Unreal Engine 5.6 C++ API: TDefaultDelete< T[]> Struct Template Reference
TDefaultDelete< T[]> Struct Template Reference
#include "UniquePtr.h"
Public Member Functions
TDefaultDelete ()=default
TDefaultDelete (const TDefaultDelete &)=default
template<typename U UE_REQUIRES>
TDefaultDelete (const TDefaultDelete< U[]> &)
~TDefaultDelete ()=default
DECLARE_INLINE_TYPE_LAYOUT (TDefaultDelete, NonVirtual)
template<typename U UE_REQUIRES>
void operator() (U *Ptr) const
TDefaultDelete & operator= (const TDefaultDelete &)=default
template<typename U UE_REQUIRES>
TDefaultDelete & operator= (const TDefaultDelete< U[]> &)
Detailed Description
template<typename T>
struct TDefaultDelete< T[]>
Definition at line 71 of file UniquePtr.h.
Constructor & Destructor Documentation
TDefaultDelete() [1/3]
template<typename T> TDefaultDelete< T[]>::TDefaultDelete () default
Referenced by TDefaultDelete(), TDefaultDelete(), operator=(), and operator=().
TDefaultDelete() [2/3]
template<typename T> TDefaultDelete< T[]>::TDefaultDelete (const TDefaultDelete< T[]> &) default
References TDefaultDelete().
~TDefaultDelete()
template<typename T> TDefaultDelete< T[]>::~TDefaultDelete () default
TDefaultDelete() [3/3]
template<typename T> template<typename U UE_REQUIRES> TDefaultDelete< T[]>::TDefaultDelete (const TDefaultDelete< U[]> &) inline
Definition at line 82 of file UniquePtr.h.
References TDefaultDelete().
Member Function Documentation
DECLARE_INLINE_TYPE_LAYOUT()
TDefaultDelete< T >::DECLARE_INLINE_TYPE_LAYOUT (TDefaultDelete< T[]> , NonVirtual)
operator()()
template<typename T> template<typename U UE_REQUIRES> void TDefaultDelete< T[]>::operator() (U * Ptr) const inline
Definition at line 99 of file UniquePtr.h.
operator=() [1/2]
template<typename T> TDefaultDelete & TDefaultDelete< T[]>::operator= (const TDefaultDelete< T[]> &) default
References TDefaultDelete().
operator=() [2/2]
template<typename T> template<typename U UE_REQUIRES> TDefaultDelete & TDefaultDelete< T[]>::operator= (const TDefaultDelete< U[]> &) inline
Definition at line 90 of file UniquePtr.h.
References TDefaultDelete().
The documentation for this struct was generated from the following file:
UniquePtr.h