Unreal Engine 5.6 C++ API: UE::CurveEditor::Private Namespace Reference
UE::CurveEditor::Private Namespace Reference
Functions
static TArray< FKeyAttributes > CopyAndInvertKeyAttributesFromBuffer (const IBufferedCurveModel &RealBuffer)
static TArray< FKeyPosition > CopyAndInvertKeyPositionsFromBuffer (const IBufferedCurveModel &RealBuffer)
template<typename InT, typename OutT>
static void InvertKeyAttributes (const InT &Input, OutT &&Output)
static FKeyAttributes InvertKeyAttributes (FKeyAttributes Attributes)
static void InvertKeyAttributes (TArrayView< FKeyAttributes > Output)
static FKeyPosition InvertKeyPosition (const FKeyPosition &KeyPosition)
template<typename InT, typename OutT>
static void InvertKeyPositions (const InT &Input, OutT &&Output)
static void InvertKeyPositions (TArrayView< FKeyPosition > Output)
static float InvertTangent (float Tangent)
Function Documentation
CopyAndInvertKeyAttributesFromBuffer()
TArray< FKeyAttributes > UE::CurveEditor::Private::CopyAndInvertKeyAttributesFromBuffer (const IBufferedCurveModel & RealBuffer) static
Definition at line 104 of file InvertedCurveModel.h.
References IBufferedCurveModel::GetKeyAttributes(), and InvertKeyAttributes().
CopyAndInvertKeyPositionsFromBuffer()
TArray< FKeyPosition > UE::CurveEditor::Private::CopyAndInvertKeyPositionsFromBuffer (const IBufferedCurveModel & RealBuffer) static
Definition at line 96 of file InvertedCurveModel.h.
References IBufferedCurveModel::GetKeyPositions(), and InvertKeyPositions().
InvertKeyAttributes() [1/3]
template<typename InT, typename OutT> void UE::CurveEditor::Private::InvertKeyAttributes (const InT & Input, OutT && Output) static
Definition at line 80 of file InvertedCurveModel.h.
References Input, InvertKeyAttributes(), and Algo::Transform().
InvertKeyAttributes() [2/3]
FKeyAttributes UE::CurveEditor::Private::InvertKeyAttributes (FKeyAttributes Attributes) static
Definition at line 66 of file InvertedCurveModel.h.
References InvertTangent().
Referenced by UE::CurveEditor::TInvertedCurveModel< TBase >::AddKeys(), CopyAndInvertKeyAttributesFromBuffer(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyAttributes(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyAttributesExcludingAutoComputed(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyAttributesIncludingAutoComputed(), InvertKeyAttributes(), InvertKeyAttributes(), and UE::CurveEditor::TInvertedCurveModel< TBase >::SetKeyAttributes().
InvertKeyAttributes() [3/3]
void UE::CurveEditor::Private::InvertKeyAttributes (TArrayView< FKeyAttributes > Output) static
Definition at line 88 of file InvertedCurveModel.h.
References InvertKeyAttributes(), and TArrayView< InElementType, InSizeType >::Num().
InvertKeyPosition()
FKeyPosition UE::CurveEditor::Private::InvertKeyPosition (const FKeyPosition & KeyPosition) static
Definition at line 38 of file InvertedCurveModel.h.
Referenced by InvertKeyPositions(), and InvertKeyPositions().
InvertKeyPositions() [1/2]
template<typename InT, typename OutT> void UE::CurveEditor::Private::InvertKeyPositions (const InT & Input, OutT && Output) static
Definition at line 44 of file InvertedCurveModel.h.
References Input, InvertKeyPosition(), and Algo::Transform().
Referenced by UE::CurveEditor::TInvertedCurveModel< TBase >::AddKeys(), CopyAndInvertKeyPositionsFromBuffer(), UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyPositions(), and UE::CurveEditor::TInvertedCurveModel< TBase >::SetKeyPositions().
InvertKeyPositions() [2/2]
void UE::CurveEditor::Private::InvertKeyPositions (TArrayView< FKeyPosition > Output) static
Definition at line 52 of file InvertedCurveModel.h.
References InvertKeyPosition(), and TArrayView< InElementType, InSizeType >::Num().
InvertTangent()
float UE::CurveEditor::Private::InvertTangent (float Tangent) static
Definition at line 60 of file InvertedCurveModel.h.
References Angle, and Tangent.
Referenced by InvertKeyAttributes().