Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitUID Struct Reference
UE::AnimNext::FTraitUID Struct Reference final
FTraitUID.
#include "TraitUID.h"
Public Member Functions
constexpr FTraitUID () noexcept
constexpr FTraitUID (FTraitUIDRaw InUID) noexcept
constexpr const TCHAR * GetTraitName () const noexcept
constexpr FTraitUIDRaw GetUID () const noexcept
constexpr bool IsValid () const noexcept
Static Public Member Functions
template<typename CharType, int32 Len>
static UE_CONSTEVAL FTraitUID MakeUID (const CharType(&InTraitName)[Len]) noexcept
Private Member Functions
constexpr FTraitUID (FTraitUIDRaw InUID, const TCHAR *InTraitName) noexcept
Private Attributes
const TCHAR * TraitName
FTraitUIDRaw UID
Static Private Attributes
static constexpr FTraitUIDRaw INVALID_UID = 0
Detailed Description
FTraitUID.
Encapsulates a trait global UID.
The whole struct is meant to be 'constexpr' to allow inlining within the assembly as constants.
Definition at line 20 of file TraitUID.h.
Constructor & Destructor Documentation
FTraitUID() [1/3]
UE::AnimNext::FTraitUID::FTraitUID () inline constexpr noexcept
Definition at line 23 of file TraitUID.h.
References INVALID_UID, and UID.
Referenced by MakeUID().
FTraitUID() [2/3]
UE::AnimNext::FTraitUID::FTraitUID (FTraitUIDRaw InUID) inline explicit constexpr noexcept
Definition at line 32 of file TraitUID.h.
FTraitUID() [3/3]
UE::AnimNext::FTraitUID::FTraitUID (FTraitUIDRaw InUID, const TCHAR * InTraitName) inline explicit constexpr private noexcept
Definition at line 62 of file TraitUID.h.
Member Function Documentation
GetTraitName()
const TCHAR * UE::AnimNext::FTraitUID::GetTraitName () const inline constexpr noexcept
Definition at line 49 of file TraitUID.h.
References TraitName.
GetUID()
FTraitUIDRaw UE::AnimNext::FTraitUID::GetUID () const inline constexpr noexcept
Definition at line 53 of file TraitUID.h.
References UID.
IsValid()
bool UE::AnimNext::FTraitUID::IsValid () const inline constexpr noexcept
Definition at line 56 of file TraitUID.h.
References INVALID_UID, and UID.
MakeUID()
template<typename CharType, int32 Len> UE_CONSTEVAL FTraitUID UE::AnimNext::FTraitUID::MakeUID (const CharType(&) InTraitName[Len]) inline static noexcept
Definition at line 42 of file TraitUID.h.
References FTraitUID(), UE::HashStringFNV1a(), MakeStringView(), and UE_CONSTEVAL.
Field Documentation
INVALID_UID
FTraitUIDRaw UE::AnimNext::FTraitUID::INVALID_UID = 0 static constexpr private
Definition at line 59 of file TraitUID.h.
Referenced by FTraitUID(), and IsValid().
TraitName
const TCHAR* UE::AnimNext::FTraitUID::TraitName private
Definition at line 73 of file TraitUID.h.
Referenced by GetTraitName().
UID
FTraitUIDRaw UE::AnimNext::FTraitUID::UID private
Definition at line 70 of file TraitUID.h.
Referenced by FTraitUID(), GetUID(), and IsValid().
The documentation for this struct was generated from the following file:
TraitUID.h