Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityGroupID Struct Reference
UE::MovieScene::FEntityGroupID Struct Reference
The component data for describing what group an entity belongs to (see UMovieSceneEntityGroupingSystem)
#include "BuiltInComponentTypes.h"
Public Member Functions
FEntityGroupID ()
FEntityGroupID (const FEntityGroupingPolicyKey InPolicyKey, int32 InGroupIndex)
bool HasGroup () const
Returns whether this component is valid (see IsValid) and if it still belongs to a group.
bool IsValid () const
Returns whether this component points to a valid grouping policy, and has a valid group.
Static Public Member Functions
static const FEntityGroupID Invalid ()
Data Fields
EEntityGroupFlags Flags = EEntityGroupFlags::None
int32 GroupIndex = INDEX_NONE
FEntityGroupingPolicyKey PolicyKey
Friends
uint32 GetTypeHash (const FEntityGroupID &GroupID)
bool operator== (const FEntityGroupID &A, const FEntityGroupID &B)
Detailed Description
The component data for describing what group an entity belongs to (see UMovieSceneEntityGroupingSystem)
Definition at line 515 of file BuiltInComponentTypes.h.
Constructor & Destructor Documentation
FEntityGroupID() [1/2]
UE::MovieScene::FEntityGroupID::FEntityGroupID () inline
Definition at line 523 of file BuiltInComponentTypes.h.
Referenced by GetTypeHash, Invalid(), and operator==.
FEntityGroupID() [2/2]
UE::MovieScene::FEntityGroupID::FEntityGroupID (const FEntityGroupingPolicyKey InPolicyKey, int32 InGroupIndex) inline
Definition at line 524 of file BuiltInComponentTypes.h.
References GroupIndex, and PolicyKey.
Member Function Documentation
HasGroup()
bool UE::MovieScene::FEntityGroupID::HasGroup () const inline
Returns whether this component is valid (see IsValid) and if it still belongs to a group.
If the entity was removed from its group, the GroupIndex would still be valid, but we would have set Flags to RemovedFromGroup. This lets downstream systems still know what group the entity used to be part of, for their own book-keeping.
Definition at line 540 of file BuiltInComponentTypes.h.
References EnumHasAnyFlags(), Flags, GroupIndex, INDEX_NONE, PolicyKey, and UE::MovieScene::RemovedFromGroup.
Invalid()
const FEntityGroupID UE::MovieScene::FEntityGroupID::Invalid () inline static
Definition at line 517 of file BuiltInComponentTypes.h.
References FEntityGroupID().
IsValid()
bool UE::MovieScene::FEntityGroupID::IsValid () const inline
Returns whether this component points to a valid grouping policy, and has a valid group.
Definition at line 529 of file BuiltInComponentTypes.h.
References GroupIndex, INDEX_NONE, and PolicyKey.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FEntityGroupID & GroupID) friend
Definition at line 545 of file BuiltInComponentTypes.h.
References FEntityGroupID(), GetTypeHash(), GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
operator==
bool operator== (const FEntityGroupID & A, const FEntityGroupID & B) friend
Definition at line 550 of file BuiltInComponentTypes.h.
References FEntityGroupID(), A, and B.
Field Documentation
Flags
EEntityGroupFlags UE::MovieScene::FEntityGroupID::Flags = EEntityGroupFlags::None
Definition at line 521 of file BuiltInComponentTypes.h.
Referenced by HasGroup().
GroupIndex
int32 UE::MovieScene::FEntityGroupID::GroupIndex = INDEX_NONE
Definition at line 520 of file BuiltInComponentTypes.h.
Referenced by FEntityGroupID(), HasGroup(), and IsValid().
PolicyKey
FEntityGroupingPolicyKey UE::MovieScene::FEntityGroupID::PolicyKey
Definition at line 519 of file BuiltInComponentTypes.h.
Referenced by FEntityGroupID(), HasGroup(), and IsValid().
The documentation for this struct was generated from the following file:
BuiltInComponentTypes.h