Unreal Engine 5.6 C++ API: IPixelStreamingHMDModule Class Reference
IPixelStreamingHMDModule Class Reference abstract
The public interface of the Pixel Streaming HMD module.
#include "IPixelStreamingHMDModule.h"
Public Member Functions
virtual EPixelStreamingXRSystem GetActiveXRSystem ()=0
Get the Active XR System.
virtual FPixelStreamingHMD * GetPixelStreamingHMD () const =0
Get the Pixel Streaming HMD object.
virtual void SetActiveXRSystem (EPixelStreamingXRSystem System)=0
Static Public Member Functions
static IPixelStreamingHMDModule & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Detailed Description
The public interface of the Pixel Streaming HMD module.
Definition at line 14 of file IPixelStreamingHMDModule.h.
Member Function Documentation
Get()
IPixelStreamingHMDModule & IPixelStreamingHMDModule::Get () inline static
Singleton-like access to this module's interface.
Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 23 of file IPixelStreamingHMDModule.h.
References FModuleManager::LoadModuleChecked().
GetActiveXRSystem()
virtual EPixelStreamingXRSystem IPixelStreamingHMDModule::GetActiveXRSystem () pure virtual
Get the Active XR System.
Returns
EPixelStreamingXRSystem
GetPixelStreamingHMD()
virtual FPixelStreamingHMD * IPixelStreamingHMDModule::GetPixelStreamingHMD () const pure virtual
Get the Pixel Streaming HMD object.
Returns
FPixelStreamingHMD*
IsAvailable()
bool IPixelStreamingHMDModule::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 33 of file IPixelStreamingHMDModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
SetActiveXRSystem()
virtual void IPixelStreamingHMDModule::SetActiveXRSystem (EPixelStreamingXRSystem System) pure virtual
The documentation for this class was generated from the following file:
IPixelStreamingHMDModule.h