Unreal Engine 5.6 C++ API: TReversePointerIterator< T > Struct Template Reference
TReversePointerIterator< T > Struct Template Reference
Pointer-like reverse iterator type.
#include "ReverseIterate.h"
Public Member Functions
constexpr TReversePointerIterator (T *InPtr UE_LIFETIMEBOUND)
Constructor for TReversePointerIterator.
constexpr bool operator!= (const TReversePointerIterator &Rhs) const
constexpr T & operator* () const
constexpr TReversePointerIterator & operator++ ()
Private Attributes
T * Ptr
Detailed Description
template<typename T>
struct TReversePointerIterator< T >
Pointer-like reverse iterator type.
Definition at line 12 of file ReverseIterate.h.
Constructor & Destructor Documentation
TReversePointerIterator()
template<typename T> TReversePointerIterator< T >::TReversePointerIterator (T *InPtr UE_LIFETIMEBOUND) inline explicit constexpr
Constructor for TReversePointerIterator.
Parameters
InPtr A pointer to the location after the element being referenced.
Note
Like std::reverse_iterator, this points to one past the element being referenced. Therefore, for an array of size N starting at P, the begin iterator should be constructed at (P+N) and the end iterator should be constructed at P.
Definition at line 26 of file ReverseIterate.h.
References Ptr, and UE_LIFETIMEBOUND.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
template<typename T> bool TReversePointerIterator< T >::operator!= (const TReversePointerIterator< T > & Rhs) const inline constexpr
Definition at line 42 of file ReverseIterate.h.
References TReversePointerIterator(), and Ptr.
operator*()
template<typename T> T & TReversePointerIterator< T >::operator* () const inline constexpr
Definition at line 31 of file ReverseIterate.h.
References Ptr.
operator++()
template<typename T> TReversePointerIterator & TReversePointerIterator< T >::operator++ () inline constexpr
Definition at line 36 of file ReverseIterate.h.
References TReversePointerIterator(), and Ptr.
Field Documentation
Ptr
template<typename T> T* TReversePointerIterator< T >::Ptr private
Definition at line 48 of file ReverseIterate.h.
Referenced by TReversePointerIterator(), operator!=(), operator*(), and operator++().
The documentation for this struct was generated from the following file:
ReverseIterate.h