Unreal Engine 5.6 C++ API: UE::Geometry::TExactIntrTriangle3Triangle3< Real > Class Template Reference
UE::Geometry::TExactIntrTriangle3Triangle3< Real > Class Template Reference
#include "ExactIntrTriangle3Triangle3.h"
Public Member Functions
TExactIntrTriangle3Triangle3 ()=default
TExactIntrTriangle3Triangle3 (TTriangle3< Real > Triangle0, TTriangle3< Real > Triangle1)
bool Test (bool &bWasCoplanar)
Static Public Member Functions
static bool FindWithoutCoplanar (const TTriangle3< Real > &Triangle0, const TTriangle3< Real > &Triangle1, TVector< Real > &OutSegA, TVector< Real > &OutSegB, bool &bWasCoplanar)
static bool TestWithoutCoplanar (const TTriangle3< Real > &Triangle0, const TTriangle3< Real > &Triangle1, bool &bWasCoplanar)
Data Fields
TTriangle3< Real > Triangle0
TTriangle3< Real > Triangle1
Static Private Member Functions
template<bool bFindSegments>
static bool FindOrTestWithoutCoplanar (const TTriangle3< Real > &Triangle0, const TTriangle3< Real > &Triangle1, TVector< Real > &OutSegA, TVector< Real > &OutSegB, bool &bWasCoplanar)
Detailed Description
template<typename Real>
class UE::Geometry::TExactIntrTriangle3Triangle3< Real >
Definition at line 15 of file ExactIntrTriangle3Triangle3.h.
Constructor & Destructor Documentation
TExactIntrTriangle3Triangle3() [1/2]
template<typename Real> UE::Geometry::TExactIntrTriangle3Triangle3< Real >::TExactIntrTriangle3Triangle3 () default
TExactIntrTriangle3Triangle3() [2/2]
template<typename Real> UE::Geometry::TExactIntrTriangle3Triangle3< Real >::TExactIntrTriangle3Triangle3 (TTriangle3< Real > Triangle0, TTriangle3< Real > Triangle1) inline
Definition at line 25 of file ExactIntrTriangle3Triangle3.h.
Member Function Documentation
FindOrTestWithoutCoplanar()
template<typename Real> template<bool bFindSegments> bool UE::Geometry::TExactIntrTriangle3Triangle3< Real >::FindOrTestWithoutCoplanar (const TTriangle3< Real > & Triangle0, const TTriangle3< Real > & Triangle1, TVector< Real > & OutSegA, TVector< Real > & OutSegB, bool & bWasCoplanar) inline static private
Definition at line 48 of file ExactIntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindWithoutCoplanar(), and UE::Geometry::TExactIntrTriangle3Triangle3< float >::TestWithoutCoplanar().
FindWithoutCoplanar()
template<typename Real> bool UE::Geometry::TExactIntrTriangle3Triangle3< Real >::FindWithoutCoplanar (const TTriangle3< Real > & Triangle0, const TTriangle3< Real > & Triangle1, TVector< Real > & OutSegA, TVector< Real > & OutSegB, bool & bWasCoplanar) inline static
Definition at line 33 of file ExactIntrTriangle3Triangle3.h.
Test()
template<typename Real> bool UE::Geometry::TExactIntrTriangle3Triangle3< Real >::Test (bool & bWasCoplanar) inline
Definition at line 28 of file ExactIntrTriangle3Triangle3.h.
TestWithoutCoplanar()
template<typename Real> bool UE::Geometry::TExactIntrTriangle3Triangle3< Real >::TestWithoutCoplanar (const TTriangle3< Real > & Triangle0, const TTriangle3< Real > & Triangle1, bool & bWasCoplanar) inline static
Definition at line 38 of file ExactIntrTriangle3Triangle3.h.
Referenced by UE::Geometry::TExactIntrTriangle3Triangle3< float >::Test().
Field Documentation
Triangle0
template<typename Real> TTriangle3<Real> UE::Geometry::TExactIntrTriangle3Triangle3< Real >::Triangle0
Definition at line 19 of file ExactIntrTriangle3Triangle3.h.
Triangle1
template<typename Real> TTriangle3<Real> UE::Geometry::TExactIntrTriangle3Triangle3< Real >::Triangle1
Definition at line 19 of file ExactIntrTriangle3Triangle3.h.
The documentation for this class was generated from the following file:
ExactIntrTriangle3Triangle3.h