Unreal Engine 5.6 C++ API: FSequencerTrackFilter Class Reference
FSequencerTrackFilter Class Reference
#include "SequencerTrackFilterBase.h"
Public Member Functions
SEQUENCER_API FSequencerTrackFilter (ISequencerTrackFilters &InOutFilterInterface, TSharedPtr< FFilterCategory > &&InCategory=nullptr)
virtual SEQUENCER_API ISequencerTrackFilters & GetFilterInterface () const override
virtual SEQUENCER_API TSubclassOf< UMovieSceneTrack > GetTrackClass () const
virtual SEQUENCER_API bool ShouldUpdateOnTrackValueChanged () const
Returns whether this filter needs reevaluating any time track values have been modified, not just tree changes.
virtual SEQUENCER_API bool SupportsSequence (UMovieSceneSequence *const InSequence) const override
Returns whether the filter supports the sequence type.
Public Member Functions inherited from FSequencerFilterBase< FSequencerTrackFilterType >
FSequencerFilterBase (ISequencerFilterBar &InOutFilterInterface, TSharedPtr< FFilterCategory > &&InCategory=nullptr)
virtual void ActiveStateChanged (const bool bInActive) override
virtual void BindCommands ()
bool CanToggleFilter () const
virtual FLinearColor GetColor () const override
virtual FText GetDefaultToolTipText () const
virtual FText GetDisplayName () const override
virtual FSlateIcon GetIcon () const
ISequencer & GetSequencer () const
virtual TSharedPtr< FUICommandInfo > GetToggleCommand () const
virtual FText GetToolTipText () const override
virtual bool IsCustomTextFilter () const
virtual bool IsInverseFilter () const override
virtual void LoadSettings (const FString &InIniFilename, const FString &InIniSection, const FString &InSettingsString) override
virtual void ModifyContextMenu (FMenuBuilder &MenuBuilder) override
virtual bool PassesFilter (FSequencerTrackFilterType InItem) const override
virtual void SaveSettings (const FString &InIniFilename, const FString &InIniSection, const FString &InSettingsString) const override
void ToggleFilter ()
Public Member Functions inherited from TSharedFromThis< FSequencerFilterBase< FSequencerTrackFilterType > >
TSharedRef< FSequencerFilterBase< FSequencerTrackFilterType >, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FSequencerFilterBase< FSequencerTrackFilterType >, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename InTrackClassType>
static bool IsSequenceTrackSupported (UMovieSceneSequence *const InSequence)
Static Public Member Functions inherited from FSequencerFilterBase< FSequencerTrackFilterType >
static FText BuildTooltipTextForCommand (const FText &InBaseText, const TSharedPtr< FUICommandInfo > &InCommand)
static bool SupportsDaySequence (UMovieSceneSequence *const InSequence)
static bool SupportsLevelSequence (UMovieSceneSequence *const InSequence)
static bool SupportsUMGSequence (UMovieSceneSequence *const InSequence)
Protected Member Functions
UMovieScene * GetFocusedGetMovieScene () const
UMovieSceneSequence * GetFocusedMovieSceneSequence () const
Protected Member Functions inherited from FSequencerFilterBase< FSequencerTrackFilterType >
void MapToggleAction (const TSharedPtr< FUICommandInfo > &InCommand)
Protected Member Functions inherited from TSharedFromThis< FSequencerFilterBase< FSequencerTrackFilterType > >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FSequencerFilterBase< FSequencerTrackFilterType > >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FSequencerFilterBase< FSequencerTrackFilterType >
ISequencerFilterBar & FilterInterface
Detailed Description
Definition at line 37 of file Filters/SequencerTrackFilterBase.h.
Constructor & Destructor Documentation
FSequencerTrackFilter()
SEQUENCER_API FSequencerTrackFilter::FSequencerTrackFilter (ISequencerTrackFilters & InOutFilterInterface, TSharedPtr< FFilterCategory > && InCategory = nullptr)
Referenced by FSequencerTrackFilter_ClassType< InClassType >::FSequencerTrackFilter_ClassType(), FSequencerTrackFilter_ComponentType< InComponentType >::FSequencerTrackFilter_ComponentType(), and FSequencerTrackFilter_ModelType< InModelType >::FSequencerTrackFilter_ModelType().
Member Function Documentation
GetFilterInterface()
virtual SEQUENCER_API ISequencerTrackFilters & FSequencerTrackFilter::GetFilterInterface () const override virtual
Reimplemented from FSequencerFilterBase< FSequencerTrackFilterType >.
Referenced by FSequencerTrackFilter_ClassType< InClassType >::PassesFilter(), and FSequencerTrackFilter_ComponentType< InComponentType >::PassesFilter().
GetFocusedGetMovieScene()
UMovieScene * FSequencerTrackFilter::GetFocusedGetMovieScene () const protected
GetFocusedMovieSceneSequence()
UMovieSceneSequence * FSequencerTrackFilter::GetFocusedMovieSceneSequence () const protected
GetTrackClass()
virtual SEQUENCER_API TSubclassOf< UMovieSceneTrack > FSequencerTrackFilter::GetTrackClass () const inline virtual
Reimplemented in FSequencerTrackFilter_ClassType< InClassType >, FSequencerTrackFilter_ClassType< UMovieSceneAudioTrack >, FSequencerTrackFilter_ClassType< UMovieSceneCameraCutTrack >, FSequencerTrackFilter_ClassType< UMovieSceneCinematicShotTrack >, FSequencerTrackFilter_ClassType< UMovieSceneDataLayerTrack >, FSequencerTrackFilter_ClassType< UMovieSceneEventTrack >, FSequencerTrackFilter_ClassType< UMovieSceneFadeTrack >, FSequencerTrackFilter_ClassType< UMovieSceneLevelVisibilityTrack >, FSequencerTrackFilter_ClassType< UMovieSceneParticleTrack >, FSequencerTrackFilter_ClassType< UMovieSceneSlomoTrack >, and FSequencerTrackFilter_ClassType< UMovieSceneSubTrack >.
Definition at line 63 of file Filters/SequencerTrackFilterBase.h.
IsSequenceTrackSupported()
template<typename InTrackClassType> bool FSequencerTrackFilter::IsSequenceTrackSupported (UMovieSceneSequence *const InSequence) inline static
Definition at line 41 of file Filters/SequencerTrackFilterBase.h.
References NotSupported, and Supported.
ShouldUpdateOnTrackValueChanged()
virtual SEQUENCER_API bool FSequencerTrackFilter::ShouldUpdateOnTrackValueChanged () const inline virtual
Returns whether this filter needs reevaluating any time track values have been modified, not just tree changes.
Reimplemented in FSequencerTrackFilter_Condition, FSequencerTrackFilter_Keyed, FSequencerTrackFilter_Modified, FSequencerTrackFilter_Selected, FSequencerTrackFilter_TimeWarp, and FSequencerTrackFilter_Unbound.
Definition at line 58 of file Filters/SequencerTrackFilterBase.h.
SupportsSequence()
virtual SEQUENCER_API bool FSequencerTrackFilter::SupportsSequence (UMovieSceneSequence *const InSequence) const override virtual
Returns whether the filter supports the sequence type.
Reimplemented from FSequencerFilterBase< FSequencerTrackFilterType >.
Reimplemented in FSequencerTrackFilter_Audio, FSequencerTrackFilter_Camera, FSequencerTrackFilter_CameraCut, FSequencerTrackFilter_CinematicShot, FSequencerTrackFilter_DataLayer, FSequencerTrackFilter_Event, FSequencerTrackFilter_Fade, FSequencerTrackFilter_Folder, FSequencerTrackFilter_LevelVisibility, FSequencerTrackFilter_Light, FSequencerTrackFilter_Particle, FSequencerTrackFilter_SkeletalMesh, FSequencerTrackFilter_Subsequence, and FSequencerTrackFilter_TimeDilation.
The documentation for this class was generated from the following file:
Filters/SequencerTrackFilterBase.h