Unreal Engine 5.6 C++ API: FCompressedAnimSequence Struct Reference
FCompressedAnimSequence Struct Reference
#include "AnimCompressionTypes.h"
Public Member Functions
FCompressedAnimSequence ()
void ClearCompressedBoneData ()
void ClearCompressedCurveData ()
SIZE_T GetMemorySize () const
int32 GetSkeletonIndexFromTrackIndex (const int32 TrackIndex) const
int32 GetTrackIndexFromSkeletonIndex (const int32 BoneIndex) const
bool IsBoneDataValid (const UAnimSequence *AnimSequence, bool bLogInformation=false) const
bool IsCurveDataValid (const UAnimSequence *AnimSequence, bool bLogInformation=false) const
bool IsValid (const UAnimSequence *AnimSequence, bool bLogInformation=false) const
void RebuildCurveIndexTable ()
void Reset ()
void SerializeCompressedData (FArchive &Ar, bool bDDCData, UObject *DataOwner, USkeleton *Skeleton, UAnimBoneCompressionSettings *BoneCompressionSettings, UAnimCurveCompressionSettings *CurveCompressionSettings, bool bCanUseBulkData=true)
UE_DEPRECATED (5.3, "Please use IndexedCurveNames.") TArray< struct FSmartName > CompressedCurveNames
UE_NONCOPYABLE (FCompressedAnimSequence) TArray< struct FTrackToSkeletonMap > CompressedTrackToSkeletonMapTable
Version of TrackToSkeletonMapTable for the compressed tracks.
Data Fields
TObjectPtr< class UAnimBoneCompressionCodec > BoneCompressionCodec
The codec used by the compressed data as determined by the bone compression settings.
TArray< uint8 > CompressedByteStream
ByteStream for compressed animation data.
TArray< uint8 > CompressedCurveByteStream
TUniquePtr< ICompressedAnimData > CompressedDataStructure
TArray< FRawAnimSequenceTrack > CompressedRawData
int32 CompressedRawDataSize
TObjectPtr< class UAnimCurveCompressionCodec > CurveCompressionCodec
The codec used by the compressed data as determined by the curve compression settings.
TArray< FAnimCompressedCurveIndexedName > IndexedCurveNames
Curve names for each compressed curve track, indices sorted by FName.
FByteBulkData OptionalBulk
FName OwnerName
Detailed Description
Definition at line 774 of file AnimCompressionTypes.h.
Constructor & Destructor Documentation
FCompressedAnimSequence()
FCompressedAnimSequence::FCompressedAnimSequence () inline
Definition at line 824 of file AnimCompressionTypes.h.
References BoneCompressionCodec, CompressedRawDataSize, and CurveCompressionCodec.
Referenced by UE_NONCOPYABLE().
Member Function Documentation
ClearCompressedBoneData()
void FCompressedAnimSequence::ClearCompressedBoneData ()
ClearCompressedCurveData()
void FCompressedAnimSequence::ClearCompressedCurveData ()
GetMemorySize()
SIZE_T FCompressedAnimSequence::GetMemorySize () const
GetSkeletonIndexFromTrackIndex()
int32 FCompressedAnimSequence::GetSkeletonIndexFromTrackIndex (const int32 TrackIndex) const inline
Definition at line 834 of file AnimCompressionTypes.h.
GetTrackIndexFromSkeletonIndex()
int32 FCompressedAnimSequence::GetTrackIndexFromSkeletonIndex (const int32 BoneIndex) const inline
Definition at line 839 of file AnimCompressionTypes.h.
References TArray< InElementType, InAllocatorType >::IndexOfByPredicate().
IsBoneDataValid()
bool FCompressedAnimSequence::IsBoneDataValid (const UAnimSequence * AnimSequence, bool bLogInformation = false) const
IsCurveDataValid()
bool FCompressedAnimSequence::IsCurveDataValid (const UAnimSequence * AnimSequence, bool bLogInformation = false) const
IsValid()
bool FCompressedAnimSequence::IsValid (const UAnimSequence * AnimSequence, bool bLogInformation = false) const
RebuildCurveIndexTable()
void FCompressedAnimSequence::RebuildCurveIndexTable ()
Reset()
void FCompressedAnimSequence::Reset ()
SerializeCompressedData()
void FCompressedAnimSequence::SerializeCompressedData (FArchive & Ar, bool bDDCData, UObject * DataOwner, USkeleton * Skeleton, UAnimBoneCompressionSettings * BoneCompressionSettings, UAnimCurveCompressionSettings * CurveCompressionSettings, bool bCanUseBulkData = true)
References Ar, and Skeleton.
UE_DEPRECATED()
FCompressedAnimSequence::UE_DEPRECATED (5. 3, "Please use IndexedCurveNames.")
UE_NONCOPYABLE()
FCompressedAnimSequence::UE_NONCOPYABLE (FCompressedAnimSequence)
Version of TrackToSkeletonMapTable for the compressed tracks.
Due to baking additive data we can end up with a different amount of tracks to the original raw animation and so we must index into the compressed data using this
References FCompressedAnimSequence().
Field Documentation
BoneCompressionCodec
TObjectPtr<class UAnimBoneCompressionCodec> FCompressedAnimSequence::BoneCompressionCodec
The codec used by the compressed data as determined by the bone compression settings.
Definition at line 810 of file AnimCompressionTypes.h.
Referenced by FCompressedAnimSequence().
CompressedByteStream
TArray<uint8> FCompressedAnimSequence::CompressedByteStream
ByteStream for compressed animation data.
The memory layout is dependent on the algorithm used to compress the anim sequence.
Definition at line 797 of file AnimCompressionTypes.h.
CompressedCurveByteStream
TArray<uint8> FCompressedAnimSequence::CompressedCurveByteStream
Definition at line 804 of file AnimCompressionTypes.h.
CompressedDataStructure
TUniquePtr<ICompressedAnimData> FCompressedAnimSequence::CompressedDataStructure
Definition at line 807 of file AnimCompressionTypes.h.
CompressedRawData
TArray<FRawAnimSequenceTrack> FCompressedAnimSequence::CompressedRawData
Definition at line 820 of file AnimCompressionTypes.h.
CompressedRawDataSize
int32 FCompressedAnimSequence::CompressedRawDataSize
Definition at line 816 of file AnimCompressionTypes.h.
Referenced by FCompressedAnimSequence().
CurveCompressionCodec
TObjectPtr<class UAnimCurveCompressionCodec> FCompressedAnimSequence::CurveCompressionCodec
The codec used by the compressed data as determined by the curve compression settings.
Definition at line 813 of file AnimCompressionTypes.h.
Referenced by FCompressedAnimSequence().
IndexedCurveNames
TArray<FAnimCompressedCurveIndexedName> FCompressedAnimSequence::IndexedCurveNames
Curve names for each compressed curve track, indices sorted by FName.
Definition at line 790 of file AnimCompressionTypes.h.
OptionalBulk
FByteBulkData FCompressedAnimSequence::OptionalBulk
Definition at line 798 of file AnimCompressionTypes.h.
OwnerName
FName FCompressedAnimSequence::OwnerName
Definition at line 821 of file AnimCompressionTypes.h.
The documentation for this struct was generated from the following file:
AnimCompressionTypes.h