Unreal Engine 5.6 C++ API: TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Types
using FMethodPtr = typename TMemFunPtrType<bConst, UserClass, RetValType(ParamTypes..., VarTypes...)>::Type
Public Member Functions
template<typename... InVarTypes>
TBaseUObjectMethodDelegateInstance (UserClass *InUserObject, FMethodPtr InMethodPtr, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst InUserObject) const final
bool IsCompactable () const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Protected Attributes
FMethodPtr MethodPtr
TWeakObjectPtr< UserClass > UserObject
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
Detailed Description
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes>
class TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >
Definition at line 561 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 565 of file DelegateInstancesImpl.h.
FMethodPtr
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::FMethodPtr = typename TMemFunPtrType<bConst, UserClass, RetValType(ParamTypes..., VarTypes...)>::Type
Definition at line 570 of file DelegateInstancesImpl.h.
Super
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 564 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseUObjectMethodDelegateInstance()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> template<typename... InVarTypes> TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseUObjectMethodDelegateInstance (UserClass * InUserObject, FMethodPtr InMethodPtr, InVarTypes &&... Vars) inline explicit
Definition at line 573 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), MethodPtr, and UserObject.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 648 of file DelegateInstancesImpl.h.
References TBaseUObjectMethodDelegateInstance().
CreateCopy() [2/3]
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 653 of file DelegateInstancesImpl.h.
References TBaseUObjectMethodDelegateInstance().
CreateCopy() [3/3]
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 643 of file DelegateInstancesImpl.h.
References TBaseUObjectMethodDelegateInstance().
Execute()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> RetValType TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 658 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), MethodPtr, Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObject.
ExecuteIfSafe()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 675 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), IsInGameThread(), MethodPtr, Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObject.
GetBoundProgramCounterForTimerManager()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> uint64 TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 604 of file DelegateInstancesImpl.h.
References MethodPtr.
GetObjectForTimerManager()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> const void * TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 599 of file DelegateInstancesImpl.h.
References UserObject.
GetUObject()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UObject * TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetUObject () const inline final
Definition at line 594 of file DelegateInstancesImpl.h.
References UserObject.
HasSameObject()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::HasSameObject (FDelegateUserObjectConst InUserObject) const inline final
Definition at line 614 of file DelegateInstancesImpl.h.
References UserObject.
IsCompactable()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsCompactable () const inline final
Definition at line 625 of file DelegateInstancesImpl.h.
References UserObject.
IsSafeToExecute()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 634 of file DelegateInstancesImpl.h.
References UserObject.
Field Documentation
MethodPtr
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> FMethodPtr TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::MethodPtr protected
Definition at line 702 of file DelegateInstancesImpl.h.
Referenced by TBaseUObjectMethodDelegateInstance(), Execute(), ExecuteIfSafe(), and GetBoundProgramCounterForTimerManager().
UserObject
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> TWeakObjectPtr<UserClass> TBaseUObjectMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::UserObject protected
Definition at line 699 of file DelegateInstancesImpl.h.
Referenced by TBaseUObjectMethodDelegateInstance(), Execute(), ExecuteIfSafe(), GetObjectForTimerManager(), GetUObject(), HasSameObject(), IsCompactable(), and IsSafeToExecute().
The documentation for this class was generated from the following file:
DelegateInstancesImpl.h