Unreal Engine 5.6 C++ API: UE::MovieScene::FSequenceInstance Struct Reference
UE::MovieScene::FSequenceInstance Struct Reference
A sequence instance represents a specific instance of a currently playing sequence, either as a top-level sequence in an IMovieScenePlayer, or as a sub sequence.
#include "MovieSceneSequenceInstance.h"
Public Member Functions
FSequenceInstance (const FSequenceInstance &)=delete
Sequence instances are not copyable.
MOVIESCENE_API FSequenceInstance (FSequenceInstance &&)
Move constructors implemented in cpp to avoid includes for TUniquePtr.
MOVIESCENE_API FSequenceInstance (TSharedRef< FSharedPlaybackState > PlaybackState)
Constructor for top level sequences.
MOVIESCENE_API FSequenceInstance (TSharedRef< FSharedPlaybackState > PlaybackState, FInstanceHandle ThisInstanceHandle, FInstanceHandle InParentInstanceHandle, FMovieSceneSequenceID InSequenceID)
Constructor for sub sequences.
MOVIESCENE_API ~FSequenceInstance ()
Destructor.
MOVIESCENE_API bool CanFinishImmediately () const
Returns whether this instance can be finished immediately without any last update.
MOVIESCENE_API bool ConditionalRecompile ()
Conditionally recompile this sequence if it needs to be.
MOVIESCENE_API void DestroyImmediately ()
Destroy this sequence instance immediately - Finish must previously have been called.
MOVIESCENE_API void DissectContext (const FMovieSceneContext &Context, TArray< TRange< FFrameTime > > &OutDissections)
Called only for top-level sequence instances before any updates to it with the specified context.
MOVIESCENE_API bool EvaluateCondition (const FGuid &BindingID, const FMovieSceneSequenceID &SequenceID, const UMovieSceneCondition *Condition, UObject *ConditionOwnerObject) const
MOVIESCENE_API void FindEntities (UObject *Owner, TArray< FMovieSceneEntityID > &OutEntityIDs) const
Attempt to locate all entities given their owner.
MOVIESCENE_API FMovieSceneEntityID FindEntity (UObject *Owner, uint32 EntityID) const
Attempt to locate an entity given its owner and ID.
MOVIESCENE_API FInstanceHandle FindSubInstance (FMovieSceneSequenceID SequenceID) const
Attempt to locate a sub instance based on its sequence ID.
MOVIESCENE_API void Finish ()
Mark this instance as finished, causing all its entities to be unlinked and the instance to become inactive at the end of the next update.
const FMovieSceneContext & GetContext () const
Get the evaluation context for the current frame.
FInstanceHandle GetInstanceHandle () const
Gets the handle to this instance.
const FMovieSceneTrackEvaluator * GetLegacyEvaluator () const
Retrieve the legacy evaluator for this sequence, if it is available (may return nullptr)
FInstanceHandle GetParentInstanceHandle () const
Get a handle to the parent instance for this sequence instance, or an invalid handle if it is a root instance.
FRootInstanceHandle GetRootInstanceHandle () const
Get a handle to the root instance for this sub sequence instance.
FMovieSceneSequenceID GetSequenceID () const
Retrieve the SequenceID for this instance.
uint16 GetSerialNumber () const
Get the serial number for this sequence instance that it was created with on construction.
TSharedRef< FSharedPlaybackState > GetSharedPlaybackState () const
Retrieve the shared playback state for this instance's hierarchy.
MOVIESCENE_API FSubSequencePath GetSubSequencePath () const
Retrieve a path for this sequence instance back to the root.
ESequenceInstanceUpdateFlags GetUpdateFlags () const
Retrieve this sequence's update flags.
bool HasEverUpdated () const
Check whether this sequence instance has ever been updated or not.
bool HasFinished () const
Check whether this sequence instance has finished evaluating.
MOVIESCENE_API void Initialize ()
Finish initializing this sequence instance.
MOVIESCENE_API void InvalidateCachedData (ESequenceInstanceInvalidationType InvalidationType=ESequenceInstanceInvalidationType::All)
Invalidate any cached data that may be being used for evaluation due to a change in the source asset data.
bool IsRootSequence () const
Returns whether this instance is the root instance.
bool IsSubSequence () const
Returns whether this instance is a sub sequence.
FSequenceInstance & operator= (const FSequenceInstance &)=delete
MOVIESCENE_API FSequenceInstance & operator= (FSequenceInstance &&)
MOVIESCENE_API void OverrideRootSequence (FMovieSceneSequenceID NewRootSequenceID)
Called to override the simulated root sequence ID for this instance.
MOVIESCENE_API void PostEvaluation ()
Called when this sequence instance has been evaluated in order for it to do any clean-up or other post-update work.
MOVIESCENE_API void PreEvaluation ()
Called when this instance has been queued for evaluation in order for it to do any pre-work setup.
MOVIESCENE_API void RunLegacyTrackTemplates ()
Called to run legacy track templates.
void SetContext (const FMovieSceneContext &InContext)
Get the evaluation context for the current frame.
void SetFinished (bool bInFinished)
Indicate that this sequence instance has finished evaluation and should remove its entities.
MOVIESCENE_API void Start (const FMovieSceneContext &InContext)
Called for root level instances that have either never evaluated, or have previously finished evaluating.
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") bool CanFinishImmediately(UMovieSceneEntitySystemLinker *Linker) const
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") bool ConditionalRecompile(UMovieSceneEntitySystemLinker *Linker)
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void DestroyImmediately(UMovieSceneEntitySystemLinker *Linker)
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void DissectContext(UMovieSceneEntitySystemLinker *Linker
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void Finish(UMovieSceneEntitySystemLinker *Linker)
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void InvalidateCachedData(UMovieSceneEntitySystemLinker *Linker)
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void OverrideRootSequence(UMovieSceneEntitySystemLinker *Linker
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void PostEvaluation(UMovieSceneEntitySystemLinker *Linker)
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void PreEvaluation(UMovieSceneEntitySystemLinker *Linker)
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void Start(UMovieSceneEntitySystemLinker *Linker
UE_DEPRECATED (5.4, "Please use the version of this method without a Linker parameter") void Update(UMovieSceneEntitySystemLinker *Linker
UE_DEPRECATED (5.5, "The player interface is now optional and will be deprecated in a future relase. Please use FPlayerIndexPlaybackCapability::GetPlayer()") MOVIESCENE_API IMovieScenePlayer *GetPlayer() const
Retrieve the IMovieScenePlayer that is playing back the top level sequence for this instance.
UE_DEPRECATED (5.5, "The player interface is now optional and will be deprecated in a future relase. Please use FPlayerIndexPlaybackCapability::GetPlayerIndex()") MOVIESCENE_API uint16 GetPlayerIndex() const
Retrieve the IMovieScenePlayer's unique index.
MOVIESCENE_API void Update (const FMovieSceneContext &InContext)
Called after dissection for root level instances in order for this sequence instacne to update any entities it needs for evaluation.
Data Fields
const FMovieSceneContext & Context
const FMovieSceneContext & InContext
FEntityLedger Ledger
Ledger that tracks all currently instantiated entities for this instance.
FMovieSceneSequenceID NewRootSequenceID
const FMovieSceneContext TArray< TRange< FFrameTime > > & OutDissections
Private Member Functions
void InitializeLegacyEvaluator ()
void InitializeLegacyPlayer ()
Private Attributes
bool bFinished: 1
Flag that is set when this sequence has or (will be) finished.
bool bHasEverUpdated: 1
Flag that is set if this sequence has ever updated.
bool bInitialized: 1
Flag that indicates whether this instance was initialized.
FMovieSceneContext Context
FInstanceHandle InstanceHandle
This instance's handle.
TUniquePtr< FMovieSceneTrackEvaluator > LegacyEvaluator
For top-level sequences only - legacy track template evaluator for the entire sequence.
TUniquePtr< FMovieSceneLegacyPlayer > LegacyPlayer
For top-level sequences only - legacy player.
FInstanceHandle ParentInstanceHandle
This instance's parent handle.
FRootInstanceHandle RootInstanceHandle
This instance's root handle, if it is a sub sequence.
FMovieSceneSequenceID RootOverrideSequenceID
When SequenceID != MovieSceneSequenceID::Root, specifies an ID to override as a simulated root.
FString RootSequenceName
Name of the root sequence.
FMovieSceneSequenceID SequenceID
This sequence instances sequence ID, or MovieSceneSequenceID::Root for top-level sequences.
TUniquePtr< ISequenceUpdater > SequenceUpdater
For top-level sequences only - interface for either a flat or hierarchical entity updater.
TSharedRef< FSharedPlaybackState > SharedPlaybackState
Playback state shared by the entire sequence hierarchy.
ESequenceInstanceUpdateFlags UpdateFlags
Cached update flags denoting what kinds of updates are required by this instance.
TUniquePtr< FCompiledDataVolatilityManager > VolatilityManager
For top-level sequences only - a utility class that is used to ensure that volatile sequences are up to date.
Friends
struct FScopedVolatilityManagerSuppression
Detailed Description
A sequence instance represents a specific instance of a currently playing sequence, either as a top-level sequence in an IMovieScenePlayer, or as a sub sequence.
Any given sequence asset may have any number of instances created for it at any given time depending on how many times it is referenced by playing sequences
Definition at line 69 of file MovieSceneSequenceInstance.h.
Constructor & Destructor Documentation
FSequenceInstance() [1/4]
MOVIESCENE_API UE::MovieScene::FSequenceInstance::FSequenceInstance (TSharedRef< FSharedPlaybackState > PlaybackState) explicit
Constructor for top level sequences.
Referenced by FSequenceInstance(), FSequenceInstance(), operator=(), and operator=().
FSequenceInstance() [2/4]
MOVIESCENE_API UE::MovieScene::FSequenceInstance::FSequenceInstance (TSharedRef< FSharedPlaybackState > PlaybackState, FInstanceHandle ThisInstanceHandle, FInstanceHandle InParentInstanceHandle, FMovieSceneSequenceID InSequenceID) explicit
Constructor for sub sequences.
~FSequenceInstance()
MOVIESCENE_API UE::MovieScene::FSequenceInstance::~FSequenceInstance ()
Destructor.
FSequenceInstance() [3/4]
UE::MovieScene::FSequenceInstance::FSequenceInstance (const FSequenceInstance &) delete
Sequence instances are not copyable.
References FSequenceInstance().
FSequenceInstance() [4/4]
MOVIESCENE_API UE::MovieScene::FSequenceInstance::FSequenceInstance (FSequenceInstance &&)
Move constructors implemented in cpp to avoid includes for TUniquePtr.
References FSequenceInstance().
Member Function Documentation
CanFinishImmediately()
MOVIESCENE_API bool UE::MovieScene::FSequenceInstance::CanFinishImmediately () const
Returns whether this instance can be finished immediately without any last update.
Parameters
Linker The linker that owns this sequence instance
Returns
Whether the instance can be finished immediately
Referenced by UE_DEPRECATED().
ConditionalRecompile()
MOVIESCENE_API bool UE::MovieScene::FSequenceInstance::ConditionalRecompile ()
Conditionally recompile this sequence if it needs to be.
Parameters
Linker The linker that owns this sequence instance
Returns
true if a recompile has ocurred, false otherwise
Referenced by UE_DEPRECATED().
DestroyImmediately()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::DestroyImmediately ()
Destroy this sequence instance immediately - Finish must previously have been called.
Referenced by UE_DEPRECATED().
DissectContext()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::DissectContext (const FMovieSceneContext & Context, TArray< TRange< FFrameTime > > & OutDissections)
Called only for top-level sequence instances before any updates to it with the specified context.
This allows the sequence an opportunity to dissect the context into a series of distinct evaluations to force determinism.
Parameters
Linker The linker that owns this sequence instance
Context The overall context that this sequence instance is being evaluated with
OutDissections An array to populate with dissected time ranges that should be evaluated separately, in order.
References Context, and OutDissections.
EvaluateCondition()
MOVIESCENE_API bool UE::MovieScene::FSequenceInstance::EvaluateCondition (const FGuid & BindingID, const FMovieSceneSequenceID & SequenceID, const UMovieSceneCondition * Condition, UObject * ConditionOwnerObject) const
References SequenceID.
FindEntities()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::FindEntities (UObject * Owner, TArray< FMovieSceneEntityID > & OutEntityIDs) const
Attempt to locate all entities given their owner.
References Owner.
FindEntity()
MOVIESCENE_API FMovieSceneEntityID UE::MovieScene::FSequenceInstance::FindEntity (UObject * Owner, uint32 EntityID) const
Attempt to locate an entity given its owner and ID.
References Owner.
FindSubInstance()
MOVIESCENE_API FInstanceHandle UE::MovieScene::FSequenceInstance::FindSubInstance (FMovieSceneSequenceID SequenceID) const
Attempt to locate a sub instance based on its sequence ID.
References SequenceID.
Finish()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::Finish ()
Mark this instance as finished, causing all its entities to be unlinked and the instance to become inactive at the end of the next update.
Parameters
Linker The linker that owns this sequence instance
Referenced by UE_DEPRECATED().
GetContext()
const FMovieSceneContext & UE::MovieScene::FSequenceInstance::GetContext () const inline
Get the evaluation context for the current frame.
Returns
This sequence instance's playback context
Definition at line 183 of file MovieSceneSequenceInstance.h.
References Context.
Referenced by UE::MovieScene::FInstanceRegistry::GetContext().
GetInstanceHandle()
FInstanceHandle UE::MovieScene::FSequenceInstance::GetInstanceHandle () const inline
Gets the handle to this instance.
Definition at line 191 of file MovieSceneSequenceInstance.h.
References InstanceHandle.
GetLegacyEvaluator()
const FMovieSceneTrackEvaluator * UE::MovieScene::FSequenceInstance::GetLegacyEvaluator () const inline
Retrieve the legacy evaluator for this sequence, if it is available (may return nullptr)
Definition at line 286 of file MovieSceneSequenceInstance.h.
References LegacyEvaluator.
GetParentInstanceHandle()
FInstanceHandle UE::MovieScene::FSequenceInstance::GetParentInstanceHandle () const inline
Get a handle to the parent instance for this sequence instance, or an invalid handle if it is a root instance.
Returns
A a handle to the parent instance for this sequence instance, or an invalid handle if it is a root instance
Definition at line 211 of file MovieSceneSequenceInstance.h.
References ParentInstanceHandle.
GetRootInstanceHandle()
FRootInstanceHandle UE::MovieScene::FSequenceInstance::GetRootInstanceHandle () const inline
Get a handle to the root instance for this sub sequence instance.
Returns
A handle to the root sequence instance for this sub sequence, or a handle to this sequence instance if it is not a sub sequence
Definition at line 201 of file MovieSceneSequenceInstance.h.
References RootInstanceHandle.
GetSequenceID()
FMovieSceneSequenceID UE::MovieScene::FSequenceInstance::GetSequenceID () const inline
Retrieve the SequenceID for this instance.
Returns
This sequence instance's SequenceID within the root-sequences hierachy, or MovieSceneSequenceID::Root for root sequence instances.
Definition at line 173 of file MovieSceneSequenceInstance.h.
References GetSequenceID(), and SequenceID.
Referenced by GetSequenceID().
GetSerialNumber()
uint16 UE::MovieScene::FSequenceInstance::GetSerialNumber () const inline
Get the serial number for this sequence instance that it was created with on construction.
Returns
The serial number of this instance that is used to check that handles to it are still valid.
Definition at line 237 of file MovieSceneSequenceInstance.h.
References InstanceHandle.
GetSharedPlaybackState()
TSharedRef< FSharedPlaybackState > UE::MovieScene::FSequenceInstance::GetSharedPlaybackState () const inline
Retrieve the shared playback state for this instance's hierarchy.
Definition at line 149 of file MovieSceneSequenceInstance.h.
References SharedPlaybackState.
GetSubSequencePath()
MOVIESCENE_API FSubSequencePath UE::MovieScene::FSequenceInstance::GetSubSequencePath () const
Retrieve a path for this sequence instance back to the root.
GetUpdateFlags()
ESequenceInstanceUpdateFlags UE::MovieScene::FSequenceInstance::GetUpdateFlags () const inline
Retrieve this sequence's update flags.
Definition at line 263 of file MovieSceneSequenceInstance.h.
References UpdateFlags.
HasEverUpdated()
bool UE::MovieScene::FSequenceInstance::HasEverUpdated () const inline
Check whether this sequence instance has ever been updated or not.
Definition at line 255 of file MovieSceneSequenceInstance.h.
References bHasEverUpdated.
HasFinished()
bool UE::MovieScene::FSequenceInstance::HasFinished () const inline
Check whether this sequence instance has finished evaluating.
Returns
True if this sequence has finished evaluation, false otherwise
Definition at line 247 of file MovieSceneSequenceInstance.h.
References bFinished.
Initialize()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::Initialize ()
Finish initializing this sequence instance.
InitializeLegacyEvaluator()
void UE::MovieScene::FSequenceInstance::InitializeLegacyEvaluator () private
References InitializeLegacyEvaluator().
Referenced by InitializeLegacyEvaluator().
InitializeLegacyPlayer()
void UE::MovieScene::FSequenceInstance::InitializeLegacyPlayer () private
References InitializeLegacyPlayer().
Referenced by InitializeLegacyPlayer().
InvalidateCachedData()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::InvalidateCachedData (ESequenceInstanceInvalidationType InvalidationType = ESequenceInstanceInvalidationType::All)
Invalidate any cached data that may be being used for evaluation due to a change in the source asset data.
References UE::MovieScene::All.
Referenced by UE_DEPRECATED().
IsRootSequence()
bool UE::MovieScene::FSequenceInstance::IsRootSequence () const inline
Returns whether this instance is the root instance.
Definition at line 219 of file MovieSceneSequenceInstance.h.
References InstanceHandle, and RootInstanceHandle.
IsSubSequence()
bool UE::MovieScene::FSequenceInstance::IsSubSequence () const inline
Returns whether this instance is a sub sequence.
Definition at line 227 of file MovieSceneSequenceInstance.h.
References InstanceHandle, and RootInstanceHandle.
operator=() [1/2]
FSequenceInstance & UE::MovieScene::FSequenceInstance::operator= (const FSequenceInstance &) delete
References FSequenceInstance().
operator=() [2/2]
MOVIESCENE_API FSequenceInstance & UE::MovieScene::FSequenceInstance::operator= (FSequenceInstance &&)
References FSequenceInstance().
OverrideRootSequence()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::OverrideRootSequence (FMovieSceneSequenceID NewRootSequenceID)
Called to override the simulated root sequence ID for this instance.
Only valid for IsRootSequence() instances.
References NewRootSequenceID.
PostEvaluation()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::PostEvaluation ()
Called when this sequence instance has been evaluated in order for it to do any clean-up or other post-update work.
Parameters
Linker The linker that owns this sequence instance
Referenced by UE_DEPRECATED().
PreEvaluation()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::PreEvaluation ()
Called when this instance has been queued for evaluation in order for it to do any pre-work setup.
Parameters
Linker The linker that owns this sequence instance
Referenced by UE_DEPRECATED().
RunLegacyTrackTemplates()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::RunLegacyTrackTemplates ()
Called to run legacy track templates.
SetContext()
void UE::MovieScene::FSequenceInstance::SetContext (const FMovieSceneContext & InContext) inline
Get the evaluation context for the current frame.
Returns
This sequence instance's playback context
Definition at line 303 of file MovieSceneSequenceInstance.h.
References Context, and InContext.
SetFinished()
void UE::MovieScene::FSequenceInstance::SetFinished (bool bInFinished) inline
Indicate that this sequence instance has finished evaluation and should remove its entities.
Definition at line 311 of file MovieSceneSequenceInstance.h.
References bFinished.
Start()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::Start (const FMovieSceneContext & InContext)
Called for root level instances that have either never evaluated, or have previously finished evaluating.
Parameters
Linker The linker that owns this sequence instance
InContext The context that this sequence instance is to be evaluated with
References InContext.
UE_DEPRECATED() [1/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter") const
References CanFinishImmediately(), and UE_DEPRECATED().
UE_DEPRECATED() [2/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References bool, and ConditionalRecompile().
UE_DEPRECATED() [3/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References DestroyImmediately(), and UE_DEPRECATED().
UE_DEPRECATED() [4/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References UE_DEPRECATED().
UE_DEPRECATED() [5/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References Finish(), and UE_DEPRECATED().
UE_DEPRECATED() [6/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References InvalidateCachedData(), and UE_DEPRECATED().
UE_DEPRECATED() [7/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References UE_DEPRECATED().
UE_DEPRECATED() [8/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References PostEvaluation(), and UE_DEPRECATED().
UE_DEPRECATED() [9/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References PreEvaluation(), and UE_DEPRECATED().
UE_DEPRECATED() [10/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References UE_DEPRECATED().
UE_DEPRECATED() [11/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 4, "Please use the version of this method without a Linker parameter")
References InContext, UE_DEPRECATED(), and Update().
UE_DEPRECATED() [12/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 5, "The player interface is now optional and will be deprecated in a future relase. Please use FPlayerIndexPlaybackCapability::GetPlayer()") const
Retrieve the IMovieScenePlayer that is playing back the top level sequence for this instance.
Returns
A pointer to this instance's player
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [13/13]
UE::MovieScene::FSequenceInstance::UE_DEPRECATED (5. 5, "The player interface is now optional and will be deprecated in a future relase. Please use FPlayerIndexPlaybackCapability::GetPlayerIndex()") const
Retrieve the IMovieScenePlayer's unique index.
References UE_DEPRECATED().
Update()
MOVIESCENE_API void UE::MovieScene::FSequenceInstance::Update (const FMovieSceneContext & InContext)
Called after dissection for root level instances in order for this sequence instacne to update any entities it needs for evaluation.
Parameters
Linker The linker that owns this sequence instance
InContext The (potentially dissected) context that this sequence instance is to be evaluated with
References InContext.
Referenced by UE_DEPRECATED().
Friends And Related Symbol Documentation
FScopedVolatilityManagerSuppression
friend struct FScopedVolatilityManagerSuppression friend
Definition at line 428 of file MovieSceneSequenceInstance.h.
References FScopedVolatilityManagerSuppression.
Referenced by FScopedVolatilityManagerSuppression.
Field Documentation
bFinished
bool UE::MovieScene::FSequenceInstance::bFinished private
Flag that is set when this sequence has or (will be) finished.
Definition at line 424 of file MovieSceneSequenceInstance.h.
Referenced by HasFinished(), and SetFinished().
bHasEverUpdated
bool UE::MovieScene::FSequenceInstance::bHasEverUpdated private
Flag that is set if this sequence has ever updated.
Definition at line 426 of file MovieSceneSequenceInstance.h.
Referenced by HasEverUpdated().
bInitialized
bool UE::MovieScene::FSequenceInstance::bInitialized private
Flag that indicates whether this instance was initialized.
Definition at line 422 of file MovieSceneSequenceInstance.h.
Context [1/2]
const FMovieSceneContext& UE::MovieScene::FSequenceInstance::Context
Definition at line 363 of file MovieSceneSequenceInstance.h.
Referenced by DissectContext(), GetContext(), and SetContext().
Context [2/2]
FMovieSceneContext UE::MovieScene::FSequenceInstance::Context private
Definition at line 390 of file MovieSceneSequenceInstance.h.
InContext
const FMovieSceneContext & UE::MovieScene::FSequenceInstance::InContext
Definition at line 365 of file MovieSceneSequenceInstance.h.
Referenced by SetContext(), Start(), UE_DEPRECATED(), and Update().
InstanceHandle
FInstanceHandle UE::MovieScene::FSequenceInstance::InstanceHandle private
This instance's handle.
Definition at line 416 of file MovieSceneSequenceInstance.h.
Referenced by GetInstanceHandle(), GetSerialNumber(), IsRootSequence(), and IsSubSequence().
Ledger
FEntityLedger UE::MovieScene::FSequenceInstance::Ledger
Ledger that tracks all currently instantiated entities for this instance.
Definition at line 72 of file MovieSceneSequenceInstance.h.
LegacyEvaluator
TUniquePtr<FMovieSceneTrackEvaluator> UE::MovieScene::FSequenceInstance::LegacyEvaluator private
For top-level sequences only - legacy track template evaluator for the entire sequence.
Definition at line 398 of file MovieSceneSequenceInstance.h.
Referenced by GetLegacyEvaluator().
LegacyPlayer
TUniquePtr<FMovieSceneLegacyPlayer> UE::MovieScene::FSequenceInstance::LegacyPlayer private
For top-level sequences only - legacy player.
Definition at line 400 of file MovieSceneSequenceInstance.h.
NewRootSequenceID
FMovieSceneSequenceID UE::MovieScene::FSequenceInstance::NewRootSequenceID
Definition at line 381 of file MovieSceneSequenceInstance.h.
Referenced by OverrideRootSequence().
OutDissections
const FMovieSceneContext TArray<TRange<FFrameTime> >& UE::MovieScene::FSequenceInstance::OutDissections
Definition at line 363 of file MovieSceneSequenceInstance.h.
Referenced by DissectContext().
ParentInstanceHandle
FInstanceHandle UE::MovieScene::FSequenceInstance::ParentInstanceHandle private
This instance's parent handle.
Definition at line 418 of file MovieSceneSequenceInstance.h.
Referenced by GetParentInstanceHandle().
RootInstanceHandle
FRootInstanceHandle UE::MovieScene::FSequenceInstance::RootInstanceHandle private
This instance's root handle, if it is a sub sequence.
Definition at line 420 of file MovieSceneSequenceInstance.h.
Referenced by GetRootInstanceHandle(), IsRootSequence(), and IsSubSequence().
RootOverrideSequenceID
FMovieSceneSequenceID UE::MovieScene::FSequenceInstance::RootOverrideSequenceID private
When SequenceID != MovieSceneSequenceID::Root, specifies an ID to override as a simulated root.
Definition at line 412 of file MovieSceneSequenceInstance.h.
RootSequenceName
FString UE::MovieScene::FSequenceInstance::RootSequenceName private
Name of the root sequence.
Definition at line 394 of file MovieSceneSequenceInstance.h.
SequenceID
FMovieSceneSequenceID UE::MovieScene::FSequenceInstance::SequenceID private
This sequence instances sequence ID, or MovieSceneSequenceID::Root for top-level sequences.
Definition at line 410 of file MovieSceneSequenceInstance.h.
Referenced by EvaluateCondition(), FindSubInstance(), and GetSequenceID().
SequenceUpdater
TUniquePtr<ISequenceUpdater> UE::MovieScene::FSequenceInstance::SequenceUpdater private
For top-level sequences only - interface for either a flat or hierarchical entity updater.
Definition at line 402 of file MovieSceneSequenceInstance.h.
SharedPlaybackState
TSharedRef<FSharedPlaybackState> UE::MovieScene::FSequenceInstance::SharedPlaybackState private
Playback state shared by the entire sequence hierarchy.
Definition at line 407 of file MovieSceneSequenceInstance.h.
Referenced by GetSharedPlaybackState().
UpdateFlags
ESequenceInstanceUpdateFlags UE::MovieScene::FSequenceInstance::UpdateFlags private
Cached update flags denoting what kinds of updates are required by this instance.
Definition at line 414 of file MovieSceneSequenceInstance.h.
Referenced by GetUpdateFlags().
VolatilityManager
TUniquePtr<FCompiledDataVolatilityManager> UE::MovieScene::FSequenceInstance::VolatilityManager private
For top-level sequences only - a utility class that is used to ensure that volatile sequences are up to date.
Only valid in editor, or for sequences that have the volatile flag.
Definition at line 404 of file MovieSceneSequenceInstance.h.
The documentation for this struct was generated from the following file:
MovieSceneSequenceInstance.h