Unreal Engine 5.6 C++ API: FTrackedActivity Class Reference
FTrackedActivity Class Reference
Tracked Activity is used to be able to visualize on a semi-high level what is going on in the process.
#include "TrackedActivity.h"
Data Structures
struct FInfo
Public Types
enum class EEvent : int32 { Added = 1 , Removed = 2 , Changed = 3 }
Enum used for Event listener to identify type of activity change.
using ELight = ETrackedActivityLight
enum class EType { Activity , Info , Debug }
Enum to specify status type of activity In the new console, 'Activity' will make sure tracked activity appears to the left of the window 'Info' appears to the right and use less width.
Public Member Functions
FTrackedActivity (const TCHAR *Name, const TCHAR *Status=TEXT(""), ELight Light=ELight::None, EType Type=EType::Activity, int32 SortValue=100)
Ctor.
~FTrackedActivity ()
Dtor.
void Pop ()
uint32 Push (const TCHAR *Status, bool bShowParent=false, ELight Light=ELight::Inherit)
Pushes new status on to tracked activity, will require a pop to get back to previous status ShowParent can be used to make sure Status of parent is visible in front of status of pushed scope.
void Update (const TCHAR *Status, ELight Light, uint32 Index=~0u)
void Update (const TCHAR *Status, uint32 Index=~0u)
Updates status.
void Update (ELight Light, uint32 Index=~0u)
Public Member Functions inherited from TSharedFromThis< FTrackedActivity >
TSharedRef< FTrackedActivity, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FTrackedActivity, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FTrackedActivity & GetEngineActivity ()
Process Engine Activity.
static FTrackedActivity & GetIOActivity ()
I/O Activity.Shows current I / O operation.If plugin / game have their own I / O, scopes will need to be manually added.
static void RegisterEventListener (TUniqueFunction< void(EEvent Event, const FInfo &Info)> &&Func, uint32 MaxDepth=~0u)
Register listener that can track adds, removes and changes when they happen.
static void TraverseActivities (const TFunction< void(const FInfo &Info)> &Func)
Traverses all FTrackedActivities in the order they were added.
Private Member Functions
FTrackedActivity (const FTrackedActivity &O)=delete
FTrackedActivity & operator= (const FTrackedActivity &O)=delete
Private Attributes
void * Internal
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FTrackedActivity >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FTrackedActivity >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Tracked Activity is used to be able to visualize on a semi-high level what is going on in the process.
It is very useful when wanting to show the status of online, or if the runtime is waiting on loading something When new console is enabled tracked activities show at the bottom of the window under the log Tracked Activities can be created/updated/destroyed on multiple threads
Definition at line 28 of file TrackedActivity.h.
Member Typedef Documentation
ELight
using FTrackedActivity::ELight = ETrackedActivityLight
Definition at line 43 of file TrackedActivity.h.
Member Enumeration Documentation
EEvent
enum class FTrackedActivity::EEvent : int32 strong
Enum used for Event listener to identify type of activity change.
Enumerator
Added
Removed
Changed
Definition at line 100 of file TrackedActivity.h.
EType
enum class FTrackedActivity::EType strong
Enum to specify status type of activity In the new console, 'Activity' will make sure tracked activity appears to the left of the window 'Info' appears to the right and use less width.
Typically use 'Info' for things that are more static
Enumerator
Activity
Info
Debug
Definition at line 36 of file TrackedActivity.h.
Constructor & Destructor Documentation
FTrackedActivity() [1/2]
FTrackedActivity::FTrackedActivity (const TCHAR * Name, const TCHAR * Status = TEXT(""), ELight Light = ELight::None, EType Type = EType::Activity, int32 SortValue = 100)
Ctor.
Parameters
Name Name of tracked activity
Status Initial status of tracked activity
Light for the activity. Will show as a dot in front of activity in console
Type Decides where activity information show in console. Activity is to the left, Info to the right
SortValue Decides in what order within type the activity will show in console. Lower value means earlier
References Activity, Light, and Name.
Referenced by FTrackedActivity(), GetEngineActivity(), GetIOActivity(), and operator=().
~FTrackedActivity()
FTrackedActivity::~FTrackedActivity ()
Dtor.
FTrackedActivity() [2/2]
FTrackedActivity::FTrackedActivity (const FTrackedActivity & O) private delete
References FTrackedActivity().
Member Function Documentation
GetEngineActivity()
FTrackedActivity & FTrackedActivity::GetEngineActivity () static
Process Engine Activity.
General status of the Engine. Used by Engine initialization etc. By default, status light will stay yellow until main threads hits Tick update, then it turns green.
References FTrackedActivity().
GetIOActivity()
FTrackedActivity & FTrackedActivity::GetIOActivity () static
I/O Activity.Shows current I / O operation.If plugin / game have their own I / O, scopes will need to be manually added.
References FTrackedActivity().
operator=()
FTrackedActivity & FTrackedActivity::operator= (const FTrackedActivity & O) private delete
References FTrackedActivity().
Pop()
void FTrackedActivity::Pop ()
Push()
uint32 FTrackedActivity::Push (const TCHAR * Status, bool bShowParent = false, ELight Light = ELight::Inherit)
Pushes new status on to tracked activity, will require a pop to get back to previous status ShowParent can be used to make sure Status of parent is visible in front of status of pushed scope.
References Light.
RegisterEventListener()
void FTrackedActivity::RegisterEventListener (TUniqueFunction< void(EEvent Event, const FInfo &Info)> && Func, uint32 MaxDepth = ~0u) static
Register listener that can track adds, removes and changes when they happen.
Listener will be called from the same thread as the event happens, so make sure listener is threadsafe.
References Event, and Info.
TraverseActivities()
void FTrackedActivity::TraverseActivities (const TFunction< void(const FInfo &Info)> & Func) static
Traverses all FTrackedActivities in the order they were added.
References Info.
Update() [1/3]
void FTrackedActivity::Update (const TCHAR * Status, ELight Light, uint32 Index = ~0u)
References Light.
Update() [2/3]
void FTrackedActivity::Update (const TCHAR * Status, uint32 Index = ~0u)
Updates status.
If Index is ~0u entry at top of stack will be updated (which is the one showing)
Update() [3/3]
void FTrackedActivity::Update (ELight Light, uint32 Index = ~0u)
References Light.
Field Documentation
Internal
void* FTrackedActivity::Internal private
Definition at line 117 of file TrackedActivity.h.
The documentation for this class was generated from the following file:
TrackedActivity.h