Unreal Engine 5.6 C++ API: UE::MovieScene::TComponentPtr< T > Struct Template Reference
UE::MovieScene::TComponentPtr< T > Struct Template Reference
Facade for any component data type.
#include "MovieSceneComponentPtr.h"
Public Types
using ValueType = std::conditional_t<TIsConst<T>::Value, typename TCallTraits<T>::ParamType, T&>
Value type is either a T or const T& for read-only types, or T& for writeable types.
Public Member Functions
TComponentPtr ()
TComponentPtr (const TComponentPtr &RHS)=default
TComponentPtr (T *InComponentPtr)
TComponentPtr (TComponentPtr &&RHS)
FORCEINLINE TArrayView< T > AsArray (int32 Num) const
Retrieve this component data as an array view of the specified size (usually the size will be FEntityAllocation::Num())
FORCEINLINE T * AsPtr () const
Explicitly convert this component data to its underlying pointer type.
ValueType ComponentAtIndex (int32 Index) const
FORCEINLINE bool IsValid () const
FORCEINLINE operator bool () const
FORCEINLINE operator T* () const
FORCEINLINE ValueType operator* () const
FORCEINLINE T * operator-> () const
TComponentPtr & operator= (const TComponentPtr &RHS)=default
TComponentPtr & operator= (TComponentPtr &&RHS)
FORCEINLINE ValueType operator[] (int32 Index) const
FORCEINLINE TArrayView< T > Slice (int32 StartIndex, int32 Num) const
Retrieve a slice of this component data as an array view of the specified size and offset (usually the size will be FEntityAllocation::Num())
Protected Attributes
T * ComponentPtr
Detailed Description
template<typename T>
struct UE::MovieScene::TComponentPtr< T >
Facade for any component data type.
Definition at line 15 of file MovieSceneComponentPtr.h.
Member Typedef Documentation
ValueType
template<typename T> using UE::MovieScene::TComponentPtr< T >::ValueType = std::conditional_t<TIsConst<T>::Value, typename TCallTraits<T>::ParamType, T&>
Value type is either a T or const T& for read-only types, or T& for writeable types.
Definition at line 18 of file MovieSceneComponentPtr.h.
Constructor & Destructor Documentation
TComponentPtr() [1/4]
template<typename T> UE::MovieScene::TComponentPtr< T >::TComponentPtr () inline
Definition at line 20 of file MovieSceneComponentPtr.h.
References ComponentPtr.
Referenced by TComponentPtr(), TComponentPtr(), UE::MovieScene::TRead< FMovieSceneEntityID >::TRead(), UE::MovieScene::TRead< FMovieSceneEntityID >::TRead(), UE::MovieScene::TWrite< T >::TWrite(), UE::MovieScene::TWrite< T >::TWrite(), operator=(), and operator=().
TComponentPtr() [2/4]
template<typename T> UE::MovieScene::TComponentPtr< T >::TComponentPtr (T * InComponentPtr) inline explicit
Definition at line 24 of file MovieSceneComponentPtr.h.
References ComponentPtr.
TComponentPtr() [3/4]
template<typename T> UE::MovieScene::TComponentPtr< T >::TComponentPtr (const TComponentPtr< T > & RHS) default
References TComponentPtr().
TComponentPtr() [4/4]
template<typename T> UE::MovieScene::TComponentPtr< T >::TComponentPtr (TComponentPtr< T > && RHS) inline
Definition at line 31 of file MovieSceneComponentPtr.h.
References TComponentPtr(), and ComponentPtr.
Member Function Documentation
AsArray()
template<typename T> FORCEINLINE TArrayView< T > UE::MovieScene::TComponentPtr< T >::AsArray (int32 Num) const inline
Retrieve this component data as an array view of the specified size (usually the size will be FEntityAllocation::Num())
Definition at line 61 of file MovieSceneComponentPtr.h.
References ComponentPtr, FORCEINLINE, MakeArrayView(), and Num.
AsPtr()
template<typename T> FORCEINLINE T * UE::MovieScene::TComponentPtr< T >::AsPtr () const inline
Explicitly convert this component data to its underlying pointer type.
Definition at line 55 of file MovieSceneComponentPtr.h.
References ComponentPtr, and FORCEINLINE.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendChannel(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendImpl().
ComponentAtIndex()
template<typename T> ValueType UE::MovieScene::TComponentPtr< T >::ComponentAtIndex (int32 Index) const inline
Definition at line 87 of file MovieSceneComponentPtr.h.
IsValid()
template<typename T> FORCEINLINE bool UE::MovieScene::TComponentPtr< T >::IsValid () const inline
Definition at line 49 of file MovieSceneComponentPtr.h.
References ComponentPtr, and FORCEINLINE.
Referenced by operator bool().
operator bool()
template<typename T> FORCEINLINE UE::MovieScene::TComponentPtr< T >::operator bool () const inline explicit
Definition at line 44 of file MovieSceneComponentPtr.h.
References FORCEINLINE, and IsValid().
operator T*()
template<typename T> FORCEINLINE UE::MovieScene::TComponentPtr< T >::operator T* () const inline
Definition at line 92 of file MovieSceneComponentPtr.h.
References ComponentPtr, and FORCEINLINE.
operator*()
template<typename T> FORCEINLINE ValueType UE::MovieScene::TComponentPtr< T >::operator* () const inline
Definition at line 77 of file MovieSceneComponentPtr.h.
References ComponentPtr, and FORCEINLINE.
operator->()
template<typename T> FORCEINLINE T * UE::MovieScene::TComponentPtr< T >::operator-> () const inline
Definition at line 72 of file MovieSceneComponentPtr.h.
References ComponentPtr, and FORCEINLINE.
operator=() [1/2]
template<typename T> TComponentPtr & UE::MovieScene::TComponentPtr< T >::operator= (const TComponentPtr< T > & RHS) default
References TComponentPtr().
operator=() [2/2]
template<typename T> TComponentPtr & UE::MovieScene::TComponentPtr< T >::operator= (TComponentPtr< T > && RHS) inline
Definition at line 37 of file MovieSceneComponentPtr.h.
References TComponentPtr(), and ComponentPtr.
operator[]()
template<typename T> FORCEINLINE ValueType UE::MovieScene::TComponentPtr< T >::operator[] (int32 Index) const inline
Definition at line 82 of file MovieSceneComponentPtr.h.
References ComponentPtr, and FORCEINLINE.
Slice()
template<typename T> FORCEINLINE TArrayView< T > UE::MovieScene::TComponentPtr< T >::Slice (int32 StartIndex, int32 Num) const inline
Retrieve a slice of this component data as an array view of the specified size and offset (usually the size will be FEntityAllocation::Num())
Definition at line 67 of file MovieSceneComponentPtr.h.
References ComponentPtr, FORCEINLINE, MakeArrayView(), and Num.
Field Documentation
ComponentPtr
template<typename T> T* UE::MovieScene::TComponentPtr< T >::ComponentPtr protected
Definition at line 99 of file MovieSceneComponentPtr.h.
Referenced by TComponentPtr(), TComponentPtr(), TComponentPtr(), UE::MovieScene::TRead< FMovieSceneEntityID >::TRead(), UE::MovieScene::TWriteOptional< T >::TWriteOptional(), UE::MovieScene::TWriteOptional< T >::TWriteOptional(), AsArray(), AsPtr(), UE::MovieScene::TWriteOptional< T >::ComponentAtIndex(), IsValid(), operator T*(), operator*(), operator->(), operator=(), operator[](), and Slice().
The documentation for this struct was generated from the following file:
MovieSceneComponentPtr.h