Unreal Engine 5.6 C++ API: UE::SourceLocation::FFileAndLineAdapter Struct Reference
UE::SourceLocation::FFileAndLineAdapter Struct Reference
Adapter for formatting a source location as file and line only.
#include "SourceLocationUtils.h"
Public Member Functions
void AppendString (FUtf8StringBuilderBase &Out) const
void AppendString (FWideStringBuilderBase &Out) const
Converts the source location to a readable format with file and line information, appending to an existing string.
FString ToString () const
Converts the source location to a readable format with file and line information.
void ToString (FUtf8String &Out) const
void ToString (FWideString &Out) const
Converts the source location to a readable format with file and line information, in place.
FUtf8String ToUtf8String () const
Data Fields
const FSourceLocation & Location
Friends
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase &Builder, const FFileAndLineAdapter &Adapter)
FWideStringBuilderBase & operator<< (FWideStringBuilderBase &Builder, const FFileAndLineAdapter &Adapter)
void SerializeForLog (FCbWriter &Writer, const FFileAndLineAdapter &Adapter)
Detailed Description
Adapter for formatting a source location as file and line only.
Definition at line 75 of file SourceLocationUtils.h.
Member Function Documentation
AppendString() [1/2]
void UE::SourceLocation::FFileAndLineAdapter::AppendString (FUtf8StringBuilderBase & Out) const
AppendString() [2/2]
void UE::SourceLocation::FFileAndLineAdapter::AppendString (FWideStringBuilderBase & Out) const
Converts the source location to a readable format with file and line information, appending to an existing string.
Parameters
Out StringBuilder to append with the string representation of the source location.
Referenced by operator<<, and operator<<.
ToString() [1/3]
FString UE::SourceLocation::FFileAndLineAdapter::ToString () const nodiscard
Converts the source location to a readable format with file and line information.
Returns
String representation of the source location.
Referenced by UE::SourceLocation::UE_DEPRECATED(), and UE::SourceLocation::UE_DEPRECATED().
ToString() [2/3]
void UE::SourceLocation::FFileAndLineAdapter::ToString (FUtf8String & Out) const
ToString() [3/3]
void UE::SourceLocation::FFileAndLineAdapter::ToString (FWideString & Out) const
Converts the source location to a readable format with file and line information, in place.
Parameters
Out String to fill with the string representation of the source location.
ToUtf8String()
FUtf8String UE::SourceLocation::FFileAndLineAdapter::ToUtf8String () const nodiscard
Friends And Related Symbol Documentation
operator<< [1/2]
FUtf8StringBuilderBase & operator<< (FUtf8StringBuilderBase & Builder, const FFileAndLineAdapter & Adapter) friend
Definition at line 113 of file SourceLocationUtils.h.
References AppendString().
operator<< [2/2]
FWideStringBuilderBase & operator<< (FWideStringBuilderBase & Builder, const FFileAndLineAdapter & Adapter) friend
Definition at line 108 of file SourceLocationUtils.h.
References AppendString().
SerializeForLog
void SerializeForLog (FCbWriter & Writer, const FFileAndLineAdapter & Adapter) friend
Definition at line 103 of file SourceLocationUtils.h.
References Location, and UE::SourceLocation::Private::SerializeForLogFileAndLine().
Field Documentation
Location
const FSourceLocation& UE::SourceLocation::FFileAndLineAdapter::Location
Definition at line 77 of file SourceLocationUtils.h.
Referenced by SerializeForLog.
The documentation for this struct was generated from the following file:
SourceLocationUtils.h