Unreal Engine 5.6 C++ API: FDynamicSpriteEmitterDataBase Struct Reference
FDynamicSpriteEmitterDataBase Struct Reference
Base class for Sprite emitters and other emitter types that share similar features.
#include "ParticleHelper.h"
Public Member Functions
FDynamicSpriteEmitterDataBase (const UParticleModuleRequired *RequiredModule)
virtual ~FDynamicSpriteEmitterDataBase ()
void BuildViewFillData (const FParticleSystemSceneProxy *Proxy, const FSceneView *InView, int32 InVertexCount, int32 InVertexSize, int32 InDynamicParameterVertexSize, FGlobalDynamicIndexBuffer &DynamicIndexBuffer, FGlobalDynamicVertexBuffer &DynamicVertexBuffer, FGlobalDynamicVertexBufferAllocation &DynamicVertexAllocation, FGlobalDynamicIndexBufferAllocation &DynamicIndexAllocation, FGlobalDynamicVertexBufferAllocation *DynamicParameterAllocation, FAsyncBufferFillData &Data) const
Set up an buffer for async filling.
virtual void DoBufferFill (FAsyncBufferFillData &Me) const
virtual int32 GetDynamicParameterVertexStride () const
Get the vertex stride for the dynamic parameter rendering data.
virtual int32 GetDynamicVertexStride (ERHIFeatureLevel::Type) const
Get the vertex stride for the dynamic rendering data.
virtual void GetIndexAllocInfo (int32 &OutNumIndices, int32 &OutStride) const
Gets the information required for allocating this emitters indices from the global index array.
const FMaterialRenderProxy * GetMaterialRenderProxy ()
Retrieve the material render proxy to use for rendering this emitter.
virtual const FDynamicSpriteEmitterReplayDataBase * GetSourceData () const
Get the source replay data for this emitter.
virtual void RenderDebug (const FParticleSystemSceneProxy *Proxy, FPrimitiveDrawInterface *PDI, const FSceneView *View, bool bCrosses) const
Debug rendering.
void SortSpriteParticles (int32 SortMode, bool bLocalSpace, int32 ParticleCount, const uint8 *ParticleData, int32 ParticleStride, const uint16 *ParticleIndices, const FSceneView *View, const FMatrix &LocalToWorld, FParticleOrder *ParticleOrder) const
Sort the given sprite particles.
Public Member Functions inherited from FDynamicEmitterDataBase
FDynamicEmitterDataBase (const class UParticleModuleRequired *RequiredModule)
virtual ~FDynamicEmitterDataBase ()
virtual void GatherSimpleLights (const FParticleSystemSceneProxy *Proxy, const FSceneViewFamily &ViewFamily, FSimpleLightArray &OutParticleLights) const
Callback from the renderer to gather simple lights that this proxy wants renderered.
virtual void GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy *Proxy, const FSceneView *View, const FSceneViewFamily &ViewFamily, int32 ViewIndex, FMeshElementCollector &Collector) const
virtual const FMacroUVOverride & GetMacroUVOverride () const
Returns the current macro uv override.
virtual const FDynamicEmitterReplayDataBase & GetSource () const =0
Returns the source data for this particle system.
void operator delete (void *RawMemory, size_t Size)
void * operator new (size_t Size)
Custom new/delete with recycling.
virtual void ReleaseRenderThreadResources (const FParticleSystemSceneProxy *InOwnerProxy)
Release the render thread resources for this emitter data.
virtual void UpdateRenderThreadResourcesEmitter (const FParticleSystemSceneProxy *InOwnerProxy)
Create the render thread resources for this emitter data.
Data Fields
uint32 bUsesDynamicParameter:1
true if the particle emitter utilizes the DynamicParameter module
const FMaterialRenderProxy * MaterialResource
The material render proxy for this emitter.
Data Fields inherited from FDynamicEmitterDataBase
uint32 bSelected:1
true if this emitter is currently selected
uint32 bValid:1
true if this emitter has valid rendering data
int32 EmitterIndex
TStatId StatID
Stat id of this object, 0 if nobody asked for it yet.
Detailed Description
Base class for Sprite emitters and other emitter types that share similar features.
Definition at line 1365 of file ParticleHelper.h.
Constructor & Destructor Documentation
FDynamicSpriteEmitterDataBase()
FDynamicSpriteEmitterDataBase::FDynamicSpriteEmitterDataBase (const UParticleModuleRequired * RequiredModule) inline
Definition at line 1367 of file ParticleHelper.h.
References FDynamicEmitterDataBase::FDynamicEmitterDataBase(), bUsesDynamicParameter, and MaterialResource.
Referenced by FDynamicBeam2EmitterData::FDynamicBeam2EmitterData(), FDynamicSpriteEmitterData::FDynamicSpriteEmitterData(), and FDynamicTrailsEmitterData::FDynamicTrailsEmitterData().
~FDynamicSpriteEmitterDataBase()
virtual FDynamicSpriteEmitterDataBase::~FDynamicSpriteEmitterDataBase () inline virtual
Definition at line 1374 of file ParticleHelper.h.
Member Function Documentation
BuildViewFillData()
void FDynamicSpriteEmitterDataBase::BuildViewFillData (const FParticleSystemSceneProxy * Proxy, const FSceneView * InView, int32 InVertexCount, int32 InVertexSize, int32 InDynamicParameterVertexSize, FGlobalDynamicIndexBuffer & DynamicIndexBuffer, FGlobalDynamicVertexBuffer & DynamicVertexBuffer, FGlobalDynamicVertexBufferAllocation & DynamicVertexAllocation, FGlobalDynamicIndexBufferAllocation & DynamicIndexAllocation, FGlobalDynamicVertexBufferAllocation * DynamicParameterAllocation, FAsyncBufferFillData & Data) const
Set up an buffer for async filling.
Parameters
Proxy The primitive scene proxy for the emitter.
InView View for this buffer
InVertexCount Count of verts for this buffer
InVertexSize Stride of these verts, only used for verification
InDynamicParameterVertexStride Stride of the dynamic parameter
DoBufferFill()
virtual void FDynamicSpriteEmitterDataBase::DoBufferFill (FAsyncBufferFillData & Me) const inline virtual
Reimplemented in FDynamicBeam2EmitterData, and FDynamicTrailsEmitterData.
Definition at line 1452 of file ParticleHelper.h.
References check.
GetDynamicParameterVertexStride()
virtual int32 FDynamicSpriteEmitterDataBase::GetDynamicParameterVertexStride () const inline virtual
Get the vertex stride for the dynamic parameter rendering data.
Reimplemented in FDynamicBeam2EmitterData, FDynamicMeshEmitterData, FDynamicSpriteEmitterData, and FDynamicTrailsEmitterData.
Definition at line 1419 of file ParticleHelper.h.
References checkf, and TEXT.
GetDynamicVertexStride()
virtual int32 FDynamicSpriteEmitterDataBase::GetDynamicVertexStride (ERHIFeatureLevel::Type) const inline virtual
Get the vertex stride for the dynamic rendering data.
Reimplemented in FDynamicBeam2EmitterData, FDynamicMeshEmitterData, FDynamicSpriteEmitterData, and FDynamicTrailsEmitterData.
Definition at line 1410 of file ParticleHelper.h.
References checkf, and TEXT.
GetIndexAllocInfo()
virtual void FDynamicSpriteEmitterDataBase::GetIndexAllocInfo (int32 & OutNumIndices, int32 & OutStride) const inline virtual
Gets the information required for allocating this emitters indices from the global index array.
Reimplemented in FDynamicBeam2EmitterData, and FDynamicTrailsEmitterData.
Definition at line 1437 of file ParticleHelper.h.
References checkf, and TEXT.
GetMaterialRenderProxy()
const FMaterialRenderProxy * FDynamicSpriteEmitterDataBase::GetMaterialRenderProxy () inline virtual
Retrieve the material render proxy to use for rendering this emitter.
PURE VIRTUAL
Parameters
bSelected Whether the object is selected
Returns
FMaterialRenderProxy* The material proxt to render with.
Implements FDynamicEmitterDataBase.
Definition at line 1385 of file ParticleHelper.h.
References MaterialResource.
GetSourceData()
virtual const FDynamicSpriteEmitterReplayDataBase * FDynamicSpriteEmitterDataBase::GetSourceData () const inline virtual
Get the source replay data for this emitter.
Reimplemented in FDynamicMeshEmitterData, FDynamicRibbonEmitterData, FDynamicSpriteEmitterData, and FDynamicTrailsEmitterData.
Definition at line 1428 of file ParticleHelper.h.
References checkf, and TEXT.
RenderDebug()
virtual void FDynamicSpriteEmitterDataBase::RenderDebug (const FParticleSystemSceneProxy * Proxy, FPrimitiveDrawInterface * PDI, const FSceneView * View, bool bCrosses) const virtual
Debug rendering.
Parameters
Proxy The primitive scene proxy for the emitter.
PDI The primitive draw interface to render with
View The scene view being rendered
bCrosses If true, render Crosses at particle position; false, render points
Reimplemented in FDynamicAnimTrailEmitterData, FDynamicBeam2EmitterData, FDynamicRibbonEmitterData, and FDynamicTrailsEmitterData.
SortSpriteParticles()
void FDynamicSpriteEmitterDataBase::SortSpriteParticles (int32 SortMode, bool bLocalSpace, int32 ParticleCount, const uint8 * ParticleData, int32 ParticleStride, const uint16 * ParticleIndices, const FSceneView * View, const FMatrix & LocalToWorld, FParticleOrder * ParticleOrder) const
Sort the given sprite particles.
Parameters
SorceMode The sort mode to utilize (EParticleSortMode)
bLocalSpace true if the emitter is using local space
ParticleCount The number of particles
ParticleData The actual particle data
ParticleStride The stride between entries in the ParticleData array
ParticleIndices Indirect index list into ParticleData
View The scene view being rendered
LocalToWorld The local to world transform of the component rendering the emitter
ParticleOrder The array to fill in with ordered indices
Field Documentation
bUsesDynamicParameter
uint32 FDynamicSpriteEmitterDataBase::bUsesDynamicParameter
true if the particle emitter utilizes the DynamicParameter module
Definition at line 1483 of file ParticleHelper.h.
Referenced by FDynamicSpriteEmitterDataBase().
MaterialResource
const FMaterialRenderProxy* FDynamicSpriteEmitterDataBase::MaterialResource
The material render proxy for this emitter.
Definition at line 1481 of file ParticleHelper.h.
Referenced by FDynamicSpriteEmitterDataBase(), and GetMaterialRenderProxy().
The documentation for this struct was generated from the following file:
ParticleHelper.h