Unreal Engine 5.6 C++ API: FObjectExport Struct Reference
FObjectExport Struct Reference
UObject resource type for objects that are contained within this package and can be referenced by other packages.
#include "ObjectResource.h"
Public Member Functions
FObjectExport ()
Constructors.
FObjectExport (const FObjectExport &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FObjectExport (FObjectExport &&)=default
FObjectExport (UObject *InObject, bool bInNotAlwaysLoadedForEditorGame=true)
FObjectExport & operator= (const FObjectExport &)=default
FObjectExport & operator= (FObjectExport &&)=default
PRAGMA_ENABLE_DEPRECATION_WARNINGS void ResetObject ()
Resets the stored Object and any transient flags.
Public Member Functions inherited from FObjectResource
FObjectResource ()
FObjectResource (UObject *InObject)
Data Fields
bool bExportLoadFailed:1
Force this export to not load, it failed because the outer didn't exist.
bool bForcedExport:1
Whether the export was forced into the export table via OBJECTMARK_ForceTagExp.
bool bGeneratePublicHash:1
True if this export should have its iostore public hash generated even if not RF_Public.
bool bIsAsset:1
True if this export is an asset object.
bool bIsInheritedInstance:1
If this export is an instanced object inherited from a template and should only be created if the template has the object.
bool bNotAlwaysLoadedForEditorGame:1
Whether the export should be always loaded in editor game False means that the object is True doesn't means, that the object won't be loaded.
bool bNotForClient:1
Whether the export should be loaded on clients Serialized.
bool bNotForServer:1
Whether the export should be loaded on servers Serialized.
bool bWasFiltered:1
Export was filtered out on load.
FPackageIndex ClassIndex
Location of the resource for this export's class (if non-zero).
int32 CreateBeforeCreateDependencies
int32 CreateBeforeSerializationDependencies
int32 FirstExportDependency
The export table must serialize as a fixed size, this is use to index into a long list, which is later loaded into the array.
int32 HashNext
The index into the FLinker's ExportMap for the next export in the linker's export hash table.
UObject * Object
The UObject represented by this export.
EObjectFlags ObjectFlags
The object flags for the UObject represented by this resource.
uint32 PackageFlags
If this object is a top level package (which must have been forced into the export table via OBJECTMARK_ForceTagExp) this is the package flags for the original package file Serialized.
int64 ScriptSerializationEndOffset
The location (relative to SerialOffset) of the end of the portion of this export's data that is serialized using tagged property serialization.
int64 ScriptSerializationStartOffset
The location (relative to SerialOffset) of the beginning of the portion of this export's data that is serialized using tagged property serialization.
int32 SerializationBeforeCreateDependencies
int32 SerializationBeforeSerializationDependencies
int64 SerialOffset
The location (into the FLinker's underlying file reader archive) of the beginning of the data for this export's UObject.
int64 SerialSize
The number of bytes to serialize when saving/loading this export's UObject.
FPackageIndex SuperIndex
Location of the resource for this export's SuperField (parent).
FPackageIndex TemplateIndex
Location of the resource for this export's template/archetypes.
FPackageIndex ThisIndex
Location of this resource in export map.
Data Fields inherited from FObjectResource
FName ObjectName
The name of the UObject represented by this resource.
FPackageIndex OuterIndex
Location of the resource for this resource's Outer.
Friends
FArchive & operator<< (FArchive &Ar, FObjectExport &E)
I/O functions.
void operator<< (FStructuredArchive::FSlot Slot, FObjectExport &E)
Detailed Description
UObject resource type for objects that are contained within this package and can be referenced by other packages.
Definition at line 226 of file ObjectResource.h.
Constructor & Destructor Documentation
FObjectExport() [1/4]
FObjectExport::FObjectExport ()
Constructors.
Referenced by FObjectExport(), FObjectExport(), operator<<, operator<<, operator=(), and operator=().
FObjectExport() [2/4]
FObjectExport::FObjectExport (UObject * InObject, bool bInNotAlwaysLoadedForEditorGame = true)
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
FObjectExport() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FObjectExport::FObjectExport (FObjectExport &&) default
References FObjectExport().
FObjectExport() [4/4]
FObjectExport::FObjectExport (const FObjectExport &) default
References FObjectExport().
Member Function Documentation
operator=() [1/2]
FObjectExport & FObjectExport::operator= (const FObjectExport &) default
References FObjectExport(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FObjectExport & FObjectExport::operator= (FObjectExport &&) default
References FObjectExport().
ResetObject()
PRAGMA_ENABLE_DEPRECATION_WARNINGS void FObjectExport::ResetObject ()
Resets the stored Object and any transient flags.
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FObjectExport & E) friend
I/O functions.
References FObjectExport(), and Ar.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FObjectExport & E) friend
References FObjectExport().
Field Documentation
bExportLoadFailed
bool FObjectExport::bExportLoadFailed
Force this export to not load, it failed because the outer didn't exist.
Definition at line 352 of file ObjectResource.h.
bForcedExport
bool FObjectExport::bForcedExport
Whether the export was forced into the export table via OBJECTMARK_ForceTagExp.
Serialized
Definition at line 311 of file ObjectResource.h.
bGeneratePublicHash
bool FObjectExport::bGeneratePublicHash
True if this export should have its iostore public hash generated even if not RF_Public.
Definition at line 347 of file ObjectResource.h.
bIsAsset
bool FObjectExport::bIsAsset
True if this export is an asset object.
Definition at line 336 of file ObjectResource.h.
bIsInheritedInstance
bool FObjectExport::bIsInheritedInstance
If this export is an instanced object inherited from a template and should only be created if the template has the object.
Definition at line 342 of file ObjectResource.h.
bNotAlwaysLoadedForEditorGame
bool FObjectExport::bNotAlwaysLoadedForEditorGame
Whether the export should be always loaded in editor game False means that the object is True doesn't means, that the object won't be loaded.
Serialized
Definition at line 331 of file ObjectResource.h.
bNotForClient
bool FObjectExport::bNotForClient
Whether the export should be loaded on clients Serialized.
Definition at line 317 of file ObjectResource.h.
bNotForServer
bool FObjectExport::bNotForServer
Whether the export should be loaded on servers Serialized.
Definition at line 323 of file ObjectResource.h.
bWasFiltered
bool FObjectExport::bWasFiltered
Export was filtered out on load.
Definition at line 357 of file ObjectResource.h.
ClassIndex
FPackageIndex FObjectExport::ClassIndex
Location of the resource for this export's class (if non-zero).
A value of zero indicates that this export represents a UClass object; there is no resource for this export's class object Serialized
Definition at line 234 of file ObjectResource.h.
CreateBeforeCreateDependencies
int32 FObjectExport::CreateBeforeCreateDependencies
Definition at line 373 of file ObjectResource.h.
CreateBeforeSerializationDependencies
int32 FObjectExport::CreateBeforeSerializationDependencies
Definition at line 371 of file ObjectResource.h.
FirstExportDependency
int32 FObjectExport::FirstExportDependency
The export table must serialize as a fixed size, this is use to index into a long list, which is later loaded into the array.
-1 means dependencies are not present These are contiguous blocks, so CreateBeforeSerializationDependencies starts at FirstExportDependency + SerializationBeforeSerializationDependencies
Definition at line 369 of file ObjectResource.h.
HashNext
int32 FObjectExport::HashNext
The index into the FLinker's ExportMap for the next export in the linker's export hash table.
Transient
Definition at line 305 of file ObjectResource.h.
Object
UObject* FObjectExport::Object
The UObject represented by this export.
Assigned the first time CreateExport is called for this export. Transient
Definition at line 299 of file ObjectResource.h.
ObjectFlags
EObjectFlags FObjectExport::ObjectFlags
The object flags for the UObject represented by this resource.
Only flags that match the RF_Load combination mask will be loaded from disk and applied to the UObject. Serialized
Definition at line 264 of file ObjectResource.h.
PackageFlags
uint32 FObjectExport::PackageFlags
If this object is a top level package (which must have been forced into the export table via OBJECTMARK_ForceTagExp) this is the package flags for the original package file Serialized.
Definition at line 363 of file ObjectResource.h.
ScriptSerializationEndOffset
int64 FObjectExport::ScriptSerializationEndOffset
The location (relative to SerialOffset) of the end of the portion of this export's data that is serialized using tagged property serialization.
Serialized into versioned packages as of EUnrealEngineObjectUE5Version::SCRIPT_SERIALIZATION_OFFSET Otherwise transient
Definition at line 293 of file ObjectResource.h.
ScriptSerializationStartOffset
int64 FObjectExport::ScriptSerializationStartOffset
The location (relative to SerialOffset) of the beginning of the portion of this export's data that is serialized using tagged property serialization.
Serialized into versioned packages as of EUnrealEngineObjectUE5Version::SCRIPT_SERIALIZATION_OFFSET Otherwise transient
Definition at line 285 of file ObjectResource.h.
SerializationBeforeCreateDependencies
int32 FObjectExport::SerializationBeforeCreateDependencies
Definition at line 372 of file ObjectResource.h.
SerializationBeforeSerializationDependencies
int32 FObjectExport::SerializationBeforeSerializationDependencies
Definition at line 370 of file ObjectResource.h.
SerialOffset
int64 FObjectExport::SerialOffset
The location (into the FLinker's underlying file reader archive) of the beginning of the data for this export's UObject.
Used for verification only. Serialized
Definition at line 277 of file ObjectResource.h.
SerialSize
int64 FObjectExport::SerialSize
The number of bytes to serialize when saving/loading this export's UObject.
Serialized
Definition at line 270 of file ObjectResource.h.
SuperIndex
FPackageIndex FObjectExport::SuperIndex
Location of the resource for this export's SuperField (parent).
Only valid if this export represents a UStruct object. A value of zero indicates that the object represented by this export isn't a UStruct-derived object. Serialized
Definition at line 249 of file ObjectResource.h.
TemplateIndex
FPackageIndex FObjectExport::TemplateIndex
Location of the resource for this export's template/archetypes.
Only used in the new cooked loader. A value of zero indicates that the value of GetArchetype was zero at cook time, which is more or less impossible and checked. Serialized
Definition at line 257 of file ObjectResource.h.
ThisIndex
FPackageIndex FObjectExport::ThisIndex
Location of this resource in export map.
Used for export fixups while loading packages. Value of zero indicates resource is invalid and shouldn't be loaded. Not serialized.
Definition at line 241 of file ObjectResource.h.
The documentation for this struct was generated from the following file:
ObjectResource.h