Unreal Engine 5.6 C++ API: TLinearCircularRamper< T > Class Template Reference
TLinearCircularRamper< T > Class Template Reference
#include "Ramper.h"
Public Member Functions
TLinearCircularRamper (T InMin, T InMax, float InNumRampCallsPerSecond=1.0f)
T GetMax () const
T GetMin () const
bool Ramp ()
void SetMinMax (T InMin, T InMax, bool bCircular)
void SetTarget (T InTarget, bool bCircular, FRamper::FCallback InCallback=nullptr, void *InData=nullptr)
void SnapTo (T InValue, bool Circular)
Public Member Functions inherited from TRamper< T >
TRamper (float InNumRampCallsPerSecond=1.0f)
const T & GetCurrent () const
float GetProgressPct () const
float GetRampTimeMs () const
const T & GetTarget () const
bool IsAtTarget () const
operator T () const
void SetRampTimeMs (float InNumRampCallsPerSecond, float InRampTimeMs)
void SetRampTimeMs (float InRampTimeMs)
void SnapToTarget ()
Private Attributes
T Max
T Min
Additional Inherited Members
Protected Member Functions inherited from TRamper< T >
void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
Protected Attributes inherited from TRamper< T >
FRamper::FCallback Callback
T CurrentValue
void * Data
T Increment
volatile bool IsSettingTarget
float NormalIncrement
float NumRampCallsPerSecond
float ProgressPct
T TargetValue
Detailed Description
template<typename T>
class TLinearCircularRamper< T >
Definition at line 520 of file Ramper.h.
Constructor & Destructor Documentation
TLinearCircularRamper()
template<typename T> TLinearCircularRamper< T >::TLinearCircularRamper (T InMin, T InMax, float InNumRampCallsPerSecond = 1.0f) inline
Definition at line 523 of file Ramper.h.
References TRamper< T >::TRamper(), Max, and Min.
Member Function Documentation
GetMax()
template<typename T> T TLinearCircularRamper< T >::GetMax () const inline
Definition at line 649 of file Ramper.h.
References Max.
GetMin()
template<typename T> T TLinearCircularRamper< T >::GetMin () const inline
Definition at line 648 of file Ramper.h.
References Min.
Ramp()
template<typename T> bool TLinearCircularRamper< T >::Ramp () inline
Definition at line 598 of file Ramper.h.
References TRamper< T >::CurrentValue, TRamper< T >::Increment, Max, Min, TRamper< T >::NormalIncrement, TRamper< T >::ProgressPct, and TRamper< T >::SnapToTarget().
SetMinMax()
template<typename T> void TLinearCircularRamper< T >::SetMinMax (T InMin, T InMax, bool bCircular) inline
Definition at line 530 of file Ramper.h.
References TRamper< T >::CurrentValue, Max, Min, and SnapTo().
SetTarget()
template<typename T> void TLinearCircularRamper< T >::SetTarget (T InTarget, bool bCircular, FRamper::FCallback InCallback = nullptr, void * InData = nullptr) inline
Definition at line 537 of file Ramper.h.
References TRamper< T >::Callback, FMath::Clamp(), TRamper< T >::CurrentValue, TRamper< T >::Data, Forward(), TRamper< T >::Increment, TRamper< T >::IsSettingTarget, Max, Min, TRamper< T >::NormalIncrement, TRamper< T >::ProgressPct, and TRamper< T >::TargetValue.
SnapTo()
template<typename T> void TLinearCircularRamper< T >::SnapTo (T InValue, bool Circular) inline
Definition at line 626 of file Ramper.h.
References FMath::Clamp(), Max, Min, TRamper< T >::SnapToTarget(), and TRamper< T >::TargetValue.
Referenced by SetMinMax().
Field Documentation
Max
template<typename T> T TLinearCircularRamper< T >::Max private
Definition at line 653 of file Ramper.h.
Referenced by TLinearCircularRamper(), GetMax(), Ramp(), SetMinMax(), SetTarget(), and SnapTo().
Min
template<typename T> T TLinearCircularRamper< T >::Min private
Definition at line 652 of file Ramper.h.
Referenced by TLinearCircularRamper(), GetMin(), Ramp(), SetMinMax(), SetTarget(), and SnapTo().
The documentation for this class was generated from the following file:
Ramper.h