Unreal Engine 5.6 C++ API: UE::AnimNext::FDataHandle Struct Reference
UE::AnimNext::FDataHandle Struct Reference
#include "DataRegistryTypes.h"
Public Member Functions
FDataHandle ()=default
FDataHandle (const FDataHandle &Other)
FDataHandle (FDataHandle &&Other)
FDataHandle (Private::FAllocatedBlock *InAllocatedBlock)
ANIMNEXT_API ~FDataHandle ()
template<typename DataType>
TArrayView< DataType > AsArrayView ()
template<typename DataType>
TArrayView< DataType > AsArrayView () const
template<typename DataType>
DataType * GetPtr ()
template<typename DataType>
const DataType * GetPtr () const
template<typename DataType>
DataType & GetRef ()
template<typename DataType>
const DataType & GetRef () const
FAnimNextParamType GetType () const
bool IsValid () const
FDataHandle & operator= (const FDataHandle &Other)
FDataHandle & operator= (FDataHandle &&Other)
Private Attributes
Private::FAllocatedBlock * AllocatedBlock = nullptr
Detailed Description
Definition at line 62 of file DataRegistryTypes.h.
Constructor & Destructor Documentation
FDataHandle() [1/4]
UE::AnimNext::FDataHandle::FDataHandle () default
Referenced by FDataHandle(), FDataHandle(), operator=(), and operator=().
FDataHandle() [2/4]
UE::AnimNext::FDataHandle::FDataHandle (Private::FAllocatedBlock * InAllocatedBlock) inline
Definition at line 66 of file DataRegistryTypes.h.
References AllocatedBlock.
~FDataHandle()
ANIMNEXT_API UE::AnimNext::FDataHandle::~FDataHandle ()
References UE_API.
FDataHandle() [3/4]
UE::AnimNext::FDataHandle::FDataHandle (const FDataHandle & Other) inline
Definition at line 73 of file DataRegistryTypes.h.
References FDataHandle(), AllocatedBlock, check, and Other.
FDataHandle() [4/4]
UE::AnimNext::FDataHandle::FDataHandle (FDataHandle && Other) inline
Definition at line 91 of file DataRegistryTypes.h.
References FDataHandle(), Other, and Swap.
Member Function Documentation
AsArrayView() [1/2]
template<typename DataType> TArrayView< DataType > UE::AnimNext::FDataHandle::AsArrayView () inline
Definition at line 109 of file DataRegistryTypes.h.
References AllocatedBlock, check, and IsValid().
AsArrayView() [2/2]
template<typename DataType> TArrayView< DataType > UE::AnimNext::FDataHandle::AsArrayView () const inline
Definition at line 116 of file DataRegistryTypes.h.
References AllocatedBlock, check, and IsValid().
GetPtr() [1/2]
template<typename DataType> DataType * UE::AnimNext::FDataHandle::GetPtr () inline
Definition at line 123 of file DataRegistryTypes.h.
References AllocatedBlock, check, and IsValid().
GetPtr() [2/2]
template<typename DataType> const DataType * UE::AnimNext::FDataHandle::GetPtr () const inline
Definition at line 132 of file DataRegistryTypes.h.
References AllocatedBlock, check, and IsValid().
GetRef() [1/2]
template<typename DataType> DataType & UE::AnimNext::FDataHandle::GetRef () inline
Definition at line 140 of file DataRegistryTypes.h.
References AllocatedBlock, check, and IsValid().
GetRef() [2/2]
template<typename DataType> const DataType & UE::AnimNext::FDataHandle::GetRef () const inline
Definition at line 149 of file DataRegistryTypes.h.
References AllocatedBlock, check, and IsValid().
GetType()
FAnimNextParamType UE::AnimNext::FDataHandle::GetType () const inline
Definition at line 157 of file DataRegistryTypes.h.
References AllocatedBlock.
IsValid()
bool UE::AnimNext::FDataHandle::IsValid () const inline
Definition at line 103 of file DataRegistryTypes.h.
References AllocatedBlock.
Referenced by AsArrayView(), AsArrayView(), GetPtr(), GetPtr(), GetRef(), and GetRef().
operator=() [1/2]
FDataHandle & UE::AnimNext::FDataHandle::operator= (const FDataHandle & Other) inline
Definition at line 83 of file DataRegistryTypes.h.
References FDataHandle(), Other, and Swap.
operator=() [2/2]
FDataHandle & UE::AnimNext::FDataHandle::operator= (FDataHandle && Other) inline
Definition at line 97 of file DataRegistryTypes.h.
References FDataHandle(), Other, and Swap.
Field Documentation
AllocatedBlock
Private::FAllocatedBlock* UE::AnimNext::FDataHandle::AllocatedBlock = nullptr private
Definition at line 163 of file DataRegistryTypes.h.
Referenced by FDataHandle(), FDataHandle(), AsArrayView(), AsArrayView(), GetPtr(), GetPtr(), GetRef(), GetRef(), GetType(), and IsValid().
The documentation for this struct was generated from the following file:
DataRegistryTypes.h