Unreal Engine 5.6 C++ API: FUniqueBuffer Class Reference
FUniqueBuffer Class Reference
A reference to a single-ownership mutable buffer.
#include "SharedBuffer.h"
Public Member Functions
FUniqueBuffer ()=default
Construct a null unique buffer.
FUniqueBuffer (const FUniqueBuffer &)=delete
FUniqueBuffer (FBufferOwner *Owner)
Construct a unique buffer from a new unreferenced buffer owner.
FUniqueBuffer (FUniqueBuffer &&)=default
void * GetData ()
Returns a pointer to the start of the buffer.
const void * GetData () const
uint64 GetSize () const
Returns the size of the buffer in bytes.
FMutableMemoryView GetView ()
Returns a view of the buffer.
FMemoryView GetView () const
bool IsMaterialized () const
Returns true if the referenced buffer has been materialized.
bool IsNull () const
Returns true if this does not point to a buffer owner.
bool IsOwned () const
Returns true if this keeps the referenced buffer alive.
FUniqueBuffer MakeOwned () &&
Returns a buffer that is owned, by cloning if not owned.
void Materialize () const
Materialize the buffer by making its data and size available.
FSharedBuffer MoveToShared ()
Convert this to an immutable shared buffer, leaving this null.
operator bool () const
Returns true if this points to a buffer owner.
operator FMemoryView () const
operator FMutableMemoryView ()
bool operator!= (const FUniqueBuffer &BufferB) const
FUniqueBuffer & operator= (const FUniqueBuffer &)=delete
FUniqueBuffer & operator= (FUniqueBuffer &&)=default
bool operator== (const FUniqueBuffer &BufferB) const
void Reset ()
Reset this to null.
Static Public Member Functions
static FUniqueBuffer Alloc (uint64 Size)
Make an uninitialized owned buffer of the specified size.
static FUniqueBuffer AllocZeroed (uint64 Size)
Make a zeroed owned buffer of the specified size.
static FUniqueBuffer Clone (const void *Data, uint64 Size)
static FUniqueBuffer Clone (FMemoryView View)
Make an owned clone of the input.
static FUniqueBuffer MakeView (FMutableMemoryView View)
Make a non-owned view of the input.
static FUniqueBuffer MakeView (void *Data, uint64 Size)
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >())) * = nullptr>
static FUniqueBuffer TakeOwnership (void *Data, uint64 Size, DeleteFunctionType &&DeleteFunction)
Make an owned buffer by taking ownership of the input.
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >(), std::declval< uint64 >())) * = nullptr>
static FUniqueBuffer TakeOwnership (void *Data, uint64 Size, DeleteFunctionType &&DeleteFunction)
Make an owned buffer by taking ownership of the input.
Private Types
using FOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FSharedOps>
Private Member Functions
FUniqueBuffer (FOwnerPtrType &&SharedOwner)
Private Attributes
FOwnerPtrType Owner
Friends
class FSharedBuffer
uint32 GetTypeHash (const FUniqueBuffer &Buffer)
const FOwnerPtrType & ToPrivateOwnerPtr (const FUniqueBuffer &Buffer)
FOwnerPtrType ToPrivateOwnerPtr (FUniqueBuffer &&Buffer)
Detailed Description
A reference to a single-ownership mutable buffer.
Ownership can be transferred by moving to FUniqueBuffer or it can be converted to an immutable shared buffer with MoveToShared().
See also
FBufferOwner
Definition at line 217 of file SharedBuffer.h.
Member Typedef Documentation
FOwnerPtrType
using FUniqueBuffer::FOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FSharedOps> private
Definition at line 315 of file SharedBuffer.h.
Constructor & Destructor Documentation
FUniqueBuffer() [1/5]
FUniqueBuffer::FUniqueBuffer () default
Construct a null unique buffer.
Referenced by FUniqueBuffer(), FUniqueBuffer(), Alloc(), AllocZeroed(), Clone(), Clone(), GetTypeHash, MakeOwned(), MakeView(), MakeView(), operator!=(), operator=(), operator=(), operator==(), TakeOwnership(), ToPrivateOwnerPtr, and ToPrivateOwnerPtr.
FUniqueBuffer() [2/5]
FUniqueBuffer::FUniqueBuffer (FBufferOwner * Owner) explicit
Construct a unique buffer from a new unreferenced buffer owner.
References Owner.
FUniqueBuffer() [3/5]
FUniqueBuffer::FUniqueBuffer (FUniqueBuffer &&) default
References FUniqueBuffer().
FUniqueBuffer() [4/5]
FUniqueBuffer::FUniqueBuffer (const FUniqueBuffer &) delete
References FUniqueBuffer().
FUniqueBuffer() [5/5]
FUniqueBuffer::FUniqueBuffer (FOwnerPtrType && SharedOwner) explicit private
Member Function Documentation
Alloc()
FUniqueBuffer FUniqueBuffer::Alloc (uint64 Size) static nodiscard
Make an uninitialized owned buffer of the specified size.
References FUniqueBuffer(), and TSequenceHistory< HistorySize >::Size.
Referenced by LoadCompactBinary(), TCbBuffer< ViewType >::MakeOwned(), FCbAttachment::TryLoad(), and FCbPackage::TryLoad().
AllocZeroed()
FUniqueBuffer FUniqueBuffer::AllocZeroed (uint64 Size) static nodiscard
Make a zeroed owned buffer of the specified size.
References FUniqueBuffer(), and TSequenceHistory< HistorySize >::Size.
Clone() [1/2]
FUniqueBuffer FUniqueBuffer::Clone (const void * Data, uint64 Size) static nodiscard
References FUniqueBuffer(), and TSequenceHistory< HistorySize >::Size.
Clone() [2/2]
FUniqueBuffer FUniqueBuffer::Clone (FMemoryView View) static nodiscard
Make an owned clone of the input.
References FUniqueBuffer().
GetData() [1/2]
void * FUniqueBuffer::GetData () inline nodiscard
Returns a pointer to the start of the buffer.
Definition at line 267 of file SharedBuffer.h.
References Owner.
Referenced by GetView(), GetView(), and TCbBuffer< ViewType >::MakeOwned().
GetData() [2/2]
const void * FUniqueBuffer::GetData () const inline nodiscard
Definition at line 268 of file SharedBuffer.h.
References Owner.
GetSize()
uint64 FUniqueBuffer::GetSize () const inline nodiscard
Returns the size of the buffer in bytes.
Definition at line 271 of file SharedBuffer.h.
References Owner.
Referenced by GetView(), and GetView().
GetView() [1/2]
FMutableMemoryView FUniqueBuffer::GetView () inline nodiscard
Returns a view of the buffer.
Definition at line 274 of file SharedBuffer.h.
References GetData(), and GetSize().
Referenced by operator FMemoryView(), and operator FMutableMemoryView().
GetView() [2/2]
FMemoryView FUniqueBuffer::GetView () const inline nodiscard
Definition at line 275 of file SharedBuffer.h.
References GetData(), and GetSize().
IsMaterialized()
bool FUniqueBuffer::IsMaterialized () const inline nodiscard
Returns true if the referenced buffer has been materialized.
Definition at line 296 of file SharedBuffer.h.
References Owner.
IsNull()
bool FUniqueBuffer::IsNull () const inline nodiscard
Returns true if this does not point to a buffer owner.
A null buffer is always owned, materialized, and empty.
Definition at line 287 of file SharedBuffer.h.
References Owner.
Referenced by operator bool().
IsOwned()
bool FUniqueBuffer::IsOwned () const inline nodiscard
Returns true if this keeps the referenced buffer alive.
Definition at line 290 of file SharedBuffer.h.
References Owner.
MakeOwned()
FUniqueBuffer FUniqueBuffer::MakeOwned () && nodiscard
Returns a buffer that is owned, by cloning if not owned.
References FUniqueBuffer().
MakeView() [1/2]
FUniqueBuffer FUniqueBuffer::MakeView (FMutableMemoryView View) static nodiscard
Make a non-owned view of the input.
References FUniqueBuffer().
MakeView() [2/2]
FUniqueBuffer FUniqueBuffer::MakeView (void * Data, uint64 Size) static nodiscard
References FUniqueBuffer(), and TSequenceHistory< HistorySize >::Size.
Materialize()
void FUniqueBuffer::Materialize () const
Materialize the buffer by making its data and size available.
The buffer is automatically materialized by GetData, GetSize, GetView.
MoveToShared()
FSharedBuffer FUniqueBuffer::MoveToShared () nodiscard
Convert this to an immutable shared buffer, leaving this null.
Steals the buffer owner from the unique buffer.
References FSharedBuffer.
Referenced by TCbBuffer< ViewType >::MakeOwned().
operator bool()
FUniqueBuffer::operator bool () const inline explicit nodiscard
Returns true if this points to a buffer owner.
Definition at line 280 of file SharedBuffer.h.
References IsNull().
operator FMemoryView()
FUniqueBuffer::operator FMemoryView () const inline nodiscard
Definition at line 277 of file SharedBuffer.h.
References GetView().
operator FMutableMemoryView()
FUniqueBuffer::operator FMutableMemoryView () inline nodiscard
Definition at line 276 of file SharedBuffer.h.
References GetView().
operator!=()
bool FUniqueBuffer::operator!= (const FUniqueBuffer & BufferB) const inline
Definition at line 329 of file SharedBuffer.h.
References FUniqueBuffer(), and ToPrivateOwnerPtr.
operator=() [1/2]
FUniqueBuffer & FUniqueBuffer::operator= (const FUniqueBuffer &) delete
References FUniqueBuffer().
operator=() [2/2]
FUniqueBuffer & FUniqueBuffer::operator= (FUniqueBuffer &&) default
References FUniqueBuffer().
operator==()
bool FUniqueBuffer::operator== (const FUniqueBuffer & BufferB) const inline
Definition at line 327 of file SharedBuffer.h.
References FUniqueBuffer(), and ToPrivateOwnerPtr.
Reset()
void FUniqueBuffer::Reset ()
Reset this to null.
TakeOwnership() [1/2]
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >(), std::declval< uint64 >())) *> FUniqueBuffer FUniqueBuffer::TakeOwnership (void * Data, uint64 Size, DeleteFunctionType && DeleteFunction) inline static nodiscard
Make an owned buffer by taking ownership of the input.
Parameters
DeleteFunction Called with Data to free memory when the last shared reference is released.
Definition at line 551 of file SharedBuffer.h.
References FUniqueBuffer(), Delete, Forward(), Invoke(), TakeOwnership, TakeOwnership(), and TSequenceHistory< HistorySize >::Size.
Referenced by TakeOwnership().
TakeOwnership() [2/2]
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >(), std::declval< uint64 >())) * = nullptr> FUniqueBuffer FUniqueBuffer::TakeOwnership (void * Data, uint64 Size, DeleteFunctionType && DeleteFunction) inline static nodiscard
Make an owned buffer by taking ownership of the input.
Parameters
DeleteFunction Called with (Data, Size) to free memory when the last shared reference is released.
References FUniqueBuffer(), and TSequenceHistory< HistorySize >::Size.
Friends And Related Symbol Documentation
FSharedBuffer
friend class FSharedBuffer friend
Definition at line 312 of file SharedBuffer.h.
References FSharedBuffer.
Referenced by FSharedBuffer, and MoveToShared().
GetTypeHash
uint32 GetTypeHash (const FUniqueBuffer & Buffer) friend
Definition at line 325 of file SharedBuffer.h.
References FUniqueBuffer(), Buffer, PointerHash(), and ToPrivateOwnerPtr.
ToPrivateOwnerPtr [1/2]
const FOwnerPtrType & ToPrivateOwnerPtr (const FUniqueBuffer & Buffer) friend
Definition at line 319 of file SharedBuffer.h.
References FUniqueBuffer(), and Buffer.
Referenced by GetTypeHash, operator!=(), and operator==().
ToPrivateOwnerPtr [2/2]
FOwnerPtrType ToPrivateOwnerPtr (FUniqueBuffer && Buffer) friend
Definition at line 320 of file SharedBuffer.h.
References FUniqueBuffer(), Buffer, and MoveTemp().
Field Documentation
Owner
FOwnerPtrType FUniqueBuffer::Owner private
Definition at line 322 of file SharedBuffer.h.
Referenced by FUniqueBuffer(), GetData(), GetData(), GetSize(), IsMaterialized(), IsNull(), and IsOwned().
The documentation for this class was generated from the following file:
SharedBuffer.h