Unreal Engine 5.6 C++ API: UE::CoreUObject Namespace Reference
UE::CoreUObject Namespace Reference
Namespaces
namespace Private
Enumerations
enum class EAllowSetNullOnNonNullableBehavior : uint8 { Disabled , Enabled }
Functions
EAllowSetNullOnNonNullableBehavior AllowSetNullOnNonNullableBehavior ()
template<typename UEnumType UE_REQUIRES>
bool TestEqual (const FString &What, const UEnumType Actual, const UEnumType Expected, FAutomationTestBase &InTestInstance)
Tests the equality of a UEnum.
template<typename UEnumType UE_REQUIRES>
bool TestNotEqual (const FString &What, const UEnumType Actual, const UEnumType Expected, FAutomationTestBase &InTestInstance)
Tests the inequality of a UEnum.
Enumeration Type Documentation
EAllowSetNullOnNonNullableBehavior
enum class UE::CoreUObject::EAllowSetNullOnNonNullableBehavior : uint8 strong
Enumerator
Disabled
Enabled
Definition at line 10 of file NonNullPropertyUtils.h.
Function Documentation
AllowSetNullOnNonNullableBehavior()
EAllowSetNullOnNonNullableBehavior UE::CoreUObject::AllowSetNullOnNonNullableBehavior () inline
Definition at line 44 of file NonNullPropertyUtils.h.
References Disabled.
TestEqual()
template<typename UEnumType UE_REQUIRES> bool UE::CoreUObject::TestEqual (const FString & What, const UEnumType Actual, const UEnumType Expected, FAutomationTestBase & InTestInstance)
Tests the equality of a UEnum.
Definition at line 15 of file UObjectTestUtils.h.
References StaticEnum(), and TEXT.
Referenced by FAutomationTestUObjectClassBase::TestEqual().
TestNotEqual()
template<typename UEnumType UE_REQUIRES> bool UE::CoreUObject::TestNotEqual (const FString & What, const UEnumType Actual, const UEnumType Expected, FAutomationTestBase & InTestInstance)
Tests the inequality of a UEnum.
Definition at line 45 of file UObjectTestUtils.h.
References StaticEnum(), and TEXT.
Referenced by FAutomationTestUObjectClassBase::TestNotEqual().