Unreal Engine 5.6 C++ API: IAssetFamily Class Reference
IAssetFamily Class Reference abstract
Represents a group of related assets, e.g.
#include "IAssetFamily.h"
Public Member Functions
virtual ~IAssetFamily ()
Virtual destructor.
DECLARE_EVENT (IAssetFamily, FOnAssetFamilyChanged) virtual FOnAssetFamilyChanged &GetOnAssetFamilyChanged()=0
Event fired when an asset family changes (e.g.
DECLARE_EVENT_OneParam (IAssetFamily, FOnAssetOpened, UObject *) virtual FOnAssetOpened &GetOnAssetOpened()=0
Event fired when an asset is opened.
virtual FAssetData FindAssetOfType (UClass *AssetType) const =0
Find the most relevant asset of a specified type.
virtual void FindAssetsOfType (UClass *AssetType, TArray< FAssetData > &OutAssets) const =0
Find all assets of a specified type.
template<typename AssetType>
FAssetData GetAsset ()
Find the most relevant asset of a specified type.
virtual UClass * GetAssetFamilyClass (UClass *InClass) const =0
template<typename AssetType>
void GetAssets (TArray< FAssetData > &OutAssets)
Find all assets of a specified type.
virtual const FSlateBrush * GetAssetTypeDisplayIcon (UClass *InAssetClass) const =0
Gets the slate brush that represents this asset family.
virtual FText GetAssetTypeDisplayName (UClass *InAssetClass) const =0
Gets the name of an asset that will be displayed to a user.
virtual FSlateColor GetAssetTypeDisplayTint (UClass *InAssetClass) const =0
Gets the color to tint the asset display icon.
virtual void GetAssetTypes (TArray< UClass * > &OutAssetTypes) const =0
Get all the asset classes this family supports (doesnt need to include derived classes)
virtual bool IsAssetCompatible (const FAssetData &InAssetData) const =0
Check whether an asset is compatible with this family.
UE_DEPRECATED (5.2, "Please use FPersonaModule::RecordAssetOpened to inform all asset familes rather than just one.") virtual void RecordAssetOpened(const FAssetData &InAssetData)=0
Record that an asset was opened.
Detailed Description
Represents a group of related assets, e.g.
a skeleton, its animations and skeletal meshes
Definition at line 12 of file IAssetFamily.h.
Constructor & Destructor Documentation
~IAssetFamily()
virtual IAssetFamily::~IAssetFamily () inline virtual
Virtual destructor.
Definition at line 16 of file IAssetFamily.h.
Member Function Documentation
DECLARE_EVENT()
IAssetFamily::DECLARE_EVENT (IAssetFamily , FOnAssetFamilyChanged) & pure virtual
Event fired when an asset family changes (e.g.
relationships are altered)
References DECLARE_EVENT().
Referenced by DECLARE_EVENT().
DECLARE_EVENT_OneParam()
IAssetFamily::DECLARE_EVENT_OneParam (IAssetFamily , FOnAssetOpened , UObject *) & pure virtual
Event fired when an asset is opened.
References DECLARE_EVENT_OneParam().
Referenced by DECLARE_EVENT_OneParam().
FindAssetOfType()
virtual FAssetData IAssetFamily::FindAssetOfType (UClass * AssetType) const pure virtual
Find the most relevant asset of a specified type.
Referenced by GetAsset().
FindAssetsOfType()
virtual void IAssetFamily::FindAssetsOfType (UClass * AssetType, TArray< FAssetData > & OutAssets) const pure virtual
Find all assets of a specified type.
Referenced by GetAssets().
GetAsset()
template<typename AssetType> FAssetData IAssetFamily::GetAsset () inline
Find the most relevant asset of a specified type.
Definition at line 26 of file IAssetFamily.h.
References FindAssetOfType().
GetAssetFamilyClass()
virtual UClass * IAssetFamily::GetAssetFamilyClass (UClass * InClass) const pure virtual
Returns
the outermost superclass of the passed-in class for this asset family
GetAssets()
template<typename AssetType> void IAssetFamily::GetAssets (TArray< FAssetData > & OutAssets) inline
Find all assets of a specified type.
Definition at line 36 of file IAssetFamily.h.
References FindAssetsOfType().
GetAssetTypeDisplayIcon()
virtual const FSlateBrush * IAssetFamily::GetAssetTypeDisplayIcon (UClass * InAssetClass) const pure virtual
Gets the slate brush that represents this asset family.
GetAssetTypeDisplayName()
virtual FText IAssetFamily::GetAssetTypeDisplayName (UClass * InAssetClass) const pure virtual
Gets the name of an asset that will be displayed to a user.
GetAssetTypeDisplayTint()
virtual FSlateColor IAssetFamily::GetAssetTypeDisplayTint (UClass * InAssetClass) const pure virtual
Gets the color to tint the asset display icon.
GetAssetTypes()
virtual void IAssetFamily::GetAssetTypes (TArray< UClass * > & OutAssetTypes) const pure virtual
Get all the asset classes this family supports (doesnt need to include derived classes)
IsAssetCompatible()
virtual bool IAssetFamily::IsAssetCompatible (const FAssetData & InAssetData) const pure virtual
Check whether an asset is compatible with this family.
UE_DEPRECATED()
IAssetFamily::UE_DEPRECATED (5. 2, "Please use FPersonaModule::RecordAssetOpened to inform all asset familes rather than just one.") const & pure virtual
Record that an asset was opened.
The documentation for this class was generated from the following file:
IAssetFamily.h