Unreal Engine 5.6 C++ API: AnimEncoding Class Reference
AnimEncoding Class Reference
#include "AnimEncoding.h"
Static Protected Member Functions
static float TimeToIndex (EAnimInterpolationType Interpolation, int32 NumberOfFrames, const uint8 *FrameTable, float RelativePos, int32 NumKeys, int32 &PosIndex0Out, int32 &PosIndex1Out)
Utility function to determine the two key indices to interpolate given a relative position in the animation.
static float TimeToIndex (float SequenceLength, float RelativePos, int32 NumKeys, EAnimInterpolationType Interpolation, int32 &PosIndex0Out, int32 &PosIndex1Out)
Handles Byte-swapping incoming animation data from a MemoryReader.
Detailed Description
Definition at line 121 of file AnimEncoding.h.
Member Function Documentation
TimeToIndex() [1/2]
FORCEINLINE float AnimEncoding::TimeToIndex (EAnimInterpolationType Interpolation, int32 NumberOfFrames, const uint8 * FrameTable, float RelativePos, int32 NumKeys, int32 & PosIndex0Out, int32 & PosIndex1Out) static protected
Utility function to determine the two key indices to interpolate given a relative position in the animation.
Parameters
Interpolation The Interpolation type of the sequence
NumberOfFrames The number of frames in the original sequence
FrameTable The frame table containing a frame index for each key.
RelativePos The relative position to solve in the range [0,1] inclusive.
NumKeys The number of keys present in the track being solved.
PosIndex0Out Output value for the closest key index before the RelativePos specified.
PosIndex1Out Output value for the closest key index after the RelativePos specified.
Returns
The rate at which to interpolate the two keys returned to obtain the final result.
Parameters
Seq The UAnimSequence container.
FrameTable The frame table containing a frame index for each key.
RelativePos The relative position to solve in the range [0,1] inclusive.
NumKeys The number of keys present in the track being solved.
PosIndex0Out Output value for the closest key index before the RelativePos specified.
PosIndex1Out Output value for the closest key index after the RelativePos specified.
Returns
The rate at which to interpolate the two keys returned to obtain the final result.
Definition at line 514 of file AnimEncoding.h.
References Alpha, check, FMath::Clamp(), FindLowKeyIndex(), float, FORCEINLINE, Interpolation, and FMath::Max.
TimeToIndex() [2/2]
FORCEINLINE float AnimEncoding::TimeToIndex (float SequenceLength, float RelativePos, int32 NumKeys, EAnimInterpolationType Interpolation, int32 & PosIndex0Out, int32 & PosIndex1Out) static protected virtual
Handles Byte-swapping incoming animation data from a MemoryReader.
Utility function to determine the two key indices to interpolate given a relative position in the animation.
Parameters
CompressedData The compressed animation data being operated on.
MemoryReader The MemoryReader object to read from.
SourceArVersion The version of the archive that the data is coming from. Handles Byte-swapping outgoing animation data to an array of BYTEs
CompressedData The compressed animation data being operated on.
SerializedData The output buffer.
ForceByteSwapping true is byte swapping is not optional. Decompress all requested rotation components from an Animation Sequence
Atoms The FTransform array to fill in.
DesiredPairs Array of requested bone information
DecompContext The decompression context to use. Decompress all requested translation components from an Animation Sequence
Atoms The FTransform array to fill in.
DesiredPairs Array of requested bone information
DecompContext The decompression context to use. Decompress all requested translation components from an Animation Sequence
Atoms The FTransform array to fill in.
DesiredPairs Array of requested bone information
DecompContext The decompression context to use. Utility function to determine the two key indices to interpolate given a relative position in the animation
SequenceLength The length of the anim sequence
RelativePos The relative position to solve in the range [0,1] inclusive.
NumKeys The number of keys present in the track being solved.
Interpolation The Interpolation type of the sequence
PosIndex0Out Output value for the closest key index before the RelativePos specified.
PosIndex1Out Output value for the closest key index after the RelativePos specified.
Returns
The rate at which to interpolate the two keys returned to obtain the final result.
Parameters
Seq The UAnimSequence container.
RelativePos The relative position to solve in the range [0,1] inclusive.
NumKeys The number of keys present in the track being solved.
PosIndex0Out Output value for the closest key index before the RelativePos specified.
PosIndex1Out Output value for the closest key index after the RelativePos specified.
Returns
The rate at which to interpolate the two keys returned to obtain the final result.
Definition at line 399 of file AnimEncoding.h.
References Alpha, checkSlow, float, FORCEINLINE, Interpolation, FMath::Min, and SequenceLength.
Referenced by AEFConstantKeyLerp< FORMAT >::GetBoneAtomRotation(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomRotation(), AEFConstantKeyLerp< FORMAT >::GetBoneAtomScale(), AEFVariableKeyLerp< FORMAT >::GetBoneAtomScale(), AEFConstantKeyLerp< FORMAT >::GetBoneAtomTranslation(), and AEFVariableKeyLerp< FORMAT >::GetBoneAtomTranslation().
The documentation for this class was generated from the following file:
AnimEncoding.h