Unreal Engine 5.6 C++ API: ISequencerSection Class Reference
ISequencerSection Class Reference abstract
Interface that should be implemented for the UI portion of a section.
#include "ISequencerSection.h"
Data Structures
struct FChannelData
Structure used during key area creation to group channels by their group name.
Public Member Functions
virtual ~ISequencerSection ()
virtual SEQUENCER_API void BeginDilateSection ()
Dilation starts with a drag operation.
virtual void BeginResizeSection ()
Resize the section.
virtual void BeginSlipSection ()
Slips the section by a specific factor.
virtual void BuildSectionContextMenu (FMenuBuilder &MenuBuilder, const FGuid &ObjectBinding)
Builds up the section context menu for the outliner.
virtual void BuildSectionSidebarMenu (FMenuBuilder &MenuBuilder, const FGuid &ObjectBinding)
Builds up the section sidebar menu for the outliner.
virtual TSharedPtr< UE::Sequencer::FCategoryModel > ConstructCategoryModel (FName InCategoryName, const FText &InDisplayText, TArrayView< const FChannelData > Channels) const
Create a custom category model.
virtual TSharedPtr< UE::Sequencer::FChannelModel > ConstructChannelModel (FName InChannelName, const FMovieSceneChannelHandle &InChannelHandle) const
Create a custom channel model.
virtual SEQUENCER_API void CreateViewWidgets (const UE::Sequencer::FCreateSectionViewWidgetParams &Params)
Create view widgets for the section by adding the necessary widgets to the overlay widget.
virtual void CustomizePropertiesDetailsView (TSharedRef< IDetailsView > DetailsView, const FSequencerSectionPropertyDetailsViewCustomizationParams &InParams) const
Called when the properties context menu is being built, so this section can customize how the menu's details view looks like.
virtual SEQUENCER_API void DilateSection (const TRange< FFrameNumber > &NewRange, float DilationFactor)
New Range that's set as we Dilate.
virtual SEQUENCER_API void GenerateSectionLayout (class ISectionLayoutBuilder &LayoutBuilder)
Generates the inner layout for this section.
virtual TSharedRef< SWidget > GenerateSectionWidget ()
Allows each section to have it's own unique widget for advanced editing functionality OnPaintSection will still be called if a widget is provided.
virtual FMargin GetContentPadding () const
virtual FVector2D GetKeySize () const
@ return The size of keyframe widgets
virtual float GetSectionGripHeight (float InSectionHeight) const
virtual float GetSectionGripSize () const
virtual SEQUENCER_API float GetSectionHeight (const UE::Sequencer::FViewDensityInfo &ViewDensity) const
virtual UMovieSceneSection * GetSectionObject ()=0
The MovieSceneSection data being visualized.
virtual TOptional< FFrameTime > GetSectionTime (FSequencerSectionPainter &InPainter) const
virtual FText GetSectionTitle () const
virtual FText GetSectionToolTip () const
virtual bool IsReadOnly () const
virtual FReply OnKeyDoubleClicked (const TArray< FKeyHandle > &KeyHandles)
Called when a key on this section is double clicked.
virtual int32 OnPaintSection (FSequencerSectionPainter &InPainter) const =0
Called when the section should be painted.
virtual FReply OnSectionDoubleClicked (const FGeometry &SectionGeometry, const FPointerEvent &MouseEvent)
Called when the section is double clicked.
virtual FReply OnSectionDoubleClicked (const FGeometry &SectionGeometry, const FPointerEvent &MouseEvent, const FGuid &ObjectBinding)
Called when the section is double clicked.
virtual bool RequestDeleteCategory (const TArray< FName > &CategoryNamePath)
Called when the user requests that a category from this section be deleted.
virtual bool RequestDeleteKeyArea (const TArray< FName > &KeyAreaNamePath)
Called when the user requests that a key area from this section be deleted.
virtual SEQUENCER_API void ResizeSection (ESequencerSectionResizeMode ResizeMode, FFrameNumber ResizeFrameNumber)
virtual bool SectionIsResizable () const
virtual void SlipSection (FFrameNumber SlipTime)
virtual void Tick (const FGeometry &AllottedGeometry, const FGeometry &ClippedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks the section during the Slate tick.
UE_DEPRECATED (5.4, "Please call GetSectionHeight(const FViewDensityInfo& ViewDensity) instead.") SEQUENCER_API virtual float GetSectionHeight() const
Detailed Description
Interface that should be implemented for the UI portion of a section.
Definition at line 119 of file ISequencerSection.h.
Constructor & Destructor Documentation
~ISequencerSection()
virtual ISequencerSection::~ISequencerSection () inline virtual
Definition at line 132 of file ISequencerSection.h.
Member Function Documentation
BeginDilateSection()
virtual SEQUENCER_API void ISequencerSection::BeginDilateSection () inline virtual
Dilation starts with a drag operation.
Reimplemented in FChaosCacheSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 321 of file ISequencerSection.h.
BeginResizeSection()
virtual void ISequencerSection::BeginResizeSection () inline virtual
Resize the section.
Parameters
ResizeMode Resize either the leading or the trailing edge of the section
ResizeTime The time to resize to
Reimplemented in FAudioSection, FChaosCacheSection, FMediaThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 307 of file ISequencerSection.h.
BeginSlipSection()
virtual void ISequencerSection::BeginSlipSection () inline virtual
Slips the section by a specific factor.
Parameters
SlipTime The amount to slip this section by
Reimplemented in FAudioSection, FChaosCacheSection, FMediaThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 315 of file ISequencerSection.h.
BuildSectionContextMenu()
virtual void ISequencerSection::BuildSectionContextMenu (FMenuBuilder & MenuBuilder, const FGuid & ObjectBinding) inline virtual
Builds up the section context menu for the outliner.
Parameters
MenuBuilder The menu builder to change
ObjectBinding The object guid bound to this section
Reimplemented in FThumbnailSection, and UE::Sequencer::FCommonAnimationSection.
Definition at line 272 of file ISequencerSection.h.
Referenced by BuildSectionSidebarMenu().
BuildSectionSidebarMenu()
virtual void ISequencerSection::BuildSectionSidebarMenu (FMenuBuilder & MenuBuilder, const FGuid & ObjectBinding) inline virtual
Builds up the section sidebar menu for the outliner.
Parameters
MenuBuilder The menu builder to change
ObjectBinding The object guid bound to this section
Reimplemented in FThumbnailSection.
Definition at line 280 of file ISequencerSection.h.
References BuildSectionContextMenu().
ConstructCategoryModel()
virtual TSharedPtr< UE::Sequencer::FCategoryModel > ISequencerSection::ConstructCategoryModel (FName InCategoryName, const FText & InDisplayText, TArrayView< const FChannelData > Channels) const inline virtual
Create a custom category model.
Definition at line 216 of file ISequencerSection.h.
ConstructChannelModel()
virtual TSharedPtr< UE::Sequencer::FChannelModel > ISequencerSection::ConstructChannelModel (FName InChannelName, const FMovieSceneChannelHandle & InChannelHandle) const inline virtual
Create a custom channel model.
Definition at line 221 of file ISequencerSection.h.
CreateViewWidgets()
virtual SEQUENCER_API void ISequencerSection::CreateViewWidgets (const UE::Sequencer::FCreateSectionViewWidgetParams & Params) virtual
Create view widgets for the section by adding the necessary widgets to the overlay widget.
References Params.
CustomizePropertiesDetailsView()
virtual void ISequencerSection::CustomizePropertiesDetailsView (TSharedRef< IDetailsView > DetailsView, const FSequencerSectionPropertyDetailsViewCustomizationParams & InParams) const inline virtual
Called when the properties context menu is being built, so this section can customize how the menu's details view looks like.
Parameters
DetailsView The details view widget
InParams Information about the current operation
Reimplemented in UE::Sequencer::FCommonAnimationSection.
Definition at line 337 of file ISequencerSection.h.
DilateSection()
virtual SEQUENCER_API void ISequencerSection::DilateSection (const TRange< FFrameNumber > & NewRange, float DilationFactor) inline virtual
New Range that's set as we Dilate.
Parameters
NewRange The NewRange.
DilationFactor The factor we have dilated from the beginning of the drag
Reimplemented in FChaosCacheSection, FSequencerSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 327 of file ISequencerSection.h.
GenerateSectionLayout()
virtual SEQUENCER_API void ISequencerSection::GenerateSectionLayout (class ISectionLayoutBuilder & LayoutBuilder) virtual
Generates the inner layout for this section.
Parameters
LayoutBuilder The builder utility for creating section layouts
GenerateSectionWidget()
virtual TSharedRef< SWidget > ISequencerSection::GenerateSectionWidget () inline virtual
Allows each section to have it's own unique widget for advanced editing functionality OnPaintSection will still be called if a widget is provided.
OnPaintSection is still used for the background section display
Returns
The generated widget
Reimplemented in FThumbnailSection.
Definition at line 152 of file ISequencerSection.h.
References SNullWidget::NullWidget.
GetContentPadding()
virtual FMargin ISequencerSection::GetContentPadding () const inline virtual
Returns
The amount of padding to apply to non-interactive portions of the section interface (such as section text)
Reimplemented in FMediaThumbnailSection, and UE::Sequencer::FCommonAnimationSection.
Definition at line 204 of file ISequencerSection.h.
Referenced by TSubSectionMixin< ParentSectionClass >::OnPaintSection().
GetKeySize()
virtual FVector2D ISequencerSection::GetKeySize () const inline virtual
@ return The size of keyframe widgets
Definition at line 244 of file ISequencerSection.h.
References SequencerSectionConstants::KeySize().
GetSectionGripHeight()
virtual float ISequencerSection::GetSectionGripHeight (float InSectionHeight) const inline virtual
Returns
The height of the section drag handles
Definition at line 239 of file ISequencerSection.h.
GetSectionGripSize()
virtual float ISequencerSection::GetSectionGripSize () const inline virtual
Returns
The width of the section drag handles
Reimplemented in FThumbnailSection.
Definition at line 234 of file ISequencerSection.h.
References SequencerSectionConstants::DefaultSectionGripSize, and GetSectionGripSize().
Referenced by GetSectionGripSize().
GetSectionHeight()
virtual SEQUENCER_API float ISequencerSection::GetSectionHeight (const UE::Sequencer::FViewDensityInfo & ViewDensity) const virtual
Reimplemented in FAudioSection, FChaosCacheSection, FMediaThumbnailSection, FThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
References GetSectionHeight().
Referenced by GetSectionHeight(), and UE_DEPRECATED().
GetSectionObject()
virtual UMovieSceneSection * ISequencerSection::GetSectionObject () pure virtual
The MovieSceneSection data being visualized.
Implemented in FAudioSection, FChaosCacheSection, FSequencerSection, FThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
GetSectionTime()
virtual TOptional< FFrameTime > ISequencerSection::GetSectionTime (FSequencerSectionPainter & InPainter) const inline virtual
Returns
The local section time
Reimplemented in FAudioSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 199 of file ISequencerSection.h.
GetSectionTitle()
virtual FText ISequencerSection::GetSectionTitle () const inline virtual
Returns
The display name of the section in the section view
Reimplemented in FAudioSection, FChaosCacheSection, FMediaThumbnailSection, FThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 189 of file ISequencerSection.h.
Referenced by GetSectionToolTip().
GetSectionToolTip()
virtual FText ISequencerSection::GetSectionToolTip () const inline virtual
Returns
The ToolTip for the section in the section view. By default, the section title
Reimplemented in FAudioSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 194 of file ISequencerSection.h.
References GetSectionTitle().
IsReadOnly()
virtual bool ISequencerSection::IsReadOnly () const inline virtual
Returns
Whether this section is read only.
Reimplemented in FSequencerSection, and TSubSectionMixin< ParentSectionClass >.
Definition at line 254 of file ISequencerSection.h.
OnKeyDoubleClicked()
virtual FReply ISequencerSection::OnKeyDoubleClicked (const TArray< FKeyHandle > & KeyHandles) inline virtual
Called when a key on this section is double clicked.
Parameters
KeyHandles The array of keys that were clicked
Returns
A reply in response to double clicking the key
Reimplemented in FColorPropertySection.
Definition at line 184 of file ISequencerSection.h.
References FReply::Unhandled().
OnPaintSection()
virtual int32 ISequencerSection::OnPaintSection (FSequencerSectionPainter & InPainter) const pure virtual
Called when the section should be painted.
Parameters
Painter Structure that affords common painting operations
Returns
The new LayerId
Implemented in FAudioSection, FBoolPropertySection, FChaosCacheSection, FColorPropertySection, FMediaThumbnailSection, FSequencerSection, FThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
OnSectionDoubleClicked() [1/2]
virtual FReply ISequencerSection::OnSectionDoubleClicked (const FGeometry & SectionGeometry, const FPointerEvent & MouseEvent) inline virtual
Called when the section is double clicked.
Parameters
SectionGeometry Geometry of the section
MouseEvent Event causing the double click
Returns
A reply in response to double clicking the section
Reimplemented in TSubSectionMixin< ParentSectionClass >.
Definition at line 166 of file ISequencerSection.h.
References MouseEvent, and FReply::Unhandled().
OnSectionDoubleClicked() [2/2]
virtual FReply ISequencerSection::OnSectionDoubleClicked (const FGeometry & SectionGeometry, const FPointerEvent & MouseEvent, const FGuid & ObjectBinding) inline virtual
Called when the section is double clicked.
Parameters
SectionGeometry Geometry of the section
MouseEvent Event causing the double click
ObjectBinding The object guid bound to this section
Returns
A reply in response to double clicking the section
Definition at line 176 of file ISequencerSection.h.
References MouseEvent, and FReply::Unhandled().
RequestDeleteCategory()
virtual bool ISequencerSection::RequestDeleteCategory (const TArray< FName > & CategoryNamePath) inline virtual
Called when the user requests that a category from this section be deleted.
Parameters
CategoryNamePath An array of category names which is the path to the category to be deleted.
Returns
Whether or not the category was deleted.
Definition at line 291 of file ISequencerSection.h.
RequestDeleteKeyArea()
virtual bool ISequencerSection::RequestDeleteKeyArea (const TArray< FName > & KeyAreaNamePath) inline virtual
Called when the user requests that a key area from this section be deleted.
Parameters
KeyAreaNamePath An array of names representing the path of to the key area to delete, starting with any categories which contain the key area.
Returns
Whether or not the key area was deleted.
Reimplemented in TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 299 of file ISequencerSection.h.
ResizeSection()
virtual SEQUENCER_API void ISequencerSection::ResizeSection (ESequencerSectionResizeMode ResizeMode, FFrameNumber ResizeFrameNumber) virtual
Reimplemented in FAudioSection, FChaosCacheSection, FMediaThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
SectionIsResizable()
virtual bool ISequencerSection::SectionIsResizable () const inline virtual
Returns
Whether or not the user can resize this section.
Definition at line 249 of file ISequencerSection.h.
SlipSection()
virtual void ISequencerSection::SlipSection (FFrameNumber SlipTime) inline virtual
Reimplemented in FAudioSection, FChaosCacheSection, FMediaThumbnailSection, TSubSectionMixin< ParentSectionClass >, and UE::Sequencer::FCommonAnimationSection.
Definition at line 316 of file ISequencerSection.h.
Tick()
virtual void ISequencerSection::Tick (const FGeometry & AllottedGeometry, const FGeometry & ClippedGeometry, const double InCurrentTime, const float InDeltaTime) inline virtual
Ticks the section during the Slate tick.
Parameters
AllottedGeometry The space allotted for this widget
ClippedGeometry The space for this widget clipped against the parent widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented in FAudioSection, FMediaThumbnailSection, and FThumbnailSection.
Definition at line 264 of file ISequencerSection.h.
UE_DEPRECATED()
ISequencerSection::UE_DEPRECATED (5. 4, "Please call GetSectionHeight(const FViewDensityInfo& ViewDensity) instead.") const
Returns
The height of the section
References GetSectionHeight().
The documentation for this class was generated from the following file:
ISequencerSection.h