Unreal Engine 5.6 C++ API: FGenericPlatformMemory::FSharedMemoryRegion Struct Reference
FGenericPlatformMemory::FSharedMemoryRegion Struct Reference
Generic representation of a shared memory region.
#include "GenericPlatformMemory.h"
Public Member Functions
FSharedMemoryRegion (const FString &InName, uint32 InAccessMode, void *InAddress, SIZE_T InSize)
void * GetAddress ()
Returns the beginning of the region in process address space.
const void * GetAddress () const
Returns the beginning of the region in process address space.
const TCHAR * GetName () const
Returns the name of the region.
SIZE_T GetSize () const
Returns size of the region in bytes.
Protected Types
enum Limits { MaxSharedMemoryName = 128 }
Protected Attributes
uint32 AccessMode
Access mode for the region.
void * Address
The actual buffer.
TCHAR Name [MaxSharedMemoryName]
Name of the region.
SIZE_T Size
Size of the buffer.
Detailed Description
Generic representation of a shared memory region.
Definition at line 292 of file GenericPlatformMemory.h.
Member Enumeration Documentation
Limits
enum FGenericPlatformMemory::FSharedMemoryRegion::Limits protected
Enumerator
MaxSharedMemoryName
Definition at line 311 of file GenericPlatformMemory.h.
Constructor & Destructor Documentation
FSharedMemoryRegion()
FGenericPlatformMemory::FSharedMemoryRegion::FSharedMemoryRegion (const FString & InName, uint32 InAccessMode, void * InAddress, SIZE_T InSize)
References InName.
Referenced by FMacPlatformMemory::FMacSharedMemoryRegion::FMacSharedMemoryRegion(), FUnixPlatformMemory::FUnixSharedMemoryRegion::FUnixSharedMemoryRegion(), and FWindowsPlatformMemory::FWindowsSharedMemoryRegion::FWindowsSharedMemoryRegion().
Member Function Documentation
GetAddress() [1/2]
void * FGenericPlatformMemory::FSharedMemoryRegion::GetAddress () inline
Returns the beginning of the region in process address space.
Definition at line 298 of file GenericPlatformMemory.h.
References Address.
GetAddress() [2/2]
const void * FGenericPlatformMemory::FSharedMemoryRegion::GetAddress () const inline
Returns the beginning of the region in process address space.
Definition at line 301 of file GenericPlatformMemory.h.
References Address.
GetName()
const TCHAR * FGenericPlatformMemory::FSharedMemoryRegion::GetName () const inline
Returns the name of the region.
Definition at line 295 of file GenericPlatformMemory.h.
References Name.
GetSize()
SIZE_T FGenericPlatformMemory::FSharedMemoryRegion::GetSize () const inline
Returns size of the region in bytes.
Definition at line 304 of file GenericPlatformMemory.h.
References Size.
Field Documentation
AccessMode
uint32 FGenericPlatformMemory::FSharedMemoryRegion::AccessMode protected
Access mode for the region.
Definition at line 320 of file GenericPlatformMemory.h.
Address
void* FGenericPlatformMemory::FSharedMemoryRegion::Address protected
The actual buffer.
Definition at line 323 of file GenericPlatformMemory.h.
Referenced by GetAddress(), and GetAddress().
Name
TCHAR FGenericPlatformMemory::FSharedMemoryRegion::Name[MaxSharedMemoryName] protected
Name of the region.
Definition at line 317 of file GenericPlatformMemory.h.
Referenced by GetName().
Size
SIZE_T FGenericPlatformMemory::FSharedMemoryRegion::Size protected
Size of the buffer.
Definition at line 326 of file GenericPlatformMemory.h.
Referenced by GetSize().
The documentation for this struct was generated from the following file:
GenericPlatformMemory.h