Unreal Engine 5.6 C++ API: FBaseToolkit Class Reference
FBaseToolkit Class Reference abstract
Base class for all toolkits (abstract).
#include "BaseToolkit.h"
Public Member Functions
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual FEditorModeTools & GetEditorModeManager () const =0
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const override
virtual FText GetTabSuffix () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API FName GetToolkitContextFName () const override
virtual UNREALED_API const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsBlueprintEditor () const override
virtual UNREALED_API bool IsHosted () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Protected Member Functions
virtual UNREALED_API void CreateEditorModeManager ()
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Attributes
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Detailed Description
Base class for all toolkits (abstract).
Definition at line 27 of file BaseToolkit.h.
Constructor & Destructor Documentation
FBaseToolkit()
UNREALED_API FBaseToolkit::FBaseToolkit ()
FBaseToolkit constructor.
~FBaseToolkit()
virtual UNREALED_API FBaseToolkit::~FBaseToolkit () virtual
Virtual destructor.
Member Function Documentation
BringToolkitToFront()
virtual UNREALED_API void FBaseToolkit::BringToolkitToFront () override virtual
Referenced by FRigVMNewEditor::BringToolkitToFrontImpl().
CreateEditorModeManager()
virtual UNREALED_API void FBaseToolkit::CreateEditorModeManager () protected virtual
Reimplemented in FAssetEditorToolkit, FBaseAssetToolkit, FPersonaAssetEditorToolkit, and FWidgetBlueprintEditor.
GetEditorModeManager()
virtual FEditorModeTools & FBaseToolkit::GetEditorModeManager () const pure virtual
Implemented in FAssetEditorToolkit, and FModeToolkit.
GetInlineContent()
virtual UNREALED_API TSharedPtr< SWidget > FBaseToolkit::GetInlineContent () const override virtual
Reimplemented in FFractureEditorModeToolkit, and FModeToolkit.
GetTabColorScale()
UNREALED_API FLinearColor FBaseToolkit::GetTabColorScale () const protected
Returns
Returns the color to use for tabs created for this toolkit. In world-centric mode, tabs may be colored to make them more easy to distinguish compared to other tabs.
GetTabPrefix()
UNREALED_API FString FBaseToolkit::GetTabPrefix () const protected
Returns
Returns the prefix string to use for tabs created for this toolkit. In world-centric mode, tabs get a name prefix to make them distinguishable from other tabs
GetTabSuffix()
virtual FText FBaseToolkit::GetTabSuffix () const inline override virtual
Reimplemented in FAssetEditorToolkit.
Definition at line 43 of file BaseToolkit.h.
References FText::GetEmpty().
GetToolkitCommands()
const TSharedRef< FUICommandList > FBaseToolkit::GetToolkitCommands () const inline
Returns
Returns our toolkit command list
Definition at line 60 of file BaseToolkit.h.
References ToolkitCommands.
GetToolkitContextFName()
virtual UNREALED_API FName FBaseToolkit::GetToolkitContextFName () const override virtual
Reimplemented in FBlueprintEditor, and FWidgetBlueprintEditor.
GetToolkitHost()
virtual UNREALED_API const TSharedRef< IToolkitHost > FBaseToolkit::GetToolkitHost () const override virtual
Reimplemented in FRigVMNewEditor.
Referenced by FRigVMNewEditor::GetToolkitHost().
GetWorkspaceMenuCategory()
virtual TSharedRef< FWorkspaceItem > FBaseToolkit::GetWorkspaceMenuCategory () const inline override virtual
Definition at line 50 of file BaseToolkit.h.
References WorkspaceMenuCategory.
IsBlueprintEditor()
virtual UNREALED_API bool FBaseToolkit::IsBlueprintEditor () const override virtual
Reimplemented in FBlueprintEditor.
IsHosted()
virtual UNREALED_API bool FBaseToolkit::IsHosted () const override virtual
Reimplemented in FRigVMNewEditor.
Referenced by FRigVMNewEditor::IsHosted().
IsWorldCentricAssetEditor()
UNREALED_API bool FBaseToolkit::IsWorldCentricAssetEditor () const
Returns
Returns true if this is a world-centric asset editor. That is, the user is editing the asset inline in a Level Editor app.
ProcessCommandBindings()
virtual UNREALED_API bool FBaseToolkit::ProcessCommandBindings (const FKeyEvent & InKeyEvent) const override virtual
Field Documentation
ToolkitCommands
TSharedRef<FUICommandList> FBaseToolkit::ToolkitCommands protected
List of UI commands for this toolkit.
This should be filled in by the derived class!
Definition at line 84 of file BaseToolkit.h.
Referenced by GetToolkitCommands(), and FRigVMNewEditor::GetToolkitCommands().
ToolkitHost
TWeakPtr<IToolkitHost> FBaseToolkit::ToolkitHost protected
The host application for this editor.
If editing in world-centric mode, this is the level level editor that we're editing the asset within Use GetToolkitHost() method to access this member.
Definition at line 88 of file BaseToolkit.h.
Referenced by FAssetEditorToolkit::SetPreviousWorldCentricToolkitHostForNewAssetEditor().
ToolkitMode
EToolkitMode::Type FBaseToolkit::ToolkitMode protected
Asset editing mode, set at creation-time and never changes.
Definition at line 81 of file BaseToolkit.h.
WorkspaceMenuCategory
TSharedPtr<FWorkspaceItem> FBaseToolkit::WorkspaceMenuCategory protected
The workspace menu category of this toolkit.
Definition at line 91 of file BaseToolkit.h.
Referenced by GetWorkspaceMenuCategory().
The documentation for this class was generated from the following file:
BaseToolkit.h