Unreal Engine 5.6 C++ API: UE::Geometry::FSegmentTree3 Class Reference
UE::Geometry::FSegmentTree3 Class Reference
FSegmentTree3 is a spatial data structure for a set of 3D line segments.
#include "SegmentTree3.h"
Data Structures
struct FBoxesSet
struct FRayNearestSegmentInfo
Information on a nearest-segment returned by query functions.
struct FSegment
FSegment is a 3D line segment with an external identifier.
struct FTreeBox
Public Types
using GetSplitAxisFunc = TUniqueFunction<int(int Depth, const FAxisAlignedBox3d& Box)>
Public Member Functions
template<typename SegmentIDEnumerable, typename GetSegmentFunc>
void Build (SegmentIDEnumerable Enumerable, GetSegmentFunc GetSegmentForID, int32 NumSegmentsHint=0)
Build the segment tree based on the given Enumerable (ie something that supports a range-based for loop over a set of integer IDs) and a function GetSegmentForID that returns the 3D line segment for a given ID.
bool FindNearestSegment (const FVector3d &P, FSegment &NearestSegmentOut, const IMeshSpatial::FQueryOptions &Options=IMeshSpatial::FQueryOptions()) const
Find the nearest segment to query point P, and return it in NearestSegmentOut.
bool FindNearestVisibleSegmentHitByRay (const FRay3d &Ray, TFunctionRef< bool(int32, const FVector3d &, const FVector3d &)> WithinToleranceCheck, FSegment &NearestHitSegmentOut, FRayNearestSegmentInfo &NearestInfo, const IMeshSpatial::FQueryOptions &Options=IMeshSpatial::FQueryOptions()) const
Find the segment that is hit by a 3D ray under a function WithinToleranceCheck, which will be called with the Ray and Segment points.
void SetTolerance (double Tolerance)
Sets the box intersection tolerance TODO: move into the IMeshSpatial::FQueryOptions and delete this function.
Protected Member Functions
void BuildTopDown (TArray< int > &SegmentIndices, TArray< FVector3d > &SegmentCenters, int32 NumSegments)
void FindNearestSegmentInternal (int BoxIndex, const FVector3d &P, double &NearestDistSqr, int &NearSegmentIdx, const IMeshSpatial::FQueryOptions &Options) const
void FindNearestVisibleSegmentHitByRayInternal (int BoxIndex, const FRay3d &Ray, TFunctionRef< bool(int32, const FVector3d &, const FVector3d &)> WithinToleranceCheck, int &NearSegmentIdx, FRayNearestSegmentInfo &NearestInfo, const IMeshSpatial::FQueryOptions &Options) const
double GetBoxDistanceSqr (int BoxIndex, const FVector3d &V) const
double GetRayBoxIntersectionParam (int BoxIndex, const FRay3d &Ray, double Radius=0) const
int SplitSegmentSetMidpoints (TArray< int > &SegmentIndices, TArray< FVector3d > &SegmentCenters, int StartIdx, int Count, int Depth, int MinSegmentCount, FBoxesSet &SegmentBoxes, FBoxesSet &Nodes, FAxisAlignedBox3d &Box)
Static Protected Member Functions
static GetSplitAxisFunc MakeDefaultSplitAxisFunc ()
Protected Attributes
double BoxEps = FMathd::ZeroTolerance
GetSplitAxisFunc GetSplitAxis = MakeDefaultSplitAxisFunc()
TArray< int > IndexList
int RootBoxIndex = -1
TArray< FSegment > SegmentList
int SegmentsEnd = -1
int TopDownLeafMaxSegmentCount = 8
TArray< FTreeBox > TreeBoxes
Detailed Description
FSegmentTree3 is a spatial data structure for a set of 3D line segments.
The line segments are provided externally, and each segment can have an arbitrary ID. The line segment geometry (ie endpoints) are stored directly by FSegmentTree3, so the class does not hold onto any reference to the source geometry (ie unlike FMeshAABBTree3).
Available queries:
FindNearestSegment(Point) - finds the nearest segment to the 3D point
FindNearestVisibleSegmentHitByRay(Ray) - finds the nearest segment that is "hit" by the ray under a tolerance check (see comments below). This is mainly intended for UI hit testing.
Definition at line 35 of file SegmentTree3.h.
Member Typedef Documentation
GetSplitAxisFunc
using UE::Geometry::FSegmentTree3::GetSplitAxisFunc = TUniqueFunction<int(int Depth, const FAxisAlignedBox3d& Box)>
Definition at line 38 of file SegmentTree3.h.
Member Function Documentation
Build()
template<typename SegmentIDEnumerable, typename GetSegmentFunc> void UE::Geometry::FSegmentTree3::Build (SegmentIDEnumerable Enumerable, GetSegmentFunc GetSegmentForID, int32 NumSegmentsHint = 0) inline
Build the segment tree based on the given Enumerable (ie something that supports a range-based for loop over a set of integer IDs) and a function GetSegmentForID that returns the 3D line segment for a given ID.
Gaps/etc are allowed but all enumerated IDs must be valid.
Definition at line 57 of file SegmentTree3.h.
References TArray< InElementType, InAllocatorType >::Add(), BuildTopDown(), TArray< InElementType, InAllocatorType >::Reserve(), Segment, and SegmentList.
BuildTopDown()
void UE::Geometry::FSegmentTree3::BuildTopDown (TArray< int > & SegmentIndices, TArray< FVector3d > & SegmentCenters, int32 NumSegments) inline protected
Definition at line 221 of file SegmentTree3.h.
References UE::Geometry::FSegmentTree3::FBoxesSet::Boxes, UE::Geometry::FSegmentTree3::FBoxesSet::IBoxCur, UE::Geometry::FSegmentTree3::FBoxesSet::IIndicesCur, UE::Geometry::FSegmentTree3::FBoxesSet::IndexList, IndexList, UE::Geometry::TDynamicVector< Type, BlockSize >::InsertAt(), UE::Geometry::TDynamicVector< Type, BlockSize >::Num(), RootBoxIndex, SegmentsEnd, SplitSegmentSetMidpoints(), TopDownLeafMaxSegmentCount, and TreeBoxes.
Referenced by Build().
FindNearestSegment()
bool UE::Geometry::FSegmentTree3::FindNearestSegment (const FVector3d & P, FSegment & NearestSegmentOut, const IMeshSpatial::FQueryOptions & Options = IMeshSpatial::FQueryOptions()) const inline
Find the nearest segment to query point P, and return it in NearestSegmentOut.
Definition at line 87 of file SegmentTree3.h.
References FindNearestSegmentInternal(), IndexConstants::InvalidID, UE::Geometry::Options, RootBoxIndex, and SegmentList.
FindNearestSegmentInternal()
void UE::Geometry::FSegmentTree3::FindNearestSegmentInternal (int BoxIndex, const FVector3d & P, double & NearestDistSqr, int & NearSegmentIdx, const IMeshSpatial::FQueryOptions & Options) const inline protected
Definition at line 432 of file SegmentTree3.h.
References UE::Geometry::FSegmentTree3::FTreeBox::BoxToIndex, FindNearestSegmentInternal(), GetBoxDistanceSqr(), IndexList, UE::Geometry::Options, SegmentList, SegmentsEnd, and TreeBoxes.
Referenced by FindNearestSegment(), and FindNearestSegmentInternal().
FindNearestVisibleSegmentHitByRay()
bool UE::Geometry::FSegmentTree3::FindNearestVisibleSegmentHitByRay (const FRay3d & Ray, TFunctionRef< bool(int32, const FVector3d &, const FVector3d &)> WithinToleranceCheck, FSegment & NearestHitSegmentOut, FRayNearestSegmentInfo & NearestInfo, const IMeshSpatial::FQueryOptions & Options = IMeshSpatial::FQueryOptions()) const inline
Find the segment that is hit by a 3D ray under a function WithinToleranceCheck, which will be called with the Ray and Segment points.
For example if this is a 3D distance check against a fixed radius, this function essentially raycasts against 3D capsules.
The function compares potential hits (ie that pass the tolerance) with a sort of "distance" metric that tries to balance distance from the ray origin (ie "close to eye") and distance from the hit segment (ie "on the line"). There is no correct way to do this, currently the code uses a metric based on the opening angle between ray and segment points.
Definition at line 130 of file SegmentTree3.h.
References FindNearestVisibleSegmentHitByRayInternal(), IndexConstants::InvalidID, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::Metric, UE::Geometry::Options, Ray, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::RayParam, RootBoxIndex, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::SegmentDist, SegmentList, and UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::SegmentParam.
FindNearestVisibleSegmentHitByRayInternal()
void UE::Geometry::FSegmentTree3::FindNearestVisibleSegmentHitByRayInternal (int BoxIndex, const FRay3d & Ray, TFunctionRef< bool(int32, const FVector3d &, const FVector3d &)> WithinToleranceCheck, int & NearSegmentIdx, FRayNearestSegmentInfo & NearestInfo, const IMeshSpatial::FQueryOptions & Options) const inline protected
Definition at line 506 of file SegmentTree3.h.
References TMathUtil< double >::Abs(), UE::Geometry::VectorUtil::Area(), UE::Geometry::FSegmentTree3::FTreeBox::BoxToIndex, FindNearestVisibleSegmentHitByRayInternal(), GetRayBoxIntersectionParam(), ID, IndexList, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::Metric, TMathUtil< double >::Min(), UE::Geometry::Options, Ray, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::RayParam, Segment, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::SegmentDist, SegmentList, UE::Geometry::FSegmentTree3::FRayNearestSegmentInfo::SegmentParam, SegmentsEnd, TMathUtil< double >::Sqrt(), UE::Geometry::TDistRay3Segment3< double >::SquaredDistance(), and TreeBoxes.
Referenced by FindNearestVisibleSegmentHitByRay(), and FindNearestVisibleSegmentHitByRayInternal().
GetBoxDistanceSqr()
double UE::Geometry::FSegmentTree3::GetBoxDistanceSqr (int BoxIndex, const FVector3d & V) const inline protected
Definition at line 396 of file SegmentTree3.h.
References TMathUtil< double >::Abs(), UE::Geometry::Box, FMath::Max, TreeBoxes, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by FindNearestSegmentInternal().
GetRayBoxIntersectionParam()
double UE::Geometry::FSegmentTree3::GetRayBoxIntersectionParam (int BoxIndex, const FRay3d & Ray, double Radius = 0) const inline protected
Definition at line 412 of file SegmentTree3.h.
References UE::Geometry::Box, BoxEps, UE::Geometry::FSegmentTree3::FTreeBox::Center, UE::Geometry::FSegmentTree3::FTreeBox::Extents, UE::Geometry::TIntrRay3AxisAlignedBox3< double >::FindIntersection(), Ray, and TreeBoxes.
Referenced by FindNearestVisibleSegmentHitByRayInternal().
MakeDefaultSplitAxisFunc()
GetSplitAxisFunc UE::Geometry::FSegmentTree3::MakeDefaultSplitAxisFunc () inline static protected
Definition at line 163 of file SegmentTree3.h.
References Depth.
SetTolerance()
void UE::Geometry::FSegmentTree3::SetTolerance (double Tolerance) inline
Sets the box intersection tolerance TODO: move into the IMeshSpatial::FQueryOptions and delete this function.
Definition at line 387 of file SegmentTree3.h.
References BoxEps.
SplitSegmentSetMidpoints()
int UE::Geometry::FSegmentTree3::SplitSegmentSetMidpoints (TArray< int > & SegmentIndices, TArray< FVector3d > & SegmentCenters, int StartIdx, int Count, int Depth, int MinSegmentCount, FBoxesSet & SegmentBoxes, FBoxesSet & Nodes, FAxisAlignedBox3d & Box) inline protected
Definition at line 285 of file SegmentTree3.h.
References UE::Geometry::Box, UE::Geometry::FSegmentTree3::FBoxesSet::Boxes, UE::Geometry::TInterval1< RealType >::Center(), checkSlow, UE::Geometry::TInterval1< RealType >::Contain(), UE::Count, Depth, UE::Geometry::TAxisAlignedBox3< double >::Empty(), UE::Geometry::TInterval1< double >::Empty(), GetSplitAxis, UE::Geometry::FSegmentTree3::FBoxesSet::IBoxCur, UE::Geometry::FSegmentTree3::FBoxesSet::IIndicesCur, UE::Geometry::FSegmentTree3::FBoxesSet::IndexList, UE::Geometry::TDynamicVector< Type, BlockSize >::InsertAt(), UE::Geometry::Left, UE::Geometry::TInterval1< RealType >::Length(), TArray< InElementType, InAllocatorType >::Num(), UE::Geometry::Right, SegmentList, SplitSegmentSetMidpoints(), Swap, UE::Math::TVector< double >::Zero(), and TMathUtilConstants< double >::ZeroTolerance.
Referenced by BuildTopDown(), and SplitSegmentSetMidpoints().
Field Documentation
BoxEps
double UE::Geometry::FSegmentTree3::BoxEps = FMathd::ZeroTolerance protected
Definition at line 394 of file SegmentTree3.h.
Referenced by GetRayBoxIntersectionParam(), and SetTolerance().
GetSplitAxis
GetSplitAxisFunc UE::Geometry::FSegmentTree3::GetSplitAxis = MakeDefaultSplitAxisFunc() protected
Definition at line 171 of file SegmentTree3.h.
Referenced by SplitSegmentSetMidpoints().
IndexList
TArray<int> UE::Geometry::FSegmentTree3::IndexList protected
Definition at line 197 of file SegmentTree3.h.
Referenced by BuildTopDown(), FindNearestSegmentInternal(), and FindNearestVisibleSegmentHitByRayInternal().
RootBoxIndex
int UE::Geometry::FSegmentTree3::RootBoxIndex = -1 protected
Definition at line 203 of file SegmentTree3.h.
Referenced by BuildTopDown(), FindNearestSegment(), and FindNearestVisibleSegmentHitByRay().
SegmentList
TArray<FSegment> UE::Geometry::FSegmentTree3::SegmentList protected
Definition at line 174 of file SegmentTree3.h.
Referenced by Build(), FindNearestSegment(), FindNearestSegmentInternal(), FindNearestVisibleSegmentHitByRay(), FindNearestVisibleSegmentHitByRayInternal(), and SplitSegmentSetMidpoints().
SegmentsEnd
int UE::Geometry::FSegmentTree3::SegmentsEnd = -1 protected
Definition at line 200 of file SegmentTree3.h.
Referenced by BuildTopDown(), FindNearestSegmentInternal(), and FindNearestVisibleSegmentHitByRayInternal().
TopDownLeafMaxSegmentCount
int UE::Geometry::FSegmentTree3::TopDownLeafMaxSegmentCount = 8 protected
Definition at line 161 of file SegmentTree3.h.
Referenced by BuildTopDown().
TreeBoxes
TArray<FTreeBox> UE::Geometry::FSegmentTree3::TreeBoxes protected
Definition at line 183 of file SegmentTree3.h.
Referenced by BuildTopDown(), FindNearestSegmentInternal(), FindNearestVisibleSegmentHitByRayInternal(), GetBoxDistanceSqr(), and GetRayBoxIntersectionParam().
The documentation for this class was generated from the following file:
SegmentTree3.h