Unreal Engine 5.6 C++ API: FRDGBuilder Class Reference
FRDGBuilder Class Reference
Use the render graph builder to build up a graph of passes and then call Execute() to process them.
#include "RenderGraphBuilder.h"
Data Structures
struct FAsyncDeleter
struct FAsyncSetupOp
struct FAsyncSetupQueue
struct FAuxiliaryPass
Tracks stack counters of auxiliary passes to avoid calling them recursively.
struct FCollectResourceContext
A temporary context used to collect resources for allocation.
struct FCollectResourceOp
struct FExtractedBuffer
struct FExtractedTexture
struct FParallelExecute
struct FUploadedBuffer
Public Member Functions
FRDGBuilder (const FRDGBuilder &)=delete
RENDERCORE_API FRDGBuilder (FRHICommandListImmediate &RHICmdList, FRDGEventName Name={}, ERDGBuilderFlags Flags=ERDGBuilderFlags::None, EShaderPlatform ShaderPlatform=GMaxRHIShaderPlatform)
RENDERCORE_API ~FRDGBuilder ()
template<typename TaskLambda>
UE::Tasks::FTask AddCommandListSetupTask (TaskLambda &&Task, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
Launches a task that is synced prior to graph execution.
template<typename TaskLambda, typename PrerequisitesCollectionType>
UE::Tasks::FTask AddCommandListSetupTask (TaskLambda &&Task, PrerequisitesCollectionType &&Prerequisites, UE::Tasks::ETaskPriority Priority=UE::Tasks::ETaskPriority::Normal, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
template<typename TaskLambda>
UE::Tasks::FTask AddCommandListSetupTask (TaskLambda &&Task, UE::Tasks::ETaskPriority Priority, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
template<typename TaskLambda, typename PrerequisitesCollectionType>
UE::Tasks::FTask AddCommandListSetupTask (TaskLambda &&Task, UE::Tasks::FPipe *Pipe, PrerequisitesCollectionType &&Prerequisites, UE::Tasks::ETaskPriority Priority=UE::Tasks::ETaskPriority::Normal, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
template<typename TaskLambda>
UE::Tasks::FTask AddCommandListSetupTask (TaskLambda &&Task, UE::Tasks::FPipe *Pipe, UE::Tasks::ETaskPriority Priority=UE::Tasks::ETaskPriority::Normal, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
void AddDispatchHint ()
A hint to the builder to flush work to the RHI thread after the last queued pass on the execution timeline.
template<typename ParameterStructType, typename LaunchLambdaType>
FRDGPassRef AddDispatchPass (FRDGEventName &&Name, const ParameterStructType *ParameterStruct, ERDGPassFlags Flags, LaunchLambdaType &&LaunchLambda)
Adds a pass that takes a FRDGDispatchPassBuilder instead of a RHI command list.
template<typename ExecuteLambdaType>
FRDGPassRef AddPass (FRDGEventName &&Name, const FShaderParametersMetadata *ParametersMetadata, const void *ParameterStruct, ERDGPassFlags Flags, ExecuteLambdaType &&ExecuteLambda)
Adds a lambda pass to the graph with a runtime-generated parameter struct.
template<typename ParameterStructType, typename ExecuteLambdaType>
FRDGPassRef AddPass (FRDGEventName &&Name, const ParameterStructType *ParameterStruct, ERDGPassFlags Flags, ExecuteLambdaType &&ExecuteLambda)
Adds a lambda pass to the graph with an accompanied pass parameter struct.
template<typename ExecuteLambdaType>
FRDGPassRef AddPass (FRDGEventName &&Name, ERDGPassFlags Flags, ExecuteLambdaType &&ExecuteLambda)
Adds a lambda pass to the graph without any parameters.
RENDERCORE_API void AddPassDependency (FRDGPass *Producer, FRDGPass *Consumer)
Adds a user-defined dependency between two passes.
void AddPostExecuteCallback (TUniqueFunction< void()> &&Callback)
Adds a callback that is called after pass execution is complete.
template<typename TaskLambda>
UE::Tasks::FTask AddSetupTask (TaskLambda &&Task, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
Launches a task that is synced prior to graph execution.
template<typename TaskLambda, typename PrerequisitesCollectionType>
UE::Tasks::FTask AddSetupTask (TaskLambda &&Task, PrerequisitesCollectionType &&Prerequisites, UE::Tasks::ETaskPriority Priority=UE::Tasks::ETaskPriority::Normal, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
template<typename TaskLambda>
UE::Tasks::FTask AddSetupTask (TaskLambda &&Task, UE::Tasks::ETaskPriority Priority, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
template<typename TaskLambda, typename PrerequisitesCollectionType>
UE::Tasks::FTask AddSetupTask (TaskLambda &&Task, UE::Tasks::FPipe *Pipe, PrerequisitesCollectionType &&Prerequisites, UE::Tasks::ETaskPriority Priority=UE::Tasks::ETaskPriority::Normal, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
template<typename TaskLambda>
UE::Tasks::FTask AddSetupTask (TaskLambda &&Task, UE::Tasks::FPipe *Pipe, UE::Tasks::ETaskPriority Priority=UE::Tasks::ETaskPriority::Normal, bool bCondition=true, ERDGSetupTaskWaitPoint WaitPoint=ERDGSetupTaskWaitPoint::Compile)
void * Alloc (uint64 SizeInBytes, uint32 AlignInBytes=16)
Allocates raw memory using an allocator tied to the lifetime of the graph.
template<typename ObjectType>
TArray< ObjectType, SceneRenderingAllocator > & AllocArray ()
Allocates a C++ array where both the array and the data are tied to the lifetime of the graph.
template<typename ObjectType, typename... TArgs>
ObjectType * AllocObject (TArgs &&... Args)
Allocates a C++ object using an allocator tied to the lifetime of the graph.
template<typename ParameterStructType>
ParameterStructType * AllocParameters ()
Allocates a parameter struct with a lifetime tied to graph execution.
template<typename BaseParameterStructType>
BaseParameterStructType * AllocParameters (const FShaderParametersMetadata *ParametersMetadata)
Allocates a data-driven parameter struct with a lifetime tied to graph execution.
template<typename BaseParameterStructType>
TStridedView< BaseParameterStructType > AllocParameters (const FShaderParametersMetadata *ParametersMetadata, uint32 NumStructs)
Allocates an array of data-driven parameter structs with a lifetime tied to graph execution.
template<typename ParameterStructType>
ParameterStructType * AllocParameters (const ParameterStructType *StructToCopy)
Allocates a parameter struct with a lifetime tied to graph execution, and copies contents from an existing parameters struct.
template<typename PODType>
PODType * AllocPOD ()
Allocates POD memory using an allocator tied to the lifetime of the graph.
template<typename PODType>
PODType * AllocPODArray (uint32 Count)
Allocates POD memory using an allocator tied to the lifetime of the graph.
template<typename PODType>
TArrayView< PODType > AllocPODArrayView (uint32 Count)
Allocates POD memory using an allocator tied to the lifetime of the graph.
RENDERCORE_API const TRefCountPtr< FRDGPooledBuffer > & ConvertToExternalBuffer (FRDGBufferRef Buffer)
RENDERCORE_API const TRefCountPtr< IPooledRenderTarget > & ConvertToExternalTexture (FRDGTextureRef Texture)
For graph-created resources, this forces immediate allocation of the underlying pooled resource, effectively promoting it to an external resource.
RENDERCORE_API FRHIUniformBuffer * ConvertToExternalUniformBuffer (FRDGUniformBufferRef UniformBuffer)
For a graph-created uniform buffer, this forces immediate allocation of the underlying resource, effectively promoting it to an external resource.
FRDGBufferRef CreateBuffer (const FRDGBufferDesc &Desc, const TCHAR *Name, ERDGBufferFlags Flags=ERDGBufferFlags::None)
Create graph tracked buffer from a descriptor.
FRDGBufferRef CreateBuffer (const FRDGBufferDesc &Desc, const TCHAR *Name, FRDGBufferNumElementsCallback &&NumElementsCallback, ERDGBufferFlags Flags=ERDGBufferFlags::None)
A variant of CreateBuffer where users supply NumElements through a callback.
FRDGBufferSRVRef CreateSRV (const FRDGBufferSRVDesc &Desc)
Create graph tracked SRV for a buffer from a descriptor.
FRDGTextureSRVRef CreateSRV (const FRDGTextureSRVDesc &Desc)
Create graph tracked SRV for a texture from a descriptor.
FORCEINLINE FRDGBufferSRVRef CreateSRV (FRDGBufferRef Buffer, EPixelFormat Format)
FRDGTextureRef CreateTexture (const FRDGTextureDesc &Desc, const TCHAR *Name, ERDGTextureFlags Flags=ERDGTextureFlags::None)
Create graph tracked texture from a descriptor.
FRDGBufferUAVRef CreateUAV (const FRDGBufferUAVDesc &Desc, ERDGUnorderedAccessViewFlags Flags=ERDGUnorderedAccessViewFlags::None)
Create graph tracked UAV for a buffer from a descriptor.
FRDGTextureUAVRef CreateUAV (const FRDGTextureUAVDesc &Desc, ERDGUnorderedAccessViewFlags Flags=ERDGUnorderedAccessViewFlags::None)
Create graph tracked UAV for a texture from a descriptor.
FORCEINLINE FRDGBufferUAVRef CreateUAV (FRDGBufferRef Buffer, EPixelFormat Format, ERDGUnorderedAccessViewFlags Flags=ERDGUnorderedAccessViewFlags::None)
FORCEINLINE FRDGTextureUAVRef CreateUAV (FRDGTextureRef Texture, ERDGUnorderedAccessViewFlags Flags=ERDGUnorderedAccessViewFlags::None, EPixelFormat Format=PF_Unknown)
template<typename ParameterStructType>
TRDGUniformBufferRef< ParameterStructType > CreateUniformBuffer (const ParameterStructType *ParameterStruct)
Creates a graph tracked uniform buffer which can be attached to passes.
RENDERCORE_API void Execute ()
Executes the queued passes, managing setting of render targets (RHI RenderPasses), resource transitions and queued texture extraction.
FRDGBuffer * FindExternalBuffer (FRDGPooledBuffer *ExternalPooledBuffer) const
FRDGBuffer * FindExternalBuffer (FRHIBuffer *Buffer) const
Finds an RDG buffer associated with the external buffer, or returns null if none is found.
FRDGTexture * FindExternalTexture (FRHITexture *Texture) const
Finds an RDG texture associated with the external texture, or returns null if none is found.
FRDGTexture * FindExternalTexture (IPooledRenderTarget *ExternalPooledTexture) const
RENDERCORE_API void FlushSetupQueue ()
Flushes all queued passes to an async task to perform setup work.
const TRefCountPtr< FRDGPooledBuffer > & GetPooledBuffer (FRDGBufferRef Buffer) const
const TRefCountPtr< IPooledRenderTarget > & GetPooledTexture (FRDGTextureRef Texture) const
Performs an immediate query for the underlying pooled resource.
bool IsAsyncComputeEnabled () const
bool IsParallelSetupEnabled () const
Whether RDG will launch async tasks when AddSetup{CommandList}Task is called.
void QueueBufferExtraction (FRDGBufferRef Buffer, TRefCountPtr< FRDGPooledBuffer > *OutPooledBufferPtr)
Queues a pooled buffer extraction to happen at the end of graph execution.
void QueueBufferExtraction (FRDGBufferRef Buffer, TRefCountPtr< FRDGPooledBuffer > *OutPooledBufferPtr, ERHIAccess AccessFinal)
void QueueBufferUpload (FRDGBufferRef Buffer, const void *InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Queues a buffer upload operation prior to execution.
void QueueBufferUpload (FRDGBufferRef Buffer, const void *InitialData, uint64 InitialDataSize, FRDGBufferInitialDataFreeCallback &&InitialDataFreeCallback)
Queues a buffer upload operation prior to execution.
void QueueBufferUpload (FRDGBufferRef Buffer, FRDGBufferInitialDataCallback &&InitialDataCallback, FRDGBufferInitialDataSizeCallback &&InitialDataSizeCallback)
A variant where InitialData and InitialDataSize are supplied through callbacks.
void QueueBufferUpload (FRDGBufferRef Buffer, FRDGBufferInitialDataCallback &&InitialDataCallback, FRDGBufferInitialDataSizeCallback &&InitialDataSizeCallback, FRDGBufferInitialDataFreeCallback &&InitialDataFreeCallback)
void QueueBufferUpload (FRDGBufferRef Buffer, FRDGBufferInitialDataFillCallback &&InitialDataFillCallback)
A variant where the buffer is mapped and the pointer / size is provided to the callback to fill the buffer pointer.
template<typename ElementType>
void QueueBufferUpload (FRDGBufferRef Buffer, TArrayView< ElementType, int32 > Container, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
template<typename ElementType>
void QueueBufferUpload (FRDGBufferRef Buffer, TArrayView< ElementType, int32 > Container, FRDGBufferInitialDataFreeCallback &&InitialDataFreeCallback)
void QueueCommitReservedBuffer (FRDGBufferRef Buffer, uint64 CommitSizeInBytes)
Queues a reserved buffer commit on first use of the buffer in the graph.
void QueueTextureExtraction (FRDGTextureRef Texture, TRefCountPtr< IPooledRenderTarget > *OutPooledTexturePtr, ERDGResourceExtractionFlags Flags=ERDGResourceExtractionFlags::None)
Queues a pooled render target extraction to happen at the end of graph execution.
void QueueTextureExtraction (FRDGTextureRef Texture, TRefCountPtr< IPooledRenderTarget > *OutPooledTexturePtr, ERHIAccess AccessFinal, ERDGResourceExtractionFlags Flags=ERDGResourceExtractionFlags::None)
RENDERCORE_API FRDGBufferRef RegisterExternalBuffer (const TRefCountPtr< FRDGPooledBuffer > &ExternalPooledBuffer, const TCHAR *NameIfNotRegistered, ERDGBufferFlags Flags=ERDGBufferFlags::None)
Register an external buffer with a custom name.
RENDERCORE_API FRDGBufferRef RegisterExternalBuffer (const TRefCountPtr< FRDGPooledBuffer > &ExternalPooledBuffer, ERDGBufferFlags Flags, ERHIAccess AccessFinal)
RENDERCORE_API FRDGBufferRef RegisterExternalBuffer (const TRefCountPtr< FRDGPooledBuffer > &ExternalPooledBuffer, ERDGBufferFlags Flags=ERDGBufferFlags::None)
Register a external buffer to be tracked by the render graph.
RENDERCORE_API FRDGTextureRef RegisterExternalTexture (const TRefCountPtr< IPooledRenderTarget > &ExternalPooledTexture, const TCHAR *NameIfNotRegistered, ERDGTextureFlags Flags=ERDGTextureFlags::None)
Register an external texture with a custom name.
RENDERCORE_API FRDGTextureRef RegisterExternalTexture (const TRefCountPtr< IPooledRenderTarget > &ExternalPooledTexture, ERDGTextureFlags Flags=ERDGTextureFlags::None)
Registers a external pooled render target texture to be tracked by the render graph.
void SetBufferAccessFinal (FRDGBufferRef Buffer, ERHIAccess Access)
(External | Extracted only) Sets the access to transition to after execution at the end of the graph.
RENDERCORE_API void SetFlushResourcesRHI ()
Tells the builder to delete unused RHI resources.
void SetPassWorkload (FRDGPass *Pass, uint32 Workload)
Sets the expected workload of the pass execution lambda.
void SetTextureAccessFinal (FRDGTextureRef Texture, ERHIAccess Access)
(External | Extracted only) Sets the access to transition to after execution at the end of the graph.
void SkipInitialAsyncComputeFence ()
Tells the RDG Builder that it is safe not to issue a fence from Async Compute -> Graphics at the start of the graph.
UE_DEPRECATED (5.5, "SetCommandListStat is deprecated. The underlying stats have been removed. Consider marking up rendering code with RDG event scopes.") inline void SetCommandListStat(TStatId StatId)
Sets the current command list stat for all subsequent passes.
UE_DEPRECATED (5.5, "This path is no longer supported.") static bool IsDumpingDraws()
UE_DEPRECATED (5.5, "This path is no longer supported.") static void DumpDraw(const FRDGEventName &DrawEventName)
UE_DEPRECATED (5.6, "RemoveUnusedBufferWarning is no longer necessary.") void RemoveUnusedBufferWarning(FRDGBufferRef Buffer)
UE_DEPRECATED (5.6, "RemoveUnusedTextureWarning is no longer necessary.") void RemoveUnusedTextureWarning(FRDGTextureRef Texture)
RENDERCORE_API void UseExternalAccessMode (FRDGViewableResource *Resource, ERHIAccess ReadOnlyAccess, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
Configures the resource for external access for all subsequent passes, or until UseInternalAccessMode is called.
void UseExternalAccessMode (TArrayView< FRDGViewableResource *const > Resources, ERHIAccess ReadOnlyAccess, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
RENDERCORE_API void UseInternalAccessMode (FRDGViewableResource *Resource)
Use this method to resume tracking of a resource after calling UseExternalAccessMode.
void UseInternalAccessMode (TArrayView< FRDGViewableResource *const > Resources)
Public Member Functions inherited from FRDGScopeState
FRDGScopeState (FRHICommandListImmediate &InRHICmdList, bool bImmediate, bool bParallelExecute)
template<typename TScopeType>
bool ShouldAllocScope (TOptional< TRDGEventScopeGuard< TScopeType > > const &, ERDGScopeFlags Flags) const
bool ShouldEmitEvents () const
Static Public Member Functions
static RENDERCORE_API const UE::Tasks::FTask & GetAsyncDeleteTask ()
Returns the last RDG chained deletion task that was launched.
static RENDERCORE_API const UE::Tasks::FTask & GetAsyncExecuteTask ()
Returns the last RDG chained execution task that was launched.
static bool IsDumpingFrame ()
static RENDERCORE_API bool IsImmediateMode ()
Whether RDG is running in immediate mode.
static RENDERCORE_API void TickPoolElements ()
Per-frame update of the render graph resource pool.
static RENDERCORE_API void WaitForAsyncDeleteTask ()
Waits for the last RDG async delete task that was launched.
static RENDERCORE_API void WaitForAsyncExecuteTask ()
Waits for the last RDG chained execution task that was launched.
Data Fields
FRDGBlackboard Blackboard
The blackboard used to hold common data tied to the graph lifetime.
Data Fields inherited from FRDGScopeState
friend FRDGScope_Budget
FRHICommandListImmediate & RHICmdList
The RHI command list used for the render graph.
Private Types
using FCollectResourceOpArray = TArray<FCollectResourceOp, FRDGArrayAllocator>
Private Member Functions
FRDGBufferReservedCommitHandle AcquireReservedCommitHandle (FRDGBuffer *Buffer)
void AddAliasingTransition (FRDGPassHandle BeginPassHandle, FRDGPassHandle EndPassHandle, FRDGViewableResource *Resource, const FRHITransientAliasingInfo &Info)
void AddBufferTransition (FRDGBufferRef Buffer, FRDGSubresourceState *&StateBefore, FRDGSubresourceState *StateAfter)
template<typename FilterSubresourceLambdaType>
void AddBufferTransition (FRDGBufferRef Buffer, FRDGSubresourceState *&StateBefore, FRDGSubresourceState *StateAfter, FilterSubresourceLambdaType &&FilterSubresourceLambda)
void AddCulledReservedCommitTransition (FRDGBufferRef Buffer)
bool AddCullingDependency (FRDGProducerStatesByPipeline &LastProducers, const FRDGProducerState &NextState, ERHIPipeline NextPipeline)
void AddCullRootBuffer (FRDGBuffer *Buffer)
void AddCullRootTexture (FRDGTexture *Texture)
void AddFirstBufferTransition (FRDGBufferRef Buffer)
void AddFirstTextureTransition (FRDGTextureRef Texture)
void AddLastBufferTransition (FRDGBufferRef Buffer)
void AddLastProducersToCullStack (const FRDGProducerStatesByPipeline &LastProducers)
void AddLastTextureTransition (FRDGTextureRef Texture)
template<typename ParameterStructType, typename ExecuteLambdaType>
FRDGPass * AddPassInternal (FRDGEventName &&Name, const FShaderParametersMetadata *ParametersMetadata, const ParameterStructType *ParameterStruct, ERDGPassFlags Flags, ExecuteLambdaType &&ExecuteLambda)
void AddTextureTransition (FRDGTextureRef Texture, FRDGTextureSubresourceState &StateBefore, FRDGTextureSubresourceState &StateAfter)
template<typename FilterSubresourceLambdaType>
void AddTextureTransition (FRDGTextureRef Texture, FRDGTextureSubresourceState &StateBefore, FRDGTextureSubresourceState &StateAfter, FilterSubresourceLambdaType &&FilterSubresourceLambda)
template<typename FunctionType>
void AddToEpilogueBarriers (FRDGPassHandle PassHandle, FunctionType Function)
Utility function to add an immediate barrier dependency in the epilogue of the provided pass.
void AddToEpilogueBarriersToEnd (FRDGPassHandle Handle, FRDGBarrierBatchBegin &BarriersToBegin)
Ends the barrier batch in the epilogue of the provided pass.
template<typename FunctionType>
void AddToPrologueBarriers (FRDGPassHandle PassHandle, FunctionType Function)
Utility function to add an immediate barrier dependency in the prologue of the provided pass.
void AddToPrologueBarriersToEnd (FRDGPassHandle Handle, FRDGBarrierBatchBegin &BarriersToBegin)
Ends the barrier batch in the prologue of the provided pass.
void AddTransition (FRDGViewableResource *Resource, FRDGSubresourceState StateBefore, FRDGSubresourceState StateAfter, FRDGTransitionInfo TransitionInfo)
TRefCountPtr< FRDGPooledBuffer > AllocatePooledBufferRHI (FRHICommandListBase &RHICmdList, FRDGBufferRef Buffer)
void AllocatePooledBuffers (FRHICommandListBase &RHICmdList, TConstArrayView< FCollectResourceOp > Ops)
TRefCountPtr< IPooledRenderTarget > AllocatePooledRenderTargetRHI (FRHICommandListBase &RHICmdList, FRDGTextureRef Texture)
Allocates and returns a pooled resource for the RDG resource.
void AllocatePooledTextures (FRHICommandListBase &RHICmdList, TConstArrayView< FCollectResourceOp > Ops)
void AllocateTransientResources (TConstArrayView< FCollectResourceOp > Ops)
Allocates resources using the provided lifetime op arrays.
FRDGSubresourceState * AllocSubresource ()
FRDGSubresourceState * AllocSubresource (const FRDGSubresourceState &Other)
void BeginFlushResourcesRHI ()
RENDERCORE_API void ClobberPassOutputs (const FRDGPass *Pass)
void CollectAllocateBuffer (FCollectResourceContext &Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGBuffer *Buffer)
void CollectAllocateTexture (FCollectResourceContext &Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGTexture *Texture)
void CollectAllocations (FCollectResourceContext &Context, FRDGPass *Pass)
Collects new resource allocations for the pass into the provided context.
void CollectDeallocateBuffer (FCollectResourceContext &Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGBuffer *Buffer, uint32 ReferenceCount)
void CollectDeallocateTexture (FCollectResourceContext &Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGTexture *Texture, uint32 ReferenceCount)
void CollectDeallocations (FCollectResourceContext &Context, FRDGPass *Pass)
Collects new resource deallocations for the pass into the provided context.
void CollectPassBarriers ()
void CollectPassBarriers (FRDGPassHandle PassHandle)
void Compile ()
void CompilePassBarriers ()
void CompilePassOps (FRDGPass *Pass)
void CreatePassBarriers ()
void CreateUniformBuffers (TConstArrayView< FRDGUniformBufferHandle > UniformBuffersToCreate)
void CreateViews (FRHICommandListBase &RHICmdList, TConstArrayView< FRDGViewHandle > ViewsToCreate)
Creates resources for the provided handles.
void EndFlushResourcesRHI ()
void ExecuteSerialPass (FRHIComputeCommandList &RHICmdListPass, FRDGPass *Pass)
void FinalizeDescs ()
Finalizes the resource descriptors by calling callbacks to gather resource sizes.
void FinalizeResources ()
RENDERCORE_API void FlushAccessModeQueue ()
void FlushCullStack ()
FRHITransientAllocationFences GetAllocateFences (FRDGViewableResource *Resource) const
FRHITransientAllocationFences GetDeallocateFences (FRDGViewableResource *Resource) const
FRDGPass * GetEpilogueBarrierPass (FRDGPassHandle Handle)
FRDGPassHandle GetEpilogueBarrierPassHandle (FRDGPassHandle Handle)
Prologue and Epilogue barrier passes are used to plan transitions around RHI render pass merging, as it is illegal to issue a barrier during a render pass.
FORCEINLINE FRDGPassHandle GetEpiloguePassHandle () const
Returns the graph epilogue pass handle.
ERHIPipeline GetPassPipeline (FRDGPassHandle PassHandle) const
FRDGPass * GetPrologueBarrierPass (FRDGPassHandle Handle)
FRDGPassHandle GetPrologueBarrierPassHandle (FRDGPassHandle Handle)
FORCEINLINE FRDGPass * GetProloguePass () const
FORCEINLINE FRDGPassHandle GetProloguePassHandle () const
Returns the graph prologue pass handle.
FRHIRenderPassInfo GetRenderPassInfo (const FRDGPass *Pass) const
uint64 GetReservedCommitSize (FRDGBufferReservedCommitHandle Handle)
void InitBufferViewRHI (FRHICommandListBase &RHICmdList, FRDGBufferSRV *SRV)
void InitBufferViewRHI (FRHICommandListBase &RHICmdList, FRDGBufferUAV *UAV)
void InitTextureViewRHI (FRHICommandListBase &RHICmdList, FRDGTextureSRV *SRV)
void InitTextureViewRHI (FRHICommandListBase &RHICmdList, FRDGTextureUAV *UAV)
void InitViewRHI (FRHICommandListBase &RHICmdList, FRDGView *View)
Initializes various view types.
bool IsTransient (FRDGBufferRef Buffer) const
bool IsTransient (FRDGTextureRef Texture) const
bool IsTransientInternal (FRDGViewableResource *Resource, bool bFastVRAM) const
void LaunchAsyncSetupQueueTask ()
void MarkResourcesAsProduced (FRDGPass *Pass)
RENDERCORE_API ERDGPassFlags OverridePassFlags (const TCHAR *PassName, ERDGPassFlags Flags) const
void ProcessAsyncSetupQueue ()
void SetDiscardPass (FRDGTexture *Texture, FRHITransientTexture *TransientTexture)
void SetExternalPooledBufferRHI (FRDGBuffer *Buffer, const TRefCountPtr< FRDGPooledBuffer > &PooledBuffer)
void SetExternalPooledRenderTargetRHI (FRDGTexture *Texture, IPooledRenderTarget *RenderTarget)
Assigns an underlying RHI resource to an RDG resource.
void SetPooledBufferRHI (FRDGBuffer *Buffer, FRDGPooledBuffer *PooledBuffer)
void SetPooledTextureRHI (FRDGTexture *Texture, FRDGPooledTexture *PooledTexture)
void SetTransientBufferRHI (FRDGBuffer *Buffer, FRHITransientBuffer *TransientBuffer)
void SetTransientTextureRHI (FRDGTexture *Texture, FRHITransientTexture *TransientTexture)
void SetupAuxiliaryPasses (FRDGPass *Pass)
void SetupDispatchPassExecute ()
RENDERCORE_API FRDGPass * SetupEmptyPass (FRDGPass *Pass)
void SetupParallelExecute (TStaticArray< void *, MAX_NUM_GPUS > const &QueryBatchData)
RENDERCORE_API FRDGPass * SetupParameterPass (FRDGPass *Pass)
void SetupPassDependencies (FRDGPass *Pass)
void SetupPassInternals (FRDGPass *Pass)
void SetupPassResources (FRDGPass *Pass)
void SubmitBufferUploads (FRHICommandListBase &InRHICmdList, UE::Tasks::FTaskEvent *AllocateUploadBuffersTask=nullptr)
RENDERCORE_API void VisualizePassOutputs (const FRDGPass *Pass)
void WaitForParallelSetupTasks (ERDGSetupTaskWaitPoint WaitPoint)
Static Private Member Functions
static void ExecutePass (FRHIComputeCommandList &RHICmdListPass, FRDGPass *Pass)
static void ExecutePassEpilogue (FRHIComputeCommandList &RHICmdListPass, FRDGPass *Pass)
static void ExecutePassPrologue (FRHIComputeCommandList &RHICmdListPass, FRDGPass *Pass)
static void PopPassScopes (FRHIComputeCommandList &RHICmdListPass, FRDGPass *Pass)
static void PopPreScopes (FRHIComputeCommandList &RHICmdListPass, FRDGPass *LastPass)
static void PushPassScopes (FRHIComputeCommandList &RHICmdListPass, FRDGPass *Pass)
static void PushPreScopes (FRHIComputeCommandList &RHICmdListPass, FRDGPass *FirstPass)
Private Attributes
TArray< FRDGViewableResource *, FRDGArrayAllocator > AccessModeQueue
Contains resources queued for either access mode change passes.
TArray< TRefCountPtr< FRDGPooledBuffer >, FRDGArrayAllocator > ActivePooledBuffers
TArray< TRefCountPtr< IPooledRenderTarget >, FRDGArrayAllocator > ActivePooledTextures
Array of all pooled references held during execution.
uint32 AsyncComputePassCount = 0
struct FRDGBuilder::FAsyncDeleter AsyncDeleter
struct FRDGBuilder::FAsyncSetupQueue AsyncSetupQueue
struct FRDGBuilder::FAuxiliaryPass AuxiliaryPasses
TMap< FRDGBarrierBatchBeginId, FRDGBarrierBatchBegin *, FRDGSetAllocator > BarrierBatchMap
Map of barrier batches begun from more than one pipe.
FRDGBarrierValidation BarrierValidation
bool bFlushResourcesRHI = false
bool bInitialAsyncComputeFence = GSupportsEfficientAsyncCompute
bool bParallelCompileEnabled = false
bool bSupportsAsyncCompute = false
bool bSupportsRenderPassMerge = false
bool bSupportsTransientBuffers = false
bool bSupportsTransientTextures = false
FRDGBufferRegistry Buffers
const FRDGEventName BuilderName
TArray< FRDGPass *, FRDGArrayAllocator > CullPassStack
TArray< FRDGDispatchPass *, FRDGArrayAllocator > DispatchPasses
Tracks dispatch passes that need to launch tasks.
FRDGPass * EpiloguePass = nullptr
TArray< FRHITrackedAccessInfo, FRDGArrayAllocator > EpilogueResourceAccesses
Tracks the final access used on resources in order to call SetTrackedAccess.
FRHICommandListScopedExtendResourceLifetime ExtendResourceLifetimeScope
TSet< FRDGViewableResource *, DefaultKeyFuncs< FRDGViewableResource * >, FRDGSetAllocator > ExternalAccessResources
Experimental::TRobinHoodHashMap< FRHIBuffer *, FRDGBuffer *, DefaultKeyFuncs< FRHIBuffer * >, FRDGArrayAllocator > ExternalBuffers
Experimental::TRobinHoodHashMap< FRHITexture *, FRDGTexture *, DefaultKeyFuncs< FRHITexture * >, FRDGArrayAllocator > ExternalTextures
Tracks external resources to their registered render graph counterparts for de-duplication.
TArray< FExtractedBuffer, FRDGArrayAllocator > ExtractedBuffers
TArray< FExtractedTexture, FRDGArrayAllocator > ExtractedTextures
friend FRDGAsyncComputeBudgetScopeGuard
friend FRDGDispatchPassBuilder
friend FRDGScopedCsvStatExclusive
friend FRDGScopedCsvStatExclusiveConditional
friend FRDGTrace
TArray< FRDGBuffer *, FRDGArrayAllocator > NumElementsCallbackBuffers
Tracks buffers that have a defered num elements callback.
struct FRDGBuilder::FParallelExecute ParallelExecute
struct {
bool bEnabled = false
int8 TaskPriorityBias = 0
TStaticArray< TArray< UE::Tasks::FTask, FRDGArrayAllocator >,(int32) ERDGSetupTaskWaitPoint::MAX > Tasks
Array of all tasks for variants of AddSetupTask.
} ParallelSetup
FRDGPassRegistry Passes
Registry of graph objects.
Experimental::TRobinHoodHashMap< FRDGPooledBuffer *, FRDGBuffer *, DefaultKeyFuncs< FRDGPooledBuffer * >, FConcurrentLinearArrayAllocator > PooledBufferOwnershipMap
Experimental::TRobinHoodHashMap< FRDGPooledTexture *, FRDGTexture *, DefaultKeyFuncs< FRDGPooledTexture * >, FConcurrentLinearArrayAllocator > PooledTextureOwnershipMap
Tracks the latest RDG resource to own an alias of a pooled resource (multiple RDG resources can reference the same pooled resource).
TArray< TUniqueFunction< void()>, FRDGArrayAllocator > PostExecuteCallbacks
FRDGPass * ProloguePass = nullptr
The epilogue and prologue passes are sentinels that are used to simplify graph logic around barriers and traversal.
FRDGSubresourceState PrologueSubresourceState
Subresource state representing the graph prologue.
uint32 RasterPassCount = 0
TArray< uint64, FRDGArrayAllocator > ReservedBufferCommitSizes
FRDGAllocatorScope RootAllocatorScope
FRDGTextureSubresourceState ScratchTextureState
Texture state used for intermediate operations.
FRDGTextureRegistry Textures
IRHITransientResourceAllocator * TransientResourceAllocator = nullptr
FRDGTransitionCreateQueue TransitionCreateQueue
Set of all active barrier batch begin instances; used to create transitions.
FRDGUniformBufferRegistry UniformBuffers
TArray< FUploadedBuffer, FRDGArrayAllocator > UploadedBuffers
FRDGUserValidation UserValidation
FRDGViewRegistry Views
FGraphEventArray WaitOutstandingTasks
Static Private Attributes
static const char *const kDefaultUnaccountedCSVStat
Additional Inherited Members
Protected Attributes inherited from FRDGScopeState
struct {
FRDGAllocator Root
FRDGAllocator Task
FRDGAllocator Transition
} Allocators
struct FRDGScopeState::FState ScopeState
Detailed Description
Use the render graph builder to build up a graph of passes and then call Execute() to process them.
Resource barriers and lifetimes are derived from RDG parameters in the pass parameter struct provided to each AddPass call. The resulting graph is compiled, culled, and executed in Execute(). The builder should be created on the stack and executed prior to destruction.
Definition at line 47 of file RenderGraphBuilder.h.
Member Typedef Documentation
FCollectResourceOpArray
using FRDGBuilder::FCollectResourceOpArray = TArray<FCollectResourceOp, FRDGArrayAllocator> private
Definition at line 662 of file RenderGraphBuilder.h.
Constructor & Destructor Documentation
FRDGBuilder() [1/2]
RENDERCORE_API FRDGBuilder::FRDGBuilder (FRHICommandListImmediate & RHICmdList, FRDGEventName Name = {}, ERDGBuilderFlags Flags = ERDGBuilderFlags::None, EShaderPlatform ShaderPlatform = GMaxRHIShaderPlatform)
References Name, and FRDGScopeState::RHICmdList.
Referenced by FRDGBuilder().
FRDGBuilder() [2/2]
FRDGBuilder::FRDGBuilder (const FRDGBuilder &) delete
References FRDGBuilder().
~FRDGBuilder()
RENDERCORE_API FRDGBuilder::~FRDGBuilder ()
Member Function Documentation
AcquireReservedCommitHandle()
FRDGBufferReservedCommitHandle FRDGBuilder::AcquireReservedCommitHandle (FRDGBuffer * Buffer) inline private
Definition at line 958 of file RenderGraphBuilder.h.
References Buffer, Handle, and ReservedBufferCommitSizes.
AddAliasingTransition()
void FRDGBuilder::AddAliasingTransition (FRDGPassHandle BeginPassHandle, FRDGPassHandle EndPassHandle, FRDGViewableResource * Resource, const FRHITransientAliasingInfo & Info) private
References Info.
AddBufferTransition() [1/2]
void FRDGBuilder::AddBufferTransition (FRDGBufferRef Buffer, FRDGSubresourceState *& StateBefore, FRDGSubresourceState * StateAfter) inline private
Definition at line 780 of file RenderGraphBuilder.h.
References AddBufferTransition(), and Buffer.
AddBufferTransition() [2/2]
template<typename FilterSubresourceLambdaType> void FRDGBuilder::AddBufferTransition (FRDGBufferRef Buffer, FRDGSubresourceState *& StateBefore, FRDGSubresourceState * StateAfter, FilterSubresourceLambdaType && FilterSubresourceLambda) private
References Buffer.
Referenced by AddBufferTransition().
AddCommandListSetupTask() [1/5]
template<typename TaskLambda> UE::Tasks::FTask FRDGBuilder::AddCommandListSetupTask (TaskLambda && Task, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
Launches a task that is synced prior to graph execution.
If parallel execution is not enabled, the lambda is run immediately.
References Compile, and FRDGScopeState::Task.
AddCommandListSetupTask() [2/5]
template<typename TaskLambda, typename PrerequisitesCollectionType> UE::Tasks::FTask FRDGBuilder::AddCommandListSetupTask (TaskLambda && Task, PrerequisitesCollectionType && Prerequisites, UE::Tasks::ETaskPriority Priority = UE::Tasks::ETaskPriority::Normal, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddCommandListSetupTask() [3/5]
template<typename TaskLambda> UE::Tasks::FTask FRDGBuilder::AddCommandListSetupTask (TaskLambda && Task, UE::Tasks::ETaskPriority Priority, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddCommandListSetupTask() [4/5]
template<typename TaskLambda, typename PrerequisitesCollectionType> UE::Tasks::FTask FRDGBuilder::AddCommandListSetupTask (TaskLambda && Task, UE::Tasks::FPipe * Pipe, PrerequisitesCollectionType && Prerequisites, UE::Tasks::ETaskPriority Priority = UE::Tasks::ETaskPriority::Normal, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddCommandListSetupTask() [5/5]
template<typename TaskLambda> UE::Tasks::FTask FRDGBuilder::AddCommandListSetupTask (TaskLambda && Task, UE::Tasks::FPipe * Pipe, UE::Tasks::ETaskPriority Priority = UE::Tasks::ETaskPriority::Normal, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddCulledReservedCommitTransition()
void FRDGBuilder::AddCulledReservedCommitTransition (FRDGBufferRef Buffer) private
References Buffer.
AddCullingDependency()
bool FRDGBuilder::AddCullingDependency (FRDGProducerStatesByPipeline & LastProducers, const FRDGProducerState & NextState, ERHIPipeline NextPipeline) private
AddCullRootBuffer()
void FRDGBuilder::AddCullRootBuffer (FRDGBuffer * Buffer) private
References Buffer.
AddCullRootTexture()
void FRDGBuilder::AddCullRootTexture (FRDGTexture * Texture) private
References Texture.
AddDispatchHint()
void FRDGBuilder::AddDispatchHint ()
A hint to the builder to flush work to the RHI thread after the last queued pass on the execution timeline.
Referenced by AddDispatchToRHIThreadPass().
AddDispatchPass()
template<typename ParameterStructType, typename LaunchLambdaType> FRDGPassRef FRDGBuilder::AddDispatchPass (FRDGEventName && Name, const ParameterStructType * ParameterStruct, ERDGPassFlags Flags, LaunchLambdaType && LaunchLambda)
Adds a pass that takes a FRDGDispatchPassBuilder instead of a RHI command list.
The lambda should create command lists and launch tasks to record commands into them. Each task should call EndRenderPass() (if raster) and FinishRecording() to complete each command list. The user is responsible for task management of dispatched command lists.
References Flags, and Name.
AddFirstBufferTransition()
void FRDGBuilder::AddFirstBufferTransition (FRDGBufferRef Buffer) private
References Buffer.
AddFirstTextureTransition()
void FRDGBuilder::AddFirstTextureTransition (FRDGTextureRef Texture) private
References Texture.
AddLastBufferTransition()
void FRDGBuilder::AddLastBufferTransition (FRDGBufferRef Buffer) private
References Buffer.
AddLastProducersToCullStack()
void FRDGBuilder::AddLastProducersToCullStack (const FRDGProducerStatesByPipeline & LastProducers) private
AddLastTextureTransition()
void FRDGBuilder::AddLastTextureTransition (FRDGTextureRef Texture) private
References Texture.
AddPass() [1/3]
template<typename ExecuteLambdaType> FRDGPassRef FRDGBuilder::AddPass (FRDGEventName && Name, const FShaderParametersMetadata * ParametersMetadata, const void * ParameterStruct, ERDGPassFlags Flags, ExecuteLambdaType && ExecuteLambda)
Adds a lambda pass to the graph with a runtime-generated parameter struct.
References Flags, and Name.
AddPass() [2/3]
template<typename ParameterStructType, typename ExecuteLambdaType> FRDGPassRef FRDGBuilder::AddPass (FRDGEventName && Name, const ParameterStructType * ParameterStruct, ERDGPassFlags Flags, ExecuteLambdaType && ExecuteLambda)
Adds a lambda pass to the graph with an accompanied pass parameter struct.
RDG resources declared in the struct (via _RDG parameter macros) are safe to access in the lambda. The pass parameter struct should be allocated by AllocParameters(), and once passed in, should not be mutated. It is safe to provide the same parameter struct to multiple passes, so long as it is kept immutable. The lambda is deferred until execution unless the immediate debug mode is enabled. All lambda captures should assume deferral of execution.
The lambda must include a single RHI command list as its parameter. The exact type of command list depends on the workload. For example, use FRHIComputeCommandList& for Compute / AsyncCompute workloads. Raster passes should use FRHICommandList&. Prefer not to use FRHICommandListImmediate& unless actually required.
Declare the type of GPU workload (i.e. Copy, Compute / AsyncCompute, Graphics) to the pass via the Flags argument. This is used to determine async compute regions, render pass setup / merging, RHI transition accesses, etc. Other flags exist for specialized purposes, like forcing a pass to never be culled (NeverCull). See ERDGPassFlags for more info.
The pass name is used by debugging / profiling tools.
References Flags, and Name.
Referenced by FPixelShaderUtils::AddFullscreenInstancedMultiViewportPass(), FPixelShaderUtils::AddFullscreenPass(), AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), and FPixelShaderUtils::AddRasterizeToRectsPass().
AddPass() [3/3]
template<typename ExecuteLambdaType> FRDGPassRef FRDGBuilder::AddPass (FRDGEventName && Name, ERDGPassFlags Flags, ExecuteLambdaType && ExecuteLambda)
Adds a lambda pass to the graph without any parameters.
This useful for deferring RHI work onto the graph timeline, or incrementally porting code to use the graph system. NeverCull and SkipRenderPass (if Raster) are implicitly added to Flags. AsyncCompute is not allowed. It is never permitted to access a created (i.e. not externally registered) RDG resource outside of passes it is registered with, as the RHI lifetime is not guaranteed.
References Flags, and Name.
AddPassDependency()
RENDERCORE_API void FRDGBuilder::AddPassDependency (FRDGPass * Producer, FRDGPass * Consumer)
Adds a user-defined dependency between two passes.
This can be used to fine-tune async compute overlap by forcing a sync point.
AddPassInternal()
template<typename ParameterStructType, typename ExecuteLambdaType> FRDGPass * FRDGBuilder::AddPassInternal (FRDGEventName && Name, const FShaderParametersMetadata * ParametersMetadata, const ParameterStructType * ParameterStruct, ERDGPassFlags Flags, ExecuteLambdaType && ExecuteLambda) private
References Flags, and Name.
AddPostExecuteCallback()
void FRDGBuilder::AddPostExecuteCallback (TUniqueFunction< void()> && Callback) inline
Adds a callback that is called after pass execution is complete.
Definition at line 194 of file RenderGraphBuilder.h.
References check, Forward(), and PostExecuteCallbacks.
AddSetupTask() [1/5]
template<typename TaskLambda> UE::Tasks::FTask FRDGBuilder::AddSetupTask (TaskLambda && Task, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
Launches a task that is synced prior to graph execution.
If parallel execution is not enabled, the lambda is run immediately.
References Compile, and FRDGScopeState::Task.
AddSetupTask() [2/5]
template<typename TaskLambda, typename PrerequisitesCollectionType> UE::Tasks::FTask FRDGBuilder::AddSetupTask (TaskLambda && Task, PrerequisitesCollectionType && Prerequisites, UE::Tasks::ETaskPriority Priority = UE::Tasks::ETaskPriority::Normal, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddSetupTask() [3/5]
template<typename TaskLambda> UE::Tasks::FTask FRDGBuilder::AddSetupTask (TaskLambda && Task, UE::Tasks::ETaskPriority Priority, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddSetupTask() [4/5]
template<typename TaskLambda, typename PrerequisitesCollectionType> UE::Tasks::FTask FRDGBuilder::AddSetupTask (TaskLambda && Task, UE::Tasks::FPipe * Pipe, PrerequisitesCollectionType && Prerequisites, UE::Tasks::ETaskPriority Priority = UE::Tasks::ETaskPriority::Normal, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddSetupTask() [5/5]
template<typename TaskLambda> UE::Tasks::FTask FRDGBuilder::AddSetupTask (TaskLambda && Task, UE::Tasks::FPipe * Pipe, UE::Tasks::ETaskPriority Priority = UE::Tasks::ETaskPriority::Normal, bool bCondition = true, ERDGSetupTaskWaitPoint WaitPoint = ERDGSetupTaskWaitPoint::Compile)
References Compile, and FRDGScopeState::Task.
AddTextureTransition() [1/2]
void FRDGBuilder::AddTextureTransition (FRDGTextureRef Texture, FRDGTextureSubresourceState & StateBefore, FRDGTextureSubresourceState & StateAfter) inline private
Definition at line 765 of file RenderGraphBuilder.h.
References AddTextureTransition(), and Texture.
AddTextureTransition() [2/2]
template<typename FilterSubresourceLambdaType> void FRDGBuilder::AddTextureTransition (FRDGTextureRef Texture, FRDGTextureSubresourceState & StateBefore, FRDGTextureSubresourceState & StateAfter, FilterSubresourceLambdaType && FilterSubresourceLambda) private
References Texture.
Referenced by AddTextureTransition().
AddToEpilogueBarriers()
template<typename FunctionType> void FRDGBuilder::AddToEpilogueBarriers (FRDGPassHandle PassHandle, FunctionType Function) inline private
Utility function to add an immediate barrier dependency in the epilogue of the provided pass.
Definition at line 852 of file RenderGraphBuilder.h.
References FRDGScopeState::Allocators, Function, GetEpilogueBarrierPass(), Pass, and TransitionCreateQueue.
AddToEpilogueBarriersToEnd()
void FRDGBuilder::AddToEpilogueBarriersToEnd (FRDGPassHandle Handle, FRDGBarrierBatchBegin & BarriersToBegin) inline private
Ends the barrier batch in the epilogue of the provided pass.
Definition at line 834 of file RenderGraphBuilder.h.
References FRDGScopeState::Allocators, GetEpilogueBarrierPass(), Handle, and Pass.
AddToPrologueBarriers()
template<typename FunctionType> void FRDGBuilder::AddToPrologueBarriers (FRDGPassHandle PassHandle, FunctionType Function) inline private
Utility function to add an immediate barrier dependency in the prologue of the provided pass.
Definition at line 842 of file RenderGraphBuilder.h.
References FRDGScopeState::Allocators, Function, GetPrologueBarrierPass(), Pass, and TransitionCreateQueue.
AddToPrologueBarriersToEnd()
void FRDGBuilder::AddToPrologueBarriersToEnd (FRDGPassHandle Handle, FRDGBarrierBatchBegin & BarriersToBegin) inline private
Ends the barrier batch in the prologue of the provided pass.
Definition at line 827 of file RenderGraphBuilder.h.
References FRDGScopeState::Allocators, GetPrologueBarrierPass(), Handle, and Pass.
AddTransition()
void FRDGBuilder::AddTransition (FRDGViewableResource * Resource, FRDGSubresourceState StateBefore, FRDGSubresourceState StateAfter, FRDGTransitionInfo TransitionInfo) private
Alloc()
void * FRDGBuilder::Alloc (uint64 SizeInBytes, uint32 AlignInBytes = 16)
Allocates raw memory using an allocator tied to the lifetime of the graph.
AllocArray()
template<typename ObjectType> TArray< ObjectType, SceneRenderingAllocator > & FRDGBuilder::AllocArray ()
Allocates a C++ array where both the array and the data are tied to the lifetime of the graph.
The array itself is safe to pass into an RDG lambda.
AllocatePooledBufferRHI()
TRefCountPtr< FRDGPooledBuffer > FRDGBuilder::AllocatePooledBufferRHI (FRHICommandListBase & RHICmdList, FRDGBufferRef Buffer) private
References Buffer, and FRDGScopeState::RHICmdList.
AllocatePooledBuffers()
void FRDGBuilder::AllocatePooledBuffers (FRHICommandListBase & RHICmdList, TConstArrayView< FCollectResourceOp > Ops) private
References FRDGScopeState::RHICmdList.
AllocatePooledRenderTargetRHI()
TRefCountPtr< IPooledRenderTarget > FRDGBuilder::AllocatePooledRenderTargetRHI (FRHICommandListBase & RHICmdList, FRDGTextureRef Texture) private
Allocates and returns a pooled resource for the RDG resource.
Does not assign it.
References FRDGScopeState::RHICmdList, and Texture.
AllocatePooledTextures()
void FRDGBuilder::AllocatePooledTextures (FRHICommandListBase & RHICmdList, TConstArrayView< FCollectResourceOp > Ops) private
References FRDGScopeState::RHICmdList.
AllocateTransientResources()
void FRDGBuilder::AllocateTransientResources (TConstArrayView< FCollectResourceOp > Ops) private
Allocates resources using the provided lifetime op arrays.
AllocObject()
template<typename ObjectType, typename... TArgs> ObjectType * FRDGBuilder::AllocObject (TArgs &&... Args)
Allocates a C++ object using an allocator tied to the lifetime of the graph.
Will destruct the object.
Referenced by CreateByteAddressBuffer(), and CreateStructuredBuffer().
AllocParameters() [1/4]
template<typename ParameterStructType> ParameterStructType * FRDGBuilder::AllocParameters ()
Allocates a parameter struct with a lifetime tied to graph execution.
AllocParameters() [2/4]
template<typename BaseParameterStructType> BaseParameterStructType * FRDGBuilder::AllocParameters (const FShaderParametersMetadata * ParametersMetadata)
Allocates a data-driven parameter struct with a lifetime tied to graph execution.
AllocParameters() [3/4]
template<typename BaseParameterStructType> TStridedView< BaseParameterStructType > FRDGBuilder::AllocParameters (const FShaderParametersMetadata * ParametersMetadata, uint32 NumStructs)
Allocates an array of data-driven parameter structs with a lifetime tied to graph execution.
AllocParameters() [4/4]
template<typename ParameterStructType> ParameterStructType * FRDGBuilder::AllocParameters (const ParameterStructType * StructToCopy)
Allocates a parameter struct with a lifetime tied to graph execution, and copies contents from an existing parameters struct.
AllocPOD()
template<typename PODType> PODType * FRDGBuilder::AllocPOD ()
Allocates POD memory using an allocator tied to the lifetime of the graph.
Does not construct / destruct.
AllocPODArray()
template<typename PODType> PODType * FRDGBuilder::AllocPODArray (uint32 Count)
Allocates POD memory using an allocator tied to the lifetime of the graph.
Does not construct / destruct.
References Count.
AllocPODArrayView()
template<typename PODType> TArrayView< PODType > FRDGBuilder::AllocPODArrayView (uint32 Count)
Allocates POD memory using an allocator tied to the lifetime of the graph.
Does not construct / destruct.
References Count.
AllocSubresource() [1/2]
FRDGSubresourceState * FRDGBuilder::AllocSubresource () private
AllocSubresource() [2/2]
FRDGSubresourceState * FRDGBuilder::AllocSubresource (const FRDGSubresourceState & Other) private
References Other.
BeginFlushResourcesRHI()
void FRDGBuilder::BeginFlushResourcesRHI () private
ClobberPassOutputs()
RENDERCORE_API void FRDGBuilder::ClobberPassOutputs (const FRDGPass * Pass) private
References FRDGTrace, and Pass.
CollectAllocateBuffer()
void FRDGBuilder::CollectAllocateBuffer (FCollectResourceContext & Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGBuffer * Buffer) private
References Buffer.
CollectAllocateTexture()
void FRDGBuilder::CollectAllocateTexture (FCollectResourceContext & Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGTexture * Texture) private
References Texture.
CollectAllocations()
void FRDGBuilder::CollectAllocations (FCollectResourceContext & Context, FRDGPass * Pass) private
Collects new resource allocations for the pass into the provided context.
References Pass.
CollectDeallocateBuffer()
void FRDGBuilder::CollectDeallocateBuffer (FCollectResourceContext & Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGBuffer * Buffer, uint32 ReferenceCount) private
References Buffer.
CollectDeallocateTexture()
void FRDGBuilder::CollectDeallocateTexture (FCollectResourceContext & Context, ERHIPipeline PassPipeline, FRDGPassHandle PassHandle, FRDGTexture * Texture, uint32 ReferenceCount) private
References Texture.
CollectDeallocations()
void FRDGBuilder::CollectDeallocations (FCollectResourceContext & Context, FRDGPass * Pass) private
Collects new resource deallocations for the pass into the provided context.
References Pass.
CollectPassBarriers() [1/2]
void FRDGBuilder::CollectPassBarriers () private
CollectPassBarriers() [2/2]
void FRDGBuilder::CollectPassBarriers (FRDGPassHandle PassHandle) private
Compile()
void FRDGBuilder::Compile () private
CompilePassBarriers()
void FRDGBuilder::CompilePassBarriers () private
CompilePassOps()
void FRDGBuilder::CompilePassOps (FRDGPass * Pass) private
References Pass.
ConvertToExternalBuffer()
RENDERCORE_API const TRefCountPtr< FRDGPooledBuffer > & FRDGBuilder::ConvertToExternalBuffer (FRDGBufferRef Buffer)
References Buffer.
Referenced by ConvertToExternalAccessBuffer(), and ConvertToExternalAccessBuffer().
ConvertToExternalTexture()
RENDERCORE_API const TRefCountPtr< IPooledRenderTarget > & FRDGBuilder::ConvertToExternalTexture (FRDGTextureRef Texture)
For graph-created resources, this forces immediate allocation of the underlying pooled resource, effectively promoting it to an external resource.
This will increase memory pressure, but allows for querying the pooled resource with GetPooled{Texture, Buffer}. This is primarily used as an aid for porting code incrementally to RDG.
References Texture.
Referenced by ConvertToExternalAccessTexture(), and ConvertToExternalAccessTexture().
ConvertToExternalUniformBuffer()
RENDERCORE_API FRHIUniformBuffer * FRDGBuilder::ConvertToExternalUniformBuffer (FRDGUniformBufferRef UniformBuffer)
For a graph-created uniform buffer, this forces immediate allocation of the underlying resource, effectively promoting it to an external resource.
This will increase memory pressure, but allows access to the RHI resource. Graph resources that are referenced in the buffer will be converted to external. This is primarily used as an aid for porting code incrementally to RDG.
References UniformBuffer.
CreateBuffer() [1/2]
FRDGBufferRef FRDGBuilder::CreateBuffer (const FRDGBufferDesc & Desc, const TCHAR * Name, ERDGBufferFlags Flags = ERDGBufferFlags::None)
Create graph tracked buffer from a descriptor.
The CPU memory is guaranteed to be valid through execution of the graph, at which point it is released. The underlying RHI buffer lifetime is only guaranteed for passes which declare the buffer in the pass parameter struct. The name is the name used for GPU debugging tools.
References Flags, Name, and None.
Referenced by CreateByteAddressUploadBuffer(), CreateByteAddressUploadBuffer(), and CreateStructuredUploadBuffer().
CreateBuffer() [2/2]
FRDGBufferRef FRDGBuilder::CreateBuffer (const FRDGBufferDesc & Desc, const TCHAR * Name, FRDGBufferNumElementsCallback && NumElementsCallback, ERDGBufferFlags Flags = ERDGBufferFlags::None)
A variant of CreateBuffer where users supply NumElements through a callback.
This allows creating buffers with sizes unknown at creation time. The callback is called before executing the most recent RDG pass that references the buffer so data must be ready before that.
References Flags, Name, and None.
CreatePassBarriers()
void FRDGBuilder::CreatePassBarriers () private
CreateSRV() [1/3]
FRDGBufferSRVRef FRDGBuilder::CreateSRV (const FRDGBufferSRVDesc & Desc)
Create graph tracked SRV for a buffer from a descriptor.
CreateSRV() [2/3]
FRDGTextureSRVRef FRDGBuilder::CreateSRV (const FRDGTextureSRVDesc & Desc)
Create graph tracked SRV for a texture from a descriptor.
Referenced by CreateSRV().
CreateSRV() [3/3]
FORCEINLINE FRDGBufferSRVRef FRDGBuilder::CreateSRV (FRDGBufferRef Buffer, EPixelFormat Format) inline
Definition at line 121 of file RenderGraphBuilder.h.
References Buffer, CreateSRV(), FORCEINLINE, and Format.
CreateTexture()
FRDGTextureRef FRDGBuilder::CreateTexture (const FRDGTextureDesc & Desc, const TCHAR * Name, ERDGTextureFlags Flags = ERDGTextureFlags::None)
Create graph tracked texture from a descriptor.
The CPU memory is guaranteed to be valid through execution of the graph, at which point it is released. The underlying RHI texture lifetime is only guaranteed for passes which declare the texture in the pass parameter struct. The name is the name used for GPU debugging tools and the the VisualizeTexture/Vis command.
References Flags, Name, and None.
CreateUAV() [1/4]
FRDGBufferUAVRef FRDGBuilder::CreateUAV (const FRDGBufferUAVDesc & Desc, ERDGUnorderedAccessViewFlags Flags = ERDGUnorderedAccessViewFlags::None)
Create graph tracked UAV for a buffer from a descriptor.
References Flags, and None.
CreateUAV() [2/4]
FRDGTextureUAVRef FRDGBuilder::CreateUAV (const FRDGTextureUAVDesc & Desc, ERDGUnorderedAccessViewFlags Flags = ERDGUnorderedAccessViewFlags::None)
Create graph tracked UAV for a texture from a descriptor.
References Flags, and None.
Referenced by CreateUAV(), and CreateUAV().
CreateUAV() [3/4]
FORCEINLINE FRDGBufferUAVRef FRDGBuilder::CreateUAV (FRDGBufferRef Buffer, EPixelFormat Format, ERDGUnorderedAccessViewFlags Flags = ERDGUnorderedAccessViewFlags::None) inline
Definition at line 137 of file RenderGraphBuilder.h.
References Buffer, CreateUAV(), Flags, FORCEINLINE, Format, and None.
CreateUAV() [4/4]
FORCEINLINE FRDGTextureUAVRef FRDGBuilder::CreateUAV (FRDGTextureRef Texture, ERDGUnorderedAccessViewFlags Flags = ERDGUnorderedAccessViewFlags::None, EPixelFormat Format = PF_Unknown) inline
Definition at line 129 of file RenderGraphBuilder.h.
References CreateUAV(), Flags, FORCEINLINE, Format, None, PF_Unknown, and Texture.
CreateUniformBuffer()
template<typename ParameterStructType> TRDGUniformBufferRef< ParameterStructType > FRDGBuilder::CreateUniformBuffer (const ParameterStructType * ParameterStruct)
Creates a graph tracked uniform buffer which can be attached to passes.
These uniform buffers require some care because they will bulk transition all resources. The graph will only transition resources which are not also bound for write access by the pass.
CreateUniformBuffers()
void FRDGBuilder::CreateUniformBuffers (TConstArrayView< FRDGUniformBufferHandle > UniformBuffersToCreate) private
CreateViews()
void FRDGBuilder::CreateViews (FRHICommandListBase & RHICmdList, TConstArrayView< FRDGViewHandle > ViewsToCreate) private
Creates resources for the provided handles.
References FRDGScopeState::RHICmdList.
EndFlushResourcesRHI()
void FRDGBuilder::EndFlushResourcesRHI () private
Execute()
RENDERCORE_API void FRDGBuilder::Execute ()
Executes the queued passes, managing setting of render targets (RHI RenderPasses), resource transitions and queued texture extraction.
ExecutePass()
void FRDGBuilder::ExecutePass (FRHIComputeCommandList & RHICmdListPass, FRDGPass * Pass) static private
References Pass.
ExecutePassEpilogue()
void FRDGBuilder::ExecutePassEpilogue (FRHIComputeCommandList & RHICmdListPass, FRDGPass * Pass) static private
References Pass.
ExecutePassPrologue()
void FRDGBuilder::ExecutePassPrologue (FRHIComputeCommandList & RHICmdListPass, FRDGPass * Pass) static private
References Pass.
ExecuteSerialPass()
void FRDGBuilder::ExecuteSerialPass (FRHIComputeCommandList & RHICmdListPass, FRDGPass * Pass) private
References Pass.
FinalizeDescs()
void FRDGBuilder::FinalizeDescs () private
Finalizes the resource descriptors by calling callbacks to gather resource sizes.
FinalizeResources()
void FRDGBuilder::FinalizeResources () private
FindExternalBuffer() [1/2]
FRDGBuffer * FRDGBuilder::FindExternalBuffer (FRDGPooledBuffer * ExternalPooledBuffer) const
FindExternalBuffer() [2/2]
FRDGBuffer * FRDGBuilder::FindExternalBuffer (FRHIBuffer * Buffer) const
Finds an RDG buffer associated with the external buffer, or returns null if none is found.
References Buffer.
Referenced by IsRegistered().
FindExternalTexture() [1/2]
FRDGTexture * FRDGBuilder::FindExternalTexture (FRHITexture * Texture) const
Finds an RDG texture associated with the external texture, or returns null if none is found.
References Texture.
Referenced by IsRegistered(), and RegisterExternalTexture().
FindExternalTexture() [2/2]
FRDGTexture * FRDGBuilder::FindExternalTexture (IPooledRenderTarget * ExternalPooledTexture) const
FlushAccessModeQueue()
RENDERCORE_API void FRDGBuilder::FlushAccessModeQueue () private
FlushCullStack()
void FRDGBuilder::FlushCullStack () private
FlushSetupQueue()
RENDERCORE_API void FRDGBuilder::FlushSetupQueue ()
Flushes all queued passes to an async task to perform setup work.
GetAllocateFences()
FRHITransientAllocationFences FRDGBuilder::GetAllocateFences (FRDGViewableResource * Resource) const private
GetAsyncDeleteTask()
RENDERCORE_API const UE::Tasks::FTask & FRDGBuilder::GetAsyncDeleteTask () static
Returns the last RDG chained deletion task that was launched.
GetAsyncExecuteTask()
RENDERCORE_API const UE::Tasks::FTask & FRDGBuilder::GetAsyncExecuteTask () static
Returns the last RDG chained execution task that was launched.
GetDeallocateFences()
FRHITransientAllocationFences FRDGBuilder::GetDeallocateFences (FRDGViewableResource * Resource) const private
GetEpilogueBarrierPass()
FRDGPass * FRDGBuilder::GetEpilogueBarrierPass (FRDGPassHandle Handle) inline private
Definition at line 816 of file RenderGraphBuilder.h.
References GetEpilogueBarrierPassHandle(), Handle, and Passes.
Referenced by AddToEpilogueBarriers(), and AddToEpilogueBarriersToEnd().
GetEpilogueBarrierPassHandle()
FRDGPassHandle FRDGBuilder::GetEpilogueBarrierPassHandle (FRDGPassHandle Handle) inline private
Prologue and Epilogue barrier passes are used to plan transitions around RHI render pass merging, as it is illegal to issue a barrier during a render pass.
If passes [A, B, C] are merged together, 'A' becomes 'B's prologue pass and 'C' becomes 'A's epilogue pass. This way, any transitions that need to happen before the merged pass (i.e. in the prologue) are done in A. Any transitions after the render pass merge are done in C.
Definition at line 806 of file RenderGraphBuilder.h.
References Handle, and Passes.
Referenced by GetEpilogueBarrierPass().
GetEpiloguePassHandle()
FORCEINLINE FRDGPassHandle FRDGBuilder::GetEpiloguePassHandle () const inline private
Returns the graph epilogue pass handle.
Definition at line 504 of file RenderGraphBuilder.h.
References checkf, EpiloguePass, FORCEINLINE, Passes, and TEXT.
GetPassPipeline()
ERHIPipeline FRDGBuilder::GetPassPipeline (FRDGPassHandle PassHandle) const inline private
Definition at line 866 of file RenderGraphBuilder.h.
References Passes.
GetPooledBuffer()
const TRefCountPtr< FRDGPooledBuffer > & FRDGBuilder::GetPooledBuffer (FRDGBufferRef Buffer) const
References Buffer.
GetPooledTexture()
const TRefCountPtr< IPooledRenderTarget > & FRDGBuilder::GetPooledTexture (FRDGTextureRef Texture) const
Performs an immediate query for the underlying pooled resource.
This is only allowed for external or extracted resources.
References Texture.
GetPrologueBarrierPass()
FRDGPass * FRDGBuilder::GetPrologueBarrierPass (FRDGPassHandle Handle) inline private
Definition at line 821 of file RenderGraphBuilder.h.
References GetPrologueBarrierPassHandle(), Handle, and Passes.
Referenced by AddToPrologueBarriers(), and AddToPrologueBarriersToEnd().
GetPrologueBarrierPassHandle()
FRDGPassHandle FRDGBuilder::GetPrologueBarrierPassHandle (FRDGPassHandle Handle) inline private
Definition at line 811 of file RenderGraphBuilder.h.
References Handle, and Passes.
Referenced by GetPrologueBarrierPass().
GetProloguePass()
FORCEINLINE FRDGPass * FRDGBuilder::GetProloguePass () const inline private
Definition at line 492 of file RenderGraphBuilder.h.
References FORCEINLINE, and ProloguePass.
GetProloguePassHandle()
FORCEINLINE FRDGPassHandle FRDGBuilder::GetProloguePassHandle () const inline private
Returns the graph prologue pass handle.
Definition at line 498 of file RenderGraphBuilder.h.
References FORCEINLINE.
GetRenderPassInfo()
FRHIRenderPassInfo FRDGBuilder::GetRenderPassInfo (const FRDGPass * Pass) const private
References Pass.
GetReservedCommitSize()
uint64 FRDGBuilder::GetReservedCommitSize (FRDGBufferReservedCommitHandle Handle) inline private
Definition at line 972 of file RenderGraphBuilder.h.
References Handle, and ReservedBufferCommitSizes.
InitBufferViewRHI() [1/2]
void FRDGBuilder::InitBufferViewRHI (FRHICommandListBase & RHICmdList, FRDGBufferSRV * SRV) private
References FRDGScopeState::RHICmdList, and SRV.
InitBufferViewRHI() [2/2]
void FRDGBuilder::InitBufferViewRHI (FRHICommandListBase & RHICmdList, FRDGBufferUAV * UAV) private
References FRDGScopeState::RHICmdList, and UAV.
InitTextureViewRHI() [1/2]
void FRDGBuilder::InitTextureViewRHI (FRHICommandListBase & RHICmdList, FRDGTextureSRV * SRV) private
References FRDGScopeState::RHICmdList, and SRV.
InitTextureViewRHI() [2/2]
void FRDGBuilder::InitTextureViewRHI (FRHICommandListBase & RHICmdList, FRDGTextureUAV * UAV) private
References FRDGScopeState::RHICmdList, and UAV.
InitViewRHI()
void FRDGBuilder::InitViewRHI (FRHICommandListBase & RHICmdList, FRDGView * View) private
Initializes various view types.
Assumes that the underlying RHI viewable resource type is assigned.
References FRDGScopeState::RHICmdList.
IsAsyncComputeEnabled()
bool FRDGBuilder::IsAsyncComputeEnabled () const inline
Definition at line 293 of file RenderGraphBuilder.h.
References bSupportsAsyncCompute.
IsDumpingFrame()
bool FRDGBuilder::IsDumpingFrame () inline static
Definition at line 440 of file RenderGraphBuilder.h.
IsImmediateMode()
RENDERCORE_API bool FRDGBuilder::IsImmediateMode () static
Whether RDG is running in immediate mode.
IsParallelSetupEnabled()
bool FRDGBuilder::IsParallelSetupEnabled () const inline
Whether RDG will launch async tasks when AddSetup{CommandList}Task is called.
Definition at line 288 of file RenderGraphBuilder.h.
References ParallelSetup.
IsTransient() [1/2]
bool FRDGBuilder::IsTransient (FRDGBufferRef Buffer) const private
References Buffer.
IsTransient() [2/2]
bool FRDGBuilder::IsTransient (FRDGTextureRef Texture) const private
References Texture.
IsTransientInternal()
bool FRDGBuilder::IsTransientInternal (FRDGViewableResource * Resource, bool bFastVRAM) const private
LaunchAsyncSetupQueueTask()
void FRDGBuilder::LaunchAsyncSetupQueueTask () private
MarkResourcesAsProduced()
void FRDGBuilder::MarkResourcesAsProduced (FRDGPass * Pass) private
References Pass.
OverridePassFlags()
RENDERCORE_API ERDGPassFlags FRDGBuilder::OverridePassFlags (const TCHAR * PassName, ERDGPassFlags Flags) const private
References Flags.
PopPassScopes()
void FRDGBuilder::PopPassScopes (FRHIComputeCommandList & RHICmdListPass, FRDGPass * Pass) static private
References Pass.
PopPreScopes()
void FRDGBuilder::PopPreScopes (FRHIComputeCommandList & RHICmdListPass, FRDGPass * LastPass) static private
ProcessAsyncSetupQueue()
void FRDGBuilder::ProcessAsyncSetupQueue () private
PushPassScopes()
void FRDGBuilder::PushPassScopes (FRHIComputeCommandList & RHICmdListPass, FRDGPass * Pass) static private
References Pass.
PushPreScopes()
void FRDGBuilder::PushPreScopes (FRHIComputeCommandList & RHICmdListPass, FRDGPass * FirstPass) static private
QueueBufferExtraction() [1/2]
void FRDGBuilder::QueueBufferExtraction (FRDGBufferRef Buffer, TRefCountPtr< FRDGPooledBuffer > * OutPooledBufferPtr)
Queues a pooled buffer extraction to happen at the end of graph execution.
For graph-created buffers, this extends the lifetime of the GPU resource until execution, at which point the pointer is filled. If specified, the buffer is transitioned to the AccessFinal state, or kDefaultAccessFinal otherwise.
References Buffer.
QueueBufferExtraction() [2/2]
void FRDGBuilder::QueueBufferExtraction (FRDGBufferRef Buffer, TRefCountPtr< FRDGPooledBuffer > * OutPooledBufferPtr, ERHIAccess AccessFinal)
References Buffer.
QueueBufferUpload() [1/7]
void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, const void * InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Queues a buffer upload operation prior to execution.
The resource lifetime is extended and the data is uploaded prior to executing passes.
References Buffer, and None.
Referenced by CreateByteAddressUploadBuffer(), CreateByteAddressUploadBuffer(), CreateStructuredUploadBuffer(), QueueBufferUpload(), and QueueBufferUpload().
QueueBufferUpload() [2/7]
void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, const void * InitialData, uint64 InitialDataSize, FRDGBufferInitialDataFreeCallback && InitialDataFreeCallback)
Queues a buffer upload operation prior to execution.
The resource lifetime is extended and the data is uploaded prior to executing passes.
References Buffer.
QueueBufferUpload() [3/7]
void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, FRDGBufferInitialDataCallback && InitialDataCallback, FRDGBufferInitialDataSizeCallback && InitialDataSizeCallback)
A variant where InitialData and InitialDataSize are supplied through callbacks.
This allows queuing an upload with information unknown at creation time. The callbacks are called before RDG pass execution so data must be ready before that.
References Buffer.
QueueBufferUpload() [4/7]
void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, FRDGBufferInitialDataCallback && InitialDataCallback, FRDGBufferInitialDataSizeCallback && InitialDataSizeCallback, FRDGBufferInitialDataFreeCallback && InitialDataFreeCallback)
References Buffer.
QueueBufferUpload() [5/7]
void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, FRDGBufferInitialDataFillCallback && InitialDataFillCallback)
A variant where the buffer is mapped and the pointer / size is provided to the callback to fill the buffer pointer.
References Buffer.
QueueBufferUpload() [6/7]
template<typename ElementType> void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, TArrayView< ElementType, int32 > Container, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None) inline
Definition at line 313 of file RenderGraphBuilder.h.
References Buffer, Container, None, and QueueBufferUpload().
QueueBufferUpload() [7/7]
template<typename ElementType> void FRDGBuilder::QueueBufferUpload (FRDGBufferRef Buffer, TArrayView< ElementType, int32 > Container, FRDGBufferInitialDataFreeCallback && InitialDataFreeCallback) inline
Definition at line 322 of file RenderGraphBuilder.h.
References Buffer, Container, and QueueBufferUpload().
QueueCommitReservedBuffer()
void FRDGBuilder::QueueCommitReservedBuffer (FRDGBufferRef Buffer, uint64 CommitSizeInBytes)
Queues a reserved buffer commit on first use of the buffer in the graph.
The commit is applied at the start of the graph and synced at the pass when the resource is first used, or at the end of the graph if the resource is unused and external. A resource may only be assigned a commit size once.
References Buffer.
QueueTextureExtraction() [1/2]
void FRDGBuilder::QueueTextureExtraction (FRDGTextureRef Texture, TRefCountPtr< IPooledRenderTarget > * OutPooledTexturePtr, ERDGResourceExtractionFlags Flags = ERDGResourceExtractionFlags::None)
Queues a pooled render target extraction to happen at the end of graph execution.
For graph-created textures, this extends the lifetime of the GPU resource until execution, at which point the pointer is filled. If specified, the texture is transitioned to the AccessFinal state, or kDefaultAccessFinal otherwise.
References Flags, None, and Texture.
QueueTextureExtraction() [2/2]
void FRDGBuilder::QueueTextureExtraction (FRDGTextureRef Texture, TRefCountPtr< IPooledRenderTarget > * OutPooledTexturePtr, ERHIAccess AccessFinal, ERDGResourceExtractionFlags Flags = ERDGResourceExtractionFlags::None)
References Flags, None, and Texture.
RegisterExternalBuffer() [1/3]
RENDERCORE_API FRDGBufferRef FRDGBuilder::RegisterExternalBuffer (const TRefCountPtr< FRDGPooledBuffer > & ExternalPooledBuffer, const TCHAR * NameIfNotRegistered, ERDGBufferFlags Flags = ERDGBufferFlags::None)
Register an external buffer with a custom name.
The name is only used if the buffer has not already been registered.
References Flags, and None.
RegisterExternalBuffer() [2/3]
RENDERCORE_API FRDGBufferRef FRDGBuilder::RegisterExternalBuffer (const TRefCountPtr< FRDGPooledBuffer > & ExternalPooledBuffer, ERDGBufferFlags Flags, ERHIAccess AccessFinal)
References Flags.
RegisterExternalBuffer() [3/3]
RENDERCORE_API FRDGBufferRef FRDGBuilder::RegisterExternalBuffer (const TRefCountPtr< FRDGPooledBuffer > & ExternalPooledBuffer, ERDGBufferFlags Flags = ERDGBufferFlags::None)
Register a external buffer to be tracked by the render graph.
References Flags, and None.
Referenced by TryRegisterExternalBuffer().
RegisterExternalTexture() [1/2]
RENDERCORE_API FRDGTextureRef FRDGBuilder::RegisterExternalTexture (const TRefCountPtr< IPooledRenderTarget > & ExternalPooledTexture, const TCHAR * NameIfNotRegistered, ERDGTextureFlags Flags = ERDGTextureFlags::None)
Register an external texture with a custom name.
The name is only used if the texture has not already been registered.
References Flags, and None.
RegisterExternalTexture() [2/2]
RENDERCORE_API FRDGTextureRef FRDGBuilder::RegisterExternalTexture (const TRefCountPtr< IPooledRenderTarget > & ExternalPooledTexture, ERDGTextureFlags Flags = ERDGTextureFlags::None)
Registers a external pooled render target texture to be tracked by the render graph.
The name of the registered RDG texture is pulled from the pooled render target.
References Flags, and None.
Referenced by RegisterExternalTexture(), and TryRegisterExternalTexture().
SetBufferAccessFinal()
void FRDGBuilder::SetBufferAccessFinal (FRDGBufferRef Buffer, ERHIAccess Access)
(External | Extracted only) Sets the access to transition to after execution at the end of the graph.
Overwrites any previously set final access.
References Access, and Buffer.
SetDiscardPass()
void FRDGBuilder::SetDiscardPass (FRDGTexture * Texture, FRHITransientTexture * TransientTexture) private
References Texture.
SetExternalPooledBufferRHI()
void FRDGBuilder::SetExternalPooledBufferRHI (FRDGBuffer * Buffer, const TRefCountPtr< FRDGPooledBuffer > & PooledBuffer) private
References Buffer.
SetExternalPooledRenderTargetRHI()
void FRDGBuilder::SetExternalPooledRenderTargetRHI (FRDGTexture * Texture, IPooledRenderTarget * RenderTarget) private
Assigns an underlying RHI resource to an RDG resource.
References RenderTarget, and Texture.
SetFlushResourcesRHI()
RENDERCORE_API void FRDGBuilder::SetFlushResourcesRHI ()
Tells the builder to delete unused RHI resources.
The behavior of this method depends on whether RDG immediate mode is enabled: Deferred: RHI resource flushes are performed prior to execution. Immediate: RHI resource flushes are performed immediately.
SetPassWorkload()
void FRDGBuilder::SetPassWorkload (FRDGPass * Pass, uint32 Workload)
Sets the expected workload of the pass execution lambda.
The default workload is 1 and is more or less the 'average cost' of a pass. Recommended usage is to set a workload equal to the number of complex draw / dispatch calls (each with its own parameters, etc), and only as a performance tweak if a particular pass is very expensive relative to other passes.
References Pass.
SetPooledBufferRHI()
void FRDGBuilder::SetPooledBufferRHI (FRDGBuffer * Buffer, FRDGPooledBuffer * PooledBuffer) private
References Buffer.
SetPooledTextureRHI()
void FRDGBuilder::SetPooledTextureRHI (FRDGTexture * Texture, FRDGPooledTexture * PooledTexture) private
References Texture.
SetTextureAccessFinal()
void FRDGBuilder::SetTextureAccessFinal (FRDGTextureRef Texture, ERHIAccess Access)
(External | Extracted only) Sets the access to transition to after execution at the end of the graph.
Overwrites any previously set final access.
References Access, and Texture.
SetTransientBufferRHI()
void FRDGBuilder::SetTransientBufferRHI (FRDGBuffer * Buffer, FRHITransientBuffer * TransientBuffer) private
References Buffer.
SetTransientTextureRHI()
void FRDGBuilder::SetTransientTextureRHI (FRDGTexture * Texture, FRHITransientTexture * TransientTexture) private
References Texture.
SetupAuxiliaryPasses()
void FRDGBuilder::SetupAuxiliaryPasses (FRDGPass * Pass) private
References Pass.
SetupDispatchPassExecute()
void FRDGBuilder::SetupDispatchPassExecute () private
SetupEmptyPass()
RENDERCORE_API FRDGPass * FRDGBuilder::SetupEmptyPass (FRDGPass * Pass) private
References Pass.
SetupParallelExecute()
void FRDGBuilder::SetupParallelExecute (TStaticArray< void *, MAX_NUM_GPUS > const & QueryBatchData) private
SetupParameterPass()
RENDERCORE_API FRDGPass * FRDGBuilder::SetupParameterPass (FRDGPass * Pass) private
References Pass.
SetupPassDependencies()
void FRDGBuilder::SetupPassDependencies (FRDGPass * Pass) private
References Pass.
SetupPassInternals()
void FRDGBuilder::SetupPassInternals (FRDGPass * Pass) private
References Pass.
SetupPassResources()
void FRDGBuilder::SetupPassResources (FRDGPass * Pass) private
References Pass.
SkipInitialAsyncComputeFence()
void FRDGBuilder::SkipInitialAsyncComputeFence ()
Tells the RDG Builder that it is safe not to issue a fence from Async Compute -> Graphics at the start of the graph.
By default RDG will issue the fence to keep new work from overlapping with work from prior builders.
SubmitBufferUploads()
void FRDGBuilder::SubmitBufferUploads (FRHICommandListBase & InRHICmdList, UE::Tasks::FTaskEvent * AllocateUploadBuffersTask = nullptr) private
TickPoolElements()
RENDERCORE_API void FRDGBuilder::TickPoolElements () static
Per-frame update of the render graph resource pool.
UE_DEPRECATED() [1/5]
FRDGBuilder::UE_DEPRECATED (5. 5, "SetCommandListStat is deprecated. The underlying stats have been removed. Consider marking up rendering code with RDG event scopes.") inline
Sets the current command list stat for all subsequent passes.
Definition at line 249 of file RenderGraphBuilder.h.
UE_DEPRECATED() [2/5]
FRDGBuilder::UE_DEPRECATED (5. 5, "This path is no longer supported.") inline
Definition at line 454 of file RenderGraphBuilder.h.
UE_DEPRECATED() [3/5]
FRDGBuilder::UE_DEPRECATED (5. 5, "This path is no longer supported.") const & inline
Definition at line 451 of file RenderGraphBuilder.h.
UE_DEPRECATED() [4/5]
FRDGBuilder::UE_DEPRECATED (5. 6, "RemoveUnusedBufferWarning is no longer necessary.") inline
Definition at line 460 of file RenderGraphBuilder.h.
References Buffer.
UE_DEPRECATED() [5/5]
FRDGBuilder::UE_DEPRECATED (5. 6, "RemoveUnusedTextureWarning is no longer necessary.") inline
Definition at line 457 of file RenderGraphBuilder.h.
References Texture.
UseExternalAccessMode() [1/2]
RENDERCORE_API void FRDGBuilder::UseExternalAccessMode (FRDGViewableResource * Resource, ERHIAccess ReadOnlyAccess, ERHIPipeline Pipelines = ERHIPipeline::Graphics)
Configures the resource for external access for all subsequent passes, or until UseInternalAccessMode is called.
Only read-only access states are allowed. When in external access mode, it is safe to access the underlying RHI resource directly in later RDG passes. This method is only allowed for registered or externally converted resources. The method effectively guarantees that RDG will transition the resource into the desired state for all subsequent passes so long as the resource remains externally accessible.
Referenced by ConvertToExternalAccessBuffer(), ConvertToExternalAccessTexture(), and UseExternalAccessMode().
UseExternalAccessMode() [2/2]
void FRDGBuilder::UseExternalAccessMode (TArrayView< FRDGViewableResource *const > Resources, ERHIAccess ReadOnlyAccess, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 387 of file RenderGraphBuilder.h.
References UseExternalAccessMode().
UseInternalAccessMode() [1/2]
RENDERCORE_API void FRDGBuilder::UseInternalAccessMode (FRDGViewableResource * Resource)
Use this method to resume tracking of a resource after calling UseExternalAccessMode.
It is safe to call this method even if external access mode was not enabled (it will simply no-op). It is not valid to access the underlying RHI resource in any pass added after calling this method.
Referenced by UseInternalAccessMode().
UseInternalAccessMode() [2/2]
void FRDGBuilder::UseInternalAccessMode (TArrayView< FRDGViewableResource *const > Resources) inline
Definition at line 401 of file RenderGraphBuilder.h.
References UseInternalAccessMode().
VisualizePassOutputs()
RENDERCORE_API void FRDGBuilder::VisualizePassOutputs (const FRDGPass * Pass) private
References Pass.
WaitForAsyncDeleteTask()
RENDERCORE_API void FRDGBuilder::WaitForAsyncDeleteTask () static
Waits for the last RDG async delete task that was launched.
If the event is valid it is consumed. Thus, it is not thread safe to wait from multiple threads at once.
WaitForAsyncExecuteTask()
RENDERCORE_API void FRDGBuilder::WaitForAsyncExecuteTask () static
Waits for the last RDG chained execution task that was launched.
WaitForParallelSetupTasks()
void FRDGBuilder::WaitForParallelSetupTasks (ERDGSetupTaskWaitPoint WaitPoint) private
Field Documentation
AccessModeQueue
TArray<FRDGViewableResource*, FRDGArrayAllocator> FRDGBuilder::AccessModeQueue private
Contains resources queued for either access mode change passes.
Definition at line 1098 of file RenderGraphBuilder.h.
ActivePooledBuffers
TArray<TRefCountPtr<FRDGPooledBuffer>, FRDGArrayAllocator> FRDGBuilder::ActivePooledBuffers private
Definition at line 733 of file RenderGraphBuilder.h.
ActivePooledTextures
TArray<TRefCountPtr<IPooledRenderTarget>, FRDGArrayAllocator> FRDGBuilder::ActivePooledTextures private
Array of all pooled references held during execution.
Definition at line 732 of file RenderGraphBuilder.h.
AsyncComputePassCount
uint32 FRDGBuilder::AsyncComputePassCount = 0 private
Definition at line 484 of file RenderGraphBuilder.h.
AsyncDeleter
struct FRDGBuilder::FAsyncDeleter FRDGBuilder::AsyncDeleter private
AsyncSetupQueue
struct FRDGBuilder::FAsyncSetupQueue FRDGBuilder::AsyncSetupQueue private
AuxiliaryPasses
struct FRDGBuilder::FAuxiliaryPass FRDGBuilder::AuxiliaryPasses private
BarrierBatchMap
TMap<FRDGBarrierBatchBeginId, FRDGBarrierBatchBegin*, FRDGSetAllocator> FRDGBuilder::BarrierBatchMap private
Map of barrier batches begun from more than one pipe.
Definition at line 726 of file RenderGraphBuilder.h.
BarrierValidation
FRDGBarrierValidation FRDGBuilder::BarrierValidation private
Definition at line 1167 of file RenderGraphBuilder.h.
bEnabled
bool FRDGBuilder::bEnabled = false
Definition at line 998 of file RenderGraphBuilder.h.
bFlushResourcesRHI
bool FRDGBuilder::bFlushResourcesRHI = false private
Definition at line 1112 of file RenderGraphBuilder.h.
bInitialAsyncComputeFence
bool FRDGBuilder::bInitialAsyncComputeFence = GSupportsEfficientAsyncCompute private
Definition at line 480 of file RenderGraphBuilder.h.
Blackboard
FRDGBlackboard FRDGBuilder::Blackboard
The blackboard used to hold common data tied to the graph lifetime.
Definition at line 434 of file RenderGraphBuilder.h.
bParallelCompileEnabled
bool FRDGBuilder::bParallelCompileEnabled = false private
Definition at line 1013 of file RenderGraphBuilder.h.
bSupportsAsyncCompute
bool FRDGBuilder::bSupportsAsyncCompute = false private
Definition at line 481 of file RenderGraphBuilder.h.
Referenced by IsAsyncComputeEnabled().
bSupportsRenderPassMerge
bool FRDGBuilder::bSupportsRenderPassMerge = false private
Definition at line 482 of file RenderGraphBuilder.h.
bSupportsTransientBuffers
bool FRDGBuilder::bSupportsTransientBuffers = false private
Definition at line 594 of file RenderGraphBuilder.h.
bSupportsTransientTextures
bool FRDGBuilder::bSupportsTransientTextures = false private
Definition at line 593 of file RenderGraphBuilder.h.
Buffers
FRDGBufferRegistry FRDGBuilder::Buffers private
Definition at line 548 of file RenderGraphBuilder.h.
BuilderName
const FRDGEventName FRDGBuilder::BuilderName private
Definition at line 466 of file RenderGraphBuilder.h.
CullPassStack
TArray<FRDGPass*, FRDGArrayAllocator> FRDGBuilder::CullPassStack private
Definition at line 982 of file RenderGraphBuilder.h.
DispatchPasses
TArray<FRDGDispatchPass*, FRDGArrayAllocator> FRDGBuilder::DispatchPasses private
Tracks dispatch passes that need to launch tasks.
Definition at line 488 of file RenderGraphBuilder.h.
EpiloguePass
FRDGPass* FRDGBuilder::EpiloguePass = nullptr private
Definition at line 478 of file RenderGraphBuilder.h.
Referenced by GetEpiloguePassHandle().
EpilogueResourceAccesses
TArray<FRHITrackedAccessInfo, FRDGArrayAllocator> FRDGBuilder::EpilogueResourceAccesses private
Tracks the final access used on resources in order to call SetTrackedAccess.
Definition at line 729 of file RenderGraphBuilder.h.
ExtendResourceLifetimeScope
FRHICommandListScopedExtendResourceLifetime FRDGBuilder::ExtendResourceLifetimeScope private
Definition at line 1113 of file RenderGraphBuilder.h.
ExternalAccessResources
TSet<FRDGViewableResource*, DefaultKeyFuncs<FRDGViewableResource*>, FRDGSetAllocator> FRDGBuilder::ExternalAccessResources private
Definition at line 1099 of file RenderGraphBuilder.h.
ExternalBuffers
Experimental::TRobinHoodHashMap<FRHIBuffer*, FRDGBuffer*, DefaultKeyFuncs<FRHIBuffer*>, FRDGArrayAllocator> FRDGBuilder::ExternalBuffers private
Definition at line 584 of file RenderGraphBuilder.h.
ExternalTextures
Experimental::TRobinHoodHashMap<FRHITexture*, FRDGTexture*, DefaultKeyFuncs<FRHITexture*>, FRDGArrayAllocator> FRDGBuilder::ExternalTextures private
Tracks external resources to their registered render graph counterparts for de-duplication.
Definition at line 583 of file RenderGraphBuilder.h.
ExtractedBuffers
TArray<FExtractedBuffer, FRDGArrayAllocator> FRDGBuilder::ExtractedBuffers private
Definition at line 580 of file RenderGraphBuilder.h.
ExtractedTextures
TArray<FExtractedTexture, FRDGArrayAllocator> FRDGBuilder::ExtractedTextures private
Definition at line 565 of file RenderGraphBuilder.h.
FRDGAsyncComputeBudgetScopeGuard
friend FRDGBuilder::FRDGAsyncComputeBudgetScopeGuard private
Definition at line 1173 of file RenderGraphBuilder.h.
FRDGDispatchPassBuilder
friend FRDGBuilder::FRDGDispatchPassBuilder private
Definition at line 1176 of file RenderGraphBuilder.h.
FRDGScopedCsvStatExclusive
friend FRDGBuilder::FRDGScopedCsvStatExclusive private
Definition at line 1174 of file RenderGraphBuilder.h.
FRDGScopedCsvStatExclusiveConditional
friend FRDGBuilder::FRDGScopedCsvStatExclusiveConditional private
Definition at line 1175 of file RenderGraphBuilder.h.
FRDGTrace
friend FRDGBuilder::FRDGTrace private
Definition at line 1172 of file RenderGraphBuilder.h.
Referenced by ClobberPassOutputs().
kDefaultUnaccountedCSVStat
const char* const FRDGBuilder::kDefaultUnaccountedCSVStat static private
Definition at line 464 of file RenderGraphBuilder.h.
NumElementsCallbackBuffers
TArray<FRDGBuffer*, FRDGArrayAllocator> FRDGBuilder::NumElementsCallbackBuffers private
Tracks buffers that have a defered num elements callback.
Definition at line 587 of file RenderGraphBuilder.h.
ParallelExecute
struct FRDGBuilder::FParallelExecute FRDGBuilder::ParallelExecute private
[struct]
struct { ... } FRDGBuilder::ParallelSetup
Referenced by IsParallelSetupEnabled().
Passes
FRDGPassRegistry FRDGBuilder::Passes private
Registry of graph objects.
Definition at line 546 of file RenderGraphBuilder.h.
Referenced by GetEpilogueBarrierPass(), GetEpilogueBarrierPassHandle(), GetEpiloguePassHandle(), GetPassPipeline(), GetPrologueBarrierPass(), and GetPrologueBarrierPassHandle().
PooledBufferOwnershipMap
Experimental::TRobinHoodHashMap<FRDGPooledBuffer*, FRDGBuffer*, DefaultKeyFuncs<FRDGPooledBuffer*>, FConcurrentLinearArrayAllocator> FRDGBuilder::PooledBufferOwnershipMap private
Definition at line 678 of file RenderGraphBuilder.h.
PooledTextureOwnershipMap
Experimental::TRobinHoodHashMap<FRDGPooledTexture*, FRDGTexture*, DefaultKeyFuncs<FRDGPooledTexture*>, FConcurrentLinearArrayAllocator> FRDGBuilder::PooledTextureOwnershipMap private
Tracks the latest RDG resource to own an alias of a pooled resource (multiple RDG resources can reference the same pooled resource).
Definition at line 677 of file RenderGraphBuilder.h.
PostExecuteCallbacks
TArray<TUniqueFunction<void()>, FRDGArrayAllocator> FRDGBuilder::PostExecuteCallbacks private
Definition at line 1106 of file RenderGraphBuilder.h.
Referenced by AddPostExecuteCallback().
ProloguePass
FRDGPass* FRDGBuilder::ProloguePass = nullptr private
The epilogue and prologue passes are sentinels that are used to simplify graph logic around barriers and traversal.
The prologue pass is used exclusively for barriers before the graph executes, while the epilogue pass is used for resource extraction barriers–a property that also makes it the main root of the graph for culling purposes. The epilogue pass is added to the very end of the pass array for traversal purposes. The prologue does not need to participate in any graph traversal behavior.
Definition at line 477 of file RenderGraphBuilder.h.
Referenced by GetProloguePass().
PrologueSubresourceState
FRDGSubresourceState FRDGBuilder::PrologueSubresourceState private
Subresource state representing the graph prologue.
Used for immediate mode.
Definition at line 742 of file RenderGraphBuilder.h.
RasterPassCount
uint32 FRDGBuilder::RasterPassCount = 0 private
Definition at line 485 of file RenderGraphBuilder.h.
ReservedBufferCommitSizes
TArray<uint64, FRDGArrayAllocator> FRDGBuilder::ReservedBufferCommitSizes private
Definition at line 977 of file RenderGraphBuilder.h.
Referenced by AcquireReservedCommitHandle(), and GetReservedCommitSize().
RootAllocatorScope
FRDGAllocatorScope FRDGBuilder::RootAllocatorScope private
Definition at line 60 of file RenderGraphBuilder.h.
ScratchTextureState
FRDGTextureSubresourceState FRDGBuilder::ScratchTextureState private
Texture state used for intermediate operations.
Held here to avoid re-allocating.
Definition at line 739 of file RenderGraphBuilder.h.
TaskPriorityBias
int8 FRDGBuilder::TaskPriorityBias = 0
Definition at line 999 of file RenderGraphBuilder.h.
Tasks
TStaticArray<TArray<UE::Tasks::FTask, FRDGArrayAllocator>, (int32)ERDGSetupTaskWaitPoint::MAX> FRDGBuilder::Tasks
Array of all tasks for variants of AddSetupTask.
Definition at line 996 of file RenderGraphBuilder.h.
Textures
FRDGTextureRegistry FRDGBuilder::Textures private
Definition at line 547 of file RenderGraphBuilder.h.
TransientResourceAllocator
IRHITransientResourceAllocator* FRDGBuilder::TransientResourceAllocator = nullptr private
Definition at line 592 of file RenderGraphBuilder.h.
TransitionCreateQueue
FRDGTransitionCreateQueue FRDGBuilder::TransitionCreateQueue private
Set of all active barrier batch begin instances; used to create transitions.
Definition at line 736 of file RenderGraphBuilder.h.
Referenced by AddToEpilogueBarriers(), and AddToPrologueBarriers().
UniformBuffers
FRDGUniformBufferRegistry FRDGBuilder::UniformBuffers private
Definition at line 550 of file RenderGraphBuilder.h.
UploadedBuffers
TArray<FUploadedBuffer, FRDGArrayAllocator> FRDGBuilder::UploadedBuffers private
Definition at line 1090 of file RenderGraphBuilder.h.
UserValidation
FRDGUserValidation FRDGBuilder::UserValidation private
Definition at line 1166 of file RenderGraphBuilder.h.
Views
FRDGViewRegistry FRDGBuilder::Views private
Definition at line 549 of file RenderGraphBuilder.h.
WaitOutstandingTasks
FGraphEventArray FRDGBuilder::WaitOutstandingTasks private
Definition at line 1111 of file RenderGraphBuilder.h.
The documentation for this class was generated from the following file:
RenderGraphBuilder.h