Unreal Engine 5.6 C++ API: UE::UnrealEd::FViewportCameraMenuOptions Struct Reference
UE::UnrealEd::FViewportCameraMenuOptions Struct Reference
#include "UnrealEdViewportToolbar.h"
Public Member Functions
FViewportCameraMenuOptions ()
FViewportCameraMenuOptions & ShowAll ()
FViewportCameraMenuOptions & ShowCameraMovement ()
FViewportCameraMenuOptions & ShowLensControls ()
Data Fields
bool bShowCameraMovement: 1
bool bShowFieldOfView: 1
bool bShowNearAndFarPlanes: 1
Detailed Description
Definition at line 192 of file UnrealEdViewportToolbar.h.
Constructor & Destructor Documentation
FViewportCameraMenuOptions()
UE::UnrealEd::FViewportCameraMenuOptions::FViewportCameraMenuOptions ()
Referenced by ShowAll(), ShowCameraMovement(), and ShowLensControls().
Member Function Documentation
ShowAll()
FViewportCameraMenuOptions & UE::UnrealEd::FViewportCameraMenuOptions::ShowAll ()
References FViewportCameraMenuOptions().
ShowCameraMovement()
FViewportCameraMenuOptions & UE::UnrealEd::FViewportCameraMenuOptions::ShowCameraMovement ()
References FViewportCameraMenuOptions().
ShowLensControls()
FViewportCameraMenuOptions & UE::UnrealEd::FViewportCameraMenuOptions::ShowLensControls ()
References FViewportCameraMenuOptions().
Field Documentation
bShowCameraMovement
bool UE::UnrealEd::FViewportCameraMenuOptions::bShowCameraMovement
Definition at line 196 of file UnrealEdViewportToolbar.h.
bShowFieldOfView
bool UE::UnrealEd::FViewportCameraMenuOptions::bShowFieldOfView
Definition at line 197 of file UnrealEdViewportToolbar.h.
bShowNearAndFarPlanes
bool UE::UnrealEd::FViewportCameraMenuOptions::bShowNearAndFarPlanes
Definition at line 198 of file UnrealEdViewportToolbar.h.
The documentation for this struct was generated from the following file:
UnrealEdViewportToolbar.h