Unreal Engine 5.6 C++ API: VolumetricCloudComponent.h File Reference
VolumetricCloudComponent.h File Reference
#include "CoreMinimal.h"
#include "Components/SceneComponent.h"
#include "EngineDefines.h"
#include "GameFramework/Info.h"
#include "Misc/Guid.h"
#include "RenderResource.h"
#include "VolumetricCloudComponent.generated.h"
Data Structures
class AVolumetricCloud
class UVolumetricCloudComponent
Functions
UENUM() enum class EVolumetricCloudTracingMaxDistanceMode UCLASS ()
A component that represents a participating media material around a planet, e.g.
Variables
ClassGroup = Fog
UENUM() enum class EVolumetricCloudTracingMaxDistanceMode editinlinenew
hidecategories = (Info, Object, Input)
UENUM() enum class EVolumetricCloudTracingMaxDistanceMode meta = (BlueprintSpawnableComponent)
Function Documentation
UCLASS()
UENUM() enum class EVolumetricCloudTracingMaxDistanceMode UCLASS ()
A component that represents a participating media material around a planet, e.g.
A placeable actor that represents a participating media material around a planet, e.g.
clouds.
clouds.
See also
TODO address to the documentation.
Variable Documentation
ClassGroup
ClassGroup = Fog
Definition at line 254 of file VolumetricCloudComponent.h.
editinlinenew
UENUM() enum class EVolumetricCloudTracingMaxDistanceMode editinlinenew
Definition at line 27 of file VolumetricCloudComponent.h.
hidecategories
hidecategories = (Info, Object, Input)
Definition at line 254 of file VolumetricCloudComponent.h.
meta
UENUM() enum class EVolumetricCloudTracingMaxDistanceMode meta = (BlueprintSpawnableComponent)
Definition at line 27 of file VolumetricCloudComponent.h.
Referenced by UVolumetricCloudComponent::UE_DEPRECATED(), UVolumetricCloudComponent::UE_DEPRECATED(), UVolumetricCloudComponent::UFUNCTION(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), UVolumetricCloudComponent::UPROPERTY(), and UVolumetricCloudComponent::UPROPERTY().