Unreal Engine 5.6 C++ API: FArchiveReplaceOrClearExternalReferences< T > Class Template Reference
FArchiveReplaceOrClearExternalReferences< T > Class Template Reference
Identical to FArchiveReplaceObjectRef, but for references to private objects in other packages we clear the reference instead of preserving it (unless it makes it into the replacement map)
#include "ArchiveReplaceOrClearExternalReferences.h"
Public Member Functions
FArchiveReplaceOrClearExternalReferences (UObject *InSearchObject, const TMap< T *, T * > &InReplacementMap, UPackage *InDestPackage, EArchiveReplaceObjectFlags Flags=EArchiveReplaceObjectFlags::None)
const TMap< T *, T * > UPackage bool DestPackage (InDestPackage)
FArchive & operator<< (UObject *&Obj)
UE_DEPRECATED (5.0, "Use version that passes Flags instead of just bDelayStart") FArchiveReplaceOrClearExternalReferences(UObject *InSearchObject
Data Fields
const TMap< T *, T * > UPackage bool bDelayStart: TSuper(InSearchObject
const TMap< T *, T * > UPackage * InDestPackage
const TMap< T *, T * > & InReplacementMap
const TMap< T *, T * > UPackage bool InReplacementMap
Protected Attributes
UPackage * DestPackage
Package that we are loading into, references to private objects in other packages will be cleared.
Private Types
typedef FArchiveReplaceObjectRef< T > TSuper
Detailed Description
template<class T>
class FArchiveReplaceOrClearExternalReferences< T >
Identical to FArchiveReplaceObjectRef, but for references to private objects in other packages we clear the reference instead of preserving it (unless it makes it into the replacement map)
Definition at line 19 of file ArchiveReplaceOrClearExternalReferences.h.
Member Typedef Documentation
TSuper
template<class T> typedef FArchiveReplaceObjectRef<T> FArchiveReplaceOrClearExternalReferences< T >::TSuper private
Definition at line 21 of file ArchiveReplaceOrClearExternalReferences.h.
Constructor & Destructor Documentation
FArchiveReplaceOrClearExternalReferences()
template<class T> FArchiveReplaceOrClearExternalReferences< T >::FArchiveReplaceOrClearExternalReferences (UObject * InSearchObject, const TMap< T *, T * > & InReplacementMap, UPackage * InDestPackage, EArchiveReplaceObjectFlags Flags = EArchiveReplaceObjectFlags::None) inline
Definition at line 23 of file ArchiveReplaceOrClearExternalReferences.h.
References DelayStart, DestPackage, Flags, InDestPackage, InReplacementMap, and None.
Referenced by UE_DEPRECATED().
Member Function Documentation
DestPackage()
template<class T> const TMap< T *, T * > UPackage bool FArchiveReplaceOrClearExternalReferences< T >::DestPackage (InDestPackage) inline
Definition at line 44 of file ArchiveReplaceOrClearExternalReferences.h.
References bDelayStart, DestPackage, and InDestPackage.
operator<<()
template<class T> FArchive & FArchiveReplaceOrClearExternalReferences< T >::operator<< (UObject *& Obj) inline
Definition at line 52 of file ArchiveReplaceOrClearExternalReferences.h.
References CA_SUPPRESS, DestPackage, UObjectBaseUtility::GetOutermostObject(), UObjectBaseUtility::GetPackage(), UObjectBaseUtility::HasAnyFlags(), and RF_Public.
UE_DEPRECATED()
template<class T> FArchiveReplaceOrClearExternalReferences< T >::UE_DEPRECATED (5. 0, "Use version that passes Flags instead of just bDelayStart")
References FArchiveReplaceOrClearExternalReferences().
Field Documentation
bDelayStart
template<class T> const TMap<T*, T*> UPackage bool FArchiveReplaceOrClearExternalReferences< T >::bDelayStart
Definition at line 42 of file ArchiveReplaceOrClearExternalReferences.h.
Referenced by DestPackage().
DestPackage
template<class T> UPackage* FArchiveReplaceOrClearExternalReferences< T >::DestPackage protected
Package that we are loading into, references to private objects in other packages will be cleared.
Definition at line 78 of file ArchiveReplaceOrClearExternalReferences.h.
Referenced by FArchiveReplaceOrClearExternalReferences(), DestPackage(), and operator<<().
InDestPackage
template<class T> const TMap<T*, T*> UPackage* FArchiveReplaceOrClearExternalReferences< T >::InDestPackage
Definition at line 41 of file ArchiveReplaceOrClearExternalReferences.h.
Referenced by FArchiveReplaceOrClearExternalReferences(), and DestPackage().
InReplacementMap [1/2]
template<class T> const TMap<T*, T*>& FArchiveReplaceOrClearExternalReferences< T >::InReplacementMap
Definition at line 40 of file ArchiveReplaceOrClearExternalReferences.h.
Referenced by FArchiveReplaceOrClearExternalReferences().
InReplacementMap [2/2]
template<class T> const TMap<T*, T*> UPackage bool FArchiveReplaceOrClearExternalReferences< T >::InReplacementMap
Definition at line 43 of file ArchiveReplaceOrClearExternalReferences.h.
The documentation for this class was generated from the following file:
ArchiveReplaceOrClearExternalReferences.h