Unreal Engine 5.6 C++ API: FStructSharedMemory Struct Reference
FStructSharedMemory Struct Reference
Holds the information and memory about a UStruct.
#include "SharedStruct.h"
Data Structures
struct FStructSharedMemoryDeleter
Public Member Functions
FStructSharedMemory (const FStructSharedMemory &&Other)=delete
FStructSharedMemory (const FStructSharedMemory &Other)=delete
~FStructSharedMemory ()
const uint8 * GetMemory () const
Returns pointer to aligned struct memory.
uint8 * GetMutableMemory ()
Returns mutable pointer to aligned struct memory.
const UScriptStruct & GetScriptStruct () const
Returns struct type.
TObjectPtr< const UScriptStruct > & GetScriptStructPtr ()
FStructSharedMemory & operator= (const FStructSharedMemory &&Other)=delete
FStructSharedMemory & operator= (const FStructSharedMemory &Other)=delete
UE_DEPRECATED (5.6, "FStructSharedMemory::Create should be passed a pointer.") static TSharedPtr< FStructSharedMemory > Create(const UScriptStruct &InScriptStruct
Static Public Member Functions
static TSharedPtr< FStructSharedMemory > Create (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory=nullptr)
const uint8 typename static TArgs TSharedPtr< FStructSharedMemory > CreateArgs (TArgs &&... InArgs)
Data Fields
const uint8 * InStructMemory
Private Member Functions
FStructSharedMemory (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory=nullptr)
Static Private Member Functions
static FStructSharedMemory * CreateImpl (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory=nullptr)
Private Attributes
TObjectPtr< const UScriptStruct > ScriptStruct
uint8 StructMemory [0]
Memory for the struct described by ScriptStruct will be allocated here using the 'Flexible array member' pattern.
Detailed Description
Holds the information and memory about a UStruct.
Instances of these are shared using FConstSharedStruct and FSharedStruct.
The size of the allocation for this struct always includes both the size of the struct and also the size required to hold the structure described by the ScriptStruct. This avoids two pointer referencing (cache misses). Look at Create() to understand more.
A 'const FStructSharedMemory' the memory is immutable. We restrict shallow copies of StructMemory where it's not appropriate in the owning types that compose this type:
FSharedStruct A; ConstSharedStruct B = A; is allowed
ConstSharedStruct A; FSharedStruct B = A; is not allowed
This type is designed to be used in composition and should not be used outside the types that compose it.
Definition at line 35 of file StructUtils/SharedStruct.h.
Constructor & Destructor Documentation
~FStructSharedMemory()
FStructSharedMemory::~FStructSharedMemory () inline
Definition at line 37 of file StructUtils/SharedStruct.h.
References GetMutableMemory(), and ScriptStruct.
Referenced by FStructSharedMemory::FStructSharedMemoryDeleter::operator()().
FStructSharedMemory() [1/3]
FStructSharedMemory::FStructSharedMemory (const FStructSharedMemory & Other) delete
References FStructSharedMemory(), and Other.
Referenced by FStructSharedMemory(), FStructSharedMemory(), Create(), CreateArgs(), CreateImpl(), FStructSharedMemory::FStructSharedMemoryDeleter::operator()(), operator=(), and operator=().
FStructSharedMemory() [2/3]
FStructSharedMemory::FStructSharedMemory (const FStructSharedMemory && Other) delete
References FStructSharedMemory(), and Other.
FStructSharedMemory() [3/3]
FStructSharedMemory::FStructSharedMemory (const UScriptStruct * InScriptStruct, const uint8 * InStructMemory = nullptr) inline explicit private
Definition at line 112 of file StructUtils/SharedStruct.h.
References GetMutableMemory(), InStructMemory, and ScriptStruct.
Member Function Documentation
Create()
TSharedPtr< FStructSharedMemory > FStructSharedMemory::Create (const UScriptStruct * InScriptStruct, const uint8 * InStructMemory = nullptr) inline static
Definition at line 60 of file StructUtils/SharedStruct.h.
References FStructSharedMemory(), checkf, CreateImpl(), InStructMemory, MakeShareable(), StructMemory, and TEXT.
Referenced by USTRUCT().
CreateArgs()
const uint8 typename static TArgs TSharedPtr< FStructSharedMemory > FStructSharedMemory::CreateArgs (TArgs &&... InArgs) inline static
Definition at line 77 of file StructUtils/SharedStruct.h.
References FStructSharedMemory(), checkf, UE::StructUtils::CheckStructType(), CreateImpl(), Forward(), TBaseStructureBase< T, bHasStaticStruct >::Get(), MakeShareable(), StructMemory, and TEXT.
Referenced by USTRUCT().
CreateImpl()
FStructSharedMemory * FStructSharedMemory::CreateImpl (const UScriptStruct * InScriptStruct, const uint8 * InStructMemory = nullptr) inline static private
Definition at line 123 of file StructUtils/SharedStruct.h.
References FStructSharedMemory(), Align, CA_SUPPRESS, UStruct::GetMinAlignment(), UStruct::GetStructureSize(), InStructMemory, and StructMemory.
Referenced by Create(), and CreateArgs().
GetMemory()
const uint8 * FStructSharedMemory::GetMemory () const inline
Returns pointer to aligned struct memory.
Definition at line 89 of file StructUtils/SharedStruct.h.
References Align, ScriptStruct, and StructMemory.
GetMutableMemory()
uint8 * FStructSharedMemory::GetMutableMemory () inline
Returns mutable pointer to aligned struct memory.
Definition at line 95 of file StructUtils/SharedStruct.h.
References Align, ScriptStruct, and StructMemory.
Referenced by FStructSharedMemory(), and ~FStructSharedMemory().
GetScriptStruct()
const UScriptStruct & FStructSharedMemory::GetScriptStruct () const inline
Returns struct type.
Definition at line 101 of file StructUtils/SharedStruct.h.
References ObjectPtrDecay(), and ScriptStruct.
GetScriptStructPtr()
TObjectPtr< const UScriptStruct > & FStructSharedMemory::GetScriptStructPtr () inline
Definition at line 106 of file StructUtils/SharedStruct.h.
References ScriptStruct.
operator=() [1/2]
FStructSharedMemory & FStructSharedMemory::operator= (const FStructSharedMemory && Other) delete
References FStructSharedMemory(), and Other.
operator=() [2/2]
FStructSharedMemory & FStructSharedMemory::operator= (const FStructSharedMemory & Other) delete
References FStructSharedMemory(), and Other.
UE_DEPRECATED()
FStructSharedMemory::UE_DEPRECATED (5. 6, "FStructSharedMemory::Create should be passed a pointer.") const &
Field Documentation
InStructMemory
const uint8* FStructSharedMemory::InStructMemory
Initial value:
= nullptr)
    {
        return Create(&InScriptStruct, InStructMemory);
    }
    template<typename T
Definition at line 71 of file StructUtils/SharedStruct.h.
Referenced by FStructSharedMemory(), Create(), and CreateImpl().
ScriptStruct
TObjectPtr<const UScriptStruct> FStructSharedMemory::ScriptStruct private
Definition at line 134 of file StructUtils/SharedStruct.h.
Referenced by FStructSharedMemory(), ~FStructSharedMemory(), GetMemory(), GetMutableMemory(), GetScriptStruct(), and GetScriptStructPtr().
StructMemory
uint8 FStructSharedMemory::StructMemory[0] private
Memory for the struct described by ScriptStruct will be allocated here using the 'Flexible array member' pattern.
Access this using GetMutableMemory() / GetMemory() to account for memory alignment.
Definition at line 140 of file StructUtils/SharedStruct.h.
Referenced by Create(), CreateArgs(), CreateImpl(), GetMemory(), and GetMutableMemory().
The documentation for this struct was generated from the following file:
StructUtils/SharedStruct.h