Unreal Engine 5.6 C++ API: FMemoryArena Class Reference
FMemoryArena Class Reference abstract
Memory arena interface.
#include "MemoryArena.h"
Public Member Functions
FMemoryArena ()
FMemoryArena (const FMemoryArena &)=delete
virtual ~FMemoryArena ()
void * Alloc (SIZE_T Size, SIZE_T Alignment)
void Free (const void *MemoryBlock)
SIZE_T GetBlockSize (const void *MemoryBlock) const
const TCHAR * GetDebugName () const
FMemoryArena & operator= (const FMemoryArena &)=delete
Data Fields
uint16 ArenaId = ~uint16(0)
Private Types
enum { FlagNoFree = 1 << 0 }
Private Member Functions
virtual void * InternalAlloc (SIZE_T Size, SIZE_T Alignment)=0
virtual void InternalFree (const void *MemoryBlock, SIZE_T MemoryBlockSize)
virtual SIZE_T InternalGetBlockSize (const void *MemoryBlock) const =0
virtual const TCHAR * InternalGetDebugName () const
Private Attributes
uint16 ArenaFlags = 0
Detailed Description
Memory arena interface.
Definition at line 103 of file MemoryArena.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
FlagNoFree
Definition at line 125 of file MemoryArena.h.
Constructor & Destructor Documentation
FMemoryArena() [1/2]
FMemoryArena::FMemoryArena ()
Referenced by FMemoryArena(), and operator=().
~FMemoryArena()
virtual FMemoryArena::~FMemoryArena () virtual
FMemoryArena() [2/2]
FMemoryArena::FMemoryArena (const FMemoryArena &) delete
References FMemoryArena().
Member Function Documentation
Alloc()
void * FMemoryArena::Alloc (SIZE_T Size, SIZE_T Alignment)
References TSequenceHistory< HistorySize >::Size, UE_NOALIAS, and UE_RESTRICT.
Free()
void FMemoryArena::Free (const void * MemoryBlock)
References UE_NOALIAS.
Referenced by FArenaPointer::Free().
GetBlockSize()
SIZE_T FMemoryArena::GetBlockSize (const void * MemoryBlock) const
GetDebugName()
const TCHAR * FMemoryArena::GetDebugName () const
InternalAlloc()
virtual void * FMemoryArena::InternalAlloc (SIZE_T Size, SIZE_T Alignment) private pure virtual
Implemented in FAnsiArena, and FMallocArena.
References TSequenceHistory< HistorySize >::Size.
InternalFree()
virtual void FMemoryArena::InternalFree (const void * MemoryBlock, SIZE_T MemoryBlockSize) private virtual
Reimplemented in FAnsiArena, and FMallocArena.
InternalGetBlockSize()
virtual SIZE_T FMemoryArena::InternalGetBlockSize (const void * MemoryBlock) const private pure virtual
Implemented in FAnsiArena, and FMallocArena.
InternalGetDebugName()
virtual const TCHAR * FMemoryArena::InternalGetDebugName () const private virtual
Reimplemented in FAnsiArena, and FMallocArena.
operator=()
FMemoryArena & FMemoryArena::operator= (const FMemoryArena &) delete
References FMemoryArena().
Field Documentation
ArenaFlags
uint16 FMemoryArena::ArenaFlags = 0 private
Definition at line 127 of file MemoryArena.h.
ArenaId
uint16 FMemoryArena::ArenaId = ~uint16(0)
Definition at line 130 of file MemoryArena.h.
The documentation for this class was generated from the following file:
MemoryArena.h