Unreal Engine 5.6 C++ API: FRDGTextureUAVDesc Class Reference
FRDGTextureUAVDesc Class Reference final
Descriptor for render graph tracked UAV.
#include "RenderGraphResources.h"
Public Member Functions
FRDGTextureUAVDesc ()=default
FRDGTextureUAVDesc (FRDGTextureRef InTexture, uint8 InMipLevel=0, EPixelFormat InFormat=PF_Unknown, uint16 InFirstArraySlice=0, uint16 InNumArraySlices=0)
bool operator!= (const FRDGTextureUAVDesc &Other) const
bool operator== (const FRDGTextureUAVDesc &Other) const
Static Public Member Functions
static FRDGTextureUAVDesc CreateForMetaData (FRDGTextureRef Texture, ERDGTextureMetaDataAccess MetaData)
Create UAV with access to a specific meta data plane.
Data Fields
FRDGTextureRef Texture = nullptr
Friends
uint32 GetTypeHash (const FRDGTextureUAVDesc &Desc)
Detailed Description
Descriptor for render graph tracked UAV.
Definition at line 865 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGTextureUAVDesc() [1/2]
FRDGTextureUAVDesc::FRDGTextureUAVDesc () default
Referenced by CreateForMetaData(), GetTypeHash, operator!=(), and operator==().
FRDGTextureUAVDesc() [2/2]
FRDGTextureUAVDesc::FRDGTextureUAVDesc (FRDGTextureRef InTexture, uint8 InMipLevel = 0, EPixelFormat InFormat = PF_Unknown, uint16 InFirstArraySlice = 0, uint16 InNumArraySlices = 0) inline
Definition at line 871 of file RenderGraphResources.h.
References PF_Unknown, and Texture.
Member Function Documentation
CreateForMetaData()
FRDGTextureUAVDesc FRDGTextureUAVDesc::CreateForMetaData (FRDGTextureRef Texture, ERDGTextureMetaDataAccess MetaData) inline static
Create UAV with access to a specific meta data plane.
Definition at line 877 of file RenderGraphResources.h.
References FRDGTextureUAVDesc(), MetaData, and Texture.
operator!=()
bool FRDGTextureUAVDesc::operator!= (const FRDGTextureUAVDesc & Other) const inline
Definition at line 889 of file RenderGraphResources.h.
References FRDGTextureUAVDesc(), and Other.
operator==()
bool FRDGTextureUAVDesc::operator== (const FRDGTextureUAVDesc & Other) const inline
Definition at line 884 of file RenderGraphResources.h.
References FRDGTextureUAVDesc(), Other, and Texture.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRDGTextureUAVDesc & Desc) friend
Definition at line 894 of file RenderGraphResources.h.
References FRDGTextureUAVDesc(), GetTypeHash, HashCombine(), and Texture.
Referenced by GetTypeHash.
Field Documentation
Texture
FRDGTextureRef FRDGTextureUAVDesc::Texture = nullptr
Definition at line 899 of file RenderGraphResources.h.
Referenced by FRDGTextureUAVDesc(), CreateForMetaData(), GetTypeHash, and operator==().
The documentation for this class was generated from the following file:
RenderGraphResources.h