Unreal Engine 5.6 C++ API: FDynamicEmitterDataBase Struct Reference
FDynamicEmitterDataBase Struct Reference abstract
Base class for all emitter types.
#include "ParticleHelper.h"
Public Member Functions
FDynamicEmitterDataBase (const class UParticleModuleRequired *RequiredModule)
virtual ~FDynamicEmitterDataBase ()
virtual void GatherSimpleLights (const FParticleSystemSceneProxy *Proxy, const FSceneViewFamily &ViewFamily, FSimpleLightArray &OutParticleLights) const
Callback from the renderer to gather simple lights that this proxy wants renderered.
virtual void GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy *Proxy, const FSceneView *View, const FSceneViewFamily &ViewFamily, int32 ViewIndex, FMeshElementCollector &Collector) const
virtual const FMacroUVOverride & GetMacroUVOverride () const
Returns the current macro uv override.
virtual const FMaterialRenderProxy * GetMaterialRenderProxy ()=0
Retrieve the material render proxy to use for rendering this emitter.
virtual const FDynamicEmitterReplayDataBase & GetSource () const =0
Returns the source data for this particle system.
void operator delete (void *RawMemory, size_t Size)
void * operator new (size_t Size)
Custom new/delete with recycling.
virtual void ReleaseRenderThreadResources (const FParticleSystemSceneProxy *InOwnerProxy)
Release the render thread resources for this emitter data.
virtual void UpdateRenderThreadResourcesEmitter (const FParticleSystemSceneProxy *InOwnerProxy)
Create the render thread resources for this emitter data.
Data Fields
uint32 bSelected:1
true if this emitter is currently selected
uint32 bValid:1
true if this emitter has valid rendering data
int32 EmitterIndex
TStatId StatID
Stat id of this object, 0 if nobody asked for it yet.
Detailed Description
Base class for all emitter types.
Definition at line 1264 of file ParticleHelper.h.
Constructor & Destructor Documentation
FDynamicEmitterDataBase()
FDynamicEmitterDataBase::FDynamicEmitterDataBase (const class UParticleModuleRequired * RequiredModule)
Referenced by FDynamicSpriteEmitterDataBase::FDynamicSpriteEmitterDataBase().
~FDynamicEmitterDataBase()
virtual FDynamicEmitterDataBase::~FDynamicEmitterDataBase () inline virtual
Definition at line 1268 of file ParticleHelper.h.
Member Function Documentation
GatherSimpleLights()
virtual void FDynamicEmitterDataBase::GatherSimpleLights (const FParticleSystemSceneProxy * Proxy, const FSceneViewFamily & ViewFamily, FSimpleLightArray & OutParticleLights) const inline virtual
Callback from the renderer to gather simple lights that this proxy wants renderered.
Reimplemented in FDynamicMeshEmitterData, and FDynamicSpriteEmitterData.
Definition at line 1306 of file ParticleHelper.h.
GetDynamicMeshElementsEmitter()
virtual void FDynamicEmitterDataBase::GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy * Proxy, const FSceneView * View, const FSceneViewFamily & ViewFamily, int32 ViewIndex, FMeshElementCollector & Collector) const inline virtual
Reimplemented in FDynamicBeam2EmitterData, FDynamicMeshEmitterData, FDynamicSpriteEmitterData, and FDynamicTrailsEmitterData.
Definition at line 1294 of file ParticleHelper.h.
GetMacroUVOverride()
virtual const FMacroUVOverride & FDynamicEmitterDataBase::GetMacroUVOverride () const inline virtual
Returns the current macro uv override.
Specialized by FGPUSpriteDynamicEmitterData
Definition at line 1312 of file ParticleHelper.h.
References GetSource(), and FDynamicEmitterReplayDataBase::MacroUVOverride.
GetMaterialRenderProxy()
virtual const FMaterialRenderProxy * FDynamicEmitterDataBase::GetMaterialRenderProxy () pure virtual
Retrieve the material render proxy to use for rendering this emitter.
PURE VIRTUAL
Parameters
bSelected Whether the object is selected
Returns
FMaterialRenderProxy* The material proxt to render with.
Implemented in FDynamicSpriteEmitterDataBase.
GetSource()
virtual const FDynamicEmitterReplayDataBase & FDynamicEmitterDataBase::GetSource () const pure virtual
Returns the source data for this particle system.
Implemented in FDynamicBeam2EmitterData, FDynamicMeshEmitterData, FDynamicSpriteEmitterData, and FDynamicTrailsEmitterData.
Referenced by GetMacroUVOverride().
operator delete()
void FDynamicEmitterDataBase::operator delete (void * RawMemory, size_t Size)
References TSequenceHistory< HistorySize >::Size.
operator new()
void * FDynamicEmitterDataBase::operator new (size_t Size)
Custom new/delete with recycling.
References TSequenceHistory< HistorySize >::Size.
ReleaseRenderThreadResources()
virtual void FDynamicEmitterDataBase::ReleaseRenderThreadResources (const FParticleSystemSceneProxy * InOwnerProxy) inline virtual
Release the render thread resources for this emitter data.
Parameters
InOwnerProxy The proxy that owns this dynamic emitter data
Reimplemented in FDynamicMeshEmitterData.
Definition at line 1290 of file ParticleHelper.h.
UpdateRenderThreadResourcesEmitter()
virtual void FDynamicEmitterDataBase::UpdateRenderThreadResourcesEmitter (const FParticleSystemSceneProxy * InOwnerProxy) inline virtual
Create the render thread resources for this emitter data.
Parameters
InOwnerProxy The proxy that owns this dynamic emitter data
Reimplemented in FDynamicMeshEmitterData, and FDynamicSpriteEmitterData.
Definition at line 1281 of file ParticleHelper.h.
Field Documentation
bSelected
uint32 FDynamicEmitterDataBase::bSelected
true if this emitter is currently selected
Definition at line 1317 of file ParticleHelper.h.
bValid
uint32 FDynamicEmitterDataBase::bValid
true if this emitter has valid rendering data
Definition at line 1319 of file ParticleHelper.h.
EmitterIndex
int32 FDynamicEmitterDataBase::EmitterIndex
Definition at line 1321 of file ParticleHelper.h.
StatID
TStatId FDynamicEmitterDataBase::StatID mutable
Stat id of this object, 0 if nobody asked for it yet.
Definition at line 1315 of file ParticleHelper.h.
The documentation for this struct was generated from the following file:
ParticleHelper.h