Unreal Engine 5.6 C++ API: MovieSceneEvaluationField.h File Reference
MovieSceneEvaluationField.h File Reference
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/Set.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "EntitySystem/MovieSceneEntityIDs.h"
#include "EntitySystem/MovieSceneEntitySystemTypes.h"
#include "Evaluation/MovieSceneEvaluationKey.h"
#include "Evaluation/MovieSceneEvaluationTree.h"
#include "Evaluation/MovieSceneSegment.h"
#include "Evaluation/MovieSceneTrackIdentifier.h"
#include "Math/NumericLimits.h"
#include "Math/Range.h"
#include "Misc/FrameNumber.h"
#include "Misc/Guid.h"
#include "MovieSceneFrameMigration.h"
#include "MovieSceneSequenceID.h"
#include "Serialization/Archive.h"
#include "Templates/Function.h"
#include "Templates/TypeHash.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "UObject/WeakObjectPtr.h"
#include "UObject/WeakObjectPtrTemplates.h"
#include "MovieSceneEvaluationField.generated.h"
Data Structures
struct FMovieSceneEntityComponentFieldBuilder
Builder class used for populating an FMovieSceneEntityComponentField with data.
struct FMovieSceneEntityComponentFieldBuilder::FKeyToIndex
Array of entity keys and their field index within FMovieSceneEntityComponentField::Entities.
struct FMovieSceneEntityComponentFieldBuilder::FMetaDataToIndex
struct FMovieSceneEvaluationFieldEntityKeyFuncs
struct FMovieSceneEvaluationFieldEntityQuery
struct TStructOpsTypeTraits< FMovieSceneEvaluationFieldEntityTree >
Typedefs
using FMovieSceneEvaluationFieldEntitySet = TSet<FMovieSceneEvaluationFieldEntityQuery, FMovieSceneEvaluationFieldEntityKeyFuncs>
Functions
USTRUCT () struct FMovieSceneEvaluationFieldEntityKey
A key that uniquely identifies an entity by its owner and ID.
Typedef Documentation
FMovieSceneEvaluationFieldEntitySet
using FMovieSceneEvaluationFieldEntitySet = TSet<FMovieSceneEvaluationFieldEntityQuery, FMovieSceneEvaluationFieldEntityKeyFuncs>
Definition at line 170 of file MovieSceneEvaluationField.h.
Function Documentation
USTRUCT()
USTRUCT ()
A key that uniquely identifies an entity by its owner and ID.
Memory layout optimized primarily for speed of searching the applicable ranges.
Informational meta-data that applies to a given time range.
Struct that stores the key for an evaluated entity, and the index at which it was (or is to be) evaluated.
Holds segment pointers for all segments that are active for a given range of the sequence.
Lookup table index for a group of evaluation templates.
A pointer to a particular segment of a track held within an evaluation template.
A pointer to a track held within an evaluation template.
High-level container which acts as a look-up-table for IMovieSceneEntityProviders and their entities and meta-data in a sequence.
Generally generated and accessed through UMovieSceneCompiledDataManager, but can also be used independently. Entity fields are constructed using FMovieSceneEntityComponentFieldBuilder which ensures the invariants of this class are maintained along with guaranteeing no redundant entries exist.
The entity owner - either a UMovieSceneSection or perhaps a UMovieSceneTrack. Must implement the IMovieSceneEntityProvider interface
The identifer for the entity within the owner. Normally this will be irrelevant (and 0), but may be used to identifier unique entities by index, or flags
Opt-in - when this value is set, the entity should use this property path instead of the one defined on its generating section
Opt-in - when no meta-data is present, or this value is false, this entity cannot be evaluated as part of sub-sequence preroll
Opt-in - when no meta-data is present, or this value is false, this entity cannot be evaluated as part of sub-sequence postroll
Check if this field is empty
Retrieve an entity from its index
Retrieve the meta-data for an entity
Returns
The meta-data for an entity or nullptr if it has none associated with it
Retrieve the shared meta-data for an entity
Returns
The shared meta-data for an entity or nullptr if it has none associated with it
Query the persistent entities for any given time within a sequence.
Note
: Persistent entities should remain alive until they are no longer present at the current time.
Parameters
QueryTime The time at which to query the field (in the TickResolution of the sequence this was generated from)
OutRange Will receive the hull of the range that was intersected for which the resulting OutEntities remains constant
OutEntities A set that will be populated with all the entities that exist at the specified time
Query the persistent entities for any given time within a sequence.
Note
: Persistent entities should remain alive until they are no longer present at the current time.
Parameters
QueryTime The time at which to query the field (in the TickResolution of the sequence this was generated from)
QueryCallback A handler for dealing with the resulting entities
OutRange Will receive the hull of the range that was intersected for which the resulting OutEntities remains constant
Check whether this field contains any one-shot entities
Query the one-shot entities that overlap with the specified query range.
Note
: One-shot entities only ever live for a single frame of evaluation.
Parameters
QueryRange The ranger over which to query the field (in the TickResolution of the sequence this was generated from)
OutEntities A set that will be populated with all the entities that overlapped at all with the specified range
A hierarchical tree specifiying indices into the Entities array for any given time such persistent entities are active
A hierarchical tree specifiying indices into the Entities array for any given time such one-shot entities are active
16 bytes - Flat array of unique entities. The 2 tree types specify indices into this array
16 bytes - Optional meta-data for specific entities. Specified in FMovieSceneEvaluationFieldEntity::MetaDataIndex.
16 bytes - Optional shared meta-data for groups of entities. Specified in FMovieSceneEvaluationFieldEntity::SharedMetaDataIndex.
Default constructor
Construction from a sequence ID, and the index of the track within that sequence's track list
Check for equality
Get a hashed representation of this type
The sequence ID that identifies to which sequence the track belongs
The Identifier of the track inside the track map (see FMovieSceneEvaluationTemplate::Tracks)
The number of initialization pointers are stored after &FMovieSceneEvaluationGroup::SegmentPtrLUT[0] + LUTOffset.
The number of evaluation pointers are stored after &FMovieSceneEvaluationGroup::SegmentPtrLUT[0] + LUTOffset + NumInitPtrs.
Array of indices that define all the flush groups in the range.
Reset this meta-data
Diff the active sequences this frame, with the specified previous frame's meta-data
Parameters
LastFrame Meta-data pertaining to the last frame
NewSequences (Optional) Ptr to an array that will be populated with sequences that are new this frame
ExpiredSequences (Optional) Ptr to an array that will be populated with sequences that are no longer being evaluated
Diff the active entities (tracks and sections) this frame, with the specified previous frame's meta-data
Parameters
LastFrame Meta-data pertaining to the last frame
NewKeys (Optional) Ptr to an array that will be populated with entities that are new this frame
ExpiredKeys (Optional) Ptr to an array that will be populated with entities that are no longer being evaluated
Array of sequences that are active in this time range.
Array of entities (tracks and/or sections) that are active in this time range.
Efficiently find the entry that exists at the specified time, if any
Parameters
Time The time at which to seach
Returns
The index within Ranges, Groups and MetaData that the current time resides, or INDEX_NONE if there is nothing to do at the requested time
Deduce the indices into Ranges and Groups that overlap with the specified time range
Parameters
Range The range to overlap with our field
Returns
A range of indices for which GetRange() overlaps the specified Range, of the form [First, First+Num)
Invalidate a range in this field
Parameters
Range The range to overlap with our field
Returns
A range of indices into Ranges and Groups that overlap with the requested range
Insert a new range into this field
Parameters
InRange The total range to insert to the field. Will potentially be intersected with preexisting adjacent ranges
InGroup The group defining what should happen at this time
InMetaData The meta-data defining efficient access to what happens in this frame
Returns
The index the entries were inserted at
Add the specified data to this field, assuming the specified range lies after any other entries
Parameters
InRange The range to add
InGroup The group defining what should happen at this time
InMetaData The meta-data defining efficient access to what happens in this frame
Access this field's signature
Access this field's size
Access this entire field's set of ranges
Lookup a valid range by index
Parameters
Index The valid index within the ranges to lookup
Returns
The range
Lookup a valid evaluation group by entry index
Parameters
Index The valid index within the evaluation group array to lookup
Returns
The group
Lookup valid meta-data by entry index
Parameters
Index The valid index within the meta-data array to lookup
Returns
The meta-data
Ranges stored separately for fast (cache efficient) lookup. Each index has a corresponding entry in FMovieSceneEvaluationField::Groups.
Groups that store segment pointers for each of the above ranges. Each index has a corresponding entry in FMovieSceneEvaluationField::Ranges.
Meta data that maps to entries in the 'Ranges' array.
Definition at line 46 of file MovieSceneEvaluationField.h.
References A, B, GENERATED_BODY, GetTypeHash(), operator!=(), operator==(), and UPROPERTY.