Unreal Engine 5.6 C++ API: UE::AnimNext::FNodeHandle Struct Reference
UE::AnimNext::FNodeHandle Struct Reference final
Node Handle A node handle represents a reference to a specific node instance in the shared/read-only portion of a sub-graph.
#include "NodeHandle.h"
Public Member Functions
constexpr FNodeHandle () noexcept
FNodeID GetNodeID () const
uint32 GetSharedOffset () const
constexpr bool IsNodeID () const noexcept
constexpr bool IsSharedOffset () const noexcept
constexpr bool IsValid () const noexcept
constexpr bool operator!= (FNodeHandle RHS) const noexcept
constexpr bool operator== (FNodeHandle RHS) const noexcept
Static Public Member Functions
static constexpr FNodeHandle FromNodeID (FNodeID NodeID) noexcept
static constexpr FNodeHandle FromSharedOffset (uint32 SharedOffset) noexcept
Private Member Functions
constexpr FNodeHandle (uint32 PackedValue) noexcept
constexpr uint32 GetPackedValue () const
Static Private Member Functions
static constexpr FNodeHandle FromPackedValue (uint32 PackedValue) noexcept
Private Attributes
friend FAnimNextEntryPointHandle
friend FAnimNextTraitHandle
uint32 PackedSharedOffsetOrID
Static Private Attributes
static constexpr uint32 INVALID_NODE_HANDLE_RAW_VALUE = ~0u >> (32 - 24)
static constexpr uint32 NODE_HANDLE_MASK = INVALID_NODE_HANDLE_RAW_VALUE
static constexpr uint32 NODE_ID_MARKER_BIT_MASK = 0x01u
static constexpr uint32 NODE_ID_SHIFT = 1
Detailed Description
Node Handle A node handle represents a reference to a specific node instance in the shared/read-only portion of a sub-graph.
It points to a FNodeDescription when resolved.
Internally, it contains either a shared data offset into the parent graph (at runtime) or a FNodeID (during compilation and on disk). Shared offsets must be computed at runtime and as such we use the FNodeID to resolve into our final offset on load. We only use the bottom 24 bits. If the LSB is 0, the packed value represents a shared offset (due to alignment) but if the LSB is 1, the packed value represents a node ID shifted left by 1.
See also
FNodeDescription, FNodeID
Definition at line 26 of file NodeHandle.h.
Constructor & Destructor Documentation
FNodeHandle() [1/2]
UE::AnimNext::FNodeHandle::FNodeHandle () inline constexpr noexcept
Definition at line 29 of file NodeHandle.h.
References INVALID_NODE_HANDLE_RAW_VALUE, and PackedSharedOffsetOrID.
Referenced by FromNodeID(), FromPackedValue(), FromSharedOffset(), operator!=(), and operator==().
FNodeHandle() [2/2]
UE::AnimNext::FNodeHandle::FNodeHandle (uint32 PackedValue) inline explicit constexpr private noexcept
Definition at line 75 of file NodeHandle.h.
Member Function Documentation
FromNodeID()
constexpr FNodeHandle UE::AnimNext::FNodeHandle::FromNodeID (FNodeID NodeID) inline static constexpr noexcept
Definition at line 45 of file NodeHandle.h.
References FNodeHandle(), NODE_ID_MARKER_BIT_MASK, and NODE_ID_SHIFT.
FromPackedValue()
constexpr FNodeHandle UE::AnimNext::FNodeHandle::FromPackedValue (uint32 PackedValue) inline static constexpr private noexcept
Definition at line 83 of file NodeHandle.h.
References FNodeHandle().
Referenced by USTRUCT(), and USTRUCT().
FromSharedOffset()
constexpr FNodeHandle UE::AnimNext::FNodeHandle::FromSharedOffset (uint32 SharedOffset) inline static constexpr noexcept
Definition at line 34 of file NodeHandle.h.
References FNodeHandle(), and NODE_HANDLE_MASK.
GetNodeID()
FNodeID UE::AnimNext::FNodeHandle::GetNodeID () const inline
Definition at line 68 of file NodeHandle.h.
References check, UE::AnimNext::FNodeID::FromRawValue(), IsNodeID(), NODE_HANDLE_MASK, NODE_ID_SHIFT, and PackedSharedOffsetOrID.
GetPackedValue()
uint32 UE::AnimNext::FNodeHandle::GetPackedValue () const inline constexpr private
Definition at line 80 of file NodeHandle.h.
References PackedSharedOffsetOrID.
Referenced by USTRUCT(), and USTRUCT().
GetSharedOffset()
uint32 UE::AnimNext::FNodeHandle::GetSharedOffset () const inline
Definition at line 65 of file NodeHandle.h.
References check, IsSharedOffset(), NODE_HANDLE_MASK, and PackedSharedOffsetOrID.
IsNodeID()
bool UE::AnimNext::FNodeHandle::IsNodeID () const inline constexpr noexcept
Definition at line 62 of file NodeHandle.h.
References IsValid(), NODE_ID_MARKER_BIT_MASK, and PackedSharedOffsetOrID.
Referenced by GetNodeID(), and USTRUCT().
IsSharedOffset()
bool UE::AnimNext::FNodeHandle::IsSharedOffset () const inline constexpr noexcept
Definition at line 59 of file NodeHandle.h.
References IsValid(), NODE_ID_MARKER_BIT_MASK, and PackedSharedOffsetOrID.
Referenced by GetSharedOffset().
IsValid()
bool UE::AnimNext::FNodeHandle::IsValid () const inline constexpr noexcept
Definition at line 56 of file NodeHandle.h.
References INVALID_NODE_HANDLE_RAW_VALUE, NODE_HANDLE_MASK, and PackedSharedOffsetOrID.
Referenced by IsNodeID(), IsSharedOffset(), and USTRUCT().
operator!=()
bool UE::AnimNext::FNodeHandle::operator!= (FNodeHandle RHS) const inline constexpr noexcept
Definition at line 72 of file NodeHandle.h.
References FNodeHandle(), NODE_HANDLE_MASK, and PackedSharedOffsetOrID.
operator==()
bool UE::AnimNext::FNodeHandle::operator== (FNodeHandle RHS) const inline constexpr noexcept
Definition at line 71 of file NodeHandle.h.
References FNodeHandle(), NODE_HANDLE_MASK, and PackedSharedOffsetOrID.
Field Documentation
FAnimNextEntryPointHandle
friend UE::AnimNext::FNodeHandle::FAnimNextEntryPointHandle private
Definition at line 94 of file NodeHandle.h.
FAnimNextTraitHandle
friend UE::AnimNext::FNodeHandle::FAnimNextTraitHandle private
Definition at line 93 of file NodeHandle.h.
INVALID_NODE_HANDLE_RAW_VALUE
uint32 UE::AnimNext::FNodeHandle::INVALID_NODE_HANDLE_RAW_VALUE = ~0u >> (32 - 24) static constexpr private
Definition at line 86 of file NodeHandle.h.
Referenced by FNodeHandle(), IsValid(), USTRUCT(), and USTRUCT().
NODE_HANDLE_MASK
uint32 UE::AnimNext::FNodeHandle::NODE_HANDLE_MASK = INVALID_NODE_HANDLE_RAW_VALUE static constexpr private
Definition at line 87 of file NodeHandle.h.
Referenced by FromSharedOffset(), GetNodeID(), GetSharedOffset(), IsValid(), operator!=(), and operator==().
NODE_ID_MARKER_BIT_MASK
uint32 UE::AnimNext::FNodeHandle::NODE_ID_MARKER_BIT_MASK = 0x01u static constexpr private
Definition at line 88 of file NodeHandle.h.
Referenced by FromNodeID(), IsNodeID(), and IsSharedOffset().
NODE_ID_SHIFT
uint32 UE::AnimNext::FNodeHandle::NODE_ID_SHIFT = 1 static constexpr private
Definition at line 89 of file NodeHandle.h.
Referenced by FromNodeID(), and GetNodeID().
PackedSharedOffsetOrID
uint32 UE::AnimNext::FNodeHandle::PackedSharedOffsetOrID private
Definition at line 91 of file NodeHandle.h.
Referenced by FNodeHandle(), GetNodeID(), GetPackedValue(), GetSharedOffset(), IsNodeID(), IsSharedOffset(), IsValid(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
NodeHandle.h