Unreal Engine 5.6 C++ API: Metasound::Frontend::FRenameRootGraphClass Class Reference
Metasound::Frontend::FRenameRootGraphClass Class Reference
Sets the document's graph class, optionally updating the namespace and variant.
#include "MetasoundFrontendTransform.h"
Public Member Functions
UE_DEPRECATED (5.5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead") METASOUNDFRONTEND_API bool Transform(FMetasoundFrontendDocument &InOutDocument) const override
UE_DEPRECATED (5.5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead") static bool Generate(FDocumentHandle InDocument
Public Member Functions inherited from Metasound::Frontend::IDocumentTransform
virtual ~IDocumentTransform ()=default
virtual bool Transform (FDocumentHandle InDocument) const =0
Return true if InDocument was modified, false otherwise.
virtual METASOUNDFRONTEND_API bool Transform (FMetasoundFrontendDocument &InOutDocument) const
Return true if InDocument was modified, false otherwise.
Data Fields
const FGuid & InGuid
const FGuid const FName Namespace = { }
const FGuid const FName const FName Variant
Private Attributes
const FMetasoundFrontendClassName NewClassName
Detailed Description
Sets the document's graph class, optionally updating the namespace and variant.
Definition at line 222 of file MetasoundFrontendTransform.h.
Member Function Documentation
UE_DEPRECATED() [1/2]
Metasound::Frontend::FRenameRootGraphClass::UE_DEPRECATED (5. 5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead") const & override
References Metasound::Frontend::IDocumentTransform::Transform(), UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [2/2]
Metasound::Frontend::FRenameRootGraphClass::UE_DEPRECATED (5. 5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead")
Referenced by UE_DEPRECATED().
Field Documentation
InGuid
const FGuid& Metasound::Frontend::FRenameRootGraphClass::InGuid
Definition at line 228 of file MetasoundFrontendTransform.h.
Namespace
const FGuid const FName Metasound::Frontend::FRenameRootGraphClass::Namespace = { }
Definition at line 228 of file MetasoundFrontendTransform.h.
NewClassName
const FMetasoundFrontendClassName Metasound::Frontend::FRenameRootGraphClass::NewClassName private
Definition at line 224 of file MetasoundFrontendTransform.h.
Variant
const FGuid const FName const FName Metasound::Frontend::FRenameRootGraphClass::Variant
Initial value:
= { })
        {
            return false;
        }
        UE_DEPRECATED(5.5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead")
        static bool Generate(FMetasoundFrontendDocument& InDocument, const FGuid& InGuid, const FName Namespace = { }, const FName Variant = { })
        {
            return false;
        }
        UE_DEPRECATED(5.5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead")
        FRenameRootGraphClass(const FMetasoundFrontendClassName InClassName)
            : NewClassName(InClassName)
        {
        }
        UE_DEPRECATED(5.5, "Use FMetasoundFrontendDocumentBuilder::GenerateNewClassName instead")
         METASOUNDFRONTEND_API bool Transform(FDocumentHandle InDocument) const override
Definition at line 228 of file MetasoundFrontendTransform.h.
The documentation for this class was generated from the following file:
MetasoundFrontendTransform.h