Unreal Engine 5.6 C++ API: FThumbnailPreviewScene::FConstructionValues Struct Reference
FThumbnailPreviewScene::FConstructionValues Struct Reference
#include "ThumbnailHelpers.h"
Public Member Functions
FConstructionValues ()
FConstructionValues & SetCreateFloorPlane (const bool bInValue)
FConstructionValues & SetCreateSkySphere (const bool bInValue)
FConstructionValues & SetDefaultLightingThumbnailScene (const bool bInValue)
FConstructionValues & SetLightBrightness2 (const float InValue)
FConstructionValues & SetLightBrightness3 (const float InValue)
FConstructionValues & SetLightRotation2 (const FRotator &InValue)
FConstructionValues & SetLightRotation3 (const FRotator &InValue)
FConstructionValues & SetSkyCubeMap (const bool bInValue)
Data Fields
uint32 bCreateFloorPlane: 1
uint32 bCreateSkySphere: 1
uint32 bDefaultLightingThumbnailScene: 1
uint32 bSetSkyCubeMap: 1
float LightBrightness2
float LightBrightness3
FRotator LightRotation2
FRotator LightRotation3
Detailed Description
Definition at line 21 of file ThumbnailHelpers.h.
Constructor & Destructor Documentation
FConstructionValues()
FThumbnailPreviewScene::FConstructionValues::FConstructionValues () inline
Definition at line 23 of file ThumbnailHelpers.h.
References bCreateFloorPlane, bCreateSkySphere, bDefaultLightingThumbnailScene, bSetSkyCubeMap, LightBrightness2, LightBrightness3, LightRotation2, and LightRotation3.
Referenced by SetCreateFloorPlane(), SetCreateSkySphere(), SetDefaultLightingThumbnailScene(), SetLightBrightness2(), SetLightBrightness3(), SetLightRotation2(), SetLightRotation3(), and SetSkyCubeMap().
Member Function Documentation
SetCreateFloorPlane()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetCreateFloorPlane (const bool bInValue) inline
Definition at line 51 of file ThumbnailHelpers.h.
References FConstructionValues(), and bCreateFloorPlane.
SetCreateSkySphere()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetCreateSkySphere (const bool bInValue) inline
Definition at line 44 of file ThumbnailHelpers.h.
References FConstructionValues(), and bCreateSkySphere.
SetDefaultLightingThumbnailScene()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetDefaultLightingThumbnailScene (const bool bInValue) inline
Definition at line 45 of file ThumbnailHelpers.h.
References FConstructionValues(), and bDefaultLightingThumbnailScene.
SetLightBrightness2()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetLightBrightness2 (const float InValue) inline
Definition at line 47 of file ThumbnailHelpers.h.
References FConstructionValues(), and LightBrightness2.
SetLightBrightness3()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetLightBrightness3 (const float InValue) inline
Definition at line 49 of file ThumbnailHelpers.h.
References FConstructionValues(), and LightBrightness3.
SetLightRotation2()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetLightRotation2 (const FRotator & InValue) inline
Definition at line 46 of file ThumbnailHelpers.h.
References FConstructionValues(), and LightRotation2.
SetLightRotation3()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetLightRotation3 (const FRotator & InValue) inline
Definition at line 48 of file ThumbnailHelpers.h.
References FConstructionValues(), and LightRotation3.
SetSkyCubeMap()
FConstructionValues & FThumbnailPreviewScene::FConstructionValues::SetSkyCubeMap (const bool bInValue) inline
Definition at line 50 of file ThumbnailHelpers.h.
References FConstructionValues(), and bSetSkyCubeMap.
Field Documentation
bCreateFloorPlane
uint32 FThumbnailPreviewScene::FConstructionValues::bCreateFloorPlane
Definition at line 42 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetCreateFloorPlane().
bCreateSkySphere
uint32 FThumbnailPreviewScene::FConstructionValues::bCreateSkySphere
Definition at line 35 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetCreateSkySphere().
bDefaultLightingThumbnailScene
uint32 FThumbnailPreviewScene::FConstructionValues::bDefaultLightingThumbnailScene
Definition at line 36 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetDefaultLightingThumbnailScene().
bSetSkyCubeMap
uint32 FThumbnailPreviewScene::FConstructionValues::bSetSkyCubeMap
Definition at line 41 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetSkyCubeMap().
LightBrightness2
float FThumbnailPreviewScene::FConstructionValues::LightBrightness2
Definition at line 38 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetLightBrightness2().
LightBrightness3
float FThumbnailPreviewScene::FConstructionValues::LightBrightness3
Definition at line 40 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetLightBrightness3().
LightRotation2
FRotator FThumbnailPreviewScene::FConstructionValues::LightRotation2
Definition at line 37 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetLightRotation2().
LightRotation3
FRotator FThumbnailPreviewScene::FConstructionValues::LightRotation3
Definition at line 39 of file ThumbnailHelpers.h.
Referenced by FConstructionValues(), and SetLightRotation3().
The documentation for this struct was generated from the following file:
ThumbnailHelpers.h