Unreal Engine 5.6 C++ API: TLockFreeClassAllocator< T, TPaddingForCacheContention > Class Template Reference
TLockFreeClassAllocator< T, TPaddingForCacheContention > Class Template Reference
Thread safe, lock free pooling allocator of memory for instances of T.
#include "LockFreeFixedSizeAllocator.h"
Public Member Functions
void * Allocate ()
Returns a memory block of size sizeof(T).
void Free (T *Item)
Calls a destructor on Item and returns the memory to the free list for recycling.
T * New ()
Returns a new T using the default constructor.
Additional Inherited Members
Private Member Functions inherited from TLockFreeFixedSizeAllocator< sizeof(T), TPaddingForCacheContention, FNoopCounter >
TLockFreeFixedSizeAllocator ()
~TLockFreeFixedSizeAllocator ()
Destructor, returns all memory via FMemory::Free.
void * Allocate (int32 Alignment=MIN_ALIGNMENT)
Allocates a memory block of size SIZE.
void Free (void *Item)
Puts a memory block previously obtained from Allocate() back on the free list for future use.
FNoopCounter::IntegerType GetNumFree () const
Gets the number of allocated memory blocks that are currently unused.
FNoopCounter::IntegerType GetNumUsed () const
Gets the number of allocated memory blocks that are currently in use.
void Trim ()
Returns all free memory to the heap.
Detailed Description
template<class T, int TPaddingForCacheContention>
class TLockFreeClassAllocator< T, TPaddingForCacheContention >
Thread safe, lock free pooling allocator of memory for instances of T.
Never returns free space until program shutdown.
Definition at line 343 of file LockFreeFixedSizeAllocator.h.
Member Function Documentation
Allocate()
template<class T, int TPaddingForCacheContention> void * TLockFreeClassAllocator< T, TPaddingForCacheContention >::Allocate () inline
Returns a memory block of size sizeof(T).
Returns
Pointer to the allocated memory.
See also
Free, New
Definition at line 352 of file LockFreeFixedSizeAllocator.h.
References TLockFreeFixedSizeAllocator< sizeof(T), TPaddingForCacheContention, FNoopCounter >::TLockFreeFixedSizeAllocator(), and Allocate().
Referenced by Allocate(), and New().
Free()
template<class T, int TPaddingForCacheContention> void TLockFreeClassAllocator< T, TPaddingForCacheContention >::Free (T * Item) inline
Calls a destructor on Item and returns the memory to the free list for recycling.
Parameters
Item The item whose memory to free.
See also
Allocate, New
Definition at line 374 of file LockFreeFixedSizeAllocator.h.
References TLockFreeFixedSizeAllocator< sizeof(T), TPaddingForCacheContention, FNoopCounter >::TLockFreeFixedSizeAllocator(), Free(), and Item.
Referenced by Free().
New()
template<class T, int TPaddingForCacheContention> T * TLockFreeClassAllocator< T, TPaddingForCacheContention >::New () inline
Returns a new T using the default constructor.
Returns
Pointer to the new object.
See also
Allocate, Free
Definition at line 363 of file LockFreeFixedSizeAllocator.h.
References Allocate().
The documentation for this class was generated from the following file:
LockFreeFixedSizeAllocator.h