Unreal Engine 5.6 C++ API: SAudioMaterialSlider Class Reference
SAudioMaterialSlider Class Reference
A simple slate that renders slider in single material and modifies the material on value change.
#include "SAudioMaterialSlider.h"
Public Member Functions
AUDIOWIDGETS_API void ApplyNewMaterial ()
Apply new material to be used to render the Slate.
virtual AUDIOWIDGETS_API FVector2D ComputeDesiredSize (float) const override
Overwritten from SWidget.
virtual AUDIOWIDGETS_API bool IsInteractable () const override
AUDIOWIDGETS_API bool IsLocked () const
virtual AUDIOWIDGETS_API FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual AUDIOWIDGETS_API FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual AUDIOWIDGETS_API FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual AUDIOWIDGETS_API FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual AUDIOWIDGETS_API void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent) override
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual AUDIOWIDGETS_API FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual AUDIOWIDGETS_API int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
Overwritten from SWidget.
AUDIOWIDGETS_API void SetFineTuneSpeed (const float InMouseFineTuneSpeed)
Set the FineTuneSpeed attribute.
AUDIOWIDGETS_API void SetLocked (const bool bInLocked)
Set the bLocked attribute.
AUDIOWIDGETS_API void SetMouseUsesStep (const bool InUsesStep)
See the bMouseUsesStep attribute.
AUDIOWIDGETS_API void SetOrientation (EOrientation InOrientation)
Set the orientation of the slider.
AUDIOWIDGETS_API void SetStepSize (const float InStepSize)
Set the StepSize attribute.
AUDIOWIDGETS_API void SetTuneSpeed (const float InMouseTuneSpeed)
Set the TuneSpeed attribute.
AUDIOWIDGETS_API void SetValue (TAttribute< float > InValueAttribute)
Set the Value attribute.
SLATE_ARGUMENT (TWeakObjectPtr< UObject >, Owner) SLATE_ARGUMENT(EOrientation
The owner object.
Orientation FineTuneSpeed SLATE_ATTRIBUTE (bool, IsFocusable) SLATE_ATTRIBUTE(bool
When true slider will be keyboard focusable, else only mouse-clickable and never keyboard focusable.
Orientation FineTuneSpeed Locked SLATE_ATTRIBUTE (bool, MouseUsesStep) SLATE_ATTRIBUTE(float
Moves Slider handle in given steps.
Orientation SLATE_ATTRIBUTE (float, TuneSpeed) SLATE_ATTRIBUTE(float
The tune speed of the slider handle.
SLATE_BEGIN_ARGS (SAudioMaterialSlider)
Orientation FineTuneSpeed Locked StepSize ValueAttribute OnValueCommitted SLATE_END_ARGS () AUDIOWIDGETS_API void Construct(const FArguments &InArgs)
Construct the widget.
Orientation FineTuneSpeed Locked StepSize ValueAttribute SLATE_EVENT (FOnFloatValueChanged, OnValueChanged) SLATE_EVENT(FOnFloatValueChanged
Called when the value is changed by the slider.
Orientation FineTuneSpeed Locked StepSize SLATE_STYLE_ARGUMENT (FAudioMaterialSliderStyle, AudioMaterialSliderStyle) SLATE_ATTRIBUTE(float
The style used to draw the slider.
virtual AUDIOWIDGETS_API bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
Public Member Functions inherited from SLeafWidget
SLeafWidget ()
virtual ~SLeafWidget ()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FOnFloatValueChanged OnValueChanged
FOnFloatValueChanged OnValueCommitted
Private Member Functions
void CommitValue (float NewValue)
Commits the specified slider value.
Private Attributes
const FAudioMaterialSliderStyle * AudioMaterialSliderStyle = nullptr
bool bIsFineTune = false
TAttribute< bool > bIsFocusable
Holds a flag indicating whether slider will be keyboard focusable.
TAttribute< bool > bLocked
TAttribute< bool > bMouseUsesStep
EMouseCursor::Type CachedCursor = EMouseCursor::None
TAttribute< TOptional< FVector2D > > DesiredSizeOverride
TWeakObjectPtr< UMaterialInstanceDynamic > DynamicMaterial
TAttribute< float > FineTuneSpeed
Holds the amount to adjust the slider On Mouse move & FineTuning.
FVector2D MouseDownStartPosition
float MouseDownValue = 0.f
EOrientation Orientation
TWeakObjectPtr< UObject > Owner
int32 PixelDelta = 50
TAttribute< float > StepSize
Holds the amount to adjust the value when steps are used.
TAttribute< float > TuneSpeed
Holds the amount to adjust the slider On Mouse move.
TAttribute< float > ValueAttribute = 0.f
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
A simple slate that renders slider in single material and modifies the material on value change.
Definition at line 19 of file SAudioMaterialSlider.h.
Member Function Documentation
ApplyNewMaterial()
AUDIOWIDGETS_API void SAudioMaterialSlider::ApplyNewMaterial ()
Apply new material to be used to render the Slate.
References ApplyNewMaterial(), and UE_API.
Referenced by ApplyNewMaterial().
CommitValue()
void SAudioMaterialSlider::CommitValue (float NewValue) private
Commits the specified slider value.
Parameters
NewValue The value to commit.
References CommitValue().
Referenced by CommitValue().
ComputeDesiredSize()
virtual AUDIOWIDGETS_API FVector2D SAudioMaterialSlider::ComputeDesiredSize (float) const override virtual
Overwritten from SWidget.
LeafWidgets should compute their DesiredSize based solely on their visual representation. There is no need to take child widgets into account as LeafWidgets have none by definition. For example, the TextBlock widget simply measures the area necessary to display its text with the given font and font size.
Implements SLeafWidget.
References ComputeDesiredSize(), and UE_API.
Referenced by ComputeDesiredSize().
IsInteractable()
virtual AUDIOWIDGETS_API bool SAudioMaterialSlider::IsInteractable () const override virtual
Returns
Is this widget interactive or not? Defaults to false
Reimplemented from SWidget.
References IsInteractable(), and UE_API.
Referenced by IsInteractable().
IsLocked()
AUDIOWIDGETS_API bool SAudioMaterialSlider::IsLocked () const
Returns
Is the knob interaction locked or not?
References IsLocked(), and UE_API.
Referenced by IsLocked().
OnKeyDown()
virtual AUDIOWIDGETS_API FReply SAudioMaterialSlider::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown(), and UE_API.
Referenced by OnKeyDown().
OnKeyUp()
virtual AUDIOWIDGETS_API FReply SAudioMaterialSlider::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyUp(), and UE_API.
Referenced by OnKeyUp().
OnMouseButtonDown()
virtual AUDIOWIDGETS_API FReply SAudioMaterialSlider::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, OnMouseButtonDown(), and UE_API.
Referenced by OnMouseButtonDown().
OnMouseButtonUp()
virtual AUDIOWIDGETS_API FReply SAudioMaterialSlider::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, OnMouseButtonUp(), and UE_API.
Referenced by OnMouseButtonUp().
OnMouseCaptureLost()
virtual AUDIOWIDGETS_API void SAudioMaterialSlider::OnMouseCaptureLost (const FCaptureLostEvent & CaptureLostEvent) override virtual
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
Reimplemented from SWidget.
References OnMouseCaptureLost(), and UE_API.
Referenced by OnMouseCaptureLost().
OnMouseMove()
virtual AUDIOWIDGETS_API FReply SAudioMaterialSlider::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, OnMouseMove(), and UE_API.
Referenced by OnMouseMove().
OnPaint()
virtual AUDIOWIDGETS_API int32 SAudioMaterialSlider::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
Overwritten from SWidget.
LeafWidgets provide a visual representation of themselves. They do so by adding DrawElement(s) to the OutDrawElements. DrawElements should have their positions set to absolute coordinates in Window space; for this purpose the Slate system provides the AllottedGeometry parameter. AllottedGeometry describes the space allocated for the visualization of this widget.
Whenever possible, LeafWidgets should avoid dealing with layout properties. See TextBlock for an example.
Implements SLeafWidget.
References SWidget::FSlateWindowElementList, OnPaint(), and UE_API.
Referenced by OnPaint().
SetFineTuneSpeed()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetFineTuneSpeed (const float InMouseFineTuneSpeed)
Set the FineTuneSpeed attribute.
References SetFineTuneSpeed(), and UE_API.
Referenced by SetFineTuneSpeed().
SetLocked()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetLocked (const bool bInLocked)
Set the bLocked attribute.
References SetLocked(), and UE_API.
Referenced by SetLocked().
SetMouseUsesStep()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetMouseUsesStep (const bool InUsesStep)
See the bMouseUsesStep attribute.
References SetMouseUsesStep(), and UE_API.
Referenced by SetMouseUsesStep().
SetOrientation()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetOrientation (EOrientation InOrientation)
Set the orientation of the slider.
References SetOrientation(), and UE_API.
Referenced by SetOrientation().
SetStepSize()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetStepSize (const float InStepSize)
Set the StepSize attribute.
References SetStepSize(), and UE_API.
Referenced by SetStepSize().
SetTuneSpeed()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetTuneSpeed (const float InMouseTuneSpeed)
Set the TuneSpeed attribute.
References SetTuneSpeed(), and UE_API.
Referenced by SetTuneSpeed().
SetValue()
AUDIOWIDGETS_API void SAudioMaterialSlider::SetValue (TAttribute< float > InValueAttribute)
Set the Value attribute.
References SetValue(), and UE_API.
Referenced by SetValue().
SLATE_ARGUMENT()
SAudioMaterialSlider::SLATE_ARGUMENT (TWeakObjectPtr< UObject > , Owner)
The owner object.
The slider's orientation.
References Orientation, and Owner.
SLATE_ATTRIBUTE() [1/3]
Orientation FineTuneSpeed SAudioMaterialSlider::SLATE_ATTRIBUTE (bool , IsFocusable)
When true slider will be keyboard focusable, else only mouse-clickable and never keyboard focusable.
Whether the slider is interactive or fixed.
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/3]
Orientation FineTuneSpeed Locked SAudioMaterialSlider::SLATE_ATTRIBUTE (bool , MouseUsesStep)
Moves Slider handle in given steps.
Sets new value if mouse position is greater/less than half the step size. StepSize
References SLATE_ATTRIBUTE(), and StepSize.
SLATE_ATTRIBUTE() [3/3]
Orientation SAudioMaterialSlider::SLATE_ATTRIBUTE (float , TuneSpeed)
The tune speed of the slider handle.
The fine-tune speed of the slider handle
References FineTuneSpeed, SLATE_ATTRIBUTE(), and TuneSpeed.
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_STYLE_ARGUMENT().
SLATE_BEGIN_ARGS()
SAudioMaterialSlider::SLATE_BEGIN_ARGS (SAudioMaterialSlider) inline
Definition at line 22 of file SAudioMaterialSlider.h.
SLATE_END_ARGS()
Orientation FineTuneSpeed Locked StepSize ValueAttribute OnValueCommitted SAudioMaterialSlider::SLATE_END_ARGS () const &
Construct the widget.
References SLATE_END_ARGS(), and UE_API.
Referenced by SLATE_END_ARGS().
SLATE_EVENT()
Orientation FineTuneSpeed Locked StepSize ValueAttribute SAudioMaterialSlider::SLATE_EVENT (FOnFloatValueChanged , OnValueChanged)
Called when the value is changed by the slider.
Called when the value is committed (mouse capture ends)
References OnValueChanged, OnValueCommitted, and SLATE_EVENT().
Referenced by SLATE_EVENT().
SLATE_STYLE_ARGUMENT()
Orientation FineTuneSpeed Locked StepSize SAudioMaterialSlider::SLATE_STYLE_ARGUMENT (FAudioMaterialSliderStyle , AudioMaterialSliderStyle)
The style used to draw the slider.
A value that drives where the slider handle appears. Value is clamped between 0 and 1.
References AudioMaterialSliderStyle, SLATE_ATTRIBUTE(), SLATE_STYLE_ARGUMENT(), and ValueAttribute.
Referenced by SLATE_STYLE_ARGUMENT().
SupportsKeyboardFocus()
virtual AUDIOWIDGETS_API bool SAudioMaterialSlider::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
References SupportsKeyboardFocus(), and UE_API.
Referenced by SupportsKeyboardFocus().
Field Documentation
AudioMaterialSliderStyle
const FAudioMaterialSliderStyle* SAudioMaterialSlider::AudioMaterialSliderStyle = nullptr private
Definition at line 145 of file SAudioMaterialSlider.h.
Referenced by SLATE_STYLE_ARGUMENT().
bIsFineTune
bool SAudioMaterialSlider::bIsFineTune = false private
Definition at line 175 of file SAudioMaterialSlider.h.
bIsFocusable
TAttribute<bool> SAudioMaterialSlider::bIsFocusable private
Holds a flag indicating whether slider will be keyboard focusable.
Definition at line 160 of file SAudioMaterialSlider.h.
bLocked
TAttribute<bool> SAudioMaterialSlider::bLocked private
Definition at line 163 of file SAudioMaterialSlider.h.
bMouseUsesStep
TAttribute<bool> SAudioMaterialSlider::bMouseUsesStep private
Definition at line 166 of file SAudioMaterialSlider.h.
CachedCursor
EMouseCursor::Type SAudioMaterialSlider::CachedCursor = EMouseCursor::None private
Definition at line 184 of file SAudioMaterialSlider.h.
DesiredSizeOverride
TAttribute<TOptional<FVector2D> > SAudioMaterialSlider::DesiredSizeOverride private
Definition at line 136 of file SAudioMaterialSlider.h.
DynamicMaterial
TWeakObjectPtr<UMaterialInstanceDynamic> SAudioMaterialSlider::DynamicMaterial mutable private
Definition at line 148 of file SAudioMaterialSlider.h.
FineTuneSpeed
TAttribute<float> SAudioMaterialSlider::FineTuneSpeed private
Holds the amount to adjust the slider On Mouse move & FineTuning.
Definition at line 157 of file SAudioMaterialSlider.h.
Referenced by SLATE_ATTRIBUTE().
MouseDownStartPosition
FVector2D SAudioMaterialSlider::MouseDownStartPosition private
Definition at line 178 of file SAudioMaterialSlider.h.
MouseDownValue
float SAudioMaterialSlider::MouseDownValue = 0.f private
Definition at line 181 of file SAudioMaterialSlider.h.
OnValueChanged
FOnFloatValueChanged SAudioMaterialSlider::OnValueChanged
Definition at line 119 of file SAudioMaterialSlider.h.
Referenced by SLATE_EVENT().
OnValueCommitted
FOnFloatValueChanged SAudioMaterialSlider::OnValueCommitted
Definition at line 122 of file SAudioMaterialSlider.h.
Referenced by SLATE_EVENT().
Orientation
EOrientation SAudioMaterialSlider::Orientation private
Definition at line 139 of file SAudioMaterialSlider.h.
Referenced by SLATE_ARGUMENT().
Owner
TWeakObjectPtr<UObject> SAudioMaterialSlider::Owner private
Definition at line 142 of file SAudioMaterialSlider.h.
Referenced by SLATE_ARGUMENT().
PixelDelta
int32 SAudioMaterialSlider::PixelDelta = 50 private
Definition at line 172 of file SAudioMaterialSlider.h.
StepSize
TAttribute<float> SAudioMaterialSlider::StepSize private
Holds the amount to adjust the value when steps are used.
Definition at line 169 of file SAudioMaterialSlider.h.
Referenced by SLATE_ATTRIBUTE().
TuneSpeed
TAttribute<float> SAudioMaterialSlider::TuneSpeed private
Holds the amount to adjust the slider On Mouse move.
Definition at line 154 of file SAudioMaterialSlider.h.
Referenced by SLATE_ATTRIBUTE().
ValueAttribute
TAttribute<float> SAudioMaterialSlider::ValueAttribute = 0.f private
Definition at line 151 of file SAudioMaterialSlider.h.
Referenced by SLATE_STYLE_ARGUMENT().
The documentation for this class was generated from the following file:
SAudioMaterialSlider.h