Unreal Engine 5.6 C++ API: FWaveFormatInfo Struct Reference
FWaveFormatInfo Struct Reference
The header of an wave formatted file.
#include "AudioWaveFormatParser.h"
Public Member Functions
FWaveFormatInfo ()
Data Fields
FChunkHeader DataChunkHeader
uint32 DataStartOffset
FFactChunk FactChunk
FChunkHeader FactChunkHeader
FFormatChunk FmtChunk
FChunkHeader FmtChunkHeader
FRiffWaveHeader RiffWaveHeader
FSampleChunk SampleChunk
FChunkHeader SampleChunkHeader
Detailed Description
The header of an wave formatted file.
Definition at line 106 of file AudioWaveFormatParser.h.
Constructor & Destructor Documentation
FWaveFormatInfo()
FWaveFormatInfo::FWaveFormatInfo () inline
Definition at line 118 of file AudioWaveFormatParser.h.
References FWaveFormatInfo(), and FMemory::Memzero().
Referenced by FWaveFormatInfo().
Field Documentation
DataChunkHeader
FChunkHeader FWaveFormatInfo::DataChunkHeader
Definition at line 115 of file AudioWaveFormatParser.h.
DataStartOffset
uint32 FWaveFormatInfo::DataStartOffset
Definition at line 116 of file AudioWaveFormatParser.h.
FactChunk
FFactChunk FWaveFormatInfo::FactChunk
Definition at line 112 of file AudioWaveFormatParser.h.
FactChunkHeader
FChunkHeader FWaveFormatInfo::FactChunkHeader
Definition at line 111 of file AudioWaveFormatParser.h.
FmtChunk
FFormatChunk FWaveFormatInfo::FmtChunk
Definition at line 110 of file AudioWaveFormatParser.h.
FmtChunkHeader
FChunkHeader FWaveFormatInfo::FmtChunkHeader
Definition at line 109 of file AudioWaveFormatParser.h.
RiffWaveHeader
FRiffWaveHeader FWaveFormatInfo::RiffWaveHeader
Definition at line 108 of file AudioWaveFormatParser.h.
SampleChunk
FSampleChunk FWaveFormatInfo::SampleChunk
Definition at line 114 of file AudioWaveFormatParser.h.
SampleChunkHeader
FChunkHeader FWaveFormatInfo::SampleChunkHeader
Definition at line 113 of file AudioWaveFormatParser.h.
The documentation for this struct was generated from the following file:
AudioWaveFormatParser.h