Unreal Engine 5.6 C++ API: UE::Geometry::TTransformSRT3< RealType > Class Template Reference
UE::Geometry::TTransformSRT3< RealType > Class Template Reference
TTransformSRT3 is a variant of the standard UE FTransform/TTransform that uses the UE::Geometry::TQuaternion instead of the UE::Math::TQuat.
#include "TransformTypes.h"
Public Member Functions
TTransformSRT3 ()
TTransformSRT3 (const FTransform3d &Transform)
TTransformSRT3 (const FTransform3f &Transform)
TTransformSRT3 (const TQuaternion< RealType > &RotationIn, const UE::Math::TVector< RealType > &TranslationIn)
TTransformSRT3 (const TQuaternion< RealType > &RotationIn, const UE::Math::TVector< RealType > &TranslationIn, const UE::Math::TVector< RealType > &ScaleIn)
TTransformSRT3 (const UE::Math::TVector< RealType > &TranslationIn)
bool CanRepresentInverse (RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
Reports wheth the inverse is representable with a single TTransformSRT3.
void ClampMinimumScale (RealType MinimumScale=TMathUtil< RealType >::ZeroTolerance)
Clamp all scale components to a minimum value.
RealType GetDeterminant () const
const TQuaternion< RealType > & GetRotation () const
FRotator GetRotator () const
const TVector< RealType > & GetScale () const
const TVector< RealType > & GetScale3D () const
const TVector< RealType > & GetTranslation () const
bool HasNonUniformScale (RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
template<typename RealType2>
TVector< RealType2 > InverseTransformNormal (const UE::Math::TVector< RealType2 > &Normal) const
Surface Normals are special, their inverse transform is InverseRotate(Normalize(Scale * Normal)))
template<typename RealType2>
TVector< RealType2 > InverseTransformPosition (const UE::Math::TVector< RealType2 > &P) const
UE::Math::TRay< RealType > InverseTransformRay (const UE::Math::TRay< RealType > &Ray) const
template<typename RealType2>
TVector< RealType2 > InverseTransformVector (const UE::Math::TVector< RealType2 > &V) const
template<typename RealType2>
TVector< RealType2 > InverseTransformVectorNoScale (const UE::Math::TVector< RealType2 > &V) const
TTransformSRT3< RealType > InverseUnsafe (RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
Attempts to return an inverse, but will give an incorrect result if the transform has both non-uniform scaling and rotation, because TTransformSRT3<RealType> cannot represent the true inverse in that case.
operator FTransform3d () const
operator FTransform3f () const
void SetRotation (const TQuaternion< RealType > &RotationIn)
Set Rotation portion of Transform.
void SetScale (const UE::Math::TVector< RealType > &ScaleIn)
set Scale portion of transform
void SetTranslation (const UE::Math::TVector< RealType > &TranslationIn)
set Translation portion of transform
template<typename RealType2>
TVector< RealType2 > TransformNormal (const UE::Math::TVector< RealType2 > &Normal) const
Surface Normals are special, their transform is Rotate(Normalize((1/Scale) * Normal))).
template<typename RealType2>
TVector< RealType2 > TransformPosition (const TVector< RealType2 > &P) const
UE::Math::TRay< RealType > TransformRay (const UE::Math::TRay< RealType > &Ray) const
template<typename RealType2>
TVector< RealType2 > TransformVector (const UE::Math::TVector< RealType2 > &V) const
template<typename RealType2>
TVector< RealType2 > TransformVectorNoScale (const UE::Math::TVector< RealType2 > &V) const
Static Public Member Functions
static TVector< RealType > GetSafeScaleReciprocal (const TVector< RealType > &InScale, RealType Tolerance=TMathUtil< RealType >::ZeroTolerance)
static TTransformSRT3< RealType > Identity ()
Protected Attributes
TQuaternion< RealType > Rotation
TVector< RealType > Scale3D
TVector< RealType > Translation
Detailed Description
template<typename RealType>
class UE::Geometry::TTransformSRT3< RealType >
TTransformSRT3 is a variant of the standard UE FTransform/TTransform that uses the UE::Geometry::TQuaternion instead of the UE::Math::TQuat.
Transform order is Scale, then Rotate, then Translate. So mathematically (T * R * S) * v , assuming traditional matrix-vector multiplication order (note that the UE::Math library uses the opposite vector*Matrix ordering for TMatrix!)
Implicit constructors/casts are defined to/from FTransform3d and FTransform3f. This will likely be revised in future so that conversions that lose precision are explicit.
Definition at line 29 of file TransformTypes.h.
Constructor & Destructor Documentation
TTransformSRT3() [1/6]
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::TTransformSRT3 () inline
Definition at line 38 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::Identity(), and UE::Geometry::TTransformSRT3< float >::InverseUnsafe().
TTransformSRT3() [2/6]
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::TTransformSRT3 (const TQuaternion< RealType > & RotationIn, const UE::Math::TVector< RealType > & TranslationIn, const UE::Math::TVector< RealType > & ScaleIn) inline
Definition at line 45 of file TransformTypes.h.
TTransformSRT3() [3/6]
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::TTransformSRT3 (const TQuaternion< RealType > & RotationIn, const UE::Math::TVector< RealType > & TranslationIn) inline explicit
Definition at line 52 of file TransformTypes.h.
TTransformSRT3() [4/6]
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::TTransformSRT3 (const UE::Math::TVector< RealType > & TranslationIn) inline explicit
Definition at line 59 of file TransformTypes.h.
TTransformSRT3() [5/6]
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::TTransformSRT3 (const FTransform3f & Transform) inline
Definition at line 66 of file TransformTypes.h.
TTransformSRT3() [6/6]
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::TTransformSRT3 (const FTransform3d & Transform) inline
Definition at line 73 of file TransformTypes.h.
Member Function Documentation
CanRepresentInverse()
template<typename RealType> bool UE::Geometry::TTransformSRT3< RealType >::CanRepresentInverse (RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const inline
Reports wheth the inverse is representable with a single TTransformSRT3.
(Ignores zeros in scale.)
Definition at line 199 of file TransformTypes.h.
ClampMinimumScale()
template<typename RealType> void UE::Geometry::TTransformSRT3< RealType >::ClampMinimumScale (RealType MinimumScale = TMathUtil<RealType>::ZeroTolerance) inline
Clamp all scale components to a minimum value.
Sign of scale components is preserved. This is used to remove uninvertible zero/near-zero scaling.
Definition at line 373 of file TransformTypes.h.
GetDeterminant()
template<typename RealType> RealType UE::Geometry::TTransformSRT3< RealType >::GetDeterminant () const inline
Returns
determinant of scale matrix
Definition at line 171 of file TransformTypes.h.
GetRotation()
template<typename RealType> const TQuaternion< RealType > & UE::Geometry::TTransformSRT3< RealType >::GetRotation () const inline
Returns
Rotation portion of Transform, as Quaternion
Definition at line 107 of file TransformTypes.h.
Referenced by UE::Geometry::TFrame3< float >::Transform().
GetRotator()
template<typename RealType> FRotator UE::Geometry::TTransformSRT3< RealType >::GetRotator () const inline
Returns
Rotation portion of Transform, as FRotator
Definition at line 115 of file TransformTypes.h.
GetSafeScaleReciprocal()
template<typename RealType> TVector< RealType > UE::Geometry::TTransformSRT3< RealType >::GetSafeScaleReciprocal (const TVector< RealType > & InScale, RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) inline static
Definition at line 388 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSequence3< float >::AppendInverse(), UE::Geometry::TTransformSRT3< float >::InverseTransformPosition(), UE::Geometry::TTransformSRT3< float >::InverseTransformVector(), and UE::Geometry::TTransformSRT3< float >::InverseUnsafe().
GetScale()
template<typename RealType> const TVector< RealType > & UE::Geometry::TTransformSRT3< RealType >::GetScale () const inline
Returns
Scale portion of transform
Definition at line 147 of file TransformTypes.h.
GetScale3D()
template<typename RealType> const TVector< RealType > & UE::Geometry::TTransformSRT3< RealType >::GetScale3D () const inline
Returns
Scale portion of transform
Definition at line 155 of file TransformTypes.h.
GetTranslation()
template<typename RealType> const TVector< RealType > & UE::Geometry::TTransformSRT3< RealType >::GetTranslation () const inline
Returns
Translation portion of transform
Definition at line 131 of file TransformTypes.h.
HasNonUniformScale()
template<typename RealType> bool UE::Geometry::TTransformSRT3< RealType >::HasNonUniformScale (RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const inline
Returns
true if scale is nonuniform, within tolerance
Definition at line 179 of file TransformTypes.h.
Identity()
template<typename RealType> TTransformSRT3< RealType > UE::Geometry::TTransformSRT3< RealType >::Identity () inline static
Returns
identity transform, IE no rotation, zero origin, unit scale
Definition at line 83 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSequence3< float >::AppendInverse().
InverseTransformNormal()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::InverseTransformNormal (const UE::Math::TVector< RealType2 > & Normal) const inline
Surface Normals are special, their inverse transform is InverseRotate(Normalize(Scale * Normal)))
Returns
input surface normal with inverse transform applied.
Definition at line 341 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::InverseTransformNormal().
InverseTransformPosition()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::InverseTransformPosition (const UE::Math::TVector< RealType2 > & P) const inline
Returns
input vector with inverse-QST transformation applied, ie QSTinv(P) = InverseScale(InverseRotate(P - Translate))
Definition at line 290 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::InverseTransformPosition(), and UE::Geometry::TTransformSRT3< float >::InverseTransformRay().
InverseTransformRay()
template<typename RealType> UE::Math::TRay< RealType > UE::Geometry::TTransformSRT3< RealType >::InverseTransformRay (const UE::Math::TRay< RealType > & Ray) const inline
Definition at line 362 of file TransformTypes.h.
InverseTransformVector()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::InverseTransformVector (const UE::Math::TVector< RealType2 > & V) const inline
Returns
input vector with inverse-QS transformation applied, ie QSinv(V) = InverseScale(InverseRotate(V))
Definition at line 306 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::InverseTransformRay(), and UE::Geometry::TTransformSRT3< float >::InverseTransformVector().
InverseTransformVectorNoScale()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::InverseTransformVectorNoScale (const UE::Math::TVector< RealType2 > & V) const inline
Returns
input vector with inverse-Q transformation applied, ie Qinv(V) = InverseRotate(V)
Definition at line 323 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::InverseTransformNormal(), and UE::Geometry::TTransformSRT3< float >::InverseTransformVectorNoScale().
InverseUnsafe()
template<typename RealType> TTransformSRT3< RealType > UE::Geometry::TTransformSRT3< RealType >::InverseUnsafe (RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const inline
Attempts to return an inverse, but will give an incorrect result if the transform has both non-uniform scaling and rotation, because TTransformSRT3<RealType> cannot represent the true inverse in that case.
Definition at line 190 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSequence3< float >::AppendInverse().
operator FTransform3d()
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::operator FTransform3d () const inline
Returns
this transform converted to FTransform3d
Definition at line 99 of file TransformTypes.h.
operator FTransform3f()
template<typename RealType> UE::Geometry::TTransformSRT3< RealType >::operator FTransform3f () const inline
Returns
this transform converted to FTransform
Definition at line 91 of file TransformTypes.h.
SetRotation()
template<typename RealType> void UE::Geometry::TTransformSRT3< RealType >::SetRotation (const TQuaternion< RealType > & RotationIn) inline
Set Rotation portion of Transform.
Definition at line 123 of file TransformTypes.h.
SetScale()
template<typename RealType> void UE::Geometry::TTransformSRT3< RealType >::SetScale (const UE::Math::TVector< RealType > & ScaleIn) inline
set Scale portion of transform
Definition at line 163 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSequence3< float >::AppendInverse().
SetTranslation()
template<typename RealType> void UE::Geometry::TTransformSRT3< RealType >::SetTranslation (const UE::Math::TVector< RealType > & TranslationIn) inline
set Translation portion of transform
Definition at line 139 of file TransformTypes.h.
TransformNormal()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::TransformNormal (const UE::Math::TVector< RealType2 > & Normal) const inline
Surface Normals are special, their transform is Rotate(Normalize((1/Scale) * Normal))).
However 1/Scale requires special handling in case any component is near-zero.
Returns
input surface normal with transform applied.
Definition at line 269 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::TransformNormal().
TransformPosition()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::TransformPosition (const TVector< RealType2 > & P) const inline
Returns
input point with QST transformation applied, ie QST(P) = Rotate(Scale*P) + Translate
Definition at line 217 of file TransformTypes.h.
Referenced by UE::Geometry::TFrame3< float >::Transform(), UE::Geometry::TTransformSRT3< float >::TransformPosition(), and UE::Geometry::TTransformSRT3< float >::TransformRay().
TransformRay()
template<typename RealType> UE::Math::TRay< RealType > UE::Geometry::TTransformSRT3< RealType >::TransformRay (const UE::Math::TRay< RealType > & Ray) const inline
Definition at line 354 of file TransformTypes.h.
TransformVector()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::TransformVector (const UE::Math::TVector< RealType2 > & V) const inline
Returns
input vector with QS transformation applied, ie QS(V) = Rotate(Scale*V)
Definition at line 235 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::TransformRay(), and UE::Geometry::TTransformSRT3< float >::TransformVector().
TransformVectorNoScale()
template<typename RealType> template<typename RealType2> TVector< RealType2 > UE::Geometry::TTransformSRT3< RealType >::TransformVectorNoScale (const UE::Math::TVector< RealType2 > & V) const inline
Returns
input vector with Q transformation applied, ie Q(V) = Rotate(V)
Definition at line 251 of file TransformTypes.h.
Referenced by UE::Geometry::TTransformSRT3< float >::TransformNormal(), and UE::Geometry::TTransformSRT3< float >::TransformVectorNoScale().
Field Documentation
Rotation
template<typename RealType> TQuaternion<RealType> UE::Geometry::TTransformSRT3< RealType >::Rotation protected
Definition at line 32 of file TransformTypes.h.
Scale3D
template<typename RealType> TVector<RealType> UE::Geometry::TTransformSRT3< RealType >::Scale3D protected
Definition at line 34 of file TransformTypes.h.
Translation
template<typename RealType> TVector<RealType> UE::Geometry::TTransformSRT3< RealType >::Translation protected
Definition at line 33 of file TransformTypes.h.
The documentation for this class was generated from the following file:
TransformTypes.h