Unreal Engine 5.6 C++ API: UE::Geometry::FilteredIterator< ValueType, IteratorT > Class Template Reference
UE::Geometry::FilteredIterator< ValueType, IteratorT > Class Template Reference
Wrapper around an existing iterator that skips over values for which the filter_func returns false.
#include "IteratorUtil.h"
Public Member Functions
FilteredIterator ()
FilteredIterator (const IteratorT &CurItr, const IteratorT &EndItr, const FilterFunctionT &FilterFuncIn)
void GotoNextElement ()
bool operator!= (const FilteredIterator &Other) const
ValueType operator* () const
const FilteredIterator & operator++ ()
bool operator== (const FilteredIterator &Other) const
Data Fields
IteratorT Cur
IteratorT End
FilterFunctionT FilterFunc
Private Types
using FilterFunctionT = TFunction<bool(ValueType)>
Detailed Description
template<typename ValueType, typename IteratorT>
class UE::Geometry::FilteredIterator< ValueType, IteratorT >
Wrapper around an existing iterator that skips over values for which the filter_func returns false.
Definition at line 71 of file IteratorUtil.h.
Member Typedef Documentation
FilterFunctionT
template<typename ValueType, typename IteratorT> using UE::Geometry::FilteredIterator< ValueType, IteratorT >::FilterFunctionT = TFunction<bool(ValueType)> private
Definition at line 73 of file IteratorUtil.h.
Constructor & Destructor Documentation
FilteredIterator() [1/2]
template<typename ValueType, typename IteratorT> UE::Geometry::FilteredIterator< ValueType, IteratorT >::FilteredIterator () inline
Definition at line 76 of file IteratorUtil.h.
Referenced by operator!=(), operator++(), and operator==().
FilteredIterator() [2/2]
template<typename ValueType, typename IteratorT> UE::Geometry::FilteredIterator< ValueType, IteratorT >::FilteredIterator (const IteratorT & CurItr, const IteratorT & EndItr, const FilterFunctionT & FilterFuncIn) inline
Definition at line 105 of file IteratorUtil.h.
References Cur, End, FilterFunc, and GotoNextElement().
Member Function Documentation
GotoNextElement()
template<typename ValueType, typename IteratorT> void UE::Geometry::FilteredIterator< ValueType, IteratorT >::GotoNextElement () inline
Definition at line 98 of file IteratorUtil.h.
References Cur, End, and FilterFunc.
Referenced by FilteredIterator(), and operator++().
operator!=()
template<typename ValueType, typename IteratorT> bool UE::Geometry::FilteredIterator< ValueType, IteratorT >::operator!= (const FilteredIterator< ValueType, IteratorT > & Other) const inline
Definition at line 82 of file IteratorUtil.h.
References FilteredIterator(), Cur, and Other.
operator*()
template<typename ValueType, typename IteratorT> ValueType UE::Geometry::FilteredIterator< ValueType, IteratorT >::operator* () const inline
Definition at line 87 of file IteratorUtil.h.
References Cur.
operator++()
template<typename ValueType, typename IteratorT> const FilteredIterator & UE::Geometry::FilteredIterator< ValueType, IteratorT >::operator++ () inline
Definition at line 92 of file IteratorUtil.h.
References FilteredIterator(), and GotoNextElement().
operator==()
template<typename ValueType, typename IteratorT> bool UE::Geometry::FilteredIterator< ValueType, IteratorT >::operator== (const FilteredIterator< ValueType, IteratorT > & Other) const inline
Definition at line 78 of file IteratorUtil.h.
References FilteredIterator(), Cur, and Other.
Field Documentation
Cur
template<typename ValueType, typename IteratorT> IteratorT UE::Geometry::FilteredIterator< ValueType, IteratorT >::Cur
Definition at line 116 of file IteratorUtil.h.
Referenced by FilteredIterator(), GotoNextElement(), operator!=(), operator*(), and operator==().
End
template<typename ValueType, typename IteratorT> IteratorT UE::Geometry::FilteredIterator< ValueType, IteratorT >::End
Definition at line 117 of file IteratorUtil.h.
Referenced by FilteredIterator(), and GotoNextElement().
FilterFunc
template<typename ValueType, typename IteratorT> FilterFunctionT UE::Geometry::FilteredIterator< ValueType, IteratorT >::FilterFunc
Definition at line 118 of file IteratorUtil.h.
Referenced by FilteredIterator(), and GotoNextElement().
The documentation for this class was generated from the following file:
IteratorUtil.h