Unreal Engine 5.6 C++ API: DynamicRenderScaling::TMap< Type > Class Template Reference
DynamicRenderScaling::TMap< Type > Class Template Reference
#include "DynamicRenderScaling.h"
Data Structures
struct FItem
Public Member Functions
TMap ()
TMap (const TMap< Type > &Map)=default
TMap (const Type &Value)
~TMap ()=default
Type & operator[] (const FBudget &Budget)
const Type & operator[] (const FBudget &Budget) const
Type & operator[] (const int32 BudgetId)
const Type & operator[] (const int32 BudgetId) const
void SetAll (const Type &Value)
Static Public Attributes
static constexpr int32 kInlineAllocatedBudgets = 16
Private Attributes
TArray< FItem, TInlineAllocator< kInlineAllocatedBudgets > > Array
Detailed Description
template<typename Type>
class DynamicRenderScaling::TMap< Type >
Definition at line 171 of file DynamicRenderScaling.h.
Constructor & Destructor Documentation
TMap() [1/3]
template<typename Type> DynamicRenderScaling::TMap< Type >::TMap () inline
Definition at line 176 of file DynamicRenderScaling.h.
References Array, DynamicRenderScaling::FBudget::GetGlobalList(), and DynamicRenderScaling::FBudget::GetGlobalListSize().
Referenced by TMap(), and TMap().
TMap() [2/3]
template<typename Type> DynamicRenderScaling::TMap< Type >::TMap (const Type & Value) inline
Definition at line 187 of file DynamicRenderScaling.h.
References TMap(), SetAll(), and Value.
TMap() [3/3]
template<typename Type> DynamicRenderScaling::TMap< Type >::TMap (const TMap< Type > & Map) default
References TMap(), and Map.
~TMap()
template<typename Type> DynamicRenderScaling::TMap< Type >::~TMap () default
Member Function Documentation
operator[]() [1/4]
template<typename Type> Type & DynamicRenderScaling::TMap< Type >::operator[] (const FBudget & Budget) inline
Definition at line 211 of file DynamicRenderScaling.h.
References Array, DynamicRenderScaling::FBudget::BudgetId, check, and DynamicRenderScaling::FBudget::GetGlobalListSize().
operator[]() [2/4]
template<typename Type> const Type & DynamicRenderScaling::TMap< Type >::operator[] (const FBudget & Budget) const inline
Definition at line 205 of file DynamicRenderScaling.h.
References Array, DynamicRenderScaling::FBudget::BudgetId, check, and DynamicRenderScaling::FBudget::GetGlobalListSize().
operator[]() [3/4]
template<typename Type> Type & DynamicRenderScaling::TMap< Type >::operator[] (const int32 BudgetId) inline
Definition at line 223 of file DynamicRenderScaling.h.
References Array, check, and DynamicRenderScaling::FBudget::GetGlobalListSize().
operator[]() [4/4]
template<typename Type> const Type & DynamicRenderScaling::TMap< Type >::operator[] (const int32 BudgetId) const inline
Definition at line 217 of file DynamicRenderScaling.h.
References Array, check, and DynamicRenderScaling::FBudget::GetGlobalListSize().
SetAll()
template<typename Type> void DynamicRenderScaling::TMap< Type >::SetAll (const Type & Value) inline
Definition at line 196 of file DynamicRenderScaling.h.
References Array, DynamicRenderScaling::FBudget::GetGlobalListSize(), and Value.
Referenced by TMap().
Field Documentation
Array
template<typename Type> TArray<FItem, TInlineAllocator<kInlineAllocatedBudgets> > DynamicRenderScaling::TMap< Type >::Array private
Definition at line 237 of file DynamicRenderScaling.h.
Referenced by TMap(), operator[](), operator[](), operator[](), operator[](), and SetAll().
kInlineAllocatedBudgets
template<typename Type> int32 DynamicRenderScaling::TMap< Type >::kInlineAllocatedBudgets = 16 static constexpr
Definition at line 174 of file DynamicRenderScaling.h.
The documentation for this class was generated from the following file:
DynamicRenderScaling.h