Unreal Engine 5.6 C++ API: FResourceArrayUploadInterface Struct Reference
FResourceArrayUploadInterface Struct Reference abstract
An element type independent interface for uploading an array of resource data.
#include "ResourceArray.h"
Public Member Functions
virtual ~FResourceArrayUploadInterface ()
virtual void Discard ()=0
Called on non-UMA systems after the RHI has copied the resource data, and no longer needs the CPU's copy.
virtual const void * GetResourceData () const =0
Returns a pointer to the resource data.
virtual uint32 GetResourceDataSize () const =0
Returns size of resource data allocation.
template<typename TElement>
TConstArrayView< TElement > GetResourceDataView () const
Detailed Description
An element type independent interface for uploading an array of resource data.
Definition at line 9 of file ResourceArray.h.
Constructor & Destructor Documentation
~FResourceArrayUploadInterface()
virtual FResourceArrayUploadInterface::~FResourceArrayUploadInterface () inline virtual
Definition at line 11 of file ResourceArray.h.
Member Function Documentation
Discard()
virtual void FResourceArrayUploadInterface::Discard () pure virtual
Called on non-UMA systems after the RHI has copied the resource data, and no longer needs the CPU's copy.
Implemented in FResourceArrayUploadArrayView, TResourceArray< ElementType, Alignment >, TResourceArray< FColor >, TResourceArray< FIndexLengthPair, VERTEXBUFFER_ALIGNMENT >, TResourceArray< float >, TResourceArray< FSimpleElementVertex >, TResourceArray< INDEX_TYPE, INDEXBUFFER_ALIGNMENT >, TResourceArray< int32 >, TResourceArray< UE::Math::TIntVector3< int32 > >, TResourceArray< uint32 >, TResourceArray< uint32, VERTEXBUFFER_ALIGNMENT >, TResourceArray< uint8 >, TResourceArray< uint8, INDEXBUFFER_ALIGNMENT >, and TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >.
GetResourceData()
virtual const void * FResourceArrayUploadInterface::GetResourceData () const nodiscard pure virtual
Returns a pointer to the resource data.
Implemented in FResourceArrayUploadArrayView, TResourceArray< ElementType, Alignment >, TResourceArray< FColor >, TResourceArray< FIndexLengthPair, VERTEXBUFFER_ALIGNMENT >, TResourceArray< float >, TResourceArray< FSimpleElementVertex >, TResourceArray< INDEX_TYPE, INDEXBUFFER_ALIGNMENT >, TResourceArray< int32 >, TResourceArray< UE::Math::TIntVector3< int32 > >, TResourceArray< uint32 >, TResourceArray< uint32, VERTEXBUFFER_ALIGNMENT >, TResourceArray< uint8 >, TResourceArray< uint8, INDEXBUFFER_ALIGNMENT >, and TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >.
Referenced by GetResourceDataView().
GetResourceDataSize()
virtual uint32 FResourceArrayUploadInterface::GetResourceDataSize () const nodiscard pure virtual
Returns size of resource data allocation.
Implemented in FResourceArrayUploadArrayView, TResourceArray< ElementType, Alignment >, TResourceArray< FColor >, TResourceArray< FIndexLengthPair, VERTEXBUFFER_ALIGNMENT >, TResourceArray< float >, TResourceArray< FSimpleElementVertex >, TResourceArray< INDEX_TYPE, INDEXBUFFER_ALIGNMENT >, TResourceArray< int32 >, TResourceArray< UE::Math::TIntVector3< int32 > >, TResourceArray< uint32 >, TResourceArray< uint32, VERTEXBUFFER_ALIGNMENT >, TResourceArray< uint8 >, TResourceArray< uint8, INDEXBUFFER_ALIGNMENT >, and TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >.
Referenced by GetResourceDataView(), and FDuplicatedVerticesBuffer::InitRHI().
GetResourceDataView()
template<typename TElement> TConstArrayView< TElement > FResourceArrayUploadInterface::GetResourceDataView () const inline
Definition at line 20 of file ResourceArray.h.
References GetResourceData(), and GetResourceDataSize().
The documentation for this struct was generated from the following file:
ResourceArray.h