Unreal Engine 5.6 C++ API: TWidgetFactory< WidgetType > Class Template Reference
TWidgetFactory< WidgetType > Class Template Reference
#include "WidgetFactory.h"
Public Types
typedef TFunctionRef< TSharedPtr< SObjectWidget >(UUserWidget *, TSharedRef< SWidget >)> ConstructMethodType
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Public Member Functions
TWidgetFactory ()=default
TWidgetFactory (TWidgetFactory &&Other)
TWidgetFactory (UWidget &InOwningWidget, TSubclassOf< WidgetType > InWidgetClass, TFunction< UObject *(void)> &&InOuterGetter, bool InTrackActiveWidgets=false)
virtual ~TWidgetFactory ()
WidgetType * Acquire ()
Method to get a widget from this factory, can sometimes call CreateWidget.
void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
const TArray< WidgetType * > & GetActiveWidgets () const
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
bool IsInitialized () const
TWidgetFactory & operator= (TWidgetFactory &&Other)
void PreConstruct (int32 Num)
void Release (WidgetType *Widget)
Return a widget to the pool, allowing it to be reused in the future.
void Reset (const bool bReleaseSlate=false, const bool bMoveToInactive=false)
template<class DerivedWidgetType = SObjectWidget, class = typename TEnableIf<TIsDerivedFrom<DerivedWidgetType, ITableRow>::IsDerived, DerivedWidgetType>::Type>
TSharedRef< DerivedWidgetType > TakeAndCacheRow (WidgetType *Key, const TSharedRef< STableViewBase > &DestinationTable)
Convenience function for SObjectTableRows takes and caches the widget, then creates the object row around it.
template<class DerivedWidgetType = SObjectWidget, class = typename TEnableIf<TIsDerivedFrom<DerivedWidgetType, SObjectWidget>::IsDerived, DerivedWidgetType>::Type>
TSharedRef< DerivedWidgetType > TakeAndCacheWidget (WidgetType *Key, ConstructMethodType ConstructMethod)
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Private Member Functions
FORCEINLINE UGameInstance * OwningObjectAsGameInstance () const
FORCEINLINE APlayerController * OwningObjectAsPlayerController () const
FORCEINLINE UWorld * OwningObjectAsWorld () const
Private Attributes
TArray< TObjectPtr< WidgetType > > ActiveWidgets
bool bTrackActiveWidgets
TMap< WidgetType *, TSharedPtr< SWidget > > CachedSlateWidgets
TArray< TObjectPtr< WidgetType > > InactiveWidgets
TFunction< UObject *(void)> OuterGetter
TWeakObjectPtr< UWidget > OwningWidget
TSubclassOf< WidgetType > WidgetClass
Additional Inherited Members
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
template<class WidgetType>
class TWidgetFactory< WidgetType >
Definition at line 14 of file WidgetFactory.h.
Member Typedef Documentation
ConstructMethodType
template<class WidgetType> typedef TFunctionRef<TSharedPtr<SObjectWidget>(UUserWidget*, TSharedRef<SWidget>)> TWidgetFactory< WidgetType >::ConstructMethodType
Definition at line 23 of file WidgetFactory.h.
Constructor & Destructor Documentation
TWidgetFactory() [1/3]
template<class WidgetType> TWidgetFactory< WidgetType >::TWidgetFactory () default
TWidgetFactory() [2/3]
template<class WidgetType> TWidgetFactory< WidgetType >::TWidgetFactory (UWidget & InOwningWidget, TSubclassOf< WidgetType > InWidgetClass, TFunction< UObject *(void)> && InOuterGetter, bool InTrackActiveWidgets = false) inline
Definition at line 26 of file WidgetFactory.h.
TWidgetFactory() [3/3]
template<class WidgetType> TWidgetFactory< WidgetType >::TWidgetFactory (TWidgetFactory< WidgetType > && Other) inline
Definition at line 35 of file WidgetFactory.h.
~TWidgetFactory()
template<class WidgetType> virtual TWidgetFactory< WidgetType >::~TWidgetFactory () inline virtual
Definition at line 51 of file WidgetFactory.h.
Member Function Documentation
Acquire()
template<class WidgetType> WidgetType * TWidgetFactory< WidgetType >::Acquire () inline
Method to get a widget from this factory, can sometimes call CreateWidget.
Definition at line 122 of file WidgetFactory.h.
AddReferencedObjects()
template<class WidgetType> void TWidgetFactory< WidgetType >::AddReferencedObjects (FReferenceCollector & Collector) inline override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Definition at line 227 of file WidgetFactory.h.
GetActiveWidgets()
template<class WidgetType> const TArray< WidgetType * > & TWidgetFactory< WidgetType >::GetActiveWidgets () const inline
Definition at line 84 of file WidgetFactory.h.
GetReferencerName()
template<class WidgetType> virtual FString TWidgetFactory< WidgetType >::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 235 of file WidgetFactory.h.
IsInitialized()
template<class WidgetType> bool TWidgetFactory< WidgetType >::IsInitialized () const inline
Definition at line 79 of file WidgetFactory.h.
operator=()
template<class WidgetType> TWidgetFactory & TWidgetFactory< WidgetType >::operator= (TWidgetFactory< WidgetType > && Other) inline
Definition at line 58 of file WidgetFactory.h.
OwningObjectAsGameInstance()
template<class WidgetType> FORCEINLINE UGameInstance * TWidgetFactory< WidgetType >::OwningObjectAsGameInstance () const inline private
Definition at line 18 of file WidgetFactory.h.
Referenced by TWidgetFactory< UUserWidget >::Acquire(), and TWidgetFactory< UUserWidget >::PreConstruct().
OwningObjectAsPlayerController()
template<class WidgetType> FORCEINLINE APlayerController * TWidgetFactory< WidgetType >::OwningObjectAsPlayerController () const inline private
Definition at line 20 of file WidgetFactory.h.
Referenced by TWidgetFactory< UUserWidget >::Acquire(), and TWidgetFactory< UUserWidget >::PreConstruct().
OwningObjectAsWorld()
template<class WidgetType> FORCEINLINE UWorld * TWidgetFactory< WidgetType >::OwningObjectAsWorld () const inline private
Definition at line 19 of file WidgetFactory.h.
Referenced by TWidgetFactory< UUserWidget >::Acquire(), and TWidgetFactory< UUserWidget >::PreConstruct().
PreConstruct()
template<class WidgetType> void TWidgetFactory< WidgetType >::PreConstruct (int32 Num) inline
Definition at line 86 of file WidgetFactory.h.
Release()
template<class WidgetType> void TWidgetFactory< WidgetType >::Release (WidgetType * Widget) inline
Return a widget to the pool, allowing it to be reused in the future.
Definition at line 172 of file WidgetFactory.h.
Reset()
template<class WidgetType> void TWidgetFactory< WidgetType >::Reset (const bool bReleaseSlate = false, const bool bMoveToInactive = false) inline
Definition at line 194 of file WidgetFactory.h.
TakeAndCacheRow()
template<class WidgetType> template<class DerivedWidgetType = SObjectWidget, class = typename TEnableIf<TIsDerivedFrom<DerivedWidgetType, ITableRow>::IsDerived, DerivedWidgetType>::Type> TSharedRef< DerivedWidgetType > TWidgetFactory< WidgetType >::TakeAndCacheRow (WidgetType * Key, const TSharedRef< STableViewBase > & DestinationTable) inline
Convenience function for SObjectTableRows takes and caches the widget, then creates the object row around it.
Definition at line 256 of file WidgetFactory.h.
TakeAndCacheWidget()
template<class WidgetType> template<class DerivedWidgetType = SObjectWidget, class = typename TEnableIf<TIsDerivedFrom<DerivedWidgetType, SObjectWidget>::IsDerived, DerivedWidgetType>::Type> TSharedRef< DerivedWidgetType > TWidgetFactory< WidgetType >::TakeAndCacheWidget (WidgetType * Key, ConstructMethodType ConstructMethod) inline
Definition at line 242 of file WidgetFactory.h.
Field Documentation
ActiveWidgets
template<class WidgetType> TArray<TObjectPtr<WidgetType> > TWidgetFactory< WidgetType >::ActiveWidgets private
Definition at line 275 of file WidgetFactory.h.
bTrackActiveWidgets
template<class WidgetType> bool TWidgetFactory< WidgetType >::bTrackActiveWidgets private
Definition at line 281 of file WidgetFactory.h.
CachedSlateWidgets
template<class WidgetType> TMap<WidgetType*, TSharedPtr<SWidget> > TWidgetFactory< WidgetType >::CachedSlateWidgets private
Definition at line 277 of file WidgetFactory.h.
InactiveWidgets
template<class WidgetType> TArray<TObjectPtr<WidgetType> > TWidgetFactory< WidgetType >::InactiveWidgets private
Definition at line 276 of file WidgetFactory.h.
OuterGetter
template<class WidgetType> TFunction<UObject*(void)> TWidgetFactory< WidgetType >::OuterGetter private
Definition at line 280 of file WidgetFactory.h.
Referenced by TWidgetFactory< UUserWidget >::OwningObjectAsGameInstance(), TWidgetFactory< UUserWidget >::OwningObjectAsPlayerController(), and TWidgetFactory< UUserWidget >::OwningObjectAsWorld().
OwningWidget
template<class WidgetType> TWeakObjectPtr<UWidget> TWidgetFactory< WidgetType >::OwningWidget private
Definition at line 278 of file WidgetFactory.h.
WidgetClass
template<class WidgetType> TSubclassOf<WidgetType> TWidgetFactory< WidgetType >::WidgetClass private
Definition at line 279 of file WidgetFactory.h.
The documentation for this class was generated from the following file:
WidgetFactory.h