Unreal Engine 5.6 C++ API: LODActor.h File Reference
LODActor.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "HAL/IConsoleManager.h"
#include "Engine/MaterialMerging.h"
#include "GameFramework/Actor.h"
#include "Components/StaticMeshComponent.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "LODActor.generated.h"
Data Structures
class ALODActor
Functions
UCLASS ()
LODActor is an instance of an autogenerated StaticMesh Actors by Hierarchical LOD System This is essentially just StaticMeshActor that you can't move or edit, but it contains multiple actors reference.
USTRUCT () struct FHLODInstancingKey
Mesh/Material pair used as a key to insert/retrieve instances in the LODActor.
Variables
TAutoConsoleVariable< FString > CVarHLODDistanceOverride
Function Documentation
UCLASS()
UCLASS ()
LODActor is an instance of an autogenerated StaticMesh Actors by Hierarchical LOD System This is essentially just StaticMeshActor that you can't move or edit, but it contains multiple actors reference.
See also
https://docs.unrealengine.com/BuildingWorlds/HLOD
UStaticMesh
References Display, hidecategories, Input, MinimalAPI, notplaceable, Object, Physics, and Transform.
USTRUCT()
USTRUCT ()
Mesh/Material pair used as a key to insert/retrieve instances in the LODActor.
Definition at line 23 of file LODActor.h.
References GENERATED_BODY, GetTypeHash(), HashCombine(), IsValid(), Key, Material, operator==(), Other, StaticMesh, and UPROPERTY.
Variable Documentation
CVarHLODDistanceOverride
TAutoConsoleVariable<FString> CVarHLODDistanceOverride extern