Unreal Engine 5.6 C++ API: UE::Geometry::TPairExpandIterator< InputIteratorT > Class Template Reference
UE::Geometry::TPairExpandIterator< InputIteratorT > Class Template Reference
Wrapper around existing integer iterator that returns either 0, 1, or 2 integers for each value that the original iterator returns.
#include "IteratorUtil.h"
Public Member Functions
TPairExpandIterator ()
TPairExpandIterator (const InputIteratorT &CurItr, const InputIteratorT &EndItr, const PairExpandFunctionT &PairFuncIn)
void goto_next ()
bool operator!= (const TPairExpandIterator &Other) const
int operator* () const
const TPairExpandIterator & operator++ ()
bool operator== (const TPairExpandIterator &Other) const
Data Fields
InputIteratorT Cur
FIndex2i CurPair
int CurPairI
int CurValue
InputIteratorT End
PairExpandFunctionT PairFunc
Private Types
using PairExpandFunctionT = TFunction<FIndex2i(int)>
Detailed Description
template<typename InputIteratorT>
class UE::Geometry::TPairExpandIterator< InputIteratorT >
Wrapper around existing integer iterator that returns either 0, 1, or 2 integers for each value that the original iterator returns.
This is specifically used by FDynamicMesh3::VtxTrianglesItr, where for each edge around a vertex, between 0 and 2 triangles need to be returned.
This is done via the PairExpandFunctionT TFunction, which returns a FIndex2i for a given integer. This pair must be either (a,invalid), (a, b), or (invalid, invalid), where invalid is integer < 0
Definition at line 275 of file IteratorUtil.h.
Member Typedef Documentation
PairExpandFunctionT
template<typename InputIteratorT> using UE::Geometry::TPairExpandIterator< InputIteratorT >::PairExpandFunctionT = TFunction<FIndex2i(int)> private
Definition at line 277 of file IteratorUtil.h.
Constructor & Destructor Documentation
TPairExpandIterator() [1/2]
template<typename InputIteratorT> UE::Geometry::TPairExpandIterator< InputIteratorT >::TPairExpandIterator () inline
Definition at line 280 of file IteratorUtil.h.
Referenced by operator!=(), operator++(), and operator==().
TPairExpandIterator() [2/2]
template<typename InputIteratorT> UE::Geometry::TPairExpandIterator< InputIteratorT >::TPairExpandIterator (const InputIteratorT & CurItr, const InputIteratorT & EndItr, const PairExpandFunctionT & PairFuncIn) inline
Definition at line 343 of file IteratorUtil.h.
References Cur, CurPairI, End, goto_next(), and PairFunc.
Member Function Documentation
goto_next()
template<typename InputIteratorT> void UE::Geometry::TPairExpandIterator< InputIteratorT >::goto_next () inline
Definition at line 302 of file IteratorUtil.h.
References Cur, CurPair, CurPairI, CurValue, End, and PairFunc.
Referenced by TPairExpandIterator(), and operator++().
operator!=()
template<typename InputIteratorT> bool UE::Geometry::TPairExpandIterator< InputIteratorT >::operator!= (const TPairExpandIterator< InputIteratorT > & Other) const inline
Definition at line 286 of file IteratorUtil.h.
References TPairExpandIterator(), Cur, and Other.
operator*()
template<typename InputIteratorT> int UE::Geometry::TPairExpandIterator< InputIteratorT >::operator* () const inline
Definition at line 291 of file IteratorUtil.h.
References CurValue.
operator++()
template<typename InputIteratorT> const TPairExpandIterator & UE::Geometry::TPairExpandIterator< InputIteratorT >::operator++ () inline
Definition at line 296 of file IteratorUtil.h.
References TPairExpandIterator(), and goto_next().
operator==()
template<typename InputIteratorT> bool UE::Geometry::TPairExpandIterator< InputIteratorT >::operator== (const TPairExpandIterator< InputIteratorT > & Other) const inline
Definition at line 282 of file IteratorUtil.h.
References TPairExpandIterator(), Cur, and Other.
Field Documentation
Cur
template<typename InputIteratorT> InputIteratorT UE::Geometry::TPairExpandIterator< InputIteratorT >::Cur
Definition at line 352 of file IteratorUtil.h.
Referenced by TPairExpandIterator(), goto_next(), operator!=(), and operator==().
CurPair
template<typename InputIteratorT> FIndex2i UE::Geometry::TPairExpandIterator< InputIteratorT >::CurPair
Definition at line 354 of file IteratorUtil.h.
Referenced by goto_next().
CurPairI
template<typename InputIteratorT> int UE::Geometry::TPairExpandIterator< InputIteratorT >::CurPairI
Definition at line 356 of file IteratorUtil.h.
Referenced by TPairExpandIterator(), and goto_next().
CurValue
template<typename InputIteratorT> int UE::Geometry::TPairExpandIterator< InputIteratorT >::CurValue
Definition at line 355 of file IteratorUtil.h.
Referenced by goto_next(), and operator*().
End
template<typename InputIteratorT> InputIteratorT UE::Geometry::TPairExpandIterator< InputIteratorT >::End
Definition at line 353 of file IteratorUtil.h.
Referenced by TPairExpandIterator(), and goto_next().
PairFunc
template<typename InputIteratorT> PairExpandFunctionT UE::Geometry::TPairExpandIterator< InputIteratorT >::PairFunc
Definition at line 357 of file IteratorUtil.h.
Referenced by TPairExpandIterator(), and goto_next().
The documentation for this class was generated from the following file:
IteratorUtil.h