Unreal Engine 5.6 C++ API: FStringFormatArg Struct Reference
FStringFormatArg Struct Reference
An argument supplied to FString::Format.
#include "StringFormatArg.h"
Public Types
enum EType {
Int , UInt , Double , String ,
StringLiteralANSI , StringLiteralWIDE , StringLiteralUCS2 , StringLiteralUTF8
}
Public Member Functions
FStringFormatArg ()=delete
Not default constructible.
FStringFormatArg (const ANSICHAR *Value)
FStringFormatArg (const double Value)
FStringFormatArg (const float Value)
FStringFormatArg (const FStringFormatArg &Other)
FStringFormatArg (const int32 Value)
FStringFormatArg (const int64 Value)
FStringFormatArg (const UCS2CHAR *Value)
FStringFormatArg (const uint32 Value)
FStringFormatArg (const uint64 Value)
FStringFormatArg (const UTF8CHAR *Value)
FStringFormatArg (const WIDECHAR *Value)
FStringFormatArg (FString Value)
FStringFormatArg (FStringFormatArg &&Other)
FStringFormatArg (FStringView Value)
~FStringFormatArg ()=default
FStringFormatArg & operator= (const FStringFormatArg &Other)
FStringFormatArg & operator= (FStringFormatArg &&Other)
Data Fields
union {
double DoubleValue
Value as double.
int64 IntValue
Value as integer.
const ANSICHAR * StringLiteralANSIValue
Value as an ANSI string literal.
const UCS2CHAR * StringLiteralUCS2Value
Value as a UCS2 string literal.
const UTF8CHAR * StringLiteralUTF8Value
Value as a UTF8 string literal.
const WIDECHAR * StringLiteralWIDEValue
Value as a WIDE string literal.
uint64 UIntValue
Value as uint.
};
FString StringValue
Value as an FString.
EType Type
The type of this arg.
Detailed Description
An argument supplied to FString::Format.
Definition at line 10 of file StringFormatArg.h.
Member Enumeration Documentation
EType
enum FStringFormatArg::EType
Enumerator
Int
UInt
Double
String
StringLiteralANSI
StringLiteralWIDE
StringLiteralUCS2
StringLiteralUTF8
Definition at line 12 of file StringFormatArg.h.
Constructor & Destructor Documentation
FStringFormatArg() [1/15]
FStringFormatArg::FStringFormatArg () delete
Not default constructible.
Referenced by FStringFormatArg(), FStringFormatArg(), operator=(), and operator=().
~FStringFormatArg()
FStringFormatArg::~FStringFormatArg () default
FStringFormatArg() [2/15]
FStringFormatArg::FStringFormatArg (const int32 Value)
References Value.
FStringFormatArg() [3/15]
FStringFormatArg::FStringFormatArg (const uint32 Value)
References Value.
FStringFormatArg() [4/15]
FStringFormatArg::FStringFormatArg (const int64 Value)
References Value.
FStringFormatArg() [5/15]
FStringFormatArg::FStringFormatArg (const uint64 Value)
References Value.
FStringFormatArg() [6/15]
FStringFormatArg::FStringFormatArg (const float Value)
References Value.
FStringFormatArg() [7/15]
FStringFormatArg::FStringFormatArg (const double Value)
References Value.
FStringFormatArg() [8/15]
FStringFormatArg::FStringFormatArg (FString Value)
References Value.
FStringFormatArg() [9/15]
FStringFormatArg::FStringFormatArg (FStringView Value)
References Value.
FStringFormatArg() [10/15]
FStringFormatArg::FStringFormatArg (const ANSICHAR * Value)
References Value.
FStringFormatArg() [11/15]
FStringFormatArg::FStringFormatArg (const WIDECHAR * Value)
References Value.
FStringFormatArg() [12/15]
FStringFormatArg::FStringFormatArg (const UCS2CHAR * Value)
References Value.
FStringFormatArg() [13/15]
FStringFormatArg::FStringFormatArg (const UTF8CHAR * Value)
References Value.
FStringFormatArg() [14/15]
FStringFormatArg::FStringFormatArg (const FStringFormatArg & Other) inline
Definition at line 56 of file StringFormatArg.h.
References FStringFormatArg(), and Other.
FStringFormatArg() [15/15]
FStringFormatArg::FStringFormatArg (FStringFormatArg && Other) inline
Definition at line 60 of file StringFormatArg.h.
References FStringFormatArg(), MoveTemp(), and Other.
Member Function Documentation
operator=() [1/2]
FStringFormatArg & FStringFormatArg::operator= (const FStringFormatArg & Other)
References FStringFormatArg(), and Other.
operator=() [2/2]
FStringFormatArg & FStringFormatArg::operator= (FStringFormatArg && Other)
References FStringFormatArg(), and Other.
Field Documentation
[union]
union { ... } FStringFormatArg
DoubleValue
double FStringFormatArg::DoubleValue
Value as double.
Definition at line 25 of file StringFormatArg.h.
IntValue
int64 FStringFormatArg::IntValue
Value as integer.
Definition at line 21 of file StringFormatArg.h.
StringLiteralANSIValue
const ANSICHAR* FStringFormatArg::StringLiteralANSIValue
Value as an ANSI string literal.
Definition at line 27 of file StringFormatArg.h.
StringLiteralUCS2Value
const UCS2CHAR* FStringFormatArg::StringLiteralUCS2Value
Value as a UCS2 string literal.
Definition at line 31 of file StringFormatArg.h.
StringLiteralUTF8Value
const UTF8CHAR* FStringFormatArg::StringLiteralUTF8Value
Value as a UTF8 string literal.
Definition at line 33 of file StringFormatArg.h.
StringLiteralWIDEValue
const WIDECHAR* FStringFormatArg::StringLiteralWIDEValue
Value as a WIDE string literal.
Definition at line 29 of file StringFormatArg.h.
StringValue
FString FStringFormatArg::StringValue
Value as an FString.
Definition at line 37 of file StringFormatArg.h.
Type
EType FStringFormatArg::Type
The type of this arg.
Definition at line 15 of file StringFormatArg.h.
UIntValue
uint64 FStringFormatArg::UIntValue
Value as uint.
Definition at line 23 of file StringFormatArg.h.
The documentation for this struct was generated from the following file:
StringFormatArg.h