Unreal Engine 5.6 C++ API: FBuoyancyComponentSim Class Reference
FBuoyancyComponentSim Class Reference
#include "BuoyancyComponentSimulation.h"
Public Types
using TParticleUtilities = Chaos::FParticleUtilitiesXR
Public Member Functions
FBuoyancyComponentSim ()
Static Public Member Functions
template<typename TBody>
static void AddForce (TBody *Body, const FVector &Force)
template<typename TBody>
static void AddForceAtPositionWorld (TBody *Body, const FVector &WorldForce, const FVector &WorldPosition)
template<typename TBody>
static void AddTorque (TBody *Body, const FVector &TorqueRadians)
template<typename TBody, typename TState>
static void ApplyAngularDrag (TBody *Body, const FBuoyancyData &BuoyancyData, const TState &State)
template<typename TBody, typename TAux, typename TState>
static void ApplyBuoyancy (TBody *Body, TAux &Aux, const TState &State)
template<typename TBody, typename TState>
static void ApplyLinearDrag (TBody *Body, const FBuoyancyData &BuoyancyData, const TState &State)
template<typename TBody, typename TState, typename TAux>
static void ApplyTorqueForDownstreamAngularRotation (const float DeltaSeconds, TBody *Body, TState &State, const FBuoyancyData &BuoyancyData, TAux &Aux)
template<typename TBody, typename TState, typename TAux>
static void ApplyWaterForce (TBody *Body, const FBuoyancyData &BuoyancyData, const TState &State, TAux &Aux, float DeltaSeconds)
static void ComputeBuoyancy (const FBuoyancyData &BuoyancyData, FSphericalPontoon &Pontoon, float ForwardSpeedKmh, float VelocityZ)
static FVector ComputeWaterForce (FSphericalPontoon &Pontoon, const FBuoyancyData &BuoyancyData, const FVector &BodyVelocity, float DeltaTime)
template<typename TBody>
static FVector GetAngularVelocity (const TBody *Body)
template<typename TBody>
static FVector GetVelocity (const TBody *Body)
static float GetWaterHeight (const TArray< FSolverSafeWaterBodyData * > &WaterBodies, FVector Position, float InWaveReferenceTime, const TMap< const FSolverSafeWaterBodyData *, float > &SplineKeyMap, float DefaultHeight, FSolverSafeWaterBodyData *&OutWaterBody, float &OutWaterDepth, FVector &OutWaterPlaneLocation, FVector &OutWaterPlaneNormal, FVector &OutWaterSurfacePosition, FVector &OutWaterVelocity, int32 &OutWaterBodyIdx, bool bShouldIncludeWaves=true)
template<typename TBody>
static FTransform GetWorldTM (const TBody *Body)
static float ToKmH (float Speed)
template<typename TBody, typename TAux, typename TOut>
static void Update (const float DeltaSeconds, const float TotalSeconds, const UWorld *World, TBody *Body, const FBuoyancyData &BuoyancyData, TAux &Aux, const TMap< UWaterBodyComponent *, TUniquePtr< FSolverSafeWaterBodyData > > &WaterBodyComponentData, TOut &Out)
template<typename TBody, typename TState, typename TAux>
static void UpdateBuoyancy (const TBody *Body, TState &State, const FBuoyancyData &BuoyancyData, TAux &Aux, const TMap< UWaterBodyComponent *, TUniquePtr< FSolverSafeWaterBodyData > > &WaterBodyComponentData)
template<typename TBody, typename TState>
static void UpdatePhysicsState (const TBody *Body, TState &State)
Detailed Description
Definition at line 93 of file BuoyancyComponentSimulation.h.
Member Typedef Documentation
TParticleUtilities
using FBuoyancyComponentSim::TParticleUtilities = Chaos::FParticleUtilitiesXR
Definition at line 97 of file BuoyancyComponentSimulation.h.
Constructor & Destructor Documentation
FBuoyancyComponentSim()
FBuoyancyComponentSim::FBuoyancyComponentSim () inline
Definition at line 99 of file BuoyancyComponentSimulation.h.
Member Function Documentation
AddForce()
template<typename TBody> void FBuoyancyComponentSim::AddForce (TBody * Body, const FVector & Force) inline static
Definition at line 538 of file BuoyancyComponentSimulation.h.
References ensure, Force, and FVector.
Referenced by ApplyLinearDrag(), and ApplyWaterForce().
AddForceAtPositionWorld()
template<typename TBody> void FBuoyancyComponentSim::AddForceAtPositionWorld (TBody * Body, const FVector & WorldForce, const FVector & WorldPosition) inline static
Definition at line 547 of file BuoyancyComponentSimulation.h.
References UE::Math::TVector< T >::ContainsNaN(), ensure, and FVector.
Referenced by ApplyBuoyancy().
AddTorque()
template<typename TBody> void FBuoyancyComponentSim::AddTorque (TBody * Body, const FVector & TorqueRadians) inline static
Definition at line 559 of file BuoyancyComponentSimulation.h.
References UE::Math::TVector< T >::ContainsNaN(), ensure, and FVector.
Referenced by ApplyAngularDrag(), and ApplyTorqueForDownstreamAngularRotation().
ApplyAngularDrag()
template<typename TBody, typename TState> void FBuoyancyComponentSim::ApplyAngularDrag (TBody * Body, const FBuoyancyData & BuoyancyData, const TState & State) inline static
Definition at line 603 of file BuoyancyComponentSimulation.h.
References AddTorque(), FVector, and State.
Referenced by Update().
ApplyBuoyancy()
template<typename TBody, typename TAux, typename TState> void FBuoyancyComponentSim::ApplyBuoyancy (TBody * Body, TAux & Aux, const TState & State) inline static
Definition at line 485 of file BuoyancyComponentSimulation.h.
References AddForceAtPositionWorld(), Aux, and State.
Referenced by Update().
ApplyLinearDrag()
template<typename TBody, typename TState> void FBuoyancyComponentSim::ApplyLinearDrag (TBody * Body, const FBuoyancyData & BuoyancyData, const TState & State) inline static
Definition at line 581 of file BuoyancyComponentSimulation.h.
References AddForce(), FMath::Clamp(), FVector, UE::Math::TVector< T >::GetSafeNormal(), UE::Math::TVector< T >::Size(), State, ToKmH(), UE::Math::TVector< T >::Z, and UE::Math::TVector< double >::ZeroVector.
Referenced by Update().
ApplyTorqueForDownstreamAngularRotation()
template<typename TBody, typename TState, typename TAux> void FBuoyancyComponentSim::ApplyTorqueForDownstreamAngularRotation (const float DeltaSeconds, TBody * Body, TState & State, const FBuoyancyData & BuoyancyData, TAux & Aux) inline static
Definition at line 161 of file BuoyancyComponentSimulation.h.
References AddTorque(), Angle, Aux, Axis, FMath::Clamp(), UE::Math::TVector< double >::DotProduct(), UE::Math::TQuat< double >::FindBetweenNormals(), FVector, UE::Math::TQuat< T >::GetAngle(), UE::Math::TQuat< T >::GetRotationAxis(), GetWorldTM(), FMath::RadiansToDegrees(), State, UE::Math::TTransform< T >::TransformVectorNoScale(), FMath::UnwindRadians(), and UE::Math::TVector< double >::ZeroVector.
Referenced by Update().
ApplyWaterForce()
template<typename TBody, typename TState, typename TAux> void FBuoyancyComponentSim::ApplyWaterForce (TBody * Body, const FBuoyancyData & BuoyancyData, const TState & State, TAux & Aux, float DeltaSeconds) inline static
Definition at line 568 of file BuoyancyComponentSimulation.h.
References AddForce(), Aux, ComputeWaterForce(), FVector, State, and UE::Math::TVector< double >::ZeroVector.
Referenced by Update().
ComputeBuoyancy()
void FBuoyancyComponentSim::ComputeBuoyancy (const FBuoyancyData & BuoyancyData, FSphericalPontoon & Pontoon, float ForwardSpeedKmh, float VelocityZ) inline static
Definition at line 306 of file BuoyancyComponentSimulation.h.
References Bottom, FMath::Clamp(), float, FVector, FMath::Max, PI, UE::Math::TVector< double >::UpVector, and UE::Math::TVector< T >::Z.
Referenced by UpdateBuoyancy().
ComputeWaterForce()
FVector FBuoyancyComponentSim::ComputeWaterForce (FSphericalPontoon & Pontoon, const FBuoyancyData & BuoyancyData, const FVector & BodyVelocity, float DeltaTime) inline static
Definition at line 239 of file BuoyancyComponentSimulation.h.
References DeltaTime, UE::Math::TVector< double >::Distance(), UE::Math::TVector< double >::DotProduct(), FVector, UE::Math::TVector< T >::GetClampedToSize(), FWaterSplineDataPhysics::GetLocationAtSplineInputKey(), UE::Math::TVector< T >::GetSafeNormal(), FSolverSafeWaterBodyData::GetWaterVelocityAtSplineInputKey(), FSolverSafeWaterBodyData::GetWaterVelocityVectorAtSplineInputKey(), FMath::Lerp(), FSolverSafeWaterBodyData::WaterBodyType, FSolverSafeWaterBodyData::WaterSpline, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< double >::ZeroVector.
Referenced by ApplyWaterForce().
GetAngularVelocity()
template<typename TBody> FVector FBuoyancyComponentSim::GetAngularVelocity (const TBody * Body) inline static
Definition at line 520 of file BuoyancyComponentSimulation.h.
References FVector.
Referenced by UpdatePhysicsState().
GetVelocity()
template<typename TBody> FVector FBuoyancyComponentSim::GetVelocity (const TBody * Body) inline static
Definition at line 514 of file BuoyancyComponentSimulation.h.
References FVector.
Referenced by UpdatePhysicsState().
GetWaterHeight()
float FBuoyancyComponentSim::GetWaterHeight (const TArray< FSolverSafeWaterBodyData * > & WaterBodies, FVector Position, float InWaveReferenceTime, const TMap< const FSolverSafeWaterBodyData *, float > & SplineKeyMap, float DefaultHeight, FSolverSafeWaterBodyData *& OutWaterBody, float & OutWaterDepth, FVector & OutWaterPlaneLocation, FVector & OutWaterPlaneNormal, FVector & OutWaterSurfacePosition, FVector & OutWaterVelocity, int32 & OutWaterBodyIdx, bool bShouldIncludeWaves = true) inline static
Definition at line 191 of file BuoyancyComponentSimulation.h.
References check, ComputeDepth, ComputeImmersionDepth, ComputeLocation, ComputeNormal, ComputeVelocity, EnumHasAnyFlags(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindRef(), FVector, FWaterBodyQueryResult::GetImmersionDepth(), FWaterBodyQueryResult::GetQueryFlags(), FWaterBodyQueryResult::GetVelocity(), FWaterBodyQueryResult::GetWaterPlaneLocation(), FWaterBodyQueryResult::GetWaterPlaneNormal(), FWaterBodyQueryResult::GetWaterSurfaceDepth(), FWaterBodyQueryResult::GetWaterSurfaceLocation(), IncludeWaves, FWaterBodyQueryResult::IsInExclusionVolume(), FWaterBodyQueryResult::IsInWater(), Position, UE::Math::TVector< double >::UpVector, and UE::Math::TVector< double >::ZeroVector.
Referenced by UpdateBuoyancy().
GetWorldTM()
template<typename TBody> FTransform FBuoyancyComponentSim::GetWorldTM (const TBody * Body) inline static
Definition at line 531 of file BuoyancyComponentSimulation.h.
Referenced by ApplyTorqueForDownstreamAngularRotation(), and UpdatePhysicsState().
ToKmH()
float FBuoyancyComponentSim::ToKmH (float Speed) inline static
Definition at line 525 of file BuoyancyComponentSimulation.h.
References Speed.
Referenced by ApplyLinearDrag(), and UpdatePhysicsState().
Update()
template<typename TBody, typename TAux, typename TOut> void FBuoyancyComponentSim::Update (const float DeltaSeconds, const float TotalSeconds, const UWorld * World, TBody * Body, const FBuoyancyData & BuoyancyData, TAux & Aux, const TMap< UWaterBodyComponent *, TUniquePtr< FSolverSafeWaterBodyData > > & WaterBodyComponentData, TOut & Out) inline static
Definition at line 103 of file BuoyancyComponentSimulation.h.
References ApplyAngularDrag(), ApplyBuoyancy(), ApplyLinearDrag(), ApplyTorqueForDownstreamAngularRotation(), ApplyWaterForce(), Aux, State, UpdateBuoyancy(), UpdatePhysicsState(), and FSolverSafeWaterBodyData::WaterBodyType.
UpdateBuoyancy()
template<typename TBody, typename TState, typename TAux> void FBuoyancyComponentSim::UpdateBuoyancy (const TBody * Body, TState & State, const FBuoyancyData & BuoyancyData, TAux & Aux, const TMap< UWaterBodyComponent *, TUniquePtr< FSolverSafeWaterBodyData > > & WaterBodyComponentData) inline static
Definition at line 345 of file BuoyancyComponentSimulation.h.
References TArray< InElementType, InAllocatorType >::Add(), Aux, FColor::Blue, ComputeBuoyancy(), CVarWaterBuoyancyDebugPoints, CVarWaterBuoyancyDebugSize, CVarWaterDebugBuoyancy, UE::Math::TVector< double >::ForwardVector, FVector, GetWaterHeight(), FColor::Green, Location, MakeTuple(), FColor::Red, UE::Math::TVector< double >::RightVector, Scale, State, TSequenceHistory< HistorySize >::Size, UE::Math::TVector< double >::UpVector, and UE::Math::TVector< T >::Z.
Referenced by Update().
UpdatePhysicsState()
template<typename TBody, typename TState> void FBuoyancyComponentSim::UpdatePhysicsState (const TBody * Body, TState & State) inline static
Definition at line 499 of file BuoyancyComponentSimulation.h.
References UE::Math::TVector< double >::DotProduct(), GetAngularVelocity(), UE::Math::TTransform< T >::GetUnitAxis(), GetVelocity(), GetWorldTM(), State, ToKmH(), EAxis::X, EAxis::Y, and EAxis::Z.
Referenced by Update().
The documentation for this class was generated from the following file:
BuoyancyComponentSimulation.h