Unreal Engine 5.6 C++ API: UE::Anim::FScopedGraphMessage Struct Reference
UE::Anim::FScopedGraphMessage Struct Reference
#include "AnimNodeMessages.h"
Protected Member Functions
FScopedGraphMessage (const FAnimationBaseContext &InContext)
void PopMessage ()
void PushMessage (const FAnimationBaseContext &InContext, TSharedRef< IGraphMessage > InMessage, FName InMessageType)
Protected Attributes
FName MessageType
FAnimationUpdateSharedContext * SharedContext
Detailed Description
Definition at line 143 of file AnimNodeMessages.h.
Constructor & Destructor Documentation
FScopedGraphMessage()
UE::Anim::FScopedGraphMessage::FScopedGraphMessage (const FAnimationBaseContext & InContext) protected
Referenced by UE::Anim::TOptionalScopedGraphMessage< TGraphMessageType >::TOptionalScopedGraphMessage(), and UE::Anim::TScopedGraphMessage< TGraphMessageType >::TScopedGraphMessage().
Member Function Documentation
PopMessage()
void UE::Anim::FScopedGraphMessage::PopMessage () protected
Referenced by UE::Anim::TOptionalScopedGraphMessage< TGraphMessageType >::~TOptionalScopedGraphMessage(), and UE::Anim::TScopedGraphMessage< TGraphMessageType >::~TScopedGraphMessage().
PushMessage()
void UE::Anim::FScopedGraphMessage::PushMessage (const FAnimationBaseContext & InContext, TSharedRef< IGraphMessage > InMessage, FName InMessageType) protected
Referenced by UE::Anim::TOptionalScopedGraphMessage< TGraphMessageType >::TOptionalScopedGraphMessage(), and UE::Anim::TScopedGraphMessage< TGraphMessageType >::TScopedGraphMessage().
Field Documentation
MessageType
FName UE::Anim::FScopedGraphMessage::MessageType protected
Definition at line 156 of file AnimNodeMessages.h.
SharedContext
FAnimationUpdateSharedContext* UE::Anim::FScopedGraphMessage::SharedContext protected
Definition at line 153 of file AnimNodeMessages.h.
The documentation for this struct was generated from the following file:
AnimNodeMessages.h