Unreal Engine 5.6 C++ API: UE::Geometry::FMeshUVShellMapEvaluator Class Reference
UE::Geometry::FMeshUVShellMapEvaluator Class Reference
A mesh evaluator for mesh properties as color data.
#include "MeshUVShellMapEvaluator.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FMeshUVShellMapEvaluator ()=default
FMeshUVShellMapEvaluator (const FMeshUVShellMapEvaluator &)=default
virtual DYNAMICMESH_API const TArray< EComponents > & DataLayout () const override
FMeshUVShellMapEvaluator & operator= (const FMeshUVShellMapEvaluator &)=default
DYNAMICMESH_API virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void Setup (const FMeshBaseBaker &Baker, FEvaluationContext &Context) override
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
virtual EMeshMapEvaluatorType Type () const override
Public Member Functions inherited from UE::Geometry::FMeshMapEvaluator
virtual ~FMeshMapEvaluator ()=default
Static Public Member Functions
static DYNAMICMESH_API void EvaluateChannel (const int DataIdx, float *&In, float &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateColor (const int DataIdx, float *&In, FVector4f &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateDefault (float *&Out, void *EvalData)
static DYNAMICMESH_API void EvaluateSample (float *&Out, const FCorrespondenceSample &Sample, void *EvalData)
Data Fields
FVector4f BackgroundColor = FVector4f(0.0f, 0.0f, 0.0f, 0.0f)
FVector4f ShellColor = FLinearColor::Gray
FVector2d TexelSize = FVector2d::One()
int UVLayer = 0
FVector4f WireframeColor = FLinearColor::Blue
float WireframeThickness = 1.0f
Protected Attributes
const IMeshBakerDetailSampler * DetailSampler = nullptr
Private Member Functions
DYNAMICMESH_API FVector4f SampleFunction (const FCorrespondenceSample &SampleData) const
Additional Inherited Members
Public Types inherited from UE::Geometry::FMeshMapEvaluator
enum class EAccumulateMode { Add , Overwrite , Last }
Accumulate mode informs the baker how samples should be accumulated into the buffer.
enum class EComponents { Float1 = 1 , Float2 = 2 , Float3 = 3 , Float4 = 4 }
The number of float components of an evaluator result/target.
Static Protected Member Functions inherited from UE::Geometry::FMeshMapEvaluator
static void WriteToBuffer (float *&Out, const float Data)
Write float data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector2f &Data)
Write FVector2f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector3f &Data)
Write FVector3f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector4f &Data)
Write FVector4f data to a float buffer and increment.
Detailed Description
A mesh evaluator for mesh properties as color data.
Definition at line 18 of file MeshUVShellMapEvaluator.h.
Constructor & Destructor Documentation
FMeshUVShellMapEvaluator() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshUVShellMapEvaluator::FMeshUVShellMapEvaluator () default
Referenced by FMeshUVShellMapEvaluator(), and operator=().
FMeshUVShellMapEvaluator() [2/2]
UE::Geometry::FMeshUVShellMapEvaluator::FMeshUVShellMapEvaluator (const FMeshUVShellMapEvaluator &) default
References FMeshUVShellMapEvaluator().
Member Function Documentation
DataLayout()
virtual DYNAMICMESH_API const TArray< EComponents > & UE::Geometry::FMeshUVShellMapEvaluator::DataLayout () const override virtual
Returns
the data layout of the evaluator
Implements UE::Geometry::FMeshMapEvaluator.
References UE_API.
EvaluateChannel()
DYNAMICMESH_API void UE::Geometry::FMeshUVShellMapEvaluator::EvaluateChannel (const int DataIdx, float *& In, float & Out, void * EvalData) static
References UE_API.
EvaluateColor()
DYNAMICMESH_API void UE::Geometry::FMeshUVShellMapEvaluator::EvaluateColor (const int DataIdx, float *& In, FVector4f & Out, void * EvalData) static
References UE_API.
EvaluateDefault()
DYNAMICMESH_API void UE::Geometry::FMeshUVShellMapEvaluator::EvaluateDefault (float *& Out, void * EvalData) static
References UE_API.
EvaluateSample()
DYNAMICMESH_API void UE::Geometry::FMeshUVShellMapEvaluator::EvaluateSample (float *& Out, const FCorrespondenceSample & Sample, void * EvalData) static
References UE_API.
operator=()
FMeshUVShellMapEvaluator & UE::Geometry::FMeshUVShellMapEvaluator::operator= (const FMeshUVShellMapEvaluator &) default
References FMeshUVShellMapEvaluator(), PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_API.
SampleFunction()
DYNAMICMESH_API FVector4f UE::Geometry::FMeshUVShellMapEvaluator::SampleFunction (const FCorrespondenceSample & SampleData) const private
References UE_API.
Setup()
DYNAMICMESH_API virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void UE::Geometry::FMeshUVShellMapEvaluator::Setup (const FMeshBaseBaker & Baker, FEvaluationContext & Context) override virtual
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
The evaluation context indicates to the baker how the evaluator should be invoked. See FEvaluationContext for more details.
Parameters
Baker the baker that owns this evaluator.
Context [out] the evaluation context.
Implements UE::Geometry::FMeshMapEvaluator.
Type()
virtual EMeshMapEvaluatorType UE::Geometry::FMeshUVShellMapEvaluator::Type () const inline override virtual
Returns
the type of evaluator.
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 41 of file MeshUVShellMapEvaluator.h.
References UE::Geometry::UVShell.
Field Documentation
BackgroundColor
FVector4f UE::Geometry::FMeshUVShellMapEvaluator::BackgroundColor = FVector4f(0.0f, 0.0f, 0.0f, 0.0f)
Definition at line 25 of file MeshUVShellMapEvaluator.h.
DetailSampler
const IMeshBakerDetailSampler* UE::Geometry::FMeshUVShellMapEvaluator::DetailSampler = nullptr protected
Definition at line 53 of file MeshUVShellMapEvaluator.h.
ShellColor
FVector4f UE::Geometry::FMeshUVShellMapEvaluator::ShellColor = FLinearColor::Gray
Definition at line 24 of file MeshUVShellMapEvaluator.h.
TexelSize
FVector2d UE::Geometry::FMeshUVShellMapEvaluator::TexelSize = FVector2d::One()
Definition at line 21 of file MeshUVShellMapEvaluator.h.
UVLayer
int UE::Geometry::FMeshUVShellMapEvaluator::UVLayer = 0
Definition at line 27 of file MeshUVShellMapEvaluator.h.
WireframeColor
FVector4f UE::Geometry::FMeshUVShellMapEvaluator::WireframeColor = FLinearColor::Blue
Definition at line 23 of file MeshUVShellMapEvaluator.h.
WireframeThickness
float UE::Geometry::FMeshUVShellMapEvaluator::WireframeThickness = 1.0f
Definition at line 22 of file MeshUVShellMapEvaluator.h.
The documentation for this class was generated from the following file:
MeshUVShellMapEvaluator.h