Unreal Engine 5.6 C++ API: FExpressionNode Class Reference
FExpressionNode Class Reference
A node in an expression.
#include "ExpressionParserTypes.h"
Public Member Functions
FExpressionNode ()=default
Default constructor.
FExpressionNode (const FExpressionNode &)=delete
FExpressionNode (FExpressionNode &&In)
template<typename T UE_REQUIRES>
FExpressionNode (T In)
Construction from client expression data type.
~FExpressionNode ()
template<typename T>
const T * Cast () const
Cast this node to the specified type.
FExpressionNode Copy () const
Copy this node and its wrapped data.
const FGuid & GetTypeId () const
Get the type identifier of this node.
FExpressionNode & operator= (const FExpressionNode &)=delete
FExpressionNode & operator= (FExpressionNode &&In)
Private Member Functions
Impl::IExpressionNodeStorage * GetData ()
Helper accessor to the data interface.
const Impl::IExpressionNodeStorage * GetData () const
Private Attributes
uint8 InlineBytes [MaxStackAllocationSize]
FGuid TypeId
TypeID - 16 bytes.
Static Private Attributes
static constexpr uint32 MaxStackAllocationSize = 64 - sizeof(FGuid)
The maximum size of type we will allow allocation on the stack (for efficiency).
Detailed Description
A node in an expression.
Can be constructed from any C++ type that has a corresponding DEFINE_EXPRESSION_NODE_TYPE. Evaluation behaviour (unary/binary operator etc) is defined in the expression grammar, rather than the type itself.
Definition at line 216 of file ExpressionParserTypes.h.
Constructor & Destructor Documentation
FExpressionNode() [1/4]
FExpressionNode::FExpressionNode () default
Default constructor.
Referenced by FExpressionNode(), FExpressionNode(), Copy(), operator=(), and operator=().
FExpressionNode() [2/4]
template<typename T UE_REQUIRES> FExpressionNode::FExpressionNode (T In)
Construction from client expression data type.
~FExpressionNode()
FExpressionNode::~FExpressionNode ()
FExpressionNode() [3/4]
FExpressionNode::FExpressionNode (FExpressionNode && In)
References FExpressionNode().
FExpressionNode() [4/4]
FExpressionNode::FExpressionNode (const FExpressionNode &) delete
References FExpressionNode().
Member Function Documentation
Cast()
template<typename T> const T * FExpressionNode::Cast () const
Cast this node to the specified type.
Will return nullptr if the types do not match.
Copy()
FExpressionNode FExpressionNode::Copy () const
Copy this node and its wrapped data.
References FExpressionNode().
GetData() [1/2]
Impl::IExpressionNodeStorage * FExpressionNode::GetData () private
Helper accessor to the data interface.
Returns null for empty containers.
GetData() [2/2]
const Impl::IExpressionNodeStorage * FExpressionNode::GetData () const private
GetTypeId()
const FGuid & FExpressionNode::GetTypeId () const
Get the type identifier of this node.
operator=() [1/2]
FExpressionNode & FExpressionNode::operator= (const FExpressionNode &) delete
References FExpressionNode().
operator=() [2/2]
FExpressionNode & FExpressionNode::operator= (FExpressionNode && In)
References FExpressionNode().
Field Documentation
InlineBytes
uint8 FExpressionNode::InlineBytes[MaxStackAllocationSize] private
Definition at line 257 of file ExpressionParserTypes.h.
MaxStackAllocationSize
uint32 FExpressionNode::MaxStackAllocationSize = 64 - sizeof(FGuid) static constexpr private
The maximum size of type we will allow allocation on the stack (for efficiency).
Anything larger will be allocated on the heap.
Definition at line 249 of file ExpressionParserTypes.h.
TypeId
FGuid FExpressionNode::TypeId private
TypeID - 16 bytes.
Definition at line 256 of file ExpressionParserTypes.h.
The documentation for this class was generated from the following file:
ExpressionParserTypes.h