Unreal Engine 5.6 C++ API: UEnvQueryGenerator_PathingGrid Class Reference
UEnvQueryGenerator_PathingGrid Class Reference
#include "EnvQueryGenerator_PathingGrid.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FAIDataProviderBoolValue PathToItem
pathfinding direction
virtual AIMODULE_API void ProjectAndFilterNavPoints (TArray< FNavLocation > &Points, FEnvQueryInstance &QueryInstance) const override
UPROPERTY () FAIDataProviderFloatValue ScanRangeMultiplier
multiplier for max distance between point and context
UPROPERTY () TSubclassOf< UNavigationQueryFilter > NavigationFilter
navigation filter to use in pathfinding
Detailed Description
Definition at line 22 of file EnvQueryGenerator_PathingGrid.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UEnvQueryGenerator_PathingGrid::GENERATED_UCLASS_BODY () private
pathfinding direction
References Category, and UPROPERTY().
ProjectAndFilterNavPoints()
virtual AIMODULE_API void UEnvQueryGenerator_PathingGrid::ProjectAndFilterNavPoints (TArray< FNavLocation > & Points, FEnvQueryInstance & QueryInstance) const override private virtual
References Points, and ProjectAndFilterNavPoints().
Referenced by ProjectAndFilterNavPoints().
UPROPERTY() [1/2]
UEnvQueryGenerator_PathingGrid::UPROPERTY () private
multiplier for max distance between point and context
References Category, and UPROPERTY().
UPROPERTY() [2/2]
UEnvQueryGenerator_PathingGrid::UPROPERTY () private
navigation filter to use in pathfinding
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
EnvQueryGenerator_PathingGrid.h