Unreal Engine 5.6 C++ API: SSplitter::FSlot Class Reference
SSplitter::FSlot Class Reference
#include "SSplitter.h"
Public Member Functions
FSlot ()
bool CanBeResized () const
A slot can be resize if bIsResizable and the SizeRule is a FractionOfParent or the OnSlotResized delegate is set.
float GetMinSize () const
float GetSizeValue () const
ESizeRule GetSizingRule () const
bool IsResizable () const
FOnSlotResized & OnSlotResized ()
Callback when the slot is resized.
const FOnSlotResized & OnSlotResized () const
void SetMinSize (float InMinSize)
Minimum slot size when resizing.
void SetResizable (bool bInIsResizable)
Can the slot be resize by the user.
void SetSizeValue (TAttribute< float > InValue)
When the RuleSize is set to FractionOfParent, the size of the slot is the Value percentage of its parent size.
void SetSizingRule (TAttribute< ESizeRule > InSizeRule)
The size rule used by the slot.
SizeRule MinSize SLATE_ARGUMENT (TOptional< bool >, Resizable) SLATE_EVENT(FOnSlotResized
Can the slot be resize by the user.
SizeRule SLATE_ATTRIBUTE (float, Value) SLATE_ATTRIBUTE(float
When the RuleSize is set to FractionOfParent, the size of the slot is the Value percentage of its parent size.
SLATE_SLOT_BEGIN_ARGS (FSlot, TSlotBase< FSlot >) SLATE_ATTRIBUTE(ESizeRule
The size rule used by the slot.
SizeRule MinSize OnSlotResized SLATE_SLOT_END_ARGS () 1 void Construct(const FChildren &SlotOwner
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Data Fields
SizeRule MinSize OnSlotResized FSlotArguments && InArgs
Private Attributes
TOptional< bool > bIsResizable
TAttribute< float > MinSizeValue
FOnSlotResized OnSlotResized_Handler
TAttribute< float > SizeValue
TAttribute< ESizeRule > SizingRule
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Detailed Description
Definition at line 65 of file SSplitter.h.
Constructor & Destructor Documentation
FSlot()
SSplitter::FSlot::FSlot () inline
Definition at line 68 of file SSplitter.h.
References FSlot(), SSplitter::FractionOfParent, MinSizeValue, SizeValue, and SizingRule.
Referenced by FSlot(), and SLATE_SLOT_BEGIN_ARGS().
Member Function Documentation
CanBeResized()
bool SSplitter::FSlot::CanBeResized () const
A slot can be resize if bIsResizable and the SizeRule is a FractionOfParent or the OnSlotResized delegate is set.
References UE_API.
GetMinSize()
float SSplitter::FSlot::GetMinSize () const inline
Definition at line 119 of file SSplitter.h.
References MinSizeValue.
GetSizeValue()
float SSplitter::FSlot::GetSizeValue () const inline
Definition at line 96 of file SSplitter.h.
References SizeValue.
GetSizingRule()
ESizeRule SSplitter::FSlot::GetSizingRule () const inline
Definition at line 142 of file SSplitter.h.
References SizingRule.
IsResizable()
bool SSplitter::FSlot::IsResizable () const inline
Definition at line 109 of file SSplitter.h.
References bIsResizable.
OnSlotResized() [1/2]
FOnSlotResized & SSplitter::FSlot::OnSlotResized () inline
Callback when the slot is resized.
See also
CanBeResized()
Definition at line 128 of file SSplitter.h.
References OnSlotResized_Handler.
Referenced by SLATE_ARGUMENT().
OnSlotResized() [2/2]
const FOnSlotResized & SSplitter::FSlot::OnSlotResized () const inline
Definition at line 132 of file SSplitter.h.
References OnSlotResized_Handler.
SetMinSize()
void SSplitter::FSlot::SetMinSize (float InMinSize) inline
Minimum slot size when resizing.
Definition at line 115 of file SSplitter.h.
References MinSizeValue.
SetResizable()
void SSplitter::FSlot::SetResizable (bool bInIsResizable) inline
Can the slot be resize by the user.
See also
CanBeResized()
Definition at line 105 of file SSplitter.h.
References bIsResizable.
SetSizeValue()
void SSplitter::FSlot::SetSizeValue (TAttribute< float > InValue) inline
When the RuleSize is set to FractionOfParent, the size of the slot is the Value percentage of its parent size.
Definition at line 92 of file SSplitter.h.
References MoveTemp(), SetSizeValue(), and SizeValue.
Referenced by SetSizeValue().
SetSizingRule()
void SSplitter::FSlot::SetSizingRule (TAttribute< ESizeRule > InSizeRule) inline
The size rule used by the slot.
Definition at line 138 of file SSplitter.h.
References MoveTemp(), and SizingRule.
SLATE_ARGUMENT()
SizeRule MinSize SSplitter::FSlot::SLATE_ARGUMENT (TOptional< bool > , Resizable)
Can the slot be resize by the user.
Callback when the slot is resized.
References OnSlotResized(), SLATE_ARGUMENT(), and SLATE_EVENT.
Referenced by SLATE_ARGUMENT().
SLATE_ATTRIBUTE()
SizeRule SSplitter::FSlot::SLATE_ATTRIBUTE (float , Value)
When the RuleSize is set to FractionOfParent, the size of the slot is the Value percentage of its parent size.
Minimum slot size when resizing.
References MinSize, SLATE_ATTRIBUTE(), and Value.
Referenced by SLATE_ATTRIBUTE().
SLATE_SLOT_BEGIN_ARGS()
SSplitter::FSlot::SLATE_SLOT_BEGIN_ARGS (FSlot , TSlotBase< FSlot >)
The size rule used by the slot.
References FSlot().
SLATE_SLOT_END_ARGS()
SizeRule MinSize OnSlotResized SSplitter::FSlot::SLATE_SLOT_END_ARGS () const &
References SLATE_SLOT_END_ARGS().
Referenced by SLATE_SLOT_END_ARGS().
Field Documentation
bIsResizable
TOptional<bool> SSplitter::FSlot::bIsResizable private
Definition at line 156 of file SSplitter.h.
Referenced by IsResizable(), and SetResizable().
InArgs
SizeRule MinSize OnSlotResized FSlotArguments&& SSplitter::FSlot::InArgs
Definition at line 89 of file SSplitter.h.
MinSizeValue
TAttribute<float> SSplitter::FSlot::MinSizeValue private
Definition at line 154 of file SSplitter.h.
Referenced by FSlot(), GetMinSize(), and SetMinSize().
OnSlotResized_Handler
FOnSlotResized SSplitter::FSlot::OnSlotResized_Handler private
Definition at line 155 of file SSplitter.h.
Referenced by OnSlotResized(), and OnSlotResized().
SizeValue
TAttribute<float> SSplitter::FSlot::SizeValue private
Definition at line 153 of file SSplitter.h.
Referenced by FSlot(), GetSizeValue(), and SetSizeValue().
SizingRule
TAttribute<ESizeRule> SSplitter::FSlot::SizingRule private
Definition at line 152 of file SSplitter.h.
Referenced by FSlot(), GetSizingRule(), and SetSizingRule().
The documentation for this class was generated from the following file:
SSplitter.h