Unreal Engine 5.6 C++ API: FSharedBuffer Class Reference
FSharedBuffer Class Reference
A reference to a shared-ownership immutable buffer.
#include "SharedBuffer.h"
Public Member Functions
FSharedBuffer ()=default
Construct a null shared buffer.
FSharedBuffer (FBufferOwner *Owner)
Construct a shared buffer from a new unreferenced buffer owner.
const void * GetData () const
Returns a pointer to the start of the buffer.
uint64 GetSize () const
Returns the size of the buffer in bytes.
FMemoryView GetView () const
Returns a view of the buffer.
bool IsMaterialized () const
Returns true if the referenced buffer has been materialized.
bool IsNull () const
Returns true if this does not point to a buffer owner.
bool IsOwned () const
Returns true if this keeps the referenced buffer alive.
FSharedBuffer MakeOwned () &&
FSharedBuffer MakeOwned () const &
Returns a buffer that is owned, by cloning if not owned.
void Materialize () const
Materialize the buffer by making its data and size available.
FUniqueBuffer MoveToUnique ()
Convert this to a unique buffer, leaving this null.
operator bool () const
Returns true if this points to a buffer owner.
operator FMemoryView () const
bool operator!= (const FSharedBuffer &BufferB) const
bool operator== (const FSharedBuffer &BufferB) const
void Reset ()
Reset this to null.
Static Public Member Functions
static FSharedBuffer Clone (const void *Data, uint64 Size)
static FSharedBuffer Clone (FMemoryView View)
Make an owned clone of the input.
static FSharedBuffer MakeView (const void *Data, uint64 Size)
static FSharedBuffer MakeView (const void *Data, uint64 Size, const FSharedBuffer &OuterBuffer)
static FSharedBuffer MakeView (const void *Data, uint64 Size, FSharedBuffer &&OuterBuffer)
static FSharedBuffer MakeView (FMemoryView View)
Make a non-owned view of the input.
static FSharedBuffer MakeView (FMemoryView View, const FSharedBuffer &OuterBuffer)
static FSharedBuffer MakeView (FMemoryView View, FSharedBuffer &&OuterBuffer)
Make a view of the input within its outer buffer.
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >())) * = nullptr>
static FSharedBuffer TakeOwnership (const void *Data, uint64 Size, DeleteFunctionType &&DeleteFunction)
Make an owned buffer by taking ownership of the input.
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >(), std::declval< uint64 >())) * = nullptr>
static FSharedBuffer TakeOwnership (const void *Data, uint64 Size, DeleteFunctionType &&DeleteFunction)
Make an owned buffer by taking ownership of the input.
Private Types
using FOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FSharedOps>
using FWeakOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FWeakOps>
Private Member Functions
FSharedBuffer (const FWeakOwnerPtrType &WeakOwner)
FSharedBuffer (FOwnerPtrType &&SharedOwner)
Private Attributes
FOwnerPtrType Owner
Friends
class FUniqueBuffer
class FWeakSharedBuffer
uint32 GetTypeHash (const FSharedBuffer &Buffer)
bool operator!= (const FSharedBuffer &BufferA, const FUniqueBuffer &BufferB)
bool operator!= (const FUniqueBuffer &BufferA, const FSharedBuffer &BufferB)
bool operator== (const FSharedBuffer &BufferA, const FUniqueBuffer &BufferB)
bool operator== (const FUniqueBuffer &BufferA, const FSharedBuffer &BufferB)
const FOwnerPtrType & ToPrivateOwnerPtr (const FSharedBuffer &Buffer)
FOwnerPtrType ToPrivateOwnerPtr (FSharedBuffer &&Buffer)
Detailed Description
A reference to a shared-ownership immutable buffer.
See also
FBufferOwner
Definition at line 340 of file SharedBuffer.h.
Member Typedef Documentation
FOwnerPtrType
using FSharedBuffer::FOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FSharedOps> private
Definition at line 433 of file SharedBuffer.h.
FWeakOwnerPtrType
using FSharedBuffer::FWeakOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FWeakOps> private
Definition at line 434 of file SharedBuffer.h.
Constructor & Destructor Documentation
FSharedBuffer() [1/4]
FSharedBuffer::FSharedBuffer () default
Construct a null shared buffer.
Referenced by Clone(), Clone(), GetTypeHash, MakeOwned(), MakeOwned(), MakeView(), MakeView(), MakeView(), MakeView(), MakeView(), MakeView(), operator!=, operator!=(), operator!=, operator==, operator==(), operator==, TakeOwnership(), ToPrivateOwnerPtr, and ToPrivateOwnerPtr.
FSharedBuffer() [2/4]
FSharedBuffer::FSharedBuffer (FBufferOwner * Owner) explicit
Construct a shared buffer from a new unreferenced buffer owner.
References Owner.
FSharedBuffer() [3/4]
FSharedBuffer::FSharedBuffer (FOwnerPtrType && SharedOwner) explicit private
FSharedBuffer() [4/4]
FSharedBuffer::FSharedBuffer (const FWeakOwnerPtrType & WeakOwner) explicit private
Member Function Documentation
Clone() [1/2]
FSharedBuffer FSharedBuffer::Clone (const void * Data, uint64 Size) static nodiscard
References FSharedBuffer(), and TSequenceHistory< HistorySize >::Size.
Clone() [2/2]
FSharedBuffer FSharedBuffer::Clone (FMemoryView View) static nodiscard
Make an owned clone of the input.
References FSharedBuffer().
Referenced by FShaderCodeResource::PopulateHeader().
GetData()
const void * FSharedBuffer::GetData () const inline nodiscard
Returns a pointer to the start of the buffer.
Definition at line 385 of file SharedBuffer.h.
References Owner.
Referenced by TCbBuffer< ViewType >::TCbBuffer(), and TraceServices::TCachedPagedArray< InItemType, PageSize >::GetPageForNextItem().
GetSize()
uint64 FSharedBuffer::GetSize () const inline nodiscard
Returns the size of the buffer in bytes.
Definition at line 388 of file SharedBuffer.h.
References Owner.
Referenced by GetView().
GetView()
FMemoryView FSharedBuffer::GetView () const inline nodiscard
Returns a view of the buffer.
Definition at line 391 of file SharedBuffer.h.
References GetData(), and GetSize().
Referenced by TCbBuffer< ViewType >::TCbBuffer(), TCbBuffer< ViewType >::TCbBuffer(), operator FMemoryView(), and FShaderCodeResource::Unpack().
IsMaterialized()
bool FSharedBuffer::IsMaterialized () const inline nodiscard
Returns true if the referenced buffer has been materialized.
Definition at line 412 of file SharedBuffer.h.
References IsMaterialized(), and Owner.
Referenced by IsMaterialized().
IsNull()
bool FSharedBuffer::IsNull () const inline nodiscard
Returns true if this does not point to a buffer owner.
A null buffer is always owned, materialized, and empty.
Definition at line 402 of file SharedBuffer.h.
References Owner.
Referenced by FCompositeBuffer::FCompositeBuffer(), and operator bool().
IsOwned()
bool FSharedBuffer::IsOwned () const inline nodiscard
Returns true if this keeps the referenced buffer alive.
Definition at line 405 of file SharedBuffer.h.
References Owner.
MakeOwned() [1/2]
FSharedBuffer FSharedBuffer::MakeOwned () && nodiscard
References FSharedBuffer(), and MakeOwned().
MakeOwned() [2/2]
FSharedBuffer FSharedBuffer::MakeOwned () const & nodiscard
Returns a buffer that is owned, by cloning if not owned.
References FSharedBuffer().
Referenced by MakeOwned().
MakeView() [1/6]
FSharedBuffer FSharedBuffer::MakeView (const void * Data, uint64 Size) static nodiscard
References FSharedBuffer(), and TSequenceHistory< HistorySize >::Size.
MakeView() [2/6]
FSharedBuffer FSharedBuffer::MakeView (const void * Data, uint64 Size, const FSharedBuffer & OuterBuffer) static nodiscard
References FSharedBuffer(), and TSequenceHistory< HistorySize >::Size.
MakeView() [3/6]
FSharedBuffer FSharedBuffer::MakeView (const void * Data, uint64 Size, FSharedBuffer && OuterBuffer) static nodiscard
References FSharedBuffer(), and TSequenceHistory< HistorySize >::Size.
MakeView() [4/6]
FSharedBuffer FSharedBuffer::MakeView (FMemoryView View) static nodiscard
Make a non-owned view of the input.
References FSharedBuffer().
Referenced by FCbField::AsBinary(), FCbField::AsBinary(), and FShaderCodeResource::Unpack().
MakeView() [5/6]
FSharedBuffer FSharedBuffer::MakeView (FMemoryView View, const FSharedBuffer & OuterBuffer) static nodiscard
References FSharedBuffer().
MakeView() [6/6]
FSharedBuffer FSharedBuffer::MakeView (FMemoryView View, FSharedBuffer && OuterBuffer) static nodiscard
Make a view of the input within its outer buffer.
Ownership matches OuterBuffer.
References FSharedBuffer().
Materialize()
void FSharedBuffer::Materialize () const
Materialize the buffer by making its data and size available.
The buffer is automatically materialized by GetData, GetSize, GetView.
MoveToUnique()
FUniqueBuffer FSharedBuffer::MoveToUnique () nodiscard
Convert this to a unique buffer, leaving this null.
Steals the buffer owner from the shared buffer if this is the last reference to it, otherwise clones the shared buffer to guarantee unique ownership. A non-owned buffer is always cloned.
References FUniqueBuffer.
operator bool()
FSharedBuffer::operator bool () const inline explicit nodiscard
Returns true if this points to a buffer owner.
Definition at line 395 of file SharedBuffer.h.
References IsNull().
operator FMemoryView()
FSharedBuffer::operator FMemoryView () const inline nodiscard
Definition at line 392 of file SharedBuffer.h.
References GetView().
operator!=()
bool FSharedBuffer::operator!= (const FSharedBuffer & BufferB) const inline
Definition at line 450 of file SharedBuffer.h.
References FSharedBuffer(), and ToPrivateOwnerPtr.
operator==()
bool FSharedBuffer::operator== (const FSharedBuffer & BufferB) const inline
Definition at line 446 of file SharedBuffer.h.
References FSharedBuffer(), and ToPrivateOwnerPtr.
Reset()
void FSharedBuffer::Reset ()
Reset this to null.
TakeOwnership() [1/2]
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >(), std::declval< uint64 >())) *> FSharedBuffer FSharedBuffer::TakeOwnership (const void * Data, uint64 Size, DeleteFunctionType && DeleteFunction) inline static nodiscard
Make an owned buffer by taking ownership of the input.
Parameters
DeleteFunction Called with Data to free memory when the last shared reference is released.
Definition at line 569 of file SharedBuffer.h.
References FSharedBuffer(), Delete, Forward(), Invoke(), TakeOwnership, TakeOwnership(), and TSequenceHistory< HistorySize >::Size.
Referenced by TakeOwnership().
TakeOwnership() [2/2]
template<typename DeleteFunctionType, decltype(Invoke(std::declval< DeleteFunctionType >(), std::declval< void * >(), std::declval< uint64 >())) * = nullptr> FSharedBuffer FSharedBuffer::TakeOwnership (const void * Data, uint64 Size, DeleteFunctionType && DeleteFunction) inline static nodiscard
Make an owned buffer by taking ownership of the input.
Parameters
DeleteFunction Called with (Data, Size) to free memory when the last shared reference is released.
References FSharedBuffer(), and TSequenceHistory< HistorySize >::Size.
Friends And Related Symbol Documentation
FUniqueBuffer
friend class FUniqueBuffer friend
Definition at line 429 of file SharedBuffer.h.
References FUniqueBuffer.
Referenced by FUniqueBuffer, MoveToUnique(), operator!=, operator!=, operator==, and operator==.
FWeakSharedBuffer
friend class FWeakSharedBuffer friend
Definition at line 430 of file SharedBuffer.h.
References FWeakSharedBuffer.
Referenced by FWeakSharedBuffer.
GetTypeHash
uint32 GetTypeHash (const FSharedBuffer & Buffer) friend
Definition at line 445 of file SharedBuffer.h.
References FSharedBuffer(), Buffer, PointerHash(), and ToPrivateOwnerPtr.
operator!= [1/2]
bool operator!= (const FSharedBuffer & BufferA, const FUniqueBuffer & BufferB) friend
Definition at line 451 of file SharedBuffer.h.
References FSharedBuffer(), FUniqueBuffer, and ToPrivateOwnerPtr.
operator!= [2/2]
bool operator!= (const FUniqueBuffer & BufferA, const FSharedBuffer & BufferB) friend
Definition at line 453 of file SharedBuffer.h.
References FSharedBuffer(), FUniqueBuffer, and ToPrivateOwnerPtr.
operator== [1/2]
bool operator== (const FSharedBuffer & BufferA, const FUniqueBuffer & BufferB) friend
Definition at line 447 of file SharedBuffer.h.
References FSharedBuffer(), FUniqueBuffer, and ToPrivateOwnerPtr.
operator== [2/2]
bool operator== (const FUniqueBuffer & BufferA, const FSharedBuffer & BufferB) friend
Definition at line 452 of file SharedBuffer.h.
References FSharedBuffer(), FUniqueBuffer, and ToPrivateOwnerPtr.
ToPrivateOwnerPtr [1/2]
const FOwnerPtrType & ToPrivateOwnerPtr (const FSharedBuffer & Buffer) friend
Definition at line 439 of file SharedBuffer.h.
References FSharedBuffer(), and Buffer.
Referenced by GetTypeHash, operator!=, operator!=(), operator!=, operator==, operator==(), and operator==.
ToPrivateOwnerPtr [2/2]
FOwnerPtrType ToPrivateOwnerPtr (FSharedBuffer && Buffer) friend
Definition at line 440 of file SharedBuffer.h.
References FSharedBuffer(), Buffer, and MoveTemp().
Field Documentation
Owner
FOwnerPtrType FSharedBuffer::Owner private
Definition at line 442 of file SharedBuffer.h.
Referenced by FSharedBuffer(), GetData(), GetSize(), IsMaterialized(), IsNull(), and IsOwned().
The documentation for this class was generated from the following file:
SharedBuffer.h