Unreal Engine 5.6 C++ API: FSoundCueParameterTransmitter Class Reference
FSoundCueParameterTransmitter Class Reference
#include "SoundCue.h"
Public Member Functions
FSoundCueParameterTransmitter (Audio::FParameterTransmitterInitParams &&InParams)
virtual ~FSoundCueParameterTransmitter ()
virtual void AddReferencedObjects (FReferenceCollector &InCollector) override
void CreateChildTransmitter (UPTRINT InWaveInstanceHash, USoundBase &InSound, Audio::FParameterTransmitterInitParams InTransmitterInitParams)
TArray< FAudioParameter > ReleaseAccumulatedParameterUpdates ()
The SoundCueParameter keeps a running track of parameter changes from SetParameters(...).
void RemoveChildTransmitter (UPTRINT InWaveInstanceHash)
virtual bool SetParameters (TArray< FAudioParameter > &&InParameters) override
UE_DEPRECATED (5.6, "Do not access ParamsToSet. This will be moved to be a private member.") TArray< FAudioParameter > ParamsToSet
UE_DEPRECATED (5.6, "Do not access Transmitters. This will be moved to be a private member.") TMap< UPTRINT
UE_DEPRECATED (5.6, "Use AddReferencedObjects(...) instead") 1 TArray< const TObjectPtr< UObject > * > GetReferencedObjects() const override
Data Fields
TSharedPtr< Audio::IParameterTransmitter > Transmitters
Private Types
using Super = Audio::FParameterTransmitterBase
Detailed Description
Definition at line 350 of file SoundCue.h.
Member Typedef Documentation
Super
using FSoundCueParameterTransmitter::Super = Audio::FParameterTransmitterBase private
Definition at line 352 of file SoundCue.h.
Constructor & Destructor Documentation
FSoundCueParameterTransmitter()
FSoundCueParameterTransmitter::FSoundCueParameterTransmitter (Audio::FParameterTransmitterInitParams && InParams)
~FSoundCueParameterTransmitter()
virtual FSoundCueParameterTransmitter::~FSoundCueParameterTransmitter () virtual
Member Function Documentation
AddReferencedObjects()
virtual void FSoundCueParameterTransmitter::AddReferencedObjects (FReferenceCollector & InCollector) override virtual
References AddReferencedObjects().
Referenced by AddReferencedObjects().
CreateChildTransmitter()
void FSoundCueParameterTransmitter::CreateChildTransmitter (UPTRINT InWaveInstanceHash, USoundBase & InSound, Audio::FParameterTransmitterInitParams InTransmitterInitParams)
References CreateChildTransmitter().
Referenced by CreateChildTransmitter().
ReleaseAccumulatedParameterUpdates()
TArray< FAudioParameter > FSoundCueParameterTransmitter::ReleaseAccumulatedParameterUpdates ()
The SoundCueParameter keeps a running track of parameter changes from SetParameters(...).
When this method is called, the accumulated parameters are returned and the internal tracking of accumulated parameters is reset.
References ReleaseAccumulatedParameterUpdates().
Referenced by ReleaseAccumulatedParameterUpdates().
RemoveChildTransmitter()
void FSoundCueParameterTransmitter::RemoveChildTransmitter (UPTRINT InWaveInstanceHash)
References RemoveChildTransmitter().
Referenced by RemoveChildTransmitter().
SetParameters()
virtual bool FSoundCueParameterTransmitter::SetParameters (TArray< FAudioParameter > && InParameters) override virtual
References SetParameters().
Referenced by SetParameters().
UE_DEPRECATED() [1/3]
FSoundCueParameterTransmitter::UE_DEPRECATED (5. 6, "Do not access ParamsToSet. This will be moved to be a private member.")
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FSoundCueParameterTransmitter::UE_DEPRECATED (5. 6, "Do not access Transmitters. This will be moved to be a private member.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FSoundCueParameterTransmitter::UE_DEPRECATED (5. 6, "Use AddReferencedObjects(...) instead") const override
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
Transmitters
TSharedPtr<Audio::IParameterTransmitter> FSoundCueParameterTransmitter::Transmitters
Definition at line 378 of file SoundCue.h.
The documentation for this class was generated from the following file:
SoundCue.h