Unreal Engine 5.6 C++ API: UE::FIoFileHandle Struct Reference
UE::FIoFileHandle Struct Reference
Handle to a file on disk.
#include "PlatformIoDispatcher.h"
Public Member Functions
FIoFileHandle ()=default
FIoFileHandle (uint64 InHandle)
bool IsValid () const
uint64 Value () const
Private Attributes
uint64 Handle = 0
Friends
uint32 GetTypeHash (FIoFileHandle FileHandle)
bool operator!= (FIoFileHandle LHS, FIoFileHandle RHS)
bool operator< (FIoFileHandle LHS, FIoFileHandle RHS)
bool operator== (FIoFileHandle LHS, FIoFileHandle RHS)
Detailed Description
Handle to a file on disk.
Definition at line 55 of file PlatformIoDispatcher.h.
Constructor & Destructor Documentation
FIoFileHandle() [1/2]
UE::FIoFileHandle::FIoFileHandle () default
Referenced by GetTypeHash, operator!=, operator<, and operator==.
FIoFileHandle() [2/2]
UE::FIoFileHandle::FIoFileHandle (uint64 InHandle) inline explicit
Definition at line 58 of file PlatformIoDispatcher.h.
References Handle.
Member Function Documentation
IsValid()
bool UE::FIoFileHandle::IsValid () const inline
Definition at line 63 of file PlatformIoDispatcher.h.
References Handle.
Referenced by UE::FPlatformIoDispatcherBase::CancelAllRequests(), and UE::FGenericPlatformIoDispatcher::CloseFile().
Value()
uint64 UE::FIoFileHandle::Value () const inline
Definition at line 62 of file PlatformIoDispatcher.h.
References Handle.
Referenced by UE::FGenericPlatformIoDispatcher::CloseFile(), UE::FIoFileBlockRequestQueue::FileOffsetLess(), UE::FGenericPlatformIoDispatcher::GetPlatformFileInfo(), and UE::FGenericPlatformIoDispatcher::ProcessFileIo().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FIoFileHandle FileHandle) friend
Definition at line 65 of file PlatformIoDispatcher.h.
References FIoFileHandle(), GetTypeHash, and Handle.
Referenced by GetTypeHash.
operator!=
bool operator!= (FIoFileHandle LHS, FIoFileHandle RHS) friend
Definition at line 67 of file PlatformIoDispatcher.h.
References FIoFileHandle(), and Handle.
operator<
bool operator< (FIoFileHandle LHS, FIoFileHandle RHS) friend
Definition at line 68 of file PlatformIoDispatcher.h.
References FIoFileHandle(), and Handle.
operator==
bool operator== (FIoFileHandle LHS, FIoFileHandle RHS) friend
Definition at line 66 of file PlatformIoDispatcher.h.
References FIoFileHandle(), and Handle.
Field Documentation
Handle
uint64 UE::FIoFileHandle::Handle = 0 private
Definition at line 71 of file PlatformIoDispatcher.h.
Referenced by FIoFileHandle(), GetTypeHash, IsValid(), operator!=, operator<, operator==, and Value().
The documentation for this struct was generated from the following file:
PlatformIoDispatcher.h