Unreal Engine 5.6 C++ API: UE::AnimNext::FExecutionContext Struct Reference
UE::AnimNext::FExecutionContext Struct Reference
Execution Context.
#include "ExecutionContext.h"
Public Member Functions
ANIMNEXTANIMGRAPH_API FExecutionContext ()
ANIMNEXTANIMGRAPH_API FExecutionContext (FAnimNextGraphInstance &InGraphInstance)
virtual ~FExecutionContext ()=default
ANIMNEXTANIMGRAPH_API FTraitPtr AllocateNodeInstance (const FTraitBinding &ParentBinding, FAnimNextTraitHandle ChildTraitHandle) const
ANIMNEXTANIMGRAPH_API FTraitPtr AllocateNodeInstance (const FWeakTraitPtr &ParentBinding, FAnimNextTraitHandle ChildTraitHandle) const
ANIMNEXTANIMGRAPH_API FTraitPtr AllocateNodeInstance (FAnimNextGraphInstance &GraphInstance, FAnimNextTraitHandle ChildTraitHandle) const
ANIMNEXTANIMGRAPH_API void BindTo (const FWeakTraitPtr &TraitPtr)
ANIMNEXTANIMGRAPH_API void BindTo (FAnimNextGraphInstance &InGraphInstance)
template<class ScopedTraitInterface>
void ForEachScopedInterface (TFunctionRef< bool(TTraitBinding< ScopedTraitInterface > &Binding)> InFunction) const
const TWeakObjectPtr< const USkeletalMeshComponent > GetBindingObject () const
template<class ComponentType>
ComponentType & GetComponent () const
ANIMNEXTANIMGRAPH_API GraphInstanceComponentMapType::TConstIterator GetComponentIterator () const
ANIMNEXTANIMGRAPH_API const class UObject * GetHostObject () const
FMemStack & GetMemStack () const
FAnimNextGraphInstance & GetRootGraphInstance () const
template<class ScopedTraitInterface>
bool GetScopedInterface (TTraitBinding< ScopedTraitInterface > &OutBinding) const
ANIMNEXTANIMGRAPH_API bool GetStack (const FWeakTraitPtr &TraitPtr, FTraitStackBinding &OutStackBinding) const
bool HasScopedInterfaces () const
ANIMNEXTANIMGRAPH_API bool IsBound () const
ANIMNEXTANIMGRAPH_API bool IsBoundTo (const FAnimNextGraphInstance &InGraphInstance) const
template<class ScopedTraitInterface>
bool PopScopedInterface (const FTraitBinding &Binding)
ANIMNEXTANIMGRAPH_API bool PopStackScopedInterfaces (const FTraitBinding &Binding)
ANIMNEXTANIMGRAPH_API bool PopStackScopedInterfaces (const FTraitStackBinding &StackBinding)
template<class ScopedTraitInterface>
void PushOptionalScopedInterface (bool bCondition, const FTraitBinding &Binding)
template<class ScopedTraitInterface>
void PushScopedInterface (const FTraitBinding &Binding)
virtual ANIMNEXTANIMGRAPH_API void RaiseInputTraitEvent (FAnimNextTraitEventPtr Event)
virtual ANIMNEXTANIMGRAPH_API void RaiseOutputTraitEvent (FAnimNextTraitEventPtr Event)
ANIMNEXTANIMGRAPH_API void ReleaseNodeInstance (FTraitPtr &NodePtr) const
void SetBindingObject (const TWeakObjectPtr< const USkeletalMeshComponent > &InBindingObject)
template<class ComponentType>
ComponentType * TryGetComponent () const
Protected Attributes
TWeakObjectPtr< const USkeletalMeshComponent > BindingObject = nullptr
FMemStack & MemStack
Private Member Functions
FExecutionContext (const FExecutionContext &)=delete
ANIMNEXTANIMGRAPH_API FGraphInstanceComponent & AddComponent (int32 ComponentNameHash, FName ComponentName, TSharedPtr< FGraphInstanceComponent > &&Component) const
ANIMNEXTANIMGRAPH_API void ForEachScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, TFunctionRef< bool(FTraitBinding &Binding)> InFunction) const
ANIMNEXTANIMGRAPH_API const FNodeDescription & GetNodeDescription (const FAnimNextGraphInstance &GraphInstance, FNodeHandle NodeHandle) const
ANIMNEXTANIMGRAPH_API const FNodeDescription & GetNodeDescription (const FNodeInstance &NodeInstance) const
ANIMNEXTANIMGRAPH_API const FNodeTemplate * GetNodeTemplate (const FNodeDescription &NodeDesc) const
ANIMNEXTANIMGRAPH_API bool GetScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding &OutBinding) const
ANIMNEXTANIMGRAPH_API const FTrait * GetTrait (const FTraitTemplate &TraitDesc) const
FExecutionContext & operator= (const FExecutionContext &)=delete
ANIMNEXTANIMGRAPH_API bool PopScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding &Binding)
ANIMNEXTANIMGRAPH_API void PushScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding &Binding)
ANIMNEXTANIMGRAPH_API FGraphInstanceComponent * TryGetComponent (int32 ComponentNameHash, FName ComponentName) const
Private Attributes
Private::FScopedInterfaceEntry * FreeScopedInterfaceEntryStackHead = nullptr
const FNodeTemplateRegistry & NodeTemplateRegistry
FAnimNextGraphInstance * RootGraphInstance = nullptr
Private::FScopedInterfaceEntry * ScopedInterfaceStackHead = nullptr
const FTraitRegistry & TraitRegistry
Friends
struct FTraitStackBinding
Detailed Description
Execution Context.
The execution context aims to centralize the trait query API. It is meant to be bound to a graph instance and re-used by the nodes/traits within.
Definition at line 50 of file ExecutionContext.h.
Constructor & Destructor Documentation
FExecutionContext() [1/3]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FExecutionContext::FExecutionContext ()
References UE_API.
Referenced by FExecutionContext(), and operator=().
FExecutionContext() [2/3]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FExecutionContext::FExecutionContext (FAnimNextGraphInstance & InGraphInstance) explicit
References UE_API.
~FExecutionContext()
virtual UE::AnimNext::FExecutionContext::~FExecutionContext () virtual default
FExecutionContext() [3/3]
UE::AnimNext::FExecutionContext::FExecutionContext (const FExecutionContext &) private delete
References FExecutionContext().
Member Function Documentation
AddComponent()
ANIMNEXTANIMGRAPH_API FGraphInstanceComponent & UE::AnimNext::FExecutionContext::AddComponent (int32 ComponentNameHash, FName ComponentName, TSharedPtr< FGraphInstanceComponent > && Component) const private
References Component, and UE_API.
Referenced by GetComponent().
AllocateNodeInstance() [1/3]
FTraitPtr UE::AnimNext::FExecutionContext::AllocateNodeInstance (const FTraitBinding & ParentBinding, FAnimNextTraitHandle ChildTraitHandle) const inline
Definition at line 329 of file ExecutionContext.h.
References AllocateNodeInstance(), and UE::AnimNext::FTraitBinding::GetTraitPtr().
AllocateNodeInstance() [2/3]
ANIMNEXTANIMGRAPH_API FTraitPtr UE::AnimNext::FExecutionContext::AllocateNodeInstance (const FWeakTraitPtr & ParentBinding, FAnimNextTraitHandle ChildTraitHandle) const
References UE_API.
AllocateNodeInstance() [3/3]
ANIMNEXTANIMGRAPH_API FTraitPtr UE::AnimNext::FExecutionContext::AllocateNodeInstance (FAnimNextGraphInstance & GraphInstance, FAnimNextTraitHandle ChildTraitHandle) const
References UE_API.
Referenced by AllocateNodeInstance().
BindTo() [1/2]
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::BindTo (const FWeakTraitPtr & TraitPtr)
References UE_API.
BindTo() [2/2]
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::BindTo (FAnimNextGraphInstance & InGraphInstance)
References UE_API.
ForEachScopedInterface()
template<class ScopedTraitInterface> void UE::AnimNext::FExecutionContext::ForEachScopedInterface (TFunctionRef< bool(TTraitBinding< ScopedTraitInterface > &Binding)> InFunction) const inline
Definition at line 315 of file ExecutionContext.h.
References ForEachScopedInterfaceImpl().
ForEachScopedInterfaceImpl()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::ForEachScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, TFunctionRef< bool(FTraitBinding &Binding)> InFunction) const private
References UE_API.
Referenced by ForEachScopedInterface().
GetBindingObject()
const TWeakObjectPtr< const USkeletalMeshComponent > UE::AnimNext::FExecutionContext::GetBindingObject () const inline
Definition at line 207 of file ExecutionContext.h.
References BindingObject.
GetComponent()
template<class ComponentType> ComponentType & UE::AnimNext::FExecutionContext::GetComponent () const
Definition at line 335 of file ExecutionContext.h.
References AddComponent(), Component, GetTypeHash(), MakeShared(), RootGraphInstance, and TryGetComponent().
GetComponentIterator()
ANIMNEXTANIMGRAPH_API GraphInstanceComponentMapType::TConstIterator UE::AnimNext::FExecutionContext::GetComponentIterator () const
References UE_API.
GetHostObject()
ANIMNEXTANIMGRAPH_API const class UObject * UE::AnimNext::FExecutionContext::GetHostObject () const
References UE_API.
GetMemStack()
FMemStack & UE::AnimNext::FExecutionContext::GetMemStack () const inline
Definition at line 210 of file ExecutionContext.h.
References MemStack.
GetNodeDescription() [1/2]
ANIMNEXTANIMGRAPH_API const FNodeDescription & UE::AnimNext::FExecutionContext::GetNodeDescription (const FAnimNextGraphInstance & GraphInstance, FNodeHandle NodeHandle) const private
References UE_API.
GetNodeDescription() [2/2]
ANIMNEXTANIMGRAPH_API const FNodeDescription & UE::AnimNext::FExecutionContext::GetNodeDescription (const FNodeInstance & NodeInstance) const private
References UE_API.
GetNodeTemplate()
ANIMNEXTANIMGRAPH_API const FNodeTemplate * UE::AnimNext::FExecutionContext::GetNodeTemplate (const FNodeDescription & NodeDesc) const private
References UE_API.
GetRootGraphInstance()
FAnimNextGraphInstance & UE::AnimNext::FExecutionContext::GetRootGraphInstance () const inline
Definition at line 203 of file ExecutionContext.h.
References RootGraphInstance.
GetScopedInterface()
template<class ScopedTraitInterface> bool UE::AnimNext::FExecutionContext::GetScopedInterface (TTraitBinding< ScopedTraitInterface > & OutBinding) const inline
Definition at line 306 of file ExecutionContext.h.
References GetScopedInterfaceImpl().
GetScopedInterfaceImpl()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FExecutionContext::GetScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding & OutBinding) const private
References UE_API.
Referenced by GetScopedInterface().
GetStack()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FExecutionContext::GetStack (const FWeakTraitPtr & TraitPtr, FTraitStackBinding & OutStackBinding) const
References FTraitStackBinding, and UE_API.
GetTrait()
ANIMNEXTANIMGRAPH_API const FTrait * UE::AnimNext::FExecutionContext::GetTrait (const FTraitTemplate & TraitDesc) const private
References UE_API.
HasScopedInterfaces()
bool UE::AnimNext::FExecutionContext::HasScopedInterfaces () const inline
Definition at line 141 of file ExecutionContext.h.
References ScopedInterfaceStackHead.
IsBound()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FExecutionContext::IsBound () const
References UE_API.
IsBoundTo()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FExecutionContext::IsBoundTo (const FAnimNextGraphInstance & InGraphInstance) const
References UE_API.
operator=()
FExecutionContext & UE::AnimNext::FExecutionContext::operator= (const FExecutionContext &) private delete
References FExecutionContext().
PopScopedInterface()
template<class ScopedTraitInterface> bool UE::AnimNext::FExecutionContext::PopScopedInterface (const FTraitBinding & Binding) inline
Definition at line 287 of file ExecutionContext.h.
References PopScopedInterfaceImpl().
PopScopedInterfaceImpl()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FExecutionContext::PopScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding & Binding) private
References UE_API.
Referenced by PopScopedInterface().
PopStackScopedInterfaces() [1/2]
bool UE::AnimNext::FExecutionContext::PopStackScopedInterfaces (const FTraitBinding & Binding) inline
Definition at line 295 of file ExecutionContext.h.
References UE::AnimNext::FTraitBinding::GetStack(), UE::AnimNext::FTraitBinding::IsValid(), and PopStackScopedInterfaces().
Referenced by PopStackScopedInterfaces().
PopStackScopedInterfaces() [2/2]
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FExecutionContext::PopStackScopedInterfaces (const FTraitStackBinding & StackBinding)
References FTraitStackBinding, and UE_API.
PushOptionalScopedInterface()
template<class ScopedTraitInterface> void UE::AnimNext::FExecutionContext::PushOptionalScopedInterface (bool bCondition, const FTraitBinding & Binding) inline
Definition at line 274 of file ExecutionContext.h.
References PushScopedInterface().
PushScopedInterface()
template<class ScopedTraitInterface> void UE::AnimNext::FExecutionContext::PushScopedInterface (const FTraitBinding & Binding) inline
Definition at line 265 of file ExecutionContext.h.
References PushScopedInterfaceImpl().
Referenced by PushOptionalScopedInterface().
PushScopedInterfaceImpl()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::PushScopedInterfaceImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding & Binding) private
References UE_API.
Referenced by PushScopedInterface().
RaiseInputTraitEvent()
virtual ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::RaiseInputTraitEvent (FAnimNextTraitEventPtr Event) virtual
Reimplemented in UE::AnimNext::FUpdateTraversalContext.
References Event, and UE_API.
RaiseOutputTraitEvent()
virtual ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::RaiseOutputTraitEvent (FAnimNextTraitEventPtr Event) virtual
Reimplemented in UE::AnimNext::FUpdateTraversalContext.
References Event, and UE_API.
ReleaseNodeInstance()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FExecutionContext::ReleaseNodeInstance (FTraitPtr & NodePtr) const
References UE_API.
SetBindingObject()
void UE::AnimNext::FExecutionContext::SetBindingObject (const TWeakObjectPtr< const USkeletalMeshComponent > & InBindingObject) inline
Definition at line 206 of file ExecutionContext.h.
References BindingObject.
TryGetComponent() [1/2]
template<class ComponentType> ComponentType * UE::AnimNext::FExecutionContext::TryGetComponent () const
Definition at line 351 of file ExecutionContext.h.
References GetTypeHash(), and TryGetComponent().
Referenced by GetComponent(), and TryGetComponent().
TryGetComponent() [2/2]
ANIMNEXTANIMGRAPH_API FGraphInstanceComponent * UE::AnimNext::FExecutionContext::TryGetComponent (int32 ComponentNameHash, FName ComponentName) const private
References UE_API.
Friends And Related Symbol Documentation
FTraitStackBinding
friend struct FTraitStackBinding friend
Definition at line 258 of file ExecutionContext.h.
References FTraitStackBinding.
Referenced by FTraitStackBinding, GetStack(), and PopStackScopedInterfaces().
Field Documentation
BindingObject
TWeakObjectPtr<const USkeletalMeshComponent> UE::AnimNext::FExecutionContext::BindingObject = nullptr protected
Definition at line 235 of file ExecutionContext.h.
Referenced by GetBindingObject(), and SetBindingObject().
FreeScopedInterfaceEntryStackHead
Private::FScopedInterfaceEntry* UE::AnimNext::FExecutionContext::FreeScopedInterfaceEntryStackHead = nullptr private
Definition at line 254 of file ExecutionContext.h.
MemStack
FMemStack& UE::AnimNext::FExecutionContext::MemStack protected
Definition at line 238 of file ExecutionContext.h.
Referenced by GetMemStack().
NodeTemplateRegistry
const FNodeTemplateRegistry& UE::AnimNext::FExecutionContext::NodeTemplateRegistry private
Definition at line 242 of file ExecutionContext.h.
RootGraphInstance
FAnimNextGraphInstance* UE::AnimNext::FExecutionContext::RootGraphInstance = nullptr private
Definition at line 246 of file ExecutionContext.h.
Referenced by GetComponent(), and GetRootGraphInstance().
ScopedInterfaceStackHead
Private::FScopedInterfaceEntry* UE::AnimNext::FExecutionContext::ScopedInterfaceStackHead = nullptr private
Definition at line 249 of file ExecutionContext.h.
Referenced by HasScopedInterfaces().
TraitRegistry
const FTraitRegistry& UE::AnimNext::FExecutionContext::TraitRegistry private
Definition at line 243 of file ExecutionContext.h.
The documentation for this struct was generated from the following file:
ExecutionContext.h