Unreal Engine 5.6 C++ API: FLazySingleton Class Reference
FLazySingleton Class Reference
Allows inline friend declaration without forward-declaring TLazySingleton.
#include "LazySingleton.h"
Static Protected Member Functions
template<class T>
static void Construct (void *Place)
template<class T>
static void Destruct (T *Instance)
Detailed Description
Allows inline friend declaration without forward-declaring TLazySingleton.
Definition at line 8 of file LazySingleton.h.
Member Function Documentation
Construct()
template<class T> void FLazySingleton::Construct (void * Place) inline static protected
Definition at line 11 of file LazySingleton.h.
Referenced by TLazySingleton< T >::Get(), and TLazySingleton< T >::TryGet().
Destruct()
template<class T> void FLazySingleton::Destruct (T * Instance) inline static protected
Definition at line 12 of file LazySingleton.h.
References Instance.
Referenced by TLazySingleton< T >::Reset().
The documentation for this class was generated from the following file:
LazySingleton.h