Unreal Engine 5.6 C++ API: FRigVMEditorZoomLevelsContainer Struct Reference
FRigVMEditorZoomLevelsContainer Struct Reference
#include "RigVMEditor.h"
Data Structures
struct FRigVMEditorZoomLevelEntry
Public Member Functions
FRigVMEditorZoomLevelsContainer ()
int32 GetDefaultZoomLevel () const override
EGraphRenderingLOD::Type GetLOD (int32 InZoomLevel) const override
int32 GetNearestZoomLevel (float InZoomAmount) const override
int32 GetNumZoomLevels () const override
float GetZoomAmount (int32 InZoomLevel) const override
FText GetZoomText (int32 InZoomLevel) const override
Public Member Functions inherited from FZoomLevelsContainer
virtual ~FZoomLevelsContainer (void)
virtual EGraphZoomLimitHandling GetZoomLimitHandling () const
Data Fields
TArray< FRigVMEditorZoomLevelEntry > ZoomLevels
Detailed Description
Definition at line 631 of file RigVMEditor.h.
Constructor & Destructor Documentation
FRigVMEditorZoomLevelsContainer()
FRigVMEditorZoomLevelsContainer::FRigVMEditorZoomLevelsContainer () inline
Definition at line 649 of file RigVMEditor.h.
References EGraphRenderingLOD::DefaultDetail, FText::FromString(), EGraphRenderingLOD::FullyZoomedIn, EGraphRenderingLOD::LowDetail, EGraphRenderingLOD::LowestDetail, EGraphRenderingLOD::MediumDetail, TEXT, and ZoomLevels.
Member Function Documentation
GetDefaultZoomLevel()
int32 FRigVMEditorZoomLevelsContainer::GetDefaultZoomLevel () const inline override virtual
Returns
the optimal(1:1) zoom level value, default zoom level for the graph
Implements FZoomLevelsContainer.
Definition at line 706 of file RigVMEditor.h.
Referenced by GetNearestZoomLevel().
GetLOD()
EGraphRenderingLOD::Type FRigVMEditorZoomLevelsContainer::GetLOD (int32 InZoomLevel) const inline override virtual
Parameters
InZoomLevel virtual zoom level value
Returns
associated LOD value
Implements FZoomLevelsContainer.
Definition at line 711 of file RigVMEditor.h.
References checkSlow, and ZoomLevels.
GetNearestZoomLevel()
int32 FRigVMEditorZoomLevelsContainer::GetNearestZoomLevel (float InZoomAmount) const inline override virtual
Parameters
InZoomAmount scaling value
Returns
nearest ZoomLevel mapping for provided scale value
Implements FZoomLevelsContainer.
Definition at line 682 of file RigVMEditor.h.
References GetDefaultZoomLevel(), GetNumZoomLevels(), and GetZoomAmount().
GetNumZoomLevels()
int32 FRigVMEditorZoomLevelsContainer::GetNumZoomLevels () const inline override virtual
Returns
count of supported zoom levels
Implements FZoomLevelsContainer.
Definition at line 701 of file RigVMEditor.h.
References ZoomLevels.
Referenced by GetNearestZoomLevel().
GetZoomAmount()
float FRigVMEditorZoomLevelsContainer::GetZoomAmount (int32 InZoomLevel) const inline override virtual
Parameters
InZoomLevel virtual zoom level value
Returns
associated scaling value
Implements FZoomLevelsContainer.
Definition at line 676 of file RigVMEditor.h.
References checkSlow, and ZoomLevels.
Referenced by GetNearestZoomLevel().
GetZoomText()
FText FRigVMEditorZoomLevelsContainer::GetZoomText (int32 InZoomLevel) const inline override virtual
Parameters
InZoomLevel virtual zoom level value
Returns
associated friendly name
Implements FZoomLevelsContainer.
Definition at line 695 of file RigVMEditor.h.
References checkSlow, and ZoomLevels.
Field Documentation
ZoomLevels
TArray<FRigVMEditorZoomLevelEntry> FRigVMEditorZoomLevelsContainer::ZoomLevels
Definition at line 717 of file RigVMEditor.h.
Referenced by FRigVMEditorZoomLevelsContainer(), GetLOD(), GetNumZoomLevels(), GetZoomAmount(), and GetZoomText().
The documentation for this struct was generated from the following file:
RigVMEditor.h