Unreal Engine 5.6 C++ API: FStyleFonts Struct Reference
FStyleFonts Struct Reference
#include "StarshipCoreStyle.h"
Static Public Member Functions
static const FStyleFonts & Get ()
Data Fields
const FSlateFontInfo HeadingExtraSmall
const FSlateFontInfo HeadingMedium
const FSlateFontInfo HeadingSmall
const FSlateFontInfo Large
const FSlateFontInfo LargeBold
const FSlateFontInfo Normal
const FSlateFontInfo NormalBold
const FSlateFontInfo NormalBoldItalic
const FSlateFontInfo NormalItalic
const FSlateFontInfo Small
const FSlateFontInfo SmallBold
Private Member Functions
FStyleFonts ()
Static Private Attributes
static TUniquePtr< struct FStyleFonts > Instance
Detailed Description
Definition at line 90 of file StarshipCoreStyle.h.
Constructor & Destructor Documentation
FStyleFonts()
FStyleFonts::FStyleFonts () private
Referenced by Get().
Member Function Documentation
Get()
const FStyleFonts & FStyleFonts::Get () inline static
Definition at line 94 of file StarshipCoreStyle.h.
References FStyleFonts(), Instance, and MakeUnique().
Field Documentation
HeadingExtraSmall
const FSlateFontInfo FStyleFonts::HeadingExtraSmall
Definition at line 114 of file StarshipCoreStyle.h.
HeadingMedium
const FSlateFontInfo FStyleFonts::HeadingMedium
Definition at line 112 of file StarshipCoreStyle.h.
HeadingSmall
const FSlateFontInfo FStyleFonts::HeadingSmall
Definition at line 113 of file StarshipCoreStyle.h.
Instance
TUniquePtr<struct FStyleFonts> FStyleFonts::Instance static private
Definition at line 118 of file StarshipCoreStyle.h.
Referenced by Get().
Large
const FSlateFontInfo FStyleFonts::Large
Definition at line 109 of file StarshipCoreStyle.h.
LargeBold
const FSlateFontInfo FStyleFonts::LargeBold
Definition at line 110 of file StarshipCoreStyle.h.
Normal
const FSlateFontInfo FStyleFonts::Normal
Definition at line 103 of file StarshipCoreStyle.h.
NormalBold
const FSlateFontInfo FStyleFonts::NormalBold
Definition at line 105 of file StarshipCoreStyle.h.
NormalBoldItalic
const FSlateFontInfo FStyleFonts::NormalBoldItalic
Definition at line 106 of file StarshipCoreStyle.h.
NormalItalic
const FSlateFontInfo FStyleFonts::NormalItalic
Definition at line 104 of file StarshipCoreStyle.h.
Small
const FSlateFontInfo FStyleFonts::Small
Definition at line 107 of file StarshipCoreStyle.h.
SmallBold
const FSlateFontInfo FStyleFonts::SmallBold
Definition at line 108 of file StarshipCoreStyle.h.
The documentation for this struct was generated from the following file:
StarshipCoreStyle.h