Unreal Engine 5.6 C++ API: HarmonixMetasound::FMidiStream Class Reference
HarmonixMetasound::FMidiStream Class Reference
#include "MidiStream.h"
Public Types
using FEventFilter = TFunction<bool(const FMidiStreamEvent&)>
using FEventTransformer = TFunction<FMidiStreamEvent(const FMidiStreamEvent&)>
Public Member Functions
HARMONIXMETASOUND_API void AddMidiEvent (const FMidiStreamEvent &Event)
HARMONIXMETASOUND_API void AddNoteOffEventOrCancelPendingNoteOn (const FMidiStreamEvent &Event)
HARMONIXMETASOUND_API TSharedPtr< const FMidiClock, ESPMode::NotThreadSafe > GetClock () const
const TArray< FMidiStreamEvent > & GetEventsInBlock () const
HARMONIXMETASOUND_API const FString * GetMidiTrackText (int32 TrackNumber, int32 TextIndex) const
int32 GetTicksPerQuarterNote () const
HARMONIXMETASOUND_API void InsertMidiEvent (const FMidiStreamEvent &Event)
HARMONIXMETASOUND_API void InsertNoteOffEventOrCancelPendingNoteOn (const FMidiStreamEvent &Event)
HARMONIXMETASOUND_API bool NoteIsActive (const FMidiStreamEvent &Event) const
HARMONIXMETASOUND_API void PrepareBlock ()
HARMONIXMETASOUND_API void ResetClock ()
HARMONIXMETASOUND_API void SetClock (const FMidiClock &InClock)
void SetMidiFile (const FMidiFileProxyPtr &MidiFile)
void SetTicksPerQuarterNote (int32 InTicksPerQuarterNote)
Static Public Member Functions
static HARMONIXMETASOUND_API void Copy (const FMidiStream &From, FMidiStream &To, const FEventFilter &Filter=NoOpFilter, const FEventTransformer &Transformer=NoOpTransformer)
static HARMONIXMETASOUND_API void Merge (const FMidiStream &From, FMidiStream &To, const FEventFilter &Filter=NoOpFilter, const FEventTransformer &Transformer=NoOpTransformer)
static HARMONIXMETASOUND_API void Merge (const FMidiStream &FromA, const FMidiStream &FromB, FMidiStream &To, const FEventFilter &Filter=NoOpFilter, const FEventTransformer &Transformer=NoOpTransformer)
Static Public Attributes
static const FEventFilter NoOpFilter = [](const FMidiStreamEvent&) { return true; }
static const FEventTransformer NoOpTransformer = [](const FMidiStreamEvent& Event) { return Event; }
Private Member Functions
void TrackNote (const FMidiStreamEvent &Event)
Private Attributes
TArray< FMidiStreamEvent > ActiveNotes
TWeakPtr< const FMidiClock, ESPMode::NotThreadSafe > Clock
TArray< FMidiStreamEvent > EventsInBlock
TMap< uint32, FMidiVoiceGeneratorBase > GeneratorMap
FMidiFileProxyPtr MidiFileSourceOfEvents
int32 TicksPerQuarterNote = Harmonix::Midi::Constants::GTicksPerQuarterNoteInt
Detailed Description
Definition at line 40 of file MidiStream.h.
Member Typedef Documentation
FEventFilter
using HarmonixMetasound::FMidiStream::FEventFilter = TFunction<bool(const FMidiStreamEvent&)>
Definition at line 66 of file MidiStream.h.
FEventTransformer
using HarmonixMetasound::FMidiStream::FEventTransformer = TFunction<FMidiStreamEvent(const FMidiStreamEvent&)>
Definition at line 69 of file MidiStream.h.
Member Function Documentation
AddMidiEvent()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::AddMidiEvent (const FMidiStreamEvent & Event)
References Event.
AddNoteOffEventOrCancelPendingNoteOn()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::AddNoteOffEventOrCancelPendingNoteOn (const FMidiStreamEvent & Event)
References Event.
Copy()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::Copy (const FMidiStream & From, FMidiStream & To, const FEventFilter & Filter = NoOpFilter, const FEventTransformer & Transformer = NoOpTransformer) static
References Filter, NoOpFilter, and NoOpTransformer.
GetClock()
HARMONIXMETASOUND_API TSharedPtr< const FMidiClock, ESPMode::NotThreadSafe > HarmonixMetasound::FMidiStream::GetClock () const
GetEventsInBlock()
const TArray< FMidiStreamEvent > & HarmonixMetasound::FMidiStream::GetEventsInBlock () const inline
Definition at line 58 of file MidiStream.h.
References EventsInBlock.
GetMidiTrackText()
HARMONIXMETASOUND_API const FString * HarmonixMetasound::FMidiStream::GetMidiTrackText (int32 TrackNumber, int32 TextIndex) const
GetTicksPerQuarterNote()
int32 HarmonixMetasound::FMidiStream::GetTicksPerQuarterNote () const inline
Definition at line 63 of file MidiStream.h.
References TicksPerQuarterNote.
InsertMidiEvent()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::InsertMidiEvent (const FMidiStreamEvent & Event)
References Event.
InsertNoteOffEventOrCancelPendingNoteOn()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::InsertNoteOffEventOrCancelPendingNoteOn (const FMidiStreamEvent & Event)
References Event.
Merge() [1/2]
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::Merge (const FMidiStream & From, FMidiStream & To, const FEventFilter & Filter = NoOpFilter, const FEventTransformer & Transformer = NoOpTransformer) static
References Filter, NoOpFilter, and NoOpTransformer.
Merge() [2/2]
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::Merge (const FMidiStream & FromA, const FMidiStream & FromB, FMidiStream & To, const FEventFilter & Filter = NoOpFilter, const FEventTransformer & Transformer = NoOpTransformer) static
References Filter, NoOpFilter, and NoOpTransformer.
NoteIsActive()
HARMONIXMETASOUND_API bool HarmonixMetasound::FMidiStream::NoteIsActive (const FMidiStreamEvent & Event) const
References Event.
PrepareBlock()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::PrepareBlock ()
ResetClock()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::ResetClock ()
SetClock()
HARMONIXMETASOUND_API void HarmonixMetasound::FMidiStream::SetClock (const FMidiClock & InClock)
SetMidiFile()
void HarmonixMetasound::FMidiStream::SetMidiFile (const FMidiFileProxyPtr & MidiFile) inline
Definition at line 54 of file MidiStream.h.
References MidiFileSourceOfEvents.
SetTicksPerQuarterNote()
void HarmonixMetasound::FMidiStream::SetTicksPerQuarterNote (int32 InTicksPerQuarterNote) inline
Definition at line 64 of file MidiStream.h.
References TicksPerQuarterNote.
TrackNote()
void HarmonixMetasound::FMidiStream::TrackNote (const FMidiStreamEvent & Event) private
References Event.
Field Documentation
ActiveNotes
TArray<FMidiStreamEvent> HarmonixMetasound::FMidiStream::ActiveNotes private
Definition at line 105 of file MidiStream.h.
Clock
TWeakPtr<const FMidiClock, ESPMode::NotThreadSafe> HarmonixMetasound::FMidiStream::Clock private
Definition at line 99 of file MidiStream.h.
EventsInBlock
TArray<FMidiStreamEvent> HarmonixMetasound::FMidiStream::EventsInBlock private
Definition at line 97 of file MidiStream.h.
Referenced by GetEventsInBlock().
GeneratorMap
TMap<uint32, FMidiVoiceGeneratorBase> HarmonixMetasound::FMidiStream::GeneratorMap private
Definition at line 102 of file MidiStream.h.
MidiFileSourceOfEvents
FMidiFileProxyPtr HarmonixMetasound::FMidiStream::MidiFileSourceOfEvents private
Definition at line 94 of file MidiStream.h.
Referenced by SetMidiFile().
NoOpFilter
const FEventFilter HarmonixMetasound::FMidiStream::NoOpFilter = [](const FMidiStreamEvent&) { return true; } inline static
Definition at line 67 of file MidiStream.h.
Referenced by Copy(), Merge(), and Merge().
NoOpTransformer
const FEventTransformer HarmonixMetasound::FMidiStream::NoOpTransformer = [](const FMidiStreamEvent& Event) { return Event; } inline static
Definition at line 70 of file MidiStream.h.
Referenced by Copy(), Merge(), and Merge().
TicksPerQuarterNote
int32 HarmonixMetasound::FMidiStream::TicksPerQuarterNote = Harmonix::Midi::Constants::GTicksPerQuarterNoteInt private
Definition at line 95 of file MidiStream.h.
Referenced by GetTicksPerQuarterNote(), and SetTicksPerQuarterNote().
The documentation for this class was generated from the following file:
MidiStream.h