Unreal Engine 5.6 C++ API: FScriptArray Class Reference
FScriptArray Class Reference
#include "ScriptArray.h"
Public Types
using IntrusiveUnsetOptionalStateType = FScriptArray
Public Types inherited from TScriptArray< FHeapAllocator >
using IntrusiveUnsetOptionalStateType
Public Member Functions
FScriptArray ()=default
FScriptArray (const FScriptArray &)
FScriptArray (FIntrusiveUnsetOptionalState Tag)
void MoveAssign (FScriptArray &Other, int32 NumBytesPerElement, uint32 AlignmentOfElement)
void operator= (const FScriptArray &)
Public Member Functions inherited from TScriptArray< FHeapAllocator >
TScriptArray ()
TScriptArray (const TScriptArray &)
TScriptArray (FIntrusiveUnsetOptionalState Tag)
int32 Add (int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
int32 AddZeroed (int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCEINLINE void CheckAddress (const void *Addr, int32 NumBytesPerElement) const
void CountBytes (FArchive &Ar, int32 NumBytesPerElement) const
void Empty (int32 Slack, int32 NumBytesPerElement, uint32 AlignmentOfElement)
SIZE_T GetAllocatedSize (int32 NumBytesPerElement) const
FORCEINLINE void * GetData ()
FORCEINLINE const void * GetData () const
FORCEINLINE int32 GetSlack () const
Returns the amount of slack in this array in elements.
void Insert (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
void InsertZeroed (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement)
bool IsEmpty () const
FORCEINLINE bool IsValidIndex (int32 i) const
void MoveAssign (TScriptArray &Other, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCEINLINE int32 Num () const
FORCEINLINE int32 NumUnchecked () const
void operator= (const TScriptArray &)
bool operator== (FIntrusiveUnsetOptionalState Tag) const
void Remove (int32 Index, int32 Count, int32 NumBytesPerElement, uint32 AlignmentOfElement, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void Reset (int32 NewSize, int32 NumBytesPerElement, uint32 AlignmentOfElement)
void SetNumUninitialized (int32 NewNum, int32 NumBytesPerElement, uint32 AlignmentOfElement, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void Shrink (int32 NumBytesPerElement, uint32 AlignmentOfElement)
void SwapMemory (int32 A, int32 B, int32 NumBytesPerElement)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Remove") FORCEINLINE void Remove(int32 Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized") FORCEINLINE void SetNumUninitialized(int32 NewNum
Protected Member Functions
FScriptArray (int32 InNum, int32 NumBytesPerElement, uint32 AlignmentOfElement)
Protected Member Functions inherited from TScriptArray< FHeapAllocator >
TScriptArray (int32 InNum, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeGrow (int32 OldNum, int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeInit (int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeShrink (int32 NumBytesPerElement, uint32 AlignmentOfElement)
FORCENOINLINE void ResizeTo (int32 NewMax, int32 NumBytesPerElement, uint32 AlignmentOfElement)
Private Types
using Super = TScriptArray<FHeapAllocator>
Additional Inherited Members
Data Fields inherited from TScriptArray< FHeapAllocator >
int32 uint32 AlignmentOfElement
int32 int32 uint32 AlignmentOfElement
int32 uint32 bool bAllowShrinking
int32 int32 uint32 bool bAllowShrinking
int32 Count
int32 NumBytesPerElement
int32 int32 NumBytesPerElement
Static Public Attributes inherited from TScriptArray< FHeapAllocator >
static constexpr bool bHasIntrusiveUnsetOptionalState
Protected Attributes inherited from TScriptArray< FHeapAllocator >
int32 ArrayMax
int32 ArrayNum
Detailed Description
Definition at line 322 of file ScriptArray.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
using FScriptArray::IntrusiveUnsetOptionalStateType = FScriptArray
Definition at line 344 of file ScriptArray.h.
Super
using FScriptArray::Super = TScriptArray<FHeapAllocator> private
Definition at line 324 of file ScriptArray.h.
Constructor & Destructor Documentation
FScriptArray() [1/4]
FScriptArray::FScriptArray () nodiscard default
Referenced by FScriptArray(), MoveAssign(), and operator=().
FScriptArray() [2/4]
FScriptArray::FScriptArray (int32 InNum, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline nodiscard protected
Definition at line 335 of file ScriptArray.h.
References TScriptArray< FHeapAllocator >::TScriptArray(), TScriptArray< FHeapAllocator >::AlignmentOfElement, and TScriptArray< FHeapAllocator >::NumBytesPerElement.
FScriptArray() [3/4]
FScriptArray::FScriptArray (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 345 of file ScriptArray.h.
References TScriptArray< FHeapAllocator >::TScriptArray().
FScriptArray() [4/4]
FScriptArray::FScriptArray (const FScriptArray &) inline nodiscard
Definition at line 355 of file ScriptArray.h.
References FScriptArray(), and check.
Member Function Documentation
MoveAssign()
void FScriptArray::MoveAssign (FScriptArray & Other, int32 NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 329 of file ScriptArray.h.
References FScriptArray(), TScriptArray< FHeapAllocator >::AlignmentOfElement, TScriptArray< FHeapAllocator >::MoveAssign(), TScriptArray< FHeapAllocator >::NumBytesPerElement, and Other.
operator=()
void FScriptArray::operator= (const FScriptArray &) inline
Definition at line 356 of file ScriptArray.h.
References FScriptArray(), and check.
The documentation for this class was generated from the following file:
ScriptArray.h