Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityRange< T > Struct Template Reference
UE::MovieScene::TEntityRange< T > Struct Template Reference
Variadic template representing a contiguous range of entities with a specific set of components.
#include "MovieSceneEntityRange.h"
Public Types
using PtrType = TEntityPtr<T...>
using Super = TEntityRangeImpl<TMakeIntegerSequence<int, sizeof...(T)>, T...>
Public Member Functions
TEntityRange ()
Default constructor - empty range.
TEntityRange (int32 InNum)
Constructor that initializes the size, but no component ptrs.
TEntityRange (int32 InNum, T *... InComponentArrays)
Constructor that initializes the size and components for this range.
TEntityPtr< T... > begin () const
TEntityPtr< T... > end () const
template<int32 ComponentTypeIndex>
auto GetAll () const
Get all the components for the templated index as a TArrayView.
template<int ComponentTypeIndex>
auto & GetComponent (int32 EntityIndex) const
Get the component from the templated component array index, using its index within this range.
template<int ComponentTypeIndex>
auto *& GetComponentArrayReference ()
Return a reference to the component array pointer at the specified index.
template<int ComponentTypeIndex>
auto * GetComponentOptional (int32 EntityIndex) const
Get a pointer to an entity's component from its templated component array index, using the entity's index within this range.
template<int ComponentTypeIndex>
auto * GetRawUnchecked () const
Retrieve the raw pointer to the (possibly nullptr) component array at the templated index.
int32 Num () const
Access the size of this range.
TEntityPtr< T... > operator[] (int32 Index) const
Access a specific entity within this range.
template<int ComponentTypeIndex, typename ValueType>
void SetComponent (int32 EntityIndex, ValueType &&InValue) const
Assign the value of an entity's component from its templated component array index, using the entity's index within this range.
Detailed Description
template<typename... T>
struct UE::MovieScene::TEntityRange< T >
Variadic template representing a contiguous range of entities with a specific set of components.
The template parameters define each component type by index, whose constness should match the read/write semantics of the accessor. For example, an entity with a float, int and bool component, accessed read-only should be represented by a TEntityRange<const float, const int const bool>. If one wished to write to all the float components, we would require a TEntityRange<float, const int, const bool> etc
Definition at line 28 of file MovieSceneEntityRange.h.
Member Typedef Documentation
PtrType
template<typename... T> using UE::MovieScene::TEntityRange< T >::PtrType = TEntityPtr<T...>
Definition at line 30 of file MovieSceneEntityRange.h.
Super
template<typename... T> using UE::MovieScene::TEntityRange< T >::Super = TEntityRangeImpl<TMakeIntegerSequence<int, sizeof...(T)>, T...>
Definition at line 31 of file MovieSceneEntityRange.h.
Constructor & Destructor Documentation
TEntityRange() [1/3]
template<typename... T> UE::MovieScene::TEntityRange< T >::TEntityRange () inline
Default constructor - empty range.
Definition at line 36 of file MovieSceneEntityRange.h.
TEntityRange() [2/3]
template<typename... T> UE::MovieScene::TEntityRange< T >::TEntityRange (int32 InNum) inline explicit
Constructor that initializes the size, but no component ptrs.
Subsequent calls to InitializeComponentArray should be made
Definition at line 44 of file MovieSceneEntityRange.h.
TEntityRange() [3/3]
template<typename... T> UE::MovieScene::TEntityRange< T >::TEntityRange (int32 InNum, T *... InComponentArrays) inline explicit
Constructor that initializes the size and components for this range.
Definition at line 52 of file MovieSceneEntityRange.h.
Member Function Documentation
begin()
template<typename... T> TEntityPtr< T... > UE::MovieScene::TEntityRange< T >::begin () const inline
Definition at line 159 of file MovieSceneEntityRange.h.
end()
template<typename... T> TEntityPtr< T... > UE::MovieScene::TEntityRange< T >::end () const inline
Definition at line 160 of file MovieSceneEntityRange.h.
References Num().
GetAll()
template<typename... T> template<int32 ComponentTypeIndex> auto UE::MovieScene::TEntityRange< T >::GetAll () const inline
Get all the components for the templated index as a TArrayView.
Returns
A TArrayView<T> for the component array at this index. T will be const for read-only components.
Definition at line 106 of file MovieSceneEntityRange.h.
References MakeArrayView().
GetComponent()
template<typename... T> template<int ComponentTypeIndex> auto & UE::MovieScene::TEntityRange< T >::GetComponent (int32 EntityIndex) const inline
Get the component from the templated component array index, using its index within this range.
Note
: will fail an assertion if this entity range does not contain this component type (eg Read/WriteOptional)
Parameters
EntityIndex The index of the entity within this range
Returns
A reference to the component matching the constness of the access-mode.
Definition at line 121 of file MovieSceneEntityRange.h.
References checkSlow.
GetComponentArrayReference()
template<typename... T> template<int ComponentTypeIndex> auto *& UE::MovieScene::TEntityRange< T >::GetComponentArrayReference () inline
Return a reference to the component array pointer at the specified index.
Should only be used for initialization
Definition at line 84 of file MovieSceneEntityRange.h.
GetComponentOptional()
template<typename... T> template<int ComponentTypeIndex> auto * UE::MovieScene::TEntityRange< T >::GetComponentOptional (int32 EntityIndex) const inline
Get a pointer to an entity's component from its templated component array index, using the entity's index within this range.
Parameters
EntityIndex The index of the entity within this range
Returns
A pointer to the component matching the constness of the access-mode, or nullptr if the component does not exist in this entity range.
Definition at line 136 of file MovieSceneEntityRange.h.
GetRawUnchecked()
template<typename... T> template<int ComponentTypeIndex> auto * UE::MovieScene::TEntityRange< T >::GetRawUnchecked () const inline
Retrieve the raw pointer to the (possibly nullptr) component array at the templated index.
Definition at line 94 of file MovieSceneEntityRange.h.
Num()
template<typename... T> int32 UE::MovieScene::TEntityRange< T >::Num () const inline
Access the size of this range.
Returns
The number of entities in this range
Definition at line 61 of file MovieSceneEntityRange.h.
Referenced by end().
operator[]()
template<typename... T> TEntityPtr< T... > UE::MovieScene::TEntityRange< T >::operator[] (int32 Index) const inline
Access a specific entity within this range.
Parameters
Index The index of the entity within this range
Returns
The entity with all its components
Definition at line 73 of file MovieSceneEntityRange.h.
References check.
SetComponent()
template<typename... T> template<int ComponentTypeIndex, typename ValueType> void UE::MovieScene::TEntityRange< T >::SetComponent (int32 EntityIndex, ValueType && InValue) const inline
Assign the value of an entity's component from its templated component array index, using the entity's index within this range.
Parameters
EntityIndex The index of the entity within this range
InValue The value to assign to the component
Definition at line 150 of file MovieSceneEntityRange.h.
References checkSlow, and Forward().
The documentation for this struct was generated from the following file:
MovieSceneEntityRange.h