Unreal Engine 5.6 C++ API: FShaderTypeDependency Class Reference
FShaderTypeDependency Class Reference
Encapsulates a dependency on a shader type and saved state from that shader type.
#include "Shader.h"
Public Member Functions
FShaderTypeDependency ()
FShaderTypeDependency (FShaderType *InShaderType, EShaderPlatform ShaderPlatform)
LAYOUT_FIELD (FHashedName, ShaderTypeName)
Shader type.
LAYOUT_FIELD (FSHAHash, SourceHash)
Used to detect changes to the shader source files.
LAYOUT_FIELD (int32, PermutationId)
Unique permutation identifier of the global shader type.
bool operator!= (const FShaderTypeDependency &Reference) const
bool operator== (const FShaderTypeDependency &Reference) const
RENDERCORE_API void RefreshCachedSourceHash (EShaderPlatform ShaderPlatform)
Call GetShaderFileHash to get the cached value for the filename's hash in the current process.
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderTypeDependency, RENDERCORE_API, NonVirtual)
RENDERCORE_API void Save (FCbWriter &Writer) const
bool TryLoad (FCbFieldView Field)
Friends
RENDERCORE_API bool LoadFromCompactBinary (FCbFieldView Field, FShaderTypeDependency &OutValue)
FArchive & operator<< (FArchive &Ar, class FShaderTypeDependency &Ref)
FCbWriter & operator<< (FCbWriter &Writer, const FShaderTypeDependency &Value)
Detailed Description
Encapsulates a dependency on a shader type and saved state from that shader type.
Definition at line 2069 of file Shader.h.
Constructor & Destructor Documentation
FShaderTypeDependency() [1/2]
FShaderTypeDependency::FShaderTypeDependency () inline
Definition at line 2074 of file Shader.h.
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT(), LoadFromCompactBinary, operator!=(), operator<<, operator<<, and operator==().
FShaderTypeDependency() [2/2]
FShaderTypeDependency::FShaderTypeDependency (FShaderType * InShaderType, EShaderPlatform ShaderPlatform) inline
Definition at line 2078 of file Shader.h.
References FShaderType::GetSourceHash(), and ShaderPlatform.
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderTypeDependency::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderTypeDependency , RENDERCORE_API , NonVirtual) private
References FShaderTypeDependency().
LAYOUT_FIELD() [1/3]
FShaderTypeDependency::LAYOUT_FIELD (FHashedName , ShaderTypeName)
Shader type.
LAYOUT_FIELD() [2/3]
FShaderTypeDependency::LAYOUT_FIELD (FSHAHash , SourceHash)
Used to detect changes to the shader source files.
This is always present, as this type is sometimes frozen.
LAYOUT_FIELD() [3/3]
FShaderTypeDependency::LAYOUT_FIELD (int32 , PermutationId)
Unique permutation identifier of the global shader type.
operator!=()
bool FShaderTypeDependency::operator!= (const FShaderTypeDependency & Reference) const inline
Definition at line 2108 of file Shader.h.
References FShaderTypeDependency().
operator==()
bool FShaderTypeDependency::operator== (const FShaderTypeDependency & Reference) const inline
Definition at line 2103 of file Shader.h.
References FShaderTypeDependency().
RefreshCachedSourceHash()
RENDERCORE_API void FShaderTypeDependency::RefreshCachedSourceHash (EShaderPlatform ShaderPlatform)
Call GetShaderFileHash to get the cached value for the filename's hash in the current process.
References ShaderPlatform.
Save()
RENDERCORE_API void FShaderTypeDependency::Save (FCbWriter & Writer) const private
TryLoad()
bool FShaderTypeDependency::TryLoad (FCbFieldView Field) private
Friends And Related Symbol Documentation
LoadFromCompactBinary
RENDERCORE_API bool LoadFromCompactBinary (FCbFieldView Field, FShaderTypeDependency & OutValue) friend
References FShaderTypeDependency().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, class FShaderTypeDependency & Ref) friend
Definition at line 2088 of file Shader.h.
References FShaderTypeDependency(), Ar, FRenderingObjectVersion::GUID, and FRenderingObjectVersion::ShaderPermutationId.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FShaderTypeDependency & Value) friend
Definition at line 2130 of file Shader.h.
References FShaderTypeDependency(), and Value.
The documentation for this class was generated from the following file:
Shader.h