Unreal Engine 5.6 C++ API: FDebugLineItem Class Reference
FDebugLineItem Class Reference abstract
#include "SKismetDebugTreeView.h"
Public Types
enum EDebugLineType {
DLT_Message , DLT_TraceStackParent , DLT_TraceStackChild , DLT_Parent ,
DLT_SelfWatch , DLT_Watch , DLT_WatchChild , DLT_LatentAction ,
DLT_Breakpoint , DLT_BreakpointParent
}
enum ESearchFlags { SF_None = 0 , SF_RootNode = 1 << 0 , SF_ContainerElement = 1 << 1 }
Public Member Functions
virtual ~FDebugLineItem ()
virtual bool CanHaveChildren ()
bool DoParentsMatchSearch ()
virtual void ExtendContextMenu (class FMenuBuilder &MenuBuilder, bool bInDebuggerTab)
virtual void GatherChildrenBase (TArray< FDebugTreeItemPtr > &OutChildren, const FString &InSearchString, bool bRespectSearch=true)
virtual TSharedRef< SWidget > GenerateNameWidget (TSharedPtr< FString > InSearchString)
virtual TSharedRef< SWidget > GenerateValueWidget (TSharedPtr< FString > InSearchString)
virtual FText GetDescription () const
FText GetHighlightText (const TSharedPtr< FString > InSearchString) const
virtual TSharedRef< SWidget > GetNameIcon ()
virtual UObject * GetParentObject () const
virtual EDebugLineType GetType () const
virtual TSharedRef< SWidget > GetValueIcon ()
virtual bool HasChildren () const
bool IsVisible ()
void MakeMenu (class FMenuBuilder &MenuBuilder, bool bInDebuggerTab)
void UpdateSearch (const FString &InSearchString, ESearchFlags SearchFlags)
Public Member Functions inherited from TSharedFromThis< FDebugLineItem >
TSharedRef< FDebugLineItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDebugLineItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static UBlueprint * GetBlueprintForObject (UObject *ParentObject)
static UBlueprintGeneratedClass * GetClassForObject (UObject *ParentObject)
static bool IsDebugLineTypeActive (EDebugLineType Type)
static void OnDebugLineTypeActiveChanged (ECheckBoxState CheckState, EDebugLineType Type)
static void SetBreakpointParentItemBlueprint (FDebugTreeItemPtr InBreakpointParentItem, TWeakObjectPtr< UBlueprint > InBlueprint)
Protected Member Functions
FDebugLineItem (EDebugLineType InType)
virtual bool Compare (const FDebugLineItem *Other) const =0
void CopyNameToClipboard () const
void CopyValueToClipboard () const
virtual FDebugLineItem * Duplicate () const =0
virtual FText GetDisplayName () const
virtual uint32 GetHash () const =0
virtual FText GetName () const
bool HasName () const
bool HasValue () const
virtual void UpdateData (const FDebugLineItem &NewerData)
Protected Member Functions inherited from TSharedFromThis< FDebugLineItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bParentsMatchSearch = false
bool bVisible = false
EDebugLineType Type
Static Protected Attributes
static uint16 ActiveTypeBitset
Friends
class FLineItemWithChildren
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FDebugLineItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 54 of file SKismetDebugTreeView.h.
Member Enumeration Documentation
EDebugLineType
enum FDebugLineItem::EDebugLineType
Enumerator
DLT_Message
DLT_TraceStackParent
DLT_TraceStackChild
DLT_Parent
DLT_SelfWatch
DLT_Watch
DLT_WatchChild
DLT_LatentAction
DLT_Breakpoint
DLT_BreakpointParent
Definition at line 58 of file SKismetDebugTreeView.h.
ESearchFlags
enum FDebugLineItem::ESearchFlags
Enumerator
SF_None
SF_RootNode
SF_ContainerElement
Definition at line 72 of file SKismetDebugTreeView.h.
Constructor & Destructor Documentation
~FDebugLineItem()
virtual FDebugLineItem::~FDebugLineItem () inline virtual
Definition at line 79 of file SKismetDebugTreeView.h.
FDebugLineItem()
FDebugLineItem::FDebugLineItem (EDebugLineType InType) inline protected
Definition at line 143 of file SKismetDebugTreeView.h.
References Type.
Referenced by Compare(), Duplicate(), and UpdateData().
Member Function Documentation
CanHaveChildren()
virtual bool FDebugLineItem::CanHaveChildren () inline virtual
Definition at line 100 of file SKismetDebugTreeView.h.
Compare()
virtual bool FDebugLineItem::Compare (const FDebugLineItem * Other) const protected pure virtual
References FDebugLineItem(), and Other.
CopyNameToClipboard()
void FDebugLineItem::CopyNameToClipboard () const protected
CopyValueToClipboard()
void FDebugLineItem::CopyValueToClipboard () const protected
DoParentsMatchSearch()
bool FDebugLineItem::DoParentsMatchSearch ()
Duplicate()
virtual FDebugLineItem * FDebugLineItem::Duplicate () const protected pure virtual
References FDebugLineItem().
ExtendContextMenu()
virtual void FDebugLineItem::ExtendContextMenu (class FMenuBuilder & MenuBuilder, bool bInDebuggerTab) virtual
GatherChildrenBase()
virtual void FDebugLineItem::GatherChildrenBase (TArray< FDebugTreeItemPtr > & OutChildren, const FString & InSearchString, bool bRespectSearch = true) inline virtual
Definition at line 94 of file SKismetDebugTreeView.h.
GenerateNameWidget()
virtual TSharedRef< SWidget > FDebugLineItem::GenerateNameWidget (TSharedPtr< FString > InSearchString) virtual
GenerateValueWidget()
virtual TSharedRef< SWidget > FDebugLineItem::GenerateValueWidget (TSharedPtr< FString > InSearchString) virtual
GetBlueprintForObject()
UBlueprint * FDebugLineItem::GetBlueprintForObject (UObject * ParentObject) static
GetClassForObject()
UBlueprintGeneratedClass * FDebugLineItem::GetClassForObject (UObject * ParentObject) static
GetDescription()
virtual FText FDebugLineItem::GetDescription () const virtual
GetDisplayName()
virtual FText FDebugLineItem::GetDisplayName () const protected virtual
GetHash()
virtual uint32 FDebugLineItem::GetHash () const protected pure virtual
GetHighlightText()
FText FDebugLineItem::GetHighlightText (const TSharedPtr< FString > InSearchString) const
GetName()
virtual FText FDebugLineItem::GetName () const protected virtual
GetNameIcon()
virtual TSharedRef< SWidget > FDebugLineItem::GetNameIcon () virtual
GetParentObject()
virtual UObject * FDebugLineItem::GetParentObject () const inline virtual
Definition at line 103 of file SKismetDebugTreeView.h.
GetType()
virtual EDebugLineType FDebugLineItem::GetType () const inline virtual
Definition at line 105 of file SKismetDebugTreeView.h.
References Type.
GetValueIcon()
virtual TSharedRef< SWidget > FDebugLineItem::GetValueIcon () virtual
HasChildren()
virtual bool FDebugLineItem::HasChildren () const virtual
HasName()
bool FDebugLineItem::HasName () const protected
HasValue()
bool FDebugLineItem::HasValue () const protected
IsDebugLineTypeActive()
bool FDebugLineItem::IsDebugLineTypeActive (EDebugLineType Type) static
References Type.
IsVisible()
bool FDebugLineItem::IsVisible ()
MakeMenu()
void FDebugLineItem::MakeMenu (class FMenuBuilder & MenuBuilder, bool bInDebuggerTab)
OnDebugLineTypeActiveChanged()
void FDebugLineItem::OnDebugLineTypeActiveChanged (ECheckBoxState CheckState, EDebugLineType Type) static
References Type.
SetBreakpointParentItemBlueprint()
void FDebugLineItem::SetBreakpointParentItemBlueprint (FDebugTreeItemPtr InBreakpointParentItem, TWeakObjectPtr< UBlueprint > InBlueprint) static
UpdateData()
virtual void FDebugLineItem::UpdateData (const FDebugLineItem & NewerData) inline protected virtual
Definition at line 159 of file SKismetDebugTreeView.h.
References FDebugLineItem().
UpdateSearch()
void FDebugLineItem::UpdateSearch (const FString & InSearchString, ESearchFlags SearchFlags)
Friends And Related Symbol Documentation
FLineItemWithChildren
friend class FLineItemWithChildren friend
Definition at line 57 of file SKismetDebugTreeView.h.
References FLineItemWithChildren.
Referenced by FLineItemWithChildren.
Field Documentation
ActiveTypeBitset
uint16 FDebugLineItem::ActiveTypeBitset static protected
Definition at line 176 of file SKismetDebugTreeView.h.
bParentsMatchSearch
bool FDebugLineItem::bParentsMatchSearch = false protected
Definition at line 181 of file SKismetDebugTreeView.h.
bVisible
bool FDebugLineItem::bVisible = false protected
Definition at line 179 of file SKismetDebugTreeView.h.
Type
EDebugLineType FDebugLineItem::Type protected
Definition at line 174 of file SKismetDebugTreeView.h.
Referenced by FDebugLineItem(), GetType(), IsDebugLineTypeActive(), and OnDebugLineTypeActiveChanged().
The documentation for this class was generated from the following file:
SKismetDebugTreeView.h