Unreal Engine 5.6 C++ API: DrawDebugHelpers.h File Reference
DrawDebugHelpers.h File Reference
#include "CoreMinimal.h"
#include "Engine/EngineTypes.h"
#include "EngineDefines.h"
Macros
#define ENABLE_DRAW_DEBUG UE_ENABLE_DEBUG_DRAWING
Functions
void DrawCentripetalCatmullRomSpline (const UWorld *InWorld, TConstArrayView< FVector > Points, FColor const &Color, float Alpha=0.5f, int32 NumSamplesPerSegment=8, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a centripetal catmull rom spline.
void DrawCentripetalCatmullRomSpline (const UWorld *InWorld, TConstArrayView< FVector > Points, TConstArrayView< FColor > Colors, float Alpha=0.5f, int32 NumSamplesPerSegment=8, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
void DrawCircle (const UWorld *InWorld, const FVector &Base, const FVector &X, const FVector &Y, const FColor &Color, float Radius, int32 NumSides, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0)
Draw a circle using user define axis and radius.
void DrawDebug2DDonut (const UWorld *InWorld, const FMatrix &TransformMatrix, float InnerRadius, float OuterRadius, int32 Segments, const FColor &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw Debug 2D donut.
void DrawDebugAltCone (const UWorld *InWorld, FVector const &Origin, FRotator const &Rotation, float Length, float AngleWidth, float AngleHeight, FColor const &DrawColor, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Used by gameplay when defining a cone by a vertical and horizontal dot products.
void DrawDebugBox (const UWorld *InWorld, FVector const &Center, FVector const &Extent, const FQuat &Rotation, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a debug box with rotation.
void DrawDebugBox (const UWorld *InWorld, FVector const &Center, FVector const &Extent, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a debug box.
void DrawDebugCamera (const UWorld *InWorld, FVector const &Location, FRotator const &Rotation, float FOVDeg, float Scale=1.f, FColor const &Color=FColor::White, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0)
Draw a debug camera shape.
void DrawDebugCanvas2DBox (UCanvas *Canvas, const FBox2D &Box, const FLinearColor &LineColor, const float &LineThickness=1.f)
void DrawDebugCanvas2DCircle (UCanvas *Canvas, const FVector2D &Center, float Radius, int32 NumSides, const FLinearColor &LineColor, const float &LineThickness=1.f)
void DrawDebugCanvas2DLine (UCanvas *Canvas, const FVector &Start, const FVector &End, const FLinearColor &LineColor)
Draws a 2D line on a canvas.
void DrawDebugCanvas2DLine (UCanvas *Canvas, const FVector2D &StartPosition, const FVector2D &EndPosition, const FLinearColor &LineColor, const float &LineThickness=1.f)
void DrawDebugCanvasCapsule (UCanvas *Canvas, const FMatrix &Transform, float HalfLength, float Radius, const FColor &LineColor)
Draws a capsule using lines.
void DrawDebugCanvasCircle (UCanvas *Canvas, const FVector &Base, const FVector &X, const FVector &Y, FColor Color, float Radius, int32 NumSides)
Draws a circle using lines.
void DrawDebugCanvasHalfCircle (UCanvas *Canvas, const FVector &Base, const FVector &X, const FVector &Y, FColor Color, float Radius, int32 NumSides)
Draws a half circle using lines.
void DrawDebugCanvasLine (UCanvas *Canvas, const FVector &Start, const FVector &End, const FLinearColor &LineColor)
Draws a line on a canvas.
void DrawDebugCanvasWireBox (UCanvas *Canvas, const FMatrix &Transform, const FBox &Box, FColor Color)
Draws a box using lines.
void DrawDebugCanvasWireCone (UCanvas *Canvas, const FTransform &Transform, float ConeRadius, float ConeAngle, int32 ConeSides, FColor Color)
Draws a wireframe cone.
void DrawDebugCanvasWireSphere (UCanvas *Canvas, const FVector &Base, FColor Color, float Radius, int32 NumSides)
Draws a sphere using circles.
void DrawDebugCapsule (const UWorld *InWorld, FVector const &Center, float HalfHeight, float Radius, const FQuat &Rotation, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0)
Draw a capsule using the LineBatcher.
void DrawDebugCircle (const UWorld *InWorld, const FMatrix &TransformMatrix, float Radius, int32 Segments, const FColor &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f, bool bDrawAxis=true)
Draw Debug Circle.
void DrawDebugCircle (const UWorld *InWorld, FVector Center, float Radius, int32 Segments, const FColor &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f, FVector YAxis=FVector(0.f, 1.f, 0.f), FVector ZAxis=FVector(0.f, 0.f, 1.f), bool bDrawAxis=true)
Draw Debug Circle.
void DrawDebugCircleArc (const UWorld *InWorld, const FVector &Center, float Radius, const FVector &Direction, float AngleWidth, int32 Segments, const FColor &Color, bool PersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw Debug Circle Arc.
void DrawDebugCone (const UWorld *InWorld, FVector const &Origin, FVector const &Direction, float Length, float AngleWidth, float AngleHeight, int32 NumSides, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a debug cone.
void DrawDebugCoordinateSystem (const UWorld *InWorld, FVector const &AxisLoc, FRotator const &AxisRot, float Scale, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw Debug coordinate system.
void DrawDebugCrosshairs (const UWorld *InWorld, FVector const &AxisLoc, FRotator const &AxisRot, float Scale, const FColor &Color=FColor::White, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0)
Draw Debug crosshair.
void DrawDebugCylinder (const UWorld *InWorld, FVector const &Start, FVector const &End, float Radius, int32 Segments, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a debug cylinder.
void DrawDebugDirectionalArrow (const UWorld *InWorld, FVector const &LineStart, FVector const &LineEnd, float ArrowSize, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw directional arrow.
void DrawDebugFloatHistory (UWorld const &WorldRef, FDebugFloatHistory const &FloatHistory, FTransform const &DrawTransform, FVector2D const &DrawSize, FColor const &DrawColor, bool const &bPersistent=false, float const &LifeTime=-1.f, uint8 const &DepthPriority=0)
void DrawDebugFloatHistory (UWorld const &WorldRef, FDebugFloatHistory const &FloatHistory, FVector const &DrawLocation, FVector2D const &DrawSize, FColor const &DrawColor, bool const &bPersistent=false, float const &LifeTime=-1.f, uint8 const &DepthPriority=0)
void DrawDebugFrustum (const UWorld *InWorld, const FMatrix &FrustumToWorld, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
void DrawDebugLine (const UWorld *InWorld, FVector const &LineStart, FVector const &LineEnd, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a debug line.
void DrawDebugMesh (const UWorld *InWorld, TArray< FVector > const &Verts, TArray< int32 > const &Indices, FColor const &Color, bool bPersistent=false, float LifeTime=-1.f, uint8 DepthPriority=0)
void DrawDebugPoint (const UWorld *InWorld, FVector const &Position, float Size, FColor const &PointColor, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0)
Draw a debug point.
void DrawDebugSolidBox (const UWorld *InWorld, FBox const &Box, FColor const &Color, const FTransform &Transform=FTransform::Identity, bool bPersistent=false, float LifeTime=-1.f, uint8 DepthPriority=0)
Draw a solid box.
void DrawDebugSolidBox (const UWorld *InWorld, FVector const &Center, FVector const &Extent, FColor const &Color, bool bPersistent=false, float LifeTime=-1.f, uint8 DepthPriority=0)
Draw a Debug box from (Center, Extent) with no rotation (axis-aligned)
void DrawDebugSolidBox (const UWorld *InWorld, FVector const &Center, FVector const &Extent, FQuat const &Rotation, FColor const &Color, bool bPersistent=false, float LifeTime=-1.f, uint8 DepthPriority=0)
Draw a Debug box from (Center, Extent) with specified Rotation.
void DrawDebugSolidPlane (const UWorld *InWorld, FPlane const &P, FVector const &Loc, float Size, FColor const &Color, bool bPersistent=false, float LifeTime=-1, uint8 DepthPriority=0)
void DrawDebugSolidPlane (const UWorld *InWorld, FPlane const &P, FVector const &Loc, FVector2D const &Extents, FColor const &Color, bool bPersistent=false, float LifeTime=-1, uint8 DepthPriority=0)
void DrawDebugSphere (const UWorld *InWorld, FVector const &Center, float Radius, int32 Segments, FColor const &Color, bool bPersistentLines=false, float LifeTime=-1.f, uint8 DepthPriority=0, float Thickness=0.f)
Draw a debug sphere.
void DrawDebugString (const UWorld *InWorld, FVector const &TextLocation, const FString &Text, class AActor *TestBaseActor=NULL, FColor const &TextColor=FColor::White, float Duration=-1.000000, bool bDrawShadow=false, float FontScale=1.f)
void FlushDebugStrings (const UWorld *InWorld)
void FlushPersistentDebugLines (const UWorld *InWorld)
Flush persistent lines.
Macro Definition Documentation
ENABLE_DRAW_DEBUG
#define ENABLE_DRAW_DEBUG UE_ENABLE_DEBUG_DRAWING
Definition at line 14 of file DrawDebugHelpers.h.
Function Documentation
DrawCentripetalCatmullRomSpline() [1/2]
void DrawCentripetalCatmullRomSpline (const UWorld * InWorld, TConstArrayView< FVector > Points, FColor const & Color, float Alpha = 0.5f, int32 NumSamplesPerSegment = 8, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a centripetal catmull rom spline.
Alpha values between 0 and 1
References Alpha, Color, and Points.
DrawCentripetalCatmullRomSpline() [2/2]
void DrawCentripetalCatmullRomSpline (const UWorld * InWorld, TConstArrayView< FVector > Points, TConstArrayView< FColor > Colors, float Alpha = 0.5f, int32 NumSamplesPerSegment = 8, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
References Alpha, and Points.
DrawCircle()
void DrawCircle (const UWorld * InWorld, const FVector & Base, const FVector & X, const FVector & Y, const FColor & Color, float Radius, int32 NumSides, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0)
Draw a circle using user define axis and radius.
References Color, FVector, X, and Y.
DrawDebug2DDonut()
void DrawDebug2DDonut (const UWorld * InWorld, const FMatrix & TransformMatrix, float InnerRadius, float OuterRadius, int32 Segments, const FColor & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw Debug 2D donut.
References Color.
DrawDebugAltCone()
void DrawDebugAltCone (const UWorld * InWorld, FVector const & Origin, FRotator const & Rotation, float Length, float AngleWidth, float AngleHeight, FColor const & DrawColor, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Used by gameplay when defining a cone by a vertical and horizontal dot products.
References FVector, Origin, and Rotation.
DrawDebugBox() [1/2]
void DrawDebugBox (const UWorld * InWorld, FVector const & Center, FVector const & Extent, const FQuat & Rotation, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a debug box with rotation.
References Color, FVector, and Rotation.
DrawDebugBox() [2/2]
void DrawDebugBox (const UWorld * InWorld, FVector const & Center, FVector const & Extent, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a debug box.
References Color, and FVector.
Referenced by UCLASS().
DrawDebugCamera()
void DrawDebugCamera (const UWorld * InWorld, FVector const & Location, FRotator const & Rotation, float FOVDeg, float Scale = 1.f, FColor const & Color = FColor::White, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
Draw a debug camera shape.
FOV is full angle in degrees.
References Color, FVector, Location, Rotation, Scale, and FColor::White.
Referenced by UCLASS().
DrawDebugCanvas2DBox()
void DrawDebugCanvas2DBox (UCanvas * Canvas, const FBox2D & Box, const FLinearColor & LineColor, const float & LineThickness = 1.f)
References Box.
DrawDebugCanvas2DCircle()
void DrawDebugCanvas2DCircle (UCanvas * Canvas, const FVector2D & Center, float Radius, int32 NumSides, const FLinearColor & LineColor, const float & LineThickness = 1.f)
DrawDebugCanvas2DLine() [1/2]
void DrawDebugCanvas2DLine (UCanvas * Canvas, const FVector & Start, const FVector & End, const FLinearColor & LineColor)
Draws a 2D line on a canvas.
Parameters
Canvas The Canvas to draw on
Start The start of the line in screen space
End The end of the line in screen space
LineColor The color to use for the line
References End, and FVector.
DrawDebugCanvas2DLine() [2/2]
void DrawDebugCanvas2DLine (UCanvas * Canvas, const FVector2D & StartPosition, const FVector2D & EndPosition, const FLinearColor & LineColor, const float & LineThickness = 1.f)
DrawDebugCanvasCapsule()
void DrawDebugCanvasCapsule (UCanvas * Canvas, const FMatrix & Transform, float HalfLength, float Radius, const FColor & LineColor)
Draws a capsule using lines.
Parameters
Canvas The Canvas to draw on.
Transform Transform to apply to the capsule.
HalfLength Distance from the center of the capsule to the tip (including the cap)
Radius Radius of the capsule.
Color Color of the capsule.
References FORCEINLINE, and Transform.
DrawDebugCanvasCircle()
void DrawDebugCanvasCircle (UCanvas * Canvas, const FVector & Base, const FVector & X, const FVector & Y, FColor Color, float Radius, int32 NumSides)
Draws a circle using lines.
Parameters
Canvas The Canvas to draw on.
Base Center of the circle.
X X alignment axis to draw along.
Y Y alignment axis to draw along.
Color Color of the circle.
Radius Radius of the circle.
NumSides Numbers of sides that the circle has.
References Color, FVector, X, and Y.
DrawDebugCanvasHalfCircle()
void DrawDebugCanvasHalfCircle (UCanvas * Canvas, const FVector & Base, const FVector & X, const FVector & Y, FColor Color, float Radius, int32 NumSides)
Draws a half circle using lines.
Parameters
Canvas The Canvas to draw on.
Base Center of the circle.
X X alignment axis to draw along.
Y Y alignment axis to draw along.
Color Color of the circle.
Radius Radius of the circle.
NumSides Numbers of sides that the circle has.
References Color, FVector, X, and Y.
DrawDebugCanvasLine()
void DrawDebugCanvasLine (UCanvas * Canvas, const FVector & Start, const FVector & End, const FLinearColor & LineColor)
Draws a line on a canvas.
Parameters
Canvas The Canvas to draw on.
Start The start of the line in world space
End The end of the line in world space
LineColor The color to use for the line
References End, and FVector.
DrawDebugCanvasWireBox()
void DrawDebugCanvasWireBox (UCanvas * Canvas, const FMatrix & Transform, const FBox & Box, FColor Color)
Draws a box using lines.
Parameters
Canvas The Canvas to draw on.
Transform Transform to apply to the capsule.
Box The box to be drawn.
Color Color of the capsule.
References Box, Color, and Transform.
DrawDebugCanvasWireCone()
void DrawDebugCanvasWireCone (UCanvas * Canvas, const FTransform & Transform, float ConeRadius, float ConeAngle, int32 ConeSides, FColor Color)
Draws a wireframe cone.
Parameters
Canvas Canvas to draw on
Transform Generic transform to apply (ex. a local-to-world transform).
ConeRadius Radius of the cone.
ConeAngle Angle of the cone.
ConeSides Numbers of sides that the cone has.
Color Color of the cone.
References Color, and Transform.
DrawDebugCanvasWireSphere()
void DrawDebugCanvasWireSphere (UCanvas * Canvas, const FVector & Base, FColor Color, float Radius, int32 NumSides)
Draws a sphere using circles.
Parameters
Canvas The Canvas to draw on.
Base Center of the sphere.
Color Color of the sphere.
Radius Radius of the sphere.
NumSides Numbers of sides that the circle has.
References Color, and FVector.
DrawDebugCapsule()
void DrawDebugCapsule (const UWorld * InWorld, FVector const & Center, float HalfHeight, float Radius, const FQuat & Rotation, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0)
Draw a capsule using the LineBatcher.
References Color, FVector, and Rotation.
Referenced by UCLASS().
DrawDebugCircle() [1/2]
void DrawDebugCircle (const UWorld * InWorld, const FMatrix & TransformMatrix, float Radius, int32 Segments, const FColor & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f, bool bDrawAxis = true)
Draw Debug Circle.
References Color.
Referenced by UCLASS().
DrawDebugCircle() [2/2]
void DrawDebugCircle (const UWorld * InWorld, FVector Center, float Radius, int32 Segments, const FColor & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f, FVector YAxis = FVector(0.f, 1.f, 0.f), FVector ZAxis = FVector(0.f, 0.f, 1.f), bool bDrawAxis = true)
Draw Debug Circle.
References Color, and FVector.
DrawDebugCircleArc()
void DrawDebugCircleArc (const UWorld * InWorld, const FVector & Center, float Radius, const FVector & Direction, float AngleWidth, int32 Segments, const FColor & Color, bool PersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw Debug Circle Arc.
References Color, and FVector.
DrawDebugCone()
void DrawDebugCone (const UWorld * InWorld, FVector const & Origin, FVector const & Direction, float Length, float AngleWidth, float AngleHeight, int32 NumSides, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a debug cone.
AngleWidth and AngleHeight are given in radians
References Color, FVector, and Origin.
Referenced by UCLASS().
DrawDebugCoordinateSystem()
void DrawDebugCoordinateSystem (const UWorld * InWorld, FVector const & AxisLoc, FRotator const & AxisRot, float Scale, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw Debug coordinate system.
References FVector, and Scale.
Referenced by UCLASS().
DrawDebugCrosshairs()
void DrawDebugCrosshairs (const UWorld * InWorld, FVector const & AxisLoc, FRotator const & AxisRot, float Scale, const FColor & Color = FColor::White, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
Draw Debug crosshair.
References Color, FVector, Scale, and FColor::White.
DrawDebugCylinder()
void DrawDebugCylinder (const UWorld * InWorld, FVector const & Start, FVector const & End, float Radius, int32 Segments, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a debug cylinder.
References Color, End, and FVector.
Referenced by UCLASS().
DrawDebugDirectionalArrow()
void DrawDebugDirectionalArrow (const UWorld * InWorld, FVector const & LineStart, FVector const & LineEnd, float ArrowSize, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw directional arrow.
References Color, and FVector.
DrawDebugFloatHistory() [1/2]
void DrawDebugFloatHistory (UWorld const & WorldRef, FDebugFloatHistory const & FloatHistory, FTransform const & DrawTransform, FVector2D const & DrawSize, FColor const & DrawColor, bool const & bPersistent = false, float const & LifeTime = -1.f, uint8 const & DepthPriority = 0)
DrawDebugFloatHistory() [2/2]
void DrawDebugFloatHistory (UWorld const & WorldRef, FDebugFloatHistory const & FloatHistory, FVector const & DrawLocation, FVector2D const & DrawSize, FColor const & DrawColor, bool const & bPersistent = false, float const & LifeTime = -1.f, uint8 const & DepthPriority = 0)
References FVector.
DrawDebugFrustum()
void DrawDebugFrustum (const UWorld * InWorld, const FMatrix & FrustumToWorld, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
References Color.
Referenced by UCLASS().
DrawDebugLine()
void DrawDebugLine (const UWorld * InWorld, FVector const & LineStart, FVector const & LineEnd, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a debug line.
References Color, and FVector.
Referenced by UCLASS().
DrawDebugMesh()
void DrawDebugMesh (const UWorld * InWorld, TArray< FVector > const & Verts, TArray< int32 > const & Indices, FColor const & Color, bool bPersistent = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
References Color.
DrawDebugPoint()
void DrawDebugPoint (const UWorld * InWorld, FVector const & Position, float Size, FColor const & PointColor, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
Draw a debug point.
References FVector, Position, and TSequenceHistory< HistorySize >::Size.
Referenced by UCLASS().
DrawDebugSolidBox() [1/3]
void DrawDebugSolidBox (const UWorld * InWorld, FBox const & Box, FColor const & Color, const FTransform & Transform = FTransform::Identity, bool bPersistent = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
Draw a solid box.
Various API's provided for convenience, including ones that use FBox as well as ones that prefer (Center, Extent). Draw a Debug box with optional transform.
References Box, Color, UE::Math::TTransform< double >::Identity, and Transform.
DrawDebugSolidBox() [2/3]
void DrawDebugSolidBox (const UWorld * InWorld, FVector const & Center, FVector const & Extent, FColor const & Color, bool bPersistent = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
Draw a Debug box from (Center, Extent) with no rotation (axis-aligned)
References Color, and FVector.
DrawDebugSolidBox() [3/3]
void DrawDebugSolidBox (const UWorld * InWorld, FVector const & Center, FVector const & Extent, FQuat const & Rotation, FColor const & Color, bool bPersistent = false, float LifeTime = -1.f, uint8 DepthPriority = 0)
Draw a Debug box from (Center, Extent) with specified Rotation.
References Color, FVector, and Rotation.
DrawDebugSolidPlane() [1/2]
void DrawDebugSolidPlane (const UWorld * InWorld, FPlane const & P, FVector const & Loc, float Size, FColor const & Color, bool bPersistent = false, float LifeTime = -1, uint8 DepthPriority = 0)
References Color, FVector, and TSequenceHistory< HistorySize >::Size.
DrawDebugSolidPlane() [2/2]
void DrawDebugSolidPlane (const UWorld * InWorld, FPlane const & P, FVector const & Loc, FVector2D const & Extents, FColor const & Color, bool bPersistent = false, float LifeTime = -1, uint8 DepthPriority = 0)
References Color, and FVector.
DrawDebugSphere()
void DrawDebugSphere (const UWorld * InWorld, FVector const & Center, float Radius, int32 Segments, FColor const & Color, bool bPersistentLines = false, float LifeTime = -1.f, uint8 DepthPriority = 0, float Thickness = 0.f)
Draw a debug sphere.
References Color, and FVector.
Referenced by UCLASS().
DrawDebugString()
void DrawDebugString (const UWorld * InWorld, FVector const & TextLocation, const FString & Text, class AActor * TestBaseActor = NULL, FColor const & TextColor = FColor::White, float Duration = -1.000000, bool bDrawShadow = false, float FontScale = 1.f)
References Duration, FVector, Text, and FColor::White.
Referenced by UCLASS().
FlushDebugStrings()
void FlushDebugStrings (const UWorld * InWorld)
Referenced by UCLASS().
FlushPersistentDebugLines()
void FlushPersistentDebugLines (const UWorld * InWorld)
Flush persistent lines.
Referenced by UCLASS().