Unreal Engine 5.6 C++ API: FMovieScenePropertyTrackEntityImportHelper Struct Reference
FMovieScenePropertyTrackEntityImportHelper Struct Reference
Base class for tracks that animate an object property.
#include "MovieScenePropertyTrack.h"
Static Public Member Functions
static MOVIESCENETRACKS_API void ImportEditConditionToggleEntity (const UE::MovieScene::FEntityImportParams &Params, UE::MovieScene::FImportedEntity *OutImportedEntity)
static MOVIESCENETRACKS_API bool IsEditConditionToggleID (const UE::MovieScene::FEntityImportParams &Params)
static MOVIESCENETRACKS_API bool IsPropertyValueID (const UE::MovieScene::FEntityImportParams &Params)
static MOVIESCENETRACKS_API void PopulateEvaluationField (UMovieSceneSection &Section, const TRange< FFrameNumber > &EffectiveRange, const FMovieSceneEvaluationFieldEntityMetaData &InMetaData, FMovieSceneEntityComponentFieldBuilder *OutFieldBuilder)
static MOVIESCENETRACKS_API FName SanitizeBoolPropertyName (FName InPropertyName)
Static Public Attributes
static MOVIESCENETRACKS_API const int32 SectionEditConditionToggleImportingID
static MOVIESCENETRACKS_API const int32 SectionPropertyValueImportingID
Detailed Description
Base class for tracks that animate an object property.
Definition at line 156 of file MovieScenePropertyTrack.h.
Member Function Documentation
ImportEditConditionToggleEntity()
MOVIESCENETRACKS_API void FMovieScenePropertyTrackEntityImportHelper::ImportEditConditionToggleEntity (const UE::MovieScene::FEntityImportParams & Params, UE::MovieScene::FImportedEntity * OutImportedEntity) static
References Params.
Referenced by UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), and UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit().
IsEditConditionToggleID()
MOVIESCENETRACKS_API bool FMovieScenePropertyTrackEntityImportHelper::IsEditConditionToggleID (const UE::MovieScene::FEntityImportParams & Params) static
References Params.
Referenced by UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), and UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit().
IsPropertyValueID()
MOVIESCENETRACKS_API bool FMovieScenePropertyTrackEntityImportHelper::IsPropertyValueID (const UE::MovieScene::FEntityImportParams & Params) static
References Params.
Referenced by UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), and UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit().
PopulateEvaluationField()
MOVIESCENETRACKS_API void FMovieScenePropertyTrackEntityImportHelper::PopulateEvaluationField (UMovieSceneSection & Section, const TRange< FFrameNumber > & EffectiveRange, const FMovieSceneEvaluationFieldEntityMetaData & InMetaData, FMovieSceneEntityComponentFieldBuilder * OutFieldBuilder) static
SanitizeBoolPropertyName()
MOVIESCENETRACKS_API FName FMovieScenePropertyTrackEntityImportHelper::SanitizeBoolPropertyName (FName InPropertyName) static
Field Documentation
SectionEditConditionToggleImportingID
MOVIESCENETRACKS_API const int32 FMovieScenePropertyTrackEntityImportHelper::SectionEditConditionToggleImportingID static
Definition at line 159 of file MovieScenePropertyTrack.h.
SectionPropertyValueImportingID
MOVIESCENETRACKS_API const int32 FMovieScenePropertyTrackEntityImportHelper::SectionPropertyValueImportingID static
Definition at line 158 of file MovieScenePropertyTrack.h.
The documentation for this struct was generated from the following file:
MovieScenePropertyTrack.h