Unreal Engine 5.6 C++ API: Metasound::Frontend::ISearchEngine Class Reference
Metasound::Frontend::ISearchEngine Class Reference abstract
Interface for frontend search engine.
#include "MetasoundFrontendSearchEngine.h"
Public Member Functions
virtual ~ISearchEngine ()=default
virtual TArray< FMetasoundFrontendVersion > FindAllRegisteredInterfacesWithName (FName InInterfaceName)=0
Finds all registered interfaces with the given name.
virtual bool FindClassWithHighestMinorVersion (const FMetasoundFrontendClassName &InName, int32 InMajorVersion, FMetasoundFrontendClass &OutClass)=0
Find the class with the given ClassName & Major Version.
virtual bool FindInterfaceWithHighestVersion (FName InInterfaceName, FMetasoundFrontendInterface &OutInterface)=0
Finds the registered interface with the highest version of the given name.
virtual TArray< FMetasoundFrontendVersion > FindUClassDefaultInterfaceVersions (const FTopLevelAssetPath &InUClassPath)=0
Returns all interfaces that are to be added to a given document when it is initialized on an object with the given class.
virtual void Prime ()=0
Updates internal state to speed up queries.
UE_DEPRECATED (5.3, "Use ISearchEngine::FindUClassDefaultInterfaceVersions using TopLevelAssetPath instead.") virtual TArray< FMetasoundFrontendInterface > FindUClassDefaultInterfaces(FName InUClassName)=0
Static Public Member Functions
static METASOUNDFRONTEND_API ISearchEngine & Get ()
Return an instance of a search engine.
Protected Member Functions
ISearchEngine ()=default
Detailed Description
Interface for frontend search engine.
A frontend search engine provides a simple interface for common frontend queries. It also serves as an opportunity to cache queries to reduce CPU load.
Definition at line 18 of file MetasoundFrontendSearchEngine.h.
Constructor & Destructor Documentation
~ISearchEngine()
virtual Metasound::Frontend::ISearchEngine::~ISearchEngine () virtual default
ISearchEngine()
Metasound::Frontend::ISearchEngine::ISearchEngine () protected default
Referenced by Get().
Member Function Documentation
FindAllRegisteredInterfacesWithName()
virtual TArray< FMetasoundFrontendVersion > Metasound::Frontend::ISearchEngine::FindAllRegisteredInterfacesWithName (FName InInterfaceName) pure virtual
Finds all registered interfaces with the given name.
FindClassWithHighestMinorVersion()
virtual bool Metasound::Frontend::ISearchEngine::FindClassWithHighestMinorVersion (const FMetasoundFrontendClassName & InName, int32 InMajorVersion, FMetasoundFrontendClass & OutClass) pure virtual
Find the class with the given ClassName & Major Version.
Returns false if not found, true if found.
References InName.
FindInterfaceWithHighestVersion()
virtual bool Metasound::Frontend::ISearchEngine::FindInterfaceWithHighestVersion (FName InInterfaceName, FMetasoundFrontendInterface & OutInterface) pure virtual
Finds the registered interface with the highest version of the given name.
Returns true if found, false if not.
FindUClassDefaultInterfaceVersions()
virtual TArray< FMetasoundFrontendVersion > Metasound::Frontend::ISearchEngine::FindUClassDefaultInterfaceVersions (const FTopLevelAssetPath & InUClassPath) pure virtual
Returns all interfaces that are to be added to a given document when it is initialized on an object with the given class.
References FindUClassDefaultInterfaceVersions(), and InName.
Referenced by FindUClassDefaultInterfaceVersions().
Get()
METASOUNDFRONTEND_API ISearchEngine & Metasound::Frontend::ISearchEngine::Get () static
Return an instance of a search engine.
References ISearchEngine(), and UE_API.
Prime()
virtual void Metasound::Frontend::ISearchEngine::Prime () pure virtual
Updates internal state to speed up queries.
UE_DEPRECATED()
Metasound::Frontend::ISearchEngine::UE_DEPRECATED (5. 3, "Use ISearchEngine::FindUClassDefaultInterfaceVersions using TopLevelAssetPath instead.") pure virtual
The documentation for this class was generated from the following file:
MetasoundFrontendSearchEngine.h