Unreal Engine 5.6 C++ API: TraceServices::TVariablePagedArrayIterator< ItemType > Class Template Reference
TraceServices::TVariablePagedArrayIterator< ItemType > Class Template Reference
#include "VariablePagedArray.h"
Public Types
typedef TVariablePagedArray< ItemType > ArrayType
typedef TVariablePagedArrayPageGroup< ItemType > PageGroupType
typedef TVariablePagedArrayPage< ItemType > PageType
Public Member Functions
TVariablePagedArrayIterator (const ArrayType &InOuter)
TVariablePagedArrayIterator (const ArrayType &InOuter, const uint64 ItemIndex)
const ItemType * GetCurrentItem ()
const uint64 GetCurrentItemIndex ()
const PageType * GetCurrentPage ()
const ItemType * NextItem ()
const PageType * NextPage ()
operator bool () const
const ItemType & operator* () const
TVariablePagedArrayIterator & operator++ ()
TVariablePagedArrayIterator operator++ (int)
TVariablePagedArrayIterator & operator-- ()
TVariablePagedArrayIterator operator-- (int)
const ItemType * operator-> () const
const ItemType * PrevItem ()
const PageType * PrevPage ()
const ItemType * SetPosition (uint64 Index)
const ItemType * SetPositionAtFirstItem ()
const ItemType * SetPositionAtLastItem ()
Private Member Functions
void OnCurrentPageChanged ()
Private Attributes
const ItemType * CurrentItem = nullptr
uint64 CurrentItemIndex = 0
const PageType * CurrentPage = nullptr
const ItemType * CurrentPageFirstItem = nullptr
const ItemType * CurrentPageLastItem = nullptr
const ArrayType * Outer = nullptr
Detailed Description
template<typename ItemType>
class TraceServices::TVariablePagedArrayIterator< ItemType >
Definition at line 117 of file VariablePagedArray.h.
Member Typedef Documentation
ArrayType
template<typename ItemType> typedef TVariablePagedArray<ItemType> TraceServices::TVariablePagedArrayIterator< ItemType >::ArrayType
Definition at line 122 of file VariablePagedArray.h.
PageGroupType
template<typename ItemType> typedef TVariablePagedArrayPageGroup<ItemType> TraceServices::TVariablePagedArrayIterator< ItemType >::PageGroupType
Definition at line 121 of file VariablePagedArray.h.
PageType
template<typename ItemType> typedef TVariablePagedArrayPage<ItemType> TraceServices::TVariablePagedArrayIterator< ItemType >::PageType
Definition at line 120 of file VariablePagedArray.h.
Constructor & Destructor Documentation
TVariablePagedArrayIterator() [1/2]
template<typename ItemType> TraceServices::TVariablePagedArrayIterator< ItemType >::TVariablePagedArrayIterator (const ArrayType & InOuter) inline
Definition at line 125 of file VariablePagedArray.h.
TVariablePagedArrayIterator() [2/2]
template<typename ItemType> TraceServices::TVariablePagedArrayIterator< ItemType >::TVariablePagedArrayIterator (const ArrayType & InOuter, const uint64 ItemIndex) inline
Definition at line 134 of file VariablePagedArray.h.
Member Function Documentation
GetCurrentItem()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::GetCurrentItem () inline
Definition at line 162 of file VariablePagedArray.h.
GetCurrentItemIndex()
template<typename ItemType> const uint64 TraceServices::TVariablePagedArrayIterator< ItemType >::GetCurrentItemIndex () inline
Definition at line 167 of file VariablePagedArray.h.
GetCurrentPage()
template<typename ItemType> const PageType * TraceServices::TVariablePagedArrayIterator< ItemType >::GetCurrentPage () inline
Definition at line 157 of file VariablePagedArray.h.
NextItem()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::NextItem () inline
Definition at line 254 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArrayIterator< InItemType >::operator++(), and TraceServices::TVariablePagedArrayIterator< InItemType >::operator++().
NextPage()
template<typename ItemType> const PageType * TraceServices::TVariablePagedArrayIterator< ItemType >::NextPage () inline
Definition at line 207 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArrayIterator< InItemType >::NextItem().
OnCurrentPageChanged()
template<typename ItemType> void TraceServices::TVariablePagedArrayIterator< ItemType >::OnCurrentPageChanged () inline private
Definition at line 322 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArrayIterator< InItemType >::TVariablePagedArrayIterator(), TraceServices::TVariablePagedArrayIterator< InItemType >::NextPage(), TraceServices::TVariablePagedArrayIterator< InItemType >::PrevPage(), TraceServices::TVariablePagedArrayIterator< InItemType >::SetPosition(), TraceServices::TVariablePagedArrayIterator< InItemType >::SetPositionAtFirstItem(), and TraceServices::TVariablePagedArrayIterator< InItemType >::SetPositionAtLastItem().
operator bool()
template<typename ItemType> TraceServices::TVariablePagedArrayIterator< ItemType >::operator bool () const inline explicit
Definition at line 182 of file VariablePagedArray.h.
operator*()
template<typename ItemType> const ItemType & TraceServices::TVariablePagedArrayIterator< ItemType >::operator* () const inline
Definition at line 172 of file VariablePagedArray.h.
operator++() [1/2]
template<typename ItemType> TVariablePagedArrayIterator & TraceServices::TVariablePagedArrayIterator< ItemType >::operator++ () inline
Definition at line 268 of file VariablePagedArray.h.
operator++() [2/2]
template<typename ItemType> TVariablePagedArrayIterator TraceServices::TVariablePagedArrayIterator< ItemType >::operator++ (int) inline
Definition at line 274 of file VariablePagedArray.h.
operator--() [1/2]
template<typename ItemType> TVariablePagedArrayIterator & TraceServices::TVariablePagedArrayIterator< ItemType >::operator-- () inline
Definition at line 241 of file VariablePagedArray.h.
operator--() [2/2]
template<typename ItemType> TVariablePagedArrayIterator TraceServices::TVariablePagedArrayIterator< ItemType >::operator-- (int) inline
Definition at line 247 of file VariablePagedArray.h.
operator->()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::operator-> () const inline
Definition at line 177 of file VariablePagedArray.h.
PrevItem()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::PrevItem () inline
Definition at line 227 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArrayIterator< InItemType >::operator--(), and TraceServices::TVariablePagedArrayIterator< InItemType >::operator--().
PrevPage()
template<typename ItemType> const PageType * TraceServices::TVariablePagedArrayIterator< ItemType >::PrevPage () inline
Definition at line 187 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArrayIterator< InItemType >::PrevItem().
SetPosition()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::SetPosition (uint64 Index) inline
Definition at line 305 of file VariablePagedArray.h.
SetPositionAtFirstItem()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::SetPositionAtFirstItem () inline
Definition at line 281 of file VariablePagedArray.h.
Referenced by TraceServices::TVariablePagedArrayIterator< InItemType >::TVariablePagedArrayIterator().
SetPositionAtLastItem()
template<typename ItemType> const ItemType * TraceServices::TVariablePagedArrayIterator< ItemType >::SetPositionAtLastItem () inline
Definition at line 293 of file VariablePagedArray.h.
Field Documentation
CurrentItem
template<typename ItemType> const ItemType* TraceServices::TVariablePagedArrayIterator< ItemType >::CurrentItem = nullptr private
Definition at line 331 of file VariablePagedArray.h.
CurrentItemIndex
template<typename ItemType> uint64 TraceServices::TVariablePagedArrayIterator< ItemType >::CurrentItemIndex = 0 private
Definition at line 330 of file VariablePagedArray.h.
CurrentPage
template<typename ItemType> const PageType* TraceServices::TVariablePagedArrayIterator< ItemType >::CurrentPage = nullptr private
Definition at line 329 of file VariablePagedArray.h.
CurrentPageFirstItem
template<typename ItemType> const ItemType* TraceServices::TVariablePagedArrayIterator< ItemType >::CurrentPageFirstItem = nullptr private
Definition at line 332 of file VariablePagedArray.h.
CurrentPageLastItem
template<typename ItemType> const ItemType* TraceServices::TVariablePagedArrayIterator< ItemType >::CurrentPageLastItem = nullptr private
Definition at line 333 of file VariablePagedArray.h.
Outer
template<typename ItemType> const ArrayType* TraceServices::TVariablePagedArrayIterator< ItemType >::Outer = nullptr private
Definition at line 328 of file VariablePagedArray.h.
The documentation for this class was generated from the following file:
VariablePagedArray.h