Unreal Engine 5.6 C++ API: FDisplayNameEntryId Class Reference
FDisplayNameEntryId Class Reference
Serialization util that optimizes WITH_CASE_PRESERVING_NAME-loading by reducing comparison id lookups.
#include "NameTypes.h"
Public Member Functions
FDisplayNameEntryId ()
FDisplayNameEntryId (FName Name)
void SetLoadedComparisonId (FNameEntryId ComparisonId)
FNameEntryId ToDisplayId () const
FORCEINLINE FName ToName (uint32 Number) const
Static Public Member Functions
static FDisplayNameEntryId FromComparisonId (FNameEntryId ComparisonId)
Private Member Functions
FDisplayNameEntryId (FNameEntryId InId, FNameEntryId)
FORCEINLINE FNameEntryId GetComparisonId () const
FORCEINLINE FNameEntryId GetDisplayId () const
Private Attributes
FNameEntryId Id
Friends
uint32 GetTypeHash (FDisplayNameEntryId InId)
bool operator== (FDisplayNameEntryId A, FDisplayNameEntryId B)
bool operator== (FDisplayNameEntryId A, FNameEntryId B)
bool operator== (FNameEntryId A, FDisplayNameEntryId B)
Detailed Description
Serialization util that optimizes WITH_CASE_PRESERVING_NAME-loading by reducing comparison id lookups.
Stores 32-bit display entry id with an unused bit to indicate if FName::GetComparisonIdFromDisplayId lookup is needed.
Note that only display entries should be saved to make output deterministic.
Definition at line 1801 of file NameTypes.h.
Constructor & Destructor Documentation
FDisplayNameEntryId() [1/3]
FDisplayNameEntryId::FDisplayNameEntryId () inline
Definition at line 1804 of file NameTypes.h.
References FDisplayNameEntryId().
Referenced by FDisplayNameEntryId(), FDisplayNameEntryId(), FromComparisonId(), GetTypeHash, operator==, operator==, and operator==.
FDisplayNameEntryId() [2/3]
FDisplayNameEntryId::FDisplayNameEntryId (FName Name) inline explicit
Definition at line 1805 of file NameTypes.h.
References FDisplayNameEntryId(), and Name.
FDisplayNameEntryId() [3/3]
FDisplayNameEntryId::FDisplayNameEntryId (FNameEntryId InId, FNameEntryId) inline private
Definition at line 1823 of file NameTypes.h.
References Id.
Member Function Documentation
FromComparisonId()
FDisplayNameEntryId FDisplayNameEntryId::FromComparisonId (FNameEntryId ComparisonId) static
References FDisplayNameEntryId().
GetComparisonId()
FORCEINLINE FNameEntryId FDisplayNameEntryId::GetComparisonId () const inline private
Definition at line 1825 of file NameTypes.h.
References FORCEINLINE, and Id.
Referenced by ToName().
GetDisplayId()
FORCEINLINE FNameEntryId FDisplayNameEntryId::GetDisplayId () const inline private
Definition at line 1824 of file NameTypes.h.
References FORCEINLINE, and Id.
Referenced by GetTypeHash, and ToName().
SetLoadedComparisonId()
void FDisplayNameEntryId::SetLoadedComparisonId (FNameEntryId ComparisonId)
ToDisplayId()
FNameEntryId FDisplayNameEntryId::ToDisplayId () const
ToName()
FORCEINLINE FName FDisplayNameEntryId::ToName (uint32 Number) const inline
Definition at line 1806 of file NameTypes.h.
References FName, FORCEINLINE, GetComparisonId(), and GetDisplayId().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FDisplayNameEntryId InId) friend
Definition at line 1830 of file NameTypes.h.
References FDisplayNameEntryId(), GetDisplayId(), and GetTypeHash.
Referenced by GetTypeHash.
operator== [1/3]
bool operator== (FDisplayNameEntryId A, FDisplayNameEntryId B) friend
Definition at line 1826 of file NameTypes.h.
References FDisplayNameEntryId(), A, and B.
operator== [2/3]
bool operator== (FDisplayNameEntryId A, FNameEntryId B) friend
Definition at line 1829 of file NameTypes.h.
References FDisplayNameEntryId(), A, and B.
operator== [3/3]
bool operator== (FNameEntryId A, FDisplayNameEntryId B) friend
Definition at line 1828 of file NameTypes.h.
References FDisplayNameEntryId(), A, and B.
Field Documentation
Id
FNameEntryId FDisplayNameEntryId::Id private
Definition at line 1821 of file NameTypes.h.
Referenced by FDisplayNameEntryId(), GetComparisonId(), and GetDisplayId().
The documentation for this class was generated from the following file:
NameTypes.h