Unreal Engine 5.6 C++ API: UE::Sequencer::TViewModelPtr< T > Struct Template Reference
UE::Sequencer::TViewModelPtr< T > Struct Template Reference
Pointer type that wraps a shared view model pointer to provide implicit dynamic_cast style casting to any other view-model or extension.
#include "ViewModelPtr.h"
Public Types
using ViewModelType = typename std::conditional_t<std::is_const_v<T>, const FViewModel, FViewModel>
Public Types inherited from UE::Sequencer::TViewModelConversions< T >
using ViewModelType = typename std::conditional_t<std::is_const_v<T>, const FViewModel, FViewModel>
Public Member Functions
TViewModelPtr ()=default
template<typename ModelType>
TViewModelPtr (const TSharedPtr< ModelType > &InModel)
Construction from a shared ptr.
template<typename ModelType>
TViewModelPtr (const TSharedRef< ModelType > &InModel)
Construction from a shared ptr.
TViewModelPtr (const TViewModelPtr &)=default
template<typename OtherType>
TViewModelPtr (const TViewModelPtr< OtherType > &In)
TViewModelPtr (nullptr_t)
Construction from a nullptr.
TViewModelPtr (T *InViewModelType)
TViewModelPtr (TSharedPtr< ViewModelType > InModel, T *InExtension)
TViewModelPtr (TViewModelPtr &&)=default
TSharedPtr< ViewModelType > AsModel () const
Explicitly access the view model as a regular shared pointer.
T * Get () const
Member access operator giving access to the wrapped view model.
TImplicitViewModelCast< ViewModelType > ImplicitCast () const
Return a proxy type that is able to implicitly convert this view model to any other TViewModel<IMyExtension> or TSharedPtr<IMyExtension>
TImplicitViewModelCastChecked< ViewModelType > ImplicitCastChecked () const
bool IsValid () const
operator bool () const
Check whether this ptr is valid (non-null)
T & operator* () const
Dereference operator giving access to the wrapped view model.
T * operator-> () const
Member access operator giving access to the wrapped view model.
template<typename ModelType>
TViewModelPtr & operator= (const TSharedPtr< ModelType > &InModel)
Assignment from a shared ptr.
template<typename ModelType>
TViewModelPtr & operator= (const TSharedRef< ModelType > &InModel)
Assignment from a shared ptr.
TViewModelPtr & operator= (const TViewModelPtr &)=default
template<typename OtherType>
TViewModelPtr & operator= (const TViewModelPtr< OtherType > &In)
TViewModelPtr & operator= (nullptr_t)
Assignment from a nullptr.
TViewModelPtr & operator= (TViewModelPtr &&)=default
void Reset ()
Reset this view model pointer back to its default (null) state.
TSharedRef< T > ToSharedRef () const
Public Member Functions inherited from UE::Sequencer::TViewModelConversions< T >
TWeakViewModelPtr< T > AsWeak () const
operator TSharedPtr< T > () const
operator TSharedPtr< ViewModelType > () const
operator TWeakPtr< T > () const
operator TWeakPtr< ViewModelType > () const
Protected Attributes
TViewModelPtrStorage< T > Storage
friend TViewModelConversions< T >
Friends
template<typename>
struct TViewModelPtr
uint32 GetTypeHash (const TViewModelPtr< T > &In)
Type hash function for use with the TSet and TMap family of containers.
template<typename SharedType>
bool operator!= (const TViewModelPtr< T > &A, const TSharedPtr< SharedType > &B)
template<typename SharedType>
bool operator!= (const TViewModelPtr< T > &A, const TSharedRef< SharedType > &B)
bool operator!= (const TViewModelPtr< T > &A, const TViewModelPtr< T > &B)
bool operator!= (const TViewModelPtr< T > &A, nullptr_t B)
template<typename SharedType>
bool operator== (const TViewModelPtr< T > &A, const TSharedPtr< SharedType > &B)
template<typename SharedType>
bool operator== (const TViewModelPtr< T > &A, const TSharedRef< SharedType > &B)
bool operator== (const TViewModelPtr< T > &A, const TViewModelPtr< T > &B)
Equality operator comparing 2 view model pointers.
bool operator== (const TViewModelPtr< T > &A, nullptr_t B)
Detailed Description
template<typename T>
struct UE::Sequencer::TViewModelPtr< T >
Pointer type that wraps a shared view model pointer to provide implicit dynamic_cast style casting to any other view-model or extension.
Implicit conversion is implemented through a proxy object so as to make the 'implicit' conversion somewhat explicit: FViewModelPtr ModelPtr = GetViewModel(); TSharedPtr<IDraggableOutlinerExtension> Draggable = ModelPtr.ImplicitCast(); TSharedPtr<IDroppableExtension> Droppable = ModelPtr.ImplicitCast();
Definition at line 107 of file ViewModelPtr.h.
Member Typedef Documentation
ViewModelType
template<typename T> using UE::Sequencer::TViewModelPtr< T >::ViewModelType = typename std::conditional_t<std::is_const_v<T>, const FViewModel, FViewModel>
Definition at line 109 of file ViewModelPtr.h.
Constructor & Destructor Documentation
TViewModelPtr() [1/9]
template<typename T> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr () default
TViewModelPtr() [2/9]
template<typename T> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (const TViewModelPtr< T > &) default
TViewModelPtr() [3/9]
template<typename T> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (TViewModelPtr< T > &&) default
TViewModelPtr() [4/9]
template<typename T> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (T * InViewModelType) inline explicit
Definition at line 117 of file ViewModelPtr.h.
TViewModelPtr() [5/9]
template<typename T> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (TSharedPtr< ViewModelType > InModel, T * InExtension) inline
Definition at line 122 of file ViewModelPtr.h.
TViewModelPtr() [6/9]
template<typename T> template<typename OtherType> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (const TViewModelPtr< OtherType > & In) inline
Definition at line 131 of file ViewModelPtr.h.
TViewModelPtr() [7/9]
template<typename T> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (nullptr_t) inline
Construction from a nullptr.
Definition at line 158 of file ViewModelPtr.h.
TViewModelPtr() [8/9]
template<typename T> template<typename ModelType> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (const TSharedPtr< ModelType > & InModel) inline
Construction from a shared ptr.
Definition at line 170 of file ViewModelPtr.h.
TViewModelPtr() [9/9]
template<typename T> template<typename ModelType> UE::Sequencer::TViewModelPtr< T >::TViewModelPtr (const TSharedRef< ModelType > & InModel) inline
Construction from a shared ptr.
Definition at line 190 of file ViewModelPtr.h.
Member Function Documentation
AsModel()
template<typename T> TSharedPtr< ViewModelType > UE::Sequencer::TViewModelPtr< T >::AsModel () const inline
Explicitly access the view model as a regular shared pointer.
Definition at line 259 of file ViewModelPtr.h.
Referenced by UE::Sequencer::TWeakViewModelPtr< ExtensionType >::TWeakViewModelPtr(), TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::DebugDump(), and UE::Sequencer::TWeakViewModelPtr< ExtensionType >::operator=().
Get()
template<typename T> T * UE::Sequencer::TViewModelPtr< T >::Get () const inline
Member access operator giving access to the wrapped view model.
Definition at line 241 of file ViewModelPtr.h.
ImplicitCast()
template<typename T> TImplicitViewModelCast< typename TViewModelPtr< T >::ViewModelType > UE::Sequencer::TViewModelPtr< T >::ImplicitCast () const
Return a proxy type that is able to implicitly convert this view model to any other TViewModel<IMyExtension> or TSharedPtr<IMyExtension>
Definition at line 632 of file ViewModelPtr.h.
References Storage.
Referenced by UE::Sequencer::CastViewModel(), and UE::Sequencer::CastViewModelChecked().
ImplicitCastChecked()
template<typename T> TImplicitViewModelCastChecked< typename TViewModelPtr< T >::ViewModelType > UE::Sequencer::TViewModelPtr< T >::ImplicitCastChecked () const
Definition at line 637 of file ViewModelPtr.h.
References Storage.
IsValid()
template<typename T> bool UE::Sequencer::TViewModelPtr< T >::IsValid () const inline
Definition at line 267 of file ViewModelPtr.h.
Referenced by FSequencerTrackFilter_ModelType< InModelType >::PassesFilter().
operator bool()
template<typename T> UE::Sequencer::TViewModelPtr< T >::operator bool () const inline explicit
Check whether this ptr is valid (non-null)
Definition at line 215 of file ViewModelPtr.h.
operator*()
template<typename T> T & UE::Sequencer::TViewModelPtr< T >::operator* () const inline
Dereference operator giving access to the wrapped view model.
Definition at line 249 of file ViewModelPtr.h.
operator->()
template<typename T> T * UE::Sequencer::TViewModelPtr< T >::operator-> () const inline
Member access operator giving access to the wrapped view model.
Definition at line 231 of file ViewModelPtr.h.
operator=() [1/6]
template<typename T> template<typename ModelType> TViewModelPtr & UE::Sequencer::TViewModelPtr< T >::operator= (const TSharedPtr< ModelType > & InModel) inline
Assignment from a shared ptr.
Definition at line 179 of file ViewModelPtr.h.
operator=() [2/6]
template<typename T> template<typename ModelType> TViewModelPtr & UE::Sequencer::TViewModelPtr< T >::operator= (const TSharedRef< ModelType > & InModel) inline
Assignment from a shared ptr.
Definition at line 200 of file ViewModelPtr.h.
operator=() [3/6]
template<typename T> TViewModelPtr & UE::Sequencer::TViewModelPtr< T >::operator= (const TViewModelPtr< T > &) default
operator=() [4/6]
template<typename T> template<typename OtherType> TViewModelPtr & UE::Sequencer::TViewModelPtr< T >::operator= (const TViewModelPtr< OtherType > & In) inline
Definition at line 144 of file ViewModelPtr.h.
operator=() [5/6]
template<typename T> TViewModelPtr & UE::Sequencer::TViewModelPtr< T >::operator= (nullptr_t) inline
Assignment from a nullptr.
Definition at line 162 of file ViewModelPtr.h.
operator=() [6/6]
template<typename T> TViewModelPtr & UE::Sequencer::TViewModelPtr< T >::operator= (TViewModelPtr< T > &&) default
Reset()
template<typename T> void UE::Sequencer::TViewModelPtr< T >::Reset () inline
Reset this view model pointer back to its default (null) state.
Definition at line 223 of file ViewModelPtr.h.
ToSharedRef()
template<typename T> TSharedRef< T > UE::Sequencer::TViewModelPtr< T >::ToSharedRef () const inline
Definition at line 263 of file ViewModelPtr.h.
Friends And Related Symbol Documentation
TViewModelPtr
template<typename T> template<typename> friend struct TViewModelPtr friend
Definition at line 331 of file ViewModelPtr.h.
GetTypeHash
template<typename T> uint32 GetTypeHash (const TViewModelPtr< T > & In) friend
Type hash function for use with the TSet and TMap family of containers.
Definition at line 282 of file ViewModelPtr.h.
Referenced by UE::Sequencer::TViewModelPtr< FViewModel >::GetTypeHash.
operator!= [1/4]
template<typename T> template<typename SharedType> bool operator!= (const TViewModelPtr< T > & A, const TSharedPtr< SharedType > & B) friend
Definition at line 305 of file ViewModelPtr.h.
operator!= [2/4]
template<typename T> template<typename SharedType> bool operator!= (const TViewModelPtr< T > & A, const TSharedRef< SharedType > & B) friend
Definition at line 316 of file ViewModelPtr.h.
operator!= [3/4]
template<typename T> bool operator!= (const TViewModelPtr< T > & A, const TViewModelPtr< T > & B) friend
Definition at line 294 of file ViewModelPtr.h.
operator!= [4/4]
template<typename T> bool operator!= (const TViewModelPtr< T > & A, nullptr_t B) friend
Definition at line 325 of file ViewModelPtr.h.
operator== [1/4]
template<typename T> template<typename SharedType> bool operator== (const TViewModelPtr< T > & A, const TSharedPtr< SharedType > & B) friend
Definition at line 300 of file ViewModelPtr.h.
operator== [2/4]
template<typename T> template<typename SharedType> bool operator== (const TViewModelPtr< T > & A, const TSharedRef< SharedType > & B) friend
Definition at line 311 of file ViewModelPtr.h.
operator== [3/4]
template<typename T> bool operator== (const TViewModelPtr< T > & A, const TViewModelPtr< T > & B) friend
Equality operator comparing 2 view model pointers.
Definition at line 290 of file ViewModelPtr.h.
operator== [4/4]
template<typename T> bool operator== (const TViewModelPtr< T > & A, nullptr_t B) friend
Definition at line 321 of file ViewModelPtr.h.
Field Documentation
Storage
template<typename T> TViewModelPtrStorage<T> UE::Sequencer::TViewModelPtr< T >::Storage protected
Definition at line 335 of file ViewModelPtr.h.
Referenced by UE::Sequencer::TViewModelPtr< FViewModel >::TViewModelPtr(), UE::Sequencer::TViewModelPtr< FViewModel >::GetTypeHash, ImplicitCast(), ImplicitCastChecked(), and UE::Sequencer::TViewModelPtr< FViewModel >::operator=().
TViewModelConversions< T >
template<typename T> friend UE::Sequencer::TViewModelPtr< T >::TViewModelConversions< T > protected
Definition at line 333 of file ViewModelPtr.h.
The documentation for this struct was generated from the following file:
ViewModelPtr.h