Unreal Engine 5.6 C++ API: FQueuedLowLevelThreadPool Class Reference
FQueuedLowLevelThreadPool Class Reference final
ThreadPool wrapper implementation allowing to schedule thread-pool tasks on the the low level backend which is also used by the taskgraph.
#include "QueuedThreadPoolWrapper.h"
Data Structures
struct FQueuedWorkInternalData
Public Member Functions
FQueuedLowLevelThreadPool (TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper=DefaultQueuedWorkPriorityWrapper, LowLevelTasks::FScheduler *InScheduler=&LowLevelTasks::FScheduler::Get())
InPriorityMapper Thread-safe function used to map any priority from this Queue to the priority that should be used when scheduling the task on the underlying thread pool.
~FQueuedLowLevelThreadPool ()
void operator delete (void *ptr)
void * operator new (size_t size)
void Pause ()
Queued task are not scheduled against the wrapped thread-pool until resumed.
void Resume (int32 InNumQueuedWork=-1)
Resume a specified amount of queued work, or -1 to unpause.
Public Member Functions inherited from FQueuedThreadPool
FQueuedThreadPool ()
virtual ~FQueuedThreadPool ()
virtual bool CreateForkable (uint32 InNumQueuedThreads, uint32 StackSize=(32 *1024), EThreadPriority ThreadPriority=TPri_Normal, const TCHAR *Name=TEXT("UnknownThreadPool"))
Creates the thread pool with the specified number of forkable threads (see FForkProcessHelper)
Protected Member Functions
bool Create (uint32 InNumQueuedThreads, uint32 InStackSize, EThreadPriority InThreadPriority, const TCHAR *InName) override
Creates the thread pool with the specified number of threads.
void Destroy () override
Tells the pool to clean up all background threads.
Private Member Functions
void AddQueuedWork (IQueuedWork *InQueuedWork, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal) override
Checks to see if there is a thread available to perform the task.
FQueuedWorkInternalData * Dequeue ()
void Enqueue (EQueuedWorkPriority Priority, FQueuedWorkInternalData *Item)
void FinalizeExecution ()
int32 GetNumThreads () const override
Get the number of queued threads.
bool RetractQueuedWork (IQueuedWork *InQueuedWork) override
Attempts to retract a previously queued task.
void ScheduleTasks (bool &bWakeUpWorker)
Private Attributes
std::atomic_bool bIsExiting {false}
std::atomic_bool bIsPaused {false}
UE::FManualResetEvent Finished
FAAArrayQueue< FQueuedWorkInternalData > PendingWork [int32(EQueuedWorkPriority::Count)]
TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> PriorityMapper
LowLevelTasks::FScheduler * Scheduler = nullptr
std::atomic_uint TaskCount {0}
Additional Inherited Members
Static Public Member Functions inherited from FQueuedThreadPool
static FQueuedThreadPool * Allocate ()
Allocates a thread pool.
Static Public Attributes inherited from FQueuedThreadPool
static uint32 OverrideStackSize
Stack size for threads created for the thread pool.
Detailed Description
ThreadPool wrapper implementation allowing to schedule thread-pool tasks on the the low level backend which is also used by the taskgraph.
Definition at line 369 of file QueuedThreadPoolWrapper.h.
Constructor & Destructor Documentation
FQueuedLowLevelThreadPool()
FQueuedLowLevelThreadPool::FQueuedLowLevelThreadPool (TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper = DefaultQueuedWorkPriorityWrapper, LowLevelTasks::FScheduler * InScheduler = &LowLevelTasks::FScheduler::Get()) inline
InPriorityMapper Thread-safe function used to map any priority from this Queue to the priority that should be used when scheduling the task on the underlying thread pool.
Definition at line 385 of file QueuedThreadPoolWrapper.h.
References DefaultQueuedWorkPriorityWrapper, LowLevelTasks::FScheduler::Get(), PriorityMapper, and Scheduler.
~FQueuedLowLevelThreadPool()
FQueuedLowLevelThreadPool::~FQueuedLowLevelThreadPool () inline
Definition at line 390 of file QueuedThreadPoolWrapper.h.
References Destroy().
Member Function Documentation
AddQueuedWork()
void FQueuedLowLevelThreadPool::AddQueuedWork (IQueuedWork * InQueuedWork, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) inline override private virtual
Checks to see if there is a thread available to perform the task.
If not, it queues the work for later. Otherwise it is immediately dispatched.
Parameters
InQueuedWork The work that needs to be done asynchronously
InQueuedWorkPriority The priority at which to process this task
See also
RetractQueuedWork
Implements FQueuedThreadPool.
Definition at line 471 of file QueuedThreadPoolWrapper.h.
References LowLevelTasks::BackgroundHigh, LowLevelTasks::BackgroundLow, LowLevelTasks::BackgroundNormal, bIsExiting, bIsPaused, check, Count, DoNotRunInsideBusyWait, Enqueue(), Flags, IQueuedWork::GetQueuedWorkFlags(), LowLevelTasks::GlobalQueuePreference, LowLevelTasks::High, LowLevelTasks::FTask::Init(), IQueuedWork::InternalData, None, Normal, PriorityMapper, Scheduler, FQueuedLowLevelThreadPool::FQueuedWorkInternalData::Task, TaskCount, TEXT, and verifySlow.
Create()
bool FQueuedLowLevelThreadPool::Create (uint32 InNumQueuedThreads, uint32 StackSize, EThreadPriority ThreadPriority, const TCHAR * Name) inline override protected virtual
Creates the thread pool with the specified number of threads.
Parameters
InNumQueuedThreads Specifies the number of threads to use in the pool
StackSize The size of stack the threads in the pool need (32K default)
ThreadPriority priority of new pool thread
Name optional name for the pool to be used for instrumentation
Returns
Whether the pool creation was successful or not
Implements FQueuedThreadPool.
Definition at line 520 of file QueuedThreadPoolWrapper.h.
References InName.
Dequeue()
FQueuedWorkInternalData * FQueuedLowLevelThreadPool::Dequeue () inline private
Definition at line 551 of file QueuedThreadPoolWrapper.h.
References Count, and PendingWork.
Referenced by Destroy(), Resume(), and ScheduleTasks().
Destroy()
void FQueuedLowLevelThreadPool::Destroy () inline override protected virtual
Tells the pool to clean up all background threads.
Implements FQueuedThreadPool.
Definition at line 525 of file QueuedThreadPoolWrapper.h.
References bIsExiting, Dequeue(), Finished, LowLevelTasks::GlobalQueuePreference, FQueuedLowLevelThreadPool::FQueuedWorkInternalData::Retract(), Scheduler, FQueuedLowLevelThreadPool::FQueuedWorkInternalData::Task, TaskCount, verify, and verifySlow.
Referenced by ~FQueuedLowLevelThreadPool().
Enqueue()
void FQueuedLowLevelThreadPool::Enqueue (EQueuedWorkPriority Priority, FQueuedWorkInternalData * Item) inline private
Definition at line 564 of file QueuedThreadPoolWrapper.h.
References Item, and PendingWork.
Referenced by AddQueuedWork().
FinalizeExecution()
void FQueuedLowLevelThreadPool::FinalizeExecution () inline private
Definition at line 458 of file QueuedThreadPoolWrapper.h.
References bIsExiting, Finished, ScheduleTasks(), and TaskCount.
GetNumThreads()
int32 FQueuedLowLevelThreadPool::GetNumThreads () const inline override private virtual
Get the number of queued threads.
Implements FQueuedThreadPool.
Definition at line 514 of file QueuedThreadPoolWrapper.h.
References Scheduler.
operator delete()
void FQueuedLowLevelThreadPool::operator delete (void * ptr) inline
Definition at line 400 of file QueuedThreadPoolWrapper.h.
References FMemory::Free().
operator new()
void * FQueuedLowLevelThreadPool::operator new (size_t size) inline
Definition at line 395 of file QueuedThreadPoolWrapper.h.
Pause()
void FQueuedLowLevelThreadPool::Pause () inline
Queued task are not scheduled against the wrapped thread-pool until resumed.
Definition at line 408 of file QueuedThreadPoolWrapper.h.
References bIsPaused.
Resume()
void FQueuedLowLevelThreadPool::Resume (int32 InNumQueuedWork = -1) inline
Resume a specified amount of queued work, or -1 to unpause.
Definition at line 416 of file QueuedThreadPoolWrapper.h.
References bIsPaused, Dequeue(), LowLevelTasks::GlobalQueuePreference, Scheduler, ScheduleTasks(), FQueuedLowLevelThreadPool::FQueuedWorkInternalData::Task, TaskCount, and verifySlow.
RetractQueuedWork()
bool FQueuedLowLevelThreadPool::RetractQueuedWork (IQueuedWork * InQueuedWork) inline override private virtual
Attempts to retract a previously queued task.
Parameters
InQueuedWork The work to try to retract
Returns
true if the work was retracted
See also
AddQueuedWork
Implements FQueuedThreadPool.
Definition at line 500 of file QueuedThreadPoolWrapper.h.
References IQueuedWork::InternalData, TRefCountPtr< ReferencedType >::IsValid(), IQueuedWorkInternalData::Retract(), and ScheduleTasks().
ScheduleTasks()
void FQueuedLowLevelThreadPool::ScheduleTasks (bool & bWakeUpWorker) inline private
Definition at line 439 of file QueuedThreadPoolWrapper.h.
References bIsPaused, Dequeue(), LowLevelTasks::GlobalQueuePreference, LowLevelTasks::FSchedulerTls::IsBusyWaiting(), LowLevelTasks::LocalQueuePreference, Scheduler, FQueuedLowLevelThreadPool::FQueuedWorkInternalData::Task, TaskCount, and verifySlow.
Referenced by FinalizeExecution(), Resume(), and RetractQueuedWork().
Field Documentation
bIsExiting
std::atomic_bool FQueuedLowLevelThreadPool::bIsExiting {false} private
Definition at line 573 of file QueuedThreadPoolWrapper.h.
Referenced by AddQueuedWork(), Destroy(), and FinalizeExecution().
bIsPaused
std::atomic_bool FQueuedLowLevelThreadPool::bIsPaused {false} private
Definition at line 574 of file QueuedThreadPoolWrapper.h.
Referenced by AddQueuedWork(), Pause(), Resume(), and ScheduleTasks().
Finished
UE::FManualResetEvent FQueuedLowLevelThreadPool::Finished private
Definition at line 575 of file QueuedThreadPoolWrapper.h.
Referenced by Destroy(), and FinalizeExecution().
PendingWork
FAAArrayQueue<FQueuedWorkInternalData> FQueuedLowLevelThreadPool::PendingWork[int32(EQueuedWorkPriority::Count)] private
Definition at line 549 of file QueuedThreadPoolWrapper.h.
Referenced by Dequeue(), and Enqueue().
PriorityMapper
TFunction<EQueuedWorkPriority(EQueuedWorkPriority)> FQueuedLowLevelThreadPool::PriorityMapper private
Definition at line 570 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedLowLevelThreadPool(), and AddQueuedWork().
Scheduler
LowLevelTasks::FScheduler* FQueuedLowLevelThreadPool::Scheduler = nullptr private
Definition at line 569 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedLowLevelThreadPool(), AddQueuedWork(), Destroy(), GetNumThreads(), Resume(), and ScheduleTasks().
TaskCount
std::atomic_uint FQueuedLowLevelThreadPool::TaskCount {0} private
Definition at line 572 of file QueuedThreadPoolWrapper.h.
Referenced by AddQueuedWork(), Destroy(), FinalizeExecution(), Resume(), and ScheduleTasks().
The documentation for this class was generated from the following file:
QueuedThreadPoolWrapper.h