Unreal Engine 5.6 C++ API: FAIGenericID< TCounter > Struct Template Reference
FAIGenericID< TCounter > Struct Template Reference
#include "AITypes.h"
Public Member Functions
FAIGenericID ()
FAIGenericID (const FAIGenericID &Other)
FAIGenericID & operator= (const FAIGenericID &Other)
UE_DEPRECATED (5.6, "AIGenericId is not convertible to its base type anymore.") operator typename TCounter
Static Public Member Functions
static FAIGenericID GetNextID ()
static FAIGenericID< TCounter > InvalidID ()
Data Fields
const TCounter::Type Index
Protected Member Functions
FAIGenericID (typename TCounter::Type InIndex)
Static Protected Member Functions
static TCounter & GetCounter ()
Static Private Attributes
static AIMODULE_API TCounter Counter
Friends
FORCEINLINE uint32 GetTypeHash (const FAIGenericID &ID)
Detailed Description
template<typename TCounter>
struct FAIGenericID< TCounter >
Definition at line 227 of file AITypes.h.
Constructor & Destructor Documentation
FAIGenericID() [1/3]
template<typename TCounter> FAIGenericID< TCounter >::FAIGenericID (typename TCounter::Type InIndex) inline explicit protected
Definition at line 238 of file AITypes.h.
FAIGenericID() [2/3]
template<typename TCounter> FAIGenericID< TCounter >::FAIGenericID (const FAIGenericID< TCounter > & Other) inline
Definition at line 244 of file AITypes.h.
FAIGenericID() [3/3]
template<typename TCounter> FAIGenericID< TCounter >::FAIGenericID () inline
Definition at line 254 of file AITypes.h.
Referenced by FAIGenericID< FPerceptionListenerCounter >::GetNextID(), and FAIGenericID< FPerceptionListenerCounter >::operator=().
Member Function Documentation
GetCounter()
template<typename TCounter> TCounter & FAIGenericID< TCounter >::GetCounter () inline static protected
Definition at line 233 of file AITypes.h.
Referenced by FAIGenericID< FPerceptionListenerCounter >::GetNextID().
GetNextID()
template<typename TCounter> FAIGenericID FAIGenericID< TCounter >::GetNextID () inline static
Definition at line 258 of file AITypes.h.
InvalidID()
template<typename TCounter> FAIGenericID< TCounter > FAIGenericID< TCounter >::InvalidID () inline static
Definition at line 270 of file AITypes.h.
operator=()
template<typename TCounter> FAIGenericID & FAIGenericID< TCounter >::operator= (const FAIGenericID< TCounter > & Other) inline
Definition at line 248 of file AITypes.h.
UE_DEPRECATED()
template<typename TCounter> FAIGenericID< TCounter >::UE_DEPRECATED (5. 6, "AIGenericId is not convertible to its base type anymore.") inline
Definition at line 260 of file AITypes.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename TCounter> FORCEINLINE uint32 GetTypeHash (const FAIGenericID< TCounter > & ID) friend
Definition at line 276 of file AITypes.h.
Referenced by FAIGenericID< FPerceptionListenerCounter >::GetTypeHash.
Field Documentation
Counter
template<typename TCounter> AIMODULE_API TCounter FAIGenericID< TCounter >::Counter static private
Definition at line 231 of file AITypes.h.
Index
template<typename TCounter> const TCounter::Type FAIGenericID< TCounter >::Index
Definition at line 229 of file AITypes.h.
The documentation for this struct was generated from the following file:
AITypes.h