Unreal Engine 5.6 C++ API: StructuredArchiveAdapters.h File Reference
StructuredArchiveAdapters.h File Reference
#include "CoreTypes.h"
#include "Concepts/Insertable.h"
#include "Templates/Models.h"
#include "Serialization/ArchiveProxy.h"
#include "Serialization/StructuredArchiveSlots.h"
#include "Templates/UniqueObj.h"
Data Structures
class FArchiveFromStructuredArchive
class FStructuredArchiveFromArchive
Functions
template<typename T, std::enable_if_t<!TModels_V< CInsertable< FArchive & >, T > &&TModels_V< CInsertable< FStructuredArchiveSlot >, T >, int > = 0>
FArchive & operator<< (FArchive &Ar, T &Obj)
Adapter operator which allows a type to stream to an FArchive when it already supports streaming to an FStructuredArchiveSlot.
template<typename T, std::enable_if_t< TModels_V< CInsertable< FArchive & >, T > &&!TModels_V< CInsertable< FStructuredArchiveSlot >, T >, int > = 0>
void operator<< (FStructuredArchiveSlot Slot, T &Obj)
Adapter operator which allows a type to stream to an FStructuredArchiveSlot when it already supports streaming to an FArchive.
Function Documentation
operator<<() [1/2]
template<typename T, std::enable_if_t<!TModels_V< CInsertable< FArchive & >, T > &&TModels_V< CInsertable< FStructuredArchiveSlot >, T >, int > = 0> FArchive & operator<< (FArchive & Ar, T & Obj)
Adapter operator which allows a type to stream to an FArchive when it already supports streaming to an FStructuredArchiveSlot.
Parameters
Ar The archive to read from or write to.
Obj The object to read or write.
Returns
A reference to the same archive as Ar.
Definition at line 125 of file StructuredArchiveAdapters.h.
References Ar, and FStructuredArchiveFromArchive::GetSlot().
operator<<() [2/2]
template<typename T, std::enable_if_t< TModels_V< CInsertable< FArchive & >, T > &&!TModels_V< CInsertable< FStructuredArchiveSlot >, T >, int > = 0> void operator<< (FStructuredArchiveSlot Slot, T & Obj)
Adapter operator which allows a type to stream to an FStructuredArchiveSlot when it already supports streaming to an FArchive.
Parameters
Slot The slot to read from or write to.
Obj The object to read or write.
Definition at line 140 of file StructuredArchiveAdapters.h.
References Ar, FArchiveFromStructuredArchive::Close(), FArchiveFromStructuredArchive::GetArchive(), and UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive().