Unreal Engine 5.6 C++ API: FLargeMemoryData Class Reference
FLargeMemoryData Class Reference
Data storage for the large memory reader and writer.
#include "LargeMemoryData.h"
Public Member Functions
FLargeMemoryData (const int64 PreAllocateBytes=0)
~FLargeMemoryData ()
FORCEINLINE void Append (void *InData, int64 InNum)
Append data at the given offset.
FORCEINLINE uint8 * GetData ()
Returns the written data.
FORCEINLINE const uint8 * GetData () const
Returns the written data.
FORCEINLINE int64 GetSize () const
Gets the size of the data written.
bool HasData () const
Check whether data is allocated or if the ownership was released.
bool Read (void *OutData, int64 InOffset, int64 InNum) const
Read data at the given offset.
uint8 * ReleaseOwnership ()
Releases ownership of the written data.
void Reserve (int64 Size)
bool Write (void *InData, int64 InOffset, int64 InNum)
Write data at the given offset.
Private Member Functions
FLargeMemoryData (const FLargeMemoryData &)=delete
Non-copyable.
void GrowBuffer ()
Resizes the data buffer to at least NumBytes with some slack.
FLargeMemoryData & operator= (const FLargeMemoryData &)=delete
Private Attributes
uint8 * Data
Memory owned by this archive.
int64 MaxBytes
Number of bytes currently allocated for our data buffer.
int64 NumBytes
Number of bytes currently written to our data buffer.
Detailed Description
Data storage for the large memory reader and writer.
Definition at line 16 of file LargeMemoryData.h.
Constructor & Destructor Documentation
FLargeMemoryData() [1/2]
FLargeMemoryData::FLargeMemoryData (const int64 PreAllocateBytes = 0) explicit
Referenced by FLargeMemoryData(), and operator=().
~FLargeMemoryData()
FLargeMemoryData::~FLargeMemoryData ()
FLargeMemoryData() [2/2]
FLargeMemoryData::FLargeMemoryData (const FLargeMemoryData &) private delete
Non-copyable.
References FLargeMemoryData().
Member Function Documentation
Append()
FORCEINLINE void FLargeMemoryData::Append (void * InData, int64 InNum) inline
Append data at the given offset.
Definition at line 27 of file LargeMemoryData.h.
References FORCEINLINE, NumBytes, and Write.
GetData() [1/2]
FORCEINLINE uint8 * FLargeMemoryData::GetData () inline
Returns the written data.
Definition at line 42 of file LargeMemoryData.h.
References Data, and FORCEINLINE.
GetData() [2/2]
FORCEINLINE const uint8 * FLargeMemoryData::GetData () const inline
Returns the written data.
Definition at line 48 of file LargeMemoryData.h.
References Data, and FORCEINLINE.
GetSize()
FORCEINLINE int64 FLargeMemoryData::GetSize () const inline
Gets the size of the data written.
Definition at line 36 of file LargeMemoryData.h.
References FORCEINLINE, and NumBytes.
GrowBuffer()
void FLargeMemoryData::GrowBuffer () private
Resizes the data buffer to at least NumBytes with some slack.
HasData()
bool FLargeMemoryData::HasData () const inline
Check whether data is allocated or if the ownership was released.
Definition at line 57 of file LargeMemoryData.h.
References Data.
operator=()
FLargeMemoryData & FLargeMemoryData::operator= (const FLargeMemoryData &) private delete
References FLargeMemoryData().
Read()
bool FLargeMemoryData::Read (void * OutData, int64 InOffset, int64 InNum) const
Read data at the given offset.
Returns true if the data was read.
ReleaseOwnership()
uint8 * FLargeMemoryData::ReleaseOwnership ()
Releases ownership of the written data.
Reserve()
void FLargeMemoryData::Reserve (int64 Size)
References TSequenceHistory< HistorySize >::Size.
Write()
bool FLargeMemoryData::Write (void * InData, int64 InOffset, int64 InNum)
Write data at the given offset.
Returns true if the data was written.
Field Documentation
Data
uint8* FLargeMemoryData::Data private
Memory owned by this archive.
Ownership can be released by calling ReleaseOwnership()
Definition at line 71 of file LargeMemoryData.h.
Referenced by GetData(), GetData(), and HasData().
MaxBytes
int64 FLargeMemoryData::MaxBytes private
Number of bytes currently allocated for our data buffer.
Definition at line 77 of file LargeMemoryData.h.
NumBytes
int64 FLargeMemoryData::NumBytes private
Number of bytes currently written to our data buffer.
Definition at line 74 of file LargeMemoryData.h.
Referenced by Append(), and GetSize().
The documentation for this class was generated from the following file:
LargeMemoryData.h