Unreal Engine 5.6 C++ API: FMemoryToStringContext Struct Reference
FMemoryToStringContext Struct Reference
#include "MemoryLayout.h"
Public Member Functions
void AppendFrozenPointer (const FTypeLayoutDesc &StaticTypeDesc, int32 FrozenTypeIndex)
void AppendIndent ()
void AppendNullptr ()
void AppendUnfrozenPointer (const FTypeLayoutDesc &StaticTypeDesc)
const FPointerTableBase * TryGetPrevPointerTable () const
Data Fields
int32 Indent = 0
const FPointerTableBase * PrevPointerTable = nullptr
FStringBuilderBase * String = nullptr
Detailed Description
Definition at line 50 of file MemoryLayout.h.
Member Function Documentation
AppendFrozenPointer()
void FMemoryToStringContext::AppendFrozenPointer (const FTypeLayoutDesc & StaticTypeDesc, int32 FrozenTypeIndex)
Referenced by Freeze::IntrinsicToString().
AppendIndent()
void FMemoryToStringContext::AppendIndent ()
AppendNullptr()
void FMemoryToStringContext::AppendNullptr ()
Referenced by Freeze::IntrinsicToString().
AppendUnfrozenPointer()
void FMemoryToStringContext::AppendUnfrozenPointer (const FTypeLayoutDesc & StaticTypeDesc)
Referenced by Freeze::IntrinsicToString().
TryGetPrevPointerTable()
const FPointerTableBase * FMemoryToStringContext::TryGetPrevPointerTable () const inline
Definition at line 57 of file MemoryLayout.h.
References PrevPointerTable.
Referenced by Freeze::IntrinsicToString().
Field Documentation
Indent
int32 FMemoryToStringContext::Indent = 0
Definition at line 61 of file MemoryLayout.h.
PrevPointerTable
const FPointerTableBase* FMemoryToStringContext::PrevPointerTable = nullptr
Definition at line 60 of file MemoryLayout.h.
Referenced by TryGetPrevPointerTable().
String
FStringBuilderBase* FMemoryToStringContext::String = nullptr
Definition at line 59 of file MemoryLayout.h.
The documentation for this struct was generated from the following file:
MemoryLayout.h