Unreal Engine 5.6 C++ API: UE::PixelStreaming Namespace Reference
UE::PixelStreaming Namespace Reference
Helpers for creating webrtc buffers.
Data Structures
struct BufferBuilder
Functions
PIXELSTREAMING_API void ExtendJsonWithField (const FString &Descriptor, FString FieldName, FString StringValue, FString &OutNewDescriptor, bool &OutSuccess)
Extends an existing JSON string with a new name: value property.
PIXELSTREAMING_API void ExtractJsonFromDescriptor (FString Descriptor, FString FieldName, FString &OutStringValue, bool &OutSuccess)
Extract a field's value from a JSON string.
template<typename TCodec>
PIXELSTREAMING_API bool IsDecoderSupported ()
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
template<typename TCodec>
PIXELSTREAMING_API bool IsEncoderSupported ()
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
const void * ValueLoc (FString &&Value)
template<typename T>
const void * ValueLoc (T &&Value)
size_t ValueSize (FString &&Value)
template<typename T>
size_t ValueSize (T &&Value)
Detailed Description
Helpers for creating webrtc buffers.
Function Documentation
ExtendJsonWithField()
PIXELSTREAMING_API void UE::PixelStreaming::ExtendJsonWithField (const FString & Descriptor, FString FieldName, FString StringValue, FString & OutNewDescriptor, bool & OutSuccess)
Extends an existing JSON string with a new name: value property.
Parameters
Descriptor The JSON string.
FieldName The field name to add the json string.
StringValue The value to set in the new field.
OutNewDescriptor The new JSON string.
OutSuccess True if we were able to extend the JSON string.
ExtractJsonFromDescriptor()
PIXELSTREAMING_API void UE::PixelStreaming::ExtractJsonFromDescriptor (FString Descriptor, FString FieldName, FString & OutStringValue, bool & OutSuccess)
Extract a field's value from a JSON string.
Parameters
Descriptor The JSON string.
FieldName The field name to extract a value from.
OutStringValue The value from the extracted field.
OutSuccess True if we were able to extract the value.
IsDecoderSupported()
template<typename TCodec> PIXELSTREAMING_API bool UE::PixelStreaming::IsDecoderSupported () inline
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
To remove nested switch-cases, this function is templated to take a video decoder config of the target codec. eg:
IsDecoderSupported<FVideoDecoderConfigVP8>(); OR IsDecoderSupported<FVideoDecoderConfigAV1>(); OR ...
Definition at line 68 of file PixelStreamingCoderUtils.h.
References Instance, and MakeShared().
IsEncoderSupported()
template<typename TCodec> PIXELSTREAMING_API bool UE::PixelStreaming::IsEncoderSupported () inline
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
To remove nested switch-cases, this function is templated to take a video encoder config of the target codec. eg:
IsEncoderSupported<FVideoEncoderConfigH264>(); OR IsEncoderSupported<FVideoEncoderConfigAV1>(); OR ...
Definition at line 31 of file PixelStreamingCoderUtils.h.
References Instance, and MakeShared().
ValueLoc() [1/2]
const void * UE::PixelStreaming::ValueLoc (FString && Value) inline
Definition at line 30 of file PixelStreamingBufferBuilder.h.
References Value.
ValueLoc() [2/2]
template<typename T> const void * UE::PixelStreaming::ValueLoc (T && Value) inline
Definition at line 20 of file PixelStreamingBufferBuilder.h.
References Value.
Referenced by UE::PixelStreaming::BufferBuilder::Insert().
ValueSize() [1/2]
size_t UE::PixelStreaming::ValueSize (FString && Value) inline
Definition at line 25 of file PixelStreamingBufferBuilder.h.
References Value.
ValueSize() [2/2]
template<typename T> size_t UE::PixelStreaming::ValueSize (T && Value) inline
Definition at line 14 of file PixelStreamingBufferBuilder.h.
References Value.
Referenced by UE::PixelStreaming::BufferBuilder::Insert(), and FPixelStreamingDataChannel::SendMessage().