Unreal Engine 5.6 C++ API: FPlatformMemoryStats Struct Reference
FPlatformMemoryStats Struct Reference
Android implementation of the FGenericPlatformMemoryStats.
#include "AndroidPlatformMemory.h"
Public Member Functions
FPlatformMemoryStats ()
FPlatformMemoryStats ()
Default constructor, clears all variables.
FGenericPlatformMemoryStats::EMemoryPressureStatus GetMemoryPressureStatus () const
EMemoryPressureStatus GetMemoryPressureStatus () const
EMemoryPressureStatus GetMemoryPressureStatus () const
Public Member Functions inherited from FGenericPlatformMemoryStats
FGenericPlatformMemoryStats ()
Default constructor, clears all variables.
uint64 GetAvailablePhysical (bool bExcludeExtraDevMemory) const
EMemoryPressureStatus GetMemoryPressureStatus () const
TArray< FPlatformSpecificStat > GetPlatformSpecificStats () const
void SetEndFrameCsvStats () const
Called by FCsvProfiler::EndFrame to set platform specific CSV stats.
Data Fields
EMemoryPressureStatus MemoryPressureStatus
Status reported by QueryMemoryResourceNotification.
uint64 VMRss = 0
uint64 VMSwap = 0
SIZE_T WindowsSpecificMemoryStat
Example of a memory stat that is specific to Windows.
Data Fields inherited from FGenericPlatformMemoryStats
uint64 AvailablePhysical
The amount of physical memory currently available, in bytes.
uint64 AvailableVirtual
The amount of virtual memory currently available, in bytes.
uint64 PeakUsedPhysical
The peak amount of physical memory used by the process, in bytes.
uint64 PeakUsedVirtual
The peak amount of virtual memory used by the process.
uint64 UsedPhysical
The amount of physical memory used by the process, in bytes.
uint64 UsedVirtual
Total amount of virtual memory used by the process.
Data Fields inherited from FGenericPlatformMemoryConstants
uint64 AddressLimit = (uint64)0xffffffff + 1
An estimate of the range of addresses expected to be returned by BinnedAllocFromOS().
uint64 AddressStart = 0
Starting address for the available virtual address space.
SIZE_T BinnedAllocationGranularity = 0
This is the "allocation granularity" in Binned malloc terms, i.e.
SIZE_T BinnedPageSize = 0
The size of a "page" in Binned2 malloc terms, in bytes.
SIZE_T OsAllocationGranularity = 0
Some platforms have advantages if memory is allocated in chunks larger than PageSize (e.g.
SIZE_T PageSize = 0
The size of a physical page, in bytes.
uint64 TotalPhysical = 0
The amount of actual physical memory, in bytes (needs to handle >4GB for 64-bit devices running 32-bit code).
uint32 TotalPhysicalGB = 1
Approximate physical RAM in GB; 1 on everything except PC.
uint64 TotalVirtual = 0
The amount of virtual memory, in bytes.
Additional Inherited Members
Public Types inherited from FGenericPlatformMemoryStats
enum class EMemoryPressureStatus : uint8 { Unknown , Nominal , Warning , Critical }
Memory pressure states, useful for platforms in which the available memory estimate may not take in to account memory reclaimable from closing inactive processes or resorting to swap.
Detailed Description
Android implementation of the FGenericPlatformMemoryStats.
Windows implementation of the FGenericPlatformMemoryStats.
Unix implementation of the FGenericPlatformMemoryStats.
Max implementation of the FGenericPlatformMemoryStats.
Definition at line 14 of file AndroidPlatformMemory.h.
Constructor & Destructor Documentation
FPlatformMemoryStats() [1/2]
FPlatformMemoryStats::FPlatformMemoryStats () inline
Definition at line 67 of file ApplePlatformMemory.h.
References FGenericPlatformMemoryStats::FGenericPlatformMemoryStats(), MemoryPressureStatus, and FGenericPlatformMemoryStats::Unknown.
FPlatformMemoryStats() [2/2]
FPlatformMemoryStats::FPlatformMemoryStats () inline
Default constructor, clears all variables.
Definition at line 22 of file WindowsPlatformMemory.h.
References FGenericPlatformMemoryStats::FGenericPlatformMemoryStats(), MemoryPressureStatus, FGenericPlatformMemoryStats::Unknown, and WindowsSpecificMemoryStat.
Member Function Documentation
GetMemoryPressureStatus() [1/3]
FGenericPlatformMemoryStats::EMemoryPressureStatus FPlatformMemoryStats::GetMemoryPressureStatus () const
GetMemoryPressureStatus() [2/3]
EMemoryPressureStatus FPlatformMemoryStats::GetMemoryPressureStatus () const inline
Definition at line 72 of file ApplePlatformMemory.h.
References FGenericPlatformMemoryStats::GetMemoryPressureStatus(), MemoryPressureStatus, and FGenericPlatformMemoryStats::Unknown.
GetMemoryPressureStatus() [3/3]
EMemoryPressureStatus FPlatformMemoryStats::GetMemoryPressureStatus () const inline
Definition at line 28 of file WindowsPlatformMemory.h.
References MemoryPressureStatus.
Field Documentation
MemoryPressureStatus
EMemoryPressureStatus FPlatformMemoryStats::MemoryPressureStatus
Status reported by QueryMemoryResourceNotification.
Definition at line 85 of file ApplePlatformMemory.h.
Referenced by FPlatformMemoryStats(), and GetMemoryPressureStatus().
VMRss
uint64 FPlatformMemoryStats::VMRss = 0
Definition at line 18 of file AndroidPlatformMemory.h.
VMSwap
uint64 FPlatformMemoryStats::VMSwap = 0
Definition at line 17 of file AndroidPlatformMemory.h.
WindowsSpecificMemoryStat
SIZE_T FPlatformMemoryStats::WindowsSpecificMemoryStat
Example of a memory stat that is specific to Windows.
Definition at line 34 of file WindowsPlatformMemory.h.
Referenced by FPlatformMemoryStats().
The documentation for this struct was generated from the following files:
AndroidPlatformMemory.h
ApplePlatformMemory.h
WindowsPlatformMemory.h