Unreal Engine 5.6 C++ API: FShaderCompilerOutput Struct Reference
FShaderCompilerOutput Struct Reference
The output of the shader compiler.
#include "ShaderCompilerCore.h"
Public Member Functions
FShaderCompilerOutput ()
FShaderCompilerOutput (const FShaderCompilerOutput &)=default
FShaderCompilerOutput (FShaderCompilerOutput &&)=default
template<typename TValue>
void AddStatistic (const TCHAR *Name, TValue Value, FGenericShaderStat::EFlags Flags=FGenericShaderStat::EFlags::None, FName TagName=NAME_None)
RENDERCORE_API void CompressOutput (FName ShaderCompressionFormat, FOodleDataCompression::ECompressor OodleCompressor, FOodleDataCompression::ECompressionLevel OodleLevel)
Calls GenerateOutputHash() before the compression, replaces FShaderCode with the compressed data (if compression result was smaller).
RENDERCORE_API void GenerateOutputHash ()
Generates OutputHash from the compiler output.
const FShaderCodeResource & GetFinalizedCodeResource () const
FShaderCompilerOutput & operator= (const FShaderCompilerOutput &)=default
FShaderCompilerOutput & operator= (FShaderCompilerOutput &&)=default
RENDERCORE_API void SerializeShaderCodeValidation ()
Add optional data in ShaderCode to perform additional shader input validation at runtime.
RENDERCORE_API void SerializeShaderDiagnosticData ()
Add optional diagnostic data in ShaderCode to perform assert translation at runtime.
void SetCodeFromResource (FShaderCodeResource &&Resource)
Data Fields
bool bSerializeModifiedSource
bool bSerializingForCache
bool bSucceeded
bool bSupportsQueryingUsedAttributes
double CompileTime
TArray< FShaderCompilerError > Errors
FString ModifiedEntryPointName
Use this field to store the entry point name if it's modified as part of the shader format's compilation process.
FString ModifiedShaderSource
Use this field to store the shader source code if it's modified as part of the shader format's compilation process.
uint32 NumInstructions
uint32 NumTextureSamplers
FSHAHash OutputHash
FShaderParameterMap ParameterMap
TArray< FShaderCodeValidationType > ParametersSRVTypeToValidate
TArray< FShaderCodeValidationStride > ParametersStrideToValidate
TArray< FShaderCodeValidationType > ParametersUAVTypeToValidate
TArray< FShaderCodeValidationUBSize > ParametersUBSizeToValidate
TArray< uint8 > PlatformDebugData
TArray< FString > PragmaDirectives
double PreprocessTime
FShaderCode ShaderCode
TArray< FShaderDiagnosticData > ShaderDiagnosticDatas
TArray< FGenericShaderStat > ShaderStatistics
FShaderTarget Target
TArray< FString > UsedAttributes
FShaderCompilerInputHash ValidateInputHash
Friends
FArchive & operator<< (FArchive &Ar, FShaderCompilerOutput &Output)
Detailed Description
The output of the shader compiler.
Bump UE_SHADER_CACHE_VERSION and ShaderCompileWorkerOutputVersion if FShaderCompilerOutput changes
Definition at line 486 of file ShaderCompilerCore.h.
Constructor & Destructor Documentation
FShaderCompilerOutput() [1/3]
FShaderCompilerOutput::FShaderCompilerOutput () inline
Definition at line 488 of file ShaderCompilerCore.h.
References bSerializingForCache, bSucceeded, bSupportsQueryingUsedAttributes, CompileTime, NumInstructions, NumTextureSamplers, and PreprocessTime.
Referenced by FShaderCompilerOutput(), FShaderCompilerOutput(), operator<<, operator=(), and operator=().
FShaderCompilerOutput() [2/3]
FShaderCompilerOutput::FShaderCompilerOutput (FShaderCompilerOutput &&) default
References FShaderCompilerOutput().
FShaderCompilerOutput() [3/3]
FShaderCompilerOutput::FShaderCompilerOutput (const FShaderCompilerOutput &) default
References FShaderCompilerOutput().
Member Function Documentation
AddStatistic()
template<typename TValue> void FShaderCompilerOutput::AddStatistic (const TCHAR * Name, TValue Value, FGenericShaderStat::EFlags Flags = FGenericShaderStat::EFlags::None, FName TagName = NAME_None) inline
Definition at line 564 of file ShaderCompilerCore.h.
References AddStatistic(), Flags, FName, Name, None, ShaderStatistics, Stat, and Value.
Referenced by AddStatistic().
CompressOutput()
RENDERCORE_API void FShaderCompilerOutput::CompressOutput (FName ShaderCompressionFormat, FOodleDataCompression::ECompressor OodleCompressor, FOodleDataCompression::ECompressionLevel OodleLevel)
Calls GenerateOutputHash() before the compression, replaces FShaderCode with the compressed data (if compression result was smaller).
References CompressOutput().
Referenced by CompressOutput().
GenerateOutputHash()
RENDERCORE_API void FShaderCompilerOutput::GenerateOutputHash ()
Generates OutputHash from the compiler output.
References GenerateOutputHash().
Referenced by GenerateOutputHash().
GetFinalizedCodeResource()
const FShaderCodeResource & FShaderCompilerOutput::GetFinalizedCodeResource () const inline
Definition at line 573 of file ShaderCompilerCore.h.
References OutputHash, ShaderCode, and Target.
operator=() [1/2]
FShaderCompilerOutput & FShaderCompilerOutput::operator= (const FShaderCompilerOutput &) default
References FShaderCompilerOutput(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FShaderCompilerOutput & FShaderCompilerOutput::operator= (FShaderCompilerOutput &&) default
References FShaderCompilerOutput().
SerializeShaderCodeValidation()
RENDERCORE_API void FShaderCompilerOutput::SerializeShaderCodeValidation ()
Add optional data in ShaderCode to perform additional shader input validation at runtime.
References SerializeShaderCodeValidation().
Referenced by SerializeShaderCodeValidation().
SerializeShaderDiagnosticData()
RENDERCORE_API void FShaderCompilerOutput::SerializeShaderDiagnosticData ()
Add optional diagnostic data in ShaderCode to perform assert translation at runtime.
References SerializeShaderDiagnosticData().
Referenced by SerializeShaderDiagnosticData().
SetCodeFromResource()
void FShaderCompilerOutput::SetCodeFromResource (FShaderCodeResource && Resource) inline
Definition at line 578 of file ShaderCompilerCore.h.
References MoveTemp(), and ShaderCode.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderCompilerOutput & Output) friend
Definition at line 584 of file ShaderCompilerCore.h.
References FShaderCompilerOutput(), Ar, bSerializingForCache, bSucceeded, CompileTime, Errors, ModifiedEntryPointName, ModifiedShaderSource, NumInstructions, NumTextureSamplers, OutputHash, ParameterMap, ShaderCode, ShaderStatistics, Target, and ValidateInputHash.
Field Documentation
bSerializeModifiedSource
bool FShaderCompilerOutput::bSerializeModifiedSource
Definition at line 514 of file ShaderCompilerCore.h.
bSerializingForCache
bool FShaderCompilerOutput::bSerializingForCache
Definition at line 515 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput(), and operator<<.
bSucceeded
bool FShaderCompilerOutput::bSucceeded
Definition at line 511 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput(), and operator<<.
bSupportsQueryingUsedAttributes
bool FShaderCompilerOutput::bSupportsQueryingUsedAttributes
Definition at line 512 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput().
CompileTime
double FShaderCompilerOutput::CompileTime
Definition at line 509 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput(), and operator<<.
Errors
TArray<FShaderCompilerError> FShaderCompilerOutput::Errors
Definition at line 500 of file ShaderCompilerCore.h.
Referenced by operator<<.
ModifiedEntryPointName
FString FShaderCompilerOutput::ModifiedEntryPointName
Use this field to store the entry point name if it's modified as part of the shader format's compilation process.
This field is only currently required for shader formats which implement the independent preprocessing API And should only be set when compilation requires a different entry point than was set on the FShaderCompilerInput struct.
Definition at line 544 of file ShaderCompilerCore.h.
Referenced by operator<<.
ModifiedShaderSource
FString FShaderCompilerOutput::ModifiedShaderSource
Use this field to store the shader source code if it's modified as part of the shader format's compilation process.
This should only be set when additional manipulation of source code is required that is not part of the implementation of PreprocessShader. This version of the source, if set, will be what is written as part of the debug dumps of preprocessed source, as well as used for upstream code which explicitly requests the final source code for other purposes (i.e. when ExtraSettings.bExtractShaderSource is set on the FShaderCompilerInput struct)
Definition at line 539 of file ShaderCompilerCore.h.
Referenced by operator<<.
NumInstructions
uint32 FShaderCompilerOutput::NumInstructions
Definition at line 507 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput(), and operator<<.
NumTextureSamplers
uint32 FShaderCompilerOutput::NumTextureSamplers
Definition at line 508 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput(), and operator<<.
OutputHash
FSHAHash FShaderCompilerOutput::OutputHash
Definition at line 505 of file ShaderCompilerCore.h.
Referenced by GetFinalizedCodeResource(), and operator<<.
ParameterMap
FShaderParameterMap FShaderCompilerOutput::ParameterMap
Definition at line 499 of file ShaderCompilerCore.h.
Referenced by operator<<.
ParametersSRVTypeToValidate
TArray<FShaderCodeValidationType> FShaderCompilerOutput::ParametersSRVTypeToValidate
Definition at line 528 of file ShaderCompilerCore.h.
ParametersStrideToValidate
TArray<FShaderCodeValidationStride> FShaderCompilerOutput::ParametersStrideToValidate
Definition at line 527 of file ShaderCompilerCore.h.
ParametersUAVTypeToValidate
TArray<FShaderCodeValidationType> FShaderCompilerOutput::ParametersUAVTypeToValidate
Definition at line 529 of file ShaderCompilerCore.h.
ParametersUBSizeToValidate
TArray<FShaderCodeValidationUBSize> FShaderCompilerOutput::ParametersUBSizeToValidate
Definition at line 530 of file ShaderCompilerCore.h.
PlatformDebugData
TArray<uint8> FShaderCompilerOutput::PlatformDebugData
Definition at line 547 of file ShaderCompilerCore.h.
PragmaDirectives
TArray<FString> FShaderCompilerOutput::PragmaDirectives
Definition at line 502 of file ShaderCompilerCore.h.
PreprocessTime
double FShaderCompilerOutput::PreprocessTime
Definition at line 510 of file ShaderCompilerCore.h.
Referenced by FShaderCompilerOutput().
ShaderCode
FShaderCode FShaderCompilerOutput::ShaderCode
Definition at line 504 of file ShaderCompilerCore.h.
Referenced by GetFinalizedCodeResource(), operator<<, and SetCodeFromResource().
ShaderDiagnosticDatas
TArray<FShaderDiagnosticData> FShaderCompilerOutput::ShaderDiagnosticDatas
Definition at line 532 of file ShaderCompilerCore.h.
ShaderStatistics
TArray<FGenericShaderStat> FShaderCompilerOutput::ShaderStatistics
Definition at line 549 of file ShaderCompilerCore.h.
Referenced by AddStatistic(), and operator<<.
Target
FShaderTarget FShaderCompilerOutput::Target
Definition at line 503 of file ShaderCompilerCore.h.
Referenced by GetFinalizedCodeResource(), and operator<<.
UsedAttributes
TArray<FString> FShaderCompilerOutput::UsedAttributes
Definition at line 516 of file ShaderCompilerCore.h.
ValidateInputHash
FShaderCompilerInputHash FShaderCompilerOutput::ValidateInputHash
Definition at line 506 of file ShaderCompilerCore.h.
Referenced by operator<<.
The documentation for this struct was generated from the following file:
ShaderCompilerCore.h