Unreal Engine 5.6 C++ API: FRigVMNewEditor Class Reference
FRigVMNewEditor Class Reference
#include "RigVMNewEditor.h"
Public Member Functions
FRigVMNewEditor ()
virtual void AddAutoCompileWidget (FToolBarBuilder &ToolbarBuilder) override
virtual void AddCompileWidget (FToolBarBuilder &ToolbarBuilder) override
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
virtual void AddSelectedDebugObjectWidget (FToolBarBuilder &ToolbarBuilder) override
virtual void AddSettingsAndDefaultWidget (FToolBarBuilder &ToolbarBuilder) override
bool CanSelectAllNodes () const
virtual void ClearSelectionStateFor (FName SelectionOwner)
virtual void Compile ()
void CreateDefaultTabContents (const TArray< UBlueprint * > InBlueprints)
UEdGraphNode * FindNodeWithError (FCompilerResultsLog const &ErrorLog, EMessageSeverity::Type Severity)
UEdGraphNode * FindNodeWithError (UBlueprint *Blueprint, EMessageSeverity::Type Severity)
TSharedRef< SWidget > GenerateCompileOptionsMenu ()
TSharedRef< SWidget > GetCompilerResults () const
FSlateIcon GetCompileStatusImage () const
FText GetCompileStatusTooltip () const
TSharedRef< SRigVMFindReferences > GetFindResults () const
virtual const TSharedPtr< FAssetEditorToolkit > GetHostingApp () const override
virtual TSharedPtr< FAssetEditorToolkit > GetHostingApp () override
float GetInstructionTextOpacity (UEdGraph *InGraph) const
virtual bool GetIsContextSensitive () override
virtual FNotifyHook * GetNotifyHook () override
virtual const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const override
virtual FPreviewScene * GetPreviewScene () override
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
virtual TSharedPtr< SRigVMDetailsInspector > GetRigVMInspector () const override
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
virtual FLinearColor GetWorldCentricTabColorScale () const override
virtual void HandleSetObjectBeingDebugged (UObject *InObject)
bool IsJumpToErrorNodeOptionSet ()
bool IsSaveOnCompileEnabled () const
bool IsSaveOnCompileOptionSet (TWeakPtr< FRigVMNewEditor > Editor, ESaveOnCompile Option)
virtual void JumpToHyperlink (const UObject *ObjectReference, bool bRequestRename) override
void MakeSaveOnCompileSubMenu (FMenuBuilder &InMenu)
void OnAlignBottom ()
void OnAlignCenter ()
void OnAlignLeft ()
void OnAlignMiddle ()
void OnAlignRight ()
void OnAlignTop ()
virtual void OnClose () override
Called when this toolkit is being closed.
virtual void OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList)
void OnDistributeNodesH ()
void OnDistributeNodesV ()
virtual void OnFinishedChangingProperties (const FPropertyChangedEvent &PropertyChangedEvent)
delegate for changing property
virtual void OnGraphEditorBackgrounded (const TSharedRef< SGraphEditor > &InGraphEditor)
virtual void OnGraphEditorFocused (const TSharedRef< SGraphEditor > &InGraphEditor)
void OnSelectedNodesChanged (const FGraphPanelSelectionSet &NewSelection)
virtual FReply OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f &InPosition, UEdGraph *InGraph)
void OnStraightenConnections ()
virtual void RegisterTabSpawners (const TSharedRef< class FTabManager > &InTabManager) override
IToolkit interface.
virtual void RegisterToolbarTab (const TSharedRef< FTabManager > &InTabManager) override
virtual void RestoreEditedObjectState () override
void SelectAllNodes ()
virtual void SetInspector (TSharedPtr< SRigVMDetailsInspector > InWidget)
virtual void SetIsContextSensitive (const bool bIsContextSensitive) override
void SetSaveOnCompileSetting (ESaveOnCompile NewSetting)
virtual void SetupViewForBlueprintEditingMode () override
virtual TSharedRef< const IRigVMEditor > SharedRef () const override
virtual TSharedRef< IRigVMEditor > SharedRef () override
virtual bool ShouldOpenGraphByDefault () const
virtual void StartEditingDefaults (bool bAutoFocus=true, bool bForceRefresh=false)
virtual void SummonSearchUI (bool bSetFindWithinBlueprint, FString NewSearchTerms, bool bSelectFirstResult) override
void ToggleJumpToErrorNodeSetting ()
Public Member Functions inherited from FWorkflowCentricApplication
UNREALED_API FName GetCurrentMode () const
TSharedPtr< FApplicationMode > GetCurrentModePtr () const
virtual UNREALED_API FName GetToolMenuToolbarName (FName &OutParentName) const override
Get name used by tool menu.
UNREALED_API FName GetToolMenuToolbarNameForMode (const FName InModeName, FName &OutParentName) const
bool IsModeCurrent (FName ModeToCheck) const
virtual UNREALED_API bool OnRequestClose (EAssetEditorCloseReason InCloseReason) override
Called when this toolkit is requested to close.
UNREALED_API void PushTabFactories (FWorkflowAllowedTabSet &FactorySetToPush) const
virtual UNREALED_API UToolMenu * RegisterModeToolbarIfUnregistered (const FName InModeName)
Registers toolbar for a mode if not already registered.
virtual UNREALED_API void UnregisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
Public Member Functions inherited from FAssetEditorToolkit
UNREALED_API FAssetEditorToolkit ()
Default constructor.
FAssetEditorToolkit (const FAssetEditorToolkit &)=delete
virtual UNREALED_API ~FAssetEditorToolkit ()
Virtual destructor, so that we can clean up our app when destroyed.
virtual void AddGraphEditorPinActionsToContextMenu (FToolMenuSection &InSection) const
UNREALED_API void AddMenuExtender (TSharedPtr< FExtender > Extender)
Adds or removes extenders to the default menu or the toolbar menu this asset editor.
UNREALED_API void AddToolbarExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void AddToolbarWidget (TSharedRef< SWidget > Widget)
Adds or removes widgets from the default toolbar in this asset editor.
virtual void AddViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget, int32 ZOrder=INDEX_NONE)
virtual UNREALED_API bool CloseWindow (EAssetEditorCloseReason InCloseReason) override
virtual UNREALED_API TSharedPtr< SWidget > CreateMenuBar (const TSharedPtr< FTabManager > &InTabManager, const FName InMenuName, FToolMenuContext &InToolMenuContext)
Method that can be overriden by derived classes to provide a custom MenuBar to the Standalone Toolkit Host.
UNREALED_API void FillDefaultAssetMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for modifying this asset that are generally common to most asset editors.
UNREALED_API void FillDefaultFileMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultFileMenuOpenCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultHelpMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for the help menu.
virtual UNREALED_API void FocusWindow (UObject *ObjectToFocusOn=nullptr) override
UNREALED_API void GenerateToolbar ()
Makes a default asset editing toolbar.
virtual UNREALED_API TSharedPtr< FTabManager > GetAssociatedTabManager () override
virtual FText GetBaseToolkitName () const override=0
virtual UNREALED_API FName GetEditingAssetTypeName () const override
virtual UNREALED_API FEditorModeTools & GetEditorModeManager () const final
virtual UNREALED_API FName GetEditorName () const override
IAssetEditorInstance interface.
virtual UNREALED_API double GetLastActivationTime () override
virtual UNREALED_API EAssetOpenMethod GetOpenMethod () const override
UNREALED_API TSharedPtr< IToolkitHost > GetPreviousWorldCentricToolkitHost ()
virtual UNREALED_API UE::Editor::Toolbars::ECreateStatusBarOptions GetStatusBarCreationOptions () const
Called by StandaloneAssetEditorToolkitHost to determine what sections of the StatusBar should be created.
TSharedPtr< FTabManager > GetTabManager ()
virtual UNREALED_API FText GetTabSuffix () const override
virtual FName GetToolkitFName () const override=0
virtual UNREALED_API FText GetToolkitName () const override
virtual UNREALED_API FText GetToolkitToolTipText () const override
UNREALED_API FName GetToolMenuAppName () const
UNREALED_API FName GetToolMenuName () const
UNREALED_API FName GetToolMenuToolbarName () const
virtual FString GetWorldCentricTabPrefix () const override=0
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
Initializes this asset editor.
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject *ObjectToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
virtual UNREALED_API void InvokeTab (const FTabId &TabId) override
UNREALED_API bool IsActuallyAnAsset () const
True if this actually is editing an asset.
virtual UNREALED_API bool IsAssetEditor () const override
virtual bool IsPrimaryEditor () const override
virtual void OnToolkitHostingFinished (const TSharedRef< IToolkit > &Toolkit)
virtual void OnToolkitHostingStarted (const TSharedRef< IToolkit > &Toolkit)
virtual void OnViewportDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
React to a Drag&Drop events from the viewport.
virtual void OnViewportDragLeave (const FDragDropEvent &DragDropEvent)
virtual FReply OnViewportDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
FAssetEditorToolkit & operator= (const FAssetEditorToolkit &)=delete
virtual void PostRegenerateMenusAndToolbars ()
Called at the end of RegenerateMenusAndToolbars()
UNREALED_API void RegenerateMenusAndToolbars ()
Regenerates the menubar and toolbar widgets.
UNREALED_API void RegisterDrawer (struct FWidgetDrawerConfig &&Drawer, int32 SlotIndex=INDEX_NONE)
Registers a drawer for the asset editor status bar.
UNREALED_API void RemoveAllToolbarWidgets ()
virtual UNREALED_API void RemoveEditingAsset (UObject *Asset) override
UNREALED_API void RemoveMenuExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void RemoveToolbarExtender (TSharedPtr< FExtender > Extender)
virtual void RemoveViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget)
Called when a toolkit requests the overlay widget to be removed.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout)
Applies the passed in layout (or the saved user-modified version if available).
UNREALED_API void SetMenuOverlay (TSharedRef< SWidget > Widget)
Allows the caller to set a menu overlay, displayed to the far right of the editor's menu bar.
UE_DEPRECATED (4.26, "Override CreateEditorModeManager on the toolkit class instead.") UNREALED_API void SetAssetEditorModeManager(class FAssetEditorModeManager *InModeManager)
Set the asset editor mode manager we are using.
UE_DEPRECATED (4.26, "Use GetEditorModeManager instead.") UNREALED_API class FAssetEditorModeManager *GetAssetEditorModeManager() const
Get the asset editor mode manager we are using.
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") UNREALED_API virtual bool CloseWindow() override
Public Member Functions inherited from IAssetEditorInstance
virtual bool IncludeAssetInRestoreOpenAssetsPrompt (UObject *Asset) const
virtual void InvokeTab (const struct FTabId &TabId)=0
UE_DEPRECATED (5.0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") virtual FName GetToolbarTabId() const
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") virtual bool CloseWindow()
UE_DEPRECATED (5.4, "Use the override that takes in an UObject instead") virtual bool IncludeAssetInRestoreOpenAssetsPrompt() const
If false, the asset being edited will not be included in reopen assets prompt on restart.
Public Member Functions inherited from FBaseToolkit
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API FName GetToolkitContextFName () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsBlueprintEditor () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Public Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedRef< FAssetEditorToolkit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAssetEditorToolkit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FRigVMEditorBase
bool CanCopyNodes () const
bool CanCutNodes () const
bool CanDeleteNodes () const
bool CanDuplicateNodes () const
bool CanPasteNodes () const
bool CanStartWatchingPin () const
bool CanStopWatchingPin () const
void Compile ()
void CopySelectedNodes ()
void CutSelectedNodes ()
void DeleteSelectedNodes ()
void DuplicateNodes ()
FText GetGraphDecorationString (UEdGraph *InGraph) const
virtual URigVMBlueprint * GetRigVMBlueprint () const override
void HandleJumpToHyperlink (const UObject *InSubject)
virtual void InitRigVMEditor (const EToolkitMode::Type Mode, const TSharedPtr< class IToolkitHost > &InitToolkitHost, class URigVMBlueprint *InRigVMBlueprint)
Edits the specified asset(s)
bool IsCompilingEnabled () const
virtual bool IsEditable (UEdGraph *InGraph) const override
virtual void OnGraphNodeDropToPerform (TSharedPtr< FDragDropOperation > InDragDropOp, UEdGraph *InGraph, const FVector2f &InNodePosition, const FVector2f &InScreenPosition) override
virtual FOnRefreshEvent OnRefresh () override
void OnStartWatchingPin ()
void OnStopWatchingPin ()
void PasteNodes ()
Public Member Functions inherited from IRigVMEditor
DECLARE_EVENT (IRigVMEditor, FOnRefreshEvent)
DECLARE_EVENT_OneParam (IRigVMEditor, FPreviewHostUpdated, IRigVMEditor *)
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FNotifyHook
virtual void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, class FEditPropertyChain *PropertyThatChanged)
virtual void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged)
virtual void NotifyPreChange (class FEditPropertyChain *PropertyAboutToChange)
virtual void NotifyPreChange (FProperty *PropertyAboutToChange)
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Public Member Functions inherited from FEditorUndoClient
virtual UNREALED_API ~FEditorUndoClient ()
Always unregister for undo on destruction, just in case.
virtual FString GetTransactionContext () const
Return the transaction context for this client.
virtual bool MatchesContext (const FTransactionContext &InContext, const TArray< TPair< UObject *, FTransactionObjectEvent > > &TransactionObjectContexts) const
Called to see if the context of the current undo/redo operation is a match for the client Default state matching old context-less undo is Context="" and PrimaryObject=NULL.
Static Public Member Functions
static const FSlateBrush * GetGlyphForGraph (const UEdGraph *Graph, bool bInLargeIcon)
static const FName SelectionState_ClassDefaults ()
static const FName SelectionState_ClassSettings ()
static const FName SelectionState_Graph ()
static const FName SelectionState_GraphExplorer ()
Static Public Member Functions inherited from FWorkflowCentricApplication
static TArray< FWorkflowApplicationModeExtender > & GetModeExtenderList ()
Static Public Member Functions inherited from FAssetEditorToolkit
static UNREALED_API FText GetLabelForObject (const UObject *InObject)
Gets the text to display in a toolkit titlebar for an object.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedMenuExtensibilityManager ()
Returns the default extensibility managers, these are applied for all asset types.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedToolBarExtensibilityManager ()
static UNREALED_API FText GetToolTipTextForObject (const UObject *InObject)
Gets the text to display in a toolkit tooltip for an object.
static UNREALED_API void RegisterDefaultToolBar ()
Registers default tool bar.
static UNREALED_API void SetPreviousWorldCentricToolkitHostForNewAssetEditor (TSharedRef< IToolkitHost > ToolkitHost)
Static: Used internally to set the world-centric toolkit host for a newly-created standalone asset editing toolkit.
Static Public Member Functions inherited from FRigVMEditorBase
static FRigVMEditorBase * GetFromAssetEditorInstance (IAssetEditorInstance *Instance)
static FSlateBrush const * GetVarIconAndColorFromPinType (const FEdGraphPinType &PinType, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
static FSlateBrush const * GetVarIconAndColorFromProperty (const FProperty *Property, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Protected Member Functions
virtual void AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode) override
virtual void AddMenuExtender (TSharedPtr< FExtender > Extender) override
virtual void AddReferencedObjectsImpl (FReferenceCollector &Collector) override
virtual void AddToolbarExtender (TSharedPtr< FExtender > Extender) override
virtual void AnalyticsTrackNodeEvent (UBlueprint *Blueprint, UEdGraphNode *GraphNode, bool bNodeDelete) const override
virtual void BringToolkitToFrontImpl () override
virtual void CloseDocumentTab (const UObject *DocumentID) override
virtual void CommonInitialization (const TArray< UBlueprint * > &InitBlueprints, bool bShouldOpenInDefaultsMode) override
virtual void CompileImpl () override
virtual void CreateDefaultCommands () override
virtual TSharedPtr< FApplicationMode > CreateEditorMode () override
virtual void CreateEditorToolbar () override
virtual TSharedRef< SGraphEditor > CreateGraphEditorWidget (TSharedRef< FTabInfo > InTabInfo, UEdGraph *InGraph) override
void DumpMessagesToCompilerLog (const TArray< TSharedRef< class FTokenizedMessage > > &Messages, bool bForceMessageDisplay)
Dumps messages to the compiler log, with an option to force it to display/come to front.
virtual void EditClassDefaults_Clicked () override
virtual void EditGlobalOptions_Clicked () override
virtual bool FindOpenTabsContainingDocument (const UObject *DocumentID, TArray< TSharedPtr< SDockTab > > &Results) override
virtual TSharedPtr< IMessageLogListing > GetCompilerResultsListing () override
virtual UEdGraphPin * GetCurrentlySelectedPin () const override
virtual TSharedPtr< FDocumentTracker > GetDocumentManager () const override
virtual const TArray< UObject * > & GetEditingBlueprints () const override
virtual const FName GetEditorAppName () const override
virtual UEdGraph * GetFocusedGraph () const override
virtual TWeakPtr< SGraphEditor > GetFocusedGraphEditor () override
virtual FGraphAppearanceInfo GetGraphAppearanceImpl (UEdGraph *InGraph) const override
virtual TWeakPtr< FDocumentTabFactory > GetGraphEditorTabFactory () const override
virtual FName GetGraphExplorerWidgetID () override
virtual FEdGraphPinType GetLastPinTypeUsed () override
virtual void GetPinTypeSelectorFilters (TArray< TSharedPtr< IPinTypeSelectorFilter > > &OutFilters) const override
virtual FGraphPanelSelectionSet GetSelectedNodes () const override
virtual FName GetSelectedVariableName () override
virtual TSharedPtr< FTabManager > GetTabManager () override
virtual TSharedRef< FUICommandList > GetToolkitCommands () override
virtual FEditorModeTools & GetToolkitEditorModeManager () const override
virtual const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable, const bool bInUseSmallToolbarIcons, const TOptional< EAssetOpenMethod > &InOpenMethod) override
virtual void InitToolMenuContext (FToolMenuContext &MenuContext) override
bool IsDetailsPanelEditingClassDefaults () const
bool IsDetailsPanelEditingGlobalOptions () const
virtual bool IsEditableImpl (UEdGraph *InGraph) const override
virtual bool IsGraphInCurrentBlueprint (const UEdGraph *InGraph) const override
virtual bool IsHosted () const override
virtual bool IsNodeTitleVisible (const UEdGraphNode *Node, bool bRequestRename) override
virtual bool IsSectionVisible (RigVMNodeSectionID::Type InSectionID) const
virtual void JumpToNode (const UEdGraphNode *Node, bool bRequestRename) override
virtual void JumpToPin (const UEdGraphPin *Pin) override
virtual void LogSimpleMessage (const FText &MessageText) override
virtual bool NewDocument_IsVisibleForType (ECreatedDocumentType GraphType) const
virtual void NotifyPostChangeImpl (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged) override
virtual void NotifyPreChangeImpl (FProperty *PropertyAboutToChange) override
virtual void OnAddNewVariable () override
void OnBlueprintChanged (UBlueprint *InBlueprint)
virtual void OnBlueprintChangedInnerImpl (UBlueprint *InBlueprint, bool bIsJustBeingCompiled) override
virtual FActionMenuContent OnCreateGraphActionMenu (UEdGraph *InGraph, const FVector2f &InNodePosition, const TArray< UEdGraphPin * > &InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed) override
void OnLogTokenClicked (const TSharedRef< IMessageToken > &MessageToken)
virtual TSharedPtr< SDockTab > OpenDocument (const UObject *DocumentID, FDocumentTracker::EOpenDocumentCause Cause) override
virtual TSharedPtr< SGraphEditor > OpenGraphAndBringToFront (UEdGraph *Graph, bool bSetFocus=true) override
virtual void PostLayoutBlueprintEditorInitialization () override
virtual void PostRedo (bool bSuccess) override
virtual void PostUndo (bool bSuccess) override
virtual void RefreshEditorsImpl (ERefreshRigVMEditorReason::Type Reason) override
virtual void RefreshInspector () override
virtual void RefreshStandAloneDefaultsEditor () override
virtual void RegenerateMenusAndToolbars () override
virtual void RemoveMenuExtender (TSharedPtr< FExtender > Extender) override
virtual void RemoveToolbarExtender (TSharedPtr< FExtender > Extender) override
virtual void RenameNewlyAddedAction (FName InActionName) override
virtual void SaveAsset_Execute_Impl () override
virtual void SaveAssetAs_Execute_Impl () override
void SaveEditedObjectState ()
virtual void SetCurrentMode (FName NewMode) override
virtual void SetUISelectionState (FName SelectionOwner) override
virtual void SetupGraphEditorEventsImpl (UEdGraph *InGraph, SGraphEditor::FGraphEditorEvents &InEvents) override
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
virtual bool TransactionObjectAffectsBlueprint (UObject *InTransactedObject) override
virtual void TryInvokingDetailsTab (bool bFlash=true) override
virtual void ZoomToSelection_Clicked () override
Protected Member Functions inherited from FWorkflowCentricApplication
virtual UNREALED_API const TMap< FName, TSharedPtr< FApplicationMode > > & GetApplicationModeList () const
virtual UNREALED_API void RemoveAllApplicationModes ()
virtual UNREALED_API bool RemoveApplicationMode (FName ModeName)
Protected Member Functions inherited from FAssetEditorToolkit
virtual UNREALED_API void AddEditingObject (UObject *Object)
Adds an item to the Editing Objects list.
virtual UNREALED_API void BrowseDocumentation_Execute () const
Called when "Browse Documentation" is clicked for this asset.
virtual bool CanFindInContentBrowser () const
Called to test if "Find in Content Browser" should be enabled for this asset.
virtual UNREALED_API bool CanReimport () const
Called to check to see if there's an asset capable of being reimported.
virtual UNREALED_API bool CanReimport (UObject *EditingObject) const
bool CanReimport_Internal () const
Internal function to check if the asset can be reimported that calls CanReimport.
virtual bool CanSaveAsset () const
Called to test if "Save" should be enabled for this asset.
bool CanSaveAsset_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAsset.
virtual bool CanSaveAssetAs () const
Called to test if "Save As" should be enabled for this asset.
bool CanSaveAssetAs_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAssetAs.
virtual UNREALED_API void CreateEditorModeManager () override
virtual UNREALED_API void FindInContentBrowser_Execute ()
Called when "Find in Content Browser" is clicked for this asset.
virtual UNREALED_API UToolMenu * GenerateCommonActionsToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for common asset actions like Save.
UToolMenu * GenerateReadOnlyToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for read only mode specific content.
virtual UNREALED_API FLinearColor GetDefaultTabColor () const
virtual UNREALED_API const FSlateBrush * GetDefaultTabIcon () const
virtual UNREALED_API FString GetDocumentationLink () const
UNREALED_API UObject * GetEditingObject () const
Returns the single object currently being edited.
UNREALED_API TArray< TObjectPtr< UObject > > & GetEditingObjectPtrs ()
UNREALED_API const TArray< UObject * > & GetEditingObjects () const
Returns an array of all the objects currently being edited.
virtual UNREALED_API FName GetReadOnlyMenuProfileName ()
Get the name of the profile registered with UToolMenus for read only menu customizations.
virtual UNREALED_API void GetSaveableObjects (TArray< UObject * > &OutObjects) const
Get the collection of edited objects that can be saved.
virtual UNREALED_API EVisibility GetVisibilityWhileAssetCompiling () const
Called to get the desired visibility when the asset is compiling.
bool HasEditingObject () const
Returns true if this toolkit has any objects being edited.
virtual bool IsFindInContentBrowserButtonVisible () const
Called to test if "Find in Content Browser" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetAsVisible () const
Called to test if "Save As" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetVisible () const
Called to test if "Save" should be visible for this asset.
virtual UNREALED_API void MapToolkitCommands ()
Can be overriden to prevent registering the default commands.
virtual void OnAssetsSaved (const TArray< UObject * > &SavedObjects)
Called from SaveAsset_Execute when assets have been saved.
virtual void OnAssetsSavedAs (const TArray< UObject * > &SavedObjects)
Called from SaveAssetAs_Execute when assets have been saved.
virtual void PostInitAssetEditor ()
Perform any initialization that should happen after the basic toolkit needs are created for the asset editor.
virtual UNREALED_API void Reimport_Execute ()
Called when "Reimport" is clicked for this asset.
virtual UNREALED_API void Reimport_Execute (UObject *EditingObject)
virtual UNREALED_API void RemoveEditingObject (UObject *Object)
Removes an item from the Editing Objects list.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout, bool bLoadUserLayout)
Applies the passed in layout.
virtual UNREALED_API void SaveAsset_Execute ()
Called when "Save" is clicked for this asset.
virtual UNREALED_API void SaveAssetAs_Execute ()
Called when "Save As" is clicked for this asset.
virtual UNREALED_API void SetupReadOnlyMenuProfiles (FReadOnlyAssetEditorCustomization &OutReadOnlyCustomization)
Specify the permission lists to use in read only mode.
virtual UNREALED_API bool ShouldPromptForNewFilesOnReload (const UObject &object) const
Called to determine if the user should be prompted for a new file if one is missing during an asset reload.
virtual bool ShouldReopenEditorForSavedAsset (const UObject *Asset) const
Whether to open a new asset editor for the newly-saved Asset.
UE_DEPRECATED (4.26, "Use EditorModeManager instead.") FAssetEditorModeManager *AssetEditorModeManager
UE_DEPRECATED (5.3, "Use OnRequestClose that takes in an EAssetEditorCloseReason instead") virtual bool OnRequestClose()
Called when this toolkit is requested to close.
Protected Member Functions inherited from FBaseToolkit
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from FRigVMEditorBase
FRigVMEditorBase ()
virtual ~FRigVMEditorBase ()
virtual void AddNewFunctionVariant (const UEdGraph *InOriginalFunction) override
void AddReferencedObjects (FReferenceCollector &Collector)
bool AreDelegatesAllowed () const
bool AreEventGraphsAllowed () const
bool AreMacrosAllowed () const
virtual void BindCommands ()
void BringToolkitToFront ()
virtual void CacheNameLists ()
Update the name lists for use in name combo boxes.
virtual bool CanAddNewLocalVariable () const override
bool CanAutoCompileGraph () const
bool CanHideItem () const
void ClearDetailObject (bool bChangeUISelectionState=true)
void ClearDetailsViewWrapperObjects ()
void CreateDefaultCommandsImpl ()
virtual void CreateEmptyGraphContent (URigVMController *InController)
bool DetailViewShowsAnyRigUnit () const
bool DetailViewShowsLocalVariable () const
bool DetailViewShowsStruct (UScriptStruct *InStruct) const
void ExtendMenu ()
Extend menu.
void ExtendToolbar ()
Extend toolbar.
virtual void FillToolbar (FToolBarBuilder &ToolbarBuilder, bool bEndSection=true)
Fill the toolbar with content.
void FocusInspectorOnGraphSelection (const TSet< class UObject * > &NewSelection, bool bForceRefresh=false)
virtual void ForceEditorRefresh (ERefreshRigVMEditorReason::Type Reason=ERefreshRigVMEditorReason::UnknownReason) override
void FrameSelection ()
virtual FMenuBuilder GenerateBulkEditMenu ()
TSharedRef< SWidget > GenerateBulkEditMenuContent ()
TSharedRef< SWidget > GenerateEventQueueMenuContent ()
virtual void GenerateEventQueueMenuContent (FMenuBuilder &MenuBuilder)
TSharedRef< SWidget > GenerateExecutionModeMenuContent ()
FText GetBaseToolkitName () const
UBlueprint * GetBlueprintObj () const
virtual FString GetCustomDebugObjectLabel (UObject *ObjectBeingDebugged) const override
virtual void GetDebugObjects (TArray< FRigVMCustomDebugObject > &DebugList) const override
virtual TArray< FName > GetDefaultEventQueue () const
TSubclassOf< UEdGraphSchema > GetDefaultSchemaClass () const
virtual UClass * GetDetailWrapperClass () const
virtual const FName GetEditorModeName () const
TArray< FName > GetEventQueue () const
virtual int32 GetEventQueueComboValue () const
FSlateIcon GetEventQueueIcon () const
virtual FSlateIcon GetEventQueueIcon (const TArray< FName > &InEventQueue) const
virtual FText GetEventQueueLabel () const
int32 GetExecutionModeComboValue () const
FSlateIcon GetExecutionModeIcon () const
FText GetExecutionModeLabel () const
URigVMController * GetFocusedController () const
virtual URigVMGraph * GetFocusedModel () const override
FGraphAppearanceInfo GetGraphAppearance (class UEdGraph *InGraph) const
TSharedPtr< SGraphEditor > GetGraphEditor (UEdGraph *InEdGraph) const
virtual TSharedPtr< SRigVMEditorGraphExplorer > GetGraphExplorerWidget () override
virtual UObject * GetOuterForHost () const
virtual URigVMHost * GetRigVMHost () const override
TArray< TWeakObjectPtr< UObject > > GetSelectedObjects () const
TStatId GetStatId () const
bool & GetSuspendDetailsPanelRefreshFlag ()
TSharedRef< SBorder > GetToolbox ()
Get the toolbox hosting widget.
FName GetToolkitContextFName () const
FName GetToolkitFName () const
FText GetToolkitToolTipText () const
FLinearColor GetWorldCentricTabColorScale () const
FString GetWorldCentricTabPrefix () const
const TArray< TStrongObjectPtr< URigVMDetailsViewWrapperObject > > & GetWrapperObjects () const
void HandleAssetRequestClose (UObject *InObject, EAssetEditorCloseReason InReason)
void HandleAssetRequestedOpen (UObject *InObject)
void HandleBreakpointActionRequested (const ERigVMBreakpointAction BreakpointAction)
void HandleBreakpointAdded ()
FActionMenuContent HandleCreateGraphActionMenu (UEdGraph *InGraph, const FVector2f &InNodePosition, const TArray< UEdGraphPin * > &InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed)
Wraps the normal blueprint editor's action menu creation callback.
void HandleHideItem ()
Handle hiding items in the graph.
virtual void HandleModifiedEvent (ERigVMGraphNotifType InNotifType, URigVMGraph *InGraph, UObject *InSubject) override
virtual void HandleRefreshEditorFromBlueprint (URigVMBlueprint *InBlueprint)
void HandleSetObjectBeingDebugged (UObject *InObject)
void HandleShowCurrentStatement ()
void HandleVariableDroppedFromBlueprint (UObject *InSubject, FProperty *InVariableToDrop, const FVector2D &InDropPosition, const FVector2D &InScreenPosition)
virtual void HandleVMExecutedEvent (URigVMHost *InHost, const FName &InEventName)
void HandleVMExecutionHalted (const int32 InstructionIndex, UObject *InNode, const FName &InEntryName)
virtual bool InEditingMode () const override
void InitToolMenuContextImpl (FToolMenuContext &MenuContext)
bool IsAutoCompileGraphOn () const
bool IsDetailsPanelRefreshSuspended () const
bool IsEditingSingleBlueprint () const
bool IsHaltedAtBreakpoint () const
bool IsInAScriptingMode () const
bool IsNativeParentClassCodeLinkEnabled () const
bool IsSectionVisibleImpl (RigVMNodeSectionID::Type InSectionID) const
bool JumpToHyperlinkImpl (const UObject *ObjectReference, bool bRequestRename=false)
bool NewDocument_IsVisibleForTypeImpl (ECreatedDocumentType GraphType) const
void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged)
void NotifyPreChange (FProperty *PropertyAboutToChange)
bool OnActionMatchesName (FEdGraphSchemaAction *InAction, const FName &InName) const
void OnActiveTabChanged (TSharedPtr< SDockTab > PreviouslyActive, TSharedPtr< SDockTab > NewlyActivated)
virtual void OnAddNewLocalVariable () override
void OnBlueprintChangedImpl (UBlueprint *InBlueprint, bool bIsJustBeingCompiled)
void OnCreateComment ()
void OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList)
virtual FRigVMEditorClosed & OnEditorClosed () override
void OnGraphEditorFocused (const TSharedRef< SGraphEditor > &InGraphEditor)
void OnGraphImported (UEdGraph *InEdGraph)
void OnGraphNodeClicked (URigVMEdGraphNode *InNode)
virtual bool OnlyShowCustomDebugObjects () const override
virtual void OnNewDocumentClicked (ECreatedDocumentType GraphType) override
void OnNodeDoubleClicked (URigVMBlueprint *InBlueprint, URigVMNode *InNode)
void OnNodeTitleCommitted (const FText &NewText, ETextCommit::Type CommitInfo, UEdGraphNode *NodeBeingChanged)
virtual void OnPasteNewLocalVariable (const FBPVariableDescription &VariableDescription) override
void OnPIEStopped (bool bSimulation)
virtual FPreviewHostUpdated & OnPreviewHostUpdated () override
void OnPropertyChanged (UObject *InObject, FPropertyChangedEvent &InEvent)
bool OnRequestBreakLinksDialog (TArray< URigVMLink * > InLinks)
FRigVMController_BulkEditResult OnRequestBulkEditDialog (URigVMBlueprint *InBlueprint, URigVMController *InController, URigVMLibraryNode *InFunction, ERigVMControllerBulkEditType InEditType)
void OnRequestLocalizeFunctionDialog (FRigVMGraphFunctionIdentifier &InFunction, URigVMController *InTargetController, IRigVMGraphFunctionHost *InTargetFunctionHost, bool bForce)
TRigVMTypeIndex OnRequestPinTypeSelectionDialog (const TArray< TRigVMTypeIndex > &InTypes)
void OnSelectedNodesChangedImpl (const TSet< class UObject * > &NewSelection)
FReply OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f &InPosition, UEdGraph *InGraph)
void OnToolkitHostingFinished (const TSharedRef< class IToolkit > &Toolkit)
void OnToolkitHostingStarted (const TSharedRef< class IToolkit > &Toolkit)
virtual void OnWrappedPropertyChangedChainEvent (URigVMDetailsViewWrapperObject *InWrapperObject, const FString &InPropertyPath, FPropertyChangedChainEvent &InPropertyChangedChainEvent)
void PostRedoImpl (bool bSuccess)
virtual void PostTransaction (bool bSuccess, const FTransaction *Transaction, bool bIsRedo)
void PostUndoImpl (bool bSuccess)
void RedoAction ()
Redo Action.
virtual void RefreshDetailView ()
bool ReparentBlueprint_IsVisible () const
void SaveAsset_Execute ()
void SaveAssetAs_Execute ()
virtual bool SelectLocalVariable (const UEdGraph *Graph, const FName &VariableName) override
virtual void SetDetailObjectFilter (TSharedPtr< FDetailsViewObjectFilter > InObjectFilter)
virtual void SetDetailObjects (const TArray< UObject * > &InObjects)
virtual void SetDetailObjects (const TArray< UObject * > &InObjects, bool bChangeUISelectionState)
void SetDetailViewForFocusedGraph ()
void SetDetailViewForGraph (URigVMGraph *InGraph)
void SetDetailViewForLocalVariable ()
void SetEventQueue (TArray< FName > InEventQueue)
virtual void SetEventQueue (TArray< FName > InEventQueue, bool bCompile)
void SetExecutionMode (const ERigVMEditorExecutionModeType InExecutionMode)
virtual void SetGraphExplorerWidget (TSharedPtr< SRigVMEditorGraphExplorer > InWidget) override
void SetHaltedNode (URigVMNode *Node)
void SetHost (URigVMHost *InHost)
void SetMemoryStorageDetails (const TArray< FRigVMMemoryStorageStruct * > &InStructs)
void SetupGraphEditorEvents (UEdGraph *InGraph, SGraphEditor::FGraphEditorEvents &InEvents)
bool ShouldLoadBPLibrariesFromAssetRegistry ()
bool ShouldOpenGraphByDefault () const
void SwapAssetReferences ()
void SwapFunctionAcrossProject ()
void SwapFunctionForAssets (const TArray< FAssetData > &InAssets, bool bSetupUndo)
void SwapFunctionWithinAsset ()
void Tick (float DeltaTime)
void ToggleAutoCompileGraph ()
void ToggleEventQueue ()
void ToggleExecutionMode ()
bool TransactionObjectAffectsBlueprintImpl (UObject *InTransactedObject)
UE_DEPRECATED (5.4, "Please use HandleVMCompiledEvent with ExtendedExecuteContext param.") virtual void HandleVMCompiledEvent(UObject *InCompiledObject
void UnbindEditor ()
void UndoAction ()
Undo Action.
bool UpdateDefaultValueForVariable (FBPVariableDescription &InVariable, bool bUseCDO)
void UpdateGraphCompilerErrors ()
Once the log is collected update the graph.
virtual void UpdateRigVMHost ()
Push a newly compiled/opened host to the editor.
virtual void UpdateRigVMHost_PreClearOldHost (URigVMHost *InPreviousHost)
void UpdateStaleWatchedPins ()
Update stale watch pins.
Protected Member Functions inherited from IRigVMEditor
virtual void JumpToNode (const class UEdGraphNode *Node, bool bRequestRename=false)=0
virtual void JumpToPin (const class UEdGraphPin *Pin)=0
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Protected Attributes
bool bBlueprintModifiedOnOpen
Did we update the blueprint when it opened.
bool bIsActionMenuContextSensitive
Whether the graph action menu should be sensitive to the pins dragged off of.
bool bWasOpenedInDefaultsMode
True if the editor was opened in defaults mode.
TSharedPtr< class SWidget > CompilerResults
Compiler results log, with the log listing that it reflects.
TSharedPtr< class IMessageLogListing > CompilerResultsListing
FName CurrentUISelection
The current UI selection state of this editor.
TSharedPtr< class SRigVMDetailsInspector > DefaultEditor
defaults inspector widget
TSharedPtr< FDocumentTracker > DocumentManager
TSharedPtr< class SRigVMFindReferences > FindResults
Find results log as well as the search filter.
TWeakPtr< class SGraphEditor > FocusedGraphEdPtr
Currently focused graph editor.
TSharedPtr< FUICommandList > GraphEditorCommands
Command list for the graph editor.
TWeakPtr< FDocumentTabFactory > GraphEditorTabFactoryPtr
Factory that spawns graph editors; used to look up all tabs spawned by it.
UEdGraph * HasOpenActionMenu
When set, flags which graph has a action menu currently open (if null, no graphs do).
TSharedPtr< class SRigVMDetailsInspector > Inspector
Node inspector widget.
float InstructionsFadeCountdown
Used to nicely fade instruction text, when the context menu is opened.
Protected Attributes inherited from FWorkflowCentricApplication
TSharedPtr< FApplicationMode > CurrentAppModePtr
Protected Attributes inherited from FAssetEditorToolkit
TSharedPtr< FWorkspaceItem > AssetEditorTabsCategory
The base category that tabs are registered to, allows for child classes to register to the same point.
bool bCheckDirtyOnAssetSave
Whether only dirty assets should be prompted about on save - otherwise all edited assets will be prompted to the user for save/check-out.
TSharedPtr< FEditorModeTools > EditorModeManager
The editor mode manager.
TArray< TSharedPtr< FLayoutExtender > > LayoutExtenders
Array of layout extenders.
FString LayoutIni = GEditorLayoutIni
What ini file should be used to persist and restore the user's layout.
TWeakPtr< IToolkitHost > PreviousWorldCentricToolkitHost
For standalone asset editing tool-kits that were switched from world-centric mode on the fly, this stores the toolkit host (level editor) that hosted this toolkit last.
TSharedPtr< FTabManager > TabManager
Controls our internal layout.
Protected Attributes inherited from FBaseToolkit
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Protected Attributes inherited from FRigVMEditorBase
URigVMController * ActiveController
bool bAllowBulkEdits
bool bAnyErrorsLeft
bool bDetailsPanelRequiresClear
bool bIsCompilingThroughUI
Are we currently compiling through the user interface.
bool bIsSettingObjectBeingDebugged
bool bRequestedReopen = false
bool bRigVMEditorInitialized
bool bSuspendDetailsPanelRefresh
ERigVMEditorExecutionModeType ExecutionMode
TSharedPtr< SRigVMEditorGraphExplorer > GraphExplorerWidget
URigVMNode * HaltedAtNode
URigVM * InVM
TMap< FString, FString > KnownInstructionLimitWarnings
FString LastDebuggedHost
TArray< FName > LastEventQueue
TSharedPtr< FExtender > MenuExtender
The extender to pass to the level editor to extend it's window menu.
FOnRefreshEvent OnRefreshEvent
FPreviewHostUpdated PreviewHostUpdated
Our currently running rig vm instance.
FDelegateHandle PropertyChangedHandle
FRigVMEditorClosed RigVMEditorClosedDelegate
FRigVMLog RigVMLog
The log to use for errors resulting from the init phase of the units.
TSharedPtr< FExtender > ToolbarExtender
Toolbar extender.
TSharedPtr< SBorder > Toolbox
Toolbox hosting widget.
TArray< TStrongObjectPtr< URigVMDetailsViewWrapperObject > > WrapperObjects
Additional Inherited Members
Public Types inherited from IRigVMEditor
enum ECreatedDocumentType {
CGT_NewVariable , CGT_NewFunctionGraph , CGT_NewMacroGraph , CGT_NewAnimationLayer ,
CGT_NewEventGraph , CGT_NewLocalVariable
}
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Types inherited from FRigVMEditorBase
enum ERigVMEditorExecutionModeType { ERigVMEditorExecutionModeType_Release , ERigVMEditorExecutionModeType_Debug }
Static Protected Member Functions inherited from FAssetEditorToolkit
static UNREALED_API void SwitchToStandaloneEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to Standalone Editor" is clicked for the asset editor.
static UNREALED_API void SwitchToWorldCentricEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to World-Centric Editor" is clicked for the asset editor.
Static Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Static Protected Member Functions inherited from FRigVMEditorBase
static FSlateIcon GetExecutionModeIcon (const ERigVMEditorExecutionModeType InExecutionMode)
static bool IsPIERunning ()
Returns true if PIE is currently running.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Definition at line 18 of file RigVMNewEditor.h.
Constructor & Destructor Documentation
FRigVMNewEditor()
FRigVMNewEditor::FRigVMNewEditor ()
Referenced by GetStatId().
Member Function Documentation
AddApplicationMode()
virtual void FRigVMNewEditor::AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode) inline override protected virtual
Reimplemented from FWorkflowCentricApplication.
Definition at line 37 of file RigVMNewEditor.h.
References FWorkflowCentricApplication::AddApplicationMode().
AddAutoCompileWidget()
virtual void FRigVMNewEditor::AddAutoCompileWidget (FToolBarBuilder & ToolbarBuilder) inline override virtual
Implements IRigVMEditor.
Definition at line 127 of file RigVMNewEditor.h.
AddCompileWidget()
virtual void FRigVMNewEditor::AddCompileWidget (FToolBarBuilder & ToolbarBuilder) override virtual
Implements IRigVMEditor.
AddMenuExtender()
virtual void FRigVMNewEditor::AddMenuExtender (TSharedPtr< FExtender > Extender) inline override protected virtual
Implements IRigVMEditor.
Definition at line 88 of file RigVMNewEditor.h.
References FAssetEditorToolkit::AddMenuExtender().
AddReferencedObjects()
virtual void FRigVMNewEditor::AddReferencedObjects (FReferenceCollector & Collector) inline override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Definition at line 142 of file RigVMNewEditor.h.
References FRigVMEditorBase::AddReferencedObjects().
AddReferencedObjectsImpl()
virtual void FRigVMNewEditor::AddReferencedObjectsImpl (FReferenceCollector & Collector) override protected virtual
Implements IRigVMEditor.
AddSelectedDebugObjectWidget()
virtual void FRigVMNewEditor::AddSelectedDebugObjectWidget (FToolBarBuilder & ToolbarBuilder) override virtual
Implements IRigVMEditor.
AddSettingsAndDefaultWidget()
virtual void FRigVMNewEditor::AddSettingsAndDefaultWidget (FToolBarBuilder & ToolbarBuilder) override virtual
Implements IRigVMEditor.
AddToolbarExtender()
virtual void FRigVMNewEditor::AddToolbarExtender (TSharedPtr< FExtender > Extender) inline override protected virtual
Implements IRigVMEditor.
Definition at line 86 of file RigVMNewEditor.h.
References FAssetEditorToolkit::AddToolbarExtender().
AnalyticsTrackNodeEvent()
virtual void FRigVMNewEditor::AnalyticsTrackNodeEvent (UBlueprint * Blueprint, UEdGraphNode * GraphNode, bool bNodeDelete) const override protected virtual
Implements IRigVMEditor.
BringToolkitToFrontImpl()
virtual void FRigVMNewEditor::BringToolkitToFrontImpl () inline override protected virtual
Implements IRigVMEditor.
Definition at line 61 of file RigVMNewEditor.h.
References FBaseToolkit::BringToolkitToFront().
CanSelectAllNodes()
bool FRigVMNewEditor::CanSelectAllNodes () const
ClearSelectionStateFor()
virtual void FRigVMNewEditor::ClearSelectionStateFor (FName SelectionOwner) virtual
CloseDocumentTab()
virtual void FRigVMNewEditor::CloseDocumentTab (const UObject * DocumentID) override protected virtual
Implements IRigVMEditor.
CommonInitialization()
virtual void FRigVMNewEditor::CommonInitialization (const TArray< UBlueprint * > & InitBlueprints, bool bShouldOpenInDefaultsMode) override protected virtual
Implements IRigVMEditor.
Compile()
virtual void FRigVMNewEditor::Compile () inline virtual
Definition at line 128 of file RigVMNewEditor.h.
References FRigVMEditorBase::Compile().
CompileImpl()
virtual void FRigVMNewEditor::CompileImpl () override protected virtual
Implements IRigVMEditor.
CreateDefaultCommands()
virtual void FRigVMNewEditor::CreateDefaultCommands () override protected virtual
Implements IRigVMEditor.
CreateDefaultTabContents()
void FRigVMNewEditor::CreateDefaultTabContents (const TArray< UBlueprint * > InBlueprints)
CreateEditorMode()
virtual TSharedPtr< FApplicationMode > FRigVMNewEditor::CreateEditorMode () override protected virtual
Implements IRigVMEditor.
CreateEditorToolbar()
virtual void FRigVMNewEditor::CreateEditorToolbar () inline override protected virtual
Implements IRigVMEditor.
Definition at line 32 of file RigVMNewEditor.h.
CreateGraphEditorWidget()
virtual TSharedRef< SGraphEditor > FRigVMNewEditor::CreateGraphEditorWidget (TSharedRef< FTabInfo > InTabInfo, UEdGraph * InGraph) override protected virtual
Implements IRigVMEditor.
DumpMessagesToCompilerLog()
void FRigVMNewEditor::DumpMessagesToCompilerLog (const TArray< TSharedRef< class FTokenizedMessage > > & Messages, bool bForceMessageDisplay) protected
Dumps messages to the compiler log, with an option to force it to display/come to front.
EditClassDefaults_Clicked()
virtual void FRigVMNewEditor::EditClassDefaults_Clicked () override protected virtual
Implements IRigVMEditor.
EditGlobalOptions_Clicked()
virtual void FRigVMNewEditor::EditGlobalOptions_Clicked () override protected virtual
Implements IRigVMEditor.
FindNodeWithError() [1/2]
UEdGraphNode * FRigVMNewEditor::FindNodeWithError (FCompilerResultsLog const & ErrorLog, EMessageSeverity::Type Severity)
FindNodeWithError() [2/2]
UEdGraphNode * FRigVMNewEditor::FindNodeWithError (UBlueprint * Blueprint, EMessageSeverity::Type Severity)
FindOpenTabsContainingDocument()
virtual bool FRigVMNewEditor::FindOpenTabsContainingDocument (const UObject * DocumentID, TArray< TSharedPtr< SDockTab > > & Results) override protected virtual
Implements IRigVMEditor.
GenerateCompileOptionsMenu()
TSharedRef< SWidget > FRigVMNewEditor::GenerateCompileOptionsMenu ()
GetCompilerResults()
TSharedRef< SWidget > FRigVMNewEditor::GetCompilerResults () const inline
Definition at line 51 of file RigVMNewEditor.h.
References CompilerResults.
GetCompilerResultsListing()
virtual TSharedPtr< IMessageLogListing > FRigVMNewEditor::GetCompilerResultsListing () inline override protected virtual
Implements IRigVMEditor.
Definition at line 55 of file RigVMNewEditor.h.
References CompilerResultsListing.
GetCompileStatusImage()
FSlateIcon FRigVMNewEditor::GetCompileStatusImage () const
GetCompileStatusTooltip()
FText FRigVMNewEditor::GetCompileStatusTooltip () const
GetCurrentlySelectedPin()
virtual UEdGraphPin * FRigVMNewEditor::GetCurrentlySelectedPin () const override protected virtual
Implements IRigVMEditor.
GetDocumentManager()
virtual TSharedPtr< FDocumentTracker > FRigVMNewEditor::GetDocumentManager () const inline override protected virtual
Implements IRigVMEditor.
Definition at line 36 of file RigVMNewEditor.h.
References DocumentManager.
GetEditingBlueprints()
virtual const TArray< UObject * > & FRigVMNewEditor::GetEditingBlueprints () const inline override protected virtual
Implements IRigVMEditor.
Definition at line 58 of file RigVMNewEditor.h.
References FAssetEditorToolkit::GetEditingObjects().
GetEditorAppName()
virtual const FName FRigVMNewEditor::GetEditorAppName () const override protected virtual
Implements IRigVMEditor.
GetFindResults()
TSharedRef< SRigVMFindReferences > FRigVMNewEditor::GetFindResults () const inline
Definition at line 52 of file RigVMNewEditor.h.
References FindResults.
GetFocusedGraph()
virtual UEdGraph * FRigVMNewEditor::GetFocusedGraph () const override protected virtual
Implements IRigVMEditor.
GetFocusedGraphEditor()
virtual TWeakPtr< SGraphEditor > FRigVMNewEditor::GetFocusedGraphEditor () inline override protected virtual
Implements IRigVMEditor.
Definition at line 64 of file RigVMNewEditor.h.
References FocusedGraphEdPtr.
GetGlyphForGraph()
const FSlateBrush * FRigVMNewEditor::GetGlyphForGraph (const UEdGraph * Graph, bool bInLargeIcon) static
GetGraphAppearanceImpl()
virtual FGraphAppearanceInfo FRigVMNewEditor::GetGraphAppearanceImpl (UEdGraph * InGraph) const override protected virtual
Implements IRigVMEditor.
GetGraphEditorTabFactory()
virtual TWeakPtr< FDocumentTabFactory > FRigVMNewEditor::GetGraphEditorTabFactory () const inline override protected virtual
Implements IRigVMEditor.
Definition at line 65 of file RigVMNewEditor.h.
References GraphEditorTabFactoryPtr.
GetGraphExplorerWidgetID()
virtual FName FRigVMNewEditor::GetGraphExplorerWidgetID () inline override protected virtual
Implements IRigVMEditor.
Definition at line 107 of file RigVMNewEditor.h.
References FRigVMEditorGraphExplorerTabSummoner::TabID().
GetHostingApp() [1/2]
virtual const TSharedPtr< FAssetEditorToolkit > FRigVMNewEditor::GetHostingApp () const inline override virtual
Implements IRigVMEditor.
Definition at line 28 of file RigVMNewEditor.h.
References TSharedFromThis< FAssetEditorToolkit >::AsShared(), and ConstCastSharedRef().
GetHostingApp() [2/2]
virtual TSharedPtr< FAssetEditorToolkit > FRigVMNewEditor::GetHostingApp () inline override virtual
Implements IRigVMEditor.
Definition at line 27 of file RigVMNewEditor.h.
References TSharedFromThis< FAssetEditorToolkit >::AsShared().
GetInstructionTextOpacity()
float FRigVMNewEditor::GetInstructionTextOpacity (UEdGraph * InGraph) const
GetIsContextSensitive()
virtual bool FRigVMNewEditor::GetIsContextSensitive () inline override virtual
Implements IRigVMEditor.
Definition at line 120 of file RigVMNewEditor.h.
References bIsActionMenuContextSensitive.
GetLastPinTypeUsed()
virtual FEdGraphPinType FRigVMNewEditor::GetLastPinTypeUsed () override protected virtual
Implements IRigVMEditor.
GetNotifyHook()
virtual FNotifyHook * FRigVMNewEditor::GetNotifyHook () inline override virtual
Implements IRigVMEditor.
Definition at line 177 of file RigVMNewEditor.h.
GetObjectsCurrentlyBeingEdited()
virtual const TArray< UObject * > * FRigVMNewEditor::GetObjectsCurrentlyBeingEdited () const inline override virtual
Reimplemented from FAssetEditorToolkit.
Definition at line 123 of file RigVMNewEditor.h.
References FAssetEditorToolkit::GetObjectsCurrentlyBeingEdited().
GetPinTypeSelectorFilters()
virtual void FRigVMNewEditor::GetPinTypeSelectorFilters (TArray< TSharedPtr< IPinTypeSelectorFilter > > & OutFilters) const override protected virtual
Implements IRigVMEditor.
GetPreviewScene()
virtual FPreviewScene * FRigVMNewEditor::GetPreviewScene () inline override virtual
Implements IRigVMEditor.
Definition at line 134 of file RigVMNewEditor.h.
GetReferencerName()
virtual FString FRigVMNewEditor::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 143 of file RigVMNewEditor.h.
References TEXT.
GetRigVMInspector()
virtual TSharedPtr< SRigVMDetailsInspector > FRigVMNewEditor::GetRigVMInspector () const inline override virtual
Implements IRigVMEditor.
Definition at line 48 of file RigVMNewEditor.h.
References Inspector.
GetSelectedNodes()
virtual FGraphPanelSelectionSet FRigVMNewEditor::GetSelectedNodes () const override protected virtual
Implements IRigVMEditor.
GetSelectedVariableName()
virtual FName FRigVMNewEditor::GetSelectedVariableName () override protected virtual
Implements IRigVMEditor.
GetStatId()
virtual TStatId FRigVMNewEditor::GetStatId () const inline override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
Definition at line 144 of file RigVMNewEditor.h.
References FRigVMNewEditor(), and RETURN_QUICK_DECLARE_CYCLE_STAT.
GetTabManager()
virtual TSharedPtr< FTabManager > FRigVMNewEditor::GetTabManager () inline override protected virtual
Implements IRigVMEditor.
Definition at line 46 of file RigVMNewEditor.h.
References FAssetEditorToolkit::GetTabManager().
GetToolkitCommands()
virtual TSharedRef< FUICommandList > FRigVMNewEditor::GetToolkitCommands () inline override protected virtual
Implements IRigVMEditor.
Definition at line 63 of file RigVMNewEditor.h.
References FBaseToolkit::ToolkitCommands.
GetToolkitEditorModeManager()
virtual FEditorModeTools & FRigVMNewEditor::GetToolkitEditorModeManager () const inline override protected virtual
Implements IRigVMEditor.
Definition at line 40 of file RigVMNewEditor.h.
References FAssetEditorToolkit::GetEditorModeManager().
GetToolkitHost()
virtual const TSharedRef< IToolkitHost > FRigVMNewEditor::GetToolkitHost () const inline override protected virtual
Reimplemented from FBaseToolkit.
Definition at line 59 of file RigVMNewEditor.h.
References FBaseToolkit::GetToolkitHost().
GetWorldCentricTabColorScale()
virtual FLinearColor FRigVMNewEditor::GetWorldCentricTabColorScale () const inline override virtual
Definition at line 141 of file RigVMNewEditor.h.
References FRigVMEditorBase::GetWorldCentricTabColorScale().
HandleSetObjectBeingDebugged()
virtual void FRigVMNewEditor::HandleSetObjectBeingDebugged (UObject * InObject) inline virtual
Definition at line 132 of file RigVMNewEditor.h.
References FRigVMEditorBase::HandleSetObjectBeingDebugged().
InitAssetEditor()
virtual void FRigVMNewEditor::InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > & StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > & ObjectsToEdit, const bool bInIsToolbarFocusable, const bool bInUseSmallToolbarIcons, const TOptional< EAssetOpenMethod > & InOpenMethod) override protected virtual
Implements IRigVMEditor.
InitToolMenuContext()
virtual void FRigVMNewEditor::InitToolMenuContext (FToolMenuContext & MenuContext) override protected virtual
Reimplemented from FAssetEditorToolkit.
IsDetailsPanelEditingClassDefaults()
bool FRigVMNewEditor::IsDetailsPanelEditingClassDefaults () const protected
IsDetailsPanelEditingGlobalOptions()
bool FRigVMNewEditor::IsDetailsPanelEditingGlobalOptions () const protected
IsEditableImpl()
virtual bool FRigVMNewEditor::IsEditableImpl (UEdGraph * InGraph) const override protected virtual
Implements IRigVMEditor.
IsGraphInCurrentBlueprint()
virtual bool FRigVMNewEditor::IsGraphInCurrentBlueprint (const UEdGraph * InGraph) const override protected virtual
Implements IRigVMEditor.
IsHosted()
virtual bool FRigVMNewEditor::IsHosted () const inline override protected virtual
Reimplemented from FBaseToolkit.
Definition at line 60 of file RigVMNewEditor.h.
References FBaseToolkit::IsHosted().
IsJumpToErrorNodeOptionSet()
bool FRigVMNewEditor::IsJumpToErrorNodeOptionSet ()
IsNodeTitleVisible()
virtual bool FRigVMNewEditor::IsNodeTitleVisible (const UEdGraphNode * Node, bool bRequestRename) override protected virtual
Implements IRigVMEditor.
IsSaveOnCompileEnabled()
bool FRigVMNewEditor::IsSaveOnCompileEnabled () const
IsSaveOnCompileOptionSet()
bool FRigVMNewEditor::IsSaveOnCompileOptionSet (TWeakPtr< FRigVMNewEditor > Editor, ESaveOnCompile Option)
References Editor.
IsSectionVisible()
virtual bool FRigVMNewEditor::IsSectionVisible (RigVMNodeSectionID::Type InSectionID) const protected virtual
JumpToHyperlink()
virtual void FRigVMNewEditor::JumpToHyperlink (const UObject * ObjectReference, bool bRequestRename) override virtual
Implements IRigVMEditor.
References ObjectReference.
JumpToNode()
virtual void FRigVMNewEditor::JumpToNode (const UEdGraphNode * Node, bool bRequestRename) override protected virtual
JumpToPin()
virtual void FRigVMNewEditor::JumpToPin (const UEdGraphPin * Pin) override protected virtual
LogSimpleMessage()
virtual void FRigVMNewEditor::LogSimpleMessage (const FText & MessageText) override protected virtual
Implements IRigVMEditor.
MakeSaveOnCompileSubMenu()
void FRigVMNewEditor::MakeSaveOnCompileSubMenu (FMenuBuilder & InMenu)
NewDocument_IsVisibleForType()
virtual bool FRigVMNewEditor::NewDocument_IsVisibleForType (ECreatedDocumentType GraphType) const protected virtual
NotifyPostChangeImpl()
virtual void FRigVMNewEditor::NotifyPostChangeImpl (const FPropertyChangedEvent & PropertyChangedEvent, FProperty * PropertyThatChanged) override protected virtual
Implements IRigVMEditor.
NotifyPreChangeImpl()
virtual void FRigVMNewEditor::NotifyPreChangeImpl (FProperty * PropertyAboutToChange) override protected virtual
Implements IRigVMEditor.
OnAddNewVariable()
virtual void FRigVMNewEditor::OnAddNewVariable () override protected virtual
Implements IRigVMEditor.
OnAlignBottom()
void FRigVMNewEditor::OnAlignBottom ()
OnAlignCenter()
void FRigVMNewEditor::OnAlignCenter ()
OnAlignLeft()
void FRigVMNewEditor::OnAlignLeft ()
OnAlignMiddle()
void FRigVMNewEditor::OnAlignMiddle ()
OnAlignRight()
void FRigVMNewEditor::OnAlignRight ()
OnAlignTop()
void FRigVMNewEditor::OnAlignTop ()
OnBlueprintChanged()
void FRigVMNewEditor::OnBlueprintChanged (UBlueprint * InBlueprint) protected
OnBlueprintChangedInnerImpl()
virtual void FRigVMNewEditor::OnBlueprintChangedInnerImpl (UBlueprint * InBlueprint, bool bIsJustBeingCompiled) override protected virtual
Implements IRigVMEditor.
OnClose()
virtual void FRigVMNewEditor::OnClose () override virtual
Called when this toolkit is being closed.
Reimplemented from FWorkflowCentricApplication.
OnCreateGraphActionMenu()
virtual FActionMenuContent FRigVMNewEditor::OnCreateGraphActionMenu (UEdGraph * InGraph, const FVector2f & InNodePosition, const TArray< UEdGraphPin * > & InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed) override protected virtual
Implements IRigVMEditor.
References SGraphEditor::FActionMenuClosed.
OnCreateGraphEditorCommands()
virtual void FRigVMNewEditor::OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList) inline virtual
Definition at line 129 of file RigVMNewEditor.h.
References FRigVMEditorBase::OnCreateGraphEditorCommands().
OnDistributeNodesH()
void FRigVMNewEditor::OnDistributeNodesH ()
OnDistributeNodesV()
void FRigVMNewEditor::OnDistributeNodesV ()
OnFinishedChangingProperties()
virtual void FRigVMNewEditor::OnFinishedChangingProperties (const FPropertyChangedEvent & PropertyChangedEvent) inline virtual
delegate for changing property
Reimplemented from FRigVMEditorBase.
Definition at line 131 of file RigVMNewEditor.h.
References FRigVMEditorBase::OnFinishedChangingProperties().
OnGraphEditorBackgrounded()
virtual void FRigVMNewEditor::OnGraphEditorBackgrounded (const TSharedRef< SGraphEditor > & InGraphEditor) virtual
OnGraphEditorFocused()
virtual void FRigVMNewEditor::OnGraphEditorFocused (const TSharedRef< SGraphEditor > & InGraphEditor) virtual
OnLogTokenClicked()
void FRigVMNewEditor::OnLogTokenClicked (const TSharedRef< IMessageToken > & MessageToken) protected
OnSelectedNodesChanged()
void FRigVMNewEditor::OnSelectedNodesChanged (const FGraphPanelSelectionSet & NewSelection)
OnSpawnGraphNodeByShortcut()
virtual FReply FRigVMNewEditor::OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f & InPosition, UEdGraph * InGraph) inline virtual
Definition at line 133 of file RigVMNewEditor.h.
References FRigVMEditorBase::OnSpawnGraphNodeByShortcut().
OnStraightenConnections()
void FRigVMNewEditor::OnStraightenConnections ()
OpenDocument()
virtual TSharedPtr< SDockTab > FRigVMNewEditor::OpenDocument (const UObject * DocumentID, FDocumentTracker::EOpenDocumentCause Cause) override protected virtual
Implements IRigVMEditor.
OpenGraphAndBringToFront()
virtual TSharedPtr< SGraphEditor > FRigVMNewEditor::OpenGraphAndBringToFront (UEdGraph * Graph, bool bSetFocus = true) override protected virtual
Implements IRigVMEditor.
PostLayoutBlueprintEditorInitialization()
virtual void FRigVMNewEditor::PostLayoutBlueprintEditorInitialization () override protected virtual
Implements IRigVMEditor.
PostRedo()
virtual void FRigVMNewEditor::PostRedo (bool bSuccess) override protected virtual
Implements IRigVMEditor.
PostUndo()
virtual void FRigVMNewEditor::PostUndo (bool bSuccess) override protected virtual
Implements IRigVMEditor.
RefreshEditorsImpl()
virtual void FRigVMNewEditor::RefreshEditorsImpl (ERefreshRigVMEditorReason::Type Reason) override protected virtual
Implements IRigVMEditor.
RefreshInspector()
virtual void FRigVMNewEditor::RefreshInspector () override protected virtual
Implements IRigVMEditor.
RefreshStandAloneDefaultsEditor()
virtual void FRigVMNewEditor::RefreshStandAloneDefaultsEditor () override protected virtual
Implements IRigVMEditor.
RegenerateMenusAndToolbars()
virtual void FRigVMNewEditor::RegenerateMenusAndToolbars () inline override protected virtual
Implements IRigVMEditor.
Definition at line 38 of file RigVMNewEditor.h.
References FAssetEditorToolkit::RegenerateMenusAndToolbars().
RegisterTabSpawners()
virtual void FRigVMNewEditor::RegisterTabSpawners (const TSharedRef< class FTabManager > & TabManager) override virtual
IToolkit interface.
Reimplemented from FWorkflowCentricApplication.
RegisterToolbarTab()
virtual void FRigVMNewEditor::RegisterToolbarTab (const TSharedRef< FTabManager > & InTabManager) inline override virtual
Implements IRigVMEditor.
Definition at line 122 of file RigVMNewEditor.h.
References FAssetEditorToolkit::RegisterTabSpawners().
RemoveMenuExtender()
virtual void FRigVMNewEditor::RemoveMenuExtender (TSharedPtr< FExtender > Extender) inline override protected virtual
Implements IRigVMEditor.
Definition at line 89 of file RigVMNewEditor.h.
References FAssetEditorToolkit::RemoveMenuExtender().
RemoveToolbarExtender()
virtual void FRigVMNewEditor::RemoveToolbarExtender (TSharedPtr< FExtender > Extender) inline override protected virtual
Implements IRigVMEditor.
Definition at line 87 of file RigVMNewEditor.h.
References FAssetEditorToolkit::RemoveToolbarExtender().
RenameNewlyAddedAction()
virtual void FRigVMNewEditor::RenameNewlyAddedAction (FName InActionName) override protected virtual
Implements IRigVMEditor.
RestoreEditedObjectState()
virtual void FRigVMNewEditor::RestoreEditedObjectState () override virtual
Implements IRigVMEditor.
SaveAsset_Execute_Impl()
virtual void FRigVMNewEditor::SaveAsset_Execute_Impl () inline override protected virtual
Implements IRigVMEditor.
Definition at line 79 of file RigVMNewEditor.h.
References FAssetEditorToolkit::SaveAsset_Execute().
SaveAssetAs_Execute_Impl()
virtual void FRigVMNewEditor::SaveAssetAs_Execute_Impl () inline override protected virtual
Implements IRigVMEditor.
Definition at line 80 of file RigVMNewEditor.h.
References FAssetEditorToolkit::SaveAssetAs_Execute().
SaveEditedObjectState()
void FRigVMNewEditor::SaveEditedObjectState () protected
SelectAllNodes()
void FRigVMNewEditor::SelectAllNodes ()
SelectionState_ClassDefaults()
const FName FRigVMNewEditor::SelectionState_ClassDefaults () static
SelectionState_ClassSettings()
const FName FRigVMNewEditor::SelectionState_ClassSettings () static
SelectionState_Graph()
const FName FRigVMNewEditor::SelectionState_Graph () static
SelectionState_GraphExplorer()
const FName FRigVMNewEditor::SelectionState_GraphExplorer () static
SetCurrentMode()
virtual void FRigVMNewEditor::SetCurrentMode (FName NewMode) override protected virtual
Reimplemented from FWorkflowCentricApplication.
SetInspector()
virtual void FRigVMNewEditor::SetInspector (TSharedPtr< SRigVMDetailsInspector > InWidget) inline virtual
Definition at line 49 of file RigVMNewEditor.h.
References Inspector.
SetIsContextSensitive()
virtual void FRigVMNewEditor::SetIsContextSensitive (const bool bIsContextSensitive) inline override virtual
Implements IRigVMEditor.
Definition at line 121 of file RigVMNewEditor.h.
References bIsActionMenuContextSensitive.
SetSaveOnCompileSetting()
void FRigVMNewEditor::SetSaveOnCompileSetting (ESaveOnCompile NewSetting)
SetUISelectionState()
virtual void FRigVMNewEditor::SetUISelectionState (FName SelectionOwner) override protected virtual
Implements IRigVMEditor.
SetupGraphEditorEventsImpl()
virtual void FRigVMNewEditor::SetupGraphEditorEventsImpl (UEdGraph * InGraph, SGraphEditor::FGraphEditorEvents & InEvents) override protected virtual
Implements IRigVMEditor.
SetupViewForBlueprintEditingMode()
virtual void FRigVMNewEditor::SetupViewForBlueprintEditingMode () override virtual
Implements IRigVMEditor.
SharedRef() [1/2]
virtual TSharedRef< const IRigVMEditor > FRigVMNewEditor::SharedRef () const inline override virtual
Implements IRigVMEditor.
Definition at line 25 of file RigVMNewEditor.h.
References TSharedFromThis< FAssetEditorToolkit >::SharedThis(), and StaticCastSharedRef().
SharedRef() [2/2]
virtual TSharedRef< IRigVMEditor > FRigVMNewEditor::SharedRef () inline override virtual
Implements IRigVMEditor.
Definition at line 24 of file RigVMNewEditor.h.
References TSharedFromThis< FAssetEditorToolkit >::SharedThis(), and StaticCastSharedRef().
ShouldOpenGraphByDefault()
virtual bool FRigVMNewEditor::ShouldOpenGraphByDefault () const inline virtual
Definition at line 130 of file RigVMNewEditor.h.
References FRigVMEditorBase::ShouldOpenGraphByDefault().
StartEditingDefaults()
virtual void FRigVMNewEditor::StartEditingDefaults (bool bAutoFocus = true, bool bForceRefresh = false) virtual
SummonSearchUI()
virtual void FRigVMNewEditor::SummonSearchUI (bool bSetFindWithinBlueprint, FString NewSearchTerms, bool bSelectFirstResult) override virtual
Implements IRigVMEditor.
Tick()
virtual void FRigVMNewEditor::Tick (float DeltaTime) override protected virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
References DeltaTime.
ToggleJumpToErrorNodeSetting()
void FRigVMNewEditor::ToggleJumpToErrorNodeSetting ()
TransactionObjectAffectsBlueprint()
virtual bool FRigVMNewEditor::TransactionObjectAffectsBlueprint (UObject * InTransactedObject) override protected virtual
Implements IRigVMEditor.
TryInvokingDetailsTab()
virtual void FRigVMNewEditor::TryInvokingDetailsTab (bool bFlash = true) override protected virtual
Implements IRigVMEditor.
ZoomToSelection_Clicked()
virtual void FRigVMNewEditor::ZoomToSelection_Clicked () override protected virtual
Implements IRigVMEditor.
Field Documentation
bBlueprintModifiedOnOpen
bool FRigVMNewEditor::bBlueprintModifiedOnOpen protected
Did we update the blueprint when it opened.
Definition at line 232 of file RigVMNewEditor.h.
bIsActionMenuContextSensitive
bool FRigVMNewEditor::bIsActionMenuContextSensitive protected
Whether the graph action menu should be sensitive to the pins dragged off of.
Definition at line 235 of file RigVMNewEditor.h.
Referenced by GetIsContextSensitive(), and SetIsContextSensitive().
bWasOpenedInDefaultsMode
bool FRigVMNewEditor::bWasOpenedInDefaultsMode protected
True if the editor was opened in defaults mode.
Definition at line 229 of file RigVMNewEditor.h.
CompilerResults
TSharedPtr<class SWidget> FRigVMNewEditor::CompilerResults protected
Compiler results log, with the log listing that it reflects.
Definition at line 213 of file RigVMNewEditor.h.
Referenced by GetCompilerResults().
CompilerResultsListing
TSharedPtr<class IMessageLogListing> FRigVMNewEditor::CompilerResultsListing protected
Definition at line 214 of file RigVMNewEditor.h.
Referenced by GetCompilerResultsListing().
CurrentUISelection
FName FRigVMNewEditor::CurrentUISelection protected
The current UI selection state of this editor.
Definition at line 207 of file RigVMNewEditor.h.
DefaultEditor
TSharedPtr<class SRigVMDetailsInspector> FRigVMNewEditor::DefaultEditor protected
defaults inspector widget
Definition at line 226 of file RigVMNewEditor.h.
DocumentManager
TSharedPtr<FDocumentTracker> FRigVMNewEditor::DocumentManager protected
Definition at line 195 of file RigVMNewEditor.h.
Referenced by GetDocumentManager().
FindResults
TSharedPtr<class SRigVMFindReferences> FRigVMNewEditor::FindResults protected
Find results log as well as the search filter.
Definition at line 217 of file RigVMNewEditor.h.
Referenced by GetFindResults().
FocusedGraphEdPtr
TWeakPtr<class SGraphEditor> FRigVMNewEditor::FocusedGraphEdPtr protected
Currently focused graph editor.
Definition at line 201 of file RigVMNewEditor.h.
Referenced by GetFocusedGraphEditor().
GraphEditorCommands
TSharedPtr<FUICommandList> FRigVMNewEditor::GraphEditorCommands protected
Command list for the graph editor.
Definition at line 210 of file RigVMNewEditor.h.
GraphEditorTabFactoryPtr
TWeakPtr<FDocumentTabFactory> FRigVMNewEditor::GraphEditorTabFactoryPtr protected
Factory that spawns graph editors; used to look up all tabs spawned by it.
Definition at line 204 of file RigVMNewEditor.h.
Referenced by GetGraphEditorTabFactory().
HasOpenActionMenu
UEdGraph* FRigVMNewEditor::HasOpenActionMenu protected
When set, flags which graph has a action menu currently open (if null, no graphs do).
Definition at line 220 of file RigVMNewEditor.h.
Inspector
TSharedPtr<class SRigVMDetailsInspector> FRigVMNewEditor::Inspector protected
Node inspector widget.
Definition at line 198 of file RigVMNewEditor.h.
Referenced by GetRigVMInspector(), and SetInspector().
InstructionsFadeCountdown
float FRigVMNewEditor::InstructionsFadeCountdown protected
Used to nicely fade instruction text, when the context menu is opened.
Definition at line 223 of file RigVMNewEditor.h.
The documentation for this class was generated from the following file:
RigVMNewEditor.h