Unreal Engine 5.6 C++ API: FGainTable Class Reference
FGainTable Class Reference
#include "GainTable.h"
Public Member Functions
HARMONIXDSP_API FGainTable ()
HARMONIXDSP_API FORCEINLINE float GetDirectChannelAzimuthInCurrentLayout (ESpeakerChannelAssignment ChannelAssignment) const
const FChannelGains & GetGains (float PolarAngle) const
HARMONIXDSP_API FORCEINLINE void GetGainsForDirectAssignment (ESpeakerChannelAssignment ChannelAssignment, FChannelGains &OutGains) const
void PanSample (float InSample, float PolarAngle, FChannelGains &OutGains) const
HARMONIXDSP_API void SetChannelLayout (EAudioBufferChannelLayout ChannelLayout)
Static Public Member Functions
static FORCEINLINE FGainTable & Get ()
static HARMONIXDSP_API void Init (EAudioBufferChannelLayout ChannelLayout=EAudioBufferChannelLayout::Stereo)
static HARMONIXDSP_API void SetupPrimaryGainTable (EAudioBufferChannelLayout ChannelLayout)
Private Member Functions
HARMONIXDSP_API void BuildPanEntriesFromPannableSpeakerAzimuths (int32 NumSpeakers, const float *SpeakerAzimuths, const uint8 *InRemap)
HARMONIXDSP_API bool CurrentLayoutHasSpeaker (ESpeakerChannelAssignment ChannelAssignment) const
Private Attributes
EAudioBufferChannelLayout CurrentLayout = EAudioBufferChannelLayout::UnsupportedFormat
FChannelGains Entries [kGainTableSize]
int32 SpeakerCount = 0
uint32 SpeakerMask = 0
Static Private Attributes
static HARMONIXDSP_API FGainTable * gGainTable
static const uint32 kGainTableSize = 1024
Detailed Description
Definition at line 24 of file GainTable.h.
Constructor & Destructor Documentation
FGainTable()
HARMONIXDSP_API FGainTable::FGainTable ()
Referenced by Get().
Member Function Documentation
BuildPanEntriesFromPannableSpeakerAzimuths()
HARMONIXDSP_API void FGainTable::BuildPanEntriesFromPannableSpeakerAzimuths (int32 NumSpeakers, const float * SpeakerAzimuths, const uint8 * InRemap) private
CurrentLayoutHasSpeaker()
HARMONIXDSP_API bool FGainTable::CurrentLayoutHasSpeaker (ESpeakerChannelAssignment ChannelAssignment) const private
Get()
FORCEINLINE FGainTable & FGainTable::Get () static
References FGainTable(), and FORCEINLINE.
Referenced by USTRUCT().
GetDirectChannelAzimuthInCurrentLayout()
HARMONIXDSP_API FORCEINLINE float FGainTable::GetDirectChannelAzimuthInCurrentLayout (ESpeakerChannelAssignment ChannelAssignment) const
References FORCEINLINE.
Referenced by USTRUCT().
GetGains()
const FChannelGains & FGainTable::GetGains (float PolarAngle) const
GetGainsForDirectAssignment()
HARMONIXDSP_API FORCEINLINE void FGainTable::GetGainsForDirectAssignment (ESpeakerChannelAssignment ChannelAssignment, FChannelGains & OutGains) const
References FORCEINLINE.
Init()
HARMONIXDSP_API void FGainTable::Init (EAudioBufferChannelLayout ChannelLayout = EAudioBufferChannelLayout::Stereo) static
References Stereo.
PanSample()
void FGainTable::PanSample (float InSample, float PolarAngle, FChannelGains & OutGains) const
SetChannelLayout()
HARMONIXDSP_API void FGainTable::SetChannelLayout (EAudioBufferChannelLayout ChannelLayout)
SetupPrimaryGainTable()
HARMONIXDSP_API void FGainTable::SetupPrimaryGainTable (EAudioBufferChannelLayout ChannelLayout) static
Field Documentation
CurrentLayout
EAudioBufferChannelLayout FGainTable::CurrentLayout = EAudioBufferChannelLayout::UnsupportedFormat private
Definition at line 44 of file GainTable.h.
Entries
FChannelGains FGainTable::Entries[kGainTableSize] private
Definition at line 49 of file GainTable.h.
gGainTable
HARMONIXDSP_API FGainTable* FGainTable::gGainTable static private
Definition at line 54 of file GainTable.h.
kGainTableSize
const uint32 FGainTable::kGainTableSize = 1024 static private
Definition at line 48 of file GainTable.h.
SpeakerCount
int32 FGainTable::SpeakerCount = 0 private
Definition at line 45 of file GainTable.h.
SpeakerMask
uint32 FGainTable::SpeakerMask = 0 private
Definition at line 46 of file GainTable.h.
The documentation for this class was generated from the following file:
GainTable.h