Unreal Engine 5.6 C++ API: FWidgetStyle Class Reference
FWidgetStyle Class Reference
Contains info about those aspects of widget appearance that should be propagated hierarchically.
#include "WidgetStyle.h"
Public Member Functions
FWidgetStyle ()
Default constructor.
FWidgetStyle & BlendColorAndOpacityTint (const FLinearColor &InTint)
Blends the current tint color with the specified tint.
FWidgetStyle & BlendOpacity (float InOpacity)
Blends the current tint color with the specified alpha.
const FLinearColor & GetColorAndOpacityTint () const
Gets the style's color opacity and tint.
const FLinearColor & GetForegroundColor () const
Gets the style's foreground color.
const FLinearColor & GetSubduedForegroundColor () const
Gets the style's subdued color.
FWidgetStyle & SetForegroundColor (const FLinearColor &InForeground)
Sets the current foreground color from the given linear color.
FWidgetStyle & SetForegroundColor (const TAttribute< FSlateColor > &InForeground)
Sets the current foreground color from the given Slate color attribute.
Private Attributes
FLinearColor ColorAndOpacityTint
FLinearColor ForegroundColor
FLinearColor SubduedForeground
Static Private Attributes
static const float SubdueAmount
Detailed Description
Contains info about those aspects of widget appearance that should be propagated hierarchically.
Definition at line 14 of file WidgetStyle.h.
Constructor & Destructor Documentation
FWidgetStyle()
FWidgetStyle::FWidgetStyle () inline
Default constructor.
Definition at line 19 of file WidgetStyle.h.
References ColorAndOpacityTint, ForegroundColor, SubdueAmount, and SubduedForeground.
Referenced by BlendColorAndOpacityTint(), BlendOpacity(), SetForegroundColor(), and SetForegroundColor().
Member Function Documentation
BlendColorAndOpacityTint()
FWidgetStyle & FWidgetStyle::BlendColorAndOpacityTint (const FLinearColor & InTint) inline
Blends the current tint color with the specified tint.
Parameters
InTint The color to blend with.
Returns
This instance (for method chaining).
Definition at line 33 of file WidgetStyle.h.
References FWidgetStyle(), and ColorAndOpacityTint.
BlendOpacity()
FWidgetStyle & FWidgetStyle::BlendOpacity (float InOpacity) inline
Blends the current tint color with the specified alpha.
Parameters
InTint The color to blend with.
Returns
This instance (for method chaining).
Definition at line 45 of file WidgetStyle.h.
References FWidgetStyle(), and ColorAndOpacityTint.
GetColorAndOpacityTint()
const FLinearColor & FWidgetStyle::GetColorAndOpacityTint () const inline
Gets the style's color opacity and tint.
Returns
Current opacity and tint.
See also
GetForegroundColor, GetSubduedForegroundColor
Definition at line 87 of file WidgetStyle.h.
References ColorAndOpacityTint.
Referenced by FArguments< ItemType >::OnPaintDropIndicator(), and FArguments< ItemType >::PaintSelection().
GetForegroundColor()
const FLinearColor & FWidgetStyle::GetForegroundColor () const inline
Gets the style's foreground color.
Returns
Current foreground color.
See also
GetColorAndOpacityTint, GetSubduedForegroundColor, SetForegroundColor
Definition at line 98 of file WidgetStyle.h.
References ForegroundColor.
Referenced by USTRUCT().
GetSubduedForegroundColor()
const FLinearColor & FWidgetStyle::GetSubduedForegroundColor () const inline
Gets the style's subdued color.
Returns
Current subdued color.
See also
GetColorAndOpacityTint, GetForegroundColor
Definition at line 109 of file WidgetStyle.h.
References SubduedForeground.
Referenced by USTRUCT().
SetForegroundColor() [1/2]
FWidgetStyle & FWidgetStyle::SetForegroundColor (const FLinearColor & InForeground) inline
Sets the current foreground color from the given linear color.
Parameters
InForeground The foreground color value to set.
Returns
This instance (for method chaining).
See also
GetForegroundColor
Definition at line 58 of file WidgetStyle.h.
References FWidgetStyle(), ForegroundColor, SubdueAmount, and SubduedForeground.
SetForegroundColor() [2/2]
FWidgetStyle & FWidgetStyle::SetForegroundColor (const TAttribute< FSlateColor > & InForeground)
Sets the current foreground color from the given Slate color attribute.
If the attribute passed in is not set, the foreground will remain unchanged.
Parameters
InForeground The foreground color to set.
Returns
This instance (for method chaining).
See also
GetForegroundColor
References FWidgetStyle().
Field Documentation
ColorAndOpacityTint
FLinearColor FWidgetStyle::ColorAndOpacityTint private
Definition at line 116 of file WidgetStyle.h.
Referenced by FWidgetStyle(), BlendColorAndOpacityTint(), BlendOpacity(), and GetColorAndOpacityTint().
ForegroundColor
FLinearColor FWidgetStyle::ForegroundColor private
Definition at line 117 of file WidgetStyle.h.
Referenced by FWidgetStyle(), GetForegroundColor(), and SetForegroundColor().
SubdueAmount
const float FWidgetStyle::SubdueAmount static private
Definition at line 122 of file WidgetStyle.h.
Referenced by FWidgetStyle(), and SetForegroundColor().
SubduedForeground
FLinearColor FWidgetStyle::SubduedForeground private
Definition at line 118 of file WidgetStyle.h.
Referenced by FWidgetStyle(), GetSubduedForegroundColor(), and SetForegroundColor().
The documentation for this class was generated from the following file:
WidgetStyle.h