Unreal Engine 5.6 C++ API: TRefCountingMixin< T, ERefCountingMode::NotThreadSafe > Class Template Reference
TRefCountingMixin< T, ERefCountingMode::NotThreadSafe > Class Template Reference
Not-thread-safe specialization.
#include "RefCounting.h"
Public Member Functions
TRefCountingMixin ()=default
TRefCountingMixin (const TRefCountingMixin &)=delete
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
TRefCountingMixin & operator= (const TRefCountingMixin &)=delete
uint32 Release () const
Static Public Member Functions
static void StaticDestroyObject (const T *Obj)
Static Private Member Functions
static void StaticDestroyMixin (const TRefCountingMixin *This)
Private Attributes
uint32 RefCount
Detailed Description
template<typename T>
class TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >
Not-thread-safe specialization.
Definition at line 404 of file RefCounting.h.
Constructor & Destructor Documentation
TRefCountingMixin() [1/2]
template<typename T> TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::TRefCountingMixin () default
Referenced by TRefCountingMixin(), operator=(), and StaticDestroyMixin().
TRefCountingMixin() [2/2]
template<typename T> TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::TRefCountingMixin (const TRefCountingMixin< T, ERefCountingMode::NotThreadSafe > &) delete
References TRefCountingMixin().
Member Function Documentation
AddRef()
template<typename T> FReturnedRefCountValue TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::AddRef () const inline
Definition at line 412 of file RefCounting.h.
References RefCount.
GetRefCount()
template<typename T> uint32 TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::GetRefCount () const inline
Definition at line 430 of file RefCounting.h.
References RefCount.
operator=()
template<typename T> TRefCountingMixin & TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::operator= (const TRefCountingMixin< T, ERefCountingMode::NotThreadSafe > &) delete
References TRefCountingMixin().
Release()
template<typename T> uint32 TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::Release () const inline
Definition at line 417 of file RefCounting.h.
References checkSlow, RefCount, and StaticDestroyMixin().
StaticDestroyMixin()
template<typename T> void TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::StaticDestroyMixin (const TRefCountingMixin< T, ERefCountingMode::NotThreadSafe > * This) inline static private
Definition at line 441 of file RefCounting.h.
References TRefCountingMixin().
Referenced by Release().
StaticDestroyObject()
template<typename T> void TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::StaticDestroyObject (const T * Obj) inline static
Definition at line 435 of file RefCounting.h.
Field Documentation
RefCount
template<typename T> uint32 TRefCountingMixin< T, ERefCountingMode::NotThreadSafe >::RefCount mutable private
Definition at line 446 of file RefCounting.h.
Referenced by AddRef(), GetRefCount(), and Release().
The documentation for this class was generated from the following file:
RefCounting.h