Unreal Engine 5.6 C++ API: kDOP.h File Reference
kDOP.h File Reference
#include "CoreMinimal.h"
#include "Containers/ChunkedArray.h"
#include "Templates/UnrealTemplate.h"
Data Structures
struct FFourBox
Holds the min/max planes that make up a set of 4 bounding volumes.
struct FkDOPBuildCollisionTriangle< KDOP_IDX_TYPE >
struct FkHitResult
struct FTriangleSOA
Stores 4 triangles in one struct (Struct Of Arrays).
struct FVector3SOA
Stores XYZ from 4 vectors in one Struct Of Arrays.
struct FVector4SOA
Stores XYZW from 4 vectors in one Struct Of Arrays.
struct TkDOPCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >
Base struct for all collision checks.
struct TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >
This struct holds the information used to do a line check against the kDOP tree.
struct TkDOPNode< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >
A node in the kDOP tree.
struct TkDOPTree< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >
This is the tree of kDOPs that spatially divides the static mesh.
struct TTraversalHistory< KDOP_IDX_TYPE >
Tracks information about a traversal through the kDOP tree.
Macros
#define kDOPArray TChunkedArray
#define NUM_PLANES 3
#define PLAIN_C 0
Functions
FORCEINLINE bool appLineCheckTriangle (const FVector4 &Start, const FVector4 &End, const FVector4 &Dir, const FVector4 &V0, const FVector4 &V1, const FVector4 &V2, const FVector4 &Normal, float &IntersectionTime)
Line vs triangle intersection test.
static int32 appLineCheckTriangleSOA (const FVector3SOA &Start, const FVector3SOA &End, const FVector3SOA &Dir, const FTriangleSOA &Triangle4, float &InOutIntersectionTime)
Line vs triangle intersection test.
Variables
static const VectorRegister GSmallNegativeNumber = MakeVectorRegister(-0.0001f, -0.0001f, -0.0001f, -0.0001f)
(-0.0001f, -0.0001f, -0.0001f, -0.0001f)
static const VectorRegister GSmallNumber = MakeVectorRegister(0.0001f, 0.0001f, 0.0001f, 0.0001f)
(0.0001f, 0.0001f, 0.0001f, 0.0001f)
static const VectorRegister GZeroVectorRegister = MakeVectorRegister(0.f, 0.f, 0.f, 0.f)
static const VectorRegister VectorNegativeOne = MakeVectorRegister(-1.0f, -1.0f, -1.0f, -1.0f)
Macro Definition Documentation
kDOPArray
#define kDOPArray TChunkedArray
Definition at line 370 of file kDOP.h.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::SplitTriangleList().
NUM_PLANES
#define NUM_PLANES 3
Definition at line 10 of file kDOP.h.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::SplitTriangleList().
PLAIN_C
#define PLAIN_C 0
Function Documentation
appLineCheckTriangle()
FORCEINLINE bool appLineCheckTriangle (const FVector4 & Start, const FVector4 & End, const FVector4 & Dir, const FVector4 & V0, const FVector4 & V1, const FVector4 & V2, const FVector4 & Normal, float & IntersectionTime)
Line vs triangle intersection test.
Parameters
Start Start of the line segment
End End of the line segment
Dir Direction of the line segment (not normalized, just End-Start)
V0 First vertex of the triangle
V1 Second vertex of the triangle
V2 Third vertex of the triangle
Normal Triangle normal (including +W for the plane equation)
IntersectionTime [in/out] Best intersection time so far (0..1), as in: IntersectionPoint = Start + IntersectionTime * Dir.
Returns
true if the line intersected the triangle
Definition at line 122 of file kDOP.h.
References Dot3(), End, FORCEINLINE, Normal, UE::Math::TPlane< T >::PlaneDot(), and Time.
appLineCheckTriangleSOA()
int32 appLineCheckTriangleSOA (const FVector3SOA & Start, const FVector3SOA & End, const FVector3SOA & Dir, const FTriangleSOA & Triangle4, float & InOutIntersectionTime) static
Line vs triangle intersection test.
Tests 1 line against 4 triangles at once.
Parameters
Start Start of the line segment
End End of the line segment
Dir Direction of the line segment (not normalized, just End-Start)
Triangle4 Four triangles
IntersectionTime [in/out] Best intersection time so far (0..1), as in: IntersectionPoint = Start + IntersectionTime * Dir.
Returns
Index (0-3) to specify which of the 4 triangles the line intersected, or -1 if none was found.
Definition at line 190 of file kDOP.h.
References End, GSmallNegativeNumber, GSmallNumber, FTriangleSOA::Normals, FTriangleSOA::Positions, Time, VectorBitwiseAnd(), VectorDivide(), VectorLoadFloat1(), VectorMask_EQ, VectorMask_GE, VectorMask_LE, VectorMask_LT, VectorMaskBits(), VectorMin(), VectorMultiply(), VectorMultiplyAdd(), VectorNegateMultiplyAdd(), VectorReplicate, VectorSelect(), VectorStoreFloat1(), VectorSubtract(), VectorSwizzle, FVector4SOA::W, FVector3SOA::X, FVector4SOA::X, FVector3SOA::Y, FVector4SOA::Y, FVector3SOA::Z, and FVector4SOA::Z.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckTriangles().
Variable Documentation
GSmallNegativeNumber
const VectorRegister GSmallNegativeNumber = MakeVectorRegister(-0.0001f, -0.0001f, -0.0001f, -0.0001f) static
(-0.0001f, -0.0001f, -0.0001f, -0.0001f)
Definition at line 169 of file kDOP.h.
Referenced by appLineCheckTriangleSOA().
GSmallNumber
const VectorRegister GSmallNumber = MakeVectorRegister(0.0001f, 0.0001f, 0.0001f, 0.0001f) static
(0.0001f, 0.0001f, 0.0001f, 0.0001f)
Definition at line 173 of file kDOP.h.
Referenced by appLineCheckTriangleSOA().
GZeroVectorRegister
const VectorRegister GZeroVectorRegister = MakeVectorRegister(0.f, 0.f, 0.f, 0.f) static
Definition at line 176 of file kDOP.h.
VectorNegativeOne
const VectorRegister VectorNegativeOne = MakeVectorRegister(-1.0f, -1.0f, -1.0f, -1.0f) static
Definition at line 178 of file kDOP.h.