Unreal Engine 5.6 C++ API: TConstStructView< BaseStructT > Struct Template Reference
TConstStructView< BaseStructT > Struct Template Reference
TConstStructView is a type-safe FConstStructView wrapper against the given BaseStruct type.
#include "StructView.h"
Public Member Functions
TConstStructView ()=default
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TConstStructView (const T &InStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TConstStructView (const TConstSharedStruct< T > &SharedStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TConstStructView (const TInstancedStruct< T > &InstancedStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TConstStructView (const TSharedStruct< T > &SharedStruct)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TConstStructView (const TStructView< T > StructView)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
TConstStructView (const uint8 *InStructMemory=nullptr)
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
constexpr const T & Get () const
Returns const reference to the struct, this getter assumes that all data is valid.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
constexpr const T * GetPtr () const
Returns const pointer to the struct, or nullptr if cast is not valid.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
bool operator!= (const TConstStructView< T > &Other) const
BaseStructT * operator-> () const
Simplified accessor for members of the guaranteed minimum structure type.
template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>>
bool operator== (const TConstStructView< T > &Other) const
Comparison operators.
Public Member Functions inherited from FConstStructView
FConstStructView ()=default
FConstStructView (const FConstSharedStruct &SharedStruct)
FConstStructView (const FInstancedStruct &InstancedStruct)
FConstStructView (const FSharedStruct &SharedStruct)
FConstStructView (const FStructView StructView)
FConstStructView (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory=nullptr)
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T & >::Type Get () const
Returns const reference to the struct, this getter assumes that all data is valid.
const uint8 * GetMemory () const
Returns const pointer to struct memory.
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T * >::Type GetPtr () const
Returns const pointer to the struct, or nullptr if cast is not valid.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
bool IsValid () const
Returns True if the struct is valid.
template<typename OtherType>
bool operator!= (const OtherType &Other) const
template<typename OtherType>
bool operator== (const OtherType &Other) const
Comparison operators.
void Reset ()
Reset to empty.
void SetStructData (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory)
Additional Inherited Members
Static Public Member Functions inherited from FConstStructView
template<typename T>
static FConstStructView Make (const T &Struct)
Creates a new FConstStructView from the templated struct.
Protected Attributes inherited from FConstStructView
const UScriptStruct * ScriptStruct = nullptr
const uint8 * StructMemory = nullptr
Detailed Description
template<typename BaseStructT>
struct TConstStructView< BaseStructT >
TConstStructView is a type-safe FConstStructView wrapper against the given BaseStruct type.
Example:
TConstStructView<FTestStructBase> Test;
TArray<TConstStructView<FTestStructBase>> TestArray;
Definition at line 311 of file StructUtils/StructView.h.
Constructor & Destructor Documentation
TConstStructView() [1/7]
template<typename BaseStructT> TConstStructView< BaseStructT >::TConstStructView () explicit default
Referenced by operator!=(), and operator==().
TConstStructView() [2/7]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TConstStructView< BaseStructT >::TConstStructView (const T & InStruct) inline
Definition at line 316 of file StructUtils/StructView.h.
References FConstStructView::FConstStructView(), and StaticStruct().
TConstStructView() [3/7]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TConstStructView< BaseStructT >::TConstStructView (const uint8 * InStructMemory = nullptr) inline explicit
Definition at line 321 of file StructUtils/StructView.h.
References FConstStructView::FConstStructView(), and StaticStruct().
TConstStructView() [4/7]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TConstStructView< BaseStructT >::TConstStructView (const TInstancedStruct< T > & InstancedStruct) inline
Definition at line 326 of file StructUtils/StructView.h.
References FConstStructView::FConstStructView(), FConstStructView::GetMemory(), and FConstStructView::GetScriptStruct().
TConstStructView() [5/7]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TConstStructView< BaseStructT >::TConstStructView (const TSharedStruct< T > & SharedStruct) inline
Definition at line 331 of file StructUtils/StructView.h.
References FConstStructView::FConstStructView(), FConstStructView::GetMemory(), and FConstStructView::GetScriptStruct().
TConstStructView() [6/7]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TConstStructView< BaseStructT >::TConstStructView (const TConstSharedStruct< T > & SharedStruct) inline
Definition at line 336 of file StructUtils/StructView.h.
References FConstStructView::FConstStructView(), FConstStructView::GetMemory(), and FConstStructView::GetScriptStruct().
TConstStructView() [7/7]
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> TConstStructView< BaseStructT >::TConstStructView (const TStructView< T > StructView) inline
Definition at line 341 of file StructUtils/StructView.h.
References FConstStructView::FConstStructView(), FConstStructView::GetMemory(), and FConstStructView::GetScriptStruct().
Member Function Documentation
Get()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> const T & TConstStructView< BaseStructT >::Get () const inline constexpr
Returns const reference to the struct, this getter assumes that all data is valid.
Definition at line 347 of file StructUtils/StructView.h.
References UE::StructUtils::GetStructRef(), FConstStructView::ScriptStruct, and FConstStructView::StructMemory.
GetPtr()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> const T * TConstStructView< BaseStructT >::GetPtr () const inline constexpr
Returns const pointer to the struct, or nullptr if cast is not valid.
Definition at line 354 of file StructUtils/StructView.h.
References UE::StructUtils::GetStructPtr(), FConstStructView::ScriptStruct, and FConstStructView::StructMemory.
Referenced by operator->().
operator!=()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> bool TConstStructView< BaseStructT >::operator!= (const TConstStructView< T > & Other) const inline
Definition at line 381 of file StructUtils/StructView.h.
References TConstStructView(), operator==(), and Other.
operator->()
template<typename BaseStructT> BaseStructT * TConstStructView< BaseStructT >::operator-> () const inline
Simplified accessor for members of the guaranteed minimum structure type.
Definition at line 367 of file StructUtils/StructView.h.
References check, GetPtr(), and IsValid().
operator==()
template<typename BaseStructT> template<typename T = BaseStructT, typename = std::enable_if_t<std::is_base_of_v<BaseStructT, std::decay_t<T>>>> bool TConstStructView< BaseStructT >::operator== (const TConstStructView< T > & Other) const inline
Comparison operators.
Note: it does not compare the internal structure itself
Definition at line 375 of file StructUtils/StructView.h.
References TConstStructView(), Other, FConstStructView::ScriptStruct, and FConstStructView::StructMemory.
The documentation for this struct was generated from the following files:
StructUtils/InstancedStruct.h
StructUtils/StructView.h