Unreal Engine 5.6 C++ API: IPropertyHandle Class Reference
IPropertyHandle Class Reference abstract
A handle to a property which is used to read and write the value without needing to handle Pre/PostEditChange, transactions, package modification A handle also is used to identify the property in detail customization interfaces.
#include "PropertyHandle.h"
Public Types
typedef TFunctionRef< bool(const void *, const int32, const int32)> EnumerateConstRawDataFuncRef
Return true to continue enumeration.
typedef TFunctionRef< bool(void *, const int32, const int32)> EnumerateRawDataFuncRef
Enumerate the raw data of this property.
Public Member Functions
virtual ~IPropertyHandle ()
virtual void AccessRawData (TArray< const void * > &RawData) const =0
virtual void AccessRawData (TArray< void * > &RawData)=0
Accesses the raw data of this property.
virtual TArray< TSharedPtr< IPropertyHandle > > AddChildStructure (TSharedRef< FStructOnScope > ChildStructure)=0
Adds a child structure.
virtual TArray< TSharedPtr< IPropertyHandle > > AddChildStructure (TSharedRef< IStructureDataProvider > ChildStructure)=0
virtual void AddRestriction (TSharedRef< const FPropertyRestriction > Restriction)=0
Adds a restriction to the possible values for this property.
virtual TSharedPtr< IPropertyHandleArray > AsArray ()=0
Returns this handle as an array if possible.
virtual TSharedPtr< IPropertyHandleMap > AsMap ()=0
virtual TSharedPtr< IPropertyHandleOptional > AsOptional ()=0
virtual TSharedPtr< IPropertyHandleSet > AsSet ()=0
virtual TSharedPtr< IPropertyHandleStruct > AsStruct ()=0
virtual bool CanResetToDefault () const =0
Returns whether or not the property can be set to default.
virtual void ClearResetToDefaultCustomized ()=0
Marks this property as not having a custom reset to default (useful when a widget customizing reset to default goes away)
virtual TSharedRef< SWidget > CreateDefaultPropertyButtonWidgets () const =0
Creates the default buttons which appear next to value widgets.
virtual void CreateDefaultPropertyCopyPasteActions (FUIAction &OutCopyAction, FUIAction &OutPasteAction) const =0
Creates the default copy and paste actions for a single property.
virtual TSharedPtr< FPropertyPath > CreateFPropertyPath () const =0
Helper to fetch a PropertyPath.
virtual TSharedRef< SWidget > CreatePropertyNameWidget (const FText &NameOverride=FText::GetEmpty(), const FText &ToolTipOverride=FText::GetEmpty()) const =0
Creates a name widget for this property.
virtual TSharedRef< SWidget > CreatePropertyValueWidget (bool bDisplayDefaultPropertyButtons=true) const =0
Creates a value widget for this property.
virtual TSharedRef< SWidget > CreatePropertyValueWidgetWithCustomization (const IDetailsView *DetailsView)=0
Creates a value widget for this property using customization, if available.
virtual bool DiffersFromDefault () const =0
virtual void EnumerateConstRawData (const EnumerateConstRawDataFuncRef &InRawDataCallback) const =0
virtual void EnumerateRawData (const EnumerateRawDataFuncRef &InRawDataCallback)=0
Return true to continue enumeration.
virtual void ExecuteCustomResetToDefault (const FResetToDefaultOverride &OnCustomResetToDefault)=0
Sets an override for this property's reset to default behavior.
virtual FString GeneratePathToProperty () const =0
Generates a path from the parent UObject class to this property.
virtual bool GeneratePossibleValues (TArray< FString > &OutOptionStrings, TArray< FText > &OutToolTips, TArray< bool > &OutRestrictedItems, TArray< FText > *OutDisplayNames)=0
Generates a list of possible enum/class options for the property DisplayNames is optional.
virtual bool GeneratePossibleValues (TArray< TSharedPtr< FString > > &OutOptionStrings, TArray< FText > &OutToolTips, TArray< bool > &OutRestrictedItems)=0
Generates a list of possible enum/class options for the property.
virtual bool GenerateRestrictionToolTip (const FString &Value, FText &OutTooltip) const =0
Generates a consistent tooltip describing this restriction for use in the editor.
virtual int32 GetArrayIndex () const =0
Helper to fetch the ArrayIndex.
virtual bool GetBoolMetaData (const FName &Key) const =0
Find the metadata value associated with the key and return bool.
virtual TSharedPtr< IPropertyHandle > GetChildHandle (FName ChildName, bool bRecurse=true) const =0
Gets a child handle of this handle.
virtual TSharedPtr< IPropertyHandle > GetChildHandle (uint32 Index) const =0
Gets a child handle of this handle.
virtual UClass * GetClassMetaData (const FName &Key) const =0
Find the metadata value associated with the key and return UClass*.
virtual FName GetDefaultCategoryName () const =0
Gets the category FName that a property is in at the default location defined by the class the property is in It does not handle the property being moved to another category during customization.
virtual FText GetDefaultCategoryText () const =0
Gets the category display name that a property is in at the default location defined by the class the property is in It does not handle the property being moved to another category during customization.
virtual FString GetDocumentationExcerptName ()=0
virtual FString GetDocumentationLink ()=0
virtual double GetDoubleMetaData (const FName &Key) const =0
Find the metadata value associated with the key and return double.
virtual float GetFloatMetaData (const FName &Key) const =0
Find the metadata value associated with the key and return float.
virtual int32 GetIndexInArray () const =0
virtual const FString * GetInstanceMetaData (const FName &Key) const =0
Get metadata value for 'Key' for this property instance (as opposed to the class)
virtual const TMap< FName, FString > * GetInstanceMetaDataMap () const =0
Get metadata map for this property instance (as opposed to the class)
virtual int32 GetIntMetaData (const FName &Key) const =0
Find the metadata value associated with the key and return int32.
virtual TSharedPtr< IPropertyHandle > GetKeyHandle () const =0
virtual const FString & GetMetaData (const FName &Key) const =0
Find the metadata value associated with the key.
virtual FProperty * GetMetaDataProperty () const =0
Gets the property we should use to read meta-data.
virtual FPropertyAccess::Result GetNumChildren (uint32 &OutNumChildren) const =0
virtual uint32 GetNumOuterObjects () const =0
virtual int32 GetNumPerObjectValues () const =0
Gets the number of objects that this handle is editing.
virtual const UClass * GetOuterBaseClass () const =0
Get the shared base class of the objects that contain this property.
virtual void GetOuterObjects (TArray< UObject * > &OuterObjects) const =0
Get the objects that contain this property.
virtual void GetOuterPackages (TArray< UPackage * > &OuterPackages) const =0
Get the packages that contain this property.
virtual void GetOuterStructs (TArray< TSharedPtr< FStructOnScope > > &OutStructs) const =0
Get the structures that contain this property.
virtual TSharedPtr< IPropertyHandle > GetParentHandle () const =0
virtual FPropertyAccess::Result GetPerObjectValue (const int32 ObjectIndex, FString &OutObjectValue) const =0
Gets a value for the specified object that this handle is editing.
virtual FPropertyAccess::Result GetPerObjectValues (TArray< FString > &OutPerObjectValues) const =0
Gets a unique value for each object this handle is editing.
virtual FProperty * GetProperty () const =0
Gets the property being edited.
virtual const FFieldClass * GetPropertyClass () const =0
Gets the class of the property being edited.
virtual FText GetPropertyDisplayName () const =0
virtual FStringView GetPropertyPath () const =0
Helper to fetch a PropertyPath.
virtual FText GetResetToDefaultLabel () const =0
virtual FText GetToolTipText () const =0
Gets the property tool tip text.
virtual FPropertyAccess::Result GetValue (bool &OutValue) const =0
virtual FPropertyAccess::Result GetValue (const FProperty *&OutValue) const =0
virtual FPropertyAccess::Result GetValue (const UObject *&OutValue) const =0
virtual FPropertyAccess::Result GetValue (double &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FAssetData &OutValue) const =0
virtual FPropertyAccess::Result GetValue (float &OutValue) const =0
Gets the typed value of a property.
virtual FPropertyAccess::Result GetValue (FName &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FProperty *&OutValue) const =0
virtual FPropertyAccess::Result GetValue (FQuat &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FRotator &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FString &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FText &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FVector &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FVector2D &OutValue) const =0
virtual FPropertyAccess::Result GetValue (FVector4 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (int16 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (int32 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (int64 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (int8 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (uint16 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (uint32 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (uint64 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (uint8 &OutValue) const =0
virtual FPropertyAccess::Result GetValue (UObject *&OutValue) const =0
virtual FPropertyAccess::Result GetValueAsDisplayString (FString &OutValue, EPropertyPortFlags PortFlags=PPF_PropertyWindow) const =0
Gets the value formatted as a string, possibly using an alternate form more suitable for display in the UI.
virtual FPropertyAccess::Result GetValueAsDisplayText (FText &OutValue) const =0
Gets the value formatted as a string, as Text, possibly using an alternate form more suitable for display in the UI.
virtual FPropertyAccess::Result GetValueAsFormattedString (FString &OutValue, EPropertyPortFlags PortFlags=PPF_PropertyWindow) const =0
Gets the value formatted as a string.
virtual FPropertyAccess::Result GetValueAsFormattedText (FText &OutValue) const =0
Gets the value formatted as a string, as Text.
virtual uint8 * GetValueBaseAddress (uint8 *Base) const =0
Calculates the memory address for the data associated with this item's value.
virtual FPropertyAccess::Result GetValueData (void *&OutAddress) const =0
virtual bool HasDocumentation ()=0
virtual bool HasMetaData (const FName &Key) const =0
Determines if the property has any metadata associated with the key.
virtual bool IsCategoryHandle () const =0
virtual bool IsCustomized () const =0
virtual bool IsDisabled (const FString &Value) const =0
Tests if a value is disabled for this property.
virtual bool IsDisabled (const FString &Value, TArray< FText > &OutReasons) const =0
Tests if a value is disabled for this property.
virtual bool IsEditable () const =0
virtual bool IsEditConst () const =0
virtual bool IsExpanded () const =0
virtual bool IsFavorite () const =0
virtual bool IsHidden (const FString &Value) const =0
Tests if a value is hidden for this property.
virtual bool IsHidden (const FString &Value, TArray< FText > &OutReasons) const =0
Tests if a value is hidden for this property.
virtual bool IsResetToDefaultCustomized () const =0
virtual bool IsRestricted (const FString &Value) const =0
Tests if a value is restricted for this property.
virtual bool IsRestricted (const FString &Value, TArray< FText > &OutReasons) const =0
Tests if a value is restricted for this property.
virtual bool IsSamePropertyNode (TSharedPtr< IPropertyHandle > OtherHandle) const =0
virtual bool IsValidHandle () const =0
virtual void MarkHiddenByCustomization ()=0
Marks this property has hidden by customizaton (will not show up in the default place)
virtual void MarkResetToDefaultCustomized (bool bCustomized=true)=0
Marks this property has having a custom reset to default (reset to default will not show up in the default place)
virtual void NotifyFinishedChangingProperties ()=0
Called to manually notify root objects that this property has finished changing This does not need to be called when SetValue functions are used since it will be called automatically.
virtual void NotifyPostChange (EPropertyChangeType::Type ChangeType)=0
Called to manually notify root objects that this property has changed This does not need to be called when SetValue functions are used since it will be called automatically.
virtual void NotifyPreChange ()=0
Called to manually notify root objects that this property is about to change This does not need to be called when SetValue functions are used since it will be called automatically.
virtual void RemoveChildren ()=0
Removes all children of this handle.
virtual void ReplaceOuterObjects (const TArray< UObject * > &OuterObjects)=0
Set the outer objects for this property.
virtual void RequestRebuildChildren ()=0
Indicates that children of this node should be rebuilt next tick.
virtual void ResetToDefault ()=0
Resets the value to its default.
virtual void SetExpanded (bool bExpanded)=0
Sets the expanded flag for this property.
virtual void SetIgnoreValidation (bool bInIgnore)=0
Sets whether or not data validation should occur for this property and all of its children.
virtual void SetInstanceMetaData (const FName &Key, const FString &Value)=0
Set metadata value for 'Key' to 'Value' on this property instance (as opposed to the class)
virtual FPropertyAccess::Result SetObjectValueFromSelection ()=0
Sets the object value from the current editor selection Will fail if this handle isn't an object property.
virtual void SetOnChildPropertyValueChanged (const FSimpleDelegate &InOnChildPropertyValueChanged)=0
Sets a delegate to call when the value of the property of a child is changed.
virtual void SetOnChildPropertyValueChangedWithData (const TDelegate< void(const FPropertyChangedEvent &)> &InOnPropertyValueChanged)=0
Sets a delegate to call when the value of the property of a child is changed including the property changed event as parameter.
virtual void SetOnChildPropertyValuePreChange (const FSimpleDelegate &InOnChildPropertyValuePreChange)=0
Sets a delegate to call when the value of the property of a child is about to be changed.
virtual void SetOnPropertyResetToDefault (const FSimpleDelegate &InOnPropertyResetToDefault)=0
Sets a delegate to call when the property is reset to default.
virtual void SetOnPropertyValueChanged (const FSimpleDelegate &InOnPropertyValueChanged)=0
Sets a delegate to call when the value of the property is changed.
virtual void SetOnPropertyValueChangedWithData (const TDelegate< void(const FPropertyChangedEvent &)> &InOnPropertyValueChanged)=0
Sets a delegate to call when the value of the property is changed including the property changed event as parameter.
virtual void SetOnPropertyValuePreChange (const FSimpleDelegate &InOnPropertyValuePreChange)=0
Sets a delegate to call when the value of the property is about to be changed.
virtual FPropertyAccess::Result SetPerObjectValue (const int32 ObjectIndex, const FString &ObjectValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
Sets a value on the specified object that this handle is editing.
virtual FPropertyAccess::Result SetPerObjectValues (const TArray< FString > &PerObjectValues, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
Sets a unique value for each object this handle is editing.
virtual void SetPropertyDisplayName (FText InDisplayName)=0
Allows the handle to override the node's display name.
virtual void SetToolTipText (const FText &ToolTip)=0
Sets the tooltip shown for this property.
virtual FPropertyAccess::Result SetValue (const bool &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const double &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FAssetData &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const float &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
Sets the typed value of a property.
virtual FPropertyAccess::Result SetValue (const FName &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FProperty *const &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FQuat &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FRotator &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FString &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FText &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FVector &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FVector2D &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const FVector4 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const int16 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const int32 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const int64 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const int8 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const TCHAR *InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const uint16 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const uint32 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const uint64 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const uint8 &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (const UObject *const &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (FProperty *const &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValue (UObject *const &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
virtual FPropertyAccess::Result SetValueFromFormattedString (const FString &InValue, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)=0
Sets the value formatted as a string.
UE_DEPRECATED (5.0, "CreatePropertyNameWidget no longer supports bDisplayResetToDefault, bDisplayText or bDisplayThumbnail.") virtual TSharedRef< SWidget > CreatePropertyNameWidget(const FText &NameOverride
Creates a name widget for this property.
Public Member Functions inherited from TSharedFromThis< IPropertyHandle >
TSharedRef< IPropertyHandle, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPropertyHandle, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
const FText bool bDisplayResetToDefault
const FText bool bool bDisplayText = true
const FText bool bool bool bDisplayThumbnail = true) const = 0
const FText & ToolTipOverride
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IPropertyHandle >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IPropertyHandle >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A handle to a property which is used to read and write the value without needing to handle Pre/PostEditChange, transactions, package modification A handle also is used to identify the property in detail customization interfaces.
Definition at line 42 of file PropertyHandle.h.
Member Typedef Documentation
EnumerateConstRawDataFuncRef
typedef TFunctionRef<bool(const void* , const int32 , const int32)> IPropertyHandle::EnumerateConstRawDataFuncRef
Return true to continue enumeration.
Definition at line 520 of file PropertyHandle.h.
EnumerateRawDataFuncRef
typedef TFunctionRef<bool(void* , const int32 , const int32)> IPropertyHandle::EnumerateRawDataFuncRef
Enumerate the raw data of this property.
(Each pointer can be cast to the property data type)
Parameters
InRawDataCallback The function to call for each data
Definition at line 519 of file PropertyHandle.h.
Constructor & Destructor Documentation
~IPropertyHandle()
virtual IPropertyHandle::~IPropertyHandle () inline virtual
Definition at line 45 of file PropertyHandle.h.
Member Function Documentation
AccessRawData() [1/2]
virtual void IPropertyHandle::AccessRawData (TArray< const void * > & RawData) const pure virtual
References RawData.
AccessRawData() [2/2]
virtual void IPropertyHandle::AccessRawData (TArray< void * > & RawData) pure virtual
Accesses the raw data of this property.
(Each pointer can be cast to the property data type)
Parameters
RawData An array of raw data. The elements in this array are the raw data for this property on each of the objects in the property editor
References RawData.
AddChildStructure() [1/2]
virtual TArray< TSharedPtr< IPropertyHandle > > IPropertyHandle::AddChildStructure (TSharedRef< FStructOnScope > ChildStructure) pure virtual
Adds a child structure.
Parameters
ChildStructure The structure to add
Returns
An array of interfaces to the properties that were added
References AddChildStructure().
Referenced by AddChildStructure(), and AddChildStructure().
AddChildStructure() [2/2]
virtual TArray< TSharedPtr< IPropertyHandle > > IPropertyHandle::AddChildStructure (TSharedRef< IStructureDataProvider > ChildStructure) pure virtual
References AddChildStructure().
AddRestriction()
virtual void IPropertyHandle::AddRestriction (TSharedRef< const FPropertyRestriction > Restriction) pure virtual
Adds a restriction to the possible values for this property.
Parameters
Restriction The restriction being added to this property.
References AddRestriction().
Referenced by AddRestriction().
AsArray()
virtual TSharedPtr< IPropertyHandleArray > IPropertyHandle::AsArray () pure virtual
Returns this handle as an array if possible.
Returns
the handle as an array if it is an array (static or dynamic)
AsMap()
virtual TSharedPtr< IPropertyHandleMap > IPropertyHandle::AsMap () pure virtual
Returns
This handle as a map if possible
AsOptional()
virtual TSharedPtr< IPropertyHandleOptional > IPropertyHandle::AsOptional () pure virtual
Returns
This handle as an optional if possible
AsSet()
virtual TSharedPtr< IPropertyHandleSet > IPropertyHandle::AsSet () pure virtual
Returns
This handle as a set if possible
AsStruct()
virtual TSharedPtr< IPropertyHandleStruct > IPropertyHandle::AsStruct () pure virtual
Returns
This handle as struct if possible
CanResetToDefault()
virtual bool IPropertyHandle::CanResetToDefault () const pure virtual
Returns whether or not the property can be set to default.
Returns
If this property can be reset to default
References CanResetToDefault().
Referenced by CanResetToDefault().
ClearResetToDefaultCustomized()
virtual void IPropertyHandle::ClearResetToDefaultCustomized () pure virtual
Marks this property as not having a custom reset to default (useful when a widget customizing reset to default goes away)
CreateDefaultPropertyButtonWidgets()
virtual TSharedRef< SWidget > IPropertyHandle::CreateDefaultPropertyButtonWidgets () const pure virtual
Creates the default buttons which appear next to value widgets.
This is useful when creating customizations which don't use CreatePropertyValueWidget but you still want array item behaviors and reset to default capabilities.
References CreateDefaultPropertyButtonWidgets().
Referenced by CreateDefaultPropertyButtonWidgets().
CreateDefaultPropertyCopyPasteActions()
virtual void IPropertyHandle::CreateDefaultPropertyCopyPasteActions (FUIAction & OutCopyAction, FUIAction & OutPasteAction) const pure virtual
Creates the default copy and paste actions for a single property.
This is useful when creating customizations which use custom node builders since they can't implement copy/paste by default because the contents of the rows is not known, but frequently you're using the handles on each row to generate this UI.
References CreateDefaultPropertyCopyPasteActions().
Referenced by CreateDefaultPropertyCopyPasteActions().
CreateFPropertyPath()
virtual TSharedPtr< FPropertyPath > IPropertyHandle::CreateFPropertyPath () const pure virtual
Helper to fetch a PropertyPath.
CreatePropertyNameWidget()
virtual TSharedRef< SWidget > IPropertyHandle::CreatePropertyNameWidget (const FText & NameOverride = FText::GetEmpty(), const FText & ToolTipOverride = FText::GetEmpty()) const pure virtual
Creates a name widget for this property.
Parameters
NameOverride The name override to use instead of the property name
ToolTipOverride The tooltip override to use instead of the property name
References CreatePropertyNameWidget(), and ToolTipOverride.
Referenced by CreatePropertyNameWidget().
CreatePropertyValueWidget()
virtual TSharedRef< SWidget > IPropertyHandle::CreatePropertyValueWidget (bool bDisplayDefaultPropertyButtons = true) const pure virtual
Creates a value widget for this property.
Parameters
bDisplayDefaultPropertyButtons If the value widget should include the property buttons.
Returns
the value widget for this property
References CreatePropertyValueWidget().
Referenced by CreatePropertyValueWidget().
CreatePropertyValueWidgetWithCustomization()
virtual TSharedRef< SWidget > IPropertyHandle::CreatePropertyValueWidgetWithCustomization (const IDetailsView * DetailsView) pure virtual
Creates a value widget for this property using customization, if available.
Note that this is only the value widget for the header/main row for properties with child rows (ie: structs)
Parameters
DetailsView The details view to create the value widget for. Used to retrieve per details view customizations.
Returns
the value widget for this property
References CreatePropertyValueWidgetWithCustomization().
Referenced by CreatePropertyValueWidgetWithCustomization().
DiffersFromDefault()
virtual bool IPropertyHandle::DiffersFromDefault () const pure virtual
Returns
Whether or not the value differs from its default
EnumerateConstRawData()
virtual void IPropertyHandle::EnumerateConstRawData (const EnumerateConstRawDataFuncRef & InRawDataCallback) const pure virtual
EnumerateRawData()
virtual void IPropertyHandle::EnumerateRawData (const EnumerateRawDataFuncRef & InRawDataCallback) pure virtual
Return true to continue enumeration.
ExecuteCustomResetToDefault()
virtual void IPropertyHandle::ExecuteCustomResetToDefault (const FResetToDefaultOverride & OnCustomResetToDefault) pure virtual
Sets an override for this property's reset to default behavior.
References ExecuteCustomResetToDefault().
Referenced by ExecuteCustomResetToDefault().
GeneratePathToProperty()
virtual FString IPropertyHandle::GeneratePathToProperty () const pure virtual
Generates a path from the parent UObject class to this property.
Returns
The path to this property
GeneratePossibleValues() [1/2]
virtual bool IPropertyHandle::GeneratePossibleValues (TArray< FString > & OutOptionStrings, TArray< FText > & OutToolTips, TArray< bool > & OutRestrictedItems, TArray< FText > * OutDisplayNames) pure virtual
Generates a list of possible enum/class options for the property DisplayNames is optional.
GeneratePossibleValues() [2/2]
virtual bool IPropertyHandle::GeneratePossibleValues (TArray< TSharedPtr< FString > > & OutOptionStrings, TArray< FText > & OutToolTips, TArray< bool > & OutRestrictedItems) pure virtual
Generates a list of possible enum/class options for the property.
GenerateRestrictionToolTip()
virtual bool IPropertyHandle::GenerateRestrictionToolTip (const FString & Value, FText & OutTooltip) const pure virtual
Generates a consistent tooltip describing this restriction for use in the editor.
Parameters
Value The value to test for restriction and generate the tooltip from.
OutTooltip The tooltip describing why this value is restricted.
Returns
True if this value is restricted.
References GenerateRestrictionToolTip(), and Value.
Referenced by GenerateRestrictionToolTip().
GetArrayIndex()
virtual int32 IPropertyHandle::GetArrayIndex () const pure virtual
Helper to fetch the ArrayIndex.
GetBoolMetaData()
virtual bool IPropertyHandle::GetBoolMetaData (const FName & Key) const pure virtual
Find the metadata value associated with the key and return bool.
Parameters
Key The key to lookup in the metadata
Returns
return true if the value was true (case insensitive)
References Key.
GetChildHandle() [1/2]
virtual TSharedPtr< IPropertyHandle > IPropertyHandle::GetChildHandle (FName ChildName, bool bRecurse = true) const pure virtual
Gets a child handle of this handle.
Useful for accessing properties in structs.
Array elements cannot be accessed in this way
Parameters
ChildName The name of the child
bRecurse Whether or not to recurse into children of children and so on. If false will only search all immediate children
Returns
The property handle for the child if it exists
GetChildHandle() [2/2]
virtual TSharedPtr< IPropertyHandle > IPropertyHandle::GetChildHandle (uint32 Index) const pure virtual
Gets a child handle of this handle.
Useful for accessing properties in structs.
Parameters
The index of the child
Returns
The property handle for the child if it exists
GetClassMetaData()
virtual UClass * IPropertyHandle::GetClassMetaData (const FName & Key) const pure virtual
Find the metadata value associated with the key and return UClass*.
Parameters
Key The key to lookup in the metadata
Returns
the UClass value stored in the metadata.
References Key.
GetDefaultCategoryName()
virtual FName IPropertyHandle::GetDefaultCategoryName () const pure virtual
Gets the category FName that a property is in at the default location defined by the class the property is in It does not handle the property being moved to another category during customization.
References GetDefaultCategoryName().
Referenced by GetDefaultCategoryName().
GetDefaultCategoryText()
virtual FText IPropertyHandle::GetDefaultCategoryText () const pure virtual
Gets the category display name that a property is in at the default location defined by the class the property is in It does not handle the property being moved to another category during customization.
References GetDefaultCategoryText().
Referenced by GetDefaultCategoryText().
GetDocumentationExcerptName()
virtual FString IPropertyHandle::GetDocumentationExcerptName () pure virtual
Returns
The custom documentation except name for this property
GetDocumentationLink()
virtual FString IPropertyHandle::GetDocumentationLink () pure virtual
Returns
The custom documentation link for this property
GetDoubleMetaData()
virtual double IPropertyHandle::GetDoubleMetaData (const FName & Key) const pure virtual
Find the metadata value associated with the key and return double.
Parameters
Key The key to lookup in the metadata
Returns
the double value stored in the metadata.
References Key.
GetFloatMetaData()
virtual float IPropertyHandle::GetFloatMetaData (const FName & Key) const pure virtual
Find the metadata value associated with the key and return float.
Parameters
Key The key to lookup in the metadata
Returns
the float value stored in the metadata.
References Key.
GetIndexInArray()
virtual int32 IPropertyHandle::GetIndexInArray () const pure virtual
Returns
The index of this element in an array if it is in one. INDEX_NONE otherwise
GetInstanceMetaData()
virtual const FString * IPropertyHandle::GetInstanceMetaData (const FName & Key) const pure virtual
Get metadata value for 'Key' for this property instance (as opposed to the class)
Returns
Pointer to metadata value; nullptr if Key not found
References Key.
GetInstanceMetaDataMap()
virtual const TMap< FName, FString > * IPropertyHandle::GetInstanceMetaDataMap () const pure virtual
Get metadata map for this property instance (as opposed to the class)
Returns
Map ptr containing metadata pairs; nullptr if property node is invalid
GetIntMetaData()
virtual int32 IPropertyHandle::GetIntMetaData (const FName & Key) const pure virtual
Find the metadata value associated with the key and return int32.
Parameters
Key The key to lookup in the metadata
Returns
the int value stored in the metadata.
References Key.
GetKeyHandle()
virtual TSharedPtr< IPropertyHandle > IPropertyHandle::GetKeyHandle () const pure virtual
Returns
The property handle to the key element for this value if this is a map element
GetMetaData()
virtual const FString & IPropertyHandle::GetMetaData (const FName & Key) const pure virtual
Find the metadata value associated with the key.
Parameters
Key The key to lookup in the metadata
Returns
The value associated with the key
References Key.
GetMetaDataProperty()
virtual FProperty * IPropertyHandle::GetMetaDataProperty () const pure virtual
Gets the property we should use to read meta-data.
GetNumChildren()
virtual FPropertyAccess::Result IPropertyHandle::GetNumChildren (uint32 & OutNumChildren) const pure virtual
Returns
The number of children the property handle has
GetNumOuterObjects()
virtual uint32 IPropertyHandle::GetNumOuterObjects () const pure virtual
Returns
Get the number objects that contain this property and are being observed in the property editor
GetNumPerObjectValues()
virtual int32 IPropertyHandle::GetNumPerObjectValues () const pure virtual
Gets the number of objects that this handle is editing.
GetOuterBaseClass()
virtual const UClass * IPropertyHandle::GetOuterBaseClass () const pure virtual
Get the shared base class of the objects that contain this property.
Returns
The shared base class of the outer objects, or null if none are selected.
GetOuterObjects()
virtual void IPropertyHandle::GetOuterObjects (TArray< UObject * > & OuterObjects) const pure virtual
Get the objects that contain this property.
Parameters
OuterObjects An array that will be populated with the outer objects
GetOuterPackages()
virtual void IPropertyHandle::GetOuterPackages (TArray< UPackage * > & OuterPackages) const pure virtual
Get the packages that contain this property.
Parameters
OuterPackages An array that will be populated with the outer packages
GetOuterStructs()
virtual void IPropertyHandle::GetOuterStructs (TArray< TSharedPtr< FStructOnScope > > & OutStructs) const pure virtual
Get the structures that contain this property.
Parameters
OutStructs An array that will be populated with the outer structures
GetParentHandle()
virtual TSharedPtr< IPropertyHandle > IPropertyHandle::GetParentHandle () const pure virtual
Returns
a handle to the parent property This parent handle may not contain a valid FProperty if the parent is the uobject.
GetPerObjectValue()
virtual FPropertyAccess::Result IPropertyHandle::GetPerObjectValue (const int32 ObjectIndex, FString & OutObjectValue) const pure virtual
Gets a value for the specified object that this handle is editing.
Parameters
ObjectIndex The index of the object to get the value of
OutObjectValue Filled with the value for this object
GetPerObjectValues()
virtual FPropertyAccess::Result IPropertyHandle::GetPerObjectValues (TArray< FString > & OutPerObjectValues) const pure virtual
Gets a unique value for each object this handle is editing.
GetProperty()
virtual FProperty * IPropertyHandle::GetProperty () const pure virtual
Gets the property being edited.
GetPropertyClass()
virtual const FFieldClass * IPropertyHandle::GetPropertyClass () const pure virtual
Gets the class of the property being edited.
GetPropertyDisplayName()
virtual FText IPropertyHandle::GetPropertyDisplayName () const pure virtual
Returns
The display name of the property
GetPropertyPath()
virtual FStringView IPropertyHandle::GetPropertyPath () const pure virtual
Helper to fetch a PropertyPath.
GetResetToDefaultLabel()
virtual FText IPropertyHandle::GetResetToDefaultLabel () const pure virtual
Returns
A label suitable for displaying the reset to default value
GetToolTipText()
virtual FText IPropertyHandle::GetToolTipText () const pure virtual
Gets the property tool tip text.
GetValue() [1/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (bool & OutValue) const pure virtual
GetValue() [2/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (const FProperty *& OutValue) const pure virtual
GetValue() [3/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (const UObject *& OutValue) const pure virtual
GetValue() [4/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (double & OutValue) const pure virtual
GetValue() [5/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FAssetData & OutValue) const pure virtual
GetValue() [6/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (float & OutValue) const pure virtual
Gets the typed value of a property.
If the property does not support the value type FPropertyAccess::Fail is returned
Parameters
OutValue The value that will be set if successful
Returns
The result of attempting to get the value
GetValue() [7/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FName & OutValue) const pure virtual
GetValue() [8/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FProperty *& OutValue) const pure virtual
GetValue() [9/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FQuat & OutValue) const pure virtual
GetValue() [10/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FRotator & OutValue) const pure virtual
GetValue() [11/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FString & OutValue) const pure virtual
GetValue() [12/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FText & OutValue) const pure virtual
GetValue() [13/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FVector & OutValue) const pure virtual
References FVector.
GetValue() [14/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FVector2D & OutValue) const pure virtual
GetValue() [15/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (FVector4 & OutValue) const pure virtual
GetValue() [16/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (int16 & OutValue) const pure virtual
GetValue() [17/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (int32 & OutValue) const pure virtual
GetValue() [18/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (int64 & OutValue) const pure virtual
GetValue() [19/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (int8 & OutValue) const pure virtual
GetValue() [20/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (uint16 & OutValue) const pure virtual
GetValue() [21/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (uint32 & OutValue) const pure virtual
GetValue() [22/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (uint64 & OutValue) const pure virtual
GetValue() [23/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (uint8 & OutValue) const pure virtual
GetValue() [24/24]
virtual FPropertyAccess::Result IPropertyHandle::GetValue (UObject *& OutValue) const pure virtual
GetValueAsDisplayString()
virtual FPropertyAccess::Result IPropertyHandle::GetValueAsDisplayString (FString & OutValue, EPropertyPortFlags PortFlags = PPF_PropertyWindow) const pure virtual
Gets the value formatted as a string, possibly using an alternate form more suitable for display in the UI.
Parameters
OutValue String where the value is stored. Remains unchanged if the value could not be set
PortFlags Property flags to determine how the string is retrieved. Defaults to PPF_PropertyWindow
Returns
The result of attempting to get the value
References PPF_PropertyWindow.
GetValueAsDisplayText()
virtual FPropertyAccess::Result IPropertyHandle::GetValueAsDisplayText (FText & OutValue) const pure virtual
Gets the value formatted as a string, as Text, possibly using an alternate form more suitable for display in the UI.
Parameters
OutValue Text where the value is stored. Remains unchanged if the value could not be set
Returns
The result of attempting to get the value
GetValueAsFormattedString()
virtual FPropertyAccess::Result IPropertyHandle::GetValueAsFormattedString (FString & OutValue, EPropertyPortFlags PortFlags = PPF_PropertyWindow) const pure virtual
Gets the value formatted as a string.
Parameters
OutValue String where the value is stored. Remains unchanged if the value could not be set
PortFlags Property flags to determine how the string is retrieved. Defaults to PPF_PropertyWindow
Returns
The result of attempting to get the value
References PPF_PropertyWindow.
GetValueAsFormattedText()
virtual FPropertyAccess::Result IPropertyHandle::GetValueAsFormattedText (FText & OutValue) const pure virtual
Gets the value formatted as a string, as Text.
Parameters
OutValue Text where the value is stored. Remains unchanged if the value could not be set
Returns
The result of attempting to get the value
GetValueBaseAddress()
virtual uint8 * IPropertyHandle::GetValueBaseAddress (uint8 * Base) const pure virtual
Calculates the memory address for the data associated with this item's value.
Parameters
Base The location to use as the starting point for the calculation; typically the address of an object.
Returns
A pointer to a FProperty value or UObject.
GetValueData()
virtual FPropertyAccess::Result IPropertyHandle::GetValueData (void *& OutAddress) const pure virtual
HasDocumentation()
virtual bool IPropertyHandle::HasDocumentation () pure virtual
Returns
True if this property has custom documentation, false otherwise
HasMetaData()
virtual bool IPropertyHandle::HasMetaData (const FName & Key) const pure virtual
Determines if the property has any metadata associated with the key.
Parameters
Key The key to lookup in the metadata
Returns
true if there is a (possibly blank) value associated with this key
References Key.
IsCategoryHandle()
virtual bool IPropertyHandle::IsCategoryHandle () const pure virtual
References IsCategoryHandle().
Referenced by IsCategoryHandle().
IsCustomized()
virtual bool IPropertyHandle::IsCustomized () const pure virtual
Returns
True if this property's UI is customized
IsDisabled() [1/2]
virtual bool IPropertyHandle::IsDisabled (const FString & Value) const pure virtual
Tests if a value is disabled for this property.
Parameters
Value The value to test whether it is disabled.
Returns
True if this value is disabled.
References IsDisabled(), and Value.
Referenced by IsDisabled(), and IsDisabled().
IsDisabled() [2/2]
virtual bool IPropertyHandle::IsDisabled (const FString & Value, TArray< FText > & OutReasons) const pure virtual
Tests if a value is disabled for this property.
Parameters
Value The value to test whether it is disabled.
OutReasons Outputs an array of the reasons why this value is disabled.
Returns
True if this value is disabled.
References IsDisabled(), and Value.
IsEditable()
virtual bool IPropertyHandle::IsEditable () const pure virtual
Returns
The opposite of IsEditConst
IsEditConst()
virtual bool IPropertyHandle::IsEditConst () const pure virtual
Returns
Whether or not the property is edit const (can't be changed)
IsExpanded()
virtual bool IPropertyHandle::IsExpanded () const pure virtual
Returns
Whether or not the property is expanded
IsFavorite()
virtual bool IPropertyHandle::IsFavorite () const pure virtual
Returns
true if the property is mark as a favorite
IsHidden() [1/2]
virtual bool IPropertyHandle::IsHidden (const FString & Value) const pure virtual
Tests if a value is hidden for this property.
Parameters
Value The value to test whether it is hidden.
Returns
True if this value is hidden.
References IsHidden(), and Value.
Referenced by IsHidden(), and IsHidden().
IsHidden() [2/2]
virtual bool IPropertyHandle::IsHidden (const FString & Value, TArray< FText > & OutReasons) const pure virtual
Tests if a value is hidden for this property.
Parameters
Value The value to test whether it is hidden.
OutReasons Outputs an array of the reasons why this value is hidden.
Returns
True if this value is hidden.
References IsHidden(), and Value.
IsResetToDefaultCustomized()
virtual bool IPropertyHandle::IsResetToDefaultCustomized () const pure virtual
Returns
True if this property's reset to default UI is customized (but not necessarialy the property UI itself)
IsRestricted() [1/2]
virtual bool IPropertyHandle::IsRestricted (const FString & Value) const pure virtual
Tests if a value is restricted for this property.
Parameters
Value The value to test for restriction.
Returns
True if this value is restricted.
References IsRestricted(), and Value.
Referenced by IsRestricted(), and IsRestricted().
IsRestricted() [2/2]
virtual bool IPropertyHandle::IsRestricted (const FString & Value, TArray< FText > & OutReasons) const pure virtual
Tests if a value is restricted for this property.
Parameters
Value The value to test for restriction.
OutReasons Outputs an array of the reasons why this value is restricted.
Returns
True if this value is restricted.
References IsRestricted(), and Value.
IsSamePropertyNode()
virtual bool IPropertyHandle::IsSamePropertyNode (TSharedPtr< IPropertyHandle > OtherHandle) const pure virtual
Returns
Whether or not the handle points to the same property node. Will return true if both point to an invalid node.
IsValidHandle()
virtual bool IPropertyHandle::IsValidHandle () const pure virtual
Returns
Whether or not the handle points to a valid property node. This can be true but GetProperty may still return null
MarkHiddenByCustomization()
virtual void IPropertyHandle::MarkHiddenByCustomization () pure virtual
Marks this property has hidden by customizaton (will not show up in the default place)
MarkResetToDefaultCustomized()
virtual void IPropertyHandle::MarkResetToDefaultCustomized (bool bCustomized = true) pure virtual
Marks this property has having a custom reset to default (reset to default will not show up in the default place)
NotifyFinishedChangingProperties()
virtual void IPropertyHandle::NotifyFinishedChangingProperties () pure virtual
Called to manually notify root objects that this property has finished changing This does not need to be called when SetValue functions are used since it will be called automatically.
NotifyPostChange()
virtual void IPropertyHandle::NotifyPostChange (EPropertyChangeType::Type ChangeType) pure virtual
Called to manually notify root objects that this property has changed This does not need to be called when SetValue functions are used since it will be called automatically.
NotifyPreChange()
virtual void IPropertyHandle::NotifyPreChange () pure virtual
Called to manually notify root objects that this property is about to change This does not need to be called when SetValue functions are used since it will be called automatically.
RemoveChildren()
virtual void IPropertyHandle::RemoveChildren () pure virtual
Removes all children of this handle.
References RemoveChildren().
Referenced by RemoveChildren().
ReplaceOuterObjects()
virtual void IPropertyHandle::ReplaceOuterObjects (const TArray< UObject * > & OuterObjects) pure virtual
Set the outer objects for this property.
Parameters
OuterObjects An array that contains the new outer objects
RequestRebuildChildren()
virtual void IPropertyHandle::RequestRebuildChildren () pure virtual
Indicates that children of this node should be rebuilt next tick.
Some topology changes will require this
ResetToDefault()
virtual void IPropertyHandle::ResetToDefault () pure virtual
Resets the value to its default.
SetExpanded()
virtual void IPropertyHandle::SetExpanded (bool bExpanded) pure virtual
Sets the expanded flag for this property.
SetIgnoreValidation()
virtual void IPropertyHandle::SetIgnoreValidation (bool bInIgnore) pure virtual
Sets whether or not data validation should occur for this property and all of its children.
It is generally unsafe to set this value unless you know what you are doing. Data validation done by the details panel ensures changes to properties out from under the details panel are known This should only ever be set for extremely large arrays or other costly validation checks where validation is handled by the customizer
References SetIgnoreValidation().
Referenced by SetIgnoreValidation().
SetInstanceMetaData()
virtual void IPropertyHandle::SetInstanceMetaData (const FName & Key, const FString & Value) pure virtual
Set metadata value for 'Key' to 'Value' on this property instance (as opposed to the class)
References Key, and Value.
SetObjectValueFromSelection()
virtual FPropertyAccess::Result IPropertyHandle::SetObjectValueFromSelection () pure virtual
Sets the object value from the current editor selection Will fail if this handle isn't an object property.
SetOnChildPropertyValueChanged()
virtual void IPropertyHandle::SetOnChildPropertyValueChanged (const FSimpleDelegate & InOnChildPropertyValueChanged) pure virtual
Sets a delegate to call when the value of the property of a child is changed.
Parameters
InOnChildPropertyValueChanged The delegate to call
SetOnChildPropertyValueChangedWithData()
virtual void IPropertyHandle::SetOnChildPropertyValueChangedWithData (const TDelegate< void(const FPropertyChangedEvent &)> & InOnPropertyValueChanged) pure virtual
Sets a delegate to call when the value of the property of a child is changed including the property changed event as parameter.
Parameters
InOnPropertyValueChanged The delegate to call. Needs to be of type void with a const FPropertyChangedEvent& parameter
SetOnChildPropertyValuePreChange()
virtual void IPropertyHandle::SetOnChildPropertyValuePreChange (const FSimpleDelegate & InOnChildPropertyValuePreChange) pure virtual
Sets a delegate to call when the value of the property of a child is about to be changed.
Parameters
InOnChildPropertyValuePreChange The delegate to call
SetOnPropertyResetToDefault()
virtual void IPropertyHandle::SetOnPropertyResetToDefault (const FSimpleDelegate & InOnPropertyResetToDefault) pure virtual
Sets a delegate to call when the property is reset to default.
Parameters
InOnPropertyResetToDefault The delegate to call
SetOnPropertyValueChanged()
virtual void IPropertyHandle::SetOnPropertyValueChanged (const FSimpleDelegate & InOnPropertyValueChanged) pure virtual
Sets a delegate to call when the value of the property is changed.
Parameters
InOnPropertyValueChanged The delegate to call
SetOnPropertyValueChangedWithData()
virtual void IPropertyHandle::SetOnPropertyValueChangedWithData (const TDelegate< void(const FPropertyChangedEvent &)> & InOnPropertyValueChanged) pure virtual
Sets a delegate to call when the value of the property is changed including the property changed event as parameter.
Parameters
InOnPropertyValueChanged The delegate to call. Needs to be of type void with a const FPropertyChangedEvent& parameter
SetOnPropertyValuePreChange()
virtual void IPropertyHandle::SetOnPropertyValuePreChange (const FSimpleDelegate & InOnPropertyValuePreChange) pure virtual
Sets a delegate to call when the value of the property is about to be changed.
Parameters
InOnPropertyValuePreChange The delegate to call
SetPerObjectValue()
virtual FPropertyAccess::Result IPropertyHandle::SetPerObjectValue (const int32 ObjectIndex, const FString & ObjectValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
Sets a value on the specified object that this handle is editing.
Parameters
ObjectIndex The index of the object to set the value of
ObjectValue The value to set on the given object
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetPerObjectValues()
virtual FPropertyAccess::Result IPropertyHandle::SetPerObjectValues (const TArray< FString > & PerObjectValues, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
Sets a unique value for each object this handle is editing.
Parameters
PerObjectValues The per object values as a formatted string. There must be one entry per object or the return value is FPropertyAccess::Fail
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetPropertyDisplayName()
virtual void IPropertyHandle::SetPropertyDisplayName (FText InDisplayName) pure virtual
Allows the handle to override the node's display name.
SetToolTipText()
virtual void IPropertyHandle::SetToolTipText (const FText & ToolTip) pure virtual
Sets the tooltip shown for this property.
Parameters
ToolTip The tool tip to show
References ToolTip.
SetValue() [1/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const bool & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [2/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const double & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [3/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FAssetData & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [4/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const float & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
Sets the typed value of a property.
If the property does not support the value type FPropertyAccess::Fail is returned
Parameters
InValue The value to set
Returns
The result of attempting to set the value
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [5/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FName & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [6/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FProperty *const & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [7/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FQuat & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [8/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FRotator & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [9/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FString & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [10/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FText & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [11/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FVector & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, Flags, and FVector.
SetValue() [12/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FVector2D & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [13/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const FVector4 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [14/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const int16 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [15/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const int32 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [16/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const int64 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [17/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const int8 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [18/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const TCHAR * InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [19/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const uint16 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [20/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const uint32 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [21/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const uint64 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [22/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const uint8 & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [23/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (const UObject *const & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [24/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (FProperty *const & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValue() [25/25]
virtual FPropertyAccess::Result IPropertyHandle::SetValue (UObject *const & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
References EPropertyValueSetFlags::DefaultFlags, and Flags.
SetValueFromFormattedString()
virtual FPropertyAccess::Result IPropertyHandle::SetValueFromFormattedString (const FString & InValue, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags) pure virtual
Sets the value formatted as a string.
Parameters
OutValue String where the value is stored. Is unchanged if the value could not be set
Returns
The result of attempting to set the value
References EPropertyValueSetFlags::DefaultFlags, and Flags.
UE_DEPRECATED()
IPropertyHandle::UE_DEPRECATED (5. 0, "CreatePropertyNameWidget no longer supports bDisplayResetToDefault, bDisplayText or bDisplayThumbnail.") const &
Creates a name widget for this property.
Parameters
NameOverride The name override to use instead of the property name
ToolTipOverride The tooltip override to use instead of the property name
bDisplayResetToDefault Whether or not to display the reset to default button
bDisplayText Whether or not to display the text name of the property
bDisplayThumbnail Whether or not to display the thumbnail for the property (if any)
Returns
the name widget for this property
Field Documentation
bDisplayResetToDefault
const FText bool IPropertyHandle::bDisplayResetToDefault
Definition at line 642 of file PropertyHandle.h.
bDisplayText
const FText bool bool IPropertyHandle::bDisplayText = true
Definition at line 642 of file PropertyHandle.h.
bDisplayThumbnail
const FText bool bool bool IPropertyHandle::bDisplayThumbnail = true) const = 0
Definition at line 642 of file PropertyHandle.h.
ToolTipOverride
const FText& IPropertyHandle::ToolTipOverride
Definition at line 642 of file PropertyHandle.h.
Referenced by CreatePropertyNameWidget().
The documentation for this class was generated from the following file:
PropertyHandle.h