Unreal Engine 5.6 C++ API: FLandscapeTextureAtlas Class Reference
FLandscapeTextureAtlas Class Reference
#include "DistanceFieldAtlas.h"
Data Structures
struct FAllocation
struct FPendingUpload
class FSubAllocator
Public Types
enum ESubAllocType { SAT_Height , SAT_Visibility , SAT_Num }
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
FLandscapeTextureAtlas (ESubAllocType InSubAllocType)
void AddAllocation (UTexture2D *Texture, uint32 VisibilityChannel=0)
uint32 GetAllocationHandle (UTexture2D *Texture) const
FVector4f GetAllocationScaleBias (uint32 Handle) const
FRDGTexture * GetAtlasTexture (FRDGBuilder &GraphBuilder) const
uint32 GetGeneration () const
uint32 GetSizeX () const
uint32 GetSizeY () const
bool HasAtlasTexture () const
void InitializeIfNeeded ()
void RemoveAllocation (UTexture2D *Texture)
void UpdateAllocations (FRDGBuilder &GraphBuilder, ERHIFeatureLevel::Type InFeatureLevel)
void UpdateAllocations (FRHICommandListImmediate &RHICmdList, ERHIFeatureLevel::Type InFeatureLevel)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
virtual void ReleaseRHI ()
Releases the RHI resources used by this resource.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Member Functions
uint32 CalculateDownSampleLevel (uint32 SizeX, uint32 SizeY) const
Private Attributes
FSubAllocator AddrSpaceAllocator
TRefCountPtr< IPooledRenderTarget > AtlasTextureRHI
TSet< FAllocation > CurrentAllocations
TSet< FAllocation > FailedAllocations
uint32 Generation
uint32 MaxDownSampleLevel
TSet< FAllocation > PendingAllocations
TArray< UTexture2D * > PendingStreamingTextures
const ESubAllocType SubAllocType
Additional Inherited Members
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 52 of file DistanceFieldAtlas.h.
Member Enumeration Documentation
ESubAllocType
enum FLandscapeTextureAtlas::ESubAllocType
Enumerator
SAT_Height
SAT_Visibility
SAT_Num
Definition at line 55 of file DistanceFieldAtlas.h.
Constructor & Destructor Documentation
FLandscapeTextureAtlas()
FLandscapeTextureAtlas::FLandscapeTextureAtlas (ESubAllocType InSubAllocType)
Referenced by FLandscapeTextureAtlas::FPendingUpload::SetCommonShaderParameters(), and FLandscapeTextureAtlas::FPendingUpload::SetShaderParameters().
Member Function Documentation
AddAllocation()
void FLandscapeTextureAtlas::AddAllocation (UTexture2D * Texture, uint32 VisibilityChannel = 0)
References Texture.
CalculateDownSampleLevel()
uint32 FLandscapeTextureAtlas::CalculateDownSampleLevel (uint32 SizeX, uint32 SizeY) const private
GetAllocationHandle()
uint32 FLandscapeTextureAtlas::GetAllocationHandle (UTexture2D * Texture) const
References GetAllocationHandle(), and Texture.
Referenced by GetAllocationHandle().
GetAllocationScaleBias()
FVector4f FLandscapeTextureAtlas::GetAllocationScaleBias (uint32 Handle) const
References GetAllocationScaleBias(), and Handle.
Referenced by GetAllocationScaleBias().
GetAtlasTexture()
FRDGTexture * FLandscapeTextureAtlas::GetAtlasTexture (FRDGBuilder & GraphBuilder) const
GetGeneration()
uint32 FLandscapeTextureAtlas::GetGeneration () const inline
Definition at line 93 of file DistanceFieldAtlas.h.
References Generation.
GetSizeX()
uint32 FLandscapeTextureAtlas::GetSizeX () const inline
Definition at line 83 of file DistanceFieldAtlas.h.
References AddrSpaceAllocator.
GetSizeY()
uint32 FLandscapeTextureAtlas::GetSizeY () const inline
Definition at line 88 of file DistanceFieldAtlas.h.
References AddrSpaceAllocator.
HasAtlasTexture()
bool FLandscapeTextureAtlas::HasAtlasTexture () const inline
Definition at line 79 of file DistanceFieldAtlas.h.
References AtlasTextureRHI, and HasAtlasTexture().
Referenced by HasAtlasTexture().
InitializeIfNeeded()
void FLandscapeTextureAtlas::InitializeIfNeeded ()
RemoveAllocation()
void FLandscapeTextureAtlas::RemoveAllocation (UTexture2D * Texture)
References Texture.
UpdateAllocations() [1/2]
void FLandscapeTextureAtlas::UpdateAllocations (FRDGBuilder & GraphBuilder, ERHIFeatureLevel::Type InFeatureLevel)
Referenced by UpdateAllocations().
UpdateAllocations() [2/2]
void FLandscapeTextureAtlas::UpdateAllocations (FRHICommandListImmediate & RHICmdList, ERHIFeatureLevel::Type InFeatureLevel)
References UpdateAllocations().
Field Documentation
AddrSpaceAllocator
FSubAllocator FLandscapeTextureAtlas::AddrSpaceAllocator private
Definition at line 180 of file DistanceFieldAtlas.h.
Referenced by GetSizeX(), and GetSizeY().
AtlasTextureRHI
TRefCountPtr<IPooledRenderTarget> FLandscapeTextureAtlas::AtlasTextureRHI private
Definition at line 187 of file DistanceFieldAtlas.h.
Referenced by HasAtlasTexture().
CurrentAllocations
TSet<FAllocation> FLandscapeTextureAtlas::CurrentAllocations private
Definition at line 184 of file DistanceFieldAtlas.h.
FailedAllocations
TSet<FAllocation> FLandscapeTextureAtlas::FailedAllocations private
Definition at line 183 of file DistanceFieldAtlas.h.
Generation
uint32 FLandscapeTextureAtlas::Generation private
Definition at line 190 of file DistanceFieldAtlas.h.
Referenced by GetGeneration().
MaxDownSampleLevel
uint32 FLandscapeTextureAtlas::MaxDownSampleLevel private
Definition at line 189 of file DistanceFieldAtlas.h.
PendingAllocations
TSet<FAllocation> FLandscapeTextureAtlas::PendingAllocations private
Definition at line 182 of file DistanceFieldAtlas.h.
PendingStreamingTextures
TArray<UTexture2D*> FLandscapeTextureAtlas::PendingStreamingTextures private
Definition at line 185 of file DistanceFieldAtlas.h.
SubAllocType
const ESubAllocType FLandscapeTextureAtlas::SubAllocType private
Definition at line 192 of file DistanceFieldAtlas.h.
The documentation for this class was generated from the following file:
DistanceFieldAtlas.h