Unreal Engine 5.6 C++ API: FAutoConsoleVariable Class Reference
FAutoConsoleVariable Class Reference
Autoregistering float, int or string console variable.
#include "IConsoleManager.h"
Public Member Functions
FAutoConsoleVariable (const TCHAR *Name, bool DefaultValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a bool console variable.
FAutoConsoleVariable (const TCHAR *Name, bool DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a bool console variable.
FAutoConsoleVariable (const TCHAR *Name, const TCHAR *DefaultValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a string console variable.
FAutoConsoleVariable (const TCHAR *Name, const TCHAR *DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a string console variable.
FAutoConsoleVariable (const TCHAR *Name, float DefaultValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a float console variable.
FAutoConsoleVariable (const TCHAR *Name, float DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a float console variable.
FAutoConsoleVariable (const TCHAR *Name, int32 DefaultValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a int console variable.
FAutoConsoleVariable (const TCHAR *Name, int32 DefaultValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a int console variable.
FORCEINLINE IConsoleVariable & operator* ()
Dereference back to a console variable.
FORCEINLINE const IConsoleVariable & operator* () const
FORCEINLINE IConsoleVariable * operator-> ()
Dereference back to a console variable.
FORCEINLINE const IConsoleVariable * operator-> () const
Additional Inherited Members
Private Member Functions inherited from FAutoConsoleObject
virtual ~FAutoConsoleObject ()
Destructor, removes the console object.
FORCEINLINE IConsoleVariable * AsVariable ()
returns the contained console object as an IConsoleVariable
FORCEINLINE const IConsoleVariable * AsVariable () const
returns the contained console object as an IConsoleVariable
FAutoConsoleObject (IConsoleObject *InTarget)
Constructor, saves the argument for future removal from the console variable system.
Static Private Member Functions inherited from FAutoConsoleObject
static TArray< const FAutoConsoleObject * > & AccessDesktopShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessGeneralShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessMobileShaderChangeCvars ()
Detailed Description
Autoregistering float, int or string console variable.
Definition at line 1373 of file IConsoleManager.h.
Constructor & Destructor Documentation
FAutoConsoleVariable() [1/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, bool DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a bool console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1382 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariable() [2/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, int32 DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a int console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1392 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariable() [3/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, float DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a float console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1402 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariable() [4/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, const TCHAR * DefaultValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a string console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1412 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariable() [5/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, bool DefaultValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a bool console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1424 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
FAutoConsoleVariable() [6/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, int32 DefaultValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a int console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1437 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
FAutoConsoleVariable() [7/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, float DefaultValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a float console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1450 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
FAutoConsoleVariable() [8/8]
FAutoConsoleVariable::FAutoConsoleVariable (const TCHAR * Name, const TCHAR * DefaultValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a string console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1463 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
Member Function Documentation
operator*() [1/2]
FORCEINLINE IConsoleVariable & FAutoConsoleVariable::operator* () inline
Dereference back to a console variable.
Definition at line 1470 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator*() [2/2]
FORCEINLINE const IConsoleVariable & FAutoConsoleVariable::operator* () const inline
Definition at line 1474 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator->() [1/2]
FORCEINLINE IConsoleVariable * FAutoConsoleVariable::operator-> () inline
Dereference back to a console variable.
Definition at line 1479 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator->() [2/2]
FORCEINLINE const IConsoleVariable * FAutoConsoleVariable::operator-> () const inline
Definition at line 1483 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
The documentation for this class was generated from the following file:
IConsoleManager.h