Unreal Engine 5.6 C++ API: TLocalWorkQueue< TaskType > Class Template Reference
TLocalWorkQueue< TaskType > Class Template Reference
#include "LocalWorkQueue.h"
Data Structures
struct FInternalData
Public Member Functions
TLocalWorkQueue (TaskType *InitialWork, LowLevelTasks::ETaskPriority InPriority=LowLevelTasks::ETaskPriority::Count)
void AddTask (TaskType *NewWork)
void AddWorkers (uint16 NumWorkers)
void Run (TFunctionRef< void(TaskType *)> InDoWork)
Private Member Functions
UE_NONCOPYABLE (TLocalWorkQueue)
Private Attributes
TFunctionRef< void(TaskType *)> * DoWork = nullptr
TRefCountPtr< FInternalData > InternalData
LowLevelTasks::ETaskPriority Priority
Detailed Description
template<typename TaskType>
class TLocalWorkQueue< TaskType >
Definition at line 45 of file LocalWorkQueue.h.
Constructor & Destructor Documentation
TLocalWorkQueue()
template<typename TaskType> TLocalWorkQueue< TaskType >::TLocalWorkQueue (TaskType * InitialWork, LowLevelTasks::ETaskPriority InPriority = LowLevelTasks::ETaskPriority::Count) inline
Definition at line 68 of file LocalWorkQueue.h.
References AddTask(), LowLevelTasks::BackgroundHigh, LowLevelTasks::BackgroundLow, LowLevelTasks::BackgroundNormal, LowLevelTasks::Count, LowLevelTasks::Default, LowLevelTasks::FTask::GetActiveTask(), InternalData, and Priority.
Referenced by UE_NONCOPYABLE().
Member Function Documentation
AddTask()
template<typename TaskType> void TLocalWorkQueue< TaskType >::AddTask (TaskType * NewWork) inline
Definition at line 97 of file LocalWorkQueue.h.
References check, and InternalData.
Referenced by TLocalWorkQueue().
AddWorkers()
template<typename TaskType> void TLocalWorkQueue< TaskType >::AddWorkers (uint16 NumWorkers) inline
Definition at line 103 of file LocalWorkQueue.h.
References AddWorkers(), check, DoWork, LowLevelTasks::GlobalQueuePreference, InternalData, MakeShared(), Priority, TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, and verify.
Referenced by AddWorkers().
Run()
template<typename TaskType> void TLocalWorkQueue< TaskType >::Run (TFunctionRef< void(TaskType *)> InDoWork) inline
Definition at line 132 of file LocalWorkQueue.h.
References check, DoWork, InternalData, Run(), and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by Run().
UE_NONCOPYABLE()
template<typename TaskType> TLocalWorkQueue< TaskType >::UE_NONCOPYABLE (TLocalWorkQueue< TaskType >) private
References TLocalWorkQueue().
Field Documentation
DoWork
template<typename TaskType> TFunctionRef<void(TaskType*)>* TLocalWorkQueue< TaskType >::DoWork = nullptr private
Definition at line 65 of file LocalWorkQueue.h.
Referenced by AddWorkers(), and Run().
InternalData
template<typename TaskType> TRefCountPtr<FInternalData> TLocalWorkQueue< TaskType >::InternalData private
Definition at line 63 of file LocalWorkQueue.h.
Referenced by TLocalWorkQueue(), AddTask(), AddWorkers(), and Run().
Priority
template<typename TaskType> LowLevelTasks::ETaskPriority TLocalWorkQueue< TaskType >::Priority private
Definition at line 64 of file LocalWorkQueue.h.
Referenced by TLocalWorkQueue(), and AddWorkers().
The documentation for this class was generated from the following file:
LocalWorkQueue.h