Unreal Engine 5.6 C++ API: FProgressCancel Class Reference
FProgressCancel Class Reference
FProgressCancel is intended to be passed to long-running computes to do two things: 1) provide progress info back to caller 2) allow caller to cancel the computation.
#include "ProgressCancel.h"
Data Structures
struct FMessageInfo
struct FProgressData
class FProgressScope
Public Types
enum class EMessageLevel {
Internal = 0 , UserMessage = 1 , UserNotification = 2 , UserWarning = 3 ,
UserError = 4
}
Public Member Functions
void AddWarning (const FText &MessageText, EMessageLevel MessageLevel)
void AdvanceCurrentScopeProgressBy (float Amount)
void AdvanceCurrentScopeProgressToward (float TargetProgressFrac, float FractionToward)
Advance current progress a fraction of the way toward a target value For example: if progress is .5, AdvanceProgressToward(1, .5) will take a half step to 1 and set progress to .75 As with all public progress function, progress is expressed relative to the current active progress range and cannot go backward.
bool Cancelled ()
void ClearMaxMessageDepth ()
float GetCurrentScopeDistanceTo (float TargetProgressFrac)
float GetCurrentScopeProgress ()
float GetProgress () const
FText GetProgressMessage () const
void SetCurrentScopeProgressTo (float NewProgressFrac)
Note: This function will leave the current progress unchanged if the target value is less than the current progress – it will not allow the progress value to go backward.
void SetMaxMessageDepth (int32 ScopeDepth)
void SetProgressMessage (const FText &Message)
Static Public Member Functions
static GEOMETRYCORE_API FProgressScope CreateScopeTo (FProgressCancel *ProgressCancel, float ProgressTo, const FText &Message=FText())
Data Fields
TFunction< bool()> CancelF = []() { return false; }
TArray< FMessageInfo > Warnings
Private Member Functions
GEOMETRYCORE_API void EndWorkScope (const FProgressData &SavedProgressFrame)
GEOMETRYCORE_API void StartWorkScope (FProgressData &SaveProgressFrameOut, float StepSize, const FText &Message)
Private Attributes
int MaxMessageDepth = -1
FCriticalSection MessageCS
FProgressData Progress
std::atomic< float > ProgressFraction = 0
FText ProgressMessage
bool WasCancelled = false
Friends
class FProgressScope
Detailed Description
FProgressCancel is intended to be passed to long-running computes to do two things: 1) provide progress info back to caller 2) allow caller to cancel the computation.
Definition at line 186 of file ProgressCancel.h.
Member Enumeration Documentation
EMessageLevel
enum class FProgressCancel::EMessageLevel strong
Enumerator
Internal
Development message goes into development log.
UserMessage
User message should appear in user-facing log.
UserNotification
Notification message should be shown in a non-modal notification window.
UserWarning
Warning message should be shown in a non-modal notification window with panache.
UserError
Error message should be shown in a modal notification window.
Definition at line 454 of file ProgressCancel.h.
Member Function Documentation
AddWarning()
void FProgressCancel::AddWarning (const FText & MessageText, EMessageLevel MessageLevel) inline
Definition at line 477 of file ProgressCancel.h.
References FDateTime::Now(), and Warnings.
AdvanceCurrentScopeProgressBy()
void FProgressCancel::AdvanceCurrentScopeProgressBy (float Amount) inline
Parameters
Amount Amount to increase the progress fraction, as a fraction of the current active progress range
Definition at line 407 of file ProgressCancel.h.
References Progress, and ProgressFraction.
AdvanceCurrentScopeProgressToward()
void FProgressCancel::AdvanceCurrentScopeProgressToward (float TargetProgressFrac, float FractionToward) inline
Advance current progress a fraction of the way toward a target value For example: if progress is .5, AdvanceProgressToward(1, .5) will take a half step to 1 and set progress to .75 As with all public progress function, progress is expressed relative to the current active progress range and cannot go backward.
Definition at line 417 of file ProgressCancel.h.
References TMathUtil< float >::Lerp(), TMathUtil< float >::Max(), Progress, and ProgressFraction.
Cancelled()
bool FProgressCancel::Cancelled () inline
Returns
true if client would like to cancel operation
Definition at line 243 of file ProgressCancel.h.
References CancelF, and WasCancelled.
Referenced by UE::Geometry::FGeometryResult::CheckAndSetCancelled(), and UE::Geometry::FGeometryResult::SetSuccess().
ClearMaxMessageDepth()
void FProgressCancel::ClearMaxMessageDepth () inline
Definition at line 235 of file ProgressCancel.h.
References MaxMessageDepth.
CreateScopeTo()
GEOMETRYCORE_API FProgressScope FProgressCancel::CreateScopeTo (FProgressCancel * ProgressCancel, float ProgressTo, const FText & Message = FText()) static
Parameters
ProgressCancel Progress will be tracked on this. If null, the FProgressScope will do nothing.
ProgressTo Target value to increase progress to w/in this scope (as a fraction of the current outer-scope active progress range)
Message Optional message describing the work to be done
Returns
A new FProgressScope that covers work from the current progress to the target progress value (relative to the current scope)
EndWorkScope()
GEOMETRYCORE_API void FProgressCancel::EndWorkScope (const FProgressData & SavedProgressFrame) private
GetCurrentScopeDistanceTo()
float FProgressCancel::GetCurrentScopeDistanceTo (float TargetProgressFrac) inline
Parameters
TargetProgressFrac Target progress value as a fraction of the current scope's active progress range
Returns
Amount to progress in the current scope to reach the target progress value
Definition at line 436 of file ProgressCancel.h.
References GetCurrentScopeProgress().
GetCurrentScopeProgress()
float FProgressCancel::GetCurrentScopeProgress () inline
Returns
Progress as a fraction of the current scope's active progress range
Definition at line 426 of file ProgressCancel.h.
References Progress, and ProgressFraction.
Referenced by GetCurrentScopeDistanceTo().
GetProgress()
float FProgressCancel::GetProgress () const inline
Definition at line 383 of file ProgressCancel.h.
References TMathUtil< float >::Clamp(), and ProgressFraction.
GetProgressMessage()
FText FProgressCancel::GetProgressMessage () const inline
Definition at line 388 of file ProgressCancel.h.
References MessageCS, and ProgressMessage.
SetCurrentScopeProgressTo()
void FProgressCancel::SetCurrentScopeProgressTo (float NewProgressFrac) inline
Note: This function will leave the current progress unchanged if the target value is less than the current progress – it will not allow the progress value to go backward.
Parameters
ProgressFrac Value to set current progress to, as a fraction of the current active progress range
Definition at line 447 of file ProgressCancel.h.
References TMathUtil< float >::Clamp(), Progress, and ProgressFraction.
SetMaxMessageDepth()
void FProgressCancel::SetMaxMessageDepth (int32 ScopeDepth) inline
Definition at line 230 of file ProgressCancel.h.
References MaxMessageDepth.
SetProgressMessage()
void FProgressCancel::SetProgressMessage (const FText & Message) inline
Definition at line 394 of file ProgressCancel.h.
References MaxMessageDepth, MessageCS, Progress, and ProgressMessage.
StartWorkScope()
GEOMETRYCORE_API void FProgressCancel::StartWorkScope (FProgressData & SaveProgressFrameOut, float StepSize, const FText & Message) private
Friends And Related Symbol Documentation
FProgressScope
friend class FProgressScope friend
Definition at line 253 of file ProgressCancel.h.
Field Documentation
CancelF
TFunction<bool()> FProgressCancel::CancelF = []() { return false; }
Definition at line 228 of file ProgressCancel.h.
Referenced by Cancelled().
MaxMessageDepth
int FProgressCancel::MaxMessageDepth = -1 private
Definition at line 215 of file ProgressCancel.h.
Referenced by ClearMaxMessageDepth(), SetMaxMessageDepth(), and SetProgressMessage().
MessageCS
FCriticalSection FProgressCancel::MessageCS mutable private
Definition at line 221 of file ProgressCancel.h.
Referenced by GetProgressMessage(), and SetProgressMessage().
Progress
FProgressData FProgressCancel::Progress private
Definition at line 213 of file ProgressCancel.h.
Referenced by AdvanceCurrentScopeProgressBy(), AdvanceCurrentScopeProgressToward(), GetCurrentScopeProgress(), SetCurrentScopeProgressTo(), and SetProgressMessage().
ProgressFraction
std::atomic<float> FProgressCancel::ProgressFraction = 0 private
Definition at line 218 of file ProgressCancel.h.
Referenced by AdvanceCurrentScopeProgressBy(), AdvanceCurrentScopeProgressToward(), GetCurrentScopeProgress(), GetProgress(), and SetCurrentScopeProgressTo().
ProgressMessage
FText FProgressCancel::ProgressMessage private
Definition at line 214 of file ProgressCancel.h.
Referenced by GetProgressMessage(), and SetProgressMessage().
Warnings
TArray<FMessageInfo> FProgressCancel::Warnings
Definition at line 482 of file ProgressCancel.h.
Referenced by AddWarning().
WasCancelled
bool FProgressCancel::WasCancelled = false private
Definition at line 189 of file ProgressCancel.h.
Referenced by Cancelled().
The documentation for this class was generated from the following file:
ProgressCancel.h