Unreal Engine 5.6 C++ API: UELocal Namespace Reference
UELocal Namespace Reference
Functions
template<typename RealType>
UE::Math::TVector4< RealType > BlendColors (const UE::Math::TVector4< RealType > &Background, const UE::Math::TVector4< RealType > &Foreground, RealType Alpha, EVertexColorPaintBrushOpBlendMode BlendMode)
template<typename RealType>
UE::Math::TVector4< RealType > BlendColors_Lerp (const UE::Math::TVector4< RealType > &A, const UE::Math::TVector4< RealType > &B, RealType Alpha)
template<typename RealType>
UE::Math::TVector4< RealType > BlendColors_Mix (const UE::Math::TVector4< RealType > &BackColor, const UE::Math::TVector4< RealType > &ForeColor, RealType Alpha)
template<typename RealType>
UE::Math::TVector4< RealType > BlendColors_Multiply (const UE::Math::TVector4< RealType > &A, const UE::Math::TVector4< RealType > &B, RealType Alpha)
Function Documentation
BlendColors()
template<typename RealType> UE::Math::TVector4< RealType > UELocal::BlendColors (const UE::Math::TVector4< RealType > & Background, const UE::Math::TVector4< RealType > & Foreground, RealType Alpha, EVertexColorPaintBrushOpBlendMode BlendMode) inline
Definition at line 96 of file MeshVertexPaintBrushOps.h.
References Alpha, Background, BlendColors_Lerp(), BlendColors_Mix(), and BlendColors_Multiply().
Referenced by UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors().
BlendColors_Lerp()
template<typename RealType> UE::Math::TVector4< RealType > UELocal::BlendColors_Lerp (const UE::Math::TVector4< RealType > & A, const UE::Math::TVector4< RealType > & B, RealType Alpha) inline
Definition at line 66 of file MeshVertexPaintBrushOps.h.
References A, Alpha, B, and TMathUtil< RealType >::Clamp().
Referenced by UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), BlendColors(), and BlendColors_Multiply().
BlendColors_Mix()
template<typename RealType> UE::Math::TVector4< RealType > UELocal::BlendColors_Mix (const UE::Math::TVector4< RealType > & BackColor, const UE::Math::TVector4< RealType > & ForeColor, RealType Alpha) inline
Definition at line 28 of file MeshVertexPaintBrushOps.h.
References Alpha, TMathUtil< float >::Clamp(), and UE::Math::TVector4< T >::W.
Referenced by UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors(), and BlendColors().
BlendColors_Multiply()
template<typename RealType> UE::Math::TVector4< RealType > UELocal::BlendColors_Multiply (const UE::Math::TVector4< RealType > & A, const UE::Math::TVector4< RealType > & B, RealType Alpha) inline
Definition at line 81 of file MeshVertexPaintBrushOps.h.
References A, Alpha, B, and BlendColors_Lerp().
Referenced by BlendColors().