Unreal Engine 5.6 C++ API: TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > > Class Reference
TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > > Class Reference
#include "AsyncDetailViewDiff.h"
Public Member Functions
virtual ~TTreeDiffSpecification ()=default
virtual bool AreMatching (const TWeakPtr< FDetailTreeNode > &TreeNodeA, const TWeakPtr< FDetailTreeNode > &TreeNodeB) const
determine whether two nodes occupy the same space in their trees for example if you have a tree key/value pairs, AreMatching should compare the keys while AreValuesEqual should compare the values
virtual bool AreValuesEqual (const TWeakPtr< FDetailTreeNode > &TreeNodeA, const TWeakPtr< FDetailTreeNode > &TreeNodeB) const
determine whether the values stored in two nodes are equal.
virtual void GetChildren (const TWeakPtr< FDetailTreeNode > &InParent, TArray< TWeakPtr< FDetailTreeNode > > &OutChildren) const
retrieves an array of children nodes from the parent node
virtual bool ShouldInheritEqualFromChildren (const TWeakPtr< FDetailTreeNode > &TreeNodeA, const TWeakPtr< FDetailTreeNode > &TreeNodeB) const
return true if TreeNode is considered equal when all it's children are equal.
virtual bool ShouldMatchByValue (const TWeakPtr< FDetailTreeNode > &TreeNode) const
return true for nodes that match using AreValuesEqual first, and pair up by position second this is useful for arrays since we often want to keep elements with the same data paired while diffing other elements in order
UE_DEPRECATED (5.6, "Output parameters wasn't generic and is no longer used.") virtual bool AreMatching(const TWeakPtr< FDetailTreeNode > &TreeNodeA
UE_DEPRECATED (5.6, "Output parameters wasn't generic and is no longer used.") virtual bool AreValuesEqual(const TWeakPtr< FDetailTreeNode > &TreeNodeA
Data Fields
const TWeakPtr< FDetailTreeNode > TArray< FPropertySoftPath > *OutDifferingProperties const
const TWeakPtr< FDetailTreeNode > TArray< FPropertySoftPath > *const final
const TWeakPtr< FDetailTreeNode > & TreeNodeB
Detailed Description
Definition at line 8 of file AsyncDetailViewDiff.h.
Constructor & Destructor Documentation
~TTreeDiffSpecification()
virtual TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::~TTreeDiffSpecification () virtual default
Member Function Documentation
AreMatching()
virtual bool TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::AreMatching (const TWeakPtr< FDetailTreeNode > & TreeNodeA, const TWeakPtr< FDetailTreeNode > & TreeNodeB) const virtual
determine whether two nodes occupy the same space in their trees for example if you have a tree key/value pairs, AreMatching should compare the keys while AreValuesEqual should compare the values
Parameters
TreeNodeA node from the first user provided tree (guaranteed not to be null)
TreeNodeB node from the second user provided tree (guaranteed not to be null)
References AreMatching(), const, and TreeNodeB.
Referenced by AreMatching(), and UE_DEPRECATED().
AreValuesEqual()
virtual bool TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::AreValuesEqual (const TWeakPtr< FDetailTreeNode > & TreeNodeA, const TWeakPtr< FDetailTreeNode > & TreeNodeB) const virtual
determine whether the values stored in two nodes are equal.
Parameters
TreeNodeA node from the first user provided tree (guaranteed not to be null)
TreeNodeB node from the second user provided tree (guaranteed not to be null)
References TreeNodeB.
GetChildren()
virtual void TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::GetChildren (const TWeakPtr< FDetailTreeNode > & InParent, TArray< TWeakPtr< FDetailTreeNode > > & OutChildren) const virtual
retrieves an array of children nodes from the parent node
Parameters
InParent node from one of the two user provided trees (guaranteed not to be null)
[out] OutChildren to be filled with the children of parent
References const, and GetChildren().
Referenced by GetChildren().
ShouldInheritEqualFromChildren()
virtual bool TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::ShouldInheritEqualFromChildren (const TWeakPtr< FDetailTreeNode > & TreeNodeA, const TWeakPtr< FDetailTreeNode > & TreeNodeB) const virtual
return true if TreeNode is considered equal when all it's children are equal.
This avoids an unnecessary call to AreValuesEqual
References const, ShouldInheritEqualFromChildren(), and TreeNodeB.
Referenced by ShouldInheritEqualFromChildren().
ShouldMatchByValue()
virtual bool TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::ShouldMatchByValue (const TWeakPtr< FDetailTreeNode > & TreeNode) const virtual
return true for nodes that match using AreValuesEqual first, and pair up by position second this is useful for arrays since we often want to keep elements with the same data paired while diffing other elements in order
Parameters
TreeNode node from one of the two user provided trees (guaranteed not to be null)
References const, and ShouldMatchByValue().
Referenced by ShouldMatchByValue().
UE_DEPRECATED() [1/2]
TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::UE_DEPRECATED (5. 6, "Output parameters wasn't generic and is no longer used.") const &
References AreMatching(), const, final, TreeNodeB, and UE_DEPRECATED().
UE_DEPRECATED() [2/2]
TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::UE_DEPRECATED (5. 6, "Output parameters wasn't generic and is no longer used.") const &
Referenced by UE_DEPRECATED().
Field Documentation
const
const TWeakPtr< FDetailTreeNode > TArray< FPropertySoftPath > *OutDifferingProperties TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::const
Definition at line 95 of file AsyncTreeDifferences.h.
Referenced by AreMatching(), GetChildren(), ShouldInheritEqualFromChildren(), ShouldMatchByValue(), and UE_DEPRECATED().
final
const TWeakPtr< FDetailTreeNode > TArray< FPropertySoftPath > *const TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::final
Definition at line 19 of file AsyncDetailViewDiff.h.
Referenced by UE_DEPRECATED().
TreeNodeB
const TWeakPtr< FDetailTreeNode > & TTreeDiffSpecification< TWeakPtr< FDetailTreeNode > >::TreeNodeB
Definition at line 19 of file AsyncDetailViewDiff.h.
Referenced by AreMatching(), AreValuesEqual(), ShouldInheritEqualFromChildren(), and UE_DEPRECATED().
The documentation for this class was generated from the following files:
AsyncDetailViewDiff.h
AsyncTreeDifferences.h