Unreal Engine 5.6 C++ API: UVOIPTalker Class Reference
UVOIPTalker Class Reference
#include "VoiceConfig.h"
Public Member Functions
UPROPERTY () FVoiceSettings Settings
Public Member Functions inherited from UActorComponent
virtual void AddAssetUserData (UAssetUserData *InUserData) override
virtual UObject const * AdditionalStatObject () const
Give a readable name for this component, including asset name if applicable.
void AddReplicatedSubObject (UObject *SubObject, ELifetimeCondition NetCondition=COND_None)
Register a SubObject that will get replicated along with the actor component.
FORCEINLINE bool AllowReregistration () const
Check whether the component class allows reregistration during ReregisterAllComponents.
virtual bool AllowsAsyncPhysicsStateCreation () const
Returns whether this component allows having its physics state being created asynchronously (outside of the GameThread).
virtual bool AllowsAsyncPhysicsStateDestruction () const
Returns whether this component allows having its physics state being destroyed asynchronously (outside of the GameThread).
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift)
Called by owner actor on position shifting Component should update all relevant data structures to reflect new actor location.
virtual void AsyncPhysicsTickComponent (float DeltaTime, float SimTime)
Override this function to implement custom logic to be executed every physics step.
virtual void BeginDestroy () override
Called before destroying the object.
virtual void BeginPlay ()
Begins Play for the component.
virtual bool CallRemoteFunction (UFunction *Function, void *Parameters, FOutParmRec *OutParms, FFrame *Stack) override
Call the actor's function remotely.
virtual bool CanEditChange (const FProperty *InProperty) const override
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanEverAffectNavigation () const
Can this component potentially influence navigation.
virtual void CheckForErrors ()
Function that gets called from within Map_Check to allow this actor component to check itself for any potential errors and register them with map check dialog.
void ClearNeedEndOfFrameUpdate ()
If we belong to a world, clear the request to do a deferred update.
void ClearUCSModifiedProperties ()
Clears the component's UCS modified properties.
bool ComponentIsInLevel (const class ULevel *TestLevel) const
Returns true if this actor is contained by TestLevel.
bool ComponentIsInPersistentLevel (bool bIncludeLevelStreamingPersistent) const
See if this component is in the persistent level.
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const
Override to allow a component subclass to compute an hash for the purpose of HLOD generation.
void CreatePhysicsState (bool bAllowDeferral=false)
Create any physics engine information for this component.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMarkRenderStateDirty, UActorComponent &)
virtual void DestroyComponent (bool bPromoteChildren=false)
Unregister the component, remove it from its outer Actor's Components array and mark for pending kill.
void DestroyPhysicsState ()
Shut down any physics engine structure for this component.
void DestroyReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated Note it is up to the caller to delete the local object on the authority.
void DetermineUCSModifiedProperties ()
Initializes the list of properties that are modified by the UserConstructionScript.
void DoDeferredRenderUpdates_Concurrent ()
Uses the bRenderStateDirty/bRenderTransformDirty/bRenderInstancesDirty to perform any necessary work on this component.
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason)
Ends gameplay for this component.
virtual bool ForceActorNoDataLayers () const
virtual bool ForceActorNonSpatiallyLoaded () const
virtual void GetActorDescProperties (FPropertyPairsMap &PropertyPairsMap) const
Add properties to the component owner's actor desc.
virtual const TArray< UAssetUserData * > * GetAssetUserDataArray () const override
virtual UAssetUserData * GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual UObject * GetAsyncPhysicsStateObject () const override final
Returns the associated UObject for this processor.
virtual void GetComponentChildElements (TArray< FTypedElementHandle > &OutElementHandles, const bool bAllowCreate=true)
Get the logical child elements of this component, if any.
virtual bool GetComponentClassCanReplicate () const
Returns true if this type of component can ever replicate, override to disable the default behavior.
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const
Called before we throw away components during RerunConstructionScripts, to cache any data we wish to persist across that operation.
ULevel * GetComponentLevel () const
Return the ULevel that this Component is part of.
virtual TSharedPtr< SWidget > GetCustomEditorPreviewWidget ()
If this component is set up to provide a preview window in editor (see GetEditorPreviewInfo), you can use this to customize the preview (to be something other than a world viewport).
virtual TSubclassOf< class UHLODBuilder > GetCustomHLODBuilderClass () const
Return the custom HLODBuilder class that should be used to generate HLODs for components of this type.
virtual bool GetEditorPreviewInfo (float DeltaTime, FMinimalViewInfo &ViewOut)
Supplies the editor with a view specific to this component (think a view from a camera components POV, a render, etc.).
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack) override
Return the space this function should be called.
virtual TArray< UActorComponent * > GetHLODProxyComponents () const
Override to provide a custom set of components to be used in place of the current component for the HLOD generation.
FORCEINLINE bool GetIsReplicated () const
Returns whether replication is enabled or not.
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Returns properties that are replicated for the lifetime of the actor channel.
uint32 GetMarkedForEndOfFrameUpdateState () const
Tracks whether the component has been added to one of the world's end of frame update lists.
uint32 GetMarkedForPreEndOfFrameSync () const
Tracks whether the component has been added to one of the world's end of frame update lists.
ENetMode GetNetMode () const
Get the network mode (dedicated server, client, standalone, etc) for this component.
template<class T>
T * GetOwner () const
Templated version of GetOwner(), will return nullptr if cast fails.
ENetRole GetOwnerRole () const
Get the network role of the Owner, or ROLE_None if there is no owner.
virtual FString GetReadableName () const
Returns a readable name for this component, including the asset name if applicable By default this appends a space plus AdditionalStatObject()
virtual ELifetimeCondition GetReplicationCondition () const
Returns the replication condition for the component.
class FSceneInterface * GetScene () const
Returns the rendering scene associated with this component.
virtual FBox GetStreamingBounds () const
virtual FBox GetStreamingBoundsEditor () const
void GetUCSModifiedProperties (TSet< const FProperty * > &ModifiedProperties) const
Returns the list of properties that are modified by the UserConstructionScript.
int32 GetUCSSerializationIndex () const
Returns the UCS serialization index.
virtual UWorld * GetWorld () const override final
Getter for the cached world pointer, will return null if the component is not actually spawned in a level.
bool HasBeenCreated () const
Indicates that OnCreatedComponent has been called, but OnDestroyedComponent has not yet.
bool HasBeenInitialized () const
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
bool HasBegunPlay () const
Indicates that BeginPlay has been called, but EndPlay has not yet.
virtual void InitializeComponent ()
Initializes the component.
void InvalidateLightingCache ()
Invalidate lighting cache with default options.
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly)
Called when this actor component has moved, allowing it to discard statically cached lighting information.
bool IsAsyncCreatePhysicsStateRunning () const
Whether asynchronous physics state creation is running or not.
bool IsAsyncDestroyPhysicsStateRunning () const
Whether asynchronous physics state destruction is running or not.
virtual bool IsAsyncPhysicsStateCreated () const override final
Returns whether the physics state is created.
bool IsCreatedByConstructionScript () const
Returns true if instances of this component are created by either the user or simple construction script.
bool IsEditableWhenInherited () const
True if this component can be modified when it was inherited from a parent actor class.
virtual bool IsHLODRelevant () const
Override to specify that a component is relevant to the HLOD generation.
virtual bool IsNameStableForNetworking () const override
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsNavigationRelevant () const
Override to specify that a component is relevant to the navigation system.
bool IsNetMode (ENetMode Mode) const
Test whether net mode is the given mode.
bool IsNetSimulating () const
Returns true if we are replicating and this client is not authoritative.
bool IsNetStartupComponent () const
Returns true if this component was owned by a net startup actor during level load.
bool IsOwnerRunningUserConstructionScript () const
See if the owning Actor is currently running the UCS.
bool IsOwnerSelected () const
Returns whether the component's owner is selected in the editor.
bool IsPhysicsStateCreated () const
Returns true if the physics 'state' (e.g.
FORCEINLINE bool IsPreRegistered () const
See if this component is currently pre-registered.
FORCEINLINE bool IsPreRegistering () const
See if this component is currently pre-registering.
FORCEINLINE bool IsPreUnregistered () const
See if this component is currently pre-unregistered.
FORCEINLINE bool IsPreUnregistering () const
See if this component is currently pre-unregistering.
virtual bool IsReadyForOwnerToAutoDestroy () const
Overridable check for a component to indicate to its Owner that it should prevent the Actor from auto destroying when finished.
bool IsReadyForReplication () const
Indicates that ReadyForReplication has been called.
FORCEINLINE bool IsRegistered () const
See if this component is currently registered.
bool IsRenderInstancesDirty () const
Is this component's instance data in need of sending to the renderer?
bool IsRenderStateCreated () const
Returns true if the render 'state' (e.g.
bool IsRenderStateDirty () const
Is this component in need of its whole state being sent to the renderer?
bool IsRenderStateRecreating () const
Returns true if the render 'state' is being recreated for this component (see additional comments on variable above)
bool IsRenderTransformDirty () const
Is this component's transform in need of sending to the renderer?
bool IsReplicatedSubObjectRegistered (const UObject *SubObject) const
Tells if the object is registered to be replicated by this actor component.
virtual bool IsSelectedInEditor () const override
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const override
IsSupportedForNetworking means an object can be referenced over the network.
bool IsUsingRegisteredSubObjectList () const
Returns if this component is replicating subobjects via the registration list or via the virtual ReplicateSubObjects method.
void MarkForNeededEndOfFrameRecreate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkForNeededEndOfFrameUpdate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkRenderDynamicDataDirty ()
Indicate that dynamic data for this component needs to be sent at the end of the frame.
void MarkRenderInstancesDirty ()
Marks the instances as dirty - changes to instance transforms/custom data will be sent to the render thread at the end of the frame.
void MarkRenderStateDirty ()
Mark the render state as dirty - will be sent to the render thread at the end of the frame.
void MarkRenderTransformDirty ()
Marks the transform as dirty - will be sent to the render thread at the end of the frame.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
Note that the object will be modified.
virtual bool NeedsLoadForClient () const override
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForEditorGame () const override
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForServer () const override
Called during saving to determine the load flags to save with the object.
virtual void OnActorEnableCollisionChanged ()
Called on each component when the Actor's bEnableCollisionChanged flag changes.
virtual void OnActorVisibilityChanged ()
Called on each component when the Actor's visibility state changes.
virtual bool OnAsyncCreatePhysicsState (const UE::FTimeout &Timeout) override
Used to create any physics engine information for this component outside of the GameThread.
virtual void OnAsyncCreatePhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is created.
virtual bool OnAsyncDestroyPhysicsState (const UE::FTimeout &Timeout) override
Used to destroy any physics engine information for this component outside of the GameThread.
virtual void OnAsyncDestroyPhysicsStateBegin_GameThread () override
Called on the GameThread before the component's physic engine information is destroyed.
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is destroyed.
virtual void OnComponentCreated ()
Called when a component is created (not loaded).
void OnCreatedFromReplication ()
void OnDestroyedFromReplication ()
virtual void OnEndOfFrameUpdateDuringTick ()
Allows components to handle an EOF update happening mid tick.
virtual void OnPreEndOfFrameSync ()
Allows components to wait on outstanding tasks prior to sending EOF update data.
virtual void PostApplyToComponent ()
Called after ApplyToComponent has run.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
Called when a property on this object has been modified externally.
virtual void PostEditUndo () override
Called after applying a transaction to the object.
virtual void PostInitProperties () override
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostLoad () override
Do any object-specific cleanup required immediately after loading an object.
virtual void PostRename (UObject *OldOuter, const FName OldName) override
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
This is called when a property is about to be modified externally.
virtual void PreEditUndo () override
Called before applying a transaction to the object.
void PreRegisterComponentWithWorld (UWorld *InWorld)
Pre-registers a component with a specific world.
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker)
Called on the component right before replication occurs.
void PreUnregisterComponentFromWorld ()
Pre-unregisters a component from a specific world.
virtual void ReadyForReplication ()
ReadyForReplication gets called on replicated components when their owning actor is officially ready for replication.
void RecreatePhysicsState ()
Recreate the physics state right way.
void RecreateRenderState_Concurrent ()
Recreate the render state right away.
UFUNCTION()) 1 void ReceiveEndPlay(EEndPlayReason void RegisterAllComponentTickFunctions (bool bRegister)
Blueprint implementable event for when the component ends play, generally via destruction or its Actor's EndPlay.
void RegisterComponent ()
Register this component, creating any rendering/physics state.
void RegisterComponentWithWorld (UWorld *InWorld, FRegisterComponentContext *Context=nullptr)
Registers a component with a specific world, which creates any visual/physical state.
void RemoveReplicatedSubObject (UObject *SubObject)
Unregister a SubObject to stop replicating it's properties to clients.
void RemoveUCSModifiedProperties (const TArray< FProperty * > &Properties)
Removes specified properties from the list of UCS-modified properties.
virtual void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual bool Rename (const TCHAR *NewName=NULL, UObject *NewOuter=NULL, ERenameFlags Flags=REN_None) override
Rename this object to a unique name, or change its outer.
virtual bool ReplicateSubobjects (class UActorChannel *Channel, class FOutBunch *Bunch, FReplicationFlags *RepFlags)
Allows a component to replicate other subobject on the actor.
virtual bool RequiresGameThreadEndOfFrameRecreate () const
return true if this component requires end of frame recreates to happen from the game thread.
virtual bool RequiresGameThreadEndOfFrameUpdates () const
return true if this component requires end of frame updates to happen from the game thread.
virtual bool RequiresPreEndOfFrameSync () const
return true if this component needs to sync to tasks before end of frame updates are executed
void ReregisterComponent ()
Unregisters and immediately re-registers component.
virtual void Serialize (FArchive &Ar) override
Handles reading, writing, and reference collecting using FArchive.
void SetActiveFlag (const bool bNewIsActive)
Sets the value of bIsActive without causing other side effects to this instance.
void SetCanEverAffectNavigation (bool bRelevant)
Sets value of bCanEverAffectNavigation flag and update navigation octree if needed.
virtual void SetComponentTickEnabledAsync (bool bEnabled)
Spawns a task on GameThread that will call SetComponentTickEnabled.
void SetIsNetStartupComponent (const bool bInIsNetStartupComponent)
This should only be called by the engine in ULevel::InitializeNetworkActors to initialize bIsNetStartupComponent.
void SetNetAddressable ()
This signifies the component can be ID'd by name over the network.
virtual void SetPackageExternal (bool bExternal, bool bShouldDirty)
bool SetupActorComponentTickFunction (struct FTickFunction *TickFunction)
Set up a tick function for a component in the standard way.
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const
Returns whether PreRegisterComponentWithWorld should be called for this component when its Level is being added to the world.
virtual bool ShouldIncrementalPreUnregister () const
Returns whether PreUnregisterComponentFromWorld should be called for this component when its Level is being removed from the world.
void TearOffReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction)
Function called every frame on this ActorComponent.
UFUNCTION () 1 bool ComponentHasTag(FName Tag) const
See if this component contains the supplied tag.
UFUNCTION () 1 float GetComponentTickInterval() const
Returns the tick interval for this component's primary tick function, which is the frequency in seconds at which it will be executed.
UFUNCTION () 1 virtual bool IsComponentTickEnabled() const
Returns whether this component has tick enabled or not.
UFUNCTION () 1 virtual void OnRep_IsActive()
Handles replication of active state, handles ticking by default but should be overridden as needed.
UFUNCTION () 1 virtual void SetAutoActivate(bool bNewAutoActivate)
Sets whether the component should be auto activate or not.
UFUNCTION () 1 virtual void SetComponentTickEnabled(bool bEnabled)
Set this component's tick functions to be enabled or disabled.
UFUNCTION () 1 void SetComponentTickInterval(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetComponentTickIntervalAndCooldown(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetIsReplicated(bool ShouldReplicate)
Enable or disable replication.
UFUNCTION () 1 void SetTickableWhenPaused(bool bTickableWhenPaused)
Sets whether this component can tick when paused.
UFUNCTION ()) 1 virtual void Activate(bool bReset
Activates the SceneComponent, should be overridden by native child classes.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteActor(AActor *PrerequisiteActor)
Make this component tick after PrerequisiteActor.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Make this component tick after PrerequisiteComponent.
UFUNCTION ()) 1 virtual void Deactivate()
Deactivates the SceneComponent.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteActor(AActor *PrerequisiteActor)
Remove tick dependency on PrerequisiteActor.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Remove tick dependency on PrerequisiteComponent.
UFUNCTION ()) 1 virtual void SetActive(bool bNewActive
Sets whether the component is active or not.
UFUNCTION ()) 1 virtual void ToggleActive()
Toggles the active state of the component.
UFUNCTION ()) 1 void K2_DestroyComponent(UObject *Object)
Unregister and mark for pending kill a component.
UFUNCTION ()) 1 void ReceiveAsyncPhysicsTick(float DeltaSeconds
Event called every async physics tick if bAsyncPhysicsTickEnabled is true.
UFUNCTION ()) 1 void ReceiveBeginPlay()
Blueprint implementable event for when the component is beginning play, called before its owning actor's BeginPlay or when the component is dynamically created if the Actor has already BegunPlay.
UFUNCTION ()) 1 void ReceiveTick(float DeltaSeconds)
Event called every frame if tick is enabled.
UFUNCTION ()) 1 void SetTickGroup(ETickingGroup NewTickGroup)
Changes the ticking group for this component.
UFUNCTION ()) AActor *GetOwner() const
Follow the Outer chain to get the AActor that 'Owns' this component.
UFUNCTION ()) bool IsActive() const
Returns whether the component is active or not.
UFUNCTION ()) bool IsBeingDestroyed() const
Returns whether the component is in the process of being destroyed.
virtual void UninitializeComponent ()
Handle this component being Uninitialized.
void UnregisterComponent ()
Unregister this component, destroying any rendering/physics state.
virtual void UpdateComponentToWorld (EUpdateTransformFlags UpdateTransformFlags=EUpdateTransformFlags::None, ETeleportType Teleport=ETeleportType::None)
Recalculate the value of our component to world transform.
UPROPERTY () EComponentCreationMethod CreationMethod
Describes how a component instance will be created.
UPROPERTY () FActorComponentActivatedSignature OnComponentActivated
Called when the component has been activated, with parameter indicating if it was from a reset.
UPROPERTY () FActorComponentDeactivateSignature OnComponentDeactivated
Called when the component has been deactivated.
Public Member Functions inherited from UObject
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void FinishDestroy ()
Called to finish destroying the object.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
virtual FString GetDesc ()
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
Called during cooking.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const
Called when this object begins replicating to initialize the state of custom property conditions.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite ()
Save information for StaticAllocateObject in the case of overwriting an existing object.
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList)
Returns a list of sub-objects that have stable names for networking.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
virtual bool IsAsset () const
Returns true if this object is considered an asset.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const
Generic function to validate objects during changelist validations, etc.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsPostLoadThreadSafe () const
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostNetReceive ()
Called right after receiving a bunch.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostRepNotifies ()
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreNetReceive ()
Called right before receiving a bunch.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
virtual void Serialize (FStructuredArchive::FRecord Record)
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
virtual void TagSubobjects (EObjectFlags NewFlags)
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Public Member Functions inherited from IAsyncPhysicsStateProcessor
virtual void CollectBodySetupsWithPhysicsMeshesToCreate (TSet< UBodySetup * > &OutBodySetups) const
Returns body setups that needs to create their physics meshes before physics state asynchronous creation.
Protected Member Functions
UFUNCTION ()
UFUNCTION ()
Protected Member Functions inherited from UActorComponent
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context)
Used to create any rendering thread information for this component.
void DeferRemoveAsyncPhysicsTick ()
Defers the call to SetAsyncPhysicsTickEnabled(false) to the next async tick.
virtual void DestroyRenderState_Concurrent ()
Used to shut down any rendering thread structure for this component.
void HandleCanEverAffectNavigationChange (bool bForceUpdate=false)
Makes sure navigation system has up to date information regarding component's navigation relevancy and if it can affect navigation at all.
virtual bool HasValidPhysicsState () const
Used to check that DestroyPhysicsState() is working correctly.
bool NeedsInitialization () const
Convenience method for testing whether or not we are still be constructed / initialized.
virtual void OnCreatePhysicsState ()
Used to create any physics engine information for this component.
virtual void OnDestroyPhysicsState ()
Used to shut down and physics engine structure for this component.
virtual void OnPreRegister ()
Called by PreRegisterComponentWithWorld when the component is being pre-registered.
virtual void OnPreRegistered ()
Called once the component is pre-registered.
virtual void OnPreUnregister ()
Called by PreUnregisterComponentFromWorld when the component is being pre-unregistered.
virtual void OnPreUnregistered ()
Called once the component is pre-unregistered.
virtual void OnRegister ()
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
virtual void OnUnregister ()
Called when a component is unregistered.
bool OwnerNeedsInitialization () const
Convenience method for testing whether or not our owner is still being constructed / initialized.
virtual void PrecachePSOs ()
Precache all PSOs which can be used by the actor component.
virtual void RegisterComponentTickFunctions (bool bRegister)
Virtual call chain to register all tick functions.
virtual void SendRenderDynamicData_Concurrent ()
Called to send dynamic data for this component to the rendering thread.
virtual void SendRenderInstanceData_Concurrent ()
Called to send instance data for this component to the rendering thread.
virtual void SendRenderTransform_Concurrent ()
Called to send a transform update for this component to the rendering thread.
void SetAsyncPhysicsTickEnabled (bool bEnabled)
Sets bAsyncPhysicsTickEnabled which determines whether to use use the async physics tick with this component.
void SetIsReplicatedByDefault (const bool bNewReplicates)
Sets the value of bReplicates without causing other side effects to this instance.
virtual bool ShouldActivate () const
Return true if this component is in a state where it can be activated normally.
virtual bool ShouldAsyncCreatePhysicsState (UWorld *WorldContext) const
Returns whether this component should create its physics state asynchronously.
virtual bool ShouldAsyncDestroyPhysicsState () const
Returns whether this component should destroy its physics state asynchronously.
virtual bool ShouldCreatePhysicsState () const
Return true if CreatePhysicsState() should be called.
virtual bool ShouldCreateRenderState () const
Return true if CreateRenderState() should be called.
UPROPERTY () TArray< TObjectPtr< UAssetUserData > > AssetUserData
Array of user data stored with the component.
Protected Member Functions inherited from UObject
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Protected Attributes
Category
Protected Attributes inherited from UActorComponent
uint8 bAllowReregistration:1
Check whether the component class allows reregistration during ReregisterAllComponents.
uint8 bCallAsyncPhysicsStateCreatedDelegate:1
If the physics state was created while component was pre-registering, notification to GameThread is deferred next time CreatePhysicsState is called.
uint8 bPhysicsStateCreated:1
If the physics state is currently created for this component.
uint8 bRegistered:1
Indicates if this ActorComponent is currently registered with a scene.
uint8 bRenderStateCreated:1
If the render state is currently created for this component.
uint8 bRenderStateRecreating:1
Render state is being recreated for this component.
EComponentRegistrationState RegistrationState
Indicates if this ActorComponent is currently pre-registering or pre-registered with a scene.
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Private Member Functions
virtual GENERATED_BODY() public ~UVOIPTalker ()
void OnAudioComponentEnvelopeValue (const UAudioComponent *InAudioComponent, const float EnvelopeValue)
virtual void OnComponentDestroyed (bool bDestroyingHierarchy) override
Called when a component is destroyed.
virtual void OnTalkingBegin (UAudioComponent *AudioComponent)
virtual void OnTalkingEnd ()
UFUNCTION () 1 float GetVoiceLevel()
UFUNCTION () 1 void RegisterWithPlayerState(APlayerState *OwningState)
UFUNCTION () static 1 UVOIPTalker *CreateTalkerForPlayer(APlayerState *OwningState)
void UnregisterFromVoiceTalkerMap ()
Private Attributes
uint8 bIsRegistered: 1
float CachedVolumeLevel
FUniqueNetIdWrapper PlayerId
Additional Inherited Members
Public Types inherited from UObject
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Static Public Member Functions inherited from UActorComponent
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Static Public Member Functions inherited from UObject
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Data Fields inherited from UActorComponent
uint8 bAllowAnyoneToDestroyMe:1
Can this component be destroyed (via K2_DestroyComponent) by any parent.
uint8 bAllowConcurrentTick:1
Can we tick this concurrently on other threads?
uint8 bAutoRegister:1
Does this component automatically register with its owner.
UPROPERTY() uint8 bEditableWhenInherited uint8 bNavigationRelevant: 1
Whether the component is activated at creation or must be explicitly activated.
uint8 bNeverNeedsRenderUpdate:1
If true, this component never needs a render update.
bool bReset =false)
uint8 bTickInEditor:1
Should this component be ticked in the editor.
uint8 bWantsInitializeComponent:1
Whether this component can potentially influence navigation.
float SimSeconds
Data Fields inherited from UObject
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Static Public Attributes inherited from UActorComponent
static TMap< UActorComponent *, TArray< FSimpleMemberReference > > AllUCSModifiedProperties
static FTransactionallySafeRWLock AllUCSModifiedPropertiesLock
static const FString ComponentTemplateNameSuffix
Suffix used to identify template component instances.
static FOnMarkRenderStateDirty MarkRenderStateDirtyEvent
Called When render state is marked dirty.
Static Public Attributes inherited from UObject
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types inherited from UActorComponent
enum class EComponentRegistrationState {
None , PreRegistering , PreRegistered , PreUnregistering ,
PreUnregistered
}
Protected Types inherited from UObject
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Static Protected Member Functions inherited from UActorComponent
static bool CanBeHLODRelevant (const UActorComponent *ActorComponent)
Utility method used by subclasses to test basic conditions a component must fulfill to be considered HLOD relevant.
static const FName GetReplicatesPropertyName ()
Gets the property name for bReplicates.
Detailed Description
Definition at line 75 of file VoiceConfig.h.
Constructor & Destructor Documentation
~UVOIPTalker()
virtual GENERATED_BODY() public UVOIPTalker::~UVOIPTalker () private virtual
Member Function Documentation
OnAudioComponentEnvelopeValue()
void UVOIPTalker::OnAudioComponentEnvelopeValue (const UAudioComponent * InAudioComponent, const float EnvelopeValue) private
OnComponentDestroyed()
virtual void UVOIPTalker::OnComponentDestroyed (bool bDestroyingHierarchy) override private virtual
Called when a component is destroyed.
Parameters
bDestroyingHierarchy - True if the entire component hierarchy is being torn down, allows avoiding expensive operations
Reimplemented from UActorComponent.
OnTalkingBegin()
virtual void UVOIPTalker::OnTalkingBegin (UAudioComponent * AudioComponent) inline private virtual
Definition at line 100 of file VoiceConfig.h.
References OnTalkingBegin().
Referenced by OnTalkingBegin().
OnTalkingEnd()
virtual void UVOIPTalker::OnTalkingEnd () inline private virtual
Definition at line 103 of file VoiceConfig.h.
UFUNCTION() [1/5]
UVOIPTalker::UFUNCTION () protected
UFUNCTION() [2/5]
UVOIPTalker::UFUNCTION () protected
References Category, meta, and UFUNCTION().
UFUNCTION() [3/5]
UVOIPTalker::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [4/5]
UVOIPTalker::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/5]
UVOIPTalker::UFUNCTION () private
References Category.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UnregisterFromVoiceTalkerMap()
void UVOIPTalker::UnregisterFromVoiceTalkerMap () private
References UnregisterFromVoiceTalkerMap().
Referenced by UnregisterFromVoiceTalkerMap().
UPROPERTY()
UVOIPTalker::UPROPERTY ()
References Category, and UPROPERTY().
Referenced by UPROPERTY().
Field Documentation
bIsRegistered
uint8 UVOIPTalker::bIsRegistered private
Definition at line 138 of file VoiceConfig.h.
CachedVolumeLevel
float UVOIPTalker::CachedVolumeLevel private
Definition at line 135 of file VoiceConfig.h.
Category
UVOIPTalker::Category protected
Initial value:
= "Audio|Voice|Notification")
    1 void BPOnTalkingBegin(UAudioComponent* AudioComponent)
Definition at line 114 of file VoiceConfig.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UPROPERTY().
PlayerId
FUniqueNetIdWrapper UVOIPTalker::PlayerId private
Definition at line 132 of file VoiceConfig.h.
The documentation for this class was generated from the following file:
VoiceConfig.h