Unreal Engine 5.6 C++ API: TAttributesSet< ElementIDType > Class Template Reference
TAttributesSet< ElementIDType > Class Template Reference final
This is a version of the attributes set container which accesses elements by typesafe IDs.
#include "MeshAttributeArray.h"
Public Member Functions
template<typename ForEachFunc>
void ForEach (ForEachFunc Func)
template<typename ForEachFunc>
void ForEach (ForEachFunc Func) const
Call the supplied function on each attribute.
template<typename AttributeType, typename ForEachFunc>
void ForEachByType (ForEachFunc Func)
Call the supplied function on each attribute that matches the given type.
template<typename AttributeType, typename ForEachFunc>
void ForEachByType (ForEachFunc Func) const
Call the supplied function on each attribute that matches the given type.
int32 GetAttributeChannelCount (const FName AttributeName) const
Returns the number of indices for the attribute with the given name.
template<typename T>
TMeshAttributesRef< ElementIDType, typename TMeshAttributesRefType< T >::RefType > GetAttributesRef (const FName AttributeName)
template<typename T>
TMeshAttributesConstRef< ElementIDType, typename TMeshAttributesRefType< T >::ConstRefType > GetAttributesRef (const FName AttributeName) const
Get an attribute array with the given type and name.
void SetAttributeChannelCount (const FName AttributeName, const int32 NumChannels)
Sets the number of indices for the attribute with the given name.
UE_DEPRECATED (5.0, "Please use GetAttributeChannelCount() instead.") int32 GetAttributeIndexCount(const FName AttributeName) const
template<typename AttributeType>
UE_DEPRECATED (5.0, "Please use GetAttributeChannelCount() instead.") int32 GetAttributeIndexCount(const FName AttributeName) const
UE_DEPRECATED (5.0, "Please use SetAttributeChannelCount() instead.") void SetAttributeIndexCount(const FName AttributeName
template<typename AttributeType>
UE_DEPRECATED (5.0, "Please use untemplated SetAttributeChannelCount() instead.") void SetAttributeIndexCount(const FName AttributeName
Public Member Functions inherited from FAttributesSetBase
FAttributesSetBase ()
Constructor.
void AppendAttributesFrom (const FAttributesSetBase &OtherAttributesSet)
bool DoesAttributeHaveAllFlags (const FName AttributeName, EMeshAttributeFlags AttributeFlags) const
Determine whether an attribute has all of the given flags.
bool DoesAttributeHaveAnyFlags (const FName AttributeName, EMeshAttributeFlags AttributeFlags) const
Determine whether an attribute has any of the given flags.
template<typename Allocator>
void GetAttributeNames (TArray< FName, Allocator > &OutAttributeNames) const
Returns an array of all the attribute names registered.
template<typename T>
TMeshAttributesRef< int32, typename TMeshAttributesRefType< T >::RefType > GetAttributesRef (const FName AttributeName)
template<typename T>
TMeshAttributesConstRef< int32, typename TMeshAttributesRefType< T >::ConstRefType > GetAttributesRef (const FName AttributeName) const
Get an attribute array with the given type and name.
uint32 GetHash (const FName AttributeName) const
int32 GetNumElements () const
Gets the number of elements in the attribute set.
bool HasAttribute (const FName AttributeName) const
Determines whether an attribute exists with the given name.
template<typename T>
bool HasAttributeOfType (const FName AttributeName) const
Determines whether an attribute of the given type exists with the given name.
void Initialize (const int32 Count)
Initializes all attributes to have the given number of elements with the default value.
void Insert (const int32 Index)
Insert a new element at the given index.
template<typename T, typename TEnableIf<!TIsArray< T >::Value, int >::Type = 0>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterAttribute (const FName AttributeName, const int32 NumberOfChannels=1, const T &Default=T(), const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new simple attribute.
template<typename T, typename TEnableIf< TIsArray< T >::Value, int >::Type = 0>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterAttribute (const FName AttributeName, const int32 NumberOfChannels=1, const typename TMeshAttributesRegisterType< T >::RealAttributeType &Default=typename TMeshAttributesRegisterType< T >::RealAttributeType(), const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new fixed array attribute.
template<typename T>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterAttributeInternal (const FName AttributeName, const int32 NumberOfChannels=1, const typename TMeshAttributesRegisterType< T >::RealAttributeType &Default=typename TMeshAttributesRegisterType< T >::RealAttributeType(), const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new attribute name with the given type (must be a member of the AttributeTypes tuple).
template<typename T, typename TEnableIf< std::is_same_v< typename TMeshAttributesRegisterType< T >::RealAttributeType, int >, int >::Type = 0>
TMeshAttributesArray< typename TMeshAttributesRegisterType< T >::RefType > RegisterIndexAttribute (const FName AttributeName, const int32 NumberOfChannels=1, const EMeshAttributeFlags Flags=EMeshAttributeFlags::None)
Register a new unbounded array attribute.
void Remap (const TSparseArray< int32 > &IndexRemap)
Applies the given remapping to the attributes set.
void Remove (const int32 Index)
Remove an element at the given index.
void SetNumElements (const int32 Count)
Sets all attributes to have the given number of elements, preserving existing values and filling extra elements with the default value.
void UnregisterAttribute (const FName AttributeName)
Unregister an attribute with the given name.
Data Fields
const int32 NumChannels
const int32 NumIndices
Private Member Functions
void Insert (const int32 Index)
Insert a new element at the given index.
void Remove (const int32 Index)
Remove an element at the given index.
Additional Inherited Members
Protected Attributes inherited from FAttributesSetBase
TMap< FName, FAttributesSetEntry > Map
The actual container.
int32 NumElements
The number of elements in each attribute array.
Detailed Description
template<typename ElementIDType>
class TAttributesSet< ElementIDType >
This is a version of the attributes set container which accesses elements by typesafe IDs.
This prevents access of (for example) vertex instance attributes by vertex IDs.
Definition at line 1853 of file MeshAttributeArray.h.
Member Function Documentation
ForEach() [1/2]
template<typename ElementIDType> template<typename ForEachFunc> void TAttributesSet< ElementIDType >::ForEach (ForEachFunc Func)
Definition at line 2210 of file MeshAttributeArray.h.
ForEach() [2/2]
template<typename ElementIDType> template<typename ForEachFunc> void TAttributesSet< ElementIDType >::ForEach (ForEachFunc Func) const
Call the supplied function on each attribute.
The prototype should be Func(const FName AttributeName, auto AttributesConstRef);
Definition at line 2259 of file MeshAttributeArray.h.
References ForEachConstImpl::MakeJumpTable(), and FAttributesSetBase::Map.
ForEachByType() [1/2]
template<typename ElementIDType> template<typename AttributeType, typename ForEachFunc> void TAttributesSet< ElementIDType >::ForEachByType (ForEachFunc Func)
Call the supplied function on each attribute that matches the given type.
The type can be given as either a plain type T, TArrayView<T> or TArrayAttribute<T>. The prototype should be Func(const FName AttributeName, auto AttributesRef);
Definition at line 2349 of file MeshAttributeArray.h.
References FAttributesSetBase::Map.
ForEachByType() [2/2]
template<typename ElementIDType> template<typename AttributeType, typename ForEachFunc> void TAttributesSet< ElementIDType >::ForEachByType (ForEachFunc Func) const
Call the supplied function on each attribute that matches the given type.
The type can be given as either a plain type T, TArrayView<T> or TArrayAttribute<T>. The prototype should be Func(const FName AttributeName, auto AttributesConstRef);
Definition at line 2359 of file MeshAttributeArray.h.
References FAttributesSetBase::Map.
GetAttributeChannelCount()
template<typename ElementIDType> int32 TAttributesSet< ElementIDType >::GetAttributeChannelCount (const FName AttributeName) const inline
Returns the number of indices for the attribute with the given name.
Definition at line 1930 of file MeshAttributeArray.h.
References FAttributesSetBase::Map.
Referenced by UE_DEPRECATED().
GetAttributesRef() [1/2]
template<typename ElementIDType> template<typename T> TMeshAttributesRef< ElementIDType, typename TMeshAttributesRefType< T >::RefType > TAttributesSet< ElementIDType >::GetAttributesRef (const FName AttributeName) inline
Definition at line 1900 of file MeshAttributeArray.h.
References FAttributesSetBase::Map, TMeshAttributesRefType< T >::MaxExpectedExtent, and TMeshAttributesRefType< T >::MinExpectedExtent.
GetAttributesRef() [2/2]
template<typename ElementIDType> template<typename T> TMeshAttributesConstRef< ElementIDType, typename TMeshAttributesRefType< T >::ConstRefType > TAttributesSet< ElementIDType >::GetAttributesRef (const FName AttributeName) const inline
Get an attribute array with the given type and name.
The attribute type must correspond to the type passed as the template parameter.
Example of use:
TVertexAttributesConstRef<FVector> VertexPositions = VertexAttributes().GetAttributesRef<FVector>("Position"); // note: assign to value type
for(const FVertexID VertexID : GetVertices().GetElementIDs())
{
    const FVector Position = VertexPositions.Get( VertexID );
    DoSomethingWith( Position );
}
Note that the returned object is a value type which should be assigned and passed by value, not reference. It is valid for as long as this TAttributesSet object exists.
Definition at line 1876 of file MeshAttributeArray.h.
References FAttributesSetBase::Map, TMeshAttributesRefType< T >::MaxExpectedExtent, and TMeshAttributesRefType< T >::MinExpectedExtent.
Referenced by SetGroomAttribute(), SetHairStrandAttribute(), and SetHairVertexAttribute().
Insert()
template<typename ElementIDType> void FAttributesSetBase::Insert (const int32 Index) inline private
Insert a new element at the given index.
The public API version of this function takes an ID of ElementIDType instead of a typeless index.
Definition at line 1758 of file MeshAttributeArray.h.
Remove()
template<typename ElementIDType> void FAttributesSetBase::Remove (const int32 Index) inline private
Remove an element at the given index.
The public API version of this function takes an ID of ElementIDType instead of a typeless index.
Definition at line 1773 of file MeshAttributeArray.h.
SetAttributeChannelCount()
template<typename ElementIDType> void TAttributesSet< ElementIDType >::SetAttributeChannelCount (const FName AttributeName, const int32 NumChannels) inline
Sets the number of indices for the attribute with the given name.
Definition at line 1963 of file MeshAttributeArray.h.
References FAttributesSetBase::Map, and NumChannels.
UE_DEPRECATED() [1/4]
template<typename ElementIDType> TAttributesSet< ElementIDType >::UE_DEPRECATED (5. 0, "Please use GetAttributeChannelCount() instead.") const inline
Definition at line 1923 of file MeshAttributeArray.h.
References GetAttributeChannelCount().
UE_DEPRECATED() [2/4]
template<typename ElementIDType> template<typename AttributeType> TAttributesSet< ElementIDType >::UE_DEPRECATED (5. 0, "Please use GetAttributeChannelCount() instead.") const inline
Definition at line 1941 of file MeshAttributeArray.h.
References FAttributesSetBase::Map.
UE_DEPRECATED() [3/4]
template<typename ElementIDType> TAttributesSet< ElementIDType >::UE_DEPRECATED (5. 0, "Please use SetAttributeChannelCount() instead.") const
UE_DEPRECATED() [4/4]
template<typename ElementIDType> template<typename AttributeType> TAttributesSet< ElementIDType >::UE_DEPRECATED (5. 0, "Please use untemplated SetAttributeChannelCount() instead.") const
Field Documentation
NumChannels
template<typename ElementIDType> const int32 TAttributesSet< ElementIDType >::NumChannels
Initial value:
{
        SetAttributeChannelCount(AttributeName, NumChannels)
Definition at line 1957 of file MeshAttributeArray.h.
Referenced by SetAttributeChannelCount().
NumIndices
template<typename ElementIDType> const int32 TAttributesSet< ElementIDType >::NumIndices
Definition at line 1973 of file MeshAttributeArray.h.
The documentation for this class was generated from the following file:
MeshAttributeArray.h