Unreal Engine 5.6 C++ API: FBookMarkTypeActions Class Reference
FBookMarkTypeActions Class Reference
#include "BookMarkTypeActions.h"
Public Member Functions
virtual TSubclassOf< class UBookmarkBase > GetBookmarkClass () override
Gets the class of bookmarks with which these actions can be used.
virtual void InitFromViewport (UBookmarkBase *InBookmark, FEditorViewportClient &InViewportClient) override
Called to initialize the given bookmark from the given Viewport.
virtual void JumpToBookmark (UBookmarkBase *InBookmark, const TSharedPtr< struct FBookmarkBaseJumpToSettings > InSettings, FEditorViewportClient &InViewportClient) override
Called to jump to the given bookmark.
Public Member Functions inherited from IBookmarkTypeActions
virtual ~IBookmarkTypeActions ()
Protected Member Functions
void ApplyBookmarkToViewportClient (UBookMark *InBookmark, FEditorViewportClient *InViewportClient)
Detailed Description
Definition at line 14 of file BookMarkTypeActions.h.
Member Function Documentation
ApplyBookmarkToViewportClient()
void FBookMarkTypeActions::ApplyBookmarkToViewportClient (UBookMark * InBookmark, FEditorViewportClient * InViewportClient) inline protected
Definition at line 68 of file BookMarkTypeActions.h.
References FEditorViewportClient::Invalidate(), FEditorViewportClient::IsOrtho(), FEditorDelegates::OnEditorCameraMoved, FEditorViewportClient::SetViewLocation(), FEditorViewportClient::SetViewRotation(), FEditorViewportClient::ViewIndex, and FEditorViewportClient::ViewportType.
Referenced by FBookmarkSingleViewportActions::JumpToBookmark(), and JumpToBookmark().
GetBookmarkClass()
virtual TSubclassOf< class UBookmarkBase > FBookMarkTypeActions::GetBookmarkClass () inline override virtual
Gets the class of bookmarks with which these actions can be used.
Must match exactly with the desired bookmark class.
Implements IBookmarkTypeActions.
Definition at line 18 of file BookMarkTypeActions.h.
InitFromViewport()
virtual void FBookMarkTypeActions::InitFromViewport (UBookmarkBase * InBookmark, FEditorViewportClient & InViewportClient) inline override virtual
Called to initialize the given bookmark from the given Viewport.
Parameters
InBookmark The bookmark to initialize.
InViewportClient The client that can be used for initialization.
Implements IBookmarkTypeActions.
Definition at line 23 of file BookMarkTypeActions.h.
References Cast(), FEditorViewportClient::GetViewLocation(), FEditorViewportClient::GetViewRotation(), FEditorViewportClient::GetWorld(), FEditorViewportClient::IsOrtho(), Rotation, and UE::Math::TVector< T >::Rotation().
JumpToBookmark()
virtual void FBookMarkTypeActions::JumpToBookmark (UBookmarkBase * Bookmark, const TSharedPtr< struct FBookmarkBaseJumpToSettings > InSettings, FEditorViewportClient & InViewportClient) inline override virtual
Called to jump to the given bookmark.
Parameters
InBookmark The bookmark that should be jumped to / activated.
InSettings Optional settings, dependent on the bookmark class.
InViewportClient The viewport that will be updated.
Implements IBookmarkTypeActions.
Reimplemented in FBookmarkSingleViewportActions.
Definition at line 54 of file BookMarkTypeActions.h.
References ApplyBookmarkToViewportClient(), Cast(), and GEditor.
The documentation for this class was generated from the following file:
BookMarkTypeActions.h