Unreal Engine 5.6 C++ API: Metasound::VariableNames Namespace Reference
Metasound::VariableNames Namespace Reference
Functions
template<typename DataType>
const FNodeClassName & GetVariableAccessorNodeClassName ()
Class name for variable accessor node.
METASOUNDGRAPHCORE_API FNodeClassName GetVariableAccessorNodeClassName (const FName &InDataTypeName)
Class name for variable accessor node.
template<typename DataType>
const FNodeClassName & GetVariableDeferredAccessorNodeClassName ()
Class name for variable deferred accessor node.
METASOUNDGRAPHCORE_API FNodeClassName GetVariableDeferredAccessorNodeClassName (const FName &InDataTypeName)
Class name for variable deferred accessor node.
template<typename DataType>
const FNodeClassName & GetVariableMutatorNodeClassName ()
Class name for variable mutator node.
METASOUNDGRAPHCORE_API FNodeClassName GetVariableMutatorNodeClassName (const FName &InDataTypeName)
Class name for variable mutator node.
template<typename DataType>
const FNodeClassName & GetVariableNodeClassName ()
Class name for variable node.
METASOUNDGRAPHCORE_API FNodeClassName GetVariableNodeClassName (const FName &InDataTypeName)
Class name for variable node.
Variables
static const FText InputDataDisplayName = LOCTEXT("InputData" "DisplayName", "Value")
static const FDataVertexMetadata InputDataMetadata
static const FLazyName InputDataName = TEXT("Value")
static const FText InputDataTooltip = LOCTEXT("InputData" "Tooltip", "Value")
static const FText InputVariableDisplayName = LOCTEXT("InputVariable" "DisplayName", "Variable")
static const FDataVertexMetadata InputVariableMetadata
static const FLazyName InputVariableName = TEXT("Variable")
static const FText InputVariableTooltip = LOCTEXT("InputVariable" "Tooltip", "Variable")
static const FText OutputDataDisplayName = LOCTEXT("OutputData" "DisplayName", "Value")
static const FDataVertexMetadata OutputDataMetadata
static const FLazyName OutputDataName = TEXT("Value")
static const FText OutputDataTooltip = LOCTEXT("OutputData" "Tooltip", "Value")
static const FText OutputVariableDisplayName = LOCTEXT("OutputVariable" "DisplayName", "Variable")
static const FDataVertexMetadata OutputVariableMetadata
static const FLazyName OutputVariableName = TEXT("Variable")
static const FText OutputVariableTooltip = LOCTEXT("OutputVariable" "Tooltip", "Variable")
Function Documentation
GetVariableAccessorNodeClassName() [1/2]
template<typename DataType> const FNodeClassName & Metasound::VariableNames::GetVariableAccessorNodeClassName ()
Class name for variable accessor node.
Definition at line 81 of file MetasoundVariableNodes.h.
References Metasound::GetMetasoundDataTypeName(), and GetVariableAccessorNodeClassName().
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::GetNodeInfo(), and GetVariableAccessorNodeClassName().
GetVariableAccessorNodeClassName() [2/2]
METASOUNDGRAPHCORE_API FNodeClassName Metasound::VariableNames::GetVariableAccessorNodeClassName (const FName & InDataTypeName)
Class name for variable accessor node.
GetVariableDeferredAccessorNodeClassName() [1/2]
template<typename DataType> const FNodeClassName & Metasound::VariableNames::GetVariableDeferredAccessorNodeClassName ()
Class name for variable deferred accessor node.
Definition at line 89 of file MetasoundVariableNodes.h.
References Metasound::GetMetasoundDataTypeName(), and GetVariableDeferredAccessorNodeClassName().
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::GetNodeInfo(), and GetVariableDeferredAccessorNodeClassName().
GetVariableDeferredAccessorNodeClassName() [2/2]
METASOUNDGRAPHCORE_API FNodeClassName Metasound::VariableNames::GetVariableDeferredAccessorNodeClassName (const FName & InDataTypeName)
Class name for variable deferred accessor node.
GetVariableMutatorNodeClassName() [1/2]
template<typename DataType> const FNodeClassName & Metasound::VariableNames::GetVariableMutatorNodeClassName ()
Class name for variable mutator node.
Definition at line 73 of file MetasoundVariableNodes.h.
References Metasound::GetMetasoundDataTypeName(), and GetVariableMutatorNodeClassName().
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetNodeInfo(), and GetVariableMutatorNodeClassName().
GetVariableMutatorNodeClassName() [2/2]
METASOUNDGRAPHCORE_API FNodeClassName Metasound::VariableNames::GetVariableMutatorNodeClassName (const FName & InDataTypeName)
Class name for variable mutator node.
GetVariableNodeClassName() [1/2]
template<typename DataType> const FNodeClassName & Metasound::VariableNames::GetVariableNodeClassName ()
Class name for variable node.
Definition at line 65 of file MetasoundVariableNodes.h.
References Metasound::GetMetasoundDataTypeName(), and GetVariableNodeClassName().
Referenced by Metasound::TVariableNode< DataType >::CreateNodeClassMetadata(), and GetVariableNodeClassName().
GetVariableNodeClassName() [2/2]
METASOUNDGRAPHCORE_API FNodeClassName Metasound::VariableNames::GetVariableNodeClassName (const FName & InDataTypeName)
Class name for variable node.
Variable Documentation
InputDataDisplayName
const FText Metasound::VariableNames::InputDataDisplayName = LOCTEXT("InputData" "DisplayName", "Value") static
Definition at line 22 of file MetasoundVariableNodes.h.
InputDataMetadata
const FDataVertexMetadata Metasound::VariableNames::InputDataMetadata static
Initial value:
{
              FText::GetEmpty()
            ,  InputDataDisplayName
        }
Definition at line 27 of file MetasoundVariableNodes.h.
InputDataName
const FLazyName Metasound::VariableNames::InputDataName = TEXT("Value") static
Definition at line 22 of file MetasoundVariableNodes.h.
InputDataTooltip
const FText Metasound::VariableNames::InputDataTooltip = LOCTEXT("InputData" "Tooltip", "Value") static
Definition at line 22 of file MetasoundVariableNodes.h.
InputVariableDisplayName
const FText Metasound::VariableNames::InputVariableDisplayName = LOCTEXT("InputVariable" "DisplayName", "Variable") static
Definition at line 24 of file MetasoundVariableNodes.h.
InputVariableMetadata
const FDataVertexMetadata Metasound::VariableNames::InputVariableMetadata static
Initial value:
{
              FText::GetEmpty()
            ,  InputVariableDisplayName
        }
Definition at line 39 of file MetasoundVariableNodes.h.
InputVariableName
const FLazyName Metasound::VariableNames::InputVariableName = TEXT("Variable") static
Definition at line 24 of file MetasoundVariableNodes.h.
InputVariableTooltip
const FText Metasound::VariableNames::InputVariableTooltip = LOCTEXT("InputVariable" "Tooltip", "Variable") static
Definition at line 24 of file MetasoundVariableNodes.h.
OutputDataDisplayName
const FText Metasound::VariableNames::OutputDataDisplayName = LOCTEXT("OutputData" "DisplayName", "Value") static
Definition at line 23 of file MetasoundVariableNodes.h.
OutputDataMetadata
const FDataVertexMetadata Metasound::VariableNames::OutputDataMetadata static
Initial value:
{
              FText::GetEmpty()
            ,  OutputDataDisplayName
        }
Definition at line 33 of file MetasoundVariableNodes.h.
OutputDataName
const FLazyName Metasound::VariableNames::OutputDataName = TEXT("Value") static
Definition at line 23 of file MetasoundVariableNodes.h.
OutputDataTooltip
const FText Metasound::VariableNames::OutputDataTooltip = LOCTEXT("OutputData" "Tooltip", "Value") static
Definition at line 23 of file MetasoundVariableNodes.h.
OutputVariableDisplayName
const FText Metasound::VariableNames::OutputVariableDisplayName = LOCTEXT("OutputVariable" "DisplayName", "Variable") static
Definition at line 25 of file MetasoundVariableNodes.h.
OutputVariableMetadata
const FDataVertexMetadata Metasound::VariableNames::OutputVariableMetadata static
Initial value:
{
              FText::GetEmpty()
            ,  OutputVariableDisplayName
        }
Definition at line 45 of file MetasoundVariableNodes.h.
OutputVariableName
const FLazyName Metasound::VariableNames::OutputVariableName = TEXT("Variable") static
Definition at line 25 of file MetasoundVariableNodes.h.
OutputVariableTooltip
const FText Metasound::VariableNames::OutputVariableTooltip = LOCTEXT("OutputVariable" "Tooltip", "Variable") static
Definition at line 25 of file MetasoundVariableNodes.h.