Unreal Engine 5.6 C++ API: Ticker.h File Reference
Ticker.h File Reference
#include "Containers/Array.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/MpscQueue.h"
#include "CoreTypes.h"
#include "Delegates/Delegate.h"
#include "Templates/Function.h"
#include "Templates/SharedPointer.h"
#include <atomic>
Data Structures
class FTSTicker
Thread-safe ticker class.
struct FTSTicker::FElement
Internal structure to store a ticker delegate and related data.
class FTSTickerObjectBase
Base class for thread-safe ticker objects.
Functions
DECLARE_DELEGATE_RetVal_OneParam (bool, FTickerDelegate, float)
Ticker delegates return true to automatically reschedule at the same delay or false for one-shot.
template<typename FunctorType>
void ExecuteOnGameThread (const TCHAR *DebugName, FunctorType &&Functor)
Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
DECLARE_DELEGATE_RetVal_OneParam (bool , FTickerDelegate , float)
Ticker delegates return true to automatically reschedule at the same delay or false for one-shot.
You will not get more than one fire per "frame", which is just a FTSTicker::Tick call. DeltaTime argument is the time since the last game frame, not since the last tick the delegate received.
ExecuteOnGameThread()
template<typename FunctorType> void ExecuteOnGameThread (const TCHAR * DebugName, FunctorType && Functor)
Definition at line 168 of file Ticker.h.
References FTSTicker::AddTicker(), FTSTicker::GetCoreTicker(), and MoveTemp().