Unreal Engine 5.6 C++ API: UE::AnimNext::TTransformArrayAoS< AllocatorType > Struct Template Reference
UE::AnimNext::TTransformArrayAoS< AllocatorType > Struct Template Reference
#include "TransformArray.h"
Public Member Functions
TTransformArrayAoS ()=default
TTransformArrayAoS (const int NumTransforms)
TTransformArrayAoS (const TTransformArrayAoS &Other)=default
TTransformArrayAoS (TTransformArrayAoS &&Other)=default
~TTransformArrayAoS ()=default
void Blend (const TTransformArrayAoS &AtomArray1, const TTransformArrayAoS &AtomArray2, float BlendWeight)
Set this transform array to the weighted blend of the supplied two transforms.
bool ContainsNaN () const
void CopyTransforms (const TTransformArrayAoS &Other, int32 Index, int32 NumTransforms)
void DebugFill ()
FTransformArrayAoSConstView GetConstView () const
TArray< FTransform > & GetTransforms ()
const TArray< FTransform > & GetTransforms () const
FTransformArrayAoSView GetView ()
bool IsValid () const
int32 Num () const
TTransformArrayAoS & operator= (const TTransformArrayAoS &Other)=default
TTransformArrayAoS & operator= (TTransformArrayAoS &&Other)=default
FTransform & operator[] (int32 Index)
const FTransform & operator[] (int32 Index) const
void Reset (int NumTransforms)
void SetIdentity (bool bAdditiveIdentity=false)
void SetNum (int32 NumTransforms, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void SetNumUninitialized (int32 NumTransforms, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum") FORCEINLINE void SetNum(int32 NumTransforms
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized") FORCEINLINE void SetNumUninitialized(int32 NumTransforms
Data Fields
bool bAllowShrinking
TArray< FTransform, AllocatorType > Transforms
Private Member Functions
FORCEINLINE void DiagnosticCheck_IsValid () const
FORCEINLINE void DiagnosticCheckNaN_All () const
Static Private Member Functions
static FORCEINLINE void DiagnosticCheckNaN_Rotate (const FQuat &Rotation)
static FORCEINLINE void DiagnosticCheckNaN_Scale3D (const FVector &Scale3D)
static FORCEINLINE void DiagnosticCheckNaN_Translate (const FVector &Translation)
Detailed Description
template<typename AllocatorType>
struct UE::AnimNext::TTransformArrayAoS< AllocatorType >
Definition at line 19 of file TransformArray.h.
Constructor & Destructor Documentation
TTransformArrayAoS() [1/4]
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::TTransformArrayAoS () default
TTransformArrayAoS() [2/4]
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::TTransformArrayAoS (const int NumTransforms) inline explicit
Definition at line 27 of file TransformArray.h.
~TTransformArrayAoS()
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::~TTransformArrayAoS () default
TTransformArrayAoS() [3/4]
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::TTransformArrayAoS (const TTransformArrayAoS< AllocatorType > & Other) default
TTransformArrayAoS() [4/4]
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::TTransformArrayAoS (TTransformArrayAoS< AllocatorType > && Other) default
Member Function Documentation
Blend()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::Blend (const TTransformArrayAoS< AllocatorType > & AtomArray1, const TTransformArrayAoS< AllocatorType > & AtomArray2, float BlendWeight) inline
Set this transform array to the weighted blend of the supplied two transforms.
Definition at line 111 of file TransformArray.h.
ContainsNaN()
template<typename AllocatorType> bool UE::AnimNext::TTransformArrayAoS< AllocatorType >::ContainsNaN () const inline
Definition at line 168 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::IsValid().
CopyTransforms()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::CopyTransforms (const TTransformArrayAoS< AllocatorType > & Other, int32 Index, int32 NumTransforms) inline
Definition at line 68 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::Blend().
DebugFill()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::DebugFill () inline
Definition at line 208 of file TransformArray.h.
DiagnosticCheck_IsValid()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArrayAoS< AllocatorType >::DiagnosticCheck_IsValid () const inline private
Definition at line 263 of file TransformArray.h.
DiagnosticCheckNaN_All()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArrayAoS< AllocatorType >::DiagnosticCheckNaN_All () const inline private
Definition at line 262 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::Blend().
DiagnosticCheckNaN_Rotate()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArrayAoS< AllocatorType >::DiagnosticCheckNaN_Rotate (const FQuat & Rotation) inline static private
Definition at line 260 of file TransformArray.h.
DiagnosticCheckNaN_Scale3D()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArrayAoS< AllocatorType >::DiagnosticCheckNaN_Scale3D (const FVector & Scale3D) inline static private
Definition at line 261 of file TransformArray.h.
DiagnosticCheckNaN_Translate()
template<typename AllocatorType> FORCEINLINE void UE::AnimNext::TTransformArrayAoS< AllocatorType >::DiagnosticCheckNaN_Translate (const FVector & Translation) inline static private
Definition at line 259 of file TransformArray.h.
GetConstView()
template<typename AllocatorType> FTransformArrayAoSConstView UE::AnimNext::TTransformArrayAoS< AllocatorType >::GetConstView () const inline
Definition at line 105 of file TransformArray.h.
GetTransforms() [1/2]
template<typename AllocatorType> TArray< FTransform > & UE::AnimNext::TTransformArrayAoS< AllocatorType >::GetTransforms () inline
Definition at line 81 of file TransformArray.h.
GetTransforms() [2/2]
template<typename AllocatorType> const TArray< FTransform > & UE::AnimNext::TTransformArrayAoS< AllocatorType >::GetTransforms () const inline
Definition at line 85 of file TransformArray.h.
GetView()
template<typename AllocatorType> FTransformArrayAoSView UE::AnimNext::TTransformArrayAoS< AllocatorType >::GetView () inline
Definition at line 100 of file TransformArray.h.
IsValid()
template<typename AllocatorType> bool UE::AnimNext::TTransformArrayAoS< AllocatorType >::IsValid () const inline
Definition at line 189 of file TransformArray.h.
Num()
template<typename AllocatorType> int32 UE::AnimNext::TTransformArrayAoS< AllocatorType >::Num () const inline
Definition at line 76 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::Blend(), and UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::CopyTransforms().
operator=() [1/2]
template<typename AllocatorType> TTransformArrayAoS & UE::AnimNext::TTransformArrayAoS< AllocatorType >::operator= (const TTransformArrayAoS< AllocatorType > & Other) default
operator=() [2/2]
template<typename AllocatorType> TTransformArrayAoS & UE::AnimNext::TTransformArrayAoS< AllocatorType >::operator= (TTransformArrayAoS< AllocatorType > && Other) default
operator[]() [1/2]
template<typename AllocatorType> FTransform & UE::AnimNext::TTransformArrayAoS< AllocatorType >::operator[] (int32 Index) inline
Definition at line 90 of file TransformArray.h.
operator[]() [2/2]
template<typename AllocatorType> const FTransform & UE::AnimNext::TTransformArrayAoS< AllocatorType >::operator[] (int32 Index) const inline
Definition at line 95 of file TransformArray.h.
Reset()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::Reset (int NumTransforms) inline
Definition at line 38 of file TransformArray.h.
SetIdentity()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::SetIdentity (bool bAdditiveIdentity = false) inline
Definition at line 63 of file TransformArray.h.
SetNum()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::SetNum (int32 NumTransforms, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 43 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::TTransformArrayAoS().
SetNumUninitialized()
template<typename AllocatorType> void UE::AnimNext::TTransformArrayAoS< AllocatorType >::SetNumUninitialized (int32 NumTransforms, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 53 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::UE_ALLOWSHRINKING_BOOL_DEPRECATED().
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [1/2]
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum")
UE_ALLOWSHRINKING_BOOL_DEPRECATED() [2/2]
template<typename AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized")
Field Documentation
bAllowShrinking
template<typename AllocatorType> bool UE::AnimNext::TTransformArrayAoS< AllocatorType >::bAllowShrinking
Initial value:
{
        SetNum(NumTransforms, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 48 of file TransformArray.h.
Transforms
template<typename AllocatorType> TArray<FTransform, AllocatorType> UE::AnimNext::TTransformArrayAoS< AllocatorType >::Transforms
Definition at line 21 of file TransformArray.h.
Referenced by UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::Blend().
The documentation for this struct was generated from the following file:
TransformArray.h