Unreal Engine 5.6 C++ API: TStringBuilderBase< CharType > Class Template Reference
TStringBuilderBase< CharType > Class Template Reference
String Builder.
#include "StringBuilder.h"
Public Types
using BuilderType = TStringBuilderBase<ElementType>
The string builder base type to be used by append operators and function output parameters.
using ElementType = CharType
The character type that this builder operates on.
using ViewType = TStringView<ElementType>
The string view type that this builder is compatible with.
Public Member Functions
TStringBuilderBase ()=default
TStringBuilderBase (CharType *BufferPointer, int32 BufferCapacity)
TStringBuilderBase (const TStringBuilderBase &)=delete
TStringBuilderBase (TStringBuilderBase &&)=delete
~TStringBuilderBase ()
template<typename AppendedCharType>
auto Add (AppendedCharType Char) -> decltype(AppendChar(Char),(void) 0)
Prefer AppendChar.
int32 AddUninitialized (int32 InCount)
Adds a given number of uninitialized characters into the string builder.
template<typename CharRangeType>
auto Append (CharRangeType &&Range) -> decltype(Append(MakeStringView(Forward< CharRangeType >(Range)).GetData(), int32(0)))
template<typename OtherCharType, std::enable_if_t< TIsCharType< OtherCharType >::Value > * = nullptr>
BuilderType & Append (const OtherCharType *const String, const int32 Length)
template<typename AppendedCharType, std::enable_if_t< TIsCharType< AppendedCharType >::Value > * = nullptr>
BuilderType & AppendChar (AppendedCharType Char)
template<typename FmtType, typename... Types UE_REQUIRES>
BuilderType & Appendf (const FmtType &Fmt, Types... Args)
Appends to the string builder similarly to how classic sprintf works.
BuilderType & AppendV (const CharType *Fmt, va_list Args)
Appends to the string builder similarly to how classic vsprintf works.
SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container.
const CharType * GetData () const UE_LIFETIMEBOUND
CharType * GetData () UE_LIFETIMEBOUND
Returns a pointer to Len() code units that are not necessarily null-terminated.
void InsertAt (int32 Pos, ViewType Str)
Insert substring at given position.
template<typename RangeType, typename DelimiterType, std::enable_if_t< TCanAppendRange_V< RangeType && > &&TCanAppend_V< DelimiterType && > > * = nullptr>
BuilderType & Join (RangeType &&InRange, DelimiterType &&InDelimiter)
Append every element of the range to the builder, separating the elements by the delimiter.
template<typename RangeType, typename DelimiterType, typename QuoteType, std::enable_if_t< TCanAppendRange_V< RangeType > &&TCanAppend_V< DelimiterType && > &&TCanAppend_V< QuoteType && > > * = nullptr>
BuilderType & JoinQuoted (RangeType &&InRange, DelimiterType &&InDelimiter, QuoteType &&InQuote)
Append every element of the range to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
CharType LastChar () const
Returns the last character, technically the last code unit.
int32 Len () const
const CharType * operator* () UE_LIFETIMEBOUND
Returns a pointer to a null-terminated string that is valid until the builder is mutated.
TStringBuilderBase & operator= (const CharType *Str)
TStringBuilderBase & operator= (const TStringBuilderBase &)=delete
TStringBuilderBase & operator= (TStringBuilderBase &&)=delete
TStringBuilderBase & operator= (ViewType Str)
void Prepend (ViewType Str)
Insert prefix.
void RemoveAt (int32 Pos, int32 RemoveLen)
Remove characters at given position.
void RemoveSuffix (int32 InCount)
Modifies the string builder to remove the given number of characters from the end.
void ReplaceAt (int32 Pos, int32 RemoveLen, ViewType Str)
Replace characters at given position and length with substring.
void Reserve (int32 InNewCapacity)
Reserves memory such that the string builder can contain at least the given number of characters.
void Reset ()
Empties the string builder, but doesn't change memory allocation.
const CharType * ToString () UE_LIFETIMEBOUND
Prefer operator*() for a pointer to a null-terminated string.
ViewType ToView () const UE_LIFETIMEBOUND
Returns a view of the string that is valid until the builder is mutated.
UE_DEPRECATED (5.6, "Call the non-const operator*().") inline const CharType *operator*() const UE_LIFETIMEBOUND
Returns a pointer to a null-terminated string that is valid until the builder is mutated.
UE_DEPRECATED (5.6, "Call the non-const operator*().") inline const CharType *ToString() const UE_LIFETIMEBOUND
Prefer operator*() for a pointer to a null-terminated string.
Static Public Attributes
template<typename AppendType>
static constexpr bool TCanAppend_V = std::is_same_v<BuilderType&, decltype(DeclVal<BuilderType&>() << DeclVal<AppendType>())>
Whether the given type can be appended to this builder using the append operator.
template<typename RangeType>
static constexpr bool TCanAppendRange_V = TIsContiguousContainer<RangeType>::Value && TCanAppend_V<decltype(*::GetData(DeclVal<RangeType>()))>
Whether the given range type can have its elements appended to the builder using the append operator.
Protected Member Functions
void * AllocBuffer (SIZE_T CharCount)
void EnsureAdditionalCapacity (int32 RequiredAdditionalCapacity)
void EnsureNulTerminated () const
void Extend (SIZE_T ExtraCapacity)
void FreeBuffer (void *Buffer, SIZE_T CharCount)
void Initialize (CharType *InBase, int32 InCapacity)
Protected Attributes
CharType * Base = EmptyBuffer
bool bIsDynamic = false
CharType * CurPos = Base
CharType * End = Base + 1
Static Protected Attributes
static CharType EmptyBuffer [1] {}
Private Types
template<typename SrcEncoding>
using TIsCharEncodingCompatibleWithCharType = TIsCharEncodingCompatibleWith<SrcEncoding, CharType>
Static Private Member Functions
static BuilderType &VARARGS AppendfImpl (BuilderType &Self, const CharType *Fmt,...)
Friends
const CharType * begin (const TStringBuilderBase &Builder)
CharType * begin (TStringBuilderBase &Builder)
const CharType * end (const TStringBuilderBase &Builder)
CharType * end (TStringBuilderBase &Builder)
Detailed Description
template<typename CharType>
class TStringBuilderBase< CharType >
String Builder.
This class helps with the common task of constructing new strings.
It does this by allocating buffer space which is used to hold the constructed string. The intent is that the builder is allocated on the stack as a function local variable to avoid heap allocations.
The buffer is always contiguous and the class is not intended to be used to construct extremely large strings.
This is not intended to be used as a mechanism for holding on to strings for a long time. The use case is explicitly to aid in constructing strings on the stack and subsequently passing the string into a function call or a more permanent string storage mechanism like FString et al.
The amount of buffer space to allocate is specified via a template parameter and if the constructed string should overflow this initial buffer, a new buffer will be allocated using regular dynamic memory allocations.
Overflow allocation should be the exceptional case however – always try to size the buffer so that it can hold the vast majority of strings you expect to construct.
Be mindful that stack is a limited resource, so if you are writing a highly recursive function you may want to use some other mechanism to build your strings.
Definition at line 59 of file StringBuilder.h.
Member Typedef Documentation
BuilderType
template<typename CharType> using TStringBuilderBase< CharType >::BuilderType = TStringBuilderBase<ElementType>
The string builder base type to be used by append operators and function output parameters.
Definition at line 65 of file StringBuilder.h.
ElementType
template<typename CharType> using TStringBuilderBase< CharType >::ElementType = CharType
The character type that this builder operates on.
Definition at line 63 of file StringBuilder.h.
TIsCharEncodingCompatibleWithCharType
template<typename CharType> template<typename SrcEncoding> using TStringBuilderBase< CharType >::TIsCharEncodingCompatibleWithCharType = TIsCharEncodingCompatibleWith<SrcEncoding, CharType> private
Definition at line 389 of file StringBuilder.h.
ViewType
template<typename CharType> using TStringBuilderBase< CharType >::ViewType = TStringView<ElementType>
The string view type that this builder is compatible with.
Definition at line 67 of file StringBuilder.h.
Constructor & Destructor Documentation
TStringBuilderBase() [1/4]
template<typename CharType> TStringBuilderBase< CharType >::TStringBuilderBase () default
~TStringBuilderBase()
template<typename CharType> TStringBuilderBase< CharType >::~TStringBuilderBase ()
TStringBuilderBase() [2/4]
template<typename CharType> TStringBuilderBase< CharType >::TStringBuilderBase (const TStringBuilderBase< CharType > &) delete
TStringBuilderBase() [3/4]
template<typename CharType> TStringBuilderBase< CharType >::TStringBuilderBase (TStringBuilderBase< CharType > &&) delete
TStringBuilderBase() [4/4]
template<typename CharType> TStringBuilderBase< CharType >::TStringBuilderBase (CharType * BufferPointer, int32 BufferCapacity) inline
Definition at line 97 of file StringBuilder.h.
Member Function Documentation
Add()
template<typename CharType> template<typename AppendedCharType> auto TStringBuilderBase< CharType >::Add (AppendedCharType Char) -> decltype(AppendChar(Char), (void)0) inline
Prefer AppendChar.
Appends one character to the string. Supports this being the output for Algo::...
Definition at line 318 of file StringBuilder.h.
AddUninitialized()
template<typename CharType> int32 TStringBuilderBase< CharType >::AddUninitialized (int32 InCount) inline
Adds a given number of uninitialized characters into the string builder.
Parameters
InCount The number of uninitialized characters to add.
Returns
The number of characters in the string builder before adding the new characters.
Definition at line 190 of file StringBuilder.h.
AllocBuffer()
template<typename CharType> void * TStringBuilderBase< CharType >::AllocBuffer (SIZE_T CharCount) protected
Append() [1/2]
template<typename CharType> template<typename CharRangeType> auto TStringBuilderBase< CharType >::Append (CharRangeType && Range) -> decltype(Append(MakeStringView(Forward<CharRangeType>(Range)).GetData(), int32(0))) inline
Definition at line 238 of file StringBuilder.h.
Append() [2/2]
template<typename CharType> template<typename OtherCharType, std::enable_if_t< TIsCharType< OtherCharType >::Value > * = nullptr> BuilderType & TStringBuilderBase< CharType >::Append (const OtherCharType *const String, const int32 Length) inline
Definition at line 226 of file StringBuilder.h.
Referenced by TStringBuilderBase< TCHAR >::Append(), FAssetIdentifier::AppendString(), MaterialExpressionUtils::FormatUnsupportedMaterialDomainError(), FNetworkPredictionDriverBase< ModelDef >::GetDebugString(), FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull(), FNetworkPredictionDriverBase< ModelDef >::GetTraceString(), operator+=(), operator+=(), operator<<(), operator<<(), operator<<(), TStringBuilderBase< TCHAR >::operator=(), SNumericRotatorInputBox< float >::SLATE_END_ARGS(), and FPropertyPairsMap::ToString().
AppendChar()
template<typename CharType> template<typename AppendedCharType, std::enable_if_t< TIsCharType< AppendedCharType >::Value > * = nullptr> BuilderType & TStringBuilderBase< CharType >::AppendChar (AppendedCharType Char) inline
Definition at line 248 of file StringBuilder.h.
Referenced by TStringBuilderBase< TCHAR >::Add(), AppendChars(), FAssetData::GetExportTextName(), FAssetData::GetFullName(), operator+=(), operator+=(), operator+=(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), and FPropertyPairsMap::ToString().
Appendf()
template<typename CharType> template<typename FmtType, typename... Types UE_REQUIRES> BuilderType & TStringBuilderBase< CharType >::Appendf (const FmtType & Fmt, Types... Args) inline
Appends to the string builder similarly to how classic sprintf works.
Parameters
Fmt A format string that specifies how to format the additional arguments. Refer to standard printf format.
Definition at line 399 of file StringBuilder.h.
Referenced by FScopedDurationTimeCustomLogger< Func >::~FScopedDurationTimeCustomLogger(), FNetworkPredictionDriverBase< ModelDef >::GetDebugString(), FNetworkPredictionDriverBase< ModelDef >::GetDebugString(), FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull(), FNetworkPredictionDriverBase< ModelDef >::GetDebugStringFull(), FNetworkPredictionDriverBase< ModelDef >::GetTraceString(), FNetworkPredictionDriverBase< ModelDef >::GetTraceString(), operator<<(), and FNetworkPredictionPhysicsState::ToStringInternal().
AppendfImpl()
template<typename CharType> BuilderType &VARARGS TStringBuilderBase< CharType >::AppendfImpl (BuilderType & Self, const CharType * Fmt, ...) static private
Referenced by TStringBuilderBase< TCHAR >::Appendf().
AppendV()
template<typename CharType> BuilderType & TStringBuilderBase< CharType >::AppendV (const CharType * Fmt, va_list Args)
Appends to the string builder similarly to how classic vsprintf works.
Parameters
Fmt A format string that specifies how to format the additional arguments. Refer to standard printf format.
EnsureAdditionalCapacity()
template<typename CharType> void TStringBuilderBase< CharType >::EnsureAdditionalCapacity (int32 RequiredAdditionalCapacity) inline protected
Definition at line 433 of file StringBuilder.h.
Referenced by TStringBuilderBase< TCHAR >::AddUninitialized(), TStringBuilderBase< TCHAR >::Append(), TStringBuilderBase< TCHAR >::AppendChar(), and TStringBuilderBase< TCHAR >::ReplaceAt().
EnsureNulTerminated()
template<typename CharType> void TStringBuilderBase< CharType >::EnsureNulTerminated () const inline protected
Definition at line 428 of file StringBuilder.h.
Referenced by TStringBuilderBase< TCHAR >::operator*(), TStringBuilderBase< TCHAR >::ToString(), TStringBuilderBase< TCHAR >::UE_DEPRECATED(), and TStringBuilderBase< TCHAR >::UE_DEPRECATED().
Extend()
template<typename CharType> void TStringBuilderBase< CharType >::Extend (SIZE_T ExtraCapacity) protected
Referenced by TStringBuilderBase< TCHAR >::EnsureAdditionalCapacity(), and TStringBuilderBase< TCHAR >::Reserve().
FreeBuffer()
template<typename CharType> void TStringBuilderBase< CharType >::FreeBuffer (void * Buffer, SIZE_T CharCount) protected
GetAllocatedSize()
template<typename CharType> SIZE_T TStringBuilderBase< CharType >::GetAllocatedSize () const inline
Helper function to return the amount of memory allocated by this container.
Does not include the sizeof of the inline buffer, only includes the size of the overflow buffer.
Returns
Number of bytes allocated by this container.
Definition at line 170 of file StringBuilder.h.
GetData() [1/2]
template<typename CharType> const CharType * TStringBuilderBase< CharType >::GetData () const inline
Definition at line 113 of file StringBuilder.h.
GetData() [2/2]
template<typename CharType> CharType * TStringBuilderBase< CharType >::GetData () inline
Returns a pointer to Len() code units that are not necessarily null-terminated.
Definition at line 108 of file StringBuilder.h.
Referenced by UE::MemStack::AllocateString(), FShaderKeyGenerator::Append(), TStringBuilderBase< TCHAR >::begin, TStringBuilderBase< TCHAR >::begin, TStringBuilderBase< TCHAR >::end, TStringBuilderBase< TCHAR >::end, UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook(), FAssetIdentifier::ToString(), and FPrimaryAssetId::ToString().
Initialize()
template<typename CharType> void TStringBuilderBase< CharType >::Initialize (CharType * InBase, int32 InCapacity) inline protected
Definition at line 421 of file StringBuilder.h.
InsertAt()
template<typename CharType> void TStringBuilderBase< CharType >::InsertAt (int32 Pos, ViewType Str) inline
Insert substring at given position.
Definition at line 299 of file StringBuilder.h.
Join()
template<typename CharType> template<typename RangeType, typename DelimiterType, std::enable_if_t< TCanAppendRange_V< RangeType && > &&TCanAppend_V< DelimiterType && > > * = nullptr> BuilderType & TStringBuilderBase< CharType >::Join (RangeType && InRange, DelimiterType && InDelimiter) inline
Append every element of the range to the builder, separating the elements by the delimiter.
This function is only available when the elements of the range and the delimiter can both be written to the builder using the append operator.
Parameters
InRange The range of elements to join and append.
InDelimiter The delimiter to append as a separator for the elements.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 336 of file StringBuilder.h.
JoinQuoted()
template<typename CharType> template<typename RangeType, typename DelimiterType, typename QuoteType, std::enable_if_t< TCanAppendRange_V< RangeType > &&TCanAppend_V< DelimiterType && > &&TCanAppend_V< QuoteType && > > * = nullptr> BuilderType & TStringBuilderBase< CharType >::JoinQuoted (RangeType && InRange, DelimiterType && InDelimiter, QuoteType && InQuote) inline
Append every element of the range to the builder, separating the elements by the delimiter, and surrounding every element on each side with the given quote.
This function is only available when the elements of the range, the delimiter, and the quote can be written to the builder using the append operator.
Parameters
InRange The range of elements to join and append.
InDelimiter The delimiter to append as a separator for the elements.
InQuote The quote to append on both sides of each element.
Returns
The builder, to allow additional operations to be composed with this one.
Definition at line 369 of file StringBuilder.h.
LastChar()
template<typename CharType> CharType TStringBuilderBase< CharType >::LastChar () const inline
Returns the last character, technically the last code unit.
Definition at line 159 of file StringBuilder.h.
Len()
template<typename CharType> int32 TStringBuilderBase< CharType >::Len () const inline
Definition at line 102 of file StringBuilder.h.
Referenced by TStringBuilderBase< TCHAR >::AddUninitialized(), UE::MemStack::AllocateString(), FShaderKeyGenerator::Append(), TStringBuilderBase< TCHAR >::end, TStringBuilderBase< TCHAR >::end, MaterialExpressionUtils::FormatUnsupportedMaterialDomainError(), GetNum(), UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook(), TStringBuilderBase< TCHAR >::RemoveSuffix(), TStringBuilderBase< TCHAR >::ReplaceAt(), FAssetIdentifier::ToString(), FPrimaryAssetId::ToString(), TStringBuilderBase< TCHAR >::ToView(), TDirectoryTree< ValueType >::FTreeNode::TryFindClosestPath(), and TDirectoryTree< ValueType >::FTreeNode::TryGetChildren().
operator*()
template<typename CharType> const CharType * TStringBuilderBase< CharType >::operator* () inline
Returns a pointer to a null-terminated string that is valid until the builder is mutated.
Definition at line 138 of file StringBuilder.h.
operator=() [1/4]
template<typename CharType> TStringBuilderBase & TStringBuilderBase< CharType >::operator= (const CharType * Str) inline
Definition at line 92 of file StringBuilder.h.
operator=() [2/4]
template<typename CharType> TStringBuilderBase & TStringBuilderBase< CharType >::operator= (const TStringBuilderBase< CharType > &) delete
operator=() [3/4]
template<typename CharType> TStringBuilderBase & TStringBuilderBase< CharType >::operator= (TStringBuilderBase< CharType > &&) delete
operator=() [4/4]
template<typename CharType> TStringBuilderBase & TStringBuilderBase< CharType >::operator= (ViewType Str) inline
Definition at line 86 of file StringBuilder.h.
Prepend()
template<typename CharType> void TStringBuilderBase< CharType >::Prepend (ViewType Str) inline
Insert prefix.
Definition at line 311 of file StringBuilder.h.
RemoveAt()
template<typename CharType> void TStringBuilderBase< CharType >::RemoveAt (int32 Pos, int32 RemoveLen) inline
Remove characters at given position.
Definition at line 305 of file StringBuilder.h.
RemoveSuffix()
template<typename CharType> void TStringBuilderBase< CharType >::RemoveSuffix (int32 InCount) inline
Modifies the string builder to remove the given number of characters from the end.
Definition at line 218 of file StringBuilder.h.
Referenced by FPropertyPairsMap::ToString(), TDirectoryTree< ValueType >::FTreeNode::TryFindClosestPath(), and TDirectoryTree< ValueType >::FTreeNode::TryGetChildren().
ReplaceAt()
template<typename CharType> void TStringBuilderBase< CharType >::ReplaceAt (int32 Pos, int32 RemoveLen, ViewType Str) inline
Replace characters at given position and length with substring.
Definition at line 265 of file StringBuilder.h.
Referenced by TStringBuilderBase< TCHAR >::InsertAt(), TStringBuilderBase< TCHAR >::Prepend(), and TStringBuilderBase< TCHAR >::RemoveAt().
Reserve()
template<typename CharType> void TStringBuilderBase< CharType >::Reserve (int32 InNewCapacity) inline
Reserves memory such that the string builder can contain at least the given number of characters.
Note
: Unlike AddUninitialized, this will not advance CurPos, and thus the various Append calls will start at the end of the string builder (from prior to this Reserve call).
Parameters
InNewCapacity The total number of characters the string builder can contain.
Definition at line 205 of file StringBuilder.h.
Reset()
template<typename CharType> void TStringBuilderBase< CharType >::Reset () inline
Empties the string builder, but doesn't change memory allocation.
Definition at line 178 of file StringBuilder.h.
Referenced by FAssetData::GetExportTextName(), FAssetData::GetFullName(), TStringBuilderBase< TCHAR >::operator=(), and TDirectoryTree< ValueType >::TryFindClosestPathInternal().
ToString()
template<typename CharType> const CharType * TStringBuilderBase< CharType >::ToString () inline
Prefer operator*() for a pointer to a null-terminated string.
Construct FString and other string types directly from the string builder: FString Str(Builder).
Definition at line 123 of file StringBuilder.h.
Referenced by TNetSimCueDispatcher< ModelDef >::GetDebugName(), UE::Sequencer::IGroupableExtension::GetIdentifierForGrouping(), FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState(), FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState(), FNetworkPredictionDriverBase< ModelDef >::LogUserState(), FNetworkPredictionDriverBase< ModelDef >::LogUserStates(), SNumericRotatorInputBox< float >::SLATE_END_ARGS(), and FPropertyPairsMap::ToString().
ToView()
template<typename CharType> ViewType TStringBuilderBase< CharType >::ToView () const inline
Returns a view of the string that is valid until the builder is mutated.
Definition at line 153 of file StringBuilder.h.
Referenced by TDirectoryTree< ValueType >::NormalizePathForReading().
UE_DEPRECATED() [1/2]
template<typename CharType> TStringBuilderBase< CharType >::UE_DEPRECATED (5. 6, "Call the non-const operator*().") const inline
Returns a pointer to a null-terminated string that is valid until the builder is mutated.
Definition at line 145 of file StringBuilder.h.
UE_DEPRECATED() [2/2]
template<typename CharType> TStringBuilderBase< CharType >::UE_DEPRECATED (5. 6, "Call the non-const operator*().") const inline
Prefer operator*() for a pointer to a null-terminated string.
Definition at line 130 of file StringBuilder.h.
Friends And Related Symbol Documentation
begin [1/2]
template<typename CharType> const CharType * begin (const TStringBuilderBase< CharType > & Builder) friend
Definition at line 416 of file StringBuilder.h.
begin [2/2]
template<typename CharType> CharType * begin (TStringBuilderBase< CharType > & Builder) friend
Definition at line 415 of file StringBuilder.h.
end [1/2]
template<typename CharType> const CharType * end (const TStringBuilderBase< CharType > & Builder) friend
Definition at line 418 of file StringBuilder.h.
end [2/2]
template<typename CharType> CharType * end (TStringBuilderBase< CharType > & Builder) friend
Definition at line 417 of file StringBuilder.h.
Field Documentation
Base
template<typename CharType> CharType* TStringBuilderBase< CharType >::Base = EmptyBuffer protected
Definition at line 452 of file StringBuilder.h.
bIsDynamic
template<typename CharType> bool TStringBuilderBase< CharType >::bIsDynamic = false protected
Definition at line 455 of file StringBuilder.h.
CurPos
template<typename CharType> CharType* TStringBuilderBase< CharType >::CurPos = Base protected
Definition at line 453 of file StringBuilder.h.
EmptyBuffer
template<typename CharType> CharType TStringBuilderBase< CharType >::EmptyBuffer[1] {} inline static protected
Definition at line 450 of file StringBuilder.h.
End
template<typename CharType> CharType* TStringBuilderBase< CharType >::End = Base + 1 protected
Definition at line 454 of file StringBuilder.h.
TCanAppend_V
template<typename CharType> template<typename AppendType> bool TStringBuilderBase< CharType >::TCanAppend_V = std::is_same_v<BuilderType&, decltype(DeclVal<BuilderType&>() << DeclVal<AppendType>())> inline static constexpr
Whether the given type can be appended to this builder using the append operator.
Definition at line 71 of file StringBuilder.h.
TCanAppendRange_V
template<typename CharType> template<typename RangeType> bool TStringBuilderBase< CharType >::TCanAppendRange_V = TIsContiguousContainer<RangeType>::Value && TCanAppend_V<decltype(*::GetData(DeclVal<RangeType>()))> inline static constexpr
Whether the given range type can have its elements appended to the builder using the append operator.
Definition at line 75 of file StringBuilder.h.
The documentation for this class was generated from the following files:
StringFwd.h
StringBuilder.h