Unreal Engine 5.6 C++ API: TRDGHandleRegistry< LocalHandleType, DestructPolicy > Class Template Reference
TRDGHandleRegistry< LocalHandleType, DestructPolicy > Class Template Reference
Helper handle registry class for internal tracking of RDG types.
#include "RenderGraphDefinitions.h"
Public Types
using HandleType = LocalHandleType
using IndexType = typename HandleType::IndexType
using ObjectType = typename HandleType::ObjectType
Public Member Functions
TRDGHandleRegistry ()=default
TRDGHandleRegistry (const TRDGHandleRegistry &)=delete
TRDGHandleRegistry (TRDGHandleRegistry &&)=default
~TRDGHandleRegistry ()
template<typename DerivedType = ObjectType, class ... TArgs>
DerivedType * Allocate (FRDGAllocator &Allocator, TArgs &&... Args)
FORCEINLINE HandleType Begin () const
void Clear ()
FORCEINLINE HandleType End () const
template<typename FunctionType>
void Enumerate (FunctionType Function)
template<typename FunctionType>
void Enumerate (FunctionType Function) const
FORCEINLINE ObjectType * Get (HandleType Handle)
FORCEINLINE const ObjectType * Get (HandleType Handle) const
void Insert (ObjectType *Object)
FORCEINLINE HandleType Last () const
FORCEINLINE int32 Num () const
TRDGHandleRegistry & operator= (const TRDGHandleRegistry &)=delete
TRDGHandleRegistry & operator= (TRDGHandleRegistry &&)=default
FORCEINLINE ObjectType * operator[] (HandleType Handle)
FORCEINLINE const ObjectType * operator[] (HandleType Handle) const
Private Attributes
TArray< ObjectType *, FRDGArrayAllocator > Array
Detailed Description
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry>
class TRDGHandleRegistry< LocalHandleType, DestructPolicy >
Helper handle registry class for internal tracking of RDG types.
Definition at line 445 of file RenderGraphDefinitions.h.
Member Typedef Documentation
HandleType
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> using TRDGHandleRegistry< LocalHandleType, DestructPolicy >::HandleType = LocalHandleType
Definition at line 448 of file RenderGraphDefinitions.h.
IndexType
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> using TRDGHandleRegistry< LocalHandleType, DestructPolicy >::IndexType = typename HandleType::IndexType
Definition at line 450 of file RenderGraphDefinitions.h.
ObjectType
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> using TRDGHandleRegistry< LocalHandleType, DestructPolicy >::ObjectType = typename HandleType::ObjectType
Definition at line 449 of file RenderGraphDefinitions.h.
Constructor & Destructor Documentation
TRDGHandleRegistry() [1/3]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TRDGHandleRegistry< LocalHandleType, DestructPolicy >::TRDGHandleRegistry () default
TRDGHandleRegistry() [2/3]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TRDGHandleRegistry< LocalHandleType, DestructPolicy >::TRDGHandleRegistry (const TRDGHandleRegistry< LocalHandleType, DestructPolicy > &) delete
TRDGHandleRegistry() [3/3]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TRDGHandleRegistry< LocalHandleType, DestructPolicy >::TRDGHandleRegistry (TRDGHandleRegistry< LocalHandleType, DestructPolicy > &&) default
~TRDGHandleRegistry()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TRDGHandleRegistry< LocalHandleType, DestructPolicy >::~TRDGHandleRegistry () inline
Definition at line 458 of file RenderGraphDefinitions.h.
Member Function Documentation
Allocate()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> template<typename DerivedType = ObjectType, class ... TArgs> DerivedType * TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Allocate (FRDGAllocator & Allocator, TArgs &&... Args) inline
Definition at line 470 of file RenderGraphDefinitions.h.
Begin()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE HandleType TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Begin () const inline
Definition at line 536 of file RenderGraphDefinitions.h.
Clear()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> void TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Clear () inline
Definition at line 486 of file RenderGraphDefinitions.h.
Referenced by TRDGHandleRegistry< FRDGPassHandle >::~TRDGHandleRegistry().
End()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE HandleType TRDGHandleRegistry< LocalHandleType, DestructPolicy >::End () const inline
Definition at line 541 of file RenderGraphDefinitions.h.
Enumerate() [1/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> template<typename FunctionType> void TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Enumerate (FunctionType Function) inline
Definition at line 499 of file RenderGraphDefinitions.h.
Enumerate() [2/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> template<typename FunctionType> void TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Enumerate (FunctionType Function) const inline
Definition at line 508 of file RenderGraphDefinitions.h.
Get() [1/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE ObjectType * TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Get (HandleType Handle) inline
Definition at line 521 of file RenderGraphDefinitions.h.
Get() [2/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE const ObjectType * TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Get (HandleType Handle) const inline
Definition at line 516 of file RenderGraphDefinitions.h.
Referenced by TRDGHandleRegistry< FRDGPassHandle >::operator[](), and TRDGHandleRegistry< FRDGPassHandle >::operator[]().
Insert()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> void TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Insert (ObjectType * Object) inline
Definition at line 463 of file RenderGraphDefinitions.h.
Referenced by TRDGHandleRegistry< FRDGPassHandle >::Allocate().
Last()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE HandleType TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Last () const inline
Definition at line 546 of file RenderGraphDefinitions.h.
Referenced by TRDGHandleRegistry< FRDGPassHandle >::Insert().
Num()
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE int32 TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Num () const inline
Definition at line 551 of file RenderGraphDefinitions.h.
operator=() [1/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TRDGHandleRegistry & TRDGHandleRegistry< LocalHandleType, DestructPolicy >::operator= (const TRDGHandleRegistry< LocalHandleType, DestructPolicy > &) delete
operator=() [2/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TRDGHandleRegistry & TRDGHandleRegistry< LocalHandleType, DestructPolicy >::operator= (TRDGHandleRegistry< LocalHandleType, DestructPolicy > &&) default
operator[]() [1/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE ObjectType * TRDGHandleRegistry< LocalHandleType, DestructPolicy >::operator[] (HandleType Handle) inline
Definition at line 531 of file RenderGraphDefinitions.h.
operator[]() [2/2]
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> FORCEINLINE const ObjectType * TRDGHandleRegistry< LocalHandleType, DestructPolicy >::operator[] (HandleType Handle) const inline
Definition at line 526 of file RenderGraphDefinitions.h.
Field Documentation
Array
template<typename LocalHandleType, ERDGHandleRegistryDestructPolicy DestructPolicy = ERDGHandleRegistryDestructPolicy::Registry> TArray<ObjectType*, FRDGArrayAllocator> TRDGHandleRegistry< LocalHandleType, DestructPolicy >::Array private
Definition at line 557 of file RenderGraphDefinitions.h.
The documentation for this class was generated from the following file:
RenderGraphDefinitions.h