Unreal Engine 5.6 C++ API: ObjectPtr.h File Reference
ObjectPtr.h File Reference
#include "HAL/Platform.h"
#include "Serialization/StructuredArchive.h"
#include "Templates/IsTObjectPtr.h"
#include "UObject/GarbageCollectionGlobals.h"
#include "UObject/ObjectHandle.h"
#include "UObject/UObjectGlobals.h"
#include "Templates/NonNullPointer.h"
#include <type_traits>
Data Structures
struct FObjectPtr
FObjectPtr is the basic, minimally typed version of TObjectPtr.
struct ObjectPtr_Private::Friend
class ObjectPtr_Private::TNonAccessTrackedObjectPtr< T >
struct ObjectPtr_Private::TRawPointerType< T >
struct ObjectPtr_Private::TRawPointerType< const TObjectPtr< T > >
struct ObjectPtr_Private::TRawPointerType< const volatile TObjectPtr< T > >
struct ObjectPtr_Private::TRawPointerType< TObjectPtr< T > >
struct ObjectPtr_Private::TRawPointerType< volatile TObjectPtr< T > >
struct TCallTraits< TObjectPtr< T > >
struct TContainerElementTypeCompatibility< const TObjectPtr< T > >
struct TContainerElementTypeCompatibility< TObjectPtr< T > >
struct TDereferenceWrapper< TObjectPtr< T >, PREDICATE_CLASS >
struct TIsBitwiseConstructible< TObjectPtr< T >, T * >
struct TIsPointerOrObjectPtrToBaseOf< T, DerivedType >
struct TIsPointerOrObjectPtrToBaseOfImpl< T, DerivedType >
struct TIsPointerOrObjectPtrToBaseOfImpl< T *, DerivedType >
struct TIsPointerOrObjectPtrToBaseOfImpl< TObjectPtr< T >, DerivedType >
struct TIsZeroConstructType< TObjectPtr< T > >
class TNonNullPtr< TObjectPtr< ObjectType > >
struct TObjectPtr< T >
TObjectPtr is a type of pointer to a UObject that is meant to function as a drop-in replacement for raw pointer member properties.
struct TPointedToTypeImpl< T * >
struct TPointedToTypeImpl< TObjectPtr< T > >
struct TPrivateObjectPtr< T >
struct TRemoveObjectPointer< T >
struct TRemoveObjectPointer< TObjectPtr< T > >
class UE::Core::Private::TMaybeObjectPtr< T >
class UE::Core::Private::TMutableView< T >
struct UE::Core::Private::TMutableViewTraits< T, ViewType >
struct UE::Core::Private::TMutableViewTraits< TArray< TObjectPtr< T > >, ViewType >
struct UE::Core::Private::TMutableViewTraits< TMap< K, V >, ViewType >
struct UE::Core::Private::TMutableViewTraits< TObjectPtr< T >, ViewType >
struct UE::Core::Private::TMutableViewTraits< TSet< TObjectPtr< V > >, ViewType >
struct UE::Core::Private::TObjectPtrDecayTypeOf< T >
struct UE::Core::Private::TObjectPtrDecayTypeOf< TArray< T > >
struct UE::Core::Private::TObjectPtrDecayTypeOf< TMap< K, V > >
struct UE::Core::Private::TObjectPtrDecayTypeOf< TNonNullPtr< TObjectPtr< T > > >
struct UE::Core::Private::TObjectPtrDecayTypeOf< TObjectPtr< T > >
struct UE::Core::Private::TObjectPtrDecayTypeOf< TSet< T > >
struct UE::Core::Private::TObjectPtrWrapTypeOf< T >
struct UE::Core::Private::TObjectPtrWrapTypeOf< T * >
struct UE::Core::Private::TObjectPtrWrapTypeOf< TArray< T > >
struct UE::Core::Private::TObjectPtrWrapTypeOf< TArrayView< T > >
struct UE::Core::Private::TObjectPtrWrapTypeOf< TMap< K, V > >
struct UE::Core::Private::TObjectPtrWrapTypeOf< TSet< T > >
Namespaces
namespace ObjectPtr_Private
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
namespace UE::Core::Private::Unsafe
Macros
#define UE_OBJECT_PTR_GC_BARRIER 1
#define UE_OBJECT_PTR_NONCONFORMANCE_SUPPORT 0
#define UE_OBJPTR_DEPRECATED(Version, Message)
#define UE_TRANSITIONAL_OBJECT_PTR(Type)
Wrapper macro for use in places where code needs to allow for a pointer type that could be a TObjectPtr<T> or a raw object pointer during a transitional period.
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE(Templ, Type)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG1(Templ, Type1, Type2)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG1_SUFFIXED(Templ, Type1, Type2, Suffix)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG2(Templ, Type1, Type2)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG2_SUFFIXED(Templ, Type1, Type2, Suffix)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG_BOTH(Templ, Type1, Type2)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG_BOTH_SUFFIXED(Templ, Type1, Type2, Suffix)
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE_SUFFIXED(Templ, Type, Suffix)
#define UE_WITH_OBJECT_PTR_DEPRECATIONS 0
Typedefs
template<typename T>
using TObjectPtrWrapTypeOf = typename UE::Core::Private::TObjectPtrWrapTypeOf<T>::Type
template<typename T>
using TPointedToType = typename TPointedToTypeImpl<T>::Type
Functions
template<typename T>
FORCEINLINE const T * ObjectPtr_Private::CoerceToPointer (const T *Other)
Coerce to pointer through implicit conversion to const T* (overload through less specific "const T*" parameter to avoid ambiguity with other coercion options that may also exist.
template<typename T, typename U UE_REQUIRES>
FORCEINLINE std::common_type_t< const T *, U > ObjectPtr_Private::CoerceToPointer (const U &Other)
Coerce to pointer through implicit conversion to CommonPointerType where CommonPointerType is deduced, and must be a C++ pointer, not a wrapper type.
template<typename T, typename U UE_REQUIRES>
FORCEINLINE auto ObjectPtr_Private::CoerceToPointer (const U &Other) -> decltype(Other.Get())
Coerce to pointer through the use of a ".Get()" member, which is the convention within Unreal smart pointer types.
template<typename T>
FORCEINLINE decltype(auto) ConstCast (const TObjectPtr< T > &P)
template<typename T, typename DecayTraits = UE::Core::Private::TObjectPtrDecayTypeOf<T>, typename U = typename DecayTraits::Type>
U & UE::Core::Private::Unsafe::Decay (T &A)
template<typename T>
void Exchange (T *&A, TObjectPtr< T > &B)
template<typename T>
void Exchange (TArray< T * > &A, TArray< TObjectPtr< T > > &B)
template<typename T>
void Exchange (TObjectPtr< T > &A, T *&B)
Exchange variants between TObjectPtr<T> and raw pointer to T.
template<typename T>
FORCEINLINE T * ObjectPtr_Private::Get (const FObjectPtr &ObjectPtr)
Resolve and return the underlying reference.
template<typename T>
FORCEINLINE uint32 GetTypeHash (const TObjectPtr< T > &InObjectPtr)
template<typename T>
T * GetValid (const TObjectPtr< T > &Test)
Returns a pointer to a valid object if the Test object passes IsValid() tests, otherwise null.
template<typename T, typename U, decltype(CoerceToPointer< T >(std::declval< U >())==std::declval< const T * >()) * = nullptr UE_REQUIRES(!TIsTObjectPtr_V<U>)>
bool ObjectPtr_Private::IsObjectPtrEqual (const TObjectPtr< T > &Ptr, const U &Other)
Perform shallow equality check between a TObjectPtr and another (non TObjectPtr) type that we can coerce to a pointer.
template<typename T, typename U>
bool ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType (const TObjectPtr< T > &Ptr, const U *Other)
template<typename T>
FORCEINLINE bool ObjectPtr_Private::IsObjectPtrNull (const FObjectPtr &ObjectPtr)
Check for NULL without resolving the handle.
template<typename T>
TPrivateObjectPtr< T > MakeObjectPtrUnsafe (const UObject *Obj)
Used to allow the caller to provide a pointer to an incomplete type of T that has explicitly cast to a UObject.
template<typename T>
FORCEINLINE TWeakObjectPtr< T > MakeWeakObjectPtr (TObjectPtr< T > Ptr)
template<typename T>
decltype(auto) MutableView (T &A)
template<typename T, typename DecayTraits = typename UE::Core::Private::TObjectPtrDecayTypeOf<T>, typename U = typename DecayTraits::Type>
const U & ObjectPtrDecay (const T &Value)
template<typename T, typename U = typename UE::Core::Private::TObjectPtrWrapTypeOf<T>::Type>
const U & ObjectPtrWrap (const T &Value)
template<typename T, typename U = typename UE::Core::Private::TObjectPtrWrapTypeOf<T>::Type>
U & ObjectPtrWrap (T &Value)
template<typename T, typename U, decltype(ObjectPtr_Private::IsObjectPtrEqual(std::declval< const TObjectPtr< T > & >(), std::declval< const U & >())) * = nullptr>
FORCEINLINE bool operator!= (const U &Other, const TObjectPtr< T > &Ptr)
template<typename T>
FORCEINLINE FArchive & operator<< (FArchive &Ar, TObjectPtr< T > &InObjectPtr)
template<typename T>
FORCEINLINE void operator<< (FStructuredArchiveSlot Slot, TObjectPtr< T > &InObjectPtr)
template<typename T, typename U, decltype(ObjectPtr_Private::IsObjectPtrEqual(std::declval< const TObjectPtr< T > & >(), std::declval< const U & >())) * = nullptr>
FORCEINLINE bool operator== (const U &Other, const TObjectPtr< T > &Ptr)
template<typename T>
char(& ObjectPtr_Private::ResolveTypeIsComplete (...))[1]
template<typename T, int = sizeof(T)>
char(& ObjectPtr_Private::ResolveTypeIsComplete (int))[2]
template<typename To, typename From>
FORCEINLINE To * StaticCastPtr (const TObjectPtr< From > &P)
template<typename T>
void Swap (T *&A, TObjectPtr< T > &B)
template<typename T>
void Swap (TArray< T * > &A, TArray< TObjectPtr< T > > &B)
template<typename T>
void Swap (TObjectPtr< T > &A, T *&B)
Swap variants between TObjectPtr<T> and raw pointer to T.
template<typename T>
TObjectPtr< T > ToObjectPtr (T *Obj)
template<typename T>
FORCEINLINE T * ToRawPtr (const TObjectPtr< T > &Ptr)
template<typename T>
decltype(auto) ToRawPtr (const UE::Core::Private::TMutableView< T > &X)
template<typename T>
FORCEINLINE T * ToRawPtr (T *Ptr)
template<typename T, SIZE_T Size>
FORCEINLINE const T *const * ToRawPtrArray (const TObjectPtr< T >(&ArrayOfPtr)[Size])
template<typename T>
FORCEINLINE T ** ToRawPtrArrayUnsafe (T **ArrayOfPtr)
UE_DEPRECATED (5.6, "Exchange between TObjectPtr arrays and raw pointer arrays is deprecated. Exchange TArray<TObjectPtr<...>> values instead.") template< typename T > inline void Exchange(TArray< TObjectPtr< T > > &A
Exchange variants between TArray<TObjectPtr<T>> and TArray<T*>
template<typename T, SIZE_T Size>
UE_DEPRECATED (5.6, "Mutable ToRawPtrArrayUnsafe() is deprecated. Use MutableView() or TArray<TObjectPtr<...>> instead.") FORCEINLINE T **ToRawPtrArrayUnsafe(TObjectPtr< T >(&ArrayOfPtr)[Size])
template<typename ArrayType, typename ArrayTypeNoRef = std::remove_reference_t<ArrayType> UE_REQUIRES(TIsTArray_V<ArrayTypeNoRef>)>
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Mutable ToRawPtrTArrayUnsafe() is deprecated. Use MutableView() or TArray<TObjectPtr<...>> instead.") decltype(auto) ToRawPtrTArrayUnsafe(ArrayType &&Array)
UE_DEPRECATED (5.6, "Swap between TObjectPtr arrays and raw pointer arrays is deprecated. Swap TArray<TObjectPtr<...>> values instead.") template< typename T > inline void Swap(TArray< TObjectPtr< T > > &A
Swap variants between TArray<TObjectPtr<T>> and TArray<T*>
Variables
TArray< T * > & B
PRAGMA_ENABLE_DEPRECATION_WARNINGS constexpr auto TContainerElementTypeCompatibility_DefaultOperatorFunc = [](auto& InIt) -> decltype(auto) { return *InIt; }
Macro Definition Documentation
UE_OBJECT_PTR_GC_BARRIER
#define UE_OBJECT_PTR_GC_BARRIER 1
Definition at line 23 of file ObjectPtr.h.
UE_OBJECT_PTR_NONCONFORMANCE_SUPPORT
#define UE_OBJECT_PTR_NONCONFORMANCE_SUPPORT 0
Definition at line 51 of file ObjectPtr.h.
UE_OBJPTR_DEPRECATED
#define UE_OBJPTR_DEPRECATED (Version, Message)
Definition at line 19 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR
#define UE_TRANSITIONAL_OBJECT_PTR (Type)
Value:
auto
Wrapper macro for use in places where code needs to allow for a pointer type that could be a TObjectPtr<T> or a raw object pointer during a transitional period.
The coding standard disallows general use of the auto keyword, but in wrapping it in this macro, we have a record of the explicit type meant to be used, and an avenue to go back and change these instances to an explicit TObjectPtr<T> after the transition is complete and the type won't be toggling back and forth anymore.
Definition at line 33 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE (Templ, Type)
Value:
auto
Definition at line 34 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG1
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG1 (Templ, Type1, Type2)
Value:
auto
Definition at line 36 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG1_SUFFIXED
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG1_SUFFIXED (Templ, Type1, Type2, Suffix)
Value:
auto
Definition at line 37 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG2
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG2 (Templ, Type1, Type2)
Value:
auto
Definition at line 38 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG2_SUFFIXED
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG2_SUFFIXED (Templ, Type1, Type2, Suffix)
Value:
auto
Definition at line 39 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG_BOTH
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG_BOTH (Templ, Type1, Type2)
Value:
auto
Definition at line 40 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG_BOTH_SUFFIXED
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE2_ARG_BOTH_SUFFIXED (Templ, Type1, Type2, Suffix)
Value:
auto
Definition at line 41 of file ObjectPtr.h.
UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE_SUFFIXED
#define UE_TRANSITIONAL_OBJECT_PTR_TEMPLATE_SUFFIXED (Templ, Type, Suffix)
Value:
auto
Definition at line 35 of file ObjectPtr.h.
UE_WITH_OBJECT_PTR_DEPRECATIONS
#define UE_WITH_OBJECT_PTR_DEPRECATIONS 0
Definition at line 15 of file ObjectPtr.h.
Typedef Documentation
TObjectPtrWrapTypeOf
template<typename T> using TObjectPtrWrapTypeOf = typename UE::Core::Private::TObjectPtrWrapTypeOf<T>::Type
Definition at line 1784 of file ObjectPtr.h.
TPointedToType
template<typename T> using TPointedToType = typename TPointedToTypeImpl<T>::Type
Definition at line 1377 of file ObjectPtr.h.
Function Documentation
ConstCast()
template<typename T> FORCEINLINE decltype(auto) ConstCast (const TObjectPtr< T > & P) nodiscard
Definition at line 1801 of file ObjectPtr.h.
References FORCEINLINE.
Referenced by TActorDescContainerCollection< ActorDescContPtrType >::RegisterDelegates(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::RegisterDelegates(), TActorDescContainerCollection< ActorDescContPtrType >::UnregisterDelegates(), and TActorDescContainerInstanceCollection< ActorDescContPtrType >::UnregisterDelegates().
Exchange() [1/3]
template<typename T> void Exchange (T *& A, TObjectPtr< T > & B) inline
Definition at line 1285 of file ObjectPtr.h.
References A, B, MutableView(), and Swap.
Exchange() [2/3]
template<typename T> void Exchange (TArray< T * > & A, TArray< TObjectPtr< T > > & B) inline
Definition at line 1299 of file ObjectPtr.h.
References A, B, and Swap.
Exchange() [3/3]
template<typename T> void Exchange (TObjectPtr< T > & A, T *& B) inline
Exchange variants between TObjectPtr<T> and raw pointer to T.
Definition at line 1280 of file ObjectPtr.h.
References A, B, MutableView(), and Swap.
GetTypeHash()
template<typename T> FORCEINLINE uint32 GetTypeHash (const TObjectPtr< T > & InObjectPtr) nodiscard
Definition at line 949 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr_Private::Friend::GetPtrTypeHash().
Referenced by TObjectPtr< T >::GetPtrTypeHash().
GetValid()
template<typename T> T * GetValid (const TObjectPtr< T > & Test) nodiscard
Returns a pointer to a valid object if the Test object passes IsValid() tests, otherwise null.
Definition at line 1309 of file ObjectPtr.h.
References IsValid(), Test, and ToRawPtr().
MakeObjectPtrUnsafe()
template<typename T> TPrivateObjectPtr< T > MakeObjectPtrUnsafe (const UObject * Obj) nodiscard
Used to allow the caller to provide a pointer to an incomplete type of T that has explicitly cast to a UObject.
Definition at line 1011 of file ObjectPtr.h.
MakeWeakObjectPtr()
template<typename T> FORCEINLINE TWeakObjectPtr< T > MakeWeakObjectPtr (TObjectPtr< T > Ptr) nodiscard
Definition at line 1227 of file ObjectPtr.h.
References FORCEINLINE, and TObjectPtr< T >::IsRemote().
MutableView()
template<typename T> decltype(auto) MutableView (T & A) nodiscard
Definition at line 1741 of file ObjectPtr.h.
References A.
Referenced by Exchange(), Exchange(), Swap(), and Swap().
ObjectPtrDecay()
template<typename T, typename DecayTraits = typename UE::Core::Private::TObjectPtrDecayTypeOf<T>, typename U = typename DecayTraits::Type> const U & ObjectPtrDecay (const T & Value) nodiscard
Definition at line 1767 of file ObjectPtr.h.
References Value.
Referenced by FMaterial::GetErrorExpressions(), FAudioDevice::GetPrevPassiveSoundMixModifiers(), FPackageReloadedEvent::GetRepointedObjects(), FStructSharedMemory::GetScriptStruct(), FAudioDevice::GetSoundMixModifiers(), and UCLASS().
ObjectPtrWrap() [1/2]
template<typename T, typename U = typename UE::Core::Private::TObjectPtrWrapTypeOf<T>::Type> const U & ObjectPtrWrap (const T & Value) nodiscard
Definition at line 1788 of file ObjectPtr.h.
References Value.
ObjectPtrWrap() [2/2]
template<typename T, typename U = typename UE::Core::Private::TObjectPtrWrapTypeOf<T>::Type> U & ObjectPtrWrap (T & Value) nodiscard
Definition at line 1778 of file ObjectPtr.h.
References Value.
Referenced by FPackageReloadedEvent::FPackageReloadedEvent(), and FAudioDevice::SetSoundMixModifiers().
operator!=()
template<typename T, typename U, decltype(ObjectPtr_Private::IsObjectPtrEqual(std::declval< const TObjectPtr< T > & >(), std::declval< const U & >())) * = nullptr> FORCEINLINE bool operator!= (const U & Other, const TObjectPtr< T > & Ptr) nodiscard
Definition at line 982 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::IsObjectPtrEqual(), and Other.
operator<<() [1/2]
template<typename T> FORCEINLINE FArchive & operator<< (FArchive & Ar, TObjectPtr< T > & InObjectPtr)
Definition at line 955 of file ObjectPtr.h.
References Ar, FORCEINLINE, and ObjectPtr_Private::Friend::Serialize().
operator<<() [2/2]
template<typename T> FORCEINLINE void operator<< (FStructuredArchiveSlot Slot, TObjectPtr< T > & InObjectPtr)
Definition at line 961 of file ObjectPtr.h.
References FORCEINLINE, and ObjectPtr_Private::Friend::SerializePtrStructured().
operator==()
template<typename T, typename U, decltype(ObjectPtr_Private::IsObjectPtrEqual(std::declval< const TObjectPtr< T > & >(), std::declval< const U & >())) * = nullptr> FORCEINLINE bool operator== (const U & Other, const TObjectPtr< T > & Ptr) nodiscard
Definition at line 973 of file ObjectPtr.h.
References FORCEINLINE, ObjectPtr_Private::IsObjectPtrEqual(), and Other.
StaticCastPtr()
template<typename To, typename From> FORCEINLINE To * StaticCastPtr (const TObjectPtr< From > & P) nodiscard
Definition at line 1795 of file ObjectPtr.h.
References FORCEINLINE, and TObjectPtr< T >::Get().
Swap() [1/3]
template<typename T> void Swap (T *& A, TObjectPtr< T > & B) inline
Definition at line 1258 of file ObjectPtr.h.
References A, B, MutableView(), and Swap.
Swap() [2/3]
template<typename T> void Swap (TArray< T * > & A, TArray< TObjectPtr< T > > & B) inline
Definition at line 1272 of file ObjectPtr.h.
References A, B, and Swap.
Swap() [3/3]
template<typename T> void Swap (TObjectPtr< T > & A, T *& B) inline
Swap variants between TObjectPtr<T> and raw pointer to T.
Definition at line 1253 of file ObjectPtr.h.
References A, B, MutableView(), and Swap.
ToObjectPtr()
template<typename T> TObjectPtr< T > ToObjectPtr (T * Obj) nodiscard
Definition at line 1017 of file ObjectPtr.h.
ToRawPtr() [1/3]
template<typename T> FORCEINLINE T * ToRawPtr (const TObjectPtr< T > & Ptr) nodiscard
Definition at line 1023 of file ObjectPtr.h.
References FORCEINLINE, and TObjectPtr< T >::Get().
Referenced by TScriptInterface< const InterfaceType >::TScriptInterface(), FActiveSound::GetSourceEffectChain(), GetValid(), MakeSoftClassPtr(), MakeSoftObjectPtr(), and UCLASS().
ToRawPtr() [2/3]
template<typename T> decltype(auto) ToRawPtr (const UE::Core::Private::TMutableView< T > & X) nodiscard
Definition at line 1747 of file ObjectPtr.h.
References X.
ToRawPtr() [3/3]
template<typename T> FORCEINLINE T * ToRawPtr (T * Ptr) nodiscard
Definition at line 1030 of file ObjectPtr.h.
References FORCEINLINE.
ToRawPtrArray()
template<typename T, SIZE_T Size> FORCEINLINE const T *const * ToRawPtrArray (const TObjectPtr< T >(&) ArrayOfPtr[Size]) nodiscard
Definition at line 1056 of file ObjectPtr.h.
References TSequenceHistory< HistorySize >::Size.
ToRawPtrArrayUnsafe()
template<typename T> FORCEINLINE T ** ToRawPtrArrayUnsafe (T ** ArrayOfPtr) nodiscard
Definition at line 1067 of file ObjectPtr.h.
References FORCEINLINE.
UE_DEPRECATED() [1/4]
UE_DEPRECATED (5. 6, "Exchange between TObjectPtr arrays and raw pointer arrays is deprecated. Exchange TArray<TObjectPtr<...>> values instead.") &
Exchange variants between TArray<TObjectPtr<T>> and TArray<T*>
References A, B, Exchange(), and Swap.
UE_DEPRECATED() [2/4]
template<typename T, SIZE_T Size> UE_DEPRECATED (5. 6, "Mutable ToRawPtrArrayUnsafe() is deprecated. Use MutableView() or TArray<TObjectPtr<...>> instead."))[Size] & nodiscard
Definition at line 1037 of file ObjectPtr.h.
References check, FORCEINLINE, Item, and TSequenceHistory< HistorySize >::Size.
UE_DEPRECATED() [3/4]
template<typename ArrayType, typename ArrayTypeNoRef = std::remove_reference_t<ArrayType> UE_REQUIRES(TIsTArray_V<ArrayTypeNoRef>)> PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5. 6, "Mutable ToRawPtrTArrayUnsafe() is deprecated. Use MutableView() or TArray<TObjectPtr<...>> instead.") && nodiscard
Definition at line 1081 of file ObjectPtr.h.
References Array.
UE_DEPRECATED() [4/4]
UE_DEPRECATED (5. 6, "Swap between TObjectPtr arrays and raw pointer arrays is deprecated. Swap TArray<TObjectPtr<...>> values instead.") &
Swap variants between TArray<TObjectPtr<T>> and TArray<T*>
Variable Documentation
B
TArray<T*>& B
Initial value:
{
    Swap(ToRawPtrTArrayUnsafe(A), B)
Definition at line 1267 of file ObjectPtr.h.
Referenced by TDereferenceWrapper< TObjectPtr< T >, PREDICATE_CLASS >::operator()().
TContainerElementTypeCompatibility_DefaultOperatorFunc
PRAGMA_ENABLE_DEPRECATION_WARNINGS constexpr auto TContainerElementTypeCompatibility_DefaultOperatorFunc = [](auto& InIt) -> decltype(auto) { return *InIt; } inline constexpr
Definition at line 1102 of file ObjectPtr.h.
Referenced by TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRange(), TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRange(), TContainerElementTypeCompatibility< const TObjectPtr< T > >::ReinterpretRangeContiguous(), and TContainerElementTypeCompatibility< TObjectPtr< T > >::ReinterpretRangeContiguous().