Unreal Engine 5.6 C++ API: Shader.h File Reference
Shader.h File Reference
#include "Algo/BinarySearch.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/ContainersFwd.h"
#include "Containers/EnumAsByte.h"
#include "Containers/HashTable.h"
#include "Containers/List.h"
#include "Containers/Map.h"
#include "Containers/Set.h"
#include "Containers/StringFwd.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "HAL/CriticalSection.h"
#include "HAL/PlatformCrt.h"
#include "HAL/ThreadSafeBool.h"
#include "HAL/UnrealMemory.h"
#include "Math/NumericLimits.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CString.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/ScopeLock.h"
#include "Misc/SecureHash.h"
#include "RHI.h"
#include "RHIDefinitions.h"
#include "RHIMemoryLayout.h"
#include "RenderResource.h"
#include "RenderDeferredCleanup.h"
#include "Serialization/Archive.h"
#include "Serialization/ArchiveProxy.h"
#include "Serialization/MemoryImage.h"
#include "Serialization/MemoryLayout.h"
#include "ShaderCore.h"
#include "ShaderParameterMetadata.h"
#include "ShaderParameters.h"
#include "ShaderPermutation.h"
#include "ShaderPermutationUtils.h"
#include "Templates/RefCounting.h"
#include "Templates/TypeHash.h"
#include "Templates/UniquePtr.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "UObject/NameTypes.h"
#include "UObject/RenderingObjectVersion.h"
#include <atomic>
#include "UObject/DebugSerializationFlags.h"
Data Structures
class FCompareShaderTypes
Used to compare two shader types by name.
struct FRegisterRayTracingPayloadTypeHelper
class FShader
A compiled shader and its parameter bindings.
struct FShaderCompiledShaderInitializerType
class FShaderId
Uniquely identifies an FShader instance.
class FShaderKey
Encapsulates information about a shader's serialization behavior, used to detect when C++ serialization changes to auto-recompile.
class FShaderLooseParameterBufferInfo
class FShaderLooseParameterInfo
class FShaderMapBase
class FShaderMapContent
A collection of shaders of different types.
struct FShaderMapContent::FProjectShaderPipelineToKey
class FShaderMapPointerTable
class FShaderMapResource
class FShaderMapResource_InlineCode
class FShaderMapResourceCode
struct FShaderMapResourceCode::FShaderEntry
class FShaderParameterBindings
Stores all shader parameter bindings and their corresponding offset and size in the shader's parameters struct.
struct FShaderParameterBindings::FBindlessResourceParameter
struct FShaderParameterBindings::FParameter
struct FShaderParameterBindings::FParameterStructReference
struct FShaderParameterBindings::FResourceParameter
class FShaderParameterMapInfo
class FShaderPipeline
class FShaderPipelineRef
class FShaderPipelineType
class FShaderPipelineTypeDependency
class FShaderResourceParameterInfo
class FShaderType
An object which is used to serialize/deserialize, compile, and cache a particular shader class.
class FShaderType::FParameters
Derived FShaderTypes should derive from this class to pass params to FShader constructor.
class FShaderTypeDependency
Encapsulates a dependency on a shader type and saved state from that shader type.
class FShaderTypeRegistration
Registers a shader type in various systems.
class FShaderUniformBufferParameterInfo
class TCompareShaderTypePermutation< MetaShaderType >
Used to compare order shader types permutation deterministically.
class TOptionalShaderMapRef< ShaderType >
A reference to an optional shader, initialized with a shader type from a shader map if it is available or nullptr if it is not.
class TShaderMap< ContentType, PointerTableType >
class TShaderMapRef< ShaderType >
A reference which is initialized with the requested shader type from a shader map.
class TShaderRefBase< ShaderType, PointerTableType >
struct TShaderTypePermutation< MetaShaderType >
Define a shader permutation uniquely according to its type, and permutation id.
Namespaces
namespace Freeze
Macros
#define DECLARE_EXPORTED_SHADER_TYPE(ShaderClass, ShaderMetaTypeShortcut, RequiredAPI, ...)
A macro to declare a new shader type.
#define DECLARE_SHADER_TYPE(ShaderClass, ShaderMetaTypeShortcut, ...)
#define DECLARE_SHADER_TYPE_EXPLICIT_BASES(ShaderClass, ShaderMetaTypeShortcut, ...)
#define IMPLEMENT_RT_PAYLOAD_TYPE(PayloadType, PayloadSize)
#define IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT(x, y)
#define IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT2(x, y)
#define IMPLEMENT_RT_PAYLOAD_TYPE_FUNCTION(PayloadType, PayloadSizeFunction)
#define IMPLEMENT_SHADER_TYPE(TemplatePrefix, ShaderClass, SourceFilename, FunctionName, Frequency)
A macro to implement a shader type.
#define IMPLEMENT_SHADER_TYPE2(ShaderClass, Frequency)
#define IMPLEMENT_SHADER_TYPE2_WITH_TEMPLATE_PREFIX(TemplatePrefix, ShaderClass, Frequency)
A macro to implement a templated shader type, the function name and the source filename comes from the class.
#define IMPLEMENT_SHADER_TYPE3(ShaderClass, Frequency)
todo: this should replace IMPLEMENT_SHADER_TYPE
#define IMPLEMENT_SHADER_TYPE4_WITH_TEMPLATE_PREFIX(TemplatePrefix, RequiredAPI, ShaderClass, Frequency)
#define IMPLEMENT_SHADER_TYPE_CONSTRUCTOR(ShaderClass, InShaderTypeForDynamicCast, InShaderClassUserFriendlyName)
#define IMPLEMENT_SHADER_TYPE_WITH_DEBUG_NAME(TemplatePrefix, ShaderClass, SourceFilename, FunctionName, Frequency)
A macro to implement a shader type.
#define IMPLEMENT_SHADERPIPELINE_TYPE_MSASPS(PipelineName, MeshShaderType, AmplificationShaderType, PixelShaderType, bRemoveUnused)
#define IMPLEMENT_SHADERPIPELINE_TYPE_MSPS(PipelineName, MeshShaderType, PixelShaderType, bRemoveUnused)
#define IMPLEMENT_SHADERPIPELINE_TYPE_VS(PipelineName, VertexShaderType, bRemoveUnused)
#define IMPLEMENT_SHADERPIPELINE_TYPE_VSGS(PipelineName, VertexShaderType, GeometryShaderType, bRemoveUnused)
#define IMPLEMENT_SHADERPIPELINE_TYPE_VSGSPS(PipelineName, VertexShaderType, GeometryShaderType, PixelShaderType, bRemoveUnused)
#define IMPLEMENT_SHADERPIPELINE_TYPE_VSPS(PipelineName, VertexShaderType, PixelShaderType, bRemoveUnused)
#define INTERNAL_DECLARE_SHADER_TYPE_COMMON(ShaderClass, ShaderMetaTypeShortcut, RequiredAPI)
#define SHADER_DECLARE_EDITOR_VTABLE(ShaderClass)
#define SHADER_DECLARE_VTABLE(ShaderClass)
#define SHADER_TYPE_EDITOR_PERMUTATION_METADATA(ShaderClass)
#define SHADER_TYPE_EDITOR_VTABLE(ShaderClass)
#define SHADER_TYPE_ENTRY(Name)
#define SHADER_TYPE_ENTRY(Name)
#define SHADER_TYPE_LIST
#define SHADER_TYPE_VTABLE(ShaderClass)
Typedefs
using FShaderMapAssetPaths = TSet<FName>
using FShaderPermutation = TShaderTypePermutation<FShaderType>
typedef uint32(* TRaytracingPayloadSizeFunction) ()
template<typename ShaderType>
using TShaderRef = TShaderRefBase<ShaderType, FShaderMapPointerTable>
Enumerations
enum class EShaderPermutationPrecacheRequest : uint8 { Precached , NotPrecached , NotUsed }
Functions
DECLARE_DELEGATE_EightParams (FShaderListReport, const TCHAR *, const TCHAR *, const TCHAR *, const TCHAR *, uint32, uint32, const TCHAR *, void *)
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template<>, TIndexedPtr< FShaderType >, RENDERCORE_API)
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template<>, TIndexedPtr< FVertexFactoryType >, RENDERCORE_API)
void DispatchComputeShader (FRHIComputeCommandList &RHICmdList, const TShaderRef< FShader > &Shader, uint32 ThreadGroupCountX, uint32 ThreadGroupCountY, uint32 ThreadGroupCountZ)
RENDERCORE_API void DispatchComputeShader (FRHIComputeCommandList &RHICmdList, FShader *Shader, uint32 ThreadGroupCountX, uint32 ThreadGroupCountY, uint32 ThreadGroupCountZ)
Helper function to dispatch a compute shader while checking that parameters have been set correctly.
RENDERCORE_API void DispatchIndirectComputeShader (FRHIComputeCommandList &RHICmdList, FShader *Shader, FRHIBuffer *ArgumentBuffer, uint32 ArgumentOffset)
Helper function to dispatch a compute shader indirectly while checking that parameters have been set correctly.
RENDERCORE_API void DumpShaderPipelineStats (EShaderPlatform Platform)
Dumps shader pipeline stats to the log.
RENDERCORE_API void DumpShaderStats (EShaderPlatform Platform, EShaderFrequency Frequency)
Dumps shader stats to the log.
RENDERCORE_API FShaderType * FindShaderTypeByName (const FHashedName &ShaderTypeName)
Finds the shader type with a given name.
int16 GetParameterIndex (const FShaderParameterBindings::FBindlessResourceParameter &Parameter)
int16 GetParameterIndex (const FShaderParameterBindings::FParameterStructReference &Parameter)
int16 GetParameterIndex (const FShaderParameterBindings::FResourceParameter &Parameter)
RENDERCORE_API uint32 GetRayTracingPayloadTypeMaxSize (ERayTracingPayloadType PayloadType)
RENDERCORE_API EShaderPermutationFlags GetShaderPermutationFlags (const FPlatformTypeLayoutParameters &LayoutParams)
Get the shader permutation flags associated with a platform layout.
RENDERCORE_API const FTypeLayoutDesc & GetTypeLayoutDesc (const FPointerTableBase *PtrTable, const FShader &Shader)
RENDERCORE_API void Freeze::IntrinsicToString (const TIndexedPtr< FShaderType > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
RENDERCORE_API void Freeze::IntrinsicToString (const TIndexedPtr< FVertexFactoryType > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
RENDERCORE_API bool IsDxcEnabledForPlatform (EShaderPlatform Platform, bool bHlslVersion2021=false)
Returns whether DirectXShaderCompiler (DXC) is enabled for the specified shader platform.
RENDERCORE_API bool IsUsingEmulatedUniformBuffers (EShaderPlatform Platform)
Returns whether the platform is using emulated uniform buffers.
FString LexToString (FShaderType::EShaderTypeForDynamicCast ShaderType)
constexpr bool operator! (ERayTracingPayloadType E)
constexpr ERayTracingPayloadType operator& (ERayTracingPayloadType Lhs, ERayTracingPayloadType Rhs)
ERayTracingPayloadType & operator&= (ERayTracingPayloadType &Lhs, ERayTracingPayloadType Rhs)
bool operator< (const FShaderPipeline &Lhs, const FShaderPipeline &Rhs)
constexpr ERayTracingPayloadType operator^ (ERayTracingPayloadType Lhs, ERayTracingPayloadType Rhs)
ERayTracingPayloadType & operator^= (ERayTracingPayloadType &Lhs, ERayTracingPayloadType Rhs)
constexpr ERayTracingPayloadType operator| (ERayTracingPayloadType Lhs, ERayTracingPayloadType Rhs)
ERayTracingPayloadType & operator|= (ERayTracingPayloadType &Lhs, ERayTracingPayloadType Rhs)
constexpr ERayTracingPayloadType operator~ (ERayTracingPayloadType E)
RENDERCORE_API void RegisterRayTracingPayloadType (ERayTracingPayloadType PayloadType, uint32 PayloadSize, TRaytracingPayloadSizeFunction PayloadSizeFunction)
RENDERCORE_API void SetAdditionalShaderPermutationFlags (EShaderPermutationFlags AdditionalFlags)
Set global additional flags that are always added in GetShaderPermutationFlags().
RENDERCORE_API void ShaderMapAppendKey (EShaderPlatform Platform, FShaderKeyGenerator &KeyGen)
RENDERCORE_API void ShaderMapAppendKeyString (EShaderPlatform Platform, FString &KeyString)
Appends to KeyString for all shaders.
Variables
const int32 kUniqueShaderPermutationId = 0
Macro Definition Documentation
DECLARE_EXPORTED_SHADER_TYPE
#define DECLARE_EXPORTED_SHADER_TYPE (ShaderClass, ShaderMetaTypeShortcut, RequiredAPI, ...)
Value:
    INTERNAL_DECLARE_SHADER_TYPE_COMMON(ShaderClass, ShaderMetaTypeShortcut, RequiredAPI); \
    DECLARE_EXPORTED_TYPE_LAYOUT(ShaderClass, RequiredAPI, NonVirtual); \
    public:
A macro to declare a new shader type.
This should be called in the class body of the new shader type.
Parameters
ShaderClass - The name of the class representing an instance of the shader type.
ShaderMetaTypeShortcut - The shortcut for the shader meta type: simple, material, meshmaterial, etc. The shader meta type controls
Definition at line 1713 of file Shader.h.
DECLARE_SHADER_TYPE
#define DECLARE_SHADER_TYPE (ShaderClass, ShaderMetaTypeShortcut, ...)
Value:
    DECLARE_EXPORTED_SHADER_TYPE(ShaderClass,ShaderMetaTypeShortcut,, ##__VA_ARGS__)
Definition at line 1718 of file Shader.h.
DECLARE_SHADER_TYPE_EXPLICIT_BASES
#define DECLARE_SHADER_TYPE_EXPLICIT_BASES (ShaderClass, ShaderMetaTypeShortcut, ...)
Value:
    INTERNAL_DECLARE_SHADER_TYPE_COMMON(ShaderClass, ShaderMetaTypeShortcut,); \
    DECLARE_EXPORTED_TYPE_LAYOUT_EXPLICIT_BASES(ShaderClass,, NonVirtual, __VA_ARGS__); \
    public:
Definition at line 1721 of file Shader.h.
IMPLEMENT_RT_PAYLOAD_TYPE
#define IMPLEMENT_RT_PAYLOAD_TYPE (PayloadType, PayloadSize)
Value:
static FRegisterRayTracingPayloadTypeHelper IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT(PayloadHelper, __COUNTER__) = FRegisterRayTracingPayloadTypeHelper(PayloadType, PayloadSize, nullptr);
Definition at line 332 of file Shader.h.
IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT
#define IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT (x, y)
Value:
IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT2(x, y)
Definition at line 331 of file Shader.h.
IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT2
#define IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT2 (x, y)
Value:
x##y
Definition at line 330 of file Shader.h.
IMPLEMENT_RT_PAYLOAD_TYPE_FUNCTION
#define IMPLEMENT_RT_PAYLOAD_TYPE_FUNCTION (PayloadType, PayloadSizeFunction)
Value:
static FRegisterRayTracingPayloadTypeHelper IMPLEMENT_RT_PAYLOAD_TYPE_CONCAT(PayloadHelper, __COUNTER__) = FRegisterRayTracingPayloadTypeHelper(PayloadType, 0u, PayloadSizeFunction);
Definition at line 333 of file Shader.h.
IMPLEMENT_SHADER_TYPE
#define IMPLEMENT_SHADER_TYPE (TemplatePrefix, ShaderClass, SourceFilename, FunctionName, Frequency)
Value:
    IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, ShaderClass); \
    TemplatePrefix \
    ShaderClass::ShaderMetaType& ShaderClass::GetStaticType() \
    { \
        static ShaderClass::ShaderMetaType StaticType( \
            ShaderClass::StaticGetTypeLayout(), \
            TEXT(#ShaderClass), \
            SourceFilename, \
            FunctionName, \
            Frequency, \
            ShaderClass::FPermutationDomain::PermutationCount, \
            SHADER_TYPE_VTABLE(ShaderClass), \
            sizeof(ShaderClass), \
            ShaderClass::GetRootParametersMetadata() \
            SHADER_TYPE_EDITOR_PERMUTATION_METADATA(ShaderClass) \
        ); \
        return StaticType; \
    } \
    TemplatePrefix FShaderTypeRegistration ShaderClass::ShaderTypeRegistration{TFunctionRef<::FShaderType&()>{ShaderClass::GetStaticType}};
A macro to implement a shader type.
Definition at line 1754 of file Shader.h.
IMPLEMENT_SHADER_TYPE2
#define IMPLEMENT_SHADER_TYPE2 (ShaderClass, Frequency)
Value:
    IMPLEMENT_SHADER_TYPE2_WITH_TEMPLATE_PREFIX(template<>, ShaderClass, Frequency)
Definition at line 1819 of file Shader.h.
IMPLEMENT_SHADER_TYPE2_WITH_TEMPLATE_PREFIX
#define IMPLEMENT_SHADER_TYPE2_WITH_TEMPLATE_PREFIX (TemplatePrefix, ShaderClass, Frequency)
Value:
    IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, ShaderClass); \
    TemplatePrefix \
    ShaderClass::ShaderMetaType& ShaderClass::GetStaticType() \
    { \
        static ShaderClass::ShaderMetaType StaticType( \
            ShaderClass::StaticGetTypeLayout(), \
            TEXT(#ShaderClass), \
            ShaderClass::GetSourceFilename(), \
            ShaderClass::GetFunctionName(), \
            Frequency, \
            ShaderClass::FPermutationDomain::PermutationCount, \
            SHADER_TYPE_VTABLE(ShaderClass), \
            sizeof(ShaderClass), \
            ShaderClass::GetRootParametersMetadata() \
            SHADER_TYPE_EDITOR_PERMUTATION_METADATA(ShaderClass) \
        ); \
        return StaticType; \
    } \
    TemplatePrefix FShaderTypeRegistration ShaderClass::ShaderTypeRegistration{TFunctionRef<::FShaderType&()>{ShaderClass::GetStaticType}};
A macro to implement a templated shader type, the function name and the source filename comes from the class.
Definition at line 1798 of file Shader.h.
IMPLEMENT_SHADER_TYPE3
#define IMPLEMENT_SHADER_TYPE3 (ShaderClass, Frequency)
Value:
    IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(,ShaderClass); \
    ShaderClass::ShaderMetaType& ShaderClass::GetStaticType() \
    { \
        static ShaderClass::ShaderMetaType StaticType( \
            ShaderClass::StaticGetTypeLayout(), \
            TEXT(#ShaderClass), \
            ShaderClass::GetSourceFilename(), \
            ShaderClass::GetFunctionName(), \
            Frequency, \
            ShaderClass::FPermutationDomain::PermutationCount, \
            SHADER_TYPE_VTABLE(ShaderClass), \
            sizeof(ShaderClass), \
            ShaderClass::GetRootParametersMetadata() \
            SHADER_TYPE_EDITOR_PERMUTATION_METADATA(ShaderClass) \
        ); \
        return StaticType; \
    } \
    FShaderTypeRegistration ShaderClass::ShaderTypeRegistration{TFunctionRef<::FShaderType&()>{ShaderClass::GetStaticType}};
todo: this should replace IMPLEMENT_SHADER_TYPE
Definition at line 1823 of file Shader.h.
IMPLEMENT_SHADER_TYPE4_WITH_TEMPLATE_PREFIX
#define IMPLEMENT_SHADER_TYPE4_WITH_TEMPLATE_PREFIX (TemplatePrefix, RequiredAPI, ShaderClass, Frequency)
Value:
    IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, ShaderClass); \
    TemplatePrefix RequiredAPI \
    ShaderClass::ShaderMetaType& ShaderClass::GetStaticType() \
    { \
        static ShaderClass::ShaderMetaType StaticType( \
            ShaderClass::StaticGetTypeLayout(), \
            TEXT(#ShaderClass), \
            ShaderClass::GetSourceFilename(), \
            ShaderClass::GetFunctionName(), \
            Frequency, \
            ShaderClass::FPermutationDomain::PermutationCount, \
            SHADER_TYPE_VTABLE(ShaderClass), \
            sizeof(ShaderClass), \
            ShaderClass::GetRootParametersMetadata() \
            SHADER_TYPE_EDITOR_PERMUTATION_METADATA(ShaderClass) \
        ); \
        return StaticType; \
    } \
    TemplatePrefix FShaderTypeRegistration ShaderClass::ShaderTypeRegistration{TFunctionRef<::FShaderType&()>{ShaderClass::GetStaticType}};
Definition at line 1844 of file Shader.h.
IMPLEMENT_SHADER_TYPE_CONSTRUCTOR
#define IMPLEMENT_SHADER_TYPE_CONSTRUCTOR (ShaderClass, InShaderTypeForDynamicCast, InShaderClassUserFriendlyName)
Definition at line 1867 of file Shader.h.
IMPLEMENT_SHADER_TYPE_WITH_DEBUG_NAME
#define IMPLEMENT_SHADER_TYPE_WITH_DEBUG_NAME (TemplatePrefix, ShaderClass, SourceFilename, FunctionName, Frequency)
Value:
    IMPLEMENT_UNREGISTERED_TEMPLATE_TYPE_LAYOUT(TemplatePrefix, ShaderClass); \
    TemplatePrefix \
    typename ShaderClass::ShaderMetaType& ShaderClass::GetStaticType() \
    { \
        static typename ShaderClass::ShaderMetaType StaticType( \
            ShaderClass::StaticGetTypeLayout(), \
            ShaderClass::GetDebugName(), \
            SourceFilename, \
            FunctionName, \
            Frequency, \
            ShaderClass::FPermutationDomain::PermutationCount, \
            SHADER_TYPE_VTABLE(ShaderClass), \
            sizeof(ShaderClass), \
            ShaderClass::GetRootParametersMetadata() \
            SHADER_TYPE_EDITOR_PERMUTATION_METADATA(ShaderClass) \
        ); \
        return StaticType; \
    } \
    TemplatePrefix FShaderTypeRegistration ShaderClass::ShaderTypeRegistration{TFunctionRef<::FShaderType&()>{ShaderClass::GetStaticType}};
A macro to implement a shader type.
Shader name is got from GetDebugName(), which is helpful for templated shaders.
Definition at line 1776 of file Shader.h.
IMPLEMENT_SHADERPIPELINE_TYPE_MSASPS
#define IMPLEMENT_SHADERPIPELINE_TYPE_MSASPS (PipelineName, MeshShaderType, AmplificationShaderType, PixelShaderType, bRemoveUnused)
Value:
    static FShaderPipelineType PipelineName(TEXT(PREPROCESSOR_TO_STRING(PipelineName)), &MeshShaderType::GetStaticType(), &AmplificationShaderType::GetStaticType(), &PixelShaderType::GetStaticType(), true, bRemoveUnused);
Definition at line 2064 of file Shader.h.
IMPLEMENT_SHADERPIPELINE_TYPE_MSPS
#define IMPLEMENT_SHADERPIPELINE_TYPE_MSPS (PipelineName, MeshShaderType, PixelShaderType, bRemoveUnused)
Value:
    static FShaderPipelineType PipelineName(TEXT(PREPROCESSOR_TO_STRING(PipelineName)), &MeshShaderType::GetStaticType(), nullptr, &PixelShaderType::GetStaticType(), true, bRemoveUnused);
Definition at line 2061 of file Shader.h.
IMPLEMENT_SHADERPIPELINE_TYPE_VS
#define IMPLEMENT_SHADERPIPELINE_TYPE_VS (PipelineName, VertexShaderType, bRemoveUnused)
Value:
    static FShaderPipelineType PipelineName(TEXT(PREPROCESSOR_TO_STRING(PipelineName)), &VertexShaderType::GetStaticType(), nullptr, nullptr, false, bRemoveUnused);
Definition at line 2051 of file Shader.h.
IMPLEMENT_SHADERPIPELINE_TYPE_VSGS
#define IMPLEMENT_SHADERPIPELINE_TYPE_VSGS (PipelineName, VertexShaderType, GeometryShaderType, bRemoveUnused)
Value:
    static FShaderPipelineType PipelineName(TEXT(PREPROCESSOR_TO_STRING(PipelineName)), &VertexShaderType::GetStaticType(), &GeometryShaderType::GetStaticType(), nullptr, false, bRemoveUnused);
Definition at line 2057 of file Shader.h.
IMPLEMENT_SHADERPIPELINE_TYPE_VSGSPS
#define IMPLEMENT_SHADERPIPELINE_TYPE_VSGSPS (PipelineName, VertexShaderType, GeometryShaderType, PixelShaderType, bRemoveUnused)
Value:
    static FShaderPipelineType PipelineName(TEXT(PREPROCESSOR_TO_STRING(PipelineName)), &VertexShaderType::GetStaticType(), &GeometryShaderType::GetStaticType(), &PixelShaderType::GetStaticType(), false, bRemoveUnused);
Definition at line 2054 of file Shader.h.
IMPLEMENT_SHADERPIPELINE_TYPE_VSPS
#define IMPLEMENT_SHADERPIPELINE_TYPE_VSPS (PipelineName, VertexShaderType, PixelShaderType, bRemoveUnused)
Value:
    static FShaderPipelineType PipelineName(TEXT(PREPROCESSOR_TO_STRING(PipelineName)), &VertexShaderType::GetStaticType(), nullptr, &PixelShaderType::GetStaticType(), false, bRemoveUnused);
Definition at line 2048 of file Shader.h.
INTERNAL_DECLARE_SHADER_TYPE_COMMON
#define INTERNAL_DECLARE_SHADER_TYPE_COMMON (ShaderClass, ShaderMetaTypeShortcut, RequiredAPI)
Value:
    public: \
    using ShaderMetaType = F##ShaderMetaTypeShortcut##ShaderType; \
    using ShaderMapType = F##ShaderMetaTypeShortcut##ShaderMap; \
    \
    static RequiredAPI ShaderMetaType& GetStaticType(); \
    private: \
    static FShaderTypeRegistration ShaderTypeRegistration; \
    public: \
    \
    SHADER_DECLARE_VTABLE(ShaderClass)
Definition at line 1695 of file Shader.h.
SHADER_DECLARE_EDITOR_VTABLE
#define SHADER_DECLARE_EDITOR_VTABLE (ShaderClass)
Value:
        static void ModifyCompilationEnvironmentImpl(const FShaderPermutationParameters& Parameters, FShaderCompilerEnvironment& OutEnvironment) \
        { \
            const typename ShaderClass::FPermutationDomain PermutationVector(Parameters.PermutationId); \
            PermutationVector.ModifyCompilationEnvironment(OutEnvironment); \
            ShaderClass::ModifyCompilationEnvironment(static_cast<const typename ShaderClass::FPermutationParameters&>(Parameters), OutEnvironment); \
        } \
        static void GetPermutationIdStringImpl(int32 PermutationId, FString& OutString, bool bFullNames) \
        { \
            const typename ShaderClass::FPermutationDomain PermutationVector(PermutationId); \
            UE::ShaderPermutationUtils::FormatPermutationDomain(PermutationVector, OutString, bFullNames, nullptr); \
        }
Definition at line 1668 of file Shader.h.
SHADER_DECLARE_VTABLE
#define SHADER_DECLARE_VTABLE (ShaderClass)
Value:
    static FShader* ConstructSerializedInstance() { return new ShaderClass(); } \
    static FShader* ConstructCompiledInstance(const typename FShader::CompiledShaderInitializerType& Initializer) \
    { return new ShaderClass(static_cast<const typename ShaderMetaType::CompiledShaderInitializerType&>(Initializer)); }\
    static bool ShouldCompilePermutationImpl(const FShaderPermutationParameters& Parameters) \
    { return ShaderClass::ShouldCompilePermutation(static_cast<const typename ShaderClass::FPermutationParameters&>(Parameters)); } \
    static EShaderPermutationPrecacheRequest ShouldPrecachePermutationImpl(const FShaderPermutationParameters& Parameters) \
    { return ShaderClass::ShouldPrecachePermutation(static_cast<const typename ShaderClass::FPermutationParameters&>(Parameters)); } \
    SHADER_DECLARE_EDITOR_VTABLE(ShaderClass)
Definition at line 1684 of file Shader.h.
SHADER_TYPE_EDITOR_PERMUTATION_METADATA
#define SHADER_TYPE_EDITOR_PERMUTATION_METADATA (ShaderClass)
Value:
    , ShaderClass::GetPermutationIdStringImpl
Definition at line 1733 of file Shader.h.
SHADER_TYPE_EDITOR_VTABLE
#define SHADER_TYPE_EDITOR_VTABLE (ShaderClass)
Value:
    , ShaderClass::ModifyCompilationEnvironmentImpl \
    , ShaderClass::ValidateCompiledResult \
    , ShaderClass::GetOverrideJobPriority
Definition at line 1728 of file Shader.h.
SHADER_TYPE_ENTRY [1/2]
#define SHADER_TYPE_ENTRY (Name)
Value:
Name
Definition at line 1263 of file Shader.h.
SHADER_TYPE_ENTRY [2/2]
#define SHADER_TYPE_ENTRY (Name)
Value:
TEXT(#Name)
Definition at line 1263 of file Shader.h.
SHADER_TYPE_LIST
#define SHADER_TYPE_LIST
Value:
    SHADER_TYPE_ENTRY(Global), \
    SHADER_TYPE_ENTRY(Material), \
    SHADER_TYPE_ENTRY(MeshMaterial), \
    SHADER_TYPE_ENTRY(Niagara), \
    SHADER_TYPE_ENTRY(OCIO), \
    SHADER_TYPE_ENTRY(ComputeKernel), \
    SHADER_TYPE_ENTRY(NNERuntimeIREE),
Definition at line 1245 of file Shader.h.
Referenced by LexToString().
SHADER_TYPE_VTABLE
#define SHADER_TYPE_VTABLE (ShaderClass)
Value:
    ShaderClass::ConstructSerializedInstance, \
    ShaderClass::ConstructCompiledInstance, \
    ShaderClass::ShouldCompilePermutationImpl, \
    ShaderClass::ShouldPrecachePermutationImpl, \
    ShaderClass::GetRayTracingPayloadType, \
    ShaderClass::GetShaderBindingLayout \
    SHADER_TYPE_EDITOR_VTABLE(ShaderClass)
Definition at line 1743 of file Shader.h.
Typedef Documentation
FShaderMapAssetPaths
using FShaderMapAssetPaths = TSet<FName>
Definition at line 88 of file Shader.h.
FShaderPermutation
using FShaderPermutation = TShaderTypePermutation<FShaderType>
Definition at line 119 of file Shader.h.
TRaytracingPayloadSizeFunction
typedef uint32(* TRaytracingPayloadSizeFunction) ()
Definition at line 316 of file Shader.h.
TShaderRef
template<typename ShaderType> using TShaderRef = TShaderRefBase<ShaderType, FShaderMapPointerTable>
Definition at line 1243 of file Shader.h.
Enumeration Type Documentation
EShaderPermutationPrecacheRequest
enum class EShaderPermutationPrecacheRequest : uint8 strong
Enumerator
Precached
NotPrecached
NotUsed
Definition at line 823 of file Shader.h.
Function Documentation
DECLARE_DELEGATE_EightParams()
DECLARE_DELEGATE_EightParams (FShaderListReport , const TCHAR * , const TCHAR * , const TCHAR * , const TCHAR * , uint32 , uint32 , const TCHAR * , void *)
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT() [1/2]
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template<> , TIndexedPtr< FShaderType > , RENDERCORE_API)
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT() [2/2]
DECLARE_EXPORTED_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template<> , TIndexedPtr< FVertexFactoryType > , RENDERCORE_API)
DispatchComputeShader() [1/2]
void DispatchComputeShader (FRHIComputeCommandList & RHICmdList, const TShaderRef< FShader > & Shader, uint32 ThreadGroupCountX, uint32 ThreadGroupCountY, uint32 ThreadGroupCountZ) inline
Definition at line 2731 of file Shader.h.
References DispatchComputeShader(), and TShaderRefBase< ShaderType, PointerTableType >::GetShader().
DispatchComputeShader() [2/2]
RENDERCORE_API void DispatchComputeShader (FRHIComputeCommandList & RHICmdList, FShader * Shader, uint32 ThreadGroupCountX, uint32 ThreadGroupCountY, uint32 ThreadGroupCountZ) extern
Helper function to dispatch a compute shader while checking that parameters have been set correctly.
Referenced by DispatchComputeShader().
DispatchIndirectComputeShader()
RENDERCORE_API void DispatchIndirectComputeShader (FRHIComputeCommandList & RHICmdList, FShader * Shader, FRHIBuffer * ArgumentBuffer, uint32 ArgumentOffset) extern
Helper function to dispatch a compute shader indirectly while checking that parameters have been set correctly.
DumpShaderPipelineStats()
RENDERCORE_API void DumpShaderPipelineStats (EShaderPlatform Platform) extern
Dumps shader pipeline stats to the log.
Does not include material (eg shader pipeline instance) information.
Parameters
Platform - Platform to dump shader info for, use SP_NumPlatforms for all
References Platform.
DumpShaderStats()
RENDERCORE_API void DumpShaderStats (EShaderPlatform Platform, EShaderFrequency Frequency) extern
Dumps shader stats to the log.
Will also print some shader pipeline information.
Parameters
Platform - Platform to dump shader info for, use SP_NumPlatforms for all
Frequency - Whether to dump PS or VS info, use SF_NumFrequencies to dump both
References Frequency, and Platform.
FindShaderTypeByName()
RENDERCORE_API FShaderType * FindShaderTypeByName (const FHashedName & ShaderTypeName) extern
Finds the shader type with a given name.
Parameters
ShaderTypeName - The name of the shader type to find.
Returns
The shader type, or NULL if none matched.
GetParameterIndex() [1/3]
int16 GetParameterIndex (const FShaderParameterBindings::FBindlessResourceParameter & Parameter) inline
Definition at line 820 of file Shader.h.
GetParameterIndex() [2/3]
int16 GetParameterIndex (const FShaderParameterBindings::FParameterStructReference & Parameter) inline
Definition at line 821 of file Shader.h.
GetParameterIndex() [3/3]
int16 GetParameterIndex (const FShaderParameterBindings::FResourceParameter & Parameter) inline
Definition at line 819 of file Shader.h.
Referenced by CollectSRVsToUnset(), and CollectUAVsToUnset().
GetRayTracingPayloadTypeMaxSize()
RENDERCORE_API uint32 GetRayTracingPayloadTypeMaxSize (ERayTracingPayloadType PayloadType)
GetShaderPermutationFlags()
RENDERCORE_API EShaderPermutationFlags GetShaderPermutationFlags (const FPlatformTypeLayoutParameters & LayoutParams)
Get the shader permutation flags associated with a platform layout.
Referenced by FMaterialShaderMapId::GetPermutationFlags().
GetTypeLayoutDesc()
RENDERCORE_API const FTypeLayoutDesc & GetTypeLayoutDesc (const FPointerTableBase * PtrTable, const FShader & Shader)
IsDxcEnabledForPlatform()
RENDERCORE_API bool IsDxcEnabledForPlatform (EShaderPlatform Platform, bool bHlslVersion2021 = false) extern
Returns whether DirectXShaderCompiler (DXC) is enabled for the specified shader platform.
See console variables "r.OpenGL.ForceDXC", "r.D3D.ForceDXC".
References Platform.
IsUsingEmulatedUniformBuffers()
RENDERCORE_API bool IsUsingEmulatedUniformBuffers (EShaderPlatform Platform) extern
Returns whether the platform is using emulated uniform buffers.
References Platform.
LexToString()
FString LexToString (FShaderType::EShaderTypeForDynamicCast ShaderType) inline
Definition at line 1601 of file Shader.h.
References checkf, FShaderType::NumShaderTypes, SHADER_TYPE_LIST, and TEXT.
operator!()
bool operator! (ERayTracingPayloadType E) inline constexpr
Definition at line 317 of file Shader.h.
operator&()
ERayTracingPayloadType operator& (ERayTracingPayloadType Lhs, ERayTracingPayloadType Rhs) inline constexpr
Definition at line 317 of file Shader.h.
operator&=()
ERayTracingPayloadType & operator&= (ERayTracingPayloadType & Lhs, ERayTracingPayloadType Rhs) inline
Definition at line 317 of file Shader.h.
operator<()
bool operator< (const FShaderPipeline & Lhs, const FShaderPipeline & Rhs) inline
Definition at line 2297 of file Shader.h.
operator^()
ERayTracingPayloadType operator^ (ERayTracingPayloadType Lhs, ERayTracingPayloadType Rhs) inline constexpr
Definition at line 317 of file Shader.h.
operator^=()
ERayTracingPayloadType & operator^= (ERayTracingPayloadType & Lhs, ERayTracingPayloadType Rhs) inline
Definition at line 317 of file Shader.h.
operator|()
ERayTracingPayloadType operator| (ERayTracingPayloadType Lhs, ERayTracingPayloadType Rhs) inline constexpr
Definition at line 317 of file Shader.h.
operator|=()
ERayTracingPayloadType & operator|= (ERayTracingPayloadType & Lhs, ERayTracingPayloadType Rhs) inline
Definition at line 317 of file Shader.h.
operator~()
ERayTracingPayloadType operator~ (ERayTracingPayloadType E) inline constexpr
Definition at line 317 of file Shader.h.
RegisterRayTracingPayloadType()
RENDERCORE_API void RegisterRayTracingPayloadType (ERayTracingPayloadType PayloadType, uint32 PayloadSize, TRaytracingPayloadSizeFunction PayloadSizeFunction)
Referenced by FRegisterRayTracingPayloadTypeHelper::FRegisterRayTracingPayloadTypeHelper().
SetAdditionalShaderPermutationFlags()
RENDERCORE_API void SetAdditionalShaderPermutationFlags (EShaderPermutationFlags AdditionalFlags)
Set global additional flags that are always added in GetShaderPermutationFlags().
Expected to be called once at startup.
ShaderMapAppendKey()
RENDERCORE_API void ShaderMapAppendKey (EShaderPlatform Platform, FShaderKeyGenerator & KeyGen) extern
References Platform.
ShaderMapAppendKeyString()
RENDERCORE_API void ShaderMapAppendKeyString (EShaderPlatform Platform, FString & KeyString) extern
Appends to KeyString for all shaders.
References Platform.
Variable Documentation
kUniqueShaderPermutationId
const int32 kUniqueShaderPermutationId = 0 inline
Definition at line 121 of file Shader.h.