Unreal Engine 5.6 C++ API: AWorldSettings Class Reference
AWorldSettings Class Reference
#include "WorldSettings.h"
Public Member Functions
virtual void AddAssetUserData (UAssetUserData *InUserData) override
class UBookmarkBase * AddBookmark (const TSubclassOf< UBookmarkBase > BookmarkClass, const bool bExpandIfNecessary)
Creates and adds a new bookmark of a different class.
void ApplyWorldPartitionForcedSettings ()
bool AreWorldBoundsChecksEnabled () const
virtual bool CanDeleteSelectedActor (FText &OutReason) const override
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual bool CanReplaceSelectedActor (FText &OutReason) const override
virtual void CheckForErrors () override
void ClearAllBookmarks ()
Clears all references to current bookmarks.
void ClearBookmark (const uint32 BookmarkIndex)
Clears the reference to the bookmark from the specified index.
void CompactBookmarks ()
Attempts to move bookmarks such that all bookmarks are adjacent in memory.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnBookmarkClassChanged, AWorldSettings *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDefaultBookmarkChanged, AWorldSettings *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNaniteSettingsChanged, AWorldSettings *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNumberOfBookmarksChanged, AWorldSettings *)
virtual float FixupDeltaSeconds (float DeltaSeconds, float RealDeltaSeconds)
Returns the delta time to be used by the tick.
virtual FSoftClassPath GetAISystemClassName () const
virtual const TArray< UAssetUserData * > * GetAssetUserDataArray () const override
virtual UAssetUserData * GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
const TArray< class UBookmarkBase * > & GetBookmarks () const
Gets the array of bookmarks.
class UBookmarkBase * GetDefaultBookmark () const
Get the bookmark that will be applied when the map is opened in the editor.
TSubclassOf< class UBookmarkBase > GetDefaultBookmarkClass () const
const FWorldPartitionPerWorldSettings * GetDefaultWorldPartitionSettings () const
virtual float GetEffectiveTimeDilation () const
Multiplies all time dilation sources together and returns the effective overall time dilation.
virtual float GetGravityZ () const
Returns the Z component of the current world gravity and initializes it to the default gravity if called for the first time.
UMaterialInterface * GetHierarchicalLODBaseMaterial () const
TArray< FHierarchicalSimplification > & GetHierarchicalLODSetup ()
const TArray< FHierarchicalSimplification > & GetHierarchicalLODSetup () const
const int32 GetMaxNumberOfBookmarks () const
UNavigationSystemConfig *const GetNavigationSystemConfig () const
const UNavigationSystemConfig * GetNavigationSystemConfigOverride () const
int32 GetNumHierarchicalLODLevels () const
class UBookmarkBase * GetOrAddBookmark (const uint32 BookmarkIndex, const bool bRecreateOnClassMismatch)
Gets the bookmark at the specified index, creating it if a bookmark doesn't exist.
FORCEINLINE class APlayerState * GetPauserPlayerState () const
virtual TSubclassOf< class UPhysicsCollisionHandler > GetPhysicsCollisionHandlerClass ()
UWorldPartition * GetWorldPartition () const
bool IsAISystemEnabled () const
bool IsNavigationSystemEnabled () const
bool IsPartitionedWorld () const
virtual bool IsSelectable () const override
virtual void NotifyBeginPlay ()
Called from GameStateBase, calls BeginPlay on all actors.
virtual void NotifyMatchStarted ()
Called from GameStateBase, used to notify native classes of match startup (such as level scripting)
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PostRegisterAllComponents () override
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent) override
virtual void PreInitializeComponents () override
virtual void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
void ResetDefaultWorldPartitionSettings ()
void ResetHierarchicalLODSetup ()
virtual void RewindForReplay () override
void SaveDefaultWorldPartitionSettings ()
virtual void SetAllowMaskedMaterials (bool bState)
virtual void SetAllowTimeDilation (bool NewAllowTimeDilation)
Sets whether or not Time Dilation is allowed.
virtual float SetCinematicTimeDilation (float NewCinematicTimeDilation)
Sets the cinematic time dilation value (subject to clamping).
void SetDefaultBookmark (class UBookmarkBase *InDefaultBookmark)
Set the bookmark that will be applied when the map is opened in the editor.
void SetNavigationSystemConfigOverride (UNavigationSystemConfig *NewConfig)
Sets a configuration override for NavigationSystem's creation.
virtual FORCEINLINE void SetPauserPlayerState (class APlayerState *PlayerState)
virtual float SetTimeDilation (float NewTimeDilation)
Sets the global time dilation value (subject to clamping).
void SetWorldPartition (UWorldPartition *InWorldPartition)
virtual bool SupportsExternalPackaging () const override
virtual bool SupportsWorldPartitionStreaming () const
void SupportsWorldPartitionStreamingChanged ()
UFUNCTION () 1 virtual void OnRep_NaniteSettings()
UFUNCTION () 1 virtual void OnRep_WorldGravityZ()
UPROPERTY()) uint8 bEnableWorldComposition UPROPERTY() uint8 bUseClientSideLevelStreamingVolumes UPROPERTY()) uint8 bEnableWorldOriginRebasing UPROPERTY() uint8 bWorldGravitySet UPROPERTY ()
Whether to place visibility cells inside Precomputed Visibility Volumes and along camera tracks in this level.
UPROPERTY() uint8 bMinimizeBSPSections UPROPERTY() uint8 bForceNoPrecomputedLighting UPROPERTY() uint8 bForceVolumetricLightmapsOnly UPROPERTY() uint8 bHighPriorityLoading UPROPERTY() uint8 bHighPriorityLoadingLocal UPROPERTY() uint8 bOverrideDefaultBroadphaseSettings UPROPERTY()) uint8 bGenerateSingleClusterForLevel UPROPERTY() uint8 bAllowTimeDilation UPROPERTY() uint8 bReuseAddressAndPort UPROPERTY ()
Causes the BSP build to generate as few sections as possible.
UPROPERTY ()
Range in which volumetric lightmaps will be loaded.
UPROPERTY () FBroadphaseSettings BroadphaseSettings
UPROPERTY () FInteriorSettings DefaultAmbientZoneSettings
Default interior settings applied to sounds that have "apply ambient volumes" set to true on their SoundClass.
UPROPERTY () float CinematicTimeDilation
UPROPERTY () float DemoPlayTimeDilation
UPROPERTY () float TimeDilation
Normally 1 - scales real time passage.
UPROPERTY () float WorldGravityZ
UPROPERTY () float WorldToMeters
scale of 1uu to 1m in real world measurements, for HMD and other physically tracked devices (e.g.
UPROPERTY () FNaniteSettings NaniteSettings
NANITE SETTINGS.
UPROPERTY () FReverbSettings DefaultReverbSettings
AUDIO SETTINGS.
UPROPERTY () FVector DefaultColorScale
Default color scale for the level.
UPROPERTY () FVector LevelInstancePivotOffset
Additional transform applied when applying LevelStreaming Transform to LevelInstance.
UPROPERTY () int32 PackedLightAndShadowMapTextureSize
RENDERING SETTINGS.
UPROPERTY () TArray< struct FNetViewer > ReplicationViewers
valid only during replication - information about the player(s) being replicated to (there could be more than one in the case of a splitscreen client)
UPROPERTY () TArray< TObjectPtr< UDataLayerAsset > > BaseNavmeshDataLayers
A list of runtime data layers that should be included in the base navmesh.
UPROPERTY () TObjectPtr< class USoundMix > DefaultBaseSoundMix
Default Base SoundMix.
UPROPERTY () TSubclassOf< class ADefaultPhysicsVolume > DefaultPhysicsVolumeClass
UPROPERTY () TSubclassOf< class AGameNetworkManager > GameNetworkManagerClass
Class of GameNetworkManager to spawn for network games.
UPROPERTY () TSubclassOf< class UPhysicsCollisionHandler > PhysicsCollisionHandlerClass
UPROPERTY ()) float DefaultMaxDistanceFieldOcclusionDistance
Max occlusion distance used by mesh distance fields, overridden if there is a movable skylight.
UPROPERTY ()) float DynamicIndirectShadowsSelfShadowingIntensity
Controls the intensity of self-shadowing from capsule indirect shadows.
UPROPERTY ()) float GlobalDistanceFieldViewDistance
Distance from the camera that the global distance field should cover.
UPROPERTY ()) float GlobalGravityZ
UPROPERTY ()) float KillZ
UPROPERTY ()) float MaxCinematicTimeDilation
Highest acceptable cinematic time dilation.
UPROPERTY ()) float MaxGlobalTimeDilation
Highest acceptable global time dilation.
UPROPERTY ()) float MaxUndilatedFrameTime
Largest possible frametime, not considering dilation.
UPROPERTY ()) float MinCinematicTimeDilation
Lowest acceptable cinematic time dilation.
UPROPERTY ()) float MinGlobalTimeDilation
Lowest acceptable global time dilation.
UPROPERTY ()) float MinUndilatedFrameTime
Smallest possible frametime, not considering dilation.
UPROPERTY ()) TSubclassOf< class AGameModeBase > DefaultGameMode
GAMEMODE SETTINGS.
UPROPERTY ()) TSubclassOf< UDamageType > KillZDamageType
Data Fields
UPROPERTY() uint8 bMinimizeBSPSections UPROPERTY() uint8 bForceNoPrecomputedLighting UPROPERTY() uint8 bForceVolumetricLightmapsOnly UPROPERTY() uint8 bHighPriorityLoading UPROPERTY() uint8 bHighPriorityLoadingLocal UPROPERTY() uint8 bOverrideDefaultBroadphaseSettings UPROPERTY()) uint8 bGenerateSingleClusterForLevel UPROPERTY() uint8 bAllowTimeDilation UPROPERTY() uint8 bReuseAddressAndPort AdvancedDisplay TSoftClassPtr< UAISystemBase > AISystemClass
UPROPERTY()) uint8 bEnableWorldComposition UPROPERTY() uint8 bUseClientSideLevelStreamingVolumes UPROPERTY()) uint8 bEnableWorldOriginRebasing UPROPERTY() uint8 bWorldGravitySet Category
TUniquePtr< FWorldGridPreviewer > InstancedFoliageGridGridPreviewer
meta
Static Public Attributes
static const uint32 NumMappedBookmarks = 10
The number of bookmarks that will have mapped keyboard shortcuts by default.
static FOnBookmarkClassChanged OnBookmarkClassChanged
static FOnDefaultBookmarkChanged OnDefaultBookmarkChanged
static FOnNaniteSettingsChanged OnNaniteSettingsChanged
static FOnNumberOfBookmarksChanged OnNumberOfBoomarksChanged
Protected Member Functions
UPROPERTY () TArray< TObjectPtr< UAssetUserData > > AssetUserData
Array of user data stored with the asset.
UPROPERTY () TObjectPtr< class APlayerState > PauserPlayerState
UPROPERTY () TObjectPtr< UNavigationSystemConfig > NavigationSystemConfigOverride
Overrides NavigationSystemConfig.
UPROPERTY () TObjectPtr< UWorldPartition > WorldPartition
UPROPERTY ()) TObjectPtr< UNavigationSystemConfig > NavigationSystemConfig
Holds parameters for NavigationSystem's creation.
Private Member Functions
void AdjustNumberOfBookmarks ()
GENERATED_UCLASS_BODY () 1 virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty > &OutLifetimeProps) const override
HIDE_ACTOR_TRANSFORM_FUNCTIONS ()
void InternalPostPropertyChanged (FName PropertyName)
void SanitizeBookmarkClasses ()
virtual void Serialize (FArchive &Ar) override
void UpdateBookmarkClass ()
void UpdateNumberOfBookmarks ()
UPROPERTY () TArray< TObjectPtr< class UBookmarkBase > > BookmarkArray
UPROPERTY () TSubclassOf< class UBookmarkBase > LastBookmarkClass
UPROPERTY ()) int32 MaxNumberOfBookmarks
Maximum number of bookmarks allowed.
UPROPERTY ()) int32 VisibilityCellSize
PRECOMPUTED VISIBILITY SETTINGS.
UPROPERTY ()) TEnumAsByte< enum EVisibilityAggressiveness > VisibilityAggressiveness
Determines how aggressive precomputed visibility should be.
UPROPERTY ()) TSubclassOf< class UBookmarkBase > DefaultBookmarkClass
Class that will be used when creating new bookmarks.
Detailed Description
Definition at line 340 of file WorldSettings.h.
Member Function Documentation
AddAssetUserData()
virtual void AWorldSettings::AddAssetUserData (UAssetUserData * InUserData) override virtual
AddBookmark()
class UBookmarkBase * AWorldSettings::AddBookmark (const TSubclassOf< UBookmarkBase > BookmarkClass, const bool bExpandIfNecessary)
Creates and adds a new bookmark of a different class.
When the bookmark's class is not of the same class as the default bookmark class, the bookmark will be removed on the next update. This will fail if we've overrun MaxNumberOfBookmarks.
Parameters
BookmarkClass Class of the new bookmark.
bExpandIfNecessary Will increase MaxNumberOfBookmarks if there's not enough add another.
Returns
The bookmark that was created. Will be nullptr on failure.
AdjustNumberOfBookmarks()
void AWorldSettings::AdjustNumberOfBookmarks () private
ApplyWorldPartitionForcedSettings()
void AWorldSettings::ApplyWorldPartitionForcedSettings ()
AreWorldBoundsChecksEnabled()
bool AWorldSettings::AreWorldBoundsChecksEnabled () const inline
Returns
whether given world is restricting actors to +-HALF_WORLD_MAX bounds, destroying actors that move below KillZ
Definition at line 869 of file WorldSettings.h.
CanDeleteSelectedActor()
virtual bool AWorldSettings::CanDeleteSelectedActor (FText & OutReason) const override virtual
CanEditChange()
virtual bool AWorldSettings::CanEditChange (const FProperty * InProperty) const override virtual
CanReplaceSelectedActor()
virtual bool AWorldSettings::CanReplaceSelectedActor (FText & OutReason) const override virtual
CheckForErrors()
virtual void AWorldSettings::CheckForErrors () override virtual
ClearAllBookmarks()
void AWorldSettings::ClearAllBookmarks ()
Clears all references to current bookmarks.
ClearBookmark()
void AWorldSettings::ClearBookmark (const uint32 BookmarkIndex)
Clears the reference to the bookmark from the specified index.
CompactBookmarks()
void AWorldSettings::CompactBookmarks ()
Attempts to move bookmarks such that all bookmarks are adjacent in memory.
Note, this will not rearrange any valid Bookmarks inside the mapped range, but may move bookmarks outside that range to fill up mapped bookmarks.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/4]
AWorldSettings::DECLARE_MULTICAST_DELEGATE_OneParam (FOnBookmarkClassChanged , AWorldSettings *)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/4]
AWorldSettings::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDefaultBookmarkChanged , AWorldSettings *)
DECLARE_MULTICAST_DELEGATE_OneParam() [3/4]
AWorldSettings::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNaniteSettingsChanged , AWorldSettings *)
DECLARE_MULTICAST_DELEGATE_OneParam() [4/4]
AWorldSettings::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNumberOfBookmarksChanged , AWorldSettings *)
FixupDeltaSeconds()
virtual float AWorldSettings::FixupDeltaSeconds (float DeltaSeconds, float RealDeltaSeconds) virtual
Returns the delta time to be used by the tick.
Can be overridden if game specific logic is needed.
GENERATED_UCLASS_BODY()
AWorldSettings::GENERATED_UCLASS_BODY () const & override private
GetAISystemClassName()
virtual FSoftClassPath AWorldSettings::GetAISystemClassName () const virtual
GetAssetUserDataArray()
virtual const TArray< UAssetUserData * > * AWorldSettings::GetAssetUserDataArray () const override virtual
Reimplemented from IInterface_AssetUserData.
GetAssetUserDataOfClass()
virtual UAssetUserData * AWorldSettings::GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override virtual
GetBookmarks()
const TArray< class UBookmarkBase * > & AWorldSettings::GetBookmarks () const inline
Gets the array of bookmarks.
It's common for entries to be null as this is treated more like a sparse array.
Definition at line 985 of file WorldSettings.h.
GetDefaultBookmark()
class UBookmarkBase * AWorldSettings::GetDefaultBookmark () const
Get the bookmark that will be applied when the map is opened in the editor.
GetDefaultBookmarkClass()
TSubclassOf< class UBookmarkBase > AWorldSettings::GetDefaultBookmarkClass () const inline
Definition at line 976 of file WorldSettings.h.
GetDefaultWorldPartitionSettings()
const FWorldPartitionPerWorldSettings * AWorldSettings::GetDefaultWorldPartitionSettings () const
GetEffectiveTimeDilation()
virtual float AWorldSettings::GetEffectiveTimeDilation () const inline virtual
Multiplies all time dilation sources together and returns the effective overall time dilation.
When bAllowTimeDilation is set to false, this will return 1.0 regardless of the time dilation sources. See SetAllowTimeDilation(...)/bAllowTimeDilation.
Definition at line 825 of file WorldSettings.h.
GetGravityZ()
virtual float AWorldSettings::GetGravityZ () const virtual
Returns the Z component of the current world gravity and initializes it to the default gravity if called for the first time.
Returns
Z component of current world gravity.
GetHierarchicalLODBaseMaterial()
UMaterialInterface * AWorldSettings::GetHierarchicalLODBaseMaterial () const
GetHierarchicalLODSetup() [1/2]
TArray< FHierarchicalSimplification > & AWorldSettings::GetHierarchicalLODSetup ()
GetHierarchicalLODSetup() [2/2]
const TArray< FHierarchicalSimplification > & AWorldSettings::GetHierarchicalLODSetup () const
GetMaxNumberOfBookmarks()
const int32 AWorldSettings::GetMaxNumberOfBookmarks () const inline
Definition at line 971 of file WorldSettings.h.
GetNavigationSystemConfig()
UNavigationSystemConfig *const AWorldSettings::GetNavigationSystemConfig () const inline
Returns
configuration for NavigationSystem's creation. Null means no navigation system will be created
Definition at line 851 of file WorldSettings.h.
GetNavigationSystemConfigOverride()
const UNavigationSystemConfig * AWorldSettings::GetNavigationSystemConfigOverride () const inline
Returns
current configuration override for NavigationSystem's creation, if any.
Definition at line 860 of file WorldSettings.h.
GetNumHierarchicalLODLevels()
int32 AWorldSettings::GetNumHierarchicalLODLevels () const
GetOrAddBookmark()
class UBookmarkBase * AWorldSettings::GetOrAddBookmark (const uint32 BookmarkIndex, const bool bRecreateOnClassMismatch)
Gets the bookmark at the specified index, creating it if a bookmark doesn't exist.
This will fail if the specified index is greater than MaxNumberOfBookmarks.
For "plain" access that doesn't cause reallocation, use GetBookmarks
Parameters
bRecreateOnClassMismatch Whether or not we should recreate an existing bookmark if it's class doesn't match the default bookmark class.
GetPauserPlayerState()
FORCEINLINE class APlayerState * AWorldSettings::GetPauserPlayerState () const inline
Definition at line 900 of file WorldSettings.h.
References FORCEINLINE.
GetPhysicsCollisionHandlerClass()
virtual TSubclassOf< class UPhysicsCollisionHandler > AWorldSettings::GetPhysicsCollisionHandlerClass () inline virtual
Definition at line 587 of file WorldSettings.h.
References GetPhysicsCollisionHandlerClass().
Referenced by GetPhysicsCollisionHandlerClass().
GetWorldPartition()
UWorldPartition * AWorldSettings::GetWorldPartition () const
Referenced by IsPartitionedWorld().
HIDE_ACTOR_TRANSFORM_FUNCTIONS()
AWorldSettings::HIDE_ACTOR_TRANSFORM_FUNCTIONS () private
InternalPostPropertyChanged()
void AWorldSettings::InternalPostPropertyChanged (FName PropertyName) private
References PropertyName.
IsAISystemEnabled()
bool AWorldSettings::IsAISystemEnabled () const inline
Returns
whether given world is configured to host an AISystem
Definition at line 866 of file WorldSettings.h.
IsNavigationSystemEnabled()
bool AWorldSettings::IsNavigationSystemEnabled () const
Returns
whether given world is configured to host any NavigationSystem
IsPartitionedWorld()
bool AWorldSettings::IsPartitionedWorld () const inline
Definition at line 803 of file WorldSettings.h.
References GetWorldPartition().
IsSelectable()
virtual bool AWorldSettings::IsSelectable () const inline override virtual
Definition at line 792 of file WorldSettings.h.
NotifyBeginPlay()
virtual void AWorldSettings::NotifyBeginPlay () virtual
Called from GameStateBase, calls BeginPlay on all actors.
NotifyMatchStarted()
virtual void AWorldSettings::NotifyMatchStarted () virtual
Called from GameStateBase, used to notify native classes of match startup (such as level scripting)
PostEditChangeProperty()
virtual void AWorldSettings::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void AWorldSettings::PostInitProperties () override virtual
PostLoad()
virtual void AWorldSettings::PostLoad () override virtual
Reimplemented from AInfo.
PostRegisterAllComponents()
virtual void AWorldSettings::PostRegisterAllComponents () override virtual
PostTransacted()
virtual void AWorldSettings::PostTransacted (const FTransactionObjectEvent & TransactionEvent) override virtual
PreInitializeComponents()
virtual void AWorldSettings::PreInitializeComponents () override virtual
RemoveUserDataOfClass()
virtual void AWorldSettings::RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override virtual
Reimplemented from IInterface_AssetUserData.
ResetDefaultWorldPartitionSettings()
void AWorldSettings::ResetDefaultWorldPartitionSettings ()
ResetHierarchicalLODSetup()
void AWorldSettings::ResetHierarchicalLODSetup ()
RewindForReplay()
virtual void AWorldSettings::RewindForReplay () override virtual
SanitizeBookmarkClasses()
void AWorldSettings::SanitizeBookmarkClasses () private
SaveDefaultWorldPartitionSettings()
void AWorldSettings::SaveDefaultWorldPartitionSettings ()
Serialize()
virtual void AWorldSettings::Serialize (FArchive & Ar) override private virtual
References Ar.
SetAllowMaskedMaterials()
virtual void AWorldSettings::SetAllowMaskedMaterials (bool bState) virtual
References SetAllowMaskedMaterials().
Referenced by SetAllowMaskedMaterials().
SetAllowTimeDilation()
virtual void AWorldSettings::SetAllowTimeDilation (bool NewAllowTimeDilation) virtual
Sets whether or not Time Dilation is allowed.
When true, GetEffectiveTimeDilation() will return the time dilation as determined by the various dilation factors, when false it will return 1.0f.
SetCinematicTimeDilation()
virtual float AWorldSettings::SetCinematicTimeDilation (float NewCinematicTimeDilation) virtual
Sets the cinematic time dilation value (subject to clamping).
Returns the final value that was set (which may be clamped) even if bAllowTimeDilation is set to false.
SetDefaultBookmark()
void AWorldSettings::SetDefaultBookmark (class UBookmarkBase * InDefaultBookmark)
Set the bookmark that will be applied when the map is opened in the editor.
References bool, meta, and UPROPERTY().
SetNavigationSystemConfigOverride()
void AWorldSettings::SetNavigationSystemConfigOverride (UNavigationSystemConfig * NewConfig)
Sets a configuration override for NavigationSystem's creation.
If set, GetNavigationSystemConfig will return this configuration instead NavigationSystemConfig.
SetPauserPlayerState()
virtual FORCEINLINE void AWorldSettings::SetPauserPlayerState (class APlayerState * PlayerState) inline virtual
Definition at line 901 of file WorldSettings.h.
References FORCEINLINE.
SetTimeDilation()
virtual float AWorldSettings::SetTimeDilation (float NewTimeDilation) virtual
Sets the global time dilation value (subject to clamping).
Returns the final value that was set (which may be clamped) even if bAllowTimeDilation is set to false.
SetWorldPartition()
void AWorldSettings::SetWorldPartition (UWorldPartition * InWorldPartition)
SupportsExternalPackaging()
virtual bool AWorldSettings::SupportsExternalPackaging () const inline override virtual
Definition at line 793 of file WorldSettings.h.
SupportsWorldPartitionStreaming()
virtual bool AWorldSettings::SupportsWorldPartitionStreaming () const inline virtual
Definition at line 807 of file WorldSettings.h.
SupportsWorldPartitionStreamingChanged()
void AWorldSettings::SupportsWorldPartitionStreamingChanged ()
UFUNCTION() [1/2]
AWorldSettings::UFUNCTION ()
References UFUNCTION().
UFUNCTION() [2/2]
AWorldSettings::UFUNCTION ()
References UFUNCTION().
Referenced by UFUNCTION(), and UFUNCTION().
UpdateBookmarkClass()
void AWorldSettings::UpdateBookmarkClass () private
UpdateNumberOfBookmarks()
void AWorldSettings::UpdateNumberOfBookmarks () private
UPROPERTY() [1/45]
UPROPERTY()) uint8 bEnableWorldComposition UPROPERTY() uint8 bUseClientSideLevelStreamingVolumes UPROPERTY()) uint8 bEnableWorldOriginRebasing UPROPERTY() uint8 bWorldGravitySet AWorldSettings::UPROPERTY ()
Whether to place visibility cells inside Precomputed Visibility Volumes and along camera tracks in this level.
Precomputing visibility reduces rendering thread time at the cost of some runtime memory and somewhat increased lighting build times. Whether to place visibility cells only along camera tracks or only above shadow casting surfaces. DEFAULT BASIC PHYSICS SETTINGS If true, enables CheckStillInWorld checks if set to false navigation system will not get created (and all navigation functionality won't be accessible). This flag is now deprecated. Use NavigationSystemConfig property to determine navigation system's properties or existence if set to false AI system will not get created. Use it to disable all AI-related activity on a map Enables tools for composing a tiled world. Level has to be saved and all sub-levels removed before enabling this option. Enables client-side streaming volumes instead of server-side. Expected usage scenario: server has all streaming levels always loaded, clients independently stream levels in/out based on streaming volumes. World origin will shift to a camera position when camera goes far away from current origin if set to true, when we call GetGravityZ we assume WorldGravityZ has already been initialized and skip the lookup of DefaultGravityZ and GlobalGravityZ If set to true we will use GlobalGravityZ instead of project setting DefaultGravityZ
UPROPERTY() [2/45]
UPROPERTY() uint8 bMinimizeBSPSections UPROPERTY() uint8 bForceNoPrecomputedLighting UPROPERTY() uint8 bForceVolumetricLightmapsOnly UPROPERTY() uint8 bHighPriorityLoading UPROPERTY() uint8 bHighPriorityLoadingLocal UPROPERTY() uint8 bOverrideDefaultBroadphaseSettings UPROPERTY()) uint8 bGenerateSingleClusterForLevel UPROPERTY() uint8 bAllowTimeDilation UPROPERTY() uint8 bReuseAddressAndPort AWorldSettings::UPROPERTY ()
Causes the BSP build to generate as few sections as possible.
This is useful when you need to reduce draw calls but can reduce texture streaming efficiency and effective lightmap resolution. Note - changes require a rebuild to propagate. Also, be sure to select all surfaces and make sure they all have the same flags to minimize section count. Whether to force lightmaps and other precomputed lighting to not be created even when the engine thinks they are needed. This is useful for improving iteration in levels with fully dynamic lighting and shadowing. Note that any lighting and shadowing interactions that are usually precomputed will be lost if this is enabled. Force precomputed lighting to only use VolumetricLightmaps. when this flag is set, more time is allocated to background loading (replicated) copy of bHighPriorityLoading that is not replicated, for clientside-only loading operations If set to true, all eligible actors in this level will be added to a single cluster representing the entire level (used for small sublevels) Allows game logic to temporarily disable all forms of time dilation (when using GetEffectiveTimeDilation(). When false, logic is still allowed to set time dilation values, but their values will be ignored when calling GetEffectiveTimeDilation() until this is set back to true.
Transient because it's used for temporary overrides and shouldn't be saved/loaded from level packages. Not replicated because in multiplayer a server should modify the real time dilation, instead of ignoring it on a client (which will lead to position desyncs due to delta time mismatches). Whether to configure the listening socket to allow reuse of the address and port. If this is true, be sure no other servers can run on the same port, otherwise this can lead to undefined behavior since packets will go to two servers.
References AI, Category, and meta.
UPROPERTY() [3/45]
AWorldSettings::UPROPERTY ()
Range in which volumetric lightmaps will be loaded.
UPROPERTY() [4/45]
AWorldSettings::UPROPERTY ()
References Category, config, and UPROPERTY().
UPROPERTY() [5/45]
AWorldSettings::UPROPERTY ()
Default interior settings applied to sounds that have "apply ambient volumes" set to true on their SoundClass.
References Category, config, and UPROPERTY().
UPROPERTY() [6/45]
AWorldSettings::UPROPERTY ()
References transient.
UPROPERTY() [7/45]
AWorldSettings::UPROPERTY ()
References transient.
UPROPERTY() [8/45]
AWorldSettings::UPROPERTY ()
Normally 1 - scales real time passage.
Warning - most use cases should use GetEffectiveTimeDilation() instead of reading from this directly
References transient.
UPROPERTY() [9/45]
AWorldSettings::UPROPERTY ()
References transient, and UPROPERTY().
UPROPERTY() [10/45]
AWorldSettings::UPROPERTY ()
scale of 1uu to 1m in real world measurements, for HMD and other physically tracked devices (e.g.
1uu = 1cm would be 100.0)
References Category.
UPROPERTY() [11/45]
AWorldSettings::UPROPERTY ()
NANITE SETTINGS.
References Category, config, and UPROPERTY().
UPROPERTY() [12/45]
AWorldSettings::UPROPERTY ()
AUDIO SETTINGS.
Default reverb settings used by audio volumes.
References Category, config, and UPROPERTY().
UPROPERTY() [13/45]
AWorldSettings::UPROPERTY ()
Default color scale for the level.
References Category, FVector, and UPROPERTY().
UPROPERTY() [14/45]
AWorldSettings::UPROPERTY ()
Additional transform applied when applying LevelStreaming Transform to LevelInstance.
References FVector, and UPROPERTY().
UPROPERTY() [15/45]
AWorldSettings::UPROPERTY ()
RENDERING SETTINGS.
Maximum size of textures for packed light and shadow maps
References Category, Lightmass, and UPROPERTY().
UPROPERTY() [16/45]
AWorldSettings::UPROPERTY ()
valid only during replication - information about the player(s) being replicated to (there could be more than one in the case of a splitscreen client)
References UPROPERTY().
UPROPERTY() [17/45]
AWorldSettings::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [18/45]
AWorldSettings::UPROPERTY () protected
Array of user data stored with the asset.
References Category, and UPROPERTY().
UPROPERTY() [19/45]
AWorldSettings::UPROPERTY ()
A list of runtime data layers that should be included in the base navmesh.
Editor data layers and actors outside data layers will be included.
References Category.
UPROPERTY() [20/45]
AWorldSettings::UPROPERTY () protected
References transient.
UPROPERTY() [21/45]
AWorldSettings::UPROPERTY ()
Default Base SoundMix.
References Category, config, meta, UE_DEPRECATED, and UPROPERTY().
UPROPERTY() [22/45]
AWorldSettings::UPROPERTY () protected
Overrides NavigationSystemConfig.
References Transient, and UPROPERTY().
UPROPERTY() [23/45]
AWorldSettings::UPROPERTY () protected
References Category, meta, Transient, and UPROPERTY().
UPROPERTY() [24/45]
AWorldSettings::UPROPERTY ()
References Category, Physics, and UPROPERTY().
UPROPERTY() [25/45]
AWorldSettings::UPROPERTY ()
Class of GameNetworkManager to spawn for network games.
References UPROPERTY().
UPROPERTY() [26/45]
AWorldSettings::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [27/45]
AWorldSettings::UPROPERTY ()
References Category, and Physics.
UPROPERTY() [28/45]
AWorldSettings::UPROPERTY ()
Max occlusion distance used by mesh distance fields, overridden if there is a movable skylight.
References Category, meta, and UPROPERTY().
UPROPERTY() [29/45]
AWorldSettings::UPROPERTY ()
Controls the intensity of self-shadowing from capsule indirect shadows.
These types of shadows use approximate occluder representations, so reducing self-shadowing intensity can hide those artifacts.
References Category, config, Lightmass, meta, and UPROPERTY().
UPROPERTY() [30/45]
AWorldSettings::UPROPERTY ()
Distance from the camera that the global distance field should cover.
References Category, meta, and UPROPERTY().
UPROPERTY() [31/45]
AWorldSettings::UPROPERTY ()
References Category, meta, Physics, and UPROPERTY().
UPROPERTY() [32/45]
AWorldSettings::UPROPERTY ()
References Category, config, float, and meta.
UPROPERTY() [33/45]
AWorldSettings::UPROPERTY ()
Highest acceptable cinematic time dilation.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [34/45]
AWorldSettings::UPROPERTY ()
Highest acceptable global time dilation.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [35/45]
AWorldSettings::UPROPERTY ()
Largest possible frametime, not considering dilation.
Equiv to 1/SlowestFPS.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [36/45]
AWorldSettings::UPROPERTY ()
Lowest acceptable cinematic time dilation.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [37/45]
AWorldSettings::UPROPERTY ()
Lowest acceptable global time dilation.
References Category, config, float, and meta.
UPROPERTY() [38/45]
AWorldSettings::UPROPERTY ()
Smallest possible frametime, not considering dilation.
Equiv to 1/FastestFPS.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [39/45]
AWorldSettings::UPROPERTY () private
Maximum number of bookmarks allowed.
Changing this will change the allocation of the bookmarks array, and when shrinking may cause some bookmarks to become eligible for GC.
References Meta.
UPROPERTY() [40/45]
AWorldSettings::UPROPERTY () private
PRECOMPUTED VISIBILITY SETTINGS.
World space size of precomputed visibility cells in x and y. Smaller sizes produce more effective occlusion culling at the cost of increased runtime memory usage and lighting build times.
References Category, meta, and UPROPERTY().
Referenced by SetDefaultBookmark(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [41/45]
AWorldSettings::UPROPERTY () private
Determines how aggressive precomputed visibility should be.
More aggressive settings cull more objects but also cause more visibility errors like popping.
References AI, Category, config, meta, transient, UE_DEPRECATED, and UPROPERTY().
UPROPERTY() [42/45]
AWorldSettings::UPROPERTY () protected
Holds parameters for NavigationSystem's creation.
Set to Null will result in NavigationSystem instance not being created for this world. Note that if set NavigationSystemConfigOverride will be used instead.
References Category, meta, and UPROPERTY().
UPROPERTY() [43/45]
AWorldSettings::UPROPERTY ()
GAMEMODE SETTINGS.
The default GameMode to use when starting this map in the game. If this value is NULL, the INI setting for default game type is used.
References Category, and meta.
UPROPERTY() [44/45]
AWorldSettings::UPROPERTY () private
Class that will be used when creating new bookmarks.
Old bookmarks may be recreated with the new class where possible.
References ExactClass, Meta, and UPROPERTY().
UPROPERTY() [45/45]
AWorldSettings::UPROPERTY ()
References Category, meta, and UPROPERTY().
Field Documentation
AISystemClass
UPROPERTY() uint8 bMinimizeBSPSections UPROPERTY() uint8 bForceNoPrecomputedLighting UPROPERTY() uint8 bForceVolumetricLightmapsOnly UPROPERTY() uint8 bHighPriorityLoading UPROPERTY() uint8 bHighPriorityLoadingLocal UPROPERTY() uint8 bOverrideDefaultBroadphaseSettings UPROPERTY()) uint8 bGenerateSingleClusterForLevel UPROPERTY() uint8 bAllowTimeDilation UPROPERTY() uint8 bReuseAddressAndPort AdvancedDisplay TSoftClassPtr<UAISystemBase> AWorldSettings::AISystemClass
Definition at line 498 of file WorldSettings.h.
Category
UPROPERTY()) uint8 bEnableWorldComposition UPROPERTY() uint8 bUseClientSideLevelStreamingVolumes UPROPERTY()) uint8 bEnableWorldOriginRebasing UPROPERTY() uint8 bWorldGravitySet AWorldSettings::Category
Initial value:
= Physics)
    uint8 bGlobalGravitySet:1
Definition at line 418 of file WorldSettings.h.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
InstancedFoliageGridGridPreviewer
TUniquePtr<FWorldGridPreviewer> AWorldSettings::InstancedFoliageGridGridPreviewer mutable
Definition at line 548 of file WorldSettings.h.
meta
AWorldSettings::meta
Initial value:
= (EditConditionHides, EditCondition = "WorldPartition != nullptr"))
    float VolumetricLightmapLoadingRange
Definition at line 641 of file WorldSettings.h.
Referenced by SetDefaultBookmark(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
NumMappedBookmarks
const uint32 AWorldSettings::NumMappedBookmarks = 10 static
The number of bookmarks that will have mapped keyboard shortcuts by default.
Definition at line 955 of file WorldSettings.h.
OnBookmarkClassChanged
FOnBookmarkClassChanged AWorldSettings::OnBookmarkClassChanged static
Definition at line 959 of file WorldSettings.h.
OnDefaultBookmarkChanged
FOnDefaultBookmarkChanged AWorldSettings::OnDefaultBookmarkChanged static
Definition at line 965 of file WorldSettings.h.
OnNaniteSettingsChanged
FOnNaniteSettingsChanged AWorldSettings::OnNaniteSettingsChanged static
Definition at line 969 of file WorldSettings.h.
OnNumberOfBoomarksChanged
FOnNumberOfBookmarksChanged AWorldSettings::OnNumberOfBoomarksChanged static
Definition at line 962 of file WorldSettings.h.
The documentation for this class was generated from the following file:
WorldSettings.h