Unreal Engine 5.6 C++ API: MovieSceneNumericVariant.h File Reference
MovieSceneNumericVariant.h File Reference
#include "CoreTypes.h"
#include "MovieSceneNumericVariant.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneNumericVariant >
Macros
#define UE_MOVIESCENE_WEAKNUMERICVARIANT_CHECKS DO_CHECK
Functions
USTRUCT () struct FMovieSceneNumericVariant
A variant type that masquerades as a numeric (double) value.
Macro Definition Documentation
UE_MOVIESCENE_WEAKNUMERICVARIANT_CHECKS
#define UE_MOVIESCENE_WEAKNUMERICVARIANT_CHECKS DO_CHECK
Definition at line 11 of file MovieSceneNumericVariant.h.
Function Documentation
USTRUCT()
USTRUCT ()
A variant type that masquerades as a numeric (double) value.
This type is 8 bytes (sizeof(double)) and uses a technique called NaN-boxing to encode variants into those 8-bytes, while a literal double value maintains the exact same bits in-memory as a double. By default this variant can only represent a double, or a UMovieSceneNumericVariantGetter*, but additional variant types can be encoded by deriving from this type and associating type 'IDs' to typed-data (upto 48 bit in size), where the type bits are encoded into the nan bits of the double.
Extensive reading around NaN-boxing techniques can be found elsewhere.
UMovieSceneNumericVariantGetter may be used to assign an external, dynamic value to this variant.
The benefit of using this technique is that this type can be used as a drop-in replacement for any double member variable to provide it with dynamic getter functionality without inflating the size of the class, and with barely any runtime overhead whatsoever. Automatic UPROPERTY upgrade exists for all numeric property types that make sense: int64 and uint64 are not supported in this variant due to loss of precision (doubles only have 52 bits of mantissa)
No init constructor that leaves the underlying memory uninitialized
Default constructor - initializes this variant to a value of 0.0
Initialize this variant to an explicit literal value
Initialize this variant to an object pointer that provides a value
Move-assign and constructible
Equality comparison
Inequality comparison
Assign a new literal value to this variant, clearing any knowledge of a previously assigned value.
Parameters
InLiteralValue The new fixed value this variant should represent.
Assign a new dynamic value to this variant.
Parameters
InDynamicValue The new dynamic value this variant should represent.
Assign a new dynamic value to this variant as an unsafe weak ptr.
Warning
: This will result in a dangling pointer if it is not referenced strongly elsewhere. Use with caution.
Parameters
InDynamicValue The new dynamic value this variant should represent.
If this variant wraps a UMovieSceneTimeWarpGetter, turn it into an unsafe weak reference.
Warning
: This will result in a dangling pointer if it is not referenced strongly elsewhere. Use with caution.
Retrieve this variant's numeric value
Parameters
InDynamicValue The new dynamic value this variant should represent.
Retrieves this variant as a UMovieSceneNumericVariantGetter pointer.
Note
: Only safe to call if IsCustomPtr() returns true
Checks whether this variant is a literal double value or a different type
Retrieves this variant as a literal double representation.
Retrieves this variant as a literal double representation, clamped to the range of a float.
Checks whether this variant is a UMovieSceneNumericVariantGetter pointer (ie, GetCustomPtr is valid to call).
Make a shallow (bitwise) copy of this variant. Does not duplicate the underlying UMovieSceneNumericVariantGetter* if it is set: this function merely copies the ptr.
Make a deep copy of this variant by duplicating the underlying UMovieSceneNumericVariantGetter into a new outer if necessary.
For StructOpsTypeTraits
Assign new, implementation defined typed data to this variant.
Note
: If the instance of this class is to be serialized, the parent class should override Serialize to provide robust serialization mechanisms besides the built-in bitwise serialization.
Parameters
InValue The new value to assign. Must be <= 48 bits.
InType A unique, compiletime fixed ID that identifies 'T'. Must be <= 7.
Cast this variant to a user-defined type.
Note
: No type checking is performed other than checking !IsLiteral(). External protections must be made to ensure calling this function is safe.
Set the type flags for this variant - should only be used where custom typed data is assigned
Note
: Only valid to be called where IsLiteral() == false.
Parameters
InType A unique, compiletime fixed ID that identifies the contained data. Must be <= 7.
Retrieve the type flags for this variant.
Note
: Only valid to be called where IsLiteral() == false.
Checks whether this variant has the weak ptr flag.
Note
: Only valid to be called if IsCustomPtr() is true
Functionally non-copyable except to the reflection layer - use Deep/Shallow copy instead
Definition at line 33 of file MovieSceneNumericVariant.h.
References A, Ar, B, BlueprintType, Buffer, checkSlow, DeepCopy, GENERATED_BODY, Identical, operator!=(), operator=(), operator==(), Other, Parent, and PLATFORM_LITTLE_ENDIAN.