Unreal Engine 5.6 C++ API: FAppStyle Class Reference
FAppStyle Class Reference
AppStyle class.
#include "AppStyle.h"
Static Public Member Functions
static const ISlateStyle & Get ()
static const FName GetAppStyleSetName ()
static const FSlateBrush * GetBrush (FName PropertyName, const ANSICHAR *Specifier=NULL)
static const FLinearColor & GetColor (FName PropertyName, const ANSICHAR *Specifier=NULL)
static const FSlateBrush * GetDefaultBrush ()
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, class UTexture2D *TextureResource, FName TextureName)
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, const ANSICHAR *Specifier, class UTexture2D *TextureResource, FName TextureName)
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, FName TextureName, const ANSICHAR *Specifier=NULL)
static float GetFloat (FName PropertyName, const ANSICHAR *Specifier=NULL)
static FSlateFontInfo GetFontStyle (FName PropertyName, const ANSICHAR *Specifier=NULL)
static const FMargin & GetMargin (FName PropertyName, const ANSICHAR *Specifier=NULL)
static const FSlateBrush * GetNoBrush ()
static const FSlateBrush * GetOptionalBrush (FName PropertyName, const ANSICHAR *Specifier=NULL, const FSlateBrush *const DefaultBrush=FStyleDefaults::GetNoBrush())
static const FSlateColor GetSlateColor (FName PropertyName, const ANSICHAR *Specifier=NULL)
static const FSlateSound & GetSound (FName PropertyName, const ANSICHAR *Specifier=NULL)
static UE::Slate::FDeprecateVector2DResult GetVector (FName PropertyName, const ANSICHAR *Specifier=NULL)
template<class T>
static const T & GetWidgetStyle (FName PropertyName, const ANSICHAR *Specifier=NULL)
static FName Join (FName A, const ANSICHAR *B)
Concatenates two FNames.e If A and B are "Path.To" and ".Something" the result "Path.To.Something".
static void SetAppStyleSet (const ISlateStyle &InStyle)
static void SetAppStyleSetName (const FName &InName)
Static Private Attributes
static FName AppStyleName
Detailed Description
AppStyle class.
AppStyle is a Singleton accessor to a named SlateStyle to be used as an Application wide base style definition.
Moving forward, all references in any core Slate Application Widgets should use FAppStyle::Get()
FEditorStyle::Get accessors and FCoreStyle::Get accessors should be replaced with FAppStyle::Get()
Currently, this code defaults to use FCoreStyle::GetCoreStyle() if the named style is not found.
Definition at line 23 of file AppStyle.h.
Member Function Documentation
Get()
const ISlateStyle & FAppStyle::Get () static
Referenced by FVerticalToolBarBuilder::FVerticalToolBarBuilder(), SNumericEntryBox< NumericType >::BuildNarrowColorLabel(), FCoreStyle::Get(), FStarshipCoreStyle::Get(), GetBrush(), GetColor(), GetDefaultBrush(), SGraphPinNum< NumericType >::GetDefaultValueWidget(), SGraphPinNumSlider< NumericType >::GetDefaultValueWidget(), FDiffSingleResult::GetDisplayColor(), GetDynamicImageBrush(), GetDynamicImageBrush(), GetDynamicImageBrush(), GetFloat(), GetFontStyle(), GetMargin(), GetOptionalBrush(), GetSlateColor(), GetSound(), GetVector(), GetWidgetStyle(), FFolderDragDropOp::Init(), SAppIconWidget::SLATE_ATTRIBUTE(), and SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorWArguments< ArgumentType >::SLATE_ATTRIBUTE().
GetAppStyleSetName()
const FName FAppStyle::GetAppStyleSetName () static
GetBrush()
const FSlateBrush * FAppStyle::GetBrush (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 66 of file AppStyle.h.
References Get(), ISlateStyle::GetBrush(), and PropertyName.
Referenced by FRigVMEdGraphConnectionDrawingPolicy::FRigVMEdGraphConnectionDrawingPolicy(), FSocketDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FBoneDragDropOp::GetDefaultDecorator(), FBrushBuilderDragDropOp::GetDefaultDecorator(), FClassDragDropOp::GetDefaultDecorator(), FDecoratedDragDropOp::GetDefaultDecorator(), FLevelDragDropOp::GetDefaultDecorator(), SNodePanel::SNode::GetDiffHighlightBrushes(), FBoneDragDropOp::New(), FSocketDragDropOp::New(), SRigVMActionMenu::OnCreateWidgetForAction(), and FActorDragDropGraphEdOp::SetToolTip().
GetColor()
const FLinearColor & FAppStyle::GetColor (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 51 of file AppStyle.h.
References Get(), ISlateStyle::GetColor(), and PropertyName.
GetDefaultBrush()
const FSlateBrush * FAppStyle::GetDefaultBrush () inline static
Definition at line 96 of file AppStyle.h.
References Get(), and ISlateStyle::GetDefaultBrush().
GetDynamicImageBrush() [1/3]
const TSharedPtr< FSlateDynamicImageBrush > FAppStyle::GetDynamicImageBrush (FName BrushTemplate, class UTexture2D * TextureResource, FName TextureName) inline static
Definition at line 81 of file AppStyle.h.
References Get(), and ISlateStyle::GetDynamicImageBrush().
GetDynamicImageBrush() [2/3]
const TSharedPtr< FSlateDynamicImageBrush > FAppStyle::GetDynamicImageBrush (FName BrushTemplate, const ANSICHAR * Specifier, class UTexture2D * TextureResource, FName TextureName) inline static
Definition at line 76 of file AppStyle.h.
References Get(), and ISlateStyle::GetDynamicImageBrush().
GetDynamicImageBrush() [3/3]
const TSharedPtr< FSlateDynamicImageBrush > FAppStyle::GetDynamicImageBrush (FName BrushTemplate, FName TextureName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 71 of file AppStyle.h.
References Get(), and ISlateStyle::GetDynamicImageBrush().
GetFloat()
float FAppStyle::GetFloat (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 41 of file AppStyle.h.
References Get(), ISlateStyle::GetFloat(), and PropertyName.
Referenced by SSkeletonSelectorWindow::ConstructButtons().
GetFontStyle()
FSlateFontInfo FAppStyle::GetFontStyle (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 91 of file AppStyle.h.
References Get(), ISlateStyle::GetFontStyle(), and PropertyName.
Referenced by IPropertyTypeCustomizationUtils::GetBoldFont(), IDetailLayoutBuilder::GetDetailFont(), IDetailLayoutBuilder::GetDetailFontBold(), IDetailLayoutBuilder::GetDetailFontItalic(), IPropertyTypeCustomizationUtils::GetRegularFont(), SVector2DTextBox< NumericType >::SLATE_END_ARGS(), and SVector4TextBox< NumericType >::SLATE_END_ARGS().
GetMargin()
const FMargin & FAppStyle::GetMargin (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 61 of file AppStyle.h.
References Get(), ISlateStyle::GetMargin(), and PropertyName.
Referenced by SSkeletonSelectorWindow::ConstructButtons().
GetNoBrush()
const FSlateBrush * FAppStyle::GetNoBrush () inline static
Definition at line 101 of file AppStyle.h.
References FStyleDefaults::GetNoBrush().
GetOptionalBrush()
const FSlateBrush * FAppStyle::GetOptionalBrush (FName PropertyName, const ANSICHAR * Specifier = NULL, const FSlateBrush *const DefaultBrush = FStyleDefaults::GetNoBrush()) inline static
Definition at line 106 of file AppStyle.h.
References Get(), FStyleDefaults::GetNoBrush(), ISlateStyle::GetOptionalBrush(), and PropertyName.
GetSlateColor()
const FSlateColor FAppStyle::GetSlateColor (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 56 of file AppStyle.h.
References Get(), ISlateStyle::GetSlateColor(), and PropertyName.
GetSound()
const FSlateSound & FAppStyle::GetSound (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 86 of file AppStyle.h.
References Get(), ISlateStyle::GetSound(), and PropertyName.
GetVector()
UE::Slate::FDeprecateVector2DResult FAppStyle::GetVector (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 46 of file AppStyle.h.
References Get(), ISlateStyle::GetVector(), and PropertyName.
GetWidgetStyle()
template<class T> const T & FAppStyle::GetWidgetStyle (FName PropertyName, const ANSICHAR * Specifier = NULL) inline static
Definition at line 36 of file AppStyle.h.
References Get(), ISlateStyle::GetWidgetStyle(), and PropertyName.
Referenced by SVector2DTextBox< NumericType >::SLATE_END_ARGS(), and SVector4TextBox< NumericType >::SLATE_END_ARGS().
Join()
FName FAppStyle::Join (FName A, const ANSICHAR * B) inline static
Concatenates two FNames.e If A and B are "Path.To" and ".Something" the result "Path.To.Something".
Parameters
A First FName
B Second name
Returns
New FName that is A concatenated with B.
Definition at line 120 of file AppStyle.h.
References A, B, and FName.
SetAppStyleSet()
void FAppStyle::SetAppStyleSet (const ISlateStyle & InStyle) static
SetAppStyleSetName()
void FAppStyle::SetAppStyleSetName (const FName & InName) static
References InName.
Field Documentation
AppStyleName
FName FAppStyle::AppStyleName static private
Definition at line 134 of file AppStyle.h.
The documentation for this class was generated from the following file:
AppStyle.h