Unreal Engine 5.6 C++ API: CurveTable.h File Reference
CurveTable.h File Reference
#include "CoreMinimal.h"
#include "Misc/TransactionallySafeCriticalSection.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "Policies/PrettyJsonPrintPolicy.h"
#include "Curves/CurveOwnerInterface.h"
#include "Curves/SimpleCurve.h"
#include "CurveTable.generated.h"
Data Structures
struct TStructOpsTypeTraits< FCurveTableRowHandle >
Macros
#define GETCURVE_REPORTERROR(Handle)
Macro to call GetCurve with a correct error info.
#define GETCURVE_REPORTERROR_WITHPATHNAME(Handle, PathNameString)
Macro to call GetCurve with a correct error info.
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogCurveTable, Log, All)
UENUM() enum class ECurveTableMode UCLASS()) class UCurveTable USTRUCT () struct FCurveTableRowHandle
Whether the curve table contains simple, rich, or no curves.
Macro Definition Documentation
GETCURVE_REPORTERROR
#define GETCURVE_REPORTERROR (Handle)
Value:
Handle.GetCurve(FString::Printf(TEXT("%s.%s"), *GetPathName(), TEXT(#Handle)))
Macro to call GetCurve with a correct error info.
Assumed to be called within a UObject
Definition at line 337 of file CurveTable.h.
GETCURVE_REPORTERROR_WITHPATHNAME
#define GETCURVE_REPORTERROR_WITHPATHNAME (Handle, PathNameString)
Value:
Handle.GetCurve(FString::Printf(TEXT("%s.%s"), *PathNameString, TEXT(#Handle)))
Macro to call GetCurve with a correct error info.
Definition at line 340 of file CurveTable.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogCurveTable , Log , All)
References All, and Log.
USTRUCT()
UENUM() enum class ECurveTableMode UCLASS()) class UCurveTable USTRUCT ()
Whether the curve table contains simple, rich, or no curves.
Imported spreadsheet table as curves. Handle to a particular row in a table.
Pointer to table we want a row from
Name of row in the table that we want
Returns true if the curve is valid
Returns true if this handle is specifically pointing to nothing
Get the curve straight from the row handle
Get the rich curve straight from the row handle
Get the simple curve straight from the row handle
Evaluate the curve if it is valid
Parameters
XValue The input X value to the curve
ContextString A string to provide context for where this operation is being carried out
Returns
The value of the curve if valid, 0 if not
Evaluate the curve if it is valid
Parameters
XValue The input X value to the curve
YValue The output Y value from the curve
ContextString A string to provide context for where this operation is being carried out
Returns
True if it filled out YValue with a valid number, false otherwise
Used so we can have a TMap of this struct
Definition at line 257 of file CurveTable.h.
References Ar, BlueprintType, Category, FORCEINLINE, GENERATED_USTRUCT_BODY, GetTypeHash(), Handle, HashCombine(), FName::IsNone(), IsValid(), meta, operator!=(), operator==(), Other, PointerHash(), and UPROPERTY.