Unreal Engine 5.6 C++ API: Metasound::TArrayLastIndexOperator< ArrayType > Class Template Reference
Metasound::TArrayLastIndexOperator< ArrayType > Class Template Reference
TArrayLastIndex gets last index of an array.
#include "MetasoundArrayNodes.h"
Public Types
using FArrayDataReadReference = TDataReadReference<ArrayType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArrayLastIndexOperator (FArrayDataReadReference InArray)
virtual ~TArrayLastIndexOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArrayLastIndexOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Attributes
FArrayDataReadReference Array
TDataWriteReference< int32 > LastIndex
Detailed Description
template<typename ArrayType>
class Metasound::TArrayLastIndexOperator< ArrayType >
TArrayLastIndex gets last index of an array.
Definition at line 843 of file MetasoundArrayNodes.h.
Member Typedef Documentation
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArrayLastIndexOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 846 of file MetasoundArrayNodes.h.
Constructor & Destructor Documentation
TArrayLastIndexOperator()
template<typename ArrayType> Metasound::TArrayLastIndexOperator< ArrayType >::TArrayLastIndexOperator (FArrayDataReadReference InArray) inline
Definition at line 896 of file MetasoundArrayNodes.h.
References Array, and LastIndex.
~TArrayLastIndexOperator()
template<typename ArrayType> virtual Metasound::TArrayLastIndexOperator< ArrayType >::~TArrayLastIndexOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArrayLastIndexOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 906 of file MetasoundArrayNodes.h.
References Array, Metasound::FInputVertexInterfaceData::BindReadVertex(), and METASOUND_GET_PARAM_NAME.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArrayLastIndexOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 912 of file MetasoundArrayNodes.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), LastIndex, and METASOUND_GET_PARAM_NAME.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArrayLastIndexOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 883 of file MetasoundArrayNodes.h.
References Array, Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, and Metasound::FBuildOperatorParams::OperatorSettings.
Execute()
template<typename ArrayType> void Metasound::TArrayLastIndexOperator< ArrayType >::Execute () inline
Definition at line 919 of file MetasoundArrayNodes.h.
References Array, and LastIndex.
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArrayLastIndexOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 849 of file MetasoundArrayNodes.h.
References METASOUND_GET_PARAM_NAME_AND_METADATA.
Referenced by GetNodeInfo().
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArrayLastIndexOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 865 of file MetasoundArrayNodes.h.
References Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metadata, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, and TEXT.
Reset()
template<typename ArrayType> void Metasound::TArrayLastIndexOperator< ArrayType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 924 of file MetasoundArrayNodes.h.
References Execute.
Field Documentation
Array
template<typename ArrayType> FArrayDataReadReference Metasound::TArrayLastIndexOperator< ArrayType >::Array private
Definition at line 931 of file MetasoundArrayNodes.h.
Referenced by TArrayLastIndexOperator(), BindInputs(), CreateOperator(), and Execute().
LastIndex
template<typename ArrayType> TDataWriteReference<int32> Metasound::TArrayLastIndexOperator< ArrayType >::LastIndex private
Definition at line 932 of file MetasoundArrayNodes.h.
Referenced by TArrayLastIndexOperator(), BindOutputs(), and Execute().
The documentation for this class was generated from the following file:
MetasoundArrayNodes.h