Unreal Engine 5.6 C++ API: UE::Geometry::FSimpleMeshProcessingBaseOp Class Reference
UE::Geometry::FSimpleMeshProcessingBaseOp Class Reference
Dynamic Mesh Operator that has a separate PositionBuffer that contains copy of input vertex positions.
#include "SimpleMeshProcessingBaseOp.h"
Public Member Functions
MODELINGOPERATORS_API FSimpleMeshProcessingBaseOp (const FDynamicMesh3 *Mesh)
virtual ~FSimpleMeshProcessingBaseOp ()
MODELINGOPERATORS_API void SetTransform (const FTransformSRT3d &XForm)
MODELINGOPERATORS_API void UpdateResultMeshNormals ()
MODELINGOPERATORS_API void UpdateResultMeshPositions ()
Public Member Functions inherited from UE::Geometry::FDynamicMeshOperator
FDynamicMeshOperator ()
virtual ~FDynamicMeshOperator ()
virtual void CalculateResult (FProgressCancel *Progress)=0
Calculate the result of the operator.
TUniquePtr< FDynamicMesh3 > ExtractResult ()
const FGeometryResult & GetResultInfo () const
const FTransformSRT3d & GetResultTransform () const
virtual void SetResultInfo (const FGeometryResult &Info)
Set the output information.
virtual void SetResultTransform (const FTransformSRT3d &Transform)
Set the output transform.
Protected Attributes
TArray< FVector3d > PositionBuffer
Protected Attributes inherited from UE::Geometry::FDynamicMeshOperator
FGeometryResult ResultInfo
TUniquePtr< FDynamicMesh3 > ResultMesh
FTransformSRT3d ResultTransform
Detailed Description
Dynamic Mesh Operator that has a separate PositionBuffer that contains copy of input vertex positions.
These can be modified by operator and then UpdateResultMeshPositions() can be copied to update ResultMesh.
UpdateResultMeshNormals() recalculates normals
Definition at line 35 of file SimpleMeshProcessingBaseOp.h.
Constructor & Destructor Documentation
FSimpleMeshProcessingBaseOp()
MODELINGOPERATORS_API UE::Geometry::FSimpleMeshProcessingBaseOp::FSimpleMeshProcessingBaseOp (const FDynamicMesh3 * Mesh)
References UE::Geometry::Mesh, and UE_API.
Referenced by UE::Geometry::FMeshOffsetBaseOp::FMeshOffsetBaseOp().
~FSimpleMeshProcessingBaseOp()
virtual UE::Geometry::FSimpleMeshProcessingBaseOp::~FSimpleMeshProcessingBaseOp () inline virtual
Definition at line 40 of file SimpleMeshProcessingBaseOp.h.
Member Function Documentation
SetTransform()
MODELINGOPERATORS_API void UE::Geometry::FSimpleMeshProcessingBaseOp::SetTransform (const FTransformSRT3d & XForm)
References UE_API.
UpdateResultMeshNormals()
MODELINGOPERATORS_API void UE::Geometry::FSimpleMeshProcessingBaseOp::UpdateResultMeshNormals ()
References UE_API.
Referenced by UE::Geometry::FMeshOffsetBaseOp::CalculateResult().
UpdateResultMeshPositions()
MODELINGOPERATORS_API void UE::Geometry::FSimpleMeshProcessingBaseOp::UpdateResultMeshPositions ()
References UE_API.
Referenced by UE::Geometry::FMeshOffsetBaseOp::CalculateResult().
Field Documentation
PositionBuffer
TArray<FVector3d> UE::Geometry::FSimpleMeshProcessingBaseOp::PositionBuffer protected
Definition at line 52 of file SimpleMeshProcessingBaseOp.h.
Referenced by UE::Geometry::FIterativeOffsetMeshOp::Offset(), UE::Geometry::FLaplacianOffsetMeshOp::Offset(), and UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed().
The documentation for this class was generated from the following file:
SimpleMeshProcessingBaseOp.h