Unreal Engine 5.6 C++ API: FDistanceFieldVolumeData Class Reference
FDistanceFieldVolumeData Class Reference
Distance field data payload and output of the mesh build process.
#include "DistanceFieldAtlas.h"
Public Member Functions
FDistanceFieldVolumeData ()
uint64 GetId () const
SIZE_T GetResourceSizeBytes () const
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) const
bool IsValid () const
void Serialize (FArchive &Ar, UObject *Owner)
Public Member Functions inherited from FDeferredCleanupInterface
virtual ~FDeferredCleanupInterface ()
Data Fields
TArray< uint8 > AlwaysLoadedMip
FName AssetName
bool bAsyncBuilding
bool bMostlyTwoSided
Whether most of the triangles in the mesh used a two-sided material.
uint64 Id
FBox3f LocalSpaceMeshBounds
Local space bounding box of the distance field volume.
TStaticArray< FSparseDistanceFieldMip, DistanceField::NumMips > Mips
FByteBulkData StreamableMips
Detailed Description
Distance field data payload and output of the mesh build process.
Definition at line 240 of file DistanceFieldAtlas.h.
Constructor & Destructor Documentation
FDistanceFieldVolumeData()
FDistanceFieldVolumeData::FDistanceFieldVolumeData ()
Member Function Documentation
GetId()
uint64 FDistanceFieldVolumeData::GetId () const inline
Definition at line 302 of file DistanceFieldAtlas.h.
References Id.
GetResourceSizeBytes()
SIZE_T FDistanceFieldVolumeData::GetResourceSizeBytes () const inline
Definition at line 279 of file DistanceFieldAtlas.h.
References GetResourceSizeEx(), and FResourceSizeEx::GetTotalMemoryBytes().
GetResourceSizeEx()
void FDistanceFieldVolumeData::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) const inline
Definition at line 267 of file DistanceFieldAtlas.h.
References FResourceSizeEx::AddDedicatedSystemMemoryBytes(), AlwaysLoadedMip, and Mips.
Referenced by GetResourceSizeBytes().
IsValid()
bool FDistanceFieldVolumeData::IsValid () const inline
Definition at line 286 of file DistanceFieldAtlas.h.
References Mips.
Serialize()
void FDistanceFieldVolumeData::Serialize (FArchive & Ar, UObject * Owner)
References Ar, and Owner.
Field Documentation
AlwaysLoadedMip
TArray<uint8> FDistanceFieldVolumeData::AlwaysLoadedMip
Definition at line 255 of file DistanceFieldAtlas.h.
Referenced by GetResourceSizeEx().
AssetName
FName FDistanceFieldVolumeData::AssetName
Definition at line 263 of file DistanceFieldAtlas.h.
bAsyncBuilding
bool FDistanceFieldVolumeData::bAsyncBuilding
Definition at line 250 of file DistanceFieldAtlas.h.
bMostlyTwoSided
bool FDistanceFieldVolumeData::bMostlyTwoSided
Whether most of the triangles in the mesh used a two-sided material.
Definition at line 248 of file DistanceFieldAtlas.h.
Id
uint64 FDistanceFieldVolumeData::Id
Definition at line 260 of file DistanceFieldAtlas.h.
Referenced by GetId().
LocalSpaceMeshBounds
FBox3f FDistanceFieldVolumeData::LocalSpaceMeshBounds
Local space bounding box of the distance field volume.
Definition at line 245 of file DistanceFieldAtlas.h.
Mips
TStaticArray<FSparseDistanceFieldMip, DistanceField::NumMips> FDistanceFieldVolumeData::Mips
Definition at line 252 of file DistanceFieldAtlas.h.
Referenced by GetResourceSizeEx(), and IsValid().
StreamableMips
FByteBulkData FDistanceFieldVolumeData::StreamableMips
Definition at line 258 of file DistanceFieldAtlas.h.
The documentation for this class was generated from the following file:
DistanceFieldAtlas.h