Unreal Engine 5.6 C++ API: FInstanceAttributeTracker Class Reference
FInstanceAttributeTracker Class Reference
Tracks changes for instances, but that assumes storing stuff per index except the removed status which must be kept ID-based Removed items are tracked by ID and kept separate as we need to remember if an item was ever removed in order to handle these correctly.
#include "InstanceAttributeTracker.h"
Data Structures
class FAnyValidIterator
Iterator for iterating tracked state with the given flags.
class FDeltaRange
Represents the delta range for a given attribute, can either refer to the tracked data or just a span, or be empty.
struct FToBit
Public Types
enum class EFlag : ElementType {
Added , TransformChanged , CustomDataChanged , IndexChanged ,
Num
}
Flag describing the changed attribute.
using ElementType = uint32
using FBitManip = UE::InstanceAttributeTracker::Implementation::FBitManip<ElementType>
Public Member Functions
FInstanceAttributeTracker ()
FInstanceAttributeTracker (FInstanceAttributeTracker &&Other)
FORCEINLINE SIZE_T GetAllocatedSize () const
template<uint32 Mask = AnyFlagMask>
FORCEINLINE FAnyValidIterator< Mask > GetChangedIterator () const
template<EFlag Flag>
FORCEINLINE FDeltaRange< Flag > GetDeltaRange (bool bForceFullUpdate, int32 InNumItems) const
FORCEINLINE ElementType GetFlags (int32 Index) const
Get the masked flags for a given index.
TConstSetBitIterator GetRemovedIterator () const
Get an iterator that iterates over the IDs (note, not index as they don't exist any more) of removed instances.
FORCEINLINE bool HasAnyChanges () const
template<EFlag Flag>
FORCEINLINE void MarkIndex (int32 Index, int32 MaxInstanceIndex)
FORCEINLINE void MarkRemoved (FPrimitiveInstanceId Id)
Lazy allocate bits in the bit vector tracking removed instances and set the flag for the instance ID.
void operator= (FInstanceAttributeTracker &&Other)
FORCEINLINE void RemoveAt (FPrimitiveInstanceId Id, int32 Index, int32 MaxInstanceIndex)
Mark removed & update the tracked bits (remove & move operation) Note: this is not something that should be used really as it forces the tracker to touch all the masks after the removed item...
FORCEINLINE void RemoveAtSwap (FPrimitiveInstanceId Id, int32 Index, int32 MaxInstanceIndex)
Mark removed & update the tracked bits (remove & swap operation)
void Reset ()
FORCEINLINE void SetNum (int32 InstanceIndexMax)
template<EFlag Flag>
FORCEINLINE bool TestFlag (int32 Index) const
Test a specific flag at a given index.
FORCEINLINE void Validate () const
Static Public Member Functions
static void Move (FInstanceAttributeTracker &Dest, FInstanceAttributeTracker &Source)
Static Public Attributes
static constexpr ElementType AnyFlagMask = (ElementType(1U) << uint32(EFlag::Num)) - ElementType(1U)
static constexpr uint32 BitsPerElement = sizeof(ElementType) * 8u
static constexpr int32 MasksPerElement = BitsPerElement / uint32(EFlag::Num)
Private Member Functions
FORCEINLINE void ClearLastElement ()
Clear the last item & all remaining in element to ensure it is always all zero.
FORCEINLINE void CountMaskChanges (ElementType Element, uint32 Offset, uint32 NumMasksInElement)
template<EFlag Flag>
FORCEINLINE void DecChangedCount (uint32 Flags)
FORCEINLINE void DecChangedCounts (int32 Index)
FORCEINLINE ElementType LoadCountAndMask (int32 ElementIndex, bool bHasNextElement)
Helper to load and count mask changes, returns the element with the IndexChanged applied to all items.
FORCEINLINE void SetMaskTo (int32 Index, ElementType Mask)
Private Attributes
TArray< ElementType > Data
Data for packed per-instance change attribute mask.
int32 FirstChangedIndex = MAX_int32
Tracks the first & last mask with any change flag set.
int32 FirstRemovedIdIndex = MAX_int32
Tracks the index of the first non-zero bit in the Removed bitvector.
int32 LastChangedIndex = 0
int32 MaxIndex = 0
Maximum valid index.
int32 NumChanged [uint32(EFlag::Num)]
Tracks the number of changes for each attribute in such a way that NumChanged[Added] + NumChanged[OtherAttribute] is the total number we need to copy over.
TBitArray Removed
Removed items are tracked by ID and kept separate as we need to remember if an item was ever removed in order to handle these correctly.
Static Private Attributes
static constexpr ElementType AddedElementMask = FBitManip::FRepMask<FToBit<EFlag::Added>::Bit, uint32(EFlag::Num)>::Result
static constexpr ElementType IndexChangedElementMask = FBitManip::FRepMask<FToBit<EFlag::IndexChanged>::Bit, uint32(EFlag::Num)>::Result
Masks replicated to all masks that fit inside ElementType.
Detailed Description
Tracks changes for instances, but that assumes storing stuff per index except the removed status which must be kept ID-based Removed items are tracked by ID and kept separate as we need to remember if an item was ever removed in order to handle these correctly.
Designed to use move semantics to clear the state and transfer to the updating worker task.
Definition at line 66 of file InstanceAttributeTracker.h.
Member Typedef Documentation
ElementType
using FInstanceAttributeTracker::ElementType = uint32
Definition at line 70 of file InstanceAttributeTracker.h.
FBitManip
using FInstanceAttributeTracker::FBitManip = UE::InstanceAttributeTracker::Implementation::FBitManip<ElementType>
Definition at line 72 of file InstanceAttributeTracker.h.
Member Enumeration Documentation
EFlag
enum class FInstanceAttributeTracker::EFlag : ElementType strong
Flag describing the changed attribute.
Note that not all are created equal, see comments.
Enumerator
Added
TransformChanged
Set when.
CustomDataChanged
IndexChanged
Num
Implicitly set when calling Remove or RemoveAt as this causes movement to fill holes.
Definition at line 78 of file InstanceAttributeTracker.h.
Constructor & Destructor Documentation
FInstanceAttributeTracker() [1/2]
FInstanceAttributeTracker::FInstanceAttributeTracker ()
Referenced by FInstanceAttributeTracker::FAnyValidIterator< Mask >::FAnyValidIterator(), FInstanceAttributeTracker::FDeltaRange< Flag >::FDeltaRange(), FInstanceAttributeTracker(), Move(), and operator=().
FInstanceAttributeTracker() [2/2]
FInstanceAttributeTracker::FInstanceAttributeTracker (FInstanceAttributeTracker && Other)
References FInstanceAttributeTracker(), and Other.
Member Function Documentation
ClearLastElement()
FORCEINLINE void FInstanceAttributeTracker::ClearLastElement () inline private
Clear the last item & all remaining in element to ensure it is always all zero.
Definition at line 566 of file InstanceAttributeTracker.h.
References Data, FORCEINLINE, MasksPerElement, MaxIndex, and Num.
Referenced by RemoveAt(), and RemoveAtSwap().
CountMaskChanges()
FORCEINLINE void FInstanceAttributeTracker::CountMaskChanges (ElementType Element, uint32 Offset, uint32 NumMasksInElement) inline private
Definition at line 616 of file InstanceAttributeTracker.h.
References Added, AddedElementMask, check, FORCEINLINE, IndexChanged, IndexChangedElementMask, MasksPerElement, Num, and NumChanged.
Referenced by LoadCountAndMask(), and RemoveAt().
DecChangedCount()
template<EFlag Flag> FORCEINLINE void FInstanceAttributeTracker::DecChangedCount (uint32 Flags) inline private
Definition at line 587 of file InstanceAttributeTracker.h.
References FInstanceAttributeTracker::FToBit< Flag >::Bit, check, Flags, FORCEINLINE, and NumChanged.
Referenced by DecChangedCounts().
DecChangedCounts()
FORCEINLINE void FInstanceAttributeTracker::DecChangedCounts (int32 Index) inline private
Definition at line 598 of file InstanceAttributeTracker.h.
References Added, FInstanceAttributeTracker::FToBit< Flag >::Bit, check, DecChangedCount(), FORCEINLINE, GetFlags(), and NumChanged.
Referenced by RemoveAt(), and RemoveAtSwap().
GetAllocatedSize()
FORCEINLINE SIZE_T FInstanceAttributeTracker::GetAllocatedSize () const inline
Definition at line 541 of file InstanceAttributeTracker.h.
References Data, FORCEINLINE, and Removed.
GetChangedIterator()
template<uint32 Mask = AnyFlagMask> FORCEINLINE FAnyValidIterator< Mask > FInstanceAttributeTracker::GetChangedIterator () const inline
Definition at line 399 of file InstanceAttributeTracker.h.
References FirstChangedIndex, FORCEINLINE, MaxIndex, and FMath::Min.
GetDeltaRange()
template<EFlag Flag> FORCEINLINE FDeltaRange< Flag > FInstanceAttributeTracker::GetDeltaRange (bool bForceFullUpdate, int32 InNumItems) const inline
Definition at line 530 of file InstanceAttributeTracker.h.
References FORCEINLINE.
GetFlags()
FORCEINLINE ElementType FInstanceAttributeTracker::GetFlags (int32 Index) const inline
Get the masked flags for a given index.
Definition at line 279 of file InstanceAttributeTracker.h.
References AnyFlagMask, check, Data, FORCEINLINE, MasksPerElement, MaxIndex, and Num.
Referenced by DecChangedCounts(), RemoveAtSwap(), and TestFlag().
GetRemovedIterator()
TConstSetBitIterator FInstanceAttributeTracker::GetRemovedIterator () const
Get an iterator that iterates over the IDs (note, not index as they don't exist any more) of removed instances.
The remove flag is not cleared when a new instances is added.
HasAnyChanges()
FORCEINLINE bool FInstanceAttributeTracker::HasAnyChanges () const inline
Definition at line 536 of file InstanceAttributeTracker.h.
References FORCEINLINE, MaxIndex, and Removed.
LoadCountAndMask()
FORCEINLINE ElementType FInstanceAttributeTracker::LoadCountAndMask (int32 ElementIndex, bool bHasNextElement) inline private
Helper to load and count mask changes, returns the element with the IndexChanged applied to all items.
Used while moving elements in the compacting RemoveAt
Definition at line 635 of file InstanceAttributeTracker.h.
References CountMaskChanges(), Data, FORCEINLINE, IndexChangedElementMask, MasksPerElement, MaxIndex, and FMath::Min.
Referenced by RemoveAt().
MarkIndex()
template<EFlag Flag> FORCEINLINE void FInstanceAttributeTracker::MarkIndex (int32 Index, int32 MaxInstanceIndex) inline
Definition at line 245 of file InstanceAttributeTracker.h.
References FInstanceAttributeTracker::FToBit< Flag >::Bit, check, Data, FirstChangedIndex, FORCEINLINE, LastChangedIndex, MasksPerElement, FMath::Max, MaxIndex, FMath::Min, Num, NumChanged, SetNum(), and Validate().
MarkRemoved()
FORCEINLINE void FInstanceAttributeTracker::MarkRemoved (FPrimitiveInstanceId Id) inline
Lazy allocate bits in the bit vector tracking removed instances and set the flag for the instance ID.
Also updates the FirstRemovedIdIndex, such that we can start iteration from that bit.
Definition at line 127 of file InstanceAttributeTracker.h.
References FMath::DivideAndRoundUp(), FirstRemovedIdIndex, FORCEINLINE, FMath::Min, and Removed.
Referenced by RemoveAt(), and RemoveAtSwap().
Move()
void FInstanceAttributeTracker::Move (FInstanceAttributeTracker & Dest, FInstanceAttributeTracker & Source) static
References FInstanceAttributeTracker(), and Source.
operator=()
void FInstanceAttributeTracker::operator= (FInstanceAttributeTracker && Other)
References FInstanceAttributeTracker(), and Other.
RemoveAt()
FORCEINLINE void FInstanceAttributeTracker::RemoveAt (FPrimitiveInstanceId Id, int32 Index, int32 MaxInstanceIndex) inline
Mark removed & update the tracked bits (remove & move operation) Note: this is not something that should be used really as it forces the tracker to touch all the masks after the removed item...
Definition at line 182 of file InstanceAttributeTracker.h.
References ClearLastElement(), CountMaskChanges(), Data, DecChangedCounts(), FirstChangedIndex, FORCEINLINE, IndexChangedElementMask, LastChangedIndex, LoadCountAndMask(), MarkRemoved(), Mask, MasksPerElement, FMath::Max, MaxIndex, FMath::Min, Num, SetNum(), and Validate().
RemoveAtSwap()
FORCEINLINE void FInstanceAttributeTracker::RemoveAtSwap (FPrimitiveInstanceId Id, int32 Index, int32 MaxInstanceIndex) inline
Mark removed & update the tracked bits (remove & swap operation)
Definition at line 145 of file InstanceAttributeTracker.h.
References FInstanceAttributeTracker::FToBit< Flag >::Bit, check, ClearLastElement(), DecChangedCounts(), FirstChangedIndex, FORCEINLINE, GetFlags(), IndexChanged, LastChangedIndex, MarkRemoved(), FMath::Max, MaxIndex, FMath::Min, NumChanged, SetMaskTo(), SetNum(), and Validate().
Reset()
void FInstanceAttributeTracker::Reset ()
SetMaskTo()
FORCEINLINE void FInstanceAttributeTracker::SetMaskTo (int32 Index, ElementType Mask) inline private
Definition at line 550 of file InstanceAttributeTracker.h.
References AnyFlagMask, check, Data, FORCEINLINE, Mask, MasksPerElement, MaxIndex, and Num.
Referenced by RemoveAtSwap().
SetNum()
FORCEINLINE void FInstanceAttributeTracker::SetNum (int32 InstanceIndexMax) inline
Definition at line 298 of file InstanceAttributeTracker.h.
References Data, FMath::DivideAndRoundUp(), FORCEINLINE, MasksPerElement, MaxIndex, and Validate().
Referenced by MarkIndex(), RemoveAt(), and RemoveAtSwap().
TestFlag()
template<EFlag Flag> FORCEINLINE bool FInstanceAttributeTracker::TestFlag (int32 Index) const inline
Test a specific flag at a given index.
Definition at line 291 of file InstanceAttributeTracker.h.
References FInstanceAttributeTracker::FToBit< Flag >::Bit, FORCEINLINE, and GetFlags().
Validate()
FORCEINLINE void FInstanceAttributeTracker::Validate () const inline
Definition at line 407 of file InstanceAttributeTracker.h.
References FORCEINLINE.
Referenced by MarkIndex(), RemoveAt(), RemoveAtSwap(), and SetNum().
Field Documentation
AddedElementMask
ElementType FInstanceAttributeTracker::AddedElementMask = FBitManip::FRepMask<FToBit<EFlag::Added>::Bit, uint32(EFlag::Num)>::Result static constexpr private
Definition at line 674 of file InstanceAttributeTracker.h.
Referenced by CountMaskChanges().
AnyFlagMask
ElementType FInstanceAttributeTracker::AnyFlagMask = (ElementType(1U) << uint32(EFlag::Num)) - ElementType(1U) static constexpr
Definition at line 89 of file InstanceAttributeTracker.h.
Referenced by GetFlags(), and SetMaskTo().
BitsPerElement
uint32 FInstanceAttributeTracker::BitsPerElement = sizeof(ElementType) * 8u static constexpr
Definition at line 87 of file InstanceAttributeTracker.h.
Data
TArray<ElementType> FInstanceAttributeTracker::Data private
Data for packed per-instance change attribute mask.
Definition at line 650 of file InstanceAttributeTracker.h.
Referenced by FInstanceAttributeTracker::FAnyValidIterator< Mask >::AdvanceUntilAny(), ClearLastElement(), GetAllocatedSize(), GetFlags(), LoadCountAndMask(), MarkIndex(), RemoveAt(), SetMaskTo(), and SetNum().
FirstChangedIndex
int32 FInstanceAttributeTracker::FirstChangedIndex = MAX_int32 private
Tracks the first & last mask with any change flag set.
Definition at line 662 of file InstanceAttributeTracker.h.
Referenced by GetChangedIterator(), MarkIndex(), RemoveAt(), and RemoveAtSwap().
FirstRemovedIdIndex
int32 FInstanceAttributeTracker::FirstRemovedIdIndex = MAX_int32 private
Tracks the index of the first non-zero bit in the Removed bitvector.
Definition at line 659 of file InstanceAttributeTracker.h.
Referenced by MarkRemoved().
IndexChangedElementMask
ElementType FInstanceAttributeTracker::IndexChangedElementMask = FBitManip::FRepMask<FToBit<EFlag::IndexChanged>::Bit, uint32(EFlag::Num)>::Result static constexpr private
Masks replicated to all masks that fit inside ElementType.
Definition at line 673 of file InstanceAttributeTracker.h.
Referenced by CountMaskChanges(), LoadCountAndMask(), and RemoveAt().
LastChangedIndex
int32 FInstanceAttributeTracker::LastChangedIndex = 0 private
Definition at line 663 of file InstanceAttributeTracker.h.
Referenced by MarkIndex(), RemoveAt(), and RemoveAtSwap().
MasksPerElement
int32 FInstanceAttributeTracker::MasksPerElement = BitsPerElement / uint32(EFlag::Num) static constexpr
Definition at line 88 of file InstanceAttributeTracker.h.
Referenced by FInstanceAttributeTracker::FAnyValidIterator< Mask >::FAnyValidIterator(), ClearLastElement(), CountMaskChanges(), GetFlags(), FInstanceAttributeTracker::FAnyValidIterator< Mask >::GetIndex(), LoadCountAndMask(), MarkIndex(), RemoveAt(), SetMaskTo(), and SetNum().
MaxIndex
int32 FInstanceAttributeTracker::MaxIndex = 0 private
Maximum valid index.
Definition at line 656 of file InstanceAttributeTracker.h.
Referenced by ClearLastElement(), GetChangedIterator(), GetFlags(), HasAnyChanges(), LoadCountAndMask(), MarkIndex(), RemoveAt(), RemoveAtSwap(), SetMaskTo(), and SetNum().
NumChanged
int32 FInstanceAttributeTracker::NumChanged[uint32(EFlag::Num)] private
Tracks the number of changes for each attribute in such a way that NumChanged[Added] + NumChanged[OtherAttribute] is the total number we need to copy over.
This works by counting other attributes ONLY if the Added flag is not also set.
Definition at line 670 of file InstanceAttributeTracker.h.
Referenced by CountMaskChanges(), DecChangedCount(), DecChangedCounts(), MarkIndex(), and RemoveAtSwap().
Removed
TBitArray FInstanceAttributeTracker::Removed private
Removed items are tracked by ID and kept separate as we need to remember if an item was ever removed in order to handle these correctly.
Definition at line 653 of file InstanceAttributeTracker.h.
Referenced by GetAllocatedSize(), HasAnyChanges(), and MarkRemoved().
The documentation for this class was generated from the following file:
InstanceAttributeTracker.h