Unreal Engine 5.6 C++ API: FShaderCompilerEnvironment Struct Reference
FShaderCompilerEnvironment Struct Reference
The environment used to compile a shader.
#include "ShaderCore.h"
Public Member Functions
RENDERCORE_API FShaderCompilerEnvironment ()
Default constructor.
RENDERCORE_API FShaderCompilerEnvironment (FMemoryHasherBlake3 &Hasher)
Constructor used when enviroment is constructed temporarily purely for the purpose of hashing for inclusion in DDC keys.
template<typename ValueType>
ValueType GetCompileArgument (const TCHAR *Name, const ValueType &DefaultValue) const
template<typename ValueType>
bool GetCompileArgument (const TCHAR *Name, ValueType &OutValue) const
RENDERCORE_API FString GetDefinitionsAsCommentedCode () const
bool HasCompileArgument (const TCHAR *Name) const
RENDERCORE_API void Merge (const FShaderCompilerEnvironment &Other)
RENDERCORE_API void SerializeCompilationDependencies (FArchive &Ar)
RENDERCORE_API void SerializeEverythingButFiles (FArchive &Ar)
This "core" serialization is also used for the hashing the compiler job (where files are handled differently).
void SetCompileArgument (const TCHAR *Name, TVariant< bool, float, int32, uint32, FString > Value)
template<typename ValueType>
void SetCompileArgument (const TCHAR *Name, ValueType Value)
RENDERCORE_API void SetDefine (const TCHAR *Name, bool Value)
RENDERCORE_API void SetDefine (const TCHAR *Name, const FString &Value)
RENDERCORE_API void SetDefine (const TCHAR *Name, const TCHAR *Value)
Works for TCHAR e.g.
RENDERCORE_API void SetDefine (const TCHAR *Name, float Value)
RENDERCORE_API void SetDefine (const TCHAR *Name, int32 Value)
RENDERCORE_API void SetDefine (const TCHAR *Name, uint32 Value)
RENDERCORE_API void SetDefine (FName Name, bool Value)
RENDERCORE_API void SetDefine (FName Name, const FString &Value)
RENDERCORE_API void SetDefine (FName Name, const TCHAR *Value)
RENDERCORE_API void SetDefine (FName Name, float Value)
RENDERCORE_API void SetDefine (FName Name, int32 Value)
RENDERCORE_API void SetDefine (FName Name, uint32 Value)
RENDERCORE_API void SetDefine (FShaderCompilerDefineNameCache &Name, bool Value)
RENDERCORE_API void SetDefine (FShaderCompilerDefineNameCache &Name, const FString &Value)
RENDERCORE_API void SetDefine (FShaderCompilerDefineNameCache &Name, const TCHAR *Value)
RENDERCORE_API void SetDefine (FShaderCompilerDefineNameCache &Name, float Value)
RENDERCORE_API void SetDefine (FShaderCompilerDefineNameCache &Name, int32 Value)
RENDERCORE_API void SetDefine (FShaderCompilerDefineNameCache &Name, uint32 Value)
template<typename ValueType>
void SetDefineAndCompileArgument (const TCHAR *Name, ValueType Value)
template<typename ValueType>
void SetDefineIfUnset (const TCHAR *Name, ValueType Value)
void SetRenderTargetOutputFormat (uint32 RenderTargetIndex, EPixelFormat PixelFormat)
UE_DEPRECATED (5.5, "Accessing definition values via FShaderCompilerEnvironment is no longer allowed outside of the core shader system.\n" "Please use Get/SetCompileArgument mechanism for additional properties required by compilation.") RENDERCORE_API int32 GetIntegerValue(FName Name) const
UE_DEPRECATED (5.5, "Accessing definition values via FShaderCompilerEnvironment is no longer allowed outside of the core shader system.\n" "Please use Get/SetCompileArgument mechanism for additional properties required by compilation.") RENDERCORE_API int32 GetIntegerValue(FShaderCompilerDefineNameCache &NameCache
UE_DEPRECATED (5.5, "ContainsDefinition will be made private in the future and should not be called by downstream code.") RENDERCORE_API bool ContainsDefinition(FName Name) const
Data Fields
FShaderCompilerFlags CompilerFlags
bool FullPrecisionInPS = 0
TMap< FString, FString > IncludeVirtualPathToContentsMap
TMap< FString, FThreadSafeSharedAnsiStringPtr > IncludeVirtualPathToSharedContentsMap
TMap< uint32, uint8 > RenderTargetOutputFormatsMap
FShaderResourceTableMap ResourceTableMap
int32 ResultIfNotFound = 0) const
FRHIShaderBindingLayout RHIShaderBindingLayout
const FShaderBindingLayout * ShaderBindingLayout = nullptr
const ITargetPlatform * TargetPlatform = nullptr
TMap< FString, FUniformBufferEntry > UniformBufferMap
Private Attributes
TMap< FString, TVariant< bool, float, int32, uint32, FString > > CompileArgs
TPimplPtr< FShaderCompilerDefinitions, EPimplPtrMode::DeepCopy > Definitions
FMemoryHasherBlake3 * Hasher = nullptr
TMap< FString, FString > UnusedStringDefinitions
Unused data kept around for deprecated FShaderCompilerEnvironment::GetDefinitions call.
Friends
class FShaderCompileUtilities
class FShaderPreprocessorUtilities
FArchive & operator<< (FArchive &Ar, FShaderCompilerEnvironment &Environment)
Detailed Description
The environment used to compile a shader.
Definition at line 540 of file ShaderCore.h.
Constructor & Destructor Documentation
FShaderCompilerEnvironment() [1/2]
RENDERCORE_API FShaderCompilerEnvironment::FShaderCompilerEnvironment ()
Default constructor.
Referenced by Merge(), and operator<<.
FShaderCompilerEnvironment() [2/2]
RENDERCORE_API FShaderCompilerEnvironment::FShaderCompilerEnvironment (FMemoryHasherBlake3 & Hasher)
Constructor used when enviroment is constructed temporarily purely for the purpose of hashing for inclusion in DDC keys.
References Hasher.
Member Function Documentation
GetCompileArgument() [1/2]
template<typename ValueType> ValueType FShaderCompilerEnvironment::GetCompileArgument (const TCHAR * Name, const ValueType & DefaultValue) const inline
Definition at line 657 of file ShaderCore.h.
References CompileArgs, TVariant< T, Ts >::Get(), TVariant< T, Ts >::IsType(), and Name.
GetCompileArgument() [2/2]
template<typename ValueType> bool FShaderCompilerEnvironment::GetCompileArgument (const TCHAR * Name, ValueType & OutValue) const inline
Definition at line 670 of file ShaderCore.h.
References CompileArgs, TVariant< T, Ts >::Get(), TVariant< T, Ts >::IsType(), and Name.
GetDefinitionsAsCommentedCode()
RENDERCORE_API FString FShaderCompilerEnvironment::GetDefinitionsAsCommentedCode () const
HasCompileArgument()
bool FShaderCompilerEnvironment::HasCompileArgument (const TCHAR * Name) const inline
Definition at line 646 of file ShaderCore.h.
References CompileArgs, and Name.
Merge()
RENDERCORE_API void FShaderCompilerEnvironment::Merge (const FShaderCompilerEnvironment & Other)
References FShaderCompilerEnvironment(), and Other.
SerializeCompilationDependencies()
RENDERCORE_API void FShaderCompilerEnvironment::SerializeCompilationDependencies (FArchive & Ar)
References Ar.
SerializeEverythingButFiles()
RENDERCORE_API void FShaderCompilerEnvironment::SerializeEverythingButFiles (FArchive & Ar)
This "core" serialization is also used for the hashing the compiler job (where files are handled differently).
Should stay in sync with the ShaderCompileWorker.
References Ar.
Referenced by operator<<.
SetCompileArgument() [1/2]
void FShaderCompilerEnvironment::SetCompileArgument (const TCHAR * Name, TVariant< bool, float, int32, uint32, FString > Value) inline
Definition at line 632 of file ShaderCore.h.
References CompileArgs, MoveTempIfPossible(), Name, and Value.
SetCompileArgument() [2/2]
template<typename ValueType> void FShaderCompilerEnvironment::SetCompileArgument (const TCHAR * Name, ValueType Value) inline
Definition at line 626 of file ShaderCore.h.
References CompileArgs, Name, and Value.
Referenced by SetDefineAndCompileArgument().
SetDefine() [1/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (const TCHAR * Name, bool Value)
References Name, and Value.
SetDefine() [2/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (const TCHAR * Name, const FString & Value)
References Name, and Value.
SetDefine() [3/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (const TCHAR * Name, const TCHAR * Value)
Works for TCHAR e.g.
SetDefine(TEXT("NAME"), TEXT("Test")); e.g. SetDefine(TEXT("NUM_SAMPLES"), 1); e.g. SetDefine(TEXT("DOIT"), true);
Or use optimized macros, which can cache FName and map lookups to improve performance: e.g. SET_SHADER_DEFINE(NAME, TEXT("Test")); e.g. SET_SHADER_DEFINE(NUM_SAMPLES, 1); e.g. SET_SHADER_DEFINE(DOIT, true);
References Name, and Value.
Referenced by FIESLightProfilePS::ModifyCompilationEnvironment(), FInstancedScreenVertexShaderVS::ModifyCompilationEnvironment(), FMobileMultiViewVertexShaderVS::ModifyCompilationEnvironment(), FParticleVertexFactoryBase::ModifyCompilationEnvironment(), FScreenFromSlice0PS::ModifyCompilationEnvironment(), FScreenPSArraySlice::ModifyCompilationEnvironment(), FScreenUnwrapSlicesPS::ModifyCompilationEnvironment(), FSimpleElementGammaPS< true >::ModifyCompilationEnvironment(), FSimpleElementMaskedGammaPS< true >::ModifyCompilationEnvironment(), FVertexFactoryType::ModifyCompilationEnvironment(), TClearReplacementBase< EClearReplacementValueType::Uint32, 1, false, false >::ModifyCompilationEnvironment(), TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds >::ModifyCompilationEnvironment(), TClearReplacementPS< false, FClearReplacementBase_Float4 >::ModifyCompilationEnvironment(), TClearReplacementVS< false, FClearReplacementBase_Float4_Zero >::ModifyCompilationEnvironment(), TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ModifyCompilationEnvironment(), TOneColorVS< bUsingNDCPositions, bUsingVertexLayers >::ModifyCompilationEnvironment(), TShaderPermutationDomainSpetialization< BooleanSpecialization >::ModifyCompilationEnvironment(), TUpdateTexture2DSubresourceCS< ValueType >::ModifyCompilationEnvironment(), SetDefineAndCompileArgument(), and SetDefineIfUnset().
SetDefine() [4/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (const TCHAR * Name, float Value)
References Name, and Value.
SetDefine() [5/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (const TCHAR * Name, int32 Value)
References Name, and Value.
SetDefine() [6/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (const TCHAR * Name, uint32 Value)
References Name, and Value.
SetDefine() [7/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FName Name, bool Value)
References Name, and Value.
SetDefine() [8/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FName Name, const FString & Value)
References Name, and Value.
SetDefine() [9/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FName Name, const TCHAR * Value)
References Name, and Value.
SetDefine() [10/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FName Name, float Value)
References Name, and Value.
SetDefine() [11/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FName Name, int32 Value)
References Name, and Value.
SetDefine() [12/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FName Name, uint32 Value)
References Name, and Value.
SetDefine() [13/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FShaderCompilerDefineNameCache & Name, bool Value)
References Name, and Value.
SetDefine() [14/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FShaderCompilerDefineNameCache & Name, const FString & Value)
References Name, and Value.
SetDefine() [15/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FShaderCompilerDefineNameCache & Name, const TCHAR * Value)
References Name, and Value.
SetDefine() [16/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FShaderCompilerDefineNameCache & Name, float Value)
References Name, and Value.
SetDefine() [17/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FShaderCompilerDefineNameCache & Name, int32 Value)
References Name, and Value.
SetDefine() [18/18]
RENDERCORE_API void FShaderCompilerEnvironment::SetDefine (FShaderCompilerDefineNameCache & Name, uint32 Value)
References Name, and Value.
SetDefineAndCompileArgument()
template<typename ValueType> void FShaderCompilerEnvironment::SetDefineAndCompileArgument (const TCHAR * Name, ValueType Value) inline
Definition at line 639 of file ShaderCore.h.
References Name, SetCompileArgument(), SetDefine(), and Value.
SetDefineIfUnset()
template<typename ValueType> void FShaderCompilerEnvironment::SetDefineIfUnset (const TCHAR * Name, ValueType Value) inline
Definition at line 612 of file ShaderCore.h.
References Name, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, SetDefine(), SetDefineIfUnset(), and Value.
Referenced by SetDefineIfUnset().
SetRenderTargetOutputFormat()
void FShaderCompilerEnvironment::SetRenderTargetOutputFormat (uint32 RenderTargetIndex, EPixelFormat PixelFormat) inline
Definition at line 681 of file ShaderCore.h.
References RenderTargetOutputFormatsMap, and UE_PIXELFORMAT_TO_UINT8.
Referenced by TClearReplacementPS< false, FClearReplacementBase_Float4 >::ModifyCompilationEnvironment().
UE_DEPRECATED() [1/3]
FShaderCompilerEnvironment::UE_DEPRECATED (5. 5, "Accessing definition values via FShaderCompilerEnvironment is no longer allowed outside of the core shader system.\n" "Please use Get/SetCompileArgument mechanism for additional properties required by compilation.") const
References Name.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FShaderCompilerEnvironment::UE_DEPRECATED (5. 5, "Accessing definition values via FShaderCompilerEnvironment is no longer allowed outside of the core shader system.\n" "Please use Get/SetCompileArgument mechanism for additional properties required by compilation.") &
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FShaderCompilerEnvironment::UE_DEPRECATED (5. 5, "ContainsDefinition will be made private in the future and should not be called by downstream code.") const
References Name, and UE_DEPRECATED().
Friends And Related Symbol Documentation
FShaderCompileUtilities
friend class FShaderCompileUtilities friend
Definition at line 709 of file ShaderCore.h.
References FShaderCompileUtilities.
Referenced by FShaderCompileUtilities.
FShaderPreprocessorUtilities
friend class FShaderPreprocessorUtilities friend
Definition at line 710 of file ShaderCore.h.
References FShaderPreprocessorUtilities.
Referenced by FShaderPreprocessorUtilities.
operator<<
FArchive & operator<< (FArchive & Ar, FShaderCompilerEnvironment & Environment) friend
Definition at line 692 of file ShaderCore.h.
References FShaderCompilerEnvironment(), Ar, IncludeVirtualPathToContentsMap, and SerializeEverythingButFiles().
Field Documentation
CompileArgs
TMap<FString, TVariant<bool, float, int32, uint32, FString> > FShaderCompilerEnvironment::CompileArgs private
Definition at line 716 of file ShaderCore.h.
Referenced by GetCompileArgument(), GetCompileArgument(), HasCompileArgument(), SetCompileArgument(), and SetCompileArgument().
CompilerFlags
FShaderCompilerFlags FShaderCompilerEnvironment::CompilerFlags
Definition at line 548 of file ShaderCore.h.
Referenced by FCopyTextureCS::ModifyCompilationEnvironment(), FUpdateTextureShaderBase::ModifyCompilationEnvironment(), and TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds >::ModifyCompilationEnvironment().
Definitions
TPimplPtr<FShaderCompilerDefinitions, EPimplPtrMode::DeepCopy> FShaderCompilerEnvironment::Definitions private
Definition at line 712 of file ShaderCore.h.
FullPrecisionInPS
bool FShaderCompilerEnvironment::FullPrecisionInPS = 0
Definition at line 562 of file ShaderCore.h.
Hasher
FMemoryHasherBlake3* FShaderCompilerEnvironment::Hasher = nullptr private
Definition at line 714 of file ShaderCore.h.
Referenced by FShaderCompilerEnvironment().
IncludeVirtualPathToContentsMap
TMap<FString,FString> FShaderCompilerEnvironment::IncludeVirtualPathToContentsMap
Definition at line 544 of file ShaderCore.h.
Referenced by FVertexFactoryType::ModifyCompilationEnvironment(), and operator<<.
IncludeVirtualPathToSharedContentsMap
TMap<FString, FThreadSafeSharedAnsiStringPtr> FShaderCompilerEnvironment::IncludeVirtualPathToSharedContentsMap
Definition at line 546 of file ShaderCore.h.
RenderTargetOutputFormatsMap
TMap<uint32,uint8> FShaderCompilerEnvironment::RenderTargetOutputFormatsMap
Definition at line 549 of file ShaderCore.h.
Referenced by SetRenderTargetOutputFormat().
ResourceTableMap
FShaderResourceTableMap FShaderCompilerEnvironment::ResourceTableMap
Definition at line 550 of file ShaderCore.h.
ResultIfNotFound
int32 FShaderCompilerEnvironment::ResultIfNotFound = 0) const
Definition at line 607 of file ShaderCore.h.
RHIShaderBindingLayout
FRHIShaderBindingLayout FShaderCompilerEnvironment::RHIShaderBindingLayout
Definition at line 557 of file ShaderCore.h.
ShaderBindingLayout
const FShaderBindingLayout* FShaderCompilerEnvironment::ShaderBindingLayout = nullptr
Definition at line 554 of file ShaderCore.h.
TargetPlatform
const ITargetPlatform* FShaderCompilerEnvironment::TargetPlatform = nullptr
Definition at line 559 of file ShaderCore.h.
UniformBufferMap
TMap<FString, FUniformBufferEntry> FShaderCompilerEnvironment::UniformBufferMap
Definition at line 551 of file ShaderCore.h.
UnusedStringDefinitions
TMap<FString, FString> FShaderCompilerEnvironment::UnusedStringDefinitions private
Unused data kept around for deprecated FShaderCompilerEnvironment::GetDefinitions call.
Definition at line 719 of file ShaderCore.h.
The documentation for this struct was generated from the following file:
ShaderCore.h