Unreal Engine 5.6 C++ API: TCbFieldIterator< FieldType > Class Template Reference
TCbFieldIterator< FieldType > Class Template Reference
Iterator for FCbField[View] that can operate on any contiguous range of fields.
#include "CompactBinary.h"
Public Member Functions
constexpr TCbFieldIterator ()=default
Construct an empty field range.
void AppendRangeHash (FIoHashBuilder &Builder) const
Append the hash of every field in the range.
constexpr TCbFieldIterator begin () const
DO NOT USE DIRECTLY.
void CopyRangeTo (FArchive &Ar) const
Copy the field range into an archive, as if calling CopyTo on every field.
void CopyRangeTo (FMutableMemoryView Buffer) const
Copy the field range into a buffer of exactly GetRangeSize() bytes.
constexpr FCbIteratorSentinel end () const
template<typename OtherFieldType>
constexpr bool Equals (const TCbFieldIterator< OtherFieldType > &Other) const
FIoHash GetRangeHash () const
Calculate the hash of every field in the range.
uint64 GetRangeSize () const
Returns the size of the fields in the range in bytes.
void IterateRangeAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field range.
constexpr bool operator!= (const FCbIteratorSentinel &) const
template<typename OtherFieldType>
constexpr bool operator!= (const TCbFieldIterator< OtherFieldType > &Other) const
constexpr FieldType & operator* ()
TCbFieldIterator & operator++ ()
TCbFieldIterator operator++ (int)
constexpr FieldType * operator-> ()
constexpr bool operator== (const FCbIteratorSentinel &) const
template<typename OtherFieldType>
constexpr bool operator== (const TCbFieldIterator< OtherFieldType > &Other) const
void Reset ()
Reset this to an empty field range.
bool TryGetRangeView (FMemoryView &OutView) const
Try to get a view of every field in the range as they would be serialized.
Protected Member Functions
constexpr TCbFieldIterator (FieldType &&InField, const void *InFieldsEnd)
Construct a field range from the first field and a pointer to the end of the last field.
constexpr TCbFieldIterator (FieldType InField)
Construct a field range that contains exactly one field.
Static Protected Member Functions
template<typename OtherFieldType>
static const void * GetFieldsEnd (const TCbFieldIterator< OtherFieldType > &It)
Returns the end of the last field, or null for an iterator at the end.
Private Attributes
const void * FieldsEnd = nullptr
Pointer to the first byte past the end of the last field.
Friends
template<typename OtherType>
class TCbFieldIterator
Detailed Description
template<typename FieldType>
class TCbFieldIterator< FieldType >
Iterator for FCbField[View] that can operate on any contiguous range of fields.
The iterator is the current field that the iterator points to and exposes the full interface of FCbField[View]. An iterator that is at the end is equivalent to a field with no value.
The iterator represents a range of fields from the current field to the last field.
Definition at line 341 of file CompactBinary.h.
Constructor & Destructor Documentation
TCbFieldIterator() [1/3]
template<typename FieldType> TCbFieldIterator< FieldType >::TCbFieldIterator () constexpr default
Construct an empty field range.
TCbFieldIterator() [2/3]
template<typename FieldType> TCbFieldIterator< FieldType >::TCbFieldIterator (FieldType InField) inline explicit constexpr protected
Construct a field range that contains exactly one field.
Definition at line 425 of file CompactBinary.h.
References FieldsEnd, and MoveTemp().
TCbFieldIterator() [3/3]
template<typename FieldType> TCbFieldIterator< FieldType >::TCbFieldIterator (FieldType && InField, const void * InFieldsEnd) inline constexpr protected
Construct a field range from the first field and a pointer to the end of the last field.
Parameters
InField The first field, or the default field if there are no fields.
InFieldsEnd A pointer to the end of the value of the last field, or null.
Definition at line 437 of file CompactBinary.h.
References FieldsEnd, and MoveTemp().
Member Function Documentation
AppendRangeHash()
template<typename FieldType> void TCbFieldIterator< FieldType >::AppendRangeHash (FIoHashBuilder & Builder) const
Append the hash of every field in the range.
begin()
template<typename FieldType> TCbFieldIterator TCbFieldIterator< FieldType >::begin () const inline constexpr
DO NOT USE DIRECTLY.
These functions enable range-based for loop support.
Definition at line 420 of file CompactBinary.h.
References TCbFieldIterator.
CopyRangeTo() [1/2]
template<typename FieldType> void TCbFieldIterator< FieldType >::CopyRangeTo (FArchive & Ar) const
Copy the field range into an archive, as if calling CopyTo on every field.
References Ar.
CopyRangeTo() [2/2]
template<typename FieldType> void TCbFieldIterator< FieldType >::CopyRangeTo (FMutableMemoryView Buffer) const
Copy the field range into a buffer of exactly GetRangeSize() bytes.
References Buffer.
end()
template<typename FieldType> FCbIteratorSentinel TCbFieldIterator< FieldType >::end () const inline constexpr
Definition at line 421 of file CompactBinary.h.
Equals()
template<typename FieldType> template<typename OtherFieldType> bool TCbFieldIterator< FieldType >::Equals (const TCbFieldIterator< OtherFieldType > & Other) const inline constexpr
Definition at line 373 of file CompactBinary.h.
References TCbFieldIterator, FieldsEnd, and Other.
Referenced by operator!=(), and operator==().
GetFieldsEnd()
template<typename FieldType> template<typename OtherFieldType> const void * TCbFieldIterator< FieldType >::GetFieldsEnd (const TCbFieldIterator< OtherFieldType > & It) inline static protected
Returns the end of the last field, or null for an iterator at the end.
Definition at line 445 of file CompactBinary.h.
References TCbFieldIterator, and FieldsEnd.
GetRangeHash()
template<typename FieldType> FIoHash TCbFieldIterator< FieldType >::GetRangeHash () const
Calculate the hash of every field in the range.
GetRangeSize()
template<typename FieldType> uint64 TCbFieldIterator< FieldType >::GetRangeSize () const
Returns the size of the fields in the range in bytes.
IterateRangeAttachments()
template<typename FieldType> void TCbFieldIterator< FieldType >::IterateRangeAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field range.
Referenced by FCbArrayView::IterateAttachments(), and FCbObjectView::IterateAttachments().
operator!=() [1/2]
template<typename FieldType> bool TCbFieldIterator< FieldType >::operator!= (const FCbIteratorSentinel &) const inline constexpr
Definition at line 391 of file CompactBinary.h.
operator!=() [2/2]
template<typename FieldType> template<typename OtherFieldType> bool TCbFieldIterator< FieldType >::operator!= (const TCbFieldIterator< OtherFieldType > & Other) const inline constexpr
Definition at line 385 of file CompactBinary.h.
References TCbFieldIterator, Equals(), and Other.
operator*()
template<typename FieldType> FieldType & TCbFieldIterator< FieldType >::operator* () inline constexpr
Definition at line 356 of file CompactBinary.h.
operator++() [1/2]
template<typename FieldType> TCbFieldIterator & TCbFieldIterator< FieldType >::operator++ ()
References TCbFieldIterator.
operator++() [2/2]
template<typename FieldType> TCbFieldIterator TCbFieldIterator< FieldType >::operator++ (int) inline
Definition at line 349 of file CompactBinary.h.
References TCbFieldIterator.
operator->()
template<typename FieldType> FieldType * TCbFieldIterator< FieldType >::operator-> () inline constexpr
Definition at line 357 of file CompactBinary.h.
operator==() [1/2]
template<typename FieldType> bool TCbFieldIterator< FieldType >::operator== (const FCbIteratorSentinel &) const inline constexpr
Definition at line 390 of file CompactBinary.h.
operator==() [2/2]
template<typename FieldType> template<typename OtherFieldType> bool TCbFieldIterator< FieldType >::operator== (const TCbFieldIterator< OtherFieldType > & Other) const inline constexpr
Definition at line 379 of file CompactBinary.h.
References TCbFieldIterator, Equals(), and Other.
Reset()
template<typename FieldType> void TCbFieldIterator< FieldType >::Reset () inline
Reset this to an empty field range.
Definition at line 360 of file CompactBinary.h.
References TCbFieldIterator.
TryGetRangeView()
template<typename FieldType> bool TCbFieldIterator< FieldType >::TryGetRangeView (FMemoryView & OutView) const inline
Try to get a view of every field in the range as they would be serialized.
A view is available if each field contains its type. Access the equivalent for other field ranges through FCbFieldIterator::CloneRange or CopyRangeTo.
Definition at line 408 of file CompactBinary.h.
References FieldsEnd, TMemoryView< DataType >::GetData(), and MakeMemoryView().
Friends And Related Symbol Documentation
TCbFieldIterator
template<typename FieldType> template<typename OtherType> friend class TCbFieldIterator friend
Definition at line 452 of file CompactBinary.h.
References TCbFieldIterator.
Referenced by TCbFieldIterator, begin(), Equals(), GetFieldsEnd(), FCbFieldIterator::MakeOwned(), operator!=(), operator++(), operator++(), operator==(), and Reset().
Field Documentation
FieldsEnd
template<typename FieldType> const void* TCbFieldIterator< FieldType >::FieldsEnd = nullptr private
Pointer to the first byte past the end of the last field.
Set to null at the end.
Definition at line 455 of file CompactBinary.h.
Referenced by TCbFieldIterator(), TCbFieldIterator(), Equals(), GetFieldsEnd(), and TryGetRangeView().
The documentation for this class was generated from the following file:
CompactBinary.h