Unreal Engine 5.6 C++ API: TDefaultDelete< T > Struct Template Reference
TDefaultDelete< T > Struct Template Reference
#include "UniquePtr.h"
Inherited by TUniquePtr< USenderType > [private], TUniquePtr< UReceiverType > [private], TUniquePtr< IOperatorBuildError > [private], TUniquePtr< Audio::IProxyData > [private], TUniquePtr< IOperator > [private], TUniquePtr< const FAllocations > [private], TUniquePtr< UE::FScopedCompoundTransaction > [private], TUniquePtr< IAnimationDataController::FScopedBracket > [private], TUniquePtr< FArchive > [private], TUniquePtr< ActDescIteratorType > [private], TUniquePtr< FWorldGridPreviewer > [private], TUniquePtr< FBlockCorrelator > [private], TUniquePtr< Audio::FPeakPicker > [private], TUniquePtr< IFFTAlgorithm > [private], TUniquePtr< FContiguousSparse2DKernelTransform > [private], TUniquePtr< Audio::FConstantQAnalyzer > [private], TUniquePtr< IConvolutionAlgorithm > [private], TUniquePtr< IChannelFormatConverter > [private], TUniquePtr< FAlignedBlockBuffer > [private], TUniquePtr< Audio::FConvolutionReverb > [private], TUniquePtr< Audio::FMultichannelLoudnessAnalyzer > [private], TUniquePtr< Audio::IPitchDetector > [private], TUniquePtr< Audio::FMeterAnalyzer > [private], TUniquePtr< Audio::FSynesthesiaSpectrumAnalyzer > [private], TUniquePtr< FAsyncCompilationNotification > [private], TUniquePtr< IFileHandle > [private], TUniquePtr< FNetworkPhysicsData > [private], TUniquePtr< Chaos::FBaseRewindHistory > [private], TUniquePtr< FMeshAttributeArraySetBase > [private], TUniquePtr< UE::Tasks::FTaskEvent > [private], TUniquePtr< FEditorViewportSelectabilityBridge > [private], TUniquePtr< FBlueprintDebugger > [private], TUniquePtr< FBlueprintNamespacePathTree > [private], TUniquePtr< TCHAR[]> [private], TUniquePtr< FQueuedThreadPool > [private], TUniquePtr< FUpdatedComponentAsyncInput > [private], TUniquePtr< FCharacterAsyncInput > [private], TUniquePtr< FCharacterAsyncOutput > [private], TUniquePtr< ICompressedAnimData > [private], TUniquePtr< FCultureImplementation > [private], TUniquePtr< ICurveEditorBounds > [private], TUniquePtr< UE::CurveEditor::FTransactionManager > [private], TUniquePtr< ICurveEditorDragOperation > [private], TUniquePtr< IClickDragBehaviorTarget > [private], TUniquePtr< FAudioCookInputs > [private], TUniquePtr< class FDisplayClusterFillDerivedDataCacheWorker > [private], TUniquePtr< FAsyncTaskNotification > [private], TUniquePtr< FRunnableThread > [private], TUniquePtr< FDynamicMeshGroupEdit > [private], TUniquePtr< UE::Geometry::FDynamicMesh3 > [private], TUniquePtr< UE::Geometry::FDynamicMeshChange > [private], TUniquePtr< FMeshDescription > [private], TUniquePtr< class FCacheAllBlueprintsTickableObject > [private], TUniquePtr< FGPUSkinDataType > [private], TUniquePtr< FStaticMeshInstanceData > [private], TUniquePtr< FStaticMeshInstanceBuffer > [private], TUniquePtr< FImplementation > [private], TUniquePtr< IMappedFileHandle > [private], TUniquePtr< FLandscapeComponentSceneProxy::FLandscapeLCI > [private], TUniquePtr< IBulkDataIORequest > [private], TUniquePtr< UE::FPackageTrailer > [private], TUniquePtr< int32[]> [private], TUniquePtr< UE::FPackageTrailerBuilder > [private], TUniquePtr< FLiveLinkLog > [private], TUniquePtr< FLoadPackageAsyncDelegate > [private], TUniquePtr< FLoadPackageAsyncProgressDelegate > [private], TUniquePtr< FCriticalSection > [private], TUniquePtr< class FGlobalComponentReregisterContext > [private], TUniquePtr< class FGlobalComponentRecreateRenderStateContext > [private], TUniquePtr< FMediaIOCoreSamples > [private], TUniquePtr< FMediaIOCorePlayerBase::FJITRMediaTextureSamples > [private], TUniquePtr< FMeshElementChannels > [private], TUniquePtr< FMeshSelectionChange > [private], TUniquePtr< FTopologyProvider > [private], TUniquePtr< FMeshVertexChange > [private], TUniquePtr< Chaos::FSimModuleTree > [private], TUniquePtr< IModuleInterface > [private], TUniquePtr< FNetResult > [private], TUniquePtr< FObjectInitializer::FOverrides > [private], TUniquePtr< FRepState > [private], TUniquePtr< IAsyncReadFileHandle > [private], TUniquePtr< FCategoryInclusionInternal > [private], TUniquePtr< FPackedLevelActorBuilderCluster > [private], TUniquePtr< FPhysicsReplicationCache > [private], TUniquePtr< IPhysicsReplication > [private], TUniquePtr< IPhysicsReplicationLOD > [private], TUniquePtr< FPhysScene_AsyncPhysicsStateJobQueue > [private], TUniquePtr< rtc::Thread > [private], TUniquePtr< FReferenceCollectorArchive > [private], TUniquePtr< struct FCustomDeltaChangelistState > [private], TUniquePtr< struct FLifetimeCustomDeltaState > [private], TUniquePtr< FNetBitWriter > [private], TUniquePtr< FReceivingRepState > [private], TUniquePtr< FSendingRepState > [private], TUniquePtr< FScopedSlowTask > [private], TUniquePtr< FRotationConversionCache::FPayload > [private], TUniquePtr< FScopedTransaction > [private], TUniquePtr< ISavePackageValidator > [private], TUniquePtr< FNetSimCueWrapperBase > [private], TUniquePtr< FMemoryReaderView > [private], TUniquePtr< FMemoryWriter64 > [private], TUniquePtr< FShaderPreprocessOutput > [private], TUniquePtr< FShaderCompilerOutput > [private], TUniquePtr< FSkeletalMeshUpdateChannel::FOpQueue > [private], TUniquePtr< FRHIGPUBufferReadback > [private], TUniquePtr< class FSkinnedMeshComponentRecreateRenderStateContext > [private], TUniquePtr< FFinishBuildMorphTargetData > [private], TUniquePtr< IPlatformTextField > [private], TUniquePtr< SlateAttributePrivate::ISlateAttributeGetter > [private], TUniquePtr< FSlateTextBlockLayout > [private], TUniquePtr< FFreeTypeLibrary > [private], TUniquePtr< FFreeTypeCacheDirectory > [private], TUniquePtr< FCompositeFontCache > [private], TUniquePtr< FSlateFontRenderer > [private], TUniquePtr< FSlateTextShaper > [private], TUniquePtr< FSlateSdfGenerator > [private], TUniquePtr< FSlateInvalidationWidgetList > [private], TUniquePtr< FSlateInvalidationWidgetPreHeap > [private], TUniquePtr< FSlateInvalidationWidgetPrepassHeap > [private], TUniquePtr< FSlateInvalidationWidgetPostHeap > [private], TUniquePtr< class ICompressedAudioInfo > [private], TUniquePtr< FQuantizedLightmapData > [private], TUniquePtr< FStaticMeshPostLoadContext > [private], TUniquePtr< FStaticMeshBuildContext > [private], TUniquePtr< UE::StreamableManager::Private::FDownloadContext > [private], TUniquePtr< FStreamedAudioChunkSeekTable::ISeekTableImpl > [private], TUniquePtr< struct FStyleFonts > [private], TUniquePtr< FMovieSceneSequenceTransform > [private], TUniquePtr< FMovieSceneTimeWarpChannel > [private], TUniquePtr< TextBiDi::ITextBiDi > [private], TUniquePtr< FTimerSourceList > [private], TUniquePtr< FToolCommandChange > [private], TUniquePtr< FChange > [private], TUniquePtr< UE::Transaction::FDiffableObject > [private], TUniquePtr< FTransformProxyChange > [private], TUniquePtr< FPerformanceAnalyticsStats > [private], TUniquePtr< FConsoleCommandExecutor > [private], TUniquePtr< FEditorAxisDisplayInfo > [private], TUniquePtr< struct FVectorFieldTextureAccessorImpl > [private], TUniquePtr< FVolumetricLightmapGridStreamingManager > [private], TUniquePtr< Audio::FQuartzQuantizedRequestData > [private], TUniquePtr< Audio::IFFTAlgorithm > [private], TUniquePtr< Audio::FWindow > [private], TUniquePtr< Chaos::FGeometryCollectionCacheAdapter > [private], TUniquePtr< Chaos::FStaticMeshCacheAdapter > [private], TUniquePtr< FMovieSceneSequenceEditor > [private], TUniquePtr< IStereoLayerShape > [private], TUniquePtr< Chaos::FChaosPhysicsMaterial > [private], TUniquePtr< LowLevelTasks::Private::TLocalQueueRegistry::TLocalQueue > [private], TUniquePtr< Metasound::FTransmissionAddress > [private], TUniquePtr< Metasound::IDataReference > [private], TUniquePtr< Metasound::FFrontendQueryStep > [private], TUniquePtr< Metasound::FFrontendQueryStep::IStepExecuter > [private], TUniquePtr< Metasound::IOperator > [private], TUniquePtr< Metasound::IReceiver > [private], TUniquePtr< Metasound::ISender > [private], TUniquePtr< Metasound::FArrayRandomGet > [private], TUniquePtr< Metasound::FArrayIndexShuffler > [private], TUniquePtr< TDataType > [private], TUniquePtr< UE::CurveEditor::FPromotedFilterCommandBinder > [private], TUniquePtr< FCurveEditorEditObjectContainer > [private], TUniquePtr< FZoomLevelsContainer > [private], TUniquePtr< FSlateEditableTextLayout > [private], TUniquePtr< FHittestGrid > [private], TUniquePtr< FProgressCancel > [private], TUniquePtr< FString[]> [private], TUniquePtr< TDirectoryTree::FTreeNode[]> [private], TUniquePtr< FDisplayClusterTickableGameObject > [private], TUniquePtr< ResultDataType > [private], TUniquePtr< ChangeClassType > [private], TUniquePtr< SlotType > [private], TUniquePtr< FWorldPartitionActorDescInstance > [private], TUniquePtr< ChangeType > [private], TUniquePtr< IAnimationDataModel::FModelNotifier > [private], TUniquePtr< Chaos::FSimpleWheeledVehicle > [private], TUniquePtr< FMeshRenderDecomposition > [private], TUniquePtr< IRenderMeshPostProcessor > [private], TUniquePtr< FCompressionMemorySummary > [private], TUniquePtr< FRigInstance > [private], TUniquePtr< const Private::FOutfitCollection > [private], TUniquePtr< UE::ConfigAccessTracking::FConfigAccessData > [private], TUniquePtr< FARFilter > [private], TUniquePtr< FCompoundChangeInput > [private], TUniquePtr< uint8[]> [private], TUniquePtr< UE::FPropertyPathNameTree > [private], TUniquePtr< UE::Geometry::FDynamicMeshAttributeSet > [private], TUniquePtr< UE::Geometry::FDynamicMeshAttributeChangeSet > [private], TUniquePtr< UE::Geometry::FMeshPlaneCut > [private], TUniquePtr< UE::Geometry::FDynamicMeshChangeTracker > [private], TUniquePtr< UE::Geometry::FImageOccupancyMap > [private], TUniquePtr< UE::Geometry::IMeshSpatialWrapper > [private], TUniquePtr< UE::Geometry::FMeshRegionOperator > [private], TUniquePtr< UE::Geometry::FMeshNormals > [private], TUniquePtr< ResultType > [private], TUniquePtr< OpType > [private], TUniquePtr< UE::MovieScene::IComplexComponentOps > [private], TUniquePtr< UE::MovieScene::IMutualComponentInitializer > [private], TUniquePtr< UE::MovieScene::FPreAnimatedEntityCaptureSource > [private], TUniquePtr< UE::MovieScene::FPreAnimatedTrackInstanceCaptureSources > [private], TUniquePtr< UE::MovieScene::FPreAnimatedTrackInstanceInputCaptureSources > [private], TUniquePtr< UE::MovieScene::FPreAnimatedTemplateCaptureSources > [private], TUniquePtr< UE::MovieScene::FPreAnimatedEvaluationHookCaptureSources > [private], TUniquePtr< UE::MovieScene::FCompiledDataVolatilityManager > [private], TUniquePtr< UE::MovieScene::FSequenceDirectorPlaybackCapability::FDirectorInstanceCache > [private], TUniquePtr< FMovieSceneTrackEvaluator > [private], TUniquePtr< FMovieSceneLegacyPlayer > [private], TUniquePtr< UE::MovieScene::ISequenceUpdater > [private], TUniquePtr< FSystemInterrogatorEntityTracker > [private], TUniquePtr< UE::PixelStreaming2::FRTCStatsCollector::FCandidatePairStatsSink > [private], TUniquePtr< UE::Sequencer::FViewModelHierarchyOperation > [private], TUniquePtr< UE::Sequencer::FSelectionEventSuppressor > [private], TUniquePtr< FImpl > [private], TUniquePtr< UHierarchicalInstancedStaticMeshComponent::FClusterTree > [private], TUniquePtr< UPackage::FAdditionalInfo > [private], TUniquePtr< FWorldTileInfo > [private], TUniquePtr< FInstanceOwner > [private], and TUniquePtr< T, Deleter > [private].
Public Member Functions
TDefaultDelete ()=default
TDefaultDelete (const TDefaultDelete &)=default
template<typename U UE_REQUIRES>
TDefaultDelete (const TDefaultDelete< U > &)
~TDefaultDelete ()=default
DECLARE_INLINE_TYPE_LAYOUT (TDefaultDelete, NonVirtual)
void operator() (T *Ptr) const
TDefaultDelete & operator= (const TDefaultDelete &)=default
template<typename U UE_REQUIRES>
TDefaultDelete & operator= (const TDefaultDelete< U > &)
Detailed Description
template<typename T>
struct TDefaultDelete< T >
Definition at line 27 of file UniquePtr.h.
Constructor & Destructor Documentation
TDefaultDelete() [1/3]
template<typename T> TDefaultDelete< T >::TDefaultDelete () default
Referenced by TDefaultDelete(), TDefaultDelete(), DECLARE_INLINE_TYPE_LAYOUT(), operator=(), and operator=().
TDefaultDelete() [2/3]
template<typename T> TDefaultDelete< T >::TDefaultDelete (const TDefaultDelete< T > &) default
References TDefaultDelete().
~TDefaultDelete()
template<typename T> TDefaultDelete< T >::~TDefaultDelete () default
TDefaultDelete() [3/3]
template<typename T> template<typename U UE_REQUIRES> TDefaultDelete< T >::TDefaultDelete (const TDefaultDelete< U > &) inline
Definition at line 40 of file UniquePtr.h.
References TDefaultDelete().
Member Function Documentation
DECLARE_INLINE_TYPE_LAYOUT()
template<typename T> TDefaultDelete< T >::DECLARE_INLINE_TYPE_LAYOUT (TDefaultDelete< T > , NonVirtual)
References TDefaultDelete().
operator()()
template<typename T> void TDefaultDelete< T >::operator() (T * Ptr) const inline
Definition at line 53 of file UniquePtr.h.
operator=() [1/2]
template<typename T> TDefaultDelete & TDefaultDelete< T >::operator= (const TDefaultDelete< T > &) default
References TDefaultDelete().
operator=() [2/2]
template<typename T> template<typename U UE_REQUIRES> TDefaultDelete & TDefaultDelete< T >::operator= (const TDefaultDelete< U > &) inline
Definition at line 48 of file UniquePtr.h.
References TDefaultDelete().
The documentation for this struct was generated from the following file:
UniquePtr.h