Unreal Engine 5.6 C++ API: UE::Core::Private::Function::FFunctionStorage Struct Reference
UE::Core::Private::Function::FFunctionStorage Struct Reference
#include "Function.h"
Public Member Functions
FFunctionStorage ()
FFunctionStorage (const FFunctionStorage &Other)=delete
FFunctionStorage (FFunctionStorage &&Other)
void * BindCopy (const FFunctionStorage &Other)
IFunction_OwnedObject * GetBoundObject () const
void * GetPtr () const
Returns a pointer to the callable object - needed by TFunctionRefBase.
FFunctionStorage & operator= (const FFunctionStorage &Other)=delete
FFunctionStorage & operator= (FFunctionStorage &&Other)=delete
void Unbind ()
Destroy any owned bindings - called by TFunctionRefBase only if Bind() or BindCopy() was called.
Data Fields
void * HeapAllocation
Static Public Attributes
static constexpr bool bCanBeNull = true
Detailed Description
Definition at line 130 of file Function.h.
Constructor & Destructor Documentation
FFunctionStorage() [1/3]
UE::Core::Private::Function::FFunctionStorage::FFunctionStorage () inline
Definition at line 134 of file Function.h.
References HeapAllocation.
Referenced by FFunctionStorage(), FFunctionStorage(), UE::Core::Private::Function::TFunctionStorage< bUnique >::TFunctionStorage(), BindCopy(), operator=(), and operator=().
FFunctionStorage() [2/3]
UE::Core::Private::Function::FFunctionStorage::FFunctionStorage (FFunctionStorage && Other) inline
Definition at line 139 of file Function.h.
References FFunctionStorage(), HeapAllocation, FMemory::Memcpy(), and Other.
FFunctionStorage() [3/3]
UE::Core::Private::Function::FFunctionStorage::FFunctionStorage (const FFunctionStorage & Other) delete
References FFunctionStorage(), and Other.
Member Function Documentation
BindCopy()
void * UE::Core::Private::Function::FFunctionStorage::BindCopy (const FFunctionStorage & Other) inline
Definition at line 152 of file Function.h.
References FFunctionStorage(), and Other.
GetBoundObject()
IFunction_OwnedObject * UE::Core::Private::Function::FFunctionStorage::GetBoundObject () const inline
Definition at line 158 of file Function.h.
References HeapAllocation.
Referenced by Unbind().
GetPtr()
void * UE::Core::Private::Function::FFunctionStorage::GetPtr () const inline
Returns a pointer to the callable object - needed by TFunctionRefBase.
Definition at line 174 of file Function.h.
References UE::Core::Private::Function::IFunction_OwnedObject::GetAddress(), and HeapAllocation.
operator=() [1/2]
FFunctionStorage & UE::Core::Private::Function::FFunctionStorage::operator= (const FFunctionStorage & Other) delete
References FFunctionStorage(), and Other.
operator=() [2/2]
FFunctionStorage & UE::Core::Private::Function::FFunctionStorage::operator= (FFunctionStorage && Other) delete
References FFunctionStorage(), and Other.
Unbind()
void UE::Core::Private::Function::FFunctionStorage::Unbind () inline
Destroy any owned bindings - called by TFunctionRefBase only if Bind() or BindCopy() was called.
Definition at line 192 of file Function.h.
References UE::Core::Private::Function::IFunction_OwnedObject::Destroy(), and GetBoundObject().
Field Documentation
bCanBeNull
bool UE::Core::Private::Function::FFunctionStorage::bCanBeNull = true static constexpr
Definition at line 132 of file Function.h.
HeapAllocation
void* UE::Core::Private::Function::FFunctionStorage::HeapAllocation
Definition at line 203 of file Function.h.
Referenced by FFunctionStorage(), FFunctionStorage(), UE::Core::Private::Function::TFunctionStorage< bUnique >::Bind(), UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::CloneToEmptyStorage(), GetBoundObject(), and GetPtr().
The documentation for this struct was generated from the following file:
Function.h