Unreal Engine 5.6 C++ API: UE::GC::FSlowARO Struct Reference
UE::GC::FSlowARO Struct Reference
#include "FastReferenceCollector.h"
Static Public Member Functions
static void CallSync (uint32 SlowAROIndex, UObject *Object, FReferenceCollector &Collector)
static bool ProcessAllCalls (FWorkerContext &Context, FReferenceCollector &Collector)
static void ProcessUnbalancedCalls (FWorkerContext &Context, FReferenceCollector &Collector)
static bool TryQueueCall (uint32 SlowAROIndex, UObject *Object, FWorkerContext &Context)
Detailed Description
Definition at line 233 of file FastReferenceCollector.h.
Member Function Documentation
CallSync()
void UE::GC::FSlowARO::CallSync (uint32 SlowAROIndex, UObject * Object, FReferenceCollector & Collector) static
References UE::GC::Collector.
Referenced by UE::GC::Private::CallSlowARO().
ProcessAllCalls()
bool UE::GC::FSlowARO::ProcessAllCalls (FWorkerContext & Context, FReferenceCollector & Collector) static
References UE::GC::Collector, and UE::GC::Context.
ProcessUnbalancedCalls()
void UE::GC::FSlowARO::ProcessUnbalancedCalls (FWorkerContext & Context, FReferenceCollector & Collector) static
References UE::GC::Collector, and UE::GC::Context.
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray().
TryQueueCall()
bool UE::GC::FSlowARO::TryQueueCall (uint32 SlowAROIndex, UObject * Object, FWorkerContext & Context) static
References UE::GC::Context.
Referenced by UE::GC::Private::CallSlowARO().
The documentation for this struct was generated from the following file:
FastReferenceCollector.h