Unreal Engine 5.6 C++ API: IDetailLayoutBuilder Class Reference
IDetailLayoutBuilder Class Reference abstract
The builder for laying custom details.
#include "DetailLayoutBuilder.h"
Public Types
using FOnCategorySortOrderFunction = TFunction<void(const TMap<FName, IDetailCategoryBuilder*>&)>
Public Member Functions
virtual ~IDetailLayoutBuilder ()
virtual FDetailWidgetRow & AddCustomRowToCategory (TSharedPtr< IPropertyHandle > InPropertyHandle, const FText &InCustomSearchString, bool bForAdvanced=false)=0
Adds a custom row to the property's category automatically.
virtual TSharedPtr< IPropertyHandle > AddObjectPropertyData (TConstArrayView< UObject * > Objects, FName PropertyName)=0
Adds an external object's property to this details panel's PropertyMap.
virtual IDetailPropertyRow & AddPropertyToCategory (TSharedPtr< IPropertyHandle > InPropertyHandle)=0
Adds the property to its given category automatically.
virtual TSharedPtr< IPropertyHandle > AddStructurePropertyData (const TSharedPtr< FStructOnScope > &StructData, FName PropertyName)=0
Adds an external structure's property data to this details panel's PropertyMap.
virtual void DisableInstancedReference (TSharedRef< IPropertyHandle > PropertyHandle) const =0
Force a property to behave as a normal, peer reference regardless of CPF_InstancedReference.
virtual bool DoesCategoryHaveGeneratedChildren (FName CategoryName)=0
virtual IDetailCategoryBuilder & EditCategory (FName CategoryName, const FText &NewLocalizedDisplayName=FText::GetEmpty(), ECategoryPriority::Type CategoryType=ECategoryPriority::Default)=0
Edits an existing category or creates a new one.
virtual IDetailCategoryBuilder & EditCategoryAllowNone (FName CategoryName, const FText &NewLocalizedDisplayName=FText::GetEmpty(), ECategoryPriority::Type CategoryType=ECategoryPriority::Default)=0
Edits an existing category or creates a new one If CategoryName is NAME_None, will enable access to properties without categories.
virtual IDetailPropertyRow * EditDefaultProperty (TSharedPtr< IPropertyHandle > InPropertyHandle)=0
Allows for the customization of a property row for a property that already exists on a class being edited in the details panel The property will remain in the default location but the widget or other attributes for the property can be changed Note This cannot be used to customize other customizations.
virtual IDetailPropertyRow * EditPropertyFromRoot (TSharedPtr< IPropertyHandle > InPropertyHandle)=0
Get the property row from the root of the details panel after it's been constructed, so this will work with default or custom properties.
virtual void ForceRefreshDetails ()=0
Refreshes the details view and regenerates all the customized layouts Use only when you need to remove or add complicated dynamic items.
virtual UClass * GetBaseClass () const =0
virtual void GetCategoryNames (TArray< FName > &OutCategoryNames) const =0
Gets the current set of existing category names.
virtual TSharedPtr< const IDetailsView > GetDetailsViewSharedPtr () const =0
virtual TSharedPtr< IDetailsView > GetDetailsViewSharedPtr ()=0
virtual void GetObjectsBeingCustomized (TArray< TWeakObjectPtr< UObject > > &OutObjects) const =0
Gets the current object(s) being customized by this builder.
template<typename ObjectType = UObject>
TArray< TWeakObjectPtr< ObjectType > > GetObjectsOfTypeBeingCustomized () const
Gets the current object(s) being customized by this builder of ObjectType.
virtual TSharedRef< IPropertyHandle > GetProperty (const FName PropertyPath, const UStruct *ClassOutermost=NULL, FName InstanceName=NAME_None) const =0
Gets a handle to a property which can be used to read and write the property value and identify the property in other detail customization interfaces.
virtual TSharedRef< IPropertyUtilities > GetPropertyUtilities () const =0
virtual const TArray< TWeakObjectPtr< UObject > > & GetSelectedObjects () const =0
Get the root objects observed by this layout.
template<typename ObjectType = UObject>
TArray< TWeakObjectPtr< ObjectType > > GetSelectedObjectsOfType () const
Get the root objects (of ObjectType) observed by this layout.
virtual void GetStructsBeingCustomized (TArray< TSharedPtr< FStructOnScope > > &OutStructs) const =0
Gets the current struct(s) being customized by this builder.
virtual TSharedPtr< class FAssetThumbnailPool > GetThumbnailPool () const =0
Gets the thumbnail pool that should be used for rendering thumbnails in the details view.
virtual FName GetTopLevelProperty ()=0
Gets the top level property, for showing the warning for experimental or early access class.
virtual bool HasClassDefaultObject () const =0
virtual void HideCategory (FName CategoryName)=0
Hides an entire category.
virtual void HideProperty (const TSharedPtr< IPropertyHandle > PropertyHandle)=0
Hides a property from view.
virtual void HideProperty (FName PropertyPath, const UStruct *ClassOutermost=NULL, FName InstanceName=NAME_None)=0
Hides a property from view.
virtual bool IsPropertyPathAllowed (const FString &InPath) const =0
virtual bool IsPropertyVisible (const struct FPropertyAndParent &PropertyAndParent) const =0
virtual bool IsPropertyVisible (TSharedRef< IPropertyHandle > PropertyHandle) const =0
virtual void RegisterInstancedCustomPropertyTypeLayout (FName PropertyTypeName, FOnGetPropertyTypeCustomizationInstance PropertyTypeLayoutDelegate, TSharedPtr< IPropertyTypeIdentifier > Identifier=nullptr)=0
Registers a custom detail layout delegate for a specific type in this layout only.
virtual void SetPropertyGenerationAllowListPaths (const TSet< FString > &InPropertyGenerationAllowListPaths)=0
This function sets property paths to generate PropertyNodes.This improves the performance for cases where PropertyView is only showing a few properties of the object by not generating all other PropertyNodes.
virtual void SortCategories (const FOnCategorySortOrderFunction &SortFunction)=0
Adds sort algorythm which overrides standard algorythm with that provided by the caller.
UE_DEPRECATED (5.5, "Use GetDetailsViewSharedPtr() instead.") const IDetailsView *GetDetailsView() const
UE_DEPRECATED (5.5, "Use GetDetailsViewSharedPtr() instead.") IDetailsView *GetDetailsView()
Static Public Member Functions
static FSlateFontInfo GetDetailFont ()
static FSlateFontInfo GetDetailFontBold ()
static FSlateFontInfo GetDetailFontItalic ()
Detailed Description
The builder for laying custom details.
Definition at line 35 of file DetailLayoutBuilder.h.
Member Typedef Documentation
FOnCategorySortOrderFunction
using IDetailLayoutBuilder::FOnCategorySortOrderFunction = TFunction<void(const TMap<FName, IDetailCategoryBuilder*>&)>
Definition at line 39 of file DetailLayoutBuilder.h.
Constructor & Destructor Documentation
~IDetailLayoutBuilder()
virtual IDetailLayoutBuilder::~IDetailLayoutBuilder () inline virtual
Definition at line 41 of file DetailLayoutBuilder.h.
Member Function Documentation
AddCustomRowToCategory()
virtual FDetailWidgetRow & IDetailLayoutBuilder::AddCustomRowToCategory (TSharedPtr< IPropertyHandle > InPropertyHandle, const FText & InCustomSearchString, bool bForAdvanced = false) pure virtual
Adds a custom row to the property's category automatically.
Useful in detail customizations which want to preserve categories.
Parameters
InPropertyHandle The handle to the property that you want to add to its own category.
InCustomSearchString A string which is used to filter this custom row when a user types into the details panel search box.
Returns
the detail widget that can be further customized.
AddObjectPropertyData()
virtual TSharedPtr< IPropertyHandle > IDetailLayoutBuilder::AddObjectPropertyData (TConstArrayView< UObject * > Objects, FName PropertyName) pure virtual
Adds an external object's property to this details panel's PropertyMap.
Allows getting the property handle for the property without having to generate a row widget.
Parameters
Objects List of objects that contain the property.
PropertyName Name of the property to generate a node from.
Returns
The property handle created tied to generated property node.
References PropertyName.
AddPropertyToCategory()
virtual IDetailPropertyRow & IDetailLayoutBuilder::AddPropertyToCategory (TSharedPtr< IPropertyHandle > InPropertyHandle) pure virtual
Adds the property to its given category automatically.
Useful in detail customizations which want to preserve categories.
Parameters
InPropertyHandle The handle to the property that you want to add to its own category.
Returns
the property row with which the property was added.
AddStructurePropertyData()
virtual TSharedPtr< IPropertyHandle > IDetailLayoutBuilder::AddStructurePropertyData (const TSharedPtr< FStructOnScope > & StructData, FName PropertyName) pure virtual
Adds an external structure's property data to this details panel's PropertyMap.
Allows getting the property handle for the property without having to generate a row widget.
Parameters
StructData Struct data to find the property within.
PropertyName Name of the property to generate a node from.
Returns
The property handle tied to the generated property node.
References PropertyName.
DisableInstancedReference()
virtual void IDetailLayoutBuilder::DisableInstancedReference (TSharedRef< IPropertyHandle > PropertyHandle) const pure virtual
Force a property to behave as a normal, peer reference regardless of CPF_InstancedReference.
DoesCategoryHaveGeneratedChildren()
virtual bool IDetailLayoutBuilder::DoesCategoryHaveGeneratedChildren (FName CategoryName) pure virtual
Returns
true if the category contains child rows.
EditCategory()
virtual IDetailCategoryBuilder & IDetailLayoutBuilder::EditCategory (FName CategoryName, const FText & NewLocalizedDisplayName = FText::GetEmpty(), ECategoryPriority::Type CategoryType = ECategoryPriority::Default) pure virtual
Edits an existing category or creates a new one.
Parameters
CategoryName The name of the category
NewLocalizedDisplayName The new display name of the category (optional)
CategoryType Category type to define sort order. Category display order is sorted by this type (optional)
References ECategoryPriority::Default, and FText::GetEmpty().
EditCategoryAllowNone()
virtual IDetailCategoryBuilder & IDetailLayoutBuilder::EditCategoryAllowNone (FName CategoryName, const FText & NewLocalizedDisplayName = FText::GetEmpty(), ECategoryPriority::Type CategoryType = ECategoryPriority::Default) pure virtual
Edits an existing category or creates a new one If CategoryName is NAME_None, will enable access to properties without categories.
Parameters
CategoryName The name of the category
NewLocalizedDisplayName The new display name of the category (optional)
CategoryType Category type to define sort order. Category display order is sorted by this type (optional)
References ECategoryPriority::Default, and FText::GetEmpty().
EditDefaultProperty()
virtual IDetailPropertyRow * IDetailLayoutBuilder::EditDefaultProperty (TSharedPtr< IPropertyHandle > InPropertyHandle) pure virtual
Allows for the customization of a property row for a property that already exists on a class being edited in the details panel The property will remain in the default location but the widget or other attributes for the property can be changed Note This cannot be used to customize other customizations.
Parameters
InPropertyHandle The handle to the property that you want to edit
Returns
The property row to edit or nullptr if the property row does not exist
EditPropertyFromRoot()
virtual IDetailPropertyRow * IDetailLayoutBuilder::EditPropertyFromRoot (TSharedPtr< IPropertyHandle > InPropertyHandle) pure virtual
Get the property row from the root of the details panel after it's been constructed, so this will work with default or custom properties.
Parameters
InPropertyHandle The handle to the property that you want to edit
Returns
The property row to edit or nullptr if the property row does not exist, which may happen if not constructed yet
ForceRefreshDetails()
virtual void IDetailLayoutBuilder::ForceRefreshDetails () pure virtual
Refreshes the details view and regenerates all the customized layouts Use only when you need to remove or add complicated dynamic items.
GetBaseClass()
virtual UClass * IDetailLayoutBuilder::GetBaseClass () const pure virtual
Returns
The base class of the objects being customized in this detail layout
GetCategoryNames()
virtual void IDetailLayoutBuilder::GetCategoryNames (TArray< FName > & OutCategoryNames) const pure virtual
Gets the current set of existing category names.
This includes both categories derived from properties and categories added via EditCategory.
Parameters
OutCategoryNames The array of category names
GetDetailFont()
FSlateFontInfo IDetailLayoutBuilder::GetDetailFont () inline static
Returns
the font used for properties and details
Definition at line 46 of file DetailLayoutBuilder.h.
References FAppStyle::GetFontStyle(), and TEXT.
Referenced by FGameModeInfoCustomizer::CreateGameModePropertyLabelWidget().
GetDetailFontBold()
FSlateFontInfo IDetailLayoutBuilder::GetDetailFontBold () inline static
Returns
the bold font used for properties and details
Definition at line 51 of file DetailLayoutBuilder.h.
References FAppStyle::GetFontStyle(), and TEXT.
GetDetailFontItalic()
FSlateFontInfo IDetailLayoutBuilder::GetDetailFontItalic () inline static
Returns
the italic font used for properties and details
Definition at line 56 of file DetailLayoutBuilder.h.
References FAppStyle::GetFontStyle(), and TEXT.
GetDetailsViewSharedPtr() [1/2]
virtual TSharedPtr< const IDetailsView > IDetailLayoutBuilder::GetDetailsViewSharedPtr () const pure virtual
Returns
the parent detail view for this layout builder
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
GetDetailsViewSharedPtr() [2/2]
virtual TSharedPtr< IDetailsView > IDetailLayoutBuilder::GetDetailsViewSharedPtr () pure virtual
Returns
the parent detail view for this layout builder
GetObjectsBeingCustomized()
virtual void IDetailLayoutBuilder::GetObjectsBeingCustomized (TArray< TWeakObjectPtr< UObject > > & OutObjects) const pure virtual
Gets the current object(s) being customized by this builder.
If this is a sub-object customization it will return those sub objects. Otherwise the root objects will be returned.
Referenced by GetObjectsOfTypeBeingCustomized().
GetObjectsOfTypeBeingCustomized()
template<typename ObjectType> TArray< TWeakObjectPtr< ObjectType > > IDetailLayoutBuilder::GetObjectsOfTypeBeingCustomized () const
Gets the current object(s) being customized by this builder of ObjectType.
If this is a sub-object customization it will return those sub objects. Otherwise the root objects will be returned.
Returns
true if one or more objects of ObjectType were found.
Definition at line 352 of file DetailLayoutBuilder.h.
References Cast(), GetObjectsBeingCustomized(), TWeakObjectPtr< T, TWeakObjectPtrBase >::IsValid(), and Algo::TransformIf().
GetProperty()
virtual TSharedRef< IPropertyHandle > IDetailLayoutBuilder::GetProperty (const FName PropertyPath, const UStruct * ClassOutermost = NULL, FName InstanceName = NAME_None) const pure virtual
Gets a handle to a property which can be used to read and write the property value and identify the property in other detail customization interfaces.
Instructions
Parameters
Path The path to the property. Can be just a name of the property or a path in the format outer.outer.value[optional_index_for_static_arrays]
ClassOutermost Optional outer class if accessing a property outside of the current class being customized
InstanceName Optional instance name if multiple FProperty's of the same type exist. such as two identical structs, the instance name is one of the struct variable names) Examples:
struct MyStruct { int32 StaticArray[3]; float FloatVar; }
class MyActor { MyStruct Struct1; MyStruct Struct2; float MyFloat }
To access StaticArray at index 2 from Struct2 in MyActor, your path would be MyStruct.StaticArray[2]" and your instance name is "Struct2" To access MyFloat in MyActor you can just pass in "MyFloat" because the name of the property is unambiguous
Referenced by FGameModeInfoCustomizer::CustomizeGameModeSetting().
GetPropertyUtilities()
virtual TSharedRef< IPropertyUtilities > IDetailLayoutBuilder::GetPropertyUtilities () const pure virtual
Returns
the utilities various widgets need access to certain features of PropertyDetails
GetSelectedObjects()
virtual const TArray< TWeakObjectPtr< UObject > > & IDetailLayoutBuilder::GetSelectedObjects () const pure virtual
Get the root objects observed by this layout.
This is not guaranteed to be the same as the objects customized by this builder. See GetObjectsBeingCustomized for that.
Referenced by GetSelectedObjectsOfType().
GetSelectedObjectsOfType()
template<typename ObjectType> TArray< TWeakObjectPtr< ObjectType > > IDetailLayoutBuilder::GetSelectedObjectsOfType () const
Get the root objects (of ObjectType) observed by this layout.
This is not guaranteed to be the same as the objects customized by this builder. See GetObjectsBeingCustomized for that.
Definition at line 332 of file DetailLayoutBuilder.h.
References Cast(), GetSelectedObjects(), TWeakObjectPtr< T, TWeakObjectPtrBase >::IsValid(), and Algo::TransformIf().
GetStructsBeingCustomized()
virtual void IDetailLayoutBuilder::GetStructsBeingCustomized (TArray< TSharedPtr< FStructOnScope > > & OutStructs) const pure virtual
Gets the current struct(s) being customized by this builder.
If this is a sub-struct customization it will return those sub struct. Otherwise the root struct will be returned.
GetThumbnailPool()
virtual TSharedPtr< class FAssetThumbnailPool > IDetailLayoutBuilder::GetThumbnailPool () const pure virtual
Gets the thumbnail pool that should be used for rendering thumbnails in the details view.
GetTopLevelProperty()
virtual FName IDetailLayoutBuilder::GetTopLevelProperty () pure virtual
Gets the top level property, for showing the warning for experimental or early access class.
Returns
the top level property name
HasClassDefaultObject()
virtual bool IDetailLayoutBuilder::HasClassDefaultObject () const pure virtual
Returns
True if an object in the builder is a class default object
HideCategory()
virtual void IDetailLayoutBuilder::HideCategory (FName CategoryName) pure virtual
Hides an entire category.
Parameters
CategoryName The name of the category to hide
HideProperty() [1/2]
virtual void IDetailLayoutBuilder::HideProperty (const TSharedPtr< IPropertyHandle > PropertyHandle) pure virtual
Hides a property from view.
Parameters
PropertyHandle The handle of the property to hide from view
Referenced by FAnimGraphNodeAlphaOptions::HandleCustomizeDetails().
HideProperty() [2/2]
virtual void IDetailLayoutBuilder::HideProperty (FName PropertyPath, const UStruct * ClassOutermost = NULL, FName InstanceName = NAME_None) pure virtual
Hides a property from view.
Parameters
Path The path to the property. Can be just a name of the property or a path in the format outer.outer.value[optional_index_for_static_arrays]
NewLocalizedDisplayName Optional display name to show instead of the default name
ClassOutermost Optional outer class if accessing a property outside of the current class being customized
InstanceName Optional instance name if multiple FProperty's of the same type exist. such as two identical structs, the instance name is one of the struct variable names) See IDetailCategoryBuilder::GetProperty for clarification of parameters
IsPropertyPathAllowed()
virtual bool IDetailLayoutBuilder::IsPropertyPathAllowed (const FString & InPath) const pure virtual
Returns
True if the property path is contained within our allowed paths
IsPropertyVisible() [1/2]
virtual bool IDetailLayoutBuilder::IsPropertyVisible (const struct FPropertyAndParent & PropertyAndParent) const pure virtual
Returns
true if the property should be visible in the details panel or false if the specific details panel is not showing this property
IsPropertyVisible() [2/2]
virtual bool IDetailLayoutBuilder::IsPropertyVisible (TSharedRef< IPropertyHandle > PropertyHandle) const pure virtual
Returns
true if the property should be visible in the details panel or false if the specific details panel is not showing this property
RegisterInstancedCustomPropertyTypeLayout()
virtual void IDetailLayoutBuilder::RegisterInstancedCustomPropertyTypeLayout (FName PropertyTypeName, FOnGetPropertyTypeCustomizationInstance PropertyTypeLayoutDelegate, TSharedPtr< IPropertyTypeIdentifier > Identifier = nullptr) pure virtual
Registers a custom detail layout delegate for a specific type in this layout only.
Parameters
PropertyTypeName The type the custom detail layout is for
DetailLayoutDelegate The delegate to call when querying for custom detail layouts for the classes properties
SetPropertyGenerationAllowListPaths()
virtual void IDetailLayoutBuilder::SetPropertyGenerationAllowListPaths (const TSet< FString > & InPropertyGenerationAllowListPaths) pure virtual
This function sets property paths to generate PropertyNodes.This improves the performance for cases where PropertyView is only showing a few properties of the object by not generating all other PropertyNodes.
Parameters
InPropertyGenerationAllowListPaths Set of the property paths
SortCategories()
virtual void IDetailLayoutBuilder::SortCategories (const FOnCategorySortOrderFunction & SortFunction) pure virtual
Adds sort algorythm which overrides standard algorythm with that provided by the caller.
Function called on each category after all categories have been added, and provides caller with ability to override sort order.
Parameters
SortFunction Function called on final pass of detail panel build, which provides map of all categories to set final sort order on.
UE_DEPRECATED() [1/2]
IDetailLayoutBuilder::UE_DEPRECATED (5. 5, "Use GetDetailsViewSharedPtr() instead.") const inline
Definition at line 63 of file DetailLayoutBuilder.h.
References GetDetailsViewSharedPtr().
UE_DEPRECATED() [2/2]
IDetailLayoutBuilder::UE_DEPRECATED (5. 5, "Use GetDetailsViewSharedPtr() instead.") inline
Definition at line 74 of file DetailLayoutBuilder.h.
References GetDetailsViewSharedPtr().
The documentation for this class was generated from the following file:
DetailLayoutBuilder.h