Unreal Engine 5.6 C++ API: FMovieSceneAdditiveCameraTrackBlender Struct Reference
FMovieSceneAdditiveCameraTrackBlender Struct Reference
#include "MovieSceneCompilerRules.h"
Public Member Functions
virtual void Blend (FSegmentBlendData &BlendData) const override
Blend the specified data by performing some specific processing such as sorting or filtering.
Public Member Functions inherited from FMovieSceneTrackSegmentBlender
FMovieSceneTrackSegmentBlender ()
Default constructor.
virtual ~FMovieSceneTrackSegmentBlender ()
bool AllowEmptySegments () const
Check whether the resulting segments be empty.
bool CanFillEmptySpace () const
Check whether these rules can fill empty space between segments (such as to evaluate the nearest section)
virtual TOptional< FMovieSceneSegment > InsertEmptySpace (const TRange< FFrameNumber > &Range, const FMovieSceneSegment *PreviousSegment, const FMovieSceneSegment *NextSegment) const
Implementation function to insert empty space between two other segments or at the start/end.
Static Private Member Functions
static MOVIESCENE_API bool SortByStartTime (const FMovieSceneSectionData &A, const FMovieSceneSectionData &B)
Additional Inherited Members
Protected Attributes inherited from FMovieSceneTrackSegmentBlender
bool bAllowEmptySegments
Whether we allow empty segments to be evaluated or not.
bool bCanFillEmptySpace
Whether we can fill empty space (false signifies InsertEmptySpace will never be called)
Detailed Description
Definition at line 51 of file MovieSceneCompilerRules.h.
Member Function Documentation
Blend()
virtual void FMovieSceneAdditiveCameraTrackBlender::Blend (FSegmentBlendData & BlendData) const inline override virtual
Blend the specified data by performing some specific processing such as sorting or filtering.
Parameters
BlendData Blend data to be modified to suit the implementation's will
Reimplemented from FMovieSceneTrackSegmentBlender.
Definition at line 53 of file MovieSceneCompilerRules.h.
References TArray< InElementType, InAllocatorType >::Sort(), and SortByStartTime().
SortByStartTime()
MOVIESCENE_API bool FMovieSceneAdditiveCameraTrackBlender::SortByStartTime (const FMovieSceneSectionData & A, const FMovieSceneSectionData & B) static private
References A, and B.
Referenced by Blend().
The documentation for this struct was generated from the following file:
MovieSceneCompilerRules.h