Unreal Engine 5.6 C++ API: Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator Class Reference
Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator Class Reference
FConverterOperator converts from "FromDataType" to "ToDataType" using a implicit conversion operators.
Public Member Functions
FConverterOperator (TDataReadReference< FromDataType > InFromDataReference, TDataWriteReference< ToDataType > InToDataReference)
virtual ~FConverterOperator ()
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< FConverterOperator >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Private Attributes
bool bHasLoggedInvalidEnum = false
TDataReadReference< FromDataType > FromData
int32 PreviousIntValueForEnumConversion = 0
TDataWriteReference< ToDataType > ToData
Additional Inherited Members
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Detailed Description
template<typename FromDataType, typename ToDataType>
class Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator
FConverterOperator converts from "FromDataType" to "ToDataType" using a implicit conversion operators.
Definition at line 109 of file MetasoundAutoConverterNode.h.
Constructor & Destructor Documentation
FConverterOperator()
template<typename FromDataType, typename ToDataType> Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::FConverterOperator (TDataReadReference< FromDataType > InFromDataReference, TDataWriteReference< ToDataType > InToDataReference) inline
Definition at line 113 of file MetasoundAutoConverterNode.h.
References Execute(), FromData, and ToData.
~FConverterOperator()
template<typename FromDataType, typename ToDataType> virtual Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::~FConverterOperator () inline virtual
Definition at line 120 of file MetasoundAutoConverterNode.h.
Member Function Documentation
BindInputs()
template<typename FromDataType, typename ToDataType> virtual void Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 122 of file MetasoundAutoConverterNode.h.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), FromData, and Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetInputName().
BindOutputs()
template<typename FromDataType, typename ToDataType> virtual void Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 127 of file MetasoundAutoConverterNode.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetOutputName(), and ToData.
Execute()
template<typename FromDataType, typename ToDataType> void Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::Execute () inline
Definition at line 132 of file MetasoundAutoConverterNode.h.
References bHasLoggedInvalidEnum, Metasound::TIsAutoConvertible< TFromDataType, TToDataType >::bIsEnumToIntConversion, Metasound::TIsAutoConvertible< TFromDataType, TToDataType >::bIsIntToEnumConversion, Metasound::TEnumTraits< T >::DefaultValue, FromData, Metasound::GetMetasoundDataTypeDisplayText(), TOptional< OptionalType >::IsSet(), PreviousIntValueForEnumConversion, TEXT, ToData, ToString(), UE_LOG, and Warning.
Referenced by FConverterOperator(), and Reset().
Reset()
template<typename FromDataType, typename ToDataType> void Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 178 of file MetasoundAutoConverterNode.h.
References bHasLoggedInvalidEnum, Execute(), and PreviousIntValueForEnumConversion.
Field Documentation
bHasLoggedInvalidEnum
template<typename FromDataType, typename ToDataType> bool Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::bHasLoggedInvalidEnum = false private
Definition at line 191 of file MetasoundAutoConverterNode.h.
Referenced by Execute(), and Reset().
FromData
template<typename FromDataType, typename ToDataType> TDataReadReference<FromDataType> Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::FromData private
Definition at line 186 of file MetasoundAutoConverterNode.h.
Referenced by FConverterOperator(), BindInputs(), and Execute().
PreviousIntValueForEnumConversion
template<typename FromDataType, typename ToDataType> int32 Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::PreviousIntValueForEnumConversion = 0 private
Definition at line 192 of file MetasoundAutoConverterNode.h.
Referenced by Execute(), and Reset().
ToData
template<typename FromDataType, typename ToDataType> TDataWriteReference<ToDataType> Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::ToData private
Definition at line 187 of file MetasoundAutoConverterNode.h.
Referenced by FConverterOperator(), BindOutputs(), and Execute().
The documentation for this class was generated from the following file:
MetasoundAutoConverterNode.h