Unreal Engine 5.6 C++ API: FObjectInitializer::FOverrides::FOverride Struct Reference
FObjectInitializer::FOverrides::FOverride Struct Reference
Element of the override array.
Public Member Functions
FOverride (const FOverride &Other)
FOverride (FName InComponentName)
FOverride (FOverride &&)=default
FOverride & operator= (const FOverride &Other)
FOverride & operator= (FOverride &&)=default
Data Fields
bool bDoNotCreate = false
const UClass * ComponentClass = nullptr
FName ComponentName
TUniquePtr< FOverrides > SubOverrides
Detailed Description
Element of the override array.
Definition at line 1601 of file UObjectGlobals.h.
Constructor & Destructor Documentation
FOverride() [1/3]
FObjectInitializer::FOverrides::FOverride::FOverride (FName InComponentName) inline
Definition at line 1607 of file UObjectGlobals.h.
References ComponentName.
Referenced by FOverride(), FOverride(), operator=(), and operator=().
FOverride() [2/3]
FObjectInitializer::FOverrides::FOverride::FOverride (const FOverride & Other) inline
Definition at line 1621 of file UObjectGlobals.h.
References FOverride(), and Other.
FOverride() [3/3]
FObjectInitializer::FOverrides::FOverride::FOverride (FOverride &&) default
References FOverride().
Member Function Documentation
operator=() [1/2]
FOverride & FObjectInitializer::FOverrides::FOverride::operator= (const FOverride & Other) inline
Definition at line 1612 of file UObjectGlobals.h.
References FOverride(), bDoNotCreate, ComponentClass, ComponentName, MakeUnique(), Other, and SubOverrides.
operator=() [2/2]
FOverride & FObjectInitializer::FOverrides::FOverride::operator= (FOverride &&) default
References FOverride().
Field Documentation
bDoNotCreate
bool FObjectInitializer::FOverrides::FOverride::bDoNotCreate = false
Definition at line 1606 of file UObjectGlobals.h.
Referenced by operator=().
ComponentClass
const UClass* FObjectInitializer::FOverrides::FOverride::ComponentClass = nullptr
Definition at line 1604 of file UObjectGlobals.h.
Referenced by operator=().
ComponentName
FName FObjectInitializer::FOverrides::FOverride::ComponentName
Definition at line 1603 of file UObjectGlobals.h.
Referenced by FOverride(), and operator=().
SubOverrides
TUniquePtr<FOverrides> FObjectInitializer::FOverrides::FOverride::SubOverrides
Definition at line 1605 of file UObjectGlobals.h.
Referenced by operator=().
The documentation for this struct was generated from the following file:
UObjectGlobals.h