Unreal Engine 5.6 C++ API: FShaderMapContent Class Reference
FShaderMapContent Class Reference
A collection of shaders of different types.
#include "Shader.h"
Data Structures
struct FProjectShaderPipelineToKey
Public Member Functions
RENDERCORE_API FShaderMapContent (EShaderPlatform InPlatform)
Default constructor.
RENDERCORE_API ~FShaderMapContent ()
Destructor ensures pipelines cleared up.
RENDERCORE_API void AddShader (const FHashedName &TypeName, int32 PermutationId, FShader *Shader)
RENDERCORE_API void AddShaderPipeline (FShaderPipeline *Pipeline)
RENDERCORE_API void DumpShaderList (const FShaderMapBase &InShaderMap, FShaderListReport &Out) const
RENDERCORE_API void Empty ()
clears out all shaders and deletes shader pipelines held in the map
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API FShader * FindOrAddShader (const FHashedName &TypeName, int32 PermutationId, FShader *Shader)
RENDERCORE_API FShaderPipeline * FindOrAddShaderPipeline (FShaderPipeline *Pipeline)
RENDERCORE_API uint32 GetMaxNumInstructionsForShader (const FShaderMapBase &InShaderMap, FShaderType *ShaderType) const
RENDERCORE_API uint32 GetMaxTextureSamplersShaderMap (const FShaderMapBase &InShaderMap) const
uint32 GetNumShaderPipelines () const
RENDERCORE_API uint32 GetNumShaders () const
RENDERCORE_API void GetOutdatedTypes (const FShaderMapBase &InShaderMap, TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
RENDERCORE_API FShader * GetShader (const FHashedName &TypeName, int32 PermutationId=0) const
Finds the shader with the given type name.
FShader * GetShader (const FShaderType *ShaderType, int32 PermutationId=0) const
Finds the shader with the given type.
template<typename ShaderType>
ShaderType * GetShader (const typename ShaderType::FPermutationDomain &PermutationVector) const
Finds the shader with the given type.
template<typename ShaderType>
ShaderType * GetShader (int32 PermutationId=0) const
Finds the shader with the given type.
RENDERCORE_API void GetShaderList (const FShaderMapBase &InShaderMap, const FSHAHash &InMaterialShaderMapHash, TMap< FShaderId, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
RENDERCORE_API void GetShaderList (const FShaderMapBase &InShaderMap, TMap< FHashedName, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
FShaderPipeline * GetShaderPipeline (const FHashedName &PipelineTypeName) const
FShaderPipeline * GetShaderPipeline (const FShaderPipelineType *PipelineType) const
RENDERCORE_API void GetShaderPipelineList (const FShaderMapBase &InShaderMap, TArray< FShaderPipelineRef > &OutShaderPipelines, FShaderPipeline::EFilter Filter) const
Builds a list of the shader pipelines in a shader map.
TArrayView< const TMemoryImagePtr< FShaderPipeline > > GetShaderPipelines () const
RENDERCORE_API EShaderPlatform GetShaderPlatform () const
TArrayView< const TMemoryImagePtr< FShader > > GetShaders () const
const FShader::FShaderStatisticMap GetShaderStatisticsMapForShader (const FShaderMapBase &InShaderMap, FShaderType *ShaderType) const
bool HasShader (const FHashedName &TypeName, int32 PermutationId) const
Finds the shader with the given type.
bool HasShader (const FShaderType *Type, int32 PermutationId) const
bool HasShaderPipeline (const FHashedName &PipelineTypeName) const
bool HasShaderPipeline (const FShaderPipelineType *PipelineType) const
bool IsEmpty () const
RENDERCORE_API void RemoveShaderPipelineType (const FShaderPipelineType *ShaderPipelineType)
RENDERCORE_API void RemoveShaderTypePermutaion (const FHashedName &TypeName, int32 PermutationId)
Removes the shader of the given type from the shader map.
void RemoveShaderTypePermutaion (const FShaderType *Type, int32 PermutationId)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapBase &InShaderMap, EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API void UpdateHash (FSHA1 &Hasher) const
RENDERCORE_API void Validate (const FShaderMapBase &InShaderMap) const
Protected Types
using FMemoryImageHashTable = THashTable<FMemoryImageAllocator>
Protected Member Functions
RENDERCORE_API void EmptyShaderPipelines ()
LAYOUT_FIELD (FMemoryImageHashTable, ShaderHash)
LAYOUT_FIELD (FMemoryImageName, ShaderPlatformName)
The ShaderPlatform Name this shader map was compiled with.
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, ShaderTypes)
LAYOUT_FIELD (TMemoryImageArray< int32 >, ShaderPermutations)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShader > >, Shaders)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShaderPipeline > >, ShaderPipelines)
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderMapContent, RENDERCORE_API, NonVirtual)
Detailed Description
A collection of shaders of different types.
Definition at line 2341 of file Shader.h.
Member Typedef Documentation
FMemoryImageHashTable
using FShaderMapContent::FMemoryImageHashTable = THashTable<FMemoryImageAllocator> protected
Definition at line 2501 of file Shader.h.
Constructor & Destructor Documentation
FShaderMapContent()
RENDERCORE_API FShaderMapContent::FShaderMapContent (EShaderPlatform InPlatform) explicit
Default constructor.
Referenced by FMaterialShaderMapContent::FMaterialShaderMapContent(), FMeshMaterialShaderMap::FMeshMaterialShaderMap(), and DECLARE_EXPORTED_TYPE_LAYOUT().
~FShaderMapContent()
RENDERCORE_API FShaderMapContent::~FShaderMapContent ()
Destructor ensures pipelines cleared up.
Member Function Documentation
AddShader()
RENDERCORE_API void FShaderMapContent::AddShader (const FHashedName & TypeName, int32 PermutationId, FShader * Shader)
AddShaderPipeline()
RENDERCORE_API void FShaderMapContent::AddShaderPipeline (FShaderPipeline * Pipeline)
References Pipeline.
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderMapContent::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderMapContent , RENDERCORE_API , NonVirtual) private
References FShaderMapContent().
DumpShaderList()
RENDERCORE_API void FShaderMapContent::DumpShaderList (const FShaderMapBase & InShaderMap, FShaderListReport & Out) const
Referenced by FShaderMapBase::DumpShaderList().
Empty()
RENDERCORE_API void FShaderMapContent::Empty ()
clears out all shaders and deletes shader pipelines held in the map
EmptyShaderPipelines()
RENDERCORE_API void FShaderMapContent::EmptyShaderPipelines () protected
Finalize()
RENDERCORE_API void FShaderMapContent::Finalize (const FShaderMapResourceCode * Code)
FindOrAddShader()
RENDERCORE_API FShader * FShaderMapContent::FindOrAddShader (const FHashedName & TypeName, int32 PermutationId, FShader * Shader)
FindOrAddShaderPipeline()
RENDERCORE_API FShaderPipeline * FShaderMapContent::FindOrAddShaderPipeline (FShaderPipeline * Pipeline)
References Pipeline.
GetMaxNumInstructionsForShader()
RENDERCORE_API uint32 FShaderMapContent::GetMaxNumInstructionsForShader (const FShaderMapBase & InShaderMap, FShaderType * ShaderType) const
GetMaxTextureSamplersShaderMap()
RENDERCORE_API uint32 FShaderMapContent::GetMaxTextureSamplersShaderMap (const FShaderMapBase & InShaderMap) const
GetNumShaderPipelines()
uint32 FShaderMapContent::GetNumShaderPipelines () const inline
Returns
The number of shader pipelines in the map.
Definition at line 2470 of file Shader.h.
Referenced by FMaterialShaderMapContent::GetNumShaderPipelines().
GetNumShaders()
RENDERCORE_API uint32 FShaderMapContent::GetNumShaders () const
Returns
The number of shaders in the map.
Referenced by FMaterialShaderMapContent::GetNumShaders().
GetOutdatedTypes()
RENDERCORE_API void FShaderMapContent::GetOutdatedTypes (const FShaderMapBase & InShaderMap, TArray< const FShaderType * > & OutdatedShaderTypes, TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > & OutdatedFactoryTypes) const
GetShader() [1/4]
RENDERCORE_API FShader * FShaderMapContent::GetShader (const FHashedName & TypeName, int32 PermutationId = 0) const
Finds the shader with the given type name.
May return NULL.
GetShader() [2/4]
FShader * FShaderMapContent::GetShader (const FShaderType * ShaderType, int32 PermutationId = 0) const inline
Finds the shader with the given type.
May return NULL.
Definition at line 2377 of file Shader.h.
References FShaderType::GetHashedName(), and GetShader().
GetShader() [3/4]
template<typename ShaderType> ShaderType * FShaderMapContent::GetShader (const typename ShaderType::FPermutationDomain & PermutationVector) const inline
Finds the shader with the given type.
Asserts on failure.
Definition at line 2371 of file Shader.h.
References GetShader().
GetShader() [4/4]
template<typename ShaderType> ShaderType * FShaderMapContent::GetShader (int32 PermutationId = 0) const inline
Finds the shader with the given type.
Asserts on failure.
Definition at line 2362 of file Shader.h.
References checkf, GetShader(), GetShaderPlatform(), TEXT, and ToString().
Referenced by GetShader(), GetShader(), GetShader(), and HasShader().
GetShaderList() [1/2]
RENDERCORE_API void FShaderMapContent::GetShaderList (const FShaderMapBase & InShaderMap, const FSHAHash & InMaterialShaderMapHash, TMap< FShaderId, TShaderRef< FShader > > & OutShaders) const
Builds a list of the shaders in a shader map.
GetShaderList() [2/2]
RENDERCORE_API void FShaderMapContent::GetShaderList (const FShaderMapBase & InShaderMap, TMap< FHashedName, TShaderRef< FShader > > & OutShaders) const
Builds a list of the shaders in a shader map.
Key is FShaderType::TypeName
GetShaderPipeline() [1/2]
FShaderPipeline * FShaderMapContent::GetShaderPipeline (const FHashedName & PipelineTypeName) const inline
Definition at line 2478 of file Shader.h.
References Algo::BinarySearchBy(), and INDEX_NONE.
Referenced by GetShaderPipeline(), HasShaderPipeline(), and HasShaderPipeline().
GetShaderPipeline() [2/2]
FShaderPipeline * FShaderMapContent::GetShaderPipeline (const FShaderPipelineType * PipelineType) const inline
Definition at line 2484 of file Shader.h.
References FShaderPipelineType::GetHashedName(), and GetShaderPipeline().
GetShaderPipelineList()
RENDERCORE_API void FShaderMapContent::GetShaderPipelineList (const FShaderMapBase & InShaderMap, TArray< FShaderPipelineRef > & OutShaderPipelines, FShaderPipeline::EFilter Filter) const
Builds a list of the shader pipelines in a shader map.
References Filter.
GetShaderPipelines()
TArrayView< const TMemoryImagePtr< FShaderPipeline > > FShaderMapContent::GetShaderPipelines () const inline
Definition at line 2402 of file Shader.h.
GetShaderPlatform()
RENDERCORE_API EShaderPlatform FShaderMapContent::GetShaderPlatform () const
Referenced by GetShader().
GetShaders()
TArrayView< const TMemoryImagePtr< FShader > > FShaderMapContent::GetShaders () const inline
Definition at line 2397 of file Shader.h.
GetShaderStatisticsMapForShader()
const FShader::FShaderStatisticMap FShaderMapContent::GetShaderStatisticsMapForShader (const FShaderMapBase & InShaderMap, FShaderType * ShaderType) const inline
Definition at line 2449 of file Shader.h.
References GetShaderStatisticsMapForShader().
Referenced by GetShaderStatisticsMapForShader().
HasShader() [1/2]
bool FShaderMapContent::HasShader (const FHashedName & TypeName, int32 PermutationId) const inline
Finds the shader with the given type.
Definition at line 2386 of file Shader.h.
References GetShader().
Referenced by HasShader().
HasShader() [2/2]
bool FShaderMapContent::HasShader (const FShaderType * Type, int32 PermutationId) const inline
Definition at line 2392 of file Shader.h.
References HasShader().
HasShaderPipeline() [1/2]
bool FShaderMapContent::HasShaderPipeline (const FHashedName & PipelineTypeName) const inline
Definition at line 2489 of file Shader.h.
References GetShaderPipeline().
HasShaderPipeline() [2/2]
bool FShaderMapContent::HasShaderPipeline (const FShaderPipelineType * PipelineType) const inline
Definition at line 2490 of file Shader.h.
References GetShaderPipeline().
IsEmpty()
bool FShaderMapContent::IsEmpty () const inline
Returns
true if the map is empty
Definition at line 2461 of file Shader.h.
LAYOUT_FIELD() [1/6]
FShaderMapContent::LAYOUT_FIELD (FMemoryImageHashTable , ShaderHash) protected
LAYOUT_FIELD() [2/6]
FShaderMapContent::LAYOUT_FIELD (FMemoryImageName , ShaderPlatformName) protected
The ShaderPlatform Name this shader map was compiled with.
LAYOUT_FIELD() [3/6]
FShaderMapContent::LAYOUT_FIELD (TMemoryImageArray< FHashedName > , ShaderTypes) protected
LAYOUT_FIELD() [4/6]
FShaderMapContent::LAYOUT_FIELD (TMemoryImageArray< int32 > , ShaderPermutations) protected
LAYOUT_FIELD() [5/6]
FShaderMapContent::LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShader > > , Shaders) protected
LAYOUT_FIELD() [6/6]
FShaderMapContent::LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShaderPipeline > > , ShaderPipelines) protected
RemoveShaderPipelineType()
RENDERCORE_API void FShaderMapContent::RemoveShaderPipelineType (const FShaderPipelineType * ShaderPipelineType)
RemoveShaderTypePermutaion() [1/2]
RENDERCORE_API void FShaderMapContent::RemoveShaderTypePermutaion (const FHashedName & TypeName, int32 PermutationId)
Removes the shader of the given type from the shader map.
Parameters
Type Shader type to remove the entry for
Referenced by RemoveShaderTypePermutaion().
RemoveShaderTypePermutaion() [2/2]
void FShaderMapContent::RemoveShaderTypePermutaion (const FShaderType * Type, int32 PermutationId) inline
Definition at line 2421 of file Shader.h.
References RemoveShaderTypePermutaion().
SaveShaderStableKeys()
RENDERCORE_API void FShaderMapContent::SaveShaderStableKeys (const FShaderMapBase & InShaderMap, EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue & SaveKeyVal)
UpdateHash()
RENDERCORE_API void FShaderMapContent::UpdateHash (FSHA1 & Hasher) const
Validate()
RENDERCORE_API void FShaderMapContent::Validate (const FShaderMapBase & InShaderMap) const
The documentation for this class was generated from the following file:
Shader.h