Unreal Engine 5.6 C++ API: FDisplayClusterWeakStageActorPtr Struct Reference
FDisplayClusterWeakStageActorPtr Struct Reference
Wrapper around a WeakObjectPtr to manage actors implementing IDisplayClusterStageActor.
#include "DisplayClusterWeakStageActorPtr.h"
Public Member Functions
FDisplayClusterWeakStageActorPtr ()=default
FDisplayClusterWeakStageActorPtr (const AActor *InActorPtr)
virtual ~FDisplayClusterWeakStageActorPtr ()=default
AActor * AsActor () const
AActor * AsActorChecked () const
IDisplayClusterStageActor * Get () const
Dereference the weak pointer.
FORCEINLINE bool IsValid () const
Is the weak pointer valid.
FORCEINLINE IDisplayClusterStageActor * operator* () const
Dereference the weak pointer.
FORCEINLINE IDisplayClusterStageActor * operator-> () const
Dereference the weak pointer.
FORCEINLINE void Reset ()
Reset the weak pointer.
Protected Member Functions
FWeakObjectPtr & GetWeakObjectPtr ()
const FWeakObjectPtr & GetWeakObjectPtrConst () const
Private Attributes
FWeakObjectPtr ObjectPtr
Friends
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr != (RhsT*)nullptr)>
bool operator!= (const FDisplayClusterWeakStageActorPtr &Lhs, const RhsT *Rhs)
template<typename LhsT>
bool operator!= (const FDisplayClusterWeakStageActorPtr &Lhs, TYPE_OF_NULLPTR)
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr != (RhsT*)nullptr)>
bool operator!= (const LhsT *Lhs, const FDisplayClusterWeakStageActorPtr &Rhs)
template<typename RhsT>
bool operator!= (TYPE_OF_NULLPTR, const FDisplayClusterWeakStageActorPtr &Rhs)
bool operator== (const FDisplayClusterWeakStageActorPtr &Lhs, const FDisplayClusterWeakStageActorPtr &Rhs)
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr == (RhsT*)nullptr)>
bool operator== (const FDisplayClusterWeakStageActorPtr &Lhs, const RhsT *Rhs)
template<typename LhsT>
bool operator== (const FDisplayClusterWeakStageActorPtr &Lhs, TYPE_OF_NULLPTR)
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr == (RhsT*)nullptr)>
bool operator== (const LhsT *Lhs, const FDisplayClusterWeakStageActorPtr &Rhs)
template<typename RhsT>
bool operator== (TYPE_OF_NULLPTR, const FDisplayClusterWeakStageActorPtr &Rhs)
Detailed Description
Wrapper around a WeakObjectPtr to manage actors implementing IDisplayClusterStageActor.
Definition at line 13 of file DisplayClusterWeakStageActorPtr.h.
Constructor & Destructor Documentation
~FDisplayClusterWeakStageActorPtr()
virtual FDisplayClusterWeakStageActorPtr::~FDisplayClusterWeakStageActorPtr () virtual default
FDisplayClusterWeakStageActorPtr() [1/2]
FDisplayClusterWeakStageActorPtr::FDisplayClusterWeakStageActorPtr () default
Referenced by operator!=, operator!=, operator!=, operator!=, operator==, operator==, operator==, operator==, and operator==.
FDisplayClusterWeakStageActorPtr() [2/2]
FDisplayClusterWeakStageActorPtr::FDisplayClusterWeakStageActorPtr (const AActor * InActorPtr)
Member Function Documentation
AsActor()
AActor * FDisplayClusterWeakStageActorPtr::AsActor () const
AsActorChecked()
AActor * FDisplayClusterWeakStageActorPtr::AsActorChecked () const
Get()
IDisplayClusterStageActor * FDisplayClusterWeakStageActorPtr::Get () const
Dereference the weak pointer.
Referenced by operator!=, operator!=, operator*(), operator->(), operator==, and operator==.
GetWeakObjectPtr()
FWeakObjectPtr & FDisplayClusterWeakStageActorPtr::GetWeakObjectPtr () inline protected
Definition at line 30 of file DisplayClusterWeakStageActorPtr.h.
References ObjectPtr.
Referenced by Reset().
GetWeakObjectPtrConst()
const FWeakObjectPtr & FDisplayClusterWeakStageActorPtr::GetWeakObjectPtrConst () const inline protected
Definition at line 31 of file DisplayClusterWeakStageActorPtr.h.
References ObjectPtr.
Referenced by IsValid(), and operator==.
IsValid()
FORCEINLINE bool FDisplayClusterWeakStageActorPtr::IsValid () const inline
Is the weak pointer valid.
Definition at line 35 of file DisplayClusterWeakStageActorPtr.h.
References FORCEINLINE, and GetWeakObjectPtrConst().
Referenced by operator!=, operator!=, operator==, and operator==.
operator*()
FORCEINLINE IDisplayClusterStageActor * FDisplayClusterWeakStageActorPtr::operator* () const inline
Dereference the weak pointer.
Definition at line 47 of file DisplayClusterWeakStageActorPtr.h.
References FORCEINLINE, and Get().
operator->()
FORCEINLINE IDisplayClusterStageActor * FDisplayClusterWeakStageActorPtr::operator-> () const inline
Dereference the weak pointer.
Definition at line 53 of file DisplayClusterWeakStageActorPtr.h.
References FORCEINLINE, and Get().
Reset()
FORCEINLINE void FDisplayClusterWeakStageActorPtr::Reset () inline
Reset the weak pointer.
Definition at line 41 of file DisplayClusterWeakStageActorPtr.h.
References FORCEINLINE, and GetWeakObjectPtr().
Friends And Related Symbol Documentation
operator!= [1/4]
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr != (RhsT*)nullptr)> bool operator!= (const FDisplayClusterWeakStageActorPtr & Lhs, const RhsT * Rhs) friend
Definition at line 88 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and Get().
operator!= [2/4]
template<typename LhsT> bool operator!= (const FDisplayClusterWeakStageActorPtr & Lhs, TYPE_OF_NULLPTR) friend
Definition at line 100 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and IsValid().
operator!= [3/4]
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr != (RhsT*)nullptr)> bool operator!= (const LhsT * Lhs, const FDisplayClusterWeakStageActorPtr & Rhs) friend
Definition at line 94 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and Get().
operator!= [4/4]
template<typename RhsT> bool operator!= (TYPE_OF_NULLPTR , const FDisplayClusterWeakStageActorPtr & Rhs) friend
Definition at line 106 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and IsValid().
operator== [1/5]
bool operator== (const FDisplayClusterWeakStageActorPtr & Lhs, const FDisplayClusterWeakStageActorPtr & Rhs) friend
Definition at line 58 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and GetWeakObjectPtrConst().
operator== [2/5]
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr == (RhsT*)nullptr)> bool operator== (const FDisplayClusterWeakStageActorPtr & Lhs, const RhsT * Rhs) friend
Definition at line 64 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and Get().
operator== [3/5]
template<typename LhsT> bool operator== (const FDisplayClusterWeakStageActorPtr & Lhs, TYPE_OF_NULLPTR) friend
Definition at line 76 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and IsValid().
operator== [4/5]
template<typename LhsT, typename RhsT, typename = decltype((LhsT*)nullptr == (RhsT*)nullptr)> bool operator== (const LhsT * Lhs, const FDisplayClusterWeakStageActorPtr & Rhs) friend
Definition at line 70 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and Get().
operator== [5/5]
template<typename RhsT> bool operator== (TYPE_OF_NULLPTR , const FDisplayClusterWeakStageActorPtr & Rhs) friend
Definition at line 82 of file DisplayClusterWeakStageActorPtr.h.
References FDisplayClusterWeakStageActorPtr(), and IsValid().
Field Documentation
ObjectPtr
FWeakObjectPtr FDisplayClusterWeakStageActorPtr::ObjectPtr private
Definition at line 16 of file DisplayClusterWeakStageActorPtr.h.
Referenced by GetWeakObjectPtr(), and GetWeakObjectPtrConst().
The documentation for this struct was generated from the following file:
DisplayClusterWeakStageActorPtr.h