Unreal Engine 5.6 C++ API: UE::MovieScene::Interpolation::FConstantValue Struct Reference
UE::MovieScene::Interpolation::FConstantValue Struct Reference
Structure representing a constant value.
#include "MovieSceneInterpolation.h"
Public Member Functions
FConstantValue (FFrameNumber InOrigin, double InValue)
MOVIESCENE_API FConstantValue Derivative () const
MOVIESCENE_API FLinearInterpolation Integral (double ConstantOffset=0.0) const
UE_DEPRECATED (5.5, "Please provide an origin. This is required for Integral() to work correctly.") FConstantValue(double InValue)
Data Fields
FFrameNumber Origin
double Value
The constant value.
Detailed Description
Structure representing a constant value.
Temporarily includes a flag to determine whether it needs to be re-evaluated for legacy fallback.
Definition at line 125 of file MovieSceneInterpolation.h.
Constructor & Destructor Documentation
FConstantValue()
UE::MovieScene::Interpolation::FConstantValue::FConstantValue (FFrameNumber InOrigin, double InValue) inline
Definition at line 137 of file MovieSceneInterpolation.h.
References Origin, and Value.
Referenced by Derivative(), and UE_DEPRECATED().
Member Function Documentation
Derivative()
MOVIESCENE_API FConstantValue UE::MovieScene::Interpolation::FConstantValue::Derivative () const
References FConstantValue().
Integral()
MOVIESCENE_API FLinearInterpolation UE::MovieScene::Interpolation::FConstantValue::Integral (double ConstantOffset = 0.0) const
UE_DEPRECATED()
UE::MovieScene::Interpolation::FConstantValue::UE_DEPRECATED (5. 5, "Please provide an origin. This is required for Integral() to work correctly.") inline
Definition at line 132 of file MovieSceneInterpolation.h.
References FConstantValue().
Field Documentation
Origin
FFrameNumber UE::MovieScene::Interpolation::FConstantValue::Origin
Definition at line 130 of file MovieSceneInterpolation.h.
Referenced by FConstantValue().
Value
double UE::MovieScene::Interpolation::FConstantValue::Value
The constant value.
Definition at line 128 of file MovieSceneInterpolation.h.
Referenced by FConstantValue().
The documentation for this struct was generated from the following file:
MovieSceneInterpolation.h