Unreal Engine 5.6 C++ API: FDataLayersID Class Reference
FDataLayersID Class Reference
#include "DataLayersID.h"
Public Member Functions
FDataLayersID ()
FDataLayersID (const TArray< const UDataLayerInstance * > &DataLayerInstance)
uint32 GetHash () const
bool operator!= (const FDataLayersID &Other) const
bool operator== (const FDataLayersID &Other) const
Private Attributes
uint32 Hash
Friends
uint32 GetTypeHash (const FDataLayersID &InDataLayersID)
FArchive & operator<< (FArchive &InAr, FDataLayersID &InDataLayersID)
Detailed Description
Definition at line 10 of file DataLayersID.h.
Constructor & Destructor Documentation
FDataLayersID() [1/2]
FDataLayersID::FDataLayersID ()
Referenced by GetTypeHash, operator!=(), operator<<, and operator==().
FDataLayersID() [2/2]
FDataLayersID::FDataLayersID (const TArray< const UDataLayerInstance * > & DataLayerInstance)
Member Function Documentation
GetHash()
uint32 FDataLayersID::GetHash () const inline
Definition at line 26 of file DataLayersID.h.
References Hash.
Referenced by FSquare2DGridHelper::FGridLevel::FGridCell::AddActorSetInstance().
operator!=()
bool FDataLayersID::operator!= (const FDataLayersID & Other) const inline
Definition at line 21 of file DataLayersID.h.
References FDataLayersID(), and Other.
operator==()
bool FDataLayersID::operator== (const FDataLayersID & Other) const inline
Definition at line 16 of file DataLayersID.h.
References FDataLayersID(), Hash, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FDataLayersID & InDataLayersID) friend
Definition at line 36 of file DataLayersID.h.
References FDataLayersID(), and Hash.
operator<<
FArchive & operator<< (FArchive & InAr, FDataLayersID & InDataLayersID) friend
Definition at line 31 of file DataLayersID.h.
References FDataLayersID(), and Hash.
Field Documentation
Hash
uint32 FDataLayersID::Hash private
Definition at line 42 of file DataLayersID.h.
Referenced by GetHash(), GetTypeHash, operator<<, and operator==().
The documentation for this class was generated from the following file:
DataLayersID.h