Unreal Engine 5.6 C++ API: FAudioVirtualLoop Struct Reference
FAudioVirtualLoop Struct Reference
Class that tracks virtualized looping active sounds that are eligible to revive re-trigger as long as no stop request is received from the game thread.
#include "AudioVirtualLoop.h"
Public Member Functions
FAudioVirtualLoop ()
void CalculateUpdateInterval ()
Overrides the update interval to the provided length.
FActiveSound & GetActiveSound ()
Returns the internally-managed active sound.
const FActiveSound & GetActiveSound () const
float GetTimeVirtualized () const
Returns the time the sound has been virtualized.
float GetUpdateInterval () const
Returns the wait interval being observed before next update.
bool Update (float DeltaTime, bool bForceUpdate)
Updates the loop and checks if ready to play (or 'realize').
void UpdateFocusData (float DeltaTime)
Takes aggregate update delta and updates focus so that realization check can test if ready to play.
Static Public Member Functions
static bool IsEnabled ()
Whether the virtual loop system is enabled or not.
static bool ShouldListenerMoveForceUpdate (const FTransform &LastTransform, const FTransform &CurrentTransform)
Check to see if listener move is far enough such that a check for virtual loop realization is necessary.
static bool Virtualize (const FActiveSound &InActiveSound, bool bDoRangeCheck, FAudioVirtualLoop &OutVirtualLoop)
Checks if provided active sound is available to be virtualized.
static bool Virtualize (const FActiveSound &InActiveSound, FAudioDevice &AudioDevice, bool bDoRangeCheck, FAudioVirtualLoop &OutVirtualLoop)
Static Private Member Functions
static bool IsInAudibleRange (const FActiveSound &InActiveSound, const FAudioDevice *InAudioDevice=nullptr)
Check if provided active sound is in audible range.
Private Attributes
FActiveSound * ActiveSound
float TimeSinceLastUpdate
float TimeVirtualized
float UpdateInterval
TArray< Audio::FModulationDestination > VolumeConcurrencyDestinations
Array of Modulation Destinations for virtualized ActiveSounds to use when evaluating volume for concurrency For sounds with multiple wave instance (e.g.
Detailed Description
Class that tracks virtualized looping active sounds that are eligible to revive re-trigger as long as no stop request is received from the game thread.
Definition at line 12 of file AudioVirtualLoop.h.
Constructor & Destructor Documentation
FAudioVirtualLoop()
FAudioVirtualLoop::FAudioVirtualLoop ()
Referenced by Virtualize(), and Virtualize().
Member Function Documentation
CalculateUpdateInterval()
void FAudioVirtualLoop::CalculateUpdateInterval ()
Overrides the update interval to the provided length.
GetActiveSound() [1/2]
FActiveSound & FAudioVirtualLoop::GetActiveSound ()
Returns the internally-managed active sound.
GetActiveSound() [2/2]
const FActiveSound & FAudioVirtualLoop::GetActiveSound () const
GetTimeVirtualized()
float FAudioVirtualLoop::GetTimeVirtualized () const
Returns the time the sound has been virtualized.
GetUpdateInterval()
float FAudioVirtualLoop::GetUpdateInterval () const
Returns the wait interval being observed before next update.
IsEnabled()
bool FAudioVirtualLoop::IsEnabled () static
Whether the virtual loop system is enabled or not.
IsInAudibleRange()
bool FAudioVirtualLoop::IsInAudibleRange (const FActiveSound & InActiveSound, const FAudioDevice * InAudioDevice = nullptr) static private
Check if provided active sound is in audible range.
ShouldListenerMoveForceUpdate()
bool FAudioVirtualLoop::ShouldListenerMoveForceUpdate (const FTransform & LastTransform, const FTransform & CurrentTransform) static
Check to see if listener move is far enough such that a check for virtual loop realization is necessary.
Update()
bool FAudioVirtualLoop::Update (float DeltaTime, bool bForceUpdate)
Updates the loop and checks if ready to play (or 'realize').
Returns whether or not the sound is ready to be realized.
References DeltaTime.
UpdateFocusData()
void FAudioVirtualLoop::UpdateFocusData (float DeltaTime)
Takes aggregate update delta and updates focus so that realization check can test if ready to play.
References DeltaTime.
Virtualize() [1/2]
bool FAudioVirtualLoop::Virtualize (const FActiveSound & InActiveSound, bool bDoRangeCheck, FAudioVirtualLoop & OutVirtualLoop) static
Checks if provided active sound is available to be virtualized.
If so, returns new active sound ready to be added to virtual loop management by parent audio device.
References FAudioVirtualLoop().
Virtualize() [2/2]
bool FAudioVirtualLoop::Virtualize (const FActiveSound & InActiveSound, FAudioDevice & AudioDevice, bool bDoRangeCheck, FAudioVirtualLoop & OutVirtualLoop) static
References FAudioVirtualLoop().
Field Documentation
ActiveSound
FActiveSound* FAudioVirtualLoop::ActiveSound private
Definition at line 19 of file AudioVirtualLoop.h.
TimeSinceLastUpdate
float FAudioVirtualLoop::TimeSinceLastUpdate private
Definition at line 15 of file AudioVirtualLoop.h.
TimeVirtualized
float FAudioVirtualLoop::TimeVirtualized private
Definition at line 16 of file AudioVirtualLoop.h.
UpdateInterval
float FAudioVirtualLoop::UpdateInterval private
Definition at line 17 of file AudioVirtualLoop.h.
VolumeConcurrencyDestinations
TArray<Audio::FModulationDestination> FAudioVirtualLoop::VolumeConcurrencyDestinations private
Array of Modulation Destinations for virtualized ActiveSounds to use when evaluating volume for concurrency For sounds with multiple wave instance (e.g.
Sound Cues), each WaveInstance needs its own Modulation Destination.
Definition at line 25 of file AudioVirtualLoop.h.
The documentation for this struct was generated from the following file:
AudioVirtualLoop.h