Unreal Engine 5.6 C++ API: UE::LiveLink::Compression Namespace Reference
UE::LiveLink::Compression Namespace Reference
What compression method should be used on the LiveLink data.
Functions
FName GetCompressionAlgorithm ()
Get the named compression algorithm to invoke with serializer and memory compressors.
FName GetCompressionAlgorithm (ELiveLinkCompressionMethod Method)
Get the named compression algorithm based on the provided details.
ELiveLinkCompressionBias GetCompressionBias (ECompressionFlags Flags)
Get LiveLinkCompressionBias from a ECompressionFlags.
ECompressionFlags GetCompressionFlags ()
Get the default flags to use when invoking the compressor.
ELiveLinkCompressionMethod GetCompressionMethod (FName NamedMethod)
Convert a compression method name to a ELiveLinkCompressionMethod.
int32 GetConsoleVariableCompressionFlags ()
Function to check the console variable for the compression flags.
int32 GetConsoleVariableCompressionType ()
Get the compression type from the console variable setting.
ECompressionFlags GetCoreCompressionFlags (ELiveLinkCompressionBias InBias)
Get the compression enum value given the LiveLink compression settings.
template<typename SizeType>
bool ShouldCompress (SizeType DataSize)
Based on the size of the data to compress indicate if we should invoke the compressor.
Detailed Description
What compression method should be used on the LiveLink data.
The bias (if any) to use when compressing the data.
Function Documentation
GetCompressionAlgorithm() [1/2]
FName UE::LiveLink::Compression::GetCompressionAlgorithm () inline
Get the named compression algorithm to invoke with serializer and memory compressors.
Definition at line 95 of file LiveLinkCompression.h.
References GetConsoleVariableCompressionType().
GetCompressionAlgorithm() [2/2]
FName UE::LiveLink::Compression::GetCompressionAlgorithm (ELiveLinkCompressionMethod Method) inline
Get the named compression algorithm based on the provided details.
Current this is only Zlib or Oodle.
Definition at line 121 of file LiveLinkCompression.h.
GetCompressionBias()
ELiveLinkCompressionBias UE::LiveLink::Compression::GetCompressionBias (ECompressionFlags Flags) inline
Get LiveLinkCompressionBias from a ECompressionFlags.
Definition at line 141 of file LiveLinkCompression.h.
References COMPRESS_BiasMemory, COMPRESS_BiasSpeed, and Flags.
GetCompressionFlags()
ECompressionFlags UE::LiveLink::Compression::GetCompressionFlags () inline
Get the default flags to use when invoking the compressor.
Definition at line 106 of file LiveLinkCompression.h.
References COMPRESS_BiasSize, COMPRESS_BiasSpeed, COMPRESS_NoFlags, and GetConsoleVariableCompressionFlags().
GetCompressionMethod()
ELiveLinkCompressionMethod UE::LiveLink::Compression::GetCompressionMethod (FName NamedMethod) inline
Convert a compression method name to a ELiveLinkCompressionMethod.
Definition at line 158 of file LiveLinkCompression.h.
References check.
GetConsoleVariableCompressionFlags()
int32 UE::LiveLink::Compression::GetConsoleVariableCompressionFlags ()
Function to check the console variable for the compression flags.
Speed vs size.
Referenced by GetCompressionFlags().
GetConsoleVariableCompressionType()
int32 UE::LiveLink::Compression::GetConsoleVariableCompressionType ()
Get the compression type from the console variable setting.
Referenced by GetCompressionAlgorithm().
GetCoreCompressionFlags()
ECompressionFlags UE::LiveLink::Compression::GetCoreCompressionFlags (ELiveLinkCompressionBias InBias) inline
Get the compression enum value given the LiveLink compression settings.
This the value passed into the serializer and memory compressor.
Definition at line 127 of file LiveLinkCompression.h.
References COMPRESS_BiasSize, COMPRESS_BiasSpeed, and COMPRESS_NoFlags.
ShouldCompress()
template<typename SizeType> bool UE::LiveLink::Compression::ShouldCompress (SizeType DataSize) inline
Based on the size of the data to compress indicate if we should invoke the compressor.
Definition at line 81 of file LiveLinkCompression.h.
References DataSize.