Unreal Engine 5.6 C++ API: FSlateInvalidationWidgetVisibility Struct Reference
FSlateInvalidationWidgetVisibility Struct Reference
#include "WidgetProxy.h"
Public Member Functions
FSlateInvalidationWidgetVisibility ()
FSlateInvalidationWidgetVisibility (const FSlateInvalidationWidgetVisibility &Other)
FSlateInvalidationWidgetVisibility (EVisibility InVisibility)
FSlateInvalidationWidgetVisibility (FSlateInvalidationWidgetVisibility ParentFlags, EVisibility InVisibility)
bool AreAncestorsVisible () const
bool IsCollapsed () const
bool IsCollapseDirectly () const
bool IsCollapseIndirectly () const
bool IsVisible () const
bool IsVisibleDirectly () const
FSlateInvalidationWidgetVisibility MimicAsParent () const
Assign the ancestors value to the widget values.
bool operator!= (FSlateInvalidationWidgetVisibility Other) const
FSlateInvalidationWidgetVisibility & operator= (const FSlateInvalidationWidgetVisibility &Other)
bool operator== (FSlateInvalidationWidgetVisibility Other) const
void SetAncestorsVisibility (FSlateInvalidationWidgetVisibility ParentFlags)
void SetVisibility (FSlateInvalidationWidgetVisibility ParentFlags, EVisibility InVisibility)
Private Attributes
union {
struct {
uint8 bAncestorCollapse: 1
uint8 bAncestorsVisible: 1
uint8 bCollapse: 1
uint8 bVisible: 1
uint8 FlagPadding: 4
}
uint8 Flags
};
Detailed Description
Definition at line 34 of file WidgetProxy.h.
Constructor & Destructor Documentation
FSlateInvalidationWidgetVisibility() [1/4]
FSlateInvalidationWidgetVisibility::FSlateInvalidationWidgetVisibility () inline
Definition at line 37 of file WidgetProxy.h.
References Flags.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), MimicAsParent(), operator!=(), operator=(), operator==(), SetAncestorsVisibility(), and SetVisibility().
FSlateInvalidationWidgetVisibility() [2/4]
FSlateInvalidationWidgetVisibility::FSlateInvalidationWidgetVisibility (EVisibility InVisibility) inline
Definition at line 40 of file WidgetProxy.h.
References bAncestorCollapse, bAncestorsVisible, bCollapse, bVisible, FlagPadding, and IsVisible().
FSlateInvalidationWidgetVisibility() [3/4]
FSlateInvalidationWidgetVisibility::FSlateInvalidationWidgetVisibility (FSlateInvalidationWidgetVisibility ParentFlags, EVisibility InVisibility) inline
Definition at line 47 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), bAncestorCollapse, bAncestorsVisible, bCollapse, bVisible, FlagPadding, IsCollapsed(), and IsVisible().
FSlateInvalidationWidgetVisibility() [4/4]
FSlateInvalidationWidgetVisibility::FSlateInvalidationWidgetVisibility (const FSlateInvalidationWidgetVisibility & Other) inline
Definition at line 54 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), Flags, and Other.
Member Function Documentation
AreAncestorsVisible()
bool FSlateInvalidationWidgetVisibility::AreAncestorsVisible () const inline
Returns
true when all the widget ancestors are visible but the widget itself may not be visible.
Definition at line 60 of file WidgetProxy.h.
References bAncestorsVisible.
IsCollapsed()
bool FSlateInvalidationWidgetVisibility::IsCollapsed () const inline
Returns
true when at least one of the widget's ancestor is collapse or the widget itself is collapse.
Definition at line 64 of file WidgetProxy.h.
References bAncestorCollapse, and bCollapse.
Referenced by FSlateInvalidationWidgetVisibility(), and SetAncestorsVisibility().
IsCollapseDirectly()
bool FSlateInvalidationWidgetVisibility::IsCollapseDirectly () const inline
Returns
true the widget itself is collapse.
Definition at line 68 of file WidgetProxy.h.
References bCollapse.
IsCollapseIndirectly()
bool FSlateInvalidationWidgetVisibility::IsCollapseIndirectly () const inline
Returns
true when at least one of the widget's ancestor is collapse but the widget itself may not be collapse.
Definition at line 66 of file WidgetProxy.h.
References bAncestorCollapse.
IsVisible()
bool FSlateInvalidationWidgetVisibility::IsVisible () const inline
Returns
true when all the widget ancestors are visible and the widget itself is visible.
Definition at line 58 of file WidgetProxy.h.
References bAncestorsVisible, and bVisible.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), and SetAncestorsVisibility().
IsVisibleDirectly()
bool FSlateInvalidationWidgetVisibility::IsVisibleDirectly () const inline
Returns
true when the widget itself is visible (but may have invisible ancestors).
Definition at line 62 of file WidgetProxy.h.
References bVisible.
MimicAsParent()
FSlateInvalidationWidgetVisibility FSlateInvalidationWidgetVisibility::MimicAsParent () const inline
Assign the ancestors value to the widget values.
Mimicking as it would be the parent.
Definition at line 82 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), bAncestorCollapse, and bAncestorsVisible.
operator!=()
bool FSlateInvalidationWidgetVisibility::operator!= (FSlateInvalidationWidgetVisibility Other) const inline
Definition at line 93 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), Flags, and Other.
operator=()
FSlateInvalidationWidgetVisibility & FSlateInvalidationWidgetVisibility::operator= (const FSlateInvalidationWidgetVisibility & Other) inline
Definition at line 55 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), Flags, and Other.
operator==()
bool FSlateInvalidationWidgetVisibility::operator== (FSlateInvalidationWidgetVisibility Other) const inline
Definition at line 92 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), Flags, and Other.
SetAncestorsVisibility()
void FSlateInvalidationWidgetVisibility::SetAncestorsVisibility (FSlateInvalidationWidgetVisibility ParentFlags) inline
Definition at line 75 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility(), bAncestorCollapse, bAncestorsVisible, IsCollapsed(), and IsVisible().
SetVisibility()
void FSlateInvalidationWidgetVisibility::SetVisibility (FSlateInvalidationWidgetVisibility ParentFlags, EVisibility InVisibility) inline
Definition at line 70 of file WidgetProxy.h.
References FSlateInvalidationWidgetVisibility().
Field Documentation
[union]
union { ... } FSlateInvalidationWidgetVisibility
bAncestorCollapse
uint8 FSlateInvalidationWidgetVisibility::bAncestorCollapse
Definition at line 102 of file WidgetProxy.h.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), IsCollapsed(), IsCollapseIndirectly(), MimicAsParent(), and SetAncestorsVisibility().
bAncestorsVisible
uint8 FSlateInvalidationWidgetVisibility::bAncestorsVisible
Definition at line 100 of file WidgetProxy.h.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), AreAncestorsVisible(), IsVisible(), MimicAsParent(), and SetAncestorsVisibility().
bCollapse
uint8 FSlateInvalidationWidgetVisibility::bCollapse
Definition at line 103 of file WidgetProxy.h.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), IsCollapsed(), and IsCollapseDirectly().
bVisible
uint8 FSlateInvalidationWidgetVisibility::bVisible
Definition at line 101 of file WidgetProxy.h.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), IsVisible(), and IsVisibleDirectly().
FlagPadding
uint8 FSlateInvalidationWidgetVisibility::FlagPadding
Definition at line 104 of file WidgetProxy.h.
Referenced by FSlateInvalidationWidgetVisibility(), and FSlateInvalidationWidgetVisibility().
Flags
uint8 FSlateInvalidationWidgetVisibility::Flags
Definition at line 106 of file WidgetProxy.h.
Referenced by FSlateInvalidationWidgetVisibility(), FSlateInvalidationWidgetVisibility(), operator!=(), operator=(), and operator==().
The documentation for this struct was generated from the following file:
WidgetProxy.h