Unreal Engine 5.6 C++ API: FFieldPath Struct Reference
FFieldPath Struct Reference
#include "FieldPath.h"
Public Member Functions
FFieldPath ()=default
FFieldPath (FField *InField)
void Generate (const TCHAR *InFieldPathString)
Generates path from the passed in field pointer.
void Generate (FField *InField)
Generates path from the passed in field pointer.
FORCEINLINE FField * GetTyped (FFieldClass *ExpectedType, UStruct *InCurrentStruct=nullptr) const
Gets the field represented by this FFieldPath.
bool IsPathToFieldEmpty () const
Returns true if the field path is empty (does not test if the owner is valid) This is usually used to verify if the reason behind this field being unresolved is because the owner is missing or the property couldn't be found.
bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a FField, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool operator!= (const FFieldPath &InOther) const
FORCEINLINE bool operator== (const FFieldPath &InOther) const
void Reset ()
Reset the weak pointer back to the NULL state.
FORCEINLINE void ResolveField (FFieldClass *ExpectedClass=FField::StaticClass(), UStruct *InCurrentStruct=nullptr, EPathResolveType InResolveType=FFieldPath::UseStructIfOuterNotFound) const
Tries to resolve the path and caches the result.
FString ToString () const
FField * TryToResolvePath (UStruct *InCurrentStruct, EPathResolveType InResolveType=FFieldPath::UseStructIfOuterNotFound) const
Tries to resolve the path without caching the resolved pointer.
Protected Types
enum EPathResolveType { UseStructIfOuterNotFound = 0 , UseStructAlways = 1 }
Protected Member Functions
FORCEINLINE void ClearCachedField () const
Clears the cached value so that the next time Get() is called, it will be resolved again.
FORCEINLINE bool NeedsResolving () const
Protected Attributes
TArray< FName > Path
Path to the FField object from the innermost FField to the outermost UObject (UPackage)
FField * ResolvedField = nullptr
Untracked pointer to the resolved property.
TWeakObjectPtr< UStruct > ResolvedOwner
The cached owner of this field.
Private Member Functions
FORCEINLINE void ClearCachedFieldInternal ()
UStruct * ConvertFromFullPath (FLinkerLoad *InLinker)
Tries to convert the full path stored in this FFieldPath to the new format (Owner reference + path to the field)
FORCEINLINE FUObjectItem * GetResolvedOwnerItemInternal ()
FOR INTERNAL USE ONLY: gets the pointer to the resolved field without trying to resolve it.
UStruct * TryToResolveOwnerFromLinker (FLinkerLoad *InLinker) const
Tries to resolve the field owner.
UStruct * TryToResolveOwnerFromStruct (UStruct *InCurrentStruct=nullptr, EPathResolveType InResolveType=FFieldPath::UseStructIfOuterNotFound) const
Tries to resolve the field owner.
Friends
class FFieldPathProperty
struct FGCInternals
FORCEINLINE friend uint32 GetTypeHash (const FFieldPath &InPropertyPath)
Hash function.
FArchive & operator<< (FArchive &Ar, FFieldPath &InOutPropertyPath)
template<class T>
struct TWeakFieldPtr
Detailed Description
Definition at line 35 of file FieldPath.h.
Member Enumeration Documentation
EPathResolveType
enum FFieldPath::EPathResolveType protected
Enumerator
UseStructIfOuterNotFound
UseStructAlways
Definition at line 49 of file FieldPath.h.
Constructor & Destructor Documentation
FFieldPath() [1/2]
FFieldPath::FFieldPath () default
Referenced by TFieldPath< T >::TFieldPath(), TFieldPath< T >::TFieldPath(), TFieldPath< T >::TFieldPath(), TFieldPath< T >::TFieldPath(), GetTypeHash, operator!=(), operator<<, and operator==().
FFieldPath() [2/2]
FFieldPath::FFieldPath (FField * InField) inline
Definition at line 147 of file FieldPath.h.
References Generate().
Member Function Documentation
ClearCachedField()
FORCEINLINE void FFieldPath::ClearCachedField () const inline protected
Clears the cached value so that the next time Get() is called, it will be resolved again.
Definition at line 90 of file FieldPath.h.
References FORCEINLINE, and ResolvedField.
Referenced by Reset(), and TFieldPath< T >::ResolveWithRenamedStructPackage().
ClearCachedFieldInternal()
FORCEINLINE void FFieldPath::ClearCachedFieldInternal () inline private
Definition at line 113 of file FieldPath.h.
References FORCEINLINE, ResolvedField, and ResolvedOwner.
ConvertFromFullPath()
UStruct * FFieldPath::ConvertFromFullPath (FLinkerLoad * InLinker) private
Tries to convert the full path stored in this FFieldPath to the new format (Owner reference + path to the field)
Parameters
InLinker the current linker load serializing this field path
Returns
Resulved owner struct
Generate() [1/2]
void FFieldPath::Generate (const TCHAR * InFieldPathString)
Generates path from the passed in field pointer.
Generate() [2/2]
void FFieldPath::Generate (FField * InField)
Generates path from the passed in field pointer.
Referenced by FFieldPath(), TFieldPath< T >::TFieldPath(), and TFieldPath< T >::operator=().
GetResolvedOwnerItemInternal()
FORCEINLINE FUObjectItem * FFieldPath::GetResolvedOwnerItemInternal () inline private
FOR INTERNAL USE ONLY: gets the pointer to the resolved field without trying to resolve it.
Definition at line 109 of file FieldPath.h.
References FORCEINLINE, and ResolvedOwner.
GetTyped()
FORCEINLINE FField * FFieldPath::GetTyped (FFieldClass * ExpectedType, UStruct * InCurrentStruct = nullptr) const inline
Gets the field represented by this FFieldPath.
Parameters
ExpectedType Expected type of the resolved field
InCurrentStruct Struct that's trying to resolve this field path
Returns
Field represented by this FFieldPath or null if it couldn't be resolved
Definition at line 214 of file FieldPath.h.
References FORCEINLINE, NeedsResolving(), Path, ResolvedField, ResolveField(), and UseStructIfOuterNotFound.
Referenced by TFieldPath< T >::Get().
IsPathToFieldEmpty()
bool FFieldPath::IsPathToFieldEmpty () const inline
Returns true if the field path is empty (does not test if the owner is valid) This is usually used to verify if the reason behind this field being unresolved is because the owner is missing or the property couldn't be found.
Definition at line 227 of file FieldPath.h.
References Path.
Referenced by FPropertyProxyArchive::operator<<().
IsStale()
bool FFieldPath::IsStale () const inline
Slightly different than !IsValid(), returns true if this used to point to a FField, but doesn't any more and has not been assigned or reset in the mean time.
Returns
true if this used to point at a real object but no longer does.
Definition at line 236 of file FieldPath.h.
References ResolvedField, ResolvedOwner, and WITH_EDITORONLY_DATA.
NeedsResolving()
FORCEINLINE bool FFieldPath::NeedsResolving () const inline protected
Definition at line 69 of file FieldPath.h.
References FORCEINLINE, Owner, ResolvedField, and ResolvedOwner.
Referenced by GetTyped().
operator!=()
FORCEINLINE bool FFieldPath::operator!= (const FFieldPath & InOther) const inline
Definition at line 260 of file FieldPath.h.
References FFieldPath(), FORCEINLINE, Path, and ResolvedOwner.
operator==()
FORCEINLINE bool FFieldPath::operator== (const FFieldPath & InOther) const inline
Definition at line 255 of file FieldPath.h.
References FFieldPath(), FORCEINLINE, Path, and ResolvedOwner.
Reset()
void FFieldPath::Reset () inline
Reset the weak pointer back to the NULL state.
Definition at line 248 of file FieldPath.h.
References ClearCachedField(), Path, and ResolvedOwner.
Referenced by TListTypeTraits< TFieldPath< T > >::ResetPtr().
ResolveField()
FORCEINLINE void FFieldPath::ResolveField (FFieldClass * ExpectedClass = FField::StaticClass(), UStruct * InCurrentStruct = nullptr, EPathResolveType InResolveType = FFieldPath::UseStructIfOuterNotFound) const inline
Tries to resolve the path and caches the result.
Parameters
ExpectedClass Expected class of the resolved field
InCurrentStruct Struct that's trying to resolve this field path
Definition at line 179 of file FieldPath.h.
References check, FORCEINLINE, FField::GetClass(), FField::IsA(), Owner, ResolvedField, ResolvedOwner, FField::StaticClass(), TryToResolvePath(), UseStructIfOuterNotFound, and WITH_EDITORONLY_DATA.
Referenced by GetTyped(), and TFieldPath< T >::ResolveWithRenamedStructPackage().
ToString()
FString FFieldPath::ToString () const
TryToResolveOwnerFromLinker()
UStruct * FFieldPath::TryToResolveOwnerFromLinker (FLinkerLoad * InLinker) const private
Tries to resolve the field owner.
Parameters
InLinker the current linker load serializing this field path
Returns
Resolved owner struct
TryToResolveOwnerFromStruct()
UStruct * FFieldPath::TryToResolveOwnerFromStruct (UStruct * InCurrentStruct = nullptr, EPathResolveType InResolveType = FFieldPath::UseStructIfOuterNotFound) const private
Tries to resolve the field owner.
Parameters
InCurrentStruct Struct that's trying to resolve this field path
InResolveType Type of the resolve operation
Returns
Resolved owner struct
References UseStructIfOuterNotFound.
TryToResolvePath()
FField * FFieldPath::TryToResolvePath (UStruct * InCurrentStruct, EPathResolveType InResolveType = FFieldPath::UseStructIfOuterNotFound) const
Tries to resolve the path without caching the resolved pointer.
Parameters
InCurrentStruct Struct that's trying to resolve this field path
OutOwnerIndex ObjectIndex of the Owner UObject
Returns
Resolved field or null
References UseStructIfOuterNotFound.
Referenced by ResolveField().
Friends And Related Symbol Documentation
FFieldPathProperty
friend class FFieldPathProperty friend
Definition at line 44 of file FieldPath.h.
References FFieldPathProperty.
Referenced by FFieldPathProperty.
FGCInternals
friend struct FGCInternals friend
Definition at line 37 of file FieldPath.h.
References FGCInternals.
Referenced by FGCInternals.
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (const FFieldPath & InPropertyPath) friend
Hash function.
Definition at line 270 of file FieldPath.h.
References FFieldPath(), FORCEINLINE, GetTypeHash, HashCombine(), and Path.
Referenced by GetTypeHash.
operator<<
FArchive & operator<< (FArchive & Ar, FFieldPath & InOutPropertyPath) friend
References FFieldPath(), and Ar.
TWeakFieldPtr
template<class T> friend struct TWeakFieldPtr friend
Definition at line 41 of file FieldPath.h.
References TWeakFieldPtr.
Referenced by TWeakFieldPtr.
Field Documentation
Path
TArray<FName> FFieldPath::Path protected
Path to the FField object from the innermost FField to the outermost UObject (UPackage)
Definition at line 67 of file FieldPath.h.
Referenced by GetTyped(), GetTypeHash, IsPathToFieldEmpty(), operator!=(), operator==(), and Reset().
ResolvedField
FField* FFieldPath::ResolvedField = nullptr mutable protected
Untracked pointer to the resolved property.
Definition at line 56 of file FieldPath.h.
Referenced by ClearCachedField(), ClearCachedFieldInternal(), GetTyped(), IsStale(), NeedsResolving(), TFieldPath< T >::operator=(), ResolveField(), and TFieldPath< T >::ResolveWithRenamedStructPackage().
ResolvedOwner
TWeakObjectPtr<UStruct> FFieldPath::ResolvedOwner mutable protected
The cached owner of this field.
Even though implemented as a weak pointer, GC will keep a strong reference to it if exposed through UPROPERTY macro
Definition at line 64 of file FieldPath.h.
Referenced by ClearCachedFieldInternal(), GetResolvedOwnerItemInternal(), IsStale(), NeedsResolving(), operator!=(), operator==(), Reset(), and ResolveField().
The documentation for this struct was generated from the following file:
FieldPath.h