Unreal Engine 5.6 C++ API: IPlatformFile Class Reference
IPlatformFile Class Reference abstract
File I/O Interface.
#include "GenericPlatformFile.h"
Data Structures
class FDirectoryStatVisitor
Base class for file and directory visitors that take all the stat data.
class FDirectoryVisitor
Base class for file and directory visitors that take only the name.
class IFileServerMessageHandler
Helper class to send/receive data to the file server function.
Public Types
enum class EOpenReadFlags : uint8 { None = 0 , AllowWrite = 1 << 0 , AllowDelete = 1 << 1 }
Flags to be used when opening a file for reading via IPlatformFile::OpenRead.
typedef TFunctionRef< bool(const TCHAR *, const FFileJournalData &)> FDirectoryJournalVisitorFunc
File and directory visitor function that takes FileJournal data.
typedef TFunctionRef< bool(const TCHAR *, const FFileStatData &)> FDirectoryStatVisitorFunc
File and directory visitor function that takes all the stat data.
typedef TFunctionRef< bool(const TCHAR *, bool)> FDirectoryVisitorFunc
File and directory visitor function that takes only the name.
Public Member Functions
IPlatformFile ()
Constructor/Destructor.
virtual ~IPlatformFile ()
virtual void AddLocalDirectories (TArray< FString > &LocalDirectories)
Identifies any platform specific paths that are guaranteed to be local (i.e.
virtual void BypassSecurity (bool bInBypass)
virtual FString ConvertToAbsolutePathForExternalAppForRead (const TCHAR *Filename)
Converts passed in filename to use an absolute path (for reading).
virtual FString ConvertToAbsolutePathForExternalAppForWrite (const TCHAR *Filename)
Converts passed in filename to use an absolute path (for writing)
virtual bool CopyDirectoryTree (const TCHAR *DestinationDirectory, const TCHAR *Source, bool bOverwriteAllExisting)
Copy a file or a hierarchy of files (directory).
virtual bool CopyFile (const TCHAR *To, const TCHAR *From, EPlatformFileRead ReadFlags=EPlatformFileRead::None, EPlatformFileWrite WriteFlags=EPlatformFileWrite::None)
Copy a file.
virtual bool CreateDirectory (const TCHAR *Directory)=0
Create a directory and return true if the directory was created or already existed.
virtual bool CreateDirectoryTree (const TCHAR *Directory)
Create a directory, including any parent directories and return true if the directory was created or already existed.
virtual bool DeleteDirectory (const TCHAR *Directory)=0
Delete a directory and return true if the directory was deleted or otherwise does not exist.
virtual bool DeleteDirectoryRecursively (const TCHAR *Directory)
Delete all files and subdirectories in a directory, then delete the directory itself.
virtual bool DeleteFile (const TCHAR *Filename)=0
Delete a file and return true if the file exists.
virtual bool DeleteFiles (const TArrayView< const TCHAR * > &Filenames)
Delete an array of files and return true if ALL deletes are succeeded.
virtual bool DirectoryExists (const TCHAR *Directory)=0
Return true if the directory exists.
virtual bool DoesCreatePublicFiles ()
Checks to see if this file system creates publicly accessible files.
virtual bool FileExists (const TCHAR *Filename)=0
Return true if the file exists.
virtual FFileJournalData FileJournalGetFileData (const TCHAR *FilenameOrDirectory, FString *OutError=nullptr)
Return the data for the given path as with GetStatData, but report a FFileJournalData instead, which notably includes the FFileJournalFileHandle for the file/directory.
virtual EFileJournalResult FileJournalGetLatestEntry (const TCHAR *VolumeName, FFileJournalId &OutJournalId, FFileJournalEntryHandle &OutEntryHandle, FString *OutError=nullptr)
Report the current end of the journal for the given volume, to be used as the StartingJournalEntry in FileJournalGetModifiedDirectories.
virtual uint64 FileJournalGetMaximumSize (const TCHAR *VolumeOrPath=nullptr, ELogVerbosity::Type *OutErrorLevel=nullptr, FString *OutError=nullptr) const
Return the maximum size of the FileJournal for the specified VolumeName, if available, zero otherwise.
virtual FString FileJournalGetVolumeName (FStringView InPath)
Return the VolumeSpecifier present in the given path.
virtual bool FileJournalIsAvailable (const TCHAR *VolumeOrPath=nullptr, ELogVerbosity::Type *OutErrorLevel=nullptr, FString *OutError=nullptr)
Return whether FileJournal functionality is available on the current platform if VolumeName is nullptr or for the given Volume if VolumeName is non-null.
virtual bool FileJournalIterateDirectory (const TCHAR *Directory, FDirectoryJournalVisitorFunc Visitor, FString *OutError=nullptr)
Iterate the given directory as with IterateDirectoryStat, but report a FFileJournalData for each file and directory, which notably includes the FFileJournalFileHandle for the file/directory.
virtual EFileJournalResult FileJournalReadModified (const TCHAR *VolumeName, const FFileJournalId &JournalIdOfStartingEntry, const FFileJournalEntryHandle &StartingJournalEntry, TMap< FFileJournalFileHandle, FString > &KnownDirectories, TSet< FString > &OutModifiedDirectories, FFileJournalEntryHandle &OutNextJournalEntry, FString *OutError=nullptr)
Query the FileJournal to find a list of all directories on the given volume with files that have been added, deleted, or modified in the specified time range.
virtual int64 FileSize (const TCHAR *Filename)=0
Return the size of the file, or -1 if it doesn't exist.
virtual void FindFiles (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension)
Finds all the files within the given directory, with optional file extension filter.
virtual void FindFilesRecursively (TArray< FString > &FoundFiles, const TCHAR *Directory, const TCHAR *FileExtension)
Finds all the files within the directory tree, with optional file extension filter.
virtual FDateTime GetAccessTimeStamp (const TCHAR *Filename)=0
Return the last access time of a file.
virtual int64 GetAllowedBytesToWriteThrottledStorage (const TCHAR *DestinationPath=nullptr)
Returns the number of bytes that are currently allowed to be written to throttled write storage (if the platform has such restrictions)
virtual FString GetFilenameOnDisk (const TCHAR *Filename)=0
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
virtual IPlatformFile * GetLowerLevel ()=0
Gets the platform file wrapped by this file.
virtual const TCHAR * GetName () const =0
Gets this platform file type name.
virtual FFileStatData GetStatData (const TCHAR *FilenameOrDirectory)=0
Return the stat data for the given file or directory.
virtual FDateTime GetTimeStamp (const TCHAR *Filename)=0
Return the modification time of a file.
virtual FDateTime GetTimeStampLocal (const TCHAR *Filename)
Return the modification time of a file in the local time of the calling code (GetTimeStamp returns UTC).
virtual void GetTimeStampPair (const TCHAR *PathA, const TCHAR *PathB, FDateTime &OutTimeStampA, FDateTime &OutTimeStampB)
virtual bool HasMarkOfTheWeb (FStringView Filename, FString *OutSourceURL=nullptr)
Determine if the file has been downloaded from a web browser, based on platform-specific metadata.
virtual bool Initialize (IPlatformFile *Inner, const TCHAR *CmdLine)=0
Initializes platform file.
virtual void InitializeAfterProjectFilePath ()
Performs initialization of the platform file after the project path has been set.
virtual void InitializeAfterSetActive ()
Performs initialization of the platform file after it has become the active (FPlatformFileManager.GetPlatformFile() will return this.
virtual void InitializeNewAsyncIO ()
Performs initialization of the platform file after the new async IO has been enabled.
virtual bool IsReadOnly (const TCHAR *Filename)=0
Return true if the file is read only.
virtual bool IsSandboxEnabled () const
Returns whether the sandbox is enabled or not.
virtual ESymlinkResult IsSymlink (const TCHAR *Filename)
Return true if the file is a symbolic link.
virtual bool IterateDirectory (const TCHAR *Directory, FDirectoryVisitor &Visitor)=0
Call the Visit function of the visitor once for each file or directory in a single directory.
virtual bool IterateDirectory (const TCHAR *Directory, FDirectoryVisitorFunc Visitor)
Call the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryRecursively (const TCHAR *Directory, FDirectoryVisitor &Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryRecursively (const TCHAR *Directory, FDirectoryVisitorFunc Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryStat (const TCHAR *Directory, FDirectoryStatVisitor &Visitor)=0
Call the Visit function of the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryStat (const TCHAR *Directory, FDirectoryStatVisitorFunc Visitor)
Call the visitor once for each file or directory in a single directory.
virtual bool IterateDirectoryStatRecursively (const TCHAR *Directory, FDirectoryStatVisitor &Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual bool IterateDirectoryStatRecursively (const TCHAR *Directory, FDirectoryStatVisitorFunc Visitor)
Call the Visit function of the visitor once for each file or directory in a directory tree.
virtual void MakeUniquePakFilesForTheseFiles (const TArray< TArray< FString > > &InFiles)
Build an in memory unique pak file from a subset of files in this pak file.
virtual bool MoveFile (const TCHAR *To, const TCHAR *From)=0
Attempt to move a file.
virtual IAsyncReadFileHandle * OpenAsyncRead (const TCHAR *Filename, bool bAllowWrite=false)
Open a file for async reading.
virtual FFileOpenAsyncResult OpenAsyncRead (const TCHAR *Filename, EOpenReadFlags Flags)
Open a file for async reading.
virtual FOpenMappedResult OpenMappedEx (const TCHAR *Filename, EOpenReadFlags OpenOptions=EOpenReadFlags::None, int64 MaximumSize=0)
Open a file for async reading.
virtual IFileHandle * OpenRead (const TCHAR *Filename, bool bAllowWrite=false)=0
Attempt to open a file for reading.
virtual FFileOpenResult OpenRead (const TCHAR *Filename, EOpenReadFlags Flags)
Open a file handle for reading.
virtual IFileHandle * OpenReadNoBuffering (const TCHAR *Filename, bool bAllowWrite=false)
virtual IFileHandle * OpenWrite (const TCHAR *Filename, bool bAppend=false, bool bAllowRead=false)=0
Attempt to open a file for writing.
virtual bool SendMessageToServer (const TCHAR *Message, IFileServerMessageHandler *Handler)
Sends a message to the file server, and will block until it's complete.
virtual void SetAsyncMinimumPriority (EAsyncIOPriorityAndFlags MinPriority)
Controls if the pak precacher should process precache requests.
virtual void SetCreatePublicFiles (bool bCreatePublicFiles)
Sets file system to create publicly accessible files or not.
virtual void SetLowerLevel (IPlatformFile *NewLowerLevel)=0
Sets the platform file wrapped by this file.
virtual bool SetMarkOfTheWeb (FStringView Filename, bool bNewStatus, const FString *InSourceURL=nullptr)
Attempt to change the platform-specific metadata that indicates if the file has been downloaded from a web browser.
virtual bool SetReadOnly (const TCHAR *Filename, bool bNewReadOnlyValue)=0
Attempt to change the read only status of a file.
virtual void SetSandboxEnabled (bool bInEnabled)
Set whether the sandbox is enabled or not.
virtual void SetTimeStamp (const TCHAR *Filename, FDateTime DateTime)=0
Sets the modification time of a file.
virtual bool ShouldBeUsed (IPlatformFile *Inner, const TCHAR *CmdLine) const
Checks if this platform file should be used even though it was not asked to be.
virtual void Tick ()
Platform file can override this to get a regular tick from the engine.
UE_DEPRECATED (5.6, "Please use OpenMappedEx instead") 1 virtual IMappedFileHandle *OpenMapped(const TCHAR *Filename)
Open a file for async reading.
Static Public Member Functions
static const TCHAR * GetPhysicalTypeName ()
Returns the name of the physical platform file type.
static IPlatformFile & GetPlatformPhysical ()
Physical file system of the platform, never wrapped.
Detailed Description
File I/O Interface.
Definition at line 337 of file GenericPlatformFile.h.
Member Typedef Documentation
FDirectoryJournalVisitorFunc
typedef TFunctionRef<bool(const TCHAR*, const FFileJournalData&)> IPlatformFile::FDirectoryJournalVisitorFunc
File and directory visitor function that takes FileJournal data.
Definition at line 663 of file GenericPlatformFile.h.
FDirectoryStatVisitorFunc
typedef TFunctionRef<bool(const TCHAR*, const FFileStatData&)> IPlatformFile::FDirectoryStatVisitorFunc
File and directory visitor function that takes all the stat data.
Definition at line 618 of file GenericPlatformFile.h.
FDirectoryVisitorFunc
typedef TFunctionRef<bool(const TCHAR*, bool)> IPlatformFile::FDirectoryVisitorFunc
File and directory visitor function that takes only the name.
Definition at line 584 of file GenericPlatformFile.h.
Member Enumeration Documentation
EOpenReadFlags
enum class IPlatformFile::EOpenReadFlags : uint8 strong
Flags to be used when opening a file for reading via IPlatformFile::OpenRead.
Enumerator
None
AllowWrite
Allow other handles/processes to write to this file.
This flag is needed to open files that are currently being written to as well
AllowDelete
Allow the file to be deleted or renamed while keeping this handle valid for reading.
Definition at line 491 of file GenericPlatformFile.h.
Constructor & Destructor Documentation
IPlatformFile()
IPlatformFile::IPlatformFile ()
Constructor/Destructor.
Referenced by FCachedReadPlatformFile::GetLowerLevel(), FLoggedPlatformFile::GetLowerLevel(), FPlatformFileOpenLog::GetLowerLevel(), IPhysicalPlatformFile::GetLowerLevel(), GetLowerLevel(), GetPlatformPhysical(), FCachedReadPlatformFile::Initialize(), FLoggedPlatformFile::Initialize(), FPlatformFileOpenLog::Initialize(), IPhysicalPlatformFile::Initialize(), Initialize(), FCachedReadPlatformFile::SetLowerLevel(), FLoggedPlatformFile::SetLowerLevel(), FPlatformFileOpenLog::SetLowerLevel(), IPhysicalPlatformFile::SetLowerLevel(), SetLowerLevel(), FCachedReadPlatformFile::ShouldBeUsed(), FLoggedPlatformFile::ShouldBeUsed(), FPlatformFileOpenLog::ShouldBeUsed(), IPhysicalPlatformFile::ShouldBeUsed(), and ShouldBeUsed().
~IPlatformFile()
virtual IPlatformFile::~IPlatformFile () virtual
Member Function Documentation
AddLocalDirectories()
virtual void IPlatformFile::AddLocalDirectories (TArray< FString > & LocalDirectories) inline virtual
Identifies any platform specific paths that are guaranteed to be local (i.e.
cache, scratch space)
Definition at line 407 of file GenericPlatformFile.h.
References AddLocalDirectories(), and GetLowerLevel().
Referenced by AddLocalDirectories().
BypassSecurity()
virtual void IPlatformFile::BypassSecurity (bool bInBypass) inline virtual
Definition at line 415 of file GenericPlatformFile.h.
References BypassSecurity(), and GetLowerLevel().
Referenced by BypassSecurity().
ConvertToAbsolutePathForExternalAppForRead()
virtual FString IPlatformFile::ConvertToAbsolutePathForExternalAppForRead (const TCHAR * Filename) virtual
Converts passed in filename to use an absolute path (for reading).
Parameters
Filename filename to convert to use an absolute path, safe to pass in already using absolute path
Returns
filename using absolute path
Reimplemented in FCachedReadPlatformFile, FIOSPlatformFile, FPlatformFileOpenLog, and IAndroidPlatformFile.
References ConvertToAbsolutePathForExternalAppForRead(), and Filename.
Referenced by ConvertToAbsolutePathForExternalAppForRead().
ConvertToAbsolutePathForExternalAppForWrite()
virtual FString IPlatformFile::ConvertToAbsolutePathForExternalAppForWrite (const TCHAR * Filename) virtual
Converts passed in filename to use an absolute path (for writing)
Parameters
Filename filename to convert to use an absolute path, safe to pass in already using absolute path
Returns
filename using absolute path
Reimplemented in FCachedReadPlatformFile, FIOSPlatformFile, FPlatformFileOpenLog, and IAndroidPlatformFile.
References ConvertToAbsolutePathForExternalAppForWrite(), and Filename.
Referenced by ConvertToAbsolutePathForExternalAppForWrite().
CopyDirectoryTree()
virtual bool IPlatformFile::CopyDirectoryTree (const TCHAR * DestinationDirectory, const TCHAR * Source, bool bOverwriteAllExisting) virtual
Copy a file or a hierarchy of files (directory).
Parameters
DestinationDirectory Target path (either absolute or relative) to copy to - always a directory! (e.g. "/home/dest/").
Source Source file (or directory) to copy (e.g. "/home/source/stuff").
bOverwriteAllExisting Whether to overwrite everything that exists at target
Returns
true if operation completed successfully.
Reimplemented in FCachedReadPlatformFile, and FPlatformFileOpenLog.
References CopyDirectoryTree(), and Source.
Referenced by TManagedStoragePlatformFile< BaseClass >::TManagedStoragePlatformFile(), and CopyDirectoryTree().
CopyFile()
virtual bool IPlatformFile::CopyFile (const TCHAR * To, const TCHAR * From, EPlatformFileRead ReadFlags = EPlatformFileRead::None, EPlatformFileWrite WriteFlags = EPlatformFileWrite::None) virtual
Copy a file.
This will fail if the destination file already exists.
Parameters
To File to copy to.
From File to copy from.
ReadFlags Source file read options.
WriteFlags Destination file write options.
Returns
true if the file was copied successfully.
Reimplemented in FApplePlatformFile, FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References CopyFile(), and None.
Referenced by CopyFile().
CreateDirectory()
virtual bool IPlatformFile::CreateDirectory (const TCHAR * Directory) pure virtual
Create a directory and return true if the directory was created or already existed.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
CreateDirectoryTree()
virtual bool IPlatformFile::CreateDirectoryTree (const TCHAR * Directory) virtual
Create a directory, including any parent directories and return true if the directory was created or already existed.
Reimplemented in FCachedReadPlatformFile, and FPlatformFileOpenLog.
References CreateDirectoryTree().
Referenced by CreateDirectoryTree().
DeleteDirectory()
virtual bool IPlatformFile::DeleteDirectory (const TCHAR * Directory) pure virtual
Delete a directory and return true if the directory was deleted or otherwise does not exist.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
DeleteDirectoryRecursively()
virtual bool IPlatformFile::DeleteDirectoryRecursively (const TCHAR * Directory) virtual
Delete all files and subdirectories in a directory, then delete the directory itself.
Parameters
Directory The directory to delete.
Returns
true if the directory was deleted or did not exist.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, and FPlatformFileOpenLog.
References DeleteDirectoryRecursively().
Referenced by TManagedStoragePlatformFile< BaseClass >::TManagedStoragePlatformFile(), and DeleteDirectoryRecursively().
DeleteFile()
virtual bool IPlatformFile::DeleteFile (const TCHAR * Filename) pure virtual
Delete a file and return true if the file exists.
Will not delete read only files.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
Referenced by DeleteFiles().
DeleteFiles()
virtual bool IPlatformFile::DeleteFiles (const TArrayView< const TCHAR * > & Filenames) inline virtual
Delete an array of files and return true if ALL deletes are succeeded.
Definition at line 438 of file GenericPlatformFile.h.
References DeleteFile().
DirectoryExists()
virtual bool IPlatformFile::DirectoryExists (const TCHAR * Directory) pure virtual
Return true if the directory exists.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, FUnixPlatformFile, and IAndroidPlatformFile.
Referenced by IAndroidPlatformFile::IterateDirectoryStat().
DoesCreatePublicFiles()
virtual bool IPlatformFile::DoesCreatePublicFiles () inline virtual
Checks to see if this file system creates publicly accessible files.
Returns
true if this file system creates publicly accessible files
Reimplemented in FIOSPlatformFile.
Definition at line 920 of file GenericPlatformFile.h.
FileExists()
virtual bool IPlatformFile::FileExists (const TCHAR * Filename) pure virtual
Return true if the file exists.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, FUnixPlatformFile, and IAndroidPlatformFile.
References Filename.
Referenced by IAndroidPlatformFile::IterateDirectoryStat().
FileJournalGetFileData()
virtual FFileJournalData IPlatformFile::FileJournalGetFileData (const TCHAR * FilenameOrDirectory, FString * OutError = nullptr) virtual
Return the data for the given path as with GetStatData, but report a FFileJournalData instead, which notably includes the FFileJournalFileHandle for the file/directory.
Check the FFileJournalData::bIsValid member before using the returned data
FileJournalGetLatestEntry()
virtual EFileJournalResult IPlatformFile::FileJournalGetLatestEntry (const TCHAR * VolumeName, FFileJournalId & OutJournalId, FFileJournalEntryHandle & OutEntryHandle, FString * OutError = nullptr) virtual
Report the current end of the journal for the given volume, to be used as the StartingJournalEntry in FileJournalGetModifiedDirectories.
If !FileJournalIsAvaiable for the given volume, sets OutEntryHandle to FileJournalEntryHandleInvalid. Returns EFileJournalResult::Success if successful, otherwise an error code and optionally a user-displayable explanation for the error code.
FileJournalGetMaximumSize()
virtual uint64 IPlatformFile::FileJournalGetMaximumSize (const TCHAR * VolumeOrPath = nullptr, ELogVerbosity::Type * OutErrorLevel = nullptr, FString * OutError = nullptr) const virtual
Return the maximum size of the FileJournal for the specified VolumeName, if available, zero otherwise.
Optionally returns a user-displayable string for why the journal is not available and a severity level for the reason. VolumeName may be a VolumeName as returned by FileJournalGetVolumeName or any path to a file or directory on the Volume.
FileJournalGetVolumeName()
virtual FString IPlatformFile::FileJournalGetVolumeName (FStringView InPath) virtual
Return the VolumeSpecifier present in the given path.
Returns empty string if path does not have a valid volume specifier for use by the FileJournal (e.g. some platforms do not support \paths for FileJournal).
See also
FPathViews::SplitVolumeSpecifier for a more general function that can return specifiers not usable by the FileJournal.
FileJournalIsAvailable()
virtual bool IPlatformFile::FileJournalIsAvailable (const TCHAR * VolumeOrPath = nullptr, ELogVerbosity::Type * OutErrorLevel = nullptr, FString * OutError = nullptr) virtual
Return whether FileJournal functionality is available on the current platform if VolumeName is nullptr or for the given Volume if VolumeName is non-null.
Optionally returns a user-displayable string for why it is not available and a severity level for the reason. VolumeName may be a VolumeName as returned by FileJournalGetVolumeName or any path to a file or directory on the Volume.
FileJournalIterateDirectory()
virtual bool IPlatformFile::FileJournalIterateDirectory (const TCHAR * Directory, FDirectoryJournalVisitorFunc Visitor, FString * OutError = nullptr) virtual
Iterate the given directory as with IterateDirectoryStat, but report a FFileJournalData for each file and directory, which notably includes the FFileJournalFileHandle for the file/directory.
The paths returned as the first argument of the visitor function are the combined paths produced by combining the input directory with the relative path of the child file or directory.
If the FileJournal is unavailable on the current system the iteration will still succeed but the FFileJournalFileHandle for each child path will be set to FileJournalFileHandleInvalid.
If the FileJournal is available on the current system but not on the volume of the given directory, it is arbitrary whether the FFileJournalFileHandle will be validly set; if not valid they will be set to FileJournalFileHandleInvalid.
Returns
false if the directory did not exist or if the visitor returned false.
FileJournalReadModified()
virtual EFileJournalResult IPlatformFile::FileJournalReadModified (const TCHAR * VolumeName, const FFileJournalId & JournalIdOfStartingEntry, const FFileJournalEntryHandle & StartingJournalEntry, TMap< FFileJournalFileHandle, FString > & KnownDirectories, TSet< FString > & OutModifiedDirectories, FFileJournalEntryHandle & OutNextJournalEntry, FString * OutError = nullptr) virtual
Query the FileJournal to find a list of all directories on the given volume with files that have been added, deleted, or modified in the specified time range.
The beginning of the time range is specified by JournalIdOfStartingEntry and StartingJournalEntry, which came from FileJournalGetLatestEntry or a previous call to FileJournalReadModified. The end of the range is the latest modification on the volume. VolumeName can be the return value from FileJournalGetVolumeName, or any path on the desired volume.
The caller must provide the mapping from FFileJournalFileHandle to DirectoryName; the FFileJournalFileHandle for each Directory can be found from FileJournalGetFileData or FileJournalIterateDirectory.
Modified directories are appended into OutModifiedDirectories, and the next FileJournal entry to scan is written into OutNextJournalEntry.
Returns EFileJournalResult::Success if successful, otherwise an error code and optionally a user-displayable explanation for the error code. In an error case, partial results may still be written into the output.
FileSize()
virtual int64 IPlatformFile::FileSize (const TCHAR * Filename) pure virtual
Return the size of the file, or -1 if it doesn't exist.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, FUnixPlatformFile, and IAndroidPlatformFile.
References Filename.
Referenced by IAndroidPlatformFile::IterateDirectoryStat(), and UE::FGenericPlatformIoDispatcher::OpenFile().
FindFiles()
virtual void IPlatformFile::FindFiles (TArray< FString > & FoundFiles, const TCHAR * Directory, const TCHAR * FileExtension) virtual
Finds all the files within the given directory, with optional file extension filter.
Parameters
Directory The directory to iterate the contents of
FileExtension If FileExtension is NULL, or an empty string "" then all files are found. Otherwise FileExtension can be of the form .EXT or just EXT and only files with that extension will be returned.
Returns
FoundFiles All the files that matched the optional FileExtension filter, or all files if none was specified.
Reimplemented in FCachedReadPlatformFile.
References FindFiles().
Referenced by FindFiles().
FindFilesRecursively()
virtual void IPlatformFile::FindFilesRecursively (TArray< FString > & FoundFiles, const TCHAR * Directory, const TCHAR * FileExtension) virtual
Finds all the files within the directory tree, with optional file extension filter.
Parameters
Directory The starting directory to iterate the contents. This function explores subdirectories
FileExtension If FileExtension is NULL, or an empty string "" then all files are found. Otherwise FileExtension can be of the form .EXT or just EXT and only files with that extension will be returned.
Returns
FoundFiles All the files that matched the optional FileExtension filter, or all files if none was specified.
Reimplemented in FCachedReadPlatformFile.
References FindFilesRecursively().
Referenced by FindFilesRecursively().
GetAccessTimeStamp()
virtual FDateTime IPlatformFile::GetAccessTimeStamp (const TCHAR * Filename) pure virtual
Return the last access time of a file.
Returns FDateTime::MinValue() on failure
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
GetAllowedBytesToWriteThrottledStorage()
virtual int64 IPlatformFile::GetAllowedBytesToWriteThrottledStorage (const TCHAR * DestinationPath = nullptr) inline virtual
Returns the number of bytes that are currently allowed to be written to throttled write storage (if the platform has such restrictions)
Parameters
DestinationPath If specified, the file system can optionally take into account the destination of the file to determine the current limit
Returns
The number of bytes that are allowed to be written to write throttled storage.
If there is no limit, INT64_MAX is returned
Definition at line 944 of file GenericPlatformFile.h.
GetFilenameOnDisk()
virtual FString IPlatformFile::GetFilenameOnDisk (const TCHAR * Filename) pure virtual
For case insensitive filesystems, returns the full path of the file with the same case as in the filesystem.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
GetLowerLevel()
virtual IPlatformFile * IPlatformFile::GetLowerLevel () pure virtual
Gets the platform file wrapped by this file.
Implemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IPhysicalPlatformFile.
References IPlatformFile().
Referenced by AddLocalDirectories(), and BypassSecurity().
GetName()
virtual const TCHAR * IPlatformFile::GetName () const pure virtual
Gets this platform file type name.
Implemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IPhysicalPlatformFile.
GetPhysicalTypeName()
const TCHAR * IPlatformFile::GetPhysicalTypeName () static
Returns the name of the physical platform file type.
Referenced by IPhysicalPlatformFile::GetName().
GetPlatformPhysical()
IPlatformFile & IPlatformFile::GetPlatformPhysical () static
Physical file system of the platform, never wrapped.
References IPlatformFile().
Referenced by FPersistentStorageManager::Initialize(), and UE::FGenericPlatformIoDispatcher::OpenFile().
GetStatData()
virtual FFileStatData IPlatformFile::GetStatData (const TCHAR * FilenameOrDirectory) pure virtual
Return the stat data for the given file or directory.
Check the FFileStatData::bIsValid member before using the returned data
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, FUnixPlatformFile, and IAndroidPlatformFile.
Referenced by FPersistentStorageManager::Initialize(), and IAndroidPlatformFile::IterateDirectoryStat().
GetTimeStamp()
virtual FDateTime IPlatformFile::GetTimeStamp (const TCHAR * Filename) pure virtual
Return the modification time of a file.
Returns FDateTime::MinValue() on failure
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
GetTimeStampLocal()
virtual FDateTime IPlatformFile::GetTimeStampLocal (const TCHAR * Filename) virtual
Return the modification time of a file in the local time of the calling code (GetTimeStamp returns UTC).
Returns FDateTime::MinValue() on failure
References Filename, and GetTimeStampLocal().
Referenced by GetTimeStampLocal().
GetTimeStampPair()
virtual void IPlatformFile::GetTimeStampPair (const TCHAR * PathA, const TCHAR * PathB, FDateTime & OutTimeStampA, FDateTime & OutTimeStampB) virtual
References GetTimeStampPair().
Referenced by GetTimeStampPair().
HasMarkOfTheWeb()
virtual bool IPlatformFile::HasMarkOfTheWeb (FStringView Filename, FString * OutSourceURL = nullptr) inline virtual
Determine if the file has been downloaded from a web browser, based on platform-specific metadata.
Parameters
Filename The file to check if it has a mark of the web.
OutSourceURL An optional pointer to return a source url if available.
Returns
true if the file has a mark of the web, false otherwise.
Remarks
Only works for files on disk and currently only implemented for Windows.
Definition at line 476 of file GenericPlatformFile.h.
References Filename.
Initialize()
virtual bool IPlatformFile::Initialize (IPlatformFile * Inner, const TCHAR * CmdLine) pure virtual
Initializes platform file.
Parameters
Inner Platform file to wrap by this file.
CmdLine Command line to parse.
Returns
true if the initialization was successful, false otherise.
Implemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IPhysicalPlatformFile.
References IPlatformFile().
InitializeAfterProjectFilePath()
virtual void IPlatformFile::InitializeAfterProjectFilePath () inline virtual
Performs initialization of the platform file after the project path has been set.
Definition at line 392 of file GenericPlatformFile.h.
InitializeAfterSetActive()
virtual void IPlatformFile::InitializeAfterSetActive () inline virtual
Performs initialization of the platform file after it has become the active (FPlatformFileManager.GetPlatformFile() will return this.
Definition at line 387 of file GenericPlatformFile.h.
InitializeNewAsyncIO()
virtual void IPlatformFile::InitializeNewAsyncIO () inline virtual
Performs initialization of the platform file after the new async IO has been enabled.
Definition at line 402 of file GenericPlatformFile.h.
IsReadOnly()
virtual bool IPlatformFile::IsReadOnly (const TCHAR * Filename) pure virtual
Return true if the file is read only.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
IsSandboxEnabled()
virtual bool IPlatformFile::IsSandboxEnabled () const inline virtual
Returns whether the sandbox is enabled or not.
Returns
bool true if enabled, false if not
Definition at line 362 of file GenericPlatformFile.h.
Referenced by FFileManagerGeneric::IsSandboxEnabled().
IsSymlink()
virtual ESymlinkResult IPlatformFile::IsSymlink (const TCHAR * Filename) inline virtual
Return true if the file is a symbolic link.
Reimplemented in FApplePlatformFile, and FUnixPlatformFile.
Definition at line 465 of file GenericPlatformFile.h.
References Filename, and Unimplemented.
IterateDirectory() [1/2]
virtual bool IPlatformFile::IterateDirectory (const TCHAR * Directory, FDirectoryVisitor & Visitor) pure virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, FUnixPlatformFile, and IAndroidPlatformFile.
Referenced by IterateDirectory(), IAndroidPlatformFile::IterateDirectoryStat(), FApplePlatformFile::NormalizeDirectory(), and FUnixPlatformFile::NormalizeDirectory().
IterateDirectory() [2/2]
virtual bool IPlatformFile::IterateDirectory (const TCHAR * Directory, FDirectoryVisitorFunc Visitor) virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IAndroidPlatformFile.
References IterateDirectory().
IterateDirectoryRecursively() [1/2]
virtual bool IPlatformFile::IterateDirectoryRecursively (const TCHAR * Directory, FDirectoryVisitor & Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories.
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, and FPlatformFileOpenLog.
References IterateDirectoryRecursively().
Referenced by FPersistentStorageManager::Initialize(), IterateDirectoryRecursively(), and IterateDirectoryRecursively().
IterateDirectoryRecursively() [2/2]
virtual bool IPlatformFile::IterateDirectoryRecursively (const TCHAR * Directory, FDirectoryVisitorFunc Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories (see FDirectoryVisitor::Visit for the signature).
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, and FPlatformFileOpenLog.
References IterateDirectoryRecursively().
IterateDirectoryStat() [1/2]
virtual bool IPlatformFile::IterateDirectoryStat (const TCHAR * Directory, FDirectoryStatVisitor & Visitor) pure virtual
Call the Visit function of the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory
Returns
false if the directory did not exist or if the visitor returned false.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, FUnixPlatformFile, and IAndroidPlatformFile.
Referenced by IAndroidPlatformFile::IterateDirectoryStat(), IterateDirectoryStat(), FApplePlatformFile::NormalizeDirectory(), and FUnixPlatformFile::NormalizeDirectory().
IterateDirectoryStat() [2/2]
virtual bool IPlatformFile::IterateDirectoryStat (const TCHAR * Directory, FDirectoryStatVisitorFunc Visitor) virtual
Call the visitor once for each file or directory in a single directory.
This function does not explore subdirectories.
Parameters
Directory The directory to iterate the contents of.
Visitor Visitor to call for each element of the directory (see FDirectoryStatVisitor::Visit for the signature)
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IAndroidPlatformFile.
References IterateDirectoryStat().
IterateDirectoryStatRecursively() [1/2]
virtual bool IPlatformFile::IterateDirectoryStatRecursively (const TCHAR * Directory, FDirectoryStatVisitor & Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories.
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, and FPlatformFileOpenLog.
References IterateDirectoryStatRecursively().
Referenced by IterateDirectoryStatRecursively(), and IterateDirectoryStatRecursively().
IterateDirectoryStatRecursively() [2/2]
virtual bool IPlatformFile::IterateDirectoryStatRecursively (const TCHAR * Directory, FDirectoryStatVisitorFunc Visitor) virtual
Call the Visit function of the visitor once for each file or directory in a directory tree.
This function explores subdirectories.
Parameters
Directory The directory to iterate the contents of, recursively.
Visitor Visitor to call for each element of the directory and each element of all subdirectories (see FDirectoryStatVisitor::Visit for the signature).
Returns
false if the directory did not exist or if the visitor returned false.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, and FPlatformFileOpenLog.
References IterateDirectoryStatRecursively().
MakeUniquePakFilesForTheseFiles()
virtual void IPlatformFile::MakeUniquePakFilesForTheseFiles (const TArray< TArray< FString > > & InFiles) inline virtual
Build an in memory unique pak file from a subset of files in this pak file.
Definition at line 397 of file GenericPlatformFile.h.
MoveFile()
virtual bool IPlatformFile::MoveFile (const TCHAR * To, const TCHAR * From) pure virtual
Attempt to move a file.
Return true if successful. Will not overwrite existing files.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
OpenAsyncRead() [1/2]
virtual IAsyncReadFileHandle * IPlatformFile::OpenAsyncRead (const TCHAR * Filename, bool bAllowWrite = false) virtual
Open a file for async reading.
This call does not hit the disk or block.
Parameters
Filename file to be opened
bAllowWrite (applies to certain platforms only) whether this file is allowed to be written to by other processes. This flag is needed to open files that are currently being written to as well.
Returns
Close the file by delete'ing the handle. A non-null return value does not mean the file exists, since that may not be determined yet.
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, and FPlatformFileOpenLog.
References Filename.
OpenAsyncRead() [2/2]
virtual FFileOpenAsyncResult IPlatformFile::OpenAsyncRead (const TCHAR * Filename, EOpenReadFlags Flags) virtual
Open a file for async reading.
This call does not hit the disk or block.
Parameters
Flags Allows specialization of the open operation,
See also
EReadFlags
Returns
The return value will either contain the valid file handle or an error message.
See also
FFileOpenAsyncResult
References Filename, and Flags.
OpenMappedEx()
virtual FOpenMappedResult IPlatformFile::OpenMappedEx (const TCHAR * Filename, EOpenReadFlags OpenOptions = EOpenReadFlags::None, int64 MaximumSize = 0) virtual
Open a file for async reading.
This call does hit the disk; it is synchronous open.
Parameters
Filename File to be mapped. This doesn't actually map anything, just opens the file.
OpenOptions Allows specifying map to be writable via AllowWrite or be ReadOnly by deafault.
Returns
Close the file by deleting the handle. A non-null return value does mean the file exists. Null can be returned for many reasons even if the file exists. Perhaps this platform does not support mapped files, or this file is compressed in a pak file. Generally you attempt to open mapped, and if that fails, then use other file operations instead.
Reimplemented in FApplePlatformFile, FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename, None, and OpenMappedEx().
Referenced by OpenMappedEx().
OpenRead() [1/2]
virtual IFileHandle * IPlatformFile::OpenRead (const TCHAR * Filename, bool bAllowWrite = false) pure virtual
Attempt to open a file for reading.
Please consider using the new overload that takes EReadFlags instead of bools as parameters.
Parameters
Filename file to be opened
bAllowWrite (applies to certain platforms only) whether this file is allowed to be written to by other processes. This flag is needed to open files that are currently being written to as well.
Returns
If successful will return a non-nullptr pointer. Close the file by deleting the handle.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
OpenRead() [2/2]
virtual FFileOpenResult IPlatformFile::OpenRead (const TCHAR * Filename, EOpenReadFlags Flags) virtual
Open a file handle for reading.
Parameters
Filename The file to be opened
Flags Allows specialization of the open operation,
See also
EReadFlags
Returns
The return value will either contain the valid file handle or an error message.
See also
FFileOpenResult
References Filename, and Flags.
Referenced by OpenReadNoBuffering().
OpenReadNoBuffering()
virtual IFileHandle * IPlatformFile::OpenReadNoBuffering (const TCHAR * Filename, bool bAllowWrite = false) inline virtual
Definition at line 521 of file GenericPlatformFile.h.
References Filename, and OpenRead().
Referenced by UE::FGenericPlatformIoDispatcher::OpenFile().
OpenWrite()
virtual IFileHandle * IPlatformFile::OpenWrite (const TCHAR * Filename, bool bAppend = false, bool bAllowRead = false) pure virtual
Attempt to open a file for writing.
If successful will return a non-nullptr pointer. Close the file by deleting the handle.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
SendMessageToServer()
virtual bool IPlatformFile::SendMessageToServer (const TCHAR * Message, IFileServerMessageHandler * Handler) inline virtual
Sends a message to the file server, and will block until it's complete.
Will return immediately if the file manager doesn't support talking to a server.
Parameters
Message The string message to send to the server
Returns
true if the message was sent to server and it returned success, or false if there is no server, or the command failed
Reimplemented in FCachedReadPlatformFile, and FPlatformFileOpenLog.
Definition at line 909 of file GenericPlatformFile.h.
Referenced by FFileManagerGeneric::SendMessageToServer().
SetAsyncMinimumPriority()
virtual void IPlatformFile::SetAsyncMinimumPriority (EAsyncIOPriorityAndFlags MinPriority) inline virtual
Controls if the pak precacher should process precache requests.
Requests below this threshold will not get precached. Without this throttle, quite a lot of memory can be consumed if the disk races ahead of the CPU.
Parameters
MinPriority the minimum priority at which requests will get precached
Reimplemented in FCachedReadPlatformFile, and FLoggedPlatformFile.
Definition at line 744 of file GenericPlatformFile.h.
SetCreatePublicFiles()
virtual void IPlatformFile::SetCreatePublicFiles (bool bCreatePublicFiles) inline virtual
Sets file system to create publicly accessible files or not.
Parameters
bCreatePublicFiles true to set the file system to create publicly accessible files
Reimplemented in FIOSPlatformFile.
Definition at line 930 of file GenericPlatformFile.h.
SetLowerLevel()
virtual void IPlatformFile::SetLowerLevel (IPlatformFile * NewLowerLevel) pure virtual
Sets the platform file wrapped by this file.
Implemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IPhysicalPlatformFile.
References IPlatformFile().
SetMarkOfTheWeb()
virtual bool IPlatformFile::SetMarkOfTheWeb (FStringView Filename, bool bNewStatus, const FString * InSourceURL = nullptr) inline virtual
Attempt to change the platform-specific metadata that indicates if the file has been downloaded from a web browser.
Parameters
Filename The file to change it's mark of the web status.
bNewStatus New mark of the web status for the file.
InSourceURL An optional pointer to a source url that will be applied if new status true.
Returns
true if the file's mark of the web status was successful changed, false otherwise.
Remarks
Only works for files on disk and currently only implemented for Windows.
Definition at line 488 of file GenericPlatformFile.h.
References Filename.
SetReadOnly()
virtual bool IPlatformFile::SetReadOnly (const TCHAR * Filename, bool bNewReadOnlyValue) pure virtual
Attempt to change the read only status of a file.
Return true if successful.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References Filename.
SetSandboxEnabled()
virtual void IPlatformFile::SetSandboxEnabled (bool bInEnabled) inline virtual
Set whether the sandbox is enabled or not.
Parameters
bInEnabled true to enable the sandbox, false to disable it
Definition at line 353 of file GenericPlatformFile.h.
Referenced by FFileManagerGeneric::SetSandboxEnabled().
SetTimeStamp()
virtual void IPlatformFile::SetTimeStamp (const TCHAR * Filename, FDateTime DateTime) pure virtual
Sets the modification time of a file.
Implemented in FApplePlatformFile, FCachedReadPlatformFile, FIOSPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and FUnixPlatformFile.
References DateTime, and Filename.
ShouldBeUsed()
virtual bool IPlatformFile::ShouldBeUsed (IPlatformFile * Inner, const TCHAR * CmdLine) const inline virtual
Checks if this platform file should be used even though it was not asked to be.
i.e. pak files exist on disk so we should use a pak file
Reimplemented in FCachedReadPlatformFile, FLoggedPlatformFile, FPlatformFileOpenLog, and IPhysicalPlatformFile.
Definition at line 371 of file GenericPlatformFile.h.
References IPlatformFile().
Tick()
virtual void IPlatformFile::Tick () inline virtual
Platform file can override this to get a regular tick from the engine.
Definition at line 424 of file GenericPlatformFile.h.
UE_DEPRECATED()
IPlatformFile::UE_DEPRECATED (5. 6, "Please use OpenMappedEx instead") const
Open a file for async reading.
This call does hit the disk; it is synchronous open.
Parameters
Filename File to be mapped. This doesn't actually map anything, just opens the file.
Returns
Close the file by deleting the handle. A non-null return value does mean the file exists. Null can be returned for many reasons even if the file exists. Perhaps this platform does not support mapped files, or this file is compressed in a pak file. Generally you attempt to open mapped, and if that fails, then use other file operations instead.
References Filename.
The documentation for this class was generated from the following file:
GenericPlatformFile.h