Unreal Engine 5.6 C++ API: UE::MovieScene::TReadOneOfAccessor< T > Struct Template Reference
UE::MovieScene::TReadOneOfAccessor< T > Struct Template Reference
#include "MovieSceneComponentAccessors.h"
Public Types
using AccessType = TMultiComponentLock<TReadOptional<T>...>
Public Member Functions
TReadOneOfAccessor (TComponentTypeID< T >... InComponentTypeIDs)
TMultiComponentLock< TReadOptional< T >... > LockComponentData (const FEntityAllocation *Allocation, FEntityAllocationWriteContext WriteContext) const
void PreLockComponentData (FEntityAllocationIteratorItem Item, FPreLockedDataPtr *PrelockedComponentData) const
TMultiComponentData< TReadOptional< T >... > ResolvePreLockedComponentData (const FEntityAllocation *Allocation, const FPreLockedDataPtr *PrelockedComponentData, FEntityAllocationWriteContext WriteContext) const
Data Fields
FOptionalReadAccess ComponentTypes [sizeof...(T)]
Static Public Attributes
static constexpr int32 PreLockedDataNum = sizeof...(T)
Detailed Description
template<typename... T>
struct UE::MovieScene::TReadOneOfAccessor< T >
Definition at line 347 of file MovieSceneComponentAccessors.h.
Member Typedef Documentation
AccessType
template<typename... T> using UE::MovieScene::TReadOneOfAccessor< T >::AccessType = TMultiComponentLock<TReadOptional<T>...>
Definition at line 349 of file MovieSceneComponentAccessors.h.
Constructor & Destructor Documentation
TReadOneOfAccessor()
template<typename... T> UE::MovieScene::TReadOneOfAccessor< T >::TReadOneOfAccessor (TComponentTypeID< T >... InComponentTypeIDs) inline
Definition at line 352 of file MovieSceneComponentAccessors.h.
References ComponentTypes.
Member Function Documentation
LockComponentData()
template<typename... T> TMultiComponentLock< TReadOptional< T >... > UE::MovieScene::TReadOneOfAccessor< T >::LockComponentData (const FEntityAllocation * Allocation, FEntityAllocationWriteContext WriteContext) const inline
Definition at line 370 of file MovieSceneComponentAccessors.h.
References ComponentTypes, and LockComponentData().
Referenced by LockComponentData().
PreLockComponentData()
template<typename... T> void UE::MovieScene::TReadOneOfAccessor< T >::PreLockComponentData (FEntityAllocationIteratorItem Item, FPreLockedDataPtr * PrelockedComponentData) const inline
Definition at line 356 of file MovieSceneComponentAccessors.h.
References ComponentTypes, and Item.
ResolvePreLockedComponentData()
template<typename... T> TMultiComponentData< TReadOptional< T >... > UE::MovieScene::TReadOneOfAccessor< T >::ResolvePreLockedComponentData (const FEntityAllocation * Allocation, const FPreLockedDataPtr * PrelockedComponentData, FEntityAllocationWriteContext WriteContext) const inline
Definition at line 364 of file MovieSceneComponentAccessors.h.
References ComponentTypes, and ResolvePreLockedComponentData().
Referenced by ResolvePreLockedComponentData().
Field Documentation
ComponentTypes
template<typename... T> FOptionalReadAccess UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes[sizeof...(T)]
Definition at line 376 of file MovieSceneComponentAccessors.h.
Referenced by TReadOneOfAccessor(), UE::MovieScene::AddAccessorToFilter(), UE::MovieScene::HasAccessorWork(), UE::MovieScene::HasBeenWrittenToSince(), UE::MovieScene::IsAccessorValid(), LockComponentData(), UE::MovieScene::PopulatePrerequisites(), UE::MovieScene::PopulateReadWriteDependencies(), PreLockComponentData(), and ResolvePreLockedComponentData().
PreLockedDataNum
template<typename... T> int32 UE::MovieScene::TReadOneOfAccessor< T >::PreLockedDataNum = sizeof...(T) static constexpr
Definition at line 350 of file MovieSceneComponentAccessors.h.
The documentation for this struct was generated from the following file:
MovieSceneComponentAccessors.h