Unreal Engine 5.6 C++ API: UE::FIoFileBlockRequestQueue Class Reference
UE::FIoFileBlockRequestQueue Class Reference
#include "PlatformIoDispatcherBase.h"
Data Structures
struct FFileOffset
struct FPrioQueue
Public Member Functions
FIoFileBlockRequestQueue (FPlatformIoDispatcherStats &InStats)
FIoFileBlockRequest * Dequeue ()
void Enqueue (FIoFileBlockRequestList &&Requests)
FIoFileBlockRequest * Peek ()
void Reprioritize ()
void ReprioritizeCancelled ()
void SortByOffset (bool bValue)
Private Member Functions
FIoFileBlockRequest * GetByOffset (bool bDequeue)
FIoFileBlockRequest * GetByOffset (FPrioQueue &PrioQueue, EIoFileReadPriority QueuePriority, bool bDequeue)
FIoFileBlockRequest * GetCancelled (bool bDequeue)
Static Private Member Functions
static bool FileOffsetLess (const FFileOffset &LHS, const FFileOffset &RHS)
static bool SeqNoLess (const FIoFileBlockRequest &LHS, const FIoFileBlockRequest &RHS)
static FFileOffset ToFileOffset (const FIoFileBlockRequest *Request)
Private Attributes
bool bReprioritizeCancelled = false
bool bSortByOffset = false
TArray< FIoFileBlockRequest * > CancelledHeap
TArray< FIoFileBlockRequest * > Heap
FFileOffset LastFileOffset
FPrioQueue PrioQueues [static_cast< int32 >(EIoFileReadPriority::Count)]
FPlatformIoDispatcherStats & Stats
Detailed Description
Definition at line 256 of file PlatformIoDispatcherBase.h.
Constructor & Destructor Documentation
FIoFileBlockRequestQueue()
UE::FIoFileBlockRequestQueue::FIoFileBlockRequestQueue (FPlatformIoDispatcherStats & InStats)
Definition at line 31 of file PlatformIoDispatcherBase.cpp.
References bSortByOffset, UE::Count, PrioQueues, and Stats.
Member Function Documentation
Dequeue()
FIoFileBlockRequest * UE::FIoFileBlockRequestQueue::Dequeue ()
Definition at line 67 of file PlatformIoDispatcherBase.cpp.
References bSortByOffset, UE::FIoFileBlockRequest::Dequeued, GetByOffset(), GetCancelled(), Heap, No, UE::FIoFileBlockRequest::QueueStatus, SeqNoLess(), and Stats.
Enqueue()
void UE::FIoFileBlockRequestQueue::Enqueue (FIoFileBlockRequestList && Requests)
Definition at line 43 of file PlatformIoDispatcherBase.cpp.
References TIntrusiveList< TypeTraits >::AddTail(), bSortByOffset, UE::FIoFileBlockRequestQueue::FPrioQueue::ByOffset, UE::FIoFileBlockRequestQueue::FPrioQueue::BySequence, check, UE::FIoFileBlockRequest::Enqueued, FileOffsetLess(), Heap, INDEX_NONE, UE::FIoFileBlockRequest::None, UE::FIoFileBlockRequestQueue::FPrioQueue::PeekIndex, PrioQueues, SeqNoLess(), Stats, ToFileOffset(), and Algo::UpperBoundBy().
FileOffsetLess()
bool UE::FIoFileBlockRequestQueue::FileOffsetLess (const FFileOffset & LHS, const FFileOffset & RHS) inline static private
Definition at line 282 of file PlatformIoDispatcherBase.h.
References UE::FIoFileBlockRequestQueue::FFileOffset::FileHandle, UE::FIoFileBlockRequestQueue::FFileOffset::FileOffset, and UE::FIoFileHandle::Value().
Referenced by Enqueue(), GetByOffset(), and Reprioritize().
GetByOffset() [1/2]
FIoFileBlockRequest * UE::FIoFileBlockRequestQueue::GetByOffset (bool bDequeue) private
Definition at line 151 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileBlockRequestQueue::FPrioQueue::BySequence, UE::Count, GetByOffset(), TIntrusiveList< TypeTraits >::IsEmpty(), and PrioQueues.
Referenced by Dequeue(), GetByOffset(), and Peek().
GetByOffset() [2/2]
FIoFileBlockRequest * UE::FIoFileBlockRequestQueue::GetByOffset (FPrioQueue & PrioQueue, EIoFileReadPriority QueuePriority, bool bDequeue) private
Definition at line 165 of file PlatformIoDispatcherBase.cpp.
References UE::FIoFileBlockRequestQueue::FPrioQueue::ByOffset, UE::FIoFileBlockRequestQueue::FPrioQueue::BySequence, check, FAndroidTime::Cycles64(), FileOffsetLess(), FGenericPlatformTime::GetSecondsPerCycle64(), GIoDispatcherMaintainSortingOnPriorityChange, GIoDispatcherRequestLatencyCircuitBreakerMS, INDEX_NONE, TIntrusiveList< TypeTraits >::IsEmpty(), LastFileOffset, Algo::LowerBoundBy(), No, TIntrusiveList< TypeTraits >::PeekHead(), UE::FIoFileBlockRequestQueue::FPrioQueue::PeekIndex, TIntrusiveList< TypeTraits >::Remove(), and ToFileOffset().
GetCancelled()
FIoFileBlockRequest * UE::FIoFileBlockRequestQueue::GetCancelled (bool bDequeue) private
Definition at line 226 of file PlatformIoDispatcherBase.cpp.
References bReprioritizeCancelled, bSortByOffset, Cancelled, CancelledHeap, UE::FIoFileBlockRequest::ErrorCode, Heap, INDEX_NONE, No, PrioQueues, SeqNoLess(), and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by Dequeue(), and Peek().
Peek()
FIoFileBlockRequest * UE::FIoFileBlockRequestQueue::Peek ()
Definition at line 92 of file PlatformIoDispatcherBase.cpp.
References bSortByOffset, GetByOffset(), GetCancelled(), and Heap.
Reprioritize()
void UE::FIoFileBlockRequestQueue::Reprioritize ()
Definition at line 111 of file PlatformIoDispatcherBase.cpp.
References TArray< InElementType, InAllocatorType >::Add(), TIntrusiveList< TypeTraits >::AddTail(), bSortByOffset, UE::FIoFileBlockRequestQueue::FPrioQueue::ByOffset, UE::FIoFileBlockRequestQueue::FPrioQueue::BySequence, FileOffsetLess(), Heap, INDEX_NONE, No, UE::FIoFileBlockRequestQueue::FPrioQueue::PeekIndex, PrioQueues, UE::FIoFileBlockRequest::Priority, SeqNoLess(), ToFileOffset(), TRACE_CPUPROFILER_EVENT_SCOPE, and Algo::UpperBoundBy().
ReprioritizeCancelled()
void UE::FIoFileBlockRequestQueue::ReprioritizeCancelled () inline
Definition at line 306 of file PlatformIoDispatcherBase.h.
References bReprioritizeCancelled.
SeqNoLess()
bool UE::FIoFileBlockRequestQueue::SeqNoLess (const FIoFileBlockRequest & LHS, const FIoFileBlockRequest & RHS) inline static private
Definition at line 291 of file PlatformIoDispatcherBase.h.
References UE::FIoFileBlockRequest::Priority, and UE::FIoFileBlockRequest::SeqNo.
Referenced by Dequeue(), Enqueue(), GetCancelled(), and Reprioritize().
SortByOffset()
void UE::FIoFileBlockRequestQueue::SortByOffset (bool bValue) inline
Definition at line 307 of file PlatformIoDispatcherBase.h.
References bSortByOffset.
ToFileOffset()
FFileOffset UE::FIoFileBlockRequestQueue::ToFileOffset (const FIoFileBlockRequest * Request) inline static private
Definition at line 272 of file PlatformIoDispatcherBase.h.
References UE::FIoFileBlockRequest::FileHandle, UE::FIoFileBlockRequest::FileOffset, and UE::FIoFileBlockRequest::Priority.
Referenced by Enqueue(), GetByOffset(), and Reprioritize().
Field Documentation
bReprioritizeCancelled
bool UE::FIoFileBlockRequestQueue::bReprioritizeCancelled = false private
Definition at line 320 of file PlatformIoDispatcherBase.h.
Referenced by GetCancelled(), and ReprioritizeCancelled().
bSortByOffset
bool UE::FIoFileBlockRequestQueue::bSortByOffset = false private
Definition at line 319 of file PlatformIoDispatcherBase.h.
Referenced by FIoFileBlockRequestQueue(), Dequeue(), Enqueue(), GetCancelled(), Peek(), Reprioritize(), and SortByOffset().
CancelledHeap
TArray<FIoFileBlockRequest*> UE::FIoFileBlockRequestQueue::CancelledHeap private
Definition at line 316 of file PlatformIoDispatcherBase.h.
Referenced by GetCancelled().
Heap
TArray<FIoFileBlockRequest*> UE::FIoFileBlockRequestQueue::Heap private
Definition at line 315 of file PlatformIoDispatcherBase.h.
Referenced by Dequeue(), Enqueue(), GetCancelled(), Peek(), and Reprioritize().
LastFileOffset
FFileOffset UE::FIoFileBlockRequestQueue::LastFileOffset private
Definition at line 318 of file PlatformIoDispatcherBase.h.
Referenced by GetByOffset().
PrioQueues
FPrioQueue UE::FIoFileBlockRequestQueue::PrioQueues[static_cast< int32 >(EIoFileReadPriority::Count)] private
Definition at line 317 of file PlatformIoDispatcherBase.h.
Referenced by FIoFileBlockRequestQueue(), Enqueue(), GetByOffset(), GetCancelled(), and Reprioritize().
Stats
FPlatformIoDispatcherStats& UE::FIoFileBlockRequestQueue::Stats private
Definition at line 314 of file PlatformIoDispatcherBase.h.
Referenced by FIoFileBlockRequestQueue(), Dequeue(), and Enqueue().
The documentation for this class was generated from the following files:
PlatformIoDispatcherBase.h
PlatformIoDispatcherBase.cpp