Unreal Engine 5.6 C++ API: FCanvasLineItem Class Reference
FCanvasLineItem Class Reference
#include "CanvasItem.h"
Public Member Functions
FCanvasLineItem ()
FCanvasLineItem (const FVector &InPosition, const FVector &InEndPos)
A Line.
FCanvasLineItem (const FVector2D &InPosition, const FVector2D &InEndPos)
A Line.
virtual void Draw (FCanvas *InCanvas) override
Draw line at the given coordinates.
virtual void Draw (FCanvas *InCanvas, const FVector &InPosition)
Draw line at the given coordinates.
virtual void Draw (FCanvas *InCanvas, const FVector2D &InPosition) override
Draw line at the given coordinates.
virtual void Draw (FCanvas *InCanvas, const FVector2D &InStartPos, const FVector2D &InEndPos)
Draw line using the given coordinates.
virtual void Draw (FCanvas *InCanvas, float InX, float InY) override
Draw line at the given coordinates.
virtual void Draw (FCanvas *InCanvas, float X, float Y, float Z)
Draw line at the given coordinates.
void SetEndPos (const FVector2D &InEndPos)
Set the line end position.
Public Member Functions inherited from FCanvasItem
FCanvasItem (const FVector2D &InPosition)
Basic render item.
virtual ~FCanvasItem ()
virtual void SetColor (const FLinearColor &InColor)
Data Fields
FVector EndPos
float LineThickness
FVector Origin
Data Fields inherited from FCanvasItem
FBatchedElementParameters * BatchedElementParameters
bool bFreezeTime
ESimpleElementBlendMode BlendMode
FVector2D Position
uint32 StereoDepth
Additional Inherited Members
Protected Attributes inherited from FCanvasItem
FLinearColor Color
Detailed Description
Definition at line 626 of file CanvasItem.h.
Constructor & Destructor Documentation
FCanvasLineItem() [1/3]
FCanvasLineItem::FCanvasLineItem () inline
Definition at line 629 of file CanvasItem.h.
References FCanvasItem::FCanvasItem(), EndPos, LineThickness, and Origin.
FCanvasLineItem() [2/3]
FCanvasLineItem::FCanvasLineItem (const FVector2D & InPosition, const FVector2D & InEndPos) inline
A Line.
Parameters
InPosition Start position
InEndPos End position
Definition at line 646 of file CanvasItem.h.
References FCanvasItem::FCanvasItem(), EndPos, LineThickness, Origin, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
FCanvasLineItem() [3/3]
FCanvasLineItem::FCanvasLineItem (const FVector & InPosition, const FVector & InEndPos) inline
A Line.
Parameters
InPosition Start position
InEndPos End position
Definition at line 664 of file CanvasItem.h.
References FCanvasItem::FCanvasItem(), EndPos, FVector, LineThickness, Origin, UE_REAL_TO_FLOAT, X, and Y.
Member Function Documentation
Draw() [1/6]
virtual void FCanvasLineItem::Draw (FCanvas * InCanvas) override virtual
Draw line at the given coordinates.
Parameters
InCanvas Canvas on which to draw
Implements FCanvasItem.
Referenced by Draw(), Draw(), Draw(), Draw(), and Draw().
Draw() [2/6]
virtual void FCanvasLineItem::Draw (FCanvas * InCanvas, const FVector & InPosition) inline virtual
Draw line at the given coordinates.
Parameters
InCanvas Canvas on which to draw
InPosition Draw position
Definition at line 726 of file CanvasItem.h.
References Draw(), FVector, and Origin.
Draw() [3/6]
virtual void FCanvasLineItem::Draw (FCanvas * InCanvas, const FVector2D & InPosition) inline override virtual
Draw line at the given coordinates.
Parameters
InCanvas Canvas on which to draw
InPosition Draw Start position
Reimplemented from FCanvasItem.
Definition at line 685 of file CanvasItem.h.
References Draw(), Origin, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Draw() [4/6]
virtual void FCanvasLineItem::Draw (FCanvas * InCanvas, const FVector2D & InStartPos, const FVector2D & InEndPos) inline virtual
Draw line using the given coordinates.
Parameters
InCanvas Canvas on which to draw
InStartPos Line start position
InEndPos Line end position
Definition at line 698 of file CanvasItem.h.
References Draw(), EndPos, Origin, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Draw() [5/6]
virtual void FCanvasLineItem::Draw (FCanvas * InCanvas, float InX, float InY) inline override virtual
Draw line at the given coordinates.
Parameters
InCanvas Canvas on which to draw
X X Draw position
Y Y Draw position
Reimplemented from FCanvasItem.
Definition at line 713 of file CanvasItem.h.
References Draw(), and Origin.
Draw() [6/6]
virtual void FCanvasLineItem::Draw (FCanvas * InCanvas, float X, float Y, float Z) inline virtual
Draw line at the given coordinates.
Parameters
InCanvas Canvas on which to draw
X X Draw position
Y Y Draw position
Z Z Draw position
Definition at line 740 of file CanvasItem.h.
References Draw(), Origin, X, Y, and Z.
SetEndPos()
void FCanvasLineItem::SetEndPos (const FVector2D & InEndPos) inline
Set the line end position.
Parameters
InEndPos End position of the line
Definition at line 753 of file CanvasItem.h.
References EndPos, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Field Documentation
EndPos
FVector FCanvasLineItem::EndPos
Definition at line 763 of file CanvasItem.h.
Referenced by FCanvasLineItem(), FCanvasLineItem(), FCanvasLineItem(), Draw(), and SetEndPos().
LineThickness
float FCanvasLineItem::LineThickness
Definition at line 766 of file CanvasItem.h.
Referenced by FCanvasLineItem(), FCanvasLineItem(), and FCanvasLineItem().
Origin
FVector FCanvasLineItem::Origin
Definition at line 760 of file CanvasItem.h.
Referenced by FCanvasLineItem(), FCanvasLineItem(), FCanvasLineItem(), Draw(), Draw(), Draw(), Draw(), and Draw().
The documentation for this class was generated from the following file:
CanvasItem.h