Unreal Engine 5.6 C++ API: FInputBindingManager Class Reference
FInputBindingManager Class Reference
Manager responsible for creating and processing input bindings.
#include "InputBindingManager.h"
Data Structures
struct FCommandFilterForContext
struct FCommandFilterOwners
struct FContextEntry
Public Types
enum class ECommandFilterType { None , DenyList , AllowList }
Public Member Functions
virtual ~FInputBindingManager ()
Virtual destructor.
void AddCommandFilter (const FName InOwnerName, const FName InBindingContext, const FName InCommandName, const ECommandFilterType FilterType)
Filters a command by name.
bool CommandPassesFilter (const FName InBindingContext, const FName InCommandName) const
Command passes allow/deny list filters.
void CreateInputCommand (const TSharedRef< FBindingContext > &InBindingContext, TSharedRef< FUICommandInfo > InUICommandInfo)
Creates an input command from the specified user interface action.
const TSharedPtr< FUICommandInfo > FindCommandInContext (const FName InBindingContext, const FInputChord &InChord, bool bCheckDefault) const
Finds the command in the provided context which uses the provided input chord.
const TSharedPtr< FUICommandInfo > FindCommandInContext (const FName InBindingContext, const FName CommandName) const
Finds the command in the provided context which has the provided name.
const TSharedPtr< FUICommandInfo > GetCommandInfoFromInputChord (const FName InBindingContext, const FInputChord &InChord, bool bCheckDefault) const
Returns a command info that is has the same active chord as the provided chord and is in the same binding context or parent context.
void GetCommandInfosFromContext (const FName InBindingContext, TArray< TSharedPtr< FUICommandInfo > > &OutCommandInfos) const
Returns all known command infos for a given binding context.
TSharedPtr< FBindingContext > GetContextByName (const FName &InContextName)
Look up a binding context by name.
void GetKnownInputContexts (TArray< TSharedPtr< FBindingContext > > &OutInputContexts) const
Returns a list of all known input contexts.
bool GetProjectDefinedChord (const FName InBindingContext, const FName InCommandName, const EMultipleKeyBindingIndex InChordIndex, FInputChord &OutUserDefinedChord)
Gets the project defined chord (if any) from the provided command name.
bool GetUserDefinedChord (const FName InBindingContext, const FName InCommandName, const EMultipleKeyBindingIndex InChordIndex, FInputChord &OutUserDefinedChord)
Gets the user defined chord (if any) from the provided command name.
virtual void NotifyActiveChordChanged (const FUICommandInfo &CommandInfo, const EMultipleKeyBindingIndex InChordIndex)
Called when the active chord is changed on a command.
bool RegisterCommandList (const ::FName InBindingContext, TSharedRef< FUICommandList > CommandList) const
Exposes the given command list and its context to all OnRegisterCommandList subscribers.
TSharedPtr< FUICommandList > RegisterNewCommandList (const FName InBindingContext) const
Exposes a new given command list from the given context to all OnRegisterCommandList subscribers.
FDelegateHandle RegisterUserDefinedChordChanged (const FOnUserDefinedChordChanged::FDelegate &Delegate)
Registers a delegate to be called when a user-defined chord is edited.
void RemoveContextByName (const FName &InContextName)
Remove the context with this name.
void RemoveInputCommand (const TSharedRef< FBindingContext > &InBindingContext, TSharedRef< FUICommandInfo > InUICommandInfo)
Removes an input command, allowing a new one to take its place.
void RemoveUserDefinedChords ()
Removes any user defined chords.
void SaveInputBindings ()
Saves the user defined chords to a json file.
void UnregisterCommandFilterOwner (const FName InOwnerName)
Removes all filters associated with an owner.
bool UnregisterCommandList (const ::FName InBindingContext, TSharedRef< FUICommandList > CommandList) const
Exposes the given command list and its context to all OnUnregisterCommandList subscribers.
void UnregisterUserDefinedChordChanged (FDelegateHandle DelegateHandle)
Unregisters a delegate to be called when a user-defined chord is edited.
Static Public Member Functions
static FInputBindingManager & Get ()
Data Fields
FOnRegisterCommandList OnRegisterCommandList
A delegate for systems to subscribe to any other system exposing their command lists.
FOnRegisterCommandList OnUnregisterCommandList
A delegate for systems to subscribe to any other system unregistering their command lists.
Private Member Functions
FInputBindingManager ()
Hidden default constructor.
void CheckForDuplicateDefaultChords (const FBindingContext &InBindingContext, TSharedPtr< FUICommandInfo > InCommandInfo) const
Checks a binding context for duplicate chords.
void GetAllChildContexts (const FName InBindingContext, TArray< FName > &AllChildren) const
Recursively finds all child contexts of the provided binding context.
void PrintAllInputCommands (bool bBoundOnly)
Displays list of commands.
Private Attributes
TMap< FName, FCommandFilterForContext > CommandFiltersByContext
Mapping of command filters by context.
TMap< FName, FContextEntry > ContextMap
A mapping of context name to the associated entry map.
FOnUserDefinedChordChanged OnUserDefinedChordChanged
Delegate called when a user-defined chord is edited.
TMultiMap< FName, FName > ParentToChildMap
A mapping of contexts to their child contexts.
TSharedPtr< class FUserDefinedChords > ProjectDefinedChords
Project defined chord overrides for commands.
TSharedPtr< class FUserDefinedChords > UserDefinedChords
User defined chord overrides for commands.
Detailed Description
Manager responsible for creating and processing input bindings.
Definition at line 25 of file InputBindingManager.h.
Member Enumeration Documentation
ECommandFilterType
enum class FInputBindingManager::ECommandFilterType strong
Enumerator
None
DenyList
AllowList
Definition at line 159 of file InputBindingManager.h.
Constructor & Destructor Documentation
~FInputBindingManager()
virtual FInputBindingManager::~FInputBindingManager () inline virtual
Virtual destructor.
Definition at line 37 of file InputBindingManager.h.
FInputBindingManager()
FInputBindingManager::FInputBindingManager () private
Hidden default constructor.
Referenced by Get().
Member Function Documentation
AddCommandFilter()
void FInputBindingManager::AddCommandFilter (const FName InOwnerName, const FName InBindingContext, const FName InCommandName, const ECommandFilterType FilterType)
Filters a command by name.
Parameters
InOwnerName The name of the owner adding filter so it can be unregistered later
InBindingContext The context in which the command is active
InCommandName The name of the command
FilterType Type of filter to apply
CheckForDuplicateDefaultChords()
void FInputBindingManager::CheckForDuplicateDefaultChords (const FBindingContext & InBindingContext, TSharedPtr< FUICommandInfo > InCommandInfo) const private
Checks a binding context for duplicate chords.
CommandPassesFilter()
bool FInputBindingManager::CommandPassesFilter (const FName InBindingContext, const FName InCommandName) const
Command passes allow/deny list filters.
Parameters
InBindingContext The context in which the command is active
InCommandName The name of the command
CreateInputCommand()
void FInputBindingManager::CreateInputCommand (const TSharedRef< FBindingContext > & InBindingContext, TSharedRef< FUICommandInfo > InUICommandInfo)
Creates an input command from the specified user interface action.
Parameters
InBindingContext The context where the command is valid
InUICommandInfo The user interface action to create the input command from Will automatically bind the user interface action to the command specified by the action so when the command's chord is pressed, the action is executed
FindCommandInContext() [1/2]
const TSharedPtr< FUICommandInfo > FInputBindingManager::FindCommandInContext (const FName InBindingContext, const FInputChord & InChord, bool bCheckDefault) const
Finds the command in the provided context which uses the provided input chord.
Parameters
InBindingContext The binding context name
InChord The chord to check against when looking for commands
bCheckDefault Whether or not to check the default chord of commands instead of active chords
OutActiveChordIndex The index into the commands active chord array where the passed in chord was matched. INDEX_NONE if bCheckDefault is true or nothing was found.
FindCommandInContext() [2/2]
const TSharedPtr< FUICommandInfo > FInputBindingManager::FindCommandInContext (const FName InBindingContext, const FName CommandName) const
Finds the command in the provided context which has the provided name.
Parameters
InBindingContext The binding context name
CommandName The name of the command to find
Get()
FInputBindingManager & FInputBindingManager::Get () static
Returns
The instance of this manager
References FInputBindingManager().
Referenced by TCommands< CommandContextType >::Register(), and TCommands< CommandContextType >::Unregister().
GetAllChildContexts()
void FInputBindingManager::GetAllChildContexts (const FName InBindingContext, TArray< FName > & AllChildren) const private
Recursively finds all child contexts of the provided binding context.
Parameters
InBindingContext The binding context to search
AllChildren All the children of InBindingContext. InBindingContext is the first element in AllChildren
GetCommandInfoFromInputChord()
const TSharedPtr< FUICommandInfo > FInputBindingManager::GetCommandInfoFromInputChord (const FName InBindingContext, const FInputChord & InChord, bool bCheckDefault) const
Returns a command info that is has the same active chord as the provided chord and is in the same binding context or parent context.
Parameters
InBindingContext The context in which the command is valid
InChord The chord to match against commands
bCheckDefault Whether or not to check the default chord. Will check the active chord if false
Returns
A pointer to the command info which has the InChord as its active chord or null if one cannot be found
GetCommandInfosFromContext()
void FInputBindingManager::GetCommandInfosFromContext (const FName InBindingContext, TArray< TSharedPtr< FUICommandInfo > > & OutCommandInfos) const
Returns all known command infos for a given binding context.
Parameters
InBindingContext The binding context to get command infos from
OutCommandInfos The list of command infos for the binding context
GetContextByName()
TSharedPtr< FBindingContext > FInputBindingManager::GetContextByName (const FName & InContextName)
Look up a binding context by name.
Referenced by TCommands< CommandContextType >::Register().
GetKnownInputContexts()
void FInputBindingManager::GetKnownInputContexts (TArray< TSharedPtr< FBindingContext > > & OutInputContexts) const
Returns a list of all known input contexts.
Parameters
OutInputContexts The generated list of contexts
Returns
A list of all known input contexts
GetProjectDefinedChord()
bool FInputBindingManager::GetProjectDefinedChord (const FName InBindingContext, const FName InCommandName, const EMultipleKeyBindingIndex InChordIndex, FInputChord & OutUserDefinedChord)
Gets the project defined chord (if any) from the provided command name.
Parameters
InBindingContext The context in which the command is active
InCommandName The name of the command to get the chord from
ChordIndex The index of the key binding (in the multiple key bindings array)
GetUserDefinedChord()
bool FInputBindingManager::GetUserDefinedChord (const FName InBindingContext, const FName InCommandName, const EMultipleKeyBindingIndex InChordIndex, FInputChord & OutUserDefinedChord)
Gets the user defined chord (if any) from the provided command name.
Parameters
InBindingContext The context in which the command is active
InCommandName The name of the command to get the chord from
ChordIndex The index of the key binding (in the multiple key bindings array)
NotifyActiveChordChanged()
virtual void FInputBindingManager::NotifyActiveChordChanged (const FUICommandInfo & CommandInfo, const EMultipleKeyBindingIndex InChordIndex) virtual
Called when the active chord is changed on a command.
Parameters
CommandInfo The command that had the active chord changed.
PrintAllInputCommands()
void FInputBindingManager::PrintAllInputCommands (bool bBoundOnly) private
Displays list of commands.
RegisterCommandList()
bool FInputBindingManager::RegisterCommandList (const ::FName InBindingContext, TSharedRef< FUICommandList > CommandList) const
Exposes the given command list and its context to all OnRegisterCommandList subscribers.
Parameters
InBindingContext The context in which the command list is active
CommandList The command list to expose to subscribers
RegisterNewCommandList()
TSharedPtr< FUICommandList > FInputBindingManager::RegisterNewCommandList (const FName InBindingContext) const
Exposes a new given command list from the given context to all OnRegisterCommandList subscribers.
Parameters
InBindingContext The context in which the command list is active
Returns
The new command list exposed to subscribers
RegisterUserDefinedChordChanged()
FDelegateHandle FInputBindingManager::RegisterUserDefinedChordChanged (const FOnUserDefinedChordChanged::FDelegate & Delegate) inline
Registers a delegate to be called when a user-defined chord is edited.
Definition at line 129 of file InputBindingManager.h.
References OnUserDefinedChordChanged.
RemoveContextByName()
void FInputBindingManager::RemoveContextByName (const FName & InContextName)
Remove the context with this name.
Referenced by TCommands< CommandContextType >::Unregister().
RemoveInputCommand()
void FInputBindingManager::RemoveInputCommand (const TSharedRef< FBindingContext > & InBindingContext, TSharedRef< FUICommandInfo > InUICommandInfo)
Removes an input command, allowing a new one to take its place.
Parameters
InBindingContext The context where the command is valid
InUICommandInfo The user interface action to remove
RemoveUserDefinedChords()
void FInputBindingManager::RemoveUserDefinedChords ()
Removes any user defined chords.
SaveInputBindings()
void FInputBindingManager::SaveInputBindings ()
Saves the user defined chords to a json file.
UnregisterCommandFilterOwner()
void FInputBindingManager::UnregisterCommandFilterOwner (const FName InOwnerName)
Removes all filters associated with an owner.
UnregisterCommandList()
bool FInputBindingManager::UnregisterCommandList (const ::FName InBindingContext, TSharedRef< FUICommandList > CommandList) const
Exposes the given command list and its context to all OnUnregisterCommandList subscribers.
Parameters
InBindingContext The context in which the command list is active
CommandList The command list to expose to subscribers
UnregisterUserDefinedChordChanged()
void FInputBindingManager::UnregisterUserDefinedChordChanged (FDelegateHandle DelegateHandle) inline
Unregisters a delegate to be called when a user-defined chord is edited.
Definition at line 135 of file InputBindingManager.h.
References OnUserDefinedChordChanged.
Field Documentation
CommandFiltersByContext
TMap<FName, FCommandFilterForContext> FInputBindingManager::CommandFiltersByContext private
Mapping of command filters by context.
Definition at line 273 of file InputBindingManager.h.
ContextMap
TMap< FName, FContextEntry > FInputBindingManager::ContextMap private
A mapping of context name to the associated entry map.
Definition at line 276 of file InputBindingManager.h.
OnRegisterCommandList
FOnRegisterCommandList FInputBindingManager::OnRegisterCommandList
A delegate for systems to subscribe to any other system exposing their command lists.
Definition at line 213 of file InputBindingManager.h.
OnUnregisterCommandList
FOnRegisterCommandList FInputBindingManager::OnUnregisterCommandList
A delegate for systems to subscribe to any other system unregistering their command lists.
Definition at line 216 of file InputBindingManager.h.
OnUserDefinedChordChanged
FOnUserDefinedChordChanged FInputBindingManager::OnUserDefinedChordChanged private
Delegate called when a user-defined chord is edited.
Definition at line 288 of file InputBindingManager.h.
Referenced by RegisterUserDefinedChordChanged(), and UnregisterUserDefinedChordChanged().
ParentToChildMap
TMultiMap< FName, FName > FInputBindingManager::ParentToChildMap private
A mapping of contexts to their child contexts.
Definition at line 279 of file InputBindingManager.h.
ProjectDefinedChords
TSharedPtr< class FUserDefinedChords > FInputBindingManager::ProjectDefinedChords private
Project defined chord overrides for commands.
Definition at line 285 of file InputBindingManager.h.
UserDefinedChords
TSharedPtr< class FUserDefinedChords > FInputBindingManager::UserDefinedChords private
User defined chord overrides for commands.
Definition at line 282 of file InputBindingManager.h.
The documentation for this class was generated from the following file:
InputBindingManager.h