Unreal Engine 5.6 C++ API: UE::SequenceNavigator::INavigationToolItem Class Reference
UE::SequenceNavigator::INavigationToolItem Class Reference abstract
#include "INavigationToolItem.h"
Public Types
using FOnExpansionChanged = TMulticastDelegate<void(const TSharedPtr<INavigationToolView>&, bool)>
Delegate signature for when the Item Expansion Changes const TSharedPtr<FNavigationToolView>& - The Navigation Tool View where this Expansion happened bool - Whether the Item is expanded.
using FOnRenameAction = TMulticastDelegate<void(ENavigationToolRenameAction, const TSharedPtr<INavigationToolView>&)>
Delegate signature for relaying an Item Rename action ENavigationToolRenameAction the type of action being relayed (e.g.
Public Types inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
using FNavigationToolItemInherits = TNavigationToolItemInherits<INavigationToolItemTypeCastable,>
Public Member Functions
virtual FReply AcceptDrop (const FDragDropEvent &InDragDropEvent, const EItemDropZone InDropZone)=0
Processes the Drag and Drop Event for this Item.
virtual bool AddChild (const FNavigationToolAddItemParams &InAddItemParams)=0
Adds another Child under this Item if such Item is supported.
virtual void AddFlags (const ENavigationToolItemFlags InFlag)=0
virtual TOptional< EItemDropZone > CanAcceptDrop (const FDragDropEvent &InDragDropEvent, const EItemDropZone InDropZone)=0
Determines if and where the incoming Drag Drop Event can be processed by this item.
virtual bool CanAddChild (const FNavigationToolItemPtr &InChild) const =0
Determines whether the given Child is supported and can be added under this Item.
virtual bool CanAutoExpand () const =0
Whether the Item is able to expand when AutoExpand functionality is enabled.
virtual bool CanBeTopLevel () const =0
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
virtual bool CanDelete () const =0
Whether this Item can be deleted or not.
virtual bool CanReceiveParentVisibilityPropagation () const =0
Whether a change in Parent Visibility should also affect this Item's Visibility.
virtual bool Delete ()=0
The implementation to delete the item.
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false)
Finds the first ancestor view model that implements the given type.
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false) const
template<typename InItemType>
TArray< InItemType * > FindAncestorsOfType (const bool bInIncludeThis=false) const
virtual void FindChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive)=0
Figures out the Children of this Item.
virtual TArray< FNavigationToolItemPtr > FindPath (const TArray< FNavigationToolItemPtr > &Items) const
virtual void FindValidChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive)
virtual TSharedRef< SWidget > GenerateLabelWidget (const TSharedRef< SNavigationToolTreeRow > &InRow)=0
Function responsible of Generating the Label Widget for this Item (i.e.
virtual FNavigationToolItemPtr GetChildAt (const IndexType Index) const
virtual IndexType GetChildIndex (const FNavigationToolItemPtr &ChildItem) const
Gets the Index that the given Child Item is at.
virtual const TArray< FNavigationToolItemPtr > & GetChildren () const =0
Gets the current Child Items of this Item.
virtual TArray< FNavigationToolItemPtr > & GetChildrenMutable ()=0
Gets the current Child Items of this Item.
template<typename InItemType>
TArray< InItemType * > GetChildrenOfType (const bool bInIncludeThis=false) const
virtual FText GetClassName () const =0
Gets the Class/Type of this Item (e.g.
virtual const FSlateBrush * GetDefaultIconBrush () const
TArray< FNavigationToolItemPtr > GetDescendants (const bool bInIncludeThis=false)
template<typename InItemType>
TArray< InItemType * > GetDescendantsOfType (const bool bInIncludeThis=false) const
virtual FText GetDisplayName () const =0
Gets the Display Name Text of the Item.
virtual ENavigationToolItemFlags GetFlags () const =0
FString GetFullPath () const
Returns the path to this item in the tree.
virtual FSlateIcon GetIcon () const =0
Gets the slate icon for the item.
virtual const FSlateBrush * GetIconBrush () const =0
virtual FSlateColor GetIconColor () const =0
Gets the color for the item icon.
virtual FText GetIconTooltipText () const =0
Gets the tooltip text for the item icon.
virtual FNavigationToolItemId GetItemId () const =0
Gets the Id of this Item.
virtual FSlateColor GetItemLabelColor () const =0
Gets the color to use for the item label.
virtual UObject * GetItemObject () const
Gets the UObject that this item represents.
virtual void GetItemProxies (TArray< TSharedPtr< FNavigationToolItemProxy > > &OutItemProxies)
Gets the Item Proxies for this Item (e.g.
virtual FLinearColor GetItemTintColor () const =0
Gets the color to use to tint the entire item row (all column content)
virtual int32 GetItemTreeHeight () const
Returns the item's height in tree, Root Item should return 0 as it has no Parent.
virtual INavigationTool & GetOwnerTool () const =0
Gets the Navigation Tool that owns this item.
virtual FNavigationToolItemPtr GetParent () const =0
Gets the Parent of this Item.
virtual TSet< FNavigationToolItemPtr > GetParents (const bool bInIncludeRoot=false) const
Gets the list of all parents up the tree from this Item.
virtual TSharedPtr< FNavigationToolProvider > GetProvider () const =0
Gets the module provider responsible for the creation of this item.
virtual FNavigationToolSaveState * GetProviderSaveState () const =0
Gets the providers saved state.
virtual ENavigationToolItemViewMode GetSupportedViewModes (const INavigationToolView &InToolView) const =0
Gets the View Modes that this Item Supports.
virtual TArray< FName > GetTags () const
Gets the Tags found for this Item (e.g.
virtual bool GetVisibility () const =0
Whether this Item is currently visible or not for the Given Type.
virtual bool HasAllFlags (const ENavigationToolItemFlags InFlag) const =0
virtual bool HasAnyFlags (const ENavigationToolItemFlags InFlag) const =0
virtual bool IsAllowedInTool () const =0
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
virtual bool IsExpanded () const =0
Gets whether this item is expanded.
bool IsIgnoringPendingKill () const
Whether Ignoring Pending Kill.
virtual bool IsItemValid () const =0
Determines whether the Item properties are in a valid state.
virtual bool IsSelectable () const
Whether the Item can be selected in Navigation Tool at all.
virtual bool IsSelected (const FNavigationToolScopedSelection &InSelection) const
Determines whether the given Item is selected in the given Scoped Selection.
virtual bool IsViewModeSupported (const ENavigationToolItemViewMode InViewMode, const INavigationToolView &InToolView) const
Whether this Item should be visualized in the given View Mode, for the given Navigation Tool View.
virtual FNavigationToolSerializedItem MakeSerializedItem ()
Converts this Navigation Tool item to a serialized item that can be saved in the sequence.
virtual void OnDoubleClick ()
Called when an Item is double-clicked with the mouse.
virtual FOnExpansionChanged & OnExpansionChanged ()=0
Called when Expansion state (Expanded/Collapsed) has been changed.
virtual void OnItemRegistered ()
Called when the Item has been registered into the Navigation Tool.
virtual void OnItemSelectionChanged (const bool bInIsSelected)
Called when the Item been selected/deselected from the Tree View.
virtual void OnItemUnregistered ()
Called when the Item has been unregistered from the Navigation Tool.
virtual void OnObjectsReplaced (const TMap< UObject *, UObject * > &InReplacementMap, const bool bInRecursive)
Called when objects have been replaced on the Engine side.
virtual FOnRenameAction & OnRenameAction ()=0
Broadcasts whenever a rename action takes place from a given view (e.g.
virtual void OnSelect ()
Called when an Item is selected.
virtual void OnVisibilityChanged (const bool bInNewVisibility)
Called when the Visibility on Item has been changed on the Navigation Tool side.
virtual void RefreshChildren ()=0
Refreshes what the Parent and Children are of this Item.
virtual bool RemoveChild (const FNavigationToolRemoveItemParams &InRemoveItemParams)=0
Removes the given child from this Item if it was ever indeed a child.
virtual void RemoveFlags (const ENavigationToolItemFlags InFlag)=0
virtual void ResetChildren ()
Resets both the Cached Visible Children and Children (before doing so, sets all child's parents to null)
virtual void Select (FNavigationToolScopedSelection &InSelection) const
Used to signal the Scoped Selection that this Item should be Selected.
virtual void SetExpansion (const bool bInIsExpanded)=0
Sets the expansion state of this item.
virtual void SetFlags (const ENavigationToolItemFlags InFlags)=0
virtual void SetParent (FNavigationToolItemPtr InParent)=0
Sets the Parent.
virtual bool ShouldSort () const =0
Determines whether this item can be sorted by the Navigation Tool or not.
virtual bool ShowVisibility () const =0
Whether this Item supports Visibility for the Given Type.
UE_NAVIGATIONTOOL_INHERITS (INavigationToolItem, INavigationToolItemTypeCastable)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
virtual ~INavigationToolItemTypeCastable ()=default
template<typename InType>
InType * CastTo ()
template<typename InType>
const InType * CastTo () const
virtual const void * CastTo_Impl (FNavigationToolItemTypeId InId) const =0
virtual FNavigationToolItemTypeId GetTypeId () const =0
template<typename InType>
bool IsA () const
template<typename InType>
bool IsExactlyA () const
Public Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedRef< INavigationToolItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< INavigationToolItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Types
using IndexType = TArray<INavigationToolItem>::SizeType
Additional Inherited Members
Static Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
static FNavigationToolItemTypeId GetStaticTypeId ()
Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 39 of file INavigationToolItem.h.
Member Typedef Documentation
FOnExpansionChanged
using UE::SequenceNavigator::INavigationToolItem::FOnExpansionChanged = TMulticastDelegate<void(const TSharedPtr<INavigationToolView>&, bool)>
Delegate signature for when the Item Expansion Changes const TSharedPtr<FNavigationToolView>& - The Navigation Tool View where this Expansion happened bool - Whether the Item is expanded.
Definition at line 491 of file INavigationToolItem.h.
FOnRenameAction
using UE::SequenceNavigator::INavigationToolItem::FOnRenameAction = TMulticastDelegate<void(ENavigationToolRenameAction, const TSharedPtr<INavigationToolView>&)>
Delegate signature for relaying an Item Rename action ENavigationToolRenameAction the type of action being relayed (e.g.
request a rename, or notify rename complete, etc) const TSharedPtr<INavigationToolView>& - The Navigation Tool View where the rename action is taking place
Definition at line 535 of file INavigationToolItem.h.
IndexType
using UE::SequenceNavigator::INavigationToolItem::IndexType = TArray<INavigationToolItem>::SizeType protected
Definition at line 42 of file INavigationToolItem.h.
Member Function Documentation
AcceptDrop()
virtual FReply UE::SequenceNavigator::INavigationToolItem::AcceptDrop (const FDragDropEvent & InDragDropEvent, const EItemDropZone InDropZone) pure virtual
Processes the Drag and Drop Event for this Item.
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolSubTrack.
AddChild()
virtual bool UE::SequenceNavigator::INavigationToolItem::AddChild (const FNavigationToolAddItemParams & InAddItemParams) pure virtual
Adds another Child under this Item if such Item is supported.
Returns true if it did, false if it could not add it (e.g. item not supported).
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolSequence.
AddFlags()
virtual void UE::SequenceNavigator::INavigationToolItem::AddFlags (const ENavigationToolItemFlags InFlag) pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem.
CanAcceptDrop()
virtual TOptional< EItemDropZone > UE::SequenceNavigator::INavigationToolItem::CanAcceptDrop (const FDragDropEvent & InDragDropEvent, const EItemDropZone InDropZone) pure virtual
Determines if and where the incoming Drag Drop Event can be processed by this item.
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolSubTrack.
CanAddChild()
virtual bool UE::SequenceNavigator::INavigationToolItem::CanAddChild (const FNavigationToolItemPtr & InChild) const pure virtual
Determines whether the given Child is supported and can be added under this Item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
CanAutoExpand()
virtual bool UE::SequenceNavigator::INavigationToolItem::CanAutoExpand () const pure virtual
Whether the Item is able to expand when AutoExpand functionality is enabled.
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolItemProxy.
CanBeTopLevel()
virtual bool UE::SequenceNavigator::INavigationToolItem::CanBeTopLevel () const pure virtual
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
Actors can be Top Level, but Components or Materials can't
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
CanDelete()
virtual bool UE::SequenceNavigator::INavigationToolItem::CanDelete () const pure virtual
Whether this Item can be deleted or not.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolMarker.
CanReceiveParentVisibilityPropagation()
virtual bool UE::SequenceNavigator::INavigationToolItem::CanReceiveParentVisibilityPropagation () const pure virtual
Whether a change in Parent Visibility should also affect this Item's Visibility.
Implemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolItem.
Delete()
virtual bool UE::SequenceNavigator::INavigationToolItem::Delete () pure virtual
The implementation to delete the item.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolMarker.
FindAncestorOfType() [1/2]
template<typename InItemType> InItemType * UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType (const bool bInIncludeThis = false) inline
Finds the first ancestor view model that implements the given type.
Definition at line 385 of file INavigationToolItem.h.
References UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo(), GetParent(), UE::SequenceNavigator::INavigationToolItemTypeCastable::IsA(), and TSharedPtr< ObjectType, InMode >::IsValid().
FindAncestorOfType() [2/2]
template<typename InItemType> InItemType * UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType (const bool bInIncludeThis = false) const inline
Definition at line 250 of file INavigationToolItem.h.
References UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo(), GetParent(), and TSharedPtr< ObjectType, InMode >::IsValid().
FindAncestorsOfType()
template<typename InItemType> TArray< InItemType * > UE::SequenceNavigator::INavigationToolItem::FindAncestorsOfType (const bool bInIncludeThis = false) const inline
Definition at line 276 of file INavigationToolItem.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo(), GetParent(), and TSharedPtr< ObjectType, InMode >::IsValid().
FindChildren()
virtual void UE::SequenceNavigator::INavigationToolItem::FindChildren (TArray< FNavigationToolItemPtr > & OutChildren, const bool bInRecursive) pure virtual
Figures out the Children of this Item.
This is only relevant for items that do have that functionality (e.g. Components or Actors)
Implemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponent, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolSequence, UE::SequenceNavigator::FNavigationToolSubTrack, and UE::SequenceNavigator::FNavigationToolTrack.
Referenced by FindValidChildren().
FindPath()
virtual TArray< FNavigationToolItemPtr > UE::SequenceNavigator::INavigationToolItem::FindPath (const TArray< FNavigationToolItemPtr > & Items) const inline virtual
Reimplemented in UE::SequenceNavigator::FNavigationToolItem.
Definition at line 146 of file INavigationToolItem.h.
References TSharedPtr< ObjectType, InMode >::IsValid(), Item, Path, Algo::Reverse(), and TSharedFromThis< INavigationToolItem >::SharedThis().
FindValidChildren()
virtual void UE::SequenceNavigator::INavigationToolItem::FindValidChildren (TArray< FNavigationToolItemPtr > & OutChildren, const bool bInRecursive) inline virtual
Reimplemented in UE::SequenceNavigator::FNavigationToolItem.
Definition at line 127 of file INavigationToolItem.h.
References FindChildren(), TSharedPtr< ObjectType, InMode >::IsValid(), and TArray< InElementType, InAllocatorType >::RemoveAll().
GenerateLabelWidget()
virtual TSharedRef< SWidget > UE::SequenceNavigator::INavigationToolItem::GenerateLabelWidget (const TSharedRef< SNavigationToolTreeRow > & InRow) pure virtual
Function responsible of Generating the Label Widget for this Item (i.e.
the column containing the Icon and the Name)
Implemented in UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolItem.
GetChildAt()
virtual FNavigationToolItemPtr UE::SequenceNavigator::INavigationToolItem::GetChildAt (const IndexType Index) const inline virtual
Definition at line 216 of file INavigationToolItem.h.
References GetChildren(), and TArray< InElementType, InAllocatorType >::IsValidIndex().
GetChildIndex()
virtual IndexType UE::SequenceNavigator::INavigationToolItem::GetChildIndex (const FNavigationToolItemPtr & ChildItem) const inline virtual
Gets the Index that the given Child Item is at.
NOTE: This includes HIDDEN items as Item Visibility is relative to each Navigation Tool View. To consider only Visible Items, use FNavigationToolView::GetVisibleChildAt.
Reimplemented in UE::SequenceNavigator::FNavigationToolItem.
Definition at line 206 of file INavigationToolItem.h.
References GetChildren().
GetChildren()
virtual const TArray< FNavigationToolItemPtr > & UE::SequenceNavigator::INavigationToolItem::GetChildren () const pure virtual
Gets the current Child Items of this Item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
Referenced by GetChildAt(), GetChildIndex(), GetChildrenOfType(), GetDescendants(), GetDescendantsOfType(), OnObjectsReplaced(), and ResetChildren().
GetChildrenMutable()
virtual TArray< FNavigationToolItemPtr > & UE::SequenceNavigator::INavigationToolItem::GetChildrenMutable () pure virtual
Gets the current Child Items of this Item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
Referenced by ResetChildren().
GetChildrenOfType()
template<typename InItemType> TArray< InItemType * > UE::SequenceNavigator::INavigationToolItem::GetChildrenOfType (const bool bInIncludeThis = false) const inline
Definition at line 358 of file INavigationToolItem.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo(), Child, and GetChildren().
GetClassName()
virtual FText UE::SequenceNavigator::INavigationToolItem::GetClassName () const pure virtual
Gets the Class/Type of this Item (e.g.
for Items that represent UObjects, it will be the UObject class)
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
GetDefaultIconBrush()
virtual const FSlateBrush * UE::SequenceNavigator::INavigationToolItem::GetDefaultIconBrush () const inline virtual
Reimplemented in UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 433 of file INavigationToolItem.h.
GetDescendants()
TArray< FNavigationToolItemPtr > UE::SequenceNavigator::INavigationToolItem::GetDescendants (const bool bInIncludeThis = false) inline
Definition at line 303 of file INavigationToolItem.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Append(), TSharedFromThis< INavigationToolItem >::AsShared(), Child, and GetChildren().
GetDescendantsOfType()
template<typename InItemType> TArray< InItemType * > UE::SequenceNavigator::INavigationToolItem::GetDescendantsOfType (const bool bInIncludeThis = false) const inline
Definition at line 326 of file INavigationToolItem.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Append(), UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo(), Child, and GetChildren().
GetDisplayName()
virtual FText UE::SequenceNavigator::INavigationToolItem::GetDisplayName () const pure virtual
Gets the Display Name Text of the Item.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponentProxy, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
GetFlags()
virtual ENavigationToolItemFlags UE::SequenceNavigator::INavigationToolItem::GetFlags () const pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem.
GetFullPath()
FString UE::SequenceNavigator::INavigationToolItem::GetFullPath () const inline
Returns the path to this item in the tree.
Ex. "RootId,ChildId,ChildId"
Definition at line 173 of file INavigationToolItem.h.
References GetParent(), TSharedPtr< ObjectType, InMode >::IsValid(), and TEXT.
GetIcon()
virtual FSlateIcon UE::SequenceNavigator::INavigationToolItem::GetIcon () const pure virtual
Gets the slate icon for the item.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponentProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
GetIconBrush()
virtual const FSlateBrush * UE::SequenceNavigator::INavigationToolItem::GetIconBrush () const pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolMarker.
GetIconColor()
virtual FSlateColor UE::SequenceNavigator::INavigationToolItem::GetIconColor () const pure virtual
Gets the color for the item icon.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolMarker.
GetIconTooltipText()
virtual FText UE::SequenceNavigator::INavigationToolItem::GetIconTooltipText () const pure virtual
Gets the tooltip text for the item icon.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponentProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
GetItemId()
virtual FNavigationToolItemId UE::SequenceNavigator::INavigationToolItem::GetItemId () const pure virtual
Gets the Id of this Item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
Referenced by MakeSerializedItem().
GetItemLabelColor()
virtual FSlateColor UE::SequenceNavigator::INavigationToolItem::GetItemLabelColor () const pure virtual
Gets the color to use for the item label.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, and UE::SequenceNavigator::FNavigationToolItem.
GetItemObject()
virtual UObject * UE::SequenceNavigator::INavigationToolItem::GetItemObject () const inline virtual
Gets the UObject that this item represents.
May be null due if no item association or multiple.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 51 of file INavigationToolItem.h.
GetItemProxies()
virtual void UE::SequenceNavigator::INavigationToolItem::GetItemProxies (TArray< TSharedPtr< FNavigationToolItemProxy > > & OutItemProxies) inline virtual
Gets the Item Proxies for this Item (e.g.
Component Item that represent Primitives add in a Material Proxy to display)
Reimplemented in UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolSequence.
Definition at line 139 of file INavigationToolItem.h.
GetItemTintColor()
virtual FLinearColor UE::SequenceNavigator::INavigationToolItem::GetItemTintColor () const pure virtual
Gets the color to use to tint the entire item row (all column content)
Implemented in UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolItem.
GetItemTreeHeight()
virtual int32 UE::SequenceNavigator::INavigationToolItem::GetItemTreeHeight () const inline virtual
Returns the item's height in tree, Root Item should return 0 as it has no Parent.
Definition at line 518 of file INavigationToolItem.h.
References GetParent(), and TSharedPtr< ObjectType, InMode >::IsValid().
GetOwnerTool()
virtual INavigationTool & UE::SequenceNavigator::INavigationToolItem::GetOwnerTool () const pure virtual
Gets the Navigation Tool that owns this item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
GetParent()
virtual FNavigationToolItemPtr UE::SequenceNavigator::INavigationToolItem::GetParent () const pure virtual
Gets the Parent of this Item.
Should only be null prior to registering it in Navigation Tool or if its Root Item
Implemented in UE::SequenceNavigator::FNavigationToolItem.
Referenced by FindAncestorOfType(), FindAncestorOfType(), FindAncestorsOfType(), GetFullPath(), GetItemTreeHeight(), and GetParents().
GetParents()
virtual TSet< FNavigationToolItemPtr > UE::SequenceNavigator::INavigationToolItem::GetParents (const bool bInIncludeRoot = false) const inline virtual
Gets the list of all parents up the tree from this Item.
Definition at line 230 of file INavigationToolItem.h.
References TSet< InElementType, KeyFuncs, Allocator >::Add(), GetParent(), TSharedPtr< ObjectType, InMode >::IsValid(), and UE::SequenceNavigator::FNavigationToolItemId::RootId.
GetProvider()
virtual TSharedPtr< FNavigationToolProvider > UE::SequenceNavigator::INavigationToolItem::GetProvider () const pure virtual
Gets the module provider responsible for the creation of this item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
GetProviderSaveState()
virtual FNavigationToolSaveState * UE::SequenceNavigator::INavigationToolItem::GetProviderSaveState () const pure virtual
Gets the providers saved state.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
GetSupportedViewModes()
virtual ENavigationToolItemViewMode UE::SequenceNavigator::INavigationToolItem::GetSupportedViewModes (const INavigationToolView & InToolView) const pure virtual
Gets the View Modes that this Item Supports.
Implemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolComponent, UE::SequenceNavigator::FNavigationToolComponentProxy, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, and UE::SequenceNavigator::FNavigationToolSequence.
Referenced by IsViewModeSupported().
GetTags()
virtual TArray< FName > UE::SequenceNavigator::INavigationToolItem::GetTags () const inline virtual
Gets the Tags found for this Item (e.g.
for Actors, actor tags and for Components Component Tags)
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolItem.
Definition at line 515 of file INavigationToolItem.h.
GetVisibility()
virtual bool UE::SequenceNavigator::INavigationToolItem::GetVisibility () const pure virtual
Whether this Item is currently visible or not for the Given Type.
Implemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolItem.
HasAllFlags()
virtual bool UE::SequenceNavigator::INavigationToolItem::HasAllFlags (const ENavigationToolItemFlags InFlag) const pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem.
Referenced by IsIgnoringPendingKill().
HasAnyFlags()
virtual bool UE::SequenceNavigator::INavigationToolItem::HasAnyFlags (const ENavigationToolItemFlags InFlag) const pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem.
IsAllowedInTool()
virtual bool UE::SequenceNavigator::INavigationToolItem::IsAllowedInTool () const pure virtual
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
Implemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolComponent, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
IsExpanded()
virtual bool UE::SequenceNavigator::INavigationToolItem::IsExpanded () const pure virtual
Gets whether this item is expanded.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
IsIgnoringPendingKill()
bool UE::SequenceNavigator::INavigationToolItem::IsIgnoringPendingKill () const inline
Whether Ignoring Pending Kill.
Useful to get underlying UObjects that are pending kill and get the pointer to it and not a null value
Definition at line 547 of file INavigationToolItem.h.
References HasAllFlags().
IsItemValid()
virtual bool UE::SequenceNavigator::INavigationToolItem::IsItemValid () const pure virtual
Determines whether the Item properties are in a valid state.
Implemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolItem, UE::SequenceNavigator::FNavigationToolItemProxy, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
IsSelectable()
virtual bool UE::SequenceNavigator::INavigationToolItem::IsSelectable () const inline virtual
Whether the Item can be selected in Navigation Tool at all.
Definition at line 66 of file INavigationToolItem.h.
IsSelected()
virtual bool UE::SequenceNavigator::INavigationToolItem::IsSelected (const FNavigationToolScopedSelection & InSelection) const inline virtual
Determines whether the given Item is selected in the given Scoped Selection.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 63 of file INavigationToolItem.h.
IsViewModeSupported()
virtual bool UE::SequenceNavigator::INavigationToolItem::IsViewModeSupported (const ENavigationToolItemViewMode InViewMode, const INavigationToolView & InToolView) const inline virtual
Whether this Item should be visualized in the given View Mode, for the given Navigation Tool View.
Definition at line 447 of file INavigationToolItem.h.
References EnumHasAnyFlags(), and GetSupportedViewModes().
MakeSerializedItem()
virtual FNavigationToolSerializedItem UE::SequenceNavigator::INavigationToolItem::MakeSerializedItem () inline virtual
Converts this Navigation Tool item to a serialized item that can be saved in the sequence.
Definition at line 556 of file INavigationToolItem.h.
References GetItemId().
OnDoubleClick()
virtual void UE::SequenceNavigator::INavigationToolItem::OnDoubleClick () inline virtual
Called when an Item is double-clicked with the mouse.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 72 of file INavigationToolItem.h.
OnExpansionChanged()
virtual FOnExpansionChanged & UE::SequenceNavigator::INavigationToolItem::OnExpansionChanged () pure virtual
Called when Expansion state (Expanded/Collapsed) has been changed.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
OnItemRegistered()
virtual void UE::SequenceNavigator::INavigationToolItem::OnItemRegistered () inline virtual
Called when the Item has been registered into the Navigation Tool.
Definition at line 78 of file INavigationToolItem.h.
OnItemSelectionChanged()
virtual void UE::SequenceNavigator::INavigationToolItem::OnItemSelectionChanged (const bool bInIsSelected) inline virtual
Called when the Item been selected/deselected from the Tree View.
Definition at line 84 of file INavigationToolItem.h.
OnItemUnregistered()
virtual void UE::SequenceNavigator::INavigationToolItem::OnItemUnregistered () inline virtual
Called when the Item has been unregistered from the Navigation Tool.
Definition at line 81 of file INavigationToolItem.h.
OnObjectsReplaced()
virtual void UE::SequenceNavigator::INavigationToolItem::OnObjectsReplaced (const TMap< UObject *, UObject * > & InReplacementMap, const bool bInRecursive) inline virtual
Called when objects have been replaced on the Engine side.
Used to replace any UObjects used by this item
Parameters
InReplacementMap the map of old object that is garbage to the new object that replaced it
bInRecursive whether to recurse this same function to children items
Reimplemented in UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 457 of file INavigationToolItem.h.
References GetChildren().
OnRenameAction()
virtual FOnRenameAction & UE::SequenceNavigator::INavigationToolItem::OnRenameAction () pure virtual
Broadcasts whenever a rename action takes place from a given view (e.g.
when pressing "F2" to rename, or committing the rename text)
Implemented in UE::SequenceNavigator::FNavigationToolItem.
OnSelect()
virtual void UE::SequenceNavigator::INavigationToolItem::OnSelect () inline virtual
Called when an Item is selected.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 69 of file INavigationToolItem.h.
OnVisibilityChanged()
virtual void UE::SequenceNavigator::INavigationToolItem::OnVisibilityChanged (const bool bInNewVisibility) inline virtual
Called when the Visibility on Item has been changed on the Navigation Tool side.
Reimplemented in UE::SequenceNavigator::FNavigationToolActor, and UE::SequenceNavigator::FNavigationToolComponent.
Definition at line 484 of file INavigationToolItem.h.
RefreshChildren()
virtual void UE::SequenceNavigator::INavigationToolItem::RefreshChildren () pure virtual
Refreshes what the Parent and Children are of this Item.
(not recursive!)
Implemented in UE::SequenceNavigator::FNavigationToolItem.
RemoveChild()
virtual bool UE::SequenceNavigator::INavigationToolItem::RemoveChild (const FNavigationToolRemoveItemParams & InRemoveItemParams) pure virtual
Removes the given child from this Item if it was ever indeed a child.
Returns true if the removal did happen.
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolSequence.
RemoveFlags()
virtual void UE::SequenceNavigator::INavigationToolItem::RemoveFlags (const ENavigationToolItemFlags InFlag) pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem.
ResetChildren()
virtual void UE::SequenceNavigator::INavigationToolItem::ResetChildren () inline virtual
Resets both the Cached Visible Children and Children (before doing so, sets all child's parents to null)
Reimplemented in UE::SequenceNavigator::FNavigationToolItem.
Definition at line 90 of file INavigationToolItem.h.
References GetChildren(), GetChildrenMutable(), and Item.
Select()
virtual void UE::SequenceNavigator::INavigationToolItem::Select (FNavigationToolScopedSelection & InSelection) const inline virtual
Used to signal the Scoped Selection that this Item should be Selected.
Reimplemented in UE::SequenceNavigator::FNavigationToolBinding, UE::SequenceNavigator::FNavigationToolMarker, UE::SequenceNavigator::FNavigationToolSequence, and UE::SequenceNavigator::FNavigationToolTrack.
Definition at line 60 of file INavigationToolItem.h.
SetExpansion()
virtual void UE::SequenceNavigator::INavigationToolItem::SetExpansion (const bool bInIsExpanded) pure virtual
Sets the expansion state of this item.
Implemented in UE::SequenceNavigator::FNavigationToolItem.
SetFlags()
virtual void UE::SequenceNavigator::INavigationToolItem::SetFlags (const ENavigationToolItemFlags InFlags) pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolItem.
SetParent()
virtual void UE::SequenceNavigator::INavigationToolItem::SetParent (FNavigationToolItemPtr InParent) pure virtual
Sets the Parent.
Note that the Parent must've already have this instance as a child (check is done)
Implemented in UE::SequenceNavigator::FNavigationToolItem, and UE::SequenceNavigator::FNavigationToolItemProxy.
ShouldSort()
virtual bool UE::SequenceNavigator::INavigationToolItem::ShouldSort () const pure virtual
Determines whether this item can be sorted by the Navigation Tool or not.
Unsorted Items usually mean that they have their own way of sorting that Navigation Tool's Item Sorting Data should not interfere with. Note: Unsorted Children go before Sorted Items (e.g. Item Proxies go first before Actors below a Parent)
Implemented in UE::SequenceNavigator::FNavigationToolBinding, and UE::SequenceNavigator::FNavigationToolItem.
ShowVisibility()
virtual bool UE::SequenceNavigator::INavigationToolItem::ShowVisibility () const pure virtual
Whether this Item supports Visibility for the Given Type.
Implemented in UE::SequenceNavigator::FNavigationToolActor, UE::SequenceNavigator::FNavigationToolComponent, and UE::SequenceNavigator::FNavigationToolItem.
UE_NAVIGATIONTOOL_INHERITS()
UE::SequenceNavigator::INavigationToolItem::UE_NAVIGATIONTOOL_INHERITS (INavigationToolItem , INavigationToolItemTypeCastable)
The documentation for this class was generated from the following file:
INavigationToolItem.h