Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitInterfaceRegistry Struct Reference
UE::AnimNext::FTraitInterfaceRegistry Struct Reference final
FTraitInterfaceRegistry.
#include "TraitInterfaceRegistry.h"
Data Structures
struct FRegistryEntry
Public Member Functions
ANIMNEXTANIMGRAPH_API const ITraitInterface * Find (FTraitInterfaceUID InterfaceUID) const
ANIMNEXTANIMGRAPH_API uint32 GetNum () const
ANIMNEXTANIMGRAPH_API TArray< const ITraitInterface * > GetTraitInterfaces () const
ANIMNEXTANIMGRAPH_API void Register (const TSharedPtr< ITraitInterface > &TraitInterface)
ANIMNEXTANIMGRAPH_API void Unregister (const TSharedPtr< ITraitInterface > &TraitInterface)
Static Public Member Functions
static ANIMNEXTANIMGRAPH_API FTraitInterfaceRegistry & Get ()
Private Member Functions
FTraitInterfaceRegistry ()=default
FTraitInterfaceRegistry (const FTraitInterfaceRegistry &)=delete
FTraitInterfaceRegistry (FTraitInterfaceRegistry &&)=default
FTraitInterfaceRegistry & operator= (const FTraitInterfaceRegistry &)=delete
FTraitInterfaceRegistry & operator= (FTraitInterfaceRegistry &&)=default
Static Private Member Functions
static ANIMNEXTANIMGRAPH_API void Destroy ()
static ANIMNEXTANIMGRAPH_API void Init ()
static ANIMNEXTANIMGRAPH_API void StaticRegister (const TSharedPtr< ITraitInterface > &TraitInterface)
static ANIMNEXTANIMGRAPH_API void StaticUnregister (const TSharedPtr< ITraitInterface > &TraitInterface)
Private Attributes
TMap< FTraitInterfaceUIDRaw, FRegistryEntry > TraitInterfaceUIDToEntryMap
Friends
struct FTraitInterfaceStaticInitHook
class UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule
Detailed Description
FTraitInterfaceRegistry.
A global registry of all existing trait interfaces that can be used in animation graph traits.
See also
FTraitInterface
Definition at line 25 of file TraitInterfaceRegistry.h.
Constructor & Destructor Documentation
FTraitInterfaceRegistry() [1/3]
UE::AnimNext::FTraitInterfaceRegistry::FTraitInterfaceRegistry () private default
Referenced by FTraitInterfaceRegistry(), FTraitInterfaceRegistry(), Get(), operator=(), and operator=().
FTraitInterfaceRegistry() [2/3]
UE::AnimNext::FTraitInterfaceRegistry::FTraitInterfaceRegistry (const FTraitInterfaceRegistry &) private delete
References FTraitInterfaceRegistry().
FTraitInterfaceRegistry() [3/3]
UE::AnimNext::FTraitInterfaceRegistry::FTraitInterfaceRegistry (FTraitInterfaceRegistry &&) private default
References FTraitInterfaceRegistry().
Member Function Documentation
Destroy()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitInterfaceRegistry::Destroy () static private
References UE_API.
Find()
ANIMNEXTANIMGRAPH_API const ITraitInterface * UE::AnimNext::FTraitInterfaceRegistry::Find (FTraitInterfaceUID InterfaceUID) const
References UE_API.
Get()
ANIMNEXTANIMGRAPH_API FTraitInterfaceRegistry & UE::AnimNext::FTraitInterfaceRegistry::Get () static
References FTraitInterfaceRegistry(), and UE_API.
GetNum()
ANIMNEXTANIMGRAPH_API uint32 UE::AnimNext::FTraitInterfaceRegistry::GetNum () const
References UE_API.
GetTraitInterfaces()
ANIMNEXTANIMGRAPH_API TArray< const ITraitInterface * > UE::AnimNext::FTraitInterfaceRegistry::GetTraitInterfaces () const
References UE_API.
Init()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitInterfaceRegistry::Init () static private
References UE_API.
operator=() [1/2]
FTraitInterfaceRegistry & UE::AnimNext::FTraitInterfaceRegistry::operator= (const FTraitInterfaceRegistry &) private delete
References FTraitInterfaceRegistry().
operator=() [2/2]
FTraitInterfaceRegistry & UE::AnimNext::FTraitInterfaceRegistry::operator= (FTraitInterfaceRegistry &&) private default
References FTraitInterfaceRegistry().
Register()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitInterfaceRegistry::Register (const TSharedPtr< ITraitInterface > & TraitInterface)
References UE_API.
StaticRegister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitInterfaceRegistry::StaticRegister (const TSharedPtr< ITraitInterface > & TraitInterface) static private
References UE_API.
StaticUnregister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitInterfaceRegistry::StaticUnregister (const TSharedPtr< ITraitInterface > & TraitInterface) static private
References UE_API.
Unregister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitInterfaceRegistry::Unregister (const TSharedPtr< ITraitInterface > & TraitInterface)
References UE_API.
Friends And Related Symbol Documentation
FTraitInterfaceStaticInitHook
friend struct FTraitInterfaceStaticInitHook friend
Definition at line 71 of file TraitInterfaceRegistry.h.
References FTraitInterfaceStaticInitHook.
Referenced by FTraitInterfaceStaticInitHook.
UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule
friend class UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule friend
Definition at line 70 of file TraitInterfaceRegistry.h.
References UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule.
Referenced by UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule.
Field Documentation
TraitInterfaceUIDToEntryMap
TMap<FTraitInterfaceUIDRaw, FRegistryEntry> UE::AnimNext::FTraitInterfaceRegistry::TraitInterfaceUIDToEntryMap private
Definition at line 68 of file TraitInterfaceRegistry.h.
The documentation for this struct was generated from the following file:
TraitInterfaceRegistry.h