Unreal Engine 5.6 C++ API: TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType Class Reference
TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType Class Reference
#include "ContainerAllocationPolicies.h"
Public Member Functions
ForAnyElementType ()
Default constructor.
FORCEINLINE ~ForAnyElementType ()
Destructor.
FORCEINLINE SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) const
FORCEINLINE SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) const
FORCEINLINE SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) const
SIZE_T GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE FScriptContainerElement * GetAllocation () const
SizeType GetInitialCapacity () const
bool HasAllocation () const
FORCEINLINE void MoveToEmpty (ForAnyElementType &Other)
Moves the state of another allocator into this one.
template<typename OtherAllocator>
FORCEINLINE void MoveToEmptyFromOtherAllocator (typename OtherAllocator::ForAnyElementType &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement)
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement)
Private Member Functions
ForAnyElementType (const ForAnyElementType &)
ForAnyElementType & operator= (const ForAnyElementType &)
Private Attributes
FScriptContainerElement * Data
A pointer to the container's elements.
Friends
template<int, typename>
class TSizedHeapAllocator
Detailed Description
template<int IndexSize, typename BaseMallocType = FMemory>
class TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType
Definition at line 635 of file ContainerAllocationPolicies.h.
Constructor & Destructor Documentation
ForAnyElementType() [1/2]
template<int IndexSize, typename BaseMallocType = FMemory> TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::ForAnyElementType () inline
Default constructor.
Definition at line 642 of file ContainerAllocationPolicies.h.
References Data.
Referenced by ForAnyElementType(), MoveToEmpty(), and operator=().
~ForAnyElementType()
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::~ForAnyElementType () inline
Destructor.
Definition at line 683 of file ContainerAllocationPolicies.h.
References Data, and FORCEINLINE.
ForAnyElementType() [2/2]
template<int IndexSize, typename BaseMallocType = FMemory> TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::ForAnyElementType (const ForAnyElementType &) private
References ForAnyElementType().
Member Function Documentation
CalculateSlackGrow() [1/2]
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 766 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackGrow(), and FORCEINLINE.
CalculateSlackGrow() [2/2]
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) const inline
Definition at line 770 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackGrow(), and FORCEINLINE.
CalculateSlackReserve() [1/2]
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const inline
Definition at line 750 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackReserve(), and FORCEINLINE.
CalculateSlackReserve() [2/2]
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) const inline
Definition at line 754 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackReserve(), and FORCEINLINE.
CalculateSlackShrink() [1/2]
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 758 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackShrink(), and FORCEINLINE.
CalculateSlackShrink() [2/2]
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) const inline
Definition at line 762 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackShrink(), and FORCEINLINE.
GetAllocatedSize()
template<int IndexSize, typename BaseMallocType = FMemory> SIZE_T TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 775 of file ContainerAllocationPolicies.h.
GetAllocation()
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE FScriptContainerElement * TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::GetAllocation () const inline
Definition at line 696 of file ContainerAllocationPolicies.h.
References Data, and FORCEINLINE.
Referenced by TSizedHeapAllocator< IndexSize, BaseMallocType >::ForElementType< ElementType >::GetAllocation().
GetInitialCapacity()
template<int IndexSize, typename BaseMallocType = FMemory> SizeType TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::GetInitialCapacity () const inline
Definition at line 785 of file ContainerAllocationPolicies.h.
HasAllocation()
template<int IndexSize, typename BaseMallocType = FMemory> bool TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::HasAllocation () const inline
Definition at line 780 of file ContainerAllocationPolicies.h.
References Data.
MoveToEmpty()
template<int IndexSize, typename BaseMallocType = FMemory> FORCEINLINE void TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::MoveToEmpty (ForAnyElementType & Other) inline
Moves the state of another allocator into this one.
Moves the state of another allocator into this one. The allocator can be different.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 677 of file ContainerAllocationPolicies.h.
References ForAnyElementType(), FORCEINLINE, MoveToEmptyFromOtherAllocator(), and Other.
MoveToEmptyFromOtherAllocator()
template<int IndexSize, typename BaseMallocType = FMemory> template<typename OtherAllocator> FORCEINLINE void TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::MoveToEmptyFromOtherAllocator (typename OtherAllocator::ForAnyElementType & Other) inline
Moves the state of another allocator into this one.
The allocator can be different.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 653 of file ContainerAllocationPolicies.h.
References checkSlow, Data, FORCEINLINE, and Other.
Referenced by MoveToEmpty().
operator=()
template<int IndexSize, typename BaseMallocType = FMemory> ForAnyElementType & TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::operator= (const ForAnyElementType &) private
References ForAnyElementType().
ResizeAllocation() [1/2]
template<int IndexSize, typename BaseMallocType = FMemory> template FORCENOINLINE void TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 700 of file ContainerAllocationPolicies.h.
References Data, MAX_int32, UE::Core::Private::OnInvalidSizedHeapAllocatorNum(), and UNLIKELY.
ResizeAllocation() [2/2]
template<int IndexSize, typename BaseMallocType = FMemory> template FORCENOINLINE void TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement, uint32 AlignmentOfElement) inline
Definition at line 725 of file ContainerAllocationPolicies.h.
References Data, MAX_int32, UE::Core::Private::OnInvalidSizedHeapAllocatorNum(), and UNLIKELY.
Friends And Related Symbol Documentation
TSizedHeapAllocator
template<int IndexSize, typename BaseMallocType = FMemory> template<int, typename> friend class TSizedHeapAllocator friend
Definition at line 638 of file ContainerAllocationPolicies.h.
References TSizedHeapAllocator.
Referenced by TSizedHeapAllocator.
Field Documentation
Data
template<int IndexSize, typename BaseMallocType = FMemory> FScriptContainerElement* TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::Data private
A pointer to the container's elements.
Definition at line 809 of file ContainerAllocationPolicies.h.
Referenced by ForAnyElementType(), ~ForAnyElementType(), GetAllocation(), HasAllocation(), MoveToEmptyFromOtherAllocator(), ResizeAllocation(), and ResizeAllocation().
The documentation for this class was generated from the following file:
ContainerAllocationPolicies.h