Unreal Engine 5.6 C++ API: UE::AnimNext::FTimelineState Struct Reference
UE::AnimNext::FTimelineState Struct Reference
Timeline State.
#include "ITimeline.h"
Public Member Functions
FTimelineState ()=default
FTimelineState (float InPosition, float InDuration, float InPlayRate, bool bInIsLooping)
FTimelineState AsLooping (bool InAsLooping=true) const
FName GetDebugName () const
float GetDuration () const
float GetPlayRate () const
float GetPosition () const
float GetPositionRatio () const
float GetTimeLeft () const
bool IsFinite () const
bool IsLooping () const
void Reset ()
FTimelineState WithDebugName (FName InDebugName) const
FTimelineState WithDuration (float InDuration) const
FTimelineState WithPlayRate (float InPlayRate) const
FTimelineState WithPosition (float InPosition) const
Private Attributes
bool bIsLooping = false
FName DebugName
float Duration = 0.0f
float PlayRate = 0.0f
float Position = 0.0f
Detailed Description
Timeline State.
Encapsulates the state of a timeline.
Definition at line 50 of file ITimeline.h.
Constructor & Destructor Documentation
FTimelineState() [1/2]
UE::AnimNext::FTimelineState::FTimelineState () default
Referenced by AsLooping(), WithDebugName(), WithDuration(), WithPlayRate(), and WithPosition().
FTimelineState() [2/2]
UE::AnimNext::FTimelineState::FTimelineState (float InPosition, float InDuration, float InPlayRate, bool bInIsLooping) inline
Definition at line 56 of file ITimeline.h.
References bIsLooping, Duration, PlayRate, and Position.
Member Function Documentation
AsLooping()
FTimelineState UE::AnimNext::FTimelineState::AsLooping (bool InAsLooping = true) const inline nodiscard
Definition at line 162 of file ITimeline.h.
References FTimelineState().
GetDebugName()
FName UE::AnimNext::FTimelineState::GetDebugName () const inline
Definition at line 78 of file ITimeline.h.
References DebugName.
GetDuration()
float UE::AnimNext::FTimelineState::GetDuration () const inline
Definition at line 114 of file ITimeline.h.
References Duration.
GetPlayRate()
float UE::AnimNext::FTimelineState::GetPlayRate () const inline
Definition at line 117 of file ITimeline.h.
References PlayRate.
GetPosition()
float UE::AnimNext::FTimelineState::GetPosition () const inline
Definition at line 88 of file ITimeline.h.
References Position.
GetPositionRatio()
float UE::AnimNext::FTimelineState::GetPositionRatio () const inline
Definition at line 92 of file ITimeline.h.
References FMath::Clamp(), Duration, IsFinite(), and Position.
GetTimeLeft()
float UE::AnimNext::FTimelineState::GetTimeLeft () const inline
Definition at line 103 of file ITimeline.h.
References Duration, IsFinite(), PlayRate, and Position.
IsFinite()
bool UE::AnimNext::FTimelineState::IsFinite () const inline
Definition at line 123 of file ITimeline.h.
References Duration.
Referenced by GetPositionRatio(), and GetTimeLeft().
IsLooping()
bool UE::AnimNext::FTimelineState::IsLooping () const inline
Definition at line 120 of file ITimeline.h.
References bIsLooping.
Reset()
void UE::AnimNext::FTimelineState::Reset () inline
Definition at line 65 of file ITimeline.h.
References bIsLooping, DebugName, Duration, PlayRate, and Position.
WithDebugName()
FTimelineState UE::AnimNext::FTimelineState::WithDebugName (FName InDebugName) const inline nodiscard
Definition at line 126 of file ITimeline.h.
References FTimelineState().
WithDuration()
FTimelineState UE::AnimNext::FTimelineState::WithDuration (float InDuration) const inline nodiscard
Definition at line 146 of file ITimeline.h.
References FTimelineState().
WithPlayRate()
FTimelineState UE::AnimNext::FTimelineState::WithPlayRate (float InPlayRate) const inline nodiscard
Definition at line 154 of file ITimeline.h.
References FTimelineState().
WithPosition()
FTimelineState UE::AnimNext::FTimelineState::WithPosition (float InPosition) const inline nodiscard
Definition at line 138 of file ITimeline.h.
References FTimelineState().
Field Documentation
bIsLooping
bool UE::AnimNext::FTimelineState::bIsLooping = false private
Definition at line 185 of file ITimeline.h.
Referenced by FTimelineState(), IsLooping(), and Reset().
DebugName
FName UE::AnimNext::FTimelineState::DebugName private
Definition at line 172 of file ITimeline.h.
Referenced by GetDebugName(), and Reset().
Duration
float UE::AnimNext::FTimelineState::Duration = 0.0f private
Definition at line 179 of file ITimeline.h.
Referenced by FTimelineState(), GetDuration(), GetPositionRatio(), GetTimeLeft(), IsFinite(), and Reset().
PlayRate
float UE::AnimNext::FTimelineState::PlayRate = 0.0f private
Definition at line 182 of file ITimeline.h.
Referenced by FTimelineState(), GetPlayRate(), GetTimeLeft(), and Reset().
Position
float UE::AnimNext::FTimelineState::Position = 0.0f private
Definition at line 176 of file ITimeline.h.
Referenced by FTimelineState(), GetPosition(), GetPositionRatio(), GetTimeLeft(), and Reset().
The documentation for this struct was generated from the following file:
ITimeline.h