Unreal Engine 5.6 C++ API: TMpscQueue< T, AllocatorType > Class Template Reference
TMpscQueue< T, AllocatorType > Class Template Reference final
Fast multi-producer/single-consumer unbounded concurrent queue.
#include "MpscQueue.h"
Data Structures
struct FNode
Public Types
using ElementType = T
Public Member Functions
TMpscQueue ()
~TMpscQueue ()
TOptional< ElementType > Dequeue ()
bool Dequeue (ElementType &OutElem)
template<typename... ArgTypes>
void Enqueue (ArgTypes &&... Args)
bool IsEmpty () const
ElementType * Peek () const
UE_NONCOPYABLE (TMpscQueue)
Private Attributes
std::atomic< FNode * > Head
FNode * Tail
Detailed Description
template<typename T, typename AllocatorType = FMemory>
class TMpscQueue< T, AllocatorType >
Fast multi-producer/single-consumer unbounded concurrent queue.
Based on http://www.1024cores.net/home/lock-free-algorithms/queues/non-intrusive-mpsc-node-based-queue
Definition at line 17 of file MpscQueue.h.
Member Typedef Documentation
ElementType
template<typename T, typename AllocatorType = FMemory> using TMpscQueue< T, AllocatorType >::ElementType = T
Definition at line 20 of file MpscQueue.h.
Constructor & Destructor Documentation
TMpscQueue()
template<typename T, typename AllocatorType = FMemory> TMpscQueue< T, AllocatorType >::TMpscQueue () inline nodiscard
Definition at line 24 of file MpscQueue.h.
References Head, and Tail.
Referenced by UE_NONCOPYABLE().
~TMpscQueue()
template<typename T, typename AllocatorType = FMemory> TMpscQueue< T, AllocatorType >::~TMpscQueue () inline
Definition at line 31 of file MpscQueue.h.
References DestructItem(), and Tail.
Member Function Documentation
Dequeue() [1/2]
template<typename T, typename AllocatorType = FMemory> TOptional< ElementType > TMpscQueue< T, AllocatorType >::Dequeue () inline
Definition at line 58 of file MpscQueue.h.
References DestructItem(), MoveTemp(), and Tail.
Referenced by Dequeue().
Dequeue() [2/2]
template<typename T, typename AllocatorType = FMemory> bool TMpscQueue< T, AllocatorType >::Dequeue (ElementType & OutElem) inline
Definition at line 77 of file MpscQueue.h.
References Dequeue(), TOptional< OptionalType >::GetValue(), TOptional< OptionalType >::IsSet(), and MoveTempIfPossible().
Enqueue()
template<typename T, typename AllocatorType = FMemory> template<typename... ArgTypes> void TMpscQueue< T, AllocatorType >::Enqueue (ArgTypes &&... Args) inline
Definition at line 49 of file MpscQueue.h.
References Forward(), Head, New(), and TMpscQueue< T, AllocatorType >::FNode::Next.
IsEmpty()
template<typename T, typename AllocatorType = FMemory> bool TMpscQueue< T, AllocatorType >::IsEmpty () const inline nodiscard
Definition at line 104 of file MpscQueue.h.
References Tail.
Peek()
template<typename T, typename AllocatorType = FMemory> ElementType * TMpscQueue< T, AllocatorType >::Peek () const inline nodiscard
Definition at line 92 of file MpscQueue.h.
References Tail.
UE_NONCOPYABLE()
template<typename T, typename AllocatorType = FMemory> TMpscQueue< T, AllocatorType >::UE_NONCOPYABLE (TMpscQueue< T, AllocatorType >)
References TMpscQueue().
Field Documentation
Head
template<typename T, typename AllocatorType = FMemory> std::atomic<FNode*> TMpscQueue< T, AllocatorType >::Head private
Definition at line 117 of file MpscQueue.h.
Referenced by TMpscQueue(), and Enqueue().
Tail
template<typename T, typename AllocatorType = FMemory> FNode* TMpscQueue< T, AllocatorType >::Tail private
Definition at line 118 of file MpscQueue.h.
Referenced by TMpscQueue(), ~TMpscQueue(), Dequeue(), IsEmpty(), and Peek().
The documentation for this class was generated from the following file:
MpscQueue.h