Unreal Engine 5.6 C++ API: FKelvinletBrushOp Class Reference
FKelvinletBrushOp Class Reference
#include "KelvinletBrushOp.h"
Data Structures
struct FKelvinletBrushOpProperties
Public Member Functions
FKelvinletBrushOp (const FDynamicMesh3 &DynamicMesh)
~FKelvinletBrushOp ()
void ApplyBrush (const FKelvinletBrushOpProperties &Properties, const FMatrix &WorldToBrush, const TArray< int > &VertRIO, TArray< FVector3d > &ROIPositionBuffer)
template<typename KelvinletType>
void ApplyKelvinlet (const KelvinletType &Kelvinlet, const TArray< int > &VertexROI, TArray< FVector3d > &ROIPositionBuffer, const double Dt, const int NumIntegrationSteps)
template<typename KelvinletType>
void DisplaceKelvinlet (const KelvinletType &Kelvinlet, const TArray< int > &VertexROI, TArray< FVector3d > &ROIPositionBuffer)
void ExtractTransform (const FMatrix &WorldToBrush)
template<typename KelvinletType>
void IntegrateKelvinlet (const KelvinletType &Kelvinlet, const TArray< int > &VertexROI, TArray< FVector3d > &ROIPositionBuffer, const double Dt, const int Steps)
Data Fields
FMatrix3d BrushToWorldMat
const FDynamicMesh3 * Mesh
double NumSteps = 0.0
double TimeStep = 1.0
FVector3d Translation
FMatrix3d WorldToBrushMat
Private Member Functions
FVector3d InvXForm (const FVector3d &Pos) const
FVector3d XForm (const FVector3d &Pos) const
Detailed Description
Definition at line 485 of file KelvinletBrushOp.h.
Constructor & Destructor Documentation
FKelvinletBrushOp()
FKelvinletBrushOp::FKelvinletBrushOp (const FDynamicMesh3 & DynamicMesh) inline
Definition at line 520 of file KelvinletBrushOp.h.
References Mesh.
~FKelvinletBrushOp()
FKelvinletBrushOp::~FKelvinletBrushOp () inline
Definition at line 553 of file KelvinletBrushOp.h.
Member Function Documentation
ApplyBrush()
void FKelvinletBrushOp::ApplyBrush (const FKelvinletBrushOpProperties & Properties, const FMatrix & WorldToBrush, const TArray< int > & VertRIO, TArray< FVector3d > & ROIPositionBuffer) inline
Definition at line 572 of file KelvinletBrushOp.h.
References Alpha, ApplyKelvinlet(), BiLaplacianPullKelvinlet, check, UE::Geometry::CrossProductMatrix(), ExtractTransform(), Force, FVector, LaplacianPullKelvinlet, LaplacianTwistPullKelvinlet, UE::Geometry::Normalize, NumSteps, PinchKelvinlet, PullKelvinlet, UE::Geometry::TMatrix3< RealType >::Row0, UE::Geometry::TMatrix3< RealType >::Row1, Scale, ScaleKelvinlet, SharpPullKelvinlet, TimeStep, TwistKelvinlet, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
ApplyKelvinlet()
template<typename KelvinletType> void FKelvinletBrushOp::ApplyKelvinlet (const KelvinletType & Kelvinlet, const TArray< int > & VertexROI, TArray< FVector3d > & ROIPositionBuffer, const double Dt, const int NumIntegrationSteps) inline
Definition at line 729 of file KelvinletBrushOp.h.
References DisplaceKelvinlet(), and IntegrateKelvinlet().
Referenced by ApplyBrush().
DisplaceKelvinlet()
template<typename KelvinletType> void FKelvinletBrushOp::DisplaceKelvinlet (const KelvinletType & Kelvinlet, const TArray< int > & VertexROI, TArray< FVector3d > & ROIPositionBuffer) inline
Definition at line 678 of file KelvinletBrushOp.h.
References InvXForm(), Mesh, No, TArray< InElementType, InAllocatorType >::Num(), ParallelFor(), TArray< InElementType, InAllocatorType >::SetNum(), and XForm().
Referenced by ApplyKelvinlet().
ExtractTransform()
void FKelvinletBrushOp::ExtractTransform (const FMatrix & WorldToBrush) inline
Definition at line 524 of file KelvinletBrushOp.h.
References BrushToWorldMat, check, UE::Math::TMatrix< T >::Determinant(), UE::Math::TMatrix< T >::M, Translation, and WorldToBrushMat.
Referenced by ApplyBrush().
IntegrateKelvinlet()
template<typename KelvinletType> void FKelvinletBrushOp::IntegrateKelvinlet (const KelvinletType & Kelvinlet, const TArray< int > & VertexROI, TArray< FVector3d > & ROIPositionBuffer, const double Dt, const int Steps) inline
Definition at line 702 of file KelvinletBrushOp.h.
References InvXForm(), Mesh, No, TArray< InElementType, InAllocatorType >::Num(), ParallelFor(), TArray< InElementType, InAllocatorType >::SetNum(), and XForm().
Referenced by ApplyKelvinlet().
InvXForm()
FVector3d FKelvinletBrushOp::InvXForm (const FVector3d & Pos) const inline private
Definition at line 751 of file KelvinletBrushOp.h.
References BrushToWorldMat, and Translation.
Referenced by DisplaceKelvinlet(), and IntegrateKelvinlet().
XForm()
FVector3d FKelvinletBrushOp::XForm (const FVector3d & Pos) const inline private
Definition at line 745 of file KelvinletBrushOp.h.
References Translation, and WorldToBrushMat.
Referenced by DisplaceKelvinlet(), and IntegrateKelvinlet().
Field Documentation
BrushToWorldMat
FMatrix3d FKelvinletBrushOp::BrushToWorldMat
Definition at line 565 of file KelvinletBrushOp.h.
Referenced by ExtractTransform(), and InvXForm().
Mesh
const FDynamicMesh3* FKelvinletBrushOp::Mesh
Definition at line 556 of file KelvinletBrushOp.h.
Referenced by FKelvinletBrushOp(), DisplaceKelvinlet(), and IntegrateKelvinlet().
NumSteps
double FKelvinletBrushOp::NumSteps = 0.0
Definition at line 560 of file KelvinletBrushOp.h.
Referenced by ApplyBrush().
TimeStep
double FKelvinletBrushOp::TimeStep = 1.0
Definition at line 559 of file KelvinletBrushOp.h.
Referenced by ApplyBrush().
Translation
FVector3d FKelvinletBrushOp::Translation
Definition at line 566 of file KelvinletBrushOp.h.
Referenced by ExtractTransform(), InvXForm(), and XForm().
WorldToBrushMat
FMatrix3d FKelvinletBrushOp::WorldToBrushMat
Definition at line 564 of file KelvinletBrushOp.h.
Referenced by ExtractTransform(), and XForm().
The documentation for this class was generated from the following file:
KelvinletBrushOp.h