Unreal Engine 5.6 C++ API: UE::MovieScene::TMultiChannelValue< T, N > Struct Template Reference
UE::MovieScene::TMultiChannelValue< T, N > Struct Template Reference
Generic value type that supports a specific number of channels, optionally masked out.
#include "MovieSceneMultiChannelBlending.h"
Public Member Functions
TMultiChannelValue ()
Default Constructor.
template<typename OtherType>
TMultiChannelValue (std::initializer_list< OtherType > InitList)
Construction from a set of values.
T Get (uint8 Index, T Default) const
Access a value with a default.
void Increment (uint8 Index, T Value)
Increment the channel at the specified index by the specified amount.
bool IsEmpty () const
Check if this value is empty.
bool IsFull () const
Check if every channel in this value is valid.
bool IsSet (uint8 Index) const
Check whether the specified channel index is enabled.
T operator[] (uint8 Index) const
Array indexing operator - returns a channel value.
void Set (uint8 Index, T Value)
Enable and apply a value to the specified channel.
void WeightedBlend (uint8 Index, T Value, float Weight)
Do weighted blend with current value, this is an override.
Private Attributes
T Channels [N]
Channel data.
uint32 Mask
Mask signifying which indices within Channels are valid.
Detailed Description
template<typename T, uint8 N>
struct UE::MovieScene::TMultiChannelValue< T, N >
Generic value type that supports a specific number of channels, optionally masked out.
Used for blending types that can be represented as a contiguous set of numeric values. Relative, Weighted and Additive blending occurs on a per-channel basis
Definition at line 68 of file MovieSceneMultiChannelBlending.h.
Constructor & Destructor Documentation
TMultiChannelValue() [1/2]
template<typename T, uint8 N> UE::MovieScene::TMultiChannelValue< T, N >::TMultiChannelValue () inline
Default Constructor.
Definition at line 73 of file MovieSceneMultiChannelBlending.h.
References Mask.
TMultiChannelValue() [2/2]
template<typename T, uint8 N> template<typename OtherType> UE::MovieScene::TMultiChannelValue< T, N >::TMultiChannelValue (std::initializer_list< OtherType > InitList) inline
Construction from a set of values.
List size must match the number of channels.
Definition at line 79 of file MovieSceneMultiChannelBlending.h.
References Channels, check, and Mask.
Member Function Documentation
Get()
template<typename T, uint8 N> T UE::MovieScene::TMultiChannelValue< T, N >::Get (uint8 Index, T Default) const inline
Access a value with a default.
Definition at line 98 of file MovieSceneMultiChannelBlending.h.
References Channels, Default, and IsSet().
Increment()
template<typename T, uint8 N> void UE::MovieScene::TMultiChannelValue< T, N >::Increment (uint8 Index, T Value) inline
Increment the channel at the specified index by the specified amount.
Definition at line 133 of file MovieSceneMultiChannelBlending.h.
References Channels, check, IsSet(), Mask, and Value.
Referenced by UE::MovieScene::BlendValue().
IsEmpty()
template<typename T, uint8 N> bool UE::MovieScene::TMultiChannelValue< T, N >::IsEmpty () const inline
Check if this value is empty.
Definition at line 104 of file MovieSceneMultiChannelBlending.h.
References Mask.
IsFull()
template<typename T, uint8 N> bool UE::MovieScene::TMultiChannelValue< T, N >::IsFull () const inline
Check if every channel in this value is valid.
Definition at line 110 of file MovieSceneMultiChannelBlending.h.
References Mask.
IsSet()
template<typename T, uint8 N> bool UE::MovieScene::TMultiChannelValue< T, N >::IsSet (uint8 Index) const inline
Check whether the specified channel index is enabled.
Definition at line 117 of file MovieSceneMultiChannelBlending.h.
References check, and Mask.
Referenced by UE::MovieScene::BlendValue(), UE::MovieScene::BlendValue(), Get(), Increment(), operator[](), and WeightedBlend().
operator[]()
template<typename T, uint8 N> T UE::MovieScene::TMultiChannelValue< T, N >::operator[] (uint8 Index) const inline
Array indexing operator - returns a channel value.
Definition at line 91 of file MovieSceneMultiChannelBlending.h.
References Channels, checkf, IsSet(), and TEXT.
Set()
template<typename T, uint8 N> void UE::MovieScene::TMultiChannelValue< T, N >::Set (uint8 Index, T Value) inline
Enable and apply a value to the specified channel.
Definition at line 124 of file MovieSceneMultiChannelBlending.h.
References Channels, check, Mask, and Value.
Referenced by UE::MovieScene::BlendValue().
WeightedBlend()
template<typename T, uint8 N> void UE::MovieScene::TMultiChannelValue< T, N >::WeightedBlend (uint8 Index, T Value, float Weight) inline
Do weighted blend with current value, this is an override.
Definition at line 142 of file MovieSceneMultiChannelBlending.h.
References Channels, check, IsSet(), Mask, Value, and Weight.
Referenced by UE::MovieScene::BlendValue().
Field Documentation
Channels
template<typename T, uint8 N> T UE::MovieScene::TMultiChannelValue< T, N >::Channels[N] private
Channel data.
Definition at line 153 of file MovieSceneMultiChannelBlending.h.
Referenced by TMultiChannelValue(), Get(), Increment(), operator[](), Set(), and WeightedBlend().
Mask
template<typename T, uint8 N> uint32 UE::MovieScene::TMultiChannelValue< T, N >::Mask private
Mask signifying which indices within Channels are valid.
Definition at line 156 of file MovieSceneMultiChannelBlending.h.
Referenced by TMultiChannelValue(), TMultiChannelValue(), Increment(), IsEmpty(), IsFull(), IsSet(), Set(), and WeightedBlend().
The documentation for this struct was generated from the following file:
MovieSceneMultiChannelBlending.h