Unreal Engine 5.6 C++ API: FGlobalShaderMapSection Class Reference
FGlobalShaderMapSection Class Reference
#include "GlobalShader.h"
Public Member Functions
virtual RENDERCORE_API void GetShaderList (TMap< FHashedName, TShaderRef< FShader > > &OutShaders) const override
Builds a list of the shaders in a shader map.
virtual RENDERCORE_API void GetShaderPipelineList (TArray< FShaderPipelineRef > &OutShaderPipelines) const override
bool Serialize (FArchive &Ar)
RENDERCORE_API bool Serialize (FShaderSerializeContext &Ctx)
Public Member Functions inherited from TShaderMap< FGlobalShaderMapContent, FShaderMapPointerTable >
void FinalizeContent ()
const FGlobalShaderMapContent * GetContent () const
FGlobalShaderMapContent * GetMutableContent ()
const FShaderMapPointerTable & GetPointerTable () const
Public Member Functions inherited from FShaderMapBase
virtual RENDERCORE_API ~FShaderMapBase ()
RENDERCORE_API void AssignContent (TMemoryImageObject< FShaderMapContent > InContent)
void AssociateWithAsset (const FName &AssetPath)
Associates a shadermap with an asset (note: one shadermap can be used by several assets, e.g.
void AssociateWithAssets (const FShaderMapAssetPaths &AssetPaths)
virtual void DumpShaderList (FShaderListReport &Out) const
RENDERCORE_API void FinalizeContent ()
const FShaderMapAssetPaths & GetAssociatedAssets () const
const FShaderMapContent * GetContent () const
uint32 GetFrozenContentSize () const
FShaderMapContent * GetMutableContent ()
void GetOutdatedTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
EShaderPermutationFlags GetPermutationFlags () const
const FShaderMapPointerTable & GetPointerTable () const
FShaderMapResource * GetResource () const
FShaderMapResource * GetResourceChecked () const
RENDERCORE_API FShaderMapResourceCode * GetResourceCode ()
EShaderPlatform GetShaderPlatform () const
void SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API bool Serialize (FArchive &Ar, bool bInlineShaderResources, bool bLoadingCooked, bool bInlineShaderCode=false, const FName &SerializingAsset=NAME_None)
RENDERCORE_API bool Serialize (FShaderSerializeContext &Ctx)
RENDERCORE_API FString ToString () const
RENDERCORE_API void UnfreezeContent ()
Static Public Member Functions
static RENDERCORE_API FGlobalShaderMapSection * CreateFromArchive (FArchive &Ar)
static RENDERCORE_API FGlobalShaderMapSection * CreateFromCache (FShaderCacheLoadContext &Ctx)
Private Types
using Super = TShaderMap<FGlobalShaderMapContent, FShaderMapPointerTable>
Private Member Functions
FGlobalShaderMapSection ()
FGlobalShaderMapSection (EShaderPlatform InPlatform, const FHashedName &InHashedSourceFilename)
TShaderRef< FShader > GetShader (FShaderType *ShaderType, int32 PermutationId=0) const
FShaderPipelineRef GetShaderPipeline (const FShaderPipelineType *PipelineType) const
Friends
class FGlobalShaderMap
Additional Inherited Members
Protected Member Functions inherited from TShaderMap< FGlobalShaderMapContent, FShaderMapPointerTable >
virtual FShaderMapPointerTable * CreatePointerTable () const final override
virtual const FTypeLayoutDesc & GetContentTypeDesc () const final override
Protected Member Functions inherited from FShaderMapBase
RENDERCORE_API FShaderMapBase ()
RENDERCORE_API void AssignCopy (const FShaderMapBase &Source)
RENDERCORE_API void DestroyContent ()
RENDERCORE_API void InitResource ()
virtual void PostFinalizeContent ()
Detailed Description
Definition at line 140 of file GlobalShader.h.
Member Typedef Documentation
Super
using FGlobalShaderMapSection::Super = TShaderMap<FGlobalShaderMapContent, FShaderMapPointerTable> private
Definition at line 142 of file GlobalShader.h.
Constructor & Destructor Documentation
FGlobalShaderMapSection() [1/2]
FGlobalShaderMapSection::FGlobalShaderMapSection () inline private
Definition at line 161 of file GlobalShader.h.
References FShaderMapBase::AssociateWithAsset().
Referenced by CreateFromArchive(), and CreateFromCache().
FGlobalShaderMapSection() [2/2]
FGlobalShaderMapSection::FGlobalShaderMapSection (EShaderPlatform InPlatform, const FHashedName & InHashedSourceFilename) inline private
Definition at line 169 of file GlobalShader.h.
References FShaderMapBase::AssignContent().
Member Function Documentation
CreateFromArchive()
RENDERCORE_API FGlobalShaderMapSection * FGlobalShaderMapSection::CreateFromArchive (FArchive & Ar) static
References FGlobalShaderMapSection(), and Ar.
CreateFromCache()
RENDERCORE_API FGlobalShaderMapSection * FGlobalShaderMapSection::CreateFromCache (FShaderCacheLoadContext & Ctx) static
References FGlobalShaderMapSection().
GetShader()
TShaderRef< FShader > FGlobalShaderMapSection::GetShader (FShaderType * ShaderType, int32 PermutationId = 0) const private
GetShaderList()
virtual RENDERCORE_API void FGlobalShaderMapSection::GetShaderList (TMap< FHashedName, TShaderRef< FShader > > & OutShaders) const override virtual
Builds a list of the shaders in a shader map.
Key is FShaderType::TypeName
Implements FShaderMapBase.
GetShaderPipeline()
FShaderPipelineRef FGlobalShaderMapSection::GetShaderPipeline (const FShaderPipelineType * PipelineType) const private
GetShaderPipelineList()
virtual RENDERCORE_API void FGlobalShaderMapSection::GetShaderPipelineList (TArray< FShaderPipelineRef > & OutShaderPipelines) const override virtual
Implements FShaderMapBase.
Serialize() [1/2]
bool FGlobalShaderMapSection::Serialize (FArchive & Ar) inline
Definition at line 152 of file GlobalShader.h.
References Ar, bool, and Serialize().
Referenced by Serialize().
Serialize() [2/2]
RENDERCORE_API bool FGlobalShaderMapSection::Serialize (FShaderSerializeContext & Ctx)
Friends And Related Symbol Documentation
FGlobalShaderMap
friend class FGlobalShaderMap friend
Definition at line 143 of file GlobalShader.h.
References FGlobalShaderMap.
Referenced by FGlobalShaderMap.
The documentation for this class was generated from the following file:
GlobalShader.h