Unreal Engine 5.6 C++ API: AVPBookmarkActor Class Reference
AVPBookmarkActor Class Reference abstract
#include "VPBookmarkActor.h"
Private Member Functions
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostRegisterAllComponents () override
virtual void Tick (float DeltaSeconds) override
UFUNCTION () void CaptureSnapshot()
Update SnapshotTexture captured via SceneCaptureComponent.
UFUNCTION () void GenerateBookmarkName_Implementation()
UFUNCTION () void HideBookmarkSplineMeshIndicator_Implementation()
UFUNCTION () void OnActorDroppedFromCarry_Implementation()
UFUNCTION () void OnActorDroppedFromTransform_Implementation()
UFUNCTION () void OnActorSelectedForTransform_Implementation()
UFUNCTION () void OnBookmarkActivation_Implementation(UVPBookmark *Bookmark
UFUNCTION () void OnBookmarkChanged_Implementation(UVPBookmark *Bookmark)
UFUNCTION () void UpdateBookmarkColor(FLinearColor Color)
Update the mesh color and BookmarkColor variable.
UFUNCTION () void UpdateBookmarkSplineMeshIndicator_Implementation()
UFUNCTION () void UpdateTimestamp()
Update Timestamp property with current time.
UPROPERTY () bool bIsFlagged
Whether this was flagged by a user.
UPROPERTY () FDateTime Timestamp
DateTime to store creation time.
UPROPERTY () int32 FavoriteLevel=0
Favorite status set by a user.
UPROPERTY () TObjectPtr< UCineCameraComponent > CameraComponent
CineCamera.
UPROPERTY () TObjectPtr< UCineCaptureComponent2D > SceneCaptureComponent
CineCaptureComponent.
UPROPERTY () TObjectPtr< UMaterial > TextMaterial
UPROPERTY () TObjectPtr< UMaterialInstanceDynamic > DynamicMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > BookmarkMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > LabelMaterialInstance
UPROPERTY () TObjectPtr< UMaterialInterface > SplineMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > SplineMaterialInstance
UPROPERTY () TObjectPtr< USplineMeshComponent > SplineMeshComponent
Splinemesh.
UPROPERTY () TObjectPtr< UStaticMesh > BookmarkStaticMesh
UPROPERTY () TObjectPtr< UStaticMesh > SplineStaticMesh
GENERATED_BODY() public UPROPERTY () TObjectPtr< UStaticMeshComponent > BookmarkMeshComponent
Mesh Representation in the world.
UPROPERTY () TObjectPtr< UTextRenderComponent > NameTextRenderComponent
Textrender to display bookmark name.
UPROPERTY () TObjectPtr< UTexture2D > SnapshotTexture
Texture reference to store render of viewpoint.
UPROPERTY ()) bool IsHome
Bool to determine if this bookmark should be designated the home location.
UPROPERTY ()) FLinearColor BookmarkColor
Color of Bookmark in MU Session.
UPROPERTY ()) TObjectPtr< UVPBookmark > BookmarkObject
Reference to Editor Bookmark UObject.
Private Attributes
bool bActivate
FRotator BookmarkRotation
Additional Inherited Members
Public Types inherited from IInterface
typedef UInterface UClassType
Protected Member Functions inherited from IInterface
virtual ~IInterface ()
Detailed Description
Definition at line 22 of file VPBookmarkActor.h.
Member Function Documentation
PostEditChangeProperty()
virtual void AVPBookmarkActor::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostRegisterAllComponents()
virtual void AVPBookmarkActor::PostRegisterAllComponents () override private virtual
References PostRegisterAllComponents().
Referenced by PostRegisterAllComponents().
Tick()
virtual void AVPBookmarkActor::Tick (float DeltaSeconds) override private virtual
References Tick().
Referenced by Tick().
UFUNCTION() [1/11]
AVPBookmarkActor::UFUNCTION () private
Update SnapshotTexture captured via SceneCaptureComponent.
References Category, and UFUNCTION().
UFUNCTION() [2/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [3/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [4/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [6/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [7/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [8/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [9/11]
AVPBookmarkActor::UFUNCTION () private
Update the mesh color and BookmarkColor variable.
Intended for use with multiuser initialization
References Category, Color, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [10/11]
AVPBookmarkActor::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [11/11]
AVPBookmarkActor::UFUNCTION () private
Update Timestamp property with current time.
References Category, and UFUNCTION().
UPROPERTY() [1/20]
AVPBookmarkActor::UPROPERTY () private
Whether this was flagged by a user.
References Category, and UPROPERTY().
UPROPERTY() [2/20]
AVPBookmarkActor::UPROPERTY () private
DateTime to store creation time.
References Category, and UPROPERTY().
UPROPERTY() [3/20]
AVPBookmarkActor::UPROPERTY () private pure virtual
Favorite status set by a user.
References Category, and UPROPERTY().
UPROPERTY() [4/20]
AVPBookmarkActor::UPROPERTY () private
CineCamera.
References Category, and UPROPERTY().
UPROPERTY() [5/20]
AVPBookmarkActor::UPROPERTY () private
CineCaptureComponent.
References Category, and UPROPERTY().
UPROPERTY() [6/20]
AVPBookmarkActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [7/20]
AVPBookmarkActor::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [8/20]
AVPBookmarkActor::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [9/20]
AVPBookmarkActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [10/20]
AVPBookmarkActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [11/20]
AVPBookmarkActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [12/20]
AVPBookmarkActor::UPROPERTY () private
Splinemesh.
References Category, and UPROPERTY().
UPROPERTY() [13/20]
AVPBookmarkActor::UPROPERTY () private
UPROPERTY() [14/20]
AVPBookmarkActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [15/20]
GENERATED_BODY() public AVPBookmarkActor::UPROPERTY () private
Mesh Representation in the world.
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [16/20]
AVPBookmarkActor::UPROPERTY () private
Textrender to display bookmark name.
References Category, and UPROPERTY().
UPROPERTY() [17/20]
AVPBookmarkActor::UPROPERTY () private
Texture reference to store render of viewpoint.
References Category, and UPROPERTY().
UPROPERTY() [18/20]
AVPBookmarkActor::UPROPERTY () private
Bool to determine if this bookmark should be designated the home location.
References Category, meta, and UPROPERTY().
UPROPERTY() [19/20]
AVPBookmarkActor::UPROPERTY () private
Color of Bookmark in MU Session.
References Category, meta, and UPROPERTY().
UPROPERTY() [20/20]
AVPBookmarkActor::UPROPERTY () private
Reference to Editor Bookmark UObject.
References Category, meta, and UPROPERTY().
Field Documentation
bActivate
bool AVPBookmarkActor::bActivate private
Definition at line 99 of file VPBookmarkActor.h.
BookmarkRotation
FRotator AVPBookmarkActor::BookmarkRotation private
Definition at line 137 of file VPBookmarkActor.h.
The documentation for this class was generated from the following file:
VPBookmarkActor.h