Unreal Engine 5.6 C++ API: FInitBodiesHelper< bCompileStatic, InAllocatorType > Struct Template Reference
FInitBodiesHelper< bCompileStatic, InAllocatorType > Struct Template Reference
#include "BodyInstance.h"
Public Member Functions
FInitBodiesHelper (TArray< FBodyInstance *, InAllocatorType > &InBodies, TArray< FTransform, InAllocatorType > &InTransforms, class UBodySetup *InBodySetup, class UPrimitiveComponent *InComponent, class UObject *InSourceObject, FPhysScene *InRBScene, const FInitBodySpawnParams &InSpawnParams, FPhysicsAggregateHandle InAggregate, IPhysicsBodyInstanceOwner *InBodyInstanceOwner=nullptr)
FInitBodiesHelper (TArray< FBodyInstance *, InAllocatorType > &InBodies, TArray< FTransform, InAllocatorType > &InTransforms, class UBodySetup *InBodySetup, class UPrimitiveComponent *InPrimitiveComp, FPhysScene *InRBScene, const FInitBodySpawnParams &InSpawnParams, FPhysicsAggregateHandle InAggregate, IPhysicsBodyInstanceOwner *InBodyInstanceOwner=nullptr)
Public Member Functions inherited from TInitBodiesHelperBase< FDefaultAllocator >
TInitBodiesHelperBase (const TInitBodiesHelperBase &InHelper)=delete
TInitBodiesHelperBase (TArray< FBodyInstance *, FDefaultAllocator > &InBodies, TArray< FTransform, FDefaultAllocator > &InTransforms, class UBodySetup *InBodySetup, class UPrimitiveComponent *InComponent, UObject *InSourceObject, FPhysScene *InRBScene, const FInitBodySpawnParams &InSpawnParams, FPhysicsAggregateHandle InAggregate, IPhysicsBodyInstanceOwner *InBodyInstanceOwner=nullptr)
TInitBodiesHelperBase (TArray< FBodyInstance *, FDefaultAllocator > &InBodies, TArray< FTransform, FDefaultAllocator > &InTransforms, class UBodySetup *InBodySetup, class UPrimitiveComponent *InPrimitiveComp, FPhysScene *InRBScene, const FInitBodySpawnParams &InSpawnParams, FPhysicsAggregateHandle InAggregate, IPhysicsBodyInstanceOwner *InBodyInstanceOwner=nullptr)
TInitBodiesHelperBase (TInitBodiesHelperBase &&InHelper)=delete
void CreateActor_AssumesLocked (FBodyInstance *Instance, const FTransform &Transform) const
bool CreateShapes_AssumesLocked (FBodyInstance *Instance) const
bool CreateShapesAndActors ()
void InitBodies ()
FORCEINLINE bool IsStatic () const
TInitBodiesHelperBase & operator= (const TInitBodiesHelperBase &InHelper)=delete
TInitBodiesHelperBase & operator= (TInitBodiesHelperBase &&InHelper)=delete
Additional Inherited Members
Data Fields inherited from TInitBodiesHelperBase< FDefaultAllocator >
FPhysicsAggregateHandle Aggregate
bool bInstanceSimulatePhysics
TArray< FBodyInstance *, FDefaultAllocator > & Bodies
IPhysicsBodyInstanceOwner * BodyInstanceOwner
class UBodySetup * BodySetup
bool bStatic
bool DisableQueryOnlyActors
float InstanceBlendWeight
FPhysScene * PhysScene
class UPrimitiveComponent * PrimitiveComp
const USkeletalMeshComponent * SkelMeshComp
UObject * SourceObject
const FInitBodySpawnParams & SpawnParams
TArray< FTransform, FDefaultAllocator > & Transforms
Protected Member Functions inherited from TInitBodiesHelperBase< FDefaultAllocator >
void UpdateSimulatingAndBlendWeight ()
Protected Member Functions inherited from Chaos::Private::FInitBodiesHelperBaseInternal
void SetBodyInstanceExternalCollisionProfileBodySetup (FBodyInstance *BodyInstance, UBodySetup *ExternalCollisionProfileBodySetup)
void UpdateBodyInstanceSolverAsyncDeltaTime (FBodyInstance *BodyInstance)
Detailed Description
template<bool bCompileStatic, typename InAllocatorType = FDefaultAllocator>
struct FInitBodiesHelper< bCompileStatic, InAllocatorType >
Definition at line 163 of file BodyInstance.h.
Constructor & Destructor Documentation
FInitBodiesHelper() [1/2]
template<bool bCompileStatic, typename InAllocatorType = FDefaultAllocator> FInitBodiesHelper< bCompileStatic, InAllocatorType >::FInitBodiesHelper (TArray< FBodyInstance *, InAllocatorType > & InBodies, TArray< FTransform, InAllocatorType > & InTransforms, class UBodySetup * InBodySetup, class UPrimitiveComponent * InPrimitiveComp, FPhysScene * InRBScene, const FInitBodySpawnParams & InSpawnParams, FPhysicsAggregateHandle InAggregate, IPhysicsBodyInstanceOwner * InBodyInstanceOwner = nullptr)
FInitBodiesHelper() [2/2]
template<bool bCompileStatic, typename InAllocatorType = FDefaultAllocator> FInitBodiesHelper< bCompileStatic, InAllocatorType >::FInitBodiesHelper (TArray< FBodyInstance *, InAllocatorType > & InBodies, TArray< FTransform, InAllocatorType > & InTransforms, class UBodySetup * InBodySetup, class UPrimitiveComponent * InComponent, class UObject * InSourceObject, FPhysScene * InRBScene, const FInitBodySpawnParams & InSpawnParams, FPhysicsAggregateHandle InAggregate, IPhysicsBodyInstanceOwner * InBodyInstanceOwner = nullptr) inline
Definition at line 169 of file BodyInstance.h.
References TInitBodiesHelperBase< FDefaultAllocator >::TInitBodiesHelperBase(), TInitBodiesHelperBase< FDefaultAllocator >::bStatic, Cast(), TInitBodiesHelperBase< FDefaultAllocator >::PrimitiveComp, TInitBodiesHelperBase< FDefaultAllocator >::SkelMeshComp, TInitBodiesHelperBase< FDefaultAllocator >::SpawnParams, and TInitBodiesHelperBase< FDefaultAllocator >::UpdateSimulatingAndBlendWeight().
The documentation for this struct was generated from the following file:
BodyInstance.h