Unreal Engine 5.6 C++ API: Metasound::Frontend::FNodeClassInfo Struct Reference
Metasound::Frontend::FNodeClassInfo Struct Reference
FNodeClassInfo contains a minimal set of information needed to find and query node classes.
#include "MetasoundFrontendRegistryKey.h"
Public Member Functions
METASOUNDFRONTEND_API FNodeClassInfo ()
METASOUNDFRONTEND_API FNodeClassInfo (const FMetasoundFrontendClassMetadata &InMetadata)
METASOUNDFRONTEND_API FNodeClassInfo (const FMetasoundFrontendGraphClass &InClass)
METASOUNDFRONTEND_API FNodeClassInfo (const FNodeClassInfo &Other)
METASOUNDFRONTEND_API FNodeClassInfo (FNodeClassInfo &&Other)
METASOUNDFRONTEND_API FNodeClassInfo & operator= (const FNodeClassInfo &Other)
METASOUNDFRONTEND_API FNodeClassInfo & operator= (FNodeClassInfo &&Other)
UE_DEPRECATED (5.6, "Asset data no longer contained on NodeClassInfo, see AssetClass Info") METASOUNDFRONTEND_API FNodeClassInfo(const FMetasoundFrontendGraphClass &InClass
UE_DEPRECATED (5.6, "Data now characterized in asset class data") FGuid AssetClassID
UE_DEPRECATED (5.6, "Data now characterized in asset class data") FTopLevelAssetPath AssetPath
Data Fields
FMetasoundFrontendClassName ClassName
const FTopLevelAssetPath & InAssetPath
EMetasoundFrontendClassType Type = EMetasoundFrontendClassType::Invalid
FMetasoundFrontendVersionNumber Version
Detailed Description
FNodeClassInfo contains a minimal set of information needed to find and query node classes.
Definition at line 18 of file MetasoundFrontendRegistryKey.h.
Constructor & Destructor Documentation
FNodeClassInfo() [1/5]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassInfo::FNodeClassInfo ()
References UE_API.
Referenced by FNodeClassInfo(), FNodeClassInfo(), operator=(), and operator=().
FNodeClassInfo() [2/5]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassInfo::FNodeClassInfo (const FMetasoundFrontendClassMetadata & InMetadata)
References UE_API.
FNodeClassInfo() [3/5]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassInfo::FNodeClassInfo (const FMetasoundFrontendGraphClass & InClass)
References UE_API.
FNodeClassInfo() [4/5]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassInfo::FNodeClassInfo (const FNodeClassInfo & Other)
References FNodeClassInfo(), Other, and UE_API.
FNodeClassInfo() [5/5]
METASOUNDFRONTEND_API Metasound::Frontend::FNodeClassInfo::FNodeClassInfo (FNodeClassInfo && Other)
References FNodeClassInfo(), Other, and UE_API.
Member Function Documentation
operator=() [1/2]
METASOUNDFRONTEND_API FNodeClassInfo & Metasound::Frontend::FNodeClassInfo::operator= (const FNodeClassInfo & Other)
References FNodeClassInfo(), Other, and UE_API.
operator=() [2/2]
METASOUNDFRONTEND_API FNodeClassInfo & Metasound::Frontend::FNodeClassInfo::operator= (FNodeClassInfo && Other)
References FNodeClassInfo(), Other, and UE_API.
UE_DEPRECATED() [1/3]
Metasound::Frontend::FNodeClassInfo::UE_DEPRECATED (5. 6, "Asset data no longer contained on NodeClassInfo, see AssetClass Info") const &
UE_DEPRECATED() [2/3]
Metasound::Frontend::FNodeClassInfo::UE_DEPRECATED (5. 6, "Data now characterized in asset class data")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/3]
Metasound::Frontend::FNodeClassInfo::UE_DEPRECATED (5. 6, "Data now characterized in asset class data")
References UE_DEPRECATED().
Field Documentation
ClassName
FMetasoundFrontendClassName Metasound::Frontend::FNodeClassInfo::ClassName
Definition at line 21 of file MetasoundFrontendRegistryKey.h.
InAssetPath
const FTopLevelAssetPath& Metasound::Frontend::FNodeClassInfo::InAssetPath
Definition at line 57 of file MetasoundFrontendRegistryKey.h.
Type
EMetasoundFrontendClassType Metasound::Frontend::FNodeClassInfo::Type = EMetasoundFrontendClassType::Invalid
Definition at line 24 of file MetasoundFrontendRegistryKey.h.
Version
FMetasoundFrontendVersionNumber Metasound::Frontend::FNodeClassInfo::Version
Definition at line 33 of file MetasoundFrontendRegistryKey.h.
The documentation for this struct was generated from the following file:
MetasoundFrontendRegistryKey.h