Unreal Engine 5.6 C++ API: FDynamicTrailsEmitterData Struct Reference
FDynamicTrailsEmitterData Struct Reference
Dynamic emitter data for Ribbon emitters.
#include "ParticleHelper.h"
Public Member Functions
FDynamicTrailsEmitterData (const UParticleModuleRequired *RequiredModule)
~FDynamicTrailsEmitterData ()
virtual void DoBufferFill (FAsyncBufferFillData &Me) const override
virtual int32 FillIndexData (struct FAsyncBufferFillData &Data) const
virtual int32 FillVertexData (struct FAsyncBufferFillData &Data) const
virtual void GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy *Proxy, const FSceneView *View, const FSceneViewFamily &ViewFamily, int32 ViewIndex, FMeshElementCollector &Collector) const override
virtual int32 GetDynamicParameterVertexStride () const override
Get the vertex stride for the dynamic parameter rendering data.
virtual int32 GetDynamicVertexStride (ERHIFeatureLevel::Type) const override
Get the vertex stride for the dynamic rendering data.
virtual void GetIndexAllocInfo (int32 &OutNumIndices, int32 &OutStride) const override
Gets the number of indices to be allocated for this emitter.
virtual const FDynamicEmitterReplayDataBase & GetSource () const override
Returns the source data for this particle system.
virtual const FDynamicTrailsEmitterReplayData * GetSourceData () const override
Get the source replay data for this emitter.
virtual void Init (bool bInSelected)
Initialize this emitter's dynamic rendering data, called after source data has been filled in.
virtual void RenderDebug (const FParticleSystemSceneProxy *Proxy, FPrimitiveDrawInterface *PDI, const FSceneView *View, bool bCrosses) const override
Debug rendering.
Public Member Functions inherited from FDynamicSpriteEmitterDataBase
FDynamicSpriteEmitterDataBase (const UParticleModuleRequired *RequiredModule)
virtual ~FDynamicSpriteEmitterDataBase ()
void BuildViewFillData (const FParticleSystemSceneProxy *Proxy, const FSceneView *InView, int32 InVertexCount, int32 InVertexSize, int32 InDynamicParameterVertexSize, FGlobalDynamicIndexBuffer &DynamicIndexBuffer, FGlobalDynamicVertexBuffer &DynamicVertexBuffer, FGlobalDynamicVertexBufferAllocation &DynamicVertexAllocation, FGlobalDynamicIndexBufferAllocation &DynamicIndexAllocation, FGlobalDynamicVertexBufferAllocation *DynamicParameterAllocation, FAsyncBufferFillData &Data) const
Set up an buffer for async filling.
const FMaterialRenderProxy * GetMaterialRenderProxy ()
Retrieve the material render proxy to use for rendering this emitter.
void SortSpriteParticles (int32 SortMode, bool bLocalSpace, int32 ParticleCount, const uint8 *ParticleData, int32 ParticleStride, const uint16 *ParticleIndices, const FSceneView *View, const FMatrix &LocalToWorld, FParticleOrder *ParticleOrder) const
Sort the given sprite particles.
Public Member Functions inherited from FDynamicEmitterDataBase
FDynamicEmitterDataBase (const class UParticleModuleRequired *RequiredModule)
virtual ~FDynamicEmitterDataBase ()
virtual void GatherSimpleLights (const FParticleSystemSceneProxy *Proxy, const FSceneViewFamily &ViewFamily, FSimpleLightArray &OutParticleLights) const
Callback from the renderer to gather simple lights that this proxy wants renderered.
virtual const FMacroUVOverride & GetMacroUVOverride () const
Returns the current macro uv override.
void operator delete (void *RawMemory, size_t Size)
void * operator new (size_t Size)
Custom new/delete with recycling.
virtual void ReleaseRenderThreadResources (const FParticleSystemSceneProxy *InOwnerProxy)
Release the render thread resources for this emitter data.
virtual void UpdateRenderThreadResourcesEmitter (const FParticleSystemSceneProxy *InOwnerProxy)
Create the render thread resources for this emitter data.
Data Fields
uint32 bClipSourceSegement:1
uint32 bRenderGeometry:1
uint32 bRenderParticles:1
uint32 bRenderTangents:1
uint32 bRenderTessellation:1
uint32 bTextureTileDistance:1
float DistanceTessellationStepSize
int32 LastFramePreRendered
The sprite particle data.
FDynamicTrailsEmitterReplayData * SourcePointer
float TangentTessellationScalar
float TextureTileDistance
Data Fields inherited from FDynamicSpriteEmitterDataBase
uint32 bUsesDynamicParameter:1
true if the particle emitter utilizes the DynamicParameter module
const FMaterialRenderProxy * MaterialResource
The material render proxy for this emitter.
Data Fields inherited from FDynamicEmitterDataBase
uint32 bSelected:1
true if this emitter is currently selected
uint32 bValid:1
true if this emitter has valid rendering data
int32 EmitterIndex
TStatId StatID
Stat id of this object, 0 if nobody asked for it yet.
Detailed Description
Dynamic emitter data for Ribbon emitters.
Definition at line 2093 of file ParticleHelper.h.
Constructor & Destructor Documentation
FDynamicTrailsEmitterData()
FDynamicTrailsEmitterData::FDynamicTrailsEmitterData (const UParticleModuleRequired * RequiredModule) inline
Definition at line 2095 of file ParticleHelper.h.
References FDynamicSpriteEmitterDataBase::FDynamicSpriteEmitterDataBase(), bClipSourceSegement, bRenderGeometry, bRenderParticles, bRenderTangents, bRenderTessellation, bTextureTileDistance, DistanceTessellationStepSize, LastFramePreRendered, TangentTessellationScalar, and TextureTileDistance.
Referenced by FDynamicAnimTrailEmitterData::FDynamicAnimTrailEmitterData(), and FDynamicRibbonEmitterData::FDynamicRibbonEmitterData().
~FDynamicTrailsEmitterData()
FDynamicTrailsEmitterData::~FDynamicTrailsEmitterData ()
Member Function Documentation
DoBufferFill()
virtual void FDynamicTrailsEmitterData::DoBufferFill (FAsyncBufferFillData & Me) const inline override virtual
Reimplemented from FDynamicSpriteEmitterDataBase.
Definition at line 2136 of file ParticleHelper.h.
References FillIndexData(), FillVertexData(), FAsyncBufferFillData::IndexCount, FAsyncBufferFillData::IndexData, FAsyncBufferFillData::VertexCount, and FAsyncBufferFillData::VertexData.
FillIndexData()
virtual int32 FDynamicTrailsEmitterData::FillIndexData (struct FAsyncBufferFillData & Data) const virtual
Referenced by DoBufferFill().
FillVertexData()
virtual int32 FDynamicTrailsEmitterData::FillVertexData (struct FAsyncBufferFillData & Data) const virtual
Reimplemented in FDynamicAnimTrailEmitterData, and FDynamicRibbonEmitterData.
Referenced by DoBufferFill().
GetDynamicMeshElementsEmitter()
virtual void FDynamicTrailsEmitterData::GetDynamicMeshElementsEmitter (const FParticleSystemSceneProxy * Proxy, const FSceneView * View, const FSceneViewFamily & ViewFamily, int32 ViewIndex, FMeshElementCollector & Collector) const override virtual
Reimplemented from FDynamicEmitterDataBase.
GetDynamicParameterVertexStride()
virtual int32 FDynamicTrailsEmitterData::GetDynamicParameterVertexStride () const inline override virtual
Get the vertex stride for the dynamic parameter rendering data.
Reimplemented from FDynamicSpriteEmitterDataBase.
Definition at line 2158 of file ParticleHelper.h.
GetDynamicVertexStride()
virtual int32 FDynamicTrailsEmitterData::GetDynamicVertexStride (ERHIFeatureLevel::Type) const inline override virtual
Get the vertex stride for the dynamic rendering data.
Reimplemented from FDynamicSpriteEmitterDataBase.
Definition at line 2150 of file ParticleHelper.h.
GetIndexAllocInfo()
virtual void FDynamicTrailsEmitterData::GetIndexAllocInfo (int32 & OutNumIndices, int32 & OutStride) const override virtual
Gets the number of indices to be allocated for this emitter.
Reimplemented from FDynamicSpriteEmitterDataBase.
GetSource()
virtual const FDynamicEmitterReplayDataBase & FDynamicTrailsEmitterData::GetSource () const inline override virtual
Returns the source data for this particle system.
Implements FDynamicEmitterDataBase.
Definition at line 2124 of file ParticleHelper.h.
References check, and SourcePointer.
GetSourceData()
virtual const FDynamicTrailsEmitterReplayData * FDynamicTrailsEmitterData::GetSourceData () const inline override virtual
Get the source replay data for this emitter.
Reimplemented from FDynamicSpriteEmitterDataBase.
Reimplemented in FDynamicRibbonEmitterData.
Definition at line 2130 of file ParticleHelper.h.
References check, and SourcePointer.
Init()
virtual void FDynamicTrailsEmitterData::Init (bool bInSelected) virtual
Initialize this emitter's dynamic rendering data, called after source data has been filled in.
Reimplemented in FDynamicAnimTrailEmitterData, and FDynamicRibbonEmitterData.
RenderDebug()
virtual void FDynamicTrailsEmitterData::RenderDebug (const FParticleSystemSceneProxy * Proxy, FPrimitiveDrawInterface * PDI, const FSceneView * View, bool bCrosses) const override virtual
Debug rendering.
Parameters
Proxy The primitive scene proxy for the emitter.
PDI The primitive draw interface to render with
View The scene view being rendered
bCrosses If true, render Crosses at particle position; false, render points
Reimplemented from FDynamicSpriteEmitterDataBase.
Reimplemented in FDynamicAnimTrailEmitterData, and FDynamicRibbonEmitterData.
Field Documentation
bClipSourceSegement
uint32 FDynamicTrailsEmitterData::bClipSourceSegement
Definition at line 2172 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
bRenderGeometry
uint32 FDynamicTrailsEmitterData::bRenderGeometry
Definition at line 2173 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
bRenderParticles
uint32 FDynamicTrailsEmitterData::bRenderParticles
Definition at line 2174 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
bRenderTangents
uint32 FDynamicTrailsEmitterData::bRenderTangents
Definition at line 2175 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
bRenderTessellation
uint32 FDynamicTrailsEmitterData::bRenderTessellation
Definition at line 2176 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
bTextureTileDistance
uint32 FDynamicTrailsEmitterData::bTextureTileDistance
Definition at line 2177 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
DistanceTessellationStepSize
float FDynamicTrailsEmitterData::DistanceTessellationStepSize
Definition at line 2179 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
LastFramePreRendered
int32 FDynamicTrailsEmitterData::LastFramePreRendered
The sprite particle data.
Definition at line 2170 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
SourcePointer
FDynamicTrailsEmitterReplayData* FDynamicTrailsEmitterData::SourcePointer
Definition at line 2168 of file ParticleHelper.h.
Referenced by GetSource(), and GetSourceData().
TangentTessellationScalar
float FDynamicTrailsEmitterData::TangentTessellationScalar
Definition at line 2180 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
TextureTileDistance
float FDynamicTrailsEmitterData::TextureTileDistance
Definition at line 2181 of file ParticleHelper.h.
Referenced by FDynamicTrailsEmitterData().
The documentation for this struct was generated from the following file:
ParticleHelper.h