Unreal Engine 5.6 C++ API: Metasound::TVariableNode< DataType > Class Template Reference
Metasound::TVariableNode< DataType > Class Template Reference
Variable nodes initialize variable values.
#include "MetasoundVariableNodes.h"
Data Structures
class FFactory
Public Member Functions
TVariableNode (const FVertexName &InNodeName, const FGuid &InInstanceID, FLiteral &&InLiteral)
TVariableNode (FLiteral InLiteral, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
virtual TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Static Public Member Functions
static FNodeClassMetadata CreateNodeClassMetadata ()
Private Types
using FVariable = TVariable<DataType>
Static Private Member Functions
static FVertexInterface DeclareVertexInterface ()
Private Attributes
FOperatorFactorySharedRef Factory
Detailed Description
template<typename DataType>
class Metasound::TVariableNode< DataType >
Variable nodes initialize variable values.
The output of a VariableNode is a TVariable.
Definition at line 487 of file MetasoundVariableNodes.h.
Member Typedef Documentation
FVariable
template<typename DataType> using Metasound::TVariableNode< DataType >::FVariable = TVariable<DataType> private
Definition at line 489 of file MetasoundVariableNodes.h.
Constructor & Destructor Documentation
TVariableNode() [1/2]
template<typename DataType> Metasound::TVariableNode< DataType >::TVariableNode (const FVertexName & InNodeName, const FGuid & InInstanceID, FLiteral && InLiteral) inline
Definition at line 525 of file MetasoundVariableNodes.h.
References TVariableNode(), CreateNodeClassMetadata(), DeclareVertexInterface(), MakeShared(), and MoveTemp().
Referenced by TVariableNode().
TVariableNode() [2/2]
template<typename DataType> Metasound::TVariableNode< DataType >::TVariableNode (FLiteral InLiteral, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata) inline
Definition at line 530 of file MetasoundVariableNodes.h.
References Metasound::FBasicNode::FBasicNode(), Factory, MakeShared(), and MoveTemp().
Member Function Documentation
CreateNodeClassMetadata()
template<typename DataType> FNodeClassMetadata Metasound::TVariableNode< DataType >::CreateNodeClassMetadata () inline static
Definition at line 536 of file MetasoundVariableNodes.h.
References DeclareVertexInterface(), Metasound::VariableNames::GetVariableNodeClassName(), Info, LOCTEXT, Metasound::PluginAuthor, and Metasound::PluginNodeMissingPrompt.
Referenced by TVariableNode(), and Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
DeclareVertexInterface()
template<typename DataType> FVertexInterface Metasound::TVariableNode< DataType >::DeclareVertexInterface () inline static private
Definition at line 510 of file MetasoundVariableNodes.h.
References METASOUND_GET_PARAM_NAME.
Referenced by TVariableNode(), and CreateNodeClassMetadata().
GetDefaultOperatorFactory()
template<typename DataType> virtual TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > Metasound::TVariableNode< DataType >::GetDefaultOperatorFactory () const inline override virtual
Return a reference to the default operator factory.
Implements Metasound::INode.
Definition at line 557 of file MetasoundVariableNodes.h.
References Factory.
Field Documentation
Factory
template<typename DataType> FOperatorFactorySharedRef Metasound::TVariableNode< DataType >::Factory private
Definition at line 564 of file MetasoundVariableNodes.h.
Referenced by TVariableNode(), and GetDefaultOperatorFactory().
The documentation for this class was generated from the following file:
MetasoundVariableNodes.h