Unreal Engine 5.6 C++ API: ASceneCapture2D Class Reference
ASceneCapture2D Class Reference
#include "SceneCapture2D.h"
Public Member Functions
virtual void CalcCamera (float DeltaTime, struct FMinimalViewInfo &OutMinimalViewInfo) override
class USceneCaptureComponent2D * GetCaptureComponent2D () const
Returns CaptureComponent2D subobject.
UFUNCTION () void OnInterpToggle(bool bEnable)
Scene capture component.
Public Member Functions inherited from ASceneCapture
virtual void PostLoad () override
virtual void Serialize (FArchive &Ar) override
UE_DEPRECATED (4.22, "SceneCapture's mesh and frustum components should now be accessed through the SceneCaptureComponent instead of the Actor") class UStaticMeshComponent *GetMeshComp() const
Returns MeshComp subobject.
Detailed Description
Definition at line 16 of file SceneCapture2D.h.
Member Function Documentation
CalcCamera()
virtual void ASceneCapture2D::CalcCamera (float DeltaTime, struct FMinimalViewInfo & OutMinimalViewInfo) override virtual
References CalcCamera(), and DeltaTime.
Referenced by CalcCamera().
GetCaptureComponent2D()
class USceneCaptureComponent2D * ASceneCapture2D::GetCaptureComponent2D () const inline
Returns CaptureComponent2D subobject.
Definition at line 32 of file SceneCapture2D.h.
References GetCaptureComponent2D().
Referenced by GetCaptureComponent2D().
UFUNCTION()
ASceneCapture2D::UFUNCTION ()
Scene capture component.
References Category.
The documentation for this class was generated from the following file:
SceneCapture2D.h