Unreal Engine 5.6 C++ API: MotionTrajectoryTypes.h File Reference
MotionTrajectoryTypes.h File Reference
#include "Algo/BinarySearch.h"
#include "UObject/ObjectMacros.h"
#include "MotionTrajectoryTypes.generated.h"
Functions
bool IsZeroSample () const
PRAGMA_DISABLE_DEPRECATION_WARNINGS FTrajectorySample Lerp (const FTrajectorySample &Sample, float Alpha) const
PRAGMA_ENABLE_DEPRECATION_WARNINGS void PrependOffset (const FTransform DeltaTransform, float DeltaSeconds)
FTrajectorySample SmoothInterp (const FTrajectorySample &PrevSample, const FTrajectorySample &Sample, const FTrajectorySample &NextSample, float Alpha) const
void TransformReferenceFrame (const FTransform DeltaTransform)
UPROPERTY () FTransform Transform
USTRUCT () struct UE_DEPRECATED(5.6
Variables
FTrajectorySample has been deprecated Instead use FTransformTrajectorySample FTrajectorySample
Function Documentation
IsZeroSample()
bool IsZeroSample () const
References IsZeroSample().
Referenced by IsZeroSample().
Lerp()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FTrajectorySample Lerp (const FTrajectorySample & Sample, float Alpha) const
References Alpha, FTrajectorySample, and Lerp().
Referenced by SWindowTitleBar::GetFlashValue(), Lerp(), UENUM(), and UENUM().
PrependOffset()
PRAGMA_ENABLE_DEPRECATION_WARNINGS void PrependOffset (const FTransform DeltaTransform, float DeltaSeconds)
References PrependOffset().
Referenced by PrependOffset().
SmoothInterp()
FTrajectorySample SmoothInterp (const FTrajectorySample & PrevSample, const FTrajectorySample & Sample, const FTrajectorySample & NextSample, float Alpha) const
References Alpha, FTrajectorySample, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and SmoothInterp().
Referenced by SmoothInterp().
TransformReferenceFrame()
void TransformReferenceFrame (const FTransform DeltaTransform)
References TransformReferenceFrame().
Referenced by TransformReferenceFrame().
UPROPERTY()
UPROPERTY ()
References Category, FVector, PRAGMA_DISABLE_DEPRECATION_WARNINGS, Transform, and UPROPERTY.
USTRUCT()
USTRUCT ()
References BlueprintType, and Category.
Variable Documentation
FTrajectorySample
FTrajectorySample has been deprecated Instead use FTransformTrajectorySample FTrajectorySample
Initial value:
{
     GENERATED_BODY()
     UPROPERTY()
    float AccumulatedSeconds = 0.f
Definition at line 10 of file MotionTrajectoryTypes.h.
Referenced by Lerp(), and SmoothInterp().