Unreal Engine 5.6 C++ API: LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic Class Reference
LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic Class Reference
Public Member Functions
bool compare_exchange_strong (FPackedData &Expected, FPackedData Desired, std::memory_order Order)
bool compare_exchange_strong (FPackedData &Expected, FPackedData Desired, std::memory_order Success, std::memory_order Failure)
ETaskState fetch_or (ETaskState State, std::memory_order Order)
FPackedData load (std::memory_order Order) const
void store (const FPackedData &Expected, std::memory_order Order)
Private Attributes
std::atomic< uintptr_t > PackedData { FPackedData().PackedData }
Detailed Description
Definition at line 264 of file Async/Fundamental/Task.h.
Member Function Documentation
compare_exchange_strong() [1/2]
bool LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::compare_exchange_strong (FPackedData & Expected, FPackedData Desired, std::memory_order Order) inline
Definition at line 279 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::PackedData, and PackedData.
compare_exchange_strong() [2/2]
bool LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::compare_exchange_strong (FPackedData & Expected, FPackedData Desired, std::memory_order Success, std::memory_order Failure) inline
Definition at line 274 of file Async/Fundamental/Task.h.
References Failure, LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::PackedData, PackedData, and Success.
fetch_or()
ETaskState LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::fetch_or (ETaskState State, std::memory_order Order) inline
Definition at line 269 of file Async/Fundamental/Task.h.
References PackedData, and State.
load()
FPackedData LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::load (std::memory_order Order) const inline
Definition at line 284 of file Async/Fundamental/Task.h.
References PackedData.
store()
void LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::store (const FPackedData & Expected, std::memory_order Order) inline
Definition at line 289 of file Async/Fundamental/Task.h.
References LowLevelTasks::Tasks_Impl::FTaskBase::FPackedData::PackedData, and PackedData.
Field Documentation
PackedData
std::atomic<uintptr_t> LowLevelTasks::Tasks_Impl::FTaskBase::FPackedDataAtomic::PackedData { FPackedData().PackedData } private
Definition at line 266 of file Async/Fundamental/Task.h.
Referenced by compare_exchange_strong(), compare_exchange_strong(), fetch_or(), load(), and store().
The documentation for this class was generated from the following file:
Async/Fundamental/Task.h