Unreal Engine 5.6 C++ API: UParticleModuleLocationBoneSocket Class Reference
UParticleModuleLocationBoneSocket Class Reference
#include "ParticleModuleLocationBoneSocket.h"
Private Member Functions
virtual void AutoPopulateInstanceProperties (UParticleSystemComponent *PSysComp) override
virtual bool CanTickInAnyThread () override
virtual void FinalUpdate (const FUpdateContext &Context) override
GENERATED_UCLASS_BODY () UPROPERTY() TEnumAsByte< enum ELocationBoneSocketSource > SourceType
Whether the module uses Bones or Sockets for locations.
bool GetBoneInfoForSourceIndex (FModuleLocationBoneSocketInstancePayload *InstancePayload, USkeletalMeshComponent *SourceComponent, int32 SourceIndex, FMatrix &OutBoneMatrix, FVector &OutOffset) const
virtual bool GetCustomMenuEntryDisplayString (int32 InEntryIndex, FString &OutDisplayString) const override
int32 GetMaxSourceIndex (FModuleLocationBoneSocketInstancePayload *Payload, USkeletalMeshComponent *SourceComponent) const
virtual int32 GetNumberOfCustomMenuOptions () const override
bool GetParticleLocation (FModuleLocationBoneSocketInstancePayload *InstancePayload, FParticleEmitterInstance *Owner, USkeletalMeshComponent *InSkelMeshComponent, int32 InBoneSocketIndex, FVector &OutPosition, FQuat *OutRotation)
Retrieve the position for the given socket index.
void GetSkeletalMeshComponentSource (const FContext &Context, FModuleLocationBoneSocketInstancePayload *InstancePayload)
Retrieve the skeletal mesh component source to use for the current emitter instance.
bool GetSocketInfoForSourceIndex (FModuleLocationBoneSocketInstancePayload *InstancePayload, USkeletalMeshComponent *SourceComponent, int32 SourceIndex, USkeletalMeshSocket *&OutSocket, FVector &OutOffset) const
FORCEINLINE bool InheritingBoneVelocity () const
virtual bool PerformCustomMenuEntry (int32 InEntryIndex) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
virtual uint32 PrepPerInstanceBlock (FParticleEmitterInstance *Owner, void *InstData) override
void RegeneratePreSelectedIndices (FModuleLocationBoneSocketInstancePayload *InstancePayload, USkeletalMeshComponent *SourceComponent, FRandomStream &InRandomStream)
virtual uint32 RequiredBytes (UParticleModuleTypeDataBase *TypeData) override
virtual uint32 RequiredBytesPerInstance () override
int32 SelectNextSpawnIndex (FModuleLocationBoneSocketInstancePayload *InstancePayload, USkeletalMeshComponent *SourceComponent, FRandomStream &InRandomStream)
Selects the next socket or bone index to spawn from.
void SetSourceIndexMode ()
virtual void Spawn (const FSpawnContext &Context) override
virtual bool TouchesMeshRotation () const override
virtual void Update (const FUpdateContext &Context) override
void UpdatePrevBoneLocationsAndVelocities (FModuleLocationBoneSocketInstancePayload *InstancePayload, USkeletalMeshComponent *SourceComponent, float DeltaTime)
UPROPERTY() uint32 bUpdatePositionEachFrame UPROPERTY() uint32 bOrientMeshEmitters UPROPERTY() uint32 bInheritBoneVelocity UPROPERTY () float InheritVelocityScale
If true, update the particle locations each frame with that of the bone/socket.
UPROPERTY () FName SkelMeshActorParamName
The parameter name of the skeletal mesh actor that supplies the SkelMeshComponent for in-game.
UPROPERTY () FVector UniversalOffset
An offset to apply to each bone/socket.
UPROPERTY () TArray< struct FLocationBoneSocketInfo > SourceLocations
The name(s) of the bone/socket(s) to position at.
UPROPERTY () TEnumAsByte< enum ELocationBoneSocketSelectionMethod > SelectionMethod
The method by which to select the bone/socket to spawn at.
UPROPERTY ()) int32 NumPreSelectedIndices
When we have no source locations and we need to track bone velocities due to bInheritBoneVelocity, we pre select a set of bones to use each frame.
Static Private Member Functions
static void ValidateLODLevels (UParticleEmitter *Emitter, int32 iModule)
Validate that all LOD levels will not have issues with indexing into SourceLocations.
Private Attributes
EBoneSocketSourceIndexMode SourceIndexMode
How particle SourceIndex should be interpreted.
Detailed Description
Definition at line 64 of file ParticleModuleLocationBoneSocket.h.
Member Function Documentation
AutoPopulateInstanceProperties()
virtual void UParticleModuleLocationBoneSocket::AutoPopulateInstanceProperties (UParticleSystemComponent * PSysComp) override private virtual
CanTickInAnyThread()
virtual bool UParticleModuleLocationBoneSocket::CanTickInAnyThread () inline override private virtual
Definition at line 143 of file ParticleModuleLocationBoneSocket.h.
FinalUpdate()
virtual void UParticleModuleLocationBoneSocket::FinalUpdate (const FUpdateContext & Context) override private virtual
GENERATED_UCLASS_BODY()
UParticleModuleLocationBoneSocket::GENERATED_UCLASS_BODY () private
Whether the module uses Bones or Sockets for locations.
BONESOCKETSOURCE_Bones - Use Bones as the source locations. BONESOCKETSOURCE_Sockets - Use Sockets as the source locations.
References Category, and UPROPERTY().
GetBoneInfoForSourceIndex()
bool UParticleModuleLocationBoneSocket::GetBoneInfoForSourceIndex (FModuleLocationBoneSocketInstancePayload * InstancePayload, USkeletalMeshComponent * SourceComponent, int32 SourceIndex, FMatrix & OutBoneMatrix, FVector & OutOffset) const private
References FVector.
GetCustomMenuEntryDisplayString()
virtual bool UParticleModuleLocationBoneSocket::GetCustomMenuEntryDisplayString (int32 InEntryIndex, FString & OutDisplayString) const override private virtual
GetMaxSourceIndex()
int32 UParticleModuleLocationBoneSocket::GetMaxSourceIndex (FModuleLocationBoneSocketInstancePayload * Payload, USkeletalMeshComponent * SourceComponent) const private
GetNumberOfCustomMenuOptions()
virtual int32 UParticleModuleLocationBoneSocket::GetNumberOfCustomMenuOptions () const override private virtual
GetParticleLocation()
bool UParticleModuleLocationBoneSocket::GetParticleLocation (FModuleLocationBoneSocketInstancePayload * InstancePayload, FParticleEmitterInstance * Owner, USkeletalMeshComponent * InSkelMeshComponent, int32 InBoneSocketIndex, FVector & OutPosition, FQuat * OutRotation) private
Retrieve the position for the given socket index.
Parameters
Owner The particle emitter instance that is being setup
InSkelMeshComponent The skeletal mesh component to use as the source
InBoneSocketIndex The index of the bone/socket of interest
OutPosition The position for the particle location
OutRotation Optional orientation for the particle (mesh emitters)
Returns
bool true if successful, false if not
References FVector, and Owner.
GetSkeletalMeshComponentSource()
void UParticleModuleLocationBoneSocket::GetSkeletalMeshComponentSource (const FContext & Context, FModuleLocationBoneSocketInstancePayload * InstancePayload) private
Retrieve the skeletal mesh component source to use for the current emitter instance.
Parameters
Owner The particle emitter instance that is being setup
Returns
USkeletalMeshComponent* The skeletal mesh component to use as the source
GetSocketInfoForSourceIndex()
bool UParticleModuleLocationBoneSocket::GetSocketInfoForSourceIndex (FModuleLocationBoneSocketInstancePayload * InstancePayload, USkeletalMeshComponent * SourceComponent, int32 SourceIndex, USkeletalMeshSocket *& OutSocket, FVector & OutOffset) const private
References FVector.
InheritingBoneVelocity()
FORCEINLINE bool UParticleModuleLocationBoneSocket::InheritingBoneVelocity () const inline private
Definition at line 188 of file ParticleModuleLocationBoneSocket.h.
References FORCEINLINE.
PerformCustomMenuEntry()
virtual bool UParticleModuleLocationBoneSocket::PerformCustomMenuEntry (int32 InEntryIndex) override private virtual
PostEditChangeProperty()
virtual void UParticleModuleLocationBoneSocket::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostLoad()
virtual void UParticleModuleLocationBoneSocket::PostLoad () override private virtual
PrepPerInstanceBlock()
virtual uint32 UParticleModuleLocationBoneSocket::PrepPerInstanceBlock (FParticleEmitterInstance * Owner, void * InstData) override private virtual
References Owner.
RegeneratePreSelectedIndices()
void UParticleModuleLocationBoneSocket::RegeneratePreSelectedIndices (FModuleLocationBoneSocketInstancePayload * InstancePayload, USkeletalMeshComponent * SourceComponent, FRandomStream & InRandomStream) private
RequiredBytes()
virtual uint32 UParticleModuleLocationBoneSocket::RequiredBytes (UParticleModuleTypeDataBase * TypeData) override private virtual
RequiredBytesPerInstance()
virtual uint32 UParticleModuleLocationBoneSocket::RequiredBytesPerInstance () override private virtual
SelectNextSpawnIndex()
int32 UParticleModuleLocationBoneSocket::SelectNextSpawnIndex (FModuleLocationBoneSocketInstancePayload * InstancePayload, USkeletalMeshComponent * SourceComponent, FRandomStream & InRandomStream) private
Selects the next socket or bone index to spawn from.
SetSourceIndexMode()
void UParticleModuleLocationBoneSocket::SetSourceIndexMode () private
Spawn()
virtual void UParticleModuleLocationBoneSocket::Spawn (const FSpawnContext & Context) override private virtual
TouchesMeshRotation()
virtual bool UParticleModuleLocationBoneSocket::TouchesMeshRotation () const inline override private virtual
Definition at line 141 of file ParticleModuleLocationBoneSocket.h.
Update()
virtual void UParticleModuleLocationBoneSocket::Update (const FUpdateContext & Context) override private virtual
UpdatePrevBoneLocationsAndVelocities()
void UParticleModuleLocationBoneSocket::UpdatePrevBoneLocationsAndVelocities (FModuleLocationBoneSocketInstancePayload * InstancePayload, USkeletalMeshComponent * SourceComponent, float DeltaTime) private
References DeltaTime.
UPROPERTY() [1/6]
UPROPERTY() uint32 bUpdatePositionEachFrame UPROPERTY() uint32 bOrientMeshEmitters UPROPERTY() uint32 bInheritBoneVelocity UParticleModuleLocationBoneSocket::UPROPERTY () private
If true, update the particle locations each frame with that of the bone/socket.
If true, rotate mesh emitter meshes to orient w/ the socket. Currently does nothing. If true, particles inherit the associated bone velocity when spawned A scale on how much of the bone's velocity a particle will inherit.
References Category, and UPROPERTY().
UPROPERTY() [2/6]
UParticleModuleLocationBoneSocket::UPROPERTY () private
The parameter name of the skeletal mesh actor that supplies the SkelMeshComponent for in-game.
References Category, and UPROPERTY().
UPROPERTY() [3/6]
UParticleModuleLocationBoneSocket::UPROPERTY () private
An offset to apply to each bone/socket.
References Category, FVector, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/6]
UParticleModuleLocationBoneSocket::UPROPERTY () private
The name(s) of the bone/socket(s) to position at.
If this is empty, the module will attempt to spawn from all bones or sockets.
References Category, SourceLocations, and UPROPERTY().
UPROPERTY() [5/6]
UParticleModuleLocationBoneSocket::UPROPERTY () private
The method by which to select the bone/socket to spawn at.
SEL_Sequential - loop through the bone/socket array in order SEL_Random - randomly select a bone/socket from the array
References Category, and UPROPERTY().
UPROPERTY() [6/6]
UParticleModuleLocationBoneSocket::UPROPERTY () private
When we have no source locations and we need to track bone velocities due to bInheritBoneVelocity, we pre select a set of bones to use each frame.
This property determines how big the list is. Too low and the randomness of selection may suffer, too high and memory will be wasted.
References Category, meta, and UPROPERTY().
ValidateLODLevels()
void UParticleModuleLocationBoneSocket::ValidateLODLevels (UParticleEmitter * Emitter, int32 iModule) static private
Validate that all LOD levels will not have issues with indexing into SourceLocations.
Field Documentation
SourceIndexMode
EBoneSocketSourceIndexMode UParticleModuleLocationBoneSocket::SourceIndexMode private
How particle SourceIndex should be interpreted.
Definition at line 131 of file ParticleModuleLocationBoneSocket.h.
The documentation for this class was generated from the following file:
ParticleModuleLocationBoneSocket.h