Unreal Engine 5.6 C++ API: UE::Tick::FActiveSyncWorkHandle Struct Reference
UE::Tick::FActiveSyncWorkHandle Struct Reference final
Handle pointing to a FActiveSyncPoint that can be used to reserve or request work to execute as part of that sync point.
#include "TaskSyncManager.h"
Public Member Functions
FActiveSyncWorkHandle ()=default
FActiveSyncWorkHandle (const FActiveSyncWorkHandle &)=delete
FActiveSyncWorkHandle (FActiveSyncWorkHandle &&)=default
~FActiveSyncWorkHandle ()
bool AbandonWork ()
Abandon any requested or reserved work and return to how it was at initial registration.
FTickFunction * GetDependencyTickFunction ()
Returns a raw pointer to the tick function that implements this handle which can be passed into AddPrerequisite.
bool HasRequestedWork () const
True if this handle has been used to request work.
bool HasReservedWork () const
True if this handle has been used to reserve work.
bool IsValid () const
True if this points to a real sync point.
FActiveSyncWorkHandle & operator= (const FActiveSyncWorkHandle &)=delete
FActiveSyncWorkHandle & operator= (FActiveSyncWorkHandle &&)=default
bool RequestWork (FTickFunction *FunctionToExecute, ESyncWorkRepetition Repeat)
Requests that a tick function be executed by the sync point, this fills any reservations and may trigger tasks.
bool ReserveFutureWork (ESyncWorkRepetition Repeat)
Request to reserve work using this handle, which must be filled to complete the frame's tasks.
bool Reset ()
Completely reset this handle, which will abandon work and prevent any future use.
Private Member Functions
int32 GetIndex () const
Get index as signed int.
void ResetInternal ()
Reset a handle to point to nothing.
Private Attributes
uint32 bWorkRequested: 1 = 0
True if this may represent active requested work.
uint32 bWorkReserved: 1 = 0
True if this may represent active reserved work.
TSharedPtr< struct FActiveSyncPoint > SyncPoint
The sync point this handle is from.
uint32 WorkIndex: 24 = 0
Index into the ActiveWork array.
Static Private Attributes
static constexpr uint32 MaxWorkIndex = (2 << 24) - 1
Max amount of work per sync point.
Friends
struct FActiveSyncPoint
class FTaskSyncManager
Detailed Description
Handle pointing to a FActiveSyncPoint that can be used to reserve or request work to execute as part of that sync point.
These handles cannot be copied, but can be safely moved between threads and will cancel all reservations and requests on destruction.
Definition at line 403 of file TaskSyncManager.h.
Constructor & Destructor Documentation
FActiveSyncWorkHandle() [1/3]
UE::Tick::FActiveSyncWorkHandle::FActiveSyncWorkHandle () default
Referenced by FActiveSyncWorkHandle(), FActiveSyncWorkHandle(), operator=(), and operator=().
~FActiveSyncWorkHandle()
UE::Tick::FActiveSyncWorkHandle::~FActiveSyncWorkHandle ()
FActiveSyncWorkHandle() [2/3]
UE::Tick::FActiveSyncWorkHandle::FActiveSyncWorkHandle (FActiveSyncWorkHandle &&) default
References FActiveSyncWorkHandle().
FActiveSyncWorkHandle() [3/3]
UE::Tick::FActiveSyncWorkHandle::FActiveSyncWorkHandle (const FActiveSyncWorkHandle &) delete
References FActiveSyncWorkHandle().
Member Function Documentation
AbandonWork()
bool UE::Tick::FActiveSyncWorkHandle::AbandonWork ()
Abandon any requested or reserved work and return to how it was at initial registration.
This clears HasReserved/HasRequested, but does not invalidate the handle. Return true if there was any requested/reserved work to abandon.
GetDependencyTickFunction()
FTickFunction * UE::Tick::FActiveSyncWorkHandle::GetDependencyTickFunction ()
Returns a raw pointer to the tick function that implements this handle which can be passed into AddPrerequisite.
This is only valid to call on the game thread and should not be cached.
GetIndex()
int32 UE::Tick::FActiveSyncWorkHandle::GetIndex () const inline private
Get index as signed int.
Definition at line 469 of file TaskSyncManager.h.
References WorkIndex.
HasRequestedWork()
bool UE::Tick::FActiveSyncWorkHandle::HasRequestedWork () const
True if this handle has been used to request work.
This will still be true until work is abandoned
HasReservedWork()
bool UE::Tick::FActiveSyncWorkHandle::HasReservedWork () const
True if this handle has been used to reserve work.
This will still be true until work is abandoned
IsValid()
bool UE::Tick::FActiveSyncWorkHandle::IsValid () const
True if this points to a real sync point.
operator=() [1/2]
FActiveSyncWorkHandle & UE::Tick::FActiveSyncWorkHandle::operator= (const FActiveSyncWorkHandle &) delete
References FActiveSyncWorkHandle().
operator=() [2/2]
FActiveSyncWorkHandle & UE::Tick::FActiveSyncWorkHandle::operator= (FActiveSyncWorkHandle &&) default
References FActiveSyncWorkHandle().
RequestWork()
bool UE::Tick::FActiveSyncWorkHandle::RequestWork (FTickFunction * FunctionToExecute, ESyncWorkRepetition Repeat)
Requests that a tick function be executed by the sync point, this fills any reservations and may trigger tasks.
If EveryFrame is passed in, it will request the same function every frame until it is abandoned.
ReserveFutureWork()
bool UE::Tick::FActiveSyncWorkHandle::ReserveFutureWork (ESyncWorkRepetition Repeat)
Request to reserve work using this handle, which must be filled to complete the frame's tasks.
If EveryFrame is passed in, it will reserve work at the start of every frame that must be requested or abandoned.
Reset()
bool UE::Tick::FActiveSyncWorkHandle::Reset ()
Completely reset this handle, which will abandon work and prevent any future use.
This returns true if it was valid before
ResetInternal()
void UE::Tick::FActiveSyncWorkHandle::ResetInternal () inline private
Reset a handle to point to nothing.
Definition at line 475 of file TaskSyncManager.h.
References bWorkRequested, bWorkReserved, SyncPoint, and WorkIndex.
Friends And Related Symbol Documentation
FActiveSyncPoint
friend struct FActiveSyncPoint friend
Definition at line 483 of file TaskSyncManager.h.
References FActiveSyncPoint.
Referenced by FActiveSyncPoint.
FTaskSyncManager
friend class FTaskSyncManager friend
Definition at line 484 of file TaskSyncManager.h.
References FTaskSyncManager.
Referenced by FTaskSyncManager.
Field Documentation
bWorkRequested
uint32 UE::Tick::FActiveSyncWorkHandle::bWorkRequested private
True if this may represent active requested work.
Definition at line 466 of file TaskSyncManager.h.
Referenced by ResetInternal().
bWorkReserved
uint32 UE::Tick::FActiveSyncWorkHandle::bWorkReserved private
True if this may represent active reserved work.
Definition at line 463 of file TaskSyncManager.h.
Referenced by ResetInternal().
MaxWorkIndex
uint32 UE::Tick::FActiveSyncWorkHandle::MaxWorkIndex = (2 << 24) - 1 static constexpr private
Max amount of work per sync point.
Definition at line 460 of file TaskSyncManager.h.
SyncPoint
TSharedPtr<struct FActiveSyncPoint> UE::Tick::FActiveSyncWorkHandle::SyncPoint private
The sync point this handle is from.
Definition at line 454 of file TaskSyncManager.h.
Referenced by ResetInternal().
WorkIndex
uint32 UE::Tick::FActiveSyncWorkHandle::WorkIndex private
Index into the ActiveWork array.
Definition at line 457 of file TaskSyncManager.h.
Referenced by GetIndex(), and ResetInternal().
The documentation for this struct was generated from the following file:
TaskSyncManager.h