Unreal Engine 5.6 C++ API: TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit > Struct Template Reference
TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit > Struct Template Reference
#include "CachedOSPageAllocator.h"
Public Member Functions
TCachedOSPageAllocator ()
FORCEINLINE void * Allocate (SIZE_T Size, uint32 AllocationHint=0, UE::FPlatformRecursiveMutex *Mutex=nullptr)
void DumpAllocatorStats (class FOutputDevice &Ar)
void Free (void *Ptr, SIZE_T Size, UE::FPlatformRecursiveMutex *Mutex=nullptr, bool ThreadIsTimeCritical=false)
void FreeAll (UE::FPlatformRecursiveMutex *Mutex=nullptr)
uint64 GetCachedFreeTotal () const
uint64 GetCachedImmediatelyFreeable () const
bool IsOSAllocation (SIZE_T Size)
void Refresh ()
void UpdateStats ()
Private Attributes
SIZE_T CachedTotal
FFreePageBlock FreedPageBlocks [NumCacheBlocks *2]
uint32 FreedPageBlocksNum
Additional Inherited Members
Private Member Functions inherited from FCachedOSPageAllocator
void * AllocateImpl (SIZE_T Size, uint32 CachedByteLimit, FFreePageBlock *First, FFreePageBlock *Last, uint32 &FreedPageBlocksNum, SIZE_T &CachedTotal, UE::FPlatformRecursiveMutex *Mutex)
void FreeAllImpl (FFreePageBlock *First, uint32 &FreedPageBlocksNum, SIZE_T &CachedTotal, UE::FPlatformRecursiveMutex *Mutex)
void FreeImpl (void *Ptr, SIZE_T Size, uint32 NumCacheBlocks, uint32 CachedByteLimit, FFreePageBlock *First, uint32 &FreedPageBlocksNum, SIZE_T &CachedTotal, UE::FPlatformRecursiveMutex *Mutex, bool ThreadIsTimeCritical)
Static Private Member Functions inherited from FCachedOSPageAllocator
static bool IsOSAllocation (SIZE_T Size, uint32 CachedByteLimit)
Detailed Description
template<uint32 NumCacheBlocks, uint32 CachedByteLimit>
struct TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >
Definition at line 36 of file CachedOSPageAllocator.h.
Constructor & Destructor Documentation
TCachedOSPageAllocator()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::TCachedOSPageAllocator () inline
Definition at line 38 of file CachedOSPageAllocator.h.
References CachedTotal, and FreedPageBlocksNum.
Member Function Documentation
Allocate()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> FORCEINLINE void * TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::Allocate (SIZE_T Size, uint32 AllocationHint = 0, UE::FPlatformRecursiveMutex * Mutex = nullptr) inline
Definition at line 44 of file CachedOSPageAllocator.h.
References FCachedOSPageAllocator::AllocateImpl(), CachedTotal, FORCEINLINE, FreedPageBlocks, FreedPageBlocksNum, and TSequenceHistory< HistorySize >::Size.
DumpAllocatorStats()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> void TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::DumpAllocatorStats (class FOutputDevice & Ar) inline
Definition at line 83 of file CachedOSPageAllocator.h.
References Ar, GetCachedFreeTotal(), and TEXT.
Free()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> void TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::Free (void * Ptr, SIZE_T Size, UE::FPlatformRecursiveMutex * Mutex = nullptr, bool ThreadIsTimeCritical = false) inline
Definition at line 49 of file CachedOSPageAllocator.h.
References CachedTotal, FreedPageBlocks, FreedPageBlocksNum, FCachedOSPageAllocator::FreeImpl(), and TSequenceHistory< HistorySize >::Size.
FreeAll()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> void TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::FreeAll (UE::FPlatformRecursiveMutex * Mutex = nullptr) inline
Definition at line 54 of file CachedOSPageAllocator.h.
References CachedTotal, FCachedOSPageAllocator::FreeAllImpl(), FreedPageBlocks, and FreedPageBlocksNum.
GetCachedFreeTotal()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> uint64 TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::GetCachedFreeTotal () const inline
Definition at line 68 of file CachedOSPageAllocator.h.
References CachedTotal.
Referenced by DumpAllocatorStats(), and GetCachedImmediatelyFreeable().
GetCachedImmediatelyFreeable()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> uint64 TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::GetCachedImmediatelyFreeable () const inline
Definition at line 73 of file CachedOSPageAllocator.h.
References GetCachedFreeTotal().
IsOSAllocation()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> bool TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::IsOSAllocation (SIZE_T Size) inline
Definition at line 78 of file CachedOSPageAllocator.h.
References FCachedOSPageAllocator::IsOSAllocation(), and TSequenceHistory< HistorySize >::Size.
Refresh()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> void TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::Refresh () inline
Definition at line 60 of file CachedOSPageAllocator.h.
UpdateStats()
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> void TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::UpdateStats () inline
Definition at line 64 of file CachedOSPageAllocator.h.
Field Documentation
CachedTotal
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> SIZE_T TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::CachedTotal private
Definition at line 90 of file CachedOSPageAllocator.h.
Referenced by TCachedOSPageAllocator(), Allocate(), Free(), FreeAll(), and GetCachedFreeTotal().
FreedPageBlocks
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> FFreePageBlock TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::FreedPageBlocks[NumCacheBlocks *2] private
Definition at line 89 of file CachedOSPageAllocator.h.
Referenced by Allocate(), Free(), and FreeAll().
FreedPageBlocksNum
template<uint32 NumCacheBlocks, uint32 CachedByteLimit> uint32 TCachedOSPageAllocator< NumCacheBlocks, CachedByteLimit >::FreedPageBlocksNum private
Definition at line 91 of file CachedOSPageAllocator.h.
Referenced by TCachedOSPageAllocator(), Allocate(), Free(), and FreeAll().
The documentation for this struct was generated from the following file:
CachedOSPageAllocator.h