Unreal Engine 5.6 C++ API: FShaderCompilerInput Struct Reference
FShaderCompilerInput Struct Reference
Struct that gathers all readonly inputs needed for the compilation of a single shader.
#include "ShaderCompilerCore.h"
Public Member Functions
FShaderCompilerInput ()=default
FShaderCompilerInput (const FShaderCompilerInput &)=default
FShaderCompilerInput (FShaderCompilerInput &&)=default
void DeserializeSharedInputs (FArchive &Ar, const TArray< FShaderCompilerEnvironment > &SharedEnvironments, const TArray< TUniquePtr< FShaderParametersMetadata > > &ShaderParameterStructures)
bool DumpDebugInfoEnabled () const
void GatherSharedInputs (TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > &SharedEnvironments, TArray< const FShaderParametersMetadata * > &ParametersStructures)
void GatherSharedInputs (TMap< FString, FString > &ExternalIncludes, TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > &SharedEnvironments, TArray< const FShaderParametersMetadata * > &ParametersStructures)
void GatherSharedInputsAnsi (TMap< FString, TArray< ANSICHAR > > &ExternalIncludes, TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > &SharedEnvironments, TArray< const FShaderParametersMetadata * > &ParametersStructures)
FString GenerateDebugInfo () const
FString GenerateShaderName () const
RENDERCORE_API FString GetOrCreateShaderDebugInfoPath () const
Returns the shader debug info path for this shader compiler input and create the directory if it doesn't exist yet.
FString GetSourceFilename () const
FStringView GetSourceFilenameView () const
bool IsRayTracingShader () const
bool IsWorkGraphShader () const
bool NeedsOriginalShaderSource () const
FShaderCompilerInput & operator= (const FShaderCompilerInput &)=default
FShaderCompilerInput & operator= (FShaderCompilerInput &&)=default
void SerializeSharedInputs (FArchive &Ar, const TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > &SharedEnvironments, const TArray< const FShaderParametersMetadata * > &ParametersStructures)
bool ShouldUseStableConstantBuffer () const
Data Fields
bool bCachePreprocessed = true
bool bCompilingForShaderPipeline = false
bool bIncludeUsedOutputs = false
FName CompressionFormat
FString DebugDescription
FString DebugExtension
FString DebugGroupName
EShaderDebugInfoFlags DebugInfoFlags = EShaderDebugInfoFlags::Default
FString DumpDebugInfoPath
FString DumpDebugInfoRootPath
FString EntryPointName
FShaderCompilerEnvironment Environment
FExtraShaderCompilerSettings ExtraSettings
FShaderCompilerInputHash Hash
FOodleDataCompression::ECompressor OodleCompressor
Oodle-specific compression algorithm - used if CompressionFormat is set to NAME_Oodle.
FOodleDataCompression::ECompressionLevel OodleLevel
Oodle-specific compression level - used if CompressionFormat is set to NAME_Oodle.
TArray< FString > RequiredSymbols
const FShaderParametersMetadata * RootParametersStructure = nullptr
FName ShaderFormat
FString ShaderName
FName ShaderPlatformName
TRefCountPtr< FSharedShaderCompilerEnvironment > SharedEnvironment
uint32 SupportedHardwareMask = 0
FShaderTarget Target { SF_NumFrequencies, SP_NumPlatforms }
TArray< FString > UsedOutputs
FString VirtualSourceFilePath
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FShaderCompilerInput &Input)
Detailed Description
Struct that gathers all readonly inputs needed for the compilation of a single shader.
Definition at line 188 of file ShaderCompilerCore.h.
Constructor & Destructor Documentation
FShaderCompilerInput() [1/3]
FShaderCompilerInput::FShaderCompilerInput () default
References FShaderCompilerInput().
Referenced by FShaderCompilerInput(), FShaderCompilerInput(), FShaderCompilerInput(), operator<<, operator=(), and operator=().
FShaderCompilerInput() [2/3]
FShaderCompilerInput::FShaderCompilerInput (FShaderCompilerInput &&) default
References FShaderCompilerInput().
FShaderCompilerInput() [3/3]
FShaderCompilerInput::FShaderCompilerInput (const FShaderCompilerInput &) default
References FShaderCompilerInput().
Member Function Documentation
DeserializeSharedInputs()
void FShaderCompilerInput::DeserializeSharedInputs (FArchive & Ar, const TArray< FShaderCompilerEnvironment > & SharedEnvironments, const TArray< TUniquePtr< FShaderParametersMetadata > > & ShaderParameterStructures) inline
Definition at line 354 of file ShaderCompilerCore.h.
References Ar, check, Environment, INDEX_NONE, TArray< InElementType, InAllocatorType >::IsValidIndex(), and RootParametersStructure.
DumpDebugInfoEnabled()
bool FShaderCompilerInput::DumpDebugInfoEnabled () const inline
Definition at line 265 of file ShaderCompilerCore.h.
References IFileManager::DirectoryExists(), DumpDebugInfoEnabled(), DumpDebugInfoPath, IFileManager::Get(), and TEXT.
Referenced by DumpDebugInfoEnabled(), and NeedsOriginalShaderSource().
GatherSharedInputs() [1/2]
void FShaderCompilerInput::GatherSharedInputs (TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > & SharedEnvironments, TArray< const FShaderParametersMetadata * > & ParametersStructures) inline
Definition at line 321 of file ShaderCompilerCore.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), check, RootParametersStructure, and SharedEnvironment.
GatherSharedInputs() [2/2]
void FShaderCompilerInput::GatherSharedInputs (TMap< FString, FString > & ExternalIncludes, TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > & SharedEnvironments, TArray< const FShaderParametersMetadata * > & ParametersStructures) inline
Definition at line 310 of file ShaderCompilerCore.h.
References GatherSharedInputs().
Referenced by GatherSharedInputs().
GatherSharedInputsAnsi()
void FShaderCompilerInput::GatherSharedInputsAnsi (TMap< FString, TArray< ANSICHAR > > & ExternalIncludes, TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > & SharedEnvironments, TArray< const FShaderParametersMetadata * > & ParametersStructures) inline
Definition at line 316 of file ShaderCompilerCore.h.
References GatherSharedInputsAnsi().
Referenced by GatherSharedInputsAnsi().
GenerateDebugInfo()
FString FShaderCompilerInput::GenerateDebugInfo () const inline
Definition at line 304 of file ShaderCompilerCore.h.
References CFLAG_GenerateSymbolsInfo, DebugGroupName, and Environment.
GenerateShaderName()
FString FShaderCompilerInput::GenerateShaderName () const inline
Definition at line 276 of file ShaderCompilerCore.h.
References DebugGroupName, EntryPointName, Name, TEXT, and VirtualSourceFilePath.
GetOrCreateShaderDebugInfoPath()
RENDERCORE_API FString FShaderCompilerInput::GetOrCreateShaderDebugInfoPath () const
Returns the shader debug info path for this shader compiler input and create the directory if it doesn't exist yet.
GetSourceFilename()
FString FShaderCompilerInput::GetSourceFilename () const inline
Definition at line 297 of file ShaderCompilerCore.h.
References FPaths::GetCleanFilename(), and VirtualSourceFilePath.
GetSourceFilenameView()
FStringView FShaderCompilerInput::GetSourceFilenameView () const inline
Definition at line 292 of file ShaderCompilerCore.h.
References FPathViews::GetCleanFilename(), and VirtualSourceFilePath.
IsRayTracingShader()
bool FShaderCompilerInput::IsRayTracingShader () const inline
Definition at line 379 of file ShaderCompilerCore.h.
References Target.
Referenced by ShouldUseStableConstantBuffer().
IsWorkGraphShader()
bool FShaderCompilerInput::IsWorkGraphShader () const inline
Definition at line 384 of file ShaderCompilerCore.h.
References Target.
NeedsOriginalShaderSource()
bool FShaderCompilerInput::NeedsOriginalShaderSource () const inline
Definition at line 270 of file ShaderCompilerCore.h.
References DumpDebugInfoEnabled(), and ExtraSettings.
operator=() [1/2]
FShaderCompilerInput & FShaderCompilerInput::operator= (const FShaderCompilerInput &) default
References FShaderCompilerInput(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FShaderCompilerInput & FShaderCompilerInput::operator= (FShaderCompilerInput &&) default
References FShaderCompilerInput().
SerializeSharedInputs()
void FShaderCompilerInput::SerializeSharedInputs (FArchive & Ar, const TArray< TRefCountPtr< FSharedShaderCompilerEnvironment > > & SharedEnvironments, const TArray< const FShaderParametersMetadata * > & ParametersStructures) inline
Definition at line 338 of file ShaderCompilerCore.h.
References Ar, check, TArray< InElementType, InAllocatorType >::Find(), INDEX_NONE, RootParametersStructure, and SharedEnvironment.
ShouldUseStableConstantBuffer()
bool FShaderCompilerInput::ShouldUseStableConstantBuffer () const inline
Definition at line 389 of file ShaderCompilerCore.h.
References IsRayTracingShader(), and RootParametersStructure.
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FShaderCompilerInput & Input) friend
References FShaderCompilerInput(), Ar, and Input.
Field Documentation
bCachePreprocessed
bool FShaderCompilerInput::bCachePreprocessed = true
Definition at line 210 of file ShaderCompilerCore.h.
bCompilingForShaderPipeline
bool FShaderCompilerInput::bCompilingForShaderPipeline = false
Definition at line 217 of file ShaderCompilerCore.h.
bIncludeUsedOutputs
bool FShaderCompilerInput::bIncludeUsedOutputs = false
Definition at line 218 of file ShaderCompilerCore.h.
CompressionFormat
FName FShaderCompilerInput::CompressionFormat
Definition at line 193 of file ShaderCompilerCore.h.
DebugDescription
FString FShaderCompilerInput::DebugDescription
Definition at line 231 of file ShaderCompilerCore.h.
DebugExtension
FString FShaderCompilerInput::DebugExtension
Definition at line 228 of file ShaderCompilerCore.h.
DebugGroupName
FString FShaderCompilerInput::DebugGroupName
Definition at line 226 of file ShaderCompilerCore.h.
Referenced by GenerateDebugInfo(), and GenerateShaderName().
DebugInfoFlags
EShaderDebugInfoFlags FShaderCompilerInput::DebugInfoFlags = EShaderDebugInfoFlags::Default
Definition at line 203 of file ShaderCompilerCore.h.
DumpDebugInfoPath
FString FShaderCompilerInput::DumpDebugInfoPath
Definition at line 224 of file ShaderCompilerCore.h.
Referenced by DumpDebugInfoEnabled().
DumpDebugInfoRootPath
FString FShaderCompilerInput::DumpDebugInfoRootPath
Definition at line 222 of file ShaderCompilerCore.h.
EntryPointName
FString FShaderCompilerInput::EntryPointName
Definition at line 197 of file ShaderCompilerCore.h.
Referenced by GenerateShaderName().
Environment
FShaderCompilerEnvironment FShaderCompilerInput::Environment
Definition at line 237 of file ShaderCompilerCore.h.
Referenced by DeserializeSharedInputs(), and GenerateDebugInfo().
ExtraSettings
FExtraShaderCompilerSettings FShaderCompilerInput::ExtraSettings
Definition at line 247 of file ShaderCompilerCore.h.
Referenced by NeedsOriginalShaderSource().
Hash
FShaderCompilerInputHash FShaderCompilerInput::Hash
Definition at line 234 of file ShaderCompilerCore.h.
OodleCompressor
FOodleDataCompression::ECompressor FShaderCompilerInput::OodleCompressor
Oodle-specific compression algorithm - used if CompressionFormat is set to NAME_Oodle.
Definition at line 250 of file ShaderCompilerCore.h.
OodleLevel
FOodleDataCompression::ECompressionLevel FShaderCompilerInput::OodleLevel
Oodle-specific compression level - used if CompressionFormat is set to NAME_Oodle.
Definition at line 253 of file ShaderCompilerCore.h.
RequiredSymbols
TArray<FString> FShaderCompilerInput::RequiredSymbols
Definition at line 214 of file ShaderCompilerCore.h.
RootParametersStructure
const FShaderParametersMetadata* FShaderCompilerInput::RootParametersStructure = nullptr
Definition at line 242 of file ShaderCompilerCore.h.
Referenced by DeserializeSharedInputs(), GatherSharedInputs(), SerializeSharedInputs(), and ShouldUseStableConstantBuffer().
ShaderFormat
FName FShaderCompilerInput::ShaderFormat
Definition at line 192 of file ShaderCompilerCore.h.
ShaderName
FString FShaderCompilerInput::ShaderName
Definition at line 198 of file ShaderCompilerCore.h.
ShaderPlatformName
FName FShaderCompilerInput::ShaderPlatformName
Definition at line 194 of file ShaderCompilerCore.h.
SharedEnvironment
TRefCountPtr<FSharedShaderCompilerEnvironment> FShaderCompilerInput::SharedEnvironment
Definition at line 238 of file ShaderCompilerCore.h.
Referenced by GatherSharedInputs(), and SerializeSharedInputs().
SupportedHardwareMask
uint32 FShaderCompilerInput::SupportedHardwareMask = 0
Definition at line 200 of file ShaderCompilerCore.h.
Target
FShaderTarget FShaderCompilerInput::Target { SF_NumFrequencies, SP_NumPlatforms }
Definition at line 190 of file ShaderCompilerCore.h.
Referenced by IsRayTracingShader(), and IsWorkGraphShader().
UsedOutputs
TArray<FString> FShaderCompilerInput::UsedOutputs
Definition at line 219 of file ShaderCompilerCore.h.
VirtualSourceFilePath
FString FShaderCompilerInput::VirtualSourceFilePath
Definition at line 196 of file ShaderCompilerCore.h.
Referenced by GenerateShaderName(), GetSourceFilename(), and GetSourceFilenameView().
The documentation for this struct was generated from the following file:
ShaderCompilerCore.h