Unreal Engine 5.6 C++ API: FConstraintChannelInterfaceRegistry Class Reference
FConstraintChannelInterfaceRegistry Class Reference
Handle animatable interface registry.
#include "TransformConstraintChannelInterface.h"
Public Member Functions
~FConstraintChannelInterfaceRegistry ()=default
MOVIESCENETOOLS_API ITransformConstraintChannelInterface * FindConstraintChannelInterface (const UClass *InClass) const
Find the registered interface from the given class.
template<typename HandleType>
void RegisterConstraintChannelInterface (TUniquePtr< ITransformConstraintChannelInterface > &&InInterface)
Register an interface for the HandleType static class.
Static Public Member Functions
static MOVIESCENETOOLS_API FConstraintChannelInterfaceRegistry & Get ()
Get the singleton registry object.
Private Member Functions
FConstraintChannelInterfaceRegistry ()=default
Private Attributes
TMap< UClass *, TUniquePtr< ITransformConstraintChannelInterface > > HandleToInterfaceMap
Detailed Description
Handle animatable interface registry.
Definition at line 78 of file TransformConstraintChannelInterface.h.
Constructor & Destructor Documentation
~FConstraintChannelInterfaceRegistry()
FConstraintChannelInterfaceRegistry::~FConstraintChannelInterfaceRegistry () default
FConstraintChannelInterfaceRegistry()
FConstraintChannelInterfaceRegistry::FConstraintChannelInterfaceRegistry () private default
Referenced by Get().
Member Function Documentation
FindConstraintChannelInterface()
MOVIESCENETOOLS_API ITransformConstraintChannelInterface * FConstraintChannelInterfaceRegistry::FindConstraintChannelInterface (const UClass * InClass) const
Find the registered interface from the given class.
Returns a nullptr if noting registered for that class.
Get()
MOVIESCENETOOLS_API FConstraintChannelInterfaceRegistry & FConstraintChannelInterfaceRegistry::Get () static
Get the singleton registry object.
References FConstraintChannelInterfaceRegistry().
RegisterConstraintChannelInterface()
template<typename HandleType> void FConstraintChannelInterfaceRegistry::RegisterConstraintChannelInterface (TUniquePtr< ITransformConstraintChannelInterface > && InInterface) inline
Register an interface for the HandleType static class.
Definition at line 88 of file TransformConstraintChannelInterface.h.
References check, HandleToInterfaceMap, and MoveTemp().
Field Documentation
HandleToInterfaceMap
TMap<UClass*, TUniquePtr<ITransformConstraintChannelInterface> > FConstraintChannelInterfaceRegistry::HandleToInterfaceMap private
Definition at line 101 of file TransformConstraintChannelInterface.h.
Referenced by RegisterConstraintChannelInterface().
The documentation for this class was generated from the following file:
TransformConstraintChannelInterface.h