Unreal Engine 5.6 C++ API: FOutBunch Class Reference
FOutBunch Class Reference
#include "DataBunch.h"
Public Member Functions
FOutBunch ()
FOutBunch (class UChannel *InChannel, bool bClose)
FOutBunch (const FOutBunch &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOutBunch (FOutBunch &&)=default
FOutBunch (int64 InMaxBits)
FOutBunch (UPackageMap *PackageMap, int64 InMaxBits=1024)
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS ~FOutBunch ()
virtual void CountMemory (FArchive &Ar) const override
Counts the in-memory bytes used by this object.
FString GetDebugString () const
FOutBunch & operator= (const FOutBunch &)=default
FOutBunch & operator= (FOutBunch &&)=default
virtual void Reset () override
Resets the bit writer back to its initial state.
void SetDebugString (FString DebugStr)
FString ToString ()
Public Member Functions inherited from FNetBitWriter
FNetBitWriter ()
FNetBitWriter (int64 InMaxBits)
FNetBitWriter (UPackageMap *InPackageMap, int64 InMaxBits)
virtual FArchive & operator<< (FName &Name) override
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (FObjectPtr &Value) override
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (FSoftObjectPath &Value) override
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (FSoftObjectPtr &Value) override
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (struct FWeakObjectPtr &Value) override
Serializes FWeakObjectPtr value from or into this archive.
virtual FArchive & operator<< (UObject *&Object) override
Serializes an UObject value from or into this archive.
Public Member Functions inherited from FBitWriter
FBitWriter ()
Default constructor.
FBitWriter (const FBitWriter &)
FBitWriter (FBitWriter &&)
FBitWriter (int64 InMaxBits, bool AllowResize=false)
Constructor using known size the buffer needs to be.
virtual ~FBitWriter ()
FORCEINLINE bool AllowAppend (int64 LengthBits)
FORCEINLINE const TArray< uint8 > * GetBuffer (void) const
FORCEINLINE uint8 * GetData (void)
Returns a pointer to our internal buffer.
FORCEINLINE const uint8 * GetData (void) const
FORCEINLINE int64 GetMaxBits (void) const
Returns the number of bits the buffer supports.
FORCEINLINE int64 GetNumBits (void) const
Returns the number of bits written.
FORCEINLINE int64 GetNumBytes (void) const
Returns the number of bytes written.
FBitWriter & operator= (const FBitWriter &)
FBitWriter & operator= (FBitWriter &&)
virtual void Serialize (void *Src, int64 LengthBytes) override
virtual void SerializeBits (void *Src, int64 LengthBits) override
virtual void SerializeBitsWithOffset (void *Src, int32 SourceBit, int64 LengthBits) override
virtual void SerializeInt (uint32 &Value, uint32 Max) override
Serializes a compressed integer - Value must be < Max.
virtual void SerializeIntPacked (uint32 &Value) override
Packs int value into bytes of 7 bits with 8th bit for 'more'.
FORCEINLINE void SetAllowOverflow (bool bInAllow)
Sets whether or not this writer intentionally allows overflows (to avoid logspam)
FORCEINLINE void SetAllowResize (bool NewResize)
FORCEINLINE void SetNumBits (int64 NumBits)
Sets how many bits packet actually contains Must be not greater than max bits allowed Useful when writing bytes to buffer manually via pointer from GetData()
void SetOverflowed (int32 LengthBits)
Marks this bit writer as overflowed.
FORCEINLINE void WriteAlign ()
void WriteBit (uint8 In)
void WriteIntWrapped (uint32 Value, uint32 ValueMax)
Serializes the specified Value, but does not bounds check against ValueMax; instead, it will wrap around if the value exceeds ValueMax (this differs from SerializeInt, which clamps)
Public Member Functions inherited from FBitArchive
FBitArchive ()
Default Constructor.
Public Member Functions inherited from FArchive
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData)
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData)
Attaches/ associates the passed in bulk data object with the linker.
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback)
Adds external read dependency.
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
virtual bool Close ()
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
Detaches the passed in bulk data object from the linker.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
virtual void Flush ()
Attempts to finish writing any buffered data to disk/permanent storage.
virtual void FlushCache ()
Flushes cache and frees internal data.
virtual void ForceBlueprintFinalization ()
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj)
Called to retrieve the archetype from the event driven loader.
virtual FString GetArchiveName () const
Returns the name of the Archive.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
virtual FArchive * GetCacheableArchive ()
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
virtual FLinker * GetLinker ()
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
virtual bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
virtual void MarkScriptSerializationEnd (const UObject *Obj)
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj)
Called when an object begins serializing property data using script serialization.
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
virtual FArchive & operator<< (FField *&Value)
Serializes a Field value from or into this archive.
virtual FArchive & operator<< (FText &Value)
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (struct FLazyObjectPtr &Value)
Serializes a lazy object pointer value from or into this archive.
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopDebugDataString ()
virtual void PopFileRegionType ()
virtual void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Pop a property that was previously being serialized off the property stack.
virtual bool Precache (int64 PrecacheOffset, int64 PrecacheSize)
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
virtual void Preload (UObject *Object)
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
virtual void PushDebugDataString (const FName &DebugData)
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
virtual void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Push a property that is currently being serialized onto the property stack.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
virtual void Seek (int64 InPos)
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params)
Serialize bulk data.
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags)
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags)
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetFilterEditorOnly (bool InFilterEditorOnly)
Sets a flag indicating that this archive needs to filter editor-only content.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
virtual void SetSerializedProperty (FProperty *InProperty)
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr)
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const
Checks whether the archive wants to skip the property independent of the other flags.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
virtual int64 Tell ()
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
virtual int64 TotalSize ()
Returns total size of the backing data storage.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
virtual void UsingCustomVersion (const struct FGuid &Guid)
Registers the custom version to the archive.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Data Fields
uint8 bClose:1
uint8 bHasMustBeMappedGUIDs:1
uint8 bHasPackageMapExports:1
uint8 bOpen:1
uint8 bOutWantsFullInitState:1
uint8 bPartial:1
uint8 bPartialCustomExportsFinal:1
uint8 bPartialFinal:1
uint8 bPartialInitial:1
UE_DEPRECATED(5.3, "Replication pausing is deprecated") uint8 bIsReplicationPaused uint8 bReliable:1
UChannel * Channel
int32 ChIndex
FName ChName
int32 ChSequence
EChannelCloseReason CloseReason
FString DebugString
TArray< FNetworkGUID > ExportNetGUIDs
TArray< uint64 > NetFieldExports
TArray< UE::Net::FNetToken, TInlineAllocator< 4 > > NetTokensPendingExport
FOutBunch * Next
int32 PacketId
uint8 ReceivedAck:1
double Time
Data Fields inherited from FNetBitWriter
TNetDoNotCopyPtr< UE::Net::FNetTokenExportContext > NetTokenExportContext
class UPackageMap * PackageMap
Data Fields inherited from FArchive
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Additional Inherited Members
Protected Member Functions inherited from FArchive
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Static Protected Member Functions inherited from FArchive
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Detailed Description
Definition at line 23 of file DataBunch.h.
Constructor & Destructor Documentation
FOutBunch() [1/6]
FOutBunch::FOutBunch ()
Referenced by FOutBunch(), FOutBunch(), operator=(), and operator=().
FOutBunch() [2/6]
FOutBunch::FOutBunch (int64 InMaxBits) explicit
FOutBunch() [3/6]
FOutBunch::FOutBunch (class UChannel * InChannel, bool bClose)
References bClose.
FOutBunch() [4/6]
FOutBunch::FOutBunch (UPackageMap * PackageMap, int64 InMaxBits = 1024)
References FNetBitWriter::PackageMap, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
FOutBunch() [5/6]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOutBunch::FOutBunch (FOutBunch &&) default
References FOutBunch().
FOutBunch() [6/6]
FOutBunch::FOutBunch (const FOutBunch &) default
References FOutBunch().
~FOutBunch()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS FOutBunch::~FOutBunch () virtual
Member Function Documentation
CountMemory()
virtual void FOutBunch::CountMemory (FArchive & Ar) const override virtual
Counts the in-memory bytes used by this object.
Reimplemented from FNetBitWriter.
References Ar.
GetDebugString()
FString FOutBunch::GetDebugString () const inline
Definition at line 60 of file DataBunch.h.
References DebugString.
Referenced by ToString().
operator=() [1/2]
FOutBunch & FOutBunch::operator= (const FOutBunch &) default
References FOutBunch(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FOutBunch & FOutBunch::operator= (FOutBunch &&) default
References FOutBunch().
Reset()
virtual void FOutBunch::Reset () override virtual
Resets the bit writer back to its initial state.
Reimplemented from FBitWriter.
SetDebugString()
void FOutBunch::SetDebugString (FString DebugStr) inline
Definition at line 56 of file DataBunch.h.
References DebugString.
ToString()
FString FOutBunch::ToString () inline
Definition at line 90 of file DataBunch.h.
References bClose, bHasPackageMapExports, bOpen, bPartial, bPartialFinal, bPartialInitial, bReliable, ChIndex, ChSequence, CloseReason, GetDebugString(), FBitWriter::GetNumBits(), LexToString(), NetTokensPendingExport, PacketId, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and TEXT.
Field Documentation
bClose
uint8 FOutBunch::bClose
Definition at line 36 of file DataBunch.h.
Referenced by FControlChannelOutBunch::FControlChannelOutBunch(), FOutBunch(), and ToString().
bHasMustBeMappedGUIDs
uint8 FOutBunch::bHasMustBeMappedGUIDs
Definition at line 44 of file DataBunch.h.
bHasPackageMapExports
uint8 FOutBunch::bHasPackageMapExports
Definition at line 43 of file DataBunch.h.
Referenced by ToString().
bOpen
uint8 FOutBunch::bOpen
Definition at line 35 of file DataBunch.h.
Referenced by ToString().
bOutWantsFullInitState
uint8 FOutBunch::bOutWantsFullInitState
Definition at line 46 of file DataBunch.h.
bPartial
uint8 FOutBunch::bPartial
Definition at line 40 of file DataBunch.h.
Referenced by ToString().
bPartialCustomExportsFinal
uint8 FOutBunch::bPartialCustomExportsFinal
Definition at line 45 of file DataBunch.h.
bPartialFinal
uint8 FOutBunch::bPartialFinal
Definition at line 42 of file DataBunch.h.
Referenced by ToString().
bPartialInitial
uint8 FOutBunch::bPartialInitial
Definition at line 41 of file DataBunch.h.
Referenced by ToString().
bReliable
UE_DEPRECATED (5.3, "Replication pausing is deprecated") uint8 bIsReplicationPaused uint8 FOutBunch::bReliable
Definition at line 39 of file DataBunch.h.
Referenced by ToString().
Channel
UChannel* FOutBunch::Channel
Definition at line 28 of file DataBunch.h.
ChIndex
int32 FOutBunch::ChIndex
Definition at line 30 of file DataBunch.h.
Referenced by ToString().
ChName
FName FOutBunch::ChName
Definition at line 31 of file DataBunch.h.
ChSequence
int32 FOutBunch::ChSequence
Definition at line 32 of file DataBunch.h.
Referenced by ToString().
CloseReason
EChannelCloseReason FOutBunch::CloseReason
Definition at line 48 of file DataBunch.h.
Referenced by ToString().
DebugString
FString FOutBunch::DebugString
Definition at line 55 of file DataBunch.h.
Referenced by GetDebugString(), and SetDebugString().
ExportNetGUIDs
TArray< FNetworkGUID > FOutBunch::ExportNetGUIDs
Definition at line 50 of file DataBunch.h.
NetFieldExports
TArray< uint64 > FOutBunch::NetFieldExports
Definition at line 51 of file DataBunch.h.
NetTokensPendingExport
TArray<UE::Net::FNetToken, TInlineAllocator<4> > FOutBunch::NetTokensPendingExport
Definition at line 52 of file DataBunch.h.
Referenced by ToString().
Next
FOutBunch* FOutBunch::Next
Definition at line 27 of file DataBunch.h.
PacketId
int32 FOutBunch::PacketId
Definition at line 33 of file DataBunch.h.
Referenced by ToString().
ReceivedAck
uint8 FOutBunch::ReceivedAck
Definition at line 34 of file DataBunch.h.
Time
double FOutBunch::Time
Definition at line 29 of file DataBunch.h.
The documentation for this class was generated from the following file:
DataBunch.h