Unreal Engine 5.6 C++ API: FDevVersionRegistration Class Reference
FDevVersionRegistration Class Reference
#include "DevObjectVersion.h"
Public Member Functions
template<int N>
FDevVersionRegistration (FGuid InKey, int32 Version, const TCHAR(&InFriendlyName)[N], CustomVersionValidatorFunc InValidatorFunc=nullptr)
Public Member Functions inherited from FCustomVersionRegistration
template<int N>
FCustomVersionRegistration (FGuid InKey, int32 Version, const TCHAR(&InFriendlyName)[N], CustomVersionValidatorFunc InValidatorFunc=nullptr)
~FCustomVersionRegistration ()
Static Public Member Functions
static void DumpVersionsToLog ()
Dumps all registered versions to log.
Static Private Member Functions
static void RecordDevVersion (FGuid Key)
Detailed Description
Definition at line 35 of file DevObjectVersion.h.
Constructor & Destructor Documentation
FDevVersionRegistration()
template<int N> FDevVersionRegistration::FDevVersionRegistration (FGuid InKey, int32 Version, const TCHAR(&) InFriendlyName[N], CustomVersionValidatorFunc InValidatorFunc = nullptr) inline
Parameters
InFriendlyName must be a string literal
Definition at line 40 of file DevObjectVersion.h.
References FCustomVersionRegistration::FCustomVersionRegistration(), and RecordDevVersion().
Member Function Documentation
DumpVersionsToLog()
void FDevVersionRegistration::DumpVersionsToLog () static
Dumps all registered versions to log.
RecordDevVersion()
void FDevVersionRegistration::RecordDevVersion (FGuid Key) static private
References FCustomVersionRegistration::Key.
Referenced by FDevVersionRegistration().
The documentation for this class was generated from the following file:
DevObjectVersion.h