Unreal Engine 5.6 C++ API: FBulkData Class Reference
FBulkData Class Reference
@documentation
#include "BulkData.h"
Data Structures
struct FAllocatedPtr
Public Types
using BulkDataRangeArray = TArray<FBulkData*, TInlineAllocator<8>>
using FSerializeBulkDataElements = TFunction<void(FArchive&, void*, int64, EBulkDataFlags)>
Public Member Functions
FBulkData ()=default
Constructor, initializing all member variables.
FBulkData (const FBulkData &Other)
Copy constructor.
~FBulkData ()
Virtual destructor, free'ing allocated memory.
bool CanLoadBulkDataWithFileReader () const
Test if it is possible to load the bulk data using a file reader, even when no archive is attached to the bulk data.
bool CanLoadFromDisk () const
Returns true if the data can be loaded from disk.
void ClearBulkDataFlags (uint32 BulkDataFlagsToClear)
Clears the passed in bulk data flags.
FIoChunkId CreateChunkId () const
Returns a FIoChunkId for the bulkdata payload, this will be invalid if the bulkdata is not stored in the IoStore.
IBulkDataIORequest * CreateStreamingRequest (EAsyncIOPriorityAndFlags Priority, FBulkDataIORequestCallBack *CompleteCallback, uint8 *UserSuppliedMemory) const
Create an async read request for the bulk data.
IBulkDataIORequest * CreateStreamingRequest (int64 OffsetInBulkData, int64 BytesToRead, EAsyncIOPriorityAndFlags Priority, FBulkDataIORequestCallBack *CompleteCallback, uint8 *UserSuppliedMemory) const
Create an async read request for the bulk data.
bool DoesExist () const
Returns true if the data references a file that currently exists and can be referenced by the file system.
void ForceBulkDataResident ()
Forces the bulk data to be resident in memory and detaches the archive.
uint32 GetBulkDataAlignment () const
Gets the current bulk data alignment.
uint32 GetBulkDataFlags () const
Gets the current bulk data flags.
int64 GetBulkDataOffsetInFile () const
Returns the offset into the file the bulk data is located at.
int64 GetBulkDataSize () const
Returns the size of the bulk data in bytes.
int64 GetBulkDataSizeOnDisk () const
Returns the size of the bulk data on disk.
void GetBulkDataVersions (FArchive &InlineArchive, FPackageFileVersion &OutUEVersion, int32 &OutLicenseeUEVersion, FCustomVersionContainer &OutCustomVersions) const
Get the CustomVersions used in the file containing the BulkData payload.
void GetCopy (void **Dest, bool bDiscardInternalCopy=true)
Retrieves a copy of the bulk data.
FString GetDebugName () const
Returns a string representing the bulk data for debugging purposes.
FName GetDecompressionFormat () const
Returns flags usable to decompress the bulk data.
FIoFilenameHash GetIoFilenameHash () const
Returns the io filename hash associated with this bulk data.
bool IsBulkDataLoaded () const
Returns whether the bulk data is currently loaded and resident in memory.
bool IsDataMemoryMapped () const
Returns whether this bulk data is memory mapped or not.
bool IsDuplicateNonOptional () const
Returns whether this bulk data represents duplicate non-optional data or not.
bool IsInExternalResource () const
Returns whether this bulk data is stored in a PackageExternalResource rather than in a neighboring segment of its owner's PackagePath.
bool IsInlined () const
Returns whether this bulk data is currently stored inline or not.
bool IsInSeparateFile () const
Returns whether this bulk data is currently stored in it's own file or not.
bool IsLocked () const
Checks if this bulk is locked.
bool IsOptional () const
Returns whether this bulk data represents optional data or not.
bool IsSingleUse () const
Returns whether to deallocate the bulk data after lock.
bool IsStoredCompressedOnDisk () const
Returns whether the bulk data is stored compressed on disk.
bool IsUnlocked () const
Checks if this bulk is unlocked.
bool IsUsingIODispatcher () const
Returns whether this bulk data is accessed via the IoDispatcher or not.
bool LoadBulkDataWithFileReader ()
Load the bulk data using a file reader.
void * Lock (uint32 LockFlags)
Locks the bulk data and returns a pointer to it.
const void * LockReadOnly () const
Locks the bulk data and returns a read-only pointer to it.
IAsyncReadFileHandle * OpenAsyncReadHandle () const
Opens a new IAsyncReadFileHandle that references the file that the BulkData object represents.
FBulkData & operator= (const FBulkData &Other)
Copies the source array into this one after detaching from archive.
void * Realloc (int64 ElementCount, int64 ElementSize)
Change size of locked bulk data.
void RemoveBulkData ()
Clears/removes any currently allocated data payload and resets element count to 0.
void ResetBulkDataFlags (uint32 BulkDataFlagsToSet)
Enable the given flags and disable all other flags.
void Serialize (FArchive &Ar, UObject *Owner, bool bAttemptFileMapping, int32 ElementSize, EFileRegionType FileRegionType)
Serialize function used to serialize this bulk data structure.
void SerializeBulkData (FArchive &Ar, void *Data, EBulkDataFlags InBulkDataFlags)
Serialize just the bulk data portion to/ from the passed in memory.
void SetBulkDataFlags (uint32 BulkDataFlagsToSet)
Enables the given flags without affecting any previously set flags.
void SetCookedIndex (FBulkDataCookedIndex Index)
void SetFlagsFromDiskWrittenValues (EBulkDataFlags InBulkDataFlags, int64 InBulkDataOffsetInFile, int64 InBulkDataSizeOnDisk, int64 LinkerSummaryBulkDataStartOffset)
When saving BulkData, if we are overwriting the file we need to update the BulkData's (flags,offset,size) to be able to load from the new file.
FOwnedBulkDataPtr * StealFileMapping ()
void StoreCompressedOnDisk (FName CompressionFormat)
Sets whether we should store the data compressed on disk.
UE_DEPRECATED (5.3, "The feature is being removed, it is assumed that all bulkdata is available for use") 1 bool IsAvailableForUse() const
Returns whether this bulk data is used.
UE_DEPRECATED (5.5, "No longer provides any functionality (assume that this will always return true") 1 bool IsAsyncLoadingComplete() const
Deprecated.
bool UnloadBulkData ()
Deallocates bulk data without detaching the archive, so that further bulk data accesses require a reload.
void Unlock () const
Unlocks bulk data after which point the pointer returned by Lock no longer is valid.
Static Public Member Functions
static void ClearBulkDataFlagsOn (EBulkDataFlags &InOutAccumulator, EBulkDataFlags FlagsToClear)
Disable the given flags in the given accumulator variable.
static void DumpBulkDataUsage (FOutputDevice &Log)
Dumps detailed information of bulk data usage.
static FName GetDecompressionFormat (EBulkDataFlags InFlags)
Returns decompress method flags specified by the given bulk data flags.
static bool HasFlags (EBulkDataFlags Flags, EBulkDataFlags Contains)
Returns whether all of the specified flags are set.
static void SetBulkDataFlagsOn (EBulkDataFlags &InOutAccumulator, EBulkDataFlags FlagsToSet)
Enable the given flags in the given accumulator variable.
Static Public Attributes
static constexpr SIZE_T MaxBulkDataSize = (1ull << 40) - 1
Protected Member Functions
void SerializeBulkData (FArchive &Ar, void *Data, int64 DataSize, EBulkDataFlags InBulkDataFlags)
Protected Attributes
FArchive * AttachedAr = nullptr
Archive associated with bulk data for serialization.
FBulkDataCookedIndex CookedIndex
The index to which the cooked version of the bulkdata payload should be assigned.
FLinkerLoad * Linker = nullptr
Used to make sure the linker doesn't get garbage collected at runtime for things with attached archives.
FSerializeBulkDataElements * SerializeBulkDataElements = nullptr
Custom bulk data serialization hook when using FUntypedBulkData.
Private Member Functions
bool CanDiscardInternalData () const
void DetachFromArchive (FArchive *Ar, bool bEnsureBulkDataIsLoaded)
Detaches the bulk data from the passed in archive.
void FreeData ()
Free bulk data.
void * GetDataBufferForWrite () const
Retrieve the internal allocation for writing.
const void * GetDataBufferReadOnly () const
Retrieve the internal allocation for reading.
void MakeSureBulkDataIsLoaded ()
Loads the bulk data if it is not already loaded.
bool NeedsOffsetFixup () const
Returns if the offset needs fixing when serialized.
void * ReallocateData (int64 SizeInBytes)
Reallocate bulk data.
int64 SerializePayload (FArchive &Ar, EBulkDataFlags SerializationFlags, const TOptional< EFileRegionType > &RegionType)
bool TryLoadDataIntoMemory (FIoBuffer Dest)
Loads the data from disk into the specified memory block.
UE_DEPRECATED (5.5, "No longer provides any functionality") void FlushAsyncLoading()
Private Attributes
FIoChunkId BulkChunkId = FIoChunkId::InvalidChunkId
UE::BulkData::Private::FBulkMetaData BulkMeta
FAllocatedPtr DataAllocation
Friends
class FBulkDataBatchRequest
class FExportArchive
class FLinkerLoad
class FLinkerSave
class UE::Serialization::FEditorBulkData
Detailed Description
@documentation
Todo
documentation
Definition at line 468 of file BulkData.h.
Member Typedef Documentation
BulkDataRangeArray
using FBulkData::BulkDataRangeArray = TArray<FBulkData*, TInlineAllocator<8>>
Definition at line 514 of file BulkData.h.
FSerializeBulkDataElements
using FBulkData::FSerializeBulkDataElements = TFunction<void(FArchive&, void*, int64, EBulkDataFlags)>
Definition at line 847 of file BulkData.h.
Constructor & Destructor Documentation
FBulkData() [1/2]
FBulkData::FBulkData () default
Constructor, initializing all member variables.
Referenced by FBulkData(), FBulkData::FAllocatedPtr::Free(), FBulkData::FAllocatedPtr::GetAllocationForWrite(), FBulkData::FAllocatedPtr::GetAllocationReadOnly(), operator=(), FBulkData::FAllocatedPtr::ReallocateData(), FBulkData::FAllocatedPtr::SetData(), FBulkData::FAllocatedPtr::SetMemoryMappedData(), FBulkData::FAllocatedPtr::StealFileMapping(), and FBulkData::FAllocatedPtr::Swap().
FBulkData() [2/2]
FBulkData::FBulkData (const FBulkData & Other)
Copy constructor.
Use the common routine to perform the copy.
Parameters
Other the source array to copy
References FBulkData(), and Other.
~FBulkData()
FBulkData::~FBulkData ()
Virtual destructor, free'ing allocated memory.
Member Function Documentation
CanDiscardInternalData()
bool FBulkData::CanDiscardInternalData () const private
CanLoadBulkDataWithFileReader()
bool FBulkData::CanLoadBulkDataWithFileReader () const
Test if it is possible to load the bulk data using a file reader, even when no archive is attached to the bulk data.
Returns
Whether the operation is allowed.
CanLoadFromDisk()
bool FBulkData::CanLoadFromDisk () const
Returns true if the data can be loaded from disk.
ClearBulkDataFlags()
void FBulkData::ClearBulkDataFlags (uint32 BulkDataFlagsToClear)
Clears the passed in bulk data flags.
Parameters
BulkDataFlagsToClear Bulk data flags to clear
ClearBulkDataFlagsOn()
void FBulkData::ClearBulkDataFlagsOn (EBulkDataFlags & InOutAccumulator, EBulkDataFlags FlagsToClear) static
Disable the given flags in the given accumulator variable.
CreateChunkId()
FIoChunkId FBulkData::CreateChunkId () const
Returns a FIoChunkId for the bulkdata payload, this will be invalid if the bulkdata is not stored in the IoStore.
CreateStreamingRequest() [1/2]
IBulkDataIORequest * FBulkData::CreateStreamingRequest (EAsyncIOPriorityAndFlags Priority, FBulkDataIORequestCallBack * CompleteCallback, uint8 * UserSuppliedMemory) const
Create an async read request for the bulk data.
This version will load the entire data range that the FBulkData represents.
Parameters
Priority Priority and flags of the request. If this includes AIOP_FLAG_PRECACHE, then memory will never be returned. The request should always be canceled and waited for, even for a precache request.
CompleteCallback Called from an arbitrary thread when the request is complete. Can be nullptr, if non-null, must remain valid until it is called. It will always be called.
UserSuppliedMemory A pointer to memory for the IO request to be written to, it is up to the caller to make sure that it is large enough. If the pointer is null then the system will allocate memory instead.
Returns
A request for the read. This is owned by the caller and must be deleted by the caller.
CreateStreamingRequest() [2/2]
IBulkDataIORequest * FBulkData::CreateStreamingRequest (int64 OffsetInBulkData, int64 BytesToRead, EAsyncIOPriorityAndFlags Priority, FBulkDataIORequestCallBack * CompleteCallback, uint8 * UserSuppliedMemory) const
Create an async read request for the bulk data.
This version allows the user to request a subset of the data that the FBulkData represents.
Parameters
OffsetInBulkData Offset into the bulk data to start reading from.
BytesToRead The number of bytes to read. If this request is AIOP_Preache, the size can be anything, even MAX_int64, otherwise the size and offset must be fully contained in the file.
Priority Priority and flags of the request. If this includes AIOP_FLAG_PRECACHE, then memory will never be returned. The request should always be canceled and waited for, even for a precache request.
CompleteCallback Called from an arbitrary thread when the request is complete. Can be nullptr, if non-null, must remain valid until it is called. It will always be called.
UserSuppliedMemory A pointer to memory for the IO request to be written to, it is up to the caller to make sure that it is large enough. If the pointer is null then the system will allocate memory instead.
Returns
A request for the read. This is owned by the caller and must be deleted by the caller.
DetachFromArchive()
void FBulkData::DetachFromArchive (FArchive * Ar, bool bEnsureBulkDataIsLoaded) private
Detaches the bulk data from the passed in archive.
Needs to match the archive we are currently attached to.
Parameters
Ar Archive to detach from
bEnsureBulkDataIsLoaded whether to ensure that bulk data is load before detaching from archive
References Ar.
DoesExist()
bool FBulkData::DoesExist () const
Returns true if the data references a file that currently exists and can be referenced by the file system.
DumpBulkDataUsage()
void FBulkData::DumpBulkDataUsage (FOutputDevice & Log) static
Dumps detailed information of bulk data usage.
Parameters
Log FOutputDevice to use for logging
References Log.
ForceBulkDataResident()
void FBulkData::ForceBulkDataResident ()
Forces the bulk data to be resident in memory and detaches the archive.
FreeData()
void FBulkData::FreeData () inline private
Free bulk data.
Definition at line 996 of file BulkData.h.
References DataAllocation.
GetBulkDataAlignment()
uint32 FBulkData::GetBulkDataAlignment () const
Gets the current bulk data alignment.
Returns
Bulk data alignment currently set
GetBulkDataFlags()
uint32 FBulkData::GetBulkDataFlags () const
Gets the current bulk data flags.
Returns
Bulk data flags currently set
Referenced by IsDataMemoryMapped(), IsDuplicateNonOptional(), IsInExternalResource(), IsInlined(), IsInSeparateFile(), IsOptional(), IsSingleUse(), IsUsingIODispatcher(), FSkeletalMeshStreamIn_IO::SerializeLODData(), and TBulkData< uint8 >::SerializeWithFlags().
GetBulkDataOffsetInFile()
int64 FBulkData::GetBulkDataOffsetInFile () const
Returns the offset into the file the bulk data is located at.
Returns
Offset into the file or INDEX_NONE in case there is no association
Referenced by FSkeletalMeshStreamIn_IO::SerializeLODData().
GetBulkDataSize()
int64 FBulkData::GetBulkDataSize () const
Returns the size of the bulk data in bytes.
Returns
Size of the bulk data in bytes
Referenced by USoundWave::GetCompressedDataSize(), TBulkData< uint8 >::GetElementCount(), SerializeBulkData(), and FSkeletalMeshStreamIn_IO::SerializeLODData().
GetBulkDataSizeOnDisk()
int64 FBulkData::GetBulkDataSizeOnDisk () const
Returns the size of the bulk data on disk.
This can differ from GetBulkDataSize if BULKDATA_SerializeCompressed is set.
Returns
Size of the bulk data on disk or INDEX_NONE in case there's no association
GetBulkDataVersions()
void FBulkData::GetBulkDataVersions (FArchive & InlineArchive, FPackageFileVersion & OutUEVersion, int32 & OutLicenseeUEVersion, FCustomVersionContainer & OutCustomVersions) const
Get the CustomVersions used in the file containing the BulkData payload.
If !IsInSeparateFile, this will be the custom versions from the archive used to serialize the FBulkData, which the caller must provide. Otherwise, the CustomVersions come from the separate file and this function will look them up.
Parameters
InlineArchive The archive that was used to load this object
GetCopy()
void FBulkData::GetCopy (void ** Dest, bool bDiscardInternalCopy = true)
Retrieves a copy of the bulk data.
Parameters
Dest [in/out] Pointer to pointer going to hold copy, can point to NULL pointer in which case memory is allocated
bDiscardInternalCopy Whether to discard/ free the potentially internally allocated copy of the data
Referenced by TBulkData< uint8 >::GetCopyAsBuffer().
GetDataBufferForWrite()
void * FBulkData::GetDataBufferForWrite () const inline private
Retrieve the internal allocation for writing.
Definition at line 999 of file BulkData.h.
References DataAllocation.
GetDataBufferReadOnly()
const void * FBulkData::GetDataBufferReadOnly () const inline private
Retrieve the internal allocation for reading.
Definition at line 1002 of file BulkData.h.
References DataAllocation.
GetDebugName()
FString FBulkData::GetDebugName () const
Returns a string representing the bulk data for debugging purposes.
GetDecompressionFormat() [1/2]
FName FBulkData::GetDecompressionFormat () const
Returns flags usable to decompress the bulk data.
Returns
NAME_None if the data was not compressed on disk, or valid format to pass to FCompression::UncompressMemory for this data
GetDecompressionFormat() [2/2]
FName FBulkData::GetDecompressionFormat (EBulkDataFlags InFlags) static
Returns decompress method flags specified by the given bulk data flags.
GetIoFilenameHash()
FIoFilenameHash FBulkData::GetIoFilenameHash () const inline
Returns the io filename hash associated with this bulk data.
Returns
Hash or INVALID_IO_FILENAME_HASH if invalid.
Definition at line 741 of file BulkData.h.
References BulkChunkId, and MakeIoFilenameHash().
Referenced by FSkeletalMeshStreamIn_IO::SerializeLODData().
HasFlags()
bool FBulkData::HasFlags (EBulkDataFlags Flags, EBulkDataFlags Contains) static
Returns whether all of the specified flags are set.
References Flags.
IsBulkDataLoaded()
bool FBulkData::IsBulkDataLoaded () const
Returns whether the bulk data is currently loaded and resident in memory.
Returns
true if bulk data is loaded, false otherwise
IsDataMemoryMapped()
bool FBulkData::IsDataMemoryMapped () const inline
Returns whether this bulk data is memory mapped or not.
Definition at line 674 of file BulkData.h.
References BULKDATA_DataIsMemoryMapped, and GetBulkDataFlags().
IsDuplicateNonOptional()
bool FBulkData::IsDuplicateNonOptional () const inline
Returns whether this bulk data represents duplicate non-optional data or not.
Returns
true if BULKDATA_DuplicateNonOptionalPayload is set
Definition at line 691 of file BulkData.h.
References BULKDATA_DuplicateNonOptionalPayload, and GetBulkDataFlags().
IsInExternalResource()
bool FBulkData::IsInExternalResource () const inline
Returns whether this bulk data is stored in a PackageExternalResource rather than in a neighboring segment of its owner's PackagePath.
Definition at line 657 of file BulkData.h.
References BULKDATA_WorkspaceDomainPayload, GetBulkDataFlags(), and IsInSeparateFile().
IsInlined()
bool FBulkData::IsInlined () const inline
Returns whether this bulk data is currently stored inline or not.
Returns
true if BULKDATA_PayloadAtEndOfFile is not set
Definition at line 639 of file BulkData.h.
References BULKDATA_PayloadAtEndOfFile, and GetBulkDataFlags().
IsInSeparateFile()
bool FBulkData::IsInSeparateFile () const inline
Returns whether this bulk data is currently stored in it's own file or not.
Returns
true if BULKDATA_PayloadInSeperateFile is not set
Definition at line 648 of file BulkData.h.
References BULKDATA_PayloadInSeperateFile, and GetBulkDataFlags().
Referenced by IsInExternalResource().
IsLocked()
bool FBulkData::IsLocked () const inline
Checks if this bulk is locked.
Definition at line 790 of file BulkData.h.
References BulkMeta, and LOCKSTATUS_Unlocked.
IsOptional()
bool FBulkData::IsOptional () const inline
Returns whether this bulk data represents optional data or not.
Returns
true if BULKDATA_OptionalPayload is set
Definition at line 630 of file BulkData.h.
References BULKDATA_OptionalPayload, GetBulkDataFlags(), and IsOptional().
Referenced by IsOptional().
IsSingleUse()
bool FBulkData::IsSingleUse () const inline
Returns whether to deallocate the bulk data after lock.
Definition at line 682 of file BulkData.h.
References BULKDATA_SingleUse, and GetBulkDataFlags().
IsStoredCompressedOnDisk()
bool FBulkData::IsStoredCompressedOnDisk () const
Returns whether the bulk data is stored compressed on disk.
Returns
true if data is compressed on disk, false otherwise
IsUnlocked()
bool FBulkData::IsUnlocked () const inline
Checks if this bulk is unlocked.
Definition at line 795 of file BulkData.h.
References BulkMeta, and LOCKSTATUS_Unlocked.
IsUsingIODispatcher()
bool FBulkData::IsUsingIODispatcher () const inline
Returns whether this bulk data is accessed via the IoDispatcher or not.
Returns
false as the old BulkData API does not support it
Definition at line 666 of file BulkData.h.
References BULKDATA_UsesIoDispatcher, and GetBulkDataFlags().
LoadBulkDataWithFileReader()
bool FBulkData::LoadBulkDataWithFileReader ()
Load the bulk data using a file reader.
Works even when no archive is attached to the bulk data..
Returns
Whether the operation succeeded.
Lock()
void * FBulkData::Lock (uint32 LockFlags)
Locks the bulk data and returns a pointer to it.
Parameters
LockFlags Flags determining lock behavior
Referenced by TBulkDataScopedWriteLock< ElementType >::TBulkDataScopedWriteLock().
LockReadOnly()
const void * FBulkData::LockReadOnly () const
Locks the bulk data and returns a read-only pointer to it.
This variant can be called on a const bulkdata
Referenced by TBulkDataScopedReadLock< ElementType >::TBulkDataScopedReadLock().
MakeSureBulkDataIsLoaded()
void FBulkData::MakeSureBulkDataIsLoaded () private
Loads the bulk data if it is not already loaded.
NeedsOffsetFixup()
bool FBulkData::NeedsOffsetFixup () const private
Returns if the offset needs fixing when serialized.
OpenAsyncReadHandle()
IAsyncReadFileHandle * FBulkData::OpenAsyncReadHandle () const
Opens a new IAsyncReadFileHandle that references the file that the BulkData object represents.
Returns
A valid handle if the file can be accessed, if it cannot then nullptr.
operator=()
FBulkData & FBulkData::operator= (const FBulkData & Other)
Copies the source array into this one after detaching from archive.
Parameters
Other the source array to copy
References FBulkData(), and Other.
Realloc()
void * FBulkData::Realloc (int64 ElementCount, int64 ElementSize)
Change size of locked bulk data.
Only valid if locked via read-write lock.
Parameters
ElementCount Number of elements to allocate.
ElementSize Size in bytes of the individual element.
Referenced by TBulkData< uint8 >::Realloc().
ReallocateData()
void * FBulkData::ReallocateData (int64 SizeInBytes) inline private
Reallocate bulk data.
Definition at line 993 of file BulkData.h.
References DataAllocation.
RemoveBulkData()
void FBulkData::RemoveBulkData ()
Clears/removes any currently allocated data payload and resets element count to 0.
Note that once this has been called, the bulkdata object will no longer be able to reload it's payload from disk!
ResetBulkDataFlags()
void FBulkData::ResetBulkDataFlags (uint32 BulkDataFlagsToSet)
Enable the given flags and disable all other flags.
This can be used with GetBulkDataFlags() to effectively reset the flags to a previous state.
Parameters
BulkDataFlagsToSet Bulk data flags to set
Referenced by TBulkData< uint8 >::SerializeWithFlags().
Serialize()
void FBulkData::Serialize (FArchive & Ar, UObject * Owner, bool bAttemptFileMapping, int32 ElementSize, EFileRegionType FileRegionType)
Serialize function used to serialize this bulk data structure.
Parameters
Ar Archive to serialize with
Owner Object owning the bulk data
Idx Index of bulk data item being serialized
bAttemptFileMapping If true, attempt to map this instead of loading it into malloc'ed memory
FileRegionType When cooking, a hint describing the type of data, used by some platforms to improve compression ratios
References Ar, and Owner.
Referenced by TBulkData< uint8 >::Serialize(), and TBulkData< uint8 >::SerializeWithFlags().
SerializeBulkData() [1/2]
void FBulkData::SerializeBulkData (FArchive & Ar, void * Data, EBulkDataFlags InBulkDataFlags) inline
Serialize just the bulk data portion to/ from the passed in memory.
Parameters
Ar Archive to serialize with
Data Memory to serialize either to or from
InBulkDataFlags Flags describing how the data was/shouldbe serialized
Definition at line 867 of file BulkData.h.
References Ar, GetBulkDataSize(), and SerializeBulkData().
Referenced by SerializeBulkData().
SerializeBulkData() [2/2]
void FBulkData::SerializeBulkData (FArchive & Ar, void * Data, int64 DataSize, EBulkDataFlags InBulkDataFlags) protected
References Ar, and DataSize.
SerializePayload()
int64 FBulkData::SerializePayload (FArchive & Ar, EBulkDataFlags SerializationFlags, const TOptional< EFileRegionType > & RegionType) private
References Ar.
SetBulkDataFlags()
void FBulkData::SetBulkDataFlags (uint32 BulkDataFlagsToSet)
Enables the given flags without affecting any previously set flags.
Parameters
BulkDataFlagsToSet Bulk data flags to set
Referenced by TBulkData< uint8 >::SerializeWithFlags().
SetBulkDataFlagsOn()
void FBulkData::SetBulkDataFlagsOn (EBulkDataFlags & InOutAccumulator, EBulkDataFlags FlagsToSet) static
Enable the given flags in the given accumulator variable.
SetCookedIndex()
void FBulkData::SetCookedIndex (FBulkDataCookedIndex Index)
SetFlagsFromDiskWrittenValues()
void FBulkData::SetFlagsFromDiskWrittenValues (EBulkDataFlags InBulkDataFlags, int64 InBulkDataOffsetInFile, int64 InBulkDataSizeOnDisk, int64 LinkerSummaryBulkDataStartOffset)
When saving BulkData, if we are overwriting the file we need to update the BulkData's (flags,offset,size) to be able to load from the new file.
But SerializeBulkData modifies those values when loading, so the in-memory values after loading from disk are not the same as the values on disk. This function handles running the same steps that SerializeBulkData does, but skips the deserialization of the BulkData.
StealFileMapping()
FOwnedBulkDataPtr * FBulkData::StealFileMapping () inline
Definition at line 872 of file BulkData.h.
References DataAllocation.
StoreCompressedOnDisk()
void FBulkData::StoreCompressedOnDisk (FName CompressionFormat)
Sets whether we should store the data compressed on disk.
Parameters
CompressionFormat The format to use for compression e.g. NAME_None or NAME_Oodle.
This should likely not be used - bulk data that gets deployed should be compressed via UnrealPak so that it can leverage hardware compression as available, and editor bulk data is compressed by default and should use FEditorBulkData::SetCompressionOptions to control that if necessary.
TryLoadDataIntoMemory()
bool FBulkData::TryLoadDataIntoMemory (FIoBuffer Dest) private
Loads the data from disk into the specified memory block.
This requires us still being attached to an archive we can use for serialization.
Parameters
Dest Memory to serialize data into
Returns
Whether the load succeeded
UE_DEPRECATED() [1/3]
FBulkData::UE_DEPRECATED (5. 3, "The feature is being removed, it is assumed that all bulkdata is available for use") const
Returns whether this bulk data is used.
Returns
true if BULKDATA_Unused is not set
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FBulkData::UE_DEPRECATED (5. 5)
Deprecated.
Returns
As of 5.5 this will always return true as ::StartAsyncLoading was removed
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FBulkData::UE_DEPRECATED (5. 5, "No longer provides any functionality") inline private
Definition at line 984 of file BulkData.h.
References FlushAsyncLoading().
UnloadBulkData()
bool FBulkData::UnloadBulkData ()
Deallocates bulk data without detaching the archive, so that further bulk data accesses require a reload.
Only supported in editor builds.
Returns
Whether the operation succeeded.
Unlock()
void FBulkData::Unlock () const
Unlocks bulk data after which point the pointer returned by Lock no longer is valid.
Friends And Related Symbol Documentation
FBulkDataBatchRequest
friend class FBulkDataBatchRequest friend
Definition at line 512 of file BulkData.h.
References FBulkDataBatchRequest.
Referenced by FBulkDataBatchRequest.
FExportArchive
friend class FExportArchive friend
Definition at line 510 of file BulkData.h.
References FExportArchive.
Referenced by FExportArchive.
FLinkerLoad
friend class FLinkerLoad friend
Definition at line 508 of file BulkData.h.
References FLinkerLoad.
Referenced by FLinkerLoad.
FLinkerSave
friend class FLinkerSave friend
Definition at line 509 of file BulkData.h.
References FLinkerSave.
Referenced by FLinkerSave.
UE::Serialization::FEditorBulkData
friend class UE::Serialization::FEditorBulkData friend
Definition at line 511 of file BulkData.h.
Field Documentation
AttachedAr
FArchive* FBulkData::AttachedAr = nullptr protected
Archive associated with bulk data for serialization.
Definition at line 1015 of file BulkData.h.
BulkChunkId
FIoChunkId FBulkData::BulkChunkId = FIoChunkId::InvalidChunkId private
Definition at line 1010 of file BulkData.h.
Referenced by GetIoFilenameHash().
BulkMeta
UE::BulkData::Private::FBulkMetaData FBulkData::BulkMeta private
Definition at line 1009 of file BulkData.h.
Referenced by IsLocked(), and IsUnlocked().
CookedIndex
FBulkDataCookedIndex FBulkData::CookedIndex protected
The index to which the cooked version of the bulkdata payload should be assigned.
Definition at line 1019 of file BulkData.h.
DataAllocation
FAllocatedPtr FBulkData::DataAllocation private
Definition at line 1008 of file BulkData.h.
Referenced by FreeData(), GetDataBufferForWrite(), GetDataBufferReadOnly(), ReallocateData(), and StealFileMapping().
Linker
FLinkerLoad* FBulkData::Linker = nullptr protected
Used to make sure the linker doesn't get garbage collected at runtime for things with attached archives.
Definition at line 1017 of file BulkData.h.
MaxBulkDataSize
SIZE_T FBulkData::MaxBulkDataSize = (1ull << 40) - 1 static constexpr
Definition at line 516 of file BulkData.h.
SerializeBulkDataElements
FSerializeBulkDataElements* FBulkData::SerializeBulkDataElements = nullptr protected
Custom bulk data serialization hook when using FUntypedBulkData.
Definition at line 1024 of file BulkData.h.
The documentation for this class was generated from the following file:
BulkData.h