Unreal Engine 5.6 C++ API: UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<> Struct Reference
UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<> Struct Reference
The starting point for TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<...T>
#include "MovieScenePropertyTrack.h"
Public Member Functions
TPropertyTrackWithOverridableChannelsEntityImportHelperImpl (FComponentTypeID InPropertyTag, TScriptInterface< IMovieSceneChannelOverrideProvider > InRegistryProvider)
template<typename U, typename PayloadType>
TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< FAdd, TAddConditional< U > > Add (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, FChannelOverrideEntityImportParams OverrideParams)
template<typename U, typename PayloadType>
TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< FAdd, TAddConditional< U > > AddConditional (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, bool bCondition, FChannelOverrideEntityImportParams OverrideParams)
void Commit (const UMovieSceneSection *InSection, const UE::MovieScene::FEntityImportParams &Params, UE::MovieScene::FImportedEntity *OutImportedEntity)
Protected Attributes
TEntityBuilder< FAdd > Builder
FPropertyTrackEntityImportHelperParamsImpl OverrideInfo
FComponentTypeID PropertyTag
Detailed Description
The starting point for TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<...T>
Definition at line 393 of file MovieScenePropertyTrack.h.
Constructor & Destructor Documentation
TPropertyTrackWithOverridableChannelsEntityImportHelperImpl()
UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl (FComponentTypeID InPropertyTag, TScriptInterface< IMovieSceneChannelOverrideProvider > InRegistryProvider) inline
Definition at line 395 of file MovieScenePropertyTrack.h.
References Builder, OverrideInfo, and PropertyTag.
Referenced by UE::MovieScene::FPropertyTrackWithOverridableChannelsEntityImportHelper::FPropertyTrackWithOverridableChannelsEntityImportHelper(), Add(), and AddConditional().
Member Function Documentation
Add()
template<typename U, typename PayloadType> TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< FAdd, TAddConditional< U > > UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::Add (TComponentTypeID< U > ComponentType, PayloadType && InPayload, FChannelOverrideEntityImportParams OverrideParams) inline
Definition at line 403 of file MovieScenePropertyTrack.h.
References TPropertyTrackWithOverridableChannelsEntityImportHelperImpl(), Builder, UE::MovieScene::FChannelOverrideEntityImportParams::ChannelName, MoveTemp(), OverrideInfo, and PropertyTag.
AddConditional()
template<typename U, typename PayloadType> TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< FAdd, TAddConditional< U > > UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::AddConditional (TComponentTypeID< U > ComponentType, PayloadType && InPayload, bool bCondition, FChannelOverrideEntityImportParams OverrideParams) inline
Definition at line 414 of file MovieScenePropertyTrack.h.
References TPropertyTrackWithOverridableChannelsEntityImportHelperImpl(), Builder, UE::MovieScene::FChannelOverrideEntityImportParams::ChannelName, MoveTemp(), OverrideInfo, and PropertyTag.
Commit()
void UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit (const UMovieSceneSection * InSection, const UE::MovieScene::FEntityImportParams & Params, UE::MovieScene::FImportedEntity * OutImportedEntity) inline
Definition at line 326 of file MovieScenePropertyTrack.h.
Field Documentation
Builder
TEntityBuilder<FAdd> UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::Builder protected
Definition at line 426 of file MovieScenePropertyTrack.h.
Referenced by TPropertyTrackWithOverridableChannelsEntityImportHelperImpl(), Add(), and AddConditional().
OverrideInfo
FPropertyTrackEntityImportHelperParamsImpl UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::OverrideInfo protected
Definition at line 427 of file MovieScenePropertyTrack.h.
Referenced by TPropertyTrackWithOverridableChannelsEntityImportHelperImpl(), Add(), and AddConditional().
PropertyTag
FComponentTypeID UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>::PropertyTag protected
Definition at line 428 of file MovieScenePropertyTrack.h.
Referenced by UE::MovieScene::FPropertyTrackWithOverridableChannelsEntityImportHelper::FPropertyTrackWithOverridableChannelsEntityImportHelper(), TPropertyTrackWithOverridableChannelsEntityImportHelperImpl(), Add(), and AddConditional().
The documentation for this struct was generated from the following file:
MovieScenePropertyTrack.h