Unreal Engine 5.6 C++ API: TStridedView< InElementType, InSizeType > Class Template Reference
TStridedView< InElementType, InSizeType > Class Template Reference
Pointer with extent and a stride, similar to TArrayView.
#include "StridedView.h"
Data Structures
struct FIterator
Public Types
using ElementType = InElementType
using SizeType = InSizeType
Public Member Functions
TStridedView ()=default
template<typename OtherElementType UE_REQUIRES>
FORCEINLINE TStridedView (const TStridedView< OtherElementType, SizeType > &Other)
template<typename OtherElementType UE_REQUIRES>
FORCEINLINE TStridedView (SizeType InBytesBetweenElements, OtherElementType *InFirstElementPtr, SizeType InNumElements)
FORCEINLINE FIterator begin () const
Ranged iteration support.
FORCEINLINE FIterator end () const
FORCEINLINE SizeType GetStride () const
FORCEINLINE ElementType & GetUnsafe (SizeType Index) const
FORCEINLINE bool IsEmpty () const
FORCEINLINE bool IsValidIndex (SizeType Index) const
FORCEINLINE SizeType Num () const
FORCEINLINE ElementType & operator[] (SizeType Index) const
Private Member Functions
FORCEINLINE ElementType * GetElementPtr (SizeType Index) const
FORCEINLINE ElementType * GetElementPtrUnsafe (SizeType Index) const
FORCEINLINE void RangeCheck (SizeType Index) const
Private Attributes
SizeType BytesBetweenElements = 0
ElementType * FirstElementPtr = nullptr
SizeType NumElements = 0
Detailed Description
template<typename InElementType, typename InSizeType>
class TStridedView< InElementType, InSizeType >
Pointer with extent and a stride, similar to TArrayView.
Designed to allow functions to take pointers to arbitrarily structured data.
Definition at line 43 of file StridedView.h.
Member Typedef Documentation
ElementType
template<typename InElementType, typename InSizeType> using TStridedView< InElementType, InSizeType >::ElementType = InElementType
Definition at line 47 of file StridedView.h.
SizeType
template<typename InElementType, typename InSizeType> using TStridedView< InElementType, InSizeType >::SizeType = InSizeType
Definition at line 48 of file StridedView.h.
Constructor & Destructor Documentation
TStridedView() [1/3]
template<typename InElementType, typename InSizeType> TStridedView< InElementType, InSizeType >::TStridedView () nodiscard default
Referenced by TStridedView().
TStridedView() [2/3]
template<typename InElementType, typename InSizeType> template<typename OtherElementType UE_REQUIRES> FORCEINLINE TStridedView< InElementType, InSizeType >::TStridedView (SizeType InBytesBetweenElements, OtherElementType * InFirstElementPtr, SizeType InNumElements) inline nodiscard
Definition at line 58 of file StridedView.h.
References BytesBetweenElements, check, FirstElementPtr, FORCEINLINE, and NumElements.
TStridedView() [3/3]
template<typename InElementType, typename InSizeType> template<typename OtherElementType UE_REQUIRES> FORCEINLINE TStridedView< InElementType, InSizeType >::TStridedView (const TStridedView< OtherElementType, SizeType > & Other) inline nodiscard
Definition at line 72 of file StridedView.h.
References TStridedView(), BytesBetweenElements, FirstElementPtr, FORCEINLINE, GetStride(), Num(), NumElements, and Other.
Member Function Documentation
begin()
template<typename InElementType, typename InSizeType> FORCEINLINE FIterator TStridedView< InElementType, InSizeType >::begin () const inline nodiscard
Ranged iteration support.
DO NOT USE DIRECTLY.
Definition at line 143 of file StridedView.h.
References FORCEINLINE.
end()
template<typename InElementType, typename InSizeType> FORCEINLINE FIterator TStridedView< InElementType, InSizeType >::end () const inline nodiscard
Definition at line 144 of file StridedView.h.
References FORCEINLINE, and Num().
GetElementPtr()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType * TStridedView< InElementType, InSizeType >::GetElementPtr (SizeType Index) const inline nodiscard private
Definition at line 163 of file StridedView.h.
References FORCEINLINE, GetElementPtrUnsafe(), and RangeCheck().
Referenced by operator[]().
GetElementPtrUnsafe()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType * TStridedView< InElementType, InSizeType >::GetElementPtrUnsafe (SizeType Index) const inline nodiscard private
Definition at line 153 of file StridedView.h.
References BytesBetweenElements, FirstElementPtr, and FORCEINLINE.
Referenced by GetElementPtr(), and GetUnsafe().
GetStride()
template<typename InElementType, typename InSizeType> FORCEINLINE SizeType TStridedView< InElementType, InSizeType >::GetStride () const inline nodiscard
Definition at line 98 of file StridedView.h.
References BytesBetweenElements, and FORCEINLINE.
Referenced by TStridedView().
GetUnsafe()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType & TStridedView< InElementType, InSizeType >::GetUnsafe (SizeType Index) const inline nodiscard
Definition at line 103 of file StridedView.h.
References FORCEINLINE, and GetElementPtrUnsafe().
IsEmpty()
template<typename InElementType, typename InSizeType> FORCEINLINE bool TStridedView< InElementType, InSizeType >::IsEmpty () const inline nodiscard
Definition at line 88 of file StridedView.h.
References FORCEINLINE, and NumElements.
IsValidIndex()
template<typename InElementType, typename InSizeType> FORCEINLINE bool TStridedView< InElementType, InSizeType >::IsValidIndex (SizeType Index) const inline nodiscard
Definition at line 83 of file StridedView.h.
References FORCEINLINE, and NumElements.
Num()
template<typename InElementType, typename InSizeType> FORCEINLINE SizeType TStridedView< InElementType, InSizeType >::Num () const inline nodiscard
Definition at line 93 of file StridedView.h.
References FORCEINLINE, and NumElements.
Referenced by TStridedView(), end(), MakeStaticMeshVertex(), RemoveInvalidVertexColor(), and RemoveInvalidVertexColor().
operator[]()
template<typename InElementType, typename InSizeType> FORCEINLINE ElementType & TStridedView< InElementType, InSizeType >::operator[] (SizeType Index) const inline nodiscard
Definition at line 108 of file StridedView.h.
References FORCEINLINE, and GetElementPtr().
RangeCheck()
template<typename InElementType, typename InSizeType> FORCEINLINE void TStridedView< InElementType, InSizeType >::RangeCheck (SizeType Index) const inline private
Definition at line 148 of file StridedView.h.
References checkf, FORCEINLINE, INT64_FMT, NumElements, and TEXT.
Referenced by GetElementPtr().
Field Documentation
BytesBetweenElements
template<typename InElementType, typename InSizeType> SizeType TStridedView< InElementType, InSizeType >::BytesBetweenElements = 0 private
Definition at line 172 of file StridedView.h.
Referenced by TStridedView(), TStridedView(), GetElementPtrUnsafe(), and GetStride().
FirstElementPtr
template<typename InElementType, typename InSizeType> ElementType* TStridedView< InElementType, InSizeType >::FirstElementPtr = nullptr private
Definition at line 171 of file StridedView.h.
Referenced by TStridedView(), TStridedView(), and GetElementPtrUnsafe().
NumElements
template<typename InElementType, typename InSizeType> SizeType TStridedView< InElementType, InSizeType >::NumElements = 0 private
Definition at line 173 of file StridedView.h.
Referenced by TStridedView(), TStridedView(), IsEmpty(), IsValidIndex(), Num(), and RangeCheck().
The documentation for this class was generated from the following file:
StridedView.h