Unreal Engine 5.6 C++ API: Margin.h File Reference
Margin.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Types/SlateEnums.h"
#include "Types/SlateVector2.h"
#include "Margin.generated.h"
Data Structures
struct TIsPODType< FMargin >
Functions
USTRUCT () struct FMargin
Describes the space around a Widget.
Function Documentation
USTRUCT()
USTRUCT ()
Describes the space around a Widget.
Holds the margin to the left.
Holds the margin to the top.
Holds the margin to the right.
Holds the margin to the bottom.
Default constructor.
The default margin size is zero on all four sides..
Construct a Margin with uniform space on all sides
Construct a Margin where Horizontal describes Left and Right spacing while Vertical describes Top and Bottom spacing
Construct a Margin where Horizontal describes Left and Right spacing while Vertical describes Top and Bottom spacing
Construct a Margin where Horizontal describes Left and Right spacing while Vertical describes Top and Bottom spacing
Construct a Margin where the spacing on each side is individually specified.
Construct a Margin where the margins are coming from a FVector4
Construct a Margin where the margins are coming from a FVector4
Multiply the margin by a scalar.
Parameters
Scale How much to scale the margin.
Returns
An FMargin where each value is scaled by Scale.
Multiply the margin by another margin functioning as the scale.
Parameters
InScale How much to scale the margin.
Returns
An FMargin where each value is scaled by Scale.
Adds another margin to this margin.
Parameters
Other The margin to add.
Returns
A margin that represents this margin plus the other margin.
Subtracts another margin from this margin.
Parameters
Other The margin to subtract.
Returns
A margin that represents this margin minues the other margin.
Compares this margin with another for equality.
Parameters
Other The other margin.
Returns
true if the two margins are equal, false otherwise.
Compares this margin with another for inequality.
Parameters
Other The other margin.
Returns
true if the two margins are not equal, false otherwise.
Gets the offset for the top left.
Returns
The top left offset.
Gets the margin's total size.
Returns
Cumulative margin size.
Gets the total horizontal or vertical margin.
Returns
Cumulative horizontal margin.
Definition at line 15 of file Margin.h.
References BlueprintType, Bottom, Category, GENERATED_USTRUCT_BODY, Horizontal, Left, operator!=(), operator*(), operator+(), operator==(), Other, Right, Scale, Top, UE_REAL_TO_FLOAT, UPROPERTY, Vertical, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.