Unreal Engine 5.6 C++ API: UE::SourceLocation Namespace Reference
UE::SourceLocation Namespace Reference
Namespaces
namespace Private
Data Structures
struct FFileAndLineAdapter
Adapter for formatting a source location as file and line only.
struct FFullAdapter
Adapter for formatting a source location with full information.
Functions
FFileAndLineAdapter FileAndLine (const FSourceLocation &Location)
Returns an adapter that formats source location with file and line only.
FFullAdapter Full (const FSourceLocation &Location)
Returns an adapter that formats source location with full information (file name, line, column, and function name).
UE_DEPRECATED (5.6, "Use UE::SourceLocation::FileAndLine(Location).ToString() instead.") static inline FString ToFileAndLineString(const FSourceLocation &Location)
Returns an owning string with source filename and line.
UE_DEPRECATED (5.6, "Use UE::SourceLocation::Full(Location).ToString() instead.") static inline FString ToFullString(const FSourceLocation &Location)
Returns an owning string with full source location information (file name, line, column, and function name).
Function Documentation
FileAndLine()
FFileAndLineAdapter UE::SourceLocation::FileAndLine (const FSourceLocation & Location) inline
Returns an adapter that formats source location with file and line only.
// Example with string:
FString LocationStr = UE::SourceLocation::FileAndLine(SourceLoc).ToString();
// Example with string builder:
Builder << "Error at " << UE::SourceLocation::FileAndLine(SourceLoc);
// Example with structured log:
UE_LOGFMT(LogCore, Warning, "Error at {Location}", UE::SourceLocation::FileAndLine(SourceLoc));
Parameters
Location The source location to adapt.
Returns
Adapter for file and line formatting.
Definition at line 159 of file SourceLocationUtils.h.
References Location.
Referenced by FStreamableDownloadCachePin::Create(), and UE_DEPRECATED().
Full()
FFullAdapter UE::SourceLocation::Full (const FSourceLocation & Location) inline
Returns an adapter that formats source location with full information (file name, line, column, and function name).
// Example with string:
FString LocationStr = UE::SourceLocation::Full(SourceLoc).ToString();
// Example with string builder:
Builder << "Error at " << UE::SourceLocation::Full(SourceLoc);
// Example with structured log:
UE_LOGFMT(LogCore, Warning, "Error at {Location}", UE::SourceLocation::Full(SourceLoc));
Parameters
Location The source location to adapt.
Returns
Adapter for full source location formatting.
Definition at line 137 of file SourceLocationUtils.h.
References Location.
UE_DEPRECATED() [1/2]
UE::SourceLocation::UE_DEPRECATED (5. 6, "Use UE::SourceLocation::FileAndLine(Location).ToString() instead.") const &
Returns an owning string with source filename and line.
Equivalent to UE_SOURCE_LOCATION.
Parameters
Location - The source location to convert to string.
Returns
Formatted string with file and line information.
Definition at line 180 of file SourceLocationUtils.h.
References FileAndLine(), Location, and UE::SourceLocation::FFileAndLineAdapter::ToString().
UE_DEPRECATED() [2/2]
UE::SourceLocation::UE_DEPRECATED (5. 6, "Use UE::SourceLocation::Full(Location).ToString() instead.") const &
Returns an owning string with full source location information (file name, line, column, and function name).
Parameters
Location - The source location to convert to string.
Returns
Formatted string with full source location information.
Definition at line 169 of file SourceLocationUtils.h.
References Full, Location, and UE::SourceLocation::FFileAndLineAdapter::ToString().