Unreal Engine 5.6 C++ API: FColorVertexBuffer Class Reference
FColorVertexBuffer Class Reference
A vertex buffer of colors.
#include "ColorVertexBuffer.h"
Public Types
enum class NullBindStride { FColorSizeForComponentOverride , ZeroForDefaultBufferBind }
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
FColorVertexBuffer ()
Default constructor.
~FColorVertexBuffer ()
Destructor.
bool AppendVertices (const FStaticMeshBuildVertex *Vertices, const uint32 NumVerticesToAppend)
Appends the specified vertices to the end of the buffer.
void BindColorVertexBuffer (const class FVertexFactory *VertexFactory, struct FStaticMeshDataType &StaticMeshData) const
void CleanUp ()
Delete existing resources.
void ClearMetaData ()
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI vertex buffer with CPU data.
void ExportText (FString &ValueStr) const
Export the data to a string, used for editor Copy&Paste.
uint32 GetAllocatedSize () const
Useful for memory profiling.
bool GetAllowCPUAccess () const
FORCEINLINE FRHIShaderResourceView * GetColorComponentsSRV () const
virtual FString GetFriendlyName () const override
FORCEINLINE uint32 GetNumVertices () const
FORCEINLINE uint32 GetStride () const
void GetVertexColors (TArray< FColor > &OutColors) const
Gets all vertex colors in the buffer.
void * GetVertexData ()
const void * GetVertexData () const
void ImportText (const TCHAR *SourceText)
Export the data from a string, used for editor Copy&Paste.
void Init (const FColorVertexBuffer &InVertexBuffer, bool bNeedsCPUAccess=true)
Initializes this vertex buffer with the contents of the given vertex buffer.
void Init (const FConstMeshBuildVertexView &InVertices, bool bNeedsCPUAccess=true)
void Init (const TArray< FStaticMeshBuildVertex > &InVertices, bool bNeedsCPUAccess=true)
Initializes the buffer with the given vertices, used to convert legacy layouts.
void Init (uint32 InNumVertices, bool bNeedsCPUAccess=true)
void InitFromColorArray (const FColor *InColors, uint32 Count, uint32 Stride=sizeof(FColor), bool bNeedsCPUAccess=true)
Load from a array of colors.
void InitFromColorArray (const TArray< FColor > &InColors)
Load from raw color array.
void InitFromSingleColor (const FColor &InColor, uint32 Count)
Load from single color.
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
void operator= (const FColorVertexBuffer &Other)
Specialized assignment operator, only used when importing LOD's.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void Serialize (FArchive &Ar, bool bNeedsCPUAccess)
Serializer.
void SerializeMetaData (FArchive &Ar)
void SetMetaData (uint32 InStride, uint32 InNumVertices)
FORCEINLINE FColor & VertexColor (uint32 VertexIndex)
FORCEINLINE const FColor & VertexColor (uint32 VertexIndex) const
Public Member Functions inherited from FVertexBuffer
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static void BindDefaultColorVertexBuffer (const class FVertexFactory *VertexFactory, struct FStaticMeshDataType &StaticMeshData, NullBindStride BindStride)
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Private Member Functions
FColorVertexBuffer (const FColorVertexBuffer &rhs)
Purposely hidden.
void AllocateData (bool bNeedsCPUAccess=true)
Allocates the vertex data storage type.
Private Attributes
FShaderResourceViewRHIRef ColorComponentsSRV
uint8 * Data
The cached vertex data pointer.
bool NeedsCPUAccess = true
uint32 NumVertices
The cached number of vertices.
uint32 Stride
The cached vertex stride.
class FColorVertexData * VertexData
The vertex data storage type.
Additional Inherited Members
Data Fields inherited from FVertexBuffer
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A vertex buffer of colors.
Definition at line 15 of file ColorVertexBuffer.h.
Member Enumeration Documentation
NullBindStride
enum class FColorVertexBuffer::NullBindStride strong
Enumerator
FColorSizeForComponentOverride
ZeroForDefaultBufferBind
Definition at line 18 of file ColorVertexBuffer.h.
Constructor & Destructor Documentation
FColorVertexBuffer() [1/2]
FColorVertexBuffer::FColorVertexBuffer ()
Default constructor.
Referenced by FColorVertexBuffer(), Init(), and operator=().
~FColorVertexBuffer()
FColorVertexBuffer::~FColorVertexBuffer ()
Destructor.
FColorVertexBuffer() [2/2]
FColorVertexBuffer::FColorVertexBuffer (const FColorVertexBuffer & rhs) private
Purposely hidden.
References FColorVertexBuffer().
Member Function Documentation
AllocateData()
void FColorVertexBuffer::AllocateData (bool bNeedsCPUAccess = true) private
Allocates the vertex data storage type.
AppendVertices()
bool FColorVertexBuffer::AppendVertices (const FStaticMeshBuildVertex * Vertices, const uint32 NumVerticesToAppend)
Appends the specified vertices to the end of the buffer.
Parameters
Vertices The vertex data to be appended. Must not be nullptr.
NumVerticesToAppend How many vertices should be added
Returns
true if append operation is successful
BindColorVertexBuffer()
void FColorVertexBuffer::BindColorVertexBuffer (const class FVertexFactory * VertexFactory, struct FStaticMeshDataType & StaticMeshData) const
References VertexFactory.
BindDefaultColorVertexBuffer()
void FColorVertexBuffer::BindDefaultColorVertexBuffer (const class FVertexFactory * VertexFactory, struct FStaticMeshDataType & StaticMeshData, NullBindStride BindStride) static
References VertexFactory.
CleanUp()
void FColorVertexBuffer::CleanUp ()
Delete existing resources.
ClearMetaData()
void FColorVertexBuffer::ClearMetaData ()
CreateRHIBuffer()
FBufferRHIRef FColorVertexBuffer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Create an RHI vertex buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
ExportText()
void FColorVertexBuffer::ExportText (FString & ValueStr) const
Export the data to a string, used for editor Copy&Paste.
The method must not be called if there is no data.
GetAllocatedSize()
uint32 FColorVertexBuffer::GetAllocatedSize () const
Useful for memory profiling.
GetAllowCPUAccess()
bool FColorVertexBuffer::GetAllowCPUAccess () const
GetColorComponentsSRV()
FORCEINLINE FRHIShaderResourceView * FColorVertexBuffer::GetColorComponentsSRV () const inline
Definition at line 162 of file ColorVertexBuffer.h.
References ColorComponentsSRV, and FORCEINLINE.
GetFriendlyName()
virtual FString FColorVertexBuffer::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FVertexBuffer.
Definition at line 157 of file ColorVertexBuffer.h.
References TEXT.
GetNumVertices()
FORCEINLINE uint32 FColorVertexBuffer::GetNumVertices () const inline
Definition at line 105 of file ColorVertexBuffer.h.
References FORCEINLINE, and NumVertices.
Referenced by FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays(), VertexColor(), and VertexColor().
GetStride()
FORCEINLINE uint32 FColorVertexBuffer::GetStride () const inline
Definition at line 101 of file ColorVertexBuffer.h.
References FORCEINLINE, and Stride.
GetVertexColors()
void FColorVertexBuffer::GetVertexColors (TArray< FColor > & OutColors) const
Gets all vertex colors in the buffer.
Parameters
OutColors The populated list of colors
GetVertexData() [1/2]
void * FColorVertexBuffer::GetVertexData () inline
Definition at line 164 of file ColorVertexBuffer.h.
References Data.
GetVertexData() [2/2]
const void * FColorVertexBuffer::GetVertexData () const inline
Definition at line 165 of file ColorVertexBuffer.h.
References Data.
ImportText()
void FColorVertexBuffer::ImportText (const TCHAR * SourceText)
Export the data from a string, used for editor Copy&Paste.
Parameters
SourceText - must not be 0
Init() [1/4]
void FColorVertexBuffer::Init (const FColorVertexBuffer & InVertexBuffer, bool bNeedsCPUAccess = true)
Initializes this vertex buffer with the contents of the given vertex buffer.
Parameters
InVertexBuffer - The vertex buffer to initialize from.
References FColorVertexBuffer().
Init() [2/4]
void FColorVertexBuffer::Init (const FConstMeshBuildVertexView & InVertices, bool bNeedsCPUAccess = true)
Init() [3/4]
void FColorVertexBuffer::Init (const TArray< FStaticMeshBuildVertex > & InVertices, bool bNeedsCPUAccess = true)
Initializes the buffer with the given vertices, used to convert legacy layouts.
Parameters
InVertices - The vertices to initialize the buffer with.
Init() [4/4]
void FColorVertexBuffer::Init (uint32 InNumVertices, bool bNeedsCPUAccess = true)
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays().
InitFromColorArray() [1/2]
void FColorVertexBuffer::InitFromColorArray (const FColor * InColors, uint32 Count, uint32 Stride = sizeof(FColor), bool bNeedsCPUAccess = true)
Load from a array of colors.
Parameters
InColors - must not be 0
Count - must be > 0
Stride - in bytes, usually sizeof(FColor) but can be 0 to use a single input color or larger.
References Count, and Stride.
Referenced by InitFromColorArray(), and InitFromSingleColor().
InitFromColorArray() [2/2]
void FColorVertexBuffer::InitFromColorArray (const TArray< FColor > & InColors) inline
Load from raw color array.
Parameters
InColors - InColors must not be empty
Definition at line 133 of file ColorVertexBuffer.h.
References TArray< InElementType, InAllocatorType >::GetData(), InitFromColorArray(), and TArray< InElementType, InAllocatorType >::Num().
InitFromSingleColor()
void FColorVertexBuffer::InitFromSingleColor (const FColor & InColor, uint32 Count) inline
Load from single color.
Parameters
Count - must be > 0
Definition at line 142 of file ColorVertexBuffer.h.
References Count, and InitFromColorArray().
InitRHI()
virtual void FColorVertexBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FColorVertexBuffer::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
References IntermediateBuffer.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
operator=()
void FColorVertexBuffer::operator= (const FColorVertexBuffer & Other)
Specialized assignment operator, only used when importing LOD's.
References FColorVertexBuffer(), and Other.
ReleaseRHI()
virtual void FColorVertexBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FVertexBuffer.
ReleaseRHIForStreaming()
void FColorVertexBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
Serialize()
void FColorVertexBuffer::Serialize (FArchive & Ar, bool bNeedsCPUAccess)
Serializer.
Parameters
Ar Archive to serialize with
bInNeedsCPUAccess Whether the elements need to be accessed by the CPU
References Ar.
SerializeMetaData()
void FColorVertexBuffer::SerializeMetaData (FArchive & Ar)
References Ar.
SetMetaData()
void FColorVertexBuffer::SetMetaData (uint32 InStride, uint32 InNumVertices)
VertexColor() [1/2]
FORCEINLINE FColor & FColorVertexBuffer::VertexColor (uint32 VertexIndex) inline
Definition at line 88 of file ColorVertexBuffer.h.
References checkSlow, Data, FORCEINLINE, GetNumVertices(), and Stride.
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
VertexColor() [2/2]
FORCEINLINE const FColor & FColorVertexBuffer::VertexColor (uint32 VertexIndex) const inline
Definition at line 94 of file ColorVertexBuffer.h.
References checkSlow, Data, FORCEINLINE, GetNumVertices(), and Stride.
Field Documentation
ColorComponentsSRV
FShaderResourceViewRHIRef FColorVertexBuffer::ColorComponentsSRV private
Definition at line 172 of file ColorVertexBuffer.h.
Referenced by GetColorComponentsSRV().
Data
uint8* FColorVertexBuffer::Data private
The cached vertex data pointer.
Definition at line 175 of file ColorVertexBuffer.h.
Referenced by GetVertexData(), GetVertexData(), VertexColor(), and VertexColor().
NeedsCPUAccess
bool FColorVertexBuffer::NeedsCPUAccess = true private
Definition at line 183 of file ColorVertexBuffer.h.
NumVertices
uint32 FColorVertexBuffer::NumVertices private
The cached number of vertices.
Definition at line 181 of file ColorVertexBuffer.h.
Referenced by GetNumVertices().
Stride
uint32 FColorVertexBuffer::Stride private
The cached vertex stride.
Definition at line 178 of file ColorVertexBuffer.h.
Referenced by GetStride(), InitFromColorArray(), VertexColor(), and VertexColor().
VertexData
class FColorVertexData* FColorVertexBuffer::VertexData private
The vertex data storage type.
Definition at line 170 of file ColorVertexBuffer.h.
The documentation for this class was generated from the following file:
ColorVertexBuffer.h