Unreal Engine 5.6 C++ Documentation: FRootMotionSource_RadialForce Struct Reference
FRootMotionSource_RadialForce Struct Reference
RadialForce applies a force pulling or pushing away from a given world location to the target.
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h>
Public Member Functions
FRootMotionSource_RadialForce ()
virtual ~FRootMotionSource_RadialForce ()
virtual FRootMotionSource * Clone () const override
virtual bool Matches (const FRootMotionSource *Other) const override
virtual bool MatchesAndHasSameState (const FRootMotionSource *Other) const override
Checks that it Matches() and has the same state (time, track position, etc.)
virtual bool UpdateStateFrom (const FRootMotionSource *SourceToTakeStateFrom, bool bMarkForSimulatedCatchup=false) override
Mainly for server correction purposes - update this Source's state from another's, usually the authoritative state from the server's version of the Source.
virtual void PrepareRootMotion (float SimulationTime, float MovementTickTime, const ACharacter &Character, const UCharacterMovementComponent &MoveComponent) override
Generates the RootMotion for this Source, can be used for both "live" generation or for playback (client prediction correction, simulated proxies, etc.)
virtual bool NetSerialize (FArchive &Ar, UPackageMap *Map, bool &bOutSuccess) override
virtual UScriptStruct * GetScriptStruct () const override
virtual FString ToSimpleString () const override
virtual void AddReferencedObjects (class FReferenceCollector &Collector) override
float GetTime () const
float GetStartTime () const
bool IsStartTimeValid () const
float GetDuration () const
virtual bool IsTimeOutEnabled () const
virtual bool IsActive () const
True when this RootMotionSource should be affecting root motion.
virtual void SetTime (float NewTime)
Set the CurrentTime of this source.
virtual void CheckTimeOut ()
Checks if this source has timed out and marks for removal if necessary.
Public Attributes
FVector Location
TObjectPtr< AActor > LocationActor
float Radius
float Strength
bool bIsPush
bool bNoZForce
TObjectPtr< UCurveFloat > StrengthDistanceFalloff
TObjectPtr< UCurveFloat > StrengthOverTime
bool bUseFixedWorldDirection
FRotator FixedWorldDirection
uint16 Priority
Priority of this source relative to other sources - higher number being the highest priority/first applied.
uint16 LocalID
ID local to this client or server instance.
FName InstanceName
This name allows us to find the source later so that we can end it.
float StartTime
Time this source should start (in character movement client time) This is used to handle cases of inconsistent tick times (ServerMoves ticking for 1 second when root motion should have only applied for the last 0.1 seconds, or root motion source ending halfway through a 0.5 second tick)
float CurrentTime
Time elapsed so far for this source.
float PreviousTime
The last Time entry we had before the last SetTime() - used for simulated catchup.
float Duration
The length of this root motion - < 0 for infinite (to be removed manually)
FRootMotionSourceStatus Status
Status of this source.
FRootMotionSourceSettings Settings
Settings of this source.
ERootMotionAccumulateMode AccumulateMode
Accumulation mode for this source (whether or not to additively apply this root motion or override completely)
bool bInLocalSpace
True when this RootMotionSource is contributing local space accumulation (false for world space)
bool bNeedsSimulatedCatchup
True when this RootMotionSource has been marked for simulated catchup - this Simulated version of the Source needs to catch up to where it was before being corrected by authoritative version.
bool bSimulatedNeedsSmoothing
True when this RootMotionSource is running on a SimulatedProxy and has marked itself as needing location/rotation smoothing.
FRootMotionMovementParams RootMotionParams
Root Motion generated by this Source.
FRootMotionFinishVelocitySettings FinishVelocityParams
Finish Velocity Parameters.
Detailed Description
RadialForce applies a force pulling or pushing away from a given world location to the target.
Definition at line 469 of file RootMotionSource.h.
Constructor & Destructor Documentation
FRootMotionSource_RadialForce()
FRootMotionSource_RadialForce::FRootMotionSource_RadialForce ()
References FRootMotionSource_RadialForce().
~FRootMotionSource_RadialForce()
virtual FRootMotionSource_RadialForce::~FRootMotionSource_RadialForce () inline virtual
Definition at line 476 of file RootMotionSource.h.
References FRootMotionSource_RadialForce().
Member Function Documentation
AddReferencedObjects()
virtual void FRootMotionSource_RadialForce::AddReferencedObjects (class FReferenceCollector & Collector) override virtual
Reimplemented from FRootMotionSource.
References AddReferencedObjects().
CheckTimeOut()
virtual void FRootMotionSource::CheckTimeOut () virtual inherited
Checks if this source has timed out and marks for removal if necessary.
Clone()
virtual FRootMotionSource * FRootMotionSource_RadialForce::Clone () const override virtual
Returns
newly allocated copy of this FRootMotionSource. Must be overridden by child classes.
Reimplemented from FRootMotionSource.
References Clone(), and FRootMotionSource::FRootMotionSource().
GetDuration()
float FRootMotionSource::GetDuration () const inherited
Returns
the Duration - the length of this root motion - < 0 for infinite (to be removed manually)
GetScriptStruct()
virtual UScriptStruct * FRootMotionSource_RadialForce::GetScriptStruct () const override virtual
Reimplemented from FRootMotionSource.
References GetScriptStruct().
GetStartTime()
float FRootMotionSource::GetStartTime () const inherited
Returns
the StartTime - time this source should start (in character movement client time)
GetTime()
float FRootMotionSource::GetTime () const inherited
Returns
the CurrentTime - amount of time elapsed so far for this source
IsActive()
virtual bool FRootMotionSource::IsActive () const virtual inherited
True when this RootMotionSource should be affecting root motion.
IsStartTimeValid()
bool FRootMotionSource::IsStartTimeValid () const inherited
Returns
whether the start time has been set
IsTimeOutEnabled()
virtual bool FRootMotionSource::IsTimeOutEnabled () const virtual inherited
Returns
whether this source will be removed when CurrentTime reaches Duration
Reimplemented in FRootMotionSource_JumpForce.
Matches()
virtual bool FRootMotionSource_RadialForce::Matches (const FRootMotionSource * Other) const override virtual
Returns
Whether this is the same RootMotionSource as Other. This is used for networking when clients receive RootMotionSource data from the server and need to decide which local RootMotionSource to compare and apply the corrections to. This is required due to RootMotionSources in general being added independently on server and clients, not needing to know about each other by default.
For well-networked RootMotionSources, any given FRootMotionSource child class could implement their own unique ID and simply use that in the Matches check. This "heuristic-style" default was chosen to simplify addition of new RootMotionSources, and assumes that in a networked setting a given RootMotionSource won't be applied many times in a given frame by the same instigator to the same target with the exact same parameters.
Guaranteed uniqueness would also require a strict application order ("RootMotionSources can only be added on Authority") or a prediction-based setup ("Apply on Autonomous and Simulated predictively, then apply on Authority and confirm, and if Authority doesn't confirm remove them"). We avoid that synchronization complexity for now.
See UCharacterMovementComponent::ConvertRootMotionServerIDsToLocalIDs
Should be overridden by child classes, as default implementation only contains basic equivalency checks
Reimplemented from FRootMotionSource.
References FRootMotionSource::FRootMotionSource(), and Matches().
MatchesAndHasSameState()
virtual bool FRootMotionSource_RadialForce::MatchesAndHasSameState (const FRootMotionSource * Other) const override virtual
Checks that it Matches() and has the same state (time, track position, etc.)
Reimplemented from FRootMotionSource.
References FRootMotionSource::FRootMotionSource(), and MatchesAndHasSameState().
NetSerialize()
virtual bool FRootMotionSource_RadialForce::NetSerialize (FArchive & Ar, UPackageMap * Map, bool & bOutSuccess) override virtual
Reimplemented from FRootMotionSource.
References NetSerialize().
PrepareRootMotion()
virtual void FRootMotionSource_RadialForce::PrepareRootMotion (float SimulationTime, float MovementTickTime, const ACharacter & Character, const UCharacterMovementComponent & MoveComponent) override virtual
Generates the RootMotion for this Source, can be used for both "live" generation or for playback (client prediction correction, simulated proxies, etc.)
Examples:
Animation RootMotionSources use Time as track time into AnimMontage and extract the root motion from AnimMontage chunk of time (Position,Position+DeltaTime)
ConstantForce source uses Time as the time into the application so if its duration ends halfway through the frame it knows how much root motion it should have applied
Spline/curve-based sources use Time for knowing where on spline/curve to extract from
Parameters
SimulationTime How far forward in time to simulate root motion
MovementTickTime How much time the movement is going to take that this is being prepared for
Reimplemented from FRootMotionSource.
References PrepareRootMotion().
SetTime()
virtual void FRootMotionSource::SetTime (float NewTime) virtual inherited
Set the CurrentTime of this source.
Use this setter so that sources based on duration can get correctly marked for end
Reimplemented in FRootMotionSource_MoveToDynamicForce, and FRootMotionSource_MoveToForce.
ToSimpleString()
virtual FString FRootMotionSource_RadialForce::ToSimpleString () const override virtual
Reimplemented from FRootMotionSource.
References ToSimpleString().
UpdateStateFrom()
virtual bool FRootMotionSource_RadialForce::UpdateStateFrom (const FRootMotionSource * SourceToTakeStateFrom, bool bMarkForSimulatedCatchup = false) override virtual
Mainly for server correction purposes - update this Source's state from another's, usually the authoritative state from the server's version of the Source.
Parameters
bMarkForSimulatedCatchup sets the source for needing to "catch up" to current state next Prepare
Returns
Whether the update was sucessful or not. Note that failure to update denotes a complete failure, and the Source will then be marked for removal. We need to remove since we don't have a way of reverting partial updates depending on where the update failed.
Reimplemented from FRootMotionSource.
References FRootMotionSource::FRootMotionSource(), and UpdateStateFrom().
Member Data Documentation
AccumulateMode
ERootMotionAccumulateMode FRootMotionSource::AccumulateMode inherited
Accumulation mode for this source (whether or not to additively apply this root motion or override completely)
Definition at line 277 of file RootMotionSource.h.
bInLocalSpace
bool FRootMotionSource::bInLocalSpace inherited
True when this RootMotionSource is contributing local space accumulation (false for world space)
Definition at line 281 of file RootMotionSource.h.
bIsPush
bool FRootMotionSource_RadialForce::bIsPush
Definition at line 491 of file RootMotionSource.h.
bNeedsSimulatedCatchup
bool FRootMotionSource::bNeedsSimulatedCatchup inherited
True when this RootMotionSource has been marked for simulated catchup - this Simulated version of the Source needs to catch up to where it was before being corrected by authoritative version.
Definition at line 287 of file RootMotionSource.h.
bNoZForce
bool FRootMotionSource_RadialForce::bNoZForce
Definition at line 494 of file RootMotionSource.h.
bSimulatedNeedsSmoothing
bool FRootMotionSource::bSimulatedNeedsSmoothing inherited
True when this RootMotionSource is running on a SimulatedProxy and has marked itself as needing location/rotation smoothing.
This smoothing logic is what runs whenever the SimulatedProxy receives a replication update from the server (SimulatedTick in CharacterMovementComponent, see bCorrectedToServer and SmoothCorrection), this flag allows the RootMotionSource to signal to the CMC that a change was done significant enough that needs smoothing.
Definition at line 296 of file RootMotionSource.h.
bUseFixedWorldDirection
bool FRootMotionSource_RadialForce::bUseFixedWorldDirection
Definition at line 503 of file RootMotionSource.h.
CurrentTime
float FRootMotionSource::CurrentTime inherited
Time elapsed so far for this source.
Definition at line 255 of file RootMotionSource.h.
Duration
float FRootMotionSource::Duration inherited
The length of this root motion - < 0 for infinite (to be removed manually)
Definition at line 263 of file RootMotionSource.h.
FinishVelocityParams
FRootMotionFinishVelocitySettings FRootMotionSource::FinishVelocityParams inherited
Finish Velocity Parameters.
Definition at line 304 of file RootMotionSource.h.
FixedWorldDirection
FRotator FRootMotionSource_RadialForce::FixedWorldDirection
Definition at line 506 of file RootMotionSource.h.
InstanceName
FName FRootMotionSource::InstanceName inherited
This name allows us to find the source later so that we can end it.
Definition at line 243 of file RootMotionSource.h.
LocalID
uint16 FRootMotionSource::LocalID inherited
ID local to this client or server instance.
Used for matching up FRootMotionSources between SavedMoves and allow a mapping between server LocalIDs and client LocalIDs for correction/comparison
Definition at line 237 of file RootMotionSource.h.
Location
FVector FRootMotionSource_RadialForce::Location
Definition at line 479 of file RootMotionSource.h.
LocationActor
TObjectPtr<AActor> FRootMotionSource_RadialForce::LocationActor
Definition at line 482 of file RootMotionSource.h.
PreviousTime
float FRootMotionSource::PreviousTime inherited
The last Time entry we had before the last SetTime() - used for simulated catchup.
Definition at line 259 of file RootMotionSource.h.
Priority
uint16 FRootMotionSource::Priority inherited
Priority of this source relative to other sources - higher number being the highest priority/first applied.
Definition at line 232 of file RootMotionSource.h.
Radius
float FRootMotionSource_RadialForce::Radius
Definition at line 485 of file RootMotionSource.h.
RootMotionParams
FRootMotionMovementParams FRootMotionSource::RootMotionParams inherited
Root Motion generated by this Source.
Definition at line 300 of file RootMotionSource.h.
Settings
FRootMotionSourceSettings FRootMotionSource::Settings inherited
Settings of this source.
Definition at line 271 of file RootMotionSource.h.
StartTime
float FRootMotionSource::StartTime inherited
Time this source should start (in character movement client time) This is used to handle cases of inconsistent tick times (ServerMoves ticking for 1 second when root motion should have only applied for the last 0.1 seconds, or root motion source ending halfway through a 0.5 second tick)
Definition at line 251 of file RootMotionSource.h.
Status
FRootMotionSourceStatus FRootMotionSource::Status inherited
Status of this source.
Definition at line 267 of file RootMotionSource.h.
Strength
float FRootMotionSource_RadialForce::Strength
Definition at line 488 of file RootMotionSource.h.
StrengthDistanceFalloff
TObjectPtr<UCurveFloat> FRootMotionSource_RadialForce::StrengthDistanceFalloff
Definition at line 497 of file RootMotionSource.h.
StrengthOverTime
TObjectPtr<UCurveFloat> FRootMotionSource_RadialForce::StrengthOverTime
Definition at line 500 of file RootMotionSource.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h