Unreal Engine 5.6 C++ API: UPoseableMeshComponent Class Reference
UPoseableMeshComponent Class Reference
#include "PoseableMeshComponent.h"
Public Member Functions
virtual bool AllocateTransformData () override
void FillComponentSpaceTransforms ()
Take the BoneSpaceTransforms array (translation vector, rotation quaternion and scale vector) and update the array of component-space bone transformation matrices (SpaceBases).
bool IsRunningParallelEvaluation () const
void MarkRefreshTransformDirty ()
virtual void RefreshBoneTransforms (FActorComponentTickFunction *TickFunction=NULL) override
virtual bool ShouldUpdateTransform (bool bLODHasChanged) const override
UFUNCTION () 1 FRotator GetBoneRotationByName(FName BoneName
UFUNCTION () 1 FTransform GetBoneTransformByName(FName BoneName
UFUNCTION () 1 FVector GetBoneLocationByName(FName BoneName
UFUNCTION () 1 FVector GetBoneScaleByName(FName BoneName
UFUNCTION () 1 void CopyPoseFromSkeletalComponent(USkeletalMeshComponent *InComponentToCopy)
UFUNCTION () 1 void ResetBoneTransformByName(FName BoneName)
UFUNCTION () 1 void SetBoneLocationByName(FName BoneName
UFUNCTION () 1 void SetBoneRotationByName(FName BoneName
UFUNCTION () 1 void SetBoneScaleByName(FName BoneName
UFUNCTION () 1 void SetBoneTransformByName(FName BoneName
Data Fields
const FTransform EBoneSpaces::Type BoneSpace
FVector EBoneSpaces::Type BoneSpace
FRotator EBoneSpaces::Type BoneSpace
EBoneSpaces::Type BoneSpace
FVector InLocation
FRotator InRotation
FVector InScale3D
const FTransform & InTransform
FBoneContainer RequiredBones
Private Member Functions
GENERATED_UCLASS_BODY () const TArray< FTransform > &GetBoneSpaceTransforms() const
Private Attributes
bool bNeedsRefreshTransform
TArray< FTransform > BoneSpaceTransforms
Temporary array of local-space (ie relative to parent bone) rotation/translation/scale for each bone.
Detailed Description
Definition at line 17 of file PoseableMeshComponent.h.
Member Function Documentation
AllocateTransformData()
virtual bool UPoseableMeshComponent::AllocateTransformData () override virtual
References AllocateTransformData().
Referenced by AllocateTransformData().
FillComponentSpaceTransforms()
void UPoseableMeshComponent::FillComponentSpaceTransforms ()
Take the BoneSpaceTransforms array (translation vector, rotation quaternion and scale vector) and update the array of component-space bone transformation matrices (SpaceBases).
It will work down hierarchy multiplying the component-space transform of the parent by the relative transform of the child. This code also applies any per-bone rotators etc. as part of the composition process
GENERATED_UCLASS_BODY()
UPoseableMeshComponent::GENERATED_UCLASS_BODY () const & inline private
Definition at line 19 of file PoseableMeshComponent.h.
References BoneSpaceTransforms.
IsRunningParallelEvaluation()
bool UPoseableMeshComponent::IsRunningParallelEvaluation () const inline
Definition at line 69 of file PoseableMeshComponent.h.
References IsRunningParallelEvaluation().
Referenced by IsRunningParallelEvaluation().
MarkRefreshTransformDirty()
void UPoseableMeshComponent::MarkRefreshTransformDirty ()
RefreshBoneTransforms()
virtual void UPoseableMeshComponent::RefreshBoneTransforms (FActorComponentTickFunction * TickFunction = NULL) override virtual
References RefreshBoneTransforms().
Referenced by RefreshBoneTransforms().
ShouldUpdateTransform()
virtual bool UPoseableMeshComponent::ShouldUpdateTransform (bool bLODHasChanged) const override virtual
References ShouldUpdateTransform().
Referenced by ShouldUpdateTransform().
UFUNCTION() [1/10]
UPoseableMeshComponent::UFUNCTION ()
References BoneSpace, Category, and UFUNCTION().
UFUNCTION() [2/10]
UPoseableMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [3/10]
UPoseableMeshComponent::UFUNCTION ()
References BoneSpace, Category, FVector, and UFUNCTION().
UFUNCTION() [4/10]
UPoseableMeshComponent::UFUNCTION ()
References BoneSpace, Category, FVector, and UFUNCTION().
UFUNCTION() [5/10]
UPoseableMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [6/10]
UPoseableMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [7/10]
UPoseableMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [8/10]
UPoseableMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [9/10]
UPoseableMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [10/10]
UPoseableMeshComponent::UFUNCTION ()
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Field Documentation
bNeedsRefreshTransform
bool UPoseableMeshComponent::bNeedsRefreshTransform private
Definition at line 80 of file PoseableMeshComponent.h.
BoneSpace [1/4]
EBoneSpaces::Type UPoseableMeshComponent::BoneSpace
Definition at line 34 of file PoseableMeshComponent.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
BoneSpace [2/4]
FVector EBoneSpaces::Type UPoseableMeshComponent::BoneSpace
Definition at line 37 of file PoseableMeshComponent.h.
BoneSpace [3/4]
FRotator EBoneSpaces::Type UPoseableMeshComponent::BoneSpace
Definition at line 40 of file PoseableMeshComponent.h.
BoneSpace [4/4]
EBoneSpaces::Type UPoseableMeshComponent::BoneSpace
Definition at line 46 of file PoseableMeshComponent.h.
BoneSpaceTransforms
TArray<FTransform> UPoseableMeshComponent::BoneSpaceTransforms private
Temporary array of local-space (ie relative to parent bone) rotation/translation/scale for each bone.
Definition at line 28 of file PoseableMeshComponent.h.
Referenced by GENERATED_UCLASS_BODY().
InLocation
FVector UPoseableMeshComponent::InLocation
Definition at line 37 of file PoseableMeshComponent.h.
InRotation
FRotator UPoseableMeshComponent::InRotation
Definition at line 40 of file PoseableMeshComponent.h.
InScale3D
FVector UPoseableMeshComponent::InScale3D
Definition at line 43 of file PoseableMeshComponent.h.
InTransform
const FTransform& UPoseableMeshComponent::InTransform
Definition at line 34 of file PoseableMeshComponent.h.
RequiredBones
FBoneContainer UPoseableMeshComponent::RequiredBones
Definition at line 31 of file PoseableMeshComponent.h.
The documentation for this class was generated from the following file:
PoseableMeshComponent.h