Unreal Engine 5.6 C++ API: UVPScoutingSubsystem Class Reference
UVPScoutingSubsystem Class Reference
#include "VPScoutingSubsystem.h"
Private Member Functions
virtual void Deinitialize () override
virtual GENERATED_BODY() public void Initialize (FSubsystemCollectionBase &Collection) override
void OnEngineInitComplete ()
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) AVREditorFloatingUI *GetPanelActor(const FName &PanelID) const
Get UI panel Actor from the passed ID.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) bool IsVRScoutingUIOpen(const FName &PanelID)
Check whether a widget UI is open.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool EnterVRMode()
Enter VR Mode.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool IsHelperSystemEnabled()
Whether the helper system on the controllers is enabled.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool IsLocationGridSnappingEnabled()
Whether location grid snapping is enabled.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool IsRotationGridSnappingEnabled()
Whether rotation grid snapping is enabled.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool IsUsingInertiaDamping()
Whether grip nav inertia is enabled when scouting in VR.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool IsUsingMetricSystem()
Whether the VR user wants to use the metric system instead of imperial.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static bool IsUsingTransformGizmo()
Whether the VR user wants to have the transform gizmo enabled.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static const FName GetVProdPanelID(const EVProdPanelIDs Panel)
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static float GetFlightSpeed()
Get flight speed for scouting in VR.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static float GetGripNavSpeed()
Get grip nav speed for scouting in VR.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static FString GetDirectorName()
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static FString GetShowName()
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static TArray< UVREditorInteractor * > GetActiveEditorVRControllers()
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static UVREditorMode *GetVREditorMode()
Get VR Editor Mode object.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void ExitVRMode()
Exit VR Mode.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetFlightSpeed(const float InFlightSpeed)
Set flight speed for scouting in VR.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetGripNavSpeed(const float InGripNavSpeed)
Set grip nav speed for scouting in VR.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetInertiaDampingCVar(const float InInertiaDamping)
Set value of cvar "VI.HighSpeedInertiaDamping".
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetIsHelperSystemEnabled(const bool bInIsHelperSystemEnabled)
Set whether the helper system on the controllers is enabled.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetIsUsingInertiaDamping(const bool bInIsUsingInertiaDamping)
Set whether grip nav inertia is enabled when scouting in VR.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetIsUsingMetricSystem(const bool bInUseMetricSystem)
Set whether the VR user wants to use the metric system instead of imperial.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetIsUsingTransformGizmo(const bool bInIsUsingTransformGizmo)
Set whether the VR user wants to have the transform gizmo enabled.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void SetShowTransformGizmoCVar(const bool bInShowTransformGizmoCVar)
Set value of cvar "VI.ShowTransformGizmo".
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void ToggleLocationGridSnapping()
Toggle location grid snapping.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) static void ToggleRotationGridSnapping()
Toggle rotation grid snapping.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) UUserWidget *GetPanelWidget(const FName &PanelID) const
Get UI panel widget from the passed ID.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) void HideInfoDisplayPanel()
Hide VR Sequencer Window.
UE_DEPRECATED (5.5,"Function will be removed from UE5.7") UFUNCTION()) void ToggleVRScoutingUI(UPARAM(ref) FVREditorFloatingUICreationContext &CreationContext)
Open a widget UI in front of the user.
UE_DEPRECATED (5.5,"Property will be removed from UE5.7") UPROPERTY()) bool IsSettingsMenuOpen
bool to keep track of whether the settings menu panel in the main menu is open
UE_DEPRECATED (5.5,"Property will be removed from UE5.7") UPROPERTY()) float GripNavSpeedCoeff
This is a multiplier for grip nav speed so we can keep the grip nav value in the range 0-1 and increase this variable if we need a bigger range.
UE_DEPRECATED (5.5,"Property will be removed from UE5.7") UPROPERTY()) TObjectPtr< UVPScoutingSubsystemGestureManagerBase > GestureManager
GestureManager that manage some user input in VR editor.
UE_DEPRECATED (5.5,"Property will be removed from UE5.7") UPROPERTY()) TObjectPtr< UVPScoutingSubsystemHelpersBase > VPSubsystemHelpers
Subsystems can't have any Blueprint implementations, so we attach this class for any BP logic that we to provide.
Private Attributes
FDelegateHandle EngineInitCompleteDelegate
Static Private Attributes
static const FName VProdPanelContextID
static const FName VProdPanelGafferID
static const FName VProdPanelID
static const FName VProdPanelLeftID
static const FName VProdPanelMeasureID
static const FName VProdPanelRightID
static const FName VProdPanelTimelineID
Detailed Description
Definition at line 85 of file VPScoutingSubsystem.h.
Member Function Documentation
Deinitialize()
virtual void UVPScoutingSubsystem::Deinitialize () override private virtual
Initialize()
virtual GENERATED_BODY() public void UVPScoutingSubsystem::Initialize (FSubsystemCollectionBase & Collection) override private virtual
OnEngineInitComplete()
void UVPScoutingSubsystem::OnEngineInitComplete () private
References OnEngineInitComplete().
Referenced by OnEngineInitComplete().
UE_DEPRECATED() [1/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const & private
Get UI panel Actor from the passed ID.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [2/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const & private
Check whether a widget UI is open.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [3/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Enter VR Mode.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [4/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Whether the helper system on the controllers is enabled.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [5/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Whether location grid snapping is enabled.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [6/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Whether rotation grid snapping is enabled.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [7/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Whether grip nav inertia is enabled when scouting in VR.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [8/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Whether the VR user wants to use the metric system instead of imperial.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [9/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Whether the VR user wants to have the transform gizmo enabled.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [10/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const inline private
Definition at line 145 of file VPScoutingSubsystem.h.
References Category, meta, UE_DEPRECATED(), UFUNCTION, VProdPanelContextID, VProdPanelGafferID, VProdPanelID, VProdPanelLeftID, VProdPanelMeasureID, VProdPanelRightID, and VProdPanelTimelineID.
UE_DEPRECATED() [11/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Get flight speed for scouting in VR.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [12/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Get grip nav speed for scouting in VR.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [13/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
References Category, meta, and UFUNCTION.
UE_DEPRECATED() [14/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [15/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [16/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Get VR Editor Mode object.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [17/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Exit VR Mode.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [18/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set flight speed for scouting in VR.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [19/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set grip nav speed for scouting in VR.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [20/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set value of cvar "VI.HighSpeedInertiaDamping".
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [21/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set whether the helper system on the controllers is enabled.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [22/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set whether grip nav inertia is enabled when scouting in VR.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [23/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set whether the VR user wants to use the metric system instead of imperial.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [24/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set whether the VR user wants to have the transform gizmo enabled.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [25/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const private
Set value of cvar "VI.ShowTransformGizmo".
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [26/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Toggle location grid snapping.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [27/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Toggle rotation grid snapping.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [28/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") const & private
Get UI panel widget from the passed ID.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [29/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") private
Hide VR Sequencer Window.
References Category, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [30/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Function will be removed from UE5.7") & private
Open a widget UI in front of the user.
Opens default VProd UI (defined via the 'Virtual Scouting User Interface' setting) if null.
References Category, meta, UE_DEPRECATED(), UFUNCTION, and UPARAM.
UE_DEPRECATED() [31/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Property will be removed from UE5.7") private
bool to keep track of whether the settings menu panel in the main menu is open
References Category, meta, UE_DEPRECATED(), and UPROPERTY.
UE_DEPRECATED() [32/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Property will be removed from UE5.7") private
This is a multiplier for grip nav speed so we can keep the grip nav value in the range 0-1 and increase this variable if we need a bigger range.
References Category, meta, UE_DEPRECATED(), and UPROPERTY.
UE_DEPRECATED() [33/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Property will be removed from UE5.7") private
GestureManager that manage some user input in VR editor.
References Category, meta, Transient, UE_DEPRECATED(), and UPROPERTY.
UE_DEPRECATED() [34/34]
UVPScoutingSubsystem::UE_DEPRECATED (5. 5, "Property will be removed from UE5.7") private
Subsystems can't have any Blueprint implementations, so we attach this class for any BP logic that we to provide.
References Category, meta, Transient, UPROPERTY, and UVPScoutingSubsystemHelpersBase.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
EngineInitCompleteDelegate
FDelegateHandle UVPScoutingSubsystem::EngineInitCompleteDelegate private
Definition at line 286 of file VPScoutingSubsystem.h.
VProdPanelContextID
const FName UVPScoutingSubsystem::VProdPanelContextID static private
Definition at line 294 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
VProdPanelGafferID
const FName UVPScoutingSubsystem::VProdPanelGafferID static private
Definition at line 297 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
VProdPanelID
const FName UVPScoutingSubsystem::VProdPanelID static private
Definition at line 291 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
VProdPanelLeftID
const FName UVPScoutingSubsystem::VProdPanelLeftID static private
Definition at line 292 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
VProdPanelMeasureID
const FName UVPScoutingSubsystem::VProdPanelMeasureID static private
Definition at line 296 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
VProdPanelRightID
const FName UVPScoutingSubsystem::VProdPanelRightID static private
Definition at line 293 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
VProdPanelTimelineID
const FName UVPScoutingSubsystem::VProdPanelTimelineID static private
Definition at line 295 of file VPScoutingSubsystem.h.
Referenced by UE_DEPRECATED().
The documentation for this class was generated from the following file:
VPScoutingSubsystem.h