Unreal Engine 5.6 C++ API: FInertializationCurve Struct Reference
FInertializationCurve Struct Reference
Public Member Functions
FInertializationCurve ()=default
FInertializationCurve (const FInertializationCurve &Other)
FInertializationCurve (FInertializationCurve &&Other)
template<typename OtherAllocator>
void InitFrom (const TBaseBlendedCurve< OtherAllocator > &Other)
FInertializationCurve & operator= (const FInertializationCurve &Other)
FInertializationCurve & operator= (FInertializationCurve &&Other)
UE_DEPRECATED (5.3, "CurveUIDToArrayIndexLUT is no longer used.") TArray< uint16 > CurveUIDToArrayIndexLUT
Data Fields
FBlendedHeapCurve BlendedCurve
Detailed Description
Definition at line 76 of file AnimNode_Inertialization.h.
Constructor & Destructor Documentation
FInertializationCurve() [1/3]
FInertializationCurve::FInertializationCurve () default
References FInertializationCurve().
Referenced by FInertializationCurve(), FInertializationCurve(), FInertializationCurve(), operator=(), and operator=().
FInertializationCurve() [2/3]
FInertializationCurve::FInertializationCurve (const FInertializationCurve & Other) inline
Definition at line 85 of file AnimNode_Inertialization.h.
References FInertializationCurve(), and Other.
FInertializationCurve() [3/3]
FInertializationCurve::FInertializationCurve (FInertializationCurve && Other) inline
Definition at line 90 of file AnimNode_Inertialization.h.
References FInertializationCurve(), MoveTemp(), and Other.
Member Function Documentation
InitFrom()
template<typename OtherAllocator> void FInertializationCurve::InitFrom (const TBaseBlendedCurve< OtherAllocator > & Other) inline
Definition at line 108 of file AnimNode_Inertialization.h.
References BlendedCurve, and Other.
operator=() [1/2]
FInertializationCurve & FInertializationCurve::operator= (const FInertializationCurve & Other) inline
Definition at line 95 of file AnimNode_Inertialization.h.
References FInertializationCurve(), BlendedCurve, and Other.
operator=() [2/2]
FInertializationCurve & FInertializationCurve::operator= (FInertializationCurve && Other) inline
Definition at line 101 of file AnimNode_Inertialization.h.
References FInertializationCurve(), BlendedCurve, and Other.
UE_DEPRECATED()
FInertializationCurve::UE_DEPRECATED (5. 3, "CurveUIDToArrayIndexLUT is no longer used.")
Field Documentation
BlendedCurve
FBlendedHeapCurve FInertializationCurve::BlendedCurve
Definition at line 78 of file AnimNode_Inertialization.h.
Referenced by InitFrom(), operator=(), and operator=().
The documentation for this struct was generated from the following file:
AnimNode_Inertialization.h