Unreal Engine 5.6 C++ API: TSlotBase< SlotType > Class Template Reference
TSlotBase< SlotType > Class Template Reference
A slot that can be used by the declarative syntax.
#include "SlotBase.h"
Data Structures
struct FSlotArguments
Struct to construct a slot.
Public Types
enum EConstructSlotIsFChildren { ConstructSlotIsFChildren }
Argument to indicate the Slot is also its owner.
Public Member Functions
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
SlotType & Expose (SlotType *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
SlotType & operator[] (const TSharedRef< SWidget > &InChildWidget)
SlotType & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Additional Inherited Members
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Detailed Description
template<typename SlotType>
class TSlotBase< SlotType >
A slot that can be used by the declarative syntax.
Definition at line 121 of file SlotBase.h.
Member Enumeration Documentation
EConstructSlotIsFChildren
template<typename SlotType> enum TSlotBase::EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Enumerator
ConstructSlotIsFChildren
Definition at line 145 of file SlotBase.h.
Member Function Documentation
Construct()
template<typename SlotType> void TSlotBase< SlotType >::Construct (const FChildren & SlotOwner, FSlotArguments && InArgs) inline
Definition at line 212 of file SlotBase.h.
References FSlotBase::AttachWidget(), and FSlotBase::SetOwner().
Referenced by SUniformGridPanel::FSlot::Construct(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::Construct(), and TWidgetSlotWithAttributeSupport< SlotType >::Construct().
Expose()
template<typename SlotType> SlotType & TSlotBase< SlotType >::Expose (SlotType *& OutVarToInit) inline
Definition at line 137 of file SlotBase.h.
FSlotBase() [1/4]
template<typename SlotType> FSlotBase::FSlotBase ()
Referenced by TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::GetSlotAt().
FSlotBase() [2/4]
template<typename SlotType> FSlotBase::FSlotBase (const FChildren & InParent)
FSlotBase() [3/4]
template<typename SlotType> FSlotBase::FSlotBase (const FSlotBase &) delete
FSlotBase() [4/4]
template<typename SlotType> FSlotBase::FSlotBase (const TSharedRef< SWidget > & InWidget)
operator[]() [1/2]
template<typename SlotType> SlotType & TSlotBase< SlotType >::operator[] (const TSharedRef< SWidget > & InChildWidget) inline
Definition at line 131 of file SlotBase.h.
References FSlotBase::AttachWidget().
operator[]() [2/2]
template<typename SlotType> SlotType & TSlotBase< SlotType >::operator[] (TSharedRef< SWidget > && InChildWidget) inline
Definition at line 126 of file SlotBase.h.
References FSlotBase::AttachWidget(), and MoveTemp().
The documentation for this class was generated from the following file:
SlotBase.h