Unreal Engine 5.6 C++ API: Metasound::FAnyDataReference Class Reference
Metasound::FAnyDataReference Class Reference
Container for any data reference.
#include "MetasoundDataReference.h"
Data Structures
struct TGetAs
TGetAs allows for template specialization of data retrieval and conversion rules for the various flavors of data referencing.
struct TGetAs< TDataReadReference< DataType > >
struct TGetAs< TDataValueReference< DataType > >
struct TGetAs< TDataWriteReference< DataType > >
Public Member Functions
FAnyDataReference (const FAnyDataReference &InOther)
Copy construct with a FAnyDataReference.
template<typename DataType>
FAnyDataReference (const TDataReadReference< DataType > &InDataRef)
Construct with a TDataReadReference.
template<typename DataType>
FAnyDataReference (const TDataValueReference< DataType > &InDataRef)
Construct with a TDataValueReference.
template<typename DataType>
FAnyDataReference (const TDataWriteReference< DataType > &InDataRef)
Construct with a TDataWriteReference.
virtual TUniquePtr< IDataReference > Clone () const override
Returns a clone of the underlying data reference.
EDataReferenceAccessType GetAccessType () const
Returns the access type of the underlying data reference.
template<typename ReturnType>
ReturnType GetAs () const
Return the data in the specified format.
template<typename DataType>
TDataReadReference< DataType > GetDataReadReference () const
Get access to a TDataReadReference.
virtual const void *const GetDataTypeId () const override
Returns the data type ID of the underlying data reference.
virtual const FName & GetDataTypeName () const override
Returns the data type name of the underlying data reference.
template<typename DataType>
TDataValueReference< DataType > GetDataValueReference () const
Get access to a TDataValueReference.
template<typename DataType>
TDataWriteReference< DataType > GetDataWriteReference () const
Get access to a TDataWriteReference.
void * GetRaw () const
Return a raw pointer to the data.
template<typename DataType>
const DataType * GetValue () const
Returns the current value of a reference.
template<typename DataType>
DataType * GetWritableValue () const
Return a non-const pointer to the data.
FAnyDataReference & operator= (const FAnyDataReference &InOther)
Assignment.
Public Member Functions inherited from Metasound::IDataReference
virtual ~IDataReference ()=default
Private Member Functions
FAnyDataReference (EDataReferenceAccessType InAccessType, const IDataReference &InDataRef)
Private Attributes
EDataReferenceAccessType AccessType = EDataReferenceAccessType::None
TUniquePtr< IDataReference > DataRefPtr
Additional Inherited Members
Static Public Attributes inherited from Metasound::IDataReference
static METASOUNDGRAPHCORE_API const FName RouterName
Detailed Description
Container for any data reference.
This container maintains the underlying containers access type (Read or Write) and data type. This allows for convenient storage by implementing a virtual copy constructor and assignment operator.
Definition at line 544 of file MetasoundDataReference.h.
Constructor & Destructor Documentation
FAnyDataReference() [1/5]
Metasound::FAnyDataReference::FAnyDataReference (EDataReferenceAccessType InAccessType, const IDataReference & InDataRef) inline private
Definition at line 664 of file MetasoundDataReference.h.
References AccessType, check, Clone(), DataRefPtr, and Metasound::None.
Referenced by FAnyDataReference(), FAnyDataReference(), FAnyDataReference(), FAnyDataReference(), and operator=().
FAnyDataReference() [2/5]
template<typename DataType> Metasound::FAnyDataReference::FAnyDataReference (const TDataReadReference< DataType > & InDataRef) inline
Construct with a TDataReadReference.
Definition at line 675 of file MetasoundDataReference.h.
References FAnyDataReference(), and Metasound::Read.
FAnyDataReference() [3/5]
template<typename DataType> Metasound::FAnyDataReference::FAnyDataReference (const TDataWriteReference< DataType > & InDataRef) inline
Construct with a TDataWriteReference.
Definition at line 682 of file MetasoundDataReference.h.
References FAnyDataReference(), and Metasound::Write.
FAnyDataReference() [4/5]
template<typename DataType> Metasound::FAnyDataReference::FAnyDataReference (const TDataValueReference< DataType > & InDataRef) inline
Construct with a TDataValueReference.
Definition at line 689 of file MetasoundDataReference.h.
References FAnyDataReference(), and Metasound::Value.
FAnyDataReference() [5/5]
Metasound::FAnyDataReference::FAnyDataReference (const FAnyDataReference & InOther) inline
Copy construct with a FAnyDataReference.
Definition at line 695 of file MetasoundDataReference.h.
References FAnyDataReference(), AccessType, and DataRefPtr.
Member Function Documentation
Clone()
virtual TUniquePtr< IDataReference > Metasound::FAnyDataReference::Clone () const inline override virtual
Returns a clone of the underlying data reference.
Implements Metasound::IDataReference.
Definition at line 733 of file MetasoundDataReference.h.
References check, and DataRefPtr.
Referenced by FAnyDataReference().
GetAccessType()
EDataReferenceAccessType Metasound::FAnyDataReference::GetAccessType () const inline
Returns the access type of the underlying data reference.
Definition at line 713 of file MetasoundDataReference.h.
References AccessType.
GetAs()
template<typename ReturnType> ReturnType Metasound::FAnyDataReference::GetAs () const inline
Return the data in the specified format.
The template argument can be any of the support TData*Reference<> types, the underlying DataType or a const DataType* pointer.
Definition at line 751 of file MetasoundDataReference.h.
References AccessType, check, DataRefPtr, and Metasound::FAnyDataReference::TGetAs< ResultType >::Get().
Referenced by GetDataReadReference(), GetDataValueReference(), GetDataWriteReference(), and GetValue().
GetDataReadReference()
template<typename DataType> TDataReadReference< DataType > Metasound::FAnyDataReference::GetDataReadReference () const inline
Get access to a TDataReadReference.
This method will return a valid TDataReadReference of the templated data type. The returned object is only valid if:
The template parameter DataType matches that of the underlying data reference.
The underlying data reference is has Read, Write or Value access.
If this method's behavior is undefined and will assert if it is called with a mismatched data type or unsupported access type.
Definition at line 827 of file MetasoundDataReference.h.
References GetAs().
Referenced by Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::TVertexAnalyzerForwardValue(), Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreatePassThroughDataReference(), and Metasound::FDataReferenceCollection::GetDataReadReference().
GetDataTypeId()
virtual const void *const Metasound::FAnyDataReference::GetDataTypeId () const inline override virtual
Returns the data type ID of the underlying data reference.
Implements Metasound::IDataReference.
Definition at line 726 of file MetasoundDataReference.h.
References check, and DataRefPtr.
GetDataTypeName()
virtual const FName & Metasound::FAnyDataReference::GetDataTypeName () const inline override virtual
Returns the data type name of the underlying data reference.
Implements Metasound::IDataReference.
Definition at line 719 of file MetasoundDataReference.h.
References check, and DataRefPtr.
GetDataValueReference()
template<typename DataType> TDataValueReference< DataType > Metasound::FAnyDataReference::GetDataValueReference () const inline
Get access to a TDataValueReference.
This method will return a valid TDataValueReference of the templated data type. The returned object is only valid if:
The template parameter DataType matches that of the underlying data reference.
The underlying data reference is has Value access.
If this method's behavior is undefined and will assert if it is called with a mismatched data type or unsupported access type.
Definition at line 810 of file MetasoundDataReference.h.
References check, DataRefPtr, and GetAs().
Referenced by Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreatePassThroughDataReference().
GetDataWriteReference()
template<typename DataType> TDataWriteReference< DataType > Metasound::FAnyDataReference::GetDataWriteReference () const inline
Get access to a TDataWriteReference.
This method will return a valid TDataWriteReference of the templated data type. The returned object is only valid if:
The template paramter DataType matches that of the underlying data reference.
The underlying data reference is has Write access.
If this method's behavior is undefined and will assert if it is called with a mismatched data type or unsupported access type.
Definition at line 843 of file MetasoundDataReference.h.
References GetAs().
Referenced by Metasound::FDataReferenceCollection::GetDataWriteReference().
GetRaw()
void * Metasound::FAnyDataReference::GetRaw () const inline virtual
Return a raw pointer to the data.
Implements Metasound::IDataReference.
Definition at line 740 of file MetasoundDataReference.h.
References check, and DataRefPtr.
GetValue()
template<typename DataType> const DataType * Metasound::FAnyDataReference::GetValue () const inline
Returns the current value of a reference.
This method's behavior is undefined and an assert will be called if the DataType differs from the underlying data reference's DataType.
Definition at line 770 of file MetasoundDataReference.h.
References DataRefPtr, and GetAs().
GetWritableValue()
template<typename DataType> DataType * Metasound::FAnyDataReference::GetWritableValue () const inline
Return a non-const pointer to the data.
If the vertex is bound with this will return a valid pointer. Otherwise it will return a nullptr. This method will assert if the reference is bound, but not writable or if the data type does match.
Definition at line 787 of file MetasoundDataReference.h.
References AccessType, check, checkf, DataRefPtr, Metasound::TDataWriteReference< DataType >::Get(), Metasound::IsDataReferenceOfType(), TEXT, and Metasound::Write.
operator=()
FAnyDataReference & Metasound::FAnyDataReference::operator= (const FAnyDataReference & InOther) inline
Assignment.
Definition at line 701 of file MetasoundDataReference.h.
References FAnyDataReference(), AccessType, check, DataRefPtr, and Metasound::None.
Field Documentation
AccessType
EDataReferenceAccessType Metasound::FAnyDataReference::AccessType = EDataReferenceAccessType::None private
Definition at line 850 of file MetasoundDataReference.h.
Referenced by FAnyDataReference(), FAnyDataReference(), GetAccessType(), GetAs(), GetWritableValue(), and operator=().
DataRefPtr
TUniquePtr<IDataReference> Metasound::FAnyDataReference::DataRefPtr private
Definition at line 851 of file MetasoundDataReference.h.
Referenced by FAnyDataReference(), FAnyDataReference(), Clone(), GetAs(), GetDataTypeId(), GetDataTypeName(), GetDataValueReference(), GetRaw(), GetValue(), GetWritableValue(), and operator=().
The documentation for this class was generated from the following file:
MetasoundDataReference.h