Unreal Engine 5.6 C++ API: TObjectIterator< T > Class Template Reference
TObjectIterator< T > Class Template Reference
Class for iterating through all objects which inherit from a specified base class.
#include "UObjectIterator.h"
Public Types
enum EEndTagType { EndTag }
Public Member Functions
TObjectIterator (EEndTagType, const TObjectIterator &Begin)
Constructor.
TObjectIterator (EObjectFlags AdditionalExclusionFlags=RF_ClassDefaultObject, bool bIncludeDerivedClasses=true, EInternalObjectFlags InInternalExclusionFlags=EInternalObjectFlags::None)
Constructor.
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const TObjectIterator &Rhs) const
FUNCTION_NON_NULL_RETURN_START FORCEINLINE T * operator* () const FUNCTION_NON_NULL_RETURN_END
Iterator dereference.
FORCEINLINE void operator++ ()
Iterator advance.
FUNCTION_NON_NULL_RETURN_START FORCEINLINE T * operator-> () const FUNCTION_NON_NULL_RETURN_END
Iterator dereference.
FORCEINLINE bool operator== (const TObjectIterator &Rhs) const
Protected Member Functions
FORCEINLINE bool Advance ()
Iterator advance with ordinary name for clarity in subclasses.
FORCEINLINE UObject * GetObject () const
Dereferences the iterator with an ordinary name for clarity in derived classes.
Protected Attributes
int32 Index
index of the current element in the object array
TArray< UObject * > ObjectArray
Results from the GetObjectsOfClass query.
Detailed Description
template<class T>
class TObjectIterator< T >
Class for iterating through all objects which inherit from a specified base class.
Does not include any class default objects. Note that when Playing In Editor, this will find objects in the editor as well as the PIE world, in an indeterminate order.
Definition at line 252 of file UObjectIterator.h.
Member Enumeration Documentation
EEndTagType
template<class T> enum TObjectIterator::EEndTagType
Enumerator
EndTag
Definition at line 255 of file UObjectIterator.h.
Constructor & Destructor Documentation
TObjectIterator() [1/2]
template<class T> TObjectIterator< T >::TObjectIterator (EObjectFlags AdditionalExclusionFlags = RF_ClassDefaultObject, bool bIncludeDerivedClasses = true, EInternalObjectFlags InInternalExclusionFlags = EInternalObjectFlags::None) inline explicit
Constructor.
Definition at line 263 of file UObjectIterator.h.
References Advance(), GetObjectIteratorDefaultInternalExclusionFlags(), GetObjectsOfClass(), Index, None, ObjectArray, and RF_ClassDefaultObject.
Referenced by TObjectIterator(), operator!=(), and operator==().
TObjectIterator() [2/2]
template<class T> TObjectIterator< T >::TObjectIterator (EEndTagType , const TObjectIterator< T > & Begin) inline
Constructor.
Definition at line 273 of file UObjectIterator.h.
References TObjectIterator(), Index, Num, and ObjectArray.
Member Function Documentation
Advance()
template<class T> FORCEINLINE bool TObjectIterator< T >::Advance () inline protected
Iterator advance with ordinary name for clarity in subclasses.
Returns
true if the iterator points to a valid object, false if iteration is complete
Definition at line 336 of file UObjectIterator.h.
References FORCEINLINE, GetObject(), Index, and ObjectArray.
Referenced by TObjectIterator(), and operator++().
GetObject()
template<class T> FORCEINLINE UObject * TObjectIterator< T >::GetObject () const inline protected
Dereferences the iterator with an ordinary name for clarity in derived classes.
Returns
the UObject at the iterator
Definition at line 327 of file UObjectIterator.h.
References FORCEINLINE, Index, and ObjectArray.
Referenced by Advance(), operator*(), and operator->().
operator bool()
template<class T> FORCEINLINE TObjectIterator< T >::operator bool () const inline explicit
Conversion to "bool" returning true if the iterator is valid.
Definition at line 287 of file UObjectIterator.h.
References FORCEINLINE, Index, and ObjectArray.
operator!()
template<class T> FORCEINLINE bool TObjectIterator< T >::operator! () const inline
Conversion to "bool" returning true if the iterator is valid.
Definition at line 292 of file UObjectIterator.h.
References bool, and FORCEINLINE.
operator!=()
template<class T> FORCEINLINE bool TObjectIterator< T >::operator!= (const TObjectIterator< T > & Rhs) const inline
Definition at line 319 of file UObjectIterator.h.
References TObjectIterator(), FORCEINLINE, and Index.
operator*()
template<class T> FUNCTION_NON_NULL_RETURN_START FORCEINLINE T * TObjectIterator< T >::operator* () const inline
Iterator dereference.
Returns
the object pointer pointed at by the iterator
Definition at line 302 of file UObjectIterator.h.
References FORCEINLINE, FUNCTION_NON_NULL_RETURN_END, and GetObject().
operator++()
template<class T> FORCEINLINE void TObjectIterator< T >::operator++ () inline
Iterator advance.
Definition at line 281 of file UObjectIterator.h.
References Advance(), and FORCEINLINE.
operator->()
template<class T> FUNCTION_NON_NULL_RETURN_START FORCEINLINE T * TObjectIterator< T >::operator-> () const inline
Iterator dereference.
Returns
the object pointer pointed at by the iterator
Definition at line 312 of file UObjectIterator.h.
References FORCEINLINE, FUNCTION_NON_NULL_RETURN_END, and GetObject().
operator==()
template<class T> FORCEINLINE bool TObjectIterator< T >::operator== (const TObjectIterator< T > & Rhs) const inline
Definition at line 318 of file UObjectIterator.h.
References TObjectIterator(), FORCEINLINE, and Index.
Field Documentation
Index
template<class T> int32 TObjectIterator< T >::Index protected
index of the current element in the object array
Definition at line 353 of file UObjectIterator.h.
Referenced by TObjectIterator(), TObjectIterator(), Advance(), GetObject(), operator bool(), operator!=(), and operator==().
ObjectArray
template<class T> TArray<UObject*> TObjectIterator< T >::ObjectArray protected
Results from the GetObjectsOfClass query.
Definition at line 351 of file UObjectIterator.h.
Referenced by TObjectIterator(), TObjectIterator(), Advance(), GetObject(), and operator bool().
The documentation for this class was generated from the following file:
UObjectIterator.h