Unreal Engine 5.6 C++ API: FEditorModeFactory Struct Reference
FEditorModeFactory Struct Reference
#include "EditorModeRegistry.h"
Public Member Functions
UNREALED_API FEditorModeFactory (const FEditorModeInfo &InModeInfo)
UNREALED_API FEditorModeFactory (FEditorModeInfo &&InModeInfo)
virtual UNREALED_API ~FEditorModeFactory ()
virtual UNREALED_API TSharedRef< FEdMode > CreateMode () const final
Create a new instance of our mode.
virtual UNREALED_API FEditorModeInfo GetModeInfo () const final
Gets the information pertaining to the mode type that this factory creates.
Public Member Functions inherited from IEditorModeFactory
virtual ~IEditorModeFactory ()
Virtual destructor.
virtual void OnSelectionChanged (FEditorModeTools &Tools, UObject *ItemUndergoingChange) const
Allows mode factories to handle selection change events, and potentially activate/deactivate modes.
Public Member Functions inherited from TSharedFromThis< IEditorModeFactory >
TSharedRef< IEditorModeFactory, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IEditorModeFactory, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FEditorModeFactoryCallback FactoryCallback
Callback used to create an instance of this mode type.
FEditorModeInfo ModeInfo
Information pertaining to this factory's mode.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IEditorModeFactory >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IEditorModeFactory >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 59 of file EditorModeRegistry.h.
Constructor & Destructor Documentation
FEditorModeFactory() [1/2]
UNREALED_API FEditorModeFactory::FEditorModeFactory (const FEditorModeInfo & InModeInfo)
Referenced by FEditorModeRegistry::RegisterMode().
FEditorModeFactory() [2/2]
UNREALED_API FEditorModeFactory::FEditorModeFactory (FEditorModeInfo && InModeInfo)
~FEditorModeFactory()
virtual UNREALED_API FEditorModeFactory::~FEditorModeFactory () virtual
Member Function Documentation
CreateMode()
virtual UNREALED_API TSharedRef< FEdMode > FEditorModeFactory::CreateMode () const final virtual
Create a new instance of our mode.
Implements IEditorModeFactory.
References CreateMode().
Referenced by CreateMode().
GetModeInfo()
virtual UNREALED_API FEditorModeInfo FEditorModeFactory::GetModeInfo () const final virtual
Gets the information pertaining to the mode type that this factory creates.
Implements IEditorModeFactory.
Field Documentation
FactoryCallback
FEditorModeFactoryCallback FEditorModeFactory::FactoryCallback
Callback used to create an instance of this mode type.
Definition at line 70 of file EditorModeRegistry.h.
ModeInfo
FEditorModeInfo FEditorModeFactory::ModeInfo
Information pertaining to this factory's mode.
Definition at line 67 of file EditorModeRegistry.h.
The documentation for this struct was generated from the following file:
EditorModeRegistry.h