Unreal Engine 5.6 C++ API: FProcState Struct Reference
FProcState Struct Reference
Wrapper around Unix pid_t.
#include "MacPlatformProcess.h"
Public Member Functions
FORCEINLINE FProcState ()
Default constructor.
FORCEINLINE FProcState ()
Default constructor.
FProcState (pid_t InProcessId, bool bInFireAndForget)
Initialization constructor.
FProcState (pid_t InProcessId, bool bInFireAndForget)
Initialization constructor.
~FProcState ()
Destructor.
~FProcState ()
Destructor.
FORCEINLINE pid_t GetProcessId () const
Getter for process id.
FORCEINLINE pid_t GetProcessId () const
Getter for process id.
bool GetReturnCode (int32 *ReturnCodePtr)
Returns child's return code (only valid to call if not running)
bool GetReturnCode (int32 *ReturnCodePtr)
Returns child's return code (only valid to call if not running)
bool IsRunning ()
Returns whether this process is running.
bool IsRunning ()
Returns whether this process is running.
void Wait ()
Waits for the process to end.
void Wait ()
Waits for the process to end.
Protected Member Functions
FORCEINLINE FProcState (const FProcState &Other)
Copy constructor - should not be publicly accessible.
FORCEINLINE FProcState (const FProcState &Other)
Copy constructor - should not be publicly accessible.
FORCEINLINE FProcState & operator= (const FProcState &Other)
Assignment operator - should not be publicly accessible.
FORCEINLINE FProcState & operator= (const FProcState &Other)
Assignment operator - should not be publicly accessible.
Protected Attributes
bool bFireAndForget
Whether this child is fire-and-forget.
bool bHasBeenWaitedFor
Whether the process's return code has been collected.
bool bIsRunning
Whether the process has finished or not (cached)
pid_t ProcessId
Process id.
int32 ReturnCode
Return code of the process (if negative, means that process did not finish gracefully but was killed/crashed.
Friends
struct FUnixPlatformProcess
Detailed Description
Wrapper around Unix pid_t.
Should not be copyable as changes in the process state won't be properly propagated to all copies.
Definition at line 13 of file MacPlatformProcess.h.
Constructor & Destructor Documentation
FProcState() [1/6]
FORCEINLINE FProcState::FProcState () inline
Default constructor.
Definition at line 16 of file MacPlatformProcess.h.
References bFireAndForget, bHasBeenWaitedFor, bIsRunning, FORCEINLINE, ProcessId, and ReturnCode.
Referenced by FProcState(), and operator=().
FProcState() [2/6]
FProcState::FProcState (pid_t InProcessId, bool bInFireAndForget) explicit
Initialization constructor.
~FProcState() [1/2]
FProcState::~FProcState ()
Destructor.
FProcState() [3/6]
FORCEINLINE FProcState::FProcState (const FProcState & Other) inline protected
Copy constructor - should not be publicly accessible.
Definition at line 64 of file MacPlatformProcess.h.
References FProcState(), bFireAndForget, bHasBeenWaitedFor, bIsRunning, checkf, FORCEINLINE, Other, ProcessId, ReturnCode, and TEXT.
FProcState() [4/6]
FORCEINLINE FProcState::FProcState () inline
Default constructor.
Definition at line 23 of file UnixPlatformProcess.h.
References bFireAndForget, bHasBeenWaitedFor, bIsRunning, FORCEINLINE, ProcessId, and ReturnCode.
FProcState() [5/6]
FProcState::FProcState (pid_t InProcessId, bool bInFireAndForget) explicit
Initialization constructor.
~FProcState() [2/2]
FProcState::~FProcState ()
Destructor.
FProcState() [6/6]
FORCEINLINE FProcState::FProcState (const FProcState & Other) inline protected
Copy constructor - should not be publicly accessible.
Definition at line 71 of file UnixPlatformProcess.h.
References FProcState(), bFireAndForget, bHasBeenWaitedFor, bIsRunning, checkf, FORCEINLINE, Other, ProcessId, ReturnCode, and TEXT.
Member Function Documentation
GetProcessId() [1/2]
FORCEINLINE pid_t FProcState::GetProcessId () const inline
Getter for process id.
Definition at line 32 of file MacPlatformProcess.h.
References FORCEINLINE, and ProcessId.
GetProcessId() [2/2]
FORCEINLINE pid_t FProcState::GetProcessId () const inline
Getter for process id.
Definition at line 39 of file UnixPlatformProcess.h.
References FORCEINLINE, and ProcessId.
GetReturnCode() [1/2]
bool FProcState::GetReturnCode (int32 * ReturnCodePtr)
Returns child's return code (only valid to call if not running)
Parameters
ReturnCode set to return code if not NULL (use the value only if method returned true)
Returns
return whether we have the return code (we don't if it crashed)
GetReturnCode() [2/2]
bool FProcState::GetReturnCode (int32 * ReturnCodePtr)
Returns child's return code (only valid to call if not running)
Parameters
ReturnCode set to return code if not NULL (use the value only if method returned true)
Returns
return whether we have the return code (we don't if it crashed)
IsRunning() [1/2]
bool FProcState::IsRunning ()
Returns whether this process is running.
Returns
true if running
IsRunning() [2/2]
bool FProcState::IsRunning ()
Returns whether this process is running.
Returns
true if running
operator=() [1/2]
FORCEINLINE FProcState & FProcState::operator= (const FProcState & Other) inline protected
Assignment operator - should not be publicly accessible.
Definition at line 75 of file MacPlatformProcess.h.
References FProcState(), checkf, FORCEINLINE, Other, and TEXT.
operator=() [2/2]
FORCEINLINE FProcState & FProcState::operator= (const FProcState & Other) inline protected
Assignment operator - should not be publicly accessible.
Definition at line 82 of file UnixPlatformProcess.h.
References FProcState(), checkf, FORCEINLINE, Other, and TEXT.
Wait() [1/2]
void FProcState::Wait ()
Waits for the process to end.
Has a side effect (stores child's return code).
Wait() [2/2]
void FProcState::Wait ()
Waits for the process to end.
Has a side effect (stores child's return code).
Friends And Related Symbol Documentation
FUnixPlatformProcess
friend struct FUnixPlatformProcess friend
Definition at line 88 of file UnixPlatformProcess.h.
References bFireAndForget, bHasBeenWaitedFor, bIsRunning, FUnixPlatformProcess, ProcessId, and ReturnCode.
Referenced by FUnixPlatformProcess.
Field Documentation
bFireAndForget
bool FProcState::bFireAndForget protected
Whether this child is fire-and-forget.
Definition at line 96 of file MacPlatformProcess.h.
Referenced by FProcState(), FProcState(), and FUnixPlatformProcess.
bHasBeenWaitedFor
bool FProcState::bHasBeenWaitedFor protected
Whether the process's return code has been collected.
Definition at line 90 of file MacPlatformProcess.h.
Referenced by FProcState(), FProcState(), and FUnixPlatformProcess.
bIsRunning
bool FProcState::bIsRunning protected
Whether the process has finished or not (cached)
Definition at line 87 of file MacPlatformProcess.h.
Referenced by FProcState(), FProcState(), and FUnixPlatformProcess.
ProcessId
pid_t FProcState::ProcessId protected
Process id.
Definition at line 84 of file MacPlatformProcess.h.
Referenced by FProcState(), FProcState(), FUnixPlatformProcess, and GetProcessId().
ReturnCode
int32 FProcState::ReturnCode protected
Return code of the process (if negative, means that process did not finish gracefully but was killed/crashed.
Definition at line 93 of file MacPlatformProcess.h.
Referenced by FProcState(), FProcState(), and FUnixPlatformProcess.
The documentation for this struct was generated from the following files:
MacPlatformProcess.h
UnixPlatformProcess.h