Unreal Engine 5.6 C++ API: TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType > Struct Template Reference
TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType > Struct Template Reference
Iterator used when iterating all paths in the tree, both added or implied.
#include "DirectoryTree.h"
Public Member Functions
operator bool () const
bool operator!= (const FIterationSentinel &) const
TPair< FStringView, ViewedValueType * > operator* () const
TPointerIterator & operator++ ()
TArrowWrapper< TPair< FStringView, ViewedValueType * > > operator-> () const
Private Member Functions
TPointerIterator (FTreeNode &Root, EDirectoryTreeGetFlags InFlags, TCHAR InPathSeparator)
Private Attributes
FIteratorInternal Internal
Friends
class TDirectoryTree< ValueType >
Detailed Description
template<typename ValueType>
template<typename ViewedValueType>
struct TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >
Iterator used when iterating all paths in the tree, both added or implied.
The return value of operator* has a (possibly const) ValueType*, which will be non-null for all paths that were added to the tree and null for the implied parent directories that were not added.
Definition at line 238 of file DirectoryTree.h.
Constructor & Destructor Documentation
TPointerIterator()
template<typename ValueType> template<typename ViewedValueType> TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::TPointerIterator (FTreeNode & Root, EDirectoryTreeGetFlags InFlags, TCHAR InPathSeparator) inline private
Definition at line 1872 of file DirectoryTree.h.
References TPointerIterator(), and TDirectoryTree< ValueType >::Root.
Referenced by TPointerIterator().
Member Function Documentation
operator bool()
template<typename ValueType> template<typename ViewedValueType> TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::operator bool () const inline explicit
Definition at line 1914 of file DirectoryTree.h.
operator!=()
template<typename ValueType> template<typename ViewedValueType> bool TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::operator!= (const FIterationSentinel &) const inline
Definition at line 1898 of file DirectoryTree.h.
References operator!=().
Referenced by operator!=().
operator*()
template<typename ValueType> template<typename ViewedValueType> TPair< FStringView, ViewedValueType * > TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::operator* () const inline
Definition at line 1881 of file DirectoryTree.h.
References check, and operator*().
Referenced by operator*().
operator++()
template<typename ValueType> template<typename ViewedValueType> TDirectoryTree< ValueType >::template TPointerIterator< ViewedValueType > & TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::operator++ () inline
Definition at line 1906 of file DirectoryTree.h.
References operator++().
Referenced by operator++().
operator->()
template<typename ValueType> template<typename ViewedValueType> TArrowWrapper< TPair< FStringView, ViewedValueType * > > TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::operator-> () const inline
Definition at line 1891 of file DirectoryTree.h.
References operator->().
Referenced by operator->().
Friends And Related Symbol Documentation
TDirectoryTree< ValueType >
template<typename ValueType> template<typename ViewedValueType> friend class TDirectoryTree< ValueType > friend
Definition at line 248 of file DirectoryTree.h.
Field Documentation
Internal
template<typename ValueType> template<typename ViewedValueType> FIteratorInternal TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::Internal private
Definition at line 252 of file DirectoryTree.h.
The documentation for this struct was generated from the following file:
DirectoryTree.h