Unreal Engine 5.6 C++ API: SmartObjectSubsystem.h File Reference
SmartObjectSubsystem.h File Reference
#include "SmartObjectDefinitionReference.h"
#include "SmartObjectPersistentCollection.h"
#include "SmartObjectRuntime.h"
#include "WorldConditionContext.h"
#include "Subsystems/WorldSubsystem.h"
#include "AI/Navigation/NavigationTypes.h"
#include "AI/Navigation/NavQueryFilter.h"
#include "Misc/MTAccessDetector.h"
#include "MassExternalSubsystemTraits.h"
#include "SmartObjectSubsystem.generated.h"
Macros
#define WITH_SMARTOBJECT_MT_INSTANCE_LOCK 0
Typedefs
using FSmartObjectSlotNavigationLocationResult = FSmartObjectSlotEntranceLocationResult
Functions
DECLARE_MULTICAST_DELEGATE (FOnMainCollectionEvent)
Called when an event related to the main collection occured.
UENUM() enum class FSmartObjectSlotEntrySelectionMethod USTRUCT () struct FSmartObjectSlotEntranceHandle
Defines method for selecting slot entry from multiple candidates.
Macro Definition Documentation
WITH_SMARTOBJECT_MT_INSTANCE_LOCK
#define WITH_SMARTOBJECT_MT_INSTANCE_LOCK 0
Definition at line 16 of file SmartObjectSubsystem.h.
Typedef Documentation
FSmartObjectSlotNavigationLocationResult
using FSmartObjectSlotNavigationLocationResult = FSmartObjectSlotEntranceLocationResult
Definition at line 262 of file SmartObjectSubsystem.h.
Function Documentation
DECLARE_MULTICAST_DELEGATE()
DECLARE_MULTICAST_DELEGATE (FOnMainCollectionEvent)
Called when an event related to the main collection occured.
References First.
USTRUCT()
UENUM() enum class FSmartObjectSlotEntrySelectionMethod USTRUCT ()
Defines method for selecting slot entry from multiple candidates.
Validated result from FindEntranceLocationForSlot().
Struct used to request slot entry or exit location.
Handle describing a specific entrance on a smart object slot.
When used with actor, it is generally enough to set the UserActor. In that case NavigationData, ValidationFilter, and UserCapsule are queried via the INavAgentInterface and USmartObjectUserComponent on the actor if they are not set.
If the user actor is not available (e.g. with Mass), then ValidationFilter and UserCapsule must be defined, and if bProjectNavigationLocation is set NavigationData must be valid.
The location validation is done in following order:
navigation projection
trace ground location (uses altered location from navigation test if applicable)
check transition trajectory (test between unmodified navigation location and slow location)
Actor that is using the smart object slot. (Optional)
Filter to use for the validation. If not set and UserActor is valid, the filter is queried via USmartObjectUserComponent.
Navigation data to use for the navigation queries. If not set and UserActor is valid, the navigation data is queried via INavAgentInterface.
Size of the user of the smart object. If not set and UserActor is valid, the dimensions are queried via INavAgentInterface.
Search location that may be used to select an entry from multiple candidates. (e.g. user actor location).
How to select an entry when a slot has multiple entries.
Enum indicating if we're looking for a location to enter or exit the smart object slot.
If true, try to project the location on navigable area. If projection fails, an entry is discarded.
If true, try to trace the location on ground. If trace fails, an entry is discarded.
If true, check collisions between navigation location and slot location. If collisions are found, an entry is discarded.
If true, check user capsule collisions at the entrance location. Uses capsule dimensions set in the validation filter.
If true, check user capsule collisions at the slot location. Uses capsule dimensions set in an annotation on the slot.
If true, include slot location as a candidate if no navigation annotation is present.
If true, the result rotation will only contain rotation around the UP axis (i.e., Yaw only; Pitch and Roll set to 0).
Returns
entry as nav location.
true if the result contains valid navigation node reference.
The location to enter the slot.
The expected direction to enter the slot.
Node reference in navigation data (if requested with bMustBeNavigable).
Gameplay tag associated with the entrance.
Gameplay tags associated with the entrance.
Handle identifying the entrance that was found.
True if the result has passed validation tests.
Definition at line 63 of file SmartObjectSubsystem.h.
References BlueprintType, Category, check, GENERATED_BODY, Invalid, IsValid(), meta, operator!=(), operator==(), Other, and UPROPERTY.