Unreal Engine 5.6 C++ API: Metasound::Frontend::IDataTypeRegistryEntry Class Reference
Metasound::Frontend::IDataTypeRegistryEntry Class Reference abstract
Registry entry interface for a MetaSound data type.
#include "MetasoundFrontendDataTypeRegistry.h"
Public Member Functions
virtual ~IDataTypeRegistryEntry ()=default
virtual TUniquePtr< INode > CreateConstructorInputNode (FNodeData InNodeData) const =0
Create a constructor input node.
virtual TUniquePtr< INode > CreateConstructorOutputNode (FNodeData InNodeData) const =0
Create a constructor output node.
virtual TSharedPtr< IDataChannel, ESPMode::ThreadSafe > CreateDataChannel (const FOperatorSettings &) const =0
Create a data channel for transmission.
virtual TOptional< FAnyDataReference > CreateDataReference (EDataReferenceAccessType InAccessType, const FLiteral &InLiteral, const FOperatorSettings &InOperatorSettings) const =0
Create a data reference from a literal.
virtual TUniquePtr< INode > CreateInputNode (FNodeData InNodeData) const =0
Create an input node.
virtual TUniquePtr< INode > CreateOutputNode (FNodeData InNodeData) const =0
Create an output node.
virtual TSharedPtr< Audio::IProxyData > CreateProxy (UObject *InObject) const =0
Create a proxy from a UObject.
virtual TUniquePtr< INode > CreateVariableAccessorNode (FNodeData) const =0
Create a get variable node for this data type.
virtual TUniquePtr< INode > CreateVariableDeferredAccessorNode (FNodeData) const =0
Create a get delayed variable node for this data type.
virtual TUniquePtr< INode > CreateVariableMutatorNode (FNodeData) const =0
Create a set variable node for this data type.
virtual TUniquePtr< INode > CreateVariableNode (FLiteral InInitValue, FNodeData) const =0
Create a init variable node for this data type.
virtual TSharedPtr< const FNodeClassMetadata > GetConstructorInputClassMetadata () const =0
Return an FNodeClassMetadata representing an input node of the data type.
virtual TSharedPtr< const FNodeClassMetadata > GetConstructorOutputClassMetadata () const =0
Return an FNodeClassMetadata representing an input node of the data type.
virtual const FDataTypeRegistryInfo & GetDataTypeInfo () const =0
Return the FDataTypeRegistryInfo for the data type.
virtual TSharedPtr< const IEnumDataTypeInterface > GetEnumInterface () const =0
Return the enum interface for the data type.
virtual const FMetasoundFrontendClass & GetFrontendConstructorInputClass () const =0
Return an FMetasoundFrontendClass representing an input node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendConstructorOutputClass () const =0
Return an FMetasoundFrontendClass representing an input node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendInputClass () const =0
Return an FMetasoundFrontendClass representing an input node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendLiteralClass () const =0
Return an FMetasoundFrontendClass representing a variable node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendOutputClass () const =0
Return an FMetasoundFrontendClass representing an output node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendVariableAccessorClass () const =0
Return an FMetasoundFrontendClass representing an get variable node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendVariableClass () const =0
Return an FMetasoundFrontendClass representing an init variable node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendVariableDeferredAccessorClass () const =0
Return an FMetasoundFrontendClass representing an get delayed variable node of the data type.
virtual const FMetasoundFrontendClass & GetFrontendVariableMutatorClass () const =0
Return an FMetasoundFrontendClass representing an set variable node of the data type.
virtual TSharedPtr< const FNodeClassMetadata > GetInputClassMetadata () const =0
Return an FNodeClassMetadata representing an input node of the data type.
virtual FLiteralAssignmentFunction GetLiteralAssignmentFunction () const =0
virtual TSharedPtr< const FNodeClassMetadata > GetOutputClassMetadata () const =0
Return an FNodeClassMetadata representing an output node of the data type.
virtual const IParameterAssignmentFunction & GetRawAssignmentFunction () const =0
virtual TSharedPtr< const FNodeClassMetadata > GetVariableAccessorClassMetadata () const =0
Return an FNodeClassMetadata representing an get variable node of the data type.
virtual TSharedPtr< const FNodeClassMetadata > GetVariableClassMetadata () const =0
Return an FNodeClassMetadata representing an init variable node of the data type.
virtual TSharedPtr< const FNodeClassMetadata > GetVariableDeferredAccessorClassMetadata () const =0
Return an FNodeClassMetadata representing an get delayed variable node of the data type.
virtual TSharedPtr< const FNodeClassMetadata > GetVariableMutatorClassMetadata () const =0
Return an FNodeClassMetadata representing an set variable node of the data type.
UE_DEPRECATED (5.6, "Cloning is not required for IDataTypeRegistryEntries") virtual TUniquePtr< IDataTypeRegistryEntry > Clone() const
Clone this registry entry.
UE_DEPRECATED (5.6, "Create constructor input nodes with FNodeData") virtual TUniquePtr< INode > CreateConstructorInputNode(FInputNodeConstructorParams &&) const =0
Create an constructor input node.
UE_DEPRECATED (5.6, "Create constructor output nodes with FNodeData") virtual TUniquePtr< INode > CreateConstructorOutputNode(FOutputNodeConstructorParams &&) const =0
Create an output node.
UE_DEPRECATED (5.6, "Create input nodes with FNodeData") virtual TUniquePtr< INode > CreateInputNode(FInputNodeConstructorParams &&) const =0
Create an input node.
UE_DEPRECATED (5.6, "Create output nodes with FNodeData") virtual TUniquePtr< INode > CreateOutputNode(FOutputNodeConstructorParams &&) const =0
Create an output node.
UE_DEPRECATED (5.6, "Create variable accessor nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableAccessorNode(const FNodeInitData &) const =0
Create a get variable node for this data type.
UE_DEPRECATED (5.6, "Create variable deferred accessor nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableDeferredAccessorNode(const FNodeInitData &) const =0
Create a get delayed variable node for this data type.
UE_DEPRECATED (5.6, "Create variable mutator nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableMutatorNode(const FNodeInitData &) const =0
Create a set variable node for this data type.
UE_DEPRECATED (5.6, "Create variable nodes with FNodeData") virtual TUniquePtr< INode > CreateVariableNode(FVariableNodeConstructorParams &&InInitParams) const =0
Create a init variable node for this data type.
UE_DEPRECATED (5.6, "Direct creation of literal nodes will no longer be supported") virtual TUniquePtr< INode > CreateLiteralNode(FLiteralNodeConstructorParams &&) const =0
Create a variable node.
UE_DEPRECATED (5.6, "Direct creation of receive nodes will no longer be supported") virtual TUniquePtr< INode > CreateReceiveNode(const FNodeInitData &) const =0
Create a receive node for this data type.
Detailed Description
Registry entry interface for a MetaSound data type.
Definition at line 138 of file MetasoundFrontendDataTypeRegistry.h.
Constructor & Destructor Documentation
~IDataTypeRegistryEntry()
virtual Metasound::Frontend::IDataTypeRegistryEntry::~IDataTypeRegistryEntry () virtual default
Member Function Documentation
CreateConstructorInputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateConstructorInputNode (FNodeData InNodeData) const pure virtual
Create a constructor input node.
References CreateConstructorInputNode().
Referenced by CreateConstructorInputNode(), and UE_DEPRECATED().
CreateConstructorOutputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateConstructorOutputNode (FNodeData InNodeData) const pure virtual
Create a constructor output node.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
References CreateConstructorOutputNode().
Referenced by CreateConstructorOutputNode(), and UE_DEPRECATED().
CreateDataChannel()
virtual TSharedPtr< IDataChannel, ESPMode::ThreadSafe > Metasound::Frontend::IDataTypeRegistryEntry::CreateDataChannel (const FOperatorSettings &) const pure virtual
Create a data channel for transmission.
If this data type does not support transmission, return a nullptr.
References CreateDataChannel(), and ThreadSafe.
Referenced by CreateDataChannel().
CreateDataReference()
virtual TOptional< FAnyDataReference > Metasound::Frontend::IDataTypeRegistryEntry::CreateDataReference (EDataReferenceAccessType InAccessType, const FLiteral & InLiteral, const FOperatorSettings & InOperatorSettings) const pure virtual
Create a data reference from a literal.
References CreateDataReference().
Referenced by CreateDataReference().
CreateInputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateInputNode (FNodeData InNodeData) const pure virtual
Create an input node.
References CreateInputNode().
Referenced by CreateInputNode(), and UE_DEPRECATED().
CreateOutputNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateOutputNode (FNodeData InNodeData) const pure virtual
Create an output node.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
References CreateOutputNode().
Referenced by CreateOutputNode(), and UE_DEPRECATED().
CreateProxy()
virtual TSharedPtr< Audio::IProxyData > Metasound::Frontend::IDataTypeRegistryEntry::CreateProxy (UObject * InObject) const pure virtual
Create a proxy from a UObject.
If this data type does not support UObject proxies, return a nullptr.
References CreateProxy().
Referenced by CreateProxy().
CreateVariableAccessorNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateVariableAccessorNode (FNodeData) const pure virtual
Create a get variable node for this data type.
References CreateVariableAccessorNode().
Referenced by CreateVariableAccessorNode(), and UE_DEPRECATED().
CreateVariableDeferredAccessorNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateVariableDeferredAccessorNode (FNodeData) const pure virtual
Create a get delayed variable node for this data type.
References CreateVariableDeferredAccessorNode().
Referenced by CreateVariableDeferredAccessorNode(), and UE_DEPRECATED().
CreateVariableMutatorNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateVariableMutatorNode (FNodeData) const pure virtual
Create a set variable node for this data type.
References CreateVariableMutatorNode().
Referenced by CreateVariableMutatorNode(), and UE_DEPRECATED().
CreateVariableNode()
virtual TUniquePtr< INode > Metasound::Frontend::IDataTypeRegistryEntry::CreateVariableNode (FLiteral InInitValue, FNodeData) const pure virtual
Create a init variable node for this data type.
Parameters
InInitValue - A literal used to create the variable.
References CreateVariableNode().
Referenced by CreateVariableNode(), and UE_DEPRECATED().
GetConstructorInputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetConstructorInputClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an input node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetConstructorOutputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetConstructorOutputClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an input node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetDataTypeInfo()
virtual const FDataTypeRegistryInfo & Metasound::Frontend::IDataTypeRegistryEntry::GetDataTypeInfo () const pure virtual
Return the FDataTypeRegistryInfo for the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetEnumInterface()
virtual TSharedPtr< const IEnumDataTypeInterface > Metasound::Frontend::IDataTypeRegistryEntry::GetEnumInterface () const pure virtual
Return the enum interface for the data type.
If the data type does not support an enum interface, the returned pointer should be invalid.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendConstructorInputClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendConstructorInputClass () const pure virtual
Return an FMetasoundFrontendClass representing an input node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendConstructorOutputClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendConstructorOutputClass () const pure virtual
Return an FMetasoundFrontendClass representing an input node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendInputClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendInputClass () const pure virtual
Return an FMetasoundFrontendClass representing an input node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendLiteralClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendLiteralClass () const pure virtual
Return an FMetasoundFrontendClass representing a variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendOutputClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendOutputClass () const pure virtual
Return an FMetasoundFrontendClass representing an output node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendVariableAccessorClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendVariableAccessorClass () const pure virtual
Return an FMetasoundFrontendClass representing an get variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendVariableClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendVariableClass () const pure virtual
Return an FMetasoundFrontendClass representing an init variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendVariableDeferredAccessorClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendVariableDeferredAccessorClass () const pure virtual
Return an FMetasoundFrontendClass representing an get delayed variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetFrontendVariableMutatorClass()
virtual const FMetasoundFrontendClass & Metasound::Frontend::IDataTypeRegistryEntry::GetFrontendVariableMutatorClass () const pure virtual
Return an FMetasoundFrontendClass representing an set variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetInputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetInputClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an input node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetLiteralAssignmentFunction()
virtual FLiteralAssignmentFunction Metasound::Frontend::IDataTypeRegistryEntry::GetLiteralAssignmentFunction () const pure virtual
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
References GetLiteralAssignmentFunction().
Referenced by GetLiteralAssignmentFunction().
GetOutputClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetOutputClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an output node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetRawAssignmentFunction()
virtual const IParameterAssignmentFunction & Metasound::Frontend::IDataTypeRegistryEntry::GetRawAssignmentFunction () const pure virtual
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
References GetRawAssignmentFunction().
Referenced by GetRawAssignmentFunction().
GetVariableAccessorClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetVariableAccessorClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an get variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetVariableClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetVariableClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an init variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetVariableDeferredAccessorClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetVariableDeferredAccessorClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an get delayed variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
GetVariableMutatorClassMetadata()
virtual TSharedPtr< const FNodeClassMetadata > Metasound::Frontend::IDataTypeRegistryEntry::GetVariableMutatorClassMetadata () const pure virtual
Return an FNodeClassMetadata representing an set variable node of the data type.
Implemented in Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::FDataTypeRegistryEntryBase.
UE_DEPRECATED() [1/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Cloning is not required for IDataTypeRegistryEntries") const inline
Clone this registry entry.
Definition at line 290 of file MetasoundFrontendDataTypeRegistry.h.
References UE_DEPRECATED().
UE_DEPRECATED() [2/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create constructor input nodes with FNodeData") const && pure virtual
Create an constructor input node.
References CreateConstructorInputNode(), and UE_DEPRECATED().
UE_DEPRECATED() [3/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create constructor output nodes with FNodeData") const && pure virtual
Create an output node.
References CreateConstructorOutputNode(), and UE_DEPRECATED().
UE_DEPRECATED() [4/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create input nodes with FNodeData") const && pure virtual
Create an input node.
References CreateInputNode().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create output nodes with FNodeData") const && pure virtual
Create an output node.
References CreateOutputNode(), and UE_DEPRECATED().
UE_DEPRECATED() [6/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create variable accessor nodes with FNodeData") const & pure virtual
Create a get variable node for this data type.
References CreateVariableAccessorNode(), and UE_DEPRECATED().
UE_DEPRECATED() [7/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create variable deferred accessor nodes with FNodeData") const & pure virtual
Create a get delayed variable node for this data type.
References CreateVariableDeferredAccessorNode(), and UE_DEPRECATED().
UE_DEPRECATED() [8/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create variable mutator nodes with FNodeData") const & pure virtual
Create a set variable node for this data type.
References CreateVariableMutatorNode(), and UE_DEPRECATED().
UE_DEPRECATED() [9/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Create variable nodes with FNodeData") const && pure virtual
Create a init variable node for this data type.
Parameters
InInitParams - Contains a literal used to create the variable.
References CreateVariableNode(), and UE_DEPRECATED().
UE_DEPRECATED() [10/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Direct creation of literal nodes will no longer be supported") const && pure virtual
Create a variable node.
References UE_DEPRECATED().
UE_DEPRECATED() [11/11]
Metasound::Frontend::IDataTypeRegistryEntry::UE_DEPRECATED (5. 6, "Direct creation of receive nodes will no longer be supported") const & pure virtual
Create a receive node for this data type.
References UE_DEPRECATED().
The documentation for this class was generated from the following file:
MetasoundFrontendDataTypeRegistry.h