Unreal Engine 5.6 C++ API: UE::MovieScene Namespace Reference
UE::MovieScene Namespace Reference
Namespaces
namespace Internal
namespace Interpolation
This file contains structures that represent specific interpolation algorithms for either a continuous or discrete range.
namespace Private
Data Structures
struct CBatchGroupingPolicy
Concept that checks whether a grouping policy supports batch operations based on the presence of a InitializeGroupKeys function.
struct FAccumulatedWeightedValue
Holds an accumulation of weighted values.
struct FAccumulationBuffers
Struct that maintains accumulation buffers for each blend type, one buffer per float result component type.
struct FAccumulationResult
Structure for holding the blend results of each blend type.
struct FActiveSkeletalAnimation
Information for a single skeletal animation playing on a bound object.
struct FAdd
Implemtntation of an untyped add payload.
struct FAddConditional
Implemtntation of a contitional untyped add payload.
struct FAdditiveAndOverrideBuffer
Bufffer used for additive/override values.
struct FAdditiveAndOverrides
Structure for holding the sorted blending order data for the additive and override data.
struct FAdditiveFromBaseBuffer
Buffer used for accumulating additive-from-base values.
struct FAdditveAndOverrideData
struct FAddMany
Implemtntation of an untyped add payload.
struct FAddMultipleMutation
struct FAddSingleMutation
struct FAnimatedCustomPrimitiveDataInfo
struct FAnimatedMaterialParameterInfo
struct FAnimTypePreAnimatedStateObjectStorage
struct FAnimTypePreAnimatedStateRootStorage
struct FAttachmentComponent
struct FBlendResult
Blend result struct that stores the cumulative sum of pre-weighted values, alongside the total weight.
struct FBoneTransformFinalizeData
DelegateHandle and Skeletal Mesh for bone transform finalized.
struct FBoolPropertyTraits
struct FBoundObjectActiveSkeletalAnimations
Information for all skeletal animations playing on a bound object.
struct FBoundObjectPreAnimatedStateTraits
Group state class that groups pre-animated storage together by bound object.
struct FBoundObjectTask
struct FBuiltInComponentTypes
Pre-defined built in component types.
struct FCachedEntityFilterResult_Allocations
Cached filter result that caches pointers to allocations matching the specified filter.
struct FCachedEntityFilterResult_Match
Simple cached filter results that stores whether its filter passes or not.
struct FCachedEntityManagerState
Small utility struct that caches the entity manager's structural serial number to generated cached data NOTE: Must only be used with a single entity manager.
struct FCachePreAnimatedValueParams
struct FCameraCutPlaybackCapability
Playback capability for sequences that can run camera cuts.
struct FCameraCutPlaybackCapabilityCompatibilityWrapper
struct FCameraShakePreviewerLinkerExtension
Linker extension for storing camera shake previewers shared between the instantiator and the evaluation systems below.
struct FChannelOverrideEntityImportParams
Entity import parameters for a channel override.
struct FChannelOverrideNames
Utility class to convert channel names to indices.
struct FChannelOverrideProviderTraits
struct FChannelOwnerCapabilities
struct FChildEntityFactory
struct FChildEntityInitializer
struct FColorPropertyTraits
struct FCommonEntityTaskParams
struct FCompiledDataVolatilityManager
struct FComplexInclusivityFilter
Filter used for specifying more complex mutual inclusivity rules that depend on more than one component type.
struct FComponentAccess
struct FComponentAttachParams
struct FComponentAttachParamsDestination
struct FComponentDetachParams
struct FComponentMask
struct FComponentMaterialAccessor
struct FComponentMaterialKey
struct FComponentRegistry
struct FComponentTransformPreAnimatedTraits
struct FComponentTypeID
struct FComponentTypeIDFilter
struct FComponentTypeInfo
Complete type information for a component within an FEntityManager This structure defines how to interact with the component data for operations such as copying, relocating, initializing, destructing and reference collection.
struct FCompositePropertyTypeID
struct FConstPropertyComponentView
Type-erased view of a constant component.
struct FCustomAccessorView
struct FCustomPropertyAccessor
struct FCustomPropertyIndex
struct FCycleParams
struct FDataEventScope
struct FDecomposedValue
A structure for holding all the values of channels contributing to an animated property.
struct FDecompositionQuery
Structure used to decompose the blended result of multiple components.
struct FDirectedGraph
Directed graph represented as a bitarray for allocated nodes, and edges defined by pairs of integers (from->to).
struct FDirectedGraphStringParameters
struct FDoubleIntermediateVector
struct FDoubleVectorPropertyTraits
struct FEntityAllocationIterator
Object that iterates all entity allocations that match a specific filter.
struct FEntityAllocationIteratorProxy
Iterator proxy type returned from FEntityManager::Iterate that supports ranged-for iteration of all entity allocations matching the specified filter.
struct FEntityFactories
A class that contains all the component factory relationships.
struct FEntityGroupBuilder
Utility class used by the grouping system's policies (see below) to manage groups.
struct FEntityGroupID
The component data for describing what group an entity belongs to (see UMovieSceneEntityGroupingSystem)
struct FEntityGroupingPolicyKey
The key to a grouping policy registered on the grouping system (see UMovieSceneEntityGroupingSystem)
struct FEntityHandle
struct FEntityIDAccess
struct FEntityImportParams
struct FEntityImportSequenceParams
struct FEntityIterationResult
Utility that promotes callbacks that return void to always return 'true' when iterating entities.
struct FEntityLedger
An entity ledger is responsible for tracking the entites that have been imported for the currently relevant frame of a sequence instance.
class FEntityManager
Top-level manager class that is responsible for all entity data and interaction/.
struct FEntityOutputAggregate
Aggregate of multiple input entities for an output defined in a TOverlappingEntityTracker.
struct FEntitySystemLinkerExtensionID
Base extension identifier for a UMovieSceneEntitySystemLinker.
struct FEntitySystemMaybeAtomicInt32
A potentially atomic struct that will perform atomic operations if required on an underlying integer, depending on what EEntityThreadingModel was specified.
struct FEntityTaskBuilder
Main entry point utility for create tasks that run over component data.
struct FErasedOptionalReadAccess
struct FErasedReadAccess
struct FErasedWriteAccess
struct FEvaluatedTime
struct FEvaluationHookFlags
struct FEvaluationHookParams
struct FEvaluationTreePopulationRules
struct FEventTriggerControlPlaybackCapability
Playback capability for controlling how events are triggered.
struct FFadeComponentData
struct FFilterMatchPassthrough
struct FFixedObjectBindingID
A binding ID that is only resolveable through a fixed root sequence.
struct FFloatIntermediateVector
Intermediate type for the vector property system that lets us store how many dimensions the vector should have.
struct FFloatPropertyTraits
struct FFloatVectorPropertyTraits
struct FFrameRateRetiming
struct FFreeEntityOperation
struct FGarbageTraits
struct FHierarchicalBlendTarget
Specifies a unique, sorted path of hbiases that contribute to a blended output Supports up to 8 unique HBiases in its path.
struct FHierarchicalEasingChannelBuffer
struct FHierarchicalEasingChannelData
Computation data used for accumulating hierarchical weights for sub sequences.
struct FImportedEntity
struct FInitialValueCache
Container that houses initial values for any properties animated through FEntityManager Each type is stored in its own container, organized by the initial value component ID The cache is stored as a singleton (through GetSharedInitialValues()) and added as an extension to UMovieSceneEntitySystemLinker where it is active.
struct FInitialValueIndex
Type-safe index that defines a unique index of an initial value within a TPropertyValueStorage instance This struct is added as a component to all entities with initial values inside non-interrogated linkers.
struct FInstanceHandle
A handle to an active instance of a UMovieSceneSequence.
struct FInstanceRegistry
Core concept that is required by all entities and systems - should be located on the core system manager itself.
struct FIntegerAccumulationBuffers
Struct that maintains accumulation buffers for each blend type.
struct FIntegerBlendResult
Blend result struct that stores the cumulative sum of pre-weighted values, alongside the total weight.
struct FIntermediate3DTransform
Intermediate type used for applying partially animated transforms.
struct FIntermediateColor
Intermediate type for the color property system that lets us store what kind of color type we should use.
struct FInterrogationChannelInfo
class FInterrogationChannels
A class specialized for interrogating Sequencer entity data without applying any state to objects.
struct FInterrogationParams
struct FInterrogationUpdateParams
struct FInverseTransformTimeParams
Parameter structure that controls inverse-time-transformation operations in MovieScene code.
struct FMaterialParameterCollectionScalarTraits
struct FMaterialParameterCollectionVectorTraits
struct FMaterialParameterKey
struct FMontagePlayerPerSectionData
Temporary information about montage setups.
struct FMovieSceneBindingLifetimeComponentData
struct FMovieSceneEntityID
struct FMovieSceneTracksComponentTypes
struct FMutualComponentInitializers
Container for keeping track of which initializers need to be run for a given call to FMutualInclusivityGraphCommandBuffer::ComputeMutuallyInclusiveComponents.
struct FMutualInclusivityGraph
A mutual inclusion graph for adding components to an entity based on the presence of other components.
struct FMutualInclusivityGraphCommandBuffer
Command buffer used for computing mutually inclusive components based on a complex set of rules and dependencies.
struct FMutuallyInclusiveComponentParams
struct FNewComponentTypeParams
struct FNoopTask
struct FObjectComponent
A component that represents a UObject* either as a strong or weak reference.
struct FObjectFactoryBatch
struct FObjectPropertyTraits
struct FOnCameraCutUpdatedParams
Parameter struct for notifying a playback client that a camera cut has happened.
struct FOptionalComponentAccess
struct FOptionalReadAccess
struct FOptionalWriteAccess
struct FPiecewiseCurve
A piecewise curve represented as an array of interpolations.
struct FPiecewiseCurveData
class FPiecewiseCurveModel
struct FPlaybackCapabilities
Actual playback capabilities container.
struct FPlaybackCapabilitiesImpl
Basic, mostly untyped, implementation of the capabilities buffer.
struct FPlaybackCapabilityHeader
Header that describes an entry in the capabilities buffer.
struct FPlaybackCapabilityHelpers
struct FPlaybackCapabilityID
An identifier for a playback capability.
struct FPlaybackCapabilityIDInfo
Structure providing basic information on a playback capability type.
class FPlaybackCapabilityIDRegistry
A registry for all known playback capability types.
struct FPlaybackCapabilityPtr
Return value for accessing raw capabalities.
struct FPlayerIndexPlaybackCapability
Playback capability for storing an IMovieScenePlayer unique index.
struct FPoseSearchTracksComponentTypes
struct FPreAnimatedComponentMaterialParameterStorage
struct FPreAnimatedComponentMaterialSwitcherStorage
struct FPreAnimatedComponentMobilityStorage
struct FPreAnimatedComponentTransformStorage
struct FPreAnimatedEntityCaptureSource
Structure responsible for tracking contributions to pre-animated state entries that originate from ECS data (ie, from FMovieSceneEntityIDs)
struct FPreAnimatedEvalHookKeyType
Key type for pre-animated state associated to evaluation hooks.
struct FPreAnimatedEvaluationHookCaptureSources
Structure responsible for tracking contributions to pre-eanimated state entries that originate from track EvaluationHooks (ie, from an IMovieSceneExecutionToken::Execute)
struct FPreAnimatedEvaluationKeyType
Key type for pre-animated state associated to evaluation templates.
struct FPreAnimatedMobilityTraits
struct FPreAnimatedObjectGroupManager
struct FPreAnimatedObjectTokenTraits
struct FPreAnimatedRootTokenTraits
struct FPreAnimatedScalarMaterialParameterStorage
struct FPreAnimatedStateCachedValueHandle
A handle to a particular pre-animated value within a FPreAnimatedStateExtension instance.
struct FPreAnimatedStateEntry
Specifies an entry to a specific piece of pre-animated state within a FPreAnimatedStateExtension instance.
struct FPreAnimatedStateExtension
Pre-animated state extension that houses all cached values for objects animated by a specific UMovieSceneEntitySystemLinker.
struct FPreAnimatedStateMetaData
Meta-data pertaining to a specific animating source (could be a FMovieSceneEntityID, FMovieSceneEvaluationKey, UMovieSceneTrackInstance etc) Which specifies an entry to a piece of pre-animated state, the RootInstance that it's playing from, and whether it wants to restore state or not.
struct FPreAnimatedStateTraits
Base class for all pre-animated state traits.
struct FPreAnimatedStorageGroupHandle
struct FPreAnimatedStorageID
struct FPreAnimatedStorageIndex
struct FPreAnimatedTemplateCaptureSources
Structure responsible for tracking contributions to pre-eanimated state entries that originate from track templates (ie, from an IMovieSceneExecutionToken::Execute)
struct FPreAnimatedTrackerParams
struct FPreAnimatedTrackInstanceCaptureSources
Structure responsible for tracking contributions to pre-eanimated state entries that originate from specific track template inputs.
struct FPreAnimatedTrackInstanceInputCaptureSources
Structure responsible for tracking contributions to pre-eanimated state entries that originate from track templates (ie, from an IMovieSceneExecutionToken::Execute)
struct FPreAnimatedVectorMaterialParameterStorage
struct FPreAnimAttachment
struct FPropertyComponentArrayView
Type-erased view of an array of components.
struct FPropertyComponentView
Type-erased view of a component.
struct FPropertyCompositeDefinition
A generic definition of a composite channel that contributes to a property.
struct FPropertyDefinition
Structure defining a type of property that can be animated by sequencer.
struct FPropertyRecomposerImpl
struct FPropertyRecomposerPropertyInfo
class FPropertyRegistry
Central registry of all property types animatable by sequencer.
struct FPropertyStats
Stats pertaining to a given type of property including how many properties exist in the linker, and how many of those are partially animated.
struct FPropertyTrackEntityImportHelper
struct FPropertyTrackEntityImportHelperParamsImpl
struct FPropertyTrackWithOverridableChannelsEntityImportHelper
struct FQuaternionBlenderAccumulationBuffers
struct FQuatTransform
struct FReadAccess
struct FReadErased
struct FReadErasedOptional
struct FRelativeObjectBindingID
A binding ID whose target is resolved relative to the owner of this ID (either internal or external to that sequence through a parent or grandparent) Should be used for asignment to any serialized FMovieSceneObjectBindingID Represented by a local object binding ID and a parent index to which it is relative.
struct FRemoveMultipleMutation
struct FRemoveSingleMutation
struct FRestoreStateParams
Parameters that are passed to IMovieScenePreAnimatedToken::RestoreState and IMovieScenePreAnimatedGlobalToken::RestoreState.
struct FRootInstanceHandle
A handle to a root instance of a UMovieSceneSequence.
struct FScopedSignedObjectModifyDefer
struct FScopedSignedObjectModifySuppress
struct FScopedVolatilityManagerSuppression
Defines a scope during which a given sequence hierarchy will not be recompiled when changed even if it was set to volatile.
struct FSequenceDirectorPlaybackCapability
Playback capability for sequences that have a director blueprint.
struct FSequenceInstance
A sequence instance represents a specific instance of a currently playing sequence, either as a top-level sequence in an IMovieScenePlayer, or as a sub sequence.
struct FSequenceVisitParams
class FSequenceWeights
Container class for keeping track of externally created entities for providing dynamic sequence weights.
struct FSharedPlaybackState
A structure that stores playback state for an entire sequence hierarchy.
struct FSharedPlaybackStateCreateParams
Parameter structure for initializing a new shared playback state.
struct FSimpleBlenderEnumResultTraits
Custom blend result traits for enums:
struct FSkeletalAnimationSystemData
struct FSourceBoolChannel
The component data for evaluating a bool channel.
struct FSourceByteChannel
The component data for evaluating a byte channel.
struct FSourceDoubleChannel
The component data for evaluating a double channel.
struct FSourceFloatChannel
The component data for evaluating a float channel.
struct FSourceIntegerChannel
The component data for evaluating an integer channel.
struct FSourceObjectPathChannel
struct FSourceStringChannel
The component data for evaluating a string channel.
struct FSparseInterrogationChannelInfo
struct FStaticBindingOverrides
A re-usable implementation of IStaticBindingOverridesPlaybackCapability.
struct FSubSequencePath
A path of unaccumulated sequence IDs ordered from child->parent->grandparent that is used to generate unique sequenceIDs for inner sequences Optimized for Remap rather than Push/Pop by keeping sequence IDs child-parent order (the order they are required for remapping)
struct FSubSequenceSpace
struct FSystemFilter
Utility class for filtering systems.
class FSystemInterrogator
struct FSystemSubsequentTasks
struct FSystemTaskPrerequisites
struct FTaskID
struct FTaskParams
struct FTypelessMutation
Specifies a mask of components to add and remove from an entity.
struct FValueDecompositionParams
struct FVectorPropertyMetaData
struct FViewportSettingsPlaybackCapability
Playback capability for controlling game and editor viewports.
struct FWeightedValue
Holds a weighted value.
struct FWriteAccess
struct FWriteErased
struct FWriteErasedOptional
struct IComplexComponentOps
Class that is instantiated to specify custom behavior for interacting with component data.
struct IComponentTypeHandler
Interface for defining new registered component types within an FEntityManager.
struct ICustomPropertyRegistration
struct IDeferredSignedObjectChangeHandler
Application-wide utility interface that allows for deferral of UMovieSceneSignedObject::MarkAsChanged calls.
struct IDeferredSignedObjectFlushSignal
struct IEntityBuilder
struct IEntityGroupingHandler
Base class for grouping handlers, used by the grouping system (see below).
class IEntitySystemScheduler
struct IEventContextsPlaybackCapability
Playback capability for controlling how events are triggered.
class IFolderEventHandler
struct IInitialValueProcessor
Interface required for initializing initial values on entities.
struct IInterrogationExtension
struct ILegacyPlayerProviderPlaybackCapability
struct IMovieSceneConditionalEntityMutation
struct IMovieSceneEntityMutation
struct IMovieScenePerEntityMutation
struct IMutualComponentInitializer
struct IObjectBindingNotifyPlaybackCapability
Playback capability for being notified of object bindings changing.
struct IPlaybackCapability
Interface for playback capabilities that want to be notified of various operations.
struct IPreAnimatedCaptureSource
struct IPreAnimatedObjectEntityStorage
struct IPreAnimatedObjectPropertyStorage
struct IPreAnimatedStateGroupManager
Interface required for any logical grouping of pre-animated state.
struct IPreAnimatedStateTokenStorage
struct IPreAnimatedStorage
struct IPropertyComponentHandler
Interface for a property type handler that is able to interact with properties in sequencer.
struct IPropertyValueStorage
Base interface for all initial value storage types.
struct IRetimingInterface
class ISectionEventHandler
class ISequenceDataEventHandler
struct ISequenceUpdater
Interface for an object that will update a sequence based on the current context.
struct ISequenceVisitor
class ISignedObjectEventHandler
struct IStaticBindingOverridesPlaybackCapability
Playback capability for storing static object binding overrides.
struct ITaskContext
struct TAdd
Implemtntation of a typed add payload.
struct TAddBoundMaterialMutationImpl
struct TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >
struct TAddConditional
Implemtntation of a conditional typed add payload.
struct TAnonTaskWrapper
struct TApplyMaterialSwitchers
struct TAutoRegisterPreAnimatedStorageID
struct TChildEntityInitializer
struct TComponentLock
Typed write-lock for component data.
struct TComponentLock< FReadErased >
struct TComponentLock< FReadErasedOptional >
struct TComponentLock< FWriteErased >
struct TComponentLock< FWriteErasedOptional >
struct TComponentLock< TRead< T > >
struct TComponentLock< TReadOptional< T > >
struct TComponentLock< TWrite< T > >
struct TComponentLock< TWriteOptional< T > >
struct TComponentLockMixin
struct TComponentLockMixin< FScopedHeaderReadLock >
struct TComponentLockMixin< FScopedHeaderWriteLock >
struct TComponentPtr
Facade for any component data type.
struct TComponentTypeID
struct TCompositePropertyDefinitionBuilder
struct TCompositePropertyTypeID
struct TConditionalDuplicateChildEntityInitializer
struct TCustomPropertyAccessor
Complete information required for applying a custom getter/setter to an object.
struct TCustomPropertyAccessorFunctionsImpl
Structure that defines 2 static function pointers that are to be used for retrieving and applying properties of a given type.
struct TCustomPropertyAccessorFunctionsImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... > >
struct TCustomPropertyRegistration
Generally static collection of accessors for a given type of property.
struct TDataEventContainer
struct TDefaultEntityTaskTraits
Default traits specialized for each user TaskImplInstance.
struct TDirectPropertyTraits
Property accessor traits that talk directly to the reflected UObject property type.
struct TDuplicateChildEntityInitializer
struct TDynamicSparseBitSet
NOTE: This class is currently considered internal only, and should only be used by engine code.
struct TDynamicSparseBitSetBucketStorage
struct TDynamicSparseBitSetBucketStorage< T, 0 >
struct TEntityAllocationTask
struct TEntityAllocationTaskBase
struct TEntityBuilder
TEntityBuilder is a utility class that can be used to marshal type-safe component data into entites, either on construction or mutation of an existing entity.
struct TEntityBuilderImpl
struct TEntityBuilderImpl< TIntegerSequence< int > >
struct TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >
struct TEntityGroupingHandler
struct TEntityGroupingHandlerBase
struct TEntityGroupingHandlerImpl
Strongly-typed grouping handler class, which knows about the exact components to look for, and how to use them to group entities.
struct TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >
struct TEntityPtr
Variadic template representing a single entity with a range of entities with the same a set of typed components.
struct TEntityPtr< T >
struct TEntityRange
Variadic template representing a contiguous range of entities with a specific set of components.
struct TEntityRangeImpl
struct TEntityRangeImpl< TIntegerSequence< int, Indices... >, T... >
Implementation template for a range of entities.
struct TEntitySystemLinkerExtensionID
Typed extension identifier for a UMovieSceneEntitySystemLinker.
struct TEntityTask
struct TEntityTaskBase
struct TEntityTaskCaller
struct TEntityTaskCaller< NumComponents, false >
struct TEntityTaskCaller< NumComponents, true >
struct TEntityTaskCaller_AutoExpansion
struct TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >
struct TEntityTaskComponents
Defines the accessors for each desired component of an entity task.
struct TEntityTaskComponentsImpl
struct TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >
struct TEntityTaskTraits
Optionally specialized traits for user TaskImplInstances.
struct TFilteredEntityTask
struct TFixedSparseBitSet
NOTE: This class is currently considered internal only, and should only be used by engine code.
struct TFixedSparseBitSetBucketStorage
struct TGarbageTraitsImpl
struct TGarbageTraitsImpl< TIntegerSequence< int, Indices... >, T... >
struct TGetPropertyValues
struct TGetPropertyValuesImpl
struct TGetPropertyValuesImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... > >
struct THasAddReferencedObjectForComponent
class TimeHelpers
struct TIndirectPropertyTraits
Property accessor traits that talk directly to the reflected UObject property type.
struct TInitializeBoundMaterials
struct TInitialValueProcessor
struct TInitialValueProcessorImpl
struct TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >
class TIntrusiveEventHandler
struct TMaskedBlendable
Working data type used to blend multi-channel values.
struct TMemberFunctionTaskWrapper
class TMovieSceneMaterialSystem
struct TMultiChannelValue
Generic value type that supports a specific number of channels, optionally masked out.
struct TMultiComponentData
struct TNamedChannelOverrideProviderTraits
struct TNonIntrusiveEventHandler
struct TOptionalReadAccess
struct TOptionalWriteAccess
struct TOverlappingEntityInput
struct TOverlappingEntityTracker_NoGarbage
struct TOverlappingEntityTracker_WithGarbage
struct TOverlappingEntityTrackerImpl
Templated utility class that assists in tracking the state of many -> one data relationships in an FEntityManager.
struct TPlaybackCapabilityDestructor
struct TPlaybackCapabilityHelpers
struct TPlaybackCapabilityID
A strongly-typed identifier for a specific playback capability class.
struct TPlaybackCapabilityInterfaceCast
struct TPlaybackCapabilityInterfaceCast< PointedType * >
struct TPlaybackCapabilityInterfaceCast< TSharedPtr< PointedType > >
struct TPlaybackCapabilityStorageTraits
struct TPlaybackCapabilityStorageTraits< CapabilityType *, CapabilityType, void >
struct TPlaybackCapabilityStorageTraits< StorageType, CapabilityType, typename TEnableIf< TPointerIsConvertibleFromTo< StorageType, CapabilityType >::Value >::Type >
struct TPlaybackCapabilityStorageTraits< TSharedPtr< CapabilityType >, CapabilityType, void >
struct TPreAnimatedCaptureSources
Structure responsible for tracking contributions to pre-animated state entries that originate from track templates (ie, from an IMovieSceneExecutionToken::Execute)
struct TPreAnimatedMaterialTraits
struct TPreAnimatedPropertyStorageImpl
struct TPreAnimatedPropertyStorageImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >
struct TPreAnimatedPropertyTraits
Pre-Animated traits class that wraps a user-provided property trait that defines property accessors.
struct TPreAnimatedPropertyTraits< PropertyTraits, TIntegerSequence< int, MetaDataIndices... >, MetaDataTypes... >
struct TPreAnimatedPropertyTraits< PropertyTraits, TPropertyMetaData<>, TIntegerSequence< int > >
Pre-Animated traits class that wraps a user-provided property trait that defines property accessors with no meta-data.
struct TPreAnimatedPropertyValue
Pre-animated property value, including cached meta-data.
struct TPreAnimatedPropertyValue< StorageType >
Pre-animated property value, specialized for no meta-data.
struct TPreAnimatedStateGroupManager
struct TPreAnimatedStateStorage
Storage container for a specific type of pre-animated state as defined by the specified traits.
struct TPreAnimatedStateStorage_ObjectTraits
struct TPreAnimatedStateTaskParams
Default task that is provided to BeginTrackingEntitiesTask or CachePreAnimatedValuesTask to constrain the task using an additional filter, or to provide custom short-circuit behavior that allows the client to skip saving pre-animated state for some entities.
struct TPreAnimatedStorageID
struct TPrelockedDataOffsets
struct TPropertyComponentHandler
struct TPropertyComponentHandlerImpl
struct TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >
struct TPropertyComponents
User-defined property type that is represented as an UE::MovieScene::FPropertyDefinition within UE::MovieScene::FPropertyRegistry.
struct TPropertyDefinitionBuilder
struct TPropertyMetaData
Property accessor traits that talk directly to the reflected UObject property type.
struct TPropertyMetaDataComponents
struct TPropertyMetaDataComponents< TPropertyMetaData< MetaDataTypes... > >
struct TPropertyMetaDataComponents< TPropertyMetaData<> >
struct TPropertyMetaDataComponentsImpl
struct TPropertyMetaDataComponentsImpl< TIntegerSequence< int, Indices... >, TPropertyMetaData< MetaDataTypes... > >
struct TPropertyTrackEntityImportHelperImpl
Utility class for importing a customizable property track entity in a way that automatically supports being inside a bound property track or not, and being hooked up to a property with an edit condition or not.
struct TPropertyTrackEntityImportHelperImpl<>
The starting point for TPropertyTrackEntityImportHelperImpl<...T>
struct TPropertyTrackWithOverridableChannelsEntityImportHelperImpl
Same as TPropertyTrackEntityImportHelperImpl but with support for overridable channels.
struct TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<>
The starting point for TPropertyTrackWithOverridableChannelsEntityImportHelperImpl<...T>
struct TPropertyValueStorage
Templated storage for any initial value type, templated on the same parameter as TPropertyComponents for correct retrieval of resolved properties Initial values are stored as a sparse array, with stable indices that uniquely identify the value.
struct TRead
struct TReadAccess
struct TReadOneOfAccessor
struct TReadOneOrMoreOfAccessor
struct TReadOptional
struct TRecompositionResult
struct TReinitializeBoundMaterials
struct TRuntimePropertyTraits
Property accessor traits that do not know the underlying UObjectPropertyType until runtime.
struct TScheduledEntityTask
struct TSetCompositePropertyValuesImpl
Task implementation that combines a specific set of input components (templated as CompositeTypes) through a projection, and applies the result to an object property Three types of property are supported: Custom native accessor functions, fast pointer offset, or FTrackInstancePropertyBindings.
struct TSetCompositePropertyValuesImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, CompositeTypes... >
struct TSetPartialPropertyValuesImpl
struct TSetPartialPropertyValuesImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >
struct TSetPropertyValues
Stateless entity task that will apply values to properties.
struct TSetPropertyValuesImpl
struct TSetPropertyValuesImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... > >
struct TSharedEntitySystemLinkerExtension
struct TSimpleBlenderCombineResults
struct TSimpleBlenderGatherResults
class TSimpleBlenderSystemImpl
A helper class for simple blender systems.
struct TSimpleBlendResult
Simple blended result where a value has been accumulated by a number of contributors.
struct TSimpleBlendResultTraits
Traits class for knowing how to deal with a simply blended property type.
struct TSimplePreAnimatedStateStorage
Simple pre-animated state storage that doesn't support any grouping, and lets people simply implement a void RestoreState(KeyType, Params) method on their state class.
struct TSimplePreAnimatedStateTraits
Simple traits class that works with the simple storage below.
struct TSingleChannelOverrideProviderTraits
struct TStaticChildEntityInitializer
struct TTupleGroupingPolicy
A simple grouping policy that uses a tuple of component values as the group key.
struct TUnpackMultiComponentData
struct TUnpackMultiComponentData< TIntegerSequence< int, Indices... >, T... >
struct TUnstructuredTask
struct TWrite
struct TWriteAccess
struct TWriteOptional
Typedefs
using AllocationFunctionPtr = void (*)(const FEntityAllocation* Allocation, const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
using AllocationItemFunctionPtr = void (*)(FEntityAllocationIteratorItem Item, const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
using FBoolParameterTraits = TDirectPropertyTraits<bool, false>
using FBoundObjectResolver = UObject* (*)(UObject*)
using FByteParameterTraits = TDirectPropertyTraits<uint8, false>
using FBytePropertyTraits = TDirectPropertyTraits<uint8, false>
using FChannelOverrideProviderTraitsHandle = TInlineValue<FChannelOverrideProviderTraits, 64>
using FColorParameterTraits = TIndirectPropertyTraits<FLinearColor, FIntermediateColor>
using FComponentMaskAllocator = TFixedAllocator<ComponentMaskDWORDSize>
using FComponentMaskIterator = TConstSetBitIterator<FComponentMaskAllocator>
using FComponentReader = TComponentLock<FReadErased>
using FComponentReferenceCollectionPtr = void (*)(FReferenceCollector&, void*, int32)
using FComponentTransformPropertyTraits = TDirectPropertyTraits<FIntermediate3DTransform>
using FComponentWriter = TComponentLock<FWriteErased>
using FDoublePropertyTraits = TDirectPropertyTraits<double, false>
using FEntityAllocationIteratorItem = FEntityAllocationProxy
using FEntityBuilder = TEntityBuilder<>
using FEnumPropertyTraits = TDirectPropertyTraits<uint8, false>
using FEulerTransformPropertyTraits = TIndirectPropertyTraits<FEulerTransform, FIntermediate3DTransform>
using FFloatParameterTraits = TIndirectPropertyTraits<float, double, false>
using FIntegerParameterTraits = TDirectPropertyTraits<int32, false>
using FIntPropertyTraits = TDirectPropertyTraits<int32, false>
using FOptionalComponentReader = TComponentLock<FReadErasedOptional>
using FOptionalComponentWriter = TComponentLock<FWriteErasedOptional>
using FPlaybackCapabilityDestructionHelper = void(*)(void* Ptr)
using FPlaybackCapabilityInterfaceCastHelper = IPlaybackCapability*(*)(void* Ptr)
using FPreAnimatedComponentMaterialParameterTraits = TPreAnimatedMaterialParameterTraits<FComponentMaterialAccessor, UObject*, FComponentMaterialInfo>
using FPreAnimatedComponentMaterialTraits = TPreAnimatedMaterialTraits<FComponentMaterialAccessor, UObject*, FComponentMaterialInfo>
using FPreAnimatedStateMetaDataArray = TArray<FPreAnimatedStateMetaData, TInlineAllocator<1>>
using FPreLockedDataPtr = TRelativePtr<void, uint32>
Typedef for a pointer that is relative to another.
using FReadEntityIDs = TRead<FMovieSceneEntityID>
using FResolvedFastProperty = TVariant<uint16, UE::MovieScene::FCustomPropertyIndex>
Type aliases for a property that resolved to either a fast pointer offset (type index 0), or a custom property index (specific to the path of the property - type index 1)
using FResolvedProperty = TVariant<uint16, UE::MovieScene::FCustomPropertyIndex, TSharedPtr<FTrackInstancePropertyBindings>>
Type aliases for a property that resolved to either a fast pointer offset (type index 0), or a custom property index (specific to the path of the property - type index 1) with a fallback to a slow property binding (type index 2)
using FRotatorPropertyTraits = TDirectPropertyTraits<FRotator>
using FStringPropertyTraits = TDirectPropertyTraits<FString>
using FTransformParameterTraits = TIndirectPropertyTraits<FEulerTransform, FIntermediate3DTransform>
using FTransformPropertyTraits = TIndirectPropertyTraits<FTransform, FIntermediate3DTransform>
using FVector2ParameterTraits = TIndirectPropertyTraits<FVector2f, FFloatIntermediateVector>
using FVector3ParameterTraits = TIndirectPropertyTraits<FVector3f, FFloatIntermediateVector>
using PreLockedAllocationItemFunctionPtr = void (*)(FEntityAllocationIteratorItem Item, TArrayView<const FPreLockedDataPtr> PreLockedData, const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
using TaskFunctionPtr = TVariant<UnboundTaskFunctionPtr, AllocationFunctionPtr, AllocationItemFunctionPtr, PreLockedAllocationItemFunctionPtr>
template<typename T>
using TComponentReader = TComponentLock<TRead<T>>
template<typename T>
using TComponentWriter = TComponentLock<TWrite<T>>
template<typename PropertyTraits>
using TCustomPropertyAccessorFunctions = TCustomPropertyAccessorFunctionsImpl<PropertyTraits, typename PropertyTraits::MetaDataType>
template<typename... T>
using TMultiComponentLock = TTuple<TComponentLock<T>...>
template<typename... T>
using TMultiReadOptional = TMultiComponentData<TReadOptional<T>...>
template<typename T>
using TOptionalComponentReader = TComponentLock<TReadOptional<T>>
template<typename T>
using TOptionalComponentWriter = TComponentLock<TWriteOptional<T>>
template<typename OutputType, typename... KeyType>
using TOverlappingEntityTracker
template<typename AccessorType, typename... RequiredComponents>
using TPreAnimatedMaterialParameterTraits = TPreAnimatedMaterialTraits<AccessorType, RequiredComponents...>
template<typename PropertyTraits>
using TPreAnimatedPropertyStorage = TPreAnimatedPropertyStorageImpl<PropertyTraits, typename PropertyTraits::MetaDataType, TMakeIntegerSequence<int, PropertyTraits::MetaDataType::Num>>
template<typename... T>
using TReadOneOf = TMultiComponentData<TReadOptional<T>...>
template<typename... T>
using TReadOneOrMoreOf = TMultiComponentData<TReadOptional<T>...>
template<typename PropertyTraits, typename ... CompositeTypes>
using TSetCompositePropertyValues = TSetCompositePropertyValuesImpl<PropertyTraits, typename PropertyTraits::MetaDataType, CompositeTypes...>
template<typename PropertyTraits, typename ... CompositeTypes>
using TSetPartialPropertyValues = TSetPartialPropertyValuesImpl<PropertyTraits, typename PropertyTraits::MetaDataType, TMakeIntegerSequence<int, sizeof...(CompositeTypes)>, CompositeTypes...>
using UnboundTaskFunctionPtr = void (*)(const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
Enumerations
enum class EAutoLinkRelevantSystems : uint8 { Enabled , Disable }
enum class ECachedEntityManagerState { UpToDate , Stale }
Signifies whether any caches held for the current cached result are still up to date, or whether they should be updated.
enum class EColorPropertyType : uint8 { Undefined , Slate , Linear , Color }
Color type for the color property system.
enum class EComplexInclusivityFilterMode { AllOf , AnyOf }
Enumeration specifying how to apply a complex filter for mutual inclusion.
enum class EEntityGroupFlags : uint8 { None = 0 , RemovedFromGroup = 1 << 0 }
Flags for FEntityGroupID.
enum class EEntityRecursion : uint8 { This = 1 << 0 , Children = 1 << 1 , Full = This | Children }
enum class EEntitySystemCategory : uint32 {
None = 0 , Unspecified = 1u << 0 , Core = 1u << 1 , ChannelEvaluators = 1u << 2 ,
BlenderSystems = 1u << 3 , PropertySystems = 1u << 4 , Custom = 1u << 5 , Last = 1u << 31 ,
All = ~0u
}
enum class EEntitySystemLinkerRole : uint32 {
Unknown = 0 , LevelSequences = 1 , CameraAnimations , UMG ,
Standalone , Interrogation , Custom
}
Enum that describes what a sequencer ECS linker is meant for (only used for debugging reasons)
enum class EEntityThreadingModel : uint8 { NoThreading , TaskGraph }
Enumeration that defines a threading model for this entity manager.
enum class EEvaluationHookEvent { Begin , Update , End , Trigger }
enum class EHierarchicalBlendMode : uint8 { AccumulateParentToChild , ChildFirstBlendTarget }
enum class EInverseEvaluateFlags : uint8 {
Forwards = 1 << 0 , Backwards = 1 << 1 , Equal = 1 << 2 , Cycle = 1 << 3 ,
IgnoreClamps = 1 << 4 , AnyDirection = Forwards | Equal | Backwards
}
Flags for controlling inverse evaluation.
enum class EMovieSceneBindingLifetimeState : uint8 { Active , Inactive }
enum class EPlaybackCapabilityStorageMode : uint8 { Inline = 0 , RawPointer , SharedPointer }
enum class EPreAnimatedCaptureSourceState { New , Updated , UpToDate }
enum class EPreAnimatedCaptureSourceTracking { CacheIfTracked , AlwaysCache }
Enum that defines how to cache pre-animated values based on their capture source.
enum class EPreAnimatedStorageRequirement : uint8 { None , Persistent , Transient , NoChange }
enum class ERunnerFlushState {
None = 0 , Start = 1 << 0 , ConditionalRecompile = 1 << 1 , Import = 1 << 2 ,
ReimportAfterCompile = 1 << 3 , Spawn = 1 << 4 , Instantiation = 1 << 5 , Evaluation = 1 << 6 ,
Finalization = 1 << 7 , EventTriggers = 1 << 8 , PostEvaluation = 1 << 9 , End = 1 << 10
}
Bit-mask enumeration that defines tasks that need running.
enum class ESequenceInstanceInvalidationType : uint8 { DataChanged , All }
Specifies what cached data should be invalidated in a sequence instance.
enum class ESequenceInstanceUpdateFlags : uint8 {
None = 0 , NeedsDissection = 1u << 0 , NeedsPreEvaluation = 1u << 1 , NeedsPostEvaluation = 1u << 2 ,
HasLegacyTemplates = 1u << 3
}
enum class ESparseBitSetBitResult { NewlySet , AlreadySet }
enum class ETimeWarpChannelDomain : uint8 { Time , PlayRate }
enum class EUnlinkEverythingMode { Normal , CleanGarbage }
Functions
void AddAccessorToFilter (const FComponentAccess *In, FEntityComponentFilter *OutFilter)
void AddAccessorToFilter (const FEntityIDAccess *, FEntityComponentFilter *OutFilter)
void AddAccessorToFilter (const FFilterMatchPassthrough *, FEntityComponentFilter *OutFilter)
void AddAccessorToFilter (const FOptionalComponentAccess *In, FEntityComponentFilter *OutFilter)
template<typename... T>
void AddAccessorToFilter (const TReadOneOfAccessor< T... > *In, FEntityComponentFilter *OutFilter)
template<typename... T>
void AddAccessorToFilter (const TReadOneOrMoreOfAccessor< T... > *In, FEntityComponentFilter *OutFilter)
template<typename ChannelType, typename ExtendedEditorDataType>
void AddChannelProxy (FMovieSceneChannelProxyData &ProxyData, const UMovieSceneSectionChannelOverrideRegistry *OverrideRegistry, FName ChannelName, ChannelType &DefaultChannel, const FMovieSceneChannelMetaData &InMetaData, ExtendedEditorDataType &&InExtendedEditorData)
Utility function for adding a possibly-overriden channel into a channel proxy, with some specific extended editor data.
MOVIESCENE_API void AddGlobalCustomAccessor (const UClass *ClassType, FName PropertyPath)
template<typename ChannelType, typename ValueType>
FKeyHandle AddKeyToChannel (ChannelType *InChannel, FFrameNumber InTime, ValueType &&Value, EMovieSceneKeyInterpolation Interpolation)
Add a key to a channel, or update an existing key if one already exists at this time.
FNotImplemented * AddReferencedObjectForComponent (...)
Stub for components that do not need reference collection.
void AddReferencedObjectForComponent (FReferenceCollector *ReferenceCollector, FObjectKey *Component)
template<typename T>
TEnableIf< TPointerIsConvertibleFromTo< T, UObject >::Value >::Type AddReferencedObjectForComponent (FReferenceCollector *ReferenceCollector, T **Component)
Instantiation for raw pointers.
template<typename T, typename U = decltype(T::StaticStruct())>
void AddReferencedObjectForComponent (FReferenceCollector *ReferenceCollector, T *Component)
template<typename T>
void AddReferencedObjectForComponent (FReferenceCollector *ReferenceCollector, TObjectKey< T > *Component)
template<typename T>
void AddReferencedObjectForComponent (FReferenceCollector *ReferenceCollector, TObjectPtr< T > *Component)
template<typename ChannelType, typename ValueType>
bool AssignValue (ChannelType *InChannel, FKeyHandle InKeyHandle, ValueType &&InValue)
Called to assign a specific value in a channel.
template<typename OutputType, typename InputType, typename ActualValueType>
void BlendValue (TMaskedBlendable< OutputType, 1 > &OutBlend, InputType InValue, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< ActualValueType > &InitialValueStore)
template<typename OutputType, typename ActualValueType, uint8 ChannelSize>
void BlendValue (TMaskedBlendable< OutputType, ChannelSize > &OutBlend, const TMultiChannelValue< OutputType, ChannelSize > &InValue, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< ActualValueType > &InitialValueStore)
template<typename OutputType, typename InputType, typename ActualValueType, uint8 ChannelSize>
void BlendValue (TMaskedBlendable< OutputType, ChannelSize > &OutBlend, InputType InValue, int32 ChannelIndex, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< ActualValueType > &InitialValueStore)
template<typename InType, typename WorkingDataType, typename SourceDataType>
void BlendValue (WorkingDataType &OutBlend, InType InValue, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< SourceDataType > &InitialValueStore)
template<typename InType, typename WorkingDataType, typename SourceDataType>
void BlendValue (WorkingDataType &OutBlend, InType InValue, float Weight, EMovieSceneBlendType BlendType, TMovieSceneInitialValueStore< SourceDataType > &InitialValueStore)
FFrameTime ClampToDiscreteRange (FFrameTime InTime, const TRange< FFrameNumber > &InRange)
Clamp the specified time to a range.
MOVIESCENETRACKS_API void CollectGarbageForOutput (FAnimatedCustomPrimitiveDataInfo *Output)
MOVIESCENETRACKS_API void CollectGarbageForOutput (FAnimatedMaterialParameterInfo *Output)
void CollectGarbageForOutput (void *)
Override for OutputType* in order to provide custom garbage collection logic.
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FColor &InColor, FIntermediateColor &OutIntermediate)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FDoubleIntermediateVector &InVector, FVector2d &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FDoubleIntermediateVector &InVector, FVector3d &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FDoubleIntermediateVector &InVector, FVector4d &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FEulerTransform &In, FIntermediate3DTransform &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FFloatIntermediateVector &InVector, FVector2f &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FFloatIntermediateVector &InVector, FVector3f &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FFloatIntermediateVector &InVector, FVector4f &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FIntermediate3DTransform &In, FEulerTransform &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FIntermediate3DTransform &In, FTransform &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FIntermediateColor &InColor, FColor &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FIntermediateColor &InColor, FLinearColor &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FIntermediateColor &InColor, FSlateColor &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FLinearColor &InColor, FIntermediateColor &OutIntermediate)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FObjectComponent &In, UObject *&Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FSlateColor &InColor, FIntermediateColor &OutIntermediate)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FTransform &In, FIntermediate3DTransform &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FVector2d &In, FDoubleIntermediateVector &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FVector2f &In, FFloatIntermediateVector &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FVector3d &In, FDoubleIntermediateVector &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FVector3f &In, FFloatIntermediateVector &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FVector4d &In, FDoubleIntermediateVector &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (const FVector4f &In, FFloatIntermediateVector &Out)
template<typename InType, typename OutType>
void ConvertOperationalProperty (const InType &In, OutType &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (double In, float &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (float In, double &Out)
MOVIESCENETRACKS_API void ConvertOperationalProperty (UObject *In, FObjectComponent &Out)
template<>
TRange< FFrameNumber > ConvertRange (const TRange< FFrameTime > &Range)
template<typename InBoundType, typename OutBoundType>
TRange< OutBoundType > ConvertRange (const TRange< InBoundType > &Range)
Converts a range from one type of bounds to another.
TRange< FFrameNumber > ConvertToDiscreteRange (const TRange< FFrameTime > &InRange)
TRange< FFrameTime > ConvertToFrameTimeRange (const TRange< FFrameNumber > &InRange)
Convert a frame number range into a frame time range.
TRange< FFrameTime > ConvertToFrameTimeRange (const TRange< float > &InRange)
MOVIESCENE_API FCycleParams CycleTime (FFrameNumber MinFrame, FFrameNumber MaxFrame, FFrameTime InTime)
DECLARE_CYCLE_STAT (TEXT("Apply properties"), MovieSceneEval_ApplyProperties, STATGROUP_MovieSceneECS)
DECLARE_CYCLE_STAT (TEXT("Aquire Component Access Locks"), MovieSceneEval_AquireComponentAccessLocks, STATGROUP_MovieSceneECS)
DECLARE_CYCLE_STAT (TEXT("Release Component Access Locks"), MovieSceneEval_ReleaseComponentAccessLocks, STATGROUP_MovieSceneECS)
DECLARE_DELEGATE_RetVal_TwoParams (FPropertyRecomposerPropertyInfo, FOnGetPropertyRecomposerPropertyInfo, FMovieSceneEntityID, UObject *)
template<typename T>
TRange< T > DilateRange (const TRange< T > &InRange, T LowerAmount, T UpperAmount)
Dilate the specified range by adding a specific size to the lower and upper bounds (if closed)
FFrameNumber DiscreteExclusiveUpper (const TRange< FFrameNumber > &InRange)
Return the first frame number not contained by the specified range.
FFrameNumber DiscreteExclusiveUpper (const TRangeBound< FFrameNumber > &InUpperBound)
Return the first frame number that is not contained by the specified closed upper bound.
FFrameNumber DiscreteInclusiveLower (const TRange< FFrameNumber > &InRange)
Return the first frame number included by the specified range.
FFrameNumber DiscreteInclusiveLower (const TRangeBound< FFrameNumber > &InLowerBound)
Return the first frame number included by the specified closed lower bound.
bool DiscreteRangeIsEmpty (const TRange< FFrameNumber > &InRange)
Check whether the specified range contains any integer frame numbers or not.
int32 DiscreteSize (const TRange< FFrameNumber > &InRange)
Calculate the size of a discrete frame range, taking into account inclusive/exclusive boundaries.
ENUM_CLASS_FLAGS (EEntityGroupFlags)
ENUM_CLASS_FLAGS (EEntityRecursion)
ENUM_CLASS_FLAGS (EInverseEvaluateFlags) struct FTransformTimeParams
Parameter structure that controls time-transformation operations in MovieScene code.
ENUM_CLASS_FLAGS (ERunnerFlushState) enum class ERunnerUpdateFlags
Bit-field enumeration that defines flags for an asynchronous update request.
ENUM_CLASS_FLAGS (ERunnerUpdateFlags) enum class ERunnerFlushResult
Result from a runner flush state that indicates how to proceed.
ENUM_CLASS_FLAGS (ESequenceInstanceUpdateFlags)
template<typename ChannelType, typename ValueType>
bool EvaluateChannel (const ChannelType *InChannel, FFrameTime InTime, ValueType &OutValue)
Called to evaluate a channel.
template<typename ChannelType, typename ValueType>
bool EvaluateChannel (const UMovieSceneSection *InSection, const ChannelType *InChannel, FFrameTime InTime, ValueType &OutValue)
Called to evaluate a channel.
MOVIESCENE_API void EvaluateTime (TArrayView< const FFrameNumber > InTimes, FFrameTime InTime, int32 &OutIndex1, int32 &OutIndex2)
Evaluate the specified time array by finding the two indices that are adjacent to the supplied time.
MOVIESCENE_API void EvaluateTime (TArrayView< const FFrameNumber > InTimes, FFrameTime InTime, int32 &OutIndex1, int32 &OutIndex2, double &OutInterp)
Evaluate the specified time array by finding the two indices and an interpolation value that are adjacent to the supplied time.
template<typename T>
TRange< T > ExpandRange (const TRange< T > &InRange, T Amount)
Expand the specified range by subtracting the specified amount from the lower bound, and adding it to the upper bound.
MOVIESCENE_API void FindRange (TArrayView< const FFrameNumber > InTimes, FFrameNumber PredicateTime, FFrameNumber InTolerance, int32 MaxNum, int32 &OutMin, int32 &OutMax)
Find the range of times that fall around PredicateTime +/- InTolerance up to a maximum.
GCC_ALIGN (PLATFORM_CACHE_LINE_SIZE)
template<typename ChannelType, typename ValueType>
TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults, bool >::Type GetChannelDefault (ChannelType *Channel, ValueType &OutDefaultValue)
Gets the default value for the channel if set.
template<typename ChannelType, typename ValueType>
TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults, bool >::Type GetChannelDefault (ChannelType *Channel, ValueType &OutDefaultValue)
UMovieSceneChannelOverrideContainer * GetChannelOverride (const UMovieSceneSectionChannelOverrideRegistry *OverrideRegistry, FName ChannelName)
Utility function to return a channel override.
bool GetComponentAtIndex (const bool *BoolPassthrough, int32 Index)
template<typename T>
auto GetComponentAtIndex (T *InAccessor, int32 Index) -> decltype(DeclVal< T >().ComponentAtIndex(0))
MOVIESCENETRACKS_API FIntermediate3DTransform GetComponentTransform (const UObject *Object)
template<typename ChannelType>
EMovieSceneKeyInterpolation GetInterpolationMode (ChannelType *InChannel, const FFrameNumber &InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
template<typename ChannelType, typename ValueType>
bool GetKeyValue (ChannelType *InChannel, FKeyHandle InKeyHandle, ValueType &OutValue)
FFrameTime GetSimulatedMotionVectorTime (const FMovieSceneContext &Context)
MOVIESCENE_API bool GlobalCustomAccessorExists (const UClass *ClassType, TStringView< ANSICHAR > PropertyPath)
MOVIESCENE_API bool GlobalCustomAccessorExists (const UClass *ClassType, TStringView< WIDECHAR > PropertyPath)
bool HasAccessorWork (const FEntityManager *, const FEntityIDAccess *)
bool HasAccessorWork (const FEntityManager *EntityManager, const FComponentAccess *In)
bool HasAccessorWork (const FEntityManager *EntityManager, const FOptionalComponentAccess *In)
template<typename... T>
bool HasAccessorWork (const FEntityManager *EntityManager, const TReadOneOfAccessor< T... > *In)
template<typename... T>
bool HasAccessorWork (const FEntityManager *EntityManager, const TReadOneOrMoreOfAccessor< T... > *In)
bool HasBeenWrittenToSince (const FComponentAccess *In, FEntityAllocation *Allocation, uint64 InSystemSerial)
bool HasBeenWrittenToSince (const FEntityIDAccess *In, FEntityAllocation *Allocation, uint64 InSystemSerial)
bool HasBeenWrittenToSince (const FOptionalComponentAccess *In, FEntityAllocation *Allocation, uint64 InSystemSerial)
template<typename... T>
bool HasBeenWrittenToSince (const TReadOneOfAccessor< T... > *In, FEntityAllocation *Allocation, uint64 InSystemSerial)
template<typename... T>
bool HasBeenWrittenToSince (const TReadOneOrMoreOfAccessor< T... > *In, FEntityAllocation *Allocation, uint64 InSystemSerial)
template<typename ValueType>
void InvertValue (ValueType &InOutValue)
bool IsAccessorValid (const FComponentAccess *In)
bool IsAccessorValid (const FEntityIDAccess *)
bool IsAccessorValid (const FFilterMatchPassthrough *)
bool IsAccessorValid (const FOptionalComponentAccess *In)
template<typename... T>
bool IsAccessorValid (const TReadOneOfAccessor< T... > *In)
template<typename... T>
bool IsAccessorValid (const TReadOneOrMoreOfAccessor< T... > *In)
bool IsChannelOverriden (const UMovieSceneSectionChannelOverrideRegistry *OverrideRegistry, FName ChannelName)
Utility function to return whether a channel is overriden.
constexpr bool IsCompositePropertyTraits (...)
template<typename T, typename U = decltype(T::bIsComposite)>
constexpr bool IsCompositePropertyTraits (T *)
bool IsEmptyOrZeroSize (const TRange< FFrameNumber > &InRange)
Return whether the given range is empty or zero frames wide.
template<typename ChannelType, typename ExtendedEditorDataType>
TSharedPtr< FMovieSceneChannelProxy > MakeChannelProxy (const UMovieSceneSectionChannelOverrideRegistry *OverrideRegistry, ChannelType &DefaultChannel, const FMovieSceneChannelMetaData &InMetaData, ExtendedEditorDataType &&InExtendedEditorData)
Utility function for making a channel proxy with one channel that is maybe overriden by another channel.
TRange< FFrameNumber > MakeDiscreteRange (FFrameNumber MinInclusive, FFrameNumber MaxExclusive)
Make a new range that includes the given minimum and excludes the given maximum.
TRange< FFrameNumber > MakeDiscreteRangeFromLower (const TRangeBound< FFrameNumber > &InLowerBound, int32 DiscreteSize)
Make a new range using the specified lower bound, and a given size.
TRange< FFrameNumber > MakeDiscreteRangeFromUpper (const TRangeBound< FFrameNumber > &InUpperBound, int32 DiscreteSize)
Make a new range using the specified upper bound, and a given size.
TRange< FFrameNumber > MakeHullRange (const TRange< FFrameNumber > &InRange)
Make a new range that includes both the lower and upper bounds of the given range.
TRange< FFrameNumber > MakeHullRange (FFrameNumber MinInclusive, FFrameNumber MaxInclusive)
Make a new range that includes both the given minimum and maximum.
struct MS_ALIGN (PLATFORM_CACHE_LINE_SIZE) FAlignedDecomposedValue
void MultiChannelFromData (const FEulerTransform &In, TMultiChannelValue< float, 9 > &Out)
void MultiChannelFromData (const FLinearColor &In, TMultiChannelValue< float, 4 > &Out)
void MultiChannelFromData (const FTransform &In, TMultiChannelValue< float, 9 > &Out)
void MultiChannelFromData (const FVector4 &In, TMultiChannelValue< float, 4 > &Out)
void MultiChannelFromData (float In, TMultiChannelValue< float, 1 > &Out)
void MultiChannelFromData (FVector In, TMultiChannelValue< float, 3 > &Out)
void MultiChannelFromData (FVector2D In, TMultiChannelValue< float, 2 > &Out)
void MultiChannelFromData (int32 In, TMultiChannelValue< double, 1 > &Out)
template<typename T, typename SourceData, uint8 N>
void MultiChannelFromData (SourceData InSourceData, TMultiChannelValue< T, N > &OutChannelData)
Declaration of a function used to generate multi channel data from a source type.
MOVIESCENE_API void OnRemapChannelKeyTime (const FMovieSceneChannel *Channel, const IRetimingInterface &Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, FMovieSceneDoubleValue &InOutValue)
MOVIESCENE_API void OnRemapChannelKeyTime (const FMovieSceneChannel *Channel, const IRetimingInterface &Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, FMovieSceneFloatValue &InOutValue)
template<typename ValueType>
void OnRemapChannelKeyTime (const FMovieSceneChannel *Channel, const IRetimingInterface &Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, ValueType &InOutValue)
template<typename ChannelType>
void Optimize (ChannelType *InChannel, const FKeyDataOptimizationParams &Params)
Optimize the specified channel by removing any redundant keys.
template<typename CompositeType>
FORCEINLINE void PatchComposite (uint8 *OutValueBase, const CompositeType *Composite, uint16 PtrOffset)
template<typename... CompositeTypes>
void PatchCompositeValue (TArrayView< const FPropertyCompositeDefinition > CompositeDefinitions, void *OutValueAddress, const CompositeTypes *... Composites)
template<typename... CompositeTypes, int ... CompositeIndices>
FORCEINLINE void PatchCompositeValueImpl (const TIntegerSequence< int, CompositeIndices... > &, TArrayView< const FPropertyCompositeDefinition > CompositeDefinitions, uint8 *OutValueBase, const CompositeTypes *... Composites)
void PopulatePrerequisites (const FComponentAccess *In, const FSystemTaskPrerequisites &InPrerequisites, FGraphEventArray *OutGatheredPrereqs)
void PopulatePrerequisites (const FEntityIDAccess *, const FSystemTaskPrerequisites &InPrerequisites, FGraphEventArray *OutGatheredPrereqs)
void PopulatePrerequisites (const FOptionalComponentAccess *In, const FSystemTaskPrerequisites &InPrerequisites, FGraphEventArray *OutGatheredPrereqs)
template<typename... T>
void PopulatePrerequisites (const TReadOneOfAccessor< T... > *In, const FSystemTaskPrerequisites &InPrerequisites, FGraphEventArray *OutGatheredPrereqs)
template<typename... T>
void PopulatePrerequisites (const TReadOneOrMoreOfAccessor< T... > *In, const FSystemTaskPrerequisites &InPrerequisites, FGraphEventArray *OutGatheredPrereqs)
void PopulateReadWriteDependencies (const FEntityIDAccess *, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
void PopulateReadWriteDependencies (const FOptionalReadAccess *In, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
void PopulateReadWriteDependencies (const FOptionalWriteAccess *In, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
void PopulateReadWriteDependencies (const FReadAccess *In, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
void PopulateReadWriteDependencies (const FWriteAccess *In, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
template<typename... T>
void PopulateReadWriteDependencies (const TReadOneOfAccessor< T... > *In, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
template<typename... T>
void PopulateReadWriteDependencies (const TReadOneOrMoreOfAccessor< T... > *In, FComponentMask &OutReadDependencies, FComponentMask &OutWriteDependencies)
void PopulateSubsequents (const FOptionalWriteAccess *In, const FGraphEventRef &InEvent, FSystemSubsequentTasks &OutSubsequents)
void PopulateSubsequents (const FWriteAccess *In, const FGraphEventRef &InEvent, FSystemSubsequentTasks &OutSubsequents)
void PopulateSubsequents (const void *In, const FGraphEventRef &InEvent, FSystemSubsequentTasks &OutSubsequents)
MOVIESCENE_API EEntitySystemLinkerRole RegisterCustomEntitySystemLinkerRole ()
Register a new custom linker role.
template<typename ChannelType>
TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type RemoveChannelDefault (ChannelType *Channel)
Removes a channel's default value.
template<typename ChannelType>
TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type RemoveChannelDefault (ChannelType *Channel)
MOVIESCENE_API void RemoveGlobalCustomAccessor (const UClass *ClassType, FName PropertyPath)
void ResolveChannelsToData (const TMultiChannelValue< double, 1 > &In, int32 &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 1 > &In, float &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 2 > &In, FVector2D &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 3 > &In, FVector &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 4 > &In, FLinearColor &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 4 > &In, FVector4 &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 9 > &In, FEulerTransform &Out)
void ResolveChannelsToData (const TMultiChannelValue< float, 9 > &In, FTransform &Out)
template<typename T, typename SourceData, uint8 N>
void ResolveChannelsToData (const TMultiChannelValue< T, N > &OutChannelData, SourceData &OutData)
Declaration of a function used to popupate a specific type with generic channel data after blending has occurred.
template<typename TaskType>
static FTaskID SchedulePostTask (IEntitySystemScheduler *, const FTaskParams &, const TSharedPtr< TaskType > &, void *)
template<typename TaskType, typename TaskImplType>
static FTaskID SchedulePostTask (IEntitySystemScheduler *InScheduler, const FTaskParams &Params, const TSharedPtr< TaskType > &Context, TaskImplType *Unused, decltype(&TaskImplType::PostTask) *=0)
template<typename TaskType>
static FTaskID SchedulePreTask (IEntitySystemScheduler *, const FTaskParams &, const TSharedPtr< TaskType > &, void *)
template<typename TaskType, typename TaskImplType>
static FTaskID SchedulePreTask (IEntitySystemScheduler *InScheduler, const FTaskParams &Params, const TSharedPtr< TaskType > &Context, TaskImplType *Unused, decltype(&TaskImplType::PreTask) *=0)
template<typename ChannelType, typename ValueType>
TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type SetChannelDefault (ChannelType *Channel, ValueType &&DefaultValue)
Set a channel's default value.
template<typename ChannelType, typename ValueType>
TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type SetChannelDefault (ChannelType *Channel, ValueType &&DefaultValue)
MOVIESCENETRACKS_API void SetComponentTransform (USceneComponent *SceneComponent, const FIntermediate3DTransform &InTransform)
MOVIESCENETRACKS_API void SetComponentTransformAndVelocity (UObject *Object, const FIntermediate3DTransform &InTransform)
template<typename T>
TRange< T > TranslateRange (const TRange< T > &InRange, T Amount)
Translate the specified range by adding the specified amount to both bounds.
template<typename ChannelType, typename ValueType>
bool ValueExistsAtTime (const ChannelType *InChannel, FFrameNumber InTime, const ValueType &InValue)
Check whether the specified value already exists at the specified time.
MOVIESCENE_API void VisitSequence (UMovieSceneSequence *Sequence, const FSequenceVisitParams &InParams, ISequenceVisitor &Visitor)
Variables
static constexpr int32 ComponentMaskDWORDSize = (MaximumNumComponentsSupported + 31) / 32
Defines the number of DWORDs that we need to store for component masks.
MOVIESCENE_API FEntityManager * GEntityManagerForDebuggingVisualizers
MOVIESCENE_API FPlaybackCapabilityIDRegistry * GPlaybackCapabilityIDRegistryForDebuggingVisualizers
static constexpr int32 MaximumNumComponentsSupported = 384
Defines the absolute maximum number of component types that can exist at any one time in an FEntityManager In general component types should be kept to a minimum, but if large numbers of blocking sequences are required (which each require their own linker and instance tags), or large numbers of components are required for whatever reason, this limit can be increased.
Typedef Documentation
AllocationFunctionPtr
using UE::MovieScene::AllocationFunctionPtr = void (*)(const FEntityAllocation* Allocation, const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
Definition at line 155 of file IMovieSceneTaskScheduler.h.
AllocationItemFunctionPtr
using UE::MovieScene::AllocationItemFunctionPtr = void (*)(FEntityAllocationIteratorItem Item, const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
Definition at line 156 of file IMovieSceneTaskScheduler.h.
FBoolParameterTraits
using UE::MovieScene::FBoolParameterTraits = TDirectPropertyTraits<bool, false>
Definition at line 661 of file MovieSceneTracksComponentTypes.h.
FBoundObjectResolver
typedef UObject *(* UE::MovieScene::FBoundObjectResolver)(UObject *) = UObject* (*)(UObject*)
Definition at line 343 of file BuiltInComponentTypes.h.
FByteParameterTraits
using UE::MovieScene::FByteParameterTraits = TDirectPropertyTraits<uint8, false>
Definition at line 662 of file MovieSceneTracksComponentTypes.h.
FBytePropertyTraits
using UE::MovieScene::FBytePropertyTraits = TDirectPropertyTraits<uint8, false>
Definition at line 651 of file MovieSceneTracksComponentTypes.h.
FChannelOverrideProviderTraitsHandle
using UE::MovieScene::FChannelOverrideProviderTraitsHandle = TInlineValue<FChannelOverrideProviderTraits, 64>
Definition at line 73 of file IMovieSceneChannelOverrideProvider.h.
FColorParameterTraits
using UE::MovieScene::FColorParameterTraits = TIndirectPropertyTraits<FLinearColor, FIntermediateColor>
Definition at line 665 of file MovieSceneTracksComponentTypes.h.
FComponentMaskAllocator
using UE::MovieScene::FComponentMaskAllocator = TFixedAllocator<ComponentMaskDWORDSize>
Definition at line 35 of file MovieSceneEntityIDs.h.
FComponentMaskIterator
using UE::MovieScene::FComponentMaskIterator = TConstSetBitIterator<FComponentMaskAllocator>
Definition at line 36 of file MovieSceneEntityIDs.h.
FComponentReader
using UE::MovieScene::FComponentReader = TComponentLock<FReadErased>
Definition at line 422 of file MovieSceneComponentPtr.h.
FComponentReferenceCollectionPtr
using UE::MovieScene::FComponentReferenceCollectionPtr = void (*)(FReferenceCollector&, void*, int32)
Definition at line 25 of file MovieSceneComponentTypeInfo.h.
FComponentTransformPropertyTraits
using UE::MovieScene::FComponentTransformPropertyTraits = TDirectPropertyTraits<FIntermediate3DTransform>
Definition at line 657 of file MovieSceneTracksComponentTypes.h.
FComponentWriter
using UE::MovieScene::FComponentWriter = TComponentLock<FWriteErased>
Definition at line 424 of file MovieSceneComponentPtr.h.
FDoublePropertyTraits
using UE::MovieScene::FDoublePropertyTraits = TDirectPropertyTraits<double, false>
Definition at line 654 of file MovieSceneTracksComponentTypes.h.
FEntityAllocationIteratorItem
using UE::MovieScene::FEntityAllocationIteratorItem = FEntityAllocationProxy
Definition at line 17 of file EntityAllocationIterator.h.
FEntityBuilder
using UE::MovieScene::FEntityBuilder = TEntityBuilder<>
Definition at line 425 of file MovieSceneEntityBuilder.h.
FEnumPropertyTraits
using UE::MovieScene::FEnumPropertyTraits = TDirectPropertyTraits<uint8, false>
Definition at line 652 of file MovieSceneTracksComponentTypes.h.
FEulerTransformPropertyTraits
using UE::MovieScene::FEulerTransformPropertyTraits = TIndirectPropertyTraits<FEulerTransform, FIntermediate3DTransform>
Definition at line 656 of file MovieSceneTracksComponentTypes.h.
FFloatParameterTraits
using UE::MovieScene::FFloatParameterTraits = TIndirectPropertyTraits<float, double, false>
Definition at line 664 of file MovieSceneTracksComponentTypes.h.
FIntegerParameterTraits
using UE::MovieScene::FIntegerParameterTraits = TDirectPropertyTraits<int32, false>
Definition at line 663 of file MovieSceneTracksComponentTypes.h.
FIntPropertyTraits
using UE::MovieScene::FIntPropertyTraits = TDirectPropertyTraits<int32, false>
Definition at line 653 of file MovieSceneTracksComponentTypes.h.
FOptionalComponentReader
using UE::MovieScene::FOptionalComponentReader = TComponentLock<FReadErasedOptional>
Definition at line 423 of file MovieSceneComponentPtr.h.
FOptionalComponentWriter
using UE::MovieScene::FOptionalComponentWriter = TComponentLock<FWriteErasedOptional>
Definition at line 425 of file MovieSceneComponentPtr.h.
FPlaybackCapabilityDestructionHelper
using UE::MovieScene::FPlaybackCapabilityDestructionHelper = void(*)(void* Ptr)
Definition at line 77 of file MovieScenePlaybackCapabilities.h.
FPlaybackCapabilityInterfaceCastHelper
using UE::MovieScene::FPlaybackCapabilityInterfaceCastHelper = IPlaybackCapability*(*)(void* Ptr)
Definition at line 76 of file MovieScenePlaybackCapabilities.h.
FPreAnimatedComponentMaterialParameterTraits
using UE::MovieScene::FPreAnimatedComponentMaterialParameterTraits = TPreAnimatedMaterialParameterTraits<FComponentMaterialAccessor, UObject*, FComponentMaterialInfo>
Definition at line 53 of file MovieSceneComponentMaterialSystem.h.
FPreAnimatedComponentMaterialTraits
using UE::MovieScene::FPreAnimatedComponentMaterialTraits = TPreAnimatedMaterialTraits<FComponentMaterialAccessor, UObject*, FComponentMaterialInfo>
Definition at line 52 of file MovieSceneComponentMaterialSystem.h.
FPreAnimatedStateMetaDataArray
using UE::MovieScene::FPreAnimatedStateMetaDataArray = TArray<FPreAnimatedStateMetaData, TInlineAllocator<1>>
Definition at line 198 of file MovieScenePreAnimatedStateTypes.h.
FPreLockedDataPtr
typedef TRelativePtr< void, uint32 > UE::MovieScene::FPreLockedDataPtr = TRelativePtr<void, uint32>
Typedef for a pointer that is relative to another.
For most component data this is relative either to the FEntityAllocation itself, or FEntityAllocation::ComponentData Using a relative ptr for these allows us to store the same information with half of the memory (or 1/4 if we were able to use uint16 - I've used uint32 for safety here)
Definition at line 18 of file IMovieSceneTaskScheduler.h.
FReadEntityIDs
using UE::MovieScene::FReadEntityIDs = TRead<FMovieSceneEntityID>
Definition at line 201 of file MovieSceneComponentPtr.h.
FResolvedFastProperty
using UE::MovieScene::FResolvedFastProperty = TVariant<uint16, UE::MovieScene::FCustomPropertyIndex>
Type aliases for a property that resolved to either a fast pointer offset (type index 0), or a custom property index (specific to the path of the property - type index 1)
Definition at line 143 of file MovieScenePropertyRegistry.h.
FResolvedProperty
using UE::MovieScene::FResolvedProperty = TVariant<uint16, UE::MovieScene::FCustomPropertyIndex, TSharedPtr<FTrackInstancePropertyBindings>>
Type aliases for a property that resolved to either a fast pointer offset (type index 0), or a custom property index (specific to the path of the property - type index 1) with a fallback to a slow property binding (type index 2)
Definition at line 145 of file MovieScenePropertyRegistry.h.
FRotatorPropertyTraits
using UE::MovieScene::FRotatorPropertyTraits = TDirectPropertyTraits<FRotator>
Definition at line 658 of file MovieSceneTracksComponentTypes.h.
FStringPropertyTraits
using UE::MovieScene::FStringPropertyTraits = TDirectPropertyTraits<FString>
Definition at line 659 of file MovieSceneTracksComponentTypes.h.
FTransformParameterTraits
using UE::MovieScene::FTransformParameterTraits = TIndirectPropertyTraits<FEulerTransform, FIntermediate3DTransform>
Definition at line 668 of file MovieSceneTracksComponentTypes.h.
FTransformPropertyTraits
using UE::MovieScene::FTransformPropertyTraits = TIndirectPropertyTraits<FTransform, FIntermediate3DTransform>
Definition at line 655 of file MovieSceneTracksComponentTypes.h.
FVector2ParameterTraits
using UE::MovieScene::FVector2ParameterTraits = TIndirectPropertyTraits<FVector2f, FFloatIntermediateVector>
Definition at line 666 of file MovieSceneTracksComponentTypes.h.
FVector3ParameterTraits
using UE::MovieScene::FVector3ParameterTraits = TIndirectPropertyTraits<FVector3f, FFloatIntermediateVector>
Definition at line 667 of file MovieSceneTracksComponentTypes.h.
PreLockedAllocationItemFunctionPtr
using UE::MovieScene::PreLockedAllocationItemFunctionPtr = void (*)(FEntityAllocationIteratorItem Item, TArrayView<const FPreLockedDataPtr> PreLockedData, const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
Definition at line 157 of file IMovieSceneTaskScheduler.h.
TaskFunctionPtr
using UE::MovieScene::TaskFunctionPtr = TVariant<UnboundTaskFunctionPtr, AllocationFunctionPtr, AllocationItemFunctionPtr, PreLockedAllocationItemFunctionPtr>
Definition at line 159 of file IMovieSceneTaskScheduler.h.
TComponentReader
template<typename T> using UE::MovieScene::TComponentReader = TComponentLock<TRead<T>>
Definition at line 426 of file MovieSceneComponentPtr.h.
TComponentWriter
template<typename T> using UE::MovieScene::TComponentWriter = TComponentLock<TWrite<T>>
Definition at line 428 of file MovieSceneComponentPtr.h.
TCustomPropertyAccessorFunctions
template<typename PropertyTraits> using UE::MovieScene::TCustomPropertyAccessorFunctions = TCustomPropertyAccessorFunctionsImpl<PropertyTraits, typename PropertyTraits::MetaDataType>
Definition at line 132 of file MovieScenePropertySystemTypes.h.
TMultiComponentLock
template<typename... T> using UE::MovieScene::TMultiComponentLock = TTuple<TComponentLock<T>...>
Definition at line 432 of file MovieSceneComponentPtr.h.
TMultiReadOptional
template<typename... T> using UE::MovieScene::TMultiReadOptional = TMultiComponentData<TReadOptional<T>...>
Definition at line 471 of file MovieSceneComponentPtr.h.
TOptionalComponentReader
template<typename T> using UE::MovieScene::TOptionalComponentReader = TComponentLock<TReadOptional<T>>
Definition at line 427 of file MovieSceneComponentPtr.h.
TOptionalComponentWriter
template<typename T> using UE::MovieScene::TOptionalComponentWriter = TComponentLock<TWriteOptional<T>>
Definition at line 429 of file MovieSceneComponentPtr.h.
TOverlappingEntityTracker
template<typename OutputType, typename... KeyType> using UE::MovieScene::TOverlappingEntityTracker
Initial value:
 std::conditional_t<
    (THasAddReferencedObjectForComponent<KeyType>::Value || ...) || THasAddReferencedObjectForComponent<OutputType>::Value,
    TOverlappingEntityTracker_WithGarbage<OutputType, KeyType...>,
    TOverlappingEntityTracker_NoGarbage<OutputType, KeyType...>
>
Definition at line 674 of file MovieSceneOverlappingEntityTracker.h.
TPreAnimatedMaterialParameterTraits
template<typename AccessorType, typename... RequiredComponents> using UE::MovieScene::TPreAnimatedMaterialParameterTraits = TPreAnimatedMaterialTraits<AccessorType, RequiredComponents...>
Definition at line 85 of file MovieSceneMaterialSystem.h.
TPreAnimatedPropertyStorage
template<typename PropertyTraits> using UE::MovieScene::TPreAnimatedPropertyStorage = TPreAnimatedPropertyStorageImpl<PropertyTraits, typename PropertyTraits::MetaDataType, TMakeIntegerSequence<int, PropertyTraits::MetaDataType::Num>>
Definition at line 253 of file MovieScenePreAnimatedPropertyStorage.h.
TReadOneOf
template<typename... T> using UE::MovieScene::TReadOneOf = TMultiComponentData<TReadOptional<T>...>
Definition at line 473 of file MovieSceneComponentPtr.h.
TReadOneOrMoreOf
template<typename... T> using UE::MovieScene::TReadOneOrMoreOf = TMultiComponentData<TReadOptional<T>...>
Definition at line 472 of file MovieSceneComponentPtr.h.
TSetCompositePropertyValues
template<typename PropertyTraits, typename ... CompositeTypes> using UE::MovieScene::TSetCompositePropertyValues = TSetCompositePropertyValuesImpl<PropertyTraits, typename PropertyTraits::MetaDataType, CompositeTypes...>
Definition at line 688 of file MovieScenePropertySystemTypes.h.
TSetPartialPropertyValues
template<typename PropertyTraits, typename ... CompositeTypes> using UE::MovieScene::TSetPartialPropertyValues = TSetPartialPropertyValuesImpl<PropertyTraits, typename PropertyTraits::MetaDataType, TMakeIntegerSequence<int, sizeof...(CompositeTypes)>, CompositeTypes...>
Definition at line 86 of file MovieScenePartialProperties.h.
UnboundTaskFunctionPtr
using UE::MovieScene::UnboundTaskFunctionPtr = void (*)(const ITaskContext* TaskContext, FEntityAllocationWriteContext WriteContext)
Definition at line 154 of file IMovieSceneTaskScheduler.h.
Enumeration Type Documentation
EAutoLinkRelevantSystems
enum class UE::MovieScene::EAutoLinkRelevantSystems : uint8 strong
Enumerator
Enabled
Disable
Definition at line 35 of file MovieSceneEntitySystemLinker.h.
ECachedEntityManagerState
enum class UE::MovieScene::ECachedEntityManagerState strong
Signifies whether any caches held for the current cached result are still up to date, or whether they should be updated.
Enumerator
UpToDate
The structure of the entity manager has not changed since it was last cached.
Stale
The structure of the entity manager has changed since it was last cached and any caches must be re-generated.
Definition at line 19 of file MovieSceneCachedEntityFilterResult.h.
EColorPropertyType
enum class UE::MovieScene::EColorPropertyType : uint8 strong
Color type for the color property system.
Enumerator
Undefined
Undefined.
Slate
FSlateColor.
Linear
FLinearColor.
Color
FColor.
Definition at line 99 of file MovieSceneTracksPropertyTypes.h.
EComplexInclusivityFilterMode
enum class UE::MovieScene::EComplexInclusivityFilterMode strong
Enumeration specifying how to apply a complex filter for mutual inclusion.
Enumerator
AllOf
Specifies that all the components must be present for a mutal component to be included.
AnyOf
Specifies that the mutal component should be included if any of the specified components are present.
Definition at line 21 of file MovieSceneMutualComponentInclusivity.h.
EEntityGroupFlags
enum class UE::MovieScene::EEntityGroupFlags : uint8 strong
Flags for FEntityGroupID.
Enumerator
None
RemovedFromGroup
Definition at line 504 of file BuiltInComponentTypes.h.
EEntityRecursion
enum class UE::MovieScene::EEntityRecursion : uint8 strong
Enumerator
This
Perform the action on this entity (ie, the entity passed in)
Children
Perform the action on this entity's children recursively.
Full
Perform the action on this entity and all its children recursively.
Definition at line 59 of file MovieSceneEntityManager.h.
EEntitySystemCategory
enum class UE::MovieScene::EEntitySystemCategory : uint32 strong
Enumerator
None
Unspecified
Core
ChannelEvaluators
BlenderSystems
PropertySystems
Custom
Last
All
Definition at line 32 of file MovieSceneEntitySystem.h.
EEntitySystemLinkerRole
enum class UE::MovieScene::EEntitySystemLinkerRole : uint32 strong
Enum that describes what a sequencer ECS linker is meant for (only used for debugging reasons)
Enumerator
Unknown
The linker's role is unknown.
LevelSequences
The linker is handling level sequences.
CameraAnimations
The linker is handling camera animations.
UMG
The linker is handling UMG animations.
Standalone
The linker is handling a standalone sequence, such as those with a blocking evaluation flag.
Interrogation
This linker is running interrogations.
Custom
This value and any greater values are for other custom roles.
Definition at line 42 of file MovieSceneEntitySystemLinker.h.
EEntityThreadingModel
enum class UE::MovieScene::EEntityThreadingModel : uint8 strong
Enumeration that defines a threading model for this entity manager.
Enumerator
NoThreading
Specified when the data contained within an entity manager does not satisfy the requirements to justify using threaded evaluation.
TaskGraph
Specified when the data contained within an entity manager is large or complex enough to justify threaded evaluation.
Definition at line 16 of file MovieSceneMaybeAtomic.h.
EEvaluationHookEvent
enum class UE::MovieScene::EEvaluationHookEvent strong
Enumerator
Begin
Update
End
Trigger
Definition at line 21 of file IMovieSceneEvaluationHook.h.
EHierarchicalBlendMode
enum class UE::MovieScene::EHierarchicalBlendMode : uint8 strong
Enumerator
AccumulateParentToChild
ChildFirstBlendTarget
Definition at line 42 of file WeightAndEasingEvaluatorSystem.h.
EInverseEvaluateFlags
enum class UE::MovieScene::EInverseEvaluateFlags : uint8 strong
Flags for controlling inverse evaluation.
Enumerator
Forwards
Backwards
Equal
Cycle
IgnoreClamps
AnyDirection
Definition at line 16 of file MovieSceneTransformTypes.h.
EMovieSceneBindingLifetimeState
enum class UE::MovieScene::EMovieSceneBindingLifetimeState : uint8 strong
Enumerator
Active
Object Binding State is Active.
Tracks on this binding will be active.
Inactive
Object Binding is Inactive.
Tracks on this binding will be inactive and states will be restored/kept depending on settings.
Definition at line 330 of file BuiltInComponentTypes.h.
EPlaybackCapabilityStorageMode
enum class UE::MovieScene::EPlaybackCapabilityStorageMode : uint8 strong
Enumerator
Inline
RawPointer
SharedPointer
Definition at line 19 of file MovieScenePlaybackCapabilities.h.
EPreAnimatedCaptureSourceState
enum class UE::MovieScene::EPreAnimatedCaptureSourceState strong
Enumerator
New
Updated
UpToDate
Definition at line 28 of file MovieScenePreAnimatedCaptureSources.h.
EPreAnimatedCaptureSourceTracking
enum class UE::MovieScene::EPreAnimatedCaptureSourceTracking strong
Enum that defines how to cache pre-animated values based on their capture source.
Enumerator
CacheIfTracked
Cache the pre-animated value only if we are already tracking a capture source for it (or if global capture is enabled)
AlwaysCache
Always cache the pre-animated value, potentially adding tracking meta-data for the scoped capture source.
Definition at line 44 of file MovieScenePreAnimatedStateStorage.h.
EPreAnimatedStorageRequirement
enum class UE::MovieScene::EPreAnimatedStorageRequirement : uint8 strong
Enumerator
None
Persistent
Transient
NoChange
Definition at line 31 of file MovieScenePreAnimatedStateTypes.h.
ERunnerFlushState
enum class UE::MovieScene::ERunnerFlushState strong
Bit-mask enumeration that defines tasks that need running.
Enumerator
None
Start
ConditionalRecompile
Import
ReimportAfterCompile
Spawn
Instantiation
Evaluation
Finalization
EventTriggers
PostEvaluation
End
Definition at line 29 of file MovieSceneEntitySystemRunner.h.
ESequenceInstanceInvalidationType
enum class UE::MovieScene::ESequenceInstanceInvalidationType : uint8 strong
Specifies what cached data should be invalidated in a sequence instance.
Enumerator
DataChanged
Only invalidate cached data for sequences whose data has been dynamically changed.
All
Invalidate all cached data for all sequences.
Definition at line 52 of file MovieSceneSequenceInstance.h.
ESequenceInstanceUpdateFlags
enum class UE::MovieScene::ESequenceInstanceUpdateFlags : uint8 strong
Enumerator
None
NeedsDissection
NeedsPreEvaluation
NeedsPostEvaluation
HasLegacyTemplates
Definition at line 39 of file MovieSceneSequenceInstance.h.
ESparseBitSetBitResult
enum class UE::MovieScene::ESparseBitSetBitResult strong
Enumerator
NewlySet
AlreadySet
Definition at line 24 of file SparseBitSet.h.
ETimeWarpChannelDomain
enum class UE::MovieScene::ETimeWarpChannelDomain : uint8 strong
Enumerator
Time
PlayRate
Definition at line 14 of file MovieSceneTimeWarpChannel.h.
EUnlinkEverythingMode
enum class UE::MovieScene::EUnlinkEverythingMode strong
Enumerator
Normal
CleanGarbage
Definition at line 27 of file MovieSceneEntityLedger.h.
Function Documentation
AddAccessorToFilter() [1/6]
void UE::MovieScene::AddAccessorToFilter (const FComponentAccess * In, FEntityComponentFilter * OutFilter) inline
Definition at line 422 of file MovieSceneComponentAccessors.h.
References check, and UE::MovieScene::FComponentAccess::ComponentType.
AddAccessorToFilter() [2/6]
void UE::MovieScene::AddAccessorToFilter (const FEntityIDAccess * , FEntityComponentFilter * OutFilter) inline
Definition at line 416 of file MovieSceneComponentAccessors.h.
Referenced by UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateFilter().
AddAccessorToFilter() [3/6]
void UE::MovieScene::AddAccessorToFilter (const FFilterMatchPassthrough * , FEntityComponentFilter * OutFilter) inline
Definition at line 419 of file MovieSceneComponentAccessors.h.
AddAccessorToFilter() [4/6]
void UE::MovieScene::AddAccessorToFilter (const FOptionalComponentAccess * In, FEntityComponentFilter * OutFilter) inline
Definition at line 427 of file MovieSceneComponentAccessors.h.
AddAccessorToFilter() [5/6]
template<typename... T> void UE::MovieScene::AddAccessorToFilter (const TReadOneOfAccessor< T... > * In, FEntityComponentFilter * OutFilter)
Definition at line 431 of file MovieSceneComponentAccessors.h.
References check, Component, UE::MovieScene::FOptionalComponentAccess::ComponentType, UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes, and Mask.
AddAccessorToFilter() [6/6]
template<typename... T> void UE::MovieScene::AddAccessorToFilter (const TReadOneOrMoreOfAccessor< T... > * In, FEntityComponentFilter * OutFilter)
Definition at line 447 of file MovieSceneComponentAccessors.h.
References check, Component, UE::MovieScene::FOptionalComponentAccess::ComponentType, UE::MovieScene::TReadOneOrMoreOfAccessor< T >::ComponentTypes, and Mask.
AddChannelProxy()
template<typename ChannelType, typename ExtendedEditorDataType> void UE::MovieScene::AddChannelProxy (FMovieSceneChannelProxyData & ProxyData, const UMovieSceneSectionChannelOverrideRegistry * OverrideRegistry, FName ChannelName, ChannelType & DefaultChannel, const FMovieSceneChannelMetaData & InMetaData, ExtendedEditorDataType && InExtendedEditorData)
Utility function for adding a possibly-overriden channel into a channel proxy, with some specific extended editor data.
Definition at line 154 of file MovieSceneSectionChannelOverrideRegistry.h.
References FMovieSceneChannelProxyData::Add(), AddChannelProxy(), GetChannelOverride(), and FMovieSceneChannelProxyData::SetExtendedEditorData().
Referenced by AddChannelProxy().
AddGlobalCustomAccessor()
MOVIESCENE_API void UE::MovieScene::AddGlobalCustomAccessor (const UClass * ClassType, FName PropertyPath)
Referenced by UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::Add().
AddKeyToChannel()
template<typename ChannelType, typename ValueType> FKeyHandle UE::MovieScene::AddKeyToChannel (ChannelType * InChannel, FFrameNumber InTime, ValueType && Value, EMovieSceneKeyInterpolation Interpolation)
Add a key to a channel, or update an existing key if one already exists at this time.
Parameters
InChannel The channel the value is contained within
InTime The time to add or update the key at
InValue The new value
Returns
A handle to the key that was added
Definition at line 146 of file MovieSceneChannelTraits.h.
References AssignValue(), Forward(), Handle, INDEX_NONE, InTime, FKeyHandle::Invalid(), and Value.
AddReferencedObjectForComponent() [1/6]
FNotImplemented * UE::MovieScene::AddReferencedObjectForComponent (...) inline
Stub for components that do not need reference collection.
Overload void AddReferencedObjectForComponent(FReferenceCollector* ReferenceCollector, T* Component) for your own implementation NOTE: The return value is very important - overloaded AddReferencedObjectForComponent functions should return void otherwise they will not get called by the entity manager.
Definition at line 31 of file MovieSceneComponentTypeInfo.h.
Referenced by UE::MovieScene::FComponentTypeInfo::TComplexComponentOps< T >::AddReferencedObjects(), UE::MovieScene::FGarbageTraits::AddReferencedObjects(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::AddReferencedObjects().
AddReferencedObjectForComponent() [2/6]
void UE::MovieScene::AddReferencedObjectForComponent (FReferenceCollector * ReferenceCollector, FObjectKey * Component) inline
Definition at line 49 of file MovieSceneComponentTypeInfo.h.
References Component.
AddReferencedObjectForComponent() [3/6]
template<typename T> TEnableIf< TPointerIsConvertibleFromTo< T, UObject >::Value >::Type UE::MovieScene::AddReferencedObjectForComponent (FReferenceCollector * ReferenceCollector, T ** Component)
Instantiation for raw pointers.
Definition at line 35 of file MovieSceneComponentTypeInfo.h.
References Component.
AddReferencedObjectForComponent() [4/6]
template<typename T, typename U = decltype(T::StaticStruct())> void UE::MovieScene::AddReferencedObjectForComponent (FReferenceCollector * ReferenceCollector, T * Component)
Definition at line 57 of file MovieSceneComponentTypeInfo.h.
References FReferenceCollector::AddReferencedObject(), and Component.
AddReferencedObjectForComponent() [5/6]
template<typename T> void UE::MovieScene::AddReferencedObjectForComponent (FReferenceCollector * ReferenceCollector, TObjectKey< T > * Component)
Definition at line 53 of file MovieSceneComponentTypeInfo.h.
References Component.
AddReferencedObjectForComponent() [6/6]
template<typename T> void UE::MovieScene::AddReferencedObjectForComponent (FReferenceCollector * ReferenceCollector, TObjectPtr< T > * Component)
Definition at line 43 of file MovieSceneComponentTypeInfo.h.
References FReferenceCollector::AddReferencedObject(), and Component.
AssignValue()
template<typename ChannelType, typename ValueType> bool UE::MovieScene::AssignValue (ChannelType * InChannel, FKeyHandle InKeyHandle, ValueType && InValue)
Called to assign a specific value in a channel.
Parameters
InChannel The channel the value is contained within
InKeyHandle The handle of the key to assign to
InValue The new value
Returns
If the value was successfully assigned. Will return false if the key handle doesn't belong to that channel.
Definition at line 100 of file MovieSceneChannelTraits.h.
References Forward(), and INDEX_NONE.
Referenced by AddKeyToChannel().
BlendValue() [1/5]
template<typename OutputType, typename InputType, typename ActualValueType> void UE::MovieScene::BlendValue (TMaskedBlendable< OutputType, 1 > & OutBlend, InputType InValue, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< ActualValueType > & InitialValueStore)
Definition at line 321 of file MovieSceneMultiChannelBlending.h.
References BlendValue(), and Weight.
BlendValue() [2/5]
template<typename OutputType, typename ActualValueType, uint8 ChannelSize> void UE::MovieScene::BlendValue (TMaskedBlendable< OutputType, ChannelSize > & OutBlend, const TMultiChannelValue< OutputType, ChannelSize > & InValue, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< ActualValueType > & InitialValueStore)
Definition at line 327 of file MovieSceneMultiChannelBlending.h.
References BlendValue(), UE::MovieScene::TMultiChannelValue< T, N >::IsSet(), and Weight.
BlendValue() [3/5]
template<typename OutputType, typename InputType, typename ActualValueType, uint8 ChannelSize> void UE::MovieScene::BlendValue (TMaskedBlendable< OutputType, ChannelSize > & OutBlend, InputType InValue, int32 ChannelIndex, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< ActualValueType > & InitialValueStore)
Definition at line 264 of file MovieSceneMultiChannelBlending.h.
References UE::MovieScene::TMaskedBlendable< DataType, N >::Absolute, UE::MovieScene::TMaskedBlendable< DataType, N >::AbsoluteWeights, UE::MovieScene::TMaskedBlendable< DataType, N >::Additive, TMovieSceneInitialValueStore< DataType >::GetInitialValue(), UE::MovieScene::TMultiChannelValue< T, N >::Increment(), INDEX_NONE, UE::MovieScene::TMaskedBlendable< DataType, N >::InitialValue, UE::MovieScene::TMultiChannelValue< T, N >::IsSet(), MultiChannelFromData(), UE::MovieScene::TMaskedBlendable< DataType, N >::Override, UE::MovieScene::TMultiChannelValue< T, N >::Set(), Weight, and UE::MovieScene::TMultiChannelValue< T, N >::WeightedBlend().
BlendValue() [4/5]
template<typename InType, typename WorkingDataType, typename SourceDataType> void UE::MovieScene::BlendValue (WorkingDataType & OutBlend, InType InValue, float Weight, EMovieSceneBlendType BlendType, int32 BlendingOrder, TMovieSceneInitialValueStore< SourceDataType > & InitialValueStore)
Definition at line 86 of file BlendableToken.h.
References Weight.
BlendValue() [5/5]
template<typename InType, typename WorkingDataType, typename SourceDataType> void UE::MovieScene::BlendValue (WorkingDataType & OutBlend, InType InValue, float Weight, EMovieSceneBlendType BlendType, TMovieSceneInitialValueStore< SourceDataType > & InitialValueStore)
Definition at line 80 of file BlendableToken.h.
References BlendValue(), INDEX_NONE, and Weight.
Referenced by TBlendableToken< DataType >::TData< T >::AddTo(), BlendValue(), BlendValue(), and BlendValue().
ClampToDiscreteRange()
FFrameTime UE::MovieScene::ClampToDiscreteRange (FFrameTime InTime, const TRange< FFrameNumber > & InRange) inline
Clamp the specified time to a range.
Definition at line 253 of file MovieSceneTimeHelpers.h.
References FMath::Clamp(), DiscreteExclusiveUpper(), DiscreteInclusiveLower(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), InTime, and TRangeBound< ElementType >::IsClosed().
CollectGarbageForOutput() [1/3]
MOVIESCENETRACKS_API void UE::MovieScene::CollectGarbageForOutput (FAnimatedCustomPrimitiveDataInfo * Output)
CollectGarbageForOutput() [2/3]
MOVIESCENETRACKS_API void UE::MovieScene::CollectGarbageForOutput (FAnimatedMaterialParameterInfo * Output)
CollectGarbageForOutput() [3/3]
void UE::MovieScene::CollectGarbageForOutput (void *) inline
Override for OutputType* in order to provide custom garbage collection logic.
Definition at line 91 of file MovieSceneOverlappingEntityTracker.h.
Referenced by UE::MovieScene::TOverlappingEntityTracker_WithGarbage< OutputType, InputTypes... >::TagGarbage().
ConvertOperationalProperty() [1/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FColor & InColor, FIntermediateColor & OutIntermediate)
ConvertOperationalProperty() [2/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FDoubleIntermediateVector & InVector, FVector2d & Out)
ConvertOperationalProperty() [3/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FDoubleIntermediateVector & InVector, FVector3d & Out)
ConvertOperationalProperty() [4/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FDoubleIntermediateVector & InVector, FVector4d & Out)
ConvertOperationalProperty() [5/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FEulerTransform & In, FIntermediate3DTransform & Out)
ConvertOperationalProperty() [6/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FFloatIntermediateVector & InVector, FVector2f & Out)
ConvertOperationalProperty() [7/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FFloatIntermediateVector & InVector, FVector3f & Out)
ConvertOperationalProperty() [8/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FFloatIntermediateVector & InVector, FVector4f & Out)
ConvertOperationalProperty() [9/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FIntermediate3DTransform & In, FEulerTransform & Out)
ConvertOperationalProperty() [10/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FIntermediate3DTransform & In, FTransform & Out)
ConvertOperationalProperty() [11/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FIntermediateColor & InColor, FColor & Out)
ConvertOperationalProperty() [12/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FIntermediateColor & InColor, FLinearColor & Out)
ConvertOperationalProperty() [13/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FIntermediateColor & InColor, FSlateColor & Out)
ConvertOperationalProperty() [14/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FLinearColor & InColor, FIntermediateColor & OutIntermediate)
ConvertOperationalProperty() [15/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FObjectComponent & In, UObject *& Out)
ConvertOperationalProperty() [16/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FSlateColor & InColor, FIntermediateColor & OutIntermediate)
ConvertOperationalProperty() [17/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FTransform & In, FIntermediate3DTransform & Out)
ConvertOperationalProperty() [18/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FVector2d & In, FDoubleIntermediateVector & Out)
ConvertOperationalProperty() [19/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FVector2f & In, FFloatIntermediateVector & Out)
ConvertOperationalProperty() [20/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FVector3d & In, FDoubleIntermediateVector & Out)
ConvertOperationalProperty() [21/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FVector3f & In, FFloatIntermediateVector & Out)
ConvertOperationalProperty() [22/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FVector4d & In, FDoubleIntermediateVector & Out)
ConvertOperationalProperty() [23/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (const FVector4f & In, FFloatIntermediateVector & Out)
ConvertOperationalProperty() [24/27]
template<typename InType, typename OutType> void UE::MovieScene::ConvertOperationalProperty (const InType & In, OutType & Out)
Definition at line 12 of file MovieSceneOperationalTypeConversions.h.
Referenced by UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue(), UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue(), UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue(), UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::SetObjectPropertyValue(), and UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::SetObjectPropertyValue().
ConvertOperationalProperty() [25/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (double In, float & Out)
ConvertOperationalProperty() [26/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (float In, double & Out)
ConvertOperationalProperty() [27/27]
MOVIESCENETRACKS_API void UE::MovieScene::ConvertOperationalProperty (UObject * In, FObjectComponent & Out)
ConvertRange() [1/2]
template<> TRange< FFrameNumber > UE::MovieScene::ConvertRange (const TRange< FFrameTime > & Range) inline
Definition at line 372 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::Inclusive(), TRangeBound< ElementType >::IsInclusive(), and TRangeBound< ElementType >::IsOpen().
ConvertRange() [2/2]
template<typename InBoundType, typename OutBoundType> TRange< OutBoundType > UE::MovieScene::ConvertRange (const TRange< InBoundType > & Range) inline
Converts a range from one type of bounds to another.
The output bounds type must be implicitly constructable from the input bounds type.
Definition at line 351 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::Inclusive(), TRangeBound< ElementType >::IsInclusive(), and TRangeBound< ElementType >::IsOpen().
ConvertToDiscreteRange()
TRange< FFrameNumber > UE::MovieScene::ConvertToDiscreteRange (const TRange< FFrameTime > & InRange) inline
Definition at line 321 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBoundValue(), TRange< ElementType >::HasLowerBound(), TRange< ElementType >::HasUpperBound(), TRangeBound< ElementType >::Inclusive(), and TRangeBound< ElementType >::IsInclusive().
ConvertToFrameTimeRange() [1/2]
TRange< FFrameTime > UE::MovieScene::ConvertToFrameTimeRange (const TRange< FFrameNumber > & InRange) inline
Convert a frame number range into a frame time range.
Definition at line 265 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBound(), TRange< ElementType >::GetUpperBoundValue(), TRange< ElementType >::HasLowerBound(), TRange< ElementType >::HasUpperBound(), TRangeBound< ElementType >::Inclusive(), and TRangeBound< ElementType >::IsInclusive().
ConvertToFrameTimeRange() [2/2]
TRange< FFrameTime > UE::MovieScene::ConvertToFrameTimeRange (const TRange< float > & InRange) inline
Definition at line 293 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), FFrameTime::FromDecimal(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBound(), TRange< ElementType >::GetUpperBoundValue(), TRange< ElementType >::HasLowerBound(), TRange< ElementType >::HasUpperBound(), TRangeBound< ElementType >::Inclusive(), and TRangeBound< ElementType >::IsInclusive().
CycleTime()
MOVIESCENE_API FCycleParams UE::MovieScene::CycleTime (FFrameNumber MinFrame, FFrameNumber MaxFrame, FFrameTime InTime)
References InTime.
DECLARE_CYCLE_STAT() [1/3]
UE::MovieScene::DECLARE_CYCLE_STAT (TEXT("Apply properties") , MovieSceneEval_ApplyProperties , STATGROUP_MovieSceneECS)
DECLARE_CYCLE_STAT() [2/3]
UE::MovieScene::DECLARE_CYCLE_STAT (TEXT("Aquire Component Access Locks") , MovieSceneEval_AquireComponentAccessLocks , STATGROUP_MovieSceneECS)
DECLARE_CYCLE_STAT() [3/3]
UE::MovieScene::DECLARE_CYCLE_STAT (TEXT("Release Component Access Locks") , MovieSceneEval_ReleaseComponentAccessLocks , STATGROUP_MovieSceneECS)
DECLARE_DELEGATE_RetVal_TwoParams()
UE::MovieScene::DECLARE_DELEGATE_RetVal_TwoParams (FPropertyRecomposerPropertyInfo , FOnGetPropertyRecomposerPropertyInfo , FMovieSceneEntityID , UObject *)
DilateRange()
template<typename T> TRange< T > UE::MovieScene::DilateRange (const TRange< T > & InRange, T LowerAmount, T UpperAmount) inline
Dilate the specified range by adding a specific size to the lower and upper bounds (if closed)
Definition at line 209 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), TRangeBound< ElementType >::Inclusive(), and TRangeBound< ElementType >::Open().
Referenced by ExpandRange(), and TranslateRange().
DiscreteExclusiveUpper() [1/2]
FFrameNumber UE::MovieScene::DiscreteExclusiveUpper (const TRange< FFrameNumber > & InRange) inline
Return the first frame number not contained by the specified range.
Assumes a closed upper bound. For example, a range of (0:10) would return 10, and [0:10] would return 11
Definition at line 81 of file MovieSceneTimeHelpers.h.
References DiscreteExclusiveUpper(), and TRange< ElementType >::GetUpperBound().
DiscreteExclusiveUpper() [2/2]
FFrameNumber UE::MovieScene::DiscreteExclusiveUpper (const TRangeBound< FFrameNumber > & InUpperBound) inline
Return the first frame number that is not contained by the specified closed upper bound.
For example, a bound of 10) would return 10, and 10] would return 11
Definition at line 66 of file MovieSceneTimeHelpers.h.
References check, TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::IsInclusive(), and TRangeBound< ElementType >::IsOpen().
Referenced by ClampToDiscreteRange(), DiscreteExclusiveUpper(), DiscreteSize(), and FMovieSceneEvaluationRange::GetEvaluationFieldTime().
DiscreteInclusiveLower() [1/2]
FFrameNumber UE::MovieScene::DiscreteInclusiveLower (const TRange< FFrameNumber > & InRange) inline
Return the first frame number included by the specified range.
Assumes a closed lower bound. For example, a range of (0:10) would return 1, and [0:10] would return 0
Definition at line 57 of file MovieSceneTimeHelpers.h.
References DiscreteInclusiveLower(), and TRange< ElementType >::GetLowerBound().
DiscreteInclusiveLower() [2/2]
FFrameNumber UE::MovieScene::DiscreteInclusiveLower (const TRangeBound< FFrameNumber > & InLowerBound) inline
Return the first frame number included by the specified closed lower bound.
For example, a bound of (0 would return 1, and [0 would return 0
Definition at line 42 of file MovieSceneTimeHelpers.h.
References check, TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::IsExclusive(), and TRangeBound< ElementType >::IsOpen().
Referenced by ClampToDiscreteRange(), DiscreteInclusiveLower(), DiscreteSize(), and FMovieSceneEvaluationRange::GetEvaluationFieldTime().
DiscreteRangeIsEmpty()
bool UE::MovieScene::DiscreteRangeIsEmpty (const TRange< FFrameNumber > & InRange) inline
Check whether the specified range contains any integer frame numbers or not.
Definition at line 178 of file MovieSceneTimeHelpers.h.
References TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBound(), TRange< ElementType >::GetUpperBoundValue(), TRangeBound< ElementType >::IsInclusive(), and TRangeBound< ElementType >::IsOpen().
DiscreteSize()
int32 UE::MovieScene::DiscreteSize (const TRange< FFrameNumber > & InRange) inline
Calculate the size of a discrete frame range, taking into account inclusive/exclusive boundaries.
Parameters
InRange The range to calculate for. Must be a frinite range.
Returns
The size of the range (considering inclusive and exclusive boundaries)
Definition at line 170 of file MovieSceneTimeHelpers.h.
References DiscreteExclusiveUpper(), DiscreteInclusiveLower(), and FFrameNumber::Value.
Referenced by MakeDiscreteRangeFromLower(), and MakeDiscreteRangeFromUpper().
ENUM_CLASS_FLAGS() [1/6]
UE::MovieScene::ENUM_CLASS_FLAGS (EEntityGroupFlags)
ENUM_CLASS_FLAGS() [2/6]
UE::MovieScene::ENUM_CLASS_FLAGS (EEntityRecursion)
ENUM_CLASS_FLAGS() [3/6]
UE::MovieScene::ENUM_CLASS_FLAGS (EInverseEvaluateFlags)
Parameter structure that controls time-transformation operations in MovieScene code.
Instruct the algorithm to add breadcrumbs to the specified container as it performs the transformation
Note
: this function will empty the breadcrumbs
Instruct the algorithm to add breadcrumbs to the specified container as it performs the transformation
Note
: this function will not empty the breadcrumbs, allowing the callsite to append paths of breadcrumbs together
Instruct the algorithm to track the cycle counts
Ignore clamping operations while transforming the time.
Breadcrumbs structure. When non-null, breadcrumbs will be added according to its FMovieSceneTransformBreadcrumbs::Mode
Pointer that receives the last encountered cycle count
Whether to ignore clamp operations or not
Definition at line 27 of file MovieSceneTransformTypes.h.
References IgnoreClamps.
ENUM_CLASS_FLAGS() [4/6]
UE::MovieScene::ENUM_CLASS_FLAGS (ERunnerFlushState)
Bit-field enumeration that defines flags for an asynchronous update request.
Definition at line 44 of file MovieSceneEntitySystemRunner.h.
References None.
ENUM_CLASS_FLAGS() [5/6]
UE::MovieScene::ENUM_CLASS_FLAGS (ERunnerUpdateFlags)
Result from a runner flush state that indicates how to proceed.
Continue evaluation, allow budgeting
Continue evaluation without budgeting the next step.
Do not continue evaluation and break out of our loop.
Definition at line 56 of file MovieSceneEntitySystemRunner.h.
References Break.
ENUM_CLASS_FLAGS() [6/6]
UE::MovieScene::ENUM_CLASS_FLAGS (ESequenceInstanceUpdateFlags)
EvaluateChannel() [1/2]
template<typename ChannelType, typename ValueType> bool UE::MovieScene::EvaluateChannel (const ChannelType * InChannel, FFrameTime InTime, ValueType & OutValue)
Called to evaluate a channel.
Overload with specific channel types for custom behaviour.
Parameters
InChannel The channel to evaluate
InTime The time to evaluate at
OutValue Value to receive the result
Returns
true if the channel was evaluated successfully, false otherwise
Definition at line 71 of file MovieSceneChannelTraits.h.
References InTime.
Referenced by EvaluateChannel(), and ValueExistsAtTime().
EvaluateChannel() [2/2]
template<typename ChannelType, typename ValueType> bool UE::MovieScene::EvaluateChannel (const UMovieSceneSection * InSection, const ChannelType * InChannel, FFrameTime InTime, ValueType & OutValue)
Called to evaluate a channel.
Overload with specific channel types for custom behaviour.
Parameters
InSection The section that contains the channel
InChannel The channel to evaluate
InTime The time to evaluate at
OutValue Value to receive the result
Returns
true if the channel was evaluated successfully, false otherwise
Definition at line 86 of file MovieSceneChannelTraits.h.
References EvaluateChannel(), and InTime.
EvaluateTime() [1/2]
MOVIESCENE_API void UE::MovieScene::EvaluateTime (TArrayView< const FFrameNumber > InTimes, FFrameTime InTime, int32 & OutIndex1, int32 & OutIndex2)
Evaluate the specified time array by finding the two indices that are adjacent to the supplied time.
Parameters
InTimes A sorted array of frame numbers
InTime The time to find within the array
OutIndex1 The first time in the array that's >= InTime, or INDEX_NONE if there are none
OutIndex2 OutIndex1 + 1 if it is a valid index in the array, INDEX_NONE otherwise
References InTime.
EvaluateTime() [2/2]
MOVIESCENE_API void UE::MovieScene::EvaluateTime (TArrayView< const FFrameNumber > InTimes, FFrameTime InTime, int32 & OutIndex1, int32 & OutIndex2, double & OutInterp)
Evaluate the specified time array by finding the two indices and an interpolation value that are adjacent to the supplied time.
Parameters
InTimes A sorted array of frame numbers
InTime The time to find within the array
OutIndex1 The first time in the array that's >= InTime, or INDEX_NONE if there are none
OutIndex2 OutIndex1 + 1 if it is a valid index in the array, INDEX_NONE otherwise
OutInterp A value from 0.0 -> 1.0 specifying how a linear interpolation value from index 1 to index 2
References InTime.
ExpandRange()
template<typename T> TRange< T > UE::MovieScene::ExpandRange (const TRange< T > & InRange, T Amount) inline
Expand the specified range by subtracting the specified amount from the lower bound, and adding it to the upper bound.
Definition at line 234 of file MovieSceneTimeHelpers.h.
References DilateRange().
FindRange()
MOVIESCENE_API void UE::MovieScene::FindRange (TArrayView< const FFrameNumber > InTimes, FFrameNumber PredicateTime, FFrameNumber InTolerance, int32 MaxNum, int32 & OutMin, int32 & OutMax)
Find the range of times that fall around PredicateTime +/- InTolerance up to a maximum.
Parameters
InTimes A sorted array of frame numbers
PredicateTime The time around which to search
InTolerance The tolerance range to search around PredicateTime with
MaxNum A maximum number of times to find, starting with those closest to the predicate time
OutMin The earliest index that met the conditions of the search
OutMax The latest index that met the conditions of the search
Referenced by TMovieSceneChannelData< const ValueType >::FindKey(), and TMovieSceneChannelData< const ValueType >::FindKeys().
GCC_ALIGN()
UE::MovieScene::GCC_ALIGN (PLATFORM_CACHE_LINE_SIZE)
GetChannelDefault() [1/2]
template<typename ChannelType, typename ValueType> TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults, bool >::Type UE::MovieScene::GetChannelDefault (ChannelType * Channel, ValueType & OutDefaultValue)
Gets the default value for the channel if set.
Parameters
InChannel The channel to set the default on
Returns
If there is a default value or not.
Definition at line 218 of file MovieSceneChannelTraits.h.
GetChannelDefault() [2/2]
template<typename ChannelType, typename ValueType> TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults, bool >::Type UE::MovieScene::GetChannelDefault (ChannelType * Channel, ValueType & OutDefaultValue)
Definition at line 229 of file MovieSceneChannelTraits.h.
GetChannelOverride()
UMovieSceneChannelOverrideContainer * UE::MovieScene::GetChannelOverride (const UMovieSceneSectionChannelOverrideRegistry * OverrideRegistry, FName ChannelName) inline
Utility function to return a channel override.
Definition at line 142 of file MovieSceneSectionChannelOverrideRegistry.h.
References GetChannelOverride().
Referenced by AddChannelProxy(), GetChannelOverride(), and MakeChannelProxy().
GetComponentAtIndex() [1/2]
bool UE::MovieScene::GetComponentAtIndex (const bool * BoolPassthrough, int32 Index) inline
Definition at line 607 of file MovieSceneComponentAccessors.h.
GetComponentAtIndex() [2/2]
template<typename T> auto UE::MovieScene::GetComponentAtIndex (T * InAccessor, int32 Index) -> decltype(DeclVal<T>().ComponentAtIndex(0))
Definition at line 601 of file MovieSceneComponentAccessors.h.
Referenced by UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl(), UE::MovieScene::TEntityTaskCaller_AutoExpansion< TIntegerSequence< int, Indices... > >::ForEachEntityImpl(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerEntityImpl().
GetComponentTransform()
MOVIESCENETRACKS_API FIntermediate3DTransform UE::MovieScene::GetComponentTransform (const UObject * Object)
GetInterpolationMode()
template<typename ChannelType> EMovieSceneKeyInterpolation UE::MovieScene::GetInterpolationMode (ChannelType * InChannel, const FFrameNumber & InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
Definition at line 132 of file MovieSceneChannelTraits.h.
References InTime.
GetKeyValue()
template<typename ChannelType, typename ValueType> bool UE::MovieScene::GetKeyValue (ChannelType * InChannel, FKeyHandle InKeyHandle, ValueType & OutValue)
Definition at line 116 of file MovieSceneChannelTraits.h.
References INDEX_NONE.
GetSimulatedMotionVectorTime()
FFrameTime UE::MovieScene::GetSimulatedMotionVectorTime (const FMovieSceneContext & Context)
GlobalCustomAccessorExists() [1/2]
MOVIESCENE_API bool UE::MovieScene::GlobalCustomAccessorExists (const UClass * ClassType, TStringView< ANSICHAR > PropertyPath)
GlobalCustomAccessorExists() [2/2]
MOVIESCENE_API bool UE::MovieScene::GlobalCustomAccessorExists (const UClass * ClassType, TStringView< WIDECHAR > PropertyPath)
HasAccessorWork() [1/5]
bool UE::MovieScene::HasAccessorWork (const FEntityManager * , const FEntityIDAccess *) inline
Definition at line 651 of file MovieSceneComponentAccessors.h.
Referenced by HasAccessorWork(), HasAccessorWork(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::HasAnyWork().
HasAccessorWork() [2/5]
bool UE::MovieScene::HasAccessorWork (const FEntityManager * EntityManager, const FComponentAccess * In) inline
Definition at line 655 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType.
HasAccessorWork() [3/5]
bool UE::MovieScene::HasAccessorWork (const FEntityManager * EntityManager, const FOptionalComponentAccess * In) inline
Definition at line 659 of file MovieSceneComponentAccessors.h.
HasAccessorWork() [4/5]
template<typename... T> bool UE::MovieScene::HasAccessorWork (const FEntityManager * EntityManager, const TReadOneOfAccessor< T... > * In) inline
Definition at line 664 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes, and HasAccessorWork().
HasAccessorWork() [5/5]
template<typename... T> bool UE::MovieScene::HasAccessorWork (const FEntityManager * EntityManager, const TReadOneOrMoreOfAccessor< T... > * In) inline
Definition at line 674 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOrMoreOfAccessor< T >::ComponentTypes, and HasAccessorWork().
HasBeenWrittenToSince() [1/5]
bool UE::MovieScene::HasBeenWrittenToSince (const FComponentAccess * In, FEntityAllocation * Allocation, uint64 InSystemSerial) inline
Definition at line 567 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType.
HasBeenWrittenToSince() [2/5]
bool UE::MovieScene::HasBeenWrittenToSince (const FEntityIDAccess * In, FEntityAllocation * Allocation, uint64 InSystemSerial) inline
Definition at line 563 of file MovieSceneComponentAccessors.h.
Referenced by HasBeenWrittenToSince(), HasBeenWrittenToSince(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::HasBeenWrittenToSince().
HasBeenWrittenToSince() [3/5]
bool UE::MovieScene::HasBeenWrittenToSince (const FOptionalComponentAccess * In, FEntityAllocation * Allocation, uint64 InSystemSerial) inline
Definition at line 571 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FOptionalComponentAccess::ComponentType, and Header.
HasBeenWrittenToSince() [4/5]
template<typename... T> bool UE::MovieScene::HasBeenWrittenToSince (const TReadOneOfAccessor< T... > * In, FEntityAllocation * Allocation, uint64 InSystemSerial)
Definition at line 580 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes, and HasBeenWrittenToSince().
HasBeenWrittenToSince() [5/5]
template<typename... T> bool UE::MovieScene::HasBeenWrittenToSince (const TReadOneOrMoreOfAccessor< T... > * In, FEntityAllocation * Allocation, uint64 InSystemSerial)
Definition at line 590 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOrMoreOfAccessor< T >::ComponentTypes, and HasBeenWrittenToSince().
InvertValue()
template<typename ValueType> void UE::MovieScene::InvertValue (ValueType & InOutValue)
Definition at line 278 of file MovieSceneChannelTraits.h.
IsAccessorValid() [1/6]
bool UE::MovieScene::IsAccessorValid (const FComponentAccess * In) inline
Definition at line 620 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FComponentAccess::ComponentType, and UE::MovieScene::FComponentTypeID::Invalid().
IsAccessorValid() [2/6]
bool UE::MovieScene::IsAccessorValid (const FEntityIDAccess *) inline
Definition at line 612 of file MovieSceneComponentAccessors.h.
Referenced by IsAccessorValid(), IsAccessorValid(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::IsValid().
IsAccessorValid() [3/6]
bool UE::MovieScene::IsAccessorValid (const FFilterMatchPassthrough *) inline
Definition at line 616 of file MovieSceneComponentAccessors.h.
IsAccessorValid() [4/6]
bool UE::MovieScene::IsAccessorValid (const FOptionalComponentAccess * In) inline
Definition at line 624 of file MovieSceneComponentAccessors.h.
IsAccessorValid() [5/6]
template<typename... T> bool UE::MovieScene::IsAccessorValid (const TReadOneOfAccessor< T... > * In) inline
Definition at line 629 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes, and IsAccessorValid().
IsAccessorValid() [6/6]
template<typename... T> bool UE::MovieScene::IsAccessorValid (const TReadOneOrMoreOfAccessor< T... > * In) inline
Definition at line 639 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOrMoreOfAccessor< T >::ComponentTypes, and IsAccessorValid().
IsChannelOverriden()
bool UE::MovieScene::IsChannelOverriden (const UMovieSceneSectionChannelOverrideRegistry * OverrideRegistry, FName ChannelName) inline
Utility function to return whether a channel is overriden.
Definition at line 136 of file MovieSceneSectionChannelOverrideRegistry.h.
References IsChannelOverriden().
Referenced by IsChannelOverriden().
IsCompositePropertyTraits() [1/2]
bool UE::MovieScene::IsCompositePropertyTraits (...) constexpr
Definition at line 335 of file MovieScenePropertyComponentHandler.h.
IsCompositePropertyTraits() [2/2]
template<typename T, typename U = decltype(T::bIsComposite)> bool UE::MovieScene::IsCompositePropertyTraits (T *) constexpr
Definition at line 331 of file MovieScenePropertyComponentHandler.h.
IsEmptyOrZeroSize()
bool UE::MovieScene::IsEmptyOrZeroSize (const TRange< FFrameNumber > & InRange) inline
Return whether the given range is empty or zero frames wide.
Definition at line 127 of file MovieSceneTimeHelpers.h.
References TRange< ElementType >::IsEmpty(), and TRange< ElementType >::Size().
MakeChannelProxy()
template<typename ChannelType, typename ExtendedEditorDataType> TSharedPtr< FMovieSceneChannelProxy > UE::MovieScene::MakeChannelProxy (const UMovieSceneSectionChannelOverrideRegistry * OverrideRegistry, ChannelType & DefaultChannel, const FMovieSceneChannelMetaData & InMetaData, ExtendedEditorDataType && InExtendedEditorData)
Utility function for making a channel proxy with one channel that is maybe overriden by another channel.
Definition at line 178 of file MovieSceneSectionChannelOverrideRegistry.h.
References FMovieSceneChannelProxyData::Add(), GetChannelOverride(), MakeChannelProxy(), MakeShared(), MoveTemp(), and FMovieSceneChannelProxyData::SetExtendedEditorData().
Referenced by MakeChannelProxy().
MakeDiscreteRange()
TRange< FFrameNumber > UE::MovieScene::MakeDiscreteRange (FFrameNumber MinInclusive, FFrameNumber MaxExclusive) inline
Make a new range that includes the given minimum and excludes the given maximum.
Parameters
MinInclusive The minimum value for the inclusive lower bound
MaxExclusive The maximum value for the exclusive upper bound
Returns
A new range.
Definition at line 94 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Exclusive(), and TRangeBound< ElementType >::Inclusive().
MakeDiscreteRangeFromLower()
TRange< FFrameNumber > UE::MovieScene::MakeDiscreteRangeFromLower (const TRangeBound< FFrameNumber > & InLowerBound, int32 DiscreteSize) inline
Make a new range using the specified lower bound, and a given size.
Definition at line 136 of file MovieSceneTimeHelpers.h.
References check, DiscreteSize(), TRangeBound< ElementType >::Exclusive(), TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::IsExclusive(), and TRangeBound< ElementType >::IsOpen().
MakeDiscreteRangeFromUpper()
TRange< FFrameNumber > UE::MovieScene::MakeDiscreteRangeFromUpper (const TRangeBound< FFrameNumber > & InUpperBound, int32 DiscreteSize) inline
Make a new range using the specified upper bound, and a given size.
Definition at line 152 of file MovieSceneTimeHelpers.h.
References check, DiscreteSize(), TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::Inclusive(), TRangeBound< ElementType >::IsInclusive(), and TRangeBound< ElementType >::IsOpen().
MakeHullRange() [1/2]
TRange< FFrameNumber > UE::MovieScene::MakeHullRange (const TRange< FFrameNumber > & InRange) inline
Make a new range that includes both the lower and upper bounds of the given range.
Definition at line 103 of file MovieSceneTimeHelpers.h.
References TRange< ElementType >::GetLowerBoundValue(), TRange< ElementType >::GetUpperBoundValue(), TRange< ElementType >::HasLowerBound(), TRange< ElementType >::HasUpperBound(), TRangeBound< ElementType >::Inclusive(), and TRangeBound< ElementType >::Open().
MakeHullRange() [2/2]
TRange< FFrameNumber > UE::MovieScene::MakeHullRange (FFrameNumber MinInclusive, FFrameNumber MaxInclusive) inline
Make a new range that includes both the given minimum and maximum.
Parameters
MinInclusive The minimum value for the inclusive lower bound
MaxInclusive The maximum value for the inclusive lower bound
Returns
A new range.
Definition at line 118 of file MovieSceneTimeHelpers.h.
References TRangeBound< ElementType >::Inclusive().
MS_ALIGN()
struct UE::MovieScene::MS_ALIGN (PLATFORM_CACHE_LINE_SIZE)
Definition at line 203 of file MovieSceneDecompositionQuery.h.
References GENERATED_BODY, and MinimalAPI.
MultiChannelFromData() [1/9]
void UE::MovieScene::MultiChannelFromData (const FEulerTransform & In, TMultiChannelValue< float, 9 > & Out) inline
Definition at line 350 of file MovieSceneMultiChannelBlending.h.
References FVector, Rotation, Scale, and Translation.
MultiChannelFromData() [2/9]
void UE::MovieScene::MultiChannelFromData (const FLinearColor & In, TMultiChannelValue< float, 4 > & Out) inline
Definition at line 357 of file MovieSceneMultiChannelBlending.h.
References FLinearColor::A, FLinearColor::B, FLinearColor::G, and FLinearColor::R.
MultiChannelFromData() [3/9]
void UE::MovieScene::MultiChannelFromData (const FTransform & In, TMultiChannelValue< float, 9 > & Out) inline
Definition at line 343 of file MovieSceneMultiChannelBlending.h.
References UE::Math::TRotator< T >::Euler(), FVector, UE::Math::TTransform< T >::GetRotation(), UE::Math::TTransform< T >::GetScale3D(), UE::Math::TTransform< T >::GetTranslation(), Rotation, UE::Math::TQuat< T >::Rotator(), Scale, and Translation.
MultiChannelFromData() [4/9]
void UE::MovieScene::MultiChannelFromData (const FVector4 & In, TMultiChannelValue< float, 4 > & Out) inline
Definition at line 342 of file MovieSceneMultiChannelBlending.h.
References UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
MultiChannelFromData() [5/9]
void UE::MovieScene::MultiChannelFromData (float In, TMultiChannelValue< float, 1 > & Out) inline
Definition at line 339 of file MovieSceneMultiChannelBlending.h.
MultiChannelFromData() [6/9]
void UE::MovieScene::MultiChannelFromData (FVector In, TMultiChannelValue< float, 3 > & Out) inline
Definition at line 341 of file MovieSceneMultiChannelBlending.h.
References FVector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
MultiChannelFromData() [7/9]
void UE::MovieScene::MultiChannelFromData (FVector2D In, TMultiChannelValue< float, 2 > & Out) inline
Definition at line 340 of file MovieSceneMultiChannelBlending.h.
References UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
MultiChannelFromData() [8/9]
void UE::MovieScene::MultiChannelFromData (int32 In, TMultiChannelValue< double, 1 > & Out) inline
Definition at line 338 of file MovieSceneMultiChannelBlending.h.
MultiChannelFromData() [9/9]
template<typename T, typename SourceData, uint8 N> void UE::MovieScene::MultiChannelFromData (SourceData InSourceData, TMultiChannelValue< T, N > & OutChannelData)
Declaration of a function used to generate multi channel data from a source type.
Overload in the MovieScene namespace for type-specific functionality.
Definition at line 161 of file MovieSceneMultiChannelBlending.h.
Referenced by BlendValue(), and UE::MovieScene::TMaskedBlendable< double, 1 >::Resolve().
OnRemapChannelKeyTime() [1/3]
MOVIESCENE_API void UE::MovieScene::OnRemapChannelKeyTime (const FMovieSceneChannel * Channel, const IRetimingInterface & Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, FMovieSceneDoubleValue & InOutValue)
OnRemapChannelKeyTime() [2/3]
MOVIESCENE_API void UE::MovieScene::OnRemapChannelKeyTime (const FMovieSceneChannel * Channel, const IRetimingInterface & Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, FMovieSceneFloatValue & InOutValue)
OnRemapChannelKeyTime() [3/3]
template<typename ValueType> void UE::MovieScene::OnRemapChannelKeyTime (const FMovieSceneChannel * Channel, const IRetimingInterface & Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, ValueType & InOutValue)
Definition at line 29 of file MovieSceneChannelData.h.
Optimize()
template<typename ChannelType> void UE::MovieScene::Optimize (ChannelType * InChannel, const FKeyDataOptimizationParams & Params)
Optimize the specified channel by removing any redundant keys.
Parameters
InChannel The channel to optimize
Params Optimization parameters
Definition at line 241 of file MovieSceneChannelTraits.h.
References Algo::LowerBound(), MoveTemp(), Num, TArrayView< InElementType, InSizeType >::Num(), Params, Time, Algo::UpperBound(), and ValueExistsAtTime().
PatchComposite()
template<typename CompositeType> FORCEINLINE void UE::MovieScene::PatchComposite (uint8 * OutValueBase, const CompositeType * Composite, uint16 PtrOffset)
Definition at line 21 of file MovieScenePartialProperties.h.
References FORCEINLINE.
Referenced by PatchCompositeValueImpl().
PatchCompositeValue()
template<typename... CompositeTypes> void UE::MovieScene::PatchCompositeValue (TArrayView< const FPropertyCompositeDefinition > CompositeDefinitions, void * OutValueAddress, const CompositeTypes *... Composites)
Definition at line 39 of file MovieScenePartialProperties.h.
References PatchCompositeValueImpl().
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RebuildOperational().
PatchCompositeValueImpl()
template<typename... CompositeTypes, int ... CompositeIndices> FORCEINLINE void UE::MovieScene::PatchCompositeValueImpl (const TIntegerSequence< int, CompositeIndices... > & , TArrayView< const FPropertyCompositeDefinition > CompositeDefinitions, uint8 * OutValueBase, const CompositeTypes *... Composites)
Definition at line 30 of file MovieScenePartialProperties.h.
References FORCEINLINE, and PatchComposite().
Referenced by PatchCompositeValue().
PopulatePrerequisites() [1/5]
void UE::MovieScene::PopulatePrerequisites (const FComponentAccess * In, const FSystemTaskPrerequisites & InPrerequisites, FGraphEventArray * OutGatheredPrereqs) inline
Definition at line 467 of file MovieSceneComponentAccessors.h.
References check, UE::MovieScene::FComponentAccess::ComponentType, and UE::MovieScene::FSystemTaskPrerequisites::FilterByComponent().
PopulatePrerequisites() [2/5]
void UE::MovieScene::PopulatePrerequisites (const FEntityIDAccess * , const FSystemTaskPrerequisites & InPrerequisites, FGraphEventArray * OutGatheredPrereqs) inline
Definition at line 464 of file MovieSceneComponentAccessors.h.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::Dispatch(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), PopulatePrerequisites(), PopulatePrerequisites(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulatePrerequisites().
PopulatePrerequisites() [3/5]
void UE::MovieScene::PopulatePrerequisites (const FOptionalComponentAccess * In, const FSystemTaskPrerequisites & InPrerequisites, FGraphEventArray * OutGatheredPrereqs) inline
Definition at line 472 of file MovieSceneComponentAccessors.h.
References check, UE::MovieScene::FOptionalComponentAccess::ComponentType, and UE::MovieScene::FSystemTaskPrerequisites::FilterByComponent().
PopulatePrerequisites() [4/5]
template<typename... T> void UE::MovieScene::PopulatePrerequisites (const TReadOneOfAccessor< T... > * In, const FSystemTaskPrerequisites & InPrerequisites, FGraphEventArray * OutGatheredPrereqs)
Definition at line 481 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes, and PopulatePrerequisites().
PopulatePrerequisites() [5/5]
template<typename... T> void UE::MovieScene::PopulatePrerequisites (const TReadOneOrMoreOfAccessor< T... > * In, const FSystemTaskPrerequisites & InPrerequisites, FGraphEventArray * OutGatheredPrereqs)
Definition at line 489 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOrMoreOfAccessor< T >::ComponentTypes, and PopulatePrerequisites().
PopulateReadWriteDependencies() [1/7]
void UE::MovieScene::PopulateReadWriteDependencies (const FEntityIDAccess * , FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies) inline
Definition at line 517 of file MovieSceneComponentAccessors.h.
Referenced by PopulateReadWriteDependencies(), PopulateReadWriteDependencies(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateReadWriteDependencies(), and UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl().
PopulateReadWriteDependencies() [2/7]
void UE::MovieScene::PopulateReadWriteDependencies (const FOptionalReadAccess * In, FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies) inline
Definition at line 525 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FOptionalComponentAccess::ComponentType, and UE::MovieScene::FComponentMask::Set().
PopulateReadWriteDependencies() [3/7]
void UE::MovieScene::PopulateReadWriteDependencies (const FOptionalWriteAccess * In, FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies) inline
Definition at line 537 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FOptionalComponentAccess::ComponentType, and UE::MovieScene::FComponentMask::Set().
PopulateReadWriteDependencies() [4/7]
void UE::MovieScene::PopulateReadWriteDependencies (const FReadAccess * In, FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies) inline
Definition at line 520 of file MovieSceneComponentAccessors.h.
References checkSlow, UE::MovieScene::FComponentAccess::ComponentType, and UE::MovieScene::FComponentMask::Set().
PopulateReadWriteDependencies() [5/7]
void UE::MovieScene::PopulateReadWriteDependencies (const FWriteAccess * In, FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies) inline
Definition at line 532 of file MovieSceneComponentAccessors.h.
References checkSlow, UE::MovieScene::FComponentAccess::ComponentType, and UE::MovieScene::FComponentMask::Set().
PopulateReadWriteDependencies() [6/7]
template<typename... T> void UE::MovieScene::PopulateReadWriteDependencies (const TReadOneOfAccessor< T... > * In, FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies)
Definition at line 545 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOfAccessor< T >::ComponentTypes, and PopulateReadWriteDependencies().
PopulateReadWriteDependencies() [7/7]
template<typename... T> void UE::MovieScene::PopulateReadWriteDependencies (const TReadOneOrMoreOfAccessor< T... > * In, FComponentMask & OutReadDependencies, FComponentMask & OutWriteDependencies)
Definition at line 553 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::TReadOneOrMoreOfAccessor< T >::ComponentTypes, and PopulateReadWriteDependencies().
PopulateSubsequents() [1/3]
void UE::MovieScene::PopulateSubsequents (const FOptionalWriteAccess * In, const FGraphEventRef & InEvent, FSystemSubsequentTasks & OutSubsequents) inline
Definition at line 504 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FSystemSubsequentTasks::AddComponentTask(), and UE::MovieScene::FOptionalComponentAccess::ComponentType.
PopulateSubsequents() [2/3]
void UE::MovieScene::PopulateSubsequents (const FWriteAccess * In, const FGraphEventRef & InEvent, FSystemSubsequentTasks & OutSubsequents) inline
Definition at line 499 of file MovieSceneComponentAccessors.h.
References UE::MovieScene::FSystemSubsequentTasks::AddComponentTask(), check, and UE::MovieScene::FComponentAccess::ComponentType.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::Dispatch(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateSubsequents().
PopulateSubsequents() [3/3]
void UE::MovieScene::PopulateSubsequents (const void * In, const FGraphEventRef & InEvent, FSystemSubsequentTasks & OutSubsequents) inline
Definition at line 511 of file MovieSceneComponentAccessors.h.
RegisterCustomEntitySystemLinkerRole()
MOVIESCENE_API EEntitySystemLinkerRole UE::MovieScene::RegisterCustomEntitySystemLinkerRole ()
Register a new custom linker role.
RemoveChannelDefault() [1/2]
template<typename ChannelType> TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type UE::MovieScene::RemoveChannelDefault (ChannelType * Channel)
Removes a channel's default value.
Parameters
InChannel The channel to remove the default from.
Definition at line 203 of file MovieSceneChannelTraits.h.
RemoveChannelDefault() [2/2]
template<typename ChannelType> TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type UE::MovieScene::RemoveChannelDefault (ChannelType * Channel)
Definition at line 208 of file MovieSceneChannelTraits.h.
RemoveGlobalCustomAccessor()
MOVIESCENE_API void UE::MovieScene::RemoveGlobalCustomAccessor (const UClass * ClassType, FName PropertyPath)
Referenced by UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::Remove(), and UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::RemoveAll().
ResolveChannelsToData() [1/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< double, 1 > & In, int32 & Out) inline
Definition at line 362 of file MovieSceneMultiChannelBlending.h.
ResolveChannelsToData() [2/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 1 > & In, float & Out) inline
Definition at line 363 of file MovieSceneMultiChannelBlending.h.
ResolveChannelsToData() [3/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 2 > & In, FVector2D & Out) inline
Definition at line 364 of file MovieSceneMultiChannelBlending.h.
ResolveChannelsToData() [4/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 3 > & In, FVector & Out) inline
Definition at line 365 of file MovieSceneMultiChannelBlending.h.
References FVector.
ResolveChannelsToData() [5/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 4 > & In, FLinearColor & Out) inline
Definition at line 383 of file MovieSceneMultiChannelBlending.h.
ResolveChannelsToData() [6/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 4 > & In, FVector4 & Out) inline
Definition at line 366 of file MovieSceneMultiChannelBlending.h.
ResolveChannelsToData() [7/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 9 > & In, FEulerTransform & Out) inline
Definition at line 375 of file MovieSceneMultiChannelBlending.h.
References FVector, and UE::Math::TRotator< double >::MakeFromEuler().
ResolveChannelsToData() [8/9]
void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< float, 9 > & In, FTransform & Out) inline
Definition at line 367 of file MovieSceneMultiChannelBlending.h.
References FVector, and UE::Math::TRotator< double >::MakeFromEuler().
ResolveChannelsToData() [9/9]
template<typename T, typename SourceData, uint8 N> void UE::MovieScene::ResolveChannelsToData (const TMultiChannelValue< T, N > & OutChannelData, SourceData & OutData)
Declaration of a function used to popupate a specific type with generic channel data after blending has occurred.
Overload in the MovieScene namespace for type-specific functionality. For example, to support multi channel blending
Definition at line 171 of file MovieSceneMultiChannelBlending.h.
Referenced by UE::MovieScene::TMaskedBlendable< double, 1 >::Resolve().
SchedulePostTask() [1/2]
template<typename TaskType> FTaskID UE::MovieScene::SchedulePostTask (IEntitySystemScheduler * , const FTaskParams & , const TSharedPtr< TaskType > & , void *) static
Definition at line 135 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskID::None().
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), and UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl().
SchedulePostTask() [2/2]
template<typename TaskType, typename TaskImplType> FTaskID UE::MovieScene::SchedulePostTask (IEntitySystemScheduler * InScheduler, const FTaskParams & Params, const TSharedPtr< TaskType > & Context, TaskImplType * Unused, decltype &::PostTask * = 0) static
Definition at line 155 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::IEntitySystemScheduler::AddTask(), Function, Params, and Unused.
SchedulePreTask() [1/2]
template<typename TaskType> FTaskID UE::MovieScene::SchedulePreTask (IEntitySystemScheduler * , const FTaskParams & , const TSharedPtr< TaskType > & , void *) static
Definition at line 130 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskID::None().
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), and UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl().
SchedulePreTask() [2/2]
template<typename TaskType, typename TaskImplType> FTaskID UE::MovieScene::SchedulePreTask (IEntitySystemScheduler * InScheduler, const FTaskParams & Params, const TSharedPtr< TaskType > & Context, TaskImplType * Unused, decltype &::PreTask * = 0) static
Definition at line 141 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::IEntitySystemScheduler::AddTask(), Function, Params, and Unused.
SetChannelDefault() [1/2]
template<typename ChannelType, typename ValueType> TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type UE::MovieScene::SetChannelDefault (ChannelType * Channel, ValueType && DefaultValue)
Set a channel's default value.
Parameters
InChannel The channel to set the default on
DefaultValue The new default value
Definition at line 189 of file MovieSceneChannelTraits.h.
Referenced by TAddKeyImpl< ChannelType, ValueType >::ApplyDefault(), TAddKeyImpl< FMovieSceneBoolChannel, bool >::ApplyDefault(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::ApplyDefault(), TAddKeyImpl< FMovieSceneFloatChannel, float >::ApplyDefault(), and TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ApplyDefault().
SetChannelDefault() [2/2]
template<typename ChannelType, typename ValueType> TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type UE::MovieScene::SetChannelDefault (ChannelType * Channel, ValueType && DefaultValue)
Definition at line 194 of file MovieSceneChannelTraits.h.
SetComponentTransform()
MOVIESCENETRACKS_API void UE::MovieScene::SetComponentTransform (USceneComponent * SceneComponent, const FIntermediate3DTransform & InTransform)
SetComponentTransformAndVelocity()
MOVIESCENETRACKS_API void UE::MovieScene::SetComponentTransformAndVelocity (UObject * Object, const FIntermediate3DTransform & InTransform)
TranslateRange()
template<typename T> TRange< T > UE::MovieScene::TranslateRange (const TRange< T > & InRange, T Amount) inline
Translate the specified range by adding the specified amount to both bounds.
Definition at line 244 of file MovieSceneTimeHelpers.h.
References DilateRange().
ValueExistsAtTime()
template<typename ChannelType, typename ValueType> bool UE::MovieScene::ValueExistsAtTime (const ChannelType * InChannel, FFrameNumber InTime, const ValueType & InValue)
Check whether the specified value already exists at the specified time.
Parameters
InChannel The channel to check
InTime The time to check for
InValue The value to check - compared against the curve's existing value at this time
Returns
true if this value already exists at the time, false otherwise
Definition at line 176 of file MovieSceneChannelTraits.h.
References EvaluateChannel(), and InTime.
Referenced by Optimize().
VisitSequence()
MOVIESCENE_API void UE::MovieScene::VisitSequence (UMovieSceneSequence * Sequence, const FSequenceVisitParams & InParams, ISequenceVisitor & Visitor)
Variable Documentation
ComponentMaskDWORDSize
int32 UE::MovieScene::ComponentMaskDWORDSize = (MaximumNumComponentsSupported + 31) / 32 static constexpr
Defines the number of DWORDs that we need to store for component masks.
Definition at line 33 of file MovieSceneEntityIDs.h.
GEntityManagerForDebuggingVisualizers
MOVIESCENE_API FEntityManager* UE::MovieScene::GEntityManagerForDebuggingVisualizers extern
GPlaybackCapabilityIDRegistryForDebuggingVisualizers
MOVIESCENE_API FPlaybackCapabilityIDRegistry* UE::MovieScene::GPlaybackCapabilityIDRegistryForDebuggingVisualizers extern
MaximumNumComponentsSupported
int32 UE::MovieScene::MaximumNumComponentsSupported = 384 static constexpr
Defines the absolute maximum number of component types that can exist at any one time in an FEntityManager In general component types should be kept to a minimum, but if large numbers of blocking sequences are required (which each require their own linker and instance tags), or large numbers of components are required for whatever reason, this limit can be increased.
Component masks are stored as fixed size inline bit arrays, so considerations should be made before increasing this number.
Definition at line 30 of file MovieSceneEntityIDs.h.