Unreal Engine 5.6 C++ API: FHairStrandsLODDeformedRootResource Struct Reference
FHairStrandsLODDeformedRootResource Struct Reference
#include "GroomResources.h"
Public Types
enum EFrameType { Previous , Current }
enum class EStatus { Invalid , Initialized , Completed }
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
FHairStrandsLODDeformedRootResource (FHairStrandsRestRootResource *InRestResources, EHairStrandsResourcesType CurveType, const uint32 MeshLODIndex, const FHairResourceName &ResourceName, const FName &OwnerName)
Build the hair strands resource.
const FRDGExternalBuffer & GetDeformedSamplePositionsBuffer (EFrameType T) const
const FRDGExternalBuffer & GetDeformedUniqueTrianglePositionBuffer (EFrameType T) const
virtual FString GetFriendlyName () const override
uint32 GetIndex (EFrameType T) const
const FRDGExternalBuffer & GetMeshSampleWeightsBuffer (EFrameType T) const
uint32 GetResourcesSize () const
virtual void InternalAllocate (FRDGBuilder &GraphBuilder, uint32 InCurveCount, uint32 InPointCount) override
virtual void InternalRelease () override
bool IsDataValid () const
bool IsValid () const
void SwapBuffer ()
Public Member Functions inherited from FHairCommonResource
FHairCommonResource (EHairStrandsAllocationType AllocationType, const FHairResourceName &InResourceName, const FName &InOwnerName, bool bUseRenderGraph=true)
Build the hair strands resource.
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status, uint32 InRequestedCurveCount, uint32 InRequestedPointCount, bool bAllowDeallocation=true)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void InternalAllocate ()
virtual void InternalAllocate (FRDGBuilder &GraphBuilder)
virtual FHairStrandsBulkCommon * InternalGetBulkData ()
virtual bool InternalGetOrRequestData (uint32 InRequestedCurveCount, uint32 InRequestedPointCount)
virtual void InternalResetLoadedSize ()
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void StreamInData ()
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
uint32 AvailableCurveCount = 0
uint32 CurrentIndex = 0
const EHairStrandsResourcesType CurveType
FRDGExternalBuffer DeformedSamplePositionsBuffer [2]
FRDGExternalBuffer DeformedUniqueTrianglePositionBuffer [2]
const int32 MeshLODIndex = -1
FRDGExternalBuffer MeshSampleWeightsBuffer [2]
uint32 RootCount = 0
uint32 SampleCount = 0
EStatus Status = EStatus::Invalid
Data Fields inherited from FHairCommonResource
EHairStrandsAllocationType AllocationType = EHairStrandsAllocationType::Deferred
bool bIsInitialized = false
bool bUseRenderGraph = true
uint32 MaxAvailableCurveCount = HAIR_MAX_NUM_CURVE_PER_GROUP
FName OwnerName
FHairResourceName ResourceName
FHairStreamingRequest StreamingRequest
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Additional Inherited Members
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 548 of file GroomResources.h.
Member Enumeration Documentation
EFrameType
enum FHairStrandsLODDeformedRootResource::EFrameType
Enumerator
Previous
Current
Definition at line 600 of file GroomResources.h.
EStatus
enum class FHairStrandsLODDeformedRootResource::EStatus strong
Enumerator
Invalid
Initialized
Completed
Definition at line 579 of file GroomResources.h.
Constructor & Destructor Documentation
FHairStrandsLODDeformedRootResource()
FHairStrandsLODDeformedRootResource::FHairStrandsLODDeformedRootResource (FHairStrandsRestRootResource * InRestResources, EHairStrandsResourcesType CurveType, const uint32 MeshLODIndex, const FHairResourceName & ResourceName, const FName & OwnerName)
Build the hair strands resource.
References CurveType, MeshLODIndex, FHairCommonResource::OwnerName, and FHairCommonResource::ResourceName.
Member Function Documentation
GetDeformedSamplePositionsBuffer()
const FRDGExternalBuffer & FHairStrandsLODDeformedRootResource::GetDeformedSamplePositionsBuffer (EFrameType T) const inline
Definition at line 609 of file GroomResources.h.
References DeformedSamplePositionsBuffer, and GetIndex().
GetDeformedUniqueTrianglePositionBuffer()
const FRDGExternalBuffer & FHairStrandsLODDeformedRootResource::GetDeformedUniqueTrianglePositionBuffer (EFrameType T) const inline
Definition at line 608 of file GroomResources.h.
References DeformedUniqueTrianglePositionBuffer, and GetIndex().
GetFriendlyName()
virtual FString FHairStrandsLODDeformedRootResource::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Definition at line 559 of file GroomResources.h.
References TEXT.
GetIndex()
uint32 FHairStrandsLODDeformedRootResource::GetIndex (EFrameType T) const inline
Definition at line 607 of file GroomResources.h.
References Current, and CurrentIndex.
Referenced by GetDeformedSamplePositionsBuffer(), GetDeformedUniqueTrianglePositionBuffer(), and GetMeshSampleWeightsBuffer().
GetMeshSampleWeightsBuffer()
const FRDGExternalBuffer & FHairStrandsLODDeformedRootResource::GetMeshSampleWeightsBuffer (EFrameType T) const inline
Definition at line 610 of file GroomResources.h.
References GetIndex(), and MeshSampleWeightsBuffer.
GetResourcesSize()
uint32 FHairStrandsLODDeformedRootResource::GetResourcesSize () const inline
Definition at line 562 of file GroomResources.h.
References DeformedSamplePositionsBuffer, DeformedUniqueTrianglePositionBuffer, GetBufferTotalNumBytes(), and MeshSampleWeightsBuffer.
InternalAllocate()
virtual void FHairStrandsLODDeformedRootResource::InternalAllocate (FRDGBuilder & GraphBuilder, uint32 InCurveCount, uint32 InPointCount) override virtual
Reimplemented from FHairCommonResource.
InternalRelease()
virtual void FHairStrandsLODDeformedRootResource::InternalRelease () override virtual
Reimplemented from FHairCommonResource.
IsDataValid()
bool FHairStrandsLODDeformedRootResource::IsDataValid () const inline
Definition at line 584 of file GroomResources.h.
References MeshLODIndex, and RootCount.
IsValid()
bool FHairStrandsLODDeformedRootResource::IsValid () const inline
Definition at line 585 of file GroomResources.h.
References Completed, Initialized, and Status.
SwapBuffer()
void FHairStrandsLODDeformedRootResource::SwapBuffer () inline
Definition at line 611 of file GroomResources.h.
References CurrentIndex.
Field Documentation
AvailableCurveCount
uint32 FHairStrandsLODDeformedRootResource::AvailableCurveCount = 0
Definition at line 587 of file GroomResources.h.
CurrentIndex
uint32 FHairStrandsLODDeformedRootResource::CurrentIndex = 0
Definition at line 598 of file GroomResources.h.
Referenced by GetIndex(), and SwapBuffer().
CurveType
const EHairStrandsResourcesType FHairStrandsLODDeformedRootResource::CurveType
Definition at line 621 of file GroomResources.h.
Referenced by FHairStrandsLODDeformedRootResource().
DeformedSamplePositionsBuffer
FRDGExternalBuffer FHairStrandsLODDeformedRootResource::DeformedSamplePositionsBuffer[2]
Definition at line 594 of file GroomResources.h.
Referenced by GetDeformedSamplePositionsBuffer(), and GetResourcesSize().
DeformedUniqueTrianglePositionBuffer
FRDGExternalBuffer FHairStrandsLODDeformedRootResource::DeformedUniqueTrianglePositionBuffer[2]
Definition at line 590 of file GroomResources.h.
Referenced by GetDeformedUniqueTrianglePositionBuffer(), and GetResourcesSize().
MeshLODIndex
const int32 FHairStrandsLODDeformedRootResource::MeshLODIndex = -1
Definition at line 618 of file GroomResources.h.
Referenced by FHairStrandsLODDeformedRootResource(), and IsDataValid().
MeshSampleWeightsBuffer
FRDGExternalBuffer FHairStrandsLODDeformedRootResource::MeshSampleWeightsBuffer[2]
Definition at line 595 of file GroomResources.h.
Referenced by GetMeshSampleWeightsBuffer(), and GetResourcesSize().
RootCount
uint32 FHairStrandsLODDeformedRootResource::RootCount = 0
Definition at line 615 of file GroomResources.h.
Referenced by IsDataValid().
SampleCount
uint32 FHairStrandsLODDeformedRootResource::SampleCount = 0
Definition at line 593 of file GroomResources.h.
Status
EStatus FHairStrandsLODDeformedRootResource::Status = EStatus::Invalid
Definition at line 586 of file GroomResources.h.
Referenced by IsValid().
The documentation for this struct was generated from the following file:
GroomResources.h