Unreal Engine 5.6 C++ API: Metasound::TSender< TDataType > Class Template Reference
Metasound::TSender< TDataType > Class Template Reference
#include "MetasoundRouter.h"
Public Member Functions
TSender (const FSenderInitParams &InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel)
int64 GetPayloadID () const override
bool Push (const TDataType &InElement)
bool PushLiteral (const FLiteral &InLiteral) override
bool PushToDataChannel ()
TDataType RetrievePayload ()
bool SetDelay (float InSeconds)
Public Member Functions inherited from Metasound::ISender
ISender (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType)
virtual METASOUNDFRONTEND_API ~ISender ()
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Static Public Member Functions
static FName GetDataTypeName ()
Private Attributes
bool bMessageDataTypeError = true
uint32 NumElementsToDelayBy = 0
FSenderInitParams Params
TUniquePtr< TDataType > Payload
int64 PayloadID = 0
Audio::TCircularAudioBuffer< TDataType > SenderBuffer
Static Private Attributes
static constexpr float BufferResizeThreshold = 2.0f
Additional Inherited Members
Protected Attributes inherited from Metasound::ISender
TSharedPtr< IDataChannel, ESPMode::ThreadSafe > DataChannel
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
template<typename TDataType>
class Metasound::TSender< TDataType >
Definition at line 418 of file MetasoundRouter.h.
Constructor & Destructor Documentation
TSender()
template<typename TDataType> Metasound::TSender< TDataType >::TSender (const FSenderInitParams & InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel) inline
Definition at line 473 of file MetasoundRouter.h.
References Metasound::ISender::ISender(), Metasound::FSenderInitParams::DelayTimeInSeconds, GetDataTypeName(), Params, and SetDelay().
Member Function Documentation
GetDataTypeName()
template<typename TDataType> FName Metasound::TSender< TDataType >::GetDataTypeName () inline static
Definition at line 468 of file MetasoundRouter.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by TSender().
GetPayloadID()
template<typename TDataType> int64 Metasound::TSender< TDataType >::GetPayloadID () const inline override virtual
Implements Metasound::ISender.
Definition at line 480 of file MetasoundRouter.h.
References PayloadID.
Push()
template<typename TDataType> bool Metasound::TSender< TDataType >::Push (const TDataType & InElement) inline
Definition at line 429 of file MetasoundRouter.h.
References NumElementsToDelayBy, PushToDataChannel(), and SenderBuffer.
Referenced by PushLiteral().
PushLiteral()
template<typename TDataType> bool Metasound::TSender< TDataType >::PushLiteral (const FLiteral & InLiteral) inline override virtual
Implements Metasound::ISender.
Definition at line 443 of file MetasoundRouter.h.
References bMessageDataTypeError, Metasound::TDataLiteralFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs(), Error, Metasound::GetMetasoundDataTypeString(), Metasound::TLiteralTraits< DataType >::IsParsable(), LexToString(), Params, Push(), TEXT, and UE_LOG.
PushToDataChannel()
template<typename TDataType> bool Metasound::TSender< TDataType >::PushToDataChannel () inline
Definition at line 492 of file MetasoundRouter.h.
References Metasound::ISender::DataChannel, MakeUnique(), Payload, PayloadID, and SenderBuffer.
Referenced by Push().
RetrievePayload()
template<typename TDataType> TDataType Metasound::TSender< TDataType >::RetrievePayload () inline
Definition at line 485 of file MetasoundRouter.h.
References check, MoveTempIfPossible(), and Payload.
Referenced by Metasound::TCopyableDataChannel< TDataType >::PushOpaque().
SetDelay()
template<typename TDataType> bool Metasound::TSender< TDataType >::SetDelay (float InSeconds) inline
Definition at line 461 of file MetasoundRouter.h.
References Params, and SenderBuffer.
Referenced by TSender().
Field Documentation
bMessageDataTypeError
template<typename TDataType> bool Metasound::TSender< TDataType >::bMessageDataTypeError = true private
Definition at line 425 of file MetasoundRouter.h.
Referenced by PushLiteral().
BufferResizeThreshold
template<typename TDataType> float Metasound::TSender< TDataType >::BufferResizeThreshold = 2.0f static constexpr private
Definition at line 423 of file MetasoundRouter.h.
NumElementsToDelayBy
template<typename TDataType> uint32 Metasound::TSender< TDataType >::NumElementsToDelayBy = 0 private
Definition at line 520 of file MetasoundRouter.h.
Referenced by Push().
Params
template<typename TDataType> FSenderInitParams Metasound::TSender< TDataType >::Params private
Definition at line 517 of file MetasoundRouter.h.
Referenced by TSender(), PushLiteral(), and SetDelay().
Payload
template<typename TDataType> TUniquePtr<TDataType> Metasound::TSender< TDataType >::Payload private
Definition at line 515 of file MetasoundRouter.h.
Referenced by PushToDataChannel(), and RetrievePayload().
PayloadID
template<typename TDataType> int64 Metasound::TSender< TDataType >::PayloadID = 0 private
Definition at line 511 of file MetasoundRouter.h.
Referenced by GetPayloadID(), and PushToDataChannel().
SenderBuffer
template<typename TDataType> Audio::TCircularAudioBuffer<TDataType> Metasound::TSender< TDataType >::SenderBuffer private
Definition at line 509 of file MetasoundRouter.h.
Referenced by Push(), PushToDataChannel(), and SetDelay().
The documentation for this class was generated from the following file:
MetasoundRouter.h