Unreal Engine 5.6 C++ API: UE::Anim::TAttributeContainer< BoneIndexType, InAllocator > Struct Template Reference
UE::Anim::TAttributeContainer< BoneIndexType, InAllocator > Struct Template Reference
Runtime container for Animation Attributes, providing a TMap like interface.
#include "AttributesContainer.h"
Public Member Functions
template<typename AttributeType>
AttributeType * Add (const FAttributeId &InAttributeId, const AttributeType &Attribute)
Adds a new attribute type/value entry of the specified underlying AttributeType.
uint8 * Add (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId)
Adds a new attribute type/value entry for the specified InScriptType.
bool ContainsData () const
Returns whether or not any this container contains any entries.
void CopyFrom (const TAttributeContainer< BoneIndexType, InAllocator > &Other)
Copies all contained data from another Container instance using the same memory allocator.
template<typename OtherAllocator>
void CopyFrom (const TAttributeContainer< BoneIndexType, OtherAllocator > &Other)
Copies all contained data from another Container instance using another memory allocator.
template<class OtherBoneIndexType, typename OtherAllocator>
void CopyFrom (const TAttributeContainer< OtherBoneIndexType, OtherAllocator > &Other, const FBoneContainer &BoneContainer)
template<class OtherBoneIndexType, typename OtherAllocator>
void CopyFrom (const TAttributeContainer< OtherBoneIndexType, OtherAllocator > &Other, const TMap< OtherBoneIndexType, BoneIndexType > &IndexMapping)
void Empty ()
Cleans out all contained entries and types.
template<typename AttributeType>
AttributeType * Find (const FAttributeId &InAttributeId)
Tries to find a attribute type/value entry of the specified AttributeType.
template<typename AttributeType>
const AttributeType * Find (const FAttributeId &InAttributeId) const
Tries to find a attribute type/value entry of the specified AttributeType.
uint8 * Find (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId)
Tries to find a attribute type/value entry for the specified InScriptType.
const uint8 * Find (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId) const
Tries to find a attribute type/value entry for the specified InScriptType.
template<typename AttributeType>
AttributeType & FindChecked (const FAttributeId &InAttributeId)
Tries to find a attribute type/value entry of the specified AttributeType.
template<typename AttributeType>
const AttributeType & FindChecked (const FAttributeId &InAttributeId) const
Tries to find a attribute type/value entry of the specified AttributeType.
template<typename AttributeType>
AttributeType * FindOrAdd (const FAttributeId &InAttributeId)
Adds, if not yet existing, a new attribute type/value entry of the specified AttributeType.
uint8 * FindOrAdd (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId)
Adds, if not yet existing, a new attribute type/value entry for the specified InScriptType.
int32 FindTypeIndex (const UScriptStruct *InScriptStruct) const
template<typename ArrayAllocator>
bool GetAllKeyNames (TArray< FName, ArrayAllocator > &OutAttributeKeyNames) const
const TArray< FAttributeId > & GetKeys (int32 TypeIndex) const
const TArray< int32 > & GetUniqueTypedBoneIndices (int32 TypeIndex) const
const TArray< TWeakObjectPtr< UScriptStruct > > & GetUniqueTypes () const
const TArray< TWrappedAttribute< InAllocator > > & GetValues (int32 TypeIndex) const
template<typename AttributeType>
int32 IndexOfByKey (const FAttributeId &InAttributeId) const
Tries to find and return the indedx of a attribute type/value entry of the specified AttributeType.
int32 IndexOfByKey (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId) const
Tries to find and return the indedx of a attribute type/value entry of the specified AttributeType.
void MoveFrom (TAttributeContainer< BoneIndexType, InAllocator > &Other)
Moves all contained data from another Container instance, once moved the other Container instance data is invalid.
int32 Num () const
bool operator!= (const TAttributeContainer< BoneIndexType, InAllocator > &Other)
template<typename AttributeType>
bool Remove (const FAttributeId &InAttributeId)
Removes, if existing, an attribute type/value entry of the specified AttributeType.
bool Remove (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId)
Removes, if existing, an attribute type/value entry for the specified InScriptType.
template<typename AttributeType>
bool RemoveAll ()
Removes all, if existing, an attribute type/value entries of the specified AttributeType.
bool RemoveAll (const UScriptStruct *InScriptStruct, const FAttributeId &InAttributeId)
Removes all, if existing, an attribute type/value entries for the specified InScriptType.
Protected Member Functions
int32 FindOrAddTypeIndex (const UScriptStruct *InScriptStruct)
Find or add a new root-level entry for the provided attribute data type, returning the index into the arrays representing the type.
TArray< FAttributeId > & GetKeysInternal (int32 TypeIndex)
TArray< TWrappedAttribute< InAllocator > > & GetValuesInternal (int32 TypeIndex)
Protected Attributes
TArray< TArray< FAttributeId > > AttributeIdentifiers
TArray< TArray< int32 > > UniqueTypedBoneIndices
Unique bone indices for all contained entries of a specific attribute type.
TArray< TWeakObjectPtr< UScriptStruct > > UniqueTypes
TArray< TArray< TWrappedAttribute< InAllocator > > > Values
Friends
template<typename OtherBoneIndexType, typename OtherAllocator>
struct TAttributeContainer
template<class OtherBoneIndexType, typename OtherAllocator>
struct TAttributeContainerAccessor
Detailed Description
template<class BoneIndexType, typename InAllocator>
struct UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >
Runtime container for Animation Attributes, providing a TMap like interface.
Used in FStack
Definition at line 70 of file AttributesContainer.h.
Member Function Documentation
Add() [1/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> AttributeType * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Add (const FAttributeId & InAttributeId, const AttributeType & Attribute) inline
Adds a new attribute type/value entry of the specified underlying AttributeType.
Parameters
InAttributeId Key to be used for the entry
Attribute Value for the new entry
Returns
The ptr to the added and populated entry, to be used for populating the data, nullptr if adding it failed
Definition at line 309 of file AttributesContainer.h.
References Add, and Attribute.
Referenced by UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal().
Add() [2/2]
template<class BoneIndexType, typename InAllocator> uint8 * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Add (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) inline
Adds a new attribute type/value entry for the specified InScriptType.
Parameters
InScriptStruct UScriptStruct (type) for the entry
InAttributeId Key to be used for the entry
Returns
The ptr to the added entry, to be used for populating the data, nullptr if adding it failed
Definition at line 328 of file AttributesContainer.h.
References TArray< InElementType, InAllocatorType >::Add(), AttributeIdentifiers, ensure, FindOrAddTypeIndex(), UE::Anim::FAttributeId::GetIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), UScriptStruct::InitializeStruct(), TArray< InElementType, InAllocatorType >::Num(), UniqueTypedBoneIndices, and Values.
ContainsData()
template<class BoneIndexType, typename InAllocator> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::ContainsData () const inline
Returns whether or not any this container contains any entries.
Definition at line 226 of file AttributesContainer.h.
References Values.
CopyFrom() [1/4]
template<class BoneIndexType, typename InAllocator> void UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom (const TAttributeContainer< BoneIndexType, InAllocator > & Other) inline
Copies all contained data from another Container instance using the same memory allocator.
Ensure a copy to self is never performed
Definition at line 190 of file AttributesContainer.h.
References TAttributeContainer, TArray< InElementType, InAllocatorType >::Add_GetRef(), Array, AttributeIdentifiers, TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), Other, UniqueTypedBoneIndices, UniqueTypes, and Values.
CopyFrom() [2/4]
template<class BoneIndexType, typename InAllocator> template<typename OtherAllocator> void UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom (const TAttributeContainer< BoneIndexType, OtherAllocator > & Other) inline
Copies all contained data from another Container instance using another memory allocator.
Definition at line 74 of file AttributesContainer.h.
References TAttributeContainer, TArray< InElementType, InAllocatorType >::Add_GetRef(), Array, AttributeIdentifiers, TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), Other, UniqueTypedBoneIndices, UniqueTypes, and Values.
CopyFrom() [3/4]
template<class BoneIndexType, typename InAllocator> template<class OtherBoneIndexType, typename OtherAllocator> void UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom (const TAttributeContainer< OtherBoneIndexType, OtherAllocator > & Other, const FBoneContainer & BoneContainer) inline
Definition at line 137 of file AttributesContainer.h.
References TAttributeContainer, TArray< InElementType, InAllocatorType >::Add(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), TArray< InElementType, InAllocatorType >::Add_GetRef(), TArray< InElementType, InAllocatorType >::AddUnique(), AttributeIdentifiers, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), UE::Anim::FAttributeId::GetIndex(), UE::Anim::FAttributeId::GetName(), UE::Anim::FAttributeId::GetNamespace(), UE::Anim::Conversion::MakeIndex(), TArray< InElementType, InAllocatorType >::Num(), Other, UniqueTypedBoneIndices, UniqueTypes, Value, and Values.
CopyFrom() [4/4]
template<class BoneIndexType, typename InAllocator> template<class OtherBoneIndexType, typename OtherAllocator> void UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom (const TAttributeContainer< OtherBoneIndexType, OtherAllocator > & Other, const TMap< OtherBoneIndexType, BoneIndexType > & IndexMapping) inline
Definition at line 97 of file AttributesContainer.h.
References TAttributeContainer, TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Add_GetRef(), TArray< InElementType, InAllocatorType >::AddUnique(), AttributeIdentifiers, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), UE::Anim::FAttributeId::GetIndex(), UE::Anim::FAttributeId::GetName(), UE::Anim::FAttributeId::GetNamespace(), TArray< InElementType, InAllocatorType >::Num(), Other, UniqueTypedBoneIndices, UniqueTypes, Value, and Values.
Empty()
template<class BoneIndexType, typename InAllocator> void UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Empty () inline
Cleans out all contained entries and types.
Definition at line 232 of file AttributesContainer.h.
References AttributeIdentifiers, UniqueTypedBoneIndices, UniqueTypes, and Values.
Find() [1/4]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> AttributeType * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find (const FAttributeId & InAttributeId) inline
Tries to find a attribute type/value entry of the specified AttributeType.
Parameters
InAttributeId Key to be used for seraching the entry
Returns
The ptr to the entry, to be used for modifying the data, nullptr if it was not found
Definition at line 421 of file AttributesContainer.h.
References Find.
Find() [2/4]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> const AttributeType * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find (const FAttributeId & InAttributeId) const inline
Tries to find a attribute type/value entry of the specified AttributeType.
Parameters
InAttributeId Key to be used for seraching the entry
Returns
The ptr to the constant entry, nullptr if it was not found
Definition at line 464 of file AttributesContainer.h.
References Find.
Find() [3/4]
template<class BoneIndexType, typename InAllocator> uint8 * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) inline
Tries to find a attribute type/value entry for the specified InScriptType.
Parameters
InScriptStruct UScriptStruct (type) for the entry
InAttributeId Key to be used for seraching the entry
Returns
The ptr to the entry, to be used for modifying the data, nullptr if it was not found
Definition at line 434 of file AttributesContainer.h.
References AttributeIdentifiers, ensure, FindTypeIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), TArray< InElementType, InAllocatorType >::IsValidIndex(), and Values.
Find() [4/4]
template<class BoneIndexType, typename InAllocator> const uint8 * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Find (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) const inline
Tries to find a attribute type/value entry for the specified InScriptType.
Parameters
InScriptStruct UScriptStruct (type) for the entry
InAttributeId Key to be used for seraching the entry
Returns
The ptr to the constant entry, nullptr if it was not found
Definition at line 477 of file AttributesContainer.h.
References AttributeIdentifiers, ensure, FindTypeIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), TArray< InElementType, InAllocatorType >::IsValidIndex(), and Values.
FindChecked() [1/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> AttributeType & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindChecked (const FAttributeId & InAttributeId) inline
Tries to find a attribute type/value entry of the specified AttributeType.
Asserts when the attribute was not found.
Parameters
InAttributeId Key to be used for seraching the entry
Returns
Reference to the entry
Definition at line 508 of file AttributesContainer.h.
References AttributeIdentifiers, checkf, ensure, FindTypeIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), TArray< InElementType, InAllocatorType >::IsValidIndex(), TEXT, and Values.
FindChecked() [2/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> const AttributeType & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindChecked (const FAttributeId & InAttributeId) const inline
Tries to find a attribute type/value entry of the specified AttributeType.
Asserts when the attribute was not found.
Parameters
InAttributeId Key to be used for seraching the entry
Returns
Reference to the entry
Definition at line 544 of file AttributesContainer.h.
References AttributeIdentifiers, checkf, ensure, FindTypeIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), TArray< InElementType, InAllocatorType >::IsValidIndex(), TEXT, and Values.
FindOrAdd() [1/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> AttributeType * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd (const FAttributeId & InAttributeId) inline
Adds, if not yet existing, a new attribute type/value entry of the specified AttributeType.
Parameters
InAttributeId Key to be used for the entry
Returns
The ptr to the added/existing entry, to be used for populating the data, nullptr if adding it failed
Definition at line 367 of file AttributesContainer.h.
References FindOrAdd().
Referenced by UE::Anim::TAttributeBlendOperator< AttributeType >::Accumulate_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::Blend_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::ConvertToAdditive_Internal(), FindOrAdd(), and UE::Anim::TAttributeBlendOperator< AttributeType >::Override_Internal().
FindOrAdd() [2/2]
template<class BoneIndexType, typename InAllocator> uint8 * UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAdd (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) inline
Adds, if not yet existing, a new attribute type/value entry for the specified InScriptType.
Parameters
InScriptStruct UScriptStruct (type) for the entry
InAttributeId Key to be used for the entry
Returns
The ptr to the added/existing entry, to be used for populating the data, nullptr if adding it failed
Definition at line 380 of file AttributesContainer.h.
References TArray< InElementType, InAllocatorType >::Add(), AttributeIdentifiers, ensure, FindOrAddTypeIndex(), UE::Anim::FAttributeId::GetIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), UScriptStruct::InitializeStruct(), TArray< InElementType, InAllocatorType >::IsValidIndex(), TArray< InElementType, InAllocatorType >::Num(), UniqueTypedBoneIndices, and Values.
FindOrAddTypeIndex()
template<class BoneIndexType, typename InAllocator> int32 UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindOrAddTypeIndex (const UScriptStruct * InScriptStruct) inline protected
Find or add a new root-level entry for the provided attribute data type, returning the index into the arrays representing the type.
Definition at line 799 of file AttributesContainer.h.
References AttributeIdentifiers, ensure, UniqueTypedBoneIndices, UniqueTypes, and Values.
Referenced by Add(), and FindOrAdd().
FindTypeIndex()
template<class BoneIndexType, typename InAllocator> int32 UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::FindTypeIndex (const UScriptStruct * InScriptStruct) const inline
Definition at line 723 of file AttributesContainer.h.
References UniqueTypes.
Referenced by Find(), Find(), FindChecked(), FindChecked(), IndexOfByKey(), IndexOfByKey(), Remove(), and RemoveAll().
GetAllKeyNames()
template<class BoneIndexType, typename InAllocator> template<typename ArrayAllocator> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetAllKeyNames (TArray< FName, ArrayAllocator > & OutAttributeKeyNames) const inline
Definition at line 749 of file AttributesContainer.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), and AttributeIdentifiers.
GetKeys()
template<class BoneIndexType, typename InAllocator> const TArray< FAttributeId > & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetKeys (int32 TypeIndex) const inline
Definition at line 731 of file AttributesContainer.h.
References AttributeIdentifiers.
Referenced by SAnimAttributeView::DisplayNewAttributeContainerSnapshots().
GetKeysInternal()
template<class BoneIndexType, typename InAllocator> TArray< FAttributeId > & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetKeysInternal (int32 TypeIndex) inline protected
Definition at line 796 of file AttributesContainer.h.
References AttributeIdentifiers.
GetUniqueTypedBoneIndices()
template<class BoneIndexType, typename InAllocator> const TArray< int32 > & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetUniqueTypedBoneIndices (int32 TypeIndex) const inline
Definition at line 770 of file AttributesContainer.h.
References UniqueTypedBoneIndices.
GetUniqueTypes()
template<class BoneIndexType, typename InAllocator> const TArray< TWeakObjectPtr< UScriptStruct > > & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetUniqueTypes () const inline
Definition at line 741 of file AttributesContainer.h.
References UniqueTypes.
Referenced by SAnimAttributeView::DisplayNewAttributeContainerSnapshots().
GetValues()
template<class BoneIndexType, typename InAllocator> const TArray< TWrappedAttribute< InAllocator > > & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetValues (int32 TypeIndex) const inline
Definition at line 736 of file AttributesContainer.h.
References Values.
GetValuesInternal()
template<class BoneIndexType, typename InAllocator> TArray< TWrappedAttribute< InAllocator > > & UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::GetValuesInternal (int32 TypeIndex) inline protected
Definition at line 791 of file AttributesContainer.h.
References Values.
IndexOfByKey() [1/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> int32 UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey (const FAttributeId & InAttributeId) const inline
Tries to find and return the indedx of a attribute type/value entry of the specified AttributeType.
Parameters
InAttributeId Key to be used for seraching the entry
Returns
Index to the entry, INDEX_NONE if not found
Definition at line 575 of file AttributesContainer.h.
References AttributeIdentifiers, TArray< InElementType, InAllocatorType >::Contains(), FindTypeIndex(), UE::Anim::FAttributeId::GetIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), and UniqueTypedBoneIndices.
Referenced by UE::Anim::TAttributeBlendOperator< AttributeType >::Accumulate_Internal(), UE::Anim::TAttributeBlendOperator< AttributeType >::BlendPerBone_Internal(), and UE::Anim::TAttributeBlendOperator< AttributeType >::ConvertToAdditive_Internal().
IndexOfByKey() [2/2]
template<class BoneIndexType, typename InAllocator> int32 UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::IndexOfByKey (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) const inline
Tries to find and return the indedx of a attribute type/value entry of the specified AttributeType.
Parameters
InAttributeId Key to be used for seraching the entry
Returns
Index to the entry, INDEX_NONE if not found
Definition at line 602 of file AttributesContainer.h.
References AttributeIdentifiers, TArray< InElementType, InAllocatorType >::Contains(), FindTypeIndex(), UE::Anim::FAttributeId::GetIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), and UniqueTypedBoneIndices.
MoveFrom()
template<class BoneIndexType, typename InAllocator> void UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::MoveFrom (TAttributeContainer< BoneIndexType, InAllocator > & Other) inline
Moves all contained data from another Container instance, once moved the other Container instance data is invalid.
Definition at line 217 of file AttributesContainer.h.
References TAttributeContainer, AttributeIdentifiers, MoveTemp(), Other, UniqueTypedBoneIndices, UniqueTypes, and Values.
Num()
template<class BoneIndexType, typename InAllocator> int32 UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Num () const inline
Definition at line 775 of file AttributesContainer.h.
References AttributeIdentifiers.
Referenced by SAnimAttributeView::DisplayNewAttributeContainerSnapshots(), and operator!=().
operator!=()
template<class BoneIndexType, typename InAllocator> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::operator!= (const TAttributeContainer< BoneIndexType, InAllocator > & Other) inline
Number of types should match
Other should contain ThisType
Number of entries for type should match
Other should contain ThisAttributeId
Other value should match ThisAttributeValue
Definition at line 240 of file AttributesContainer.h.
References TAttributeContainer, AttributeIdentifiers, TWeakObjectPtr< T, TWeakObjectPtrBase >::Get(), INDEX_NONE, Num(), Other, UniqueTypes, and Values.
Remove() [1/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Remove (const FAttributeId & InAttributeId) inline
Removes, if existing, an attribute type/value entry of the specified AttributeType.
Parameters
InAttributeId Key of the entry to be removed
Returns
Whether or not the removal was succesful
Definition at line 630 of file AttributesContainer.h.
References Remove.
Remove() [2/2]
template<class BoneIndexType, typename InAllocator> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Remove (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) inline
Removes, if existing, an attribute type/value entry for the specified InScriptType.
Parameters
InAttributeId Key of the entry to be removed
Returns
Whether or not the removal was succesful
Definition at line 642 of file AttributesContainer.h.
References AttributeIdentifiers, check, FindTypeIndex(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IndexOfByKey(), TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::RemoveAtSwap(), UniqueTypedBoneIndices, UniqueTypes, and Values.
RemoveAll() [1/2]
template<class BoneIndexType, typename InAllocator> template<typename AttributeType> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::RemoveAll () inline
Removes all, if existing, an attribute type/value entries of the specified AttributeType.
Returns
Whether or not the removal was succesful
Definition at line 689 of file AttributesContainer.h.
References RemoveAll().
Referenced by RemoveAll().
RemoveAll() [2/2]
template<class BoneIndexType, typename InAllocator> bool UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::RemoveAll (const UScriptStruct * InScriptStruct, const FAttributeId & InAttributeId) inline
Removes all, if existing, an attribute type/value entries for the specified InScriptType.
Returns
Whether or not the removal was succesful
Definition at line 699 of file AttributesContainer.h.
References AttributeIdentifiers, ensure, FindTypeIndex(), INDEX_NONE, UniqueTypedBoneIndices, UniqueTypes, and Values.
Friends And Related Symbol Documentation
TAttributeContainer
template<class BoneIndexType, typename InAllocator> template<typename OtherBoneIndexType, typename OtherAllocator> friend struct TAttributeContainer friend
Definition at line 826 of file AttributesContainer.h.
References TAttributeContainer.
Referenced by TAttributeContainer, CopyFrom(), CopyFrom(), CopyFrom(), CopyFrom(), MoveFrom(), and operator!=().
TAttributeContainerAccessor
template<class BoneIndexType, typename InAllocator> template<class OtherBoneIndexType, typename OtherAllocator> friend struct TAttributeContainerAccessor friend
Definition at line 829 of file AttributesContainer.h.
References TAttributeContainerAccessor.
Referenced by TAttributeContainerAccessor.
Field Documentation
AttributeIdentifiers
template<class BoneIndexType, typename InAllocator> TArray<TArray<FAttributeId> > UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::AttributeIdentifiers protected
Definition at line 821 of file AttributesContainer.h.
Referenced by Add(), CopyFrom(), CopyFrom(), CopyFrom(), CopyFrom(), Empty(), Find(), Find(), FindChecked(), FindChecked(), FindOrAdd(), FindOrAddTypeIndex(), GetAllKeyNames(), GetKeys(), GetKeysInternal(), IndexOfByKey(), IndexOfByKey(), MoveFrom(), Num(), operator!=(), Remove(), and RemoveAll().
UniqueTypedBoneIndices
template<class BoneIndexType, typename InAllocator> TArray<TArray<int32> > UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::UniqueTypedBoneIndices protected
Unique bone indices for all contained entries of a specific attribute type.
Definition at line 820 of file AttributesContainer.h.
Referenced by Add(), CopyFrom(), CopyFrom(), CopyFrom(), CopyFrom(), Empty(), FindOrAdd(), FindOrAddTypeIndex(), GetUniqueTypedBoneIndices(), IndexOfByKey(), IndexOfByKey(), MoveFrom(), Remove(), and RemoveAll().
UniqueTypes
template<class BoneIndexType, typename InAllocator> TArray<TWeakObjectPtr<UScriptStruct> > UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::UniqueTypes protected
Definition at line 823 of file AttributesContainer.h.
Referenced by CopyFrom(), CopyFrom(), CopyFrom(), CopyFrom(), Empty(), FindOrAddTypeIndex(), FindTypeIndex(), GetUniqueTypes(), MoveFrom(), operator!=(), Remove(), and RemoveAll().
Values
template<class BoneIndexType, typename InAllocator> TArray<TArray<TWrappedAttribute<InAllocator> > > UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::Values protected
Definition at line 822 of file AttributesContainer.h.
Referenced by Add(), ContainsData(), CopyFrom(), CopyFrom(), CopyFrom(), CopyFrom(), Empty(), Find(), Find(), FindChecked(), FindChecked(), FindOrAdd(), FindOrAddTypeIndex(), GetValues(), GetValuesInternal(), MoveFrom(), operator!=(), Remove(), and RemoveAll().
The documentation for this struct was generated from the following file:
AttributesContainer.h