Unreal Engine 5.6 C++ API: FWindowsPlatformProcess Struct Reference
FWindowsPlatformProcess Struct Reference
Windows implementation of the process handle.
#include "WindowsPlatformProcess.h"
Data Structures
class FProcEnumerator
Process enumerator.
struct FProcEnumInfo
Process enumeration info structure.
struct FWindowsSemaphore
Windows representation of a interprocess semaphore.
Public Member Functions
UE_DEPRECATED (5.0, "Please use GetSynchEventFromPool to create a new event, and ReturnSynchEventToPool to release the event.") static 1 class FEvent *CreateSynchEvent(bool bIsManualReset
Public Member Functions inherited from FGenericPlatformProcess
UE_DEPRECATED (5.0, "Please use GetSynchEventFromPool to create a new event, and ReturnSynchEventToPool to release the event.") static 1 class FEvent *CreateSynchEvent(bool bIsManualReset
Creates a new event.
Static Public Member Functions
static void AddDllDirectory (const TCHAR *Directory)
static const TCHAR * ApplicationSettingsDir ()
static const TCHAR * BaseDir ()
static bool CanLaunchURL (const TCHAR *URL)
static void CeaseBeingFirstInstance ()
Releases locks that we held for IsFirstInstance check.
static void ClosePipe (void *ReadPipe, void *WritePipe)
static void CloseProc (FProcHandle &ProcessHandle)
static const TCHAR * ComputerName ()
static FProcHandle CreateElevatedProcess (const TCHAR *URL, const TCHAR *Params)
static bool CreatePipe (void *&ReadPipe, void *&WritePipe, bool bWritePipeLocal=false)
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild, void *PipeStdErrChild)
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild=nullptr)
static class FRunnableThread * CreateRunnableThread ()
static bool Daemonize ()
static bool DeleteInterprocessSynchObject (FSemaphore *Object)
static bool ExecElevatedProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode)
static bool ExecProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode, FString *OutStdOut, FString *OutStdErr, const TCHAR *OptionalWorkingDirectory=NULL, bool bShouldEndWithParentProcess=false)
static const TCHAR * ExecutableName (bool bRemoveExtension=true)
static const TCHAR * ExecutablePath ()
static void ExploreFolder (const TCHAR *FilePath)
static void FreeDllHandle (void *DllHandle)
static FString GenerateApplicationPath (const FString &AppName, EBuildConfiguration BuildConfiguration)
static bool GetApplicationMemoryUsage (uint32 ProcessId, SIZE_T *OutMemoryUsage)
static FString GetApplicationName (uint32 ProcessId)
static FString GetApplicationSettingsDir (const ApplicationSettingsContext &Settings)
static const TCHAR * GetArchitectureSuffix ()
static const TCHAR * GetBinariesSubdirectory ()
static uint32 GetCurrentCoreNumber ()
static uint32 GetCurrentProcessId ()
static FString GetCurrentWorkingDirectory ()
static void GetDllDirectories (TArray< FString > &OutDllDirectories)
static void * GetDllExport (void *DllHandle, const TCHAR *ProcName)
static void * GetDllHandle (const TCHAR *Filename)
static const TCHAR * GetModuleExtension ()
static const FString GetModulesDirectory ()
static bool GetPerFrameProcessorUsage (uint32 ProcessId, float &ProcessUsageFraction, float &IdleUsageFraction)
static bool GetProcReturnCode (FProcHandle &ProcHandle, int32 *ReturnCode)
static bool IsApplicationRunning (const TCHAR *ProcName)
static bool IsApplicationRunning (uint32 ProcessId)
static bool IsFirstInstance ()
static bool IsProcessAffinitySet ()
static bool IsProcRunning (FProcHandle &ProcessHandle)
static bool LaunchFileInDefaultExternalApplication (const TCHAR *FileName, const TCHAR *Parms=NULL, ELaunchVerb::Type Verb=ELaunchVerb::Open, bool bPromptToOpenOnFailure=true)
static void LaunchURL (const TCHAR *URL, const TCHAR *Parms, FString *Error)
static FSemaphore * NewInterprocessSynchObject (const FString &Name, bool bCreate, uint32 MaxLocks=1)
static FSemaphore * NewInterprocessSynchObject (const TCHAR *Name, bool bCreate, uint32 MaxLocks=1)
static FProcHandle OpenProcess (uint32 ProcessID)
static void PopDllDirectory (const TCHAR *Directory)
static void PushDllDirectory (const TCHAR *Directory)
static FString ReadPipe (void *ReadPipe)
static bool ReadPipeToArray (void *ReadPipe, TArray< uint8 > &Output)
static bool ResolveNetworkPath (FString InUNCPath, FString &OutPath)
static void SetCurrentWorkingDirectoryToBaseDir ()
static bool SetProcessAffinity (uint32 NumCoresForAffinity, bool bPhysicalCoresOnly)
static bool SetProcPriority (FProcHandle &InProcHandle, int32 PriorityModifier)
static void SetThreadAffinityMask (uint64 AffinityMask)
static void SetThreadName (const TCHAR *ThreadName)
static void SetThreadPriority (EThreadPriority NewPriority)
static void SetupAudioThread ()
static void SetupGameThread ()
static const FString ShaderWorkingDir ()
static bool ShouldExpectLowIntegrityLevel ()
Whether to expect to run at a low process integrity level or not.
static void Sleep (float Seconds)
static void SleepInfinite ()
static void SleepNoStats (float Seconds)
static void TeardownAudioThread ()
static void TerminateProc (FProcHandle &ProcessHandle, bool KillTree=false)
static void TerminateProcTreeWithPredicate (FProcHandle &ProcessHandle, TFunctionRef< bool(uint32 ProcessId, const TCHAR *ApplicationName)> Predicate)
static bool TryGetMemoryUsage (FProcHandle &ProcessHandle, FPlatformProcessMemoryStats &OutStats)
static const TCHAR * UserDir ()
static const TCHAR * UserHomeDir ()
static const TCHAR * UserName (bool bOnlyAlphaNumeric=true)
static const TCHAR * UserSettingsDir ()
static const TCHAR * UserSettingsDirMediumIntegrity ()
static const TCHAR * UserTempDir ()
static void WaitForProc (FProcHandle &ProcessHandle)
static const TCHAR * WindowsSystemDir ()
static bool WritePipe (void *WritePipe, const FString &Message, FString *OutWritten=nullptr)
static bool WritePipe (void *WritePipe, const uint8 *Data, const int32 DataLength, int32 *OutDataLength=nullptr)
static void YieldThread ()
Static Public Member Functions inherited from FGenericPlatformProcess
static FORCEINLINE void AddDllDirectory (const TCHAR *Directory)
Adds a directory to search in when resolving implicitly loaded or filename-only DLLs.
static const TCHAR * ApplicationSettingsDir ()
Get application settings directory.
static const TCHAR * BaseDir ()
Get startup directory.
static bool CanLaunchURL (const TCHAR *URL)
Checks if the platform can launch a uniform resource locator (i.e.
static void CleanShaderWorkingDir ()
Clean the shader working directory.
static void ClosePipe (void *ReadPipe, void *WritePipe)
Closes an anonymous pipe.
static void CloseProc (FProcHandle &ProcessHandle)
Cleans up FProcHandle after we're done with it.
static const TCHAR * ComputerName ()
Get computer name.
static void ConditionalSleep (TFunctionRef< bool()> Condition, float SleepTime=0.0f)
Sleep thread until condition is satisfied.
static bool CreatePipe (void *&ReadPipe, void *&WritePipe, bool bWritePipeLocal=false)
Creates a writable anonymous pipe.
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild, void *PipeStdErrChild)
Creates a new process and its primary thread, with separate std pipes.
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild=nullptr)
Creates a new process and its primary thread.
static class FRunnableThread * CreateRunnableThread ()
Creates the platform-specific runnable thread.
static bool Daemonize ()
Makes process run as a system service (daemon), i.e.
static bool DeleteInterprocessSynchObject (FSemaphore *Object)
Deletes an interprocess synchronization object.
static void DumpThreadInfo (const TCHAR *MarkerName)
Output information about the currently active thread.
static bool ExecElevatedProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode)
Executes a process as administrator, requesting elevation as necessary.
static bool ExecProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode, FString *OutStdOut, FString *OutStdErr, const TCHAR *OptionalWorkingDirectory=NULL, bool bShouldEndWithParentProcess=false)
Executes a process, returning the return code, stdout, and stderr.
static const TCHAR * ExecutableName (bool bRemoveExtension=true)
Return the name of the currently running executable.
static const TCHAR * ExecutablePath ()
Return the path to the currently running executable.
static void ExploreFolder (const TCHAR *FilePath)
Attempt to "explore" the folder specified by the provided file path.
static void FlushPoolSyncEvents ()
Deletes all the recycled sync events contained by the pools.
static void FreeDllHandle (void *DllHandle)
Free a DLL.
static FString GenerateApplicationPath (const FString &AppName, EBuildConfiguration BuildConfiguration)
Generates the path to the specified application or game.
static bool GetApplicationMemoryUsage (uint32 ProcessId, SIZE_T *OutMemoryUsage)
Outputs the virtual memory usage, of the process with the specified PID.
static FString GetApplicationName (uint32 ProcessId)
Returns the Name of process given by the PID.
static FString GetApplicationSettingsDir (const ApplicationSettingsContext &Settings)
Get application settings directory for a given context.
static const TCHAR * GetArchitectureSuffix ()
Get the architecture suffix, if any.
static const TCHAR * GetBinariesSubdirectory ()
Used only by platforms with DLLs, this gives the subdirectory from binaries to find the executables.
static uint32 GetCurrentCoreNumber ()
Retrieves the current hardware CPU core.
static uint32 GetCurrentProcessId ()
Retrieves the ProcessId of this process.
static FString GetCurrentWorkingDirectory ()
Get the current working directory (only really makes sense on desktop platforms)
static ENamedThreads::Type GetDesiredThreadForUObjectReferenceCollector ()
specifies the thread to use for UObject reference collection
static FORCEINLINE void GetDllDirectories (TArray< FString > &OutDllDirectories)
Get the list of registered directories to search in when resolving implicitly loaded or filename-only DLLs.
static void * GetDllExport (void *DllHandle, const TCHAR *ProcName)
Lookup the address of a DLL function.
static void * GetDllHandle (const TCHAR *Filename)
Load a DLL.
static FString GetGameBundleId ()
Retrieves the platform-specific bundle identifier or package name of the game.
static const TCHAR * GetModuleExtension ()
Return the extension of dynamic library.
static const TCHAR * GetModulePrefix ()
Return the prefix of dynamic library (e.g.
static const FString GetModulesDirectory ()
Used only by platforms with DLLs, this gives the full path to the main directory containing modules.
static bool GetPerFrameProcessorUsage (uint32 ProcessId, float &ProcessUsageFraction, float &IdleUsageFraction)
Retrieves the current CPU Utilization for the current process in terms of percentage of all capacity.
static bool GetProcReturnCode (FProcHandle &ProcHandle, int32 *ReturnCode)
Retrieves the termination status of the specified process.
static uint32 GetStackSize ()
Get the active stack size for the currently running thread.
static class FEvent * GetSynchEventFromPool (bool bIsManualReset=false)
Gets an event from the pool or creates a new one if necessary.
static bool IsApplicationRunning (const TCHAR *ProcName)
Returns true if the specified application is running.
static bool IsApplicationRunning (uint32 ProcessId)
Returns true if the specified application is running.
static bool IsFirstInstance ()
Checks if we're the first instance.
static bool IsProcRunning (FProcHandle &ProcessHandle)
Returns true if the specified process is running.
static bool LaunchFileInDefaultExternalApplication (const TCHAR *FileName, const TCHAR *Parms=NULL, ELaunchVerb::Type Verb=ELaunchVerb::Open, bool bPromptToOpenOnFailure=true)
Attempt to launch the provided file name in its default external application.
static void LaunchURL (const TCHAR *URL, const TCHAR *Parms, FString *Error)
Launch a uniform resource locator (i.e.
static bool LaunchURLFiltered (const TCHAR *URL, const TCHAR *Parms, FString *Error, const UE::Core::FURLRequestFilter &Filter)
Launch a uniform resource locator (i.e.
static void ModifyThreadAssignmentForUObjectReferenceCollector (int32 &NumThreads, int32 &NumBackgroundThreads, ENamedThreads::Type &NormalThreadName, ENamedThreads::Type &BackgroundThreadName)
allows a platform to override the threading configuration for reference collection
static bool ModuleExists (const FString &Filename)
Used only by platforms with DLLs, this confirms the existence of a given module.
static FSemaphore * NewInterprocessSynchObject (const FString &Name, bool bCreate, uint32 MaxLocks=1)
Creates or opens an interprocess synchronization object.
static FSemaphore * NewInterprocessSynchObject (const TCHAR *Name, bool bCreate, uint32 MaxLocks=1)
Creates or opens an interprocess synchronization object.
static FProcHandle OpenProcess (uint32 ProcessID)
Opens an existing process.
static FORCEINLINE void PopDllDirectory (const TCHAR *Directory)
Unsets a directory to look for DLL files.
static FORCEINLINE void PushDllDirectory (const TCHAR *Directory)
Set a directory to look for DLL files.
static FString ReadPipe (void *ReadPipe)
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
static bool ReadPipeToArray (void *ReadPipe, TArray< uint8 > &Output)
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
static void ReturnSynchEventToPool (FEvent *Event)
Returns an event to the pool.
static void SetCurrentWorkingDirectoryToBaseDir ()
static bool SetProcessLimits (EProcessResource::Type Resource, uint64 Limit)
Sets the process limits.
static void SetShaderDir (const TCHAR *Where)
static void SetThreadAffinityMask (uint64 AffinityMask)
Change the thread processor affinity.
static void SetThreadName (const TCHAR *ThreadName)
Helper function to set thread name of the current thread.
static void SetThreadPriority (EThreadPriority NewPriority)
Change the thread processor priority.
static void SetupAudioThread ()
Allow the platform to do anything it needs for audio thread.
static void SetupGameThread ()
Allow the platform to do anything it needs for game thread.
static void SetupRenderThread ()
Allow the platform to do anything it needs for render thread.
static const TCHAR * ShaderDir ()
static const FString ShaderWorkingDir ()
Get the shader working directory.
static bool ShouldSaveToUserDir ()
Content saved to the game or engine directories should be rerouted to user directories instead.
static bool SkipWaitForStats ()
force skip calling FThreadStats::WaitForStats()
static bool SupportsMultithreading ()
Gets whether this platform can use multiple threads.
static void TearDown ()
Tears down allocated process resources.
static void TeardownAudioThread ()
Allow the platform to tear down the audio thread.
static void TerminateProc (FProcHandle &ProcessHandle, bool KillTree=false)
Terminates a process.
static void TerminateProcTreeWithPredicate (FProcHandle &ProcessHandle, TFunctionRef< bool(uint32 ProcessId, const TCHAR *ApplicationName)> Predicate)
Terminates a process tree.
static bool TryGetMemoryUsage (FProcHandle &ProcessHandle, FPlatformProcessMemoryStats &OutStats)
Queries the memory usage of the process.
static const TCHAR * UserDir ()
Get user directory.
static const TCHAR * UserHomeDir ()
Get the user home directory.
static const TCHAR * UserName (bool bOnlyAlphaNumeric=true)
Get user name.
static const TCHAR * UserSettingsDir ()
Get the user settings directory.
static const TCHAR * UserTempDir ()
Get the user temporary directory.
static EWaitAndForkResult WaitAndFork ()
Waits for process signals and forks child processes.
static void WaitForProc (FProcHandle &ProcessHandle)
Waits for a process to stop.
static bool WritePipe (void *WritePipe, const FString &Message, FString *OutWritten=nullptr)
Sends the message to process through pipe.
static bool WritePipe (void *WritePipe, const uint8 *Data, const int32 DataLength, int32 *OutDataLength=nullptr)
Sends data to process through pipe.
static FORCEINLINE void Yield ()
Tells the processor to pause for implementation-specific amount of time.
static FORCEINLINE void YieldCycles (uint64 Cycles)
Tells the processor to pause for at least the amount of cycles given.
Static Public Attributes
static FLaunchURLOverride LaunchURLOverrideDelegate
Static Protected Member Functions
static void ReadFromPipes (FString *OutStrings[], Windows::HANDLE InPipes[], int32 PipeCount)
Reads from a collection of anonymous pipes.
Static Private Member Functions
static void LaunchURLInternal (const TCHAR *URL, const TCHAR *Parms, FString *Error)
static void * LoadLibraryWithSearchPaths (const FString &FileName, const TArray< FString > &SearchPaths)
Replacement implementation of the Win32 LoadLibrary function which searches the given list of directories for dependent imports, and attempts to load them from the correct location first.
static bool ResolveImport (const FString &Name, const TArray< FString > &SearchPaths, FString &OutFileName)
Resolve an individual import.
static void ResolveMissingImportsRecursive (const FString &FileName, const TArray< FString > &SearchPaths, TArray< FString > &ImportFileNames, TSet< FString > &VisitedImportNames)
Resolve all the imports for the given library, searching through a set of directories.
Static Private Attributes
static TArray< FString > DllDirectories
All the DLL directories we want to load from.
static TArray< FString > DllDirectoryStack
Since Windows can only have one directory at a time, this stack is used to reset the previous DllDirectory.
static TMap< FName, TArray< FString > > SearchPathDllCache
A cache of the dlls found in each directory in DllDirectories.
Additional Inherited Members
Public Types inherited from FGenericPlatformProcess
enum class EWaitAndForkResult : uint8 { Error , Parent , Child }
Detailed Description
Windows implementation of the process handle.
Windows implementation of the Process OS functions.
Definition at line 34 of file WindowsPlatformProcess.h.
Member Function Documentation
AddDllDirectory()
void FWindowsPlatformProcess::AddDllDirectory (const TCHAR * Directory) static
ApplicationSettingsDir()
const TCHAR * FWindowsPlatformProcess::ApplicationSettingsDir () static
BaseDir()
const TCHAR * FWindowsPlatformProcess::BaseDir () static
CanLaunchURL()
bool FWindowsPlatformProcess::CanLaunchURL (const TCHAR * URL) static
References CanLaunchURL().
Referenced by CanLaunchURL().
CeaseBeingFirstInstance()
void FWindowsPlatformProcess::CeaseBeingFirstInstance () static
Releases locks that we held for IsFirstInstance check.
References CeaseBeingFirstInstance().
Referenced by CeaseBeingFirstInstance().
ClosePipe()
void FWindowsPlatformProcess::ClosePipe (void * ReadPipe, void * WritePipe) static
References ClosePipe(), ReadPipe(), and WritePipe().
Referenced by ClosePipe().
CloseProc()
void FWindowsPlatformProcess::CloseProc (FProcHandle & ProcessHandle) static
ComputerName()
const TCHAR * FWindowsPlatformProcess::ComputerName () static
CreateElevatedProcess()
FProcHandle FWindowsPlatformProcess::CreateElevatedProcess (const TCHAR * URL, const TCHAR * Params) static
References Params.
CreatePipe()
bool FWindowsPlatformProcess::CreatePipe (void *& ReadPipe, void *& WritePipe, bool bWritePipeLocal = false) static
References CreatePipe(), ReadPipe(), and WritePipe().
Referenced by CreatePipe().
CreateProc() [1/2]
FProcHandle FWindowsPlatformProcess::CreateProc (const TCHAR * URL, const TCHAR * Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 * OutProcessID, int32 PriorityModifier, const TCHAR * OptionalWorkingDirectory, void * PipeWriteChild, void * PipeReadChild, void * PipeStdErrChild) static
CreateProc() [2/2]
FProcHandle FWindowsPlatformProcess::CreateProc (const TCHAR * URL, const TCHAR * Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 * OutProcessID, int32 PriorityModifier, const TCHAR * OptionalWorkingDirectory, void * PipeWriteChild, void * PipeReadChild = nullptr) static
CreateRunnableThread()
class FRunnableThread * FWindowsPlatformProcess::CreateRunnableThread () static
References CreateRunnableThread().
Referenced by CreateRunnableThread().
Daemonize()
bool FWindowsPlatformProcess::Daemonize () static
References Daemonize().
Referenced by Daemonize().
DeleteInterprocessSynchObject()
bool FWindowsPlatformProcess::DeleteInterprocessSynchObject (FSemaphore * Object) static
References DeleteInterprocessSynchObject(), and Object.
Referenced by DeleteInterprocessSynchObject().
ExecElevatedProcess()
bool FWindowsPlatformProcess::ExecElevatedProcess (const TCHAR * URL, const TCHAR * Params, int32 * OutReturnCode) static
References Params.
ExecProcess()
bool FWindowsPlatformProcess::ExecProcess (const TCHAR * URL, const TCHAR * Params, int32 * OutReturnCode, FString * OutStdOut, FString * OutStdErr, const TCHAR * OptionalWorkingDirectory = NULL, bool bShouldEndWithParentProcess = false) static
References Params.
ExecutableName()
const TCHAR * FWindowsPlatformProcess::ExecutableName (bool bRemoveExtension = true) static
ExecutablePath()
const TCHAR * FWindowsPlatformProcess::ExecutablePath () static
ExploreFolder()
void FWindowsPlatformProcess::ExploreFolder (const TCHAR * FilePath) static
FreeDllHandle()
void FWindowsPlatformProcess::FreeDllHandle (void * DllHandle) static
GenerateApplicationPath()
FString FWindowsPlatformProcess::GenerateApplicationPath (const FString & AppName, EBuildConfiguration BuildConfiguration) static
GetApplicationMemoryUsage()
bool FWindowsPlatformProcess::GetApplicationMemoryUsage (uint32 ProcessId, SIZE_T * OutMemoryUsage) static
GetApplicationName()
FString FWindowsPlatformProcess::GetApplicationName (uint32 ProcessId) static
GetApplicationSettingsDir()
FString FWindowsPlatformProcess::GetApplicationSettingsDir (const ApplicationSettingsContext & Settings) static
GetArchitectureSuffix()
const TCHAR * FWindowsPlatformProcess::GetArchitectureSuffix () static
GetBinariesSubdirectory()
const TCHAR * FWindowsPlatformProcess::GetBinariesSubdirectory () static
GetCurrentCoreNumber()
uint32 FWindowsPlatformProcess::GetCurrentCoreNumber () static
GetCurrentProcessId()
uint32 FWindowsPlatformProcess::GetCurrentProcessId () static
GetCurrentWorkingDirectory()
FString FWindowsPlatformProcess::GetCurrentWorkingDirectory () static
GetDllDirectories()
void FWindowsPlatformProcess::GetDllDirectories (TArray< FString > & OutDllDirectories) static
GetDllExport()
void * FWindowsPlatformProcess::GetDllExport (void * DllHandle, const TCHAR * ProcName) static
GetDllHandle()
void * FWindowsPlatformProcess::GetDllHandle (const TCHAR * Filename) static
References Filename.
GetModuleExtension()
const TCHAR * FWindowsPlatformProcess::GetModuleExtension () static
GetModulesDirectory()
const FString FWindowsPlatformProcess::GetModulesDirectory () static
GetPerFrameProcessorUsage()
bool FWindowsPlatformProcess::GetPerFrameProcessorUsage (uint32 ProcessId, float & ProcessUsageFraction, float & IdleUsageFraction) static
GetProcReturnCode()
bool FWindowsPlatformProcess::GetProcReturnCode (FProcHandle & ProcHandle, int32 * ReturnCode) static
IsApplicationRunning() [1/2]
bool FWindowsPlatformProcess::IsApplicationRunning (const TCHAR * ProcName) static
IsApplicationRunning() [2/2]
bool FWindowsPlatformProcess::IsApplicationRunning (uint32 ProcessId) static
IsFirstInstance()
bool FWindowsPlatformProcess::IsFirstInstance () static
References IsFirstInstance().
Referenced by IsFirstInstance().
IsProcessAffinitySet()
bool FWindowsPlatformProcess::IsProcessAffinitySet () static
IsProcRunning()
bool FWindowsPlatformProcess::IsProcRunning (FProcHandle & ProcessHandle) static
LaunchFileInDefaultExternalApplication()
bool FWindowsPlatformProcess::LaunchFileInDefaultExternalApplication (const TCHAR * FileName, const TCHAR * Parms = NULL, ELaunchVerb::Type Verb = ELaunchVerb::Open, bool bPromptToOpenOnFailure = true) static
References ELaunchVerb::Open.
LaunchURL()
void FWindowsPlatformProcess::LaunchURL (const TCHAR * URL, const TCHAR * Parms, FString * Error) static
References FGenericPlatformProcess::Error, and LaunchURL().
Referenced by LaunchURL().
LaunchURLInternal()
void FWindowsPlatformProcess::LaunchURLInternal (const TCHAR * URL, const TCHAR * Parms, FString * Error) static private
References FGenericPlatformProcess::Error, and LaunchURLInternal().
Referenced by LaunchURLInternal().
LoadLibraryWithSearchPaths()
void * FWindowsPlatformProcess::LoadLibraryWithSearchPaths (const FString & FileName, const TArray< FString > & SearchPaths) static private
Replacement implementation of the Win32 LoadLibrary function which searches the given list of directories for dependent imports, and attempts to load them from the correct location first.
The normal LoadLibrary function (pre-Win8) only searches a limited list of locations.
Parameters
FileName Path to the library to load
SearchPaths Search directories to scan for imports
References LoadLibraryWithSearchPaths().
Referenced by LoadLibraryWithSearchPaths().
NewInterprocessSynchObject() [1/2]
FSemaphore * FWindowsPlatformProcess::NewInterprocessSynchObject (const FString & Name, bool bCreate, uint32 MaxLocks = 1) static
References Name, and NewInterprocessSynchObject().
Referenced by NewInterprocessSynchObject(), and NewInterprocessSynchObject().
NewInterprocessSynchObject() [2/2]
FSemaphore * FWindowsPlatformProcess::NewInterprocessSynchObject (const TCHAR * Name, bool bCreate, uint32 MaxLocks = 1) static
References Name, and NewInterprocessSynchObject().
OpenProcess()
FProcHandle FWindowsPlatformProcess::OpenProcess (uint32 ProcessID) static
PopDllDirectory()
void FWindowsPlatformProcess::PopDllDirectory (const TCHAR * Directory) static
PushDllDirectory()
void FWindowsPlatformProcess::PushDllDirectory (const TCHAR * Directory) static
ReadFromPipes()
void FWindowsPlatformProcess::ReadFromPipes (FString * OutStrings[], Windows::HANDLE InPipes[], int32 PipeCount) static protected
Reads from a collection of anonymous pipes.
Parameters
OutStrings Will hold the read data.
InPipes The pipes to read from.
PipeCount The number of pipes.
References ReadFromPipes().
Referenced by ReadFromPipes().
ReadPipe()
FString FWindowsPlatformProcess::ReadPipe (void * ReadPipe) static
References ReadPipe().
Referenced by ClosePipe(), CreatePipe(), ReadPipe(), and ReadPipeToArray().
ReadPipeToArray()
bool FWindowsPlatformProcess::ReadPipeToArray (void * ReadPipe, TArray< uint8 > & Output) static
References ReadPipe(), and ReadPipeToArray().
Referenced by ReadPipeToArray().
ResolveImport()
bool FWindowsPlatformProcess::ResolveImport (const FString & Name, const TArray< FString > & SearchPaths, FString & OutFileName) static private
Resolve an individual import.
Parameters
ImportName Name of the imported module
OutFileName On success, receives the path to the imported file
Returns
true if an import was found.
References Name, and ResolveImport().
Referenced by ResolveImport().
ResolveMissingImportsRecursive()
void FWindowsPlatformProcess::ResolveMissingImportsRecursive (const FString & FileName, const TArray< FString > & SearchPaths, TArray< FString > & ImportFileNames, TSet< FString > & VisitedImportNames) static private
Resolve all the imports for the given library, searching through a set of directories.
Parameters
FileName Path to the library to load
SearchPaths Search directories to scan for imports
ImportFileNames Array which is filled with a list of the resolved imports found in the given search directories
VisitedImportNames Array which stores a list of imports which have been checked
References ResolveMissingImportsRecursive().
Referenced by ResolveMissingImportsRecursive().
ResolveNetworkPath()
bool FWindowsPlatformProcess::ResolveNetworkPath (FString InUNCPath, FString & OutPath) static
SetCurrentWorkingDirectoryToBaseDir()
void FWindowsPlatformProcess::SetCurrentWorkingDirectoryToBaseDir () static
SetProcessAffinity()
bool FWindowsPlatformProcess::SetProcessAffinity (uint32 NumCoresForAffinity, bool bPhysicalCoresOnly) static
SetProcPriority()
bool FWindowsPlatformProcess::SetProcPriority (FProcHandle & InProcHandle, int32 PriorityModifier) static
SetThreadAffinityMask()
void FWindowsPlatformProcess::SetThreadAffinityMask (uint64 AffinityMask) static
SetThreadName()
void FWindowsPlatformProcess::SetThreadName (const TCHAR * ThreadName) static
SetThreadPriority()
void FWindowsPlatformProcess::SetThreadPriority (EThreadPriority NewPriority) static
SetupAudioThread()
void FWindowsPlatformProcess::SetupAudioThread () static
References SetupAudioThread().
Referenced by SetupAudioThread().
SetupGameThread()
void FWindowsPlatformProcess::SetupGameThread () static
References SetupGameThread().
Referenced by SetupGameThread().
ShaderWorkingDir()
const FString FWindowsPlatformProcess::ShaderWorkingDir () static
ShouldExpectLowIntegrityLevel()
bool FWindowsPlatformProcess::ShouldExpectLowIntegrityLevel () static
Whether to expect to run at a low process integrity level or not.
This affects the paths that must be used for user and temp storage. The process may launch at default (medium) integrity level and then downgrade itself to low later for security benefits, so checking the current integrity level alone is not sufficient.
Returns
true if low integrity level should be expected, otherwise false.
References ShouldExpectLowIntegrityLevel().
Referenced by ShouldExpectLowIntegrityLevel().
Sleep()
void FWindowsPlatformProcess::Sleep (float Seconds) static
References Seconds.
SleepInfinite()
void FWindowsPlatformProcess::SleepInfinite () static
SleepNoStats()
void FWindowsPlatformProcess::SleepNoStats (float Seconds) static
References Seconds.
TeardownAudioThread()
void FWindowsPlatformProcess::TeardownAudioThread () static
References TeardownAudioThread().
Referenced by TeardownAudioThread().
TerminateProc()
void FWindowsPlatformProcess::TerminateProc (FProcHandle & ProcessHandle, bool KillTree = false) static
TerminateProcTreeWithPredicate()
void FWindowsPlatformProcess::TerminateProcTreeWithPredicate (FProcHandle & ProcessHandle, TFunctionRef< bool(uint32 ProcessId, const TCHAR *ApplicationName)> Predicate) static
References Predicate.
TryGetMemoryUsage()
bool FWindowsPlatformProcess::TryGetMemoryUsage (FProcHandle & ProcessHandle, FPlatformProcessMemoryStats & OutStats) static
References TryGetMemoryUsage().
Referenced by TryGetMemoryUsage().
UE_DEPRECATED()
FWindowsPlatformProcess::UE_DEPRECATED (5. 0, "Please use GetSynchEventFromPool to create a new event, and ReturnSynchEventToPool to release the event.")
UserDir()
const TCHAR * FWindowsPlatformProcess::UserDir () static
UserHomeDir()
const TCHAR * FWindowsPlatformProcess::UserHomeDir () static
UserName()
const TCHAR * FWindowsPlatformProcess::UserName (bool bOnlyAlphaNumeric = true) static
UserSettingsDir()
const TCHAR * FWindowsPlatformProcess::UserSettingsDir () static
UserSettingsDirMediumIntegrity()
const TCHAR * FWindowsPlatformProcess::UserSettingsDirMediumIntegrity () static
UserTempDir()
const TCHAR * FWindowsPlatformProcess::UserTempDir () static
WaitForProc()
void FWindowsPlatformProcess::WaitForProc (FProcHandle & ProcessHandle) static
WindowsSystemDir()
const TCHAR * FWindowsPlatformProcess::WindowsSystemDir () static
WritePipe() [1/2]
bool FWindowsPlatformProcess::WritePipe (void * WritePipe, const FString & Message, FString * OutWritten = nullptr) static
References WritePipe().
Referenced by ClosePipe(), CreatePipe(), WritePipe(), and WritePipe().
WritePipe() [2/2]
bool FWindowsPlatformProcess::WritePipe (void * WritePipe, const uint8 * Data, const int32 DataLength, int32 * OutDataLength = nullptr) static
References WritePipe().
YieldThread()
void FWindowsPlatformProcess::YieldThread () static
Field Documentation
DllDirectories
TArray<FString> FWindowsPlatformProcess::DllDirectories static private
All the DLL directories we want to load from.
Definition at line 258 of file WindowsPlatformProcess.h.
DllDirectoryStack
TArray<FString> FWindowsPlatformProcess::DllDirectoryStack static private
Since Windows can only have one directory at a time, this stack is used to reset the previous DllDirectory.
Definition at line 253 of file WindowsPlatformProcess.h.
LaunchURLOverrideDelegate
FLaunchURLOverride FWindowsPlatformProcess::LaunchURLOverrideDelegate static
Definition at line 230 of file WindowsPlatformProcess.h.
SearchPathDllCache
TMap<FName, TArray<FString> > FWindowsPlatformProcess::SearchPathDllCache static private
A cache of the dlls found in each directory in DllDirectories.
Definition at line 263 of file WindowsPlatformProcess.h.
The documentation for this struct was generated from the following file:
WindowsPlatformProcess.h