Unreal Engine 5.6 C++ API: UE::MovieScene::FComponentMask Struct Reference
UE::MovieScene::FComponentMask Struct Reference
#include "MovieSceneEntityIDs.h"
Public Member Functions
FComponentMask ()
FComponentMask (bool bValue, int32 InNum)
FComponentMask (std::initializer_list< FComponentTypeID > InComponentTypes)
FORCEINLINE void BitwiseNOT ()
FORCEINLINE FComponentMask & CombineWithBitwiseAND (const FComponentMask &Other, EBitwiseOperatorFlags InFlags)
FORCEINLINE FComponentMask & CombineWithBitwiseOR (const FComponentMask &Other, EBitwiseOperatorFlags InFlags)
FORCEINLINE FComponentMask & CombineWithBitwiseXOR (const FComponentMask &Other, EBitwiseOperatorFlags InFlags)
bool CompareSetBits (const FComponentMask &Other) const
bool Contains (FComponentTypeID InComponentType) const
bool ContainsAll (const FComponentMask &InComponentMask) const
bool ContainsAny (const FComponentMask &InComponentMask) const
FORCEINLINE int32 Find (bool bValue) const
FComponentTypeID First () const
Find the first component type ID in this mask, or Invalid if the mask is empty.
FComponentMaskIterator Iterate () const
FORCEINLINE int32 Num () const
FORCEINLINE int32 NumComponents () const
FBitReference operator[] (FComponentTypeID ComponentType)
FConstBitReference operator[] (FComponentTypeID ComponentType) const
FORCEINLINE void PadToNum (int32 Num, bool bPadValue)
void Remove (FComponentTypeID InComponentType)
FORCEINLINE void Reset ()
void Set (FComponentTypeID InComponentType)
void SetAll (std::initializer_list< FComponentTypeID > InComponentTypes)
void SetAllLenient (std::initializer_list< FComponentTypeID > InComponentTypes)
Static Public Member Functions
static FORCEINLINE FComponentMask BitwiseAND (const FComponentMask &A, const FComponentMask &B, EBitwiseOperatorFlags InFlags)
static FORCEINLINE FComponentMask BitwiseNOT (const FComponentMask &A)
static FORCEINLINE FComponentMask BitwiseOR (const FComponentMask &A, const FComponentMask &B, EBitwiseOperatorFlags InFlags)
static FORCEINLINE FComponentMask BitwiseXOR (const FComponentMask &A, const FComponentMask &B, EBitwiseOperatorFlags InFlags)
Private Attributes
TBitArray< FComponentMaskAllocator > Bits
Friends
uint32 GetTypeHash (const FComponentMask &Mask)
bool operator== (const FComponentMask &A, const FComponentMask &B)
Detailed Description
Definition at line 39 of file MovieSceneEntityIDs.h.
Constructor & Destructor Documentation
FComponentMask() [1/3]
UE::MovieScene::FComponentMask::FComponentMask () inline
Definition at line 41 of file MovieSceneEntityIDs.h.
Referenced by BitwiseAND(), BitwiseNOT(), BitwiseOR(), BitwiseXOR(), CombineWithBitwiseAND(), CombineWithBitwiseOR(), CombineWithBitwiseXOR(), CompareSetBits(), ContainsAll(), ContainsAny(), GetTypeHash, and operator==.
FComponentMask() [2/3]
UE::MovieScene::FComponentMask::FComponentMask (bool bValue, int32 InNum) inline
Definition at line 43 of file MovieSceneEntityIDs.h.
References Bits.
FComponentMask() [3/3]
UE::MovieScene::FComponentMask::FComponentMask (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Definition at line 47 of file MovieSceneEntityIDs.h.
References SetAll().
Member Function Documentation
BitwiseAND()
FORCEINLINE FComponentMask UE::MovieScene::FComponentMask::BitwiseAND (const FComponentMask & A, const FComponentMask & B, EBitwiseOperatorFlags InFlags) inline static
Definition at line 94 of file MovieSceneEntityIDs.h.
References FComponentMask(), A, B, TBitArray< Allocator >::BitwiseAND(), and FORCEINLINE.
Referenced by ContainsAll(), ContainsAny(), and UE::MovieScene::FEntityManager::ContainsAnyComponent().
BitwiseNOT() [1/2]
FORCEINLINE void UE::MovieScene::FComponentMask::BitwiseNOT () inline
Definition at line 122 of file MovieSceneEntityIDs.h.
References Bits, and FORCEINLINE.
BitwiseNOT() [2/2]
FORCEINLINE FComponentMask UE::MovieScene::FComponentMask::BitwiseNOT (const FComponentMask & A) inline static
Definition at line 115 of file MovieSceneEntityIDs.h.
References FComponentMask(), A, and FORCEINLINE.
Referenced by UE::MovieScene::FTypelessMutation::MutateType().
BitwiseOR()
FORCEINLINE FComponentMask UE::MovieScene::FComponentMask::BitwiseOR (const FComponentMask & A, const FComponentMask & B, EBitwiseOperatorFlags InFlags) inline static
Definition at line 101 of file MovieSceneEntityIDs.h.
References FComponentMask(), A, B, TBitArray< Allocator >::BitwiseOR(), and FORCEINLINE.
BitwiseXOR()
FORCEINLINE FComponentMask UE::MovieScene::FComponentMask::BitwiseXOR (const FComponentMask & A, const FComponentMask & B, EBitwiseOperatorFlags InFlags) inline static
Definition at line 108 of file MovieSceneEntityIDs.h.
References FComponentMask(), A, B, TBitArray< Allocator >::BitwiseXOR(), and FORCEINLINE.
CombineWithBitwiseAND()
FORCEINLINE FComponentMask & UE::MovieScene::FComponentMask::CombineWithBitwiseAND (const FComponentMask & Other, EBitwiseOperatorFlags InFlags) inline
Definition at line 88 of file MovieSceneEntityIDs.h.
References FComponentMask(), Bits, FORCEINLINE, and Other.
Referenced by UE::MovieScene::FTypelessMutation::MutateType(), and UE::MovieScene::FComplexInclusivityFilter::UE_DEPRECATED().
CombineWithBitwiseOR()
FORCEINLINE FComponentMask & UE::MovieScene::FComponentMask::CombineWithBitwiseOR (const FComponentMask & Other, EBitwiseOperatorFlags InFlags) inline
Definition at line 76 of file MovieSceneEntityIDs.h.
References FComponentMask(), Bits, FORCEINLINE, and Other.
Referenced by UE::MovieScene::FAddMany::AccumulateMask(), and UE::MovieScene::FTypelessMutation::MutateType().
CombineWithBitwiseXOR()
FORCEINLINE FComponentMask & UE::MovieScene::FComponentMask::CombineWithBitwiseXOR (const FComponentMask & Other, EBitwiseOperatorFlags InFlags) inline
Definition at line 82 of file MovieSceneEntityIDs.h.
References FComponentMask(), Bits, FORCEINLINE, and Other.
CompareSetBits()
bool UE::MovieScene::FComponentMask::CompareSetBits (const FComponentMask & Other) const inline
Definition at line 71 of file MovieSceneEntityIDs.h.
References FComponentMask(), Bits, and Other.
Referenced by ContainsAll(), and UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int, Indices... >, T... >::MutateExisting().
Contains()
bool UE::MovieScene::FComponentMask::Contains (FComponentTypeID InComponentType) const inline
Definition at line 429 of file MovieSceneEntityIDs.h.
References UE::MovieScene::FComponentTypeID::BitIndex(), and Bits.
Referenced by UE::MovieScene::FEntityManager::ContainsComponent(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::FMaterialGroupingPolicy::InitializeGroupKeys(), UE::MovieScene::FChildEntityInitializer::IsRelevant(), UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::Process(), and UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::ProcessAllocation().
ContainsAll()
bool UE::MovieScene::FComponentMask::ContainsAll (const FComponentMask & InComponentMask) const inline
Definition at line 434 of file MovieSceneEntityIDs.h.
References FComponentMask(), BitwiseAND(), CompareSetBits(), and MinSize.
Referenced by UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType >::IsRelevant().
ContainsAny()
bool UE::MovieScene::FComponentMask::ContainsAny (const FComponentMask & InComponentMask) const inline
Definition at line 439 of file MovieSceneEntityIDs.h.
References FComponentMask(), BitwiseAND(), Find(), INDEX_NONE, and MinSize.
Find()
FORCEINLINE int32 UE::MovieScene::FComponentMask::Find (bool bValue) const inline
Definition at line 152 of file MovieSceneEntityIDs.h.
References Bits, and FORCEINLINE.
Referenced by ContainsAny(), and UE::MovieScene::FComplexInclusivityFilter::UE_DEPRECATED().
First()
FComponentTypeID UE::MovieScene::FComponentMask::First () const inline
Find the first component type ID in this mask, or Invalid if the mask is empty.
Definition at line 490 of file MovieSceneEntityIDs.h.
References Bits, UE::MovieScene::FComponentTypeID::FromBitIndex(), INDEX_NONE, and UE::MovieScene::FComponentTypeID::Invalid().
Referenced by UE::MovieScene::FEntityManager::ContainsAnyComponent().
Iterate()
FComponentMaskIterator UE::MovieScene::FComponentMask::Iterate () const inline
Definition at line 56 of file MovieSceneEntityIDs.h.
References Bits.
Num()
FORCEINLINE int32 UE::MovieScene::FComponentMask::Num () const inline
Definition at line 147 of file MovieSceneEntityIDs.h.
References Bits, and FORCEINLINE.
Referenced by PadToNum().
NumComponents()
FORCEINLINE int32 UE::MovieScene::FComponentMask::NumComponents () const inline
Definition at line 157 of file MovieSceneEntityIDs.h.
References Bits, and FORCEINLINE.
operator[]() [1/2]
FBitReference UE::MovieScene::FComponentMask::operator[] (FComponentTypeID ComponentType) inline
Definition at line 419 of file MovieSceneEntityIDs.h.
References UE::MovieScene::FComponentTypeID::BitIndex(), and Bits.
operator[]() [2/2]
FConstBitReference UE::MovieScene::FComponentMask::operator[] (FComponentTypeID ComponentType) const inline
Definition at line 424 of file MovieSceneEntityIDs.h.
References UE::MovieScene::FComponentTypeID::BitIndex(), and Bits.
PadToNum()
FORCEINLINE void UE::MovieScene::FComponentMask::PadToNum (int32 Num, bool bPadValue) inline
Definition at line 162 of file MovieSceneEntityIDs.h.
References Bits, FORCEINLINE, and Num().
Remove()
void UE::MovieScene::FComponentMask::Remove (FComponentTypeID InComponentType) inline
Definition at line 481 of file MovieSceneEntityIDs.h.
References UE::MovieScene::FComponentTypeID::BitIndex(), Bits, and checkSlow.
Reset()
FORCEINLINE void UE::MovieScene::FComponentMask::Reset () inline
Definition at line 142 of file MovieSceneEntityIDs.h.
References Bits, and FORCEINLINE.
Set()
void UE::MovieScene::FComponentMask::Set (FComponentTypeID InComponentType) inline
Definition at line 444 of file MovieSceneEntityIDs.h.
References UE::MovieScene::FComponentTypeID::BitIndex(), Bits, and checkSlow.
Referenced by UE::MovieScene::FAdd::AccumulateMask(), UE::MovieScene::FAddConditional::AccumulateMask(), UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::CreateMutation(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), UE::MovieScene::PopulateReadWriteDependencies(), UE::MovieScene::PopulateReadWriteDependencies(), UE::MovieScene::PopulateReadWriteDependencies(), UE::MovieScene::PopulateReadWriteDependencies(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
SetAll()
void UE::MovieScene::FComponentMask::SetAll (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Definition at line 454 of file MovieSceneEntityIDs.h.
References Bits, and checkSlow.
Referenced by FComponentMask().
SetAllLenient()
void UE::MovieScene::FComponentMask::SetAllLenient (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Definition at line 467 of file MovieSceneEntityIDs.h.
References Bits.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FComponentMask & Mask) friend
Definition at line 61 of file MovieSceneEntityIDs.h.
References FComponentMask(), GetTypeHash, and Mask.
Referenced by GetTypeHash.
operator==
bool operator== (const FComponentMask & A, const FComponentMask & B) friend
Definition at line 66 of file MovieSceneEntityIDs.h.
References FComponentMask(), A, and B.
Field Documentation
Bits
TBitArray<FComponentMaskAllocator> UE::MovieScene::FComponentMask::Bits private
Definition at line 169 of file MovieSceneEntityIDs.h.
Referenced by FComponentMask(), BitwiseNOT(), CombineWithBitwiseAND(), CombineWithBitwiseOR(), CombineWithBitwiseXOR(), CompareSetBits(), Contains(), Find(), First(), Iterate(), Num(), NumComponents(), operator[](), operator[](), PadToNum(), Remove(), Reset(), Set(), SetAll(), and SetAllLenient().
The documentation for this struct was generated from the following file:
MovieSceneEntityIDs.h