Unreal Engine 5.6 C++ API: FBlendableEntry Struct Reference
FBlendableEntry Struct Reference
#include "BlendableManager.h"
Data Fields
float Weight
Private Member Functions
uint8 * GetDataPtr ()
FBlendableEntry * GetNext ()
Private Attributes
FName BlendableType
uint32 DataSize
uint32 PrePadding
Friends
class FBlendableManager
Detailed Description
Definition at line 8 of file BlendableManager.h.
Member Function Documentation
GetDataPtr()
uint8 * FBlendableEntry::GetDataPtr () inline private
Definition at line 22 of file BlendableManager.h.
References check, and PrePadding.
Referenced by GetNext(), FBlendableManager::IterateBlendables(), FBlendableManager::PushBlendableData(), and FBlendableManager::PushBlendableDataPtr().
GetNext()
FBlendableEntry * FBlendableEntry::GetNext () inline private
Definition at line 24 of file BlendableManager.h.
References DataSize, and GetDataPtr().
Friends And Related Symbol Documentation
FBlendableManager
friend class FBlendableManager friend
Definition at line 26 of file BlendableManager.h.
References FBlendableManager.
Referenced by FBlendableManager.
Field Documentation
BlendableType
FName FBlendableEntry::BlendableType private
Definition at line 15 of file BlendableManager.h.
Referenced by FBlendableManager::IterateBlendables(), and FBlendableManager::PushBlendableDataPtr().
DataSize
uint32 FBlendableEntry::DataSize private
Definition at line 17 of file BlendableManager.h.
Referenced by GetNext(), and FBlendableManager::PushBlendableDataPtr().
PrePadding
uint32 FBlendableEntry::PrePadding private
Definition at line 19 of file BlendableManager.h.
Referenced by GetDataPtr(), and FBlendableManager::PushBlendableDataPtr().
Weight
float FBlendableEntry::Weight
Definition at line 11 of file BlendableManager.h.
Referenced by FBlendableManager::PushBlendableDataPtr().
The documentation for this struct was generated from the following file:
BlendableManager.h