Unreal Engine 5.6 C++ API: FTexture2DResource Class Reference
FTexture2DResource Class Reference
FTextureResource implementation for streamable 2D textures.
#include "Texture2DResource.h"
Public Member Functions
FTexture2DResource (UTexture2D *InOwner, const FStreamableRenderResourceState &InPostInitState)
Minimal initialization constructor.
virtual ~FTexture2DResource ()
Destructor, freeing MipData in the case of resource being destroyed without ever having been initialized by the rendering thread via InitRHI.
void CacheSamplerStateInitializer (const UTexture2D *InOwner)
Set the value of Filter, AddressU, AddressV, AddressW and MipBias from FStreamableTextureResource on the gamethread.
virtual uint64 GetPlatformMipsSize (uint32 NumMips) const override
Returns the platform mip size for the given mip count.
virtual FTexture2DResource * GetTexture2DResource ()
virtual const FTexture2DResource * GetTexture2DResource () const
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual bool IsProxy () const override
Returns true if the resource is proxying another one.
Public Member Functions inherited from FStreamableTextureResource
FStreamableTextureResource (UTexture *InOwner, const FTexturePlatformData *InPlatformData, const FStreamableRenderResourceState &InPostInitState, bool bAllowPartiallyResidentMips)
void FinalizeStreaming (FRHITexture *InTextureRHI)
FORCEINLINE ETextureCreateFlags GetCreationFlags () const
FORCEINLINE int32 GetCurrentFirstMip () const
FORCEINLINE uint32 GetExtData () const
FORCEINLINE TextureGroup GetLODGroup () const
FORCEINLINE EPixelFormat GetPixelFormat () const
const FTexture2DMipMap * GetPlatformMip (int32 MipIdx) const
TArrayView< const FTexture2DMipMap * > GetPlatformMipsView () const
FORCEINLINE FStreamableRenderResourceState GetPostInitState () const
virtual uint32 GetSizeX () const final override
Returns the width of the texture in pixels.
virtual uint32 GetSizeY () const final override
Returns the height of the texture in pixels.
virtual uint32 GetSizeZ () const final override
Returns the depth of the texture in pixels.
FORCEINLINE FStreamableRenderResourceState GetState () const
virtual FStreamableTextureResource * GetStreamableTextureResource ()
virtual const FStreamableTextureResource * GetStreamableTextureResource () const
FORCEINLINE const FName & GetTextureName () const
void RefreshSamplerStates ()
Returns the default mip map bias for this texture.
virtual void ReleaseRHI () final override
Releases the RHI resources used by this resource.
Public Member Functions inherited from FTextureResource
FTextureResource ()
virtual ~FTextureResource ()
FORCEINLINE int32 GetCurrentMipCount () const
virtual FTexture2DArrayResource * GetTexture2DArrayResource ()
virtual const FTexture2DArrayResource * GetTexture2DArrayResource () const
FORCEINLINE FRHITexture * GetTexture2DArrayRHI () const
FORCEINLINE FRHITexture * GetTexture2DRHI () const
virtual FTexture3DResource * GetTexture3DResource ()
virtual const FTexture3DResource * GetTexture3DResource () const
FORCEINLINE FRHITexture * GetTexture3DRHI () const
FRHITextureReference * GetTextureReference () const
virtual FVirtualTexture2DResource * GetVirtualTexture2DResource ()
virtual const FVirtualTexture2DResource * GetVirtualTexture2DResource () const
FORCEINLINE bool IsTextureRHIPartiallyResident () const
void SetTextureReference (FRHITextureReference *TextureReference)
Public Member Functions inherited from FTexture
RENDERCORE_API FTexture ()
RENDERCORE_API FTexture (const FTexture &)
RENDERCORE_API FTexture (FTexture &&)
virtual RENDERCORE_API ~FTexture ()
virtual RENDERCORE_API FString GetFriendlyName () const override
const FTextureRHIRef & GetTextureRHI ()
RENDERCORE_API FTexture & operator= (const FTexture &Other)
RENDERCORE_API FTexture & operator= (FTexture &&Other)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static uint32 CalculateTightPackedMipSize (int32 SizeX, int32 SizeY, EPixelFormat PixelFormat, uint32 &OutPitch)
static void WarnRequiresTightPackedMip (int32 SizeX, int32 SizeY, EPixelFormat PixelFormat, uint32 Pitch)
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Private Member Functions
FTexture2DResource (UTexture2D *InOwner, const FTexture2DResource *InProxiedResource)
Make this Texture2DResource Proxy another one.
virtual void CreatePartiallyResidentTexture () final override
virtual void CreateTexture () final override
void GetData (uint32 MipIndex, void *Dest, uint32 DestPitch, uint64 DestSize)
Writes the data for a single mip-level into a destination buffer.
Private Attributes
TArray< void *, TInlineAllocator< MAX_TEXTURE_MIP_COUNT > > MipData
Local copy/ cache of mip data between creation and first call to InitRHI.
TArray< int64, TInlineAllocator< MAX_TEXTURE_MIP_COUNT > > MipDataSize
const FTexture2DResource *const ProxiedResource = nullptr
Another resource being proxied by this one.
FTexture2DResourceMem * ResourceMem
Resource memory allocated by the owner for serialize bulk mip data into.
Friends
class FTexture2DMipAllocator_Virtual
class FTexture2DUpdate
class UTexture2D
Texture streaming command classes that need to be friends in order to call Update/FinalizeMipCount.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Data Fields inherited from FTexture
bool bGreyScaleFormat = false
bGreyScaleFormat indicates the texture is actually in R channel but should be read as Grey (replicate R to RGBA) this is set from CompressionSettings, not PixelFormat this is only used by Editor/Debug shaders, not real game materials, which use SamplerType from MaterialExpressions
bool bIgnoreGammaConversions = false
true if the texture is in the same gamma space as the intended rendertarget (e.g.
bool bSRGB = false
Is the pixel data in this texture sRGB?
FSamplerStateRHIRef DeferredPassSamplerStateRHI
Sampler state to be used in deferred passes when discontinuities in ddx / ddy would cause too blurry of a mip to be used.
double LastRenderTime = -FLT_MAX
The last time the texture has been bound.
FMipBiasFade MipBiasFade
Base values for fading in/out mip-levels.
FSamplerStateRHIRef SamplerStateRHI
The sampler state to use for the texture.
FTextureRHIRef TextureRHI
The texture's RHI resource.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FTexture
static RENDERCORE_API FRHISamplerState * GetOrCreateSamplerState (const FSamplerStateInitializerRHI &Initializer)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes inherited from FStreamableTextureResource
TEnumAsByte< ESamplerAddressMode > AddressU = AM_Wrap
TEnumAsByte< ESamplerAddressMode > AddressV = AM_Wrap
TEnumAsByte< ESamplerAddressMode > AddressW = AM_Wrap
bool bUsePartiallyResidentMips = false
Whether this texture should be updated using the virtual address mapping for each mip.
ETextureCreateFlags CreationFlags = TexCreate_None
Creation flags of the texture.
TEnumAsByte< ESamplerFilter > Filter = SF_Point
Sample config.
TextureGroup LODGroup = TEXTUREGROUP_World
The asset LOD group.
int8 MaxAniso = 0
Max anisotropy.
float MipBias = 0
EMipFadeSettings MipFadeSetting = MipFade_Normal
Mip fade settings.
EPixelFormat PixelFormat = PF_Unknown
Format of the texture.
const FTexturePlatformData * PlatformData
Platform data should be ref counted eventually to remove any synchronization needed when the asset is rebuild.
uint32 SizeX = 0
The width this resource, when all mips are streamed in.
uint32 SizeY = 0
The height when all mips are streamed in.
uint32 SizeZ = 0
The 3d depth for volume texture or num slices for 2d array when all mips are streamed in.
FStreamableRenderResourceState State
Different states for streaming synchronization.
FName TextureName
The FName of the texture asset.
Protected Attributes inherited from FTextureResource
FTextureReferenceRHIRef TextureReferenceRHI
Detailed Description
FTextureResource implementation for streamable 2D textures.
Definition at line 15 of file Texture2DResource.h.
Constructor & Destructor Documentation
FTexture2DResource() [1/2]
FTexture2DResource::FTexture2DResource (UTexture2D * InOwner, const FStreamableRenderResourceState & InPostInitState)
Minimal initialization constructor.
Parameters
InOwner UTexture2D which this FTexture2DResource represents.
InPostInitState The renderthread coherent state the resource will have once InitRHI() will be called.
References UTexture2D.
Referenced by FTexture2DResource(), GetTexture2DResource(), and GetTexture2DResource().
~FTexture2DResource()
virtual FTexture2DResource::~FTexture2DResource () virtual
Destructor, freeing MipData in the case of resource being destroyed without ever having been initialized by the rendering thread via InitRHI.
FTexture2DResource() [2/2]
FTexture2DResource::FTexture2DResource (UTexture2D * InOwner, const FTexture2DResource * InProxiedResource) private
Make this Texture2DResource Proxy another one.
Parameters
InOwner UTexture2D which this FTexture2DResource represents.
InProxiedResource The resource to proxy.
References FTexture2DResource(), and UTexture2D.
Member Function Documentation
CacheSamplerStateInitializer()
void FTexture2DResource::CacheSamplerStateInitializer (const UTexture2D * InOwner)
Set the value of Filter, AddressU, AddressV, AddressW and MipBias from FStreamableTextureResource on the gamethread.
References UTexture2D.
CalculateTightPackedMipSize()
uint32 FTexture2DResource::CalculateTightPackedMipSize (int32 SizeX, int32 SizeY, EPixelFormat PixelFormat, uint32 & OutPitch) static
References FStreamableTextureResource::PixelFormat, FStreamableTextureResource::SizeX, and FStreamableTextureResource::SizeY.
CreatePartiallyResidentTexture()
virtual void FTexture2DResource::CreatePartiallyResidentTexture () final override private virtual
Implements FStreamableTextureResource.
References CreatePartiallyResidentTexture().
Referenced by CreatePartiallyResidentTexture().
CreateTexture()
virtual void FTexture2DResource::CreateTexture () final override private virtual
Implements FStreamableTextureResource.
GetData()
void FTexture2DResource::GetData (uint32 MipIndex, void * Dest, uint32 DestPitch, uint64 DestSize) private
Writes the data for a single mip-level into a destination buffer.
Parameters
MipIndex The index of the mip-level to read.
Dest The address of the destination buffer to receive the mip-level's data.
DestPitch Number of bytes per row
References GetData().
Referenced by GetData().
GetPlatformMipsSize()
virtual uint64 FTexture2DResource::GetPlatformMipsSize (uint32 NumMips) const override virtual
Returns the platform mip size for the given mip count.
Implements FStreamableTextureResource.
GetTexture2DResource() [1/2]
virtual FTexture2DResource * FTexture2DResource::GetTexture2DResource () inline virtual
Reimplemented from FTextureResource.
Definition at line 33 of file Texture2DResource.h.
References FTexture2DResource().
GetTexture2DResource() [2/2]
virtual const FTexture2DResource * FTexture2DResource::GetTexture2DResource () const inline virtual
Reimplemented from FTextureResource.
Definition at line 35 of file Texture2DResource.h.
References FTexture2DResource().
InitRHI()
virtual void FTexture2DResource::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FStreamableTextureResource.
IsProxy()
virtual bool FTexture2DResource::IsProxy () const inline override virtual
Returns true if the resource is proxying another one.
Reimplemented from FTextureResource.
Definition at line 44 of file Texture2DResource.h.
References ProxiedResource.
WarnRequiresTightPackedMip()
void FTexture2DResource::WarnRequiresTightPackedMip (int32 SizeX, int32 SizeY, EPixelFormat PixelFormat, uint32 Pitch) static
References FStreamableTextureResource::PixelFormat, FStreamableTextureResource::SizeX, and FStreamableTextureResource::SizeY.
Friends And Related Symbol Documentation
FTexture2DMipAllocator_Virtual
friend class FTexture2DMipAllocator_Virtual friend
Definition at line 67 of file Texture2DResource.h.
References FTexture2DMipAllocator_Virtual.
Referenced by FTexture2DMipAllocator_Virtual.
FTexture2DUpdate
friend class FTexture2DUpdate friend
Definition at line 66 of file Texture2DResource.h.
References FTexture2DUpdate.
Referenced by FTexture2DUpdate.
UTexture2D
friend class UTexture2D friend
Texture streaming command classes that need to be friends in order to call Update/FinalizeMipCount.
Definition at line 65 of file Texture2DResource.h.
References UTexture2D.
Referenced by FTexture2DResource(), FTexture2DResource(), CacheSamplerStateInitializer(), and UTexture2D.
Field Documentation
MipData
TArray<void*, TInlineAllocator<MAX_TEXTURE_MIP_COUNT> > FTexture2DResource::MipData private
Local copy/ cache of mip data between creation and first call to InitRHI.
Definition at line 76 of file Texture2DResource.h.
MipDataSize
TArray<int64, TInlineAllocator<MAX_TEXTURE_MIP_COUNT> > FTexture2DResource::MipDataSize private
Definition at line 77 of file Texture2DResource.h.
ProxiedResource
const FTexture2DResource* const FTexture2DResource::ProxiedResource = nullptr private
Another resource being proxied by this one.
Definition at line 73 of file Texture2DResource.h.
Referenced by IsProxy().
ResourceMem
FTexture2DResourceMem* FTexture2DResource::ResourceMem private
Resource memory allocated by the owner for serialize bulk mip data into.
Definition at line 70 of file Texture2DResource.h.
The documentation for this class was generated from the following file:
Texture2DResource.h