Unreal Engine 5.6 C++ API: TRDGHandle< LocalObjectType, LocalIndexType > Class Template Reference
TRDGHandle< LocalObjectType, LocalIndexType > Class Template Reference
HANDLE UTILITIES.
#include "RenderGraphDefinitions.h"
Public Types
using IndexType = LocalIndexType
using ObjectType = LocalObjectType
Public Member Functions
TRDGHandle ()=default
TRDGHandle (uint32 InIndex)
FORCEINLINE IndexType GetIndex () const
FORCEINLINE IndexType GetIndexUnchecked () const
FORCEINLINE bool IsNull () const
FORCEINLINE bool IsValid () const
FORCEINLINE bool operator!= (TRDGHandle Other) const
FORCEINLINE TRDGHandle operator+ (int32 Add) const
FORCEINLINE TRDGHandle & operator++ ()
FORCEINLINE TRDGHandle & operator+= (int32 Increment)
FORCEINLINE TRDGHandle operator- (int32 Subtract) const
FORCEINLINE TRDGHandle & operator-- ()
FORCEINLINE TRDGHandle & operator-= (int32 Decrement)
FORCEINLINE bool operator< (TRDGHandle Other) const
FORCEINLINE bool operator<= (TRDGHandle Other) const
FORCEINLINE bool operator== (TRDGHandle Other) const
FORCEINLINE bool operator> (TRDGHandle Other) const
FORCEINLINE bool operator>= (TRDGHandle Other) const
Static Public Member Functions
static FORCEINLINE TRDGHandle Max (TRDGHandle A, TRDGHandle B)
static FORCEINLINE TRDGHandle Min (TRDGHandle A, TRDGHandle B)
Static Public Attributes
static const TRDGHandle Null
Private Attributes
IndexType Index = kNullIndex
Static Private Attributes
static const IndexType kNullIndex = TNumericLimits<IndexType>::Max()
Friends
FORCEINLINE uint32 GetTypeHash (TRDGHandle Handle)
Detailed Description
template<typename LocalObjectType, typename LocalIndexType>
class TRDGHandle< LocalObjectType, LocalIndexType >
HANDLE UTILITIES.
Handle helper class for internal tracking of RDG types.
Definition at line 342 of file RenderGraphDefinitions.h.
Member Typedef Documentation
IndexType
template<typename LocalObjectType, typename LocalIndexType> using TRDGHandle< LocalObjectType, LocalIndexType >::IndexType = LocalIndexType
Definition at line 346 of file RenderGraphDefinitions.h.
ObjectType
template<typename LocalObjectType, typename LocalIndexType> using TRDGHandle< LocalObjectType, LocalIndexType >::ObjectType = LocalObjectType
Definition at line 345 of file RenderGraphDefinitions.h.
Constructor & Destructor Documentation
TRDGHandle() [1/2]
template<typename LocalObjectType, typename LocalIndexType> TRDGHandle< LocalObjectType, LocalIndexType >::TRDGHandle () default
TRDGHandle() [2/2]
template<typename LocalObjectType, typename LocalIndexType> TRDGHandle< LocalObjectType, LocalIndexType >::TRDGHandle (uint32 InIndex) inline explicit
Definition at line 352 of file RenderGraphDefinitions.h.
Member Function Documentation
GetIndex()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE IndexType TRDGHandle< LocalObjectType, LocalIndexType >::GetIndex () const inline
Definition at line 358 of file RenderGraphDefinitions.h.
Referenced by FRDGBuilder::FCollectResourceOp::Allocate(), FRDGBuilder::FCollectResourceOp::Allocate(), FRDGBuilder::FCollectResourceOp::Deallocate(), and FRDGBuilder::FCollectResourceOp::Deallocate().
GetIndexUnchecked()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE IndexType TRDGHandle< LocalObjectType, LocalIndexType >::GetIndexUnchecked () const inline
Definition at line 359 of file RenderGraphDefinitions.h.
IsNull()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::IsNull () const inline
Definition at line 360 of file RenderGraphDefinitions.h.
IsValid()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::IsValid () const inline
Definition at line 361 of file RenderGraphDefinitions.h.
Referenced by TRDGHandle< FSocket, uint32 >::GetIndex(), TRDGHandle< FSocket, uint32 >::operator++(), TRDGHandle< FSocket, uint32 >::operator--(), TRDGHandle< FSocket, uint32 >::operator<(), TRDGHandle< FSocket, uint32 >::operator<=(), TRDGHandle< FSocket, uint32 >::operator>(), and TRDGHandle< FSocket, uint32 >::operator>=().
Max()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle TRDGHandle< LocalObjectType, LocalIndexType >::Max (TRDGHandle< LocalObjectType, LocalIndexType > A, TRDGHandle< LocalObjectType, LocalIndexType > B) inline static
Definition at line 419 of file RenderGraphDefinitions.h.
Min()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle TRDGHandle< LocalObjectType, LocalIndexType >::Min (TRDGHandle< LocalObjectType, LocalIndexType > A, TRDGHandle< LocalObjectType, LocalIndexType > B) inline static
Definition at line 412 of file RenderGraphDefinitions.h.
operator!=()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::operator!= (TRDGHandle< LocalObjectType, LocalIndexType > Other) const inline
Definition at line 363 of file RenderGraphDefinitions.h.
operator+()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle TRDGHandle< LocalObjectType, LocalIndexType >::operator+ (int32 Add) const inline
Definition at line 390 of file RenderGraphDefinitions.h.
operator++()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle & TRDGHandle< LocalObjectType, LocalIndexType >::operator++ () inline
Definition at line 397 of file RenderGraphDefinitions.h.
operator+=()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle & TRDGHandle< LocalObjectType, LocalIndexType >::operator+= (int32 Increment) inline
Definition at line 369 of file RenderGraphDefinitions.h.
operator-()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle TRDGHandle< LocalObjectType, LocalIndexType >::operator- (int32 Subtract) const inline
Definition at line 383 of file RenderGraphDefinitions.h.
operator--()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle & TRDGHandle< LocalObjectType, LocalIndexType >::operator-- () inline
Definition at line 404 of file RenderGraphDefinitions.h.
operator-=()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE TRDGHandle & TRDGHandle< LocalObjectType, LocalIndexType >::operator-= (int32 Decrement) inline
Definition at line 376 of file RenderGraphDefinitions.h.
operator<()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::operator< (TRDGHandle< LocalObjectType, LocalIndexType > Other) const inline
Definition at line 366 of file RenderGraphDefinitions.h.
operator<=()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::operator<= (TRDGHandle< LocalObjectType, LocalIndexType > Other) const inline
Definition at line 364 of file RenderGraphDefinitions.h.
operator==()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::operator== (TRDGHandle< LocalObjectType, LocalIndexType > Other) const inline
Definition at line 362 of file RenderGraphDefinitions.h.
operator>()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::operator> (TRDGHandle< LocalObjectType, LocalIndexType > Other) const inline
Definition at line 367 of file RenderGraphDefinitions.h.
operator>=()
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE bool TRDGHandle< LocalObjectType, LocalIndexType >::operator>= (TRDGHandle< LocalObjectType, LocalIndexType > Other) const inline
Definition at line 365 of file RenderGraphDefinitions.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename LocalObjectType, typename LocalIndexType> FORCEINLINE uint32 GetTypeHash (TRDGHandle< LocalObjectType, LocalIndexType > Handle) friend
Definition at line 429 of file RenderGraphDefinitions.h.
Field Documentation
Index
template<typename LocalObjectType, typename LocalIndexType> IndexType TRDGHandle< LocalObjectType, LocalIndexType >::Index = kNullIndex private
Definition at line 427 of file RenderGraphDefinitions.h.
kNullIndex
template<typename LocalObjectType, typename LocalIndexType> const IndexType TRDGHandle< LocalObjectType, LocalIndexType >::kNullIndex = TNumericLimits<IndexType>::Max() static private
Definition at line 426 of file RenderGraphDefinitions.h.
Null
template<typename LocalObjectType, typename LocalIndexType> const TRDGHandle TRDGHandle< LocalObjectType, LocalIndexType >::Null static
Definition at line 348 of file RenderGraphDefinitions.h.
The documentation for this class was generated from the following file:
RenderGraphDefinitions.h