Unreal Engine 5.6 C++ API: FStructuredArchive Class Reference
FStructuredArchive Class Reference
Manages the state of an underlying FStructuredArchiveFormatter, and provides a consistent API for reading and writing to a structured archive.
#include "StructuredArchive.h"
Public Types
using FArray = FStructuredArchiveArray
using FMap = FStructuredArchiveMap
using FRecord = FStructuredArchiveRecord
using FSlot = FStructuredArchiveSlot
using FStream = FStructuredArchiveStream
Public Member Functions
FStructuredArchive (const FStructuredArchive &)=delete
FORCEINLINE FStructuredArchive (FArchiveFormatterType &InFormatter)
Constructor.
FORCEINLINE ~FStructuredArchive ()
Default destructor.
FORCEINLINE void Close ()
Flushes any remaining scope to the underlying formatter and closes the archive.
FORCEINLINE const FArchiveState & GetArchiveState () const
Gets the archiving state.
FORCEINLINE FArchive & GetUnderlyingArchive () const
Gets the serialization context from the underlying archive.
FORCEINLINE FStructuredArchiveSlot Open ()
Start writing to the archive, and gets an interface to the root slot.
FStructuredArchive & operator= (const FStructuredArchive &)=delete
Private Attributes
FArchiveFormatterType & Formatter
Reference to the formatter that actually writes out the data to the underlying archive.
friend FStructuredArchiveArray
friend FStructuredArchiveMap
friend FStructuredArchiveRecord
friend FStructuredArchiveSlot
friend FStructuredArchiveStream
Friends
class FStructuredArchiveChildReader
UE::StructuredArchive::Private::FElementId UE::StructuredArchive::Private::GetCurrentSlotElementIdImpl (FStructuredArchive &Ar)
FArchiveFormatterType & UE::StructuredArchive::Private::GetFormatterImpl (FStructuredArchive &Ar)
Detailed Description
Manages the state of an underlying FStructuredArchiveFormatter, and provides a consistent API for reading and writing to a structured archive.
Both reading and writing to the archive are forward only from an interface point of view. There is no point at which it is possible to require seeking.
Definition at line 56 of file StructuredArchive.h.
Member Typedef Documentation
FArray
using FStructuredArchive::FArray = FStructuredArchiveArray
Definition at line 67 of file StructuredArchive.h.
FMap
using FStructuredArchive::FMap = FStructuredArchiveMap
Definition at line 69 of file StructuredArchive.h.
FRecord
using FStructuredArchive::FRecord = FStructuredArchiveRecord
Definition at line 66 of file StructuredArchive.h.
FSlot
using FStructuredArchive::FSlot = FStructuredArchiveSlot
Definition at line 65 of file StructuredArchive.h.
FStream
using FStructuredArchive::FStream = FStructuredArchiveStream
Definition at line 68 of file StructuredArchive.h.
Constructor & Destructor Documentation
FStructuredArchive() [1/2]
FORCEINLINE FStructuredArchive::FStructuredArchive (FArchiveFormatterType & InFormatter) explicit
Constructor.
Parameters
InFormatter Formatter for the archive data
Definition at line 212 of file StructuredArchive.h.
References FORCEINLINE, and Formatter.
Referenced by FStructuredArchive(), operator=(), UE::StructuredArchive::Private::GetCurrentSlotElementIdImpl, and UE::StructuredArchive::Private::GetFormatterImpl.
~FStructuredArchive()
FORCEINLINE FStructuredArchive::~FStructuredArchive ()
Default destructor.
Closes the archive.
Definition at line 217 of file StructuredArchive.h.
References FORCEINLINE.
FStructuredArchive() [2/2]
FStructuredArchive::FStructuredArchive (const FStructuredArchive &) delete
References FStructuredArchive().
Member Function Documentation
Close()
FORCEINLINE void FStructuredArchive::Close ()
Flushes any remaining scope to the underlying formatter and closes the archive.
Definition at line 226 of file StructuredArchive.h.
References FORCEINLINE.
GetArchiveState()
FORCEINLINE const FArchiveState & FStructuredArchive::GetArchiveState () const inline
Gets the archiving state.
Definition at line 104 of file StructuredArchive.h.
References FORCEINLINE, FArchive::GetArchiveState(), and GetUnderlyingArchive().
GetUnderlyingArchive()
FORCEINLINE FArchive & FStructuredArchive::GetUnderlyingArchive () const inline
Gets the serialization context from the underlying archive.
Definition at line 96 of file StructuredArchive.h.
References FORCEINLINE, and Formatter.
Referenced by GetArchiveState().
Open()
FORCEINLINE FStructuredArchiveSlot FStructuredArchive::Open ()
Start writing to the archive, and gets an interface to the root slot.
Definition at line 221 of file StructuredArchive.h.
References FORCEINLINE, and FStructuredArchiveSlot.
operator=()
FStructuredArchive & FStructuredArchive::operator= (const FStructuredArchive &) delete
References FStructuredArchive().
Friends And Related Symbol Documentation
FStructuredArchiveChildReader
friend class FStructuredArchiveChildReader friend
Definition at line 113 of file StructuredArchive.h.
References FStructuredArchiveChildReader.
Referenced by FStructuredArchiveChildReader.
UE::StructuredArchive::Private::GetCurrentSlotElementIdImpl
UE::StructuredArchive::Private::FElementId UE::StructuredArchive::Private::GetCurrentSlotElementIdImpl (FStructuredArchive & Ar) friend
References FStructuredArchive(), and Ar.
UE::StructuredArchive::Private::GetFormatterImpl
FArchiveFormatterType & UE::StructuredArchive::Private::GetFormatterImpl (FStructuredArchive & Ar) friend
References FStructuredArchive(), and Ar.
Field Documentation
Formatter
FArchiveFormatterType& FStructuredArchive::Formatter private
Reference to the formatter that actually writes out the data to the underlying archive.
Definition at line 120 of file StructuredArchive.h.
Referenced by FStructuredArchive(), FStructuredArchiveChildReader::FStructuredArchiveChildReader(), and GetUnderlyingArchive().
FStructuredArchiveArray
friend FStructuredArchive::FStructuredArchiveArray private
Definition at line 60 of file StructuredArchive.h.
FStructuredArchiveMap
friend FStructuredArchive::FStructuredArchiveMap private
Definition at line 62 of file StructuredArchive.h.
FStructuredArchiveRecord
friend FStructuredArchive::FStructuredArchiveRecord private
Definition at line 59 of file StructuredArchive.h.
FStructuredArchiveSlot
friend FStructuredArchive::FStructuredArchiveSlot private
Definition at line 58 of file StructuredArchive.h.
Referenced by Open().
FStructuredArchiveStream
friend FStructuredArchive::FStructuredArchiveStream private
Definition at line 61 of file StructuredArchive.h.
The documentation for this class was generated from the following file:
StructuredArchive.h