Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelListIterator Struct Reference
UE::Sequencer::FViewModelListIterator Struct Reference
Iterates all models contained in the specified list chain.
#include "ViewModelIterators.h"
Public Member Functions
FViewModelListIterator (const FViewModelListHead *InListHead, EViewModelListType InFilter=EViewModelListType::Everything)
FViewModelListIterator (const TSharedPtr< FViewModel > &InModel, EViewModelListType InFilter=EViewModelListType::Everything)
FViewModelListIterator (EViewModelListType InFilter=EViewModelListType::Everything)
FORCEINLINE FViewModelListIterator begin () const
FORCEINLINE FViewModelListIterator end () const
template<typename ValueType, typename ProjectionType>
FViewModelPtr FindBy (const ValueType &Value, ProjectionType Proj) const
Linearly search through this iterator to find a predicate using a projection For example, to find the first item that has children of its own: const bool bHasChildren = true; Model->GetChildren().FindBy(bHasChildren, &FViewModel::HasChildren)
FORCEINLINE FViewModelPtr GetCurrentItem () const
FORCEINLINE operator bool () const
FORCEINLINE const FViewModelPtr & operator* () const
void operator++ ()
FORCEINLINE FViewModel * operator-> () const
TArray< FViewModelPtr > ToArray () const
Return the remaining items in this iterator as an array The state of this iterator remains unchanged.
void ToArray (TArray< FViewModelPtr > &OutArray) const
Populate the specified array with the remaining items in this iterator The state of this iterator remains unchanged.
Private Member Functions
void FindNextValidIterator ()
Private Attributes
EViewModelListType Filter
FViewModelSubListIterator ListIterator
const FViewModelListHead * NextList
Friends
FORCEINLINE friend bool operator!= (const FViewModelListIterator &A, const FViewModelListIterator &B)
Detailed Description
Iterates all models contained in the specified list chain.
Definition at line 118 of file ViewModelIterators.h.
Constructor & Destructor Documentation
FViewModelListIterator() [1/3]
UE::Sequencer::FViewModelListIterator::FViewModelListIterator (EViewModelListType InFilter = EViewModelListType::Everything) inline
Definition at line 120 of file ViewModelIterators.h.
References UE::Sequencer::Everything, Filter, and NextList.
Referenced by begin(), end(), FindBy(), operator!=, and ToArray().
FViewModelListIterator() [2/3]
UE::Sequencer::FViewModelListIterator::FViewModelListIterator (const TSharedPtr< FViewModel > & InModel, EViewModelListType InFilter = EViewModelListType::Everything) inline explicit
Definition at line 125 of file ViewModelIterators.h.
References UE::Sequencer::Everything, Filter, FindNextValidIterator(), and NextList.
FViewModelListIterator() [3/3]
UE::Sequencer::FViewModelListIterator::FViewModelListIterator (const FViewModelListHead * InListHead, EViewModelListType InFilter = EViewModelListType::Everything) inline explicit
Definition at line 132 of file ViewModelIterators.h.
References UE::Sequencer::Everything, Filter, FindNextValidIterator(), and NextList.
Member Function Documentation
begin()
FORCEINLINE FViewModelListIterator UE::Sequencer::FViewModelListIterator::begin () const inline
Definition at line 154 of file ViewModelIterators.h.
References FViewModelListIterator(), and FORCEINLINE.
end()
FORCEINLINE FViewModelListIterator UE::Sequencer::FViewModelListIterator::end () const inline
Definition at line 155 of file ViewModelIterators.h.
References FViewModelListIterator(), and FORCEINLINE.
FindBy()
template<typename ValueType, typename ProjectionType> FViewModelPtr UE::Sequencer::FViewModelListIterator::FindBy (const ValueType & Value, ProjectionType Proj) const inline
Linearly search through this iterator to find a predicate using a projection For example, to find the first item that has children of its own: const bool bHasChildren = true; Model->GetChildren().FindBy(bHasChildren, &FViewModel::HasChildren)
Definition at line 187 of file ViewModelIterators.h.
References FViewModelListIterator(), Invoke(), Item, and Value.
FindNextValidIterator()
void UE::Sequencer::FViewModelListIterator::FindNextValidIterator () inline private
Definition at line 202 of file ViewModelIterators.h.
References EnumHasAnyFlags(), Filter, ListIterator, and NextList.
Referenced by FViewModelListIterator(), FViewModelListIterator(), and operator++().
GetCurrentItem()
FORCEINLINE FViewModelPtr UE::Sequencer::FViewModelListIterator::GetCurrentItem () const inline
Definition at line 146 of file ViewModelIterators.h.
References FORCEINLINE, and ListIterator.
operator bool()
FORCEINLINE UE::Sequencer::FViewModelListIterator::operator bool () const inline explicit
Definition at line 143 of file ViewModelIterators.h.
References FORCEINLINE, and ListIterator.
operator*()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FViewModelListIterator::operator* () const inline
Definition at line 145 of file ViewModelIterators.h.
References FORCEINLINE, and ListIterator.
operator++()
void UE::Sequencer::FViewModelListIterator::operator++ () inline
Definition at line 148 of file ViewModelIterators.h.
References FindNextValidIterator(), and ListIterator.
operator->()
FORCEINLINE FViewModel * UE::Sequencer::FViewModelListIterator::operator-> () const inline
Definition at line 144 of file ViewModelIterators.h.
References FORCEINLINE, and ListIterator.
ToArray() [1/2]
TArray< FViewModelPtr > UE::Sequencer::FViewModelListIterator::ToArray () const inline
Return the remaining items in this iterator as an array The state of this iterator remains unchanged.
Definition at line 173 of file ViewModelIterators.h.
References ToArray().
Referenced by ToArray().
ToArray() [2/2]
void UE::Sequencer::FViewModelListIterator::ToArray (TArray< FViewModelPtr > & OutArray) const inline
Populate the specified array with the remaining items in this iterator The state of this iterator remains unchanged.
Definition at line 161 of file ViewModelIterators.h.
References FViewModelListIterator(), and TArray< InElementType, InAllocatorType >::Add().
Friends And Related Symbol Documentation
operator!=
FORCEINLINE friend bool operator!= (const FViewModelListIterator & A, const FViewModelListIterator & B) friend
Definition at line 139 of file ViewModelIterators.h.
References FViewModelListIterator(), A, B, and FORCEINLINE.
Field Documentation
Filter
EViewModelListType UE::Sequencer::FViewModelListIterator::Filter private
Definition at line 224 of file ViewModelIterators.h.
Referenced by FViewModelListIterator(), FViewModelListIterator(), FViewModelListIterator(), and FindNextValidIterator().
ListIterator
FViewModelSubListIterator UE::Sequencer::FViewModelListIterator::ListIterator private
Definition at line 223 of file ViewModelIterators.h.
Referenced by FindNextValidIterator(), GetCurrentItem(), operator bool(), operator*(), operator++(), and operator->().
NextList
const FViewModelListHead* UE::Sequencer::FViewModelListIterator::NextList private
Definition at line 222 of file ViewModelIterators.h.
Referenced by FViewModelListIterator(), FViewModelListIterator(), FViewModelListIterator(), and FindNextValidIterator().
The documentation for this struct was generated from the following file:
ViewModelIterators.h