Unreal Engine 5.6 C++ API: UE::AnimNext::IAlphaInputArgs Struct Reference
UE::AnimNext::IAlphaInputArgs Struct Reference
IAlphaInputArgs.
#include "IAlphaInputArgs.h"
Public Member Functions
DECLARE_ANIM_TRAIT_INTERFACE (IAlphaInputArgs) ANIMNEXTANIMGRAPH_API virtual FAlphaInputTraitArgs Get(const FExecutionContext &Context
Returns the args captured by this trait interface.
virtual ANIMNEXTANIMGRAPH_API FName GetAlphaCurveName (const FExecutionContext &Context, const TTraitBinding< IAlphaInputArgs > &Binding) const
Returns current alpha curve name, if any.
virtual ANIMNEXTANIMGRAPH_API EAnimAlphaInputType GetAlphaInputType (const FExecutionContext &Context, const TTraitBinding< IAlphaInputArgs > &Binding) const
Returns current alpha input type.
virtual ANIMNEXTANIMGRAPH_API float GetCurrentAlphaValue (const FExecutionContext &Context, const TTraitBinding< IAlphaInputArgs > &Binding) const
Returns alpha value for current input.
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayName () const override
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayShortName () const override
virtual ANIMNEXTANIMGRAPH_API TFunction< float(float)> GetInputScaleBiasClampCallback (const FExecutionContext &Context, const TTraitBinding< IAlphaInputArgs > &Binding) const
Returns callback to clamp alpha values, typically used for curve sampling Note: Callback may perform a deferred write to alpha input instance data.
Public Member Functions inherited from UE::AnimNext::ITraitInterface
virtual ~ITraitInterface ()
virtual FTraitInterfaceUID GetInterfaceUID () const
virtual bool IsInternal () const
Data Fields
const TTraitBinding< IAlphaInputArgs > &Binding const
Additional Inherited Members
Static Public Attributes inherited from UE::AnimNext::ITraitInterface
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
IAlphaInputArgs.
This interface exposes alpha input args & convience methods for operating on those args
Alpha input is typically a curve / float / bool that controls the strength of some other trait. Ex: 0 - no effect, 1 - full effect.
Definition at line 65 of file IAlphaInputArgs.h.
Member Function Documentation
DECLARE_ANIM_TRAIT_INTERFACE()
UE::AnimNext::IAlphaInputArgs::DECLARE_ANIM_TRAIT_INTERFACE (IAlphaInputArgs) const &
Returns the args captured by this trait interface.
Note: We return a copy as some implementations may return a temp struct & our return type is relatively cheap to copy.
GetAlphaCurveName()
virtual ANIMNEXTANIMGRAPH_API FName UE::AnimNext::IAlphaInputArgs::GetAlphaCurveName (const FExecutionContext & Context, const TTraitBinding< IAlphaInputArgs > & Binding) const virtual
Returns current alpha curve name, if any.
References const, GetAlphaCurveName(), and UE_API.
Referenced by GetAlphaCurveName().
GetAlphaInputType()
virtual ANIMNEXTANIMGRAPH_API EAnimAlphaInputType UE::AnimNext::IAlphaInputArgs::GetAlphaInputType (const FExecutionContext & Context, const TTraitBinding< IAlphaInputArgs > & Binding) const virtual
Returns current alpha input type.
References const, GetAlphaInputType(), and UE_API.
Referenced by GetAlphaInputType().
GetCurrentAlphaValue()
virtual ANIMNEXTANIMGRAPH_API float UE::AnimNext::IAlphaInputArgs::GetCurrentAlphaValue (const FExecutionContext & Context, const TTraitBinding< IAlphaInputArgs > & Binding) const virtual
Returns alpha value for current input.
For curve types this will be 1.0, so curves should use trait args to resolve alpha in a task.
Parameters
DeltaTime - Time since last API call using DeltaTime (Ex: Time since last 'ComputeAlphaValue' call).
References const, GetCurrentAlphaValue(), and UE_API.
Referenced by GetCurrentAlphaValue().
GetDisplayName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IAlphaInputArgs::GetDisplayName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetDisplayShortName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IAlphaInputArgs::GetDisplayShortName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetInputScaleBiasClampCallback()
virtual ANIMNEXTANIMGRAPH_API TFunction< float(float)> UE::AnimNext::IAlphaInputArgs::GetInputScaleBiasClampCallback (const FExecutionContext & Context, const TTraitBinding< IAlphaInputArgs > & Binding) const virtual
Returns callback to clamp alpha values, typically used for curve sampling Note: Callback may perform a deferred write to alpha input instance data.
References const, GetInputScaleBiasClampCallback(), and UE_API.
Referenced by GetInputScaleBiasClampCallback().
Field Documentation
const
const TTraitBinding<IAlphaInputArgs>& Binding UE::AnimNext::IAlphaInputArgs::const
Definition at line 73 of file IAlphaInputArgs.h.
Referenced by GetAlphaCurveName(), GetAlphaInputType(), GetCurrentAlphaValue(), and GetInputScaleBiasClampCallback().
The documentation for this struct was generated from the following file:
IAlphaInputArgs.h