Unreal Engine 5.6 C++ API: UE::MovieScene::FDoubleVectorPropertyTraits Struct Reference
UE::MovieScene::FDoubleVectorPropertyTraits Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Public Types
using MetaDataType = TPropertyMetaData<FVectorPropertyMetaData>
using StorageType = FDoubleIntermediateVector
Static Public Member Functions
static FDoubleIntermediateVector CombineComposites (FVectorPropertyMetaData MetaData, double InX, double InY, double InZ, double InW)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor &BaseCustomAccessor, FDoubleIntermediateVector &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, const FName &PropertyPath, StorageType &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings *PropertyBindings, FDoubleIntermediateVector &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, FDoubleIntermediateVector &OutValue)
static void SetObjectPropertyValue (UObject *InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor &BaseCustomAccessor, const FDoubleIntermediateVector &InValue)
static void SetObjectPropertyValue (UObject *InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings *PropertyBindings, const FDoubleIntermediateVector &InValue)
static void SetObjectPropertyValue (UObject *InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, const FDoubleIntermediateVector &InValue)
Detailed Description
Definition at line 358 of file MovieSceneTracksComponentTypes.h.
Member Typedef Documentation
MetaDataType
using UE::MovieScene::FDoubleVectorPropertyTraits::MetaDataType = TPropertyMetaData<FVectorPropertyMetaData>
Definition at line 361 of file MovieSceneTracksComponentTypes.h.
StorageType
using UE::MovieScene::FDoubleVectorPropertyTraits::StorageType = FDoubleIntermediateVector
Definition at line 360 of file MovieSceneTracksComponentTypes.h.
Member Function Documentation
CombineComposites()
FDoubleIntermediateVector UE::MovieScene::FDoubleVectorPropertyTraits::CombineComposites (FVectorPropertyMetaData MetaData, double InX, double InY, double InZ, double InW) inline static
Definition at line 424 of file MovieSceneTracksComponentTypes.h.
References MetaData.
GetObjectPropertyValue() [1/4]
void UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor & BaseCustomAccessor, FDoubleIntermediateVector & OutValue) inline static
Definition at line 363 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions, and MetaData.
GetObjectPropertyValue() [2/4]
void UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, const FName & PropertyPath, StorageType & OutValue) inline static
Definition at line 386 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), and MetaData.
GetObjectPropertyValue() [3/4]
void UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings * PropertyBindings, FDoubleIntermediateVector & OutValue) inline static
Definition at line 377 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), and MetaData.
GetObjectPropertyValue() [4/4]
void UE::MovieScene::FDoubleVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, FDoubleIntermediateVector & OutValue) inline static
Definition at line 368 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), and MetaData.
SetObjectPropertyValue() [1/3]
void UE::MovieScene::FDoubleVectorPropertyTraits::SetObjectPropertyValue (UObject * InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor & BaseCustomAccessor, const FDoubleIntermediateVector & InValue) inline static
Definition at line 396 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions, and MetaData.
SetObjectPropertyValue() [2/3]
void UE::MovieScene::FDoubleVectorPropertyTraits::SetObjectPropertyValue (UObject * InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings * PropertyBindings, const FDoubleIntermediateVector & InValue) inline static
Definition at line 412 of file MovieSceneTracksComponentTypes.h.
References checkf, MetaData, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue(), and TEXT.
SetObjectPropertyValue() [3/3]
void UE::MovieScene::FDoubleVectorPropertyTraits::SetObjectPropertyValue (UObject * InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, const FDoubleIntermediateVector & InValue) inline static
Definition at line 401 of file MovieSceneTracksComponentTypes.h.
References checkf, MetaData, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue(), and TEXT.
The documentation for this struct was generated from the following file:
MovieSceneTracksComponentTypes.h