Unreal Engine 5.6 C++ Documentation: FRootMotionSourceSettings Struct Reference
FRootMotionSourceSettings Struct Reference
Structure for RootMotionSource option flags (used for convenience instead of having to manually manipulate flag bitfields)
#include <UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h>
Public Member Functions
FRootMotionSourceSettings ()
void Clear ()
void SetFlag (ERootMotionSourceSettingsFlags Flag)
void UnSetFlag (ERootMotionSourceSettingsFlags Flag)
bool HasFlag (ERootMotionSourceSettingsFlags Flag) const
FRootMotionSourceSettings & operator+= (const FRootMotionSourceSettings &Other)
Public Attributes
uint8 Flags
Detailed Description
Structure for RootMotionSource option flags (used for convenience instead of having to manually manipulate flag bitfields)
Definition at line 119 of file RootMotionSource.h.
Constructor & Destructor Documentation
FRootMotionSourceSettings()
FRootMotionSourceSettings::FRootMotionSourceSettings ()
References FRootMotionSourceSettings().
Member Function Documentation
Clear()
void FRootMotionSourceSettings::Clear ()
References Clear().
HasFlag()
bool FRootMotionSourceSettings::HasFlag (ERootMotionSourceSettingsFlags Flag) const
References ERootMotionSourceSettingsFlags, and HasFlag().
operator+=()
FRootMotionSourceSettings & FRootMotionSourceSettings::operator+= (const FRootMotionSourceSettings & Other)
References FRootMotionSourceSettings().
SetFlag()
void FRootMotionSourceSettings::SetFlag (ERootMotionSourceSettingsFlags Flag)
References ERootMotionSourceSettingsFlags, and SetFlag().
UnSetFlag()
void FRootMotionSourceSettings::UnSetFlag (ERootMotionSourceSettingsFlags Flag)
References ERootMotionSourceSettingsFlags, and UnSetFlag().
Member Data Documentation
Flags
uint8 FRootMotionSourceSettings::Flags
Definition at line 125 of file RootMotionSource.h.
The documentation for this struct was generated from the following file:
UE_5.6/Engine/Source/Runtime/Engine/Classes/GameFramework/RootMotionSource.h