Unreal Engine 5.6 C++ API: UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType > Class Template Reference
UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType > Class Template Reference
Public Member Functions
void Lock ()
TArray< FTaskBase *, AllocatorType > PopAll ()
void Push (FTaskBase *Prerequisite)
void PushNoLock (FTaskBase *Prerequisite)
void Unlock ()
Private Attributes
UE::FMutex Mutex { UE::AcquireLock }
TArray< FTaskBase *, AllocatorType > Prerequisites
Detailed Description
template<typename AllocatorType = FDefaultAllocator>
class UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >
Definition at line 743 of file TaskPrivate.h.
Member Function Documentation
Lock()
template<typename AllocatorType = FDefaultAllocator> void UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::Lock () inline
Definition at line 766 of file TaskPrivate.h.
References Mutex.
Referenced by PopAll(), and Push().
PopAll()
template<typename AllocatorType = FDefaultAllocator> TArray< FTaskBase *, AllocatorType > UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::PopAll () inline
Definition at line 759 of file TaskPrivate.h.
References Lock(), MoveTemp(), Mutex, PopAll(), Prerequisites, and TASKGRAPH_VERBOSE_EVENT_SCOPE.
Referenced by PopAll().
Push()
template<typename AllocatorType = FDefaultAllocator> void UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::Push (FTaskBase * Prerequisite) inline
Definition at line 746 of file TaskPrivate.h.
References UE::Tasks::Private::FTaskBase::FTaskBase(), Lock(), Mutex, Prerequisites, Push(), and TASKGRAPH_VERBOSE_EVENT_SCOPE.
Referenced by Push().
PushNoLock()
template<typename AllocatorType = FDefaultAllocator> void UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::PushNoLock (FTaskBase * Prerequisite) inline
Definition at line 753 of file TaskPrivate.h.
References UE::Tasks::Private::FTaskBase::FTaskBase(), Prerequisites, PushNoLock(), and TASKGRAPH_VERBOSE_EVENT_SCOPE.
Referenced by PushNoLock().
Unlock()
template<typename AllocatorType = FDefaultAllocator> void UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::Unlock () inline
Definition at line 771 of file TaskPrivate.h.
References Mutex.
Field Documentation
Mutex
template<typename AllocatorType = FDefaultAllocator> UE::FMutex UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::Mutex { UE::AcquireLock } private
Definition at line 777 of file TaskPrivate.h.
Referenced by Lock(), PopAll(), Push(), and Unlock().
Prerequisites
template<typename AllocatorType = FDefaultAllocator> TArray<FTaskBase*, AllocatorType> UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::Prerequisites private
Definition at line 776 of file TaskPrivate.h.
Referenced by PopAll(), Push(), and PushNoLock().
The documentation for this class was generated from the following file:
TaskPrivate.h