Unreal Engine 5.6 C++ API: FSpawnableRestoreState Struct Reference
FSpawnableRestoreState Struct Reference
#include "MovieSceneToolHelpers.h"
Public Member Functions
FSpawnableRestoreState (UMovieScene *MovieScene, TSharedPtr< UE::MovieScene::FSharedPlaybackState > InSharedPlaybackState)
~FSpawnableRestoreState ()
UE_DEPRECATED (5.5, "This constructor is deprecated in favor of passing in shared playback state") FSpawnableRestoreState(UMovieScene *MovieScene)
Data Fields
bool bWasChanged
TSharedPtr< UE::MovieScene::FSharedPlaybackState > SharedPlaybackState
TMap< FGuid, ESpawnOwnership > SpawnOwnershipMap
TWeakObjectPtr< UMovieScene > WeakMovieScene
Detailed Description
Definition at line 1185 of file MovieSceneToolHelpers.h.
Constructor & Destructor Documentation
FSpawnableRestoreState()
FSpawnableRestoreState::FSpawnableRestoreState (UMovieScene * MovieScene, TSharedPtr< UE::MovieScene::FSharedPlaybackState > InSharedPlaybackState)
References FSpawnableRestoreState().
Referenced by FSpawnableRestoreState(), ~FSpawnableRestoreState(), and UE_DEPRECATED().
~FSpawnableRestoreState()
FSpawnableRestoreState::~FSpawnableRestoreState ()
References FSpawnableRestoreState().
Member Function Documentation
UE_DEPRECATED()
FSpawnableRestoreState::UE_DEPRECATED (5. 5, "This constructor is deprecated in favor of passing in shared playback state")
References FSpawnableRestoreState().
Field Documentation
bWasChanged
bool FSpawnableRestoreState::bWasChanged
Definition at line 1193 of file MovieSceneToolHelpers.h.
SharedPlaybackState
TSharedPtr<UE::MovieScene::FSharedPlaybackState> FSpawnableRestoreState::SharedPlaybackState
Definition at line 1196 of file MovieSceneToolHelpers.h.
SpawnOwnershipMap
TMap<FGuid, ESpawnOwnership> FSpawnableRestoreState::SpawnOwnershipMap
Definition at line 1194 of file MovieSceneToolHelpers.h.
WeakMovieScene
TWeakObjectPtr<UMovieScene> FSpawnableRestoreState::WeakMovieScene
Definition at line 1195 of file MovieSceneToolHelpers.h.
The documentation for this struct was generated from the following file:
MovieSceneToolHelpers.h