Unreal Engine 5.6 C++ API: TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType > Class Template Reference
TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType > Class Template Reference
#include "ContainerAllocationPolicies.h"
Public Member Functions
ForElementType ()
Default constructor.
~ForElementType ()
FORCEINLINE SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
SIZE_T GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE ElementType * GetAllocation () const
SizeType GetInitialCapacity () const
FORCEINLINE bool HasAllocation () const
FORCEINLINE void MoveToEmpty (ForElementType &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement)
Private Member Functions
ForElementType (const ForElementType &)=delete
FORCEINLINE ElementType * GetInlineElements () const
ForElementType & operator= (const ForElementType &)=delete
Private Attributes
ElementType * Data
The data is allocated through the indirect allocation policy if more than NumInlineElements is needed.
TTypeCompatibleBytes< ElementType > InlineData [NumInlineElements]
The data is stored in this array if less than NumInlineElements is needed.
Detailed Description
template<uint32 NumInlineElements>
template<typename ElementType>
class TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >
Definition at line 1042 of file ContainerAllocationPolicies.h.
Constructor & Destructor Documentation
ForElementType() [1/2]
template<uint32 NumInlineElements> template<typename ElementType> TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::ForElementType () inline
Default constructor.
Definition at line 1046 of file ContainerAllocationPolicies.h.
References Data, and GetInlineElements().
Referenced by ForElementType(), MoveToEmpty(), and operator=().
~ForElementType()
template<uint32 NumInlineElements> template<typename ElementType> TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::~ForElementType () inline
Definition at line 1052 of file ContainerAllocationPolicies.h.
References Data, FMemory::Free(), and HasAllocation().
ForElementType() [2/2]
template<uint32 NumInlineElements> template<typename ElementType> TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::ForElementType (const ForElementType< ElementType > &) private delete
References ForElementType().
Member Function Documentation
CalculateSlackGrow()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE SizeType TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1155 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackGrow(), and FORCEINLINE.
CalculateSlackReserve()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE SizeType TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1143 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackReserve(), and FORCEINLINE.
CalculateSlackShrink()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE SizeType TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1149 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackShrink(), and FORCEINLINE.
GetAllocatedSize()
template<uint32 NumInlineElements> template<typename ElementType> SIZE_T TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 1161 of file ContainerAllocationPolicies.h.
References HasAllocation().
GetAllocation()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE ElementType * TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::GetAllocation () const inline
Definition at line 1095 of file ContainerAllocationPolicies.h.
References Data, and FORCEINLINE.
GetInitialCapacity()
template<uint32 NumInlineElements> template<typename ElementType> SizeType TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::GetInitialCapacity () const inline
Definition at line 1171 of file ContainerAllocationPolicies.h.
GetInlineElements()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE ElementType * TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::GetInlineElements () const inline private
Returns
the base of the aligned inline element data
Definition at line 1199 of file ContainerAllocationPolicies.h.
References FORCEINLINE, and InlineData.
Referenced by ForElementType(), HasAllocation(), MoveToEmpty(), and ResizeAllocation().
HasAllocation()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE bool TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::HasAllocation () const inline
Definition at line 1166 of file ContainerAllocationPolicies.h.
References Data, FORCEINLINE, and GetInlineElements().
Referenced by ~ForElementType(), GetAllocatedSize(), MoveToEmpty(), and ResizeAllocation().
MoveToEmpty()
template<uint32 NumInlineElements> template<typename ElementType> FORCEINLINE void TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::MoveToEmpty (ForElementType< ElementType > & Other) inline
Moves the state of another allocator into this one.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 1069 of file ContainerAllocationPolicies.h.
References ForElementType(), checkSlow, Data, FORCEINLINE, FMemory::Free(), GetInlineElements(), HasAllocation(), Other, and RelocateConstructItems().
operator=()
template<uint32 NumInlineElements> template<typename ElementType> ForElementType & TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::operator= (const ForElementType< ElementType > &) private delete
References ForElementType().
ResizeAllocation()
template<uint32 NumInlineElements> template<typename ElementType> void TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 1100 of file ContainerAllocationPolicies.h.
References Data, FMemory::Free(), GetInlineElements(), HasAllocation(), and RelocateConstructItems().
Field Documentation
Data
template<uint32 NumInlineElements> template<typename ElementType> ElementType* TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::Data private
The data is allocated through the indirect allocation policy if more than NumInlineElements is needed.
Definition at line 1193 of file ContainerAllocationPolicies.h.
Referenced by ForElementType(), ~ForElementType(), GetAllocation(), HasAllocation(), MoveToEmpty(), and ResizeAllocation().
InlineData
template<uint32 NumInlineElements> template<typename ElementType> TTypeCompatibleBytes<ElementType> TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::InlineData[NumInlineElements] private
The data is stored in this array if less than NumInlineElements is needed.
Definition at line 1196 of file ContainerAllocationPolicies.h.
Referenced by GetInlineElements().
The documentation for this class was generated from the following file:
ContainerAllocationPolicies.h