Unreal Engine 5.6 C++ API: FNumberFormattingOptions Struct Reference
FNumberFormattingOptions Struct Reference
#include "Text.h"
Public Member Functions
FNumberFormattingOptions ()
bool IsIdentical (const FNumberFormattingOptions &Other) const
Check to see if our formatting options match the other formatting options.
FNumberFormattingOptions & SetAlwaysSign (bool InValue)
FNumberFormattingOptions & SetIndicateNearlyInteger (bool InValue)
FNumberFormattingOptions & SetMaximumFractionalDigits (int32 InValue)
FNumberFormattingOptions & SetMaximumIntegralDigits (int32 InValue)
FNumberFormattingOptions & SetMinimumFractionalDigits (int32 InValue)
FNumberFormattingOptions & SetMinimumIntegralDigits (int32 InValue)
FNumberFormattingOptions & SetRoundingMode (ERoundingMode InValue)
FNumberFormattingOptions & SetUseGrouping (bool InValue)
Static Public Member Functions
static const FNumberFormattingOptions & DefaultNoGrouping ()
Get the default number formatting options with grouping disabled.
static const FNumberFormattingOptions & DefaultWithGrouping ()
Get the default number formatting options with grouping enabled.
Data Fields
bool AlwaysSign
bool IndicateNearlyInteger
int32 MaximumFractionalDigits
int32 MaximumIntegralDigits
int32 MinimumFractionalDigits
int32 MinimumIntegralDigits
ERoundingMode RoundingMode
bool UseGrouping
Friends
uint32 GetTypeHash (const FNumberFormattingOptions &Key)
Get the hash code to use for the given formatting options.
void operator<< (FStructuredArchive::FSlot Slot, FNumberFormattingOptions &Value)
Detailed Description
Definition at line 198 of file Text.h.
Constructor & Destructor Documentation
FNumberFormattingOptions()
FNumberFormattingOptions::FNumberFormattingOptions ()
Referenced by DefaultNoGrouping(), DefaultWithGrouping(), GetTypeHash, IsIdentical(), operator<<, SetAlwaysSign(), SetIndicateNearlyInteger(), SetMaximumFractionalDigits(), SetMaximumIntegralDigits(), SetMinimumFractionalDigits(), SetMinimumIntegralDigits(), SetRoundingMode(), and SetUseGrouping().
Member Function Documentation
DefaultNoGrouping()
const FNumberFormattingOptions & FNumberFormattingOptions::DefaultNoGrouping () static
Get the default number formatting options with grouping disabled.
References FNumberFormattingOptions().
Referenced by USTRUCT().
DefaultWithGrouping()
const FNumberFormattingOptions & FNumberFormattingOptions::DefaultWithGrouping () static
Get the default number formatting options with grouping enabled.
References FNumberFormattingOptions().
IsIdentical()
bool FNumberFormattingOptions::IsIdentical (const FNumberFormattingOptions & Other) const
Check to see if our formatting options match the other formatting options.
References FNumberFormattingOptions(), and Other.
SetAlwaysSign()
FNumberFormattingOptions & FNumberFormattingOptions::SetAlwaysSign (bool InValue) inline
Definition at line 203 of file Text.h.
References FNumberFormattingOptions(), and AlwaysSign.
SetIndicateNearlyInteger()
FNumberFormattingOptions & FNumberFormattingOptions::SetIndicateNearlyInteger (bool InValue) inline
Definition at line 209 of file Text.h.
References FNumberFormattingOptions(), and IndicateNearlyInteger.
Referenced by TDefaultNumericTypeInterface< NumericType >::ToString().
SetMaximumFractionalDigits()
FNumberFormattingOptions & FNumberFormattingOptions::SetMaximumFractionalDigits (int32 InValue) inline
Definition at line 224 of file Text.h.
References FNumberFormattingOptions(), and MaximumFractionalDigits.
Referenced by IAnimationDataController::ConvertSecondsToFrameNumber(), FDelayAction::GetDescription(), FVariablePrecisionNumericInterface::ToString(), and TDefaultNumericTypeInterface< NumericType >::ToString().
SetMaximumIntegralDigits()
FNumberFormattingOptions & FNumberFormattingOptions::SetMaximumIntegralDigits (int32 InValue) inline
Definition at line 218 of file Text.h.
References FNumberFormattingOptions(), and MaximumIntegralDigits.
SetMinimumFractionalDigits()
FNumberFormattingOptions & FNumberFormattingOptions::SetMinimumFractionalDigits (int32 InValue) inline
Definition at line 221 of file Text.h.
References FNumberFormattingOptions(), and MinimumFractionalDigits.
Referenced by IAnimationDataController::ConvertSecondsToFrameNumber(), FDelayAction::GetDescription(), FVariablePrecisionNumericInterface::ToString(), and TDefaultNumericTypeInterface< NumericType >::ToString().
SetMinimumIntegralDigits()
FNumberFormattingOptions & FNumberFormattingOptions::SetMinimumIntegralDigits (int32 InValue) inline
Definition at line 215 of file Text.h.
References FNumberFormattingOptions(), and MinimumIntegralDigits.
SetRoundingMode()
FNumberFormattingOptions & FNumberFormattingOptions::SetRoundingMode (ERoundingMode InValue) inline
Definition at line 212 of file Text.h.
References FNumberFormattingOptions(), and RoundingMode.
SetUseGrouping()
FNumberFormattingOptions & FNumberFormattingOptions::SetUseGrouping (bool InValue) inline
Definition at line 206 of file Text.h.
References FNumberFormattingOptions(), and UseGrouping.
Referenced by FVariablePrecisionNumericInterface::ToString(), and TDefaultNumericTypeInterface< NumericType >::ToString().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FNumberFormattingOptions & Key) friend
Get the hash code to use for the given formatting options.
References FNumberFormattingOptions(), and Key.
operator<<
void operator<< (FStructuredArchive::FSlot Slot, FNumberFormattingOptions & Value) friend
References FNumberFormattingOptions(), and Value.
Field Documentation
AlwaysSign
bool FNumberFormattingOptions::AlwaysSign
Definition at line 202 of file Text.h.
Referenced by SetAlwaysSign().
IndicateNearlyInteger
bool FNumberFormattingOptions::IndicateNearlyInteger
Definition at line 208 of file Text.h.
Referenced by SetIndicateNearlyInteger().
MaximumFractionalDigits
int32 FNumberFormattingOptions::MaximumFractionalDigits
Definition at line 223 of file Text.h.
Referenced by SetMaximumFractionalDigits().
MaximumIntegralDigits
int32 FNumberFormattingOptions::MaximumIntegralDigits
Definition at line 217 of file Text.h.
Referenced by SetMaximumIntegralDigits().
MinimumFractionalDigits
int32 FNumberFormattingOptions::MinimumFractionalDigits
Definition at line 220 of file Text.h.
Referenced by SetMinimumFractionalDigits(), and UE::Math::TVector< T >::ToCompactText().
MinimumIntegralDigits
int32 FNumberFormattingOptions::MinimumIntegralDigits
Definition at line 214 of file Text.h.
Referenced by SetMinimumIntegralDigits(), and UE::Math::TVector< T >::ToCompactText().
RoundingMode
ERoundingMode FNumberFormattingOptions::RoundingMode
Definition at line 211 of file Text.h.
Referenced by SetRoundingMode().
UseGrouping
bool FNumberFormattingOptions::UseGrouping
Definition at line 205 of file Text.h.
Referenced by SetUseGrouping().
The documentation for this struct was generated from the following file:
Text.h