Unreal Engine 5.6 C++ API: FKeyframeTrackEditor< TrackType > Class Template Reference
FKeyframeTrackEditor< TrackType > Class Template Reference
A base class for track editors that edit tracks which contain sections implementing GetKeyDataInterface.
#include "KeyframeTrackEditor.h"
Public Types
using GenerateKeysCallback = TFunction<void(UMovieSceneSection*, FGeneratedTrackKeys&)>
Public Member Functions
FKeyframeTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
~FKeyframeTrackEditor ()
Virtual destructor.
virtual void BuildTrackContextMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the context menu for the track.
virtual FText GetDisplayName () const override
The display name text to use in the UX.
virtual bool SupportsType (TSubclassOf< UMovieSceneTrack > Type) const override
Returns whether a track class is supported by this tool.
Public Member Functions inherited from FMovieSceneTrackEditor
FMovieSceneTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FMovieSceneTrackEditor ()
Destructor.
virtual UMovieSceneTrack * AddTrack (UMovieScene *FocusedMovieScene, const FGuid &ObjectHandle, TSubclassOf< class UMovieSceneTrack > TrackClass, FName UniqueTypeName) override
Add a new track to the sequence.
void AnimatablePropertyChanged (FOnKeyProperty OnKeyProperty)
virtual void BindCommands (TSharedRef< FUICommandList > SequencerCommandBindings) override
Allows the track editors to bind commands.
virtual void BuildAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildObjectBindingColumnWidgets (TFunctionRef< TSharedRef< SHorizontalBox >()> GetEditBox, const UE::Sequencer::TViewModelPtr< UE::Sequencer::FObjectBindingModel > &ObjectBinding, const UE::Sequencer::FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Build a column widget for the specified object binding on the outliner.
virtual void BuildObjectBindingTrackMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass) override
Builds up the object binding track menu for the outliner.
virtual TSharedPtr< SWidget > BuildOutlinerColumnWidget (const FBuildColumnWidgetParams &Params, const FName &ColumnName) override
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditColumnWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the edit column for outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
virtual void BuildPinnedAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildTrackSidebarMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the sidebar menu for the track.
FFindOrCreateHandleResult FindOrCreateHandleToObject (UObject *Object, bool bCreateHandleIfMissing=true, const FName &CreatedFolderName=NAME_None)
template<typename TrackClass>
FFindOrCreateRootTrackResult< TrackClass > FindOrCreateRootTrack ()
Find or add a track of the specified type in the focused movie scene.
FFindOrCreateTrackResult FindOrCreateTrackForObject (const FGuid &ObjectHandle, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName=NAME_None, bool bCreateTrackIfMissing=true)
UMovieSceneSequence * GetMovieSceneSequence () const
TSharedPtr< ISequencer > GetSequencer () const
FFrameNumber GetTimeForKey ()
virtual bool HandleAssetAdded (UObject *Asset, const FGuid &TargetObjectGuid) override
Called when an asset is dropped into Sequencer.
virtual TSharedRef< ISequencerSection > MakeSectionInterface (UMovieSceneSection &SectionObject, UMovieSceneTrack &Track, FGuid ObjectBinding) override
Called to generate a section layout for a particular section.
virtual bool OnAllowDrop (const FDragDropEvent &DragDropEvent, FSequencerDragDropParams &DragDropParams) override
Called when attempting to drop an asset directly onto a track.
virtual FReply OnDrop (const FDragDropEvent &DragDropEvent, const FSequencerDragDropParams &DragDropParams) override
Called when an asset is dropped directly onto a track.
virtual void OnInitialize () override
Called when the instance of this track editor is initialized.
virtual void OnRelease () override
Called when the instance of this track editor is released.
virtual bool SupportsSequence (UMovieSceneSequence *InSequence) const override
Returns whether a sequence is supported by this tool.
virtual void Tick (float DeltaTime) override
Ticks this tool.
void UpdatePlaybackRange ()
Public Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedRef< FMovieSceneTrackEditor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneTrackEditor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from ISequencerTrackEditor
virtual ~ISequencerTrackEditor ()
Virtual destructor.
virtual void BuildObjectBindingContextMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Builds up the object binding cpmtext menu for the outliner.
virtual void BuildObjectBindingEditButtons (TSharedPtr< SHorizontalBox > EditBox, const FGuid &ObjectBinding, const UClass *ObjectClass)
Deprecated in principle, not practice (due to difficulty deprecating public virtual functions).
virtual bool CanAddTransformKeysForSelectedObjects () const
Whether or not we can add a transform key for a selected object.
virtual void ExtendObjectBindingTrackMenu (TSharedRef< FExtender > Extender, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Extend the object binding track menu for the specified binding and class.
virtual bool GetDefaultExpansionState (UMovieSceneTrack *InTrack) const
virtual const FSlateBrush * GetIconBrush () const
Gets an icon brush for this track editor.
virtual bool HasTransformKeyBindings () const
virtual bool HasTransformKeyOverridePriority () const
If true this track has priority when setting transform keys and should be the only one to set them.
virtual bool IsResizable (UMovieSceneTrack *InTrack) const
virtual void ObjectImplicitlyAdded (UObject *InObject)
Handle this object being implicitly added.
virtual void ObjectImplicitlyRemoved (UObject *InObject)
Handle this object being implicitly removed.
virtual void OnAddTransformKeysForSelectedObjects (EMovieSceneTransformChannel Channel)
Adds transform tracks and keys to the selected objects in the level.
virtual void OnPostSaveWorld (UWorld *World)
Called after the sequencer has re-evaluated all objects after saving the level.
virtual void OnPreSaveWorld (UWorld *World)
Called before the sequencer restores pre-animated state on all objects before saving the level.
virtual void ProcessKeyOperation (FFrameNumber InKeyTime, const UE::Sequencer::FKeyOperation &Operation, ISequencer &InSequencer, TArray< UE::Sequencer::FAddKeyResult > *OutResults=nullptr)
Add keys for the following sections based on an external value if possible.
virtual void Resize (float NewSize, UMovieSceneTrack *InTrack)
Resize this track.
Protected Member Functions
FKeyPropertyResult AddKeysToObjects (TArrayView< UObject *const > ObjectsToKey, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(TrackType *)> OnInitializeNewTrack, const GenerateKeysCallback &OnGenerateKeys)
FKeyPropertyResult AddKeysToSection (UMovieSceneSection *Section, FFrameNumber KeyTime, const FGeneratedTrackKeys &Keys, ESequencerKeyMode KeyMode, EKeyFrameTrackEditorSetDefault SetDefault=EKeyFrameTrackEditorSetDefault::SetDefault)
virtual bool ModifyGeneratedKeysByCurrentAndWeight (UObject *Object, UMovieSceneTrack *Track, UMovieSceneSection *SectionToKey, FFrameNumber Time, FGeneratedTrackKeys &GeneratedTotalKeys, float Weight) const
Scale the generated keys by the the current value and the weight.
Protected Member Functions inherited from FMovieSceneTrackEditor
UMovieScene * GetFocusedMovieScene () const
Gets the currently focused movie scene, if any.
Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static bool CanAutoKeySection (UMovieSceneSection *Section, FFrameNumber Time)
Check whether we can autokey the specified section at the specified time.
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Private Member Functions
FKeyPropertyResult AddKeysToHandle (UObject *Object, FGuid ObjectHandle, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(TrackType *)> OnInitializeNewTrack, const GenerateKeysCallback &OnGenerateKeys)
void AddTrackDefaultsItems (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track)
void ClearDefaults (UMovieSceneTrack *Track)
Additional Inherited Members
Static Public Member Functions inherited from FMovieSceneTrackEditor
static void BeginKeying (FFrameNumber InFrameNumber)
Initiate keying when there is more than one object to key (ie.
static void EndKeying ()
Detailed Description
template<typename TrackType>
class FKeyframeTrackEditor< TrackType >
A base class for track editors that edit tracks which contain sections implementing GetKeyDataInterface.
Definition at line 454 of file KeyframeTrackEditor.h.
Member Typedef Documentation
GenerateKeysCallback
template<typename TrackType> using FKeyframeTrackEditor< TrackType >::GenerateKeysCallback = TFunction<void(UMovieSceneSection*, FGeneratedTrackKeys&)>
Definition at line 458 of file KeyframeTrackEditor.h.
Constructor & Destructor Documentation
FKeyframeTrackEditor()
template<typename TrackType> FKeyframeTrackEditor< TrackType >::FKeyframeTrackEditor (TSharedRef< ISequencer > InSequencer) inline
Constructor.
Parameters
InSequencer The sequencer instance to be used by this tool
Definition at line 465 of file KeyframeTrackEditor.h.
References FMovieSceneTrackEditor::FMovieSceneTrackEditor().
Referenced by FPropertyTrackEditor< TrackType >::FPropertyTrackEditor(), and FPropertyTrackEditor< TrackType >::FPropertyTrackEditor().
~FKeyframeTrackEditor()
template<typename TrackType> FKeyframeTrackEditor< TrackType >::~FKeyframeTrackEditor () inline
Virtual destructor.
Definition at line 470 of file KeyframeTrackEditor.h.
Member Function Documentation
AddKeysToHandle()
template<typename TrackType> FKeyPropertyResult FKeyframeTrackEditor< TrackType >::AddKeysToHandle (UObject * Object, FGuid ObjectHandle, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(TrackType *)> OnInitializeNewTrack, const GenerateKeysCallback & OnGenerateKeys) inline private
Definition at line 591 of file KeyframeTrackEditor.h.
References TArray< InElementType, InAllocatorType >::Add(), AddKeysToSection(), TRange< ElementType >::All(), AutoKey, FKeyPropertyResult::bTrackCreated, FMovieSceneTrackEditor::FFindOrCreateTrackResult::bWasCreated, CanAutoKeySection(), CastChecked(), FMovieSceneTrackEditor::FindOrCreateTrackForObject(), ISequencer::GetAllowEditsMode(), ISequencer::GetAutoChangeMode(), FMovieSceneTrackEditor::GetSequencer(), ManualKey, ManualKeyForced, ModifyGeneratedKeysByCurrentAndWeight(), ECastCheckedType::NullAllowed, Object, PropertyName, FKeyPropertyResult::SectionsCreated, FMovieSceneTrackEditor::FFindOrCreateTrackResult::Track, and Weight.
Referenced by AddKeysToObjects().
AddKeysToObjects()
template<typename TrackType> FKeyPropertyResult FKeyframeTrackEditor< TrackType >::AddKeysToObjects (TArrayView< UObject *const > ObjectsToKey, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(TrackType *)> OnInitializeNewTrack, const GenerateKeysCallback & OnGenerateKeys) inline protected
Definition at line 511 of file KeyframeTrackEditor.h.
References AddKeysToHandle(), AutoKey, FKeyPropertyResult::bHandleCreated, FMovieSceneTrackEditor::FFindOrCreateHandleResult::bWasCreated, FMovieSceneTrackEditor::FindOrCreateHandleToObject(), FName, ISequencer::GetAllowEditsMode(), ISequencer::GetAutoChangeMode(), FMovieSceneTrackEditor::GetSequencer(), FMovieSceneTrackEditor::FFindOrCreateHandleResult::Handle, FGuid::IsValid(), ManualKey, ManualKeyForced, Object, PropertyName, and TEXT.
Referenced by FPropertyTrackEditor< TrackType >::OnKeyProperty().
AddKeysToSection()
template<typename TrackType> FKeyPropertyResult FKeyframeTrackEditor< TrackType >::AddKeysToSection (UMovieSceneSection * Section, FFrameNumber KeyTime, const FGeneratedTrackKeys & Keys, ESequencerKeyMode KeyMode, EKeyFrameTrackEditorSetDefault SetDefault = EKeyFrameTrackEditorSetDefault::SetDefault) inline protected
Definition at line 666 of file KeyframeTrackEditor.h.
References TArray< InElementType, InAllocatorType >::Add(), AutoKey, FKeyPropertyResult::bKeyCreated, DoNotSetDefault, ISequencer::GetAutoChangeMode(), ISequencer::GetAutoSetTrackDefaults(), ISequencer::GetKeyGroupMode(), ISequencer::GetKeyInterpolation(), FMovieSceneTrackEditor::GetSequencer(), ManualKeyForced, FKeyPropertyResult::SectionsKeyed, and SetDefault.
Referenced by AddKeysToHandle().
AddTrackDefaultsItems()
template<typename TrackType> void FKeyframeTrackEditor< TrackType >::AddTrackDefaultsItems (FMenuBuilder & MenuBuilder, UMovieSceneTrack * Track) inline private
Definition at line 566 of file KeyframeTrackEditor.h.
References FBaseMenuBuilder::AddMenuEntry(), ClearDefaults(), and NSLOCTEXT.
Referenced by BuildTrackContextMenu().
BuildTrackContextMenu()
template<typename TrackType> virtual void FKeyframeTrackEditor< TrackType >::BuildTrackContextMenu (FMenuBuilder & MenuBuilder, UMovieSceneTrack * Track) inline override virtual
Builds the context menu for the track.
Parameters
MenuBuilder The menu builder to use to build the track menu.
Reimplemented from FMovieSceneTrackEditor.
Reimplemented in FCinematicShotTrackEditor.
Definition at line 487 of file KeyframeTrackEditor.h.
References FMenuBuilder::AddSubMenu(), AddTrackDefaultsItems(), and NSLOCTEXT.
CanAutoKeySection()
template<typename TrackType> bool FKeyframeTrackEditor< TrackType >::CanAutoKeySection (UMovieSceneSection * Section, FFrameNumber Time) inline static protected
Check whether we can autokey the specified section at the specified time.
Definition at line 735 of file KeyframeTrackEditor.h.
References Time.
Referenced by AddKeysToHandle().
ClearDefaults()
template<typename TrackType> void FKeyframeTrackEditor< TrackType >::ClearDefaults (UMovieSceneTrack * Track) inline private
Definition at line 547 of file KeyframeTrackEditor.h.
References FMovieSceneTrackEditor::GetSequencer(), ISequencer::NotifyMovieSceneDataChanged(), NSLOCTEXT, and TrackValueChanged.
Referenced by AddTrackDefaultsItems().
GetDisplayName()
template<typename TrackType> virtual FText FKeyframeTrackEditor< TrackType >::GetDisplayName () const inline override virtual
The display name text to use in the UX.
Currently only used for sorting.
Reimplemented from FMovieSceneTrackEditor.
Reimplemented in FBoolPropertyTrackEditor, FCinematicShotTrackEditor, FPropertyTrackEditor< TrackType >, FPropertyTrackEditor< UMovieSceneBoolTrack >, FSubTrackEditor, and FTimeWarpTrackEditor.
Definition at line 476 of file KeyframeTrackEditor.h.
References NSLOCTEXT.
ModifyGeneratedKeysByCurrentAndWeight()
template<typename TrackType> virtual bool FKeyframeTrackEditor< TrackType >::ModifyGeneratedKeysByCurrentAndWeight (UObject * Object, UMovieSceneTrack * Track, UMovieSceneSection * SectionToKey, FFrameNumber Time, FGeneratedTrackKeys & GeneratedTotalKeys, float Weight) const inline protected virtual
Scale the generated keys by the the current value and the weight.
This is used for supporting layered workflows so the keyed value is set correctly. The issue is that the Generated Property Values are the Globa Values that we want to meet but we need to set the local value on a particular section based upon The algorithm to implement should be NewGeneratedValue = (GeneratedTotalValue - CurrentValue) * Weight + CurrentChannelValue Expect that this will only be called if blended sections are occuring, it will not get called if no blending is happening.
Parameters
Object Object we are keying
Track The track we are on
SectionToKey the section we are on
Time Time we are at
GeneratedKeys Array of keys that are modified from the changed property. This is the same one that's calculdate but it's the Total/Global
Weight The Weight used in the algorithm above. Note it maybe be greater than one since it's the actual inverse of the weight on that section.
Returns
Return true if this is actually implemented false if not. Usually only TrackEditors with valid BlendTypes will implement this.
Definition at line 729 of file KeyframeTrackEditor.h.
References Object, Time, and Weight.
Referenced by AddKeysToHandle().
SupportsType()
template<typename TrackType> virtual bool FKeyframeTrackEditor< TrackType >::SupportsType (TSubclassOf< UMovieSceneTrack > TrackClass) const inline override virtual
Returns whether a track class is supported by this tool.
Parameters
TrackClass The track class that could be supported.
Returns
true if the type is supported.
Implements FMovieSceneTrackEditor.
Reimplemented in FPropertyTrackEditor< TrackType >, FPropertyTrackEditor< UMovieSceneBoolTrack >, FSpawnTrackEditor, and FSubTrackEditor.
Definition at line 481 of file KeyframeTrackEditor.h.
The documentation for this class was generated from the following file:
KeyframeTrackEditor.h