Unreal Engine 5.6 C++ API: FEditPropertyChain Class Reference
FEditPropertyChain Class Reference
This class represents the chain of member properties leading to an internal struct property.
#include "UnrealType.h"
Public Member Functions
FEditPropertyChain ()
Constructors.
TDoubleLinkedListNode * GetActiveMemberNode () const
Returns the node corresponding to the currently active property, or if the currently active property is not a member variable (i.e.
TDoubleLinkedListNode * GetActiveNode () const
Returns the node corresponding to the currently active property.
bool IsArchetypeInstanceAffected (UObject *InInstance) const
Returns whether the specified archetype instance will be affected by the property change.
bool SetActiveMemberPropertyNode (FProperty *NewActiveMemberProperty)
Sets the ActiveMemberPropertyNode to the node associated with the property specified.
bool SetActivePropertyNode (FProperty *NewActiveProperty)
Sets the ActivePropertyNode to the node associated with the property specified.
template<typename T>
void SetAffectedArchetypeInstances (T &&InAffectedInstances)
Specify the set of archetype instances that will be affected by the property change.
Public Member Functions inherited from TDoubleLinkedList< FProperty * >
TDoubleLinkedList ()
Constructors.
virtual ~TDoubleLinkedList ()
Destructor.
bool AddHead (const FProperty *&InElement)
Add the specified value to the beginning of the list, making that value the new head of the list.
bool AddTail (const FProperty *&InElement)
Append the specified value to the end of the list.
bool Contains (const FProperty *&InElement)
void Empty ()
Removes all nodes from the list.
TDoubleLinkedListNode * FindNode (const FProperty *&InElement)
Finds the node corresponding to the value specified.
TDoubleLinkedListNode * GetHead () const
Returns the node at the head of the list.
TDoubleLinkedListNode * GetTail () const
Returns the node at the end of the list.
bool InsertNode (const FProperty *&InElement, TDoubleLinkedListNode *NodeToInsertBefore=nullptr)
Insert the specified value into the list at an arbitrary point.
bool IsEmpty () const
Returns true if the list is empty and contains no elements.
int32 Num () const
Returns the number of items in the list.
void RemoveNode (const FProperty *&InElement)
Remove the node corresponding to InElement.
Protected Member Functions
virtual void SetListSize (int32 NewListSize)
TDoubleLinkedList interface.
Protected Attributes
TDoubleLinkedListNode * ActiveMemberPropertyNode
In a hierarchy of properties being edited, corresponds to the class member property which contains the property that is currently being processed by Pre/PostEditChange.
TDoubleLinkedListNode * ActivePropertyNode
In a hierarchy of properties being edited, corresponds to the property that is currently being processed by Pre/PostEditChange.
TSet< UObject * > AffectedInstances
Archetype instances that will be affected by the property change.
bool bFilterAffectedInstances
Assume all archetype instances are affected unless a set of affected instances is provided.
Additional Inherited Members
Public Types inherited from TDoubleLinkedList< FProperty * >
typedef TDoubleLinkedListIterator< TDoubleLinkedListNode, const FProperty * > TConstIterator
typedef TDoubleLinkedListIterator< TDoubleLinkedListNode, FProperty * > TIterator
Used to iterate over the elements of a linked list.
Detailed Description
This class represents the chain of member properties leading to an internal struct property.
It is used for tracking which member property corresponds to the UScriptStruct that owns a particular property.
Definition at line 6314 of file UnrealType.h.
Constructor & Destructor Documentation
FEditPropertyChain()
FEditPropertyChain::FEditPropertyChain () inline
Constructors.
Definition at line 6319 of file UnrealType.h.
References ActiveMemberPropertyNode, ActivePropertyNode, and bFilterAffectedInstances.
Member Function Documentation
GetActiveMemberNode()
TDoubleLinkedListNode * FEditPropertyChain::GetActiveMemberNode () const
Returns the node corresponding to the currently active property, or if the currently active property is not a member variable (i.e.
inside of a struct/array), the node corresponding to the member variable which contains the currently active property.
References UE_API.
GetActiveNode()
TDoubleLinkedListNode * FEditPropertyChain::GetActiveNode () const
Returns the node corresponding to the currently active property.
References UE_API.
IsArchetypeInstanceAffected()
bool FEditPropertyChain::IsArchetypeInstanceAffected (UObject * InInstance) const
Returns whether the specified archetype instance will be affected by the property change.
References UE_API.
SetActiveMemberPropertyNode()
bool FEditPropertyChain::SetActiveMemberPropertyNode (FProperty * NewActiveMemberProperty)
Sets the ActiveMemberPropertyNode to the node associated with the property specified.
Parameters
NewActiveMemberProperty the member FProperty which contains the property currently being evaluated by Pre/PostEditChange
Returns
true if the ActiveMemberPropertyNode was successfully changed to the node associated with the property specified. false if there was no node corresponding to that property.
References UE_API.
Referenced by FRigVMGraphEnumDetailCustomization::GetPropertyChain(), and FRigVMGraphMathTypeDetailCustomization::GetPropertyChain().
SetActivePropertyNode()
bool FEditPropertyChain::SetActivePropertyNode (FProperty * NewActiveProperty)
Sets the ActivePropertyNode to the node associated with the property specified.
Parameters
NewActiveProperty the FProperty that is currently being evaluated by Pre/PostEditChange
Returns
true if the ActivePropertyNode was successfully changed to the node associated with the property specified. false if there was no node corresponding to that property.
References UE_API.
SetAffectedArchetypeInstances()
template<typename T> void FEditPropertyChain::SetAffectedArchetypeInstances (T && InAffectedInstances) inline
Specify the set of archetype instances that will be affected by the property change.
Definition at line 6346 of file UnrealType.h.
References AffectedInstances, bFilterAffectedInstances, and Forward().
SetListSize()
virtual void FEditPropertyChain::SetListSize (int32 NewListSize) protected virtual
TDoubleLinkedList interface.
Updates the size reported by Num(). Child classes can use this function to conveniently hook into list additions/removals.
This version ensures that the ActivePropertyNode and ActiveMemberPropertyNode point to a valid nodes or NULL if this list is empty.
Parameters
NewListSize the new size for this list
Reimplemented from TDoubleLinkedList< FProperty * >.
References UE_API.
Field Documentation
ActiveMemberPropertyNode
TDoubleLinkedListNode* FEditPropertyChain::ActiveMemberPropertyNode protected
In a hierarchy of properties being edited, corresponds to the class member property which contains the property that is currently being processed by Pre/PostEditChange.
This will only be different from the ActivePropertyNode if the active property is contained within a struct, dynamic array, or static array.
Definition at line 6382 of file UnrealType.h.
Referenced by FEditPropertyChain().
ActivePropertyNode
TDoubleLinkedListNode* FEditPropertyChain::ActivePropertyNode protected
In a hierarchy of properties being edited, corresponds to the property that is currently being processed by Pre/PostEditChange.
Definition at line 6374 of file UnrealType.h.
Referenced by FEditPropertyChain().
AffectedInstances
TSet<UObject*> FEditPropertyChain::AffectedInstances protected
Archetype instances that will be affected by the property change.
Definition at line 6387 of file UnrealType.h.
Referenced by SetAffectedArchetypeInstances().
bFilterAffectedInstances
bool FEditPropertyChain::bFilterAffectedInstances protected
Assume all archetype instances are affected unless a set of affected instances is provided.
Definition at line 6392 of file UnrealType.h.
Referenced by FEditPropertyChain(), and SetAffectedArchetypeInstances().
The documentation for this class was generated from the following file:
UnrealType.h