Unreal Engine 5.6 C++ API: Metasound::FArrayRandomGet Class Reference
Metasound::FArrayRandomGet Class Reference
#include "MetasoundArrayRandomNode.h"
Public Member Functions
FArrayRandomGet ()=default
METASOUNDFRONTEND_API FArrayRandomGet (int32 InSeed, int32 InMaxIndex, const TArray< float > &InWeights, int32 InNoRepeatOrder)
~FArrayRandomGet ()=default
int32 GetMaxIndex () const
int32 GetNoRepeatOrder () const
METASOUNDFRONTEND_API int32 NextValue ()
METASOUNDFRONTEND_API void ResetSeed ()
METASOUNDFRONTEND_API void SetNoRepeatOrder (int32 InNoRepeatOrder)
METASOUNDFRONTEND_API void SetRandomWeights (const TArray< float > &InRandomWeights)
METASOUNDFRONTEND_API void SetSeed (int32 InSeed)
UE_DEPRECATED (5.5, "Use UpdateState instead") METASOUNDFRONTEND_API void Init(int32 InSeed
METASOUNDFRONTEND_API void UpdateState (int32 InSeed, int32 InMaxIndex, const TArray< float > &InWeights, int32 InNoRepeatOrder)
Data Fields
int32 InMaxIndex
int32 const TArray< float > int32 InNoRepeatOrder
int32 const TArray< float > & InWeights
Private Member Functions
METASOUNDFRONTEND_API float ComputeTotalWeight ()
Private Attributes
bool bRandomStreamInitialized = false
int32 MaxIndex = 0
int32 NoRepeatOrder = INDEX_NONE
TArray< int32 > PreviousIndices
TUniquePtr< TCircularQueue< int32 > > PreviousIndicesQueue
FRandomStream RandomStream
TArray< float > RandomWeights
int32 Seed = INDEX_NONE
Detailed Description
Definition at line 87 of file MetasoundArrayRandomNode.h.
Constructor & Destructor Documentation
FArrayRandomGet() [1/2]
Metasound::FArrayRandomGet::FArrayRandomGet () default
FArrayRandomGet() [2/2]
METASOUNDFRONTEND_API Metasound::FArrayRandomGet::FArrayRandomGet (int32 InSeed, int32 InMaxIndex, const TArray< float > & InWeights, int32 InNoRepeatOrder)
References InMaxIndex, InNoRepeatOrder, InWeights, and UE_API.
~FArrayRandomGet()
Metasound::FArrayRandomGet::~FArrayRandomGet () default
Member Function Documentation
ComputeTotalWeight()
METASOUNDFRONTEND_API float Metasound::FArrayRandomGet::ComputeTotalWeight () private
References UE_API.
GetMaxIndex()
int32 Metasound::FArrayRandomGet::GetMaxIndex () const inline
Definition at line 104 of file MetasoundArrayRandomNode.h.
References MaxIndex.
GetNoRepeatOrder()
int32 Metasound::FArrayRandomGet::GetNoRepeatOrder () const inline
Definition at line 103 of file MetasoundArrayRandomNode.h.
References GetNoRepeatOrder(), and NoRepeatOrder.
Referenced by GetNoRepeatOrder().
NextValue()
METASOUNDFRONTEND_API int32 Metasound::FArrayRandomGet::NextValue ()
References NextValue(), and UE_API.
Referenced by NextValue().
ResetSeed()
METASOUNDFRONTEND_API void Metasound::FArrayRandomGet::ResetSeed ()
References ResetSeed(), and UE_API.
Referenced by ResetSeed().
SetNoRepeatOrder()
METASOUNDFRONTEND_API void Metasound::FArrayRandomGet::SetNoRepeatOrder (int32 InNoRepeatOrder)
References InNoRepeatOrder, SetNoRepeatOrder(), and UE_API.
Referenced by SetNoRepeatOrder().
SetRandomWeights()
METASOUNDFRONTEND_API void Metasound::FArrayRandomGet::SetRandomWeights (const TArray< float > & InRandomWeights)
References SetRandomWeights(), and UE_API.
Referenced by SetRandomWeights().
SetSeed()
METASOUNDFRONTEND_API void Metasound::FArrayRandomGet::SetSeed (int32 InSeed)
References SetSeed(), and UE_API.
Referenced by SetSeed().
UE_DEPRECATED()
Metasound::FArrayRandomGet::UE_DEPRECATED (5. 5, "Use UpdateState instead")
UpdateState()
METASOUNDFRONTEND_API void Metasound::FArrayRandomGet::UpdateState (int32 InSeed, int32 InMaxIndex, const TArray< float > & InWeights, int32 InNoRepeatOrder)
References InMaxIndex, InNoRepeatOrder, InWeights, UE_API, and UpdateState().
Referenced by UpdateState().
Field Documentation
bRandomStreamInitialized
bool Metasound::FArrayRandomGet::bRandomStreamInitialized = false private
Definition at line 121 of file MetasoundArrayRandomNode.h.
InMaxIndex
int32 Metasound::FArrayRandomGet::InMaxIndex
Definition at line 95 of file MetasoundArrayRandomNode.h.
Referenced by FArrayRandomGet(), and UpdateState().
InNoRepeatOrder
int32 const TArray<float> int32 Metasound::FArrayRandomGet::InNoRepeatOrder
Definition at line 95 of file MetasoundArrayRandomNode.h.
Referenced by FArrayRandomGet(), SetNoRepeatOrder(), and UpdateState().
InWeights
int32 const TArray<float>& Metasound::FArrayRandomGet::InWeights
Definition at line 95 of file MetasoundArrayRandomNode.h.
Referenced by FArrayRandomGet(), and UpdateState().
MaxIndex
int32 Metasound::FArrayRandomGet::MaxIndex = 0 private
Definition at line 115 of file MetasoundArrayRandomNode.h.
Referenced by GetMaxIndex().
NoRepeatOrder
int32 Metasound::FArrayRandomGet::NoRepeatOrder = INDEX_NONE private
Definition at line 112 of file MetasoundArrayRandomNode.h.
Referenced by GetNoRepeatOrder().
PreviousIndices
TArray<int32> Metasound::FArrayRandomGet::PreviousIndices private
Definition at line 110 of file MetasoundArrayRandomNode.h.
PreviousIndicesQueue
TUniquePtr<TCircularQueue<int32> > Metasound::FArrayRandomGet::PreviousIndicesQueue private
Definition at line 111 of file MetasoundArrayRandomNode.h.
RandomStream
FRandomStream Metasound::FArrayRandomGet::RandomStream private
Definition at line 119 of file MetasoundArrayRandomNode.h.
RandomWeights
TArray<float> Metasound::FArrayRandomGet::RandomWeights private
Definition at line 116 of file MetasoundArrayRandomNode.h.
Seed
int32 Metasound::FArrayRandomGet::Seed = INDEX_NONE private
Definition at line 120 of file MetasoundArrayRandomNode.h.
The documentation for this class was generated from the following file:
MetasoundArrayRandomNode.h