Unreal Engine 5.6 C++ API: ParticleSystemComponent.h File Reference
ParticleSystemComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Components/SceneComponent.h"
#include "Components/PrimitiveComponent.h"
#include "Materials/MaterialInterface.h"
#include "Particles/ParticleSystem.h"
#include "Particles/Emitter.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Particles/WorldPSCPool.h"
#include "Particles/ParticlePerfStats.h"
#include "StateStream/ParticleSystemStateStreamHandle.h"
#include "ParticleSystemComponent.generated.h"
Data Structures
struct FParticleEventBurstData
Particle burst event data.
struct FParticleEventCollideData
Collision particle event data.
struct FParticleEventData
The base class for all particle event data.
struct FParticleEventDeathData
Killed particle event data.
struct FParticleEventKismetData
Kismet particle event data.
struct FParticleEventSpawnData
Spawn particle event data.
struct FParticleExistingData
Particle event data for particles that already existed at the time of the event.
struct TIsPODType< FParticleSysParam >
class UParticleSystemComponent
Functions
UENUM() enum EParticleSysParamType UENUM() enum ParticleReplayState UENUM() enum EParticleEventType DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnSystemFinished, class UParticleSystemComponent *, PSystem)
Enum for specifying type of a name instance parameter.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnSystemPreActivationChange, class UParticleSystemComponent *, bool)
UCLASS() class UFXSystemComponent UCLASS ()
A particle emitter.
USTRUCT () struct FParticleSysParam
Struct used for a particular named instance parameter for this ParticleSystemComponent.
Variables
UCLASS() class UFXSystemComponent editinlinenew
UCLASS() class UFXSystemComponent hidecategories =Object
UCLASS() class UFXSystemComponent meta =(BlueprintSpawnableComponent, DisplayName = "Cascade Particle System Component")
UCLASS() class UFXSystemComponent showcategories =Trigger
Function Documentation
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam()
UENUM() enum EParticleSysParamType UENUM() enum ParticleReplayState UENUM() enum EParticleEventType DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnSystemFinished , class UParticleSystemComponent * , PSystem)
Enum for specifying type of a name instance parameter.
Particle system replay state Event type
DECLARE_MULTICAST_DELEGATE_TwoParams()
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnSystemPreActivationChange , class UParticleSystemComponent * , bool)
UCLASS()
UCLASS() class UFXSystemComponent UCLASS ()
A particle emitter.
USTRUCT()
USTRUCT ()
Struct used for a particular named instance parameter for this ParticleSystemComponent.
Parameters controlling the spawning behavior of FX systems via the SpawnSystemAtLocation and SpawnSystemAttached.
The name of the parameter
The type of parameters PSPT_None - There is no data type PSPT_Scalar - Use the scalar value PSPT_ScalarRand - Select a scalar value in the range [Scalar_Low..Scalar) PSPT_Vector - Use the vector value PSPT_VectorRand - Select a vector value in the range [Vector_Low..Vector) PSPT_Color - Use the color value PSPT_Actor - Use the actor value PSPT_Material - Use the material value PSPT_VectorUnitRand - Select a random unit vector and scale along the range [Vector_Low..Vector)
Definition at line 103 of file ParticleSystemComponent.h.
References Actor, BlueprintType, Category, check, Color, ForceInit, FVector, GENERATED_USTRUCT_BODY, UE::Math::TTransform< double >::Identity, IsInGameThread(), Material, Name, UPROPERTY, Vector, and UE::Math::TVector< double >::ZeroVector.
Variable Documentation
editinlinenew
UCLASS() class UFXSystemComponent editinlinenew
Definition at line 486 of file ParticleSystemComponent.h.
hidecategories
UCLASS() class UFXSystemComponent hidecategories =Object
Definition at line 486 of file ParticleSystemComponent.h.
meta
UCLASS() class UFXSystemComponent meta =(BlueprintSpawnableComponent, DisplayName = "Cascade Particle System Component")
Definition at line 486 of file ParticleSystemComponent.h.
Referenced by UParticleSystemComponent::UFUNCTION(), UParticleSystemComponent::UPROPERTY(), UParticleSystemComponent::UPROPERTY(), UParticleSystemComponent::UPROPERTY(), UParticleSystemComponent::UPROPERTY(), and UParticleSystemComponent::UPROPERTY().
showcategories
UCLASS() class UFXSystemComponent showcategories =Trigger
Definition at line 486 of file ParticleSystemComponent.h.