Unreal Engine 5.6 C++ API: FScopedSceneLock_Chaos Struct Reference
FScopedSceneLock_Chaos Struct Reference
#include "ChaosScopedSceneLock.h"
Public Member Functions
FScopedSceneLock_Chaos (Chaos::FPhysicsObjectHandle InObjectA, Chaos::FPhysicsObjectHandle InObjectB, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (const FPhysicsActorHandle &InActorHandle, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (const FPhysicsActorHandle &InActorHandleA, const FPhysicsActorHandle &InActorHandleB, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (FChaosScene *InScene, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (FPhysicsActorHandle const *InActorHandle, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (FPhysicsActorHandle const *InActorHandleA, FPhysicsActorHandle const *InActorHandleB, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (FPhysicsConstraintHandle const *InConstraintHandle, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos (FScopedSceneLock_Chaos &&Other)
FScopedSceneLock_Chaos (FScopedSceneLock_Chaos &Other)=delete
FScopedSceneLock_Chaos (USkeletalMeshComponent *InSkelMeshComp, EPhysicsInterfaceScopedLockType InLockType)
~FScopedSceneLock_Chaos ()
FScopedSceneLock_Chaos & operator= (FScopedSceneLock_Chaos &&Other)
FScopedSceneLock_Chaos & operator= (FScopedSceneLock_Chaos &Other)=delete
void Release ()
Protected Member Functions
FScopedSceneLock_Chaos (EPhysicsInterfaceScopedLockType InLockType)
FChaosScene * GetSceneForActor (const FPhysicsActorHandle &InActorHandle)
FChaosScene * GetSceneForActor (FPhysicsConstraintHandle const *InConstraintHandle)
Chaos::FPhysSceneLock * GetSolverLock (Chaos::FPBDRigidsSolver *InSolver)
void LockScene ()
void LockSceneForConstraint (FPhysicsConstraintHandle const *InConstraintHandle)
void UnlockScene ()
Protected Attributes
bool bHasLock = false
EPhysicsInterfaceScopedLockType LockType
Chaos::FPBDRigidsSolver * Solver
EPhysicsInterfaceScopedThreadContext ThreadContext = EPhysicsInterfaceScopedThreadContext::External
Detailed Description
Definition at line 35 of file ChaosScopedSceneLock.h.
Constructor & Destructor Documentation
FScopedSceneLock_Chaos() [1/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (const FPhysicsActorHandle & InActorHandle, EPhysicsInterfaceScopedLockType InLockType)
Referenced by FScopedSceneLock_Chaos(), FScopedSceneLock_Chaos(), operator=(), and operator=().
FScopedSceneLock_Chaos() [2/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (const FPhysicsActorHandle & InActorHandleA, const FPhysicsActorHandle & InActorHandleB, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos() [3/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (FPhysicsActorHandle const * InActorHandle, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos() [4/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (FPhysicsActorHandle const * InActorHandleA, FPhysicsActorHandle const * InActorHandleB, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos() [5/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (FPhysicsConstraintHandle const * InConstraintHandle, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos() [6/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (USkeletalMeshComponent * InSkelMeshComp, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos() [7/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (Chaos::FPhysicsObjectHandle InObjectA, Chaos::FPhysicsObjectHandle InObjectB, EPhysicsInterfaceScopedLockType InLockType)
FScopedSceneLock_Chaos() [8/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (FChaosScene * InScene, EPhysicsInterfaceScopedLockType InLockType)
~FScopedSceneLock_Chaos()
FScopedSceneLock_Chaos::~FScopedSceneLock_Chaos ()
FScopedSceneLock_Chaos() [9/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (FScopedSceneLock_Chaos & Other) delete
References FScopedSceneLock_Chaos(), and Other.
FScopedSceneLock_Chaos() [10/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (FScopedSceneLock_Chaos && Other)
References FScopedSceneLock_Chaos(), and Other.
FScopedSceneLock_Chaos() [11/11]
FScopedSceneLock_Chaos::FScopedSceneLock_Chaos (EPhysicsInterfaceScopedLockType InLockType) inline protected
Definition at line 58 of file ChaosScopedSceneLock.h.
References LockType, and Solver.
Member Function Documentation
GetSceneForActor() [1/2]
FChaosScene * FScopedSceneLock_Chaos::GetSceneForActor (const FPhysicsActorHandle & InActorHandle) protected
GetSceneForActor() [2/2]
FChaosScene * FScopedSceneLock_Chaos::GetSceneForActor (FPhysicsConstraintHandle const * InConstraintHandle) protected
GetSolverLock()
Chaos::FPhysSceneLock * FScopedSceneLock_Chaos::GetSolverLock (Chaos::FPBDRigidsSolver * InSolver) protected
LockScene()
void FScopedSceneLock_Chaos::LockScene () protected
LockSceneForConstraint()
void FScopedSceneLock_Chaos::LockSceneForConstraint (FPhysicsConstraintHandle const * InConstraintHandle) protected
operator=() [1/2]
FScopedSceneLock_Chaos & FScopedSceneLock_Chaos::operator= (FScopedSceneLock_Chaos && Other)
References FScopedSceneLock_Chaos(), and Other.
operator=() [2/2]
FScopedSceneLock_Chaos & FScopedSceneLock_Chaos::operator= (FScopedSceneLock_Chaos & Other) delete
References FScopedSceneLock_Chaos(), and Other.
Release()
void FScopedSceneLock_Chaos::Release ()
UnlockScene()
void FScopedSceneLock_Chaos::UnlockScene () protected
Field Documentation
bHasLock
bool FScopedSceneLock_Chaos::bHasLock = false protected
Definition at line 72 of file ChaosScopedSceneLock.h.
LockType
EPhysicsInterfaceScopedLockType FScopedSceneLock_Chaos::LockType protected
Definition at line 74 of file ChaosScopedSceneLock.h.
Referenced by FScopedSceneLock_Chaos().
Solver
Chaos::FPBDRigidsSolver* FScopedSceneLock_Chaos::Solver protected
Definition at line 73 of file ChaosScopedSceneLock.h.
Referenced by FScopedSceneLock_Chaos().
ThreadContext
EPhysicsInterfaceScopedThreadContext FScopedSceneLock_Chaos::ThreadContext = EPhysicsInterfaceScopedThreadContext::External protected
Definition at line 76 of file ChaosScopedSceneLock.h.
The documentation for this struct was generated from the following file:
ChaosScopedSceneLock.h