Unreal Engine 5.6 C++ API: TBVTree< InElementType, InAllocator > Struct Template Reference
TBVTree< InElementType, InAllocator > Struct Template Reference
BVTree - Bounding Volumes Tree.
#include "BVTree.h"
Data Structures
struct FElementBox
Public Types
typedef InElementType FElement
Public Member Functions
TBVTree ()
TBVTree (const TArray< FElement > &InElements)
TBVTree (TArray< FElement > &&InElements)
const TArray< FBox, InAllocator > & GetBoundingBoxes () const
TArray< FElement > & GetElements ()
const TArray< FElement > & GetElements () const
const TArray< int16, InAllocator > & GetNodes () const
void GetOverlapping (const FBox &Box, TArray< FElement > &OutOverlappingElements) const
bool IsEmpty () const
void RecreateTree ()
void RecreateTree (const TArray< FElement > &InElements)
void RecreateTree (TArray< FElement > &&InElements)
Protected Member Functions
void Create (const TArray< FElement > &InElements)
void Create (TArray< FElement > &&InElements)
void CreateCommonInternal ()
void Reset ()
void Subdivide (TArray< FElementBox > &ElementBBoxes, const int StartIndex, const int LimitIndex, int &CurrentNode)
Static Protected Member Functions
static FBox CalcElementBounds (const FElement &)
static FBox CalcNodeBounds (const TArray< FElementBox > &ElementBBoxes, const int StartIndex, const int LimitIndex)
static int GetLongestAxis (const FBox &NodeBounds)
Private Attributes
TArray< FElement > Elements
TArray< FBox, InAllocator > NodeBoundingBoxes
TArray< int16, InAllocator > Nodes
Detailed Description
template<typename InElementType, typename InAllocator = FDefaultAllocator>
struct TBVTree< InElementType, InAllocator >
BVTree - Bounding Volumes Tree.
A binary search tree where each node has a Bounding Volume which is either an element (leaf nodes) or a volume encompassing all of its children (non-leaf nodes).
It provides fast gathering of all bounding volumes overlapping a given FBox (see GetOverlapping).
Users are expected to provide an implementation of CalcElementBounds for ElementType: static FBox CalcElementBounds(const FElement& Element) const
Definition at line 20 of file BVTree.h.
Member Typedef Documentation
FElement
template<typename InElementType, typename InAllocator = FDefaultAllocator> typedef InElementType TBVTree< InElementType, InAllocator >::FElement
Definition at line 22 of file BVTree.h.
Constructor & Destructor Documentation
TBVTree() [1/3]
template<typename InElementType, typename InAllocator = FDefaultAllocator> TBVTree< InElementType, InAllocator >::TBVTree () inline
Definition at line 36 of file BVTree.h.
TBVTree() [2/3]
template<typename InElementType, typename InAllocator = FDefaultAllocator> TBVTree< InElementType, InAllocator >::TBVTree (const TArray< FElement > & InElements) inline
Definition at line 38 of file BVTree.h.
References Create.
TBVTree() [3/3]
template<typename InElementType, typename InAllocator = FDefaultAllocator> TBVTree< InElementType, InAllocator >::TBVTree (TArray< FElement > && InElements) inline
Definition at line 43 of file BVTree.h.
References Create, and MoveTemp().
Member Function Documentation
CalcElementBounds()
template<typename InElementType, typename InAllocator = FDefaultAllocator> FBox TBVTree< InElementType, InAllocator >::CalcElementBounds (const FElement &) static protected
Referenced by CreateCommonInternal().
CalcNodeBounds()
template<typename InElementType, typename InAllocator = FDefaultAllocator> FBox TBVTree< InElementType, InAllocator >::CalcNodeBounds (const TArray< FElementBox > & ElementBBoxes, const int StartIndex, const int LimitIndex) inline static protected
Definition at line 194 of file BVTree.h.
References ForceInit.
Referenced by Subdivide().
Create() [1/2]
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::Create (const TArray< FElement > & InElements) inline protected
Definition at line 154 of file BVTree.h.
References CreateCommonInternal(), and Elements.
Create() [2/2]
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::Create (TArray< FElement > && InElements) inline protected
Definition at line 162 of file BVTree.h.
References CreateCommonInternal(), Elements, and MoveTemp().
CreateCommonInternal()
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::CreateCommonInternal () inline protected
Definition at line 170 of file BVTree.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), CalcElementBounds(), Elements, NodeBoundingBoxes, Nodes, and Subdivide().
Referenced by Create(), Create(), and RecreateTree().
GetBoundingBoxes()
template<typename InElementType, typename InAllocator = FDefaultAllocator> const TArray< FBox, InAllocator > & TBVTree< InElementType, InAllocator >::GetBoundingBoxes () const inline
Definition at line 90 of file BVTree.h.
References NodeBoundingBoxes.
GetElements() [1/2]
template<typename InElementType, typename InAllocator = FDefaultAllocator> TArray< FElement > & TBVTree< InElementType, InAllocator >::GetElements () inline
Definition at line 92 of file BVTree.h.
References Elements.
GetElements() [2/2]
template<typename InElementType, typename InAllocator = FDefaultAllocator> const TArray< FElement > & TBVTree< InElementType, InAllocator >::GetElements () const inline
Definition at line 91 of file BVTree.h.
References Elements.
GetLongestAxis()
template<typename InElementType, typename InAllocator = FDefaultAllocator> int TBVTree< InElementType, InAllocator >::GetLongestAxis (const FBox & NodeBounds) inline static protected
Definition at line 204 of file BVTree.h.
References UE::Math::TBox< T >::Max, UE::Math::TBox< T >::Min, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by Subdivide().
GetNodes()
template<typename InElementType, typename InAllocator = FDefaultAllocator> const TArray< int16, InAllocator > & TBVTree< InElementType, InAllocator >::GetNodes () const inline
Definition at line 89 of file BVTree.h.
References Nodes.
GetOverlapping()
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::GetOverlapping (const FBox & Box, TArray< FElement > & OutOverlappingElements) const inline
Definition at line 69 of file BVTree.h.
References TArray< InElementType, InAllocatorType >::Add(), Box, Elements, NodeBoundingBoxes, and Nodes.
IsEmpty()
template<typename InElementType, typename InAllocator = FDefaultAllocator> bool TBVTree< InElementType, InAllocator >::IsEmpty () const inline
Definition at line 94 of file BVTree.h.
References Nodes.
RecreateTree() [1/3]
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::RecreateTree () inline
Definition at line 50 of file BVTree.h.
References CreateCommonInternal(), NodeBoundingBoxes, and Nodes.
RecreateTree() [2/3]
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::RecreateTree (const TArray< FElement > & InElements) inline
Definition at line 57 of file BVTree.h.
References Create, and Reset().
RecreateTree() [3/3]
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::RecreateTree (TArray< FElement > && InElements) inline
Definition at line 63 of file BVTree.h.
References Create, MoveTemp(), and Reset().
Reset()
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::Reset () inline protected
Definition at line 147 of file BVTree.h.
References Elements, NodeBoundingBoxes, and Nodes.
Referenced by RecreateTree(), and RecreateTree().
Subdivide()
template<typename InElementType, typename InAllocator = FDefaultAllocator> void TBVTree< InElementType, InAllocator >::Subdivide (TArray< FElementBox > & ElementBBoxes, const int StartIndex, const int LimitIndex, int & CurrentNode) inline protected
Definition at line 97 of file BVTree.h.
References A, Axis, B, CalcNodeBounds(), Count, TArray< InElementType, InAllocatorType >::GetData(), GetLongestAxis(), MakeArrayView(), NodeBoundingBoxes, Nodes, Algo::Sort(), and Subdivide().
Referenced by CreateCommonInternal(), and Subdivide().
Field Documentation
Elements
template<typename InElementType, typename InAllocator = FDefaultAllocator> TArray<FElement> TBVTree< InElementType, InAllocator >::Elements private
Definition at line 222 of file BVTree.h.
Referenced by Create(), Create(), CreateCommonInternal(), GetElements(), GetElements(), GetOverlapping(), and Reset().
NodeBoundingBoxes
template<typename InElementType, typename InAllocator = FDefaultAllocator> TArray<FBox, InAllocator> TBVTree< InElementType, InAllocator >::NodeBoundingBoxes private
Definition at line 221 of file BVTree.h.
Referenced by CreateCommonInternal(), GetBoundingBoxes(), GetOverlapping(), RecreateTree(), Reset(), and Subdivide().
Nodes
template<typename InElementType, typename InAllocator = FDefaultAllocator> TArray<int16, InAllocator> TBVTree< InElementType, InAllocator >::Nodes private
Definition at line 220 of file BVTree.h.
Referenced by CreateCommonInternal(), GetNodes(), GetOverlapping(), IsEmpty(), RecreateTree(), Reset(), and Subdivide().
The documentation for this struct was generated from the following file:
BVTree.h