Unreal Engine 5.6 C++ API: TraceServices::TPagedArray< InItemType, InPageType > Class Template Reference
TraceServices::TPagedArray< InItemType, InPageType > Class Template Reference
#include "PagedArray.h"
Public Types
typedef InItemType ItemType
typedef InPageType PageType
typedef TPagedArrayIterator< InItemType, InPageType > TIterator
Public Member Functions
TPagedArray (ILinearAllocator &InAllocator, uint64 InPageSize)
~TPagedArray ()
FORCEINLINE TIterator begin ()
FORCEINLINE TIterator begin () const
template<typename... ArgsType>
ItemType & EmplaceBack (ArgsType &&... Args)
FORCEINLINE TIterator end ()
FORCEINLINE TIterator end () const
ItemType & First ()
const ItemType & First () const
PageType * GetItemPage (uint64 ItemIndex)
const PageType * GetItemPage (uint64 ItemIndex) const
TIterator GetIterator () const
TIterator GetIteratorFromItem (uint64 ItemIndex) const
TIterator GetIteratorFromPage (uint64 PageIndex) const
PageType * GetLastPage ()
const PageType * GetLastPage () const
PageType * GetPage (uint64 PageIndex)
const PageType * GetPage (uint64 PageIndex) const
const PageType * GetPages () const
uint64 GetPageSize () const
ItemType & Insert (uint64 Index)
ItemType & Last ()
const ItemType & Last () const
uint64 Num () const
uint64 NumPages () const
ItemType & operator[] (uint64 Index)
const ItemType & operator[] (uint64 Index) const
ItemType & PushBack ()
Private Attributes
ILinearAllocator & Allocator
PageType * FirstPage = nullptr
PageType * LastPage = nullptr
TArray< PageType > PagesArray
uint64 PageSize
uint64 TotalItemCount = 0
Friends
template<typename ItemType, typename PageType>
class TPagedArrayIterator
Detailed Description
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>>
class TraceServices::TPagedArray< InItemType, InPageType >
Definition at line 553 of file Developer/TraceServices/Public/Common/PagedArray.h.
Member Typedef Documentation
ItemType
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> typedef InItemType TraceServices::TPagedArray< InItemType, InPageType >::ItemType
Definition at line 556 of file Developer/TraceServices/Public/Common/PagedArray.h.
PageType
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> typedef InPageType TraceServices::TPagedArray< InItemType, InPageType >::PageType
Definition at line 557 of file Developer/TraceServices/Public/Common/PagedArray.h.
TIterator
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> typedef TPagedArrayIterator<InItemType, InPageType> TraceServices::TPagedArray< InItemType, InPageType >::TIterator
Definition at line 558 of file Developer/TraceServices/Public/Common/PagedArray.h.
Constructor & Destructor Documentation
TPagedArray()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> TraceServices::TPagedArray< InItemType, InPageType >::TPagedArray (ILinearAllocator & InAllocator, uint64 InPageSize) inline
Definition at line 560 of file Developer/TraceServices/Public/Common/PagedArray.h.
References Allocator, and PageSize.
Referenced by operator[]().
~TPagedArray()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> TraceServices::TPagedArray< InItemType, InPageType >::~TPagedArray () inline
Definition at line 567 of file Developer/TraceServices/Public/Common/PagedArray.h.
References Item, and PagesArray.
Member Function Documentation
begin() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> FORCEINLINE TIterator TraceServices::TPagedArray< InItemType, InPageType >::begin () inline
Definition at line 736 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FORCEINLINE.
begin() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> FORCEINLINE TIterator TraceServices::TPagedArray< InItemType, InPageType >::begin () const inline
Definition at line 737 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FORCEINLINE.
EmplaceBack()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> template<typename... ArgsType> ItemType & TraceServices::TPagedArray< InItemType, InPageType >::EmplaceBack (ArgsType &&... Args) inline
Definition at line 610 of file Developer/TraceServices/Public/Common/PagedArray.h.
References Allocator, FirstPage, Forward(), LastPage, PagesArray, PageSize, and TotalItemCount.
end() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> FORCEINLINE TIterator TraceServices::TPagedArray< InItemType, InPageType >::end () inline
Definition at line 738 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FORCEINLINE, and TotalItemCount.
end() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> FORCEINLINE TIterator TraceServices::TPagedArray< InItemType, InPageType >::end () const inline
Definition at line 739 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FORCEINLINE, and TotalItemCount.
First() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> ItemType & TraceServices::TPagedArray< InItemType, InPageType >::First () inline
Definition at line 712 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage, and Item.
Referenced by TraceServices::GetElementRangeOverlappingGivenRange().
First() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const ItemType & TraceServices::TPagedArray< InItemType, InPageType >::First () const inline
Definition at line 718 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage, and Item.
GetItemPage() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetItemPage (uint64 ItemIndex) inline
Definition at line 666 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage, and PageSize.
GetItemPage() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetItemPage (uint64 ItemIndex) const inline
Definition at line 672 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage, and PageSize.
GetIterator()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> TIterator TraceServices::TPagedArray< InItemType, InPageType >::GetIterator () const inline
Definition at line 678 of file Developer/TraceServices/Public/Common/PagedArray.h.
GetIteratorFromItem()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> TIterator TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem (uint64 ItemIndex) const inline
Definition at line 688 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwardsDownSampled(), TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::EnumerateEventsDownSampled(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEventInfo(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
GetIteratorFromPage()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> TIterator TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromPage (uint64 PageIndex) const inline
Definition at line 683 of file Developer/TraceServices/Public/Common/PagedArray.h.
References PageSize.
GetLastPage() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetLastPage () inline
Definition at line 646 of file Developer/TraceServices/Public/Common/PagedArray.h.
References LastPage.
GetLastPage() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetLastPage () const inline
Definition at line 651 of file Developer/TraceServices/Public/Common/PagedArray.h.
References LastPage.
GetPage() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetPage (uint64 PageIndex) inline
Definition at line 656 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage.
GetPage() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetPage (uint64 PageIndex) const inline
Definition at line 661 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage.
GetPages()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const PageType * TraceServices::TPagedArray< InItemType, InPageType >::GetPages () const inline
Definition at line 693 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage.
Referenced by TraceServices::GetData(), TraceServices::GetElementRangeOverlappingGivenRange(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
GetPageSize()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> uint64 TraceServices::TPagedArray< InItemType, InPageType >::GetPageSize () const inline
Definition at line 584 of file Developer/TraceServices/Public/Common/PagedArray.h.
References PageSize.
Referenced by TraceServices::GetElementRangeOverlappingGivenRange(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
Insert()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> ItemType & TraceServices::TPagedArray< InItemType, InPageType >::Insert (uint64 Index) inline
Definition at line 625 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage, PagesArray, PageSize, PushBack(), and TotalItemCount.
Last() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> ItemType & TraceServices::TPagedArray< InItemType, InPageType >::Last () inline
Definition at line 724 of file Developer/TraceServices/Public/Common/PagedArray.h.
References Item, and LastPage.
Referenced by TraceServices::GetElementRangeOverlappingGivenRange().
Last() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const ItemType & TraceServices::TPagedArray< InItemType, InPageType >::Last () const inline
Definition at line 730 of file Developer/TraceServices/Public/Common/PagedArray.h.
References Item, and LastPage.
Num()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> uint64 TraceServices::TPagedArray< InItemType, InPageType >::Num () const inline
Definition at line 579 of file Developer/TraceServices/Public/Common/PagedArray.h.
References TotalItemCount.
Referenced by TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AddScopeEntry(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AppendBeginEvent(), TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwardsDownSampled(), TraceServices::GetElementRangeOverlappingGivenRange(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
NumPages()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> uint64 TraceServices::TPagedArray< InItemType, InPageType >::NumPages () const inline
Definition at line 589 of file Developer/TraceServices/Public/Common/PagedArray.h.
References PagesArray.
Referenced by TraceServices::GetElementRangeOverlappingGivenRange(), TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
operator[]() [1/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> ItemType & TraceServices::TPagedArray< InItemType, InPageType >::operator[] (uint64 Index) inline
Definition at line 698 of file Developer/TraceServices/Public/Common/PagedArray.h.
References FirstPage, Item, and PageSize.
operator[]() [2/2]
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> const ItemType & TraceServices::TPagedArray< InItemType, InPageType >::operator[] (uint64 Index) const inline
Definition at line 707 of file Developer/TraceServices/Public/Common/PagedArray.h.
References TPagedArray().
PushBack()
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> ItemType & TraceServices::TPagedArray< InItemType, InPageType >::PushBack () inline
Definition at line 594 of file Developer/TraceServices/Public/Common/PagedArray.h.
References Allocator, FirstPage, LastPage, PagesArray, PageSize, and TotalItemCount.
Referenced by TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AddEvent(), and Insert().
Friends And Related Symbol Documentation
TPagedArrayIterator
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> template<typename ItemType, typename PageType> friend class TPagedArrayIterator friend
Definition at line 743 of file Developer/TraceServices/Public/Common/PagedArray.h.
References TPagedArrayIterator.
Referenced by TPagedArrayIterator.
Field Documentation
Allocator
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> ILinearAllocator& TraceServices::TPagedArray< InItemType, InPageType >::Allocator private
Definition at line 745 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by TPagedArray(), EmplaceBack(), and PushBack().
FirstPage
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> PageType* TraceServices::TPagedArray< InItemType, InPageType >::FirstPage = nullptr private
Definition at line 747 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by EmplaceBack(), First(), First(), GetItemPage(), GetItemPage(), GetPage(), GetPage(), GetPages(), Insert(), operator[](), and PushBack().
LastPage
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> PageType* TraceServices::TPagedArray< InItemType, InPageType >::LastPage = nullptr private
Definition at line 748 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by EmplaceBack(), GetLastPage(), GetLastPage(), Last(), Last(), and PushBack().
PagesArray
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> TArray<PageType> TraceServices::TPagedArray< InItemType, InPageType >::PagesArray private
Definition at line 746 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by ~TPagedArray(), EmplaceBack(), Insert(), NumPages(), and PushBack().
PageSize
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> uint64 TraceServices::TPagedArray< InItemType, InPageType >::PageSize private
Definition at line 749 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by TPagedArray(), EmplaceBack(), GetItemPage(), GetItemPage(), GetIteratorFromPage(), GetPageSize(), Insert(), operator[](), and PushBack().
TotalItemCount
template<typename InItemType, typename InPageType = TPagedArrayPage<InItemType>> uint64 TraceServices::TPagedArray< InItemType, InPageType >::TotalItemCount = 0 private
Definition at line 750 of file Developer/TraceServices/Public/Common/PagedArray.h.
Referenced by EmplaceBack(), end(), end(), Insert(), Num(), and PushBack().
The documentation for this class was generated from the following file:
Developer/TraceServices/Public/Common/PagedArray.h