Unreal Engine 5.6 C++ API: ForceFeedbackComponent.h File Reference
ForceFeedbackComponent.h File Reference
#include "GameFramework/ForceFeedbackAttenuation.h"
#include "Components/SceneComponent.h"
#include "Tickable.h"
#include "UObject/GCObject.h"
#include "ForceFeedbackComponent.generated.h"
Data Structures
class FForceFeedbackManager
class UForceFeedbackComponent
Functions
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnForceFeedbackFinished, UForceFeedbackComponent *, ForceFeedbackComponent)
called when we finish playing forcefeedback effect, either because it played to completion or because a Stop() call turned it off early
UCLASS ()
ForceFeedbackComponent allows placing a rumble effect in to the world and having it apply to player characters who come near it.
Variables
hidecategories =(Object, ActorComponent, Physics, Rendering, Mobility, LOD)
meta =(BlueprintSpawnableComponent)
ShowCategories =Trigger
Function Documentation
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam (FOnForceFeedbackFinished , UForceFeedbackComponent * , ForceFeedbackComponent)
called when we finish playing forcefeedback effect, either because it played to completion or because a Stop() call turned it off early
UCLASS()
UCLASS ()
ForceFeedbackComponent allows placing a rumble effect in to the world and having it apply to player characters who come near it.
Variable Documentation
hidecategories
hidecategories =(Object, ActorComponent, Physics, Rendering, Mobility, LOD)
Definition at line 58 of file ForceFeedbackComponent.h.
meta
meta =(BlueprintSpawnableComponent)
Definition at line 58 of file ForceFeedbackComponent.h.
Referenced by UForceFeedbackComponent::UFUNCTION(), UForceFeedbackComponent::UPROPERTY(), and UForceFeedbackComponent::UPROPERTY().
ShowCategories
ShowCategories =Trigger
Definition at line 58 of file ForceFeedbackComponent.h.