Unreal Engine 5.6 C++ API: FSlateNotificationManager Class Reference
FSlateNotificationManager Class Reference
A class which manages a group of notification windows.
#include "NotificationManager.h"
Data Structures
struct FRegionalNotificationList
A list of notifications, bound to a particular region.
Public Member Functions
TSharedPtr< SNotificationItem > AddNotification (const FNotificationInfo &Info)
Adds a floating notification.
bool AreNotificationsAllowed () const
Checks whether notifications are currently enabled.
void CancelProgressNotification (FProgressNotificationHandle InHandle)
Cancels an active notification.
void ForceNotificationsInFront (const TSharedRef< SWindow > InWindow)
Called back from the SlateApplication when a window is activated/resized We need to keep notifications topmost in the z-order so we manage it here directly as there isn't a cross-platform OS-level way of making a 'topmost child'.
void GetWindows (TArray< TSharedRef< SWindow > > &OutWindows) const
Gets all the windows that represent notifications.
void QueueNotification (FNotificationInfo *Info)
Thread safe method of queuing a notification for presentation on the next tick.
void RegisterStagedNotification (TSharedPtr< IAsyncTaskNotificationImpl > InNotification)
Register a Staged Async Notification, allowing the NotificationManager to keep a reference to it.
void SetAllowNotifications (const bool bShouldAllow)
Sets whether notifications should be displayed at all.
void SetProgressNotificationHandler (IProgressNotificationHandler *NewHandler)
Sets the progress notification handler for the current application.
void SetRootWindow (const TSharedRef< SWindow > InRootWindow)
Provide a window under which all notifications should nest.
FProgressNotificationHandle StartProgressNotification (FText DisplayText, int32 TotalWorkToDo)
Begin a progress notification.
void Tick ()
Update the manager.
void UnregisterStagedNotification (TSharedPtr< IAsyncTaskNotificationImpl > InNotification)
Unregister a previously added Staged Notification.
void UpdateProgressNotification (FProgressNotificationHandle InHandle, int32 TotalWorkDone, int32 UpdatedTotalWorkToDo=0, FText UpdatedDisplayText=FText::GetEmpty())
Updates a progress notification.
Static Public Member Functions
static FSlateNotificationManager & Get ()
Gets the instance of this manager.
Protected Member Functions
FSlateNotificationManager ()
Protect constructor as this is a singleton.
TSharedRef< SNotificationList > CreateStackForArea (const FSlateRect &InRectangle, TSharedPtr< SWindow > Window)
Create a notification list for the specified screen rectangle.
void ShutdownOnPreExit ()
FCoreDelegates::OnPreExit shutdown callback.
Private Attributes
bool bAllowNotifications = true
Whether notifications should be displayed or not.
FAutoConsoleVariableRef CVarAllowNotifications
CVar allowing us to control the display of notifications.
TLockFreePointerListLIFO< FNotificationInfo > PendingNotifications
Thread safe queue of notifications to display.
IProgressNotificationHandler * ProgressNotificationHandler = nullptr
Handle to a system which updates progress notifications (e.g a status bar)
TArray< FRegionalNotificationList > RegionalLists
An array of notification lists grouped by work area regions.
TWeakPtr< SWindow > RootWindowPtr
A window under which all of the notification windows will nest.
FCriticalSection StagedNotificationCS
Critical Section to guard access to StagedNotifications.
TArray< TSharedPtr< IAsyncTaskNotificationImpl > > StagedNotifications
An array of staged notifications.
Static Private Attributes
static int32 ProgressHandleCounter
Counter used to create progress handles.
Friends
class SNotificationList
Detailed Description
A class which manages a group of notification windows.
Definition at line 76 of file NotificationManager.h.
Constructor & Destructor Documentation
FSlateNotificationManager()
FSlateNotificationManager::FSlateNotificationManager () protected
Protect constructor as this is a singleton.
Referenced by Get().
Member Function Documentation
AddNotification()
TSharedPtr< SNotificationItem > FSlateNotificationManager::AddNotification (const FNotificationInfo & Info)
Adds a floating notification.
Parameters
Info Contains various settings used to initialize the notification
References Info.
AreNotificationsAllowed()
bool FSlateNotificationManager::AreNotificationsAllowed () const inline
Checks whether notifications are currently enabled.
Returns
true if allowed, false otherwise.
Definition at line 165 of file NotificationManager.h.
References bAllowNotifications.
CancelProgressNotification()
void FSlateNotificationManager::CancelProgressNotification (FProgressNotificationHandle InHandle)
Cancels an active notification.
CreateStackForArea()
TSharedRef< SNotificationList > FSlateNotificationManager::CreateStackForArea (const FSlateRect & InRectangle, TSharedPtr< SWindow > Window) protected
Create a notification list for the specified screen rectangle.
ForceNotificationsInFront()
void FSlateNotificationManager::ForceNotificationsInFront (const TSharedRef< SWindow > InWindow)
Called back from the SlateApplication when a window is activated/resized We need to keep notifications topmost in the z-order so we manage it here directly as there isn't a cross-platform OS-level way of making a 'topmost child'.
Parameters
ActivateEvent Information about the activation event
Get()
FSlateNotificationManager & FSlateNotificationManager::Get () static
Gets the instance of this manager.
References FSlateNotificationManager().
GetWindows()
void FSlateNotificationManager::GetWindows (TArray< TSharedRef< SWindow > > & OutWindows) const
Gets all the windows that represent notifications.
Returns
an array of windows that contain notifications.
QueueNotification()
void FSlateNotificationManager::QueueNotification (FNotificationInfo * Info)
Thread safe method of queuing a notification for presentation on the next tick.
Parameters
Info Pointer to heap allocated notification info. Released by FSlateNotificationManager once the notification is displayed;
References Info.
RegisterStagedNotification()
void FSlateNotificationManager::RegisterStagedNotification (TSharedPtr< IAsyncTaskNotificationImpl > InNotification)
Register a Staged Async Notification, allowing the NotificationManager to keep a reference to it.
SetAllowNotifications()
void FSlateNotificationManager::SetAllowNotifications (const bool bShouldAllow) inline
Sets whether notifications should be displayed at all.
Note, notifications can be disabled via console variable Slate.bAllowNotificationWidget.
Parameters
bShouldAllow Whether notifications should be enabled. It defaults to on.
Definition at line 155 of file NotificationManager.h.
References bAllowNotifications.
SetProgressNotificationHandler()
void FSlateNotificationManager::SetProgressNotificationHandler (IProgressNotificationHandler * NewHandler)
Sets the progress notification handler for the current application.
Only one handler is used at a time. This handler is not managed in any way. If your handler is being destroyed call SetProgressNotificationHandler(nullptr)
SetRootWindow()
void FSlateNotificationManager::SetRootWindow (const TSharedRef< SWindow > InRootWindow)
Provide a window under which all notifications should nest.
ShutdownOnPreExit()
void FSlateNotificationManager::ShutdownOnPreExit () protected
FCoreDelegates::OnPreExit shutdown callback.
StartProgressNotification()
FProgressNotificationHandle FSlateNotificationManager::StartProgressNotification (FText DisplayText, int32 TotalWorkToDo)
Begin a progress notification.
These notifications should be used for background work not blocking work. Use SlowTask for blocking work
Parameters
DisplayText Display text used to describe the type of work to the user
TotalWorkToDo Arbitrary number of work units to perform. If more than one progress notification is active this work is summed with any other active notifications. This value usually represents the number of steps to be completed
Returns
NotificationHandle A handle that can be used to update the progress or cancel the notification
Tick()
void FSlateNotificationManager::Tick ()
Update the manager.
UnregisterStagedNotification()
void FSlateNotificationManager::UnregisterStagedNotification (TSharedPtr< IAsyncTaskNotificationImpl > InNotification)
Unregister a previously added Staged Notification.
UpdateProgressNotification()
void FSlateNotificationManager::UpdateProgressNotification (FProgressNotificationHandle InHandle, int32 TotalWorkDone, int32 UpdatedTotalWorkToDo = 0, FText UpdatedDisplayText = FText::GetEmpty())
Updates a progress notification.
Parameters
InHandle Handle to the notification that was previously created with StartProgressNotification
TotalWorkDone The total number of work uits done for the notification. This is NOT an incremental value.
UpdatedTotalWorkToDo (Optional) If the total work to do changes you can update the value here. Note that if the total work left increases but the total work done does not, the progress bar may go backwards
UpdatedDisplayText (Optional) Updated display text of the notification
Returns
NotificationHandle A handle that can be used to update the progress or cancel the notification
References FText::GetEmpty().
Friends And Related Symbol Documentation
SNotificationList
friend class SNotificationList friend
Definition at line 78 of file NotificationManager.h.
References SNotificationList.
Referenced by SNotificationList.
Field Documentation
bAllowNotifications
bool FSlateNotificationManager::bAllowNotifications = true private
Whether notifications should be displayed or not.
This can be used to globally suppress notification pop-ups
Definition at line 233 of file NotificationManager.h.
Referenced by AreNotificationsAllowed(), and SetAllowNotifications().
CVarAllowNotifications
FAutoConsoleVariableRef FSlateNotificationManager::CVarAllowNotifications private
CVar allowing us to control the display of notifications.
Definition at line 236 of file NotificationManager.h.
PendingNotifications
TLockFreePointerListLIFO<FNotificationInfo> FSlateNotificationManager::PendingNotifications private
Thread safe queue of notifications to display.
Definition at line 221 of file NotificationManager.h.
ProgressHandleCounter
int32 FSlateNotificationManager::ProgressHandleCounter static private
Counter used to create progress handles.
Definition at line 230 of file NotificationManager.h.
ProgressNotificationHandler
IProgressNotificationHandler* FSlateNotificationManager::ProgressNotificationHandler = nullptr private
Handle to a system which updates progress notifications (e.g a status bar)
Definition at line 212 of file NotificationManager.h.
RegionalLists
TArray<FRegionalNotificationList> FSlateNotificationManager::RegionalLists private
An array of notification lists grouped by work area regions.
Definition at line 218 of file NotificationManager.h.
RootWindowPtr
TWeakPtr<SWindow> FSlateNotificationManager::RootWindowPtr private
A window under which all of the notification windows will nest.
Definition at line 215 of file NotificationManager.h.
StagedNotificationCS
FCriticalSection FSlateNotificationManager::StagedNotificationCS private
Critical Section to guard access to StagedNotifications.
Definition at line 227 of file NotificationManager.h.
StagedNotifications
TArray<TSharedPtr<IAsyncTaskNotificationImpl> > FSlateNotificationManager::StagedNotifications private
An array of staged notifications.
Definition at line 224 of file NotificationManager.h.
The documentation for this class was generated from the following file:
NotificationManager.h