Unreal Engine 5.6 C++ API: UScriptStruct::ICppStructOps Struct Reference
UScriptStruct::ICppStructOps Struct Reference abstract
Interface to template to manage dynamic access to C++ struct construction and destruction.
#include "Class.h"
Data Structures
struct FCapabilities
Filled by implementation classes to report their capabilities.
Public Types
typedef void(* TPointerToAddStructReferencedObjects) (void *A, class FReferenceCollector &Collector)
return a pointer to a function that can add referenced objects
Public Member Functions
ICppStructOps (int32 InSize, int32 InAlignment)
Constructor.
virtual ~ICppStructOps ()
virtual TPointerToAddStructReferencedObjects AddStructReferencedObjects ()=0
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain, const void *Data) const =0
Returns true if this struct would allow the given property to be edited in the details panel.
virtual void ClearIntrusiveOptionalValue (void *Data) const =0
Reset an optional value to its unset state.
virtual void Construct (void *Dest)=0
Call the C++ constructor.
virtual void ConstructForTests (void *Dest)=0
Call the C++ constructor without value-init (new T instead of new T())
virtual bool Copy (void *Dest, void const *Src, int32 ArrayDim)=0
Copy this structure.
virtual void Destruct (void *Dest)=0
Call the C++ destructor.
virtual bool ExportTextItem (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, class UObject *Parent, int32 PortFlags, class UObject *ExportRootScope)=0
export this structure
virtual bool FindInnerPropertyInstance (FName PropertyName, const void *Data, const FProperty *&OutProp, const void *&OutData) const =0
FORCEINLINE int32 GetAlignment () const
return the alignof() of this structure
virtual FCapabilities GetCapabilities () const =0
returns struct capabilities
EPropertyFlags GetComputedPropertyFlags () const
Returns property flag values that can be computed at compile time.
virtual void GetPreloadDependencies (void *Data, TArray< UObject * > &OutDeps)=0
Call PreloadDependencies on this structure.
FORCEINLINE int32 GetSize () const
return the sizeof() of this structure
virtual uint32 GetStructTypeHash (const void *Src)=0
Calls GetTypeHash if enabled.
bool HasAddStructReferencedObjects () const
return true if this struct has custom GC code
bool HasCanEditChange () const
Returns true if this struct wants to indicate whether a property can be edited in the details panel.
bool HasClearOnFinishDestroy () const
return true if this struct has a ClearOnFinishDestroy
bool HasCopy () const
return true if this struct can copy
bool HasDestructor () const
return false if this destructor can be skipped
bool HasExportTextItem () const
return true if this struct can export
bool HasFindInnerPropertyInstance () const
bool HasGetTypeHash () const
return true if this struct has a GetTypeHash
bool HasIdentical () const
return true if this struct can compare
bool HasImportTextItem () const
return true if this struct can import
bool HasIntrusiveUnsetOptionalState () const
Return true if this type can be constructed with FIntrusiveUnsetOptionalState for TOptional.
bool HasNetDeltaSerializer () const
return true if this struct can net delta serialize delta (serialize a network delta from a base state)
bool HasNetSerializer () const
return true if this struct can net serialize
bool HasNetSharedSerialization () const
return true if this can share net serialization across connections
bool HasNoopConstructor () const
return true if this class has a no-op constructor and takes EForceInit to init
bool HasPostScriptConstruct () const
return true if this class implements a post script construct call
bool HasPostSerialize () const
return true if this class implements a post serialize call
bool HasSerializeFromMismatchedTag () const
return true if this class wants to serialize from some other tag (usually for conversion purposes)
bool HasSerializer () const
return true if this class can serialize
bool HasSerializerObjectReferences (EPropertyObjectReferenceType Type) const
returns true if the native serialize functions may serialize object references of the given type
bool HasStructuredSerializeFromMismatchedTag () const
bool HasStructuredSerializer () const
return true if this class can serialize to a structured archive
bool HasVisitor () const
Returns true if this struct wants to indicate whether it has a custom impl for visiting properties.
bool HasZeroConstructor () const
return true if memset can be used instead of the constructor
virtual bool Identical (const void *A, const void *B, uint32 PortFlags, bool &bOutResult)=0
Compare this structure.
virtual bool ImportTextItem (const TCHAR *&Buffer, void *Data, int32 PortFlags, class UObject *OwnerObject, FOutputDevice *ErrorText)=0
import this structure
virtual void InitializeIntrusiveUnsetOptionalValue (void *Data) const =0
Construct an unset optional value.
bool IsAbstract () const
return true if this struct is abstract
virtual bool IsIntrusiveOptionalSafeForGC () const =0
Used for assertions only: confirms that this type has certified that its object reference fields are safe for the GC to visit while the struct is in its intrusive unset optional state.
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const =0
Return true if the optional value at Data is in an unset state.
bool IsPlainOldData () const
return true if this struct should be memcopied
bool IsUECoreType () const
return true if this struct is one of the UE Core types (and is include in CoreMinimal.h)
bool IsUECoreVariant () const
return true if this struct is one of the UE Core types (and is include in CoreMinimal.h)
virtual bool NetDeltaSerialize (FNetDeltaSerializeInfo &DeltaParms, void *Data)=0
Net serialize delta this structure.
virtual bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess, void *Data)=0
Net serialize this structure.
virtual void PostScriptConstruct (void *Data)=0
Call PostScriptConstruct on this structure.
virtual void PostSerialize (const FArchive &Ar, void *Data)=0
Call PostSerialize on this structure.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const =0
virtual bool Serialize (FArchive &Ar, void *Data, UStruct *DefaultsStruct, const void *Defaults)=0
Serialize this structure.
virtual bool Serialize (FStructuredArchive::FSlot Slot, void *Data, UStruct *DefaultsStruct, const void *Defaults)=0
virtual bool SerializeFromMismatchedTag (struct FPropertyTag const &Tag, FArchive &Ar, void *Data)=0
Serialize this structure, from some other tag.
virtual bool StructuredSerializeFromMismatchedTag (struct FPropertyTag const &Tag, FStructuredArchive::FSlot Slot, void *Data)=0
UE_DEPRECATED (5.6, "Use the overload of Serialize with defaults.") virtual bool Serialize(FArchive &Ar
UE_DEPRECATED (5.6, "Use the overload of Serialize with defaults.") virtual bool Serialize(FStructuredArchive
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const =0
Structs property visitor signature.
Data Fields
void * Data
Private Attributes
const int32 Alignment
alignof() of the structure
const int32 Size
sizeof() of the structure
Detailed Description
Interface to template to manage dynamic access to C++ struct construction and destruction.
Definition at line 1009 of file Class.h.
Member Typedef Documentation
TPointerToAddStructReferencedObjects
typedef void(* UScriptStruct::ICppStructOps::TPointerToAddStructReferencedObjects) (void *A, class FReferenceCollector &Collector)
return a pointer to a function that can add referenced objects
Returns
true if the copy was imported, otherwise it will fall back to FStructProperty::ImportText
Definition at line 1252 of file Class.h.
Constructor & Destructor Documentation
ICppStructOps()
UScriptStruct::ICppStructOps::ICppStructOps (int32 InSize, int32 InAlignment) inline
Constructor.
Parameters
InSize sizeof() of the structure
Definition at line 1051 of file Class.h.
References Alignment, UScriptStruct::InAlignment, UScriptStruct::InSize, and Size.
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::TCppStructOps().
~ICppStructOps()
virtual UScriptStruct::ICppStructOps::~ICppStructOps () inline virtual
Definition at line 1056 of file Class.h.
Member Function Documentation
AddStructReferencedObjects()
virtual TPointerToAddStructReferencedObjects UScriptStruct::ICppStructOps::AddStructReferencedObjects () pure virtual
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
CanEditChange()
virtual bool UScriptStruct::ICppStructOps::CanEditChange (const FEditPropertyChain & PropertyChain, const void * Data) const pure virtual
Returns true if this struct would allow the given property to be edited in the details panel.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
ClearIntrusiveOptionalValue()
virtual void UScriptStruct::ICppStructOps::ClearIntrusiveOptionalValue (void * Data) const pure virtual
Reset an optional value to its unset state.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
Construct()
virtual void UScriptStruct::ICppStructOps::Construct (void * Dest) pure virtual
Call the C++ constructor.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
Referenced by USTRUCT(), and USTRUCT().
ConstructForTests()
virtual void UScriptStruct::ICppStructOps::ConstructForTests (void * Dest) pure virtual
Call the C++ constructor without value-init (new T instead of new T())
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
Copy()
virtual bool UScriptStruct::ICppStructOps::Copy (void * Dest, void const * Src, int32 ArrayDim) pure virtual
Copy this structure.
Returns
true if the copy was handled, otherwise it will fall back to CopySingleValue
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
Referenced by USTRUCT(), and USTRUCT().
Destruct()
virtual void UScriptStruct::ICppStructOps::Destruct (void * Dest) pure virtual
Call the C++ destructor.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
ExportTextItem()
virtual bool UScriptStruct::ICppStructOps::ExportTextItem (FString & ValueStr, const void * PropertyValue, const void * DefaultValue, class UObject * Parent, int32 PortFlags, class UObject * ExportRootScope) pure virtual
export this structure
Returns
true if the copy was exported, otherwise it will fall back to FStructProperty::ExportTextItem
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References UObject::UObject(), and Parent.
FindInnerPropertyInstance()
virtual bool UScriptStruct::ICppStructOps::FindInnerPropertyInstance (FName PropertyName, const void * Data, const FProperty *& OutProp, const void *& OutData) const pure virtual
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data, and PropertyName.
GetAlignment()
FORCEINLINE int32 UScriptStruct::ICppStructOps::GetAlignment () const inline
return the alignof() of this structure
Definition at line 1088 of file Class.h.
References Alignment, and FORCEINLINE.
Referenced by USTRUCT(), and USTRUCT().
GetCapabilities()
virtual FCapabilities UScriptStruct::ICppStructOps::GetCapabilities () const pure virtual
returns struct capabilities
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
Referenced by GetComputedPropertyFlags(), HasAddStructReferencedObjects(), HasCanEditChange(), HasClearOnFinishDestroy(), HasCopy(), HasDestructor(), HasExportTextItem(), HasFindInnerPropertyInstance(), HasGetTypeHash(), HasIdentical(), HasImportTextItem(), HasIntrusiveUnsetOptionalState(), HasNetDeltaSerializer(), HasNetSerializer(), HasNetSharedSerialization(), HasNoopConstructor(), HasPostScriptConstruct(), HasPostSerialize(), HasSerializeFromMismatchedTag(), HasSerializer(), HasSerializerObjectReferences(), HasStructuredSerializeFromMismatchedTag(), HasStructuredSerializer(), HasVisitor(), HasZeroConstructor(), IsAbstract(), IsPlainOldData(), IsUECoreType(), and IsUECoreVariant().
GetComputedPropertyFlags()
EPropertyFlags UScriptStruct::ICppStructOps::GetComputedPropertyFlags () const inline
Returns property flag values that can be computed at compile time.
Definition at line 1282 of file Class.h.
References UScriptStruct::ICppStructOps::FCapabilities::ComputedPropertyFlags, and GetCapabilities().
GetPreloadDependencies()
virtual void UScriptStruct::ICppStructOps::GetPreloadDependencies (void * Data, TArray< UObject * > & OutDeps) pure virtual
Call PreloadDependencies on this structure.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
GetSize()
FORCEINLINE int32 UScriptStruct::ICppStructOps::GetSize () const inline
return the sizeof() of this structure
Definition at line 1083 of file Class.h.
References FORCEINLINE, and Size.
Referenced by USTRUCT(), and USTRUCT().
GetStructTypeHash()
virtual uint32 UScriptStruct::ICppStructOps::GetStructTypeHash (const void * Src) pure virtual
Calls GetTypeHash if enabled.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
HasAddStructReferencedObjects()
bool UScriptStruct::ICppStructOps::HasAddStructReferencedObjects () const inline
return true if this struct has custom GC code
Definition at line 1239 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasAddStructReferencedObjects.
HasCanEditChange()
bool UScriptStruct::ICppStructOps::HasCanEditChange () const inline
Returns true if this struct wants to indicate whether a property can be edited in the details panel.
Definition at line 1318 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasCanEditChange.
HasClearOnFinishDestroy()
bool UScriptStruct::ICppStructOps::HasClearOnFinishDestroy () const inline
return true if this struct has a ClearOnFinishDestroy
Definition at line 1294 of file Class.h.
References UScriptStruct::ICppStructOps::FCapabilities::ClearOnFinishDestroy, and GetCapabilities().
HasCopy()
bool UScriptStruct::ICppStructOps::HasCopy () const inline
return true if this struct can copy
Definition at line 1189 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasCopy.
HasDestructor()
bool UScriptStruct::ICppStructOps::HasDestructor () const inline
return false if this destructor can be skipped
Definition at line 1076 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasDestructor.
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::ExportTextItem().
HasExportTextItem()
bool UScriptStruct::ICppStructOps::HasExportTextItem () const inline
return true if this struct can export
Definition at line 1211 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasExportTextItem.
HasFindInnerPropertyInstance()
bool UScriptStruct::ICppStructOps::HasFindInnerPropertyInstance () const inline
Definition at line 1232 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasFindInnerPropertyInstance.
HasGetTypeHash()
bool UScriptStruct::ICppStructOps::HasGetTypeHash () const inline
return true if this struct has a GetTypeHash
Definition at line 1273 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasGetTypeHash.
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::GetStructTypeHash(), and UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateAnimatedBoneAttributes().
HasIdentical()
bool UScriptStruct::ICppStructOps::HasIdentical () const inline
return true if this struct can compare
Definition at line 1200 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasIdentical.
HasImportTextItem()
bool UScriptStruct::ICppStructOps::HasImportTextItem () const inline
return true if this struct can import
Definition at line 1222 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasImportTextItem.
HasIntrusiveUnsetOptionalState()
bool UScriptStruct::ICppStructOps::HasIntrusiveUnsetOptionalState () const inline
Return true if this type can be constructed with FIntrusiveUnsetOptionalState for TOptional.
Definition at line 1300 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasIntrusiveUnsetOptionalState.
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::GetCapabilities().
HasNetDeltaSerializer()
bool UScriptStruct::ICppStructOps::HasNetDeltaSerializer () const inline
return true if this struct can net delta serialize delta (serialize a network delta from a base state)
Definition at line 1149 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasNetDeltaSerializer.
HasNetSerializer()
bool UScriptStruct::ICppStructOps::HasNetSerializer () const inline
return true if this struct can net serialize
Definition at line 1132 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasNetSerializer.
HasNetSharedSerialization()
bool UScriptStruct::ICppStructOps::HasNetSharedSerialization () const inline
return true if this can share net serialization across connections
Definition at line 1138 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasNetSharedSerialization.
HasNoopConstructor()
bool UScriptStruct::ICppStructOps::HasNoopConstructor () const inline
return true if this class has a no-op constructor and takes EForceInit to init
Definition at line 1062 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasNoopConstructor.
HasPostScriptConstruct()
bool UScriptStruct::ICppStructOps::HasPostScriptConstruct () const inline
return true if this class implements a post script construct call
Definition at line 1160 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasPostScriptConstruct.
HasPostSerialize()
bool UScriptStruct::ICppStructOps::HasPostSerialize () const inline
return true if this class implements a post serialize call
Definition at line 1124 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasPostSerialize.
HasSerializeFromMismatchedTag()
bool UScriptStruct::ICppStructOps::HasSerializeFromMismatchedTag () const inline
return true if this class wants to serialize from some other tag (usually for conversion purposes)
Definition at line 1256 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasSerializeFromMismatchedTag.
HasSerializer()
bool UScriptStruct::ICppStructOps::HasSerializer () const inline
return true if this class can serialize
Definition at line 1094 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasSerializer.
HasSerializerObjectReferences()
bool UScriptStruct::ICppStructOps::HasSerializerObjectReferences (EPropertyObjectReferenceType Type) const inline
returns true if the native serialize functions may serialize object references of the given type
Definition at line 1244 of file Class.h.
References EnumHasAnyFlags(), GetCapabilities(), and HasSerializerObjectReferences().
Referenced by HasSerializerObjectReferences().
HasStructuredSerializeFromMismatchedTag()
bool UScriptStruct::ICppStructOps::HasStructuredSerializeFromMismatchedTag () const inline
Definition at line 1260 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasStructuredSerializeFromMismatchedTag.
HasStructuredSerializer()
bool UScriptStruct::ICppStructOps::HasStructuredSerializer () const inline
return true if this class can serialize to a structured archive
Definition at line 1099 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasStructuredSerializer.
HasVisitor()
bool UScriptStruct::ICppStructOps::HasVisitor () const inline
Returns true if this struct wants to indicate whether it has a custom impl for visiting properties.
Definition at line 1327 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasVisitor.
HasZeroConstructor()
bool UScriptStruct::ICppStructOps::HasZeroConstructor () const inline
return true if memset can be used instead of the constructor
Definition at line 1067 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::HasZeroConstructor.
Referenced by UScriptStruct::TCppStructOps< CPPSTRUCT >::ExportTextItem().
Identical()
virtual bool UScriptStruct::ICppStructOps::Identical (const void * A, const void * B, uint32 PortFlags, bool & bOutResult) pure virtual
Compare this structure.
Returns
true if the comparison was performed. bOutResult contains the result of the comparison.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References A, and B.
ImportTextItem()
virtual bool UScriptStruct::ICppStructOps::ImportTextItem (const TCHAR *& Buffer, void * Data, int32 PortFlags, class UObject * OwnerObject, FOutputDevice * ErrorText) pure virtual
import this structure
Returns
true if the copy was imported, otherwise it will fall back to FStructProperty::ImportText
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References UObject::UObject(), Buffer, and Data.
InitializeIntrusiveUnsetOptionalValue()
virtual void UScriptStruct::ICppStructOps::InitializeIntrusiveUnsetOptionalValue (void * Data) const pure virtual
Construct an unset optional value.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
IsAbstract()
bool UScriptStruct::ICppStructOps::IsAbstract () const inline
return true if this struct is abstract
Definition at line 1288 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::IsAbstract.
IsIntrusiveOptionalSafeForGC()
virtual bool UScriptStruct::ICppStructOps::IsIntrusiveOptionalSafeForGC () const pure virtual
Used for assertions only: confirms that this type has certified that its object reference fields are safe for the GC to visit while the struct is in its intrusive unset optional state.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
IsIntrusiveOptionalValueSet()
virtual bool UScriptStruct::ICppStructOps::IsIntrusiveOptionalValueSet (const void * Data) const pure virtual
Return true if the optional value at Data is in an unset state.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
IsPlainOldData()
bool UScriptStruct::ICppStructOps::IsPlainOldData () const inline
return true if this struct should be memcopied
Definition at line 1171 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::IsPlainOldData.
IsUECoreType()
bool UScriptStruct::ICppStructOps::IsUECoreType () const inline
return true if this struct is one of the UE Core types (and is include in CoreMinimal.h)
Definition at line 1177 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::IsUECoreType.
IsUECoreVariant()
bool UScriptStruct::ICppStructOps::IsUECoreVariant () const inline
return true if this struct is one of the UE Core types (and is include in CoreMinimal.h)
Definition at line 1183 of file Class.h.
References GetCapabilities(), and UScriptStruct::ICppStructOps::FCapabilities::IsUECoreVariant.
NetDeltaSerialize()
virtual bool UScriptStruct::ICppStructOps::NetDeltaSerialize (FNetDeltaSerializeInfo & DeltaParms, void * Data) pure virtual
Net serialize delta this structure.
Serialize a network delta from a base state
Returns
true if the struct was serialized, otherwise it will fall back to ordinary script struct net delta serialization
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
NetSerialize()
virtual bool UScriptStruct::ICppStructOps::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess, void * Data) pure virtual
Net serialize this structure.
Returns
true if the struct was serialized, otherwise it will fall back to ordinary script struct net serialization
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Ar, Data, and Map.
PostScriptConstruct()
virtual void UScriptStruct::ICppStructOps::PostScriptConstruct (void * Data) pure virtual
Call PostScriptConstruct on this structure.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
PostSerialize()
virtual void UScriptStruct::ICppStructOps::PostSerialize (const FArchive & Ar, void * Data) pure virtual
Call PostSerialize on this structure.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Ar, and Data.
ResolveVisitedPathInfo()
virtual void * UScriptStruct::ICppStructOps::ResolveVisitedPathInfo (void * Data, const FPropertyVisitorInfo & Info) const pure virtual
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data, and Info.
Serialize() [1/2]
virtual bool UScriptStruct::ICppStructOps::Serialize (FArchive & Ar, void * Data, UStruct * DefaultsStruct, const void * Defaults) pure virtual
Serialize this structure.
Returns
true if serialization was handled, false to fall back to standard script struct serialization.
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References UStruct::UStruct(), Ar, and Data.
Referenced by UE_DEPRECATED().
Serialize() [2/2]
virtual bool UScriptStruct::ICppStructOps::Serialize (FStructuredArchive::FSlot Slot, void * Data, UStruct * DefaultsStruct, const void * Defaults) pure virtual
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References UStruct::UStruct(), and Data.
SerializeFromMismatchedTag()
virtual bool UScriptStruct::ICppStructOps::SerializeFromMismatchedTag (struct FPropertyTag const & Tag, FArchive & Ar, void * Data) pure virtual
Serialize this structure, from some other tag.
Returns
true if this succeeded, false will trigger a warning and not serialize at all
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Ar, and Data.
StructuredSerializeFromMismatchedTag()
virtual bool UScriptStruct::ICppStructOps::StructuredSerializeFromMismatchedTag (struct FPropertyTag const & Tag, FStructuredArchive::FSlot Slot, void * Data) pure virtual
Implemented in UScriptStruct::TCppStructOps< CPPSTRUCT >.
References Data.
UE_DEPRECATED() [1/2]
UScriptStruct::ICppStructOps::UE_DEPRECATED (5. 6, "Use the overload of Serialize with defaults.") &
UE_DEPRECATED() [2/2]
UScriptStruct::ICppStructOps::UE_DEPRECATED (5. 6, "Use the overload of Serialize with defaults.") inline
Definition at line 1110 of file Class.h.
References Data, and Serialize().
Visit()
virtual EPropertyVisitorControlFlow UScriptStruct::ICppStructOps::Visit (FPropertyVisitorContext & Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const pure virtual
Structs property visitor signature.
Field Documentation
Alignment
const int32 UScriptStruct::ICppStructOps::Alignment private
alignof() of the structure
Definition at line 1339 of file Class.h.
Referenced by ICppStructOps(), and GetAlignment().
Data
void* UScriptStruct::ICppStructOps::Data
Initial value:
{
            return Serialize(Ar, Data, nullptr, nullptr)
Definition at line 1105 of file Class.h.
Referenced by CanEditChange(), UScriptStruct::TCppStructOps< CPPSTRUCT >::CanEditChange(), ClearIntrusiveOptionalValue(), UScriptStruct::TCppStructOps< CPPSTRUCT >::ClearIntrusiveOptionalValue(), FindInnerPropertyInstance(), UScriptStruct::TCppStructOps< CPPSTRUCT >::FindInnerPropertyInstance(), GetPreloadDependencies(), UScriptStruct::TCppStructOps< CPPSTRUCT >::GetPreloadDependencies(), ImportTextItem(), UScriptStruct::TCppStructOps< CPPSTRUCT >::ImportTextItem(), InitializeIntrusiveUnsetOptionalValue(), UScriptStruct::TCppStructOps< CPPSTRUCT >::InitializeIntrusiveUnsetOptionalValue(), IsIntrusiveOptionalValueSet(), UScriptStruct::TCppStructOps< CPPSTRUCT >::IsIntrusiveOptionalValueSet(), NetDeltaSerialize(), UScriptStruct::TCppStructOps< CPPSTRUCT >::NetDeltaSerialize(), NetSerialize(), UScriptStruct::TCppStructOps< CPPSTRUCT >::NetSerialize(), PostScriptConstruct(), UScriptStruct::TCppStructOps< CPPSTRUCT >::PostScriptConstruct(), PostSerialize(), UScriptStruct::TCppStructOps< CPPSTRUCT >::PostSerialize(), ResolveVisitedPathInfo(), UScriptStruct::TCppStructOps< CPPSTRUCT >::ResolveVisitedPathInfo(), Serialize(), Serialize(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Serialize(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Serialize(), SerializeFromMismatchedTag(), UScriptStruct::TCppStructOps< CPPSTRUCT >::SerializeFromMismatchedTag(), StructuredSerializeFromMismatchedTag(), UScriptStruct::TCppStructOps< CPPSTRUCT >::StructuredSerializeFromMismatchedTag(), and UE_DEPRECATED().
Size
const int32 UScriptStruct::ICppStructOps::Size private
sizeof() of the structure
Definition at line 1337 of file Class.h.
Referenced by ICppStructOps(), and GetSize().
The documentation for this struct was generated from the following file:
Class.h