Unreal Engine 5.6 C++ API: FAnimAssetFindReplaceConfig Struct Reference
FAnimAssetFindReplaceConfig Struct Reference
Configuration for the find/replace tab.
#include "AnimAssetFindReplace.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAnimAssetFindReplaceConfig ()=default
FAnimAssetFindReplaceConfig (const FAnimAssetFindReplaceConfig &)=default
FAnimAssetFindReplaceConfig & operator= (const FAnimAssetFindReplaceConfig &)=default
UE_DEPRECATED (5.3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI") EAnimAssetFindReplaceMode Mode
UE_DEPRECATED (5.3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI") EAnimAssetFindReplaceType Type
UE_DEPRECATED (5.3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI") FAssetData SkeletonFilter
UE_DEPRECATED (5.3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI") FString FindString
UE_DEPRECATED (5.3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI") FString ReplaceString
Data Fields
PRAGMA_ENABLE_DEPRECATION_WARNINGS TSubclassOf< UAnimAssetFindReplaceProcessor > InitialProcessorClass = nullptr
The initial processor class to use.
Detailed Description
Configuration for the find/replace tab.
Definition at line 208 of file AnimAssetFindReplace.h.
Constructor & Destructor Documentation
FAnimAssetFindReplaceConfig() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAnimAssetFindReplaceConfig::FAnimAssetFindReplaceConfig () default
Referenced by FAnimAssetFindReplaceConfig(), and operator=().
FAnimAssetFindReplaceConfig() [2/2]
FAnimAssetFindReplaceConfig::FAnimAssetFindReplaceConfig (const FAnimAssetFindReplaceConfig &) default
References FAnimAssetFindReplaceConfig().
Member Function Documentation
operator=()
FAnimAssetFindReplaceConfig & FAnimAssetFindReplaceConfig::operator= (const FAnimAssetFindReplaceConfig &) default
References FAnimAssetFindReplaceConfig(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED() [1/5]
FAnimAssetFindReplaceConfig::UE_DEPRECATED (5. 3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI")
References Find, and UE_DEPRECATED().
UE_DEPRECATED() [2/5]
FAnimAssetFindReplaceConfig::UE_DEPRECATED (5. 3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI")
References Curves, and UE_DEPRECATED().
UE_DEPRECATED() [3/5]
FAnimAssetFindReplaceConfig::UE_DEPRECATED (5. 3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI")
References UE_DEPRECATED().
UE_DEPRECATED() [4/5]
FAnimAssetFindReplaceConfig::UE_DEPRECATED (5. 3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/5]
FAnimAssetFindReplaceConfig::UE_DEPRECATED (5. 3, "Please use the UAnimAssetFindReplaceProcessor classes to configure the find/replace UI")
References UE_DEPRECATED().
Field Documentation
InitialProcessorClass
PRAGMA_ENABLE_DEPRECATION_WARNINGS TSubclassOf<UAnimAssetFindReplaceProcessor> FAnimAssetFindReplaceConfig::InitialProcessorClass = nullptr
The initial processor class to use.
Definition at line 217 of file AnimAssetFindReplace.h.
The documentation for this struct was generated from the following file:
AnimAssetFindReplace.h