Unreal Engine 5.6 C++ API: UE::MovieScene::TPlaybackCapabilityID< T > Struct Template Reference
UE::MovieScene::TPlaybackCapabilityID< T > Struct Template Reference
A strongly-typed identifier for a specific playback capability class.
#include "IMovieScenePlaybackCapability.h"
Public Types
using CapabilityType = T
Private Member Functions
TPlaybackCapabilityID ()
TPlaybackCapabilityID (int32 InIndex)
UE_DEPRECATED (5.6, "Use the version that takes a debug name. If defining a static ID field, please upgrade to UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API and UE_DEFINE_MOVIESCENE_PLAYBACK_CAPABILITY instead.") static TPlaybackCapabilityID< T > Register()
Static Private Member Functions
static TPlaybackCapabilityID< T > Register (const TCHAR *InDebugName)
Private Attributes
friend T
Additional Inherited Members
Public Member Functions inherited from UE::MovieScene::FPlaybackCapabilityID
bool IsValid () const
Data Fields inherited from UE::MovieScene::FPlaybackCapabilityID
int32 Index = INDEX_NONE
Static Protected Member Functions inherited from UE::MovieScene::FPlaybackCapabilityID
static MOVIESCENE_API FPlaybackCapabilityID Register (const TCHAR *InDebugName)
Detailed Description
template<typename T>
struct UE::MovieScene::TPlaybackCapabilityID< T >
A strongly-typed identifier for a specific playback capability class.
The base capablity class must create a static ID member that returns its own typed ID. We will use this as a convention to quickly get the ID of a base capability class in the capabilities container.
Definition at line 45 of file IMovieScenePlaybackCapability.h.
Member Typedef Documentation
CapabilityType
template<typename T> using UE::MovieScene::TPlaybackCapabilityID< T >::CapabilityType = T
Definition at line 48 of file IMovieScenePlaybackCapability.h.
Constructor & Destructor Documentation
TPlaybackCapabilityID() [1/2]
template<typename T> UE::MovieScene::TPlaybackCapabilityID< T >::TPlaybackCapabilityID () inline private
Definition at line 54 of file IMovieScenePlaybackCapability.h.
Referenced by Register(), and UE_DEPRECATED().
TPlaybackCapabilityID() [2/2]
template<typename T> UE::MovieScene::TPlaybackCapabilityID< T >::TPlaybackCapabilityID (int32 InIndex) inline explicit private
Definition at line 57 of file IMovieScenePlaybackCapability.h.
Member Function Documentation
Register()
template<typename T> TPlaybackCapabilityID< T > UE::MovieScene::TPlaybackCapabilityID< T >::Register (const TCHAR * InDebugName) inline static private
Definition at line 67 of file IMovieScenePlaybackCapability.h.
References TPlaybackCapabilityID(), UE::MovieScene::FPlaybackCapabilityID::Index, and UE::MovieScene::FPlaybackCapabilityID::Register().
Referenced by UE_DEPRECATED().
UE_DEPRECATED()
template<typename T> UE::MovieScene::TPlaybackCapabilityID< T >::UE_DEPRECATED (5. 6, "Use the version that takes a debug name. If defining a static ID field, please upgrade to UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API and UE_DEFINE_MOVIESCENE_PLAYBACK_CAPABILITY instead.") inline private
Definition at line 61 of file IMovieScenePlaybackCapability.h.
References TPlaybackCapabilityID(), Register(), T, and TEXT.
Field Documentation
T
template<typename T> friend UE::MovieScene::TPlaybackCapabilityID< T >::T private
Definition at line 52 of file IMovieScenePlaybackCapability.h.
Referenced by UE_DEPRECATED().
The documentation for this struct was generated from the following file:
IMovieScenePlaybackCapability.h