Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityGroupingPolicyKey Struct Reference
UE::MovieScene::FEntityGroupingPolicyKey Struct Reference
The key to a grouping policy registered on the grouping system (see UMovieSceneEntityGroupingSystem)
#include "BuiltInComponentTypes.h"
Public Member Functions
FEntityGroupingPolicyKey ()
FEntityGroupingPolicyKey (int32 FromIndex)
bool IsValid () const
Static Public Member Functions
static const FEntityGroupingPolicyKey Invalid ()
Data Fields
int32 Index = INDEX_NONE
Friends
uint32 GetTypeHash (const FEntityGroupingPolicyKey &Key)
bool operator== (const FEntityGroupingPolicyKey &A, const FEntityGroupingPolicyKey &B)
Detailed Description
The key to a grouping policy registered on the grouping system (see UMovieSceneEntityGroupingSystem)
Definition at line 476 of file BuiltInComponentTypes.h.
Constructor & Destructor Documentation
FEntityGroupingPolicyKey() [1/2]
UE::MovieScene::FEntityGroupingPolicyKey::FEntityGroupingPolicyKey () inline
Definition at line 480 of file BuiltInComponentTypes.h.
Referenced by GetTypeHash, Invalid(), and operator==.
FEntityGroupingPolicyKey() [2/2]
UE::MovieScene::FEntityGroupingPolicyKey::FEntityGroupingPolicyKey (int32 FromIndex) inline
Definition at line 481 of file BuiltInComponentTypes.h.
References Index.
Member Function Documentation
Invalid()
const FEntityGroupingPolicyKey UE::MovieScene::FEntityGroupingPolicyKey::Invalid () inline static
Definition at line 478 of file BuiltInComponentTypes.h.
References FEntityGroupingPolicyKey().
IsValid()
bool UE::MovieScene::FEntityGroupingPolicyKey::IsValid () const inline
Definition at line 483 of file BuiltInComponentTypes.h.
References Index, and INDEX_NONE.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FEntityGroupingPolicyKey & Key) friend
Definition at line 488 of file BuiltInComponentTypes.h.
References FEntityGroupingPolicyKey(), GetTypeHash(), and Key.
operator==
bool operator== (const FEntityGroupingPolicyKey & A, const FEntityGroupingPolicyKey & B) friend
Definition at line 493 of file BuiltInComponentTypes.h.
References FEntityGroupingPolicyKey(), A, and B.
Field Documentation
Index
int32 UE::MovieScene::FEntityGroupingPolicyKey::Index = INDEX_NONE
Definition at line 498 of file BuiltInComponentTypes.h.
Referenced by FEntityGroupingPolicyKey(), and IsValid().
The documentation for this struct was generated from the following file:
BuiltInComponentTypes.h