Unreal Engine 5.6 C++ API: SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType > Struct Template Reference
SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType > Struct Template Reference
Public Types
using WidgetArgsType = ArgumentType
Public Member Functions
FORCENOINLINE FVectorZArguments ()
OnZChanged ToggleZChecked ContextMenuExtenderZ OnZEndSliderMovement SLATE_ATTRIBUTE (FText, ZDisplayName) SLATE_ATTRIBUTE(FLinearColor
The DisplayName of the Z component of the vector.
SLATE_ATTRIBUTE (TOptional< NumericType >, Z) SLATE_EVENT(FOnNumericValueChanged
Z Component of the vector.
OnZChanged ToggleZChecked SLATE_EVENT (FOnCheckStateChanged, OnToggleZChanged) SLATE_EVENT(FMenuExtensionDelegate
Called whenever the toggle Z changes state.
OnZChanged SLATE_EVENT (FOnNumericValueCommitted, OnZCommitted) SLATE_ATTRIBUTE(ECheckBoxState
Called when the Z value of the vector is committed.
OnZChanged ToggleZChecked ContextMenuExtenderZ SLATE_EVENT (FSimpleDelegate, OnZBeginSliderMovement) SLATE_EVENT(FOnNumericValueChanged
Called when the z value of the vector slider began movement.
Detailed Description
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3>
template<typename ArgumentType>
struct SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >
Definition at line 151 of file SVectorInputBox.h.
Member Typedef Documentation
WidgetArgsType
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> using SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::WidgetArgsType = ArgumentType
Definition at line 153 of file SVectorInputBox.h.
Constructor & Destructor Documentation
FVectorZArguments()
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> FORCENOINLINE SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::FVectorZArguments () inline
Definition at line 155 of file SVectorInputBox.h.
References FORCENOINLINE, AxisDisplayInfo::GetAxisColor(), AxisDisplayInfo::GetAxisDisplayName(), NSLOCTEXT, AxisDisplayInfo::UseForwardRightUpDisplayNames(), and EAxisList::Z.
Member Function Documentation
SLATE_ATTRIBUTE() [1/2]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnZChanged ToggleZChecked ContextMenuExtenderZ OnZEndSliderMovement SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::SLATE_ATTRIBUTE (FText , ZDisplayName)
The DisplayName of the Z component of the vector.
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/2]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::SLATE_ATTRIBUTE (TOptional< NumericType > , Z)
Z Component of the vector.
Called when the Z value of the vector is changed
References Z.
Referenced by SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_EVENT() [1/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnZChanged ToggleZChecked SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::SLATE_EVENT (FOnCheckStateChanged , OnToggleZChanged)
Called whenever the toggle Z changes state.
Menu extender delegate for the Z value
References SLATE_EVENT().
SLATE_EVENT() [2/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnZChanged SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::SLATE_EVENT (FOnNumericValueCommitted , OnZCommitted)
Called when the Z value of the vector is committed.
The value of the toggle Z checkbox
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
Referenced by SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [3/3]
template<typename NumericType, typename VectorType = UE::Math::TVector<NumericType>, int32 NumberOfComponents = 3> template<typename ArgumentType> OnZChanged ToggleZChecked ContextMenuExtenderZ SNumericVectorInputBox< NumericType, VectorType, NumberOfComponents >::FVectorZArguments< ArgumentType >::SLATE_EVENT (FSimpleDelegate , OnZBeginSliderMovement)
Called when the z value of the vector slider began movement.
Called when the z value of the vector slider ended movement
References SLATE_EVENT().
The documentation for this struct was generated from the following file:
SVectorInputBox.h