Unreal Engine 5.6 C++ API: FNumericUnit< NumericType > Struct Template Reference
FNumericUnit< NumericType > Struct Template Reference
FNumericUnit is a numeric type that wraps the templated type, whilst a specified unit.
#include "UnitConversion.h"
Public Member Functions
FNumericUnit ()
Constructors.
FNumericUnit (const FNumericUnit &Other)
Copy construction/assignment from the same type.
template<typename OtherType>
FNumericUnit (const FNumericUnit< OtherType > &Other)
Templated Copy construction/assignment from differing numeric types.
FNumericUnit (const NumericType &InValue, EUnit InUnits=EUnit::Unspecified)
TOptional< FNumericUnit< NumericType > > ConvertTo (EUnit ToUnits) const
Convert this quantity to a different unit.
FNumericUnit & operator= (const FNumericUnit &Other)
template<typename OtherType>
FNumericUnit & operator= (const FNumericUnit< OtherType > &Other)
FNumericUnit< NumericType > QuantizeUnitsToBestFit () const
Quantizes this number to the most appropriate unit for user friendly presentation (e.g.
Static Public Member Functions
static TValueOrError< FNumericUnit< NumericType >, FText > TryParseExpression (const TCHAR *InExpression, EUnit InDefaultUnit, const FNumericUnit< NumericType > &InExistingValue)
Try and parse an expression into a numeric unit.
static TOptional< FNumericUnit< NumericType > > TryParseString (const TCHAR *InSource)
Parse a numeric unit from a string.
Data Fields
const EUnit Units
The associated units for the value.
NumericType Value
The numeric (scalar) value.
Private Member Functions
template<typename OtherType>
void CopyValueWithConversion (const FNumericUnit< OtherType > &Other)
Copy another unit into this one, taking account of its units, and applying necessary conversion.
operator const NumericType & () const =delete
Conversion to the numeric type disabled as coupled with implicit construction from NumericType can easily lead to loss of associated units.
Static Private Member Functions
static bool ExtractNumberBoundary (const TCHAR *Start, const TCHAR *&End)
Given a string, skip past whitespace, then any numeric characters.
Friends
template<typename OtherType>
bool operator!= (const FNumericUnit< NumericType > &LHS, const FNumericUnit< OtherType > &RHS)
template<typename OtherType>
bool operator== (const FNumericUnit< NumericType > &LHS, const FNumericUnit< OtherType > &RHS)
Global arithmetic operators for number types.
Detailed Description
template<typename NumericType>
struct FNumericUnit< NumericType >
FNumericUnit is a numeric type that wraps the templated type, whilst a specified unit.
It handles conversion to/from related units automatically. The units are considered not to contribute to the type's state, and as such should be considered immutable once set.
Definition at line 184 of file UnitConversion.h.
Constructor & Destructor Documentation
FNumericUnit() [1/4]
template<typename NumericType> FNumericUnit< NumericType >::FNumericUnit () nodiscard
Constructors.
Referenced by FNumericUnit(), FNumericUnit(), CopyValueWithConversion(), operator!=, operator=(), operator=(), operator==, QuantizeUnitsToBestFit(), and TryParseExpression().
FNumericUnit() [2/4]
template<typename NumericType> FNumericUnit< NumericType >::FNumericUnit (const NumericType & InValue, EUnit InUnits = EUnit::Unspecified) nodiscard
References Unspecified.
FNumericUnit() [3/4]
template<typename NumericType> FNumericUnit< NumericType >::FNumericUnit (const FNumericUnit< NumericType > & Other) nodiscard
Copy construction/assignment from the same type.
References FNumericUnit(), and Other.
FNumericUnit() [4/4]
template<typename NumericType> template<typename OtherType> FNumericUnit< NumericType >::FNumericUnit (const FNumericUnit< OtherType > & Other) nodiscard
Templated Copy construction/assignment from differing numeric types.
Relies on implicit conversion of the two numeric types.
References FNumericUnit(), and Other.
Member Function Documentation
ConvertTo()
template<typename NumericType> TOptional< FNumericUnit< NumericType > > FNumericUnit< NumericType >::ConvertTo (EUnit ToUnits) const nodiscard
Convert this quantity to a different unit.
CopyValueWithConversion()
template<typename NumericType> template<typename OtherType> void FNumericUnit< NumericType >::CopyValueWithConversion (const FNumericUnit< OtherType > & Other) private
Copy another unit into this one, taking account of its units, and applying necessary conversion.
References FNumericUnit(), and Other.
ExtractNumberBoundary()
template<typename NumericType> bool FNumericUnit< NumericType >::ExtractNumberBoundary (const TCHAR * Start, const TCHAR *& End) static private
Given a string, skip past whitespace, then any numeric characters.
Set End pointer to the end of the last numeric character.
References End.
operator const NumericType &()
template<typename NumericType> FNumericUnit< NumericType >::operator const NumericType & () const private delete
Conversion to the numeric type disabled as coupled with implicit construction from NumericType can easily lead to loss of associated units.
operator=() [1/2]
template<typename NumericType> FNumericUnit & FNumericUnit< NumericType >::operator= (const FNumericUnit< NumericType > & Other)
References FNumericUnit(), and Other.
operator=() [2/2]
template<typename NumericType> template<typename OtherType> FNumericUnit & FNumericUnit< NumericType >::operator= (const FNumericUnit< OtherType > & Other)
References FNumericUnit(), and Other.
QuantizeUnitsToBestFit()
template<typename NumericType> FNumericUnit< NumericType > FNumericUnit< NumericType >::QuantizeUnitsToBestFit () const nodiscard
Quantizes this number to the most appropriate unit for user friendly presentation (e.g.
1000m returns 1km).
References FNumericUnit().
TryParseExpression()
template<typename NumericType> TValueOrError< FNumericUnit< NumericType >, FText > FNumericUnit< NumericType >::TryParseExpression (const TCHAR * InExpression, EUnit InDefaultUnit, const FNumericUnit< NumericType > & InExistingValue) static
Try and parse an expression into a numeric unit.
References FNumericUnit().
TryParseString()
template<typename NumericType> TOptional< FNumericUnit< NumericType > > FNumericUnit< NumericType >::TryParseString (const TCHAR * InSource) static
Parse a numeric unit from a string.
Friends And Related Symbol Documentation
operator!=
template<typename NumericType> template<typename OtherType> bool operator!= (const FNumericUnit< NumericType > & LHS, const FNumericUnit< OtherType > & RHS) friend
Definition at line 257 of file UnitConversion.h.
References FNumericUnit().
operator==
template<typename NumericType> template<typename OtherType> bool operator== (const FNumericUnit< NumericType > & LHS, const FNumericUnit< OtherType > & RHS) friend
Global arithmetic operators for number types.
Deals with conversion from related units correctly. Note must be inlined for hidden friend optimization to work
Definition at line 232 of file UnitConversion.h.
References FNumericUnit(), FUnitConversion::AreUnitsCompatible(), FUnitConversion::Convert(), Units, Unspecified, and Value.
Field Documentation
Units
template<typename NumericType> const EUnit FNumericUnit< NumericType >::Units
The associated units for the value.
Can never change once set to anything other than EUnit::Unspecified.
Definition at line 189 of file UnitConversion.h.
Referenced by operator==.
Value
template<typename NumericType> NumericType FNumericUnit< NumericType >::Value
The numeric (scalar) value.
Definition at line 187 of file UnitConversion.h.
Referenced by operator==.
The documentation for this struct was generated from the following file:
UnitConversion.h