Unreal Engine 5.6 C++ API: FFindInBlueprintSearchManager Class Reference
FFindInBlueprintSearchManager Class Reference
Singleton manager for handling all Blueprint searches, helps to manage the going progress of Blueprints, and is thread-safe.
#include "FindInBlueprintManager.h"
Data Structures
struct FActiveSearchQuery
Contains info about an active search query.
Public Member Functions
FFindInBlueprintSearchManager ()
~FFindInBlueprintSearchManager ()
void AddOrUpdateBlueprintSearchMetadata (UBlueprint *InBlueprint, EAddOrUpdateBlueprintSearchMetadataFlags InFlags=EAddOrUpdateBlueprintSearchMetadataFlags::None, EFiBVersion InVersion=EFiBVersion::FIB_VER_NONE)
Gathers the Blueprint's search metadata and adds or updates it in the cache.
void ApplySearchDataToDatabase (FSearchData InSearchData, bool bAllowNewEntry=false)
Applies the given search data to a matching entry in the database.
void BeginSearchQuery (const class FStreamSearch *InSearchOriginator)
Starts a search query, the FiB manager handles where the thread is at in the search query at all times so that post-save of the cache to disk it can correct the index.
void CacheAllAssets (TWeakPtr< class SFindInBlueprints > InSourceWidget, const FFindInBlueprintCachingOptions &InCachingOptions)
Starts a task to cache Blueprints at a rate of 1 per tick.
void CancelCacheAll (SFindInBlueprints *InFindInBlueprintWidget)
Stops the caching process where it currently is at, the rest can be continued later.
void CloseOrphanedGlobalFindResultsTabs (TSharedPtr< class FTabManager > TabManager)
Close any orphaned global find results tabs for a particular tab manager.
bool ContinueSearchQuery (const class FStreamSearch *InSearchOriginator, FSearchData &OutSearchData)
Continues a search query, returning a single piece of search data.
void DoRandomIndexCacheRebuild ()
Randomly initiates a partial rebuild of the index cache (for debugging purposes)
void DumpCache (FArchive &Ar)
Dumps the full index cache to the given stream (for debugging purposes)
void EnableGatheringData (bool bInEnableGatheringData)
void EnableGlobalFindResults (bool bEnable)
Enable or disable the global find results tab feature.
void EnsureSearchQueryEnds (const class FStreamSearch *InSearchOriginator)
This function ensures that the passed in search query ends in a safe manner.
void ExportOutdatedAssetList ()
Exports a list of all unindexed assets to Saved/FindInBlueprints_OutdatedAssetList.txt.
void FinishedCachingBlueprints (EFiBCacheOpType InCacheOpType, EFiBCacheOpFlags InCacheOpFlags, int32 InNumberCached, TSet< FSoftObjectPath > &InFailedToCacheList)
Callback to note that Blueprint caching is complete.
float GetCacheProgress () const
Returns the progress complete on the caching.
FSoftObjectPath GetCurrentCacheBlueprintPath () const
Returns the path of the current Blueprint being cached.
int32 GetCurrentCacheIndex () const
Returns the current index in the caching.
int32 GetFailedToCacheCount () const
Returns the number of Blueprints that failed to cache.
TSet< FSoftObjectPath > GetFailedToCachePathList () const
Returns the list of Blueprint paths that failed to cache.
TSharedPtr< SFindInBlueprints > GetGlobalFindResults ()
Find or create the global find results widget.
int32 GetNumberUncachedAssets () const
Returns the number of uncached assets during an active indexing operation.
int32 GetNumberUnindexedAssets () const
Returns the number of unindexed Blueprints, either due to not having been indexed before, or AR data being out-of-date.
float GetPercentComplete (const class FStreamSearch *InSearchOriginator) const
Query how far along a search thread is.
FSearchData GetSearchDataForAssetPath (const FSoftObjectPath &InAssetPath)
Given an asset path, locate and return a copy of its matching search data in the index cache.
TWeakPtr< SFindInBlueprints > GetSourceCachingWidget () const
Returns a weak reference to the widget that initiated the current caching operation.
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
void GlobalFindResultsClosed (const TSharedRef< SFindInBlueprints > &FindResults)
bool HasCachingFailed () const
Returns TRUE if caching failed.
bool IsAssetDiscoveryInProgress () const
Returns TRUE if we're still inside the initial asset discovery and registration stage.
bool IsAsyncSearchQueryInProgress () const
Returns TRUE if there are one or more active asynchronous search queries.
bool IsCacheInProgress () const
Returns TRUE if Blueprints are being cached.
bool IsGatheringDataEnabled () const
bool IsGlobalFindResultsOpen () const
Returns true if a global find results tab is currently open.
virtual bool IsTickable () const override
Virtual that can be overloaded by the inheriting class.
bool IsUnindexedCacheInProgress () const
Returns TRUE if unindexed Blueprints are being cached (since this can block the UI)
void OnCacheAllUnindexedAssets (bool bInSourceControlActive, bool bInCheckoutAndSave)
Starts the actual caching process.
bool ProcessEncodedValueForUnloadedBlueprint (FSearchData &SearchData)
Processes the encoded string value in the SearchData into the intermediate format, return true if string and version were valid.
FSearchData QuerySingleBlueprint (UBlueprint *InBlueprint, bool bInRebuildSearchData)
Query for a single, specific Blueprint's search data.
bool ShouldEnableDeveloperMenuTools () const
If TRUE, the developer menu tool commands will be shown in the 'Developer' section of the Blueprint Editor's menu bar.
bool ShouldEnableSearchResultTemplates () const
If TRUE, search result meta will be gathered once and stored in a template.
void StartedCachingBlueprints (EFiBCacheOpType InCacheOpType, EFiBCacheOpFlags InCacheOpFlags)
Callback to note that Blueprint caching is started.
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Public Member Functions
static FString ConvertFTextToHexString (FText InValue)
Serializes an FText to memory and converts the memory into a string of hex characters.
static FText ConvertHexStringToFText (FString InHexString)
Converts a string of hex characters, previously converted by ConvertFTextToHexString, to an FText.
static TSharedPtr< class FJsonObject > ConvertJsonStringToObject (FSearchDataVersionInfo InVersionInfo, const FString &InJsonString, TMap< int32, FText > &OutFTextLookupTable)
Given a fully constructed Find-in-Blueprint FString of searchable data, will parse and construct a JsonObject.
static FString GenerateSearchIndexForDebugging (UBlueprint *InBlueprint)
Generates a human-readable search index for the given Blueprint (for debugging purposes)
static FFindInBlueprintSearchManager & Get ()
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Public Attributes
static FFindInBlueprintSearchManager * Instance
Protected Types
typedef TSharedPtr< FActiveSearchQuery, ESPMode::ThreadSafe > FActiveSearchQueryPtr
Protected Member Functions
void BlockSearchQueryIfPaused ()
If searches are paused, blocks the calling thread until searching is resumed.
FActiveSearchQueryPtr FindSearchQuery (const class FStreamSearch *InSearchOriginator) const
Thread-safe access to the active search query that's mapped to the given stream search.
FSearchData GetNextSearchDataForQuery (const FStreamSearch *InSearchOriginator, FActiveSearchQueryPtr InSearchQueryPtr, bool bCheckDeferredList)
Returns the next pending search data for the given query and advances the index to the next entry.
Private Member Functions
int32 AddSearchDataToDatabase (FSearchData InSearchData)
Helper to properly add a Blueprint's SearchData to the database.
void AddUnloadedBlueprintSearchMetadata (const FAssetData &InAssetData)
Adds a new search database entry for unloaded asset data.
void BuildCache ()
Builds the cache from all available Blueprint assets that the asset registry has discovered at the time of this function.
void CleanCache ()
Cleans the cache of any excess data from Blueprints that have been moved, renamed, or deleted.
void ExtractUnloadedFiBData (const FAssetData &InAssetData, FString *InFiBData, FName InKeyForFiBData, EFiBVersion InFiBDataVersion)
Begins the process of extracting FiB data from an unloaded asset.
FText GetGlobalFindResultsTabLabel (int32 TabIdx)
Determines the global find results tab label.
FSearchData GetSearchDataForIndex (int32 CacheIndex)
Returns a copy of the search data that's cached at the given index.
void Initialize ()
Initializes the FiB manager.
void OnAssetAdded (const struct FAssetData &InAssetData)
Callback hook from the Asset Registry when an asset is added.
void OnAssetLoaded (class UObject *InAsset)
Callback hook from the Asset Registry when an asset is loaded.
void OnAssetRegistryFilesLoaded ()
Callback hook from the Asset Registry, signals that the initial asset discovery stage has been completed.
void OnAssetRemoved (const struct FAssetData &InAssetData)
Callback hook from the Asset Registry, marks the asset for deletion from the cache.
void OnAssetRenamed (const struct FAssetData &InAssetData, const FString &InOldName)
Callback hook from the Asset Registry, marks the asset for deletion from the cache.
void OnBlueprintUnloaded (class UBlueprint *InBlueprint)
Callback from Kismet when a Blueprint is unloaded.
void OnReloadComplete (EReloadCompleteReason Reason)
Callback hook from the Reload manager that indicates that a module has been reloaded.
TSharedPtr< SFindInBlueprints > OpenGlobalFindResultsTab ()
Creates and opens a new global find results tab.
void PauseFindInBlueprintSearch ()
Callback hook during pre-garbage collection, pauses all processing searches so that the GC can do it's job.
void RemoveBlueprintByPath (const FSoftObjectPath &InPath)
Removes a Blueprint from being managed by the FiB system by passing in the UBlueprint's path.
TSharedRef< SDockTab > SpawnGlobalFindResultsTab (const FSpawnTabArgs &SpawnTabArgs, int32 TabIdx)
Handler for a request to spawn a new global find results tab.
void UnpauseFindInBlueprintSearch ()
Callback hook during post-garbage collection, saves the cache to disk and unpauses all processing searches.
Private Attributes
FThreadSafeCounter ActiveSearchCounter
Counter of active searches.
TMap< const class FStreamSearch *, FActiveSearchQueryPtr > ActiveSearchQueries
A mapping of active search queries and where they are currently at in the search data.
class FAssetRegistryModule * AssetRegistryModule
Because we are unable to query for the module on another thread, cache it for use later.
TSet< FSoftObjectPath > AssetsToIndexOnFirstSearch
List of paths that require a full index pass during the first global search.
int32 AsyncTaskBatchSize
Size of a single async indexing task batch; zero or negative means that a caching operation will consist of a single batch.
bool bDisableDeferredIndexing
If true, search metadata will be regenerated for loaded assets on the main thread immediately at discovery or load time.
bool bDisableImmediateAssetDiscovery
Defers the cost to extract metadata for each discovered asset during the initial asset registry scan into a single pass over the full asset registry once the scan is complete.
bool bDisableSearchResultTemplates
Disable the use of search result templates.
bool bDisableThreadedIndexing
If true, and if deferred indexing is not disabled, search metadata will be regenerated for loaded assets on the main thread at a rate of one asset per tick.
bool bEnableCSVStatsProfiling
Whether CSV profiling has been enabled (default=false)
bool bEnableDeveloperMenuTools
Whether to enable Blueprint editor developer menu tools.
bool bEnableGatheringData
Tells if gathering data is currently allowed.
TAtomic< bool > bHasFirstSearchOccurred
Currently used to delay the full indexing pass until the first search in order to control memory usage.
TAtomic< bool > bIsPausing
TRUE when the the FiB manager wants to pause all searches, helps manage the pausing procedure.
TMap< FTopLevelAssetPath, TWeakObjectPtr< const UClass > > CachedAssetClasses
Mapping between a class name and its UClass instance - used for faster look up in FFindInBlueprintSearchManager::OnAssetAdded.
TUniquePtr< class FCacheAllBlueprintsTickableObject > CachingObject
Tickable object that does the caching of uncached Blueprints at a rate of once per tick.
EFiBCacheOpType CurrentCacheOpType
Stores the type of caching operation that's currently in progress.
TSet< FSoftObjectPath > FailedToCachePaths
List of paths for Blueprints that failed to cache.
TArray< TWeakPtr< SFindInBlueprints > > GlobalFindResults
Array of open global find results widgets.
TSharedPtr< class FWorkspaceItem > GlobalFindResultsMenuItem
Global Find Results workspace menu item.
FName GlobalFindResultsTabIDs [4]
The tab identifier/instance name for global find results.
FCriticalSection PauseThreadsCriticalSection
Critical section to lock threads during the pausing procedure.
TSet< FSoftObjectPath > PendingAssets
Asset paths that were discovered, loaded or modified and now require indexing (or re-indexing)
FCriticalSection SafeModifyCacheCriticalSection
Critical section to safely modify cached data.
FCriticalSection SafeQueryModifyCriticalSection
Critical section to safely add, remove, and find data in ActiveSearchQueries.
TArray< FSearchData > SearchArray
Stores the Blueprint search data and is used to iterate over in small chunks.
TMap< FSoftObjectPath, int32 > SearchMap
Maps the Blueprint paths to their index in the SearchArray.
TWeakPtr< SFindInBlueprints > SourceCachingWidget
FindInBlueprints widget that started the cache process.
TSet< FSoftObjectPath > UnindexedAssets
Asset paths that have not been cached for searching due to lack of FiB data, this means that they are either older Blueprints, or the DDC cannot find the data.
Additional Inherited Members
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Singleton manager for handling all Blueprint searches, helps to manage the going progress of Blueprints, and is thread-safe.
Definition at line 525 of file FindInBlueprintManager.h.
Member Typedef Documentation
FActiveSearchQueryPtr
typedef TSharedPtr<FActiveSearchQuery, ESPMode::ThreadSafe> FFindInBlueprintSearchManager::FActiveSearchQueryPtr protected
Definition at line 809 of file FindInBlueprintManager.h.
Constructor & Destructor Documentation
FFindInBlueprintSearchManager()
FFindInBlueprintSearchManager::FFindInBlueprintSearchManager ()
Referenced by Get().
~FFindInBlueprintSearchManager()
FFindInBlueprintSearchManager::~FFindInBlueprintSearchManager ()
Member Function Documentation
AddOrUpdateBlueprintSearchMetadata()
void FFindInBlueprintSearchManager::AddOrUpdateBlueprintSearchMetadata (UBlueprint * InBlueprint, EAddOrUpdateBlueprintSearchMetadataFlags InFlags = EAddOrUpdateBlueprintSearchMetadataFlags::None, EFiBVersion InVersion = EFiBVersion::FIB_VER_NONE)
Gathers the Blueprint's search metadata and adds or updates it in the cache.
Parameters
InBlueprint Blueprint to cache the searchable data for
InFlags Flags to assist with controlling this function's behavior
InVersion Allows the caller to override the format version to use for caching
References None.
AddSearchDataToDatabase()
int32 FFindInBlueprintSearchManager::AddSearchDataToDatabase (FSearchData InSearchData) private
Helper to properly add a Blueprint's SearchData to the database.
Parameters
InSearchData Data to add to the database
Returns
Index into the SearchArray for looking up the added item
AddUnloadedBlueprintSearchMetadata()
void FFindInBlueprintSearchManager::AddUnloadedBlueprintSearchMetadata (const FAssetData & InAssetData) private
Adds a new search database entry for unloaded asset data.
ApplySearchDataToDatabase()
void FFindInBlueprintSearchManager::ApplySearchDataToDatabase (FSearchData InSearchData, bool bAllowNewEntry = false)
Applies the given search data to a matching entry in the database.
Optionally adds a new entry if a match is not found.
Parameters
InSearchData Search data to be applied
bAllowNewEntry Whether to allow a new entry to be added if a match is not found
BeginSearchQuery()
void FFindInBlueprintSearchManager::BeginSearchQuery (const class FStreamSearch * InSearchOriginator)
Starts a search query, the FiB manager handles where the thread is at in the search query at all times so that post-save of the cache to disk it can correct the index.
Parameters
InSearchOriginator Pointer to the thread object that the query originates from
BlockSearchQueryIfPaused()
void FFindInBlueprintSearchManager::BlockSearchQueryIfPaused () protected
If searches are paused, blocks the calling thread until searching is resumed.
BuildCache()
void FFindInBlueprintSearchManager::BuildCache () private
Builds the cache from all available Blueprint assets that the asset registry has discovered at the time of this function.
Occurs on startup
CacheAllAssets()
void FFindInBlueprintSearchManager::CacheAllAssets (TWeakPtr< class SFindInBlueprints > InSourceWidget, const FFindInBlueprintCachingOptions & InCachingOptions)
Starts a task to cache Blueprints at a rate of 1 per tick.
Parameters
InSourceWidget The source FindInBlueprints widget, this widget will be informed when caching is complete
InCachingOptions Options to configure the caching task
CancelCacheAll()
void FFindInBlueprintSearchManager::CancelCacheAll (SFindInBlueprints * InFindInBlueprintWidget)
Stops the caching process where it currently is at, the rest can be continued later.
CleanCache()
void FFindInBlueprintSearchManager::CleanCache () private
Cleans the cache of any excess data from Blueprints that have been moved, renamed, or deleted.
Occurs during post-garbage collection
CloseOrphanedGlobalFindResultsTabs()
void FFindInBlueprintSearchManager::CloseOrphanedGlobalFindResultsTabs (TSharedPtr< class FTabManager > TabManager)
Close any orphaned global find results tabs for a particular tab manager.
ContinueSearchQuery()
bool FFindInBlueprintSearchManager::ContinueSearchQuery (const class FStreamSearch * InSearchOriginator, FSearchData & OutSearchData)
Continues a search query, returning a single piece of search data.
Parameters
InSearchOriginator Pointer to the thread object that the query originates from
OutSearchData Result of the search, if there is any Blueprint search data still available to query
Returns
TRUE if the search was successful, FALSE if the search is complete
ConvertFTextToHexString()
FString FFindInBlueprintSearchManager::ConvertFTextToHexString (FText InValue) static
Serializes an FText to memory and converts the memory into a string of hex characters.
ConvertHexStringToFText()
FText FFindInBlueprintSearchManager::ConvertHexStringToFText (FString InHexString) static
Converts a string of hex characters, previously converted by ConvertFTextToHexString, to an FText.
ConvertJsonStringToObject()
TSharedPtr< class FJsonObject > FFindInBlueprintSearchManager::ConvertJsonStringToObject (FSearchDataVersionInfo InVersionInfo, const FString & InJsonString, TMap< int32, FText > & OutFTextLookupTable) static
Given a fully constructed Find-in-Blueprint FString of searchable data, will parse and construct a JsonObject.
DoRandomIndexCacheRebuild()
void FFindInBlueprintSearchManager::DoRandomIndexCacheRebuild ()
Randomly initiates a partial rebuild of the index cache (for debugging purposes)
DumpCache()
void FFindInBlueprintSearchManager::DumpCache (FArchive & Ar)
Dumps the full index cache to the given stream (for debugging purposes)
References Ar.
EnableGatheringData()
void FFindInBlueprintSearchManager::EnableGatheringData (bool bInEnableGatheringData) inline
Definition at line 682 of file FindInBlueprintManager.h.
References bEnableGatheringData.
Referenced by FDisableGatheringDataOnScope::FDisableGatheringDataOnScope(), and FDisableGatheringDataOnScope::~FDisableGatheringDataOnScope().
EnableGlobalFindResults()
void FFindInBlueprintSearchManager::EnableGlobalFindResults (bool bEnable)
Enable or disable the global find results tab feature.
EnsureSearchQueryEnds()
void FFindInBlueprintSearchManager::EnsureSearchQueryEnds (const class FStreamSearch * InSearchOriginator)
This function ensures that the passed in search query ends in a safe manner.
The search will no longer be valid to this manager, though it does not destroy any objects. Use this whenever the search is finished or canceled.
Parameters
InSearchOriginator Identifying search stream to be stopped
ExportOutdatedAssetList()
void FFindInBlueprintSearchManager::ExportOutdatedAssetList ()
Exports a list of all unindexed assets to Saved/FindInBlueprints_OutdatedAssetList.txt.
ExtractUnloadedFiBData()
void FFindInBlueprintSearchManager::ExtractUnloadedFiBData (const FAssetData & InAssetData, FString * InFiBData, FName InKeyForFiBData, EFiBVersion InFiBDataVersion) private
Begins the process of extracting FiB data from an unloaded asset.
FindSearchQuery()
FActiveSearchQueryPtr FFindInBlueprintSearchManager::FindSearchQuery (const class FStreamSearch * InSearchOriginator) const protected
Thread-safe access to the active search query that's mapped to the given stream search.
FinishedCachingBlueprints()
void FFindInBlueprintSearchManager::FinishedCachingBlueprints (EFiBCacheOpType InCacheOpType, EFiBCacheOpFlags InCacheOpFlags, int32 InNumberCached, TSet< FSoftObjectPath > & InFailedToCacheList)
Callback to note that Blueprint caching is complete.
Parameters
InNumberCached The number of Blueprints cached, to be chopped off the existing array so the rest (if any) can be finished later
GenerateSearchIndexForDebugging()
FString FFindInBlueprintSearchManager::GenerateSearchIndexForDebugging (UBlueprint * InBlueprint) static
Generates a human-readable search index for the given Blueprint (for debugging purposes)
Get()
FFindInBlueprintSearchManager & FFindInBlueprintSearchManager::Get () static
References FFindInBlueprintSearchManager().
Referenced by FDisableGatheringDataOnScope::FDisableGatheringDataOnScope(), and FDisableGatheringDataOnScope::~FDisableGatheringDataOnScope().
GetCacheProgress()
float FFindInBlueprintSearchManager::GetCacheProgress () const
Returns the progress complete on the caching.
GetCurrentCacheBlueprintPath()
FSoftObjectPath FFindInBlueprintSearchManager::GetCurrentCacheBlueprintPath () const
Returns the path of the current Blueprint being cached.
GetCurrentCacheIndex()
int32 FFindInBlueprintSearchManager::GetCurrentCacheIndex () const
Returns the current index in the caching.
GetFailedToCacheCount()
int32 FFindInBlueprintSearchManager::GetFailedToCacheCount () const inline
Returns the number of Blueprints that failed to cache.
Definition at line 652 of file FindInBlueprintManager.h.
References FailedToCachePaths.
GetFailedToCachePathList()
TSet< FSoftObjectPath > FFindInBlueprintSearchManager::GetFailedToCachePathList () const inline
Returns the list of Blueprint paths that failed to cache.
Definition at line 649 of file FindInBlueprintManager.h.
References FailedToCachePaths.
GetGlobalFindResults()
TSharedPtr< SFindInBlueprints > FFindInBlueprintSearchManager::GetGlobalFindResults ()
Find or create the global find results widget.
GetGlobalFindResultsTabLabel()
FText FFindInBlueprintSearchManager::GetGlobalFindResultsTabLabel (int32 TabIdx) private
Determines the global find results tab label.
GetNextSearchDataForQuery()
FSearchData FFindInBlueprintSearchManager::GetNextSearchDataForQuery (const FStreamSearch * InSearchOriginator, FActiveSearchQueryPtr InSearchQueryPtr, bool bCheckDeferredList) protected
Returns the next pending search data for the given query and advances the index to the next entry.
GetNumberUncachedAssets()
int32 FFindInBlueprintSearchManager::GetNumberUncachedAssets () const
Returns the number of uncached assets during an active indexing operation.
GetNumberUnindexedAssets()
int32 FFindInBlueprintSearchManager::GetNumberUnindexedAssets () const
Returns the number of unindexed Blueprints, either due to not having been indexed before, or AR data being out-of-date.
GetPercentComplete()
float FFindInBlueprintSearchManager::GetPercentComplete (const class FStreamSearch * InSearchOriginator) const
Query how far along a search thread is.
Parameters
OutSearchData Result of the search, if there is any Blueprint search data still available to query
Returns
Percent along the search thread is
GetSearchDataForAssetPath()
FSearchData FFindInBlueprintSearchManager::GetSearchDataForAssetPath (const FSoftObjectPath & InAssetPath)
Given an asset path, locate and return a copy of its matching search data in the index cache.
Parameters
InAssetPath Asset path (search index key).
Returns
Matching search data from the index cache. Will return invalid (empty) search data if a matching entry was not found.
GetSearchDataForIndex()
FSearchData FFindInBlueprintSearchManager::GetSearchDataForIndex (int32 CacheIndex) private
Returns a copy of the search data that's cached at the given index.
Will return invalid (empty) search data if the index is out of range
GetSourceCachingWidget()
TWeakPtr< SFindInBlueprints > FFindInBlueprintSearchManager::GetSourceCachingWidget () const inline
Returns a weak reference to the widget that initiated the current caching operation.
Definition at line 680 of file FindInBlueprintManager.h.
References SourceCachingWidget.
GetStatId()
virtual TStatId FFindInBlueprintSearchManager::GetStatId () const override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
GlobalFindResultsClosed()
void FFindInBlueprintSearchManager::GlobalFindResultsClosed (const TSharedRef< SFindInBlueprints > & FindResults)
HasCachingFailed()
bool FFindInBlueprintSearchManager::HasCachingFailed () const inline
Returns TRUE if caching failed.
Definition at line 655 of file FindInBlueprintManager.h.
References FailedToCachePaths.
Initialize()
void FFindInBlueprintSearchManager::Initialize () private
Initializes the FiB manager.
IsAssetDiscoveryInProgress()
bool FFindInBlueprintSearchManager::IsAssetDiscoveryInProgress () const
Returns TRUE if we're still inside the initial asset discovery and registration stage.
IsAsyncSearchQueryInProgress()
bool FFindInBlueprintSearchManager::IsAsyncSearchQueryInProgress () const
Returns TRUE if there are one or more active asynchronous search queries.
IsCacheInProgress()
bool FFindInBlueprintSearchManager::IsCacheInProgress () const
Returns TRUE if Blueprints are being cached.
IsGatheringDataEnabled()
bool FFindInBlueprintSearchManager::IsGatheringDataEnabled () const inline
Definition at line 684 of file FindInBlueprintManager.h.
References bEnableGatheringData.
IsGlobalFindResultsOpen()
bool FFindInBlueprintSearchManager::IsGlobalFindResultsOpen () const inline
Returns true if a global find results tab is currently open.
Definition at line 702 of file FindInBlueprintManager.h.
References GlobalFindResults.
IsTickable()
virtual bool FFindInBlueprintSearchManager::IsTickable () const override virtual
Virtual that can be overloaded by the inheriting class.
It is used to determine whether an object should be conditionally ticked.
Returns
true if object is ready to be ticked, false otherwise.
Reimplemented from FTickableObjectBase.
IsUnindexedCacheInProgress()
bool FFindInBlueprintSearchManager::IsUnindexedCacheInProgress () const
Returns TRUE if unindexed Blueprints are being cached (since this can block the UI)
OnAssetAdded()
void FFindInBlueprintSearchManager::OnAssetAdded (const struct FAssetData & InAssetData) private
Callback hook from the Asset Registry when an asset is added.
OnAssetLoaded()
void FFindInBlueprintSearchManager::OnAssetLoaded (class UObject * InAsset) private
Callback hook from the Asset Registry when an asset is loaded.
OnAssetRegistryFilesLoaded()
void FFindInBlueprintSearchManager::OnAssetRegistryFilesLoaded () private
Callback hook from the Asset Registry, signals that the initial asset discovery stage has been completed.
OnAssetRemoved()
void FFindInBlueprintSearchManager::OnAssetRemoved (const struct FAssetData & InAssetData) private
Callback hook from the Asset Registry, marks the asset for deletion from the cache.
OnAssetRenamed()
void FFindInBlueprintSearchManager::OnAssetRenamed (const struct FAssetData & InAssetData, const FString & InOldName) private
Callback hook from the Asset Registry, marks the asset for deletion from the cache.
OnBlueprintUnloaded()
void FFindInBlueprintSearchManager::OnBlueprintUnloaded (class UBlueprint * InBlueprint) private
Callback from Kismet when a Blueprint is unloaded.
OnCacheAllUnindexedAssets()
void FFindInBlueprintSearchManager::OnCacheAllUnindexedAssets (bool bInSourceControlActive, bool bInCheckoutAndSave)
Starts the actual caching process.
Parameters
bInSourceControlActive TRUE if source control is active
bInCheckoutAndSave TRUE if the system should checkout and save all assets that need to be reindexed
OnReloadComplete()
void FFindInBlueprintSearchManager::OnReloadComplete (EReloadCompleteReason Reason) private
Callback hook from the Reload manager that indicates that a module has been reloaded.
OpenGlobalFindResultsTab()
TSharedPtr< SFindInBlueprints > FFindInBlueprintSearchManager::OpenGlobalFindResultsTab () private
Creates and opens a new global find results tab.
PauseFindInBlueprintSearch()
void FFindInBlueprintSearchManager::PauseFindInBlueprintSearch () private
Callback hook during pre-garbage collection, pauses all processing searches so that the GC can do it's job.
ProcessEncodedValueForUnloadedBlueprint()
bool FFindInBlueprintSearchManager::ProcessEncodedValueForUnloadedBlueprint (FSearchData & SearchData)
Processes the encoded string value in the SearchData into the intermediate format, return true if string and version were valid.
QuerySingleBlueprint()
FSearchData FFindInBlueprintSearchManager::QuerySingleBlueprint (UBlueprint * InBlueprint, bool bInRebuildSearchData)
Query for a single, specific Blueprint's search data.
Parameters
InBlueprint The Blueprint to search for
bInRebuildSearchData When TRUE the search data will be freshly collected
Returns
The search data, or invalid (empty) search data if not found
RemoveBlueprintByPath()
void FFindInBlueprintSearchManager::RemoveBlueprintByPath (const FSoftObjectPath & InPath) private
Removes a Blueprint from being managed by the FiB system by passing in the UBlueprint's path.
ShouldEnableDeveloperMenuTools()
bool FFindInBlueprintSearchManager::ShouldEnableDeveloperMenuTools () const inline
If TRUE, the developer menu tool commands will be shown in the 'Developer' section of the Blueprint Editor's menu bar.
Definition at line 687 of file FindInBlueprintManager.h.
References bEnableDeveloperMenuTools.
ShouldEnableSearchResultTemplates()
bool FFindInBlueprintSearchManager::ShouldEnableSearchResultTemplates () const inline
If TRUE, search result meta will be gathered once and stored in a template.
Avoids doing this work redundantly at search time.
Definition at line 690 of file FindInBlueprintManager.h.
References bDisableSearchResultTemplates.
SpawnGlobalFindResultsTab()
TSharedRef< SDockTab > FFindInBlueprintSearchManager::SpawnGlobalFindResultsTab (const FSpawnTabArgs & SpawnTabArgs, int32 TabIdx) private
Handler for a request to spawn a new global find results tab.
StartedCachingBlueprints()
void FFindInBlueprintSearchManager::StartedCachingBlueprints (EFiBCacheOpType InCacheOpType, EFiBCacheOpFlags InCacheOpFlags)
Callback to note that Blueprint caching is started.
Tick()
virtual void FFindInBlueprintSearchManager::Tick (float DeltaTime) override virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
References DeltaTime.
UnpauseFindInBlueprintSearch()
void FFindInBlueprintSearchManager::UnpauseFindInBlueprintSearch () private
Callback hook during post-garbage collection, saves the cache to disk and unpauses all processing searches.
Field Documentation
ActiveSearchCounter
FThreadSafeCounter FFindInBlueprintSearchManager::ActiveSearchCounter private
Counter of active searches.
Definition at line 828 of file FindInBlueprintManager.h.
ActiveSearchQueries
TMap<const class FStreamSearch*, FActiveSearchQueryPtr> FFindInBlueprintSearchManager::ActiveSearchQueries private
A mapping of active search queries and where they are currently at in the search data.
Definition at line 831 of file FindInBlueprintManager.h.
AssetRegistryModule
class FAssetRegistryModule* FFindInBlueprintSearchManager::AssetRegistryModule private
Because we are unable to query for the module on another thread, cache it for use later.
Definition at line 843 of file FindInBlueprintManager.h.
AssetsToIndexOnFirstSearch
TSet<FSoftObjectPath> FFindInBlueprintSearchManager::AssetsToIndexOnFirstSearch private
List of paths that require a full index pass during the first global search.
Definition at line 858 of file FindInBlueprintManager.h.
AsyncTaskBatchSize
int32 FFindInBlueprintSearchManager::AsyncTaskBatchSize private
Size of a single async indexing task batch; zero or negative means that a caching operation will consist of a single batch.
Definition at line 879 of file FindInBlueprintManager.h.
bDisableDeferredIndexing
bool FFindInBlueprintSearchManager::bDisableDeferredIndexing private
If true, search metadata will be regenerated for loaded assets on the main thread immediately at discovery or load time.
By default, this work is deferred to avoid hitching.
Definition at line 891 of file FindInBlueprintManager.h.
bDisableImmediateAssetDiscovery
bool FFindInBlueprintSearchManager::bDisableImmediateAssetDiscovery private
Defers the cost to extract metadata for each discovered asset during the initial asset registry scan into a single pass over the full asset registry once the scan is complete.
Definition at line 907 of file FindInBlueprintManager.h.
bDisableSearchResultTemplates
bool FFindInBlueprintSearchManager::bDisableSearchResultTemplates private
Disable the use of search result templates.
Setting this to TRUE will slightly decrease overall memory usage, but will also increase global search times
Definition at line 904 of file FindInBlueprintManager.h.
Referenced by ShouldEnableSearchResultTemplates().
bDisableThreadedIndexing
bool FFindInBlueprintSearchManager::bDisableThreadedIndexing private
If true, and if deferred indexing is not disabled, search metadata will be regenerated for loaded assets on the main thread at a rate of one asset per tick.
Additional indexing work will be deferred to the search thread. By default, all indexing work is deferred to a background thread and both loaded and unloaded assets are fully indexed asynchronously.
Definition at line 895 of file FindInBlueprintManager.h.
bEnableCSVStatsProfiling
bool FFindInBlueprintSearchManager::bEnableCSVStatsProfiling private
Whether CSV profiling has been enabled (default=false)
Definition at line 898 of file FindInBlueprintManager.h.
bEnableDeveloperMenuTools
bool FFindInBlueprintSearchManager::bEnableDeveloperMenuTools private
Whether to enable Blueprint editor developer menu tools.
Definition at line 901 of file FindInBlueprintManager.h.
Referenced by ShouldEnableDeveloperMenuTools().
bEnableGatheringData
bool FFindInBlueprintSearchManager::bEnableGatheringData private
Tells if gathering data is currently allowed.
Definition at line 888 of file FindInBlueprintManager.h.
Referenced by EnableGatheringData(), and IsGatheringDataEnabled().
bHasFirstSearchOccurred
TAtomic<bool> FFindInBlueprintSearchManager::bHasFirstSearchOccurred private
Currently used to delay the full indexing pass until the first search in order to control memory usage.
Definition at line 885 of file FindInBlueprintManager.h.
bIsPausing
TAtomic<bool> FFindInBlueprintSearchManager::bIsPausing private
TRUE when the the FiB manager wants to pause all searches, helps manage the pausing procedure.
Definition at line 882 of file FindInBlueprintManager.h.
CachedAssetClasses
TMap<FTopLevelAssetPath, TWeakObjectPtr<const UClass> > FFindInBlueprintSearchManager::CachedAssetClasses private
Mapping between a class name and its UClass instance - used for faster look up in FFindInBlueprintSearchManager::OnAssetAdded.
Definition at line 867 of file FindInBlueprintManager.h.
CachingObject
TUniquePtr<class FCacheAllBlueprintsTickableObject> FFindInBlueprintSearchManager::CachingObject private
Tickable object that does the caching of uncached Blueprints at a rate of once per tick.
Definition at line 861 of file FindInBlueprintManager.h.
CurrentCacheOpType
EFiBCacheOpType FFindInBlueprintSearchManager::CurrentCacheOpType private
Stores the type of caching operation that's currently in progress.
Definition at line 864 of file FindInBlueprintManager.h.
FailedToCachePaths
TSet<FSoftObjectPath> FFindInBlueprintSearchManager::FailedToCachePaths private
List of paths for Blueprints that failed to cache.
Definition at line 855 of file FindInBlueprintManager.h.
Referenced by GetFailedToCacheCount(), GetFailedToCachePathList(), and HasCachingFailed().
GlobalFindResults
TArray<TWeakPtr<SFindInBlueprints> > FFindInBlueprintSearchManager::GlobalFindResults private
Array of open global find results widgets.
Definition at line 873 of file FindInBlueprintManager.h.
Referenced by IsGlobalFindResultsOpen().
GlobalFindResultsMenuItem
TSharedPtr<class FWorkspaceItem> FFindInBlueprintSearchManager::GlobalFindResultsMenuItem private
Global Find Results workspace menu item.
Definition at line 876 of file FindInBlueprintManager.h.
GlobalFindResultsTabIDs
FName FFindInBlueprintSearchManager::GlobalFindResultsTabIDs[4] private
The tab identifier/instance name for global find results.
Definition at line 870 of file FindInBlueprintManager.h.
Instance
FFindInBlueprintSearchManager* FFindInBlueprintSearchManager::Instance static
Definition at line 528 of file FindInBlueprintManager.h.
PauseThreadsCriticalSection
FCriticalSection FFindInBlueprintSearchManager::PauseThreadsCriticalSection private
Critical section to lock threads during the pausing procedure.
Definition at line 837 of file FindInBlueprintManager.h.
PendingAssets
TSet<FSoftObjectPath> FFindInBlueprintSearchManager::PendingAssets private
Asset paths that were discovered, loaded or modified and now require indexing (or re-indexing)
Definition at line 849 of file FindInBlueprintManager.h.
SafeModifyCacheCriticalSection
FCriticalSection FFindInBlueprintSearchManager::SafeModifyCacheCriticalSection private
Critical section to safely modify cached data.
Definition at line 840 of file FindInBlueprintManager.h.
SafeQueryModifyCriticalSection
FCriticalSection FFindInBlueprintSearchManager::SafeQueryModifyCriticalSection mutable private
Critical section to safely add, remove, and find data in ActiveSearchQueries.
Definition at line 834 of file FindInBlueprintManager.h.
SearchArray
TArray<FSearchData> FFindInBlueprintSearchManager::SearchArray private
Stores the Blueprint search data and is used to iterate over in small chunks.
Definition at line 825 of file FindInBlueprintManager.h.
SearchMap
TMap<FSoftObjectPath, int32> FFindInBlueprintSearchManager::SearchMap private
Maps the Blueprint paths to their index in the SearchArray.
Definition at line 822 of file FindInBlueprintManager.h.
SourceCachingWidget
TWeakPtr<SFindInBlueprints> FFindInBlueprintSearchManager::SourceCachingWidget private
FindInBlueprints widget that started the cache process.
Definition at line 846 of file FindInBlueprintManager.h.
Referenced by GetSourceCachingWidget().
UnindexedAssets
TSet<FSoftObjectPath> FFindInBlueprintSearchManager::UnindexedAssets private
Asset paths that have not been cached for searching due to lack of FiB data, this means that they are either older Blueprints, or the DDC cannot find the data.
Definition at line 852 of file FindInBlueprintManager.h.
The documentation for this class was generated from the following file:
FindInBlueprintManager.h