Unreal Engine 5.6 C++ API: FInstancedSkinnedMeshComponentHelper Class Reference
FInstancedSkinnedMeshComponentHelper Class Reference
Helper class used to share implementation for different InstancedSkinnedMeshComponent types.
#include "InstancedSkinnedMeshComponentHelper.h"
Static Public Member Functions
template<class T>
static FBoxSphereBounds CalcBounds (const T &InComponent, const FTransform &LocalToWorld)
template<class T>
static FSkeletalMeshObject * CreateMeshObject (const T &InComponent, const FInstancedSkinnedMeshSceneProxyDesc &InSceneProxyDesc)
template<class T>
static FPrimitiveSceneProxy * CreateSceneProxy (const T &InComponent, const FInstancedSkinnedMeshSceneProxyDesc &Desc)
template<class T, bool bSupportHitProxies = true>
static FInstanceDataManagerSourceDataDesc GetComponentDesc (T &InComponent, ERHIFeatureLevel::Type FeatureLevel)
template<class T>
static bool IsEnabled (const T &InComponent)
Detailed Description
Helper class used to share implementation for different InstancedSkinnedMeshComponent types.
Definition at line 12 of file InstancedSkinnedMeshComponentHelper.h.
Member Function Documentation
CalcBounds()
template<class T> FBoxSphereBounds FInstancedSkinnedMeshComponentHelper::CalcBounds (const T & InComponent, const FTransform & LocalToWorld) static
Definition at line 128 of file InstancedSkinnedMeshComponentHelper.h.
References FAnimBankData::Entries, UE::Math::TBoxSphereBounds< T, TExtent >::GetBox(), Instance, UE::Math::TBox< T >::IsValid, TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), FAnimBankEntry::SampledBounds, UInstancedSkinnedMeshComponent::ShouldUseSampledBounds(), UE::Math::TTransform< T >::ToMatrixWithScale(), UE::Math::TBox< T >::TransformBy(), and UE::Math::TVector< float >::ZeroVector.
CreateMeshObject()
template<class T> FSkeletalMeshObject * FInstancedSkinnedMeshComponentHelper::CreateMeshObject (const T & InComponent, const FInstancedSkinnedMeshSceneProxyDesc & InSceneProxyDesc) static
Definition at line 217 of file InstancedSkinnedMeshComponentHelper.h.
References UInstancedSkinnedMeshComponent::CreateMeshObject(), and FSkinnedMeshComponentHelper::GetSkeletalMeshRenderData().
CreateSceneProxy()
template<class T> FPrimitiveSceneProxy * FInstancedSkinnedMeshComponentHelper::CreateSceneProxy (const T & InComponent, const FInstancedSkinnedMeshSceneProxyDesc & Desc) static
Definition at line 235 of file InstancedSkinnedMeshComponentHelper.h.
References FSkinnedMeshComponentHelper::ComputeMinLOD(), UInstancedSkinnedMeshComponent::CreateSceneProxy(), IsEnabled(), and FSkinnedMeshComponentHelper::ShouldNaniteSkin().
GetComponentDesc()
template<class T, bool bSupportHitProxies> FInstanceDataManagerSourceDataDesc FInstancedSkinnedMeshComponentHelper::GetComponentDesc (T & InComponent, ERHIFeatureLevel::Type FeatureLevel) static
Definition at line 32 of file InstancedSkinnedMeshComponentHelper.h.
References FPrimitiveMaterialPropertyDescriptor::bAnyMaterialHasPerInstanceCustomData, FPrimitiveMaterialPropertyDescriptor::bAnyMaterialHasPerInstanceRandom, FInstanceDataManagerSourceDataDesc::BuildChangeSet, FInstanceDataManagerSourceDataDesc::ComponentMobility, FAnimBankData::Entries, Flags, FInstanceDataManagerSourceDataDesc::Flags, FReferenceSkeleton::GetRawBoneNum(), FPrimitiveComponentHelper::GetUsedMaterialPropertyDesc(), GIsEditor, MakeArrayView(), FInstanceDataManagerSourceDataDesc::MeshBounds, TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), FInstanceDataManagerSourceDataDesc::NumCustomDataFloats, FInstanceDataManagerSourceDataDesc::NumInstances, FInstanceDataManagerSourceDataDesc::PrimitiveLocalToWorld, FInstanceDataManagerSourceDataDesc::PrimitiveMaterialDesc, and UInstancedSkinnedMeshComponent::ShouldForceRefPose().
IsEnabled()
template<class T> bool FInstancedSkinnedMeshComponentHelper::IsEnabled (const T & InComponent) static
Definition at line 223 of file InstancedSkinnedMeshComponentHelper.h.
References Cast().
Referenced by CreateSceneProxy().
The documentation for this class was generated from the following file:
InstancedSkinnedMeshComponentHelper.h