Unreal Engine 5.6 C++ API: ICookedPackageWriter Class Reference
ICookedPackageWriter Class Reference abstract
Interface for cooking that writes cooked packages to storage usable by the runtime game.
#include "PackageWriter.h"
Data Structures
struct FBeginCacheForCookedPlatformDataInfo
struct FCookCapabilities
struct FCookInfo
struct FDeleteByFree
struct FPreviousCookedBytesData
Public Types
enum class EPackageHeaderFormat { PackageFileSummary , ZenPackageSummary }
using FBeginCacheCallback = TUniqueFunction<EPackageWriterResult(FBeginCacheForCookedPlatformDataInfo& Info)>
using FRegisterDeterminismHelperCallback
Public Types inherited from IPackageWriter
enum class ECommitStatus {
Success , Canceled , NothingToCook , Error ,
NotCommitted
}
enum class EWriteOptions {
None = 0 , WritePackage = 0x01 , WriteSidecars = 0x02 , Write = WritePackage | WriteSidecars ,
ComputeHash = 0x04 , SaveForDiff = 0x08
}
Public Member Functions
virtual ~ICookedPackageWriter ()=default
virtual ICookedPackageWriter * AsCookedPackageWriter () override
Downcast function for IPackageWriters that implement the ICookedPackageWriters inherited interface.
virtual IPackageStoreWriter * AsPackageStoreWriter ()
Downcast function for ICookedPackageWriters that implement the IPackageStoreWriter inherited interface.
virtual EPackageWriterResult BeginCacheForCookedPlatformData (FBeginCacheForCookedPlatformDataInfo &Info)
virtual void BeginCook (const FCookInfo &Info)=0
Signal the start of a cooking pass.
virtual void CompleteExportsArchiveForDiff (FPackageInfo &Info, FLargeMemoryWriter &ExportsArchive)
Append all data to the Exports archive that would normally be done in CommitPackage, used for diffing.
virtual void EndCook (const FCookInfo &Info)=0
Signal the end of a cooking pass.
virtual ECommitStatus GetCommitStatus (FName PackageName)=0
Report commit status for the given package.
virtual FCookCapabilities GetCookCapabilities () const
Return cook capabilities/settings this PackageWriter has/requires.
virtual FCbObject GetOplogAttachment (FName PackageName, FUtf8StringView AttachmentKey)=0
Returns an Attachment that was previously commited for the given PackageName.
virtual void GetOplogAttachments (TArrayView< FName > PackageNames, TArrayView< FUtf8StringView > AttachmentKeys, TUniqueFunction< void(FName PackageName, FUtf8StringView AttachmentKey, FCbObject &&Attachment)> &&Callback)=0
Callback is called for every cross product pair of PackageNames X AttachmentKeys.
virtual TMap< FName, TRefCountPtr< FPackageHashes > > & GetPackageHashes ()=0
Cooked package writers asynchronously hash the chunks for each package after CommitPackage.
virtual bool GetPreviousCookedBytes (const FPackageInfo &Info, FPreviousCookedBytesData &OutData)
Load the bytes of the previously-cooked package, used for diffing.
virtual FDateTime GetPreviousCookTime () const
Return the timestamp of the previous cook, or FDateTime::MaxValue to indicate previous cook should be assumed newer than any other cook data.
virtual void Initialize (const FCookInfo &Info)=0
Delete outdated cooked data, etc.
virtual bool IsAnotherSaveNeeded (FSavePackageResultStruct &PreviousResult, FSavePackageArgs &SaveArgs)
Report whether an additional save is needed and set up for it if so.
virtual TUniquePtr< FAssetRegistryState > LoadPreviousAssetRegistry ()=0
Returns an AssetRegistry describing the previous cook results.
virtual void RemoveCookedPackages ()=0
Remove all cooked packages from storage.
virtual void RemoveCookedPackages (TArrayView< const FName > PackageNamesToRemove)=0
Remove the given cooked package(s) from storage; they have been modified since the last cook.
virtual bool TryReadMPCookMessageForPackage (FName PackageName, FCbObjectView Message)=0
Read PackageData written by WriteMPCookMessageForPackage on a CookWorker.
UE_DEPRECATED (5.4, "No longer called; override UpdatePackageModificationStatus instead") virtual void MarkPackagesUpToDate(TArrayView< const FName > UpToDatePackages)
virtual void UpdatePackageModificationStatus (FName PackageName, bool bIncrementallyUnmodified, bool &bInOutShouldIncrementallySkip)=0
During incremental cooking, signal the cooked package has been checked for changes, and decide whether it should be incrementally skipped.
virtual void UpdateSaveArguments (FSavePackageArgs &SaveArgs)
Modify the SaveArgs if required before the first Save.
virtual TFuture< FCbObject > WriteMPCookMessageForPackage (FName PackageName)=0
Asynchronously create a CompactBinary Object message that replicates all of the package data from package save that is collected in memory and written at end of cook rather than being written to disk during package save.
Public Member Functions inherited from IPackageWriter
virtual ~IPackageWriter ()=default
virtual void BeginPackage (const FBeginPackageInfo &Info)=0
Mark the beginning of a package store transaction for the specified package.
virtual void CommitPackage (FCommitPackageInfo &&Info)=0
Finalize a package started with BeginPackage()
virtual TUniquePtr< FLargeMemoryWriter > CreateLinkerArchive (FName PackageName, UObject *Asset, uint16 MultiOutputIndex)
Create the FLargeMemoryWriter to which the Header and Exports are written during the save.
virtual TUniquePtr< FLargeMemoryWriter > CreateLinkerExportsArchive (FName PackageName, UObject *Asset, uint16 MultiOutputIndex)
Returns an archive to be used when serializing exports.
virtual FCapabilities GetCapabilities () const
Return capabilities/settings this PackageWriter has/requires.
virtual int64 GetExportsFooterSize ()
Report the size of the Footer that is added after Exports and BulkData but before the PackageTrailer.
virtual bool IsPreSaveCompleted () const
Report whether PreSave was already called by the PackageWriter before the current UPackage::Save call.
virtual void RegisterDeterminismHelper (UObject *SourceObject, const TRefCountPtr< UE::Cook::IDeterminismHelper > &DeterminismHelper)
Overridden by PackageWriters that handle bDeterminismDebug=true.
virtual void WriteAdditionalFile (const FAdditionalFileInfo &Info, const FIoBuffer &FileData)=0
Write separate files written by UObjects during cooking via UObject::CookAdditionalFiles.
virtual void WriteBulkData (const FBulkDataInfo &Info, const FIoBuffer &BulkData, const TArray< FFileRegion > &FileRegions)=0
Write bulk data for the current package.
virtual void WriteLinkerAdditionalData (const FLinkerAdditionalDataInfo &Info, const FIoBuffer &Data, const TArray< FFileRegion > &FileRegions)=0
Write separate data written by UObjects via FLinkerSave::AdditionalDataToAppend.
virtual void WritePackageData (const FPackageInfo &Info, FLargeMemoryWriter &ExportsArchive, const TArray< FFileRegion > &FileRegions)=0
Write package data (exports and serialized header)
virtual void WritePackageTrailer (const FPackageTrailerInfo &Info, const FIoBuffer &Data)=0
Write the PackageTrailer, a separate segment for some bulkdata that is written the end of the file.
Detailed Description
Interface for cooking that writes cooked packages to storage usable by the runtime game.
Definition at line 254 of file PackageWriter.h.
Member Typedef Documentation
FBeginCacheCallback
using ICookedPackageWriter::FBeginCacheCallback = TUniqueFunction<EPackageWriterResult(FBeginCacheForCookedPlatformDataInfo& Info)>
Definition at line 422 of file PackageWriter.h.
FRegisterDeterminismHelperCallback
using ICookedPackageWriter::FRegisterDeterminismHelperCallback
Initial value:
 TUniqueFunction<void(UObject* SourceObject,
        const TRefCountPtr<UE::Cook::IDeterminismHelper>& DeterminismHelper)>
Definition at line 423 of file PackageWriter.h.
Member Enumeration Documentation
EPackageHeaderFormat
enum class ICookedPackageWriter::EPackageHeaderFormat strong
Enumerator
PackageFileSummary
ZenPackageSummary
Definition at line 259 of file PackageWriter.h.
Constructor & Destructor Documentation
~ICookedPackageWriter()
virtual ICookedPackageWriter::~ICookedPackageWriter () virtual default
Member Function Documentation
AsCookedPackageWriter()
virtual ICookedPackageWriter * ICookedPackageWriter::AsCookedPackageWriter () inline override virtual
Downcast function for IPackageWriters that implement the ICookedPackageWriters inherited interface.
Reimplemented from IPackageWriter.
Definition at line 303 of file PackageWriter.h.
AsPackageStoreWriter()
virtual IPackageStoreWriter * ICookedPackageWriter::AsPackageStoreWriter () inline virtual
Downcast function for ICookedPackageWriters that implement the IPackageStoreWriter inherited interface.
Definition at line 453 of file PackageWriter.h.
BeginCacheForCookedPlatformData()
virtual EPackageWriterResult ICookedPackageWriter::BeginCacheForCookedPlatformData (FBeginCacheForCookedPlatformDataInfo & Info) inline virtual
Definition at line 426 of file PackageWriter.h.
References Error, Info, and unimplemented.
BeginCook()
virtual void ICookedPackageWriter::BeginCook (const FCookInfo & Info) pure virtual
Signal the start of a cooking pass.
Package data may only be produced after BeginCook() has been called and before EndCook() is called
References BeginCook(), and Info.
Referenced by BeginCook().
CompleteExportsArchiveForDiff()
virtual void ICookedPackageWriter::CompleteExportsArchiveForDiff (FPackageInfo & Info, FLargeMemoryWriter & ExportsArchive) inline virtual
Append all data to the Exports archive that would normally be done in CommitPackage, used for diffing.
Definition at line 408 of file PackageWriter.h.
References Info, and unimplemented.
EndCook()
virtual void ICookedPackageWriter::EndCook (const FCookInfo & Info) pure virtual
Signal the end of a cooking pass.
References EndCook(), and Info.
Referenced by EndCook().
GetCommitStatus()
virtual ECommitStatus ICookedPackageWriter::GetCommitStatus (FName PackageName) pure virtual
Report commit status for the given package.
If cooking incrementally, this reports the status from a previous cook if it has not yet been committed in the current cook.
References GetCommitStatus(), and PackageName.
Referenced by GetCommitStatus().
GetCookCapabilities()
virtual FCookCapabilities ICookedPackageWriter::GetCookCapabilities () const inline virtual
Return cook capabilities/settings this PackageWriter has/requires.
Definition at line 292 of file PackageWriter.h.
GetOplogAttachment()
virtual FCbObject ICookedPackageWriter::GetOplogAttachment (FName PackageName, FUtf8StringView AttachmentKey) pure virtual
Returns an Attachment that was previously commited for the given PackageName.
Returns an empty object if not found.
References GetOplogAttachment(), and PackageName.
Referenced by GetOplogAttachment().
GetOplogAttachments()
virtual void ICookedPackageWriter::GetOplogAttachments (TArrayView< FName > PackageNames, TArrayView< FUtf8StringView > AttachmentKeys, TUniqueFunction< void(FName PackageName, FUtf8StringView AttachmentKey, FCbObject &&Attachment)> && Callback) pure virtual
Callback is called for every cross product pair of PackageNames X AttachmentKeys.
The Attachment object passed to the callback is empty if not found.
References GetOplogAttachments(), and PackageName.
Referenced by GetOplogAttachments().
GetPackageHashes()
virtual TMap< FName, TRefCountPtr< FPackageHashes > > & ICookedPackageWriter::GetPackageHashes () pure virtual
Cooked package writers asynchronously hash the chunks for each package after CommitPackage.
Once cooking has completed, use this to acquire the results. This is synced using void UPackage::WaitForAsyncFileWrites() - do not access the results before that completes. Non-const so that the cooking process can Move the map of hashes.
GetPreviousCookedBytes()
virtual bool ICookedPackageWriter::GetPreviousCookedBytes (const FPackageInfo & Info, FPreviousCookedBytesData & OutData) inline virtual
Load the bytes of the previously-cooked package, used for diffing.
Definition at line 401 of file PackageWriter.h.
References Info, and unimplemented.
GetPreviousCookTime()
virtual FDateTime ICookedPackageWriter::GetPreviousCookTime () const inline virtual
Return the timestamp of the previous cook, or FDateTime::MaxValue to indicate previous cook should be assumed newer than any other cook data.
Definition at line 298 of file PackageWriter.h.
References FDateTime::MaxValue().
Initialize()
virtual void ICookedPackageWriter::Initialize (const FCookInfo & Info) pure virtual
Delete outdated cooked data, etc.
References Info, and Initialize().
Referenced by Initialize().
IsAnotherSaveNeeded()
virtual bool ICookedPackageWriter::IsAnotherSaveNeeded (FSavePackageResultStruct & PreviousResult, FSavePackageArgs & SaveArgs) inline virtual
Report whether an additional save is needed and set up for it if so.
Used for diffing.
Definition at line 437 of file PackageWriter.h.
LoadPreviousAssetRegistry()
virtual TUniquePtr< FAssetRegistryState > ICookedPackageWriter::LoadPreviousAssetRegistry () pure virtual
Returns an AssetRegistry describing the previous cook results.
This doesn't mean a cook saved off to another directory - it means the AssetRegistry that's living in the directory we are about to cook in to.
References LoadPreviousAssetRegistry().
Referenced by LoadPreviousAssetRegistry().
RemoveCookedPackages() [1/2]
virtual void ICookedPackageWriter::RemoveCookedPackages () pure virtual
Remove all cooked packages from storage.
References RemoveCookedPackages().
RemoveCookedPackages() [2/2]
virtual void ICookedPackageWriter::RemoveCookedPackages (TArrayView< const FName > PackageNamesToRemove) pure virtual
Remove the given cooked package(s) from storage; they have been modified since the last cook.
References RemoveCookedPackages().
Referenced by RemoveCookedPackages(), and RemoveCookedPackages().
TryReadMPCookMessageForPackage()
virtual bool ICookedPackageWriter::TryReadMPCookMessageForPackage (FName PackageName, FCbObjectView Message) pure virtual
Read PackageData written by WriteMPCookMessageForPackage on a CookWorker.
Called only on CookDirector.
References PackageName.
UE_DEPRECATED()
ICookedPackageWriter::UE_DEPRECATED (5. 4, "No longer called; override UpdatePackageModificationStatus instead") const inline
Definition at line 376 of file PackageWriter.h.
References UE_DEPRECATED().
Referenced by UE_DEPRECATED().
UpdatePackageModificationStatus()
virtual void ICookedPackageWriter::UpdatePackageModificationStatus (FName PackageName, bool bIncrementallyUnmodified, bool & bInOutShouldIncrementallySkip) pure virtual
During incremental cooking, signal the cooked package has been checked for changes, and decide whether it should be incrementally skipped.
References PackageName.
UpdateSaveArguments()
virtual void ICookedPackageWriter::UpdateSaveArguments (FSavePackageArgs & SaveArgs) inline virtual
Modify the SaveArgs if required before the first Save.
Used for diffing.
Definition at line 433 of file PackageWriter.h.
WriteMPCookMessageForPackage()
virtual TFuture< FCbObject > ICookedPackageWriter::WriteMPCookMessageForPackage (FName PackageName) pure virtual
Asynchronously create a CompactBinary Object message that replicates all of the package data from package save that is collected in memory and written at end of cook rather than being written to disk during package save.
Used during MPCook to transfer this information from CookWorker to CookDirector. Called after CommitPackage, and only on CookWorkers.
References PackageName.
The documentation for this class was generated from the following file:
PackageWriter.h