Unreal Engine 5.6 C++ API: WeakObjectPtrTemplates.h File Reference
WeakObjectPtrTemplates.h File Reference
#include "CoreTypes.h"
#include "Templates/LosesQualifiersFromTo.h"
#include "Templates/Requires.h"
#include "Containers/Map.h"
#include "UObject/WeakObjectPtrTemplatesFwd.h"
#include "UObject/StrongObjectPtrTemplatesFwd.h"
#include <type_traits>
Data Structures
struct TCallTraits< TWeakObjectPtr< T > >
struct TWeakObjectPtr< T, TWeakObjectPtrBase >
TWeakObjectPtr is the templated version of the generic FWeakObjectPtr.
struct TWeakObjectPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >
MapKeyFuncs for TWeakObjectPtrs which allow the key to become stale without invalidating the map.
struct TWeakObjectPtrSetKeyFuncs< ElementType, bInAllowDuplicateKeys >
SetKeyFuncs for TWeakObjectPtrs which allow the key to become stale without invalidating the set.
Functions
template<typename DestArrayType, typename SourceArrayType>
void CopyFromWeakArray (DestArrayType &Dest, const SourceArrayType &Src)
Utility function to fill in a TArray<ClassName*> from a TArray<TWeakObjectPtr<ClassName>>
template<typename DestArrayType, typename SourceArrayType>
void CopyToWeakArray (DestArrayType &Dest, const SourceArrayType &Src)
Utility function to fill in a TArray<TWeakObjectPtr<ClassName>> from a TArray<TObjectPtr<ClassName>> or TArray<ClassName*>
template<typename T>
FORCEINLINE uint32 GetTypeHash (const TWeakObjectPtr< T > &WeakObjectPtr)
Hash function.
template<typename T>
FORCEINLINE TWeakObjectPtr< T > MakeWeakObjectPtr (T *Ptr)
template<typename LhsT, typename RhsT, typename OtherTWeakObjectPtrBase, typename = decltype((LhsT*)nullptr != (RhsT*)nullptr)>
FORCEINLINE bool operator!= (const LhsT *Lhs, const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > &Rhs)
Compare weak pointers for inequality.
template<typename RhsT, typename OtherTWeakObjectPtrBase>
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > &Rhs)
template<class T, class TWeakObjectPtrBase>
FArchive & operator<< (FArchive &Ar, TWeakObjectPtr< T, TWeakObjectPtrBase > &WeakObjectPtr)
Weak object pointer serialization, this forwards to FArchive::operator<<(struct FWeakObjectPtr&) or an override.
template<typename LhsT, typename RhsT, typename OtherTWeakObjectPtrBase, typename = decltype((LhsT*)nullptr == (RhsT*)nullptr)>
FORCEINLINE bool operator== (const LhsT *Lhs, const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > &Rhs)
Compare weak pointers for equality.
template<typename RhsT, typename OtherTWeakObjectPtrBase>
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > &Rhs)
template<typename T>
TWeakObjectPtr (const TWeakObjectPtr< T > &) -> TWeakObjectPtr< T >
template<typename T>
TWeakObjectPtr (T *) -> TWeakObjectPtr< T >
Function Documentation
CopyFromWeakArray()
template<typename DestArrayType, typename SourceArrayType> void CopyFromWeakArray (DestArrayType & Dest, const SourceArrayType & Src)
Utility function to fill in a TArray<ClassName*> from a TArray<TWeakObjectPtr<ClassName>>
Definition at line 464 of file WeakObjectPtrTemplates.h.
References Count, and Value.
CopyToWeakArray()
template<typename DestArrayType, typename SourceArrayType> void CopyToWeakArray (DestArrayType & Dest, const SourceArrayType & Src)
Utility function to fill in a TArray<TWeakObjectPtr<ClassName>> from a TArray<TObjectPtr<ClassName>> or TArray<ClassName*>
Definition at line 479 of file WeakObjectPtrTemplates.h.
References Count, and Value.
GetTypeHash()
template<typename T> FORCEINLINE uint32 GetTypeHash (const TWeakObjectPtr< T > & WeakObjectPtr) nodiscard
Hash function.
Definition at line 494 of file WeakObjectPtrTemplates.h.
References FORCEINLINE, and WeakObjectPtr.
Referenced by TWeakObjectPtrMapKeyFuncs< KeyType, ValueType, bInAllowDuplicateKeys >::GetKeyHash(), and TWeakObjectPtrSetKeyFuncs< ElementType, bInAllowDuplicateKeys >::GetKeyHash().
MakeWeakObjectPtr()
template<typename T> FORCEINLINE TWeakObjectPtr< T > MakeWeakObjectPtr (T * Ptr) nodiscard
Definition at line 412 of file WeakObjectPtrTemplates.h.
References FORCEINLINE.
Referenced by FGameModeInfoCustomizer::GetCurrentGameModeClass(), and FGameModeInfoCustomizer::SetCurrentGameModeClass().
operator!=() [1/2]
template<typename LhsT, typename RhsT, typename OtherTWeakObjectPtrBase, typename = decltype((LhsT*)nullptr != (RhsT*)nullptr)> FORCEINLINE bool operator!= (const LhsT * Lhs, const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > & Rhs) nodiscard
Compare weak pointers for inequality.
Parameters
Other weak pointer to compare to
Definition at line 399 of file WeakObjectPtrTemplates.h.
References FORCEINLINE.
operator!=() [2/2]
template<typename RhsT, typename OtherTWeakObjectPtrBase> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > & Rhs) nodiscard
Definition at line 404 of file WeakObjectPtrTemplates.h.
References FORCEINLINE.
operator<<()
template<class T, class TWeakObjectPtrBase> FArchive & operator<< (FArchive & Ar, TWeakObjectPtr< T, TWeakObjectPtrBase > & WeakObjectPtr)
Weak object pointer serialization, this forwards to FArchive::operator<<(struct FWeakObjectPtr&) or an override.
Definition at line 504 of file WeakObjectPtrTemplates.h.
References Ar, and WeakObjectPtr.
operator==() [1/2]
template<typename LhsT, typename RhsT, typename OtherTWeakObjectPtrBase, typename = decltype((LhsT*)nullptr == (RhsT*)nullptr)> FORCEINLINE bool operator== (const LhsT * Lhs, const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > & Rhs) nodiscard
Compare weak pointers for equality.
If both pointers would return nullptr from Get() they count as equal even if they were not initialized to the same object.
Parameters
Other weak pointer to compare to
Definition at line 384 of file WeakObjectPtrTemplates.h.
References FORCEINLINE.
operator==() [2/2]
template<typename RhsT, typename OtherTWeakObjectPtrBase> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , const TWeakObjectPtr< RhsT, OtherTWeakObjectPtrBase > & Rhs) nodiscard
Definition at line 389 of file WeakObjectPtrTemplates.h.
References FORCEINLINE.
TWeakObjectPtr() [1/2]
template<typename T> TWeakObjectPtr (const TWeakObjectPtr< T > &) -> TWeakObjectPtr< T >
TWeakObjectPtr() [2/2]
template<typename T> TWeakObjectPtr (T *) -> TWeakObjectPtr< T >