Unreal Engine 5.6 C++ API: FRDGEventName Class Reference
FRDGEventName Class Reference final
Stores a GPU event name for the render graph.
#include "RenderGraphEvent.h"
Public Member Functions
FRDGEventName ()=default
FRDGEventName (const FRDGEventName &Other)=default
RENDERCORE_API FRDGEventName (const TCHAR *EventFormat,...)
RENDERCORE_API FRDGEventName (int32 NonVariadic, const TCHAR *EventName)
RENDERCORE_API const TCHAR * GetTCHAR () const
bool HasFormattedString () const
FRDGEventName & operator= (const FRDGEventName &Other)=default
Detailed Description
Stores a GPU event name for the render graph.
Draw events can be compiled out entirely from a release build for performance.
Definition at line 37 of file RenderGraphEvent.h.
Constructor & Destructor Documentation
FRDGEventName() [1/4]
FRDGEventName::FRDGEventName () default
Referenced by FRDGEventName(), and operator=().
FRDGEventName() [2/4]
RENDERCORE_API FRDGEventName::FRDGEventName (const TCHAR * EventFormat, ...) explicit
FRDGEventName() [3/4]
RENDERCORE_API FRDGEventName::FRDGEventName (int32 NonVariadic, const TCHAR * EventName)
FRDGEventName() [4/4]
FRDGEventName::FRDGEventName (const FRDGEventName & Other) default
References FRDGEventName(), and Other.
Member Function Documentation
GetTCHAR()
RENDERCORE_API const TCHAR * FRDGEventName::GetTCHAR () const
HasFormattedString()
bool FRDGEventName::HasFormattedString () const inline
Definition at line 51 of file RenderGraphEvent.h.
operator=()
FRDGEventName & FRDGEventName::operator= (const FRDGEventName & Other) default
References FRDGEventName(), and Other.
The documentation for this class was generated from the following file:
RenderGraphEvent.h