Unreal Engine 5.6 C++ API: UE::SequenceNavigator::TNavigationToolViewModelTypeID< T > Struct Template Reference
UE::SequenceNavigator::TNavigationToolViewModelTypeID< T > Struct Template Reference
#include "NavigationToolViewModelTypeID.h"
Public Member Functions
uint32 GetTypeID () const
FNavigationToolCastableTypeTable * GetTypeTable () const
operator FNavigationToolViewModelTypeID () const
void Register () const
Protected Member Functions
bool IsRegistered () const
Protected Attributes
uint32 ID = ~0u
friend T
FNavigationToolCastableTypeTable * TypeTable = nullptr
Detailed Description
template<typename T>
struct UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >
Definition at line 64 of file NavigationToolViewModelTypeID.h.
Member Function Documentation
GetTypeID()
template<typename T> uint32 UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::GetTypeID () const inline
Definition at line 72 of file NavigationToolViewModelTypeID.h.
References ID, and Register().
GetTypeTable()
template<typename T> FNavigationToolCastableTypeTable * UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::GetTypeTable () const inline
Definition at line 78 of file NavigationToolViewModelTypeID.h.
References Register(), and TypeTable.
IsRegistered()
template<typename T> bool UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::IsRegistered () const inline protected
Definition at line 95 of file NavigationToolViewModelTypeID.h.
References ID.
Referenced by Register().
operator FNavigationToolViewModelTypeID()
template<typename T> UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::operator FNavigationToolViewModelTypeID () const inline
Definition at line 66 of file NavigationToolViewModelTypeID.h.
References ID, Register(), and TypeTable.
Register()
template<typename T> void UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::Register () const inline
Definition at line 84 of file NavigationToolViewModelTypeID.h.
References IsRegistered().
Referenced by GetTypeID(), GetTypeTable(), and operator FNavigationToolViewModelTypeID().
Field Documentation
ID
template<typename T> uint32 UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::ID = ~0u protected
Definition at line 101 of file NavigationToolViewModelTypeID.h.
Referenced by GetTypeID(), IsRegistered(), and operator FNavigationToolViewModelTypeID().
T
template<typename T> friend UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::T protected
Definition at line 93 of file NavigationToolViewModelTypeID.h.
TypeTable
template<typename T> FNavigationToolCastableTypeTable* UE::SequenceNavigator::TNavigationToolViewModelTypeID< T >::TypeTable = nullptr protected
Definition at line 100 of file NavigationToolViewModelTypeID.h.
Referenced by GetTypeTable(), and operator FNavigationToolViewModelTypeID().
The documentation for this struct was generated from the following file:
NavigationToolViewModelTypeID.h