Unreal Engine 5.6 C++ API: FDebugViewModeInterface Class Reference
FDebugViewModeInterface Class Reference abstract
#include "DebugViewModeInterface.h"
Data Structures
struct FRenderState
Public Member Functions
FDebugViewModeInterface ()
virtual ~FDebugViewModeInterface ()
virtual void AddShaderTypes (ERHIFeatureLevel::Type InFeatureLevel, const FVertexFactoryType *InVertexFactoryType, FMaterialShaderTypes &OutShaderTypes) const =0
virtual void GetDebugViewModeShaderBindings (const FDebugViewModePS &Shader, const FPrimitiveSceneProxy *PrimitiveSceneProxy, const FMaterialRenderProxy &MaterialRenderProxy, const FMaterial &Material, EDebugViewShaderMode DebugViewMode, const FVector &ViewOrigin, int32 VisualizeLODIndex, const FColor &SkinCacheDebugColor, int32 VisualizeElementIndex, int32 NumVSInstructions, int32 NumPSInstructions, int32 LWCComplexityVS, int32 LWCComplexityPS, int32 ViewModeParam, FName ViewModeParamName, FMeshDrawSingleShaderBindings &ShaderBindings) const
virtual void SetDrawRenderState (EDebugViewShaderMode DebugViewMode, EBlendMode BlendMode, FRenderState &DrawRenderState, bool bHasDepthPrepassForMaskedMaterial) const
Static Public Member Functions
static bool AllowFallbackToDefaultMaterial (bool bHasVertexPositionOffsetConnected, bool bHasPixelDepthOffsetConnected)
static bool AllowFallbackToDefaultMaterial (const FMaterial *InMaterial)
Whether this material can be substituted by the default material.
static const FDebugViewModeInterface * GetInterface (EDebugViewShaderMode InDebugViewMode)
Return the interface object for the given viewmode.
static void SetInterface (FDebugViewModeInterface *Interface)
Return the interface object for the given viewmode.
Static Private Attributes
static FDebugViewModeInterface * Singleton
Detailed Description
Definition at line 27 of file DebugViewModeInterface.h.
Constructor & Destructor Documentation
FDebugViewModeInterface()
FDebugViewModeInterface::FDebugViewModeInterface () inline
Definition at line 41 of file DebugViewModeInterface.h.
Referenced by GetInterface(), and SetInterface().
~FDebugViewModeInterface()
virtual FDebugViewModeInterface::~FDebugViewModeInterface () inline virtual
Definition at line 44 of file DebugViewModeInterface.h.
Member Function Documentation
AddShaderTypes()
virtual void FDebugViewModeInterface::AddShaderTypes (ERHIFeatureLevel::Type InFeatureLevel, const FVertexFactoryType * InVertexFactoryType, FMaterialShaderTypes & OutShaderTypes) const pure virtual
AllowFallbackToDefaultMaterial() [1/2]
bool FDebugViewModeInterface::AllowFallbackToDefaultMaterial (bool bHasVertexPositionOffsetConnected, bool bHasPixelDepthOffsetConnected) static
AllowFallbackToDefaultMaterial() [2/2]
bool FDebugViewModeInterface::AllowFallbackToDefaultMaterial (const FMaterial * InMaterial) static
Whether this material can be substituted by the default material.
GetDebugViewModeShaderBindings()
virtual void FDebugViewModeInterface::GetDebugViewModeShaderBindings (const FDebugViewModePS & Shader, const FPrimitiveSceneProxy * PrimitiveSceneProxy, const FMaterialRenderProxy & MaterialRenderProxy, const FMaterial & Material, EDebugViewShaderMode DebugViewMode, const FVector & ViewOrigin, int32 VisualizeLODIndex, const FColor & SkinCacheDebugColor, int32 VisualizeElementIndex, int32 NumVSInstructions, int32 NumPSInstructions, int32 LWCComplexityVS, int32 LWCComplexityPS, int32 ViewModeParam, FName ViewModeParamName, FMeshDrawSingleShaderBindings & ShaderBindings) const inline virtual
Definition at line 52 of file DebugViewModeInterface.h.
References FVector, and Material.
GetInterface()
const FDebugViewModeInterface * FDebugViewModeInterface::GetInterface (EDebugViewShaderMode InDebugViewMode) inline static
Return the interface object for the given viewmode.
Definition at line 72 of file DebugViewModeInterface.h.
References FDebugViewModeInterface(), DVSM_MAX, and Singleton.
SetDrawRenderState()
virtual void FDebugViewModeInterface::SetDrawRenderState (EDebugViewShaderMode DebugViewMode, EBlendMode BlendMode, FRenderState & DrawRenderState, bool bHasDepthPrepassForMaskedMaterial) const virtual
SetInterface()
void FDebugViewModeInterface::SetInterface (FDebugViewModeInterface * Interface) static
Return the interface object for the given viewmode.
References FDebugViewModeInterface(), and Interface.
Field Documentation
Singleton
FDebugViewModeInterface* FDebugViewModeInterface::Singleton static private
Definition at line 86 of file DebugViewModeInterface.h.
Referenced by GetInterface().
The documentation for this class was generated from the following file:
DebugViewModeInterface.h