Unreal Engine 5.6 C++ API: FLocMetadataObject Class Reference
FLocMetadataObject Class Reference
A LocMetadata Object is a structure holding an unordered set of name/value pairs.
#include "InternationalizationMetadata.h"
Public Member Functions
FLocMetadataObject ()
FLocMetadataObject (const FLocMetadataObject &Other)
Copy ctor.
TArray< TSharedPtr< FLocMetadataValue > > GetArrayField (const FString &FieldName)
Get the field named FieldName as an array.
bool GetBoolField (const FString &FieldName)
Get the field named FieldName as a boolean.
template<ELocMetadataType LocMetadataType>
TSharedPtr< FLocMetadataValue > GetField (const FString &FieldName)
TSharedPtr< FLocMetadataObject > GetObjectField (const FString &FieldName)
Get the field named FieldName as a LocMetadata object.
FString GetStringField (const FString &FieldName)
Get the field named FieldName as a string.
bool HasField (const FString &FieldName)
Checks to see if the FieldName exists in the object.
template<ELocMetadataType LocMetadataType>
bool HasTypedField (const FString &FieldName)
Checks to see if the FieldName exists in the object, and has the specified type.
bool IsExactMatch (const FLocMetadataObject &Other) const
Similar functionality to == operator but ensures everything matches(ignores COMPARISON_MODIFIER_PREFIX).
bool operator< (const FLocMetadataObject &Other) const
FLocMetadataObject & operator= (const FLocMetadataObject &Other)
bool operator== (const FLocMetadataObject &Other) const
void RemoveField (const FString &FieldName)
void SetArrayField (const FString &FieldName, const TArray< TSharedPtr< FLocMetadataValue > > &Array)
Set an array field named FieldName and value of Array.
void SetBoolField (const FString &FieldName, bool InValue)
Set a boolean field named FieldName and value of InValue.
void SetField (const FString &FieldName, const TSharedPtr< FLocMetadataValue > &Value)
void SetObjectField (const FString &FieldName, const TSharedPtr< FLocMetadataObject > &LocMetadataObject)
Set an ObjectField named FieldName and value of LocMetadataObject.
void SetStringField (const FString &FieldName, const FString &StringValue)
Add a field named FieldName with value of StringValue.
FString ToString () const
Static Public Member Functions
static bool IsMetadataExactMatch (const FLocMetadataObject *const MetadataA, const FLocMetadataObject *const MetadataB)
Data Fields
TMap< FString, TSharedPtr< FLocMetadataValue > > Values
Stores the name/value pairs for the metadata object.
Static Public Attributes
static const TCHAR * COMPARISON_MODIFIER_PREFIX
Special reserved character.
Friends
FArchive & operator<< (FArchive &Archive, FLocMetadataObject &Object)
void operator<< (FStructuredArchive::FSlot Slot, FLocMetadataObject &Object)
Detailed Description
A LocMetadata Object is a structure holding an unordered set of name/value pairs.
Definition at line 77 of file InternationalizationMetadata.h.
Constructor & Destructor Documentation
FLocMetadataObject() [1/2]
FLocMetadataObject::FLocMetadataObject () inline
Definition at line 80 of file InternationalizationMetadata.h.
References Values.
Referenced by FLocMetadataObject(), IsExactMatch(), IsMetadataExactMatch(), operator<(), operator<<, operator<<, operator=(), and operator==().
FLocMetadataObject() [2/2]
FLocMetadataObject::FLocMetadataObject (const FLocMetadataObject & Other)
Copy ctor.
References FLocMetadataObject(), and Other.
Member Function Documentation
GetArrayField()
TArray< TSharedPtr< FLocMetadataValue > > FLocMetadataObject::GetArrayField (const FString & FieldName)
Get the field named FieldName as an array.
Ensures that the field is present and is of type LocMetadata Array.
GetBoolField()
bool FLocMetadataObject::GetBoolField (const FString & FieldName)
Get the field named FieldName as a boolean.
Ensures that the field is present and is of type LocMetadata boolean.
GetField()
template<ELocMetadataType LocMetadataType> TSharedPtr< FLocMetadataValue > FLocMetadataObject::GetField (const FString & FieldName) inline
Definition at line 89 of file InternationalizationMetadata.h.
References ensureMsgf, TSharedPtr< ObjectType, InMode >::IsValid(), TEXT, and Values.
GetObjectField()
TSharedPtr< FLocMetadataObject > FLocMetadataObject::GetObjectField (const FString & FieldName)
Get the field named FieldName as a LocMetadata object.
Ensures that the field is present and is a LocMetadata object
GetStringField()
FString FLocMetadataObject::GetStringField (const FString & FieldName)
Get the field named FieldName as a string.
Ensures that the field is present and is of type LocMetadata string.
HasField()
bool FLocMetadataObject::HasField (const FString & FieldName) inline
Checks to see if the FieldName exists in the object.
Definition at line 104 of file InternationalizationMetadata.h.
References TSharedPtr< ObjectType, InMode >::IsValid(), and Values.
HasTypedField()
template<ELocMetadataType LocMetadataType> bool FLocMetadataObject::HasTypedField (const FString & FieldName) inline
Checks to see if the FieldName exists in the object, and has the specified type.
Definition at line 117 of file InternationalizationMetadata.h.
References TSharedPtr< ObjectType, InMode >::IsValid(), and Values.
IsExactMatch()
bool FLocMetadataObject::IsExactMatch (const FLocMetadataObject & Other) const
Similar functionality to == operator but ensures everything matches(ignores COMPARISON_MODIFIER_PREFIX).
References FLocMetadataObject(), and Other.
IsMetadataExactMatch()
bool FLocMetadataObject::IsMetadataExactMatch (const FLocMetadataObject *const MetadataA, const FLocMetadataObject *const MetadataB) static
References FLocMetadataObject().
operator<()
bool FLocMetadataObject::operator< (const FLocMetadataObject & Other) const
References FLocMetadataObject(), and Other.
operator=()
FLocMetadataObject & FLocMetadataObject::operator= (const FLocMetadataObject & Other)
References FLocMetadataObject(), and Other.
operator==()
bool FLocMetadataObject::operator== (const FLocMetadataObject & Other) const
References FLocMetadataObject(), and Other.
RemoveField()
void FLocMetadataObject::RemoveField (const FString & FieldName)
SetArrayField()
void FLocMetadataObject::SetArrayField (const FString & FieldName, const TArray< TSharedPtr< FLocMetadataValue > > & Array)
Set an array field named FieldName and value of Array.
References Array.
SetBoolField()
void FLocMetadataObject::SetBoolField (const FString & FieldName, bool InValue)
Set a boolean field named FieldName and value of InValue.
SetField()
void FLocMetadataObject::SetField (const FString & FieldName, const TSharedPtr< FLocMetadataValue > & Value)
References Value.
SetObjectField()
void FLocMetadataObject::SetObjectField (const FString & FieldName, const TSharedPtr< FLocMetadataObject > & LocMetadataObject)
Set an ObjectField named FieldName and value of LocMetadataObject.
SetStringField()
void FLocMetadataObject::SetStringField (const FString & FieldName, const FString & StringValue)
Add a field named FieldName with value of StringValue.
ToString()
FString FLocMetadataObject::ToString () const
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Archive, FLocMetadataObject & Object) friend
References FLocMetadataObject(), and Object.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FLocMetadataObject & Object) friend
References FLocMetadataObject(), and Object.
Field Documentation
COMPARISON_MODIFIER_PREFIX
const TCHAR* FLocMetadataObject::COMPARISON_MODIFIER_PREFIX static
Special reserved character.
When encountered as a prefix metadata name(the key in the Values map), it will adjust the way comparisons are done.
Definition at line 176 of file InternationalizationMetadata.h.
Values
TMap< FString, TSharedPtr<FLocMetadataValue> > FLocMetadataObject::Values
Stores the name/value pairs for the metadata object.
Definition at line 173 of file InternationalizationMetadata.h.
Referenced by FLocMetadataObject(), GetField(), HasField(), and HasTypedField().
The documentation for this class was generated from the following file:
InternationalizationMetadata.h