Unreal Engine 5.6 C++ API: FTimerManager Class Reference
FTimerManager Class Reference
Class to globally manage timers.
#include "TimerManager.h"
Public Member Functions
FTimerManager (UGameInstance *GameInstance=nullptr)
virtual ~FTimerManager ()
FORCEINLINE void ClearAllTimersForObject (void const *Object)
Clears all timers that are bound to functions on the given object.
FORCEINLINE void ClearTimer (FTimerHandle &InHandle)
Clears a previously set timer, identical to calling SetTimer() with a <= 0.f rate.
FTimerHandle GenerateHandle (int32 Index)
Generates a handle for a timer at a given index.
TStatId GetStatId () const
FORCEINLINE float GetTimerElapsed (FTimerHandle InHandle) const
Gets the current elapsed time for the specified timer.
FORCEINLINE float GetTimerRate (FTimerHandle InHandle) const
Gets the current rate (time between activations) for the specified timer.
FORCEINLINE float GetTimerRemaining (FTimerHandle InHandle) const
Gets the time remaining before the specified timer is called.
bool FORCEINLINE HasBeenTickedThisFrame () const
FORCEINLINE bool IsTimerActive (FTimerHandle InHandle) const
Returns true if the specified timer exists and is not paused.
FORCEINLINE bool IsTimerPaused (FTimerHandle InHandle) const
Returns true if the specified timer exists and is paused.
FORCEINLINE bool IsTimerPending (FTimerHandle InHandle) const
Returns true if the specified timer exists and is pending.
FTimerHandle K2_FindDynamicTimerHandle (FTimerDynamicDelegate InDynamicDelegate) const
Finds a handle to a timer bound to a particular dynamic delegate.
void ListTimers () const
Debug command to output info on all timers currently set to the log.
virtual void OnCrash ()
Called from crash handler to provide more debug information.
void PauseTimer (FTimerHandle InHandle)
Pauses a previously set timer.
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, float InRate, bool InbLoop, float InFirstDelay=-1.f)
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, FTimerDelegate const &InDelegate, float InRate, bool InbLoop, float InFirstDelay=-1.f)
Version that takes any generic delegate.
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, FTimerDelegate const &InDelegate, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
Version that takes any generic delegate.
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, FTimerDynamicDelegate const &InDynDelegate, float InRate, bool InbLoop, float InFirstDelay=-1.f)
Version that takes a dynamic delegate (e.g.
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, FTimerDynamicDelegate const &InDynDelegate, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
Version that takes a dynamic delegate (e.g.
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, TFunction< void(void)> &&Callback, float InRate, bool InbLoop, float InFirstDelay=-1.f)
Version that takes a TFunction.
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, TFunction< void(void)> &&Callback, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
Version that takes a TFunction.
template<class UserClass>
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, UserClass *InObj, typename FTimerDelegate::TConstMethodPtr< UserClass > InTimerMethod, float InRate, bool InbLoop=false, float InFirstDelay=-1.f)
template<class UserClass>
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, UserClass *InObj, typename FTimerDelegate::TConstMethodPtr< UserClass > InTimerMethod, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
template<class UserClass>
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, UserClass *InObj, typename FTimerDelegate::TMethodPtr< UserClass > InTimerMethod, float InRate, bool InbLoop=false, float InFirstDelay=-1.f)
Sets a timer to call the given native function at a set interval.
template<class UserClass>
FORCEINLINE void SetTimer (FTimerHandle &InOutHandle, UserClass *InObj, typename FTimerDelegate::TMethodPtr< UserClass > InTimerMethod, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
Sets a timer to call the given native function at a set interval.
FORCEINLINE FTimerHandle SetTimerForNextTick (FTimerDelegate const &InDelegate)
Version that takes any generic delegate.
FORCEINLINE FTimerHandle SetTimerForNextTick (FTimerDynamicDelegate const &InDynDelegate)
Version that takes a dynamic delegate (e.g.
FORCEINLINE FTimerHandle SetTimerForNextTick (TFunction< void(void)> &&Callback)
Version that takes a TFunction.
template<class UserClass>
FORCEINLINE FTimerHandle SetTimerForNextTick (UserClass *inObj, typename FTimerDelegate::TConstMethodPtr< UserClass > inTimerMethod)
template<class UserClass>
FORCEINLINE FTimerHandle SetTimerForNextTick (UserClass *inObj, typename FTimerDelegate::TMethodPtr< UserClass > inTimerMethod)
Sets a timer to call the given native function on the next tick.
void Tick (float DeltaTime)
FORCEINLINE bool TimerExists (FTimerHandle InHandle) const
Returns true if the specified timer exists.
void UnPauseTimer (FTimerHandle InHandle)
Unpauses a previously set timer.
Protected Member Functions
FTimerData * FindTimer (FTimerHandle const &InHandle)
FORCEINLINE FTimerData const * FindTimer (FTimerHandle const &InHandle) const
Will find a timer in the active, paused, or pending list.
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Private Member Functions
FTimerHandle AddTimer (FTimerData &&TimerData)
Adds a timer from the Timers list, also updating the TimerIndicesByObject map.
FORCEINLINE const FTimerData & GetTimer (const FTimerHandle &InHandle) const
Will get a timer in the active, paused, or pending list.
FTimerData & GetTimer (FTimerHandle const &InHandle)
void InternalClearAllTimers (void const *Object)
void InternalClearTimer (FTimerHandle InDelegate)
float InternalGetTimerElapsed (FTimerData const *const TimerData) const
float InternalGetTimerRate (FTimerData const *const TimerData) const
float InternalGetTimerRemaining (FTimerData const *const TimerData) const
void InternalSetTimer (FTimerHandle &InOutHandle, FTimerUnifiedDelegate &&InDelegate, float InRate, bool bInLoop, float InFirstDelay)
void InternalSetTimer (FTimerHandle &InOutHandle, FTimerUnifiedDelegate &&InDelegate, float InRate, const FTimerManagerTimerParameters &InTimerParameters)
FTimerHandle InternalSetTimerForNextTick (FTimerUnifiedDelegate &&InDelegate)
void RemoveTimer (FTimerHandle Handle)
Removes a timer from the Timers list at the given index, also cleaning up the TimerIndicesByObject map.
void SetGameInstance (UGameInstance *InGameInstance)
bool WillRemoveTimerAssert (FTimerHandle Handle) const
Private Attributes
TArray< FTimerHandle > ActiveTimerHeap
Heap of actively running timers.
FTimerHandle CurrentlyExecutingTimer
Index to the timer delegate currently being executed, or INDEX_NONE if none are executing.
double InternalTime
An internally consistent clock, independent of World.
uint64 LastTickedFrame
Set this to GFrameCounter when Timer is ticked.
TMap< const void *, TSet< FTimerHandle > > ObjectToTimers
A map of object pointers to timers with delegates bound to those objects, for quick lookup.
UGameInstance * OwningGameInstance
The game instance that created this timer manager.
TSet< FTimerHandle > PausedTimerSet
Set of paused timers.
TSet< FTimerHandle > PendingTimerSet
Set of timers added this frame, to be added after timer has been ticked.
TSparseArray< FTimerData > Timers
The array of timers - all other arrays will index into this.
TUniquePtr< FTimerSourceList > TimerSourceList
Debugging/tracking information used when TimerManager.BuildTimerSourceList is set.
Static Private Attributes
static uint64 LastAssignedSerialNumber
The last serial number we assigned from this timer manager.
Detailed Description
Class to globally manage timers.
Definition at line 132 of file TimerManager.h.
Constructor & Destructor Documentation
FTimerManager()
FTimerManager::FTimerManager (UGameInstance * GameInstance = nullptr) explicit
Referenced by FindTimer(), and GetTimer().
~FTimerManager()
virtual FTimerManager::~FTimerManager () virtual
Member Function Documentation
AddTimer()
FTimerHandle FTimerManager::AddTimer (FTimerData && TimerData) private
Adds a timer from the Timers list, also updating the TimerIndicesByObject map.
Returns the insertion index.
ClearAllTimersForObject()
FORCEINLINE void FTimerManager::ClearAllTimersForObject (void const * Object) inline
Clears all timers that are bound to functions on the given object.
Definition at line 286 of file TimerManager.h.
References FORCEINLINE, InternalClearAllTimers(), and Object.
ClearTimer()
FORCEINLINE void FTimerManager::ClearTimer (FTimerHandle & InHandle) inline
Clears a previously set timer, identical to calling SetTimer() with a <= 0.f rate.
Invalidates the timer handle as it should no longer be used.
Parameters
InHandle The handle of the timer to clear.
Definition at line 276 of file TimerManager.h.
References FindTimer(), FORCEINLINE, and InternalClearTimer().
FindTimer() [1/2]
FTimerData * FTimerManager::FindTimer (FTimerHandle const & InHandle) protected
FindTimer() [2/2]
FORCEINLINE FTimerData const * FTimerManager::FindTimer (FTimerHandle const & InHandle) const inline protected
Will find a timer in the active, paused, or pending list.
Definition at line 420 of file TimerManager.h.
References FTimerManager(), FindTimer(), and FORCEINLINE.
Referenced by ClearTimer(), FindTimer(), GetTimerElapsed(), GetTimerRate(), GetTimerRemaining(), IsTimerActive(), IsTimerPaused(), IsTimerPending(), and TimerExists().
GenerateHandle()
FTimerHandle FTimerManager::GenerateHandle (int32 Index)
Generates a handle for a timer at a given index.
GetStatId()
TStatId FTimerManager::GetStatId () const
GetTimer() [1/2]
FORCEINLINE const FTimerData & FTimerManager::GetTimer (const FTimerHandle & InHandle) const inline private
Will get a timer in the active, paused, or pending list.
Expected to be given a valid, non-stale handle
Definition at line 437 of file TimerManager.h.
References FTimerManager(), FORCEINLINE, and GetTimer().
Referenced by GetTimer().
GetTimer() [2/2]
FTimerData & FTimerManager::GetTimer (FTimerHandle const & InHandle) private
GetTimerElapsed()
FORCEINLINE float FTimerManager::GetTimerElapsed (FTimerHandle InHandle) const inline
Gets the current elapsed time for the specified timer.
Parameters
InHandle The handle of the timer to check the elapsed time of.
Returns
The current time elapsed or -1.f if the timer does not exist.
Definition at line 373 of file TimerManager.h.
References FindTimer(), FORCEINLINE, and InternalGetTimerElapsed().
GetTimerRate()
FORCEINLINE float FTimerManager::GetTimerRate (FTimerHandle InHandle) const inline
Gets the current rate (time between activations) for the specified timer.
Parameters
InHandle The handle of the timer to return the rate of.
Returns
The current rate or -1.f if timer does not exist.
Definition at line 314 of file TimerManager.h.
References FindTimer(), FORCEINLINE, and InternalGetTimerRate().
GetTimerRemaining()
FORCEINLINE float FTimerManager::GetTimerRemaining (FTimerHandle InHandle) const inline
Gets the time remaining before the specified timer is called.
Parameters
InHandle The handle of the timer to check the remaining time of.
Returns
The current time remaining, or -1.f if timer does not exist
Definition at line 385 of file TimerManager.h.
References FindTimer(), FORCEINLINE, and InternalGetTimerRemaining().
HasBeenTickedThisFrame()
bool FORCEINLINE FTimerManager::HasBeenTickedThisFrame () const inline
Definition at line 391 of file TimerManager.h.
References FORCEINLINE, GFrameCounter, and LastTickedFrame.
InternalClearAllTimers()
void FTimerManager::InternalClearAllTimers (void const * Object) private
References Object.
Referenced by ClearAllTimersForObject().
InternalClearTimer()
void FTimerManager::InternalClearTimer (FTimerHandle InDelegate) private
Referenced by ClearTimer().
InternalGetTimerElapsed()
float FTimerManager::InternalGetTimerElapsed (FTimerData const *const TimerData) const private
Referenced by GetTimerElapsed().
InternalGetTimerRate()
float FTimerManager::InternalGetTimerRate (FTimerData const *const TimerData) const private
Referenced by GetTimerRate().
InternalGetTimerRemaining()
float FTimerManager::InternalGetTimerRemaining (FTimerData const *const TimerData) const private
Referenced by GetTimerRemaining().
InternalSetTimer() [1/2]
void FTimerManager::InternalSetTimer (FTimerHandle & InOutHandle, FTimerUnifiedDelegate && InDelegate, float InRate, bool bInLoop, float InFirstDelay) private
Referenced by SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), SetTimer(), and SetTimer().
InternalSetTimer() [2/2]
void FTimerManager::InternalSetTimer (FTimerHandle & InOutHandle, FTimerUnifiedDelegate && InDelegate, float InRate, const FTimerManagerTimerParameters & InTimerParameters) private
InternalSetTimerForNextTick()
FTimerHandle FTimerManager::InternalSetTimerForNextTick (FTimerUnifiedDelegate && InDelegate) private
Referenced by SetTimerForNextTick(), SetTimerForNextTick(), SetTimerForNextTick(), SetTimerForNextTick(), and SetTimerForNextTick().
IsTimerActive()
FORCEINLINE bool FTimerManager::IsTimerActive (FTimerHandle InHandle) const inline
Returns true if the specified timer exists and is not paused.
Parameters
InHandle The handle of the timer to check for being active.
Returns
true if the timer exists and is active, false otherwise.
Definition at line 326 of file TimerManager.h.
References FindTimer(), FORCEINLINE, Paused, and FTimerData::Status.
IsTimerPaused()
FORCEINLINE bool FTimerManager::IsTimerPaused (FTimerHandle InHandle) const inline
Returns true if the specified timer exists and is paused.
Parameters
InHandle The handle of the timer to check for being paused.
Returns
true if the timer exists and is paused, false otherwise.
Definition at line 338 of file TimerManager.h.
References FindTimer(), FORCEINLINE, Paused, and FTimerData::Status.
IsTimerPending()
FORCEINLINE bool FTimerManager::IsTimerPending (FTimerHandle InHandle) const inline
Returns true if the specified timer exists and is pending.
Parameters
InHandle The handle of the timer to check for being pending.
Returns
true if the timer exists and is pending, false otherwise.
Definition at line 350 of file TimerManager.h.
References FindTimer(), FORCEINLINE, Pending, and FTimerData::Status.
K2_FindDynamicTimerHandle()
FTimerHandle FTimerManager::K2_FindDynamicTimerHandle (FTimerDynamicDelegate InDynamicDelegate) const
Finds a handle to a timer bound to a particular dynamic delegate.
This function is intended to be used only by the K2 system.
Parameters
InDynamicDelegate The dynamic delegate to search for.
Returns
A handle to the found timer - !IsValid() if no such timer was found.
ListTimers()
void FTimerManager::ListTimers () const
Debug command to output info on all timers currently set to the log.
OnCrash()
virtual void FTimerManager::OnCrash () virtual
Called from crash handler to provide more debug information.
PauseTimer()
void FTimerManager::PauseTimer (FTimerHandle InHandle)
Pauses a previously set timer.
Parameters
InHandle The handle of the timer to pause.
RemoveTimer()
void FTimerManager::RemoveTimer (FTimerHandle Handle) private
Removes a timer from the Timers list at the given index, also cleaning up the TimerIndicesByObject map.
References Handle.
SetGameInstance()
void FTimerManager::SetGameInstance (UGameInstance * InGameInstance) private
SetTimer() [1/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, float InRate, bool InbLoop, float InFirstDelay = -1.f) inline
Definition at line 183 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [2/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, float InRate, const FTimerManagerTimerParameters & InTimerParameters) inline
Definition at line 227 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [3/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, FTimerDelegate const & InDelegate, float InRate, bool InbLoop, float InFirstDelay = -1.f) inline
Version that takes any generic delegate.
Definition at line 173 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [4/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, FTimerDelegate const & InDelegate, float InRate, const FTimerManagerTimerParameters & InTimerParameters) inline
Version that takes any generic delegate.
Definition at line 217 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [5/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, FTimerDynamicDelegate const & InDynDelegate, float InRate, bool InbLoop, float InFirstDelay = -1.f) inline
Version that takes a dynamic delegate (e.g.
for UFunctions).
Definition at line 178 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [6/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, FTimerDynamicDelegate const & InDynDelegate, float InRate, const FTimerManagerTimerParameters & InTimerParameters) inline
Version that takes a dynamic delegate (e.g.
for UFunctions).
Definition at line 222 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [7/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, TFunction< void(void)> && Callback, float InRate, bool InbLoop, float InFirstDelay = -1.f) inline
Version that takes a TFunction.
Definition at line 188 of file TimerManager.h.
References FORCEINLINE, InternalSetTimer(), and MoveTemp().
SetTimer() [8/12]
FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, TFunction< void(void)> && Callback, float InRate, const FTimerManagerTimerParameters & InTimerParameters) inline
Version that takes a TFunction.
Definition at line 232 of file TimerManager.h.
References FORCEINLINE, InternalSetTimer(), and MoveTemp().
SetTimer() [9/12]
template<class UserClass> FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, UserClass * InObj, typename FTimerDelegate::TConstMethodPtr< UserClass > InTimerMethod, float InRate, bool InbLoop = false, float InFirstDelay = -1.f) inline
Definition at line 167 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [10/12]
template<class UserClass> FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, UserClass * InObj, typename FTimerDelegate::TConstMethodPtr< UserClass > InTimerMethod, float InRate, const FTimerManagerTimerParameters & InTimerParameters) inline
Definition at line 211 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [11/12]
template<class UserClass> FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, UserClass * InObj, typename FTimerDelegate::TMethodPtr< UserClass > InTimerMethod, float InRate, bool InbLoop = false, float InFirstDelay = -1.f) inline
Sets a timer to call the given native function at a set interval.
If a timer is already set for this handle, it will replace the current timer.
Parameters
InOutHandle If the passed-in handle refers to an existing timer, it will be cleared before the new timer is added. A new handle to the new timer is returned in either case.
InObj Object to call the timer function on.
InTimerMethod Method to call when timer fires.
InRate The amount of time (in seconds) between set and firing. If <= 0.f, clears existing timers.
InbLoop true to keep firing at Rate intervals, false to fire only once.
InFirstDelay The time (in seconds) for the first iteration of a looping timer. If < 0.f InRate will be used.
Definition at line 162 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimer() [12/12]
template<class UserClass> FORCEINLINE void FTimerManager::SetTimer (FTimerHandle & InOutHandle, UserClass * InObj, typename FTimerDelegate::TMethodPtr< UserClass > InTimerMethod, float InRate, const FTimerManagerTimerParameters & InTimerParameters) inline
Sets a timer to call the given native function at a set interval.
If a timer is already set for this handle, it will replace the current timer.
Parameters
InOutHandle If the passed-in handle refers to an existing timer, it will be cleared before the new timer is added. A new handle to the new timer is returned in either case.
InObj Object to call the timer function on.
InTimerMethod Method to call when timer fires.
InRate The amount of time (in seconds) between set and firing. If <= 0.f, clears existing timers.
InTimerParameters The structure with additional timer looping and delay parameters.
Definition at line 206 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimer().
SetTimerForNextTick() [1/5]
FORCEINLINE FTimerHandle FTimerManager::SetTimerForNextTick (FTimerDelegate const & InDelegate) inline
Version that takes any generic delegate.
Definition at line 255 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimerForNextTick().
SetTimerForNextTick() [2/5]
FORCEINLINE FTimerHandle FTimerManager::SetTimerForNextTick (FTimerDynamicDelegate const & InDynDelegate) inline
Version that takes a dynamic delegate (e.g.
for UFunctions).
Definition at line 260 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimerForNextTick().
SetTimerForNextTick() [3/5]
FORCEINLINE FTimerHandle FTimerManager::SetTimerForNextTick (TFunction< void(void)> && Callback) inline
Version that takes a TFunction.
Definition at line 265 of file TimerManager.h.
References FORCEINLINE, InternalSetTimerForNextTick(), and MoveTemp().
SetTimerForNextTick() [4/5]
template<class UserClass> FORCEINLINE FTimerHandle FTimerManager::SetTimerForNextTick (UserClass * inObj, typename FTimerDelegate::TConstMethodPtr< UserClass > inTimerMethod) inline
Definition at line 249 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimerForNextTick().
SetTimerForNextTick() [5/5]
template<class UserClass> FORCEINLINE FTimerHandle FTimerManager::SetTimerForNextTick (UserClass * inObj, typename FTimerDelegate::TMethodPtr< UserClass > inTimerMethod) inline
Sets a timer to call the given native function on the next tick.
Parameters
inObj Object to call the timer function on.
inTimerMethod Method to call when timer fires.
Definition at line 244 of file TimerManager.h.
References FORCEINLINE, and InternalSetTimerForNextTick().
Tick()
void FTimerManager::Tick (float DeltaTime)
References DeltaTime.
TimerExists()
FORCEINLINE bool FTimerManager::TimerExists (FTimerHandle InHandle) const inline
Returns true if the specified timer exists.
Parameters
InHandle The handle of the timer to check for existence.
Returns
true if the timer exists, false otherwise.
Definition at line 362 of file TimerManager.h.
References FindTimer(), and FORCEINLINE.
UnPauseTimer()
void FTimerManager::UnPauseTimer (FTimerHandle InHandle)
Unpauses a previously set timer.
Parameters
InHandle The handle of the timer to unpause.
WillRemoveTimerAssert()
bool FTimerManager::WillRemoveTimerAssert (FTimerHandle Handle) const private
References Handle.
Field Documentation
ActiveTimerHeap
TArray<FTimerHandle> FTimerManager::ActiveTimerHeap private
Heap of actively running timers.
Definition at line 452 of file TimerManager.h.
CurrentlyExecutingTimer
FTimerHandle FTimerManager::CurrentlyExecutingTimer private
Index to the timer delegate currently being executed, or INDEX_NONE if none are executing.
Used to handle "timer delegates that manipulate timers" cases.
Definition at line 464 of file TimerManager.h.
InternalTime
double FTimerManager::InternalTime private
An internally consistent clock, independent of World.
Advances during ticking.
Definition at line 461 of file TimerManager.h.
LastAssignedSerialNumber
uint64 FTimerManager::LastAssignedSerialNumber static private
The last serial number we assigned from this timer manager.
Definition at line 470 of file TimerManager.h.
LastTickedFrame
uint64 FTimerManager::LastTickedFrame private
Set this to GFrameCounter when Timer is ticked.
To figure out if Timer has been already ticked or not this frame.
Definition at line 467 of file TimerManager.h.
Referenced by HasBeenTickedThisFrame().
ObjectToTimers
TMap<const void*, TSet<FTimerHandle> > FTimerManager::ObjectToTimers private
A map of object pointers to timers with delegates bound to those objects, for quick lookup.
Definition at line 458 of file TimerManager.h.
OwningGameInstance
UGameInstance* FTimerManager::OwningGameInstance private
The game instance that created this timer manager.
May be null if this timer manager wasn't created by a game instance.
Definition at line 473 of file TimerManager.h.
PausedTimerSet
TSet<FTimerHandle> FTimerManager::PausedTimerSet private
Set of paused timers.
Definition at line 454 of file TimerManager.h.
PendingTimerSet
TSet<FTimerHandle> FTimerManager::PendingTimerSet private
Set of timers added this frame, to be added after timer has been ticked.
Definition at line 456 of file TimerManager.h.
Timers
TSparseArray<FTimerData> FTimerManager::Timers private
The array of timers - all other arrays will index into this.
Definition at line 450 of file TimerManager.h.
TimerSourceList
TUniquePtr<FTimerSourceList> FTimerManager::TimerSourceList private
Debugging/tracking information used when TimerManager.BuildTimerSourceList is set.
Definition at line 477 of file TimerManager.h.
The documentation for this class was generated from the following file:
TimerManager.h