Unreal Engine 5.6 C++ API: UE::AnimNext::FParamCompatibility Struct Reference
UE::AnimNext::FParamCompatibility Struct Reference
#include "ParamCompatibility.h"
Public Member Functions
FParamCompatibility (EParamCompatibility InCompatibility)
bool IsCompatible () const
bool IsCompatibleWithDataLoss () const
bool IsEqual () const
bool operator!= (const FParamCompatibility &InOther) const
bool operator< (const FParamCompatibility &InOther) const
bool operator<= (const FParamCompatibility &InOther) const
bool operator== (const FParamCompatibility &InOther) const
bool operator> (const FParamCompatibility &InOther) const
bool operator>= (const FParamCompatibility &InOther) const
Static Public Member Functions
static FParamCompatibility Compatible ()
static FParamCompatibility Equal ()
static FParamCompatibility IncompatibleWithDataLoss ()
Data Fields
EParamCompatibility Compatibility
Detailed Description
Definition at line 28 of file ParamCompatibility.h.
Constructor & Destructor Documentation
FParamCompatibility()
UE::AnimNext::FParamCompatibility::FParamCompatibility (EParamCompatibility InCompatibility) inline
Definition at line 30 of file ParamCompatibility.h.
References Compatibility.
Referenced by Compatible(), Equal(), IncompatibleWithDataLoss(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
Member Function Documentation
Compatible()
FParamCompatibility UE::AnimNext::FParamCompatibility::Compatible () inline static
Definition at line 41 of file ParamCompatibility.h.
References FParamCompatibility(), and UE::AnimNext::Compatible_Promotion.
Equal()
FParamCompatibility UE::AnimNext::FParamCompatibility::Equal () inline static
Definition at line 36 of file ParamCompatibility.h.
References FParamCompatibility(), and UE::AnimNext::Compatible_Cast.
IncompatibleWithDataLoss()
FParamCompatibility UE::AnimNext::FParamCompatibility::IncompatibleWithDataLoss () inline static
Definition at line 46 of file ParamCompatibility.h.
References FParamCompatibility(), and UE::AnimNext::Incompatible_DataLoss.
IsCompatible()
bool UE::AnimNext::FParamCompatibility::IsCompatible () const inline
Definition at line 56 of file ParamCompatibility.h.
References Compatibility, and UE::AnimNext::Compatible_Promotion.
IsCompatibleWithDataLoss()
bool UE::AnimNext::FParamCompatibility::IsCompatibleWithDataLoss () const inline
Definition at line 61 of file ParamCompatibility.h.
References Compatibility, and UE::AnimNext::Incompatible_DataLoss.
IsEqual()
bool UE::AnimNext::FParamCompatibility::IsEqual () const inline
Definition at line 51 of file ParamCompatibility.h.
References Compatibility, and UE::AnimNext::Compatible_Cast.
operator!=()
bool UE::AnimNext::FParamCompatibility::operator!= (const FParamCompatibility & InOther) const inline
Definition at line 81 of file ParamCompatibility.h.
References FParamCompatibility(), and Compatibility.
operator<()
bool UE::AnimNext::FParamCompatibility::operator< (const FParamCompatibility & InOther) const inline
Definition at line 66 of file ParamCompatibility.h.
References FParamCompatibility(), and Compatibility.
operator<=()
bool UE::AnimNext::FParamCompatibility::operator<= (const FParamCompatibility & InOther) const inline
Definition at line 71 of file ParamCompatibility.h.
References FParamCompatibility(), and Compatibility.
operator==()
bool UE::AnimNext::FParamCompatibility::operator== (const FParamCompatibility & InOther) const inline
Definition at line 76 of file ParamCompatibility.h.
References FParamCompatibility(), and Compatibility.
operator>()
bool UE::AnimNext::FParamCompatibility::operator> (const FParamCompatibility & InOther) const inline
Definition at line 91 of file ParamCompatibility.h.
References FParamCompatibility(), and Compatibility.
operator>=()
bool UE::AnimNext::FParamCompatibility::operator>= (const FParamCompatibility & InOther) const inline
Definition at line 86 of file ParamCompatibility.h.
References FParamCompatibility(), and Compatibility.
Field Documentation
Compatibility
EParamCompatibility UE::AnimNext::FParamCompatibility::Compatibility
Definition at line 34 of file ParamCompatibility.h.
Referenced by FParamCompatibility(), IsCompatible(), IsCompatibleWithDataLoss(), IsEqual(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this struct was generated from the following file:
ParamCompatibility.h