Unreal Engine 5.6 C++ API: TBitArray< Allocator >::FConstWordIterator Struct Reference
TBitArray< Allocator >::FConstWordIterator Struct Reference
#include "BitArray.h"
Public Member Functions
FConstWordIterator (const TBitArray< Allocator > &InArray UE_LIFETIMEBOUND)
FConstWordIterator (const TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 InStartBitIndex, int32 InEndBitIndex)
Public Member Functions inherited from TBitArray< Allocator >::TWordIteratorBase< const uint32 >
void FillMissingBits (uint32 InMissingBitsFill)
int32 GetIndex () const
uint32 GetWord () const
operator bool () const
void operator++ ()
Additional Inherited Members
Protected Member Functions inherited from TBitArray< Allocator >::TWordIteratorBase< const uint32 >
TWordIteratorBase (const uint32 *InData, int32 InStartBitIndex, int32 InEndBitIndex)
Protected Attributes inherited from TBitArray< Allocator >::TWordIteratorBase< const uint32 >
int32 CurrentIndex
uint32 CurrentMask
const uint32 *RESTRICT Data
uint32 FinalMask
uint32 MissingBitsFill
int32 NumWords
Detailed Description
template<typename Allocator>
struct TBitArray< Allocator >::FConstWordIterator
Definition at line 1771 of file BitArray.h.
Constructor & Destructor Documentation
FConstWordIterator() [1/2]
template<typename Allocator> TBitArray< Allocator >::FConstWordIterator::FConstWordIterator (const TBitArray< Allocator > &InArray UE_LIFETIMEBOUND) inline explicit nodiscard
Definition at line 1773 of file BitArray.h.
References TBitArray< Allocator >::TBitArray(), TBitArray< Allocator >::TWordIteratorBase< const uint32 >::TWordIteratorBase(), TBitArray< Allocator >::GetData(), TBitArray< Allocator >::Num(), and UE_LIFETIMEBOUND.
FConstWordIterator() [2/2]
template<typename Allocator> TBitArray< Allocator >::FConstWordIterator::FConstWordIterator (const TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 InStartBitIndex, int32 InEndBitIndex) inline explicit nodiscard
Definition at line 1778 of file BitArray.h.
References TBitArray< Allocator >::TBitArray(), TBitArray< Allocator >::TWordIteratorBase< const uint32 >::TWordIteratorBase(), checkSlow, TBitArray< Allocator >::GetData(), and UE_LIFETIMEBOUND.
The documentation for this struct was generated from the following file:
BitArray.h