Unreal Engine 5.6 C++ API: FDeprecatedSerializedPackedNormal Class Reference
FDeprecatedSerializedPackedNormal Class Reference
#include "PackedNormal.h"
Public Member Functions
operator FVector3d () const
operator FVector3f () const
operator FVector4d () const
operator FVector4f () const
Private Attributes
union {
struct {
uint8 W
uint8 X
uint8 Y
uint8 Z
}
uint32 Packed
} Vector
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FDeprecatedSerializedPackedNormal &N)
Detailed Description
Definition at line 65 of file PackedNormal.h.
Member Function Documentation
operator FVector3d()
FDeprecatedSerializedPackedNormal::operator FVector3d () const inline
Definition at line 89 of file PackedNormal.h.
operator FVector3f()
FDeprecatedSerializedPackedNormal::operator FVector3f () const inline
Definition at line 77 of file PackedNormal.h.
References VectorLoadByte4, VectorMultiplyAdd(), VectorSetFloat1(), and VectorStoreFloat3().
operator FVector4d()
FDeprecatedSerializedPackedNormal::operator FVector4d () const inline
Definition at line 107 of file PackedNormal.h.
operator FVector4f()
FDeprecatedSerializedPackedNormal::operator FVector4f () const inline
Definition at line 95 of file PackedNormal.h.
References VectorLoadByte4, VectorMultiplyAdd(), VectorSetFloat1(), and VectorStore().
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FDeprecatedSerializedPackedNormal & N) friend
References Ar.
Field Documentation
Packed
uint32 FDeprecatedSerializedPackedNormal::Packed
Definition at line 73 of file PackedNormal.h.
[union]
union { ... } FDeprecatedSerializedPackedNormal::Vector
W
uint8 FDeprecatedSerializedPackedNormal::W
Definition at line 71 of file PackedNormal.h.
X
uint8 FDeprecatedSerializedPackedNormal::X
Definition at line 71 of file PackedNormal.h.
Y
uint8 FDeprecatedSerializedPackedNormal::Y
Definition at line 71 of file PackedNormal.h.
Z
uint8 FDeprecatedSerializedPackedNormal::Z
Definition at line 71 of file PackedNormal.h.
The documentation for this class was generated from the following file:
PackedNormal.h