Unreal Engine 5.6 C++ API: STextBlock Class Reference
STextBlock Class Reference
A simple static text widget.
#include "STextBlock.h"
Public Member Functions
virtual FVector2D ComputeDesiredSize (float) const override
Overwritten from SWidget.
FSlateColor GetColorAndOpacity () const
Gets the current foreground color.
const FSlateColor & GetColorAndOpacityRef () const
Gets the current foreground color as ref.
FSlateFontInfo GetFont () const
Gets the current font.
const FSlateFontInfo & GetFontRef () const
Gets the current font as ref.
FSlateColor GetHighlightColor () const
Gets the current highlight color.
const FSlateBrush * GetHighlightShape () const
Gets the current highlight shape.
FMargin GetMargin () const
Gets the current margin.
float GetMinDesiredWidth () const
Gets the current min desired width.
FLinearColor GetShadowColorAndOpacity () const
Gets the current shadow color and opacity.
const FLinearColor & GetShadowColorAndOpacityRef () const
Gets the current shadow color and opacity as ref.
FVector2f GetShadowOffset () const
Gets the current shadow offset.
const FSlateBrush * GetStrikeBrush () const
Gets the current strike brush.
ETextTransformPolicy GetTransformPolicyImpl () const
Get TransformPolicy attribute.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
Overwritten from SWidget.
void SetApplyLineHeightToBottomLine (TAttribute< bool > InApplyLineHeightToBottomLine)
See ApplyLineHeightToBottomLine attribute.
void SetAutoWrapText (TAttribute< bool > InAutoWrapText)
See AutoWrapText attribute.
void SetColorAndOpacity (TAttribute< FSlateColor > InColorAndOpacity)
See ColorAndOpacity attribute.
void SetFont (TAttribute< FSlateFontInfo > InFont)
Sets the font used to draw the text.
void SetHighlightColor (TAttribute< FLinearColor > InHighlightColor)
See HighlightColor attribute.
void SetHighlightShape (TAttribute< const FSlateBrush * > InHighlightShape)
See HighlightShape attribute.
void SetHighlightText (TAttribute< FText > InText)
Sets the highlight text for this text block.
void SetJustification (TAttribute< ETextJustify::Type > InJustification)
See Justification attribute.
void SetLineHeightPercentage (TAttribute< float > InLineHeightPercentage)
See LineHeightPercentage attribute.
void SetMargin (TAttribute< FMargin > InMargin)
See Margin attribute.
void SetMinDesiredWidth (TAttribute< float > InMinDesiredWidth)
See MinDesiredWidth attribute.
void SetOverflowPolicy (TOptional< ETextOverflowPolicy > InOverflowPolicy)
Sets the overflow policy for this text block.
void SetShadowColorAndOpacity (TAttribute< FLinearColor > InShadowColorAndOpacity)
See ShadowColorAndOpacity attribute.
void SetShadowOffset (TAttribute< FVector2D > InShadowOffset)
See ShadowOffset attribute.
void SetStrikeBrush (TAttribute< const FSlateBrush * > InStrikeBrush)
Sets the brush used to strike through the text.
void SetText (TAttribute< FText > InText)
Sets the text for this text block.
void SetTextFlowDirection (const TOptional< ETextFlowDirection > &InTextFlowDirection)
See TextFlowDirection attribute.
void SetTextShapingMethod (const TOptional< ETextShapingMethod > &InTextShapingMethod)
See TextShapingMethod attribute.
void SetTextStyle (const FTextBlockStyle *InTextStyle)
See TextStyle argument.
void SetTransformPolicy (TAttribute< ETextTransformPolicy > InTransformPolicy)
Set TransformPolicy attribute.
void SetWrappingPolicy (TAttribute< ETextWrappingPolicy > InWrappingPolicy)
Set WrappingPolicy attribute.
void SetWrapTextAt (TAttribute< float > InWrapTextAt)
See WrapTextAt attribute.
Public Member Functions inherited from SLeafWidget
SLeafWidget ()
virtual ~SLeafWidget ()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Member Functions
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText AutoWrapText TransformPolicy LineHeightPercentage SLATE_ATTRIBUTE(bool, ApplyLineHeightToBottomLine) SLATE_ATTRIBUTE(ETextJustify ~STextBlock ()
Whether to leave extra space below the last line due to line height.
void Construct (const FArguments &InArgs)
Construct this widget.
FTextBlockStyle GetComputedTextStyle () const
Get the computed text style to use with the text marshaller.
const FText & GetText () const
Gets the text assigned to this text block.
void InvalidateText (EInvalidateWidgetReason InvalidateReason)
Call to invalidate this text block.
TextStyle StrikeBrush ShadowOffset HighlightColor SLATE_ATTRIBUTE (const FSlateBrush *, HighlightShape) SLATE_ATTRIBUTE(FText
The brush used to highlight the specified text.
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText AutoWrapText SLATE_ATTRIBUTE (ETextWrappingPolicy, WrappingPolicy) SLATE_ATTRIBUTE(ETextTransformPolicy
The wrapping policy to use.
TextStyle StrikeBrush ShadowOffset SLATE_ATTRIBUTE (FLinearColor, ShadowColorAndOpacity) SLATE_ATTRIBUTE(FLinearColor
Shadow color and opacity.
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText SLATE_ATTRIBUTE (float, WrapTextAt) SLATE_ATTRIBUTE(bool
Whether text wraps onto a new line when it's length exceeds this width; if this value is zero or negative, no wrapping occurs.
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText AutoWrapText TransformPolicy SLATE_ATTRIBUTE (FMargin, Margin) SLATE_ATTRIBUTE(float
The amount of blank space left around the edges of text area.
TextStyle StrikeBrush SLATE_ATTRIBUTE (FSlateColor, ColorAndOpacity) SLATE_ATTRIBUTE(FVector2D
Text color and opacity.
TextStyle SLATE_ATTRIBUTE (FSlateFontInfo, Font) SLATE_ATTRIBUTE(const FSlateBrush *
Sets the font used to draw the text.
SLATE_ATTRIBUTE (FText, Text) SLATE_STYLE_ARGUMENT(FTextBlockStyle
The text displayed in this text block.
SLATE_DECLARE_WIDGET_API (STextBlock, SLeafWidget, 1) public
void UpdateTextBlockLayout (float LayoutScaleMultiplier) const
Update the TextBlock layout.
Private Attributes
union {
struct {
uint16 bIsAttributeBoundTextBound: 1
uint16 bIsAttributeColorAndOpacitySet: 1
uint16 bIsAttributeFontSet: 1
uint16 bIsAttributeHighlightColorSet: 1
uint16 bIsAttributeHighlightShapeSet: 1
uint16 bIsAttributeShadowColorAndOpacitySet: 1
uint16 bIsAttributeShadowOffsetSet: 1
uint16 bIsAttributeStrikeBrushSet: 1
uint16 bIsAttributeTransformPolicySet: 1
uint16 bIsAttributeWrapTextAtSet: 1
uint16 bTextLayoutUpdateDesiredSize: 1
uint16 bTextLayoutUpdateTextStyle: 1
}
uint16 Union_Flags
};
Flags used to check if the SlateAttribute is set.
TSlateAttribute< bool > ApplyLineHeightToBottomLine
Whether to leave extra space below the last line due to line height.
TSlateAttribute< bool > AutoWrapText
True if we're wrapping text automatically based on the computed horizontal space for this widget.
TSlateAttribute< FText > BoundText
The text displayed in this text block.
bool bSimpleTextMode
TOptional< FVector2f > CachedSimpleDesiredSize
If this is enabled, text shaping, wrapping, justification are disabled in favor of much faster text layout and measurement.
TSlateAttribute< FSlateColor > ColorAndOpacity
Text color and opacity.
TSlateAttribute< FSlateFontInfo > Font
Sets the font used to draw the text.
TSlateAttribute< FLinearColor > HighlightColor
The color used to highlight the specified text.
TSlateAttribute< const FSlateBrush * > HighlightShape
The brush used to highlight the specified text.
TSlateAttribute< FText > HighlightText
Highlight this text in the TextBlock.
TSlateAttribute< ETextJustify::Type > Justification
The amount to scale each lines height by.
TSlateAttribute< float > LineHeightPercentage
How the text should be aligned with the margin.
TSlateAttribute< FMargin > Margin
The amount of blank space left around the edges of text area.
TSlateAttribute< float > MinDesiredWidth
Prevents the text block from being smaller than desired in certain cases (e.g.
TSlateAttribute< FLinearColor > ShadowColorAndOpacity
Shadow color and opacity.
TSlateAttribute< FVector2D > ShadowOffset
Drop shadow offset in pixels.
TSlateAttribute< const FSlateBrush * > StrikeBrush
Sets the brush used to strike through the text.
TUniquePtr< FSlateTextBlockLayout > TextLayoutCache
The wrapped layout for this text block.
FTextBlockStyle TextStyle
Default style used by the TextLayout.
TSlateAttribute< ETextTransformPolicy > TransformPolicy
The transform policy we're using.
TSlateAttribute< ETextWrappingPolicy > WrappingPolicy
The wrapping policy we're using.
TSlateAttribute< float > WrapTextAt
Whether text wraps onto a new line when it's length exceeds this width; if this value is zero or negative, no wrapping occurs.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
A simple static text widget.
Definition at line 39 of file STextBlock.h.
Constructor & Destructor Documentation
~STextBlock()
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText AutoWrapText TransformPolicy LineHeightPercentage SLATE_ATTRIBUTE(bool, ApplyLineHeightToBottomLine) SLATE_ATTRIBUTE(ETextJustify STextBlock::~STextBlock () private
Whether to leave extra space below the last line due to line height.
How the text should be aligned with the margin. Minimum width that a text block should be Which text shaping method should we use? (unset to use the default returned by GetDefaultTextShapingMethod) Which text flow direction should we use? (unset to use the default returned by GetDefaultTextFlowDirection) The iterator to use to detect appropriate soft-wrapping points for lines (or null to use the default) Determines what happens to text that is clipped and doesn't fit within the clip rect for this widget If this is enabled, text shaping, wrapping, justification are disabled in favor of much faster text layout and measurement. This feature is suitable for numbers and text that changes often and impact performance. Enabling this setting may cause certain languages (such as Right to left languages) to not display properly. Called when this text is double clicked Constructor Destructor
Member Function Documentation
ComputeDesiredSize()
virtual FVector2D STextBlock::ComputeDesiredSize (float) const override virtual
Overwritten from SWidget.
LeafWidgets should compute their DesiredSize based solely on their visual representation. There is no need to take child widgets into account as LeafWidgets have none by definition. For example, the TextBlock widget simply measures the area necessary to display its text with the given font and font size.
Implements SLeafWidget.
References Main.
Construct()
void STextBlock::Construct (const FArguments & InArgs) private
Construct this widget.
Parameters
InArgs The declaration data for this widget
References Construct().
Referenced by Construct().
GetColorAndOpacity()
FSlateColor STextBlock::GetColorAndOpacity () const
Gets the current foreground color.
GetColorAndOpacityRef()
const FSlateColor & STextBlock::GetColorAndOpacityRef () const
Gets the current foreground color as ref.
GetComputedTextStyle()
FTextBlockStyle STextBlock::GetComputedTextStyle () const private
Get the computed text style to use with the text marshaller.
GetFont()
FSlateFontInfo STextBlock::GetFont () const
Gets the current font.
GetFontRef()
const FSlateFontInfo & STextBlock::GetFontRef () const
Gets the current font as ref.
GetHighlightColor()
FSlateColor STextBlock::GetHighlightColor () const
Gets the current highlight color.
GetHighlightShape()
const FSlateBrush * STextBlock::GetHighlightShape () const
Gets the current highlight shape.
GetMargin()
FMargin STextBlock::GetMargin () const
Gets the current margin.
GetMinDesiredWidth()
float STextBlock::GetMinDesiredWidth () const
Gets the current min desired width.
GetShadowColorAndOpacity()
FLinearColor STextBlock::GetShadowColorAndOpacity () const
Gets the current shadow color and opacity.
GetShadowColorAndOpacityRef()
const FLinearColor & STextBlock::GetShadowColorAndOpacityRef () const
Gets the current shadow color and opacity as ref.
GetShadowOffset()
FVector2f STextBlock::GetShadowOffset () const
Gets the current shadow offset.
GetStrikeBrush()
const FSlateBrush * STextBlock::GetStrikeBrush () const
Gets the current strike brush.
GetText()
const FText & STextBlock::GetText () const inline private
Gets the text assigned to this text block.
Returns
This text block's text string
Definition at line 175 of file STextBlock.h.
References bIsAttributeBoundTextBound, BoundText, and GetText().
Referenced by GetText().
GetTransformPolicyImpl()
ETextTransformPolicy STextBlock::GetTransformPolicyImpl () const
Get TransformPolicy attribute.
InvalidateText()
void STextBlock::InvalidateText (EInvalidateWidgetReason InvalidateReason) private
Call to invalidate this text block.
OnPaint()
virtual int32 STextBlock::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
Overwritten from SWidget.
LeafWidgets provide a visual representation of themselves. They do so by adding DrawElement(s) to the OutDrawElements. DrawElements should have their positions set to absolute coordinates in Window space; for this purpose the Slate system provides the AllottedGeometry parameter. AllottedGeometry describes the space allocated for the visualization of this widget.
Whenever possible, LeafWidgets should avoid dealing with layout properties. See TextBlock for an example.
Implements SLeafWidget.
References SWidget::FSlateWindowElementList.
SetApplyLineHeightToBottomLine()
void STextBlock::SetApplyLineHeightToBottomLine (TAttribute< bool > InApplyLineHeightToBottomLine)
See ApplyLineHeightToBottomLine attribute.
SetAutoWrapText()
void STextBlock::SetAutoWrapText (TAttribute< bool > InAutoWrapText)
See AutoWrapText attribute.
SetColorAndOpacity()
void STextBlock::SetColorAndOpacity (TAttribute< FSlateColor > InColorAndOpacity)
See ColorAndOpacity attribute.
SetFont()
void STextBlock::SetFont (TAttribute< FSlateFontInfo > InFont)
Sets the font used to draw the text.
SetHighlightColor()
void STextBlock::SetHighlightColor (TAttribute< FLinearColor > InHighlightColor)
See HighlightColor attribute.
SetHighlightShape()
void STextBlock::SetHighlightShape (TAttribute< const FSlateBrush * > InHighlightShape)
See HighlightShape attribute.
SetHighlightText()
void STextBlock::SetHighlightText (TAttribute< FText > InText)
Sets the highlight text for this text block.
SetJustification()
void STextBlock::SetJustification (TAttribute< ETextJustify::Type > InJustification)
See Justification attribute.
SetLineHeightPercentage()
void STextBlock::SetLineHeightPercentage (TAttribute< float > InLineHeightPercentage)
See LineHeightPercentage attribute.
SetMargin()
void STextBlock::SetMargin (TAttribute< FMargin > InMargin)
See Margin attribute.
SetMinDesiredWidth()
void STextBlock::SetMinDesiredWidth (TAttribute< float > InMinDesiredWidth)
See MinDesiredWidth attribute.
SetOverflowPolicy()
void STextBlock::SetOverflowPolicy (TOptional< ETextOverflowPolicy > InOverflowPolicy)
Sets the overflow policy for this text block.
SetShadowColorAndOpacity()
void STextBlock::SetShadowColorAndOpacity (TAttribute< FLinearColor > InShadowColorAndOpacity)
See ShadowColorAndOpacity attribute.
SetShadowOffset()
void STextBlock::SetShadowOffset (TAttribute< FVector2D > InShadowOffset)
See ShadowOffset attribute.
SetStrikeBrush()
void STextBlock::SetStrikeBrush (TAttribute< const FSlateBrush * > InStrikeBrush)
Sets the brush used to strike through the text.
SetText()
void STextBlock::SetText (TAttribute< FText > InText)
Sets the text for this text block.
SetTextFlowDirection()
void STextBlock::SetTextFlowDirection (const TOptional< ETextFlowDirection > & InTextFlowDirection)
See TextFlowDirection attribute.
SetTextShapingMethod()
void STextBlock::SetTextShapingMethod (const TOptional< ETextShapingMethod > & InTextShapingMethod)
See TextShapingMethod attribute.
SetTextStyle()
void STextBlock::SetTextStyle (const FTextBlockStyle * InTextStyle)
See TextStyle argument.
SetTransformPolicy()
void STextBlock::SetTransformPolicy (TAttribute< ETextTransformPolicy > InTransformPolicy)
Set TransformPolicy attribute.
SetWrappingPolicy()
void STextBlock::SetWrappingPolicy (TAttribute< ETextWrappingPolicy > InWrappingPolicy)
Set WrappingPolicy attribute.
SetWrapTextAt()
void STextBlock::SetWrapTextAt (TAttribute< float > InWrapTextAt)
See WrapTextAt attribute.
SLATE_ATTRIBUTE() [1/8]
TextStyle StrikeBrush ShadowOffset HighlightColor STextBlock::SLATE_ATTRIBUTE (const FSlateBrush * , HighlightShape) private
The brush used to highlight the specified text.
Highlight this text in the text block
References HighlightShape, HighlightText, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/8]
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText AutoWrapText STextBlock::SLATE_ATTRIBUTE (ETextWrappingPolicy , WrappingPolicy) private
The wrapping policy to use.
The transform policy to use
References SLATE_ATTRIBUTE(), TransformPolicy, and WrappingPolicy.
SLATE_ATTRIBUTE() [3/8]
TextStyle StrikeBrush ShadowOffset STextBlock::SLATE_ATTRIBUTE (FLinearColor , ShadowColorAndOpacity) private
Shadow color and opacity.
The color used to highlight the specified text
References HighlightColor, ShadowColorAndOpacity, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [4/8]
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText STextBlock::SLATE_ATTRIBUTE (float , WrapTextAt) private
Whether text wraps onto a new line when it's length exceeds this width; if this value is zero or negative, no wrapping occurs.
Whether to wrap text automatically based on the widget's computed horizontal space. IMPORTANT: Using automatic wrapping can result in visual artifacts, as the the wrapped size will computed be at least one frame late! Consider using WrapTextAt instead. The initial desired size will not be clamped. This works best in cases where the text block's size is not affecting other widget's layout.
References AutoWrapText, SLATE_ATTRIBUTE(), and WrapTextAt.
SLATE_ATTRIBUTE() [5/8]
TextStyle StrikeBrush ShadowOffset HighlightColor HighlightText AutoWrapText TransformPolicy STextBlock::SLATE_ATTRIBUTE (FMargin , Margin) private
The amount of blank space left around the edges of text area.
The amount to scale each lines height by.
References ApplyLineHeightToBottomLine, Justification, LineHeightPercentage, Margin, MinDesiredWidth, SLATE_ARGUMENT, SLATE_ATTRIBUTE(), SLATE_END_ARGS, and SLATE_EVENT.
SLATE_ATTRIBUTE() [6/8]
TextStyle StrikeBrush STextBlock::SLATE_ATTRIBUTE (FSlateColor , ColorAndOpacity) private
Text color and opacity.
Drop shadow offset in pixels
References ColorAndOpacity, ShadowOffset, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [7/8]
TextStyle STextBlock::SLATE_ATTRIBUTE (FSlateFontInfo , Font) const private
Sets the font used to draw the text.
Sets the brush used to strike through the text
References Font, SLATE_ATTRIBUTE(), and StrikeBrush.
SLATE_ATTRIBUTE() [8/8]
STextBlock::SLATE_ATTRIBUTE (FText , Text) private
The text displayed in this text block.
Pointer to a style of the text block, which dictates the font, color, and shadow options.
References Text, and TextStyle.
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_DECLARE_WIDGET_API()
STextBlock::SLATE_DECLARE_WIDGET_API (STextBlock , SLeafWidget , 1) inline private
Definition at line 41 of file STextBlock.h.
References SLeafWidget::SLeafWidget(), and Left.
UpdateTextBlockLayout()
void STextBlock::UpdateTextBlockLayout (float LayoutScaleMultiplier) const private
Update the TextBlock layout.
Field Documentation
[union]
union { ... } STextBlock
Flags used to check if the SlateAttribute is set.
ApplyLineHeightToBottomLine
TSlateAttribute<bool> STextBlock::ApplyLineHeightToBottomLine private
Whether to leave extra space below the last line due to line height.
Definition at line 367 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
AutoWrapText
TSlateAttribute<bool> STextBlock::AutoWrapText private
True if we're wrapping text automatically based on the computed horizontal space for this widget.
Definition at line 349 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
bIsAttributeBoundTextBound
uint16 STextBlock::bIsAttributeBoundTextBound
Definition at line 381 of file STextBlock.h.
Referenced by GetText().
bIsAttributeColorAndOpacitySet
uint16 STextBlock::bIsAttributeColorAndOpacitySet
Definition at line 384 of file STextBlock.h.
bIsAttributeFontSet
uint16 STextBlock::bIsAttributeFontSet
Definition at line 382 of file STextBlock.h.
bIsAttributeHighlightColorSet
uint16 STextBlock::bIsAttributeHighlightColorSet
Definition at line 387 of file STextBlock.h.
bIsAttributeHighlightShapeSet
uint16 STextBlock::bIsAttributeHighlightShapeSet
Definition at line 388 of file STextBlock.h.
bIsAttributeShadowColorAndOpacitySet
uint16 STextBlock::bIsAttributeShadowColorAndOpacitySet
Definition at line 386 of file STextBlock.h.
bIsAttributeShadowOffsetSet
uint16 STextBlock::bIsAttributeShadowOffsetSet
Definition at line 385 of file STextBlock.h.
bIsAttributeStrikeBrushSet
uint16 STextBlock::bIsAttributeStrikeBrushSet
Definition at line 383 of file STextBlock.h.
bIsAttributeTransformPolicySet
uint16 STextBlock::bIsAttributeTransformPolicySet
Definition at line 390 of file STextBlock.h.
bIsAttributeWrapTextAtSet
uint16 STextBlock::bIsAttributeWrapTextAtSet
Definition at line 389 of file STextBlock.h.
BoundText
TSlateAttribute<FText> STextBlock::BoundText private
The text displayed in this text block.
Definition at line 313 of file STextBlock.h.
Referenced by GetText().
bSimpleTextMode
bool STextBlock::bSimpleTextMode private
Definition at line 398 of file STextBlock.h.
bTextLayoutUpdateDesiredSize
uint16 STextBlock::bTextLayoutUpdateDesiredSize mutable
Definition at line 393 of file STextBlock.h.
bTextLayoutUpdateTextStyle
uint16 STextBlock::bTextLayoutUpdateTextStyle mutable
Definition at line 392 of file STextBlock.h.
CachedSimpleDesiredSize
TOptional<FVector2f> STextBlock::CachedSimpleDesiredSize mutable private
If this is enabled, text shaping, wrapping, justification are disabled in favor of much faster text layout and measurement.
Definition at line 373 of file STextBlock.h.
ColorAndOpacity
TSlateAttribute<FSlateColor> STextBlock::ColorAndOpacity private
Text color and opacity.
Definition at line 328 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
Font
TSlateAttribute<FSlateFontInfo> STextBlock::Font private
Sets the font used to draw the text.
Definition at line 322 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
HighlightColor
TSlateAttribute<FLinearColor> STextBlock::HighlightColor private
The color used to highlight the specified text.
Definition at line 337 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
HighlightShape
TSlateAttribute<const FSlateBrush*> STextBlock::HighlightShape private
The brush used to highlight the specified text.
Definition at line 340 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
HighlightText
TSlateAttribute<FText> STextBlock::HighlightText private
Highlight this text in the TextBlock.
Definition at line 343 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
Justification
TSlateAttribute<ETextJustify::Type> STextBlock::Justification private
The amount to scale each lines height by.
Definition at line 361 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
LineHeightPercentage
TSlateAttribute<float> STextBlock::LineHeightPercentage private
How the text should be aligned with the margin.
Definition at line 364 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
Margin
TSlateAttribute<FMargin> STextBlock::Margin private
The amount of blank space left around the edges of text area.
Definition at line 358 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
MinDesiredWidth
TSlateAttribute<float> STextBlock::MinDesiredWidth private
Prevents the text block from being smaller than desired in certain cases (e.g.
when it is empty)
Definition at line 370 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
ShadowColorAndOpacity
TSlateAttribute<FLinearColor> STextBlock::ShadowColorAndOpacity private
Shadow color and opacity.
Definition at line 334 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
ShadowOffset
TSlateAttribute<FVector2D> STextBlock::ShadowOffset private
Drop shadow offset in pixels.
Definition at line 331 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
StrikeBrush
TSlateAttribute<const FSlateBrush*> STextBlock::StrikeBrush private
Sets the brush used to strike through the text.
Definition at line 325 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
TextLayoutCache
TUniquePtr< FSlateTextBlockLayout > STextBlock::TextLayoutCache private
The wrapped layout for this text block.
Definition at line 316 of file STextBlock.h.
TextStyle
FTextBlockStyle STextBlock::TextStyle private
Default style used by the TextLayout.
Definition at line 319 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
TransformPolicy
TSlateAttribute<ETextTransformPolicy> STextBlock::TransformPolicy private
The transform policy we're using.
Definition at line 355 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
Union_Flags
uint16 STextBlock::Union_Flags
Definition at line 395 of file STextBlock.h.
WrappingPolicy
TSlateAttribute<ETextWrappingPolicy> STextBlock::WrappingPolicy private
The wrapping policy we're using.
Definition at line 352 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
WrapTextAt
TSlateAttribute<float> STextBlock::WrapTextAt private
Whether text wraps onto a new line when it's length exceeds this width; if this value is zero or negative, no wrapping occurs.
Definition at line 346 of file STextBlock.h.
Referenced by SLATE_ATTRIBUTE().
The documentation for this class was generated from the following file:
STextBlock.h