Unreal Engine 5.6 C++ API: FAssetReferenceFilterReferencerInfo Struct Reference
FAssetReferenceFilterReferencerInfo Struct Reference
#include "EditorEngine.h"
Public Member Functions
FAssetReferenceFilterReferencerInfo ()
FAssetReferenceFilterReferencerInfo (const FAssetData &InData)
FAssetReferenceFilterReferencerInfo (const FAssetData &InData, EAssetReferenceFilterProperties InProperties)
bool operator!= (const FAssetReferenceFilterReferencerInfo &Other) const
bool operator== (const FAssetReferenceFilterReferencerInfo &Other) const
Data Fields
FAssetData Data
EAssetReferenceFilterProperties Properties
Detailed Description
Definition at line 325 of file EditorEngine.h.
Constructor & Destructor Documentation
FAssetReferenceFilterReferencerInfo() [1/3]
FAssetReferenceFilterReferencerInfo::FAssetReferenceFilterReferencerInfo () inline
Definition at line 330 of file EditorEngine.h.
References None, and Properties.
Referenced by operator!=(), and operator==().
FAssetReferenceFilterReferencerInfo() [2/3]
FAssetReferenceFilterReferencerInfo::FAssetReferenceFilterReferencerInfo (const FAssetData & InData) inline
Definition at line 331 of file EditorEngine.h.
References Data, None, and Properties.
FAssetReferenceFilterReferencerInfo() [3/3]
FAssetReferenceFilterReferencerInfo::FAssetReferenceFilterReferencerInfo (const FAssetData & InData, EAssetReferenceFilterProperties InProperties) inline
Definition at line 332 of file EditorEngine.h.
References Data, and Properties.
Member Function Documentation
operator!=()
bool FAssetReferenceFilterReferencerInfo::operator!= (const FAssetReferenceFilterReferencerInfo & Other) const inline
Definition at line 338 of file EditorEngine.h.
References FAssetReferenceFilterReferencerInfo(), and Other.
operator==()
bool FAssetReferenceFilterReferencerInfo::operator== (const FAssetReferenceFilterReferencerInfo & Other) const inline
Definition at line 333 of file EditorEngine.h.
References FAssetReferenceFilterReferencerInfo(), Data, Other, and Properties.
Field Documentation
Data
FAssetData FAssetReferenceFilterReferencerInfo::Data
Definition at line 327 of file EditorEngine.h.
Referenced by FAssetReferenceFilterReferencerInfo(), FAssetReferenceFilterReferencerInfo(), and operator==().
Properties
EAssetReferenceFilterProperties FAssetReferenceFilterReferencerInfo::Properties
Definition at line 328 of file EditorEngine.h.
Referenced by FAssetReferenceFilterReferencerInfo(), FAssetReferenceFilterReferencerInfo(), FAssetReferenceFilterReferencerInfo(), and operator==().
The documentation for this struct was generated from the following file:
EditorEngine.h