Unreal Engine 5.6 C++ API: FStaticMeshVertexFactories Struct Reference
FStaticMeshVertexFactories Struct Reference
#include "StaticMeshResources.h"
Public Member Functions
FStaticMeshVertexFactories (ERHIFeatureLevel::Type InFeatureLevel)
~FStaticMeshVertexFactories ()
void InitResources (const FStaticMeshLODResources &LodResources, uint32 LODIndex, const UStaticMesh *Parent)
void InitResources (const FStaticMeshVertexBuffers &VertexBuffers, uint32 LODIndex, const UStaticMesh *Parent)
Initializes all rendering resources.
void InitVertexFactory (const FStaticMeshLODResources &LodResources, FLocalVertexFactory &InOutVertexFactory, uint32 LODIndex, const UStaticMesh *InParentMesh, bool bInOverrideColorVertexBuffer)
void InitVertexFactory (const FStaticMeshVertexBuffers &VertexBuffers, FLocalVertexFactory &InOutVertexFactory, uint32 LODIndex, const UStaticMesh *InParentMesh, bool bInOverrideColorVertexBuffer)
Initializes a vertex factory for rendering this static mesh.
void ReleaseResources ()
Releases all rendering resources.
Data Fields
struct FSplineMeshVertexFactory * SplineVertexFactory
struct FSplineMeshVertexFactory * SplineVertexFactoryOverrideColorVertexBuffer
FLocalVertexFactory VertexFactory
The vertex factory used when rendering this mesh.
FLocalVertexFactory VertexFactoryOverrideColorVertexBuffer
The vertex factory used when rendering this mesh with vertex colors.
Detailed Description
Definition at line 642 of file StaticMeshResources.h.
Constructor & Destructor Documentation
FStaticMeshVertexFactories()
FStaticMeshVertexFactories::FStaticMeshVertexFactories (ERHIFeatureLevel::Type InFeatureLevel) inline
Definition at line 644 of file StaticMeshResources.h.
References check, SplineVertexFactory, SplineVertexFactoryOverrideColorVertexBuffer, VertexFactory, and VertexFactoryOverrideColorVertexBuffer.
~FStaticMeshVertexFactories()
FStaticMeshVertexFactories::~FStaticMeshVertexFactories ()
Member Function Documentation
InitResources() [1/2]
void FStaticMeshVertexFactories::InitResources (const FStaticMeshLODResources & LodResources, uint32 LODIndex, const UStaticMesh * Parent) inline
Definition at line 685 of file StaticMeshResources.h.
References InitResources(), and Parent.
InitResources() [2/2]
void FStaticMeshVertexFactories::InitResources (const FStaticMeshVertexBuffers & VertexBuffers, uint32 LODIndex, const UStaticMesh * Parent)
Initializes all rendering resources.
References Parent.
Referenced by InitResources().
InitVertexFactory() [1/2]
void FStaticMeshVertexFactories::InitVertexFactory (const FStaticMeshLODResources & LodResources, FLocalVertexFactory & InOutVertexFactory, uint32 LODIndex, const UStaticMesh * InParentMesh, bool bInOverrideColorVertexBuffer) inline
Definition at line 676 of file StaticMeshResources.h.
References InitVertexFactory().
InitVertexFactory() [2/2]
void FStaticMeshVertexFactories::InitVertexFactory (const FStaticMeshVertexBuffers & VertexBuffers, FLocalVertexFactory & InOutVertexFactory, uint32 LODIndex, const UStaticMesh * InParentMesh, bool bInOverrideColorVertexBuffer)
Initializes a vertex factory for rendering this static mesh.
Parameters
InOutVertexFactory The vertex factory to configure
InParentMesh Parent static mesh
bInOverrideColorVertexBuffer If true, make a vertex factory ready for per-instance colors
Referenced by InitVertexFactory().
ReleaseResources()
void FStaticMeshVertexFactories::ReleaseResources ()
Releases all rendering resources.
Field Documentation
SplineVertexFactory
struct FSplineMeshVertexFactory* FStaticMeshVertexFactories::SplineVertexFactory
Definition at line 662 of file StaticMeshResources.h.
Referenced by FStaticMeshVertexFactories().
SplineVertexFactoryOverrideColorVertexBuffer
struct FSplineMeshVertexFactory* FStaticMeshVertexFactories::SplineVertexFactoryOverrideColorVertexBuffer
Definition at line 664 of file StaticMeshResources.h.
Referenced by FStaticMeshVertexFactories().
VertexFactory
FLocalVertexFactory FStaticMeshVertexFactories::VertexFactory
The vertex factory used when rendering this mesh.
Definition at line 657 of file StaticMeshResources.h.
Referenced by FStaticMeshVertexFactories().
VertexFactoryOverrideColorVertexBuffer
FLocalVertexFactory FStaticMeshVertexFactories::VertexFactoryOverrideColorVertexBuffer
The vertex factory used when rendering this mesh with vertex colors.
This is lazy init.
Definition at line 660 of file StaticMeshResources.h.
Referenced by FStaticMeshVertexFactories().
The documentation for this struct was generated from the following file:
StaticMeshResources.h