Unreal Engine 5.6 C++ API: Metasound::FTrigger Class Reference
Metasound::FTrigger Class Reference
FTrigger supports sample accurate triggering, sample accurate internal tracking, and a convenient interface for running trigger-aligned audio signal processing routines on buffers.
#include "MetasoundTrigger.h"
Public Member Functions
METASOUNDFRONTEND_API FTrigger (const FOperatorSettings &InSettings)
FTrigger constructor.
METASOUNDFRONTEND_API FTrigger (const FOperatorSettings &InSettings, bool bShouldTrigger)
FTrigger constructor.
METASOUNDFRONTEND_API FTrigger (const FOperatorSettings &InSettings, int32 InFrameToTrigger)
FTrigger constructor.
METASOUNDFRONTEND_API void Advance (int32 InNumFrames)
Advance internal frame counters by specific frame count.
METASOUNDFRONTEND_API void AdvanceBlock ()
Advance internal frame counters by block size.
METASOUNDFRONTEND_API void AssignRawParameter (const void *ParamPackPayload)
For use when a Trigger request is found in a Parameter Pack.
template<typename PreTriggerType, typename OnTriggerType>
void ExecuteBlock (PreTriggerType InPreTrigger, OnTriggerType InOnTrigger) const
Executes one block of frames and calls underlying InPreTrigger and InOnTrigger functions with frame indices.
METASOUNDFRONTEND_API int32 First () const
Returns frame index for the first trigger in the block.
const TArray< int32 > & GetTriggeredFrames () const
METASOUNDFRONTEND_API bool IsTriggered () const
Returns true if there are any triggered frames.
METASOUNDFRONTEND_API bool IsTriggeredInBlock () const
Returns true there is a trigger in the current block of audio.
METASOUNDFRONTEND_API int32 Last () const
Returns frame index for the last trigger in the block.
template<typename PreTriggerType, typename OnTriggerType>
void LookAhead (int32 InNumFrames, PreTriggerType InPreTrigger, OnTriggerType InOnTrigger) const
Executes a desired number of frames and calls underlying InPreTrigger and InOnTrigger functions with frame indices.
METASOUNDFRONTEND_API int32 Num () const
Number of triggered frames.
METASOUNDFRONTEND_API int32 NumTriggeredInBlock () const
Returns true if there is a trigger in the current block of audio.
METASOUNDFRONTEND_API operator bool () const
Implicit conversion of FTrigger into bool by calling IsTriggeredInBlock()
METASOUNDFRONTEND_API int32 operator[] (int32 InTriggerIndex) const
Returns frame index for a given trigger index.
METASOUNDFRONTEND_API void RemoveAfter (int32 InFrameIndex)
Removes all triggers which occur after the frame index.
METASOUNDFRONTEND_API void Reset ()
Removes all triggered frames.
METASOUNDFRONTEND_API void TriggerFrame (int32 InFrameToTrigger)
Trigger a specific frame in the future.
Private Member Functions
template<typename PreTriggerType, typename OnTriggerType>
void ExecuteFrames (int32 InNumFrames, int32 InLastTriggerIndex, PreTriggerType InPreTrigger, OnTriggerType InOnTrigger) const
METASOUNDFRONTEND_API void UpdateLastTriggerIndexInBlock ()
Private Attributes
bool bHasAdvanced = false
bool bHasTrigger = false
bool bTriggeredFromInit = false
int32 LastTriggerIndexInBlock = 0
int32 NumFramesPerBlock = 0
FSampleRate SampleRate = 0
TArray< int32 > TriggeredFrames
Detailed Description
FTrigger supports sample accurate triggering, sample accurate internal tracking, and a convenient interface for running trigger-aligned audio signal processing routines on buffers.
FTriggers are triggered using FTrigger::TriggerTime or FTrigger::TriggerFrame. FTriggers track time internally by calling FTrigger::Advance. Executing audio signal processing on buffers can be performed by calling FTrigger::ExecuteBlock or FTrigger::LookAhead.
Definition at line 23 of file MetasoundTrigger.h.
Constructor & Destructor Documentation
FTrigger() [1/3]
METASOUNDFRONTEND_API Metasound::FTrigger::FTrigger (const FOperatorSettings & InSettings, bool bShouldTrigger) explicit
FTrigger constructor.
Parameters
InSettings - Operator settings.
bShouldTrigger - If true, triggers first sample.
References UE_API.
FTrigger() [2/3]
METASOUNDFRONTEND_API Metasound::FTrigger::FTrigger (const FOperatorSettings & InSettings, int32 InFrameToTrigger) explicit
FTrigger constructor.
Parameters
InFrameToTrigger - Set specific frame to trigger.
InSettings - Operator settings.
References UE_API.
FTrigger() [3/3]
METASOUNDFRONTEND_API Metasound::FTrigger::FTrigger (const FOperatorSettings & InSettings)
FTrigger constructor.
By default it is not triggered.
Parameters
InSettings - Operator settings.
References UE_API.
Member Function Documentation
Advance()
METASOUNDFRONTEND_API void Metasound::FTrigger::Advance (int32 InNumFrames)
Advance internal frame counters by specific frame count.
References UE_API.
AdvanceBlock()
METASOUNDFRONTEND_API void Metasound::FTrigger::AdvanceBlock ()
Advance internal frame counters by block size.
References UE_API.
Referenced by Metasound::TPostExecutableDataType< FTrigger >::PostExecute().
AssignRawParameter()
METASOUNDFRONTEND_API void Metasound::FTrigger::AssignRawParameter (const void * ParamPackPayload)
For use when a Trigger request is found in a Parameter Pack.
Parameters
ParamPackPayload - A pointer to a bool which should always be 'true'.
References UE_API.
ExecuteBlock()
template<typename PreTriggerType, typename OnTriggerType> void Metasound::FTrigger::ExecuteBlock (PreTriggerType InPreTrigger, OnTriggerType InOnTrigger) const inline
Executes one block of frames and calls underlying InPreTrigger and InOnTrigger functions with frame indices.
Parameters
InPreTrigger - A function which handles frames before the first trigger in the current block. The function must accept the arguments (int32 StartFrame, int32 EndFrame).
InOnTrigger - A function which handles frames starting with the triggers index and ending the next trigger index or the number of frames in a block.. The function must accept the arguments (int32 StartFrame, int32 EndFrame).
Definition at line 120 of file MetasoundTrigger.h.
References ExecuteFrames(), LastTriggerIndexInBlock, and NumFramesPerBlock.
ExecuteFrames()
template<typename PreTriggerType, typename OnTriggerType> void Metasound::FTrigger::ExecuteFrames (int32 InNumFrames, int32 InLastTriggerIndex, PreTriggerType InPreTrigger, OnTriggerType InOnTrigger) const inline private
Definition at line 157 of file MetasoundTrigger.h.
References TriggeredFrames.
Referenced by ExecuteBlock(), and LookAhead().
First()
METASOUNDFRONTEND_API int32 Metasound::FTrigger::First () const
Returns frame index for the first trigger in the block.
Returns
The frame of the first trigger in the block or -1 if there is no trigger in the block.
References UE_API.
GetTriggeredFrames()
const TArray< int32 > & Metasound::FTrigger::GetTriggeredFrames () const inline
Definition at line 148 of file MetasoundTrigger.h.
References TriggeredFrames.
IsTriggered()
METASOUNDFRONTEND_API bool Metasound::FTrigger::IsTriggered () const
Returns true if there are any triggered frames.
References UE_API.
IsTriggeredInBlock()
METASOUNDFRONTEND_API bool Metasound::FTrigger::IsTriggeredInBlock () const
Returns true there is a trigger in the current block of audio.
References UE_API.
Last()
METASOUNDFRONTEND_API int32 Metasound::FTrigger::Last () const
Returns frame index for the last trigger in the block.
Returns
The frame of the last trigger in the block or -1 if there is no trigger in the block.
References UE_API.
LookAhead()
template<typename PreTriggerType, typename OnTriggerType> void Metasound::FTrigger::LookAhead (int32 InNumFrames, PreTriggerType InPreTrigger, OnTriggerType InOnTrigger) const inline
Executes a desired number of frames and calls underlying InPreTrigger and InOnTrigger functions with frame indices.
Parameters
InNumFrames - The number of frames to look ahead.
InPreTrigger - A function which handles frames before the first trigger in the range of frames. The function must accept the arguments (int32 StartFrame, int32 EndFrame).
InOnTrigger - A function which handles frames starting with the triggers index and ending the next trigger index or InNumFrames The function must accept the arguments (int32 StartFrame, int32 EndFrame).
Definition at line 138 of file MetasoundTrigger.h.
References ExecuteFrames(), Algo::LowerBound(), and TriggeredFrames.
Num()
METASOUNDFRONTEND_API int32 Metasound::FTrigger::Num () const
Number of triggered frames.
References UE_API.
NumTriggeredInBlock()
METASOUNDFRONTEND_API int32 Metasound::FTrigger::NumTriggeredInBlock () const
Returns true if there is a trigger in the current block of audio.
References UE_API.
operator bool()
METASOUNDFRONTEND_API Metasound::FTrigger::operator bool () const
Implicit conversion of FTrigger into bool by calling IsTriggeredInBlock()
Returns
Returns true if frame is triggered in current block.
References UE_API.
operator[]()
METASOUNDFRONTEND_API int32 Metasound::FTrigger::operator[] (int32 InTriggerIndex) const
Returns frame index for a given trigger index.
Parameters
InIndex - Index of trigger. Must be a value between 0 and Num().
Returns
The frame of the trigger.
References UE_API.
RemoveAfter()
METASOUNDFRONTEND_API void Metasound::FTrigger::RemoveAfter (int32 InFrameIndex)
Removes all triggers which occur after the frame index.
References UE_API.
Reset()
METASOUNDFRONTEND_API void Metasound::FTrigger::Reset ()
Removes all triggered frames.
References UE_API.
TriggerFrame()
METASOUNDFRONTEND_API void Metasound::FTrigger::TriggerFrame (int32 InFrameToTrigger)
Trigger a specific frame in the future.
Parameters
InFrameToTrigger - Index of frame to trigger.
References UE_API.
UpdateLastTriggerIndexInBlock()
METASOUNDFRONTEND_API void Metasound::FTrigger::UpdateLastTriggerIndexInBlock () private
References UE_API.
Field Documentation
bHasAdvanced
bool Metasound::FTrigger::bHasAdvanced = false private
Definition at line 185 of file MetasoundTrigger.h.
bHasTrigger
bool Metasound::FTrigger::bHasTrigger = false private
Definition at line 187 of file MetasoundTrigger.h.
bTriggeredFromInit
bool Metasound::FTrigger::bTriggeredFromInit = false private
Definition at line 186 of file MetasoundTrigger.h.
LastTriggerIndexInBlock
int32 Metasound::FTrigger::LastTriggerIndexInBlock = 0 private
Definition at line 190 of file MetasoundTrigger.h.
Referenced by ExecuteBlock().
NumFramesPerBlock
int32 Metasound::FTrigger::NumFramesPerBlock = 0 private
Definition at line 188 of file MetasoundTrigger.h.
Referenced by ExecuteBlock().
SampleRate
FSampleRate Metasound::FTrigger::SampleRate = 0 private
Definition at line 189 of file MetasoundTrigger.h.
TriggeredFrames
TArray<int32> Metasound::FTrigger::TriggeredFrames private
Definition at line 183 of file MetasoundTrigger.h.
Referenced by ExecuteFrames(), GetTriggeredFrames(), and LookAhead().
The documentation for this class was generated from the following file:
MetasoundTrigger.h