Unreal Engine 5.6 C++ API: AWorldDataLayers Class Reference
AWorldDataLayers Class Reference
#include "WorldDataLayers.h"
Public Member Functions
template<class IdentifierType>
void OverwriteDataLayerRuntimeStates (const TArray< IdentifierType > *InActiveDataLayers, const TArray< IdentifierType > *InLoadedDataLayers)
Private Types
enum class ESetDataLayerRuntimeStateError { NotRuntime , ClientOnlyFromServer , ServerOnlyFromClient , AuthoritativeFromClient }
Private Member Functions
virtual bool ActorTypeIsMainWorldOnly () const override
virtual bool ActorTypeSupportsDataLayer () const override
virtual bool ActorTypeSupportsExternalDataLayer () const override
void AddDataLayerInstance (UDataLayerInstance *InDataLayerInstance)
bool AddExternalDataLayerInstance (UExternalDataLayerInstance *ExternalDataLayerInstance)
bool AddToActorEditorContext (UDataLayerInstance *InDataLayerInstance)
bool CanChangeDataLayerRuntimeState (const UDataLayerInstance *InDataLayerInstance, ESetDataLayerRuntimeStateError *OutReason=nullptr) const
bool CanReferenceDataLayerAsset (const UDataLayerAsset *InDataLayerAsset, FText *OutFailureReason) const
bool ContainsDataLayer (const UDataLayerInstance *InDataLayer) const
void ConvertDataLayerToInstances ()
virtual TUniquePtr< class FWorldPartitionActorDesc > CreateClassActorDesc () const override
template<class DataLayerInstanceType, typename ... CreationsArgs>
DataLayerInstanceType * CreateDataLayer (CreationsArgs... InCreationArgs)
void DumpDataLayerRecursively (const UDataLayerInstance *DataLayer, FString Prefix, FOutputDevice &OutputDevice) const
void DumpDataLayers (FOutputDevice &OutputDevice) const
void ForEachDataLayerInstance (TFunctionRef< bool(UDataLayerInstance *)> Func)
void ForEachDataLayerInstance (TFunctionRef< bool(UDataLayerInstance *)> Func) const
TArray< UDataLayerInstance * > GetActorEditorContextDataLayers () const
bool GetAllowRuntimeDataLayerEditing () const
EDataLayerRuntimeState GetDataLayerEffectiveRuntimeStateByName (FName InDataLAyerName) const
const UDataLayerInstance * GetDataLayerInstance (const FName &InDataLayerInstanceName) const
const UDataLayerInstance * GetDataLayerInstance (const UDataLayerAsset *InDataLayerAsset) const
const UDataLayerInstance * GetDataLayerInstanceFromAssetName (const FName &InDataLayerAssetPathName) const
TArray< FName > GetDataLayerInstanceNames (const TArray< const UDataLayerAsset * > &InDataLayersAssets) const
virtual const TSet< TObjectPtr< UDataLayerInstance > > & GetDataLayerInstances () const override
virtual TSet< TObjectPtr< UDataLayerInstance > > & GetDataLayerInstances () override
TArray< const UDataLayerInstance * > GetDataLayerInstances (const TArray< const UDataLayerAsset * > &InDataLayersAssets) const
TArray< const UDataLayerInstance * > GetDataLayerInstances (const TArray< FName > &InDataLayerInstanceNames) const
TArray< const UDataLayerInstance * > GetDataLayerInstances (const TArray< UDataLayerAsset * > &InDataLayersAssets) const
EDataLayerRuntimeState GetDataLayerRuntimeStateByName (FName InDataLayerName) const
int32 GetDataLayersStateEpoch () const
const TSet< FName > & GetEffectiveActiveDataLayerNames () const
const TSet< FName > & GetEffectiveLoadedDataLayerNames () const
const FWorldDataLayersEffectiveStates & GetEffectiveStates () const
UExternalDataLayerInstance * GetExternalDataLayerInstance (const UExternalDataLayerAsset *InExternalDataLayerAsset)
const UExternalDataLayerInstance * GetExternalDataLayerInstance (const UExternalDataLayerAsset *InExternalDataLayerAsset) const
virtual const UExternalDataLayerInstance * GetRootExternalDataLayerInstance () const override
bool HasDeprecatedDataLayers () const
void InitializeExternalPackageDataLayerInstances ()
bool IsActorEditorContextCurrentColorized (const UDataLayerInstance *InDataLayerInstance) const
virtual bool IsEditorOnly () const override
bool IsEmpty () const
bool IsExternalDataLayerWorldDataLayers () const
bool IsInActorEditorContext (const UDataLayerInstance *InDataLayerInstance) const
virtual bool IsLockLocation () const
bool IsReadOnly (FText *OutReason=nullptr) const
bool IsSubWorldDataLayers () const
virtual bool IsUserManaged () const override
bool IsUsingExternalPackageDataLayerInstances () const
void OnDataLayerManagerInitialized ()
virtual void OnLoadedActorRemovedFromLevel () override
template<class T>
void OverwriteDataLayerRuntimeStates (const TArray< T > *InActiveDataLayers, const TArray< T > *InLoadedDataLayers)
void PopActorEditorContext (int32 InContextID)
virtual void PostEditUndo () override
virtual void PostRegisterAllComponents () override
virtual void PostUnregisterAllComponents () override
virtual void PreEditUndo () override
void PushActorEditorContext (int32 InContextID, bool bDuplicateContext)
bool RemoveDataLayer (const UDataLayerInstance *InDataLayer, bool bInResolveActorDescContainers=true)
int32 RemoveDataLayers (const TArray< UDataLayerInstance * > &InDataLayerInstances, bool bInResolveActorDescContainers=true)
void RemoveEditorDataLayers ()
bool RemoveExternalDataLayerInstance (UExternalDataLayerInstance *ExternalDataLayerInstance)
bool RemoveFromActorEditorContext (UDataLayerInstance *InDataLayerInstance)
void ResetDataLayerRuntimeStates ()
void ResolveActorDescContainers ()
void ResolveEffectiveRuntimeState (const UDataLayerInstance *InDataLayer, bool bInNotifyChange=true)
virtual void RewindForReplay () override
virtual GENERATED_UCLASS_BODY() public void Serialize (FArchive &Ar) override
void SetAllowRuntimeDataLayerEditing (bool bInAllowRuntimeDataLayerEditing)
bool SetDataLayerRuntimeState (const UDataLayerInstance *InDataLayerInstance, EDataLayerRuntimeState InState, bool bIsRecursive=false)
bool SetUseExternalPackageDataLayerInstances (bool bInNewValue, bool bInInteractiveMode=false)
virtual bool ShouldImport (FStringView ActorPropString, bool IsMovingLevel) override
virtual bool ShouldLevelKeepRefIfExternal () const override
bool SupportsExternalPackageDataLayerInstances () const
UE_DEPRECATED (5.0, "Use GetDataLayerRuntimeStateByName() instead.") EDataLayerState GetDataLayerStateByName(FName InDataLayerName) const
UE_DEPRECATED (5.0, "Use GetEffectiveActiveDataLayerNames() instead.") const TSet< FName > &GetActiveDataLayerNames() const
UE_DEPRECATED (5.0, "Use GetEffectiveLoadedDataLayerNames() instead.") const TSet< FName > &GetLoadedDataLayerNames() const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.0, "Use SetDataLayerRuntimeState() instead.") void SetDataLayerState(FActorDataLayer InDataLayer
UE_DEPRECATED (5.1, "Convert DataLayer using UDataLayerToAssetCommandlet and use UDataLayerInstance* overload instead.") 1 bool ContainsDataLayer(const UDEPRECATED_DataLayer *InDataLayer) const
UE_DEPRECATED (5.1, "Convert DataLayer using UDataLayerToAssetCommandlet and use UDataLayerInstance* overload instead.") 1 bool RemoveDataLayer(const UDEPRECATED_DataLayer *InDataLayer)
UE_DEPRECATED (5.1, "Convert UDataLayers to UDataLayerAsset and UDataLayerInstance using DataLayerToAssetCommandLet") 1 const UDataLayerInstance *GetDataLayerFromLabel(const FName &InDataLayerLabel) const
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "Use GetDataLayerInstance with FName or UDataLayerAsset instead") 1 const UDataLayerInstance *GetDataLayerInstance(const FActorDataLayer &InActorDataLayer) const
UE_DEPRECATED (5.1, "Use GetDataLayerInstanceNames with UDataLayerAsset instead") 1 TArray< FName > GetDataLayerInstanceNames(const TArray< FActorDataLayer > &InActorDataLayers) const
UE_DEPRECATED (5.1, "Use GetDataLayerInstances with FName or UDataLayerAsset instead") 1 TArray< const UDataLayerInstance * > GetDataLayerInstances(const TArray< FActorDataLayer > &InActorDataLayers) const
UE_DEPRECATED (5.3, "This function has been deprecated.") void GetUserLoadedInEditorStates(TArray< FName > &OutDataLayersLoadedInEditor
UE_DEPRECATED (5.4, "Use ForEachDataLayerInstance() instead.") void ForEachDataLayer(TFunctionRef< bool(UDataLayerInstance *)> Func)
UE_DEPRECATED (5.4, "Use ForEachDataLayerInstance() instead.") void ForEachDataLayer(TFunctionRef< bool(UDataLayerInstance *)> Func) const
UE_DEPRECATED (5.4, "Use GetWorldPartitionWorldDataLayersName() instead.") static FName GetWorldPartionWorldDataLayersName()
UFUNCTION () 1 void OnDataLayerRuntimeStateChanged(const UDataLayerInstance *InDataLayer
UFUNCTION () 1 void OnRep_ActiveDataLayerNames()
UFUNCTION () 1 void OnRep_EffectiveActiveDataLayerNames()
UFUNCTION () 1 void OnRep_EffectiveLoadedDataLayerNames()
UFUNCTION () 1 void OnRep_LoadedDataLayerNames()
void UpdateContainsDeprecatedDataLayers ()
void UpdateCurrentColorizedDataLayerInstance ()
PRAGMA_ENABLE_DEPRECATION_WARNINGS UPROPERTY () TArray< FName > RepActiveDataLayerNames
UPROPERTY () TArray< FName > RepEffectiveActiveDataLayerNames
UPROPERTY () TArray< FName > RepEffectiveLoadedDataLayerNames
UPROPERTY () TArray< FName > RepLoadedDataLayerNames
UPROPERTY () TArray< TObjectPtr< UDataLayerInstance > > LoadedExternalPackageDataLayerInstances
Temporary array containing data layer instances manually loaded from their external packages.
UPROPERTY () TArray< TObjectPtr< UDataLayerInstance > > TransientDataLayerInstances
UPROPERTY () TMap< FName
UPROPERTY () TObjectPtr< UExternalDataLayerInstance > RootExternalDataLayerInstance
UPROPERTY () TSet< TObjectPtr< UDataLayerInstance > > DataLayerInstances
UPROPERTY () TSet< TObjectPtr< UDataLayerInstance > > ExternalPackageDataLayerInstances
Data layer instances stored in their external package (only used when UseExternalPackageDataLayerInstances is True)
PRAGMA_DISABLE_DEPRECATION_WARNINGS UPROPERTY ()) TSet< TObjectPtr< UDEPRECATED_DataLayer > > WorldDataLayers_DEPRECATED
Static Private Member Functions
static AWorldDataLayers * Create (const FActorSpawnParameters &SpawnParameters)
static AWorldDataLayers * Create (UWorld *World, FName InWorldDataLayerName=NAME_None)
static FName GetWorldPartitionWorldDataLayersName ()
Private Attributes
TSet< FName > ActiveDataLayerNames
bool bHasDeprecatedDataLayers
TSet< TObjectPtr< UDataLayerInstance > > CachedDataLayerInstances
TArray< FName > &OutDataLayersNotLoadedInEditor const
int32 DataLayersStateEpoch
TWeakObjectPtr< UDataLayerInstance > DeprecatedDataLayerNameToDataLayerInstance
FWorldDataLayersEffectiveStates EffectiveStates
EDataLayerRuntimeState InState
PRAGMA_DISABLE_DEPRECATION_WARNINGS EDataLayerState InState { SetDataLayerRuntimeState(GetDataLayerInstance(InDataLayer.Name), (EDataLayerRuntimeState)InState)
TSet< FName > LoadedDataLayerNames
TSet< FName > LocalActiveDataLayerNames
TSet< FName > LocalLoadedDataLayerNames
Friends
struct FWorldDataLayersEffectiveStatesAccessor
class UDataLayerEditorSubsystem
class UDataLayerInstanceWithAsset
class UDataLayerManager
class UDataLayerToAssetCommandlet
class UExternalDataLayerManager
class UWorldPartition
Detailed Description
Definition at line 84 of file WorldDataLayers.h.
Member Enumeration Documentation
ESetDataLayerRuntimeStateError
enum class AWorldDataLayers::ESetDataLayerRuntimeStateError strong private
Enumerator
NotRuntime
ClientOnlyFromServer
ServerOnlyFromClient
AuthoritativeFromClient
Definition at line 249 of file WorldDataLayers.h.
Member Function Documentation
ActorTypeIsMainWorldOnly()
virtual bool AWorldDataLayers::ActorTypeIsMainWorldOnly () const inline override private virtual
Definition at line 285 of file WorldDataLayers.h.
ActorTypeSupportsDataLayer()
virtual bool AWorldDataLayers::ActorTypeSupportsDataLayer () const inline override private virtual
Reimplemented from AInfo.
Definition at line 106 of file WorldDataLayers.h.
ActorTypeSupportsExternalDataLayer()
virtual bool AWorldDataLayers::ActorTypeSupportsExternalDataLayer () const inline override private virtual
Definition at line 107 of file WorldDataLayers.h.
AddDataLayerInstance()
void AWorldDataLayers::AddDataLayerInstance (UDataLayerInstance * InDataLayerInstance) private
Referenced by CreateDataLayer().
AddExternalDataLayerInstance()
bool AWorldDataLayers::AddExternalDataLayerInstance (UExternalDataLayerInstance * ExternalDataLayerInstance) private
AddToActorEditorContext()
bool AWorldDataLayers::AddToActorEditorContext (UDataLayerInstance * InDataLayerInstance) private
CanChangeDataLayerRuntimeState()
bool AWorldDataLayers::CanChangeDataLayerRuntimeState (const UDataLayerInstance * InDataLayerInstance, ESetDataLayerRuntimeStateError * OutReason = nullptr) const private
CanReferenceDataLayerAsset()
bool AWorldDataLayers::CanReferenceDataLayerAsset (const UDataLayerAsset * InDataLayerAsset, FText * OutFailureReason) const private
ContainsDataLayer()
bool AWorldDataLayers::ContainsDataLayer (const UDataLayerInstance * InDataLayer) const private
Referenced by UE_DEPRECATED().
ConvertDataLayerToInstances()
void AWorldDataLayers::ConvertDataLayerToInstances () private
Create() [1/2]
AWorldDataLayers * AWorldDataLayers::Create (const FActorSpawnParameters & SpawnParameters) static private
Create() [2/2]
AWorldDataLayers * AWorldDataLayers::Create (UWorld * World, FName InWorldDataLayerName = NAME_None) static private
CreateClassActorDesc()
virtual TUniquePtr< class FWorldPartitionActorDesc > AWorldDataLayers::CreateClassActorDesc () const override private virtual
CreateDataLayer()
template<class DataLayerInstanceType, typename ... CreationsArgs> DataLayerInstanceType * AWorldDataLayers::CreateDataLayer (CreationsArgs... InCreationArgs) private
Definition at line 404 of file WorldDataLayers.h.
References AddDataLayerInstance(), check, FExternalPackageHelper::CreateExternalPackage(), Forward(), FExternalPackageHelper::GetDefaultExternalPackageFlags(), UObjectBaseUtility::GetPathName(), IDataLayerInstanceProvider::GetRootExternalDataLayerAsset(), IsUsingExternalPackageDataLayerInstances(), FGuid::NewGuid(), NewObject, PKG_PlayInEditor, ResolveActorDescContainers(), RF_Transactional, SupportsExternalPackageDataLayerInstances(), TEXT, FGuid::ToString(), UniqueObjectGuid, and UpdateContainsDeprecatedDataLayers().
DumpDataLayerRecursively()
void AWorldDataLayers::DumpDataLayerRecursively (const UDataLayerInstance * DataLayer, FString Prefix, FOutputDevice & OutputDevice) const private
DumpDataLayers()
void AWorldDataLayers::DumpDataLayers (FOutputDevice & OutputDevice) const private
ForEachDataLayerInstance() [1/2]
void AWorldDataLayers::ForEachDataLayerInstance (TFunctionRef< bool(UDataLayerInstance *)> Func) private
Referenced by OverwriteDataLayerRuntimeStates(), UE_DEPRECATED(), and UE_DEPRECATED().
ForEachDataLayerInstance() [2/2]
void AWorldDataLayers::ForEachDataLayerInstance (TFunctionRef< bool(UDataLayerInstance *)> Func) const private
GetActorEditorContextDataLayers()
TArray< UDataLayerInstance * > AWorldDataLayers::GetActorEditorContextDataLayers () const private
GetAllowRuntimeDataLayerEditing()
bool AWorldDataLayers::GetAllowRuntimeDataLayerEditing () const inline private
Definition at line 124 of file WorldDataLayers.h.
GetDataLayerEffectiveRuntimeStateByName()
EDataLayerRuntimeState AWorldDataLayers::GetDataLayerEffectiveRuntimeStateByName (FName InDataLAyerName) const private
GetDataLayerInstance() [1/2]
const UDataLayerInstance * AWorldDataLayers::GetDataLayerInstance (const FName & InDataLayerInstanceName) const private
Referenced by OverwriteDataLayerRuntimeStates(), and UE_DEPRECATED().
GetDataLayerInstance() [2/2]
const UDataLayerInstance * AWorldDataLayers::GetDataLayerInstance (const UDataLayerAsset * InDataLayerAsset) const private
GetDataLayerInstanceFromAssetName()
const UDataLayerInstance * AWorldDataLayers::GetDataLayerInstanceFromAssetName (const FName & InDataLayerAssetPathName) const private
GetDataLayerInstanceNames()
TArray< FName > AWorldDataLayers::GetDataLayerInstanceNames (const TArray< const UDataLayerAsset * > & InDataLayersAssets) const private
Referenced by UE_DEPRECATED().
GetDataLayerInstances() [1/5]
virtual const TSet< TObjectPtr< UDataLayerInstance > > & AWorldDataLayers::GetDataLayerInstances () const inline override private virtual
Implements IDataLayerInstanceProvider.
Definition at line 276 of file WorldDataLayers.h.
References GetDataLayerInstances().
Referenced by GetDataLayerInstances().
GetDataLayerInstances() [2/5]
virtual TSet< TObjectPtr< UDataLayerInstance > > & AWorldDataLayers::GetDataLayerInstances () override private virtual
GetDataLayerInstances() [3/5]
TArray< const UDataLayerInstance * > AWorldDataLayers::GetDataLayerInstances (const TArray< const UDataLayerAsset * > & InDataLayersAssets) const private
GetDataLayerInstances() [4/5]
TArray< const UDataLayerInstance * > AWorldDataLayers::GetDataLayerInstances (const TArray< FName > & InDataLayerInstanceNames) const private
GetDataLayerInstances() [5/5]
TArray< const UDataLayerInstance * > AWorldDataLayers::GetDataLayerInstances (const TArray< UDataLayerAsset * > & InDataLayersAssets) const private
Referenced by UE_DEPRECATED().
GetDataLayerRuntimeStateByName()
EDataLayerRuntimeState AWorldDataLayers::GetDataLayerRuntimeStateByName (FName InDataLayerName) const private
Referenced by UE_DEPRECATED().
GetDataLayersStateEpoch()
int32 AWorldDataLayers::GetDataLayersStateEpoch () const inline private
Definition at line 187 of file WorldDataLayers.h.
References DataLayersStateEpoch, and GetDataLayersStateEpoch().
Referenced by GetDataLayersStateEpoch().
GetEffectiveActiveDataLayerNames()
const TSet< FName > & AWorldDataLayers::GetEffectiveActiveDataLayerNames () const private
Referenced by UE_DEPRECATED().
GetEffectiveLoadedDataLayerNames()
const TSet< FName > & AWorldDataLayers::GetEffectiveLoadedDataLayerNames () const private
Referenced by UE_DEPRECATED().
GetEffectiveStates()
const FWorldDataLayersEffectiveStates & AWorldDataLayers::GetEffectiveStates () const private
Referenced by FWorldDataLayersEffectiveStatesAccessor::Get().
GetExternalDataLayerInstance() [1/2]
UExternalDataLayerInstance * AWorldDataLayers::GetExternalDataLayerInstance (const UExternalDataLayerAsset * InExternalDataLayerAsset) private
GetExternalDataLayerInstance() [2/2]
const UExternalDataLayerInstance * AWorldDataLayers::GetExternalDataLayerInstance (const UExternalDataLayerAsset * InExternalDataLayerAsset) const private
GetRootExternalDataLayerInstance()
virtual const UExternalDataLayerInstance * AWorldDataLayers::GetRootExternalDataLayerInstance () const inline override private virtual
Implements IDataLayerInstanceProvider.
Definition at line 277 of file WorldDataLayers.h.
GetWorldPartitionWorldDataLayersName()
FName AWorldDataLayers::GetWorldPartitionWorldDataLayersName () inline static private
Definition at line 158 of file WorldDataLayers.h.
References FName, and TEXT.
Referenced by UE_DEPRECATED().
HasDeprecatedDataLayers()
bool AWorldDataLayers::HasDeprecatedDataLayers () const inline private
Definition at line 116 of file WorldDataLayers.h.
References bHasDeprecatedDataLayers.
InitializeExternalPackageDataLayerInstances()
void AWorldDataLayers::InitializeExternalPackageDataLayerInstances () private
IsActorEditorContextCurrentColorized()
bool AWorldDataLayers::IsActorEditorContextCurrentColorized (const UDataLayerInstance * InDataLayerInstance) const private
IsEditorOnly()
virtual bool AWorldDataLayers::IsEditorOnly () const override private virtual
IsEmpty()
bool AWorldDataLayers::IsEmpty () const private
IsExternalDataLayerWorldDataLayers()
bool AWorldDataLayers::IsExternalDataLayerWorldDataLayers () const private
IsInActorEditorContext()
bool AWorldDataLayers::IsInActorEditorContext (const UDataLayerInstance * InDataLayerInstance) const private
IsLockLocation()
virtual bool AWorldDataLayers::IsLockLocation () const inline private virtual
Definition at line 104 of file WorldDataLayers.h.
IsReadOnly()
bool AWorldDataLayers::IsReadOnly (FText * OutReason = nullptr) const private
IsSubWorldDataLayers()
bool AWorldDataLayers::IsSubWorldDataLayers () const private
IsUserManaged()
virtual bool AWorldDataLayers::IsUserManaged () const inline override private virtual
Definition at line 105 of file WorldDataLayers.h.
IsUsingExternalPackageDataLayerInstances()
bool AWorldDataLayers::IsUsingExternalPackageDataLayerInstances () const inline private
Definition at line 148 of file WorldDataLayers.h.
Referenced by CreateDataLayer().
OnDataLayerManagerInitialized()
void AWorldDataLayers::OnDataLayerManagerInitialized () private
OnLoadedActorRemovedFromLevel()
virtual void AWorldDataLayers::OnLoadedActorRemovedFromLevel () override private virtual
OverwriteDataLayerRuntimeStates() [1/2]
template<class IdentifierType> void AWorldDataLayers::OverwriteDataLayerRuntimeStates (const TArray< IdentifierType > * InActiveDataLayers, const TArray< IdentifierType > * InLoadedDataLayers)
Definition at line 449 of file WorldDataLayers.h.
References ActiveDataLayerNames, check, EffectiveStates, FlushNetDormancy, ForEachDataLayerInstance(), GetDataLayerInstance(), LoadedDataLayerNames, TArray< InElementType, InAllocatorType >::Num(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and ResolveEffectiveRuntimeState().
OverwriteDataLayerRuntimeStates() [2/2]
template<class T> void AWorldDataLayers::OverwriteDataLayerRuntimeStates (const TArray< T > * InActiveDataLayers, const TArray< T > * InLoadedDataLayers) private
PopActorEditorContext()
void AWorldDataLayers::PopActorEditorContext (int32 InContextID) private
PostEditUndo()
virtual void AWorldDataLayers::PostEditUndo () override private virtual
PostRegisterAllComponents()
virtual void AWorldDataLayers::PostRegisterAllComponents () override private virtual
PostUnregisterAllComponents()
virtual void AWorldDataLayers::PostUnregisterAllComponents () override private virtual
PreEditUndo()
virtual void AWorldDataLayers::PreEditUndo () override private virtual
PushActorEditorContext()
void AWorldDataLayers::PushActorEditorContext (int32 InContextID, bool bDuplicateContext) private
RemoveDataLayer()
bool AWorldDataLayers::RemoveDataLayer (const UDataLayerInstance * InDataLayer, bool bInResolveActorDescContainers = true) private
Referenced by UE_DEPRECATED().
RemoveDataLayers()
int32 AWorldDataLayers::RemoveDataLayers (const TArray< UDataLayerInstance * > & InDataLayerInstances, bool bInResolveActorDescContainers = true) private
RemoveEditorDataLayers()
void AWorldDataLayers::RemoveEditorDataLayers () private
RemoveExternalDataLayerInstance()
bool AWorldDataLayers::RemoveExternalDataLayerInstance (UExternalDataLayerInstance * ExternalDataLayerInstance) private
RemoveFromActorEditorContext()
bool AWorldDataLayers::RemoveFromActorEditorContext (UDataLayerInstance * InDataLayerInstance) private
ResetDataLayerRuntimeStates()
void AWorldDataLayers::ResetDataLayerRuntimeStates () private
ResolveActorDescContainers()
void AWorldDataLayers::ResolveActorDescContainers () private
Referenced by CreateDataLayer().
ResolveEffectiveRuntimeState()
void AWorldDataLayers::ResolveEffectiveRuntimeState (const UDataLayerInstance * InDataLayer, bool bInNotifyChange = true) private
Referenced by OverwriteDataLayerRuntimeStates().
RewindForReplay()
virtual void AWorldDataLayers::RewindForReplay () override private virtual
Serialize()
virtual GENERATED_UCLASS_BODY() public void AWorldDataLayers::Serialize (FArchive & Ar) override private virtual
References Ar.
SetAllowRuntimeDataLayerEditing()
void AWorldDataLayers::SetAllowRuntimeDataLayerEditing (bool bInAllowRuntimeDataLayerEditing) private
SetDataLayerRuntimeState()
bool AWorldDataLayers::SetDataLayerRuntimeState (const UDataLayerInstance * InDataLayerInstance, EDataLayerRuntimeState InState, bool bIsRecursive = false) private
References InState.
SetUseExternalPackageDataLayerInstances()
bool AWorldDataLayers::SetUseExternalPackageDataLayerInstances (bool bInNewValue, bool bInInteractiveMode = false) private
ShouldImport()
virtual bool AWorldDataLayers::ShouldImport (FStringView ActorPropString, bool IsMovingLevel) inline override private virtual
Definition at line 103 of file WorldDataLayers.h.
ShouldLevelKeepRefIfExternal()
virtual bool AWorldDataLayers::ShouldLevelKeepRefIfExternal () const override private virtual
SupportsExternalPackageDataLayerInstances()
bool AWorldDataLayers::SupportsExternalPackageDataLayerInstances () const private
Referenced by CreateDataLayer().
UE_DEPRECATED() [1/14]
AWorldDataLayers::UE_DEPRECATED (5. 0, "Use GetDataLayerRuntimeStateByName() instead.") const inline private
Definition at line 196 of file WorldDataLayers.h.
References EDataLayerState, and GetDataLayerRuntimeStateByName().
UE_DEPRECATED() [2/14]
AWorldDataLayers::UE_DEPRECATED (5. 0, "Use GetEffectiveActiveDataLayerNames() instead.") const & inline private
Definition at line 199 of file WorldDataLayers.h.
References const, and GetEffectiveActiveDataLayerNames().
UE_DEPRECATED() [3/14]
AWorldDataLayers::UE_DEPRECATED (5. 0, "Use GetEffectiveLoadedDataLayerNames() instead.") const & inline private
Definition at line 202 of file WorldDataLayers.h.
References const, and GetEffectiveLoadedDataLayerNames().
UE_DEPRECATED() [4/14]
PRAGMA_DISABLE_DEPRECATION_WARNINGS AWorldDataLayers::UE_DEPRECATED (5. 0, "Use SetDataLayerRuntimeState() instead.") private
UE_DEPRECATED() [5/14]
AWorldDataLayers::UE_DEPRECATED (5. 1, "Convert DataLayer using UDataLayerToAssetCommandlet and use UDataLayerInstance* overload instead.") const private
References const, ContainsDataLayer(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED() [6/14]
AWorldDataLayers::UE_DEPRECATED (5. 1, "Convert DataLayer using UDataLayerToAssetCommandlet and use UDataLayerInstance* overload instead.") const private
References const, and RemoveDataLayer().
UE_DEPRECATED() [7/14]
AWorldDataLayers::UE_DEPRECATED (5. 1, "Convert UDataLayers to UDataLayerAsset and UDataLayerInstance using DataLayerToAssetCommandLet") const & private
References const, and UE_DEPRECATED().
UE_DEPRECATED() [8/14]
PRAGMA_ENABLE_DEPRECATION_WARNINGS AWorldDataLayers::UE_DEPRECATED (5. 1, "Use GetDataLayerInstance with FName or UDataLayerAsset instead") const & private
References const, GetDataLayerInstance(), and UE_DEPRECATED().
UE_DEPRECATED() [9/14]
AWorldDataLayers::UE_DEPRECATED (5. 1, "Use GetDataLayerInstanceNames with UDataLayerAsset instead") const & private
References const, GetDataLayerInstanceNames(), and UE_DEPRECATED().
UE_DEPRECATED() [10/14]
AWorldDataLayers::UE_DEPRECATED (5. 1, "Use GetDataLayerInstances with FName or UDataLayerAsset instead") const & private
References const, GetDataLayerInstances(), and UE_DEPRECATED().
UE_DEPRECATED() [11/14]
AWorldDataLayers::UE_DEPRECATED (5. 3, "This function has been deprecated.") & private
References UE_DEPRECATED().
UE_DEPRECATED() [12/14]
AWorldDataLayers::UE_DEPRECATED (5. 4, "Use ForEachDataLayerInstance() instead.") inline private
Definition at line 166 of file WorldDataLayers.h.
References ForEachDataLayerInstance().
UE_DEPRECATED() [13/14]
AWorldDataLayers::UE_DEPRECATED (5. 4, "Use ForEachDataLayerInstance() instead.") const inline private
Definition at line 169 of file WorldDataLayers.h.
References ForEachDataLayerInstance().
UE_DEPRECATED() [14/14]
AWorldDataLayers::UE_DEPRECATED (5. 4, "Use GetWorldPartitionWorldDataLayersName() instead.") inline private
Definition at line 155 of file WorldDataLayers.h.
References GetWorldPartitionWorldDataLayersName().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UFUNCTION() [1/5]
AWorldDataLayers::UFUNCTION () const private
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/5]
AWorldDataLayers::UFUNCTION () private
UFUNCTION() [3/5]
AWorldDataLayers::UFUNCTION () private
References UFUNCTION().
UFUNCTION() [4/5]
AWorldDataLayers::UFUNCTION () private
References UFUNCTION().
UFUNCTION() [5/5]
AWorldDataLayers::UFUNCTION () private
References UFUNCTION().
UpdateContainsDeprecatedDataLayers()
void AWorldDataLayers::UpdateContainsDeprecatedDataLayers () private
Referenced by CreateDataLayer().
UpdateCurrentColorizedDataLayerInstance()
void AWorldDataLayers::UpdateCurrentColorizedDataLayerInstance () private
UPROPERTY() [1/11]
PRAGMA_ENABLE_DEPRECATION_WARNINGS AWorldDataLayers::UPROPERTY () private
References Transient, and UPROPERTY().
UPROPERTY() [2/11]
AWorldDataLayers::UPROPERTY () private
References Transient, and UPROPERTY().
UPROPERTY() [3/11]
AWorldDataLayers::UPROPERTY () private
References Transient, and UPROPERTY().
UPROPERTY() [4/11]
AWorldDataLayers::UPROPERTY () private
References Transient, and UPROPERTY().
UPROPERTY() [5/11]
AWorldDataLayers::UPROPERTY () private
Temporary array containing data layer instances manually loaded from their external packages.
References Transient, and UPROPERTY().
UPROPERTY() [6/11]
AWorldDataLayers::UPROPERTY () private
References DATALAYER_TO_INSTANCE_RUNTIME_CONVERSION_ENABLED, Transient, and UPROPERTY().
UPROPERTY() [7/11]
AWorldDataLayers::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [8/11]
AWorldDataLayers::UPROPERTY () private
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [9/11]
AWorldDataLayers::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [10/11]
AWorldDataLayers::UPROPERTY () private
Data layer instances stored in their external package (only used when UseExternalPackageDataLayerInstances is True)
References Transient, and UPROPERTY().
UPROPERTY() [11/11]
PRAGMA_DISABLE_DEPRECATION_WARNINGS AWorldDataLayers::UPROPERTY () private
References meta, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UPROPERTY().
Friends And Related Symbol Documentation
FWorldDataLayersEffectiveStatesAccessor
friend struct FWorldDataLayersEffectiveStatesAccessor friend
Definition at line 376 of file WorldDataLayers.h.
References FWorldDataLayersEffectiveStatesAccessor.
Referenced by FWorldDataLayersEffectiveStatesAccessor.
UDataLayerEditorSubsystem
friend class UDataLayerEditorSubsystem friend
Definition at line 375 of file WorldDataLayers.h.
References UDataLayerEditorSubsystem.
Referenced by UDataLayerEditorSubsystem.
UDataLayerInstanceWithAsset
friend class UDataLayerInstanceWithAsset friend
Definition at line 294 of file WorldDataLayers.h.
References UDataLayerInstanceWithAsset.
Referenced by UDataLayerInstanceWithAsset.
UDataLayerManager
friend class UDataLayerManager friend
Definition at line 373 of file WorldDataLayers.h.
References UDataLayerManager.
Referenced by UDataLayerManager.
UDataLayerToAssetCommandlet
friend class UDataLayerToAssetCommandlet friend
Definition at line 295 of file WorldDataLayers.h.
References UDataLayerToAssetCommandlet.
Referenced by UDataLayerToAssetCommandlet.
UExternalDataLayerManager
friend class UExternalDataLayerManager friend
Definition at line 374 of file WorldDataLayers.h.
References UExternalDataLayerManager.
Referenced by UExternalDataLayerManager.
UWorldPartition
friend class UWorldPartition friend
Definition at line 372 of file WorldDataLayers.h.
References UWorldPartition.
Referenced by UWorldPartition.
Field Documentation
ActiveDataLayerNames
TSet<FName> AWorldDataLayers::ActiveDataLayerNames private
Definition at line 353 of file WorldDataLayers.h.
Referenced by OverwriteDataLayerRuntimeStates().
bHasDeprecatedDataLayers
bool AWorldDataLayers::bHasDeprecatedDataLayers private
Definition at line 370 of file WorldDataLayers.h.
Referenced by HasDeprecatedDataLayers().
CachedDataLayerInstances
TSet<TObjectPtr<UDataLayerInstance> > AWorldDataLayers::CachedDataLayerInstances private
Definition at line 298 of file WorldDataLayers.h.
const
TArray<FName>& OutDataLayersNotLoadedInEditor AWorldDataLayers::const private
Initial value:
{}
protected:
    1 void InitializeDataLayerRuntimeStates()
Definition at line 228 of file WorldDataLayers.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
DataLayersStateEpoch
int32 AWorldDataLayers::DataLayersStateEpoch private
Definition at line 367 of file WorldDataLayers.h.
Referenced by GetDataLayersStateEpoch().
DeprecatedDataLayerNameToDataLayerInstance
TWeakObjectPtr<UDataLayerInstance> AWorldDataLayers::DeprecatedDataLayerNameToDataLayerInstance private
Definition at line 339 of file WorldDataLayers.h.
EffectiveStates
FWorldDataLayersEffectiveStates AWorldDataLayers::EffectiveStates private
Definition at line 365 of file WorldDataLayers.h.
Referenced by OverwriteDataLayerRuntimeStates().
InState [1/2]
EDataLayerRuntimeState AWorldDataLayers::InState private
Definition at line 186 of file WorldDataLayers.h.
Referenced by SetDataLayerRuntimeState().
InState [2/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS EDataLayerState AWorldDataLayers::InState { SetDataLayerRuntimeState(GetDataLayerInstance(InDataLayer.Name), (EDataLayerRuntimeState)InState) private
Definition at line 194 of file WorldDataLayers.h.
LoadedDataLayerNames
TSet<FName> AWorldDataLayers::LoadedDataLayerNames private
Definition at line 354 of file WorldDataLayers.h.
Referenced by OverwriteDataLayerRuntimeStates().
LocalActiveDataLayerNames
TSet<FName> AWorldDataLayers::LocalActiveDataLayerNames private
Definition at line 356 of file WorldDataLayers.h.
LocalLoadedDataLayerNames
TSet<FName> AWorldDataLayers::LocalLoadedDataLayerNames private
Definition at line 357 of file WorldDataLayers.h.
The documentation for this class was generated from the following file:
WorldDataLayers.h