Unreal Engine 5.6 C++ API: RigVMTemplate.h File Reference
RigVMTemplate.h File Reference
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "Delegates/Delegate.h"
#include "HAL/Platform.h"
#include "Internationalization/Text.h"
#include "Math/Color.h"
#include "Misc/AssertionMacros.h"
#include "RigVMFunction.h"
#include "RigVMTypeIndex.h"
#include "RigVMTypeUtils.h"
#include "UObject/Class.h"
#include "UObject/NameTypes.h"
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectPtr.h"
#include "UObject/UnrealNames.h"
#include "RigVMTemplate.generated.h"
Data Structures
struct FRigVMTemplate
The template is used to group multiple rigvm functions that share the same notation.
struct FRigVMTemplateArgument
The template argument represents a single parameter in a function call and all of its possible types.
struct FRigVMTemplateArgument::CategoryViews
struct FRigVMTemplateArgumentInfo
FRigVMTemplateArgumentInfo.
struct FRigVMTemplateDelegates
class FRigVMTypeCacheScope_NoLock
Typedefs
typedef TMap< FName, TRigVMTypeIndex > FRigVMTemplateTypeMap
Functions
DECLARE_DELEGATE_RetVal (FRigVMDispatchFactory *, FRigVMTemplate_GetDispatchFactoryDelegate)
DECLARE_DELEGATE_RetVal_TwoParams (FRigVMTemplateTypeMap, FRigVMTemplate_NewArgumentTypeDelegate, const FName &, TRigVMTypeIndex)
USTRUCT () struct FRigVMTemplateArgumentType
Typedef Documentation
FRigVMTemplateTypeMap
typedef TMap<FName, TRigVMTypeIndex> FRigVMTemplateTypeMap
Definition at line 34 of file RigVMTemplate.h.
Function Documentation
DECLARE_DELEGATE_RetVal()
DECLARE_DELEGATE_RetVal (FRigVMDispatchFactory * , FRigVMTemplate_GetDispatchFactoryDelegate)
DECLARE_DELEGATE_RetVal_TwoParams()
DECLARE_DELEGATE_RetVal_TwoParams (FRigVMTemplateTypeMap , FRigVMTemplate_NewArgumentTypeDelegate , const FName & , TRigVMTypeIndex)
USTRUCT()
USTRUCT ()
Definition at line 46 of file RigVMTemplate.h.
References Array, RigVMTypeUtils::ArrayTypeFromBaseType(), RigVMTypeUtils::AsObject, RigVMTypeUtils::BaseTypeFromArrayType(), RigVMTypeUtils::CPPTypeFromEnum(), RigVMTypeUtils::CPPTypeFromObject(), FORCEINLINE, GENERATED_BODY, GetTypeHash(), RigVMTypeUtils::GetUniqueStructTypeName(), RigVMTypeUtils::GetWildCardArrayCPPTypeName(), RigVMTypeUtils::GetWildCardCPPTypeName(), RigVMTypeUtils::GetWildCardCPPTypeObject(), RigVMTypeUtils::IsArrayType(), FName::IsNone(), IsValid(), operator!=(), operator==(), FName::ToString(), and UPROPERTY.