Unreal Engine 5.6 C++ API: FKeyHandle Struct Reference
FKeyHandle Struct Reference
Key handles are used to keep a handle to a key.
#include "KeyHandle.h"
Public Member Functions
FKeyHandle ()
bool IsValid () const
operator bool () const
bool operator!= (const FKeyHandle &Other) const
bool operator== (const FKeyHandle &Other) const
Static Public Member Functions
static FKeyHandle Invalid ()
Private Member Functions
FKeyHandle (uint32 SpecificIndex)
Private constructor from a specific index - only for use in FKeyHandle::Invalid to avoid allocating new handles unnecessarily.
Private Attributes
uint32 Index
Friends
uint32 GetTypeHash (const FKeyHandle &Handle)
bool operator< (FKeyHandle A, FKeyHandle B)
FArchive & operator<< (FArchive &Ar, FKeyHandle &Handle)
bool operator> (FKeyHandle A, FKeyHandle B)
Detailed Description
Key handles are used to keep a handle to a key.
They are completely transient.
Definition at line 14 of file KeyHandle.h.
Constructor & Destructor Documentation
FKeyHandle() [1/2]
FKeyHandle::FKeyHandle ()
Referenced by GetTypeHash, Invalid(), operator!=(), operator<, operator<<, operator==(), and operator>.
FKeyHandle() [2/2]
FKeyHandle::FKeyHandle (uint32 SpecificIndex) explicit private
Private constructor from a specific index - only for use in FKeyHandle::Invalid to avoid allocating new handles unnecessarily.
Member Function Documentation
Invalid()
FKeyHandle FKeyHandle::Invalid () static
References FKeyHandle().
Referenced by UE::MovieScene::AddKeyToChannel(), TPerlinNoiseChannelInterface< ChannelContainerType >::AddOrUpdateKey_Raw(), and USTRUCT().
IsValid()
bool FKeyHandle::IsValid () const
Referenced by operator bool().
operator bool()
FKeyHandle::operator bool () const inline
Definition at line 22 of file KeyHandle.h.
References IsValid().
operator!=()
bool FKeyHandle::operator!= (const FKeyHandle & Other) const inline
Definition at line 29 of file KeyHandle.h.
References FKeyHandle(), Index, and Other.
operator==()
bool FKeyHandle::operator== (const FKeyHandle & Other) const inline
Definition at line 24 of file KeyHandle.h.
References FKeyHandle(), Index, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FKeyHandle & Handle) friend
Definition at line 44 of file KeyHandle.h.
References FKeyHandle(), GetTypeHash, and Handle.
Referenced by GetTypeHash.
operator<
bool operator< (FKeyHandle A, FKeyHandle B) friend
Definition at line 34 of file KeyHandle.h.
References FKeyHandle(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FKeyHandle & Handle) friend
Definition at line 49 of file KeyHandle.h.
References FKeyHandle(), Ar, and Handle.
operator>
bool operator> (FKeyHandle A, FKeyHandle B) friend
Definition at line 39 of file KeyHandle.h.
References FKeyHandle(), A, and B.
Field Documentation
Index
uint32 FKeyHandle::Index private
Definition at line 60 of file KeyHandle.h.
Referenced by operator!=(), and operator==().
The documentation for this struct was generated from the following file:
KeyHandle.h