Unreal Engine 5.6 C++ API: FMaterial Class Reference
FMaterial Class Reference abstract
FMaterial serves 3 intertwined purposes: Represents a material to the material compilation process, and provides hooks for extensibility (CompileProperty, etc) Represents a material to the renderer, with functions to access material properties Stores a cached shader map, and other transient output from a compile, which is necessary with async shader compiling (when a material finishes async compilation, the shader map and compile errors need to be stored somewhere)
#include "MaterialShared.h"
Public Member Functions
FMaterial ()
Minimal initialization constructor.
virtual ~FMaterial ()
Destructor.
uint32 AddRef () const
virtual void AddReferencedObjects (FReferenceCollector &Collector)
virtual bool AllowNegativeEmissiveColor () const
virtual bool AllowTranslucentLocalLightShadow () const
void AppendCompileStateDebugInfo (FStringBuilderBase &OutDebugInfo) const
virtual void BeginAllowCachingStaticParameterValues ()
void BeginCacheShaders (const FMaterialShaderMapId &ShaderMapId, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode=EMaterialShaderPrecompileMode::Default, const ITargetPlatform *TargetPlatform=nullptr, TUniqueFunction< void(bool bSuccess)> &&CompletionCallback=nullptr)
Begins caching the material shaders for the given static parameter set and platform.
void BeginCacheShaders (EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode=EMaterialShaderPrecompileMode::Default, const ITargetPlatform *TargetPlatform=nullptr, TUniqueFunction< void(bool bSuccess)> &&CompletionCallback=nullptr)
Begins caching the material shaders for the given static parameter set and platform.
void CacheGivenTypes (EShaderPlatform ShaderPlatform, const TArray< const FVertexFactoryType * > &VFTypes, const TArray< const FShaderPipelineType * > &PipelineTypes, const TArray< const FShaderType * > &ShaderTypes)
Submits local compile jobs for the exact given shader types and vertex factory type combination.
bool CacheShaders (const FMaterialShaderMapId &ShaderMapId, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode=EMaterialShaderPrecompileMode::Default, const ITargetPlatform *TargetPlatform=nullptr)
Caches the material shaders for the given static parameter set and platform.
bool CacheShaders (EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode=EMaterialShaderPrecompileMode::Default, const ITargetPlatform *TargetPlatform=nullptr)
Caches the material shaders for this material on the given platform.
void CancelCompilation ()
Cancels all outstanding compilation jobs for this material.
virtual bool CastsRayTracedShadows () const
void ClearPrecachedPSORequestIDs ()
Clear all cached PSO data because manager has been reset.
FGraphEventArray CollectPSOs (ERHIFeatureLevel::Type InFeatureLevel, const FPSOPrecacheVertexFactoryDataList &VertexFactoryDataList, const FPSOPrecacheParams &PreCacheParams, EPSOPrecachePriority Priority, TArray< FMaterialPSOPrecacheRequestID > &OutMaterialPSORequestIDs)
Collect all possible PSO's which can be used with this material for given parameters - PSOs will be async precached.
virtual bool ComputeFogPerPixel () const
void DiscardShaderMap ()
Discards loaded shader maps if the application can't render.
void DumpDebugInfo (FOutputDevice &OutputDevice)
virtual void EndAllowCachingStaticParameterValues ()
virtual void FeedbackMaterialLayersInstancedGraphFromCompilation (const FMaterialLayersFunctions *InLayers)
bool FinishCacheShaders () const
Finishes any pending material caching.
void FinishCompilation ()
Blocks until compilation has completed.
virtual bool GetAllowDevelopmentShaderCompile () const
Returns true if this material is allowed to make development shaders via the global CVar CompileShadersForDevelopment.
virtual FString GetAssetName () const
Similar to GetFriendlyName, but but avoids historical behavior of the former, returning the exact asset name for material instances instead of just the material.
virtual FName GetAssetPath () const
Allows to associate the shader resources with the asset for load order.
virtual int32 GetBlendableLocation () const
virtual bool GetBlendableOutputAlpha () const
virtual int32 GetBlendablePriority () const
virtual enum EBlendMode GetBlendMode () const =0
const FMaterialCachedExpressionData & GetCachedExpressionData () const
virtual bool GetCastDynamicShadowAsMasked () const =0
const TArray< FString > & GetCompileErrors () const
uint8 GetCustomDepthStencilUsageMask_GameThread () const
The material usage mask of CustomDepth and CustomStencil.
const FString & GetDebugGroupName () const
virtual bool GetDisablePreExposureScale () const
virtual FDisplacementFadeRange GetDisplacementFadeRange () const
virtual FDisplacementScaling GetDisplacementScaling () const
const TArray< UMaterialExpression * > & GetErrorExpressions () const
const FStaticFeatureLevel GetFeatureLevel () const
virtual bool GetForceCompatibleWithLightFunctionAtlas () const
virtual bool GetForwardBlendsSkyLightCubemaps () const
virtual FString GetFriendlyName () const =0
virtual FString GetFullPath () const
class FMaterialShaderMap * GetGameThreadShaderMap () const
const FGuid & GetLegacyId () const
virtual uint32 GetMaterialDecalResponse () const
virtual EMaterialDomain GetMaterialDomain () const =0
bool GetMaterialExpressionSource (FString &OutSource)
Get user source code for the material, with a list of code snippets to highlight representing the code for each MaterialExpression.
virtual enum EMaterialFloatPrecisionMode GetMaterialFloatPrecisionMode () const
virtual UMaterialInterface * GetMaterialInterface () const
virtual const FMaterialLayersFunctions * GetMaterialLayers () const
TArray< FMaterialPSOPrecacheRequestID > GetMaterialPSOPrecacheRequestIDs () const
Collect all PSO request information already done for this material.
virtual EMaterialShaderMapUsage::Type GetMaterialShaderMapUsage () const
Returns which shadermap this material is bound to.
virtual EMaterialTranslateValidationFlags GetMaterialTranslateValidationFlags () const
virtual FString GetMaterialUsageDescription () const =0
Returns a string that describes the material's usage for debugging purposes.
virtual int32 GetNeuralProfileId () const
virtual int32 GetNumCustomizedUVs () const
virtual float GetOpacityMaskClipValue () const =0
FName GetOwnerFName () const
For tracking ownership data.
virtual EPixelDepthOffsetMode GetPixelDepthOffsetMode () const
virtual uint16 GetPreshaderGap () const
void GetPreshaderStats (uint32 &TotalParameters, uint32 &TotalOps) const
Returns summary statistics for preshaders.
EMaterialQualityLevel::Type GetQualityLevel () const
uint32 GetRefCount () const
virtual TConstArrayView< TObjectPtr< UTextureCollection > > GetReferencedTextureCollections () const =0
virtual TArrayView< const TObjectPtr< UObject > > GetReferencedTextures () const =0
virtual ERefractionCoverageMode GetRefractionCoverageMode () const
virtual float GetRefractionDepthBiasValue () const
virtual enum ERefractionMode GetRefractionMode () const
class FMaterialShaderMap * GetRenderingThreadShaderMap () const
virtual bool GetRootNodeOverridesDefaultRefraction () const =0
uint8 GetRuntimeVirtualTextureOutputAttibuteMask_GameThread () const
Get the runtime virtual texture output attribute mask for the material.
uint8 GetRuntimeVirtualTextureOutputAttibuteMask_RenderThread () const
template<typename ShaderType>
TShaderRef< ShaderType > GetShader (FVertexFactoryType *VertexFactoryType, const typename ShaderType::FPermutationDomain &PermutationVector, bool bFatalIfMissing=true) const
Finds the shader matching the template type and the passed in vertex factory, asserts if not found.
template<typename ShaderType>
TShaderRef< ShaderType > GetShader (FVertexFactoryType *VertexFactoryType, int32 PermutationId=0, bool bFatalIfMissing=true) const
virtual void GetShaderMapId (EShaderPlatform Platform, const ITargetPlatform *TargetPlatform, FMaterialShaderMapId &OutId) const
FShaderPipelineRef GetShaderPipeline (class FShaderPipelineType *ShaderPipelineType, FVertexFactoryType *VertexFactoryType, bool bFatalIfNotFound=true) const
virtual void GetShaderTags (TArray< FName > &OutShaderTags) const
void GetShaderTypes (EShaderPlatform Platform, const FPlatformTypeLayoutParameters &LayoutParams, TArray< FDebugShaderTypeInfo > &OutShaderInfo) const
Gathers a list of shader types sorted by vertex factory types that should be cached for this material.
void GetShaderTypesForLayout (EShaderPlatform Platform, const FShaderMapLayout &Layout, FVertexFactoryType *VertexFactory, TArray< FDebugShaderTypeInfo > &OutShaderInfo) const
virtual FMaterialShadingModelField GetShadingModels () const =0
virtual EMaterialShadingRate GetShadingRate () const
virtual uint32 GetStencilCompare () const
virtual uint32 GetStencilRefValue () const
virtual const FSubstrateCompilationConfig & GetSubstrateCompilationConfig () const
Get to the Substrate compilation config.
virtual float GetTranslucencyDirectionalLightingIntensity () const
virtual enum ETranslucencyLightingMode GetTranslucencyLightingMode () const
virtual float GetTranslucentBackscatteringExponent () const
virtual float GetTranslucentDirectionalLightShadowQuality () const
virtual float GetTranslucentLocalLightShadowQuality () const
virtual FLinearColor GetTranslucentMultipleScatteringExtinction () const
virtual float GetTranslucentSelfShadowDensityScale () const
virtual float GetTranslucentSelfShadowSecondDensityScale () const
virtual float GetTranslucentSelfShadowSecondOpacity () const
virtual float GetTranslucentShadowDensityScale () const
virtual float GetTranslucentShadowStartOffset () const
TArrayView< const FMaterialTextureParameterInfo > GetUniform2DArrayTextureExpressions () const
TArrayView< const FMaterialTextureParameterInfo > GetUniform2DTextureExpressions () const
TArrayView< const FMaterialTextureParameterInfo > GetUniformCubeTextureExpressions () const
const FUniformExpressionSet & GetUniformExpressions () const
TArrayView< const FMaterialNumericParameterInfo > GetUniformNumericParameterExpressions () const
TArrayView< const FMaterialTextureParameterInfo > GetUniformSparseVolumeTextureExpressions () const
TConstArrayView< FMaterialTextureCollectionParameterInfo > GetUniformTextureCollectionExpressions () const
TArrayView< const FMaterialTextureParameterInfo > GetUniformTextureExpressions (EMaterialTextureParameterType Type) const
TArrayView< const FMaterialTextureParameterInfo > GetUniformVirtualTextureExpressions () const
TArrayView< const FMaterialTextureParameterInfo > GetUniformVolumeTextureExpressions () const
FString GetUniqueAssetName (EShaderPlatform Platform, const FMaterialShaderMapId &ShaderMapId) const
Similar to GetFriendlyName, but appends a hash of shader map ID portion of the DDC key (excluding source file hashes) to differentiate materials/material instances that would collide when considering the base material name alone (this name is used when creating debug output paths for disambiguation).
bool GetUsesDynamicParameter () const
virtual bool HasAmbientOcclusionConnected () const
virtual bool HasAnisotropyConnected () const
virtual bool HasBaseColorConnected () const
virtual bool HasDisplacementConnected () const
virtual bool HasEmissiveColorConnected () const
virtual bool HasFirstPersonOutput () const
virtual bool HasMaterialPropertyConnected (EMaterialProperty In) const
virtual bool HasMetallicConnected () const
virtual bool HasNormalConnected () const
virtual bool HasPerInstanceCustomData () const
virtual bool HasPerInstanceRandom () const
virtual bool HasPixelAnimation () const
virtual bool HasPixelDepthOffsetConnected () const
virtual bool HasRenderTracePhysicalMaterialOutputs () const
virtual bool HasRoughnessConnected () const
virtual bool HasRuntimeVirtualTextureOutput () const
bool HasShaders (const FMaterialShaderTypes &InTypes, const FVertexFactoryType *InVertexFactoryType) const
virtual bool HasSpecularConnected () const
virtual bool HasSubstrateRoughnessTracking () const
bool HasValidGameThreadShaderMap () const
Checks if there is a valid GameThreadShaderMap, that is, the material can be rendered as intended.
virtual bool HasVertexInterpolator () const
virtual bool HasVertexPositionOffsetConnected () const
bool IsCachingShaders () const
Returns whether or not a material caching is still pending.
bool IsCompilationFinished () const
Checks if the compilation for this shader is finished.
virtual bool IsDefaultMaterial () const
virtual bool IsDeferredDecal () const =0
virtual bool IsDisplacementFadeEnabled () const
virtual bool IsDistorted () const
virtual bool IsDitheredLODTransition () const =0
virtual bool IsDitherMasked () const
virtual bool IsDualBlendingEnabled (EShaderPlatform Platform) const
virtual bool IsFullyRough () const
bool IsGameThreadShaderMapComplete () const
virtual bool IsLightFunction () const =0
virtual bool IsMasked () const =0
virtual bool IsMobileSeparateTranslucencyEnabled () const
virtual bool IsNonmetal () const
bool IsOwnerBeginDestroyed () const
virtual bool IsPersistent () const =0
Should shaders compiled for this material be saved to disk?
virtual bool IsPostProcessMaterial () const
virtual bool IsPreview () const
bool IsRenderingThreadShaderMapComplete () const
bool IsRequiredComplete () const
Is the material required to be complete?
virtual bool IsShadingModelFromMaterialExpression () const =0
virtual bool IsSky () const
virtual bool IsSpecialEngineMaterial () const =0
virtual bool IsStencilTestEnabled () const
virtual bool IsSubstrateMaterial () const
virtual bool IsTangentSpaceNormal () const
virtual bool IsTessellationEnabled () const
virtual bool IsThinSurface () const =0
virtual bool IsTranslucencyAfterDOFEnabled () const
virtual bool IsTranslucencyAfterMotionBlurEnabled () const
virtual bool IsTranslucencyVelocityFromDepth () const
virtual bool IsTranslucencyWritingCustomDepth () const
virtual bool IsTranslucencyWritingFrontLayerTransparency () const
virtual bool IsTranslucencyWritingVelocity () const
virtual bool IsTwoSided () const =0
virtual bool IsUIMaterial () const =0
virtual bool IsUsedWithAPEXCloth () const
virtual bool IsUsedWithBeamTrails () const
virtual bool IsUsedWithEditorCompositing () const
virtual bool IsUsedWithGeometryCache () const
virtual bool IsUsedWithGeometryCollections () const
virtual bool IsUsedWithHairStrands () const
virtual bool IsUsedWithHeterogeneousVolumes () const
virtual bool IsUsedWithInstancedStaticMeshes () const
virtual bool IsUsedWithLandscape () const
virtual bool IsUsedWithLidarPointCloud () const
virtual bool IsUsedWithMeshParticles () const
virtual bool IsUsedWithMorphTargets () const
virtual bool IsUsedWithNanite () const
virtual bool IsUsedWithNeuralNetworks () const
virtual bool IsUsedWithNiagaraMeshParticles () const
virtual bool IsUsedWithNiagaraRibbons () const
virtual bool IsUsedWithNiagaraSprites () const
virtual bool IsUsedWithParticleSprites () const
virtual bool IsUsedWithParticleSystem () const
virtual bool IsUsedWithSkeletalMesh () const
virtual bool IsUsedWithSplineMeshes () const
virtual bool IsUsedWithStaticLighting () const
virtual bool IsUsedWithStaticMesh () const
virtual bool IsUsedWithUI () const
virtual bool IsUsedWithVirtualHeightfieldMesh () const
virtual bool IsUsedWithVolumetricCloud () const
virtual bool IsUsedWithWater () const
virtual bool IsUsingAlphaToCoverage () const
virtual bool IsUsingHQForwardReflections () const
virtual bool IsUsingNewHLSLGenerator () const
Is the material using the new (WIP) HLSL generator?
virtual bool IsUsingPlanarForwardReflections () const
virtual bool IsUsingPreintegratedGFForSimpleIBL () const
virtual bool IsVariableRateShadingAllowed () const
virtual bool IsVolumetricPrimitive () const =0
virtual bool IsWireframe () const =0
virtual void LegacySerialize (FArchive &Ar)
Serializes the material.
uint8 MaterialGetSubstrateClosureCount_GameThread () const
Get Substrate material BSDF count.
uint8 MaterialGetSubstrateClosureCount_RenderThread () const
uint8 MaterialGetSubstrateMaterialType_GameThread () const
Get Substrate material type (single, single, complex slab).
uint8 MaterialGetSubstrateMaterialType_RenderThread () const
uint8 MaterialGetSubstrateUintPerPixel_GameThread () const
Get Substrate material uint count per pixel.
uint8 MaterialGetSubstrateUintPerPixel_RenderThread () const
bool MaterialGetSubstrateUsesComplexSpecialRenderPath_GameThread () const
Get Substrate material special path requirement (for more expenssive features such as Glints or SpecularLUT).
bool MaterialGetSubstrateUsesComplexSpecialRenderPath_RenderThread () const
bool MaterialIsLightFunctionAtlasCompatible_GameThread () const
Get whether or not the material is compatible with the light function atlas.
bool MaterialIsLightFunctionAtlasCompatible_RenderThread () const
bool MaterialMayModifyMeshPosition () const
Note: This function is only intended for use in deciding whether or not shader permutations are required before material translation occurs.
bool MaterialModifiesMeshPosition_GameThread () const
bool MaterialModifiesMeshPosition_RenderThread () const
Does the material modify the mesh position.
bool MaterialUsesAnisotropy_GameThread () const
bool MaterialUsesAnisotropy_RenderThread () const
bool MaterialUsesDisplacement_GameThread () const
bool MaterialUsesDisplacement_RenderThread () const
Does the material use displacement.
bool MaterialUsesDistanceCullFade_GameThread () const
Does the material use a distance cull fade.
bool MaterialUsesPixelDepthOffset_GameThread () const
bool MaterialUsesPixelDepthOffset_RenderThread () const
Does the material use a pixel depth offset.
bool MaterialUsesSceneDepthLookup_GameThread () const
bool MaterialUsesSceneDepthLookup_RenderThread () const
Does the material use a SceneDepth lookup.
bool MaterialUsesWorldPositionOffset_GameThread () const
bool MaterialUsesWorldPositionOffset_RenderThread () const
Does the material use world position offset.
bool NeedsGBuffer () const
bool NeedsSceneTextures () const
virtual void NotifyCompilationFinished ()
Called when compilation of an FMaterial finishes, after the GameThreadShaderMap is set and the render command to set the RenderThreadShaderMap is queued.
virtual bool PrepareDestroy_GameThread ()
Prepares to destroy the material, must be called from game thread Returns 'true' if PrepareDestroy_RenderThread() is required.
virtual void PrepareDestroy_RenderThread ()
Prepares to destroy the material, must be called from render thread, only if PrepareDestroy_GameThread() returned true.
void RegisterInlineShaderMap (bool bLoadingCooked)
Serializes the shader map inline in this material, including any shader dependencies.
uint32 Release () const
void ReleaseShaderMap ()
Releases this material's shader map.
bool RequiresSceneColorCopy_GameThread () const
bool RequiresSceneColorCopy_RenderThread () const
virtual bool RequiresSynchronousCompilation () const
void SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, struct FStableShaderKeyAndValue &SaveKeyVal)
void SerializeInlineShaderMap (FArchive &Ar, const FName &SerializingAsset=NAME_None)
Serializes the shader map inline in this material, including any shader dependencies.
void SetCompileErrors (const TArray< FString > &InCompileErrors)
void SetGameThreadShaderMap (FMaterialShaderMap *InMaterialShaderMap)
void SetInlineShaderMap (FMaterialShaderMap *InMaterialShaderMap)
void SetOwnerBeginDestroyed ()
void SetRenderingThreadShaderMap (TRefCountPtr< FMaterialShaderMap > &InMaterialShaderMap)
virtual void SetSubstrateCompilationConfig (FSubstrateCompilationConfig &SubstrateCompilationConfig)
Set the Substrate compilation config.
virtual void SetupExtraCompilationSettings (const EShaderPlatform Platform, FExtraShaderCompilerSettings &Settings) const
call during shader compilation jobs setup to fill additional settings that may be required by classes who inherit from this
virtual bool ShouldAlwaysEvaluateWorldPositionOffset () const
virtual bool ShouldApplyCloudFogging () const
virtual bool ShouldApplyFogging () const
virtual bool ShouldCache (EShaderPlatform Platform, const FShaderType *ShaderType, const FVertexFactoryType *VertexFactoryType) const
Should the shader for this material with the given platform, shader type and vertex factory type combination be compiled.
bool ShouldCachePipeline (EShaderPlatform Platform, const FShaderPipelineType *PipelineType, const FVertexFactoryType *VertexFactoryType) const
bool ShouldCacheShaders (const EShaderPlatform ShaderPlatform, const FMaterialShaderTypes &InTypes, const FVertexFactoryType *InVertexFactoryType) const
bool ShouldCastDynamicShadows () const
Returns whether this material should be considered for casting dynamic shadows.
virtual bool ShouldDisableDepthTest () const
virtual bool ShouldDoContactShadows () const
virtual bool ShouldDoSSR () const
virtual bool ShouldEnableResponsiveAA () const
virtual bool ShouldGenerateSphericalParticleNormals () const
virtual bool ShouldWriteOnlyAlpha () const
void SubmitCompileJobs_GameThread (EShaderCompileJobPriority Priority)
void SubmitCompileJobs_RenderThread (EShaderCompileJobPriority Priority) const
virtual bool SupportsMaterialCache () const
bool TryGetShaders (const FMaterialShaderTypes &InTypes, const FVertexFactoryType *InVertexFactoryType, FMaterialShaders &OutShaders) const
UE_DEPRECATED (5.5, "ShouldInlineShaderCode is no longer used when packaging shader maps. If you rely on this for some reason please reach out to the UE rendering team.") virtual bool ShouldInlineShaderCode() const
void UpdateInlineShaderMapIsComplete ()
virtual bool UseLmDirectionality () const
virtual bool UseNormalCurvatureToRoughness () const
bool UsesEyeAdaptation () const
bool UsesGlobalDistanceField_GameThread () const
bool WritesEveryPixel (bool bShadowPass, bool bVFTypeSupportsNullPixelShader) const
bool WritesEveryPixel (bool bShadowPass=false) const
Static Public Member Functions
static void AddEditorLoadedMaterialResource (FMaterial *Material)
Adds an FMaterial to the global list.
static void DeferredDelete (FMaterial *Material)
template<typename TMaterial>
static void DeferredDeleteArray (TArray< TMaterial * > &Materials)
template<typename TMaterial>
static void DeferredDeleteArray (TArray< TRefCountPtr< TMaterial > > &Materials)
static void DeleteMaterialsOnRenderThread (TArray< TRefCountPtr< FMaterial > > &MaterialsRenderThread)
static void FinishCompilation (const TCHAR *MaterialName, const TArray< FMaterial * > &MaterialsToCompile)
Blocks until compilation has completed.
static void SetShaderMapsOnMaterialResources (const TMap< TRefCountPtr< FMaterial >, TRefCountPtr< FMaterialShaderMap > > &MaterialsToUpdate)
Sets shader maps on the specified materials without blocking.
static void UpdateEditorLoadedMaterialResources (EShaderPlatform InShaderPlatform)
Recompiles any materials in the EditorLoadedMaterialResources list if they are not complete.
Data Fields
FThreadSafeCounter NumDebugRefs
FUniformParameterOverrides TransientOverrides
Protected Member Functions
void AddShaderMapIDsWithUnfinishedCompilation (TArray< int32 > &ShaderMapIds)
Fills the passed array with IDs of shader maps unfinished compilation jobs.
bool AllowPixelDepthOffset () const
virtual bool CheckInValidStateForCompilation (class FMaterialCompiler *Compiler) const
Checks that no pre-compilation errors have been detected and if so it reports them using specified compiler.
virtual int32 CompileCustomAttribute (const FGuid &AttributeID, class FMaterialCompiler *Compiler) const
Used to translate code for custom output attributes such as ClearCoatBottomNormal.
virtual int32 CompilePropertyAndSetMaterialProperty (EMaterialProperty Property, class FMaterialCompiler *Compiler, EShaderFrequency OverrideShaderFrequency=SF_NumFrequencies, bool bUsePreviousFrameTime=false) const =0
Entry point for compiling a specific material property.
virtual FString GetBaseMaterialPathName () const
Useful for debugging.
virtual FString GetDebugName () const
void GetDependentShaderAndVFTypes (EShaderPlatform Platform, const FPlatformTypeLayoutParameters &LayoutParams, TArray< FShaderType * > &OutShaderTypes, TArray< const FShaderPipelineType * > &OutShaderPipelineTypes, TArray< FVertexFactoryType * > &OutVFTypes) const
Produces arrays of any shader and vertex factory type that this material is dependent on.
uint32 GetGameThreadCompilingShaderMapId () const
bool GetLoadedCookedShaderMapId () const
virtual UMaterialExpression * GetMaterialGraphNodePreviewExpression () const
The returned value is not const because the expression is used to build the Substrate tree and this requires to execute multiple such as link function caller, compile expression, etc.
virtual FGuid GetMaterialId () const =0
Gets the Guid that represents this material.
const FMaterialShaderMap * GetShaderMapToUse () const
virtual EMaterialShaderMapUsage::Type GetShaderMapUsage () const
Gets the shader map usage of the material, which will be included in the DDC key.
void SetAllowPixelDepthOffset (bool bEnable)
void SetCompilingShaderMap (FMaterialShaderMap *InMaterialShaderMap)
void SetQualityLevelProperties (ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type InQualityLevel=EMaterialQualityLevel::Num)
Private Member Functions
bool BeginCompileShaderMap (const FMaterialShaderMapId &ShaderMapId, const FStaticParameterSet &StaticParameterSet, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode, const ITargetPlatform *TargetPlatform=nullptr)
Compiles this material for Platform, storing the result in OutShaderMap if the compile was synchronous.
void GetExpressionIncludesHash (EShaderPlatform Platform, FSHAHash &OutHash) const
void GetExternalCodeReferencesHash (FSHAHash &OutHash) const
void GetReferencedTexturesHash (EShaderPlatform Platform, FSHAHash &OutHash) const
TShaderRef< FShader > GetShader (class FMeshMaterialShaderType *ShaderType, FVertexFactoryType *VertexFactoryType, int32 PermutationId, bool bFatalIfMissing=true) const
Finds the shader matching the template type and the passed in vertex factory, asserts if not found.
bool ReleaseGameThreadCompilingShaderMap ()
void ReleaseRenderThreadCompilingShaderMap ()
void SetupMaterialEnvironment (EShaderPlatform Platform, const FShaderParametersMetadata &InUniformBufferStruct, const FUniformExpressionSet &InUniformExpressionSet, FShaderCompilerEnvironment &OutEnvironment) const
Populates OutEnvironment with defines needed to compile shaders for this material.
bool Translate (const FMaterialShaderMapId &InShaderMapId, const FStaticParameterSet &InStaticParameters, EShaderPlatform InPlatform, const ITargetPlatform *InTargetPlatform, FMaterialCompilationOutput &OutCompilationOutput, TRefCountPtr< FSharedShaderCompilerEnvironment > &OutMaterialEnvironment)
bool Translate_Legacy (const FMaterialShaderMapId &InShaderMapId, const FStaticParameterSet &InStaticParameters, EShaderPlatform InPlatform, const ITargetPlatform *InTargetPlatform, FMaterialCompilationOutput &OutCompilationOutput, TRefCountPtr< FSharedShaderCompilerEnvironment > &OutMaterialEnvironment)
bool Translate_New (const FMaterialShaderMapId &InShaderMapId, const FStaticParameterSet &InStaticParameters, EShaderPlatform InPlatform, const ITargetPlatform *InTargetPlatform, FMaterialCompilationOutput &OutCompilationOutput, TRefCountPtr< FSharedShaderCompilerEnvironment > &OutMaterialEnvironment)
Static Private Member Functions
static void GetOutputPrecision (EMaterialFloatPrecisionMode FloatPrecisionMode, bool &bFullPrecisionInPS, bool &bFullPrecisionInMaterial)
Get the float precision mode for the material and shader taking into account any project wide precision values.
Private Attributes
uint32 bAllowPixelDepthOffset: 1
uint32 bContainsInlineShaders: 1
Whether this material was loaded with shaders inlined.
std::atomic< bool > bGameThreadShaderMapIsComplete { false }
uint32 bLoadedCookedShaderMapId: 1
uint32 bOwnerBeginDestroyed: 1
Set when the owner of this FMaterial (typically a UMaterial or UMaterialInstance) has had BeginDestroy() called.
std::atomic< bool > bRenderingThreadShaderMapIsComplete { false }
uint32 bStencilDitheredLOD: 1
Whether tthis project uses stencil dither lod.
TUniqueFunction< bool()> CacheShadersCompletion
TSharedPtr< FMaterialShaderMap::FAsyncLoadContext > CacheShadersPending
TArray< FString > CompileErrors
FString DebugGroupName
TArray< TObjectPtr< UMaterialExpression > > ErrorExpressions
List of material expressions which generated a compiler error during the last compile.
ERHIFeatureLevel::Type FeatureLevel
Feature level that this material is representing.
uint32 GameThreadCompilingShaderMapId = 0
TRefCountPtr< FSharedShaderCompilerEnvironment > GameThreadPendingCompilerEnvironment
TRefCountPtr< FMaterialShaderMap > GameThreadShaderMap
Game thread tracked shader map, which is ref counted and manages shader map lifetime.
EShaderCompileJobPriority GameThreadShaderMapSubmittedPriority = EShaderCompileJobPriority::None
Used to prevent submitting the material more than once.
FGuid Id_DEPRECATED
Legacy unique identifier of this material resource.
TArray< FMaterialPSOPrecacheRequestID > PrecachedPSORequestIDs
MaterialPSO request IDs currently active for this material.
EMaterialQualityLevel::Type QualityLevel
Contains the compiling id of this shader map when it is being compiled asynchronously.
uint32 RenderingThreadCompilingShaderMapId = 0
TRefCountPtr< FSharedShaderCompilerEnvironment > RenderingThreadPendingCompilerEnvironment
TRefCountPtr< FMaterialShaderMap > RenderingThreadShaderMap
Shader map for this material resource which is accessible by the rendering thread.
std::atomic< int8 > RenderingThreadShaderMapSubmittedPriority { -1 }
Used to prevent submitting the material more than once during CacheMeshDrawCommands unless priority has been increased.
Static Private Attributes
static TSet< FMaterial * > EditorLoadedMaterialResources
Tracks FMaterials without a corresponding UMaterialInterface in the editor, for example FExpressionPreviews.
static FCriticalSection PrecachedPSORequestIDsCS
Shared critical section on PrecachedPSORequestIDs because contention should be very limited.
Friends
class FHLSLMaterialTranslator
class FMaterialHLSLErrorHandler
class FMaterialShaderMap
class FShaderCompilingManager
class UE::Cook::FODSCClientData
Detailed Description
FMaterial serves 3 intertwined purposes: Represents a material to the material compilation process, and provides hooks for extensibility (CompileProperty, etc) Represents a material to the renderer, with functions to access material properties Stores a cached shader map, and other transient output from a compile, which is necessary with async shader compiling (when a material finishes async compilation, the shader map and compile errors need to be stored somewhere)
Definition at line 1976 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterial()
FMaterial::FMaterial () inline
Minimal initialization constructor.
Definition at line 2036 of file MaterialShared.h.
References bAllowPixelDepthOffset, bContainsInlineShaders, bLoadedCookedShaderMapId, bOwnerBeginDestroyed, bStencilDitheredLOD, FeatureLevel, IConsoleManager::FindTConsoleVariableDataInt(), IConsoleManager::Get(), TConsoleVariableData< T >::GetValueOnAnyThread(), Num, QualityLevel, RenderingThreadShaderMap, and TEXT.
Referenced by AddEditorLoadedMaterialResource(), DeferredDelete(), DeferredDeleteArray(), and DeferredDeleteArray().
~FMaterial()
virtual FMaterial::~FMaterial () virtual
Destructor.
Member Function Documentation
AddEditorLoadedMaterialResource()
void FMaterial::AddEditorLoadedMaterialResource (FMaterial * Material) inline static
Adds an FMaterial to the global list.
Any FMaterials that don't belong to a UMaterialInterface need to be registered in this way to work correctly with runtime recompiling of outdated shaders.
Definition at line 2601 of file MaterialShared.h.
References FMaterial(), EditorLoadedMaterialResources, and Material.
AddRef()
uint32 FMaterial::AddRef () const
AddReferencedObjects()
virtual void FMaterial::AddReferencedObjects (FReferenceCollector & Collector) virtual
Reimplemented in FMaterialResource.
AddShaderMapIDsWithUnfinishedCompilation()
void FMaterial::AddShaderMapIDsWithUnfinishedCompilation (TArray< int32 > & ShaderMapIds) protected
Fills the passed array with IDs of shader maps unfinished compilation jobs.
AllowNegativeEmissiveColor()
virtual bool FMaterial::AllowNegativeEmissiveColor () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2233 of file MaterialShared.h.
AllowPixelDepthOffset()
bool FMaterial::AllowPixelDepthOffset () const inline protected
Definition at line 2714 of file MaterialShared.h.
References bAllowPixelDepthOffset.
AllowTranslucentLocalLightShadow()
virtual bool FMaterial::AllowTranslucentLocalLightShadow () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2267 of file MaterialShared.h.
AppendCompileStateDebugInfo()
void FMaterial::AppendCompileStateDebugInfo (FStringBuilderBase & OutDebugInfo) const
BeginAllowCachingStaticParameterValues()
virtual void FMaterial::BeginAllowCachingStaticParameterValues () inline virtual
Reimplemented in FMaterialResource.
Definition at line 2619 of file MaterialShared.h.
BeginCacheShaders() [1/2]
void FMaterial::BeginCacheShaders (const FMaterialShaderMapId & ShaderMapId, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode = EMaterialShaderPrecompileMode::Default, const ITargetPlatform * TargetPlatform = nullptr, TUniqueFunction< void(bool bSuccess)> && CompletionCallback = nullptr)
Begins caching the material shaders for the given static parameter set and platform.
This is used by material resources of UMaterialInstances.
References Default, and Platform.
BeginCacheShaders() [2/2]
void FMaterial::BeginCacheShaders (EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode = EMaterialShaderPrecompileMode::Default, const ITargetPlatform * TargetPlatform = nullptr, TUniqueFunction< void(bool bSuccess)> && CompletionCallback = nullptr)
Begins caching the material shaders for the given static parameter set and platform.
This is used by material resources of UMaterials.
References Default, and Platform.
BeginCompileShaderMap()
bool FMaterial::BeginCompileShaderMap (const FMaterialShaderMapId & ShaderMapId, const FStaticParameterSet & StaticParameterSet, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode, const ITargetPlatform * TargetPlatform = nullptr) private
Compiles this material for Platform, storing the result in OutShaderMap if the compile was synchronous.
References Platform.
CacheGivenTypes()
void FMaterial::CacheGivenTypes (EShaderPlatform ShaderPlatform, const TArray< const FVertexFactoryType * > & VFTypes, const TArray< const FShaderPipelineType * > & PipelineTypes, const TArray< const FShaderType * > & ShaderTypes)
Submits local compile jobs for the exact given shader types and vertex factory type combination.
Note
CacheShaders() should be called first to prepare the resource for compilation.
The arrays of shader types, pipeline types and vertex factory types must match.
Entries in the PipelineTypes and ShaderTypes arrays can contain null entries.
These compile jobs are submitted async and it is up to client code to block on results if needed.
References ShaderPlatform.
CacheShaders() [1/2]
bool FMaterial::CacheShaders (const FMaterialShaderMapId & ShaderMapId, EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode = EMaterialShaderPrecompileMode::Default, const ITargetPlatform * TargetPlatform = nullptr)
Caches the material shaders for the given static parameter set and platform.
This is used by material resources of UMaterialInstances.
References Default, and Platform.
CacheShaders() [2/2]
bool FMaterial::CacheShaders (EShaderPlatform Platform, EMaterialShaderPrecompileMode PrecompileMode = EMaterialShaderPrecompileMode::Default, const ITargetPlatform * TargetPlatform = nullptr)
Caches the material shaders for this material on the given platform.
This is used by material resources of UMaterials.
References Default, and Platform.
CancelCompilation()
void FMaterial::CancelCompilation ()
Cancels all outstanding compilation jobs for this material.
CastsRayTracedShadows()
virtual bool FMaterial::CastsRayTracedShadows () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2311 of file MaterialShared.h.
CheckInValidStateForCompilation()
virtual bool FMaterial::CheckInValidStateForCompilation (class FMaterialCompiler * Compiler) const inline protected virtual
Checks that no pre-compilation errors have been detected and if so it reports them using specified compiler.
Returns
whether no errors occurred.
Reimplemented in FMaterialResource.
Definition at line 2664 of file MaterialShared.h.
ClearPrecachedPSORequestIDs()
void FMaterial::ClearPrecachedPSORequestIDs ()
Clear all cached PSO data because manager has been reset.
CollectPSOs()
FGraphEventArray FMaterial::CollectPSOs (ERHIFeatureLevel::Type InFeatureLevel, const FPSOPrecacheVertexFactoryDataList & VertexFactoryDataList, const FPSOPrecacheParams & PreCacheParams, EPSOPrecachePriority Priority, TArray< FMaterialPSOPrecacheRequestID > & OutMaterialPSORequestIDs)
Collect all possible PSO's which can be used with this material for given parameters - PSOs will be async precached.
CompileCustomAttribute()
virtual int32 FMaterial::CompileCustomAttribute (const FGuid & AttributeID, class FMaterialCompiler * Compiler) const inline protected virtual
Used to translate code for custom output attributes such as ClearCoatBottomNormal.
Reimplemented in FMaterialResource.
Definition at line 2675 of file MaterialShared.h.
References INDEX_NONE.
CompilePropertyAndSetMaterialProperty()
virtual int32 FMaterial::CompilePropertyAndSetMaterialProperty (EMaterialProperty Property, class FMaterialCompiler * Compiler, EShaderFrequency OverrideShaderFrequency = SF_NumFrequencies, bool bUsePreviousFrameTime = false) const protected pure virtual
Entry point for compiling a specific material property.
This must call SetMaterialProperty.
Parameters
OverrideShaderFrequency SF_NumFrequencies to not override
Returns
cases to the proper type e.g. Compiler->ForceCast(Ret, GetValueType(Property));
Implemented in FMaterialResource.
References Property.
ComputeFogPerPixel()
virtual bool FMaterial::ComputeFogPerPixel () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2264 of file MaterialShared.h.
DeferredDelete()
void FMaterial::DeferredDelete (FMaterial * Material) static
References FMaterial(), and Material.
DeferredDeleteArray() [1/2]
template<typename TMaterial> void FMaterial::DeferredDeleteArray (TArray< TMaterial * > & Materials) inline static
Definition at line 2017 of file MaterialShared.h.
References FMaterial(), DeleteMaterialsOnRenderThread(), TArray< InElementType, InAllocatorType >::Emplace(), TArray< InElementType, InAllocatorType >::Empty(), Material, and TArray< InElementType, InAllocatorType >::Num().
DeferredDeleteArray() [2/2]
template<typename TMaterial> void FMaterial::DeferredDeleteArray (TArray< TRefCountPtr< TMaterial > > & Materials) inline static
Definition at line 1999 of file MaterialShared.h.
References FMaterial(), DeleteMaterialsOnRenderThread(), TArray< InElementType, InAllocatorType >::Emplace(), Material, MoveTemp(), and PrepareDestroy_GameThread().
DeleteMaterialsOnRenderThread()
void FMaterial::DeleteMaterialsOnRenderThread (TArray< TRefCountPtr< FMaterial > > & MaterialsRenderThread) static
Referenced by DeferredDeleteArray(), and DeferredDeleteArray().
DiscardShaderMap()
void FMaterial::DiscardShaderMap ()
Discards loaded shader maps if the application can't render.
DumpDebugInfo()
void FMaterial::DumpDebugInfo (FOutputDevice & OutputDevice)
EndAllowCachingStaticParameterValues()
virtual void FMaterial::EndAllowCachingStaticParameterValues () inline virtual
Reimplemented in FMaterialResource.
Definition at line 2620 of file MaterialShared.h.
FeedbackMaterialLayersInstancedGraphFromCompilation()
virtual void FMaterial::FeedbackMaterialLayersInstancedGraphFromCompilation (const FMaterialLayersFunctions * InLayers) inline virtual
Reimplemented in FMaterialResource.
Definition at line 2644 of file MaterialShared.h.
FinishCacheShaders()
bool FMaterial::FinishCacheShaders () const
Finishes any pending material caching.
FinishCompilation() [1/2]
void FMaterial::FinishCompilation ()
Blocks until compilation has completed.
Returns immediately if a compilation is not outstanding.
FinishCompilation() [2/2]
void FMaterial::FinishCompilation (const TCHAR * MaterialName, const TArray< FMaterial * > & MaterialsToCompile) static
Blocks until compilation has completed.
Returns immediately if a compilation is not outstanding.
GetAllowDevelopmentShaderCompile()
virtual bool FMaterial::GetAllowDevelopmentShaderCompile () const inline virtual
Returns true if this material is allowed to make development shaders via the global CVar CompileShadersForDevelopment.
Reimplemented in FMaterialResource.
Definition at line 2555 of file MaterialShared.h.
GetAssetName()
virtual FString FMaterial::GetAssetName () const inline virtual
Similar to GetFriendlyName, but but avoids historical behavior of the former, returning the exact asset name for material instances instead of just the material.
Reimplemented in FMaterialResource.
Definition at line 2272 of file MaterialShared.h.
References GetFriendlyName().
Referenced by GetUniqueAssetName().
GetAssetPath()
virtual FName FMaterial::GetAssetPath () const inline virtual
Allows to associate the shader resources with the asset for load order.
Reimplemented in FMaterialResource.
Definition at line 2610 of file MaterialShared.h.
GetBaseMaterialPathName()
virtual FString FMaterial::GetBaseMaterialPathName () const inline protected virtual
Useful for debugging.
Reimplemented in FMaterialResource.
Definition at line 2678 of file MaterialShared.h.
References TEXT.
Referenced by GetDebugName().
GetBlendableLocation()
virtual int32 FMaterial::GetBlendableLocation () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2299 of file MaterialShared.h.
GetBlendableOutputAlpha()
virtual bool FMaterial::GetBlendableOutputAlpha () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2301 of file MaterialShared.h.
GetBlendablePriority()
virtual int32 FMaterial::GetBlendablePriority () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2300 of file MaterialShared.h.
GetBlendMode()
virtual enum EBlendMode FMaterial::GetBlendMode () const pure virtual
Implemented in FMaterialResource.
Referenced by ShouldCastDynamicShadows().
GetCachedExpressionData()
const FMaterialCachedExpressionData & FMaterial::GetCachedExpressionData () const
GetCastDynamicShadowAsMasked()
virtual bool FMaterial::GetCastDynamicShadowAsMasked () const pure virtual
Implemented in FMaterialResource.
Referenced by ShouldCastDynamicShadows().
GetCompileErrors()
const TArray< FString > & FMaterial::GetCompileErrors () const inline
Definition at line 2415 of file MaterialShared.h.
References CompileErrors.
GetCustomDepthStencilUsageMask_GameThread()
uint8 FMaterial::GetCustomDepthStencilUsageMask_GameThread () const
The material usage mask of CustomDepth and CustomStencil.
GetDebugGroupName()
const FString & FMaterial::GetDebugGroupName () const inline
Definition at line 2419 of file MaterialShared.h.
References DebugGroupName.
GetDebugName()
virtual FString FMaterial::GetDebugName () const inline protected virtual
Reimplemented in FMaterialResource.
Definition at line 2679 of file MaterialShared.h.
References GetBaseMaterialPathName().
GetDependentShaderAndVFTypes()
void FMaterial::GetDependentShaderAndVFTypes (EShaderPlatform Platform, const FPlatformTypeLayoutParameters & LayoutParams, TArray< FShaderType * > & OutShaderTypes, TArray< const FShaderPipelineType * > & OutShaderPipelineTypes, TArray< FVertexFactoryType * > & OutVFTypes) const protected
Produces arrays of any shader and vertex factory type that this material is dependent on.
References Platform.
GetDisablePreExposureScale()
virtual bool FMaterial::GetDisablePreExposureScale () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2302 of file MaterialShared.h.
GetDisplacementFadeRange()
virtual FDisplacementFadeRange FMaterial::GetDisplacementFadeRange () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2253 of file MaterialShared.h.
GetDisplacementScaling()
virtual FDisplacementScaling FMaterial::GetDisplacementScaling () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2251 of file MaterialShared.h.
GetErrorExpressions()
const TArray< UMaterialExpression * > & FMaterial::GetErrorExpressions () const inline
Definition at line 2417 of file MaterialShared.h.
References ErrorExpressions, and ObjectPtrDecay().
GetExpressionIncludesHash()
void FMaterial::GetExpressionIncludesHash (EShaderPlatform Platform, FSHAHash & OutHash) const private
References Platform.
GetExternalCodeReferencesHash()
void FMaterial::GetExternalCodeReferencesHash (FSHAHash & OutHash) const private
GetFeatureLevel()
const FStaticFeatureLevel FMaterial::GetFeatureLevel () const inline
Definition at line 2422 of file MaterialShared.h.
References checkSlow, and FeatureLevel.
Referenced by FMaterialResourceMemoryWriter::EndSerializingMaterialResource().
GetForceCompatibleWithLightFunctionAtlas()
virtual bool FMaterial::GetForceCompatibleWithLightFunctionAtlas () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2221 of file MaterialShared.h.
GetForwardBlendsSkyLightCubemaps()
virtual bool FMaterial::GetForwardBlendsSkyLightCubemaps () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2227 of file MaterialShared.h.
GetFriendlyName()
virtual FString FMaterial::GetFriendlyName () const pure virtual
Implemented in FMaterialResource.
Referenced by GetAssetName().
GetFullPath()
virtual FString FMaterial::GetFullPath () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2616 of file MaterialShared.h.
References TEXT.
GetGameThreadCompilingShaderMapId()
uint32 FMaterial::GetGameThreadCompilingShaderMapId () const inline protected
Definition at line 2658 of file MaterialShared.h.
References GameThreadCompilingShaderMapId.
GetGameThreadShaderMap()
class FMaterialShaderMap * FMaterial::GetGameThreadShaderMap () const inline
Definition at line 2491 of file MaterialShared.h.
References checkSlow, FMaterialShaderMap, GameThreadShaderMap, IsInAsyncLoadingThread, IsInGameThread(), and IsInParallelGameThread().
GetLegacyId()
const FGuid & FMaterial::GetLegacyId () const inline
Definition at line 2418 of file MaterialShared.h.
References Id_DEPRECATED.
GetLoadedCookedShaderMapId()
bool FMaterial::GetLoadedCookedShaderMapId () const inline protected
Definition at line 2700 of file MaterialShared.h.
References bLoadedCookedShaderMapId.
GetMaterialDecalResponse()
virtual uint32 FMaterial::GetMaterialDecalResponse () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2284 of file MaterialShared.h.
GetMaterialDomain()
virtual EMaterialDomain FMaterial::GetMaterialDomain () const pure virtual
Implemented in FMaterialResource.
GetMaterialExpressionSource()
bool FMaterial::GetMaterialExpressionSource (FString & OutSource)
Get user source code for the material, with a list of code snippets to highlight representing the code for each MaterialExpression.
Parameters
OutSource - generated source code
OutHighlightMap - source code highlight list
Returns
- true on Success
GetMaterialFloatPrecisionMode()
virtual enum EMaterialFloatPrecisionMode FMaterial::GetMaterialFloatPrecisionMode () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2223 of file MaterialShared.h.
GetMaterialGraphNodePreviewExpression()
virtual UMaterialExpression * FMaterial::GetMaterialGraphNodePreviewExpression () const inline protected virtual
The returned value is not const because the expression is used to build the Substrate tree and this requires to execute multiple such as link function caller, compile expression, etc.
See HLSLTranslator.cpp for the single use case.
Returns
Nullptr if this is not a material used to generate a preview of a node of a material graph.
Definition at line 2710 of file MaterialShared.h.
GetMaterialId()
virtual FGuid FMaterial::GetMaterialId () const protected pure virtual
Gets the Guid that represents this material.
Implemented in FMaterialResource.
GetMaterialInterface()
virtual UMaterialInterface * FMaterial::GetMaterialInterface () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2325 of file MaterialShared.h.
GetMaterialLayers()
virtual const FMaterialLayersFunctions * FMaterial::GetMaterialLayers () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2645 of file MaterialShared.h.
GetMaterialPSOPrecacheRequestIDs()
TArray< FMaterialPSOPrecacheRequestID > FMaterial::GetMaterialPSOPrecacheRequestIDs () const
Collect all PSO request information already done for this material.
GetMaterialShaderMapUsage()
virtual EMaterialShaderMapUsage::Type FMaterial::GetMaterialShaderMapUsage () const inline virtual
Returns which shadermap this material is bound to.
Definition at line 2558 of file MaterialShared.h.
References EMaterialShaderMapUsage::Default.
GetMaterialTranslateValidationFlags()
virtual EMaterialTranslateValidationFlags FMaterial::GetMaterialTranslateValidationFlags () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2319 of file MaterialShared.h.
References None.
GetMaterialUsageDescription()
virtual FString FMaterial::GetMaterialUsageDescription () const pure virtual
Returns a string that describes the material's usage for debugging purposes.
Implemented in FMaterialResource.
GetNeuralProfileId()
virtual int32 FMaterial::GetNeuralProfileId () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2316 of file MaterialShared.h.
References INDEX_NONE.
GetNumCustomizedUVs()
virtual int32 FMaterial::GetNumCustomizedUVs () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2298 of file MaterialShared.h.
GetOpacityMaskClipValue()
virtual float FMaterial::GetOpacityMaskClipValue () const pure virtual
Implemented in FMaterialResource.
GetOutputPrecision()
void FMaterial::GetOutputPrecision (EMaterialFloatPrecisionMode FloatPrecisionMode, bool & bFullPrecisionInPS, bool & bFullPrecisionInMaterial) static private
Get the float precision mode for the material and shader taking into account any project wide precision values.
GetOwnerFName()
FName FMaterial::GetOwnerFName () const
For tracking ownership data.
GetPixelDepthOffsetMode()
virtual EPixelDepthOffsetMode FMaterial::GetPixelDepthOffsetMode () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2244 of file MaterialShared.h.
GetPreshaderGap()
virtual uint16 FMaterial::GetPreshaderGap () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2314 of file MaterialShared.h.
GetPreshaderStats()
void FMaterial::GetPreshaderStats (uint32 & TotalParameters, uint32 & TotalOps) const
Returns summary statistics for preshaders.
GetQualityLevel()
EMaterialQualityLevel::Type FMaterial::GetQualityLevel () const inline
Definition at line 2392 of file MaterialShared.h.
References QualityLevel.
Referenced by FMaterialResourceMemoryWriter::EndSerializingMaterialResource().
GetRefCount()
uint32 FMaterial::GetRefCount () const inline
Definition at line 1982 of file MaterialShared.h.
References NumDebugRefs.
GetReferencedTextureCollections()
virtual TConstArrayView< TObjectPtr< UTextureCollection > > FMaterial::GetReferencedTextureCollections () const pure virtual
Implemented in FMaterialResource.
GetReferencedTextures()
virtual TArrayView< const TObjectPtr< UObject > > FMaterial::GetReferencedTextures () const pure virtual
Implemented in FMaterialResource.
GetReferencedTexturesHash()
void FMaterial::GetReferencedTexturesHash (EShaderPlatform Platform, FSHAHash & OutHash) const private
References Platform.
GetRefractionCoverageMode()
virtual ERefractionCoverageMode FMaterial::GetRefractionCoverageMode () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2243 of file MaterialShared.h.
GetRefractionDepthBiasValue()
virtual float FMaterial::GetRefractionDepthBiasValue () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2260 of file MaterialShared.h.
GetRefractionMode()
virtual enum ERefractionMode FMaterial::GetRefractionMode () const virtual
Reimplemented in FMaterialResource.
GetRenderingThreadShaderMap()
class FMaterialShaderMap * FMaterial::GetRenderingThreadShaderMap () const
References FMaterialShaderMap.
GetRootNodeOverridesDefaultRefraction()
virtual bool FMaterial::GetRootNodeOverridesDefaultRefraction () const pure virtual
Implemented in FMaterialResource.
GetRuntimeVirtualTextureOutputAttibuteMask_GameThread()
uint8 FMaterial::GetRuntimeVirtualTextureOutputAttibuteMask_GameThread () const
Get the runtime virtual texture output attribute mask for the material.
GetRuntimeVirtualTextureOutputAttibuteMask_RenderThread()
uint8 FMaterial::GetRuntimeVirtualTextureOutputAttibuteMask_RenderThread () const
GetShader() [1/3]
TShaderRef< FShader > FMaterial::GetShader (class FMeshMaterialShaderType * ShaderType, FVertexFactoryType * VertexFactoryType, int32 PermutationId, bool bFatalIfMissing = true) const private
Finds the shader matching the template type and the passed in vertex factory, asserts if not found.
GetShader() [2/3]
template<typename ShaderType> TShaderRef< ShaderType > FMaterial::GetShader (FVertexFactoryType * VertexFactoryType, const typename ShaderType::FPermutationDomain & PermutationVector, bool bFatalIfMissing = true) const inline
Finds the shader matching the template type and the passed in vertex factory, asserts if not found.
Note - Only implemented for FMeshMaterialShaderTypes
Definition at line 2527 of file MaterialShared.h.
References GetShader().
Referenced by GetShader(), and GetShader().
GetShader() [3/3]
template<typename ShaderType> TShaderRef< ShaderType > FMaterial::GetShader (FVertexFactoryType * VertexFactoryType, int32 PermutationId = 0, bool bFatalIfMissing = true) const inline
Definition at line 2533 of file MaterialShared.h.
References TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), and GetShader().
GetShaderMapId()
virtual void FMaterial::GetShaderMapId (EShaderPlatform Platform, const ITargetPlatform * TargetPlatform, FMaterialShaderMapId & OutId) const virtual
Reimplemented in FMaterialResource.
References Platform.
GetShaderMapToUse()
const FMaterialShaderMap * FMaterial::GetShaderMapToUse () const protected
References FMaterialShaderMap.
GetShaderMapUsage()
virtual EMaterialShaderMapUsage::Type FMaterial::GetShaderMapUsage () const inline protected virtual
Gets the shader map usage of the material, which will be included in the DDC key.
This mechanism allows derived material classes to create different DDC keys with the same base material. For example lightmass exports diffuse and emissive, each of which requires a material resource with the same base material.
Definition at line 2692 of file MaterialShared.h.
References EMaterialShaderMapUsage::Default.
GetShaderPipeline()
FShaderPipelineRef FMaterial::GetShaderPipeline (class FShaderPipelineType * ShaderPipelineType, FVertexFactoryType * VertexFactoryType, bool bFatalIfNotFound = true) const
GetShaderTags()
virtual void FMaterial::GetShaderTags (TArray< FName > & OutShaderTags) const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2318 of file MaterialShared.h.
GetShaderTypes()
void FMaterial::GetShaderTypes (EShaderPlatform Platform, const FPlatformTypeLayoutParameters & LayoutParams, TArray< FDebugShaderTypeInfo > & OutShaderInfo) const
Gathers a list of shader types sorted by vertex factory types that should be cached for this material.
Avoids doing expensive material and shader compilation to acquire this information.
Parameters
Platform The shader platform to get info for.
OutShaderInfo Array of results sorted by vertex factory type, and shader type.
References Platform.
GetShaderTypesForLayout()
void FMaterial::GetShaderTypesForLayout (EShaderPlatform Platform, const FShaderMapLayout & Layout, FVertexFactoryType * VertexFactory, TArray< FDebugShaderTypeInfo > & OutShaderInfo) const
References Layout, Platform, and VertexFactory.
GetShadingModels()
virtual FMaterialShadingModelField FMaterial::GetShadingModels () const pure virtual
Implemented in FMaterialResource.
Referenced by ShouldCastDynamicShadows().
GetShadingRate()
virtual EMaterialShadingRate FMaterial::GetShadingRate () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2315 of file MaterialShared.h.
GetStencilCompare()
virtual uint32 FMaterial::GetStencilCompare () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2305 of file MaterialShared.h.
GetStencilRefValue()
virtual uint32 FMaterial::GetStencilRefValue () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2304 of file MaterialShared.h.
GetSubstrateCompilationConfig()
virtual const FSubstrateCompilationConfig & FMaterial::GetSubstrateCompilationConfig () const virtual
Get to the Substrate compilation config.
GetTranslucencyDirectionalLightingIntensity()
virtual float FMaterial::GetTranslucencyDirectionalLightingIntensity () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2245 of file MaterialShared.h.
GetTranslucencyLightingMode()
virtual enum ETranslucencyLightingMode FMaterial::GetTranslucencyLightingMode () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2239 of file MaterialShared.h.
GetTranslucentBackscatteringExponent()
virtual float FMaterial::GetTranslucentBackscatteringExponent () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2250 of file MaterialShared.h.
GetTranslucentDirectionalLightShadowQuality()
virtual float FMaterial::GetTranslucentDirectionalLightShadowQuality () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2269 of file MaterialShared.h.
GetTranslucentLocalLightShadowQuality()
virtual float FMaterial::GetTranslucentLocalLightShadowQuality () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2268 of file MaterialShared.h.
GetTranslucentMultipleScatteringExtinction()
virtual FLinearColor FMaterial::GetTranslucentMultipleScatteringExtinction () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2258 of file MaterialShared.h.
References FLinearColor::White.
GetTranslucentSelfShadowDensityScale()
virtual float FMaterial::GetTranslucentSelfShadowDensityScale () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2247 of file MaterialShared.h.
GetTranslucentSelfShadowSecondDensityScale()
virtual float FMaterial::GetTranslucentSelfShadowSecondDensityScale () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2248 of file MaterialShared.h.
GetTranslucentSelfShadowSecondOpacity()
virtual float FMaterial::GetTranslucentSelfShadowSecondOpacity () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2249 of file MaterialShared.h.
GetTranslucentShadowDensityScale()
virtual float FMaterial::GetTranslucentShadowDensityScale () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2246 of file MaterialShared.h.
GetTranslucentShadowStartOffset()
virtual float FMaterial::GetTranslucentShadowStartOffset () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2259 of file MaterialShared.h.
GetUniform2DArrayTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniform2DArrayTextureExpressions () const inline
Definition at line 2409 of file MaterialShared.h.
References Array2D, and GetUniformTextureExpressions().
GetUniform2DTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniform2DTextureExpressions () const inline
Definition at line 2407 of file MaterialShared.h.
References GetUniformTextureExpressions(), and Standard2D.
GetUniformCubeTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniformCubeTextureExpressions () const inline
Definition at line 2408 of file MaterialShared.h.
References Cube, and GetUniformTextureExpressions().
GetUniformExpressions()
const FUniformExpressionSet & FMaterial::GetUniformExpressions () const
GetUniformNumericParameterExpressions()
TArrayView< const FMaterialNumericParameterInfo > FMaterial::GetUniformNumericParameterExpressions () const
GetUniformSparseVolumeTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniformSparseVolumeTextureExpressions () const inline
Definition at line 2412 of file MaterialShared.h.
References GetUniformTextureExpressions(), and SparseVolume.
GetUniformTextureCollectionExpressions()
TConstArrayView< FMaterialTextureCollectionParameterInfo > FMaterial::GetUniformTextureCollectionExpressions () const
GetUniformTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniformTextureExpressions (EMaterialTextureParameterType Type) const
Referenced by GetUniform2DArrayTextureExpressions(), GetUniform2DTextureExpressions(), GetUniformCubeTextureExpressions(), GetUniformSparseVolumeTextureExpressions(), GetUniformVirtualTextureExpressions(), and GetUniformVolumeTextureExpressions().
GetUniformVirtualTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniformVirtualTextureExpressions () const inline
Definition at line 2411 of file MaterialShared.h.
References GetUniformTextureExpressions(), and Virtual.
GetUniformVolumeTextureExpressions()
TArrayView< const FMaterialTextureParameterInfo > FMaterial::GetUniformVolumeTextureExpressions () const inline
Definition at line 2410 of file MaterialShared.h.
References GetUniformTextureExpressions(), and Volume.
GetUniqueAssetName()
FString FMaterial::GetUniqueAssetName (EShaderPlatform Platform, const FMaterialShaderMapId & ShaderMapId) const
Similar to GetFriendlyName, but appends a hash of shader map ID portion of the DDC key (excluding source file hashes) to differentiate materials/material instances that would collide when considering the base material name alone (this name is used when creating debug output paths for disambiguation).
References GetAssetName(), GetUniqueAssetName(), and Platform.
Referenced by GetUniqueAssetName().
GetUsesDynamicParameter()
bool FMaterial::GetUsesDynamicParameter () const inline
Definition at line 2423 of file MaterialShared.h.
HasAmbientOcclusionConnected()
virtual bool FMaterial::HasAmbientOcclusionConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2292 of file MaterialShared.h.
HasAnisotropyConnected()
virtual bool FMaterial::HasAnisotropyConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2291 of file MaterialShared.h.
HasBaseColorConnected()
virtual bool FMaterial::HasBaseColorConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2285 of file MaterialShared.h.
HasDisplacementConnected()
virtual bool FMaterial::HasDisplacementConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2294 of file MaterialShared.h.
HasEmissiveColorConnected()
virtual bool FMaterial::HasEmissiveColorConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2290 of file MaterialShared.h.
HasFirstPersonOutput()
virtual bool FMaterial::HasFirstPersonOutput () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2310 of file MaterialShared.h.
HasMaterialPropertyConnected()
virtual bool FMaterial::HasMaterialPropertyConnected (EMaterialProperty In) const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2293 of file MaterialShared.h.
HasMetallicConnected()
virtual bool FMaterial::HasMetallicConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2289 of file MaterialShared.h.
HasNormalConnected()
virtual bool FMaterial::HasNormalConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2286 of file MaterialShared.h.
HasPerInstanceCustomData()
virtual bool FMaterial::HasPerInstanceCustomData () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2306 of file MaterialShared.h.
HasPerInstanceRandom()
virtual bool FMaterial::HasPerInstanceRandom () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2307 of file MaterialShared.h.
HasPixelAnimation()
virtual bool FMaterial::HasPixelAnimation () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2184 of file MaterialShared.h.
HasPixelDepthOffsetConnected()
virtual bool FMaterial::HasPixelDepthOffsetConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2283 of file MaterialShared.h.
HasRenderTracePhysicalMaterialOutputs()
virtual bool FMaterial::HasRenderTracePhysicalMaterialOutputs () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2313 of file MaterialShared.h.
HasRoughnessConnected()
virtual bool FMaterial::HasRoughnessConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2287 of file MaterialShared.h.
HasRuntimeVirtualTextureOutput()
virtual bool FMaterial::HasRuntimeVirtualTextureOutput () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2309 of file MaterialShared.h.
HasShaders()
bool FMaterial::HasShaders (const FMaterialShaderTypes & InTypes, const FVertexFactoryType * InVertexFactoryType) const
HasSpecularConnected()
virtual bool FMaterial::HasSpecularConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2288 of file MaterialShared.h.
HasSubstrateRoughnessTracking()
virtual bool FMaterial::HasSubstrateRoughnessTracking () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2266 of file MaterialShared.h.
HasValidGameThreadShaderMap()
bool FMaterial::HasValidGameThreadShaderMap () const
Checks if there is a valid GameThreadShaderMap, that is, the material can be rendered as intended.
Returns
returns true if there is a GameThreadShaderMap.
HasVertexInterpolator()
virtual bool FMaterial::HasVertexInterpolator () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2308 of file MaterialShared.h.
HasVertexPositionOffsetConnected()
virtual bool FMaterial::HasVertexPositionOffsetConnected () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2282 of file MaterialShared.h.
IsCachingShaders()
bool FMaterial::IsCachingShaders () const
Returns whether or not a material caching is still pending.
IsCompilationFinished()
bool FMaterial::IsCompilationFinished () const
Checks if the compilation for this shader is finished.
Returns
returns true if compilation is complete false otherwise
IsDefaultMaterial()
virtual bool FMaterial::IsDefaultMaterial () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2297 of file MaterialShared.h.
IsDeferredDecal()
virtual bool FMaterial::IsDeferredDecal () const pure virtual
Implemented in FMaterialResource.
IsDisplacementFadeEnabled()
virtual bool FMaterial::IsDisplacementFadeEnabled () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2252 of file MaterialShared.h.
IsDistorted()
virtual bool FMaterial::IsDistorted () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2242 of file MaterialShared.h.
IsDitheredLODTransition()
virtual bool FMaterial::IsDitheredLODTransition () const pure virtual
Implemented in FMaterialResource.
IsDitherMasked()
virtual bool FMaterial::IsDitherMasked () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2232 of file MaterialShared.h.
IsDualBlendingEnabled()
virtual bool FMaterial::IsDualBlendingEnabled (EShaderPlatform Platform) const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2256 of file MaterialShared.h.
References Platform.
IsFullyRough()
virtual bool FMaterial::IsFullyRough () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2220 of file MaterialShared.h.
IsGameThreadShaderMapComplete()
bool FMaterial::IsGameThreadShaderMapComplete () const inline
Definition at line 2503 of file MaterialShared.h.
References bGameThreadShaderMapIsComplete, checkSlow, IsInGameThread(), and IsInParallelGameThread().
IsLightFunction()
virtual bool FMaterial::IsLightFunction () const pure virtual
Implemented in FMaterialResource.
IsMasked()
virtual bool FMaterial::IsMasked () const pure virtual
Implemented in FMaterialResource.
IsMobileSeparateTranslucencyEnabled()
virtual bool FMaterial::IsMobileSeparateTranslucencyEnabled () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2257 of file MaterialShared.h.
IsNonmetal()
virtual bool FMaterial::IsNonmetal () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2229 of file MaterialShared.h.
IsOwnerBeginDestroyed()
bool FMaterial::IsOwnerBeginDestroyed () const inline
Definition at line 2625 of file MaterialShared.h.
References bOwnerBeginDestroyed.
IsPersistent()
virtual bool FMaterial::IsPersistent () const pure virtual
Should shaders compiled for this material be saved to disk?
Implemented in FMaterialResource.
IsPostProcessMaterial()
virtual bool FMaterial::IsPostProcessMaterial () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2191 of file MaterialShared.h.
IsPreview()
virtual bool FMaterial::IsPreview () const inline virtual
Definition at line 2329 of file MaterialShared.h.
IsRenderingThreadShaderMapComplete()
bool FMaterial::IsRenderingThreadShaderMapComplete () const inline
Definition at line 2509 of file MaterialShared.h.
References bRenderingThreadShaderMapIsComplete, checkSlow, and IsInParallelRenderingThread().
IsRequiredComplete()
bool FMaterial::IsRequiredComplete () const
Is the material required to be complete?
Default materials, special engine materials, etc
IsShadingModelFromMaterialExpression()
virtual bool FMaterial::IsShadingModelFromMaterialExpression () const pure virtual
Implemented in FMaterialResource.
IsSky()
virtual bool FMaterial::IsSky () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2265 of file MaterialShared.h.
IsSpecialEngineMaterial()
virtual bool FMaterial::IsSpecialEngineMaterial () const pure virtual
Implemented in FMaterialResource.
IsStencilTestEnabled()
virtual bool FMaterial::IsStencilTestEnabled () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2303 of file MaterialShared.h.
IsSubstrateMaterial()
virtual bool FMaterial::IsSubstrateMaterial () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2295 of file MaterialShared.h.
IsTangentSpaceNormal()
virtual bool FMaterial::IsTangentSpaceNormal () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2177 of file MaterialShared.h.
IsTessellationEnabled()
virtual bool FMaterial::IsTessellationEnabled () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2312 of file MaterialShared.h.
IsThinSurface()
virtual bool FMaterial::IsThinSurface () const pure virtual
Implemented in FMaterialResource.
IsTranslucencyAfterDOFEnabled()
virtual bool FMaterial::IsTranslucencyAfterDOFEnabled () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2254 of file MaterialShared.h.
IsTranslucencyAfterMotionBlurEnabled()
virtual bool FMaterial::IsTranslucencyAfterMotionBlurEnabled () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2255 of file MaterialShared.h.
IsTranslucencyVelocityFromDepth()
virtual bool FMaterial::IsTranslucencyVelocityFromDepth () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2175 of file MaterialShared.h.
IsTranslucencyWritingCustomDepth()
virtual bool FMaterial::IsTranslucencyWritingCustomDepth () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2173 of file MaterialShared.h.
IsTranslucencyWritingFrontLayerTransparency()
virtual bool FMaterial::IsTranslucencyWritingFrontLayerTransparency () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2176 of file MaterialShared.h.
IsTranslucencyWritingVelocity()
virtual bool FMaterial::IsTranslucencyWritingVelocity () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2174 of file MaterialShared.h.
IsTwoSided()
virtual bool FMaterial::IsTwoSided () const pure virtual
Implemented in FMaterialResource.
IsUIMaterial()
virtual bool FMaterial::IsUIMaterial () const pure virtual
Implemented in FMaterialResource.
IsUsedWithAPEXCloth()
virtual bool FMaterial::IsUsedWithAPEXCloth () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2207 of file MaterialShared.h.
IsUsedWithBeamTrails()
virtual bool FMaterial::IsUsedWithBeamTrails () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2197 of file MaterialShared.h.
IsUsedWithEditorCompositing()
virtual bool FMaterial::IsUsedWithEditorCompositing () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2186 of file MaterialShared.h.
IsUsedWithGeometryCache()
virtual bool FMaterial::IsUsedWithGeometryCache () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2213 of file MaterialShared.h.
IsUsedWithGeometryCollections()
virtual bool FMaterial::IsUsedWithGeometryCollections () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2206 of file MaterialShared.h.
IsUsedWithHairStrands()
virtual bool FMaterial::IsUsedWithHairStrands () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2215 of file MaterialShared.h.
IsUsedWithHeterogeneousVolumes()
virtual bool FMaterial::IsUsedWithHeterogeneousVolumes () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2210 of file MaterialShared.h.
IsUsedWithInstancedStaticMeshes()
virtual bool FMaterial::IsUsedWithInstancedStaticMeshes () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2205 of file MaterialShared.h.
IsUsedWithLandscape()
virtual bool FMaterial::IsUsedWithLandscape () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2194 of file MaterialShared.h.
IsUsedWithLidarPointCloud()
virtual bool FMaterial::IsUsedWithLidarPointCloud () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2216 of file MaterialShared.h.
IsUsedWithMeshParticles()
virtual bool FMaterial::IsUsedWithMeshParticles () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2198 of file MaterialShared.h.
IsUsedWithMorphTargets()
virtual bool FMaterial::IsUsedWithMorphTargets () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2203 of file MaterialShared.h.
IsUsedWithNanite()
virtual bool FMaterial::IsUsedWithNanite () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2208 of file MaterialShared.h.
IsUsedWithNeuralNetworks()
virtual bool FMaterial::IsUsedWithNeuralNetworks () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2218 of file MaterialShared.h.
IsUsedWithNiagaraMeshParticles()
virtual bool FMaterial::IsUsedWithNiagaraMeshParticles () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2201 of file MaterialShared.h.
IsUsedWithNiagaraRibbons()
virtual bool FMaterial::IsUsedWithNiagaraRibbons () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2200 of file MaterialShared.h.
IsUsedWithNiagaraSprites()
virtual bool FMaterial::IsUsedWithNiagaraSprites () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2199 of file MaterialShared.h.
IsUsedWithParticleSprites()
virtual bool FMaterial::IsUsedWithParticleSprites () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2196 of file MaterialShared.h.
IsUsedWithParticleSystem()
virtual bool FMaterial::IsUsedWithParticleSystem () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2195 of file MaterialShared.h.
IsUsedWithSkeletalMesh()
virtual bool FMaterial::IsUsedWithSkeletalMesh () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2193 of file MaterialShared.h.
IsUsedWithSplineMeshes()
virtual bool FMaterial::IsUsedWithSplineMeshes () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2204 of file MaterialShared.h.
IsUsedWithStaticLighting()
virtual bool FMaterial::IsUsedWithStaticLighting () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2202 of file MaterialShared.h.
IsUsedWithStaticMesh()
virtual bool FMaterial::IsUsedWithStaticMesh () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2219 of file MaterialShared.h.
IsUsedWithUI()
virtual bool FMaterial::IsUsedWithUI () const inline virtual
Definition at line 2212 of file MaterialShared.h.
IsUsedWithVirtualHeightfieldMesh()
virtual bool FMaterial::IsUsedWithVirtualHeightfieldMesh () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2217 of file MaterialShared.h.
IsUsedWithVolumetricCloud()
virtual bool FMaterial::IsUsedWithVolumetricCloud () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2209 of file MaterialShared.h.
IsUsedWithWater()
virtual bool FMaterial::IsUsedWithWater () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2214 of file MaterialShared.h.
IsUsingAlphaToCoverage()
virtual bool FMaterial::IsUsingAlphaToCoverage () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2224 of file MaterialShared.h.
IsUsingHQForwardReflections()
virtual bool FMaterial::IsUsingHQForwardReflections () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2226 of file MaterialShared.h.
IsUsingNewHLSLGenerator()
virtual bool FMaterial::IsUsingNewHLSLGenerator () const virtual
Is the material using the new (WIP) HLSL generator?
Reimplemented in FMaterialResource.
IsUsingPlanarForwardReflections()
virtual bool FMaterial::IsUsingPlanarForwardReflections () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2228 of file MaterialShared.h.
IsUsingPreintegratedGFForSimpleIBL()
virtual bool FMaterial::IsUsingPreintegratedGFForSimpleIBL () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2225 of file MaterialShared.h.
IsVariableRateShadingAllowed()
virtual bool FMaterial::IsVariableRateShadingAllowed () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2317 of file MaterialShared.h.
IsVolumetricPrimitive()
virtual bool FMaterial::IsVolumetricPrimitive () const pure virtual
Implemented in FMaterialResource.
IsWireframe()
virtual bool FMaterial::IsWireframe () const pure virtual
Implemented in FMaterialResource.
LegacySerialize()
virtual void FMaterial::LegacySerialize (FArchive & Ar) virtual
Serializes the material.
Reimplemented in FMaterialResource.
References Ar.
MaterialGetSubstrateClosureCount_GameThread()
uint8 FMaterial::MaterialGetSubstrateClosureCount_GameThread () const
Get Substrate material BSDF count.
MaterialGetSubstrateClosureCount_RenderThread()
uint8 FMaterial::MaterialGetSubstrateClosureCount_RenderThread () const
MaterialGetSubstrateMaterialType_GameThread()
uint8 FMaterial::MaterialGetSubstrateMaterialType_GameThread () const
Get Substrate material type (single, single, complex slab).
MaterialGetSubstrateMaterialType_RenderThread()
uint8 FMaterial::MaterialGetSubstrateMaterialType_RenderThread () const
MaterialGetSubstrateUintPerPixel_GameThread()
uint8 FMaterial::MaterialGetSubstrateUintPerPixel_GameThread () const
Get Substrate material uint count per pixel.
MaterialGetSubstrateUintPerPixel_RenderThread()
uint8 FMaterial::MaterialGetSubstrateUintPerPixel_RenderThread () const
MaterialGetSubstrateUsesComplexSpecialRenderPath_GameThread()
bool FMaterial::MaterialGetSubstrateUsesComplexSpecialRenderPath_GameThread () const
Get Substrate material special path requirement (for more expenssive features such as Glints or SpecularLUT).
MaterialGetSubstrateUsesComplexSpecialRenderPath_RenderThread()
bool FMaterial::MaterialGetSubstrateUsesComplexSpecialRenderPath_RenderThread () const
MaterialIsLightFunctionAtlasCompatible_GameThread()
bool FMaterial::MaterialIsLightFunctionAtlasCompatible_GameThread () const
Get whether or not the material is compatible with the light function atlas.
MaterialIsLightFunctionAtlasCompatible_RenderThread()
bool FMaterial::MaterialIsLightFunctionAtlasCompatible_RenderThread () const
MaterialMayModifyMeshPosition()
bool FMaterial::MaterialMayModifyMeshPosition () const
Note: This function is only intended for use in deciding whether or not shader permutations are required before material translation occurs.
MaterialModifiesMeshPosition_GameThread()
bool FMaterial::MaterialModifiesMeshPosition_GameThread () const
MaterialModifiesMeshPosition_RenderThread()
bool FMaterial::MaterialModifiesMeshPosition_RenderThread () const
Does the material modify the mesh position.
MaterialUsesAnisotropy_GameThread()
bool FMaterial::MaterialUsesAnisotropy_GameThread () const
MaterialUsesAnisotropy_RenderThread()
bool FMaterial::MaterialUsesAnisotropy_RenderThread () const
MaterialUsesDisplacement_GameThread()
bool FMaterial::MaterialUsesDisplacement_GameThread () const
MaterialUsesDisplacement_RenderThread()
bool FMaterial::MaterialUsesDisplacement_RenderThread () const
Does the material use displacement.
MaterialUsesDistanceCullFade_GameThread()
bool FMaterial::MaterialUsesDistanceCullFade_GameThread () const
Does the material use a distance cull fade.
MaterialUsesPixelDepthOffset_GameThread()
bool FMaterial::MaterialUsesPixelDepthOffset_GameThread () const
MaterialUsesPixelDepthOffset_RenderThread()
bool FMaterial::MaterialUsesPixelDepthOffset_RenderThread () const
Does the material use a pixel depth offset.
MaterialUsesSceneDepthLookup_GameThread()
bool FMaterial::MaterialUsesSceneDepthLookup_GameThread () const
MaterialUsesSceneDepthLookup_RenderThread()
bool FMaterial::MaterialUsesSceneDepthLookup_RenderThread () const
Does the material use a SceneDepth lookup.
MaterialUsesWorldPositionOffset_GameThread()
bool FMaterial::MaterialUsesWorldPositionOffset_GameThread () const
MaterialUsesWorldPositionOffset_RenderThread()
bool FMaterial::MaterialUsesWorldPositionOffset_RenderThread () const
Does the material use world position offset.
NeedsGBuffer()
bool FMaterial::NeedsGBuffer () const
NeedsSceneTextures()
bool FMaterial::NeedsSceneTextures () const
NotifyCompilationFinished()
virtual void FMaterial::NotifyCompilationFinished () inline virtual
Called when compilation of an FMaterial finishes, after the GameThreadShaderMap is set and the render command to set the RenderThreadShaderMap is queued.
Reimplemented in FMaterialResource.
Definition at line 2340 of file MaterialShared.h.
PrepareDestroy_GameThread()
virtual bool FMaterial::PrepareDestroy_GameThread () virtual
Prepares to destroy the material, must be called from game thread Returns 'true' if PrepareDestroy_RenderThread() is required.
Referenced by DeferredDeleteArray().
PrepareDestroy_RenderThread()
virtual void FMaterial::PrepareDestroy_RenderThread () virtual
Prepares to destroy the material, must be called from render thread, only if PrepareDestroy_GameThread() returned true.
RegisterInlineShaderMap()
void FMaterial::RegisterInlineShaderMap (bool bLoadingCooked)
Serializes the shader map inline in this material, including any shader dependencies.
Release()
uint32 FMaterial::Release () const
ReleaseGameThreadCompilingShaderMap()
bool FMaterial::ReleaseGameThreadCompilingShaderMap () private
ReleaseRenderThreadCompilingShaderMap()
void FMaterial::ReleaseRenderThreadCompilingShaderMap () private
ReleaseShaderMap()
void FMaterial::ReleaseShaderMap ()
Releases this material's shader map.
Must only be called on materials not exposed to the rendering thread!
RequiresSceneColorCopy_GameThread()
bool FMaterial::RequiresSceneColorCopy_GameThread () const
RequiresSceneColorCopy_RenderThread()
bool FMaterial::RequiresSceneColorCopy_RenderThread () const
RequiresSynchronousCompilation()
virtual bool FMaterial::RequiresSynchronousCompilation () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2296 of file MaterialShared.h.
SaveShaderStableKeys()
void FMaterial::SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, struct FStableShaderKeyAndValue & SaveKeyVal)
SerializeInlineShaderMap()
void FMaterial::SerializeInlineShaderMap (FArchive & Ar, const FName & SerializingAsset = NAME_None)
Serializes the shader map inline in this material, including any shader dependencies.
References Ar.
SetAllowPixelDepthOffset()
void FMaterial::SetAllowPixelDepthOffset (bool bEnable) inline protected
Definition at line 2713 of file MaterialShared.h.
References bAllowPixelDepthOffset.
SetCompileErrors()
void FMaterial::SetCompileErrors (const TArray< FString > & InCompileErrors) inline
Definition at line 2416 of file MaterialShared.h.
References CompileErrors.
SetCompilingShaderMap()
void FMaterial::SetCompilingShaderMap (FMaterialShaderMap * InMaterialShaderMap) protected
References FMaterialShaderMap.
SetGameThreadShaderMap()
void FMaterial::SetGameThreadShaderMap (FMaterialShaderMap * InMaterialShaderMap)
References FMaterialShaderMap.
SetInlineShaderMap()
void FMaterial::SetInlineShaderMap (FMaterialShaderMap * InMaterialShaderMap)
References FMaterialShaderMap.
SetOwnerBeginDestroyed()
void FMaterial::SetOwnerBeginDestroyed () inline
Definition at line 2624 of file MaterialShared.h.
References bOwnerBeginDestroyed.
SetQualityLevelProperties()
void FMaterial::SetQualityLevelProperties (ERHIFeatureLevel::Type InFeatureLevel, EMaterialQualityLevel::Type InQualityLevel = EMaterialQualityLevel::Num) inline protected
Definition at line 2681 of file MaterialShared.h.
References FeatureLevel, EMaterialQualityLevel::Num, and QualityLevel.
Referenced by FMaterialResource::SetMaterial().
SetRenderingThreadShaderMap()
void FMaterial::SetRenderingThreadShaderMap (TRefCountPtr< FMaterialShaderMap > & InMaterialShaderMap)
SetShaderMapsOnMaterialResources()
void FMaterial::SetShaderMapsOnMaterialResources (const TMap< TRefCountPtr< FMaterial >, TRefCountPtr< FMaterialShaderMap > > & MaterialsToUpdate) static
Sets shader maps on the specified materials without blocking.
SetSubstrateCompilationConfig()
virtual void FMaterial::SetSubstrateCompilationConfig (FSubstrateCompilationConfig & SubstrateCompilationConfig) virtual
Set the Substrate compilation config.
SetupExtraCompilationSettings()
virtual void FMaterial::SetupExtraCompilationSettings (const EShaderPlatform Platform, FExtraShaderCompilerSettings & Settings) const inline virtual
call during shader compilation jobs setup to fill additional settings that may be required by classes who inherit from this
Definition at line 2576 of file MaterialShared.h.
References Platform.
SetupMaterialEnvironment()
void FMaterial::SetupMaterialEnvironment (EShaderPlatform Platform, const FShaderParametersMetadata & InUniformBufferStruct, const FUniformExpressionSet & InUniformExpressionSet, FShaderCompilerEnvironment & OutEnvironment) const private
Populates OutEnvironment with defines needed to compile shaders for this material.
References Platform.
ShouldAlwaysEvaluateWorldPositionOffset()
virtual bool FMaterial::ShouldAlwaysEvaluateWorldPositionOffset () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2263 of file MaterialShared.h.
ShouldApplyCloudFogging()
virtual bool FMaterial::ShouldApplyCloudFogging () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2262 of file MaterialShared.h.
ShouldApplyFogging()
virtual bool FMaterial::ShouldApplyFogging () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2261 of file MaterialShared.h.
ShouldCache()
virtual bool FMaterial::ShouldCache (EShaderPlatform Platform, const FShaderType * ShaderType, const FVertexFactoryType * VertexFactoryType) const virtual
Should the shader for this material with the given platform, shader type and vertex factory type combination be compiled.
Parameters
Platform The platform currently being compiled for
ShaderType Which shader is being compiled
VertexFactory Which vertex factory is being compiled (can be NULL)
Returns
true if the shader should be compiled
References Platform.
ShouldCachePipeline()
bool FMaterial::ShouldCachePipeline (EShaderPlatform Platform, const FShaderPipelineType * PipelineType, const FVertexFactoryType * VertexFactoryType) const
References Platform.
ShouldCacheShaders()
bool FMaterial::ShouldCacheShaders (const EShaderPlatform ShaderPlatform, const FMaterialShaderTypes & InTypes, const FVertexFactoryType * InVertexFactoryType) const
References ShaderPlatform.
ShouldCastDynamicShadows()
bool FMaterial::ShouldCastDynamicShadows () const inline
Returns whether this material should be considered for casting dynamic shadows.
Definition at line 2382 of file MaterialShared.h.
References GetBlendMode(), GetCastDynamicShadowAsMasked(), GetShadingModels(), IsMaskedBlendMode(), IsOpaqueBlendMode(), and IsTranslucentOnlyBlendMode().
ShouldDisableDepthTest()
virtual bool FMaterial::ShouldDisableDepthTest () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2179 of file MaterialShared.h.
ShouldDoContactShadows()
virtual bool FMaterial::ShouldDoContactShadows () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2183 of file MaterialShared.h.
ShouldDoSSR()
virtual bool FMaterial::ShouldDoSSR () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2182 of file MaterialShared.h.
ShouldEnableResponsiveAA()
virtual bool FMaterial::ShouldEnableResponsiveAA () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2181 of file MaterialShared.h.
ShouldGenerateSphericalParticleNormals()
virtual bool FMaterial::ShouldGenerateSphericalParticleNormals () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2178 of file MaterialShared.h.
ShouldWriteOnlyAlpha()
virtual bool FMaterial::ShouldWriteOnlyAlpha () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2180 of file MaterialShared.h.
SubmitCompileJobs_GameThread()
void FMaterial::SubmitCompileJobs_GameThread (EShaderCompileJobPriority Priority)
SubmitCompileJobs_RenderThread()
void FMaterial::SubmitCompileJobs_RenderThread (EShaderCompileJobPriority Priority) const
SupportsMaterialCache()
virtual bool FMaterial::SupportsMaterialCache () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2211 of file MaterialShared.h.
Translate()
bool FMaterial::Translate (const FMaterialShaderMapId & InShaderMapId, const FStaticParameterSet & InStaticParameters, EShaderPlatform InPlatform, const ITargetPlatform * InTargetPlatform, FMaterialCompilationOutput & OutCompilationOutput, TRefCountPtr< FSharedShaderCompilerEnvironment > & OutMaterialEnvironment) private
Translate_Legacy()
bool FMaterial::Translate_Legacy (const FMaterialShaderMapId & InShaderMapId, const FStaticParameterSet & InStaticParameters, EShaderPlatform InPlatform, const ITargetPlatform * InTargetPlatform, FMaterialCompilationOutput & OutCompilationOutput, TRefCountPtr< FSharedShaderCompilerEnvironment > & OutMaterialEnvironment) private
Translate_New()
bool FMaterial::Translate_New (const FMaterialShaderMapId & InShaderMapId, const FStaticParameterSet & InStaticParameters, EShaderPlatform InPlatform, const ITargetPlatform * InTargetPlatform, FMaterialCompilationOutput & OutCompilationOutput, TRefCountPtr< FSharedShaderCompilerEnvironment > & OutMaterialEnvironment) private
TryGetShaders()
bool FMaterial::TryGetShaders (const FMaterialShaderTypes & InTypes, const FVertexFactoryType * InVertexFactoryType, FMaterialShaders & OutShaders) const
UE_DEPRECATED()
FMaterial::UE_DEPRECATED (5. 5, "ShouldInlineShaderCode is no longer used when packaging shader maps. If you rely on this for some reason please reach out to the UE rendering team.") const inline
Definition at line 2612 of file MaterialShared.h.
UpdateEditorLoadedMaterialResources()
void FMaterial::UpdateEditorLoadedMaterialResources (EShaderPlatform InShaderPlatform) static
Recompiles any materials in the EditorLoadedMaterialResources list if they are not complete.
UpdateInlineShaderMapIsComplete()
void FMaterial::UpdateInlineShaderMapIsComplete ()
UseLmDirectionality()
virtual bool FMaterial::UseLmDirectionality () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2230 of file MaterialShared.h.
UseNormalCurvatureToRoughness()
virtual bool FMaterial::UseNormalCurvatureToRoughness () const inline virtual
Reimplemented in FMaterialResource.
Definition at line 2222 of file MaterialShared.h.
UsesEyeAdaptation()
bool FMaterial::UsesEyeAdaptation () const
UsesGlobalDistanceField_GameThread()
bool FMaterial::UsesGlobalDistanceField_GameThread () const
WritesEveryPixel() [1/2]
bool FMaterial::WritesEveryPixel (bool bShadowPass, bool bVFTypeSupportsNullPixelShader) const
WritesEveryPixel() [2/2]
bool FMaterial::WritesEveryPixel (bool bShadowPass = false) const
Friends And Related Symbol Documentation
FHLSLMaterialTranslator
friend class FHLSLMaterialTranslator friend
Definition at line 2881 of file MaterialShared.h.
References FHLSLMaterialTranslator.
Referenced by FHLSLMaterialTranslator.
FMaterialHLSLErrorHandler
friend class FMaterialHLSLErrorHandler friend
Definition at line 2882 of file MaterialShared.h.
References FMaterialHLSLErrorHandler.
Referenced by FMaterialHLSLErrorHandler.
FMaterialShaderMap
friend class FMaterialShaderMap friend
Definition at line 2879 of file MaterialShared.h.
References FMaterialShaderMap.
Referenced by FMaterialShaderMap, GetGameThreadShaderMap(), GetRenderingThreadShaderMap(), GetShaderMapToUse(), SetCompilingShaderMap(), SetGameThreadShaderMap(), and SetInlineShaderMap().
FShaderCompilingManager
friend class FShaderCompilingManager friend
Definition at line 2880 of file MaterialShared.h.
References FShaderCompilingManager.
Referenced by FShaderCompilingManager.
UE::Cook::FODSCClientData
friend class UE::Cook::FODSCClientData friend
Definition at line 2883 of file MaterialShared.h.
Field Documentation
bAllowPixelDepthOffset
uint32 FMaterial::bAllowPixelDepthOffset private
Definition at line 2805 of file MaterialShared.h.
Referenced by FMaterial(), AllowPixelDepthOffset(), and SetAllowPixelDepthOffset().
bContainsInlineShaders
uint32 FMaterial::bContainsInlineShaders private
Whether this material was loaded with shaders inlined.
If true, GameThreadShaderMap will contain a reference to the inlined shader map between Serialize and PostLoad.
Definition at line 2802 of file MaterialShared.h.
Referenced by FMaterial().
bGameThreadShaderMapIsComplete
std::atomic<bool> FMaterial::bGameThreadShaderMapIsComplete { false } private
Definition at line 2813 of file MaterialShared.h.
Referenced by IsGameThreadShaderMapComplete().
bLoadedCookedShaderMapId
uint32 FMaterial::bLoadedCookedShaderMapId private
Definition at line 2803 of file MaterialShared.h.
Referenced by FMaterial(), and GetLoadedCookedShaderMapId().
bOwnerBeginDestroyed
uint32 FMaterial::bOwnerBeginDestroyed private
Set when the owner of this FMaterial (typically a UMaterial or UMaterialInstance) has had BeginDestroy() called.
Definition at line 2809 of file MaterialShared.h.
Referenced by FMaterial(), IsOwnerBeginDestroyed(), and SetOwnerBeginDestroyed().
bRenderingThreadShaderMapIsComplete
std::atomic<bool> FMaterial::bRenderingThreadShaderMapIsComplete { false } private
Definition at line 2814 of file MaterialShared.h.
Referenced by IsRenderingThreadShaderMapComplete().
bStencilDitheredLOD
uint32 FMaterial::bStencilDitheredLOD private
Whether tthis project uses stencil dither lod.
Definition at line 2796 of file MaterialShared.h.
Referenced by FMaterial().
CacheShadersCompletion
TUniqueFunction<bool ()> FMaterial::CacheShadersCompletion private
Definition at line 2736 of file MaterialShared.h.
CacheShadersPending
TSharedPtr<FMaterialShaderMap::FAsyncLoadContext> FMaterial::CacheShadersPending private
Definition at line 2735 of file MaterialShared.h.
CompileErrors
TArray<FString> FMaterial::CompileErrors private
Definition at line 2730 of file MaterialShared.h.
Referenced by GetCompileErrors(), and SetCompileErrors().
DebugGroupName
FString FMaterial::DebugGroupName private
Definition at line 2744 of file MaterialShared.h.
Referenced by GetDebugGroupName().
EditorLoadedMaterialResources
TSet<FMaterial*> FMaterial::EditorLoadedMaterialResources static private
Tracks FMaterials without a corresponding UMaterialInterface in the editor, for example FExpressionPreviews.
Used to handle the 'recompileshaders changed' command in the editor. This doesn't have to use a reference counted pointer because materials are removed on destruction.
Definition at line 2728 of file MaterialShared.h.
Referenced by AddEditorLoadedMaterialResource().
ErrorExpressions
TArray<TObjectPtr<UMaterialExpression> > FMaterial::ErrorExpressions private
List of material expressions which generated a compiler error during the last compile.
Definition at line 2733 of file MaterialShared.h.
Referenced by GetErrorExpressions().
FeatureLevel
ERHIFeatureLevel::Type FMaterial::FeatureLevel private
Feature level that this material is representing.
Definition at line 2793 of file MaterialShared.h.
Referenced by FMaterial(), GetFeatureLevel(), and SetQualityLevelProperties().
GameThreadCompilingShaderMapId
uint32 FMaterial::GameThreadCompilingShaderMapId = 0 private
Definition at line 2738 of file MaterialShared.h.
Referenced by GetGameThreadCompilingShaderMapId().
GameThreadPendingCompilerEnvironment
TRefCountPtr<FSharedShaderCompilerEnvironment> FMaterial::GameThreadPendingCompilerEnvironment private
Definition at line 2741 of file MaterialShared.h.
GameThreadShaderMap
TRefCountPtr<FMaterialShaderMap> FMaterial::GameThreadShaderMap private
Game thread tracked shader map, which is ref counted and manages shader map lifetime.
The shader map uses deferred deletion so that the rendering thread has a chance to process a release command when the shader map is no longer referenced. Code that sets this is responsible for updating RenderingThreadShaderMap in a thread safe way. During an async compile, this will be NULL and will not contain the actual shader map until compilation is complete.
Definition at line 2763 of file MaterialShared.h.
Referenced by GetGameThreadShaderMap().
GameThreadShaderMapSubmittedPriority
EShaderCompileJobPriority FMaterial::GameThreadShaderMapSubmittedPriority = EShaderCompileJobPriority::None private
Used to prevent submitting the material more than once.
This is accessed by just the game thread so it doesn't need to be an atomic.
Definition at line 2755 of file MaterialShared.h.
Id_DEPRECATED
FGuid FMaterial::Id_DEPRECATED private
Legacy unique identifier of this material resource.
This functionality is now provided by UMaterial::StateId.
Definition at line 2776 of file MaterialShared.h.
Referenced by GetLegacyId().
NumDebugRefs
FThreadSafeCounter FMaterial::NumDebugRefs mutable
Definition at line 1984 of file MaterialShared.h.
Referenced by GetRefCount().
PrecachedPSORequestIDs
TArray<FMaterialPSOPrecacheRequestID> FMaterial::PrecachedPSORequestIDs private
MaterialPSO request IDs currently active for this material.
Definition at line 2817 of file MaterialShared.h.
PrecachedPSORequestIDsCS
FCriticalSection FMaterial::PrecachedPSORequestIDsCS static private
Shared critical section on PrecachedPSORequestIDs because contention should be very limited.
Definition at line 2820 of file MaterialShared.h.
QualityLevel
EMaterialQualityLevel::Type FMaterial::QualityLevel private
Contains the compiling id of this shader map when it is being compiled asynchronously.
This can be used to access the shader map during async compiling, since GameThreadShaderMap will not have been set yet. Quality level that this material is representing, may be EMaterialQualityLevel::Num if material doesn't depend on current quality level
Definition at line 2786 of file MaterialShared.h.
Referenced by FMaterial(), GetQualityLevel(), and SetQualityLevelProperties().
RenderingThreadCompilingShaderMapId
uint32 FMaterial::RenderingThreadCompilingShaderMapId = 0 private
Definition at line 2739 of file MaterialShared.h.
RenderingThreadPendingCompilerEnvironment
TRefCountPtr<FSharedShaderCompilerEnvironment> FMaterial::RenderingThreadPendingCompilerEnvironment private
Definition at line 2742 of file MaterialShared.h.
RenderingThreadShaderMap
TRefCountPtr<FMaterialShaderMap> FMaterial::RenderingThreadShaderMap private
Shader map for this material resource which is accessible by the rendering thread.
This must be updated along with GameThreadShaderMap, but on the rendering thread.
Definition at line 2769 of file MaterialShared.h.
Referenced by FMaterial().
RenderingThreadShaderMapSubmittedPriority
std::atomic<int8> FMaterial::RenderingThreadShaderMapSubmittedPriority { -1 } mutable private
Used to prevent submitting the material more than once during CacheMeshDrawCommands unless priority has been increased.
Definition at line 2750 of file MaterialShared.h.
TransientOverrides
FUniformParameterOverrides FMaterial::TransientOverrides
Definition at line 2398 of file MaterialShared.h.
The documentation for this class was generated from the following file:
MaterialShared.h