Unreal Engine 5.6 C++ API: DisplayClusterHelpers::filesystem Namespace Reference
DisplayClusterHelpers::filesystem Namespace Reference
Functions
static FString GetFullPathForConfig (const FString &RelativeConfig)
static FString GetFullPathForConfigResource (const FString &ResourcePath)
static FString GetFullPathForThirdPartyDLL (const FString &InRelativePathForThirdPartyDll)
Returns the full path to the DLL located in the ThirdParty directory in the nDisplay plugin.
static TArray< FString > GetOrderedConfigResourceDirs ()
Get ordered search base dirs for resources.
static FString GetRelativePathForConfigResource (const FString &ResourceFullPath)
Getting the relative path to an external file.
Function Documentation
GetFullPathForConfig()
FString DisplayClusterHelpers::filesystem::GetFullPathForConfig (const FString & RelativeConfig) static
Definition at line 401 of file DisplayClusterHelpers.h.
References FPaths::ConvertRelativePathToFull(), IFileManager::ConvertToAbsolutePathForExternalAppForRead(), TArray< InElementType, InAllocatorType >::Emplace(), FPaths::FileExists(), IFileManager::Get(), FPaths::IsRelative(), FPaths::LaunchDir(), FPaths::ProjectDir(), and Root.
GetFullPathForConfigResource()
FString DisplayClusterHelpers::filesystem::GetFullPathForConfigResource (const FString & ResourcePath) static
Definition at line 480 of file DisplayClusterHelpers.h.
References FPaths::ConvertRelativePathToFull(), FPaths::FileExists(), GetOrderedConfigResourceDirs(), FPaths::IsRelative(), FPaths::NormalizeFilename(), and DisplayClusterHelpers::str::TrimStringValue().
GetFullPathForThirdPartyDLL()
FString DisplayClusterHelpers::filesystem::GetFullPathForThirdPartyDLL (const FString & InRelativePathForThirdPartyDll) static
Returns the full path to the DLL located in the ThirdParty directory in the nDisplay plugin.
Parameters
InRelativePathForThirdPartyDll - relative path to dll from ThirdParty root
Returns
full path to file
Definition at line 509 of file DisplayClusterHelpers.h.
References FPaths::Combine(), FPaths::FileExists(), and TEXT.
GetOrderedConfigResourceDirs()
TArray< FString > DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs () static
Get ordered search base dirs for resources.
Definition at line 431 of file DisplayClusterHelpers.h.
References TArray< InElementType, InAllocatorType >::Add(), FPaths::ConvertRelativePathToFull(), IDisplayCluster::Get(), IDisplayCluster::GetConfigMgr(), IDisplayClusterConfigManager::GetConfigPath(), FPaths::GetPath(), FPaths::ProjectDir(), and FPaths::RootDir().
Referenced by GetFullPathForConfigResource(), and GetRelativePathForConfigResource().
GetRelativePathForConfigResource()
FString DisplayClusterHelpers::filesystem::GetRelativePathForConfigResource (const FString & ResourceFullPath) static
Getting the relative path to an external file.
Definition at line 459 of file DisplayClusterHelpers.h.
References GetOrderedConfigResourceDirs(), FPaths::NormalizeFilename(), and DisplayClusterHelpers::str::TrimStringValue().