Unreal Engine 5.6 C++ API: EntryPointHandle.h File Reference
EntryPointHandle.h File Reference
#include "CoreMinimal.h"
#include "TraitCore/NodeHandle.h"
#include "EntryPointHandle.generated.h"
Functions
USTRUCT () struct FAnimNextEntryPointHandle final
Entry Point Handle An entry point handle is equivalent to a trait handle but it will not resolve automatically on load.
Function Documentation
USTRUCT()
USTRUCT () final
Entry Point Handle An entry point handle is equivalent to a trait handle but it will not resolve automatically on load.
As such, it is safe to use outside of an AnimNext graph. They must be manually resolved through FTraitReader.
Internally, it contains a node handle (as a node ID) and a trait index.
See also
FAnimNextTraitHandle, FTraitReader
Definition at line 21 of file EntryPointHandle.h.
References BlueprintType, check, UE::AnimNext::FNodeHandle::FromPackedValue(), GENERATED_BODY, UE::AnimNext::FNodeHandle::GetPackedValue(), UE::AnimNext::FNodeHandle::INVALID_NODE_HANDLE_RAW_VALUE, UE::AnimNext::FNodeHandle::IsNodeID(), IsValid(), UE::AnimNext::FNodeHandle::IsValid(), MAX_uint8, and UPROPERTY.