Unreal Engine 5.6 C++ API: FInterpCurve< T > Class Template Reference
FInterpCurve< T > Class Template Reference
Template for interpolation curves.
#include "InterpCurve.h"
Public Types
using ElementType = T
Public Member Functions
FInterpCurve ()
Default constructor.
int32 AddPoint (const float InVal, const T &OutVal)
Adds a new keypoint to the InterpCurve with the supplied In and Out value.
void AutoSetTangents (float Tension=0.0f, bool bStationaryEndpoints=true)
Automatically set the tangents on the curve based on surrounding points.
void CalcBounds (T &OutMin, T &OutMax, const T &Default=T(ForceInit)) const
Calculate the min/max out value that can be returned by this InterpCurve.
void ClearLoopKey ()
Clear loop key for curve.
T Eval (const float InVal, const T &Default=T(ForceInit)) const
Evaluate the output for an arbitary input value.
T EvalDerivative (const float InVal, const T &Default=T(ForceInit)) const
Evaluate the derivative at a point on the curve.
T EvalSecondDerivative (const float InVal, const T &Default=T(ForceInit)) const
Evaluate the second derivative at a point on the curve.
float FindNearest (const T &PointInSpace, float &OutDistanceSq) const
Find the nearest point on spline to the given point.
float FindNearest (const T &PointInSpace, float &OutDistanceSq, float &OutSegment) const
Find the nearest point on spline to the given point.
float FindNearestOnSegment (const T &PointInSpace, int32 PtIdx, float &OutSquaredDistance) const
Find the nearest point (to the given point) on segment between Points[PtIdx] and Points[PtIdx+1].
int32 GetPointIndexForInputValue (const float InValue) const
Finds the lower index of the two points whose input values bound the supplied input value.
float InaccurateFindNearest (const T &PointInSpace, float &OutDistanceSq) const
float InaccurateFindNearest (const T &PointInSpace, float &OutDistanceSq, float &OutSegment) const
float InaccurateFindNearestOnSegment (const T &PointInSpace, int32 PtIdx, float &OutSquaredDistance) const
int32 MovePoint (int32 PointIndex, float NewInVal)
Moves a keypoint to a new In value.
void Reset ()
Clears all keypoints from InterpCurve.
void SetLoopKey (float InLoopKey)
Set loop key for curve.
Data Fields
bool bIsLooped
Specify whether the curve is looped or not.
float LoopKeyOffset
Specify the offset from the last point's input key corresponding to the loop point.
TArray< FInterpCurvePoint< T > > Points
Holds the collection of interpolation points.
Friends
bool operator!= (const FInterpCurve &Curve1, const FInterpCurve &Curve2)
Compare inequality of two FInterpCurves.
FArchive & operator<< (FArchive &Ar, FInterpCurve &Curve)
Serializes the interp curve.
bool operator== (const FInterpCurve &Curve1, const FInterpCurve &Curve2)
Compare equality of two FInterpCurves.
Detailed Description
template<class T>
class FInterpCurve< T >
Template for interpolation curves.
See also
FInterpCurvePoint
Todo
Docs: FInterpCurve needs template and function documentation
Definition at line 25 of file InterpCurve.h.
Member Typedef Documentation
ElementType
template<class T> using FInterpCurve< T >::ElementType = T
Definition at line 39 of file InterpCurve.h.
Constructor & Destructor Documentation
FInterpCurve()
template<class T> FInterpCurve< T >::FInterpCurve () inline nodiscard
Default constructor.
Definition at line 42 of file InterpCurve.h.
Member Function Documentation
AddPoint()
template<class T> int32 FInterpCurve< T >::AddPoint (const float InVal, const T & OutVal)
Adds a new keypoint to the InterpCurve with the supplied In and Out value.
Parameters
InVal
OutVal
Returns
The index of the new key.
Definition at line 197 of file InterpCurve.h.
References Points.
Referenced by MovePoint().
AutoSetTangents()
template<class T> void FInterpCurve< T >::AutoSetTangents (float Tension = 0.0f, bool bStationaryEndpoints = true)
Automatically set the tangents on the curve based on surrounding points.
Definition at line 674 of file InterpCurve.h.
References bIsLooped, CIM_Constant, CIM_CurveAuto, CIM_CurveAutoClamped, CIM_Linear, ComputeCurveTangent(), ForceInit, LoopKeyOffset, Points, and Tangent.
CalcBounds()
template<class T> void FInterpCurve< T >::CalcBounds (T & OutMin, T & OutMax, const T & Default = T(ForceInit)) const
Calculate the min/max out value that can be returned by this InterpCurve.
Definition at line 743 of file InterpCurve.h.
References bIsLooped, CurveFindIntervalBounds(), Default, and Points.
ClearLoopKey()
template<class T> void FInterpCurve< T >::ClearLoopKey ()
Clear loop key for curve.
Definition at line 261 of file InterpCurve.h.
References bIsLooped.
Eval()
template<class T> T FInterpCurve< T >::Eval (const float InVal, const T & Default = T(ForceInit)) const nodiscard
Evaluate the output for an arbitary input value.
For inputs outside the range of the keys, the first/last key value is assumed.
Definition at line 307 of file InterpCurve.h.
References Alpha, bIsLooped, check, checkf, CIM_Constant, CIM_Linear, FMath::CubicInterp(), Default, GetPointIndexForInputValue(), FMath::Lerp(), logOrEnsureNanError, LoopKeyOffset, Points, and TEXT.
EvalDerivative()
template<class T> T FInterpCurve< T >::EvalDerivative (const float InVal, const T & Default = T(ForceInit)) const nodiscard
Evaluate the derivative at a point on the curve.
Definition at line 382 of file InterpCurve.h.
References Alpha, bIsLooped, check, checkf, CIM_Constant, CIM_Linear, FMath::CubicInterpDerivative(), Default, ForceInit, GetPointIndexForInputValue(), logOrEnsureNanError, LoopKeyOffset, Points, and TEXT.
EvalSecondDerivative()
template<class T> T FInterpCurve< T >::EvalSecondDerivative (const float InVal, const T & Default = T(ForceInit)) const nodiscard
Evaluate the second derivative at a point on the curve.
Definition at line 457 of file InterpCurve.h.
References Alpha, bIsLooped, check, checkf, CIM_Constant, CIM_Linear, FMath::CubicInterpSecondDerivative(), Default, ForceInit, GetPointIndexForInputValue(), logOrEnsureNanError, LoopKeyOffset, Points, and TEXT.
FindNearest() [1/2]
template<class T> float FInterpCurve< T >::FindNearest (const T & PointInSpace, float & OutDistanceSq) const
Find the nearest point on spline to the given point.
Parameters
PointInSpace - the given point
OutDistanceSq - output - the squared distance between the given point and the closest found point.
Returns
The key (the 't' parameter) of the nearest point.
Definition at line 528 of file InterpCurve.h.
References FindNearest().
Referenced by FindNearest(), InaccurateFindNearest(), and InaccurateFindNearest().
FindNearest() [2/2]
template<class T> float FInterpCurve< T >::FindNearest (const T & PointInSpace, float & OutDistanceSq, float & OutSegment) const
Find the nearest point on spline to the given point.
Parameters
PointInSpace - the given point
OutDistanceSq - output - the squared distance between the given point and the closest found point.
OutSegment - output - the nearest segment to the given point.
Returns
The key (the 't' parameter) of the nearest point.
Definition at line 542 of file InterpCurve.h.
References bIsLooped, FindNearestOnSegment(), float, Points, and Segment.
FindNearestOnSegment()
template<class T> float FInterpCurve< T >::FindNearestOnSegment (const T & PointInSpace, int32 PtIdx, float & OutSquaredDistance) const
Find the nearest point (to the given point) on segment between Points[PtIdx] and Points[PtIdx+1].
Parameters
PointInSpace - the given point
Returns
The key (the 't' parameter) of the found point.
Definition at line 585 of file InterpCurve.h.
References A, B, bIsLooped, check, CIM_Constant, CIM_Linear, FMath::Clamp(), FMath::CubicInterp(), FMath::Lerp(), LoopKeyOffset, Points, and UE::Math::TPolynomialRootSolver< RealType, PolynomialDegree >::Roots.
Referenced by FindNearest(), and InaccurateFindNearestOnSegment().
GetPointIndexForInputValue()
template<class T> int32 FInterpCurve< T >::GetPointIndexForInputValue (const float InValue) const nodiscard
Finds the lower index of the two points whose input values bound the supplied input value.
Definition at line 268 of file InterpCurve.h.
References check, and Points.
Referenced by Eval(), EvalDerivative(), and EvalSecondDerivative().
InaccurateFindNearest() [1/2]
template<class T> float FInterpCurve< T >::InaccurateFindNearest (const T & PointInSpace, float & OutDistanceSq) const
Deprecated
Use FindNearest instead.
Definition at line 535 of file InterpCurve.h.
References FindNearest().
InaccurateFindNearest() [2/2]
template<class T> float FInterpCurve< T >::InaccurateFindNearest (const T & PointInSpace, float & OutDistanceSq, float & OutSegment) const
Deprecated
Use FindNearest instead.
Definition at line 579 of file InterpCurve.h.
References FindNearest().
InaccurateFindNearestOnSegment()
template<class T> float FInterpCurve< T >::InaccurateFindNearestOnSegment (const T & PointInSpace, int32 PtIdx, float & OutSquaredDistance) const
Deprecated
Use FindNearestOnSegment instead.
Definition at line 668 of file InterpCurve.h.
References FindNearestOnSegment().
MovePoint()
template<class T> int32 FInterpCurve< T >::MovePoint (int32 PointIndex, float NewInVal)
Moves a keypoint to a new In value.
This may change the index of the keypoint, so the new key index is returned.
Parameters
PointIndex
NewInVal
Returns
Definition at line 207 of file InterpCurve.h.
References AddPoint(), and Points.
Reset()
template<class T> void FInterpCurve< T >::Reset ()
Clears all keypoints from InterpCurve.
Definition at line 229 of file InterpCurve.h.
References Points.
SetLoopKey()
template<class T> void FInterpCurve< T >::SetLoopKey (float InLoopKey)
Set loop key for curve.
Definition at line 236 of file InterpCurve.h.
References bIsLooped, LoopKeyOffset, and Points.
Friends And Related Symbol Documentation
operator!=
template<class T> bool operator!= (const FInterpCurve< T > & Curve1, const FInterpCurve< T > & Curve2) friend
Compare inequality of two FInterpCurves.
Definition at line 181 of file InterpCurve.h.
operator<<
template<class T> FArchive & operator<< (FArchive & Ar, FInterpCurve< T > & Curve) friend
Serializes the interp curve.
Parameters
Ar Reference to the serialization archive.
Curve Reference to the interp curve being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 153 of file InterpCurve.h.
operator==
template<class T> bool operator== (const FInterpCurve< T > & Curve1, const FInterpCurve< T > & Curve2) friend
Compare equality of two FInterpCurves.
Definition at line 171 of file InterpCurve.h.
Field Documentation
bIsLooped
template<class T> bool FInterpCurve< T >::bIsLooped
Specify whether the curve is looped or not.
Definition at line 33 of file InterpCurve.h.
Referenced by AutoSetTangents(), CalcBounds(), ClearLoopKey(), Eval(), EvalDerivative(), EvalSecondDerivative(), FindNearest(), FindNearestOnSegment(), FInterpCurve< float >::operator<<, FInterpCurve< float >::operator==, and SetLoopKey().
LoopKeyOffset
template<class T> float FInterpCurve< T >::LoopKeyOffset
Specify the offset from the last point's input key corresponding to the loop point.
Definition at line 36 of file InterpCurve.h.
Referenced by AutoSetTangents(), Eval(), EvalDerivative(), EvalSecondDerivative(), FindNearestOnSegment(), FInterpCurve< float >::operator<<, FInterpCurve< float >::operator==, and SetLoopKey().
Points
template<class T> TArray<FInterpCurvePoint<T> > FInterpCurve< T >::Points
Holds the collection of interpolation points.
Definition at line 30 of file InterpCurve.h.
Referenced by AddPoint(), AutoSetTangents(), CalcBounds(), Eval(), EvalDerivative(), EvalSecondDerivative(), FindNearest(), FindNearestOnSegment(), GetPointIndexForInputValue(), MovePoint(), FInterpCurve< float >::operator<<, FInterpCurve< float >::operator==, Reset(), and SetLoopKey().
The documentation for this class was generated from the following files:
ConnectionDrawingPolicy.h
InterpCurve.h