Unreal Engine 5.6 C++ API: FMainMRUFavoritesList Class Reference
FMainMRUFavoritesList Class Reference
Simple class to represent a combined MRU and favorite map list.
#include "MRUFavoritesList.h"
Public Member Functions
UNREALED_API FMainMRUFavoritesList ()
Constructor.
UNREALED_API FMainMRUFavoritesList (const FString &IniSectionOverride, const FString &IniFavoritesSectionOverride, const int32 InitMaxItems=12)
UNREALED_API ~FMainMRUFavoritesList ()
Destructor.
UNREALED_API void AddFavoritesItem (const FString &Item)
Add a new file item to the favorites list.
UNREALED_API bool ContainsFavoritesItem (const FString &Item) const
Returns whether a filename is favorited or not.
DECLARE_DELEGATE_RetVal_OneParam (bool, FDoesMRUFavoritesItemPassFilter, const FString &MRUFavoritesItem)
UNREALED_API bool FavoritesItemPassesCurrentFilter (int32 ItemIndex) const
Checks the favorites item specified by the provided index against the optional 'DoesMRUFavoritesItemPassFilterDelegate'.
UNREALED_API FString GetFavoritesItem (int32 ItemIndex) const
Return the favorites item specified by the provided index.
int32 GetNumFavorites () const
Returns the number of favorites items.
UNREALED_API void MoveFavoritesItemToHead (const FString &Item)
Moves the specified favorites item to the head of the list.
UNREALED_API bool MRUItemPassesCurrentFilter (int32 ItemIndex) const
Checks the MRU item specified by the provided index against the optional 'DoesMRUFavoritesItemPassFilterDelegate'.
virtual UNREALED_API void ReadFromINI ()
Populate MRU/Favorites list by reading saved values from the relevant INI file.
UNREALED_API void RegisterDoesMRUFavoritesItemPassFilterDelegate (FDoesMRUFavoritesItemPassFilter DoesMRUFavoritesItemPassFilterDelegate)
Supplies an optional delegate that can be used to filter a given MRUFavorites item Useful for dynamically verifying which items should be utilized at a given time.
UNREALED_API void RemoveFavoritesItem (const FString &Item)
Remove a file from the favorites list.
UE_DEPRECATED (5.4, "Use the constructor that takes in an override section for the favorites as well") UNREALED_API FMainMRUFavoritesList(const FString &IniSectionOverride
UNREALED_API void UnregisterDoesMRUFavoritesItemPassFilterDelegate ()
Unregisters the optional filter delegate.
UNREALED_API bool VerifyFavoritesFile (int32 ItemIndex)
Verifies that the favorites item specified by the provided index still exists.
virtual UNREALED_API void WriteToINI () const
Save off the state of the MRU and favorites lists to the relevant INI file.
Public Member Functions inherited from FMRUList
UNREALED_API FMRUList (const FString &InINISection, const int32 InitMaxItems=12)
virtual UNREALED_API ~FMRUList ()
UNREALED_API void AddMRUItem (const FString &Item)
Adds an item to the MRU list, moving it to the top.
UNREALED_API void ClearMRUItems ()
Clears the list of MRU items.
UNREALED_API int32 FindMRUItemIdx (const FString &Item) const
Returns the index of the specified item, or INDEX_NONE if not found.
int32 GetMaxItems ()
const FString & GetMRUItem (int32 ItemIndex) const
Accessor.
int32 GetNumItems () const
Returns the number of MRU items.
UNREALED_API void RemoveMRUItem (const FString &Item)
Removes the specified item from the list if it exists.
UNREALED_API void RemoveMRUItem (int32 ItemIndex)
Removes the item at the specified index.
UNREALED_API bool VerifyMRUFile (int32 ItemIndex, FString &OutPackageName)
Checks to make sure the file specified still exists.
Data Fields
const int32 InitMaxItems = 12)
Private Attributes
FDoesMRUFavoritesItemPassFilter DoesMRUFavoritesItemPassFilter
Filter delegate.
TArray< FString > FavoriteItems
Favorited items.
FString INIFavoritesSection
INI section to read/write favorite items to.
Additional Inherited Members
Static Protected Member Functions inherited from FMRUList
static UNREALED_API void InternalReadINI (TArray< FString > &OutItems, const FString &INISection, const FString &INIKeyBase, int32 NumElements)
Internal helper function to populate a provided array with data from the provided ini section using the provided ini key as a base, searching for the number of provided elements at a maximum.
static UNREALED_API void InternalWriteINI (const TArray< FString > &InItems, const FString &INISection, const FString &INIKeyBase)
Internal helper function to write out the provided array of data to the provided INI section, using the provided key base as a prefix for each item written to the INI file.
Protected Attributes inherited from FMRUList
FString INISection
The INI section we read/write the filenames to.
TArray< FString > Items
The filenames.
const int32 MaxItems
Maximum MRU items.
Detailed Description
Simple class to represent a combined MRU and favorite map list.
Definition at line 18 of file MRUFavoritesList.h.
Constructor & Destructor Documentation
FMainMRUFavoritesList() [1/2]
UNREALED_API FMainMRUFavoritesList::FMainMRUFavoritesList ()
Constructor.
Referenced by FMainMRUFavoritesList(), and ~FMainMRUFavoritesList().
FMainMRUFavoritesList() [2/2]
UNREALED_API FMainMRUFavoritesList::FMainMRUFavoritesList (const FString & IniSectionOverride, const FString & IniFavoritesSectionOverride, const int32 InitMaxItems = 12)
References FMainMRUFavoritesList(), and InitMaxItems.
~FMainMRUFavoritesList()
UNREALED_API FMainMRUFavoritesList::~FMainMRUFavoritesList ()
Destructor.
References FMainMRUFavoritesList().
Member Function Documentation
AddFavoritesItem()
UNREALED_API void FMainMRUFavoritesList::AddFavoritesItem (const FString & Item)
Add a new file item to the favorites list.
Parameters
Item Filename of the item to add to the favorites list
References Item.
ContainsFavoritesItem()
UNREALED_API bool FMainMRUFavoritesList::ContainsFavoritesItem (const FString & Item) const
Returns whether a filename is favorited or not.
Parameters
Item Filename of the item to check
Returns
true if the provided item is in the favorite's list; false if it is not
References Item.
DECLARE_DELEGATE_RetVal_OneParam()
FMainMRUFavoritesList::DECLARE_DELEGATE_RetVal_OneParam (bool , FDoesMRUFavoritesItemPassFilter , const FString & MRUFavoritesItem)
FavoritesItemPassesCurrentFilter()
UNREALED_API bool FMainMRUFavoritesList::FavoritesItemPassesCurrentFilter (int32 ItemIndex) const
Checks the favorites item specified by the provided index against the optional 'DoesMRUFavoritesItemPassFilterDelegate'.
Parameters
ItemIndex Index of the favorites item to check
Returns
true if the item specified by the index passes the filter or if no filter has been provided; false if it does not pass the filter
GetFavoritesItem()
UNREALED_API FString FMainMRUFavoritesList::GetFavoritesItem (int32 ItemIndex) const
Return the favorites item specified by the provided index.
Parameters
ItemIndex Index of the favorites item to return
Returns
The favorites item specified by the provided index
GetNumFavorites()
int32 FMainMRUFavoritesList::GetNumFavorites () const inline
Returns the number of favorites items.
Returns
Number of favorites
Definition at line 43 of file MRUFavoritesList.h.
References FavoriteItems, and GetNumFavorites().
Referenced by GetNumFavorites().
MoveFavoritesItemToHead()
UNREALED_API void FMainMRUFavoritesList::MoveFavoritesItemToHead (const FString & Item)
Moves the specified favorites item to the head of the list.
Parameters
Item Filename of the item to move
References Item.
MRUItemPassesCurrentFilter()
UNREALED_API bool FMainMRUFavoritesList::MRUItemPassesCurrentFilter (int32 ItemIndex) const
Checks the MRU item specified by the provided index against the optional 'DoesMRUFavoritesItemPassFilterDelegate'.
Parameters
ItemIndex Index of the MRU item to check
Returns
true if the item specified by the index passes the filter or if no filter has been provided; false if it does not pass the filter
ReadFromINI()
virtual UNREALED_API void FMainMRUFavoritesList::ReadFromINI () virtual
Populate MRU/Favorites list by reading saved values from the relevant INI file.
Reimplemented from FMRUList.
References ReadFromINI().
Referenced by ReadFromINI().
RegisterDoesMRUFavoritesItemPassFilterDelegate()
UNREALED_API void FMainMRUFavoritesList::RegisterDoesMRUFavoritesItemPassFilterDelegate (FDoesMRUFavoritesItemPassFilter DoesMRUFavoritesItemPassFilterDelegate)
Supplies an optional delegate that can be used to filter a given MRUFavorites item Useful for dynamically verifying which items should be utilized at a given time.
Parameters
DoesMRUFavoritesItemPassFilterDelegate The delegate to use
RemoveFavoritesItem()
UNREALED_API void FMainMRUFavoritesList::RemoveFavoritesItem (const FString & Item)
Remove a file from the favorites list.
Parameters
Item Filename of the item to remove from the favorites list
References Item.
UE_DEPRECATED()
FMainMRUFavoritesList::UE_DEPRECATED (5. 4, "Use the constructor that takes in an override section for the favorites as well") const &
UnregisterDoesMRUFavoritesItemPassFilterDelegate()
UNREALED_API void FMainMRUFavoritesList::UnregisterDoesMRUFavoritesItemPassFilterDelegate ()
Unregisters the optional filter delegate.
VerifyFavoritesFile()
UNREALED_API bool FMainMRUFavoritesList::VerifyFavoritesFile (int32 ItemIndex)
Verifies that the favorites item specified by the provided index still exists.
If it does not, the item is removed from the favorites list and the user is notified.
Parameters
ItemIndex Index of the favorites item to check
Returns
true if the item specified by the index was verified and still exists; false if it does not
WriteToINI()
virtual UNREALED_API void FMainMRUFavoritesList::WriteToINI () const virtual
Save off the state of the MRU and favorites lists to the relevant INI file.
Reimplemented from FMRUList.
References WriteToINI().
Referenced by WriteToINI().
Field Documentation
DoesMRUFavoritesItemPassFilter
FDoesMRUFavoritesItemPassFilter FMainMRUFavoritesList::DoesMRUFavoritesItemPassFilter private
Filter delegate.
Definition at line 132 of file MRUFavoritesList.h.
FavoriteItems
TArray<FString> FMainMRUFavoritesList::FavoriteItems private
Favorited items.
Definition at line 135 of file MRUFavoritesList.h.
Referenced by GetNumFavorites().
INIFavoritesSection
FString FMainMRUFavoritesList::INIFavoritesSection private
INI section to read/write favorite items to.
Definition at line 138 of file MRUFavoritesList.h.
InitMaxItems
const int32 FMainMRUFavoritesList::InitMaxItems = 12)
Definition at line 25 of file MRUFavoritesList.h.
Referenced by FMainMRUFavoritesList().
The documentation for this class was generated from the following file:
MRUFavoritesList.h