Unreal Engine 5.6 C++ API: ICompressionFormat Struct Reference
ICompressionFormat Struct Reference abstract
#include "ICompressionFormat.h"
Public Member Functions
virtual bool Compress (void *CompressedBuffer, int64 &CompressedSize, const void *UncompressedBuffer, int64 UncompressedSize, uintptr_t CompressionData, ECompressionFlags Flags)
virtual bool DoesOwnWorthDecompressingCheck ()=0
virtual bool GetCompressedBufferSize (int64 &OutBufferSize, int64 UncompressedSize, uintptr_t CompressionData)
virtual FName GetCompressionFormatName ()=0
virtual FString GetDDCKeySuffix ()=0
virtual uint32 GetVersion ()=0
UE_DEPRECATED (5.5, "Switch to 64 bit version for memory sizes") virtual bool Compress(void *CompressedBuffer
UE_DEPRECATED (5.5, "Switch to 64 bit version for memory sizes") virtual bool Uncompress(void *UncompressedBuffer
UE_DEPRECATED (5.5, "Switch to 64 bit version for memory sizes") virtual int32 GetCompressedBufferSize(int32 UncompressedSize
virtual bool Uncompress (void *UncompressedBuffer, int64 UncompressedSize, const void *CompressedBuffer, int64 CompressedSize, uintptr_t CompressionData)
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Data Fields
int32 const void * CompressedBuffer
int32 & CompressedSize
int32 const void int32 CompressedSize
int32 const void int32 int32 CompressionData {return false
int32 CompressionData {return -1
int32 const void int32 int32 ECompressionFlags Flags { return false
int32 const void * UncompressedBuffer
int32 const void int32 UncompressedSize
int32 & UncompressedSize
Detailed Description
Definition at line 14 of file ICompressionFormat.h.
Member Function Documentation
Compress()
virtual bool ICompressionFormat::Compress (void * CompressedBuffer, int64 & CompressedSize, const void * UncompressedBuffer, int64 UncompressedSize, uintptr_t CompressionData, ECompressionFlags Flags) inline virtual
Definition at line 22 of file ICompressionFormat.h.
References Compress, CompressedBuffer, CompressedSize, CompressionData, Flags, IntFitsIn(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, UncompressedBuffer, and UncompressedSize.
DoesOwnWorthDecompressingCheck()
virtual bool ICompressionFormat::DoesOwnWorthDecompressingCheck () pure virtual
GetCompressedBufferSize()
virtual bool ICompressionFormat::GetCompressedBufferSize (int64 & OutBufferSize, int64 UncompressedSize, uintptr_t CompressionData) inline virtual
Definition at line 55 of file ICompressionFormat.h.
References checkf, CompressionData, GetCompressedBufferSize(), GetCompressionFormatName(), IntFitsIn(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, TEXT, ToString(), and UncompressedSize.
Referenced by GetCompressedBufferSize().
GetCompressionFormatName()
virtual FName ICompressionFormat::GetCompressionFormatName () pure virtual
Referenced by GetCompressedBufferSize().
GetDDCKeySuffix()
virtual FString ICompressionFormat::GetDDCKeySuffix () pure virtual
GetVersion()
virtual uint32 ICompressionFormat::GetVersion () pure virtual
UE_DEPRECATED() [1/3]
ICompressionFormat::UE_DEPRECATED (5. 5, "Switch to 64 bit version for memory sizes")
UE_DEPRECATED() [2/3]
ICompressionFormat::UE_DEPRECATED (5. 5, "Switch to 64 bit version for memory sizes")
UE_DEPRECATED() [3/3]
ICompressionFormat::UE_DEPRECATED (5. 5, "Switch to 64 bit version for memory sizes")
Uncompress()
virtual bool ICompressionFormat::Uncompress (void * UncompressedBuffer, int64 UncompressedSize, const void * CompressedBuffer, int64 CompressedSize, uintptr_t CompressionData) inline virtual
Definition at line 39 of file ICompressionFormat.h.
References CompressedBuffer, CompressedSize, CompressionData, IntFitsIn(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, Uncompress(), UncompressedBuffer, and UncompressedSize.
Referenced by Uncompress().
Field Documentation
CompressedBuffer
int32 const void* ICompressionFormat::CompressedBuffer
Definition at line 36 of file ICompressionFormat.h.
Referenced by Compress(), and Uncompress().
CompressedSize [1/2]
int32& ICompressionFormat::CompressedSize
Definition at line 19 of file ICompressionFormat.h.
Referenced by Compress(), and Uncompress().
CompressedSize [2/2]
int32 const void int32 ICompressionFormat::CompressedSize
Definition at line 36 of file ICompressionFormat.h.
CompressionData [1/2]
int32 const void int32 int32 ICompressionFormat::CompressionData {return false
Definition at line 19 of file ICompressionFormat.h.
Referenced by Compress(), GetCompressedBufferSize(), and Uncompress().
CompressionData [2/2]
int32 ICompressionFormat::CompressionData {return -1
Definition at line 53 of file ICompressionFormat.h.
Flags
int32 const void int32 int32 ECompressionFlags ICompressionFormat::Flags { return false
Definition at line 19 of file ICompressionFormat.h.
Referenced by Compress().
UncompressedBuffer
int32 const void* ICompressionFormat::UncompressedBuffer
Definition at line 19 of file ICompressionFormat.h.
Referenced by Compress(), and Uncompress().
UncompressedSize [1/2]
int32 const void int32 ICompressionFormat::UncompressedSize
Definition at line 19 of file ICompressionFormat.h.
Referenced by Compress(), GetCompressedBufferSize(), and Uncompress().
UncompressedSize [2/2]
int32& ICompressionFormat::UncompressedSize
Definition at line 36 of file ICompressionFormat.h.
The documentation for this struct was generated from the following file:
ICompressionFormat.h