Unreal Engine 5.6 C++ API: GPUSkinCache.h File Reference
GPUSkinCache.h File Reference
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "HAL/IConsoleManager.h"
#include "RHI.h"
#include "RHIUtilities.h"
#include "RenderGraphDefinitions.h"
#include "RenderResource.h"
#include "ShaderParameters.h"
#include "UniformBuffer.h"
#include "GPUSkinPublicDefs.h"
#include "VertexFactory.h"
#include "CanvasTypes.h"
#include "CachedGeometry.h"
#include "DataDrivenShaderPlatformInfo.h"
#include "Engine/SkinnedAssetCommon.h"
Data Structures
struct FClothSimulEntry
class FGPUSkinCache
struct FGPUSkinCache::FDispatchEntry
struct FGPUSkinCache::FSortedDispatchEntry
Enumerations
enum class EGPUSkinCacheEntryMode { Raster , RayTracing }
Functions
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Sections Processed"), STAT_GPUSkinCache_NumSectionsProcessed, STATGROUP_GPUSkinCache,)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Sections Skinned"), STAT_GPUSkinCache_TotalNumChunks, STATGROUP_GPUSkinCache,)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Triangles for Recompute Tangents"), STAT_GPUSkinCache_NumTrianglesForRecomputeTangents, STATGROUP_GPUSkinCache,)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Vertices Skinned"), STAT_GPUSkinCache_TotalNumVertices, STATGROUP_GPUSkinCache,)
DECLARE_MEMORY_STAT_EXTERN (TEXT("Intermediate buffer for Recompute Tangents"), STAT_GPUSkinCache_TangentsIntermediateMemUsed, STATGROUP_GPUSkinCache,)
DECLARE_MEMORY_STAT_EXTERN (TEXT("Total Memory Bytes Used"), STAT_GPUSkinCache_TotalMemUsed, STATGROUP_GPUSkinCache,)
DECLARE_STATS_GROUP (TEXT("GPU Skin Cache"), STATGROUP_GPUSkinCache, STATCAT_Advanced)
ESkinCacheDefaultBehavior GetSkinCacheDefaultBehavior ()
bool GPUSkinCacheStoreDuplicatedVertices ()
bool ShouldWeCompileGPUSkinVFShaders (EShaderPlatform Platform, ERHIFeatureLevel::Type FeatureLevel)
UE_DEPRECATED (5.6, "Use GPUSkinCacheStoreDuplicatedVertices instead to check if duplicate vertices need to be stored.") extern 1 bool GPUSkinCacheNeedsDuplicatedVertices()
Variables
int32 GEnableGPUSkinCache
int32 GSkinCacheRecomputeTangents
Enumeration Type Documentation
EGPUSkinCacheEntryMode
enum class EGPUSkinCacheEntryMode strong
Enumerator
Raster
RayTracing
Definition at line 101 of file GPUSkinCache.h.
Function Documentation
DECLARE_DWORD_COUNTER_STAT_EXTERN() [1/4]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Sections Processed") , STAT_GPUSkinCache_NumSectionsProcessed , STATGROUP_GPUSkinCache)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [2/4]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Sections Skinned") , STAT_GPUSkinCache_TotalNumChunks , STATGROUP_GPUSkinCache)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [3/4]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Triangles for Recompute Tangents") , STAT_GPUSkinCache_NumTrianglesForRecomputeTangents , STATGROUP_GPUSkinCache)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [4/4]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Num Vertices Skinned") , STAT_GPUSkinCache_TotalNumVertices , STATGROUP_GPUSkinCache)
DECLARE_MEMORY_STAT_EXTERN() [1/2]
DECLARE_MEMORY_STAT_EXTERN (TEXT("Intermediate buffer for Recompute Tangents") , STAT_GPUSkinCache_TangentsIntermediateMemUsed , STATGROUP_GPUSkinCache)
DECLARE_MEMORY_STAT_EXTERN() [2/2]
DECLARE_MEMORY_STAT_EXTERN (TEXT("Total Memory Bytes Used") , STAT_GPUSkinCache_TotalMemUsed , STATGROUP_GPUSkinCache)
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("GPU Skin Cache") , STATGROUP_GPUSkinCache , STATCAT_Advanced)
GetSkinCacheDefaultBehavior()
ESkinCacheDefaultBehavior GetSkinCacheDefaultBehavior () extern
References GEnableGPUSkinCache, GetSkinCacheDefaultBehavior(), and GSkinCacheRecomputeTangents.
Referenced by GetSkinCacheDefaultBehavior().
GPUSkinCacheStoreDuplicatedVertices()
bool GPUSkinCacheStoreDuplicatedVertices () extern
References GPUSkinCacheStoreDuplicatedVertices().
Referenced by GPUSkinCacheStoreDuplicatedVertices().
ShouldWeCompileGPUSkinVFShaders()
bool ShouldWeCompileGPUSkinVFShaders (EShaderPlatform Platform, ERHIFeatureLevel::Type FeatureLevel) extern
References Platform.
UE_DEPRECATED()
UE_DEPRECATED (5. 6, "Use GPUSkinCacheStoreDuplicatedVertices instead to check if duplicate vertices need to be stored.")
Variable Documentation
GEnableGPUSkinCache
int32 GEnableGPUSkinCache extern
Referenced by GetSkinCacheDefaultBehavior().
GSkinCacheRecomputeTangents
int32 GSkinCacheRecomputeTangents extern
Referenced by GetSkinCacheDefaultBehavior().