Unreal Engine 5.6 C++ API: FBlueprintEditorModule Class Reference
FBlueprintEditorModule Class Reference
The blueprint editor module provides the blueprint editor application.
#include "BlueprintEditorModule.h"
Public Member Functions
virtual TSharedRef< IBlueprintEditor > CreateBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const TArray< UBlueprint * > &BlueprintsToEdit, bool bShouldOpenInDefaultsMode=true)
virtual TSharedRef< IBlueprintEditor > CreateBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, UBlueprint *Blueprint, bool bShouldOpenInDefaultsMode=false)
Creates an instance of a Kismet editor object.
virtual TSharedRef< IUserDefinedEnumEditor > CreateUserDefinedEnumEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, UUserDefinedEnum *UDEnum)
Creates an instance of a Enum editor object.
virtual TSharedRef< IUserDefinedStructureEditor > CreateUserDefinedStructEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, UUserDefinedStruct *UDStruct)
Creates an instance of a Structure editor object.
virtual TArray< TSharedPtr< IDetailCustomization > > CustomizeFunction (TSubclassOf< UK2Node_EditablePinBase > InFunctionClass, TSharedPtr< IBlueprintEditor > InBlueprintEditor)
Build a set of details customizations for function with the passed-in type, if possible.
virtual TArray< TSharedPtr< IDetailCustomization > > CustomizeGraph (const UEdGraphSchema *InGraphSchema, TSharedPtr< IBlueprintEditor > InBlueprintEditor)
Build a set of details customizations for graphs with the passed-in schema, if possible.
virtual TArray< TSharedPtr< IDetailCustomization > > CustomizeVariable (FFieldClass *InFieldClass, TSharedPtr< IBlueprintEditor > InBlueprintEditor)
Build a set of details customizations for the passed-in type, if possible.
DECLARE_EVENT_OneParam (FBlueprintEditorModule, FBlueprintEditorOpenedEvent, EBlueprintType)
Delegate for binding functions to be called when the blueprint editor finishes getting created.
DECLARE_EVENT_OneParam (IBlueprintEditor, FOnRegisterLayoutExtensions, FLayoutExtender &)
DECLARE_EVENT_ThreeParams (IBlueprintEditor, FOnRegisterTabs, FWorkflowAllowedTabSet &, FName, TSharedPtr< FBlueprintEditor >)
DECLARE_EVENT_TwoParams (FBlueprintEditorModule, FBlueprintMenuExtensionEvent, TSharedPtr< FExtender >, UBlueprint *)
const TUniquePtr< FBlueprintDebugger > & GetBlueprintDebugger () const
Returns a reference to the Blueprint Debugger state object.
virtual TArray< TSharedRef< IBlueprintEditor > > GetBlueprintEditors () const
Get all blueprint editor instances.
virtual TSharedPtr< FExtensibilityManager > GetMenuExtensibilityManager () override
Gets the extensibility managers for outside entities to extend blueprint editor's menus and toolbars.
virtual const TSharedRef< FUICommandList > GetsSharedBlueprintEditorCommands () const
Exposes a way for other modules to fold in their own Blueprint editor commands (folded in with other BP editor commands, when the editor is first opened).
FBlueprintEditorOpenedEvent & OnBlueprintEditorOpened ()
FBlueprintMenuExtensionEvent & OnGatherBlueprintMenuExtensions ()
FOnRegisterLayoutExtensions & OnRegisterLayoutExtensions ()
FOnRegisterTabs & OnRegisterTabsForEditor ()
virtual FDelegateHandle RegisterFunctionCustomization (TSubclassOf< UK2Node_EditablePinBase > InFieldClass, FOnGetFunctionCustomizationInstance InOnGetFunctionCustomization)
Register a customization for for Blueprint functions.
virtual void RegisterGraphCustomization (const UEdGraphSchema *InGraphSchema, FOnGetGraphCustomizationInstance InOnGetGraphCustomization)
Register a customization for for Blueprint graphs.
virtual FDelegateHandle RegisterLocalVariableCustomization (FFieldClass *InFieldClass, FOnGetLocalVariableCustomizationInstance InOnGetLocalVariableCustomization)
Register a customization for for Blueprint local variables.
virtual void RegisterSCSEditorCustomization (const FName &InComponentName, FSCSEditorCustomizationBuilder InCustomizationBuilder)
Register a customization for interacting with the SCS editor.
virtual FDelegateHandle RegisterVariableCustomization (FFieldClass *InFieldClass, FOnGetVariableCustomizationInstance InOnGetVariableCustomization)
Register a customization for for Blueprint variables.
virtual void SetDetailsCustomization (TSharedPtr< class FDetailsViewObjectFilter > InDetailsObjectFilter, TSharedPtr< class IDetailRootObjectCustomization > InDetailsRootCustomization)
Sets customizations for the BP editor details panel.
virtual void SetSubobjectEditorUICustomization (TSharedPtr< class ISCSEditorUICustomization > InSCSEditorUICustomization)
Sets SCS editor UI customization.
virtual void ShutdownModule () override
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule () override
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
UE_DEPRECATED (5.1, "UnregisterLocalVariableCustomization without a delegate handle is deprecated.") virtual void UnregisterLocalVariableCustomization(FFieldClass *InFieldClass)
Unregister a previously registered customization for BP local variables.
UE_DEPRECATED (5.1, "UnregisterVariableCustomization without a delegate handle is deprecated.") virtual void UnregisterVariableCustomization(FFieldClass *InFieldClass)
Unregister a previously registered customization for BP variables.
virtual void UnregisterFunctionCustomization (TSubclassOf< UK2Node_EditablePinBase > InFieldClass, FDelegateHandle InHandle)
Unregister a previously registered customization for BP functions.
virtual void UnregisterGraphCustomization (const UEdGraphSchema *InGraphSchema)
Unregister a previously registered customization for BP graphs.
virtual void UnregisterLocalVariableCustomization (FFieldClass *InFieldClass, FDelegateHandle InHandle)
Unregister a previously registered customization for BP local variables.
virtual void UnregisterSCSEditorCustomization (const FName &InComponentName)
Unregister a previously registered customization for interacting with the SCS editor.
virtual void UnregisterVariableCustomization (FFieldClass *InFieldClass, FDelegateHandle InHandle)
Unregister a previously registered customization for BP variables.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Private Member Functions
void PrepareAutoGeneratedDefaultEvents ()
Loads from ini a list of all events that should be auto created for Blueprints of a specific class.
Private Attributes
TUniquePtr< FBlueprintDebugger > BlueprintDebugger
Blueprint debugger state - refactor into SBlueprintDebugger if needed.
FBlueprintEditorOpenedEvent BlueprintEditorOpened
TArray< TWeakPtr< FBlueprintEditor > > BlueprintEditors
List of all blueprint editors that were created.
TSharedPtr< SWidget > ConfigurationPanel
Reference to keep our custom configuration panel alive.
TSharedPtr< class FDetailsViewObjectFilter > DetailsObjectFilter
Filter used to determine the set of objects shown in the BP editor details panel.
TSharedPtr< class IDetailRootObjectCustomization > DetailsRootCustomization
Root customization for the BP editor details panel.
TMultiMap< TSubclassOf< UK2Node_EditablePinBase >, FOnGetFunctionCustomizationInstance > FunctionCustomizations
Customizations for Blueprint functions.
FBlueprintMenuExtensionEvent GatherBlueprintMenuExtensions
TMap< const UEdGraphSchema *, FOnGetGraphCustomizationInstance > GraphCustomizations
Customizations for Blueprint graphs.
FDelegateHandle LevelViewportContextMenuBlueprintExtenderDelegateHandle
Handle to a registered LevelViewportContextMenuBlueprintExtender delegate.
TMultiMap< FFieldClass *, FOnGetLocalVariableCustomizationInstance > LocalVariableCustomizations
Customizations for Blueprint local variables.
TSharedPtr< FExtensibilityManager > MenuExtensibilityManager
FOnRegisterLayoutExtensions RegisterLayoutExtensions
FOnRegisterTabs RegisterTabsForEditor
Event called to allow external clients to register additional tabs for the specified editor.
TMap< FName, FSCSEditorCustomizationBuilder > SCSEditorCustomizations
Customizations for the SCS editor.
TSharedPtr< class ISCSEditorUICustomization > SCSEditorUICustomization
UI customizations for the SCS editor inside the blueprint editor.
TSharedPtr< FUICommandList > SharedBlueprintEditorCommands
A command list that can be passed around and isn't bound to an instance of the blueprint editor.
TMultiMap< FFieldClass *, FOnGetVariableCustomizationInstance > VariableCustomizations
Customizations for Blueprint variables.
Detailed Description
The blueprint editor module provides the blueprint editor application.
Definition at line 163 of file BlueprintEditorModule.h.
Member Function Documentation
CreateBlueprintEditor() [1/2]
virtual TSharedRef< IBlueprintEditor > FBlueprintEditorModule::CreateBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, const TArray< UBlueprint * > & BlueprintsToEdit, bool bShouldOpenInDefaultsMode = true) virtual
CreateBlueprintEditor() [2/2]
virtual TSharedRef< IBlueprintEditor > FBlueprintEditorModule::CreateBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, UBlueprint * Blueprint, bool bShouldOpenInDefaultsMode = false) virtual
Creates an instance of a Kismet editor object.
Only virtual so that it can be called across the DLL boundary.
Note: This function should not be called directly, use one of the following instead:
FKismetEditorUtilities::BringKismetToFocusAttentionOnObject
GEditor->GetEditorSubsystem<UAssetEditorSubsystem>()->OpenEditorForAsset
Parameters
Mode Mode that this editor should operate in
InitToolkitHost When Mode is WorldCentric, this is the level editor instance to spawn this editor within
Blueprint The blueprint object to start editing
bShouldOpenInDefaultsMode If true, the editor will open in defaults editing mode
Returns
Interface to the new Blueprint editor
CreateUserDefinedEnumEditor()
virtual TSharedRef< IUserDefinedEnumEditor > FBlueprintEditorModule::CreateUserDefinedEnumEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, UUserDefinedEnum * UDEnum) virtual
Creates an instance of a Enum editor object.
Parameters
Mode Mode that this editor should operate in
InitToolkitHost When Mode is WorldCentric, this is the level editor instance to spawn this editor within
UDEnum The user-defined Enum to start editing
Returns
Interface to the new Enum editor
CreateUserDefinedStructEditor()
virtual TSharedRef< IUserDefinedStructureEditor > FBlueprintEditorModule::CreateUserDefinedStructEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > & InitToolkitHost, UUserDefinedStruct * UDStruct) virtual
Creates an instance of a Structure editor object.
Parameters
Mode Mode that this editor should operate in
InitToolkitHost When Mode is WorldCentric, this is the level editor instance to spawn this editor within
UDEnum The user-defined structure to start editing
Returns
Interface to the new Struct editor
CustomizeFunction()
virtual TArray< TSharedPtr< IDetailCustomization > > FBlueprintEditorModule::CustomizeFunction (TSubclassOf< UK2Node_EditablePinBase > InFunctionClass, TSharedPtr< IBlueprintEditor > InBlueprintEditor) virtual
Build a set of details customizations for function with the passed-in type, if possible.
Parameters
InFunctionClass The type to create the customization for
InBlueprintEditor The Blueprint Editor the customization will be created for
References CustomizeFunction().
Referenced by CustomizeFunction().
CustomizeGraph()
virtual TArray< TSharedPtr< IDetailCustomization > > FBlueprintEditorModule::CustomizeGraph (const UEdGraphSchema * InGraphSchema, TSharedPtr< IBlueprintEditor > InBlueprintEditor) virtual
Build a set of details customizations for graphs with the passed-in schema, if possible.
Parameters
InGraphSchema The schema to create the customization for
InBlueprintEditor The Blueprint Editor the customization will be created for
References CustomizeGraph().
Referenced by CustomizeGraph().
CustomizeVariable()
virtual TArray< TSharedPtr< IDetailCustomization > > FBlueprintEditorModule::CustomizeVariable (FFieldClass * InFieldClass, TSharedPtr< IBlueprintEditor > InBlueprintEditor) virtual
Build a set of details customizations for the passed-in type, if possible.
Parameters
InStruct The type to create the customization for
InBlueprintEditor The Blueprint Editor the customization will be created for
References CustomizeVariable().
Referenced by CustomizeVariable().
DECLARE_EVENT_OneParam() [1/2]
FBlueprintEditorModule::DECLARE_EVENT_OneParam (FBlueprintEditorModule , FBlueprintEditorOpenedEvent , EBlueprintType)
Delegate for binding functions to be called when the blueprint editor finishes getting created.
References DECLARE_EVENT_OneParam().
DECLARE_EVENT_OneParam() [2/2]
FBlueprintEditorModule::DECLARE_EVENT_OneParam (IBlueprintEditor , FOnRegisterLayoutExtensions , FLayoutExtender &)
Referenced by DECLARE_EVENT_OneParam().
DECLARE_EVENT_ThreeParams()
FBlueprintEditorModule::DECLARE_EVENT_ThreeParams (IBlueprintEditor , FOnRegisterTabs , FWorkflowAllowedTabSet & , FName , TSharedPtr< FBlueprintEditor >)
DECLARE_EVENT_TwoParams()
FBlueprintEditorModule::DECLARE_EVENT_TwoParams (FBlueprintEditorModule , FBlueprintMenuExtensionEvent , TSharedPtr< FExtender > , UBlueprint *)
GetBlueprintDebugger()
const TUniquePtr< FBlueprintDebugger > & FBlueprintEditorModule::GetBlueprintDebugger () const inline
Returns a reference to the Blueprint Debugger state object.
Definition at line 349 of file BlueprintEditorModule.h.
References BlueprintDebugger.
GetBlueprintEditors()
virtual TArray< TSharedRef< IBlueprintEditor > > FBlueprintEditorModule::GetBlueprintEditors () const virtual
Get all blueprint editor instances.
GetMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > FBlueprintEditorModule::GetMenuExtensibilityManager () inline override virtual
Gets the extensibility managers for outside entities to extend blueprint editor's menus and toolbars.
Implements IHasMenuExtensibility.
Definition at line 215 of file BlueprintEditorModule.h.
References MenuExtensibilityManager.
GetsSharedBlueprintEditorCommands()
virtual const TSharedRef< FUICommandList > FBlueprintEditorModule::GetsSharedBlueprintEditorCommands () const inline virtual
Exposes a way for other modules to fold in their own Blueprint editor commands (folded in with other BP editor commands, when the editor is first opened).
Definition at line 346 of file BlueprintEditorModule.h.
References SharedBlueprintEditorCommands.
OnBlueprintEditorOpened()
FBlueprintEditorOpenedEvent & FBlueprintEditorModule::OnBlueprintEditorOpened () inline
Definition at line 339 of file BlueprintEditorModule.h.
References BlueprintEditorOpened, and OnBlueprintEditorOpened().
Referenced by OnBlueprintEditorOpened().
OnGatherBlueprintMenuExtensions()
FBlueprintMenuExtensionEvent & FBlueprintEditorModule::OnGatherBlueprintMenuExtensions () inline
Definition at line 219 of file BlueprintEditorModule.h.
References GatherBlueprintMenuExtensions.
OnRegisterLayoutExtensions()
FOnRegisterLayoutExtensions & FBlueprintEditorModule::OnRegisterLayoutExtensions () inline
Definition at line 225 of file BlueprintEditorModule.h.
References RegisterLayoutExtensions.
OnRegisterTabsForEditor()
FOnRegisterTabs & FBlueprintEditorModule::OnRegisterTabsForEditor () inline
Definition at line 222 of file BlueprintEditorModule.h.
References RegisterTabsForEditor.
PrepareAutoGeneratedDefaultEvents()
void FBlueprintEditorModule::PrepareAutoGeneratedDefaultEvents () private
Loads from ini a list of all events that should be auto created for Blueprints of a specific class.
RegisterFunctionCustomization()
virtual FDelegateHandle FBlueprintEditorModule::RegisterFunctionCustomization (TSubclassOf< UK2Node_EditablePinBase > InFieldClass, FOnGetFunctionCustomizationInstance InOnGetFunctionCustomization) virtual
Register a customization for for Blueprint functions.
Parameters
InStruct The type of the pin to create the customization for
InOnGetFunctionCustomization The delegate used to create customization instances
References RegisterFunctionCustomization().
Referenced by RegisterFunctionCustomization().
RegisterGraphCustomization()
virtual void FBlueprintEditorModule::RegisterGraphCustomization (const UEdGraphSchema * InGraphSchema, FOnGetGraphCustomizationInstance InOnGetGraphCustomization) virtual
Register a customization for for Blueprint graphs.
Parameters
InGraphSchema The schema of the graph to create the customization for
InOnGetDetailCustomization The delegate used to create customization instances
References RegisterGraphCustomization().
Referenced by RegisterGraphCustomization().
RegisterLocalVariableCustomization()
virtual FDelegateHandle FBlueprintEditorModule::RegisterLocalVariableCustomization (FFieldClass * InFieldClass, FOnGetLocalVariableCustomizationInstance InOnGetLocalVariableCustomization) virtual
Register a customization for for Blueprint local variables.
Parameters
InFieldClass The type of the variable to create the customization for
InOnGetLocalVariableCustomization The delegate used to create customization instances
References RegisterLocalVariableCustomization().
Referenced by RegisterLocalVariableCustomization().
RegisterSCSEditorCustomization()
virtual void FBlueprintEditorModule::RegisterSCSEditorCustomization (const FName & InComponentName, FSCSEditorCustomizationBuilder InCustomizationBuilder) virtual
Register a customization for interacting with the SCS editor.
Parameters
InComponentName The name of the component to customize behavior for
InCustomizationBuilder The delegate used to create customization instances
RegisterVariableCustomization()
virtual FDelegateHandle FBlueprintEditorModule::RegisterVariableCustomization (FFieldClass * InFieldClass, FOnGetVariableCustomizationInstance InOnGetVariableCustomization) virtual
Register a customization for for Blueprint variables.
Parameters
InStruct The type of the variable to create the customization for
InOnGetDetailCustomization The delegate used to create customization instances
SetDetailsCustomization()
virtual void FBlueprintEditorModule::SetDetailsCustomization (TSharedPtr< class FDetailsViewObjectFilter > InDetailsObjectFilter, TSharedPtr< class IDetailRootObjectCustomization > InDetailsRootCustomization) virtual
Sets customizations for the BP editor details panel.
SetSubobjectEditorUICustomization()
virtual void FBlueprintEditorModule::SetSubobjectEditorUICustomization (TSharedPtr< class ISCSEditorUICustomization > InSCSEditorUICustomization) virtual
Sets SCS editor UI customization.
ShutdownModule()
virtual void FBlueprintEditorModule::ShutdownModule () override virtual
Called before the module is unloaded, right before the module object is destroyed.
During normal shutdown, this is called in reverse order that modules finish StartupModule(). This means that, as long as a module references dependent modules in it's StartupModule(), it can safely reference those dependencies in ShutdownModule() as well.
Reimplemented from IModuleInterface.
StartupModule()
virtual void FBlueprintEditorModule::StartupModule () override virtual
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
ie:
FModuleManager::Get().LoadModuleChecked(TEXT("HTTP"));
Reimplemented from IModuleInterface.
UE_DEPRECATED() [1/2]
FBlueprintEditorModule::UE_DEPRECATED (5. 1, "UnregisterLocalVariableCustomization without a delegate handle is deprecated.")
Unregister a previously registered customization for BP local variables.
Parameters
InFieldClass The type to create the customization for
References UE_DEPRECATED(), and UnregisterLocalVariableCustomization().
UE_DEPRECATED() [2/2]
FBlueprintEditorModule::UE_DEPRECATED (5. 1, "UnregisterVariableCustomization without a delegate handle is deprecated.")
Unregister a previously registered customization for BP variables.
Parameters
InStruct The type to create the customization for
References UnregisterVariableCustomization().
Referenced by UE_DEPRECATED().
UnregisterFunctionCustomization()
virtual void FBlueprintEditorModule::UnregisterFunctionCustomization (TSubclassOf< UK2Node_EditablePinBase > InFieldClass, FDelegateHandle InHandle) virtual
Unregister a previously registered customization for BP functions.
Parameters
InStruct The type to create the customization for
InHandle The handle returned by UnregisterFunctionCustomization
References UnregisterFunctionCustomization().
Referenced by UnregisterFunctionCustomization().
UnregisterGraphCustomization()
virtual void FBlueprintEditorModule::UnregisterGraphCustomization (const UEdGraphSchema * InGraphSchema) virtual
Unregister a previously registered customization for BP graphs.
Parameters
InGraphSchema The schema of the graph to create the customization for
References UnregisterGraphCustomization().
Referenced by UnregisterGraphCustomization().
UnregisterLocalVariableCustomization()
virtual void FBlueprintEditorModule::UnregisterLocalVariableCustomization (FFieldClass * InFieldClass, FDelegateHandle InHandle) virtual
Unregister a previously registered customization for BP local variables.
Parameters
InFieldClass The type to create the customization for
InHandle The handle returned by RegisterLocalVariableCustomization
References UnregisterLocalVariableCustomization().
Referenced by UE_DEPRECATED(), and UnregisterLocalVariableCustomization().
UnregisterSCSEditorCustomization()
virtual void FBlueprintEditorModule::UnregisterSCSEditorCustomization (const FName & InComponentName) virtual
Unregister a previously registered customization for interacting with the SCS editor.
Parameters
InComponentName The name of the component to customize behavior for
UnregisterVariableCustomization()
virtual void FBlueprintEditorModule::UnregisterVariableCustomization (FFieldClass * InFieldClass, FDelegateHandle InHandle) virtual
Unregister a previously registered customization for BP variables.
Parameters
InStruct The type to create the customization for
InHandle The handle returned by RegisterVariableCustomization
References UnregisterVariableCustomization().
Referenced by UE_DEPRECATED(), and UnregisterVariableCustomization().
Field Documentation
BlueprintDebugger
TUniquePtr<FBlueprintDebugger> FBlueprintEditorModule::BlueprintDebugger private
Blueprint debugger state - refactor into SBlueprintDebugger if needed.
Definition at line 408 of file BlueprintEditorModule.h.
Referenced by GetBlueprintDebugger().
BlueprintEditorOpened
FBlueprintEditorOpenedEvent FBlueprintEditorModule::BlueprintEditorOpened private
Definition at line 369 of file BlueprintEditorModule.h.
Referenced by OnBlueprintEditorOpened().
BlueprintEditors
TArray<TWeakPtr<FBlueprintEditor> > FBlueprintEditorModule::BlueprintEditors private
List of all blueprint editors that were created.
Definition at line 357 of file BlueprintEditorModule.h.
ConfigurationPanel
TSharedPtr<SWidget> FBlueprintEditorModule::ConfigurationPanel private
Reference to keep our custom configuration panel alive.
Definition at line 405 of file BlueprintEditorModule.h.
DetailsObjectFilter
TSharedPtr<class FDetailsViewObjectFilter> FBlueprintEditorModule::DetailsObjectFilter private
Filter used to determine the set of objects shown in the BP editor details panel.
Definition at line 390 of file BlueprintEditorModule.h.
DetailsRootCustomization
TSharedPtr<class IDetailRootObjectCustomization> FBlueprintEditorModule::DetailsRootCustomization private
Root customization for the BP editor details panel.
Definition at line 387 of file BlueprintEditorModule.h.
FunctionCustomizations
TMultiMap<TSubclassOf<UK2Node_EditablePinBase>, FOnGetFunctionCustomizationInstance> FBlueprintEditorModule::FunctionCustomizations private
Customizations for Blueprint functions.
Definition at line 384 of file BlueprintEditorModule.h.
GatherBlueprintMenuExtensions
FBlueprintMenuExtensionEvent FBlueprintEditorModule::GatherBlueprintMenuExtensions private
Definition at line 362 of file BlueprintEditorModule.h.
Referenced by OnGatherBlueprintMenuExtensions().
GraphCustomizations
TMap<const UEdGraphSchema*, FOnGetGraphCustomizationInstance> FBlueprintEditorModule::GraphCustomizations private
Customizations for Blueprint graphs.
Definition at line 381 of file BlueprintEditorModule.h.
LevelViewportContextMenuBlueprintExtenderDelegateHandle
FDelegateHandle FBlueprintEditorModule::LevelViewportContextMenuBlueprintExtenderDelegateHandle private
Handle to a registered LevelViewportContextMenuBlueprintExtender delegate.
Definition at line 402 of file BlueprintEditorModule.h.
LocalVariableCustomizations
TMultiMap<FFieldClass*, FOnGetLocalVariableCustomizationInstance> FBlueprintEditorModule::LocalVariableCustomizations private
Customizations for Blueprint local variables.
Definition at line 378 of file BlueprintEditorModule.h.
MenuExtensibilityManager
TSharedPtr<FExtensibilityManager> FBlueprintEditorModule::MenuExtensibilityManager private
Definition at line 359 of file BlueprintEditorModule.h.
Referenced by GetMenuExtensibilityManager().
RegisterLayoutExtensions
FOnRegisterLayoutExtensions FBlueprintEditorModule::RegisterLayoutExtensions private
Definition at line 366 of file BlueprintEditorModule.h.
Referenced by OnRegisterLayoutExtensions().
RegisterTabsForEditor
FOnRegisterTabs FBlueprintEditorModule::RegisterTabsForEditor private
Event called to allow external clients to register additional tabs for the specified editor.
Definition at line 365 of file BlueprintEditorModule.h.
Referenced by OnRegisterTabsForEditor().
SCSEditorCustomizations
TMap<FName, FSCSEditorCustomizationBuilder> FBlueprintEditorModule::SCSEditorCustomizations private
Customizations for the SCS editor.
Definition at line 372 of file BlueprintEditorModule.h.
SCSEditorUICustomization
TSharedPtr<class ISCSEditorUICustomization> FBlueprintEditorModule::SCSEditorUICustomization private
UI customizations for the SCS editor inside the blueprint editor.
Definition at line 393 of file BlueprintEditorModule.h.
SharedBlueprintEditorCommands
TSharedPtr<FUICommandList> FBlueprintEditorModule::SharedBlueprintEditorCommands private
A command list that can be passed around and isn't bound to an instance of the blueprint editor.
Definition at line 399 of file BlueprintEditorModule.h.
Referenced by GetsSharedBlueprintEditorCommands().
VariableCustomizations
TMultiMap<FFieldClass*, FOnGetVariableCustomizationInstance> FBlueprintEditorModule::VariableCustomizations private
Customizations for Blueprint variables.
Definition at line 375 of file BlueprintEditorModule.h.
The documentation for this class was generated from the following file:
BlueprintEditorModule.h