Unreal Engine 5.6 C++ API: FThreadSafeBool Class Reference
FThreadSafeBool Class Reference
Thread safe bool, wraps FThreadSafeCounter.
#include "ThreadSafeBool.h"
Public Member Functions
FThreadSafeBool (bool bValue=false)
Constructor optionally takes value to initialize with, otherwise initializes false.
FORCEINLINE bool AtomicSet (bool bNewValue)
Sets a new value atomically, and returns the old value.
FORCEINLINE operator bool () const
Operator to use this struct as a bool with thread safety.
FORCEINLINE bool operator= (bool bNewValue)
Operator to set the bool value with thread safety.
Additional Inherited Members
Private Types inherited from FThreadSafeCounter
using IntegerType = int32
Private Member Functions inherited from FThreadSafeCounter
FThreadSafeCounter (const FThreadSafeCounter &Other)
Copy Constructor.
FThreadSafeCounter (int32 Value=0)
Constructor, initializing counter to passed in value.
int32 Add (int32 Amount)
Adds an amount and returns the old value.
int32 Decrement ()
Decrement and return new value.
int32 GetValue () const
Gets the current value.
int32 Increment ()
Increment and return new value.
int32 Reset ()
Resets the counter's value to zero.
int32 Set (int32 Value)
Sets the counter to a specific value and returns the old value.
int32 Subtract (int32 Amount)
Subtracts an amount and returns the old value.
Detailed Description
Thread safe bool, wraps FThreadSafeCounter.
Definition at line 15 of file ThreadSafeBool.h.
Constructor & Destructor Documentation
FThreadSafeBool()
FThreadSafeBool::FThreadSafeBool (bool bValue = false) inline
Constructor optionally takes value to initialize with, otherwise initializes false.
Parameters
bValue Value to initialize with
Definition at line 23 of file ThreadSafeBool.h.
References FThreadSafeCounter::FThreadSafeCounter().
Member Function Documentation
AtomicSet()
FORCEINLINE bool FThreadSafeBool::AtomicSet (bool bNewValue) inline
Sets a new value atomically, and returns the old value.
Parameters
bNewValue Value to set
Returns
The old value
Definition at line 50 of file ThreadSafeBool.h.
References FORCEINLINE, and FThreadSafeCounter::Set().
operator bool()
FORCEINLINE FThreadSafeBool::operator bool () const inline
Operator to use this struct as a bool with thread safety.
Definition at line 30 of file ThreadSafeBool.h.
References FORCEINLINE, and FThreadSafeCounter::GetValue().
operator=()
FORCEINLINE bool FThreadSafeBool::operator= (bool bNewValue) inline
Operator to set the bool value with thread safety.
Definition at line 38 of file ThreadSafeBool.h.
References FORCEINLINE, and FThreadSafeCounter::Set().
The documentation for this class was generated from the following file:
ThreadSafeBool.h