Unreal Engine 5.6 C++ API: UE::Insights::FTableCellValueFormatter Class Reference
UE::Insights::FTableCellValueFormatter Class Reference
#include "TableCellValueFormatter.h"
Public Member Functions
FTableCellValueFormatter ()
virtual ~FTableCellValueFormatter ()
virtual FText CopyTooltip (const FTableColumn &Column, const FBaseTreeNode &Node) const override
virtual FText CopyValue (const FTableColumn &Column, const FBaseTreeNode &Node) const override
virtual FText FormatValue (const FTableColumn &Column, const FBaseTreeNode &Node) const override
virtual FText FormatValue (const TOptional< FTableCellValue > &InValue) const override
virtual FText FormatValueForGrouping (const FTableColumn &Column, const FBaseTreeNode &Node) const override
virtual FText FormatValueForTooltip (const FTableColumn &Column, const FBaseTreeNode &Node) const override
virtual FText FormatValueForTooltip (const TOptional< FTableCellValue > &InValue) const override
virtual TSharedPtr< SWidget > GenerateCustomWidget (const FTableColumn &Column, const FBaseTreeNode &Node) const override
virtual TSharedPtr< IToolTip > GetCustomTooltip (const FTableColumn &Column, const FBaseTreeNode &Node) const override
Static Public Member Functions
static EVisibility GetTooltipVisibility ()
Detailed Description
Definition at line 42 of file TableCellValueFormatter.h.
Constructor & Destructor Documentation
FTableCellValueFormatter()
UE::Insights::FTableCellValueFormatter::FTableCellValueFormatter () inline
Definition at line 45 of file TableCellValueFormatter.h.
~FTableCellValueFormatter()
virtual UE::Insights::FTableCellValueFormatter::~FTableCellValueFormatter () inline virtual
Definition at line 46 of file TableCellValueFormatter.h.
Member Function Documentation
CopyTooltip()
virtual FText UE::Insights::FTableCellValueFormatter::CopyTooltip (const FTableColumn & Column, const FBaseTreeNode & Node) const override virtual
Implements UE::Insights::ITableCellValueFormatter.
CopyValue()
virtual FText UE::Insights::FTableCellValueFormatter::CopyValue (const FTableColumn & Column, const FBaseTreeNode & Node) const override virtual
Implements UE::Insights::ITableCellValueFormatter.
FormatValue() [1/2]
virtual FText UE::Insights::FTableCellValueFormatter::FormatValue (const FTableColumn & Column, const FBaseTreeNode & Node) const override virtual
Implements UE::Insights::ITableCellValueFormatter.
FormatValue() [2/2]
virtual FText UE::Insights::FTableCellValueFormatter::FormatValue (const TOptional< FTableCellValue > & InValue) const inline override virtual
Implements UE::Insights::ITableCellValueFormatter.
Reimplemented in UE::Insights::FAsTextValueFormatter, UE::Insights::FBoolValueFormatterAsOnOff, UE::Insights::FBoolValueFormatterAsTrueFalse, UE::Insights::FCStringValueFormatterAsText, UE::Insights::FDoubleValueFormatterAsNumber, UE::Insights::FDoubleValueFormatterAsTimeAuto, UE::Insights::FDoubleValueFormatterAsTimeMs, UE::Insights::FFloatValueFormatterAsNumber, UE::Insights::FFloatValueFormatterAsTimeAuto, UE::Insights::FInt64ValueFormatterAsHex32, UE::Insights::FInt64ValueFormatterAsHex64, UE::Insights::FInt64ValueFormatterAsMemory, UE::Insights::FInt64ValueFormatterAsNumber, UE::Insights::FInt64ValueFormatterAsUInt32InfinteNumber, and UE::Insights::FTextValueFormatter.
Definition at line 48 of file TableCellValueFormatter.h.
References FText::GetEmpty().
Referenced by FormatValueForTooltip().
FormatValueForGrouping()
virtual FText UE::Insights::FTableCellValueFormatter::FormatValueForGrouping (const FTableColumn & Column, const FBaseTreeNode & Node) const override virtual
Implements UE::Insights::ITableCellValueFormatter.
FormatValueForTooltip() [1/2]
virtual FText UE::Insights::FTableCellValueFormatter::FormatValueForTooltip (const FTableColumn & Column, const FBaseTreeNode & Node) const override virtual
Implements UE::Insights::ITableCellValueFormatter.
FormatValueForTooltip() [2/2]
virtual FText UE::Insights::FTableCellValueFormatter::FormatValueForTooltip (const TOptional< FTableCellValue > & InValue) const inline override virtual
Implements UE::Insights::ITableCellValueFormatter.
Reimplemented in UE::Insights::FDoubleValueFormatterAsTimeAuto, UE::Insights::FDoubleValueFormatterAsTimeMs, UE::Insights::FFloatValueFormatterAsTimeAuto, UE::Insights::FInt64ValueFormatterAsMemory, and UE::Insights::FInt64ValueFormatterAsUInt32InfinteNumber.
Definition at line 49 of file TableCellValueFormatter.h.
References FormatValue().
GenerateCustomWidget()
virtual TSharedPtr< SWidget > UE::Insights::FTableCellValueFormatter::GenerateCustomWidget (const FTableColumn & Column, const FBaseTreeNode & Node) const inline override virtual
Implements UE::Insights::ITableCellValueFormatter.
Definition at line 58 of file TableCellValueFormatter.h.
GetCustomTooltip()
virtual TSharedPtr< IToolTip > UE::Insights::FTableCellValueFormatter::GetCustomTooltip (const FTableColumn & Column, const FBaseTreeNode & Node) const override virtual
Implements UE::Insights::ITableCellValueFormatter.
GetTooltipVisibility()
EVisibility UE::Insights::FTableCellValueFormatter::GetTooltipVisibility () static
The documentation for this class was generated from the following file:
TableCellValueFormatter.h