Unreal Engine 5.6 C++ API: UE::Geometry::FNormalFlowRemesher Class Reference
UE::Geometry::FNormalFlowRemesher Class Reference
Remeshing with "face aligned projection".
#include "NormalFlowRemesher.h"
Public Member Functions
FNormalFlowRemesher (FDynamicMesh3 *MeshIn)
void BasicRemeshPass () override
"Outer loop" for all remeshing operations
Public Member Functions inherited from UE::Geometry::FQueueRemesher
FQueueRemesher (FDynamicMesh3 *MeshIn)
void BasicRemeshPass () override
"Outer loop" for all remeshing operations
DYNAMICMESH_API void FastestRemesh ()
Converge on remeshed result as quickly as possible.
Public Member Functions inherited from UE::Geometry::FRemesher
FRemesher (FDynamicMesh3 *MeshIn)
virtual ~FRemesher ()
virtual void OnEdgeCollapse (int EdgeID, int VertexA, int VertexB, const FDynamicMesh3::FEdgeCollapseInfo &CollapseInfo)
Callback for subclasses to override to implement custom behavior.
virtual void OnEdgeFlip (int EdgeID, const FDynamicMesh3::FEdgeFlipInfo &FlipInfo)
Callback for subclasses to override to implement custom behavior.
virtual DYNAMICMESH_API void Precompute ()
We can speed things up if we precompute some invariants.
DYNAMICMESH_API void SetTargetEdgeLength (double fLength)
Set min/max edge-lengths to sane values for given target edge length.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBase
FMeshRefinerBase (const FMeshRefinerBase &)=delete
FMeshRefinerBase (FMeshRefinerBase &&)=delete
virtual ~FMeshRefinerBase ()
virtual bool Cancelled ()
If this returns true, abort computation.
const TOptional< FMeshConstraints > & GetConstraints ()
Get the current mesh constraints.
double GetEdgeFlipTolerance ()
FDynamicMesh3 * GetMesh ()
Get the current mesh we are operating on.
FMeshRefinerBase & operator= (const FMeshRefinerBase &)=delete
FMeshRefinerBase & operator= (FMeshRefinerBase &&)=delete
IProjectionTarget * ProjectionTarget ()
Get the current Projection Target.
void SetEdgeFlipTolerance (double NewTolerance)
Set edge flip tolerance.
void SetExternalConstraints (TOptional< FMeshConstraints > ConstraintsIn)
Set external constraints.
DYNAMICMESH_API void SetMeshChangeTracker (FDynamicMeshChangeTracker *Tracker)
void SetProjectionTarget (IProjectionTarget *TargetIn)
Set a Projection Target.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBaseFixLayout
virtual ~FMeshRefinerBaseFixLayout ()=default
Data Fields
bool bEnableParallelEdgeFlipPass = true
Gather candidates for edge flipping in parallel, then do the actual flips sequentially.
bool bSmoothInFillAreas = true
Control whether or not we want to apply mesh smoothing in "free" areas that have not projected to target surface.
int FaceProjectionPassesPerRemeshIteration = 1
During each call to RemeshIteration, do this many passes of face-aligned projection.
float FillAreaDistanceMultiplier = 0.25
This is used as a multiplier on MaxEdgeLength to determine when we identify points as being in "free" areas.
float FillAreaSmoothMultiplier = 0.25
This is used as a multiplier on the Remesher smoothing rate, applied to points identified as being in "free" areas.
int MaxTriangleCount = 0
cap on triangle count, to prevent runaway mesh messes. Ignored if zero.
double NormalAlignmentSpeed = 0.2
drag on normal alignment
int NumExtraProjectionIterations = 5
Additional projection iterations after the usual remesh step.
double SurfaceProjectionSpeed = 0.2
drag on surface projection
Data Fields inherited from UE::Geometry::FQueueRemesher
int MaxFastSplitIterations = 20
Max number of passes just doing edge splits.
int MaxRemeshIterations = 20
Max number of passes doing full remeshing operations.
double MinActiveEdgeFraction = 0.01
If fraction of active edges falls below this threshold, consider result converged and terminate before MaxRemeshIterations.
Data Fields inherited from UE::Geometry::FRemesher
bool bEnableCollapses = true
Controls whether edge collapses are allowed during remeshing pass.
bool bEnableFlips = true
Controls whether edge-flips are allowed during remeshing pass.
bool bEnableParallelProjection = true
enable parallel projection.
bool bEnableParallelSmooth = true
Enable parallel smoothing.
bool bEnableSmoothing = true
Controls whether vertex smoothing is applied during remeshing pass.
bool bEnableSmoothInPlace = false
If smoothing is done in-place, we don't need an extra buffer, but also there will some randomness introduced in results.
bool bEnableSplits = true
Controls whether edge splits are allowed during remeshing pass.
bool bPreventNormalFlips = false
Controls whether we try to prevent normal flips inside operations and smoothing.
bool bPreventTinyTriangles = false
Controls whether we disallow creation of triangles with small areas inside edge operations.
TFunction< double(const FDynamicMesh3 &Mesh, int VertexA, int VertexB)> CustomEdgeLengthScaleF
Scale the computed edge length to allow for adaptive remeshing.
TFunction< FVector3d(const FDynamicMesh3 &, int, double)> CustomSmoothF
Override default smoothing function.
TFunction< double(const FDynamicMesh3 &, int)> CustomSmoothSpeedF
Override constant SmoothSpeedT with function.
EFlipMetric FlipMetric = EFlipMetric::OptimalValence
Type of flip metric that will be applied.
double MaxEdgeLength = 3.0
Maximum target edge length.
double MinEdgeLength = 1.0
Minimum target edge length.
double MinLengthFlipThresh = 0.9
For MinEdgeLength metric, only flip if NewLength < (MinLengthFlipThresh * CurLength)
int ModifiedEdgesLastPass = 0
Number of edges that were modified in previous Remesh pass.
double SmoothSpeedT = 0.1
Smoothing speed, in range [0,1].
ESmoothTypes SmoothType = ESmoothTypes::Uniform
Type of smoothing that will be applied unless overridden by CustomSmoothF.
Data Fields inherited from UE::Geometry::FMeshRefinerBase
bool AllowCollapseFixedVertsWithSameSetID = true
If true, then when two Fixed vertices have the same non-invalid SetID, we treat them as not fixed and allow collapse.
int DEBUG_CHECK_LEVEL = 0
0 = no checking, 1 = check constraints each pass, 2 = and check validity each pass, 3 = and check validity after every mesh change (v slow but best for debugging)
TArray< int > DebugEdges
This is a debugging aid, will break to debugger if these edges are touched, in debug builds.
bool ENABLE_PROFILING = false
Set to true to profile various passes.
FProgressCancel * Progress = nullptr
Set this to be able to cancel running Remesher/Reducer.
ETargetProjectionMode ProjectionMode = ETargetProjectionMode::NoProjection
Method to use to project vertices onto target surface.
TFunction< EVertexControl(int)> VertexControlF = nullptr
This function allows client to specify fine-grained control over what happens to specific vertices.
Protected Member Functions
DYNAMICMESH_API bool EdgeFlipWouldReduceNormalError (int EdgeID, double BadEdgeErrorThreshold=0.01, double ImprovementRatioThreshold=0.75) const
Test to see if flipping an edge would improve "normal error".
void InitializeVertexBufferForFacePass ()
DYNAMICMESH_API void RemeshWithFaceProjection ()
DYNAMICMESH_API void TrackedEdgeFlipPass ()
Flip all edges for which EdgeFlipWouldReduceNormalError returns true.
DYNAMICMESH_API void TrackedFaceProjectionPass (double &MaxDistanceMoved, bool bIsTuningIteration)
DYNAMICMESH_API void TrackedFaceProjectionPass_Serial (double &MaxDistanceMoved, bool bIsTuningIteration)
void TrackedFullProjectionPass (bool bParallel) override
Protected Member Functions inherited from UE::Geometry::FQueueRemesher
DYNAMICMESH_API int FastSplitIteration ()
This pass only does edge splits and enqueues modified vertex neighborhoods.
virtual DYNAMICMESH_API void InitializeVertexBufferForPass ()
void OnEdgeSplit (int EdgeID, int VertexA, int VertexB, const FDynamicMesh3::FEdgeSplitInfo &SplitInfo) final
Callback for subclasses to override to implement custom behavior.
void PopState ()
void PushState ()
void QueueEdge (int eid)
void QueueOneRing (int vid)
DYNAMICMESH_API void RemeshIteration (TFunctionRef< bool(void)> EarlyTerminationCheck)
This pass does all edge operations plug smoothing and reprojection.
void ResetQueue ()
DYNAMICMESH_API void TrackedFullSmoothPass_Buffer (bool bParallel)
DYNAMICMESH_API void TrackedMoveVerticesParallel (TFunction< FVector3d(int, bool &)> NewVertexPosition)
Protected Member Functions inherited from UE::Geometry::FRemesher
FRemesher ()
virtual DYNAMICMESH_API void ApplyToProjectVertices (const TFunction< void(int)> &VertexProjectFunc)
virtual DYNAMICMESH_API void ApplyToSmoothVertices (const TFunction< void(int)> &VertexSmoothFunc)
virtual DYNAMICMESH_API void ApplyVertexBuffer (bool bParallel)
virtual DYNAMICMESH_API FVector3d ComputeSmoothedVertexPos (int VertexID, TFunction< FVector3d(const FDynamicMesh3 &, int, double)> SmoothFunc, bool &bModified)
bool EnableInlineProjection () const
virtual DYNAMICMESH_API void FullProjectionPass (bool bParallel)
virtual DYNAMICMESH_API void FullSmoothPass_Buffer (bool bParallel)
virtual int GetNextEdge (int CurEdgeID, bool &bDone)
virtual DYNAMICMESH_API FVector3d GetProjectedCollapsePosition (int VertexID, const FVector3d &vNewPos)
virtual DYNAMICMESH_API TFunction< FVector3d(const FDynamicMesh3 &, int, double)> GetSmoothFunction ()
DYNAMICMESH_API void MoveVerticesParallel (TFunction< FVector3d(int, bool &)> NewVertexPosition)
virtual DYNAMICMESH_API EProcessResult ProcessEdge (int edgeID)
virtual void ProfileBeginCollapse ()
virtual void ProfileBeginFlip ()
virtual void ProfileBeginOps ()
virtual void ProfileBeginPass ()
virtual void ProfileBeginProject ()
virtual void ProfileBeginSmooth ()
virtual void ProfileBeginSplit ()
virtual void ProfileEndCollapse ()
virtual void ProfileEndFlip ()
virtual void ProfileEndOps ()
virtual void ProfileEndPass ()
virtual void ProfileEndProject ()
virtual void ProfileEndSmooth ()
virtual void ProfileEndSplit ()
virtual DYNAMICMESH_API void ProjectVertex (int VertexID, IProjectionTarget *UseTarget)
virtual int StartEdges ()
virtual DYNAMICMESH_API void UpdateAfterSplit (int edgeID, int va, int vb, const FDynamicMesh3::FEdgeSplitInfo &splitInfo)
Protected Member Functions inherited from UE::Geometry::FMeshRefinerBase
FMeshRefinerBase ()
FMeshRefinerBase (FDynamicMesh3 *MeshIn)
DYNAMICMESH_API bool CanCollapseEdge (int eid, int a, int b, int c, int d, int tc, int td, int &collapse_to) const
Figure out if we can collapse edge eid=[a,b] under current constraint set.
DYNAMICMESH_API bool CanCollapseVertex (int eid, int a, int b, int &collapse_to) const
Resolve vertex constraints for collapsing edge eid=[a,b].
DYNAMICMESH_API bool CheckIfCollapseCreatesFlipOrInvalid (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a face-normal flip.
DYNAMICMESH_API bool CheckIfCollapseCreatesTinyTriangle (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a triangle with small area (either all vertices are close together, or in a sliver configuration) This only checks one-ring of vid, so you have to call it twice, with vid and vother reversed, to check both one-rings.
DYNAMICMESH_API bool CheckIfFlipCreatesTinyTriangle (int OriginalEdgeVertexA, int OriginalEdgeVertexB, int OppositeEdgeVertexC, int OppositeEdgeVertexD, int OriginalTriangleIndex) const
Check if edge flip might create a triangle with small area (either all vertices are close together, or in a sliver configuration)
DYNAMICMESH_API bool CheckIfFlipInvertsNormals (int a, int b, int c, int d, int t0) const
Check if edge flip might reverse normal direction.
double ComputeEdgeFlipMetric (const FVector3d &Direction0, const FVector3d &Direction1) const
DYNAMICMESH_API void DebugCheckUVSeamConstraints ()
DYNAMICMESH_API void DebugCheckVertexConstraints ()
virtual DYNAMICMESH_API void DoDebugChecks (bool bEndOfPass=false)
FVertexConstraint GetVertexConstraint (int VertexID)
bool GetVertexConstraint (int VertexID, FVertexConstraint &OutConstraint)
bool IsVertexPositionConstrained (int VertexID)
DYNAMICMESH_API void RuntimeDebugCheck (int EdgeID)
virtual DYNAMICMESH_API void SaveEdgeBeforeModify (int32 EdgeID)
virtual DYNAMICMESH_API void SaveTriangleBeforeModify (int32 TriangleID)
virtual DYNAMICMESH_API void SaveVertexTrianglesBeforeModify (int32 VertexID)
Protected Attributes
TArray< FVector3d > ProjectionVertexBuffer
TArray< double > ProjectionWeightBuffer
TArray< double > TempWeightBuffer
Protected Attributes inherited from UE::Geometry::FQueueRemesher
TSet< int > EdgeBuffer
TArray< bool > EdgeShouldBeQueuedBuffer
TOptional< TSet< int > > ModifiedEdges
TFunction< void(int, int, int, int)> PostEdgeSplitFunction
SettingState SavedState
Protected Attributes inherited from UE::Geometry::FRemesher
bool bMeshIsClosed = false
we can avoid some checks/etc if we know that the mesh has no boundary edges.
int COUNT_COLLAPSES
int COUNT_FLIPS
int COUNT_SPLITS
uint64 MaxEdgeID = 0
TArray< bool > TempFlagBuffer
TDynamicVector< FVector3d > TempPosBuffer
Protected Attributes inherited from UE::Geometry::FMeshRefinerBase
FDynamicMeshChangeTracker * ActiveChangeTracker = nullptr
TOptional< FMeshConstraints > Constraints
Constraints are used to control how certain edges and vertices can be modified.
double EdgeFlipTolerance = 0.0f
If normals dot product is less than this, we consider it a normal flip.
FDynamicMesh3 * Mesh = nullptr
Mesh that will be refined.
IProjectionTarget * ProjTarget = nullptr
Vertices can be projected onto this surface when they are modified.
double TinyTriangleThreshold = SMALL_NUMBER
Avoid creation of triangles smaller than this value.
Additional Inherited Members
Public Types inherited from UE::Geometry::FRemesher
enum class EFlipMetric { OptimalValence = 0 , MinEdgeLength = 1 }
Available Edge Flip metrics.
enum class ESmoothTypes { Uniform = 0 , Cotan = 1 , MeanValue = 2 }
Built-in Smoothing types.
Public Types inherited from UE::Geometry::FMeshRefinerBase
enum class ETargetProjectionMode : uint8 { NoProjection = 0 , AfterRefinement = 1 , Inline = 2 }
Options for projecting vertices onto target surface.
enum class EVertexControl : uint8 { AllowAll = 0 , NoSmooth = 1 , NoProject = 2 , NoMovement = NoSmooth | NoProject }
Protected Types inherited from UE::Geometry::FRemesher
enum class EProcessResult {
Ok_Collapsed , Ok_Flipped , Ok_Split , Ignored_EdgeIsFine ,
Ignored_EdgeIsFullyConstrained , Failed_OpNotSuccessful , Failed_NotAnEdge
}
Detailed Description
Remeshing with "face aligned projection".
This approach to projection attempts to preserve sharp features in the mesh by aligning triangle normals with normals from the original mesh during the projection pass. This class also performs a pass of edge flips aimed at further aligning triangle normals to their originals. This can be helpful in fixing the occasional single "bad edge" along a sequence of feature edges.
Definition at line 20 of file NormalFlowRemesher.h.
Constructor & Destructor Documentation
FNormalFlowRemesher()
UE::Geometry::FNormalFlowRemesher::FNormalFlowRemesher (FDynamicMesh3 * MeshIn) inline
Definition at line 24 of file NormalFlowRemesher.h.
References UE::Geometry::FQueueRemesher::FQueueRemesher().
Member Function Documentation
BasicRemeshPass()
void UE::Geometry::FNormalFlowRemesher::BasicRemeshPass () inline override virtual
"Outer loop" for all remeshing operations
Reimplemented from UE::Geometry::FRemesher.
Definition at line 52 of file NormalFlowRemesher.h.
References RemeshWithFaceProjection().
EdgeFlipWouldReduceNormalError()
DYNAMICMESH_API bool UE::Geometry::FNormalFlowRemesher::EdgeFlipWouldReduceNormalError (int EdgeID, double BadEdgeErrorThreshold = 0.01, double ImprovementRatioThreshold = 0.75) const protected
Test to see if flipping an edge would improve "normal error".
Normal error for a triangle is: 0.5 * (1.0 - TriangleNormal \cdot ProjectedNormal), where ProjectedNormal is the normal of the triangle returned by finding the closest point on ProjTarget. The normal error for an edge is the sum of errors for the edge's incident triangles.
Parameters
EdgeID Edge to consider.
BadEdgeErrorThreshold Only edges with this error or greater are candidates for flipping.
ImprovementRatioThreshold New edge must have error less than old edge error times this ratio.
Returns
True iff (CurrentEdgeError > BadEdgeErrorThreshold) and (NewEdgeError < ImprovementRatioThreshold * CurrentEdgeError)
References UE_API.
InitializeVertexBufferForFacePass()
void UE::Geometry::FNormalFlowRemesher::InitializeVertexBufferForFacePass () inline protected
Definition at line 100 of file NormalFlowRemesher.h.
References UE::Geometry::FQueueRemesher::InitializeVertexBufferForPass(), UE::Geometry::Mesh, ProjectionVertexBuffer, ProjectionWeightBuffer, and TempWeightBuffer.
RemeshWithFaceProjection()
DYNAMICMESH_API void UE::Geometry::FNormalFlowRemesher::RemeshWithFaceProjection () protected
References UE_API.
Referenced by BasicRemeshPass().
TrackedEdgeFlipPass()
DYNAMICMESH_API void UE::Geometry::FNormalFlowRemesher::TrackedEdgeFlipPass () protected
Flip all edges for which EdgeFlipWouldReduceNormalError returns true.
References UE_API.
TrackedFaceProjectionPass()
DYNAMICMESH_API void UE::Geometry::FNormalFlowRemesher::TrackedFaceProjectionPass (double & MaxDistanceMoved, bool bIsTuningIteration) protected
References UE_API.
Referenced by TrackedFullProjectionPass().
TrackedFaceProjectionPass_Serial()
DYNAMICMESH_API void UE::Geometry::FNormalFlowRemesher::TrackedFaceProjectionPass_Serial (double & MaxDistanceMoved, bool bIsTuningIteration) protected
References UE_API.
Referenced by TrackedFullProjectionPass().
TrackedFullProjectionPass()
void UE::Geometry::FNormalFlowRemesher::TrackedFullProjectionPass (bool bParallel) inline override protected virtual
Reimplemented from UE::Geometry::FQueueRemesher.
Definition at line 72 of file NormalFlowRemesher.h.
References FaceProjectionPassesPerRemeshIteration, TrackedFaceProjectionPass(), and TrackedFaceProjectionPass_Serial().
Field Documentation
bEnableParallelEdgeFlipPass
bool UE::Geometry::FNormalFlowRemesher::bEnableParallelEdgeFlipPass = true
Gather candidates for edge flipping in parallel, then do the actual flips sequentially.
Definition at line 58 of file NormalFlowRemesher.h.
bSmoothInFillAreas
bool UE::Geometry::FNormalFlowRemesher::bSmoothInFillAreas = true
Control whether or not we want to apply mesh smoothing in "free" areas that have not projected to target surface.
This smoothing is on applied in the ExtraProjections Iterations
Definition at line 40 of file NormalFlowRemesher.h.
FaceProjectionPassesPerRemeshIteration
int UE::Geometry::FNormalFlowRemesher::FaceProjectionPassesPerRemeshIteration = 1
During each call to RemeshIteration, do this many passes of face-aligned projection.
Definition at line 27 of file NormalFlowRemesher.h.
Referenced by TrackedFullProjectionPass().
FillAreaDistanceMultiplier
float UE::Geometry::FNormalFlowRemesher::FillAreaDistanceMultiplier = 0.25
This is used as a multiplier on MaxEdgeLength to determine when we identify points as being in "free" areas.
Definition at line 43 of file NormalFlowRemesher.h.
FillAreaSmoothMultiplier
float UE::Geometry::FNormalFlowRemesher::FillAreaSmoothMultiplier = 0.25
This is used as a multiplier on the Remesher smoothing rate, applied to points identified as being in "free" areas.
Definition at line 46 of file NormalFlowRemesher.h.
MaxTriangleCount
int UE::Geometry::FNormalFlowRemesher::MaxTriangleCount = 0
cap on triangle count, to prevent runaway mesh messes. Ignored if zero.
Definition at line 49 of file NormalFlowRemesher.h.
NormalAlignmentSpeed
double UE::Geometry::FNormalFlowRemesher::NormalAlignmentSpeed = 0.2
drag on normal alignment
Definition at line 36 of file NormalFlowRemesher.h.
NumExtraProjectionIterations
int UE::Geometry::FNormalFlowRemesher::NumExtraProjectionIterations = 5
Additional projection iterations after the usual remesh step.
Definition at line 30 of file NormalFlowRemesher.h.
ProjectionVertexBuffer
TArray<FVector3d> UE::Geometry::FNormalFlowRemesher::ProjectionVertexBuffer protected
Definition at line 96 of file NormalFlowRemesher.h.
Referenced by InitializeVertexBufferForFacePass().
ProjectionWeightBuffer
TArray<double> UE::Geometry::FNormalFlowRemesher::ProjectionWeightBuffer protected
Definition at line 93 of file NormalFlowRemesher.h.
Referenced by InitializeVertexBufferForFacePass().
SurfaceProjectionSpeed
double UE::Geometry::FNormalFlowRemesher::SurfaceProjectionSpeed = 0.2
drag on surface projection
Definition at line 33 of file NormalFlowRemesher.h.
TempWeightBuffer
TArray<double> UE::Geometry::FNormalFlowRemesher::TempWeightBuffer protected
Definition at line 90 of file NormalFlowRemesher.h.
Referenced by InitializeVertexBufferForFacePass().
The documentation for this class was generated from the following file:
NormalFlowRemesher.h