Unreal Engine 5.6 C++ API: MovieSceneEventSection.h File Reference
MovieSceneEventSection.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Class.h"
#include "Curves/KeyHandle.h"
#include "MovieSceneSection.h"
#include "Curves/NameCurve.h"
#include "UObject/StructOnScope.h"
#include "Engine/Engine.h"
#include "UObject/SoftObjectPath.h"
#include "Channels/MovieSceneChannel.h"
#include "Channels/MovieSceneChannelData.h"
#include "Channels/MovieSceneChannelTraits.h"
#include "MovieSceneEventSection.generated.h"
Data Structures
struct TMovieSceneChannelTraits< FMovieSceneEventSectionData >
A curve of events.
struct TStructOpsTypeTraits< FMovieSceneEventParameters >
Functions
bool EvaluateChannel (const FMovieSceneEventSectionData *InChannel, FFrameTime InTime, FEventPayload &OutValue)
Stub out unnecessary functions.
USTRUCT () struct FMovieSceneEventParameters
bool ValueExistsAtTime (const FMovieSceneEventSectionData *InChannel, FFrameNumber Time, const FEventPayload &Value)
Function Documentation
EvaluateChannel()
bool EvaluateChannel (const FMovieSceneEventSectionData * InChannel, FFrameTime InTime, FEventPayload & OutValue) inline
Stub out unnecessary functions.
Definition at line 273 of file MovieSceneEventSection.h.
References InTime.
USTRUCT()
USTRUCT ()
Construction from a struct type
Access the struct type of this event parameter payload
Returns
A valid UScriptStruct* or nullptr if the struct is not set, or no longer available
Change the type of this event parameter payload to be the specified struct
Retrieve an instance of this payload
Parameters
OutStruct Structure to receive the instance
Overwrite this payload with another instance of the same type.
Parameters
InstancePtr A valid pointer to an instance of the type represented by GetStructType
Serialization implementation
Soft object path to the type of this parameter payload
Used while loading to pass along to the FEventParameterReader
Serialized bytes that represent the payload. Serialized internally with FEventParameterArchive
The name of the event to trigger
The event parameters
Definition at line 21 of file MovieSceneEventSection.h.
References A, Ar, B, BlueprintType, Cast(), GENERATED_BODY, GPackageFileLicenseeUEVersion, GPackageFileUEVersion, operator!=(), operator<<(), and operator==().
ValueExistsAtTime()
bool ValueExistsAtTime (const FMovieSceneEventSectionData * InChannel, FFrameNumber Time, const FEventPayload & Value) inline
Definition at line 279 of file MovieSceneEventSection.h.
References INDEX_NONE, Time, and Value.