Unreal Engine 5.6 C++ API: FOutputDevice Class Reference
FOutputDevice Class Reference abstract
#include "OutputDevice.h"
Public Member Functions
FOutputDevice ()
FOutputDevice (const FOutputDevice &)
FOutputDevice (FOutputDevice &&)
virtual ~FOutputDevice ()
virtual bool CanBeUsedOnAnyThread () const
virtual bool CanBeUsedOnMultipleThreads () const
virtual bool CanBeUsedOnPanicThread () const
template<typename FmtType, typename... Types>
FORCEINLINE void CategorizedLogf (const FName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
virtual void Dump (class FArchive &Ar)
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
virtual void Flush ()
FORCEINLINE bool GetAutoEmitLineTerminator () const
FORCEINLINE bool GetSuppressEventTag () const
virtual bool IsMemoryOnly () const
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const FString &S)
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Str)
void Log (const FString &S)
void Log (const FText &S)
void Log (const TCHAR *S)
void Log (ELogVerbosity::Type Verbosity, const FString &S)
void Log (ELogVerbosity::Type Verbosity, const TCHAR *S)
template<typename FmtType>
void Logf (const FmtType &Fmt)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
FOutputDevice & operator= (const FOutputDevice &)
FOutputDevice & operator= (FOutputDevice &&)
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category)=0
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category, const double Time)
virtual void SerializeRecord (const UE::FLogRecord &Record)
void SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator)
void SetSuppressEventTag (bool bInSuppressEventTag)
virtual void TearDown ()
Closes output device and cleans up.
Protected Attributes
bool bAutoEmitLineTerminator
Whether to output a line-terminator after each log call...
bool bSuppressEventTag
Whether to output the 'Log: ' type front...
Private Member Functions
void VARARGS CategorizedLogfImpl (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Fmt,...)
void VARARGS LogfImpl (const TCHAR *Fmt,...)
void VARARGS LogfImpl (ELogVerbosity::Type Verbosity, const TCHAR *Fmt,...)
Detailed Description
Definition at line 132 of file OutputDevice.h.
Constructor & Destructor Documentation
FOutputDevice() [1/3]
FOutputDevice::FOutputDevice ()
Referenced by FOutputDevice(), FOutputDevice(), FRigVMMemoryStorageImportErrorContext::FRigVMMemoryStorageImportErrorContext(), FRigVMPinDefaultValueImportErrorContext::FRigVMPinDefaultValueImportErrorContext(), FOutputDeviceRedirector::AddOutputDevice(), FOutputDeviceRedirector::IsRedirectingTo(), operator=(), operator=(), FBufferedOutputDevice::RedirectTo(), FOutputDeviceRedirector::RemoveOutputDevice(), and FOutputDeviceRedirector::SerializeBacklog().
FOutputDevice() [2/3]
FOutputDevice::FOutputDevice (FOutputDevice &&)
References FOutputDevice().
FOutputDevice() [3/3]
FOutputDevice::FOutputDevice (const FOutputDevice &)
References FOutputDevice().
~FOutputDevice()
virtual FOutputDevice::~FOutputDevice () virtual
Member Function Documentation
CanBeUsedOnAnyThread()
virtual bool FOutputDevice::CanBeUsedOnAnyThread () const inline virtual
Returns
whether this output device can be used on any thread.
Reimplemented in FLinuxConsoleOutputDevice, FOutputDeviceAnsiError, FOutputDeviceDebug, FOutputDeviceFile, FOutputDeviceMemory, FOutputDeviceStdOutput, FWindowsConsoleOutputDevice2, and FWindowsConsoleOutputDevice.
Definition at line 196 of file OutputDevice.h.
CanBeUsedOnMultipleThreads()
virtual bool FOutputDevice::CanBeUsedOnMultipleThreads () const inline virtual
Returns
whether this output device can be used from multiple threads simultaneously without any locking
Reimplemented in FOutputDeviceDebug.
Definition at line 204 of file OutputDevice.h.
CanBeUsedOnPanicThread()
virtual bool FOutputDevice::CanBeUsedOnPanicThread () const inline virtual
Returns
whether this output device can be used after a panic (crash or fatal error) has been flagged.
Note
The return value is cached by AddOutputDevice because calling this during a panic may fail.
Reimplemented in FLinuxConsoleOutputDevice, FOutputDeviceDebug, FOutputDeviceError, FOutputDeviceFile, FOutputDeviceMemory, FOutputDeviceStdOutput, and FWindowsConsoleOutputDevice.
Definition at line 213 of file OutputDevice.h.
CategorizedLogf()
template<typename FmtType, typename... Types> FORCEINLINE void FOutputDevice::CategorizedLogf (const FName & Category, ELogVerbosity::Type Verbosity, const FmtType & Fmt, Types... Args) inline
Definition at line 259 of file OutputDevice.h.
References CategorizedLogfImpl(), Category, FORCEINLINE, TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
CategorizedLogfImpl()
void VARARGS FOutputDevice::CategorizedLogfImpl (const FName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Fmt, ...) private
References Category, and VARARGS.
Referenced by CategorizedLogf().
Dump()
virtual void FOutputDevice::Dump (class FArchive & Ar) inline virtual
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
Parameters
Ar Archive to dump the buffer to
Reimplemented in FOutputDeviceMemory.
Definition at line 181 of file OutputDevice.h.
References Ar.
Flush()
virtual void FOutputDevice::Flush (void) inline virtual
Reimplemented in FOutputDeviceArchiveWrapper, FOutputDeviceFile, FOutputDeviceMemory, FOutputDeviceRedirector, and FWindowsEventLogOutputDevice.
Definition at line 153 of file OutputDevice.h.
GetAutoEmitLineTerminator()
FORCEINLINE bool FOutputDevice::GetAutoEmitLineTerminator () const inline
Definition at line 175 of file OutputDevice.h.
References bAutoEmitLineTerminator, and FORCEINLINE.
GetSuppressEventTag()
FORCEINLINE bool FOutputDevice::GetSuppressEventTag () const inline
Definition at line 170 of file OutputDevice.h.
References bSuppressEventTag, and FORCEINLINE.
IsMemoryOnly()
virtual bool FOutputDevice::IsMemoryOnly () const inline virtual
Returns
whether this output device is a memory-only device
Reimplemented in FOutputDeviceMemory.
Definition at line 188 of file OutputDevice.h.
Log() [1/7]
void FOutputDevice::Log (const FName & Category, ELogVerbosity::Type Verbosity, const FString & S)
References Category.
Log() [2/7]
void FOutputDevice::Log (const FName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Str)
References Category.
Log() [3/7]
void FOutputDevice::Log (const FString & S)
Log() [4/7]
void FOutputDevice::Log (const FText & S)
Log() [5/7]
void FOutputDevice::Log (const TCHAR * S)
Log() [6/7]
void FOutputDevice::Log (ELogVerbosity::Type Verbosity, const FString & S)
Log() [7/7]
void FOutputDevice::Log (ELogVerbosity::Type Verbosity, const TCHAR * S)
Logf() [1/3]
template<typename FmtType> void FOutputDevice::Logf (const FmtType & Fmt) inline
Definition at line 234 of file OutputDevice.h.
References Log, and TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value.
Logf() [2/3]
template<typename FmtType, typename... Types> FORCEINLINE void FOutputDevice::Logf (const FmtType & Fmt, Types... Args) inline
Definition at line 241 of file OutputDevice.h.
References FORCEINLINE, LogfImpl(), TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
Logf() [3/3]
template<typename FmtType, typename... Types> FORCEINLINE void FOutputDevice::Logf (ELogVerbosity::Type Verbosity, const FmtType & Fmt, Types... Args) inline
Definition at line 250 of file OutputDevice.h.
References FORCEINLINE, LogfImpl(), TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
LogfImpl() [1/2]
void VARARGS FOutputDevice::LogfImpl (const TCHAR * Fmt, ...) private
References VARARGS.
Referenced by Logf(), and Logf().
LogfImpl() [2/2]
void VARARGS FOutputDevice::LogfImpl (ELogVerbosity::Type Verbosity, const TCHAR * Fmt, ...) private
References VARARGS.
operator=() [1/2]
FOutputDevice & FOutputDevice::operator= (const FOutputDevice &)
References FOutputDevice().
operator=() [2/2]
FOutputDevice & FOutputDevice::operator= (FOutputDevice &&)
References FOutputDevice().
Serialize() [1/2]
virtual void FOutputDevice::Serialize (const TCHAR * V, ELogVerbosity::Type Verbosity, const FName & Category) pure virtual
Implemented in FBufferedOutputDevice, FFeedbackContext, FFeedbackContextAnsi, FOutputDeviceDebug, FOutputDeviceRedirector, FOutputDeviceStdOutput, and FUnixFeedbackContext.
References Category.
Referenced by Serialize().
Serialize() [2/2]
virtual void FOutputDevice::Serialize (const TCHAR * V, ELogVerbosity::Type Verbosity, const FName & Category, const double Time) inline virtual
Reimplemented in FFeedbackContext, FFeedbackContextAnsi, FOutputDeviceDebug, FOutputDeviceRedirector, FOutputDeviceStdOutput, and FUnixFeedbackContext.
Definition at line 146 of file OutputDevice.h.
References Category, Serialize(), and Time.
SerializeRecord()
virtual void FOutputDevice::SerializeRecord (const UE::FLogRecord & Record) virtual
Reimplemented in FFeedbackContext, FFeedbackContextAnsi, FOutputDeviceDebug, FOutputDeviceRedirector, FOutputDeviceStdOutput, and FUnixFeedbackContext.
References Record.
SetAutoEmitLineTerminator()
void FOutputDevice::SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator) inline
Definition at line 171 of file OutputDevice.h.
References bAutoEmitLineTerminator.
SetSuppressEventTag()
void FOutputDevice::SetSuppressEventTag (bool bInSuppressEventTag) inline
Definition at line 166 of file OutputDevice.h.
References bSuppressEventTag.
TearDown()
virtual void FOutputDevice::TearDown (void) inline virtual
Closes output device and cleans up.
This can't happen in the destructor as we might have to call "delete" which cannot be done for static/ global objects.
Reimplemented in FOutputDeviceFile, FOutputDeviceMemory, FOutputDeviceRedirector, and FWindowsEventLogOutputDevice.
Definition at line 162 of file OutputDevice.h.
Field Documentation
bAutoEmitLineTerminator
bool FOutputDevice::bAutoEmitLineTerminator protected
Whether to output a line-terminator after each log call...
Definition at line 271 of file OutputDevice.h.
Referenced by FStringOutputDevice::FStringOutputDevice(), GetAutoEmitLineTerminator(), FStringOutputDevice::Serialize(), FStringOutputDeviceCountLines::Serialize(), and SetAutoEmitLineTerminator().
bSuppressEventTag
bool FOutputDevice::bSuppressEventTag protected
Whether to output the 'Log: ' type front...
Definition at line 269 of file OutputDevice.h.
Referenced by GetSuppressEventTag(), and SetSuppressEventTag().
The documentation for this class was generated from the following file:
OutputDevice.h