Unreal Engine 5.6 C++ API: UE::FSharedRecursiveMutex Class Reference
UE::FSharedRecursiveMutex Class Reference final
An eight-byte shared mutex that is not fair and supports recursive locking.
#include "SharedRecursiveMutex.h"
Public Member Functions
constexpr FSharedRecursiveMutex ()=default
FSharedRecursiveMutex (const FSharedRecursiveMutex &)=delete
void Lock ()
void LockShared (Core::Private::FSharedRecursiveMutexLink &Link)
FSharedRecursiveMutex & operator= (const FSharedRecursiveMutex &)=delete
bool TryLock ()
bool TryLockShared (Core::Private::FSharedRecursiveMutexLink &Link)
void Unlock ()
void UnlockShared (Core::Private::FSharedRecursiveMutexLink &Link)
Private Member Functions
const void * GetLockAddress () const
const void * GetSharedLockAddress () const
void LockSharedSlow (Core::Private::FSharedRecursiveMutexLink &Link)
void LockSlow (uint32 CurrentState, uint32 CurrentThreadId)
void WakeWaitingThreads (uint32 CurrentState)
Private Attributes
std::atomic< uint32 > State = 0
std::atomic< uint32 > ThreadId = 0
Static Private Attributes
static constexpr uint32 LockCountMask = 0x0000'0ffc
static constexpr uint32 LockCountShift = 2
static constexpr uint32 MayHaveWaitingLockFlag = 1 << 0
static constexpr uint32 MayHaveWaitingSharedLockFlag = 1 << 1
static constexpr uint32 SharedLockCountMask = 0xffff'f000
static constexpr uint32 SharedLockCountShift = 12
Detailed Description
An eight-byte shared mutex that is not fair and supports recursive locking.
Prefer FRecursiveMutex when shared locking is not required. Prefer FSharedMutex when recursive locking is not required. All non-recursive shared locks will wait when any thread is waiting to take an exclusive lock. An exclusive lock and a shared lock may not be simultaneously held by the same thread.
Definition at line 39 of file SharedRecursiveMutex.h.
Constructor & Destructor Documentation
FSharedRecursiveMutex() [1/2]
UE::FSharedRecursiveMutex::FSharedRecursiveMutex () constexpr default
Referenced by FSharedRecursiveMutex(), and operator=().
FSharedRecursiveMutex() [2/2]
UE::FSharedRecursiveMutex::FSharedRecursiveMutex (const FSharedRecursiveMutex &) delete
References FSharedRecursiveMutex().
Member Function Documentation
GetLockAddress()
const void * UE::FSharedRecursiveMutex::GetLockAddress () const private
GetSharedLockAddress()
const void * UE::FSharedRecursiveMutex::GetSharedLockAddress () const private
Lock()
void UE::FSharedRecursiveMutex::Lock ()
References UE_API.
Referenced by UAnimSequence::FCompressedAnimationDataWriteScope::FCompressedAnimationDataWriteScope().
LockShared()
void UE::FSharedRecursiveMutex::LockShared (Core::Private::FSharedRecursiveMutexLink & Link)
References UE_API.
LockSharedSlow()
void UE::FSharedRecursiveMutex::LockSharedSlow (Core::Private::FSharedRecursiveMutexLink & Link) private
LockSlow()
void UE::FSharedRecursiveMutex::LockSlow (uint32 CurrentState, uint32 CurrentThreadId) private
operator=()
FSharedRecursiveMutex & UE::FSharedRecursiveMutex::operator= (const FSharedRecursiveMutex &) delete
References FSharedRecursiveMutex().
TryLock()
bool UE::FSharedRecursiveMutex::TryLock ()
References UE_API.
TryLockShared()
bool UE::FSharedRecursiveMutex::TryLockShared (Core::Private::FSharedRecursiveMutexLink & Link)
References UE_API.
Unlock()
void UE::FSharedRecursiveMutex::Unlock ()
References UE_API.
UnlockShared()
void UE::FSharedRecursiveMutex::UnlockShared (Core::Private::FSharedRecursiveMutexLink & Link)
References UE_API.
WakeWaitingThreads()
void UE::FSharedRecursiveMutex::WakeWaitingThreads (uint32 CurrentState) private
Field Documentation
LockCountMask
uint32 UE::FSharedRecursiveMutex::LockCountMask = 0x0000'0ffc static constexpr private
Definition at line 67 of file SharedRecursiveMutex.h.
LockCountShift
uint32 UE::FSharedRecursiveMutex::LockCountShift = 2 static constexpr private
Definition at line 66 of file SharedRecursiveMutex.h.
MayHaveWaitingLockFlag
uint32 UE::FSharedRecursiveMutex::MayHaveWaitingLockFlag = 1 << 0 static constexpr private
Definition at line 64 of file SharedRecursiveMutex.h.
MayHaveWaitingSharedLockFlag
uint32 UE::FSharedRecursiveMutex::MayHaveWaitingSharedLockFlag = 1 << 1 static constexpr private
Definition at line 65 of file SharedRecursiveMutex.h.
SharedLockCountMask
uint32 UE::FSharedRecursiveMutex::SharedLockCountMask = 0xffff'f000 static constexpr private
Definition at line 69 of file SharedRecursiveMutex.h.
SharedLockCountShift
uint32 UE::FSharedRecursiveMutex::SharedLockCountShift = 12 static constexpr private
Definition at line 68 of file SharedRecursiveMutex.h.
State
std::atomic<uint32> UE::FSharedRecursiveMutex::State = 0 private
Definition at line 71 of file SharedRecursiveMutex.h.
ThreadId
std::atomic<uint32> UE::FSharedRecursiveMutex::ThreadId = 0 private
Definition at line 72 of file SharedRecursiveMutex.h.
The documentation for this class was generated from the following file:
SharedRecursiveMutex.h