Unreal Engine 5.6 C++ API: ClearReplacementShaders.h File Reference
ClearReplacementShaders.h File Reference
#include "CoreMinimal.h"
#include "DataDrivenShaderPlatformInfo.h"
#include "GlobalShader.h"
#include "Math/IntVector.h"
#include "Math/UnrealMathSSE.h"
#include "PipelineStateCache.h"
#include "PixelFormat.h"
#include "RenderGraphUtils.h"
#include "RHI.h"
#include "RHICommandList.h"
#include "RHIDefinitions.h"
#include "Serialization/MemoryLayout.h"
#include "Shader.h"
#include "ShaderCompilerCore.h"
#include "ShaderCore.h"
#include "ShaderParameterUtils.h"
#include "ShaderParameters.h"
#include "Templates/EnableIf.h"
#include "Templates/Function.h"
Data Structures
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType >
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType::Buffer >
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType::LargeBuffer >
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType::StructuredBuffer >
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType::Texture2D >
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType::Texture2DArray >
struct ClearReplacementCS::TThreadGroupSize< EClearReplacementResourceType::Texture3D >
struct TClearReplacementBase< ValueType, NumChannels, bZeroOutput, bEnableBounds >
class TClearReplacementCS< ResourceType, BaseType >
class TClearReplacementPS< b128BitOutput, BaseType >
struct TClearReplacementTypeSelector< Type >
struct TClearReplacementTypeSelector< EClearReplacementValueType::Float >
struct TClearReplacementTypeSelector< EClearReplacementValueType::Int32 >
struct TClearReplacementTypeSelector< EClearReplacementValueType::Uint32 >
class TClearReplacementVS< bEnableDepth, BaseType >
Namespaces
namespace ClearReplacementCS
Typedefs
typedef TClearReplacementBase< EClearReplacementValueType::Float, 4, false, false > FClearReplacementBase_Float4
typedef TClearReplacementBase< EClearReplacementValueType::Float, 4, false, true > FClearReplacementBase_Float4_Bounds
typedef TClearReplacementBase< EClearReplacementValueType::Float, 4, true, false > FClearReplacementBase_Float4_Zero
typedef TClearReplacementBase< EClearReplacementValueType::Float, 4, true, true > FClearReplacementBase_Float4_Zero_Bounds
typedef TClearReplacementBase< EClearReplacementValueType::Float, 1, false, true > FClearReplacementBase_Float_Bounds
typedef TClearReplacementBase< EClearReplacementValueType::Int32, 4, false, true > FClearReplacementBase_Sint4_Bounds
typedef TClearReplacementBase< EClearReplacementValueType::Uint32, 1, false, false > FClearReplacementBase_Uint
typedef TClearReplacementBase< EClearReplacementValueType::Uint32, 4, false, false > FClearReplacementBase_Uint4
typedef TClearReplacementBase< EClearReplacementValueType::Uint32, 4, false, true > FClearReplacementBase_Uint4_Bounds
typedef TClearReplacementBase< EClearReplacementValueType::Uint32, 1, false, true > FClearReplacementBase_Uint_Bounds
typedef TClearReplacementBase< EClearReplacementValueType::Uint32, 1, true, false > FClearReplacementBase_Uint_Zero
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Float4_Bounds > FClearReplacementCS_Buffer_Float4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Float_Bounds > FClearReplacementCS_Buffer_Float_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Sint4_Bounds > FClearReplacementCS_Buffer_Sint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint > FClearReplacementCS_Buffer_Uint
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint4 > FClearReplacementCS_Buffer_Uint4
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint4_Bounds > FClearReplacementCS_Buffer_Uint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds > FClearReplacementCS_Buffer_Uint_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Zero > FClearReplacementCS_Buffer_Uint_Zero
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Float4_Bounds > FClearReplacementCS_LargeBuffer_Float4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Float_Bounds > FClearReplacementCS_LargeBuffer_Float_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Sint4_Bounds > FClearReplacementCS_LargeBuffer_Sint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint > FClearReplacementCS_LargeBuffer_Uint
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint4 > FClearReplacementCS_LargeBuffer_Uint4
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint4_Bounds > FClearReplacementCS_LargeBuffer_Uint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint_Bounds > FClearReplacementCS_LargeBuffer_Uint_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Float4_Bounds > FClearReplacementCS_StructuredBuffer_Float4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Float_Bounds > FClearReplacementCS_StructuredBuffer_Float_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Sint4_Bounds > FClearReplacementCS_StructuredBuffer_Sint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint > FClearReplacementCS_StructuredBuffer_Uint
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint4 > FClearReplacementCS_StructuredBuffer_Uint4
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint4_Bounds > FClearReplacementCS_StructuredBuffer_Uint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint_Bounds > FClearReplacementCS_StructuredBuffer_Uint_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint_Zero > FClearReplacementCS_StructuredBuffer_Uint_Zero
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2D, FClearReplacementBase_Float4 > FClearReplacementCS_Texture2D_Float4
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2D, FClearReplacementBase_Float4_Bounds > FClearReplacementCS_Texture2D_Float4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2D, FClearReplacementBase_Sint4_Bounds > FClearReplacementCS_Texture2D_Sint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2D, FClearReplacementBase_Uint4 > FClearReplacementCS_Texture2D_Uint4
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2D, FClearReplacementBase_Uint4_Bounds > FClearReplacementCS_Texture2D_Uint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Float4 > FClearReplacementCS_Texture2DArray_Float4
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Float4_Bounds > FClearReplacementCS_Texture2DArray_Float4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Sint4_Bounds > FClearReplacementCS_Texture2DArray_Sint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint > FClearReplacementCS_Texture2DArray_Uint
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint4 > FClearReplacementCS_Texture2DArray_Uint4
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint4_Bounds > FClearReplacementCS_Texture2DArray_Uint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint_Zero > FClearReplacementCS_Texture2DArray_Uint_Zero
typedef TClearReplacementCS< EClearReplacementResourceType::Texture3D, FClearReplacementBase_Float4 > FClearReplacementCS_Texture3D_Float4
typedef TClearReplacementCS< EClearReplacementResourceType::Texture3D, FClearReplacementBase_Float4_Bounds > FClearReplacementCS_Texture3D_Float4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture3D, FClearReplacementBase_Sint4_Bounds > FClearReplacementCS_Texture3D_Sint4_Bounds
typedef TClearReplacementCS< EClearReplacementResourceType::Texture3D, FClearReplacementBase_Uint4 > FClearReplacementCS_Texture3D_Uint4
typedef TClearReplacementCS< EClearReplacementResourceType::Texture3D, FClearReplacementBase_Uint4_Bounds > FClearReplacementCS_Texture3D_Uint4_Bounds
typedef TClearReplacementPS< false, FClearReplacementBase_Float4 > FClearReplacementPS
typedef TClearReplacementPS< true, FClearReplacementBase_Float4 > FClearReplacementPS_128
typedef TClearReplacementPS< false, FClearReplacementBase_Float4_Zero > FClearReplacementPS_Zero
typedef TClearReplacementVS< false, FClearReplacementBase_Float4_Zero > FClearReplacementVS
typedef TClearReplacementVS< false, FClearReplacementBase_Float4_Zero_Bounds > FClearReplacementVS_Bounds
typedef TClearReplacementVS< true, FClearReplacementBase_Float4_Zero > FClearReplacementVS_Depth
Enumerations
enum class EClearReplacementResourceType {
Buffer = 0 , Texture2D = 1 , Texture2DArray = 2 , Texture3D = 3 ,
StructuredBuffer = 4 , LargeBuffer = 5
}
enum class EClearReplacementValueType { Float , Int32 , Uint32 }
Functions
template<EClearReplacementResourceType ResourceType, EClearReplacementValueType ValueType, uint32 NumChannels, bool bBarriers>
void ClearUAVShader_T (FRHIComputeCommandList &RHICmdList, FRHIUnorderedAccessView *UAV, uint32 SizeX, uint32 SizeY, uint32 SizeZ, const typename TClearReplacementTypeSelector< ValueType >::Type(&ClearValues)[NumChannels])
template<EClearReplacementResourceType ResourceType, EClearReplacementValueType ValueType, uint32 NumChannels, bool bBarriers>
void ClearUAVShader_T (FRHIComputeCommandList &RHICmdList, FRHIUnorderedAccessView *UAV, uint32 SizeX, uint32 SizeY, uint32 SizeZ, const typename TClearReplacementTypeSelector< ValueType >::Type(&ClearValues)[NumChannels], TFunctionRef< void(FRHIComputeShader *, const FShaderResourceParameter &, bool)> ResourceBindCallback)
Helper functions for running the clear replacement shader for specific resource types, values types and number of channels.
template<EClearReplacementResourceType ResourceType, uint32 NumChannels, bool bBarriers>
void ClearUAVShader_T (FRHIComputeCommandList &RHICmdList, FRHIUnorderedAccessView *UAV, uint32 SizeX, uint32 SizeY, uint32 SizeZ, const void *ClearValues, EClearReplacementValueType ValueType)
Typedef Documentation
FClearReplacementBase_Float4
typedef TClearReplacementBase<EClearReplacementValueType::Float , 4, false, false> FClearReplacementBase_Float4
Definition at line 278 of file ClearReplacementShaders.h.
FClearReplacementBase_Float4_Bounds
typedef TClearReplacementBase<EClearReplacementValueType::Float , 4, false, true > FClearReplacementBase_Float4_Bounds
Definition at line 286 of file ClearReplacementShaders.h.
FClearReplacementBase_Float4_Zero
typedef TClearReplacementBase<EClearReplacementValueType::Float , 4, true , false> FClearReplacementBase_Float4_Zero
Definition at line 280 of file ClearReplacementShaders.h.
FClearReplacementBase_Float4_Zero_Bounds
typedef TClearReplacementBase<EClearReplacementValueType::Float , 4, true , true > FClearReplacementBase_Float4_Zero_Bounds
Definition at line 281 of file ClearReplacementShaders.h.
FClearReplacementBase_Float_Bounds
typedef TClearReplacementBase<EClearReplacementValueType::Float , 1, false, true > FClearReplacementBase_Float_Bounds
Definition at line 285 of file ClearReplacementShaders.h.
FClearReplacementBase_Sint4_Bounds
typedef TClearReplacementBase<EClearReplacementValueType::Int32, 4, false, true > FClearReplacementBase_Sint4_Bounds
Definition at line 284 of file ClearReplacementShaders.h.
FClearReplacementBase_Uint
typedef TClearReplacementBase<EClearReplacementValueType::Uint32, 1, false, false> FClearReplacementBase_Uint
Definition at line 276 of file ClearReplacementShaders.h.
FClearReplacementBase_Uint4
typedef TClearReplacementBase<EClearReplacementValueType::Uint32, 4, false, false> FClearReplacementBase_Uint4
Definition at line 277 of file ClearReplacementShaders.h.
FClearReplacementBase_Uint4_Bounds
typedef TClearReplacementBase<EClearReplacementValueType::Uint32, 4, false, true > FClearReplacementBase_Uint4_Bounds
Definition at line 283 of file ClearReplacementShaders.h.
FClearReplacementBase_Uint_Bounds
typedef TClearReplacementBase<EClearReplacementValueType::Uint32, 1, false, true > FClearReplacementBase_Uint_Bounds
Definition at line 282 of file ClearReplacementShaders.h.
FClearReplacementBase_Uint_Zero
typedef TClearReplacementBase<EClearReplacementValueType::Uint32, 1, true , false> FClearReplacementBase_Uint_Zero
Definition at line 279 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Float4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Float4_Bounds> FClearReplacementCS_Buffer_Float4_Bounds
Definition at line 302 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Float_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Float_Bounds> FClearReplacementCS_Buffer_Float_Bounds
Definition at line 301 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Sint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Sint4_Bounds> FClearReplacementCS_Buffer_Sint4_Bounds
Definition at line 341 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Uint
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint> FClearReplacementCS_Buffer_Uint
Definition at line 317 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Uint4
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint4> FClearReplacementCS_Buffer_Uint4
Definition at line 330 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Uint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint4_Bounds> FClearReplacementCS_Buffer_Uint4_Bounds
Definition at line 334 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Uint_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds> FClearReplacementCS_Buffer_Uint_Bounds
Definition at line 300 of file ClearReplacementShaders.h.
FClearReplacementCS_Buffer_Uint_Zero
typedef TClearReplacementCS<EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Zero> FClearReplacementCS_Buffer_Uint_Zero
Definition at line 314 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Float4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Float4_Bounds> FClearReplacementCS_LargeBuffer_Float4_Bounds
Definition at line 305 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Float_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Float_Bounds> FClearReplacementCS_LargeBuffer_Float_Bounds
Definition at line 304 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Sint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Sint4_Bounds> FClearReplacementCS_LargeBuffer_Sint4_Bounds
Definition at line 342 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Uint
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint> FClearReplacementCS_LargeBuffer_Uint
Definition at line 318 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Uint4
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint4> FClearReplacementCS_LargeBuffer_Uint4
Definition at line 331 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Uint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint4_Bounds> FClearReplacementCS_LargeBuffer_Uint4_Bounds
Definition at line 335 of file ClearReplacementShaders.h.
FClearReplacementCS_LargeBuffer_Uint_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::LargeBuffer, FClearReplacementBase_Uint_Bounds> FClearReplacementCS_LargeBuffer_Uint_Bounds
Definition at line 303 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Float4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Float4_Bounds> FClearReplacementCS_StructuredBuffer_Float4_Bounds
Definition at line 308 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Float_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Float_Bounds> FClearReplacementCS_StructuredBuffer_Float_Bounds
Definition at line 307 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Sint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Sint4_Bounds> FClearReplacementCS_StructuredBuffer_Sint4_Bounds
Definition at line 343 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Uint
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint> FClearReplacementCS_StructuredBuffer_Uint
Definition at line 319 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Uint4
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint4> FClearReplacementCS_StructuredBuffer_Uint4
Definition at line 332 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Uint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint4_Bounds> FClearReplacementCS_StructuredBuffer_Uint4_Bounds
Definition at line 336 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Uint_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint_Bounds> FClearReplacementCS_StructuredBuffer_Uint_Bounds
Definition at line 306 of file ClearReplacementShaders.h.
FClearReplacementCS_StructuredBuffer_Uint_Zero
typedef TClearReplacementCS<EClearReplacementResourceType::StructuredBuffer, FClearReplacementBase_Uint_Zero> FClearReplacementCS_StructuredBuffer_Uint_Zero
Definition at line 315 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2D_Float4
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2D, FClearReplacementBase_Float4> FClearReplacementCS_Texture2D_Float4
Definition at line 323 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2D_Float4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2D, FClearReplacementBase_Float4_Bounds> FClearReplacementCS_Texture2D_Float4_Bounds
Definition at line 310 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2D_Sint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2D, FClearReplacementBase_Sint4_Bounds> FClearReplacementCS_Texture2D_Sint4_Bounds
Definition at line 345 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2D_Uint4
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2D, FClearReplacementBase_Uint4> FClearReplacementCS_Texture2D_Uint4
Definition at line 328 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2D_Uint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2D, FClearReplacementBase_Uint4_Bounds> FClearReplacementCS_Texture2D_Uint4_Bounds
Definition at line 338 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Float4
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Float4> FClearReplacementCS_Texture2DArray_Float4
Definition at line 324 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Float4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Float4_Bounds> FClearReplacementCS_Texture2DArray_Float4_Bounds
Definition at line 311 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Sint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Sint4_Bounds> FClearReplacementCS_Texture2DArray_Sint4_Bounds
Definition at line 346 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Uint
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint> FClearReplacementCS_Texture2DArray_Uint
Definition at line 320 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Uint4
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint4> FClearReplacementCS_Texture2DArray_Uint4
Definition at line 329 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Uint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint4_Bounds> FClearReplacementCS_Texture2DArray_Uint4_Bounds
Definition at line 339 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture2DArray_Uint_Zero
typedef TClearReplacementCS<EClearReplacementResourceType::Texture2DArray, FClearReplacementBase_Uint_Zero> FClearReplacementCS_Texture2DArray_Uint_Zero
Definition at line 316 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture3D_Float4
typedef TClearReplacementCS<EClearReplacementResourceType::Texture3D, FClearReplacementBase_Float4> FClearReplacementCS_Texture3D_Float4
Definition at line 322 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture3D_Float4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture3D, FClearReplacementBase_Float4_Bounds> FClearReplacementCS_Texture3D_Float4_Bounds
Definition at line 309 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture3D_Sint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture3D, FClearReplacementBase_Sint4_Bounds> FClearReplacementCS_Texture3D_Sint4_Bounds
Definition at line 344 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture3D_Uint4
typedef TClearReplacementCS<EClearReplacementResourceType::Texture3D, FClearReplacementBase_Uint4> FClearReplacementCS_Texture3D_Uint4
Definition at line 327 of file ClearReplacementShaders.h.
FClearReplacementCS_Texture3D_Uint4_Bounds
typedef TClearReplacementCS<EClearReplacementResourceType::Texture3D, FClearReplacementBase_Uint4_Bounds> FClearReplacementCS_Texture3D_Uint4_Bounds
Definition at line 337 of file ClearReplacementShaders.h.
FClearReplacementPS
typedef TClearReplacementPS<false, FClearReplacementBase_Float4> FClearReplacementPS
Definition at line 294 of file ClearReplacementShaders.h.
FClearReplacementPS_128
typedef TClearReplacementPS<true, FClearReplacementBase_Float4> FClearReplacementPS_128
Definition at line 295 of file ClearReplacementShaders.h.
FClearReplacementPS_Zero
typedef TClearReplacementPS<false, FClearReplacementBase_Float4_Zero> FClearReplacementPS_Zero
Definition at line 297 of file ClearReplacementShaders.h.
FClearReplacementVS
typedef TClearReplacementVS<false, FClearReplacementBase_Float4_Zero > FClearReplacementVS
Definition at line 289 of file ClearReplacementShaders.h.
FClearReplacementVS_Bounds
typedef TClearReplacementVS<false, FClearReplacementBase_Float4_Zero_Bounds> FClearReplacementVS_Bounds
Definition at line 290 of file ClearReplacementShaders.h.
FClearReplacementVS_Depth
typedef TClearReplacementVS<true, FClearReplacementBase_Float4_Zero > FClearReplacementVS_Depth
Definition at line 291 of file ClearReplacementShaders.h.
Enumeration Type Documentation
EClearReplacementResourceType
enum class EClearReplacementResourceType strong
Enumerator
Buffer
Texture2D
Texture2DArray
Texture3D
StructuredBuffer
LargeBuffer
Definition at line 28 of file ClearReplacementShaders.h.
EClearReplacementValueType
enum class EClearReplacementValueType strong
Enumerator
Float
Int32
Uint32
Definition at line 38 of file ClearReplacementShaders.h.
Function Documentation
ClearUAVShader_T() [1/3]
template<EClearReplacementResourceType ResourceType, EClearReplacementValueType ValueType, uint32 NumChannels, bool bBarriers> void ClearUAVShader_T (FRHIComputeCommandList & RHICmdList, FRHIUnorderedAccessView * UAV, uint32 SizeX, uint32 SizeY, uint32 SizeZ, const typename TClearReplacementTypeSelector< ValueType >::Type(&) ClearValues[NumChannels]) inline
Definition at line 391 of file ClearReplacementShaders.h.
References TShaderRefBase< ShaderType, PointerTableType >::GetComputeShader(), GetGlobalShaderMap(), SetShaderValue(), SetUAVParameter(), UAV, UnsetUAVParameter(), UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
ClearUAVShader_T() [2/3]
template<EClearReplacementResourceType ResourceType, EClearReplacementValueType ValueType, uint32 NumChannels, bool bBarriers> void ClearUAVShader_T (FRHIComputeCommandList & RHICmdList, FRHIUnorderedAccessView * UAV, uint32 SizeX, uint32 SizeY, uint32 SizeZ, const typename TClearReplacementTypeSelector< ValueType >::Type(&) ClearValues[NumChannels], TFunctionRef< void(FRHIComputeShader *, const FShaderResourceParameter &, bool)> ResourceBindCallback) inline
Helper functions for running the clear replacement shader for specific resource types, values types and number of channels.
Can be used from inside RHIs via FRHICommandList_RecursiveHazardous. ResourceBindCallback is provided to allow the RHI to override how the UAV resource is bound to the underlying platform context..
Definition at line 354 of file ClearReplacementShaders.h.
References TShaderRefBase< ShaderType, PointerTableType >::GetComputeShader(), GetGlobalShaderMap(), SetShaderValue(), UAV, UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
Referenced by ClearUAVShader_T().
ClearUAVShader_T() [3/3]
template<EClearReplacementResourceType ResourceType, uint32 NumChannels, bool bBarriers> void ClearUAVShader_T (FRHIComputeCommandList & RHICmdList, FRHIUnorderedAccessView * UAV, uint32 SizeX, uint32 SizeY, uint32 SizeZ, const void * ClearValues, EClearReplacementValueType ValueType) inline
Definition at line 433 of file ClearReplacementShaders.h.
References ClearUAVShader_T(), Float, Int32, UAV, and Uint32.