Unreal Engine 5.6 C++ API: FDisplayClusterLightCardEditorHelper Struct Reference
FDisplayClusterLightCardEditorHelper Struct Reference
Helper class for moving lightcards in an nDisplay cluster in various projection modes.
#include "DisplayClusterLightCardEditorHelper.h"
Data Structures
struct FAddLightCardArgs
struct FSpawnActorArgs
struct FSphericalCoordinates
Public Types
enum class ECoordinateSystem : uint8 { Cartesian , Spherical }
Public Member Functions
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper ()
Create a projection helper that automatically creates its own preview renderer for normal map generation.
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper (int32 RendererId)
Create a projection helper that uses an existing preview renderer for normal map generation.
DISPLAYCLUSTERSCENEPREVIEW_API ~FDisplayClusterLightCardEditorHelper ()
Clean up the projection renderer and any data used by the helper.
DISPLAYCLUSTERSCENEPREVIEW_API bool CalculateNormalAndPositionInDirection (const FVector &InOrigin, const FVector &InDirection, FVector &OutWorldPosition, FVector &OutRelativeNormal, double InDesiredDistanceFromFlush=0.)
Calculates the relative normal vector and world position in the specified direction from the given origin.
DISPLAYCLUSTERSCENEPREVIEW_API bool CalculateOriginAndDirectionFromPixelPosition (const FIntPoint &InPixelPos, const FSceneView &InSceneView, const FVector &InOriginOffset, FVector &OutOrigin, FVector &OutDirection)
Calculates the desired direction from the origin given a pixel position within the view.
DISPLAYCLUSTERSCENEPREVIEW_API void ConfigureRenderProjectionSettings (FDisplayClusterMeshProjectionRenderSettings &OutRenderSettings, FVector ViewLocation=FVector::ZeroVector) const
Sets up projection-related settings of a preview render in a consistent way.
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterMeshProjectionPrimitiveFilter::FPrimitiveFilter CreateDefaultShouldApplyProjectionToPrimitiveFilter () const
Creates the default ShouldApplyProjectionToPrimitive filter that most FDisplayClusterMeshProjectionRenderSettings will use.
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterMeshProjectionPrimitiveFilter::FPrimitiveFilter CreateDefaultShouldRenderPrimitiveFilter () const
Creates the default ShouldRenderPrimitive filter that most FDisplayClusterMeshProjectionRenderSettings will use.
DISPLAYCLUSTERSCENEPREVIEW_API void DragActors (const TArray< FDisplayClusterWeakStageActorPtr > &Actors, const FIntPoint &PixelPos, const FSceneView &SceneView, ECoordinateSystem CoordinateSystem, const FVector &DragWidgetOffset, EAxisList::Type DragAxis, FDisplayClusterWeakStageActorPtr PrimaryActor=nullptr)
Moves specified cards to a coordinate in viewport space as if dragged by a translate widget.
DISPLAYCLUSTERSCENEPREVIEW_API void DragUVActors (const TArray< FDisplayClusterWeakStageActorPtr > &Actors, const FIntPoint &PixelPos, const FSceneView &SceneView, const FVector &DragWidgetOffset, EAxisList::Type DragAxis, FDisplayClusterWeakStageActorPtr PrimaryActor=nullptr)
Moves specified UV actors to a coordinate in viewport space as if dragged by a translate widget.
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates GetActorCoordinates (const FDisplayClusterWeakStageActorPtr &Actor)
Gets the spherical coordinates of the specified actor.
DISPLAYCLUSTERSCENEPREVIEW_API bool GetIsOrthographic () const
Get whether this is using an orthographic projection.
DISPLAYCLUSTERSCENEPREVIEW_API EDisplayClusterMeshProjectionType GetProjectionMode () const
Get the projection mode to use.
DISPLAYCLUSTERSCENEPREVIEW_API void GetSceneViewInitOptions (FSceneViewInitOptions &OutViewInitOptions, float InFOV, const FIntPoint &InViewportSize, const FVector &InLocation, const FRotator &InRotation, const EAspectRatioAxisConstraint InAspectRatioAxisConstraint=EAspectRatioAxisConstraint::AspectRatio_MaintainYFOV, float InNearClipPlane=GNearClippingPlane, const FMatrix *InRotationMatrix=nullptr, float InDPIScale=1.f)
Sets up FSceneViewInitOptions' basic settings in a consistent way for preview renders.
DISPLAYCLUSTERSCENEPREVIEW_API void MoveActorsTo (const TArray< FDisplayClusterWeakStageActorPtr > &Actors, const FSphericalCoordinates &SphericalCoords)
Moves specified actors to desired coordinates.
DISPLAYCLUSTERSCENEPREVIEW_API void MoveActorsToPixel (const TArray< FDisplayClusterWeakStageActorPtr > &Actors, const FIntPoint &PixelPos, const FSceneView &SceneView)
Moves the given light cards to the specified pixel position within the provided scene view.
DISPLAYCLUSTERSCENEPREVIEW_API void PixelToWorld (const FSceneView &View, const FIntPoint &PixelPos, FVector &OutOrigin, FVector &OutDirection) const
Converts a pixel coordinate into a point and direction vector in world space.
DISPLAYCLUSTERSCENEPREVIEW_API void SetEditorViewportClient (TWeakPtr< FEditorViewportClient > InViewportClient)
Set the viewport client for which this is handling rendering.
DISPLAYCLUSTERSCENEPREVIEW_API void SetIsOrthographic (bool bValue)
Set whether to use an orthographic projection.
DISPLAYCLUSTERSCENEPREVIEW_API void SetLevelInstanceRootActor (ADisplayClusterRootActor &NewRootActor)
If the root actor is a proxy, use this to set the corresponding level instance that is being proxied.
DISPLAYCLUSTERSCENEPREVIEW_API void SetProjectionMode (EDisplayClusterMeshProjectionType Value)
Set the projection mode to use.
DISPLAYCLUSTERSCENEPREVIEW_API void SetRootActor (ADisplayClusterRootActor &NewRootActor)
Set the root actor of the DisplayCluster being controlled.
UE_DEPRECATED (5.3, "The raw stage geoemetry normal maps are no longer exposed by the stage geometry component") DISPLAYCLUSTERSCENEPREVIEW_API const UTexture2D *GetNormalMapTexture(bool bShowNorthMap)
Get (or generate) a visualization of one of the helper's normal maps.
DISPLAYCLUSTERSCENEPREVIEW_API void VerifyAndFixActorOrigin (const FDisplayClusterWeakStageActorPtr &Actor)
Ensures that the actor root component is at the same location as the projection/origin.
DISPLAYCLUSTERSCENEPREVIEW_API bool WorldToPixel (const FSceneView &View, const FVector &WorldPos, FVector2D &OutPixelPos) const
Converts a world coordinate into a point in screen space, and returns true if the world position is on the screen.
DISPLAYCLUSTERSCENEPREVIEW_API bool WorldToPixel (const FSceneView &View, const FVector &WorldPos, FVector2D &OutPixelPos, EDisplayClusterMeshProjectionType OverrideProjectionMode) const
Converts a world coordinate into a point in screen space using a specific projection mode, and returns true if the world position is on the screen.
Static Public Member Functions
static DISPLAYCLUSTERSCENEPREVIEW_API void AddLightCardsToRootActor (const TArray< ADisplayClusterLightCardActor * > &LightCards, ADisplayClusterRootActor *RootActor, const FAddLightCardArgs &AddLightCardArgs=FAddLightCardArgs())
Adds the given Light Card to the root actor.
static DISPLAYCLUSTERSCENEPREVIEW_API AActor * SpawnStageActor (const FSpawnActorArgs &InSpawnArgs)
Spawns a new actor for stage use and adds it to the root actor if it is a light card.
Private Member Functions
double CalculateFinalLightCardDistance (double FlushDistance, double DesiredOffsetFromFlush=0.) const
Calculates the final distance from the origin of a light card, given its flush distance and a desired offset.
FRotator GetActorRotationDelta (const FIntPoint &PixelPos, const FSceneView &View, const FDisplayClusterWeakStageActorPtr &Actor, ECoordinateSystem CoordinateSystem, EAxisList::Type DragAxis, const FVector &DragWidgetOffset)
Determines the appropriate delta rotation needed to move the specified light card to the given position within the view.
FSphericalCoordinates GetActorTranslationDelta (const FIntPoint &PixelPos, const FSceneView &View, const FDisplayClusterWeakStageActorPtr &Actor, ECoordinateSystem CoordinateSystem, EAxisList::Type DragAxis, const FVector &DragWidgetOffset)
Determines the appropriate delta in spherical coordinates needed to move the specified actor to the given position within the view.
FVector GetProjectionOrigin () const
Get the origin point of the projection from the ProjectionOriginComponent (or root actor as a fallback).
FVector2D GetUVActorTranslationDelta (const FIntPoint &PixelPos, const FSceneView &View, const FDisplayClusterWeakStageActorPtr &Actor, EAxisList::Type DragAxis, const FVector &DragWidgetOffset)
Determines the appropriate delta in UV coordinates needed to move the specified UV actor to the given position within the view.
void InternalDragActors (const TArray< FDisplayClusterWeakStageActorPtr > &Actors, const FIntPoint &PixelPos, const FSceneView &View, ECoordinateSystem CoordinateSystem, const FVector &DragWidgetOffset, EAxisList::Type DragAxis, FDisplayClusterWeakStageActorPtr PrimaryActor)
Moves specified actors to a coordinate in viewport space as if dragged by a widget.
void InternalMoveActorTo (const FDisplayClusterWeakStageActorPtr &Actor, const FSphericalCoordinates &Position, bool bIsFinalChange) const
Moves specified actor to desired coordinates immediately using the current normal maps.
void InvalidateNormalMap ()
Invalidates the viewport's normal map, forcing it to be re-rendered before using it next.
void OnWorldCleanup (UWorld *World, bool bSessionEnded, bool bCleanupResources)
Called when a world beings cleanup.
void PostEditChangePropertiesForMovedActor (const FDisplayClusterWeakStageActorPtr &Actor) const
Send property change events for any properties that may have changed due to a actor being moved.
void SetActorCoordinates (const FDisplayClusterWeakStageActorPtr &Actor, const FSphericalCoordinates &SphericalCoords) const
Sets the actor position to the given spherical coordinates.
FVector TraceScreenRay (const FVector &RayOrigin, const FVector &RayDirection, const FVector &ViewOrigin)
Traces the world geometry to find the best direction vector from the origin to a valid point in space using a screen ray.
bool TraceStage (const FVector &RayStart, const FVector &RayEnd, FVector &OutHitLocation)
Performs a ray trace against the stage's geometry, and returns the hit point.
void UpdateNormalMapMesh ()
Update the normal map mesh.
bool UpdateNormalMaps ()
Update the normal maps and mesh if necessary.
USceneComponent * UpdateProjectionOriginComponent ()
Update the cached pointer to the component marking the origin point of the projection and return it.
ADisplayClusterRootActor * UpdateRootActor ()
Update the cached pointer to the root actor from the associated preview renderer and, if the actor has changed, update related data.
Private Attributes
bool bCreatedRenderer = false
Whether this created its own preview renderer (and therefore is responsible for destroying it).
bool bIsOrthographic = false
If true, this is using an orthographic projection mode.
bool bNormalMapInvalid = false
Indicates if the cached normal map is invalid and needs to be redrawn.
TWeakObjectPtr< ADisplayClusterRootActor > CachedRootActor
The cached root actor of the DisplayCluster being controlled.
TWeakObjectPtr< ADisplayClusterRootActor > LevelInstanceRootActor
The level instance root actor of the DisplayCluster being controlled, if RootActor is a proxy.
TWeakObjectPtr< UProceduralMeshComponent > NormalMapMeshComponent
A morphed ico-sphere mesh component that approximates the normal and depth map.
TSharedPtr< FPreviewScene > NormalMeshScene
The preview scene containing NormalMapMeshComponent.
EDisplayClusterMeshProjectionType ProjectionMode
The projection mode of the view this is helping.
TWeakObjectPtr< USceneComponent > ProjectionOriginComponent
The component of the root actor that is acting as the projection origin.
int32 RendererId
The ID of the preview renderer used for normal map generation, as returned by IDisplayClusterScenePreview.
float RootActorBoundingRadius = 0.0f
The radius of the bounding sphere that entirely encapsulates the root actor.
TWeakPtr< FEditorViewportClient > ViewportClient
The viewport client for which this is handling projections.
Detailed Description
Helper class for moving lightcards in an nDisplay cluster in various projection modes.
Contains functions to perform coordinate conversion, scene setup, and lightcard movement, and manages the normal maps needed to convert from projected to world coordinates.
Definition at line 33 of file DisplayClusterLightCardEditorHelper.h.
Member Enumeration Documentation
ECoordinateSystem
enum class FDisplayClusterLightCardEditorHelper::ECoordinateSystem : uint8 strong
Enumerator
Cartesian
Spherical
Definition at line 36 of file DisplayClusterLightCardEditorHelper.h.
Constructor & Destructor Documentation
FDisplayClusterLightCardEditorHelper() [1/2]
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper::FDisplayClusterLightCardEditorHelper ()
Create a projection helper that automatically creates its own preview renderer for normal map generation.
FDisplayClusterLightCardEditorHelper() [2/2]
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper::FDisplayClusterLightCardEditorHelper (int32 RendererId)
Create a projection helper that uses an existing preview renderer for normal map generation.
References RendererId.
~FDisplayClusterLightCardEditorHelper()
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterLightCardEditorHelper::~FDisplayClusterLightCardEditorHelper ()
Clean up the projection renderer and any data used by the helper.
Member Function Documentation
AddLightCardsToRootActor()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::AddLightCardsToRootActor (const TArray< ADisplayClusterLightCardActor * > & LightCards, ADisplayClusterRootActor * RootActor, const FAddLightCardArgs & AddLightCardArgs = FAddLightCardArgs()) static
Adds the given Light Card to the root actor.
CalculateFinalLightCardDistance()
double FDisplayClusterLightCardEditorHelper::CalculateFinalLightCardDistance (double FlushDistance, double DesiredOffsetFromFlush = 0.) const private
Calculates the final distance from the origin of a light card, given its flush distance and a desired offset.
CalculateNormalAndPositionInDirection()
DISPLAYCLUSTERSCENEPREVIEW_API bool FDisplayClusterLightCardEditorHelper::CalculateNormalAndPositionInDirection (const FVector & InOrigin, const FVector & InDirection, FVector & OutWorldPosition, FVector & OutRelativeNormal, double InDesiredDistanceFromFlush = 0.)
Calculates the relative normal vector and world position in the specified direction from the given origin.
Parameters
InOrigin The origin point of the view.
InDirection The direction in which check the normal.
OutWorldPosition The world-space coordinates of the calculated position.
OutRelativeNormal The normal vector at the calculated position.
InDesiredDistanceFromFlush The desired flush distance from the initial calculated position.
Returns
true if the position was found, or false if the normal maps need to be updated first.
References CalculateNormalAndPositionInDirection(), and FVector.
Referenced by CalculateNormalAndPositionInDirection().
CalculateOriginAndDirectionFromPixelPosition()
DISPLAYCLUSTERSCENEPREVIEW_API bool FDisplayClusterLightCardEditorHelper::CalculateOriginAndDirectionFromPixelPosition (const FIntPoint & InPixelPos, const FSceneView & InSceneView, const FVector & InOriginOffset, FVector & OutOrigin, FVector & OutDirection)
Calculates the desired direction from the origin given a pixel position within the view.
Parameters
InPixelPos The desired position within the view in pixels.
InSceneView The view that was displayed when the pixel position was chosen.
InOriginOffset An offset to apply to the origin before calling TraceScreenRay (if this is in orthographic mode).
OutOrigin The origin point of the view.
OutDirection The direction relative to the origin.
Returns
true if the direction was found
References CalculateOriginAndDirectionFromPixelPosition(), and FVector.
Referenced by CalculateOriginAndDirectionFromPixelPosition().
ConfigureRenderProjectionSettings()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::ConfigureRenderProjectionSettings (FDisplayClusterMeshProjectionRenderSettings & OutRenderSettings, FVector ViewLocation = FVector::ZeroVector) const
Sets up projection-related settings of a preview render in a consistent way.
This includes the ProjectionType and its related ProjectionTypeSettings. If provided, the UV projection's panning settings will updated to reflect the ViewLocation passed in.
References ConfigureRenderProjectionSettings(), and FVector.
Referenced by ConfigureRenderProjectionSettings().
CreateDefaultShouldApplyProjectionToPrimitiveFilter()
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterMeshProjectionPrimitiveFilter::FPrimitiveFilter FDisplayClusterLightCardEditorHelper::CreateDefaultShouldApplyProjectionToPrimitiveFilter () const
Creates the default ShouldApplyProjectionToPrimitive filter that most FDisplayClusterMeshProjectionRenderSettings will use.
Filters actors so that in UV projection mode, UV light cards are rendered linearly.
References CreateDefaultShouldApplyProjectionToPrimitiveFilter().
Referenced by CreateDefaultShouldApplyProjectionToPrimitiveFilter().
CreateDefaultShouldRenderPrimitiveFilter()
DISPLAYCLUSTERSCENEPREVIEW_API FDisplayClusterMeshProjectionPrimitiveFilter::FPrimitiveFilter FDisplayClusterLightCardEditorHelper::CreateDefaultShouldRenderPrimitiveFilter () const
Creates the default ShouldRenderPrimitive filter that most FDisplayClusterMeshProjectionRenderSettings will use.
Filters actors so that only UV lightcards are shown in UV mode, and only non-UV light cards are shown otherwise.
References CreateDefaultShouldRenderPrimitiveFilter().
Referenced by CreateDefaultShouldRenderPrimitiveFilter().
DragActors()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::DragActors (const TArray< FDisplayClusterWeakStageActorPtr > & Actors, const FIntPoint & PixelPos, const FSceneView & SceneView, ECoordinateSystem CoordinateSystem, const FVector & DragWidgetOffset, EAxisList::Type DragAxis, FDisplayClusterWeakStageActorPtr PrimaryActor = nullptr)
Moves specified cards to a coordinate in viewport space as if dragged by a translate widget.
Parameters
Actors The actors that we are moving
PixelPos The screen pixel position of the widget
SceneView The scene view used to convert from pixel position to 3D position
CoordinateSystem The coordinate system to use when computing drag constraints
DragWidgetOffset The offset between the actual cursor position and the position of the widget when the drag action started
DragAxis The axis along which the widget is being dragged
PrimaryActor The actor used to calculate the translation/rotation delta. If not provided, the last entry in Actors will be used.
References Actors, CoordinateSystem, DragActors(), and FVector.
Referenced by DragActors().
DragUVActors()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::DragUVActors (const TArray< FDisplayClusterWeakStageActorPtr > & Actors, const FIntPoint & PixelPos, const FSceneView & SceneView, const FVector & DragWidgetOffset, EAxisList::Type DragAxis, FDisplayClusterWeakStageActorPtr PrimaryActor = nullptr)
Moves specified UV actors to a coordinate in viewport space as if dragged by a translate widget.
Parameters
Actors The actors that we are moving
PixelPos The screen pixel position of the widget
SceneView The scene view used to convert from pixel position to 3D position
DragWidgetOffset The offset between the actual cursor position and the position of the widget when the drag action started
DragAxis The axis along which the widget is being dragged
PrimaryActor The actor used to calculate the translation/rotation delta. If not provided, the last entry in Actors will be used.
References Actors, DragUVActors(), and FVector.
Referenced by DragUVActors().
GetActorCoordinates()
DISPLAYCLUSTERSCENEPREVIEW_API FSphericalCoordinates FDisplayClusterLightCardEditorHelper::GetActorCoordinates (const FDisplayClusterWeakStageActorPtr & Actor)
Gets the spherical coordinates of the specified actor.
References Actor, and GetActorCoordinates().
Referenced by GetActorCoordinates().
GetActorRotationDelta()
FRotator FDisplayClusterLightCardEditorHelper::GetActorRotationDelta (const FIntPoint & PixelPos, const FSceneView & View, const FDisplayClusterWeakStageActorPtr & Actor, ECoordinateSystem CoordinateSystem, EAxisList::Type DragAxis, const FVector & DragWidgetOffset) private
Determines the appropriate delta rotation needed to move the specified light card to the given position within the view.
References Actor, CoordinateSystem, and FVector.
GetActorTranslationDelta()
FSphericalCoordinates FDisplayClusterLightCardEditorHelper::GetActorTranslationDelta (const FIntPoint & PixelPos, const FSceneView & View, const FDisplayClusterWeakStageActorPtr & Actor, ECoordinateSystem CoordinateSystem, EAxisList::Type DragAxis, const FVector & DragWidgetOffset) private
Determines the appropriate delta in spherical coordinates needed to move the specified actor to the given position within the view.
References Actor, CoordinateSystem, and FVector.
GetIsOrthographic()
DISPLAYCLUSTERSCENEPREVIEW_API bool FDisplayClusterLightCardEditorHelper::GetIsOrthographic () const
Get whether this is using an orthographic projection.
GetProjectionMode()
DISPLAYCLUSTERSCENEPREVIEW_API EDisplayClusterMeshProjectionType FDisplayClusterLightCardEditorHelper::GetProjectionMode () const
Get the projection mode to use.
GetProjectionOrigin()
FVector FDisplayClusterLightCardEditorHelper::GetProjectionOrigin () const private
Get the origin point of the projection from the ProjectionOriginComponent (or root actor as a fallback).
References FVector.
GetSceneViewInitOptions()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::GetSceneViewInitOptions (FSceneViewInitOptions & OutViewInitOptions, float InFOV, const FIntPoint & InViewportSize, const FVector & InLocation, const FRotator & InRotation, const EAspectRatioAxisConstraint InAspectRatioAxisConstraint = EAspectRatioAxisConstraint::AspectRatio_MaintainYFOV, float InNearClipPlane = GNearClippingPlane, const FMatrix * InRotationMatrix = nullptr, float InDPIScale = 1.f)
Sets up FSceneViewInitOptions' basic settings in a consistent way for preview renders.
If RotationMatrix is not provided, one will be automatically generated based on the view rotation.
References FVector, GetSceneViewInitOptions(), and GNearClippingPlane.
Referenced by GetSceneViewInitOptions().
GetUVActorTranslationDelta()
FVector2D FDisplayClusterLightCardEditorHelper::GetUVActorTranslationDelta (const FIntPoint & PixelPos, const FSceneView & View, const FDisplayClusterWeakStageActorPtr & Actor, EAxisList::Type DragAxis, const FVector & DragWidgetOffset) private
Determines the appropriate delta in UV coordinates needed to move the specified UV actor to the given position within the view.
References Actor, and FVector.
InternalDragActors()
void FDisplayClusterLightCardEditorHelper::InternalDragActors (const TArray< FDisplayClusterWeakStageActorPtr > & Actors, const FIntPoint & PixelPos, const FSceneView & View, ECoordinateSystem CoordinateSystem, const FVector & DragWidgetOffset, EAxisList::Type DragAxis, FDisplayClusterWeakStageActorPtr PrimaryActor) private
Moves specified actors to a coordinate in viewport space as if dragged by a widget.
Requires valid normal maps.
References Actors, CoordinateSystem, and FVector.
InternalMoveActorTo()
void FDisplayClusterLightCardEditorHelper::InternalMoveActorTo (const FDisplayClusterWeakStageActorPtr & Actor, const FSphericalCoordinates & Position, bool bIsFinalChange) const private
Moves specified actor to desired coordinates immediately using the current normal maps.
Requires valid normal maps.
References Actor, and Position.
InvalidateNormalMap()
void FDisplayClusterLightCardEditorHelper::InvalidateNormalMap () private
Invalidates the viewport's normal map, forcing it to be re-rendered before using it next.
MoveActorsTo()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::MoveActorsTo (const TArray< FDisplayClusterWeakStageActorPtr > & Actors, const FSphericalCoordinates & SphericalCoords)
Moves specified actors to desired coordinates.
Actual radius will be based on flush constraint and actor's RadialOffset.
Parameters
Actors The actors that we are moving
SphericalCoords The desired location of the actors in spherical coordinates with respect to origin.
References Actors, and MoveActorsTo().
Referenced by MoveActorsTo().
MoveActorsToPixel()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::MoveActorsToPixel (const TArray< FDisplayClusterWeakStageActorPtr > & Actors, const FIntPoint & PixelPos, const FSceneView & SceneView)
Moves the given light cards to the specified pixel position within the provided scene view.
Parameters
Actors The actors that we are moving
PixelPos The pixel location to move the actors to
SceneView The scene view used to convert from pixel position to 3D position
References Actors, and MoveActorsToPixel().
Referenced by MoveActorsToPixel().
OnWorldCleanup()
void FDisplayClusterLightCardEditorHelper::OnWorldCleanup (UWorld * World, bool bSessionEnded, bool bCleanupResources) private
Called when a world beings cleanup.
We destroy our preview scene if the world containing the root actor is cleaned up.
PixelToWorld()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::PixelToWorld (const FSceneView & View, const FIntPoint & PixelPos, FVector & OutOrigin, FVector & OutDirection) const
Converts a pixel coordinate into a point and direction vector in world space.
References FVector, and PixelToWorld().
Referenced by PixelToWorld().
PostEditChangePropertiesForMovedActor()
void FDisplayClusterLightCardEditorHelper::PostEditChangePropertiesForMovedActor (const FDisplayClusterWeakStageActorPtr & Actor) const private
Send property change events for any properties that may have changed due to a actor being moved.
References Actor.
SetActorCoordinates()
void FDisplayClusterLightCardEditorHelper::SetActorCoordinates (const FDisplayClusterWeakStageActorPtr & Actor, const FSphericalCoordinates & SphericalCoords) const private
Sets the actor position to the given spherical coordinates.
References Actor.
SetEditorViewportClient()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::SetEditorViewportClient (TWeakPtr< FEditorViewportClient > InViewportClient)
Set the viewport client for which this is handling rendering.
If set, its data will be included in the SceneViewInitOptions generated by this helper.
SetIsOrthographic()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::SetIsOrthographic (bool bValue)
Set whether to use an orthographic projection.
SetLevelInstanceRootActor()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::SetLevelInstanceRootActor (ADisplayClusterRootActor & NewRootActor)
If the root actor is a proxy, use this to set the corresponding level instance that is being proxied.
SetProjectionMode()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::SetProjectionMode (EDisplayClusterMeshProjectionType Value)
Set the projection mode to use.
References Value.
SetRootActor()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::SetRootActor (ADisplayClusterRootActor & NewRootActor)
Set the root actor of the DisplayCluster being controlled.
This will also update the renderer's root actor. Don't call this if the helper was created with an existing preview renderer, as it will automatically the root actor from that renderer.
SpawnStageActor()
DISPLAYCLUSTERSCENEPREVIEW_API AActor * FDisplayClusterLightCardEditorHelper::SpawnStageActor (const FSpawnActorArgs & InSpawnArgs) static
Spawns a new actor for stage use and adds it to the root actor if it is a light card.
TraceScreenRay()
FVector FDisplayClusterLightCardEditorHelper::TraceScreenRay (const FVector & RayOrigin, const FVector & RayDirection, const FVector & ViewOrigin) private
Traces the world geometry to find the best direction vector from the origin to a valid point in space using a screen ray.
Requires valid normal maps.
References FVector.
TraceStage()
bool FDisplayClusterLightCardEditorHelper::TraceStage (const FVector & RayStart, const FVector & RayEnd, FVector & OutHitLocation) private
Performs a ray trace against the stage's geometry, and returns the hit point.
References FVector.
UE_DEPRECATED()
FDisplayClusterLightCardEditorHelper::UE_DEPRECATED (5. 3, "The raw stage geoemetry normal maps are no longer exposed by the stage geometry component") const
Get (or generate) a visualization of one of the helper's normal maps.
Parameters
bShowNorthMap If true, return the texture for the north normal map. Otherwise, return the texture for the south normal map.
UpdateNormalMapMesh()
void FDisplayClusterLightCardEditorHelper::UpdateNormalMapMesh () private
Update the normal map mesh.
Only call this once both maps are valid.
UpdateNormalMaps()
bool FDisplayClusterLightCardEditorHelper::UpdateNormalMaps () private
Update the normal maps and mesh if necessary.
Returns true if there are now valid normal maps to read from.
UpdateProjectionOriginComponent()
USceneComponent * FDisplayClusterLightCardEditorHelper::UpdateProjectionOriginComponent () private
Update the cached pointer to the component marking the origin point of the projection and return it.
Note that this has a cost, so avoid calling it frequently.
UpdateRootActor()
ADisplayClusterRootActor * FDisplayClusterLightCardEditorHelper::UpdateRootActor () private
Update the cached pointer to the root actor from the associated preview renderer and, if the actor has changed, update related data.
Returns the root actor.
VerifyAndFixActorOrigin()
DISPLAYCLUSTERSCENEPREVIEW_API void FDisplayClusterLightCardEditorHelper::VerifyAndFixActorOrigin (const FDisplayClusterWeakStageActorPtr & Actor)
Ensures that the actor root component is at the same location as the projection/origin.
References Actor, and VerifyAndFixActorOrigin().
Referenced by VerifyAndFixActorOrigin().
WorldToPixel() [1/2]
DISPLAYCLUSTERSCENEPREVIEW_API bool FDisplayClusterLightCardEditorHelper::WorldToPixel (const FSceneView & View, const FVector & WorldPos, FVector2D & OutPixelPos) const
Converts a world coordinate into a point in screen space, and returns true if the world position is on the screen.
References FVector, and WorldToPixel().
Referenced by WorldToPixel(), and WorldToPixel().
WorldToPixel() [2/2]
DISPLAYCLUSTERSCENEPREVIEW_API bool FDisplayClusterLightCardEditorHelper::WorldToPixel (const FSceneView & View, const FVector & WorldPos, FVector2D & OutPixelPos, EDisplayClusterMeshProjectionType OverrideProjectionMode) const
Converts a world coordinate into a point in screen space using a specific projection mode, and returns true if the world position is on the screen.
References FVector, and WorldToPixel().
Field Documentation
bCreatedRenderer
bool FDisplayClusterLightCardEditorHelper::bCreatedRenderer = false private
Whether this created its own preview renderer (and therefore is responsible for destroying it).
Definition at line 400 of file DisplayClusterLightCardEditorHelper.h.
bIsOrthographic
bool FDisplayClusterLightCardEditorHelper::bIsOrthographic = false private
If true, this is using an orthographic projection mode.
Definition at line 403 of file DisplayClusterLightCardEditorHelper.h.
bNormalMapInvalid
bool FDisplayClusterLightCardEditorHelper::bNormalMapInvalid = false private
Indicates if the cached normal map is invalid and needs to be redrawn.
Definition at line 406 of file DisplayClusterLightCardEditorHelper.h.
CachedRootActor
TWeakObjectPtr<ADisplayClusterRootActor> FDisplayClusterLightCardEditorHelper::CachedRootActor private
The cached root actor of the DisplayCluster being controlled.
You should generally use UpdateRootActor() instead of accessing this directly.
Definition at line 382 of file DisplayClusterLightCardEditorHelper.h.
LevelInstanceRootActor
TWeakObjectPtr<ADisplayClusterRootActor> FDisplayClusterLightCardEditorHelper::LevelInstanceRootActor private
The level instance root actor of the DisplayCluster being controlled, if RootActor is a proxy.
Definition at line 385 of file DisplayClusterLightCardEditorHelper.h.
NormalMapMeshComponent
TWeakObjectPtr<UProceduralMeshComponent> FDisplayClusterLightCardEditorHelper::NormalMapMeshComponent private
A morphed ico-sphere mesh component that approximates the normal and depth map.
Definition at line 379 of file DisplayClusterLightCardEditorHelper.h.
NormalMeshScene
TSharedPtr<FPreviewScene> FDisplayClusterLightCardEditorHelper::NormalMeshScene private
The preview scene containing NormalMapMeshComponent.
Definition at line 376 of file DisplayClusterLightCardEditorHelper.h.
ProjectionMode
EDisplayClusterMeshProjectionType FDisplayClusterLightCardEditorHelper::ProjectionMode private
The projection mode of the view this is helping.
Definition at line 391 of file DisplayClusterLightCardEditorHelper.h.
ProjectionOriginComponent
TWeakObjectPtr<USceneComponent> FDisplayClusterLightCardEditorHelper::ProjectionOriginComponent private
The component of the root actor that is acting as the projection origin.
Can be either the root component (stage origin) or a view point component
Definition at line 388 of file DisplayClusterLightCardEditorHelper.h.
RendererId
int32 FDisplayClusterLightCardEditorHelper::RendererId private
The ID of the preview renderer used for normal map generation, as returned by IDisplayClusterScenePreview.
Definition at line 394 of file DisplayClusterLightCardEditorHelper.h.
Referenced by FDisplayClusterLightCardEditorHelper().
RootActorBoundingRadius
float FDisplayClusterLightCardEditorHelper::RootActorBoundingRadius = 0.0f private
The radius of the bounding sphere that entirely encapsulates the root actor.
Definition at line 397 of file DisplayClusterLightCardEditorHelper.h.
ViewportClient
TWeakPtr<FEditorViewportClient> FDisplayClusterLightCardEditorHelper::ViewportClient private
The viewport client for which this is handling projections.
This can be null.
Definition at line 372 of file DisplayClusterLightCardEditorHelper.h.
The documentation for this struct was generated from the following file:
DisplayClusterLightCardEditorHelper.h