Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Engine/ActorInstanceHandle.h File Reference
ActorInstanceHandle.h File Reference
#include "UObject/WeakInterfacePtr.h"
#include "ActorInstanceHandle.generated.h"
Typedefs
using FActorInstanceManagerInterface = TWeakInterfacePtr<IActorInstanceManagerInterface>
Functions
USTRUCT () struct FActorInstanceHandle
Handle to a unique object.
Typedef Documentation
FActorInstanceManagerInterface
using FActorInstanceManagerInterface = TWeakInterfacePtr<IActorInstanceManagerInterface>
Definition at line 14 of file ActorInstanceHandle.h.
Function Documentation
USTRUCT()
USTRUCT ()
Handle to a unique object.
This may specify a full weigh actor or it may only specify the actor instance that represents the same object.
Note
The handle has game thread constraints related to UObjects and should be used carefully from other threads.
Can only be used on the game thread
all constructors
all getters (GetXYZ, FetchActor, IsActorValid, DoesRepresent) *
comparison operators against live AActor pointer
Can be used on any thread
MakeActorHandleToResolve to create a handle that will be lazily resolved on the game thread since it only stores a weak object ptr without any access to the live object
handle validity and comparison operators against another handle (i.e. IsValid(), operator==|!=(const FActorInstanceHandle& Other))
A path dedicated to creation of handles while converting actor to a dehydrated representation. This path ensures an actor won't be spawned as a side effect of looking for the actor given Manager/Index represents
A path dedicated to creation of handles from any threads. This path marks the handle as need resolving once it gets accessed from the game thread.
If this handle has a valid actor, return it; otherwise return the actor responsible for managing the instances.
Returns either the actor's root component or the root component for the manager associated with the handle
Returns the actor specified by this handle. This may require loading and creating the actor object.
helper functions that let us treat the actor pointer as a UObject in templated functions these do NOT fetch the actor so they will return nullptr if we don't have a full actor representation
Returns true if Actor is not null and not pending kill
Weak UObject pointer used for two purposes:
a resolved handle uses it to store the AActor
a handle to be resolved uses it to store the UPrimitiveComponent provided by MakeActorHandleToResolve
Identifies the actor instance manager to use
Identifies the instance within the manager
Enum to keep track of the resolution status of the handle. It is only possible to safely resolve the handle on the game thread so other threads should use MakeActorHandleToResolve to safely create one.
Indicates if the handle is resolved, needs to be resolved (extract Actor|ManagerInterface)
Definition at line 31 of file ActorInstanceHandle.h.
References Ar, BlueprintType, bool, Cast(), FORCEINLINE, FVector, GENERATED_BODY, GetTypeHash(), Handle, INDEX_NONE, Invalid, IsValid(), operator!=(), operator<<(), operator=(), operator==(), Other, and UPROPERTY.