Unreal Engine 5.6 C++ API: Runtime/AIModule/Classes/AITypes.h File Reference
AITypes.h File Reference
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "UObject/ObjectMacros.h"
#include "Templates/SubclassOf.h"
#include "NavigationSystemTypes.h"
#include "AITypes.generated.h"
Data Structures
struct FAIBasicCounter< TCounterType >
struct FAIGenericID< TCounter >
struct FAINamedID< TCounter >
TCounter needs to supply following functions: default constructor typedef X Type; where X is an integer type to be used as ID's internal type TCounter::Type GetNextAvailableID() - returns next available ID and advances the internal counter uint32 GetSize() const - returns number of unique IDs created so far OnIndexForced(TCounter::Type Index) - called when given Index has been force-used.
struct FAIResCounter
struct FAIResourceLock
structure used to define which subsystem requested locking of a specific AI resource (like movement, logic, etc.)
struct FAIResourcesSet
Namespaces
namespace EAIForceParam
namespace EAILogicResuming
namespace EAIRequestPriority
namespace FAIMoveFlag
namespace FAIResources
namespace FAISystem
AIController is the base class of controllers for AI-controlled Pawns.
Macros
#define TEXT_AI_LOCATION(v)
Typedefs
typedef FAINamedID< FAIResCounter > FAIResourceID
typedef TSharedPtr< FMoveRequestCustomData, ESPMode::ThreadSafe > FCustomMoveSharedPtr
Enumerations
enum EAIForceParam::Type { EAIForceParam::Force , EAIForceParam::DoNotForce , EAIForceParam::UMETA =(Hidden) }
enum EAILogicResuming::Type { EAILogicResuming::Continue , EAILogicResuming::RestartedInstead }
Functions
FORCEINLINE EAIOptionFlag::Type FAISystem::BoolToAIOption (bool Value)
DECLARE_CYCLE_STAT_EXTERN (TEXT("Overall AI Time"), STAT_AI_Overall, STATGROUP_AI, AIMODULE_API)
AIMODULE_API const FAIResourceID & FAIResources::GetResource (int32 ResourceIndex)
AIMODULE_API int32 FAIResources::GetResourcesCount ()
AIMODULE_API FString FAIResources::GetSetDescription (FAIResourcesSet ResourceSet)
FORCEINLINE bool FAISystem::IsValidDirection (const FVector &TestVector)
FORCEINLINE bool FAISystem::IsValidLocation (const FVector &TestLocation)
FORCEINLINE bool FAISystem::IsValidOrientation (const FQuat &TestOrientation)
FORCEINLINE bool FAISystem::IsValidRotation (const FRotator &TestRotation)
FORCEINLINE bool FAISystem::PickAIOption (EAIOptionFlag::Type Option, bool DefaultOption)
AIMODULE_API void FAIResources::RegisterResource (const FAIResourceID &Resource)
UENUM () namespace EAIOptionFlag
USTRUCT () struct FAIRequestID
Variables
constexpr bool FAIMoveFlag::IgnorePathfinding = false
constexpr float FAISystem::InfiniteInterval = -FLT_MAX
constexpr FVector FAISystem::InvalidDirection = FVector(0, UE::Math::TVectorConstInit{})
constexpr FVector FAISystem::InvalidLocation = FVector(FLT_MAX, UE::Math::TVectorConstInit{})
AIMODULE_API const FQuat FAISystem::InvalidOrientation
constexpr float FAISystem::InvalidRange = -1.f
AIMODULE_API const FAIResourceID FAIResources::InvalidResource
AIMODULE_API const FRotator FAISystem::InvalidRotation
constexpr uint32 FAISystem::InvalidUnsignedID = uint32(INDEX_NONE)
AIMODULE_API const FAIResourceID FAIResources::Logic
constexpr int32 EAIRequestPriority::Lowest = EAIRequestPriority::Logic
AIMODULE_API const FAIResourceID FAIResources::Movement
AIMODULE_API const FAIResourceID FAIResources::Perception
constexpr bool FAIMoveFlag::StopOnOverlap = true
constexpr bool FAIMoveFlag::UsePathfinding = true
Macro Definition Documentation
TEXT_AI_LOCATION
#define TEXT_AI_LOCATION (v)
Value:
(FAISystem::IsValidLocation(v) ? *(v).ToString() : TEXT("Invalid"))
Definition at line 24 of file AITypes.h.
Typedef Documentation
FAIResourceID
typedef FAINamedID<FAIResCounter> FAIResourceID
Definition at line 298 of file AITypes.h.
FCustomMoveSharedPtr
typedef TSharedPtr<FMoveRequestCustomData, ESPMode::ThreadSafe> FCustomMoveSharedPtr
Definition at line 20 of file AITypes.h.
Function Documentation
DECLARE_CYCLE_STAT_EXTERN()
DECLARE_CYCLE_STAT_EXTERN (TEXT("Overall AI Time") , STAT_AI_Overall , STATGROUP_AI , AIMODULE_API)
UENUM()
UENUM ()
Actions requested by Level Designers by placing AI-hinting elements on the map.
Actions AI wants to do due to its internal logic.
Actions LDs really want AI to perform.
Actions being result of game-world mechanics, like hit reactions, death, falling, etc. In general things not depending on what AI's thinking.
Ultimate priority, to be used with caution, makes AI perform given action regardless of anything else (for example disabled reactions).
Definition at line 59 of file AITypes.h.
References Default, Disable, Enable, Hidden, MAX, and UMETA.
USTRUCT()
USTRUCT ()
returns true if given ID is identical to stored ID or any of considered IDs is FAIRequestID::AnyRequest
Defines if the underlying pathfind query should limit its exploration based on the navigation cost
Parameters
bApply if set - the pathfind query cost will be limited based on the heuristic between the start and end location
InCostLimitFactor this multiplier is used to compute a max node cost allowed to the open list (cost limit = CostLimitFactor*InitialHeuristicEstimate)
InMinimumCostLimit minimum cost limit clamping value (in cost units) used to allow large deviation in short paths
the request should be either set up to move to a location, of go to a valid actor
retrieves request's requested destination location, GoalActor's location or GoalLocation, depending on the request itself
move goal: actor
move goal: location
pathfinding: navigation filter to use
move goal is an actor
move goal is an actor
pathfinding: if set - regular pathfinding will be used, if not - direct path between two points
pathfinding: allow using incomplete path going toward goal but not reaching it
pathfinding: if set - require the end location to be linked to the navigation data
pathfinding: if set - the pathfind query cost will be limited based on the heuristic between the start and end location (c.f. CostLimitFactor and MinimumCostLimit).
pathfinding: goal location will be projected on navigation data before use
pathfinding: the request will start from the end of the previous path (if any), and the generated path will be merged with the remaining points of the previous path
pathfollowing: acceptance radius needs to be increased by agent radius (stop on overlap vs exact point)
pathfollowing: acceptance radius needs to be increased by goal actor radius
pathfollowing: keep focal point at move goal
pathfollowing: required distance to goal to complete move
pathfinding: this multiplier is used to compute a max node cost allowed to the open list (cost limit = CostLimitFactor*InitialHeuristicEstimate)
pathfinding: minimum cost limit clamping value (in cost units) used to allow large deviation in short paths
custom user data: structure
custom user data: flags
Returns
True if time's up
resets the countdown back to Interval
Note that this function returns meaningful results only if Interval > 0
Returns
If Interval > 0 returns time accumulated since resetting. Oterwise returns FallbackValue
Definition at line 401 of file AITypes.h.
References BlueprintType, FORCEINLINE, GENERATED_USTRUCT_BODY, IsValid(), operator=(), Other, ToString(), and UPROPERTY.