Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/AlignmentTemplates.h File Reference
AlignmentTemplates.h File Reference
#include "CoreTypes.h"
#include "Templates/IsIntegral.h"
#include "Templates/IsPointer.h"
Functions
template<typename T>
FORCEINLINE constexpr T Align (T Val, uint64 Alignment)
Aligns a value to the nearest higher multiple of 'Alignment', which must be a power of two.
template<typename T>
FORCEINLINE constexpr T AlignArbitrary (T Val, uint64 Alignment)
Aligns a value to the nearest higher multiple of 'Alignment'.
template<typename T>
FORCEINLINE constexpr T AlignDown (T Val, uint64 Alignment)
Aligns a value to the nearest lower multiple of 'Alignment', which must be a power of two.
template<typename T>
FORCEINLINE constexpr bool IsAligned (T Val, uint64 Alignment)
Checks if a pointer is aligned to the specified alignment.
Function Documentation
Align()
template<typename T> FORCEINLINE constexpr T Align (T Val, uint64 Alignment) constexpr
Aligns a value to the nearest higher multiple of 'Alignment', which must be a power of two.
Parameters
Val The value to align.
Alignment The alignment value, must be a power of two.
Returns
The value aligned up to the specified alignment.
Definition at line 18 of file AlignmentTemplates.h.
References FORCEINLINE, TIsIntegral< T >::Value, and TIsPointer< T >::Value.
Referenced by FOptionalPropertyLayout::CalcIsSetOffset(), FMemStackBase::FMemMark, New(), NewOned(), NewZeroed(), FMemStackBase::operator new, FMemStackBase::operator new, FMemStackBase::operator new, TConcurrentLinearObject< T, FSceneRenderingBlockAllocationTag >::operator new(), FMemStackBase::operator new[], FMemStackBase::operator new[], FMemStackBase::operator new[], and TConcurrentLinearObject< T, FSceneRenderingBlockAllocationTag >::operator new[]().
AlignArbitrary()
template<typename T> FORCEINLINE constexpr T AlignArbitrary (T Val, uint64 Alignment) constexpr
Aligns a value to the nearest higher multiple of 'Alignment'.
Parameters
Val The value to align.
Alignment The alignment value, can be any arbitrary value.
Returns
The value aligned up to the specified alignment.
Definition at line 66 of file AlignmentTemplates.h.
References FORCEINLINE, TIsIntegral< T >::Value, and TIsPointer< T >::Value.
Referenced by FMetasoundParameterPackStorage::AddArrayParameter(), FMetasoundParameterPackStorage::AddParameter(), MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::SizeOfParam(), and USTRUCT().
AlignDown()
template<typename T> FORCEINLINE constexpr T AlignDown (T Val, uint64 Alignment) constexpr
Aligns a value to the nearest lower multiple of 'Alignment', which must be a power of two.
Parameters
Val The value to align.
Alignment The alignment value, must be a power of two.
Returns
The value aligned down to the specified alignment.
Definition at line 34 of file AlignmentTemplates.h.
References FORCEINLINE, TIsIntegral< T >::Value, and TIsPointer< T >::Value.
Referenced by FMediaIOAudioOutput::ConvertAndUpmixBuffer(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Free(), and FMallocBinned2::GetPoolHeaderFromPointer().
IsAligned()
template<typename T> FORCEINLINE constexpr bool IsAligned (T Val, uint64 Alignment) constexpr
Checks if a pointer is aligned to the specified alignment.
Parameters
Val The value to align.
Alignment The alignment value, must be a power of two.
Returns
true if the pointer is aligned to the specified alignment, false otherwise.
Definition at line 50 of file AlignmentTemplates.h.
References FORCEINLINE, TIsIntegral< T >::Value, and TIsPointer< T >::Value.
Referenced by FVirtualAllocator::FVirtualAllocator(), TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObject< T >::~TObject(), TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T >::~TObjectArray(), TMaybeMappedAllocator< Alignment >::ForAnyElementType::AcceptFileMapping(), FMallocBinned2::FFreeBlock::AllocateBin(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::AllocateBlock(), FVirtualAllocator::AllocateVirtualPages(), FVirtualAllocator::AllocNewVM(), FPageCache::Commit(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::CreateArrayNoInit(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::CreateNoInit(), FPageCache::DecommitPending(), FPageCache::ForceDecommit(), TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 >::GetRawItem(), FMallocBinned2::IsOSAllocation(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc(), FPageCache::MarkForPendingDecommit(), MS_ALIGN(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::PromoteToLargerBin(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::QuantizeSizeCommon(), and FPageCache::TryDecommitPending().