Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Animation/AnimBank.h File Reference
AnimBank.h File Reference
#include "AnimationAsset.h"
#include "Experimental/Containers/RobinHoodHashTable.h"
#include "HLOD/HLODBatchingPolicy.h"
#include "Interfaces/Interface_AsyncCompilation.h"
#include "IO/IoHash.h"
#include "Logging/LogMacros.h"
#include "RenderCommandFence.h"
#include "SkinningDefinitions.h"
#include "UObject/ObjectPtr.h"
#include "UObject/WeakObjectPtr.h"
#include "AnimBank.generated.h"
Data Structures
struct FAnimBankData
struct FAnimBankDesc
struct FAnimBankDescKeyFuncs
struct FAnimBankEntry
struct FAnimBankRecord
struct FAnimBankRecordHandle
struct FSkinnedAssetMapping
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::AnimBank
Typedefs
using FAnimBankRecordMap = Experimental::TRobinHoodHashMap<FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs>
Functions
void UE::AnimBank::BuildSkinnedAssetMapping (const USkinnedAsset &Asset, FSkinnedAssetMapping &Mapping)
void UE::AnimBank::ConvertLocalToGlobalSpaceTransforms (const FReferenceSkeleton &InRefSkeleton, const TArray< FTransform > &InLocalSpaceTransforms, TArray< FTransform > &OutGlobalSpaceTransforms)
DECLARE_LOG_CATEGORY_EXTERN (LogAnimBank, Log, All)
uint32 GetTypeHash (const FAnimBankItem &Key)
uint32 GetTypeHash (const FSoftAnimBankItem &Key)
uint32 GetTypeHash (const TArray< FAnimBankItem > &InBankItems)
uint32 GetTypeHash (const TArray< FSoftAnimBankItem > &InBankItems)
FArchive & operator<< (FArchive &Ar, FAnimBankData &BankData)
FArchive & operator<< (FArchive &Ar, FAnimBankEntry &BankEntry)
FArchive & operator<< (FArchive &Ar, FSkinnedAssetMapping &AssetMapping)
USTRUCT () struct FAnimBankSequence
Typedef Documentation
FAnimBankRecordMap
using FAnimBankRecordMap = Experimental::TRobinHoodHashMap<FAnimBankDesc, FAnimBankRecord, FAnimBankDescKeyFuncs>
Definition at line 609 of file AnimBank.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogAnimBank , Log , All)
References All, and Log.
GetTypeHash() [1/4]
uint32 GetTypeHash (const FAnimBankItem & Key) inline
Definition at line 301 of file AnimBank.h.
References GetTypeHash(), HashCombine(), and Key.
GetTypeHash() [2/4]
uint32 GetTypeHash (const FSoftAnimBankItem & Key) inline
Definition at line 335 of file AnimBank.h.
References GetTypeHash(), HashCombine(), and Key.
GetTypeHash() [3/4]
uint32 GetTypeHash (const TArray< FAnimBankItem > & InBankItems) inline
Definition at line 306 of file AnimBank.h.
References GetTypeHash(), Hash, and HashCombine().
GetTypeHash() [4/4]
uint32 GetTypeHash (const TArray< FSoftAnimBankItem > & InBankItems) inline
Definition at line 340 of file AnimBank.h.
References GetTypeHash(), Hash, and HashCombine().
operator<<() [1/3]
FArchive & operator<< (FArchive & Ar, FAnimBankData & BankData) inline
Definition at line 126 of file AnimBank.h.
References Ar, FAnimBankData::Entries, and FAnimBankData::Mapping.
operator<<() [2/3]
FArchive & operator<< (FArchive & Ar, FAnimBankEntry & BankEntry) inline
Definition at line 106 of file AnimBank.h.
References Ar, FAnimBankEntry::Flags, FAnimBankEntry::FrameCount, FAnimBankEntry::KeyCount, FAnimBankEntry::PlayRate, FAnimBankEntry::Position, FAnimBankEntry::PositionKeys, FAnimBankEntry::RotationKeys, FAnimBankEntry::SampledBounds, and FAnimBankEntry::ScalingKeys.
operator<<() [3/3]
FArchive & operator<< (FArchive & Ar, FSkinnedAssetMapping & AssetMapping) inline
Definition at line 48 of file AnimBank.h.
References FSkinnedAssetMapping::AnimGlobalRefPose, Ar, FSkinnedAssetMapping::BoneCount, FSkinnedAssetMapping::MeshGlobalRefPose, FSkinnedAssetMapping::MeshToAnimIndexMap, FSkinnedAssetMapping::PositionKeys, FSkinnedAssetMapping::RetargetingTable, and FSkinnedAssetMapping::RotationKeys.
USTRUCT()
USTRUCT ()
Scales the bounds of the instances playing this sequence. This is useful when the animation moves the vertices of the mesh outside of its bounds. Warning: Increasing the bounds will reduce performance!
Definition at line 133 of file AnimBank.h.
References Animation, BlueprintType, Category, GENERATED_USTRUCT_BODY, meta, Position, and UPROPERTY.