Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Animation/AnimSequence.h File Reference
AnimSequence.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Misc/Guid.h"
#include "Animation/AnimTypes.h"
#include "Animation/AnimationAsset.h"
#include "Animation/AnimSequenceBase.h"
#include "Animation/AnimCompressionTypes.h"
#include "CustomAttributes.h"
#include "Containers/ArrayView.h"
#include "Animation/AnimData/AnimDataNotifications.h"
#include "Animation/AttributeCurve.h"
#include "Async/SharedRecursiveMutex.h"
#include "UObject/PerPlatformProperties.h"
#include "IO/IoHash.h"
#include "AnimData/IAnimationDataModel.h"
#include "AnimSequence.generated.h"
Data Structures
class UAnimSequence
struct UAnimSequence::FCompressedAnimationDataReadScope
Helper struct to enter/leave compressed data lock in read-mode.
struct UAnimSequence::FCompressedAnimationDataWriteScope
Helper struct to enter/leave compressed data lock in write-mode.
struct UAnimSequence::FScopedCompressedAnimSequence
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Anim
namespace UE::Anim::Compression
namespace UE::AnimNext
Synchronization Role.
Macros
#define UE_COMPRESSED_DATA_READ_SCOPE(sequence)
#define UE_COMPRESSED_DATA_WRITE_SCOPE(sequence)
Typedefs
typedef TArray< FTransform > FTransformArrayA2
One animation sequence of keyframes.
Functions
UENUM() enum class EStripAnimDataOnDedicatedServerSettings UCLASS ()
Enum used to decide whether we should strip animation data on dedicated server.
USTRUCT () struct FTranslationTrack
Keyframe position data for one track.
Variables
UENUM() enum class EStripAnimDataOnDedicatedServerSettings BlueprintType
int32 GPerformFrameStripping
Macro Definition Documentation
UE_COMPRESSED_DATA_READ_SCOPE
#define UE_COMPRESSED_DATA_READ_SCOPE (sequence)
Value:
    UAnimSequence::FCompressedAnimationDataReadScope Scope(sequence);
Definition at line 996 of file AnimSequence.h.
UE_COMPRESSED_DATA_WRITE_SCOPE
#define UE_COMPRESSED_DATA_WRITE_SCOPE (sequence)
Value:
    UAnimSequence::FCompressedAnimationDataWriteScope Scope(sequence);
Definition at line 987 of file AnimSequence.h.
Typedef Documentation
FTransformArrayA2
typedef TArray<FTransform> FTransformArrayA2
One animation sequence of keyframes.
Contains a number of tracks of data.
Definition at line 33 of file AnimSequence.h.
Function Documentation
UCLASS()
UENUM() enum class EStripAnimDataOnDedicatedServerSettings UCLASS ()
Enum used to decide whether we should strip animation data on dedicated server.
USTRUCT()
USTRUCT ()
Keyframe position data for one track.
Key frame curve data for one track CurveName: Morph Target Name CurveWeights: List of weights for each frame.
Keyframe scale data for one track.
Keyframe rotation data for one track.
Pos(i) occurs at Time(i). Pos.Num() always equals Time.Num().
Rot(i) occurs at Time(i). Rot.Num() always equals Time.Num().
Scale(i) occurs at Time(i). Rot.Num() always equals Time.Num().
Returns true if valid curve weight exists in the array
This is very simple cut to 1 key method if all is same since I see so many redundant same value in every frame Eventually this can get more complicated Will return true if compressed to 1. Return false otherwise
Definition at line 51 of file AnimSequence.h.
References TArray< InElementType, InAllocatorType >::AddZeroed(), check, TArray< InElementType, InAllocatorType >::Empty(), GENERATED_USTRUCT_BODY, GetNum(), Initialize, MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), and UPROPERTY.
Variable Documentation
BlueprintType
UENUM() enum class EStripAnimDataOnDedicatedServerSettings BlueprintType
Definition at line 201 of file AnimSequence.h.
GPerformFrameStripping
int32 GPerformFrameStripping extern