Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/Array.h File Reference
Array.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Misc/IntrusiveUnsetOptionalState.h"
#include "Misc/ReverseIterate.h"
#include "HAL/UnrealMemory.h"
#include "Templates/UnrealTypeTraits.h"
#include "Templates/UnrealTemplate.h"
#include "Containers/AllowShrinking.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/ContainerElementTypeCompatibility.h"
#include "Serialization/Archive.h"
#include "Serialization/MemoryImageWriter.h"
#include "Algo/Heapify.h"
#include "Algo/HeapSort.h"
#include "Algo/IsHeap.h"
#include "Algo/Impl/BinaryHeap.h"
#include "Algo/StableSort.h"
#include "Concepts/GetTypeHashable.h"
#include "Templates/IdentityFunctor.h"
#include "Templates/Invoke.h"
#include "Templates/Less.h"
#include "Templates/LosesQualifiersFromTo.h"
#include "Templates/Requires.h"
#include "Templates/Sorting.h"
#include "Templates/AlignmentTemplates.h"
#include "Traits/ElementType.h"
#include <limits>
#include <type_traits>
Data Structures
class TArray< InElementType, InAllocatorType >
Templated dynamic array.
struct TArrayPrivateFriend
struct TCanBulkSerialize< T >
struct TCheckedPointerIterator< ElementType, SizeType, bReverse >
Pointer-like iterator type for ranged-for loops which checks that the container hasn't been resized during iteration.
struct TDereferencingIterator< ElementType, IteratorType >
class TIndexedContainerIterator< ContainerType, ElementType, SizeType >
Generic iterator which can operate on types that expose the following:
struct TIsContiguousContainer< TArray< T, AllocatorType > >
struct TIsTArray< T >
struct TIsZeroConstructType< TArray< InElementType, AllocatorType > >
Namespaces
namespace Freeze
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define TARRAY_RANGED_FOR_CHECKS 1
Typedefs
template<typename AllocatorInstanceType>
using UE::Core::Private::TAllocatorSizeType_T = decltype(std::declval<AllocatorInstanceType&>().GetInitialCapacity())
Functions
template<typename FromArrayType, typename ToArrayType>
UE_NODEBUG constexpr bool UE::Core::Private::CanMoveTArrayPointersBetweenArrayTypes ()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename T, typename AllocatorType >),(TArray< T, AllocatorType >))
template<typename AllocatorType>
UE_NODEBUG constexpr uint32 UE::Core::Private::GetAllocatorFlags ()
template<typename T>
FORCEINLINE decltype(auto) UE::Core::Private::GetDataHelper (T &&Arg)
template<typename InElementType, typename InAllocatorType>
uint32 GetTypeHash (const TArray< InElementType, InAllocatorType > &A)
Returns a unique hash by combining those of each array element.
template<typename T, typename AllocatorType>
UE_NODEBUG uint32 Freeze::IntrinsicAppendHash (const TArray< T, AllocatorType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename T, typename AllocatorType>
UE_NODEBUG uint32 Freeze::IntrinsicGetTargetAlignment (const TArray< T, AllocatorType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename T, typename AllocatorType>
UE_NODEBUG void Freeze::IntrinsicToString (const TArray< T, AllocatorType > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
template<typename T, typename AllocatorType>
UE_NODEBUG uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TArray< T, AllocatorType > &Object, void *OutDst)
template<typename T, typename AllocatorType>
UE_NODEBUG void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TArray< T, AllocatorType > &Object, const FTypeLayoutDesc &)
void UE::Core::Private::OnInvalidArrayNum (unsigned long long NewNum)
template<typename T, typename AllocatorType>
void * operator new (size_t Size, TArray< T, AllocatorType > &Array)
template<typename T, typename AllocatorType>
UE_NODEBUG void * operator new (size_t Size, TArray< T, AllocatorType > &Array)
template<typename T, typename AllocatorType>
void * operator new (size_t Size, TArray< T, AllocatorType > &Array, typename TArray< T, AllocatorType >::SizeType Index)
template<typename T, typename AllocatorType>
UE_NODEBUG void * operator new (size_t Size, TArray< T, AllocatorType > &Array, typename TArray< T, AllocatorType >::SizeType Index)
template<typename ContainerType, typename ElementType, typename SizeType>
UE_NODEBUG FORCEINLINE TIndexedContainerIterator< ContainerType, ElementType, SizeType > operator+ (SizeType Offset, TIndexedContainerIterator< ContainerType, ElementType, SizeType > RHS)
operator +
template<typename ElementType, typename AllocatorType>
UE_NODEBUG FArchive & operator<< (FArchive &Ar, TArray< ElementType, AllocatorType > &A)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE void UE::Core::Private::ReallocForCopy (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > NewMax, TAllocatorSizeType_T< AllocatorInstanceType > PrevMax, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > Count, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow1_DoAlloc (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCEINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow1_DoAlloc_Impl (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow1_DoAlloc_Tiny (uint16 ElementSizeAndAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE void UE::Core::Private::ReallocShrink (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE void UE::Core::Private::ReallocTo (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > NewMax, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
static UE_NODEBUG char(& UE::Core::Private::ResolveIsTArrayPtr (...))[1]
template<typename ElementType, typename AllocatorType>
static UE_NODEBUG char(& UE::Core::Private::ResolveIsTArrayPtr (const volatile TArray< ElementType, AllocatorType > *))[2]
Variables
template<typename DestType, typename SourceType>
constexpr bool UE::Core::Private::TArrayElementsAreCompatible_V = std::disjunction_v<std::is_same<DestType, std::decay_t<SourceType>>, std::is_constructible<DestType, SourceType>>
template<typename T>
constexpr bool TIsTArray_V = false
Trait which determines whether or not a type is a TArray.
template<typename InElementType, typename InAllocatorType>
constexpr bool TIsTArray_V< const TArray< InElementType, InAllocatorType > > = true
template<typename InElementType, typename InAllocatorType>
constexpr bool TIsTArray_V< const volatile TArray< InElementType, InAllocatorType > > = true
template<typename InElementType, typename InAllocatorType>
constexpr bool TIsTArray_V< TArray< InElementType, InAllocatorType > > = true
template<typename InElementType, typename InAllocatorType>
constexpr bool TIsTArray_V< volatile TArray< InElementType, InAllocatorType > > = true
template<typename T>
constexpr bool UE::Core::Private::TIsTArrayOrDerivedFromTArray_V = sizeof(ResolveIsTArrayPtr((T*)nullptr)) == 2
Macro Definition Documentation
TARRAY_RANGED_FOR_CHECKS
#define TARRAY_RANGED_FOR_CHECKS 1
Definition at line 39 of file Array.h.
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename T, typename AllocatorType >) , (TArray< T, AllocatorType >))
GetTypeHash()
template<typename InElementType, typename InAllocatorType> uint32 GetTypeHash (const TArray< InElementType, InAllocatorType > & A) nodiscard
Returns a unique hash by combining those of each array element.
Definition at line 4155 of file Array.h.
References A, GetTypeHash(), Hash, and HashCombineFast().
Referenced by GetTypeHash().
operator new() [1/4]
template<typename T, typename AllocatorType> void * operator new (size_t Size, TArray< T, AllocatorType > & Array) inline
Definition at line 4028 of file Array.h.
References Array, check, TSequenceHistory< HistorySize >::Size, and UE_NODEBUG.
operator new() [2/4]
template<typename T, typename AllocatorType> UE_NODEBUG void * operator new (size_t Size, TArray< T, AllocatorType > & Array) inline
Definition at line 4028 of file Array.h.
References Array, check, TSequenceHistory< HistorySize >::Size, and UE_NODEBUG.
operator new() [3/4]
template<typename T, typename AllocatorType> void * operator new (size_t Size, TArray< T, AllocatorType > & Array, typename TArray< T, AllocatorType >::SizeType Index) inline
Definition at line 4035 of file Array.h.
References Array, check, TSequenceHistory< HistorySize >::Size, and UE_NODEBUG.
operator new() [4/4]
template<typename T, typename AllocatorType> UE_NODEBUG void * operator new (size_t Size, TArray< T, AllocatorType > & Array, typename TArray< T, AllocatorType >::SizeType Index) inline
Definition at line 4035 of file Array.h.
References Array, check, TSequenceHistory< HistorySize >::Size, and UE_NODEBUG.
operator+()
template<typename ContainerType, typename ElementType, typename SizeType> UE_NODEBUG FORCEINLINE TIndexedContainerIterator< ContainerType, ElementType, SizeType > operator+ (SizeType Offset, TIndexedContainerIterator< ContainerType, ElementType, SizeType > RHS) nodiscard
operator +
Definition at line 192 of file Array.h.
References FORCEINLINE, and UE_NODEBUG.
Referenced by USTRUCT().
operator<<()
template<typename ElementType, typename AllocatorType> UE_NODEBUG FArchive & operator<< (FArchive & Ar, TArray< ElementType, AllocatorType > & A)
Definition at line 4148 of file Array.h.
References A, Ar, TArrayPrivateFriend::Serialize(), and UE_NODEBUG.
Variable Documentation
TIsTArray_V
template<typename T> bool TIsTArray_V = false constexpr
Trait which determines whether or not a type is a TArray.
Definition at line 4010 of file Array.h.
Referenced by MetasoundParameterPackPrivate::FMetasoundParameterPackItem< T, MaxNumItems >::FMetasoundParameterPackItem(), FMetasoundParameterPackStorage::AddArrayParameter(), and FMetasoundParameterPackStorage::AddParameter().
TIsTArray_V< const TArray< InElementType, InAllocatorType > >
template<typename InElementType, typename InAllocatorType> bool TIsTArray_V< const TArray< InElementType, InAllocatorType > > = true constexpr
Definition at line 4013 of file Array.h.
TIsTArray_V< const volatile TArray< InElementType, InAllocatorType > >
template<typename InElementType, typename InAllocatorType> bool TIsTArray_V< const volatile TArray< InElementType, InAllocatorType > > = true constexpr
Definition at line 4015 of file Array.h.
TIsTArray_V< TArray< InElementType, InAllocatorType > >
template<typename InElementType, typename InAllocatorType> bool TIsTArray_V< TArray< InElementType, InAllocatorType > > = true constexpr
Definition at line 4012 of file Array.h.
TIsTArray_V< volatile TArray< InElementType, InAllocatorType > >
template<typename InElementType, typename InAllocatorType> bool TIsTArray_V< volatile TArray< InElementType, InAllocatorType > > = true constexpr
Definition at line 4014 of file Array.h.