Unreal Engine 5.6 C++ API: Runtime/Core/Public/Misc/Attribute.h File Reference
Attribute.h File Reference
#include "CoreTypes.h"
#include "Misc/TVariant.h"
#include "Templates/Function.h"
#include "Templates/Identity.h"
#include "Templates/SharedPointer.h"
#include "Delegates/Delegate.h"
Data Structures
class TAttribute< ObjectType >
Attribute object.
Functions
template<typename LambdaType, typename... PayloadTypes>
decltype(auto) MakeAttributeLambda (LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Helper function for creating TAttributes from a lambda TAttribute<float> FloatAttribute = MakeAttributeLambda([]{ return 10.f; });.
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes>
FORCEINLINE TAttribute< T > MakeAttributeRaw (const SourceType *InObject, T(SourceTypeOrBase::*InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload)
Helper function for creating TAttributes from a const member function pointer, accessed through a raw pointer.
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes>
FORCEINLINE TAttribute< T > MakeAttributeSP (const SourceType *InObject, T(SourceTypeOrBase::*InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload)
Helper function for creating TAttributes from a const member function pointer, accessed through a weak pointer to the shared object.
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes>
FORCEINLINE TAttribute< T > MakeAttributeSP (TSharedRef< SourceType > InObject, T(SourceTypeOrBase::*InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload)
template<typename UserClass, ESPMode Mode, typename LambdaType, typename... PayloadTypes>
decltype(auto) MakeAttributeSPLambda (const TSharedRef< UserClass, Mode > &InUserObjectRef, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Helper function for creating TAttributes from a weak shared pointer C++ lambda delegate.
template<typename UserClass, typename LambdaType, typename... PayloadTypes>
decltype(auto) MakeAttributeSPLambda (UserClass *InUserObject, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes>
FORCEINLINE TAttribute< T > MakeAttributeUObject (const SourceType *InObject, T(SourceTypeOrBase::*InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload)
template<typename UserClass, typename LambdaType, typename... PayloadTypes>
decltype(auto) MakeAttributeWeakLambda (UserClass *InUserObject, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Helper function for creating TAttributes from a weak object pointer C++ lambda delegate.
Function Documentation
MakeAttributeLambda()
template<typename LambdaType, typename... PayloadTypes> decltype(auto) MakeAttributeLambda (LambdaType && InCallable, PayloadTypes &&... InputPayload) nodiscard
Helper function for creating TAttributes from a lambda TAttribute<float> FloatAttribute = MakeAttributeLambda([]{ return 10.f; });.
Definition at line 545 of file Attribute.h.
References TAttribute< ObjectType >::Create(), DeclVal(), and Forward().
Referenced by SSegmentedControl< OptionType >::GetCheckBoxStateAttribute(), and SSegmentedControl< OptionType >::RebuildChildren().
MakeAttributeRaw()
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes> FORCEINLINE TAttribute< T > MakeAttributeRaw (const SourceType * InObject, T(SourceTypeOrBase::* InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload) nodiscard
Helper function for creating TAttributes from a const member function pointer, accessed through a raw pointer.
Definition at line 515 of file Attribute.h.
References TAttribute< ObjectType >::Create(), FORCEINLINE, and MoveTemp().
MakeAttributeSP() [1/2]
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes> FORCEINLINE TAttribute< T > MakeAttributeSP (const SourceType * InObject, T(SourceTypeOrBase::* InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload) nodiscard
Helper function for creating TAttributes from a const member function pointer, accessed through a weak pointer to the shared object.
Definition at line 524 of file Attribute.h.
References TAttribute< ObjectType >::Create(), FORCEINLINE, and MoveTemp().
MakeAttributeSP() [2/2]
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes> FORCEINLINE TAttribute< T > MakeAttributeSP (TSharedRef< SourceType > InObject, T(SourceTypeOrBase::* InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload) nodiscard
Definition at line 529 of file Attribute.h.
References TAttribute< ObjectType >::Create(), FORCEINLINE, and MoveTemp().
MakeAttributeSPLambda() [1/2]
template<typename UserClass, ESPMode Mode, typename LambdaType, typename... PayloadTypes> decltype(auto) MakeAttributeSPLambda (const TSharedRef< UserClass, Mode > & InUserObjectRef, LambdaType && InCallable, PayloadTypes &&... InputPayload) nodiscard
Helper function for creating TAttributes from a weak shared pointer C++ lambda delegate.
Definition at line 556 of file Attribute.h.
References TAttribute< ObjectType >::Create(), DeclVal(), and Forward().
MakeAttributeSPLambda() [2/2]
template<typename UserClass, typename LambdaType, typename... PayloadTypes> decltype(auto) MakeAttributeSPLambda (UserClass * InUserObject, LambdaType && InCallable, PayloadTypes &&... InputPayload) nodiscard
Definition at line 563 of file Attribute.h.
References TAttribute< ObjectType >::Create(), DeclVal(), and Forward().
MakeAttributeUObject()
template<typename T, typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes> FORCEINLINE TAttribute< T > MakeAttributeUObject (const SourceType * InObject, T(SourceTypeOrBase::* InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload) nodiscard
Definition at line 535 of file Attribute.h.
References TAttribute< ObjectType >::Create(), FORCEINLINE, and MoveTemp().
MakeAttributeWeakLambda()
template<typename UserClass, typename LambdaType, typename... PayloadTypes> decltype(auto) MakeAttributeWeakLambda (UserClass * InUserObject, LambdaType && InCallable, PayloadTypes &&... InputPayload) nodiscard
Helper function for creating TAttributes from a weak object pointer C++ lambda delegate.
Definition at line 574 of file Attribute.h.
References TAttribute< ObjectType >::Create(), DeclVal(), and Forward().