Unreal Engine 5.6 C++ API: Runtime/GeometryFramework/Public/Components/BaseDynamicMeshComponent.h File Reference
BaseDynamicMeshComponent.h File Reference
#include "CoreMinimal.h"
#include "Components/MeshComponent.h"
#include "InteractiveToolObjects.h"
#include "Changes/MeshVertexChange.h"
#include "Changes/MeshChange.h"
#include "Changes/MeshReplacementChange.h"
#include "MeshConversionOptions.h"
#include "DynamicMesh/DynamicMesh3.h"
#include "UDynamicMesh.h"
#include "BaseDynamicMeshComponent.generated.h"
Data Structures
class UBaseDynamicMeshComponent
Enumerations
enum class EMeshRenderAttributeFlags : uint8 {
None = 0 , Positions = 1 , VertexColors = 1<<1 , VertexNormals = 1<<2 ,
VertexUVs = 1<<3 , SecondaryIndexBuffers = 1<<4 , AllVertexAttribs = Positions | VertexColors | VertexNormals | VertexUVs
}
EMeshRenderAttributeFlags is used to identify different mesh rendering attributes, for things like fast-update functions.
Functions
ENUM_CLASS_FLAGS (EMeshRenderAttributeFlags)
UENUM() enum class EDynamicMeshVertexColorTransformMode UCLASS ()
Color Transform to apply to Vertex Colors when converting from internal DynamicMesh Color attributes (eg Color Overlay stored in FVector4f) to RHI Render Buffers (FColor).
UENUM() enum class EDynamicMeshComponentTangentsMode UENUM() enum class EDynamicMeshComponentColorOverrideMode UENUM() enum class EDynamicMeshDrawPath UENUM () enum class UE_DEPRECATED(5.0
Tangent calculation modes.
Variables
UENUM() enum class EDynamicMeshComponentTangentsMode UENUM() enum class EDynamicMeshComponentColorOverrideMode UENUM() enum class EDynamicMeshDrawPath Dynamic Mesh distance field support has been deprecated AsyncCPUDistanceField
Compute a distance field in a background thread.
UENUM() enum class EDynamicMeshVertexColorTransformMode ClassGroup = Rendering
UENUM() enum class EDynamicMeshComponentTangentsMode UENUM() enum class EDynamicMeshComponentColorOverrideMode UENUM() enum class EDynamicMeshDrawPath Dynamic Mesh distance field support has been deprecated EDynamicMeshComponentDistanceFieldMode
Enumeration Type Documentation
EMeshRenderAttributeFlags
enum class EMeshRenderAttributeFlags : uint8 strong
EMeshRenderAttributeFlags is used to identify different mesh rendering attributes, for things like fast-update functions.
Enumerator
None
Positions
VertexColors
VertexNormals
VertexUVs
SecondaryIndexBuffers
AllVertexAttribs
Definition at line 28 of file BaseDynamicMeshComponent.h.
Function Documentation
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EMeshRenderAttributeFlags)
References BlueprintType, and Default.
UCLASS()
UENUM() enum class EDynamicMeshVertexColorTransformMode UCLASS ()
Color Transform to apply to Vertex Colors when converting from internal DynamicMesh Color attributes (eg Color Overlay stored in FVector4f) to RHI Render Buffers (FColor).
Note that UStaticMesh assumes the Source Mesh colors are Linear and always converts to SRGB. UBaseDynamicMeshComponent is a base interface for a UMeshComponent based on a UDynamicMesh.
UENUM()
UENUM() enum class EDynamicMeshComponentTangentsMode UENUM() enum class EDynamicMeshComponentColorOverrideMode UENUM() enum class EDynamicMeshDrawPath UENUM ()
Tangent calculation modes.
Color Override Modes Draw Path to use Mesh Signed Distance Field (SDF) mode
References BlueprintType.
Variable Documentation
AsyncCPUDistanceField
UENUM() enum class EDynamicMeshComponentTangentsMode UENUM() enum class EDynamicMeshComponentColorOverrideMode UENUM() enum class EDynamicMeshDrawPath Dynamic Mesh distance field support has been deprecated AsyncCPUDistanceField
Initial value:
= 1 UMETA(DisplayName = "Async CPU Distance Field")
}
Compute a distance field in a background thread.
Definition at line 99 of file BaseDynamicMeshComponent.h.
ClassGroup
UENUM() enum class EDynamicMeshVertexColorTransformMode ClassGroup = Rendering
Definition at line 123 of file BaseDynamicMeshComponent.h.
EDynamicMeshComponentDistanceFieldMode
UENUM() enum class EDynamicMeshComponentTangentsMode UENUM() enum class EDynamicMeshComponentColorOverrideMode UENUM() enum class EDynamicMeshDrawPath Dynamic Mesh distance field support has been deprecated EDynamicMeshComponentDistanceFieldMode
Definition at line 94 of file BaseDynamicMeshComponent.h.
Referenced by UBaseDynamicMeshComponent::UE_DEPRECATED(), UBaseDynamicMeshComponent::UE_DEPRECATED(), and UBaseDynamicMeshComponent::UE_DEPRECATED().