Unreal Engine 5.6 C++ API: Runtime/AIModule/Classes/BehaviorTree/BehaviorTreeTypes.h File Reference
BehaviorTreeTypes.h File Reference
#include "Blackboard/BlackboardKey.h"
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "InputCoreTypes.h"
#include "Templates/SubclassOf.h"
#include "BehaviorTreeTypes.generated.h"
Data Structures
struct FBehaviorTreeDebuggerInstance
debugger data about subtree instance
struct FBehaviorTreeDebuggerInstance::FNodeFlowData
struct FBehaviorTreeExecutionStep
debugger data about current execution step
struct FBehaviorTreeInstance
data required for instance of single subtree
struct FBehaviorTreeInstanceId
identifier of subtree instance
struct FBehaviorTreeParallelTask
wrapper struct for holding a parallel task node and its status
struct FBehaviorTreePropertyMemory
property block in blueprint defined nodes
struct FBehaviorTreeSearchData
node search data
struct FBehaviorTreeSearchUpdate
node update data
struct FBehaviorTreeSearchUpdateNotify
instance notify data
struct FBTNodeIndex
struct FBTNodeIndexRange
struct FScopedBTLoggingContext
Helper struct to push a node as the new logging context and automatically reset the context on destruction.
struct TIsValidVariadicFunctionArg< FBlackboard::FKey >
Namespaces
namespace BTSpecialChild
namespace EBTActiveNode
namespace EBTDescriptionVerbosity
namespace EBTExecutionMode
namespace EBTExecutionSnap
namespace EBTMemoryClear
namespace EBTMemoryInit
namespace EBTNodeUpdateMode
namespace EBTStopMode
namespace EBTTaskStatus
Macros
#define BT_SEARCHLOG(SearchData, Verbosity, Format, ...)
#define BT_VLOG(Context, Verbosity, Format, ...)
#define USE_BEHAVIORTREE_DEBUGGER (1 && WITH_EDITORONLY_DATA)
Typedefs
using FOnBlackboardChangeNotification = TDelegate<EBlackboardNotificationResult(const UBlackboardComponent&, FBlackboard::FKey keyID), FNotThreadSafeNotCheckedDelegateUserPolicy>
Enumerations
enum class EBlackboardNotificationResult : uint8 { RemoveObserver , ContinueObserving }
enum class EBTNodeRelativePriority : uint8 { Lower , Same , Higher }
enum class EBTRestartMode : uint8 { ForceReevaluateRootNode , CompleteRestart }
enum EBTActiveNode::Type { EBTActiveNode::Composite , EBTActiveNode::ActiveTask , EBTActiveNode::AbortingTask , EBTActiveNode::InactiveTask }
enum EBTDescriptionVerbosity::Type { EBTDescriptionVerbosity::Basic , EBTDescriptionVerbosity::Detailed }
enum EBTExecutionMode::Type { EBTExecutionMode::SingleRun , EBTExecutionMode::Looped }
enum EBTExecutionSnap::Type { EBTExecutionSnap::Regular , EBTExecutionSnap::OutOfNodes }
enum EBTMemoryClear::Type { EBTMemoryClear::Destroy , EBTMemoryClear::StoreSubtree }
enum EBTMemoryInit::Type { EBTMemoryInit::Initialize , EBTMemoryInit::RestoreSubtree }
enum EBTNodeUpdateMode::Type { EBTNodeUpdateMode::Unknown , EBTNodeUpdateMode::Add , EBTNodeUpdateMode::Remove }
enum EBTStopMode::Type { EBTStopMode::Safe , EBTStopMode::Forced }
enum EBTTaskStatus::Type { EBTTaskStatus::Active , EBTTaskStatus::Aborting , EBTTaskStatus::Inactive }
Functions
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Auxiliary Update Time"), STAT_AI_BehaviorTree_AuxUpdateTime, STATGROUP_AIBehaviorTree,)
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Cleanup Time"), STAT_AI_BehaviorTree_Cleanup, STATGROUP_AIBehaviorTree,)
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Execution Time"), STAT_AI_BehaviorTree_ExecutionTime, STATGROUP_AIBehaviorTree,)
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Load Time"), STAT_AI_BehaviorTree_LoadTime, STATGROUP_AIBehaviorTree,)
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Search Time"), STAT_AI_BehaviorTree_SearchTime, STATGROUP_AIBehaviorTree,)
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Stop Tree Time"), STAT_AI_BehaviorTree_StopTree, STATGROUP_AIBehaviorTree,)
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Tick"), STAT_AI_BehaviorTree_Tick, STATGROUP_AIBehaviorTree,)
DECLARE_DELEGATE_TwoParams (FBTInstanceDeactivation, UBehaviorTreeComponent &, EBTNodeResult::Type)
DECLARE_DELEGATE_TwoParams (FOnBlackboardChange, const UBlackboardComponent &, FBlackboard::FKey)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Instances"), STAT_AI_BehaviorTree_NumInstances, STATGROUP_AIBehaviorTree,)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Templates"), STAT_AI_BehaviorTree_NumTemplates, STATGROUP_AIBehaviorTree,)
DECLARE_MEMORY_STAT_EXTERN (TEXT("Instance memory"), STAT_AI_BehaviorTree_InstanceMemory, STATGROUP_AIBehaviorTree, AIMODULE_API)
DECLARE_STATS_GROUP (TEXT("Behavior Tree"), STATGROUP_AIBehaviorTree, STATCAT_Advanced)
UENUM () namespace EBTNodeResult
USTRUCT () struct FBlackboardKeySelector
helper struct for defining types of allowed blackboard entries (e.g.
Variables
constexpr int32 BTSpecialChild::NotInitialized = -1
constexpr uint8 BTSpecialChild::OwnedByComposite = MAX_uint8
constexpr int32 BTSpecialChild::ReturnToParent = -2
Macro Definition Documentation
BT_SEARCHLOG
#define BT_SEARCHLOG (SearchData, Verbosity, Format, ...)
Value:
UE_VLOG(SearchData.OwnerComp.GetOwner(), LogBehaviorTree, Verbosity, Format, ##__VA_ARGS__)
Definition at line 29 of file BehaviorTreeTypes.h.
BT_VLOG
#define BT_VLOG (Context, Verbosity, Format, ...)
Value:
UE_VLOG(Context->OwnerComp.IsValid() ? Context->OwnerComp->GetOwner() : NULL, LogBehaviorTree, Verbosity, Format, ##__VA_ARGS__)
Definition at line 28 of file BehaviorTreeTypes.h.
USE_BEHAVIORTREE_DEBUGGER
#define USE_BEHAVIORTREE_DEBUGGER (1 && WITH_EDITORONLY_DATA)
Definition at line 32 of file BehaviorTreeTypes.h.
Typedef Documentation
FOnBlackboardChangeNotification
using FOnBlackboardChangeNotification = TDelegate<EBlackboardNotificationResult(const UBlackboardComponent&, FBlackboard::FKey keyID), FNotThreadSafeNotCheckedDelegateUserPolicy>
Definition at line 72 of file BehaviorTreeTypes.h.
Enumeration Type Documentation
EBlackboardNotificationResult
enum class EBlackboardNotificationResult : uint8 strong
Enumerator
RemoveObserver
ContinueObserving
Definition at line 61 of file BehaviorTreeTypes.h.
EBTNodeRelativePriority
enum class EBTNodeRelativePriority : uint8 strong
Enumerator
Lower
Same
Higher
Definition at line 223 of file BehaviorTreeTypes.h.
EBTRestartMode
enum class EBTRestartMode : uint8 strong
Enumerator
ForceReevaluateRootNode
CompleteRestart
Definition at line 117 of file BehaviorTreeTypes.h.
Function Documentation
DECLARE_CYCLE_STAT_EXTERN() [1/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Auxiliary Update Time") , STAT_AI_BehaviorTree_AuxUpdateTime , STATGROUP_AIBehaviorTree)
DECLARE_CYCLE_STAT_EXTERN() [2/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Cleanup Time") , STAT_AI_BehaviorTree_Cleanup , STATGROUP_AIBehaviorTree)
DECLARE_CYCLE_STAT_EXTERN() [3/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Execution Time") , STAT_AI_BehaviorTree_ExecutionTime , STATGROUP_AIBehaviorTree)
DECLARE_CYCLE_STAT_EXTERN() [4/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Load Time") , STAT_AI_BehaviorTree_LoadTime , STATGROUP_AIBehaviorTree)
DECLARE_CYCLE_STAT_EXTERN() [5/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Search Time") , STAT_AI_BehaviorTree_SearchTime , STATGROUP_AIBehaviorTree)
DECLARE_CYCLE_STAT_EXTERN() [6/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Stop Tree Time") , STAT_AI_BehaviorTree_StopTree , STATGROUP_AIBehaviorTree)
DECLARE_CYCLE_STAT_EXTERN() [7/7]
DECLARE_CYCLE_STAT_EXTERN (TEXT("BT Tick") , STAT_AI_BehaviorTree_Tick , STATGROUP_AIBehaviorTree)
DECLARE_DELEGATE_TwoParams() [1/2]
DECLARE_DELEGATE_TwoParams (FBTInstanceDeactivation , UBehaviorTreeComponent & , EBTNodeResult::Type)
DECLARE_DELEGATE_TwoParams() [2/2]
DECLARE_DELEGATE_TwoParams (FOnBlackboardChange , const UBlackboardComponent & , FBlackboard::FKey)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [1/2]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Instances") , STAT_AI_BehaviorTree_NumInstances , STATGROUP_AIBehaviorTree)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [2/2]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Templates") , STAT_AI_BehaviorTree_NumTemplates , STATGROUP_AIBehaviorTree)
DECLARE_MEMORY_STAT_EXTERN()
DECLARE_MEMORY_STAT_EXTERN (TEXT("Instance memory") , STAT_AI_BehaviorTree_InstanceMemory , STATGROUP_AIBehaviorTree , AIMODULE_API)
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("Behavior Tree") , STATGROUP_AIBehaviorTree , STATCAT_Advanced)
UENUM()
UENUM ()
Definition at line 82 of file BehaviorTreeTypes.h.
References BlueprintType, Failed, InProgress, and Succeeded.
USTRUCT()
USTRUCT ()
helper struct for defining types of allowed blackboard entries (e.g.
only entries holding points and objects derived form actor class)
array of allowed types with additional properties (e.g. uobject's base class) EditAnywhere is required for FBlackboardSelectorDetails::CacheBlackboardData()
name of selected key
class of selected key
ID of selected key
find initial selection. Called when None is not a valid option for this key selector
find ID and class of selected key
helper functions for setting basic filters
Definition at line 622 of file BehaviorTreeTypes.h.
References BlueprintType, Category, FORCEINLINE, GENERATED_USTRUCT_BODY, TBaseStructureBase< T, bHasStaticStruct >::Get(), IntCastChecked(), FBlackboard::InvalidKey, FName::IsNone(), Meta, meta, Outer, Owner, PreSave, PropertyName, transient, and UPROPERTY.