Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/BitArray.h File Reference
BitArray.h File Reference
#include "Containers/ContainerAllocationPolicies.h"
#include "CoreTypes.h"
#include "HAL/PlatformAtomics.h"
#include "HAL/UnrealMemory.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/AssertionMacros.h"
#include "Misc/EnumClassFlags.h"
#include "Serialization/Archive.h"
#include "Serialization/MemoryImageWriter.h"
#include "Serialization/MemoryLayout.h"
#include "Templates/EnableIf.h"
#include "Templates/Invoke.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
Data Structures
class FBitArrayMemory
struct FBitSet
class FConstBitReference
Used to read/write a bit in the array as a bool.
class FRelativeBitReference
Used to reference a bit in an unspecified bit array.
class FScriptBitArray
class TBitArray< Allocator >
A dynamically sized bit array.
class TBitArray< Allocator >::FConstIterator
Const BitArray iterator.
class TBitArray< Allocator >::FConstReverseIterator
Const reverse iterator.
struct TBitArray< Allocator >::FConstWordIterator
class TBitArray< Allocator >::FIterator
BitArray iterator.
class TBitArray< Allocator >::FReverseIterator
Reverse iterator.
struct TBitArray< Allocator >::FWordIterator
struct TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy >
struct TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< true, Dummy >
struct TBitArray< Allocator >::TWordIteratorBase< WordType >
class TConstDualSetBitIterator< Allocator, OtherAllocator, Both >
An iterator which only iterates over the bits which are set in both of two bit-arrays, if the Both template argument is true, or either if the argument is false.
class TConstSetBitIterator< Allocator >
An iterator which only iterates over set bits.
struct TIsZeroConstructType< TScriptBitArray< AllocatorType, InDerivedType > >
class TScriptBitArray< Allocator, InDerivedType >
Namespaces
namespace Freeze
Typedefs
template<typename Allocator, typename OtherAllocator>
using TConstDualBothSetBitIterator = TConstDualSetBitIterator<Allocator, OtherAllocator, true>
template<typename Allocator, typename OtherAllocator>
using TConstDualEitherSetBitIterator = TConstDualSetBitIterator<Allocator, OtherAllocator, false>
Enumerations
enum class EBitwiseOperatorFlags { MaxSize = 1 << 0 , MinSize = 1 << 1 , MaintainSize = 1 << 2 , OneFillMissingBits = 1 << 4 }
Flag enumeration for control bitwise operator functionality.
Functions
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template< typename Allocator >, TBitArray< Allocator >)
template<typename Allocator>
FORCEINLINE uint32 GetTypeHash (const TBitArray< Allocator > &BitArray)
template<typename Allocator>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TBitArray< Allocator > &Object, const FTypeLayoutDesc &)
template<typename Allocator>
FArchive & operator<< (FArchive &Ar, TBitArray< Allocator > &BitArray)
Typedef Documentation
TConstDualBothSetBitIterator
template<typename Allocator, typename OtherAllocator> using TConstDualBothSetBitIterator = TConstDualSetBitIterator<Allocator, OtherAllocator, true>
Definition at line 2177 of file BitArray.h.
TConstDualEitherSetBitIterator
template<typename Allocator, typename OtherAllocator> using TConstDualEitherSetBitIterator = TConstDualSetBitIterator<Allocator, OtherAllocator, false>
Definition at line 2182 of file BitArray.h.
Enumeration Type Documentation
EBitwiseOperatorFlags
enum class EBitwiseOperatorFlags strong
Flag enumeration for control bitwise operator functionality.
Enumerator
MaxSize
Specifies that the result should be sized Max(A.Num(), B.Num())
MinSize
Specifies that the result should be sized Min(A.Num(), B.Num())
MaintainSize
Only valid for self-mutating bitwise operators - indicates that the size of the LHS operand should not be changed.
OneFillMissingBits
When MaxSize or MaintainSize is specified and the operands are sized differently, any missing bits in the resulting bit array will be considered as 1, rather than 0.
Definition at line 57 of file BitArray.h.
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template< typename Allocator > , TBitArray< Allocator >)
GetTypeHash()
template<typename Allocator> FORCEINLINE uint32 GetTypeHash (const TBitArray< Allocator > & BitArray) nodiscard
Definition at line 1900 of file BitArray.h.
References FBitSet::CalculateNumWords(), FORCEINLINE, TBitArray< Allocator >::GetData(), Hash, and TBitArray< Allocator >::Num().
operator<<()
template<typename Allocator> FArchive & operator<< (FArchive & Ar, TBitArray< Allocator > & BitArray)
Definition at line 2354 of file BitArray.h.
References Ar, and TBitArray< Allocator >::Serialize().