Unreal Engine 5.6 C++ API: Editor/Kismet/Classes/BlueprintPaletteFavorites.h File Reference
BlueprintPaletteFavorites.h File Reference
#include "BlueprintNodeSignature.h"
#include "Containers/Array.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "Delegates/Delegate.h"
#include "EdGraph/EdGraphSchema.h"
#include "Templates/SharedPointer.h"
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectGlobals.h"
#include "BlueprintPaletteFavorites.generated.h"
Functions
USTRUCT () struct KISMET_API FFavoritedBlueprintPaletteItem
Function Documentation
USTRUCT()
USTRUCT ()
Sometime favorites can be coming from user edited .ini files, so this converts that readable text into a favorite (since the strings are user generated, there could be some error, so sure to check its validity).
Parameters
SerializedAction A string representing a serialized favorite.
Constructs a favorite from the specified palette action (some palette actions cannot be favorited, so make sure to check its validity).
Parameters
PaletteAction The action you wish to favorite.
BlueprintAction
Returns
Sometimes we're not able to construct favorites from specified actions, so this provides us a way to check this item's validity.
Returns
True if this favorite is valid (refers to a specific node), false if not.
Checks to see if this favorite matches the specified one.
Parameters
Rhs The other favorite you want to compare with.
Returns
True if this favorite matches the other one, false if not.
Checks to see if this favorite represents the supplied ed-graph action (so we can match them together, and construct a favorites list).
Parameters
PaletteAction The action you want to compare with.
Returns
True if this favorite represents the specified action, false if not.
We want to be able to specify some of these in .ini files, so let we have to have a readable string representation for them.
Returns
A string representation of this item.
Definition at line 26 of file BlueprintPaletteFavorites.h.
References GENERATED_USTRUCT_BODY, IsValid(), operator==(), ToString(), and UE_DEPRECATED.