Unreal Engine 5.6 C++ API: Editor/MovieSceneTools/Public/Channels/BuiltInChannelEditors.h File Reference
BuiltInChannelEditors.h File Reference
#include "CoreTypes.h"
#include "Templates/SharedPointer.h"
#include "Containers/Array.h"
#include "Containers/ContainersFwd.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Class.h"
#include "MovieSceneKeyStruct.h"
#include "SequencerChannelTraits.h"
#include "Channels/MovieSceneChannelHandle.h"
#include "Channels/MovieSceneBoolChannel.h"
#include "Channels/MovieSceneByteChannel.h"
#include "Channels/MovieSceneDoubleChannel.h"
#include "Channels/MovieSceneFloatChannel.h"
#include "Channels/MovieSceneIntegerChannel.h"
#include "Channels/MovieSceneEventChannel.h"
#include "Channels/MovieSceneObjectPathChannel.h"
#include "Channels/MovieSceneTimeWarpChannel.h"
#include "Sections/MovieSceneStringSection.h"
#include "Sections/MovieSceneParticleSection.h"
#include "Sections/MovieSceneActorReferenceSection.h"
Functions
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneActorReferenceData *Channel, UMovieSceneSection *SectionToKey, FFrameNumber InTime, ISequencer &Sequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *PropertyBindings)
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneDoubleChannel *Channel, UMovieSceneSection *SectionToKey, const TMovieSceneExternalValue< double > &EditorData, FFrameNumber InTime, ISequencer &Sequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *PropertyBindings)
Overrides for adding or updating a key for non-standard channels.
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneFloatChannel *Channel, UMovieSceneSection *SectionToKey, const TMovieSceneExternalValue< float > &EditorData, FFrameNumber InTime, ISequencer &Sequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *PropertyBindings)
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneTimeWarpChannel *Channel, UMovieSceneSection *SectionToKey, FFrameNumber InTime, ISequencer &Sequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *PropertyBindings)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneActorReferenceData *Channel)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneBoolChannel *Channel)
Key editor overrides.
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneByteChannel *Channel)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneDoubleChannel *Channel)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneFloatChannel *Channel)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneIntegerChannel *Channel)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneObjectPathChannel *Channel)
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneStringChannel *Channel)
MOVIESCENETOOLS_API TSharedPtr< UE::Sequencer::FChannelModel > CreateChannelModel (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > &InChannelHandle, const UE::Sequencer::FSectionModel &InSection, FName InChannelName)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneBoolChannel > &BoolChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneByteChannel > &ByteChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > &DoubleChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneEventChannel > &EventChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneFloatChannel > &FloatChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneIntegerChannel > &IntegerChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > &TimeWarpChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneActorReferenceData > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneBoolChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneByteChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneFloatChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneIntegerChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneObjectPathChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneStringChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params)
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneDoubleChannel *Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
Key drawing overrides.
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneEventChannel *Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneFloatChannel *Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneParticleChannel *Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
MOVIESCENETOOLS_API void ExtendKeyMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< FMovieSceneDoubleChannel > > &&Channels, TWeakPtr< ISequencer > InSequencer)
MOVIESCENETOOLS_API void ExtendKeyMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< FMovieSceneFloatChannel > > &&Channels, TWeakPtr< ISequencer > InSequencer)
MOVIESCENETOOLS_API void ExtendKeyMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< FMovieSceneTimeWarpChannel > > &&Channels, TWeakPtr< ISequencer > InSequencer)
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneBoolChannel > > &&Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneByteChannel > > &&Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneDoubleChannel > > &&Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Context menu overrides.
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneFloatChannel > > &&Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneIntegerChannel > > &&Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneBoolChannel > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneByteChannel > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneDoubleChannel > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneFloatChannel > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder &OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneIntegerChannel > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
MOVIESCENETOOLS_API UMovieSceneKeyStructType * InstanceGeneratedStruct (FMovieSceneByteChannel *Channel, FSequencerKeyStructGenerator *Generator)
MOVIESCENETOOLS_API UMovieSceneKeyStructType * InstanceGeneratedStruct (FMovieSceneObjectPathChannel *Channel, FSequencerKeyStructGenerator *Generator)
MOVIESCENETOOLS_API UMovieSceneKeyStructType * InstanceGeneratedStruct (FMovieSceneTimeWarpChannel *Channel, FSequencerKeyStructGenerator *Generator)
MOVIESCENETOOLS_API void PostConstructKeyInstance (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > &ChannelHandle, FKeyHandle InHandle, FStructOnScope *Struct)
MOVIESCENETOOLS_API void PostConstructKeyInstance (const TMovieSceneChannelHandle< FMovieSceneObjectPathChannel > &ChannelHandle, FKeyHandle InHandle, FStructOnScope *Struct)
MOVIESCENETOOLS_API void PostConstructKeyInstance (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > &ChannelHandle, FKeyHandle InHandle, FStructOnScope *Struct)
MOVIESCENETOOLS_API bool ShouldShowCurve (const FMovieSceneDoubleChannel *Channel, UMovieSceneSection *InSection)
MOVIESCENETOOLS_API bool ShouldShowCurve (const FMovieSceneFloatChannel *Channel, UMovieSceneSection *InSection)
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneBoolChannel > &BoolChannel)
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneByteChannel > &ByteChannel)
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > &DoubleChannel)
Curve editor models.
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneEventChannel > &EventChannel)
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneFloatChannel > &FloatChannel)
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneIntegerChannel > &IntegerChannel)
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > &TimeWarpChannel)
Function Documentation
AddOrUpdateKey() [1/4]
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneActorReferenceData * Channel, UMovieSceneSection * SectionToKey, FFrameNumber InTime, ISequencer & Sequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * PropertyBindings)
References InTime.
AddOrUpdateKey() [2/4]
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneDoubleChannel * Channel, UMovieSceneSection * SectionToKey, const TMovieSceneExternalValue< double > & EditorData, FFrameNumber InTime, ISequencer & Sequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * PropertyBindings)
Overrides for adding or updating a key for non-standard channels.
References InTime.
Referenced by TSequencerChannelInterfaceBase< ChannelType, false >::AddOrUpdateKey_Raw(), and TSequencerChannelInterfaceBase< ChannelType, true >::AddOrUpdateKey_Raw().
AddOrUpdateKey() [3/4]
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneFloatChannel * Channel, UMovieSceneSection * SectionToKey, const TMovieSceneExternalValue< float > & EditorData, FFrameNumber InTime, ISequencer & Sequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * PropertyBindings)
References InTime.
AddOrUpdateKey() [4/4]
MOVIESCENETOOLS_API FKeyHandle AddOrUpdateKey (FMovieSceneTimeWarpChannel * Channel, UMovieSceneSection * SectionToKey, FFrameNumber InTime, ISequencer & Sequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * PropertyBindings)
References InTime.
CanCreateKeyEditor() [1/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneActorReferenceData * Channel)
CanCreateKeyEditor() [2/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneBoolChannel * Channel)
Key editor overrides.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CanCreateKeyEditor_Raw().
CanCreateKeyEditor() [3/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneByteChannel * Channel)
CanCreateKeyEditor() [4/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneDoubleChannel * Channel)
CanCreateKeyEditor() [5/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneFloatChannel * Channel)
CanCreateKeyEditor() [6/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneIntegerChannel * Channel)
CanCreateKeyEditor() [7/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneObjectPathChannel * Channel)
CanCreateKeyEditor() [8/8]
MOVIESCENETOOLS_API bool CanCreateKeyEditor (const FMovieSceneStringChannel * Channel)
CreateChannelModel()
MOVIESCENETOOLS_API TSharedPtr< UE::Sequencer::FChannelModel > CreateChannelModel (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > & InChannelHandle, const UE::Sequencer::FSectionModel & InSection, FName InChannelName)
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CreateChannelModel_Raw().
CreateCurveEditorModel() [1/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneBoolChannel > & BoolChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
CreateCurveEditorModel() [2/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneByteChannel > & ByteChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
CreateCurveEditorModel() [3/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > & DoubleChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CreateCurveEditorModel_Raw().
CreateCurveEditorModel() [4/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneEventChannel > & EventChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
CreateCurveEditorModel() [5/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneFloatChannel > & FloatChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
CreateCurveEditorModel() [6/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneIntegerChannel > & IntegerChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
CreateCurveEditorModel() [7/7]
MOVIESCENETOOLS_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > & TimeWarpChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
References Params.
CreateKeyEditor() [1/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneActorReferenceData > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [2/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneBoolChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CreateKeyEditor_Raw().
CreateKeyEditor() [3/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneByteChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [4/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [5/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneFloatChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [6/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneIntegerChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [7/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneObjectPathChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [8/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneStringChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
CreateKeyEditor() [9/9]
MOVIESCENETOOLS_API TSharedRef< SWidget > CreateKeyEditor (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params)
References Params.
DrawKeys() [1/4]
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneDoubleChannel * Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
Key drawing overrides.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::DrawKeys_Raw().
DrawKeys() [2/4]
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneEventChannel * Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
DrawKeys() [3/4]
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneFloatChannel * Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
DrawKeys() [4/4]
MOVIESCENETOOLS_API void DrawKeys (FMovieSceneParticleChannel * Channel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
ExtendKeyMenu() [1/3]
MOVIESCENETOOLS_API void ExtendKeyMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< FMovieSceneDoubleChannel > > && Channels, TWeakPtr< ISequencer > InSequencer)
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::ExtendKeyMenu_Raw().
ExtendKeyMenu() [2/3]
MOVIESCENETOOLS_API void ExtendKeyMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< FMovieSceneFloatChannel > > && Channels, TWeakPtr< ISequencer > InSequencer)
ExtendKeyMenu() [3/3]
MOVIESCENETOOLS_API void ExtendKeyMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< FMovieSceneTimeWarpChannel > > && Channels, TWeakPtr< ISequencer > InSequencer)
ExtendSectionMenu() [1/5]
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneBoolChannel > > && Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSectionMenu() [2/5]
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneByteChannel > > && Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSectionMenu() [3/5]
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneDoubleChannel > > && Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Context menu overrides.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::ExtendSectionMenu_Raw().
ExtendSectionMenu() [4/5]
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneFloatChannel > > && Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSectionMenu() [5/5]
MOVIESCENETOOLS_API void ExtendSectionMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneIntegerChannel > > && Channels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSidebarMenu() [1/5]
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneBoolChannel > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSidebarMenu() [2/5]
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneByteChannel > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSidebarMenu() [3/5]
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneDoubleChannel > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::ExtendSidebarMenu_Raw().
ExtendSidebarMenu() [4/5]
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneFloatChannel > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
ExtendSidebarMenu() [5/5]
MOVIESCENETOOLS_API TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder & OuterMenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TMovieSceneChannelHandle< FMovieSceneIntegerChannel > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
InstanceGeneratedStruct() [1/3]
MOVIESCENETOOLS_API UMovieSceneKeyStructType * InstanceGeneratedStruct (FMovieSceneByteChannel * Channel, FSequencerKeyStructGenerator * Generator)
InstanceGeneratedStruct() [2/3]
MOVIESCENETOOLS_API UMovieSceneKeyStructType * InstanceGeneratedStruct (FMovieSceneObjectPathChannel * Channel, FSequencerKeyStructGenerator * Generator)
InstanceGeneratedStruct() [3/3]
MOVIESCENETOOLS_API UMovieSceneKeyStructType * InstanceGeneratedStruct (FMovieSceneTimeWarpChannel * Channel, FSequencerKeyStructGenerator * Generator)
PostConstructKeyInstance() [1/3]
MOVIESCENETOOLS_API void PostConstructKeyInstance (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > & ChannelHandle, FKeyHandle InHandle, FStructOnScope * Struct)
References Struct.
PostConstructKeyInstance() [2/3]
MOVIESCENETOOLS_API void PostConstructKeyInstance (const TMovieSceneChannelHandle< FMovieSceneObjectPathChannel > & ChannelHandle, FKeyHandle InHandle, FStructOnScope * Struct)
References Struct.
PostConstructKeyInstance() [3/3]
MOVIESCENETOOLS_API void PostConstructKeyInstance (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > & ChannelHandle, FKeyHandle InHandle, FStructOnScope * Struct)
References Struct.
ShouldShowCurve() [1/2]
MOVIESCENETOOLS_API bool ShouldShowCurve (const FMovieSceneDoubleChannel * Channel, UMovieSceneSection * InSection)
ShouldShowCurve() [2/2]
MOVIESCENETOOLS_API bool ShouldShowCurve (const FMovieSceneFloatChannel * Channel, UMovieSceneSection * InSection)
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::ShouldShowCurve_Raw().
SupportsCurveEditorModels() [1/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneBoolChannel > & BoolChannel) inline
Definition at line 99 of file BuiltInChannelEditors.h.
SupportsCurveEditorModels() [2/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneByteChannel > & ByteChannel) inline
Definition at line 100 of file BuiltInChannelEditors.h.
SupportsCurveEditorModels() [3/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneDoubleChannel > & DoubleChannel) inline
Curve editor models.
Definition at line 96 of file BuiltInChannelEditors.h.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::SupportsCurveEditorModels_Raw().
SupportsCurveEditorModels() [4/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneEventChannel > & EventChannel) inline
Definition at line 101 of file BuiltInChannelEditors.h.
SupportsCurveEditorModels() [5/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneFloatChannel > & FloatChannel) inline
Definition at line 97 of file BuiltInChannelEditors.h.
SupportsCurveEditorModels() [6/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneIntegerChannel > & IntegerChannel) inline
Definition at line 98 of file BuiltInChannelEditors.h.
SupportsCurveEditorModels() [7/7]
MOVIESCENETOOLS_API bool SupportsCurveEditorModels (const TMovieSceneChannelHandle< FMovieSceneTimeWarpChannel > & TimeWarpChannel) inline
Definition at line 102 of file BuiltInChannelEditors.h.