Unreal Engine 5.6 C++ API: Runtime/Core/Public/Misc/ByteSwap.h File Reference
ByteSwap.h File Reference
#include "CoreTypes.h"
#include "HAL/PlatformCrt.h"
Namespaces
namespace Internal
Macros
#define BYTESWAP_ORDER16_unsigned(x)
#define BYTESWAP_ORDER32_unsigned(x)
#define INTEL_ORDER16(x)
#define INTEL_ORDER32(x)
#define INTEL_ORDER64(x)
#define INTEL_ORDER_TCHARARRAY(x)
#define INTEL_ORDERF(x)
#define NETWORK_ORDER16(x)
#define NETWORK_ORDER32(x)
#define NETWORK_ORDER64(x)
#define NETWORK_ORDER_TCHARARRAY(x)
#define NETWORK_ORDERF(x)
Functions
template<>
char16_t ByteSwap (char16_t Value)
template<>
double ByteSwap (double Value)
template<>
float ByteSwap (float Value)
template<>
int16 ByteSwap (int16 Value)
template<>
int32 ByteSwap (int32 Value)
template<>
int64 ByteSwap (int64 Value)
template<typename T>
T ByteSwap (T Value)
template<>
uint16 ByteSwap (uint16 Value)
template<>
uint32 ByteSwap (uint32 Value)
template<>
uint64 ByteSwap (uint64 Value)
FORCEINLINE int16 BYTESWAP_ORDER16 (int16 Val)
FORCEINLINE uint16 BYTESWAP_ORDER16 (uint16 Val)
FORCEINLINE int32 BYTESWAP_ORDER32 (int32 val)
FORCEINLINE uint32 BYTESWAP_ORDER32 (uint32 Val)
FORCEINLINE int64 BYTESWAP_ORDER64 (int64 Value)
FORCEINLINE uint64 BYTESWAP_ORDER64 (uint64 Value)
FORCEINLINE void BYTESWAP_ORDER_TCHARARRAY (TCHAR *str)
FORCEINLINE double BYTESWAP_ORDERD (double val)
FORCEINLINE float BYTESWAP_ORDERF (float val)
static FORCEINLINE uint16 Internal::ByteSwapGeneric16 (uint16 Value)
static FORCEINLINE uint32 Internal::ByteSwapGeneric32 (uint32 Value)
static FORCEINLINE uint64 Internal::ByteSwapGeneric64 (uint64 Value)
Macro Definition Documentation
BYTESWAP_ORDER16_unsigned
#define BYTESWAP_ORDER16_unsigned (x)
Value:
((((x) >> 8) & 0xff) + (((x) << 8) & 0xff00))
Definition at line 9 of file ByteSwap.h.
Referenced by Internal::ByteSwapGeneric16().
BYTESWAP_ORDER32_unsigned
#define BYTESWAP_ORDER32_unsigned (x)
Value:
(((x) >> 24) + (((x) >> 8) & 0xff00) + (((x) << 8) & 0xff0000) + ((x) << 24))
Definition at line 10 of file ByteSwap.h.
Referenced by Internal::ByteSwapGeneric32().
INTEL_ORDER16
#define INTEL_ORDER16 (x)
Value:
BYTESWAP_ORDER16(x)
Definition at line 139 of file ByteSwap.h.
INTEL_ORDER32
#define INTEL_ORDER32 (x)
Value:
BYTESWAP_ORDER32(x)
Definition at line 140 of file ByteSwap.h.
INTEL_ORDER64
#define INTEL_ORDER64 (x)
Value:
BYTESWAP_ORDER64(x)
Definition at line 142 of file ByteSwap.h.
INTEL_ORDER_TCHARARRAY
#define INTEL_ORDER_TCHARARRAY (x)
Value:
BYTESWAP_ORDER_TCHARARRAY(x)
Definition at line 143 of file ByteSwap.h.
INTEL_ORDERF
#define INTEL_ORDERF (x)
Value:
BYTESWAP_ORDERF(x)
Definition at line 141 of file ByteSwap.h.
Referenced by INTEL_ORDER_VECTOR().
NETWORK_ORDER16
#define NETWORK_ORDER16 (x)
Value:
(x)
Definition at line 144 of file ByteSwap.h.
Referenced by CreateBulkDataIoChunkId(), and CreateIoChunkId().
NETWORK_ORDER32
#define NETWORK_ORDER32 (x)
Value:
(x)
Definition at line 145 of file ByteSwap.h.
Referenced by FCbValue::AsFloat32(), and FCbValue::AsUuid().
NETWORK_ORDER64
#define NETWORK_ORDER64 (x)
Value:
(x)
Definition at line 147 of file ByteSwap.h.
Referenced by FCbValue::AsDateTimeTicks(), FCbValue::AsFloat64(), FCbValue::AsTimeSpanTicks(), FXxHash128::FromByteArray(), FXxHash64::FromByteArray(), FXxHash128::ToByteArray(), and FXxHash64::ToByteArray().
NETWORK_ORDER_TCHARARRAY
#define NETWORK_ORDER_TCHARARRAY (x)
Definition at line 148 of file ByteSwap.h.
NETWORK_ORDERF
#define NETWORK_ORDERF (x)
Value:
(x)
Definition at line 146 of file ByteSwap.h.
Function Documentation
ByteSwap() [1/10]
template<> char16_t ByteSwap (char16_t Value) inline
Definition at line 161 of file ByteSwap.h.
References BYTESWAP_ORDER16(), and Value.
ByteSwap() [2/10]
template<> double ByteSwap (double Value) inline
Definition at line 160 of file ByteSwap.h.
References BYTESWAP_ORDERD(), and Value.
ByteSwap() [3/10]
template<> float ByteSwap (float Value) inline
Definition at line 159 of file ByteSwap.h.
References BYTESWAP_ORDERF(), and Value.
ByteSwap() [4/10]
template<> int16 ByteSwap (int16 Value) inline
Definition at line 153 of file ByteSwap.h.
References BYTESWAP_ORDER16(), and Value.
ByteSwap() [5/10]
template<> int32 ByteSwap (int32 Value) inline
Definition at line 155 of file ByteSwap.h.
References BYTESWAP_ORDER32(), and Value.
ByteSwap() [6/10]
template<> int64 ByteSwap (int64 Value) inline
Definition at line 157 of file ByteSwap.h.
References BYTESWAP_ORDER64(), and Value.
ByteSwap() [7/10]
template<typename T> T ByteSwap (T Value)
References Value.
ByteSwap() [8/10]
template<> uint16 ByteSwap (uint16 Value) inline
Definition at line 154 of file ByteSwap.h.
References BYTESWAP_ORDER16(), and Value.
ByteSwap() [9/10]
template<> uint32 ByteSwap (uint32 Value) inline
Definition at line 156 of file ByteSwap.h.
References BYTESWAP_ORDER32(), and Value.
ByteSwap() [10/10]
template<> uint64 ByteSwap (uint64 Value) inline
Definition at line 158 of file ByteSwap.h.
References BYTESWAP_ORDER64(), and Value.
BYTESWAP_ORDER16() [1/2]
FORCEINLINE int16 BYTESWAP_ORDER16 (int16 Val)
Definition at line 59 of file ByteSwap.h.
References BYTESWAP_ORDER16(), and FORCEINLINE.
BYTESWAP_ORDER16() [2/2]
FORCEINLINE uint16 BYTESWAP_ORDER16 (uint16 Val)
Definition at line 50 of file ByteSwap.h.
References Internal::ByteSwapGeneric16(), and FORCEINLINE.
Referenced by ByteSwap(), ByteSwap(), ByteSwap(), BYTESWAP_ORDER16(), and BYTESWAP_ORDER_TCHARARRAY().
BYTESWAP_ORDER32() [1/2]
FORCEINLINE int32 BYTESWAP_ORDER32 (int32 val)
Definition at line 73 of file ByteSwap.h.
References BYTESWAP_ORDER32(), and FORCEINLINE.
BYTESWAP_ORDER32() [2/2]
FORCEINLINE uint32 BYTESWAP_ORDER32 (uint32 Val)
Definition at line 64 of file ByteSwap.h.
References Internal::ByteSwapGeneric32(), and FORCEINLINE.
Referenced by ByteSwap(), ByteSwap(), BYTESWAP_ORDER32(), BYTESWAP_ORDERF(), FOodleCompressedArray::PeekSizes(), and FOodleCompressedArray::PeekSizes64().
BYTESWAP_ORDER64() [1/2]
FORCEINLINE int64 BYTESWAP_ORDER64 (int64 Value)
Definition at line 87 of file ByteSwap.h.
References BYTESWAP_ORDER64(), FORCEINLINE, and Value.
BYTESWAP_ORDER64() [2/2]
FORCEINLINE uint64 BYTESWAP_ORDER64 (uint64 Value)
Definition at line 78 of file ByteSwap.h.
References Internal::ByteSwapGeneric64(), FORCEINLINE, and Value.
Referenced by ByteSwap(), ByteSwap(), BYTESWAP_ORDER64(), BYTESWAP_ORDERD(), and FOodleCompressedArray::PeekSizes64().
BYTESWAP_ORDER_TCHARARRAY()
FORCEINLINE void BYTESWAP_ORDER_TCHARARRAY (TCHAR * str)
Definition at line 115 of file ByteSwap.h.
References BYTESWAP_ORDER16(), and FORCEINLINE.
BYTESWAP_ORDERD()
FORCEINLINE double BYTESWAP_ORDERD (double val)
Definition at line 98 of file ByteSwap.h.
References BYTESWAP_ORDER64(), and FORCEINLINE.
Referenced by ByteSwap().
BYTESWAP_ORDERF()
FORCEINLINE float BYTESWAP_ORDERF (float val)
Definition at line 92 of file ByteSwap.h.
References BYTESWAP_ORDER32(), and FORCEINLINE.
Referenced by ByteSwap().