Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Camera/CameraComponent.h File Reference
CameraComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ScriptInterface.h"
#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/BlendableInterface.h"
#include "Engine/Scene.h"
#include "Camera/CameraTypes.h"
#include "CameraComponent.generated.h"
Data Structures
class UCameraComponent
Functions
UCLASS() class UCameraProxyMeshComponent UCLASS ()
Allows a custom SceneProxy to interact with camera specific show flags.
Variables
UCLASS() class UCameraProxyMeshComponent Blueprintable
UCLASS() class UCameraProxyMeshComponent ClassGroup =Camera
UCLASS() class UCameraProxyMeshComponent meta =(BlueprintSpawnableComponent)
Function Documentation
UCLASS()
UCLASS() class UCameraProxyMeshComponent UCLASS ()
Allows a custom SceneProxy to interact with camera specific show flags.
Represents a camera viewpoint and settings, such as projection type, field of view, and post-process overrides. The default behavior for an actor used as the camera view target is to look for an attached camera component and use its location, rotation, and settings.
Variable Documentation
Blueprintable
UCLASS() class UCameraProxyMeshComponent Blueprintable
Definition at line 31 of file CameraComponent.h.
ClassGroup
UCLASS() class UCameraProxyMeshComponent ClassGroup =Camera
Definition at line 31 of file CameraComponent.h.
meta
UCLASS() class UCameraProxyMeshComponent meta =(BlueprintSpawnableComponent)
Definition at line 31 of file CameraComponent.h.
Referenced by UCameraComponent::GENERATED_UCLASS_BODY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), UCameraComponent::UPROPERTY(), and UCameraComponent::UPROPERTY().