Unreal Engine 5.6 C++ API: Runtime/Engine/Public/CanvasTypes.h File Reference
CanvasTypes.h File Reference
#include "CoreMinimal.h"
#include "GameTime.h"
#include "SceneTypes.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "HitProxies.h"
#include "CanvasTypes.generated.h"
Data Structures
class FCanvas
Encapsulates the canvas state.
class FCanvas::FCanvasSortElement
Contains all of the batched elements that need to be rendered at a certain depth sort key.
class FCanvas::FTransformEntry
Entry for the transform stack which stores a matrix and its CRC for faster comparisons.
class FCanvasBaseRenderItem
Base interface for canvas items which can be batched for rendering.
class FCanvasWordWrapper
struct FCanvasWordWrapper::FWrappingState
struct FScreenMessageWriter
Helper class to write a line of texts on screen.
Namespaces
namespace ERHIFeatureLevel
Typedefs
using FRDGTextureRef = FRDGTexture*
Functions
void StringSize (const UFont *Font, int32 &XL, int32 &YL, FStringView Text)
Render string using both a font and a material.
USTRUCT () struct FTextSizingParameters
General purpose data structure for grouping all parameters needed when sizing or wrapping a string.
Typedef Documentation
FRDGTextureRef
using FRDGTextureRef = FRDGTexture*
Definition at line 34 of file CanvasTypes.h.
Function Documentation
StringSize()
void StringSize (const UFont * Font, int32 & XL, int32 & YL, FStringView Text) extern
Render string using both a font and a material.
The material should have a font exposed as a parameter so that the correct font page can be set based on the character being drawn.
Parameters
Font - font containing texture pages of character glyphs
XL - out width
YL - out height
Text - string of text to be measured
References Text.
Referenced by Audio::FTabularRenderHelper::AddCol(), Audio::FTabularRenderHelper::RightJustify(), FAndroidPlatformString::Strnlen(), FAndroidPlatformString::Strnlen(), FAndroidPlatformString::Strnlen(), FAndroidPlatformString::Strnlen(), FMicrosoftPlatformString::Strnlen(), FMicrosoftPlatformString::Strnlen(), FMicrosoftPlatformString::Strnlen(), FMicrosoftPlatformString::Strnlen(), TCString< T >::Strnlen(), and TCString< TCHAR >::Strnlen().
USTRUCT()
USTRUCT ()
General purpose data structure for grouping all parameters needed when sizing or wrapping a string.
Used by UUIString::WrapString to track information about each line that is generated as the result of wrapping.
a pixel value representing the horizontal screen location to begin rendering the string
a pixel value representing the vertical screen location to begin rendering the string
a pixel value representing the width of the area available for rendering the string
a pixel value representing the height of the area available for rendering the string
A value between 0.0 and 1.0, which represents how much the width/height should be scaled, where 1.0 represents 100% scaling.
the font to use for sizing/wrapping the string
Horizontal spacing adjustment between characters and vertical spacing adjustment between wrapped lines
the string associated with this line
the size (in pixels) that it will take to render this string
Definition at line 40 of file CanvasTypes.h.
References ForceInit, GENERATED_USTRUCT_BODY, ScaleX, ScaleY, and UPROPERTY.