Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/Templates/Casts.h File Reference
Casts.h File Reference
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "Misc/NotNull.h"
#include "Templates/LosesQualifiersFromTo.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/Class.h"
#include "UObject/Object.h"
#include "UObject/ObjectHandle.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectPtr.h"
#include <type_traits>
Data Structures
struct TIsIInterface< T, bIsAUObject_IMPL >
Metafunction which detects whether or not a class is an IInterface.
struct TIsIInterface< T, false >
struct UE::CoreUObject::Private::TIsCastable< T >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::CoreUObject
namespace UE::CoreUObject::Private
Macros
#define DECLARE_CAST_BY_FLAG(ClassName)
#define dynamic_cast UE::CoreUObject::Private::DynamicCast
#define UE_ENABLE_UNRELATED_CAST_WARNINGS 1
#define UE_USE_CAST_FLAGS (USTRUCT_FAST_ISCHILDOF_IMPL != USTRUCT_ISCHILDOF_STRUCTARRAY)
Functions
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (const TObjectPtr< From > &InSrc)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (const TSubclassOf< From > &Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (const TWeakObjectPtr< From > &Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (From *Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TObjectPtr< From > &Src, ECastCheckedType::Type CheckType=ECastCheckedType::NullChecked)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TSubclassOf< From > &Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TSubclassOf< From > &Src, ECastCheckedType::Type CheckType)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TWeakObjectPtr< From > &Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TWeakObjectPtr< From > &Src, ECastCheckedType::Type CheckType)
template<typename To, typename From>
FUNCTION_NON_NULL_RETURN_START FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (From *Src) FUNCTION_NON_NULL_RETURN_END
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (From *Src, ECastCheckedType::Type CheckType)
void CastLogError (const TCHAR *FromType, const TCHAR *ToType)
template<typename To, typename From>
FORCEINLINE To UE::CoreUObject::Private::DynamicCast (From &&Arg)
template<typename To, typename From>
FORCEINLINE To UE::CoreUObject::Private::DynamicCast (From *Arg)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * ExactCast (const TObjectPtr< From > &Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * ExactCast (const TWeakObjectPtr< From > &Src)
template<typename To, typename From>
FORCEINLINE TCopyQualifiersFromTo_T< From, To > * ExactCast (From *Src)
template<typename T>
FORCEINLINE FString GetTypeName ()
template<typename Type>
struct UE_DEPRECATED (5.5, "TCastFlags has been deprecated - use Cast instead.") TCastFlags
Variables
template<typename Type>
constexpr EClassCastFlags UE::CoreUObject::Private::TCastFlags_V = CASTCLASS_None
template<typename Type>
constexpr EClassCastFlags UE::CoreUObject::Private::TCastFlags_V< const Type > = TCastFlags_V<Type>
Macro Definition Documentation
DECLARE_CAST_BY_FLAG
#define DECLARE_CAST_BY_FLAG (ClassName)
Value:
    class ClassName; \
    template <> \
    constexpr inline EClassCastFlags UE::CoreUObject::Private::TCastFlags_V<ClassName> = CASTCLASS_##ClassName;
Definition at line 465 of file Casts.h.
dynamic_cast
#define dynamic_cast UE::CoreUObject::Private::DynamicCast
Definition at line 591 of file Casts.h.
UE_ENABLE_UNRELATED_CAST_WARNINGS
#define UE_ENABLE_UNRELATED_CAST_WARNINGS 1
Definition at line 20 of file Casts.h.
UE_USE_CAST_FLAGS
#define UE_USE_CAST_FLAGS (USTRUCT_FAST_ISCHILDOF_IMPL != USTRUCT_ISCHILDOF_STRUCTARRAY)
Definition at line 17 of file Casts.h.
Referenced by Cast(), Cast(), and CastChecked().
Function Documentation
Cast() [1/4]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (const TObjectPtr< From > & InSrc)
Definition at line 313 of file Casts.h.
References CASTCLASS_None, FORCEINLINE, FObjectPtr::Get(), FObjectPtr::GetClass(), FObjectPtr::GetHandleRef(), UObjectBaseUtility::GetInterfaceAddress(), UClass::HasAnyCastFlag(), FObjectPtr::IsA(), UE::CoreUObject::Private::OnHandleRead(), UE::CoreUObject::Private::ResolveObjectHandleNoRead(), UE::CoreUObject::Private::TCastFlags_V, UE_STATIC_ASSERT_WARN, UE_USE_CAST_FLAGS, and TIsIInterface< T, bIsAUObject_IMPL >::Value.
Cast() [2/4]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (const TSubclassOf< From > & Src)
Definition at line 426 of file Casts.h.
References Cast(), and FORCEINLINE.
Cast() [3/4]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (const TWeakObjectPtr< From > & Src)
Definition at line 291 of file Casts.h.
References Cast(), FORCEINLINE, and TWeakObjectPtr< T, TWeakObjectPtrBase >::Get().
Cast() [4/4]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * Cast (From * Src)
Definition at line 95 of file Casts.h.
References CASTCLASS_None, FORCEINLINE, UE::CoreUObject::Private::TCastFlags_V, UE_STATIC_ASSERT_WARN, UE_USE_CAST_FLAGS, and TIsIInterface< T, bIsAUObject_IMPL >::Value.
Referenced by FCanvasSimpleTextItem::FCanvasSimpleTextItem(), FInitBodiesHelper< bCompileStatic, InAllocatorType >::FInitBodiesHelper(), FInitBodiesHelperWithData< bCompileStatic >::FInitBodiesHelperWithData(), FInitBodiesHelperWithData< bCompileStatic >::FInitBodiesHelperWithData(), FSkelMeshUpdateContext::FSkelMeshUpdateContext(), UE::Core::Private::TPtrVariantBase< BaseType, true >::TPtrVariantBase(), TScriptInterface< const InterfaceType >::TScriptInterface(), TScriptInterface< const InterfaceType >::TScriptInterface(), TWeakInterfacePtr< IActorInstanceManagerInterface >::TWeakInterfacePtr(), TWeakInterfacePtr< IActorInstanceManagerInterface >::TWeakInterfacePtr(), UE::Core::Private::TMaybeObjectPtr< T >::AddReferencedObject(), TBasePlayerControllerIterator< T, true >::AdvanceCurrent(), FGameModeInfoCustomizer::AllowModifyGameMode(), FStaticLightingTextureMapping_InstancedStaticMesh::Apply(), Cast(), Cast(), CastChecked(), UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit(), UE::Core::Private::TMaybeObjectPtr< T >::ConditionallyMarkAsReachable(), UProperty::ContainerVoidPtrToValuePtrInternal(), FMovieSceneChannelProxy::CopyHandle(), ToolBuilderUtil::CountSelectedActorsOfType(), ToolBuilderUtil::CountSelectedComponentsOfType(), RigVMTypeUtils::CPPTypeFromObject(), AnimationEditorUtils::CreateAnimationAsset(), FBlueprintEditorUtils::CreateFunctionGraph(), UE::GizmoUtil::CreateGizmoViaSimpleBuilder(), SCommonButtonTableRow< ItemType >::DetectItemSelectionChanged(), EditorAnimUtils::DuplicateAssets(), UE::CoreUObject::Private::DynamicCast(), AnimationEditorUtils::ExecuteNewAnimAsset(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::ExportTypes(), DisplayClusterHelpers::game::FindAllActors(), FStructOnScopeStructureDataProvider::FindBaseStructure(), MaterialInstance_Private::FindClosestExpressionByGUIDRecursive(), ToolBuilderUtil::FindFirstActorOfType(), ToolBuilderUtil::FindFirstComponentOfType(), IMovieSceneBindingOwnerInterface::FindFromObject(), RigVMTypeUtils::FindObjectFromCPPTypeObjectPath(), UE::Editor::FindOrCreateThumbnailInfo(), FindParentComponent(), RigVMTypeUtils::FixCPPTypeAndObject(), FEditorModeTools::ForEachEdMode(), UE::MovieScene::TApplyMaterialSwitchers< AccessorType, RequiredComponents >::ForEachEntity(), FBindingObject::Get(), FGeometryIdentifier::GetAsComponentType(), FGeometryIdentifier::GetAsObjectType(), EditorAnimUtils::GetAssetsFromProperties(), IInterface_AssetUserData::GetAssetUserData(), FLevelEditorViewportClient::GetCameraComponentForView(), FSCSEditorTreeNode::GetComponentTemplate(), APawn::GetController(), FNavigationSystem::GetCurrent(), FNavigationSystem::GetCurrent(), FKismetNodeInfoContext::FObjectUUIDPair::GetDisplayName(), FSCSEditorTreeNode::GetEditableObjectForBlueprint(), AGameModeBase::GetGameState(), FLocalPlayerContext::GetGameState(), FLocalPlayerContext::GetHUD(), FStreamableHandle::GetLoadedAsset(), FStreamableHandle::GetLoadedAssets(), FSCSEditorTreeNode::GetMutableObject(), FSCSEditorTreeNode::GetObject(), IDetailLayoutBuilder::GetObjectsOfTypeBeingCustomized(), FReferenceGraphNode::GetObjectToDisplay(), FSCSEditorTreeNode::GetOrCreateEditableComponentTemplate(), FPrimitiveSceneProxyDesc::GetOwner(), IPrimitiveComponent::GetOwner(), UActorComponent::GetOwner(), UE::DisplayClusterViewportHelpers::GetOwnerRootActorComponentByName(), FPhysScene_Chaos::GetOwningComponent(), FCurveModel::GetOwningObjectOrOuter(), CommonUIUtils::GetOwningUserWidget(), AController::GetPawn(), FLocalPlayerContext::GetPawn(), FLocalPlayerContext::GetPlayerController(), AController::GetPlayerState(), APawn::GetPlayerState(), FLocalPlayerContext::GetPlayerState(), IAnimAssetFindReplace::GetProcessor(), UPostProcessComponent::GetProperties(), FMeshSculptBrushOp::GetPropertySetAs(), FMeshSculptBrushOp::GetPropertySetAs(), IDetailLayoutBuilder::GetSelectedObjectsOfType(), UAIPerceptionComponent::GetSenseConfig(), FRigVMASTProxy::GetSubject(), IGenericTeamAgentInterface::GetTeamAttitudeTowards(), TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeAtIndex(), RigVMTypeUtils::GetUniqueStructTypeName(), IPrimitiveComponent::GetUObject(), IPrimitiveComponent::GetUObject(), FStaticMeshSceneProxyDesc::GetUStaticMeshComponent(), FPropertyBagArrayRef::GetValueObject(), FWorldPartitionHelpersPrivate::GetWorldPartition(), SLoadGuard::GuardAndLoadAsset(), FChannelCurveModel< ChannelType, ChannelValue, KeyType >::HasChangedAndResetTest(), FCurveControlPointsMechanicInsertionChange::HasExpired(), FCurveControlPointsMechanicModeChange::HasExpired(), FCurveControlPointsMechanicMovementChange::HasExpired(), FCurveControlPointsMechanicSelectionChange::HasExpired(), FGroupEdgeInsertionFirstPointChange::HasExpired(), FLatticeControlPointsMechanicMovementChange::HasExpired(), FLatticeControlPointsMechanicSelectionChange::HasExpired(), FLatticeDeformerToolConstrainedPointsChange::HasExpired(), FPolyEditCutFacesActivityFirstPointChange::HasExpired(), IAssetBackedTarget::HasSameSourceData(), FBookMarkTypeActions::InitFromViewport(), UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::InitializeBoundMaterial(), FSubsystemCollectionBase::InitializeDependency(), SCommonButtonTableRow< ItemType >::InitializeObjectRow(), FInstancedSkinnedMeshComponentHelper::IsEnabled(), FSelectedEditableComponentFilter::IsObjectValid(), FSCSEditorTreeNode::IsSceneComponent(), FMovieSceneDirectorBlueprintConditionUtils::IterateDirectorBlueprintConditions(), FBookmarkSingleViewportActions::JumpToBookmark(), FBookMarkTypeActions::JumpToBookmark(), FSoundWaveLoadingBehaviorUtil::LoadAndCacheClass(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FStreamableManager::LoadSynchronous(), FStreamableManager::LoadSynchronous(), FStreamableManager::LoadSynchronous(), TSoftObjectPtr< const T >::LoadSynchronous(), FMovieSceneChannelProxy::MakeHandle(), UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeAndExportToken(), FBasePinChangeHelper::NodeIsNotTransient(), SRigVMActionMenu::OnCreateWidgetForAction(), SCommonButtonTableRow< ItemType >::OnItemSelectionChanged(), TExternalDirtyActorsTracker< StoreType >::OnObjectsReplaced(), IMovieSceneKeyProxy::OnProxyValueChanged(), FGameModeInfoCustomizer::OnSetDefaultClass(), TWidgetFactory< UUserWidget >::OwningObjectAsGameInstance(), TWidgetFactory< UUserWidget >::OwningObjectAsPlayerController(), TWidgetFactory< UUserWidget >::OwningObjectAsWorld(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendChannel(), UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::RecomposeBlendImpl(), USoundCue::RecursiveFindNode(), USoundCue::RecursiveFindNode(), UE::MovieScene::FBoundObjectPreAnimatedStateTraits::ReplaceObject(), SCommonButtonTableRow< ItemType >::ResetObjectRow(), FSkeletalMeshRestoreState::SaveState(), UE::Net::TStructNetTokenDataStoreHelper< T >::SerializeHelper(), SCommonButtonTableRow< ItemType >::SLATE_END_ARGS(), FGameModeInfoCustomizer::SyncBrowserToClass(), Verse::FNativeConverter::ToVValue(), SRigVMActionMenu::TryInsertPromoteToVariable(), UCLASS(), FKCHandler_CallFunction::UE_DEPRECATED(), FAnimNodeAlphaOptions::Update(), MaterialInstance_Private::UpdateParameter_FullTraversal(), FDisplayClusterActorRef::UpdateWorldPtr(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and FWidgetBlueprintCompilerContext::WidgetBlueprint().
CastChecked() [1/7]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TObjectPtr< From > & Src, ECastCheckedType::Type CheckType = ECastCheckedType::NullChecked)
Definition at line 384 of file Casts.h.
References Cast(), CASTCLASS_None, CastLogError(), FORCEINLINE, TObjectPtr< T >::Get(), GetTypeName(), ECastCheckedType::NullChecked, UE::CoreUObject::Private::OnHandleRead(), UE::CoreUObject::Private::ResolveObjectHandleNoRead(), UE::CoreUObject::Private::TCastFlags_V, TEXT, UE_USE_CAST_FLAGS, and TIsIInterface< T, bIsAUObject_IMPL >::Value.
CastChecked() [2/7]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TSubclassOf< From > & Src)
Definition at line 431 of file Casts.h.
References CastChecked(), and FORCEINLINE.
CastChecked() [3/7]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TSubclassOf< From > & Src, ECastCheckedType::Type CheckType)
Definition at line 436 of file Casts.h.
References CastChecked(), and FORCEINLINE.
CastChecked() [4/7]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TWeakObjectPtr< From > & Src)
Definition at line 301 of file Casts.h.
References CastChecked(), FORCEINLINE, and TWeakObjectPtr< T, TWeakObjectPtrBase >::Get().
CastChecked() [5/7]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (const TWeakObjectPtr< From > & Src, ECastCheckedType::Type CheckType)
Definition at line 306 of file Casts.h.
References CastChecked(), FORCEINLINE, and TWeakObjectPtr< T, TWeakObjectPtrBase >::Get().
CastChecked() [6/7]
template<typename To, typename From> FUNCTION_NON_NULL_RETURN_START FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (From * Src)
Definition at line 249 of file Casts.h.
References FORCEINLINE, FUNCTION_NON_NULL_RETURN_END, UObjectBaseUtility::GetInterfaceAddress(), and TIsIInterface< T, bIsAUObject_IMPL >::Value.
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToHandle(), CastChecked(), CastChecked(), CastChecked(), CastChecked(), CastChecked(), FSequencerKeyStructGenerator::CopyInstanceToKey(), AnimationEditorUtils::CreateAnimationAsset(), UE::CoreUObject::Private::DynamicCast(), AnimationEditorUtils::ExecuteNewAnimAsset(), FCompilerResultsLog::FindSourceObjectTypeChecked(), FCompilerResultsLog::FindSourceObjectTypeChecked(), FMovieSceneBlendChannelID::FindSystem(), FAudioDevice::ForEachSubsystem(), FAudioSubsystemCollection::ForEachSubsystem(), FObjectSubsystemCollection< TBaseType >::ForEachSubsystemWithInterface(), UDebugCameraControllerSettings::Get(), IAnimationEditorsAssetFamilyInterface::GetAssetOfType(), IInterface_AssetUserData::GetAssetUserDataChecked(), ACharacter::GetCharacterMovement(), FHLODCreationParams::GetExternalDataLayerAsset(), FLocalPlayerContext::GetGameState(), FLocalPlayerContext::GetHUD(), FLocalPlayerContext::GetPawn(), FLocalPlayerContext::GetPlayerController(), FLocalPlayerContext::GetPlayerState(), APawn::GetPlayerStateChecked(), TSubSectionMixin< ParentSectionClass >::GetSectionObjectAs(), TSubSectionMixin< ParentSectionClass >::GetSectionObjectAs(), FRigVMASTProxy::GetSubjectChecked(), FObjectEditorUtils::GetTypedWeakObjectPtrs(), UPhysicsCollisionHandler::GetWorld(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), TActorIterator< ActorType >::operator*(), FSequencerTrackFilter_ComponentType< InComponentType >::PassesFilter(), PostConstructKeyInstance(), UShapeComponent::PrepareSharedBodySetup(), UCLASS(), MaterialInstance_Private::UpdateParameter_FullTraversal(), USTRUCT(), USTRUCT(), and USTRUCT().
CastChecked() [7/7]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * CastChecked (From * Src, ECastCheckedType::Type CheckType)
Definition at line 282 of file Casts.h.
References CastChecked(), and FORCEINLINE.
CastLogError()
void CastLogError (const TCHAR * FromType, const TCHAR * ToType)
Referenced by CastChecked().
ExactCast() [1/3]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * ExactCast (const TObjectPtr< From > & Src)
Definition at line 370 of file Casts.h.
References FORCEINLINE, UObjectBase::GetClass(), UE::CoreUObject::Private::OnHandleRead(), and UE::CoreUObject::Private::ResolveObjectHandleNoRead().
ExactCast() [2/3]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * ExactCast (const TWeakObjectPtr< From > & Src)
Definition at line 296 of file Casts.h.
References ExactCast(), FORCEINLINE, and TWeakObjectPtr< T, TWeakObjectPtrBase >::Get().
ExactCast() [3/3]
template<typename To, typename From> FORCEINLINE TCopyQualifiersFromTo_T< From, To > * ExactCast (From * Src)
Definition at line 174 of file Casts.h.
References FORCEINLINE.
Referenced by ExactCast(), and FPlaneBrushOp::GetReferencePlaneType().
GetTypeName()
template<typename T> FORCEINLINE FString GetTypeName ()
Definition at line 66 of file Casts.h.
References FORCEINLINE, and TIsIInterface< T, bIsAUObject_IMPL >::Value.
Referenced by CastChecked(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), TCueDispatchTable< TCueHandler >::Dispatch(), FSavedCue::GetDebugName(), FNetSimCueDispatcher::Invoke(), and USTRUCT().
UE_DEPRECATED()
template<typename Type> struct UE_DEPRECATED (5. 5, "TCastFlags has been deprecated - use Cast instead.")
Definition at line 66 of file Casts.h.