Unreal Engine 5.6 C++ API: Runtime/Core/Public/Hash/CityHash.h File Reference
CityHash.h File Reference
#include "CoreTypes.h"
Data Structures
struct Uint128_64
Functions
uint64 CityHash128to64 (const Uint128_64 &x)
uint32 CityHash32 (const char *buf, uint32 len)
uint64 CityHash64 (const char *buf, uint32 len)
uint64 CityHash64WithSeed (const char *buf, uint32 len, uint64 seed)
uint64 CityHash64WithSeeds (const char *buf, uint32 len, uint64 seed0, uint64 seed1)
Function Documentation
CityHash128to64()
uint64 CityHash128to64 (const Uint128_64 & x) inline
Definition at line 91 of file CityHash.h.
References Uint128_64::hi, and Uint128_64::lo.
CityHash32()
uint32 CityHash32 (const char * buf, uint32 len)
CityHash64()
uint64 CityHash64 (const char * buf, uint32 len)
Referenced by FHashBuilder::AppendRaw(), FGuid::GetTypeHash, FRepSharedPropertyKey::GetTypeHash, FWorldPartitionCookPackage::MakeCookPackageID(), and USTRUCT().
CityHash64WithSeed()
uint64 CityHash64WithSeed (const char * buf, uint32 len, uint64 seed)
Referenced by AppendCityHash().
CityHash64WithSeeds()
uint64 CityHash64WithSeeds (const char * buf, uint32 len, uint64 seed0, uint64 seed1)