Unreal Engine 5.6 C++ API: UDataDrivenConsoleVariableSettings Class Reference
UDataDrivenConsoleVariableSettings Class Reference
#include "DataDrivenCVars.h"
Protected Attributes
TArray< FString > ShadowCVars
Private Member Functions
virtual FName GetCategoryName () const
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
UPROPERTY () TArray< FDataDrivenConsoleVariable > CVarsArray
Static Private Member Functions
static void OnDataDrivenChange (IConsoleVariable *CVar)
Private Attributes
GENERATED_BODY() public FOnStageChanged OnStageChanged
Detailed Description
Definition at line 85 of file DataDrivenCVars.h.
Member Function Documentation
GetCategoryName()
virtual FName UDataDrivenConsoleVariableSettings::GetCategoryName () const private virtual
OnDataDrivenChange()
void UDataDrivenConsoleVariableSettings::OnDataDrivenChange (IConsoleVariable * CVar) static private
References OnDataDrivenChange().
Referenced by OnDataDrivenChange().
PostEditChangeProperty()
virtual void UDataDrivenConsoleVariableSettings::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UDataDrivenConsoleVariableSettings::PostInitProperties () override private virtual
References PostInitProperties().
Referenced by PostInitProperties().
UPROPERTY()
UDataDrivenConsoleVariableSettings::UPROPERTY () private
References Category, and config.
Field Documentation
OnStageChanged
GENERATED_BODY () public FOnStageChanged UDataDrivenConsoleVariableSettings::OnStageChanged private
Definition at line 92 of file DataDrivenCVars.h.
ShadowCVars
TArray<FString> UDataDrivenConsoleVariableSettings::ShadowCVars protected
Definition at line 110 of file DataDrivenCVars.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/DataDrivenCVars/DataDrivenCVars.h