Unreal Engine 5.6 C++ API: UE::Color::FColorSpace Class Reference
UE::Color::FColorSpace Class Reference
Color space definition as 4 chromaticity coordinates, in double precision internally.
#include "ColorSpace.h"
Public Member Functions
FColorSpace ()
Constructor.
FColorSpace (const FColorSpace &)=default
FColorSpace (const FVector2d &InRed, const FVector2d &InGreen, const FVector2d &InBlue, const FVector2d &InWhite)
Constructor.
FColorSpace (FColorSpace &&)=default
FColorSpace (UE::Color::EColorSpace ColorSpaceType)
Constructor.
bool Equals (const FColorSpace &ColorSpace, double Tolerance=1.e-7) const
Check against another color space for equality, within specified error limits.
bool Equals (const TStaticArray< FVector2d, 4 > &InChromaticities, double Tolerance=1.e-7) const
Check against color space chromaticities for equality, within specified error limits.
const FVector2d & GetBlueChromaticity () const
Gets the color space's blue chromaticity coordinates.
template<typename T>
void GetChromaticities (UE::Math::TVector2< T > &OutRed, UE::Math::TVector2< T > &OutGreen, UE::Math::TVector2< T > &OutBlue, UE::Math::TVector2< T > &OutWhite) const
Getter for the color space chromaticity coordinates.
const FVector2d & GetGreenChromaticity () const
Gets the color space's green chromaticity coordinates.
float GetLuminance (const FLinearColor &Color) const
Calculate the color's luminance value in the current space.
FLinearColor GetLuminanceFactors () const
Get the luminance factors in the current space.
const FVector2d & GetRedChromaticity () const
Gets the color space's red chromaticity coordinates.
const FMatrix44d & GetRgbToXYZ () const
Gets the RGB-to-XYZ conversion matrix.
const FVector2d & GetWhiteChromaticity () const
Gets the color space's white point chromaticity coordinates.
const FMatrix44d & GetXYZToRgb () const
Gets the XYZ-to-RGB conversion matrix.
bool IsSRGB () const
Convenience function to verify if the color space matches the engine's default sRGB chromaticities.
FLinearColor MakeFromColorTemperature (float Temp) const
Converts temperature in Kelvins of a black body radiator to an RGB color in the current space.
bool operator!= (const FColorSpace &ColorSpace) const
Check against another color space for inequality.
FColorSpace & operator= (const FColorSpace &)=default
FColorSpace & operator= (FColorSpace &&)=default
bool operator== (const FColorSpace &ColorSpace) const
Check against another color space for equality.
bool Serialize (FArchive &Ar)
Static Public Member Functions
static const FColorSpace & GetSRGB ()
Get a (statically cached) sRGB color space.
static const FColorSpace & GetWorking ()
Get the global engine working color space (as a singleton).
static TStaticArray< FVector2d, 4 > MakeChromaticities (UE::Color::EColorSpace ColorSpaceType)
Make the chromaticities of the color space type.
static void SetWorking (FColorSpace ColorSpace)
Set the global engine working color space (as a singleton).
Private Member Functions
FMatrix44d CalcRgbToXYZ () const
Private Attributes
bool bIsSRGB
TStaticArray< FVector2d, 4 > Chromaticities
Red, green, blue, white chromaticities, in order.
FMatrix44d RgbToXYZ
FMatrix44d XYZToRgb
Friends
FArchive & operator<< (FArchive &Ar, FColorSpace &CS)
Serializer.
Detailed Description
Color space definition as 4 chromaticity coordinates, in double precision internally.
Definition at line 97 of file ColorSpace.h.
Constructor & Destructor Documentation
FColorSpace() [1/5]
UE::Color::FColorSpace::FColorSpace () inline
Constructor.
Definition at line 122 of file ColorSpace.h.
Referenced by FColorSpace(), FColorSpace(), Equals(), GetSRGB(), GetWorking(), operator!=(), operator<<, operator=(), operator=(), operator==(), and SetWorking().
FColorSpace() [2/5]
UE::Color::FColorSpace::FColorSpace (const FVector2d & InRed, const FVector2d & InGreen, const FVector2d & InBlue, const FVector2d & InWhite) explicit
Constructor.
Parameters
InRed Chromaticity 2D coordinates for the red color.
InGreen Chromaticity 2D coordinates for the green color.
InBlue Chromaticity 2D coordinates for the blue color.
InWhite Chromaticity 2D coordinates for the white point.
FColorSpace() [3/5]
UE::Color::FColorSpace::FColorSpace (UE::Color::EColorSpace ColorSpaceType) explicit
Constructor.
Parameters
ColorSpaceType Color space type.
FColorSpace() [4/5]
UE::Color::FColorSpace::FColorSpace (FColorSpace &&) default
References FColorSpace().
FColorSpace() [5/5]
UE::Color::FColorSpace::FColorSpace (const FColorSpace &) default
References FColorSpace().
Member Function Documentation
CalcRgbToXYZ()
FMatrix44d UE::Color::FColorSpace::CalcRgbToXYZ () const private
Equals() [1/2]
bool UE::Color::FColorSpace::Equals (const FColorSpace & ColorSpace, double Tolerance = 1.e-7) const
Check against another color space for equality, within specified error limits.
Parameters
ColorSpace The color space to check against.
Tolerance Error tolerance.
Returns
true if the color spaces are equal within tolerance limits, false otherwise.
References FColorSpace().
Equals() [2/2]
bool UE::Color::FColorSpace::Equals (const TStaticArray< FVector2d, 4 > & InChromaticities, double Tolerance = 1.e-7) const
Check against color space chromaticities for equality, within specified error limits.
Parameters
InChromaticities The color space chromaticities to check against.
Tolerance Error tolerance.
Returns
true if the color spaces are equal within tolerance limits, false otherwise.
GetBlueChromaticity()
const FVector2d & UE::Color::FColorSpace::GetBlueChromaticity () const inline
Gets the color space's blue chromaticity coordinates.
Returns
FVector2d xy coordinates.
Definition at line 195 of file ColorSpace.h.
References Chromaticities.
GetChromaticities()
template<typename T> void UE::Color::FColorSpace::GetChromaticities (UE::Math::TVector2< T > & OutRed, UE::Math::TVector2< T > & OutGreen, UE::Math::TVector2< T > & OutBlue, UE::Math::TVector2< T > & OutWhite) const inline
Getter for the color space chromaticity coordinates.
Parameters
OutRed FVector2d for the red color chromaticity coordinate.
OutGreen FVector2d for the green color chromaticity coordinate.
OutBlue FVector2d for the blue color chromaticity coordinate.
OutWhite FVector2d for the white color chromaticity coordinate.
Definition at line 162 of file ColorSpace.h.
References Chromaticities.
GetGreenChromaticity()
const FVector2d & UE::Color::FColorSpace::GetGreenChromaticity () const inline
Gets the color space's green chromaticity coordinates.
Returns
FVector2d xy coordinates.
Definition at line 185 of file ColorSpace.h.
References Chromaticities.
GetLuminance()
float UE::Color::FColorSpace::GetLuminance (const FLinearColor & Color) const
Calculate the color's luminance value in the current space.
Parameters
Color The sampled color.
Returns
float Luminance value.
GetLuminanceFactors()
FLinearColor UE::Color::FColorSpace::GetLuminanceFactors () const
Get the luminance factors in the current space.
Returns
FLinearColor Luminance factors.
GetRedChromaticity()
const FVector2d & UE::Color::FColorSpace::GetRedChromaticity () const inline
Gets the color space's red chromaticity coordinates.
Returns
FVector2d xy coordinates.
Definition at line 175 of file ColorSpace.h.
References Chromaticities.
GetRgbToXYZ()
const FMatrix44d & UE::Color::FColorSpace::GetRgbToXYZ () const inline
Gets the RGB-to-XYZ conversion matrix.
Returns
FMatrix conversion matrix.
Definition at line 215 of file ColorSpace.h.
References RgbToXYZ.
GetSRGB()
const FColorSpace & UE::Color::FColorSpace::GetSRGB () static
Get a (statically cached) sRGB color space.
Returns
FColorSpace sRGB color space
References FColorSpace().
GetWhiteChromaticity()
const FVector2d & UE::Color::FColorSpace::GetWhiteChromaticity () const inline
Gets the color space's white point chromaticity coordinates.
Returns
FVector2d xy coordinates.
Definition at line 205 of file ColorSpace.h.
References Chromaticities.
GetWorking()
const FColorSpace & UE::Color::FColorSpace::GetWorking () static
Get the global engine working color space (as a singleton).
Returns
FColorSpace working color space
References FColorSpace().
Referenced by FAtmosphereSetup::InternalInit().
GetXYZToRgb()
const FMatrix44d & UE::Color::FColorSpace::GetXYZToRgb () const inline
Gets the XYZ-to-RGB conversion matrix.
Returns
FMatrix conversion matrix.
Definition at line 225 of file ColorSpace.h.
References XYZToRgb.
IsSRGB()
bool UE::Color::FColorSpace::IsSRGB () const
Convenience function to verify if the color space matches the engine's default sRGB chromaticities.
Returns
true if sRGB.
Referenced by FAtmosphereSetup::InternalInit().
MakeChromaticities()
TStaticArray< FVector2d, 4 > UE::Color::FColorSpace::MakeChromaticities (UE::Color::EColorSpace ColorSpaceType) static
Make the chromaticities of the color space type.
Returns
TStaticArray of four chromaticities
MakeFromColorTemperature()
FLinearColor UE::Color::FColorSpace::MakeFromColorTemperature (float Temp) const
Converts temperature in Kelvins of a black body radiator to an RGB color in the current space.
operator!=()
bool UE::Color::FColorSpace::operator!= (const FColorSpace & ColorSpace) const inline
Check against another color space for inequality.
Parameters
ColorSpace The color space to check against.
Returns
true if the color spaces are not equal, false otherwise.
Definition at line 247 of file ColorSpace.h.
References FColorSpace(), and Chromaticities.
operator=() [1/2]
FColorSpace & UE::Color::FColorSpace::operator= (const FColorSpace &) default
References FColorSpace().
operator=() [2/2]
FColorSpace & UE::Color::FColorSpace::operator= (FColorSpace &&) default
References FColorSpace().
operator==()
bool UE::Color::FColorSpace::operator== (const FColorSpace & ColorSpace) const inline
Check against another color space for equality.
Parameters
ColorSpace The vector to check against.
Returns
true if the color spaces are equal, false otherwise.
Definition at line 236 of file ColorSpace.h.
References FColorSpace(), and Chromaticities.
Serialize()
bool UE::Color::FColorSpace::Serialize (FArchive & Ar) inline
Definition at line 324 of file ColorSpace.h.
References Ar.
SetWorking()
void UE::Color::FColorSpace::SetWorking (FColorSpace ColorSpace) static
Set the global engine working color space (as a singleton).
Parameters
ColorSpace working color space
References FColorSpace().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FColorSpace & CS) friend
Serializer.
Parameters
Ar The Serialization Archive.
CS The Color Space being serialized.
Returns
Reference to the Archive after serialization.
Definition at line 319 of file ColorSpace.h.
References FColorSpace(), Ar, and Chromaticities.
Field Documentation
bIsSRGB
bool UE::Color::FColorSpace::bIsSRGB private
Definition at line 308 of file ColorSpace.h.
Chromaticities
TStaticArray<FVector2d, 4> UE::Color::FColorSpace::Chromaticities private
Red, green, blue, white chromaticities, in order.
Definition at line 303 of file ColorSpace.h.
Referenced by GetBlueChromaticity(), GetChromaticities(), GetGreenChromaticity(), GetRedChromaticity(), GetWhiteChromaticity(), operator!=(), operator<<, and operator==().
RgbToXYZ
FMatrix44d UE::Color::FColorSpace::RgbToXYZ private
Definition at line 305 of file ColorSpace.h.
Referenced by GetRgbToXYZ().
XYZToRgb
FMatrix44d UE::Color::FColorSpace::XYZToRgb private
Definition at line 306 of file ColorSpace.h.
Referenced by GetXYZToRgb().
The documentation for this class was generated from the following file:
Runtime/Core/Public/ColorManagement/ColorSpace.h