Unreal Engine 5.6 C++ API: FReply Class Reference
FReply Class Reference
A Reply is something that a Slate event returns to the system to notify it about certain aspect of how an event was handled.
#include "Reply.h"
Public Member Functions
bool AffectsAllUsers () const
If the event replied with a request to change the user focus whether it should do it for all users or just the current UserIndex.
FReply & BeginDragDrop (TSharedRef< FDragDropOperation > InDragDropContent)
An event should return FReply::Handled().BeginDragDrop(Content) to initiate a drag and drop operation.
FReply & CancelFocusRequest ()
An event should rarely invoke FReply::CancelFocusRequest.
FReply & CaptureMouse (TSharedRef< SWidget > InMouseCaptor)
An event should return a FReply::Handled().CaptureMouse(SomeWidget) as a means of asking the system to forward all mouse events to SomeWidget.
FReply & ClearUserFocus (bool bInAllUsers=false)
An event should return a FReply::Handled().ClearUserFocus() to ask the system to clear user focus.
FReply & ClearUserFocus (EFocusCause ReasonFocusIsChanging, bool bInAllUsers=false)
An event should return a FReply::Handled().ClearUserFocus() to ask the system to clear user focus.
FReply & DetectDrag (const TSharedRef< SWidget > &DetectDragInMe, FKey MouseButton)
Ask Slate to detect if a user started dragging in this widget.
FReply & EndDragDrop ()
An event should return FReply::Handled().EndDragDrop() to request that the current drag/drop operation be terminated.
TSharedPtr< SWidget > GetDetectDragRequest () const
FKey GetDetectDragRequestButton () const
const TSharedPtr< FDragDropOperation > & GetDragDropContent () const
EFocusCause GetFocusCause () const
Get the reason that a focus change is being requested.
TSharedPtr< SWidget > GetMouseCaptor () const
If the event replied with a request to capture the mouse, this returns the desired mouse captor.
TSharedPtr< SWidget > GetMouseLockWidget () const
Returns the widget that the mouse should be locked to (if any)
TSharedPtr< SWidget > GetNavigationDestination () const
Get the widget that is the navigation destination.
ENavigationGenesis GetNavigationGenesis () const
Get the genesis of the navigation.
ENavigationSource GetNavigationSource () const
Get the source of the navigation.
EUINavigation GetNavigationType () const
Get the navigation type (Invalid if no navigation is requested).
const TOptional< FIntPoint > & GetRequestedMousePos () const
TSharedPtr< SWidget > GetUserFocusRecepient () const
When not nullptr, user focus has been requested to be set on the FocusRecipient.
FReply & LockMouseToWidget (TSharedRef< SWidget > InWidget)
An event should return FReply::Handled().LockMouseToWidget(SomeWidget) as a means of asking the system to Lock the mouse so it cannot move out of the bounds of the widget.
FReply & PreventThrottling ()
Ensures throttling for Slate UI responsiveness is not done on mouse down.
FReply & ReleaseMouseCapture ()
An event should return a FReply::Handled().ReleaseMouse() to ask the system to release mouse capture NOTE: Deactivates high precision mouse movement if activated.
FReply & ReleaseMouseLock ()
An event should return a FReply::Handled().ReleaseMouseLock() to ask the system to release mouse lock on a widget.
FReply & SetMousePos (const FIntPoint &NewMousePos)
An event should return FReply::Handled().SetMousePos to ask Slate to move the mouse cursor to a different location.
FReply & SetNavigation (EUINavigation InNavigationType, const ENavigationGenesis InNavigationGenesis, const ENavigationSource InNavigationSource=ENavigationSource::FocusedWidget)
An event should return FReply::Handled().SetNavigation(NavigationType) as a means of asking the system to attempt a navigation.
FReply & SetNavigation (TSharedRef< SWidget > InNavigationDestination, const ENavigationGenesis InNavigationGenesis, const ENavigationSource InNavigationSource=ENavigationSource::FocusedWidget)
An event should return FReply::Handled().SetNavigation(NavigationDestination) as a means of asking the system to attempt a navigation to the specified destination.
FReply & SetUserFocus (TSharedRef< SWidget > GiveMeFocus, EFocusCause ReasonFocusIsChanging=EFocusCause::SetDirectly, bool bInAllUsers=false)
An event should return FReply::Handled().SetUserFocus(SomeWidget) as a means of asking the system to set users focus to the provided widget.
bool ShouldEndDragDrop () const
bool ShouldReleaseMouse () const
True if this reply indicated that we should release mouse capture as a result of the event being handled.
bool ShouldReleaseMouseLock () const
True if the reply indicated that we should release mouse lock.
bool ShouldReleaseUserFocus () const
true if this reply indicated that we should release focus as a result of the event being handled
bool ShouldSetUserFocus () const
true if this reply indicated that we should set focus as a result of the event being handled
bool ShouldThrottle () const
Whether or not we should throttle on mouse down.
bool ShouldUseHighPrecisionMouse () const
True if this reply indicated that we should use high precision mouse movement.
FString ToString ()
Converts the reply into an string representation.
FReply & UseHighPrecisionMouseMovement (TSharedRef< SWidget > InMouseCaptor)
Enables the use of high precision (raw input) mouse movement, for more accurate mouse movement without mouse ballistics NOTE: This implies mouse capture and hidden mouse movement.
Public Member Functions inherited from TReplyBase< FReply >
TReplyBase (bool bIsHandled)
Public Member Functions inherited from FReplyBase
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately handled the event.
bool IsEventHandled () const
Static Public Member Functions
static FReply Handled ()
An event should return a FReply::Handled() to let the system know that an event was handled.
static FReply Unhandled ()
An event should return a FReply::Unhandled() to let the system know that an event was unhandled.
Private Member Functions
FReply (bool bIsHandled)
Hidden default constructor.
Private Attributes
uint32 bAllUsers: 1
uint32 bEndDragDrop: 1
uint32 bPreventThrottling: 1
uint32 bReleaseMouseCapture: 1
uint32 bReleaseUserFocus: 1
uint32 bSetUserFocus: 1
uint32 bShouldReleaseMouseLock: 1
uint32 bUseHighPrecisionMouse: 1
FKey DetectDragForMouseButton
TWeakPtr< SWidget > DetectDragForWidget
TSharedPtr< FDragDropOperation > DragDropContent
TWeakPtr< SWidget > EventHandler
EFocusCause FocusChangeReason
TWeakPtr< SWidget > FocusRecipient
TWeakPtr< SWidget > MouseCaptor
TWeakPtr< SWidget > MouseLockWidget
TWeakPtr< SWidget > NavigationDestination
ENavigationGenesis NavigationGenesis
ENavigationSource NavigationSource
EUINavigation NavigationType
TOptional< FIntPoint > RequestedMousePos
Friends
class FSlateApplication
Additional Inherited Members
Protected Member Functions inherited from TReplyBase< FReply >
FReply & Me ()
FReply & SetHandler (const TSharedRef< SWidget > &InHandler)
Set the widget that handled the event; undefined if never handled.
Protected Member Functions inherited from FReplyBase
FReplyBase (bool InIsHandled)
A reply can be handled or unhandled.
Protected Attributes inherited from FReplyBase
bool bIsHandled
Has a widget handled an event.
TSharedPtr< SWidget > EventHandler
Widget that handled the event that generated this reply.
Detailed Description
A Reply is something that a Slate event returns to the system to notify it about certain aspect of how an event was handled.
For example, a widget may handle an OnMouseDown event by asking the system to give mouse capture to a specific Widget. To do this, return FReply::CaptureMouse(NewMouseCapture).
Definition at line 23 of file Reply.h.
Constructor & Destructor Documentation
FReply()
FReply::FReply (bool bIsHandled) inline private
Hidden default constructor.
Definition at line 251 of file Reply.h.
References FReply(), TReplyBase< FReply >::TReplyBase(), bAllUsers, bEndDragDrop, FReplyBase::bIsHandled, bPreventThrottling, bReleaseMouseCapture, bReleaseUserFocus, bSetUserFocus, bShouldReleaseMouseLock, bUseHighPrecisionMouse, DetectDragForWidget, DragDropContent, EventHandler, FocusChangeReason, FocusRecipient, Invalid, MouseCaptor, MouseLockWidget, NavigationDestination, NavigationGenesis, NavigationSource, NavigationType, RequestedMousePos, and SetDirectly.
Referenced by FReply(), BeginDragDrop(), CancelFocusRequest(), CaptureMouse(), ClearUserFocus(), ClearUserFocus(), DetectDrag(), EndDragDrop(), Handled(), LockMouseToWidget(), PreventThrottling(), ReleaseMouseCapture(), ReleaseMouseLock(), SetMousePos(), SetNavigation(), SetNavigation(), SetUserFocus(), Unhandled(), and UseHighPrecisionMouseMovement().
Member Function Documentation
AffectsAllUsers()
bool FReply::AffectsAllUsers () const inline
If the event replied with a request to change the user focus whether it should do it for all users or just the current UserIndex.
Definition at line 175 of file Reply.h.
References bAllUsers.
BeginDragDrop()
FReply & FReply::BeginDragDrop (TSharedRef< FDragDropOperation > InDragDropContent) inline
An event should return FReply::Handled().BeginDragDrop(Content) to initiate a drag and drop operation.
Parameters
InDragDropContent The content that is being dragged. This could be a widget, or some arbitrary data
Returns
reference back to the FReply so that this call can be chained.
Definition at line 143 of file Reply.h.
References FReply(), DragDropContent, and TReplyBase< FReply >::Me().
CancelFocusRequest()
FReply & FReply::CancelFocusRequest ()
An event should rarely invoke FReply::CancelFocusRequest.
This will change the reply so that it no longer contains a request for the system to set or clear focus. This is most useful when a reply has been cached for use in async operations.
References FReply().
CaptureMouse()
FReply & FReply::CaptureMouse (TSharedRef< SWidget > InMouseCaptor) inline
An event should return a FReply::Handled().CaptureMouse(SomeWidget) as a means of asking the system to forward all mouse events to SomeWidget.
Definition at line 28 of file Reply.h.
References FReply(), TReplyBase< FReply >::Me(), and MouseCaptor.
Referenced by FArguments< ItemType >::OnDragDetected(), and FArguments< ItemType >::OnMouseButtonDown().
ClearUserFocus() [1/2]
FReply & FReply::ClearUserFocus (bool bInAllUsers = false) inline
An event should return a FReply::Handled().ClearUserFocus() to ask the system to clear user focus.
Definition at line 54 of file Reply.h.
References FReply(), and ClearUserFocus().
Referenced by ClearUserFocus().
ClearUserFocus() [2/2]
FReply & FReply::ClearUserFocus (EFocusCause ReasonFocusIsChanging, bool bInAllUsers = false)
An event should return a FReply::Handled().ClearUserFocus() to ask the system to clear user focus.
References FReply().
DetectDrag()
FReply & FReply::DetectDrag (const TSharedRef< SWidget > & DetectDragInMe, FKey MouseButton) inline
Ask Slate to detect if a user started dragging in this widget.
If a drag is detected, Slate will send an OnDragDetected event.
Parameters
DetectDragInMe Detect dragging in this widget
MouseButton This button should be pressed to detect the drag
Definition at line 129 of file Reply.h.
References FReply(), DetectDragForMouseButton, DetectDragForWidget, and TReplyBase< FReply >::Me().
Referenced by FArguments< ItemType >::OnMouseButtonDown(), and FArguments< ItemType >::OnTouchStarted().
EndDragDrop()
FReply & FReply::EndDragDrop () inline
An event should return FReply::Handled().EndDragDrop() to request that the current drag/drop operation be terminated.
Definition at line 150 of file Reply.h.
References FReply(), bEndDragDrop, and TReplyBase< FReply >::Me().
GetDetectDragRequest()
TSharedPtr< SWidget > FReply::GetDetectDragRequest () const inline
Returns
a widget for which to detect a drag; Invalid SharedPtr if no drag detection requested
Definition at line 217 of file Reply.h.
References DetectDragForWidget.
GetDetectDragRequestButton()
FKey FReply::GetDetectDragRequestButton () const inline
Returns
the mouse button for which we are detecting a drag
Definition at line 220 of file Reply.h.
References DetectDragForMouseButton.
GetDragDropContent()
const TSharedPtr< FDragDropOperation > & FReply::GetDragDropContent () const inline
Returns
the Content that we should use for the Drag and Drop operation; Invalid SharedPtr if a drag and drop operation is not requested
Definition at line 211 of file Reply.h.
References DragDropContent.
GetFocusCause()
EFocusCause FReply::GetFocusCause () const inline
Get the reason that a focus change is being requested.
Definition at line 193 of file Reply.h.
References FocusChangeReason.
GetMouseCaptor()
TSharedPtr< SWidget > FReply::GetMouseCaptor () const inline
If the event replied with a request to capture the mouse, this returns the desired mouse captor.
Otherwise returns an invalid pointer.
Definition at line 196 of file Reply.h.
References MouseCaptor.
Referenced by UE::Sequencer::FInputHandlerStack::ProcessReply().
GetMouseLockWidget()
TSharedPtr< SWidget > FReply::GetMouseLockWidget () const inline
Returns the widget that the mouse should be locked to (if any)
Definition at line 187 of file Reply.h.
References MouseLockWidget.
GetNavigationDestination()
TSharedPtr< SWidget > FReply::GetNavigationDestination () const inline
Get the widget that is the navigation destination.
Definition at line 208 of file Reply.h.
References NavigationDestination.
GetNavigationGenesis()
ENavigationGenesis FReply::GetNavigationGenesis () const inline
Get the genesis of the navigation.
Definition at line 202 of file Reply.h.
References NavigationGenesis.
GetNavigationSource()
ENavigationSource FReply::GetNavigationSource () const inline
Get the source of the navigation.
Definition at line 205 of file Reply.h.
References NavigationSource.
GetNavigationType()
EUINavigation FReply::GetNavigationType () const inline
Get the navigation type (Invalid if no navigation is requested).
Definition at line 199 of file Reply.h.
References NavigationType.
GetRequestedMousePos()
const TOptional< FIntPoint > & FReply::GetRequestedMousePos () const inline
Returns
The coordinates of the requested mouse position
Definition at line 223 of file Reply.h.
References RequestedMousePos.
GetUserFocusRecepient()
TSharedPtr< SWidget > FReply::GetUserFocusRecepient () const inline
When not nullptr, user focus has been requested to be set on the FocusRecipient.
Definition at line 190 of file Reply.h.
References FocusRecipient.
Handled()
FReply FReply::Handled () inline static
An event should return a FReply::Handled() to let the system know that an event was handled.
Definition at line 233 of file Reply.h.
References FReply().
Referenced by SBreadcrumbTrail< ItemType >::CrumbButtonClicked(), SHyperlink::Hyperlink_OnClicked(), FBlueprintEditor::NewDocument_OnClick(), SSkeletonSelectorWindow::OnAccept(), FBlueprintEditor::OnAddNewVariable_OnClick(), SGraphNode::OnAddPin(), SSkeletonSelectorWindow::OnCancel(), SSkinWeightProfileImportOptions::OnCancel(), FFindInBlueprintsNoResult::OnClick(), SBreadcrumbTrail< ItemType >::OnCrumbDelimiterClicked(), FArguments< ItemType >::OnDragDetected(), FArguments< ItemType >::OnDragOver(), SNumericEntryBox< NumericType >::OnFocusReceived(), SSkinWeightProfileImportOptions::OnImport(), SComboBox< OptionType >::OnKeyDown(), SListViewSelectorDropdownMenu< ListType >::OnKeyDown(), SNumericEntryBox< NumericType >::OnKeyDown(), STreeView< FRigVMSearchResult >::OnKeyDown(), SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), SComboBox< OptionType >::OnKeyDownHandler(), FArguments< ItemType >::OnMouseButtonDoubleClick(), SCommonButtonTableRow< ItemType >::OnMouseButtonDoubleClick(), FArguments< ItemType >::OnMouseButtonDown(), SListView< ItemType >::SListViewPinnedRowWidget::OnMouseButtonDown(), SListView< TSharedPtr< FString > >::OnMouseButtonDown(), FArguments< ItemType >::OnMouseButtonUp(), TSubSectionMixin< ParentSectionClass >::OnSectionDoubleClicked(), FArguments< ItemType >::OnTouchEnded(), and FArguments< ItemType >::OnTouchStarted().
LockMouseToWidget()
FReply & FReply::LockMouseToWidget (TSharedRef< SWidget > InWidget) inline
An event should return FReply::Handled().LockMouseToWidget(SomeWidget) as a means of asking the system to Lock the mouse so it cannot move out of the bounds of the widget.
Definition at line 93 of file Reply.h.
References FReply(), bShouldReleaseMouseLock, TReplyBase< FReply >::Me(), and MouseLockWidget.
PreventThrottling()
FReply & FReply::PreventThrottling () inline
Ensures throttling for Slate UI responsiveness is not done on mouse down.
Definition at line 157 of file Reply.h.
References FReply(), bPreventThrottling, and TReplyBase< FReply >::Me().
ReleaseMouseCapture()
FReply & FReply::ReleaseMouseCapture () inline
An event should return a FReply::Handled().ReleaseMouse() to ask the system to release mouse capture NOTE: Deactivates high precision mouse movement if activated.
Definition at line 114 of file Reply.h.
References FReply(), bReleaseMouseCapture, bUseHighPrecisionMouse, TReplyBase< FReply >::Me(), and MouseCaptor.
Referenced by FArguments< ItemType >::OnMouseButtonUp().
ReleaseMouseLock()
FReply & FReply::ReleaseMouseLock () inline
An event should return a FReply::Handled().ReleaseMouseLock() to ask the system to release mouse lock on a widget.
Definition at line 103 of file Reply.h.
References FReply(), bShouldReleaseMouseLock, TReplyBase< FReply >::Me(), and MouseLockWidget.
SetMousePos()
FReply & FReply::SetMousePos (const FIntPoint & NewMousePos)
An event should return FReply::Handled().SetMousePos to ask Slate to move the mouse cursor to a different location.
References FReply().
SetNavigation() [1/2]
FReply & FReply::SetNavigation (EUINavigation InNavigationType, const ENavigationGenesis InNavigationGenesis, const ENavigationSource InNavigationSource = ENavigationSource::FocusedWidget) inline
An event should return FReply::Handled().SetNavigation(NavigationType) as a means of asking the system to attempt a navigation.
Definition at line 70 of file Reply.h.
References FReply(), TReplyBase< FReply >::Me(), NavigationDestination, NavigationGenesis, NavigationSource, and NavigationType.
SetNavigation() [2/2]
FReply & FReply::SetNavigation (TSharedRef< SWidget > InNavigationDestination, const ENavigationGenesis InNavigationGenesis, const ENavigationSource InNavigationSource = ENavigationSource::FocusedWidget) inline
An event should return FReply::Handled().SetNavigation(NavigationDestination) as a means of asking the system to attempt a navigation to the specified destination.
Definition at line 80 of file Reply.h.
References FReply(), TReplyBase< FReply >::Me(), NavigationDestination, NavigationGenesis, NavigationSource, and NavigationType.
SetUserFocus()
FReply & FReply::SetUserFocus (TSharedRef< SWidget > GiveMeFocus, EFocusCause ReasonFocusIsChanging = EFocusCause::SetDirectly, bool bInAllUsers = false)
An event should return FReply::Handled().SetUserFocus(SomeWidget) as a means of asking the system to set users focus to the provided widget.
References FReply().
Referenced by SNumericEntryBox< NumericType >::OnFocusReceived(), SComboBox< OptionType >::OnKeyDown(), SListViewSelectorDropdownMenu< ListType >::OnKeyDown(), SNumericEntryBox< NumericType >::OnKeyDown(), FArguments< ItemType >::OnMouseButtonDown(), SCommonListView< ItemType >::OnTouchMoved(), SCommonTileView< ItemType >::OnTouchMoved(), and SCommonTreeView< ItemType >::OnTouchMoved().
ShouldEndDragDrop()
bool FReply::ShouldEndDragDrop () const inline
Returns
true if the user has asked us to terminate the ongoing drag/drop operation
Definition at line 214 of file Reply.h.
References bEndDragDrop.
ShouldReleaseMouse()
bool FReply::ShouldReleaseMouse () const inline
True if this reply indicated that we should release mouse capture as a result of the event being handled.
Definition at line 166 of file Reply.h.
References bReleaseMouseCapture.
Referenced by UE::Sequencer::FInputHandlerStack::ProcessReply().
ShouldReleaseMouseLock()
bool FReply::ShouldReleaseMouseLock () const inline
True if the reply indicated that we should release mouse lock.
Definition at line 181 of file Reply.h.
References bShouldReleaseMouseLock.
ShouldReleaseUserFocus()
bool FReply::ShouldReleaseUserFocus () const inline
true if this reply indicated that we should release focus as a result of the event being handled
Definition at line 172 of file Reply.h.
References bReleaseUserFocus.
ShouldSetUserFocus()
bool FReply::ShouldSetUserFocus () const inline
true if this reply indicated that we should set focus as a result of the event being handled
Definition at line 169 of file Reply.h.
References bSetUserFocus.
ShouldThrottle()
bool FReply::ShouldThrottle () const inline
Whether or not we should throttle on mouse down.
Definition at line 184 of file Reply.h.
References bPreventThrottling.
ShouldUseHighPrecisionMouse()
bool FReply::ShouldUseHighPrecisionMouse () const inline
True if this reply indicated that we should use high precision mouse movement.
Definition at line 178 of file Reply.h.
References bUseHighPrecisionMouse.
ToString()
FString FReply::ToString ()
Converts the reply into an string representation.
Unhandled()
FReply FReply::Unhandled () inline static
An event should return a FReply::Unhandled() to let the system know that an event was unhandled.
Definition at line 241 of file Reply.h.
References FReply().
Referenced by FRigVMTreePhase::Cancel(), FGraphEditorDragDropAction::DroppedOnAction(), FGraphEditorDragDropAction::DroppedOnCategory(), ISlateViewport::OnAnalogValueChanged(), SBreadcrumbTrail< ItemType >::OnCrumbDelimiterClicked(), FWidgetTemplate::OnDoubleClicked(), FArguments< ItemType >::OnDragDetected(), FArguments< ItemType >::OnDragOver(), FArguments< ItemType >::OnDrop(), ISlateViewport::OnFocusReceived(), ISlateViewport::OnKeyChar(), ISequencerSection::OnKeyDoubleClicked(), ICurveEditorToolExtension::OnKeyDown(), ISequencerInputHandler::OnKeyDown(), ISlateViewport::OnKeyDown(), SListViewSelectorDropdownMenu< ListType >::OnKeyDown(), SNumericEntryBox< NumericType >::OnKeyDown(), SSkinWeightProfileImportOptions::OnKeyDown(), UE::Sequencer::ISequencerEditTool::OnKeyDown(), SComboBox< OptionType >::OnKeyDownHandler(), ICurveEditorToolExtension::OnKeyUp(), ISequencerInputHandler::OnKeyUp(), ISlateViewport::OnKeyUp(), UE::Sequencer::ISequencerEditTool::OnKeyUp(), ISlateViewport::OnMotionDetected(), FArguments< ItemType >::OnMouseButtonDoubleClick(), ICurveEditorToolExtension::OnMouseButtonDoubleClick(), ISlateViewport::OnMouseButtonDoubleClick(), FArguments< ItemType >::OnMouseButtonDown(), ICurveEditorToolExtension::OnMouseButtonDown(), ISlateViewport::OnMouseButtonDown(), SListView< ItemType >::SListViewPinnedRowWidget::OnMouseButtonDown(), FArguments< ItemType >::OnMouseButtonUp(), ICurveEditorToolExtension::OnMouseButtonUp(), ISlateViewport::OnMouseButtonUp(), ICurveEditorToolExtension::OnMouseMove(), ISlateViewport::OnMouseMove(), ICurveEditorDragOperation::OnMouseWheel(), ISlateViewport::OnMouseWheel(), ISlateViewport::OnRequestWindowClose(), ISequencerSection::OnSectionDoubleClicked(), ISequencerSection::OnSectionDoubleClicked(), FArguments< ItemType >::OnTouchEnded(), ISlateViewport::OnTouchEnded(), ISlateViewport::OnTouchFirstMove(), ISlateViewport::OnTouchForceChanged(), ISlateViewport::OnTouchGesture(), ISlateViewport::OnTouchMoved(), ISlateViewport::OnTouchStarted(), ISlateViewport::OnViewportActivated(), FAssetEditorToolkit::OnViewportDrop(), FRigVMTreePhase::PrimaryAction(), UE::Sequencer::FInputHandlerStack::ProcessEvent(), UE::Sequencer::FInputHandlerStack::ProcessKeyEvent(), and USTRUCT().
UseHighPrecisionMouseMovement()
FReply & FReply::UseHighPrecisionMouseMovement (TSharedRef< SWidget > InMouseCaptor) inline
Enables the use of high precision (raw input) mouse movement, for more accurate mouse movement without mouse ballistics NOTE: This implies mouse capture and hidden mouse movement.
Releasing mouse capture deactivates this mode.
Definition at line 38 of file Reply.h.
References FReply(), bUseHighPrecisionMouse, TReplyBase< FReply >::Me(), and MouseCaptor.
Friends And Related Symbol Documentation
FSlateApplication
friend class FSlateApplication friend
Definition at line 277 of file Reply.h.
References FSlateApplication.
Referenced by FSlateApplication.
Field Documentation
bAllUsers
uint32 FReply::bAllUsers private
Definition at line 297 of file Reply.h.
Referenced by FReply(), and AffectsAllUsers().
bEndDragDrop
uint32 FReply::bEndDragDrop private
Definition at line 301 of file Reply.h.
Referenced by FReply(), EndDragDrop(), and ShouldEndDragDrop().
bPreventThrottling
uint32 FReply::bPreventThrottling private
Definition at line 300 of file Reply.h.
Referenced by FReply(), PreventThrottling(), and ShouldThrottle().
bReleaseMouseCapture
uint32 FReply::bReleaseMouseCapture private
Definition at line 294 of file Reply.h.
Referenced by FReply(), ReleaseMouseCapture(), and ShouldReleaseMouse().
bReleaseUserFocus
uint32 FReply::bReleaseUserFocus private
Definition at line 296 of file Reply.h.
Referenced by FReply(), and ShouldReleaseUserFocus().
bSetUserFocus
uint32 FReply::bSetUserFocus private
Definition at line 295 of file Reply.h.
Referenced by FReply(), and ShouldSetUserFocus().
bShouldReleaseMouseLock
uint32 FReply::bShouldReleaseMouseLock private
Definition at line 298 of file Reply.h.
Referenced by FReply(), LockMouseToWidget(), ReleaseMouseLock(), and ShouldReleaseMouseLock().
bUseHighPrecisionMouse
uint32 FReply::bUseHighPrecisionMouse private
Definition at line 299 of file Reply.h.
Referenced by FReply(), ReleaseMouseCapture(), ShouldUseHighPrecisionMouse(), and UseHighPrecisionMouseMovement().
DetectDragForMouseButton
FKey FReply::DetectDragForMouseButton private
Definition at line 288 of file Reply.h.
Referenced by DetectDrag(), and GetDetectDragRequestButton().
DetectDragForWidget
TWeakPtr<SWidget> FReply::DetectDragForWidget private
Definition at line 286 of file Reply.h.
Referenced by FReply(), DetectDrag(), and GetDetectDragRequest().
DragDropContent
TSharedPtr<FDragDropOperation> FReply::DragDropContent private
Definition at line 289 of file Reply.h.
Referenced by FReply(), BeginDragDrop(), and GetDragDropContent().
EventHandler
TWeakPtr<SWidget> FReply::EventHandler private
Definition at line 282 of file Reply.h.
Referenced by FReply().
FocusChangeReason
EFocusCause FReply::FocusChangeReason private
Definition at line 290 of file Reply.h.
Referenced by FReply(), and GetFocusCause().
FocusRecipient
TWeakPtr<SWidget> FReply::FocusRecipient private
Definition at line 284 of file Reply.h.
Referenced by FReply(), and GetUserFocusRecepient().
MouseCaptor
TWeakPtr<SWidget> FReply::MouseCaptor private
Definition at line 283 of file Reply.h.
Referenced by FReply(), CaptureMouse(), GetMouseCaptor(), ReleaseMouseCapture(), and UseHighPrecisionMouseMovement().
MouseLockWidget
TWeakPtr<SWidget> FReply::MouseLockWidget private
Definition at line 285 of file Reply.h.
Referenced by FReply(), GetMouseLockWidget(), LockMouseToWidget(), and ReleaseMouseLock().
NavigationDestination
TWeakPtr<SWidget> FReply::NavigationDestination private
Definition at line 287 of file Reply.h.
Referenced by FReply(), GetNavigationDestination(), SetNavigation(), and SetNavigation().
NavigationGenesis
ENavigationGenesis FReply::NavigationGenesis private
Definition at line 292 of file Reply.h.
Referenced by FReply(), GetNavigationGenesis(), SetNavigation(), and SetNavigation().
NavigationSource
ENavigationSource FReply::NavigationSource private
Definition at line 293 of file Reply.h.
Referenced by FReply(), GetNavigationSource(), SetNavigation(), and SetNavigation().
NavigationType
EUINavigation FReply::NavigationType private
Definition at line 291 of file Reply.h.
Referenced by FReply(), GetNavigationType(), SetNavigation(), and SetNavigation().
RequestedMousePos
TOptional<FIntPoint> FReply::RequestedMousePos private
Definition at line 281 of file Reply.h.
Referenced by FReply(), and GetRequestedMousePos().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/Reply.h