Unreal Engine 5.6 C++ API: UEnvQueryGenerator Class Reference
UEnvQueryGenerator Class Reference
#include "EnvQueryGenerator.h"
Private Member Functions
bool CanRunAsync () const
GENERATED_UCLASS_BODY () UPROPERTY() FString OptionName
virtual UPROPERTY() uint32 bAutoSortTests void GenerateItems (FEnvQueryInstance &QueryInstance) const
if set, tests will be automatically sorted for best performance before running query
virtual bool IsValidGenerator () const
virtual AIMODULE_API void PostLoad () override
AIMODULE_API void UpdateNodeVersion () override
UPROPERTY () TSubclassOf< UEnvQueryItemType > ItemType
type of generated items
Detailed Description
Definition at line 21 of file EnvQueryGenerator.h.
Member Function Documentation
CanRunAsync()
bool UEnvQueryGenerator::CanRunAsync () const inline private
Definition at line 38 of file EnvQueryGenerator.h.
GENERATED_UCLASS_BODY()
UEnvQueryGenerator::GENERATED_UCLASS_BODY () private
References Category, and UPROPERTY().
GenerateItems()
virtual UPROPERTY() uint32 bAutoSortTests void UEnvQueryGenerator::GenerateItems (FEnvQueryInstance & QueryInstance) const inline private virtual
if set, tests will be automatically sorted for best performance before running query
Reimplemented in UEnvQueryGenerator_ActorsOfClass, UEnvQueryGenerator_Composite, and UEnvQueryGenerator_PerceivedActors.
Definition at line 36 of file EnvQueryGenerator.h.
References checkNoEntry, and GenerateItems().
Referenced by GenerateItems().
IsValidGenerator()
virtual bool UEnvQueryGenerator::IsValidGenerator () const inline private virtual
Reimplemented in UEnvQueryGenerator_Composite.
Definition at line 37 of file EnvQueryGenerator.h.
PostLoad()
virtual AIMODULE_API void UEnvQueryGenerator::PostLoad () override private virtual
UpdateNodeVersion()
AIMODULE_API void UEnvQueryGenerator::UpdateNodeVersion () override private
References Category.
UPROPERTY()
UEnvQueryGenerator::UPROPERTY () private
type of generated items
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/EnvironmentQuery/EnvQueryGenerator.h