Unreal Engine 5.6 C++ API: UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade Class Reference
UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade Class Reference
Cloth outfit collection facade.
#include "CollectionOutfitFacade.h"
Data Structures
struct FRBFInterpolationDataWrapper
Public Member Functions
FCollectionOutfitConstFacade ()=delete
FCollectionOutfitConstFacade (const FCollectionOutfitConstFacade &)=delete
CHAOSOUTFITASSETENGINE_API FCollectionOutfitConstFacade (const FManagedArrayCollection &InManagedArrayCollection)
CHAOSOUTFITASSETENGINE_API FCollectionOutfitConstFacade (const TSharedRef< const FManagedArrayCollection > &InManagedArrayCollection)
FCollectionOutfitConstFacade (FCollectionOutfitConstFacade &&)=default
virtual CHAOSOUTFITASSETENGINE_API ~FCollectionOutfitConstFacade ()
CHAOSOUTFITASSETENGINE_API int32 FindBodySize (const FString &Name) const
Return the body size index for the specified name, or INDEX_NONE if it doesn't exist in this outfit.
CHAOSOUTFITASSETENGINE_API int32 FindClosestBodySize (const TMap< FString, float > &Measurements) const
Return the closest size to the specified measurements, or INDEX_NONE if this outfit has no sizes or the measurements are incomplete.
CHAOSOUTFITASSETENGINE_API int32 FindClosestBodySize (const USkeletalMesh &BodyPart) const
Return the closest size to the specified body, or INDEX_NONE if this outfit has no sizes or the body has no measurement data.
CHAOSOUTFITASSETENGINE_API int32 GetBodySizeBodyPartCount (const int32 BodySize) const
Return the body size body part count.
CHAOSOUTFITASSETENGINE_API int32 GetBodySizeBodyPartOffset (const int32 BodySize) const
Return the body size body part offset (to index into the global body part array).
CHAOSOUTFITASSETENGINE_API TConstArrayView< FString > GetBodySizeBodyPartsSkeletalMeshes (const int32 BodySize) const
Return the body part skeletal meshes path name for the specified body size.
CHAOSOUTFITASSETENGINE_API FRBFInterpolationDataWrapper GetBodySizeInterpolationData (const int32 BodySize) const
Return for the specified body size.
CHAOSOUTFITASSETENGINE_API TMap< FString, float > GetBodySizeMeasurements (const int32 BodySize) const
Return the body measurements stored for this specified body size.
CHAOSOUTFITASSETENGINE_API const FString & GetBodySizeName (const int32 BodySize) const
Return the specified body size name which is unique.
CHAOSOUTFITASSETENGINE_API int32 GetNumBodySizes () const
Return the number of body sizes.
CHAOSOUTFITASSETENGINE_API TArray< FString > GetOutfitBodyPartsSkeletalMeshes () const
Return all unique body part skeletal meshes used by this outfit.
CHAOSOUTFITASSETENGINE_API TArray< int32 > GetOutfitBodySizes (const FGuid &Guid) const
Return the body size available for the specified outfit GUID.
CHAOSOUTFITASSETENGINE_API TArray< FGuid > GetOutfitGuids () const
Return the sized outfits GUID, one per sized outfit which can contain different sized outfits.
CHAOSOUTFITASSETENGINE_API const FString & GetOutfitName (const FGuid &Guid, const int32 BodySize) const
Return the name of the original asset making up the specified outfit body size.
CHAOSOUTFITASSETENGINE_API TMap< FGuid, FString > GetOutfitPieces (const FGuid &Guid, const int32 BodySize) const
Return the outfit pieces making up the specified outfit body size.
CHAOSOUTFITASSETENGINE_API TConstArrayView< FGuid > GetOutfitPiecesGuids () const
Return all outfit pieces asset GUIDs.
bool HasBodySize (const FString &Name) const
Return whether this body size already exist.
CHAOSOUTFITASSETENGINE_API bool HasValidBodySize (bool bBodyPartMustExist=false, bool bMeasurementsMustExist=false, bool bInterpolationDataMustExist=false) const
Return whether this outfit has at least one valid body size.
CHAOSOUTFITASSETENGINE_API bool IsValid () const
Return whether the facade is defined on the collection.
FCollectionOutfitConstFacade & operator= (const FCollectionOutfitConstFacade &)=delete
FCollectionOutfitConstFacade & operator= (FCollectionOutfitConstFacade &&)=default
Protected Member Functions
const Private::FOutfitCollection * GetOutfitCollection () const
Protected Attributes
TSharedPtr< const FManagedArrayCollection > ManagedArrayCollection
TUniquePtr< const Private::FOutfitCollection > OutfitCollection
Detailed Description
Cloth outfit collection facade.
Const access (read only) version.
Definition at line 27 of file CollectionOutfitFacade.h.
Constructor & Destructor Documentation
FCollectionOutfitConstFacade() [1/5]
CHAOSOUTFITASSETENGINE_API UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade (const TSharedRef< const FManagedArrayCollection > & InManagedArrayCollection) explicit
References UE_API.
Referenced by FCollectionOutfitConstFacade(), FCollectionOutfitConstFacade(), UE::Chaos::OutfitAsset::FCollectionOutfitFacade::Append(), UE::Chaos::OutfitAsset::FCollectionOutfitFacade::Append(), operator=(), and operator=().
FCollectionOutfitConstFacade() [2/5]
CHAOSOUTFITASSETENGINE_API UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade (const FManagedArrayCollection & InManagedArrayCollection) explicit
References UE_API.
FCollectionOutfitConstFacade() [3/5]
UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade () delete
FCollectionOutfitConstFacade() [4/5]
UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade (const FCollectionOutfitConstFacade &) delete
References FCollectionOutfitConstFacade().
FCollectionOutfitConstFacade() [5/5]
UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FCollectionOutfitConstFacade (FCollectionOutfitConstFacade &&) default
References FCollectionOutfitConstFacade().
~FCollectionOutfitConstFacade()
virtual CHAOSOUTFITASSETENGINE_API UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::~FCollectionOutfitConstFacade () virtual
References UE_API.
Member Function Documentation
FindBodySize()
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FindBodySize (const FString & Name) const
Return the body size index for the specified name, or INDEX_NONE if it doesn't exist in this outfit.
References Name, and UE_API.
Referenced by UE::Chaos::OutfitAsset::FCollectionOutfitFacade::FindOrAddBodySize(), and HasBodySize().
FindClosestBodySize() [1/2]
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FindClosestBodySize (const TMap< FString, float > & Measurements) const
Return the closest size to the specified measurements, or INDEX_NONE if this outfit has no sizes or the measurements are incomplete.
References UE_API.
FindClosestBodySize() [2/2]
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::FindClosestBodySize (const USkeletalMesh & BodyPart) const
Return the closest size to the specified body, or INDEX_NONE if this outfit has no sizes or the body has no measurement data.
References UE_API.
GetBodySizeBodyPartCount()
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetBodySizeBodyPartCount (const int32 BodySize) const
Return the body size body part count.
Returns 0 if BodySize is invalid.
References UE_API.
GetBodySizeBodyPartOffset()
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetBodySizeBodyPartOffset (const int32 BodySize) const
Return the body size body part offset (to index into the global body part array).
Returns INDEX_NONE if BodySize is invalid.
References UE_API.
GetBodySizeBodyPartsSkeletalMeshes()
CHAOSOUTFITASSETENGINE_API TConstArrayView< FString > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetBodySizeBodyPartsSkeletalMeshes (const int32 BodySize) const
Return the body part skeletal meshes path name for the specified body size.
References UE_API.
GetBodySizeInterpolationData()
CHAOSOUTFITASSETENGINE_API FRBFInterpolationDataWrapper UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetBodySizeInterpolationData (const int32 BodySize) const
Return for the specified body size.
References UE_API.
GetBodySizeMeasurements()
CHAOSOUTFITASSETENGINE_API TMap< FString, float > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetBodySizeMeasurements (const int32 BodySize) const
Return the body measurements stored for this specified body size.
References UE_API.
GetBodySizeName()
CHAOSOUTFITASSETENGINE_API const FString & UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetBodySizeName (const int32 BodySize) const
Return the specified body size name which is unique.
References UE_API.
GetNumBodySizes()
CHAOSOUTFITASSETENGINE_API int32 UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetNumBodySizes () const
Return the number of body sizes.
References UE_API.
GetOutfitBodyPartsSkeletalMeshes()
CHAOSOUTFITASSETENGINE_API TArray< FString > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitBodyPartsSkeletalMeshes () const
Return all unique body part skeletal meshes used by this outfit.
References UE_API.
GetOutfitBodySizes()
CHAOSOUTFITASSETENGINE_API TArray< int32 > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitBodySizes (const FGuid & Guid) const
Return the body size available for the specified outfit GUID.
References Guid, and UE_API.
GetOutfitCollection()
const Private::FOutfitCollection * UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitCollection () const inline protected
Definition at line 109 of file CollectionOutfitFacade.h.
References OutfitCollection.
GetOutfitGuids()
CHAOSOUTFITASSETENGINE_API TArray< FGuid > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitGuids () const
Return the sized outfits GUID, one per sized outfit which can contain different sized outfits.
References UE_API.
GetOutfitName()
CHAOSOUTFITASSETENGINE_API const FString & UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitName (const FGuid & Guid, const int32 BodySize) const
Return the name of the original asset making up the specified outfit body size.
References Guid, and UE_API.
GetOutfitPieces()
CHAOSOUTFITASSETENGINE_API TMap< FGuid, FString > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitPieces (const FGuid & Guid, const int32 BodySize) const
Return the outfit pieces making up the specified outfit body size.
References Guid, and UE_API.
GetOutfitPiecesGuids()
CHAOSOUTFITASSETENGINE_API TConstArrayView< FGuid > UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::GetOutfitPiecesGuids () const
Return all outfit pieces asset GUIDs.
References UE_API.
HasBodySize()
bool UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::HasBodySize (const FString & Name) const inline
Return whether this body size already exist.
Definition at line 75 of file CollectionOutfitFacade.h.
References FindBodySize(), INDEX_NONE, and Name.
HasValidBodySize()
CHAOSOUTFITASSETENGINE_API bool UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::HasValidBodySize (bool bBodyPartMustExist = false, bool bMeasurementsMustExist = false, bool bInterpolationDataMustExist = false) const
Return whether this outfit has at least one valid body size.
Definition of valid depends on the passed arguments.
References UE_API.
IsValid()
CHAOSOUTFITASSETENGINE_API bool UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::IsValid () const
Return whether the facade is defined on the collection.
References UE_API.
operator=() [1/2]
FCollectionOutfitConstFacade & UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::operator= (const FCollectionOutfitConstFacade &) delete
References FCollectionOutfitConstFacade().
operator=() [2/2]
FCollectionOutfitConstFacade & UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::operator= (FCollectionOutfitConstFacade &&) default
References FCollectionOutfitConstFacade().
Field Documentation
ManagedArrayCollection
TSharedPtr<const FManagedArrayCollection> UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::ManagedArrayCollection protected
Definition at line 112 of file CollectionOutfitFacade.h.
OutfitCollection
TUniquePtr<const Private::FOutfitCollection> UE::Chaos::OutfitAsset::FCollectionOutfitConstFacade::OutfitCollection protected
Definition at line 111 of file CollectionOutfitFacade.h.
Referenced by GetOutfitCollection(), and UE::Chaos::OutfitAsset::FCollectionOutfitFacade::GetOutfitCollection().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosOutfitAsset/Source/ChaosOutfitAssetEngine/Public/ChaosOutfitAsset/CollectionOutfitFacade.h