Unreal Engine 5.6 C++ API: UE::Geometry::TIntrSegment2Segment2< RealType > Class Template Reference
UE::Geometry::TIntrSegment2Segment2< RealType > Class Template Reference
Calculate intersection between two 2D line segments.
#include "IntrSegment2Segment2.h"
Public Member Functions
TIntrSegment2Segment2 (const TSegment2< RealType > &Segment1In, const TSegment2< RealType > &Segment2In)
TIntrSegment2Segment2 & Compute ()
bool Find ()
RealType GetDotThreshold () const
RealType GetIntervalThreshold () const
const TSegment2< RealType > & GetSegment1 () const
const TSegment2< RealType > & GetSegment2 () const
bool IsSimpleIntersection () const
void SetDotThreshold (RealType Value)
void SetIntervalThreshold (RealType Value)
void SetSegment1 (const TSegment2< RealType > &Value)
void SetSegment2 (const TSegment2< RealType > &Value)
Data Fields
RealType Parameter0
RealType Parameter1
TVector2< RealType > Point0
TVector2< RealType > Point1
int Quantity = 0
EIntersectionResult Result = EIntersectionResult::NotComputed
EIntersectionType Type = EIntersectionType::Empty
Protected Member Functions
void SanityCheck ()
Protected Attributes
RealType DotThreshold = TMathUtil<RealType>::ZeroTolerance
RealType IntervalThreshold = 0
TSegment2< RealType > Segment1
TSegment2< RealType > Segment2
Detailed Description
template<typename RealType>
class UE::Geometry::TIntrSegment2Segment2< RealType >
Calculate intersection between two 2D line segments.
Definition at line 56 of file IntrSegment2Segment2.h.
Constructor & Destructor Documentation
TIntrSegment2Segment2()
template<typename RealType> UE::Geometry::TIntrSegment2Segment2< RealType >::TIntrSegment2Segment2 (const TSegment2< RealType > & Segment1In, const TSegment2< RealType > & Segment2In) inline
Definition at line 79 of file IntrSegment2Segment2.h.
Member Function Documentation
Compute()
template<typename RealType> TIntrSegment2Segment2 & UE::Geometry::TIntrSegment2Segment2< RealType >::Compute () inline
Definition at line 135 of file IntrSegment2Segment2.h.
Find()
template<typename RealType> bool UE::Geometry::TIntrSegment2Segment2< RealType >::Find () inline
Definition at line 145 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::TIntrSegment2Segment2< double >::Compute(), UE::Geometry::FArrangement2d::find_intersecting_edges(), and UE::Geometry::TPolygon2< double >::FindIntersections().
GetDotThreshold()
template<typename RealType> RealType UE::Geometry::TIntrSegment2Segment2< RealType >::GetDotThreshold () const inline
Definition at line 118 of file IntrSegment2Segment2.h.
GetIntervalThreshold()
template<typename RealType> RealType UE::Geometry::TIntrSegment2Segment2< RealType >::GetIntervalThreshold () const inline
Definition at line 107 of file IntrSegment2Segment2.h.
GetSegment1()
template<typename RealType> const TSegment2< RealType > & UE::Geometry::TIntrSegment2Segment2< RealType >::GetSegment1 () const inline
Definition at line 85 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::FArrangement2d::insert_segment().
GetSegment2()
template<typename RealType> const TSegment2< RealType > & UE::Geometry::TIntrSegment2Segment2< RealType >::GetSegment2 () const inline
Definition at line 96 of file IntrSegment2Segment2.h.
IsSimpleIntersection()
template<typename RealType> bool UE::Geometry::TIntrSegment2Segment2< RealType >::IsSimpleIntersection () const inline
Definition at line 129 of file IntrSegment2Segment2.h.
SanityCheck()
template<typename RealType> void UE::Geometry::TIntrSegment2Segment2< RealType >::SanityCheck () inline protected
Definition at line 282 of file IntrSegment2Segment2.h.
SetDotThreshold()
template<typename RealType> void UE::Geometry::TIntrSegment2Segment2< RealType >::SetDotThreshold (RealType Value) inline
Definition at line 123 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::FArrangement2d::find_intersecting_edges().
SetIntervalThreshold()
template<typename RealType> void UE::Geometry::TIntrSegment2Segment2< RealType >::SetIntervalThreshold (RealType Value) inline
Definition at line 112 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::FArrangement2d::find_intersecting_edges().
SetSegment1()
template<typename RealType> void UE::Geometry::TIntrSegment2Segment2< RealType >::SetSegment1 (const TSegment2< RealType > & Value) inline
Definition at line 90 of file IntrSegment2Segment2.h.
SetSegment2()
template<typename RealType> void UE::Geometry::TIntrSegment2Segment2< RealType >::SetSegment2 (const TSegment2< RealType > & Value) inline
Definition at line 101 of file IntrSegment2Segment2.h.
Field Documentation
DotThreshold
template<typename RealType> RealType UE::Geometry::TIntrSegment2Segment2< RealType >::DotThreshold = TMathUtil<RealType>::ZeroTolerance protected
Definition at line 63 of file IntrSegment2Segment2.h.
IntervalThreshold
template<typename RealType> RealType UE::Geometry::TIntrSegment2Segment2< RealType >::IntervalThreshold = 0 protected
Definition at line 62 of file IntrSegment2Segment2.h.
Parameter0
template<typename RealType> RealType UE::Geometry::TIntrSegment2Segment2< RealType >::Parameter0
Definition at line 74 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::FArrangement2d::insert_segment().
Parameter1
template<typename RealType> RealType UE::Geometry::TIntrSegment2Segment2< RealType >::Parameter1
Definition at line 75 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::FArrangement2d::insert_segment().
Point0
template<typename RealType> TVector2<RealType> UE::Geometry::TIntrSegment2Segment2< RealType >::Point0
Definition at line 71 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::TPolygon2< double >::FindIntersections().
Point1
template<typename RealType> TVector2<RealType> UE::Geometry::TIntrSegment2Segment2< RealType >::Point1
Definition at line 72 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::TPolygon2< double >::FindIntersections().
Quantity
template<typename RealType> int UE::Geometry::TIntrSegment2Segment2< RealType >::Quantity = 0
Definition at line 67 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::TPolygon2< double >::FindIntersections().
Result
template<typename RealType> EIntersectionResult UE::Geometry::TIntrSegment2Segment2< RealType >::Result = EIntersectionResult::NotComputed
Definition at line 68 of file IntrSegment2Segment2.h.
Segment1
template<typename RealType> TSegment2<RealType> UE::Geometry::TIntrSegment2Segment2< RealType >::Segment1 protected
Definition at line 60 of file IntrSegment2Segment2.h.
Segment2
template<typename RealType> TSegment2<RealType> UE::Geometry::TIntrSegment2Segment2< RealType >::Segment2 protected
Definition at line 61 of file IntrSegment2Segment2.h.
Type
template<typename RealType> EIntersectionType UE::Geometry::TIntrSegment2Segment2< RealType >::Type = EIntersectionType::Empty
Definition at line 69 of file IntrSegment2Segment2.h.
Referenced by UE::Geometry::FArrangement2d::insert_segment().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Intersection/IntrSegment2Segment2.h