Unreal Engine 5.6 C++ API: TTypeContainer< Mode > Class Template Reference
TTypeContainer< Mode > Class Template Reference
Template for type containers.
#include "TypeContainer.h"
Data Structures
struct FThreadInstanceProvider
Base class for per-thread instances providers.
class IInstanceProvider
Interface for object instance providers.
struct TFunctionInstanceProvider
Implements an instance provider that forwards instance requests to a factory function.
struct TSharedInstanceProvider
Implements an instance provider that returns the same instance for all threads.
struct TThreadInstanceProvider
Implements an instance provider that returns the same instance per thread.
Public Member Functions
template<class R>
TSharedRef< R, Mode > GetInstance () const
Gets a shared pointer to an instance of the specified class.
template<class R>
TSharedRef< R, Mode > GetInstanceRef () const
Gets a shared reference to an instance of the specified class.
template<class R>
bool IsRegistered () const
Check whether the specified class has been registered.
template<class R, class T, typename... P>
void RegisterClass (ETypeContainerScope Scope=ETypeContainerScope::Process)
Registers a class for instances of the specified class.
template<class R, class D, typename... P>
void RegisterDelegate (D Delegate)
Register a factory delegate for the specified class.
template<class R>
void RegisterFactory (const TFunction< TSharedRef< R, Mode >()> &CreateFunc)
Register a factory function for the specified class.
template<class R, typename P0, typename... P>
void RegisterFactory (const TFunction< TSharedRef< R, Mode >(TSharedRef< P0, Mode >, TSharedRef< P, Mode >...)> &CreateFunc)
Register a factory function for the specified class.
template<class R, class T>
void RegisterInstance (const TSharedRef< T, Mode > &Instance)
Registers an existing instance for the specified class.
template<class R>
void Unregister ()
Unregisters the instance or class for a previously registered class.
Protected Member Functions
void AddProvider (const TCHAR *Name, const TSharedPtr< IInstanceProvider > &Provider)
Add an instance provider to the container.
Private Attributes
FCriticalSection CriticalSection
Critical section for synchronizing access.
TMap< FString, TSharedPtr< IInstanceProvider > > Providers
Maps class names to instance providers.
Detailed Description
template<ESPMode Mode = ESPMode::ThreadSafe>
class TTypeContainer< Mode >
Template for type containers.
Type containers allow for configuring objects and their dependencies without actually creating these objects. They fulfill a role similar to class factories, but without being locked to a particular type of class. When passed into class constructors or methods, type containers can facilitate the Inversion of Control (IoC) pattern.
Since UE neither uses run-time type information nor pre-processes plain old C++ classes, type names need to be exposed using the Expose_TNameOf macro in order to make them registrable with type containers, i.e. Expose_TNameOf(FMyClass).
Once a type is registered with a container, instances of that type can be retrieved from it. There are currently three life time scopes available for instance creation:
Unique instance per process (aka. singleton), using RegisterClass(ETypeContainerScope::Process) or RegisterInstance()
Unique instance per thread (aka. thread singleton), using RegisterClass(ETypeContainerScope::Thread)
Unique instance per call (aka. class factory), using RegisterClass(ETypeContainerScope::Instance) or RegisterFactory()
See the file TypeContainerTest.cpp for detailed examples on how to use each of these type registration methods.
In the interest of fast performance, the object pointers returned by type containers are not thread-safe by default. If you intend to use the same type container and share its objects from different threads, use TTypeContainer<ESPMode::ThreadSafe> instead, which will then manage and return thread-safe versions of all object pointers.
Note: Type containers depend on variadic templates and are therefore not available on XboxOne at this time, which means they should only be used for desktop applications.
Definition at line 66 of file TypeContainer.h.
Member Function Documentation
AddProvider()
template<ESPMode Mode = ESPMode::ThreadSafe> void TTypeContainer< Mode >::AddProvider (const TCHAR * Name, const TSharedPtr< IInstanceProvider > & Provider) inline protected
Add an instance provider to the container.
Parameters
Name The name of the type to add the provider for.
Provider The instance provider.
Definition at line 407 of file TypeContainer.h.
References CriticalSection, Name, and Providers.
Referenced by RegisterClass(), RegisterDelegate(), RegisterFactory(), RegisterFactory(), and RegisterInstance().
GetInstance()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R> TSharedRef< R, Mode > TTypeContainer< Mode >::GetInstance () const inline
Gets a shared pointer to an instance of the specified class.
Parameters
R The type of class to get an instance for.
A shared reference to the instance.
See also
RegisterClass, RegisterDelegate, RegisterFactory, RegisterInstance
Definition at line 181 of file TypeContainer.h.
References check, CriticalSection, TNameOf< T >::GetName(), TSharedPtr< ObjectType, InMode >::IsValid(), Providers, and StaticCastSharedPtr().
Referenced by GetInstanceRef(), RegisterClass(), RegisterDelegate(), and RegisterFactory().
GetInstanceRef()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R> TSharedRef< R, Mode > TTypeContainer< Mode >::GetInstanceRef () const inline
Gets a shared reference to an instance of the specified class.
Unlike GetInstance(), this function will assert if no instance was registered for the requested type of class using either RegisterClass() or RegisterInstance().
Parameters
R The type of class that an instance is being requested for.
A shared pointer to the instance.
See also
GetInstance, RegisterClass, RegisterInstance
Definition at line 203 of file TypeContainer.h.
References GetInstance().
IsRegistered()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R> bool TTypeContainer< Mode >::IsRegistered () const inline
Check whether the specified class has been registered.
Parameters
R The type of registered class to check.
Returns
true if the class was registered, false otherwise.
Definition at line 215 of file TypeContainer.h.
References CriticalSection, TNameOf< T >::GetName(), and Providers.
RegisterClass()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R, class T, typename... P> void TTypeContainer< Mode >::RegisterClass (ETypeContainerScope Scope = ETypeContainerScope::Process) inline
Registers a class for instances of the specified class.
Parameters
R The type of class to register an instance class for.
T Tye type of class to register (must be the same as or derived from R).
P The constructor parameters that the class requires.
Scope The scope at which instances must be unique (default = Process).
See also
RegisterDelegate, RegisterInstance, Unregister
Definition at line 233 of file TypeContainer.h.
References AddProvider(), GetInstance(), TNameOf< T >::GetName(), Instance, MakeShareable(), Process, Thread, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
RegisterDelegate()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R, class D, typename... P> void TTypeContainer< Mode >::RegisterDelegate (D Delegate) inline
Register a factory delegate for the specified class.
Parameters
R The type of class to register an instance class for.
D Tye type of factory delegate to register.
P The parameters that the delegate requires.
Delegate The delegate to register.
Definition at line 282 of file TypeContainer.h.
References AddProvider(), GetInstance(), TNameOf< T >::GetName(), and MakeShareable().
RegisterFactory() [1/2]
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R> void TTypeContainer< Mode >::RegisterFactory (const TFunction< TSharedRef< R, Mode >()> & CreateFunc) inline
Register a factory function for the specified class.
Parameters
R The type of class to register the instance for.
P Additional parameters that the factory function requires.
CreateFunc The factory function that will create instances.
See also
RegisterClass, RegisterInstance, Unregister
Definition at line 306 of file TypeContainer.h.
References AddProvider(), TNameOf< T >::GetName(), and MakeShareable().
RegisterFactory() [2/2]
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R, typename P0, typename... P> void TTypeContainer< Mode >::RegisterFactory (const TFunction< TSharedRef< R, Mode >(TSharedRef< P0, Mode >, TSharedRef< P, Mode >...)> & CreateFunc) inline
Register a factory function for the specified class.
Parameters
R The type of class to register the instance for.
P0 The first parameter that the factory function requires.
P Additional parameters that the factory function requires.
CreateFunc The factory function that will create instances.
See also
RegisterClass, RegisterInstance, Unregister
Definition at line 329 of file TypeContainer.h.
References AddProvider(), GetInstance(), TNameOf< T >::GetName(), and MakeShareable().
RegisterInstance()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R, class T> void TTypeContainer< Mode >::RegisterInstance (const TSharedRef< T, Mode > & Instance) inline
Registers an existing instance for the specified class.
Parameters
R The type of class to register the instance for.
T The type of the instance to register (must be the same as or derived from R).
Instance The instance of the class to register.
See also
RegisterClass, RegisterDelegate, Unregister
Definition at line 377 of file TypeContainer.h.
References AddProvider(), TNameOf< T >::GetName(), Instance, MakeShareable(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
Unregister()
template<ESPMode Mode = ESPMode::ThreadSafe> template<class R> void TTypeContainer< Mode >::Unregister () inline
Unregisters the instance or class for a previously registered class.
Parameters
R The type of class to unregister.
See also
RegisterClass, RegisterDelegate, RegisterInstance
Definition at line 391 of file TypeContainer.h.
References CriticalSection, TNameOf< T >::GetName(), and Providers.
Field Documentation
CriticalSection
template<ESPMode Mode = ESPMode::ThreadSafe> FCriticalSection TTypeContainer< Mode >::CriticalSection mutable private
Critical section for synchronizing access.
Definition at line 418 of file TypeContainer.h.
Referenced by AddProvider(), GetInstance(), IsRegistered(), and Unregister().
Providers
template<ESPMode Mode = ESPMode::ThreadSafe> TMap<FString, TSharedPtr<IInstanceProvider> > TTypeContainer< Mode >::Providers private
Maps class names to instance providers.
Definition at line 421 of file TypeContainer.h.
Referenced by AddProvider(), GetInstance(), IsRegistered(), and Unregister().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/TypeContainer.h