Unreal Engine 5.6 C++ API: TFixedTickReplicator_AP< InModelDef > Class Template Reference
TFixedTickReplicator_AP< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using ModelDef = InModelDef
Static Public Member Functions
static void NetRecv (const FNetSerializeParams &P, TClientRecvData< ModelDef > &ClientRecvState, TModelDataStore< ModelDef > *DataStore, FFixedTickState *TickState)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, const FFixedTickState *TickState)
Detailed Description
template<typename InModelDef>
class TFixedTickReplicator_AP< InModelDef >
Definition at line 387 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
ModelDef
template<typename InModelDef> using TFixedTickReplicator_AP< InModelDef >::ModelDef = InModelDef
Definition at line 391 of file NetworkPredictionSerialization.h.
Member Function Documentation
NetRecv()
template<typename InModelDef> void TFixedTickReplicator_AP< InModelDef >::NetRecv (const FNetSerializeParams & P, TClientRecvData< ModelDef > & ClientRecvState, TModelDataStore< ModelDef > * DataStore, FFixedTickState * TickState) inline static
Definition at line 396 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, FFixedTickState::ConfirmedFrame, TInstanceData< ModelDef >::CueDispatcher, FFixedTickState::FixedStepMS, INDEX_NONE, TClientRecvData< ModelDef >::InstanceIdx, TModelDataStore< ModelDef >::Instances, FFixedTickState::Interpolation, FFixedTickState::FInterpolationState::LatestRecvFrameAP, TCommonReplicator_AP< ModelDef >::NetRecv(), npEnsure, npEnsureSlow, FFixedTickState::Offset, FFixedTickState::PendingFrame, FNetworkPredictionSerialization::ReadCompressedFrame(), TClientRecvData< ModelDef >::ServerFrame, and UE_NP_TRACE_NET_RECV.
NetSend()
template<typename InModelDef> void TFixedTickReplicator_AP< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, const FFixedTickState * TickState) inline static
Definition at line 449 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, AutoProxy, TInstanceFrameState< ModelDef >::Buffer, TModelDataStore< ModelDef >::Frames, ID, INDEX_NONE, Instance, TModelDataStore< ModelDef >::Instances, TServerRecvData_Fixed< ModelDef >::LastConsumedFrame, TCommonReplicator_AP< ModelDef >::NetSend(), npCheckSlow, npEnsureSlow, FFixedTickState::PendingFrame, TModelDataStore< ModelDef >::ServerRecv, and FNetworkPredictionSerialization::WriteCompressedFrame().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionSerialization.h