Unreal Engine 5.6 C++ API: FSeparatingAxisPointCheck Class Reference
FSeparatingAxisPointCheck Class Reference
#include "Collision.h"
Public Member Functions
FSeparatingAxisPointCheck (const TArray< FVector > &InPolyVertices, const FVector &InBoxCenter, const FVector &InBoxExtent, bool bInCalcLeastPenetration=true)
Creates an object representing the intersection between an axis-aligned bounding box and a convex polygon.
Data Fields
float BestDist
The amount that the bounding box is penetrating the axis defined by HitNormal.
bool bHit
Whether the bounding box intersects with the polygon.
FVector HitNormal
The normal of the separating axis that the bounding box is penetrating the least.
Private Member Functions
bool FindSeparatingAxisGeneric ()
Determines whether the bounding box encroaches on the convex polygon, checking all relevant axes.
bool FindSeparatingAxisTriangle ()
Determines whether the bounding box encroaches on the triangle, checking all relevant axes.
bool TestSeparatingAxisCommon (const FVector &Axis, float ProjectedPolyMin, float ProjectedPolyMax)
Given a separating axis, and a minimum and maximum point projected onto it, determines whether the bounding box encroaches on the polygon along that axis, according to the separating axis theorem.
bool TestSeparatingAxisGeneric (const FVector &Axis)
Determines whether the bounding box encroaches on the convex polygon along the given axis.
bool TestSeparatingAxisTriangle (const FVector &Axis)
Determines whether the bounding box encroaches on the triangle along the given axis.
Private Attributes
bool bCalcLeastPenetration
Flag specifying whether the least penetration should be calculated.
FVector BoxCenter
Center of the axis-aligned bounding box being checked.
FVector BoxExtent
Extents of the axis-aligned bounding box being checked.
const TArray< FVector > & PolyVertices
Array of vertices defining the convex polygon being checked.
Detailed Description
Definition at line 53 of file Collision.h.
Constructor & Destructor Documentation
FSeparatingAxisPointCheck()
FSeparatingAxisPointCheck::FSeparatingAxisPointCheck (const TArray< FVector > & InPolyVertices, const FVector & InBoxCenter, const FVector & InBoxExtent, bool bInCalcLeastPenetration = true) inline
Creates an object representing the intersection between an axis-aligned bounding box and a convex polygon.
Parameters
InPolyVertices Array of points forming a convex polygon.
InBoxCenter The center of the axis-aligned bounding box being checked.
InBoxExtent The extents of the axis-aligned bounding box being checked.
bInCalcLeastPenetration Whether the axis and amount of penetration of the bounding box into the polygon should be calculated.
Definition at line 73 of file Collision.h.
References bCalcLeastPenetration, BestDist, bHit, BoxCenter, BoxExtent, FindSeparatingAxisGeneric(), FindSeparatingAxisTriangle(), float, FVector, HitNormal, Max, and PolyVertices.
Member Function Documentation
FindSeparatingAxisGeneric()
bool FSeparatingAxisPointCheck::FindSeparatingAxisGeneric () private
Determines whether the bounding box encroaches on the convex polygon, checking all relevant axes.
Returns
True if the bounding box encroaches on the convex polygon.
Referenced by FSeparatingAxisPointCheck().
FindSeparatingAxisTriangle()
bool FSeparatingAxisPointCheck::FindSeparatingAxisTriangle () private
Determines whether the bounding box encroaches on the triangle, checking all relevant axes.
Returns
True if the bounding box encroaches on the triangle.
Referenced by FSeparatingAxisPointCheck().
TestSeparatingAxisCommon()
bool FSeparatingAxisPointCheck::TestSeparatingAxisCommon (const FVector & Axis, float ProjectedPolyMin, float ProjectedPolyMax) private
Given a separating axis, and a minimum and maximum point projected onto it, determines whether the bounding box encroaches on the polygon along that axis, according to the separating axis theorem.
Optionally sets the HitNormal and BestDist members according to the least penetration of the bounding box into the polygon.
Parameters
Axis The separating axis.
ProjectedPolyMin The minimum polygon point, projected onto the separating axis.
ProjectedPolyMax The maximum polygon point, projected onto the separating axis.
References Axis, and FVector.
TestSeparatingAxisGeneric()
bool FSeparatingAxisPointCheck::TestSeparatingAxisGeneric (const FVector & Axis) private
Determines whether the bounding box encroaches on the convex polygon along the given axis.
Parameters
Axis The separating axis.
Returns
True if the bounding box encroaches on the triangle along the given axis.
References Axis, and FVector.
TestSeparatingAxisTriangle()
bool FSeparatingAxisPointCheck::TestSeparatingAxisTriangle (const FVector & Axis) private
Determines whether the bounding box encroaches on the triangle along the given axis.
Parameters
Axis The separating axis.
Returns
True if the bounding box encroaches on the triangle along the given axis.
References Axis, and FVector.
Field Documentation
bCalcLeastPenetration
bool FSeparatingAxisPointCheck::bCalcLeastPenetration private
Flag specifying whether the least penetration should be calculated.
Definition at line 145 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
BestDist
float FSeparatingAxisPointCheck::BestDist
The amount that the bounding box is penetrating the axis defined by HitNormal.
Definition at line 60 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
bHit
bool FSeparatingAxisPointCheck::bHit
Whether the bounding box intersects with the polygon.
Definition at line 63 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
BoxCenter
FVector FSeparatingAxisPointCheck::BoxCenter private
Center of the axis-aligned bounding box being checked.
Definition at line 139 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
BoxExtent
FVector FSeparatingAxisPointCheck::BoxExtent private
Extents of the axis-aligned bounding box being checked.
Definition at line 142 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
HitNormal
FVector FSeparatingAxisPointCheck::HitNormal
The normal of the separating axis that the bounding box is penetrating the least.
Definition at line 57 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
PolyVertices
const TArray<FVector>& FSeparatingAxisPointCheck::PolyVertices private
Array of vertices defining the convex polygon being checked.
Definition at line 136 of file Collision.h.
Referenced by FSeparatingAxisPointCheck().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Collision.h