Unreal Engine 5.6 C++ API: UE::Insights::FFilterState Class Reference
UE::Insights::FFilterState Class Reference
#include "Filters.h"
Public Member Functions
FFilterState (TSharedRef< FFilter > InFilter)
virtual ~FFilterState ()
virtual void AddCustomUI (TSharedRef< SHorizontalBox > LeftBox)
virtual bool ApplyFilter (const FFilterContext &Context) const
template<typename Type>
Type & As ()
template<typename Type>
const Type & As () const
virtual TSharedRef< FFilterState > DeepCopy () const
virtual bool Equals (const FFilterState &Other) const
TSharedPtr< const IFilterOperator > GetSelectedOperator () const
virtual const FName & GetTypeName () const
virtual bool HasCustomUI () const
template<typename Type>
bool Is () const
virtual bool IsKindOf (const FName &InTypeName) const
virtual void SetFilterValue (FString InTextValue)
void SetSelectedOperator (TSharedPtr< IFilterOperator > InOperator)
virtual void Update ()
Static Public Member Functions
static const FName & GetStaticTypeName ()
Protected Attributes
TSharedRef< FFilter > Filter
FFilterContext::ContextData FilterValue
TSharedPtr< IFilterOperator > SelectedOperator
Static Private Attributes
static const FName TypeName
Detailed Description
Definition at line 200 of file Filters.h.
Constructor & Destructor Documentation
FFilterState()
UE::Insights::FFilterState::FFilterState (TSharedRef< FFilter > InFilter) inline
Definition at line 205 of file Filters.h.
References Filter.
Referenced by As(), and Equals().
~FFilterState()
virtual UE::Insights::FFilterState::~FFilterState () inline virtual
Definition at line 210 of file Filters.h.
Member Function Documentation
AddCustomUI()
virtual void UE::Insights::FFilterState::AddCustomUI (TSharedRef< SHorizontalBox > LeftBox) inline virtual
Definition at line 221 of file Filters.h.
ApplyFilter()
virtual bool UE::Insights::FFilterState::ApplyFilter (const FFilterContext & Context) const virtual
As() [1/2]
template<typename Type> Type & UE::Insights::FFilterState::As () inline
Definition at line 202 of file Filters.h.
As() [2/2]
template<typename Type> const Type & UE::Insights::FFilterState::As () const inline
Definition at line 202 of file Filters.h.
References FFilterState().
DeepCopy()
virtual TSharedRef< FFilterState > UE::Insights::FFilterState::DeepCopy () const virtual
Equals()
virtual bool UE::Insights::FFilterState::Equals (const FFilterState & Other) const virtual
References FFilterState(), and Other.
GetSelectedOperator()
TSharedPtr< const IFilterOperator > UE::Insights::FFilterState::GetSelectedOperator () const inline
Definition at line 213 of file Filters.h.
References SelectedOperator.
GetStaticTypeName()
const FName & UE::Insights::FFilterState::GetStaticTypeName () inline static
Definition at line 202 of file Filters.h.
GetTypeName()
virtual const FName & UE::Insights::FFilterState::GetTypeName () const inline virtual
Definition at line 202 of file Filters.h.
HasCustomUI()
virtual bool UE::Insights::FFilterState::HasCustomUI () const inline virtual
Definition at line 220 of file Filters.h.
Is()
template<typename Type> bool UE::Insights::FFilterState::Is () const inline
Definition at line 202 of file Filters.h.
IsKindOf()
virtual bool UE::Insights::FFilterState::IsKindOf (const FName & InTypeName) const inline virtual
Definition at line 202 of file Filters.h.
SetFilterValue()
virtual void UE::Insights::FFilterState::SetFilterValue (FString InTextValue) virtual
SetSelectedOperator()
void UE::Insights::FFilterState::SetSelectedOperator (TSharedPtr< IFilterOperator > InOperator) inline
Definition at line 212 of file Filters.h.
References SelectedOperator.
Update()
virtual void UE::Insights::FFilterState::Update () inline virtual
Definition at line 215 of file Filters.h.
Field Documentation
Filter
TSharedRef<FFilter> UE::Insights::FFilterState::Filter protected
Definition at line 227 of file Filters.h.
Referenced by FFilterState().
FilterValue
FFilterContext::ContextData UE::Insights::FFilterState::FilterValue protected
Definition at line 229 of file Filters.h.
SelectedOperator
TSharedPtr<IFilterOperator> UE::Insights::FFilterState::SelectedOperator protected
Definition at line 228 of file Filters.h.
Referenced by GetSelectedOperator(), and SetSelectedOperator().
TypeName
const FName UE::Insights::FFilterState::TypeName static private
Definition at line 202 of file Filters.h.
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Filter/ViewModels/Filters.h