Unreal Engine 5.6 C++ API: TraceServices::IAnalysisSession Class Reference
TraceServices::IAnalysisSession Class Reference abstract
#include "AnalysisSession.h"
Public Member Functions
virtual ~IAnalysisSession ()=default
virtual void AddAnalyzer (TSharedRef< UE::Trace::IAnalyzer > Analyzer)=0
virtual void AddAnalyzer (UE::Trace::IAnalyzer *Analyzer)=0
virtual void AddMetadata (FName InName, double InValue)=0
virtual void AddMetadata (FName InName, FString InValue)=0
virtual void AddMetadata (FName InName, int64 InValue)=0
virtual void AddProvider (const FName &Name, TSharedPtr< IProvider > Provider, TSharedPtr< IEditableProvider > EditableProvider=nullptr)=0
virtual void BeginEdit ()=0
virtual void BeginRead () const =0
virtual TArray< FAnalysisMessage > DrainPendingMessages ()=0
Moves pending messages to the return array.
template<typename ProviderType>
ProviderType * EditProvider (const FName &Name)
virtual void EndEdit ()=0
virtual void EndRead () const =0
virtual void EnumerateMetadata (TFunctionRef< void(const FTraceSessionMetadata &Metadata)> Callback) const =0
virtual IAnalysisCache & GetCache ()=0
virtual double GetDurationSeconds () const =0
virtual ILinearAllocator & GetLinearAllocator ()=0
virtual uint32 GetMetadataCount () const =0
virtual const TCHAR * GetName () const =0
virtual uint32 GetNumPendingMessages () const =0
Get the number of pending messages.
virtual IStringStore & GetStringStore ()=0
virtual uint32 GetTraceId () const =0
virtual bool IsAnalysisComplete () const =0
virtual void ReadAccessCheck () const =0
template<typename ProviderType>
const ProviderType * ReadProvider (const FName &Name) const
virtual void Stop (bool bAndWait=false) const =0
virtual const TCHAR * StoreString (const FStringView &String)=0
virtual const TCHAR * StoreString (const TCHAR *String)=0
UE_DEPRECATED (5.3, "No longer used.") virtual FMessageLog *GetLog() const =0
virtual void UpdateDurationSeconds (double Duration)=0
Update the internal estimation of the session duration with a new timestamp.
virtual void Wait () const =0
virtual void WriteAccessCheck ()=0
Private Member Functions
virtual IEditableProvider * EditProviderPrivate (const FName &Name)=0
virtual const IProvider * ReadProviderPrivate (const FName &Name) const =0
Detailed Description
Definition at line 74 of file AnalysisSession.h.
Constructor & Destructor Documentation
~IAnalysisSession()
virtual TraceServices::IAnalysisSession::~IAnalysisSession () virtual default
Member Function Documentation
AddAnalyzer() [1/2]
virtual void TraceServices::IAnalysisSession::AddAnalyzer (TSharedRef< UE::Trace::IAnalyzer > Analyzer) pure virtual
References AddAnalyzer().
AddAnalyzer() [2/2]
virtual void TraceServices::IAnalysisSession::AddAnalyzer (UE::Trace::IAnalyzer * Analyzer) pure virtual
References AddAnalyzer().
Referenced by AddAnalyzer(), and AddAnalyzer().
AddMetadata() [1/3]
virtual void TraceServices::IAnalysisSession::AddMetadata (FName InName, double InValue) pure virtual
References InName.
AddMetadata() [2/3]
virtual void TraceServices::IAnalysisSession::AddMetadata (FName InName, FString InValue) pure virtual
References InName.
AddMetadata() [3/3]
virtual void TraceServices::IAnalysisSession::AddMetadata (FName InName, int64 InValue) pure virtual
References InName.
AddProvider()
virtual void TraceServices::IAnalysisSession::AddProvider (const FName & Name, TSharedPtr< IProvider > Provider, TSharedPtr< IEditableProvider > EditableProvider = nullptr) pure virtual
References AddProvider(), and Name.
Referenced by AddProvider().
BeginEdit()
virtual void TraceServices::IAnalysisSession::BeginEdit () pure virtual
References BeginEdit().
Referenced by BeginEdit().
BeginRead()
virtual void TraceServices::IAnalysisSession::BeginRead () const pure virtual
References BeginRead().
Referenced by BeginRead().
DrainPendingMessages()
virtual TArray< FAnalysisMessage > TraceServices::IAnalysisSession::DrainPendingMessages () pure virtual
Moves pending messages to the return array.
References DrainPendingMessages().
Referenced by DrainPendingMessages().
EditProvider()
template<typename ProviderType> ProviderType * TraceServices::IAnalysisSession::EditProvider (const FName & Name) inline
Definition at line 132 of file AnalysisSession.h.
References EditProviderPrivate(), and Name.
EditProviderPrivate()
virtual IEditableProvider * TraceServices::IAnalysisSession::EditProviderPrivate (const FName & Name) private pure virtual
References Name.
Referenced by EditProvider().
EndEdit()
virtual void TraceServices::IAnalysisSession::EndEdit () pure virtual
References EndEdit().
Referenced by EndEdit().
EndRead()
virtual void TraceServices::IAnalysisSession::EndRead () const pure virtual
References EndRead().
Referenced by EndRead().
EnumerateMetadata()
virtual void TraceServices::IAnalysisSession::EnumerateMetadata (TFunctionRef< void(const FTraceSessionMetadata &Metadata)> Callback) const pure virtual
References Metadata.
GetCache()
virtual IAnalysisCache & TraceServices::IAnalysisSession::GetCache () pure virtual
References GetCache().
Referenced by GetCache().
GetDurationSeconds()
virtual double TraceServices::IAnalysisSession::GetDurationSeconds () const pure virtual
GetLinearAllocator()
virtual ILinearAllocator & TraceServices::IAnalysisSession::GetLinearAllocator () pure virtual
References GetLinearAllocator().
Referenced by GetLinearAllocator().
GetMetadataCount()
virtual uint32 TraceServices::IAnalysisSession::GetMetadataCount () const pure virtual
GetName()
virtual const TCHAR * TraceServices::IAnalysisSession::GetName () const pure virtual
GetNumPendingMessages()
virtual uint32 TraceServices::IAnalysisSession::GetNumPendingMessages () const pure virtual
Get the number of pending messages.
Can be called without lock
References GetNumPendingMessages().
Referenced by GetNumPendingMessages().
GetStringStore()
virtual IStringStore & TraceServices::IAnalysisSession::GetStringStore () pure virtual
References GetStringStore().
Referenced by GetStringStore().
GetTraceId()
virtual uint32 TraceServices::IAnalysisSession::GetTraceId () const pure virtual
IsAnalysisComplete()
virtual bool TraceServices::IAnalysisSession::IsAnalysisComplete () const pure virtual
ReadAccessCheck()
virtual void TraceServices::IAnalysisSession::ReadAccessCheck () const pure virtual
References ReadAccessCheck().
Referenced by ReadAccessCheck().
ReadProvider()
template<typename ProviderType> const ProviderType * TraceServices::IAnalysisSession::ReadProvider (const FName & Name) const inline
Definition at line 126 of file AnalysisSession.h.
References Name, ReadProvider(), and ReadProviderPrivate().
Referenced by ReadProvider().
ReadProviderPrivate()
virtual const IProvider * TraceServices::IAnalysisSession::ReadProviderPrivate (const FName & Name) const private pure virtual
References Name.
Referenced by ReadProvider().
Stop()
virtual void TraceServices::IAnalysisSession::Stop (bool bAndWait = false) const pure virtual
StoreString() [1/2]
virtual const TCHAR * TraceServices::IAnalysisSession::StoreString (const FStringView & String) pure virtual
References StoreString(), and String.
StoreString() [2/2]
virtual const TCHAR * TraceServices::IAnalysisSession::StoreString (const TCHAR * String) pure virtual
References StoreString(), and String.
Referenced by StoreString(), and StoreString().
UE_DEPRECATED()
TraceServices::IAnalysisSession::UE_DEPRECATED (5. 3, "No longer used.") const pure virtual
UpdateDurationSeconds()
virtual void TraceServices::IAnalysisSession::UpdateDurationSeconds (double Duration) pure virtual
Update the internal estimation of the session duration with a new timestamp.
This function should be called with any timestamps from individual events so the full session duration can be estimated.
References Duration.
Wait()
virtual void TraceServices::IAnalysisSession::Wait () const pure virtual
WriteAccessCheck()
virtual void TraceServices::IAnalysisSession::WriteAccessCheck () pure virtual
References WriteAccessCheck().
Referenced by WriteAccessCheck().
The documentation for this class was generated from the following file:
Developer/TraceServices/Public/TraceServices/Model/AnalysisSession.h