Unreal Engine 5.6 C++ API: ILiveLinkSource Class Reference
ILiveLinkSource Class Reference abstract
#include "ILiveLinkSource.h"
Public Member Functions
virtual ~ILiveLinkSource ()
virtual bool CanBeDisplayedInUI () const
Can this source be displayed in the Source UI list.
virtual TSubclassOf< ULiveLinkSourceSettings > GetSettingsClass () const
Setting class to display and used by the Source.
virtual FText GetSourceMachineName () const =0
For UI, from where the source data is coming from.
virtual FText GetSourceStatus () const =0
For UI, what is the status of the source.
virtual FText GetSourceToolTip () const
For UI, what should be shown in the source list when hovering this source.
virtual FText GetSourceType () const =0
For UI, what is the identifier of the source.
virtual void InitializeSettings (ULiveLinkSourceSettings *Settings)
The setting class has been created.
virtual bool IsSourceStillValid () const =0
Returns whether the Source is connected to its data provider and can still push valid data.
virtual void OnSettingsChanged (ULiveLinkSourceSettings *Settings, const FPropertyChangedEvent &PropertyChangedEvent)
Notification when a setting value has changed via the UI.
virtual void ReceiveClient (ILiveLinkClient *InClient, FGuid InSourceGuid)=0
The source has been added to the Client and a Guid has been associated.
virtual bool RequestSourceShutdown ()=0
Request the source to shutdown.
UE_DEPRECATED (4.24, "ILiveLinkClient::GetCustomSettingsClass is deprecated. Please use GetSettingsClass instead!") virtual UClass *GetCustomSettingsClass() const
virtual void Update ()
Update the source.
Detailed Description
Definition at line 15 of file ILiveLinkSource.h.
Constructor & Destructor Documentation
~ILiveLinkSource()
virtual ILiveLinkSource::~ILiveLinkSource () inline virtual
Definition at line 18 of file ILiveLinkSource.h.
Member Function Documentation
CanBeDisplayedInUI()
virtual bool ILiveLinkSource::CanBeDisplayedInUI () const inline virtual
Can this source be displayed in the Source UI list.
Definition at line 36 of file ILiveLinkSource.h.
GetSettingsClass()
virtual TSubclassOf< ULiveLinkSourceSettings > ILiveLinkSource::GetSettingsClass () const inline virtual
Setting class to display and used by the Source.
An instance of that class will be constructed when the source is added to the Client. Then InitializeSettings will be called.
Definition at line 67 of file ILiveLinkSource.h.
Referenced by UE_DEPRECATED().
GetSourceMachineName()
virtual FText ILiveLinkSource::GetSourceMachineName () const pure virtual
For UI, from where the source data is coming from.
GetSourceStatus()
virtual FText ILiveLinkSource::GetSourceStatus () const pure virtual
For UI, what is the status of the source.
Should be: "Active", "Not responding", "Connecting" or any short message that makes sense for the source.
GetSourceToolTip()
virtual FText ILiveLinkSource::GetSourceToolTip () const inline virtual
For UI, what should be shown in the source list when hovering this source.
Definition at line 61 of file ILiveLinkSource.h.
References FText::GetEmpty().
GetSourceType()
virtual FText ILiveLinkSource::GetSourceType () const pure virtual
For UI, what is the identifier of the source.
InitializeSettings()
virtual void ILiveLinkSource::InitializeSettings (ULiveLinkSourceSettings * Settings) inline virtual
The setting class has been created.
Called after ReceiveClient.
See also
GetSettingsClass
Definition at line 27 of file ILiveLinkSource.h.
IsSourceStillValid()
virtual bool ILiveLinkSource::IsSourceStillValid () const pure virtual
Returns whether the Source is connected to its data provider and can still push valid data.
OnSettingsChanged()
virtual void ILiveLinkSource::OnSettingsChanged (ULiveLinkSourceSettings * Settings, const FPropertyChangedEvent & PropertyChangedEvent) inline virtual
Notification when a setting value has changed via the UI.
Definition at line 72 of file ILiveLinkSource.h.
ReceiveClient()
virtual void ILiveLinkSource::ReceiveClient (ILiveLinkClient * InClient, FGuid InSourceGuid) pure virtual
The source has been added to the Client and a Guid has been associated.
RequestSourceShutdown()
virtual bool ILiveLinkSource::RequestSourceShutdown () pure virtual
Request the source to shutdown.
This may be called multiple times. Should return true, when the source can be destroyed. RequestSourceShutdown will be called multiple times until it returns true. If the source is multithreaded, the source should test if it can be shutdown, set a flag and return immediately.
UE_DEPRECATED()
ILiveLinkSource::UE_DEPRECATED (4. 24, "ILiveLinkClient::GetCustomSettingsClass is deprecated. Please use GetSettingsClass instead!") const inline
Definition at line 68 of file ILiveLinkSource.h.
References GetSettingsClass().
Update()
virtual void ILiveLinkSource::Update () inline virtual
Update the source.
This is called in a critical path on the game thread. The user is expected to return quickly.
Definition at line 33 of file ILiveLinkSource.h.
The documentation for this class was generated from the following file:
Runtime/LiveLinkInterface/Public/ILiveLinkSource.h