Unreal Engine 5.6 C++ API: FSoundBuffer Class Reference
FSoundBuffer Class Reference
#include "Audio.h"
Public Member Functions
FSoundBuffer (class FAudioDevice *InAudioDevice)
virtual ~FSoundBuffer ()
virtual FString Describe (bool bUseLongName)
Describe the buffer (platform can override to add to the description, but should call the base class version)
virtual void EnsureRealtimeTaskCompletion ()
Forces any pending async realtime source tasks to finish for the buffer.
FString GetChannelsDesc ()
Turn the number of channels into a string description.
virtual int32 GetCurrentChunkIndex () const
Gets the chunk index that was last read from (for Streaming Manager requests)
virtual int32 GetCurrentChunkOffset () const
Gets the offset into the chunk that was last read to (for Streaming Manager priority)
FName GetSoundClassName ()
Return the name of the sound class for this buffer.
virtual bool IsRealTimeSourceReady ()
Returns whether or not a real-time decoding buffer is ready for playback.
virtual bool ReadCompressedData (uint8 *Destination, int32 NumFramesToDecode, bool bLooping)
Reads the next compressed data chunk.
virtual bool ReadCompressedInfo (USoundWave *SoundWave)
Reads the compressed info of the given sound wave.
virtual void Seek (const float SeekTime)
Seeks the buffer to the given seek time.
Data Fields
class FAudioDevice * AudioDevice
Parent Audio Device used when creating the sound buffer.
bool bAllocationInPermanentPool
Whether memory for this buffer has been allocated from permanent pool.
virtual int32 GetSize () PURE_VIRTUAL(FSoundBuffer
int32 NumChannels
Cumulative channels from all streams.
int32 ResourceID
Unique ID that ties this buffer to a USoundWave.
FString ResourceName
Human readable name of resource, most likely name of UObject associated during caching.
Detailed Description
Definition at line 547 of file Audio.h.
Constructor & Destructor Documentation
FSoundBuffer()
FSoundBuffer::FSoundBuffer (class FAudioDevice * InAudioDevice) inline
Definition at line 550 of file Audio.h.
References AudioDevice, bAllocationInPermanentPool, NumChannels, and ResourceID.
~FSoundBuffer()
virtual FSoundBuffer::~FSoundBuffer () virtual
Member Function Documentation
Describe()
virtual FString FSoundBuffer::Describe (bool bUseLongName) virtual
Describe the buffer (platform can override to add to the description, but should call the base class version)
Parameters
bUseLongNames If TRUE, this will print out the full path of the sound resource, otherwise, it will show just the object name
References Describe().
Referenced by Describe().
EnsureRealtimeTaskCompletion()
virtual void FSoundBuffer::EnsureRealtimeTaskCompletion () inline virtual
Forces any pending async realtime source tasks to finish for the buffer.
Definition at line 605 of file Audio.h.
GetChannelsDesc()
FString FSoundBuffer::GetChannelsDesc ()
Turn the number of channels into a string description.
References GetChannelsDesc().
Referenced by GetChannelsDesc().
GetCurrentChunkIndex()
virtual int32 FSoundBuffer::GetCurrentChunkIndex () const inline virtual
Gets the chunk index that was last read from (for Streaming Manager requests)
Definition at line 594 of file Audio.h.
GetCurrentChunkOffset()
virtual int32 FSoundBuffer::GetCurrentChunkOffset () const inline virtual
Gets the offset into the chunk that was last read to (for Streaming Manager priority)
Definition at line 599 of file Audio.h.
GetSoundClassName()
FName FSoundBuffer::GetSoundClassName ()
Return the name of the sound class for this buffer.
References GetSoundClassName().
Referenced by GetSoundClassName().
IsRealTimeSourceReady()
virtual bool FSoundBuffer::IsRealTimeSourceReady () inline virtual
Returns whether or not a real-time decoding buffer is ready for playback.
Definition at line 602 of file Audio.h.
ReadCompressedData()
virtual bool FSoundBuffer::ReadCompressedData (uint8 * Destination, int32 NumFramesToDecode, bool bLooping) inline virtual
Reads the next compressed data chunk.
Definition at line 586 of file Audio.h.
ReadCompressedInfo()
virtual bool FSoundBuffer::ReadCompressedInfo (USoundWave * SoundWave) inline virtual
Reads the compressed info of the given sound wave.
Not implemented on all platforms.
Definition at line 583 of file Audio.h.
References ReadCompressedInfo().
Referenced by ReadCompressedInfo().
Seek()
virtual void FSoundBuffer::Seek (const float SeekTime) inline virtual
Seeks the buffer to the given seek time.
Definition at line 589 of file Audio.h.
Field Documentation
AudioDevice
class FAudioDevice* FSoundBuffer::AudioDevice
Parent Audio Device used when creating the sound buffer.
Used to remove tracking info on this sound buffer when its done.
Definition at line 616 of file Audio.h.
Referenced by FSoundBuffer().
bAllocationInPermanentPool
bool FSoundBuffer::bAllocationInPermanentPool
Whether memory for this buffer has been allocated from permanent pool.
Definition at line 614 of file Audio.h.
Referenced by FSoundBuffer().
GetSize
virtual int32 FSoundBuffer::GetSize() PURE_VIRTUAL(FSoundBuffer
Definition at line 561 of file Audio.h.
NumChannels
int32 FSoundBuffer::NumChannels
Cumulative channels from all streams.
Definition at line 610 of file Audio.h.
Referenced by FSoundBuffer().
ResourceID
int32 FSoundBuffer::ResourceID
Unique ID that ties this buffer to a USoundWave.
Definition at line 608 of file Audio.h.
Referenced by FSoundBuffer().
ResourceName
FString FSoundBuffer::ResourceName
Human readable name of resource, most likely name of UObject associated during caching.
Definition at line 612 of file Audio.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Audio.h