Unreal Engine 5.6 C++ API: FTextFormatString Class Reference
FTextFormatString Class Reference
Type used as a string literal by the text formatter.
#include "ITextFormatArgumentModifier.h"
Public Member Functions
FTextFormatString ()
Construct an empty string.
FTextFormatString (const FTextFormatString &Other)
FTextFormatString (const TCHAR *InStr)
Construct from the given string (takes a copy, expected to be null terminated)
FTextFormatString (FString InStr)
Construct from the given string (steals the value)
FTextFormatString (FTextFormatString &&Other)
FTextFormatString & operator= (const FTextFormatString &Other)
FTextFormatString & operator= (FTextFormatString &&Other)
Static Public Member Functions
static FTextFormatString MakeReference (const TCHAR *InStr)
Construct from the given string (takes a reference, expected to be null terminated)
static FTextFormatString MakeReference (const TCHAR *InStr, const int32 InLen)
Construct from the given pointer and size (takes a sub-string reference, doesn't have to be null terminated)
Data Fields
int32 StringLen
The length of the string.
const TCHAR * StringPtr
The start of the string.
Private Member Functions
FTextFormatString (const TCHAR *InStr, const int32 InLen)
Construct from the given pointer and size (takes a sub-string reference, doesn't have to be null terminated)
Private Attributes
FString InternalString
Internal copy if constructed from a string.
Friends
uint32 GetTypeHash (const FTextFormatString &InStr)
Detailed Description
Type used as a string literal by the text formatter.
It is a case sensitive string that can hold onto a string either by pointer (in which case the data being pointed to must outlive this object), or by taking a copy (stored as an FString internally).
Note
The buffer is not guaranteed to be null terminated, so always test the length!
Definition at line 25 of file ITextFormatArgumentModifier.h.
Constructor & Destructor Documentation
FTextFormatString() [1/6]
FTextFormatString::FTextFormatString () inline
Construct an empty string.
Definition at line 29 of file ITextFormatArgumentModifier.h.
References InternalString, StringLen, StringPtr, and TEXT.
Referenced by FTextFormatString(), FTextFormatString(), GetTypeHash, MakeReference(), MakeReference(), operator=(), and operator=().
FTextFormatString() [2/6]
FTextFormatString::FTextFormatString (FString InStr) inline
Construct from the given string (steals the value)
Definition at line 37 of file ITextFormatArgumentModifier.h.
References InternalString, MoveTemp(), StringLen, and StringPtr.
FTextFormatString() [3/6]
FTextFormatString::FTextFormatString (const TCHAR * InStr) inline
Construct from the given string (takes a copy, expected to be null terminated)
Definition at line 47 of file ITextFormatArgumentModifier.h.
References InternalString, StringLen, and StringPtr.
FTextFormatString() [4/6]
FTextFormatString::FTextFormatString (const FTextFormatString & Other) inline
Definition at line 68 of file ITextFormatArgumentModifier.h.
References FTextFormatString(), InternalString, Other, StringLen, and StringPtr.
FTextFormatString() [5/6]
FTextFormatString::FTextFormatString (FTextFormatString && Other) inline
Definition at line 79 of file ITextFormatArgumentModifier.h.
References FTextFormatString(), InternalString, MoveTemp(), Other, StringLen, and StringPtr.
FTextFormatString() [6/6]
FTextFormatString::FTextFormatString (const TCHAR * InStr, const int32 InLen) inline private
Construct from the given pointer and size (takes a sub-string reference, doesn't have to be null terminated)
Definition at line 129 of file ITextFormatArgumentModifier.h.
References InternalString, StringLen, and StringPtr.
Member Function Documentation
MakeReference() [1/2]
FTextFormatString FTextFormatString::MakeReference (const TCHAR * InStr) inline static
Construct from the given string (takes a reference, expected to be null terminated)
Definition at line 57 of file ITextFormatArgumentModifier.h.
References FTextFormatString(), and TCString< TCHAR >::Strlen().
MakeReference() [2/2]
FTextFormatString FTextFormatString::MakeReference (const TCHAR * InStr, const int32 InLen) inline static
Construct from the given pointer and size (takes a sub-string reference, doesn't have to be null terminated)
Definition at line 63 of file ITextFormatArgumentModifier.h.
References FTextFormatString().
operator=() [1/2]
FTextFormatString & FTextFormatString::operator= (const FTextFormatString & Other) inline
Definition at line 86 of file ITextFormatArgumentModifier.h.
References FTextFormatString(), InternalString, Other, StringLen, and StringPtr.
operator=() [2/2]
FTextFormatString & FTextFormatString::operator= (FTextFormatString && Other) inline
Definition at line 102 of file ITextFormatArgumentModifier.h.
References FTextFormatString(), InternalString, MoveTemp(), Other, StringLen, and StringPtr.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FTextFormatString & InStr) friend
Definition at line 113 of file ITextFormatArgumentModifier.h.
References FTextFormatString(), FCrc::MemCrc32(), StringLen, and StringPtr.
Field Documentation
InternalString
FString FTextFormatString::InternalString private
Internal copy if constructed from a string.
Definition at line 126 of file ITextFormatArgumentModifier.h.
Referenced by FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), operator=(), and operator=().
StringLen
int32 FTextFormatString::StringLen
The length of the string.
Definition at line 122 of file ITextFormatArgumentModifier.h.
Referenced by FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), GetTypeHash, operator!=(), operator<(), operator=(), operator=(), and operator==().
StringPtr
const TCHAR* FTextFormatString::StringPtr
The start of the string.
Definition at line 119 of file ITextFormatArgumentModifier.h.
Referenced by FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), FTextFormatString(), GetTypeHash, operator!=(), operator<(), operator=(), operator=(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/ITextFormatArgumentModifier.h