Unreal Engine 5.6 C++ API: UWorldProxy Class Reference
UWorldProxy Class Reference
Proxy class that allows verification on GWorld accesses.
#include "World.h"
Public Member Functions
UWorldProxy ()
UWorld * GetReference ()
operator UWorld * () const
UWorld & operator* ()
const UWorld & operator* () const
UWorld * operator-> ()
const UWorld * operator-> () const
UWorldProxy & operator= (const UWorldProxy &InProxy)
UWorldProxy & operator= (UWorld *InWorld)
bool operator== (const UWorldProxy &Other) const
Private Attributes
UWorld * World
Detailed Description
Proxy class that allows verification on GWorld accesses.
Definition at line 107 of file World.h.
Constructor & Destructor Documentation
UWorldProxy()
UWorldProxy::UWorldProxy () inline
Definition at line 111 of file World.h.
References World.
Referenced by operator=(), operator=(), and operator==().
Member Function Documentation
GetReference()
UWorld * UWorldProxy::GetReference () inline
Definition at line 164 of file World.h.
References checkSlow, IsInGameThread(), and World.
operator UWorld *()
UWorldProxy::operator UWorld * () const inline
Definition at line 158 of file World.h.
References checkSlow, IsInGameThread(), and World.
operator*() [1/2]
UWorld & UWorldProxy::operator* () inline
Definition at line 129 of file World.h.
References checkSlow, IsInGameThread(), and World.
operator*() [2/2]
const UWorld & UWorldProxy::operator* () const inline
Definition at line 135 of file World.h.
References checkSlow, IsInGameThread(), and World.
operator->() [1/2]
UWorld * UWorldProxy::operator-> () inline
Definition at line 115 of file World.h.
References checkSlow, IsInGameThread(), and World.
operator->() [2/2]
const UWorld * UWorldProxy::operator-> () const inline
Definition at line 123 of file World.h.
References checkSlow, IsInGameThread(), and World.
operator=() [1/2]
UWorldProxy & UWorldProxy::operator= (const UWorldProxy & InProxy) inline
Definition at line 147 of file World.h.
References UWorldProxy(), and World.
operator=() [2/2]
UWorldProxy & UWorldProxy::operator= (UWorld * InWorld) inline
Definition at line 141 of file World.h.
References UWorldProxy(), and World.
operator==()
bool UWorldProxy::operator== (const UWorldProxy & Other) const inline
Definition at line 153 of file World.h.
References UWorldProxy(), Other, and World.
Field Documentation
World
UWorld* UWorldProxy::World private
Definition at line 172 of file World.h.
Referenced by UWorldProxy(), GetReference(), operator UWorld *(), operator*(), operator*(), operator->(), operator->(), operator=(), operator=(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/World.h