Unreal Engine 5.6 C++ API: UUVEditorLayoutTool Class Reference
UUVEditorLayoutTool Class Reference
#include "UVEditorLayoutTool.h"
Public Member Functions
virtual bool CanAccept () const override
virtual bool HasAccept () const override
virtual bool HasCancel () const override
virtual void OnPropertyModified (UObject *PropertySet, FProperty *Property) override
virtual void OnTick (float DeltaTime) override
virtual void SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > &TargetsIn)
The tool will operate on the meshes given here.
virtual void Setup () override
virtual void Shutdown (EToolShutdownType ShutdownType) override
Protected Member Functions
void RecordAnalytics ()
Protected Attributes
TArray< TObjectPtr< UUVLayoutOperatorFactory > > Factories
UE::Geometry::UVEditorAnalytics::FTargetAnalytics InputTargetAnalytics
TObjectPtr< UUVLayoutProperties > Settings = nullptr
TArray< TObjectPtr< UUVEditorToolMeshInput > > Targets
FDateTime ToolStartTimeAnalytics
TObjectPtr< UUVTool2DViewportAPI > UVTool2DViewportAPI = nullptr
TObjectPtr< UUVToolSelectionAPI > UVToolSelectionAPI = nullptr
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Definition at line 37 of file UVEditorLayoutTool.h.
Member Function Documentation
CanAccept()
virtual bool UUVEditorLayoutTool::CanAccept () const override virtual
HasAccept()
virtual bool UUVEditorLayoutTool::HasAccept () const inline override virtual
Definition at line 57 of file UVEditorLayoutTool.h.
HasCancel()
virtual bool UUVEditorLayoutTool::HasCancel () const inline override virtual
Definition at line 56 of file UVEditorLayoutTool.h.
OnPropertyModified()
virtual void UUVEditorLayoutTool::OnPropertyModified (UObject * PropertySet, FProperty * Property) override virtual
References Property.
OnTick()
virtual void UUVEditorLayoutTool::OnTick (float DeltaTime) override virtual
References DeltaTime.
RecordAnalytics()
void UUVEditorLayoutTool::RecordAnalytics () protected
References RecordAnalytics().
Referenced by RecordAnalytics().
SetTargets()
virtual void UUVEditorLayoutTool::SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > & TargetsIn) inline virtual
The tool will operate on the meshes given here.
Definition at line 46 of file UVEditorLayoutTool.h.
References SetTargets(), and Targets.
Referenced by SetTargets().
Setup()
virtual void UUVEditorLayoutTool::Setup () override virtual
Shutdown()
virtual void UUVEditorLayoutTool::Shutdown (EToolShutdownType ShutdownType) override virtual
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorLayoutTool::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 39 of file UVEditorLayoutTool.h.
Factories
TArray<TObjectPtr<UUVLayoutOperatorFactory> > UUVEditorLayoutTool::Factories protected
Definition at line 70 of file UVEditorLayoutTool.h.
InputTargetAnalytics
UE::Geometry::UVEditorAnalytics::FTargetAnalytics UUVEditorLayoutTool::InputTargetAnalytics protected
Definition at line 83 of file UVEditorLayoutTool.h.
Settings
TObjectPtr<UUVLayoutProperties> UUVEditorLayoutTool::Settings = nullptr protected
Definition at line 67 of file UVEditorLayoutTool.h.
Targets
TArray<TObjectPtr<UUVEditorToolMeshInput> > UUVEditorLayoutTool::Targets protected
Definition at line 64 of file UVEditorLayoutTool.h.
Referenced by SetTargets().
ToolStartTimeAnalytics
FDateTime UUVEditorLayoutTool::ToolStartTimeAnalytics protected
Definition at line 84 of file UVEditorLayoutTool.h.
UVTool2DViewportAPI
TObjectPtr< UUVTool2DViewportAPI> UUVEditorLayoutTool::UVTool2DViewportAPI = nullptr protected
Definition at line 77 of file UVEditorLayoutTool.h.
UVToolSelectionAPI
TObjectPtr<UUVToolSelectionAPI> UUVEditorLayoutTool::UVToolSelectionAPI = nullptr protected
Definition at line 73 of file UVEditorLayoutTool.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/UVEditorLayoutTool.h