Unreal Engine 5.6 C++ API: SharedPointerInternals::TReferenceControllerBase< Mode > Class Template Reference
SharedPointerInternals::TReferenceControllerBase< Mode > Class Template Reference abstract
#include "SharedPointerInternals.h"
Public Member Functions
FORCEINLINE TReferenceControllerBase ()=default
TReferenceControllerBase (const TReferenceControllerBase &)=delete
virtual ~TReferenceControllerBase ()
FORCEINLINE void AddSharedReference ()
Adds a shared reference to this counter.
FORCEINLINE void AddWeakReference ()
Adds a weak reference to this counter.
bool ConditionallyAddSharedReference ()
Adds a shared reference to this counter ONLY if there is already at least one reference.
virtual void DestroyObject ()=0
Destroys the object associated with this reference counter.
FORCEINLINE int32 GetSharedReferenceCount () const
Returns the shared reference count.
FORCEINLINE bool IsUnique () const
Checks if there is exactly one reference left to the object.
TReferenceControllerBase & operator= (const TReferenceControllerBase &)=delete
FORCEINLINE void ReleaseSharedReference ()
Releases a shared reference to this counter.
void ReleaseWeakReference ()
Releases a weak reference to this counter.
Data Fields
RefCountType SharedReferenceCount {1}
RefCountType WeakReferenceCount {1}
Private Types
using RefCountType = std::conditional_t<Mode == ESPMode::ThreadSafe, std::atomic<int32>, int32>
Detailed Description
template<ESPMode Mode>
class SharedPointerInternals::TReferenceControllerBase< Mode >
Definition at line 44 of file SharedPointerInternals.h.
Member Typedef Documentation
RefCountType
template<ESPMode Mode> using SharedPointerInternals::TReferenceControllerBase< Mode >::RefCountType = std::conditional_t<Mode == ESPMode::ThreadSafe, std::atomic<int32>, int32> private
Definition at line 46 of file SharedPointerInternals.h.
Constructor & Destructor Documentation
TReferenceControllerBase() [1/2]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::TReferenceControllerBase< Mode >::TReferenceControllerBase () explicit default
References FORCEINLINE.
Referenced by TReferenceControllerBase(), and operator=().
~TReferenceControllerBase()
template<ESPMode Mode> virtual SharedPointerInternals::TReferenceControllerBase< Mode >::~TReferenceControllerBase () inline virtual
Definition at line 68 of file SharedPointerInternals.h.
TReferenceControllerBase() [2/2]
template<ESPMode Mode> SharedPointerInternals::TReferenceControllerBase< Mode >::TReferenceControllerBase (const TReferenceControllerBase< Mode > &) delete
References TReferenceControllerBase().
Member Function Documentation
AddSharedReference()
template<ESPMode Mode> FORCEINLINE void SharedPointerInternals::TReferenceControllerBase< Mode >::AddSharedReference () inline
Adds a shared reference to this counter.
Definition at line 106 of file SharedPointerInternals.h.
References FORCEINLINE, ReleaseSharedReference(), SharedReferenceCount, and ThreadSafe.
AddWeakReference()
template<ESPMode Mode> FORCEINLINE void SharedPointerInternals::TReferenceControllerBase< Mode >::AddWeakReference () inline
Adds a weak reference to this counter.
Definition at line 252 of file SharedPointerInternals.h.
References FORCEINLINE, ReleaseWeakReference(), ThreadSafe, and WeakReferenceCount.
Referenced by SharedPointerInternals::FWeakReferencer< Mode >::AssignReferenceController().
ConditionallyAddSharedReference()
template<ESPMode Mode> bool SharedPointerInternals::TReferenceControllerBase< Mode >::ConditionallyAddSharedReference () inline
Adds a shared reference to this counter ONLY if there is already at least one reference.
Returns
True if the shared reference was added successfully
Definition at line 144 of file SharedPointerInternals.h.
References ReleaseSharedReference(), SharedReferenceCount, and ThreadSafe.
DestroyObject()
template<ESPMode Mode> virtual void SharedPointerInternals::TReferenceControllerBase< Mode >::DestroyObject () pure virtual
Destroys the object associated with this reference counter.
Implemented in SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >, and SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >.
Referenced by ReleaseSharedReference().
GetSharedReferenceCount()
template<ESPMode Mode> FORCEINLINE int32 SharedPointerInternals::TReferenceControllerBase< Mode >::GetSharedReferenceCount () const inline
Returns the shared reference count.
Definition at line 73 of file SharedPointerInternals.h.
References Count, FORCEINLINE, SharedReferenceCount, and ThreadSafe.
Referenced by IsUnique().
IsUnique()
template<ESPMode Mode> FORCEINLINE bool SharedPointerInternals::TReferenceControllerBase< Mode >::IsUnique () const inline
Checks if there is exactly one reference left to the object.
Definition at line 100 of file SharedPointerInternals.h.
References FORCEINLINE, and GetSharedReferenceCount().
operator=()
template<ESPMode Mode> TReferenceControllerBase & SharedPointerInternals::TReferenceControllerBase< Mode >::operator= (const TReferenceControllerBase< Mode > &) delete
References TReferenceControllerBase().
ReleaseSharedReference()
template<ESPMode Mode> FORCEINLINE void SharedPointerInternals::TReferenceControllerBase< Mode >::ReleaseSharedReference () inline
Releases a shared reference to this counter.
Definition at line 212 of file SharedPointerInternals.h.
References checkSlow, DestroyObject(), FORCEINLINE, ReleaseWeakReference(), SharedReferenceCount, and ThreadSafe.
Referenced by AddSharedReference(), and ConditionallyAddSharedReference().
ReleaseWeakReference()
template<ESPMode Mode> void SharedPointerInternals::TReferenceControllerBase< Mode >::ReleaseWeakReference () inline
Releases a weak reference to this counter.
Definition at line 285 of file SharedPointerInternals.h.
References checkSlow, ThreadSafe, and WeakReferenceCount.
Referenced by AddWeakReference(), and ReleaseSharedReference().
Field Documentation
SharedReferenceCount
template<ESPMode Mode> RefCountType SharedPointerInternals::TReferenceControllerBase< Mode >::SharedReferenceCount {1}
Definition at line 56 of file SharedPointerInternals.h.
Referenced by AddSharedReference(), ConditionallyAddSharedReference(), GetSharedReferenceCount(), and ReleaseSharedReference().
WeakReferenceCount
template<ESPMode Mode> RefCountType SharedPointerInternals::TReferenceControllerBase< Mode >::WeakReferenceCount {1}
Definition at line 63 of file SharedPointerInternals.h.
Referenced by AddWeakReference(), and ReleaseWeakReference().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/SharedPointerInternals.h