Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FMergeContext Class Reference
UE::Landscape::EditLayers::FMergeContext Class Reference
Global info about the landscape being merged that can be used throughout the merge.
#include "LandscapeEditLayerMergeContext.h"
Public Member Functions
FMergeContext (ALandscape *InLandscape, bool bInIsHeightmapMerge, bool bInSkipProceduralRenderers)
FMergeContext (const FMergeContext &Other)=default
FMergeContext (FMergeContext &&Other)=default
virtual ~FMergeContext ()=default
const TBitArray & GetNegatedVisibilityTargetLayerMask () const
Same as GetVisibilityTargetLayerMask() but negated.
const TBitArray & GetValidTargetLayerBitIndices () const
int32 GetVisibilityTargetLayerIndex () const
const TBitArray & GetVisibilityTargetLayerMask () const
FMergeContext & operator= (const FMergeContext &Other)=default
FMergeContext & operator= (FMergeContext &&Other)=default
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline ALandscape *GetLandscape() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline bool IsHeightmapMerge() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline bool ShouldSkipProceduralRenderers() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline const TArray< FName > &GetAllTargetLayerNames() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline const TArray< ULandscapeLayerInfoObject * > &GetAllWeightmapLayerInfos() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") inline ULandscapeInfo *GetLandscapeInfo() const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FName GetTargetLayerNameForIndex(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API FName GetTargetLayerNameForIndexChecked(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForLayerInfo(ULandscapeLayerInfoObject *InLayerInfo) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForLayerInfoChecked(ULandscapeLayerInfoObject *InLayerInfo) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForName(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 GetTargetLayerIndexForNameChecked(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 IsTargetLayerIndexValid(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 IsValidTargetLayerName(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API int32 IsValidTargetLayerNameChecked(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TArray< FName > ConvertTargetLayerBitIndicesToNames(const TBitArray<> &InTargetLayerBitIndices) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TArray< ULandscapeLayerInfoObject * > ConvertTargetLayerBitIndicesToLayerInfos(const TBitArray<> &InTargetLayerBitIndices) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> BuildTargetLayerBitIndices(bool bInBitValue) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> ConvertTargetLayerNamesToBitIndices(TConstArrayView< FName > InTargetLayerNames) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API TBitArray<> ConvertTargetLayerNamesToBitIndicesChecked(TConstArrayView< FName > InTargetLayerNames) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeLayerInfoObject *GetTargetLayerInfoForIndex(int32 InIndex) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeLayerInfoObject *GetTargetLayerInfoForName(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API ULandscapeLayerInfoObject *GetTargetLayerInfoForNameChecked(const FName &InName) const
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void ForEachTargetLayer(const TBitArray<> &InTargetLayerBitIndices
Runs the given function for each all valid target layer in the bit indices in parameters, with the possibility of early exit Most easily used with a lambda as follows: ForEachTargetLayer([](int32 InTargetLayerIndex, FName InTargetLayerName) -> bool { return continueLoop ?
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") LANDSCAPE_API void ForEachValidTargetLayer(TFunctionRef< bool(int32
Same as ForEachTargetLayer but skips over invalid target layers.
UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") TArray< FName > GetValidTargetLayerNames() const
Data Fields
friend ALandscape
TFunctionRef< bool(int32, const FName &, ULandscapeLayerInfoObject *)> Fn const
const FName ULandscapeLayerInfoObject *Fn const
Protected Attributes
TArray< FName > AllTargetLayerNames
List of all target layer names that can possibly be rendered on this landscape (even invalid ones).
TArray< ULandscapeLayerInfoObject * > AllWeightmapLayerInfos
Per-target layer info.
bool bIsHeightmapMerge = false
Type of merge being requested.
bool bSkipProceduralRenderers = false
Allows to skip all non-default (i.e.
ALandscape * Landscape = nullptr
Landscape being merged.
ULandscapeInfo * LandscapeInfo = nullptr
Landscape info associated with the landscape being merged.
TBitArray NegatedVisibilityTargetLayerMask
Bit mask that corresponds to all target layers except the visibility layer.
TBitArray ValidTargetLayerBitIndices
List of valid target layers.
int32 VisibilityTargetLayerIndex = INDEX_NONE
TBitArray VisibilityTargetLayerMask
Bit mask that corresponds to only the visibility layer.
Detailed Description
Global info about the landscape being merged that can be used throughout the merge.
Definition at line 27 of file LandscapeEditLayerMergeContext.h.
Constructor & Destructor Documentation
FMergeContext() [1/3]
UE::Landscape::EditLayers::FMergeContext::FMergeContext (ALandscape * InLandscape, bool bInIsHeightmapMerge, bool bInSkipProceduralRenderers)
References ALandscape.
Referenced by FMergeContext(), FMergeContext(), UE::Landscape::EditLayers::FMergeRenderContext::FMergeRenderContext(), operator=(), and operator=().
~FMergeContext()
virtual UE::Landscape::EditLayers::FMergeContext::~FMergeContext () virtual default
FMergeContext() [2/3]
UE::Landscape::EditLayers::FMergeContext::FMergeContext (const FMergeContext & Other) default
References FMergeContext(), and Other.
FMergeContext() [3/3]
UE::Landscape::EditLayers::FMergeContext::FMergeContext (FMergeContext && Other) default
References FMergeContext(), and Other.
Member Function Documentation
GetNegatedVisibilityTargetLayerMask()
const TBitArray & UE::Landscape::EditLayers::FMergeContext::GetNegatedVisibilityTargetLayerMask () const inline
Same as GetVisibilityTargetLayerMask() but negated.
Definition at line 198 of file LandscapeEditLayerMergeContext.h.
References NegatedVisibilityTargetLayerMask.
GetValidTargetLayerBitIndices()
const TBitArray & UE::Landscape::EditLayers::FMergeContext::GetValidTargetLayerBitIndices () const inline
Returns
a bit mask for all target layers from AllTargetLayerNames that have a valid landscape layer info object
Definition at line 203 of file LandscapeEditLayerMergeContext.h.
References ValidTargetLayerBitIndices.
GetVisibilityTargetLayerIndex()
int32 UE::Landscape::EditLayers::FMergeContext::GetVisibilityTargetLayerIndex () const inline
Returns
the index corresponding to the visibility target layer in AllTargetLayerNames, INDEX_NONE if it's not in the list of layers
Definition at line 190 of file LandscapeEditLayerMergeContext.h.
References VisibilityTargetLayerIndex.
GetVisibilityTargetLayerMask()
const TBitArray & UE::Landscape::EditLayers::FMergeContext::GetVisibilityTargetLayerMask () const inline
Returns
a bit mask the size of AllTargetLayerNames, where all bits are set to zero except the one corresponding to the visibility target layer
Definition at line 195 of file LandscapeEditLayerMergeContext.h.
References VisibilityTargetLayerMask.
operator=() [1/2]
FMergeContext & UE::Landscape::EditLayers::FMergeContext::operator= (const FMergeContext & Other) default
References FMergeContext(), and Other.
operator=() [2/2]
FMergeContext & UE::Landscape::EditLayers::FMergeContext::operator= (FMergeContext && Other) default
References FMergeContext(), and Other.
UE_EXPERIMENTAL() [1/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Definition at line 39 of file LandscapeEditLayerMergeContext.h.
References ALandscape, Landscape, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [2/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Returns
true if this merge context is used for a heightmap merge, false otherwise (visibility / weightmap)
Definition at line 66 of file LandscapeEditLayerMergeContext.h.
References bIsHeightmapMerge, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [3/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Returns
true if this merge context is used for a heightmap merge, false otherwise (visibility / weightmap)
Definition at line 72 of file LandscapeEditLayerMergeContext.h.
References bSkipProceduralRenderers, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [4/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const & inline
Returns
all target layer names declared in this context, including ones that are potentially invalid (i.e. no layer info associated)
Definition at line 48 of file LandscapeEditLayerMergeContext.h.
References AllTargetLayerNames, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [5/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const & inline
Returns
all layer info objects declared in this context (can contain null entries for invalid layers or in the case of a heightmap merge)
Definition at line 60 of file LandscapeEditLayerMergeContext.h.
References AllWeightmapLayerInfos, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [6/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const inline
Definition at line 42 of file LandscapeEditLayerMergeContext.h.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL, and LandscapeInfo.
UE_EXPERIMENTAL() [7/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
the target layer name corresponding to the index in this context, NAME_None if not found
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [8/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
the target layer name corresponding to the index in this context, NAME_None if not found. Asserts if the layer index isn't known to the merge context
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [9/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
the index of this landscape layer info in this context, INDEX_NONE if not found
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [10/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
the index of this landscape layer info in this context. Asserts if the layer info isn't known to the merge context
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [11/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
the index of this target layer name in this context, INDEX_NONE if not found
References InName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [12/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
the index of this target layer name in this context. Asserts if the layer name isn't known to the merge context
References InName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [13/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
true if the target layer index is valid in the list of declared target layers on the merge context. Important note : it doesn't mean that it's associated with a valid layer info object, use IsValidTargetLayerName for this!
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [14/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
true if the target layer name is registered to this merge context and has an associated layer info object
References InName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [15/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
true if the target layer name has an associated layer info object. Asserts if the layer name isn't known to the merge context
References InName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [16/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
a list of target layer names for each set bit in InTargetLayerBitIndices. Asserts if InTargetLayerBitIndices isn't the same size as AllTargetLayerNames
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [17/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
a list of landscape layer info objects for each set bit in InTargetLayerBitIndices. Asserts if InTargetLayerBitIndices isn't the same size as AllTargetLayerNames
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [18/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
a bit mask the size of AllTargetLayerNames, where all bits are set to bBitValue
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [19/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
a TBitArray<> where, for each layer from InTargetLayerNames that is found in this context, the corresponding bit is set
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [20/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
a TBitArray<> where, for each layer from InTargetLayerNames that is found in this context, the corresponding bit is set. Asserts if one of the layer names isn't known to the merge context
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [21/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
the landscape layer object corresponding to the index in this context, nullptr if not found. Asserts if the layer index isn't known to the merge context
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [22/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
the landscape layer object corresponding to the target layer name in this context, nullptr if not found
References InName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [23/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Returns
the landscape layer object corresponding to the target layer name in this context. Asserts if the layer name isn't known to the merge context
References InName, and LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [24/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const &
Runs the given function for each all valid target layer in the bit indices in parameters, with the possibility of early exit Most easily used with a lambda as follows: ForEachTargetLayer([](int32 InTargetLayerIndex, FName InTargetLayerName) -> bool { return continueLoop ?
true : false; });
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [25/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Same as ForEachTargetLayer but skips over invalid target layers.
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
UE_EXPERIMENTAL() [26/26]
UE::Landscape::EditLayers::FMergeContext::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.") const
Returns
all target layer names that have a valid layer info object. Will return the height layer in the case of a heightmap merge, even though there's no layer info for those :
References LANDSCAPE_EDIT_LAYERS_BATCHED_MERGE_EXPERIMENTAL.
Field Documentation
ALandscape
friend UE::Landscape::EditLayers::FMergeContext::ALandscape
Definition at line 30 of file LandscapeEditLayerMergeContext.h.
Referenced by FMergeContext(), and UE_EXPERIMENTAL().
AllTargetLayerNames
TArray<FName> UE::Landscape::EditLayers::FMergeContext::AllTargetLayerNames protected
List of all target layer names that can possibly be rendered on this landscape (even invalid ones).
The index of the target layer in that list is important : it allows to use a TBitArray instead of a TSet to designate a list of target layers all throughout the merge, which greatly accelerates all the intersection tests being made. If merging heightmaps, it contains a single name (that is only meaningful for debug display).
Definition at line 230 of file LandscapeEditLayerMergeContext.h.
Referenced by UE_EXPERIMENTAL().
AllWeightmapLayerInfos
TArray<ULandscapeLayerInfoObject*> UE::Landscape::EditLayers::FMergeContext::AllWeightmapLayerInfos protected
Per-target layer info.
Same size as AllTargetLayerNames (only meaningful when rendering weightmaps)
Definition at line 239 of file LandscapeEditLayerMergeContext.h.
Referenced by UE_EXPERIMENTAL().
bIsHeightmapMerge
bool UE::Landscape::EditLayers::FMergeContext::bIsHeightmapMerge = false protected
Type of merge being requested.
Definition at line 216 of file LandscapeEditLayerMergeContext.h.
Referenced by UE_EXPERIMENTAL().
bSkipProceduralRenderers
bool UE::Landscape::EditLayers::FMergeContext::bSkipProceduralRenderers = false protected
Allows to skip all non-default (i.e.
persistent edit layer) layer renderers for this merge. Mostly there for backwards compatibility and debugging purposes.
Definition at line 219 of file LandscapeEditLayerMergeContext.h.
Referenced by UE_EXPERIMENTAL().
const [1/2]
TFunctionRef<bool(int32 , const FName& , ULandscapeLayerInfoObject*)> Fn UE::Landscape::EditLayers::FMergeContext::const
Definition at line 181 of file LandscapeEditLayerMergeContext.h.
Referenced by UE::Landscape::EditLayers::FMergeRenderContext::Render(), and UE::Landscape::EditLayers::FMergeRenderContext::FOnRenderBatchTargetGroupDoneParams::UE_DEPRECATED().
const [2/2]
const FName ULandscapeLayerInfoObject* Fn UE::Landscape::EditLayers::FMergeContext::const
Definition at line 185 of file LandscapeEditLayerMergeContext.h.
Landscape
ALandscape* UE::Landscape::EditLayers::FMergeContext::Landscape = nullptr protected
Landscape being merged.
Definition at line 222 of file LandscapeEditLayerMergeContext.h.
Referenced by UE::Landscape::EditLayers::FMergeRenderContext::Render(), and UE_EXPERIMENTAL().
LandscapeInfo
ULandscapeInfo* UE::Landscape::EditLayers::FMergeContext::LandscapeInfo = nullptr protected
Landscape info associated with the landscape being merged.
Definition at line 225 of file LandscapeEditLayerMergeContext.h.
Referenced by UE_EXPERIMENTAL().
NegatedVisibilityTargetLayerMask
TBitArray UE::Landscape::EditLayers::FMergeContext::NegatedVisibilityTargetLayerMask protected
Bit mask that corresponds to all target layers except the visibility layer.
Definition at line 236 of file LandscapeEditLayerMergeContext.h.
Referenced by GetNegatedVisibilityTargetLayerMask().
ValidTargetLayerBitIndices
TBitArray UE::Landscape::EditLayers::FMergeContext::ValidTargetLayerBitIndices protected
List of valid target layers.
If a target layer name is present here, it's because it has a valid landscape layer info object. Each bit in that bit array corresponds to an entry in AllTargetLayerNames
Definition at line 242 of file LandscapeEditLayerMergeContext.h.
Referenced by GetValidTargetLayerBitIndices().
VisibilityTargetLayerIndex
int32 UE::Landscape::EditLayers::FMergeContext::VisibilityTargetLayerIndex = INDEX_NONE protected
Definition at line 245 of file LandscapeEditLayerMergeContext.h.
Referenced by GetVisibilityTargetLayerIndex().
VisibilityTargetLayerMask
TBitArray UE::Landscape::EditLayers::FMergeContext::VisibilityTargetLayerMask protected
Bit mask that corresponds to only the visibility layer.
Definition at line 233 of file LandscapeEditLayerMergeContext.h.
Referenced by GetVisibilityTargetLayerMask().
The documentation for this class was generated from the following file:
Runtime/Landscape/Public/LandscapeEditLayerMergeContext.h