Unreal Engine 5.6 C++ API: FGlobalShader Class Reference
FGlobalShader Class Reference
FGlobalShader.
#include "GlobalShader.h"
Public Types
using FPermutationParameters = FGlobalShaderPermutationParameters
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FShader
using CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
using FPermutationDomain = FShaderPermutationNone
using FPermutationParameters = FShaderPermutationParameters
using FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
using ShaderMetaType = FShaderType
using ShaderStatKeyType = FMemoryImageName
Public Member Functions
FGlobalShader ()=default
RENDERCORE_API FGlobalShader (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
template<typename TViewUniformShaderParameters>
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, FRHIUniformBuffer *ViewUniformBuffer)
Public Member Functions inherited from FShader
RENDERCORE_API FShader ()
Used to construct a shader for deserialization.
RENDERCORE_API FShader (const CompiledShaderInitializerType &Initializer)
Construct a shader from shader compiler output.
RENDERCORE_API ~FShader ()
RENDERCORE_API void DumpDebugInfo (const FShaderMapPointerTable &InPtrTable)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API const FShaderParametersMetadata * FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
uint32 GetCodeSize () const
EShaderFrequency GetFrequency () const
RENDERCORE_API const FSHAHash & GetHash () const
Returns the hash of the shader file that this shader was compiled with.
uint32 GetNumInstructions () const
uint32 GetNumTextureSamplers () const
RENDERCORE_API const FSHAHash & GetOutputHash () const
int32 GetResourceIndex () const
EShaderPlatform GetShaderPlatform () const
uint32 GetSortKey () const
Returns an identifier suitable for deterministic sorting of shaders between sessions.
const FShaderTarget GetTarget () const
FShaderType * GetType (const FPointerTableBase *InPointerTable) const
FShaderType * GetType (const FShaderMapPointerTable &InPointerTable) const
FShaderType * GetTypeUnfrozen () const
template<typename UniformBufferStructType>
const TShaderUniformBufferParameter< UniformBufferStructType > & GetUniformBufferParameter () const
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FHashedName SearchName) const
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FShaderParametersMetadata *SearchStruct) const
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
RENDERCORE_API const FSHAHash & GetVertexFactoryHash () const
FVertexFactoryType * GetVertexFactoryType (const FPointerTableBase *InPointerTable) const
FVertexFactoryType * GetVertexFactoryType (const FShaderMapPointerTable &InPointerTable) const
bool IsFrozen () const
LAYOUT_FIELD (FShaderParameterBindings, Bindings)
LAYOUT_FIELD (FShaderParameterMapInfo, ParameterMapInfo)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SetNumInstructions (uint32 Value)
Static Public Member Functions
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &Environment)
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Static Public Member Functions inherited from FShader
static EShaderCompileJobPriority GetOverrideJobPriority ()
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
static ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId)
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
static const FShaderParametersMetadata * GetRootParametersMetadata ()
Returns the meta data for the root shader parameter struct.
static const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &)
Get shader binding layout used by the shader.
static void ModifyCompilationEnvironment (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
static bool ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap &InParameterMap, TArray< FString > &OutError)
Can be overridden by FShader subclasses to determine whether compilation is valid.
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FGlobalShader, RENDERCORE_API, NonVirtual)
Additional Inherited Members
Protected Member Functions inherited from FShader
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, UniformBufferParameterStructs)
LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter >, UniformBufferParameters)
LAYOUT_FIELD_EDITORONLY (FSHAHash, OutputHash)
Hash of the compiled output from this shader and the resulting parameter map.
LAYOUT_FIELD_EDITORONLY (FSHAHash, SourceHash)
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY (FSHAHash, VFSourceHash)
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
Detailed Description
FGlobalShader.
Global shaders derive from this class to set their default recompile group as a global one
Definition at line 274 of file GlobalShader.h.
Member Typedef Documentation
FPermutationParameters
using FGlobalShader::FPermutationParameters = FGlobalShaderPermutationParameters
Definition at line 279 of file GlobalShader.h.
ShaderMetaType
using FGlobalShader::ShaderMetaType = FGlobalShaderType
Definition at line 278 of file GlobalShader.h.
Constructor & Destructor Documentation
FGlobalShader() [1/2]
FGlobalShader::FGlobalShader () default
Referenced by FARGB16BigConvertPS::FARGB16BigConvertPS(), FAYUVConvertPS::FAYUVConvertPS(), FBinkDrawICtCpPS::FBinkDrawICtCpPS(), FBinkDrawVS::FBinkDrawVS(), FBinkDrawYCbCrPS::FBinkDrawYCbCrPS(), FBMPConvertPS::FBMPConvertPS(), FCopyRectPS::FCopyRectPS(), FCopyRectSrvPS::FCopyRectSrvPS(), FCopyTextureCS::FCopyTextureCS(), FDispatchShaderBundleCS::FDispatchShaderBundleCS(), FDispatchShaderBundleWorkGraph::FDispatchShaderBundleWorkGraph(), FImagePreTransformVS::FImagePreTransformVS(), FMediaShadersVS::FMediaShadersVS(), FModifyAlphaSwizzleRgbaPS::FModifyAlphaSwizzleRgbaPS(), FNULLPS::FNULLPS(), FNV12ConvertAsBytesPS::FNV12ConvertAsBytesPS(), FNV12ConvertPS::FNV12ConvertPS(), FNV21ConvertPS::FNV21ConvertPS(), FOculusAlphaInverseShader::FOculusAlphaInverseShader(), FOculusBlackShader::FOculusBlackShader(), FOculusCubemapPS::FOculusCubemapPS(), FOculusVertexShader::FOculusVertexShader(), FOculusWhiteShader::FOculusWhiteShader(), FOneColorPS::FOneColorPS(), FP010_2101010ConvertPS::FP010_2101010ConvertPS(), FP010ConvertAsUINT16sPS::FP010ConvertAsUINT16sPS(), FP010ConvertPS::FP010ConvertPS(), FPixelShaderUtils::FRasterizeToRectsVS::FRasterizeToRectsVS(), FReadTextureExternalPS::FReadTextureExternalPS(), FRGB10toYUVv210ConvertPS::FRGB10toYUVv210ConvertPS(), FRGB8toUYVY8ConvertPS::FRGB8toUYVY8ConvertPS(), FRGB8toY8ConvertPS::FRGB8toY8ConvertPS(), FRGBConvertPS::FRGBConvertPS(), FScreenPS::FScreenPS(), FScreenPS_OSE::FScreenPS_OSE(), FScreenPSArraySlice::FScreenPSArraySlice(), FScreenPSInvertAlpha::FScreenPSInvertAlpha(), FScreenPSMipLevel::FScreenPSMipLevel(), FScreenPSsRGBSource::FScreenPSsRGBSource(), FScreenPSsRGBSourceMipLevel::FScreenPSsRGBSourceMipLevel(), FScreenVertexShaderVS::FScreenVertexShaderVS(), FScreenVS::FScreenVS(), FStereoLayerPS_Base::FStereoLayerPS_Base(), FStereoLayerVS::FStereoLayerVS(), FUpdateDescriptorHandleCS::FUpdateDescriptorHandleCS(), FUpdateTextureShaderBase::FUpdateTextureShaderBase(), FUYVYConvertPS::FUYVYConvertPS(), FVYUConvertPS::FVYUConvertPS(), FYCbCrConvertPS::FYCbCrConvertPS(), FYCoCgConvertPS::FYCoCgConvertPS(), FYUVConvertPS::FYUVConvertPS(), FYUVv210ConvertPS::FYUVv210ConvertPS(), FYUVv216ConvertPS::FYUVv216ConvertPS(), FYUVY416ConvertPS::FYUVY416ConvertPS(), FYUY2ConvertPS::FYUY2ConvertPS(), FYVYUConvertPS::FYVYUConvertPS(), TClearReplacementBase< EClearReplacementValueType::Uint32, 1, false, false >::TClearReplacementBase(), TOneColorVS< bUsingNDCPositions, bUsingVertexLayers >::TOneColorVS(), DECLARE_EXPORTED_TYPE_LAYOUT(), FCopyResidentBricksCS::SHADER_USE_PARAMETER_STRUCT(), FCopyResidentBrickSHCoefficientsCS::SHADER_USE_PARAMETER_STRUCT(), FMoveWholeIndirectionTextureCS::SHADER_USE_PARAMETER_STRUCT(), FPatchIndirectionTextureCS::SHADER_USE_PARAMETER_STRUCT(), and FRemoveSubLevelBricksCS::SHADER_USE_PARAMETER_STRUCT().
FGlobalShader() [2/2]
RENDERCORE_API FGlobalShader::FGlobalShader (const ShaderMetaType::CompiledShaderInitializerType & Initializer)
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FGlobalShader::DECLARE_EXPORTED_TYPE_LAYOUT (FGlobalShader , RENDERCORE_API , NonVirtual) private
References FGlobalShader().
ModifyCompilationEnvironment()
void FGlobalShader::ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & Environment) inline static
Definition at line 295 of file GlobalShader.h.
Referenced by FCopyTextureCS::ModifyCompilationEnvironment(), FIESLightProfilePS::ModifyCompilationEnvironment(), FInstancedScreenVertexShaderVS::ModifyCompilationEnvironment(), FMobileMultiViewVertexShaderVS::ModifyCompilationEnvironment(), FScreenFromSlice0PS::ModifyCompilationEnvironment(), FScreenUnwrapSlicesPS::ModifyCompilationEnvironment(), FUpdateDescriptorHandleCS::ModifyCompilationEnvironment(), FUpdateTextureShaderBase::ModifyCompilationEnvironment(), TClearReplacementBase< EClearReplacementValueType::Uint32, 1, false, false >::ModifyCompilationEnvironment(), and TOneColorVS< bUsingNDCPositions, bUsingVertexLayers >::ModifyCompilationEnvironment().
SetParameters()
template<typename TViewUniformShaderParameters> void FGlobalShader::SetParameters (FRHIBatchedShaderParameters & BatchedParameters, FRHIUniformBuffer * ViewUniformBuffer) inline
Definition at line 286 of file GlobalShader.h.
References FShader::GetUniformBufferParameter(), and SetUniformBufferParameter().
Referenced by FScreenVS::SetParameters().
ShouldCompilePermutation()
bool FShader::ShouldCompilePermutation (const FShaderPermutationParameters &) inline static
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
Definition at line 877 of file Shader.h.
ShouldPrecachePermutation()
EShaderPermutationPrecacheRequest FShader::ShouldPrecachePermutation (const FShaderPermutationParameters & Parameters) inline static
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Definition at line 880 of file Shader.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/GlobalShader.h