Unreal Engine 5.6 C++ API: UKismetStringTableLibrary Class Reference
UKismetStringTableLibrary Class Reference
#include "KismetStringTableLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION()) static 1 bool IsRegisteredTableId(const FName TableId)
Returns true if the given table ID corresponds to a registered string table.
UFUNCTION ()) static 1 bool IsRegisteredTableEntry(const FName TableId
Returns true if the given table ID corresponds to a registered string table, and that table has.
UFUNCTION ()) static 1 FString GetTableEntryMetaData(const FName TableId
Returns the specified meta-data of the given string table entry (or an empty string).
UFUNCTION ()) static 1 FString GetTableEntrySourceString(const FName TableId
Returns the source string of the given string table entry (or an empty string).
UFUNCTION ()) static 1 FString GetTableNamespace(const FName TableId)
Returns the namespace of the given string table.
UFUNCTION ()) static 1 TArray< FName > GetMetaDataIdsFromStringTableEntry(const FName TableId
Returns an array of all meta-data IDs within the given string table entry.
UFUNCTION ()) static 1 TArray< FName > GetRegisteredStringTables()
Returns an array of all registered string table IDs.
UFUNCTION ()) static 1 TArray< FString > GetKeysFromStringTable(const FName TableId)
Returns an array of all keys within the given string table.
Private Attributes
const FString & Key
const FString const FName MetaDataId
Detailed Description
Definition at line 12 of file KismetStringTableLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UKismetStringTableLibrary::GENERATED_UCLASS_BODY () const private
Returns true if the given table ID corresponds to a registered string table.
References Category, meta, and UFUNCTION().
UFUNCTION() [1/7]
UKismetStringTableLibrary::UFUNCTION () const private
Returns true if the given table ID corresponds to a registered string table, and that table has.
References Category, meta, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/7]
UKismetStringTableLibrary::UFUNCTION () const private
Returns the specified meta-data of the given string table entry (or an empty string).
References Category, meta, and UFUNCTION().
UFUNCTION() [3/7]
UKismetStringTableLibrary::UFUNCTION () const private
Returns the source string of the given string table entry (or an empty string).
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [4/7]
UKismetStringTableLibrary::UFUNCTION () const private
Returns the namespace of the given string table.
References Category, meta, and UFUNCTION().
UFUNCTION() [5/7]
UKismetStringTableLibrary::UFUNCTION () const private
Returns an array of all meta-data IDs within the given string table entry.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [6/7]
UKismetStringTableLibrary::UFUNCTION () private
Returns an array of all registered string table IDs.
References Category, meta, and UFUNCTION().
UFUNCTION() [7/7]
UKismetStringTableLibrary::UFUNCTION () const private
Returns an array of all keys within the given string table.
References Category, meta, and UFUNCTION().
Field Documentation
Key
const FString & UKismetStringTableLibrary::Key private
Definition at line 22 of file KismetStringTableLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
MetaDataId
const FString const FName UKismetStringTableLibrary::MetaDataId private
Definition at line 34 of file KismetStringTableLibrary.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/KismetStringTableLibrary.h