Unreal Engine 5.6 C++ API: FPropertyLocalizationDataGatherer Class Reference
FPropertyLocalizationDataGatherer Class Reference
#include "PropertyLocalizationDataGathering.h"
Data Structures
struct FGatherableFieldsForType
struct FObjectAndGatherFlags
Public Types
typedef TFunction< void(const UObject *, FPropertyLocalizationDataGatherer &, const EPropertyLocalizationGathererTextFlags)> FLocalizationDataObjectGatheringCallback
typedef TMap< const UClass *, FLocalizationDataObjectGatheringCallback > FLocalizationDataObjectGatheringCallbackMap
typedef TFunction< void(const FString &, const UScriptStruct *, const void *, const void *, FPropertyLocalizationDataGatherer &, const EPropertyLocalizationGathererTextFlags)> FLocalizationDataStructGatheringCallback
typedef TMap< const UScriptStruct *, FLocalizationDataStructGatheringCallback > FLocalizationDataStructGatheringCallbackMap
Public Member Functions
FPropertyLocalizationDataGatherer (const FPropertyLocalizationDataGatherer &)=delete
FPropertyLocalizationDataGatherer (TArray< FGatherableTextData > &InOutGatherableTextDataArray, const UPackage *const InPackage, EPropertyLocalizationGathererResultFlags &OutResultFlags)
void GatherLocalizationDataFromChildTextProperties (const FString &PathToParent, const FProperty *const Property, const void *const ValueAddress, const void *const DefaultValueAddress, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherLocalizationDataFromObject (const UObject *Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherLocalizationDataFromObjectFields (const FString &PathToParent, const UObject *Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherLocalizationDataFromObjectWithCallbacks (const UObject *Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherLocalizationDataFromStruct (const FString &PathToParent, const UScriptStruct *Struct, const void *StructData, const void *DefaultStructData, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherLocalizationDataFromStructFields (const FString &PathToParent, const UStruct *Struct, const void *StructData, const void *DefaultStructData, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherLocalizationDataFromStructWithCallbacks (const FString &PathToParent, const UScriptStruct *Struct, const void *StructData, const void *DefaultStructData, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
void GatherScriptBytecode (const FString &PathToScript, const TArray< uint8 > &ScriptData, const bool bIsEditorOnly)
void GatherTextInstance (const FText &Text, const FString &Description, const bool bIsEditorOnly)
const FGatherableFieldsForType & GetGatherableFieldsForType (const UStruct *InType)
FORCEINLINE TArray< FGatherableTextData > & GetGatherableTextDataArray () const
bool IsDefaultTextInstance (const FText &Text) const
FORCEINLINE bool IsObjectValidForGather (const UObject *Object) const
void MarkDefaultTextInstance (const FText &Text)
void MarkObjectProcessed (const UObject *Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
FPropertyLocalizationDataGatherer & operator= (const FPropertyLocalizationDataGatherer &)=delete
bool ShouldProcessObject (const UObject *Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags) const
Static Public Member Functions
static bool ExtractTextIdentity (const FText &Text, FString &OutNamespace, FString &OutKey, const bool bCleanNamespace)
static FLocalizationDataObjectGatheringCallbackMap & GetTypeSpecificLocalizationDataObjectGatheringCallbacks ()
static FLocalizationDataStructGatheringCallbackMap & GetTypeSpecificLocalizationDataStructGatheringCallbacks ()
Private Member Functions
const FGatherableFieldsForType & CacheGatherableFieldsForType (const UStruct *InType)
bool CanGatherFromInnerProperty (const FProperty *InInnerProperty)
Private Attributes
TSet< const UObject * > AllObjectsInPackage
TSet< FObjectAndGatherFlags > BytecodePendingGather
TSet< FTextId > DefaultTextInstances
TMap< const UStruct *, TUniquePtr< FGatherableFieldsForType > > GatherableFieldsForTypes
TArray< FGatherableTextData > & GatherableTextDataArray
const UPackage * Package
FString PackageNamespace
TSet< FObjectAndGatherFlags > ProcessedObjects
EPropertyLocalizationGathererResultFlags & ResultFlags
Detailed Description
Definition at line 92 of file PropertyLocalizationDataGathering.h.
Member Typedef Documentation
FLocalizationDataObjectGatheringCallback
typedef TFunction<void(const UObject* , FPropertyLocalizationDataGatherer& , const EPropertyLocalizationGathererTextFlags)> FPropertyLocalizationDataGatherer::FLocalizationDataObjectGatheringCallback
Definition at line 95 of file PropertyLocalizationDataGathering.h.
FLocalizationDataObjectGatheringCallbackMap
typedef TMap<const UClass*, FLocalizationDataObjectGatheringCallback> FPropertyLocalizationDataGatherer::FLocalizationDataObjectGatheringCallbackMap
Definition at line 96 of file PropertyLocalizationDataGathering.h.
FLocalizationDataStructGatheringCallback
typedef TFunction<void(const FString& , const UScriptStruct* , const void* , const void* , FPropertyLocalizationDataGatherer& , const EPropertyLocalizationGathererTextFlags)> FPropertyLocalizationDataGatherer::FLocalizationDataStructGatheringCallback
Definition at line 98 of file PropertyLocalizationDataGathering.h.
FLocalizationDataStructGatheringCallbackMap
typedef TMap<const UScriptStruct*, FLocalizationDataStructGatheringCallback> FPropertyLocalizationDataGatherer::FLocalizationDataStructGatheringCallbackMap
Definition at line 99 of file PropertyLocalizationDataGathering.h.
Constructor & Destructor Documentation
FPropertyLocalizationDataGatherer() [1/2]
FPropertyLocalizationDataGatherer::FPropertyLocalizationDataGatherer (TArray< FGatherableTextData > & InOutGatherableTextDataArray, const UPackage *const InPackage, EPropertyLocalizationGathererResultFlags & OutResultFlags)
Referenced by FPropertyLocalizationDataGatherer(), and operator=().
FPropertyLocalizationDataGatherer() [2/2]
FPropertyLocalizationDataGatherer::FPropertyLocalizationDataGatherer (const FPropertyLocalizationDataGatherer &) delete
References FPropertyLocalizationDataGatherer().
Member Function Documentation
CacheGatherableFieldsForType()
const FGatherableFieldsForType & FPropertyLocalizationDataGatherer::CacheGatherableFieldsForType (const UStruct * InType) private
CanGatherFromInnerProperty()
bool FPropertyLocalizationDataGatherer::CanGatherFromInnerProperty (const FProperty * InInnerProperty) private
ExtractTextIdentity()
bool FPropertyLocalizationDataGatherer::ExtractTextIdentity (const FText & Text, FString & OutNamespace, FString & OutKey, const bool bCleanNamespace) static
References Text.
GatherLocalizationDataFromChildTextProperties()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromChildTextProperties (const FString & PathToParent, const FProperty *const Property, const void *const ValueAddress, const void *const DefaultValueAddress, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Property.
GatherLocalizationDataFromObject()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromObject (const UObject * Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Object.
GatherLocalizationDataFromObjectFields()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromObjectFields (const FString & PathToParent, const UObject * Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Object.
GatherLocalizationDataFromObjectWithCallbacks()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromObjectWithCallbacks (const UObject * Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Object.
GatherLocalizationDataFromStruct()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromStruct (const FString & PathToParent, const UScriptStruct * Struct, const void * StructData, const void * DefaultStructData, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Struct.
GatherLocalizationDataFromStructFields()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromStructFields (const FString & PathToParent, const UStruct * Struct, const void * StructData, const void * DefaultStructData, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Struct.
GatherLocalizationDataFromStructWithCallbacks()
void FPropertyLocalizationDataGatherer::GatherLocalizationDataFromStructWithCallbacks (const FString & PathToParent, const UScriptStruct * Struct, const void * StructData, const void * DefaultStructData, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Struct.
GatherScriptBytecode()
void FPropertyLocalizationDataGatherer::GatherScriptBytecode (const FString & PathToScript, const TArray< uint8 > & ScriptData, const bool bIsEditorOnly)
GatherTextInstance()
void FPropertyLocalizationDataGatherer::GatherTextInstance (const FText & Text, const FString & Description, const bool bIsEditorOnly)
References Text.
GetGatherableFieldsForType()
const FGatherableFieldsForType & FPropertyLocalizationDataGatherer::GetGatherableFieldsForType (const UStruct * InType)
GetGatherableTextDataArray()
FORCEINLINE TArray< FGatherableTextData > & FPropertyLocalizationDataGatherer::GetGatherableTextDataArray () const inline
Definition at line 149 of file PropertyLocalizationDataGathering.h.
References FORCEINLINE, and GatherableTextDataArray.
GetTypeSpecificLocalizationDataObjectGatheringCallbacks()
FLocalizationDataObjectGatheringCallbackMap & FPropertyLocalizationDataGatherer::GetTypeSpecificLocalizationDataObjectGatheringCallbacks () static
Referenced by FAutoRegisterLocalizationDataGatheringCallback::FAutoRegisterLocalizationDataGatheringCallback().
GetTypeSpecificLocalizationDataStructGatheringCallbacks()
FLocalizationDataStructGatheringCallbackMap & FPropertyLocalizationDataGatherer::GetTypeSpecificLocalizationDataStructGatheringCallbacks () static
Referenced by FAutoRegisterLocalizationDataGatheringCallback::FAutoRegisterLocalizationDataGatheringCallback().
IsDefaultTextInstance()
bool FPropertyLocalizationDataGatherer::IsDefaultTextInstance (const FText & Text) const
References Text.
IsObjectValidForGather()
FORCEINLINE bool FPropertyLocalizationDataGatherer::IsObjectValidForGather (const UObject * Object) const inline
Definition at line 154 of file PropertyLocalizationDataGathering.h.
References AllObjectsInPackage, FORCEINLINE, and Object.
MarkDefaultTextInstance()
void FPropertyLocalizationDataGatherer::MarkDefaultTextInstance (const FText & Text)
References Text.
MarkObjectProcessed()
void FPropertyLocalizationDataGatherer::MarkObjectProcessed (const UObject * Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags)
References Object.
operator=()
FPropertyLocalizationDataGatherer & FPropertyLocalizationDataGatherer::operator= (const FPropertyLocalizationDataGatherer &) delete
References FPropertyLocalizationDataGatherer().
ShouldProcessObject()
bool FPropertyLocalizationDataGatherer::ShouldProcessObject (const UObject * Object, const EPropertyLocalizationGathererTextFlags GatherTextFlags) const
References Object.
Field Documentation
AllObjectsInPackage
TSet<const UObject*> FPropertyLocalizationDataGatherer::AllObjectsInPackage private
Definition at line 200 of file PropertyLocalizationDataGathering.h.
Referenced by IsObjectValidForGather().
BytecodePendingGather
TSet<FObjectAndGatherFlags> FPropertyLocalizationDataGatherer::BytecodePendingGather private
Definition at line 202 of file PropertyLocalizationDataGathering.h.
DefaultTextInstances
TSet<FTextId> FPropertyLocalizationDataGatherer::DefaultTextInstances private
Definition at line 203 of file PropertyLocalizationDataGathering.h.
GatherableFieldsForTypes
TMap<const UStruct*, TUniquePtr<FGatherableFieldsForType> > FPropertyLocalizationDataGatherer::GatherableFieldsForTypes private
Definition at line 199 of file PropertyLocalizationDataGathering.h.
GatherableTextDataArray
TArray<FGatherableTextData>& FPropertyLocalizationDataGatherer::GatherableTextDataArray private
Definition at line 195 of file PropertyLocalizationDataGathering.h.
Referenced by GetGatherableTextDataArray().
Package
const UPackage* FPropertyLocalizationDataGatherer::Package private
Definition at line 196 of file PropertyLocalizationDataGathering.h.
PackageNamespace
FString FPropertyLocalizationDataGatherer::PackageNamespace private
Definition at line 197 of file PropertyLocalizationDataGathering.h.
ProcessedObjects
TSet<FObjectAndGatherFlags> FPropertyLocalizationDataGatherer::ProcessedObjects private
Definition at line 201 of file PropertyLocalizationDataGathering.h.
ResultFlags
EPropertyLocalizationGathererResultFlags& FPropertyLocalizationDataGatherer::ResultFlags private
Definition at line 198 of file PropertyLocalizationDataGathering.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/PropertyLocalizationDataGathering.h