Unreal Engine 5.6 C++ API: Metasound::TAudioReceiver< TDataType > Class Template Reference
Metasound::TAudioReceiver< TDataType > Class Template Reference
#include "MetasoundRouter.h"
Public Member Functions
TAudioReceiver (const FReceiverInitParams &InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, TArray< Audio::FPatchOutputStrongPtr > &&Outputs)
bool CanPop () const
bool Pop (TDataType &OutElement)
Public Member Functions inherited from Metasound::IReceiver
IReceiver (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType)
virtual METASOUNDFRONTEND_API ~IReceiver ()
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Static Public Member Functions
static FName GetDataTypeName ()
Private Attributes
TArray< Audio::FPatchOutputStrongPtr > DataChannelOutputs
FReceiverInitParams Params
Static Private Attributes
static constexpr float BufferResizeThreshold = 2.0f
static const int32 MaxChannels = 8
Additional Inherited Members
Protected Attributes inherited from Metasound::IReceiver
TSharedPtr< IDataChannel, ESPMode::ThreadSafe > DataChannel
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
template<typename TDataType>
class Metasound::TAudioReceiver< TDataType >
Definition at line 804 of file MetasoundRouter.h.
Constructor & Destructor Documentation
TAudioReceiver()
template<typename TDataType> Metasound::TAudioReceiver< TDataType >::TAudioReceiver (const FReceiverInitParams & InitParams, TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, TArray< Audio::FPatchOutputStrongPtr > && Outputs) inline
Definition at line 840 of file MetasoundRouter.h.
References Metasound::IReceiver::IReceiver(), DataChannelOutputs, GetDataTypeName(), MoveTemp(), and Params.
Member Function Documentation
CanPop()
template<typename TDataType> bool Metasound::TAudioReceiver< TDataType >::CanPop () const inline
Definition at line 810 of file MetasoundRouter.h.
GetDataTypeName()
template<typename TDataType> FName Metasound::TAudioReceiver< TDataType >::GetDataTypeName () inline static
Definition at line 835 of file MetasoundRouter.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by TAudioReceiver(), and Metasound::Downcast().
Pop()
template<typename TDataType> bool Metasound::TAudioReceiver< TDataType >::Pop (TDataType & OutElement) inline
Definition at line 817 of file MetasoundRouter.h.
References check, Metasound::IReceiver::DataChannel, DataChannelOutputs, Metasound::FAudioBuffer::GetData(), MaxChannels, and Metasound::FAudioBuffer::Num().
Field Documentation
BufferResizeThreshold
template<typename TDataType> float Metasound::TAudioReceiver< TDataType >::BufferResizeThreshold = 2.0f static constexpr private
Definition at line 806 of file MetasoundRouter.h.
DataChannelOutputs
template<typename TDataType> TArray<Audio::FPatchOutputStrongPtr> Metasound::TAudioReceiver< TDataType >::DataChannelOutputs private
Definition at line 849 of file MetasoundRouter.h.
Referenced by TAudioReceiver(), and Pop().
MaxChannels
template<typename TDataType> const int32 Metasound::TAudioReceiver< TDataType >::MaxChannels = 8 static private
Definition at line 807 of file MetasoundRouter.h.
Referenced by Pop().
Params
template<typename TDataType> FReceiverInitParams Metasound::TAudioReceiver< TDataType >::Params private
Definition at line 851 of file MetasoundRouter.h.
Referenced by TAudioReceiver().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h