Unreal Engine 5.6 C++ API: TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator Class Reference
TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator Class Reference
Const map iterator.
#include "SortedMap.h"
Public Member Functions
FORCEINLINE TConstIterator (const TSortedMap &InMap)
FORCEINLINE TConstIterator (const typename TBaseIterator< true >::PairItType &InPairIt)
Public Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
FORCEINLINE FSetElementId GetId () const
FORCEINLINE ItKeyType & Key () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
FORCEINLINE PairType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
FORCEINLINE PairType * operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
FORCEINLINE ItValueType & Value () const
Additional Inherited Members
Public Types inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
typedef std::conditional_t< bConst, typename ElementArrayType::TConstIterator, typename ElementArrayType::TIterator > PairItType
Protected Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
FORCEINLINE TBaseIterator (const PairItType &InElementIt)
Protected Attributes inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >
PairItType PairIt
Detailed Description
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate>
class TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator
Const map iterator.
Definition at line 769 of file SortedMap.h.
Constructor & Destructor Documentation
TConstIterator() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator::TConstIterator (const TSortedMap & InMap) inline nodiscard
Definition at line 772 of file SortedMap.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >::TBaseIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap, TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateConstIterator(), FORCEINLINE, and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Pairs.
TConstIterator() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator::TConstIterator (const typename TBaseIterator< true >::PairItType & InPairIt) inline nodiscard
Definition at line 777 of file SortedMap.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >::TBaseIterator(), and FORCEINLINE.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SortedMap.h