Unreal Engine 5.6 C++ API: UE::Tasks::Private::FTaskHandle Class Reference
UE::Tasks::Private::FTaskHandle Class Reference
#include "Task.h"
Public Types
using FTaskHandleId = void
Public Member Functions
FTaskHandle ()=default
EExtendedTaskPriority GetExtendedPriority () const
ETaskPriority GetPriority () const
bool IsAwaitable () const
bool IsCompleted () const
bool IsValid () const
PrerequisitesCollectionType void Launch (const TCHAR *DebugName, TaskBodyType &&TaskBody, PrerequisitesCollectionType &&Prerequisites, ETaskPriority Priority=ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority=EExtendedTaskPriority::None, ETaskFlags Flags=ETaskFlags::None)
bool operator!= (const FTaskHandle &Other) const
bool operator== (const FTaskHandle &Other) const
UE_DEPRECATED (5.5, "Use Wait instead.") bool BusyWait(FTimespan Timeout
bool Wait () const
bool Wait (FTimespan Timeout) const
Protected Member Functions
FTaskHandle (FTaskBase *Other)
Protected Attributes
TRefCountPtr< FTaskBase > Pimpl
Private Attributes
friend FTaskBase
Friends
template<typename TaskCollectionType>
TArray< TaskTrace::FId > GetTraceIds (const TaskCollectionType &Tasks)
template<int32 Index, typename ArrayType, typename FirstTaskType, typename... OtherTasksTypes>
void PrerequisitesUnpacker (ArrayType &Array, FirstTaskType &FirstTask, OtherTasksTypes &... OtherTasks)
template<int32 Index, typename ArrayType, typename TaskType>
void PrerequisitesUnpacker (ArrayType &Array, TaskType &FirstTask)
template<typename TaskCollectionType>
bool TryRetractAndExecute (const TaskCollectionType &Tasks, FTimeout Timeout)
template<typename TaskType>
void UE::Tasks::AddNested (const TaskType &Nested)
template<typename TaskCollectionType>
bool UE::Tasks::BusyWait (const TaskCollectionType &Tasks, FTimespan InTimeout)
template<typename TaskCollectionType>
bool UE::Tasks::Wait (const TaskCollectionType &Tasks, FTimespan InTimeout)
Detailed Description
Definition at line 33 of file Task.h.
Member Typedef Documentation
FTaskHandleId
using UE::Tasks::Private::FTaskHandle::FTaskHandleId = void
Definition at line 65 of file Task.h.
Constructor & Destructor Documentation
FTaskHandle() [1/2]
UE::Tasks::Private::FTaskHandle::FTaskHandle (FTaskBase * Other) inline explicit protected
Definition at line 60 of file Task.h.
References FTaskBase, Other, and Pimpl.
Referenced by UE::Tasks::FTaskEvent::FTaskEvent(), UE::Tasks::TTask< ResultType >::TTask(), UE::Tasks::TTask< void >::TTask(), operator!=(), and operator==().
FTaskHandle() [2/2]
UE::Tasks::Private::FTaskHandle::FTaskHandle () default
Member Function Documentation
GetExtendedPriority()
EExtendedTaskPriority UE::Tasks::Private::FTaskHandle::GetExtendedPriority () const inline
Definition at line 206 of file Task.h.
References Pimpl.
GetPriority()
ETaskPriority UE::Tasks::Private::FTaskHandle::GetPriority () const inline
Definition at line 201 of file Task.h.
References Pimpl.
IsAwaitable()
bool UE::Tasks::Private::FTaskHandle::IsAwaitable () const inline
Definition at line 186 of file Task.h.
References IsValid(), and Pimpl.
IsCompleted()
bool UE::Tasks::Private::FTaskHandle::IsCompleted () const inline
Definition at line 75 of file Task.h.
References IsValid(), and Pimpl.
Referenced by UE::Tasks::FTaskEvent::Trigger().
IsValid()
bool UE::Tasks::Private::FTaskHandle::IsValid () const inline
Definition at line 69 of file Task.h.
References Pimpl.
Referenced by UE::Tasks::TTask< ResultType >::GetResult(), and UE::Tasks::TTask< void >::GetResult().
Launch()
PrerequisitesCollectionType void UE::Tasks::Private::FTaskHandle::Launch (const TCHAR * DebugName, TaskBodyType && TaskBody, PrerequisitesCollectionType && Prerequisites, ETaskPriority Priority = ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority = EExtendedTaskPriority::None, ETaskFlags Flags = ETaskFlags::None) inline
Definition at line 167 of file Task.h.
References check, Flags, Forward(), IsValid(), UE::Tasks::None, Pimpl, and UE::Tasks::Prerequisites().
Referenced by UE::Tasks::Launch(), and UE::Tasks::Launch().
operator!=()
bool UE::Tasks::Private::FTaskHandle::operator!= (const FTaskHandle & Other) const inline
Definition at line 196 of file Task.h.
References FTaskHandle(), Other, and Pimpl.
operator==()
bool UE::Tasks::Private::FTaskHandle::operator== (const FTaskHandle & Other) const inline
Definition at line 191 of file Task.h.
References FTaskHandle(), Other, and Pimpl.
UE_DEPRECATED()
UE::Tasks::Private::FTaskHandle::UE_DEPRECATED (5. 5, "Use Wait instead.")
References bool, IsValid(), Pimpl, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, UE::Tasks::Timeout, and UE::Tasks::BusyWait.
Wait() [1/2]
bool UE::Tasks::Private::FTaskHandle::Wait () const inline
Definition at line 91 of file Task.h.
References IsValid(), and Pimpl.
Referenced by UE::Tasks::TTask< void >::GetResult().
Wait() [2/2]
bool UE::Tasks::Private::FTaskHandle::Wait (FTimespan Timeout) const inline
Definition at line 83 of file Task.h.
References IsValid(), Pimpl, and UE::Tasks::Timeout.
Referenced by UE::Tasks::Wait().
Friends And Related Symbol Documentation
GetTraceIds
template<typename TaskCollectionType> TArray< TaskTrace::FId > GetTraceIds (const TaskCollectionType & Tasks) friend
Definition at line 340 of file Task.h.
References TArray< InElementType, InAllocatorType >::Add(), and TArray< InElementType, InAllocatorType >::Reserve().
PrerequisitesUnpacker [1/2]
template<int32 Index, typename ArrayType, typename FirstTaskType, typename... OtherTasksTypes> void PrerequisitesUnpacker (ArrayType & Array, FirstTaskType & FirstTask, OtherTasksTypes &... OtherTasks) friend
Definition at line 397 of file Task.h.
References Array, and UE::Tasks::Private::PrerequisitesUnpacker().
PrerequisitesUnpacker [2/2]
template<int32 Index, typename ArrayType, typename TaskType> void PrerequisitesUnpacker (ArrayType & Array, TaskType & FirstTask) friend
Definition at line 404 of file Task.h.
References Array.
TryRetractAndExecute
template<typename TaskCollectionType> bool TryRetractAndExecute (const TaskCollectionType & Tasks, FTimeout Timeout) friend
Definition at line 1014 of file TaskPrivate.h.
References UE::Tasks::Timeout.
UE::Tasks::AddNested
template<typename TaskType> void UE::Tasks::AddNested (const TaskType & Nested) friend
UE::Tasks::BusyWait
template<typename TaskCollectionType> bool UE::Tasks::BusyWait (const TaskCollectionType & Tasks, FTimespan InTimeout) friend
References UE::Tasks::InTimeout.
Referenced by UE_DEPRECATED().
UE::Tasks::Wait
template<typename TaskCollectionType> bool UE::Tasks::Wait (const TaskCollectionType & Tasks, FTimespan InTimeout) friend
References UE::Tasks::InTimeout.
Field Documentation
FTaskBase
friend UE::Tasks::Private::FTaskHandle::FTaskBase private
Definition at line 36 of file Task.h.
Referenced by FTaskHandle().
Pimpl
TRefCountPtr<FTaskBase> UE::Tasks::Private::FTaskHandle::Pimpl protected
Definition at line 213 of file Task.h.
Referenced by FTaskHandle(), UE::Tasks::FTaskEvent::AddPrerequisites(), GetExtendedPriority(), GetPriority(), UE::Tasks::TTask< ResultType >::GetResult(), IsAwaitable(), IsCompleted(), IsValid(), Launch(), operator!=(), operator==(), UE::Tasks::FTaskEvent::Trigger(), UE_DEPRECATED(), Wait(), and Wait().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Tasks/Task.h