Unreal Engine 5.6 C++ API: UAnimNotify_PlayParticleEffect Class Reference
UAnimNotify_PlayParticleEffect Class Reference
#include "AnimNotify_PlayParticleEffect.h"
Public Member Functions
UPROPERTY() uint32 Attached UPROPERTY () FName SocketName
Protected Member Functions
virtual UParticleSystemComponent * SpawnParticleSystem (USkeletalMeshComponent *MeshComp, UAnimSequenceBase *Animation)
Private Member Functions
virtual FString GetNotifyName_Implementation () const override
virtual void Notify (USkeletalMeshComponent *MeshComp, UAnimSequenceBase *Animation, const FAnimNotifyEventReference &EventReference) override
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual GENERATED_BODY() public void PostLoad () override
UE_DEPRECATED (5.0, "Please use the other Notify function instead") 1 virtual void Notify(USkeletalMeshComponent *MeshComp
UPROPERTY () FRotator RotationOffset
UPROPERTY () FVector LocationOffset
UPROPERTY () FVector Scale
UPROPERTY ()) TObjectPtr< UParticleSystem > PSTemplate
virtual void ValidateAssociatedAssets () override
Private Attributes
UAnimSequenceBase *Animation override
FQuat RotationOffsetQuat
Detailed Description
Definition at line 17 of file AnimNotify_PlayParticleEffect.h.
Member Function Documentation
GetNotifyName_Implementation()
virtual FString UAnimNotify_PlayParticleEffect::GetNotifyName_Implementation () const override private virtual
Notify()
virtual void UAnimNotify_PlayParticleEffect::Notify (USkeletalMeshComponent * MeshComp, UAnimSequenceBase * Animation, const FAnimNotifyEventReference & EventReference) override private virtual
References Animation, Notify(), and override.
Referenced by Notify().
PostEditChangeProperty()
virtual void UAnimNotify_PlayParticleEffect::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostLoad()
virtual GENERATED_BODY() public void UAnimNotify_PlayParticleEffect::PostLoad () override private virtual
SpawnParticleSystem()
virtual UParticleSystemComponent * UAnimNotify_PlayParticleEffect::SpawnParticleSystem (USkeletalMeshComponent * MeshComp, UAnimSequenceBase * Animation) protected virtual
References Animation, Category, SpawnParticleSystem(), and UPROPERTY().
Referenced by SpawnParticleSystem().
UE_DEPRECATED()
UAnimNotify_PlayParticleEffect::UE_DEPRECATED (5. 0, "Please use the other Notify function instead") private
UPROPERTY() [1/5]
UPROPERTY() uint32 Attached UAnimNotify_PlayParticleEffect::UPROPERTY ()
References Category, and UPROPERTY().
UPROPERTY() [2/5]
UAnimNotify_PlayParticleEffect::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [3/5]
UAnimNotify_PlayParticleEffect::UPROPERTY () private
References Category, FVector, and UPROPERTY().
UPROPERTY() [4/5]
UAnimNotify_PlayParticleEffect::UPROPERTY () private
References Category, FVector, Scale, and UPROPERTY().
UPROPERTY() [5/5]
UAnimNotify_PlayParticleEffect::UPROPERTY () private
References Category, and meta.
Referenced by SpawnParticleSystem(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
ValidateAssociatedAssets()
virtual void UAnimNotify_PlayParticleEffect::ValidateAssociatedAssets () override private virtual
Field Documentation
override
UAnimSequenceBase* Animation UAnimNotify_PlayParticleEffect::override private
Definition at line 36 of file AnimNotify_PlayParticleEffect.h.
Referenced by Notify().
RotationOffsetQuat
FQuat UAnimNotify_PlayParticleEffect::RotationOffsetQuat private
Definition at line 61 of file AnimNotify_PlayParticleEffect.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Animation/AnimNotifies/AnimNotify_PlayParticleEffect.h