Unreal Engine 5.6 C++ API: FCanvasTileRendererItem Class Reference
FCanvasTileRendererItem Class Reference
Info needed to render a single FTileRenderer.
#include "CanvasRendererItem.h"
Data Structures
class FRenderData
class FTileVertexFactory
Public Member Functions
FCanvasTileRendererItem (ERHIFeatureLevel::Type InFeatureLevel, const FMaterialRenderProxy *InMaterialRenderProxy=NULL, const FCanvas::FTransformEntry &InTransform=FCanvas::FTransformEntry(FMatrix::Identity), bool bInFreezeTime=false)
Init constructor.
int32 AddTile (float X, float Y, float SizeX, float SizeY, float U, float V, float SizeU, float SizeV, FHitProxyId HitProxyId, FColor InColor)
Add a new tile to the render data.
virtual class FCanvasTileRendererItem * GetCanvasTileRendererItem () override
FCanvasTileRendererItem instance accessor.
bool IsMatch (const FMaterialRenderProxy *InMaterialRenderProxy, const FCanvas::FTransformEntry &InTransform)
Determine if this is a matching set by comparing material,transform.
virtual bool Render_GameThread (const FCanvas *Canvas, FCanvasRenderThreadScope &RenderScope) override
Renders the canvas item.
virtual bool Render_RenderThread (FCanvasRenderContext &RenderContext, FMeshPassProcessorRenderState &DrawRenderState, const FCanvas *Canvas) override
Renders the canvas item.
Public Member Functions inherited from FCanvasBaseRenderItem
virtual ~FCanvasBaseRenderItem ()
virtual class FCanvasBatchedElementRenderItem * GetCanvasBatchedElementRenderItem ()
FCanvasBatchedElementRenderItem instance accessor.
virtual class FCanvasTriangleRendererItem * GetCanvasTriangleRendererItem ()
FCanvasTriangleRendererItem instance accessor.
Private Attributes
const bool bFreezeTime
TSharedPtr< FRenderData > Data
Render data which is allocated when a new FCanvasTileRendererItem is added for rendering.
Detailed Description
Info needed to render a single FTileRenderer.
Definition at line 12 of file CanvasRendererItem.h.
Constructor & Destructor Documentation
FCanvasTileRendererItem()
FCanvasTileRendererItem::FCanvasTileRendererItem (ERHIFeatureLevel::Type InFeatureLevel, const FMaterialRenderProxy * InMaterialRenderProxy = NULL, const FCanvas::FTransformEntry & InTransform = FCanvas::FTransformEntry(FMatrix::Identity), bool bInFreezeTime = false) inline
Init constructor.
Definition at line 18 of file CanvasRendererItem.h.
References bFreezeTime, Data, UE::Math::TMatrix< double >::Identity, and MakeShared().
Referenced by GetCanvasTileRendererItem().
Member Function Documentation
AddTile()
int32 FCanvasTileRendererItem::AddTile (float X, float Y, float SizeX, float SizeY, float U, float V, float SizeU, float SizeV, FHitProxyId HitProxyId, FColor InColor) inline
Add a new tile to the render data.
These tiles all use the same transform and material proxy
Parameters
X - tile X offset
Y - tile Y offset
SizeX - tile X size
SizeY - tile Y size
U - tile U offset
V - tile V offset
SizeU - tile U size
SizeV - tile V size
return number of tiles added
Definition at line 82 of file CanvasRendererItem.h.
References Data, FORCEINLINE, X, and Y.
GetCanvasTileRendererItem()
virtual class FCanvasTileRendererItem * FCanvasTileRendererItem::GetCanvasTileRendererItem () inline override virtual
FCanvasTileRendererItem instance accessor.
Returns
this instance
Reimplemented from FCanvasBaseRenderItem.
Definition at line 32 of file CanvasRendererItem.h.
References FCanvasTileRendererItem().
IsMatch()
bool FCanvasTileRendererItem::IsMatch (const FMaterialRenderProxy * InMaterialRenderProxy, const FCanvas::FTransformEntry & InTransform) inline
Determine if this is a matching set by comparing material,transform.
All must match
Parameters
IInMaterialRenderProxy - material proxy resource for the item being rendered
InTransform - the transform for the item being rendered
Returns
true if the parameters match this render item
Definition at line 63 of file CanvasRendererItem.h.
References Data, and FCanvas::FTransformEntry::GetMatrixCRC().
Render_GameThread()
virtual bool FCanvasTileRendererItem::Render_GameThread (const FCanvas * Canvas, FCanvasRenderThreadScope & RenderScope) override virtual
Renders the canvas item.
Iterates over each tile to be rendered and draws it with its own transforms
Parameters
Canvas - canvas currently being rendered
Returns
true if anything rendered
Implements FCanvasBaseRenderItem.
Render_RenderThread()
virtual bool FCanvasTileRendererItem::Render_RenderThread (FCanvasRenderContext & RenderContext, FMeshPassProcessorRenderState & DrawRenderState, const FCanvas * Canvas) override virtual
Renders the canvas item.
Iterates over each tile to be rendered and draws it with its own transforms
Parameters
Canvas - canvas currently being rendered
RHICmdList - command list to use
Returns
true if anything rendered
Implements FCanvasBaseRenderItem.
Field Documentation
bFreezeTime
const bool FCanvasTileRendererItem::bFreezeTime private
Definition at line 154 of file CanvasRendererItem.h.
Referenced by FCanvasTileRendererItem().
Data
TSharedPtr<FRenderData> FCanvasTileRendererItem::Data private
Render data which is allocated when a new FCanvasTileRendererItem is added for rendering.
This data is only freed on the rendering thread once the item has finished rendering
Definition at line 152 of file CanvasRendererItem.h.
Referenced by FCanvasTileRendererItem(), AddTile(), and IsMatch().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/CanvasRendererItem.h