Unreal Engine 5.6 C++ API: ISlateViewport Class Reference
ISlateViewport Class Reference abstract
Viewport implementation interface that is used by SViewport when it needs to draw and processes input.
#include "RenderingCommon.h"
Public Member Functions
virtual ~ISlateViewport ()
virtual bool AllowScaling () const
Whether the viewport contents should be scaled or not.
virtual EPixelFormat GetSceneTargetFormat () const
Returns format for the scene of this viewport, only valid if this viewport actually has a scene, else PF_Unknown.
virtual FIntPoint GetSize () const =0
Returns the size of the viewport.
virtual FVector2D GetSoftwareCursorPosition () const
Returns the current position of the software cursor.
virtual ESlateViewportDynamicRange GetViewportDynamicRange () const
Does the texture contain SDR/HDR information.
virtual class FSlateShaderResource * GetViewportRenderTargetTexture () const =0
Returns a slate texture used to draw the rendered viewport in Slate.
virtual TWeakPtr< SWidget > GetWidget ()
Gets the SWidget associated with this viewport.
virtual bool HandleNavigation (const uint32 InUserIndex, TSharedPtr< SWidget > InDestination)
Give the viewport an opportunity to override the navigation behavior.
virtual bool IsSoftwareCursorVisible () const
Returns whether the software cursor is currently visible.
virtual bool IsStereoscopic3D () const
Does the texture returned by GetViewportRenderTargetTexture represent a stereoscopic 3D target?
virtual bool IsViewportTextureAlphaOnly () const
Does the texture returned by GetViewportRenderTargetTexture only have an alpha channel?
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent)
Called when Slate needs to know what the mouse cursor should be.
virtual void OnDrawViewport (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, class FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled)
Called by Slate when the viewport widget is drawn Implementers of this interface can use this method to perform custom per draw functionality.
virtual void OnFinishedPointerInput ()
Called after all input for this frame is processed.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when the viewport loses keyboard focus.
virtual FReply OnFocusReceived (const FFocusEvent &InFocusEvent)
Called when the viewport gains keyboard focus.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called by Slate when a character key is pressed while the viewport has focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called by Slate when a key is pressed inside the viewport.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called by Slate when a key is released inside the viewport.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply)
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called by Slate when the mouse wheel is used inside the viewport.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called by Slate when a mouse button is pressed inside the viewport.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called by Slate when a mouse button is released inside the viewport.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called by Slate when a mouse button is released inside the viewport.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called by Slate when the mouse wheel is used inside the viewport.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FPopupMethodReply OnQueryPopupMethod () const
Called to figure out whether we can make new windows for popups within this viewport.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual FReply OnRequestWindowClose ()
Called when the top level window associated with the viewport has been requested to close.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch has first moved after initial press.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch force changes, but may or may not have moved.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &InGestureEvent)
Called on a touchpad gesture event.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual FReply OnViewportActivated (const FWindowActivateEvent &InActivateEvent)
Called when the viewports top level window is being Activated.
virtual void OnViewportClosed ()
Called when the viewport has been requested to close.
virtual void OnViewportDeactivated (const FWindowActivateEvent &InActivateEvent)
Called when the viewports top level window is being Deactivated.
virtual bool RequiresVsync () const =0
Returns true if the viewport should be vsynced.
virtual void Tick (const FGeometry &AllottedGeometry, double InCurrentTime, float DeltaTime)
Performs any ticking necessary by this handle.
virtual bool UseSeparateRenderTarget () const
Is the viewport expected to render to GetViewportRenderTargetTexture?
Detailed Description
Viewport implementation interface that is used by SViewport when it needs to draw and processes input.
Definition at line 470 of file RenderingCommon.h.
Constructor & Destructor Documentation
~ISlateViewport()
virtual ISlateViewport::~ISlateViewport () inline virtual
Definition at line 473 of file RenderingCommon.h.
Member Function Documentation
AllowScaling()
virtual bool ISlateViewport::AllowScaling () const inline virtual
Whether the viewport contents should be scaled or not.
Defaults to true.
Reimplemented in FAudioSpectrogramViewport.
Definition at line 546 of file RenderingCommon.h.
GetSceneTargetFormat()
virtual EPixelFormat ISlateViewport::GetSceneTargetFormat () const inline virtual
Returns format for the scene of this viewport, only valid if this viewport actually has a scene, else PF_Unknown.
Reimplemented in FSceneViewport.
Definition at line 497 of file RenderingCommon.h.
References PF_Unknown.
GetSize()
virtual FIntPoint ISlateViewport::GetSize () const pure virtual
Returns the size of the viewport.
Implemented in FAssetThumbnail, FAudioSpectrogramViewport, FSceneViewport, and FTrackEditorThumbnail.
GetSoftwareCursorPosition()
virtual FVector2D ISlateViewport::GetSoftwareCursorPosition () const inline virtual
Returns the current position of the software cursor.
Reimplemented in FSceneViewport.
Definition at line 582 of file RenderingCommon.h.
References UE::Math::TVector2< double >::ZeroVector.
GetViewportDynamicRange()
virtual ESlateViewportDynamicRange ISlateViewport::GetViewportDynamicRange () const inline virtual
Does the texture contain SDR/HDR information.
Reimplemented in FSceneViewport.
Definition at line 526 of file RenderingCommon.h.
References SDR.
GetViewportRenderTargetTexture()
virtual class FSlateShaderResource * ISlateViewport::GetViewportRenderTargetTexture () const pure virtual
Returns a slate texture used to draw the rendered viewport in Slate.
Implemented in FAssetThumbnail, FAudioSpectrogramViewport, FSceneViewport, and FTrackEditorThumbnail.
GetWidget()
virtual TWeakPtr< SWidget > ISlateViewport::GetWidget () inline virtual
Gets the SWidget associated with this viewport.
Reimplemented in FSceneViewport.
Definition at line 878 of file RenderingCommon.h.
HandleNavigation()
virtual bool ISlateViewport::HandleNavigation (const uint32 InUserIndex, TSharedPtr< SWidget > InDestination) inline virtual
Give the viewport an opportunity to override the navigation behavior.
This is called after all the navigation event bubbling is complete and we know a destination.
Parameters
InDestination The destination widget
Returns
whether we handled the navigation
Reimplemented in FSceneViewport.
Definition at line 840 of file RenderingCommon.h.
IsSoftwareCursorVisible()
virtual bool ISlateViewport::IsSoftwareCursorVisible () const inline virtual
Returns whether the software cursor is currently visible.
Reimplemented in FSceneViewport.
Definition at line 574 of file RenderingCommon.h.
IsStereoscopic3D()
virtual bool ISlateViewport::IsStereoscopic3D () const inline virtual
Does the texture returned by GetViewportRenderTargetTexture represent a stereoscopic 3D target?
Definition at line 510 of file RenderingCommon.h.
IsViewportTextureAlphaOnly()
virtual bool ISlateViewport::IsViewportTextureAlphaOnly () const inline virtual
Does the texture returned by GetViewportRenderTargetTexture only have an alpha channel?
Definition at line 502 of file RenderingCommon.h.
OnAnalogValueChanged()
virtual FReply ISlateViewport::OnAnalogValueChanged (const FGeometry & MyGeometry, const FAnalogInputEvent & InAnalogInputEvent) inline virtual
Called when an analog value changes on a button that supports analog.
Parameters
MyGeometry The Geometry of the widget receiving the event
InAnalogInputEvent Analog input event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in FSceneViewport.
Definition at line 696 of file RenderingCommon.h.
References FReply::Unhandled().
OnCursorQuery()
virtual FCursorReply ISlateViewport::OnCursorQuery (const FGeometry & MyGeometry, const FPointerEvent & CursorEvent) inline virtual
Called when Slate needs to know what the mouse cursor should be.
Returns
FCursorReply::Unhandled() if the event is not handled; FCursorReply::Cursor() otherwise.
Reimplemented in FSceneViewport.
Definition at line 556 of file RenderingCommon.h.
References FCursorReply::Unhandled().
OnDrawViewport()
virtual void ISlateViewport::OnDrawViewport (const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, class FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) inline virtual
Called by Slate when the viewport widget is drawn Implementers of this interface can use this method to perform custom per draw functionality.
This is only called if the widget is visible
Parameters
AllottedGeometry The geometry of the viewport widget
Reimplemented in FSceneViewport.
Definition at line 482 of file RenderingCommon.h.
OnFinishedPointerInput()
virtual void ISlateViewport::OnFinishedPointerInput () inline virtual
Called after all input for this frame is processed.
Reimplemented in FSceneViewport.
Definition at line 808 of file RenderingCommon.h.
OnFocusLost()
virtual void ISlateViewport::OnFocusLost (const FFocusEvent & InFocusEvent) inline virtual
Called when the viewport loses keyboard focus.
Parameters
InFocusEvent Information about what caused the viewport to lose focus
Reimplemented in FSceneViewport.
Definition at line 850 of file RenderingCommon.h.
OnFocusReceived()
virtual FReply ISlateViewport::OnFocusReceived (const FFocusEvent & InFocusEvent) inline virtual
Called when the viewport gains keyboard focus.
Parameters
InFocusEvent Information about what caused the viewport to gain focus
Reimplemented in FSceneViewport.
Definition at line 719 of file RenderingCommon.h.
References FReply::Unhandled().
OnKeyChar()
virtual FReply ISlateViewport::OnKeyChar (const FGeometry & MyGeometry, const FCharacterEvent & InCharacterEvent) inline virtual
Called by Slate when a character key is pressed while the viewport has focus.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the character that was pressed
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 709 of file RenderingCommon.h.
References FReply::Unhandled().
OnKeyDown()
virtual FReply ISlateViewport::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline virtual
Called by Slate when a key is pressed inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the key event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 671 of file RenderingCommon.h.
References FReply::Unhandled().
OnKeyUp()
virtual FReply ISlateViewport::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline virtual
Called by Slate when a key is released inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the key event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 684 of file RenderingCommon.h.
References FReply::Unhandled().
OnMapCursor()
virtual TOptional< TSharedRef< SWidget > > ISlateViewport::OnMapCursor (const FCursorReply & CursorReply) inline virtual
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
This event is bubbled.
Returns
TOptional<TSharedRef<SWidget>>() if you don't have a mapping otherwise return the Widget to show.
Reimplemented in FSceneViewport.
Definition at line 566 of file RenderingCommon.h.
OnMotionDetected()
virtual FReply ISlateViewport::OnMotionDetected (const FGeometry & MyGeometry, const FMotionEvent & InMotionEvent) inline virtual
Called when motion is detected (controller or device) e.g.
Someone tilts or shakes their controller.
Parameters
InMotionEvent The motion event generated
Reimplemented in FSceneViewport.
Definition at line 790 of file RenderingCommon.h.
References FReply::Unhandled().
OnMouseButtonDoubleClick()
virtual FReply ISlateViewport::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) inline virtual
Called by Slate when the mouse wheel is used inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the mouse event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 658 of file RenderingCommon.h.
References FReply::Unhandled().
OnMouseButtonDown()
virtual FReply ISlateViewport::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Called by Slate when a mouse button is pressed inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the mouse event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 595 of file RenderingCommon.h.
References MouseEvent, and FReply::Unhandled().
OnMouseButtonUp()
virtual FReply ISlateViewport::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Called by Slate when a mouse button is released inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the mouse event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 608 of file RenderingCommon.h.
References MouseEvent, and FReply::Unhandled().
OnMouseEnter()
virtual void ISlateViewport::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Reimplemented in FSceneViewport.
Definition at line 614 of file RenderingCommon.h.
References MouseEvent.
OnMouseLeave()
virtual void ISlateViewport::OnMouseLeave (const FPointerEvent & MouseEvent) inline virtual
Reimplemented in FSceneViewport.
Definition at line 619 of file RenderingCommon.h.
References MouseEvent.
OnMouseMove()
virtual FReply ISlateViewport::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Called by Slate when a mouse button is released inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the mouse event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 632 of file RenderingCommon.h.
References MouseEvent, and FReply::Unhandled().
OnMouseWheel()
virtual FReply ISlateViewport::OnMouseWheel (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Called by Slate when the mouse wheel is used inside the viewport.
Parameters
MyGeometry Information about the location and size of the viewport
MouseEvent Information about the mouse event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FSceneViewport.
Definition at line 645 of file RenderingCommon.h.
References MouseEvent, and FReply::Unhandled().
OnNavigation()
virtual FNavigationReply ISlateViewport::OnNavigation (const FGeometry & MyGeometry, const FNavigationEvent & InNavigationEvent) inline virtual
Called when navigation is requested e.g.
Left Joystick, Direction Pad, Arrow Keys can generate navigation events.
Parameters
InNavigationEvent The navigation event generated
Definition at line 828 of file RenderingCommon.h.
References FNavigationReply::Stop().
OnQueryPopupMethod()
virtual FPopupMethodReply ISlateViewport::OnQueryPopupMethod () const inline virtual
Called to figure out whether we can make new windows for popups within this viewport.
Making windows allows us to have popups that go outside the parent window, but cannot be used in fullscreen and do not have per-pixel alpha.
Reimplemented in FSceneViewport.
Definition at line 817 of file RenderingCommon.h.
References FPopupMethodReply::Unhandled().
OnQueryShowFocus()
virtual TOptional< bool > ISlateViewport::OnQueryShowFocus (const EFocusCause InFocusCause) const inline virtual
Called to determine if we should render the focus brush.
Parameters
InFocusCause The cause of focus
Reimplemented in FSceneViewport.
Definition at line 800 of file RenderingCommon.h.
OnRequestWindowClose()
virtual FReply ISlateViewport::OnRequestWindowClose () inline virtual
Called when the top level window associated with the viewport has been requested to close.
At this point, the viewport has not been closed and the operation may be canceled. This may not called from PIE, Editor Windows, on consoles, or before the game ends from other methods. This is only when the platform specific window is closed.
Returns
FReply::Handled if the close event was consumed (and the window should remain open).
Reimplemented in FSceneViewport.
Definition at line 863 of file RenderingCommon.h.
References FReply::Unhandled().
OnTouchEnded()
virtual FReply ISlateViewport::OnTouchEnded (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) inline virtual
Called when a touchpad touch is ended (finger lifted)
Parameters
ControllerEvent The controller event generated
Reimplemented in FSceneViewport.
Definition at line 749 of file RenderingCommon.h.
References FReply::Unhandled().
OnTouchFirstMove()
virtual FReply ISlateViewport::OnTouchFirstMove (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) inline virtual
Called when a touchpad touch has first moved after initial press.
Parameters
ControllerEvent The controller event generated
Reimplemented in FSceneViewport.
Definition at line 769 of file RenderingCommon.h.
References FReply::Unhandled().
OnTouchForceChanged()
virtual FReply ISlateViewport::OnTouchForceChanged (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) inline virtual
Called when a touchpad touch force changes, but may or may not have moved.
Parameters
ControllerEvent The controller event generated
Reimplemented in FSceneViewport.
Definition at line 759 of file RenderingCommon.h.
References FReply::Unhandled().
OnTouchGesture()
virtual FReply ISlateViewport::OnTouchGesture (const FGeometry & MyGeometry, const FPointerEvent & InGestureEvent) inline virtual
Called on a touchpad gesture event.
Parameters
InGestureEvent The touch event generated
Reimplemented in FSceneViewport.
Definition at line 779 of file RenderingCommon.h.
References FReply::Unhandled().
OnTouchMoved()
virtual FReply ISlateViewport::OnTouchMoved (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) inline virtual
Called when a touchpad touch is moved (finger moved)
Parameters
ControllerEvent The controller event generated
Reimplemented in FSceneViewport.
Definition at line 739 of file RenderingCommon.h.
References FReply::Unhandled().
OnTouchStarted()
virtual FReply ISlateViewport::OnTouchStarted (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) inline virtual
Called when a touchpad touch is started (finger down)
Parameters
ControllerEvent The controller event generated
Reimplemented in FSceneViewport.
Definition at line 729 of file RenderingCommon.h.
References FReply::Unhandled().
OnViewportActivated()
virtual FReply ISlateViewport::OnViewportActivated (const FWindowActivateEvent & InActivateEvent) inline virtual
Called when the viewports top level window is being Activated.
Reimplemented in FSceneViewport.
Definition at line 886 of file RenderingCommon.h.
References FReply::Unhandled().
OnViewportClosed()
virtual void ISlateViewport::OnViewportClosed () inline virtual
Called when the viewport has been requested to close.
Reimplemented in FSceneViewport.
Definition at line 871 of file RenderingCommon.h.
OnViewportDeactivated()
virtual void ISlateViewport::OnViewportDeactivated (const FWindowActivateEvent & InActivateEvent) inline virtual
Called when the viewports top level window is being Deactivated.
Reimplemented in FSceneViewport.
Definition at line 894 of file RenderingCommon.h.
RequiresVsync()
virtual bool ISlateViewport::RequiresVsync () const pure virtual
Returns true if the viewport should be vsynced.
Implemented in FAssetThumbnail, FAudioSpectrogramViewport, FSceneViewport, and FTrackEditorThumbnail.
Tick()
virtual void ISlateViewport::Tick (const FGeometry & AllottedGeometry, double InCurrentTime, float DeltaTime) inline virtual
Performs any ticking necessary by this handle.
Reimplemented in FSceneViewport.
Definition at line 534 of file RenderingCommon.h.
References DeltaTime.
UseSeparateRenderTarget()
virtual bool ISlateViewport::UseSeparateRenderTarget () const inline virtual
Is the viewport expected to render to GetViewportRenderTargetTexture?
Or to the swapchain?
Definition at line 518 of file RenderingCommon.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Rendering/RenderingCommon.h