Unreal Engine 5.6 C++ API: FCustomVersionRegistration Class Reference
FCustomVersionRegistration Class Reference
This class will cause the registration of a custom version number and key with the global FCustomVersionContainer when instantiated, and unregister when destroyed.
#include "CustomVersion.h"
Public Member Functions
template<int N>
FCustomVersionRegistration (FGuid InKey, int32 Version, const TCHAR(&InFriendlyName)[N], CustomVersionValidatorFunc InValidatorFunc=nullptr)
~FCustomVersionRegistration ()
Private Attributes
FGuid Key
Additional Inherited Members
Private Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Detailed Description
This class will cause the registration of a custom version number and key with the global FCustomVersionContainer when instantiated, and unregister when destroyed.
It should be instantiated as a global variable somewhere in the module which needs a custom version number.
Definition at line 219 of file CustomVersion.h.
Constructor & Destructor Documentation
FCustomVersionRegistration()
template<int N> FCustomVersionRegistration::FCustomVersionRegistration (FGuid InKey, int32 Version, const TCHAR(&) InFriendlyName[N], CustomVersionValidatorFunc InValidatorFunc = nullptr) inline
Parameters
InFriendlyName must be a string literal
Definition at line 224 of file CustomVersion.h.
References Key, and FCurrentCustomVersions::Register().
Referenced by FDevVersionRegistration::FDevVersionRegistration().
~FCustomVersionRegistration()
FCustomVersionRegistration::~FCustomVersionRegistration () inline
Definition at line 230 of file CustomVersion.h.
References Key, and FCurrentCustomVersions::Unregister().
Field Documentation
Key
FGuid FCustomVersionRegistration::Key private
Definition at line 236 of file CustomVersion.h.
Referenced by FCustomVersionRegistration(), ~FCustomVersionRegistration(), and FDevVersionRegistration::RecordDevVersion().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CustomVersion.h