Unreal Engine 5.6 C++ API: TSparseArray< InElementType, Allocator >::TBaseIterator< bConst > Class Template Reference
TSparseArray< InElementType, Allocator >::TBaseIterator< bConst > Class Template Reference
The base class of sparse array iterators.
Public Types
typedef TConstSetBitIterator< typename Allocator::BitArrayAllocator > BitArrayItType
Public Member Functions
TBaseIterator (ArrayType &InArray, const BitArrayItType &InBitArrayIt)
FORCEINLINE int32 GetIndex () const
FORCEINLINE const FRelativeBitReference & GetRelativeBitReference () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
FORCEINLINE ItElementType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
FORCEINLINE ItElementType * operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
Protected Attributes
ArrayType & Array
BitArrayItType BitArrayIt
Private Types
typedef std::conditional_t< bConst, const TSparseArray, TSparseArray > ArrayType
typedef std::conditional_t< bConst, const ElementType, ElementType > ItElementType
Detailed Description
template<typename InElementType, typename Allocator>
template<bool bConst>
class TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >
The base class of sparse array iterators.
Definition at line 942 of file SparseArray.h.
Member Typedef Documentation
ArrayType
template<typename InElementType, typename Allocator> template<bool bConst> typedef std::conditional_t<bConst,const TSparseArray,TSparseArray> TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::ArrayType private
Definition at line 948 of file SparseArray.h.
BitArrayItType
template<typename InElementType, typename Allocator> template<bool bConst> typedef TConstSetBitIterator<typename Allocator::BitArrayAllocator> TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::BitArrayItType
Definition at line 945 of file SparseArray.h.
ItElementType
template<typename InElementType, typename Allocator> template<bool bConst> typedef std::conditional_t<bConst,const ElementType,ElementType> TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::ItElementType private
Definition at line 949 of file SparseArray.h.
Constructor & Destructor Documentation
TBaseIterator()
template<typename InElementType, typename Allocator> template<bool bConst> TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::TBaseIterator (ArrayType & InArray, const BitArrayItType & InBitArrayIt) inline explicit nodiscard
Definition at line 952 of file SparseArray.h.
References Array, and BitArrayIt.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
GetIndex()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE int32 TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::GetIndex () const inline nodiscard
Definition at line 965 of file SparseArray.h.
References BitArrayIt, and FORCEINLINE.
Referenced by operator*(), and operator->().
GetRelativeBitReference()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE const FRelativeBitReference & TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::GetRelativeBitReference () const inline nodiscard
Definition at line 999 of file SparseArray.h.
References BitArrayIt, and FORCEINLINE.
operator bool()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator bool () const inline explicit nodiscard
conversion to "bool" returning true if the iterator is valid.
Definition at line 980 of file SparseArray.h.
References BitArrayIt, and FORCEINLINE.
operator!()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE bool TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator! () const inline nodiscard
inverse of the "bool" operator
Definition at line 986 of file SparseArray.h.
References bool, and FORCEINLINE.
operator!=()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE bool TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator!= (const TBaseIterator< bConst > & Rhs) const inline nodiscard
Definition at line 974 of file SparseArray.h.
References TBaseIterator(), Array, BitArrayIt, and FORCEINLINE.
operator*()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE ItElementType & TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator* () const inline nodiscard
Definition at line 991 of file SparseArray.h.
References Array, FORCEINLINE, and GetIndex().
operator++()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE TBaseIterator & TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator++ () inline
Definition at line 958 of file SparseArray.h.
References TBaseIterator(), BitArrayIt, and FORCEINLINE.
operator->()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE ItElementType * TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator-> () const inline nodiscard
Definition at line 995 of file SparseArray.h.
References Array, FORCEINLINE, and GetIndex().
operator==()
template<typename InElementType, typename Allocator> template<bool bConst> FORCEINLINE bool TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::operator== (const TBaseIterator< bConst > & Rhs) const inline nodiscard
Definition at line 970 of file SparseArray.h.
References TBaseIterator(), Array, BitArrayIt, and FORCEINLINE.
Field Documentation
Array
template<typename InElementType, typename Allocator> template<bool bConst> ArrayType& TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::Array protected
Definition at line 1005 of file SparseArray.h.
Referenced by TBaseIterator(), operator!=(), operator*(), operator->(), and operator==().
BitArrayIt
template<typename InElementType, typename Allocator> template<bool bConst> BitArrayItType TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >::BitArrayIt protected
Definition at line 1006 of file SparseArray.h.
Referenced by TBaseIterator(), GetIndex(), GetRelativeBitReference(), operator bool(), operator!=(), operator++(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SparseArray.h