Unreal Engine 5.6 C++ API: UE::Virtualization::IVirtualizationSystem Class Reference
UE::Virtualization::IVirtualizationSystem Class Reference abstract
The base interface for the virtualization system.
#include "VirtualizationSystem.h"
Public Types
enum ENotification {
PushBegunNotification , PushEndedNotification , PushFailedNotification , PullBegunNotification ,
PullEndedNotification , PullFailedNotification
}
using FOnNotification = TTSMulticastDelegate<void(ENotification, const FIoHash&)>
Declare delegate for notifications.
using GetPayloadActivityInfoFuncRef = TFunctionRef<void(const FString& DebugName, const FString& ConfigName, const FPayloadActivityInfo& PayloadInfo)>
Public Member Functions
IVirtualizationSystem ()=default
virtual ~IVirtualizationSystem ()=default
virtual bool AllowSubmitIfVirtualizationFailed () const =0
Poll to see if the virtualization process failing when submitting a collection of files to source control should block that submit or allow it to continue.
virtual void DumpStats () const =0
When called the system should write any performance stats that it has been gathering to the log file.
virtual EPayloadFilterReason FilterPayload (const UObject *Owner) const =0
Run checks to see if the payload can be virtualized or not.
virtual void GatherAnalytics (TArray< FAnalyticsEventAttribute > &Attributes) const =0
Gather analytics data.
virtual TArray< FBackendStats > GetBackendStatistics () const =0
Access profiling info relating to payload activity per backend.
virtual FOnNotification & GetNotificationEvent ()=0
virtual FPayloadActivityInfo GetSystemStatistics () const =0
Access profiling info for all backends combined.
virtual bool Initialize (const FInitParams &InitParams)=0
Initialize the system from the parameters given in the FInitParams structure.
virtual bool IsEnabled () const =0
Poll to see if content virtualization is enabled or not.
virtual bool IsPushingEnabled (EStorageType StorageType) const =0
Poll to see if pushing virtualized content to the given backend storage type is enabled or not.
FCompressedBuffer PullData (const FIoHash &Id)
Pull a single payload from the virtualization backends.
bool PullData (FPullRequest Request)
Pull a single payload from the virtualization backends.
virtual bool PullData (TArrayView< FPullRequest > Requests)=0
Pull a number of payloads from the virtualization backends.
bool PushData (const FIoHash &Id, const FCompressedBuffer &Payload, const FString &Context, EStorageType StorageType)
Push a payload to the virtualization backends.
bool PushData (FPushRequest Request, EStorageType StorageType)
Push a payload to the virtualization backends.
virtual bool PushData (TArrayView< FPushRequest > Requests, EStorageType StorageType)=0
Push one or more payloads to a backend storage system.
virtual EQueryResult QueryPayloadStatuses (TArrayView< const FIoHash > Ids, EStorageType StorageType, TArray< EPayloadStatus > &OutStatuses)=0
Query if a number of payloads exist or not in the given storage type.
return Result virtual WasSuccessful() ? ERehydrationResult FRehydrationResult TryRehydratePackages (TConstArrayView< FString > PackagePaths, ERehydrationOptions Options)=0
Runs the rehydration process on a set of packages.
virtual ERehydrationResult TryRehydratePackages (TConstArrayView< FString > PackagePaths, uint64 PaddingAlignment, TArray< FText > &OutErrors, TArray< FSharedBuffer > &OutPackages, TArray< FRehydrationInfo > *OutInfo)=0
Rehydrates a number of packages into memory buffers.
virtual FVirtualizationResult TryVirtualizePackages (TConstArrayView< FString > PackagePaths, EVirtualizationOptions Options)=0
Runs the virtualization process on a set of packages.
UE_DEPRECATED (5.2, "Use The other overload that takes a EVirtualizationOptions parameter") virtual ERehydrationResult TryRehydratePackages(TConstArrayView< FString > PackagePaths
UE_DEPRECATED (5.5, "Use IVirtualizationSystem::GetBackendStatistics instead") virtual void GetPayloadActivityInfo(GetPayloadActivityInfoFuncRef Func) const
UE_DEPRECATED (5.5, "Use IVirtualizationSystem::GetSystemStatistics instead") virtual FPayloadActivityInfo GetAccumualtedPayloadActivityInfo() const
Static Public Member Functions
static IVirtualizationSystem & Get ()
Gain access to the current virtualization system active for the project.
static FName GetSystemName ()
Returns the name of the currently initialized system, will be NAME_None if initialization failed or the system is not enabled.
static bool IsInitialized ()
Returns true if a virtualization system has been initialized and false if not.
Data Fields
TArray< FText > & OutErrors
OutErrors = MoveTemp(Result.Errors)
Detailed Description
The base interface for the virtualization system.
An Epic maintained version can be found in the Virtualization module. To implement your own, simply derived from this interface and then use the UE_REGISTER_VIRTUALIZATION_SYSTEM macro in the cpp to register it as an option. You can then set the config file option [Core.ContentVirtualization]SystemName=FooBar, where FooBar should be the SystemName parameter you used when registering with the macro.
Special Cases: SystemName=Off - This is the default set up and means a project will not use content virtualization Note that calling IVirtualizationSystem::Get() will still return a valid IVirtualizationSystem implementation, but all push and pull operations will result in failure and IsEnabled will always return false. SystemName=Default - This will cause the default Epic implementation to be used
See also
VirtualizationManager
Definition at line 584 of file VirtualizationSystem.h.
Member Typedef Documentation
FOnNotification
using UE::Virtualization::IVirtualizationSystem::FOnNotification = TTSMulticastDelegate<void(ENotification, const FIoHash&)>
Declare delegate for notifications.
Definition at line 857 of file VirtualizationSystem.h.
GetPayloadActivityInfoFuncRef
using UE::Virtualization::IVirtualizationSystem::GetPayloadActivityInfoFuncRef = TFunctionRef<void(const FString& DebugName, const FString& ConfigName, const FPayloadActivityInfo& PayloadInfo)>
Definition at line 818 of file VirtualizationSystem.h.
Member Enumeration Documentation
ENotification
enum UE::Virtualization::IVirtualizationSystem::ENotification
Enumerator
PushBegunNotification
PushEndedNotification
PushFailedNotification
PullBegunNotification
PullEndedNotification
PullFailedNotification
Definition at line 845 of file VirtualizationSystem.h.
Constructor & Destructor Documentation
IVirtualizationSystem()
UE::Virtualization::IVirtualizationSystem::IVirtualizationSystem () default
Referenced by Get().
~IVirtualizationSystem()
virtual UE::Virtualization::IVirtualizationSystem::~IVirtualizationSystem () virtual default
Member Function Documentation
AllowSubmitIfVirtualizationFailed()
virtual bool UE::Virtualization::IVirtualizationSystem::AllowSubmitIfVirtualizationFailed () const pure virtual
Poll to see if the virtualization process failing when submitting a collection of files to source control should block that submit or allow it to continue.
NOTE: This is a bit of an odd ball option to be included in the VirtualizationSystem API but at the moment we don't really have a better place for it. This might be removed or replaced in future releases.
Returns
True if the calling code should continue with submitting files if the virtualization process failed. If it returns false then the calling code should prevent the submit.
DumpStats()
virtual void UE::Virtualization::IVirtualizationSystem::DumpStats () const pure virtual
When called the system should write any performance stats that it has been gathering to the log file.
FilterPayload()
virtual EPayloadFilterReason UE::Virtualization::IVirtualizationSystem::FilterPayload (const UObject * Owner) const pure virtual
Run checks to see if the payload can be virtualized or not.
Parameters
Owner The UObject that contains the payload, this can be nullptr if the payload is not owned by one
Returns
The reasons why the payload can not be virtualized, encoded as a bitfield of EPayloadFilterReason. This bitfield will be EPayloadFilterReason::None (0) if no reason was found.
References Owner.
GatherAnalytics()
virtual void UE::Virtualization::IVirtualizationSystem::GatherAnalytics (TArray< FAnalyticsEventAttribute > & Attributes) const pure virtual
Gather analytics data.
Stats will only be collected if ENABLE_COOK_STATS is enabled.
Get()
IVirtualizationSystem & UE::Virtualization::IVirtualizationSystem::Get () static
Gain access to the current virtualization system active for the project.
If the system has not yet been initialized then calling this method will initialize it.
References IVirtualizationSystem().
GetBackendStatistics()
virtual TArray< FBackendStats > UE::Virtualization::IVirtualizationSystem::GetBackendStatistics () const pure virtual
Access profiling info relating to payload activity per backend.
Stats will only be collected if ENABLE_COOK_STATS is enabled.
Referenced by UE_DEPRECATED().
GetNotificationEvent()
virtual FOnNotification & UE::Virtualization::IVirtualizationSystem::GetNotificationEvent () pure virtual
GetSystemName()
FName UE::Virtualization::IVirtualizationSystem::GetSystemName () static
Returns the name of the currently initialized system, will be NAME_None if initialization failed or the system is not enabled.
GetSystemStatistics()
virtual FPayloadActivityInfo UE::Virtualization::IVirtualizationSystem::GetSystemStatistics () const pure virtual
Access profiling info for all backends combined.
Stats will only be collected if ENABLE_COOK_STATS is enabled.
Referenced by UE_DEPRECATED().
Initialize()
virtual bool UE::Virtualization::IVirtualizationSystem::Initialize (const FInitParams & InitParams) pure virtual
Initialize the system from the parameters given in the FInitParams structure.
The system can only rely on the members of FInitParams to be valid for the duration of the method call, so if a system needs to retain information longer term then it should make it's own copy of the required data.
NOTE: Although it is relatively easy to access cached FConfigFiles, systems should use the one provided by InitParams to ensure that the correct settings are parsed.
Parameters
InitParam The parameters used to initialize the system
Returns
True if the system was initialized correctly, otherwise false. Note that if the method returns false then the system will be deleted and the default FNullVirtualizationSystem will be used instead.
IsEnabled()
virtual bool UE::Virtualization::IVirtualizationSystem::IsEnabled () const pure virtual
Poll to see if content virtualization is enabled or not.
IsInitialized()
bool UE::Virtualization::IVirtualizationSystem::IsInitialized () static
Returns true if a virtualization system has been initialized and false if not.
IsPushingEnabled()
virtual bool UE::Virtualization::IVirtualizationSystem::IsPushingEnabled (EStorageType StorageType) const pure virtual
Poll to see if pushing virtualized content to the given backend storage type is enabled or not.
PullData() [1/3]
FCompressedBuffer UE::Virtualization::IVirtualizationSystem::PullData (const FIoHash & Id) inline
Pull a single payload from the virtualization backends.
Parameters
Id The hash of the payload to pull
Returns
A valid buffer representing the payload if the pull was successful. An invalid buffer if the pull failed.
Definition at line 716 of file VirtualizationSystem.h.
References UE::Virtualization::FPullRequest::GetPayload(), MakeArrayView(), and PullData().
PullData() [2/3]
bool UE::Virtualization::IVirtualizationSystem::PullData (FPullRequest Request) inline
Pull a single payload from the virtualization backends.
Parameters
Request A payload pull request.
See also
FPullRequest
Returns
True if the pull failed and the request will return a valid payload. False if the pull failed and the request will return an invalid payload
Definition at line 737 of file VirtualizationSystem.h.
References MakeArrayView(), and PullData().
PullData() [3/3]
virtual bool UE::Virtualization::IVirtualizationSystem::PullData (TArrayView< FPullRequest > Requests) pure virtual
Pull a number of payloads from the virtualization backends.
Parameters
Requests An array of payload pull requests.
See also
FPullRequest
Returns
True if the requests succeeded, false if one or more requests failed
Referenced by PullData(), and PullData().
PushData() [1/3]
bool UE::Virtualization::IVirtualizationSystem::PushData (const FIoHash & Id, const FCompressedBuffer & Payload, const FString & Context, EStorageType StorageType) inline
Push a payload to the virtualization backends.
Parameters
Id The identifier of the payload being pushed.
Payload The payload itself in FCompressedBuffer form, it is assumed that if the buffer is to be compressed that it will have been done by the caller.
Context Context for the payload being submitted, typically the name from the UPackage that owns it.
StorageType The type of storage to push the payload to, @See EStorageType for details.
Returns
When StorageType is EStorageType::Cache this will return true as long each payload ends up being stored in at least one of the cache backends. When StorageType is EStorageType::Persistent this will only return true if each payload endd up being stored in all of the backends. This is because the cache backends are not considered essential and it is not the end of the world if a payload is missing but the persistent backends must be reliable.
Definition at line 695 of file VirtualizationSystem.h.
References MakeArrayView(), and PushData().
PushData() [2/3]
bool UE::Virtualization::IVirtualizationSystem::PushData (FPushRequest Request, EStorageType StorageType) inline
Push a payload to the virtualization backends.
Parameters
Request A single push request
PackageContext Context for the payload being submitted, typically the name from the UPackage that owns it.
Returns
When StorageType is EStorageType::Cache this will return true as long each payload ends up being stored in at least one of the cache backends. When StorageType is EStorageType::Persistent this will only return true if each payload endd up being stored in all of the backends. This is because the cache backends are not considered essential and it is not the end of the world if a payload is missing but the persistent backends must be reliable.
Definition at line 674 of file VirtualizationSystem.h.
References MakeArrayView(), and PushData().
PushData() [3/3]
virtual bool UE::Virtualization::IVirtualizationSystem::PushData (TArrayView< FPushRequest > Requests, EStorageType StorageType) pure virtual
Push one or more payloads to a backend storage system.
@See FPushRequest.
Parameters
Requests A collection of one or more payload push requests
StorageType The type of storage to push the payload to, @See EStorageType for details.
Returns
When StorageType is EStorageType::Cache this will return true as long each payload ends up being stored in at least one of the cache backends. When StorageType is EStorageType::Persistent this will only return true if each payload endd up being stored in all of the backends. This is because the cache backends are not considered essential and it is not the end of the world if a payload is missing but the persistent backends must be reliable.
Referenced by PushData(), and PushData().
QueryPayloadStatuses()
virtual EQueryResult UE::Virtualization::IVirtualizationSystem::QueryPayloadStatuses (TArrayView< const FIoHash > Ids, EStorageType StorageType, TArray< EPayloadStatus > & OutStatuses) pure virtual
Query if a number of payloads exist or not in the given storage type.
Parameters
Ids One or more payload identifiers to test
StorageType The type of storage to push the payload to, @See EStorageType for details.
OutStatuses [out] An array containing the results for each payload. @See FPayloadStatus If the operation succeeds the array will be resized to match the size of Ids.
Returns
True if the operation succeeded and the contents of OutStatuses is valid. False if errors were encountered in which case the contents of OutStatuses should be ignored.
TryRehydratePackages() [1/2]
return Result virtual WasSuccessful() ? ERehydrationResult FRehydrationResult UE::Virtualization::IVirtualizationSystem::TryRehydratePackages (TConstArrayView< FString > PackagePaths, ERehydrationOptions Options) pure virtual
Runs the rehydration process on a set of packages.
This involves downloading virtualized payloads and placing them back in the trailer of the given packages.
Parameters
PackagePaths An array containing the absolute file paths of packages
Options An enum bitfield containing various options for the process.
See also
EVirtualizationOptions
Parameters
OutResultInfo A struct that will contain info about the process.
See also
FVirtualizationResult
Returns
A ERehydrationResult enum with the status of the process. If the status indicates any sort of failure then OutResultInfo.Errors should contain at least one entry.
References UE::Options.
TryRehydratePackages() [2/2]
virtual ERehydrationResult UE::Virtualization::IVirtualizationSystem::TryRehydratePackages (TConstArrayView< FString > PackagePaths, uint64 PaddingAlignment, TArray< FText > & OutErrors, TArray< FSharedBuffer > & OutPackages, TArray< FRehydrationInfo > * OutInfo) pure virtual
Rehydrates a number of packages into memory buffers.
Note that if a package does not require rehydration we will still return the package in a memory buffer but it will be the same as the package on disk.
Parameters
PackagePaths An array containing the absolute file paths of packages.
PaddingAlignment Byte alignment to pad each package buffer too, a value of 0 will result in the buffers being the same size as the packages
OutErrors Any errors encountered while rehydration will be added here
OutPackages The rehydrated packages as memory buffers. Each entry should match the corresponding entry in PackagePaths. This array is only guaranteed to be correct if the method returns ERehydrationResult::Success.
OutInfo Information about the rehydration process, each entry should match the corresponding entry in PackagePaths assuming that the method returns ERehydrationResult::Success. This parameter is optional, if the information is not required then pass in nullptr to skip.
Returns
ERehydrationResult::Success if the rehydration suceeeds and OutPackages/OutInfocan be trued, otherwise it will return an error value.
See also
ERehydrationResult
References OutErrors.
TryVirtualizePackages()
virtual FVirtualizationResult UE::Virtualization::IVirtualizationSystem::TryVirtualizePackages (TConstArrayView< FString > PackagePaths, EVirtualizationOptions Options) pure virtual
Runs the virtualization process on a set of packages.
All of the packages will be parsed and any found to be containing locally stored payloads will have them removed but before they are removed they will be pushed to persistent storage.
Note that if errors occur some or all of the payloads could still get pushed to persistent storage, usually if the errors occur when trying to remove the now virtualized payload from the packages on disk. In addition, if errors do occur when removing the virtualized payloads, some packages may be virtualized successfully. In any case the packages should still be usable and safe to checkin after the process has run, even with failure cases.
Parameters
PackagePaths An array of file paths to packages that should be virtualized. If a path resolves to a file that is not a valid package then it will be silently skipped and will not be considered an error.
Options An enum bitfield containing various options for the process.
See also
EVirtualizationOptions
Parameters
OutResultInfo A struct that will contain info about the process.
See also
FVirtualizationResult
Returns
A EVirtualizationResult enum with the status of the process. If the status is not EVirtualizationResult::Success then the parameter OutErrors should contain at least one entry.
References UE::Options.
UE_DEPRECATED() [1/3]
UE::Virtualization::IVirtualizationSystem::UE_DEPRECATED (5. 2, "Use The other overload that takes a EVirtualizationOptions parameter")
UE_DEPRECATED() [2/3]
UE::Virtualization::IVirtualizationSystem::UE_DEPRECATED (5. 5, "Use IVirtualizationSystem::GetBackendStatistics instead") const inline
Definition at line 820 of file VirtualizationSystem.h.
References GetBackendStatistics().
UE_DEPRECATED() [3/3]
UE::Virtualization::IVirtualizationSystem::UE_DEPRECATED (5. 5, "Use IVirtualizationSystem::GetSystemStatistics instead") const inline
Definition at line 829 of file VirtualizationSystem.h.
References GetSystemStatistics().
Field Documentation
OutErrors [1/2]
TArray<FText>& UE::Virtualization::IVirtualizationSystem::OutErrors
Initial value:
{
        FRehydrationResult Result = TryRehydratePackages(PackagePaths, ERehydrationOptions::None)
Definition at line 775 of file VirtualizationSystem.h.
Referenced by TryRehydratePackages().
OutErrors [2/2]
UE::Virtualization::IVirtualizationSystem::OutErrors = MoveTemp(Result.Errors)
Definition at line 779 of file VirtualizationSystem.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Virtualization/VirtualizationSystem.h