Unreal Engine 5.6 C++ API: TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Types
using FMethodPtr = typename TMemFunPtrType<bConst, UserClass, RetValType(ParamTypes..., VarTypes...)>::Type
Public Member Functions
template<typename... InVarTypes>
TBaseSPMethodDelegateInstance (const TSharedPtr< UserClass, SPMode > &InUserObject, FMethodPtr InMethodPtr, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst InUserObject) const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Protected Attributes
FMethodPtr MethodPtr
TWeakPtr< UserClass, SPMode > UserObject
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
Detailed Description
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes>
class TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >
Definition at line 197 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 201 of file DelegateInstancesImpl.h.
FMethodPtr
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::FMethodPtr = typename TMemFunPtrType<bConst, UserClass, RetValType(ParamTypes..., VarTypes...)>::Type
Definition at line 204 of file DelegateInstancesImpl.h.
Super
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 200 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseSPMethodDelegateInstance()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> template<typename... InVarTypes> TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseSPMethodDelegateInstance (const TSharedPtr< UserClass, SPMode > & InUserObject, FMethodPtr InMethodPtr, InVarTypes &&... Vars) inline explicit
Definition at line 207 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), MethodPtr, and UserObject.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 267 of file DelegateInstancesImpl.h.
References TBaseSPMethodDelegateInstance().
CreateCopy() [2/3]
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 272 of file DelegateInstancesImpl.h.
References TBaseSPMethodDelegateInstance().
CreateCopy() [3/3]
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 262 of file DelegateInstancesImpl.h.
References TBaseSPMethodDelegateInstance().
Execute()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> RetValType TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 277 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), TSharedPtr< ObjectType, InMode >::Get(), TSharedPtr< ObjectType, InMode >::IsValid(), MethodPtr, Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObject.
ExecuteIfSafe()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 295 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), MethodPtr, Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObject.
GetBoundProgramCounterForTimerManager()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> uint64 TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 238 of file DelegateInstancesImpl.h.
References MethodPtr.
GetObjectForTimerManager()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> const void * TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 233 of file DelegateInstancesImpl.h.
References UserObject.
GetUObject()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UObject * TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetUObject () const inline final
Definition at line 228 of file DelegateInstancesImpl.h.
HasSameObject()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::HasSameObject (FDelegateUserObjectConst InUserObject) const inline final
Definition at line 248 of file DelegateInstancesImpl.h.
References UserObject.
IsSafeToExecute()
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 253 of file DelegateInstancesImpl.h.
References UserObject.
Field Documentation
MethodPtr
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> FMethodPtr TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::MethodPtr protected
Definition at line 323 of file DelegateInstancesImpl.h.
Referenced by TBaseSPMethodDelegateInstance(), Execute(), ExecuteIfSafe(), and GetBoundProgramCounterForTimerManager().
UserObject
template<bool bConst, class UserClass, ESPMode SPMode, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> TWeakPtr<UserClass, SPMode> TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::UserObject protected
Definition at line 320 of file DelegateInstancesImpl.h.
Referenced by TBaseSPMethodDelegateInstance(), Execute(), ExecuteIfSafe(), GetObjectForTimerManager(), HasSameObject(), and IsSafeToExecute().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstancesImpl.h