Unreal Engine 5.6 C++ API: TRangeAllocator< FAllocatorModifier > Class Template Reference
TRangeAllocator< FAllocatorModifier > Class Template Reference
#include "RangeAllocator.h"
Data Structures
struct FAllocInfo
class FChunk
struct FFreeChunkInfo
Public Member Functions
template<typename... ArgTypes>
TRangeAllocator (uint32 InMinAllocSize, ArgTypes &&... Args)
FPointerType Alloc (uint32 Size, uint32 Alignment, FAllocInfo &OutAllocInfo)
bool Contains (FConstPointerType Addr) const
void Free (const FAllocInfo &AllocInfo)
Protected Types
using FAllocInfoModifier = typename FAllocatorModifier::FAllocInfoModifier
using FChunkModifier = typename FAllocatorModifier::FChunkModifier
using FConstPointerType = typename FAllocatorModifier::FConstPointerType
using FPointerType = typename FAllocatorModifier::FPointerType
using FRangeAllocator = TRangeAllocator<FAllocatorModifier>
Protected Member Functions
void FreeChunk (uint32 ChunkIndex)
void RemoveFreeChunkInfo (int32 InfoIndex)
Protected Attributes
TArray< FChunk > Chunks
FCriticalSection CS
TArray< FFreeChunkInfo > FreeChunkInfos
int32 FreeChunkSlotHead
const uint16 MinAllocSize
SIZE_T SizeTotal = 0
SIZE_T SizeUsed = 0
Detailed Description
template<typename FAllocatorModifier>
class TRangeAllocator< FAllocatorModifier >
Definition at line 81 of file RangeAllocator.h.
Member Typedef Documentation
FAllocInfoModifier
template<typename FAllocatorModifier> using TRangeAllocator< FAllocatorModifier >::FAllocInfoModifier = typename FAllocatorModifier::FAllocInfoModifier protected
Definition at line 88 of file RangeAllocator.h.
FChunkModifier
template<typename FAllocatorModifier> using TRangeAllocator< FAllocatorModifier >::FChunkModifier = typename FAllocatorModifier::FChunkModifier protected
Definition at line 87 of file RangeAllocator.h.
FConstPointerType
template<typename FAllocatorModifier> using TRangeAllocator< FAllocatorModifier >::FConstPointerType = typename FAllocatorModifier::FConstPointerType protected
Definition at line 86 of file RangeAllocator.h.
FPointerType
template<typename FAllocatorModifier> using TRangeAllocator< FAllocatorModifier >::FPointerType = typename FAllocatorModifier::FPointerType protected
Definition at line 85 of file RangeAllocator.h.
FRangeAllocator
template<typename FAllocatorModifier> using TRangeAllocator< FAllocatorModifier >::FRangeAllocator = TRangeAllocator<FAllocatorModifier> protected
Definition at line 84 of file RangeAllocator.h.
Constructor & Destructor Documentation
TRangeAllocator()
template<typename FAllocatorModifier> template<typename... ArgTypes> TRangeAllocator< FAllocatorModifier >::TRangeAllocator (uint32 InMinAllocSize, ArgTypes &&... Args) inline
Definition at line 301 of file RangeAllocator.h.
References Forward(), FreeChunkSlotHead, INDEX_NONE, and MinAllocSize.
Member Function Documentation
Alloc()
template<typename FAllocatorModifier> FPointerType TRangeAllocator< FAllocatorModifier >::Alloc (uint32 Size, uint32 Alignment, FAllocInfo & OutAllocInfo) inline
Definition at line 307 of file RangeAllocator.h.
References TArray< InElementType, InAllocatorType >::Add(), Align, TRangeAllocator< FAllocatorModifier >::FChunk::Alloc(), TRangeAllocator< FAllocatorModifier >::FAllocInfo::ChunkIndex, Chunks, CS, FreeChunkInfos, FreeChunkSlotHead, INDEX_NONE, Info, TRangeAllocator< FAllocatorModifier >::FChunk::InfoIndex, FMath::IsPowerOfTwo(), FMath::Max, MinAllocSize, TArray< InElementType, InAllocatorType >::Num(), TRangeAllocator< FAllocatorModifier >::FAllocInfo::RangeOffset, TRangeAllocator< FAllocatorModifier >::FAllocInfo::RangeSize, RemoveFreeChunkInfo(), SizeTotal, SizeUsed, and TSequenceHistory< HistorySize >::Size.
Contains()
template<typename FAllocatorModifier> bool TRangeAllocator< FAllocatorModifier >::Contains (FConstPointerType Addr) const inline
Definition at line 429 of file RangeAllocator.h.
References Chunks, and CS.
Free()
template<typename FAllocatorModifier> void TRangeAllocator< FAllocatorModifier >::Free (const FAllocInfo & AllocInfo) inline
Definition at line 400 of file RangeAllocator.h.
References TRangeAllocator< FAllocatorModifier >::FAllocInfo::ChunkIndex, Chunks, CS, FreeChunk(), FreeChunkInfos, INDEX_NONE, MinAllocSize, TRangeAllocator< FAllocatorModifier >::FAllocInfo::RangeOffset, TRangeAllocator< FAllocatorModifier >::FAllocInfo::RangeSize, and SizeUsed.
FreeChunk()
template<typename FAllocatorModifier> void TRangeAllocator< FAllocatorModifier >::FreeChunk (uint32 ChunkIndex) inline protected
Definition at line 263 of file RangeAllocator.h.
References Chunks, FreeChunkSlotHead, INDEX_NONE, RemoveFreeChunkInfo(), and SizeTotal.
Referenced by Free().
RemoveFreeChunkInfo()
template<typename FAllocatorModifier> void TRangeAllocator< FAllocatorModifier >::RemoveFreeChunkInfo (int32 InfoIndex) inline protected
Definition at line 254 of file RangeAllocator.h.
References Chunks, FreeChunkInfos, and No.
Referenced by Alloc(), and FreeChunk().
Field Documentation
Chunks
template<typename FAllocatorModifier> TArray<FChunk> TRangeAllocator< FAllocatorModifier >::Chunks protected
Definition at line 286 of file RangeAllocator.h.
Referenced by Alloc(), Contains(), Free(), FreeChunk(), and RemoveFreeChunkInfo().
CS
template<typename FAllocatorModifier> FCriticalSection TRangeAllocator< FAllocatorModifier >::CS mutable protected
Definition at line 287 of file RangeAllocator.h.
Referenced by Alloc(), Contains(), and Free().
FreeChunkInfos
template<typename FAllocatorModifier> TArray<FFreeChunkInfo> TRangeAllocator< FAllocatorModifier >::FreeChunkInfos protected
Definition at line 285 of file RangeAllocator.h.
Referenced by Alloc(), Free(), and RemoveFreeChunkInfo().
FreeChunkSlotHead
template<typename FAllocatorModifier> int32 TRangeAllocator< FAllocatorModifier >::FreeChunkSlotHead protected
Definition at line 284 of file RangeAllocator.h.
Referenced by TRangeAllocator(), Alloc(), and FreeChunk().
MinAllocSize
template<typename FAllocatorModifier> const uint16 TRangeAllocator< FAllocatorModifier >::MinAllocSize protected
Definition at line 283 of file RangeAllocator.h.
Referenced by TRangeAllocator(), Alloc(), and Free().
SizeTotal
template<typename FAllocatorModifier> SIZE_T TRangeAllocator< FAllocatorModifier >::SizeTotal = 0 protected
Definition at line 279 of file RangeAllocator.h.
Referenced by Alloc(), and FreeChunk().
SizeUsed
template<typename FAllocatorModifier> SIZE_T TRangeAllocator< FAllocatorModifier >::SizeUsed = 0 protected
Definition at line 280 of file RangeAllocator.h.
Referenced by Alloc(), and Free().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/RangeAllocator.h