Unreal Engine 5.6 C++ API: FFolderDragDropOp Class Reference
FFolderDragDropOp Class Reference
#include "FolderDragDropOp.h"
Public Member Functions
DRAG_DROP_OPERATOR_TYPE (FFolderDragDropOp, FDecoratedDragDropOp) TArray< FName > Folders
Array of folders that we are dragging.
void Init (TArray< FName > InFolders, UWorld *InWorld, const FFolder::FRootObject &InRootObject=FFolder::GetInvalidRootObject())
Public Member Functions inherited from FDecoratedDragDropOp
FDecoratedDragDropOp ()
virtual void Construct () override
Overridden to provide public access.
DRAG_DROP_OPERATOR_TYPE (FDecoratedDragDropOp, FDragDropOperation) FText CurrentHoverText
String to show as hover text.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const override
The widget decorator to use.
FText GetDefaultHoverText () const
Gets the default hover text for this drag drop op.
FText GetHoverText () const
const FSlateBrush * GetIcon () const
FSlateColor GetIconColorAndOpacity () const
virtual void ResetToDefaultToolTip ()
Set the decorator back to the icon and text defined by the default.
void SetToolTip (const FText &Text, const FSlateBrush *Icon)
Set the text and icon for this tooltip.
void SetupDefaults ()
Setup some default values for the decorator.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FFolder::FRootObject RootObject
Root object of folder (can be invalid)
TWeakObjectPtr< UWorld > World
World to which the folders belong.
Data Fields inherited from FDecoratedDragDropOp
const FSlateBrush * CurrentIconBrush
Icon to be displayed.
FSlateColor CurrentIconColorAndOpacity
The color of the icon to be displayed.
Additional Inherited Members
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FDecoratedDragDropOp
const FSlateBrush * DefaultHoverIcon
Default icon to be displayed.
FSlateColor DefaultHoverIconColorAndOpacity
Default color and opacity for the default icon to be displayed.
FText DefaultHoverText
Default string to show as hover text.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Detailed Description
Definition at line 13 of file FolderDragDropOp.h.
Member Function Documentation
DRAG_DROP_OPERATOR_TYPE()
FFolderDragDropOp::DRAG_DROP_OPERATOR_TYPE (FFolderDragDropOp , FDecoratedDragDropOp)
Array of folders that we are dragging.
References FDecoratedDragDropOp::FDecoratedDragDropOp(), and Folders.
Init()
void FFolderDragDropOp::Init (TArray< FName > InFolders, UWorld * InWorld, const FFolder::FRootObject & InRootObject = FFolder::GetInvalidRootObject()) inline
Definition at line 25 of file FolderDragDropOp.h.
References FText::AsNumber(), check, FDecoratedDragDropOp::CurrentIconBrush, Folders, FText::Format(), FText::FromName(), FAppStyle::Get(), ISlateStyle::GetBrush(), FFolder::GetInvalidRootObject(), FEditorFolderUtils::GetLeafName(), MoveTemp(), NSLOCTEXT, RootObject, FDecoratedDragDropOp::SetupDefaults(), TEXT, and World.
Field Documentation
RootObject
FFolder::FRootObject FFolderDragDropOp::RootObject
Root object of folder (can be invalid)
Definition at line 23 of file FolderDragDropOp.h.
Referenced by Init().
World
TWeakObjectPtr<UWorld> FFolderDragDropOp::World
World to which the folders belong.
Definition at line 21 of file FolderDragDropOp.h.
Referenced by Init().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/DragAndDrop/FolderDragDropOp.h