Unreal Engine 5.6 C++ API: UE::Insights::STableTreeView Class Reference
UE::Insights::STableTreeView Class Reference
A custom widget used to display the list of tree nodes.
#include "STableTreeView.h"
Public Member Functions
STableTreeView ()
Default constructor.
virtual ~STableTreeView ()
Virtual destructor.
virtual double GetAllOperationsDuration () override
const TArray< TSharedPtr< FTreeNodeGrouping > > & GetAvailableGroupings () const
Gets the available groupings.
virtual double GetCurrentOperationDuration () override
virtual FText GetCurrentOperationName () const override
TSharedPtr< STreeView< FTableTreeNodePtr > > GetInnerTreeView () const
const FName & GetLogListingName ()
FTableTreeNodePtr GetNodeByTableRowIndex (int32 RowIndex) const
virtual uint32 GetOperationCount () const override
TSharedPtr< FTable > & GetTable ()
const TSharedPtr< FTable > & GetTable () const
const TArray< FTableTreeNodePtr > & GetTableRowNodes () const
Gets the table row nodes.
virtual bool IsRunning () const override
bool IsRunningAsyncUpdate ()
void OnClose ()
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
void RebuildColumns ()
virtual void RebuildTree (bool bResync)
Rebuilds the tree (if necessary).
virtual void Reset ()
void SelectNodeByTableRowIndex (int32 RowIndex)
void SetCurrentGroupings (TArray< TSharedPtr< FTreeNodeGrouping > > &InCurrentGroupings)
Sets the current groupings.
void SetLogListingName (const FName &InLogListingName)
Sets a log listing name to be used for any errors or warnings.
SLATE_BEGIN_ARGS (STableTreeView)
SLATE_END_ARGS () void Construct(const FArguments &InArgs
Construct this widget.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FTable > InTablePtr
Protected Types
typedef TFunctionRef< void(TArray< FBaseTreeNodePtr > &InNodes)> WriteToFileCallback
Protected Member Functions
void AddInProgressAsyncOperation (EAsyncOperationType InType)
void ApplyColumnConfig (const TArrayView< FTableColumnConfig > &InTableConfig)
void ApplyEmptyHierarchyFilteringRec (FTableTreeNodePtr NodePtr)
void ApplyGrouping ()
void ApplyHierarchyFiltering ()
bool ApplyHierarchyFilteringRec (FTableTreeNodePtr NodePtr)
void ApplyNodeFiltering ()
void ApplySorting ()
void ApplyViewPreset (const ITableTreeViewPreset &InPreset)
void BuildGroupingSubMenu_Add (FMenuBuilder &MenuBuilder, const TSharedPtr< FTreeNodeGrouping > CrumbGrouping)
void BuildGroupingSubMenu_Change (FMenuBuilder &MenuBuilder, const TSharedPtr< FTreeNodeGrouping > CrumbGrouping)
void CancelCurrentAsyncOp ()
bool CanHideColumn (const FName ColumnId) const
bool CanShowColumn (const FName ColumnId) const
bool CanToggleColumnVisibility (const FName ColumnId) const
void ClearInProgressAsyncOperations ()
virtual TSharedPtr< SWidget > ConstructExtraToolbar ()
virtual TSharedRef< SWidget > ConstructFilterConfiguratorButton ()
virtual TSharedPtr< SWidget > ConstructFilterToolbar ()
virtual TSharedPtr< SWidget > ConstructFooter ()
virtual void ConstructFooterArea (TSharedRef< SVerticalBox > InHostBox)
virtual void ConstructHeaderArea (TSharedRef< SVerticalBox > InHostBox)
virtual TSharedRef< SWidget > ConstructHierarchyBreadcrumbTrail ()
virtual TSharedRef< SWidget > ConstructSearchBox ()
virtual TSharedPtr< SWidget > ConstructToolbar ()
void ConstructViewPreset (TSharedPtr< SHorizontalBox > InHorizontalBox, float InMinDesiredWidth=50.0f)
virtual void ConstructWidget (TSharedPtr< FTable > InTablePtr)
bool ContextMenu_CollapseSubtree_CanExecute () const
void ContextMenu_CollapseSubtree_Execute ()
bool ContextMenu_CopyColumnToClipboard_CanExecute () const
void ContextMenu_CopyColumnToClipboard_Execute ()
bool ContextMenu_CopyColumnTooltipToClipboard_CanExecute () const
void ContextMenu_CopyColumnTooltipToClipboard_Execute ()
bool ContextMenu_CopySelectedToClipboard_CanExecute () const
void ContextMenu_CopySelectedToClipboard_Execute ()
bool ContextMenu_ExpandCriticalPath_CanExecute () const
void ContextMenu_ExpandCriticalPath_Execute ()
bool ContextMenu_ExpandSubtree_CanExecute () const
void ContextMenu_ExpandSubtree_Execute ()
bool ContextMenu_ExportToFile_CanExecute () const
void ContextMenu_ExportToFile_Execute (bool bInExportCollapsed, bool InExportLeafs)
bool ContextMenu_HideAllColumns_CanExecute () const
void ContextMenu_HideAllColumns_Execute ()
bool ContextMenu_ResetColumns_CanExecute () const
void ContextMenu_ResetColumns_Execute ()
bool ContextMenu_ShowAllColumns_CanExecute () const
void ContextMenu_ShowAllColumns_Execute ()
bool ContextMenu_SortByColumn_CanExecute (const FName ColumnId) const
void ContextMenu_SortByColumn_Execute (const FName ColumnId)
bool ContextMenu_SortByColumn_IsChecked (const FName ColumnId)
bool ContextMenu_SortMode_CanExecute (const EColumnSortMode::Type InSortMode) const
void ContextMenu_SortMode_Execute (const EColumnSortMode::Type InSortMode)
bool ContextMenu_SortMode_IsChecked (const EColumnSortMode::Type InSortMode)
void CountNumNodesPerDepthRec (FBaseTreeNode *InRoot, TArray< int32 > &InOutNumNodesPerDepth, int32 InDepth, int32 InMaxDepth, int32 InMaxNodes) const
void CreateGroupings ()
void CreateGroups (const TArray< TSharedPtr< FTreeNodeGrouping > > &Groupings)
void CreateSortings ()
void ExportToFileRec (const FBaseTreeNodePtr &InGroupNode, TArray< FBaseTreeNodePtr > &InNodes, bool bInExportCollapsed, bool InExportLeafs, WriteToFileCallback Callback)
virtual void ExtendMenu (FMenuBuilder &Menu)
virtual void ExtendMenu (TSharedRef< FExtender > Extender)
FReply FilterConfigurator_OnClicked ()
virtual bool FilterNode (const FFilterConfigurator &InFilterConfigurator, const FTableTreeNode &InNode) const
virtual bool FilterNodeCustom (const FTableTreeNode &InNode) const
const TArray< TSharedRef< ITableTreeViewPreset > > * GetAvailableViewPresets () const
FText GetColumnHeaderText (const FName ColumnId) const
TSharedRef< SWidget > GetGroupingCrumbMenuContent (const TSharedPtr< FTreeNodeGrouping > &CrumbGrouping)
int32 GetGroupingDepth (const TSharedPtr< FTreeNodeGrouping > &Grouping) const
TSharedPtr< ITableTreeViewPreset > GetSelectedViewPreset () const
EColumnSortMode::Type GetSortModeForColumn (const FName ColumnId) const
FText GetTreeViewBannerText () const
bool GroupingCrumbMenu_Add_CanExecute (const TSharedPtr< FTreeNodeGrouping > Grouping, const TSharedPtr< FTreeNodeGrouping > AfterGrouping) const
void GroupingCrumbMenu_Add_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping, const TSharedPtr< FTreeNodeGrouping > AfterGrouping)
bool GroupingCrumbMenu_Change_CanExecute (const TSharedPtr< FTreeNodeGrouping > OldGrouping, const TSharedPtr< FTreeNodeGrouping > NewGrouping) const
void GroupingCrumbMenu_Change_Execute (const TSharedPtr< FTreeNodeGrouping > OldGrouping, const TSharedPtr< FTreeNodeGrouping > NewGrouping)
void GroupingCrumbMenu_MoveLeft_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping)
void GroupingCrumbMenu_MoveRight_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping)
void GroupingCrumbMenu_Remove_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping)
void GroupingCrumbMenu_Reset_Execute ()
void GroupNodesRec (const TArray< FTableTreeNodePtr > &Nodes, FTableTreeNode &ParentGroup, int32 GroupingDepth, const TArray< TSharedPtr< FTreeNodeGrouping > > &Groupings)
virtual bool HasCustomNodeFilter () const
bool HasInProgressAsyncOperation (EAsyncOperationType InType) const
bool HeaderMenu_SortMode_CanExecute (const FName ColumnId, const EColumnSortMode::Type InSortMode) const
void HeaderMenu_SortMode_Execute (const FName ColumnId, const EColumnSortMode::Type InSortMode)
bool HeaderMenu_SortMode_IsChecked (const FName ColumnId, const EColumnSortMode::Type InSortMode)
void HideColumn (const FName ColumnId)
void HideColumn (FTableColumn &Column)
virtual void InitAvailableViewPresets ()
void InitCommandList ()
virtual void InitFilterConfigurator (FFilterConfigurator &InOutFilterConfigurator)
void InitHierarchyFiltering ()
void InitializeAndShowHeaderColumns ()
void InitNodeFiltering ()
virtual void InternalCreateGroupings ()
bool IsColumnVisible (const FName ColumnId)
bool MakeSubtreeVisible (FTableTreeNodePtr NodePtr, bool bFilterIsEmpty)
Set all the nodes belonging to a subtree as visible.
void OnGroupingChanged ()
void OnGroupingCrumbClicked (const TSharedPtr< FTreeNodeGrouping > &InEntry)
void OnHierarchyFilteringChanged ()
void OnNodeFilteringChanged ()
virtual void OnPostAsyncUpdate ()
virtual void OnPreAsyncUpdate ()
void OnSortingChanged ()
void OnSortModeChanged (const EColumnSortPriority::Type SortPriority, const FName &ColumnId, const EColumnSortMode::Type SortMode)
void PostChangeGroupings ()
void PreChangeGroupings ()
void RebuildGroupingCrumbs ()
void ScheduleGroupingAsyncOperation ()
bool ScheduleGroupingAsyncOperationIfNeeded ()
void ScheduleHierarchyFilteringAsyncOperation ()
bool ScheduleHierarchyFilteringAsyncOperationIfNeeded ()
void ScheduleNodeFilteringAsyncOperation ()
bool ScheduleNodeFilteringAsyncOperationIfNeeded ()
void ScheduleSortingAsyncOperation ()
bool ScheduleSortingAsyncOperationIfNeeded ()
void SearchBox_OnTextChanged (const FText &InFilterText)
virtual void SearchForItem (TSharedPtr< FTableTaskCancellationToken > CancellationToken)
void SelectViewPreset (TSharedPtr< ITableTreeViewPreset > InPreset)
void SetExpandValueForChildGroups (FBaseTreeNode *InRoot, int32 InMaxExpandedNodes, int32 MaxDepthToExpand, bool InValue)
void SetExpandValueForChildGroupsRec (FBaseTreeNode *InRoot, int32 InDepth, int32 InMaxDepth, bool InValue)
void SetSortModeForColumn (const FName &ColumnId, EColumnSortMode::Type SortMode)
void ShowColumn (const FName ColumnId)
void ShowColumn (FTableColumn &Column)
void SortTreeNodes (ITableCellValueSorter *InSorter, EColumnSortMode::Type InColumnSortMode)
void SortTreeNodesRec (FTableTreeNode &GroupNode, const ITableCellValueSorter &Sorter, EColumnSortMode::Type InColumnSortMode)
FGraphEventRef StartGroupingTask (FGraphEventRef Prerequisite=nullptr)
FGraphEventRef StartHierarchyFilteringTask (FGraphEventRef Prerequisite=nullptr)
FGraphEventRef StartNodeFilteringTask (FGraphEventRef Prerequisite=nullptr)
void StartPendingAsyncOperations ()
FGraphEventRef StartSortingTask (FGraphEventRef Prerequisite=nullptr)
template<typename T, typename... TArgs>
TSharedPtr< FTableTaskInfo > StartTableDataTask (TArgs &&... Args)
void StopAllTableDataTasks (bool bWait=true)
EHorizontalAlignment TableRow_GetColumnOutlineHAlignment (const FName ColumnId) const
FName TableRow_GetHighlightedNodeName () const
FText TableRow_GetHighlightText () const
void TableRow_SetHoveredCell (TSharedPtr< FTable > TablePtr, TSharedPtr< FTableColumn > ColumnPtr, FTableTreeNodePtr NodePtr)
bool TableRow_ShouldBeEnabled (FTableTreeNodePtr NodePtr) const
void ToggleColumnVisibility (const FName ColumnId)
void TreeView_BuildExportMenu (FMenuBuilder &MenuBuilder)
void TreeView_BuildSortByMenu (FMenuBuilder &MenuBuilder)
void TreeView_BuildViewColumnMenu (FMenuBuilder &MenuBuilder)
TSharedPtr< SWidget > TreeView_GetMenuContent ()
virtual void TreeView_OnExpansionChanged (FTableTreeNodePtr TreeNode, bool bShouldBeExpanded)
Called by STreeView when a tree node is expanded or collapsed.
TSharedRef< ITableRow > TreeView_OnGenerateRow (FTableTreeNodePtr TreeNode, const TSharedRef< STableViewBase > &OwnerTable)
Called by STreeView to generate a table row for the specified item.
void TreeView_OnGetChildren (FTableTreeNodePtr InParent, TArray< FTableTreeNodePtr > &OutChildren)
Called by STreeView to retrieves the children for the specified parent item.
virtual void TreeView_OnMouseButtonDoubleClick (FTableTreeNodePtr TreeNode)
Called by STreeView when a tree item is double clicked.
virtual void TreeView_OnSelectionChanged (FTableTreeNodePtr SelectedItem, ESelectInfo::Type SelectInfo)
Called by STreeView when selection has changed.
void TreeView_Refresh ()
TSharedRef< SWidget > TreeViewHeaderRow_GenerateColumnMenu (const FTableColumn &Column)
void UpdateAggregatedValuesRec (FTableTreeNode &GroupNode)
void UpdateAggregatedValuesSingleNode (FTableTreeNode &GroupNode)
virtual void UpdateBannerText ()
void UpdateCurrentSortingByColumn ()
virtual void UpdateFilterContext (const FFilterConfigurator &InFilterConfigurator, const FTableTreeNode &InNode) const
void UpdateTree ()
FText ViewPreset_GetSelectedText () const
FText ViewPreset_GetSelectedToolTipText () const
TSharedRef< SWidget > ViewPreset_OnGenerateWidget (TSharedRef< ITableTreeViewPreset > InPreset)
void ViewPreset_OnSelectionChanged (TSharedPtr< ITableTreeViewPreset > InPreset, ESelectInfo::Type SelectInfo)
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static const FName GetDefaultColumnBeingSorted ()
static const EColumnSortMode::Type GetDefaultColumnSortMode ()
static void HandleItemToStringArray (const FTableTreeNodePtr &GroupOrStatNodePtr, TArray< FString > &OutSearchStrings)
Populates OutSearchStrings with the strings that should be used in searching.
template<bool bIsRercursive>
static void UpdateAggregatedValues (TSharedPtr< FTable > InTable, FTableTreeNode &InOutGroupNode)
template<typename T, bool bSetInitialValue, bool bIsRercursive>
static void UpdateAggregation (const FTableColumn &InColumn, FTableTreeNode &InOutGroupNode, const T InitialAggregatedValue, TFunctionRef< T(T, const FTableCellValue &)> ValueGetterFunc)
static void UpdateCStringSameValueAggregationRec (const FTableColumn &InColumn, FTableTreeNode &GroupNode)
static void UpdateCStringSameValueAggregationSingleNode (const FTableColumn &InColumn, FTableTreeNode &GroupNode)
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
FGraphEventRef AsyncCompleteTaskEvent
FAsyncOperationProgress AsyncOperationProgress
TSharedPtr< class SAsyncOperationStatus > AsyncOperationStatus
FStopwatch AsyncUpdateStopwatch
TArray< TSharedPtr< FTreeNodeGrouping > > AvailableGroupings
TArray< TSharedPtr< ITableCellValueSorter > > AvailableSorters
All available sorters.
TArray< TSharedRef< ITableTreeViewPreset > > AvailableViewPresets
bool bExpansionSaved = false
If true, the expanded nodes have been saved before applying a text filter.
bool bIsCloseScheduled = false
bool bIsUpdateRunning = false
bool bRunInAsyncMode = false
FName ColumnBeingSorted
Name of the column currently being sorted.
EColumnSortMode::Type ColumnSortMode = EColumnSortMode::None
How we sort the nodes?
TSharedPtr< FUICommandList > CommandList
EColumnSortMode::Type CurrentAsyncOpColumnSortMode
The sort mode actually used in the Sorting async task.
FFilterConfigurator * CurrentAsyncOpFilterConfigurator = nullptr
The filter configurator actually used in the Hierarchy Filtering async task.
TArray< TSharedPtr< FTreeNodeGrouping > > CurrentAsyncOpGroupings
The groupings actually used in the Grouping async task.
ITableCellValueSorter * CurrentAsyncOpSorter = nullptr
The sorter actually used in the Sorting async task.
TSharedPtr< FTableTreeNodeTextFilter > CurrentAsyncOpTextFilter
The text based filter actually used in the Hierarchy Filtering async task.
TArray< TSharedPtr< FTreeNodeGrouping > > CurrentGroupings
How we group the tree nodes?
TSharedPtr< ITableCellValueSorter > CurrentSorter
Current sorter.
TArray< TSharedPtr< FTableTaskInfo > > DataTaskInfos
FGraphEventRef DispatchEvent
TArray< FTableTreeNodePtr > DummyGroupNodes
TSet< FTableTreeNodePtr > ExpandedNodes
Currently expanded group nodes.
TSharedPtr< SScrollBar > ExternalScrollbar
External scrollbar used to synchronize tree view position.
TSharedPtr< FFilterConfigurator > FilterConfigurator
FFilterContext FilterContext
TArray< FTableTreeNodePtr > FilteredGroupNodes
A filtered array of group nodes to be displayed in the tree widget.
TArray< FTableTreeNodePtr > FilteredNodes
Filtered table nodes.
TArray< FTableTreeNodePtr > * FilteredNodesPtr = nullptr
A pointer to the filtered table nodes.
TSharedPtr< FTableTreeNodeFilterCollection > Filters
The filter collection.
TSharedPtr< SBreadcrumbTrail< TSharedPtr< FTreeNodeGrouping > > > GroupingBreadcrumbTrail
FName HighlightedNodeName
Name of the tree node that should be drawn as highlighted.
FName HoveredColumnId
Name of the column currently being hovered by the mouse.
FTableTreeNodePtr HoveredNodePtr
A shared pointer to the tree node currently being hovered by the mouse.
FGraphEventRef InProgressAsyncOperationEvent
EAsyncOperationType InProgressAsyncOperations = static_cast<EAsyncOperationType>(0)
FName LogListingName
A log listing name to be used for any errors or warnings.
int32 MaxDepthToAutoExpand = 4
int32 MaxDepthToExpand = 100
int32 MaxNodesToAutoExpand = 1000
int32 MaxNodesToExpand = 1000000
TArray< FTableTreeNodePtr > NodesToExpand
FDelegateHandle OnFilterChangesCommittedHandle
TSharedPtr< SComboBox< TSharedRef< ITableTreeViewPreset > > > PresetComboBox
FTableTreeNodePtr Root
The root node of the tree.
TSharedPtr< SSearchBox > SearchBox
The search box widget used to filter items displayed in the stats and groups tree.
TSharedPtr< ITableTreeViewPreset > SelectedViewPreset
TSharedPtr< FTable > Table
Table view model.
TArray< FTableTreeNodePtr > TableRowNodes
Table row nodes.
TSharedPtr< FTableTreeNodeTextFilter > TextFilter
The text based filter.
TSharedPtr< STreeView< FTableTreeNodePtr > > TreeView
The child STreeView widget.
FText TreeViewBannerText
TSharedPtr< SHeaderRow > TreeViewHeaderRow
Holds the tree view header row widget which display all columns in the tree view.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Static Protected Attributes
static const FName RootNodeName
Friends
class FSearchForItemToSelectTask
class FSelectNodeByTableRowIndexTask
class FTableTreeViewAsyncCompleteTask
class FTableTreeViewGroupingAsyncTask
class FTableTreeViewHierarchyFilteringAsyncTask
class FTableTreeViewNodeFilteringAsyncTask
class FTableTreeViewSortingAsyncTask
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Detailed Description
A custom widget used to display the list of tree nodes.
Definition at line 107 of file STableTreeView.h.
Member Typedef Documentation
WriteToFileCallback
typedef TFunctionRef<void(TArray<FBaseTreeNodePtr>& InNodes)> UE::Insights::STableTreeView::WriteToFileCallback protected
Definition at line 462 of file STableTreeView.h.
Constructor & Destructor Documentation
STableTreeView()
UE::Insights::STableTreeView::STableTreeView ()
Default constructor.
Referenced by SLATE_BEGIN_ARGS().
~STableTreeView()
virtual UE::Insights::STableTreeView::~STableTreeView () virtual
Virtual destructor.
Member Function Documentation
AddInProgressAsyncOperation()
void UE::Insights::STableTreeView::AddInProgressAsyncOperation (EAsyncOperationType InType) inline protected
Definition at line 445 of file STableTreeView.h.
References EAsyncOperationType::EAsyncOperationType, EnumAddFlags(), and InProgressAsyncOperations.
ApplyColumnConfig()
void UE::Insights::STableTreeView::ApplyColumnConfig (const TArrayView< FTableColumnConfig > & InTableConfig) protected
ApplyEmptyHierarchyFilteringRec()
void UE::Insights::STableTreeView::ApplyEmptyHierarchyFilteringRec (FTableTreeNodePtr NodePtr) protected
ApplyGrouping()
void UE::Insights::STableTreeView::ApplyGrouping () protected
ApplyHierarchyFiltering()
void UE::Insights::STableTreeView::ApplyHierarchyFiltering () protected
ApplyHierarchyFilteringRec()
bool UE::Insights::STableTreeView::ApplyHierarchyFilteringRec (FTableTreeNodePtr NodePtr) protected
ApplyNodeFiltering()
void UE::Insights::STableTreeView::ApplyNodeFiltering () protected
ApplySorting()
void UE::Insights::STableTreeView::ApplySorting () protected
ApplyViewPreset()
void UE::Insights::STableTreeView::ApplyViewPreset (const ITableTreeViewPreset & InPreset) protected
BuildGroupingSubMenu_Add()
void UE::Insights::STableTreeView::BuildGroupingSubMenu_Add (FMenuBuilder & MenuBuilder, const TSharedPtr< FTreeNodeGrouping > CrumbGrouping) protected
BuildGroupingSubMenu_Change()
void UE::Insights::STableTreeView::BuildGroupingSubMenu_Change (FMenuBuilder & MenuBuilder, const TSharedPtr< FTreeNodeGrouping > CrumbGrouping) protected
CancelCurrentAsyncOp()
void UE::Insights::STableTreeView::CancelCurrentAsyncOp () protected
CanHideColumn()
bool UE::Insights::STableTreeView::CanHideColumn (const FName ColumnId) const protected
CanShowColumn()
bool UE::Insights::STableTreeView::CanShowColumn (const FName ColumnId) const protected
CanToggleColumnVisibility()
bool UE::Insights::STableTreeView::CanToggleColumnVisibility (const FName ColumnId) const protected
ClearInProgressAsyncOperations()
void UE::Insights::STableTreeView::ClearInProgressAsyncOperations () inline protected
Definition at line 447 of file STableTreeView.h.
References EAsyncOperationType::EAsyncOperationType, and InProgressAsyncOperations.
ConstructExtraToolbar()
virtual TSharedPtr< SWidget > UE::Insights::STableTreeView::ConstructExtraToolbar () inline protected virtual
Definition at line 197 of file STableTreeView.h.
ConstructFilterConfiguratorButton()
virtual TSharedRef< SWidget > UE::Insights::STableTreeView::ConstructFilterConfiguratorButton () protected virtual
ConstructFilterToolbar()
virtual TSharedPtr< SWidget > UE::Insights::STableTreeView::ConstructFilterToolbar () protected virtual
ConstructFooter()
virtual TSharedPtr< SWidget > UE::Insights::STableTreeView::ConstructFooter () inline protected virtual
Definition at line 198 of file STableTreeView.h.
ConstructFooterArea()
virtual void UE::Insights::STableTreeView::ConstructFooterArea (TSharedRef< SVerticalBox > InHostBox) protected virtual
ConstructHeaderArea()
virtual void UE::Insights::STableTreeView::ConstructHeaderArea (TSharedRef< SVerticalBox > InHostBox) protected virtual
ConstructHierarchyBreadcrumbTrail()
virtual TSharedRef< SWidget > UE::Insights::STableTreeView::ConstructHierarchyBreadcrumbTrail () protected virtual
ConstructSearchBox()
virtual TSharedRef< SWidget > UE::Insights::STableTreeView::ConstructSearchBox () protected virtual
ConstructToolbar()
virtual TSharedPtr< SWidget > UE::Insights::STableTreeView::ConstructToolbar () inline protected virtual
Reimplemented in UE::Insights::SUntypedDiffTableTreeView.
Definition at line 196 of file STableTreeView.h.
ConstructViewPreset()
void UE::Insights::STableTreeView::ConstructViewPreset (TSharedPtr< SHorizontalBox > InHorizontalBox, float InMinDesiredWidth = 50.0f) protected
ConstructWidget()
virtual void UE::Insights::STableTreeView::ConstructWidget (TSharedPtr< FTable > InTablePtr) protected virtual
References InTablePtr.
ContextMenu_CollapseSubtree_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_CollapseSubtree_CanExecute () const protected
ContextMenu_CollapseSubtree_Execute()
void UE::Insights::STableTreeView::ContextMenu_CollapseSubtree_Execute () protected
ContextMenu_CopyColumnToClipboard_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_CopyColumnToClipboard_CanExecute () const protected
ContextMenu_CopyColumnToClipboard_Execute()
void UE::Insights::STableTreeView::ContextMenu_CopyColumnToClipboard_Execute () protected
ContextMenu_CopyColumnTooltipToClipboard_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_CopyColumnTooltipToClipboard_CanExecute () const protected
ContextMenu_CopyColumnTooltipToClipboard_Execute()
void UE::Insights::STableTreeView::ContextMenu_CopyColumnTooltipToClipboard_Execute () protected
ContextMenu_CopySelectedToClipboard_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_CopySelectedToClipboard_CanExecute () const protected
ContextMenu_CopySelectedToClipboard_Execute()
void UE::Insights::STableTreeView::ContextMenu_CopySelectedToClipboard_Execute () protected
ContextMenu_ExpandCriticalPath_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_ExpandCriticalPath_CanExecute () const protected
ContextMenu_ExpandCriticalPath_Execute()
void UE::Insights::STableTreeView::ContextMenu_ExpandCriticalPath_Execute () protected
ContextMenu_ExpandSubtree_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_ExpandSubtree_CanExecute () const protected
ContextMenu_ExpandSubtree_Execute()
void UE::Insights::STableTreeView::ContextMenu_ExpandSubtree_Execute () protected
ContextMenu_ExportToFile_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_ExportToFile_CanExecute () const protected
ContextMenu_ExportToFile_Execute()
void UE::Insights::STableTreeView::ContextMenu_ExportToFile_Execute (bool bInExportCollapsed, bool InExportLeafs) protected
ContextMenu_HideAllColumns_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_HideAllColumns_CanExecute () const protected
ContextMenu_HideAllColumns_Execute()
void UE::Insights::STableTreeView::ContextMenu_HideAllColumns_Execute () protected
ContextMenu_ResetColumns_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_ResetColumns_CanExecute () const protected
ContextMenu_ResetColumns_Execute()
void UE::Insights::STableTreeView::ContextMenu_ResetColumns_Execute () protected
ContextMenu_ShowAllColumns_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_ShowAllColumns_CanExecute () const protected
ContextMenu_ShowAllColumns_Execute()
void UE::Insights::STableTreeView::ContextMenu_ShowAllColumns_Execute () protected
ContextMenu_SortByColumn_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_SortByColumn_CanExecute (const FName ColumnId) const protected
ContextMenu_SortByColumn_Execute()
void UE::Insights::STableTreeView::ContextMenu_SortByColumn_Execute (const FName ColumnId) protected
ContextMenu_SortByColumn_IsChecked()
bool UE::Insights::STableTreeView::ContextMenu_SortByColumn_IsChecked (const FName ColumnId) protected
ContextMenu_SortMode_CanExecute()
bool UE::Insights::STableTreeView::ContextMenu_SortMode_CanExecute (const EColumnSortMode::Type InSortMode) const protected
ContextMenu_SortMode_Execute()
void UE::Insights::STableTreeView::ContextMenu_SortMode_Execute (const EColumnSortMode::Type InSortMode) protected
ContextMenu_SortMode_IsChecked()
bool UE::Insights::STableTreeView::ContextMenu_SortMode_IsChecked (const EColumnSortMode::Type InSortMode) protected
CountNumNodesPerDepthRec()
void UE::Insights::STableTreeView::CountNumNodesPerDepthRec (FBaseTreeNode * InRoot, TArray< int32 > & InOutNumNodesPerDepth, int32 InDepth, int32 InMaxDepth, int32 InMaxNodes) const protected
CreateGroupings()
void UE::Insights::STableTreeView::CreateGroupings () protected
CreateGroups()
void UE::Insights::STableTreeView::CreateGroups (const TArray< TSharedPtr< FTreeNodeGrouping > > & Groupings) protected
CreateSortings()
void UE::Insights::STableTreeView::CreateSortings () protected
ExportToFileRec()
void UE::Insights::STableTreeView::ExportToFileRec (const FBaseTreeNodePtr & InGroupNode, TArray< FBaseTreeNodePtr > & InNodes, bool bInExportCollapsed, bool InExportLeafs, WriteToFileCallback Callback) protected
ExtendMenu() [1/2]
virtual void UE::Insights::STableTreeView::ExtendMenu (FMenuBuilder & Menu) inline protected virtual
Definition at line 460 of file STableTreeView.h.
References Menu.
ExtendMenu() [2/2]
virtual void UE::Insights::STableTreeView::ExtendMenu (TSharedRef< FExtender > Extender) inline protected virtual
Definition at line 459 of file STableTreeView.h.
FilterConfigurator_OnClicked()
FReply UE::Insights::STableTreeView::FilterConfigurator_OnClicked () protected
FilterNode()
virtual bool UE::Insights::STableTreeView::FilterNode (const FFilterConfigurator & InFilterConfigurator, const FTableTreeNode & InNode) const protected virtual
FilterNodeCustom()
virtual bool UE::Insights::STableTreeView::FilterNodeCustom (const FTableTreeNode & InNode) const inline protected virtual
Definition at line 284 of file STableTreeView.h.
GetAllOperationsDuration()
virtual double UE::Insights::STableTreeView::GetAllOperationsDuration () override virtual
Implements UE::Insights::IAsyncOperationStatusProvider.
Reimplemented in UE::Insights::SUntypedTableTreeView.
GetAvailableGroupings()
const TArray< TSharedPtr< FTreeNodeGrouping > > & UE::Insights::STableTreeView::GetAvailableGroupings () const inline
Gets the available groupings.
Definition at line 185 of file STableTreeView.h.
References AvailableGroupings.
GetAvailableViewPresets()
const TArray< TSharedRef< ITableTreeViewPreset > > * UE::Insights::STableTreeView::GetAvailableViewPresets () const inline protected
Definition at line 472 of file STableTreeView.h.
References AvailableViewPresets.
GetColumnHeaderText()
FText UE::Insights::STableTreeView::GetColumnHeaderText (const FName ColumnId) const protected
GetCurrentOperationDuration()
virtual double UE::Insights::STableTreeView::GetCurrentOperationDuration () inline override virtual
Implements UE::Insights::IAsyncOperationStatusProvider.
Reimplemented in UE::Insights::SUntypedTableTreeView.
Definition at line 171 of file STableTreeView.h.
GetCurrentOperationName()
virtual FText UE::Insights::STableTreeView::GetCurrentOperationName () const override virtual
Implements UE::Insights::IAsyncOperationStatusProvider.
Reimplemented in UE::Insights::SUntypedTableTreeView.
GetDefaultColumnBeingSorted()
const FName UE::Insights::STableTreeView::GetDefaultColumnBeingSorted () static protected
GetDefaultColumnSortMode()
const EColumnSortMode::Type UE::Insights::STableTreeView::GetDefaultColumnSortMode () static protected
GetGroupingCrumbMenuContent()
TSharedRef< SWidget > UE::Insights::STableTreeView::GetGroupingCrumbMenuContent (const TSharedPtr< FTreeNodeGrouping > & CrumbGrouping) protected
GetGroupingDepth()
int32 UE::Insights::STableTreeView::GetGroupingDepth (const TSharedPtr< FTreeNodeGrouping > & Grouping) const protected
References UE::Insights::Grouping.
GetInnerTreeView()
TSharedPtr< STreeView< FTableTreeNodePtr > > UE::Insights::STableTreeView::GetInnerTreeView () const inline
Definition at line 133 of file STableTreeView.h.
References GetInnerTreeView(), and TreeView.
Referenced by GetInnerTreeView().
GetLogListingName()
const FName & UE::Insights::STableTreeView::GetLogListingName () inline
Definition at line 179 of file STableTreeView.h.
References LogListingName.
GetNodeByTableRowIndex()
FTableTreeNodePtr UE::Insights::STableTreeView::GetNodeByTableRowIndex (int32 RowIndex) const
GetOperationCount()
virtual uint32 UE::Insights::STableTreeView::GetOperationCount () const inline override virtual
Implements UE::Insights::IAsyncOperationStatusProvider.
Reimplemented in UE::Insights::SUntypedTableTreeView.
Definition at line 172 of file STableTreeView.h.
GetSelectedViewPreset()
TSharedPtr< ITableTreeViewPreset > UE::Insights::STableTreeView::GetSelectedViewPreset () const protected
GetSortModeForColumn()
EColumnSortMode::Type UE::Insights::STableTreeView::GetSortModeForColumn (const FName ColumnId) const protected
GetTable() [1/2]
TSharedPtr< FTable > & UE::Insights::STableTreeView::GetTable () inline
Definition at line 135 of file STableTreeView.h.
References Table.
Referenced by UE::Insights::SUntypedTableTreeView::GetUntypedTable().
GetTable() [2/2]
const TSharedPtr< FTable > & UE::Insights::STableTreeView::GetTable () const inline
Definition at line 136 of file STableTreeView.h.
References Table.
GetTableRowNodes()
const TArray< FTableTreeNodePtr > & UE::Insights::STableTreeView::GetTableRowNodes () const inline
Gets the table row nodes.
Each node corresponds to a table row. Index in this array corresponds to RowIndex in source table.
Definition at line 182 of file STableTreeView.h.
References TableRowNodes.
GetTreeViewBannerText()
FText UE::Insights::STableTreeView::GetTreeViewBannerText () const inline protected
Definition at line 465 of file STableTreeView.h.
References TreeViewBannerText.
GroupingCrumbMenu_Add_CanExecute()
bool UE::Insights::STableTreeView::GroupingCrumbMenu_Add_CanExecute (const TSharedPtr< FTreeNodeGrouping > Grouping, const TSharedPtr< FTreeNodeGrouping > AfterGrouping) const protected
References UE::Insights::Grouping.
GroupingCrumbMenu_Add_Execute()
void UE::Insights::STableTreeView::GroupingCrumbMenu_Add_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping, const TSharedPtr< FTreeNodeGrouping > AfterGrouping) protected
References UE::Insights::Grouping.
GroupingCrumbMenu_Change_CanExecute()
bool UE::Insights::STableTreeView::GroupingCrumbMenu_Change_CanExecute (const TSharedPtr< FTreeNodeGrouping > OldGrouping, const TSharedPtr< FTreeNodeGrouping > NewGrouping) const protected
GroupingCrumbMenu_Change_Execute()
void UE::Insights::STableTreeView::GroupingCrumbMenu_Change_Execute (const TSharedPtr< FTreeNodeGrouping > OldGrouping, const TSharedPtr< FTreeNodeGrouping > NewGrouping) protected
GroupingCrumbMenu_MoveLeft_Execute()
void UE::Insights::STableTreeView::GroupingCrumbMenu_MoveLeft_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping) protected
References UE::Insights::Grouping.
GroupingCrumbMenu_MoveRight_Execute()
void UE::Insights::STableTreeView::GroupingCrumbMenu_MoveRight_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping) protected
References UE::Insights::Grouping.
GroupingCrumbMenu_Remove_Execute()
void UE::Insights::STableTreeView::GroupingCrumbMenu_Remove_Execute (const TSharedPtr< FTreeNodeGrouping > Grouping) protected
References UE::Insights::Grouping.
GroupingCrumbMenu_Reset_Execute()
void UE::Insights::STableTreeView::GroupingCrumbMenu_Reset_Execute () protected
GroupNodesRec()
void UE::Insights::STableTreeView::GroupNodesRec (const TArray< FTableTreeNodePtr > & Nodes, FTableTreeNode & ParentGroup, int32 GroupingDepth, const TArray< TSharedPtr< FTreeNodeGrouping > > & Groupings) protected
HandleItemToStringArray()
void UE::Insights::STableTreeView::HandleItemToStringArray (const FTableTreeNodePtr & GroupOrStatNodePtr, TArray< FString > & OutSearchStrings) static protected
Populates OutSearchStrings with the strings that should be used in searching.
Parameters
GroupOrStatNodePtr - the group and stat node to get a text description from.
OutSearchStrings - an array of strings to use in searching.
HasCustomNodeFilter()
virtual bool UE::Insights::STableTreeView::HasCustomNodeFilter () const inline protected virtual
Definition at line 283 of file STableTreeView.h.
HasInProgressAsyncOperation()
bool UE::Insights::STableTreeView::HasInProgressAsyncOperation (EAsyncOperationType InType) const inline protected
Definition at line 446 of file STableTreeView.h.
References EAsyncOperationType::EAsyncOperationType, EnumHasAnyFlags(), and InProgressAsyncOperations.
HeaderMenu_SortMode_CanExecute()
bool UE::Insights::STableTreeView::HeaderMenu_SortMode_CanExecute (const FName ColumnId, const EColumnSortMode::Type InSortMode) const protected
HeaderMenu_SortMode_Execute()
void UE::Insights::STableTreeView::HeaderMenu_SortMode_Execute (const FName ColumnId, const EColumnSortMode::Type InSortMode) protected
HeaderMenu_SortMode_IsChecked()
bool UE::Insights::STableTreeView::HeaderMenu_SortMode_IsChecked (const FName ColumnId, const EColumnSortMode::Type InSortMode) protected
HideColumn() [1/2]
void UE::Insights::STableTreeView::HideColumn (const FName ColumnId) protected
HideColumn() [2/2]
void UE::Insights::STableTreeView::HideColumn (FTableColumn & Column) protected
InitAvailableViewPresets()
virtual void UE::Insights::STableTreeView::InitAvailableViewPresets () inline protected virtual
Definition at line 471 of file STableTreeView.h.
InitCommandList()
void UE::Insights::STableTreeView::InitCommandList () protected
InitFilterConfigurator()
virtual void UE::Insights::STableTreeView::InitFilterConfigurator (FFilterConfigurator & InOutFilterConfigurator) protected virtual
InitHierarchyFiltering()
void UE::Insights::STableTreeView::InitHierarchyFiltering () protected
InitializeAndShowHeaderColumns()
void UE::Insights::STableTreeView::InitializeAndShowHeaderColumns () protected
InitNodeFiltering()
void UE::Insights::STableTreeView::InitNodeFiltering () protected
InternalCreateGroupings()
virtual void UE::Insights::STableTreeView::InternalCreateGroupings () protected virtual
IsColumnVisible()
bool UE::Insights::STableTreeView::IsColumnVisible (const FName ColumnId) protected
IsRunning()
virtual bool UE::Insights::STableTreeView::IsRunning () const inline override virtual
Implements UE::Insights::IAsyncOperationStatusProvider.
Reimplemented in UE::Insights::SUntypedTableTreeView.
Definition at line 168 of file STableTreeView.h.
References bIsUpdateRunning.
IsRunningAsyncUpdate()
bool UE::Insights::STableTreeView::IsRunningAsyncUpdate () inline
Definition at line 159 of file STableTreeView.h.
References bIsUpdateRunning.
MakeSubtreeVisible()
bool UE::Insights::STableTreeView::MakeSubtreeVisible (FTableTreeNodePtr NodePtr, bool bFilterIsEmpty) protected
Set all the nodes belonging to a subtree as visible.
Returns true if the caller node should be expanded.
OnClose()
void UE::Insights::STableTreeView::OnClose ()
OnGroupingChanged()
void UE::Insights::STableTreeView::OnGroupingChanged () protected
OnGroupingCrumbClicked()
void UE::Insights::STableTreeView::OnGroupingCrumbClicked (const TSharedPtr< FTreeNodeGrouping > & InEntry) protected
OnHierarchyFilteringChanged()
void UE::Insights::STableTreeView::OnHierarchyFilteringChanged () protected
OnKeyDown()
virtual FReply UE::Insights::STableTreeView::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnNodeFilteringChanged()
void UE::Insights::STableTreeView::OnNodeFilteringChanged () protected
OnPostAsyncUpdate()
virtual void UE::Insights::STableTreeView::OnPostAsyncUpdate () protected virtual
OnPreAsyncUpdate()
virtual void UE::Insights::STableTreeView::OnPreAsyncUpdate () protected virtual
OnSortingChanged()
void UE::Insights::STableTreeView::OnSortingChanged () protected
OnSortModeChanged()
void UE::Insights::STableTreeView::OnSortModeChanged (const EColumnSortPriority::Type SortPriority, const FName & ColumnId, const EColumnSortMode::Type SortMode) protected
PostChangeGroupings()
void UE::Insights::STableTreeView::PostChangeGroupings () protected
PreChangeGroupings()
void UE::Insights::STableTreeView::PreChangeGroupings () protected
RebuildColumns()
void UE::Insights::STableTreeView::RebuildColumns ()
RebuildGroupingCrumbs()
void UE::Insights::STableTreeView::RebuildGroupingCrumbs () protected
RebuildTree()
virtual void UE::Insights::STableTreeView::RebuildTree (bool bResync) virtual
Rebuilds the tree (if necessary).
Parameters
bResync - If true, it forces a resync even if the list did not changed since last sync.
Reimplemented in UE::Insights::SUntypedTableTreeView.
Reset()
virtual void UE::Insights::STableTreeView::Reset () virtual
Reimplemented in UE::Insights::SUntypedTableTreeView.
ScheduleGroupingAsyncOperation()
void UE::Insights::STableTreeView::ScheduleGroupingAsyncOperation () protected
ScheduleGroupingAsyncOperationIfNeeded()
bool UE::Insights::STableTreeView::ScheduleGroupingAsyncOperationIfNeeded () protected
ScheduleHierarchyFilteringAsyncOperation()
void UE::Insights::STableTreeView::ScheduleHierarchyFilteringAsyncOperation () protected
ScheduleHierarchyFilteringAsyncOperationIfNeeded()
bool UE::Insights::STableTreeView::ScheduleHierarchyFilteringAsyncOperationIfNeeded () protected
ScheduleNodeFilteringAsyncOperation()
void UE::Insights::STableTreeView::ScheduleNodeFilteringAsyncOperation () protected
ScheduleNodeFilteringAsyncOperationIfNeeded()
bool UE::Insights::STableTreeView::ScheduleNodeFilteringAsyncOperationIfNeeded () protected
ScheduleSortingAsyncOperation()
void UE::Insights::STableTreeView::ScheduleSortingAsyncOperation () protected
ScheduleSortingAsyncOperationIfNeeded()
bool UE::Insights::STableTreeView::ScheduleSortingAsyncOperationIfNeeded () protected
SearchBox_OnTextChanged()
void UE::Insights::STableTreeView::SearchBox_OnTextChanged (const FText & InFilterText) protected
SearchForItem()
virtual void UE::Insights::STableTreeView::SearchForItem (TSharedPtr< FTableTaskCancellationToken > CancellationToken) inline protected virtual
Definition at line 485 of file STableTreeView.h.
SelectNodeByTableRowIndex()
void UE::Insights::STableTreeView::SelectNodeByTableRowIndex (int32 RowIndex)
SelectViewPreset()
void UE::Insights::STableTreeView::SelectViewPreset (TSharedPtr< ITableTreeViewPreset > InPreset) protected
SetCurrentGroupings()
void UE::Insights::STableTreeView::SetCurrentGroupings (TArray< TSharedPtr< FTreeNodeGrouping > > & InCurrentGroupings)
Sets the current groupings.
SetExpandValueForChildGroups()
void UE::Insights::STableTreeView::SetExpandValueForChildGroups (FBaseTreeNode * InRoot, int32 InMaxExpandedNodes, int32 MaxDepthToExpand, bool InValue) protected
References MaxDepthToExpand.
SetExpandValueForChildGroupsRec()
void UE::Insights::STableTreeView::SetExpandValueForChildGroupsRec (FBaseTreeNode * InRoot, int32 InDepth, int32 InMaxDepth, bool InValue) protected
SetLogListingName()
void UE::Insights::STableTreeView::SetLogListingName (const FName & InLogListingName) inline
Sets a log listing name to be used for any errors or warnings.
Must be preregistered by the caller with the MessageLog module.
Definition at line 178 of file STableTreeView.h.
References LogListingName.
SetSortModeForColumn()
void UE::Insights::STableTreeView::SetSortModeForColumn (const FName & ColumnId, EColumnSortMode::Type SortMode) protected
ShowColumn() [1/2]
void UE::Insights::STableTreeView::ShowColumn (const FName ColumnId) protected
ShowColumn() [2/2]
void UE::Insights::STableTreeView::ShowColumn (FTableColumn & Column) protected
SLATE_BEGIN_ARGS()
UE::Insights::STableTreeView::SLATE_BEGIN_ARGS (STableTreeView) inline
Definition at line 124 of file STableTreeView.h.
References STableTreeView().
SLATE_END_ARGS()
UE::Insights::STableTreeView::SLATE_END_ARGS () const &
Construct this widget.
Parameters
InArgs - The declaration data for this widget
SortTreeNodes()
void UE::Insights::STableTreeView::SortTreeNodes (ITableCellValueSorter * InSorter, EColumnSortMode::Type InColumnSortMode) protected
SortTreeNodesRec()
void UE::Insights::STableTreeView::SortTreeNodesRec (FTableTreeNode & GroupNode, const ITableCellValueSorter & Sorter, EColumnSortMode::Type InColumnSortMode) protected
StartGroupingTask()
FGraphEventRef UE::Insights::STableTreeView::StartGroupingTask (FGraphEventRef Prerequisite = nullptr) protected
StartHierarchyFilteringTask()
FGraphEventRef UE::Insights::STableTreeView::StartHierarchyFilteringTask (FGraphEventRef Prerequisite = nullptr) protected
StartNodeFilteringTask()
FGraphEventRef UE::Insights::STableTreeView::StartNodeFilteringTask (FGraphEventRef Prerequisite = nullptr) protected
StartPendingAsyncOperations()
void UE::Insights::STableTreeView::StartPendingAsyncOperations () protected
StartSortingTask()
FGraphEventRef UE::Insights::STableTreeView::StartSortingTask (FGraphEventRef Prerequisite = nullptr) protected
StartTableDataTask()
template<typename T, typename... TArgs> TSharedPtr< FTableTaskInfo > UE::Insights::STableTreeView::StartTableDataTask (TArgs &&... Args) inline protected
Definition at line 490 of file STableTreeView.h.
References TGraphTask< TTask >::FConstructor::ConstructAndDispatchWhenReady(), TGraphTask< TTask >::CreateTask(), DataTaskInfos, Forward(), Info, and MakeShared().
StopAllTableDataTasks()
void UE::Insights::STableTreeView::StopAllTableDataTasks (bool bWait = true) protected
References bWait.
TableRow_GetColumnOutlineHAlignment()
EHorizontalAlignment UE::Insights::STableTreeView::TableRow_GetColumnOutlineHAlignment (const FName ColumnId) const protected
TableRow_GetHighlightedNodeName()
FName UE::Insights::STableTreeView::TableRow_GetHighlightedNodeName () const protected
TableRow_GetHighlightText()
FText UE::Insights::STableTreeView::TableRow_GetHighlightText () const protected
TableRow_SetHoveredCell()
void UE::Insights::STableTreeView::TableRow_SetHoveredCell (TSharedPtr< FTable > TablePtr, TSharedPtr< FTableColumn > ColumnPtr, FTableTreeNodePtr NodePtr) protected
TableRow_ShouldBeEnabled()
bool UE::Insights::STableTreeView::TableRow_ShouldBeEnabled (FTableTreeNodePtr NodePtr) const protected
Tick()
virtual void UE::Insights::STableTreeView::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
ToggleColumnVisibility()
void UE::Insights::STableTreeView::ToggleColumnVisibility (const FName ColumnId) protected
TreeView_BuildExportMenu()
void UE::Insights::STableTreeView::TreeView_BuildExportMenu (FMenuBuilder & MenuBuilder) protected
TreeView_BuildSortByMenu()
void UE::Insights::STableTreeView::TreeView_BuildSortByMenu (FMenuBuilder & MenuBuilder) protected
TreeView_BuildViewColumnMenu()
void UE::Insights::STableTreeView::TreeView_BuildViewColumnMenu (FMenuBuilder & MenuBuilder) protected
TreeView_GetMenuContent()
TSharedPtr< SWidget > UE::Insights::STableTreeView::TreeView_GetMenuContent () protected
TreeView_OnExpansionChanged()
virtual void UE::Insights::STableTreeView::TreeView_OnExpansionChanged (FTableTreeNodePtr TreeNode, bool bShouldBeExpanded) protected virtual
Called by STreeView when a tree node is expanded or collapsed.
TreeView_OnGenerateRow()
TSharedRef< ITableRow > UE::Insights::STableTreeView::TreeView_OnGenerateRow (FTableTreeNodePtr TreeNode, const TSharedRef< STableViewBase > & OwnerTable) protected
Called by STreeView to generate a table row for the specified item.
TreeView_OnGetChildren()
void UE::Insights::STableTreeView::TreeView_OnGetChildren (FTableTreeNodePtr InParent, TArray< FTableTreeNodePtr > & OutChildren) protected
Called by STreeView to retrieves the children for the specified parent item.
Parameters
InParent - The parent node to retrieve the children from.
OutChildren - List of children for the parent node.
TreeView_OnMouseButtonDoubleClick()
virtual void UE::Insights::STableTreeView::TreeView_OnMouseButtonDoubleClick (FTableTreeNodePtr TreeNode) protected virtual
Called by STreeView when a tree item is double clicked.
TreeView_OnSelectionChanged()
virtual void UE::Insights::STableTreeView::TreeView_OnSelectionChanged (FTableTreeNodePtr SelectedItem, ESelectInfo::Type SelectInfo) protected virtual
Called by STreeView when selection has changed.
TreeView_Refresh()
void UE::Insights::STableTreeView::TreeView_Refresh () protected
TreeViewHeaderRow_GenerateColumnMenu()
TSharedRef< SWidget > UE::Insights::STableTreeView::TreeViewHeaderRow_GenerateColumnMenu (const FTableColumn & Column) protected
UpdateAggregatedValues()
template<bool bIsRercursive> void UE::Insights::STableTreeView::UpdateAggregatedValues (TSharedPtr< FTable > InTable, FTableTreeNode & InOutGroupNode) static protected
UpdateAggregatedValuesRec()
void UE::Insights::STableTreeView::UpdateAggregatedValuesRec (FTableTreeNode & GroupNode) protected
UpdateAggregatedValuesSingleNode()
void UE::Insights::STableTreeView::UpdateAggregatedValuesSingleNode (FTableTreeNode & GroupNode) protected
UpdateAggregation()
template<typename T, bool bSetInitialValue, bool bIsRercursive> void UE::Insights::STableTreeView::UpdateAggregation (const FTableColumn & InColumn, FTableTreeNode & InOutGroupNode, const T InitialAggregatedValue, TFunctionRef< T(T, const FTableCellValue &)> ValueGetterFunc) static protected
UpdateBannerText()
virtual void UE::Insights::STableTreeView::UpdateBannerText () protected virtual
UpdateCStringSameValueAggregationRec()
void UE::Insights::STableTreeView::UpdateCStringSameValueAggregationRec (const FTableColumn & InColumn, FTableTreeNode & GroupNode) static protected
UpdateCStringSameValueAggregationSingleNode()
void UE::Insights::STableTreeView::UpdateCStringSameValueAggregationSingleNode (const FTableColumn & InColumn, FTableTreeNode & GroupNode) static protected
UpdateCurrentSortingByColumn()
void UE::Insights::STableTreeView::UpdateCurrentSortingByColumn () protected
UpdateFilterContext()
virtual void UE::Insights::STableTreeView::UpdateFilterContext (const FFilterConfigurator & InFilterConfigurator, const FTableTreeNode & InNode) const protected virtual
UpdateTree()
void UE::Insights::STableTreeView::UpdateTree () protected
ViewPreset_GetSelectedText()
FText UE::Insights::STableTreeView::ViewPreset_GetSelectedText () const protected
ViewPreset_GetSelectedToolTipText()
FText UE::Insights::STableTreeView::ViewPreset_GetSelectedToolTipText () const protected
ViewPreset_OnGenerateWidget()
TSharedRef< SWidget > UE::Insights::STableTreeView::ViewPreset_OnGenerateWidget (TSharedRef< ITableTreeViewPreset > InPreset) protected
ViewPreset_OnSelectionChanged()
void UE::Insights::STableTreeView::ViewPreset_OnSelectionChanged (TSharedPtr< ITableTreeViewPreset > InPreset, ESelectInfo::Type SelectInfo) protected
Friends And Related Symbol Documentation
FSearchForItemToSelectTask
friend class FSearchForItemToSelectTask friend
Definition at line 114 of file STableTreeView.h.
References FSearchForItemToSelectTask.
Referenced by FSearchForItemToSelectTask.
FSelectNodeByTableRowIndexTask
friend class FSelectNodeByTableRowIndexTask friend
Definition at line 115 of file STableTreeView.h.
References FSelectNodeByTableRowIndexTask.
Referenced by FSelectNodeByTableRowIndexTask.
FTableTreeViewAsyncCompleteTask
friend class FTableTreeViewAsyncCompleteTask friend
Definition at line 113 of file STableTreeView.h.
References FTableTreeViewAsyncCompleteTask.
Referenced by FTableTreeViewAsyncCompleteTask.
FTableTreeViewGroupingAsyncTask
friend class FTableTreeViewGroupingAsyncTask friend
Definition at line 111 of file STableTreeView.h.
References FTableTreeViewGroupingAsyncTask.
Referenced by FTableTreeViewGroupingAsyncTask.
FTableTreeViewHierarchyFilteringAsyncTask
friend class FTableTreeViewHierarchyFilteringAsyncTask friend
Definition at line 112 of file STableTreeView.h.
References FTableTreeViewHierarchyFilteringAsyncTask.
Referenced by FTableTreeViewHierarchyFilteringAsyncTask.
FTableTreeViewNodeFilteringAsyncTask
friend class FTableTreeViewNodeFilteringAsyncTask friend
Definition at line 109 of file STableTreeView.h.
References FTableTreeViewNodeFilteringAsyncTask.
Referenced by FTableTreeViewNodeFilteringAsyncTask.
FTableTreeViewSortingAsyncTask
friend class FTableTreeViewSortingAsyncTask friend
Definition at line 110 of file STableTreeView.h.
References FTableTreeViewSortingAsyncTask.
Referenced by FTableTreeViewSortingAsyncTask.
Field Documentation
AsyncCompleteTaskEvent
FGraphEventRef UE::Insights::STableTreeView::AsyncCompleteTaskEvent protected
Definition at line 631 of file STableTreeView.h.
AsyncOperationProgress
FAsyncOperationProgress UE::Insights::STableTreeView::AsyncOperationProgress protected
Definition at line 635 of file STableTreeView.h.
AsyncOperationStatus
TSharedPtr<class SAsyncOperationStatus> UE::Insights::STableTreeView::AsyncOperationStatus protected
Definition at line 633 of file STableTreeView.h.
AsyncUpdateStopwatch
FStopwatch UE::Insights::STableTreeView::AsyncUpdateStopwatch protected
Definition at line 634 of file STableTreeView.h.
AvailableGroupings
TArray<TSharedPtr<FTreeNodeGrouping> > UE::Insights::STableTreeView::AvailableGroupings protected
Definition at line 591 of file STableTreeView.h.
Referenced by GetAvailableGroupings().
AvailableSorters
TArray<TSharedPtr<ITableCellValueSorter> > UE::Insights::STableTreeView::AvailableSorters protected
All available sorters.
Definition at line 605 of file STableTreeView.h.
AvailableViewPresets
TArray<TSharedRef<ITableTreeViewPreset> > UE::Insights::STableTreeView::AvailableViewPresets protected
Definition at line 644 of file STableTreeView.h.
Referenced by GetAvailableViewPresets().
bExpansionSaved
bool UE::Insights::STableTreeView::bExpansionSaved = false protected
If true, the expanded nodes have been saved before applying a text filter.
Only used when bRunInAsyncMode==false.
Definition at line 555 of file STableTreeView.h.
bIsCloseScheduled
bool UE::Insights::STableTreeView::bIsCloseScheduled = false protected
Definition at line 627 of file STableTreeView.h.
bIsUpdateRunning
bool UE::Insights::STableTreeView::bIsUpdateRunning = false protected
Definition at line 626 of file STableTreeView.h.
Referenced by IsRunning(), and IsRunningAsyncUpdate().
bRunInAsyncMode
bool UE::Insights::STableTreeView::bRunInAsyncMode = false protected
Definition at line 625 of file STableTreeView.h.
ColumnBeingSorted
FName UE::Insights::STableTreeView::ColumnBeingSorted protected
Name of the column currently being sorted.
Can be NAME_None if sorting is disabled (CurrentSorting == nullptr) or if a complex sorting is used (CurrentSorting != nullptr).
Definition at line 611 of file STableTreeView.h.
ColumnSortMode
EColumnSortMode::Type UE::Insights::STableTreeView::ColumnSortMode = EColumnSortMode::None protected
How we sort the nodes?
Ascending or Descending.
Definition at line 614 of file STableTreeView.h.
CommandList
TSharedPtr<FUICommandList> UE::Insights::STableTreeView::CommandList protected
Definition at line 505 of file STableTreeView.h.
CurrentAsyncOpColumnSortMode
EColumnSortMode::Type UE::Insights::STableTreeView::CurrentAsyncOpColumnSortMode protected
The sort mode actually used in the Sorting async task.
Definition at line 620 of file STableTreeView.h.
CurrentAsyncOpFilterConfigurator
FFilterConfigurator* UE::Insights::STableTreeView::CurrentAsyncOpFilterConfigurator = nullptr protected
The filter configurator actually used in the Hierarchy Filtering async task.
Definition at line 584 of file STableTreeView.h.
CurrentAsyncOpGroupings
TArray<TSharedPtr<FTreeNodeGrouping> > UE::Insights::STableTreeView::CurrentAsyncOpGroupings protected
The groupings actually used in the Grouping async task.
Definition at line 599 of file STableTreeView.h.
CurrentAsyncOpSorter
ITableCellValueSorter* UE::Insights::STableTreeView::CurrentAsyncOpSorter = nullptr protected
The sorter actually used in the Sorting async task.
Definition at line 617 of file STableTreeView.h.
CurrentAsyncOpTextFilter
TSharedPtr<FTableTreeNodeTextFilter> UE::Insights::STableTreeView::CurrentAsyncOpTextFilter protected
The text based filter actually used in the Hierarchy Filtering async task.
Definition at line 575 of file STableTreeView.h.
CurrentGroupings
TArray<TSharedPtr<FTreeNodeGrouping> > UE::Insights::STableTreeView::CurrentGroupings protected
How we group the tree nodes?
Definition at line 594 of file STableTreeView.h.
CurrentSorter
TSharedPtr<ITableCellValueSorter> UE::Insights::STableTreeView::CurrentSorter protected
Current sorter.
It is nullptr if sorting is disabled.
Definition at line 608 of file STableTreeView.h.
DataTaskInfos
TArray<TSharedPtr<FTableTaskInfo> > UE::Insights::STableTreeView::DataTaskInfos protected
Definition at line 637 of file STableTreeView.h.
Referenced by StartTableDataTask().
DispatchEvent
FGraphEventRef UE::Insights::STableTreeView::DispatchEvent protected
Definition at line 636 of file STableTreeView.h.
DummyGroupNodes
TArray<FTableTreeNodePtr> UE::Insights::STableTreeView::DummyGroupNodes protected
Definition at line 629 of file STableTreeView.h.
ExpandedNodes
TSet<FTableTreeNodePtr> UE::Insights::STableTreeView::ExpandedNodes protected
Currently expanded group nodes.
Definition at line 552 of file STableTreeView.h.
ExternalScrollbar
TSharedPtr<SScrollBar> UE::Insights::STableTreeView::ExternalScrollbar protected
External scrollbar used to synchronize tree view position.
Definition at line 517 of file STableTreeView.h.
FilterConfigurator
TSharedPtr<FFilterConfigurator> UE::Insights::STableTreeView::FilterConfigurator protected
Definition at line 580 of file STableTreeView.h.
FilterContext
FFilterContext UE::Insights::STableTreeView::FilterContext mutable protected
Definition at line 586 of file STableTreeView.h.
FilteredGroupNodes
TArray<FTableTreeNodePtr> UE::Insights::STableTreeView::FilteredGroupNodes protected
A filtered array of group nodes to be displayed in the tree widget.
Definition at line 549 of file STableTreeView.h.
FilteredNodes
TArray<FTableTreeNodePtr> UE::Insights::STableTreeView::FilteredNodes protected
Filtered table nodes.
These are the nodes from the TableRowNodes array, after applying the node filtering.
Definition at line 543 of file STableTreeView.h.
FilteredNodesPtr
TArray<FTableTreeNodePtr>* UE::Insights::STableTreeView::FilteredNodesPtr = nullptr protected
A pointer to the filtered table nodes.
If node filtering is empty, this points directly to TableRowNodes.
Definition at line 546 of file STableTreeView.h.
Filters
TSharedPtr<FTableTreeNodeFilterCollection> UE::Insights::STableTreeView::Filters protected
The filter collection.
Definition at line 569 of file STableTreeView.h.
GroupingBreadcrumbTrail
TSharedPtr<SBreadcrumbTrail<TSharedPtr<FTreeNodeGrouping> > > UE::Insights::STableTreeView::GroupingBreadcrumbTrail protected
Definition at line 596 of file STableTreeView.h.
HighlightedNodeName
FName UE::Insights::STableTreeView::HighlightedNodeName protected
Name of the tree node that should be drawn as highlighted.
Definition at line 529 of file STableTreeView.h.
HoveredColumnId
FName UE::Insights::STableTreeView::HoveredColumnId protected
Name of the column currently being hovered by the mouse.
Definition at line 523 of file STableTreeView.h.
HoveredNodePtr
FTableTreeNodePtr UE::Insights::STableTreeView::HoveredNodePtr protected
A shared pointer to the tree node currently being hovered by the mouse.
Definition at line 526 of file STableTreeView.h.
InProgressAsyncOperationEvent
FGraphEventRef UE::Insights::STableTreeView::InProgressAsyncOperationEvent protected
Definition at line 630 of file STableTreeView.h.
InProgressAsyncOperations
EAsyncOperationType UE::Insights::STableTreeView::InProgressAsyncOperations = static_cast<EAsyncOperationType>(0) protected
Definition at line 632 of file STableTreeView.h.
Referenced by AddInProgressAsyncOperation(), ClearInProgressAsyncOperations(), and HasInProgressAsyncOperation().
InTablePtr
TSharedPtr<FTable> UE::Insights::STableTreeView::InTablePtr
Definition at line 131 of file STableTreeView.h.
Referenced by ConstructWidget().
LogListingName
FName UE::Insights::STableTreeView::LogListingName protected
A log listing name to be used for any errors or warnings.
Definition at line 652 of file STableTreeView.h.
Referenced by GetLogListingName(), and SetLogListingName().
MaxDepthToAutoExpand
int32 UE::Insights::STableTreeView::MaxDepthToAutoExpand = 4 protected
Definition at line 558 of file STableTreeView.h.
MaxDepthToExpand
int32 UE::Insights::STableTreeView::MaxDepthToExpand = 100 protected
Definition at line 560 of file STableTreeView.h.
Referenced by SetExpandValueForChildGroups().
MaxNodesToAutoExpand
int32 UE::Insights::STableTreeView::MaxNodesToAutoExpand = 1000 protected
Definition at line 557 of file STableTreeView.h.
MaxNodesToExpand
int32 UE::Insights::STableTreeView::MaxNodesToExpand = 1000000 protected
Definition at line 559 of file STableTreeView.h.
NodesToExpand
TArray<FTableTreeNodePtr> UE::Insights::STableTreeView::NodesToExpand protected
Definition at line 638 of file STableTreeView.h.
OnFilterChangesCommittedHandle
FDelegateHandle UE::Insights::STableTreeView::OnFilterChangesCommittedHandle protected
Definition at line 581 of file STableTreeView.h.
PresetComboBox
TSharedPtr<SComboBox<TSharedRef<ITableTreeViewPreset> > > UE::Insights::STableTreeView::PresetComboBox protected
Definition at line 646 of file STableTreeView.h.
Root
FTableTreeNodePtr UE::Insights::STableTreeView::Root protected
The root node of the tree.
It is invisible; only its children are displayed in the tree view.
Definition at line 537 of file STableTreeView.h.
RootNodeName
const FName UE::Insights::STableTreeView::RootNodeName static protected
Definition at line 534 of file STableTreeView.h.
SearchBox
TSharedPtr<SSearchBox> UE::Insights::STableTreeView::SearchBox protected
The search box widget used to filter items displayed in the stats and groups tree.
Definition at line 566 of file STableTreeView.h.
SelectedViewPreset
TSharedPtr<ITableTreeViewPreset> UE::Insights::STableTreeView::SelectedViewPreset protected
Definition at line 645 of file STableTreeView.h.
Table
TSharedPtr<FTable> UE::Insights::STableTreeView::Table protected
Table view model.
Definition at line 503 of file STableTreeView.h.
Referenced by GetTable(), and GetTable().
TableRowNodes
TArray<FTableTreeNodePtr> UE::Insights::STableTreeView::TableRowNodes protected
Table row nodes.
Each node corresponds to a table row. Index in this array corresponds to RowIndex in source table.
Definition at line 540 of file STableTreeView.h.
Referenced by GetTableRowNodes().
TextFilter
TSharedPtr<FTableTreeNodeTextFilter> UE::Insights::STableTreeView::TextFilter protected
The text based filter.
Definition at line 572 of file STableTreeView.h.
TreeView
TSharedPtr<STreeView<FTableTreeNodePtr> > UE::Insights::STableTreeView::TreeView protected
The child STreeView widget.
Definition at line 511 of file STableTreeView.h.
Referenced by GetInnerTreeView().
TreeViewBannerText
FText UE::Insights::STableTreeView::TreeViewBannerText protected
Definition at line 642 of file STableTreeView.h.
Referenced by GetTreeViewBannerText().
TreeViewHeaderRow
TSharedPtr<SHeaderRow> UE::Insights::STableTreeView::TreeViewHeaderRow protected
Holds the tree view header row widget which display all columns in the tree view.
Definition at line 514 of file STableTreeView.h.
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Table/Widgets/STableTreeView.h