Unreal Engine 5.6 C++ API: FBinaryHeap< KeyType, IndexType > Class Template Reference
FBinaryHeap< KeyType, IndexType > Class Template Reference
#include "BinaryHeap.h"
Public Member Functions
FBinaryHeap ()
FBinaryHeap (const FBinaryHeap &)=delete
FBinaryHeap (FBinaryHeap &&Other)
FBinaryHeap (uint32 InHeapSize, uint32 InIndexSize)
~FBinaryHeap ()
void Add (KeyType Key, IndexType Index)
void Clear ()
void Free ()
uint32 GetHeapSize () const
uint32 GetIndexSize () const
KeyType GetKey (IndexType Index) const
bool IsEmpty () const
bool IsPresent (IndexType Index) const
uint32 Num () const
void operator= (const FBinaryHeap &)=delete
IndexType Peek (IndexType Index) const
void Pop ()
void Remove (IndexType Index)
void Resize (uint32 NewHeapSize, uint32 NewIndexSize)
IndexType Top () const
void Update (KeyType Key, IndexType Index)
Protected Member Functions
void DownHeap (IndexType HeapIndex)
void ResetInternal ()
Reset internal variables to a cleared state, does not free data.
void ResizeHeap (uint32 NewHeapSize)
void ResizeIndexes (uint32 NewIndexSize)
void UpHeap (IndexType HeapIndex)
Protected Attributes
IndexType * Heap
IndexType * HeapIndexes
uint32 HeapNum
uint32 HeapSize
uint32 IndexSize
KeyType * Keys
Detailed Description
template<typename KeyType, typename IndexType = uint32>
class FBinaryHeap< KeyType, IndexType >
Definition at line 19 of file BinaryHeap.h.
Constructor & Destructor Documentation
FBinaryHeap() [1/4]
template<typename KeyType, typename IndexType> FORCEINLINE FBinaryHeap< KeyType, IndexType >::FBinaryHeap () nodiscard
Definition at line 75 of file BinaryHeap.h.
References FORCEINLINE, and ResetInternal().
Referenced by FBinaryHeap(), FBinaryHeap(), and operator=().
FBinaryHeap() [2/4]
template<typename KeyType, typename IndexType> FORCEINLINE FBinaryHeap< KeyType, IndexType >::FBinaryHeap (uint32 InHeapSize, uint32 InIndexSize) nodiscard
Definition at line 81 of file BinaryHeap.h.
References FORCEINLINE, Heap, HeapIndexes, HeapNum, HeapSize, IndexSize, Keys, and FMemory::Memset().
~FBinaryHeap()
template<typename KeyType, typename IndexType> FORCEINLINE FBinaryHeap< KeyType, IndexType >::~FBinaryHeap ()
Definition at line 108 of file BinaryHeap.h.
References FORCEINLINE, and Free().
FBinaryHeap() [3/4]
template<typename KeyType, typename IndexType = uint32> FBinaryHeap< KeyType, IndexType >::FBinaryHeap (const FBinaryHeap< KeyType, IndexType > &) delete
References FBinaryHeap().
FBinaryHeap() [4/4]
template<typename KeyType, typename IndexType> FORCEINLINE FBinaryHeap< KeyType, IndexType >::FBinaryHeap (FBinaryHeap< KeyType, IndexType > && Other) nodiscard
Definition at line 94 of file BinaryHeap.h.
References FBinaryHeap(), FORCEINLINE, Heap, HeapIndexes, HeapNum, HeapSize, IndexSize, Keys, and Other.
Member Function Documentation
Add()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Add (KeyType Key, IndexType Index)
Definition at line 265 of file BinaryHeap.h.
References checkSlow, FORCEINLINE, Heap, HeapIndexes, HeapNum, HeapSize, IndexSize, IsPresent(), Key, Keys, FMath::Max, ResizeHeap(), ResizeIndexes(), and UpHeap().
Clear()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Clear ()
Definition at line 114 of file BinaryHeap.h.
References FORCEINLINE, HeapIndexes, HeapNum, IndexSize, and FMemory::Memset().
DownHeap()
template<typename KeyType, typename IndexType> void FBinaryHeap< KeyType, IndexType >::DownHeap (IndexType HeapIndex) protected
Definition at line 357 of file BinaryHeap.h.
References Heap, HeapIndexes, HeapNum, Keys, Left, Right, and Smallest.
Referenced by Pop(), Remove(), and Update().
Free()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Free ()
Definition at line 121 of file BinaryHeap.h.
References FORCEINLINE, Heap, HeapIndexes, Keys, and ResetInternal().
Referenced by ~FBinaryHeap().
GetHeapSize()
template<typename KeyType, typename IndexType = uint32> uint32 FBinaryHeap< KeyType, IndexType >::GetHeapSize () const inline nodiscard
Definition at line 38 of file BinaryHeap.h.
References HeapSize.
GetIndexSize()
template<typename KeyType, typename IndexType = uint32> uint32 FBinaryHeap< KeyType, IndexType >::GetIndexSize () const inline nodiscard
Definition at line 39 of file BinaryHeap.h.
References IndexSize.
GetKey()
template<typename KeyType, typename IndexType> FORCEINLINE KeyType FBinaryHeap< KeyType, IndexType >::GetKey (IndexType Index) const nodiscard
Definition at line 228 of file BinaryHeap.h.
References checkSlow, FORCEINLINE, IsPresent(), and Keys.
IsEmpty()
template<typename KeyType, typename IndexType = uint32> bool FBinaryHeap< KeyType, IndexType >::IsEmpty () const inline nodiscard
Definition at line 36 of file BinaryHeap.h.
References HeapNum.
IsPresent()
template<typename KeyType, typename IndexType> FORCEINLINE bool FBinaryHeap< KeyType, IndexType >::IsPresent (IndexType Index) const nodiscard
Definition at line 218 of file BinaryHeap.h.
References FORCEINLINE, HeapIndexes, and IndexSize.
Referenced by Add(), GetKey(), Remove(), and Update().
Num()
template<typename KeyType, typename IndexType = uint32> uint32 FBinaryHeap< KeyType, IndexType >::Num () const inline nodiscard
Definition at line 37 of file BinaryHeap.h.
References HeapNum.
operator=()
template<typename KeyType, typename IndexType = uint32> void FBinaryHeap< KeyType, IndexType >::operator= (const FBinaryHeap< KeyType, IndexType > &) delete
References FBinaryHeap(), and Other.
Peek()
template<typename KeyType, typename IndexType> FORCEINLINE IndexType FBinaryHeap< KeyType, IndexType >::Peek (IndexType Index) const nodiscard
Definition at line 235 of file BinaryHeap.h.
References checkSlow, FORCEINLINE, Heap, and HeapNum.
Pop()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Pop ()
Definition at line 250 of file BinaryHeap.h.
References checkSlow, DownHeap(), FORCEINLINE, Heap, HeapIndexes, and HeapNum.
Remove()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Remove (IndexType Index)
Definition at line 309 of file BinaryHeap.h.
References DownHeap(), FORCEINLINE, Heap, HeapIndexes, HeapNum, IsPresent(), Key, Keys, and UpHeap().
ResetInternal()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::ResetInternal () protected
Reset internal variables to a cleared state, does not free data.
Definition at line 395 of file BinaryHeap.h.
References FORCEINLINE, Heap, HeapIndexes, HeapNum, HeapSize, IndexSize, and Keys.
Referenced by FBinaryHeap(), and Free().
Resize()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Resize (uint32 NewHeapSize, uint32 NewIndexSize)
Definition at line 204 of file BinaryHeap.h.
References FORCEINLINE, HeapSize, IndexSize, ResizeHeap(), and ResizeIndexes().
ResizeHeap()
template<typename KeyType, typename IndexType> void FBinaryHeap< KeyType, IndexType >::ResizeHeap (uint32 NewHeapSize) protected
Definition at line 131 of file BinaryHeap.h.
References checkSlow, Heap, HeapNum, HeapSize, FMemory::Memcpy(), and FMath::Min.
Referenced by Add(), and Resize().
ResizeIndexes()
template<typename KeyType, typename IndexType> void FBinaryHeap< KeyType, IndexType >::ResizeIndexes (uint32 NewIndexSize) protected
Definition at line 160 of file BinaryHeap.h.
References check, checkSlow, HeapIndexes, IndexSize, and Keys.
Referenced by Add(), and Resize().
Top()
template<typename KeyType, typename IndexType> FORCEINLINE IndexType FBinaryHeap< KeyType, IndexType >::Top () const nodiscard
Definition at line 242 of file BinaryHeap.h.
References checkSlow, FORCEINLINE, Heap, and HeapNum.
Update()
template<typename KeyType, typename IndexType> FORCEINLINE void FBinaryHeap< KeyType, IndexType >::Update (KeyType Key, IndexType Index)
Definition at line 289 of file BinaryHeap.h.
References checkSlow, DownHeap(), FORCEINLINE, Heap, HeapIndexes, IsPresent(), Key, Keys, Parent, and UpHeap().
UpHeap()
template<typename KeyType, typename IndexType> void FBinaryHeap< KeyType, IndexType >::UpHeap (IndexType HeapIndex) protected
Definition at line 334 of file BinaryHeap.h.
References Heap, HeapIndexes, Keys, and Parent.
Referenced by Add(), Remove(), and Update().
Field Documentation
Heap
template<typename KeyType, typename IndexType = uint32> IndexType* FBinaryHeap< KeyType, IndexType >::Heap protected
Definition at line 68 of file BinaryHeap.h.
Referenced by FBinaryHeap(), FBinaryHeap(), Add(), DownHeap(), Free(), Peek(), Pop(), Remove(), ResetInternal(), ResizeHeap(), Top(), Update(), and UpHeap().
HeapIndexes
template<typename KeyType, typename IndexType = uint32> IndexType* FBinaryHeap< KeyType, IndexType >::HeapIndexes protected
Definition at line 71 of file BinaryHeap.h.
Referenced by FBinaryHeap(), FBinaryHeap(), Add(), Clear(), DownHeap(), Free(), IsPresent(), Pop(), Remove(), ResetInternal(), ResizeIndexes(), Update(), and UpHeap().
HeapNum
template<typename KeyType, typename IndexType = uint32> uint32 FBinaryHeap< KeyType, IndexType >::HeapNum protected
Definition at line 64 of file BinaryHeap.h.
Referenced by FBinaryHeap(), FBinaryHeap(), Add(), Clear(), DownHeap(), IsEmpty(), Num(), Peek(), Pop(), Remove(), ResetInternal(), ResizeHeap(), and Top().
HeapSize
template<typename KeyType, typename IndexType = uint32> uint32 FBinaryHeap< KeyType, IndexType >::HeapSize protected
Definition at line 65 of file BinaryHeap.h.
Referenced by FBinaryHeap(), FBinaryHeap(), Add(), GetHeapSize(), ResetInternal(), Resize(), and ResizeHeap().
IndexSize
template<typename KeyType, typename IndexType = uint32> uint32 FBinaryHeap< KeyType, IndexType >::IndexSize protected
Definition at line 66 of file BinaryHeap.h.
Referenced by FBinaryHeap(), FBinaryHeap(), Add(), Clear(), GetIndexSize(), IsPresent(), ResetInternal(), Resize(), and ResizeIndexes().
Keys
template<typename KeyType, typename IndexType = uint32> KeyType* FBinaryHeap< KeyType, IndexType >::Keys protected
Definition at line 70 of file BinaryHeap.h.
Referenced by FBinaryHeap(), FBinaryHeap(), Add(), DownHeap(), Free(), GetKey(), Remove(), ResetInternal(), ResizeIndexes(), Update(), and UpHeap().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/BinaryHeap.h