Unreal Engine 5.6 C++ API: FClassNetCache Class Reference
FClassNetCache Class Reference
#include "CoreNet.h"
Public Member Functions
FClassNetCache ()
FClassNetCache (const UClass *Class)
void CountBytes (FArchive &Ar) const
uint32 GetClassChecksum () const
const TArray< FFieldNetCache > & GetFields () const
const FFieldNetCache * GetFromChecksum (const uint32 Checksum) const
const FFieldNetCache * GetFromField (FFieldVariant Field) const
const FFieldNetCache * GetFromIndex (const int32 Index) const
int32 GetMaxIndex () const
const FClassNetCache * GetSuper () const
Private Attributes
TWeakObjectPtr< const UClass > Class
uint32 ClassChecksum
TMap< uint32, FFieldNetCache * > FieldChecksumMap
TMap< void *, FFieldNetCache * > FieldMap
TArray< FFieldNetCache > Fields
int32 FieldsBase
const FClassNetCache * Super
Friends
class FClassNetCacheMgr
Detailed Description
Definition at line 90 of file CoreNet.h.
Constructor & Destructor Documentation
FClassNetCache() [1/2]
FClassNetCache::FClassNetCache ()
Referenced by GetFromChecksum(), GetFromField(), GetFromIndex(), and GetSuper().
FClassNetCache() [2/2]
FClassNetCache::FClassNetCache (const UClass * Class)
References Class.
Member Function Documentation
CountBytes()
void FClassNetCache::CountBytes (FArchive & Ar) const
References Ar.
GetClassChecksum()
uint32 FClassNetCache::GetClassChecksum () const inline
Definition at line 142 of file CoreNet.h.
References ClassChecksum.
GetFields()
const TArray< FFieldNetCache > & FClassNetCache::GetFields () const inline
Definition at line 145 of file CoreNet.h.
References Fields.
GetFromChecksum()
const FFieldNetCache * FClassNetCache::GetFromChecksum (const uint32 Checksum) const inline
Definition at line 116 of file CoreNet.h.
References FClassNetCache().
GetFromField()
const FFieldNetCache * FClassNetCache::GetFromField (FFieldVariant Field) const inline
Definition at line 102 of file CoreNet.h.
References FClassNetCache(), and FFieldVariant::GetRawPointer().
GetFromIndex()
const FFieldNetCache * FClassNetCache::GetFromIndex (const int32 Index) const inline
Definition at line 130 of file CoreNet.h.
References FClassNetCache(), and FieldsBase.
GetMaxIndex()
int32 FClassNetCache::GetMaxIndex () const inline
Definition at line 97 of file CoreNet.h.
References Fields, and FieldsBase.
GetSuper()
const FClassNetCache * FClassNetCache::GetSuper () const inline
Definition at line 144 of file CoreNet.h.
References FClassNetCache(), and Super.
Friends And Related Symbol Documentation
FClassNetCacheMgr
friend class FClassNetCacheMgr friend
Definition at line 92 of file CoreNet.h.
References FClassNetCacheMgr.
Referenced by FClassNetCacheMgr.
Field Documentation
Class
TWeakObjectPtr< const UClass > FClassNetCache::Class private
Definition at line 152 of file CoreNet.h.
Referenced by FClassNetCache().
ClassChecksum
uint32 FClassNetCache::ClassChecksum private
Definition at line 153 of file CoreNet.h.
Referenced by GetClassChecksum().
FieldChecksumMap
TMap< uint32, FFieldNetCache* > FClassNetCache::FieldChecksumMap private
Definition at line 156 of file CoreNet.h.
FieldMap
TMap< void*, FFieldNetCache* > FClassNetCache::FieldMap private
Definition at line 155 of file CoreNet.h.
Fields
TArray< FFieldNetCache > FClassNetCache::Fields private
Definition at line 154 of file CoreNet.h.
Referenced by GetFields(), and GetMaxIndex().
FieldsBase
int32 FClassNetCache::FieldsBase private
Definition at line 150 of file CoreNet.h.
Referenced by GetFromIndex(), and GetMaxIndex().
Super
const FClassNetCache* FClassNetCache::Super private
Definition at line 151 of file CoreNet.h.
Referenced by GetSuper().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/CoreNet.h