Unreal Engine 5.6 C++ API: TSet< InElementType, KeyFuncs, Allocator > Class Template Reference
TSet< InElementType, KeyFuncs, Allocator > Class Template Reference
A set with an optional KeyFuncs parameters for customizing how the elements are compared and searched.
#include "Set.h"
Data Structures
class FElementCompareClass
Extracts the element value from the set's element structure and passes it to the user provided comparison class.
class TBaseIterator
The base type of whole set iterators.
class TBaseKeyIterator
The base type of whole set iterators.
class TConstIterator
Used to iterate over the elements of a const TSet.
class TConstKeyIterator
Used to iterate over the elements of a const TSet.
class TIterator
Used to iterate over the elements of a TSet.
class TKeyIterator
Used to iterate over the elements of a TSet.
Public Types
typedef Allocator AllocatorType
typedef InElementType ElementType
using IntrusiveUnsetOptionalStateType = TSet
typedef KeyFuncs KeyFuncsType
using SizeType = typename Allocator::SparseArrayAllocator::ElementAllocator::SizeType
using TRangedForConstIterator = TBaseIterator<true, true>
using TRangedForIterator = TBaseIterator<false, true>
Public Member Functions
FORCEINLINE TSet ()=default
Initialization constructor.
FORCEINLINE TSet (const TSet &Copy)
Copy constructor.
template<typename OtherAllocator>
TSet (const TSet< ElementType, KeyFuncs, OtherAllocator > &Other)
Constructor for copying elements from a TSet with a different SetAllocator.
TSet (FIntrusiveUnsetOptionalState Tag)
TSet (std::initializer_list< ElementType > InitList)
Initializer list constructor.
FORCEINLINE TSet (TArray< ElementType > &&InArray)
FORCEINLINE TSet (TArrayView< const ElementType > InArrayView)
TSet (TSet &&Other)
Move constructor.
template<typename OtherAllocator>
TSet (TSet< ElementType, KeyFuncs, OtherAllocator > &&Other)
Constructor for moving elements from a TSet with a different SetAllocator.
FORCEINLINE ~TSet ()
Destructor.
FORCEINLINE FSetElementId Add (const InElementType &InElement, bool *bIsAlreadyInSetPtr=nullptr)
Adds an element to the set.
FORCEINLINE FSetElementId Add (InElementType &&InElement, bool *bIsAlreadyInSetPtr=nullptr)
FORCEINLINE FSetElementId AddByHash (uint32 KeyHash, const InElementType &InElement, bool *bIsAlreadyInSetPtr=nullptr)
Adds an element to the set.
FORCEINLINE FSetElementId AddByHash (uint32 KeyHash, InElementType &&InElement, bool *bIsAlreadyInSetPtr=nullptr)
template<typename OtherAllocator>
void Append (const TSet< ElementType, KeyFuncs, OtherAllocator > &OtherSet)
Add all items from another set to our set (union without creating a new set)
template<typename OtherKeyFuncs, typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
void Append (const TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, OtherAllocator > &OtherSet)
Add all items from another set to our set (union without creating a new set) Compatible element type version.
void Append (std::initializer_list< ElementType > InitList)
template<typename ArrayAllocator>
void Append (TArray< ElementType, ArrayAllocator > &&InElements)
void Append (TArrayView< const ElementType > InElements)
template<typename OtherAllocator>
void Append (TSet< ElementType, KeyFuncs, OtherAllocator > &&OtherSet)
template<typename OtherKeyFuncs, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
void Append (TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, Allocator > &&OtherSet)
Add all items from another set to our set (union without creating a new set) Compatible element type version.
TArray< ElementType > Array () const
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void CheckAddress (const ElementType *Addr) const
Checks that the specified address is not part of an element within the container.
FORCEINLINE void Compact ()
Compacts the allocated elements into a contiguous range.
FORCEINLINE void CompactStable ()
Compacts the allocated elements into a contiguous range.
FORCEINLINE bool Contains (KeyInitType Key) const
Checks if the element contains an element with the given key.
template<typename ComparableKey>
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
Checks if the element contains an element with the given key.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Tracks the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator for the contents of this set.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator for the contents of this set.
TSet Difference (const TSet &OtherSet) const
void Dump (FOutputDevice &Ar)
Describes the set's contents through an output device.
void DumpHashElements (FOutputDevice &Ar)
template<typename ArgsType = ElementType>
FSetElementId Emplace (ArgsType &&Args, bool *bIsAlreadyInSetPtr=nullptr)
Adds an element to the set.
template<typename ArgsType = ElementType>
FSetElementId EmplaceByHash (uint32 KeyHash, ArgsType &&Args, bool *bIsAlreadyInSetPtr=nullptr)
Adds an element to the set.
void Empty (int32 ExpectedNumElements=0)
Removes all elements from the set, potentially leaving space allocated for an expected number of elements about to be added.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
FORCEINLINE ElementType * Find (KeyInitType Key)
Finds an element with the given key in the set.
FORCEINLINE const ElementType * Find (KeyInitType Key) const
Finds an element with the given key in the set.
ElementType * FindArbitraryElement ()
Finds any element in the set and returns a pointer to it.
const ElementType * FindArbitraryElement () const
template<typename ComparableKey>
ElementType * FindByHash (uint32 KeyHash, const ComparableKey &Key)
Finds an element with a pre-calculated hash and a key that can be compared to KeyType.
template<typename ComparableKey>
const ElementType * FindByHash (uint32 KeyHash, const ComparableKey &Key) const
FSetElementId FindId (KeyInitType Key) const
Finds an element with the given key in the set.
template<typename ComparableKey>
FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
Finds an element with a pre-calculated hash and a key that can be compared to KeyType.
FORCEINLINE ElementType & FindOrAdd (const InElementType &InElement, bool *bIsAlreadyInSetPtr=nullptr)
Adds an element to the set if not already present and returns a reference to the added or existing element.
FORCEINLINE ElementType & FindOrAdd (InElementType &&InElement, bool *bIsAlreadyInSetPtr=nullptr)
template<typename ElementReferenceType>
ElementType & FindOrAddByHash (uint32 KeyHash, ElementReferenceType &&InElement, bool *bIsAlreadyInSetPtr=nullptr)
Adds an element to the set if not already present and returns a reference to the added or existing element.
FORCEINLINE ElementType & Get (FSetElementId Id)
Accesses the identified element's value.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Accesses the identified element's value.
FORCEINLINE SIZE_T GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container Only returns the size of allocations made directly by the container, not the elements themselves.
FORCEINLINE int32 GetMaxIndex () const
bool Includes (const TSet< ElementType, KeyFuncs, Allocator > &OtherSet) const
Determine whether the specified set is entirely included within this set.
TSet Intersect (const TSet &OtherSet) const
bool IsEmpty () const
Returns true if the sets is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
TSet & operator= (const TSet &Copy)
Assignment operator.
template<typename OtherAllocator>
TSet & operator= (const TSet< ElementType, KeyFuncs, OtherAllocator > &Other)
Assignment operator for copying elements from a TSet with a different SetAllocator.
template<typename OtherKeyFuncs, typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
TSet & operator= (const TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, OtherAllocator > &Other)
Assignment operator.
TSet & operator= (std::initializer_list< ElementType > InitList)
Initializer list assignment operator.
TSet & operator= (TSet &&Other)
Move assignment operator.
template<typename OtherAllocator>
TSet & operator= (TSet< ElementType, KeyFuncs, OtherAllocator > &&Other)
Assignment operator for moving elements from a TSet with a different SetAllocator.
template<typename OtherKeyFuncs, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
TSet & operator= (TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, Allocator > &&Other)
Move assignment operator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE ElementType & operator[] (FSetElementId Id)
Accesses the identified element's value.
FORCEINLINE const ElementType & operator[] (FSetElementId Id) const
Accesses the identified element's value.
FORCEINLINE void Relax ()
Relaxes the set's hash to a size strictly bounded by the number of elements in the set.
void Remove (FSetElementId ElementId)
Removes an element from the set.
int32 Remove (KeyInitType Key)
Removes all elements from the set matching the specified key.
template<typename ComparableKey>
int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
Removes all elements from the set matching the specified key.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
void Reset ()
Efficiently empties out the set but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the set's element storage to avoid slack.
template<typename PREDICATE_CLASS>
void Sort (const PREDICATE_CLASS &Predicate)
Sorts the set's elements using the provided comparison class.
void SortFreeList ()
Sort the free element list so that subsequent additions will occur in the lowest available TSparseArray index resulting in tighter packing without moving any existing items.
template<typename PREDICATE_CLASS>
void StableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the set's elements using the provided comparison class.
TSet Union (const TSet &OtherSet) const
bool VerifyHashElementsKey (KeyInitType Key) const
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Public Member Functions
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
using ElementArrayType = TSparseArray<SetElementType, typename Allocator::SparseArrayAllocator>
typedef KeyFuncs::ElementInitType ElementInitType
using HashType = typename Allocator::HashAllocator::template ForElementType<FSetElementId>
typedef KeyFuncs::KeyInitType KeyInitType
typedef TSetElement< InElementType > SetElementType
using USizeType = std::make_unsigned_t<SizeType>
Private Member Functions
bool ConditionalRehash (int32 NumHashedElements, EAllowShrinking AllowShrinking)
Checks if the hash has an appropriate number of buckets, and if not resizes it.
template<typename ComparableKey>
SizeType FindIndexByHash (uint32 KeyHash, const ComparableKey &Key) const
Finds an element with a pre-calculated hash and a key that can be compared to KeyType.
FORCEINLINE FSetElementId & GetTypedHash (int32 HashIndex) const
FORCEINLINE void HashElement (SizeType ElementIndex, const SetElementType &Element) const
Hashes and links an added element to the hash chain.
FORCEINLINE void LinkElement (SizeType ElementIndex, const SetElementType &Element, uint32 KeyHash) const
Links an added element to the hash chain.
void Rehash ()
Resizes the hash.
FORCEINLINE void RehashOrLink (uint32 KeyHash, SetElementType &Element, SizeType ElementIndex)
void RemoveByIndex (SizeType ElementIndex)
template<typename ComparableKey>
FORCEINLINE int32 RemoveImpl (uint32 KeyHash, const ComparableKey &Key)
FORCEINLINE bool ShouldRehash (int32 NumHashedElements, int32 DesiredHashSize, EAllowShrinking AllowShrinking) const
Checks if the hash has an appropriate number of buckets, and if it should be resized.
bool TryReplaceExisting (uint32 KeyHash, SetElementType &Element, SizeType &InOutElementIndex, bool *bIsAlreadyInSetPtr)
void UnhashElements ()
Reset hash buckets to invalid.
Static Private Member Functions
template<typename SetType>
static FORCEINLINE void Move (SetType &ToSet, SetType &FromSet)
Private Attributes
ElementArrayType Elements
HashType Hash
int32 HashSize = 0
Friends
uint32 GetTypeHash (const TSet &Set)=delete
bool operator!= (const TSet &, const TSet &)=delete
bool operator== (const TSet &, const TSet &)=delete
template<typename, typename>
class TScriptSet
struct TSetPrivateFriend
Detailed Description
template<typename InElementType, typename KeyFuncs, typename Allocator>
class TSet< InElementType, KeyFuncs, Allocator >
A set with an optional KeyFuncs parameters for customizing how the elements are compared and searched.
E.g. You can specify a mapping from elements to keys if you want to find elements by specifying a subset of the element type. It uses a TSparseArray of the elements, and also links the elements into a hash with a number of buckets proportional to the number of elements. Addition, removal, and finding are O(1).
The ByHash() functions are somewhat dangerous but particularly useful in two scenarios: – Heterogeneous lookup to avoid creating expensive keys like FString when looking up by const TCHAR*. You must ensure the hash is calculated in the same way as ElementType is hashed. If possible put both ComparableKey and ElementType hash functions next to each other in the same header to avoid bugs when the ElementType hash function is changed. – Reducing contention around hash tables protected by a lock. It is often important to incur the cache misses of reading key data and doing the hashing before acquiring the lock.
Definition at line 153 of file Set.h.
Member Typedef Documentation
AllocatorType
template<typename InElementType, typename KeyFuncs, typename Allocator> typedef Allocator TSet< InElementType, KeyFuncs, Allocator >::AllocatorType
Definition at line 158 of file Set.h.
ElementArrayType
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::ElementArrayType = TSparseArray<SetElementType, typename Allocator::SparseArrayAllocator> private
Definition at line 1294 of file Set.h.
ElementInitType
template<typename InElementType, typename KeyFuncs, typename Allocator> typedef KeyFuncs::ElementInitType TSet< InElementType, KeyFuncs, Allocator >::ElementInitType private
Definition at line 171 of file Set.h.
ElementType
template<typename InElementType, typename KeyFuncs, typename Allocator> typedef InElementType TSet< InElementType, KeyFuncs, Allocator >::ElementType
Definition at line 156 of file Set.h.
HashType
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::HashType = typename Allocator::HashAllocator::template ForElementType<FSetElementId> private
Definition at line 1295 of file Set.h.
IntrusiveUnsetOptionalStateType
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::IntrusiveUnsetOptionalStateType = TSet
Definition at line 205 of file Set.h.
KeyFuncsType
template<typename InElementType, typename KeyFuncs, typename Allocator> typedef KeyFuncs TSet< InElementType, KeyFuncs, Allocator >::KeyFuncsType
Definition at line 157 of file Set.h.
KeyInitType
template<typename InElementType, typename KeyFuncs, typename Allocator> typedef KeyFuncs::KeyInitType TSet< InElementType, KeyFuncs, Allocator >::KeyInitType private
Definition at line 170 of file Set.h.
SetElementType
template<typename InElementType, typename KeyFuncs, typename Allocator> typedef TSetElement<InElementType> TSet< InElementType, KeyFuncs, Allocator >::SetElementType private
Definition at line 173 of file Set.h.
SizeType
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::SizeType = typename Allocator::SparseArrayAllocator::ElementAllocator::SizeType
Definition at line 160 of file Set.h.
TRangedForConstIterator
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::TRangedForConstIterator = TBaseIterator<true, true>
Definition at line 1631 of file Set.h.
TRangedForIterator
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::TRangedForIterator = TBaseIterator<false, true>
Definition at line 1632 of file Set.h.
USizeType
template<typename InElementType, typename KeyFuncs, typename Allocator> using TSet< InElementType, KeyFuncs, Allocator >::USizeType = std::make_unsigned_t<SizeType> private
Definition at line 165 of file Set.h.
Constructor & Destructor Documentation
TSet() [1/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TSet< InElementType, KeyFuncs, Allocator >::TSet () nodiscard default
Initialization constructor.
Referenced by TSet< InElementType, KeyFuncs, Allocator >::TConstKeyIterator::TConstKeyIterator(), TSet< InElementType, KeyFuncs, Allocator >::TKeyIterator::TKeyIterator(), TSet< class UObject * >::CopyUnfrozen(), and TSet< class UObject * >::WriteMemoryImage().
TSet() [2/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TSet< InElementType, KeyFuncs, Allocator >::TSet (const TSet< InElementType, KeyFuncs, Allocator > & Copy) inline nodiscard
Copy constructor.
Definition at line 180 of file Set.h.
TSet() [3/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TSet< InElementType, KeyFuncs, Allocator >::TSet (TArrayView< const ElementType > InArrayView) inline explicit nodiscard
Definition at line 185 of file Set.h.
TSet() [4/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TSet< InElementType, KeyFuncs, Allocator >::TSet (TArray< ElementType > && InArray) inline explicit nodiscard
Definition at line 190 of file Set.h.
~TSet()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TSet< InElementType, KeyFuncs, Allocator >::~TSet () inline
Destructor.
Definition at line 196 of file Set.h.
TSet() [5/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet< InElementType, KeyFuncs, Allocator >::TSet (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 207 of file Set.h.
TSet() [6/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet< InElementType, KeyFuncs, Allocator >::TSet (std::initializer_list< ElementType > InitList) inline nodiscard
Initializer list constructor.
Definition at line 250 of file Set.h.
TSet() [7/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet< InElementType, KeyFuncs, Allocator >::TSet (TSet< InElementType, KeyFuncs, Allocator > && Other) inline nodiscard
Move constructor.
Definition at line 257 of file Set.h.
TSet() [8/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherAllocator> TSet< InElementType, KeyFuncs, Allocator >::TSet (TSet< ElementType, KeyFuncs, OtherAllocator > && Other) inline nodiscard
Constructor for moving elements from a TSet with a different SetAllocator.
Definition at line 276 of file Set.h.
TSet() [9/9]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherAllocator> TSet< InElementType, KeyFuncs, Allocator >::TSet (const TSet< ElementType, KeyFuncs, OtherAllocator > & Other) inline nodiscard
Constructor for copying elements from a TSet with a different SetAllocator.
Definition at line 284 of file Set.h.
Member Function Documentation
Add() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE FSetElementId TSet< InElementType, KeyFuncs, Allocator >::Add (const InElementType & InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Adds an element to the set.
Parameters
InElement Element to add to set
bIsAlreadyInSetPtr [out] Optional pointer to bool that will be set depending on whether element is already in set
Returns
A pointer to the element stored in the set.
Definition at line 501 of file Set.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::BuildLevelCutSet(), UE::Geometry::TFastWindingTree< TriangleMeshType >::collect_triangles(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), UE::Geometry::FMeshRegionOperator::CurrentBaseInteriorVertices(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::GetBoundBoneIndices(), STreeView< FRigVMSearchResult >::GetExpandedItems(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys(), UE::SequenceNavigator::INavigationToolItem::GetParents(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexSelectedTriangles(), Algo::KahnTopologicalSort(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), STreeView< FRigVMSearchResult >::PopulateLinearizedItems(), FComponentEditorUtils::PropagateDefaultValueChange(), UE::Geometry::FMeshFaceSelection::remove_bowties(), UE::Geometry::FMeshVertexSelection::SelectConnectedBoundaryV(), UE::Geometry::FDynamicMeshOctree3::UpdateLevelCutSet(), and SListView< TSharedPtr< FString > >::UpdateSelectionSet().
Add() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE FSetElementId TSet< InElementType, KeyFuncs, Allocator >::Add (InElementType && InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Definition at line 505 of file Set.h.
AddByHash() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE FSetElementId TSet< InElementType, KeyFuncs, Allocator >::AddByHash (uint32 KeyHash, const InElementType & InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Adds an element to the set.
See also
Class documentation section on ByHash() functions
Parameters
InElement Element to add to set
bIsAlreadyInSetPtr [out] Optional pointer to bool that will be set depending on whether element is already in set
Returns
A handle to the element stored in the set
Definition at line 534 of file Set.h.
AddByHash() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE FSetElementId TSet< InElementType, KeyFuncs, Allocator >::AddByHash (uint32 KeyHash, InElementType && InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Definition at line 538 of file Set.h.
Append() [1/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherAllocator> void TSet< InElementType, KeyFuncs, Allocator >::Append (const TSet< ElementType, KeyFuncs, OtherAllocator > & OtherSet) inline
Add all items from another set to our set (union without creating a new set)
Parameters
OtherSet - The other set of items to add.
Definition at line 689 of file Set.h.
Append() [2/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherKeyFuncs, typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> void TSet< InElementType, KeyFuncs, Allocator >::Append (const TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, OtherAllocator > & OtherSet) inline
Add all items from another set to our set (union without creating a new set) Compatible element type version.
Parameters
OtherSet - The other set of items to add.
Definition at line 1244 of file Set.h.
Append() [3/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Append (std::initializer_list< ElementType > InitList) inline
Definition at line 709 of file Set.h.
Append() [4/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ArrayAllocator> void TSet< InElementType, KeyFuncs, Allocator >::Append (TArray< ElementType, ArrayAllocator > && InElements) inline
Definition at line 674 of file Set.h.
Append() [5/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Append (TArrayView< const ElementType > InElements) inline
Definition at line 664 of file Set.h.
Referenced by TSet< class UObject * >::TSet(), TSet< class UObject * >::TSet(), TSet< class UObject * >::TSet(), TSet< class UObject * >::TSet(), TSet< class UObject * >::TSet(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), and DisplayClusterHelpers::str::StrToSet().
Append() [6/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherAllocator> void TSet< InElementType, KeyFuncs, Allocator >::Append (TSet< ElementType, KeyFuncs, OtherAllocator > && OtherSet) inline
Definition at line 699 of file Set.h.
Append() [7/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherKeyFuncs, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> void TSet< InElementType, KeyFuncs, Allocator >::Append (TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, Allocator > && OtherSet) inline
Add all items from another set to our set (union without creating a new set) Compatible element type version.
Parameters
OtherSet - The other set of items to add.
Definition at line 1264 of file Set.h.
AppendHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::AppendHash (const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher) inline static
Definition at line 1336 of file Set.h.
Referenced by Freeze::IntrinsicAppendHash().
Array()
template<typename InElementType, typename KeyFuncs, typename Allocator> TArray< ElementType > TSet< InElementType, KeyFuncs, Allocator >::Array () const inline nodiscard
Returns
a TArray of the elements
Definition at line 1171 of file Set.h.
Referenced by FastTriWinding::ComputeCoeffs(), and UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexSelectedTriangles().
begin() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TRangedForIterator TSet< InElementType, KeyFuncs, Allocator >::begin () inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 1690 of file Set.h.
Referenced by TSet< InElementType, KeyFuncs, Allocator >::TConstIterator::TConstIterator(), and TSet< InElementType, KeyFuncs, Allocator >::TIterator::TIterator().
begin() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TRangedForConstIterator TSet< InElementType, KeyFuncs, Allocator >::begin () const inline nodiscard
Definition at line 1694 of file Set.h.
CheckAddress()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::CheckAddress (const ElementType * Addr) const inline
Checks that the specified address is not part of an element within the container.
Used for implementations to check that reference arguments aren't going to be invalidated by possible reallocation.
Parameters
Addr The address to check.
Definition at line 1188 of file Set.h.
Compact()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::Compact () inline
Compacts the allocated elements into a contiguous range.
Definition at line 363 of file Set.h.
CompactStable()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::CompactStable () inline
Compacts the allocated elements into a contiguous range.
Does not change the iteration order of the elements.
Definition at line 373 of file Set.h.
ConditionalRehash()
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::ConditionalRehash (int32 NumHashedElements, EAllowShrinking AllowShrinking) inline private
Checks if the hash has an appropriate number of buckets, and if not resizes it.
Parameters
NumHashedElements - The number of elements to size the hash for.
AllowShrinking - If the hash is allowed to shrink.
Returns
true if the set was rehashed.
Definition at line 1410 of file Set.h.
Referenced by TSet< class UObject * >::RehashOrLink(), and TSet< class UObject * >::Relax().
Contains()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE bool TSet< InElementType, KeyFuncs, Allocator >::Contains (KeyInitType Key) const inline nodiscard
Checks if the element contains an element with the given key.
Parameters
Key - The key to check for.
Returns
true if the set contains an element with the given key.
Definition at line 964 of file Set.h.
Referenced by FActorIteratorState::FActorIteratorState(), UE::Geometry::FDynamicMeshOctree3::CollectRootTriangles(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::Geometry::FMeshRegionOperator::CurrentBaseInteriorVertices(), TSet< class UObject * >::Difference(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::GetKeys(), TSet< class UObject * >::Includes(), FStreamingSourceShapeHelper::IsSourceAffectingGrid(), FComponentEditorUtils::PropagateDefaultValueChange(), UE::Geometry::FMeshVertexSelection::SelectConnectedBoundaryV(), and UE::Geometry::FDynamicMeshOctree3::UpdateLevelCutSet().
ContainsByHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> FORCEINLINE bool TSet< InElementType, KeyFuncs, Allocator >::ContainsByHash (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard
Checks if the element contains an element with the given key.
See also
Class documentation section on ByHash() functions
Definition at line 975 of file Set.h.
CopyUnfrozen()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::CopyUnfrozen (const FMemoryUnfreezeContent & Context, void * Dst) const inline
Definition at line 1318 of file Set.h.
CountBytes()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::CountBytes (FArchive & Ar) const inline
Tracks the container's memory use through an archive.
Definition at line 428 of file Set.h.
CreateConstIterator()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TConstIterator TSet< InElementType, KeyFuncs, Allocator >::CreateConstIterator () const inline nodiscard
Creates a const iterator for the contents of this set.
Definition at line 1678 of file Set.h.
CreateIterator()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TIterator TSet< InElementType, KeyFuncs, Allocator >::CreateIterator () inline nodiscard
Creates an iterator for the contents of this set.
Definition at line 1672 of file Set.h.
Referenced by AlgoImpl::FindMostIndependentMutuallyReachableVertexSet().
Difference()
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet TSet< InElementType, KeyFuncs, Allocator >::Difference (const TSet< InElementType, KeyFuncs, Allocator > & OtherSet) const inline nodiscard
Returns
the complement of two sets. (A not in B where A is this and B is Other)
Definition at line 1126 of file Set.h.
Referenced by STreeView< FRigVMSearchResult >::Tick().
Dump()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Dump (FOutputDevice & Ar) inline
Describes the set's contents through an output device.
Parameters
Ar - The output device to describe the set's contents through.
Definition at line 1025 of file Set.h.
DumpHashElements()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::DumpHashElements (FOutputDevice & Ar) inline
Definition at line 1064 of file Set.h.
Emplace()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ArgsType = ElementType> FSetElementId TSet< InElementType, KeyFuncs, Allocator >::Emplace (ArgsType && Args, bool * bIsAlreadyInSetPtr = nullptr) inline
Adds an element to the set.
Parameters
Args The argument(s) to be forwarded to the set element's constructor.
bIsAlreadyInSetPtr [out] Optional pointer to bool that will be set depending on whether element is already in set
Returns
A handle to the element stored in the set.
Definition at line 624 of file Set.h.
Referenced by TSet< class UObject * >::Add(), and TSet< class UObject * >::Add().
EmplaceByHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ArgsType = ElementType> FSetElementId TSet< InElementType, KeyFuncs, Allocator >::EmplaceByHash (uint32 KeyHash, ArgsType && Args, bool * bIsAlreadyInSetPtr = nullptr) inline
Adds an element to the set.
See also
Class documentation section on ByHash() functions
Parameters
Args The argument(s) to be forwarded to the set element's constructor.
bIsAlreadyInSetPtr [out] Optional pointer to bool that will be set depending on whether element is already in set
Returns
A handle to the element stored in the set.
Definition at line 649 of file Set.h.
Referenced by TSet< class UObject * >::AddByHash(), and TSet< class UObject * >::AddByHash().
Empty()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Empty (int32 ExpectedNumElements = 0) inline
Removes all elements from the set, potentially leaving space allocated for an expected number of elements about to be added.
Parameters
ExpectedNumElements - The number of elements about to be added to the set.
Definition at line 320 of file Set.h.
Referenced by UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Empty(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), and UE::Geometry::FMeshFaceSelection::remove_bowties().
end() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TRangedForIterator TSet< InElementType, KeyFuncs, Allocator >::end () inline nodiscard
Definition at line 1698 of file Set.h.
end() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE TRangedForConstIterator TSet< InElementType, KeyFuncs, Allocator >::end () const inline nodiscard
Definition at line 1702 of file Set.h.
Find() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE ElementType * TSet< InElementType, KeyFuncs, Allocator >::Find (KeyInitType Key) inline nodiscard
Finds an element with the given key in the set.
Parameters
Key - The key to search for.
Returns
A pointer to an element with the given key. If no element in the set has the given key, this will return NULL.
Definition at line 838 of file Set.h.
Find() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE const ElementType * TSet< InElementType, KeyFuncs, Allocator >::Find (KeyInitType Key) const inline nodiscard
Finds an element with the given key in the set.
Parameters
Key - The key to search for.
Returns
A const pointer to an element with the given key. If no element in the set has the given key, this will return NULL.
Definition at line 856 of file Set.h.
FindArbitraryElement() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> ElementType * TSet< InElementType, KeyFuncs, Allocator >::FindArbitraryElement () inline nodiscard
Finds any element in the set and returns a pointer to it.
Callers should not depend on particular patterns in the behaviour of this function.
Returns
A pointer to an arbitrary element, or nullptr if the container is empty.
Definition at line 795 of file Set.h.
Referenced by TSet< class UObject * >::FindArbitraryElement().
FindArbitraryElement() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> const ElementType * TSet< InElementType, KeyFuncs, Allocator >::FindArbitraryElement () const inline nodiscard
Definition at line 802 of file Set.h.
FindByHash() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> ElementType * TSet< InElementType, KeyFuncs, Allocator >::FindByHash (uint32 KeyHash, const ComparableKey & Key) inline nodiscard
Finds an element with a pre-calculated hash and a key that can be compared to KeyType.
See also
Class documentation section on ByHash() functions
Returns
A pointer to the contained element or nullptr.
Definition at line 867 of file Set.h.
Referenced by TSet< class UObject * >::FindByHash().
FindByHash() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> const ElementType * TSet< InElementType, KeyFuncs, Allocator >::FindByHash (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard
Definition at line 881 of file Set.h.
FindId()
template<typename InElementType, typename KeyFuncs, typename Allocator> FSetElementId TSet< InElementType, KeyFuncs, Allocator >::FindId (KeyInitType Key) const inline nodiscard
Finds an element with the given key in the set.
Parameters
Key - The key to search for.
Returns
The id of the set element matching the given key, or the NULL id if none matches.
Definition at line 812 of file Set.h.
FindIdByHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> FSetElementId TSet< InElementType, KeyFuncs, Allocator >::FindIdByHash (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard
Finds an element with a pre-calculated hash and a key that can be compared to KeyType.
See also
Class documentation section on ByHash() functions
Returns
The element id that matches the key and hash or an invalid element id
Definition at line 823 of file Set.h.
FindIndexByHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> SizeType TSet< InElementType, KeyFuncs, Allocator >::FindIndexByHash (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard private
Finds an element with a pre-calculated hash and a key that can be compared to KeyType.
See also
Class documentation section on ByHash() functions
Returns
The element id that matches the key and hash or an invalid element id
Definition at line 763 of file Set.h.
Referenced by TSet< class UObject * >::Contains(), TSet< class UObject * >::ContainsByHash(), TSet< class UObject * >::Find(), TSet< class UObject * >::FindByHash(), TSet< class UObject * >::FindId(), TSet< class UObject * >::FindIdByHash(), TSet< class UObject * >::FindOrAddByHash(), and TSet< class UObject * >::TryReplaceExisting().
FindOrAdd() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE ElementType & TSet< InElementType, KeyFuncs, Allocator >::FindOrAdd (const InElementType & InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Adds an element to the set if not already present and returns a reference to the added or existing element.
Parameters
InElement Element to add to set
bIsAlreadyInSetPtr [out] Optional pointer to bool that will be set depending on whether element is already in set
Returns
A reference to the element stored in the set.
Definition at line 517 of file Set.h.
Referenced by AddOrMergeTileRequest().
FindOrAdd() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE ElementType & TSet< InElementType, KeyFuncs, Allocator >::FindOrAdd (InElementType && InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Definition at line 521 of file Set.h.
FindOrAddByHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ElementReferenceType> ElementType & TSet< InElementType, KeyFuncs, Allocator >::FindOrAddByHash (uint32 KeyHash, ElementReferenceType && InElement, bool * bIsAlreadyInSetPtr = nullptr) inline
Adds an element to the set if not already present and returns a reference to the added or existing element.
See also
Class documentation section on ByHash() functions
Parameters
InElement Element to add to set
bIsAlreadyInSetPtr [out] Optional pointer to bool that will be set depending on whether element is already in set
Returns
A reference to the element stored in the set
Definition at line 552 of file Set.h.
Referenced by TSet< class UObject * >::FindOrAdd(), and TSet< class UObject * >::FindOrAdd().
Get() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE ElementType & TSet< InElementType, KeyFuncs, Allocator >::Get (FSetElementId Id) inline nodiscard
Accesses the identified element's value.
Element must be valid (see @IsValidId).
Definition at line 483 of file Set.h.
Get() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE const ElementType & TSet< InElementType, KeyFuncs, Allocator >::Get (FSetElementId Id) const inline nodiscard
Accesses the identified element's value.
Element must be valid (see @IsValidId).
Definition at line 489 of file Set.h.
GetAllocatedSize()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE SIZE_T TSet< InElementType, KeyFuncs, Allocator >::GetAllocatedSize (void) const inline nodiscard
Helper function to return the amount of memory allocated by this container Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
number of bytes allocated by this container
Definition at line 422 of file Set.h.
GetMaxIndex()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE int32 TSet< InElementType, KeyFuncs, Allocator >::GetMaxIndex () const inline nodiscard
Definition at line 451 of file Set.h.
GetTypedHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE FSetElementId & TSet< InElementType, KeyFuncs, Allocator >::GetTypedHash (int32 HashIndex) const inline nodiscard private
Definition at line 1343 of file Set.h.
Referenced by TSet< class UObject * >::Dump(), TSet< class UObject * >::DumpHashElements(), TSet< class UObject * >::LinkElement(), TSet< class UObject * >::Rehash(), TSet< class UObject * >::RemoveImpl(), and TSet< class UObject * >::VerifyHashElementsKey().
HashElement()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::HashElement (SizeType ElementIndex, const SetElementType & Element) const inline private
Hashes and links an added element to the hash chain.
Definition at line 1361 of file Set.h.
Referenced by TSet< class UObject * >::Rehash().
Includes()
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::Includes (const TSet< ElementType, KeyFuncs, Allocator > & OtherSet) const inline nodiscard
Determine whether the specified set is entirely included within this set.
Parameters
OtherSet Set to check
Returns
True if the other set is entirely included in this set, false if it is not
Definition at line 1148 of file Set.h.
Intersect()
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet TSet< InElementType, KeyFuncs, Allocator >::Intersect (const TSet< InElementType, KeyFuncs, Allocator > & OtherSet) const inline nodiscard
Returns
the intersection of two sets. (A AND B)
Definition at line 1089 of file Set.h.
Referenced by AlgoImpl::FindMostIndependentMutuallyReachableVertexSet().
IsEmpty()
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::IsEmpty () const inline nodiscard
Returns true if the sets is empty and contains no elements.
Returns
True if the set is empty.
See also
Num
Definition at line 440 of file Set.h.
Referenced by AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), FStreamingSourceShapeHelper::IsSourceAffectingGrid(), and Algo::KahnTopologicalSort().
IsValidId()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE bool TSet< InElementType, KeyFuncs, Allocator >::IsValidId (FSetElementId Id) const inline nodiscard
Checks whether an element id is valid.
Parameters
Id - The element id to check.
Returns
true if the element identifier refers to a valid element in this set.
Definition at line 461 of file Set.h.
Referenced by TSet< class UObject * >::DumpHashElements(), and TSet< class UObject * >::VerifyHashElementsKey().
LinkElement()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::LinkElement (SizeType ElementIndex, const SetElementType & Element, uint32 KeyHash) const inline private
Links an added element to the hash chain.
Definition at line 1349 of file Set.h.
Referenced by TSet< class UObject * >::HashElement(), and TSet< class UObject * >::RehashOrLink().
Move()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename SetType> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::Move (SetType & ToSet, SetType & FromSet) inline static private
Definition at line 238 of file Set.h.
Num()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE int32 TSet< InElementType, KeyFuncs, Allocator >::Num () const inline nodiscard
Returns
the number of elements.
Definition at line 446 of file Set.h.
Referenced by TSet< class UObject * >::Append(), IBlueprintNodeBinder::ApplyBindings(), TSet< class UObject * >::Array(), FastTriWinding::ComputeCoeffs(), TSet< class UObject * >::Difference(), FBoundaryTopologyProvider::ForGroupSetEdges(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TSet< class UObject * >::Includes(), TSet< class UObject * >::Intersect(), Algo::KahnTopologicalSort(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::FGroupTopologySelection::operator==(), TSet< class UObject * >::Reset(), UE::Geometry::TDynamicVertexAttributeChange< AttribValueType, AttribDimension, ParentType >::StoreAllFinalVertices(), UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::StoreAllFinalVertices(), STreeView< FRigVMSearchResult >::Tick(), TSet< class UObject * >::UnhashElements(), TSet< class UObject * >::Union(), and SListView< TSharedPtr< FString > >::UpdateSelectionSet().
operator=() [1/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (const TSet< InElementType, KeyFuncs, Allocator > & Copy) inline
Assignment operator.
Definition at line 220 of file Set.h.
operator=() [2/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherAllocator> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (const TSet< ElementType, KeyFuncs, OtherAllocator > & Other) inline
Assignment operator for copying elements from a TSet with a different SetAllocator.
Definition at line 301 of file Set.h.
operator=() [3/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherKeyFuncs, typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (const TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, OtherAllocator > & Other) inline
Assignment operator.
First deletes all currently contained elements and then copies from other set. Compatible element type version.
Parameters
Other The source set to assign from.
Definition at line 1225 of file Set.h.
operator=() [4/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (std::initializer_list< ElementType > InitList) inline
Initializer list assignment operator.
Definition at line 309 of file Set.h.
operator=() [5/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (TSet< InElementType, KeyFuncs, Allocator > && Other) inline
Move assignment operator.
Definition at line 264 of file Set.h.
operator=() [6/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherAllocator> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (TSet< ElementType, KeyFuncs, OtherAllocator > && Other) inline
Assignment operator for moving elements from a TSet with a different SetAllocator.
Definition at line 292 of file Set.h.
operator=() [7/7]
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename OtherKeyFuncs, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)> TSet & TSet< InElementType, KeyFuncs, Allocator >::operator= (TSet< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherKeyFuncs, Allocator > && Other) inline
Move assignment operator.
Compatible element type version.
Parameters
Other Set to assign and move from.
Definition at line 1204 of file Set.h.
operator==()
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 211 of file Set.h.
operator[]() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE ElementType & TSet< InElementType, KeyFuncs, Allocator >::operator[] (FSetElementId Id) inline nodiscard
Accesses the identified element's value.
Element must be valid (see @IsValidId).
Definition at line 471 of file Set.h.
operator[]() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE const ElementType & TSet< InElementType, KeyFuncs, Allocator >::operator[] (FSetElementId Id) const inline nodiscard
Accesses the identified element's value.
Element must be valid (see @IsValidId).
Definition at line 477 of file Set.h.
Rehash()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Rehash () inline private
Resizes the hash.
Definition at line 1426 of file Set.h.
Referenced by TSet< class UObject * >::Compact(), TSet< class UObject * >::CompactStable(), TSet< class UObject * >::ConditionalRehash(), TSet< class UObject * >::Empty(), TSet< class UObject * >::Reserve(), TSet< class UObject * >::Sort(), and TSet< class UObject * >::StableSort().
RehashOrLink()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::RehashOrLink (uint32 KeyHash, SetElementType & Element, SizeType ElementIndex) inline private
Definition at line 605 of file Set.h.
Referenced by TSet< class UObject * >::Emplace(), TSet< class UObject * >::EmplaceByHash(), and TSet< class UObject * >::FindOrAddByHash().
Relax()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::Relax () inline
Relaxes the set's hash to a size strictly bounded by the number of elements in the set.
Definition at line 412 of file Set.h.
Referenced by TSet< class UObject * >::Shrink().
Remove() [1/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Remove (FSetElementId ElementId) inline
Removes an element from the set.
Parameters
Element - A pointer to the element in the set, as returned by Add or Find.
Definition at line 751 of file Set.h.
Referenced by AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), and Algo::KahnTopologicalSort().
Remove() [2/2]
template<typename InElementType, typename KeyFuncs, typename Allocator> int32 TSet< InElementType, KeyFuncs, Allocator >::Remove (KeyInitType Key) inline
Removes all elements from the set matching the specified key.
Parameters
Key - The key to match elements against.
Returns
The number of elements removed.
Definition at line 926 of file Set.h.
RemoveByHash()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> int32 TSet< InElementType, KeyFuncs, Allocator >::RemoveByHash (uint32 KeyHash, const ComparableKey & Key) inline
Removes all elements from the set matching the specified key.
See also
Class documentation section on ByHash() functions
Parameters
Key - The key to match elements against.
Returns
The number of elements removed.
Definition at line 944 of file Set.h.
RemoveByIndex()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::RemoveByIndex (SizeType ElementIndex) inline private
Definition at line 719 of file Set.h.
Referenced by TSet< class UObject * >::Remove(), and TSet< class UObject * >::RemoveImpl().
RemoveImpl()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename ComparableKey> FORCEINLINE int32 TSet< InElementType, KeyFuncs, Allocator >::RemoveImpl (uint32 KeyHash, const ComparableKey & Key) inline private
Definition at line 888 of file Set.h.
Referenced by TSet< class UObject * >::Remove(), and TSet< class UObject * >::RemoveByHash().
Reserve()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::Reserve (int32 Number) inline
Preallocates enough memory to contain Number elements.
Definition at line 383 of file Set.h.
Referenced by TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexSelectedTriangles(), and Algo::KahnTopologicalSort().
Reset()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::Reset () inline
Efficiently empties out the set but preserves all allocations and capacities.
Definition at line 343 of file Set.h.
Referenced by AlgoImpl::FindMostIndependentMutuallyReachableVertexSet(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys(), Algo::KahnTopologicalSort(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), TSet< class UObject * >::operator=(), and DisplayClusterHelpers::str::StrToSet().
ShouldRehash()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE bool TSet< InElementType, KeyFuncs, Allocator >::ShouldRehash (int32 NumHashedElements, int32 DesiredHashSize, EAllowShrinking AllowShrinking) const inline nodiscard private
Checks if the hash has an appropriate number of buckets, and if it should be resized.
Parameters
NumHashedElements - The number of elements to size the hash for.
DesiredHashSize - Desired size if we should rehash.
AllowShrinking - If the hash is allowed to shrink.
Returns
true if the set should berehashed.
Definition at line 1397 of file Set.h.
Referenced by TSet< class UObject * >::ConditionalRehash(), and TSet< class UObject * >::Empty().
Shrink()
template<typename InElementType, typename KeyFuncs, typename Allocator> FORCEINLINE void TSet< InElementType, KeyFuncs, Allocator >::Shrink () inline
Shrinks the set's element storage to avoid slack.
Definition at line 356 of file Set.h.
Sort()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename PREDICATE_CLASS> void TSet< InElementType, KeyFuncs, Allocator >::Sort (const PREDICATE_CLASS & Predicate) inline
Sorts the set's elements using the provided comparison class.
Definition at line 989 of file Set.h.
SortFreeList()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::SortFreeList () inline
Sort the free element list so that subsequent additions will occur in the lowest available TSparseArray index resulting in tighter packing without moving any existing items.
Also useful for some types of determinism.
See also
TSparseArray::SortFreeList() for more info.
Definition at line 1016 of file Set.h.
StableSort()
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename PREDICATE_CLASS> void TSet< InElementType, KeyFuncs, Allocator >::StableSort (const PREDICATE_CLASS & Predicate) inline
Stable sorts the set's elements using the provided comparison class.
Definition at line 1002 of file Set.h.
TryReplaceExisting()
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::TryReplaceExisting (uint32 KeyHash, SetElementType & Element, SizeType & InOutElementIndex, bool * bIsAlreadyInSetPtr) inline private
Definition at line 573 of file Set.h.
Referenced by TSet< class UObject * >::Emplace(), and TSet< class UObject * >::EmplaceByHash().
UnhashElements()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::UnhashElements () inline private
Reset hash buckets to invalid.
Reset the whole hash to invalid
Definition at line 1367 of file Set.h.
Referenced by TSet< class UObject * >::Empty(), and TSet< class UObject * >::Reset().
Union()
template<typename InElementType, typename KeyFuncs, typename Allocator> TSet TSet< InElementType, KeyFuncs, Allocator >::Union (const TSet< InElementType, KeyFuncs, Allocator > & OtherSet) const inline nodiscard
Returns
the union of two sets. (A OR B)
Definition at line 1109 of file Set.h.
VerifyHashElementsKey()
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::VerifyHashElementsKey (KeyInitType Key) const inline nodiscard
Definition at line 1043 of file Set.h.
WriteMemoryImage()
template<typename InElementType, typename KeyFuncs, typename Allocator> void TSet< InElementType, KeyFuncs, Allocator >::WriteMemoryImage (FMemoryImageWriter & Writer) const inline
Definition at line 1303 of file Set.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename InElementType, typename KeyFuncs, typename Allocator> uint32 GetTypeHash (const TSet< InElementType, KeyFuncs, Allocator > & Set) friend
operator!=
template<typename InElementType, typename KeyFuncs, typename Allocator> bool operator!= (const TSet< InElementType, KeyFuncs, Allocator > & , const TSet< InElementType, KeyFuncs, Allocator > &) friend
operator==
template<typename InElementType, typename KeyFuncs, typename Allocator> bool operator== (const TSet< InElementType, KeyFuncs, Allocator > & , const TSet< InElementType, KeyFuncs, Allocator > &) friend
TScriptSet
template<typename InElementType, typename KeyFuncs, typename Allocator> template<typename, typename> friend class TScriptSet friend
Definition at line 168 of file Set.h.
TSetPrivateFriend
template<typename InElementType, typename KeyFuncs, typename Allocator> friend struct TSetPrivateFriend friend
Definition at line 1683 of file Set.h.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename InElementType, typename KeyFuncs, typename Allocator> bool TSet< InElementType, KeyFuncs, Allocator >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 204 of file Set.h.
Elements
template<typename InElementType, typename KeyFuncs, typename Allocator> ElementArrayType TSet< InElementType, KeyFuncs, Allocator >::Elements private
Definition at line 1297 of file Set.h.
Referenced by TSet< InElementType, KeyFuncs, Allocator >::TConstIterator::TConstIterator(), TSet< InElementType, KeyFuncs, Allocator >::TIterator::TIterator(), and TSet< class UObject * >::CopyUnfrozen().
Hash
template<typename InElementType, typename KeyFuncs, typename Allocator> HashType TSet< InElementType, KeyFuncs, Allocator >::Hash private
Definition at line 1299 of file Set.h.
Referenced by TSet< class UObject * >::CopyUnfrozen().
HashSize
template<typename InElementType, typename KeyFuncs, typename Allocator> int32 TSet< InElementType, KeyFuncs, Allocator >::HashSize = 0 private
Definition at line 1300 of file Set.h.
Referenced by TSet< class UObject * >::CopyUnfrozen().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Set.h