Unreal Engine 5.6 C++ API: UE::MediaIO::FOrderedAsyncGate Class Reference
UE::MediaIO::FOrderedAsyncGate Class Reference
#include "OrderedAsyncGate.h"
Public Member Functions
uint64 GetANumber ()
Gets a number that represents the when the number holder will get their turn.
void GiveUpTurn (const uint32 Number)
Call this function when you are ready to give up your turn.
bool IsMyTurn (const uint32 Number) const
Returns true if it is the turn of the given number.
void WaitForTurn (const uint32 Number) const
This function will block until it is the turn of the given number to execute.
Private Attributes
std::atomic< uint32 > CurrentNumber = 0
The current number that has its turn without having to wait any longer.
std::atomic< uint32 > NextNumber = 0
The number that will be given out to the next client that calls GetANumber.
Detailed Description
Definition at line 17 of file OrderedAsyncGate.h.
Member Function Documentation
GetANumber()
uint64 UE::MediaIO::FOrderedAsyncGate::GetANumber () inline
Gets a number that represents the when the number holder will get their turn.
Definition at line 22 of file OrderedAsyncGate.h.
References NextNumber.
GiveUpTurn()
void UE::MediaIO::FOrderedAsyncGate::GiveUpTurn (const uint32 Number) inline
Call this function when you are ready to give up your turn.
It must be called with the number received from GetANumber, and it must be called whether WaitForTurn was called or not. Not giving up the turn will prevent any others from getting their turn. Note: It will internally call WaitForTurn.
Definition at line 55 of file OrderedAsyncGate.h.
References CurrentNumber, and WaitForTurn().
IsMyTurn()
bool UE::MediaIO::FOrderedAsyncGate::IsMyTurn (const uint32 Number) const inline
Returns true if it is the turn of the given number.
Definition at line 28 of file OrderedAsyncGate.h.
References CurrentNumber.
Referenced by WaitForTurn().
WaitForTurn()
void UE::MediaIO::FOrderedAsyncGate::WaitForTurn (const uint32 Number) const inline
This function will block until it is the turn of the given number to execute.
It can be called multiple times until the turn is given up by calling GiveUpTurn. The number given must have been received from a call to GetANumber.
Definition at line 38 of file OrderedAsyncGate.h.
References IsMyTurn().
Referenced by GiveUpTurn().
Field Documentation
CurrentNumber
std::atomic<uint32> UE::MediaIO::FOrderedAsyncGate::CurrentNumber = 0 private
The current number that has its turn without having to wait any longer.
Definition at line 65 of file OrderedAsyncGate.h.
Referenced by GiveUpTurn(), and IsMyTurn().
NextNumber
std::atomic<uint32> UE::MediaIO::FOrderedAsyncGate::NextNumber = 0 private
The number that will be given out to the next client that calls GetANumber.
Definition at line 68 of file OrderedAsyncGate.h.
Referenced by GetANumber().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaIOFramework/Source/MediaIOCore/Public/OrderedAsyncGate.h