Unreal Engine 5.6 C++ API: UE::UnifiedError::FError Class Reference
UE::UnifiedError::FError Class Reference
#include "UnifiedError.h"
Public Member Functions
FError (const FError &InError)
FError (FError &&InError)
FError (int32 InModuleId, int32 InErrorCode, const IErrorDetails *InErrorDetails)
~FError ()
bool GetDetailByKey (const FUtf8StringView &KeyName, double &Result) const
bool GetDetailByKey (const FUtf8StringView &KeyName, float &Result) const
bool GetDetailByKey (const FUtf8StringView &KeyName, FString &Result) const
bool GetDetailByKey (const FUtf8StringView &KeyName, FText &Result) const
bool GetDetailByKey (const FUtf8StringView &KeyName, FUtf8String &Result) const
bool GetDetailByKey (const FUtf8StringView &KeyName, int32 &Result) const
bool GetDetailByKey (const FUtf8StringView &KeyName, int64 &Result) const
int32 GetErrorCode () const
const FUtf8String GetErrorCodeString () const
template<typename T>
const T * GetErrorContext () const
template<typename DetailType>
TRefCountPtr< const DetailType > GetErrorDetails () const
FText GetErrorMessage (bool bAppendContext=false) const
void GetErrorProperties (IErrorPropertyExtractor &Visitor) const
FText GetFormatErrorText () const
int32 GetModuleId () const
const FUtf8String GetModuleIdString () const
FORCEINLINE void Invalidate ()
FORCEINLINE bool IsValid () const
template<typename T>
void PushErrorContext (T &&InErrorStruct)
void PushErrorDetails (TRefCountPtr< IErrorDetails > InErrorDetails)
void SerializeDetailsForLog (FCbWriter &Writer) const
Private Member Functions
TRefCountPtr< const IErrorDetails > GetInnerMostErrorDetails () const
Private Attributes
int32 ErrorCode
TRefCountPtr< const IErrorDetails > ErrorDetails
int32 ModuleId
Friends
bool operator== (const FError &Error, const FError &OtherError)
Detailed Description
Definition at line 369 of file UnifiedError.h.
Constructor & Destructor Documentation
FError() [1/3]
UE::UnifiedError::FError::FError (int32 InModuleId, int32 InErrorCode, const IErrorDetails * InErrorDetails) inline
Definition at line 376 of file UnifiedError.h.
References ErrorCode, ErrorDetails, and ModuleId.
Referenced by FError(), FError(), and operator==.
FError() [2/3]
UE::UnifiedError::FError::FError (FError && InError) inline
Definition at line 383 of file UnifiedError.h.
References FError(), ErrorCode, ErrorDetails, and ModuleId.
FError() [3/3]
UE::UnifiedError::FError::FError (const FError & InError) inline
Definition at line 396 of file UnifiedError.h.
References FError(), ErrorCode, ErrorDetails, and ModuleId.
~FError()
UE::UnifiedError::FError::~FError () inline
Definition at line 403 of file UnifiedError.h.
References Invalidate().
Member Function Documentation
GetDetailByKey() [1/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, double & Result) const
GetDetailByKey() [2/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, float & Result) const
GetDetailByKey() [3/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, FString & Result) const
GetDetailByKey() [4/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, FText & Result) const
GetDetailByKey() [5/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, FUtf8String & Result) const
GetDetailByKey() [6/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, int32 & Result) const
GetDetailByKey() [7/7]
bool UE::UnifiedError::FError::GetDetailByKey (const FUtf8StringView & KeyName, int64 & Result) const
GetErrorCode()
int32 UE::UnifiedError::FError::GetErrorCode () const
GetErrorCodeString()
const FUtf8String UE::UnifiedError::FError::GetErrorCodeString () const
GetErrorContext()
template<typename T> const T * UE::UnifiedError::FError::GetErrorContext () const inline
Definition at line 441 of file UnifiedError.h.
References ErrorDetails, UE::UnifiedError::TErrorDetails< T >::GetErrorContext(), TErrorStructFeatures< T >::GetErrorDetailsTypeNameAsString(), and TRefCountPtr< ReferencedType >::GetReference().
GetErrorDetails()
template<typename DetailType> TRefCountPtr< const DetailType > UE::UnifiedError::FError::GetErrorDetails () const inline
Definition at line 418 of file UnifiedError.h.
References ErrorDetails, and TRefCountPtr< ReferencedType >::GetReference().
GetErrorMessage()
FText UE::UnifiedError::FError::GetErrorMessage (bool bAppendContext = false) const
GetErrorProperties()
void UE::UnifiedError::FError::GetErrorProperties (IErrorPropertyExtractor & Visitor) const
GetFormatErrorText()
FText UE::UnifiedError::FError::GetFormatErrorText () const
GetInnerMostErrorDetails()
TRefCountPtr< const IErrorDetails > UE::UnifiedError::FError::GetInnerMostErrorDetails () const private
GetModuleId()
int32 UE::UnifiedError::FError::GetModuleId () const
GetModuleIdString()
const FUtf8String UE::UnifiedError::FError::GetModuleIdString () const
Invalidate()
FORCEINLINE void UE::UnifiedError::FError::Invalidate () inline
Definition at line 471 of file UnifiedError.h.
References ErrorCode, ErrorDetails, FORCEINLINE, and ModuleId.
Referenced by ~FError().
IsValid()
FORCEINLINE bool UE::UnifiedError::FError::IsValid () const inline
Definition at line 466 of file UnifiedError.h.
References ErrorCode, FORCEINLINE, and ModuleId.
PushErrorContext()
template<typename T> void UE::UnifiedError::FError::PushErrorContext (T && InErrorStruct) inline
Definition at line 435 of file UnifiedError.h.
References MoveTemp(), and PushErrorDetails().
PushErrorDetails()
void UE::UnifiedError::FError::PushErrorDetails (TRefCountPtr< IErrorDetails > InErrorDetails)
Referenced by PushErrorContext().
SerializeDetailsForLog()
void UE::UnifiedError::FError::SerializeDetailsForLog (FCbWriter & Writer) const
Friends And Related Symbol Documentation
operator==
bool operator== (const FError & Error, const FError & OtherError) friend
Definition at line 478 of file UnifiedError.h.
References FError(), UE::Error, ErrorCode, and ModuleId.
Field Documentation
ErrorCode
int32 UE::UnifiedError::FError::ErrorCode private
Definition at line 372 of file UnifiedError.h.
Referenced by FError(), FError(), FError(), Invalidate(), IsValid(), and operator==.
ErrorDetails
TRefCountPtr<const IErrorDetails> UE::UnifiedError::FError::ErrorDetails private
Definition at line 374 of file UnifiedError.h.
Referenced by FError(), FError(), FError(), GetErrorContext(), GetErrorDetails(), and Invalidate().
ModuleId
int32 UE::UnifiedError::FError::ModuleId private
Definition at line 373 of file UnifiedError.h.
Referenced by FError(), FError(), FError(), Invalidate(), IsValid(), and operator==.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/UnifiedError/UnifiedError.h