Unreal Engine 5.6 C++ API: UE::Geometry::FIndexPriorityQueue Class Reference
UE::Geometry::FIndexPriorityQueue Class Reference
This is a min-heap priority queue class that does not use an object for each queue node.
#include "IndexPriorityQueue.h"
Data Structures
struct FQueueNode
Public Member Functions
FIndexPriorityQueue ()
This constructor is provided for convenience, you must call Initialize()
FIndexPriorityQueue (int maxID)
Calls Initialize()
bool CheckIds ()
Check if node ordering is correct (for debugging/testing)
void Clear (bool bFreeMemory=true)
Reset the queue to empty state.
bool Contains (int NodeID) const
int Dequeue ()
Remove node at head of queue, update queue, and return id for that node.
int GetCount () const
int GetFirstNodeID () const
float GetFirstNodePriority () const
float GetPriority (int id)
Query the priority at node id, assuming it exists in queue.
void Initialize (int MaxNodeID)
Initialize internal data structures.
void Insert (int NodeID, float priority)
Add id to list w/ given priority.
bool IsValidQueue () const
Check if node ordering is correct (for debugging/testing)
void Remove (int NodeID)
Remove node associated with given ID from queue.
void Update (int NodeID, float Priority)
Update priority at node id, and then move it to correct position in queue.
Data Fields
bool EnableDebugChecks = false
set this to true during development to catch issues
TArray< int > id_to_index
mapping from external ids to internal node indices
TDynamicVector< FQueueNode > nodes
tree of allocated nodes, stored linearly.
int num_nodes
count of active nodes
Private Member Functions
bool has_higher_priority (int iHigher, int iLower) const
void move (int iFrom, int iTo)
move node at iFrom to iTo
void move_down (int iNode)
move iNode down tree branches to correct position, by iteratively swapping w/ children
void move_up (int iNode)
move iNode up tree to correct position by iteratively swapping w/ parent
void on_node_updated (int iNode)
call this after node is modified, to move it to correct position in queue
void remove_at_index (int NodeIndex)
remove node at index and update tree
void set (int iTo, FQueueNode &n)
set node at iTo
void swap_nodes_at_indices (int i1, int i2)
swap two nodes in the true
Detailed Description
This is a min-heap priority queue class that does not use an object for each queue node.
Integer IDs must be provided by the user to identify unique nodes. Internally an array is used to keep track of the mapping from ids to internal indices, so the max ID must also be provided.
Todo
based on C# code where TDynamicVector could not return a reference to internal element. In C++ we can, and code could be updated to be more efficient in many places.
id_to_index could be sparse in many situations...
Definition at line 21 of file IndexPriorityQueue.h.
Constructor & Destructor Documentation
FIndexPriorityQueue() [1/2]
UE::Geometry::FIndexPriorityQueue::FIndexPriorityQueue () inline
This constructor is provided for convenience, you must call Initialize()
Definition at line 46 of file IndexPriorityQueue.h.
References Initialize.
FIndexPriorityQueue() [2/2]
UE::Geometry::FIndexPriorityQueue::FIndexPriorityQueue (int maxID) inline
Calls Initialize()
Parameters
maxID maximum external ID that will be passed to any public functions
Definition at line 55 of file IndexPriorityQueue.h.
References Initialize.
Member Function Documentation
CheckIds()
bool UE::Geometry::FIndexPriorityQueue::CheckIds () inline
Check if node ordering is correct (for debugging/testing)
Definition at line 403 of file IndexPriorityQueue.h.
References Contains(), UE::Geometry::FIndexPriorityQueue::FQueueNode::id, id_to_index, UE::Geometry::FIndexPriorityQueue::FQueueNode::index, nodes, and num_nodes.
Clear()
void UE::Geometry::FIndexPriorityQueue::Clear (bool bFreeMemory = true) inline
Reset the queue to empty state.
if bFreeMemory is false, we don't discard internal data structures, so there will be less allocation next time
Definition at line 79 of file IndexPriorityQueue.h.
References check, id_to_index, nodes, and num_nodes.
Contains()
bool UE::Geometry::FIndexPriorityQueue::Contains (int NodeID) const inline
Returns
true if id is already in queue
Definition at line 106 of file IndexPriorityQueue.h.
References id_to_index, nodes, and num_nodes.
Referenced by CheckIds(), UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill(), GetPriority(), Insert(), Remove(), and Update().
Dequeue()
int UE::Geometry::FIndexPriorityQueue::Dequeue () inline
Remove node at head of queue, update queue, and return id for that node.
Returns
ID of node at head of queue
Definition at line 142 of file IndexPriorityQueue.h.
References check, EnableDebugChecks, GetCount(), nodes, and remove_at_index().
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill().
GetCount()
int UE::Geometry::FIndexPriorityQueue::GetCount () const inline
Returns
current size of queue
Definition at line 88 of file IndexPriorityQueue.h.
References num_nodes.
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill(), and Dequeue().
GetFirstNodeID()
int UE::Geometry::FIndexPriorityQueue::GetFirstNodeID () const inline
Returns
id of node at head of queue
Definition at line 94 of file IndexPriorityQueue.h.
References nodes.
GetFirstNodePriority()
float UE::Geometry::FIndexPriorityQueue::GetFirstNodePriority () const inline
Returns
id of node at head of queue
Definition at line 100 of file IndexPriorityQueue.h.
References nodes.
GetPriority()
float UE::Geometry::FIndexPriorityQueue::GetPriority (int id) inline
Query the priority at node id, assuming it exists in queue.
Behavior is undefined if you call w/ id that is not in queue
Returns
priority for node
Definition at line 193 of file IndexPriorityQueue.h.
References check, Contains(), EnableDebugChecks, id_to_index, and nodes.
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill().
has_higher_priority()
bool UE::Geometry::FIndexPriorityQueue::has_higher_priority (int iHigher, int iLower) const inline private
Returns
true if priority at iHigher is less than at iLower
Definition at line 374 of file IndexPriorityQueue.h.
References nodes.
Referenced by IsValidQueue(), and on_node_updated().
Initialize()
void UE::Geometry::FIndexPriorityQueue::Initialize (int MaxNodeID) inline
Initialize internal data structures.
Internally a fixed-size array is used to track mapping from IDs to internal node indices, so maxID must be provided up-front. If this seems problematic or inefficient, this is not the Priority Queue for you.
Parameters
MaxNodeID maximum external ID that will be passed to any public functions
Definition at line 67 of file IndexPriorityQueue.h.
References id_to_index, nodes, and num_nodes.
Insert()
void UE::Geometry::FIndexPriorityQueue::Insert (int NodeID, float priority) inline
Add id to list w/ given priority.
Do not call with same id twice!
Definition at line 121 of file IndexPriorityQueue.h.
References check, Contains(), EnableDebugChecks, UE::Geometry::FIndexPriorityQueue::FQueueNode::id, id_to_index, UE::Geometry::FIndexPriorityQueue::FQueueNode::index, move_up(), nodes, num_nodes, and UE::Geometry::FIndexPriorityQueue::FQueueNode::priority.
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill().
IsValidQueue()
bool UE::Geometry::FIndexPriorityQueue::IsValidQueue () const inline
Check if node ordering is correct (for debugging/testing)
Definition at line 386 of file IndexPriorityQueue.h.
References has_higher_priority(), and num_nodes.
move()
void UE::Geometry::FIndexPriorityQueue::move (int iFrom, int iTo) inline private
move node at iFrom to iTo
Definition at line 260 of file IndexPriorityQueue.h.
References UE::Geometry::FIndexPriorityQueue::FQueueNode::id, id_to_index, UE::Geometry::FIndexPriorityQueue::FQueueNode::index, and nodes.
Referenced by move_down(), and move_up().
move_down()
void UE::Geometry::FIndexPriorityQueue::move_down (int iNode) inline private
move iNode down tree branches to correct position, by iteratively swapping w/ children
Definition at line 306 of file IndexPriorityQueue.h.
References move(), nodes, num_nodes, UE::Geometry::FIndexPriorityQueue::FQueueNode::priority, and set().
Referenced by on_node_updated().
move_up()
void UE::Geometry::FIndexPriorityQueue::move_up (int iNode) inline private
move iNode up tree to correct position by iteratively swapping w/ parent
Definition at line 278 of file IndexPriorityQueue.h.
References move(), nodes, UE::Geometry::FIndexPriorityQueue::FQueueNode::priority, and set().
Referenced by Insert(), and on_node_updated().
on_node_updated()
void UE::Geometry::FIndexPriorityQueue::on_node_updated (int iNode) inline private
call this after node is modified, to move it to correct position in queue
Definition at line 363 of file IndexPriorityQueue.h.
References has_higher_priority(), move_down(), and move_up().
Referenced by remove_at_index(), and Update().
Remove()
void UE::Geometry::FIndexPriorityQueue::Remove (int NodeID) inline
Remove node associated with given ID from queue.
Behavior is undefined if you call w/ id that is not in queue
Definition at line 157 of file IndexPriorityQueue.h.
References check, Contains(), EnableDebugChecks, id_to_index, and remove_at_index().
remove_at_index()
void UE::Geometry::FIndexPriorityQueue::remove_at_index (int NodeIndex) inline private
remove node at index and update tree
Definition at line 211 of file IndexPriorityQueue.h.
References id_to_index, nodes, num_nodes, on_node_updated(), and swap_nodes_at_indices().
Referenced by Dequeue(), and Remove().
set()
void UE::Geometry::FIndexPriorityQueue::set (int iTo, FQueueNode & n) inline private
set node at iTo
Definition at line 269 of file IndexPriorityQueue.h.
References UE::Geometry::FIndexPriorityQueue::FQueueNode::id, id_to_index, UE::Geometry::FIndexPriorityQueue::FQueueNode::index, and nodes.
Referenced by move_down(), and move_up().
swap_nodes_at_indices()
void UE::Geometry::FIndexPriorityQueue::swap_nodes_at_indices (int i1, int i2) inline private
swap two nodes in the true
Definition at line 246 of file IndexPriorityQueue.h.
References UE::Geometry::FIndexPriorityQueue::FQueueNode::id, id_to_index, UE::Geometry::FIndexPriorityQueue::FQueueNode::index, and nodes.
Referenced by remove_at_index().
Update()
void UE::Geometry::FIndexPriorityQueue::Update (int NodeID, float Priority) inline
Update priority at node id, and then move it to correct position in queue.
Behavior is undefined if you call w/ id that is not in queue
Definition at line 172 of file IndexPriorityQueue.h.
References check, Contains(), EnableDebugChecks, id_to_index, nodes, on_node_updated(), and UE::Geometry::FIndexPriorityQueue::FQueueNode::priority.
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill().
Field Documentation
EnableDebugChecks
bool UE::Geometry::FIndexPriorityQueue::EnableDebugChecks = false
set this to true during development to catch issues
Definition at line 25 of file IndexPriorityQueue.h.
Referenced by Dequeue(), GetPriority(), Insert(), Remove(), and Update().
id_to_index
TArray<int> UE::Geometry::FIndexPriorityQueue::id_to_index
mapping from external ids to internal node indices
Definition at line 40 of file IndexPriorityQueue.h.
Referenced by CheckIds(), Clear(), Contains(), GetPriority(), Initialize(), Insert(), move(), Remove(), remove_at_index(), set(), swap_nodes_at_indices(), and Update().
nodes
TDynamicVector<FQueueNode> UE::Geometry::FIndexPriorityQueue::nodes
tree of allocated nodes, stored linearly.
active up to num_nodes (allocated may be larger)
Definition at line 36 of file IndexPriorityQueue.h.
Referenced by CheckIds(), Clear(), Contains(), Dequeue(), GetFirstNodeID(), GetFirstNodePriority(), GetPriority(), has_higher_priority(), Initialize(), Insert(), move(), move_down(), move_up(), remove_at_index(), set(), swap_nodes_at_indices(), and Update().
num_nodes
int UE::Geometry::FIndexPriorityQueue::num_nodes
count of active nodes
Definition at line 38 of file IndexPriorityQueue.h.
Referenced by CheckIds(), Clear(), Contains(), GetCount(), Initialize(), Insert(), IsValidQueue(), move_down(), and remove_at_index().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/IndexPriorityQueue.h