Unreal Engine 5.6 C++ API: UE::Tasks::FTaskPriorityCVar Class Reference
UE::Tasks::FTaskPriorityCVar Class Reference
#include "Task.h"
Public Member Functions
FTaskPriorityCVar (const TCHAR *Name, const TCHAR *Help, ETaskPriority DefaultPriority, EExtendedTaskPriority DefaultExtendedPriority)
EExtendedTaskPriority GetExtendedTaskPriority () const
ETaskPriority GetTaskPriority () const
Private Member Functions
void OnSettingChanged (IConsoleVariable *Variable)
Static Private Member Functions
static FString ConfigStringFromPriorities (ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority)
static FString CreateFullHelpText (const TCHAR *Name, const TCHAR *OriginalHelp)
Private Attributes
EExtendedTaskPriority ExtendedPriority
FString FullHelpText
ETaskPriority Priority
FString RawSetting
FAutoConsoleVariableRef Variable
Detailed Description
Definition at line 578 of file Task.h.
Constructor & Destructor Documentation
FTaskPriorityCVar()
UE::Tasks::FTaskPriorityCVar::FTaskPriorityCVar (const TCHAR * Name, const TCHAR * Help, ETaskPriority DefaultPriority, EExtendedTaskPriority DefaultExtendedPriority) inline
Definition at line 581 of file Task.h.
References FTaskPriorityCVar(), ConfigStringFromPriorities(), CreateFullHelpText(), ECVF_Default, ExtendedPriority, FullHelpText, Name, OnSettingChanged(), Priority, RawSetting, and Variable.
Referenced by FTaskPriorityCVar().
Member Function Documentation
ConfigStringFromPriorities()
FString UE::Tasks::FTaskPriorityCVar::ConfigStringFromPriorities (ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority) static private
Referenced by FTaskPriorityCVar().
CreateFullHelpText()
FString UE::Tasks::FTaskPriorityCVar::CreateFullHelpText (const TCHAR * Name, const TCHAR * OriginalHelp) static private
References Name.
Referenced by FTaskPriorityCVar().
GetExtendedTaskPriority()
EExtendedTaskPriority UE::Tasks::FTaskPriorityCVar::GetExtendedTaskPriority () const inline
Definition at line 595 of file Task.h.
References ExtendedPriority.
GetTaskPriority()
ETaskPriority UE::Tasks::FTaskPriorityCVar::GetTaskPriority () const inline
Definition at line 590 of file Task.h.
References Priority.
OnSettingChanged()
void UE::Tasks::FTaskPriorityCVar::OnSettingChanged (IConsoleVariable * Variable) private
References Variable.
Referenced by FTaskPriorityCVar().
Field Documentation
ExtendedPriority
EExtendedTaskPriority UE::Tasks::FTaskPriorityCVar::ExtendedPriority private
Definition at line 610 of file Task.h.
Referenced by FTaskPriorityCVar(), and GetExtendedTaskPriority().
FullHelpText
FString UE::Tasks::FTaskPriorityCVar::FullHelpText private
Definition at line 607 of file Task.h.
Referenced by FTaskPriorityCVar().
Priority
ETaskPriority UE::Tasks::FTaskPriorityCVar::Priority private
Definition at line 609 of file Task.h.
Referenced by FTaskPriorityCVar(), and GetTaskPriority().
RawSetting
FString UE::Tasks::FTaskPriorityCVar::RawSetting private
Definition at line 606 of file Task.h.
Referenced by FTaskPriorityCVar().
Variable
FAutoConsoleVariableRef UE::Tasks::FTaskPriorityCVar::Variable private
Definition at line 608 of file Task.h.
Referenced by FTaskPriorityCVar(), and OnSettingChanged().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Tasks/Task.h