Unreal Engine 5.6 C++ API: FPixelStreamingHMD Class Reference
FPixelStreamingHMD Class Reference
Pixel Streamed Head Mounted Display.
#include "PixelStreamingHMD.h"
Public Member Functions
FPixelStreamingHMD (const FAutoRegister &)
Constructor.
virtual ~FPixelStreamingHMD ()
Destructor.
virtual void AdjustViewRect (int32 ViewIndex, int32 &X, int32 &Y, uint32 &SizeX, uint32 &SizeY) const override
virtual void CalculateStereoViewOffset (const int32 ViewIndex, FRotator &ViewRotation, const float InWorldToMeters, FVector &ViewLocation) override
virtual void DrawDistortionMesh_RenderThread (struct FHeadMountedDisplayPassContext &Context, const FIntPoint &TextureSize) override
virtual void EnableHMD (bool allow=true) override
virtual bool EnableStereo (bool stereo=true) override
virtual bool EnumerateTrackedDevices (TArray< int32 > &OutDevices, EXRTrackedDeviceType Type=EXRTrackedDeviceType::Any) override
virtual FQuat GetBaseOrientation () const override
virtual FVector GetBasePosition () const override
virtual FRotator GetBaseRotation () const override
virtual bool GetCurrentPose (int32 DeviceId, FQuat &CurrentOrientation, FVector &CurrentPosition) override
virtual void GetEyeRenderParams_RenderThread (const struct FHeadMountedDisplayPassContext &Context, FVector2D &EyeToSrcUVScaleValue, FVector2D &EyeToSrcUVOffsetValue) const override
virtual void GetFieldOfView (float &OutHFOVInDegrees, float &OutVFOVInDegrees) const override
virtual class IHeadMountedDisplay * GetHMDDevice () override
virtual bool GetHMDDistortionEnabled (EShadingPath ShadingPath) const override
virtual bool GetHMDMonitorInfo (MonitorInfo &) override
virtual float GetInterpupillaryDistance () const override
virtual bool GetRelativeEyePose (int32 DeviceId, int32 ViewIndex, FQuat &OutOrientation, FVector &OutPosition) override
virtual FMatrix GetStereoProjectionMatrix (const int32 ViewIndex) const override
virtual class TSharedPtr< class IStereoRendering, ESPMode::ThreadSafe > GetStereoRenderingDevice () override
virtual FName GetSystemName () const override
IXRTrackingSystem interface.
int32 GetXRSystemFlags () const
virtual bool IsChromaAbCorrectionEnabled () const override
virtual bool IsHMDConnected () override
IHeadMountedDisplay interface.
virtual bool IsHMDEnabled () const override
bool IsInitialized () const
virtual bool IsStereoEnabled () const override
IStereoRendering interface.
virtual void ResetOrientation (float Yaw=0.f) override
virtual void ResetOrientationAndPosition (float yaw=0.f) override
virtual void ResetPosition () override
virtual void SetBaseOrientation (const FQuat &BaseOrient) override
virtual void SetBasePosition (const FVector &InBasePosition) override
virtual void SetBaseRotation (const FRotator &BaseRot) override
void SetEyeViews (FTransform Left, FMatrix LeftProj, FTransform Right, FMatrix RightProj, FTransform HMD)
virtual void SetInterpupillaryDistance (float NewInterpupillaryDistance) override
void SetTransform (FTransform Transform)
virtual void SetupViewFamily (FSceneViewFamily &InViewFamily) override
ISceneViewExtension interface.
Public Member Functions inherited from FHMDSceneViewExtension
FHMDSceneViewExtension (const FAutoRegister &AutoReg)
Public Member Functions inherited from FSceneViewExtensionBase
FSceneViewExtensionBase (const FAutoRegister &)
virtual ~FSceneViewExtensionBase ()
virtual bool IsActiveThisFrame (const FSceneViewExtensionContext &Context) const override final
Returning false disables the extension for the current frame in the given context.
Public Member Functions inherited from ISceneViewExtension
virtual void BeginRenderViewFamily (FSceneViewFamily &InViewFamily)
Called on game thread when view family is about to be rendered.
virtual int32 GetPriority () const
Called to determine view extensions priority in relation to other view extensions, higher comes first.
virtual void PostCreateSceneRenderer (const FSceneViewFamily &InViewFamily, ISceneRenderer *Renderer)
Called on game thread after the scene renderers have been created.
virtual void PostRenderBasePassDeferred_RenderThread (FRDGBuilder &GraphBuilder, FSceneView &InView, const FRenderTargetBindingSlots &RenderTargets, TRDGUniformBufferRef< FSceneTextureUniformParameters > SceneTextures)
Called right after Base Pass rendering finished when using the deferred renderer.
virtual void PostRenderBasePassMobile_RenderThread (FRHICommandList &RHICmdList, FSceneView &InView)
Called right after Base Pass rendering finished when using the mobile renderer.
virtual void PostRenderView_RenderThread (FRDGBuilder &GraphBuilder, FSceneView &InView)
Allows to render content after the 3D content scene, useful for debugging.
virtual void PostRenderViewFamily_RenderThread (FRDGBuilder &GraphBuilder, FSceneViewFamily &InViewFamily)
Allows to render content after the 3D content scene, useful for debugging.
virtual void PreInitViews_RenderThread (FRDGBuilder &GraphBuilder)
Called on render thread prior to initializing views.
virtual void PrePostProcessPass_RenderThread (FRDGBuilder &GraphBuilder, const FSceneView &InView, const FPostProcessingInputs &Inputs)
Called right before Post Processing rendering begins.
virtual void PrePostProcessPassMobile_RenderThread (FRDGBuilder &GraphBuilder, const FSceneView &InView, const FMobilePostProcessingInputs &Inputs)
Called right before Post Processing rendering begins for the mobile renderer.
virtual void PreRenderBasePass_RenderThread (FRDGBuilder &GraphBuilder, bool bDepthBufferIsPopulated)
Called on render thread right before Base Pass rendering.
virtual void PreRenderView_RenderThread (FRDGBuilder &GraphBuilder, FSceneView &InView)
Called on render thread at the start of rendering, for each view, after PreRenderViewFamily_RenderThread call.
virtual void PreRenderViewFamily_RenderThread (FRDGBuilder &GraphBuilder, FSceneViewFamily &InViewFamily)
Called on render thread at the start of rendering.
virtual void SetupView (FSceneViewFamily &InViewFamily, FSceneView &InView)
Called on game thread when creating the view.
virtual void SetupViewPoint (APlayerController *Player, FMinimalViewInfo &InViewInfo)
Called when creating the viewpoint, before culling, in case an external tracking device needs to modify the base location of the view.
virtual void SetupViewProjectionMatrix (FSceneViewProjectionData &InOutProjectionData)
Called when creating the view, in case non-stereo devices need to update projection matrix.
virtual void SubscribeToPostProcessingPass (EPostProcessingPass Pass, const FSceneView &InView, FPostProcessingPassDelegateArray &InOutPassCallbacks, bool bIsPassEnabled)
This will be called at the beginning of post processing to make sure that each view extension gets a chance to subscribe to a post-processing pass event.
UE_DEPRECATED (5.5, "SubscribeToPostProcessingPass now takes a SceneView") virtual void SubscribeToPostProcessingPass(EPostProcessingPass Pass
Deprecated APIs - These are no longer called and must be converted to restore functionality.
Public Member Functions inherited from TSharedFromThis< FSceneViewExtensionBase, ESPMode::ThreadSafe >
TSharedRef< FSceneViewExtensionBase, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FSceneViewExtensionBase, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual float GetWorldToMetersScale () const override
FXRTrackingSystemBase protected interface.
Protected Member Functions inherited from FHMDSceneViewExtension
virtual bool IsActiveThisFrame_Internal (const FSceneViewExtensionContext &Context) const override
Protected Member Functions inherited from TSharedFromThis< FSceneViewExtensionBase, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
FVector BasePosition = FVector::ZeroVector
bool bReceivedTransforms = false
bool bStereoEnabled
FTransform CurHmdTransform
float CurLeftEyeProjOffsetX = 0.0f
float CurLeftEyeProjOffsetY = 0.0f
float CurRightEyeProjOffsetX = 0.0f
float CurRightEyeProjOffsetY = 0.0f
float FarClip = 10000.0f
float HFoVRads = FMath::DegreesToRadians(90.0f)
float InterpupillaryDistance
double LastResChangeSeconds = 0.0f
FVector LeftEyePosOffset
FQuat LeftEyeRotOffset
float NearClip = 10.0f
FVector RightEyePosOffset
FQuat RightEyeRotOffset
float TargetAspectRatio = 9.0f/16.0f
float VFoVRads = FMath::DegreesToRadians(90.0f)
float WorldToMeters
Additional Inherited Members
Public Types inherited from ISceneViewExtension
enum class EPostProcessingPass : uint32 {
BeforeDOF , AfterDOF , TranslucencyAfterDOF , SSRInput ,
ReplacingTonemapper , MotionBlur , Tonemap , FXAA ,
VisualizeDepthOfField , MAX
}
Data Fields inherited from FSceneViewExtensionBase
TArray< FSceneViewExtensionIsActiveFunctor > IsActiveThisFrameFunctions
Data Fields inherited from ISceneViewExtension
FPostProcessingPassDelegateArray & InOutPassCallbacks
Static Protected Member Functions inherited from TSharedFromThis< FSceneViewExtensionBase, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Pixel Streamed Head Mounted Display.
Definition at line 20 of file PixelStreamingHMD.h.
Constructor & Destructor Documentation
FPixelStreamingHMD()
FPixelStreamingHMD::FPixelStreamingHMD (const FAutoRegister &)
Constructor.
~FPixelStreamingHMD()
virtual FPixelStreamingHMD::~FPixelStreamingHMD () virtual
Destructor.
Member Function Documentation
AdjustViewRect()
virtual void FPixelStreamingHMD::AdjustViewRect (int32 ViewIndex, int32 & X, int32 & Y, uint32 & SizeX, uint32 & SizeY) const override virtual
References X, and Y.
CalculateStereoViewOffset()
virtual void FPixelStreamingHMD::CalculateStereoViewOffset (const int32 ViewIndex, FRotator & ViewRotation, const float InWorldToMeters, FVector & ViewLocation) override virtual
References FVector.
DrawDistortionMesh_RenderThread()
virtual void FPixelStreamingHMD::DrawDistortionMesh_RenderThread (struct FHeadMountedDisplayPassContext & Context, const FIntPoint & TextureSize) override virtual
EnableHMD()
virtual void FPixelStreamingHMD::EnableHMD (bool allow = true) override virtual
EnableStereo()
virtual bool FPixelStreamingHMD::EnableStereo (bool stereo = true) override virtual
EnumerateTrackedDevices()
virtual bool FPixelStreamingHMD::EnumerateTrackedDevices (TArray< int32 > & OutDevices, EXRTrackedDeviceType Type = EXRTrackedDeviceType::Any) override virtual
GetBaseOrientation()
virtual FQuat FPixelStreamingHMD::GetBaseOrientation () const inline override virtual
Definition at line 49 of file PixelStreamingHMD.h.
References UE::Math::TQuat< double >::Identity.
GetBasePosition()
virtual FVector FPixelStreamingHMD::GetBasePosition () const inline override virtual
Definition at line 33 of file PixelStreamingHMD.h.
References BasePosition, and FVector.
GetBaseRotation()
virtual FRotator FPixelStreamingHMD::GetBaseRotation () const inline override virtual
Definition at line 46 of file PixelStreamingHMD.h.
References UE::Math::TRotator< double >::ZeroRotator.
GetCurrentPose()
virtual bool FPixelStreamingHMD::GetCurrentPose (int32 DeviceId, FQuat & CurrentOrientation, FVector & CurrentPosition) override virtual
References FVector.
GetEyeRenderParams_RenderThread()
virtual void FPixelStreamingHMD::GetEyeRenderParams_RenderThread (const struct FHeadMountedDisplayPassContext & Context, FVector2D & EyeToSrcUVScaleValue, FVector2D & EyeToSrcUVOffsetValue) const override virtual
GetFieldOfView()
virtual void FPixelStreamingHMD::GetFieldOfView (float & OutHFOVInDegrees, float & OutVFOVInDegrees) const override virtual
GetHMDDevice()
virtual class IHeadMountedDisplay * FPixelStreamingHMD::GetHMDDevice () inline override virtual
Definition at line 51 of file PixelStreamingHMD.h.
GetHMDDistortionEnabled()
virtual bool FPixelStreamingHMD::GetHMDDistortionEnabled (EShadingPath ShadingPath) const inline override virtual
Definition at line 70 of file PixelStreamingHMD.h.
GetHMDMonitorInfo()
virtual bool FPixelStreamingHMD::GetHMDMonitorInfo (MonitorInfo &) override virtual
GetInterpupillaryDistance()
virtual float FPixelStreamingHMD::GetInterpupillaryDistance () const override virtual
GetRelativeEyePose()
virtual bool FPixelStreamingHMD::GetRelativeEyePose (int32 DeviceId, int32 ViewIndex, FQuat & OutOrientation, FVector & OutPosition) override virtual
References FVector.
GetStereoProjectionMatrix()
virtual FMatrix FPixelStreamingHMD::GetStereoProjectionMatrix (const int32 ViewIndex) const override virtual
GetStereoRenderingDevice()
virtual class TSharedPtr< class IStereoRendering, ESPMode::ThreadSafe > FPixelStreamingHMD::GetStereoRenderingDevice () inline override virtual
Definition at line 53 of file PixelStreamingHMD.h.
References GetStereoRenderingDevice(), TSharedFromThis< FSceneViewExtensionBase, ESPMode::ThreadSafe >::SharedThis(), and ThreadSafe.
Referenced by GetStereoRenderingDevice().
GetSystemName()
virtual FName FPixelStreamingHMD::GetSystemName () const inline override virtual
IXRTrackingSystem interface.
Definition at line 24 of file PixelStreamingHMD.h.
References TEXT.
GetWorldToMetersScale()
virtual float FPixelStreamingHMD::GetWorldToMetersScale () const override protected virtual
FXRTrackingSystemBase protected interface.
GetXRSystemFlags()
int32 FPixelStreamingHMD::GetXRSystemFlags () const inline
Definition at line 30 of file PixelStreamingHMD.h.
IsChromaAbCorrectionEnabled()
virtual bool FPixelStreamingHMD::IsChromaAbCorrectionEnabled () const override virtual
IsHMDConnected()
virtual bool FPixelStreamingHMD::IsHMDConnected () inline override virtual
IHeadMountedDisplay interface.
Definition at line 64 of file PixelStreamingHMD.h.
IsHMDEnabled()
virtual bool FPixelStreamingHMD::IsHMDEnabled () const override virtual
IsInitialized()
bool FPixelStreamingHMD::IsInitialized () const inline
Returns
True if the HMD was initialized OK
Definition at line 96 of file PixelStreamingHMD.h.
IsStereoEnabled()
virtual bool FPixelStreamingHMD::IsStereoEnabled () const override virtual
IStereoRendering interface.
ResetOrientation()
virtual void FPixelStreamingHMD::ResetOrientation (float Yaw = 0.f) inline override virtual
Definition at line 41 of file PixelStreamingHMD.h.
ResetOrientationAndPosition()
virtual void FPixelStreamingHMD::ResetOrientationAndPosition (float yaw = 0.f) override virtual
ResetPosition()
virtual void FPixelStreamingHMD::ResetPosition () inline override virtual
Definition at line 42 of file PixelStreamingHMD.h.
SetBaseOrientation()
virtual void FPixelStreamingHMD::SetBaseOrientation (const FQuat & BaseOrient) inline override virtual
Definition at line 48 of file PixelStreamingHMD.h.
SetBasePosition()
virtual void FPixelStreamingHMD::SetBasePosition (const FVector & InBasePosition) inline override virtual
Definition at line 32 of file PixelStreamingHMD.h.
References BasePosition, and FVector.
SetBaseRotation()
virtual void FPixelStreamingHMD::SetBaseRotation (const FRotator & BaseRot) inline override virtual
Definition at line 45 of file PixelStreamingHMD.h.
SetEyeViews()
void FPixelStreamingHMD::SetEyeViews (FTransform Left, FMatrix LeftProj, FTransform Right, FMatrix RightProj, FTransform HMD)
References Left, and Right.
SetInterpupillaryDistance()
virtual void FPixelStreamingHMD::SetInterpupillaryDistance (float NewInterpupillaryDistance) override virtual
SetTransform()
void FPixelStreamingHMD::SetTransform (FTransform Transform) inline
Definition at line 98 of file PixelStreamingHMD.h.
References CurHmdTransform, and Transform.
SetupViewFamily()
virtual void FPixelStreamingHMD::SetupViewFamily (FSceneViewFamily & InViewFamily) override virtual
ISceneViewExtension interface.
Reimplemented from ISceneViewExtension.
Field Documentation
BasePosition
FVector FPixelStreamingHMD::BasePosition = FVector::ZeroVector private
Definition at line 102 of file PixelStreamingHMD.h.
Referenced by GetBasePosition(), and SetBasePosition().
bReceivedTransforms
bool FPixelStreamingHMD::bReceivedTransforms = false private
Definition at line 120 of file PixelStreamingHMD.h.
bStereoEnabled
bool FPixelStreamingHMD::bStereoEnabled private
Definition at line 119 of file PixelStreamingHMD.h.
CurHmdTransform
FTransform FPixelStreamingHMD::CurHmdTransform private
Definition at line 103 of file PixelStreamingHMD.h.
Referenced by SetTransform().
CurLeftEyeProjOffsetX
float FPixelStreamingHMD::CurLeftEyeProjOffsetX = 0.0f private
Definition at line 112 of file PixelStreamingHMD.h.
CurLeftEyeProjOffsetY
float FPixelStreamingHMD::CurLeftEyeProjOffsetY = 0.0f private
Definition at line 113 of file PixelStreamingHMD.h.
CurRightEyeProjOffsetX
float FPixelStreamingHMD::CurRightEyeProjOffsetX = 0.0f private
Definition at line 114 of file PixelStreamingHMD.h.
CurRightEyeProjOffsetY
float FPixelStreamingHMD::CurRightEyeProjOffsetY = 0.0f private
Definition at line 115 of file PixelStreamingHMD.h.
FarClip
float FPixelStreamingHMD::FarClip = 10000.0f private
Definition at line 118 of file PixelStreamingHMD.h.
HFoVRads
float FPixelStreamingHMD::HFoVRads = FMath::DegreesToRadians(90.0f) private
Definition at line 110 of file PixelStreamingHMD.h.
InterpupillaryDistance
float FPixelStreamingHMD::InterpupillaryDistance private
Definition at line 109 of file PixelStreamingHMD.h.
LastResChangeSeconds
double FPixelStreamingHMD::LastResChangeSeconds = 0.0f private
Definition at line 121 of file PixelStreamingHMD.h.
LeftEyePosOffset
FVector FPixelStreamingHMD::LeftEyePosOffset private
Definition at line 104 of file PixelStreamingHMD.h.
LeftEyeRotOffset
FQuat FPixelStreamingHMD::LeftEyeRotOffset private
Definition at line 106 of file PixelStreamingHMD.h.
NearClip
float FPixelStreamingHMD::NearClip = 10.0f private
Definition at line 117 of file PixelStreamingHMD.h.
RightEyePosOffset
FVector FPixelStreamingHMD::RightEyePosOffset private
Definition at line 105 of file PixelStreamingHMD.h.
RightEyeRotOffset
FQuat FPixelStreamingHMD::RightEyeRotOffset private
Definition at line 107 of file PixelStreamingHMD.h.
TargetAspectRatio
float FPixelStreamingHMD::TargetAspectRatio = 9.0f/16.0f private
Definition at line 116 of file PixelStreamingHMD.h.
VFoVRads
float FPixelStreamingHMD::VFoVRads = FMath::DegreesToRadians(90.0f) private
Definition at line 111 of file PixelStreamingHMD.h.
WorldToMeters
float FPixelStreamingHMD::WorldToMeters private
Definition at line 108 of file PixelStreamingHMD.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingHMD/Public/PixelStreamingHMD.h