Unreal Engine 5.6 C++ API: FThumbnailPreviewScene Class Reference
FThumbnailPreviewScene Class Reference abstract
#include "ThumbnailHelpers.h"
Data Structures
struct FConstructionValues
Public Member Functions
UNREALED_API FThumbnailPreviewScene (const FConstructionValues &InCVS=FConstructionValues())
Constructor.
UNREALED_API FSceneView * CreateView (FSceneViewFamily *ViewFamily, int32 X, int32 Y, uint32 SizeX, uint32 SizeY) const
Allocates then adds an FSceneView to the ViewFamily.
virtual UNREALED_API TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
virtual ETickableTickType GetTickableTickType () const override
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual UNREALED_API void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
UE_DEPRECATED (5.0, "Use CreateView") UNREALED_API void GetView(FSceneViewFamily *ViewFamily
Public Member Functions inherited from FPreviewScene
FPreviewScene (ConstructionValues CVS=ConstructionValues())
virtual ~FPreviewScene ()
virtual void AddComponent (class UActorComponent *Component, const FTransform &LocalToWorld, bool bAttachToRoot=false)
Adds a component to the preview scene.
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void ClearLineBatcher ()
Clean out the line batcher each frame.
virtual FLinearColor GetBackgroundColor () const
Get the background color we use by default.
FRotator GetLightDirection ()
class ULineBatchComponent * GetLineBatcher () const
Access to line drawing.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
FSceneInterface * GetScene () const
UWorld * GetWorld () const
void LoadSettings (const TCHAR *Section)
Load/Save settings to the config, specifying the key.
virtual void RemoveComponent (class UActorComponent *Component)
Removes a component from the preview scene.
void SaveSettings (const TCHAR *Section)
void SetLightBrightness (float LightBrightness)
void SetLightColor (const FColor &LightColor)
void SetLightDirection (const FRotator &InLightDir)
void SetSkyBrightness (float SkyBrightness)
void SetSkyCubemap (class UTextureCube *Cubemap)
void UpdateCaptureContents ()
Update sky and reflection captures.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Data Fields
int32 int32 uint32 uint32 SizeY const
int32 int32 uint32 SizeX
int32 X
int32 int32 Y
Data Fields inherited from FPreviewScene
class UDirectionalLightComponent * DirectionalLight = nullptr
class USkyLightComponent * SkyLight = nullptr
Protected Member Functions
UNREALED_API float GetBoundsZOffset (const FBoxSphereBounds &Bounds) const
Helper function to get the bounds offset to display an asset.
virtual UNREALED_API float GetFOV () const
Returns FOV value to use for the view matrix.
virtual void GetViewMatrixParameters (const float InFOVDegrees, FVector &OutOrigin, float &OutOrbitPitch, float &OutOrbitYaw, float &OutOrbitZoom) const =0
Gets parameters to create a view matrix to be used by CreateView().
virtual bool ShouldClampOrbitZoom () const
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Protected Attributes inherited from FPreviewScene
bool bForceAllUsedMipsResident
This controls whether or not all mip levels of textures used by UMeshComponents added to this preview window should be loaded and remain loaded.
class ULineBatchComponent * LineBatcher = nullptr
TObjectPtr< class UWorld > PreviewWorld = nullptr
Detailed Description
Definition at line 18 of file ThumbnailHelpers.h.
Constructor & Destructor Documentation
FThumbnailPreviewScene()
UNREALED_API FThumbnailPreviewScene::FThumbnailPreviewScene (const FConstructionValues & InCVS = FConstructionValues()) explicit
Constructor.
Member Function Documentation
CreateView()
UNREALED_API FSceneView * FThumbnailPreviewScene::CreateView (FSceneViewFamily * ViewFamily, int32 X, int32 Y, uint32 SizeX, uint32 SizeY) const nodiscard
Allocates then adds an FSceneView to the ViewFamily.
References const, CreateView(), SizeX, X, and Y.
Referenced by CreateView().
GetBoundsZOffset()
UNREALED_API float FThumbnailPreviewScene::GetBoundsZOffset (const FBoxSphereBounds & Bounds) const protected
Helper function to get the bounds offset to display an asset.
GetFOV()
virtual UNREALED_API float FThumbnailPreviewScene::GetFOV () const protected virtual
Returns FOV value to use for the view matrix.
GetStatId()
virtual UNREALED_API TStatId FThumbnailPreviewScene::GetStatId () const override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
GetTickableTickType()
virtual ETickableTickType FThumbnailPreviewScene::GetTickableTickType () const inline override virtual
Virtual that can be overloaded by the inheriting class and is called before first tick.
It is used to determine whether an object can possibly tick, and if not, it will not get added to the tickable objects array. If the tickable tick type is Conditional then the virtual IsTickable will be called to determine whether to tick the object on each given frame.
Returns
an enum defining the rules for ticking this object.
Reimplemented from FTickableObjectBase.
Definition at line 65 of file ThumbnailHelpers.h.
References Always, and GetTickableTickType().
Referenced by GetTickableTickType().
GetViewMatrixParameters()
virtual void FThumbnailPreviewScene::GetViewMatrixParameters (const float InFOVDegrees, FVector & OutOrigin, float & OutOrbitPitch, float & OutOrbitYaw, float & OutOrbitZoom) const protected pure virtual
Gets parameters to create a view matrix to be used by CreateView().
Implemented in children classes.
Parameters
InFOVDegrees The FOV used to display the thumbnail. Often used to calculate the output parameters.
OutOrigin The origin of the orbit view. Typically the center of the bounds of the target object.
OutOrbitPitch The pitch of the orbit cam around the object.
OutOrbitYaw The yaw of the orbit cam around the object.
OutOrbitZoom The camera distance from the object.
Implemented in FAnimationSequenceThumbnailScene, FAnimBlueprintThumbnailScene, FBlendSpaceThumbnailScene, FClassActorThumbnailScene, FFleshAssetThumbnailScene, FMaterialThumbnailScene, FParticleSystemThumbnailScene, FPhysicsAssetThumbnailScene, FSkeletalMeshThumbnailScene, and FStaticMeshThumbnailScene.
References FVector.
ShouldClampOrbitZoom()
virtual bool FThumbnailPreviewScene::ShouldClampOrbitZoom () const inline protected virtual
Definition at line 85 of file ThumbnailHelpers.h.
Tick()
virtual UNREALED_API void FThumbnailPreviewScene::Tick (float DeltaTime) override virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
References DeltaTime, and Tick().
Referenced by Tick().
UE_DEPRECATED()
FThumbnailPreviewScene::UE_DEPRECATED (5. 0, "Use CreateView")
Field Documentation
const
int32 int32 uint32 uint32 SizeY FThumbnailPreviewScene::const
Definition at line 58 of file ThumbnailHelpers.h.
Referenced by CreateView().
SizeX
int32 int32 uint32 FThumbnailPreviewScene::SizeX
Definition at line 58 of file ThumbnailHelpers.h.
Referenced by CreateView().
X
int32 FThumbnailPreviewScene::X
Definition at line 58 of file ThumbnailHelpers.h.
Referenced by CreateView().
Y
int32 int32 FThumbnailPreviewScene::Y
Definition at line 58 of file ThumbnailHelpers.h.
Referenced by CreateView().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/ThumbnailHelpers.h