Unreal Engine 5.6 C++ API: Metasound::SendNodePrivate::TSendOperator< TDataType > Class Template Reference
Metasound::SendNodePrivate::TSendOperator< TDataType > Class Template Reference
#include "MetasoundSendNode.h"
Public Member Functions
TSendOperator (TDataReadReference< TDataType > InInputData, TDataReadReference< FSendAddress > InSendAddress, const FOperatorSettings &InOperatorSettings)
virtual ~TSendOperator ()
virtual void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TSendOperator< TDataType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static FVertexInterface DeclareVertexInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
static const FVertexName & GetSendInputName ()
Private Member Functions
TSenderPtr< TDataType > CreateNewSender () const
FSendAddress GetSendAddressWithDataType (const FSendAddress &InAddress) const
void ResetSenderAndCleanupChannel ()
Private Attributes
FSendAddress CachedSendAddress
FSenderInitParams CachedSenderParams
TDataReadReference< TDataType > InputData
TDataReadReference< FSendAddress > SendAddress
TSenderPtr< TDataType > Sender
Additional Inherited Members
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Detailed Description
template<typename TDataType>
class Metasound::SendNodePrivate::TSendOperator< TDataType >
Definition at line 31 of file MetasoundSendNode.h.
Constructor & Destructor Documentation
TSendOperator()
template<typename TDataType> Metasound::SendNodePrivate::TSendOperator< TDataType >::TSendOperator (TDataReadReference< TDataType > InInputData, TDataReadReference< FSendAddress > InSendAddress, const FOperatorSettings & InOperatorSettings) inline
Definition at line 41 of file MetasoundSendNode.h.
References CachedSendAddress, CachedSenderParams, InputData, and SendAddress.
~TSendOperator()
template<typename TDataType> virtual Metasound::SendNodePrivate::TSendOperator< TDataType >::~TSendOperator () inline virtual
Definition at line 51 of file MetasoundSendNode.h.
References ResetSenderAndCleanupChannel().
Member Function Documentation
BindInputs()
template<typename TDataType> virtual void Metasound::SendNodePrivate::TSendOperator< TDataType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 56 of file MetasoundSendNode.h.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), GetSendInputName(), InputData, METASOUND_GET_PARAM_NAME, and SendAddress.
BindOutputs()
template<typename TDataType> virtual void Metasound::SendNodePrivate::TSendOperator< TDataType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 63 of file MetasoundSendNode.h.
CreateNewSender()
template<typename TDataType> TSenderPtr< TDataType > Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateNewSender () const inline private
Definition at line 167 of file MetasoundSendNode.h.
References CachedSenderParams, ensure, Metasound::FDataTransmissionCenter::Get(), Metasound::GetMetasoundDataTypeName(), GetSendAddressWithDataType(), Metasound::FDataTransmissionCenter::RegisterNewSender(), and SendAddress.
Referenced by Execute(), and Reset().
CreateOperator()
template<typename TDataType> TUniquePtr< IOperator > Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 138 of file MetasoundSendNode.h.
References Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), GetSendInputName(), Metasound::FBuildOperatorParams::InputData, Metasound::FInputVertexInterfaceData::IsVertexBound(), MakeUnique(), METASOUND_GET_PARAM_NAME, and Metasound::FBuildOperatorParams::OperatorSettings.
DeclareVertexInterface()
template<typename TDataType> FVertexInterface Metasound::SendNodePrivate::TSendOperator< TDataType >::DeclareVertexInterface () inline static
Definition at line 88 of file MetasoundSendNode.h.
References FText::GetEmpty(), GetSendInputName(), METASOUND_GET_PARAM_DISPLAYNAME, and METASOUND_GET_PARAM_NAME.
Referenced by Metasound::TSendNode< TDataType >::DeclareVertexInterface(), and GetNodeInfo().
Execute()
template<typename TDataType> void Metasound::SendNodePrivate::TSendOperator< TDataType >::Execute () inline
Definition at line 67 of file MetasoundSendNode.h.
References CachedSendAddress, check, CreateNewSender(), InputData, ResetSenderAndCleanupChannel(), SendAddress, and Sender.
GetNodeInfo()
template<typename TDataType> const FNodeClassMetadata & Metasound::SendNodePrivate::TSendOperator< TDataType >::GetNodeInfo () inline static
Definition at line 107 of file MetasoundSendNode.h.
References DeclareVertexInterface(), FName, Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), GetSendInputName(), Info, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, Metasound::PluginAuthor, and Metasound::PluginNodeMissingPrompt.
Referenced by Metasound::TSendNode< TDataType >::GetNodeInfo().
GetSendAddressWithDataType()
template<typename TDataType> FSendAddress Metasound::SendNodePrivate::TSendOperator< TDataType >::GetSendAddressWithDataType (const FSendAddress & InAddress) const inline private
Definition at line 159 of file MetasoundSendNode.h.
References Metasound::FSendAddress::GetChannelName(), Metasound::FSendAddress::GetInstanceID(), and Metasound::GetMetasoundDataTypeName().
Referenced by CreateNewSender(), and ResetSenderAndCleanupChannel().
GetSendInputName()
template<typename TDataType> const FVertexName & Metasound::SendNodePrivate::TSendOperator< TDataType >::GetSendInputName () inline static
Definition at line 35 of file MetasoundSendNode.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by BindInputs(), CreateOperator(), DeclareVertexInterface(), GetNodeInfo(), and Metasound::TSendNode< TDataType >::GetSendInputName().
Reset()
template<typename TDataType> void Metasound::SendNodePrivate::TSendOperator< TDataType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 80 of file MetasoundSendNode.h.
References CachedSendAddress, check, CreateNewSender(), ResetSenderAndCleanupChannel(), SendAddress, and Sender.
ResetSenderAndCleanupChannel()
template<typename TDataType> void Metasound::SendNodePrivate::TSendOperator< TDataType >::ResetSenderAndCleanupChannel () inline private
Definition at line 176 of file MetasoundSendNode.h.
References CachedSendAddress, Metasound::FDataTransmissionCenter::Get(), GetSendAddressWithDataType(), Sender, and Metasound::FDataTransmissionCenter::UnregisterDataChannelIfUnconnected().
Referenced by ~TSendOperator(), Execute(), and Reset().
Field Documentation
CachedSendAddress
template<typename TDataType> FSendAddress Metasound::SendNodePrivate::TSendOperator< TDataType >::CachedSendAddress private
Definition at line 184 of file MetasoundSendNode.h.
Referenced by TSendOperator(), Execute(), Reset(), and ResetSenderAndCleanupChannel().
CachedSenderParams
template<typename TDataType> FSenderInitParams Metasound::SendNodePrivate::TSendOperator< TDataType >::CachedSenderParams private
Definition at line 185 of file MetasoundSendNode.h.
Referenced by TSendOperator(), and CreateNewSender().
InputData
template<typename TDataType> TDataReadReference<TDataType> Metasound::SendNodePrivate::TSendOperator< TDataType >::InputData private
Definition at line 182 of file MetasoundSendNode.h.
Referenced by TSendOperator(), BindInputs(), and Execute().
SendAddress
template<typename TDataType> TDataReadReference<FSendAddress> Metasound::SendNodePrivate::TSendOperator< TDataType >::SendAddress private
Definition at line 183 of file MetasoundSendNode.h.
Referenced by TSendOperator(), BindInputs(), CreateNewSender(), Execute(), and Reset().
Sender
template<typename TDataType> TSenderPtr<TDataType> Metasound::SendNodePrivate::TSendOperator< TDataType >::Sender private
Definition at line 187 of file MetasoundSendNode.h.
Referenced by Execute(), Reset(), and ResetSenderAndCleanupChannel().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundSendNode.h