Unreal Engine 5.6 C++ API: TFutureState< ResultType > Class Template Reference
TFutureState< ResultType > Class Template Reference
Implements the internal state of asynchronous return values (futures).
#include "Future.h"
Public Types
using ConstResultType = typename TTypeCompatibleBytes<ResultType>::ConstGetType
using MutableResultType = typename TTypeCompatibleBytes<ResultType>::MutableGetType
using RvalueResultType = typename TTypeCompatibleBytes<ResultType>::RvalueGetType
Public Member Functions
TFutureState ()
Default constructor.
TFutureState (TUniqueFunction< void()> &&CompletionCallback)
Create and initialize a new instance with a callback.
~TFutureState ()
template<typename... ArgTypes>
void EmplaceResult (ArgTypes &&... Args)
Sets the result and notifies any waiting threads.
MutableResultType GetResult ()
Gets the result (will block the calling thread until the result is available).
ConstResultType GetResult () const
Public Member Functions inherited from FFutureState
FFutureState ()=default
Default constructor.
FFutureState (TUniqueFunction< void()> &&InCompletionCallback)
Create and initialize a new instance with a callback.
bool IsComplete () const
Checks whether the asynchronous result has been set.
void SetContinuation (TUniqueFunction< void()> &&Continuation)
Set a continuation to be called on completion of the promise.
bool WaitFor (const FTimespan &Duration) const
Blocks the calling thread until the future result is available.
Private Attributes
TTypeCompatibleBytes< ResultType > Result
Holds the asynchronous result.
Additional Inherited Members
Protected Member Functions inherited from FFutureState
void MarkComplete ()
Notifies any waiting threads that the result is available.
Detailed Description
template<typename ResultType>
class TFutureState< ResultType >
Implements the internal state of asynchronous return values (futures).
Definition at line 145 of file Future.h.
Member Typedef Documentation
ConstResultType
template<typename ResultType> using TFutureState< ResultType >::ConstResultType = typename TTypeCompatibleBytes<ResultType>::ConstGetType
Definition at line 150 of file Future.h.
MutableResultType
template<typename ResultType> using TFutureState< ResultType >::MutableResultType = typename TTypeCompatibleBytes<ResultType>::MutableGetType
Definition at line 149 of file Future.h.
RvalueResultType
template<typename ResultType> using TFutureState< ResultType >::RvalueResultType = typename TTypeCompatibleBytes<ResultType>::RvalueGetType
Definition at line 151 of file Future.h.
Constructor & Destructor Documentation
TFutureState() [1/2]
template<typename ResultType> TFutureState< ResultType >::TFutureState () inline
Default constructor.
Definition at line 154 of file Future.h.
References FFutureState::FFutureState().
Referenced by GetResult().
~TFutureState()
template<typename ResultType> TFutureState< ResultType >::~TFutureState () inline
Definition at line 158 of file Future.h.
References FFutureState::IsComplete(), and Result.
TFutureState() [2/2]
template<typename ResultType> TFutureState< ResultType >::TFutureState (TUniqueFunction< void()> && CompletionCallback) inline
Create and initialize a new instance with a callback.
Parameters
CompletionCallback A function that is called when the state is completed.
Definition at line 171 of file Future.h.
References FFutureState::FFutureState(), FFutureState::CompletionCallback, and MoveTemp().
Member Function Documentation
EmplaceResult()
template<typename ResultType> template<typename... ArgTypes> void TFutureState< ResultType >::EmplaceResult (ArgTypes &&... Args) inline
Sets the result and notifies any waiting threads.
Parameters
Args The arguments to forward to the constructor of the result.
See also
GetResult
Definition at line 204 of file Future.h.
References check, Forward(), FFutureState::IsComplete(), FFutureState::MarkComplete(), and Result.
GetResult() [1/2]
template<typename ResultType> MutableResultType TFutureState< ResultType >::GetResult () inline
Gets the result (will block the calling thread until the result is available).
Returns
The result value.
See also
EmplaceResult
Definition at line 183 of file Future.h.
References FFutureState::IsComplete(), FTimespan::MaxValue(), Result, and FFutureState::WaitFor().
Referenced by GetResult().
GetResult() [2/2]
template<typename ResultType> ConstResultType TFutureState< ResultType >::GetResult () const inline
Definition at line 192 of file Future.h.
References TFutureState(), and GetResult().
Field Documentation
Result
template<typename ResultType> TTypeCompatibleBytes<ResultType> TFutureState< ResultType >::Result private
Holds the asynchronous result.
Definition at line 214 of file Future.h.
Referenced by ~TFutureState(), EmplaceResult(), and GetResult().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/Future.h