Unreal Engine 5.6 C++ API: FSlateLayoutTransform Class Reference
FSlateLayoutTransform Class Reference
Represents a 2D transformation in the following order: scale then translate.
#include "SlateLayoutTransform.h"
Public Member Functions
FSlateLayoutTransform (const UE::Slate::FDeprecateVector2DParameter &InTranslation)
FSlateLayoutTransform (float InScale, const UE::Slate::FDeprecateVector2DParameter &InTranslation)
Ctor from a scale followed by translate.
FSlateLayoutTransform (float InScale=1.0f)
FSlateLayoutTransform Concatenate (const FSlateLayoutTransform &RHS) const
This works by transforming the origin through LHS then RHS.
float GetScale () const
Access to the scale.
UE::Slate::FDeprecateVector2DResult GetTranslation () const
Access to the 2D translation.
FSlateLayoutTransform Inverse () const
Invert the transform/scale.
bool operator!= (const FSlateLayoutTransform &Other) const
Inequality.
bool operator== (const FSlateLayoutTransform &Other) const
Equality.
FMatrix ToMatrix () const
Support for converting to an FMatrix.
FORCEINLINE UE::Slate::FDeprecateVector2DResult TransformPoint (const UE::Slate::FDeprecateVector2DParameter &Point) const
FORCEINLINE UE::Slate::FDeprecateVector2DResult TransformVector (const UE::Slate::FDeprecateVector2DParameter &Vector) const
Private Attributes
float Scale
FVector2f Translation
Detailed Description
Represents a 2D transformation in the following order: scale then translate.
Used by FGeometry for it's layout transformations.
Matrix form looks like: [Vx Vy 1] * [ S 0 0 ] [ 0 S 0 ] [ Tx Ty 1 ]
Definition at line 19 of file SlateLayoutTransform.h.
Constructor & Destructor Documentation
FSlateLayoutTransform() [1/3]
FSlateLayoutTransform::FSlateLayoutTransform (float InScale = 1.0f) inline
Definition at line 22 of file SlateLayoutTransform.h.
References ForceInit, Scale, and Translation.
Referenced by Concatenate(), Inverse(), operator!=(), and operator==().
FSlateLayoutTransform() [2/3]
FSlateLayoutTransform::FSlateLayoutTransform (float InScale, const UE::Slate::FDeprecateVector2DParameter & InTranslation) inline explicit
Ctor from a scale followed by translate.
Shortcut to Concatenate(InScale, InTranslation).
Definition at line 29 of file SlateLayoutTransform.h.
References Scale, and Translation.
FSlateLayoutTransform() [3/3]
FSlateLayoutTransform::FSlateLayoutTransform (const UE::Slate::FDeprecateVector2DParameter & InTranslation) inline explicit
Definition at line 35 of file SlateLayoutTransform.h.
References Scale, and Translation.
Member Function Documentation
Concatenate()
FSlateLayoutTransform FSlateLayoutTransform::Concatenate (const FSlateLayoutTransform & RHS) const inline
This works by transforming the origin through LHS then RHS.
In matrix form, looks like this: [ Sa 0 0 ] [ Sb 0 0 ] [ 0 Sa 0 ] * [ 0 Sb 0 ] [ Tax Tay 1 ] [ Tbx Tby 1 ]
Definition at line 78 of file SlateLayoutTransform.h.
References FSlateLayoutTransform(), Concatenate(), Scale, TransformPoint(), and Translation.
Referenced by Concatenate().
GetScale()
float FSlateLayoutTransform::GetScale () const inline
Access to the scale.
Definition at line 48 of file SlateLayoutTransform.h.
References Scale.
Referenced by FPaintGeometry::AppendTransform(), ToMatrix(), and USTRUCT().
GetTranslation()
UE::Slate::FDeprecateVector2DResult FSlateLayoutTransform::GetTranslation () const inline
Access to the 2D translation.
Definition at line 42 of file SlateLayoutTransform.h.
References Translation.
Referenced by USTRUCT().
Inverse()
FSlateLayoutTransform FSlateLayoutTransform::Inverse () const inline
Invert the transform/scale.
Definition at line 86 of file SlateLayoutTransform.h.
References FSlateLayoutTransform(), Inverse(), Scale, and Translation.
Referenced by Inverse().
operator!=()
bool FSlateLayoutTransform::operator!= (const FSlateLayoutTransform & Other) const inline
Inequality.
Definition at line 98 of file SlateLayoutTransform.h.
References FSlateLayoutTransform(), operator==(), and Other.
operator==()
bool FSlateLayoutTransform::operator== (const FSlateLayoutTransform & Other) const inline
Equality.
Definition at line 92 of file SlateLayoutTransform.h.
References FSlateLayoutTransform(), Other, Scale, and Translation.
Referenced by operator!=().
ToMatrix()
FMatrix FSlateLayoutTransform::ToMatrix () const inline
Support for converting to an FMatrix.
Definition at line 54 of file SlateLayoutTransform.h.
References FVector, GetScale(), Matrix, and Translation.
TransformPoint()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateLayoutTransform::TransformPoint (const UE::Slate::FDeprecateVector2DParameter & Point) const inline
Definition at line 61 of file SlateLayoutTransform.h.
References FORCEINLINE, Point, Scale, TransformPoint(), and Translation.
Referenced by Concatenate(), and TransformPoint().
TransformVector()
FORCEINLINE UE::Slate::FDeprecateVector2DResult FSlateLayoutTransform::TransformVector (const UE::Slate::FDeprecateVector2DParameter & Vector) const inline
Definition at line 66 of file SlateLayoutTransform.h.
References FORCEINLINE, Scale, TransformVector(), Translation, and Vector.
Referenced by TransformVector().
Field Documentation
Scale
float FSlateLayoutTransform::Scale private
Definition at line 104 of file SlateLayoutTransform.h.
Referenced by FSlateLayoutTransform(), FSlateLayoutTransform(), FSlateLayoutTransform(), Concatenate(), GetScale(), Inverse(), operator==(), TransformPoint(), and TransformVector().
Translation
FVector2f FSlateLayoutTransform::Translation private
Definition at line 105 of file SlateLayoutTransform.h.
Referenced by FSlateLayoutTransform(), FSlateLayoutTransform(), FSlateLayoutTransform(), Concatenate(), GetTranslation(), Inverse(), operator==(), ToMatrix(), TransformPoint(), and TransformVector().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Rendering/SlateLayoutTransform.h