Unreal Engine 5.6 C++ API: FPSOCollectorCreateManager Class Reference
FPSOCollectorCreateManager Class Reference
Manages all create functions of the globally defined IPSOCollectors.
#include "PSOPrecacheMaterial.h"
Data Structures
struct FPSOCollectorData
Static Public Member Functions
static PSOCollectorCreateFunction GetCreateFunction (EShadingPath ShadingPath, int32 Index)
static int32 GetIndex (EShadingPath ShadingPath, const TCHAR *Name)
static const TCHAR * GetName (EShadingPath ShadingPath, int32 Index)
static int32 GetPSOCollectorCount (EShadingPath ShadingPath)
Static Public Attributes
static constexpr uint32 MaxPSOCollectorCount = 64
Static Private Attributes
static int32 PSOCollectorCount [(uint32) EShadingPath::Num] = {0,0}
static FPSOCollectorData PSOCollectors [(uint32) EShadingPath::Num][MaxPSOCollectorCount]
Friends
class FRegisterPSOCollectorCreateFunction
Detailed Description
Manages all create functions of the globally defined IPSOCollectors.
Definition at line 53 of file PSOPrecacheMaterial.h.
Member Function Documentation
GetCreateFunction()
PSOCollectorCreateFunction FPSOCollectorCreateManager::GetCreateFunction (EShadingPath ShadingPath, int32 Index) inline static
Definition at line 59 of file PSOPrecacheMaterial.h.
References check, MaxPSOCollectorCount, and PSOCollectors.
GetIndex()
int32 FPSOCollectorCreateManager::GetIndex (EShadingPath ShadingPath, const TCHAR * Name) static
References Name.
GetName()
const TCHAR * FPSOCollectorCreateManager::GetName (EShadingPath ShadingPath, int32 Index) inline static
Definition at line 65 of file PSOPrecacheMaterial.h.
References check, INDEX_NONE, MaxPSOCollectorCount, PSOCollectors, and TEXT.
GetPSOCollectorCount()
int32 FPSOCollectorCreateManager::GetPSOCollectorCount (EShadingPath ShadingPath) inline static
Definition at line 58 of file PSOPrecacheMaterial.h.
References PSOCollectorCount.
Friends And Related Symbol Documentation
FRegisterPSOCollectorCreateFunction
friend class FRegisterPSOCollectorCreateFunction friend
Definition at line 89 of file PSOPrecacheMaterial.h.
References FRegisterPSOCollectorCreateFunction.
Referenced by FRegisterPSOCollectorCreateFunction.
Field Documentation
MaxPSOCollectorCount
uint32 FPSOCollectorCreateManager::MaxPSOCollectorCount = 64 static constexpr
Definition at line 56 of file PSOPrecacheMaterial.h.
Referenced by FRegisterPSOCollectorCreateFunction::FRegisterPSOCollectorCreateFunction(), GetCreateFunction(), and GetName().
PSOCollectorCount
int32 FPSOCollectorCreateManager::PSOCollectorCount[(uint32) EShadingPath::Num] = {0,0} inline static private
Definition at line 80 of file PSOPrecacheMaterial.h.
Referenced by FRegisterPSOCollectorCreateFunction::FRegisterPSOCollectorCreateFunction(), and GetPSOCollectorCount().
PSOCollectors
FPSOCollectorData FPSOCollectorCreateManager::PSOCollectors[(uint32) EShadingPath::Num][MaxPSOCollectorCount] static private
Definition at line 87 of file PSOPrecacheMaterial.h.
Referenced by FRegisterPSOCollectorCreateFunction::FRegisterPSOCollectorCreateFunction(), FRegisterPSOCollectorCreateFunction::~FRegisterPSOCollectorCreateFunction(), GetCreateFunction(), and GetName().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/PSOPrecacheMaterial.h