Unreal Engine 5.6 C++ API: UE::Geometry::TPolygon2< T >::SegmentIterator Class Reference
UE::Geometry::TPolygon2< T >::SegmentIterator Class Reference
SegmentIterator is used to iterate over the TSegment2<T> segments of the polygon.
#include "Polygon2.h"
Public Member Functions
bool operator! ()
bool operator!= (const SegmentIterator &i2) const
TSegment2< T > operator* () const
SegmentIterator & operator++ ()
SegmentIterator operator++ (int)
bool operator== (const SegmentIterator &i2) const
Protected Member Functions
SegmentIterator (const TPolygon2 *p, int iCur)
Protected Attributes
int i
const TPolygon2 * polygon
Friends
class TPolygon2
Detailed Description
template<typename T>
class UE::Geometry::TPolygon2< T >::SegmentIterator
SegmentIterator is used to iterate over the TSegment2<T> segments of the polygon.
Definition at line 206 of file Polygon2.h.
Constructor & Destructor Documentation
SegmentIterator()
template<typename T> UE::Geometry::TPolygon2< T >::SegmentIterator::SegmentIterator (const TPolygon2 * p, int iCur) inline protected
Definition at line 235 of file Polygon2.h.
References i, polygon, and TPolygon2.
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
operator!()
template<typename T> bool UE::Geometry::TPolygon2< T >::SegmentIterator::operator! () inline
Definition at line 209 of file Polygon2.h.
References i, and polygon.
operator!=()
template<typename T> bool UE::Geometry::TPolygon2< T >::SegmentIterator::operator!= (const SegmentIterator & i2) const inline
Definition at line 231 of file Polygon2.h.
References SegmentIterator(), i, and polygon.
operator*()
template<typename T> TSegment2< T > UE::Geometry::TPolygon2< T >::SegmentIterator::operator* () const inline
Definition at line 213 of file Polygon2.h.
References check, i, polygon, and UE::Geometry::TPolygon2< T >::VertexCount().
operator++() [1/2]
template<typename T> SegmentIterator & UE::Geometry::TPolygon2< T >::SegmentIterator::operator++ () inline
Definition at line 219 of file Polygon2.h.
References SegmentIterator(), and i.
operator++() [2/2]
template<typename T> SegmentIterator UE::Geometry::TPolygon2< T >::SegmentIterator::operator++ (int) inline
Definition at line 224 of file Polygon2.h.
References SegmentIterator(), and i.
operator==()
template<typename T> bool UE::Geometry::TPolygon2< T >::SegmentIterator::operator== (const SegmentIterator & i2) const inline
Definition at line 230 of file Polygon2.h.
References SegmentIterator(), i, and polygon.
Friends And Related Symbol Documentation
TPolygon2
template<typename T> friend class TPolygon2 friend
Definition at line 236 of file Polygon2.h.
References TPolygon2.
Referenced by SegmentIterator(), and TPolygon2.
Field Documentation
i
template<typename T> int UE::Geometry::TPolygon2< T >::SegmentIterator::i protected
Definition at line 234 of file Polygon2.h.
Referenced by SegmentIterator(), operator!(), operator!=(), operator*(), operator++(), operator++(), and operator==().
polygon
template<typename T> const TPolygon2* UE::Geometry::TPolygon2< T >::SegmentIterator::polygon protected
Definition at line 233 of file Polygon2.h.
Referenced by SegmentIterator(), operator!(), operator!=(), operator*(), and operator==().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Polygon2.h