Unreal Engine 5.6 C++ API: TraceServices::FEnumerateAsyncTask< InEventType, SettingsType > Class Template Reference
TraceServices::FEnumerateAsyncTask< InEventType, SettingsType > Class Template Reference
#include "AsyncEnumerateTask.h"
Public Member Functions
FEnumerateAsyncTask (const FAsyncEnumerateTaskData< InEventType, SettingsType > &InData)
void DoWork ()
void EnumerateOrderedByEndTime ()
void EnumerateOrderedByStartTime ()
FORCEINLINE TStatId GetStatId () const
Public Member Functions inherited from FNonAbandonableTask
void Abandon ()
bool CanAbandon ()
Data Fields
FAsyncEnumerateTaskData< InEventType, SettingsType > Data
Private Types
using EventType = InEventType
Friends
class FAsyncTask< FEnumerateAsyncTask >
Detailed Description
template<typename InEventType, typename SettingsType>
class TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >
Definition at line 190 of file AsyncEnumerateTask.h.
Member Typedef Documentation
EventType
template<typename InEventType, typename SettingsType> using TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EventType = InEventType private
Definition at line 192 of file AsyncEnumerateTask.h.
Constructor & Destructor Documentation
FEnumerateAsyncTask()
template<typename InEventType, typename SettingsType> TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::FEnumerateAsyncTask (const FAsyncEnumerateTaskData< InEventType, SettingsType > & InData) inline
Definition at line 197 of file AsyncEnumerateTask.h.
References Data.
Member Function Documentation
DoWork()
template<typename InEventType, typename SettingsType> void TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::DoWork () inline
Definition at line 314 of file AsyncEnumerateTask.h.
References TraceServices::ByEndTime, TraceServices::ByStartTime, Data, TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::EnumerateEventsDownSampled(), EnumerateOrderedByEndTime(), EnumerateOrderedByStartTime(), Event, and Time.
EnumerateOrderedByEndTime()
template<typename InEventType, typename SettingsType> void TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByEndTime () inline
Definition at line 274 of file AsyncEnumerateTask.h.
References TraceServices::Continue, Data, TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::EnumerateEventsDownSampled(), Event, TraceServices::Stop, and Time.
Referenced by DoWork().
EnumerateOrderedByStartTime()
template<typename InEventType, typename SettingsType> void TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::EnumerateOrderedByStartTime () inline
Definition at line 202 of file AsyncEnumerateTask.h.
References TArray< InElementType, InAllocatorType >::AddDefaulted_GetRef(), check, TraceServices::Continue, Data, Depth, TraceServices::EnumerateAsyncAlgoritm< InEventType, SettingsType >::EnumerateEventsDownSampled(), Event, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::Num(), TraceServices::Stop, and Time.
Referenced by DoWork().
GetStatId()
template<typename InEventType, typename SettingsType> FORCEINLINE TStatId TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::GetStatId () const inline
Definition at line 340 of file AsyncEnumerateTask.h.
References FORCEINLINE, and RETURN_QUICK_DECLARE_CYCLE_STAT.
Friends And Related Symbol Documentation
FAsyncTask< FEnumerateAsyncTask >
template<typename InEventType, typename SettingsType> friend class FAsyncTask< FEnumerateAsyncTask > friend
Definition at line 36 of file AsyncEnumerateTask.h.
Field Documentation
Data
template<typename InEventType, typename SettingsType> FAsyncEnumerateTaskData<InEventType, SettingsType> TraceServices::FEnumerateAsyncTask< InEventType, SettingsType >::Data
Definition at line 345 of file AsyncEnumerateTask.h.
Referenced by FEnumerateAsyncTask(), DoWork(), EnumerateOrderedByEndTime(), and EnumerateOrderedByStartTime().
The documentation for this class was generated from the following file:
Developer/TraceServices/Public/Model/AsyncEnumerateTask.h