Unreal Engine 5.6 C++ API: TFilePackageStoreEntryCArrayView< T > Class Template Reference
TFilePackageStoreEntryCArrayView< T > Class Template Reference
Package store entry array view.
#include "IoContainerHeader.h"
Public Member Functions
T * begin ()
const T * begin () const
T * Data ()
const T * Data () const
T * end ()
const T * end () const
uint32 Num () const
T & operator[] (uint32 Index)
const T & operator[] (uint32 Index) const
Private Attributes
const uint32 ArrayNum = 0
const uint32 OffsetToDataFromThis = 0
Detailed Description
template<typename T>
class TFilePackageStoreEntryCArrayView< T >
Package store entry array view.
Definition at line 19 of file IoContainerHeader.h.
Member Function Documentation
begin() [1/2]
template<typename T> T * TFilePackageStoreEntryCArrayView< T >::begin () inline
Definition at line 31 of file IoContainerHeader.h.
References Data().
begin() [2/2]
template<typename T> const T * TFilePackageStoreEntryCArrayView< T >::begin () const inline
Definition at line 30 of file IoContainerHeader.h.
References Data().
Data() [1/2]
template<typename T> T * TFilePackageStoreEntryCArrayView< T >::Data () inline
Definition at line 28 of file IoContainerHeader.h.
References OffsetToDataFromThis.
Data() [2/2]
template<typename T> const T * TFilePackageStoreEntryCArrayView< T >::Data () const inline
Definition at line 27 of file IoContainerHeader.h.
References OffsetToDataFromThis.
Referenced by begin(), begin(), end(), end(), operator[](), and operator[]().
end() [1/2]
template<typename T> T * TFilePackageStoreEntryCArrayView< T >::end () inline
Definition at line 34 of file IoContainerHeader.h.
References ArrayNum, and Data().
end() [2/2]
template<typename T> const T * TFilePackageStoreEntryCArrayView< T >::end () const inline
Definition at line 33 of file IoContainerHeader.h.
References ArrayNum, and Data().
Num()
template<typename T> uint32 TFilePackageStoreEntryCArrayView< T >::Num () const inline
Definition at line 25 of file IoContainerHeader.h.
References ArrayNum.
operator[]() [1/2]
template<typename T> T & TFilePackageStoreEntryCArrayView< T >::operator[] (uint32 Index) inline
Definition at line 37 of file IoContainerHeader.h.
References Data().
operator[]() [2/2]
template<typename T> const T & TFilePackageStoreEntryCArrayView< T >::operator[] (uint32 Index) const inline
Definition at line 36 of file IoContainerHeader.h.
References Data().
Field Documentation
ArrayNum
template<typename T> const uint32 TFilePackageStoreEntryCArrayView< T >::ArrayNum = 0 private
Definition at line 21 of file IoContainerHeader.h.
Referenced by end(), end(), and Num().
OffsetToDataFromThis
template<typename T> const uint32 TFilePackageStoreEntryCArrayView< T >::OffsetToDataFromThis = 0 private
Definition at line 22 of file IoContainerHeader.h.
Referenced by Data(), and Data().
The documentation for this class was generated from the following file:
Runtime/Core/Public/IO/IoContainerHeader.h