Unreal Engine 5.6 C++ API: FPopupMethodReply Class Reference
FPopupMethodReply Class Reference
Reply informs Slate how it should express the popup: by creating a new window or by reusing the existing window.
#include "PopupMethodReply.h"
Public Member Functions
FPopupMethodReply ()
EPopupMethod GetPopupMethod () const
Which method to use for the popup: new window or reuse current window.
EShouldThrottle GetShouldThrottle () const
Should we throttle the engine?
bool IsSet () const
Alias for IsEventHandled for situations where this is used as optional.
FPopupMethodReply & SetShouldThrottle (EShouldThrottle InShouldThrottle)
Specify whether we should throttle the engine ticking s.t.
Public Member Functions inherited from TReplyBase< FPopupMethodReply >
TReplyBase (bool bIsHandled)
Public Member Functions inherited from FReplyBase
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately handled the event.
bool IsEventHandled () const
Static Public Member Functions
static FPopupMethodReply Unhandled ()
Create a reply that signals not having an opinion about the popup method.
static FPopupMethodReply UseMethod (EPopupMethod WithMethod)
Create a reply that specifies how a popup should be handled.
Private Member Functions
FPopupMethodReply (bool bIsHandled, EPopupMethod InMethod)
Private Attributes
EPopupMethod PopupMethod
EShouldThrottle ShouldThrottle
Additional Inherited Members
Protected Member Functions inherited from TReplyBase< FPopupMethodReply >
FPopupMethodReply & Me ()
FPopupMethodReply & SetHandler (const TSharedRef< SWidget > &InHandler)
Set the widget that handled the event; undefined if never handled.
Protected Member Functions inherited from FReplyBase
FReplyBase (bool InIsHandled)
A reply can be handled or unhandled.
Protected Attributes inherited from FReplyBase
bool bIsHandled
Has a widget handled an event.
TSharedPtr< SWidget > EventHandler
Widget that handled the event that generated this reply.
Detailed Description
Reply informs Slate how it should express the popup: by creating a new window or by reusing the existing window.
Definition at line 23 of file PopupMethodReply.h.
Constructor & Destructor Documentation
FPopupMethodReply() [1/2]
FPopupMethodReply::FPopupMethodReply () inline
Definition at line 65 of file PopupMethodReply.h.
References FPopupMethodReply(), TReplyBase< FPopupMethodReply >::TReplyBase(), CreateNewWindow, PopupMethod, ShouldThrottle, and Yes.
Referenced by FPopupMethodReply(), FPopupMethodReply(), SetShouldThrottle(), Unhandled(), and UseMethod().
FPopupMethodReply() [2/2]
FPopupMethodReply::FPopupMethodReply (bool bIsHandled, EPopupMethod InMethod) inline private
Definition at line 72 of file PopupMethodReply.h.
References FPopupMethodReply(), TReplyBase< FPopupMethodReply >::TReplyBase(), FReplyBase::bIsHandled, PopupMethod, ShouldThrottle, and Yes.
Member Function Documentation
GetPopupMethod()
EPopupMethod FPopupMethodReply::GetPopupMethod () const inline
Which method to use for the popup: new window or reuse current window.
Definition at line 52 of file PopupMethodReply.h.
References PopupMethod.
GetShouldThrottle()
EShouldThrottle FPopupMethodReply::GetShouldThrottle () const inline
Should we throttle the engine?
Definition at line 46 of file PopupMethodReply.h.
References ShouldThrottle.
IsSet()
bool FPopupMethodReply::IsSet () const inline
Alias for IsEventHandled for situations where this is used as optional.
Definition at line 58 of file PopupMethodReply.h.
References FReplyBase::IsEventHandled().
SetShouldThrottle()
FPopupMethodReply & FPopupMethodReply::SetShouldThrottle (EShouldThrottle InShouldThrottle) inline
Specify whether we should throttle the engine ticking s.t.
the UI is most responsive when this popup is up.
Definition at line 39 of file PopupMethodReply.h.
References FPopupMethodReply(), TReplyBase< FPopupMethodReply >::Me(), and ShouldThrottle.
Unhandled()
FPopupMethodReply FPopupMethodReply::Unhandled () inline static
Create a reply that signals not having an opinion about the popup method.
Definition at line 27 of file PopupMethodReply.h.
References FPopupMethodReply(), and CreateNewWindow.
Referenced by ISlateViewport::OnQueryPopupMethod().
UseMethod()
FPopupMethodReply FPopupMethodReply::UseMethod (EPopupMethod WithMethod) inline static
Create a reply that specifies how a popup should be handled.
Definition at line 33 of file PopupMethodReply.h.
References FPopupMethodReply().
Field Documentation
PopupMethod
EPopupMethod FPopupMethodReply::PopupMethod private
Definition at line 79 of file PopupMethodReply.h.
Referenced by FPopupMethodReply(), FPopupMethodReply(), and GetPopupMethod().
ShouldThrottle
EShouldThrottle FPopupMethodReply::ShouldThrottle private
Definition at line 80 of file PopupMethodReply.h.
Referenced by FPopupMethodReply(), FPopupMethodReply(), GetShouldThrottle(), and SetShouldThrottle().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/PopupMethodReply.h