Unreal Engine 5.6 C++ API: UE::CurveEditor::TInvertedCurveModel< TBase > Class Template Reference
UE::CurveEditor::TInvertedCurveModel< TBase > Class Template Reference
#include "InvertedCurveModel.h"
Public Member Functions
template<typename... TArg>
requires std::is_base_of_v<FCurveModel, TBase>
TInvertedCurveModel (TArg &&... Arg)
virtual void AddKeys (TArrayView< const FKeyPosition > InPositions, TArrayView< const FKeyAttributes > InAttributes, TArrayView< TOptional< FKeyHandle > > *OutKeyHandles=nullptr) override
virtual TUniquePtr< IBufferedCurveModel > CreateBufferedCurveCopy () const override
virtual void DrawCurve (const FCurveEditor &CurveEditor, const FCurveEditorScreenSpace &ScreenSpace, TArray< TTuple< double, double > > &InterpolatingPoints) const override
virtual bool Evaluate (double InTime, double &OutValue) const override
virtual void GetKeyAttributes (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyAttributes > OutAttributes) const override
virtual void GetKeyAttributesExcludingAutoComputed (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyAttributes > OutAttributes) const override
virtual void GetKeyAttributesIncludingAutoComputed (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyAttributes > OutAttributes) const override
virtual void GetKeyDrawInfo (ECurvePointType PointType, const FKeyHandle InKeyHandle, FKeyDrawInfo &OutDrawInfo) const override
virtual void GetKeyPositions (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyPosition > OutKeyPositions) const override
virtual void GetKeys (double MinTime, double MaxTime, double MinValue, double MaxValue, TArray< FKeyHandle > &OutKeyHandles) const override
virtual void GetValueRange (double &MinValue, double &MaxValue) const override
virtual void SetKeyAttributes (TArrayView< const FKeyHandle > InKeys, TArrayView< const FKeyAttributes > InAttributes, EPropertyChangeType::Type ChangeType=EPropertyChangeType::Unspecified) override
virtual void SetKeyPositions (TArrayView< const FKeyHandle > InKeys, TArrayView< const FKeyPosition > InKeyPositions, EPropertyChangeType::Type ChangeType=EPropertyChangeType::Unspecified) override
Detailed Description
template<typename TBase>
requires std::is_base_of_v<FCurveModel, TBase>
class UE::CurveEditor::TInvertedCurveModel< TBase >
Definition at line 11 of file InvertedCurveModel.h.
Constructor & Destructor Documentation
TInvertedCurveModel()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> template<typename ... TArg> requires std::is_base_of_v<FCurveModel, TBase> UE::CurveEditor::TInvertedCurveModel< TBase >::TInvertedCurveModel (TArg &&... Arg) explicit
Definition at line 115 of file InvertedCurveModel.h.
References Forward().
Member Function Documentation
AddKeys()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::AddKeys (TArrayView< const FKeyPosition > InPositions, TArrayView< const FKeyAttributes > InAttributes, TArrayView< TOptional< FKeyHandle > > * OutKeyHandles = nullptr) override virtual
Definition at line 140 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyAttributes(), and UE::CurveEditor::Private::InvertKeyPositions().
CreateBufferedCurveCopy()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> TUniquePtr< IBufferedCurveModel > UE::CurveEditor::TInvertedCurveModel< TBase >::CreateBufferedCurveCopy () const override virtual
Definition at line 226 of file InvertedCurveModel.h.
DrawCurve()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::DrawCurve (const FCurveEditor & CurveEditor, const FCurveEditorScreenSpace & ScreenSpace, TArray< TTuple< double, double > > & InterpolatingPoints) const override virtual
Definition at line 120 of file InvertedCurveModel.h.
Evaluate()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> bool UE::CurveEditor::TInvertedCurveModel< TBase >::Evaluate (double InTime, double & OutValue) const override virtual
Definition at line 184 of file InvertedCurveModel.h.
References InTime.
GetKeyAttributes()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyAttributes (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyAttributes > OutAttributes) const override virtual
Definition at line 195 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyAttributes().
GetKeyAttributesExcludingAutoComputed()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyAttributesExcludingAutoComputed (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyAttributes > OutAttributes) const override virtual
Definition at line 209 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyAttributes().
GetKeyAttributesIncludingAutoComputed()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyAttributesIncludingAutoComputed (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyAttributes > OutAttributes) const override virtual
Definition at line 202 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyAttributes().
GetKeyDrawInfo()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyDrawInfo (ECurvePointType PointType, const FKeyHandle InKeyHandle, FKeyDrawInfo & OutDrawInfo) const override virtual
Definition at line 169 of file InvertedCurveModel.h.
GetKeyPositions()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeyPositions (TArrayView< const FKeyHandle > InKeys, TArrayView< FKeyPosition > OutKeyPositions) const override virtual
Definition at line 152 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyPositions().
GetKeys()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetKeys (double MinTime, double MaxTime, double MinValue, double MaxValue, TArray< FKeyHandle > & OutKeyHandles) const override virtual
Definition at line 132 of file InvertedCurveModel.h.
References FMath::Max, and FMath::Min.
GetValueRange()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::GetValueRange (double & MinValue, double & MaxValue) const override virtual
Definition at line 175 of file InvertedCurveModel.h.
References FMath::Max, and FMath::Min.
SetKeyAttributes()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::SetKeyAttributes (TArrayView< const FKeyHandle > InKeys, TArrayView< const FKeyAttributes > InAttributes, EPropertyChangeType::Type ChangeType = EPropertyChangeType::Unspecified) override virtual
Definition at line 216 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyAttributes().
SetKeyPositions()
template<typename TBase> requires std::is_base_of_v<FCurveModel, TBase> void UE::CurveEditor::TInvertedCurveModel< TBase >::SetKeyPositions (TArrayView< const FKeyHandle > InKeys, TArrayView< const FKeyPosition > InKeyPositions, EPropertyChangeType::Type ChangeType = EPropertyChangeType::Unspecified) override virtual
Definition at line 159 of file InvertedCurveModel.h.
References UE::CurveEditor::Private::InvertKeyPositions().
The documentation for this class was generated from the following file:
Editor/CurveEditor/Public/InvertedCurveModel.h