Unreal Engine 5.6 C++ API: FGroomBindingAsyncBuildWorker Class Reference
FGroomBindingAsyncBuildWorker Class Reference
Worker used to perform async compilation.
#include "GroomBindingAsset.h"
Public Member Functions
FGroomBindingAsyncBuildWorker (UGroomBindingAsset *InGroomBinding, FGroomBindingBuildContext &&InBuildContext)
Initialization constructor.
void DoWork ()
TStatId GetStatId () const
Public Member Functions inherited from FNonAbandonableTask
void Abandon ()
bool CanAbandon ()
Data Fields
TOptional< FGroomBindingBuildContext > BuildContext
UGroomBindingAsset * GroomBinding
Detailed Description
Worker used to perform async compilation.
Definition at line 141 of file GroomBindingAsset.h.
Constructor & Destructor Documentation
FGroomBindingAsyncBuildWorker()
FGroomBindingAsyncBuildWorker::FGroomBindingAsyncBuildWorker (UGroomBindingAsset * InGroomBinding, FGroomBindingBuildContext && InBuildContext) inline
Initialization constructor.
Definition at line 148 of file GroomBindingAsset.h.
References BuildContext, GroomBinding, and MoveTemp().
Referenced by GetStatId().
Member Function Documentation
DoWork()
void FGroomBindingAsyncBuildWorker::DoWork ()
GetStatId()
TStatId FGroomBindingAsyncBuildWorker::GetStatId () const inline
Definition at line 156 of file GroomBindingAsset.h.
References FGroomBindingAsyncBuildWorker(), FORCEINLINE, and RETURN_QUICK_DECLARE_CYCLE_STAT.
Field Documentation
BuildContext
TOptional<FGroomBindingBuildContext> FGroomBindingAsyncBuildWorker::BuildContext
Definition at line 145 of file GroomBindingAsset.h.
Referenced by FGroomBindingAsyncBuildWorker().
GroomBinding
UGroomBindingAsset* FGroomBindingAsyncBuildWorker::GroomBinding
Definition at line 144 of file GroomBindingAsset.h.
Referenced by FGroomBindingAsyncBuildWorker().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/GroomBindingAsset.h