Unreal Engine 5.6 C++ API: TScriptInterface< InInterfaceType > Class Template Reference
TScriptInterface< InInterfaceType > Class Template Reference
Templated version of FScriptInterface, which provides accessors and operators for referencing the interface portion of an object implementing an interface.
#include "ScriptInterface.h"
Public Types
using InterfaceType = InInterfaceType
using UObjectType = TCopyQualifiersFromTo_T<InterfaceType, UObject>
Public Member Functions
TScriptInterface ()=default
Default constructor.
TScriptInterface (const TScriptInterface &)=default
Copyable.
template<typename OtherInterfaceType UE_REQUIRES>
FORCEINLINE TScriptInterface (const TScriptInterface< OtherInterfaceType > &Other)
Construction from another script interface of a compatible interface type.
template<typename ObjectType>
TScriptInterface (TObjectPtr< ObjectType > SourceObject)
Assignment from an object type that may natively implement InterfaceType.
TScriptInterface (TYPE_OF_NULLPTR)
Construction from nullptr.
template<typename U UE_REQUIRES>
FORCEINLINE TScriptInterface (U &&Source)
Construction from an object type that may natively implement InterfaceType.
FORCEINLINE InInterfaceType * GetInterface () const
Returns the pointer to the interface.
FORCEINLINE UObjectType * GetObject () const
Returns the ObjectPointer contained by this TScriptInterface.
FORCEINLINE TObjectPtr< UObjectType > & GetObjectRef ()
Returns the ObjectPointer contained by this TScriptInterface.
FORCEINLINE operator bool () const
Boolean operator, returns true if this object natively implements InterfaceType.
template<typename OtherInterface UE_REQUIRES>
FORCEINLINE bool operator!= (const OtherInterface *Other) const
FORCEINLINE bool operator!= (const TScriptInterface &Other) const
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
FORCEINLINE InInterfaceType & operator* () const
Dereference operator.
FORCEINLINE InInterfaceType * operator-> () const
Member access operator.
TScriptInterface & operator= (const TScriptInterface &)=default
template<typename OtherInterfaceType UE_REQUIRES>
TScriptInterface & operator= (const TScriptInterface< OtherInterfaceType > &Other)
Assignment from another script interface of a compatible interface type.
template<typename ObjectType>
TScriptInterface & operator= (TObjectPtr< ObjectType > SourceObject)
Assignment from an object type that may natively implement InterfaceType.
TScriptInterface & operator= (TYPE_OF_NULLPTR)
Assignment from nullptr.
template<typename U UE_REQUIRES>
TScriptInterface & operator= (U &&Source)
Assignment from an object type that may natively implement InterfaceType.
template<typename OtherInterface UE_REQUIRES>
FORCEINLINE bool operator== (const OtherInterface *Other) const
Comparison operator, taking a pointer to InterfaceType.
FORCEINLINE bool operator== (const TScriptInterface &Other) const
Comparison operator, taking a reference to another TScriptInterface.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
Comparison operator, taking a nullptr.
FORCEINLINE void SetInterface (InInterfaceType *InInterfacePointer)
Sets the value of the InterfacePointer for this TScriptInterface.
FORCEINLINE void SetObject (UObjectType *InObjectPointer)
Sets the value of the ObjectPointer for this TScriptInterface.
Public Member Functions inherited from FScriptInterface
FScriptInterface ()=default
Default constructor.
FScriptInterface (const FScriptInterface &)=default
Copyable.
FScriptInterface (UObject *InObjectPointer, void *InInterfacePointer)
Construction from object and interface.
void AddReferencedObjects (FReferenceCollector &Collector)
FORCEINLINE void * GetInterface () const
Returns the pointer to the native interface if it is valid.
FORCEINLINE UObject * GetObject () const
Returns the ObjectPointer contained by this FScriptInterface.
FORCEINLINE TObjectPtr< UObject > & GetObjectRef ()
Returns the ObjectPointer contained by this FScriptInterface.
FORCEINLINE bool operator!= (const FScriptInterface &Other) const
FScriptInterface & operator= (const FScriptInterface &)=default
FORCEINLINE bool operator== (const FScriptInterface &Other) const
Comparison operator, taking a reference to another FScriptInterface.
FORCEINLINE void SetInterface (void *InInterfacePointer)
Sets the value of the InterfacePointer for this FScriptInterface.
FORCEINLINE void SetObject (UObject *InObjectPointer)
Sets the value of the ObjectPointer for this FScriptInterface.
Friends
FArchive & operator<< (FArchive &Ar, TScriptInterface &Interface)
Additional Inherited Members
Protected Member Functions inherited from FScriptInterface
FArchive & Serialize (FArchive &Ar, class UClass *InterfaceType)
Serialize ScriptInterface.
Detailed Description
template<typename InInterfaceType>
class TScriptInterface< InInterfaceType >
Templated version of FScriptInterface, which provides accessors and operators for referencing the interface portion of an object implementing an interface.
This type is only useful with native interfaces, UClass::ImplementsInterface should be used to check for blueprint interfaces.
Definition at line 138 of file ScriptInterface.h.
Member Typedef Documentation
InterfaceType
template<typename InInterfaceType> using TScriptInterface< InInterfaceType >::InterfaceType = InInterfaceType
Definition at line 141 of file ScriptInterface.h.
UObjectType
template<typename InInterfaceType> using TScriptInterface< InInterfaceType >::UObjectType = TCopyQualifiersFromTo_T<InterfaceType, UObject>
Definition at line 142 of file ScriptInterface.h.
Constructor & Destructor Documentation
TScriptInterface() [1/6]
template<typename InInterfaceType> TScriptInterface< InInterfaceType >::TScriptInterface () default
Default constructor.
Referenced by TScriptInterface< const InterfaceType >::operator=(), TScriptInterface< const InterfaceType >::operator=(), TScriptInterface< const InterfaceType >::operator=(), and TScriptInterface< const InterfaceType >::operator=().
TScriptInterface() [2/6]
template<typename InInterfaceType> TScriptInterface< InInterfaceType >::TScriptInterface (TYPE_OF_NULLPTR) inline
Construction from nullptr.
Definition at line 152 of file ScriptInterface.h.
TScriptInterface() [3/6]
template<typename InInterfaceType> template<typename U UE_REQUIRES> FORCEINLINE TScriptInterface< InInterfaceType >::TScriptInterface (U && Source) inline
Construction from an object type that may natively implement InterfaceType.
Definition at line 161 of file ScriptInterface.h.
TScriptInterface() [4/6]
template<typename InInterfaceType> template<typename OtherInterfaceType UE_REQUIRES> FORCEINLINE TScriptInterface< InInterfaceType >::TScriptInterface (const TScriptInterface< OtherInterfaceType > & Other) inline
Construction from another script interface of a compatible interface type.
Definition at line 188 of file ScriptInterface.h.
TScriptInterface() [5/6]
template<typename InInterfaceType> template<typename ObjectType> TScriptInterface< InInterfaceType >::TScriptInterface (TObjectPtr< ObjectType > SourceObject) inline
Assignment from an object type that may natively implement InterfaceType.
Definition at line 200 of file ScriptInterface.h.
TScriptInterface() [6/6]
template<typename InInterfaceType> TScriptInterface< InInterfaceType >::TScriptInterface (const TScriptInterface< InInterfaceType > &) default
Copyable.
Member Function Documentation
GetInterface()
template<typename InInterfaceType> FORCEINLINE InInterfaceType * TScriptInterface< InInterfaceType >::GetInterface () const inline
Returns the pointer to the interface.
Definition at line 335 of file ScriptInterface.h.
Referenced by TWeakInterfacePtr< IActorInstanceManagerInterface >::TWeakInterfacePtr(), TScriptInterface< const InterfaceType >::operator bool(), TScriptInterface< const InterfaceType >::operator!=(), TScriptInterface< const InterfaceType >::operator!=(), TScriptInterface< const InterfaceType >::operator!=(), TScriptInterface< const InterfaceType >::operator*(), TScriptInterface< const InterfaceType >::operator->(), TScriptInterface< const InterfaceType >::operator==(), TScriptInterface< const InterfaceType >::operator==(), and TScriptInterface< const InterfaceType >::operator==().
GetObject()
template<typename InInterfaceType> FORCEINLINE UObjectType * TScriptInterface< InInterfaceType >::GetObject () const inline
Returns the ObjectPointer contained by this TScriptInterface.
Definition at line 351 of file ScriptInterface.h.
Referenced by TWeakInterfacePtr< IActorInstanceManagerInterface >::TWeakInterfacePtr(), TScriptInterface< const InterfaceType >::operator!=(), and TScriptInterface< const InterfaceType >::operator==().
GetObjectRef()
template<typename InInterfaceType> FORCEINLINE TObjectPtr< UObjectType > & TScriptInterface< InInterfaceType >::GetObjectRef () inline
Returns the ObjectPointer contained by this TScriptInterface.
Definition at line 359 of file ScriptInterface.h.
operator bool()
template<typename InInterfaceType> FORCEINLINE TScriptInterface< InInterfaceType >::operator bool () const inline explicit
Boolean operator, returns true if this object natively implements InterfaceType.
This will return false for objects that only implement the interface in blueprint classes.
Definition at line 376 of file ScriptInterface.h.
operator!=() [1/3]
template<typename InInterfaceType> template<typename OtherInterface UE_REQUIRES> FORCEINLINE bool TScriptInterface< InInterfaceType >::operator!= (const OtherInterface * Other) const inline
Definition at line 285 of file ScriptInterface.h.
operator!=() [2/3]
template<typename InInterfaceType> FORCEINLINE bool TScriptInterface< InInterfaceType >::operator!= (const TScriptInterface< InInterfaceType > & Other) const inline
Definition at line 297 of file ScriptInterface.h.
operator!=() [3/3]
template<typename InInterfaceType> FORCEINLINE bool TScriptInterface< InInterfaceType >::operator!= (TYPE_OF_NULLPTR) const inline
Definition at line 309 of file ScriptInterface.h.
operator*()
template<typename InInterfaceType> FORCEINLINE InInterfaceType & TScriptInterface< InInterfaceType >::operator* () const inline
Dereference operator.
Provides transparent access to the native interface pointer contained by this TScriptInterface
Returns
a reference (of type InterfaceType) to the object pointed to by InterfacePointer
Definition at line 327 of file ScriptInterface.h.
operator->()
template<typename InInterfaceType> FORCEINLINE InInterfaceType * TScriptInterface< InInterfaceType >::operator-> () const inline
Member access operator.
Provides transparent access to the native interface pointer contained by this TScriptInterface
Definition at line 317 of file ScriptInterface.h.
operator=() [1/5]
template<typename InInterfaceType> TScriptInterface & TScriptInterface< InInterfaceType >::operator= (const TScriptInterface< InInterfaceType > &) default
operator=() [2/5]
template<typename InInterfaceType> template<typename OtherInterfaceType UE_REQUIRES> TScriptInterface & TScriptInterface< InInterfaceType >::operator= (const TScriptInterface< OtherInterfaceType > & Other) inline
Assignment from another script interface of a compatible interface type.
Definition at line 254 of file ScriptInterface.h.
operator=() [3/5]
template<typename InInterfaceType> template<typename ObjectType> TScriptInterface & TScriptInterface< InInterfaceType >::operator= (TObjectPtr< ObjectType > SourceObject) inline
Assignment from an object type that may natively implement InterfaceType.
Definition at line 264 of file ScriptInterface.h.
operator=() [4/5]
template<typename InInterfaceType> TScriptInterface & TScriptInterface< InInterfaceType >::operator= (TYPE_OF_NULLPTR) inline
Assignment from nullptr.
Definition at line 228 of file ScriptInterface.h.
operator=() [5/5]
template<typename InInterfaceType> template<typename U UE_REQUIRES> TScriptInterface & TScriptInterface< InInterfaceType >::operator= (U && Source) inline
Assignment from an object type that may natively implement InterfaceType.
Definition at line 241 of file ScriptInterface.h.
operator==() [1/3]
template<typename InInterfaceType> template<typename OtherInterface UE_REQUIRES> FORCEINLINE bool TScriptInterface< InInterfaceType >::operator== (const OtherInterface * Other) const inline
Comparison operator, taking a pointer to InterfaceType.
Definition at line 277 of file ScriptInterface.h.
operator==() [2/3]
template<typename InInterfaceType> FORCEINLINE bool TScriptInterface< InInterfaceType >::operator== (const TScriptInterface< InInterfaceType > & Other) const inline
Comparison operator, taking a reference to another TScriptInterface.
Definition at line 293 of file ScriptInterface.h.
operator==() [3/3]
template<typename InInterfaceType> FORCEINLINE bool TScriptInterface< InInterfaceType >::operator== (TYPE_OF_NULLPTR) const inline
Comparison operator, taking a nullptr.
Definition at line 305 of file ScriptInterface.h.
SetInterface()
template<typename InInterfaceType> FORCEINLINE void TScriptInterface< InInterfaceType >::SetInterface (InInterfaceType * InInterfacePointer) inline
Sets the value of the InterfacePointer for this TScriptInterface.
Definition at line 343 of file ScriptInterface.h.
Referenced by TScriptInterface< const InterfaceType >::TScriptInterface(), TScriptInterface< const InterfaceType >::TScriptInterface(), and TScriptInterface< const InterfaceType >::TScriptInterface().
SetObject()
template<typename InInterfaceType> FORCEINLINE void TScriptInterface< InInterfaceType >::SetObject (UObjectType * InObjectPointer) inline
Sets the value of the ObjectPointer for this TScriptInterface.
Definition at line 367 of file ScriptInterface.h.
Referenced by TScriptInterface< const InterfaceType >::TScriptInterface(), TScriptInterface< const InterfaceType >::TScriptInterface(), and TScriptInterface< const InterfaceType >::TScriptInterface().
Friends And Related Symbol Documentation
operator<<
template<typename InInterfaceType> FArchive & operator<< (FArchive & Ar, TScriptInterface< InInterfaceType > & Interface) friend
Definition at line 381 of file ScriptInterface.h.
The documentation for this class was generated from the following files:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundFrontendRegistryContainer.h
Runtime/CoreUObject/Public/UObject/ScriptInterface.h