Unreal Engine 5.6 C++ API: ILocalizedTextSource Class Reference
ILocalizedTextSource Class Reference abstract
Interface for a localized text source.
#include "ILocalizedTextSource.h"
Public Member Functions
virtual ~ILocalizedTextSource ()=default
virtual void GetLocalizedCultureNames (const ELocalizationLoadFlags InLoadFlags, TSet< FString > &OutLocalizedCultureNames)=0
Populate a list of culture names that this localized text source has resource data for (ELocalizationLoadFlags controls which resources should be checked).
virtual bool GetNativeCultureName (const ELocalizedTextSourceCategory InCategory, FString &OutNativeCultureName)=0
Given a localization category, get the native culture for the category (if known).
virtual int32 GetPriority () const
Get the priority of this source when building the complete list of translations to apply (higher numbers have a higher priority).
virtual void LoadLocalizedResources (const ELocalizationLoadFlags InLoadFlags, TArrayView< const FString > InPrioritizedCultures, FTextLocalizationResource &InOutNativeResource, FTextLocalizationResource &InOutLocalizedResource)=0
Load the localized resources from this localized text source for the given cultures into the given maps (ELocalizationLoadFlags controls which resources should be loaded).
virtual EQueryLocalizedResourceResult QueryLocalizedResource (const ELocalizationLoadFlags InLoadFlags, TArrayView< const FString > InPrioritizedCultures, const FTextId InTextId, FTextLocalizationResource &InOutNativeResource, FTextLocalizationResource &InOutLocalizedResource)
Query a localized resource from this localized text source for the given cultures and ID into the given maps (ELocalizationLoadFlags controls which resources should be queried).
Static Public Member Functions
static FORCEINLINE bool ShouldLoadAdditional (const ELocalizationLoadFlags InLoadFlags)
Should we load additional (eg, plugin) data based on the given load flags and environment?
static FORCEINLINE bool ShouldLoadEditor (const ELocalizationLoadFlags InLoadFlags)
Should we load editor data based on the given load flags and environment?
static FORCEINLINE bool ShouldLoadEngine (const ELocalizationLoadFlags InLoadFlags)
Should we load engine data based on the given load flags and environment?
static FORCEINLINE bool ShouldLoadGame (const ELocalizationLoadFlags InLoadFlags)
Should we load game data based on the given load flags and environment?
static FORCEINLINE bool ShouldLoadNative (const ELocalizationLoadFlags InLoadFlags)
Should we load native data based on the given load flags and environment?
static FORCEINLINE bool ShouldLoadNativeGameData (const ELocalizationLoadFlags InLoadFlags)
Should we load native game data based on the given load flags and environment?
Detailed Description
Interface for a localized text source.
These can be registered with the text localization manager, and provide an extensible way to inject localized text to UE4.
Definition at line 18 of file ILocalizedTextSource.h.
Constructor & Destructor Documentation
~ILocalizedTextSource()
virtual ILocalizedTextSource::~ILocalizedTextSource () virtual default
Member Function Documentation
GetLocalizedCultureNames()
virtual void ILocalizedTextSource::GetLocalizedCultureNames (const ELocalizationLoadFlags InLoadFlags, TSet< FString > & OutLocalizedCultureNames) pure virtual
Populate a list of culture names that this localized text source has resource data for (ELocalizationLoadFlags controls which resources should be checked).
GetNativeCultureName()
virtual bool ILocalizedTextSource::GetNativeCultureName (const ELocalizedTextSourceCategory InCategory, FString & OutNativeCultureName) pure virtual
Given a localization category, get the native culture for the category (if known).
Returns
True if the native culture was populated, or false if the native culture is unknown.
GetPriority()
virtual int32 ILocalizedTextSource::GetPriority () const inline virtual
Get the priority of this source when building the complete list of translations to apply (higher numbers have a higher priority).
Definition at line 26 of file ILocalizedTextSource.h.
References ELocalizedTextSourcePriority::Normal.
LoadLocalizedResources()
virtual void ILocalizedTextSource::LoadLocalizedResources (const ELocalizationLoadFlags InLoadFlags, TArrayView< const FString > InPrioritizedCultures, FTextLocalizationResource & InOutNativeResource, FTextLocalizationResource & InOutLocalizedResource) pure virtual
Load the localized resources from this localized text source for the given cultures into the given maps (ELocalizationLoadFlags controls which resources should be loaded).
QueryLocalizedResource()
virtual EQueryLocalizedResourceResult ILocalizedTextSource::QueryLocalizedResource (const ELocalizationLoadFlags InLoadFlags, TArrayView< const FString > InPrioritizedCultures, const FTextId InTextId, FTextLocalizationResource & InOutNativeResource, FTextLocalizationResource & InOutLocalizedResource) inline virtual
Query a localized resource from this localized text source for the given cultures and ID into the given maps (ELocalizationLoadFlags controls which resources should be queried).
Definition at line 50 of file ILocalizedTextSource.h.
References NotImplemented.
ShouldLoadAdditional()
FORCEINLINE bool ILocalizedTextSource::ShouldLoadAdditional (const ELocalizationLoadFlags InLoadFlags) inline static
Should we load additional (eg, plugin) data based on the given load flags and environment?
Definition at line 80 of file ILocalizedTextSource.h.
References Additional, EnumHasAnyFlags(), and FORCEINLINE.
ShouldLoadEditor()
FORCEINLINE bool ILocalizedTextSource::ShouldLoadEditor (const ELocalizationLoadFlags InLoadFlags) inline static
Should we load editor data based on the given load flags and environment?
Definition at line 62 of file ILocalizedTextSource.h.
References Editor, EnumHasAnyFlags(), and FORCEINLINE.
ShouldLoadEngine()
FORCEINLINE bool ILocalizedTextSource::ShouldLoadEngine (const ELocalizationLoadFlags InLoadFlags) inline static
Should we load engine data based on the given load flags and environment?
Definition at line 74 of file ILocalizedTextSource.h.
References Engine, EnumHasAnyFlags(), and FORCEINLINE.
ShouldLoadGame()
FORCEINLINE bool ILocalizedTextSource::ShouldLoadGame (const ELocalizationLoadFlags InLoadFlags) inline static
Should we load game data based on the given load flags and environment?
Definition at line 68 of file ILocalizedTextSource.h.
References EnumHasAnyFlags(), FORCEINLINE, ForceLocalizedGame, and Game.
ShouldLoadNative()
FORCEINLINE bool ILocalizedTextSource::ShouldLoadNative (const ELocalizationLoadFlags InLoadFlags) inline static
Should we load native data based on the given load flags and environment?
Definition at line 56 of file ILocalizedTextSource.h.
References EnumHasAnyFlags(), FORCEINLINE, and Native.
ShouldLoadNativeGameData()
FORCEINLINE bool ILocalizedTextSource::ShouldLoadNativeGameData (const ELocalizationLoadFlags InLoadFlags) inline static
Should we load native game data based on the given load flags and environment?
Definition at line 86 of file ILocalizedTextSource.h.
References EnumHasAnyFlags(), FORCEINLINE, ForceLocalizedGame, and GIsEditor.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/ILocalizedTextSource.h