Unreal Engine 5.6 C++ API: DisplayClusterTypesConverter Class Reference
DisplayClusterTypesConverter Class Reference
Auxiliary class with different type conversion functions.
#include "DisplayClusterTypesConverter.h"
Public Member Functions
template<>
float FromHexString (const FString &From)
template<>
double FromHexString (const FString &From)
template<>
FVector FromHexString (const FString &From)
template<>
FVector2D FromHexString (const FString &From)
template<>
FRotator FromHexString (const FString &From)
template<>
FMatrix FromHexString (const FString &From)
template<>
FTransform FromHexString (const FString &From)
template<>
FQuat FromHexString (const FString &From)
template<>
FString FromString (const FString &From)
template<>
bool FromString (const FString &From)
template<>
int8 FromString (const FString &From)
template<>
uint8 FromString (const FString &From)
template<>
int32 FromString (const FString &From)
template<>
uint32 FromString (const FString &From)
template<>
float FromString (const FString &From)
template<>
double FromString (const FString &From)
template<>
FVector FromString (const FString &From)
template<>
FVector2D FromString (const FString &From)
template<>
FRotator FromString (const FString &From)
template<>
FMatrix FromString (const FString &From)
template<>
FQuat FromString (const FString &From)
template<>
FIntPoint FromString (const FString &From)
template<>
FTimecode FromString (const FString &From)
template<>
FFrameRate FromString (const FString &From)
template<>
FQualifiedFrameTime FromString (const FString &From)
template<>
EDisplayClusterSyncGroup FromString (const FString &From)
template<>
FString ToHexString (const double &From)
template<>
FString ToHexString (const float &From)
template<>
FString ToHexString (const FMatrix &From)
template<>
FString ToHexString (const FQuat &From)
template<>
FString ToHexString (const FRotator &From)
template<>
FString ToHexString (const FTransform &From)
template<>
FString ToHexString (const FVector &From)
template<>
FString ToHexString (const FVector2D &From)
template<>
FString ToString (const bool &From)
template<>
FString ToString (const double &From)
template<>
FString ToString (const EDisplayClusterOperationMode &From)
template<>
FString ToString (const EDisplayClusterSyncGroup &From)
template<>
FString ToString (const FFrameRate &From)
template<>
FString ToString (const FIntPoint &From)
template<>
FString ToString (const float &From)
template<>
FString ToString (const FMatrix &From)
template<>
FString ToString (const FQualifiedFrameTime &From)
template<>
FString ToString (const FQuat &From)
template<>
FString ToString (const FRotator &From)
template<>
FString ToString (const FString &From)
template<>
FString ToString (const FTimecode &From)
template<>
FString ToString (const FVector &From)
template<>
FString ToString (const FVector2D &From)
template<>
FString ToString (const int32 &From)
template<>
FString ToString (const int8 &From)
template<>
FString ToString (const uint32 &From)
template<>
FString ToString (const uint8 &From)
Static Public Member Functions
template<typename ConvertTo>
static ConvertTo FromHexString (const FString &From)
template<>
float FromHexString (const FString &From)
template<typename ConvertTo>
static ConvertTo FromString (const FString &From)
template<typename ConvertFrom>
static FString ToHexString (const ConvertFrom &From)
template<>
FString ToHexString (const float &From)
template<typename ConvertFrom>
static FString ToString (const ConvertFrom &From)
Detailed Description
Auxiliary class with different type conversion functions.
Definition at line 16 of file DisplayClusterTypesConverter.h.
Member Function Documentation
FromHexString() [1/10]
template<typename ConvertTo> ConvertTo DisplayClusterTypesConverter::FromHexString (const FString & From) static
Referenced by FromHexString(), and FromString().
FromHexString() [2/10]
template<> float DisplayClusterTypesConverter::FromHexString (const FString & From) static
FromHexString() [3/10]
template<> float DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 373 of file DisplayClusterTypesConverter.h.
References checkSlow.
FromHexString() [4/10]
template<> double DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 381 of file DisplayClusterTypesConverter.h.
References checkSlow.
FromHexString() [5/10]
template<> FVector DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 389 of file DisplayClusterTypesConverter.h.
References FromHexString(), FVector, TEXT, FParse::Value(), X, Y, Z, and UE::Math::TVector< double >::ZeroVector.
FromHexString() [6/10]
template<> FVector2D DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 405 of file DisplayClusterTypesConverter.h.
References FromHexString(), TEXT, FParse::Value(), X, Y, and UE::Math::TVector2< double >::ZeroVector.
FromHexString() [7/10]
template<> FRotator DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 420 of file DisplayClusterTypesConverter.h.
References FromHexString(), R, TEXT, FParse::Value(), Y, and UE::Math::TRotator< double >::ZeroRotator.
FromHexString() [8/10]
template<> FMatrix DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 436 of file DisplayClusterTypesConverter.h.
References FromHexString(), ESearchDir::FromStart, UE::Math::TMatrix< double >::Identity, ESearchCase::IgnoreCase, INDEX_NONE, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
FromHexString() [9/10]
template<> FTransform DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 484 of file DisplayClusterTypesConverter.h.
References FromHexString(), FVector, UE::Math::TTransform< double >::Identity, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
FromHexString() [10/10]
template<> FQuat DisplayClusterTypesConverter::FromHexString (const FString & From) inline
Definition at line 502 of file DisplayClusterTypesConverter.h.
References FromHexString(), UE::Math::TQuat< double >::Identity, TEXT, FParse::Value(), X, Y, and Z.
FromString() [1/19]
template<typename ConvertTo> ConvertTo DisplayClusterTypesConverter::FromString (const FString & From) static
Referenced by FromString().
FromString() [2/19]
template<> FString DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 130 of file DisplayClusterTypesConverter.h.
FromString() [3/19]
template<> bool DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 131 of file DisplayClusterTypesConverter.h.
References ESearchCase::IgnoreCase.
FromString() [4/19]
template<> int8 DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 132 of file DisplayClusterTypesConverter.h.
References TCString< TCHAR >::Atoi().
FromString() [5/19]
template<> uint8 DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 133 of file DisplayClusterTypesConverter.h.
References FromString().
FromString() [6/19]
template<> int32 DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 134 of file DisplayClusterTypesConverter.h.
References TCString< TCHAR >::Atoi().
FromString() [7/19]
template<> uint32 DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 135 of file DisplayClusterTypesConverter.h.
References FromString().
FromString() [8/19]
template<> float DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 136 of file DisplayClusterTypesConverter.h.
References TCString< TCHAR >::Atof().
FromString() [9/19]
template<> double DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 137 of file DisplayClusterTypesConverter.h.
References TCString< TCHAR >::Atod().
FromString() [10/19]
template<> FVector DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 138 of file DisplayClusterTypesConverter.h.
References FVector, and UE::Math::TVector< T >::InitFromString().
FromString() [11/19]
template<> FVector2D DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 139 of file DisplayClusterTypesConverter.h.
References UE::Math::TVector2< T >::InitFromString().
FromString() [12/19]
template<> FRotator DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 140 of file DisplayClusterTypesConverter.h.
References UE::Math::TRotator< T >::InitFromString().
FromString() [13/19]
template<> FMatrix DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 142 of file DisplayClusterTypesConverter.h.
References ESearchDir::FromStart, FromString(), UE::Math::TMatrix< double >::Identity, ESearchCase::IgnoreCase, INDEX_NONE, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
FromString() [14/19]
template<> FQuat DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 190 of file DisplayClusterTypesConverter.h.
References UE::Math::TQuat< double >::Identity, TEXT, and FParse::Value().
FromString() [15/19]
template<> FIntPoint DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 207 of file DisplayClusterTypesConverter.h.
References TEXT, FParse::Value(), and UE::Math::TIntPoint< int32 >::ZeroValue.
FromString() [16/19]
template<> FTimecode DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 222 of file DisplayClusterTypesConverter.h.
References FTimecode::bDropFrameFormat, FTimecode::Frames, FromString(), FTimecode::Hours, FTimecode::Minutes, TArray< InElementType, InAllocatorType >::Reserve(), FTimecode::Seconds, and TEXT.
FromString() [17/19]
template<> FFrameRate DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 243 of file DisplayClusterTypesConverter.h.
References FFrameRate::Denominator, FromString(), FFrameRate::Numerator, TArray< InElementType, InAllocatorType >::Reserve(), and TEXT.
FromString() [18/19]
template<> FQualifiedFrameTime DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 261 of file DisplayClusterTypesConverter.h.
References FFrameRate::Denominator, FromHexString(), FromString(), FFrameRate::Numerator, FQualifiedFrameTime::Rate, TArray< InElementType, InAllocatorType >::Reserve(), TEXT, and FQualifiedFrameTime::Time.
FromString() [19/19]
template<> EDisplayClusterSyncGroup DisplayClusterTypesConverter::FromString (const FString & From) inline
Definition at line 280 of file DisplayClusterTypesConverter.h.
References TEXT.
ToHexString() [1/10]
template<typename ConvertFrom> FString DisplayClusterTypesConverter::ToHexString (const ConvertFrom & From) static
Referenced by ToHexString(), ToHexString(), ToHexString(), ToHexString(), ToHexString(), ToHexString(), and ToString().
ToHexString() [2/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const double & From) inline
Definition at line 307 of file DisplayClusterTypesConverter.h.
References BytesToHex().
ToHexString() [3/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const float & From) static
ToHexString() [4/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const float & From) inline
Definition at line 302 of file DisplayClusterTypesConverter.h.
References BytesToHex().
ToHexString() [5/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const FMatrix & From) inline
Definition at line 335 of file DisplayClusterTypesConverter.h.
References UE::Math::TMatrix< T >::M, TEXT, and ToHexString().
ToHexString() [6/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const FQuat & From) inline
Definition at line 359 of file DisplayClusterTypesConverter.h.
References TEXT, ToHexString(), UE::Math::TQuat< T >::W, UE::Math::TQuat< T >::X, UE::Math::TQuat< T >::Y, and UE::Math::TQuat< T >::Z.
ToHexString() [7/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const FRotator & From) inline
Definition at line 327 of file DisplayClusterTypesConverter.h.
References UE::Math::TRotator< T >::Pitch, UE::Math::TRotator< T >::Roll, TEXT, ToHexString(), and UE::Math::TRotator< T >::Yaw.
ToHexString() [8/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const FTransform & From) inline
Definition at line 351 of file DisplayClusterTypesConverter.h.
References UE::Math::TTransform< T >::GetLocation(), UE::Math::TTransform< T >::GetRotation(), UE::Math::TTransform< T >::GetScale3D(), UE::Math::TQuat< T >::Rotator(), TEXT, and ToHexString().
ToHexString() [9/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const FVector & From) inline
Definition at line 312 of file DisplayClusterTypesConverter.h.
References FVector, TEXT, ToHexString(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
ToHexString() [10/10]
template<> FString DisplayClusterTypesConverter::ToHexString (const FVector2D & From) inline
Definition at line 320 of file DisplayClusterTypesConverter.h.
References TEXT, ToHexString(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
ToString() [1/20]
template<> FString DisplayClusterTypesConverter::ToString (const bool & From) inline
Definition at line 56 of file DisplayClusterTypesConverter.h.
References TEXT.
ToString() [2/20]
template<typename ConvertFrom> FString DisplayClusterTypesConverter::ToString (const ConvertFrom & From) static
ToString() [3/20]
template<> FString DisplayClusterTypesConverter::ToString (const double & From) inline
Definition at line 62 of file DisplayClusterTypesConverter.h.
References TEXT.
ToString() [4/20]
template<> FString DisplayClusterTypesConverter::ToString (const EDisplayClusterOperationMode & From) inline
Definition at line 96 of file DisplayClusterTypesConverter.h.
ToString() [5/20]
template<> FString DisplayClusterTypesConverter::ToString (const EDisplayClusterSyncGroup & From) inline
Definition at line 111 of file DisplayClusterTypesConverter.h.
ToString() [6/20]
template<> FString DisplayClusterTypesConverter::ToString (const FFrameRate & From) inline
Definition at line 86 of file DisplayClusterTypesConverter.h.
References FFrameRate::Denominator, FFrameRate::Numerator, and TEXT.
ToString() [7/20]
template<> FString DisplayClusterTypesConverter::ToString (const FIntPoint & From) inline
Definition at line 66 of file DisplayClusterTypesConverter.h.
References UE::Math::TIntPoint< InIntType >::ToString().
ToString() [8/20]
template<> FString DisplayClusterTypesConverter::ToString (const float & From) inline
Definition at line 61 of file DisplayClusterTypesConverter.h.
ToString() [9/20]
template<> FString DisplayClusterTypesConverter::ToString (const FMatrix & From) inline
Definition at line 64 of file DisplayClusterTypesConverter.h.
References UE::Math::TMatrix< T >::ToString().
ToString() [10/20]
template<> FString DisplayClusterTypesConverter::ToString (const FQualifiedFrameTime & From) inline
Definition at line 91 of file DisplayClusterTypesConverter.h.
References FFrameRate::Denominator, FFrameTime::GetFrame(), FFrameTime::GetSubFrame(), FFrameRate::Numerator, FQualifiedFrameTime::Rate, TEXT, FQualifiedFrameTime::Time, ToHexString(), and FFrameNumber::Value.
ToString() [11/20]
template<> FString DisplayClusterTypesConverter::ToString (const FQuat & From) inline
Definition at line 65 of file DisplayClusterTypesConverter.h.
References UE::Math::TQuat< T >::ToString().
ToString() [12/20]
template<> FString DisplayClusterTypesConverter::ToString (const FRotator & From) inline
Definition at line 63 of file DisplayClusterTypesConverter.h.
References UE::Math::TRotator< T >::ToString().
ToString() [13/20]
template<> FString DisplayClusterTypesConverter::ToString (const FString & From) inline
Definition at line 55 of file DisplayClusterTypesConverter.h.
ToString() [14/20]
template<> FString DisplayClusterTypesConverter::ToString (const FTimecode & From) inline
Definition at line 81 of file DisplayClusterTypesConverter.h.
References FTimecode::bDropFrameFormat, FTimecode::Frames, FTimecode::Hours, FTimecode::Minutes, FTimecode::Seconds, and TEXT.
ToString() [15/20]
template<> FString DisplayClusterTypesConverter::ToString (const FVector & From) inline
Definition at line 69 of file DisplayClusterTypesConverter.h.
References FVector, TEXT, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
ToString() [16/20]
template<> FString DisplayClusterTypesConverter::ToString (const FVector2D & From) inline
Definition at line 75 of file DisplayClusterTypesConverter.h.
References TEXT, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
ToString() [17/20]
template<> FString DisplayClusterTypesConverter::ToString (const int32 & From) inline
Definition at line 59 of file DisplayClusterTypesConverter.h.
ToString() [18/20]
template<> FString DisplayClusterTypesConverter::ToString (const int8 & From) inline
Definition at line 57 of file DisplayClusterTypesConverter.h.
ToString() [19/20]
template<> FString DisplayClusterTypesConverter::ToString (const uint32 & From) inline
Definition at line 60 of file DisplayClusterTypesConverter.h.
References ToString().
Referenced by ToString().
ToString() [20/20]
template<> FString DisplayClusterTypesConverter::ToString (const uint8 & From) inline
Definition at line 58 of file DisplayClusterTypesConverter.h.
References ToString().
Referenced by ToString().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Misc/DisplayClusterTypesConverter.h