Unreal Engine 5.6 C++ API: IAnimBlueprintCompilationBracketContext Class Reference
IAnimBlueprintCompilationBracketContext Class Reference abstract
#include "IAnimBlueprintCompilationBracketContext.h"
Public Member Functions
virtual ~IAnimBlueprintCompilationBracketContext ()
const TMap< UAnimGraphNode_Base *, int32 > & GetAllocatedAnimNodeIndices () const
const TMap< UAnimGraphNode_Base *, FProperty * > & GetAllocatedHandlerPropertiesByNode () const
FCompilerResultsLog & GetMessageLog () const
Protected Member Functions
virtual const TMap< UAnimGraphNode_Base *, int32 > & GetAllocatedAnimNodeIndicesImpl () const =0
virtual const TMap< UAnimGraphNode_Base *, FProperty * > & GetAllocatedHandlerPropertiesByNodeImpl () const =0
virtual FCompilerResultsLog & GetMessageLogImpl () const =0
Detailed Description
Definition at line 11 of file IAnimBlueprintCompilationBracketContext.h.
Constructor & Destructor Documentation
~IAnimBlueprintCompilationBracketContext()
virtual IAnimBlueprintCompilationBracketContext::~IAnimBlueprintCompilationBracketContext () inline virtual
Definition at line 14 of file IAnimBlueprintCompilationBracketContext.h.
Member Function Documentation
GetAllocatedAnimNodeIndices()
const TMap< UAnimGraphNode_Base *, int32 > & IAnimBlueprintCompilationBracketContext::GetAllocatedAnimNodeIndices () const inline
Definition at line 20 of file IAnimBlueprintCompilationBracketContext.h.
References GetAllocatedAnimNodeIndicesImpl().
GetAllocatedAnimNodeIndicesImpl()
virtual const TMap< UAnimGraphNode_Base *, int32 > & IAnimBlueprintCompilationBracketContext::GetAllocatedAnimNodeIndicesImpl () const protected pure virtual
Referenced by GetAllocatedAnimNodeIndices().
GetAllocatedHandlerPropertiesByNode()
const TMap< UAnimGraphNode_Base *, FProperty * > & IAnimBlueprintCompilationBracketContext::GetAllocatedHandlerPropertiesByNode () const inline
Definition at line 23 of file IAnimBlueprintCompilationBracketContext.h.
References GetAllocatedHandlerPropertiesByNodeImpl().
GetAllocatedHandlerPropertiesByNodeImpl()
virtual const TMap< UAnimGraphNode_Base *, FProperty * > & IAnimBlueprintCompilationBracketContext::GetAllocatedHandlerPropertiesByNodeImpl () const protected pure virtual
Referenced by GetAllocatedHandlerPropertiesByNode().
GetMessageLog()
FCompilerResultsLog & IAnimBlueprintCompilationBracketContext::GetMessageLog () const inline
Definition at line 17 of file IAnimBlueprintCompilationBracketContext.h.
References GetMessageLogImpl().
GetMessageLogImpl()
virtual FCompilerResultsLog & IAnimBlueprintCompilationBracketContext::GetMessageLogImpl () const protected pure virtual
Referenced by GetMessageLog().
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/IAnimBlueprintCompilationBracketContext.h