Unreal Engine 5.6 C++ API: FIoChunkId Class Reference
FIoChunkId Class Reference
Identifier to a chunk of data.
#include "IoChunkId.h"
Public Member Functions
EIoChunkType GetChunkType () const
const uint8 * GetData () const
uint32 GetSize () const
bool IsValid () const
bool operator!= (const FIoChunkId &Rhs) const
bool operator< (const FIoChunkId &Rhs) const
bool operator== (const FIoChunkId &Rhs) const
bool operator> (const FIoChunkId &Rhs) const
void Set (const void *InIdPtr, SIZE_T InSize)
void Set (FMemoryView InView)
void ToString (FString &Output) const
Static Public Member Functions
static FIoChunkId FromHex (FStringView Hex)
Creates an I/O chunk ID from a 24 character long hexadecimal string.
Static Public Attributes
static const FIoChunkId InvalidChunkId
Static Private Member Functions
static FIoChunkId CreateEmptyId ()
Private Attributes
uint8 Id [12]
Friends
class FIoStoreReaderImpl
uint32 GetTypeHash (FIoChunkId InId)
FString LexToString (const FIoChunkId &Id)
bool LoadFromCompactBinary (FCbFieldView Field, FIoChunkId &OutChunkId)
FArchive & operator<< (FArchive &Ar, FIoChunkId &ChunkId)
FCbWriter & operator<< (FCbWriter &Writer, const FIoChunkId &ChunkId)
template<typename CharType>
TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > &Builder, const FIoChunkId &ChunkId)
Detailed Description
Identifier to a chunk of data.
Definition at line 63 of file IoChunkId.h.
Member Function Documentation
CreateEmptyId()
FIoChunkId FIoChunkId::CreateEmptyId () inline static private
Definition at line 146 of file IoChunkId.h.
References Set().
FromHex()
FIoChunkId FIoChunkId::FromHex (FStringView Hex) static
Creates an I/O chunk ID from a 24 character long hexadecimal string.
Returns
The corresponding I/O chunk ID or an invalid ID if the input string is not in the correct format.
GetChunkType()
EIoChunkType FIoChunkId::GetChunkType () const inline
Definition at line 132 of file IoChunkId.h.
References Id.
GetData()
const uint8 * FIoChunkId::GetData () const inline
Definition at line 129 of file IoChunkId.h.
References Id.
GetSize()
uint32 FIoChunkId::GetSize () const inline
Definition at line 130 of file IoChunkId.h.
References Id.
IsValid()
bool FIoChunkId::IsValid () const inline
Definition at line 124 of file IoChunkId.h.
References InvalidChunkId.
operator!=()
bool FIoChunkId::operator!= (const FIoChunkId & Rhs) const inline
Definition at line 97 of file IoChunkId.h.
operator<()
bool FIoChunkId::operator< (const FIoChunkId & Rhs) const inline
Definition at line 102 of file IoChunkId.h.
References Id, and FMemory::Memcmp().
operator==()
bool FIoChunkId::operator== (const FIoChunkId & Rhs) const inline
Definition at line 92 of file IoChunkId.h.
References Id, and FMemory::Memcmp().
operator>()
bool FIoChunkId::operator> (const FIoChunkId & Rhs) const inline
Definition at line 107 of file IoChunkId.h.
References Id, and FMemory::Memcmp().
Set() [1/2]
void FIoChunkId::Set (const void * InIdPtr, SIZE_T InSize) inline
Definition at line 112 of file IoChunkId.h.
References check, Id, and FMemory::Memcpy().
Referenced by CreateBulkDataIoChunkId(), CreateEmptyId(), and CreateIoChunkId().
Set() [2/2]
void FIoChunkId::Set (FMemoryView InView) inline
Definition at line 118 of file IoChunkId.h.
References check, TMemoryView< DataType >::GetData(), TMemoryView< DataType >::GetSize(), Id, and FMemory::Memcpy().
ToString()
void FIoChunkId::ToString (FString & Output) const
Friends And Related Symbol Documentation
FIoStoreReaderImpl
friend class FIoStoreReaderImpl friend
Definition at line 137 of file IoChunkId.h.
References FIoStoreReaderImpl.
Referenced by FIoStoreReaderImpl.
GetTypeHash
uint32 GetTypeHash (FIoChunkId InId) friend
Definition at line 68 of file IoChunkId.h.
References Hash, and Id.
LexToString
FString LexToString (const FIoChunkId & Id) friend
References Id.
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Field, FIoChunkId & OutChunkId) friend
operator<< [1/3]
FArchive & operator<< (FArchive & Ar, FIoChunkId & ChunkId) friend
References Ar.
operator<< [2/3]
FCbWriter & operator<< (FCbWriter & Writer, const FIoChunkId & ChunkId) friend
operator<< [3/3]
template<typename CharType> TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > & Builder, const FIoChunkId & ChunkId) friend
Definition at line 83 of file IoChunkId.h.
References UE::String::BytesToHexLower(), and Id.
Field Documentation
Id
uint8 FIoChunkId::Id[12] private
Definition at line 155 of file IoChunkId.h.
Referenced by GetChunkType(), GetData(), GetSize(), GetTypeHash, LexToString, operator<(), operator<<, operator==(), operator>(), Set(), and Set().
InvalidChunkId
const FIoChunkId FIoChunkId::InvalidChunkId static
Definition at line 66 of file IoChunkId.h.
Referenced by IsValid().
The documentation for this class was generated from the following file:
Runtime/Core/Public/IO/IoChunkId.h