Unreal Engine 5.6 C++ API: FRenderCommandPipe Class Reference
FRenderCommandPipe Class Reference
#include "RenderingThread.h"
Data Structures
struct FCommand
struct FFrame
Public Types
using FCommandListFunction = TUniqueFunction<void(FRHICommandList&)>
using FEmptyFunction = TUniqueFunction<void()>
Public Member Functions
RENDERCORE_API FRenderCommandPipe (const TCHAR *Name, ERenderCommandPipeFlags Flags, const TCHAR *CVarName, const TCHAR *CVarDescription)
RENDERCORE_API ~FRenderCommandPipe ()
FORCEINLINE const TCHAR * GetName () const
FORCEINLINE bool IsEmpty () const
FORCEINLINE bool IsRecording () const
FORCEINLINE bool IsReplaying () const
void SetEnabled (bool bInIsEnabled)
Static Public Member Functions
template<typename RenderCommandTag>
static void Enqueue (FRenderCommandPipe &Pipe, FCommandListFunction &&Function)
template<typename RenderCommandTag>
static void Enqueue (FRenderCommandPipe &Pipe, FEmptyFunction &&Function)
template<typename RenderCommandTag>
static void Enqueue (FRenderCommandPipe *Pipe, FCommandListFunction &&Function)
template<typename RenderCommandTag>
static void Enqueue (FRenderCommandPipe *Pipe, FEmptyFunction &&Function)
template<typename RenderCommandTag, typename LambdaType>
static FORCEINLINE void Enqueue (LambdaType &&Lambda)
Private Types
using FFunctionVariant = TVariant<FEmptyFunction, FCommandListFunction>
Private Member Functions
void EnqueueAndLaunch (FCommandListFunction &&Function, const TCHAR *CommandName, uint32 &CommandSpecId)
void EnqueueAndLaunch (FEmptyFunction &&Function, const TCHAR *CommandName, uint32 &CommandSpecId)
RENDERCORE_API void EnqueueAndLaunch (FFunctionVariant &&FunctionVariant, const TCHAR *Name, uint32 &SpecId)
void ExecuteCommand (FCommandListFunction &&Function, const TCHAR *CommandName, uint32 &CommandSpecId)
void ExecuteCommand (FEmptyFunction &&Function, const TCHAR *CommandName, uint32 &CommandSpecId)
RENDERCORE_API void ExecuteCommand (FFunctionVariant &&FunctionVariant, const TCHAR *CommandName, uint32 &CommandSpecId)
Private Attributes
bool bEnabled = true
bool bRecording = false
FAutoConsoleVariable ConsoleVariable
FFrame * Frame_GameThread = nullptr
FFrame * Frame_RenderThread = nullptr
TLinkedList< FRenderCommandPipe * > GlobalListLink
uint16 Index = uint16(-1)
UE::FMutex Mutex
const TCHAR * Name
std::atomic_int32_t NumInFlightCommands { 0 }
Friends
class FRenderCommandPipeRegistry
Detailed Description
Definition at line 404 of file RenderingThread.h.
Member Typedef Documentation
FCommandListFunction
using FRenderCommandPipe::FCommandListFunction = TUniqueFunction<void(FRHICommandList&)>
Definition at line 407 of file RenderingThread.h.
FEmptyFunction
using FRenderCommandPipe::FEmptyFunction = TUniqueFunction<void()>
Definition at line 408 of file RenderingThread.h.
FFunctionVariant
using FRenderCommandPipe::FFunctionVariant = TVariant<FEmptyFunction, FCommandListFunction> private
Definition at line 513 of file RenderingThread.h.
Constructor & Destructor Documentation
FRenderCommandPipe()
RENDERCORE_API FRenderCommandPipe::FRenderCommandPipe (const TCHAR * Name, ERenderCommandPipeFlags Flags, const TCHAR * CVarName, const TCHAR * CVarDescription)
References Flags, and Name.
Referenced by Enqueue(), Enqueue(), Enqueue(), and Enqueue().
~FRenderCommandPipe()
RENDERCORE_API FRenderCommandPipe::~FRenderCommandPipe ()
Member Function Documentation
Enqueue() [1/5]
template<typename RenderCommandTag> void FRenderCommandPipe::Enqueue (FRenderCommandPipe & Pipe, FCommandListFunction && Function) inline static
Definition at line 469 of file RenderingThread.h.
References FRenderCommandPipe(), Enqueue(), Function, and MoveTemp().
Enqueue() [2/5]
template<typename RenderCommandTag> void FRenderCommandPipe::Enqueue (FRenderCommandPipe & Pipe, FEmptyFunction && Function) inline static
Definition at line 499 of file RenderingThread.h.
References FRenderCommandPipe(), Enqueue(), Function, and MoveTemp().
Enqueue() [3/5]
template<typename RenderCommandTag> void FRenderCommandPipe::Enqueue (FRenderCommandPipe * Pipe, FCommandListFunction && Function) inline static
Definition at line 441 of file RenderingThread.h.
References FRenderCommandPipe(), All, EnqueueAndLaunch(), EnqueueUniqueRenderCommand(), ExecuteCommand(), Frame_GameThread, Function, GRenderCommandPipeMode, IsInRenderingThread(), UE::RenderCommandPipe::IsReplaying(), MoveTemp(), Mutex, and WITH_STATE_STREAM.
Referenced by Enqueue(), and Enqueue().
Enqueue() [4/5]
template<typename RenderCommandTag> void FRenderCommandPipe::Enqueue (FRenderCommandPipe * Pipe, FEmptyFunction && Function) inline static
Definition at line 475 of file RenderingThread.h.
References FRenderCommandPipe(), All, EnqueueAndLaunch(), EnqueueUniqueRenderCommand(), ExecuteCommand(), Frame_GameThread, Function, GRenderCommandPipeMode, UE::RenderCommandPipe::IsReplaying(), MoveTemp(), and Mutex.
Enqueue() [5/5]
template<typename RenderCommandTag, typename LambdaType> FORCEINLINE void FRenderCommandPipe::Enqueue (LambdaType && Lambda) inline static
Definition at line 505 of file RenderingThread.h.
References EnqueueUniqueRenderCommand(), FORCEINLINE, and MoveTemp().
EnqueueAndLaunch() [1/3]
void FRenderCommandPipe::EnqueueAndLaunch (FCommandListFunction && Function, const TCHAR * CommandName, uint32 & CommandSpecId) inline private
Definition at line 517 of file RenderingThread.h.
References EnqueueAndLaunch(), Function, and MoveTemp().
EnqueueAndLaunch() [2/3]
void FRenderCommandPipe::EnqueueAndLaunch (FEmptyFunction && Function, const TCHAR * CommandName, uint32 & CommandSpecId) inline private
Definition at line 522 of file RenderingThread.h.
References EnqueueAndLaunch(), Function, and MoveTemp().
EnqueueAndLaunch() [3/3]
RENDERCORE_API void FRenderCommandPipe::EnqueueAndLaunch (FFunctionVariant && FunctionVariant, const TCHAR * Name, uint32 & SpecId) private
References Name.
Referenced by Enqueue(), Enqueue(), EnqueueAndLaunch(), and EnqueueAndLaunch().
ExecuteCommand() [1/3]
void FRenderCommandPipe::ExecuteCommand (FCommandListFunction && Function, const TCHAR * CommandName, uint32 & CommandSpecId) inline private
Definition at line 529 of file RenderingThread.h.
References ExecuteCommand(), Function, and MoveTemp().
ExecuteCommand() [2/3]
void FRenderCommandPipe::ExecuteCommand (FEmptyFunction && Function, const TCHAR * CommandName, uint32 & CommandSpecId) inline private
Definition at line 534 of file RenderingThread.h.
References ExecuteCommand(), Function, and MoveTemp().
ExecuteCommand() [3/3]
RENDERCORE_API void FRenderCommandPipe::ExecuteCommand (FFunctionVariant && FunctionVariant, const TCHAR * CommandName, uint32 & CommandSpecId) private
Referenced by Enqueue(), Enqueue(), ExecuteCommand(), and ExecuteCommand().
GetName()
FORCEINLINE const TCHAR * FRenderCommandPipe::GetName () const inline
Definition at line 413 of file RenderingThread.h.
References FORCEINLINE, and Name.
IsEmpty()
FORCEINLINE bool FRenderCommandPipe::IsEmpty () const inline
Definition at line 429 of file RenderingThread.h.
References FORCEINLINE, and NumInFlightCommands.
IsRecording()
FORCEINLINE bool FRenderCommandPipe::IsRecording () const inline
Definition at line 424 of file RenderingThread.h.
References bRecording, and FORCEINLINE.
IsReplaying()
FORCEINLINE bool FRenderCommandPipe::IsReplaying () const inline
Definition at line 418 of file RenderingThread.h.
References ensure, FORCEINLINE, Frame_RenderThread, and IsInParallelRenderingThread().
SetEnabled()
void FRenderCommandPipe::SetEnabled (bool bInIsEnabled) inline
Definition at line 434 of file RenderingThread.h.
References bEnabled, check, and IsInGameThread().
Friends And Related Symbol Documentation
FRenderCommandPipeRegistry
friend class FRenderCommandPipeRegistry friend
Definition at line 511 of file RenderingThread.h.
References FRenderCommandPipeRegistry.
Referenced by FRenderCommandPipeRegistry.
Field Documentation
bEnabled
bool FRenderCommandPipe::bEnabled = true private
Definition at line 574 of file RenderingThread.h.
Referenced by SetEnabled().
bRecording
bool FRenderCommandPipe::bRecording = false private
Definition at line 573 of file RenderingThread.h.
Referenced by IsRecording().
ConsoleVariable
FAutoConsoleVariable FRenderCommandPipe::ConsoleVariable private
Definition at line 570 of file RenderingThread.h.
Frame_GameThread
FFrame* FRenderCommandPipe::Frame_GameThread = nullptr private
Definition at line 567 of file RenderingThread.h.
Referenced by Enqueue(), and Enqueue().
Frame_RenderThread
FFrame* FRenderCommandPipe::Frame_RenderThread = nullptr private
Definition at line 568 of file RenderingThread.h.
Referenced by IsReplaying().
GlobalListLink
TLinkedList<FRenderCommandPipe*> FRenderCommandPipe::GlobalListLink private
Definition at line 569 of file RenderingThread.h.
Index
uint16 FRenderCommandPipe::Index = uint16(-1) private
Definition at line 572 of file RenderingThread.h.
Mutex
UE::FMutex FRenderCommandPipe::Mutex private
Definition at line 566 of file RenderingThread.h.
Referenced by Enqueue(), and Enqueue().
Name
const TCHAR* FRenderCommandPipe::Name private
Definition at line 565 of file RenderingThread.h.
Referenced by FRenderCommandPipe(), EnqueueAndLaunch(), and GetName().
NumInFlightCommands
std::atomic_int32_t FRenderCommandPipe::NumInFlightCommands { 0 } private
Definition at line 571 of file RenderingThread.h.
Referenced by IsEmpty().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderingThread.h