Unreal Engine 5.6 C++ API: Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase Class Reference
Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase Class Reference
#include "MetasoundInputNode.h"
Public Member Functions
virtual METASOUNDFRONTEND_API void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual METASOUNDFRONTEND_API void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
virtual METASOUNDFRONTEND_API IOperator::FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual METASOUNDFRONTEND_API IOperator::FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual METASOUNDFRONTEND_API IOperator::FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Protected Member Functions
METASOUNDFRONTEND_API FNonExecutableInputOperatorBase (const FVertexName &InVertexName, FAnyDataReference &&InDataRef)
Protected Attributes
FAnyDataReference DataRef
FVertexName VertexName
Additional Inherited Members
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Detailed Description
Definition at line 23 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
FNonExecutableInputOperatorBase()
METASOUNDFRONTEND_API Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::FNonExecutableInputOperatorBase (const FVertexName & InVertexName, FAnyDataReference && InDataRef) protected
References UE_API.
Referenced by Metasound::MetasoundInputNodePrivate::FNonExecutableInputPassThroughOperator::FNonExecutableInputPassThroughOperator(), Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >::TInputValueOperator(), Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >::TInputValueOperator(), and Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >::TInputValueOperator().
Member Function Documentation
BindInputs()
virtual METASOUNDFRONTEND_API void Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::BindInputs (FInputVertexInterfaceData & InVertexData) override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
References UE_API.
BindOutputs()
virtual METASOUNDFRONTEND_API void Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::BindOutputs (FOutputVertexInterfaceData & InVertexData) override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
References UE_API.
GetExecuteFunction()
virtual METASOUNDFRONTEND_API IOperator::FExecuteFunction Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::GetExecuteFunction () override virtual
Return the execution function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be executed.
Implements Metasound::IOperator.
References UE_API.
GetPostExecuteFunction()
virtual METASOUNDFRONTEND_API IOperator::FPostExecuteFunction Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::GetPostExecuteFunction () override virtual
Return the FPostExecute function to call during graph post execution.
The IOperator* argument to the FPostExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be post executed.
Implements Metasound::IOperator.
References UE_API.
GetResetFunction()
virtual METASOUNDFRONTEND_API IOperator::FResetFunction Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::GetResetFunction () override virtual
Return the reset function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be reset.
Implements Metasound::IOperator.
References UE_API.
Field Documentation
DataRef
FAnyDataReference Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::DataRef protected
Definition at line 37 of file MetasoundInputNode.h.
VertexName
FVertexName Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::VertexName protected
Definition at line 36 of file MetasoundInputNode.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundInputNode.h