Unreal Engine 5.6 C++ API: TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... > Class Template Reference
TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Member Functions
template<typename InFunctorType, typename... InVarTypes>
TWeakBaseFunctorDelegateInstance (UserClass *InContextObject, InFunctorType &&InFunctor, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst InContextObject) const final
bool IsCompactable () const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
using UserClass = std::conditional_t<sizeof...(ParamTypes) == 0, const UObject, const UObject>
Private Attributes
TWeakObjectPtr< UserClass > ContextObject
std::remove_const_t< FunctorType > Functor
Additional Inherited Members
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Detailed Description
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes>
class TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >
Definition at line 907 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 913 of file DelegateInstancesImpl.h.
Super
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 912 of file DelegateInstancesImpl.h.
UserClass
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::UserClass = std::conditional_t<sizeof...(ParamTypes) == 0, const UObject, const UObject> private
Definition at line 917 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TWeakBaseFunctorDelegateInstance()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> template<typename InFunctorType, typename... InVarTypes> TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::TWeakBaseFunctorDelegateInstance (UserClass * InContextObject, InFunctorType && InFunctor, InVarTypes &&... Vars) inline explicit
Definition at line 921 of file DelegateInstancesImpl.h.
References ContextObject, Forward(), and Functor.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 987 of file DelegateInstancesImpl.h.
References TWeakBaseFunctorDelegateInstance().
CreateCopy() [2/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 992 of file DelegateInstancesImpl.h.
References TWeakBaseFunctorDelegateInstance().
CreateCopy() [3/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 982 of file DelegateInstancesImpl.h.
References TWeakBaseFunctorDelegateInstance().
Execute()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> RetValType TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 997 of file DelegateInstancesImpl.h.
References Forward(), Functor, Params, and TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload.
ExecuteIfSafe()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 1002 of file DelegateInstancesImpl.h.
References ContextObject, Forward(), Functor, IsInGameThread(), Params, and TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload.
GetBoundProgramCounterForTimerManager()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> uint64 TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 949 of file DelegateInstancesImpl.h.
GetObjectForTimerManager()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> const void * TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 944 of file DelegateInstancesImpl.h.
References ContextObject.
GetUObject()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> UObject * TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetUObject () const inline final
Definition at line 939 of file DelegateInstancesImpl.h.
References ContextObject.
Referenced by HasSameObject().
HasSameObject()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::HasSameObject (FDelegateUserObjectConst InContextObject) const inline final
Definition at line 955 of file DelegateInstancesImpl.h.
References ContextObject, and GetUObject().
IsCompactable()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::IsCompactable () const inline final
Definition at line 966 of file DelegateInstancesImpl.h.
References ContextObject.
IsSafeToExecute()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 975 of file DelegateInstancesImpl.h.
References ContextObject.
Field Documentation
ContextObject
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> TWeakObjectPtr<UserClass> TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ContextObject private
Definition at line 1016 of file DelegateInstancesImpl.h.
Referenced by TWeakBaseFunctorDelegateInstance(), ExecuteIfSafe(), GetObjectForTimerManager(), GetUObject(), HasSameObject(), IsCompactable(), and IsSafeToExecute().
Functor
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> std::remove_const_t<FunctorType> TWeakBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Functor mutable private
Definition at line 1022 of file DelegateInstancesImpl.h.
Referenced by TWeakBaseFunctorDelegateInstance(), Execute(), and ExecuteIfSafe().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstancesImpl.h