Unreal Engine 5.6 C++ API: Metasound::Frontend::TAccessPtr< Type > Class Template Reference
Metasound::Frontend::TAccessPtr< Type > Class Template Reference
TAccessPtr.
#include "MetasoundAccessPtr.h"
Public Types
using FTokenType = FAccessToken
using ObjectType = Type
Public Member Functions
TAccessPtr ()
template<typename OtherType>
TAccessPtr (const TAccessPtr< OtherType > &InOther, EConstCast InTag)
Creates an access pointer from another using a const casts.
template<typename OtherType UE_REQUIRES>
TAccessPtr (const TAccessPtr< OtherType > &InOther, EDerivedCopy InTag=EDerivedCopy::Tag)
Creates an access pointer from another using a static cast.
TAccessPtr (const TAccessPtr< Type > &InOther)=default
TAccessPtr (TAccessPtr< Type > &&InOther)=default
TAccessPtr (TWeakPtr< FTokenType > AccessToken, Type &InRef)
Creates a access pointer using an access token.
Type * Get () const
Returns a pointer to the accessible object.
template<typename AccessPtrType, typename FunctionType>
AccessPtrType GetMemberAccessPtr (FunctionType InGetMember) const
Returns an access pointer to a member of the wrapped object.
TAccessPtr< Type > & operator= (const TAccessPtr< Type > &InOther)=default
TAccessPtr & operator= (TAccessPtr< Type > &&InOther)=default
Static Public Attributes
static Type FallbackObject
Protected Member Functions
TAccessPtr (TFunction< Type *()> InGetObject)
Protected Attributes
Type * CachedObjectPtr = nullptr
TFunction< Type *()> GetObject
Private Types
enum class EConstCast { Tag }
enum class EDerivedCopy { Tag }
Friends
template<typename OtherType>
class TAccessPtr
template<typename ToAccessPtrType, typename FromAccessPtrType>
ToAccessPtrType ConstCastAccessPtr (const FromAccessPtrType &InAccessPtr)
template<typename RelatedAccessPtrType, typename RelatedType>
RelatedAccessPtrType MakeAccessPtr (const FAccessPoint &InAccessPoint, RelatedType &InRef)
Detailed Description
template<typename Type>
class Metasound::Frontend::TAccessPtr< Type >
TAccessPtr.
TAccessPtr is used to determine whether an object has been destructed or not. It is useful when an object cannot be wrapped in a TSharedPtr. A TAccessPtr is functionally similar to a TWeakPtr, but it cannot pin the object. In order to determine whether an object as accessible, the TAccessPtr executes a TFunctions<> which returns object. If a nullptr is returned, then the object is not accessible.
Object pointers held within a TAccessPtr must only be accessed on the thread where the objects gets destructed to avoid having the object destructed while in use.
If the TAccessPtr's underlying object is accessed when the pointer is invalid, a fallback object will be returned.
Template Parameters
Type - The type of object to track.
Definition at line 50 of file MetasoundAccessPtr.h.
Member Typedef Documentation
FTokenType
template<typename Type> using Metasound::Frontend::TAccessPtr< Type >::FTokenType = FAccessToken
Definition at line 56 of file MetasoundAccessPtr.h.
ObjectType
template<typename Type> using Metasound::Frontend::TAccessPtr< Type >::ObjectType = Type
Definition at line 57 of file MetasoundAccessPtr.h.
Member Enumeration Documentation
EConstCast
template<typename Type> enum class Metasound::Frontend::TAccessPtr::EConstCast strong private
Enumerator
Tag
Definition at line 52 of file MetasoundAccessPtr.h.
EDerivedCopy
template<typename Type> enum class Metasound::Frontend::TAccessPtr::EDerivedCopy strong private
Enumerator
Tag
Definition at line 53 of file MetasoundAccessPtr.h.
Constructor & Destructor Documentation
TAccessPtr() [1/7]
template<typename Type> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr () inline
Definition at line 98 of file MetasoundAccessPtr.h.
TAccessPtr() [2/7]
template<typename Type> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr (TWeakPtr< FTokenType > AccessToken, Type & InRef) inline
Creates a access pointer using an access token.
Definition at line 107 of file MetasoundAccessPtr.h.
TAccessPtr() [3/7]
template<typename Type> template<typename OtherType> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr (const TAccessPtr< OtherType > & InOther, EConstCast InTag) inline
Creates an access pointer from another using a const casts.
Definition at line 128 of file MetasoundAccessPtr.h.
TAccessPtr() [4/7]
template<typename Type> template<typename OtherType UE_REQUIRES> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr (const TAccessPtr< OtherType > & InOther, EDerivedCopy InTag = EDerivedCopy::Tag) inline
Creates an access pointer from another using a static cast.
Definition at line 144 of file MetasoundAccessPtr.h.
TAccessPtr() [5/7]
template<typename Type> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr (const TAccessPtr< Type > & InOther) default
TAccessPtr() [6/7]
template<typename Type> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr (TAccessPtr< Type > && InOther) default
TAccessPtr() [7/7]
template<typename Type> Metasound::Frontend::TAccessPtr< Type >::TAccessPtr (TFunction< Type *()> InGetObject) inline protected
Definition at line 177 of file MetasoundAccessPtr.h.
Member Function Documentation
Get()
template<typename Type> Type * Metasound::Frontend::TAccessPtr< Type >::Get () const inline
Returns a pointer to the accessible object.
If the object is inaccessible, a nullptr is returned.
Definition at line 64 of file MetasoundAccessPtr.h.
Referenced by Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), and Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr().
GetMemberAccessPtr()
template<typename Type> template<typename AccessPtrType, typename FunctionType> AccessPtrType Metasound::Frontend::TAccessPtr< Type >::GetMemberAccessPtr (FunctionType InGetMember) const inline
Returns an access pointer to a member of the wrapped object.
Template Parameters
AccessPtrType - The access pointer type to return.
FunctionType - A type which is callable accepts a reference to the wrapped object and returns a pointer to the member.
Parameters
InGetMember - A FunctionType accepts a reference to the wrapped object and returns a pointer to the member.
Definition at line 82 of file MetasoundAccessPtr.h.
operator=() [1/2]
template<typename Type> TAccessPtr< Type > & Metasound::Frontend::TAccessPtr< Type >::operator= (const TAccessPtr< Type > & InOther) default
operator=() [2/2]
template<typename Type> TAccessPtr & Metasound::Frontend::TAccessPtr< Type >::operator= (TAccessPtr< Type > && InOther) default
Friends And Related Symbol Documentation
TAccessPtr
template<typename Type> template<typename OtherType> friend class TAccessPtr friend
Definition at line 170 of file MetasoundAccessPtr.h.
ConstCastAccessPtr
template<typename Type> template<typename ToAccessPtrType, typename FromAccessPtrType> ToAccessPtrType ConstCastAccessPtr (const FromAccessPtrType & InAccessPtr) friend
Definition at line 233 of file MetasoundAccessPtr.h.
MakeAccessPtr
template<typename Type> template<typename RelatedAccessPtrType, typename RelatedType> RelatedAccessPtrType MakeAccessPtr (const FAccessPoint & InAccessPoint, RelatedType & InRef) friend
Field Documentation
CachedObjectPtr
template<typename Type> Type* Metasound::Frontend::TAccessPtr< Type >::CachedObjectPtr = nullptr mutable protected
Definition at line 173 of file MetasoundAccessPtr.h.
FallbackObject
template<typename Type> Type Metasound::Frontend::TAccessPtr< Type >::FallbackObject static
Definition at line 59 of file MetasoundAccessPtr.h.
GetObject
template<typename Type> TFunction<Type*()> Metasound::Frontend::TAccessPtr< Type >::GetObject protected
Definition at line 175 of file MetasoundAccessPtr.h.
Referenced by Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::TAccessPtr(), Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::Get(), and Metasound::Frontend::TAccessPtr< FMetasoundFrontendVertex >::GetMemberAccessPtr().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundAccessPtr.h