Unreal Engine 5.6 C++ API: ISequencer Class Reference
ISequencer Class Reference abstract
Interface for sequencers.
#include "ISequencer.h"
Public Member Functions
virtual TArray< FGuid > AddActors (const TArray< TWeakObjectPtr< AActor > > &InActors, bool bSelectActors=true)=0
Add actors as possessable objects to sequencer.
virtual FGuid AddEmptyBinding ()=0
Add a new empty binding to Sequencer which can be then connected to an object or actor afterwards in the binding properties menu.
virtual void AddNumericTypeInterface (TSharedRef< UE::Sequencer::FSequencerNumericTypeInterface > InNumericTypeInterface)=0
virtual void AddSubSequence (UMovieSceneSequence *Sequence)=0
Adds a movie scene as a section inside the current movie scene.
virtual bool CanKeyProperty (FCanKeyPropertyParams CanKeyPropertyParams) const =0
virtual void Close ()=0
Close the sequencer.
virtual TArray< FGuid > ConvertToSpawnable (FGuid Guid)=0
Convert the Possessable to a Spawnable.
FGuid CreateBinding (UMovieSceneSequence *InSequence, UObject *InObject) override
SEQUENCER_API FGuid CreateBinding (UObject &InObject, const FString &InName)
Create a new binding for the specified object, lightly deprecated and no longer virtual in favor of the overload with binding parameters.
virtual SEQUENCER_API FGuid CreateBinding (UObject &InObject, const UE::Sequencer::FCreateBindingParams &InParams)=0
Create a new binding for the specified object.
DECLARE_DELEGATE_RetVal (bool, FOnGetIsRecording) FOnGetIsRecording &OnGetIsRecording()
A delegate which will determine whether there is a recording in progress.
DECLARE_DELEGATE_RetVal (TArray< float >, FOnGetPlaybackSpeeds)
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetCanRecord, FText &OutInfoText) FOnGetCanRecord &OnGetCanRecord()
A delegate which will determine whether a recording is possible.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetIsBindingVisible, const FMovieSceneBinding &) FOnGetIsBindingVisible &OnGetIsBindingVisible()
A delegate which will determine whether a binding should be visible in the tree.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetIsTrackVisible, const UMovieSceneTrack *) FOnGetIsTrackVisible &OnGetIsTrackVisible()
A delegate which will determine whether a track should be visible in the tree.
DECLARE_DELEGATE_RetVal_TwoParams (bool, FOnCameraAddedToSequencer, ACameraActor *, FGuid) FOnCameraAddedToSequencer &OnCameraAddedToSequencer()
A delegate which will can be used in response to a camera being added to the sequence.
DECLARE_EVENT_OneParam (ISequencer, FOnActivateSequence, FMovieSceneSequenceIDRef) virtual FOnActivateSequence &OnActivateSequence()=0
DECLARE_EVENT_OneParam (ISequencer, FOnPostSave, ISequencer &) virtual FOnPostSave &OnPostSave()=0
DECLARE_EVENT_OneParam (ISequencer, FOnPreSave, ISequencer &) virtual FOnPreSave &OnPreSave()=0
DECLARE_EVENT_TwoParams (ISequencer, FOnCameraCut, UObject *, bool) virtual FOnCameraCut &OnCameraCut()=0
DECLARE_EVENT_TwoParams (ISequencer, FOnInitializeDetailsPanel, TSharedRef< IDetailsView >, TSharedRef< ISequencer >) FOnInitializeDetailsPanel &OnInitializeDetailsPanel()
DECLARE_MULTICAST_DELEGATE (FOnBeginScrubbingEvent)
DECLARE_MULTICAST_DELEGATE (FOnEndScrubbingEvent)
DECLARE_MULTICAST_DELEGATE (FOnGlobalTimeChanged)
DECLARE_MULTICAST_DELEGATE (FOnPlayEvent)
DECLARE_MULTICAST_DELEGATE (FOnRecordEvent)
DECLARE_MULTICAST_DELEGATE (FOnStopEvent)
DECLARE_MULTICAST_DELEGATE (FOnTreeViewChanged)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnCloseEvent, TSharedRef< ISequencer >)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMovieSceneBindingsPasted, const TArray< FMovieSceneBinding > &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMovieSceneDataChanged, EMovieSceneDataChangeType)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSelectionChangedObjectGuids, TArray< FGuid >)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSelectionChangedSections, TArray< UMovieSceneSection * >)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSelectionChangedTracks, TArray< UMovieSceneTrack * >)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnViewportSelectionLimitedChanged, const bool)
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnCurveDisplayChanged, FCurveModel *, bool, const FCurveEditor *)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnActorAddedToSequencer, AActor *, const FGuid)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnChannelChanged, const FMovieSceneChannelMetaData *MetaData, UMovieSceneSection *) DECLARE_MULTICAST_DELEGATE(FOnMovieSceneBindingsChanged)
virtual void EmptySelection ()=0
Empties the current selection.
virtual void EnterSilentMode ()=0
virtual void ExitSilentMode ()=0
virtual void ExternalSelectionHasChanged ()=0
Called when the external selection has changed in such a way that sequencer should re-synchronize its selection states.
TArrayView< TWeakObjectPtr<> > FindObjectsInCurrentSequence (const FGuid &InObjectBinding)
virtual UObject * FindSpawnedObjectOrTemplate (const FGuid &BindingId)=0
Attempt to find a spawned object in the currently focused movie scene, or the template object for the specified binding ID, if possible.
virtual UMovieSceneSubSection * FindSubSection (FMovieSceneSequenceID SequenceID) const =0
Attempt to locate the sub section that relates to the specified sequence ID.
virtual void FocusSequenceInstance (UMovieSceneSubSection &Section)=0
Focuses a sub-movie scene (MovieScene within a MovieScene) in the sequencer.
virtual void ForceEvaluate ()=0
Forcefully reevaluate the sequence immediately.
virtual EAllowEditsMode GetAllowEditsMode () const =0
virtual EAutoChangeMode GetAutoChangeMode () const =0
virtual bool GetAutoSetTrackDefaults () const =0
Gets whether or not property track defaults will be automatically set when adding tracks.
virtual void GetCameraObjectBindings (TArray< FGuid > &OutBindingIDs)
Gets the list of bindings for camera objects.
virtual TSharedPtr< FUICommandList > GetCommandBindings (ESequencerCommandBindings Type=ESequencerCommandBindings::Sequencer) const =0
virtual FOnCurveDisplayChanged & GetCurveDisplayChanged ()=0
Gets a multicast delegate when the curve edtior associated with this sequencer has it's selection change.
virtual bool GetCurveEditorIsVisible () const
virtual FText GetDisplayName (FGuid InBinding)=0
Get the Display Name of the Object Binding Track.
virtual SEQUENCER_API TSharedRef< ISequencerTrackFilters > GetFilterInterface () const =0
Gets the Sequencer filter interface used to manage filters.
SEQUENCER_API FFrameRate GetFocusedDisplayRate () const
Get the display rate of the currently focused sequence.
virtual UMovieSceneSequence * GetFocusedMovieSceneSequence () const =0
virtual FMovieSceneSequenceTransform GetFocusedMovieSceneSequenceTransform () const =0
virtual FMovieSceneSequenceIDRef GetFocusedTemplateID () const =0
SEQUENCER_API FFrameRate GetFocusedTickResolution () const
Get the tick resolution of the currently focused sequence.
virtual FMovieSceneSequenceTransform GetGlobalPlaybackWarpTransform () const =0
virtual FQualifiedFrameTime GetGlobalTime () const =0
Gets the global time.
virtual FGuid GetHandleToObject (UObject *Object, bool bCreateHandleIfMissing=true, const FName &CreatedFolderName=NAME_None)=0
Gets a handle to runtime information about the object being manipulated by a movie scene.
virtual const FSequencerHostCapabilities & GetHostCapabilities () const =0
virtual bool GetInfiniteKeyAreas () const =0
virtual FSequencerKeyCollection * GetKeyCollection ()=0
virtual EKeyGroupMode GetKeyGroupMode () const =0
virtual EMovieSceneKeyInterpolation GetKeyInterpolation () const =0
virtual void GetKeysFromSelection (TUniquePtr< FSequencerKeyCollection > &KeyCollection, float DuplicateThresoldTime)=0
Get all the keys for the current sequencer selection.
SEQUENCER_API TWeakObjectPtr< UCameraComponent > GetLastEvaluatedCameraCut () const
virtual FFrameTime GetLastEvaluatedLocalTime () const =0
Get the last evaluated time, which may be different form the current local time.
virtual TOptional< int32 > GetLocalLoopIndex () const =0
virtual FQualifiedFrameTime GetLocalTime () const =0
Gets the current time of the time slider relative to the currently focused movie scene.
virtual FMovieSceneSequenceTransform GetLocalTimeWarpTransform () const =0
virtual TArray< FMovieSceneMarkedFrame > GetMarkedFrames () const =0
virtual TSharedPtr< INumericTypeInterface< double > > GetNumericTypeInterface (UE::Sequencer::ENumericIntent Intent=UE::Sequencer::ENumericIntent::Position) const =0
virtual TArrayView< const TSharedRef< UE::Sequencer::FSequencerNumericTypeInterface > > GetNumericTypeInterfaces () const =0
virtual class ISequencerObjectChangeListener & GetObjectChangeListener ()=0
virtual TSharedPtr< UE::Sequencer::SOutlinerView > GetOutlinerViewWidget () const =0
virtual TRange< FFrameNumber > GetPlaybackRange () const =0
Get the playback range.
virtual float GetPlaybackSpeed () const =0
virtual EPropertyKeyedStatus GetPropertyKeyedStatus (const IPropertyHandle &PropertyHandle) const =0
virtual class ISequencerPropertyKeyedStatusHandler & GetPropertyKeyedStatusHandler ()=0
SEQUENCER_API FFrameRate GetRootDisplayRate () const
Get the display rate of the currently root sequence.
virtual UMovieSceneSequence * GetRootMovieSceneSequence () const =0
virtual FMovieSceneSequenceIDRef GetRootTemplateID () const =0
SEQUENCER_API FFrameRate GetRootTickResolution () const
Get the tick resolution of the currently root sequence.
virtual void GetSelectedFolders (TArray< UMovieSceneFolder * > &OutSelectedFolders)=0
Gets the currently selected folders.
virtual void GetSelectedKeyAreas (TArray< const IKeyArea * > &OutSelectedKeyAreas, bool bIncludeSelectedKeys=true)=0
Gets the currently selected key areas.
virtual void GetSelectedObjects (TArray< FGuid > &OutSelectedObjects)=0
Gets the currently selected Object Guids.
virtual void GetSelectedSections (TArray< UMovieSceneSection * > &OutSelectedSections)=0
Gets the currently selected sections.
virtual void GetSelectedTrackRows (TArray< TPair< UMovieSceneTrack *, int32 > > &OutSelectedTrackRows)=0
Gets the currently selected track rows.
virtual void GetSelectedTracks (TArray< UMovieSceneTrack * > &OutSelectedTracks)=0
Gets the currently selected tracks.
virtual FOnSelectionChangedObjectGuids & GetSelectionChangedObjectGuids ()=0
Gets a multicast delegate with an array of FGuid of bound objects which is called when the outliner node selection changes.
virtual FOnSelectionChangedSections & GetSelectionChangedSections ()=0
Gets a multicast delegate with an array of UMovieSceneSections which is called when the outliner node selection changes.
virtual FOnSelectionChangedTracks & GetSelectionChangedTracks ()=0
Gets a multicast delegate with an array of UMovieSceneTracks which is called when the outliner node selection changes.
virtual TRange< FFrameNumber > GetSelectionRange () const =0
Get the selection range.
virtual USequencerSettings * GetSequencerSettings () const =0
Getter for sequencer settings.
virtual TSharedRef< SWidget > GetSequencerWidget () const =0
virtual const TArray< FMovieSceneSequenceID > & GetSubSequenceHierarchy () const =0
virtual TOptional< TRange< FFrameNumber > > GetSubSequenceRange () const
Get the currently viewed sub sequence range.
virtual TArrayView< const TSubclassOf< UMovieSceneCustomBinding > > GetSupportedCustomBindingTypes () const
virtual TSharedPtr< IToolkitHost > GetToolkitHost () const =0
Returns the Toolkit hosting the sequencer instance, if any.
virtual TSharedPtr< class ITimeSlider > GetTopTimeSliderWidget () const =0
Get the top time slider from the main widget.
virtual TSharedPtr< ISequencerTrackEditor > GetTrackEditor (UMovieSceneTrack *InTrack)=0
Retrieve or create a track editor for the specified track.
virtual FQualifiedFrameTime GetUnwarpedLocalTime () const =0
Retrieve the current local time in unwarped space.
virtual TSharedPtr< UE::Sequencer::FSequencerEditorViewModel > GetViewModel () const =0
Retrieve the top level view model for this sequence.
virtual FAnimatedRange GetViewRange () const
virtual void InvalidateGlobalMarkedFramesCache ()=0
virtual bool IsAllowedToChange () const
virtual bool IsInSilentMode () const =0
virtual bool IsLevelEditorSequencer () const =0
virtual bool IsObjectSelectableInViewport (UObject *const InObject)=0
virtual bool IsPerspectiveViewportCameraCutEnabled () const
virtual bool IsPerspectiveViewportPossessionEnabled () const
virtual bool IsReadOnly () const =0
Whether the sequence is read-only.
virtual bool IsViewportSelectionLimited () const =0
virtual void KeyProperty (FKeyPropertyParams KeyPropertyParams)=0
virtual TSharedRef< IPropertyTypeCustomization > MakeFrameNumberDetailsCustomization ()=0
virtual FGuid MakeNewSpawnable (UObject &SourceObject, UActorFactory *ActorFactory=nullptr, bool bSetupDefaults=true)=0
Attempts to add a new spawnable to the MovieScene for the specified object (asset, class or actor instance)
virtual TSharedRef< SWidget > MakeTimeRange (const TSharedRef< SWidget > &InnerContent, bool bShowWorkingRange, bool bShowViewRange, bool bShowPlaybackRange)=0
Create a widget containing the spinboxes for setting the working and playback range.
virtual TSharedRef< SWidget > MakeTransportControls (bool bExtended)=0
virtual void NotifyMovieSceneDataChanged (EMovieSceneDataChangeType DataChangeType)=0
virtual void ObjectImplicitlyAdded (UObject *InObject) const =0
Specify that an object was implicitly added.
virtual void ObjectImplicitlyRemoved (UObject *InObject) const =0
Specify that an object was implicitly removed.
virtual FOnActorAddedToSequencer & OnActorAddedToSequencer ()=0
virtual void OnAddBinding (const FGuid &ObjectBinding, UMovieScene *MovieScene)=0
Should be called after adding a binding to the MovieScene.
virtual void OnAddTrack (const TWeakObjectPtr< UMovieSceneTrack > &InTrack, const FGuid &ObjectBinding)=0
Should be called after adding a track to the MovieScene.
virtual void OnBeginScrubbing ()=0
virtual FOnBeginScrubbingEvent & OnBeginScrubbingEvent ()=0
Gets a multicast delegate which is executed whenever the user begins scrubbing.
virtual FOnChannelChanged & OnChannelChanged ()=0
Gets a multicast delegate which is executed whenever a channel is changed by Sequencer.
virtual FOnCloseEvent & OnCloseEvent ()=0
virtual void OnEndScrubbing ()=0
virtual FOnEndScrubbingEvent & OnEndScrubbingEvent ()=0
Gets a multicast delegate which is executed whenever the user stops scrubbing.
virtual FFrameNumber OnGetNearestKey (FFrameTime InTime, ENearestKeyOption NearestKeyOption)=0
virtual FOnGlobalTimeChanged & OnGlobalTimeChanged ()=0
Gets a multicast delegate which is executed whenever the global time changes.
virtual FOnMovieSceneBindingsChanged & OnMovieSceneBindingsChanged ()=0
Gets a multicast delegate which is executed whenever the movie scene bindings are changed.
virtual FOnMovieSceneBindingsPasted & OnMovieSceneBindingsPasted ()=0
Gets a multicast delegate which is executed whenever bindings are pasted.
virtual FOnMovieSceneDataChanged & OnMovieSceneDataChanged ()=0
Gets a multicast delegate which is executed whenever the movie scene data is changed.
virtual FReply OnPlay (bool bTogglePlay=true)=0
Play or toggle playback at the specified play rate.
virtual FOnPlayEvent & OnPlayEvent ()=0
Gets a multicast delegate which is executed whenever the user begins playing the sequence.
virtual FOnRecordEvent & OnRecordEvent ()=0
Gets a multicast delegate which is executed whenever the user toggles recording.
virtual void OnScrubPositionChanged (FFrameTime NewScrubPosition, bool bScrubbing, bool bEvaluate)=0
virtual FOnStopEvent & OnStopEvent ()=0
Gets a multicast delegate which is executed whenever the user stops playing the sequence.
virtual FOnTreeViewChanged & OnTreeViewChanged ()=0
Gets a multicast delegate which is executed whenever the sequencer tree view changes, like when an object is added, or filtered from the view.
virtual FOnViewportSelectionLimitedChanged & OnViewportSelectionLimitedChanged ()=0
virtual UE::Sequencer::FTimeDomainOverride OverrideTimeDomain (UE::Sequencer::ETimeDomain NewDomain)=0
Temporarily override the behavior of a call to one of the SetLocalTime or OnScrubPositionChanged functions to operate in a specific time-domain.
virtual void Pause ()=0
Pause playback.
virtual void PlayTo (FMovieSceneSequencePlaybackParams PlaybackParams)=0
Play from the current time to the requested time.
virtual void PopToSequenceInstance (FMovieSceneSequenceIDRef SequenceID)=0
Pops the current focused movie scene from the stack.
virtual void RecreateCurveEditor ()
virtual void RefreshSupportedCustomBindingTypes ()
virtual void RefreshTree ()=0
Refresh the sequencer tree view.
virtual bool RegisterDrawer (FSidebarDrawerConfig &&InDrawerConfig)=0
Registers and displays a new drawer in the sidebar.
virtual bool RegisterDrawerSection (const FName InDrawerId, const TSharedPtr< ISidebarDrawerContent > &InSection)=0
Registers and displays a new drawer section in the sidebar.
virtual void RemoveNumericTypeInterface (TSharedRef< UE::Sequencer::FSequencerNumericTypeInterface > InNumericTypeInterface)=0
virtual void RenderMovie (const TArray< UMovieSceneCinematicShotSection * > &InSections) const =0
virtual void RequestEvaluate ()=0
Forcefully reevaluate the sequence on the next frame.
virtual void RequestInvalidateCachedData ()=0
Invalidate cached data so that it will be reevaluated on the next frame.
virtual void ResetTimeController ()=0
Reset the timing manager to the clock source specified by the root movie scene.
virtual void ResetToNewRootSequence (UMovieSceneSequence &NewAnimation)=0
Resets sequencer with a new animation.
virtual void RestorePlaybackSpeed ()=0
Restores the speed to 1.
virtual void Save ()=0
Saves the sequence content to the asset registry.
virtual void SelectByChannels (UMovieSceneSection *Section, const TArray< FName > &InChannelNames, bool bSelectParentInstead, bool bSelect)=0
Selects the nodes that relate to the specified channels.
virtual void SelectByChannels (UMovieSceneSection *Section, TArrayView< const FMovieSceneChannelHandle > InChannels, bool bSelectParentInstead, bool bSelect)=0
Selects the nodes that relate to the specified channels.
virtual void SelectByNthCategoryNode (UMovieSceneSection *Section, int Index, bool bSelect)=0
Selects nodes by the nth category node under a section.
virtual void SelectByPropertyPaths (const TArray< FString > &InPropertyPaths)=0
Selects property tracks by property path.
virtual void SelectFolder (UMovieSceneFolder *Folder)=0
Selects a folder.
virtual void SelectObject (FGuid ObjectBinding)=0
Selects an object by GUID.
virtual void SelectSection (UMovieSceneSection *Section)=0
Selects a section.
virtual void SelectTrack (UMovieSceneTrack *Track)=0
Selects a track.
virtual void SetAllowEditsMode (EAllowEditsMode AllowEditsMode)=0
Sets where edits are allowed.
virtual void SetAutoChangeMode (EAutoChangeMode AutoChangeMode)=0
SSets the current auto-change mode.
virtual void SetClampRange (TRange< double > NewClampRange)=0
Set the clamp range.
virtual void SetDisplayName (FGuid InBinding, const FText &InDisplayName)=0
Set the Display Name of the Object Binding Track.
virtual void SetGlobalTime (FFrameTime Time, bool bEvaluate=true)=0
Set the global time directly, without performing any auto-scroll, snapping or other adjustments to the supplied time.
virtual void SetInfiniteKeyAreas (bool bInfiniteKeyAreas)=0
Set infinite key area default.
virtual void SetKeyGroupMode (EKeyGroupMode Mode)=0
Sets which channels are keyed when a channel is keyed.
virtual void SetKeyInterpolation (EMovieSceneKeyInterpolation)=0
Set default key interpolation.
virtual void SetLocalTime (FFrameTime Time, ESnapTimeMode SnapTimeMode=ESnapTimeMode::STM_None, bool bEvaluate=true)=0
Sets the cursor position relative to the currently focused sequence.
virtual void SetLocalTimeDirectly (FFrameTime NewTime, bool bEvaluate=true)=0
Set the current local time directly, with no other snapping, scrolling or manipulation.
virtual void SetPerspectiveViewportCameraCutEnabled (bool bEnabled)=0
Sets whether perspective viewport camera cutting is enabled.
virtual void SetPerspectiveViewportPossessionEnabled (bool bEnabled)=0
Sets whether perspective viewport hijacking is enabled.
virtual void SetPlaybackSpeed (float InPlaybackSpeed)=0
virtual void SetSelectionRangeEnd (FFrameTime EndFrame)=0
Set the selection range's end position to the requested time.
virtual void SetSelectionRangeStart (FFrameTime StartFrame)=0
Set the selection range's start position to the requested time.
virtual void SetSequencerSettings (USequencerSettings *)=0
Setter for sequencer settings.
virtual void SetShowCurveEditor (bool bInShowCurveEditor)
Whether to show the curve editor or not.
virtual void SetViewportSelectionLimited (const bool bInSelectionLimited)=0
Turns on or off Sequencer selection limiting.
virtual void SetViewRange (TRange< double > NewViewRange, EViewRangeInterpolation Interpolation=EViewRangeInterpolation::Animated)=0
Set the view range, growing the working range to accomodate, if necessary.
virtual void SnapSequencerTime (FFrameTime &InOutScrubTime)=0
virtual void SnapToClosestPlaybackSpeed ()=0
Snaps to the closest available speed to the current one.
virtual void SuppressAutoEvaluation (UMovieSceneSequence *Sequence, const FGuid &InSignature)=0
Suppresses automatic evaluation the specified sequence and signature are the only difference that would prompt a re-evaluation.
virtual void ThrobKeySelection ()=0
Throb key or section selection.
virtual void ThrobSectionSelection ()=0
virtual bool TrackSupportsConditions (const UMovieSceneTrack *Track) const =0
UE_DEPRECATED (5.5, "GetTrackFilterNames() has been deprecated. Use GetFilterInterface()->GetFilterDisplayNames() instead.") virtual TArray< FText > GetTrackFilterNames() const =0
Gets all the available track filter names.
UE_DEPRECATED (5.5, "IsTrackFilterEnabled() has been deprecated. Use GetFilterInterface()->IsFilterActiveByDisplayName() instead.") virtual bool IsTrackFilterEnabled(const FText &InTrackFilterName) const =0
Gets whether the specified track filter is on/off.
UE_DEPRECATED (5.5, "SetTrackFilterEnabled() has been deprecated. Use GetFilterInterface()->SetFilterActiveByDisplayName() instead.") virtual void SetTrackFilterEnabled(const FText &InTrackFilterName
Sets the specified track filter to be on or off.
virtual bool UnregisterDrawer (const FName InDrawerId)=0
Unregisters and removes a drawer from the sidebar.
virtual bool UnregisterDrawerSection (const FName InDrawerId, const FName InSectionId)=0
Unregisters and removes a drawer section from the sidebar.
virtual void UpdatePlaybackRange ()=0
Public Member Functions inherited from IMovieScenePlayer
MOVIESCENE_API IMovieScenePlayer ()
virtual MOVIESCENE_API ~IMovieScenePlayer ()
void AddBindingOverride (const FMovieSceneEvaluationOperand &InOperand, const FMovieSceneEvaluationOperand &InOverrideOperand)
Adds an override for the given operand.
virtual UObject * AsUObject ()
Cast this player instance as a UObject if possible.
virtual UMovieSceneEntitySystemLinker * ConstructEntitySystemLinker ()
Called to retrieve or construct an entity linker for the specified playback context.
void DiscardPreAnimatedState ()
Discard all pre-animated state without restoring it.
MOVIESCENE_API TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FGuid &ObjectBindingID, FMovieSceneSequenceIDRef SequenceID)
Locate objects bound to the specified object guid, in the specified sequence.
TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FMovieSceneEvaluationOperand &Operand)
Locate objects bound to the specified sequence operand.
FGuid FindCachedObjectId (UObject &InObject, FMovieSceneSequenceIDRef SequenceID)
Attempt to find the object binding ID for the specified object, in the specified sequence.
FGuid FindObjectId (UObject &InObject, FMovieSceneSequenceIDRef SequenceID)
Attempt to find the object binding ID for the specified object, in the specified sequence.
MOVIESCENE_API TSharedPtr< UE::MovieScene::FSharedPlaybackState > FindSharedPlaybackState ()
Returns the evaluated sequence instance's shared playback state, if any.
MOVIESCENE_API TSharedPtr< const UE::MovieScene::FSharedPlaybackState > FindSharedPlaybackState () const
FMovieSceneEvaluationOperand * GetBindingOverride (const FMovieSceneEvaluationOperand &InOperand)
Retrieves any override for the given operand.
MOVIESCENE_API FMovieSceneEvaluationState * GetEvaluationState ()
Gets the evaluation state that stores global state to do with the playback operation.
virtual FMovieSceneRootEvaluationTemplateInstance & GetEvaluationTemplate ()=0
Access the evaluation template that we are playing back.
virtual MOVIESCENE_API TArray< UObject * > GetEventContexts () const
Access the event contexts for this movie scene player.
virtual TScriptInterface< IMovieSceneSequencePlayerObserver > GetObserver ()
virtual IMovieScenePlaybackClient * GetPlaybackClient ()
Access the client in charge of playback.
const IMovieScenePlaybackClient * GetPlaybackClient () const
virtual UObject * GetPlaybackContext () const
Access the playback context for this movie scene player.
MOVIESCENE_API TSharedRef< UE::MovieScene::FSharedPlaybackState > GetSharedPlaybackState ()
Returns the evaluated sequence instance's shared playback state, asserts if there is none.
MOVIESCENE_API TSharedRef< const UE::MovieScene::FSharedPlaybackState > GetSharedPlaybackState () const
virtual FMovieSceneSpawnRegister & GetSpawnRegister ()
Obtain an object responsible for managing movie scene spawnables.
MOVIESCENE_API UE::MovieScene::IStaticBindingOverridesPlaybackCapability * GetStaticBindingOverrides ()
Gets the list of binding overrides to use for the sequence.
uint16 GetUniqueIndex () const
virtual bool HasDynamicWeighting () const
Whether this player utilizes dynamic weighting.
virtual MOVIESCENE_API void InitializeRootInstance (TSharedRef< UE::MovieScene::FSharedPlaybackState > NewSharedPlaybackState)
Initializes a new root sequence instance and its shared playback state.
MOVIESCENE_API void InvalidateCachedData ()
Invalidate any cached state contained within this player causing all entities to be forcibly re-linked and evaluated.
virtual MOVIESCENE_API bool IsDisablingEventTriggers (FFrameTime &DisabledUntilTime) const
Returns whether event triggers are disabled and if so, until what time.
MOVIESCENE_API bool IsEvaluating () const
virtual bool IsPreview () const
Test whether this is a preview player or not.
virtual void NotifyBindingsChanged () override
Called whenever any object bindings have changed.
virtual void NotifyBindingUpdate (const FGuid &InGuid, FMovieSceneSequenceIDRef InSequenceID, TArrayView< TWeakObjectPtr<> > Objects) override
Called whenever an object binding has been resolved to give the player a chance to interact with the objects before they are animated.
virtual void OnObjectSpawned (UObject *InObject, const FMovieSceneEvaluationOperand &Operand)
UE_DEPRECATED(5.4, "Director instances are now automanaged via FSequenceDirectorPlaybackCapability") UObject *GetOrCreateDirectorInstance(TSharedRef< const UE virtual MOVIESCENE_API void PopulateUpdateFlags (UE::MovieScene::ESequenceInstanceUpdateFlags &OutFlags)
Gets a new or existing director blueprint instance for the given root or sub sequence.
virtual void PostEvaluation (const FMovieSceneContext &Context)
Called by the evaluation system after evaluation has occured.
virtual void PreEvaluation (const FMovieSceneContext &Context)
Called by the evaluation system when evaluation has just started.
void RemoveBindingOverride (const FMovieSceneEvaluationOperand &InOperand)
Removes any override set for the given operand.
virtual MOVIESCENE_API void ResolveBoundObjects (UE::UniversalObjectLocator::FResolveParams &ResolveParams, const FGuid &InBindingId, FMovieSceneSequenceID SequenceID, UMovieSceneSequence &Sequence, TArray< UObject *, TInlineAllocator< 1 > > &OutObjects) const
Resolve objects bound to the specified binding ID.
void RestorePreAnimatedState ()
Restore all pre-animated state.
FORCEINLINE void SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer &InProducer)
Attempt to save specific state for the specified token state before it mutates state.
FORCEINLINE void SavePreAnimatedState (UObject &InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer &InProducer)
Attempt to save specific state for the specified token state before it animates an object.
virtual void SetPlaybackStatus (EMovieScenePlayerStatus::Type InPlaybackStatus)=0
UE_DEPRECATED (5.4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance") virtual bool CanUpdateCameraCut() const
UE_DEPRECATED (5.4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance") virtual void UpdateCameraCut(UObject *CameraObject
UE_DEPRECATED (5.4, "Director instances are now automanaged via FSequenceDirectorPlaybackCapability") void ResetDirectorInstances()
Remove all director blueprint instances.
UE_DEPRECATED (5.4, "Please either call IMovieScenePlayer::FindBoundObjects, FMovieSceneObjectBindingID::ResolveBoundObjects, or FMovieSceneEvaluationState::FindBoundObjects") MOVIESCENE_API virtual void ResolveBoundObjects(const FGuid &InBindingId
Resolve objects bound to the specified binding ID.
UE_DEPRECATED (5.5, "Viewport settings management has moved to FViewportSettingsPlaybackCapability") virtual void SetViewportSettings(const TMap< FViewportClient *
UE_DEPRECATED (5.6, "Please use GetEvaluationState().") FMovieSceneEvaluationState State
Evaluation state that stores global state to do with the playback operation.
UE_DEPRECATED (5.6, "Please use GetStaticBindingOverrides().") TMap< FMovieSceneEvaluationOperand
List of binding overrides to use for the sequence.
Public Member Functions inherited from UE::MovieScene::IObjectBindingNotifyPlaybackCapability
UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API (MOVIESCENE_API, IObjectBindingNotifyPlaybackCapability) virtual void NotifyBindingsChanged()
Called when multiple object bindings have changed.
Public Member Functions inherited from TSharedFromThis< ISequencer >
TSharedRef< ISequencer, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< ISequencer, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
bool bEnabled = 0
Data Fields inherited from IMovieScenePlayer
FMovieSceneEvaluationOperand & BindingOverrides
UObject bool bJumpCut
FMovieSceneSequenceID UMovieSceneSequence UObject TArray< UObject *, TInlineAllocator< 1 > > &OutObjects const
FMovieScenePreAnimatedState PreAnimatedState
Container that stores any per-animated state tokens.
FMovieSceneSequenceID UMovieSceneSequence UObject * ResolutionContext
FMovieSceneSequenceID UMovieSceneSequence & Sequence
FMovieSceneSequenceID SequenceID
UObject * UnlockIfCameraObject = nullptr
EMovieSceneViewportParams & ViewportParamsMap
Protected Member Functions
virtual void NotifyMovieSceneDataChangedInternal ()=0
Protected Member Functions inherited from TSharedFromThis< ISequencer >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
FOnCameraAddedToSequencer CameraAddedToSequencer
FOnGetCanRecord GetCanRecord
FOnGetIsBindingVisible GetIsBindingVisible
FOnGetIsRecording GetIsRecording
FOnGetIsTrackVisible GetIsTrackVisible
FOnGetPlaybackSpeeds GetPlaybackSpeeds
FOnInitializeDetailsPanel InitializeDetailsPanelEvent
Additional Inherited Members
Static Public Member Functions inherited from IMovieScenePlayer
static MOVIESCENE_API void Get (TArray< IMovieScenePlayer * > &OutPlayers, bool bOnlyUnstoppedPlayers)
static MOVIESCENE_API IMovieScenePlayer * Get (uint16 InUniqueIndex)
static MOVIESCENE_API void SetIsEvaluatingFlag (uint16 InUniqueIndex, bool bIsUpdating)
Static Protected Member Functions inherited from TSharedFromThis< ISequencer >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Interface for sequencers.
Definition at line 218 of file ISequencer.h.
Member Function Documentation
AddActors()
virtual TArray< FGuid > ISequencer::AddActors (const TArray< TWeakObjectPtr< AActor > > & InActors, bool bSelectActors = true) pure virtual
Add actors as possessable objects to sequencer.
Parameters
InActors The actors to add to sequencer.
bSelectActors Select the newly added possessable objects in sequencer.
Returns
The posssessable guids for the newly added actors.
AddEmptyBinding()
virtual FGuid ISequencer::AddEmptyBinding () pure virtual
Add a new empty binding to Sequencer which can be then connected to an object or actor afterwards in the binding properties menu.
AddNumericTypeInterface()
virtual void ISequencer::AddNumericTypeInterface (TSharedRef< UE::Sequencer::FSequencerNumericTypeInterface > InNumericTypeInterface) pure virtual
AddSubSequence()
virtual void ISequencer::AddSubSequence (UMovieSceneSequence * Sequence) pure virtual
Adds a movie scene as a section inside the current movie scene.
Parameters
Sequence The sequence to add.
References IMovieScenePlayer::Sequence.
CanKeyProperty()
virtual bool ISequencer::CanKeyProperty (FCanKeyPropertyParams CanKeyPropertyParams) const pure virtual
Close()
virtual void ISequencer::Close () pure virtual
Close the sequencer.
ConvertToSpawnable()
virtual TArray< FGuid > ISequencer::ConvertToSpawnable (FGuid Guid) pure virtual
Convert the Possessable to a Spawnable.
Returns an array of Spawnable Id's
Parameters
Guid The Possessable Guid.
Returns
Array of Spawnable Guids
References Guid.
CreateBinding() [1/3]
FGuid ISequencer::CreateBinding (UMovieSceneSequence * InSequence, UObject * InObject) override virtual
Reimplemented from IMovieScenePlayer.
CreateBinding() [2/3]
SEQUENCER_API FGuid ISequencer::CreateBinding (UObject & InObject, const FString & InName)
Create a new binding for the specified object, lightly deprecated and no longer virtual in favor of the overload with binding parameters.
References IMovieScenePlayer::const, CreateBinding(), and InName.
CreateBinding() [3/3]
virtual SEQUENCER_API FGuid ISequencer::CreateBinding (UObject & InObject, const UE::Sequencer::FCreateBindingParams & InParams) pure virtual
Create a new binding for the specified object.
Referenced by CreateBinding().
DECLARE_DELEGATE_RetVal() [1/2]
ISequencer::DECLARE_DELEGATE_RetVal (bool , FOnGetIsRecording) & inline
A delegate which will determine whether there is a recording in progress.
Definition at line 623 of file ISequencer.h.
References GetIsRecording.
DECLARE_DELEGATE_RetVal() [2/2]
ISequencer::DECLARE_DELEGATE_RetVal (TArray< float > , FOnGetPlaybackSpeeds)
DECLARE_DELEGATE_RetVal_OneParam() [1/3]
ISequencer::DECLARE_DELEGATE_RetVal_OneParam (bool , FOnGetCanRecord , FText & OutInfoText) & inline
A delegate which will determine whether a recording is possible.
Definition at line 619 of file ISequencer.h.
References GetCanRecord.
DECLARE_DELEGATE_RetVal_OneParam() [2/3]
ISequencer::DECLARE_DELEGATE_RetVal_OneParam (bool , FOnGetIsBindingVisible , const FMovieSceneBinding &) & inline
A delegate which will determine whether a binding should be visible in the tree.
Definition at line 611 of file ISequencer.h.
References GetIsBindingVisible.
DECLARE_DELEGATE_RetVal_OneParam() [3/3]
ISequencer::DECLARE_DELEGATE_RetVal_OneParam (bool , FOnGetIsTrackVisible , const UMovieSceneTrack *) & inline
A delegate which will determine whether a track should be visible in the tree.
Definition at line 615 of file ISequencer.h.
References GetIsTrackVisible.
DECLARE_DELEGATE_RetVal_TwoParams()
ISequencer::DECLARE_DELEGATE_RetVal_TwoParams (bool , FOnCameraAddedToSequencer , ACameraActor * , FGuid) & inline
A delegate which will can be used in response to a camera being added to the sequence.
If true, the default behavior of locking the camera to the viewport and adding a camera cut will be executed
Definition at line 607 of file ISequencer.h.
References CameraAddedToSequencer.
DECLARE_EVENT_OneParam() [1/3]
ISequencer::DECLARE_EVENT_OneParam (ISequencer , FOnActivateSequence , FMovieSceneSequenceIDRef) & pure virtual
DECLARE_EVENT_OneParam() [2/3]
ISequencer::DECLARE_EVENT_OneParam (ISequencer , FOnPostSave , ISequencer &) & pure virtual
DECLARE_EVENT_OneParam() [3/3]
ISequencer::DECLARE_EVENT_OneParam (ISequencer , FOnPreSave , ISequencer &) & pure virtual
DECLARE_EVENT_TwoParams() [1/2]
ISequencer::DECLARE_EVENT_TwoParams (ISequencer , FOnCameraCut , UObject * , bool) & pure virtual
DECLARE_EVENT_TwoParams() [2/2]
ISequencer::DECLARE_EVENT_TwoParams (ISequencer , FOnInitializeDetailsPanel , TSharedRef< IDetailsView > , TSharedRef< ISequencer >) & inline
Definition at line 603 of file ISequencer.h.
References InitializeDetailsPanelEvent.
DECLARE_MULTICAST_DELEGATE() [1/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnBeginScrubbingEvent)
DECLARE_MULTICAST_DELEGATE() [2/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnEndScrubbingEvent)
DECLARE_MULTICAST_DELEGATE() [3/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnGlobalTimeChanged)
DECLARE_MULTICAST_DELEGATE() [4/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnPlayEvent)
DECLARE_MULTICAST_DELEGATE() [5/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnRecordEvent)
DECLARE_MULTICAST_DELEGATE() [6/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnStopEvent)
DECLARE_MULTICAST_DELEGATE() [7/7]
ISequencer::DECLARE_MULTICAST_DELEGATE (FOnTreeViewChanged)
DECLARE_MULTICAST_DELEGATE_OneParam() [1/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnCloseEvent , TSharedRef< ISequencer >)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnMovieSceneBindingsPasted , const TArray< FMovieSceneBinding > &)
DECLARE_MULTICAST_DELEGATE_OneParam() [3/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnMovieSceneDataChanged , EMovieSceneDataChangeType)
DECLARE_MULTICAST_DELEGATE_OneParam() [4/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnSelectionChangedObjectGuids , TArray< FGuid >)
DECLARE_MULTICAST_DELEGATE_OneParam() [5/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnSelectionChangedSections , TArray< UMovieSceneSection * >)
DECLARE_MULTICAST_DELEGATE_OneParam() [6/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnSelectionChangedTracks , TArray< UMovieSceneTrack * >)
DECLARE_MULTICAST_DELEGATE_OneParam() [7/7]
ISequencer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnViewportSelectionLimitedChanged , const bool)
DECLARE_MULTICAST_DELEGATE_ThreeParams()
ISequencer::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnCurveDisplayChanged , FCurveModel * , bool , const FCurveEditor *)
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/2]
ISequencer::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnActorAddedToSequencer , AActor * , const FGuid)
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/2]
ISequencer::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnChannelChanged , const FMovieSceneChannelMetaData * MetaData, UMovieSceneSection *)
References MetaData.
EmptySelection()
virtual void ISequencer::EmptySelection () pure virtual
Empties the current selection.
EnterSilentMode()
virtual void ISequencer::EnterSilentMode () pure virtual
ExitSilentMode()
virtual void ISequencer::ExitSilentMode () pure virtual
ExternalSelectionHasChanged()
virtual void ISequencer::ExternalSelectionHasChanged () pure virtual
Called when the external selection has changed in such a way that sequencer should re-synchronize its selection states.
FindObjectsInCurrentSequence()
TArrayView< TWeakObjectPtr<> > ISequencer::FindObjectsInCurrentSequence (const FGuid & InObjectBinding) inline
Definition at line 287 of file ISequencer.h.
References IMovieScenePlayer::FindBoundObjects(), and GetFocusedTemplateID().
FindSpawnedObjectOrTemplate()
virtual UObject * ISequencer::FindSpawnedObjectOrTemplate (const FGuid & BindingId) pure virtual
Attempt to find a spawned object in the currently focused movie scene, or the template object for the specified binding ID, if possible.
FindSubSection()
virtual UMovieSceneSubSection * ISequencer::FindSubSection (FMovieSceneSequenceID SequenceID) const pure virtual
Attempt to locate the sub section that relates to the specified sequence ID.
References IMovieScenePlayer::SequenceID.
FocusSequenceInstance()
virtual void ISequencer::FocusSequenceInstance (UMovieSceneSubSection & Section) pure virtual
Focuses a sub-movie scene (MovieScene within a MovieScene) in the sequencer.
Parameters
Section The sub-movie scene section containing the sequence instance to get.
ForceEvaluate()
virtual void ISequencer::ForceEvaluate () pure virtual
Forcefully reevaluate the sequence immediately.
GetAllowEditsMode()
virtual EAllowEditsMode ISequencer::GetAllowEditsMode () const pure virtual
Returns
Returns where edits are allowed.
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToHandle(), FKeyframeTrackEditor< TrackType >::AddKeysToObjects(), and IsAllowedToChange().
GetAutoChangeMode()
virtual EAutoChangeMode ISequencer::GetAutoChangeMode () const pure virtual
Returns
Returns the current auto-change mode.
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToHandle(), FKeyframeTrackEditor< TrackType >::AddKeysToObjects(), FKeyframeTrackEditor< TrackType >::AddKeysToSection(), and IsAllowedToChange().
GetAutoSetTrackDefaults()
virtual bool ISequencer::GetAutoSetTrackDefaults () const pure virtual
Gets whether or not property track defaults will be automatically set when adding tracks.
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToSection().
GetCameraObjectBindings()
virtual void ISequencer::GetCameraObjectBindings (TArray< FGuid > & OutBindingIDs) inline virtual
Gets the list of bindings for camera objects.
Parameters
OutBindingIDs The list of binding IDs for cameras
Definition at line 552 of file ISequencer.h.
GetCommandBindings()
virtual TSharedPtr< FUICommandList > ISequencer::GetCommandBindings (ESequencerCommandBindings Type = ESequencerCommandBindings::Sequencer) const pure virtual
Returns
the command bindings for this sequencer
References Sequencer.
GetCurveDisplayChanged()
virtual FOnCurveDisplayChanged & ISequencer::GetCurveDisplayChanged () pure virtual
Gets a multicast delegate when the curve edtior associated with this sequencer has it's selection change.
GetCurveEditorIsVisible()
virtual bool ISequencer::GetCurveEditorIsVisible () const inline virtual
Returns
If the curve editor is currently visible.
Definition at line 569 of file ISequencer.h.
GetDisplayName()
virtual FText ISequencer::GetDisplayName (FGuid InBinding) pure virtual
Get the Display Name of the Object Binding Track.
Parameters
InBinding the Binding of the Object
Returns
The name of the object binding track.
References GetDisplayName().
Referenced by GetDisplayName().
GetFilterInterface()
virtual SEQUENCER_API TSharedRef< ISequencerTrackFilters > ISequencer::GetFilterInterface () const pure virtual
Gets the Sequencer filter interface used to manage filters.
References IMovieScenePlayer::const, and GetFilterInterface().
Referenced by GetFilterInterface().
GetFocusedDisplayRate()
SEQUENCER_API FFrameRate ISequencer::GetFocusedDisplayRate () const
Get the display rate of the currently focused sequence.
References IMovieScenePlayer::const, and GetFocusedDisplayRate().
Referenced by GetFocusedDisplayRate().
GetFocusedMovieSceneSequence()
virtual UMovieSceneSequence * ISequencer::GetFocusedMovieSceneSequence () const pure virtual
Returns
Returns the MovieScene that is currently focused for editing by the sequencer. This can change at any time.
GetFocusedMovieSceneSequenceTransform()
virtual FMovieSceneSequenceTransform ISequencer::GetFocusedMovieSceneSequenceTransform () const pure virtual
Returns
Returns the time transform from the focused sequence back to the root
GetFocusedTemplateID()
virtual FMovieSceneSequenceIDRef ISequencer::GetFocusedTemplateID () const pure virtual
Referenced by Sequencer::AddKeyForExternalValue(), and FindObjectsInCurrentSequence().
GetFocusedTickResolution()
SEQUENCER_API FFrameRate ISequencer::GetFocusedTickResolution () const
Get the tick resolution of the currently focused sequence.
References IMovieScenePlayer::const, and GetFocusedTickResolution().
Referenced by GetFocusedTickResolution().
GetGlobalPlaybackWarpTransform()
virtual FMovieSceneSequenceTransform ISequencer::GetGlobalPlaybackWarpTransform () const pure virtual
Returns
Returns the timewrap transform that applies to global playback
GetGlobalTime()
virtual FQualifiedFrameTime ISequencer::GetGlobalTime () const pure virtual
Gets the global time.
Returns
Global time in seconds.
See also
SetGlobalTime
GetHandleToObject()
virtual FGuid ISequencer::GetHandleToObject (UObject * Object, bool bCreateHandleIfMissing = true, const FName & CreatedFolderName = NAME_None) pure virtual
Gets a handle to runtime information about the object being manipulated by a movie scene.
Parameters
Object The object to get a handle for.
bCreateHandleIfMissing Create a handle if it doesn't exist.
CreatedFolderName - The name of the folder to place the created objects in (if bCreateHandleIfMissing is true).
Returns
The handle to the object.
References Object.
GetHostCapabilities()
virtual const FSequencerHostCapabilities & ISequencer::GetHostCapabilities () const pure virtual
Returns
The capabilities of this sequencer host
GetInfiniteKeyAreas()
virtual bool ISequencer::GetInfiniteKeyAreas () const pure virtual
Returns
Returns whether key sections are infinite by default when created
GetKeyCollection()
virtual FSequencerKeyCollection * ISequencer::GetKeyCollection () pure virtual
GetKeyGroupMode()
virtual EKeyGroupMode ISequencer::GetKeyGroupMode () const pure virtual
Returns
Returns what channels will get keyed when one channel changes
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToSection().
GetKeyInterpolation()
virtual EMovieSceneKeyInterpolation ISequencer::GetKeyInterpolation () const pure virtual
Returns
Returns default key interpolation
Referenced by Sequencer::AddKeyForExternalValue(), FKeyframeTrackEditor< TrackType >::AddKeysToSection(), and Sequencer::AddOrUpdateKey().
GetKeysFromSelection()
virtual void ISequencer::GetKeysFromSelection (TUniquePtr< FSequencerKeyCollection > & KeyCollection, float DuplicateThresoldTime) pure virtual
Get all the keys for the current sequencer selection.
GetLastEvaluatedCameraCut()
SEQUENCER_API TWeakObjectPtr< UCameraComponent > ISequencer::GetLastEvaluatedCameraCut () const
Returns
The camera cut that was last used by a camera cut; it is the view that the sequence should have at the current time.
GetLastEvaluatedLocalTime()
virtual FFrameTime ISequencer::GetLastEvaluatedLocalTime () const pure virtual
Get the last evaluated time, which may be different form the current local time.
GetLocalLoopIndex()
virtual TOptional< int32 > ISequencer::GetLocalLoopIndex () const pure virtual
GetLocalTime()
virtual FQualifiedFrameTime ISequencer::GetLocalTime () const pure virtual
Gets the current time of the time slider relative to the currently focused movie scene.
GetLocalTimeWarpTransform()
virtual FMovieSceneSequenceTransform ISequencer::GetLocalTimeWarpTransform () const pure virtual
Returns
Returns the timewrap transform that local time to warped-local-time
GetMarkedFrames()
virtual TArray< FMovieSceneMarkedFrame > ISequencer::GetMarkedFrames () const pure virtual
GetNumericTypeInterface()
virtual TSharedPtr< INumericTypeInterface< double > > ISequencer::GetNumericTypeInterface (UE::Sequencer::ENumericIntent Intent = UE::Sequencer::ENumericIntent::Position) const pure virtual
Returns
a numeric type interface that will parse and display numbers as frame / time / bar.beat positions correctly
References UE::Sequencer::Position.
GetNumericTypeInterfaces()
virtual TArrayView< const TSharedRef< UE::Sequencer::FSequencerNumericTypeInterface > > ISequencer::GetNumericTypeInterfaces () const pure virtual
GetObjectChangeListener()
virtual class ISequencerObjectChangeListener & ISequencer::GetObjectChangeListener () pure virtual
Returns
Returns the object change listener for sequencer instance
Referenced by FPropertyTrackEditor< TrackType >::AddWatchedProperty().
GetOutlinerViewWidget()
virtual TSharedPtr< UE::Sequencer::SOutlinerView > ISequencer::GetOutlinerViewWidget () const pure virtual
GetPlaybackRange()
virtual TRange< FFrameNumber > ISequencer::GetPlaybackRange () const pure virtual
Get the playback range.
GetPlaybackSpeed()
virtual float ISequencer::GetPlaybackSpeed () const pure virtual
GetPropertyKeyedStatus()
virtual EPropertyKeyedStatus ISequencer::GetPropertyKeyedStatus (const IPropertyHandle & PropertyHandle) const pure virtual
GetPropertyKeyedStatusHandler()
virtual class ISequencerPropertyKeyedStatusHandler & ISequencer::GetPropertyKeyedStatusHandler () pure virtual
Returns
Returns the property keyed status handler for this sequencer instance
GetRootDisplayRate()
SEQUENCER_API FFrameRate ISequencer::GetRootDisplayRate () const
Get the display rate of the currently root sequence.
References IMovieScenePlayer::const, and GetRootDisplayRate().
Referenced by GetRootDisplayRate().
GetRootMovieSceneSequence()
virtual UMovieSceneSequence * ISequencer::GetRootMovieSceneSequence () const pure virtual
Returns
The root movie scene being used
GetRootTemplateID()
virtual FMovieSceneSequenceIDRef ISequencer::GetRootTemplateID () const pure virtual
Returns
The root movie scene being used
GetRootTickResolution()
SEQUENCER_API FFrameRate ISequencer::GetRootTickResolution () const
Get the tick resolution of the currently root sequence.
References IMovieScenePlayer::const, and GetRootTickResolution().
Referenced by GetRootTickResolution().
GetSelectedFolders()
virtual void ISequencer::GetSelectedFolders (TArray< UMovieSceneFolder * > & OutSelectedFolders) pure virtual
Gets the currently selected folders.
GetSelectedKeyAreas()
virtual void ISequencer::GetSelectedKeyAreas (TArray< const IKeyArea * > & OutSelectedKeyAreas, bool bIncludeSelectedKeys = true) pure virtual
Gets the currently selected key areas.
If bIncludeSelectedKeys is true it will include key areas for selected keys, if not will only include key areas for selected display nodes
GetSelectedObjects()
virtual void ISequencer::GetSelectedObjects (TArray< FGuid > & OutSelectedObjects) pure virtual
Gets the currently selected Object Guids.
GetSelectedSections()
virtual void ISequencer::GetSelectedSections (TArray< UMovieSceneSection * > & OutSelectedSections) pure virtual
Gets the currently selected sections.
GetSelectedTrackRows()
virtual void ISequencer::GetSelectedTrackRows (TArray< TPair< UMovieSceneTrack *, int32 > > & OutSelectedTrackRows) pure virtual
Gets the currently selected track rows.
GetSelectedTracks()
virtual void ISequencer::GetSelectedTracks (TArray< UMovieSceneTrack * > & OutSelectedTracks) pure virtual
Gets the currently selected tracks.
GetSelectionChangedObjectGuids()
virtual FOnSelectionChangedObjectGuids & ISequencer::GetSelectionChangedObjectGuids () pure virtual
Gets a multicast delegate with an array of FGuid of bound objects which is called when the outliner node selection changes.
GetSelectionChangedSections()
virtual FOnSelectionChangedSections & ISequencer::GetSelectionChangedSections () pure virtual
Gets a multicast delegate with an array of UMovieSceneSections which is called when the outliner node selection changes.
GetSelectionChangedTracks()
virtual FOnSelectionChangedTracks & ISequencer::GetSelectionChangedTracks () pure virtual
Gets a multicast delegate with an array of UMovieSceneTracks which is called when the outliner node selection changes.
GetSelectionRange()
virtual TRange< FFrameNumber > ISequencer::GetSelectionRange () const pure virtual
Get the selection range.
Returns
The selection range.
See also
SetSelectionRange, SetSelectionRangeEnd, SetSelectionRangeStart
GetSequencerSettings()
virtual USequencerSettings * ISequencer::GetSequencerSettings () const pure virtual
Getter for sequencer settings.
GetSequencerWidget()
virtual TSharedRef< SWidget > ISequencer::GetSequencerWidget () const pure virtual
Returns
Widget used to display the sequencer
GetSubSequenceHierarchy()
virtual const TArray< FMovieSceneSequenceID > & ISequencer::GetSubSequenceHierarchy () const pure virtual
GetSubSequenceRange()
virtual TOptional< TRange< FFrameNumber > > ISequencer::GetSubSequenceRange () const inline virtual
Get the currently viewed sub sequence range.
Returns
The sub sequence range, or an empty optional if we're viewing the root.
Definition at line 312 of file ISequencer.h.
References Optional.
GetSupportedCustomBindingTypes()
virtual TArrayView< const TSubclassOf< UMovieSceneCustomBinding > > ISequencer::GetSupportedCustomBindingTypes () const inline virtual
Definition at line 941 of file ISequencer.h.
References IMovieScenePlayer::const, and GetSupportedCustomBindingTypes().
Referenced by GetSupportedCustomBindingTypes().
GetToolkitHost()
virtual TSharedPtr< IToolkitHost > ISequencer::GetToolkitHost () const pure virtual
Returns the Toolkit hosting the sequencer instance, if any.
GetTopTimeSliderWidget()
virtual TSharedPtr< class ITimeSlider > ISequencer::GetTopTimeSliderWidget () const pure virtual
Get the top time slider from the main widget.
Returns
the widget
GetTrackEditor()
virtual TSharedPtr< ISequencerTrackEditor > ISequencer::GetTrackEditor (UMovieSceneTrack * InTrack) pure virtual
Retrieve or create a track editor for the specified track.
GetUnwarpedLocalTime()
virtual FQualifiedFrameTime ISequencer::GetUnwarpedLocalTime () const pure virtual
Retrieve the current local time in unwarped space.
This is usually only required for time-warp operations. Prefer GetLocalTime.
GetViewModel()
virtual TSharedPtr< UE::Sequencer::FSequencerEditorViewModel > ISequencer::GetViewModel () const pure virtual
Retrieve the top level view model for this sequence.
GetViewRange()
virtual FAnimatedRange ISequencer::GetViewRange () const virtual
Returns
The current view range
InvalidateGlobalMarkedFramesCache()
virtual void ISequencer::InvalidateGlobalMarkedFramesCache () pure virtual
IsAllowedToChange()
virtual bool ISequencer::IsAllowedToChange () const inline virtual
Returns
Returns whether sequencer will respond to changes and possibly create a key or track
Definition at line 427 of file ISequencer.h.
References GetAllowEditsMode(), GetAutoChangeMode(), and IsReadOnly().
IsInSilentMode()
virtual bool ISequencer::IsInSilentMode () const pure virtual
IsLevelEditorSequencer()
virtual bool ISequencer::IsLevelEditorSequencer () const pure virtual
Returns
Whether or not this sequencer is used in the level editor
IsObjectSelectableInViewport()
virtual bool ISequencer::IsObjectSelectableInViewport (UObject *const InObject) pure virtual
Returns
True if the specified object is selectable in the viewport and not made unselectable by the Sequencer selection limiting.
IsPerspectiveViewportCameraCutEnabled()
virtual bool ISequencer::IsPerspectiveViewportCameraCutEnabled () const inline virtual
Definition at line 545 of file ISequencer.h.
IsPerspectiveViewportPossessionEnabled()
virtual bool ISequencer::IsPerspectiveViewportPossessionEnabled () const inline virtual
Definition at line 533 of file ISequencer.h.
IsReadOnly()
virtual bool ISequencer::IsReadOnly () const pure virtual
Whether the sequence is read-only.
Referenced by IsAllowedToChange().
IsViewportSelectionLimited()
virtual bool ISequencer::IsViewportSelectionLimited () const pure virtual
Returns
True if the Sequencer is currently limiting viewport selection to only Sequencer objects.
KeyProperty()
virtual void ISequencer::KeyProperty (FKeyPropertyParams KeyPropertyParams) pure virtual
MakeFrameNumberDetailsCustomization()
virtual TSharedRef< IPropertyTypeCustomization > ISequencer::MakeFrameNumberDetailsCustomization () pure virtual
MakeNewSpawnable()
virtual FGuid ISequencer::MakeNewSpawnable (UObject & SourceObject, UActorFactory * ActorFactory = nullptr, bool bSetupDefaults = true) pure virtual
Attempts to add a new spawnable to the MovieScene for the specified object (asset, class or actor instance)
Parameters
Object The asset, class, or actor to add a spawnable for
ActorFactory Optional actor factory to use to create spawnable type
bSetupDefaults Setup default tracks for this spawnable
Returns
The spawnable guid for the spawnable, or an invalid Guid if we were not able to create a spawnable
MakeTimeRange()
virtual TSharedRef< SWidget > ISequencer::MakeTimeRange (const TSharedRef< SWidget > & InnerContent, bool bShowWorkingRange, bool bShowViewRange, bool bShowPlaybackRange) pure virtual
Create a widget containing the spinboxes for setting the working and playback range.
Parameters
InnerContent Inner content to be inserted to the middle of the widget (inbetween the playback range spinboxes)
Returns
the widget
MakeTransportControls()
virtual TSharedRef< SWidget > ISequencer::MakeTransportControls (bool bExtended) pure virtual
Returns
Returns a widget containing the sequencer's playback controls
NotifyMovieSceneDataChanged()
virtual void ISequencer::NotifyMovieSceneDataChanged (EMovieSceneDataChangeType DataChangeType) pure virtual
Referenced by FKeyframeTrackEditor< TrackType >::ClearDefaults().
NotifyMovieSceneDataChangedInternal()
virtual void ISequencer::NotifyMovieSceneDataChangedInternal () protected pure virtual
ObjectImplicitlyAdded()
virtual void ISequencer::ObjectImplicitlyAdded (UObject * InObject) const pure virtual
Specify that an object was implicitly added.
We will notify the track editors that it was @InObject Object that was added to be part of a track/binding but not the real binding
ObjectImplicitlyRemoved()
virtual void ISequencer::ObjectImplicitlyRemoved (UObject * InObject) const pure virtual
Specify that an object was implicitly removed.
We will notify the track editors that it was @InObject Object that was removed that was part of a track/binding but not the real binding
OnActorAddedToSequencer()
virtual FOnActorAddedToSequencer & ISequencer::OnActorAddedToSequencer () pure virtual
OnAddBinding()
virtual void ISequencer::OnAddBinding (const FGuid & ObjectBinding, UMovieScene * MovieScene) pure virtual
Should be called after adding a binding to the MovieScene.
OnAddTrack()
virtual void ISequencer::OnAddTrack (const TWeakObjectPtr< UMovieSceneTrack > & InTrack, const FGuid & ObjectBinding) pure virtual
Should be called after adding a track to the MovieScene.
This will set the specified track as your current selection cause it to throb, notify the sequence to rebuild any data required. The track will be added to the selected folder unless ObjectBinding points to a valid FGuid.
OnBeginScrubbing()
virtual void ISequencer::OnBeginScrubbing () pure virtual
OnBeginScrubbingEvent()
virtual FOnBeginScrubbingEvent & ISequencer::OnBeginScrubbingEvent () pure virtual
Gets a multicast delegate which is executed whenever the user begins scrubbing.
OnChannelChanged()
virtual FOnChannelChanged & ISequencer::OnChannelChanged () pure virtual
Gets a multicast delegate which is executed whenever a channel is changed by Sequencer.
OnCloseEvent()
virtual FOnCloseEvent & ISequencer::OnCloseEvent () pure virtual
Returns
a multicast delegate which is executed when sequencer closes.
OnEndScrubbing()
virtual void ISequencer::OnEndScrubbing () pure virtual
OnEndScrubbingEvent()
virtual FOnEndScrubbingEvent & ISequencer::OnEndScrubbingEvent () pure virtual
Gets a multicast delegate which is executed whenever the user stops scrubbing.
OnGetNearestKey()
virtual FFrameNumber ISequencer::OnGetNearestKey (FFrameTime InTime, ENearestKeyOption NearestKeyOption) pure virtual
References InTime.
OnGlobalTimeChanged()
virtual FOnGlobalTimeChanged & ISequencer::OnGlobalTimeChanged () pure virtual
Gets a multicast delegate which is executed whenever the global time changes.
OnMovieSceneBindingsChanged()
virtual FOnMovieSceneBindingsChanged & ISequencer::OnMovieSceneBindingsChanged () pure virtual
Gets a multicast delegate which is executed whenever the movie scene bindings are changed.
OnMovieSceneBindingsPasted()
virtual FOnMovieSceneBindingsPasted & ISequencer::OnMovieSceneBindingsPasted () pure virtual
Gets a multicast delegate which is executed whenever bindings are pasted.
OnMovieSceneDataChanged()
virtual FOnMovieSceneDataChanged & ISequencer::OnMovieSceneDataChanged () pure virtual
Gets a multicast delegate which is executed whenever the movie scene data is changed.
OnPlay()
virtual FReply ISequencer::OnPlay (bool bTogglePlay = true) pure virtual
Play or toggle playback at the specified play rate.
OnPlayEvent()
virtual FOnPlayEvent & ISequencer::OnPlayEvent () pure virtual
Gets a multicast delegate which is executed whenever the user begins playing the sequence.
OnRecordEvent()
virtual FOnRecordEvent & ISequencer::OnRecordEvent () pure virtual
Gets a multicast delegate which is executed whenever the user toggles recording.
OnScrubPositionChanged()
virtual void ISequencer::OnScrubPositionChanged (FFrameTime NewScrubPosition, bool bScrubbing, bool bEvaluate) pure virtual
OnStopEvent()
virtual FOnStopEvent & ISequencer::OnStopEvent () pure virtual
Gets a multicast delegate which is executed whenever the user stops playing the sequence.
OnTreeViewChanged()
virtual FOnTreeViewChanged & ISequencer::OnTreeViewChanged () pure virtual
Gets a multicast delegate which is executed whenever the sequencer tree view changes, like when an object is added, or filtered from the view.
OnViewportSelectionLimitedChanged()
virtual FOnViewportSelectionLimitedChanged & ISequencer::OnViewportSelectionLimitedChanged () pure virtual
Returns
Delegate executed when Sequencer selection limiting is enabled or disabled.
OverrideTimeDomain()
virtual UE::Sequencer::FTimeDomainOverride ISequencer::OverrideTimeDomain (UE::Sequencer::ETimeDomain NewDomain) nodiscard pure virtual
Temporarily override the behavior of a call to one of the SetLocalTime or OnScrubPositionChanged functions to operate in a specific time-domain.
Pause()
virtual void ISequencer::Pause () pure virtual
Pause playback.
PlayTo()
virtual void ISequencer::PlayTo (FMovieSceneSequencePlaybackParams PlaybackParams) pure virtual
Play from the current time to the requested time.
PopToSequenceInstance()
virtual void ISequencer::PopToSequenceInstance (FMovieSceneSequenceIDRef SequenceID) pure virtual
Pops the current focused movie scene from the stack.
The parent of this movie scene will be come the focused one
References IMovieScenePlayer::SequenceID.
RecreateCurveEditor()
virtual void ISequencer::RecreateCurveEditor () inline virtual
Definition at line 564 of file ISequencer.h.
RefreshSupportedCustomBindingTypes()
virtual void ISequencer::RefreshSupportedCustomBindingTypes () inline virtual
Definition at line 943 of file ISequencer.h.
RefreshTree()
virtual void ISequencer::RefreshTree () pure virtual
Refresh the sequencer tree view.
RegisterDrawer()
virtual bool ISequencer::RegisterDrawer (FSidebarDrawerConfig && InDrawerConfig) pure virtual
Registers and displays a new drawer in the sidebar.
Parameters
InDrawerConfig Configuration info for the new drawer
Returns
True if the new drawer registration was successful.
RegisterDrawerSection()
virtual bool ISequencer::RegisterDrawerSection (const FName InDrawerId, const TSharedPtr< ISidebarDrawerContent > & InSection) pure virtual
Registers and displays a new drawer section in the sidebar.
Parameters
InDrawerId Unique drawer Id to register
InSection Drawer content interface for the section
Returns
True if the new drawer section registration was successful.
RemoveNumericTypeInterface()
virtual void ISequencer::RemoveNumericTypeInterface (TSharedRef< UE::Sequencer::FSequencerNumericTypeInterface > InNumericTypeInterface) pure virtual
RenderMovie()
virtual void ISequencer::RenderMovie (const TArray< UMovieSceneCinematicShotSection * > & InSections) const pure virtual
RequestEvaluate()
virtual void ISequencer::RequestEvaluate () pure virtual
Forcefully reevaluate the sequence on the next frame.
RequestInvalidateCachedData()
virtual void ISequencer::RequestInvalidateCachedData () pure virtual
Invalidate cached data so that it will be reevaluated on the next frame.
ResetTimeController()
virtual void ISequencer::ResetTimeController () pure virtual
Reset the timing manager to the clock source specified by the root movie scene.
ResetToNewRootSequence()
virtual void ISequencer::ResetToNewRootSequence (UMovieSceneSequence & NewAnimation) pure virtual
Resets sequencer with a new animation.
RestorePlaybackSpeed()
virtual void ISequencer::RestorePlaybackSpeed () pure virtual
Restores the speed to 1.
Save()
virtual void ISequencer::Save () pure virtual
Saves the sequence content to the asset registry.
SelectByChannels() [1/2]
virtual void ISequencer::SelectByChannels (UMovieSceneSection * Section, const TArray< FName > & InChannelNames, bool bSelectParentInstead, bool bSelect) pure virtual
Selects the nodes that relate to the specified channels.
SelectByChannels() [2/2]
virtual void ISequencer::SelectByChannels (UMovieSceneSection * Section, TArrayView< const FMovieSceneChannelHandle > InChannels, bool bSelectParentInstead, bool bSelect) pure virtual
Selects the nodes that relate to the specified channels.
SelectByNthCategoryNode()
virtual void ISequencer::SelectByNthCategoryNode (UMovieSceneSection * Section, int Index, bool bSelect) pure virtual
Selects nodes by the nth category node under a section.
SelectByPropertyPaths()
virtual void ISequencer::SelectByPropertyPaths (const TArray< FString > & InPropertyPaths) pure virtual
Selects property tracks by property path.
SelectFolder()
virtual void ISequencer::SelectFolder (UMovieSceneFolder * Folder) pure virtual
Selects a folder.
SelectObject()
virtual void ISequencer::SelectObject (FGuid ObjectBinding) pure virtual
Selects an object by GUID.
SelectSection()
virtual void ISequencer::SelectSection (UMovieSceneSection * Section) pure virtual
Selects a section.
SelectTrack()
virtual void ISequencer::SelectTrack (UMovieSceneTrack * Track) pure virtual
Selects a track.
SetAllowEditsMode()
virtual void ISequencer::SetAllowEditsMode (EAllowEditsMode AllowEditsMode) pure virtual
Sets where edits are allowed.
SetAutoChangeMode()
virtual void ISequencer::SetAutoChangeMode (EAutoChangeMode AutoChangeMode) pure virtual
SSets the current auto-change mode.
SetClampRange()
virtual void ISequencer::SetClampRange (TRange< double > NewClampRange) pure virtual
Set the clamp range.
Parameters
NewClampRange The new clamp range. Must be a finite range
SetDisplayName()
virtual void ISequencer::SetDisplayName (FGuid InBinding, const FText & InDisplayName) pure virtual
Set the Display Name of the Object Binding Track.
Parameters
InBinding the Binding of the Object
InDisplayName The new name of the object binding track.
References IMovieScenePlayer::const, and SetDisplayName().
Referenced by SetDisplayName().
SetGlobalTime()
virtual void ISequencer::SetGlobalTime (FFrameTime Time, bool bEvaluate = true) pure virtual
Set the global time directly, without performing any auto-scroll, snapping or other adjustments to the supplied time.
References Time.
SetInfiniteKeyAreas()
virtual void ISequencer::SetInfiniteKeyAreas (bool bInfiniteKeyAreas) pure virtual
Set infinite key area default.
SetKeyGroupMode()
virtual void ISequencer::SetKeyGroupMode (EKeyGroupMode Mode) pure virtual
Sets which channels are keyed when a channel is keyed.
Parameters
Mode Specifies which channels to key, all (EKeyGroupMode::KeyAll), just changed (EKeyGroup::KeyChanged), just the group,e.g. Rotation X,Y and Z if any of those are changed (EKeyGroup::KeyGroup)
SetKeyInterpolation()
virtual void ISequencer::SetKeyInterpolation (EMovieSceneKeyInterpolation) pure virtual
Set default key interpolation.
SetLocalTime()
virtual void ISequencer::SetLocalTime (FFrameTime Time, ESnapTimeMode SnapTimeMode = ESnapTimeMode::STM_None, bool bEvaluate = true) pure virtual
Sets the cursor position relative to the currently focused sequence.
Parameters
Time The local time to set.
SnapTimeMode The type of time snapping allowed.
bEvaluate If True also evaluate
References STM_None, and Time.
SetLocalTimeDirectly()
virtual void ISequencer::SetLocalTimeDirectly (FFrameTime NewTime, bool bEvaluate = true) pure virtual
Set the current local time directly, with no other snapping, scrolling or manipulation.
SetPerspectiveViewportCameraCutEnabled()
virtual void ISequencer::SetPerspectiveViewportCameraCutEnabled (bool bEnabled) pure virtual
Sets whether perspective viewport camera cutting is enabled.
Parameters
bEnabled true if the viewport should be enabled, false if it should be disabled.
References bEnabled.
SetPerspectiveViewportPossessionEnabled()
virtual void ISequencer::SetPerspectiveViewportPossessionEnabled (bool bEnabled) pure virtual
Sets whether perspective viewport hijacking is enabled.
Parameters
bEnabled true if the viewport should be enabled, false if it should be disabled.
References bEnabled.
SetPlaybackSpeed()
virtual void ISequencer::SetPlaybackSpeed (float InPlaybackSpeed) pure virtual
SetSelectionRangeEnd()
virtual void ISequencer::SetSelectionRangeEnd (FFrameTime EndFrame) pure virtual
Set the selection range's end position to the requested time.
See also
GetSelectionRange, SetSelectionRange, SetSelectionRangeStart
References EndFrame.
SetSelectionRangeStart()
virtual void ISequencer::SetSelectionRangeStart (FFrameTime StartFrame) pure virtual
Set the selection range's start position to the requested time.
See also
GetSelectionRange, SetSelectionRange, SetSelectionRangeEnd
SetSequencerSettings()
virtual void ISequencer::SetSequencerSettings (USequencerSettings *) pure virtual
Setter for sequencer settings.
SetShowCurveEditor()
virtual void ISequencer::SetShowCurveEditor (bool bInShowCurveEditor) inline virtual
Whether to show the curve editor or not.
Definition at line 567 of file ISequencer.h.
SetViewportSelectionLimited()
virtual void ISequencer::SetViewportSelectionLimited (const bool bInSelectionLimited) pure virtual
Turns on or off Sequencer selection limiting.
SetViewRange()
virtual void ISequencer::SetViewRange (TRange< double > NewViewRange, EViewRangeInterpolation Interpolation = EViewRangeInterpolation::Animated) pure virtual
Set the view range, growing the working range to accomodate, if necessary.
Parameters
NewViewRange The new view range. Must be a finite range
Interpolation How to interpolate to the new view range
References Interpolation.
SnapSequencerTime()
virtual void ISequencer::SnapSequencerTime (FFrameTime & InOutScrubTime) pure virtual
SnapToClosestPlaybackSpeed()
virtual void ISequencer::SnapToClosestPlaybackSpeed () pure virtual
Snaps to the closest available speed to the current one.
Useful when external systems update the available speeds so the current speed is no longer valid.
SuppressAutoEvaluation()
virtual void ISequencer::SuppressAutoEvaluation (UMovieSceneSequence * Sequence, const FGuid & InSignature) pure virtual
Suppresses automatic evaluation the specified sequence and signature are the only difference that would prompt a re-evaluation.
Parameters
Sequence The sequence that the signature relates to
InSignature The signature to suppress
References IMovieScenePlayer::Sequence.
ThrobKeySelection()
virtual void ISequencer::ThrobKeySelection () pure virtual
Throb key or section selection.
ThrobSectionSelection()
virtual void ISequencer::ThrobSectionSelection () pure virtual
TrackSupportsConditions()
virtual bool ISequencer::TrackSupportsConditions (const UMovieSceneTrack * Track) const pure virtual
UE_DEPRECATED() [1/3]
ISequencer::UE_DEPRECATED (5. 5, "GetTrackFilterNames() has been deprecated. Use GetFilterInterface()->GetFilterDisplayNames() instead.") const pure virtual
Gets all the available track filter names.
References IMovieScenePlayer::const, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
ISequencer::UE_DEPRECATED (5. 5, "IsTrackFilterEnabled() has been deprecated. Use GetFilterInterface()->IsFilterActiveByDisplayName() instead.") const & pure virtual
Gets whether the specified track filter is on/off.
References IMovieScenePlayer::const, and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
ISequencer::UE_DEPRECATED (5. 5, "SetTrackFilterEnabled() has been deprecated. Use GetFilterInterface()->SetFilterActiveByDisplayName() instead.") const &
Sets the specified track filter to be on or off.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UnregisterDrawer()
virtual bool ISequencer::UnregisterDrawer (const FName InDrawerId) pure virtual
Unregisters and removes a drawer from the sidebar.
Parameters
InDrawerId Unique drawer Id to unregister
Returns
True if the drawer removal was successful.
UnregisterDrawerSection()
virtual bool ISequencer::UnregisterDrawerSection (const FName InDrawerId, const FName InSectionId) pure virtual
Unregisters and removes a drawer section from the sidebar.
Parameters
InDrawerId Unique drawer Id that contains the section to unregister
InSectionId Unique drawer section Id to unregister
Returns
True if the drawer removal was successful.
UpdatePlaybackRange()
virtual void ISequencer::UpdatePlaybackRange () pure virtual
Field Documentation
bEnabled
bool ISequencer::bEnabled = 0
Definition at line 883 of file ISequencer.h.
Referenced by SetPerspectiveViewportCameraCutEnabled(), and SetPerspectiveViewportPossessionEnabled().
CameraAddedToSequencer
FOnCameraAddedToSequencer ISequencer::CameraAddedToSequencer protected
Definition at line 1001 of file ISequencer.h.
Referenced by DECLARE_DELEGATE_RetVal_TwoParams().
GetCanRecord
FOnGetCanRecord ISequencer::GetCanRecord protected
Definition at line 1006 of file ISequencer.h.
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
GetIsBindingVisible
FOnGetIsBindingVisible ISequencer::GetIsBindingVisible protected
Definition at line 1002 of file ISequencer.h.
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
GetIsRecording
FOnGetIsRecording ISequencer::GetIsRecording protected
Definition at line 1005 of file ISequencer.h.
Referenced by DECLARE_DELEGATE_RetVal().
GetIsTrackVisible
FOnGetIsTrackVisible ISequencer::GetIsTrackVisible protected
Definition at line 1003 of file ISequencer.h.
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
GetPlaybackSpeeds
FOnGetPlaybackSpeeds ISequencer::GetPlaybackSpeeds protected
Definition at line 1004 of file ISequencer.h.
InitializeDetailsPanelEvent
FOnInitializeDetailsPanel ISequencer::InitializeDetailsPanelEvent protected
Definition at line 1000 of file ISequencer.h.
Referenced by DECLARE_EVENT_TwoParams().
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/ISequencer.h