Unreal Engine 5.6 C++ API: SComboButton Class Reference
SComboButton Class Reference
A button that, when clicked, brings up a popup.
#include "SComboButton.h"
Public Member Functions
void Construct (const FArguments &InArgs)
Construct the widget from a declaration.
void SetButtonContentPadding (FMargin InPadding)
See the padding for button content.
void SetHasDownArrow (bool InHasArrowDown)
add/remove the expanding arrow.
void SetMenuContentWidgetToFocus (TWeakPtr< SWidget > InWidgetToFocusPtr)
void SetOnGetMenuContent (FOnGetContent InOnGetMenuContent)
See the OnGetMenuContent event.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign Method SLATE_ARGUMENT (bool, CollapseMenuOnParentFocus) SLATE_END_ARGS() 1 virtual void SetMenuContent(TSharedRef< SWidget > InContent) override
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable SLATE_ARGUMENT (bool, HasDownArrow) SLATE_ATTRIBUTE(FSlateColor
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign SLATE_ARGUMENT (EVerticalAlignment, VAlign) SLATE_ARGUMENT(TOptional< EPopupMethod >
Spawn a new window or reuse current window for this combo.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding SLATE_ATTRIBUTE (EMenuPlacement, MenuPlacement) SLATE_ARGUMENT(EHorizontalAlignment
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor SLATE_ATTRIBUTE (FSlateColor, ButtonColorAndOpacity) SLATE_ATTRIBUTE(FMargin
SLATE_BEGIN_ARGS (SComboButton)
ButtonStyle MenuContent OnMenuOpenChanged SLATE_EVENT (FOnComboBoxOpened, OnComboBoxOpened) SLATE_ARGUMENT(bool
ButtonStyle MenuContent SLATE_EVENT (FOnGetContent, OnGetMenuContent) SLATE_EVENT(FOnIsOpenChanged
Sets an event handler to generate a widget dynamically when the menu is needed.
ButtonStyle SLATE_NAMED_SLOT (FArguments, ButtonContent) SLATE_NAMED_SLOT(FArguments
Optional static menu content.
SLATE_STYLE_ARGUMENT (FComboButtonStyle, ComboButtonStyle) SLATE_STYLE_ARGUMENT(FButtonStyle
The visual style of the button (overrides ComboButtonStyle)
Protected Member Functions
FText GetFilteredToolTipText (TAttribute< FText > ToolTipText) const
Called to query the tool tip text for this widget, but will return an empty text when the menu is already open.
virtual FReply OnButtonClicked ()
Handle the button being clicked by summoning the ComboButton.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Protected Attributes
bool bIsFocusable
Can this button be focused?
SHorizontalBox::FSlot * ButtonContentSlot
Area where the button's content resides.
TWeakPtr< SWidget > ContentWidgetPtr
The content widget, if any, set by the user on creation.
const FSlateBrush * MenuBorderBrush
Brush to use to add a "menu border" around the drop-down content.
FMargin MenuBorderPadding
Padding to use to add a "menu border" around the drop-down content.
FOnComboBoxOpened OnComboBoxOpened
Delegate to execute when the combo list is opened.
TWeakPtr< SWidget > WidgetToFocusPtr
Private Attributes
TSharedPtr< SButton > ButtonPtr
The button widget within the ComboButton.
TSharedPtr< SImage > ForegroundArrowImage
The arrow image.
TSharedPtr< SHorizontalBox > HBox
The box containing the arrow.
TSharedPtr< SImage > ShadowImage
The arrow image shadow.
const FComboButtonStyle * Style
The ComboButton style.
Detailed Description
A button that, when clicked, brings up a popup.
Definition at line 24 of file SComboButton.h.
Member Function Documentation
Construct()
void SComboButton::Construct (const FArguments & InArgs)
Construct the widget from a declaration.
Parameters
InArgs The declaration from which to construct
References Construct().
Referenced by Construct(), SComboBox< OptionType >::SLATE_ARGUMENT(), SRigVMGraphPinEditableNameValueWidget::SLATE_ARGUMENT(), SRigVMGraphPinNameListValueWidget::SLATE_ARGUMENT(), and SPopupErrorText::SLATE_END_ARGS().
GetFilteredToolTipText()
FText SComboButton::GetFilteredToolTipText (TAttribute< FText > ToolTipText) const protected
Called to query the tool tip text for this widget, but will return an empty text when the menu is already open.
Parameters
ToolTipText Tool tip text to display, if possible
Returns
Tool tip text, or an empty text if filtered out
OnButtonClicked()
virtual FReply SComboButton::OnButtonClicked () protected virtual
Handle the button being clicked by summoning the ComboButton.
Reimplemented in SComboBox< OptionType >, SComboBox< FName >, SComboBox< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SComboBox< TSharedPtr< ECSVImportType > >, SComboBox< TSharedPtr< ERichCurveInterpMode > >, SComboBox< TSharedPtr< FBlueprintDebugObjectInstance > >, SComboBox< TSharedPtr< FName > >, SComboBox< TSharedPtr< FRigVMDebugObjectInstance > >, SComboBox< TSharedPtr< FString > >, SComboBox< TSharedPtr< UE::Insights::FFilter > >, SComboBox< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SComboBox< TSharedPtr< UE::Insights::IFilterOperator > >, SComboBox< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SRigVMGraphPinEditableNameValueWidget, and SRigVMGraphPinNameListValueWidget.
Referenced by SComboBox< OptionType >::OnButtonClicked(), and SComboBox< OptionType >::OnKeyDown().
OnKeyDown()
virtual FReply SComboButton::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override protected virtual
Reimplemented in SComboBox< OptionType >, SComboBox< FName >, SComboBox< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SComboBox< TSharedPtr< ECSVImportType > >, SComboBox< TSharedPtr< ERichCurveInterpMode > >, SComboBox< TSharedPtr< FBlueprintDebugObjectInstance > >, SComboBox< TSharedPtr< FName > >, SComboBox< TSharedPtr< FRigVMDebugObjectInstance > >, SComboBox< TSharedPtr< FString > >, SComboBox< TSharedPtr< UE::Insights::FFilter > >, SComboBox< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SComboBox< TSharedPtr< UE::Insights::IFilterOperator > >, and SComboBox< TSharedRef< UE::Insights::ITableTreeViewPreset > >.
Referenced by SComboBox< OptionType >::OnKeyDown().
SetButtonContentPadding()
void SComboButton::SetButtonContentPadding (FMargin InPadding)
See the padding for button content.
SetHasDownArrow()
void SComboButton::SetHasDownArrow (bool InHasArrowDown)
add/remove the expanding arrow.
SetMenuContentWidgetToFocus()
void SComboButton::SetMenuContentWidgetToFocus (TWeakPtr< SWidget > InWidgetToFocusPtr) inline
Definition at line 91 of file SComboButton.h.
References SetMenuContentWidgetToFocus(), and WidgetToFocusPtr.
Referenced by SetMenuContentWidgetToFocus(), and SComboBox< OptionType >::SLATE_ARGUMENT().
SetOnGetMenuContent()
void SComboButton::SetOnGetMenuContent (FOnGetContent InOnGetMenuContent)
See the OnGetMenuContent event.
References SetOnGetMenuContent().
Referenced by SetOnGetMenuContent().
SLATE_ARGUMENT() [1/3]
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign Method SComboButton::SLATE_ARGUMENT (bool , CollapseMenuOnParentFocus) override
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
References SLATE_ARGUMENT(), and SLATE_END_ARGS.
SLATE_ARGUMENT() [2/3]
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable SComboButton::SLATE_ARGUMENT (bool , HasDownArrow)
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ARGUMENT() [3/3]
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign SComboButton::SLATE_ARGUMENT (EVerticalAlignment , VAlign)
Spawn a new window or reuse current window for this combo.
References SLATE_ARGUMENT().
SLATE_ATTRIBUTE() [1/2]
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding SComboButton::SLATE_ATTRIBUTE (EMenuPlacement , MenuPlacement)
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/2]
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor SComboButton::SLATE_ATTRIBUTE (FSlateColor , ButtonColorAndOpacity)
References SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SComboButton::SLATE_BEGIN_ARGS (SComboButton) inline
Definition at line 28 of file SComboButton.h.
SLATE_EVENT() [1/2]
ButtonStyle MenuContent OnMenuOpenChanged SComboButton::SLATE_EVENT (FOnComboBoxOpened , OnComboBoxOpened)
References OnComboBoxOpened, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_EVENT() [2/2]
ButtonStyle MenuContent SComboButton::SLATE_EVENT (FOnGetContent , OnGetMenuContent)
Sets an event handler to generate a widget dynamically when the menu is needed.
References SLATE_EVENT().
Referenced by SLATE_EVENT(), and SLATE_EVENT().
SLATE_NAMED_SLOT()
ButtonStyle SComboButton::SLATE_NAMED_SLOT (FArguments , ButtonContent)
Optional static menu content.
If the menu content needs to be dynamically built, use the OnGetMenuContent event
References SLATE_NAMED_SLOT().
Referenced by SLATE_NAMED_SLOT().
SLATE_STYLE_ARGUMENT()
SComboButton::SLATE_STYLE_ARGUMENT (FComboButtonStyle , ComboButtonStyle)
The visual style of the button (overrides ComboButtonStyle)
Field Documentation
bIsFocusable
bool SComboButton::bIsFocusable protected
Can this button be focused?
Definition at line 137 of file SComboButton.h.
Referenced by SComboBox< OptionType >::SupportsKeyboardFocus().
ButtonContentSlot
SHorizontalBox::FSlot* SComboButton::ButtonContentSlot protected
Area where the button's content resides.
Definition at line 120 of file SComboButton.h.
ButtonPtr
TSharedPtr<SButton> SComboButton::ButtonPtr private
The button widget within the ComboButton.
Definition at line 141 of file SComboButton.h.
ContentWidgetPtr
TWeakPtr<SWidget> SComboButton::ContentWidgetPtr protected
The content widget, if any, set by the user on creation.
Definition at line 134 of file SComboButton.h.
ForegroundArrowImage
TSharedPtr<SImage> SComboButton::ForegroundArrowImage private
The arrow image.
Definition at line 150 of file SComboButton.h.
HBox
TSharedPtr<SHorizontalBox> SComboButton::HBox private
The box containing the arrow.
Definition at line 144 of file SComboButton.h.
MenuBorderBrush
const FSlateBrush* SComboButton::MenuBorderBrush protected
Brush to use to add a "menu border" around the drop-down content.
Definition at line 128 of file SComboButton.h.
MenuBorderPadding
FMargin SComboButton::MenuBorderPadding protected
Padding to use to add a "menu border" around the drop-down content.
Definition at line 131 of file SComboButton.h.
OnComboBoxOpened
FOnComboBoxOpened SComboButton::OnComboBoxOpened protected
Delegate to execute when the combo list is opened.
Definition at line 123 of file SComboButton.h.
Referenced by SLATE_EVENT().
ShadowImage
TSharedPtr<SImage> SComboButton::ShadowImage private
The arrow image shadow.
Definition at line 147 of file SComboButton.h.
Style
const FComboButtonStyle* SComboButton::Style private
The ComboButton style.
Definition at line 153 of file SComboButton.h.
WidgetToFocusPtr
TWeakPtr<SWidget> SComboButton::WidgetToFocusPtr protected
Definition at line 125 of file SComboButton.h.
Referenced by SetMenuContentWidgetToFocus().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SComboButton.h