Unreal Engine 5.6 C++ API: Metasound::Frontend::IMetaSoundDocumentBuilderRegistry Class Reference
Metasound::Frontend::IMetaSoundDocumentBuilderRegistry Class Reference
#include "MetasoundDocumentInterface.h"
Public Member Functions
virtual ~IMetaSoundDocumentBuilderRegistry ()=default
UE_DEPRECATED (5.4, "Public exposition of modify delegates no longer available to discourage unsafe manipulation of builder document cache") virtual const FDocumentModifyDelegates *FindModifyDelegates(const FMetasoundFrontendClassName &InClassName) const
UE_DEPRECATED (5.4, "Use 'IDocumentBuilderRegistry' instead") static METASOUNDFRONTEND_API IMetaSoundDocumentBuilderRegistry &GetChecked()
UE_DEPRECATED (5.5, "Class Renamed: use IDocumentBuilderRegistry instead") IMetaSoundDocumentBuilderRegistry()=default
Public Member Functions inherited from Metasound::Frontend::IDocumentBuilderRegistry
virtual ~IDocumentBuilderRegistry ()=default
virtual FMetaSoundFrontendDocumentBuilder * FindBuilder (const FMetasoundFrontendClassName &ClassName, const FTopLevelAssetPath &AssetPath) const =0
virtual FMetaSoundFrontendDocumentBuilder * FindBuilder (TScriptInterface< IMetaSoundDocumentInterface > MetaSound) const =0
virtual FMetaSoundFrontendDocumentBuilder * FindOutermostBuilder (const UObject &InSubObject) const =0
virtual bool FinishBuilding (const FMetasoundFrontendClassName &InClassName, bool bForceUnregisterNodeClass=false) const =0
virtual bool FinishBuilding (const FMetasoundFrontendClassName &InClassName, const FTopLevelAssetPath &InAssetPath, bool bForceUnregisterNodeClass=false) const =0
virtual bool ReloadBuilder (const FMetasoundFrontendClassName &InClassName) const =0
virtual FGuid ResolveTargetPageID (const FMetasoundFrontendClassInput &InClassInput) const =0
virtual FGuid ResolveTargetPageID (const FMetasoundFrontendGraphClass &InGraphClass) const =0
virtual FGuid ResolveTargetPageID (const TArray< FMetasoundFrontendClassInputDefault > &Defaults) const =0
UE_DEPRECATED (5.5, "Document cache can now be invalidated by retrieving an asset builder and calling 'ReloadBuilder'") virtual void InvalidateDocumentCache(const FMetasoundFrontendClassName &InClassName) const
Additional Inherited Members
Static Public Member Functions inherited from Metasound::Frontend::IDocumentBuilderRegistry
static METASOUNDFRONTEND_API void Deinitialize ()
static METASOUNDFRONTEND_API IDocumentBuilderRegistry * Get ()
static METASOUNDFRONTEND_API IDocumentBuilderRegistry & GetChecked ()
static METASOUNDFRONTEND_API void Initialize (TUniquePtr< IDocumentBuilderRegistry > &&InBuilderRegistry)
Protected Member Functions inherited from Metasound::Frontend::IDocumentBuilderRegistry
UE_DEPRECATED (5.5, "Use 'Initialize' instead") static void Set(TUniqueFunction< IDocumentBuilderRegistry &()> &&InGetInstance)
Detailed Description
Definition at line 138 of file MetasoundDocumentInterface.h.
Constructor & Destructor Documentation
~IMetaSoundDocumentBuilderRegistry()
virtual Metasound::Frontend::IMetaSoundDocumentBuilderRegistry::~IMetaSoundDocumentBuilderRegistry () virtual default
Member Function Documentation
UE_DEPRECATED() [1/3]
Metasound::Frontend::IMetaSoundDocumentBuilderRegistry::UE_DEPRECATED (5. 4, "Public exposition of modify delegates no longer available to discourage unsafe manipulation of builder document cache") const & inline
Definition at line 145 of file MetasoundDocumentInterface.h.
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
Metasound::Frontend::IMetaSoundDocumentBuilderRegistry::UE_DEPRECATED (5. 4, "Use 'IDocumentBuilderRegistry' instead") &
References Metasound::Frontend::IDocumentBuilderRegistry::GetChecked(), and UE_API.
UE_DEPRECATED() [3/3]
Metasound::Frontend::IMetaSoundDocumentBuilderRegistry::UE_DEPRECATED (5. 5, "Class Renamed: use IDocumentBuilderRegistry instead") default
Referenced by UE_DEPRECATED().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundDocumentInterface.h