Unreal Engine 5.6 C++ API: FPrimitiveInstanceDataManager Class Reference
FPrimitiveInstanceDataManager Class Reference
Manager class that tracks changes to instance data within the component, and is responsible for dispatching updates of the proxy.
#include "ISMInstanceDataManager.h"
Public Types
enum class EMode : uint8 { Default , Legacy , ExternalLegacyData }
enum class ETrackingState : uint8 { Initial , Tracked , Disabled , Optimized }
Current tracking state,.
Public Member Functions
FPrimitiveInstanceDataManager (UPrimitiveComponent *InPrimitiveComponent)
void Add (int32 InInstanceAddAtIndex, bool bInsert)
void BakedLightingDataChanged (int32 InstanceIndex)
void BakedLightingDataChangedAll ()
void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform, FInstanceUpdateComponentDesc &&ComponentData, TStridedView< FMatrix > InstanceTransforms)
void ClearChangeTracking ()
Clear all tracked changes (will result in a full update when next one is flushed)
void ClearIdTracking (int32 InNumInstances)
Clear the ID/Index association and reset the mapping to identity & number of instances to the given number.
void CreateExplicitIdentityMapping ()
void CustomDataChanged (int32 InstanceIndex)
void EditorDataChangedAll ()
bool FlushChanges (FInstanceUpdateComponentDesc &&ComponentData, bool bNewPrimitiveProxy)
SIZE_T GetAllocatedSize () const
int32 GetMaxInstanceId () const
int32 GetMaxInstanceIndex () const
EMode GetMode () const
TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > GetOrCreateProxy (ERHIFeatureLevel::Type InFeatureLevel)
const TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > & GetProxy () const
ETrackingState GetState () const
bool HasAnyChanges () const
Returns true if there are explicitly tracked instance changes, or the state is not tracked (because no proxy has been created yet), and the tracking state is not Disabled.
bool HasAnyInstanceChanges () const
void Invalidate (int32 InNumInstances)
void MarkForRebuildFromLegacy (TUniquePtr< FStaticMeshInstanceData > &&LegacyInstanceData, const TArray< int32 > &InstanceReorderTable, const TArray< TRefCountPtr< HHitProxy > > &HitProxies)
Call to mark the manager as needing a full rebuild & having an external driver for this.
void NumCustomDataChanged ()
void OnRegister (int32 InNumInstances)
Called by the corresponding function in the owner UPrimitiveComponent Because of the multifarious ways the engine shoves data into the properties it is possible for the count to get out of sync.
void PostLoad (int32 InNumInstances)
void PrimitiveTransformChanged ()
void ReadCookedRenderData (FArchive &Ar)
void RemoveAt (int32 InstanceIndex)
void RemoveAtSwap (int32 InstanceIndex)
void ResetComponentDirtyTracking ()
void SetMode (EMode InMode)
bool ShouldWriteCookedData (const ITargetPlatform *TargetPlatform, int32 NumInstancesToBuildFor)
void TransformChanged (FPrimitiveInstanceId InstanceId)
void TransformChanged (int32 InstanceIndex)
void TransformsChangedAll ()
FORCEINLINE void ValidateMapping () const
void WriteCookedRenderData (FArchive &Ar, FInstanceUpdateComponentDesc &&ComponentData, TStridedView< FMatrix > InstanceTransforms)
Public Member Functions inherited from FInstanceIdIndexMap
FInstanceIdIndexMap ()=default
void CreateExplicitIdentityMapping ()
Convert an implicit identity mapping to an explicit one, by filling in the mapping arrays.
FORCEINLINE int32 GetMaxInstanceId () const
Returms the upper bound on the instance ID represented as an integer, may be larger than the number of instances but is never larger than the max that has ever been allocated.
FORCEINLINE int32 GetMaxInstanceIndex () const
Returns the maximum instance index (or rather the maximum valid number plus one), AKA the number of instances represented.
FORCEINLINE int32 IdToIndex (FPrimitiveInstanceId InstanceId) const
Translate from FPrimitiveInstanceId to Index.
FORCEINLINE FPrimitiveInstanceId IndexToId (int32 InstanceIndex) const
Translate from Index to FPrimitiveInstanceId.
FORCEINLINE bool IsIdentity () const
Returns true if the mapping is an identity mapping.
FORCEINLINE bool IsValidId (FPrimitiveInstanceId InstanceId) const
Returns true if InstanceId is in the mapped range AND .
void RebuildFromIndexToIdMap (TArray< FPrimitiveInstanceId > &&InIndexToIdMap, int32 MaxInstanceId)
void Reset (int32 InNumInstances)
Reset the mapping to an identity map of size InNumInstances.
void ResizeExplicit (int32 InNumInstances, int32 MaxInstanceId)
Make sure the mapping is explicit and add enough space to accommodate the InNumInstances & MaxInstanceId.
void Serialize (FArchive &Ar)
FORCEINLINE void SetInvalid (FPrimitiveInstanceId InstanceId)
Set the index mapping for the given InstanceId to INDEX_NONE.
FORCEINLINE void Update (FPrimitiveInstanceId InstanceId, int32 InstanceIndex)
Update the mapping from ID to index (and vice versa).
Private Types
using EChangeFlag = FInstanceAttributeTracker::EFlag
using PrecomputedOptimizationDataPtr = FISMCInstanceDataSceneProxy::FISMPrecomputedSpatialHashDataPtr
Private Member Functions
void FreeInstanceId (FPrimitiveInstanceId InstanceId)
bool HasIdentityMapping () const
void InitChangeSet (const union FChangeDesc &ChangeDesc, const FInstanceUpdateComponentDesc &ComponentData, FISMInstanceUpdateChangeSet &ChangeSet)
template<EChangeFlag Flag>
void MarkChangeHelper (FPrimitiveInstanceId InstanceId)
template<EChangeFlag Flag>
void MarkChangeHelper (int32 InstanceIndex)
void MarkComponentRenderInstancesDirty ()
Static Private Member Functions
static FISMPrecomputedSpatialHashData PrecomputeOptimizationData (FInstanceUpdateComponentDesc &&ComponentData, TStridedView< FMatrix > InstanceTransforms)
Build precomputed data from the input.
static bool ShouldUsePrecomputed ()
Private Attributes
float AbsMaxDisplacement = 0.0f
uint8 bAnyEditorDataChanged: 1
uint8 bAnyInstanceChange: 1
uint8 bBakedLightingDataChanged: 1
uint8 bComponentMarkedDirty: 1
uint8 bEnableTracking: 1
uint8 bFirstFlush: 1
uint8 bNumCustomDataChanged: 1
uint8 bPrimitiveTransformChanged: 1
uint8 bTransformChangedAllInstances: 1
FInstanceDataFlags Flags
int32 IdSearchStartIndex = 0
FInstanceAttributeTracker InstanceUpdateTracker
TPimplPtr< struct FLegacyBuildData > LegacyBuildData
EMode Mode = EMode::Default
int32 NumCustomDataFloats = 0
PrecomputedOptimizationDataPtr PrecomputedOptimizationData
TWeakObjectPtr< UPrimitiveComponent > PrimitiveComponent = nullptr
FMatrix PrimitiveLocalToWorld
TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > Proxy
FRenderBounds StaticMeshBounds
ETrackingState TrackingState = ETrackingState::Initial
TBitArray ValidInstanceIdMask
Additional Inherited Members
Protected Member Functions inherited from FInstanceIdIndexMap
void RebuildFromIndexToIdMap (int32 MaxInstanceId)
Protected Attributes inherited from FInstanceIdIndexMap
TArray< int32 > IdToIndexMap
TArray< FPrimitiveInstanceId > IndexToIdMap
int32 NumInstances = 0
Detailed Description
Manager class that tracks changes to instance data within the component, and is responsible for dispatching updates of the proxy.
Tracks instance index changes to be able to maintain a persistent ID mapping for use on the render thread. The ID mapping is not serialized and will be reset when the proxy is recreated. Not responsible for storing the component representation of the instance data. NOTE/TODO: This is tied to the ISM use-case, mostly because of legacy (HISM) interactions. Will be refactored and sub-classed or something. Also: Still somewhat tied to the UComponent, which also can be refactored a bit to make it more general.
Definition at line 44 of file ISMInstanceDataManager.h.
Member Typedef Documentation
EChangeFlag
using FPrimitiveInstanceDataManager::EChangeFlag = FInstanceAttributeTracker::EFlag private
Definition at line 182 of file ISMInstanceDataManager.h.
PrecomputedOptimizationDataPtr
using FPrimitiveInstanceDataManager::PrecomputedOptimizationDataPtr = FISMCInstanceDataSceneProxy::FISMPrecomputedSpatialHashDataPtr private
Definition at line 232 of file ISMInstanceDataManager.h.
Member Enumeration Documentation
EMode
enum class FPrimitiveInstanceDataManager::EMode : uint8 strong
Enumerator
Default
Legacy
ExternalLegacyData
Definition at line 60 of file ISMInstanceDataManager.h.
ETrackingState
enum class FPrimitiveInstanceDataManager::ETrackingState : uint8 strong
Current tracking state,.
Enumerator
Initial
Tracked
Disabled
Optimized
Definition at line 52 of file ISMInstanceDataManager.h.
Constructor & Destructor Documentation
FPrimitiveInstanceDataManager()
FPrimitiveInstanceDataManager::FPrimitiveInstanceDataManager (UPrimitiveComponent * InPrimitiveComponent)
Member Function Documentation
Add()
void FPrimitiveInstanceDataManager::Add (int32 InInstanceAddAtIndex, bool bInsert)
BakedLightingDataChanged()
void FPrimitiveInstanceDataManager::BakedLightingDataChanged (int32 InstanceIndex)
BakedLightingDataChangedAll()
void FPrimitiveInstanceDataManager::BakedLightingDataChangedAll ()
BeginCacheForCookedPlatformData()
void FPrimitiveInstanceDataManager::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform, FInstanceUpdateComponentDesc && ComponentData, TStridedView< FMatrix > InstanceTransforms)
ClearChangeTracking()
void FPrimitiveInstanceDataManager::ClearChangeTracking ()
Clear all tracked changes (will result in a full update when next one is flushed)
ClearIdTracking()
void FPrimitiveInstanceDataManager::ClearIdTracking (int32 InNumInstances)
Clear the ID/Index association and reset the mapping to identity & number of instances to the given number.
Also clears the change tracking state.
CreateExplicitIdentityMapping()
void FPrimitiveInstanceDataManager::CreateExplicitIdentityMapping ()
CustomDataChanged()
void FPrimitiveInstanceDataManager::CustomDataChanged (int32 InstanceIndex)
EditorDataChangedAll()
void FPrimitiveInstanceDataManager::EditorDataChangedAll ()
FlushChanges()
bool FPrimitiveInstanceDataManager::FlushChanges (FInstanceUpdateComponentDesc && ComponentData, bool bNewPrimitiveProxy)
FreeInstanceId()
void FPrimitiveInstanceDataManager::FreeInstanceId (FPrimitiveInstanceId InstanceId) private
GetAllocatedSize()
SIZE_T FPrimitiveInstanceDataManager::GetAllocatedSize () const
GetMaxInstanceId()
int32 FPrimitiveInstanceDataManager::GetMaxInstanceId () const
GetMaxInstanceIndex()
int32 FPrimitiveInstanceDataManager::GetMaxInstanceIndex () const
GetMode()
EMode FPrimitiveInstanceDataManager::GetMode () const inline
Definition at line 73 of file ISMInstanceDataManager.h.
References Mode.
GetOrCreateProxy()
TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > FPrimitiveInstanceDataManager::GetOrCreateProxy (ERHIFeatureLevel::Type InFeatureLevel)
GetProxy()
const TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > & FPrimitiveInstanceDataManager::GetProxy () const inline
Definition at line 141 of file ISMInstanceDataManager.h.
References Proxy.
GetState()
ETrackingState FPrimitiveInstanceDataManager::GetState () const inline
Definition at line 138 of file ISMInstanceDataManager.h.
References TrackingState.
Referenced by HasAnyChanges().
HasAnyChanges()
bool FPrimitiveInstanceDataManager::HasAnyChanges () const inline
Returns true if there are explicitly tracked instance changes, or the state is not tracked (because no proxy has been created yet), and the tracking state is not Disabled.
Definition at line 114 of file ISMInstanceDataManager.h.
References Disabled, GetState(), HasAnyInstanceChanges(), and Tracked.
HasAnyInstanceChanges()
bool FPrimitiveInstanceDataManager::HasAnyInstanceChanges () const
Referenced by HasAnyChanges().
HasIdentityMapping()
bool FPrimitiveInstanceDataManager::HasIdentityMapping () const private
InitChangeSet()
void FPrimitiveInstanceDataManager::InitChangeSet (const union FChangeDesc & ChangeDesc, const FInstanceUpdateComponentDesc & ComponentData, FISMInstanceUpdateChangeSet & ChangeSet) private
Invalidate()
void FPrimitiveInstanceDataManager::Invalidate (int32 InNumInstances)
MarkChangeHelper() [1/2]
template<EChangeFlag Flag> void FPrimitiveInstanceDataManager::MarkChangeHelper (FPrimitiveInstanceId InstanceId) inline private
MarkChangeHelper() [2/2]
template<EChangeFlag Flag> void FPrimitiveInstanceDataManager::MarkChangeHelper (int32 InstanceIndex) inline private
MarkComponentRenderInstancesDirty()
void FPrimitiveInstanceDataManager::MarkComponentRenderInstancesDirty () private
MarkForRebuildFromLegacy()
void FPrimitiveInstanceDataManager::MarkForRebuildFromLegacy (TUniquePtr< FStaticMeshInstanceData > && LegacyInstanceData, const TArray< int32 > & InstanceReorderTable, const TArray< TRefCountPtr< HHitProxy > > & HitProxies)
Call to mark the manager as needing a full rebuild & having an external driver for this.
NumCustomDataChanged()
void FPrimitiveInstanceDataManager::NumCustomDataChanged ()
OnRegister()
void FPrimitiveInstanceDataManager::OnRegister (int32 InNumInstances)
Called by the corresponding function in the owner UPrimitiveComponent Because of the multifarious ways the engine shoves data into the properties it is possible for the count to get out of sync.
Also at this point we may assume that we have no idea of the state of individual members. Thus, this function will reset tracking state to force a full update as well as, conditionally - if the counts are mismatched - reset the ID mapping.
PostLoad()
void FPrimitiveInstanceDataManager::PostLoad (int32 InNumInstances)
PrecomputeOptimizationData()
FISMPrecomputedSpatialHashData FPrimitiveInstanceDataManager::PrecomputeOptimizationData (FInstanceUpdateComponentDesc && ComponentData, TStridedView< FMatrix > InstanceTransforms) static private
Build precomputed data from the input.
PrimitiveTransformChanged()
void FPrimitiveInstanceDataManager::PrimitiveTransformChanged ()
ReadCookedRenderData()
void FPrimitiveInstanceDataManager::ReadCookedRenderData (FArchive & Ar)
References Ar.
RemoveAt()
void FPrimitiveInstanceDataManager::RemoveAt (int32 InstanceIndex)
RemoveAtSwap()
void FPrimitiveInstanceDataManager::RemoveAtSwap (int32 InstanceIndex)
ResetComponentDirtyTracking()
void FPrimitiveInstanceDataManager::ResetComponentDirtyTracking () inline
Definition at line 160 of file ISMInstanceDataManager.h.
References bComponentMarkedDirty.
SetMode()
void FPrimitiveInstanceDataManager::SetMode (EMode InMode)
ShouldUsePrecomputed()
bool FPrimitiveInstanceDataManager::ShouldUsePrecomputed () static private
ShouldWriteCookedData()
bool FPrimitiveInstanceDataManager::ShouldWriteCookedData (const ITargetPlatform * TargetPlatform, int32 NumInstancesToBuildFor)
TransformChanged() [1/2]
void FPrimitiveInstanceDataManager::TransformChanged (FPrimitiveInstanceId InstanceId)
TransformChanged() [2/2]
void FPrimitiveInstanceDataManager::TransformChanged (int32 InstanceIndex)
TransformsChangedAll()
void FPrimitiveInstanceDataManager::TransformsChangedAll ()
ValidateMapping()
FORCEINLINE void FPrimitiveInstanceDataManager::ValidateMapping () const inline
Definition at line 147 of file ISMInstanceDataManager.h.
References FORCEINLINE.
WriteCookedRenderData()
void FPrimitiveInstanceDataManager::WriteCookedRenderData (FArchive & Ar, FInstanceUpdateComponentDesc && ComponentData, TStridedView< FMatrix > InstanceTransforms)
References Ar.
Field Documentation
AbsMaxDisplacement
float FPrimitiveInstanceDataManager::AbsMaxDisplacement = 0.0f private
Definition at line 241 of file ISMInstanceDataManager.h.
bAnyEditorDataChanged
uint8 FPrimitiveInstanceDataManager::bAnyEditorDataChanged private
Definition at line 218 of file ISMInstanceDataManager.h.
bAnyInstanceChange
uint8 FPrimitiveInstanceDataManager::bAnyInstanceChange private
Definition at line 221 of file ISMInstanceDataManager.h.
bBakedLightingDataChanged
uint8 FPrimitiveInstanceDataManager::bBakedLightingDataChanged private
Definition at line 215 of file ISMInstanceDataManager.h.
bComponentMarkedDirty
uint8 FPrimitiveInstanceDataManager::bComponentMarkedDirty private
Definition at line 223 of file ISMInstanceDataManager.h.
Referenced by ResetComponentDirtyTracking().
bEnableTracking
uint8 FPrimitiveInstanceDataManager::bEnableTracking private
Definition at line 224 of file ISMInstanceDataManager.h.
bFirstFlush
uint8 FPrimitiveInstanceDataManager::bFirstFlush private
Definition at line 225 of file ISMInstanceDataManager.h.
bNumCustomDataChanged
uint8 FPrimitiveInstanceDataManager::bNumCustomDataChanged private
Definition at line 214 of file ISMInstanceDataManager.h.
bPrimitiveTransformChanged
uint8 FPrimitiveInstanceDataManager::bPrimitiveTransformChanged private
Definition at line 220 of file ISMInstanceDataManager.h.
bTransformChangedAllInstances
uint8 FPrimitiveInstanceDataManager::bTransformChangedAllInstances private
Definition at line 216 of file ISMInstanceDataManager.h.
Flags
FInstanceDataFlags FPrimitiveInstanceDataManager::Flags private
Definition at line 239 of file ISMInstanceDataManager.h.
IdSearchStartIndex
int32 FPrimitiveInstanceDataManager::IdSearchStartIndex = 0 private
Definition at line 209 of file ISMInstanceDataManager.h.
InstanceUpdateTracker
FInstanceAttributeTracker FPrimitiveInstanceDataManager::InstanceUpdateTracker private
Definition at line 205 of file ISMInstanceDataManager.h.
LegacyBuildData
TPimplPtr<struct FLegacyBuildData> FPrimitiveInstanceDataManager::LegacyBuildData private
Definition at line 230 of file ISMInstanceDataManager.h.
Mode
EMode FPrimitiveInstanceDataManager::Mode = EMode::Default private
Definition at line 211 of file ISMInstanceDataManager.h.
Referenced by GetMode().
NumCustomDataFloats
int32 FPrimitiveInstanceDataManager::NumCustomDataFloats = 0 private
Definition at line 240 of file ISMInstanceDataManager.h.
PrecomputedOptimizationData
PrecomputedOptimizationDataPtr FPrimitiveInstanceDataManager::PrecomputedOptimizationData private
Definition at line 234 of file ISMInstanceDataManager.h.
PrimitiveComponent
TWeakObjectPtr<UPrimitiveComponent> FPrimitiveInstanceDataManager::PrimitiveComponent = nullptr private
Definition at line 228 of file ISMInstanceDataManager.h.
PrimitiveLocalToWorld
FMatrix FPrimitiveInstanceDataManager::PrimitiveLocalToWorld private
Definition at line 238 of file ISMInstanceDataManager.h.
Proxy
TSharedPtr<FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe> FPrimitiveInstanceDataManager::Proxy private
Definition at line 227 of file ISMInstanceDataManager.h.
Referenced by GetProxy().
StaticMeshBounds
FRenderBounds FPrimitiveInstanceDataManager::StaticMeshBounds private
Definition at line 242 of file ISMInstanceDataManager.h.
TrackingState
ETrackingState FPrimitiveInstanceDataManager::TrackingState = ETrackingState::Initial private
Definition at line 212 of file ISMInstanceDataManager.h.
Referenced by GetState().
ValidInstanceIdMask
TBitArray FPrimitiveInstanceDataManager::ValidInstanceIdMask private
Definition at line 208 of file ISMInstanceDataManager.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/InstancedStaticMesh/ISMInstanceDataManager.h