Unreal Engine 5.6 C++ API: TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType > Class Template Reference
TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType > Class Template Reference
#include "ContainerAllocationPolicies.h"
Public Member Functions
ForElementType ()
Default constructor.
FORCEINLINE SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
SIZE_T GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE ElementType * GetAllocation () const
SizeType GetInitialCapacity () const
bool HasAllocation () const
FORCEINLINE void MoveToEmpty (ForElementType &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement)
Private Member Functions
ForElementType (const ForElementType &)
ElementType * GetInlineElements () const
ForElementType & operator= (const ForElementType &)
Private Attributes
TTypeCompatibleBytes< ElementType > InlineData [NumInlineElements]
The data is stored in this array if less than NumInlineElements is needed.
SecondaryAllocator::template ForElementType< ElementType > SecondaryData
The data is allocated through the indirect allocation policy if more than NumInlineElements is needed.
Detailed Description
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator>
template<typename ElementType>
class TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >
Definition at line 868 of file ContainerAllocationPolicies.h.
Constructor & Destructor Documentation
ForElementType() [1/2]
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::ForElementType () inline
Default constructor.
Definition at line 873 of file ContainerAllocationPolicies.h.
Referenced by ForElementType(), MoveToEmpty(), and operator=().
ForElementType() [2/2]
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::ForElementType (const ForElementType< ElementType > &) private
References ForElementType().
Member Function Documentation
CalculateSlackGrow()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> FORCEINLINE SizeType TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 953 of file ContainerAllocationPolicies.h.
References FORCEINLINE, and SecondaryData.
CalculateSlackReserve()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> FORCEINLINE SizeType TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const inline
Definition at line 939 of file ContainerAllocationPolicies.h.
References FORCEINLINE, and SecondaryData.
CalculateSlackShrink()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> FORCEINLINE SizeType TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 946 of file ContainerAllocationPolicies.h.
References FORCEINLINE, and SecondaryData.
GetAllocatedSize()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> SIZE_T TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 964 of file ContainerAllocationPolicies.h.
References SecondaryData.
GetAllocation()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> FORCEINLINE ElementType * TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::GetAllocation () const inline
Definition at line 898 of file ContainerAllocationPolicies.h.
References FORCEINLINE, GetInlineElements(), and SecondaryData.
GetInitialCapacity()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> SizeType TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::GetInitialCapacity () const inline
Definition at line 978 of file ContainerAllocationPolicies.h.
GetInlineElements()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> ElementType * TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::GetInlineElements () const inline private
Returns
the base of the aligned inline element data
Definition at line 1004 of file ContainerAllocationPolicies.h.
References InlineData.
Referenced by GetAllocation(), and ResizeAllocation().
HasAllocation()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> bool TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::HasAllocation () const inline
Definition at line 973 of file ContainerAllocationPolicies.h.
References SecondaryData.
MoveToEmpty()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> FORCEINLINE void TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::MoveToEmpty (ForElementType< ElementType > & Other) inline
Moves the state of another allocator into this one.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 882 of file ContainerAllocationPolicies.h.
References ForElementType(), checkSlow, FORCEINLINE, InlineData, Other, RelocateConstructItems(), and SecondaryData.
operator=()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> ForElementType & TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::operator= (const ForElementType< ElementType > &) private
References ForElementType().
ResizeAllocation()
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> void TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 907 of file ContainerAllocationPolicies.h.
References GetInlineElements(), InlineData, RelocateConstructItems(), and SecondaryData.
Field Documentation
InlineData
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> TTypeCompatibleBytes<ElementType> TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::InlineData[NumInlineElements] private
The data is stored in this array if less than NumInlineElements is needed.
Definition at line 998 of file ContainerAllocationPolicies.h.
Referenced by GetInlineElements(), MoveToEmpty(), and ResizeAllocation().
SecondaryData
template<uint32 NumInlineElements, int IndexSize, typename SecondaryAllocator = FDefaultAllocator> template<typename ElementType> SecondaryAllocator::template ForElementType<ElementType> TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::SecondaryData private
The data is allocated through the indirect allocation policy if more than NumInlineElements is needed.
Definition at line 1001 of file ContainerAllocationPolicies.h.
Referenced by CalculateSlackGrow(), CalculateSlackReserve(), CalculateSlackShrink(), GetAllocatedSize(), GetAllocation(), HasAllocation(), MoveToEmpty(), and ResizeAllocation().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/ContainerAllocationPolicies.h