Unreal Engine 5.6 C++ API: UUVEditorRecomputeUVsTool Class Reference
UUVEditorRecomputeUVsTool Class Reference
UUVEditorRecomputeUVsTool Recomputes UVs based on existing segmentations of the mesh.
#include "UVEditorRecomputeUVsTool.h"
Public Member Functions
virtual bool CanAccept () const override
virtual bool HasAccept () const override
virtual bool HasCancel () const override
virtual void OnPropertyModified (UObject *PropertySet, FProperty *Property) override
virtual void OnTick (float DeltaTime) override
virtual void Render (IToolsContextRenderAPI *RenderAPI) override
virtual void SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > &TargetsIn)
The tool will operate on the meshes given here.
virtual void Setup () override
virtual void Shutdown (EToolShutdownType ShutdownType) override
Protected Member Functions
void OnSelectedGroupLayerChanged ()
void RecordAnalytics ()
void UpdateActiveGroupLayer (bool bUpdateFactories=true)
Protected Attributes
TSharedPtr< UE::Geometry::FPolygroupSet, ESPMode::ThreadSafe > ActiveGroupSet
TArray< TObjectPtr< URecomputeUVsOpFactory > > Factories
UE::Geometry::UVEditorAnalytics::FTargetAnalytics InputTargetAnalytics
TObjectPtr< UPolygroupLayersProperties > PolygroupLayerProperties = nullptr
TObjectPtr< URecomputeUVsToolProperties > Settings = nullptr
TArray< TObjectPtr< UUVEditorToolMeshInput > > Targets
FDateTime ToolStartTimeAnalytics
TObjectPtr< UUVToolSelectionAPI > UVToolSelectionAPI = nullptr
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
UUVEditorRecomputeUVsTool Recomputes UVs based on existing segmentations of the mesh.
Definition at line 47 of file UVEditorRecomputeUVsTool.h.
Member Function Documentation
CanAccept()
virtual bool UUVEditorRecomputeUVsTool::CanAccept () const override virtual
HasAccept()
virtual bool UUVEditorRecomputeUVsTool::HasAccept () const inline override virtual
Definition at line 60 of file UVEditorRecomputeUVsTool.h.
HasCancel()
virtual bool UUVEditorRecomputeUVsTool::HasCancel () const inline override virtual
Definition at line 59 of file UVEditorRecomputeUVsTool.h.
References HasCancel().
Referenced by HasCancel().
OnPropertyModified()
virtual void UUVEditorRecomputeUVsTool::OnPropertyModified (UObject * PropertySet, FProperty * Property) override virtual
References Property.
OnSelectedGroupLayerChanged()
void UUVEditorRecomputeUVsTool::OnSelectedGroupLayerChanged () protected
References OnSelectedGroupLayerChanged().
Referenced by OnSelectedGroupLayerChanged().
OnTick()
virtual void UUVEditorRecomputeUVsTool::OnTick (float DeltaTime) override virtual
References DeltaTime, and OnTick().
Referenced by OnTick().
RecordAnalytics()
void UUVEditorRecomputeUVsTool::RecordAnalytics () protected
References RecordAnalytics().
Referenced by RecordAnalytics().
Render()
virtual void UUVEditorRecomputeUVsTool::Render (IToolsContextRenderAPI * RenderAPI) override virtual
References Render().
Referenced by Render().
SetTargets()
virtual void UUVEditorRecomputeUVsTool::SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > & TargetsIn) inline virtual
The tool will operate on the meshes given here.
Definition at line 69 of file UVEditorRecomputeUVsTool.h.
References Targets.
Setup()
virtual void UUVEditorRecomputeUVsTool::Setup () override virtual
References Setup().
Referenced by Setup().
Shutdown()
virtual void UUVEditorRecomputeUVsTool::Shutdown (EToolShutdownType ShutdownType) override virtual
References Shutdown().
Referenced by Shutdown().
UpdateActiveGroupLayer()
void UUVEditorRecomputeUVsTool::UpdateActiveGroupLayer (bool bUpdateFactories = true) protected
References UpdateActiveGroupLayer().
Referenced by UpdateActiveGroupLayer().
Field Documentation
ActiveGroupSet
TSharedPtr<UE::Geometry::FPolygroupSet, ESPMode::ThreadSafe> UUVEditorRecomputeUVsTool::ActiveGroupSet protected
Definition at line 91 of file UVEditorRecomputeUVsTool.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorRecomputeUVsTool::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 49 of file UVEditorRecomputeUVsTool.h.
Factories
TArray<TObjectPtr<URecomputeUVsOpFactory> > UUVEditorRecomputeUVsTool::Factories protected
Definition at line 85 of file UVEditorRecomputeUVsTool.h.
InputTargetAnalytics
UE::Geometry::UVEditorAnalytics::FTargetAnalytics UUVEditorRecomputeUVsTool::InputTargetAnalytics protected
Definition at line 99 of file UVEditorRecomputeUVsTool.h.
PolygroupLayerProperties
TObjectPtr<UPolygroupLayersProperties> UUVEditorRecomputeUVsTool::PolygroupLayerProperties = nullptr protected
Definition at line 82 of file UVEditorRecomputeUVsTool.h.
Settings
TObjectPtr<URecomputeUVsToolProperties> UUVEditorRecomputeUVsTool::Settings = nullptr protected
Definition at line 79 of file UVEditorRecomputeUVsTool.h.
Targets
TArray<TObjectPtr<UUVEditorToolMeshInput> > UUVEditorRecomputeUVsTool::Targets protected
Definition at line 76 of file UVEditorRecomputeUVsTool.h.
Referenced by SetTargets().
ToolStartTimeAnalytics
FDateTime UUVEditorRecomputeUVsTool::ToolStartTimeAnalytics protected
Definition at line 100 of file UVEditorRecomputeUVsTool.h.
UVToolSelectionAPI
TObjectPtr<UUVToolSelectionAPI> UUVEditorRecomputeUVsTool::UVToolSelectionAPI = nullptr protected
Definition at line 88 of file UVEditorRecomputeUVsTool.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/UVEditorRecomputeUVsTool.h