Unreal Engine 5.6 C++ API: FPixelStreamingDataChannel Class Reference
FPixelStreamingDataChannel Class Reference
A specialized representation of a WebRTC data channel for Pixel Streaming.
#include "PixelStreamingDataChannel.h"
Public Member Functions
virtual ~FPixelStreamingDataChannel ()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnClosed, FPixelStreamingDataChannel &)
Broadcast when the data channel state changes to closed.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnOpen, FPixelStreamingDataChannel &)
Broadcast when the data channel state changes to open.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMessage, uint8, const webrtc::DataBuffer &)
Broadcast when data comes in from the data channel.
bool SendArbitraryData (uint8 Type, const TArray64< uint8 > &DataBytes) const
Sends a large buffer of data to the data channel.
template<typename... Args>
bool SendMessage (uint8 Type, Args... VarArgs)
Sends a series of arguments to the data channel with the given type.
Public Member Functions inherited from TSharedFromThis< FPixelStreamingDataChannel >
TSharedRef< FPixelStreamingDataChannel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FPixelStreamingDataChannel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedPtr< FPixelStreamingDataChannel > Create (FPixelStreamingPeerConnection &Connection, int32 SendStreamId, int32 RecvStreamId)
static TSharedPtr< FPixelStreamingDataChannel > Create (rtc::scoped_refptr< webrtc::DataChannelInterface > InChannel)
Data Fields
FOnClosed OnClosed
FOnMessage OnMessageReceived
FOnOpen OnOpen
Protected Member Functions
virtual void OnMessage (const webrtc::DataBuffer &Buffer) override
virtual void OnStateChange () override
Protected Member Functions inherited from TSharedFromThis< FPixelStreamingDataChannel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
FPixelStreamingDataChannel (FPixelStreamingPeerConnection &Connection, int32 SendStreamId, int32 RecvStreamId)
FPixelStreamingDataChannel (rtc::scoped_refptr< webrtc::DataChannelInterface > InChannel)
Private Attributes
rtc::scoped_refptr< webrtc::DataChannelInterface > RecvChannel
rtc::scoped_refptr< webrtc::DataChannelInterface > SendChannel
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FPixelStreamingDataChannel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A specialized representation of a WebRTC data channel for Pixel Streaming.
Definition at line 13 of file PixelStreamingDataChannel.h.
Constructor & Destructor Documentation
~FPixelStreamingDataChannel()
virtual FPixelStreamingDataChannel::~FPixelStreamingDataChannel () virtual
FPixelStreamingDataChannel() [1/2]
FPixelStreamingDataChannel::FPixelStreamingDataChannel (rtc::scoped_refptr< webrtc::DataChannelInterface > InChannel) private
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), and DECLARE_MULTICAST_DELEGATE_OneParam().
FPixelStreamingDataChannel() [2/2]
FPixelStreamingDataChannel::FPixelStreamingDataChannel (FPixelStreamingPeerConnection & Connection, int32 SendStreamId, int32 RecvStreamId) private
Member Function Documentation
Create() [1/2]
TSharedPtr< FPixelStreamingDataChannel > FPixelStreamingDataChannel::Create (FPixelStreamingPeerConnection & Connection, int32 SendStreamId, int32 RecvStreamId) static
Create() [2/2]
TSharedPtr< FPixelStreamingDataChannel > FPixelStreamingDataChannel::Create (rtc::scoped_refptr< webrtc::DataChannelInterface > InChannel) static
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
FPixelStreamingDataChannel::DECLARE_MULTICAST_DELEGATE_OneParam (FOnClosed , FPixelStreamingDataChannel &)
Broadcast when the data channel state changes to closed.
References FPixelStreamingDataChannel().
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
FPixelStreamingDataChannel::DECLARE_MULTICAST_DELEGATE_OneParam (FOnOpen , FPixelStreamingDataChannel &)
Broadcast when the data channel state changes to open.
References FPixelStreamingDataChannel().
DECLARE_MULTICAST_DELEGATE_TwoParams()
FPixelStreamingDataChannel::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMessage , uint8 , const webrtc::DataBuffer &)
Broadcast when data comes in from the data channel.
OnMessage()
virtual void FPixelStreamingDataChannel::OnMessage (const webrtc::DataBuffer & Buffer) override protected virtual
References Buffer.
OnStateChange()
virtual void FPixelStreamingDataChannel::OnStateChange () override protected virtual
SendArbitraryData()
bool FPixelStreamingDataChannel::SendArbitraryData (uint8 Type, const TArray64< uint8 > & DataBytes) const
Sends a large buffer of data to the data channel.
Parameters
Type See SendMessage. The type of the message.
DataBytes The raw byte buffer to send.
Returns
True when all data was successfully sent.
SendMessage()
template<typename... Args> bool FPixelStreamingDataChannel::SendMessage (uint8 Type, Args... VarArgs) inline
Sends a series of arguments to the data channel with the given type.
Parameters
Type Should be the ID from a registered PixelStreamingProtocol message
Returns
True of the message was successfully sent.
Definition at line 26 of file PixelStreamingDataChannel.h.
References UE::PixelStreaming::BufferBuilder::Buffer, Forward(), UE::PixelStreaming::BufferBuilder::Insert(), SendChannel, and UE::PixelStreaming::ValueSize().
Field Documentation
OnClosed
FOnClosed FPixelStreamingDataChannel::OnClosed
Definition at line 57 of file PixelStreamingDataChannel.h.
OnMessageReceived
FOnMessage FPixelStreamingDataChannel::OnMessageReceived
Definition at line 63 of file PixelStreamingDataChannel.h.
OnOpen
FOnOpen FPixelStreamingDataChannel::OnOpen
Definition at line 51 of file PixelStreamingDataChannel.h.
RecvChannel
rtc::scoped_refptr<webrtc::DataChannelInterface> FPixelStreamingDataChannel::RecvChannel private
Definition at line 72 of file PixelStreamingDataChannel.h.
SendChannel
rtc::scoped_refptr<webrtc::DataChannelInterface> FPixelStreamingDataChannel::SendChannel private
Definition at line 71 of file PixelStreamingDataChannel.h.
Referenced by SendMessage().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming/Source/PixelStreaming/Public/PixelStreamingDataChannel.h