Unreal Engine 5.6 C++ API: FClothCreateSettingsCustomization Class Reference
FClothCreateSettingsCustomization Class Reference
#include "SCreateClothingSettingsPanel.h"
Public Member Functions
FClothCreateSettingsCustomization (TWeakObjectPtr< USkeletalMesh > InMeshPtr, bool bInIsSubImport)
virtual void CustomizeDetails (IDetailLayoutBuilder &DetailBuilder) override
Called when details should be customized.
Public Member Functions inherited from IDetailCustomization
virtual ~IDetailCustomization ()
virtual void CustomizeDetails (const TSharedPtr< IDetailLayoutBuilder > &DetailBuilder)
Called when details should be customized, this version allows the customization to store a weak ptr to the layout builder.
virtual void PendingDelete ()
Called when no longer used and will be deleted.
Public Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedRef< IDetailCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDetailCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IDetailCustomization > MakeInstance (TWeakObjectPtr< USkeletalMesh > MeshPtr, bool bIsSubImport)
Protected Member Functions
bool CanSelectLod () const
FText GetTargetAssetText () const
FText GetTargetLodText () const
void OnAssetSelected (int32 InMeshClothingIndex)
TSharedRef< SWidget > OnGetTargetAssetMenu ()
TSharedRef< SWidget > OnGetTargetLodMenu ()
void OnLodSelected (int32 InLodIndex)
Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bIsSubImport
TWeakObjectPtr< USkeletalMesh > MeshPtr
FSkeletalMeshClothBuildParams * ParamsStruct
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 13 of file SCreateClothingSettingsPanel.h.
Constructor & Destructor Documentation
FClothCreateSettingsCustomization()
FClothCreateSettingsCustomization::FClothCreateSettingsCustomization (TWeakObjectPtr< USkeletalMesh > InMeshPtr, bool bInIsSubImport) inline
Definition at line 17 of file SCreateClothingSettingsPanel.h.
References bIsSubImport, MeshPtr, and ParamsStruct.
Referenced by MakeInstance().
Member Function Documentation
CanSelectLod()
bool FClothCreateSettingsCustomization::CanSelectLod () const protected
CustomizeDetails()
virtual void FClothCreateSettingsCustomization::CustomizeDetails (IDetailLayoutBuilder & DetailBuilder) override virtual
Called when details should be customized.
Implements IDetailCustomization.
GetTargetAssetText()
FText FClothCreateSettingsCustomization::GetTargetAssetText () const protected
GetTargetLodText()
FText FClothCreateSettingsCustomization::GetTargetLodText () const protected
MakeInstance()
TSharedRef< IDetailCustomization > FClothCreateSettingsCustomization::MakeInstance (TWeakObjectPtr< USkeletalMesh > MeshPtr, bool bIsSubImport) inline static
Definition at line 23 of file SCreateClothingSettingsPanel.h.
References FClothCreateSettingsCustomization(), bIsSubImport, MakeShareable(), and MeshPtr.
OnAssetSelected()
void FClothCreateSettingsCustomization::OnAssetSelected (int32 InMeshClothingIndex) protected
OnGetTargetAssetMenu()
TSharedRef< SWidget > FClothCreateSettingsCustomization::OnGetTargetAssetMenu () protected
OnGetTargetLodMenu()
TSharedRef< SWidget > FClothCreateSettingsCustomization::OnGetTargetLodMenu () protected
OnLodSelected()
void FClothCreateSettingsCustomization::OnLodSelected (int32 InLodIndex) protected
Field Documentation
bIsSubImport
bool FClothCreateSettingsCustomization::bIsSubImport protected
Definition at line 41 of file SCreateClothingSettingsPanel.h.
Referenced by FClothCreateSettingsCustomization(), and MakeInstance().
MeshPtr
TWeakObjectPtr<USkeletalMesh> FClothCreateSettingsCustomization::MeshPtr protected
Definition at line 42 of file SCreateClothingSettingsPanel.h.
Referenced by FClothCreateSettingsCustomization(), and MakeInstance().
ParamsStruct
FSkeletalMeshClothBuildParams* FClothCreateSettingsCustomization::ParamsStruct protected
Definition at line 43 of file SCreateClothingSettingsPanel.h.
Referenced by FClothCreateSettingsCustomization().
The documentation for this class was generated from the following file:
Editor/Persona/Public/SCreateClothingSettingsPanel.h