Unreal Engine 5.6 C++ API: FPlanarReflectionRenderTarget Class Reference
FPlanarReflectionRenderTarget Class Reference
#include "PlanarReflectionSceneProxy.h"
Public Member Functions
FPlanarReflectionRenderTarget (FIntPoint InSize)
virtual float GetDisplayGamma () const
virtual FString GetFriendlyName () const override
virtual FRHIGPUMask GetGPUMask (FRHICommandListImmediate &RHICmdList) const override
Returns the GPU nodes on which to render this render target.
virtual uint32 GetSizeX () const
Returns the width of the texture in pixels.
virtual FIntPoint GetSizeXY () const
virtual uint32 GetSizeY () const
Returns the height of the texture in pixels.
virtual void InitRHI (FRHICommandListBase &)
Initializes the RHI resources used by this resource.
void SetActiveGPUMask (FRHIGPUMask InGPUMask)
Public Member Functions inherited from FTexture
RENDERCORE_API FTexture ()
RENDERCORE_API FTexture (const FTexture &)
RENDERCORE_API FTexture (FTexture &&)
virtual RENDERCORE_API ~FTexture ()
virtual RENDERCORE_API uint32 GetSizeZ () const
Returns the depth of the texture in pixels.
const FTextureRHIRef & GetTextureRHI ()
RENDERCORE_API FTexture & operator= (const FTexture &Other)
RENDERCORE_API FTexture & operator= (FTexture &&Other)
virtual RENDERCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Public Member Functions inherited from FRenderTarget
FRenderTarget ()
Default constructor.
virtual ~FRenderTarget ()
Destructor.
virtual EDisplayColorGamut GetDisplayColorGamut () const
virtual EDisplayOutputFormat GetDisplayOutputFormat () const
virtual const FTextureRHIRef & GetRenderTargetTexture () const
Accessor for the surface RHI when setting this render target.
virtual FRDGTextureRef GetRenderTargetTexture (FRDGBuilder &GraphBuilder) const
Returns a valid RDG texture for this render target.
virtual FUnorderedAccessViewRHIRef GetRenderTargetUAV () const
virtual bool GetSceneHDREnabled () const
virtual const FTextureRHIRef & GetShaderResourceTexture () const
Accessor for the surface RHI to use when reading the reading target (may differ from GetRenderTargetTexture() for some implementations like cubemaps)
virtual bool HasToggleFreezeCommand ()
Returns if there is a command to toggle freezerendering.
virtual void ProcessToggleFreezeCommand ()
Handles freezing/unfreezing of rendering.
virtual bool ReadFloat16Pixels (TArray< FFloat16Color > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadLinearColorPixels (TArray< FLinearColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
bool ReadLinearColorPixelsPtr (FLinearColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_MinMax, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into the given color buffer.
virtual bool ReadPixels (TArray< FColor > &OutImageData, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
bool ReadPixelsPtr (FColor *OutImageBytes, FReadSurfaceDataFlags InFlags=FReadSurfaceDataFlags(RCM_UNorm, CubeFace_MAX), FIntRect InSrcRect=FIntRect(0, 0, 0, 0))
Reads the render target's displayed pixels into a preallocated color buffer.
UE_DEPRECATED (5.4, "Use the other ReadFloat16Pixels variant (ECubeFace can be set in FReadSurfaceDataFlags)") 1 bool ReadFloat16Pixels(TArray< FFloat16Color > &OutImageData
Reads the render target's displayed pixels into the given color buffer.
Private Attributes
FRHIGPUMask ActiveGPUMask
FIntPoint Size
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Static Public Member Functions inherited from FRenderTarget
static float GetEngineDisplayGamma ()
Data Fields inherited from FTexture
bool bGreyScaleFormat = false
bGreyScaleFormat indicates the texture is actually in R channel but should be read as Grey (replicate R to RGBA) this is set from CompressionSettings, not PixelFormat this is only used by Editor/Debug shaders, not real game materials, which use SamplerType from MaterialExpressions
bool bIgnoreGammaConversions = false
true if the texture is in the same gamma space as the intended rendertarget (e.g.
bool bSRGB = false
Is the pixel data in this texture sRGB?
FSamplerStateRHIRef DeferredPassSamplerStateRHI
Sampler state to be used in deferred passes when discontinuities in ddx / ddy would cause too blurry of a mip to be used.
double LastRenderTime = -FLT_MAX
The last time the texture has been bound.
FMipBiasFade MipBiasFade
Base values for fading in/out mip-levels.
FSamplerStateRHIRef SamplerStateRHI
The sampler state to use for the texture.
FTextureRHIRef TextureRHI
The texture's RHI resource.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Data Fields inherited from FRenderTarget
ECubeFace CubeFace
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FTexture
static RENDERCORE_API FRHISamplerState * GetOrCreateSamplerState (const FSamplerStateInitializerRHI &Initializer)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes inherited from FRenderTarget
FTextureRHIRef RenderTargetTextureRHI
Detailed Description
Definition at line 21 of file PlanarReflectionSceneProxy.h.
Constructor & Destructor Documentation
FPlanarReflectionRenderTarget()
FPlanarReflectionRenderTarget::FPlanarReflectionRenderTarget (FIntPoint InSize) inline
Definition at line 25 of file PlanarReflectionSceneProxy.h.
References Size.
Member Function Documentation
GetDisplayGamma()
virtual float FPlanarReflectionRenderTarget::GetDisplayGamma () const inline virtual
Returns
display gamma expected for rendering to this render target
Reimplemented from FRenderTarget.
Definition at line 65 of file PlanarReflectionSceneProxy.h.
GetFriendlyName()
virtual FString FPlanarReflectionRenderTarget::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FTexture.
Definition at line 67 of file PlanarReflectionSceneProxy.h.
References TEXT.
GetGPUMask()
virtual FRHIGPUMask FPlanarReflectionRenderTarget::GetGPUMask (FRHICommandListImmediate & RHICmdList) const inline override virtual
Returns the GPU nodes on which to render this render target.
Reimplemented from FRenderTarget.
Definition at line 69 of file PlanarReflectionSceneProxy.h.
References ActiveGPUMask.
GetSizeX()
virtual uint32 FPlanarReflectionRenderTarget::GetSizeX () const inline virtual
Returns the width of the texture in pixels.
Reimplemented from FTexture.
Definition at line 55 of file PlanarReflectionSceneProxy.h.
References Size.
GetSizeXY()
virtual FIntPoint FPlanarReflectionRenderTarget::GetSizeXY () const inline virtual
Implements FRenderTarget.
Definition at line 52 of file PlanarReflectionSceneProxy.h.
References Size.
Referenced by InitRHI().
GetSizeY()
virtual uint32 FPlanarReflectionRenderTarget::GetSizeY () const inline virtual
Returns the height of the texture in pixels.
Reimplemented from FTexture.
Definition at line 60 of file PlanarReflectionSceneProxy.h.
References Size.
InitRHI()
virtual void FPlanarReflectionRenderTarget::InitRHI (FRHICommandListBase & RHICmdList) inline virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
Definition at line 29 of file PlanarReflectionSceneProxy.h.
References FTexture::GetOrCreateSamplerState(), GetSizeXY(), PF_FloatRGBA, FRenderTarget::RenderTargetTextureRHI, FTexture::SamplerStateRHI, TEXT, and FTexture::TextureRHI.
SetActiveGPUMask()
void FPlanarReflectionRenderTarget::SetActiveGPUMask (FRHIGPUMask InGPUMask) inline
Definition at line 75 of file PlanarReflectionSceneProxy.h.
References ActiveGPUMask, check, and IsInRenderingThread().
Field Documentation
ActiveGPUMask
FRHIGPUMask FPlanarReflectionRenderTarget::ActiveGPUMask private
Definition at line 83 of file PlanarReflectionSceneProxy.h.
Referenced by GetGPUMask(), and SetActiveGPUMask().
Size
FIntPoint FPlanarReflectionRenderTarget::Size private
Definition at line 84 of file PlanarReflectionSceneProxy.h.
Referenced by FPlanarReflectionRenderTarget(), GetSizeX(), GetSizeXY(), and GetSizeY().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/PlanarReflectionSceneProxy.h