Unreal Engine 5.6 C++ API: UParticleModuleLocationEmitterDirect Class Reference
UParticleModuleLocationEmitterDirect Class Reference
#include "ParticleModuleLocationEmitterDirect.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FName EmitterName
The name of the emitter to use as a source for the location of the particles.
virtual void Spawn (const FSpawnContext &Context) override
virtual void Update (const FUpdateContext &Context) override
Detailed Description
Definition at line 21 of file ParticleModuleLocationEmitterDirect.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UParticleModuleLocationEmitterDirect::GENERATED_UCLASS_BODY () private
The name of the emitter to use as a source for the location of the particles.
References Category, Location, and UPROPERTY.
Spawn()
virtual void UParticleModuleLocationEmitterDirect::Spawn (const FSpawnContext & Context) override private virtual
References Spawn().
Referenced by Spawn().
Update()
virtual void UParticleModuleLocationEmitterDirect::Update (const FUpdateContext & Context) override private virtual
References Update().
Referenced by Update().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/Location/ParticleModuleLocationEmitterDirect.h