Unreal Engine 5.6 C++ API: IMovieSceneEasingFunction Class Reference
IMovieSceneEasingFunction Class Reference
#include "MovieSceneEasingFunction.h"
Public Member Functions
GENERATED_BODY () static MOVIESCENE_API float EvaluateWith(const TScriptInterface< IMovieSceneEasingFunction > &ScriptInterface
Evaluate using the specified script interface.
virtual FText GetDisplayName () const
Data Fields
float Time
Protected Member Functions
virtual float Evaluate (float Interp) const
Evaluate the easing with an interpolation value between 0 and 1.
UFUNCTION ()) MOVIESCENE_API float OnEvaluate(float Interp) const
Evaluate the easing with an interpolation value between 0 and 1.
Detailed Description
Definition at line 17 of file MovieSceneEasingFunction.h.
Member Function Documentation
Evaluate()
virtual float IMovieSceneEasingFunction::Evaluate (float Interp) const inline protected virtual
Evaluate the easing with an interpolation value between 0 and 1.
Reimplemented in UMovieSceneBuiltInEasingFunction.
Definition at line 38 of file MovieSceneEasingFunction.h.
References Evaluate().
Referenced by Evaluate(), and UMovieSceneEasingExternalCurve::GENERATED_BODY().
GENERATED_BODY()
IMovieSceneEasingFunction::GENERATED_BODY () const &
Evaluate using the specified script interface.
Handles both native and k2 implemented interfaces.
GetDisplayName()
virtual FText IMovieSceneEasingFunction::GetDisplayName () const inline virtual
Reimplemented in UMovieSceneBuiltInEasingFunction, and UMovieSceneEasingExternalCurve.
Definition at line 28 of file MovieSceneEasingFunction.h.
References FText::GetEmpty().
UFUNCTION()
IMovieSceneEasingFunction::UFUNCTION () const protected
Evaluate the easing with an interpolation value between 0 and 1.
References Category, and meta.
Field Documentation
Time
float IMovieSceneEasingFunction::Time
Definition at line 25 of file MovieSceneEasingFunction.h.
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Generators/MovieSceneEasingFunction.h