Unreal Engine 5.6 C++ API: TStrongObjectPtr< ObjectType, ReferencerNameProvider > Class Template Reference
TStrongObjectPtr< ObjectType, ReferencerNameProvider > Class Template Reference
Take a ref-count on a UObject to prevent it from being GC'd while this guard is in scope.
#include "StrongObjectPtrTemplates.h"
Public Types
using ElementType = ObjectType
Public Member Functions
FORCEINLINE_DEBUGGABLE TStrongObjectPtr (const TStrongObjectPtr &InOther)
template<typename OtherObjectType, typename OtherReferencerNameProvider UE_REQUIRES>
FORCEINLINE_DEBUGGABLE TStrongObjectPtr (const TStrongObjectPtr< OtherObjectType, OtherReferencerNameProvider > &InOther)
FORCEINLINE_DEBUGGABLE TStrongObjectPtr (ObjectType *InObject)
TStrongObjectPtr (TStrongObjectPtr &&InOther)
FORCEINLINE_DEBUGGABLE TStrongObjectPtr (TYPE_OF_NULLPTR=nullptr)
FORCEINLINE_DEBUGGABLE ~TStrongObjectPtr ()
FORCEINLINE_DEBUGGABLE ObjectType * Get () const
FORCEINLINE_DEBUGGABLE bool IsValid () const
FORCEINLINE_DEBUGGABLE operator bool () const
FORCEINLINE_DEBUGGABLE ObjectType & operator* () const
FORCEINLINE_DEBUGGABLE ObjectType * operator-> () const
FORCEINLINE_DEBUGGABLE TStrongObjectPtr & operator= (const TStrongObjectPtr &InOther)
template<typename OtherObjectType, typename OtherReferencerNameProvider UE_REQUIRES>
FORCEINLINE_DEBUGGABLE TStrongObjectPtr & operator= (const TStrongObjectPtr< OtherObjectType, OtherReferencerNameProvider > &InOther)
TStrongObjectPtr & operator= (TStrongObjectPtr &&InOther)
FORCEINLINE_DEBUGGABLE void Reset ()
FORCEINLINE_DEBUGGABLE void Reset (ObjectType *InNewObject)
Private Member Functions
FORCEINLINE_DEBUGGABLE void Attach (ObjectType *InNewObject)
FORCEINLINE_DEBUGGABLE ObjectType * Detach ()
Private Attributes
const UObject * Object { nullptr }
Friends
FORCEINLINE_DEBUGGABLE friend uint32 GetTypeHash (const TStrongObjectPtr &InStrongObjectPtr)
FORCEINLINE bool operator!= (const TStrongObjectPtr &InLHS, const TStrongObjectPtr &InRHS)
template<typename RHSObjectType, typename RHSReferencerNameProvider UE_REQUIRES>
FORCEINLINE bool operator!= (const TStrongObjectPtr &InLHS, const TStrongObjectPtr< RHSObjectType, RHSReferencerNameProvider > &InRHS)
FORCEINLINE bool operator!= (const TStrongObjectPtr &InLHS, TYPE_OF_NULLPTR)
template<typename LHSObjectType, typename LHSReferencerNameProvider UE_REQUIRES>
FORCEINLINE bool operator!= (const TStrongObjectPtr< LHSObjectType, LHSReferencerNameProvider > &InLHS, const TStrongObjectPtr &InRHS)
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR, const TStrongObjectPtr &InRHS)
FORCEINLINE bool operator== (const TStrongObjectPtr &InLHS, const TStrongObjectPtr &InRHS)
template<typename RHSObjectType, typename RHSReferencerNameProvider UE_REQUIRES>
FORCEINLINE bool operator== (const TStrongObjectPtr &InLHS, const TStrongObjectPtr< RHSObjectType, RHSReferencerNameProvider > &InRHS)
FORCEINLINE bool operator== (const TStrongObjectPtr &InLHS, TYPE_OF_NULLPTR)
template<typename LHSObjectType, typename LHSReferencerNameProvider UE_REQUIRES>
FORCEINLINE bool operator== (const TStrongObjectPtr< LHSObjectType, LHSReferencerNameProvider > &InLHS, const TStrongObjectPtr &InRHS)
FORCEINLINE bool operator== (TYPE_OF_NULLPTR, const TStrongObjectPtr &InRHS)
template<class T, class TWeakObjectPtrBase>
struct TWeakObjectPtr
Detailed Description
template<typename ObjectType, typename ReferencerNameProvider>
class TStrongObjectPtr< ObjectType, ReferencerNameProvider >
Take a ref-count on a UObject to prevent it from being GC'd while this guard is in scope.
TStrongObjectPtr is a strong pointer to a UObject.
It can return nullptr if it has not been initialized or has been constructed from a weak ptr that is already garbage collected. It prevents an object from being garbage collected. It can't be directly used across a network.
Most often it is used when you explicitly want to prevent something from being garbage collected.
Definition at line 25 of file StrongObjectPtrTemplates.h.
Member Typedef Documentation
ElementType
template<typename ObjectType, typename ReferencerNameProvider> using TStrongObjectPtr< ObjectType, ReferencerNameProvider >::ElementType = ObjectType
Definition at line 28 of file StrongObjectPtrTemplates.h.
Constructor & Destructor Documentation
TStrongObjectPtr() [1/5]
template<typename ObjectType, typename ReferencerNameProvider> TStrongObjectPtr< ObjectType, ReferencerNameProvider >::TStrongObjectPtr (TStrongObjectPtr< ObjectType, ReferencerNameProvider > && InOther) inline nodiscard
Definition at line 30 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), Object, and Reset().
Referenced by TStrongObjectPtr(), TStrongObjectPtr(), TStrongObjectPtr(), GetTypeHash, operator!=, operator!=, operator!=, operator!=, operator!=, operator=(), operator=(), operator=(), operator==, operator==, operator==, operator==, and operator==.
~TStrongObjectPtr()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE TStrongObjectPtr< ObjectType, ReferencerNameProvider >::~TStrongObjectPtr () inline
Definition at line 48 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, and Reset().
TStrongObjectPtr() [2/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE TStrongObjectPtr< ObjectType, ReferencerNameProvider >::TStrongObjectPtr (TYPE_OF_NULLPTR = nullptr) inline nodiscard
Definition at line 53 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
TStrongObjectPtr() [3/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE TStrongObjectPtr< ObjectType, ReferencerNameProvider >::TStrongObjectPtr (ObjectType * InObject) inline explicit nodiscard
Definition at line 58 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, Reset(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
TStrongObjectPtr() [4/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE TStrongObjectPtr< ObjectType, ReferencerNameProvider >::TStrongObjectPtr (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InOther) inline nodiscard
Definition at line 64 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE_DEBUGGABLE, Get(), and Reset().
TStrongObjectPtr() [5/5]
template<typename ObjectType, typename ReferencerNameProvider> template<typename OtherObjectType, typename OtherReferencerNameProvider UE_REQUIRES> FORCEINLINE_DEBUGGABLE TStrongObjectPtr< ObjectType, ReferencerNameProvider >::TStrongObjectPtr (const TStrongObjectPtr< OtherObjectType, OtherReferencerNameProvider > & InOther) inline nodiscard
Definition at line 74 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE_DEBUGGABLE, Get(), and Reset().
Member Function Documentation
Attach()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE void TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Attach (ObjectType * InNewObject) inline private
Definition at line 138 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, Object, and Reset().
Referenced by TWeakObjectPtr< const T >::Pin(), TWeakObjectPtr< const T >::Pin(), and TWeakObjectPtr< const T >::TryPin().
Detach()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE ObjectType * TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Detach () inline private
Definition at line 145 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, Get(), and Object.
Get()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE ObjectType * TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Get () const inline nodiscard
Definition at line 118 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, and Object.
Referenced by TStrongObjectPtr(), TStrongObjectPtr(), Detach(), GetDefaultTexture2DArray(), GetTypeHash, operator!=, operator!=, operator!=, operator*(), operator->(), operator=(), operator=(), operator==, operator==, and operator==.
IsValid()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE bool TStrongObjectPtr< ObjectType, ReferencerNameProvider >::IsValid () const inline nodiscard
Definition at line 108 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, and Object.
Referenced by GetDefaultTexture2DArray(), operator bool(), operator!=, operator!=, operator*(), operator->(), operator==, and operator==.
operator bool()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE TStrongObjectPtr< ObjectType, ReferencerNameProvider >::operator bool () const inline explicit nodiscard
Definition at line 113 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, and IsValid().
operator*()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE ObjectType & TStrongObjectPtr< ObjectType, ReferencerNameProvider >::operator* () const inline nodiscard
Definition at line 96 of file StrongObjectPtrTemplates.h.
References check, FORCEINLINE_DEBUGGABLE, Get(), and IsValid().
operator->()
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE ObjectType * TStrongObjectPtr< ObjectType, ReferencerNameProvider >::operator-> () const inline nodiscard
Definition at line 102 of file StrongObjectPtrTemplates.h.
References check, FORCEINLINE_DEBUGGABLE, Get(), and IsValid().
operator=() [1/3]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE TStrongObjectPtr & TStrongObjectPtr< ObjectType, ReferencerNameProvider >::operator= (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InOther) inline
Definition at line 79 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE_DEBUGGABLE, Get(), and Reset().
operator=() [2/3]
template<typename ObjectType, typename ReferencerNameProvider> template<typename OtherObjectType, typename OtherReferencerNameProvider UE_REQUIRES> FORCEINLINE_DEBUGGABLE TStrongObjectPtr & TStrongObjectPtr< ObjectType, ReferencerNameProvider >::operator= (const TStrongObjectPtr< OtherObjectType, OtherReferencerNameProvider > & InOther) inline
Definition at line 90 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE_DEBUGGABLE, Get(), and Reset().
operator=() [3/3]
template<typename ObjectType, typename ReferencerNameProvider> TStrongObjectPtr & TStrongObjectPtr< ObjectType, ReferencerNameProvider >::operator= (TStrongObjectPtr< ObjectType, ReferencerNameProvider > && InOther) inline
Definition at line 37 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), Object, and Reset().
Reset() [1/2]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE void TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Reset () inline
Definition at line 123 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, Object, and UEStrongObjectPtr_Private::ReleaseUObject().
Referenced by TStrongObjectPtr(), TStrongObjectPtr(), TStrongObjectPtr(), TStrongObjectPtr(), ~TStrongObjectPtr(), Attach(), GetDefaultTexture2DArray(), operator=(), operator=(), operator=(), and Reset().
Reset() [2/2]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE void TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Reset (ObjectType * InNewObject) inline
Definition at line 153 of file StrongObjectPtrTemplates.h.
References FORCEINLINE_DEBUGGABLE, Object, UEStrongObjectPtr_Private::ReleaseUObject(), and Reset().
Friends And Related Symbol Documentation
GetTypeHash
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE_DEBUGGABLE friend uint32 GetTypeHash (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InStrongObjectPtr) friend
Definition at line 177 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE_DEBUGGABLE, Get(), and GetTypeHash.
Referenced by GetTypeHash.
operator!= [1/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE bool operator!= (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InLHS, const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InRHS) friend
Definition at line 223 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and Get().
operator!= [2/5]
template<typename ObjectType, typename ReferencerNameProvider> template<typename RHSObjectType, typename RHSReferencerNameProvider UE_REQUIRES> FORCEINLINE bool operator!= (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InLHS, const TStrongObjectPtr< RHSObjectType, RHSReferencerNameProvider > & InRHS) friend
Definition at line 243 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and Get().
operator!= [3/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE bool operator!= (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InLHS, TYPE_OF_NULLPTR) friend
Definition at line 228 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and IsValid().
operator!= [4/5]
template<typename ObjectType, typename ReferencerNameProvider> template<typename LHSObjectType, typename LHSReferencerNameProvider UE_REQUIRES> FORCEINLINE bool operator!= (const TStrongObjectPtr< LHSObjectType, LHSReferencerNameProvider > & InLHS, const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InRHS) friend
Definition at line 253 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and Get().
operator!= [5/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE bool operator!= (TYPE_OF_NULLPTR , const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InRHS) friend
Definition at line 233 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and IsValid().
operator== [1/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE bool operator== (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InLHS, const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InRHS) friend
Definition at line 187 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and Get().
operator== [2/5]
template<typename ObjectType, typename ReferencerNameProvider> template<typename RHSObjectType, typename RHSReferencerNameProvider UE_REQUIRES> FORCEINLINE bool operator== (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InLHS, const TStrongObjectPtr< RHSObjectType, RHSReferencerNameProvider > & InRHS) friend
Definition at line 207 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and Get().
operator== [3/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE bool operator== (const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InLHS, TYPE_OF_NULLPTR) friend
Definition at line 192 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and IsValid().
operator== [4/5]
template<typename ObjectType, typename ReferencerNameProvider> template<typename LHSObjectType, typename LHSReferencerNameProvider UE_REQUIRES> FORCEINLINE bool operator== (const TStrongObjectPtr< LHSObjectType, LHSReferencerNameProvider > & InLHS, const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InRHS) friend
Definition at line 217 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and Get().
operator== [5/5]
template<typename ObjectType, typename ReferencerNameProvider> FORCEINLINE bool operator== (TYPE_OF_NULLPTR , const TStrongObjectPtr< ObjectType, ReferencerNameProvider > & InRHS) friend
Definition at line 197 of file StrongObjectPtrTemplates.h.
References TStrongObjectPtr(), FORCEINLINE, and IsValid().
TWeakObjectPtr
template<typename ObjectType, typename ReferencerNameProvider> template<class T, class TWeakObjectPtrBase> friend struct TWeakObjectPtr friend
Definition at line 135 of file StrongObjectPtrTemplates.h.
References TWeakObjectPtr.
Referenced by TWeakObjectPtr.
Field Documentation
Object
template<typename ObjectType, typename ReferencerNameProvider> const UObject* TStrongObjectPtr< ObjectType, ReferencerNameProvider >::Object { nullptr } private
Definition at line 185 of file StrongObjectPtrTemplates.h.
Referenced by TStrongObjectPtr(), Attach(), Detach(), Get(), IsValid(), operator=(), Reset(), and Reset().
The documentation for this class was generated from the following file:
Runtime/Core/Public/UObject/StrongObjectPtrTemplates.h