Unreal Engine 5.6 C++ API: FExclusiveLoadPackageTimeTracker Class Reference
FExclusiveLoadPackageTimeTracker Class Reference
A singleton to keep track of the exclusive load time of every package.
#include "ExclusiveLoadPackageTimeTracker.h"
Data Structures
struct FScopedEndLoadTracker
Scoped helper for EndLoad.
struct FScopedPackageTracker
Scoped helper for LoadPackage.
struct FScopedPostLoadTracker
Scoped helper for PostLoad.
Static Public Member Functions
static FORCEINLINE void DumpReport (const TArray< FString > &Args)
Displays the data gathered in various ways.
static FORCEINLINE double GetExclusiveLoadTime (FName PackageName)
Returns the load time for the specified package, excluding its dependencies.
static FORCEINLINE double GetInclusiveLoadTime (FName PackageName)
Returns the load time for the specified package, including its dependencies.
static FORCEINLINE void PopEndLoad ()
Records some time spent in "EndLoad".
static FORCEINLINE void PopLoadPackage (UPackage *LoadedPackage)
Records a time and stats for the loaded package.
static FORCEINLINE void PopPostLoad (UObject *PostLoadObject)
Records a time and stats for the loaded package.
static FORCEINLINE void PushEndLoad ()
Starts a time for time spent in "EndLoad".
static FORCEINLINE void PushLoadPackage (FName PackageName)
Starts a time for the specified package name.
static FORCEINLINE bool PushPostLoad (UObject *PostLoadObject)
Starts a time for the specified package name.
static FORCEINLINE void ResetReport ()
Resets the data.
Detailed Description
A singleton to keep track of the exclusive load time of every package.
Also reports inclusive load time for convenience. The code that loads packages "pushes" a load on the tracker which will record the time the package started loading. Later that package will be "popped" which will cause the tracker to record the time spent. If another package is pushed while this is happening, it will pause the time recorded from the first package and start a new time for the second. This is recursive. DumpReport() can be used to log out all the recorded values in a couple different ways to get an idea about what packages are the slowest to load.
Definition at line 27 of file ExclusiveLoadPackageTimeTracker.h.
Member Function Documentation
DumpReport()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::DumpReport (const TArray< FString > & Args) inline static
Displays the data gathered in various ways.
Definition at line 136 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE.
GetExclusiveLoadTime()
FORCEINLINE double FExclusiveLoadPackageTimeTracker::GetExclusiveLoadTime (FName PackageName) inline static
Returns the load time for the specified package, excluding its dependencies.
Definition at line 152 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE, and PackageName.
GetInclusiveLoadTime()
FORCEINLINE double FExclusiveLoadPackageTimeTracker::GetInclusiveLoadTime (FName PackageName) inline static
Returns the load time for the specified package, including its dependencies.
Definition at line 162 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE, and PackageName.
PopEndLoad()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::PopEndLoad () inline static
Records some time spent in "EndLoad".
Definition at line 128 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE.
Referenced by FExclusiveLoadPackageTimeTracker::FScopedEndLoadTracker::~FScopedEndLoadTracker().
PopLoadPackage()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::PopLoadPackage (UPackage * LoadedPackage) inline static
Records a time and stats for the loaded package.
Definition at line 90 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE.
Referenced by FExclusiveLoadPackageTimeTracker::FScopedPackageTracker::~FScopedPackageTracker().
PopPostLoad()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::PopPostLoad (UObject * PostLoadObject) inline static
Records a time and stats for the loaded package.
Optionally provide the loaded asset if it is known, otherwise the asset in the package is detected.
Definition at line 111 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE.
Referenced by FExclusiveLoadPackageTimeTracker::FScopedPostLoadTracker::~FScopedPostLoadTracker().
PushEndLoad()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::PushEndLoad () inline static
Starts a time for time spent in "EndLoad".
Definition at line 119 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE, and Instance.
Referenced by FExclusiveLoadPackageTimeTracker::FScopedEndLoadTracker::FScopedEndLoadTracker().
PushLoadPackage()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::PushLoadPackage (FName PackageName) inline static
Starts a time for the specified package name.
Definition at line 82 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE, and PackageName.
Referenced by FExclusiveLoadPackageTimeTracker::FScopedPackageTracker::FScopedPackageTracker(), and FExclusiveLoadPackageTimeTracker::FScopedPackageTracker::FScopedPackageTracker().
PushPostLoad()
FORCEINLINE bool FExclusiveLoadPackageTimeTracker::PushPostLoad (UObject * PostLoadObject) inline static
Starts a time for the specified package name.
Definition at line 98 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE, UObjectBase::GetFName(), UObjectBaseUtility::GetOutermost(), and UObject::IsAsset().
Referenced by FExclusiveLoadPackageTimeTracker::FScopedPostLoadTracker::FScopedPostLoadTracker().
ResetReport()
FORCEINLINE void FExclusiveLoadPackageTimeTracker::ResetReport () inline static
Resets the data.
Definition at line 144 of file ExclusiveLoadPackageTimeTracker.h.
References FORCEINLINE.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Misc/ExclusiveLoadPackageTimeTracker.h