Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FInputWorldArea Class Reference
UE::Landscape::EditLayers::FInputWorldArea Class Reference
Describes the input area needed for a given edit layer renderer's render item: this allows to infer the dependency between each component being rendered and the components it depends on.
#include "LandscapeEditLayerRenderer.h"
Public Types
enum class EType { LocalComponent , SpecificComponent , OOBox , Infinite }
Public Member Functions
FBox ComputeWorldAreaAABB (const FTransform &InLandscapeTransform, const FBox &InLandscapeLocalBounds, const FTransform &InComponentTransform, const FBox &InComponentLocalBounds) const
FOOBox2D ComputeWorldAreaOOBB (const FTransform &InLandscapeTransform, const FBox &InLandscapeLocalBounds, const FTransform &InComponentTransform, const FBox &InComponentLocalBounds) const
FIntRect GetLocalComponentKeys (const FIntPoint &InComponentKey) const
In the EType::LocalComponent case, returns the component's coordinates and the local area around it (inclusive bounds)
const FOOBox2D & GetOOBox () const
In the EType::OOBox case, returns the OOBox.
FIntRect GetSpecificComponentKeys () const
In the EType::SpecificComponent case, returns the component's coordinates and the local area around it (inclusive bounds)
EType GetType () const
const FOOBox2D * TryGetOOBox () const
Static Public Member Functions
static FInputWorldArea CreateInfinite ()
static FInputWorldArea CreateLocalComponent (const FIntRect &InLocalArea=FIntRect())
static FInputWorldArea CreateOOBox (const FOOBox2D &InOOBox)
static FInputWorldArea CreateSpecificComponent (const FIntPoint &InComponentKey, const FIntRect &InLocalArea=FIntRect())
Private Member Functions
FInputWorldArea (EType InType, const FIntPoint &InComponentKey=FIntPoint(ForceInit), const FIntRect &InLocalArea=FIntRect(), const FOOBox2D &InOOBox2D=FOOBox2D())
Private Attributes
FIntRect LocalArea
Area around the component that is needed in the EType::LocalComponent / EType::SpecificComponent case (in component coordinates (see ULandscapeComponent::GetComponentKey()), e.g.
FOOBox2D OOBox2D
World space object-oriented box in the EType::OOBBox case.
FIntPoint SpecificComponentKey = FIntPoint(ForceInit)
Coordinates of the component (see ULandscapeComponent::GetComponentKey()) in the EType::SpecificComponent case.
EType Type = EType::LocalComponent
Detailed Description
Describes the input area needed for a given edit layer renderer's render item: this allows to infer the dependency between each component being rendered and the components it depends on.
Definition at line 68 of file LandscapeEditLayerRenderer.h.
Member Enumeration Documentation
EType
enum class UE::Landscape::EditLayers::FInputWorldArea::EType strong
Enumerator
LocalComponent
SpecificComponent
OOBox
Infinite
Definition at line 71 of file LandscapeEditLayerRenderer.h.
Constructor & Destructor Documentation
FInputWorldArea()
UE::Landscape::EditLayers::FInputWorldArea::FInputWorldArea (EType InType, const FIntPoint & InComponentKey = FIntPoint(ForceInit), const FIntRect & InLocalArea = FIntRect(), const FOOBox2D & InOOBox2D = FOOBox2D()) inline private
Definition at line 97 of file LandscapeEditLayerRenderer.h.
References ForceInit, LocalArea, OOBox2D, SpecificComponentKey, and Type.
Referenced by CreateInfinite(), CreateLocalComponent(), CreateOOBox(), and CreateSpecificComponent().
Member Function Documentation
ComputeWorldAreaAABB()
FBox UE::Landscape::EditLayers::FInputWorldArea::ComputeWorldAreaAABB (const FTransform & InLandscapeTransform, const FBox & InLandscapeLocalBounds, const FTransform & InComponentTransform, const FBox & InComponentLocalBounds) const
ComputeWorldAreaOOBB()
FOOBox2D UE::Landscape::EditLayers::FInputWorldArea::ComputeWorldAreaOOBB (const FTransform & InLandscapeTransform, const FBox & InLandscapeLocalBounds, const FTransform & InComponentTransform, const FBox & InComponentLocalBounds) const
CreateInfinite()
FInputWorldArea UE::Landscape::EditLayers::FInputWorldArea::CreateInfinite () inline static
Definition at line 79 of file LandscapeEditLayerRenderer.h.
References FInputWorldArea(), and Infinite.
CreateLocalComponent()
FInputWorldArea UE::Landscape::EditLayers::FInputWorldArea::CreateLocalComponent (const FIntRect & InLocalArea = FIntRect()) inline static
Definition at line 80 of file LandscapeEditLayerRenderer.h.
References FInputWorldArea(), ForceInit, and LocalComponent.
CreateOOBox()
FInputWorldArea UE::Landscape::EditLayers::FInputWorldArea::CreateOOBox (const FOOBox2D & InOOBox) inline static
Definition at line 82 of file LandscapeEditLayerRenderer.h.
References FInputWorldArea(), ForceInit, and OOBox.
CreateSpecificComponent()
FInputWorldArea UE::Landscape::EditLayers::FInputWorldArea::CreateSpecificComponent (const FIntPoint & InComponentKey, const FIntRect & InLocalArea = FIntRect()) inline static
Definition at line 81 of file LandscapeEditLayerRenderer.h.
References FInputWorldArea(), and SpecificComponent.
GetLocalComponentKeys()
FIntRect UE::Landscape::EditLayers::FInputWorldArea::GetLocalComponentKeys (const FIntPoint & InComponentKey) const
In the EType::LocalComponent case, returns the component's coordinates and the local area around it (inclusive bounds)
GetOOBox()
const FOOBox2D & UE::Landscape::EditLayers::FInputWorldArea::GetOOBox () const inline
In the EType::OOBox case, returns the OOBox.
Definition at line 90 of file LandscapeEditLayerRenderer.h.
References check, OOBox, OOBox2D, and Type.
GetSpecificComponentKeys()
FIntRect UE::Landscape::EditLayers::FInputWorldArea::GetSpecificComponentKeys () const
In the EType::SpecificComponent case, returns the component's coordinates and the local area around it (inclusive bounds)
GetType()
EType UE::Landscape::EditLayers::FInputWorldArea::GetType () const inline
Definition at line 84 of file LandscapeEditLayerRenderer.h.
References Type.
TryGetOOBox()
const FOOBox2D * UE::Landscape::EditLayers::FInputWorldArea::TryGetOOBox () const inline
Definition at line 91 of file LandscapeEditLayerRenderer.h.
References OOBox, OOBox2D, and Type.
Field Documentation
LocalArea
FIntRect UE::Landscape::EditLayers::FInputWorldArea::LocalArea private
Area around the component that is needed in the EType::LocalComponent / EType::SpecificComponent case (in component coordinates (see ULandscapeComponent::GetComponentKey()), e.g.
use (-1, -1, 1, 1) for the component and its immediate neighbors all around)
Definition at line 110 of file LandscapeEditLayerRenderer.h.
Referenced by FInputWorldArea().
OOBox2D
FOOBox2D UE::Landscape::EditLayers::FInputWorldArea::OOBox2D private
World space object-oriented box in the EType::OOBBox case.
Definition at line 113 of file LandscapeEditLayerRenderer.h.
Referenced by FInputWorldArea(), GetOOBox(), and TryGetOOBox().
SpecificComponentKey
FIntPoint UE::Landscape::EditLayers::FInputWorldArea::SpecificComponentKey = FIntPoint(ForceInit) private
Coordinates of the component (see ULandscapeComponent::GetComponentKey()) in the EType::SpecificComponent case.
Definition at line 107 of file LandscapeEditLayerRenderer.h.
Referenced by FInputWorldArea().
Type
EType UE::Landscape::EditLayers::FInputWorldArea::Type = EType::LocalComponent private
Definition at line 105 of file LandscapeEditLayerRenderer.h.
Referenced by FInputWorldArea(), GetOOBox(), GetType(), and TryGetOOBox().
The documentation for this class was generated from the following file:
Runtime/Landscape/Public/LandscapeEditLayerRenderer.h