Unreal Engine 5.6 C++ API: UE::TReadScopeLock< MutexType > Class Template Reference
UE::TReadScopeLock< MutexType > Class Template Reference
#include "ScopeRWLock.h"
Public Member Functions
UE_NODISCARD_CTOR TReadScopeLock (MutexType &InMutex)
~TReadScopeLock ()
void ReadUnlock ()
UE_NONCOPYABLE (TReadScopeLock)
Private Attributes
MutexType * Mutex
Detailed Description
template<typename MutexType>
class UE::TReadScopeLock< MutexType >
Definition at line 20 of file ScopeRWLock.h.
Constructor & Destructor Documentation
TReadScopeLock()
template<typename MutexType> UE_NODISCARD_CTOR UE::TReadScopeLock< MutexType >::TReadScopeLock (MutexType & InMutex) inline
Definition at line 25 of file ScopeRWLock.h.
References check, Mutex, and UE_NODISCARD_CTOR.
Referenced by UE_NONCOPYABLE().
~TReadScopeLock()
template<typename MutexType> UE::TReadScopeLock< MutexType >::~TReadScopeLock () inline
Definition at line 32 of file ScopeRWLock.h.
References ReadUnlock().
Member Function Documentation
ReadUnlock()
template<typename MutexType> void UE::TReadScopeLock< MutexType >::ReadUnlock () inline
Definition at line 37 of file ScopeRWLock.h.
References Mutex.
Referenced by ~TReadScopeLock().
UE_NONCOPYABLE()
template<typename MutexType> UE::TReadScopeLock< MutexType >::UE_NONCOPYABLE (TReadScopeLock< MutexType >)
References TReadScopeLock().
Field Documentation
Mutex
template<typename MutexType> MutexType* UE::TReadScopeLock< MutexType >::Mutex private
Definition at line 47 of file ScopeRWLock.h.
Referenced by TReadScopeLock(), and ReadUnlock().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/ScopeRWLock.h