Unreal Engine 5.6 C++ API: UE::SequenceNavigator::INavigationTool Class Reference
UE::SequenceNavigator::INavigationTool Class Reference abstract
The Navigation Tool Object that is commonly instanced once per Sequencer (unless for advanced use where there are different Navigation Tool instances with different item ordering and behaviors).
#include "INavigationTool.h"
Public Member Functions
virtual ~INavigationTool ()=default
virtual void ClearItemSelection (const bool bInSignalSelectionChange) const =0
Clears the Item Selection from all Navigation Tool Views.
DECLARE_MULTICAST_DELEGATE (FOnToolLoaded)
template<typename InItemActionType, typename = typename TEnableIf<TIsDerivedFrom<InItemActionType, INavigationToolAction>::IsDerived>::Type, typename ... InArgTypes>
void EnqueueItemAction (InArgTypes &&... InArgs)
Instantiates a single new item action and immediately adds it to the Pending Actions Queue.
virtual void EnqueueItemActions (TArray< TSharedPtr< INavigationToolAction > > &&InItemActions) noexcept=0
Adds the given actions to the Pending Action Queue.
virtual FNavigationToolItemPtr FindItem (const FNavigationToolItemId &InItemId) const =0
Finds the registered item that has the given Id.
virtual TOptional< FColor > FindItemColor (const FNavigationToolItemPtr &InItem, bool bRecurseParent=true) const =0
Gets the color related to the Item.
template<typename InItemType, typename = typename TEnableIf<TIsDerivedFrom<InItemType, INavigationToolItem>::IsDerived>::Type, typename ... InArgTypes>
TSharedRef< InItemType > FindOrAdd (const TSharedPtr< FNavigationToolProvider > &InProvider, InArgTypes &&... InArgs)
Instantiates a new Item and automatically registers it to the Navigation Tool.
virtual void ForEachProvider (const TFunction< bool(const TSharedRef< FNavigationToolProvider > &InToolProvider)> &InPredicate) const =0
virtual TSharedPtr< FUICommandList > GetBaseCommandList () const =0
Gets the Command List that the Navigation Tool Views will use to append their Command Lists to.
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type>
INavigationToolItemProxyFactory * GetItemProxyFactory () const
Tries to find the Item Proxy Factory for the given Item Proxy Type Name.
virtual TSharedPtr< INavigationToolView > GetMostRecentToolView () const =0
Gets the outliner view that was most recently used (i.e.
virtual FOnToolLoaded & GetOnToolLoaded ()=0
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type, typename ... InArgTypes>
TSharedPtr< FNavigationToolItemProxy > GetOrCreateItemProxy (const FNavigationToolItemPtr &InParentItem, InArgTypes &&... InArgs)
Tries to get the Item Proxy Factory for the given Item Proxy type, first trying the Navigation Tool Registry then the Module's then returns an existing item proxy created via the factory, or creates one if there's no existing item proxy.
virtual TArray< FName > GetRegisteredItemProxyTypeNames () const =0
Gathers the Type Names of all the Item Proxies that are registered both in the outliner proxy registry and the module's.
virtual TArray< FNavigationToolItemPtr > GetSelectedItems (const bool bInNormalizeToTopLevelSelections=false) const =0
Returns the currently selected items in the most recent outliner view (since this list can vary between outliner views)
virtual TSharedPtr< ISequencer > GetSequencer () const =0
virtual TSharedPtr< INavigationToolView > GetToolView (const int32 InToolViewId) const =0
Gets the Navigation Tool View bound to the given id.
virtual TSharedRef< FNavigationToolItem > GetTreeRoot () const =0
Gets the Tree Root Item of the Navigation Tool.
virtual bool IsObjectAllowedInTool (const UObject *const InObject) const =0
Determines whether the given actor can be presented in the Navigation Tool, at all.
virtual SEQUENCENAVIGATOR_API bool IsToolTabVisible () const =0
template<typename InItemActionType, typename = typename TEnableIf<TIsDerivedFrom<InItemActionType, INavigationToolAction>::IsDerived>::Type, typename ... InArgTypes>
TSharedRef< InItemActionType > NewItemAction (InArgTypes &&... InArgs)
Instantiates a new item action without adding it to the Pending Actions Queue.
virtual void NotifyToolItemDeleted (const FNavigationToolItemPtr &InItem)=0
Called when an Item has been deleted.
virtual void NotifyToolItemRenamed (const FNavigationToolItemPtr &InItem)=0
Called when an Item has been Renamed.
virtual void OnSequencerSelectionChanged ()=0
Called when the Sequencer selection has changed.
virtual void Refresh ()=0
Flushes the Pending Actions from the Queue while also updating the state of the Navigation Tool.
virtual void RegisterItem (const FNavigationToolItemPtr &InItem)=0
Registers the given Item, replacing the old one.
virtual TSharedPtr< INavigationToolView > RegisterToolView (const int32 InToolViewId)=0
Register a new Navigation Tool View to the Navigation Tool to the given id, replacing the old view that was bound to the given id.
virtual void RemoveItemColor (const FNavigationToolItemPtr &InItem)=0
Removes the Color pairing of the given Item (can still have an inherited color though)
virtual void RequestRefresh ()=0
Ensures that the next time Refresh is called in tick, Refresh will be called.
virtual void SelectItems (const TArray< FNavigationToolItemPtr > &InItems, const ENavigationToolItemSelectionFlags InFlags=ENavigationToolItemSelectionFlags::SignalSelectionChange) const =0
Selects the given Items on all Navigation Tool Views.
virtual void SetIgnoreNotify (const ENavigationToolIgnoreNotifyFlags InFlag, const bool bInIgnore)=0
Adds or Removes the Ignore Notify Flags to prevent certain actions from automatically happening when they're triggered.
virtual void SetItemColor (const FNavigationToolItemPtr &InItem, const FColor &InColor)=0
Pairs the Item with the given color name, overriding the inherited color if different.
virtual SEQUENCENAVIGATOR_API void ShowHideToolTab (const bool bInVisible)=0
virtual SEQUENCENAVIGATOR_API void ToggleToolTabVisible ()=0
virtual TArray< FNavigationToolItemPtr > TryFindItems (const UE::Sequencer::FViewModelPtr &InViewModel) const =0
Attempts to find all items associated with a Sequencer view model.
virtual void UnregisterItem (const FNavigationToolItemId &InItemId)=0
Unregisters the Item having the given ItemId.
Public Member Functions inherited from TSharedFromThis< INavigationTool >
TSharedRef< INavigationTool, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< INavigationTool, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual const FNavigationToolItemProxyRegistry & GetItemProxyRegistry () const =0
Protected Member Functions inherited from TSharedFromThis< INavigationTool >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< INavigationTool >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The Navigation Tool Object that is commonly instanced once per Sequencer (unless for advanced use where there are different Navigation Tool instances with different item ordering and behaviors).
This is the object that dictates core Navigation Tool behavior like how items are sorted, which items are allowed, etc. Views are the objects that take this core behavior and show a part of it (e.g. through filters).
Definition at line 38 of file INavigationTool.h.
Constructor & Destructor Documentation
~INavigationTool()
virtual UE::SequenceNavigator::INavigationTool::~INavigationTool () virtual default
Member Function Documentation
ClearItemSelection()
virtual void UE::SequenceNavigator::INavigationTool::ClearItemSelection (const bool bInSignalSelectionChange) const pure virtual
Clears the Item Selection from all Navigation Tool Views.
Parameters
bInSignalSelectionChange whether to notify the change in selection
DECLARE_MULTICAST_DELEGATE()
UE::SequenceNavigator::INavigationTool::DECLARE_MULTICAST_DELEGATE (FOnToolLoaded)
EnqueueItemAction()
template<typename InItemActionType, typename = typename TEnableIf<TIsDerivedFrom<InItemActionType, INavigationToolAction>::IsDerived>::Type, typename ... InArgTypes> void UE::SequenceNavigator::INavigationTool::EnqueueItemAction (InArgTypes &&... InArgs) inline
Instantiates a single new item action and immediately adds it to the Pending Actions Queue.
Ideal for when dealing with a single action. For multiple actions use FNavigationTool::EnqueueItemActions.
Definition at line 235 of file INavigationTool.h.
References EnqueueItemActions(), Forward(), and NewItemAction().
EnqueueItemActions()
virtual void UE::SequenceNavigator::INavigationTool::EnqueueItemActions (TArray< TSharedPtr< INavigationToolAction > > && InItemActions) pure virtual noexcept
Adds the given actions to the Pending Action Queue.
Referenced by EnqueueItemAction().
FindItem()
virtual FNavigationToolItemPtr UE::SequenceNavigator::INavigationTool::FindItem (const FNavigationToolItemId & InItemId) const pure virtual
Finds the registered item that has the given Id.
Returns
The item with the given Id, or null if the item does not exist or was not registered to the Navigation Tool
Referenced by FindOrAdd(), and GetOrCreateItemProxy().
FindItemColor()
virtual TOptional< FColor > UE::SequenceNavigator::INavigationTool::FindItemColor (const FNavigationToolItemPtr & InItem, bool bRecurseParent = true) const pure virtual
Gets the color related to the Item.
Parameters
InItem the item to query
bRecurseParent whether to get the color of the parent (recursively) if the given item does not have a color by itself
Returns
the matching color pair or unset if item is invalid or no color could be found.
FindOrAdd()
template<typename InItemType, typename = typename TEnableIf<TIsDerivedFrom<InItemType, INavigationToolItem>::IsDerived>::Type, typename ... InArgTypes> TSharedRef< InItemType > UE::SequenceNavigator::INavigationTool::FindOrAdd (const TSharedPtr< FNavigationToolProvider > & InProvider, InArgTypes &&... InArgs) inline
Instantiates a new Item and automatically registers it to the Navigation Tool.
Definition at line 68 of file INavigationTool.h.
References FindItem(), Forward(), TSharedPtr< ObjectType, InMode >::IsValid(), Item, MakeShared(), RegisterItem(), and StaticCastSharedPtr().
ForEachProvider()
virtual void UE::SequenceNavigator::INavigationTool::ForEachProvider (const TFunction< bool(const TSharedRef< FNavigationToolProvider > &InToolProvider)> & InPredicate) const pure virtual
GetBaseCommandList()
virtual TSharedPtr< FUICommandList > UE::SequenceNavigator::INavigationTool::GetBaseCommandList () const pure virtual
Gets the Command List that the Navigation Tool Views will use to append their Command Lists to.
GetItemProxyFactory()
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type> INavigationToolItemProxyFactory * UE::SequenceNavigator::INavigationTool::GetItemProxyFactory () const inline
Tries to find the Item Proxy Factory for the given Item Proxy Type Name.
Definition at line 91 of file INavigationTool.h.
References UE::SequenceNavigator::FNavigationToolItemProxyRegistry::GetItemProxyFactory(), GetItemProxyFactory(), UE::SequenceNavigator::FNavigationToolExtender::GetItemProxyRegistry(), and GetItemProxyRegistry().
Referenced by GetItemProxyFactory(), and GetOrCreateItemProxy().
GetItemProxyRegistry()
virtual const FNavigationToolItemProxyRegistry & UE::SequenceNavigator::INavigationTool::GetItemProxyRegistry () const protected pure virtual
Referenced by GetItemProxyFactory().
GetMostRecentToolView()
virtual TSharedPtr< INavigationToolView > UE::SequenceNavigator::INavigationTool::GetMostRecentToolView () const pure virtual
Gets the outliner view that was most recently used (i.e.
called FNavigationTool::UpdateRecentToolViews)
GetOnToolLoaded()
virtual FOnToolLoaded & UE::SequenceNavigator::INavigationTool::GetOnToolLoaded () pure virtual
GetOrCreateItemProxy()
template<typename InItemProxyType, typename = typename TEnableIf<TIsDerivedFrom<InItemProxyType, FNavigationToolItemProxy>::IsDerived>::Type, typename ... InArgTypes> TSharedPtr< FNavigationToolItemProxy > UE::SequenceNavigator::INavigationTool::GetOrCreateItemProxy (const FNavigationToolItemPtr & InParentItem, InArgTypes &&... InArgs) inline
Tries to get the Item Proxy Factory for the given Item Proxy type, first trying the Navigation Tool Registry then the Module's then returns an existing item proxy created via the factory, or creates one if there's no existing item proxy.
Returns
the Item Proxy created by the Factory. Can be null if no factory was found or if the factory intentionally returns null
Definition at line 109 of file INavigationTool.h.
References check, UE::SequenceNavigator::INavigationToolItemProxyFactory::CreateItemProxy(), FindItem(), GetItemProxyFactory(), TSharedPtr< ObjectType, InMode >::IsValid(), RegisterItem(), and StaticCastSharedPtr().
GetRegisteredItemProxyTypeNames()
virtual TArray< FName > UE::SequenceNavigator::INavigationTool::GetRegisteredItemProxyTypeNames () const pure virtual
Gathers the Type Names of all the Item Proxies that are registered both in the outliner proxy registry and the module's.
GetSelectedItems()
virtual TArray< FNavigationToolItemPtr > UE::SequenceNavigator::INavigationTool::GetSelectedItems (const bool bInNormalizeToTopLevelSelections = false) const pure virtual
Returns the currently selected items in the most recent outliner view (since this list can vary between outliner views)
GetSequencer()
virtual TSharedPtr< ISequencer > UE::SequenceNavigator::INavigationTool::GetSequencer () const pure virtual
GetToolView()
virtual TSharedPtr< INavigationToolView > UE::SequenceNavigator::INavigationTool::GetToolView (const int32 InToolViewId) const pure virtual
Gets the Navigation Tool View bound to the given id.
GetTreeRoot()
virtual TSharedRef< FNavigationToolItem > UE::SequenceNavigator::INavigationTool::GetTreeRoot () const pure virtual
Gets the Tree Root Item of the Navigation Tool.
IsObjectAllowedInTool()
virtual bool UE::SequenceNavigator::INavigationTool::IsObjectAllowedInTool (const UObject *const InObject) const pure virtual
Determines whether the given actor can be presented in the Navigation Tool, at all.
This is a permanent check unlike filters that are temporary.
IsToolTabVisible()
virtual SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::INavigationTool::IsToolTabVisible () const pure virtual
NewItemAction()
template<typename InItemActionType, typename = typename TEnableIf<TIsDerivedFrom<InItemActionType, INavigationToolAction>::IsDerived>::Type, typename ... InArgTypes> TSharedRef< InItemActionType > UE::SequenceNavigator::INavigationTool::NewItemAction (InArgTypes &&... InArgs) inline
Instantiates a new item action without adding it to the Pending Actions Queue.
This should only be used directly when planning to enqueue multiple actions.
See also
FNavigationTool::EnqueueItemActions
Definition at line 224 of file INavigationTool.h.
References Forward(), and MakeShared().
Referenced by EnqueueItemAction().
NotifyToolItemDeleted()
virtual void UE::SequenceNavigator::INavigationTool::NotifyToolItemDeleted (const FNavigationToolItemPtr & InItem) pure virtual
Called when an Item has been deleted.
NotifyToolItemRenamed()
virtual void UE::SequenceNavigator::INavigationTool::NotifyToolItemRenamed (const FNavigationToolItemPtr & InItem) pure virtual
Called when an Item has been Renamed.
OnSequencerSelectionChanged()
virtual void UE::SequenceNavigator::INavigationTool::OnSequencerSelectionChanged () pure virtual
Called when the Sequencer selection has changed.
Refresh()
virtual void UE::SequenceNavigator::INavigationTool::Refresh () pure virtual
Flushes the Pending Actions from the Queue while also updating the state of the Navigation Tool.
Calling it directly is forcing it to happen. If a refresh is needed it will be called on the next tick automatically.
RegisterItem()
virtual void UE::SequenceNavigator::INavigationTool::RegisterItem (const FNavigationToolItemPtr & InItem) pure virtual
Registers the given Item, replacing the old one.
Referenced by FindOrAdd(), and GetOrCreateItemProxy().
RegisterToolView()
virtual TSharedPtr< INavigationToolView > UE::SequenceNavigator::INavigationTool::RegisterToolView (const int32 InToolViewId) pure virtual
Register a new Navigation Tool View to the Navigation Tool to the given id, replacing the old view that was bound to the given id.
RemoveItemColor()
virtual void UE::SequenceNavigator::INavigationTool::RemoveItemColor (const FNavigationToolItemPtr & InItem) pure virtual
Removes the Color pairing of the given Item (can still have an inherited color though)
RequestRefresh()
virtual void UE::SequenceNavigator::INavigationTool::RequestRefresh () pure virtual
Ensures that the next time Refresh is called in tick, Refresh will be called.
SelectItems()
virtual void UE::SequenceNavigator::INavigationTool::SelectItems (const TArray< FNavigationToolItemPtr > & InItems, const ENavigationToolItemSelectionFlags InFlags = ENavigationToolItemSelectionFlags::SignalSelectionChange) const pure virtual
Selects the given Items on all Navigation Tool Views.
Parameters
InItems the items to select
InFlags how the items should be selected (appended, notify of selections, etc)
References SignalSelectionChange.
SetIgnoreNotify()
virtual void UE::SequenceNavigator::INavigationTool::SetIgnoreNotify (const ENavigationToolIgnoreNotifyFlags InFlag, const bool bInIgnore) pure virtual
Adds or Removes the Ignore Notify Flags to prevent certain actions from automatically happening when they're triggered.
Parameters
InFlag the ignore flag to add or remove
bInIgnore whether to add (true) or remove (false) the flag
SetItemColor()
virtual void UE::SequenceNavigator::INavigationTool::SetItemColor (const FNavigationToolItemPtr & InItem, const FColor & InColor) pure virtual
Pairs the Item with the given color name, overriding the inherited color if different.
ShowHideToolTab()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::INavigationTool::ShowHideToolTab (const bool bInVisible) pure virtual
ToggleToolTabVisible()
virtual SEQUENCENAVIGATOR_API void UE::SequenceNavigator::INavigationTool::ToggleToolTabVisible () pure virtual
TryFindItems()
virtual TArray< FNavigationToolItemPtr > UE::SequenceNavigator::INavigationTool::TryFindItems (const UE::Sequencer::FViewModelPtr & InViewModel) const pure virtual
Attempts to find all items associated with a Sequencer view model.
Parameters
InViewModel The Sequencer view model to find the items of
Returns
The list of Navigation Tool items found
UnregisterItem()
virtual void UE::SequenceNavigator::INavigationTool::UnregisterItem (const FNavigationToolItemId & InItemId) pure virtual
Unregisters the Item having the given ItemId.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/INavigationTool.h