Unreal Engine 5.6 C++ API: FBuildVersion Class Reference
FBuildVersion Class Reference
Stores the version information associated with a build.
#include "BuildVersion.h"
Public Member Functions
FBuildVersion ()
Default constructor.
FEngineVersion GetCompatibleEngineVersion () const
Get a compatible engine version object for this build version.
int GetEffectiveCompatibleChangelist () const
Gets the compatible changelist if set, otherwise the default compatible changelist.
FEngineVersion GetEngineVersion () const
Get an engine version object for this build version.
Static Public Member Functions
static FString GetDefaultFileName ()
Get the default path to the build.version file on disk.
static FString GetFileNameForCurrentExecutable ()
Get the path to the version file for the current executable.
static bool TryRead (const FString &FileName, FBuildVersion &OutVersion)
Try to read a version file from disk.
static bool TryReadFromString (const FString &Text, FBuildVersion &OutVersion)
Try to read version info from data stored in a string.
Data Fields
FString BranchName
Name of the current branch, with '/' characters escaped as '+'.
FString BuildId
The current build id.
FString BuildUrl
[Optional] A url to the web page for the build (if it was created by an automated build systme for example)
FString BuildVersion
The build version string.
int Changelist
The changelist that the engine is being built from.
int CompatibleChangelist
The changelist that the engine maintains compatibility with.
int IsLicenseeVersion
Whether the changelist numbers are a licensee changelist.
int IsPromotedBuild
Whether the current build is a promoted build, that is, built strictly from a clean sync of the given changelist.
int MajorVersion
The major engine version (4 for UE4)
int MinorVersion
The minor engine version.
int PatchVersion
The hotfix/patch version.
Detailed Description
Stores the version information associated with a build.
Definition at line 14 of file BuildVersion.h.
Constructor & Destructor Documentation
FBuildVersion()
FBuildVersion::FBuildVersion ()
Default constructor.
Initializes the structure to empty.
Referenced by TryRead(), and TryReadFromString().
Member Function Documentation
GetCompatibleEngineVersion()
FEngineVersion FBuildVersion::GetCompatibleEngineVersion () const
Get a compatible engine version object for this build version.
Returns
New engine version object
GetDefaultFileName()
FString FBuildVersion::GetDefaultFileName () static
Get the default path to the build.version file on disk.
Returns
Path to the Build.version file
GetEffectiveCompatibleChangelist()
int FBuildVersion::GetEffectiveCompatibleChangelist () const
Gets the compatible changelist if set, otherwise the default compatible changelist.
Returns
The compatible changelist
GetEngineVersion()
FEngineVersion FBuildVersion::GetEngineVersion () const
Get an engine version object for this build version.
Returns
New engine version object
GetFileNameForCurrentExecutable()
FString FBuildVersion::GetFileNameForCurrentExecutable () static
Get the path to the version file for the current executable.
Returns
Path to the target's version file
TryRead()
bool FBuildVersion::TryRead (const FString & FileName, FBuildVersion & OutVersion) static
Try to read a version file from disk.
Parameters
FileName Path to the version file
OutVersion The version information
Returns
True if the version was read successfully, false otherwise
References FBuildVersion().
TryReadFromString()
bool FBuildVersion::TryReadFromString (const FString & Text, FBuildVersion & OutVersion) static
Try to read version info from data stored in a string.
Parameters
Text The version info stored in string form
OutVersion The version information
Returns
True if the version was read successfully, false otherwise
References FBuildVersion(), and Text.
Field Documentation
BranchName
FString FBuildVersion::BranchName
Name of the current branch, with '/' characters escaped as '+'.
Definition at line 55 of file BuildVersion.h.
BuildId
FString FBuildVersion::BuildId
The current build id.
This will be generated automatically whenever engine binaries change if not set in the default Engine/Build/Build.version.
Definition at line 60 of file BuildVersion.h.
BuildUrl
FString FBuildVersion::BuildUrl
[Optional] A url to the web page for the build (if it was created by an automated build systme for example)
Definition at line 70 of file BuildVersion.h.
BuildVersion
FString FBuildVersion::BuildVersion
The build version string.
Definition at line 65 of file BuildVersion.h.
Changelist
int FBuildVersion::Changelist
The changelist that the engine is being built from.
Definition at line 35 of file BuildVersion.h.
CompatibleChangelist
int FBuildVersion::CompatibleChangelist
The changelist that the engine maintains compatibility with.
Definition at line 40 of file BuildVersion.h.
IsLicenseeVersion
int FBuildVersion::IsLicenseeVersion
Whether the changelist numbers are a licensee changelist.
Definition at line 45 of file BuildVersion.h.
IsPromotedBuild
int FBuildVersion::IsPromotedBuild
Whether the current build is a promoted build, that is, built strictly from a clean sync of the given changelist.
Definition at line 50 of file BuildVersion.h.
MajorVersion
int FBuildVersion::MajorVersion
The major engine version (4 for UE4)
Definition at line 20 of file BuildVersion.h.
MinorVersion
int FBuildVersion::MinorVersion
The minor engine version.
Definition at line 25 of file BuildVersion.h.
PatchVersion
int FBuildVersion::PatchVersion
The hotfix/patch version.
Definition at line 30 of file BuildVersion.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Modules/BuildVersion.h