Unreal Engine 5.6 C++ API: UE::SequenceNavigator::INavigationToolItemTypeCastable Class Reference
UE::SequenceNavigator::INavigationToolItemTypeCastable Class Reference abstract
Interface Class to perform actions like IsA, or CastTo.
#include "NavigationToolItemType.h"
Public Types
using FNavigationToolItemInherits = TNavigationToolItemInherits<INavigationToolItemTypeCastable,>
Public Member Functions
virtual ~INavigationToolItemTypeCastable ()=default
template<typename InType>
InType * CastTo ()
template<typename InType>
const InType * CastTo () const
virtual const void * CastTo_Impl (FNavigationToolItemTypeId InId) const =0
virtual FNavigationToolItemTypeId GetTypeId () const =0
template<typename InType>
bool IsA () const
template<typename InType>
bool IsExactlyA () const
Static Public Member Functions
static FNavigationToolItemTypeId GetStaticTypeId ()
Detailed Description
Interface Class to perform actions like IsA, or CastTo.
See also
UE_NAVIGATIONTOOL_INHERITS
Definition at line 168 of file NavigationToolItemType.h.
Member Typedef Documentation
FNavigationToolItemInherits
using UE::SequenceNavigator::INavigationToolItemTypeCastable::FNavigationToolItemInherits = TNavigationToolItemInherits<INavigationToolItemTypeCastable,>
Definition at line 171 of file NavigationToolItemType.h.
Constructor & Destructor Documentation
~INavigationToolItemTypeCastable()
virtual UE::SequenceNavigator::INavigationToolItemTypeCastable::~INavigationToolItemTypeCastable () virtual default
Member Function Documentation
CastTo() [1/2]
template<typename InType> InType * UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo () inline
Definition at line 192 of file NavigationToolItemType.h.
References CastTo().
Referenced by CastTo(), UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType(), UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType(), UE::SequenceNavigator::INavigationToolItem::FindAncestorsOfType(), UE::SequenceNavigator::INavigationToolItem::GetChildrenOfType(), UE::SequenceNavigator::INavigationToolItem::GetDescendantsOfType(), and IsA().
CastTo() [2/2]
template<typename InType> const InType * UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo () const inline
Definition at line 199 of file NavigationToolItemType.h.
References CastTo_Impl(), and UE::SequenceNavigator::TNavigationToolItemType< T, bool >::GetTypeId().
CastTo_Impl()
virtual const void * UE::SequenceNavigator::INavigationToolItemTypeCastable::CastTo_Impl (FNavigationToolItemTypeId InId) const pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolColorColumn, UE::SequenceNavigator::FNavigationToolCommentColumn, UE::SequenceNavigator::FNavigationToolDeactiveStateColumn, UE::SequenceNavigator::FNavigationToolHBiasColumn, UE::SequenceNavigator::FNavigationToolInTimeColumn, UE::SequenceNavigator::FNavigationToolItemsColumn, UE::SequenceNavigator::FNavigationToolLabelColumn, UE::SequenceNavigator::FNavigationToolLengthColumn, and UE::SequenceNavigator::FNavigationToolLockColumn.
References CastTo_Impl().
Referenced by CastTo(), and CastTo_Impl().
GetStaticTypeId()
FNavigationToolItemTypeId UE::SequenceNavigator::INavigationToolItemTypeCastable::GetStaticTypeId () inline static
Definition at line 171 of file NavigationToolItemType.h.
GetTypeId()
virtual FNavigationToolItemTypeId UE::SequenceNavigator::INavigationToolItemTypeCastable::GetTypeId () const pure virtual
Implemented in UE::SequenceNavigator::FNavigationToolColorColumn, UE::SequenceNavigator::FNavigationToolCommentColumn, UE::SequenceNavigator::FNavigationToolDeactiveStateColumn, UE::SequenceNavigator::FNavigationToolHBiasColumn, UE::SequenceNavigator::FNavigationToolInTimeColumn, UE::SequenceNavigator::FNavigationToolItemsColumn, UE::SequenceNavigator::FNavigationToolLabelColumn, UE::SequenceNavigator::FNavigationToolLengthColumn, and UE::SequenceNavigator::FNavigationToolLockColumn.
References GetTypeId().
Referenced by UE::SequenceNavigator::INavigationToolColumn::GetColumnId(), GetTypeId(), and IsExactlyA().
IsA()
template<typename InType> bool UE::SequenceNavigator::INavigationToolItemTypeCastable::IsA () const inline
Definition at line 180 of file NavigationToolItemType.h.
References CastTo(), and IsA().
Referenced by UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType(), and IsA().
IsExactlyA()
template<typename InType> bool UE::SequenceNavigator::INavigationToolItemTypeCastable::IsExactlyA () const inline
Definition at line 186 of file NavigationToolItemType.h.
References GetTypeId(), and UE::SequenceNavigator::TNavigationToolItemType< T, bool >::GetTypeId().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/NavigationToolItemType.h