Unreal Engine 5.6 C++ API: FSkinnedAssetCompilationContext Class Reference
FSkinnedAssetCompilationContext Class Reference
#include "SkinnedAssetAsyncCompileUtils.h"
Public Member Functions
FSkinnedAssetCompilationContext ()=default
FSkinnedAssetCompilationContext (const FSkinnedAssetCompilationContext &)=delete
FSkinnedAssetCompilationContext (FSkinnedAssetCompilationContext &&)=default
FSkinnedAssetCompilationContext & operator= (const FSkinnedAssetCompilationContext &)=delete
FSkinnedAssetCompilationContext & operator= (FSkinnedAssetCompilationContext &&)=default
Data Fields
bool bIsSerializeSaving = false
TUniquePtr< FFinishBuildMorphTargetData > FinishBuildMorphTargetData
Detailed Description
Definition at line 17 of file SkinnedAssetAsyncCompileUtils.h.
Constructor & Destructor Documentation
FSkinnedAssetCompilationContext() [1/3]
FSkinnedAssetCompilationContext::FSkinnedAssetCompilationContext () default
Referenced by FSkinnedAssetCompilationContext(), FSkinnedAssetCompilationContext(), operator=(), and operator=().
FSkinnedAssetCompilationContext() [2/3]
FSkinnedAssetCompilationContext::FSkinnedAssetCompilationContext (const FSkinnedAssetCompilationContext &) delete
References FSkinnedAssetCompilationContext().
FSkinnedAssetCompilationContext() [3/3]
FSkinnedAssetCompilationContext::FSkinnedAssetCompilationContext (FSkinnedAssetCompilationContext &&) default
References FSkinnedAssetCompilationContext().
Member Function Documentation
operator=() [1/2]
FSkinnedAssetCompilationContext & FSkinnedAssetCompilationContext::operator= (const FSkinnedAssetCompilationContext &) delete
References FSkinnedAssetCompilationContext().
operator=() [2/2]
FSkinnedAssetCompilationContext & FSkinnedAssetCompilationContext::operator= (FSkinnedAssetCompilationContext &&) default
References FSkinnedAssetCompilationContext().
Field Documentation
bIsSerializeSaving
bool FSkinnedAssetCompilationContext::bIsSerializeSaving = false
Definition at line 29 of file SkinnedAssetAsyncCompileUtils.h.
FinishBuildMorphTargetData
TUniquePtr<FFinishBuildMorphTargetData> FSkinnedAssetCompilationContext::FinishBuildMorphTargetData
Definition at line 31 of file SkinnedAssetAsyncCompileUtils.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/SkinnedAssetAsyncCompileUtils.h