Unreal Engine 5.6 C++ API: Audio::IQuartzQuantizedCommand Class Reference
Audio::IQuartzQuantizedCommand Class Reference abstract
#include "QuartzQuantizationUtilities.h"
Public Member Functions
IQuartzQuantizedCommand ()
virtual ~IQuartzQuantizedCommand ()
void AboutToStart ()
void AddSubscriber (FQuartzGameThreadSubscriber InSubscriber)
void Cancel ()
void FailedToQueue (FQuartzQuantizedRequestData &InGameThreadData)
virtual FName GetCommandName () const =0
virtual EQuartzCommandType GetCommandType () const =0
virtual TSharedPtr< IQuartzQuantizedCommand > GetDeepCopyOfDerivedObject () const
virtual bool IsClockAltering ()
void OnClockPaused ()
void OnClockStarted ()
void OnFinalCallback (int32 InNumFramesLeft)
void OnQueued (const FQuartzQuantizedCommandInitInfo &InCommandInitInfo)
void OnScheduled (const FQuartzClockTickRate &InTickRate)
virtual int32 OverrideFramesUntilExec (int32 NumFramesUntilExec)
virtual bool RequiresAudioDevice () const
virtual bool ShouldDeadlineIgnoresBpmChanges ()
void Update (int32 NumFramesUntilDeadline)
Public Member Functions inherited from Audio::FQuartzCrossThreadMessage
FQuartzCrossThreadMessage (bool bAutoStartTimer=true)
double GetCurrentTimeMilliseconds () const
double GetResultsMilliseconds () const
double RequestReceived () const
void RequestSent ()
Public Member Functions inherited from Audio::FQuartzLatencyTimer
FQuartzLatencyTimer ()
double GetCurrentTimePassedMs ()
double GetResultsMilliseconds ()
bool HasTimerRun ()
bool HasTimerStarted ()
bool HasTimerStopped ()
bool IsTimerRunning ()
void ResetTimer ()
void StartTimer ()
void StopTimer ()
Private Member Functions
virtual void AboutToStartCustom ()
virtual void CancelCustom ()
virtual void FailedToQueueCustom ()
virtual void OnClockPausedCustom ()
virtual void OnClockStartedCustom ()
virtual void OnFinalCallbackCustom (int32 InNumFramesLeft)
virtual void OnQueuedCustom (const FQuartzQuantizedCommandInitInfo &InCommandInitInfo)
Private Attributes
int32 GameThreadDelegateID { -1 }
TArray< FQuartzGameThreadSubscriber > GameThreadSubscribers
Detailed Description
Definition at line 587 of file QuartzQuantizationUtilities.h.
Constructor & Destructor Documentation
IQuartzQuantizedCommand()
Audio::IQuartzQuantizedCommand::IQuartzQuantizedCommand () default
~IQuartzQuantizedCommand()
Audio::IQuartzQuantizedCommand::~IQuartzQuantizedCommand () virtual default
Member Function Documentation
AboutToStart()
void Audio::IQuartzQuantizedCommand::AboutToStart ()
Definition at line 572 of file QuartzQuantizationUtilities.cpp.
References AboutToStartCustom(), Audio::FQuartzQuantizedCommandDelegateData::CommandType, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, GameThreadDelegateID, GameThreadSubscribers, GetCommandName(), GetCommandType(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
AboutToStartCustom()
virtual void Audio::IQuartzQuantizedCommand::AboutToStartCustom () inline private virtual
Definition at line 648 of file QuartzQuantizationUtilities.h.
Referenced by AboutToStart().
AddSubscriber()
void Audio::IQuartzQuantizedCommand::AddSubscriber (FQuartzGameThreadSubscriber InSubscriber)
Definition at line 484 of file QuartzQuantizationUtilities.cpp.
References GameThreadSubscribers.
Cancel()
void Audio::IQuartzQuantizedCommand::Cancel ()
Definition at line 629 of file QuartzQuantizationUtilities.cpp.
References CancelCustom(), Audio::FQuartzQuantizedCommandDelegateData::CommandType, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, GameThreadDelegateID, GameThreadSubscribers, GetCommandName(), GetCommandType(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
CancelCustom()
virtual void Audio::IQuartzQuantizedCommand::CancelCustom () inline private virtual
Definition at line 652 of file QuartzQuantizationUtilities.h.
Referenced by Cancel().
FailedToQueue()
void Audio::IQuartzQuantizedCommand::FailedToQueue (FQuartzQuantizedRequestData & InGameThreadData)
Definition at line 548 of file QuartzQuantizationUtilities.cpp.
References Audio::FQuartzQuantizedCommandDelegateData::CommandType, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, FailedToQueueCustom(), Audio::FQuartzQuantizedRequestData::GameThreadDelegateID, GameThreadDelegateID, Audio::FQuartzQuantizedRequestData::GameThreadSubscribers, GameThreadSubscribers, GetCommandName(), GetCommandType(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
FailedToQueueCustom()
virtual void Audio::IQuartzQuantizedCommand::FailedToQueueCustom () inline private virtual
Definition at line 647 of file QuartzQuantizationUtilities.h.
Referenced by FailedToQueue().
GetCommandName()
virtual FName Audio::IQuartzQuantizedCommand::GetCommandName () const pure virtual
Referenced by AboutToStart(), Cancel(), FailedToQueue(), OnClockPaused(), OnClockStarted(), OnFinalCallback(), and OnQueued().
GetCommandType()
virtual EQuartzCommandType Audio::IQuartzQuantizedCommand::GetCommandType () const pure virtual
Referenced by AboutToStart(), Cancel(), FailedToQueue(), OnFinalCallback(), OnQueued(), and Update().
GetDeepCopyOfDerivedObject()
TSharedPtr< IQuartzQuantizedCommand > Audio::IQuartzQuantizedCommand::GetDeepCopyOfDerivedObject () const virtual
Definition at line 477 of file QuartzQuantizationUtilities.cpp.
References checkSlow.
IsClockAltering()
virtual bool Audio::IQuartzQuantizedCommand::IsClockAltering () inline virtual
Definition at line 636 of file QuartzQuantizationUtilities.h.
OnClockPaused()
void Audio::IQuartzQuantizedCommand::OnClockPaused ()
Definition at line 615 of file QuartzQuantizationUtilities.cpp.
References GetCommandName(), OnClockPausedCustom(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
OnClockPausedCustom()
virtual void Audio::IQuartzQuantizedCommand::OnClockPausedCustom () inline private virtual
Definition at line 650 of file QuartzQuantizationUtilities.h.
Referenced by OnClockPaused().
OnClockStarted()
void Audio::IQuartzQuantizedCommand::OnClockStarted ()
Definition at line 622 of file QuartzQuantizationUtilities.cpp.
References GetCommandName(), OnClockStartedCustom(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
OnClockStartedCustom()
virtual void Audio::IQuartzQuantizedCommand::OnClockStartedCustom () inline private virtual
Definition at line 651 of file QuartzQuantizationUtilities.h.
Referenced by OnClockStarted().
OnFinalCallback()
void Audio::IQuartzQuantizedCommand::OnFinalCallback (int32 InNumFramesLeft)
Definition at line 594 of file QuartzQuantizationUtilities.cpp.
References Audio::FQuartzQuantizedCommandDelegateData::CommandType, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, GameThreadDelegateID, GameThreadSubscribers, GetCommandName(), GetCommandType(), OnFinalCallbackCustom(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
OnFinalCallbackCustom()
virtual void Audio::IQuartzQuantizedCommand::OnFinalCallbackCustom (int32 InNumFramesLeft) inline private virtual
Definition at line 649 of file QuartzQuantizationUtilities.h.
Referenced by OnFinalCallback().
OnQueued()
void Audio::IQuartzQuantizedCommand::OnQueued (const FQuartzQuantizedCommandInitInfo & InCommandInitInfo)
Definition at line 489 of file QuartzQuantizationUtilities.cpp.
References Audio::FQuartzQuantizedCommandDelegateData::CommandType, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, Audio::FQuartzQuantizedCommandInitInfo::GameThreadDelegateID, GameThreadDelegateID, Audio::FQuartzQuantizedCommandInitInfo::GameThreadSubscribers, GameThreadSubscribers, GetCommandName(), GetCommandType(), OnQueuedCustom(), Audio::FQuartzQuantizedCommandInitInfo::OwningClockPointer, Audio::FQuartzCrossThreadMessage::RequestReceived(), TEXT, ToString(), TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Verbose.
OnQueuedCustom()
virtual void Audio::IQuartzQuantizedCommand::OnQueuedCustom (const FQuartzQuantizedCommandInitInfo & InCommandInitInfo) inline private virtual
Definition at line 646 of file QuartzQuantizationUtilities.h.
Referenced by OnQueued().
OnScheduled()
void Audio::IQuartzQuantizedCommand::OnScheduled (const FQuartzClockTickRate & InTickRate)
Definition at line 519 of file QuartzQuantizationUtilities.cpp.
References GameThreadSubscribers.
OverrideFramesUntilExec()
virtual int32 Audio::IQuartzQuantizedCommand::OverrideFramesUntilExec (int32 NumFramesUntilExec) inline virtual
Definition at line 633 of file QuartzQuantizationUtilities.h.
RequiresAudioDevice()
virtual bool Audio::IQuartzQuantizedCommand::RequiresAudioDevice () const inline virtual
Definition at line 638 of file QuartzQuantizationUtilities.h.
ShouldDeadlineIgnoresBpmChanges()
virtual bool Audio::IQuartzQuantizedCommand::ShouldDeadlineIgnoresBpmChanges () inline virtual
Definition at line 637 of file QuartzQuantizationUtilities.h.
Update()
void Audio::IQuartzQuantizedCommand::Update (int32 NumFramesUntilDeadline)
Definition at line 527 of file QuartzQuantizationUtilities.cpp.
References Audio::FQuartzQuantizedCommandDelegateData::CommandType, Audio::FQuartzQuantizedCommandDelegateData::DelegateID, Audio::FQuartzQuantizedCommandDelegateData::DelegateSubType, GameThreadDelegateID, GameThreadSubscribers, GetCommandType(), and TRACE_CPUPROFILER_EVENT_SCOPE.
Field Documentation
GameThreadDelegateID
int32 Audio::IQuartzQuantizedCommand::GameThreadDelegateID { -1 } private
Definition at line 656 of file QuartzQuantizationUtilities.h.
Referenced by AboutToStart(), Cancel(), FailedToQueue(), OnFinalCallback(), OnQueued(), and Update().
GameThreadSubscribers
TArray<FQuartzGameThreadSubscriber> Audio::IQuartzQuantizedCommand::GameThreadSubscribers private
Definition at line 654 of file QuartzQuantizationUtilities.h.
Referenced by AboutToStart(), AddSubscriber(), Cancel(), FailedToQueue(), OnFinalCallback(), OnQueued(), OnScheduled(), and Update().
The documentation for this class was generated from the following files:
Runtime/Engine/Classes/Sound/QuartzQuantizationUtilities.h
Runtime/Engine/Classes/Sound/QuartzQuantizationUtilities.cpp