Unreal Engine 5.6 C++ API: FStaticMeshComponentHelper Class Reference
FStaticMeshComponentHelper Class Reference
Helper class used to share implementation for different StaticMeshComponent types.
#include "StaticMeshComponentHelper.h"
Public Types
enum class ESceneProxyCreationError { None , WaitingPSOs , MeshCompiling , InvalidMesh }
Static Public Member Functions
template<class T>
static void CollectPSOPrecacheData (const T &Component, const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams)
template<class T>
static void CollectPSOPrecacheDataImpl (const T &Component, const FVertexFactoryType *VFType, const FPSOPrecacheParams &BasePrecachePSOParams, GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList &OutParams)
template<class T, bool bAssumeRenderDataIsReady = false>
static FPrimitiveSceneProxy * CreateSceneProxy (T &Component, FStaticMeshComponentHelper::ESceneProxyCreationError *OutError=nullptr)
template<class T>
static bool DoCustomNavigableGeometryExport (const T &Component, FNavigableGeometryExport &GeomExport)
template<class T>
static UMaterialInterface * GetMaterial (const T &Component, int32 MaterialIndex, bool bDoingNaniteMaterialAudit=false, bool bIgnoreNaniteOverrideMaterials=false)
template<class T>
static FBox GetNavigationBounds (const T &Component)
template<class T>
static void GetNavigationData (const T &Component, FNavigationRelevantData &Data)
template<class T>
static void GetUsedMaterials (const T &Component, TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials)
template<class T>
static void GetUsedRayTracingOnlyMaterials (const T &Component, TArray< UMaterialInterface * > &OutMaterials)
template<class T>
static bool IsNavigationRelevant (const T &Component)
Private Types
using GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)>
Detailed Description
Helper class used to share implementation for different StaticMeshComponent types.
Definition at line 22 of file StaticMeshComponentHelper.h.
Member Typedef Documentation
GetPSOVertexElementsFn
using FStaticMeshComponentHelper::GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)> private
Definition at line 24 of file StaticMeshComponentHelper.h.
Member Enumeration Documentation
ESceneProxyCreationError
enum class FStaticMeshComponentHelper::ESceneProxyCreationError strong
Enumerator
None
WaitingPSOs
MeshCompiling
InvalidMesh
Definition at line 27 of file StaticMeshComponentHelper.h.
Member Function Documentation
CollectPSOPrecacheData()
template<class T> void FStaticMeshComponentHelper::CollectPSOPrecacheData (const T & Component, const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) static
Definition at line 270 of file StaticMeshComponentHelper.h.
References CollectPSOPrecacheDataImpl(), Component, Default, FLocalVertexFactory::GetVertexElements(), LightMapCoordinateIndex, Nanite::FNaniteResourcesHelper::ShouldCreateNaniteProxy(), and FNaniteVertexFactory::StaticType.
CollectPSOPrecacheDataImpl()
template<class T> void FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl (const T & Component, const FVertexFactoryType * VFType, const FPSOPrecacheParams & BasePrecachePSOParams, FStaticMeshComponentHelper::GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList & OutParams) static
Definition at line 172 of file StaticMeshComponentHelper.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::AddDefaulted(), TArray< InElementType, InAllocatorType >::AddDefaulted_GetRef(), TArray< InElementType, InAllocatorType >::AddUnique(), FMaterialOverlayHelper::AppendAllOverlayMaterial(), FPSOPrecacheParams::bCastShadow, FStaticMeshSection::bCastShadow, FPSOPrecacheParams::bForceLODModel, FPSOPrecacheParams::bReverseCulling, check, Component, TArray< InElementType, InAllocatorType >::FindByPredicate(), FPSOPrecacheVertexFactoryDataPerMaterialIndex::MaterialIndex, FStaticMeshSection::MaterialIndex, FMaterialInterfacePSOPrecacheParams::MaterialInterface, TArray< InElementType, InAllocatorType >::Num(), TIndirectArray< T, Allocator >::Num(), Other, FMaterialInterfacePSOPrecacheParams::PSOPrecacheParams, FStaticMeshLODResources::Sections, FVertexFactoryType::SupportsManualVertexFetch(), FMaterialInterfacePSOPrecacheParams::VertexFactoryDataList, and FPSOPrecacheVertexFactoryDataPerMaterialIndex::VertexFactoryDataList.
Referenced by FInstancedStaticMeshComponentHelper::CollectPSOPrecacheData(), and CollectPSOPrecacheData().
CreateSceneProxy()
template<class T, bool bAssumeRenderDataIsReady> FPrimitiveSceneProxy * FStaticMeshComponentHelper::CreateSceneProxy (T & Component, FStaticMeshComponentHelper::ESceneProxyCreationError * OutError = nullptr) static
Definition at line 416 of file StaticMeshComponentHelper.h.
References Nanite::Allow, Nanite::AllowForDebugging, check, FMath::Clamp(), Component, DelayUntilPSOPrecached, UObjectHelper::GetFullNameIfAvailable(), Nanite::GetProxyRenderMode(), GetPSOPrecacheProxyCreationStrategy(), GetStaticMeshComponentBoostPSOPrecachePriority(), InvalidMesh, Nanite::IsMaskingAllowed(), Nanite::FMaterialAudit::IsValid(), FMath::Max, MeshCompiling, TIndirectArray< T, Allocator >::Num(), Scene, ShaderPlatform, StaticMesh, TEXT, UE_LOG, Verbose, WaitingPSOs, and Warning.
DoCustomNavigableGeometryExport()
template<class T> bool FStaticMeshComponentHelper::DoCustomNavigableGeometryExport (const T & Component, FNavigableGeometryExport & GeomExport) static
Definition at line 383 of file StaticMeshComponentHelper.h.
References Component, ensureMsgf, FVector, UObjectHelper::GetFullNameIfAvailable(), UE::Math::TVector< T >::IsZero(), Mesh, NavCollision, and TEXT.
GetMaterial()
template<class T> UMaterialInterface * FStaticMeshComponentHelper::GetMaterial (const T & Component, int32 MaterialIndex, bool bDoingNaniteMaterialAudit = false, bool bIgnoreNaniteOverrideMaterials = false) static
Definition at line 108 of file StaticMeshComponentHelper.h.
References Component.
GetNavigationBounds()
template<class T> FBox FStaticMeshComponentHelper::GetNavigationBounds (const T & Component) static
Definition at line 312 of file StaticMeshComponentHelper.h.
References Component, and Mesh.
GetNavigationData()
template<class T> void FStaticMeshComponentHelper::GetNavigationData (const T & Component, FNavigationRelevantData & Data) static
Definition at line 329 of file StaticMeshComponentHelper.h.
References Component, FVector, UE::Math::TVector< T >::IsZero(), Mesh, FNavigationRelevantData::Modifiers, and NavCollision.
GetUsedMaterials()
template<class T> void FStaticMeshComponentHelper::GetUsedMaterials (const T & Component, TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials) static
Definition at line 140 of file StaticMeshComponentHelper.h.
References TArray< InElementType, InAllocatorType >::Add(), FMaterialOverlayHelper::AppendAllOverlayMaterial(), Component, GetUsedRayTracingOnlyMaterials(), IsRayTracingAllowed(), and TArray< InElementType, InAllocatorType >::Num().
GetUsedRayTracingOnlyMaterials()
template<typename T> void FStaticMeshComponentHelper::GetUsedRayTracingOnlyMaterials (const T & Component, TArray< UMaterialInterface * > & OutMaterials) static
Definition at line 68 of file StaticMeshComponentHelper.h.
References TArray< InElementType, InAllocatorType >::Append(), Component, TArray< InElementType, InAllocatorType >::IsEmpty(), Material, and TArray< InElementType, InAllocatorType >::RemoveAll().
Referenced by GetUsedMaterials().
IsNavigationRelevant()
template<class T> bool FStaticMeshComponentHelper::IsNavigationRelevant (const T & Component) static
Definition at line 301 of file StaticMeshComponentHelper.h.
References Component, and Mesh.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/StaticMeshComponentHelper.h