Unreal Engine 5.6 C++ API: UBasic3DPointSetComponent Class Reference
UBasic3DPointSetComponent Class Reference final
Instantiation of a basic point set component in 3D using FVector3f for point positions.
#include "BasicPointSetComponent.h"
Public Member Functions
void Clear ()
Clear all points and component state.
Public Member Functions inherited from UBasicPointSetComponentBase
UBasicPointSetComponentBase ()
void ClearComponent ()
Clears the component state and marks component as dirty.
void SetColor (const FColor InColor)
Set per point material Color parameter that is uniform for all points.
void SetPointMaterial (UMaterialInterface *InPointMaterial)
Specify material that handles points.
void SetPointSetParameters (FColor InColor, float InSize, float InDepthBias)
Set per point material parameters that are uniform for all points.
void SetPointSize (const float InSize)
Set per point material Size parameter tat is uniform for all points.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Public Member Functions inherited from TBasicElementSet< FVector3f, 1 >
void AddElement (Targs... ElementPoints)
Add a point to be rendered using the component.
void ClearElements ()
int32 NumElements () const
Current number of points.
FVector3f & operator[] (int32 Index)
void ReserveAdditionalElements (const int32 AdditionalNum)
Reserve enough memory for an additional number of points over the existing number already reserved.
void ReserveElements (const int32 MaxNum)
Reserve enough memory for up to the given maximum number of points.
Private Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Friends
class FBasicPointSetSceneProxy
Additional Inherited Members
Public Types inherited from TBasicElementSet< FVector3f, 1 >
using GeometryType
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Static Public Attributes inherited from TBasicElementSet< FVector3f, 1 >
static const int32 ElementSize
Protected Member Functions inherited from UBasicPointSetComponentBase
virtual int32 GetNumMaterials () const override
template<typename CalcPointBoxFn>
FBoxSphereBounds UpdateComponentBounds (const FTransform &LocalToWorld, bool bPointsDirty, CalcPointBoxFn &&CalcPointBox) const
Update component bounds using a provided function that determines the box around all point positions.
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Member Functions inherited from TBasicElementSet< FVector3f, 1 >
void AddElementInternal (const T &ElementPoint, Targs... ElementPoints)
FBox CalcElementsBox () const
Protected Attributes inherited from UBasicPointSetComponentBase
bool bBoundsDirty = true
FBoxSphereBounds Bounds
FColor Color
float DepthBias = 0.0f
TObjectPtr< const UMaterialInterface > PointMaterial
float Size = 1.0f
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Protected Attributes inherited from TBasicElementSet< FVector3f, 1 >
bool bElementsDirty
TArray< FVector3f > Elements
int32 Num
Detailed Description
Instantiation of a basic point set component in 3D using FVector3f for point positions.
Definition at line 138 of file BasicPointSetComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UBasic3DPointSetComponent::CalcBounds (const FTransform & LocalToWorld) const inline override private virtual
Definition at line 156 of file BasicPointSetComponent.h.
References TBasicElementSet< FVector3f, 1 >::bElementsDirty, TBasicElementSet< FVector3f, 1 >::CalcElementsBox(), and UBasicPointSetComponentBase::UpdateComponentBounds().
Clear()
void UBasic3DPointSetComponent::Clear () inline
Clear all points and component state.
Definition at line 144 of file BasicPointSetComponent.h.
References Clear(), UBasicPointSetComponentBase::ClearComponent(), and TBasicElementSet< FVector3f, 1 >::ClearElements().
Referenced by Clear().
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UBasic3DPointSetComponent::CreateSceneProxy () override private virtual
Friends And Related Symbol Documentation
FBasicPointSetSceneProxy
friend class FBasicPointSetSceneProxy friend
Definition at line 162 of file BasicPointSetComponent.h.
References FBasicPointSetSceneProxy.
Referenced by FBasicPointSetSceneProxy.
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UBasic3DPointSetComponent::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 140 of file BasicPointSetComponent.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/Drawing/BasicPointSetComponent.h