Unreal Engine 5.6 C++ API: TValueOrError< void, ErrorType > Class Template Reference
TValueOrError< void, ErrorType > Class Template Reference
#include "ValueOrError.h"
Public Member Functions
template<typename... ArgTypes>
TValueOrError (TValueOrError_ErrorProxy< ArgTypes... > &&Proxy)
Construct the error from a proxy from MakeError.
TValueOrError (TValueOrError_ValueProxy<> &&Proxy)
Construct the value from a proxy from MakeValue.
ErrorType & GetError () &
Access the error.
ErrorType GetError () &&
const ErrorType & GetError () const &
void & GetValue () &
Access the value.
bool HasError () const
Whether the error is set.
bool HasValue () const
Whether the value is set.
bool IsValid () const
Check whether a value is set.
ErrorType StealError ()
Steal the error.
void StealValue ()
Steal the value.
ErrorType * TryGetError ()
Access the error if it is set.
const ErrorType * TryGetError () const
void * TryGetValue ()
Access the value if it is set.
Private Member Functions
template<typename... ArgTypes, uint32... ArgIndices>
TValueOrError (TValueOrError_ErrorProxy< ArgTypes... > &&Proxy, TIntegerSequence< uint32, ArgIndices... >)
Private Attributes
TOptional< ErrorType > Error
TVariant< void, FWrapErrorType, FEmptyType > Variant
Detailed Description
template<typename ErrorType>
class TValueOrError< void, ErrorType >
Definition at line 201 of file ValueOrError.h.
Constructor & Destructor Documentation
TValueOrError() [1/3]
template<typename ErrorType> template<typename... ArgTypes, uint32... ArgIndices> TValueOrError< void, ErrorType >::TValueOrError (TValueOrError_ErrorProxy< ArgTypes... > && Proxy, TIntegerSequence< uint32, ArgIndices... >) inline private
Definition at line 204 of file ValueOrError.h.
References Error, InPlace, and MoveTemp().
Referenced by TValueOrError().
TValueOrError() [2/3]
template<typename ErrorType> TValueOrError< void, ErrorType >::TValueOrError (TValueOrError_ValueProxy<> && Proxy) inline
Construct the value from a proxy from MakeValue.
Definition at line 211 of file ValueOrError.h.
TValueOrError() [3/3]
template<typename ErrorType> template<typename... ArgTypes> TValueOrError< void, ErrorType >::TValueOrError (TValueOrError_ErrorProxy< ArgTypes... > && Proxy) inline
Construct the error from a proxy from MakeError.
Definition at line 217 of file ValueOrError.h.
References TValueOrError(), and MoveTemp().
Member Function Documentation
GetError() [1/3]
template<typename ErrorType> ErrorType & TValueOrError< void, ErrorType >::GetError () & inline
Access the error.
Asserts if this does not have an error.
Definition at line 229 of file ValueOrError.h.
References Error.
GetError() [2/3]
template<typename ErrorType> ErrorType TValueOrError< void, ErrorType >::GetError () && inline
Definition at line 231 of file ValueOrError.h.
References Error, and MoveTemp().
GetError() [3/3]
template<typename ErrorType> const ErrorType & TValueOrError< void, ErrorType >::GetError () const & inline
Definition at line 230 of file ValueOrError.h.
References Error.
GetValue()
void & TValueOrError< void, ErrorType >::GetValue () & inline
Access the value.
Asserts if this does not have a value.
Definition at line 131 of file ValueOrError.h.
HasError()
template<typename ErrorType> bool TValueOrError< void, ErrorType >::HasError () const inline
Whether the error is set.
An error does imply no value.
Definition at line 226 of file ValueOrError.h.
References Error.
HasValue()
template<typename ErrorType> bool TValueOrError< void, ErrorType >::HasValue () const inline
Whether the value is set.
A value does imply no error.
Definition at line 223 of file ValueOrError.h.
References Error.
IsValid()
bool TValueOrError< void, ErrorType >::IsValid () const inline
Check whether a value is set.
Prefer HasValue and HasError to this. !IsValid() does not imply HasError().
Definition at line 91 of file ValueOrError.h.
StealError()
template<typename ErrorType> ErrorType TValueOrError< void, ErrorType >::StealError () inline
Steal the error.
Asserts if this does not have an error. This causes the error to be unset.
Definition at line 238 of file ValueOrError.h.
References Error, TValueOrError< ValueType, ErrorType >::GetError(), and MoveTemp().
StealValue()
void TValueOrError< void, ErrorType >::StealValue () inline
Steal the value.
Asserts if this does not have a value. This causes the value to be unset.
Definition at line 140 of file ValueOrError.h.
TryGetError() [1/2]
template<typename ErrorType> ErrorType * TValueOrError< void, ErrorType >::TryGetError () inline
Access the error if it is set.
Definition at line 234 of file ValueOrError.h.
References Error.
TryGetError() [2/2]
template<typename ErrorType> const ErrorType * TValueOrError< void, ErrorType >::TryGetError () const inline
Definition at line 235 of file ValueOrError.h.
References Error.
TryGetValue()
void * TValueOrError< void, ErrorType >::TryGetValue () inline
Access the value if it is set.
Definition at line 136 of file ValueOrError.h.
Field Documentation
Error
template<typename ErrorType> TOptional<ErrorType> TValueOrError< void, ErrorType >::Error private
Definition at line 246 of file ValueOrError.h.
Referenced by TValueOrError(), GetError(), GetError(), GetError(), HasError(), HasValue(), StealError(), TryGetError(), and TryGetError().
Variant
TVariant<void, FWrapErrorType, FEmptyType> TValueOrError< void, ErrorType >::Variant private
Definition at line 148 of file ValueOrError.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/ValueOrError.h