Unreal Engine 5.6 C++ API: FMovieSceneClipboardKeyTrack Class Reference
FMovieSceneClipboardKeyTrack Class Reference
Container for a collection of keys arranged in a track.
#include "MovieSceneClipboard.h"
Public Member Functions
MOVIESCENE_API FMovieSceneClipboardKeyTrack (const FMovieSceneClipboardKeyTrack &In)
Copy construction/assignment.
MOVIESCENE_API FMovieSceneClipboardKeyTrack (FMovieSceneClipboardKeyTrack &&In)
Move construction/assignment.
template<typename KeyType>
void AddKey (FFrameNumber Time, KeyType Value)
Add a key of the specified type to this track.
MOVIESCENE_API const FName & GetName () const
Get the name of this track.
template<typename KeyType>
bool IsKeyOfType () const
Check the type of the keys contained within this track.
bool IterateKeys (TFunctionRef< bool(const FMovieSceneClipboardKey &Key)> Iter) const
Iterate the keys contained within this track.
bool IterateKeys (TFunctionRef< bool(FMovieSceneClipboardKey &Key)> Iter)
MOVIESCENE_API FMovieSceneClipboardKeyTrack & operator= (const FMovieSceneClipboardKeyTrack &In)
MOVIESCENE_API FMovieSceneClipboardKeyTrack & operator= (FMovieSceneClipboardKeyTrack &&In)
Static Public Member Functions
template<typename KeyType>
static FMovieSceneClipboardKeyTrack Create (FName InName, FFrameNumber KeyOffset=0)
Create a key track that wraps the specified key type.
Private Member Functions
FMovieSceneClipboardKeyTrack ()
Private Attributes
FFrameNumber KeyOffset
Optional key offset that is applied to all keys added to the clipboard.
TArray< FMovieSceneClipboardKey > Keys
Collection of keys contained within this track.
FName Name
Generic name of this track (generally the name of a key area within a track e.g.
FName TypeName
Type name for the value of the keys this track supports.
Detailed Description
Container for a collection of keys arranged in a track.
Definition at line 189 of file MovieSceneClipboard.h.
Constructor & Destructor Documentation
FMovieSceneClipboardKeyTrack() [1/3]
MOVIESCENE_API FMovieSceneClipboardKeyTrack::FMovieSceneClipboardKeyTrack (FMovieSceneClipboardKeyTrack && In)
Move construction/assignment.
References FMovieSceneClipboardKeyTrack().
Referenced by FMovieSceneClipboardKeyTrack(), FMovieSceneClipboardKeyTrack(), Create(), operator=(), and operator=().
FMovieSceneClipboardKeyTrack() [2/3]
MOVIESCENE_API FMovieSceneClipboardKeyTrack::FMovieSceneClipboardKeyTrack (const FMovieSceneClipboardKeyTrack & In)
Copy construction/assignment.
References FMovieSceneClipboardKeyTrack().
FMovieSceneClipboardKeyTrack() [3/3]
FMovieSceneClipboardKeyTrack::FMovieSceneClipboardKeyTrack () inline private
Definition at line 264 of file MovieSceneClipboard.h.
Member Function Documentation
AddKey()
template<typename KeyType> void FMovieSceneClipboardKeyTrack::AddKey (FFrameNumber Time, KeyType Value) inline
Add a key of the specified type to this track.
KeyType must match the type this track was constructed with
Definition at line 223 of file MovieSceneClipboard.h.
References checkf, IsKeyOfType(), KeyOffset, Keys, MoveTemp(), TEXT, Time, and Value.
Referenced by Sequencer::CopyKeys().
Create()
template<typename KeyType> FMovieSceneClipboardKeyTrack FMovieSceneClipboardKeyTrack::Create (FName InName, FFrameNumber KeyOffset = 0) inline static
Create a key track that wraps the specified key type.
Definition at line 195 of file MovieSceneClipboard.h.
References FMovieSceneClipboardKeyTrack(), MovieSceneClipboard::GetKeyTypeName(), InName, KeyOffset, MoveTemp(), Name, and TypeName.
Referenced by FMovieSceneClipboardBuilder::FindOrAddKeyTrack().
GetName()
MOVIESCENE_API const FName & FMovieSceneClipboardKeyTrack::GetName () const
Get the name of this track.
Referenced by FMovieSceneClipboardBuilder::FindOrAddKeyTrack().
IsKeyOfType()
template<typename KeyType> bool FMovieSceneClipboardKeyTrack::IsKeyOfType () const inline
Check the type of the keys contained within this track.
Definition at line 216 of file MovieSceneClipboard.h.
References MovieSceneClipboard::GetKeyTypeName(), and TypeName.
Referenced by AddKey().
IterateKeys() [1/2]
bool FMovieSceneClipboardKeyTrack::IterateKeys (TFunctionRef< bool(const FMovieSceneClipboardKey &Key)> Iter) const inline
Iterate the keys contained within this track.
Parameters
Iter Predicate function to call for every key in this track. return true to continue iteration, false to abort
Definition at line 236 of file MovieSceneClipboard.h.
References Key, and Keys.
Referenced by Sequencer::PasteKeys().
IterateKeys() [2/2]
bool FMovieSceneClipboardKeyTrack::IterateKeys (TFunctionRef< bool(FMovieSceneClipboardKey &Key)> Iter) inline
Definition at line 247 of file MovieSceneClipboard.h.
References Key, and Keys.
operator=() [1/2]
MOVIESCENE_API FMovieSceneClipboardKeyTrack & FMovieSceneClipboardKeyTrack::operator= (const FMovieSceneClipboardKeyTrack & In)
References FMovieSceneClipboardKeyTrack().
operator=() [2/2]
MOVIESCENE_API FMovieSceneClipboardKeyTrack & FMovieSceneClipboardKeyTrack::operator= (FMovieSceneClipboardKeyTrack && In)
References FMovieSceneClipboardKeyTrack().
Field Documentation
KeyOffset
FFrameNumber FMovieSceneClipboardKeyTrack::KeyOffset private
Optional key offset that is applied to all keys added to the clipboard.
Definition at line 277 of file MovieSceneClipboard.h.
Referenced by AddKey(), and Create().
Keys
TArray<FMovieSceneClipboardKey> FMovieSceneClipboardKeyTrack::Keys private
Collection of keys contained within this track.
Definition at line 268 of file MovieSceneClipboard.h.
Referenced by AddKey(), IterateKeys(), and IterateKeys().
Name
FName FMovieSceneClipboardKeyTrack::Name private
Generic name of this track (generally the name of a key area within a track e.g.
Location.X)
Definition at line 274 of file MovieSceneClipboard.h.
Referenced by Create().
TypeName
FName FMovieSceneClipboardKeyTrack::TypeName private
Type name for the value of the keys this track supports.
Definition at line 271 of file MovieSceneClipboard.h.
Referenced by Create(), and IsKeyOfType().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/MovieSceneClipboard.h