Unreal Engine 5.6 C++ API: SAudioOscilloscopePanelWidget Class Reference
SAudioOscilloscopePanelWidget Class Reference
#include "SAudioOscilloscopePanelWidget.h"
Public Member Functions
AUDIOWIDGETS_API void BuildWidget (const FFixedSampledSequenceView &InData, const int32 InNumChannels, const EAudioPanelLayoutType InPanelLayoutType)
EAudioPanelLayoutType GetPanelLayoutType ()
virtual AUDIOWIDGETS_API void ReceiveSequenceView (const FFixedSampledSequenceView InData, const uint32 FirstSampleIndex) override
AUDIOWIDGETS_API void SetAnalysisPeriod (const float InAnalysisPeriod)
AUDIOWIDGETS_API void SetChannelToAnalyze (const int32 InChannelToAnalyze)
AUDIOWIDGETS_API void SetMaxTimeWindowMs (const float InMaxTimeWindowMs)
AUDIOWIDGETS_API void SetSequenceRulerDisplayUnit (const EXAxisLabelsUnit InDisplayUnit)
AUDIOWIDGETS_API void SetTimeWindow (const float InTimeWindow)
AUDIOWIDGETS_API void SetTriggerMode (const EAudioOscilloscopeTriggerMode InTriggerMode)
AUDIOWIDGETS_API void SetTriggerThreshold (const float InTriggerThreshold)
AUDIOWIDGETS_API void SetValueGridOverlayDisplayUnit (const EYAxisLabelsUnit InDisplayUnit)
AUDIOWIDGETS_API void SetXAxisGridVisibility (const bool InbIsVisible)
AUDIOWIDGETS_API void SetYAxisGridVisibility (const bool InbIsVisible)
AUDIOWIDGETS_API void SetYAxisLabelsVisibility (const bool InbIsVisible)
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit SLATE_ARGUMENT (EAudioPanelLayoutType, PanelLayoutType) SLATE_STYLE_ARGUMENT(FAudioOscilloscopePanelStyle
If we want to set the basic or advanced layout.
HideSequenceGrid HideValueGrid YAxisLabelsUnit SLATE_ARGUMENT (uint32, ValueGridMaxDivisionParameter) SLATE_ARGUMENT(EXAxisLabelsUnit
Maximum number of divisions in the value grid.
HideSequenceGrid SLATE_ATTRIBUTE (bool, HideSequenceRuler) SLATE_ATTRIBUTE(bool
Whether the sequence ruler should be drawn or not.
HideSequenceGrid HideValueGrid SLATE_ATTRIBUTE (bool, HideTriggerThresholdLine) SLATE_ATTRIBUTE(EYAxisLabelsUnit
Whether the trigger threshold line should be drawn or not.
SLATE_BEGIN_ARGS (SAudioOscilloscopePanelWidget)
SLATE_DEFAULT_SLOT (FArguments, InArgs) SLATE_ATTRIBUTE(bool
Whether the sequenbce grid should be drawn or not.
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit PanelStyle SLATE_END_ARGS () AUDIOWIDGETS_API void Construct(const FArguments &InArgs
virtual AUDIOWIDGETS_API void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
AUDIOWIDGETS_API void UpdateSequenceRulerStyle (const FFixedSampleSequenceRulerStyle UpdatedRulerStyle)
AUDIOWIDGETS_API void UpdateSequenceViewerStyle (const FSampledSequenceViewerStyle UpdatedSequenceViewerStyle)
AUDIOWIDGETS_API void UpdateTriggerThresholdStyle (const FTriggerThresholdLineStyle UpdatedStyle)
AUDIOWIDGETS_API void UpdateValueGridOverlayStyle (const FSampledSequenceValueGridOverlayStyle UpdatedValueGridOverlayStyle)
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from IFixedSampledSequenceViewReceiver
virtual ~IFixedSampledSequenceViewReceiver ()=default
Data Fields
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit PanelStyle const FFixedSampledSequenceView & InData
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit PanelStyle const FFixedSampledSequenceView const int32 InNumChannels
FOnAnalysisPeriodChanged OnAnalysisPeriodChanged
FOnSelectedChannelChanged OnSelectedChannelChanged
FOnTimeWindowValueChanged OnTimeWindowValueChanged
FOnTriggerModeChanged OnTriggerModeChanged
FOnTriggerThresholdChanged OnTriggerThresholdChanged
Private Member Functions
AUDIOWIDGETS_API void CreateAnalysisPeriodKnob ()
AUDIOWIDGETS_API void CreateBackground (const FSampledSequenceViewerStyle &ViewerStyle)
AUDIOWIDGETS_API void CreateChannelCombobox ()
AUDIOWIDGETS_API void CreateGridData (const FFixedSampleSequenceRulerStyle &RulerStyle)
AUDIOWIDGETS_API void CreateLayout ()
AUDIOWIDGETS_API void CreateOscilloscopeControls ()
AUDIOWIDGETS_API void CreateSequenceRuler (TSharedRef< FFixedSampledSequenceGridData > InGridData, const FFixedSampleSequenceRulerStyle &RulerStyle)
AUDIOWIDGETS_API void CreateSequenceViewer (TSharedRef< FFixedSampledSequenceGridData > InGridData, const FFixedSampledSequenceView &InData, const FSampledSequenceViewerStyle &ViewerStyle)
AUDIOWIDGETS_API void CreateTimeWindowKnob ()
AUDIOWIDGETS_API void CreateTriggerModeCombobox ()
AUDIOWIDGETS_API void CreateTriggerThresholdKnob ()
AUDIOWIDGETS_API void CreateTriggerThresholdLine (const FTriggerThresholdLineStyle &TriggerThresholdLineStyle)
AUDIOWIDGETS_API void CreateValueGridOverlay (const uint32 MaxDivisionParameter, const SampledSequenceValueGridOverlay::EGridDivideMode DivideMode, const EYAxisLabelsUnit InValueGridOverlayDisplayUnit, const FSampledSequenceValueGridOverlayStyle &ValueGridStyle)
Private Attributes
TSharedPtr< SAudioRadialSlider > AnalysisPeriodKnob
float AnalysisPeriodValue = 0.0f
TSharedPtr< SBorder > BackgroundBorder
bool bHideSequenceGrid = false
bool bHideSequenceRuler = false
bool bHideTriggerThresholdLine = true
bool bHideValueGrid = false
bool bIsInputWidgetTransacting = false
float CachedPixelWidth = 0.0f
TSharedPtr< SComboBox< TSharedPtr< FString > > > ChannelCombobox
TArray< TSharedPtr< FString > > ChannelComboboxOptionsSource
FFixedSampledSequenceView DataView
SampledSequenceDrawingUtils::FSampledSequenceDrawingParams DrawingParams
uint32 NumChannels = 0
float OscilloscopeViewProportion = 1.0f
EAudioPanelLayoutType PanelLayoutType = EAudioPanelLayoutType::Basic
const FAudioOscilloscopePanelStyle * PanelStyle = nullptr
TSharedPtr< FString > SelectedChannelPtr
TSharedPtr< EAudioOscilloscopeTriggerMode > SelectedTriggerModePtr
TSharedPtr< FFixedSampledSequenceGridData > SequenceGridData
TSharedPtr< SFixedSampledSequenceRuler > SequenceRuler
EXAxisLabelsUnit SequenceRulerDisplayUnit
TSharedPtr< SFixedSampledSequenceViewer > SequenceViewer
TSharedPtr< SAudioRadialSlider > TimeWindowKnob
FVector2D TimeWindowKnobOutputRange = { 10.0, 5000.0 }
float TimeWindowValue = 0.0f
TSharedPtr< SComboBox< TSharedPtr< EAudioOscilloscopeTriggerMode > > > TriggerModeCombobox
TArray< TSharedPtr< EAudioOscilloscopeTriggerMode > > TriggerModeComboboxOptionsSource
TSharedPtr< SAudioRadialSlider > TriggerThresholdKnob
TSharedPtr< STriggerThresholdLineWidget > TriggerThresholdLineWidget
float TriggerThresholdValue = 0.0f
uint32 ValueGridMaxDivisionParameter = 2
TSharedPtr< SSampledSequenceValueGridOverlay > ValueGridOverlay
EYAxisLabelsUnit ValueGridOverlayDisplayUnit
Static Private Attributes
static const FVector2D AnalysisPeriodKnobOutputRange = { 10.0, 1000.0 }
static const FVector2D TriggerThresholdKnobOutputRange = { -1.0, 1.0 }
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Definition at line 49 of file SAudioOscilloscopePanelWidget.h.
Member Function Documentation
BuildWidget()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::BuildWidget (const FFixedSampledSequenceView & InData, const int32 InNumChannels, const EAudioPanelLayoutType InPanelLayoutType)
References BuildWidget(), InData, InNumChannels, and UE_API.
Referenced by BuildWidget().
CreateAnalysisPeriodKnob()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateAnalysisPeriodKnob () private
References UE_API.
CreateBackground()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateBackground (const FSampledSequenceViewerStyle & ViewerStyle) private
References UE_API.
CreateChannelCombobox()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateChannelCombobox () private
References UE_API.
CreateGridData()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateGridData (const FFixedSampleSequenceRulerStyle & RulerStyle) private
References UE_API.
CreateLayout()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateLayout () private
References UE_API.
CreateOscilloscopeControls()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateOscilloscopeControls () private
References UE_API.
CreateSequenceRuler()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateSequenceRuler (TSharedRef< FFixedSampledSequenceGridData > InGridData, const FFixedSampleSequenceRulerStyle & RulerStyle) private
References UE_API.
CreateSequenceViewer()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateSequenceViewer (TSharedRef< FFixedSampledSequenceGridData > InGridData, const FFixedSampledSequenceView & InData, const FSampledSequenceViewerStyle & ViewerStyle) private
References InData, and UE_API.
CreateTimeWindowKnob()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateTimeWindowKnob () private
References UE_API.
CreateTriggerModeCombobox()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateTriggerModeCombobox () private
References UE_API.
CreateTriggerThresholdKnob()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateTriggerThresholdKnob () private
References UE_API.
CreateTriggerThresholdLine()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateTriggerThresholdLine (const FTriggerThresholdLineStyle & TriggerThresholdLineStyle) private
References UE_API.
CreateValueGridOverlay()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::CreateValueGridOverlay (const uint32 MaxDivisionParameter, const SampledSequenceValueGridOverlay::EGridDivideMode DivideMode, const EYAxisLabelsUnit InValueGridOverlayDisplayUnit, const FSampledSequenceValueGridOverlayStyle & ValueGridStyle) private
References UE_API.
GetPanelLayoutType()
EAudioPanelLayoutType SAudioOscilloscopePanelWidget::GetPanelLayoutType () inline
Definition at line 125 of file SAudioOscilloscopePanelWidget.h.
References GetPanelLayoutType(), and PanelLayoutType.
Referenced by GetPanelLayoutType().
ReceiveSequenceView()
virtual AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::ReceiveSequenceView (const FFixedSampledSequenceView InData, const uint32 FirstSampleIndex) override virtual
Implements IFixedSampledSequenceViewReceiver.
References InData, ReceiveSequenceView(), and UE_API.
Referenced by ReceiveSequenceView().
SetAnalysisPeriod()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetAnalysisPeriod (const float InAnalysisPeriod)
References SetAnalysisPeriod(), and UE_API.
Referenced by SetAnalysisPeriod().
SetChannelToAnalyze()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetChannelToAnalyze (const int32 InChannelToAnalyze)
References SetChannelToAnalyze(), and UE_API.
Referenced by SetChannelToAnalyze().
SetMaxTimeWindowMs()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetMaxTimeWindowMs (const float InMaxTimeWindowMs)
References SetMaxTimeWindowMs(), and UE_API.
Referenced by SetMaxTimeWindowMs().
SetSequenceRulerDisplayUnit()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetSequenceRulerDisplayUnit (const EXAxisLabelsUnit InDisplayUnit)
References SetSequenceRulerDisplayUnit(), and UE_API.
Referenced by SetSequenceRulerDisplayUnit().
SetTimeWindow()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetTimeWindow (const float InTimeWindow)
References SetTimeWindow(), and UE_API.
Referenced by SetTimeWindow().
SetTriggerMode()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetTriggerMode (const EAudioOscilloscopeTriggerMode InTriggerMode)
References SetTriggerMode(), and UE_API.
Referenced by SetTriggerMode().
SetTriggerThreshold()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetTriggerThreshold (const float InTriggerThreshold)
References SetTriggerThreshold(), and UE_API.
Referenced by SetTriggerThreshold().
SetValueGridOverlayDisplayUnit()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetValueGridOverlayDisplayUnit (const EYAxisLabelsUnit InDisplayUnit)
References SetValueGridOverlayDisplayUnit(), and UE_API.
Referenced by SetValueGridOverlayDisplayUnit().
SetXAxisGridVisibility()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetXAxisGridVisibility (const bool InbIsVisible)
References SetXAxisGridVisibility(), and UE_API.
Referenced by SetXAxisGridVisibility().
SetYAxisGridVisibility()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetYAxisGridVisibility (const bool InbIsVisible)
References SetYAxisGridVisibility(), and UE_API.
Referenced by SetYAxisGridVisibility().
SetYAxisLabelsVisibility()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::SetYAxisLabelsVisibility (const bool InbIsVisible)
References SetYAxisLabelsVisibility(), and UE_API.
Referenced by SetYAxisLabelsVisibility().
SLATE_ARGUMENT() [1/2]
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit SAudioOscilloscopePanelWidget::SLATE_ARGUMENT (EAudioPanelLayoutType , PanelLayoutType)
If we want to set the basic or advanced layout.
Oscilloscope Panel widget style
References PanelLayoutType, PanelStyle, SLATE_ARGUMENT(), and SLATE_STYLE_ARGUMENT.
SLATE_ARGUMENT() [2/2]
HideSequenceGrid HideValueGrid YAxisLabelsUnit SAudioOscilloscopePanelWidget::SLATE_ARGUMENT (uint32 , ValueGridMaxDivisionParameter)
Maximum number of divisions in the value grid.
Sequence ruler display unit
References SequenceRulerDisplayUnit, SLATE_ARGUMENT(), and ValueGridMaxDivisionParameter.
Referenced by SLATE_ARGUMENT(), and SLATE_ARGUMENT().
SLATE_ATTRIBUTE() [1/2]
HideSequenceGrid SAudioOscilloscopePanelWidget::SLATE_ATTRIBUTE (bool , HideSequenceRuler)
Whether the sequence ruler should be drawn or not.
Whether the value grid should be drawn or not
References SLATE_ATTRIBUTE().
Referenced by SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/2]
HideSequenceGrid HideValueGrid SAudioOscilloscopePanelWidget::SLATE_ATTRIBUTE (bool , HideTriggerThresholdLine)
Whether the trigger threshold line should be drawn or not.
Whether the value grid values are linear or in dB
References SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SAudioOscilloscopePanelWidget::SLATE_BEGIN_ARGS (SAudioOscilloscopePanelWidget) inline
Definition at line 52 of file SAudioOscilloscopePanelWidget.h.
References Linear, and Samples.
SLATE_DEFAULT_SLOT()
SAudioOscilloscopePanelWidget::SLATE_DEFAULT_SLOT (FArguments , InArgs)
Whether the sequenbce grid should be drawn or not.
SLATE_END_ARGS()
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit PanelStyle SAudioOscilloscopePanelWidget::SLATE_END_ARGS () const &
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Tick()
virtual AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
References Tick(), and UE_API.
Referenced by Tick().
UpdateSequenceRulerStyle()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::UpdateSequenceRulerStyle (const FFixedSampleSequenceRulerStyle UpdatedRulerStyle)
References UE_API, and UpdateSequenceRulerStyle().
Referenced by UpdateSequenceRulerStyle().
UpdateSequenceViewerStyle()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::UpdateSequenceViewerStyle (const FSampledSequenceViewerStyle UpdatedSequenceViewerStyle)
References UE_API, and UpdateSequenceViewerStyle().
Referenced by UpdateSequenceViewerStyle().
UpdateTriggerThresholdStyle()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::UpdateTriggerThresholdStyle (const FTriggerThresholdLineStyle UpdatedStyle)
References UE_API, and UpdateTriggerThresholdStyle().
Referenced by UpdateTriggerThresholdStyle().
UpdateValueGridOverlayStyle()
AUDIOWIDGETS_API void SAudioOscilloscopePanelWidget::UpdateValueGridOverlayStyle (const FSampledSequenceValueGridOverlayStyle UpdatedValueGridOverlayStyle)
References UE_API, and UpdateValueGridOverlayStyle().
Referenced by UpdateValueGridOverlayStyle().
Field Documentation
AnalysisPeriodKnob
TSharedPtr<SAudioRadialSlider> SAudioOscilloscopePanelWidget::AnalysisPeriodKnob private
Definition at line 174 of file SAudioOscilloscopePanelWidget.h.
AnalysisPeriodKnobOutputRange
const FVector2D SAudioOscilloscopePanelWidget::AnalysisPeriodKnobOutputRange = { 10.0, 1000.0 } inline static private
Definition at line 177 of file SAudioOscilloscopePanelWidget.h.
AnalysisPeriodValue
float SAudioOscilloscopePanelWidget::AnalysisPeriodValue = 0.0f private
Definition at line 189 of file SAudioOscilloscopePanelWidget.h.
BackgroundBorder
TSharedPtr<SBorder> SAudioOscilloscopePanelWidget::BackgroundBorder private
Definition at line 157 of file SAudioOscilloscopePanelWidget.h.
bHideSequenceGrid
bool SAudioOscilloscopePanelWidget::bHideSequenceGrid = false private
Definition at line 202 of file SAudioOscilloscopePanelWidget.h.
bHideSequenceRuler
bool SAudioOscilloscopePanelWidget::bHideSequenceRuler = false private
Definition at line 203 of file SAudioOscilloscopePanelWidget.h.
bHideTriggerThresholdLine
bool SAudioOscilloscopePanelWidget::bHideTriggerThresholdLine = true private
Definition at line 206 of file SAudioOscilloscopePanelWidget.h.
bHideValueGrid
bool SAudioOscilloscopePanelWidget::bHideValueGrid = false private
Definition at line 204 of file SAudioOscilloscopePanelWidget.h.
bIsInputWidgetTransacting
bool SAudioOscilloscopePanelWidget::bIsInputWidgetTransacting = false private
Definition at line 185 of file SAudioOscilloscopePanelWidget.h.
CachedPixelWidth
float SAudioOscilloscopePanelWidget::CachedPixelWidth = 0.0f private
Definition at line 191 of file SAudioOscilloscopePanelWidget.h.
ChannelCombobox
TSharedPtr<SComboBox<TSharedPtr<FString> > > SAudioOscilloscopePanelWidget::ChannelCombobox private
Definition at line 164 of file SAudioOscilloscopePanelWidget.h.
ChannelComboboxOptionsSource
TArray<TSharedPtr<FString> > SAudioOscilloscopePanelWidget::ChannelComboboxOptionsSource private
Definition at line 165 of file SAudioOscilloscopePanelWidget.h.
DataView
FFixedSampledSequenceView SAudioOscilloscopePanelWidget::DataView private
Definition at line 199 of file SAudioOscilloscopePanelWidget.h.
DrawingParams
SampledSequenceDrawingUtils::FSampledSequenceDrawingParams SAudioOscilloscopePanelWidget::DrawingParams private
Definition at line 200 of file SAudioOscilloscopePanelWidget.h.
InData
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit PanelStyle const FFixedSampledSequenceView& SAudioOscilloscopePanelWidget::InData
Definition at line 95 of file SAudioOscilloscopePanelWidget.h.
Referenced by BuildWidget(), CreateSequenceViewer(), and ReceiveSequenceView().
InNumChannels
HideSequenceGrid HideValueGrid YAxisLabelsUnit SequenceRulerDisplayUnit PanelStyle const FFixedSampledSequenceView const int32 SAudioOscilloscopePanelWidget::InNumChannels
Definition at line 95 of file SAudioOscilloscopePanelWidget.h.
Referenced by BuildWidget().
NumChannels
uint32 SAudioOscilloscopePanelWidget::NumChannels = 0 private
Definition at line 183 of file SAudioOscilloscopePanelWidget.h.
OnAnalysisPeriodChanged
FOnAnalysisPeriodChanged SAudioOscilloscopePanelWidget::OnAnalysisPeriodChanged
Definition at line 131 of file SAudioOscilloscopePanelWidget.h.
OnSelectedChannelChanged
FOnSelectedChannelChanged SAudioOscilloscopePanelWidget::OnSelectedChannelChanged
Definition at line 127 of file SAudioOscilloscopePanelWidget.h.
OnTimeWindowValueChanged
FOnTimeWindowValueChanged SAudioOscilloscopePanelWidget::OnTimeWindowValueChanged
Definition at line 130 of file SAudioOscilloscopePanelWidget.h.
OnTriggerModeChanged
FOnTriggerModeChanged SAudioOscilloscopePanelWidget::OnTriggerModeChanged
Definition at line 128 of file SAudioOscilloscopePanelWidget.h.
OnTriggerThresholdChanged
FOnTriggerThresholdChanged SAudioOscilloscopePanelWidget::OnTriggerThresholdChanged
Definition at line 129 of file SAudioOscilloscopePanelWidget.h.
OscilloscopeViewProportion
float SAudioOscilloscopePanelWidget::OscilloscopeViewProportion = 1.0f private
Definition at line 192 of file SAudioOscilloscopePanelWidget.h.
PanelLayoutType
EAudioPanelLayoutType SAudioOscilloscopePanelWidget::PanelLayoutType = EAudioPanelLayoutType::Basic private
Definition at line 181 of file SAudioOscilloscopePanelWidget.h.
Referenced by GetPanelLayoutType(), and SLATE_ARGUMENT().
PanelStyle
const FAudioOscilloscopePanelStyle* SAudioOscilloscopePanelWidget::PanelStyle = nullptr private
Definition at line 153 of file SAudioOscilloscopePanelWidget.h.
Referenced by SLATE_ARGUMENT().
SelectedChannelPtr
TSharedPtr<FString> SAudioOscilloscopePanelWidget::SelectedChannelPtr private
Definition at line 166 of file SAudioOscilloscopePanelWidget.h.
SelectedTriggerModePtr
TSharedPtr<EAudioOscilloscopeTriggerMode> SAudioOscilloscopePanelWidget::SelectedTriggerModePtr private
Definition at line 170 of file SAudioOscilloscopePanelWidget.h.
SequenceGridData
TSharedPtr<FFixedSampledSequenceGridData> SAudioOscilloscopePanelWidget::SequenceGridData private
Definition at line 156 of file SAudioOscilloscopePanelWidget.h.
SequenceRuler
TSharedPtr<SFixedSampledSequenceRuler> SAudioOscilloscopePanelWidget::SequenceRuler private
Definition at line 158 of file SAudioOscilloscopePanelWidget.h.
SequenceRulerDisplayUnit
EXAxisLabelsUnit SAudioOscilloscopePanelWidget::SequenceRulerDisplayUnit private
Definition at line 194 of file SAudioOscilloscopePanelWidget.h.
Referenced by SLATE_ARGUMENT().
SequenceViewer
TSharedPtr<SFixedSampledSequenceViewer> SAudioOscilloscopePanelWidget::SequenceViewer private
Definition at line 159 of file SAudioOscilloscopePanelWidget.h.
TimeWindowKnob
TSharedPtr<SAudioRadialSlider> SAudioOscilloscopePanelWidget::TimeWindowKnob private
Definition at line 173 of file SAudioOscilloscopePanelWidget.h.
TimeWindowKnobOutputRange
FVector2D SAudioOscilloscopePanelWidget::TimeWindowKnobOutputRange = { 10.0, 5000.0 } private
Definition at line 179 of file SAudioOscilloscopePanelWidget.h.
TimeWindowValue
float SAudioOscilloscopePanelWidget::TimeWindowValue = 0.0f private
Definition at line 188 of file SAudioOscilloscopePanelWidget.h.
TriggerModeCombobox
TSharedPtr<SComboBox<TSharedPtr<EAudioOscilloscopeTriggerMode> > > SAudioOscilloscopePanelWidget::TriggerModeCombobox private
Definition at line 168 of file SAudioOscilloscopePanelWidget.h.
TriggerModeComboboxOptionsSource
TArray<TSharedPtr<EAudioOscilloscopeTriggerMode> > SAudioOscilloscopePanelWidget::TriggerModeComboboxOptionsSource private
Definition at line 169 of file SAudioOscilloscopePanelWidget.h.
TriggerThresholdKnob
TSharedPtr<SAudioRadialSlider> SAudioOscilloscopePanelWidget::TriggerThresholdKnob private
Definition at line 172 of file SAudioOscilloscopePanelWidget.h.
TriggerThresholdKnobOutputRange
const FVector2D SAudioOscilloscopePanelWidget::TriggerThresholdKnobOutputRange = { -1.0, 1.0 } inline static private
Definition at line 176 of file SAudioOscilloscopePanelWidget.h.
TriggerThresholdLineWidget
TSharedPtr<STriggerThresholdLineWidget> SAudioOscilloscopePanelWidget::TriggerThresholdLineWidget private
Definition at line 161 of file SAudioOscilloscopePanelWidget.h.
TriggerThresholdValue
float SAudioOscilloscopePanelWidget::TriggerThresholdValue = 0.0f private
Definition at line 187 of file SAudioOscilloscopePanelWidget.h.
ValueGridMaxDivisionParameter
uint32 SAudioOscilloscopePanelWidget::ValueGridMaxDivisionParameter = 2 private
Definition at line 197 of file SAudioOscilloscopePanelWidget.h.
Referenced by SLATE_ARGUMENT().
ValueGridOverlay
TSharedPtr<SSampledSequenceValueGridOverlay> SAudioOscilloscopePanelWidget::ValueGridOverlay private
Definition at line 160 of file SAudioOscilloscopePanelWidget.h.
ValueGridOverlayDisplayUnit
EYAxisLabelsUnit SAudioOscilloscopePanelWidget::ValueGridOverlayDisplayUnit private
Definition at line 195 of file SAudioOscilloscopePanelWidget.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/AudioWidgets/Source/AudioWidgets/Public/SAudioOscilloscopePanelWidget.h