Unreal Engine 5.6 C++ API: IPixelStreamingSignallingConnection Class Reference
IPixelStreamingSignallingConnection Class Reference abstract
A specialized signalling server connection object for Pixel Streaming signalling servers.
#include "IPixelStreamingSignallingConnection.h"
Public Member Functions
virtual ~IPixelStreamingSignallingConnection ()
virtual void Disconnect (FString Reason)=0
Disconnects from the signalling server with a reason message.
virtual bool IsConnected () const =0
Checks if the connection is established.
virtual void RequestStreamerList ()=0
Request a list of active streamers from the signalling server.
virtual void SendAnswer (const webrtc::SessionDescriptionInterface &SDP)=0
[Stream receiver only] Sends an answer back to the streamer after receiving an offer.
virtual void SendAnswer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface &SDP)=0
[Streamer only] Sends an answer to the specified player.
virtual void SendDisconnectPlayer (FPixelStreamingPlayerId PlayerId, const FString &Reason)=0
[Streamer only] Send a disconnect message to the specified player.
virtual void SendIceCandidate (const webrtc::IceCandidateInterface &IceCandidate)=0
[Stream receiver only] Sends ICE candidate information to the streamer.
virtual void SendIceCandidate (FPixelStreamingPlayerId PlayerId, const webrtc::IceCandidateInterface &IceCandidate)=0
[Streamer only] Sends ice candidate information to the specified player.
virtual void SendMessage (const FString &Msg)=0
Send a message to the signalling server.
virtual void SendOffer (const webrtc::SessionDescriptionInterface &SDP)=0
[Stream receiver only] Sends an offer to the streamer.
virtual void SendOffer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface &SDP)=0
[Streamer only] Sends an offer to the specified player.
virtual void SendSubscribe (const FString &StreamerId)=0
[Stream receiver only] Send a subscription request to the signalling server.
virtual void SendUnsubscribe ()=0
[Stream receiver only] Send an unsubscribe request to the signalling server.
virtual void SetAutoReconnect (bool bAutoReconnect)=0
Toggles automatic reconnecting when websocket is closed or unreachable.
virtual void SetKeepAlive (bool bKeepAlive)=0
Enables or disables the keep alive pings on this connection.
virtual void TryConnect (FString URL)=0
Connect to a specified signalling server at ths given URL.
UE_DEPRECATED (5.4, "Disconnect has been deprecated and will be removed in future versions. Please use: Disconnect(FString Reason)") virtual void Disconnect()=0
Disconnects from the signalling server.
Detailed Description
A specialized signalling server connection object for Pixel Streaming signalling servers.
Definition at line 14 of file IPixelStreamingSignallingConnection.h.
Constructor & Destructor Documentation
~IPixelStreamingSignallingConnection()
virtual IPixelStreamingSignallingConnection::~IPixelStreamingSignallingConnection () inline virtual
Definition at line 18 of file IPixelStreamingSignallingConnection.h.
Member Function Documentation
Disconnect()
virtual void IPixelStreamingSignallingConnection::Disconnect (FString Reason) pure virtual
Disconnects from the signalling server with a reason message.
Safe to call even when not connected.
Implemented in FPixelStreamingSignallingConnection.
References Disconnect().
Referenced by Disconnect(), and UE_DEPRECATED().
IsConnected()
virtual bool IPixelStreamingSignallingConnection::IsConnected () const pure virtual
Checks if the connection is established.
Returns
True when the signalling server is connected.
Implemented in FPixelStreamingSignallingConnection.
References IsConnected().
Referenced by IsConnected().
RequestStreamerList()
virtual void IPixelStreamingSignallingConnection::RequestStreamerList () pure virtual
Request a list of active streamers from the signalling server.
This is a request to the signalling server so can be used by anyone.
Implemented in FPixelStreamingSignallingConnection.
References RequestStreamerList().
Referenced by RequestStreamerList().
SendAnswer() [1/2]
virtual void IPixelStreamingSignallingConnection::SendAnswer (const webrtc::SessionDescriptionInterface & SDP) pure virtual
[Stream receiver only] Sends an answer back to the streamer after receiving an offer.
Parameters
SDP The local description answer.
Implemented in FPixelStreamingSignallingConnection.
References SendAnswer().
SendAnswer() [2/2]
virtual void IPixelStreamingSignallingConnection::SendAnswer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface & SDP) pure virtual
[Streamer only] Sends an answer to the specified player.
Parameters
PlayerId The Id of the destination player.
SDP The answer session description for the player.
Implemented in FPixelStreamingSignallingConnection.
References SendAnswer().
Referenced by SendAnswer(), and SendAnswer().
SendDisconnectPlayer()
virtual void IPixelStreamingSignallingConnection::SendDisconnectPlayer (FPixelStreamingPlayerId PlayerId, const FString & Reason) pure virtual
[Streamer only] Send a disconnect message to the specified player.
Parameters
PlayerId The Id of the destination player.
Reason An optional reason for the disconnection.
Implemented in FPixelStreamingSignallingConnection.
References SendDisconnectPlayer().
Referenced by SendDisconnectPlayer().
SendIceCandidate() [1/2]
virtual void IPixelStreamingSignallingConnection::SendIceCandidate (const webrtc::IceCandidateInterface & IceCandidate) pure virtual
[Stream receiver only] Sends ICE candidate information to the streamer.
Parameters
IceCandidate The ICE candidate information.
Implemented in FPixelStreamingSignallingConnection.
References SendIceCandidate().
SendIceCandidate() [2/2]
virtual void IPixelStreamingSignallingConnection::SendIceCandidate (FPixelStreamingPlayerId PlayerId, const webrtc::IceCandidateInterface & IceCandidate) pure virtual
[Streamer only] Sends ice candidate information to the specified player.
Parameters
PlayerId The Id of the destination player.
IceCandidate The ice candidate information to send.
Implemented in FPixelStreamingSignallingConnection.
References SendIceCandidate().
Referenced by SendIceCandidate(), and SendIceCandidate().
SendMessage()
virtual void IPixelStreamingSignallingConnection::SendMessage (const FString & Msg) pure virtual
Send a message to the signalling server.
Parameters
Msg A string message to send - typically a JSON payload.
Implemented in FPixelStreamingSignallingConnection.
References SendMessage().
Referenced by SendMessage().
SendOffer() [1/2]
virtual void IPixelStreamingSignallingConnection::SendOffer (const webrtc::SessionDescriptionInterface & SDP) pure virtual
[Stream receiver only] Sends an offer to the streamer.
Parameters
SDP The local description offer.
Implemented in FPixelStreamingSignallingConnection.
References SendOffer().
SendOffer() [2/2]
virtual void IPixelStreamingSignallingConnection::SendOffer (FPixelStreamingPlayerId PlayerId, const webrtc::SessionDescriptionInterface & SDP) pure virtual
[Streamer only] Sends an offer to the specified player.
Parameters
PlayerId The Id of the destination player.
SDP The offer session description for the player.
Implemented in FPixelStreamingSignallingConnection.
References SendOffer().
Referenced by SendOffer(), and SendOffer().
SendSubscribe()
virtual void IPixelStreamingSignallingConnection::SendSubscribe (const FString & StreamerId) pure virtual
[Stream receiver only] Send a subscription request to the signalling server.
Parameters
StreamerId The ID of the streamer to subscribe to.
Implemented in FPixelStreamingSignallingConnection.
References SendSubscribe().
Referenced by SendSubscribe().
SendUnsubscribe()
virtual void IPixelStreamingSignallingConnection::SendUnsubscribe () pure virtual
[Stream receiver only] Send an unsubscribe request to the signalling server.
Implemented in FPixelStreamingSignallingConnection.
References SendUnsubscribe().
Referenced by SendUnsubscribe().
SetAutoReconnect()
virtual void IPixelStreamingSignallingConnection::SetAutoReconnect (bool bAutoReconnect) pure virtual
Toggles automatic reconnecting when websocket is closed or unreachable.
Parameters
bAutoReconnect True to enable auto reconnect. False to disable.
Implemented in FPixelStreamingSignallingConnection.
References SetAutoReconnect().
Referenced by SetAutoReconnect().
SetKeepAlive()
virtual void IPixelStreamingSignallingConnection::SetKeepAlive (bool bKeepAlive) pure virtual
Enables or disables the keep alive pings on this connection.
Receiving connections should disable the keep alive since the reference signalling server will reject pings from players and close the connection.
Parameters
bKeepAlive True to enable keep alive pings. False to disable.
Implemented in FPixelStreamingSignallingConnection.
References SetKeepAlive().
Referenced by SetKeepAlive().
TryConnect()
virtual void IPixelStreamingSignallingConnection::TryConnect (FString URL) pure virtual
Connect to a specified signalling server at ths given URL.
Parameters
URL The url of the destination signalling server.
Implemented in FPixelStreamingSignallingConnection.
UE_DEPRECATED()
IPixelStreamingSignallingConnection::UE_DEPRECATED (5. 4, "Disconnect has been deprecated and will be removed in future versions. Please use: Disconnect(FString Reason)") pure virtual
Disconnects from the signalling server.
Safe to call even when not connected.
Implemented in FPixelStreamingSignallingConnection.
References Disconnect().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming/Source/PixelStreaming/Public/IPixelStreamingSignallingConnection.h