Unreal Engine 5.6 C++ API: SGridPanel::FSlot Class Reference
SGridPanel::FSlot Class Reference
Public Member Functions
FSlot (int32 Column, int32 Row, int32 InLayer)
Default values for a slot.
int32 GetColumn () const
Which column in the grid this cell belongs to.
int32 GetColumnSpan () const
How many columns this slot spans over.
int32 GetLayer () const
Positive values offset this cell to be hit-tested and drawn on top of others.
FVector2D GetNudge () const
Offset this slot's content by some amount; positive values offset to lower right.
int32 GetRow () const
Which row in the grid this cell belongs to.
int32 GetRowSpan () const
How many rows this this slot spans over.
void SetColumn (int32 Column)
void SetColumnSpan (int32 ColumnSpan)
void SetLayer (int32 Layer)
void SetNudge (const FVector2D &Nudge)
void SetRow (int32 Row)
void SetRowSpan (int32 RowSpan)
Column Row Layer SLATE_ARGUMENT (TOptional< FVector2D >, Nudge) SLATE_SLOT_END_ARGS() 1 void Construct(const FChildren &SlotOwner
Offset this slot's content by some amount; positive values offset to lower right.
Column SLATE_ARGUMENT (TOptional< int32 >, ColumnSpan) SLATE_ARGUMENT(TOptional< int32 >
How many columns this slot spans over.
Column Row SLATE_ARGUMENT (TOptional< int32 >, RowSpan) SLATE_ARGUMENT(TOptional< int32 >
How many rows this this slot spans over.
SLATE_SLOT_BEGIN_ARGS (FSlot, TBasicLayoutWidgetSlot< FSlot >) SLATE_ARGUMENT(TOptional< int32 >
Which column in the grid this cell belongs to.
Public Member Functions inherited from TBasicLayoutWidgetSlot< FSlot >
TBasicLayoutWidgetSlot ()
SLATE_SLOT_BEGIN_ARGS_TwoMixins (TBasicLayoutWidgetSlot, TSlotBase< FSlot >, TPaddingWidgetSlotMixin< FSlot >, TAlignmentWidgetSlotMixin< FSlot >) SLATE_SLOT_END_ARGS() void Construct(const FChildren &SlotOwner
TAlignmentWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
TPaddingWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
Public Member Functions inherited from TWidgetSlotWithAttributeSupport< FSlot >
virtual ~TWidgetSlotWithAttributeSupport ()
void Construct (const FChildren &SlotOwner, typename Super::FSlotArguments &&InArgs)
virtual FName GetContainerName () const override
virtual uint32 GetContainerSortOrder () const override
virtual SWidget & GetContainerWidget () const override
void RequestSortAttribute ()
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Public Member Functions inherited from TPaddingWidgetSlotMixin< FSlot >
TPaddingWidgetSlotMixin ()
FMargin GetPadding () const
void SetPadding (TAttribute< FMargin > InPadding)
Public Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
TAlignmentWidgetSlotMixin ()
EHorizontalAlignment GetHorizontalAlignment () const
EVerticalAlignment GetVerticalAlignment () const
void SetHorizontalAlignment (EHorizontalAlignment Alignment)
void SetVerticalAlignment (EVerticalAlignment Alignment)
Data Fields
Column Row Layer FSlotArguments && InArgs
Data Fields inherited from TBasicLayoutWidgetSlot< FSlot >
FSlotArguments && InArgs
Private Member Functions
FORCEINLINE void NotifySlotChanged (bool bSlotLayerChanged=false)
Notify that the slot was changed.
Private Attributes
int32 ColumnParam
int32 ColumnSpanParam
int32 LayerParam
FVector2D NudgeParam
TWeakPtr< SGridPanel > Panel
The panel that contains this slot.
int32 RowParam
int32 RowSpanParam
friend SGridPanel
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Static Public Member Functions inherited from TBasicLayoutWidgetSlot< FSlot >
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Static Public Member Functions inherited from TWidgetSlotWithAttributeSupport< FSlot >
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Protected Member Functions inherited from TPaddingWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Protected Member Functions inherited from TAlignmentWidgetSlotMixin< FSlot >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Static Protected Member Functions inherited from TPaddingWidgetSlotMixin< FSlot >
static void RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Detailed Description
Definition at line 36 of file SGridPanel.h.
Constructor & Destructor Documentation
FSlot()
SGridPanel::FSlot::FSlot (int32 Column, int32 Row, int32 InLayer) inline
Default values for a slot.
Definition at line 42 of file SGridPanel.h.
References FSlot(), TBasicLayoutWidgetSlot< FSlot >::TBasicLayoutWidgetSlot(), ColumnParam, ColumnSpanParam, LayerParam, NudgeParam, RowParam, and RowSpanParam.
Referenced by FSlot(), and SLATE_SLOT_BEGIN_ARGS().
Member Function Documentation
GetColumn()
int32 SGridPanel::FSlot::GetColumn () const inline
Which column in the grid this cell belongs to.
Definition at line 72 of file SGridPanel.h.
References ColumnParam, and GetColumn().
Referenced by GetColumn().
GetColumnSpan()
int32 SGridPanel::FSlot::GetColumnSpan () const inline
How many columns this slot spans over.
Definition at line 88 of file SGridPanel.h.
References ColumnSpanParam.
GetLayer()
int32 SGridPanel::FSlot::GetLayer () const inline
Positive values offset this cell to be hit-tested and drawn on top of others.
Default is 0; i.e. no offset.
Definition at line 138 of file SGridPanel.h.
References LayerParam.
GetNudge()
FVector2D SGridPanel::FSlot::GetNudge () const inline
Offset this slot's content by some amount; positive values offset to lower right.
Definition at line 154 of file SGridPanel.h.
References NudgeParam.
GetRow()
int32 SGridPanel::FSlot::GetRow () const inline
Which row in the grid this cell belongs to.
Definition at line 105 of file SGridPanel.h.
References RowParam.
GetRowSpan()
int32 SGridPanel::FSlot::GetRowSpan () const inline
How many rows this this slot spans over.
Definition at line 121 of file SGridPanel.h.
References RowSpanParam.
NotifySlotChanged()
FORCEINLINE void SGridPanel::FSlot::NotifySlotChanged (bool bSlotLayerChanged = false) inline private
Notify that the slot was changed.
Definition at line 177 of file SGridPanel.h.
References FORCEINLINE, and Panel.
Referenced by SetColumn(), SetColumnSpan(), SetLayer(), SetRow(), and SetRowSpan().
SetColumn()
void SGridPanel::FSlot::SetColumn (int32 Column) inline
Definition at line 77 of file SGridPanel.h.
References ColumnParam, FMath::Max, and NotifySlotChanged().
SetColumnSpan()
void SGridPanel::FSlot::SetColumnSpan (int32 ColumnSpan) inline
Definition at line 93 of file SGridPanel.h.
References FMath::Clamp(), ColumnSpanParam, and NotifySlotChanged().
SetLayer()
void SGridPanel::FSlot::SetLayer (int32 Layer) inline
Definition at line 143 of file SGridPanel.h.
References LayerParam, and NotifySlotChanged().
SetNudge()
void SGridPanel::FSlot::SetNudge (const FVector2D & Nudge) inline
Definition at line 159 of file SGridPanel.h.
References FSlotBase::Invalidate(), NudgeParam, and Paint.
SetRow()
void SGridPanel::FSlot::SetRow (int32 Row) inline
Definition at line 110 of file SGridPanel.h.
References FMath::Max, NotifySlotChanged(), and RowParam.
SetRowSpan()
void SGridPanel::FSlot::SetRowSpan (int32 RowSpan) inline
Definition at line 126 of file SGridPanel.h.
References FMath::Clamp(), NotifySlotChanged(), and RowSpanParam.
SLATE_ARGUMENT() [1/3]
Column Row Layer SGridPanel::FSlot::SLATE_ARGUMENT (TOptional< FVector2D > , Nudge) const &
Offset this slot's content by some amount; positive values offset to lower right.
References SLATE_ARGUMENT(), and SLATE_SLOT_END_ARGS.
SLATE_ARGUMENT() [2/3]
Column SGridPanel::FSlot::SLATE_ARGUMENT (TOptional< int32 > , ColumnSpan)
How many columns this slot spans over.
Which row in the grid this cell belongs to
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/3]
Column Row SGridPanel::FSlot::SLATE_ARGUMENT (TOptional< int32 > , RowSpan)
How many rows this this slot spans over.
Positive values offset this cell to be hit-tested and drawn on top of others. Default is 0; i.e. no offset.
References SLATE_ARGUMENT().
SLATE_SLOT_BEGIN_ARGS()
SGridPanel::FSlot::SLATE_SLOT_BEGIN_ARGS (FSlot , TBasicLayoutWidgetSlot< FSlot >)
Which column in the grid this cell belongs to.
References FSlot(), and TBasicLayoutWidgetSlot< FSlot >::TBasicLayoutWidgetSlot().
Field Documentation
ColumnParam
int32 SGridPanel::FSlot::ColumnParam private
Definition at line 169 of file SGridPanel.h.
Referenced by FSlot(), GetColumn(), and SetColumn().
ColumnSpanParam
int32 SGridPanel::FSlot::ColumnSpanParam private
Definition at line 170 of file SGridPanel.h.
Referenced by FSlot(), GetColumnSpan(), and SetColumnSpan().
InArgs
Column Row Layer FSlotArguments&& SGridPanel::FSlot::InArgs
Definition at line 68 of file SGridPanel.h.
LayerParam
int32 SGridPanel::FSlot::LayerParam private
Definition at line 173 of file SGridPanel.h.
Referenced by FSlot(), GetLayer(), and SetLayer().
NudgeParam
FVector2D SGridPanel::FSlot::NudgeParam private
Definition at line 174 of file SGridPanel.h.
Referenced by FSlot(), GetNudge(), and SetNudge().
Panel
TWeakPtr<SGridPanel> SGridPanel::FSlot::Panel private
The panel that contains this slot.
Definition at line 167 of file SGridPanel.h.
Referenced by NotifySlotChanged().
RowParam
int32 SGridPanel::FSlot::RowParam private
Definition at line 171 of file SGridPanel.h.
Referenced by FSlot(), GetRow(), and SetRow().
RowSpanParam
int32 SGridPanel::FSlot::RowSpanParam private
Definition at line 172 of file SGridPanel.h.
Referenced by FSlot(), GetRowSpan(), and SetRowSpan().
SGridPanel
friend SGridPanel::FSlot::SGridPanel private
Definition at line 38 of file SGridPanel.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Layout/SGridPanel.h