Unreal Engine 5.6 C++ API: FScopedNamedEventConditionalStatic Class Reference
FScopedNamedEventConditionalStatic Class Reference
#include "PlatformMisc.h"
Public Member Functions
FScopedNamedEventConditionalStatic (const struct FColor &Color, const ANSICHAR *Text, bool bCondition)
FScopedNamedEventConditionalStatic (const struct FColor &Color, const TCHAR *Text, bool bCondition)
~FScopedNamedEventConditionalStatic ()
Private Attributes
bool bStarted
Detailed Description
Definition at line 133 of file PlatformMisc.h.
Constructor & Destructor Documentation
FScopedNamedEventConditionalStatic() [1/2]
FScopedNamedEventConditionalStatic::FScopedNamedEventConditionalStatic (const struct FColor & Color, const TCHAR * Text, bool bCondition) inline
Definition at line 137 of file PlatformMisc.h.
References FGenericPlatformMisc::BeginNamedEvent(), bStarted, Color, and Text.
FScopedNamedEventConditionalStatic() [2/2]
FScopedNamedEventConditionalStatic::FScopedNamedEventConditionalStatic (const struct FColor & Color, const ANSICHAR * Text, bool bCondition) inline
Definition at line 150 of file PlatformMisc.h.
References FGenericPlatformMisc::BeginNamedEvent(), bStarted, Color, and Text.
~FScopedNamedEventConditionalStatic()
FScopedNamedEventConditionalStatic::~FScopedNamedEventConditionalStatic () inline
Definition at line 163 of file PlatformMisc.h.
References bStarted, and FGenericPlatformMisc::EndNamedEvent().
Field Documentation
bStarted
bool FScopedNamedEventConditionalStatic::bStarted private
Definition at line 172 of file PlatformMisc.h.
Referenced by FScopedNamedEventConditionalStatic(), FScopedNamedEventConditionalStatic(), and ~FScopedNamedEventConditionalStatic().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/PlatformMisc.h