Unreal Engine 5.6 C++ API: FSkinWeightLookupVertexBuffer Class Reference
FSkinWeightLookupVertexBuffer Class Reference
A lookup vertex buffer storing skin weight stream offset / influence count.
#include "SkinWeightVertexBuffer.h"
Public Member Functions
FSkinWeightLookupVertexBuffer ()
Default constructor.
FSkinWeightLookupVertexBuffer (const FSkinWeightLookupVertexBuffer &Other)
Constructor (copy)
~FSkinWeightLookupVertexBuffer ()
Destructor.
void CleanUp ()
Delete existing resources.
void CopyMetaData (const FSkinWeightLookupVertexBuffer &Other)
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI vertex buffer with CPU data.
virtual FString GetFriendlyName () const override
uint8 * GetLookupData ()
const uint8 * GetLookupData () const
bool GetNeedsCPUAccess () const
FORCEINLINE uint32 GetNumVertices () const
FRHIShaderResourceView * GetSRV () const
FORCEINLINE uint32 GetStride () const
FORCEINLINE uint32 GetVertexDataSize () const
void GetWeightOffsetAndInfluenceCount (uint32 VertexIndex, uint32 &OutWeightOffset, uint32 &OutInfluenceCount) const
void Init (uint32 InNumVertices)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
bool IsLookupDataValid () const
FSkinWeightLookupVertexBuffer & operator= (const FSkinWeightLookupVertexBuffer &Other)
Assignment.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void SerializeMetaData (FArchive &Ar)
void SetMetaData (uint32 InNumVertices)
void SetNeedsCPUAccess (bool bInNeedsCPUAccess)
Set if the CPU needs access to this vertex buffer.
void SetWeightOffsetAndInfluenceCount (uint32 VertexIndex, uint32 WeightOffset, uint32 InfluenceCount)
Public Member Functions inherited from FVertexBuffer
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Protected Attributes
FShaderResourceViewRHIRef SRVValue
Private Member Functions
void AllocateData ()
Allocates the vertex data storage type.
void ResizeBuffer (uint32 InNumVertices)
Private Attributes
bool bNeedsCPUAccess
true if this vertex buffer will be used with CPU skinning.
uint8 * Data
The cached vertex data pointer.
FStaticMeshVertexDataInterface * LookupData
The vertex data storage type.
uint32 NumVertices
The cached number of vertices.
Static Private Attributes
static const EPixelFormat PixelFormat = PF_R32_UINT
static const uint32 PixelFormatStride = 4
Friends
FArchive & operator<< (FArchive &Ar, FSkinWeightLookupVertexBuffer &VertexBuffer)
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FVertexBuffer
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A lookup vertex buffer storing skin weight stream offset / influence count.
Only used for unlimited bone influences.
Definition at line 72 of file SkinWeightVertexBuffer.h.
Constructor & Destructor Documentation
FSkinWeightLookupVertexBuffer() [1/2]
FSkinWeightLookupVertexBuffer::FSkinWeightLookupVertexBuffer ()
Default constructor.
Referenced by FSkinWeightLookupVertexBuffer(), CopyMetaData(), operator<<, and operator=().
FSkinWeightLookupVertexBuffer() [2/2]
FSkinWeightLookupVertexBuffer::FSkinWeightLookupVertexBuffer (const FSkinWeightLookupVertexBuffer & Other)
Constructor (copy)
References FSkinWeightLookupVertexBuffer(), and Other.
~FSkinWeightLookupVertexBuffer()
FSkinWeightLookupVertexBuffer::~FSkinWeightLookupVertexBuffer ()
Destructor.
Member Function Documentation
AllocateData()
void FSkinWeightLookupVertexBuffer::AllocateData () private
Allocates the vertex data storage type.
CleanUp()
void FSkinWeightLookupVertexBuffer::CleanUp ()
Delete existing resources.
CopyMetaData()
void FSkinWeightLookupVertexBuffer::CopyMetaData (const FSkinWeightLookupVertexBuffer & Other)
References FSkinWeightLookupVertexBuffer(), and Other.
CreateRHIBuffer()
FBufferRHIRef FSkinWeightLookupVertexBuffer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Create an RHI vertex buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
GetFriendlyName()
virtual FString FSkinWeightLookupVertexBuffer::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FVertexBuffer.
Definition at line 115 of file SkinWeightVertexBuffer.h.
References TEXT.
GetLookupData() [1/2]
uint8 * FSkinWeightLookupVertexBuffer::GetLookupData () inline
Definition at line 98 of file SkinWeightVertexBuffer.h.
References Data.
GetLookupData() [2/2]
const uint8 * FSkinWeightLookupVertexBuffer::GetLookupData () const inline
Definition at line 93 of file SkinWeightVertexBuffer.h.
References Data.
GetNeedsCPUAccess()
bool FSkinWeightLookupVertexBuffer::GetNeedsCPUAccess () const inline
Definition at line 138 of file SkinWeightVertexBuffer.h.
References bNeedsCPUAccess.
GetNumVertices()
FORCEINLINE uint32 FSkinWeightLookupVertexBuffer::GetNumVertices () const inline
Returns
number of vertices in this vertex buffer
Definition at line 119 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, and NumVertices.
GetSRV()
FRHIShaderResourceView * FSkinWeightLookupVertexBuffer::GetSRV () const inline
Definition at line 131 of file SkinWeightVertexBuffer.h.
References SRVValue.
GetStride()
FORCEINLINE uint32 FSkinWeightLookupVertexBuffer::GetStride () const inline
Returns
cached stride for vertex data type for this vertex buffer
Definition at line 123 of file SkinWeightVertexBuffer.h.
References FORCEINLINE.
Referenced by GetVertexDataSize().
GetVertexDataSize()
FORCEINLINE uint32 FSkinWeightLookupVertexBuffer::GetVertexDataSize () const inline
Returns
total size of data in resource array
Definition at line 127 of file SkinWeightVertexBuffer.h.
References FORCEINLINE, GetStride(), and NumVertices.
GetWeightOffsetAndInfluenceCount()
void FSkinWeightLookupVertexBuffer::GetWeightOffsetAndInfluenceCount (uint32 VertexIndex, uint32 & OutWeightOffset, uint32 & OutInfluenceCount) const
Init()
void FSkinWeightLookupVertexBuffer::Init (uint32 InNumVertices)
InitRHI()
virtual void FSkinWeightLookupVertexBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FSkinWeightLookupVertexBuffer::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
References IntermediateBuffer.
IsLookupDataValid()
bool FSkinWeightLookupVertexBuffer::IsLookupDataValid () const
Returns
true is LookupData is valid
operator=()
FSkinWeightLookupVertexBuffer & FSkinWeightLookupVertexBuffer::operator= (const FSkinWeightLookupVertexBuffer & Other)
Assignment.
Assumes that vertex buffer will be rebuilt
References FSkinWeightLookupVertexBuffer(), and Other.
ReleaseRHI()
virtual void FSkinWeightLookupVertexBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FVertexBuffer.
ReleaseRHIForStreaming()
void FSkinWeightLookupVertexBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
ResizeBuffer()
void FSkinWeightLookupVertexBuffer::ResizeBuffer (uint32 InNumVertices) private
SerializeMetaData()
void FSkinWeightLookupVertexBuffer::SerializeMetaData (FArchive & Ar)
References Ar.
SetMetaData()
void FSkinWeightLookupVertexBuffer::SetMetaData (uint32 InNumVertices)
SetNeedsCPUAccess()
void FSkinWeightLookupVertexBuffer::SetNeedsCPUAccess (bool bInNeedsCPUAccess) inline
Set if the CPU needs access to this vertex buffer.
Definition at line 135 of file SkinWeightVertexBuffer.h.
References bNeedsCPUAccess.
SetWeightOffsetAndInfluenceCount()
void FSkinWeightLookupVertexBuffer::SetWeightOffsetAndInfluenceCount (uint32 VertexIndex, uint32 WeightOffset, uint32 InfluenceCount)
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FSkinWeightLookupVertexBuffer & VertexBuffer) friend
References FSkinWeightLookupVertexBuffer(), Ar, and VertexBuffer.
Field Documentation
bNeedsCPUAccess
bool FSkinWeightLookupVertexBuffer::bNeedsCPUAccess private
true if this vertex buffer will be used with CPU skinning.
Resource arrays are set to cpu accessible if this is true
Definition at line 162 of file SkinWeightVertexBuffer.h.
Referenced by GetNeedsCPUAccess(), and SetNeedsCPUAccess().
Data
uint8* FSkinWeightLookupVertexBuffer::Data private
The cached vertex data pointer.
Definition at line 168 of file SkinWeightVertexBuffer.h.
Referenced by GetLookupData(), and GetLookupData().
LookupData
FStaticMeshVertexDataInterface* FSkinWeightLookupVertexBuffer::LookupData private
The vertex data storage type.
Definition at line 165 of file SkinWeightVertexBuffer.h.
NumVertices
uint32 FSkinWeightLookupVertexBuffer::NumVertices private
The cached number of vertices.
Definition at line 171 of file SkinWeightVertexBuffer.h.
Referenced by GetNumVertices(), and GetVertexDataSize().
PixelFormat
const EPixelFormat FSkinWeightLookupVertexBuffer::PixelFormat = PF_R32_UINT static private
Definition at line 173 of file SkinWeightVertexBuffer.h.
PixelFormatStride
const uint32 FSkinWeightLookupVertexBuffer::PixelFormatStride = 4 static private
Definition at line 174 of file SkinWeightVertexBuffer.h.
SRVValue
FShaderResourceViewRHIRef FSkinWeightLookupVertexBuffer::SRVValue protected
Definition at line 153 of file SkinWeightVertexBuffer.h.
Referenced by GetSRV().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/SkinWeightVertexBuffer.h