Unreal Engine 5.6 C++ API: UE::Insights::STableTreeRowToolTip Class Reference
UE::Insights::STableTreeRowToolTip Class Reference
#include "STableTreeViewTooltip.h"
Public Member Functions
STableTreeRowToolTip (const TSharedPtr< FTableTreeNode > InTreeNodePtr)
virtual ~STableTreeRowToolTip ()
virtual TSharedRef< class SWidget > AsWidget ()
Gets the widget that this tool tip represents.
virtual TSharedRef< SWidget > GetContentWidget ()
Gets the tool tip's content widget.
void InvalidateWidget ()
virtual bool IsEmpty () const
Checks whether this tool tip has no content to display right now.
virtual bool IsInteractive () const
Checks whether this tool tip can be made interactive by the user (by holding Ctrl).
virtual void OnClosed ()
Called when the tooltip widget is closed and the tooltip is no longer needed.
virtual void OnOpening ()
Called when the tooltip widget is about to be requested for opening.
virtual void SetContentWidget (const TSharedRef< SWidget > &InContentWidget)
Sets the tool tip's content widget.
Public Member Functions inherited from IToolTip
virtual ~IToolTip ()
Virtual destructor.
virtual void OnSetInteractiveWindowLocation (FVector2D &InOutDesiredLocation) const
Allows an interactive tooltip to adjust and/or change its window location on open, as interactive tooltips don't update the tooltip window to follow the cursor position.
virtual void ResetContentWidget ()
Resets the tooltip to its default without a content widget.
Private Member Functions
void CreateToolTipWidget ()
Private Attributes
TSharedPtr< SToolTip > ToolTipWidget
const TSharedPtr< FTableTreeNode > TreeNodePtr
Detailed Description
Definition at line 37 of file STableTreeViewTooltip.h.
Constructor & Destructor Documentation
STableTreeRowToolTip()
UE::Insights::STableTreeRowToolTip::STableTreeRowToolTip (const TSharedPtr< FTableTreeNode > InTreeNodePtr) inline
Definition at line 40 of file STableTreeViewTooltip.h.
References TreeNodePtr.
~STableTreeRowToolTip()
virtual UE::Insights::STableTreeRowToolTip::~STableTreeRowToolTip () inline virtual
Definition at line 41 of file STableTreeViewTooltip.h.
Member Function Documentation
AsWidget()
virtual TSharedRef< class SWidget > UE::Insights::STableTreeRowToolTip::AsWidget () inline virtual
Gets the widget that this tool tip represents.
Returns
The tool tip widget.
Implements IToolTip.
Definition at line 43 of file STableTreeViewTooltip.h.
References CreateToolTipWidget(), and ToolTipWidget.
CreateToolTipWidget()
void UE::Insights::STableTreeRowToolTip::CreateToolTipWidget () inline private
Definition at line 72 of file STableTreeViewTooltip.h.
References UE::Insights::STableTreeViewTooltip::GetRowTooltip(), ToolTipWidget, and TreeNodePtr.
Referenced by AsWidget(), GetContentWidget(), and SetContentWidget().
GetContentWidget()
virtual TSharedRef< SWidget > UE::Insights::STableTreeRowToolTip::GetContentWidget () inline virtual
Gets the tool tip's content widget.
Returns
The content widget.
Implements IToolTip.
Definition at line 49 of file STableTreeViewTooltip.h.
References CreateToolTipWidget(), and ToolTipWidget.
InvalidateWidget()
void UE::Insights::STableTreeRowToolTip::InvalidateWidget () inline
Definition at line 61 of file STableTreeViewTooltip.h.
References ToolTipWidget.
IsEmpty()
virtual bool UE::Insights::STableTreeRowToolTip::IsEmpty () const inline virtual
Checks whether this tool tip has no content to display right now.
Returns
true if the tool tip has no content to display, false otherwise.
Implements IToolTip.
Definition at line 66 of file STableTreeViewTooltip.h.
IsInteractive()
virtual bool UE::Insights::STableTreeRowToolTip::IsInteractive () const inline virtual
Checks whether this tool tip can be made interactive by the user (by holding Ctrl).
Returns
true if it is an interactive tool tip, false otherwise.
Implements IToolTip.
Definition at line 67 of file STableTreeViewTooltip.h.
OnClosed()
virtual void UE::Insights::STableTreeRowToolTip::OnClosed () inline virtual
Called when the tooltip widget is closed and the tooltip is no longer needed.
Implements IToolTip.
Definition at line 69 of file STableTreeViewTooltip.h.
OnOpening()
virtual void UE::Insights::STableTreeRowToolTip::OnOpening () inline virtual
Called when the tooltip widget is about to be requested for opening.
Implements IToolTip.
Definition at line 68 of file STableTreeViewTooltip.h.
SetContentWidget()
virtual void UE::Insights::STableTreeRowToolTip::SetContentWidget (const TSharedRef< SWidget > & InContentWidget) inline virtual
Sets the tool tip's content widget.
Parameters
InContentWidget The new content widget to set.
Implements IToolTip.
Definition at line 55 of file STableTreeViewTooltip.h.
References CreateToolTipWidget(), and ToolTipWidget.
Field Documentation
ToolTipWidget
TSharedPtr<SToolTip> UE::Insights::STableTreeRowToolTip::ToolTipWidget private
Definition at line 81 of file STableTreeViewTooltip.h.
Referenced by AsWidget(), CreateToolTipWidget(), GetContentWidget(), InvalidateWidget(), and SetContentWidget().
TreeNodePtr
const TSharedPtr<FTableTreeNode> UE::Insights::STableTreeRowToolTip::TreeNodePtr private
Definition at line 82 of file STableTreeViewTooltip.h.
Referenced by STableTreeRowToolTip(), and CreateToolTipWidget().
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Table/Widgets/STableTreeViewTooltip.h