Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVerticesOctree3< SourceType > Class Template Reference
UE::Geometry::TDynamicVerticesOctree3< SourceType > Class Template Reference
TDynamicVerticesOctree3 is an extension of FSparseDynamicPointOctree3 for the vertices of a FDynamicXYZ3 instance (eg FDynamicMesh3, TDynamicPointSet3, FDynamicGraph, etc) This extension does several things: 1) provides a simplified API based on vertex IDs to various Octree functions 2) tracks ModifiedBounds box of modified areas.
#include "DynamicVerticesOctree3.h"
Public Member Functions
void CheckValidity (EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check, bool bVerbose=false, bool bFailOnMissingPoints=false) const
Check that the Octree is internally valid.
int32 FindNearestHitVertex (const FRay3d &Ray, double MaxDistance=TNumericLimits< double >::Max()) const
Find the nearest triangle of the VertexSource that is hit by the ray.
void Initialize (const SourceType *VertexSourceIn, bool bDynamicExpand)
Add all vertices of MeshIn to the octree.
void InsertVertex (int32 VertexID)
Insert a triangle into the tree.
void InsertVertices (const TArray< int > &Vertices)
Insert a list of vertices into the tree.
void InsertVertices (const TSet< int > &Vertices)
Insert a set of vertices into the tree.
void NotifyPendingModification (const TSet< int > &Vertices)
Include the current bounds of a set of vertices in the ModifiedBounds box.
void NotifyPendingModification (int VertexID)
Include the current bounds of a triangle in the ModifiedBounds box.
void ReinsertVertices (const TSet< int > &Vertices)
Reinsert a set of vertices into the tree.
bool RemovePoint (int32 VertexID)
Remove a triangle from the tree.
void RemoveVertices (const TArray< int > &Vertices)
Remove a list of vertices from the tree.
void RemoveVertices (const TSet< int > &Vertices)
Remove a set of vertices from the tree.
void ResetModifiedBounds ()
Reset the internal ModifiedBounds box that tracks modified triangle bounds.
Public Member Functions inherited from UE::Geometry::FSparseDynamicPointOctree3
void CheckValidity (TFunctionRef< bool(int)> IsValidPointIDFunc, TFunctionRef< FVector3d(int)> GetPointFunc, EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check, bool bVerbose=false, bool bFailOnMissingPoints=false) const
Check that the octree is internally valid.
void ComputeStatistics (FStatistics &StatsOut) const
Populate given FStatistics with info about the octree.
void ConfigureFromPointCountEstimate (double MaxBoundsDimension, int CountEstimate)
Do a rough ballpark configuration of the RootDimension, MaxTreeDepth, and MaxPointsPerCell tree config values, given a bounding-box dimension and estimate of the total number of points that will be inserted.
bool ContainsPoint (int32 PointID) const
Test if an Point is stored in the tree.
GEOMETRYCORE_API int32 FindClosestPoint (FVector3d QueryPt, double DistanceThreshold, TFunctionRef< bool(int32)> PredicateFunc, TFunctionRef< double(int32)> DistSqFunc, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Find closest point in the tree, relative to a query point, within a search distance.
void FindKClosestPoints (FVector3d QueryPt, double DistanceThreshold, int32 NumToFind, TArray< TPair< int32, double > > &FoundPoints, TFunctionRef< bool(int32)> PredicateFunc, TFunctionRef< double(int32)> DistSqFunc, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Find the K closest point in the tree, relative to a query point, within a search distance.
int32 FindNearestHitPoint (const FRay3d &Ray, TFunctionRef< double(int, const FRay3d &)> HitPointDistFunc, double MaxDistance=TNumericLimits< double >::Max()) const
Find nearest ray-hit point with Points in tree.
void InsertPoint (int32 PointID, const FVector3d &Position)
Insert PointID into the Octree at maximum depth.
void InsertPoint_DynamicExpand (int32 PointID, TFunctionRef< FVector3d(int)> GetPositionFunc)
Insert PointID into the Octree.
void ParallelInsertDensePointSet (int32 MaxPointID, TFunctionRef< FVector3d(int)> GetPositionFunc)
Insert a set of dense points with IDs in range [0, MaxPointID-1], in parallel.
void ParallelRangeQuery (const FAxisAlignedBox3d &Bounds, TFunctionRef< bool(int)> PredicateFunc, TArray< int > &PointIDsOut, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Collect PointIDs from all the cells with bounding boxes that intersect Bounds, where PredicateFunc passes Query is parallelized across Root cells.
void RangeQuery (const FAxisAlignedBox3d &Bounds, TFunctionRef< bool(int)> PredicateFunc, TArray< int > &PointIDsOut, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Collect PointIDs from all the cells with bounding boxes that intersect Bounds, where PredicateFunc passes.
void ReinsertPoint (int32 PointID, const FVector3d &NewPosition)
Update the position of an Point in the octree.
bool RemovePoint (int32 PointID)
Remove a Point from the octree.
void RemovePointUnsafe (int32 PointID)
Remove a Point from the octree.
Data Fields
double HitSphereRadius = 1.0f
FAxisAlignedBox3d ModifiedBounds
bounding box of vertices that have been inserted/removed since last clear
const SourceType * VertexSource
parent mesh
Data Fields inherited from UE::Geometry::FSparseDynamicPointOctree3
int MaxPointsPerCell = 1000
if using the InsertPoint_DynamicExpand() insertion path, then when a cell gets to this many points, and has depth < MaxTreeDepth, it will be expanded and its points moved down
int MaxTreeDepth = 10
Points will not be inserted more than this many levels deep from a Root cell.
double RootDimension = 1000.0
Size of the Root cells of the octree.
Additional Inherited Members
Protected Member Functions inherited from UE::Geometry::FSparseDynamicPointOctree3
bool CellContains (const FSparsePointOctreeCell &Cell, const FVector3d &Position) const
uint32 CreateNewRootCell (FSparsePointOctreeCell NewRootCell, bool bInitializeCellPointList)
FSparsePointOctreeCell FindCurrentContainingCell (const FVector3d &Position) const
double FindNearestRayCellIntersection (const FSparsePointOctreeCell &Cell, const FRay3d &Ray) const
FAxisAlignedBox3d GetCellBox (const FSparsePointOctreeCell &Cell) const
FAxisAlignedBox3d GetCellBox (uint32 Level, const FVector3i &Index) const
FVector3d GetCellCenter (const FSparsePointOctreeCell &Cell) const
FVector3d GetCellCenter (uint32 Level, const FVector3i &Index) const
uint32 GetCellForPoint (int32 PointID) const
double GetCellWidth (uint32 Level) const
void Insert_NewChildCell (int32 PointID, const FVector3d &Position, int ParentCellID, FSparsePointOctreeCell NewChildCell, int ChildIdx)
void Insert_NewRoot (int32 PointID, const FVector3d &Position, FSparsePointOctreeCell NewRootCell)
void Insert_ToCell (int32 PointID, const FVector3d &Position, const FSparsePointOctreeCell &ExistingCell)
FVector3i PointToIndex (uint32 Level, const FVector3d &Position) const
int ToChildCellIndex (const FSparsePointOctreeCell &Cell, const FVector3d &Position) const
int ToChildCellIndex (uint32 Level, const FVector3i &Index, const FVector3d &Position) const
Protected Attributes inherited from UE::Geometry::FSparseDynamicPointOctree3
TSparseListSet< int32 > CellPointLists
FRefCountVector CellRefCounts
TDynamicVector< FSparsePointOctreeCell > Cells
TDynamicVector< uint32 > PointIDToCellMap
TSparseGrid3< uint32 > RootCells
Static Protected Attributes inherited from UE::Geometry::FSparseDynamicPointOctree3
static constexpr uint32 InvalidCellID = FSparsePointOctreeCell::InvalidID
Detailed Description
template<typename SourceType>
class UE::Geometry::TDynamicVerticesOctree3< SourceType >
TDynamicVerticesOctree3 is an extension of FSparseDynamicPointOctree3 for the vertices of a FDynamicXYZ3 instance (eg FDynamicMesh3, TDynamicPointSet3, FDynamicGraph, etc) This extension does several things: 1) provides a simplified API based on vertex IDs to various Octree functions 2) tracks ModifiedBounds box of modified areas.
The template expansion requires that FDynamicXYZ3 has the following API: 1) a function int MaxVertexID() that returns the maximum vertex ID/index 2) a function bool IsVertex(int) that returns true if the index is valid 3) a function FVector3d GetVertex(int index) that returns the position of a vertex 4) a function FAxisAlignedBox3d GetBounds() that returns a bounding-box of the point set
Definition at line 30 of file DynamicVerticesOctree3.h.
Member Function Documentation
CheckValidity()
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::CheckValidity (EValidityCheckFailMode FailMode = EValidityCheckFailMode::Check, bool bVerbose = false, bool bFailOnMissingPoints = false) const inline
Check that the Octree is internally valid.
Definition at line 214 of file DynamicVerticesOctree3.h.
References UE::Geometry::Check, UE::Geometry::FSparseDynamicPointOctree3::CheckValidity(), and VertexSource.
FindNearestHitVertex()
template<typename SourceType> int32 UE::Geometry::TDynamicVerticesOctree3< SourceType >::FindNearestHitVertex (const FRay3d & Ray, double MaxDistance = TNumericLimits<double>::Max()) const inline
Find the nearest triangle of the VertexSource that is hit by the ray.
Definition at line 199 of file DynamicVerticesOctree3.h.
References UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint(), HitSphereRadius, UE::Geometry::FLinearIntersection::intersects, UE::Geometry::TInterval1< RealType >::Min, UE::Geometry::FLinearIntersection::parameter, Point, Ray, IntersectionUtil::RaySphereIntersection(), and VertexSource.
Initialize()
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::Initialize (const SourceType * VertexSourceIn, bool bDynamicExpand) inline
Add all vertices of MeshIn to the octree.
Definition at line 49 of file DynamicVerticesOctree3.h.
References HitSphereRadius, UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand(), InsertVertex(), ModifiedBounds, and VertexSource.
InsertVertex()
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::InsertVertex (int32 VertexID) inline
Insert a triangle into the tree.
Definition at line 87 of file DynamicVerticesOctree3.h.
References UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), ModifiedBounds, Point, and VertexSource.
Referenced by Initialize().
InsertVertices() [1/2]
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::InsertVertices (const TArray< int > & Vertices) inline
Insert a list of vertices into the tree.
Definition at line 97 of file DynamicVerticesOctree3.h.
References UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), ModifiedBounds, Point, VertexSource, and UE::Geometry::Vertices.
InsertVertices() [2/2]
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::InsertVertices (const TSet< int > & Vertices) inline
Insert a set of vertices into the tree.
Definition at line 111 of file DynamicVerticesOctree3.h.
References UE::Geometry::FSparseDynamicPointOctree3::InsertPoint(), ModifiedBounds, Point, VertexSource, and UE::Geometry::Vertices.
NotifyPendingModification() [1/2]
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::NotifyPendingModification (const TSet< int > & Vertices) inline
Include the current bounds of a set of vertices in the ModifiedBounds box.
Definition at line 186 of file DynamicVerticesOctree3.h.
References ModifiedBounds, Point, VertexSource, and UE::Geometry::Vertices.
NotifyPendingModification() [2/2]
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::NotifyPendingModification (int VertexID) inline
Include the current bounds of a triangle in the ModifiedBounds box.
Definition at line 177 of file DynamicVerticesOctree3.h.
References ModifiedBounds, Point, and VertexSource.
ReinsertVertices()
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::ReinsertVertices (const TSet< int > & Vertices) inline
Reinsert a set of vertices into the tree.
Definition at line 163 of file DynamicVerticesOctree3.h.
References ModifiedBounds, Point, UE::Geometry::FSparseDynamicPointOctree3::ReinsertPoint(), VertexSource, and UE::Geometry::Vertices.
RemovePoint()
template<typename SourceType> bool UE::Geometry::TDynamicVerticesOctree3< SourceType >::RemovePoint (int32 VertexID) inline
Remove a triangle from the tree.
Definition at line 125 of file DynamicVerticesOctree3.h.
References ModifiedBounds, Point, UE::Geometry::FSparseDynamicPointOctree3::RemovePoint(), and VertexSource.
RemoveVertices() [1/2]
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::RemoveVertices (const TArray< int > & Vertices) inline
Remove a list of vertices from the tree.
Definition at line 135 of file DynamicVerticesOctree3.h.
References ModifiedBounds, Point, UE::Geometry::FSparseDynamicPointOctree3::RemovePoint(), VertexSource, and UE::Geometry::Vertices.
RemoveVertices() [2/2]
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::RemoveVertices (const TSet< int > & Vertices) inline
Remove a set of vertices from the tree.
Definition at line 149 of file DynamicVerticesOctree3.h.
References ModifiedBounds, Point, UE::Geometry::FSparseDynamicPointOctree3::RemovePoint(), VertexSource, and UE::Geometry::Vertices.
ResetModifiedBounds()
template<typename SourceType> void UE::Geometry::TDynamicVerticesOctree3< SourceType >::ResetModifiedBounds () inline
Reset the internal ModifiedBounds box that tracks modified triangle bounds.
Definition at line 79 of file DynamicVerticesOctree3.h.
References UE::Geometry::TAxisAlignedBox3< double >::Empty(), and ModifiedBounds.
Field Documentation
HitSphereRadius
template<typename SourceType> double UE::Geometry::TDynamicVerticesOctree3< SourceType >::HitSphereRadius = 1.0f
Definition at line 44 of file DynamicVerticesOctree3.h.
Referenced by FindNearestHitVertex(), and Initialize().
ModifiedBounds
template<typename SourceType> FAxisAlignedBox3d UE::Geometry::TDynamicVerticesOctree3< SourceType >::ModifiedBounds
bounding box of vertices that have been inserted/removed since last clear
Definition at line 42 of file DynamicVerticesOctree3.h.
Referenced by Initialize(), InsertVertex(), InsertVertices(), InsertVertices(), NotifyPendingModification(), NotifyPendingModification(), ReinsertVertices(), RemovePoint(), RemoveVertices(), RemoveVertices(), and ResetModifiedBounds().
VertexSource
template<typename SourceType> const SourceType* UE::Geometry::TDynamicVerticesOctree3< SourceType >::VertexSource
parent mesh
Definition at line 39 of file DynamicVerticesOctree3.h.
Referenced by CheckValidity(), FindNearestHitVertex(), Initialize(), InsertVertex(), InsertVertices(), InsertVertices(), NotifyPendingModification(), NotifyPendingModification(), ReinsertVertices(), RemovePoint(), RemoveVertices(), and RemoveVertices().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/DynamicVerticesOctree3.h