Unreal Engine 5.6 C++ API: UCapsuleComponent Class Reference
UCapsuleComponent Class Reference
#include "CapsuleComponent.h"
Public Member Functions
virtual bool AreSymmetricRotations (const FQuat &A, const FQuat &B, const FVector &Scale3D) const override
virtual void CalcBoundingCylinder (float &CylinderRadius, float &CylinderHalfHeight) const override
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual struct FCollisionShape GetCollisionShape (float Inflation=0.0f) const override
FORCEINLINE void InitCapsuleSize (float InRadius, float InHalfHeight)
virtual bool IsZeroExtent () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
UFUNCTION () 1 void SetCapsuleSize(float InRadius
Change the capsule size.
UFUNCTION () float GetScaledCapsuleHalfHeight() const
Returns the capsule half-height scaled by the component scale.
UFUNCTION () float GetScaledCapsuleHalfHeight_WithoutHemisphere() const
Returns the capsule half-height minus radius (to exclude the hemisphere), scaled by the component scale.
UFUNCTION () float GetScaledCapsuleRadius() const
Returns the capsule radius scaled by the component scale.
UFUNCTION () float GetShapeScale() const
Get the scale used by this shape.
UFUNCTION () float GetUnscaledCapsuleHalfHeight() const
Returns the capsule half-height, ignoring component scaling.
UFUNCTION () float GetUnscaledCapsuleHalfHeight_WithoutHemisphere() const
Returns the capsule half-height minus radius (to exclude the hemisphere), ignoring component scaling.
UFUNCTION () float GetUnscaledCapsuleRadius() const
Returns the capsule radius, ignoring component scaling.
UFUNCTION () void GetScaledCapsuleSize(float &OutRadius
Returns the capsule radius and half-height scaled by the component scale.
UFUNCTION () void GetScaledCapsuleSize_WithoutHemisphere(float &OutRadius
Returns the capsule radius and half-height scaled by the component scale.
UFUNCTION () void GetUnscaledCapsuleSize(float &OutRadius
Returns the capsule radius and half-height scaled by the component scale.
UFUNCTION () void GetUnscaledCapsuleSize_WithoutHemisphere(float &OutRadius
Returns the capsule radius and half-height, ignoring component scaling.
UFUNCTION () void SetCapsuleHalfHeight(float HalfHeight
Set the capsule half-height.
UFUNCTION () void SetCapsuleRadius(float Radius
Set the capsule radius.
virtual void UpdateBodySetup () override
Update the body setup parameters based on shape information.
Public Member Functions inherited from UShapeComponent
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual class UBodySetup * GetBodySetup () override
TSubclassOf< class UNavAreaBase > GetDesiredAreaClass () const
virtual bool GetIgnoreBoundsForEditorFocus () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
virtual bool IsNavigationRelevant () const override
virtual void Serialize (FArchive &Ar) override
void SetAreaClassOverride (TSubclassOf< class UNavAreaBase > InAreaClassOverride)
void SetUseSystemDefaultObstacleAreaClass ()
virtual bool ShouldCollideWhenPlacing () const override
UFUNCTION () 1 void SetLineThickness(float Thickness)
Data Fields
float bool bUpdateOverlaps =true)
bool bUpdateOverlaps =true)
float &OutHalfHeight const
float &OutHalfHeightWithoutHemisphere const
float InHalfHeight
Private Member Functions
GENERATED_UCLASS_BODY() protected UPROPERTY ()) float CapsuleRadius
Half-height, from center of capsule to the end of top or bottom hemisphere.
Additional Inherited Members
Protected Member Functions inherited from UShapeComponent
template<typename ShapeElemType>
void AddShapeToGeomArray ()
template<typename ShapeElemType>
void CreateShapeBodySetupIfNeeded ()
template<typename ComponentType>
bool PrepareSharedBodySetup ()
Checks if a shared body setup is available (and if we're eligible for it).
template<typename ShapeElemType>
void SetShapeToNewGeom (const FPhysicsShapeHandle &Shape)
UPROPERTY () float LineThickness
Used to control the line thickness when rendering.
UPROPERTY ()) TSubclassOf< class UNavAreaBase > AreaClassOverride
Navigation area type override, null / none = no change to nav mesh.
Protected Attributes inherited from UShapeComponent
UPROPERTY()) uint8 bUseSystemDefaultObstacleAreaClass uint8 bUseArchetypeBodySetup: 1
Only show this component if the actor is selected.
Detailed Description
Definition at line 16 of file CapsuleComponent.h.
Member Function Documentation
AreSymmetricRotations()
virtual bool UCapsuleComponent::AreSymmetricRotations (const FQuat & A, const FQuat & B, const FVector & Scale3D) const override virtual
References A, B, and FVector.
CalcBoundingCylinder()
virtual void UCapsuleComponent::CalcBoundingCylinder (float & CylinderRadius, float & CylinderHalfHeight) const override virtual
CalcBounds()
virtual FBoxSphereBounds UCapsuleComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
Reimplemented from UShapeComponent.
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UCapsuleComponent::CreateSceneProxy () override virtual
Reimplemented from UShapeComponent.
GetCollisionShape()
virtual struct FCollisionShape UCapsuleComponent::GetCollisionShape (float Inflation = 0.0f) const override virtual
References float, and GetCollisionShape().
Referenced by GetCollisionShape().
InitCapsuleSize()
FORCEINLINE void UCapsuleComponent::InitCapsuleSize (float InRadius, float InHalfHeight) inline
Definition at line 182 of file CapsuleComponent.h.
References FORCEINLINE, InHalfHeight, InitCapsuleSize(), FMath::Max, and FMath::Max3().
Referenced by InitCapsuleSize().
IsZeroExtent()
virtual bool UCapsuleComponent::IsZeroExtent () const override virtual
PostEditChangeProperty()
virtual void UCapsuleComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from UShapeComponent.
PostLoad()
virtual void UCapsuleComponent::PostLoad () override virtual
References Ar, PostLoad(), and UShapeComponent::Serialize().
Referenced by PostLoad().
UFUNCTION() [1/14]
UCapsuleComponent::UFUNCTION ()
Change the capsule size.
This is the unscaled size, before component scale is applied.
Parameters
InRadius : radius of end-cap hemispheres and center cylinder.
InHalfHeight : half-height, from capsule center to end of top or bottom hemisphere.
bUpdateOverlaps if true and this shape is registered and collides, updates touching array for owner actor.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/14]
UCapsuleComponent::UFUNCTION () const
Returns the capsule half-height scaled by the component scale.
This includes both the cylinder and hemisphere cap.
Returns
The capsule half-height scaled by the component scale.
References Category, const, and UFUNCTION().
UFUNCTION() [3/14]
UCapsuleComponent::UFUNCTION () const
Returns the capsule half-height minus radius (to exclude the hemisphere), scaled by the component scale.
From the center of the capsule this is the vertical distance along the straight cylindrical portion to the point just before the curve of top hemisphere begins.
Returns
The capsule half-height minus radius, scaled by the component scale.
References Category, const, and UFUNCTION().
UFUNCTION() [4/14]
UCapsuleComponent::UFUNCTION () const
Returns the capsule radius scaled by the component scale.
Returns
The capsule radius scaled by the component scale.
References Category, const, and float.
UFUNCTION() [5/14]
UCapsuleComponent::UFUNCTION () const
Get the scale used by this shape.
This is a uniform scale that is the minimum of any non-uniform scaling.
Returns
the scale used by this shape.
References Category, const, and UFUNCTION().
UFUNCTION() [6/14]
UCapsuleComponent::UFUNCTION () const
Returns the capsule half-height, ignoring component scaling.
This includes the hemisphere end cap.
Returns
The capsule radius, ignoring component scaling.
References Category, const, and UFUNCTION().
UFUNCTION() [7/14]
UCapsuleComponent::UFUNCTION () const
Returns the capsule half-height minus radius (to exclude the hemisphere), ignoring component scaling.
This excludes the hemisphere end cap. From the center of the capsule this is the vertical distance along the straight cylindrical portion to the point just before the curve of top hemisphere begins.
Returns
The capsule half-height minus radius, ignoring component scaling.
References Category, const, and UFUNCTION().
UFUNCTION() [8/14]
UCapsuleComponent::UFUNCTION () const
Returns the capsule radius, ignoring component scaling.
Returns
the capsule radius, ignoring component scaling.
References Category, const, and UFUNCTION().
UFUNCTION() [9/14]
UCapsuleComponent::UFUNCTION () &
Returns the capsule radius and half-height scaled by the component scale.
Half-height includes the hemisphere end cap.
Parameters
OutRadius Radius of the capsule, scaled by the component scale.
OutHalfHeight Half-height of the capsule, scaled by the component scale. Includes the hemisphere end cap.
Returns
The capsule radius and half-height scaled by the component scale.
References Category, and UFUNCTION().
UFUNCTION() [10/14]
UCapsuleComponent::UFUNCTION () &
Returns the capsule radius and half-height scaled by the component scale.
Half-height excludes the hemisphere end cap.
Parameters
OutRadius Radius of the capsule, ignoring component scaling.
OutHalfHeightWithoutHemisphere Half-height of the capsule, scaled by the component scale. Excludes the hemisphere end cap.
Returns
The capsule radius and half-height scaled by the component scale.
References Category, and UFUNCTION().
UFUNCTION() [11/14]
UCapsuleComponent::UFUNCTION () &
Returns the capsule radius and half-height scaled by the component scale.
Half-height includes the hemisphere end cap.
Parameters
OutRadius Radius of the capsule, scaled by the component scale.
OutHalfHeight Half-height of the capsule, scaled by the component scale. Includes the hemisphere end cap.
Returns
The capsule radius and half-height scaled by the component scale.
References Category, const, and UFUNCTION().
UFUNCTION() [12/14]
UCapsuleComponent::UFUNCTION () &
Returns the capsule radius and half-height, ignoring component scaling.
Half-height excludes the hemisphere end cap.
Parameters
OutRadius Radius of the capsule, ignoring component scaling.
OutHalfHeightWithoutHemisphere Half-height of the capsule, scaled by the component scale. Excludes the hemisphere end cap.
Returns
The capsule radius and half-height (excluding hemisphere end cap), ignoring component scaling.
References Category, const, and UFUNCTION().
UFUNCTION() [13/14]
UCapsuleComponent::UFUNCTION ()
Set the capsule half-height.
This is the unscaled half-height, before component scale is applied. If this capsule collides, updates touching array for owner actor.
Parameters
HalfHeight : half-height, from capsule center to end of top or bottom hemisphere.
bUpdateOverlaps if true and this shape is registered and collides, updates touching array for owner actor.
References bUpdateOverlaps, Category, and UFUNCTION().
UFUNCTION() [14/14]
UCapsuleComponent::UFUNCTION ()
Set the capsule radius.
This is the unscaled radius, before component scale is applied. If this capsule collides, updates touching array for owner actor.
Parameters
Radius : radius of end-cap hemispheres and center cylinder.
bUpdateOverlaps if true and this shape is registered and collides, updates touching array for owner actor.
References Category, and UFUNCTION().
UpdateBodySetup()
virtual void UCapsuleComponent::UpdateBodySetup () override virtual
Update the body setup parameters based on shape information.
Reimplemented from UShapeComponent.
UPROPERTY()
GENERATED_UCLASS_BODY() protected UCapsuleComponent::UPROPERTY () private
Half-height, from center of capsule to the end of top or bottom hemisphere.
This cannot be less than CapsuleRadius. Radius of cap hemispheres and center cylinder. This cannot be more than CapsuleHalfHeight.
References Category, float, and meta.
Field Documentation
bUpdateOverlaps [1/2]
bool UCapsuleComponent::bUpdateOverlaps =true)
Definition at line 48 of file CapsuleComponent.h.
Referenced by UFUNCTION().
bUpdateOverlaps [2/2]
bool UCapsuleComponent::bUpdateOverlaps =true)
Definition at line 57 of file CapsuleComponent.h.
const [1/2]
float &OutHalfHeightWithoutHemisphere UCapsuleComponent::const
Definition at line 123 of file CapsuleComponent.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
const [2/2]
float& OutHalfHeightWithoutHemisphere UCapsuleComponent::const
Definition at line 132 of file CapsuleComponent.h.
InHalfHeight
float UCapsuleComponent::InHalfHeight
Definition at line 48 of file CapsuleComponent.h.
Referenced by InitCapsuleSize().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/CapsuleComponent.h