Unreal Engine 5.6 C++ API: URendererSettings Class Reference
URendererSettings Class Reference
#include "RendererSettings.h"
Public Member Functions
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PreEditChange (FProperty *PropertyAboutToChange) override
Private Member Functions
void CheckForMissingShaderModels ()
void FixAntiAliasingOnShadingPathChange (FPropertyChangedEvent &PropertyChangedEvent)
void PreInitPropertiesFixup ()
void SanatizeReflectionCaptureResolution ()
UE_DEPRECATED (5.6, "MobilePlanarReflectionMode is deprecated. The screen space reflections on mobile is supported and the pixel projected reflection is removed.") UPROPERTY() uint8 MobilePlanarReflectionMode
void UpdateWorkingColorSpaceAndChromaticities ()
UPROPERTY()) uint32 bSupportExpFogMatchesVolumetricFog UPROPERTY()) uint32 bSupportLocalFogVolumes UPROPERTY()) uint32 bSupportCloudShadowOnForwardLitTranslucent UPROPERTY()) TEnumAsByte< ELightFunctionAtlasPixelFormat UPROPERTY()) uint32 bVolumetricFogUsesLightFunctionAtlas UPROPERTY ()
"When enabled, the height fog scattering lob will match the volumetric fog phase function."
UPROPERTY()) uint32 bLocalFogVolumeApplyOnTranslucent UPROPERTY () "
UPROPERTY () "
UPROPERTY()) TEnumAsByte< ECustomDepthStencil UPROPERTY() ")) uint32 bCustomDepthTaaJitter UPROPERTY () and propagate it through the renderer's post-processing chain. The legacy \"Linear color space only\" and \"Allow through tonemapper\" options now map to True and the engine keeps full alpha precision throughout post-processing. This feature can now be toggled without an engine restart.")) uint32 bEnableAlphaChannelInPostProcessing UPROPERTY () "
UPROPERTY() ")) uint32 bDefaultFeatureBloom UPROPERTY () ")) uint32 bDefaultFeatureAmbientOcclusion UPROPERTY () "
UPROPERTY() ")) uint32 bDefaultFeatureMotionBlur UPROPERTY () "
UPROPERTY()) uint32 bSingleLayerWaterUsesLightFunctionAtlas UPROPERTY()) uint32 bTranslucentUsesLightFunctionAtlas UPROPERTY () "
"Enable support for light function on Single Layer Water when the light function atlas is enabled."
UPROPERTY () "
"Enable rect light evaluation on translucent materials when using the Forward Shading mode."
UPROPERTY () "
"Enable local light shadow evaluation on translucent materials when using the Forward Shading mode."
UPROPERTY()) uint32 bGpuCrashDebugging UPROPERTY()) uint32 bMultiView UPROPERTY()) uint32 bMobilePostProcessing UPROPERTY()) uint32 bMobileMultiView UPROPERTY() rendering will use HW accelerated sRGB encoding/decoding. Available only on Oculus for now.")) uint32 bMobileUseHWsRGBEncoding UPROPERTY ()) uint32 bRoundRobinOcclusion UPROPERTY ()) uint32 bMeshStreaming UPROPERTY () "
UPROPERTY()) uint32 bSupportStationarySkylight UPROPERTY()) uint32 bSupportLowQualityLightmaps UPROPERTY()) uint32 bSupportPointLightWholeSceneShadows UPROPERTY()) uint32 bSupportTranslucentPerObjectShadow UPROPERTY()) uint32 bSupportCloudShadowOnSingleLayerWater UPROPERTY () "
"Stationary skylight requires permutations of the basepass shaders. Disabling will reduce the number of shader permutations required per material. Changing this setting requires restarting the editor." "For a mobile renderer disabling this option does not reduce shader permutations, but may increse GPU performance. It's recommended to disable it if your project does not requiure Stationary or Movable skylights."
UPROPERTY () "
"Enable Substrate opaque material rough refractions effect from top layers over layers below."
UPROPERTY()) uint32 SubstrateTranslucentMaterialRoughRefraction UPROPERTY () "
"Enable Substrate translucent material rough refractions effect over background. Editor restart is not required."
UPROPERTY () "
"Enable substrate layer support."
UPROPERTY()) uint32 bMaterialRoughDiffuse UPROPERTY()) uint32 bMaterialEnergyConservation UPROPERTY()) uint32 bAutomaticallySetMaterialUsageInEditorDefault UPROPERTY () "
"Enable rough diffuse material."
UPROPERTY () "
UPROPERTY () . Always supported for opaque geometry on mobile deferred. Changing this setting the editor."
UPROPERTY()) uint32 bUseHairStrandsAutoLODMode UPROPERTY()) uint32 bSupportSkinCacheShaders UPROPERTY () . Changing this setting the editor."
"Enable hair strands Auto LOD mode by default."
UPROPERTY () . It .SupportSkyAtmosphere to be true."
"The sky atmosphere component can light up the height fog but it requires extra samplers/textures to be bound to apply aerial perspective on transparent surfaces (and all surfaces on mobile via per vertex evaluation)." "It requires r.SupportSkyAtmosphere to be true."
UPROPERTY () ."
"The sky atmosphere component requires extra samplers/textures to be bound to apply aerial perspective on transparent surfaces (and all surfaces on mobile via per vertex evaluation)."
UPROPERTY()) uint32 LumenRayTracedTranslucentRefractions UPROPERTY()) uint32 bEnableMegaLights UPROPERTY()) uint32 bEnableRayTracingShadows UPROPERTY()) TEnumAsByte< EShadowMapMethod UPROPERTY()) uint32 bEnableRayTracing UPROPERTY () .\nIt 's recommended to enable this setting as it guarantees that static meshes have multiple ray tracing LODs to support streaming."
"Ray Tracing settings."
UPROPERTY()) uint32 bMobileAllowDistanceFieldShadows UPROPERTY()) uint32 bMobileAllowMovableSpotlightShadows UPROPERTY () or 16 bit(if > 256 bones) bone indices for rendering."
UPROPERTY()) TEnumAsByte< ECompositingSampleCount UPROPERTY ()) ELightUnits DefaultLightUnits
UPROPERTY()) uint32 ReflectionEnvironmentLightmapMixBasedOnRoughness UPROPERTY()) uint32 bUseHardwareRayTracingForLumen UPROPERTY ()) ELumenRayLightingMode LumenRayLightingMode
UPROPERTY()) uint32 LumenFrontLayerTranslucencyReflections UPROPERTY()) TEnumAsByte< ELumenSoftwareTracingMode UPROPERTY ()) ELumenScreenTracingSource LumenScreenTracingSource
UPROPERTY ()) EScreenPercentageMode DefaultScreenPercentageDesktopMode
UPROPERTY ()) EScreenPercentageMode DefaultScreenPercentageMobileMode
UPROPERTY ()) EScreenPercentageMode DefaultScreenPercentagePathTracerMode
UPROPERTY ()) EScreenPercentageMode DefaultScreenPercentageVRMode
UPROPERTY()) uint32 bSkipCompilingGPUSkinVF UPROPERTY ()) ESkinCacheDefaultBehavior DefaultSkinCacheBehavior
"When enabled this will skip compiling GPU skin vertex factory shader variants with the assumption that all skinning work will be done via the skin cache."
UPROPERTY() ")) uint32 bDefaultFeatureAutoExposure UPROPERTY () ")) TEnumAsByte< EAutoExposureMethodUI UPROPERTY ()) float DefaultFeatureAutoExposureBias
UE_DEPRECATED(4.26, "Extend Default Luminance Range is deprecated, and is forced to ON at all times in new projects.") UPROPERTY()) uint32 bExtendDefaultLuminanceRangeInAutoExposureSettings UPROPERTY ()) float DefaultFeatureLocalExposureHighlightContrast
UPROPERTY ()) float DefaultFeatureLocalExposureShadowContrast
UPROPERTY()) TEnumAsByte< EDefaultBackBufferPixelFormat UPROPERTY ()) float DefaultManualScreenPercentage
UPROPERTY()) uint32 bGlobalClipPlane UPROPERTY()) TEnumAsByte< EGBufferFormat UPROPERTY() or use a GPU-based method on Shader Model 5 hardware.")) uint32 bUseGPUMorphTargets UPROPERTY ()) float MorphTargetMaxBlendWeight
UPROPERTY()) uint32 bShouldHeterogeneousVolumesCastShadows UPROPERTY()) uint32 bCompositeHeterogeneousVolumesWithTranslucency UPROPERTY ()) float WireframeCullThreshold
UPROPERTY ()) FPerPlatformBool bDiscardSkeletalMeshOptionalLODs
UPROPERTY()) uint32 bMobileScreenSpaceReflections UPROPERTY()) uint32 bMobileSupportsGen4TAA UPROPERTY ()) FPerPlatformBool bStreamSkeletalMeshLODs
UPROPERTY ()) FPerPlatformInt DefaultBoneInfluenceLimit
UPROPERTY ()) FPerPlatformInt MaxSkinBones
UPROPERTY ()) FSoftObjectPath VisualizeCalibrationColorMaterialPath
" Visualize calibration material settings for post process calibration materials, used for setting full-screen images used for monitor calibration."
UPROPERTY ()) FSoftObjectPath VisualizeCalibrationCustomMaterialPath
UPROPERTY ()) FSoftObjectPath VisualizeCalibrationGrayscaleMaterialPath
UPROPERTY() uint32 bEnableRayTracingSkylight_DEPRECATED UPROPERTY() . Checked UPROPERTY ()) FVector TranslucentSortAxis
UPROPERTY()) uint32 bRenderUnbuiltPreviewShadowsInGame UPROPERTY()) uint32 bStencilForLODDither UPROPERTY()) TEnumAsByte< EEarlyZPass UPROPERTY()) uint32 bEarlyZPassOnlyMaterialMasking UPROPERTY()) uint32 bEnableCSMCaching UPROPERTY()) uint32 bDBuffer UPROPERTY() .")) TEnumAsByte<EClearSceneOptions UPROPERTY ()) TEnumAsByte<EVelocityOutputPass UPROPERTY ()) TEnumAsByte<EVertexDeformationOutputsVelocity UPROPERTY ()) uint32 bSelectiveBasePassOutputs UPROPERTY ()) uint32 bDefaultParticleCutouts UPROPERTY ()) int32 GPUSimulationTextureSizeX
UPROPERTY ()) int32 GPUSimulationTextureSizeY
GENERATED_UCLASS_BODY() UPROPERTY()) TEnumAsByte< EMobileShadingPath UPROPERTY()) uint32 bMobileSupportDeferredOnOpenGL UPROPERTY()) uint32 bMobileSupportGPUScene UPROPERTY()) TEnumAsByte< EMobileAntiAliasingMethod UPROPERTY()) TEnumAsByte< EMobileFloatPrecisionMode UPROPERTY()) uint32 bMobileAllowDitheredLODTransition UPROPERTY()) uint32 bMobileVirtualTextures UPROPERTY() \nChecked UPROPERTY()) uint32 bClearCoatEnableSecondNormal UPROPERTY()) TEnumAsByte< EDynamicGlobalIlluminationMethod UPROPERTY()) TEnumAsByte< EReflectionMethod UPROPERTY ()) int32 ReflectionCaptureResolution
UPROPERTY()) uint32 bGPUSkinLimit2BoneInfluences UPROPERTY()) uint32 bSupportDepthOnlyIndexBuffers UPROPERTY()) uint32 bSupportReversedIndexBuffers UPROPERTY()) uint32 bMobileAmbientOcclusion UPROPERTY()) uint32 bMobileDBuffer UPROPERTY()) uint32 bUseUnlimitedBoneInfluences UPROPERTY()) uint32 bAlwaysUseDeformerForUnlimitedBoneInfluences UPROPERTY ()) int32 UnlimitedBonInfluencesThreshold
UPROPERTY()) uint32 bTemporalUpsampling UPROPERTY ()) TEnumAsByte< EAntiAliasingMethod > DefaultFeatureAntiAliasing
UPROPERTY()) uint32 bMobileEnableStaticAndCSMShadowReceivers UPROPERTY()) uint32 bMobileEnableMovableLightCSMShaderCulling UPROPERTY ()) TEnumAsByte< EMobileLocalLightSetting > MobileLocalLightSetting
Private Attributes
UPROPERTY()) uint32 bSupportExpFogMatchesVolumetricFog UPROPERTY()) uint32 bSupportLocalFogVolumes UPROPERTY()) uint32 bSupportCloudShadowOnForwardLitTranslucent UPROPERTY()) TEnumAsByte< ELightFunctionAtlasPixelFormat UPROPERTY()) uint32 bVolumetricFogUsesLightFunctionAtlas when the light function atlas is enabled uint32 bDeferredLightingUsesLightFunctionAtlas: 1
UPROPERTY()) uint32 LumenRayTracedTranslucentRefractions UPROPERTY()) uint32 bEnableMegaLights UPROPERTY()) uint32 bEnableRayTracingShadows UPROPERTY()) TEnumAsByte< EShadowMapMethod UPROPERTY()) uint32 bEnableRayTracing ConfigRestartRequired
UPROPERTY()) TEnumAsByte< ECustomDepthStencil UPROPERTY() ")) uint32 bCustomDepthTaaJitter UPROPERTY () and propagate it through the renderer's post-processing chain. The legacy \"Linear color space only\" and \"Allow through tonemapper\" options now map to True and the engine keeps full alpha precision throughout post-processing. This feature can now be toggled without an engine restart.")) uint32 bEnableAlphaChannelInPostProcessing ConfigRestartRequired
ConfigRestartRequired
UPROPERTY()) uint32 bSingleLayerWaterUsesLightFunctionAtlas UPROPERTY()) uint32 bTranslucentUsesLightFunctionAtlas ConfigRestartRequired
UPROPERTY()) uint32 bGpuCrashDebugging UPROPERTY()) uint32 bMultiView UPROPERTY()) uint32 bMobilePostProcessing UPROPERTY()) uint32 bMobileMultiView UPROPERTY() rendering will use HW accelerated sRGB encoding/decoding. Available only on Oculus for now.")) uint32 bMobileUseHWsRGBEncoding UPROPERTY ()) uint32 bRoundRobinOcclusion UPROPERTY ()) uint32 bMeshStreaming ConfigRestartRequired
UPROPERTY()) uint32 bSupportStationarySkylight UPROPERTY()) uint32 bSupportLowQualityLightmaps UPROPERTY()) uint32 bSupportPointLightWholeSceneShadows UPROPERTY()) uint32 bSupportTranslucentPerObjectShadow UPROPERTY()) uint32 bSupportCloudShadowOnSingleLayerWater ConfigRestartRequired
UPROPERTY()) uint32 SubstrateTranslucentMaterialRoughRefraction ConfigRestartRequired
UPROPERTY()) uint32 bMaterialRoughDiffuse UPROPERTY()) uint32 bMaterialEnergyConservation UPROPERTY()) uint32 bAutomaticallySetMaterialUsageInEditorDefault ConfigRestartRequired
UPROPERTY()) uint32 bUseHairStrandsAutoLODMode UPROPERTY()) uint32 bSupportSkinCacheShaders ConfigRestartRequired
UPROPERTY()) uint32 bMobileAllowDistanceFieldShadows UPROPERTY()) uint32 bMobileAllowMovableSpotlightShadows ConfigRestartRequired
EditCondition
int32 PreEditReflectionCaptureResolution = 128
shadow copy saved before effects of PostEditChange() to provide option to roll back edit.
TWeakPtr< class SNotificationItem > ShaderModelNotificationPtr
UPROPERTY()) uint32 bLocalFogVolumeApplyOnTranslucent ToolTip
ToolTip
UPROPERTY()) TEnumAsByte< ECustomDepthStencil UPROPERTY() ")) uint32 bCustomDepthTaaJitter UPROPERTY () and propagate it through the renderer's post-processing chain. The legacy \"Linear color space only\" and \"Allow through tonemapper\" options now map to True and the engine keeps full alpha precision throughout post-processing. This feature can now be toggled without an engine restart.")) uint32 bEnableAlphaChannelInPostProcessing ToolTip = "Enable primitive alpha holdout support in multiple deferred renderer passes. If primitive holdout masks are not to be used, keep this setting disabled for increased performance. Requires \"Alpha Output\" to be enabled."
UPROPERTY() ")) uint32 bDefaultFeatureBloom UPROPERTY () ")) uint32 bDefaultFeatureAmbientOcclusion ToolTip
UPROPERTY() ")) uint32 bDefaultFeatureMotionBlur ToolTip
UPROPERTY()) uint32 bSingleLayerWaterUsesLightFunctionAtlas UPROPERTY()) uint32 bTranslucentUsesLightFunctionAtlas ToolTip = "Enable IES profile evaluation on translucent materials when using the Forward Shading mode."
UPROPERTY()) uint32 bGpuCrashDebugging UPROPERTY()) uint32 bMultiView UPROPERTY()) uint32 bMobilePostProcessing UPROPERTY()) uint32 bMobileMultiView UPROPERTY() rendering will use HW accelerated sRGB encoding/decoding. Available only on Oculus for now.")) uint32 bMobileUseHWsRGBEncoding UPROPERTY ()) uint32 bRoundRobinOcclusion UPROPERTY ()) uint32 bMeshStreaming ToolTip = "Enable rendering with the heterogeneous volumes subsystem."
UPROPERTY()) uint32 bSupportStationarySkylight UPROPERTY()) uint32 bSupportLowQualityLightmaps UPROPERTY()) uint32 bSupportPointLightWholeSceneShadows UPROPERTY()) uint32 bSupportTranslucentPerObjectShadow UPROPERTY()) uint32 bSupportCloudShadowOnSingleLayerWater ToolTip = "Enable Substrate materials (Beta)."
UPROPERTY()) uint32 SubstrateTranslucentMaterialRoughRefraction ToolTip = "Enable advanced Substrate material debug visualization shaders. Base pass shaders can output such advanced data. Only available for Editors built for Win64 and running with the DX12 graphic API for now."
UPROPERTY()) uint32 bMaterialRoughDiffuse UPROPERTY()) uint32 bMaterialEnergyConservation UPROPERTY()) uint32 bAutomaticallySetMaterialUsageInEditorDefault ToolTip = "Enable support for Order-Independent-Transparency on translucent surfaces, which remove most of the sorting artifact among translucent surfaces."
Detailed Description
Definition at line 306 of file RendererSettings.h.
Member Function Documentation
CanEditChange()
virtual bool URendererSettings::CanEditChange (const FProperty * InProperty) const override virtual
CheckForMissingShaderModels()
void URendererSettings::CheckForMissingShaderModels () private
FixAntiAliasingOnShadingPathChange()
void URendererSettings::FixAntiAliasingOnShadingPathChange (FPropertyChangedEvent & PropertyChangedEvent) private
PostEditChangeProperty()
virtual void URendererSettings::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void URendererSettings::PostInitProperties () override virtual
References PostInitProperties().
Referenced by PostInitProperties().
PreEditChange()
virtual void URendererSettings::PreEditChange (FProperty * PropertyAboutToChange) override virtual
PreInitPropertiesFixup()
void URendererSettings::PreInitPropertiesFixup () private
SanatizeReflectionCaptureResolution()
void URendererSettings::SanatizeReflectionCaptureResolution () private
UE_DEPRECATED()
URendererSettings::UE_DEPRECATED (5. 6, "MobilePlanarReflectionMode is deprecated. The screen space reflections on mobile is supported and the pixel projected reflection is removed.") private
References Category, config, ConfigRestartRequired, EditCondition, meta, Mobile, ToolTip, UE_DEPRECATED(), and UPROPERTY().
Referenced by UE_DEPRECATED(), and UPROPERTY().
UpdateWorkingColorSpaceAndChromaticities()
void URendererSettings::UpdateWorkingColorSpaceAndChromaticities () private
UPROPERTY() [1/50]
UPROPERTY()) uint32 bSupportExpFogMatchesVolumetricFog UPROPERTY()) uint32 bSupportLocalFogVolumes UPROPERTY()) uint32 bSupportCloudShadowOnForwardLitTranslucent UPROPERTY()) TEnumAsByte< ELightFunctionAtlasPixelFormat UPROPERTY()) uint32 bVolumetricFogUsesLightFunctionAtlas URendererSettings::UPROPERTY () private
"When enabled, the height fog scattering lob will match the volumetric fog phase function."
"Enable cloud shadow on translucent surface. This is evaluated per vertex to reduce GPU cost. The cloud system requires extra samplers/textures to be bound to vertex shaders." "Select the format of the light function atlas texture." "Enable support for light function on volumetric fog, when the light function atlas is enabled." "Enable support for light function on deferred lighting (multi-pass and clustered), when the light function atlas is enabled."
References ToolTip.
UPROPERTY() [2/50]
UPROPERTY()) uint32 bLocalFogVolumeApplyOnTranslucent URendererSettings::UPROPERTY () private
UPROPERTY() [3/50]
URendererSettings::UPROPERTY () private
UPROPERTY() [4/50]
UPROPERTY()) TEnumAsByte< ECustomDepthStencil UPROPERTY() ")) uint32 bCustomDepthTaaJitter UPROPERTY () and propagate it through the renderer's post-processing chain. The legacy \"Linear color space only\" and \"Allow through tonemapper\" options now map to True and the engine keeps full alpha precision throughout post-processing. This feature can now be toggled without an engine restart.")) uint32 bEnableAlphaChannelInPostProcessing URendererSettings::UPROPERTY () private
UPROPERTY() [5/50]
UPROPERTY() ")) uint32 bDefaultFeatureBloom UPROPERTY () ")) uint32 bDefaultFeatureAmbientOcclusion URendererSettings::UPROPERTY () private
UPROPERTY() [6/50]
UPROPERTY() ")) uint32 bDefaultFeatureMotionBlur URendererSettings::UPROPERTY () private
UPROPERTY() [7/50]
UPROPERTY()) uint32 bSingleLayerWaterUsesLightFunctionAtlas UPROPERTY()) uint32 bTranslucentUsesLightFunctionAtlas URendererSettings::UPROPERTY () private
"Enable support for light function on Single Layer Water when the light function atlas is enabled."
"Enable support for light function on Translucent material using Forward Shading mode, when the light function atlas is enabled." "Enable IES profile evaluation on translucent materials when using the Forward Shading mode."
UPROPERTY() [8/50]
URendererSettings::UPROPERTY () private
"Enable rect light evaluation on translucent materials when using the Forward Shading mode."
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [9/50]
URendererSettings::UPROPERTY () private
"Enable local light shadow evaluation on translucent materials when using the Forward Shading mode."
References Category, config, ConfigRestartRequired, EditCondition, meta, ToolTip, and UPROPERTY().
UPROPERTY() [10/50]
UPROPERTY()) uint32 bGpuCrashDebugging UPROPERTY()) uint32 bMultiView UPROPERTY()) uint32 bMobilePostProcessing UPROPERTY()) uint32 bMobileMultiView UPROPERTY() rendering will use HW accelerated sRGB encoding/decoding. Available only on Oculus for now.")) uint32 bMobileUseHWsRGBEncoding UPROPERTY ()) uint32 bRoundRobinOcclusion UPROPERTY ()) uint32 bMeshStreaming URendererSettings::UPROPERTY () private
UPROPERTY() [11/50]
UPROPERTY()) uint32 bSupportStationarySkylight UPROPERTY()) uint32 bSupportLowQualityLightmaps UPROPERTY()) uint32 bSupportPointLightWholeSceneShadows UPROPERTY()) uint32 bSupportTranslucentPerObjectShadow UPROPERTY()) uint32 bSupportCloudShadowOnSingleLayerWater URendererSettings::UPROPERTY () private
"Stationary skylight requires permutations of the basepass shaders. Disabling will reduce the number of shader permutations required per material. Changing this setting requires restarting the editor." "For a mobile renderer disabling this option does not reduce shader permutations, but may increse GPU performance. It's recommended to disable it if your project does not requiure Stationary or Movable skylights."
"Low quality lightmap requires permutations of the lightmap rendering shaders. Disabling will reduce the number of shader permutations required per material. Note that the mobile renderer requires low quality lightmaps, so disabling this setting is not recommended for mobile titles using static lighting. Changing this setting requires restarting the editor." PointLight WholeSceneShadows requires many vertex and geometry shader permutations for cubemap rendering. Disabling will reduce the number of shader permutations required per material. Changing this setting requires restarting the editor." ""Enable translucent volumetric self-shadow, requires vertex and pixel shader permutations for all tranlucent materials even if not used by any light." "Enable cloud shadow on SingleLayerWater surface. This is evaluated per vertex to reduce GPU cost. The cloud system requires extra samplers/textures to be bound to vertex shaders." "Enable Substrate materials (Beta)."
UPROPERTY() [12/50]
URendererSettings::UPROPERTY () private
"Enable Substrate opaque material rough refractions effect from top layers over layers below."
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [13/50]
UPROPERTY()) uint32 SubstrateTranslucentMaterialRoughRefraction URendererSettings::UPROPERTY () private
"Enable Substrate translucent material rough refractions effect over background. Editor restart is not required."
"Enable advanced Substrate material debug visualization shaders. Base pas shaders can output such advanced data."
UPROPERTY() [14/50]
URendererSettings::UPROPERTY () private
"Enable substrate layer support."
UPROPERTY() [15/50]
UPROPERTY()) uint32 bMaterialRoughDiffuse UPROPERTY()) uint32 bMaterialEnergyConservation UPROPERTY()) uint32 bAutomaticallySetMaterialUsageInEditorDefault URendererSettings::UPROPERTY () private
"Enable rough diffuse material."
"Enable rough diffuse material." "Automatically set Material usage flags in editor default." "Enable Order Independent Transparency (Experimental)."
UPROPERTY() [16/50]
URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, Mobile, ToolTip, and UPROPERTY().
UPROPERTY() [17/50]
URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [18/50]
UPROPERTY()) uint32 bUseHairStrandsAutoLODMode UPROPERTY()) uint32 bSupportSkinCacheShaders URendererSettings::UPROPERTY () private
"Enable hair strands Auto LOD mode by default."
"Skin cache allows a compute shader to skin once each vertex, save those results into a new buffer and reuse those calculations when later running the depth, base and velocity passes. This also allows opting into the 'recompute tangents' for skinned mesh instance feature. Disabling will reduce the number of shader permutations required per material. Changing this setting requires restarting the editor." "Support hardware variable rate shading.
UPROPERTY() [19/50]
URendererSettings::UPROPERTY () private
"The sky atmosphere component can light up the height fog but it requires extra samplers/textures to be bound to apply aerial perspective on transparent surfaces (and all surfaces on mobile via per vertex evaluation)." "It requires r.SupportSkyAtmosphere to be true."
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [20/50]
URendererSettings::UPROPERTY () private
"The sky atmosphere component requires extra samplers/textures to be bound to apply aerial perspective on transparent surfaces (and all surfaces on mobile via per vertex evaluation)."
UPROPERTY() [21/50]
UPROPERTY()) uint32 LumenRayTracedTranslucentRefractions UPROPERTY()) uint32 bEnableMegaLights UPROPERTY()) uint32 bEnableRayTracingShadows UPROPERTY()) TEnumAsByte< EShadowMapMethod UPROPERTY()) uint32 bEnableRayTracing URendererSettings::UPROPERTY () private
"Ray Tracing settings."
UPROPERTY() [22/50]
UPROPERTY()) uint32 bMobileAllowDistanceFieldShadows UPROPERTY()) uint32 bMobileAllowMovableSpotlightShadows URendererSettings::UPROPERTY () private
UPROPERTY() [23/50]
UPROPERTY()) TEnumAsByte< ECompositingSampleCount URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [24/50]
UPROPERTY()) uint32 ReflectionEnvironmentLightmapMixBasedOnRoughness UPROPERTY()) uint32 bUseHardwareRayTracingForLumen URendererSettings::UPROPERTY () private
References Category, config, EditCondition, meta, ToolTip, and UPROPERTY().
UPROPERTY() [25/50]
UPROPERTY()) uint32 LumenFrontLayerTranslucencyReflections UPROPERTY()) TEnumAsByte< ELumenSoftwareTracingMode URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [26/50]
URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [27/50]
URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [28/50]
URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, EditCondition, meta, ToolTip, and UPROPERTY().
UPROPERTY() [29/50]
URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [30/50]
UPROPERTY()) uint32 bSkipCompilingGPUSkinVF URendererSettings::UPROPERTY () private
"When enabled this will skip compiling GPU skin vertex factory shader variants with the assumption that all skinning work will be done via the skin cache."
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [31/50]
UPROPERTY() ")) uint32 bDefaultFeatureAutoExposure UPROPERTY () ")) TEnumAsByte< EAutoExposureMethodUI URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, UE_DEPRECATED(), and UPROPERTY().
UPROPERTY() [32/50]
UE_DEPRECATED(4.26, "Extend Default Luminance Range is deprecated, and is forced to ON at all times in new projects.") UPROPERTY()) uint32 bExtendDefaultLuminanceRangeInAutoExposureSettings URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [33/50]
URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [34/50]
UPROPERTY()) TEnumAsByte< EDefaultBackBufferPixelFormat URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [35/50]
UPROPERTY()) uint32 bGlobalClipPlane UPROPERTY()) TEnumAsByte< EGBufferFormat UPROPERTY() or use a GPU-based method on Shader Model 5 hardware.")) uint32 bUseGPUMorphTargets URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [36/50]
UPROPERTY()) uint32 bShouldHeterogeneousVolumesCastShadows UPROPERTY()) uint32 bCompositeHeterogeneousVolumesWithTranslucency URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [37/50]
URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [38/50]
UPROPERTY()) uint32 bMobileScreenSpaceReflections UPROPERTY()) uint32 bMobileSupportsGen4TAA URendererSettings::UPROPERTY () private
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [39/50]
URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [40/50]
URendererSettings::UPROPERTY () private
UPROPERTY() [41/50]
URendererSettings::UPROPERTY () private
" Visualize calibration material settings for post process calibration materials, used for setting full-screen images used for monitor calibration."
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [42/50]
URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [43/50]
URendererSettings::UPROPERTY () private
References ConfigRestartRequired.
UPROPERTY() [44/50]
UPROPERTY() uint32 bEnableRayTracingSkylight_DEPRECATED UPROPERTY() . Checked URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, EditCondition, FVector, meta, ToolTip, and UPROPERTY().
UPROPERTY() [45/50]
UPROPERTY()) uint32 bRenderUnbuiltPreviewShadowsInGame UPROPERTY()) uint32 bStencilForLODDither UPROPERTY()) TEnumAsByte< EEarlyZPass UPROPERTY()) uint32 bEarlyZPassOnlyMaterialMasking UPROPERTY()) uint32 bEnableCSMCaching UPROPERTY()) uint32 bDBuffer UPROPERTY() .")) TEnumAsByte<EClearSceneOptions UPROPERTY ()) TEnumAsByte<EVelocityOutputPass UPROPERTY ()) TEnumAsByte<EVertexDeformationOutputsVelocity UPROPERTY ()) uint32 bSelectiveBasePassOutputs UPROPERTY ()) uint32 bDefaultParticleCutouts URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [46/50]
URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [47/50]
GENERATED_UCLASS_BODY() UPROPERTY()) TEnumAsByte< EMobileShadingPath UPROPERTY()) uint32 bMobileSupportDeferredOnOpenGL UPROPERTY()) uint32 bMobileSupportGPUScene UPROPERTY()) TEnumAsByte< EMobileAntiAliasingMethod UPROPERTY()) TEnumAsByte< EMobileFloatPrecisionMode UPROPERTY()) uint32 bMobileAllowDitheredLODTransition UPROPERTY()) uint32 bMobileVirtualTextures UPROPERTY() \nChecked UPROPERTY()) uint32 bClearCoatEnableSecondNormal UPROPERTY()) TEnumAsByte< EDynamicGlobalIlluminationMethod UPROPERTY()) TEnumAsByte< EReflectionMethod URendererSettings::UPROPERTY () private
References Category, config, EditCondition, meta, ToolTip, and UPROPERTY().
Referenced by UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [48/50]
UPROPERTY()) uint32 bGPUSkinLimit2BoneInfluences UPROPERTY()) uint32 bSupportDepthOnlyIndexBuffers UPROPERTY()) uint32 bSupportReversedIndexBuffers UPROPERTY()) uint32 bMobileAmbientOcclusion UPROPERTY()) uint32 bMobileDBuffer UPROPERTY()) uint32 bUseUnlimitedBoneInfluences UPROPERTY()) uint32 bAlwaysUseDeformerForUnlimitedBoneInfluences URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, ToolTip, and UPROPERTY().
UPROPERTY() [49/50]
UPROPERTY()) uint32 bTemporalUpsampling URendererSettings::UPROPERTY () private
References Category, config, EditCondition, meta, ToolTip, and UPROPERTY().
UPROPERTY() [50/50]
UPROPERTY()) uint32 bMobileEnableStaticAndCSMShadowReceivers UPROPERTY()) uint32 bMobileEnableMovableLightCSMShaderCulling URendererSettings::UPROPERTY () private
References Category, config, ConfigRestartRequired, meta, Mobile, ToolTip, and UPROPERTY().
Field Documentation
bDeferredLightingUsesLightFunctionAtlas
UPROPERTY()) uint32 bSupportExpFogMatchesVolumetricFog UPROPERTY()) uint32 bSupportLocalFogVolumes UPROPERTY()) uint32 bSupportCloudShadowOnForwardLitTranslucent UPROPERTY()) TEnumAsByte< ELightFunctionAtlasPixelFormat UPROPERTY()) uint32 bVolumetricFogUsesLightFunctionAtlas when the light function atlas is enabled uint32 URendererSettings::bDeferredLightingUsesLightFunctionAtlas private
Definition at line 1049 of file RendererSettings.h.
ConfigRestartRequired [1/10]
UPROPERTY()) uint32 LumenRayTracedTranslucentRefractions UPROPERTY()) uint32 bEnableMegaLights UPROPERTY()) uint32 bEnableRayTracingShadows UPROPERTY()) TEnumAsByte< EShadowMapMethod UPROPERTY()) uint32 bEnableRayTracing URendererSettings::ConfigRestartRequired private
Initial value:
= true))
        uint32 bGenerateRayTracingProxies : 1
Definition at line 658 of file RendererSettings.h.
Referenced by UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
ConfigRestartRequired [2/10]
UPROPERTY()) TEnumAsByte< ECustomDepthStencil UPROPERTY() ")) uint32 bCustomDepthTaaJitter UPROPERTY () and propagate it through the renderer's post-processing chain. The legacy \"Linear color space only\" and \"Allow through tonemapper\" options now map to True and the engine keeps full alpha precision throughout post-processing. This feature can now be toggled without an engine restart.")) uint32 bEnableAlphaChannelInPostProcessing URendererSettings::ConfigRestartRequired private
Initial value:
= true))
    uint32 bDeferredSupportPrimitiveAlphaHoldout : 1
Definition at line 772 of file RendererSettings.h.
ConfigRestartRequired [3/10]
URendererSettings::ConfigRestartRequired private
Initial value:
= true))
        uint32 bSupportSkyAtmosphere : 1
Definition at line 989 of file RendererSettings.h.
ConfigRestartRequired [4/10]
UPROPERTY()) uint32 bSingleLayerWaterUsesLightFunctionAtlas UPROPERTY()) uint32 bTranslucentUsesLightFunctionAtlas URendererSettings::ConfigRestartRequired private
Initial value:
= true))
    uint32 bSupportIESProfileOnTranslucent : 1
Definition at line 1075 of file RendererSettings.h.
ConfigRestartRequired [5/10]
UPROPERTY()) uint32 bGpuCrashDebugging UPROPERTY()) uint32 bMultiView UPROPERTY()) uint32 bMobilePostProcessing UPROPERTY()) uint32 bMobileMultiView UPROPERTY() rendering will use HW accelerated sRGB encoding/decoding. Available only on Oculus for now.")) uint32 bMobileUseHWsRGBEncoding UPROPERTY ()) uint32 bRoundRobinOcclusion UPROPERTY ()) uint32 bMeshStreaming URendererSettings::ConfigRestartRequired private
Initial value:
= false))
    uint32 bEnableHeterogeneousVolumes : 1
Definition at line 1142 of file RendererSettings.h.
ConfigRestartRequired [6/10]
UPROPERTY()) uint32 bSupportStationarySkylight UPROPERTY()) uint32 bSupportLowQualityLightmaps UPROPERTY()) uint32 bSupportPointLightWholeSceneShadows UPROPERTY()) uint32 bSupportTranslucentPerObjectShadow UPROPERTY()) uint32 bSupportCloudShadowOnSingleLayerWater URendererSettings::ConfigRestartRequired private
Initial value:
= true))
        uint32 bEnableSubstrate : 1
Definition at line 1211 of file RendererSettings.h.
ConfigRestartRequired [7/10]
UPROPERTY()) uint32 SubstrateTranslucentMaterialRoughRefraction URendererSettings::ConfigRestartRequired private
Initial value:
= true))
        uint32 SubstrateDebugAdvancedVisualizationShaders : 1
Definition at line 1238 of file RendererSettings.h.
ConfigRestartRequired [8/10]
UPROPERTY()) uint32 bMaterialRoughDiffuse UPROPERTY()) uint32 bMaterialEnergyConservation UPROPERTY()) uint32 bAutomaticallySetMaterialUsageInEditorDefault URendererSettings::ConfigRestartRequired private
Initial value:
= true))
        uint32 bOrderedIndependentTransparencyEnable : 1
Definition at line 1284 of file RendererSettings.h.
ConfigRestartRequired [9/10]
UPROPERTY()) uint32 bUseHairStrandsAutoLODMode UPROPERTY()) uint32 bSupportSkinCacheShaders URendererSettings::ConfigRestartRequired private
Initial value:
= true))
    uint32 bSupportHardwareVariableRateShading : 1
Definition at line 1311 of file RendererSettings.h.
ConfigRestartRequired [10/10]
UPROPERTY()) uint32 bMobileAllowDistanceFieldShadows UPROPERTY()) uint32 bMobileAllowMovableSpotlightShadows URendererSettings::ConfigRestartRequired private
Initial value:
= true))
        uint32 bSupport16BitBoneIndex : 1
Definition at line 1376 of file RendererSettings.h.
EditCondition
URendererSettings::EditCondition private
Initial value:
= "bEnableSubstrate"))
        uint32 SubstrateEnableLayerSupport : 1
Definition at line 1248 of file RendererSettings.h.
Referenced by UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
PreEditReflectionCaptureResolution
int32 URendererSettings::PreEditReflectionCaptureResolution = 128 private
shadow copy saved before effects of PostEditChange() to provide option to roll back edit.
Definition at line 1507 of file RendererSettings.h.
ShaderModelNotificationPtr
TWeakPtr<class SNotificationItem> URendererSettings::ShaderModelNotificationPtr private
Definition at line 1510 of file RendererSettings.h.
ToolTip [1/10]
UPROPERTY()) uint32 bLocalFogVolumeApplyOnTranslucent URendererSettings::ToolTip private
Initial value:
= "Set the level of foveation to apply when generating the Variable Rate Shading attachment. This feature is currently experimental.\nThis can yield some fairly significant performance benefits on GPUs that support Tier 2 VRS.\nLower settings will result in almost no discernible artifacting on most HMDs; higher settings will show some artifacts towards the edges of the view."))
    TEnumAsByte<EFixedFoveationLevels::Type> FoveationLevel
Definition at line 744 of file RendererSettings.h.
Referenced by UE_DEPRECATED(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
ToolTip [2/10]
URendererSettings::ToolTip private
Initial value:
= "Allows foveation level to adjust dynamically based on GPU utilization.\nLevel will range between none at the minimum, and the currently selected foveation level at the maximum."))
    uint32 bDynamicFoveation:1
Definition at line 750 of file RendererSettings.h.
ToolTip [3/10]
UPROPERTY()) TEnumAsByte< ECustomDepthStencil UPROPERTY() ")) uint32 bCustomDepthTaaJitter UPROPERTY () and propagate it through the renderer's post-processing chain. The legacy \"Linear color space only\" and \"Allow through tonemapper\" options now map to True and the engine keeps full alpha precision throughout post-processing. This feature can now be toggled without an engine restart.")) uint32 bEnableAlphaChannelInPostProcessing URendererSettings::ToolTip = "Enable primitive alpha holdout support in multiple deferred renderer passes. If primitive holdout masks are not to be used, keep this setting disabled for increased performance. Requires \"Alpha Output\" to be enabled." private
Definition at line 772 of file RendererSettings.h.
ToolTip [4/10]
UPROPERTY() ")) uint32 bDefaultFeatureBloom UPROPERTY () ")) uint32 bDefaultFeatureAmbientOcclusion URendererSettings::ToolTip private
Initial value:
= "Whether the default for AmbientOcclusionStaticFraction is enabled or not (only useful for baked lighting and if AO is on, allows to have SSAO affect baked lighting as well, costs performance, postprocess volume/camera/game setting can still override and enable or disable it independently)"))
    uint32 bDefaultFeatureAmbientOcclusionStaticFraction : 1
Definition at line 787 of file RendererSettings.h.
ToolTip [5/10]
UPROPERTY() ")) uint32 bDefaultFeatureMotionBlur URendererSettings::ToolTip private
Initial value:
= "Whether the default for LensFlare is enabled or not (postprocess volume/camera/game setting can still override and enable or disable it independently)"))
    uint32 bDefaultFeatureLensFlare : 1
Definition at line 829 of file RendererSettings.h.
ToolTip [6/10]
UPROPERTY()) uint32 bSingleLayerWaterUsesLightFunctionAtlas UPROPERTY()) uint32 bTranslucentUsesLightFunctionAtlas URendererSettings::ToolTip = "Enable IES profile evaluation on translucent materials when using the Forward Shading mode." private
Definition at line 1075 of file RendererSettings.h.
ToolTip [7/10]
UPROPERTY()) uint32 bGpuCrashDebugging UPROPERTY()) uint32 bMultiView UPROPERTY()) uint32 bMobilePostProcessing UPROPERTY()) uint32 bMobileMultiView UPROPERTY() rendering will use HW accelerated sRGB encoding/decoding. Available only on Oculus for now.")) uint32 bMobileUseHWsRGBEncoding UPROPERTY ()) uint32 bRoundRobinOcclusion UPROPERTY ()) uint32 bMeshStreaming URendererSettings::ToolTip = "Enable rendering with the heterogeneous volumes subsystem." private
Definition at line 1142 of file RendererSettings.h.
ToolTip [8/10]
UPROPERTY()) uint32 bSupportStationarySkylight UPROPERTY()) uint32 bSupportLowQualityLightmaps UPROPERTY()) uint32 bSupportPointLightWholeSceneShadows UPROPERTY()) uint32 bSupportTranslucentPerObjectShadow UPROPERTY()) uint32 bSupportCloudShadowOnSingleLayerWater URendererSettings::ToolTip = "Enable Substrate materials (Beta)." private
Definition at line 1211 of file RendererSettings.h.
ToolTip [9/10]
UPROPERTY()) uint32 SubstrateTranslucentMaterialRoughRefraction URendererSettings::ToolTip = "Enable advanced Substrate material debug visualization shaders. Base pass shaders can output such advanced data. Only available for Editors built for Win64 and running with the DX12 graphic API for now." private
Definition at line 1238 of file RendererSettings.h.
ToolTip [10/10]
UPROPERTY()) uint32 bMaterialRoughDiffuse UPROPERTY()) uint32 bMaterialEnergyConservation UPROPERTY()) uint32 bAutomaticallySetMaterialUsageInEditorDefault URendererSettings::ToolTip = "Enable support for Order-Independent-Transparency on translucent surfaces, which remove most of the sorting artifact among translucent surfaces." private
Definition at line 1284 of file RendererSettings.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/RendererSettings.h