Unreal Engine 5.6 C++ API: FAnimPhysState Class Reference
FAnimPhysState Class Reference
Defines a single closed, convex shape within the rigid body.
#include "AnimPhysicsSolver.h"
Public Member Functions
FAnimPhysState ()
FAnimPhysState (const FVector &InPosition, const FQuat &InOrient, const FVector &InLinearMomentum, const FVector &InAngularMomentum)
FAnimPhysPose & GetPose ()
const FAnimPhysPose & GetPose () const
FAnimPhysState & GetState ()
const FAnimPhysState & GetState () const
Data Fields
FVector AngularMomentum
FVector LinearMomentum
FAnimPhysPose Pose
Detailed Description
Defines a single closed, convex shape within the rigid body.
Definition at line 164 of file AnimPhysicsSolver.h.
Constructor & Destructor Documentation
FAnimPhysState() [1/2]
FAnimPhysState::FAnimPhysState ()
Referenced by GetState(), and GetState().
FAnimPhysState() [2/2]
FAnimPhysState::FAnimPhysState (const FVector & InPosition, const FQuat & InOrient, const FVector & InLinearMomentum, const FVector & InAngularMomentum)
References FVector.
Member Function Documentation
GetPose() [1/2]
FAnimPhysPose & FAnimPhysState::GetPose () inline
Definition at line 175 of file AnimPhysicsSolver.h.
References Pose.
GetPose() [2/2]
const FAnimPhysPose & FAnimPhysState::GetPose () const inline
Definition at line 176 of file AnimPhysicsSolver.h.
References Pose.
GetState() [1/2]
FAnimPhysState & FAnimPhysState::GetState () inline
Definition at line 178 of file AnimPhysicsSolver.h.
References FAnimPhysState().
GetState() [2/2]
const FAnimPhysState & FAnimPhysState::GetState () const inline
Definition at line 179 of file AnimPhysicsSolver.h.
References FAnimPhysState().
Field Documentation
AngularMomentum
FVector FAnimPhysState::AngularMomentum
Definition at line 173 of file AnimPhysicsSolver.h.
LinearMomentum
FVector FAnimPhysState::LinearMomentum
Definition at line 172 of file AnimPhysicsSolver.h.
Pose
FAnimPhysPose FAnimPhysState::Pose
Definition at line 170 of file AnimPhysicsSolver.h.
Referenced by GetPose(), and GetPose().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Animation/AnimPhysicsSolver.h