Unreal Engine 5.6 C++ API: FBoolProperty Class Reference
FBoolProperty Class Reference
#include "UnrealType.h"
Public Types
typedef bool TCppType
Public Types inherited from FField
typedef FField BaseFieldClass
typedef FFieldClass FieldTypeClass
using FLinkedListBuilder = TLinkedListBuilder<FField>
typedef FField Super
typedef FField ThisClass
Public Member Functions
FBoolProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
FBoolProperty (FFieldVariant InOwner, const UECodeGen_Private::FBoolPropertyParams &Prop)
Constructor used for constructing compiled in properties.
virtual void ClearValueInternal (void *Data) const override
virtual EConvertFromTypeResult ConvertFromType (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, const uint8 *Defaults) override
Allows a property to implement backwards compatibility handling for tagged properties.
virtual void CopyValuesInternal (void *Dest, void const *Src, int32 Count) const override
FORCEINLINE uint8 GetByteOffset () const
Return the byte offset from this property's storage type to the byte that FieldMask applies to.
virtual FString GetCPPMacroType (FString &ExtendedTypeText) const override
virtual FString GetCPPType (FString *ExtendedTypeText, uint32 CPPExportFlags) const override
FORCEINLINE uint8 GetFieldMask () const
Return the the mask that defines the relevant bit for this boolean, or 0xFF if IsNativeBool() is true.
virtual int32 GetMinAlignment () const override
FORCEINLINE bool GetOptionalPropertyValue (void const *B) const
FORCEINLINE bool GetOptionalPropertyValue_InContainer (void const *B, int32 ArrayIndex=0) const
FORCEINLINE bool GetPropertyValue (void const *A) const
FORCEINLINE bool GetPropertyValue_InContainer (void const *A, int32 ArrayIndex=0) const
uint32 GetValueTypeHashInternal (const void *Src) const override
virtual bool HasIntrusiveUnsetOptionalState () const override
virtual bool Identical (const void *A, const void *B, uint32 PortFlags) const override
virtual void InitializeValueInternal (void *Dest) const override
FORCEINLINE bool IsNativeBool () const
If the return value is true this FBoolProperty represents C++ bool type.
virtual void LinkInternal (FArchive &Ar) override
virtual bool NetSerializeItem (FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const override
virtual void PostDuplicate (const FField &InField) override
Fixups after duplicating a Field.
virtual void Serialize (FArchive &Ar) override
virtual void SerializeItem (FStructuredArchive::FSlot Slot, void *Value, void const *Defaults) const override
void SetBoolSize (const uint32 InSize, const bool bIsNativeBool=false, const uint32 InBitMask=0)
Sets the bitfield/bool type and size.
FORCEINLINE void SetPropertyValue (void *A, bool Value) const
FORCEINLINE void SetPropertyValue_InContainer (void *A, bool Value, int32 ArrayIndex=0) const
Public Member Functions inherited from FProperty
FProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithoutOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
void * AllocateAndInitializeValue () const
Allocates and initializes memory to hold a value this property represents.
virtual void CallGetter (const void *Container, void *OutValue) const
Calls the native getter function for this property.
virtual void CallSetter (void *Container, const void *InValue) const
Calls the native setter function for this property.
virtual bool CanSerializeFromTypeName (UE::FPropertyTypeName Type) const
Returns true if the type of this property matches the type name.
virtual void ClearIntrusiveOptionalValue (void *Data) const
Set the value to it's special unset state.
FORCEINLINE void ClearPropertyFlags (EPropertyFlags NewFlags)
FORCEINLINE void ClearValue (void *Data) const
Zeros the value for this property.
FORCEINLINE void ClearValue_InContainer (void *Data, int32 ArrayIndex=0) const
Zeros the value for this property.
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (UObject *ContainerPtr, int32 ArrayIndex=0) const
Get the pointer to property value in a supplied 'container'.
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (void const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void const *ContainerPtr, int32 ArrayIndex=0) const
bool ContainsFinishDestroy (TArray< const FStructProperty * > &EncounteredStructProps) const
Returns true if the property or any of the child properties should be cleared on FinishDestroy.
FORCEINLINE bool ContainsInstancedObjectProperty () const
Returns true if this property, or in the case of e.g.
virtual bool ContainsObjectReference (TArray< const FStructProperty * > &EncounteredStructProps, EPropertyObjectReferenceType InReferenceType=EPropertyObjectReferenceType::Strong) const
Returns true if this property, or in the case of e.g.
bool ContainsWeakObjectReference () const
Returns true if this property, or in the case of e.g.
FORCEINLINE void CopyCompleteValue (void *Dest, void const *Src) const
Copy the value for all elements of this property.
FORCEINLINE void CopyCompleteValue_InContainer (void *Dest, void const *Src) const
virtual void CopyCompleteValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueFromScriptVM_InContainer (void *OutContainer, void const *InValue) const
virtual void CopyCompleteValueToScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueToScriptVM_InContainer (void *OutValue, void const *InContainer) const
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
FORCEINLINE void CopySingleValue (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueToScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
void DestroyAndFreeValue (void *InMemory) const
Destroys and frees memory with a value this property represents.
FORCEINLINE void DestroyValue (void *Dest) const
Destroys the value for this property.
FORCEINLINE void DestroyValue_InContainer (void *Dest) const
Destroys the value for this property.
virtual void EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
virtual void EmitReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
bool ExportText_Direct (FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
FORCEINLINE bool ExportText_InContainer (int32 Index, FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_Direct (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_InContainer (FString &ValueStr, const void *Container, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void FinishDestroy (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
void FinishDestroy_InContainer (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
ELifetimeCondition GetBlueprintReplicationCondition () const
int32 GetElementSize () const
virtual FName GetID () const
FString GetNameCPP () const
Returns the C++ name of the property, including the _DEPRECATED suffix if the property is deprecated.
FORCEINLINE int32 GetOffset_ForDebug () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForGC () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForInternal () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForUFunction () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ReplaceWith_ContainerPtrToValuePtr () const
Return offset of property from container base.
FProperty * GetOwnerProperty ()
Returns the first FProperty in this property's Outer chain that does not have a FProperty for an Outer.
const FProperty * GetOwnerProperty () const
FORCEINLINE EPropertyFlags GetPropertyFlags () const
Returns this property's propertyflags.
FORCEINLINE FProperty * GetRepOwner ()
Returns the replication owner, which is the property itself, or NULL if this isn't important for replication.
void GetSingleValue_InContainer (const void *InContainer, void *OutValue, int32 ArrayIndex) const
Copies a single value to OutValue even if the property represents a static array of values.
FORCEINLINE int32 GetSize () const
FORCEINLINE void GetValue_InContainer (void const *InContainer, void *OutValue) const
virtual void * GetValueAddressAtIndex_Direct (const FProperty *Inner, void *InValueAddress, int32 Index) const
Gets value address at given index inside of a static array or container.
uint32 GetValueTypeHash (const void *Src) const
Returns the hash value for an element of this property.
FORCEINLINE bool HasAllPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAnyPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
virtual bool HasGetter () const
Checks if this property as a native getter function.
virtual bool HasSetter () const
Checks if this property as a native setter function.
virtual bool HasSetterOrGetter () const
Checks if this property as a native setter or getter function.
bool Identical_InContainer (const void *A, const void *B, int32 ArrayIndex=0, uint32 PortFlags=0) const
Determines whether the property values are identical.
const TCHAR * ImportText_Direct (const TCHAR *Buffer, void *PropertyPtr, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
const TCHAR * ImportText_InContainer (const TCHAR *Buffer, void *Container, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
virtual bool virtual HasIntrusiveUnsetOptionalState() const PURE_VIRTUAL(FProperty void InitializeIntrusiveUnsetOptionalValue (void *Data) const
Returns whether this type has a special state for an unset TOptional meaning the size TOptional<T> and T are the same.
FORCEINLINE void InitializeValue (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE void InitializeValue_InContainer (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
virtual void InstanceSubobjects (void *Data, void const *DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph *InstanceGraph)
Creates new copies of components.
FORCEINLINE bool IsEditorOnlyProperty () const
Editor-only properties are those that only are used with the editor is present or cannot be removed from serialisation.
FORCEINLINE bool IsInContainer (const UStruct *ContainerClass) const
See if the offset of this property is below the supplied container size.
FORCEINLINE bool IsInContainer (int32 ContainerSize) const
See if the offset of this property is below the supplied container size.
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const
Returns whether an optional value of this inner type is unset.
int32 Link (FArchive &Ar)
void LinkWithoutChangingOffset (FArchive &Ar)
virtual bool LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag *Tag=nullptr)
Restores this property and its owned properties from the type name.
void PerformOperationWithGetter (void *OutContainer, const void *DirectPropertyAddress, TFunctionRef< void(const void *)> DirectValueAccessFunc) const
Helper function for getting container / struct property value and performing operation directly on the value memory.
void PerformOperationWithSetter (void *OutContainer, void *DirectPropertyAddress, TFunctionRef< void(void *)> DirectValueAccessFunc) const
Helper function for setting container / struct property value and performing operation directly on the value memory.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const
Attempt to resolve the given inner path info against this outer property to get the inner property value.
virtual bool SameType (const FProperty *Other) const
returns true, if Other is property of exactly the same type
virtual void SaveTypeName (UE::FPropertyTypeNameBuilder &Type) const
Saves the type name of this property and its owned properties.
void SerializeBinProperty (FStructuredArchive::FSlot Slot, void *Data, int32 ArrayIdx=-1)
Serializes the property with the struct's data residing in Data.
void SerializeNonMatchingBinProperty (FStructuredArchive::FSlot Slot, void *Data, void const *DefaultData, UStruct *DefaultStruct)
Serializes the property with the struct's data residing in Data, unless it matches the default.
void SetBlueprintReplicationCondition (ELifetimeCondition InBlueprintReplicationCondition)
void SetElementSize (int32 NewSize)
FORCEINLINE void SetPropertyFlags (EPropertyFlags NewFlags)
void SetSingleValue_InContainer (void *OutContainer, const void *InValue, int32 ArrayIndex) const
Copies a single value to the property even if the property represents a static array of values.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const void *InValue) const
bool ShouldDuplicateValue () const
Determines whether this property value is eligible for copying when duplicating an object.
bool ShouldPort (uint32 PortFlags=0) const
bool ShouldSerializeValue (FArchive &Ar) const
virtual bool SupportsNetSharedSerialization () const
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow Visit(const FPropertyVisitorData &Data
virtual bool UseBinaryOrNativeSerialization (const FArchive &Ar) const
bool ValidateImportFlags (uint32 PortFlags, FOutputDevice *ErrorText=NULL) const
Verify that modifying this property's value via ImportText is allowed.
EPropertyVisitorControlFlow Visit (const FPropertyVisitorData &Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from FField
FField (EInternal InInernal, FFieldClass *InClass)
FField (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
virtual ~FField ()
virtual void AddCppProperty (FProperty *Property)
virtual void AddReferencedObjects (FReferenceCollector &Collector)
void AppendName (FString &ResultString) const
virtual void BeginDestroy ()
virtual void Bind ()
void ClearFlags (EObjectFlags NewFlags)
FString GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
uint64 GetCastFlags () const
FFieldClass * GetClass () const
virtual SIZE_T GetFieldSize () const
EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
FString GetFullName () const
virtual FField * GetInnerFieldByName (const FName &InName)
Returns an inner field by name if the field has any.
virtual void GetInnerFields (TArray< FField * > &OutFields)
Fills the provided array with all inner fields this field owns (recursively)
FLinkerLoad * GetLinker () const
FORCEINLINE FString GetName () const
FORCEINLINE void GetName (FString &OutName) const
UPackage * GetOutermost () const
Goes up the outer chain to look for the outermost package.
template<typename T>
T * GetOwner () const
template<typename T>
FUNCTION_NON_NULL_RETURN_START T * GetOwnerChecked () const FUNCTION_NON_NULL_RETURN_END
UClass * GetOwnerClass () const
Goes up the outer chain to look for a UClass.
UStruct * GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
UField * GetOwnerUField () const
Goes up the outer chain to look for a UField.
FORCEINLINE UObject * GetOwnerUObject () const
Goes up the outer chain to look for a UObject.
FFieldVariant GetOwnerVariant () const
Gets the owner container for this field.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=nullptr) const
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
template<typename T>
T * GetTypedOwner () const
FField * GetTypedOwner (FFieldClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
UObject * GetTypedOwner (UClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE UObject * InternalGetOwnerAsUObjectUnsafe () const
Internal function for quickly getting the owner of this object as UObject.
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *FieldType) const
bool IsIn (const FField *InOwner) const
bool IsIn (const UObject *InOwner) const
bool IsNative () const
bool IsRooted () const
bool IsValidLowLevel () const
virtual void PostLoad ()
void Rename (const FName &NewName)
void SetFlags (EObjectFlags NewFlags)
UE_DEPRECATED (5.0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAllCastFlags(const uint64 InCastFlags) const
UE_DEPRECATED (5.0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAnyCastFlags(const uint64 InCastFlags) const
Static Public Member Functions
static FORCEINLINE bool GetDefaultPropertyValue ()
Static Public Member Functions inherited from FProperty
static FName FindRedirectedPropertyName (const UStruct *ObjectStruct, FName OldName)
Gets a redirected property name, will return NAME_None if no redirection was found.
static const TCHAR * ImportSingleProperty (const TCHAR *Str, void *DestData, const UStruct *ObjectStruct, UObject *SubobjectOuter, int32 PortFlags, FOutputDevice *Warn, TArray< struct FDefinedProperty > &DefinedProperties)
parses and imports a text definition of a single property's value (if array, may be an individual element) also includes parsing of special operations for array properties (Add/Remove/RemoveIndex/Empty)
Static Public Member Functions inherited from FField
static FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given its class.
static FField * Construct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given the name of its class.
static FField * Duplicate (const FField *InField, FFieldVariant DestOwner, const FName DestName=NAME_None, EObjectFlags FlagMask=RF_AllFlags, EInternalObjectFlags InternalFlagsMask=EInternalObjectFlags_AllFlags)
Duplicates an FField.
static FName GenerateFFieldName (FFieldVariant InOwner, FFieldClass *InClass)
Generates a name for a Field of a given type.
static FFieldClass * StaticClass ()
static constexpr uint64 StaticClassCastFlags ()
static constexpr uint64 StaticClassCastFlagsPrivate ()
static FField * TryConstruct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Tries to construct a new field given the name of its class.
Protected Member Functions
virtual void ExportText_Internal (FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const override
virtual const TCHAR * ImportText_Internal (const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject *Parent, int32 PortFlags, FOutputDevice *ErrorText) const override
Protected Member Functions inherited from FProperty
virtual bool ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > &EncounteredStructProps) const
virtual void DestroyValueInternal (void *Dest) const
virtual void FinishDestroyInternal (void *Data) const
void Init ()
Initializes internal state.
FORCEINLINE void * PointerToValuePtr (void const *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, int32 ArrayIndex=0) const
void SetOffset_Internal (int32 NewOffset)
Set the alignment offset for this property - added for FMapProperty.
Protected Member Functions inherited from FField
void SetFlagsTo (EObjectFlags NewFlags)
Set the object flags directly.
Private Attributes
uint8 ByteMask
Mask of the byte with the property value.
DECLARE_FIELD_API(FBoolProperty, FProperty, CASTCLASS_FBoolProperty, 1) private uint8 ByteOffset
Size of the bitfield/bool property.
uint8 FieldMask
Mask of the field with the property value.
Additional Inherited Members
Data Fields inherited from FProperty
const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc const
FProperty * DestructorLinkNext
In memory only: Linked list of properties requiring destruction.
virtual FString GetCPPType (FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const PURE_VIRTUAL(FProperty
Returns the text to use for exporting this property to header file.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags=0) const PURE_VIRTUAL(FProperty
Determines whether the property values are identical.
virtual void virtual SerializeItem(FStructuredArchive::FSlot Slot, void *Value, void const *Defaults=NULL) const PURE_VIRTUAL(FProperty boo NetSerializeItem)(FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const
FProperty * NextRef
In memory only: Linked list of object reference properties from most-derived to base.
FProperty * PostConstructLinkNext
In memory only: Linked list of properties requiring post constructor initialization.
EPropertyFlags PropertyFlags
FProperty * PropertyLinkNext
In memory only: Linked list of properties from most-derived to base.
uint16 RepIndex
FName RepNotifyFunc
Data Fields inherited from FField
EObjectFlags FlagsPrivate
Object flags.
FName NamePrivate
Name of this field.
FField * Next
Next Field in the linked list.
FFieldVariant Owner
Owner of this field.
Protected Attributes inherited from FProperty
virtual void virtual ExportText_Internal(FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const PURE_VIRTUAL(FProperty const TCHAR ImportText_Internal)(const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const PURE_VIRTUAL(FProperty
Detailed Description
Definition at line 2374 of file UnrealType.h.
Member Typedef Documentation
TCppType
typedef bool FBoolProperty::TCppType
Definition at line 2438 of file UnrealType.h.
Constructor & Destructor Documentation
FBoolProperty() [1/2]
FBoolProperty::FBoolProperty (FFieldVariant InOwner, const FName & InName, EObjectFlags InObjectFlags)
References InName, and UE_API.
Referenced by FBoolProperty().
FBoolProperty() [2/2]
FBoolProperty::FBoolProperty (FFieldVariant InOwner, const UECodeGen_Private::FBoolPropertyParams & Prop)
Constructor used for constructing compiled in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
References FBoolProperty(), and UE_API.
Member Function Documentation
ClearValueInternal()
virtual void FBoolProperty::ClearValueInternal (void * Data) const override virtual
Reimplemented from FProperty.
References UE_API.
ConvertFromType()
virtual EConvertFromTypeResult FBoolProperty::ConvertFromType (const FPropertyTag & Tag, FStructuredArchive::FSlot Slot, uint8 * Data, UStruct * DefaultsStruct, const uint8 * Defaults) override virtual
Allows a property to implement backwards compatibility handling for tagged properties.
Parameters
Tag property tag of the loading data
Ar the archive the data is being loaded from
Data a pointer to the container to write the loaded data to
DefaultsStruct
Defaults if available, a pointer to the container containing the default value for this property, or null
Returns
A state which tells the tagged property system how the property dealt with the data. Converted: the function handled conversion. CannotConvert: the tag is not something that the property can convert. Serialized: the function handled serialization without conversion. UseSerializeItem: no conversion was done on the property - this can mean that the tag is correct and normal serialization applies or that the tag is incompatible.
Reimplemented from FProperty.
References UE_API.
CopyValuesInternal()
virtual void FBoolProperty::CopyValuesInternal (void * Dest, void const * Src, int32 Count) const override virtual
Reimplemented from FProperty.
References Count, and UE_API.
ExportText_Internal()
virtual void FBoolProperty::ExportText_Internal (FString & ValueStr, const void * PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const override protected virtual
References Parent, and UE_API.
GetByteOffset()
FORCEINLINE uint8 FBoolProperty::GetByteOffset () const inline
Return the byte offset from this property's storage type to the byte that FieldMask applies to.
Only valid if IsNativeBool() is true.
Definition at line 2497 of file UnrealType.h.
References ByteOffset, and FORCEINLINE.
GetCPPMacroType()
virtual FString FBoolProperty::GetCPPMacroType (FString & ExtendedTypeText) const override virtual
Reimplemented from FProperty.
References UE_API.
GetCPPType()
virtual FString FBoolProperty::GetCPPType (FString * ExtendedTypeText, uint32 CPPExportFlags) const override virtual
References UE_API.
GetDefaultPropertyValue()
FORCEINLINE bool FBoolProperty::GetDefaultPropertyValue () inline static
Definition at line 2449 of file UnrealType.h.
References FORCEINLINE.
Referenced by GetOptionalPropertyValue(), and GetOptionalPropertyValue_InContainer().
GetFieldMask()
FORCEINLINE uint8 FBoolProperty::GetFieldMask () const inline
Return the the mask that defines the relevant bit for this boolean, or 0xFF if IsNativeBool() is true.
Definition at line 2491 of file UnrealType.h.
References FieldMask, and FORCEINLINE.
GetMinAlignment()
virtual int32 FBoolProperty::GetMinAlignment () const override virtual
Reimplemented from FProperty.
References UE_API.
GetOptionalPropertyValue()
FORCEINLINE bool FBoolProperty::GetOptionalPropertyValue (void const * B) const inline
Definition at line 2453 of file UnrealType.h.
References B, FORCEINLINE, GetDefaultPropertyValue(), and GetPropertyValue().
GetOptionalPropertyValue_InContainer()
FORCEINLINE bool FBoolProperty::GetOptionalPropertyValue_InContainer (void const * B, int32 ArrayIndex = 0) const inline
Definition at line 2457 of file UnrealType.h.
References B, FORCEINLINE, GetDefaultPropertyValue(), and GetPropertyValue_InContainer().
GetPropertyValue()
FORCEINLINE bool FBoolProperty::GetPropertyValue (void const * A) const inline
Definition at line 2439 of file UnrealType.h.
References A, ByteOffset, check, FieldMask, and FORCEINLINE.
Referenced by GetOptionalPropertyValue(), and GetPropertyValue_InContainer().
GetPropertyValue_InContainer()
FORCEINLINE bool FBoolProperty::GetPropertyValue_InContainer (void const * A, int32 ArrayIndex = 0) const inline
Definition at line 2445 of file UnrealType.h.
References A, FProperty::ContainerPtrToValuePtr(), FORCEINLINE, and GetPropertyValue().
Referenced by GetOptionalPropertyValue_InContainer().
GetValueTypeHashInternal()
uint32 FBoolProperty::GetValueTypeHashInternal (const void * Src) const override virtual
Reimplemented from FProperty.
References UE_API.
HasIntrusiveUnsetOptionalState()
virtual bool FBoolProperty::HasIntrusiveUnsetOptionalState () const inline override virtual
Definition at line 2504 of file UnrealType.h.
Identical()
virtual bool FBoolProperty::Identical (const void * A, const void * B, uint32 PortFlags) const override virtual
References A, B, and UE_API.
ImportText_Internal()
virtual const TCHAR * FBoolProperty::ImportText_Internal (const TCHAR * Buffer, void * ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject * Parent, int32 PortFlags, FOutputDevice * ErrorText) const override protected virtual
References Buffer, Parent, and UE_API.
InitializeValueInternal()
virtual void FBoolProperty::InitializeValueInternal (void * Dest) const override virtual
Reimplemented from FProperty.
References UE_API.
IsNativeBool()
FORCEINLINE bool FBoolProperty::IsNativeBool () const inline
If the return value is true this FBoolProperty represents C++ bool type.
Definition at line 2485 of file UnrealType.h.
References FieldMask, and FORCEINLINE.
LinkInternal()
virtual void FBoolProperty::LinkInternal (FArchive & Ar) override virtual
Reimplemented from FProperty.
References Ar, and UE_API.
NetSerializeItem()
virtual bool FBoolProperty::NetSerializeItem (FArchive & Ar, UPackageMap * Map, void * Data, TArray< uint8 > * MetaData = NULL) const override virtual
References Ar, Map, MetaData, and UE_API.
PostDuplicate()
virtual void FBoolProperty::PostDuplicate (const FField & InField) override virtual
Fixups after duplicating a Field.
Reimplemented from FProperty.
References FField::FField(), and UE_API.
Serialize()
virtual void FBoolProperty::Serialize (FArchive & Ar) override virtual
Reimplemented from FProperty.
References Ar, and UE_API.
SerializeItem()
virtual void FBoolProperty::SerializeItem (FStructuredArchive::FSlot Slot, void * Value, void const * Defaults) const override virtual
References UE_API, and Value.
SetBoolSize()
void FBoolProperty::SetBoolSize (const uint32 InSize, const bool bIsNativeBool = false, const uint32 InBitMask = 0)
Sets the bitfield/bool type and size.
This function must be called before FBoolProperty can be used.
Parameters
InSize size of the bitfield/bool type.
bIsNativeBool true if this property represents C++ bool type.
References UE_API.
SetPropertyValue()
FORCEINLINE void FBoolProperty::SetPropertyValue (void * A, bool Value) const inline
Definition at line 2461 of file UnrealType.h.
References A, ByteMask, ByteOffset, check, FieldMask, FORCEINLINE, and Value.
Referenced by SetPropertyValue_InContainer().
SetPropertyValue_InContainer()
FORCEINLINE void FBoolProperty::SetPropertyValue_InContainer (void * A, bool Value, int32 ArrayIndex = 0) const inline
Definition at line 2467 of file UnrealType.h.
References A, FProperty::ContainerPtrToValuePtr(), FORCEINLINE, SetPropertyValue(), and Value.
Field Documentation
ByteMask
uint8 FBoolProperty::ByteMask private
Mask of the byte with the property value.
Definition at line 2386 of file UnrealType.h.
Referenced by SetPropertyValue().
ByteOffset
DECLARE_FIELD_API (FBoolProperty, FProperty, CASTCLASS_FBoolProperty, 1) private uint8 FBoolProperty::ByteOffset private
Size of the bitfield/bool property.
Equal to ElementSize but used to check if the property has been properly initialized (0-8, where 0 means uninitialized). Offset from the memeber variable to the byte of the property (0-7).
Definition at line 2384 of file UnrealType.h.
Referenced by GetByteOffset(), GetPropertyValue(), and SetPropertyValue().
FieldMask
uint8 FBoolProperty::FieldMask private
Mask of the field with the property value.
Either equal to ByteMask or 255 in case of 'bool' type.
Definition at line 2388 of file UnrealType.h.
Referenced by GetFieldMask(), GetPropertyValue(), IsNativeBool(), and SetPropertyValue().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h