Unreal Engine 5.6 C++ API: FViewAlignedSculptBrushOp Class Reference
FViewAlignedSculptBrushOp Class Reference
#include "MeshSculptBrushOps.h"
Public Types
typedef TUniqueFunction< bool(int32, const FVector3d &, double, FVector3d &, FVector3d &)> NearestQueryFuncType
Public Types inherited from FMeshSculptBrushOp
enum class EBrushRegionType { LocalSphere , InfiniteCylinder , CylinderOnSphere }
enum class EReferencePlaneType { None , InitialROI , InitialROI_ViewAligned , WorkPlane }
enum class EStampAlignmentType { HitNormal , Camera , ReferencePlane , ReferenceSphere }
Public Member Functions
FViewAlignedSculptBrushOp (NearestQueryFuncType QueryFunc)
virtual void ApplyStamp (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) override
virtual bool GetAlignStampToView () const override
virtual ESculptBrushOpTargetType GetBrushTargetType () const override
virtual bool SupportsVariableSpacing () const override
virtual bool UsesAlpha () const override
Public Member Functions inherited from FMeshSculptBrushOp
virtual ~FMeshSculptBrushOp ()
virtual void BeginStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &InitialVertices)
virtual void CancelStroke ()
virtual void ConfigureOptions (const FSculptBrushOptions &Options)
virtual void EndStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &FinalVertices)
virtual EBrushRegionType GetBrushRegionType () const
const FMeshSculptFallofFunc & GetFalloff () const
template<typename PropType>
PropType * GetPropertySetAs ()
template<typename PropType>
const PropType * GetPropertySetAs () const
virtual EReferencePlaneType GetReferencePlaneType () const
virtual EStampAlignmentType GetStampAlignmentType () const
virtual bool IgnoreZeroMovements () const
virtual bool UseLastStampFrameOnZeroMovement () const
virtual bool WantsStampRegionPlane () const
Data Fields
NearestQueryFuncType BaseMeshNearestQueryFunc
double BrushSpeedTuning = 6.0
Data Fields inherited from FMeshSculptBrushOp
FSculptBrushOptions CurrentOptions
TSharedPtr< FMeshSculptFallofFunc > Falloff
TWeakObjectPtr< UMeshSculptBrushOpProps > PropertySet
Detailed Description
Definition at line 115 of file MeshSculptBrushOps.h.
Member Typedef Documentation
NearestQueryFuncType
typedef TUniqueFunction<bool(int32, const FVector3d&, double, FVector3d&, FVector3d&)> FViewAlignedSculptBrushOp::NearestQueryFuncType
Definition at line 120 of file MeshSculptBrushOps.h.
Constructor & Destructor Documentation
FViewAlignedSculptBrushOp()
FViewAlignedSculptBrushOp::FViewAlignedSculptBrushOp (NearestQueryFuncType QueryFunc) inline
Definition at line 124 of file MeshSculptBrushOps.h.
References BaseMeshNearestQueryFunc, and MoveTemp().
Member Function Documentation
ApplyStamp()
virtual void FViewAlignedSculptBrushOp::ApplyStamp (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) inline override virtual
Implements FMeshSculptBrushOp.
Definition at line 147 of file MeshSculptBrushOps.h.
References BrushSpeedTuning, FSculptBrushStamp::DeltaTime, FSculptBrushStamp::Direction, FSculptBrushStamp::HasAlpha(), FSculptBrushStamp::LocalFrame, Mesh, ParallelFor(), FSculptBrushStamp::Power, FSculptBrushStamp::Radius, and UE::Geometry::TFrame3< RealType >::Z().
GetAlignStampToView()
virtual bool FViewAlignedSculptBrushOp::GetAlignStampToView () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 134 of file MeshSculptBrushOps.h.
GetBrushTargetType()
virtual ESculptBrushOpTargetType FViewAlignedSculptBrushOp::GetBrushTargetType () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 129 of file MeshSculptBrushOps.h.
References TargetMesh.
SupportsVariableSpacing()
virtual bool FViewAlignedSculptBrushOp::SupportsVariableSpacing () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 138 of file MeshSculptBrushOps.h.
UsesAlpha()
virtual bool FViewAlignedSculptBrushOp::UsesAlpha () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 142 of file MeshSculptBrushOps.h.
Field Documentation
BaseMeshNearestQueryFunc
NearestQueryFuncType FViewAlignedSculptBrushOp::BaseMeshNearestQueryFunc
Definition at line 122 of file MeshSculptBrushOps.h.
Referenced by FViewAlignedSculptBrushOp().
BrushSpeedTuning
double FViewAlignedSculptBrushOp::BrushSpeedTuning = 6.0
Definition at line 118 of file MeshSculptBrushOps.h.
Referenced by ApplyStamp().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/MeshModelingTools/Public/Sculpting/MeshSculptBrushOps.h