Unreal Engine 5.6 C++ API: UE::Sequencer::TFlagStateCacheExtension< FlagsType > Class Template Reference
UE::Sequencer::TFlagStateCacheExtension< FlagsType > Class Template Reference abstract
#include "HierarchicalCacheExtension.h"
Public Types
using Implements = TImplements<IDynamicExtension, IHierarchicalCache>
Public Member Functions
virtual ~TFlagStateCacheExtension ()
FlagsType GetCachedFlags (const FViewModelPtr &ViewModel) const
FlagsType GetCachedFlags (uint32 InModelID) const
FlagsType GetRootFlags () const
Public Member Functions inherited from UE::Sequencer::IDynamicExtension
virtual void OnCreated (TSharedRef< FViewModel > InWeakOwner)
Called when the extension is created on a data model.
virtual void OnPostInitialize ()
Called after all extensions have been created on a data model.
virtual void OnReinitialize ()
Called to reinitialize extensions after a major change.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDynamicExtension) virtual ~IDynamicExtension()
Public Member Functions inherited from TSharedFromThis< IDynamicExtension >
TSharedRef< IDynamicExtension, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDynamicExtension, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::IHierarchicalCache
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IHierarchicalCache) virtual ~IHierarchicalCache()
Protected Member Functions
void BeginUpdate () override
void EndUpdate () override
void PostVisitChildren (const FViewModelPtr &ViewModel) override
void PreVisitChildren (const FViewModelPtr &ViewModel) override
Protected Member Functions inherited from TSharedFromThis< IDynamicExtension >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TArray< FlagsType > AccumulatedChildFlags
TMap< uint32, FlagsType > CachedFlagsFromNodeID
TArray< FlagsType > IndividualItemFlags
FlagsType RootFlags
Private Member Functions
virtual FlagsType ComputeFlagsForModel (const FViewModelPtr &ViewModel)=0
virtual void PostComputeChildrenFlags (const FViewModelPtr &ViewModel, FlagsType &OutThisModelFlags, FlagsType &OutPropagateToParentFlags)
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDynamicExtension >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename FlagsType>
class UE::Sequencer::TFlagStateCacheExtension< FlagsType >
Definition at line 73 of file HierarchicalCacheExtension.h.
Member Typedef Documentation
Implements
template<typename FlagsType> using UE::Sequencer::TFlagStateCacheExtension< FlagsType >::Implements = TImplements<IDynamicExtension, IHierarchicalCache>
Definition at line 79 of file HierarchicalCacheExtension.h.
Constructor & Destructor Documentation
~TFlagStateCacheExtension()
template<typename FlagsType> virtual UE::Sequencer::TFlagStateCacheExtension< FlagsType >::~TFlagStateCacheExtension () inline virtual
Definition at line 81 of file HierarchicalCacheExtension.h.
Member Function Documentation
BeginUpdate()
template<typename FlagsType> void UE::Sequencer::TFlagStateCacheExtension< FlagsType >::BeginUpdate () inline override protected virtual
Implements UE::Sequencer::IHierarchicalCache.
Definition at line 103 of file HierarchicalCacheExtension.h.
References AccumulatedChildFlags, CachedFlagsFromNodeID, and IndividualItemFlags.
ComputeFlagsForModel()
template<typename FlagsType> virtual FlagsType UE::Sequencer::TFlagStateCacheExtension< FlagsType >::ComputeFlagsForModel (const FViewModelPtr & ViewModel) private pure virtual
Implemented in UE::Sequencer::FDeactiveStateCacheExtension, and UE::Sequencer::FMuteStateCacheExtension.
Referenced by PreVisitChildren().
EndUpdate()
template<typename FlagsType> void UE::Sequencer::TFlagStateCacheExtension< FlagsType >::EndUpdate () inline override protected virtual
Implements UE::Sequencer::IHierarchicalCache.
Definition at line 130 of file HierarchicalCacheExtension.h.
References AccumulatedChildFlags, CachedFlagsFromNodeID, IndividualItemFlags, and RootFlags.
GetCachedFlags() [1/2]
template<typename FlagsType> FlagsType UE::Sequencer::TFlagStateCacheExtension< FlagsType >::GetCachedFlags (const FViewModelPtr & ViewModel) const inline
Definition at line 87 of file HierarchicalCacheExtension.h.
References GetCachedFlags(), and UE::Sequencer::FViewModel::GetModelID().
Referenced by GetCachedFlags().
GetCachedFlags() [2/2]
template<typename FlagsType> FlagsType UE::Sequencer::TFlagStateCacheExtension< FlagsType >::GetCachedFlags (uint32 InModelID) const inline
Definition at line 91 of file HierarchicalCacheExtension.h.
References CachedFlagsFromNodeID.
GetRootFlags()
template<typename FlagsType> FlagsType UE::Sequencer::TFlagStateCacheExtension< FlagsType >::GetRootFlags () const inline
Definition at line 83 of file HierarchicalCacheExtension.h.
References RootFlags.
PostComputeChildrenFlags()
template<typename FlagsType> virtual void UE::Sequencer::TFlagStateCacheExtension< FlagsType >::PostComputeChildrenFlags (const FViewModelPtr & ViewModel, FlagsType & OutThisModelFlags, FlagsType & OutPropagateToParentFlags) inline private virtual
Reimplemented in UE::Sequencer::FDeactiveStateCacheExtension, and UE::Sequencer::FMuteStateCacheExtension.
Definition at line 99 of file HierarchicalCacheExtension.h.
Referenced by PostVisitChildren().
PostVisitChildren()
template<typename FlagsType> void UE::Sequencer::TFlagStateCacheExtension< FlagsType >::PostVisitChildren (const FViewModelPtr & ViewModel) inline override protected virtual
Implements UE::Sequencer::IHierarchicalCache.
Definition at line 115 of file HierarchicalCacheExtension.h.
References AccumulatedChildFlags, CachedFlagsFromNodeID, UE::Sequencer::CombinePropagatedChildFlags(), UE::Sequencer::FViewModel::GetModelID(), IndividualItemFlags, and PostComputeChildrenFlags().
PreVisitChildren()
template<typename FlagsType> void UE::Sequencer::TFlagStateCacheExtension< FlagsType >::PreVisitChildren (const FViewModelPtr & ViewModel) inline override protected virtual
Implements UE::Sequencer::IHierarchicalCache.
Definition at line 109 of file HierarchicalCacheExtension.h.
References AccumulatedChildFlags, ComputeFlagsForModel(), and IndividualItemFlags.
Field Documentation
AccumulatedChildFlags
template<typename FlagsType> TArray<FlagsType> UE::Sequencer::TFlagStateCacheExtension< FlagsType >::AccumulatedChildFlags protected
Definition at line 141 of file HierarchicalCacheExtension.h.
Referenced by BeginUpdate(), EndUpdate(), PostVisitChildren(), and PreVisitChildren().
CachedFlagsFromNodeID
template<typename FlagsType> TMap<uint32, FlagsType> UE::Sequencer::TFlagStateCacheExtension< FlagsType >::CachedFlagsFromNodeID protected
Definition at line 143 of file HierarchicalCacheExtension.h.
Referenced by BeginUpdate(), EndUpdate(), GetCachedFlags(), and PostVisitChildren().
IndividualItemFlags
template<typename FlagsType> TArray<FlagsType> UE::Sequencer::TFlagStateCacheExtension< FlagsType >::IndividualItemFlags protected
Definition at line 142 of file HierarchicalCacheExtension.h.
Referenced by BeginUpdate(), EndUpdate(), PostVisitChildren(), and PreVisitChildren().
RootFlags
template<typename FlagsType> FlagsType UE::Sequencer::TFlagStateCacheExtension< FlagsType >::RootFlags protected
Definition at line 144 of file HierarchicalCacheExtension.h.
Referenced by EndUpdate(), and GetRootFlags().
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/HierarchicalCacheExtension.h