Unreal Engine 5.6 C++ API: IAnimBlueprintNodeCopyTermDefaultsContext Class Reference
IAnimBlueprintNodeCopyTermDefaultsContext Class Reference abstract
#include "IAnimBlueprintCopyTermDefaultsContext.h"
Public Member Functions
virtual ~IAnimBlueprintNodeCopyTermDefaultsContext ()=default
UObject * GetClassDefaultObject () const
template<typename NodeType>
NodeType & GetDestinationNode () const
uint8 * GetDestinationPtr () const
int32 GetNodePropertyIndex () const
template<typename NodeType>
const NodeType & GetSourceNode () const
const uint8 * GetSourcePtr () const
const FProperty * GetTargetProperty () const
Protected Member Functions
virtual UObject * GetClassDefaultObjectImpl () const =0
virtual uint8 * GetDestinationPtrImpl () const =0
virtual int32 GetNodePropertyIndexImpl () const =0
virtual const uint8 * GetSourcePtrImpl () const =0
virtual const FProperty * GetTargetPropertyImpl () const =0
Detailed Description
Definition at line 33 of file IAnimBlueprintCopyTermDefaultsContext.h.
Constructor & Destructor Documentation
~IAnimBlueprintNodeCopyTermDefaultsContext()
virtual IAnimBlueprintNodeCopyTermDefaultsContext::~IAnimBlueprintNodeCopyTermDefaultsContext () virtual default
Member Function Documentation
GetClassDefaultObject()
UObject * IAnimBlueprintNodeCopyTermDefaultsContext::GetClassDefaultObject () const inline
Definition at line 39 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetClassDefaultObjectImpl().
GetClassDefaultObjectImpl()
virtual UObject * IAnimBlueprintNodeCopyTermDefaultsContext::GetClassDefaultObjectImpl () const protected pure virtual
Referenced by GetClassDefaultObject().
GetDestinationNode()
template<typename NodeType> NodeType & IAnimBlueprintNodeCopyTermDefaultsContext::GetDestinationNode () const inline
Definition at line 64 of file IAnimBlueprintCopyTermDefaultsContext.h.
References CastFieldChecked(), check, GetDestinationPtr(), and GetTargetProperty().
GetDestinationPtr()
uint8 * IAnimBlueprintNodeCopyTermDefaultsContext::GetDestinationPtr () const inline
Definition at line 45 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetDestinationPtrImpl().
Referenced by GetDestinationNode().
GetDestinationPtrImpl()
virtual uint8 * IAnimBlueprintNodeCopyTermDefaultsContext::GetDestinationPtrImpl () const protected pure virtual
Referenced by GetDestinationPtr().
GetNodePropertyIndex()
int32 IAnimBlueprintNodeCopyTermDefaultsContext::GetNodePropertyIndex () const inline
Definition at line 51 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetNodePropertyIndexImpl().
GetNodePropertyIndexImpl()
virtual int32 IAnimBlueprintNodeCopyTermDefaultsContext::GetNodePropertyIndexImpl () const protected pure virtual
Referenced by GetNodePropertyIndex().
GetSourceNode()
template<typename NodeType> const NodeType & IAnimBlueprintNodeCopyTermDefaultsContext::GetSourceNode () const inline
Definition at line 55 of file IAnimBlueprintCopyTermDefaultsContext.h.
References CastFieldChecked(), check, GetSourcePtr(), and GetTargetProperty().
GetSourcePtr()
const uint8 * IAnimBlueprintNodeCopyTermDefaultsContext::GetSourcePtr () const inline
Definition at line 48 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetSourcePtrImpl().
Referenced by GetSourceNode().
GetSourcePtrImpl()
virtual const uint8 * IAnimBlueprintNodeCopyTermDefaultsContext::GetSourcePtrImpl () const protected pure virtual
Referenced by GetSourcePtr().
GetTargetProperty()
const FProperty * IAnimBlueprintNodeCopyTermDefaultsContext::GetTargetProperty () const inline
Definition at line 42 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetTargetPropertyImpl().
Referenced by GetDestinationNode(), and GetSourceNode().
GetTargetPropertyImpl()
virtual const FProperty * IAnimBlueprintNodeCopyTermDefaultsContext::GetTargetPropertyImpl () const protected pure virtual
Referenced by GetTargetProperty().
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/IAnimBlueprintCopyTermDefaultsContext.h