Unreal Engine 5.6 C++ API: FScreenPS Class Reference
FScreenPS Class Reference
A pixel shader for rendering a textured screen element.
#include "ScreenRendering.h"
Public Member Functions
FScreenPS ()
FScreenPS (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, const FTexture *Texture)
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, FRHISamplerState *SamplerStateRHI, FRHITexture *TextureRHI)
Public Member Functions inherited from FGlobalShader
FGlobalShader ()=default
RENDERCORE_API FGlobalShader (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
template<typename TViewUniformShaderParameters>
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, FRHIUniformBuffer *ViewUniformBuffer)
Public Member Functions inherited from FShader
RENDERCORE_API FShader ()
Used to construct a shader for deserialization.
RENDERCORE_API FShader (const CompiledShaderInitializerType &Initializer)
Construct a shader from shader compiler output.
RENDERCORE_API ~FShader ()
RENDERCORE_API void DumpDebugInfo (const FShaderMapPointerTable &InPtrTable)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API const FShaderParametersMetadata * FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
uint32 GetCodeSize () const
EShaderFrequency GetFrequency () const
RENDERCORE_API const FSHAHash & GetHash () const
Returns the hash of the shader file that this shader was compiled with.
uint32 GetNumInstructions () const
uint32 GetNumTextureSamplers () const
RENDERCORE_API const FSHAHash & GetOutputHash () const
int32 GetResourceIndex () const
EShaderPlatform GetShaderPlatform () const
uint32 GetSortKey () const
Returns an identifier suitable for deterministic sorting of shaders between sessions.
const FShaderTarget GetTarget () const
FShaderType * GetType (const FPointerTableBase *InPointerTable) const
FShaderType * GetType (const FShaderMapPointerTable &InPointerTable) const
FShaderType * GetTypeUnfrozen () const
template<typename UniformBufferStructType>
const TShaderUniformBufferParameter< UniformBufferStructType > & GetUniformBufferParameter () const
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FHashedName SearchName) const
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FShaderParametersMetadata *SearchStruct) const
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
RENDERCORE_API const FSHAHash & GetVertexFactoryHash () const
FVertexFactoryType * GetVertexFactoryType (const FPointerTableBase *InPointerTable) const
FVertexFactoryType * GetVertexFactoryType (const FShaderMapPointerTable &InPointerTable) const
bool IsFrozen () const
LAYOUT_FIELD (FShaderParameterBindings, Bindings)
LAYOUT_FIELD (FShaderParameterMapInfo, ParameterMapInfo)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SetNumInstructions (uint32 Value)
Static Public Member Functions
static bool ShouldCompilePermutation (const FGlobalShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FGlobalShader
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &Environment)
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Static Public Member Functions inherited from FShader
static EShaderCompileJobPriority GetOverrideJobPriority ()
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
static ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId)
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
static const FShaderParametersMetadata * GetRootParametersMetadata ()
Returns the meta data for the root shader parameter struct.
static const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &)
Get shader binding layout used by the shader.
static void ModifyCompilationEnvironment (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
static bool ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap &InParameterMap, TArray< FString > &OutError)
Can be overridden by FShader subclasses to determine whether compilation is valid.
Private Member Functions
DECLARE_EXPORTED_SHADER_TYPE (FScreenPS, Global, 1)
LAYOUT_FIELD (FShaderResourceParameter, InTexture)
LAYOUT_FIELD (FShaderResourceParameter, InTextureSampler)
Additional Inherited Members
Public Types inherited from FGlobalShader
using FPermutationParameters = FGlobalShaderPermutationParameters
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FShader
using CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
using FPermutationDomain = FShaderPermutationNone
using FPermutationParameters = FShaderPermutationParameters
using FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
using ShaderMetaType = FShaderType
using ShaderStatKeyType = FMemoryImageName
Protected Member Functions inherited from FShader
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, UniformBufferParameterStructs)
LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter >, UniformBufferParameters)
LAYOUT_FIELD_EDITORONLY (FSHAHash, OutputHash)
Hash of the compiled output from this shader and the resulting parameter map.
LAYOUT_FIELD_EDITORONLY (FSHAHash, SourceHash)
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY (FSHAHash, VFSourceHash)
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
Detailed Description
A pixel shader for rendering a textured screen element.
Definition at line 64 of file ScreenRendering.h.
Constructor & Destructor Documentation
FScreenPS() [1/2]
FScreenPS::FScreenPS (const ShaderMetaType::CompiledShaderInitializerType & Initializer) inline
Definition at line 71 of file ScreenRendering.h.
References FGlobalShader::FGlobalShader(), FShaderCompiledShaderInitializerType::ParameterMap, SPF_Mandatory, and TEXT.
Referenced by FScreenFromSlice0PS::FScreenFromSlice0PS(), FScreenUnwrapSlicesPS::FScreenUnwrapSlicesPS(), and DECLARE_EXPORTED_SHADER_TYPE().
FScreenPS() [2/2]
FScreenPS::FScreenPS () inline
Definition at line 77 of file ScreenRendering.h.
Member Function Documentation
DECLARE_EXPORTED_SHADER_TYPE()
FScreenPS::DECLARE_EXPORTED_SHADER_TYPE (FScreenPS , Global , 1) private
References FScreenPS(), and Global.
LAYOUT_FIELD() [1/2]
FScreenPS::LAYOUT_FIELD (FShaderResourceParameter , InTexture) private
LAYOUT_FIELD() [2/2]
FScreenPS::LAYOUT_FIELD (FShaderResourceParameter , InTextureSampler) private
SetParameters() [1/2]
void FScreenPS::SetParameters (FRHIBatchedShaderParameters & BatchedParameters, const FTexture * Texture) inline
Definition at line 79 of file ScreenRendering.h.
References SetTextureParameter(), and Texture.
SetParameters() [2/2]
void FScreenPS::SetParameters (FRHIBatchedShaderParameters & BatchedParameters, FRHISamplerState * SamplerStateRHI, FRHITexture * TextureRHI) inline
Definition at line 84 of file ScreenRendering.h.
References SetTextureParameter().
ShouldCompilePermutation()
bool FScreenPS::ShouldCompilePermutation (const FGlobalShaderPermutationParameters & Parameters) inline static
Definition at line 69 of file ScreenRendering.h.
Referenced by FScreenFromSlice0PS::ShouldCompilePermutation(), and FScreenUnwrapSlicesPS::ShouldCompilePermutation().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ScreenRendering.h