Unreal Engine 5.6 C++ API: TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Types
using FMethodPtr = typename TMemFunPtrType<bConst, UserClass, RetValType(ParamTypes..., VarTypes...)>::Type
Public Member Functions
template<typename... InVarTypes>
TBaseRawMethodDelegateInstance (UserClass *InUserObject, FMethodPtr InMethodPtr, InVarTypes &&... Vars)
Creates and initializes a new instance.
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst InUserObject) const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Protected Attributes
FMethodPtr MethodPtr
UserClass * UserObject
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
Detailed Description
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes>
class TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >
Definition at line 430 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 436 of file DelegateInstancesImpl.h.
FMethodPtr
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::FMethodPtr = typename TMemFunPtrType<bConst, UserClass, RetValType(ParamTypes..., VarTypes...)>::Type
Definition at line 439 of file DelegateInstancesImpl.h.
Super
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 435 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseRawMethodDelegateInstance()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> template<typename... InVarTypes> TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseRawMethodDelegateInstance (UserClass * InUserObject, FMethodPtr InMethodPtr, InVarTypes &&... Vars) inline explicit
Creates and initializes a new instance.
Parameters
InUserObject An arbitrary object (templated) that hosts the member function.
InMethodPtr C++ member function pointer for the method to bind.
Definition at line 448 of file DelegateInstancesImpl.h.
References check, Forward(), MethodPtr, and UserObject.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 509 of file DelegateInstancesImpl.h.
References TBaseRawMethodDelegateInstance().
CreateCopy() [2/3]
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 514 of file DelegateInstancesImpl.h.
References TBaseRawMethodDelegateInstance().
CreateCopy() [3/3]
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 504 of file DelegateInstancesImpl.h.
References TBaseRawMethodDelegateInstance().
Execute()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> RetValType TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 519 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), MethodPtr, Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObject.
ExecuteIfSafe()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 534 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), MethodPtr, Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObject.
GetBoundProgramCounterForTimerManager()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> uint64 TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 478 of file DelegateInstancesImpl.h.
References MethodPtr.
GetObjectForTimerManager()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> const void * TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 473 of file DelegateInstancesImpl.h.
References UserObject.
GetUObject()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UObject * TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetUObject () const inline final
Definition at line 468 of file DelegateInstancesImpl.h.
HasSameObject()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::HasSameObject (FDelegateUserObjectConst InUserObject) const inline final
Definition at line 488 of file DelegateInstancesImpl.h.
References UserObject.
IsSafeToExecute()
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 493 of file DelegateInstancesImpl.h.
Field Documentation
MethodPtr
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> FMethodPtr TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::MethodPtr protected
Definition at line 556 of file DelegateInstancesImpl.h.
Referenced by TBaseRawMethodDelegateInstance(), Execute(), ExecuteIfSafe(), and GetBoundProgramCounterForTimerManager().
UserObject
template<bool bConst, class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UserClass* TBaseRawMethodDelegateInstance< bConst, UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::UserObject protected
Definition at line 553 of file DelegateInstancesImpl.h.
Referenced by TBaseRawMethodDelegateInstance(), Execute(), ExecuteIfSafe(), GetObjectForTimerManager(), and HasSameObject().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstancesImpl.h