Unreal Engine 5.6 C++ API: TCueDispatchTable< TCueHandler > Class Template Reference
TCueDispatchTable< TCueHandler > Class Template Reference
#include "NetworkPredictionCues.h"
Data Structures
struct FCueTypeInfo
Public Member Functions
void Dispatch (FSavedCue &SavedCue, TCueHandler &Handler, const int32 &TimeSinceInvocation)
template<typename TCue>
void RegisterType ()
void Reset ()
Static Public Member Functions
static TCueDispatchTable< TCueHandler > & Get ()
Private Attributes
TMap< FNetSimCueTypeId, FCueTypeInfo > CueTypeInfoMap
Static Private Attributes
static TCueDispatchTable< TCueHandler > Singleton
Detailed Description
template<typename TCueHandler>
class TCueDispatchTable< TCueHandler >
Definition at line 367 of file NetworkPredictionCues.h.
Member Function Documentation
Dispatch()
template<typename TCueHandler> void TCueDispatchTable< TCueHandler >::Dispatch (FSavedCue & SavedCue, TCueHandler & Handler, const int32 & TimeSinceInvocation) inline
Definition at line 396 of file NetworkPredictionCues.h.
References check, FSavedCue::CueInstance, CueTypeInfoMap, FGlobalCueTypeTable::Get(), TUniquePtr< T, Deleter >::Get(), GetTypeName(), FSavedCue::ID, FGlobalCueTypeTable::IsRegisterationTypeInfoDirty(), npCheckSlow, TEXT, UE_LOG, and Warning.
Get()
template<typename TCueHandler> TCueDispatchTable< TCueHandler > & TCueDispatchTable< TCueHandler >::Get () inline static
Definition at line 370 of file NetworkPredictionCues.h.
References Singleton.
Referenced by TNetSimCueHandlerAutoRegisterHelper< THandler >::TNetSimCueHandlerAutoRegisterHelper(), TNetSimCueSetHandlerAutoRegisterHelper< THandler, TCueSet >::TNetSimCueSetHandlerAutoRegisterHelper(), and TNetSimCueDispatcher< ModelDef >::DispatchCueRecord().
RegisterType()
template<typename TCueHandler> template<typename TCue> void TCueDispatchTable< TCueHandler >::RegisterType () inline
Definition at line 377 of file NetworkPredictionCues.h.
References check, Cue, CueTypeInfoMap, and TCueDispatchTable< TCueHandler >::FCueTypeInfo::Dispatch.
Reset()
template<typename TCueHandler> void TCueDispatchTable< TCueHandler >::Reset () inline
Definition at line 391 of file NetworkPredictionCues.h.
References CueTypeInfoMap.
Field Documentation
CueTypeInfoMap
template<typename TCueHandler> TMap<FNetSimCueTypeId, FCueTypeInfo> TCueDispatchTable< TCueHandler >::CueTypeInfoMap private
Definition at line 425 of file NetworkPredictionCues.h.
Referenced by Dispatch(), RegisterType(), and Reset().
Singleton
template<typename TCueHandler> TCueDispatchTable<TCueHandler> TCueDispatchTable< TCueHandler >::Singleton static private
Definition at line 418 of file NetworkPredictionCues.h.
Referenced by Get().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionCues.h