Unreal Engine 5.6 C++ API: FYUY2ConvertPS Class Reference
FYUY2ConvertPS Class Reference
Pixel shader to convert a YUY2 frame to RGBA.
#include "MediaShaders.h"
Public Types
using ShaderMapType = FGlobalShaderMap
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FGlobalShader
using FPermutationParameters = FGlobalShaderPermutationParameters
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FShader
using CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
using FPermutationDomain = FShaderPermutationNone
using FPermutationParameters = FShaderPermutationParameters
using FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
using ShaderMetaType = FShaderType
using ShaderStatKeyType = FMemoryImageName
Public Member Functions
FYUY2ConvertPS ()
FYUY2ConvertPS (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
DECLARE_EXPORTED_TYPE_LAYOUT (FYUY2ConvertPS, RENDERCORE_API, NonVirtual)
RENDERCORE_API void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, TRefCountPtr< FRHITexture > YUY2Texture, const FIntPoint &OutputDimensions, const FMatrix &ColorTransform, const FVector &YUVOffset, bool SrgbToLinear, MediaShaders::EToneMapMethod ToneMapMethod=MediaShaders::EToneMapMethod::None)
Public Member Functions inherited from FGlobalShader
FGlobalShader ()=default
RENDERCORE_API FGlobalShader (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
template<typename TViewUniformShaderParameters>
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, FRHIUniformBuffer *ViewUniformBuffer)
Public Member Functions inherited from FShader
RENDERCORE_API FShader ()
Used to construct a shader for deserialization.
RENDERCORE_API FShader (const CompiledShaderInitializerType &Initializer)
Construct a shader from shader compiler output.
RENDERCORE_API ~FShader ()
RENDERCORE_API void DumpDebugInfo (const FShaderMapPointerTable &InPtrTable)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API const FShaderParametersMetadata * FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
uint32 GetCodeSize () const
EShaderFrequency GetFrequency () const
RENDERCORE_API const FSHAHash & GetHash () const
Returns the hash of the shader file that this shader was compiled with.
uint32 GetNumInstructions () const
uint32 GetNumTextureSamplers () const
RENDERCORE_API const FSHAHash & GetOutputHash () const
int32 GetResourceIndex () const
EShaderPlatform GetShaderPlatform () const
uint32 GetSortKey () const
Returns an identifier suitable for deterministic sorting of shaders between sessions.
const FShaderTarget GetTarget () const
FShaderType * GetType (const FPointerTableBase *InPointerTable) const
FShaderType * GetType (const FShaderMapPointerTable &InPointerTable) const
FShaderType * GetTypeUnfrozen () const
template<typename UniformBufferStructType>
const TShaderUniformBufferParameter< UniformBufferStructType > & GetUniformBufferParameter () const
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FHashedName SearchName) const
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FShaderParametersMetadata *SearchStruct) const
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
RENDERCORE_API const FSHAHash & GetVertexFactoryHash () const
FVertexFactoryType * GetVertexFactoryType (const FPointerTableBase *InPointerTable) const
FVertexFactoryType * GetVertexFactoryType (const FShaderMapPointerTable &InPointerTable) const
bool IsFrozen () const
LAYOUT_FIELD (FShaderParameterBindings, Bindings)
LAYOUT_FIELD (FShaderParameterMapInfo, ParameterMapInfo)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SetNumInstructions (uint32 Value)
Static Public Member Functions
static FShader * ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType &Initializer)
static FShader * ConstructSerializedInstance ()
static void GetPermutationIdStringImpl (int32 PermutationId, FString &OutString, bool bFullNames)
static RENDERCORE_API ShaderMetaType & GetStaticType ()
static void ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static bool ShouldCompilePermutationImpl (const FShaderPermutationParameters &Parameters)
static EShaderPermutationPrecacheRequest ShouldPrecachePermutationImpl (const FShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FGlobalShader
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &Environment)
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Static Public Member Functions inherited from FShader
static EShaderCompileJobPriority GetOverrideJobPriority ()
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
static ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId)
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
static const FShaderParametersMetadata * GetRootParametersMetadata ()
Returns the meta data for the root shader parameter struct.
static const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &)
Get shader binding layout used by the shader.
static void ModifyCompilationEnvironment (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
static bool ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap &InParameterMap, TArray< FString > &OutError)
Can be overridden by FShader subclasses to determine whether compilation is valid.
Static Private Attributes
static FShaderTypeRegistration ShaderTypeRegistration
Additional Inherited Members
Protected Member Functions inherited from FShader
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, UniformBufferParameterStructs)
LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter >, UniformBufferParameters)
LAYOUT_FIELD_EDITORONLY (FSHAHash, OutputHash)
Hash of the compiled output from this shader and the resulting parameter map.
LAYOUT_FIELD_EDITORONLY (FSHAHash, SourceHash)
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY (FSHAHash, VFSourceHash)
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
Detailed Description
Pixel shader to convert a YUY2 frame to RGBA.
This shader expects an YUY2 frame packed into a single texture in PF_B8G8R8A8 format with the following memory layout: [Y0, U0, Y1, V0][Y2, U1, Y3, V1]...
See also
http://www.fourcc.org/yuv.php#YUY2
Definition at line 542 of file MediaShaders.h.
Member Typedef Documentation
ShaderMapType
using FYUY2ConvertPS::ShaderMapType = FGlobalShaderMap
Definition at line 545 of file MediaShaders.h.
ShaderMetaType
using FYUY2ConvertPS::ShaderMetaType = FGlobalShaderType
Definition at line 545 of file MediaShaders.h.
Constructor & Destructor Documentation
FYUY2ConvertPS() [1/2]
FYUY2ConvertPS::FYUY2ConvertPS () inline
Definition at line 548 of file MediaShaders.h.
Referenced by ConstructCompiledInstance().
FYUY2ConvertPS() [2/2]
FYUY2ConvertPS::FYUY2ConvertPS (const ShaderMetaType::CompiledShaderInitializerType & Initializer) inline
Definition at line 550 of file MediaShaders.h.
References FGlobalShader::FGlobalShader().
Member Function Documentation
ConstructCompiledInstance()
FShader * FYUY2ConvertPS::ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType & Initializer) inline static
Definition at line 545 of file MediaShaders.h.
References FYUY2ConvertPS(), and Global.
ConstructSerializedInstance()
FShader * FYUY2ConvertPS::ConstructSerializedInstance () inline static
Definition at line 545 of file MediaShaders.h.
DECLARE_EXPORTED_TYPE_LAYOUT()
FYUY2ConvertPS::DECLARE_EXPORTED_TYPE_LAYOUT (FYUY2ConvertPS , RENDERCORE_API , NonVirtual)
GetPermutationIdStringImpl()
void FYUY2ConvertPS::GetPermutationIdStringImpl (int32 PermutationId, FString & OutString, bool bFullNames) inline static
Definition at line 545 of file MediaShaders.h.
GetStaticType()
RENDERCORE_API ShaderMetaType & FYUY2ConvertPS::GetStaticType () static
ModifyCompilationEnvironmentImpl()
void FYUY2ConvertPS::ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) inline static
Definition at line 545 of file MediaShaders.h.
SetParameters()
RENDERCORE_API void FYUY2ConvertPS::SetParameters (FRHIBatchedShaderParameters & BatchedParameters, TRefCountPtr< FRHITexture > YUY2Texture, const FIntPoint & OutputDimensions, const FMatrix & ColorTransform, const FVector & YUVOffset, bool SrgbToLinear, MediaShaders::EToneMapMethod ToneMapMethod = MediaShaders::EToneMapMethod::None)
References FVector, and MediaShaders::None.
ShouldCompilePermutationImpl()
bool FYUY2ConvertPS::ShouldCompilePermutationImpl (const FShaderPermutationParameters & Parameters) inline static
Definition at line 545 of file MediaShaders.h.
ShouldPrecachePermutationImpl()
EShaderPermutationPrecacheRequest FYUY2ConvertPS::ShouldPrecachePermutationImpl (const FShaderPermutationParameters & Parameters) inline static
Definition at line 545 of file MediaShaders.h.
Field Documentation
ShaderTypeRegistration
FShaderTypeRegistration FYUY2ConvertPS::ShaderTypeRegistration static private
Definition at line 545 of file MediaShaders.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/MediaShaders.h