Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType > Class Template Reference
UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType > Class Template Reference final
#include "DynamicVertexSkinWeightsAttribute.h"
Data Structures
struct FChangeVertexBoneWeights
Public Member Functions
TDynamicVertexSkinWeightsAttributeChange ()=default
virtual ~TDynamicVertexSkinWeightsAttributeChange () override=default
bool Apply (TDynamicAttributeBase< ParentType > *Attribute, bool bRevert) const override
void SaveInitialVertex (const TDynamicAttributeBase< ParentType > *Attribute, int VertexID) override
void StoreAllFinalVertices (const TDynamicAttributeBase< ParentType > *Attribute, const TSet< int > &VertexIDs) override
Public Member Functions inherited from UE::Geometry::TDynamicAttributeChangeBase< ParentType >
virtual ~TDynamicAttributeChangeBase ()
virtual void SaveInitialTriangle (const TDynamicAttributeBase< ParentType > *Attribute, int TriangleID)
virtual void StoreAllFinalTriangles (const TDynamicAttributeBase< ParentType > *Attribute, const TArray< int > &TriangleIDs)
UE_DEPRECATED (5.6, "Use the version of this method that takes a TSet instead") virtual void StoreAllFinalVertices(const TDynamicAttributeBase< ParentType > *Attribute
Private Attributes
TArray< FChangeVertexBoneWeights > NewVertexBoneWeights
TArray< FChangeVertexBoneWeights > OldVertexBoneWeights
Additional Inherited Members
Data Fields inherited from UE::Geometry::TDynamicAttributeChangeBase< ParentType >
const TArray< int > & TriangleIDs
Detailed Description
template<typename ParentType>
class UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >
Definition at line 18 of file DynamicVertexSkinWeightsAttribute.h.
Constructor & Destructor Documentation
TDynamicVertexSkinWeightsAttributeChange()
template<typename ParentType> UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::TDynamicVertexSkinWeightsAttributeChange () default
~TDynamicVertexSkinWeightsAttributeChange()
template<typename ParentType> virtual UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::~TDynamicVertexSkinWeightsAttributeChange () override virtual default
References Attribute.
Member Function Documentation
Apply()
template<typename ParentType> bool UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::Apply (TDynamicAttributeBase< ParentType > * Attribute, bool bRevert) const override virtual
Reimplemented from UE::Geometry::TDynamicAttributeChangeBase< ParentType >.
Definition at line 756 of file DynamicVertexSkinWeightsAttribute.h.
References Attribute, check, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetParent(), NewVertexBoneWeights, OldVertexBoneWeights, and UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::SetValue().
SaveInitialVertex()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::SaveInitialVertex (const TDynamicAttributeBase< ParentType > * Attribute, int VertexID) override virtual
Reimplemented from UE::Geometry::TDynamicAttributeChangeBase< ParentType >.
Definition at line 734 of file DynamicVertexSkinWeightsAttribute.h.
References Attribute, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetValue(), OldVertexBoneWeights, UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::FChangeVertexBoneWeights::VertexID, and UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::FChangeVertexBoneWeights::Weights.
StoreAllFinalVertices()
template<typename ParentType> void UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::StoreAllFinalVertices (const TDynamicAttributeBase< ParentType > * Attribute, const TSet< int > & VertexIDs) override virtual
Reimplemented from UE::Geometry::TDynamicAttributeChangeBase< ParentType >.
Definition at line 743 of file DynamicVertexSkinWeightsAttribute.h.
References Attribute, UE::Geometry::TDynamicVertexSkinWeightsAttribute< ParentType >::GetValue(), NewVertexBoneWeights, TSet< InElementType, KeyFuncs, Allocator >::Num(), UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::FChangeVertexBoneWeights::VertexID, and UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::FChangeVertexBoneWeights::Weights.
Field Documentation
NewVertexBoneWeights
template<typename ParentType> TArray<FChangeVertexBoneWeights> UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::NewVertexBoneWeights private
Definition at line 27 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by Apply(), and StoreAllFinalVertices().
OldVertexBoneWeights
template<typename ParentType> TArray<FChangeVertexBoneWeights> UE::Geometry::TDynamicVertexSkinWeightsAttributeChange< ParentType >::OldVertexBoneWeights private
Definition at line 27 of file DynamicVertexSkinWeightsAttribute.h.
Referenced by Apply(), and SaveInitialVertex().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/DynamicVertexSkinWeightsAttribute.h