Unreal Engine 5.6 C++ API: Metasound::TArrayGetOperator< ArrayType > Class Template Reference
Metasound::TArrayGetOperator< ArrayType > Class Template Reference
TArrayGetOperator copies a value from the array to the output when a trigger occurs.
#include "MetasoundArrayNodes.h"
Data Structures
struct FInitParams
Public Types
using ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
using FArrayDataReadReference = TDataReadReference<ArrayType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArrayGetOperator (const FOperatorSettings &InSettings, FInitParams &&InParams)
virtual ~TArrayGetOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
virtual FDataReferenceCollection GetInputs () const override
virtual FDataReferenceCollection GetOutputs () const override
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArrayGetOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Attributes
FArrayDataReadReference Array
FString GraphName
TDataReadReference< int32 > Index
TDataReadReference< FTrigger > Trigger
TDataWriteReference< ElementType > Value
Detailed Description
template<typename ArrayType>
class Metasound::TArrayGetOperator< ArrayType >
TArrayGetOperator copies a value from the array to the output when a trigger occurs.
Initially, the output value is default constructed and will remain that way until until a trigger is encountered.
Definition at line 196 of file MetasoundArrayNodes.h.
Member Typedef Documentation
ElementType
template<typename ArrayType> using Metasound::TArrayGetOperator< ArrayType >::ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
Definition at line 200 of file MetasoundArrayNodes.h.
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArrayGetOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 199 of file MetasoundArrayNodes.h.
Constructor & Destructor Documentation
TArrayGetOperator()
template<typename ArrayType> Metasound::TArrayGetOperator< ArrayType >::TArrayGetOperator (const FOperatorSettings & InSettings, FInitParams && InParams) inline
Definition at line 285 of file MetasoundArrayNodes.h.
References Array, GraphName, Index, Trigger, Value, and WITH_METASOUND_DEBUG_ENVIRONMENT.
~TArrayGetOperator()
template<typename ArrayType> virtual Metasound::TArrayGetOperator< ArrayType >::~TArrayGetOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArrayGetOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 317 of file MetasoundArrayNodes.h.
References Array, Metasound::FInputVertexInterfaceData::BindReadVertex(), Index, METASOUND_GET_PARAM_NAME, and Trigger.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArrayGetOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 326 of file MetasoundArrayNodes.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), METASOUND_GET_PARAM_NAME, and Value.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArrayGetOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 247 of file MetasoundArrayNodes.h.
References Array, Metasound::FMetasoundEnvironment::Contains(), Metasound::FBuildOperatorParams::Environment, Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FMetasoundEnvironment::GetValue(), Metasound::Frontend::SourceInterface::Environment::GraphName, GraphName, Index, Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, MoveTemp(), Metasound::FBuildOperatorParams::OperatorSettings, and Trigger.
Execute()
template<typename ArrayType> void Metasound::TArrayGetOperator< ArrayType >::Execute () inline
Definition at line 333 of file MetasoundArrayNodes.h.
References Array, GraphName, Index, TEXT, Trigger, UE_LOG, Value, and Warning.
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArrayGetOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 202 of file MetasoundArrayNodes.h.
References METASOUND_GET_PARAM_NAME_AND_METADATA.
Referenced by GetNodeInfo().
GetInputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayGetOperator< ArrayType >::GetInputs () const inline override virtual
Definition at line 305 of file MetasoundArrayNodes.h.
References checkNoEntry.
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArrayGetOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 219 of file MetasoundArrayNodes.h.
References Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metadata, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, and TEXT.
GetOutputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayGetOperator< ArrayType >::GetOutputs () const inline override virtual
Definition at line 311 of file MetasoundArrayNodes.h.
References checkNoEntry.
Reset()
template<typename ArrayType> void Metasound::TArrayGetOperator< ArrayType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 354 of file MetasoundArrayNodes.h.
References Array, Metasound::TDataFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs(), Index, Metasound::IOperator::FResetParams::OperatorSettings, and Value.
Field Documentation
Array
template<typename ArrayType> FArrayDataReadReference Metasound::TArrayGetOperator< ArrayType >::Array private
Definition at line 372 of file MetasoundArrayNodes.h.
Referenced by TArrayGetOperator(), BindInputs(), CreateOperator(), Execute(), and Reset().
GraphName
template<typename ArrayType> FString Metasound::TArrayGetOperator< ArrayType >::GraphName private
Definition at line 377 of file MetasoundArrayNodes.h.
Referenced by TArrayGetOperator(), CreateOperator(), and Execute().
Index
template<typename ArrayType> TDataReadReference<int32> Metasound::TArrayGetOperator< ArrayType >::Index private
Definition at line 373 of file MetasoundArrayNodes.h.
Referenced by TArrayGetOperator(), BindInputs(), CreateOperator(), Execute(), and Reset().
Trigger
template<typename ArrayType> TDataReadReference<FTrigger> Metasound::TArrayGetOperator< ArrayType >::Trigger private
Definition at line 371 of file MetasoundArrayNodes.h.
Referenced by TArrayGetOperator(), BindInputs(), CreateOperator(), and Execute().
Value
template<typename ArrayType> TDataWriteReference<ElementType> Metasound::TArrayGetOperator< ArrayType >::Value private
Definition at line 374 of file MetasoundArrayNodes.h.
Referenced by TArrayGetOperator(), BindOutputs(), Execute(), and Reset().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundArrayNodes.h