Unreal Engine 5.6 C++ API: UE::Geometry::FGeometrySet3 Class Reference
UE::Geometry::FGeometrySet3 Class Reference
FGeometrySet3 stores a set of 3D Points and Polyline curves, and supports spatial queries against these sets.
#include "GeometrySet3.h"
Data Structures
struct FCurve
struct FNearest
FNearest is returned by nearest-point queries.
struct FPoint
Public Member Functions
GEOMETRYCORE_API void AddCurve (int CurveID, const FPolyline3d &Polyline)
Add a polycurve with given CurveID and the give Polyline.
GEOMETRYCORE_API void AddPoint (int PointID, const FVector3d &Position)
Add a point with given PointID at the given Position.
GEOMETRYCORE_API bool CollectCurvesNearRay (const FRay3d &Ray, TArray< FNearest > &ResultsOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
Like FindNearestCurveToRay, but gives all elements within tolerance, rather than just the closest.
GEOMETRYCORE_API bool CollectPointsNearRay (const FRay3d &Ray, TArray< FNearest > &ResultsOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
Like FindNearestPointToRay, but gives all elements within tolerance, rather than just the closest.
template<typename PredicateType, typename IntContainerType>
bool FindAllCurvesSatisfying (PredicateType Predicate, IntContainerType &CurveIDsOut) const
Fills CurveIDsOut with IDs of curves that satisfy the given predicate.
template<typename PredicateType, typename IntContainerType>
bool FindAllPointsSatisfying (PredicateType Predicate, IntContainerType &PointIDsOut) const
Fills PointIDsOut with point IDs of points that satisfy the given predicate.
GEOMETRYCORE_API bool FindNearestCurveToRay (const FRay3d &Ray, FNearest &ResultOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
GEOMETRYCORE_API bool FindNearestPointToRay (const FRay3d &Ray, FNearest &ResultOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
template<typename PredicateType, typename IntContainerType>
bool ParallelFindAllCurvesSatisfying (PredicateType Predicate, IntContainerType &CurveIDsOut) const
Like FindAllCurvesSatisfying, but parallel, so predicate must be safe to call in parallel.
template<typename PredicateType, typename IntContainerType>
bool ParallelFindAllPointsSatisfying (PredicateType Predicate, IntContainerType &PointIDsOut) const
Like FindAllPointsSatisfying, but parallel, so predicate must be safe to call in parallel.
GEOMETRYCORE_API void RemoveCurve (int CurveID)
Remove a curve with given CurveID.
GEOMETRYCORE_API void RemovePoint (int PointID)
Remove a point with given PointID.
GEOMETRYCORE_API void Reset (bool bPoints=true, bool bCurves=true)
GEOMETRYCORE_API void UpdateCurve (int CurveID, const FPolyline3d &Polyline)
Update the Polyline of previously-added CurveID.
GEOMETRYCORE_API void UpdatePoint (int PointID, const FVector3d &Position)
Update the Position of previously-added PointID.
Protected Attributes
TMap< int, int > CurveIDToIndex
TArray< FCurve > Curves
TMap< int, int > PointIDToIndex
TArray< FPoint > Points
Detailed Description
FGeometrySet3 stores a set of 3D Points and Polyline curves, and supports spatial queries against these sets.
Since Points and Curves have no area to hit, hit-tests are done via nearest-point-on-ray.
Definition at line 27 of file GeometrySet3.h.
Member Function Documentation
AddCurve()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::AddCurve (int CurveID, const FPolyline3d & Polyline)
Add a polycurve with given CurveID and the give Polyline.
AddPoint()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::AddPoint (int PointID, const FVector3d & Position)
Add a point with given PointID at the given Position.
References UE::Geometry::Position.
CollectCurvesNearRay()
GEOMETRYCORE_API bool UE::Geometry::FGeometrySet3::CollectCurvesNearRay (const FRay3d & Ray, TArray< FNearest > & ResultsOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
Like FindNearestCurveToRay, but gives all elements within tolerance, rather than just the closest.
Parameters
Ray query ray
ResultsOut populated with information about successful nearest point results. Not cleared in advance.
PointWithinToleranceTest should return true if two 3D points are "close enough" to be considered a hit
Returns
true if at least one result was added (ie, passed PointWithinToleranceTest).
Warning
PointWithinToleranceTest is called in parallel and hence must be thread-safe/re-entrant!
References Ray.
CollectPointsNearRay()
GEOMETRYCORE_API bool UE::Geometry::FGeometrySet3::CollectPointsNearRay (const FRay3d & Ray, TArray< FNearest > & ResultsOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
Like FindNearestPointToRay, but gives all elements within tolerance, rather than just the closest.
Parameters
Ray query ray
ResultsOut populated with information about successful nearest point results. Not cleared in advance.
PointWithinToleranceTest should return true if two 3D points are "close enough" to be considered a hit
Returns
true if at least one result was added (ie, passed PointWithinToleranceTest).
Warning
PointWithinToleranceTest is called in parallel and hence must be thread-safe/re-entrant!
References Ray.
FindAllCurvesSatisfying()
template<typename PredicateType, typename IntContainerType> bool UE::Geometry::FGeometrySet3::FindAllCurvesSatisfying (PredicateType Predicate, IntContainerType & CurveIDsOut) const inline
Fills CurveIDsOut with IDs of curves that satisfy the given predicate.
Parameters
Predicate A lambda or function that takes in a const FPolyline3d& and returns true when the curve's ID should be added to PointIDsOut.
CurveIDsOut Output list or set. Must have an Add(int) method.
Definition at line 175 of file GeometrySet3.h.
References Curves, Invoke(), and Predicate.
FindAllPointsSatisfying()
template<typename PredicateType, typename IntContainerType> bool UE::Geometry::FGeometrySet3::FindAllPointsSatisfying (PredicateType Predicate, IntContainerType & PointIDsOut) const inline
Fills PointIDsOut with point IDs of points that satisfy the given predicate.
Parameters
Predicate A lambda or function that takes in a const FVector3d& and returns true when the point's ID should be added to PointIDsOut.
PointIDsOut Output list or set. Must have an Add(int) method.
Definition at line 128 of file GeometrySet3.h.
References Invoke(), Point, Points, and Predicate.
FindNearestCurveToRay()
GEOMETRYCORE_API bool UE::Geometry::FGeometrySet3::FindNearestCurveToRay (const FRay3d & Ray, FNearest & ResultOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
Parameters
Ray query ray
ResultOut populated with information about successful nearest point result
PointWithinToleranceTest should return true if two 3D points are "close enough" to be considered a hit
Returns
true if the nearest point on Ray to some curve in the set passed the PointWithinToleranceTest.
Warning
PointWithinToleranceTest is called in parallel and hence must be thread-safe/re-entrant!
References Ray.
FindNearestPointToRay()
GEOMETRYCORE_API bool UE::Geometry::FGeometrySet3::FindNearestPointToRay (const FRay3d & Ray, FNearest & ResultOut, TFunction< bool(const FVector3d &, const FVector3d &)> PointWithinToleranceTest) const
Parameters
Ray query ray
ResultOut populated with information about successful nearest point result
PointWithinToleranceTest should return true if two 3D points are "close enough" to be considered a hit
Returns
true if the nearest point on Ray to some point in the set passed the PointWithinToleranceTest.
Warning
PointWithinToleranceTest is called in parallel and hence must be thread-safe/re-entrant!
References Ray.
ParallelFindAllCurvesSatisfying()
template<typename PredicateType, typename IntContainerType> bool UE::Geometry::FGeometrySet3::ParallelFindAllCurvesSatisfying (PredicateType Predicate, IntContainerType & CurveIDsOut) const inline
Like FindAllCurvesSatisfying, but parallel, so predicate must be safe to call in parallel.
Definition at line 192 of file GeometrySet3.h.
References Curves, Flags, ParallelFor(), and Predicate.
ParallelFindAllPointsSatisfying()
template<typename PredicateType, typename IntContainerType> bool UE::Geometry::FGeometrySet3::ParallelFindAllPointsSatisfying (PredicateType Predicate, IntContainerType & PointIDsOut) const inline
Like FindAllPointsSatisfying, but parallel, so predicate must be safe to call in parallel.
Definition at line 145 of file GeometrySet3.h.
References Flags, ParallelFor(), Points, and Predicate.
RemoveCurve()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::RemoveCurve (int CurveID)
Remove a curve with given CurveID.
RemovePoint()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::RemovePoint (int PointID)
Remove a point with given PointID.
Reset()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::Reset (bool bPoints = true, bool bCurves = true)
Parameters
bPoints if true, discard all points
bCurves if true, discard all polycurves
UpdateCurve()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::UpdateCurve (int CurveID, const FPolyline3d & Polyline)
Update the Polyline of previously-added CurveID.
UpdatePoint()
GEOMETRYCORE_API void UE::Geometry::FGeometrySet3::UpdatePoint (int PointID, const FVector3d & Position)
Update the Position of previously-added PointID.
References UE::Geometry::Position.
Field Documentation
CurveIDToIndex
TMap<int, int> UE::Geometry::FGeometrySet3::CurveIDToIndex protected
Definition at line 232 of file GeometrySet3.h.
Curves
TArray<FCurve> UE::Geometry::FGeometrySet3::Curves protected
Definition at line 231 of file GeometrySet3.h.
Referenced by FindAllCurvesSatisfying(), and ParallelFindAllCurvesSatisfying().
PointIDToIndex
TMap<int, int> UE::Geometry::FGeometrySet3::PointIDToIndex protected
Definition at line 222 of file GeometrySet3.h.
Points
TArray<FPoint> UE::Geometry::FGeometrySet3::Points protected
Definition at line 221 of file GeometrySet3.h.
Referenced by FindAllPointsSatisfying(), and ParallelFindAllPointsSatisfying().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/GeometrySet3.h