Unreal Engine 5.6 C++ API: IPixelStreaming2Streamer Class Reference
IPixelStreaming2Streamer Class Reference abstract
The IPixelStreaming2Streamer interface provides functionality for managing a Pixel Streaming session.
#include "IPixelStreaming2Streamer.h"
Public Member Functions
virtual ~IPixelStreaming2Streamer ()=default
DECLARE_EVENT_OneParam (IPixelStreaming2Streamer, FPreConnectionEvent, IPixelStreaming2Streamer *)
Event fired just before the streamer begins connecting to signalling.
DECLARE_EVENT_OneParam (IPixelStreaming2Streamer, FStreamingStartedEvent, IPixelStreaming2Streamer *)
Event fired when the streamer has connected to a signalling server and is ready for peers.
DECLARE_EVENT_OneParam (IPixelStreaming2Streamer, FStreamingStoppedEvent, IPixelStreaming2Streamer *)
Event fired when the streamer has disconnected from a signalling server and has stopped streaming.
virtual void ForceKeyFrame ()=0
Force a key frame to be sent.
virtual void FreezeStream (UTexture2D *Texture)=0
Freeze Pixel Streaming.
virtual bool GetConfigOption (const FName &OptionName, FString &OutValue)=0
Get the Gonfigerartion value for a specific option.
virtual TArray< FString > GetConnectedPlayers ()=0
Get the ids of the connected players.
virtual FString GetConnectionURL ()=0
Get the URL this streamer will connect to.
virtual FString GetId ()=0
Get this streamer's ID.
virtual TWeakPtr< class IPixelStreaming2InputHandler > GetInputHandler ()=0
Get the streamer's input handler.
virtual TWeakPtr< IPixelStreaming2AudioSink > GetPeerAudioSink (FString PlayerId)=0
Get the audio sink associated with a specific peer/player.
virtual TWeakPtr< IPixelStreaming2VideoSink > GetPeerVideoSink (FString PlayerId)=0
Get the video sink associated with a specific peer/player.
virtual int32 GetStreamFPS ()=0
Get the Stream FPS.
virtual TWeakPtr< IPixelStreaming2AudioSink > GetUnlistenedAudioSink ()=0
Get an audio sink that has no peers/players listening to it.
virtual TWeakPtr< IPixelStreaming2VideoSink > GetUnwatchedVideoSink ()=0
Get a video sink that has no peers/players watching it.
virtual TWeakPtr< IPixelStreaming2VideoProducer > GetVideoProducer ()=0
Get the Video Input object.
virtual void Initialize ()=0
Called just after streamer creation.
virtual bool IsConnected ()=0
Check if this streamer is currently connected to the connection URL.
virtual bool IsStreaming () const =0
Get the current state of this streamer.
virtual void KickPlayer (FString PlayerId)=0
Kick a player by player id.
virtual FPreConnectionEvent & OnPreConnection ()=0
A getter for the OnPreConnection event.
virtual FStreamingStartedEvent & OnStreamingStarted ()=0
A getter for the OnStreamingStarted event.
virtual FStreamingStoppedEvent & OnStreamingStopped ()=0
A getter for the OnStreamingStopped event.
virtual void PlayerRequestsBitrate (FString PlayerId, int MinBitrate, int MaxBitrate)=0
Set the minimum and maximum bitrate for the streamer.
virtual void RefreshStreamBitrate ()=0
Refresh connection with minimum and maximum bitrate.
virtual void SendAllPlayersMessage (FString MessageType, const FString &Descriptor)=0
Send all players connected to this streamer a message.
virtual void SendFileData (const TArray64< uint8 > &ByteData, FString &MimeType, FString &FileExtension)=0
Send a file to the browser where we are sending video.
virtual void SendPlayerMessage (FString PlayerId, FString MessageType, const FString &Descriptor)=0
Send all players connected to this streamer a message.
virtual void SetConfigOption (const FName &OptionName, const FString &Value)=0
Allows sending arbitrary configuration options during initial connection.
virtual void SetConnectionURL (const FString &InConnectionURL)=0
Set the URL this streamer will connect to.
virtual void SetCoupleFramerate (bool bCouple)=0
Setting this to true will cause the streamer to ignore the FPS value and instead push out frames as they are submitted from the video input.
virtual void SetStreamFPS (int32 InFramesPerSecond)=0
Set the Stream FPS.
virtual void SetVideoProducer (TSharedPtr< IPixelStreaming2VideoProducer > Input)=0
Set the Video Input object.
virtual void StartStreaming ()=0
Start streaming this streamer.
virtual void StopStreaming ()=0
Stop this streamer from streaming.
UE_DEPRECATED (5.6, "GetSignallingServerURL has been deprecated. Please use GetConnectionURL instead.") virtual FString GetSignallingServerURL()
Get the Signalling Server URL.
UE_DEPRECATED (5.6, "IsSignallingConnected has been deprecated. Please use IsConnected instead.") virtual bool IsSignallingConnected()
Check if this streamer is currently connected to the signalling mechanism (e.g.
UE_DEPRECATED (5.6, "SetSignallingServerURL has been deprecated. Please use SetConnectionURL instead.") virtual void SetSignallingServerURL(const FString &InSignallingServerURL)
Set the Signalling Server URL.
virtual void UnfreezeStream ()=0
Unfreeze Pixel Streaming.
Detailed Description
The IPixelStreaming2Streamer interface provides functionality for managing a Pixel Streaming session.
This class manages the core operations of streaming, such as setting the framerate, handling video input, and interacting with the signalling server. It also allows for control over connected players and sending data to them.
Definition at line 24 of file IPixelStreaming2Streamer.h.
Constructor & Destructor Documentation
~IPixelStreaming2Streamer()
virtual IPixelStreaming2Streamer::~IPixelStreaming2Streamer () virtual default
Member Function Documentation
DECLARE_EVENT_OneParam() [1/3]
IPixelStreaming2Streamer::DECLARE_EVENT_OneParam (IPixelStreaming2Streamer , FPreConnectionEvent , IPixelStreaming2Streamer *)
Event fired just before the streamer begins connecting to signalling.
DECLARE_EVENT_OneParam() [2/3]
IPixelStreaming2Streamer::DECLARE_EVENT_OneParam (IPixelStreaming2Streamer , FStreamingStartedEvent , IPixelStreaming2Streamer *)
Event fired when the streamer has connected to a signalling server and is ready for peers.
DECLARE_EVENT_OneParam() [3/3]
IPixelStreaming2Streamer::DECLARE_EVENT_OneParam (IPixelStreaming2Streamer , FStreamingStoppedEvent , IPixelStreaming2Streamer *)
Event fired when the streamer has disconnected from a signalling server and has stopped streaming.
ForceKeyFrame()
virtual void IPixelStreaming2Streamer::ForceKeyFrame () pure virtual
Force a key frame to be sent.
FreezeStream()
virtual void IPixelStreaming2Streamer::FreezeStream (UTexture2D * Texture) pure virtual
Freeze Pixel Streaming.
Parameters
Texture - The freeze frame to display. If null then the back buffer is captured.
References Texture.
GetConfigOption()
virtual bool IPixelStreaming2Streamer::GetConfigOption (const FName & OptionName, FString & OutValue) pure virtual
Get the Gonfigerartion value for a specific option.
Parameters
OptionName The name of the config option to get.
Value The value of the config option retrieved.
GetConnectedPlayers()
virtual TArray< FString > IPixelStreaming2Streamer::GetConnectedPlayers () pure virtual
Get the ids of the connected players.
Returns
TArray<FString> The ids of the connected players.
GetConnectionURL()
virtual FString IPixelStreaming2Streamer::GetConnectionURL () pure virtual
Get the URL this streamer will connect to.
Returns
The connection URL.
Referenced by UE_DEPRECATED().
GetId()
virtual FString IPixelStreaming2Streamer::GetId () pure virtual
Get this streamer's ID.
Returns
The streamer's ID.
GetInputHandler()
virtual TWeakPtr< class IPixelStreaming2InputHandler > IPixelStreaming2Streamer::GetInputHandler () pure virtual
Get the streamer's input handler.
Returns
The streamer's input handler
GetPeerAudioSink()
virtual TWeakPtr< IPixelStreaming2AudioSink > IPixelStreaming2Streamer::GetPeerAudioSink (FString PlayerId) pure virtual
Get the audio sink associated with a specific peer/player.
Parameters
PlayerId The player id of the audio sink to retrieve.
Returns
The PeerAudioSink.
GetPeerVideoSink()
virtual TWeakPtr< IPixelStreaming2VideoSink > IPixelStreaming2Streamer::GetPeerVideoSink (FString PlayerId) pure virtual
Get the video sink associated with a specific peer/player.
Returns
The PeerVideoSink.
GetStreamFPS()
virtual int32 IPixelStreaming2Streamer::GetStreamFPS () pure virtual
Get the Stream FPS.
Returns
- The number of frames per second the streamer will stream at.
GetUnlistenedAudioSink()
virtual TWeakPtr< IPixelStreaming2AudioSink > IPixelStreaming2Streamer::GetUnlistenedAudioSink () pure virtual
Get an audio sink that has no peers/players listening to it.
Returns
The unlistened PeerAudioSink.
GetUnwatchedVideoSink()
virtual TWeakPtr< IPixelStreaming2VideoSink > IPixelStreaming2Streamer::GetUnwatchedVideoSink () pure virtual
Get a video sink that has no peers/players watching it.
Returns
The unwatched PeerVideoSink.
GetVideoProducer()
virtual TWeakPtr< IPixelStreaming2VideoProducer > IPixelStreaming2Streamer::GetVideoProducer () pure virtual
Get the Video Input object.
Returns
The IPixelStreaming2VideoProducer that this streamer will stream.
Initialize()
virtual void IPixelStreaming2Streamer::Initialize () pure virtual
Called just after streamer creation.
Use this method to initialize any methods that need a shared pointer to the streamer by using AsShared() inside the method.
IsConnected()
virtual bool IPixelStreaming2Streamer::IsConnected () pure virtual
Check if this streamer is currently connected to the connection URL.
Returns
True if the streamer is connected.
Referenced by UE_DEPRECATED().
IsStreaming()
virtual bool IPixelStreaming2Streamer::IsStreaming () const pure virtual
Get the current state of this streamer.
Returns
True if streaming, false otherwise.
KickPlayer()
virtual void IPixelStreaming2Streamer::KickPlayer (FString PlayerId) pure virtual
Kick a player by player id.
Parameters
PlayerId - The ID of the player to kick
OnPreConnection()
virtual FPreConnectionEvent & IPixelStreaming2Streamer::OnPreConnection () pure virtual
A getter for the OnPreConnection event.
Intent is for users to call IPixelStreaming2Module::Get().FindStreamer(ID)->OnPreConnection().AddXXX.
Returns
- The bindable OnPreConnection event.
OnStreamingStarted()
virtual FStreamingStartedEvent & IPixelStreaming2Streamer::OnStreamingStarted () pure virtual
A getter for the OnStreamingStarted event.
Intent is for users to call IPixelStreaming2Module::Get().FindStreamer(ID)->OnStreamingStarted().AddXXX.
Returns
- The bindable OnStreamingStarted event.
OnStreamingStopped()
virtual FStreamingStoppedEvent & IPixelStreaming2Streamer::OnStreamingStopped () pure virtual
A getter for the OnStreamingStopped event.
Intent is for users to call IPixelStreaming2Module::Get().FindStreamer(ID)->OnStreamingStopped().AddXXX.
Returns
- The bindable OnStreamingStopped event.
PlayerRequestsBitrate()
virtual void IPixelStreaming2Streamer::PlayerRequestsBitrate (FString PlayerId, int MinBitrate, int MaxBitrate) pure virtual
Set the minimum and maximum bitrate for the streamer.
Parameters
PlayerId Currently unused. For setting the bitrate for a individual player id.
MinBitrate minimum bitrate for the streamer.
MaxBitrate maximum bitrate for the streamer.
RefreshStreamBitrate()
virtual void IPixelStreaming2Streamer::RefreshStreamBitrate () pure virtual
Refresh connection with minimum and maximum bitrate.
SendAllPlayersMessage()
virtual void IPixelStreaming2Streamer::SendAllPlayersMessage (FString MessageType, const FString & Descriptor) pure virtual
Send all players connected to this streamer a message.
Parameters
MessageType The message type to be sent to the player.
Descriptor The contents of the message.
SendFileData()
virtual void IPixelStreaming2Streamer::SendFileData (const TArray64< uint8 > & ByteData, FString & MimeType, FString & FileExtension) pure virtual
Send a file to the browser where we are sending video.
Parameters
ByteData - The raw byte data of the file.
MimeType - The files Mime type. Used for reconstruction on the front end.
FileExtension - The files extension. Used for reconstruction on the front end.
SendPlayerMessage()
virtual void IPixelStreaming2Streamer::SendPlayerMessage (FString PlayerId, FString MessageType, const FString & Descriptor) pure virtual
Send all players connected to this streamer a message.
Parameters
MessageType The message type to be sent to the player.
Descriptor The contents of the message.
SetConfigOption()
virtual void IPixelStreaming2Streamer::SetConfigOption (const FName & OptionName, const FString & Value) pure virtual
Allows sending arbitrary configuration options during initial connection.
Parameters
OptionName The name of the option to set.
Value Setting a value to an empty string clears it from the mapping and prevents it being sent.
References Value.
SetConnectionURL()
virtual void IPixelStreaming2Streamer::SetConnectionURL (const FString & InConnectionURL) pure virtual
Set the URL this streamer will connect to.
Parameters
InConnectionURL.
Referenced by UE_DEPRECATED().
SetCoupleFramerate()
virtual void IPixelStreaming2Streamer::SetCoupleFramerate (bool bCouple) pure virtual
Setting this to true will cause the streamer to ignore the FPS value and instead push out frames as they are submitted from the video input.
If the encode process takes longer than the time between frames, frames will be dropped.
Parameters
bCouple true to couple the streamer framerate to that of the video input.
SetStreamFPS()
virtual void IPixelStreaming2Streamer::SetStreamFPS (int32 InFramesPerSecond) pure virtual
Set the Stream FPS.
Parameters
InFramesPerSecond The number of frames per second the streamer will stream at.
SetVideoProducer()
virtual void IPixelStreaming2Streamer::SetVideoProducer (TSharedPtr< IPixelStreaming2VideoProducer > Input) pure virtual
Set the Video Input object.
Parameters
Input The IPixelStreaming2VideoProducer that this streamer will stream.
References Input.
StartStreaming()
virtual void IPixelStreaming2Streamer::StartStreaming () pure virtual
Start streaming this streamer.
StopStreaming()
virtual void IPixelStreaming2Streamer::StopStreaming () pure virtual
Stop this streamer from streaming.
UE_DEPRECATED() [1/3]
IPixelStreaming2Streamer::UE_DEPRECATED (5. 6, "GetSignallingServerURL has been deprecated. Please use GetConnectionURL instead.") inline
Get the Signalling Server URL.
Returns
The Signalling Server URL.
Definition at line 90 of file IPixelStreaming2Streamer.h.
References GetConnectionURL().
UE_DEPRECATED() [2/3]
IPixelStreaming2Streamer::UE_DEPRECATED (5. 6, "IsSignallingConnected has been deprecated. Please use IsConnected instead.") inline
Check if this streamer is currently connected to the signalling mechanism (e.g.
websocket for signalling server).
Returns
True if the streamer is connected to the signalling mechanism.
Definition at line 109 of file IPixelStreaming2Streamer.h.
References IsConnected().
UE_DEPRECATED() [3/3]
IPixelStreaming2Streamer::UE_DEPRECATED (5. 6, "SetSignallingServerURL has been deprecated. Please use SetConnectionURL instead.") const & inline
Set the Signalling Server URL.
Parameters
InSignallingServerURL.
Definition at line 77 of file IPixelStreaming2Streamer.h.
References SetConnectionURL().
UnfreezeStream()
virtual void IPixelStreaming2Streamer::UnfreezeStream () pure virtual
Unfreeze Pixel Streaming.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2Core/Public/IPixelStreaming2Streamer.h