Unreal Engine 5.6 C++ API: Metasound::TCopyableDataChannel< TDataType > Class Template Reference
Metasound::TCopyableDataChannel< TDataType > Class Template Reference
#include "MetasoundRouter.h"
Public Member Functions
TCopyableDataChannel (const FOperatorSettings &InOperatorSettings)
virtual int64 CreateNewPayloadID () override
virtual FName GetDataType () override
virtual int64 GetPayloadID () const override
virtual bool IsEmpty () const override
virtual void PopOpaque (IReceiver &InReceiver) override
virtual bool PushLiteral (const FLiteral &InParam)
virtual bool PushOpaque (ISender &InSender) override
Public Member Functions inherited from Metasound::IDataChannel
IDataChannel (FName DataType)
virtual ~IDataChannel ()=default
uint32 GetNumActiveReceivers () const
uint32 GetNumActiveSenders () const
TUniquePtr< IReceiver > NewReceiver (const FReceiverInitParams &InitParams)
TUniquePtr< ISender > NewSender (const FSenderInitParams &InitParams)
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Public Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
TSharedRef< IDataChannel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDataChannel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FName GetDataTypeName ()
Protected Member Functions
virtual TUniquePtr< IReceiver > ConstructNewReceiverImplementation (const FReceiverInitParams &InitParams) override
virtual TUniquePtr< ISender > ConstructNewSenderImplementation (const FSenderInitParams &InitParams) override
Protected Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
TUniquePtr< TDataType > AtomicData
FCriticalSection AtomicDataLock
FOperatorSettings OperatorSettings
int64 PayloadID = INDEX_NONE
std::atomic< int64 > PayloadIDCounter
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
template<typename TDataType>
class Metasound::TCopyableDataChannel< TDataType >
Definition at line 592 of file MetasoundRouter.h.
Constructor & Destructor Documentation
TCopyableDataChannel()
template<typename TDataType> Metasound::TCopyableDataChannel< TDataType >::TCopyableDataChannel (const FOperatorSettings & InOperatorSettings) inline
Definition at line 598 of file MetasoundRouter.h.
References Metasound::IDataChannel::IDataChannel(), GetDataTypeName(), OperatorSettings, and PayloadIDCounter.
Member Function Documentation
ConstructNewReceiverImplementation()
template<typename TDataType> virtual TUniquePtr< IReceiver > Metasound::TCopyableDataChannel< TDataType >::ConstructNewReceiverImplementation (const FReceiverInitParams & InitParams) inline override protected virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 686 of file MetasoundRouter.h.
References TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >::AsShared().
ConstructNewSenderImplementation()
template<typename TDataType> virtual TUniquePtr< ISender > Metasound::TCopyableDataChannel< TDataType >::ConstructNewSenderImplementation (const FSenderInitParams & InitParams) inline override protected virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 691 of file MetasoundRouter.h.
References TSharedFromThis< IDataChannel, ESPMode::ThreadSafe >::AsShared().
CreateNewPayloadID()
template<typename TDataType> virtual int64 Metasound::TCopyableDataChannel< TDataType >::CreateNewPayloadID () inline override virtual
Implements Metasound::IDataChannel.
Definition at line 609 of file MetasoundRouter.h.
References PayloadIDCounter.
GetDataType()
template<typename TDataType> virtual FName Metasound::TCopyableDataChannel< TDataType >::GetDataType () inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 656 of file MetasoundRouter.h.
References GetDataTypeName().
GetDataTypeName()
template<typename TDataType> FName Metasound::TCopyableDataChannel< TDataType >::GetDataTypeName () inline static
Definition at line 651 of file MetasoundRouter.h.
References Metasound::GetMetasoundDataTypeName().
Referenced by TCopyableDataChannel(), and GetDataType().
GetPayloadID()
template<typename TDataType> virtual int64 Metasound::TCopyableDataChannel< TDataType >::GetPayloadID () const inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 604 of file MetasoundRouter.h.
References PayloadID.
IsEmpty()
template<typename TDataType> virtual bool Metasound::TCopyableDataChannel< TDataType >::IsEmpty () const inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 646 of file MetasoundRouter.h.
References AtomicData.
PopOpaque()
template<typename TDataType> virtual void Metasound::TCopyableDataChannel< TDataType >::PopOpaque (IReceiver & InReceiver) inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 635 of file MetasoundRouter.h.
References AtomicData, AtomicDataLock, Metasound::IDataTransmissionBase::GetAs(), Metasound::IDataChannel::IReceiver, PayloadID, and Metasound::TReceiver< TDataType >::PushPayload().
PushLiteral()
template<typename TDataType> virtual bool Metasound::TCopyableDataChannel< TDataType >::PushLiteral (const FLiteral & InParam) inline virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 661 of file MetasoundRouter.h.
References AtomicData, AtomicDataLock, Metasound::TDataLiteralFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs(), Metasound::TLiteralTraits< DataType >::IsParsable(), MakeUnique(), and OperatorSettings.
PushOpaque()
template<typename TDataType> virtual bool Metasound::TCopyableDataChannel< TDataType >::PushOpaque (ISender & InSender) inline override virtual
Reimplemented from Metasound::IDataChannel.
Definition at line 615 of file MetasoundRouter.h.
References AtomicData, AtomicDataLock, Metasound::IDataTransmissionBase::GetAs(), Metasound::ISender::GetPayloadID(), Metasound::IDataChannel::ISender, MakeUnique(), PayloadID, and Metasound::TSender< TDataType >::RetrievePayload().
Field Documentation
AtomicData
template<typename TDataType> TUniquePtr<TDataType> Metasound::TCopyableDataChannel< TDataType >::AtomicData private
Definition at line 700 of file MetasoundRouter.h.
Referenced by IsEmpty(), PopOpaque(), PushLiteral(), and PushOpaque().
AtomicDataLock
template<typename TDataType> FCriticalSection Metasound::TCopyableDataChannel< TDataType >::AtomicDataLock private
Definition at line 701 of file MetasoundRouter.h.
Referenced by PopOpaque(), PushLiteral(), and PushOpaque().
OperatorSettings
template<typename TDataType> FOperatorSettings Metasound::TCopyableDataChannel< TDataType >::OperatorSettings private
Definition at line 705 of file MetasoundRouter.h.
Referenced by TCopyableDataChannel(), and PushLiteral().
PayloadID
template<typename TDataType> int64 Metasound::TCopyableDataChannel< TDataType >::PayloadID = INDEX_NONE private
Definition at line 703 of file MetasoundRouter.h.
Referenced by GetPayloadID(), PopOpaque(), and PushOpaque().
PayloadIDCounter
template<typename TDataType> std::atomic<int64> Metasound::TCopyableDataChannel< TDataType >::PayloadIDCounter private
Definition at line 707 of file MetasoundRouter.h.
Referenced by TCopyableDataChannel(), and CreateNewPayloadID().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h