Unreal Engine 5.6 C++ API: TObjectArrayIterator< TObjectClass > Class Template Reference
TObjectArrayIterator< TObjectClass > Class Template Reference
Iterator for arrays of UObject pointers.
#include "UObjectGlobals.h"
Public Member Functions
FORCEINLINE TObjectArrayIterator (TArray< TObjectClass * > &InArray, UClass *InClassToCheck=nullptr, bool InbExactClass=false)
Constructor, iterates all non-null, non pending kill objects, optionally of a particular class or base class.
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE TObjectClass & operator* () const
Dereferences the iterator.
FORCEINLINE void operator++ ()
Iterator advance.
FORCEINLINE TObjectClass * operator-> () const
Dereferences the iterator.
FORCEINLINE void RemoveCurrent ()
Removes the current element from the array, slower, but preserves the order.
FORCEINLINE void RemoveCurrentSwap ()
Removes the current element from the array, faster, but does not preserves the array order.
Protected Member Functions
FORCEINLINE bool Advance ()
Iterator advance with ordinary name for clarity in subclasses.
FORCEINLINE TObjectClass * GetObject () const
Dereferences the iterator with an ordinary name for clarity in derived classes.
Private Attributes
TArray< TObjectClass * > & Array
The array that we are iterating on.
bool bExactClass
Flag to require exact class matches.
UClass * ClassToCheck
Class using as a criteria.
int32 Index
Index of the current element in the object array.
Detailed Description
template<class TObjectClass>
class TObjectArrayIterator< TObjectClass >
Iterator for arrays of UObject pointers.
Parameters
TObjectClass type of pointers contained in array
Definition at line 2232 of file UObjectGlobals.h.
Constructor & Destructor Documentation
TObjectArrayIterator()
template<class TObjectClass> FORCEINLINE TObjectArrayIterator< TObjectClass >::TObjectArrayIterator (TArray< TObjectClass * > & InArray, UClass * InClassToCheck = nullptr, bool InbExactClass = false) inline
Constructor, iterates all non-null, non pending kill objects, optionally of a particular class or base class.
Parameters
InArray the array to iterate on
InClass if non-null, will only iterate on items IsA this class
InbExactClass if true, will only iterate on exact matches
Definition at line 2250 of file UObjectGlobals.h.
References Advance(), Array, bExactClass, ClassToCheck, FORCEINLINE, and Index.
Member Function Documentation
Advance()
template<class TObjectClass> FORCEINLINE bool TObjectArrayIterator< TObjectClass >::Advance () inline protected
Iterator advance with ordinary name for clarity in subclasses.
Returns
true if the iterator points to a valid object, false if iteration is complete
Definition at line 2325 of file UObjectGlobals.h.
References Array, bExactClass, ClassToCheck, FORCEINLINE, GetObject(), Index, and IsValid().
Referenced by TObjectArrayIterator(), and operator++().
GetObject()
template<class TObjectClass> FORCEINLINE TObjectClass * TObjectArrayIterator< TObjectClass >::GetObject () const inline protected
Dereferences the iterator with an ordinary name for clarity in derived classes.
Returns
the UObject at the iterator
Definition at line 2317 of file UObjectGlobals.h.
References Array, FORCEINLINE, and Index.
Referenced by Advance(), operator*(), and operator->().
operator bool()
template<class TObjectClass> FORCEINLINE TObjectArrayIterator< TObjectClass >::operator bool () const inline explicit
conversion to "bool" returning true if the iterator is valid.
Definition at line 2266 of file UObjectGlobals.h.
References Array, FORCEINLINE, and Index.
operator!()
template<class TObjectClass> FORCEINLINE bool TObjectArrayIterator< TObjectClass >::operator! () const inline
inverse of the "bool" operator
Definition at line 2271 of file UObjectGlobals.h.
References bool, and FORCEINLINE.
operator*()
template<class TObjectClass> FORCEINLINE TObjectClass & TObjectArrayIterator< TObjectClass >::operator* () const inline
Dereferences the iterator.
Returns
the UObject at the iterator
Definition at line 2280 of file UObjectGlobals.h.
References checkSlow, FORCEINLINE, and GetObject().
operator++()
template<class TObjectClass> FORCEINLINE void TObjectArrayIterator< TObjectClass >::operator++ () inline
Iterator advance.
Definition at line 2261 of file UObjectGlobals.h.
References Advance(), and FORCEINLINE.
operator->()
template<class TObjectClass> FORCEINLINE TObjectClass * TObjectArrayIterator< TObjectClass >::operator-> () const inline
Dereferences the iterator.
Returns
the UObject at the iterator
Definition at line 2289 of file UObjectGlobals.h.
References checkSlow, FORCEINLINE, and GetObject().
RemoveCurrent()
template<class TObjectClass> FORCEINLINE void TObjectArrayIterator< TObjectClass >::RemoveCurrent () inline
Removes the current element from the array, slower, but preserves the order.
Iterator is decremented for you so a loop will check all items.
Definition at line 2299 of file UObjectGlobals.h.
References Array, FORCEINLINE, and Index.
RemoveCurrentSwap()
template<class TObjectClass> FORCEINLINE void TObjectArrayIterator< TObjectClass >::RemoveCurrentSwap () inline
Removes the current element from the array, faster, but does not preserves the array order.
Iterator is decremented for you so a loop will check all items.
Definition at line 2307 of file UObjectGlobals.h.
References Array, FORCEINLINE, and Index.
Field Documentation
Array
template<class TObjectClass> TArray<TObjectClass*>& TObjectArrayIterator< TObjectClass >::Array private
The array that we are iterating on.
Definition at line 2345 of file UObjectGlobals.h.
Referenced by TObjectArrayIterator(), Advance(), GetObject(), operator bool(), RemoveCurrent(), and RemoveCurrentSwap().
bExactClass
template<class TObjectClass> bool TObjectArrayIterator< TObjectClass >::bExactClass private
Flag to require exact class matches.
Definition at line 2351 of file UObjectGlobals.h.
Referenced by TObjectArrayIterator(), and Advance().
ClassToCheck
template<class TObjectClass> UClass* TObjectArrayIterator< TObjectClass >::ClassToCheck private
Class using as a criteria.
Definition at line 2349 of file UObjectGlobals.h.
Referenced by TObjectArrayIterator(), and Advance().
Index
template<class TObjectClass> int32 TObjectArrayIterator< TObjectClass >::Index private
Index of the current element in the object array.
Definition at line 2347 of file UObjectGlobals.h.
Referenced by TObjectArrayIterator(), Advance(), GetObject(), operator bool(), RemoveCurrent(), and RemoveCurrentSwap().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectGlobals.h