Unreal Engine 5.6 C++ API: FFinalPostProcessSettings Class Reference
FFinalPostProcessSettings Class Reference
All blended postprocessing in one place, non lerpable data is stored in non merged form.
#include "FinalPostProcessSettings.h"
Data Structures
struct FCubemapEntry
struct FLUTBlenderEntry
Public Member Functions
FFinalPostProcessSettings ()
uint32 FindIndex (UTexture *Tex) const
void LerpTo (UTexture *InTexture, float Weight)
void PushLUT (UTexture *Texture, float Weight)
add a LUT(look up table) to the ones that are blended together
void SetLUT (UTexture *Texture)
void UpdateEntry (const FCubemapEntry &Entry, float Weight)
Data Fields
bool bBufferVisualizationDumpRequired
bool bBufferVisualizationOverviewTargetIsSelected
FBlendableManager BlendableManager
FString BufferVisualizationDumpBaseFilename
TArray< UMaterialInterface * > BufferVisualizationOverviewMaterials
FString BufferVisualizationOverviewSelectedTargetMaterialName
TMap< FName, TSharedPtr< FImagePixelPipe, ESPMode::ThreadSafe > > BufferVisualizationPipes
A map of buffer visualization material names to visualization pipes onto which each intermediate render target will be pushed, if set.
TArray< FCubemapEntry > ContributingCubemaps
TArray< FLUTBlenderEntry > ContributingLUTs
UMaterialInstanceDynamic * HighResScreenshotCaptureRegionMaterial
UMaterialInterface * HighResScreenshotMaskMaterial
UMaterialInterface * HighResScreenshotMaterial
UMaterialInterface * VisualizeCalibrationColorMaterial
UMaterialInterface * VisualizeCalibrationCustomMaterial
UMaterialInterface * VisualizeCalibrationGrayscaleMaterial
Detailed Description
All blended postprocessing in one place, non lerpable data is stored in non merged form.
Definition at line 16 of file FinalPostProcessSettings.h.
Constructor & Destructor Documentation
FFinalPostProcessSettings()
FFinalPostProcessSettings::FFinalPostProcessSettings () inline
Definition at line 19 of file FinalPostProcessSettings.h.
References bBufferVisualizationDumpRequired, bBufferVisualizationOverviewTargetIsSelected, ContributingCubemaps, ContributingLUTs, HighResScreenshotCaptureRegionMaterial, HighResScreenshotMaskMaterial, HighResScreenshotMaterial, SetLUT(), UE_BUILD_TEST, VisualizeCalibrationColorMaterial, VisualizeCalibrationCustomMaterial, and VisualizeCalibrationGrayscaleMaterial.
Member Function Documentation
FindIndex()
uint32 FFinalPostProcessSettings::FindIndex (UTexture * Tex) const inline
Returns
0xffffffff if not found
Definition at line 146 of file FinalPostProcessSettings.h.
References ContributingLUTs.
Referenced by LerpTo().
LerpTo()
void FFinalPostProcessSettings::LerpTo (UTexture * InTexture, float Weight) inline
Definition at line 101 of file FinalPostProcessSettings.h.
References check, ContributingLUTs, FindIndex(), PushLUT(), SetLUT(), and Weight.
PushLUT()
void FFinalPostProcessSettings::PushLUT (UTexture * Texture, float Weight) inline
add a LUT(look up table) to the ones that are blended together
Parameters
Texture - can be 0
Weight - 0..1
Definition at line 133 of file FinalPostProcessSettings.h.
References check, ContributingLUTs, FFinalPostProcessSettings::FLUTBlenderEntry::LUTTexture, Texture, Weight, and FFinalPostProcessSettings::FLUTBlenderEntry::Weight.
Referenced by LerpTo(), and SetLUT().
SetLUT()
void FFinalPostProcessSettings::SetLUT (UTexture * Texture) inline
Definition at line 159 of file FinalPostProcessSettings.h.
References ContributingLUTs, PushLUT(), and Texture.
Referenced by FFinalPostProcessSettings(), and LerpTo().
UpdateEntry()
void FFinalPostProcessSettings::UpdateEntry (const FCubemapEntry & Entry, float Weight) inline
Definition at line 61 of file FinalPostProcessSettings.h.
References FFinalPostProcessSettings::FCubemapEntry::AmbientCubemap, FFinalPostProcessSettings::FCubemapEntry::AmbientCubemapTintMulScaleValue, ContributingCubemaps, FLinearColor::IsAlmostBlack(), FMath::Lerp(), Local, No, and Weight.
Field Documentation
bBufferVisualizationDumpRequired
bool FFinalPostProcessSettings::bBufferVisualizationDumpRequired
Definition at line 193 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
bBufferVisualizationOverviewTargetIsSelected
bool FFinalPostProcessSettings::bBufferVisualizationOverviewTargetIsSelected
Definition at line 198 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
BlendableManager
FBlendableManager FFinalPostProcessSettings::BlendableManager
Definition at line 209 of file FinalPostProcessSettings.h.
BufferVisualizationDumpBaseFilename
FString FFinalPostProcessSettings::BufferVisualizationDumpBaseFilename
Definition at line 194 of file FinalPostProcessSettings.h.
BufferVisualizationOverviewMaterials
TArray<UMaterialInterface*> FFinalPostProcessSettings::BufferVisualizationOverviewMaterials
Definition at line 172 of file FinalPostProcessSettings.h.
BufferVisualizationOverviewSelectedTargetMaterialName
FString FFinalPostProcessSettings::BufferVisualizationOverviewSelectedTargetMaterialName
Definition at line 199 of file FinalPostProcessSettings.h.
BufferVisualizationPipes
TMap<FName, TSharedPtr<FImagePixelPipe, ESPMode::ThreadSafe> > FFinalPostProcessSettings::BufferVisualizationPipes
A map of buffer visualization material names to visualization pipes onto which each intermediate render target will be pushed, if set.
Will always be used if set, regardless of r.BufferVisualizationDumpFrames
Definition at line 206 of file FinalPostProcessSettings.h.
ContributingCubemaps
TArray<FCubemapEntry> FFinalPostProcessSettings::ContributingCubemaps
Definition at line 168 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings(), and UpdateEntry().
ContributingLUTs
TArray<FLUTBlenderEntry> FFinalPostProcessSettings::ContributingLUTs
Definition at line 169 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings(), FindIndex(), LerpTo(), PushLUT(), and SetLUT().
HighResScreenshotCaptureRegionMaterial
UMaterialInstanceDynamic* FFinalPostProcessSettings::HighResScreenshotCaptureRegionMaterial
Definition at line 190 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
HighResScreenshotMaskMaterial
UMaterialInterface* FFinalPostProcessSettings::HighResScreenshotMaskMaterial
Definition at line 187 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
HighResScreenshotMaterial
UMaterialInterface* FFinalPostProcessSettings::HighResScreenshotMaterial
Definition at line 184 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
VisualizeCalibrationColorMaterial
UMaterialInterface* FFinalPostProcessSettings::VisualizeCalibrationColorMaterial
Definition at line 175 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
VisualizeCalibrationCustomMaterial
UMaterialInterface* FFinalPostProcessSettings::VisualizeCalibrationCustomMaterial
Definition at line 181 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
VisualizeCalibrationGrayscaleMaterial
UMaterialInterface* FFinalPostProcessSettings::VisualizeCalibrationGrayscaleMaterial
Definition at line 178 of file FinalPostProcessSettings.h.
Referenced by FFinalPostProcessSettings().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/FinalPostProcessSettings.h