Unreal Engine 5.6 C++ API: FCompressedBuffer Class Reference
FCompressedBuffer Class Reference
A compressed buffer stores compressed data in a self-contained format.
#include "CompressedBuffer.h"
Public Member Functions
FSharedBuffer Decompress () const
Decompress into an owned buffer.
FCompositeBuffer DecompressToComposite () const
FCompositeBuffer GetCompressed () &&
const FCompositeBuffer & GetCompressed () const &
Returns a composite buffer containing the compressed data.
uint64 GetCompressedSize () const
Returns the size of the compressed data.
FIoHash GetRawHash () const
Returns the hash of the raw data.
uint64 GetRawSize () const
Returns the size of the raw data.
bool IsNull () const
Returns true if the compressed buffer is null.
bool IsOwned () const
Returns true if the composite buffer is owned.
FCompressedBuffer MakeOwned () &&
FCompressedBuffer MakeOwned () const &
Returns a copy of the compressed buffer that owns its underlying memory.
operator bool () const
Returns true if the compressed buffer is not null.
void Reset ()
Reset this to null.
void Save (FArchive &Ar) const
Save the compressed buffer to an archive.
bool TryDecompressTo (FMutableMemoryView RawView, ECompressedBufferDecompressFlags Flags=ECompressedBufferDecompressFlags::None) const
Decompress into a memory view that is exactly equal to the raw size.
bool TryGetCompressParameters (ECompressedBufferCompressor &OutCompressor, ECompressedBufferCompressionLevel &OutCompressionLevel, uint64 &OutBlockSize) const
Returns the compressor and compression level used by this buffer.
Static Public Member Functions
static FCompressedBuffer Compress (const FCompositeBuffer &RawData)
Compress the buffer using a balanced level of compression.
static FCompressedBuffer Compress (const FCompositeBuffer &RawData, ECompressedBufferCompressor Compressor, ECompressedBufferCompressionLevel CompressionLevel, uint64 BlockSize=0)
Compress the buffer using the specified compressor and compression level.
static FCompressedBuffer Compress (const FSharedBuffer &RawData)
static FCompressedBuffer Compress (const FSharedBuffer &RawData, ECompressedBufferCompressor Compressor, ECompressedBufferCompressionLevel CompressionLevel, uint64 BlockSize=0)
static FCompressedBuffer FromCompressed (const FCompositeBuffer &CompressedData)
Construct from a compressed buffer previously created by Compress().
static FCompressedBuffer FromCompressed (const FSharedBuffer &CompressedData)
static FCompressedBuffer FromCompressed (FCompositeBuffer &&CompressedData)
static FCompressedBuffer FromCompressed (FSharedBuffer &&CompressedData)
static FCompressedBuffer Load (FArchive &Ar)
Load a compressed buffer from an archive, as saved by Save().
Static Public Attributes
static const FCompressedBuffer Null
A null compressed buffer.
Private Attributes
FCompositeBuffer CompressedData
Detailed Description
A compressed buffer stores compressed data in a self-contained format.
A buffer is self-contained in the sense that it can be decompressed without external knowledge of the compression format or the size of the raw data.
The buffer may be partially decompressed using FCompressedBufferReader.
See also
FCompressedBufferReader
Definition at line 49 of file CompressedBuffer.h.
Member Function Documentation
Compress() [1/4]
FCompressedBuffer FCompressedBuffer::Compress (const FCompositeBuffer & RawData) static nodiscard
Compress the buffer using a balanced level of compression.
Returns
An owned compressed buffer, or null on error.
References RawData.
Referenced by FShaderCode::FinalizeShaderCode().
Compress() [2/4]
FCompressedBuffer FCompressedBuffer::Compress (const FCompositeBuffer & RawData, ECompressedBufferCompressor Compressor, ECompressedBufferCompressionLevel CompressionLevel, uint64 BlockSize = 0) static nodiscard
Compress the buffer using the specified compressor and compression level.
Data that does not compress will be return uncompressed, as if with level None.
Note
Using a level of None will return a buffer that references owned raw data.
Parameters
RawData The raw data to be compressed.
Compressor The compressor to encode with. May use NotSet if level is None.
CompressionLevel The compression level to encode with.
BlockSize The power-of-two block size to encode raw data in. 0 is default.
Returns
An owned compressed buffer, or null on error.
References RawData.
Compress() [3/4]
FCompressedBuffer FCompressedBuffer::Compress (const FSharedBuffer & RawData) static nodiscard
References RawData.
Compress() [4/4]
FCompressedBuffer FCompressedBuffer::Compress (const FSharedBuffer & RawData, ECompressedBufferCompressor Compressor, ECompressedBufferCompressionLevel CompressionLevel, uint64 BlockSize = 0) static nodiscard
References RawData.
Decompress()
FSharedBuffer FCompressedBuffer::Decompress () const nodiscard
Decompress into an owned buffer.
Returns
An owned buffer containing the raw data, or null on error.
DecompressToComposite()
FCompositeBuffer FCompressedBuffer::DecompressToComposite () const nodiscard
FromCompressed() [1/4]
FCompressedBuffer FCompressedBuffer::FromCompressed (const FCompositeBuffer & CompressedData) static nodiscard
Construct from a compressed buffer previously created by Compress().
Returns
A compressed buffer, or null on error, such as an invalid format or corrupt header.
References CompressedData.
Referenced by MakeOwned(), and MakeOwned().
FromCompressed() [2/4]
FCompressedBuffer FCompressedBuffer::FromCompressed (const FSharedBuffer & CompressedData) static nodiscard
References CompressedData.
FromCompressed() [3/4]
FCompressedBuffer FCompressedBuffer::FromCompressed (FCompositeBuffer && CompressedData) static nodiscard
References CompressedData.
FromCompressed() [4/4]
FCompressedBuffer FCompressedBuffer::FromCompressed (FSharedBuffer && CompressedData) static nodiscard
References CompressedData.
GetCompressed() [1/2]
FCompositeBuffer FCompressedBuffer::GetCompressed () && inline nodiscard
Definition at line 126 of file CompressedBuffer.h.
References CompressedData, and MoveTemp().
GetCompressed() [2/2]
const FCompositeBuffer & FCompressedBuffer::GetCompressed () const & inline nodiscard
Returns a composite buffer containing the compressed data.
May be null. May not be owned.
Definition at line 125 of file CompressedBuffer.h.
References CompressedData.
GetCompressedSize()
uint64 FCompressedBuffer::GetCompressedSize () const nodiscard
Returns the size of the compressed data.
Zero on error or if this is null.
GetRawHash()
FIoHash FCompressedBuffer::GetRawHash () const nodiscard
Returns the hash of the raw data.
Zero on error or if this is null.
GetRawSize()
uint64 FCompressedBuffer::GetRawSize () const nodiscard
Returns the size of the raw data.
Zero on error or if this is empty or null.
IsNull()
bool FCompressedBuffer::IsNull () const inline nodiscard
Returns true if the compressed buffer is null.
Definition at line 115 of file CompressedBuffer.h.
References CompressedData.
Referenced by FCbAttachment::FCbAttachment(), FCbAttachment::FCbAttachment(), FCbAttachment::FCbAttachment(), FCbAttachment::FCbAttachment(), and operator bool().
IsOwned()
bool FCompressedBuffer::IsOwned () const inline nodiscard
Returns true if the composite buffer is owned.
Definition at line 118 of file CompressedBuffer.h.
References CompressedData.
Load()
FCompressedBuffer FCompressedBuffer::Load (FArchive & Ar) static nodiscard
Load a compressed buffer from an archive, as saved by Save().
The entire compressed buffer will be loaded from the archive before this function returns. Prefer to use FCompressedBufferReader to stream from an archive when the compressed buffer does not need to be fully loaded into memory.
Returns
A compressed buffer, or null on error. Ar.IsError() will be true on error.
References Ar.
MakeOwned() [1/2]
FCompressedBuffer FCompressedBuffer::MakeOwned () && inline nodiscard
Definition at line 122 of file CompressedBuffer.h.
References CompressedData, FromCompressed(), MakeOwned(), and MoveTemp().
Referenced by MakeOwned().
MakeOwned() [2/2]
FCompressedBuffer FCompressedBuffer::MakeOwned () const & inline nodiscard
Returns a copy of the compressed buffer that owns its underlying memory.
Definition at line 121 of file CompressedBuffer.h.
References CompressedData, and FromCompressed().
operator bool()
FCompressedBuffer::operator bool () const inline explicit nodiscard
Returns true if the compressed buffer is not null.
Definition at line 112 of file CompressedBuffer.h.
References IsNull().
Reset()
void FCompressedBuffer::Reset () inline
Reset this to null.
Definition at line 109 of file CompressedBuffer.h.
References CompressedData.
Save()
void FCompressedBuffer::Save (FArchive & Ar) const
Save the compressed buffer to an archive.
References Ar.
TryDecompressTo()
bool FCompressedBuffer::TryDecompressTo (FMutableMemoryView RawView, ECompressedBufferDecompressFlags Flags = ECompressedBufferDecompressFlags::None) const nodiscard
Decompress into a memory view that is exactly equal to the raw size.
Returns
True if the requested range was decompressed, otherwise false.
References Flags, and None.
TryGetCompressParameters()
bool FCompressedBuffer::TryGetCompressParameters (ECompressedBufferCompressor & OutCompressor, ECompressedBufferCompressionLevel & OutCompressionLevel, uint64 & OutBlockSize) const nodiscard
Returns the compressor and compression level used by this buffer.
The compressor and compression level may differ from those specified when creating the buffer because an incompressible buffer is stored with no compression. Parameters cannot be accessed if this is null or uses a method other than Oodle, in which case this returns false.
Returns
True if parameters were written, otherwise false.
Field Documentation
CompressedData
FCompositeBuffer FCompressedBuffer::CompressedData private
Definition at line 171 of file CompressedBuffer.h.
Referenced by FromCompressed(), FromCompressed(), FromCompressed(), FromCompressed(), GetCompressed(), GetCompressed(), IsNull(), IsOwned(), MakeOwned(), MakeOwned(), and Reset().
Null
const FCompressedBuffer FCompressedBuffer::Null inline static
A null compressed buffer.
Definition at line 168 of file CompressedBuffer.h.
Referenced by FCbAttachment::AsCompressedBinary().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Compression/CompressedBuffer.h