Unreal Engine 5.6 C++ API: FCbFieldView Class Reference
FCbFieldView Class Reference
An atom of data in the compact binary format.
#include "CompactBinary.h"
Public Member Functions
constexpr FCbFieldView ()=default
Construct a field with no name and no value.
FCbFieldView (const FCbValue &Value)
Construct a field from a value, without access to the name.
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field from a pointer to its data and an optional externally-provided type.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the field, including the type and name.
FCbArrayView AsArrayView ()
Access the field as an array.
FIoHash AsAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an attachment.
FIoHash AsBinaryAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing a binary attachment.
FMemoryView AsBinaryView (FMemoryView Default=FMemoryView())
Access the field as binary.
bool AsBool (bool bDefault=false)
Access the field as a bool.
FMemoryView AsCustom (FUtf8StringView Name, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with a string identifier.
FMemoryView AsCustom (uint64 Id, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with an integer identifier.
FCbCustomById AsCustomById (FCbCustomById Default=FCbCustomById())
Access the field as a custom sub-type with an integer identifier.
FCbCustomByName AsCustomByName (FCbCustomByName Default=FCbCustomByName())
Access the field as a custom sub-type with a string identifier.
FDateTime AsDateTime ()
Access the field as a date/time.
FDateTime AsDateTime (FDateTime Default)
Access the field as a date/time.
int64 AsDateTimeTicks (int64 Default=0)
Access the field as a date/time tick count.
double AsDouble (double Default=0.0)
Access the field as a double.
float AsFloat (float Default=0.0f)
Access the field as a float.
FIoHash AsHash (const FIoHash &Default=FIoHash())
Access the field as a hash.
int16 AsInt16 (int16 Default=0)
Access the field as an int16.
int32 AsInt32 (int32 Default=0)
Access the field as an int32.
int64 AsInt64 (int64 Default=0)
Access the field as an int64.
int8 AsInt8 (int8 Default=0)
Access the field as an int8.
FIoHash AsObjectAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an object attachment.
FCbObjectId AsObjectId (const FCbObjectId &Default=FCbObjectId())
Access the field as an object identifier.
FCbObjectView AsObjectView ()
Access the field as an object.
FUtf8StringView AsString (FUtf8StringView Default=FUtf8StringView())
Access the field as a string.
FTimespan AsTimeSpan ()
Access the field as a timespan.
FTimespan AsTimeSpan (FTimespan Default)
Access the field as a timespan.
int64 AsTimeSpanTicks (int64 Default=0)
Access the field as a timespan tick count.
uint16 AsUInt16 (uint16 Default=0)
Access the field as a uint16.
uint32 AsUInt32 (uint32 Default=0)
Access the field as a uint32.
uint64 AsUInt64 (uint64 Default=0)
Access the field as a uint64.
uint8 AsUInt8 (uint8 Default=0)
Access the field as a uint8.
FGuid AsUuid ()
Access the field as a UUID.
FGuid AsUuid (const FGuid &Default)
Access the field as a UUID.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the field into an archive, including its type and name.
void CopyTo (FMutableMemoryView Buffer) const
Copy the field into a buffer of exactly GetSize() bytes, including the type and name.
FCbFieldViewIterator CreateViewIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbFieldView &Other) const
Whether this field is identical to the other field.
constexpr ECbFieldError GetError () const
The type of error that occurred on the last field access, or None.
FIoHash GetHash () const
Calculate the hash of the field, including the type and name.
constexpr FUtf8StringView GetName () const
Returns the name of the field if it has a name, otherwise an empty view.
uint64 GetSize () const
Returns the size of the field in bytes, including the type and name.
FCbValue GetValue () const
Returns the value for unchecked access.
constexpr bool HasError () const
Whether the last field access encountered an error.
constexpr bool HasName () const
True if the field has a name.
constexpr bool HasValue () const
Whether the field has a value.
constexpr bool IsArray () const
constexpr bool IsAttachment () const
constexpr bool IsBinary () const
constexpr bool IsBinaryAttachment () const
constexpr bool IsBool () const
constexpr bool IsCustomById () const
constexpr bool IsCustomByName () const
constexpr bool IsDateTime () const
constexpr bool IsFloat () const
Whether the field is a float, or integer that supports implicit conversion.
constexpr bool IsHash () const
constexpr bool IsInteger () const
Whether the field is an integer of unspecified range and sign.
constexpr bool IsNull () const
constexpr bool IsObject () const
constexpr bool IsObjectAttachment () const
constexpr bool IsObjectId () const
constexpr bool IsString () const
constexpr bool IsTimeSpan () const
constexpr bool IsUuid () const
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field.
constexpr operator bool () const
Whether the field has a value.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
constexpr FCbFieldView RemoveName () const
Returns a copy of the field with the name removed.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the field as it would be serialized, such as by CopyTo.
Protected Member Functions
void Assign (const void *InData, const ECbFieldType InType)
Assign a field from a pointer to its data and an optional externally-provided type.
constexpr ECbFieldType GetType () const
Returns the type of the field excluding flags.
constexpr ECbFieldType GetTypeWithFlags () const
Returns the type of the field including flags.
constexpr const void * GetValueData () const
Returns the start of the value.
const void * GetValueEnd () const
Returns the end of the value.
uint64 GetValueSize () const
Returns the size of the value in bytes, which is the field excluding the type and name.
FMemoryView GetValueView () const
Returns a view of the value, which excludes the type and name.
FMemoryView GetView () const
Returns a view of the field, including the type and name when present.
FMemoryView GetViewNoType () const
Returns a view of the name and value, which excludes the type.
Private Member Functions
template<typename IntType>
IntType AsInteger (IntType Default)
Access the field as the given integer type.
uint64 AsInteger (uint64 Default, UE::CompactBinary::Private::FIntegerParams Params)
Private Attributes
ECbFieldError Error = ECbFieldError::None
The error (if any) that occurred on the last field access.
uint32 NameLen = 0
The number of bytes for the name stored before the value.
ECbFieldType TypeWithFlags = ECbFieldType::None
The field type, with the transient HasFieldType flag if the field contains its type.
const void * Value = nullptr
The value, which also points to the end of the name.
Detailed Description
An atom of data in the compact binary format.
Accessing the value of a field is always a safe operation, even if accessed as the wrong type. An invalid access will return a default value for the requested type, and set an error code on the field that can be checked with GetLastError and HasLastError. A valid access will clear an error from a previous invalid access.
A field is encoded in one or more bytes, depending on its type and the type of object or array that contains it. A field of an object or array which is non-uniform encodes its field type in the first byte, and includes the HasFieldName flag for a field in an object. The field name is encoded in a variable-length unsigned integer of its size in bytes, for named fields, followed by that many bytes of the UTF-8 encoding of the name with no null terminator. The remainder of the field is the value which is described in the field type enum. Every field must be uniquely addressable when encoded, which means a zero-byte field is not permitted, and only arises in a uniform array of fields with no value, where the answer is to encode as a non-uniform array.
This type only provides a view into memory and does not perform any memory management itself. Use FCbField to hold a reference to the underlying memory when necessary.
Definition at line 609 of file CompactBinary.h.
Constructor & Destructor Documentation
FCbFieldView() [1/3]
FCbFieldView::FCbFieldView () constexpr default
Construct a field with no name and no value.
Referenced by Assign(), Equals(), FCbFieldViewIterator::MakeRange(), operator[](), and RemoveName().
FCbFieldView() [2/3]
FCbFieldView::FCbFieldView (const void * Data, ECbFieldType Type = ECbFieldType::HasFieldType) explicit
Construct a field from a pointer to its data and an optional externally-provided type.
Parameters
Data Pointer to the start of the field data.
Type HasFieldType means that Data contains the type. Otherwise, use the given type.
References HasFieldType, and Value.
FCbFieldView() [3/3]
FORCEINLINE FCbFieldView::FCbFieldView (const FCbValue & Value) inline explicit
Construct a field from a value, without access to the name.
Definition at line 72 of file CompactBinaryValue.h.
References FORCEINLINE, GetData(), GetType(), TypeWithFlags, and Value.
Member Function Documentation
AppendHash()
void FCbFieldView::AppendHash (FIoHashBuilder & Builder) const
Append the hash of the field, including the type and name.
AsArrayView()
FCbArrayView FCbFieldView::AsArrayView () nodiscard
Access the field as an array.
Defaults to an empty array on error.
Referenced by FCbField::AsArray(), FCbField::AsArray(), LoadFromCompactBinary(), and LoadFromCompactBinary().
AsAttachment()
FIoHash FCbFieldView::AsAttachment (const FIoHash & Default = FIoHash()) nodiscard
Access the field as a hash referencing an attachment.
Returns the provided default on error.
References Default.
AsBinaryAttachment()
FIoHash FCbFieldView::AsBinaryAttachment (const FIoHash & Default = FIoHash()) nodiscard
Access the field as a hash referencing a binary attachment.
Returns the provided default on error.
References Default.
AsBinaryView()
FMemoryView FCbFieldView::AsBinaryView (FMemoryView Default = FMemoryView()) nodiscard
Access the field as binary.
Returns the provided default on error.
References Default.
Referenced by FCbField::AsBinary(), and FCbField::AsBinary().
AsBool()
bool FCbFieldView::AsBool (bool bDefault = false) nodiscard
Access the field as a bool.
Returns the provided default on error.
Referenced by LoadFromCompactBinary().
AsCustom() [1/2]
FMemoryView FCbFieldView::AsCustom (FUtf8StringView Name, FMemoryView Default = FMemoryView()) nodiscard
Access the field as a custom sub-type with a string identifier.
Returns the provided default on error.
References Default, and Name.
AsCustom() [2/2]
FMemoryView FCbFieldView::AsCustom (uint64 Id, FMemoryView Default = FMemoryView()) nodiscard
Access the field as a custom sub-type with an integer identifier.
Returns the provided default on error.
References Default.
AsCustomById()
FCbCustomById FCbFieldView::AsCustomById (FCbCustomById Default = FCbCustomById()) nodiscard
Access the field as a custom sub-type with an integer identifier.
Returns the provided default on error.
References Default.
AsCustomByName()
FCbCustomByName FCbFieldView::AsCustomByName (FCbCustomByName Default = FCbCustomByName()) nodiscard
Access the field as a custom sub-type with a string identifier.
Returns the provided default on error.
References Default.
AsDateTime() [1/2]
FDateTime FCbFieldView::AsDateTime () nodiscard
Access the field as a date/time.
Returns a date/time at the epoch on error.
AsDateTime() [2/2]
FDateTime FCbFieldView::AsDateTime (FDateTime Default) nodiscard
Access the field as a date/time.
Returns the provided default on error.
References Default.
AsDateTimeTicks()
int64 FCbFieldView::AsDateTimeTicks (int64 Default = 0) nodiscard
Access the field as a date/time tick count.
Returns the provided default on error.
References Default.
AsDouble()
double FCbFieldView::AsDouble (double Default = 0.0) nodiscard
Access the field as a double.
Returns the provided default on error.
References Default.
Referenced by LoadFromCompactBinary().
AsFloat()
float FCbFieldView::AsFloat (float Default = 0.0f) nodiscard
Access the field as a float.
Returns the provided default on error.
References Default.
Referenced by LoadFromCompactBinary().
AsHash()
FIoHash FCbFieldView::AsHash (const FIoHash & Default = FIoHash()) nodiscard
Access the field as a hash.
Returns the provided default on error.
References Default.
Referenced by LoadFromCompactBinary().
AsInt16()
int16 FCbFieldView::AsInt16 (int16 Default = 0) inline nodiscard
Access the field as an int16.
Returns the provided default on error.
Definition at line 659 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsInt32()
int32 FCbFieldView::AsInt32 (int32 Default = 0) inline nodiscard
Access the field as an int32.
Returns the provided default on error.
Definition at line 661 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsInt64()
int64 FCbFieldView::AsInt64 (int64 Default = 0) inline nodiscard
Access the field as an int64.
Returns the provided default on error.
Definition at line 663 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsInt8()
int8 FCbFieldView::AsInt8 (int8 Default = 0) inline nodiscard
Access the field as an int8.
Returns the provided default on error.
Definition at line 657 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsInteger() [1/2]
template<typename IntType> IntType FCbFieldView::AsInteger (IntType Default) inline private
Access the field as the given integer type.
Returns the provided default if the value cannot be represented in the output type.
Definition at line 868 of file CompactBinary.h.
References AsInteger(), Default, and UE::CompactBinary::Private::MakeIntegerParams().
Referenced by AsInt16(), AsInt32(), AsInt64(), AsInt8(), AsInteger(), AsUInt16(), AsUInt32(), AsUInt64(), and AsUInt8().
AsInteger() [2/2]
uint64 FCbFieldView::AsInteger (uint64 Default, UE::CompactBinary::Private::FIntegerParams Params) private
References Default, and Params.
AsObjectAttachment()
FIoHash FCbFieldView::AsObjectAttachment (const FIoHash & Default = FIoHash()) nodiscard
Access the field as a hash referencing an object attachment.
Returns the provided default on error.
References Default.
AsObjectId()
FCbObjectId FCbFieldView::AsObjectId (const FCbObjectId & Default = FCbObjectId()) nodiscard
Access the field as an object identifier.
Returns the provided default on error.
References Default.
Referenced by LoadFromCompactBinary().
AsObjectView()
FCbObjectView FCbFieldView::AsObjectView () nodiscard
Access the field as an object.
Defaults to an empty object on error.
Referenced by FCbField::AsObject(), and FCbField::AsObject().
Assign()
void FCbFieldView::Assign (const void * InData, const ECbFieldType InType) inline protected
Assign a field from a pointer to its data and an optional externally-provided type.
Definition at line 854 of file CompactBinary.h.
References FCbFieldView().
AsString()
FUtf8StringView FCbFieldView::AsString (FUtf8StringView Default = FUtf8StringView()) nodiscard
Access the field as a string.
Returns the provided default on error.
References Default.
AsTimeSpan() [1/2]
FTimespan FCbFieldView::AsTimeSpan () nodiscard
Access the field as a timespan.
Returns an empty timespan on error.
AsTimeSpan() [2/2]
FTimespan FCbFieldView::AsTimeSpan (FTimespan Default) nodiscard
Access the field as a timespan.
Returns the provided default on error.
References Default.
AsTimeSpanTicks()
int64 FCbFieldView::AsTimeSpanTicks (int64 Default = 0) nodiscard
Access the field as a timespan tick count.
Returns the provided default on error.
References Default.
AsUInt16()
uint16 FCbFieldView::AsUInt16 (uint16 Default = 0) inline nodiscard
Access the field as a uint16.
Returns the provided default on error.
Definition at line 667 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsUInt32()
uint32 FCbFieldView::AsUInt32 (uint32 Default = 0) inline nodiscard
Access the field as a uint32.
Returns the provided default on error.
Definition at line 669 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsUInt64()
uint64 FCbFieldView::AsUInt64 (uint64 Default = 0) inline nodiscard
Access the field as a uint64.
Returns the provided default on error.
Definition at line 671 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsUInt8()
uint8 FCbFieldView::AsUInt8 (uint8 Default = 0) inline nodiscard
Access the field as a uint8.
Returns the provided default on error.
Definition at line 665 of file CompactBinary.h.
References AsInteger(), and Default.
Referenced by LoadFromCompactBinary().
AsUuid() [1/2]
FGuid FCbFieldView::AsUuid () nodiscard
Access the field as a UUID.
Returns a nil UUID on error.
AsUuid() [2/2]
FGuid FCbFieldView::AsUuid (const FGuid & Default) nodiscard
Access the field as a UUID.
Returns the provided default on error.
References Default.
begin()
FCbFieldViewIterator FCbFieldView::begin () const inline
DO NOT USE DIRECTLY.
These functions enable range-based for loop support.
Definition at line 925 of file CompactBinary.h.
References CreateViewIterator().
CopyTo() [1/2]
void FCbFieldView::CopyTo (FArchive & Ar) const
Copy the field into an archive, including its type and name.
References Ar.
CopyTo() [2/2]
void FCbFieldView::CopyTo (FMutableMemoryView Buffer) const
Copy the field into a buffer of exactly GetSize() bytes, including the type and name.
References Buffer.
CreateViewIterator()
FCbFieldViewIterator FCbFieldView::CreateViewIterator () const nodiscard
Create an iterator for the fields of an array or object, otherwise an empty iterator.
Referenced by begin(), and LoadFromCompactBinary().
end()
FCbIteratorSentinel FCbFieldView::end () const inline constexpr
Definition at line 826 of file CompactBinary.h.
Equals()
bool FCbFieldView::Equals (const FCbFieldView & Other) const
Whether this field is identical to the other field.
Performs a deep comparison of any contained arrays or objects and their fields. Comparison assumes that both fields are valid and are written in the canonical format. Fields must be written in the same order in arrays and objects, and name comparison is case sensitive. If these assumptions do not hold, this may return false for equivalent inputs. Validation can be performed with ValidateCompactBinary, except for field order and field name case.
References FCbFieldView(), and Other.
GetError()
ECbFieldError FCbFieldView::GetError () const inline nodiscard constexpr
The type of error that occurred on the last field access, or None.
Definition at line 772 of file CompactBinary.h.
References Error.
GetHash()
FIoHash FCbFieldView::GetHash () const nodiscard
Calculate the hash of the field, including the type and name.
GetName()
FUtf8StringView FCbFieldView::GetName () const inline nodiscard constexpr
Returns the name of the field if it has a name, otherwise an empty view.
Definition at line 636 of file CompactBinary.h.
References NameLen, and Value.
GetSize()
uint64 FCbFieldView::GetSize () const nodiscard
Returns the size of the field in bytes, including the type and name.
GetType()
ECbFieldType FCbFieldView::GetType () const inline constexpr protected
Returns the type of the field excluding flags.
Definition at line 839 of file CompactBinary.h.
References FCbFieldType::GetType(), and TypeWithFlags.
Referenced by FCbFieldView().
GetTypeWithFlags()
ECbFieldType FCbFieldView::GetTypeWithFlags () const inline constexpr protected
Returns the type of the field including flags.
Definition at line 842 of file CompactBinary.h.
References TypeWithFlags.
GetValue()
FORCEINLINE FCbValue FCbFieldView::GetValue () const inline nodiscard
Returns the value for unchecked access.
Prefer the typed accessors below.
Definition at line 78 of file CompactBinaryValue.h.
References FORCEINLINE, FCbFieldType::GetType(), TypeWithFlags, and Value.
GetValueData()
const void * FCbFieldView::GetValueData () const inline constexpr protected
Returns the start of the value.
Definition at line 845 of file CompactBinary.h.
References Value.
GetValueEnd()
const void * FCbFieldView::GetValueEnd () const inline protected
Returns the end of the value.
Definition at line 848 of file CompactBinary.h.
References GetValueSize(), and Value.
GetValueSize()
uint64 FCbFieldView::GetValueSize () const protected
Returns the size of the value in bytes, which is the field excluding the type and name.
Referenced by GetValueEnd(), and GetValueView().
GetValueView()
FMemoryView FCbFieldView::GetValueView () const inline protected
Returns a view of the value, which excludes the type and name.
Definition at line 836 of file CompactBinary.h.
References GetValueSize(), MakeMemoryView(), and Value.
GetView()
FMemoryView FCbFieldView::GetView () const protected
Returns a view of the field, including the type and name when present.
Referenced by TryGetView().
GetViewNoType()
FMemoryView FCbFieldView::GetViewNoType () const protected
Returns a view of the name and value, which excludes the type.
HasError()
bool FCbFieldView::HasError () const inline constexpr
Whether the last field access encountered an error.
Definition at line 769 of file CompactBinary.h.
References Error, and None.
Referenced by FCbField::AsArray(), FCbField::AsArray(), FCbField::AsBinary(), FCbField::AsBinary(), FCbField::AsObject(), FCbField::AsObject(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), LoadFromCompactBinary(), and LoadFromCompactBinary().
HasName()
bool FCbFieldView::HasName () const inline constexpr
True if the field has a name.
Definition at line 726 of file CompactBinary.h.
References FCbFieldType::HasFieldName(), and TypeWithFlags.
Referenced by FCbArrayView::TryGetView(), and FCbObjectView::TryGetView().
HasValue()
bool FCbFieldView::HasValue () const inline constexpr
Whether the field has a value.
All fields in a valid object or array have a value. A field with no value is returned when finding a field by name fails or when accessing an iterator past the end.
Definition at line 766 of file CompactBinary.h.
References FCbFieldType::IsNone(), and TypeWithFlags.
Referenced by operator bool().
IsArray()
bool FCbFieldView::IsArray () const inline constexpr
Definition at line 731 of file CompactBinary.h.
References FCbFieldType::IsArray(), and TypeWithFlags.
IsAttachment()
bool FCbFieldView::IsAttachment () const inline constexpr
Definition at line 744 of file CompactBinary.h.
References FCbFieldType::IsAttachment(), and TypeWithFlags.
IsBinary()
bool FCbFieldView::IsBinary () const inline constexpr
Definition at line 733 of file CompactBinary.h.
References FCbFieldType::IsBinary(), and TypeWithFlags.
IsBinaryAttachment()
bool FCbFieldView::IsBinaryAttachment () const inline constexpr
Definition at line 743 of file CompactBinary.h.
References FCbFieldType::IsBinaryAttachment(), and TypeWithFlags.
IsBool()
bool FCbFieldView::IsBool () const inline constexpr
Definition at line 740 of file CompactBinary.h.
References FCbFieldType::IsBool(), and TypeWithFlags.
IsCustomById()
bool FCbFieldView::IsCustomById () const inline constexpr
Definition at line 754 of file CompactBinary.h.
References FCbFieldType::IsCustomById(), and TypeWithFlags.
IsCustomByName()
bool FCbFieldView::IsCustomByName () const inline constexpr
Definition at line 755 of file CompactBinary.h.
References FCbFieldType::IsCustomByName(), and TypeWithFlags.
IsDateTime()
bool FCbFieldView::IsDateTime () const inline constexpr
Definition at line 749 of file CompactBinary.h.
References FCbFieldType::IsDateTime(), and TypeWithFlags.
IsFloat()
bool FCbFieldView::IsFloat () const inline constexpr
Whether the field is a float, or integer that supports implicit conversion.
Definition at line 739 of file CompactBinary.h.
References FCbFieldType::IsFloat(), and TypeWithFlags.
IsHash()
bool FCbFieldView::IsHash () const inline constexpr
Definition at line 746 of file CompactBinary.h.
References FCbFieldType::IsHash(), and TypeWithFlags.
IsInteger()
bool FCbFieldView::IsInteger () const inline constexpr
Whether the field is an integer of unspecified range and sign.
Definition at line 737 of file CompactBinary.h.
References FCbFieldType::IsInteger(), and TypeWithFlags.
IsNull()
bool FCbFieldView::IsNull () const inline constexpr
Definition at line 728 of file CompactBinary.h.
References FCbFieldType::IsNull(), and TypeWithFlags.
IsObject()
bool FCbFieldView::IsObject () const inline constexpr
Definition at line 730 of file CompactBinary.h.
References FCbFieldType::IsObject(), and TypeWithFlags.
IsObjectAttachment()
bool FCbFieldView::IsObjectAttachment () const inline constexpr
Definition at line 742 of file CompactBinary.h.
References FCbFieldType::IsObjectAttachment(), and TypeWithFlags.
IsObjectId()
bool FCbFieldView::IsObjectId () const inline constexpr
Definition at line 752 of file CompactBinary.h.
References FCbFieldType::IsObjectId(), and TypeWithFlags.
IsString()
bool FCbFieldView::IsString () const inline constexpr
Definition at line 734 of file CompactBinary.h.
References FCbFieldType::IsString(), and TypeWithFlags.
IsTimeSpan()
bool FCbFieldView::IsTimeSpan () const inline constexpr
Definition at line 750 of file CompactBinary.h.
References FCbFieldType::IsTimeSpan(), and TypeWithFlags.
IsUuid()
bool FCbFieldView::IsUuid () const inline constexpr
Definition at line 747 of file CompactBinary.h.
References FCbFieldType::IsUuid(), and TypeWithFlags.
IterateAttachments()
void FCbFieldView::IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field.
operator bool()
FCbFieldView::operator bool () const inline explicit constexpr
Whether the field has a value.
Definition at line 758 of file CompactBinary.h.
References HasValue().
operator[]()
FCbFieldView FCbFieldView::operator[] (FUtf8StringView Name) const nodiscard
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
References FCbFieldView(), and Name.
RemoveName()
FCbFieldView FCbFieldView::RemoveName () const inline nodiscard constexpr
Returns a copy of the field with the name removed.
Definition at line 627 of file CompactBinary.h.
References FCbFieldView(), HasFieldName, HasFieldType, TypeWithFlags, and Value.
Referenced by FCbArrayView::AsFieldView(), and FCbObjectView::AsFieldView().
TryGetView()
bool FCbFieldView::TryGetView (FMemoryView & OutView) const inline
Try to get a view of the field as it would be serialized, such as by CopyTo.
A view is available if the field contains its type. Access the equivalent for other fields through FCbField::GetBuffer, FCbField::Clone, or CopyTo.
Definition at line 808 of file CompactBinary.h.
References GetView(), FCbFieldType::HasFieldType(), and TypeWithFlags.
Referenced by FCbArrayView::TryGetView(), and FCbObjectView::TryGetView().
Field Documentation
Error
ECbFieldError FCbFieldView::Error = ECbFieldError::None private
The error (if any) that occurred on the last field access.
Definition at line 879 of file CompactBinary.h.
Referenced by GetError(), and HasError().
NameLen
uint32 FCbFieldView::NameLen = 0 private
The number of bytes for the name stored before the value.
Definition at line 881 of file CompactBinary.h.
Referenced by GetName().
TypeWithFlags
ECbFieldType FCbFieldView::TypeWithFlags = ECbFieldType::None private
The field type, with the transient HasFieldType flag if the field contains its type.
Definition at line 877 of file CompactBinary.h.
Referenced by FCbFieldView(), GetType(), GetTypeWithFlags(), GetValue(), HasName(), HasValue(), IsArray(), IsAttachment(), IsBinary(), IsBinaryAttachment(), IsBool(), IsCustomById(), IsCustomByName(), IsDateTime(), IsFloat(), IsHash(), IsInteger(), IsNull(), IsObject(), IsObjectAttachment(), IsObjectId(), IsString(), IsTimeSpan(), IsUuid(), RemoveName(), and TryGetView().
Value
const void* FCbFieldView::Value = nullptr private
The value, which also points to the end of the name.
Definition at line 883 of file CompactBinary.h.
Referenced by FCbFieldView(), FCbFieldView(), GetName(), GetValue(), GetValueData(), GetValueEnd(), GetValueView(), and RemoveName().
The documentation for this class was generated from the following files:
Runtime/Core/Public/Serialization/CompactBinary.h
Runtime/Core/Public/Serialization/CompactBinaryValue.h