Unreal Engine 5.6 C++ API: LowLevelTasks::FScheduler Class Reference
LowLevelTasks::FScheduler Class Reference final
#include "Scheduler.h"
Public Member Functions
FScheduler ()=default
~FScheduler ()
EThreadPriority GetBackgroundPriority () const
uint32 GetNumWorkers () const
FOversubscriptionLimitReached & GetOversubscriptionLimitReachedEvent ()
EThreadPriority GetWorkerPriority () const
bool IsOversubscriptionLimitReached (ETaskPriority TaskPriority) const
void RestartWorkers (uint32 NumForegroundWorkers=0, uint32 NumBackgroundWorkers=0, FThread::EForkable IsForkable=FThread::NonForkable, EThreadPriority WorkerPriority=EThreadPriority::TPri_Normal, EThreadPriority BackgroundPriority=EThreadPriority::TPri_BelowNormal, uint64 InWorkerAffinity=0, uint64 InBackgroundAffinity=0)
void StartWorkers (uint32 NumForegroundWorkers=0, uint32 NumBackgroundWorkers=0, FThread::EForkable IsForkable=FThread::NonForkable, EThreadPriority InWorkerPriority=EThreadPriority::TPri_Normal, EThreadPriority InBackgroundPriority=EThreadPriority::TPri_BelowNormal, uint64 InWorkerAffinity=0, uint64 InBackgroundAffinity=0)
void StopWorkers (bool DrainGlobalQueue=true)
bool TryLaunch (FTask &Task, EQueuePreference QueuePreference=EQueuePreference::DefaultPreference, bool bWakeUpWorker=true)
template<typename TaskType>
UE_DEPRECATED (5.5, "This method will be removed.") inline void BusyWait(const TArrayView< const TaskType > &Tasks
template<typename TaskType>
UE_DEPRECATED (5.5, "This method will be removed.") inline void BusyWait(const TaskType &Task
template<typename Conditional>
UE_DEPRECATED (5.5, "This method will be removed.") inline void BusyWaitUntil(Conditional &&Cond
Public Member Functions inherited from LowLevelTasks::FSchedulerTls
bool IsWorkerThread () const
Static Public Member Functions
static FORCEINLINE_DEBUGGABLE FScheduler & Get ()
Static Public Member Functions inherited from LowLevelTasks::FSchedulerTls
static bool IsBusyWaiting ()
Data Fields
bool ForceAllowBackgroundWork = false)
Private Types
using FConditional = TTaskDelegate<bool(), 16>
Private Member Functions
void BusyWaitInternal (const FConditional &Conditional, bool ForceAllowBackgroundWork)
TUniquePtr< FThread > CreateWorker (uint32 WorkerId, const TCHAR *Name, bool bPermitBackgroundWork=false, FThread::EForkable IsForkable=FThread::NonForkable, Private::FWaitEvent *ExternalWorkerEvent=nullptr, FSchedulerTls::FLocalQueueType *ExternalWorkerLocalQueue=nullptr, EThreadPriority Priority=EThreadPriority::TPri_Normal, uint64 InAffinity=0)
void DecrementOversubscription ()
FTask * ExecuteTask (FTask *InTask)
void IncrementOversubscription ()
void LaunchInternal (FTask &Task, EQueuePreference QueuePreference, bool bWakeUpWorker)
void StandbyLoop (Private::FWaitEvent *WorkerEvent, FSchedulerTls::FLocalQueueType *ExternalWorkerLocalQueue, uint32 WaitCycles, bool bPermitBackgroundWork)
template<typename QueueType, FTask *(QueueType::*)(bool) DequeueFunction, bool bIsStandbyWorker>
bool TryExecuteTaskFrom (Private::FWaitEvent *WaitEvent, QueueType *Queue, Private::FOutOfWork &OutOfWork, bool bPermitBackgroundWork)
UE_NONCOPYABLE (FScheduler)
bool WakeUpWorker (bool bBackgroundWorker)
void WorkerLoop (Private::FWaitEvent *WorkerEvent, FSchedulerTls::FLocalQueueType *ExternalWorkerLocalQueue, uint32 WaitCycles, bool bPermitBackgroundWork)
void WorkerMain (Private::FWaitEvent *WorkerEvent, FSchedulerTls::FLocalQueueType *ExternalWorkerLocalQueue, uint32 WaitCycles, bool bPermitBackgroundWork)
Private Attributes
std::atomic_uint ActiveWorkers { 0 }
uint64 BackgroundAffinity = 0
std::atomic< int32 > BackgroundCreationIndex { 0 }
EThreadPriority BackgroundPriority = EThreadPriority::TPri_BelowNormal
std::atomic< int32 > ForegroundCreationIndex { 0 }
TUniquePtr< FSchedulerTls::FLocalQueueType > GameThreadLocalQueue
std::atomic_uint NextWorkerId { 0 }
FOversubscriptionLimitReached OversubscriptionLimitReachedEvent
FSchedulerTls::FQueueRegistry QueueRegistry
std::atomic_bool TemporaryShutdown { false }
Private::FWaitingQueue WaitingQueue [2] = { { WorkerEvents, OversubscriptionLimitReachedEvent }, { WorkerEvents, OversubscriptionLimitReachedEvent } }
uint64 WorkerAffinity = 0
UE::FPlatformRecursiveMutex WorkerCreationCS
TAlignedArray< Private::FWaitEvent > WorkerEvents
TAlignedArray< FSchedulerTls::FLocalQueueType > WorkerLocalQueues
EThreadPriority WorkerPriority = EThreadPriority::TPri_Normal
TArray< std::atomic< FThread * > > WorkerThreads
UE::FPlatformRecursiveMutex WorkerThreadsCS
Static Private Attributes
static FScheduler Singleton
static constexpr uint32 WorkerSpinCycles = 53
Friends
class FOversubscriptionScope
Additional Inherited Members
Protected Types inherited from LowLevelTasks::FSchedulerTls
enum class EWorkerType { None , Background , Foreground }
using FLocalQueueType = FQueueRegistry::TLocalQueue
using FQueueRegistry = Private::TLocalQueueRegistry<>
Protected Member Functions inherited from LowLevelTasks::FSchedulerTls
bool HasPendingWakeUp () const
Static Protected Member Functions inherited from LowLevelTasks::FSchedulerTls
static FTlsValues & GetTlsValuesRef ()
Detailed Description
Definition at line 179 of file Scheduler.h.
Member Typedef Documentation
FConditional
using LowLevelTasks::FScheduler::FConditional = TTaskDelegate<bool(), 16> private
Definition at line 187 of file Scheduler.h.
Constructor & Destructor Documentation
FScheduler()
LowLevelTasks::FScheduler::FScheduler () default
Referenced by Get(), and UE_NONCOPYABLE().
~FScheduler()
LowLevelTasks::FScheduler::~FScheduler ()
Member Function Documentation
BusyWaitInternal()
void LowLevelTasks::FScheduler::BusyWaitInternal (const FConditional & Conditional, bool ForceAllowBackgroundWork) private
References Conditional, and ForceAllowBackgroundWork.
CreateWorker()
TUniquePtr< FThread > LowLevelTasks::FScheduler::CreateWorker (uint32 WorkerId, const TCHAR * Name, bool bPermitBackgroundWork = false, FThread::EForkable IsForkable = FThread::NonForkable, Private::FWaitEvent * ExternalWorkerEvent = nullptr, FSchedulerTls::FLocalQueueType * ExternalWorkerLocalQueue = nullptr, EThreadPriority Priority = EThreadPriority::TPri_Normal, uint64 InAffinity = 0) private
References Name, FThread::NonForkable, and TPri_Normal.
DecrementOversubscription()
void LowLevelTasks::FScheduler::DecrementOversubscription () private
Referenced by LowLevelTasks::FOversubscriptionScope::~FOversubscriptionScope().
ExecuteTask()
FTask * LowLevelTasks::FScheduler::ExecuteTask (FTask * InTask) nodiscard private
Get()
FORCEINLINE_DEBUGGABLE FScheduler & LowLevelTasks::FScheduler::Get () static
References FScheduler(), and FORCEINLINE_DEBUGGABLE.
Referenced by LowLevelTasks::FOversubscriptionScope::FOversubscriptionScope(), FQueuedLowLevelThreadPool::FQueuedLowLevelThreadPool(), LowLevelTasks::FOversubscriptionScope::~FOversubscriptionScope(), ENUM_CLASS_FLAGS(), LowLevelTasks::TryLaunch(), and LowLevelTasks::UE_DEPRECATED().
GetBackgroundPriority()
EThreadPriority LowLevelTasks::FScheduler::GetBackgroundPriority () const inline
Definition at line 223 of file Scheduler.h.
References BackgroundPriority.
GetNumWorkers()
uint32 LowLevelTasks::FScheduler::GetNumWorkers () const inline
References GetNumWorkers().
Referenced by GetNumWorkers().
GetOversubscriptionLimitReachedEvent()
FOversubscriptionLimitReached & LowLevelTasks::FScheduler::GetOversubscriptionLimitReachedEvent ()
GetWorkerPriority()
EThreadPriority LowLevelTasks::FScheduler::GetWorkerPriority () const inline
Definition at line 220 of file Scheduler.h.
References GetWorkerPriority(), and WorkerPriority.
Referenced by GetWorkerPriority().
IncrementOversubscription()
void LowLevelTasks::FScheduler::IncrementOversubscription () private
Referenced by LowLevelTasks::FOversubscriptionScope::FOversubscriptionScope().
IsOversubscriptionLimitReached()
bool LowLevelTasks::FScheduler::IsOversubscriptionLimitReached (ETaskPriority TaskPriority) const
LaunchInternal()
void LowLevelTasks::FScheduler::LaunchInternal (FTask & Task, EQueuePreference QueuePreference, bool bWakeUpWorker) private
RestartWorkers()
void LowLevelTasks::FScheduler::RestartWorkers (uint32 NumForegroundWorkers = 0, uint32 NumBackgroundWorkers = 0, FThread::EForkable IsForkable = FThread::NonForkable, EThreadPriority WorkerPriority = EThreadPriority::TPri_Normal, EThreadPriority BackgroundPriority = EThreadPriority::TPri_BelowNormal, uint64 InWorkerAffinity = 0, uint64 InBackgroundAffinity = 0)
References BackgroundPriority, FThread::NonForkable, TPri_BelowNormal, TPri_Normal, and WorkerPriority.
StandbyLoop()
void LowLevelTasks::FScheduler::StandbyLoop (Private::FWaitEvent * WorkerEvent, FSchedulerTls::FLocalQueueType * ExternalWorkerLocalQueue, uint32 WaitCycles, bool bPermitBackgroundWork) private
StartWorkers()
void LowLevelTasks::FScheduler::StartWorkers (uint32 NumForegroundWorkers = 0, uint32 NumBackgroundWorkers = 0, FThread::EForkable IsForkable = FThread::NonForkable, EThreadPriority InWorkerPriority = EThreadPriority::TPri_Normal, EThreadPriority InBackgroundPriority = EThreadPriority::TPri_BelowNormal, uint64 InWorkerAffinity = 0, uint64 InBackgroundAffinity = 0)
References FThread::NonForkable, TPri_BelowNormal, and TPri_Normal.
StopWorkers()
void LowLevelTasks::FScheduler::StopWorkers (bool DrainGlobalQueue = true)
TryExecuteTaskFrom()
template<typename QueueType, FTask *(QueueType::*)(bool) DequeueFunction, bool bIsStandbyWorker> bool LowLevelTasks::FScheduler::TryExecuteTaskFrom (Private::FWaitEvent * WaitEvent, QueueType * Queue, Private::FOutOfWork & OutOfWork, bool bPermitBackgroundWork) private
TryLaunch()
bool LowLevelTasks::FScheduler::TryLaunch (FTask & Task, EQueuePreference QueuePreference = EQueuePreference::DefaultPreference, bool bWakeUpWorker = true) inline
References LowLevelTasks::DefaultPreference.
Referenced by LowLevelTasks::TryLaunch().
UE_DEPRECATED() [1/3]
template<typename TaskType> LowLevelTasks::FScheduler::UE_DEPRECATED (5. 5, "This method will be removed.") const &
References ForceAllowBackgroundWork, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
template<typename TaskType> LowLevelTasks::FScheduler::UE_DEPRECATED (5. 5, "This method will be removed.") const &
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
template<typename Conditional> LowLevelTasks::FScheduler::UE_DEPRECATED (5. 5, "This method will be removed.") &&
References Conditional, ForceAllowBackgroundWork, and UE_DEPRECATED().
UE_NONCOPYABLE()
LowLevelTasks::FScheduler::UE_NONCOPYABLE (FScheduler) private
References FScheduler().
WakeUpWorker()
bool LowLevelTasks::FScheduler::WakeUpWorker (bool bBackgroundWorker) inline private
WorkerLoop()
void LowLevelTasks::FScheduler::WorkerLoop (Private::FWaitEvent * WorkerEvent, FSchedulerTls::FLocalQueueType * ExternalWorkerLocalQueue, uint32 WaitCycles, bool bPermitBackgroundWork) private
WorkerMain()
void LowLevelTasks::FScheduler::WorkerMain (Private::FWaitEvent * WorkerEvent, FSchedulerTls::FLocalQueueType * ExternalWorkerLocalQueue, uint32 WaitCycles, bool bPermitBackgroundWork) private
Friends And Related Symbol Documentation
FOversubscriptionScope
friend class FOversubscriptionScope friend
Definition at line 251 of file Scheduler.h.
References FOversubscriptionScope.
Referenced by FOversubscriptionScope.
Field Documentation
ActiveWorkers
std::atomic_uint LowLevelTasks::FScheduler::ActiveWorkers { 0 } private
Definition at line 261 of file Scheduler.h.
BackgroundAffinity
uint64 LowLevelTasks::FScheduler::BackgroundAffinity = 0 private
Definition at line 266 of file Scheduler.h.
BackgroundCreationIndex
std::atomic<int32> LowLevelTasks::FScheduler::BackgroundCreationIndex { 0 } private
Definition at line 264 of file Scheduler.h.
BackgroundPriority
EThreadPriority LowLevelTasks::FScheduler::BackgroundPriority = EThreadPriority::TPri_BelowNormal private
Definition at line 268 of file Scheduler.h.
Referenced by GetBackgroundPriority(), and RestartWorkers().
ForceAllowBackgroundWork
bool LowLevelTasks::FScheduler::ForceAllowBackgroundWork = false)
Definition at line 203 of file Scheduler.h.
Referenced by BusyWaitInternal(), UE_DEPRECATED(), and UE_DEPRECATED().
ForegroundCreationIndex
std::atomic<int32> LowLevelTasks::FScheduler::ForegroundCreationIndex { 0 } private
Definition at line 263 of file Scheduler.h.
GameThreadLocalQueue
TUniquePtr<FSchedulerTls::FLocalQueueType> LowLevelTasks::FScheduler::GameThreadLocalQueue private
Definition at line 260 of file Scheduler.h.
NextWorkerId
std::atomic_uint LowLevelTasks::FScheduler::NextWorkerId { 0 } private
Definition at line 262 of file Scheduler.h.
OversubscriptionLimitReachedEvent
FOversubscriptionLimitReached LowLevelTasks::FScheduler::OversubscriptionLimitReachedEvent private
Definition at line 270 of file Scheduler.h.
QueueRegistry
FSchedulerTls::FQueueRegistry LowLevelTasks::FScheduler::QueueRegistry private
Definition at line 254 of file Scheduler.h.
Singleton
FScheduler LowLevelTasks::FScheduler::Singleton static private
Definition at line 184 of file Scheduler.h.
TemporaryShutdown
std::atomic_bool LowLevelTasks::FScheduler::TemporaryShutdown { false } private
Definition at line 269 of file Scheduler.h.
WaitingQueue
Private::FWaitingQueue LowLevelTasks::FScheduler::WaitingQueue[2] = { { WorkerEvents, OversubscriptionLimitReachedEvent }, { WorkerEvents, OversubscriptionLimitReachedEvent } } private
Definition at line 253 of file Scheduler.h.
WorkerAffinity
uint64 LowLevelTasks::FScheduler::WorkerAffinity = 0 private
Definition at line 265 of file Scheduler.h.
WorkerCreationCS
UE::FPlatformRecursiveMutex LowLevelTasks::FScheduler::WorkerCreationCS private
Definition at line 255 of file Scheduler.h.
WorkerEvents
TAlignedArray<Private::FWaitEvent> LowLevelTasks::FScheduler::WorkerEvents private
Definition at line 259 of file Scheduler.h.
WorkerLocalQueues
TAlignedArray<FSchedulerTls::FLocalQueueType> LowLevelTasks::FScheduler::WorkerLocalQueues private
Definition at line 258 of file Scheduler.h.
WorkerPriority
EThreadPriority LowLevelTasks::FScheduler::WorkerPriority = EThreadPriority::TPri_Normal private
Definition at line 267 of file Scheduler.h.
Referenced by GetWorkerPriority(), and RestartWorkers().
WorkerSpinCycles
uint32 LowLevelTasks::FScheduler::WorkerSpinCycles = 53 static constexpr private
Definition at line 182 of file Scheduler.h.
WorkerThreads
TArray<std::atomic<FThread*> > LowLevelTasks::FScheduler::WorkerThreads private
Definition at line 257 of file Scheduler.h.
WorkerThreadsCS
UE::FPlatformRecursiveMutex LowLevelTasks::FScheduler::WorkerThreadsCS private
Definition at line 256 of file Scheduler.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/Fundamental/Scheduler.h