Unreal Engine 5.6 C++ API: FLiveLinkLog Class Reference
FLiveLinkLog Class Reference abstract
This class represents a log of LiveLink output each of which can be a rich tokenized message.
#include "LiveLinkLog.h"
Public Member Functions
virtual ~FLiveLinkLog ()=default
Dtor.
virtual void GetLogCount (int32 &OutErrorCount, int32 &OutWarningCount, int32 &OutInfoCount) const =0
Get the total number of error, warning and info messages that occurred.
virtual TPair< int32, FTimespan > GetOccurrence (FName MessageID, FLiveLinkSubjectKey SubjectKey) const =0
Get the number of time the message with the MessageID and SubjectKey occurred.
virtual TPair< int32, FTimespan > GetSelectedOccurrence () const =0
Get the number of time the selected message occurred.
Static Public Member Functions
template<typename... ArgsType>
static void Error (UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write an error in to the LiveLink log.
template<typename... ArgsType>
static void ErrorOnce (FName MessageID, const FLiveLinkSubjectKey &SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write a error in to the LiveLink log.
static FLiveLinkLog * GetInstance ()
template<typename... ArgsType>
static void Info (UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write an info in to the LiveLink log.
template<typename... ArgsType>
static void InfoOnce (FName MessageID, const FLiveLinkSubjectKey &SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write a info in to the LiveLink log.
template<typename... ArgsType>
static TSharedPtr< FTokenizedMessage > TokenizedMessage (EMessageSeverity::Type Severity, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write an message in to the LiveLink log.
template<typename... ArgsType>
static TSharedPtr< FTokenizedMessage > TokenizedMessageOnce (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey &SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write a repeatable message in to the LiveLink log.
template<typename... ArgsType>
static void Warning (UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write an warning in to the LiveLink log.
template<typename... ArgsType>
static void WarningOnce (FName MessageID, const FLiveLinkSubjectKey &SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Write a warning in to the LiveLink log.
Protected Member Functions
virtual TSharedPtr< FTokenizedMessage > CreateTokenizedMessage (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey &SubjectKey, FString &&Message)=0
virtual void LogMessage (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey &SubjectKey, FString &&Message)=0
Static Protected Attributes
static LIVELINKINTERFACE_API TUniquePtr< FLiveLinkLog > Instance
The instance that will manage the logging.
Static Private Member Functions
template<typename... ArgsType>
static TSharedPtr< FTokenizedMessage > CreateTokenizedMessage_Internal (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey &SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
template<typename... ArgsType>
static void Log_Internal (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey &SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args)
Detailed Description
This class represents a log of LiveLink output each of which can be a rich tokenized message.
Definition at line 23 of file LiveLinkLog.h.
Constructor & Destructor Documentation
~FLiveLinkLog()
virtual FLiveLinkLog::~FLiveLinkLog () virtual default
Dtor.
Member Function Documentation
CreateTokenizedMessage()
virtual TSharedPtr< FTokenizedMessage > FLiveLinkLog::CreateTokenizedMessage (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey & SubjectKey, FString && Message) protected pure virtual
References FLiveLinkSubjectKey.
CreateTokenizedMessage_Internal()
template<typename... ArgsType> TSharedPtr< FTokenizedMessage > FLiveLinkLog::CreateTokenizedMessage_Internal (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey & SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static private
Definition at line 145 of file LiveLinkLog.h.
References FLiveLinkSubjectKey, Format, and Instance.
Referenced by TokenizedMessage(), and TokenizedMessageOnce().
Error()
template<typename... ArgsType> void FLiveLinkLog::Error (UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write an error in to the LiveLink log.
Definition at line 28 of file LiveLinkLog.h.
References EMessageSeverity::Error, FLiveLinkSubjectKey, Format, and Log_Internal().
ErrorOnce()
template<typename... ArgsType> void FLiveLinkLog::ErrorOnce (FName MessageID, const FLiveLinkSubjectKey & SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write a error in to the LiveLink log.
If the error occurred more than once for that SubjectKey, a counter will indicate the number of time it did occurred.
Definition at line 38 of file LiveLinkLog.h.
References EMessageSeverity::Error, FLiveLinkSubjectKey, Format, and Log_Internal().
GetInstance()
FLiveLinkLog * FLiveLinkLog::GetInstance () inline static
Definition at line 113 of file LiveLinkLog.h.
References Instance.
GetLogCount()
virtual void FLiveLinkLog::GetLogCount (int32 & OutErrorCount, int32 & OutWarningCount, int32 & OutInfoCount) const pure virtual
Get the total number of error, warning and info messages that occurred.
GetOccurrence()
virtual TPair< int32, FTimespan > FLiveLinkLog::GetOccurrence (FName MessageID, FLiveLinkSubjectKey SubjectKey) const pure virtual
Get the number of time the message with the MessageID and SubjectKey occurred.
References FLiveLinkSubjectKey.
GetSelectedOccurrence()
virtual TPair< int32, FTimespan > FLiveLinkLog::GetSelectedOccurrence () const pure virtual
Get the number of time the selected message occurred.
Info()
template<typename... ArgsType> void FLiveLinkLog::Info (UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write an info in to the LiveLink log.
Definition at line 68 of file LiveLinkLog.h.
References FLiveLinkSubjectKey, Format, EMessageSeverity::Info, and Log_Internal().
InfoOnce()
template<typename... ArgsType> void FLiveLinkLog::InfoOnce (FName MessageID, const FLiveLinkSubjectKey & SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write a info in to the LiveLink log.
If the info occurred more than once for that SubjectKey, a counter will indicate the number of time it did occurred.
Definition at line 78 of file LiveLinkLog.h.
References FLiveLinkSubjectKey, Format, EMessageSeverity::Info, and Log_Internal().
Log_Internal()
template<typename... ArgsType> void FLiveLinkLog::Log_Internal (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey & SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static private
Definition at line 130 of file LiveLinkLog.h.
References FLiveLinkSubjectKey, Format, and Instance.
Referenced by Error(), ErrorOnce(), Info(), InfoOnce(), Warning(), and WarningOnce().
LogMessage()
virtual void FLiveLinkLog::LogMessage (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey & SubjectKey, FString && Message) protected pure virtual
References FLiveLinkSubjectKey.
TokenizedMessage()
template<typename... ArgsType> TSharedPtr< FTokenizedMessage > FLiveLinkLog::TokenizedMessage (EMessageSeverity::Type Severity, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write an message in to the LiveLink log.
Will returns a valid TokenizedMessage if a new TokenizedMessage was created.
Definition at line 91 of file LiveLinkLog.h.
References CreateTokenizedMessage_Internal(), FLiveLinkSubjectKey, and Format.
TokenizedMessageOnce()
template<typename... ArgsType> TSharedPtr< FTokenizedMessage > FLiveLinkLog::TokenizedMessageOnce (EMessageSeverity::Type Severity, FName MessageID, const FLiveLinkSubjectKey & SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write a repeatable message in to the LiveLink log.
Will returns a valid TokenizedMessage if a new TokenizedMessage was created. If the info occurred more than once for that SubjectKey, a counter will indicate the number of time it did occurred.
Definition at line 104 of file LiveLinkLog.h.
References CreateTokenizedMessage_Internal(), FLiveLinkSubjectKey, and Format.
Warning()
template<typename... ArgsType> void FLiveLinkLog::Warning (UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write an warning in to the LiveLink log.
Definition at line 48 of file LiveLinkLog.h.
References FLiveLinkSubjectKey, Format, Log_Internal(), and EMessageSeverity::Warning.
WarningOnce()
template<typename... ArgsType> void FLiveLinkLog::WarningOnce (FName MessageID, const FLiveLinkSubjectKey & SubjectKey, UE::Core::TCheckedFormatString< FString::FmtCharType, ArgsType... > Format, ArgsType... Args) inline static
Write a warning in to the LiveLink log.
If the warning occurred more than once for that SubjectKey, a counter will indicate the number of time it did occurred.
Definition at line 58 of file LiveLinkLog.h.
References FLiveLinkSubjectKey, Format, Log_Internal(), and EMessageSeverity::Warning.
Field Documentation
Instance
LIVELINKINTERFACE_API TUniquePtr<FLiveLinkLog> FLiveLinkLog::Instance static protected
The instance that will manage the logging.
Definition at line 166 of file LiveLinkLog.h.
Referenced by CreateTokenizedMessage_Internal(), GetInstance(), and Log_Internal().
The documentation for this class was generated from the following file:
Runtime/LiveLinkInterface/Public/LiveLinkLog.h