Unreal Engine 5.6 C++ API: UE::Geometry::TIntrRay3Triangle3< Real, RayType > Class Template Reference
UE::Geometry::TIntrRay3Triangle3< Real, RayType > Class Template Reference
Compute intersection between 3D ray and 3D triangle.
#include "IntrRay3Triangle3.h"
Public Member Functions
TIntrRay3Triangle3 (const RayType &RayIn, const TTriangle3< Real > &TriangleIn)
bool Find ()
bool Test ()
Static Public Member Functions
static bool FindIntersection (const TRay< Real > &InRay, const TTriangle3< Real > &InTriangle, Real &OutRayParameter, FVector3d &OutTriangleBaryCoords, EIntersectionType &OutIntersectionType)
Find intersection point.
static bool FindIntersection (const TWatertightRay3< Real > &InRay, const TTriangle3< Real > &InTriangle, Real &OutRayParameter, FVector3d &OutTriangleBaryCoords, EIntersectionType &OutIntersectionType)
static bool TestIntersection (const TRay< Real > &InRay, const TTriangle3< Real > &InTriangle, EIntersectionType &OutIntersectionType)
static bool TestIntersection (const TWatertightRay3< Real > &InRay, const TTriangle3< Real > &InTriangle, EIntersectionType &OutIntersectionType)
Data Fields
EIntersectionType IntersectionType
RayType Ray
Real RayParameter
TTriangle3< Real > Triangle
FVector3d TriangleBaryCoords
Static Private Member Functions
template<bool bNeedResult>
static bool FindWatertightIntersectionInternal (const TWatertightRay3< Real > &InRay, const TTriangle3< Real > &InTriangle, Real &OutRayParameter, FVector3d &OutTriangleBaryCoords, EIntersectionType &OutIntersectionType)
Detailed Description
template<typename Real, typename RayType = TRay<Real>>
class UE::Geometry::TIntrRay3Triangle3< Real, RayType >
Compute intersection between 3D ray and 3D triangle.
Definition at line 66 of file IntrRay3Triangle3.h.
Constructor & Destructor Documentation
TIntrRay3Triangle3()
template<typename Real, typename RayType = TRay<Real>> UE::Geometry::TIntrRay3Triangle3< Real, RayType >::TIntrRay3Triangle3 (const RayType & RayIn, const TTriangle3< Real > & TriangleIn) inline
Definition at line 79 of file IntrRay3Triangle3.h.
Member Function Documentation
Find()
template<typename Real, typename RayType = TRay<Real>> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Find () inline
Definition at line 244 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangle(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangle_LinearSearch(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangles_LinearSearch(), UE::Geometry::TMeshQueries< TriangleMeshType >::RayTriangleIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), and UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleIntersection().
FindIntersection() [1/2]
template<typename Real, typename RayType = TRay<Real>> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::FindIntersection (const TRay< Real > & InRay, const TTriangle3< Real > & InTriangle, Real & OutRayParameter, FVector3d & OutTriangleBaryCoords, EIntersectionType & OutIntersectionType) inline static
Find intersection point.
Returns
true if ray intersects triangle
Definition at line 167 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::TIntrRay3Triangle3< float >::Find().
FindIntersection() [2/2]
template<typename Real, typename RayType = TRay<Real>> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::FindIntersection (const TWatertightRay3< Real > & InRay, const TTriangle3< Real > & InTriangle, Real & OutRayParameter, FVector3d & OutTriangleBaryCoords, EIntersectionType & OutIntersectionType) inline static
Definition at line 238 of file IntrRay3Triangle3.h.
FindWatertightIntersectionInternal()
template<typename Real, typename RayType = TRay<Real>> template<bool bNeedResult> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::FindWatertightIntersectionInternal (const TWatertightRay3< Real > & InRay, const TTriangle3< Real > & InTriangle, Real & OutRayParameter, FVector3d & OutTriangleBaryCoords, EIntersectionType & OutIntersectionType) inline static private
Definition at line 253 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::TIntrRay3Triangle3< float >::FindIntersection(), and UE::Geometry::TIntrRay3Triangle3< float >::TestIntersection().
Test()
template<typename Real, typename RayType = TRay<Real>> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Test () inline
Returns
true if ray intersects triangle
Definition at line 157 of file IntrRay3Triangle3.h.
TestIntersection() [1/2]
template<typename Real, typename RayType = TRay<Real>> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::TestIntersection (const TRay< Real > & InRay, const TTriangle3< Real > & InTriangle, EIntersectionType & OutIntersectionType) inline static
Definition at line 93 of file IntrRay3Triangle3.h.
TestIntersection() [2/2]
template<typename Real, typename RayType = TRay<Real>> bool UE::Geometry::TIntrRay3Triangle3< Real, RayType >::TestIntersection (const TWatertightRay3< Real > & InRay, const TTriangle3< Real > & InTriangle, EIntersectionType & OutIntersectionType) inline static
Definition at line 86 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::TIntrRay3Triangle3< float >::Test().
Field Documentation
IntersectionType
template<typename Real, typename RayType = TRay<Real>> EIntersectionType UE::Geometry::TIntrRay3Triangle3< Real, RayType >::IntersectionType
Definition at line 76 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject(), and UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject().
Ray
template<typename Real, typename RayType = TRay<Real>> RayType UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Ray
Definition at line 70 of file IntrRay3Triangle3.h.
RayParameter
template<typename Real, typename RayType = TRay<Real>> Real UE::Geometry::TIntrRay3Triangle3< Real, RayType >::RayParameter
Definition at line 74 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangle(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangle_LinearSearch(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangles_LinearSearch(), UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject(), UE::Geometry::FDynamicMeshOctree3::FindNearestHitObject(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle().
Triangle
template<typename Real, typename RayType = TRay<Real>> TTriangle3<Real> UE::Geometry::TIntrRay3Triangle3< Real, RayType >::Triangle
Definition at line 71 of file IntrRay3Triangle3.h.
TriangleBaryCoords
template<typename Real, typename RayType = TRay<Real>> FVector3d UE::Geometry::TIntrRay3Triangle3< Real, RayType >::TriangleBaryCoords
Definition at line 75 of file IntrRay3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangle(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Intersection/IntrRay3Triangle3.h