Unreal Engine 5.6 C++ API: FWeakSharedBuffer Class Reference
FWeakSharedBuffer Class Reference
A weak reference to a shared-ownership immutable buffer.
#include "SharedBuffer.h"
Public Member Functions
FWeakSharedBuffer ()=default
Construct a null weak shared buffer.
FWeakSharedBuffer (const FSharedBuffer &Buffer)
Construct a weak shared buffer from a shared buffer.
bool operator!= (const FWeakSharedBuffer &BufferB) const
FWeakSharedBuffer & operator= (const FSharedBuffer &Buffer)
Assign a weak shared buffer from a shared buffer.
bool operator== (const FWeakSharedBuffer &BufferB) const
FSharedBuffer Pin () const
Convert this to a shared buffer if it has any remaining shared references.
void Reset ()
Reset this to null.
Private Types
using FWeakOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FWeakOps>
Private Attributes
FWeakOwnerPtrType Owner
Friends
uint32 GetTypeHash (const FWeakSharedBuffer &Buffer)
bool operator!= (const FSharedBuffer &BufferA, const FWeakSharedBuffer &BufferB)
bool operator!= (const FUniqueBuffer &BufferA, const FWeakSharedBuffer &BufferB)
bool operator!= (const FWeakSharedBuffer &BufferA, const FSharedBuffer &BufferB)
bool operator!= (const FWeakSharedBuffer &BufferA, const FUniqueBuffer &BufferB)
bool operator== (const FSharedBuffer &BufferA, const FWeakSharedBuffer &BufferB)
bool operator== (const FUniqueBuffer &BufferA, const FWeakSharedBuffer &BufferB)
bool operator== (const FWeakSharedBuffer &BufferA, const FSharedBuffer &BufferB)
bool operator== (const FWeakSharedBuffer &BufferA, const FUniqueBuffer &BufferB)
const FWeakOwnerPtrType & ToPrivateOwnerPtr (const FWeakSharedBuffer &Buffer)
Detailed Description
A weak reference to a shared-ownership immutable buffer.
See also
FSharedBuffer
Definition at line 464 of file SharedBuffer.h.
Member Typedef Documentation
FWeakOwnerPtrType
using FWeakSharedBuffer::FWeakOwnerPtrType = UE::SharedBuffer::Private::TBufferOwnerPtr<UE::SharedBuffer::Private::FWeakOps> private
Definition at line 483 of file SharedBuffer.h.
Constructor & Destructor Documentation
FWeakSharedBuffer() [1/2]
FWeakSharedBuffer::FWeakSharedBuffer () default
Construct a null weak shared buffer.
Referenced by GetTypeHash, operator!=, operator!=, operator!=, operator!=, operator!=(), operator=(), operator==, operator==, operator==, operator==, operator==(), and ToPrivateOwnerPtr.
FWeakSharedBuffer() [2/2]
FWeakSharedBuffer::FWeakSharedBuffer (const FSharedBuffer & Buffer)
Construct a weak shared buffer from a shared buffer.
References Buffer.
Member Function Documentation
operator!=()
bool FWeakSharedBuffer::operator!= (const FWeakSharedBuffer & BufferB) const inline
Definition at line 499 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator=()
FWeakSharedBuffer & FWeakSharedBuffer::operator= (const FSharedBuffer & Buffer)
Assign a weak shared buffer from a shared buffer.
References FWeakSharedBuffer(), and Buffer.
operator==()
bool FWeakSharedBuffer::operator== (const FWeakSharedBuffer & BufferB) const inline
Definition at line 491 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
Pin()
FSharedBuffer FWeakSharedBuffer::Pin () const nodiscard
Convert this to a shared buffer if it has any remaining shared references.
Reset()
void FWeakSharedBuffer::Reset ()
Reset this to null.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FWeakSharedBuffer & Buffer) friend
Definition at line 490 of file SharedBuffer.h.
References FWeakSharedBuffer(), Buffer, PointerHash(), and ToPrivateOwnerPtr.
operator!= [1/4]
bool operator!= (const FSharedBuffer & BufferA, const FWeakSharedBuffer & BufferB) friend
Definition at line 503 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator!= [2/4]
bool operator!= (const FUniqueBuffer & BufferA, const FWeakSharedBuffer & BufferB) friend
Definition at line 501 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator!= [3/4]
bool operator!= (const FWeakSharedBuffer & BufferA, const FSharedBuffer & BufferB) friend
Definition at line 502 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator!= [4/4]
bool operator!= (const FWeakSharedBuffer & BufferA, const FUniqueBuffer & BufferB) friend
Definition at line 500 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator== [1/4]
bool operator== (const FSharedBuffer & BufferA, const FWeakSharedBuffer & BufferB) friend
Definition at line 497 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator== [2/4]
bool operator== (const FUniqueBuffer & BufferA, const FWeakSharedBuffer & BufferB) friend
Definition at line 496 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator== [3/4]
bool operator== (const FWeakSharedBuffer & BufferA, const FSharedBuffer & BufferB) friend
Definition at line 493 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
operator== [4/4]
bool operator== (const FWeakSharedBuffer & BufferA, const FUniqueBuffer & BufferB) friend
Definition at line 492 of file SharedBuffer.h.
References FWeakSharedBuffer(), and ToPrivateOwnerPtr.
ToPrivateOwnerPtr
const FWeakOwnerPtrType & ToPrivateOwnerPtr (const FWeakSharedBuffer & Buffer) friend
Definition at line 485 of file SharedBuffer.h.
References FWeakSharedBuffer(), and Buffer.
Referenced by GetTypeHash, operator!=, operator!=, operator!=, operator!=, operator!=(), operator==, operator==, operator==, operator==, and operator==().
Field Documentation
Owner
FWeakOwnerPtrType FWeakSharedBuffer::Owner private
Definition at line 487 of file SharedBuffer.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/SharedBuffer.h