Unreal Engine 5.6 C++ API: FKismetVariableDragDropAction Class Reference
FKismetVariableDragDropAction Class Reference
DragDropAction class for dropping a Variable onto a graph.
#include "BPVariableDragDropAction.h"
Data Structures
struct FNodeConstructionParams
Structure for required node construction parameters.
Public Member Functions
DRAG_DROP_OPERATOR_TYPE (FKismetVariableDragDropAction, FMyBlueprintItemDragDropAction) virtual void HoverTargetChanged() override
virtual FReply DroppedOnNode (const FVector2f &ScreenPosition, const FVector2f &GraphPosition) override
virtual FReply DroppedOnPanel (const TSharedRef< class SWidget > &Panel, const FVector2f &ScreenPosition, const FVector2f &GraphPosition, UEdGraph &Graph) override
virtual FReply DroppedOnPin (const FVector2f &ScreenPosition, const FVector2f &GraphPosition) override
FProperty * GetVariableProperty ()
Public Member Functions inherited from FMyBlueprintItemDragDropAction
DRAG_DROP_OPERATOR_TYPE (FMyBlueprintItemDragDropAction, FGraphSchemaActionDragDropAction) virtual FReply DroppedOnAction(TSharedRef< FEdGraphSchemaAction > Action) override
virtual FReply DroppedOnCategory (FText Category) override
virtual void HoverTargetChanged () override
void SetAltDrag (bool InIsAltDrag)
Set if operation is modified by alt.
void SetCtrlDrag (bool InIsCtrlDrag)
Set if operation is modified by the ctrl key.
Public Member Functions inherited from FGraphSchemaActionDragDropAction
DRAG_DROP_OPERATOR_TYPE (FGraphSchemaActionDragDropAction, FGraphEditorDragDropAction) virtual void HoverTargetChanged() override
Public Member Functions inherited from FGraphEditorDragDropAction
DRAG_DROP_OPERATOR_TYPE (FGraphEditorDragDropAction, FDragDropOperation) FGraphEditorDragDropAction()
virtual FReply DroppedOnAction (TSharedRef< struct FEdGraphSchemaAction > Action)
bool HasFeedbackMessage ()
virtual bool IsSupportedBySchema (const UEdGraphSchema *Schema) const
void SetDropTargetValid (bool bValid)
void SetFeedbackMessage (const TSharedPtr< SWidget > &Message)
void SetHoveredAction (TSharedPtr< struct FEdGraphSchemaAction > Action)
void SetHoveredCategoryName (const FText &InHoverCategoryName)
void SetHoveredGraph (const TSharedPtr< SGraphPanel > &InGraph)
void SetHoveredNode (const TSharedPtr< SGraphNode > &InNode)
void SetHoveredNode (UEdGraphNode *InNode)
void SetHoveredPin (UEdGraphPin *InPin)
void SetSimpleFeedbackMessage (const FSlateBrush *Icon, const FSlateColor &IconColor, const FText &Message, const FSlateBrush *SecondaryIcon=nullptr, const FSlateColor SecondaryColor=FSlateColor())
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnNode(FVector2D ScreenPosition
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnPanel(const TSharedRef< SWidget > &Panel
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnPin(FVector2D ScreenPosition
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const
Gets the widget that will serve as the decorator unless overridden.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FKismetVariableDragDropAction > New (TSharedPtr< FEdGraphSchemaAction > InAction, FName InVariableName, UStruct *InVariableSource, FNodeCreationAnalytic AnalyticCallback)
Static Public Member Functions inherited from FGraphSchemaActionDragDropAction
static TSharedRef< FGraphSchemaActionDragDropAction > New (TSharedPtr< FEdGraphSchemaAction > InActionNode)
Protected Member Functions
FKismetVariableDragDropAction ()
Construct a FKismetVariableDragDropAction.
bool CanVariableBeDropped (const FProperty *InVariableProperty, const UEdGraph &InGraph) const
Checks if the property can be dropped in a graph.
virtual void GetDefaultStatusSymbol (const FSlateBrush *&PrimaryBrushOut, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut) const override
void GetLinksThatWillBreak (UEdGraphNode *Node, FProperty *NewVariableProperty, TArray< class UEdGraphPin * > &OutBroken)
Test new variable type against existing links for node and get any links that will break.
UStruct * GetLocalVariableScope () const
Returns the local variable's scope, if any.
virtual UBlueprint * GetSourceBlueprint () const override
bool WillBreakLinks (UEdGraphNode *Node, FProperty *NewVariableProperty)
Indicates if replacing the variable node, with the new property will require any links to be broken.
Protected Member Functions inherited from FMyBlueprintItemDragDropAction
FMyBlueprintItemDragDropAction ()
Constructor.
bool IsFromBlueprint (UBlueprint *InBlueprint) const
Helper method to see if we're dragging in the same blueprint.
void SetFeedbackMessageError (const FText &Message)
void SetFeedbackMessageOK (const FText &Message)
Protected Member Functions inherited from FGraphEditorDragDropAction
virtual void Construct () override
Constructs the window and widget if applicable.
virtual EVisibility GetErrorIconVisible () const
UEdGraph * GetHoveredGraph () const
UEdGraphNode * GetHoveredNode () const
UEdGraphPin * GetHoveredPin () const
virtual EVisibility GetIconVisible () const
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static bool CanExecuteMakeSetter (FNodeConstructionParams InParams, FProperty *InVariableProperty)
Called too check if we can execute a setter on a given property.
static void MakeGetter (FNodeConstructionParams InParams)
Called when user selects to create a Getter for the variable.
static void MakeSetter (FNodeConstructionParams InParams)
Called when user selects to create a Setter for the variable.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
FName VariableName
Name of variable being dragged.
TWeakObjectPtr< UStruct > VariableSource
Scope this variable belongs to.
Protected Attributes inherited from FMyBlueprintItemDragDropAction
FNodeCreationAnalytic AnalyticCallback
Analytic delegate to track node creation.
bool bAltDrag
Was alt held down at the start of drag.
bool bControlDrag
Was ctrl held down at start of drag.
Protected Attributes inherited from FGraphSchemaActionDragDropAction
TSharedPtr< FEdGraphSchemaAction > SourceAction
Protected Attributes inherited from FGraphEditorDragDropAction
bool bDropTargetValid
TWeakPtr< struct FEdGraphSchemaAction > HoveredAction
FText HoveredCategoryName
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Additional Inherited Members
Data Fields inherited from FGraphEditorDragDropAction
FVector2D FVector2D GraphPosition
FVector2D ScreenPosition
FVector2D GraphPosition UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
FVector2D FVector2D UEdGraph &Graph UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Detailed Description
DragDropAction class for dropping a Variable onto a graph.
Definition at line 31 of file BPVariableDragDropAction.h.
Constructor & Destructor Documentation
FKismetVariableDragDropAction()
FKismetVariableDragDropAction::FKismetVariableDragDropAction () protected
Construct a FKismetVariableDragDropAction.
Referenced by DRAG_DROP_OPERATOR_TYPE(), and New().
Member Function Documentation
CanExecuteMakeSetter()
bool FKismetVariableDragDropAction::CanExecuteMakeSetter (FNodeConstructionParams InParams, FProperty * InVariableProperty) static protected
Called too check if we can execute a setter on a given property.
CanVariableBeDropped()
bool FKismetVariableDragDropAction::CanVariableBeDropped (const FProperty * InVariableProperty, const UEdGraph & InGraph) const protected
Checks if the property can be dropped in a graph.
Parameters
InVariableProperty The variable property to check with
InGraph The graph to check against placing the variable
DRAG_DROP_OPERATOR_TYPE()
FKismetVariableDragDropAction::DRAG_DROP_OPERATOR_TYPE (FKismetVariableDragDropAction , FMyBlueprintItemDragDropAction) override
References FKismetVariableDragDropAction(), and FMyBlueprintItemDragDropAction::FMyBlueprintItemDragDropAction().
DroppedOnNode()
virtual FReply FKismetVariableDragDropAction::DroppedOnNode (const FVector2f & ScreenPosition, const FVector2f & GraphPosition) override virtual
Reimplemented from FGraphEditorDragDropAction.
References FGraphEditorDragDropAction::GraphPosition, and FGraphEditorDragDropAction::ScreenPosition.
DroppedOnPanel()
virtual FReply FKismetVariableDragDropAction::DroppedOnPanel (const TSharedRef< class SWidget > & Panel, const FVector2f & ScreenPosition, const FVector2f & GraphPosition, UEdGraph & Graph) override virtual
Reimplemented from FGraphSchemaActionDragDropAction.
References FGraphEditorDragDropAction::GraphPosition, and FGraphEditorDragDropAction::ScreenPosition.
DroppedOnPin()
virtual FReply FKismetVariableDragDropAction::DroppedOnPin (const FVector2f & ScreenPosition, const FVector2f & GraphPosition) override virtual
Reimplemented from FGraphSchemaActionDragDropAction.
References FGraphEditorDragDropAction::GraphPosition, and FGraphEditorDragDropAction::ScreenPosition.
GetDefaultStatusSymbol()
virtual void FKismetVariableDragDropAction::GetDefaultStatusSymbol (const FSlateBrush *& PrimaryBrushOut, FSlateColor & IconColorOut, FSlateBrush const *& SecondaryBrushOut, FSlateColor & SecondaryColorOut) const override protected virtual
Reimplemented from FGraphSchemaActionDragDropAction.
GetLinksThatWillBreak()
void FKismetVariableDragDropAction::GetLinksThatWillBreak (UEdGraphNode * Node, FProperty * NewVariableProperty, TArray< class UEdGraphPin * > & OutBroken) protected
Test new variable type against existing links for node and get any links that will break.
Parameters
Node The node with existing links
NewVariableProperty the property for the new variable type
OutBroken All of the links which are NOT compatible with the new type
Referenced by WillBreakLinks().
GetLocalVariableScope()
UStruct * FKismetVariableDragDropAction::GetLocalVariableScope () const protected
Returns the local variable's scope, if any.
GetSourceBlueprint()
virtual UBlueprint * FKismetVariableDragDropAction::GetSourceBlueprint () const override protected virtual
Reimplemented from FMyBlueprintItemDragDropAction.
GetVariableProperty()
FProperty * FKismetVariableDragDropAction::GetVariableProperty () inline
Definition at line 54 of file BPVariableDragDropAction.h.
References FindFProperty(), VariableName, and VariableSource.
MakeGetter()
void FKismetVariableDragDropAction::MakeGetter (FNodeConstructionParams InParams) static protected
Called when user selects to create a Getter for the variable.
MakeSetter()
void FKismetVariableDragDropAction::MakeSetter (FNodeConstructionParams InParams) static protected
Called when user selects to create a Setter for the variable.
New()
TSharedRef< FKismetVariableDragDropAction > FKismetVariableDragDropAction::New (TSharedPtr< FEdGraphSchemaAction > InAction, FName InVariableName, UStruct * InVariableSource, FNodeCreationAnalytic AnalyticCallback) inline static
Definition at line 43 of file BPVariableDragDropAction.h.
References FKismetVariableDragDropAction(), FMyBlueprintItemDragDropAction::AnalyticCallback, and MakeShareable().
WillBreakLinks()
bool FKismetVariableDragDropAction::WillBreakLinks (UEdGraphNode * Node, FProperty * NewVariableProperty) inline protected
Indicates if replacing the variable node, with the new property will require any links to be broken.
Definition at line 101 of file BPVariableDragDropAction.h.
References GetLinksThatWillBreak(), and TArray< InElementType, InAllocatorType >::Num().
Field Documentation
VariableName
FName FKismetVariableDragDropAction::VariableName protected
Name of variable being dragged.
Definition at line 122 of file BPVariableDragDropAction.h.
Referenced by GetVariableProperty().
VariableSource
TWeakObjectPtr<UStruct> FKismetVariableDragDropAction::VariableSource protected
Scope this variable belongs to.
Definition at line 124 of file BPVariableDragDropAction.h.
Referenced by GetVariableProperty().
The documentation for this class was generated from the following file:
Editor/Kismet/Public/BPVariableDragDropAction.h