Unreal Engine 5.6 C++ API: UParticleSystemComponent Class Reference
UParticleSystemComponent Class Reference
#include "ParticleSystemComponent.h"
Public Types
enum EForceAsyncWorkCompletion { STALL , ENSURE_AND_STALL , SILENT }
typedef TArray< struct FParticleAnimTrailEmitterInstance *, TInlineAllocator< 8 > > TrailEmitterArray
Array of trail emitters.
Public Member Functions
virtual void Activate (bool bReset=false) override
virtual void ActivateSystem (bool bFlagAsJustAttached=false) override
Activate the system.
virtual UObject const * AdditionalStatObject () const override
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift) override
void AutoPopulateInstanceProperties ()
Auto-populate the instance parameters based on contained modules.
virtual void BeginDestroy () override
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
bool CanBeOccluded () const
true if this component can be occluded.
bool CanConsiderInvisible () const
True if this component can be considered invisible and potentially culled.
bool CanSkipTickDueToVisibility ()
FORCEINLINE bool CanTickInAnyThread ()
return true if this psys can tick in any thread
virtual void CheckForErrors () override
void ClearParameter (FName ParameterName, enum EParticleSysParamType ParameterType=EParticleSysParamType(0))
clears the specified parameter, returning it to the default value set in the template
void Complete ()
void ComputeCanTickInAnyThread ()
Decide if this psys can tick in any thread, and set bIsElligibleForAsyncTick.
void ComputeTickComponent_Concurrent ()
Possibly parallel phase of TickComponent.
void ConditionalCacheViewRelevanceFlags (class UParticleSystem *NewTemplate=NULL)
Cache the view-relevance for each emitter at each LOD level if needed.
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
void DeactivaateNextTick ()
virtual void Deactivate () override
virtual void DeactivateImmediate () override
void DeactivateSystem ()
Deactivate the system.
virtual int32 DetermineLODLevelForLocation (const FVector &EffectLocation)
This will determine which LOD to use based off the specific ParticleSystem passed in and the distance to where that PS is being displayed.
virtual bool Editor_CanBeTickManaged () const
void FinalizeTickComponent ()
After the possibly parallel phase of TickComponent, we fire events, etc.
UParticleSystemReplay * FindReplayClipForIDNumber (const int32 InClipIDNumber)
Finds the replay clip of the specified ID number.
virtual void FinishDestroy () override
FORCEINLINE void ForceAsyncWorkCompletion (EForceAsyncWorkCompletion Behavior, bool bDefinitelyGameThread, bool InSkipUpdateDynamicDataDuringTick)
If there is async work outstanding, force it to be completed now.
FORCEINLINE void ForceAsyncWorkCompletion (EForceAsyncWorkCompletion Behavior, bool bDefinitelyGameThread=true) const
If there is async work outstanding, force it to be completed now.
void ForceReset ()
void ForceUpdateBounds ()
Force the component to update its bounding box.
virtual bool GetActorParameter (const FName InName, class AActor *&OutActor)
Retrieve the Actor parameter value for the given name.
virtual bool GetAnyVectorParameter (const FName InName, FVector &OutVector)
Retrieve the Vector parameter value for the given name...also looks for colors and floats and returns those.
float GetApproxDistanceSquared (FVector Point) const
Returns the approximate distance squared from this component to the passed location.
uint32 GetApproxMemoryUsage () const override
Returns an approximate memory usage value for this component.
FORCEINLINE const FBoxSphereBounds & GetAsyncBounds ()
FORCEINLINE const FTransform & GetAsyncComponentToWorld ()
FORCEINLINE const TArray< struct FParticleSysParam > & GetAsyncInstanceParameters ()
FORCEINLINE const FVector & GetAsyncPartSysVelocity ()
virtual FBodyInstance * GetBodyInstance (FName BoneName=NAME_None, bool bGetWelded=true, int32 Index=INDEX_NONE) const override
virtual bool GetColorParameter (const FName InName, FLinearColor &OutColor)
Retrieve the Color parameter value for the given name.
int32 GetCurrentDetailMode () const
Decide which detail mode should be applied to this particle system.
FORCEINLINE int32 GetCurrentLODIndex () const
virtual FString GetDetailedInfoInternal () const override
virtual bool GetFloatParameter (const FName InName, float &OutFloat)
Retrieve the Float parameter value for the given name.
virtual UFXSystemAsset * GetFXSystemAsset () const
Get the referenced FXSystem asset.
virtual int32 GetLODLevel ()
Get the LOD level of the particle system.
FORCEINLINE const FVector3f & GetLWCTile () const
FORCEINLINE int32 GetManagerHandle () const
FPSCTickData & GetManagerTickData ()
virtual UMaterialInterface * GetMaterial (int32 ElementIndex) const override
virtual UMaterialInterface * GetMaterialByName (FName MaterialSlotName) const override
virtual bool GetMaterialParameter (const FName InName, class UMaterialInterface *&OutMaterial)
Retrieve the Material parameter value for the given name.
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual int32 GetNamedMaterialIndex (FName InName) const
Returns the index into the EmitterMaterials array for this named.
virtual FName GetNameForMaterial (UMaterialInterface *InMaterial) const
returns the name associated with the passed in material, returns NAME_None if it is not found
virtual int32 GetNumMaterials () const override
virtual void GetOwnedTrailEmitters (TrailEmitterArray &OutTrailEmitters, const void *InOwner, bool bSetOwner=false)
Fills the passed array with all trail emitters associated with a particular object.
FORCEINLINE FParticlePerfStatsContext GetPerfStatsContext ()
FORCEINLINE const TArray< FVector > & GetPlayerLocations ()
FORCEINLINE const TArray< float > & GetPlayerLODDistanceFactor ()
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
virtual void GetStreamingRenderAssetInfo (FStreamingTextureLevelContext &LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamingRenderAssets) const override
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
virtual bool GetVectorParameter (const FName InName, FVector &OutVector)
Retrieve the Vector parameter value for the given name.
FParticleSystemWorldManager * GetWorldManager () const
bool HasCompleted ()
void InitializeSystem ()
virtual void InitParticles ()
virtual bool IsComponentTickEnabled () const override
FORCEINLINE int32 IsPendingManagerAdd () const
FORCEINLINE int32 IsPendingManagerRemove () const
virtual bool IsReadyForOwnerToAutoDestroy () const override
FORCEINLINE bool IsTickManaged () const
void KillParticlesForced ()
void MarshalParamsForAsyncTick ()
virtual void OnAttachmentChanged () override
virtual void OnChildAttached (USceneComponent *ChildComponent) override
virtual void OnChildDetached (USceneComponent *ChildComponent) override
virtual void OnEndOfFrameUpdateDuringTick () override
void OnSignificanceChanged (bool bSignificant, bool bApplyToEmitters, bool bAsync=false)
When the overall significance for the component is changed.
virtual bool ParticleLineCheck (FHitResult &Hit, AActor *SourceActor, const FVector &End, const FVector &Start, const FVector &HalfExtent, const FCollisionObjectQueryParams &ObjectParams)
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostLoad () override
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
void ReleaseToPool () override
void ReportEventBurst (const FName InEventName, const float InEmitterTime, const int32 ParticleCount, const FVector InLocation, const TArray< class UParticleModuleEventSendToGame * > &InEventData)
Record a bursting event.
void ReportEventCollision (const FName InEventName, const float InEmitterTime, const FVector InLocation, const FVector InDirection, const FVector InVelocity, const TArray< class UParticleModuleEventSendToGame * > &InEventData, const float InParticleTime, const FVector InNormal, const float InTime, const int32 InItem, const FName InBoneName, UPhysicalMaterial *PhysMat)
Record a collision event.
void ReportEventDeath (const FName InEventName, const float InEmitterTime, const FVector InLocation, const FVector InVelocity, const TArray< class UParticleModuleEventSendToGame * > &InEventData, const float InParticleTime)
Record a death event.
void ReportEventSpawn (const FName InEventName, const float InEmitterTime, const FVector InLocation, const FVector InVelocity, const TArray< class UParticleModuleEventSendToGame * > &InEventData)
Event reporting...
void ResetBurstLists ()
void ResetNextTick ()
void ResetParticles (bool bEmptyInstances=false)
void ResetToDefaults ()
stops the emitter, unregisters the component, and resets the component's properties to the values of its template
virtual void RewindEmitterInstances ()
virtual void Serialize (FArchive &Ar) override
void SetActorParameter (FName ParameterName, class AActor *Param) override
Set a named actor instance parameter on this ParticleSystemComponent.
void SetAutoAttachmentParameters (USceneComponent *Parent, FName SocketName, EAttachmentRule LocationRule, EAttachmentRule RotationRule, EAttachmentRule ScaleRule) override
Set AutoAttachParent, AutoAttachSocketName, AutoAttachLocationRule, AutoAttachRotationRule, AutoAttachScaleRule to the specified parameters.
void SetBoolParameter (FName ParameterName, bool Param) override
Set a named float instance parameter on this ParticleSystemComponent.
void SetColorParameter (FName ParameterName, FLinearColor Param) override
Set a named color instance parameter on this ParticleSystemComponent.
virtual void SetComponentTickEnabled (bool bEnabled) override
void SetEmitterEnable (FName EmitterName, bool bNewEnableState) override
Enables/Disables a sub-emitter.
void SetFloatParameter (FName ParameterName, float Param) override
Change a named float parameter.
void SetFloatRandParameter (FName ParameterName, float Param, float ParamLow)
Set a named random float instance parameter on this ParticleSystemComponent.
void SetIntParameter (FName ParameterName, int Param) override
Set a named float instance parameter on this ParticleSystemComponent.
virtual void SetLODLevel (int32 InLODLevel)
Set the LOD level of the particle system.
FORCEINLINE void SetManagerHandle (int32 InHandle)
FORCEINLINE void SetManagingSignificance (bool bManageSignificance)
Called from game code when the component begins having it's significance managed.
virtual void SetMaterial (int32 ElementIndex, UMaterialInterface *Material) override
virtual void SetMaterialByName (FName MaterialSlotName, class UMaterialInterface *SourceMaterial) override
FORCEINLINE void SetPendingManagerAdd (bool bValue)
FORCEINLINE void SetPendingManagerRemove (bool bValue)
void SetRequiredSignificance (EParticleSignificanceLevel NewRequiredSignificance)
Called from game code when the significance required for a component changes.
virtual void SetUseAutoManageAttachment (bool bAutoManage) override
void SetVectorParameter (FName ParameterName, FVector Param) override
Set a named vector instance parameter on this ParticleSystemComponent.
void SetVectorRandParameter (FName ParameterName, const FVector &Param, const FVector &ParamLow)
Set a named random vector instance parameter on this ParticleSystemComponent.
void SetVectorUnitRandParameter (FName ParameterName, const FVector &Param, const FVector &ParamLow)
Set a named random unit vector instance parameter on this ParticleSystemComponent.
bool ShouldBeTickManaged () const
bool ShouldManageSignificance () const
Whether this component should have it's significance managed by game code.
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
UFUNCTION () 1 int32 GetNumActiveParticles() const
Get the current number of active particles in this system.
UFUNCTION () 1 virtual bool GetBeamEndPoint(int32 EmitterIndex
Get the beam end point.
UFUNCTION () 1 virtual bool GetBeamSourcePoint(int32 EmitterIndex
Get the beam source point.
UFUNCTION () 1 virtual bool GetBeamSourceStrength(int32 EmitterIndex
Get the beam source strength.
UFUNCTION () 1 virtual bool GetBeamSourceTangent(int32 EmitterIndex
Get the beam source tangent.
UFUNCTION () 1 virtual bool GetBeamTargetPoint(int32 EmitterIndex
Get the beam target point.
UFUNCTION () 1 virtual bool GetBeamTargetStrength(int32 EmitterIndex
Get the beam target strength.
UFUNCTION () 1 virtual bool GetBeamTargetTangent(int32 EmitterIndex
Get the beam target tangent.
UFUNCTION () 1 virtual class UMaterialInstanceDynamic *CreateNamedDynamicMaterialInstance(FName InName
Creates a Dynamic Material Instance for the specified named material override, optionally from the supplied material.
UFUNCTION () 1 virtual class UMaterialInterface *GetNamedMaterial(FName InName) const
Returns a named material.
UFUNCTION () 1 virtual void SetBeamEndPoint(int32 EmitterIndex
Set the beam end point.
UFUNCTION () 1 virtual void SetBeamSourcePoint(int32 EmitterIndex
Set the beam source point.
UFUNCTION () 1 virtual void SetBeamSourceStrength(int32 EmitterIndex
Set the beam source strength.
UFUNCTION () 1 virtual void SetBeamSourceTangent(int32 EmitterIndex
Set the beam source tangent.
UFUNCTION () 1 virtual void SetBeamTargetPoint(int32 EmitterIndex
Set the beam target point.
UFUNCTION () 1 virtual void SetBeamTargetStrength(int32 EmitterIndex
Set the beam target strength.
UFUNCTION () 1 virtual void SetBeamTargetTangent(int32 EmitterIndex
Set the beam target tangent.
UFUNCTION () 1 void BeginTrails(FName InFirstSocketName
Begins all trail emitters in this component.
UFUNCTION () 1 void EndTrails()
Ends all trail emitters in this component.
UFUNCTION () 1 void GenerateParticleEvent(const FName InEventName
Record a kismet event.
UFUNCTION () 1 void SetMaterialParameter(FName ParameterName
Set a named material instance parameter on this ParticleSystemComponent.
UFUNCTION () 1 void SetTemplate(class UParticleSystem *NewTemplate)
Change the ParticleSystem used by this ParticleSystemComponent.
UFUNCTION () 1 void SetTrailSourceData(FName InFirstSocketName
Sets the defining data for all trails in this component.
UFUNCTION ()) void SetAutoAttachParams(USceneComponent *Parent
DEPRECATED: Set AutoAttachParent, AutoAttachSocketName, AutoAttachLocationType to the specified parameters.
void UpdateInstances (bool bEmptyInstances=false)
UPROPERTY () bool bOldPositionValid
UPROPERTY () EParticleSignificanceLevel RequiredSignificance
The significance this component requires of it's emitters for them to be enabled.
UPROPERTY () float CustomTimeDilation
Scales DeltaTime in UParticleSystemComponent::Tick(...)
UPROPERTY () float MaxTimeBeforeForceUpdateTransform
Time between forced UpdateTransforms for systems that use dynamically calculated bounds, Which is effectively how often the bounds are shrunk.
UPROPERTY () float SecondsBeforeInactive
Number of seconds of emitter not being rendered that need to pass before it no longer gets ticked/ becomes inactive.
UPROPERTY () float WarmupTickRate
UPROPERTY () float WarmupTime
UPROPERTY () FOnSystemFinished OnSystemFinished
UPROPERTY () FParticleBurstSignature OnParticleBurst
UPROPERTY () FParticleCollisionSignature OnParticleCollide
UPROPERTY () FParticleDeathSignature OnParticleDeath
UPROPERTY () FParticleSpawnSignature OnParticleSpawn
UPROPERTY () FVector OldPosition
UPROPERTY () FVector PartSysVelocity
UPROPERTY () TArray< struct FParticleSysParam > InstanceParameters
Array holding name instance parameters for this ParticleSystemComponent.
UPROPERTY () TArray< TObjectPtr< class UParticleSystemReplay > > ReplayClips
Array of replay clips for this particle system component.
UPROPERTY () TEnumAsByte< enum ParticleSystemLODMethod > LODMethod
The method of LOD level determination to utilize for this particle system.
UPROPERTY ()) EAttachmentRule AutoAttachLocationRule
Options for how we handle our location when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
UPROPERTY ()) EAttachmentRule AutoAttachRotationRule
Options for how we handle our rotation when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
UPROPERTY ()) EAttachmentRule AutoAttachScaleRule
Options for how we handle our scale when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
UPROPERTY ()) FName AutoAttachSocketName
Socket we automatically attach to on the AutoAttachParent, if bAutoManageAttachment is true.
UPROPERTY ()) TWeakObjectPtr< USceneComponent > AutoAttachParent
Component we automatically attach to when activated, if bAutoManageAttachment is true.
Data Fields
float AccumLODDistanceCheckTime
LOD updating...
float AccumTickTime
Used to accumulate total tick time to determine whether system can be skipped ticking if not visible.
uint8 bAutoDestroy: 1
uint8 bDeactivateTriggered: 1
If true, someone has requested this component deactivate.
UPROPERTY() uint8 bWarmingUp UPROPERTY() uint8 bOverrideLODMethod UPROPERTY() uint8 bSkipUpdateDynamicDataDuringTick uint8 bForcedInActive:1
indicates that the component's LODMethod overrides the Template's
uint8 bForceLODUpdateFromRenderer:1
If true, force an LOD update from the renderer.
uint8 bHasBeenActivated:1
This flag will be set the first time the PSysComp is activated... used to prevent auto activated PSysComps from calling InitParticles twice on level load.
uint8 bIsDuringRegister: 1
UPROPERTY() uint8 bAllowRecycling UPROPERTY() uint8 bAutoManageAttachment UPROPERTY()) uint8 bAutoAttachWeldSimulatedBodies uint8 bIsManagingSignificance: 1
If true, this Particle System will be available for recycling after it has completed.
uint8 bIsViewRelevanceDirty: 1
If true, the ViewRelevanceFlags are dirty and should be recached.
UPROPERTY() uint8 bResetOnDetach UPROPERTY() uint8 bUpdateOnDedicatedServer uint8 bJustRegistered:1
whether to update the particle system on dedicated servers
uint8 bResetTriggered: 1
If true, someone has requested this component reset.
TArray< struct FParticleEventBurstData > BurstEvents
The Burst events that occurred in this PSysComp.
uint8 bWasActive:1
True if this was active before being unregistered or otherwise reset, if so reactivate it.
uint8 bWasDeactivated:1
uint8 bWasManagingSignificance: 1
If this component was previously having it's significance managed by gameplay code.
TArray< FMaterialRelevance > CachedViewRelevanceFlags
The view relevance flags for each LODLevel.
TArray< struct FParticleEventCollideData > CollisionEvents
The Collision events that occurred in this PSysComp.
FVector &OutEndPoint const
int32 FVector &OutSourcePoint const
int32 FVector &OutTangentPoint const
int32 float &OutSourceStrength const
int32 FVector &OutTargetPoint const
int32 float &OutTargetStrength const
TArray< struct FParticleEventDeathData > DeathEvents
The Death events that occurred in this PSysComp.
float EmitterDelay
This is created at start up and then added to each emitter.
TArray< struct FParticleEmitterInstance * > EmitterInstances
class FFXSystem * FXSystem
const float const FVector const FVector InDirection
const float InEmitterTime
const float const FVector InLocation
FName InSecondSocketName
TUniquePtr< FInstanceOwner > InstanceOwner
const float const FVector const FVector const FVector InVelocity
FName ETrailWidthMode float InWidth
FName ETrailWidthMode InWidthMode
TArray< struct FParticleEventKismetData > KismetEvents
The Kismet events that occurred for this PSysComp.
float LastSignificantTime
Time in seconds since we were last considered significant.
FName EAttachLocation::Type LocationType = EAttachLocation::KeepRelativeOffset)
FVector NewEndPoint
FVector NewSourcePoint
float NewSourceStrength
FVector NewTangentPoint
FVector NewTargetPoint
float NewTargetStrength
class UMaterialInterface * Param
EPSCPoolMethod PoolingMethod
If this PSC is pooling.
FRandomStream RandomStream
Stream of random values to use with this component.
class FRenderCommandFence * ReleaseResourcesFence
Command fence used to shut down properly.
int32 ReplayClipIDNumber
Clip ID number we're either playing back or capturing to, depending on the value of ReplayState.
int32 ReplayFrameIndex
The current replay frame for playback.
TEnumAsByte< enum ParticleReplayState > ReplayState
Current particle 'replay state'.
FName SocketName = NAME_None
FVector int32 SourceIndex
float int32 SourceIndex
int32 SourceIndex
class UMaterialInterface * SourceMaterial = NULL)
TArray< struct FParticleEventSpawnData > SpawnEvents
The Spawn events that occurred in this PSysComp.
FVector int32 TargetIndex
float int32 TargetIndex
int32 TargetIndex
Static Public Attributes
static FOnSystemPreActivationChange OnSystemPreActivationChange
Static delegate called for all systems on an activation change.
Protected Member Functions
void ClearDynamicData ()
Clears dynamic data on the rendering thread.
FParticleDynamicData * CreateDynamicData (ERHIFeatureLevel::Type InFeatureLevel)
Creates dynamic particle data for rendering the particle system this frame.
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
virtual void DestroyRenderState_Concurrent () override
virtual void OnRegister () override
virtual void OnUnregister () override
void OrientZAxisTowardCamera ()
Orients the Z axis of the ParticleSystemComponent toward the camera while preserving the X axis direction.
virtual void SendRenderDynamicData_Concurrent () override
virtual void SendRenderTransform_Concurrent () override
virtual bool ShouldActivate () const override
virtual void UpdateDynamicData ()
virtual void UpdateLODInformation ()
Static Protected Member Functions
static FDynamicEmitterDataBase * CreateDynamicDataFromReplay (FParticleEmitterInstance *EmitterInstance, const FDynamicEmitterReplayDataBase *EmitterReplayData, bool bSelected, ERHIFeatureLevel::Type InFeatureLevel)
Static: Supplied with a chunk of replay data, this method will create dynamic emitter data that can be used to render the particle system.
Private Member Functions
void CacheViewRelevanceFlags (class UParticleSystem *TemplateToCache)
Cache view relevance flags.
void CancelAutoAttachment (bool bDetachFromParent, const UWorld *MyWorld)
Restore relative transform from auto attachment and optionally detach from parent (regardless of whether it was an auto attachment).
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UParticleSystem > Template
FORCEINLINE void SetAsyncWork (FGraphEventRef &InAsyncWork)
In some cases the async work for this PSC can be created externally by the manager.
bool ShouldComputeLODFromGameThread ()
Returns true if this component can and should compute it's LOD without visibility information from the renderer.
UPROPERTY () TArray< TObjectPtr< class UMaterialInterface > > EmitterMaterials
UPROPERTY () TArray< TObjectPtr< class USkeletalMeshComponent > > SkelMeshComponents
The skeletal mesh components used with the socket location module.
void WaitForAsyncAndFinalize (EForceAsyncWorkCompletion Behavior, bool bDefinitelyGameThread=true) const
Wait on the async task and call finalize on the tick.
Private Attributes
FBoxSphereBounds AsyncBounds
Cached copy of bounds.
FTransform AsyncComponentToWorld
Cached copy of the transform for async work.
TArray< struct FParticleSysParam > AsyncInstanceParameters
Cached copy of the instance params.
FVector AsyncPartSysVelocity
Cached copy of PartSysVelocity.
FGraphEventRef AsyncWork
Task ref for parallel portion.
uint8 bAsyncDataCopyIsValid:1
Is AsyncComponentToWorld etc valid?
volatile bool bAsyncWorkOutstanding
If true, it means the Async work is in process and not yet completed.
uint8 bDidAutoAttach: 1
Did we auto attach during activation?
uint8 bIsElligibleForAsyncTick:1
if true, this psys can tick in any thread
uint8 bIsElligibleForAsyncTickComputed:1
if true, bIsElligibleForAsyncTick is set up
uint8 bIsTransformDirty:1
Indicates if the component's transform has been changed and requires updating.
uint8 bNeedsFinalize:1
If true, it means the ASync work is done and the finalize is not.
uint8 bParallelRenderThreadUpdate:1
int32 bPendingManagerAdd: 1
Flag denoting we are currently in the pending queue to be added to the manager.
int32 bPendingManagerRemove: 1
Flag denoting we have been unregistered and are awaiting removal from the managers arrays.
uint8 bSuppressSpawning:1
uint8 bWasCompleted:1
float DeltaTimeTick
Copy of delta time coming into TickComponent.
int32 LODLevel
FVector3f LWCTile = FVector3f::ZeroVector
LWC tile offset for gpu simulations.
int32 ManagerHandle: 30
Handle into the FParticleSystemWorldManager.
uint32 NumSignificantEmitters
Number of significant emitters.
TArray< FVector > PlayerLocations
Player locations computed before kicking off async task.
TArray< float > PlayerLODDistanceFactor
PlayerLODDistanceFactor computed before kicking off async task.
FVector SavedAutoAttachRelativeLocation
Saved relative transform before auto attachement.
FRotator SavedAutoAttachRelativeRotation
FVector SavedAutoAttachRelativeScale3D
float TimeSinceLastForceUpdateTransform
Tracks the time since the last forced UpdateTransform.
uint32 TimeSinceLastTick
Time in ms since a tick was last performed; used with MinTimeBetweenTicks (on UParticleSystem) to control tick rate.
int32 TotalActiveParticles
Info from async tick.
Friends
class FParticleSystemWorldManager
Detailed Description
Definition at line 487 of file ParticleSystemComponent.h.
Member Typedef Documentation
TrailEmitterArray
typedef TArray< struct FParticleAnimTrailEmitterInstance*, TInlineAllocator<8> > UParticleSystemComponent::TrailEmitterArray
Array of trail emitters.
Definition at line 1265 of file ParticleSystemComponent.h.
Member Enumeration Documentation
EForceAsyncWorkCompletion
enum UParticleSystemComponent::EForceAsyncWorkCompletion
Enumerator
STALL
ENSURE_AND_STALL
SILENT
Definition at line 1378 of file ParticleSystemComponent.h.
Member Function Documentation
Activate()
virtual void UParticleSystemComponent::Activate (bool bReset = false) override virtual
ActivateSystem()
virtual void UParticleSystemComponent::ActivateSystem (bool bFlagAsJustAttached = false) override virtual
Activate the system.
AdditionalStatObject()
virtual UObject const * UParticleSystemComponent::AdditionalStatObject () const inline override virtual
Definition at line 1352 of file ParticleSystemComponent.h.
ApplyWorldOffset()
virtual void UParticleSystemComponent::ApplyWorldOffset (const FVector & InOffset, bool bWorldShift) override virtual
References FVector.
AutoPopulateInstanceProperties()
void UParticleSystemComponent::AutoPopulateInstanceProperties ()
Auto-populate the instance parameters based on contained modules.
BeginDestroy()
virtual void UParticleSystemComponent::BeginDestroy () override virtual
CacheViewRelevanceFlags()
void UParticleSystemComponent::CacheViewRelevanceFlags (class UParticleSystem * TemplateToCache) private
Cache view relevance flags.
CalcBounds()
virtual FBoxSphereBounds UParticleSystemComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
CanBeOccluded()
bool UParticleSystemComponent::CanBeOccluded () const
true if this component can be occluded.
CancelAutoAttachment()
void UParticleSystemComponent::CancelAutoAttachment (bool bDetachFromParent, const UWorld * MyWorld) private
Restore relative transform from auto attachment and optionally detach from parent (regardless of whether it was an auto attachment).
References CancelAutoAttachment(), and const.
Referenced by CancelAutoAttachment().
CanConsiderInvisible()
bool UParticleSystemComponent::CanConsiderInvisible () const
True if this component can be considered invisible and potentially culled.
CanSkipTickDueToVisibility()
bool UParticleSystemComponent::CanSkipTickDueToVisibility ()
CanTickInAnyThread()
FORCEINLINE bool UParticleSystemComponent::CanTickInAnyThread () inline
return true if this psys can tick in any thread
Definition at line 1475 of file ParticleSystemComponent.h.
References bIsElligibleForAsyncTick, bIsElligibleForAsyncTickComputed, ComputeCanTickInAnyThread(), and FORCEINLINE.
CheckForErrors()
virtual void UParticleSystemComponent::CheckForErrors () override virtual
ClearDynamicData()
void UParticleSystemComponent::ClearDynamicData () protected
Clears dynamic data on the rendering thread.
References ClearDynamicData().
Referenced by ClearDynamicData().
ClearParameter()
void UParticleSystemComponent::ClearParameter (FName ParameterName, enum EParticleSysParamType ParameterType = EParticleSysParamType(0))
clears the specified parameter, returning it to the default value set in the template
Parameters
ParameterName name of parameter to remove
ParameterType type of parameter to remove; if omitted or PSPT_None is specified, all parameters with the given name are removed
References ClearParameter().
Referenced by ClearParameter().
Complete()
void UParticleSystemComponent::Complete ()
ComputeCanTickInAnyThread()
void UParticleSystemComponent::ComputeCanTickInAnyThread ()
Decide if this psys can tick in any thread, and set bIsElligibleForAsyncTick.
Referenced by CanTickInAnyThread().
ComputeTickComponent_Concurrent()
void UParticleSystemComponent::ComputeTickComponent_Concurrent ()
Possibly parallel phase of TickComponent.
ConditionalCacheViewRelevanceFlags()
void UParticleSystemComponent::ConditionalCacheViewRelevanceFlags (class UParticleSystem * NewTemplate = NULL)
Cache the view-relevance for each emitter at each LOD level if needed.
Parameters
NewTemplate The UParticleSystem* to use as the template. If NULL, use the currently set template.
CreateDynamicData()
FParticleDynamicData * UParticleSystemComponent::CreateDynamicData (ERHIFeatureLevel::Type InFeatureLevel) protected
Creates dynamic particle data for rendering the particle system this frame.
This function handle creation of dynamic data for regularly simulated particles, but also handles capture and playback of particle replay data.
Parameters
InFeatureLevel - The relevant shader feature level.
Returns
Returns the dynamic data to render this frame
References CreateDynamicData().
Referenced by CreateDynamicData().
CreateDynamicDataFromReplay()
FDynamicEmitterDataBase * UParticleSystemComponent::CreateDynamicDataFromReplay (FParticleEmitterInstance * EmitterInstance, const FDynamicEmitterReplayDataBase * EmitterReplayData, bool bSelected, ERHIFeatureLevel::Type InFeatureLevel) static protected
Static: Supplied with a chunk of replay data, this method will create dynamic emitter data that can be used to render the particle system.
Parameters
EmitterInstance Emitter instance this replay is playing on
EmitterReplayData Incoming replay data of any time, cannot be NULL
bSelected true if the particle system is currently selected
InFeatureLevel The relevant shader feature level
Returns
The newly created dynamic data, or NULL on failure
References const, and CreateDynamicDataFromReplay().
Referenced by CreateDynamicDataFromReplay().
CreateRenderState_Concurrent()
virtual void UParticleSystemComponent::CreateRenderState_Concurrent (FRegisterComponentContext * Context) override protected virtual
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UParticleSystemComponent::CreateSceneProxy () override virtual
DeactivaateNextTick()
void UParticleSystemComponent::DeactivaateNextTick () inline
Definition at line 665 of file ParticleSystemComponent.h.
References bDeactivateTriggered.
Deactivate()
virtual void UParticleSystemComponent::Deactivate () override virtual
DeactivateImmediate()
virtual void UParticleSystemComponent::DeactivateImmediate () override virtual
DeactivateSystem()
void UParticleSystemComponent::DeactivateSystem ()
Deactivate the system.
DestroyRenderState_Concurrent()
virtual void UParticleSystemComponent::DestroyRenderState_Concurrent () override protected virtual
DetermineLODLevelForLocation()
virtual int32 UParticleSystemComponent::DetermineLODLevelForLocation (const FVector & EffectLocation) virtual
This will determine which LOD to use based off the specific ParticleSystem passed in and the distance to where that PS is being displayed.
Note
: This is distance based LOD not perf based. Perf and distance are orthogonal concepts.
References const, DetermineLODLevelForLocation(), and FVector.
Referenced by DetermineLODLevelForLocation().
Editor_CanBeTickManaged()
virtual bool UParticleSystemComponent::Editor_CanBeTickManaged () const inline virtual
Definition at line 629 of file ParticleSystemComponent.h.
FinalizeTickComponent()
void UParticleSystemComponent::FinalizeTickComponent ()
After the possibly parallel phase of TickComponent, we fire events, etc.
FindReplayClipForIDNumber()
UParticleSystemReplay * UParticleSystemComponent::FindReplayClipForIDNumber (const int32 InClipIDNumber)
Finds the replay clip of the specified ID number.
Returns
Returns the replay clip or NULL if none
References const, and FindReplayClipForIDNumber().
Referenced by FindReplayClipForIDNumber().
FinishDestroy()
virtual void UParticleSystemComponent::FinishDestroy () override virtual
ForceAsyncWorkCompletion() [1/2]
FORCEINLINE void UParticleSystemComponent::ForceAsyncWorkCompletion (EForceAsyncWorkCompletion Behavior, bool bDefinitelyGameThread, bool InSkipUpdateDynamicDataDuringTick) inline
If there is async work outstanding, force it to be completed now.
Definition at line 1385 of file ParticleSystemComponent.h.
References AsyncWork, FORCEINLINE, and WaitForAsyncAndFinalize().
ForceAsyncWorkCompletion() [2/2]
FORCEINLINE void UParticleSystemComponent::ForceAsyncWorkCompletion (EForceAsyncWorkCompletion Behavior, bool bDefinitelyGameThread = true) const inline
If there is async work outstanding, force it to be completed now.
Definition at line 1397 of file ParticleSystemComponent.h.
References AsyncWork, FORCEINLINE, and WaitForAsyncAndFinalize().
ForceReset()
void UParticleSystemComponent::ForceReset ()
ForceUpdateBounds()
void UParticleSystemComponent::ForceUpdateBounds ()
Force the component to update its bounding box.
References ForceUpdateBounds().
Referenced by ForceUpdateBounds().
GENERATED_UCLASS_BODY()
UParticleSystemComponent::GENERATED_UCLASS_BODY () private
References Category, and UPROPERTY().
GetActorParameter()
virtual bool UParticleSystemComponent::GetActorParameter (const FName InName, class AActor *& OutActor) virtual
Retrieve the Actor parameter value for the given name.
Parameters
InName Name of the parameter
OutActor The value of the parameter found
Returns
true Parameter was found - OutActor is valid false Parameter was not found - OutActor is invalid
References const, GetActorParameter(), and InName.
Referenced by GetActorParameter().
GetAnyVectorParameter()
virtual bool UParticleSystemComponent::GetAnyVectorParameter (const FName InName, FVector & OutVector) virtual
Retrieve the Vector parameter value for the given name...also looks for colors and floats and returns those.
Parameters
InName Name of the parameter
OutVector The value of the parameter found
Returns
true Parameter was found - OutVector is valid false Parameter was not found - OutVector is invalid
References const, FVector, GetAnyVectorParameter(), and InName.
Referenced by GetAnyVectorParameter().
GetApproxDistanceSquared()
float UParticleSystemComponent::GetApproxDistanceSquared (FVector Point) const
Returns the approximate distance squared from this component to the passed location.
References FVector, and Point.
GetApproxMemoryUsage()
uint32 UParticleSystemComponent::GetApproxMemoryUsage () const override
Returns an approximate memory usage value for this component.
References const, and GetApproxMemoryUsage().
Referenced by GetApproxMemoryUsage().
GetAsyncBounds()
FORCEINLINE const FBoxSphereBounds & UParticleSystemComponent::GetAsyncBounds () inline
Definition at line 935 of file ParticleSystemComponent.h.
References AsyncBounds, bAsyncDataCopyIsValid, bParallelRenderThreadUpdate, check, FORCEINLINE, and IsInGameThread().
GetAsyncComponentToWorld()
FORCEINLINE const FTransform & UParticleSystemComponent::GetAsyncComponentToWorld () inline
Definition at line 915 of file ParticleSystemComponent.h.
References AsyncComponentToWorld, bAsyncDataCopyIsValid, bParallelRenderThreadUpdate, check, FORCEINLINE, and IsInGameThread().
GetAsyncInstanceParameters()
FORCEINLINE const TArray< struct FParticleSysParam > & UParticleSystemComponent::GetAsyncInstanceParameters () inline
Definition at line 925 of file ParticleSystemComponent.h.
References AsyncInstanceParameters, bAsyncDataCopyIsValid, bParallelRenderThreadUpdate, check, FORCEINLINE, and IsInGameThread().
GetAsyncPartSysVelocity()
FORCEINLINE const FVector & UParticleSystemComponent::GetAsyncPartSysVelocity () inline
Definition at line 945 of file ParticleSystemComponent.h.
References AsyncPartSysVelocity, bAsyncDataCopyIsValid, bParallelRenderThreadUpdate, check, FORCEINLINE, FVector, and IsInGameThread().
GetBodyInstance()
virtual FBodyInstance * UParticleSystemComponent::GetBodyInstance (FName BoneName = NAME_None, bool bGetWelded = true, int32 Index = INDEX_NONE) const override virtual
References INDEX_NONE.
GetColorParameter()
virtual bool UParticleSystemComponent::GetColorParameter (const FName InName, FLinearColor & OutColor) virtual
Retrieve the Color parameter value for the given name.
Parameters
InName Name of the parameter
OutColor The value of the parameter found
Returns
true Parameter was found - OutColor is valid false Parameter was not found - OutColor is invalid
References const, GetColorParameter(), and InName.
Referenced by GetColorParameter().
GetCurrentDetailMode()
int32 UParticleSystemComponent::GetCurrentDetailMode () const
Decide which detail mode should be applied to this particle system.
If we have an editor override specified, use that. Otherwise use the global cached value
GetCurrentLODIndex()
FORCEINLINE int32 UParticleSystemComponent::GetCurrentLODIndex () const inline
Definition at line 1546 of file ParticleSystemComponent.h.
References FORCEINLINE, GetCurrentLODIndex(), and LODLevel.
Referenced by GetCurrentLODIndex().
GetDetailedInfoInternal()
virtual FString UParticleSystemComponent::GetDetailedInfoInternal () const override virtual
GetFloatParameter()
virtual bool UParticleSystemComponent::GetFloatParameter (const FName InName, float & OutFloat) virtual
Retrieve the Float parameter value for the given name.
Parameters
InName Name of the parameter
OutFloat The value of the parameter found
Returns
true Parameter was found - OutFloat is valid false Parameter was not found - OutFloat is invalid
References const, GetFloatParameter(), and InName.
Referenced by GetFloatParameter().
GetFXSystemAsset()
virtual UFXSystemAsset * UParticleSystemComponent::GetFXSystemAsset () const inline virtual
Get the referenced FXSystem asset.
Definition at line 1174 of file ParticleSystemComponent.h.
References GetFXSystemAsset().
Referenced by GetFXSystemAsset().
GetLODLevel()
virtual int32 UParticleSystemComponent::GetLODLevel () virtual
Get the LOD level of the particle system.
References GetLODLevel().
Referenced by GetLODLevel().
GetLWCTile()
FORCEINLINE const FVector3f & UParticleSystemComponent::GetLWCTile () const inline
Definition at line 900 of file ParticleSystemComponent.h.
References FORCEINLINE, and LWCTile.
GetManagerHandle()
FORCEINLINE int32 UParticleSystemComponent::GetManagerHandle () const inline
Definition at line 634 of file ParticleSystemComponent.h.
References FORCEINLINE, and ManagerHandle.
GetManagerTickData()
FPSCTickData & UParticleSystemComponent::GetManagerTickData ()
GetMaterial()
virtual UMaterialInterface * UParticleSystemComponent::GetMaterial (int32 ElementIndex) const override virtual
GetMaterialByName()
virtual UMaterialInterface * UParticleSystemComponent::GetMaterialByName (FName MaterialSlotName) const override virtual
References const, and GetMaterialByName().
Referenced by GetMaterialByName().
GetMaterialParameter()
virtual bool UParticleSystemComponent::GetMaterialParameter (const FName InName, class UMaterialInterface *& OutMaterial) virtual
Retrieve the Material parameter value for the given name.
Parameters
InName Name of the parameter
OutMaterial The value of the parameter found
Returns
true Parameter was found - OutMaterial is valid false Parameter was not found - OutMaterial is invalid
References const, GetMaterialParameter(), and InName.
Referenced by GetMaterialParameter().
GetMaterialPropertyPath()
virtual bool UParticleSystemComponent::GetMaterialPropertyPath (int32 ElementIndex, UObject *& OutOwner, FString & OutPropertyPath, FProperty *& OutProperty) override virtual
GetNamedMaterialIndex()
virtual int32 UParticleSystemComponent::GetNamedMaterialIndex (FName InName) const virtual
Returns the index into the EmitterMaterials array for this named.
If there are no named material slots or this material is not found, INDEX_NONE is returned.
References const, GetNamedMaterialIndex(), and InName.
Referenced by GetNamedMaterialIndex().
GetNameForMaterial()
virtual FName UParticleSystemComponent::GetNameForMaterial (UMaterialInterface * InMaterial) const virtual
returns the name associated with the passed in material, returns NAME_None if it is not found
References const, and GetNameForMaterial().
Referenced by GetNameForMaterial().
GetNumMaterials()
virtual int32 UParticleSystemComponent::GetNumMaterials () const override virtual
GetOwnedTrailEmitters()
virtual void UParticleSystemComponent::GetOwnedTrailEmitters (TrailEmitterArray & OutTrailEmitters, const void * InOwner, bool bSetOwner = false) virtual
Fills the passed array with all trail emitters associated with a particular object.
Parameters
OutTrailEmitters The array to fill with pointers to the trail emitters.
InOwner The object that triggered this trail. Can be NULL if no assosiation was set by the owner. Not to be confused with the result of GetOwner().
bSetOwner If true, all trail emitters will be set as owned by InOwner.
References const, and GetOwnedTrailEmitters().
Referenced by GetOwnedTrailEmitters().
GetPerfStatsContext()
FORCEINLINE FParticlePerfStatsContext UParticleSystemComponent::GetPerfStatsContext () inline
Definition at line 1719 of file ParticleSystemComponent.h.
References FORCEINLINE, and GetPerfStatsContext().
Referenced by GetPerfStatsContext().
GetPlayerLocations()
FORCEINLINE const TArray< FVector > & UParticleSystemComponent::GetPlayerLocations () inline
Definition at line 955 of file ParticleSystemComponent.h.
References FORCEINLINE, and PlayerLocations.
GetPlayerLODDistanceFactor()
FORCEINLINE const TArray< float > & UParticleSystemComponent::GetPlayerLODDistanceFactor () inline
Definition at line 960 of file ParticleSystemComponent.h.
References FORCEINLINE, and PlayerLODDistanceFactor.
GetResourceSizeEx()
virtual void UParticleSystemComponent::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
GetStreamingRenderAssetInfo()
virtual void UParticleSystemComponent::GetStreamingRenderAssetInfo (FStreamingTextureLevelContext & LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > & OutStreamingRenderAssets) const override virtual
GetUsedMaterials()
virtual void UParticleSystemComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override virtual
GetVectorParameter()
virtual bool UParticleSystemComponent::GetVectorParameter (const FName InName, FVector & OutVector) virtual
Retrieve the Vector parameter value for the given name.
Parameters
InName Name of the parameter
OutVector The value of the parameter found
Returns
true Parameter was found - OutVector is valid false Parameter was not found - OutVector is invalid
References const, FVector, GetVectorParameter(), and InName.
Referenced by GetVectorParameter().
GetWorldManager()
FParticleSystemWorldManager * UParticleSystemComponent::GetWorldManager () const
References FParticleSystemWorldManager.
HasCompleted()
bool UParticleSystemComponent::HasCompleted ()
InitializeSystem()
void UParticleSystemComponent::InitializeSystem ()
InitParticles()
virtual void UParticleSystemComponent::InitParticles () virtual
IsComponentTickEnabled()
virtual bool UParticleSystemComponent::IsComponentTickEnabled () const override virtual
IsPendingManagerAdd()
FORCEINLINE int32 UParticleSystemComponent::IsPendingManagerAdd () const inline
Definition at line 637 of file ParticleSystemComponent.h.
References bPendingManagerAdd, and FORCEINLINE.
IsPendingManagerRemove()
FORCEINLINE int32 UParticleSystemComponent::IsPendingManagerRemove () const inline
Definition at line 639 of file ParticleSystemComponent.h.
References bPendingManagerRemove, and FORCEINLINE.
Referenced by IsTickManaged().
IsReadyForOwnerToAutoDestroy()
virtual bool UParticleSystemComponent::IsReadyForOwnerToAutoDestroy () const override virtual
IsTickManaged()
FORCEINLINE bool UParticleSystemComponent::IsTickManaged () const inline
Definition at line 633 of file ParticleSystemComponent.h.
References FORCEINLINE, INDEX_NONE, IsPendingManagerRemove(), and ManagerHandle.
KillParticlesForced()
void UParticleSystemComponent::KillParticlesForced ()
References KillParticlesForced().
Referenced by KillParticlesForced().
MarshalParamsForAsyncTick()
void UParticleSystemComponent::MarshalParamsForAsyncTick ()
OnAttachmentChanged()
virtual void UParticleSystemComponent::OnAttachmentChanged () override virtual
OnChildAttached()
virtual void UParticleSystemComponent::OnChildAttached (USceneComponent * ChildComponent) override virtual
OnChildDetached()
virtual void UParticleSystemComponent::OnChildDetached (USceneComponent * ChildComponent) override virtual
OnEndOfFrameUpdateDuringTick()
virtual void UParticleSystemComponent::OnEndOfFrameUpdateDuringTick () override virtual
OnRegister()
virtual void UParticleSystemComponent::OnRegister () override protected virtual
OnSignificanceChanged()
void UParticleSystemComponent::OnSignificanceChanged (bool bSignificant, bool bApplyToEmitters, bool bAsync = false)
When the overall significance for the component is changed.
OnUnregister()
virtual void UParticleSystemComponent::OnUnregister () override protected virtual
OrientZAxisTowardCamera()
void UParticleSystemComponent::OrientZAxisTowardCamera () protected
Orients the Z axis of the ParticleSystemComponent toward the camera while preserving the X axis direction.
References OrientZAxisTowardCamera().
Referenced by OrientZAxisTowardCamera().
ParticleLineCheck()
virtual bool UParticleSystemComponent::ParticleLineCheck (FHitResult & Hit, AActor * SourceActor, const FVector & End, const FVector & Start, const FVector & HalfExtent, const FCollisionObjectQueryParams & ObjectParams) virtual
References End, and FVector.
PostEditChangeChainProperty()
virtual void UParticleSystemComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
PostLoad()
virtual void UParticleSystemComponent::PostLoad () override virtual
PreEditChange()
virtual void UParticleSystemComponent::PreEditChange (FProperty * PropertyThatWillChange) override virtual
ReleaseToPool()
void UParticleSystemComponent::ReleaseToPool () override
References ReleaseToPool().
Referenced by ReleaseToPool().
ReportEventBurst()
void UParticleSystemComponent::ReportEventBurst (const FName InEventName, const float InEmitterTime, const int32 ParticleCount, const FVector InLocation, const TArray< class UParticleModuleEventSendToGame * > & InEventData)
Record a bursting event.
Parameters
InEventName The name of the event that fired.
InEmitterTime The emitter time when the event fired.
InParticleCount The number of particles spawned in the burst
InLocation The location of the particle emitter when the event fired.
References FVector, InEmitterTime, and InLocation.
ReportEventCollision()
void UParticleSystemComponent::ReportEventCollision (const FName InEventName, const float InEmitterTime, const FVector InLocation, const FVector InDirection, const FVector InVelocity, const TArray< class UParticleModuleEventSendToGame * > & InEventData, const float InParticleTime, const FVector InNormal, const float InTime, const int32 InItem, const FName InBoneName, UPhysicalMaterial * PhysMat)
Record a collision event.
Parameters
InEventName The name of the event that fired.
InEmitterTime The emitter time when the event fired.
InLocation The location of the particle when the event fired.
InDirection The direction of the particle when the event fired.
InVelocity The velocity of the particle when the event fired.
InEventData Gamespecific event data payload
InParticleTime The relative life of the particle when the event fired.
InNormal Normal vector of the collision in coordinate system of the returner. Zero=none.
InTime Time until hit, if line check.
InItem Primitive data item which was hit, INDEX_NONE=none.
InBoneName Name of bone we hit (for skeletal meshes).
References FVector, InDirection, InEmitterTime, InLocation, InTime, and InVelocity.
ReportEventDeath()
void UParticleSystemComponent::ReportEventDeath (const FName InEventName, const float InEmitterTime, const FVector InLocation, const FVector InVelocity, const TArray< class UParticleModuleEventSendToGame * > & InEventData, const float InParticleTime)
Record a death event.
Parameters
InEventName The name of the event that fired.
InEmitterTime The emitter time when the event fired.
InLocation The location of the particle when the event fired.
InVelocity The velocity of the particle when the event fired.
InEventData Gamespecific event data payload
InParticleTime The relative life of the particle when the event fired.
References FVector, InEmitterTime, InLocation, and InVelocity.
ReportEventSpawn()
void UParticleSystemComponent::ReportEventSpawn (const FName InEventName, const float InEmitterTime, const FVector InLocation, const FVector InVelocity, const TArray< class UParticleModuleEventSendToGame * > & InEventData)
Event reporting...
Record a spawning event.
Parameters
InEventName The name of the event that fired.
InEmitterTime The emitter time when the event fired.
InLocation The location of the particle when the event fired.
InVelocity The velocity of the particle when the event fired.
InEventData Gamespecific event data payload
References FVector, InEmitterTime, InLocation, and InVelocity.
ResetBurstLists()
void UParticleSystemComponent::ResetBurstLists ()
ResetNextTick()
void UParticleSystemComponent::ResetNextTick () inline
Definition at line 660 of file ParticleSystemComponent.h.
References bResetTriggered, and ResetNextTick().
Referenced by ResetNextTick().
ResetParticles()
void UParticleSystemComponent::ResetParticles (bool bEmptyInstances = false)
ResetToDefaults()
void UParticleSystemComponent::ResetToDefaults ()
stops the emitter, unregisters the component, and resets the component's properties to the values of its template
References ResetToDefaults().
Referenced by ResetToDefaults().
RewindEmitterInstances()
virtual void UParticleSystemComponent::RewindEmitterInstances () virtual
References RewindEmitterInstances().
Referenced by RewindEmitterInstances().
SendRenderDynamicData_Concurrent()
virtual void UParticleSystemComponent::SendRenderDynamicData_Concurrent () override protected virtual
SendRenderTransform_Concurrent()
virtual void UParticleSystemComponent::SendRenderTransform_Concurrent () override protected virtual
Serialize()
virtual void UParticleSystemComponent::Serialize (FArchive & Ar) override virtual
References Ar.
SetActorParameter()
void UParticleSystemComponent::SetActorParameter (FName ParameterName, class AActor * Param) override
Set a named actor instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References Param, and SetActorParameter().
Referenced by SetActorParameter().
SetAsyncWork()
FORCEINLINE void UParticleSystemComponent::SetAsyncWork (FGraphEventRef & InAsyncWork) inline private
In some cases the async work for this PSC can be created externally by the manager.
Definition at line 1323 of file ParticleSystemComponent.h.
References AsyncWork, FORCEINLINE, and SetAsyncWork().
Referenced by SetAsyncWork().
SetAutoAttachmentParameters()
void UParticleSystemComponent::SetAutoAttachmentParameters (USceneComponent * Parent, FName SocketName, EAttachmentRule LocationRule, EAttachmentRule RotationRule, EAttachmentRule ScaleRule) override
Set AutoAttachParent, AutoAttachSocketName, AutoAttachLocationRule, AutoAttachRotationRule, AutoAttachScaleRule to the specified parameters.
Does not change bAutoManageAttachment; that must be set separately.
Parameters
Parent Component to attach to.
SocketName Socket on Parent to attach to.
LocationRule Option for how we handle our location when we attach to Parent.
RotationRule Option for how we handle our rotation when we attach to Parent.
ScaleRule Option for how we handle our scale when we attach to Parent.
See also
bAutoManageAttachment, AutoAttachParent, AutoAttachSocketName, AutoAttachLocationRule, AutoAttachRotationRule, AutoAttachScaleRule
References Parent, SetAutoAttachmentParameters(), and SocketName.
Referenced by SetAutoAttachmentParameters().
SetBoolParameter()
void UParticleSystemComponent::SetBoolParameter (FName ParameterName, bool Param) override
Set a named float instance parameter on this ParticleSystemComponent.
This is for function parity with the VFX Marshaller. The bool is converted and then set to a float.
References Param, and SetBoolParameter().
Referenced by SetBoolParameter().
SetColorParameter()
void UParticleSystemComponent::SetColorParameter (FName ParameterName, FLinearColor Param) override
Set a named color instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References Param, and SetColorParameter().
Referenced by SetColorParameter().
SetComponentTickEnabled()
virtual void UParticleSystemComponent::SetComponentTickEnabled (bool bEnabled) override virtual
SetEmitterEnable()
void UParticleSystemComponent::SetEmitterEnable (FName EmitterName, bool bNewEnableState) override
Enables/Disables a sub-emitter.
Parameters
EmitterName The name of the sub-emitter to set it on
bNewEnableState The value to set it to
References SetEmitterEnable().
Referenced by SetEmitterEnable().
SetFloatParameter()
void UParticleSystemComponent::SetFloatParameter (FName ParameterName, float Param) override
Change a named float parameter.
References Param, and SetFloatParameter().
Referenced by SetFloatParameter().
SetFloatRandParameter()
void UParticleSystemComponent::SetFloatRandParameter (FName ParameterName, float Param, float ParamLow)
Set a named random float instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References Param, and SetFloatRandParameter().
Referenced by SetFloatRandParameter().
SetIntParameter()
void UParticleSystemComponent::SetIntParameter (FName ParameterName, int Param) override
Set a named float instance parameter on this ParticleSystemComponent.
This is for function parity with the VFX Marshaller. The int is converted and then set to a float.
References Param, and SetIntParameter().
Referenced by SetIntParameter().
SetLODLevel()
virtual void UParticleSystemComponent::SetLODLevel (int32 InLODLevel) virtual
Set the LOD level of the particle system.
References SetLODLevel().
Referenced by SetLODLevel().
SetManagerHandle()
FORCEINLINE void UParticleSystemComponent::SetManagerHandle (int32 InHandle) inline
Definition at line 635 of file ParticleSystemComponent.h.
References FORCEINLINE, and ManagerHandle.
SetManagingSignificance()
FORCEINLINE void UParticleSystemComponent::SetManagingSignificance (bool bManageSignificance) inline
Called from game code when the component begins having it's significance managed.
Definition at line 894 of file ParticleSystemComponent.h.
References bIsManagingSignificance, bWasManagingSignificance, and FORCEINLINE.
SetMaterial()
virtual void UParticleSystemComponent::SetMaterial (int32 ElementIndex, UMaterialInterface * Material) override virtual
References Material.
SetMaterialByName()
virtual void UParticleSystemComponent::SetMaterialByName (FName MaterialSlotName, class UMaterialInterface * SourceMaterial) override virtual
References SetMaterialByName(), and SourceMaterial.
Referenced by SetMaterialByName().
SetPendingManagerAdd()
FORCEINLINE void UParticleSystemComponent::SetPendingManagerAdd (bool bValue) inline
Definition at line 638 of file ParticleSystemComponent.h.
References bPendingManagerAdd, and FORCEINLINE.
SetPendingManagerRemove()
FORCEINLINE void UParticleSystemComponent::SetPendingManagerRemove (bool bValue) inline
Definition at line 640 of file ParticleSystemComponent.h.
References bPendingManagerRemove, and FORCEINLINE.
SetRequiredSignificance()
void UParticleSystemComponent::SetRequiredSignificance (EParticleSignificanceLevel NewRequiredSignificance)
Called from game code when the significance required for a component changes.
SetUseAutoManageAttachment()
virtual void UParticleSystemComponent::SetUseAutoManageAttachment (bool bAutoManage) inline override virtual
Definition at line 855 of file ParticleSystemComponent.h.
References SetUseAutoManageAttachment().
Referenced by SetUseAutoManageAttachment().
SetVectorParameter()
void UParticleSystemComponent::SetVectorParameter (FName ParameterName, FVector Param) override
Set a named vector instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References FVector, Param, and SetVectorParameter().
Referenced by SetVectorParameter().
SetVectorRandParameter()
void UParticleSystemComponent::SetVectorRandParameter (FName ParameterName, const FVector & Param, const FVector & ParamLow)
Set a named random vector instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References const, FVector, Param, and SetVectorRandParameter().
Referenced by SetVectorRandParameter().
SetVectorUnitRandParameter()
void UParticleSystemComponent::SetVectorUnitRandParameter (FName ParameterName, const FVector & Param, const FVector & ParamLow)
Set a named random unit vector instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References const, FVector, Param, and SetVectorUnitRandParameter().
Referenced by SetVectorUnitRandParameter().
ShouldActivate()
virtual bool UParticleSystemComponent::ShouldActivate () const override protected virtual
ShouldBeTickManaged()
bool UParticleSystemComponent::ShouldBeTickManaged () const
ShouldComputeLODFromGameThread()
bool UParticleSystemComponent::ShouldComputeLODFromGameThread () private
Returns true if this component can and should compute it's LOD without visibility information from the renderer.
References ShouldComputeLODFromGameThread().
Referenced by ShouldComputeLODFromGameThread().
ShouldManageSignificance()
bool UParticleSystemComponent::ShouldManageSignificance () const
Whether this component should have it's significance managed by game code.
TickComponent()
virtual void UParticleSystemComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
References DeltaTime.
UFUNCTION() [1/24]
UParticleSystemComponent::UFUNCTION () const
Get the current number of active particles in this system.
References Category, const, and UFUNCTION().
UFUNCTION() [2/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam end point.
Parameters
EmitterIndex The index of the emitter to get the value of
Returns
true EmitterIndex is valid and End point is set - OutEndPoint is valid false EmitterIndex invalid or End point is not set - OutEndPoint is invalid
References Category, and UFUNCTION().
UFUNCTION() [3/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam source point.
Parameters
EmitterIndex The index of the emitter to get
SourceIndex Which beam within the emitter to get
OutSourcePoint Value of source point
Returns
true EmitterIndex and SourceIndex are valid - OutSourcePoint is valid false EmitterIndex or SourceIndex is invalid - OutSourcePoint is invalid
References Category, and UFUNCTION().
UFUNCTION() [4/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam source strength.
Parameters
EmitterIndex The index of the emitter to get
SourceIndex Which beam within the emitter to get
OutSourceStrength Value of source tangent
Returns
true EmitterIndex and SourceIndex are valid - OutSourceStrength is valid false EmitterIndex or SourceIndex is invalid - OutSourceStrength is invalid
References Category, and UFUNCTION().
UFUNCTION() [5/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam source tangent.
Parameters
EmitterIndex The index of the emitter to get
SourceIndex Which beam within the emitter to get
OutTangentPoint Value of source tangent
Returns
true EmitterIndex and SourceIndex are valid - OutTangentPoint is valid false EmitterIndex or SourceIndex is invalid - OutTangentPoint is invalid
References Category, and UFUNCTION().
UFUNCTION() [6/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam target point.
Parameters
EmitterIndex The index of the emitter to get
TargetIndex Which beam within the emitter to get
OutTargetPoint Value of target point
Returns
true EmitterIndex and TargetIndex are valid - OutTargetPoint is valid false EmitterIndex or TargetIndex is invalid - OutTargetPoint is invalid
References Category, and UFUNCTION().
UFUNCTION() [7/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam target strength.
Parameters
EmitterIndex The index of the emitter to get
TargetIndex Which beam within the emitter to get
OutTargetStrength Value of target tangent
Returns
true EmitterIndex and TargetIndex are valid - OutTargetStrength is valid false EmitterIndex or TargetIndex is invalid - OutTargetStrength is invalid
References Category, and UFUNCTION().
UFUNCTION() [8/24]
UParticleSystemComponent::UFUNCTION ()
Get the beam target tangent.
Parameters
EmitterIndex The index of the emitter to get
TargetIndex Which beam within the emitter to get
OutTangentPoint Value of target tangent
Returns
true EmitterIndex and TargetIndex are valid - OutTangentPoint is valid false EmitterIndex or TargetIndex is invalid - OutTangentPoint is invalid
References Category, const, FVector, TargetIndex, and UFUNCTION().
UFUNCTION() [9/24]
UParticleSystemComponent::UFUNCTION ()
Creates a Dynamic Material Instance for the specified named material override, optionally from the supplied material.
Parameters
Name - The slot name of the material to replace. If invalid, the material is unchanged and NULL is returned.
References Category.
UFUNCTION() [10/24]
UParticleSystemComponent::UFUNCTION () const
Returns a named material.
If this named material is not found, returns NULL.
References Category, const, InName, and UFUNCTION().
UFUNCTION() [11/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam end point.
Parameters
EmitterIndex The index of the emitter to set it on
NewEndPoint The value to set it to
References Category.
UFUNCTION() [12/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam source point.
Parameters
EmitterIndex The index of the emitter to set it on
NewSourcePoint The value to set it to
SourceIndex Which beam within the emitter to set it on
References Category, and UFUNCTION().
UFUNCTION() [13/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam source strength.
Parameters
EmitterIndex The index of the emitter to set it on
NewSourceStrength The value to set it to
SourceIndex Which beam within the emitter to set it on
References Category, and UFUNCTION().
UFUNCTION() [14/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam source tangent.
Parameters
EmitterIndex The index of the emitter to set it on
NewTangentPoint The value to set it to
SourceIndex Which beam within the emitter to set it on
References Category, and UFUNCTION().
UFUNCTION() [15/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam target point.
Parameters
EmitterIndex The index of the emitter to set it on
NewTargetPoint The value to set it to
TargetIndex Which beam within the emitter to set it on
References Category, and UFUNCTION().
UFUNCTION() [16/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam target strength.
Parameters
EmitterIndex The index of the emitter to set it on
NewTargetStrength The value to set it to
TargetIndex Which beam within the emitter to set it on
References Category, and UFUNCTION().
UFUNCTION() [17/24]
UParticleSystemComponent::UFUNCTION ()
Set the beam target tangent.
Parameters
EmitterIndex The index of the emitter to set it on
NewTangentPoint The value to set it to
TargetIndex Which beam within the emitter to set it on
References Category, FVector, NewTangentPoint, TargetIndex, and UFUNCTION().
UFUNCTION() [18/24]
UParticleSystemComponent::UFUNCTION ()
Begins all trail emitters in this component.
Parameters
InFirstSocketName The name of the first socket for the trail.
InSecondSocketName The name of the second socket for the trail.
InWidthMode How the width value is applied to the trail.
InWidth The width of the trail.
References Category, and UFUNCTION().
UFUNCTION() [19/24]
UParticleSystemComponent::UFUNCTION ()
Ends all trail emitters in this component.
References Category, and UFUNCTION().
UFUNCTION() [20/24]
UParticleSystemComponent::UFUNCTION () const
Record a kismet event.
Parameters
InEventName The name of the event that fired.
InEmitterTime The emitter time when the event fired.
InLocation The location of the particle when the event fired.
InVelocity The velocity of the particle when the event fired.
InNormal Normal vector of the collision in coordinate system of the returner. Zero=none.
References Category.
UFUNCTION() [21/24]
UParticleSystemComponent::UFUNCTION ()
Set a named material instance parameter on this ParticleSystemComponent.
Updates the parameter if it already exists, or creates a new entry if not.
References Category.
UFUNCTION() [22/24]
UParticleSystemComponent::UFUNCTION ()
Change the ParticleSystem used by this ParticleSystemComponent.
References Category, and UFUNCTION().
UFUNCTION() [23/24]
UParticleSystemComponent::UFUNCTION ()
Sets the defining data for all trails in this component.
Parameters
InFirstSocketName The name of the first socket for the trail.
InSecondSocketName The name of the second socket for the trail.
InWidthMode How the width value is applied to the trail.
InWidth The width of the trail.
References Category, InSecondSocketName, InWidth, InWidthMode, and UFUNCTION().
UFUNCTION() [24/24]
UParticleSystemComponent::UFUNCTION ()
DEPRECATED: Set AutoAttachParent, AutoAttachSocketName, AutoAttachLocationType to the specified parameters.
Does not change bAutoManageAttachment; that must be set separately.
Parameters
Parent Component to attach to.
SocketName Socket on Parent to attach to.
LocationType Option for how we handle our location when we attach to Parent.
See also
bAutoManageAttachment, AutoAttachParent, AutoAttachSocketName, AutoAttachLocationType
References Category, meta, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UpdateDynamicData()
virtual void UParticleSystemComponent::UpdateDynamicData () protected virtual
References UpdateDynamicData().
Referenced by UpdateDynamicData().
UpdateInstances()
void UParticleSystemComponent::UpdateInstances (bool bEmptyInstances = false)
UpdateLODInformation()
virtual void UParticleSystemComponent::UpdateLODInformation () protected virtual
References UpdateLODInformation().
Referenced by UpdateLODInformation().
UPROPERTY() [1/24]
UParticleSystemComponent::UPROPERTY ()
References Transient.
UPROPERTY() [2/24]
UParticleSystemComponent::UPROPERTY ()
The significance this component requires of it's emitters for them to be enabled.
UPROPERTY() [3/24]
UParticleSystemComponent::UPROPERTY ()
Scales DeltaTime in UParticleSystemComponent::Tick(...)
References Category, and UPROPERTY().
UPROPERTY() [4/24]
UParticleSystemComponent::UPROPERTY ()
Time between forced UpdateTransforms for systems that use dynamically calculated bounds, Which is effectively how often the bounds are shrunk.
References float, and UPROPERTY().
UPROPERTY() [5/24]
UParticleSystemComponent::UPROPERTY ()
Number of seconds of emitter not being rendered that need to pass before it no longer gets ticked/ becomes inactive.
References Category.
UPROPERTY() [6/24]
UParticleSystemComponent::UPROPERTY ()
References Transient.
UPROPERTY() [7/24]
UParticleSystemComponent::UPROPERTY ()
References Transient.
UPROPERTY() [8/24]
UParticleSystemComponent::UPROPERTY ()
UPROPERTY() [9/24]
UParticleSystemComponent::UPROPERTY ()
UPROPERTY() [10/24]
UParticleSystemComponent::UPROPERTY ()
UPROPERTY() [11/24]
UParticleSystemComponent::UPROPERTY ()
UPROPERTY() [12/24]
UParticleSystemComponent::UPROPERTY ()
UPROPERTY() [13/24]
UParticleSystemComponent::UPROPERTY ()
References FVector, and Transient.
UPROPERTY() [14/24]
UParticleSystemComponent::UPROPERTY ()
References FVector, and Transient.
UPROPERTY() [15/24]
UParticleSystemComponent::UPROPERTY ()
Array holding name instance parameters for this ParticleSystemComponent.
Parameters can be used in Cascade using DistributionFloat/VectorParticleParameters.
References Category.
UPROPERTY() [16/24]
UParticleSystemComponent::UPROPERTY () private
References transient, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [17/24]
UParticleSystemComponent::UPROPERTY ()
Array of replay clips for this particle system component.
These are serialized to disk. You really should never add anything to this in the editor. It's exposed so that you can delete clips if you need to, but be careful when doing so!
UPROPERTY() [18/24]
UParticleSystemComponent::UPROPERTY () private
The skeletal mesh components used with the socket location module.
This is to prevent them from being garbage collected.
References transient, and UPROPERTY().
UPROPERTY() [19/24]
UParticleSystemComponent::UPROPERTY ()
The method of LOD level determination to utilize for this particle system.
References Category, and LOD.
UPROPERTY() [20/24]
UParticleSystemComponent::UPROPERTY ()
Options for how we handle our location when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
See also
bAutoManageAttachment, EAttachmentRule
References Category, and meta.
UPROPERTY() [21/24]
UParticleSystemComponent::UPROPERTY ()
Options for how we handle our rotation when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
See also
bAutoManageAttachment, EAttachmentRule
References Category, meta, and UPROPERTY().
UPROPERTY() [22/24]
UParticleSystemComponent::UPROPERTY ()
Options for how we handle our scale when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
See also
bAutoManageAttachment, EAttachmentRule
References Category, meta, and UPROPERTY().
UPROPERTY() [23/24]
UParticleSystemComponent::UPROPERTY ()
Socket we automatically attach to on the AutoAttachParent, if bAutoManageAttachment is true.
If no auto attach socket name is set during registration, the current attach socket will be assigned to AutoAttachSocketName and used when activated.
See also
bAutoManageAttachment
References Category, meta, and UPROPERTY().
UPROPERTY() [24/24]
UParticleSystemComponent::UPROPERTY ()
Component we automatically attach to when activated, if bAutoManageAttachment is true.
If null during registration, we assign the existing AttachParent and defer attachment until we activate.
See also
bAutoManageAttachment
References Category, meta, and UPROPERTY().
WaitForAsyncAndFinalize()
void UParticleSystemComponent::WaitForAsyncAndFinalize (EForceAsyncWorkCompletion Behavior, bool bDefinitelyGameThread = true) const private
Wait on the async task and call finalize on the tick.
Referenced by ForceAsyncWorkCompletion(), and ForceAsyncWorkCompletion().
Friends And Related Symbol Documentation
FParticleSystemWorldManager
friend class FParticleSystemWorldManager friend
Definition at line 489 of file ParticleSystemComponent.h.
References FParticleSystemWorldManager.
Referenced by FParticleSystemWorldManager, and GetWorldManager().
Field Documentation
AccumLODDistanceCheckTime
float UParticleSystemComponent::AccumLODDistanceCheckTime
LOD updating...
Definition at line 749 of file ParticleSystemComponent.h.
AccumTickTime
float UParticleSystemComponent::AccumTickTime
Used to accumulate total tick time to determine whether system can be skipped ticking if not visible.
Definition at line 743 of file ParticleSystemComponent.h.
AsyncBounds
FBoxSphereBounds UParticleSystemComponent::AsyncBounds private
Cached copy of bounds.
Definition at line 879 of file ParticleSystemComponent.h.
Referenced by GetAsyncBounds().
AsyncComponentToWorld
FTransform UParticleSystemComponent::AsyncComponentToWorld private
Cached copy of the transform for async work.
Definition at line 1326 of file ParticleSystemComponent.h.
Referenced by GetAsyncComponentToWorld().
AsyncInstanceParameters
TArray<struct FParticleSysParam> UParticleSystemComponent::AsyncInstanceParameters private
Cached copy of the instance params.
Definition at line 873 of file ParticleSystemComponent.h.
Referenced by GetAsyncInstanceParameters().
AsyncPartSysVelocity
FVector UParticleSystemComponent::AsyncPartSysVelocity private
Cached copy of PartSysVelocity.
Definition at line 881 of file ParticleSystemComponent.h.
Referenced by GetAsyncPartSysVelocity().
AsyncWork
FGraphEventRef UParticleSystemComponent::AsyncWork private
Task ref for parallel portion.
Definition at line 1329 of file ParticleSystemComponent.h.
Referenced by ForceAsyncWorkCompletion(), ForceAsyncWorkCompletion(), and SetAsyncWork().
bAsyncDataCopyIsValid
uint8 UParticleSystemComponent::bAsyncDataCopyIsValid private
Is AsyncComponentToWorld etc valid?
Definition at line 607 of file ParticleSystemComponent.h.
Referenced by GetAsyncBounds(), GetAsyncComponentToWorld(), GetAsyncInstanceParameters(), and GetAsyncPartSysVelocity().
bAsyncWorkOutstanding
volatile bool UParticleSystemComponent::bAsyncWorkOutstanding private
If true, it means the Async work is in process and not yet completed.
Definition at line 614 of file ParticleSystemComponent.h.
bAutoDestroy
uint8 UParticleSystemComponent::bAutoDestroy
Definition at line 596 of file ParticleSystemComponent.h.
bDeactivateTriggered
uint8 UParticleSystemComponent::bDeactivateTriggered
If true, someone has requested this component deactivate.
Definition at line 526 of file ParticleSystemComponent.h.
Referenced by DeactivaateNextTick().
bDidAutoAttach
uint8 UParticleSystemComponent::bDidAutoAttach private
Did we auto attach during activation?
Used to determine if we should restore the relative transform during detachment.
Definition at line 604 of file ParticleSystemComponent.h.
bForcedInActive
UPROPERTY () uint8 bWarmingUp UPROPERTY () uint8 bOverrideLODMethod UPROPERTY () uint8 bSkipUpdateDynamicDataDuringTick uint8 UParticleSystemComponent::bForcedInActive
indicates that the component's LODMethod overrides the Template's
Flag indicating that dynamic updating of render data should NOT occur during Tick. This is used primarily to allow for warming up and simulated effects to a certain state. This is set when any of our "don't tick me" timeout values have fired
Definition at line 588 of file ParticleSystemComponent.h.
bForceLODUpdateFromRenderer
uint8 UParticleSystemComponent::bForceLODUpdateFromRenderer
If true, force an LOD update from the renderer.
Definition at line 591 of file ParticleSystemComponent.h.
bHasBeenActivated
uint8 UParticleSystemComponent::bHasBeenActivated
This flag will be set the first time the PSysComp is activated... used to prevent auto activated PSysComps from calling InitParticles twice on level load.
Definition at line 539 of file ParticleSystemComponent.h.
bIsDuringRegister
uint8 UParticleSystemComponent::bIsDuringRegister
Definition at line 571 of file ParticleSystemComponent.h.
bIsElligibleForAsyncTick
uint8 UParticleSystemComponent::bIsElligibleForAsyncTick private
if true, this psys can tick in any thread
Definition at line 512 of file ParticleSystemComponent.h.
Referenced by CanTickInAnyThread().
bIsElligibleForAsyncTickComputed
uint8 UParticleSystemComponent::bIsElligibleForAsyncTickComputed private
if true, bIsElligibleForAsyncTick is set up
Definition at line 514 of file ParticleSystemComponent.h.
Referenced by CanTickInAnyThread().
bIsManagingSignificance
UPROPERTY () uint8 bAllowRecycling UPROPERTY () uint8 bAutoManageAttachment UPROPERTY ()) uint8 bAutoAttachWeldSimulatedBodies uint8 UParticleSystemComponent::bIsManagingSignificance
If true, this Particle System will be available for recycling after it has completed.
Auto-destroyed systems cannot be recycled. Some systems (currently particle trail effects) can recycle components to avoid respawning them to play new effects. This is only an optimization and does not change particle system behavior, aside from not triggering normal component initialization events more than once. True if we should automatically attach to AutoAttachParent when activated, and detach from our parent when completed. This overrides any current attachment that may be present at the time of activation (deferring initial attachment until activation, if AutoAttachParent is null). When enabled, detachment occurs regardless of whether AutoAttachParent is assigned, and the relative transform from the time of activation is restored. This also disables attachment on dedicated servers, where we don't actually activate even if bAutoActivate is true.
See also
AutoAttachParent, AutoAttachSocketName, AutoAttachLocationType Option for how we handle bWeldSimulatedBodies when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
bAutoManageAttachment If this component is having it's significance managed by gameplay code.
Definition at line 567 of file ParticleSystemComponent.h.
Referenced by SetManagingSignificance().
bIsTransformDirty
uint8 UParticleSystemComponent::bIsTransformDirty private
Indicates if the component's transform has been changed and requires updating.
Definition at line 601 of file ParticleSystemComponent.h.
bIsViewRelevanceDirty
uint8 UParticleSystemComponent::bIsViewRelevanceDirty
If true, the ViewRelevanceFlags are dirty and should be recached.
Definition at line 594 of file ParticleSystemComponent.h.
bJustRegistered
UPROPERTY () uint8 bResetOnDetach UPROPERTY () uint8 bUpdateOnDedicatedServer uint8 UParticleSystemComponent::bJustRegistered
whether to update the particle system on dedicated servers
Indicates that the component has not been ticked since being registered.
Definition at line 536 of file ParticleSystemComponent.h.
bNeedsFinalize
uint8 UParticleSystemComponent::bNeedsFinalize private
If true, it means the ASync work is done and the finalize is not.
Definition at line 611 of file ParticleSystemComponent.h.
bParallelRenderThreadUpdate
uint8 UParticleSystemComponent::bParallelRenderThreadUpdate private
Definition at line 608 of file ParticleSystemComponent.h.
Referenced by GetAsyncBounds(), GetAsyncComponentToWorld(), GetAsyncInstanceParameters(), and GetAsyncPartSysVelocity().
bPendingManagerAdd
int32 UParticleSystemComponent::bPendingManagerAdd private
Flag denoting we are currently in the pending queue to be added to the manager.
Definition at line 622 of file ParticleSystemComponent.h.
Referenced by IsPendingManagerAdd(), and SetPendingManagerAdd().
bPendingManagerRemove
int32 UParticleSystemComponent::bPendingManagerRemove private
Flag denoting we have been unregistered and are awaiting removal from the managers arrays.
Definition at line 624 of file ParticleSystemComponent.h.
Referenced by IsPendingManagerRemove(), and SetPendingManagerRemove().
bResetTriggered
uint8 UParticleSystemComponent::bResetTriggered
If true, someone has requested this component reset.
Definition at line 523 of file ParticleSystemComponent.h.
Referenced by ResetNextTick().
bSuppressSpawning
uint8 UParticleSystemComponent::bSuppressSpawning private
Definition at line 508 of file ParticleSystemComponent.h.
BurstEvents
TArray<struct FParticleEventBurstData> UParticleSystemComponent::BurstEvents
The Burst events that occurred in this PSysComp.
Definition at line 781 of file ParticleSystemComponent.h.
bWasActive
uint8 UParticleSystemComponent::bWasActive
True if this was active before being unregistered or otherwise reset, if so reactivate it.
Definition at line 520 of file ParticleSystemComponent.h.
bWasCompleted
uint8 UParticleSystemComponent::bWasCompleted private
Definition at line 506 of file ParticleSystemComponent.h.
bWasDeactivated
uint8 UParticleSystemComponent::bWasDeactivated
Definition at line 517 of file ParticleSystemComponent.h.
bWasManagingSignificance
uint8 UParticleSystemComponent::bWasManagingSignificance
If this component was previously having it's significance managed by gameplay code.
Allows us to refresh render data when this changes.
Definition at line 569 of file ParticleSystemComponent.h.
Referenced by SetManagingSignificance().
CachedViewRelevanceFlags
TArray<FMaterialRelevance> UParticleSystemComponent::CachedViewRelevanceFlags
The view relevance flags for each LODLevel.
Definition at line 752 of file ParticleSystemComponent.h.
CollisionEvents
TArray<struct FParticleEventCollideData> UParticleSystemComponent::CollisionEvents
The Collision events that occurred in this PSysComp.
Definition at line 778 of file ParticleSystemComponent.h.
const [1/6]
int32 FVector &OutTangentPoint UParticleSystemComponent::const
Definition at line 1047 of file ParticleSystemComponent.h.
Referenced by CancelAutoAttachment(), CreateDynamicDataFromReplay(), DetermineLODLevelForLocation(), FindReplayClipForIDNumber(), GetActorParameter(), GetAnyVectorParameter(), GetApproxMemoryUsage(), GetColorParameter(), GetFloatParameter(), GetMaterialByName(), GetMaterialParameter(), GetNamedMaterialIndex(), GetNameForMaterial(), GetOwnedTrailEmitters(), GetVectorParameter(), SetVectorRandParameter(), SetVectorUnitRandParameter(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
const [2/6]
int32 FVector& OutSourcePoint UParticleSystemComponent::const
Definition at line 1060 of file ParticleSystemComponent.h.
const [3/6]
int32 FVector& OutTangentPoint UParticleSystemComponent::const
Definition at line 1073 of file ParticleSystemComponent.h.
const [4/6]
int32 float& OutSourceStrength UParticleSystemComponent::const
Definition at line 1086 of file ParticleSystemComponent.h.
const [5/6]
int32 FVector& OutTargetPoint UParticleSystemComponent::const
Definition at line 1099 of file ParticleSystemComponent.h.
const [6/6]
int32 float& OutTargetStrength UParticleSystemComponent::const
Definition at line 1125 of file ParticleSystemComponent.h.
DeathEvents
TArray<struct FParticleEventDeathData> UParticleSystemComponent::DeathEvents
The Death events that occurred in this PSysComp.
Definition at line 775 of file ParticleSystemComponent.h.
DeltaTimeTick
float UParticleSystemComponent::DeltaTimeTick private
Copy of delta time coming into TickComponent.
Definition at line 1332 of file ParticleSystemComponent.h.
EmitterDelay
float UParticleSystemComponent::EmitterDelay
This is created at start up and then added to each emitter.
Definition at line 769 of file ParticleSystemComponent.h.
EmitterInstances
TArray<struct FParticleEmitterInstance*> UParticleSystemComponent::EmitterInstances
Definition at line 1309 of file ParticleSystemComponent.h.
FXSystem
class FFXSystem* UParticleSystemComponent::FXSystem
Definition at line 865 of file ParticleSystemComponent.h.
InDirection
const float const FVector const FVector UParticleSystemComponent::InDirection
Definition at line 1652 of file ParticleSystemComponent.h.
Referenced by ReportEventCollision().
InEmitterTime
const float UParticleSystemComponent::InEmitterTime
Definition at line 1651 of file ParticleSystemComponent.h.
Referenced by ReportEventBurst(), ReportEventCollision(), ReportEventDeath(), and ReportEventSpawn().
InLocation
const float const FVector UParticleSystemComponent::InLocation
Definition at line 1652 of file ParticleSystemComponent.h.
Referenced by ReportEventBurst(), ReportEventCollision(), ReportEventDeath(), and ReportEventSpawn().
InSecondSocketName
FName UParticleSystemComponent::InSecondSocketName
Definition at line 1284 of file ParticleSystemComponent.h.
Referenced by UFUNCTION().
InstanceOwner
TUniquePtr<FInstanceOwner> UParticleSystemComponent::InstanceOwner
Definition at line 1319 of file ParticleSystemComponent.h.
InVelocity
const float const FVector const FVector const FVector UParticleSystemComponent::InVelocity
Definition at line 1652 of file ParticleSystemComponent.h.
Referenced by ReportEventCollision(), ReportEventDeath(), and ReportEventSpawn().
InWidth
FName ETrailWidthMode float UParticleSystemComponent::InWidth
Definition at line 1284 of file ParticleSystemComponent.h.
Referenced by UFUNCTION().
InWidthMode
FName ETrailWidthMode UParticleSystemComponent::InWidthMode
Definition at line 1284 of file ParticleSystemComponent.h.
Referenced by UFUNCTION().
KismetEvents
TArray<struct FParticleEventKismetData> UParticleSystemComponent::KismetEvents
The Kismet events that occurred for this PSysComp.
Definition at line 784 of file ParticleSystemComponent.h.
LastSignificantTime
float UParticleSystemComponent::LastSignificantTime
Time in seconds since we were last considered significant.
Definition at line 746 of file ParticleSystemComponent.h.
LocationType
FName EAttachLocation::Type UParticleSystemComponent::LocationType = EAttachLocation::KeepRelativeOffset)
Definition at line 842 of file ParticleSystemComponent.h.
LODLevel
int32 UParticleSystemComponent::LODLevel private
Definition at line 705 of file ParticleSystemComponent.h.
Referenced by GetCurrentLODIndex().
LWCTile
FVector3f UParticleSystemComponent::LWCTile = FVector3f::ZeroVector private
LWC tile offset for gpu simulations.
Definition at line 883 of file ParticleSystemComponent.h.
Referenced by GetLWCTile().
ManagerHandle
int32 UParticleSystemComponent::ManagerHandle private
Handle into the FParticleSystemWorldManager.
INDEX_NONE if this component does not have managed ticks.
Definition at line 620 of file ParticleSystemComponent.h.
Referenced by GetManagerHandle(), IsTickManaged(), and SetManagerHandle().
NewEndPoint
FVector UParticleSystemComponent::NewEndPoint
Definition at line 976 of file ParticleSystemComponent.h.
NewSourcePoint
FVector UParticleSystemComponent::NewSourcePoint
Definition at line 986 of file ParticleSystemComponent.h.
NewSourceStrength
float UParticleSystemComponent::NewSourceStrength
Definition at line 1006 of file ParticleSystemComponent.h.
NewTangentPoint
FVector UParticleSystemComponent::NewTangentPoint
Definition at line 996 of file ParticleSystemComponent.h.
Referenced by UFUNCTION().
NewTargetPoint
FVector UParticleSystemComponent::NewTargetPoint
Definition at line 1016 of file ParticleSystemComponent.h.
NewTargetStrength
float UParticleSystemComponent::NewTargetStrength
Definition at line 1036 of file ParticleSystemComponent.h.
NumSignificantEmitters
uint32 UParticleSystemComponent::NumSignificantEmitters private
Number of significant emitters.
When this is 0, the system can either be deactivated or stopped ticking.
Definition at line 1336 of file ParticleSystemComponent.h.
OnSystemPreActivationChange
FOnSystemPreActivationChange UParticleSystemComponent::OnSystemPreActivationChange static
Static delegate called for all systems on an activation change.
Definition at line 1312 of file ParticleSystemComponent.h.
Param
class UMaterialInterface* UParticleSystemComponent::Param
Definition at line 1181 of file ParticleSystemComponent.h.
Referenced by SetActorParameter(), SetBoolParameter(), SetColorParameter(), SetFloatParameter(), SetFloatRandParameter(), SetIntParameter(), SetVectorParameter(), SetVectorRandParameter(), and SetVectorUnitRandParameter().
PlayerLocations
TArray<FVector> UParticleSystemComponent::PlayerLocations private
Player locations computed before kicking off async task.
Safe to access from async task or game thread
Definition at line 875 of file ParticleSystemComponent.h.
Referenced by GetPlayerLocations().
PlayerLODDistanceFactor
TArray<float> UParticleSystemComponent::PlayerLODDistanceFactor private
PlayerLODDistanceFactor computed before kicking off async task.
Safe to access from async task or game thread
Definition at line 877 of file ParticleSystemComponent.h.
Referenced by GetPlayerLODDistanceFactor().
PoolingMethod
EPSCPoolMethod UParticleSystemComponent::PoolingMethod
If this PSC is pooling.
Definition at line 647 of file ParticleSystemComponent.h.
RandomStream
FRandomStream UParticleSystemComponent::RandomStream
Stream of random values to use with this component.
Definition at line 1315 of file ParticleSystemComponent.h.
ReleaseResourcesFence
class FRenderCommandFence* UParticleSystemComponent::ReleaseResourcesFence
Command fence used to shut down properly.
Definition at line 1307 of file ParticleSystemComponent.h.
ReplayClipIDNumber
int32 UParticleSystemComponent::ReplayClipIDNumber
Clip ID number we're either playing back or capturing to, depending on the value of ReplayState.
Definition at line 759 of file ParticleSystemComponent.h.
ReplayFrameIndex
int32 UParticleSystemComponent::ReplayFrameIndex
The current replay frame for playback.
Definition at line 762 of file ParticleSystemComponent.h.
ReplayState
TEnumAsByte<enum ParticleReplayState> UParticleSystemComponent::ReplayState
Current particle 'replay state'.
This setting controls whether we're currently simulating/rendering particles normally, or whether we should capture or playback particle replay data instead.
Definition at line 658 of file ParticleSystemComponent.h.
SavedAutoAttachRelativeLocation
FVector UParticleSystemComponent::SavedAutoAttachRelativeLocation private
Saved relative transform before auto attachement.
Used during detachment to restore the transform if we had automatically attached.
Definition at line 860 of file ParticleSystemComponent.h.
SavedAutoAttachRelativeRotation
FRotator UParticleSystemComponent::SavedAutoAttachRelativeRotation private
Definition at line 861 of file ParticleSystemComponent.h.
SavedAutoAttachRelativeScale3D
FVector UParticleSystemComponent::SavedAutoAttachRelativeScale3D private
Definition at line 862 of file ParticleSystemComponent.h.
SocketName
FName UParticleSystemComponent::SocketName = NAME_None
Definition at line 842 of file ParticleSystemComponent.h.
Referenced by SetAutoAttachmentParameters().
SourceIndex [1/3]
int32 UParticleSystemComponent::SourceIndex
Definition at line 986 of file ParticleSystemComponent.h.
SourceIndex [2/3]
float int32 UParticleSystemComponent::SourceIndex
Definition at line 1006 of file ParticleSystemComponent.h.
SourceIndex [3/3]
int32 UParticleSystemComponent::SourceIndex
Definition at line 1060 of file ParticleSystemComponent.h.
SourceMaterial
class UMaterialInterface* UParticleSystemComponent::SourceMaterial = NULL)
Definition at line 1491 of file ParticleSystemComponent.h.
Referenced by SetMaterialByName().
SpawnEvents
TArray<struct FParticleEventSpawnData> UParticleSystemComponent::SpawnEvents
The Spawn events that occurred in this PSysComp.
Definition at line 772 of file ParticleSystemComponent.h.
TargetIndex [1/3]
int32 UParticleSystemComponent::TargetIndex
Definition at line 1016 of file ParticleSystemComponent.h.
Referenced by UFUNCTION(), and UFUNCTION().
TargetIndex [2/3]
float int32 UParticleSystemComponent::TargetIndex
Definition at line 1036 of file ParticleSystemComponent.h.
TargetIndex [3/3]
int32 UParticleSystemComponent::TargetIndex
Definition at line 1099 of file ParticleSystemComponent.h.
TimeSinceLastForceUpdateTransform
float UParticleSystemComponent::TimeSinceLastForceUpdateTransform private
Tracks the time since the last forced UpdateTransform.
Definition at line 718 of file ParticleSystemComponent.h.
TimeSinceLastTick
uint32 UParticleSystemComponent::TimeSinceLastTick private
Time in ms since a tick was last performed; used with MinTimeBetweenTicks (on UParticleSystem) to control tick rate.
Definition at line 1338 of file ParticleSystemComponent.h.
TotalActiveParticles
int32 UParticleSystemComponent::TotalActiveParticles private
Info from async tick.
Definition at line 1334 of file ParticleSystemComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/ParticleSystemComponent.h