Unreal Engine 5.6 C++ API: FStaticMeshRenderData Class Reference
FStaticMeshRenderData Class Reference
FStaticMeshRenderData - All data needed to render a static mesh.
#include "StaticMeshResources.h"
Public Member Functions
FStaticMeshRenderData ()
Default constructor.
~FStaticMeshRenderData ()
void AllocateLODResources (int32 NumLODs)
Allocate LOD resources.
void BuildAreaWeighedSamplingData ()
void ComputeUVDensities ()
Update LOD-SECTION uv densities.
SIZE_T GetCPUAccessMemoryOverhead () const
Get the estimated memory overhead of buffers marked as NeedsCPUAccess.
const FStaticMeshLODResources * GetCurrentFirstLOD (int32 MinLODIdx) const
Return the current first LOD that can be used for rendering starting at MinLODIdx.
int32 GetCurrentFirstLODIdx (int32 MinLODIdx) const
Return the current first LODIdx that can be used.
int32 GetFirstValidLODIdx (int32 MinLODIdx) const
Return first valid LOD index starting at MinLODIdx.
int32 GetNumNonOptionalLODs () const
Count the number of LODs that not optional and guarantied to be installed.
int32 GetNumNonStreamingLODs () const
Count the number of LODs that are inlined and not streamable.
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) const
Compute the size of this resource.
bool HasNaniteFallbackMesh (EShaderPlatform ShaderPlatform) const
bool HasValidNaniteData () const
void InitializeRayTracingRepresentationFromRenderingLODs ()
void InitResources (ERHIFeatureLevel::Type InFeatureLevel, UStaticMesh *Owner)
Initialize the render resources.
bool IsInitialized () const
void ReleaseResources ()
Releases the render resources.
void ResolveSectionInfo (UStaticMesh *Owner)
Resolve all per-section settings.
void Serialize (FArchive &Ar, UStaticMesh *Owner, bool bCooked)
Serialization.
void SerializeInlineDataRepresentations (FArchive &Ar, UStaticMesh *Owner)
Serialize mesh build data which is inlined.
Data Fields
bool bHasNaniteFallbackMesh
bool bLODsShareStaticLighting
True if LODs share static lighting data.
FBoxSphereBounds Bounds
Bounds of the renderable mesh.
bool bReadyForStreaming
True if rhi resources are initialized.
uint8 CurrentFirstLODIdx
uint8 LODBiasModifier
FStaticMeshLODResourcesArray LODResources
Per-LOD resources.
FStaticMeshVertexFactoriesArray LODVertexFactories
TPimplPtr< Nanite::FResources > NaniteResourcesPtr
uint8 NumInlinedLODs
FStaticMeshRayTracingProxy * RayTracingProxy = nullptr
Ray tracing representation of this mesh, null if not present.
FPerPlatformFloat ScreenSize [8]
Screen size to switch LODs.
Private Attributes
bool bIsInitialized = false
Detailed Description
FStaticMeshRenderData - All data needed to render a static mesh.
Definition at line 773 of file StaticMeshResources.h.
Constructor & Destructor Documentation
FStaticMeshRenderData()
FStaticMeshRenderData::FStaticMeshRenderData ()
Default constructor.
~FStaticMeshRenderData()
FStaticMeshRenderData::~FStaticMeshRenderData ()
Member Function Documentation
AllocateLODResources()
void FStaticMeshRenderData::AllocateLODResources (int32 NumLODs)
Allocate LOD resources.
BuildAreaWeighedSamplingData()
void FStaticMeshRenderData::BuildAreaWeighedSamplingData ()
ComputeUVDensities()
void FStaticMeshRenderData::ComputeUVDensities ()
Update LOD-SECTION uv densities.
GetCPUAccessMemoryOverhead()
SIZE_T FStaticMeshRenderData::GetCPUAccessMemoryOverhead () const
Get the estimated memory overhead of buffers marked as NeedsCPUAccess.
GetCurrentFirstLOD()
const FStaticMeshLODResources * FStaticMeshRenderData::GetCurrentFirstLOD (int32 MinLODIdx) const inline
Return the current first LOD that can be used for rendering starting at MinLODIdx.
This takes into account the streaming status from CurrentFirstLODIdx, and MinLODIdx is expected to be UStaticMesh::MinLOD, which is platform specific.
Definition at line 932 of file StaticMeshResources.h.
References FORCEINLINE, GetCurrentFirstLODIdx(), and LODResources.
GetCurrentFirstLODIdx()
int32 FStaticMeshRenderData::GetCurrentFirstLODIdx (int32 MinLODIdx) const inline
Return the current first LODIdx that can be used.
Definition at line 922 of file StaticMeshResources.h.
References CurrentFirstLODIdx, FORCEINLINE, GetFirstValidLODIdx(), and FMath::Max.
Referenced by GetCurrentFirstLOD().
GetFirstValidLODIdx()
int32 FStaticMeshRenderData::GetFirstValidLODIdx (int32 MinLODIdx) const
Return first valid LOD index starting at MinLODIdx.
Referenced by GetCurrentFirstLODIdx().
GetNumNonOptionalLODs()
int32 FStaticMeshRenderData::GetNumNonOptionalLODs () const
Count the number of LODs that not optional and guarantied to be installed.
Starting from the last LOD and stopping at the first optional LOD.
GetNumNonStreamingLODs()
int32 FStaticMeshRenderData::GetNumNonStreamingLODs () const
Count the number of LODs that are inlined and not streamable.
Starting from the last LOD and stopping at the first non inlined LOD.
GetResourceSizeEx()
void FStaticMeshRenderData::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) const
Compute the size of this resource.
HasNaniteFallbackMesh()
bool FStaticMeshRenderData::HasNaniteFallbackMesh (EShaderPlatform ShaderPlatform) const
References ShaderPlatform.
HasValidNaniteData()
bool FStaticMeshRenderData::HasValidNaniteData () const
InitializeRayTracingRepresentationFromRenderingLODs()
void FStaticMeshRenderData::InitializeRayTracingRepresentationFromRenderingLODs ()
InitResources()
void FStaticMeshRenderData::InitResources (ERHIFeatureLevel::Type InFeatureLevel, UStaticMesh * Owner)
Initialize the render resources.
References Owner.
IsInitialized()
bool FStaticMeshRenderData::IsInitialized () const inline
Definition at line 803 of file StaticMeshResources.h.
References bIsInitialized.
ReleaseResources()
void FStaticMeshRenderData::ReleaseResources ()
Releases the render resources.
ResolveSectionInfo()
void FStaticMeshRenderData::ResolveSectionInfo (UStaticMesh * Owner)
Resolve all per-section settings.
References Owner.
Serialize()
void FStaticMeshRenderData::Serialize (FArchive & Ar, UStaticMesh * Owner, bool bCooked)
Serialization.
References Ar, and Owner.
SerializeInlineDataRepresentations()
void FStaticMeshRenderData::SerializeInlineDataRepresentations (FArchive & Ar, UStaticMesh * Owner)
Serialize mesh build data which is inlined.
References Ar, and Owner.
Field Documentation
bHasNaniteFallbackMesh
bool FStaticMeshRenderData::bHasNaniteFallbackMesh
Definition at line 815 of file StaticMeshResources.h.
bIsInitialized
bool FStaticMeshRenderData::bIsInitialized = false private
Definition at line 943 of file StaticMeshResources.h.
Referenced by IsInitialized().
bLODsShareStaticLighting
bool FStaticMeshRenderData::bLODsShareStaticLighting
True if LODs share static lighting data.
Definition at line 813 of file StaticMeshResources.h.
Bounds
FBoxSphereBounds FStaticMeshRenderData::Bounds
Bounds of the renderable mesh.
Definition at line 797 of file StaticMeshResources.h.
bReadyForStreaming
bool FStaticMeshRenderData::bReadyForStreaming
True if rhi resources are initialized.
Definition at line 818 of file StaticMeshResources.h.
CurrentFirstLODIdx
uint8 FStaticMeshRenderData::CurrentFirstLODIdx
Definition at line 822 of file StaticMeshResources.h.
Referenced by GetCurrentFirstLODIdx().
LODBiasModifier
uint8 FStaticMeshRenderData::LODBiasModifier
Definition at line 824 of file StaticMeshResources.h.
LODResources
FStaticMeshLODResourcesArray FStaticMeshRenderData::LODResources
Per-LOD resources.
For compatibility reasons, the FStaticMeshLODResources array are not referenced through TRefCountPtr. The LODResource still has a ref count of at least 1, see FStaticMeshLODResources() constructor.
Definition at line 785 of file StaticMeshResources.h.
Referenced by GetCurrentFirstLOD().
LODVertexFactories
FStaticMeshVertexFactoriesArray FStaticMeshRenderData::LODVertexFactories
Definition at line 786 of file StaticMeshResources.h.
NaniteResourcesPtr
TPimplPtr<Nanite::FResources> FStaticMeshRenderData::NaniteResourcesPtr
Definition at line 791 of file StaticMeshResources.h.
NumInlinedLODs
uint8 FStaticMeshRenderData::NumInlinedLODs
Definition at line 820 of file StaticMeshResources.h.
RayTracingProxy
FStaticMeshRayTracingProxy* FStaticMeshRenderData::RayTracingProxy = nullptr
Ray tracing representation of this mesh, null if not present.
Definition at line 794 of file StaticMeshResources.h.
ScreenSize
FPerPlatformFloat FStaticMeshRenderData::ScreenSize[8]
Screen size to switch LODs.
Definition at line 789 of file StaticMeshResources.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/StaticMeshResources.h