Unreal Engine 5.6 C++ API: UE::Geometry::FSimpleIntrinsicMesh Class Reference
UE::Geometry::FSimpleIntrinsicMesh Class Reference
FSimpleIntrinsicMesh extends FSimpleIntrinsicEdgeFlipMesh to support edge splits and triangle pokes in addition to edge flips.
#include "IntrinsicTriangulationMesh.h"
Public Types
using FEdge = FSimpleIntrinsicEdgeFlipMesh::FEdge
using FEdgeFlipInfo = FSimpleIntrinsicEdgeFlipMesh::FEdgeFlipInfo
using FEdgeSplitInfo = DynamicMeshInfo::FEdgeSplitInfo
using FPokeTriangleInfo = DynamicMeshInfo::FPokeTriangleInfo
typedef FSimpleIntrinsicEdgeFlipMesh MyBase
Public Types inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
using FEdge = FDynamicMesh3::FEdge
Public Member Functions
FSimpleIntrinsicMesh ()
FSimpleIntrinsicMesh (const FDynamicMesh3 &SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
FSimpleIntrinsicMesh (const FSimpleIntrinsicMesh &)=delete
DYNAMICMESH_API EMeshResult PokeTriangle (int32 TID, const FVector3d &BaryCoordinates, FPokeTriangleInfo &PokeInfo)
Insert a new vertex inside an intrinsic triangle, ie do a 1 to 3 triangle split.
DYNAMICMESH_API EMeshResult SplitEdge (int32 EdgeAB, FEdgeSplitInfo &SplitInfo, double SplitParameterT=0.5)
Split an intrinsic edge of the mesh by inserting a vertex.
Public Member Functions inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
FSimpleIntrinsicEdgeFlipMesh ()
DYNAMICMESH_API FSimpleIntrinsicEdgeFlipMesh (const FDynamicMesh3 &SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
FSimpleIntrinsicEdgeFlipMesh (const FSimpleIntrinsicEdgeFlipMesh &)=delete
bool AreSameOrientation (int32 EID) const
DYNAMICMESH_API void Clear ()
Discard all data.
DYNAMICMESH_API double EdgeCotanWeight (int32 EID) const
return 1/2 (cot(alpha_{ij}) + cot(beta_{ij})) where alpha_{ij} and beta_{ij} are the to interior angles opposite the specified edge, EID.
int32 EdgeCount () const
FRefCountVector::IndexEnumerable EdgeIndicesItr () const
DYNAMICMESH_API FVector2d EdgeOpposingAngles (int32 EID) const
return FVector2(alpha_{ij} , beta_{ij}) where alpha_{ij} and beta_{ij} are the two interior angles opposite the specified edge, EID.
DYNAMICMESH_API EMeshResult FlipEdge (int32 EID, FEdgeFlipInfo &EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
FEdge GetEdge (int32 EdgeID) const
double GetEdgeLength (int32 EID) const
DYNAMICMESH_API FIndex2i GetEdgeOpposingV (int32 EID) const
FIndex2i GetEdgeT (int32 EdgeID) const
FIndex2i GetEdgeV (int32 EdgeID) const
FIndex3i GetTriangle (int32 TriangleID) const
const FIndex3i & GetTriangleRef (int TriangleID) const
FVector3d GetTriEdgeLengths (const int32 TID) const
FIndex3i GetTriEdges (int32 TriangleID) const
double GetTriInternalAngleR (const int32 TID, const int32 IndexOf) const
FVector3d GetVertex (int32 VertexID) const
int32 GetVtxEdgeCount (int32 VID) const
bool IsBoundaryEdge (int32 EdgeID) const
bool IsBoundaryVertex (int32 VertexID) const
bool IsEdge (int32 EdgeID) const
bool IsTriangle (int32 TriangleID) const
bool IsVertex (int32 VertexID) const
int32 MaxEdgeID () const
int32 MaxTriangleID () const
int32 MaxVertexID () const
template<typename Vector3Type>
Vector3Type Permute (int32 Index, const Vector3Type &Src) const
cyclic permutation of the src vector such that the 'Index' entry in the src is the first entry in the result NB: Index must be 0, 1, or 2.
DYNAMICMESH_API void Reset (const FDynamicMesh3 &SrcMesh)
Reset the mesh to an ID-matching deep copy the basic mesh topology (but no attributes or groups)
int32 TriangleCount () const
FRefCountVector::IndexEnumerable TriangleIndicesItr () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int32 VID) const
Static Public Attributes
static constexpr int InvalidID = IndexConstants::InvalidID
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Static Public Attributes inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
static constexpr int InvalidID = IndexConstants::InvalidID
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Protected Member Functions
int32 AddEdgeInternal (int32 vA, int32 vB, int32 tA, int32 tB=InvalidID)
add new edge to the mesh topology, does not update any of the intrinsic quantities
int32 AddTriangleInternal (int32 a, int32 b, int32 c, int32 e0, int32 e1, int32 e2)
add new triangle to the mesh topology, does not update any of the intrinsic quantities
void AllocateEdgesList (int32 VertexID)
allocate, or clear existing edge list for specified vertex
int32 AppendVertex (const FVector3d &vPos)
add new vertex to the mesh topology, does not update any of the intrinsic quantities
DYNAMICMESH_API EMeshResult PokeTriangleTopology (int32 TID, FPokeTriangleInfo &PokeInfo)
Updates the mesh connectivity by adding a new vertex at the vertex-averaged location.
DYNAMICMESH_API EMeshResult SplitEdgeTopology (int32 EdgeAB, FEdgeSplitInfo &SplitInfo)
Updates the mesh connectivity by adding a new vertex at the vertex-averaged location.
Protected Member Functions inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
DYNAMICMESH_API FVector3d ComputeTriInternalAnglesR (const int32 TID) const
computes the angles based on the edge lengths, so must have valid EdgeLengths for this tri before calling.
DYNAMICMESH_API EMeshResult FlipEdgeTopology (int32 eab, FEdgeFlipInfo &FlipInfo)
update the mesh topology (e.g.
FVector3d GetEdgeLengthTriple (const FIndex3i &EIDs) const
DYNAMICMESH_API double GetOpposingVerticesDistance (int32 EID) const
DYNAMICMESH_API FIndex2i GetOrientedEdgeV (int32 EID, int32 TID) const
DYNAMICMESH_API int32 ReplaceEdgeTriangle (int32 eID, int32 tOld, int32 tNew)
replace tOld with tNew in an existing edge
int32 ReplaceTriangleEdge (int32 tID, int32 eOld, int32 eNew)
replace eOld with eNew in and existing triangle
void SetEdgeTrianglesInternal (int32 EdgeID, int32 t0, int32 t1)
update the existing edge to reference triangles t0 and t1
void SetEdgeVerticesInternal (int32 EdgeID, int32 a, int32 b)
update the existing edge to reference vertices 'a' and 'b'.
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
const int32 AddOneModThree [3] = { 1, 2, 0 }
const int32 AddTwoModThree [3] = { 2, 0, 1 }
TDynamicVector< double > EdgeLengths
FRefCountVector EdgeRefCounts {}
TDynamicVector< FEdge > Edges
TDynamicVector< FVector3d > InternalAngles
TDynamicVector< FIndex3i > TriangleEdges
FRefCountVector TriangleRefCounts {}
TDynamicVector< FIndex3i > Triangles
FSmallListSet VertexEdgeLists
FRefCountVector VertexRefCounts {}
TDynamicVector< FVector3d > Vertices {}
Detailed Description
FSimpleIntrinsicMesh extends FSimpleIntrinsicEdgeFlipMesh to support edge splits and triangle pokes in addition to edge flips.
The surface mesh vertices will be a subset of the intrinsic mesh vertex set.
This is intended as a base class for more sophisticated intrinsic mesh classes, as it does not explicitly track the topology changes relative to the original surface mesh. For example it does not record the locations on the surface mesh of any new intrinsic vertices or the locations of intrinsic mesh edge intersections with the surface mesh edges.
FIntrinsicMesh and FIntrinsicTriangulation are derived from this class and each maintain their own connection with the surface mesh ("normal coordinates" or "signpost data") that can track these surface mesh locations and can be used to reconstruct paths (e.g. intrinsic edges) on the surface mesh.
Definition at line 454 of file IntrinsicTriangulationMesh.h.
Member Typedef Documentation
FEdge
using UE::Geometry::FSimpleIntrinsicMesh::FEdge = FSimpleIntrinsicEdgeFlipMesh::FEdge
Definition at line 458 of file IntrinsicTriangulationMesh.h.
FEdgeFlipInfo
using UE::Geometry::FSimpleIntrinsicMesh::FEdgeFlipInfo = FSimpleIntrinsicEdgeFlipMesh::FEdgeFlipInfo
Definition at line 459 of file IntrinsicTriangulationMesh.h.
FEdgeSplitInfo
using UE::Geometry::FSimpleIntrinsicMesh::FEdgeSplitInfo = DynamicMeshInfo::FEdgeSplitInfo
Definition at line 461 of file IntrinsicTriangulationMesh.h.
FPokeTriangleInfo
using UE::Geometry::FSimpleIntrinsicMesh::FPokeTriangleInfo = DynamicMeshInfo::FPokeTriangleInfo
Definition at line 460 of file IntrinsicTriangulationMesh.h.
MyBase
typedef FSimpleIntrinsicEdgeFlipMesh UE::Geometry::FSimpleIntrinsicMesh::MyBase
Definition at line 457 of file IntrinsicTriangulationMesh.h.
Constructor & Destructor Documentation
FSimpleIntrinsicMesh() [1/3]
UE::Geometry::FSimpleIntrinsicMesh::FSimpleIntrinsicMesh () inline
Definition at line 466 of file IntrinsicTriangulationMesh.h.
Referenced by FSimpleIntrinsicMesh().
FSimpleIntrinsicMesh() [2/3]
UE::Geometry::FSimpleIntrinsicMesh::FSimpleIntrinsicMesh (const FDynamicMesh3 & SrcMesh) inline
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
Definition at line 469 of file IntrinsicTriangulationMesh.h.
FSimpleIntrinsicMesh() [3/3]
UE::Geometry::FSimpleIntrinsicMesh::FSimpleIntrinsicMesh (const FSimpleIntrinsicMesh &) delete
References FSimpleIntrinsicMesh().
Member Function Documentation
AddEdgeInternal()
int32 UE::Geometry::FSimpleIntrinsicMesh::AddEdgeInternal (int32 vA, int32 vB, int32 tA, int32 tB = InvalidID) inline protected
add new edge to the mesh topology, does not update any of the intrinsic quantities
Definition at line 535 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeRefCounts, UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Edges, InvalidID, and UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VertexEdgeLists.
AddTriangleInternal()
int32 UE::Geometry::FSimpleIntrinsicMesh::AddTriangleInternal (int32 a, int32 b, int32 c, int32 e0, int32 e1, int32 e2) inline protected
add new triangle to the mesh topology, does not update any of the intrinsic quantities
Definition at line 551 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::TriangleEdges, UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::TriangleRefCounts, and UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Triangles.
AllocateEdgesList()
void UE::Geometry::FSimpleIntrinsicMesh::AllocateEdgesList (int32 VertexID) inline protected
allocate, or clear existing edge list for specified vertex
Definition at line 516 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VertexEdgeLists.
Referenced by AppendVertex().
AppendVertex()
int32 UE::Geometry::FSimpleIntrinsicMesh::AppendVertex (const FVector3d & vPos) inline protected
add new vertex to the mesh topology, does not update any of the intrinsic quantities
Definition at line 526 of file IntrinsicTriangulationMesh.h.
References AllocateEdgesList(), UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VertexRefCounts, and UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Vertices.
PokeTriangle()
DYNAMICMESH_API EMeshResult UE::Geometry::FSimpleIntrinsicMesh::PokeTriangle (int32 TID, const FVector3d & BaryCoordinates, FPokeTriangleInfo & PokeInfo)
Insert a new vertex inside an intrinsic triangle, ie do a 1 to 3 triangle split.
Parameters
TID - index of triangle to poke
BaryCoordinates - barycentric coordinates of poke position
PokeInfo - returned information about new and modified mesh elements
Returns
Ok on success, or enum value indicates why operation cannot be applied. Mesh remains unmodified on error.
References UE_API.
PokeTriangleTopology()
DYNAMICMESH_API EMeshResult UE::Geometry::FSimpleIntrinsicMesh::PokeTriangleTopology (int32 TID, FPokeTriangleInfo & PokeInfo) protected
Updates the mesh connectivity by adding a new vertex at the vertex-averaged location.
Note: this does not update any of the intrinsic lengths, positions, angles, etc. those quantities must be updated after. See PokeTriangle()
References UE_API.
SplitEdge()
DYNAMICMESH_API EMeshResult UE::Geometry::FSimpleIntrinsicMesh::SplitEdge (int32 EdgeAB, FEdgeSplitInfo & SplitInfo, double SplitParameterT = 0.5)
Split an intrinsic edge of the mesh by inserting a vertex.
This creates a new triangle on either side of the edge (ie a 2-4 split). If the original edge had vertices [a,b], with triangles t0=[a,b,c] and t1=[b,a,d], then the split inserts new vertex f. After the split t0=[a,f,c] and t1=[f,a,d], and we have t2=[f,b,c] and t3=[f,d,b] (it's best to draw it out on paper...) SplitInfo.OriginalTriangles = {t0, t1} and SplitInfo.NewTriangles = {t2, t3}
Parameters
EdgeAB - index of the edge to be split
SplitInfo - returned information about new and modified mesh elements
SplitParameterT - defines the position along the edge that we split at, must be between 0 and 1, and is assumed to be based on the order of vertices in t0
Returns
Ok on success, or enum value indicates why operation cannot be applied. Mesh remains unmodified on error.
References UE_API.
SplitEdgeTopology()
DYNAMICMESH_API EMeshResult UE::Geometry::FSimpleIntrinsicMesh::SplitEdgeTopology (int32 EdgeAB, FEdgeSplitInfo & SplitInfo) protected
Updates the mesh connectivity by adding a new vertex at the vertex-averaged location.
Note: this does not update any of the intrinsic lengths, positions, angles, etc. those quantities must be updated after. See SplitEdge()
References UE_API.
Field Documentation
InvalidID
int UE::Geometry::FSimpleIntrinsicMesh::InvalidID = IndexConstants::InvalidID static constexpr
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Definition at line 464 of file IntrinsicTriangulationMesh.h.
Referenced by AddEdgeInternal().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/IntrinsicTriangulationMesh.h