Unreal Engine 5.6 C++ API: FWorldPartitionLevelHelper Class Reference
FWorldPartitionLevelHelper Class Reference
#include "WorldPartitionLevelHelper.h"
Data Structures
class FActorPropertyOverridesAnnotation
struct FLoadActorsParams
struct FLoadedPropertyOverrides
struct FPackageReference
struct FPackageReferencer
Public Member Functions
UE_DEPRECATED (5.4, "LoadActors is deprecated, LoadActors with FLoadActorsParams should be used instead.") static bool LoadActors(UWorld *InOuterWorld
Static Public Member Functions
static FString AddActorContainerID (const FActorContainerID &InContainerID, const FString &InActorName)
static FString AddActorContainerIDToSubPathString (const FActorContainerID &InContainerID, const FString &InSubPathString)
static ULevel * CreateEmptyLevelForRuntimeCell (const UWorldPartitionRuntimeCell *Cell, const UWorld *InWorld, const FString &InWorldAssetName, UPackage *DestPackage=nullptr)
static FWorldPartitionLevelHelper & Get ()
static bool LoadActors (const FLoadActorsParams &InParams)
static void MoveExternalActorsToLevel (const TArray< FWorldPartitionRuntimeCellObjectMapping > &InChildPackages, ULevel *InLevel, TArray< UPackage * > &OutModifiedPackages)
static FSoftObjectPath RemapActorPath (const FActorContainerID &InContainerID, const FString &SourceWorldName, const FSoftObjectPath &InActorPath)
static void RemapLevelSoftObjectPaths (ULevel *InLevel, UWorldPartition *InWorldPartition)
Data Fields
ULevel TArrayView< FWorldPartitionRuntimeCellObjectMapping > FPackageReferencer TFunction< void(bool)> bool bInLoadAsync
ULevel TArrayView< FWorldPartitionRuntimeCellObjectMapping > InActorPackages
ULevel TArrayView< FWorldPartitionRuntimeCellObjectMapping > FPackageReferencer TFunction< void(bool)> InCompletionCallback
ULevel * InDestLevel
ULevel TArrayView< FWorldPartitionRuntimeCellObjectMapping > FPackageReferencer TFunction< void(bool)> bool FLinkerInstancingContext InInstancingContext
ULevel TArrayView< FWorldPartitionRuntimeCellObjectMapping > FPackageReferencer & InPackageReferencer
Private Member Functions
FWorldPartitionLevelHelper ()
void AddReference (UPackage *InPackage, FPackageReferencer *InReferencer)
void PreGarbageCollect ()
void RemoveReferences (FPackageReferencer *InReferencer)
Static Private Member Functions
static void ApplyConstructionScriptPropertyOverridesFromAnnotation (AActor *InActor)
static UWorld::InitializationValues GetWorldInitializationValues ()
static bool LoadActors (FLoadActorsParams &&InParams)
static bool LoadActorsInternal (FLoadActorsParams &&InParams, FLoadedPropertyOverrides &&InLoadedPropertyOverrides)
static bool LoadActorsWithPropertyOverridesInternal (FLoadActorsParams &&InParams)
static bool RemapLevelCellPathInContentBundle (ULevel *Level, const class FContentBundleEditor *ContentBundleEditor, const UWorldPartitionRuntimeCell *Cell)
static void SetForcePackageTrashingAtCleanup (ULevel *Level, bool bForcePackageTrashingAtCleanup)
Private Attributes
TMap< FName, FPackageReference > PackageReferences
TSet< TWeakObjectPtr< UPackage > > PreGCPackagesToUnload
Static Private Attributes
static FUObjectAnnotationSparse< FActorPropertyOverridesAnnotation, true > ActorPropertyOverridesAnnotation
Friends
class FContentBundleEditor
struct FPackageReferencer
class UWorldPartitionLevelStreamingDynamic
class UWorldPartitionRuntimeLevelStreamingCell
class UWorldPartitionSubsystem
Detailed Description
Definition at line 22 of file WorldPartitionLevelHelper.h.
Constructor & Destructor Documentation
FWorldPartitionLevelHelper()
FWorldPartitionLevelHelper::FWorldPartitionLevelHelper () private
Referenced by Get().
Member Function Documentation
AddActorContainerID()
FString FWorldPartitionLevelHelper::AddActorContainerID (const FActorContainerID & InContainerID, const FString & InActorName) static
AddActorContainerIDToSubPathString()
FString FWorldPartitionLevelHelper::AddActorContainerIDToSubPathString (const FActorContainerID & InContainerID, const FString & InSubPathString) static
AddReference()
void FWorldPartitionLevelHelper::AddReference (UPackage * InPackage, FPackageReferencer * InReferencer) private
ApplyConstructionScriptPropertyOverridesFromAnnotation()
void FWorldPartitionLevelHelper::ApplyConstructionScriptPropertyOverridesFromAnnotation (AActor * InActor) static private
CreateEmptyLevelForRuntimeCell()
ULevel * FWorldPartitionLevelHelper::CreateEmptyLevelForRuntimeCell (const UWorldPartitionRuntimeCell * Cell, const UWorld * InWorld, const FString & InWorldAssetName, UPackage * DestPackage = nullptr) static
References Cell.
Get()
FWorldPartitionLevelHelper & FWorldPartitionLevelHelper::Get () static
References FWorldPartitionLevelHelper().
GetWorldInitializationValues()
UWorld::InitializationValues FWorldPartitionLevelHelper::GetWorldInitializationValues () static private
LoadActors() [1/2]
bool FWorldPartitionLevelHelper::LoadActors (const FLoadActorsParams & InParams) static
LoadActors() [2/2]
bool FWorldPartitionLevelHelper::LoadActors (FLoadActorsParams && InParams) static private
LoadActorsInternal()
bool FWorldPartitionLevelHelper::LoadActorsInternal (FLoadActorsParams && InParams, FLoadedPropertyOverrides && InLoadedPropertyOverrides) static private
LoadActorsWithPropertyOverridesInternal()
bool FWorldPartitionLevelHelper::LoadActorsWithPropertyOverridesInternal (FLoadActorsParams && InParams) static private
MoveExternalActorsToLevel()
void FWorldPartitionLevelHelper::MoveExternalActorsToLevel (const TArray< FWorldPartitionRuntimeCellObjectMapping > & InChildPackages, ULevel * InLevel, TArray< UPackage * > & OutModifiedPackages) static
PreGarbageCollect()
void FWorldPartitionLevelHelper::PreGarbageCollect () private
RemapActorPath()
FSoftObjectPath FWorldPartitionLevelHelper::RemapActorPath (const FActorContainerID & InContainerID, const FString & SourceWorldName, const FSoftObjectPath & InActorPath) static
RemapLevelCellPathInContentBundle()
bool FWorldPartitionLevelHelper::RemapLevelCellPathInContentBundle (ULevel * Level, const class FContentBundleEditor * ContentBundleEditor, const UWorldPartitionRuntimeCell * Cell) static private
References Cell, and FContentBundleEditor.
RemapLevelSoftObjectPaths()
void FWorldPartitionLevelHelper::RemapLevelSoftObjectPaths (ULevel * InLevel, UWorldPartition * InWorldPartition) static
RemoveReferences()
void FWorldPartitionLevelHelper::RemoveReferences (FPackageReferencer * InReferencer) private
SetForcePackageTrashingAtCleanup()
void FWorldPartitionLevelHelper::SetForcePackageTrashingAtCleanup (ULevel * Level, bool bForcePackageTrashingAtCleanup) static private
UE_DEPRECATED()
FWorldPartitionLevelHelper::UE_DEPRECATED (5. 4, "LoadActors is deprecated, LoadActors with FLoadActorsParams should be used instead.")
Friends And Related Symbol Documentation
FContentBundleEditor
friend class FContentBundleEditor friend
Definition at line 94 of file WorldPartitionLevelHelper.h.
References FContentBundleEditor.
Referenced by FContentBundleEditor, and RemapLevelCellPathInContentBundle().
FPackageReferencer
friend struct FPackageReferencer friend
Definition at line 112 of file WorldPartitionLevelHelper.h.
UWorldPartitionLevelStreamingDynamic
friend class UWorldPartitionLevelStreamingDynamic friend
Definition at line 120 of file WorldPartitionLevelHelper.h.
References UWorldPartitionLevelStreamingDynamic.
Referenced by UWorldPartitionLevelStreamingDynamic.
UWorldPartitionRuntimeLevelStreamingCell
friend class UWorldPartitionRuntimeLevelStreamingCell friend
Definition at line 122 of file WorldPartitionLevelHelper.h.
References UWorldPartitionRuntimeLevelStreamingCell.
Referenced by UWorldPartitionRuntimeLevelStreamingCell.
UWorldPartitionSubsystem
friend class UWorldPartitionSubsystem friend
Definition at line 121 of file WorldPartitionLevelHelper.h.
References UWorldPartitionSubsystem.
Referenced by UWorldPartitionSubsystem.
Field Documentation
ActorPropertyOverridesAnnotation
FUObjectAnnotationSparse<FActorPropertyOverridesAnnotation, true> FWorldPartitionLevelHelper::ActorPropertyOverridesAnnotation static private
Definition at line 139 of file WorldPartitionLevelHelper.h.
bInLoadAsync
ULevel TArrayView<FWorldPartitionRuntimeCellObjectMapping> FPackageReferencer TFunction<void(bool)> bool FWorldPartitionLevelHelper::bInLoadAsync
Definition at line 45 of file WorldPartitionLevelHelper.h.
Referenced by FWorldPartitionLevelHelper::FLoadActorsParams::SetLoadAsync().
InActorPackages
ULevel TArrayView<FWorldPartitionRuntimeCellObjectMapping> FWorldPartitionLevelHelper::InActorPackages
Definition at line 45 of file WorldPartitionLevelHelper.h.
Referenced by FWorldPartitionLevelHelper::FLoadActorsParams::SetActorPackages().
InCompletionCallback
ULevel TArrayView<FWorldPartitionRuntimeCellObjectMapping> FPackageReferencer TFunction<void(bool)> FWorldPartitionLevelHelper::InCompletionCallback
Definition at line 45 of file WorldPartitionLevelHelper.h.
Referenced by FWorldPartitionLevelHelper::FLoadActorsParams::SetCompletionCallback().
InDestLevel
ULevel* FWorldPartitionLevelHelper::InDestLevel
Definition at line 45 of file WorldPartitionLevelHelper.h.
Referenced by FWorldPartitionLevelHelper::FLoadActorsParams::SetDestLevel().
InInstancingContext
ULevel TArrayView<FWorldPartitionRuntimeCellObjectMapping> FPackageReferencer TFunction<void(bool)> bool FLinkerInstancingContext FWorldPartitionLevelHelper::InInstancingContext
Definition at line 45 of file WorldPartitionLevelHelper.h.
Referenced by FWorldPartitionLevelHelper::FLoadActorsParams::SetInstancingContext().
InPackageReferencer
ULevel TArrayView<FWorldPartitionRuntimeCellObjectMapping> FPackageReferencer& FWorldPartitionLevelHelper::InPackageReferencer
Definition at line 45 of file WorldPartitionLevelHelper.h.
Referenced by FWorldPartitionLevelHelper::FLoadActorsParams::SetPackageReferencer().
PackageReferences
TMap<FName, FPackageReference> FWorldPartitionLevelHelper::PackageReferences private
Definition at line 114 of file WorldPartitionLevelHelper.h.
PreGCPackagesToUnload
TSet<TWeakObjectPtr<UPackage> > FWorldPartitionLevelHelper::PreGCPackagesToUnload private
Definition at line 116 of file WorldPartitionLevelHelper.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionLevelHelper.h