Unreal Engine 5.6 C++ API: FAutoConsoleObject Class Reference
FAutoConsoleObject Class Reference
Base class for autoregistering console commands.
#include "IConsoleManager.h"
Public Member Functions
virtual ~FAutoConsoleObject ()
Destructor, removes the console object.
FORCEINLINE IConsoleVariable * AsVariable ()
returns the contained console object as an IConsoleVariable
FORCEINLINE const IConsoleVariable * AsVariable () const
returns the contained console object as an IConsoleVariable
Static Public Member Functions
static TArray< const FAutoConsoleObject * > & AccessDesktopShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessGeneralShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessMobileShaderChangeCvars ()
Protected Member Functions
FAutoConsoleObject (IConsoleObject *InTarget)
Constructor, saves the argument for future removal from the console variable system.
Private Attributes
IConsoleObject * Target
Contained console object, cannot be 0.
Detailed Description
Base class for autoregistering console commands.
Definition at line 1319 of file IConsoleManager.h.
Constructor & Destructor Documentation
FAutoConsoleObject()
FAutoConsoleObject::FAutoConsoleObject (IConsoleObject * InTarget) inline protected
Constructor, saves the argument for future removal from the console variable system.
Definition at line 1323 of file IConsoleManager.h.
References AccessDesktopShaderChangeCvars(), AccessGeneralShaderChangeCvars(), AccessMobileShaderChangeCvars(), check, ECVF_DesktopShaderChange, ECVF_GeneralShaderChange, ECVF_MobileShaderChange, and Target.
Referenced by FAutoConsoleCommand::FAutoConsoleCommand(), FAutoConsoleCommand::FAutoConsoleCommand(), FAutoConsoleCommand::FAutoConsoleCommand(), FAutoConsoleCommand::FAutoConsoleCommand(), FAutoConsoleCommand::FAutoConsoleCommand(), FAutoConsoleCommand::FAutoConsoleCommand(), FAutoConsoleCommandWithArgsAndOutputDevice::FAutoConsoleCommandWithArgsAndOutputDevice(), FAutoConsoleCommandWithOutputDevice::FAutoConsoleCommandWithOutputDevice(), FAutoConsoleCommandWithWorld::FAutoConsoleCommandWithWorld(), FAutoConsoleCommandWithWorldAndArgs::FAutoConsoleCommandWithWorldAndArgs(), FAutoConsoleCommandWithWorldArgsAndOutputDevice::FAutoConsoleCommandWithWorldArgsAndOutputDevice(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), and TAutoConsoleVariable< T >::TAutoConsoleVariable().
~FAutoConsoleObject()
virtual FAutoConsoleObject::~FAutoConsoleObject () inline virtual
Destructor, removes the console object.
Definition at line 1342 of file IConsoleManager.h.
References IConsoleManager::Get(), Target, and IConsoleManager::UnregisterConsoleObject().
Member Function Documentation
AccessDesktopShaderChangeCvars()
TArray< const FAutoConsoleObject * > & FAutoConsoleObject::AccessDesktopShaderChangeCvars () static
Referenced by FAutoConsoleObject().
AccessGeneralShaderChangeCvars()
TArray< const FAutoConsoleObject * > & FAutoConsoleObject::AccessGeneralShaderChangeCvars () static
Referenced by FAutoConsoleObject().
AccessMobileShaderChangeCvars()
TArray< const FAutoConsoleObject * > & FAutoConsoleObject::AccessMobileShaderChangeCvars () static
Referenced by FAutoConsoleObject().
AsVariable() [1/2]
FORCEINLINE IConsoleVariable * FAutoConsoleObject::AsVariable () inline
returns the contained console object as an IConsoleVariable
Definition at line 1352 of file IConsoleManager.h.
References checkSlow, FORCEINLINE, and Target.
Referenced by FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), TAutoConsoleVariable< T >::TAutoConsoleVariable(), TAutoConsoleVariable< T >::TAutoConsoleVariable(), FAutoConsoleVariable::operator*(), FAutoConsoleVariable::operator*(), FAutoConsoleVariableRef::operator*(), FAutoConsoleVariableRef::operator*(), TAutoConsoleVariable< T >::operator*(), TAutoConsoleVariable< T >::operator*(), FAutoConsoleVariable::operator->(), FAutoConsoleVariable::operator->(), FAutoConsoleVariableRef::operator->(), FAutoConsoleVariableRef::operator->(), TAutoConsoleVariable< T >::operator->(), and TAutoConsoleVariable< T >::operator->().
AsVariable() [2/2]
FORCEINLINE const IConsoleVariable * FAutoConsoleObject::AsVariable () const inline
returns the contained console object as an IConsoleVariable
Definition at line 1358 of file IConsoleManager.h.
References checkSlow, FORCEINLINE, and Target.
Field Documentation
Target
IConsoleObject* FAutoConsoleObject::Target private
Contained console object, cannot be 0.
Definition at line 1366 of file IConsoleManager.h.
Referenced by FAutoConsoleObject(), ~FAutoConsoleObject(), AsVariable(), and AsVariable().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h