Unreal Engine 5.6 C++ API: UE::Geometry::FWorldRenderCapture Class Reference
UE::Geometry::FWorldRenderCapture Class Reference
FWorldRenderCapture captures a rendering of a set of Actors in a World from a specific viewpoint.
#include "WorldRenderCapture.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FWorldRenderCapture ()=default
FWorldRenderCapture (const FWorldRenderCapture &)=default
FWorldRenderCapture (FWorldRenderCapture &&) noexcept=default
MODELINGCOMPONENTS_API PRAGMA_ENABLE_DEPRECATION_WARNINGS ~FWorldRenderCapture ()
MODELINGCOMPONENTS_API bool CaptureFromPosition (ERenderCaptureType CaptureType, const FFrame3d &ViewFrame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter &ResultImageOut, const FRenderCaptureConfig &Config={})
Capture the desired buffer type CaptureType with the given view/camera parameters.
MODELINGCOMPONENTS_API FSphere ComputeContainingRenderSphere (float HorzFOVDegrees, float SafetyBoundsScale=1.25f) const
Compute a sphere where, if the camera is on the sphere pointed at the center, then the Visible Actors will be fully visible (ie a square capture will not have any clipping), for the given Field of View.
const FImageDimensions & GetDimensions () const
FBoxSphereBounds GetVisibleActorBounds () const
Get bounding-box of the Visible actors.
FWorldRenderCapture & operator= (const FWorldRenderCapture &)=default
FWorldRenderCapture & operator= (FWorldRenderCapture &&) noexcept=default
MODELINGCOMPONENTS_API void SetDimensions (const FImageDimensions &Dimensions)
Set desired pixel dimensions of the rendered target image.
MODELINGCOMPONENTS_API void SetEnableWriteDebugImage (bool bEnable, int32 ImageCounter=-1, FString FolderName=FString())
Enable debug image write.
MODELINGCOMPONENTS_API void SetVisibleActors (const TArray< AActor * > &Actors)
Set the set of Actors in the target World that should be included in the Rendering.
MODELINGCOMPONENTS_API void SetVisibleActorsAndComponents (const TArray< AActor * > &VisibleActors, const TArray< UActorComponent * > &VisibleComponents)
Set the set of Actors and Components in the target World that should be included in the Rendering.
MODELINGCOMPONENTS_API void SetVisibleComponents (const TArray< UActorComponent * > &Components)
Set the set of Components in the target World that should be included in the Rendering.
MODELINGCOMPONENTS_API void SetWorld (UWorld *World)
Set the target World.
MODELINGCOMPONENTS_API void Shutdown ()
Explicitly release any allocated textures or other data structres.
UE_DEPRECATED (5.4, "Please use GetRenderCaptureViewMatrices instead") const FViewMatrices &GetLastCaptureViewMatrices() const
Protected Member Functions
MODELINGCOMPONENTS_API bool CaptureBufferVisualizationFromPosition (const FName &VisualizationMode, const FFrame3d &Frame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter &ResultImageOut, const FRenderCaptureConfig &Config={})
The following values for VisualizationMode are supported: BaseColor, Metallic, Roughness, Specular, WorldNormal, Opacity, SubsurfaceColor, PreTonemapHDRColor.
MODELINGCOMPONENTS_API bool CaptureDeviceDepthFromPosition (const FFrame3d &Frame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter &ResultImageOut, const FRenderCaptureConfig &Config={})
Depth is a special case and uses different code than capture of color/property channels.
MODELINGCOMPONENTS_API bool CaptureMRSFromPosition (const FFrame3d &Frame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter &ResultImageOut, const FRenderCaptureConfig &Config={})
Combined Metallic/Roughness/Specular uses a custom postprocess material.
MODELINGCOMPONENTS_API UTextureRenderTarget2D * GetDepthRenderTexture ()
MODELINGCOMPONENTS_API UTextureRenderTarget2D * GetRenderTexture (bool bLinear)
UE_DEPRECATED (5.4, "Please use CaptureBufferVisualizationFromPosition with VisualizationMode=PreTonemapHDRColor instead") MODELINGCOMPONENTS_API bool CaptureEmissiveFromPosition(const FFrame3d &Frame
Emissive is a special case and uses different code than capture of color/property channels.
UE_DEPRECATED (5.4, "Please use GetRenderCaptureViewMatrices instead") FViewMatrices LastCaptureViewMatrices
MODELINGCOMPONENTS_API void WriteDebugImage (const FImageAdapter &ResultImageOut, const FString &ImageTypeName)
Protected Attributes
bool bWriteDebugImage = false
double double FImageAdapter const FRenderCaptureConfig & Config = {})
int32 DebugImageCounter = -1
FString DebugImageFolderName = TEXT("WorldRenderCapture")
UTextureRenderTarget2D * DepthRenderTexture = nullptr
FImageDimensions Dimensions = FImageDimensions(128, 128)
UTextureRenderTarget2D * GammaRenderTexture = nullptr
double HorzFOVDegrees
UTextureRenderTarget2D * LinearRenderTexture = nullptr
double double NearPlaneDist
TArray< FLinearColor > ReadImageBuffer
FImageDimensions RenderTextureDimensions
double double FImageAdapter & ResultImageOut
FBoxSphereBounds VisibleBounds
TSet< FPrimitiveComponentId > VisiblePrimitives
UWorld * World = nullptr
Detailed Description
FWorldRenderCapture captures a rendering of a set of Actors in a World from a specific viewpoint.
Various types of rendering are supported, as defined by ERenderCaptureType. Currently rendering an entire World, ie without an explicit list of Actors or Components, is not supported.
Definition at line 216 of file WorldRenderCapture.h.
Constructor & Destructor Documentation
FWorldRenderCapture() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FWorldRenderCapture::FWorldRenderCapture () default
Referenced by FWorldRenderCapture(), FWorldRenderCapture(), ~FWorldRenderCapture(), operator=(), and operator=().
FWorldRenderCapture() [2/3]
UE::Geometry::FWorldRenderCapture::FWorldRenderCapture (const FWorldRenderCapture &) default
References FWorldRenderCapture().
FWorldRenderCapture() [3/3]
UE::Geometry::FWorldRenderCapture::FWorldRenderCapture (FWorldRenderCapture &&) default noexcept
References FWorldRenderCapture().
~FWorldRenderCapture()
MODELINGCOMPONENTS_API PRAGMA_ENABLE_DEPRECATION_WARNINGS UE::Geometry::FWorldRenderCapture::~FWorldRenderCapture ()
References FWorldRenderCapture().
Member Function Documentation
CaptureBufferVisualizationFromPosition()
MODELINGCOMPONENTS_API bool UE::Geometry::FWorldRenderCapture::CaptureBufferVisualizationFromPosition (const FName & VisualizationMode, const FFrame3d & Frame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter & ResultImageOut, const FRenderCaptureConfig & Config = {}) protected
The following values for VisualizationMode are supported: BaseColor, Metallic, Roughness, Specular, WorldNormal, Opacity, SubsurfaceColor, PreTonemapHDRColor.
Its not clear where the valid VisualizationMode FNames are defined, it may be in the [Engine.BufferVisualizationMaterials] section of Config/BaseEngine.ini, which is read by FBufferVisualizationData::Initialize() and called when the engine initializes in UEngine::Init()
References Config, HorzFOVDegrees, NearPlaneDist, ResultImageOut, and UE_API.
CaptureDeviceDepthFromPosition()
MODELINGCOMPONENTS_API bool UE::Geometry::FWorldRenderCapture::CaptureDeviceDepthFromPosition (const FFrame3d & Frame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter & ResultImageOut, const FRenderCaptureConfig & Config = {}) protected
Depth is a special case and uses different code than capture of color/property channels.
References Config, HorzFOVDegrees, NearPlaneDist, ResultImageOut, and UE_API.
CaptureFromPosition()
MODELINGCOMPONENTS_API bool UE::Geometry::FWorldRenderCapture::CaptureFromPosition (ERenderCaptureType CaptureType, const FFrame3d & ViewFrame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter & ResultImageOut, const FRenderCaptureConfig & Config = {})
Capture the desired buffer type CaptureType with the given view/camera parameters.
The returned image data is interpreted according to the comment in FRenderCaptureCoordinateConverter2D
Parameters
ResultImageOut output image of size GetDimensions() is stored here.
Returns
true if capture could be rendered successfully
References Config, HorzFOVDegrees, NearPlaneDist, ResultImageOut, and UE_API.
CaptureMRSFromPosition()
MODELINGCOMPONENTS_API bool UE::Geometry::FWorldRenderCapture::CaptureMRSFromPosition (const FFrame3d & Frame, double HorzFOVDegrees, double NearPlaneDist, FImageAdapter & ResultImageOut, const FRenderCaptureConfig & Config = {}) protected
Combined Metallic/Roughness/Specular uses a custom postprocess material.
References Config, HorzFOVDegrees, NearPlaneDist, ResultImageOut, and UE_API.
ComputeContainingRenderSphere()
MODELINGCOMPONENTS_API FSphere UE::Geometry::FWorldRenderCapture::ComputeContainingRenderSphere (float HorzFOVDegrees, float SafetyBoundsScale = 1.25f) const
Compute a sphere where, if the camera is on the sphere pointed at the center, then the Visible Actors will be fully visible (ie a square capture will not have any clipping), for the given Field of View.
SafetyBoundsScale multiplier is applied to the bounding box.
References HorzFOVDegrees, and UE_API.
GetDepthRenderTexture()
MODELINGCOMPONENTS_API UTextureRenderTarget2D * UE::Geometry::FWorldRenderCapture::GetDepthRenderTexture () protected
References UE_API.
GetDimensions()
const FImageDimensions & UE::Geometry::FWorldRenderCapture::GetDimensions () const inline
Returns
pixel dimensions that target image will be rendered at
Definition at line 265 of file WorldRenderCapture.h.
References Dimensions.
GetRenderTexture()
MODELINGCOMPONENTS_API UTextureRenderTarget2D * UE::Geometry::FWorldRenderCapture::GetRenderTexture (bool bLinear) protected
References UE_API.
GetVisibleActorBounds()
FBoxSphereBounds UE::Geometry::FWorldRenderCapture::GetVisibleActorBounds () const inline
Get bounding-box of the Visible actors.
Definition at line 252 of file WorldRenderCapture.h.
References GetVisibleActorBounds(), and VisibleBounds.
Referenced by GetVisibleActorBounds().
operator=() [1/2]
FWorldRenderCapture & UE::Geometry::FWorldRenderCapture::operator= (const FWorldRenderCapture &) default
References FWorldRenderCapture().
operator=() [2/2]
FWorldRenderCapture & UE::Geometry::FWorldRenderCapture::operator= (FWorldRenderCapture &&) default noexcept
References FWorldRenderCapture(), PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_API.
SetDimensions()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::SetDimensions (const FImageDimensions & Dimensions)
Set desired pixel dimensions of the rendered target image.
References Dimensions, and UE_API.
SetEnableWriteDebugImage()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::SetEnableWriteDebugImage (bool bEnable, int32 ImageCounter = -1, FString FolderName = FString())
Enable debug image write.
The captured image will be written to <Project>/Intermediate/<FolderName>/<CaptureType>_<ImageCounter>.bmp If FolderName is not specified, "WorldRenderCapture" is used by default. If an ImageCounter is not specified, an internal static counter is used that increments on every write
References UE_API.
SetVisibleActors()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::SetVisibleActors (const TArray< AActor * > & Actors)
Set the set of Actors in the target World that should be included in the Rendering.
References UE::Geometry::Actors, SetVisibleActors(), and UE_API.
Referenced by SetVisibleActors().
SetVisibleActorsAndComponents()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::SetVisibleActorsAndComponents (const TArray< AActor * > & VisibleActors, const TArray< UActorComponent * > & VisibleComponents)
Set the set of Actors and Components in the target World that should be included in the Rendering.
References SetVisibleActorsAndComponents(), and UE_API.
Referenced by SetVisibleActorsAndComponents().
SetVisibleComponents()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::SetVisibleComponents (const TArray< UActorComponent * > & Components)
Set the set of Components in the target World that should be included in the Rendering.
References Components, SetVisibleComponents(), and UE_API.
Referenced by SetVisibleComponents().
SetWorld()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::SetWorld (UWorld * World)
Set the target World.
References SetWorld(), UE_API, and World.
Referenced by SetWorld().
Shutdown()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::Shutdown ()
Explicitly release any allocated textures or other data structres.
References Shutdown(), and UE_API.
Referenced by Shutdown().
UE_DEPRECATED() [1/3]
UE::Geometry::FWorldRenderCapture::UE_DEPRECATED (5. 4) const & protected
Emissive is a special case and uses different code than capture of color/property channels.
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
UE::Geometry::FWorldRenderCapture::UE_DEPRECATED (5. 4, "Please use GetRenderCaptureViewMatrices instead") const & inline
Returns
view matrices used in the last call to CaptureFromPosition Useful to get the needed information to unproject the DeviceDepth render capture
Definition at line 271 of file WorldRenderCapture.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/3]
UE::Geometry::FWorldRenderCapture::UE_DEPRECATED (5. 4, "Please use GetRenderCaptureViewMatrices instead") protected
WriteDebugImage()
MODELINGCOMPONENTS_API void UE::Geometry::FWorldRenderCapture::WriteDebugImage (const FImageAdapter & ResultImageOut, const FString & ImageTypeName) protected
References ResultImageOut, and UE_API.
Field Documentation
bWriteDebugImage
bool UE::Geometry::FWorldRenderCapture::bWriteDebugImage = false protected
Definition at line 363 of file WorldRenderCapture.h.
Config
double double FImageAdapter const FRenderCaptureConfig& UE::Geometry::FWorldRenderCapture::Config = {}) protected
Definition at line 330 of file WorldRenderCapture.h.
Referenced by CaptureBufferVisualizationFromPosition(), CaptureDeviceDepthFromPosition(), CaptureFromPosition(), and CaptureMRSFromPosition().
DebugImageCounter
int32 UE::Geometry::FWorldRenderCapture::DebugImageCounter = -1 protected
Definition at line 364 of file WorldRenderCapture.h.
DebugImageFolderName
FString UE::Geometry::FWorldRenderCapture::DebugImageFolderName = TEXT("WorldRenderCapture") protected
Definition at line 365 of file WorldRenderCapture.h.
DepthRenderTexture
UTextureRenderTarget2D* UE::Geometry::FWorldRenderCapture::DepthRenderTexture = nullptr protected
Definition at line 311 of file WorldRenderCapture.h.
Dimensions
FImageDimensions UE::Geometry::FWorldRenderCapture::Dimensions = FImageDimensions(128, 128) protected
Definition at line 306 of file WorldRenderCapture.h.
Referenced by GetDimensions(), and SetDimensions().
GammaRenderTexture
UTextureRenderTarget2D* UE::Geometry::FWorldRenderCapture::GammaRenderTexture = nullptr protected
Definition at line 310 of file WorldRenderCapture.h.
HorzFOVDegrees
double UE::Geometry::FWorldRenderCapture::HorzFOVDegrees protected
Definition at line 327 of file WorldRenderCapture.h.
Referenced by CaptureBufferVisualizationFromPosition(), CaptureDeviceDepthFromPosition(), CaptureFromPosition(), CaptureMRSFromPosition(), and ComputeContainingRenderSphere().
LinearRenderTexture
UTextureRenderTarget2D* UE::Geometry::FWorldRenderCapture::LinearRenderTexture = nullptr protected
Definition at line 309 of file WorldRenderCapture.h.
NearPlaneDist
double double UE::Geometry::FWorldRenderCapture::NearPlaneDist protected
Definition at line 328 of file WorldRenderCapture.h.
Referenced by CaptureBufferVisualizationFromPosition(), CaptureDeviceDepthFromPosition(), CaptureFromPosition(), and CaptureMRSFromPosition().
ReadImageBuffer
TArray<FLinearColor> UE::Geometry::FWorldRenderCapture::ReadImageBuffer protected
Definition at line 321 of file WorldRenderCapture.h.
RenderTextureDimensions
FImageDimensions UE::Geometry::FWorldRenderCapture::RenderTextureDimensions protected
Definition at line 313 of file WorldRenderCapture.h.
ResultImageOut
double double FImageAdapter& UE::Geometry::FWorldRenderCapture::ResultImageOut protected
Definition at line 329 of file WorldRenderCapture.h.
Referenced by CaptureBufferVisualizationFromPosition(), CaptureDeviceDepthFromPosition(), CaptureFromPosition(), CaptureMRSFromPosition(), and WriteDebugImage().
VisibleBounds
FBoxSphereBounds UE::Geometry::FWorldRenderCapture::VisibleBounds protected
Definition at line 304 of file WorldRenderCapture.h.
Referenced by GetVisibleActorBounds().
VisiblePrimitives
TSet<FPrimitiveComponentId> UE::Geometry::FWorldRenderCapture::VisiblePrimitives protected
Definition at line 303 of file WorldRenderCapture.h.
World
UWorld* UE::Geometry::FWorldRenderCapture::World = nullptr protected
Definition at line 301 of file WorldRenderCapture.h.
Referenced by SetWorld().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Scene/WorldRenderCapture.h