Unreal Engine 5.6 C++ API: FBitArrayMemory Class Reference
FBitArrayMemory Class Reference
#include "BitArray.h"
Static Public Member Functions
static void MemmoveBitsWordOrder (int32 *DestBits, int32 DestOffset, const int32 *SourceBits, int32 SourceOffset, uint32 NumBits)
static void MemmoveBitsWordOrder (uint32 *DestBits, int32 DestOffset, const uint32 *SourceBits, int32 SourceOffset, uint32 NumBits)
Copy NumBits bits from the source pointer and offset into the dest pointer and offset.
static void ModularizeWordOffset (uint32 *&Data, int32 &Offset)
Given Data and Offset that specify a specific bit in a specific word, modify Data and Offset so that they specify the same bit but that 0 <= Offset < NumBitsPerDWORD.
static void ModularizeWordOffset (uint32 const *&Data, int32 &Offset)
Given Data and Offset that specify a specific bit in a specific word, modify Data and Offset so that they specify the same bit but that 0 <= Offset < NumBitsPerDWORD.
Static Private Member Functions
static void MemmoveBitsWordOrderAlignedInternal (uint32 *const StartDest, const uint32 *const StartSource, int32 StartOffset, uint32 NumBits)
Copy NumBits bits from the source pointer at the given offset into the dest pointer at the given offset.
Friends
class FBitArrayMemoryTest
Detailed Description
Definition at line 303 of file BitArray.h.
Member Function Documentation
MemmoveBitsWordOrder() [1/2]
void FBitArrayMemory::MemmoveBitsWordOrder (int32 * DestBits, int32 DestOffset, const int32 * SourceBits, int32 SourceOffset, uint32 NumBits) inline static
Definition at line 319 of file BitArray.h.
References MemmoveBitsWordOrder().
MemmoveBitsWordOrder() [2/2]
void FBitArrayMemory::MemmoveBitsWordOrder (uint32 * DestBits, int32 DestOffset, const uint32 * SourceBits, int32 SourceOffset, uint32 NumBits) static
Copy NumBits bits from the source pointer and offset into the dest pointer and offset.
This function is not suitable for general use because it uses a bit order that is specific to the uint32 internal storage of BitArray
Bits within each word are read or written in the current platform's mathematical bitorder (Data[0] & 0x1, Data[0] & 0x2, ... Data[0] & 0x100, ... Data[0] & 0x80000000, Data[1] & 0x1 ... Correctly handles overlap between destination range and source range; the array of destination bits will be a copy of the source bits as they were before the copy started.
Parameters
DestBits The base location to which the bits are written.
DestOffset The (word-order) bit within DestBits at which to start writing. Can be any value; offsets outside of [0,NumBitsPerDWORD) will be equivalent to modifying the DestBits pointer.
SourceBits The base location from which the bits are read.
SourceOffset The (word-order) bit within SourceBits at which to start reading. Can be any value; offsets outside of [0,NumBitsPerDWORD) will be equivalent to modifying the SourceBits pointer.
NumBits Number of bits to copy. Must be >= 0.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::GetRange(), TBitArray< typename Allocator::BitArrayAllocator >::InsertUninitialized(), MemmoveBitsWordOrder(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAt(), TBitArray< typename Allocator::BitArrayAllocator >::SetRangeFromRange(), and TBitArray< typename Allocator::BitArrayAllocator >::SetRangeFromRange().
MemmoveBitsWordOrderAlignedInternal()
void FBitArrayMemory::MemmoveBitsWordOrderAlignedInternal (uint32 *const StartDest, const uint32 *const StartSource, int32 StartOffset, uint32 NumBits) static private
Copy NumBits bits from the source pointer at the given offset into the dest pointer at the given offset.
It has the same behavior as MemmoveBitsWordOrder under the constaint that DestOffset == SourceOffset.
ModularizeWordOffset() [1/2]
void FBitArrayMemory::ModularizeWordOffset (uint32 *& Data, int32 & Offset) inline static
Given Data and Offset that specify a specific bit in a specific word, modify Data and Offset so that they specify the same bit but that 0 <= Offset < NumBitsPerDWORD.
Definition at line 325 of file BitArray.h.
References ModularizeWordOffset().
Referenced by ModularizeWordOffset().
ModularizeWordOffset() [2/2]
void FBitArrayMemory::ModularizeWordOffset (uint32 const *& Data, int32 & Offset) static
Given Data and Offset that specify a specific bit in a specific word, modify Data and Offset so that they specify the same bit but that 0 <= Offset < NumBitsPerDWORD.
Friends And Related Symbol Documentation
FBitArrayMemoryTest
friend class FBitArrayMemoryTest friend
Definition at line 341 of file BitArray.h.
References FBitArrayMemoryTest.
Referenced by FBitArrayMemoryTest.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/BitArray.h