Unreal Engine 5.6 C++ API: FAudioDeviceManager Class Reference
FAudioDeviceManager Class Reference
Class for managing multiple audio devices.
#include "AudioDeviceManager.h"
Data Structures
struct FAudioDeviceContainer
Public Member Functions
FAudioDeviceManager ()
Constructor.
~FAudioDeviceManager ()
Destructor.
void AddReferencedObjects (FReferenceCollector &Collector)
Tracks objects in the active audio devices.
bool CreateMainAudioDevice ()
Creates the main audio device.
void FreeResource (USoundWave *SoundWave)
Frees the given sound wave resource from the device manager.
FAudioDeviceHandle GetActiveAudioDevice ()
Returns a ptr to the active audio device.
FAudioDeviceHandle GetAudioDevice (Audio::FDeviceId InDeviceID)
Returns a strong handle to the audio device associated with the given device ID.
IAudioDeviceModule * GetAudioDeviceModule ()
returns the currently used audio device module for this platform.
FAudioDevice * GetAudioDeviceRaw (Audio::FDeviceId InDeviceID)
Returns a raw ptr to the audio device associated with the handle.
const FAudioDevice * GetAudioDeviceRaw (Audio::FDeviceId InDeviceID) const
TArray< FAudioDevice * > GetAudioDevices () const
Returns all the audio devices managed by device manager.
Audio::FAudioFormatSettings & GetAudioFormatSettings () const
FAudioDeviceParams GetDefaultParamsForNewWorld ()
float GetDynamicSoundVolume (ESoundType SoundType, const FName &SoundName) const
Get, reset, or set a sound cue trim.
const FAudioDeviceHandle & GetMainAudioDeviceHandle () const
Returns the handle to the main audio device.
Audio::FDeviceId GetMainAudioDeviceID () const
FAudioDevice * GetMainAudioDeviceRaw () const
uint8 GetNumActiveAudioDevices () const
Returns the current number of active audio devices.
uint8 GetNumMainAudioDeviceWorlds () const
Returns the number of worlds (e.g.
TArray< UWorld * > GetWorldsUsingAudioDevice (const Audio::FDeviceId &InID) const
void InitSoundClasses ()
Initializes the sound class for all active devices.
void InitSoundSubmixes ()
Initializes the sound mixes for all active devices.
bool IsAlwaysPlayNonRealtimeDeviceAudio () const
Gets whether or not non-realtime devices should play their audio.
bool IsPlayAllDeviceAudio () const
Gets whether or not all devices should play their audio.
bool IsValidAudioDevice (Audio::FDeviceId DeviceID) const
Returns whether the audio device handle is valid (i.e.
bool IsVisualizeDebug3dEnabled () const
Is debug visualization of 3d sounds enabled.
void IterateOverAllDevices (TUniqueFunction< void(Audio::FDeviceId, const FAudioDevice *)> ForEachDevice) const
void IterateOverAllDevices (TUniqueFunction< void(Audio::FDeviceId, FAudioDevice *)> ForEachDevice)
Iterates over all managed audio devices.
void LogListOfAudioDevices ()
void RegisterSoundClass (USoundClass *SoundClass)
Registers the Sound Class for all active devices.
void RegisterSoundSubmix (USoundSubmixBase *SoundSubmix)
Registers the Sound Mix for all active devices.
void RegisterWorld (UWorld *InWorld, Audio::FDeviceId DeviceId)
Registers the world with the provided device Id.
void RemoveSoundMix (USoundMix *SoundMix)
Removes sound mix from all audio devices.
FAudioDeviceHandle RequestAudioDevice (const FAudioDeviceParams &InParams)
Creates or requests an audio device instance internally and returns a handle to the audio device.
void ResetAllDynamicSoundVolumes ()
Reset all sound cue trims.
void ResetDynamicSoundVolume (ESoundType SoundType, const FName &SoundName)
void SetActiveDevice (uint32 InAudioDeviceHandle)
Sets which audio device is the active audio device.
void SetAudioDevice (UWorld &InWorld, Audio::FDeviceId InDeviceID)
Sets the device associated with the given world.
void SetDynamicSoundVolume (ESoundType SoundType, const FName &SoundName, float Volume)
void SetSoloDevice (Audio::FDeviceId InAudioDeviceHandle)
Sets an audio device to be solo'd.
void StopSoundsUsingResource (class USoundWave *InSoundWave, TArray< UAudioComponent * > *StoppedComponents=nullptr)
Stops sounds using the given resource on all audio devices.
void TogglePlayAllDeviceAudio ()
Toggles playing audio for all active PIE sessions (and all devices).
void ToggleVisualize3dDebug ()
Toggles 3d visualization of 3d sounds on/off.
UE_DEPRECATED (5.4, "Will be removed in upcoming versions of this code") 1 void InitSoundEffectPresets()
Initialize all sound effect presets.
UE_DEPRECATED (5.5, "This is no longer used and should not be accessed directly.") TArray< FSoundBuffer * > Buffers
Array of all created buffers.
UE_DEPRECATED (5.5, "This is no longer used and should not be accessed directly.") TMap< int32
Look up associating a USoundWave's resource ID with sound buffers.
UE_DEPRECATED (5.5, "This is no longer used. Existing calls may be deleted") 1 FSoundBuffer *GetSoundBufferForResourceID(uint32 ResourceID)
UE_DEPRECATED (5.5, "This is no longer used. Existing calls may be deleted") 1 void FreeBufferResource(FSoundBuffer *SoundBuffer)
UE_DEPRECATED (5.5, "This is no longer used. Existing calls may be deleted") 1 void RemoveSoundBufferForResourceID(uint32 ResourceID)
Removes the sound buffer for the given resource id.
UE_DEPRECATED (5.5, "This is no longer used. Existing calls may be deleted") 1 void StopSourcesUsingBuffer(FSoundBuffer *Buffer)
UE_DEPRECATED (5.5, "This is no longer used. Existing calls may be deleted") 1 void TrackResource(USoundWave *SoundWave
void UnregisterSoundClass (USoundClass *SoundClass)
Unregisters the Sound Class for all active devices.
void UnregisterSoundSubmix (const USoundSubmixBase *SoundSubmix)
Registers the Sound Mix for all active devices.
void UnregisterWorld (UWorld *InWorld, Audio::FDeviceId DeviceId)
Unregisters the world from the provided device Id.
void UpdateActiveAudioDevices (bool bGameTicking)
Updates all active audio devices.
void UpdateSourceEffectChain (const uint32 SourceEffectChainId, const TArray< FSourceEffectChainEntry > &SourceEffectChain, const bool bPlayEffectChainTails)
Updates source effect chain on all sources currently using the source effect chain.
void UpdateSubmix (USoundSubmixBase *SoundSubmix)
Updates this submix for any changes made.
Static Public Member Functions
static void EnableAggregateDeviceSupport (const bool bInEnableAggregateDevice)
static FAudioDeviceManager * Get ()
Returns the AudioDeviceManager Singleton.
static FAudioDevice * GetAudioDeviceFromWorldContext (const UObject *WorldContextObject)
static Audio::FMixerDevice * GetAudioMixerDeviceFromWorldContext (const UObject *WorldContextObject)
static bool Initialize ()
Initializes the Manager.
static bool IsAggregateDeviceSupportEnabled ()
static bool PreInitialize ()
Pre-initializes the Manager.
static void Shutdown ()
Shuts down the AudioDeviceManager and all AudioDevices.
Data Fields
FSoundBuffer * Buffer
FSoundBuffer * WaveBufferMap
Private Types
enum class EInitPhase : uint32 { Constructed , PreInitialized , Initialized }
Simple state machine of the init state of the manager.
Private Member Functions
void AppWillEnterBackground ()
Application enters background handler.
FAudioDeviceHandle BuildNewHandle (FAudioDeviceContainer &Container, Audio::FDeviceId DeviceID, const FAudioDeviceParams &InParams)
FAudioDeviceHandle CreateNewDevice (const FAudioDeviceParams &InParams)
void DecrementDevice (Audio::FDeviceId DeviceID, UWorld *InWorld)
uint32 GetNewDeviceID ()
Creates a handle given the index and a generation value.
void IncrementDevice (Audio::FDeviceId DeviceID)
bool InitializeManager ()
Initalizes the Manager.
bool IsInitialized () const
Queries if the device manager is initalized.
bool LoadDefaultAudioDeviceModule ()
Load audio device module.
bool PreInitializeManager ()
Pre-initializes the Manager This starts up and intializes the manager early without need for the Engine to be available, so that we can load essential services ahead of Engine Startup.
void RegisterAudioInfoFactories ()
Static Private Member Functions
static bool CanUseAudioDevice (const FAudioDeviceParams &InParams, const FAudioDeviceContainer &InContainer)
This function is used to check if we can use an existing audio device.
static FAudioDeviceManager * GetOrCreate ()
Conditionally Creates the AudioDeviceManager.
Private Attributes
Audio::FDeviceId ActiveAudioDeviceID
Which audio device is currently active.
IAudioDeviceModule * AudioDeviceModule
Audio device module which creates audio devices.
TPimplPtr< Audio::FAudioFormatSettings > AudioFormatSettings
FString AudioMixerModuleName
The audio mixer module name.
bool bPlayAllDeviceAudio
Whether or not to play all audio in all active audio devices.
uint32 DeviceIDCounter
FCriticalSection DeviceMapCriticalSection
TMap< Audio::FDeviceId, FAudioDeviceContainer > Devices
Bank of audio devices.
TMap< TTuple< ESoundType, FName >, float > DynamicSoundVolumes
Dynamic volume map.
TArray< TPimplPtr< FSimpleAudioInfoFactory > > EngineFormats
EInitPhase InitPhase = EInitPhase::Constructed
FAudioDeviceHandle MainAudioDeviceHandle
Handle to the main audio device.
int32 NextResourceID
Next resource ID to assign out to a wave/buffer.
Audio::FDeviceId SoloDeviceHandle
Which audio device is solo'd.
FAudioCommandFence SyncFence
Audio Fence to ensure that we don't allow the audio thread to drift never endingly behind.
Static Private Attributes
static bool bEnableAggregateDeviceSupport
True if aggregate devices are supported.
static FAudioDeviceManager * Singleton
Friends
class FAudioDeviceHandle
Detailed Description
Class for managing multiple audio devices.
Definition at line 86 of file AudioDeviceManager.h.
Member Enumeration Documentation
EInitPhase
enum class FAudioDeviceManager::EInitPhase : uint32 strong private
Simple state machine of the init state of the manager.
Enumerator
Constructed
PreInitialized
Initialized
Definition at line 469 of file AudioDeviceManager.h.
Constructor & Destructor Documentation
FAudioDeviceManager()
FAudioDeviceManager::FAudioDeviceManager ()
Constructor.
Referenced by FAudioDeviceManager::FAudioDeviceContainer::FAudioDeviceContainer(), Get(), and GetOrCreate().
~FAudioDeviceManager()
FAudioDeviceManager::~FAudioDeviceManager ()
Destructor.
Member Function Documentation
AddReferencedObjects()
void FAudioDeviceManager::AddReferencedObjects (FReferenceCollector & Collector)
Tracks objects in the active audio devices.
AppWillEnterBackground()
void FAudioDeviceManager::AppWillEnterBackground () private
Application enters background handler.
BuildNewHandle()
FAudioDeviceHandle FAudioDeviceManager::BuildNewHandle (FAudioDeviceContainer & Container, Audio::FDeviceId DeviceID, const FAudioDeviceParams & InParams) private
References Container, DeviceID, and FAudioDeviceHandle.
CanUseAudioDevice()
bool FAudioDeviceManager::CanUseAudioDevice (const FAudioDeviceParams & InParams, const FAudioDeviceContainer & InContainer) static private
This function is used to check if we can use an existing audio device.
References InContainer.
CreateMainAudioDevice()
bool FAudioDeviceManager::CreateMainAudioDevice ()
Creates the main audio device.
CreateNewDevice()
FAudioDeviceHandle FAudioDeviceManager::CreateNewDevice (const FAudioDeviceParams & InParams) private
References FAudioDeviceHandle.
DecrementDevice()
void FAudioDeviceManager::DecrementDevice (Audio::FDeviceId DeviceID, UWorld * InWorld) private
References DeviceID.
EnableAggregateDeviceSupport()
void FAudioDeviceManager::EnableAggregateDeviceSupport (const bool bInEnableAggregateDevice) static
FreeResource()
void FAudioDeviceManager::FreeResource (USoundWave * SoundWave)
Frees the given sound wave resource from the device manager.
References FreeResource().
Referenced by FreeResource().
Get()
FAudioDeviceManager * FAudioDeviceManager::Get () static
Returns the AudioDeviceManager Singleton.
Returns
The Instance instance or nullptr if the device has not been fully initialized.
References FAudioDeviceManager().
GetActiveAudioDevice()
FAudioDeviceHandle FAudioDeviceManager::GetActiveAudioDevice ()
Returns a ptr to the active audio device.
If there is no active device then it will return the main audio device.
References FAudioDeviceHandle.
GetAudioDevice()
FAudioDeviceHandle FAudioDeviceManager::GetAudioDevice (Audio::FDeviceId InDeviceID)
Returns a strong handle to the audio device associated with the given device ID.
if the device ID is invalid returns an invalid, zeroed handle.
References FAudioDeviceHandle.
GetAudioDeviceFromWorldContext()
FAudioDevice * FAudioDeviceManager::GetAudioDeviceFromWorldContext (const UObject * WorldContextObject) static
GetAudioDeviceModule()
IAudioDeviceModule * FAudioDeviceManager::GetAudioDeviceModule ()
returns the currently used audio device module for this platform.
returns nullptr if Initialize() has not been called yet.
GetAudioDeviceRaw() [1/2]
FAudioDevice * FAudioDeviceManager::GetAudioDeviceRaw (Audio::FDeviceId InDeviceID)
Returns a raw ptr to the audio device associated with the handle.
If the handle is invalid then a NULL device ptr will be returned.
GetAudioDeviceRaw() [2/2]
const FAudioDevice * FAudioDeviceManager::GetAudioDeviceRaw (Audio::FDeviceId InDeviceID) const
GetAudioDevices()
TArray< FAudioDevice * > FAudioDeviceManager::GetAudioDevices () const
Returns all the audio devices managed by device manager.
References GetAudioDevices().
Referenced by GetAudioDevices().
GetAudioFormatSettings()
Audio::FAudioFormatSettings & FAudioDeviceManager::GetAudioFormatSettings () const
GetAudioMixerDeviceFromWorldContext()
Audio::FMixerDevice * FAudioDeviceManager::GetAudioMixerDeviceFromWorldContext (const UObject * WorldContextObject) static
GetDefaultParamsForNewWorld()
FAudioDeviceParams FAudioDeviceManager::GetDefaultParamsForNewWorld ()
GetDynamicSoundVolume()
float FAudioDeviceManager::GetDynamicSoundVolume (ESoundType SoundType, const FName & SoundName) const
Get, reset, or set a sound cue trim.
GetMainAudioDeviceHandle()
const FAudioDeviceHandle & FAudioDeviceManager::GetMainAudioDeviceHandle () const inline
Returns the handle to the main audio device.
Definition at line 101 of file AudioDeviceManager.h.
References FAudioDeviceHandle, and MainAudioDeviceHandle.
GetMainAudioDeviceID()
Audio::FDeviceId FAudioDeviceManager::GetMainAudioDeviceID () const inline
Definition at line 103 of file AudioDeviceManager.h.
References MainAudioDeviceHandle.
GetMainAudioDeviceRaw()
FAudioDevice * FAudioDeviceManager::GetMainAudioDeviceRaw () const inline
Definition at line 102 of file AudioDeviceManager.h.
References MainAudioDeviceHandle.
GetNewDeviceID()
uint32 FAudioDeviceManager::GetNewDeviceID () private
Creates a handle given the index and a generation value.
GetNumActiveAudioDevices()
uint8 FAudioDeviceManager::GetNumActiveAudioDevices () const
Returns the current number of active audio devices.
GetNumMainAudioDeviceWorlds()
uint8 FAudioDeviceManager::GetNumMainAudioDeviceWorlds () const
Returns the number of worlds (e.g.
PIE viewports) using the main audio device.
GetOrCreate()
FAudioDeviceManager * FAudioDeviceManager::GetOrCreate () static private
Conditionally Creates the AudioDeviceManager.
Returns
New Instance or Existing Singleton, or nullptr on failure (which can happen if audio is disabled).
References FAudioDeviceManager().
GetWorldsUsingAudioDevice()
TArray< UWorld * > FAudioDeviceManager::GetWorldsUsingAudioDevice (const Audio::FDeviceId & InID) const
References GetWorldsUsingAudioDevice().
Referenced by GetWorldsUsingAudioDevice().
IncrementDevice()
void FAudioDeviceManager::IncrementDevice (Audio::FDeviceId DeviceID) private
References DeviceID.
Initialize()
bool FAudioDeviceManager::Initialize () static
Initializes the Manager.
NOTE: If the manager hasn't been PreInitialized, that stage will be performed first.
Returns
True if success, false otherwise
InitializeManager()
bool FAudioDeviceManager::InitializeManager () private
Initalizes the Manager.
NOTE: If PreInitializeManager has not been called already, a PreInitializeManager call is made first.
Returns
True if success, false otherwise
InitSoundClasses()
void FAudioDeviceManager::InitSoundClasses ()
Initializes the sound class for all active devices.
InitSoundSubmixes()
void FAudioDeviceManager::InitSoundSubmixes ()
Initializes the sound mixes for all active devices.
IsAggregateDeviceSupportEnabled()
bool FAudioDeviceManager::IsAggregateDeviceSupportEnabled () static
IsAlwaysPlayNonRealtimeDeviceAudio()
bool FAudioDeviceManager::IsAlwaysPlayNonRealtimeDeviceAudio () const
Gets whether or not non-realtime devices should play their audio.
IsInitialized()
bool FAudioDeviceManager::IsInitialized () const inline private
Queries if the device manager is initalized.
Returns
true if initialized, false otherwise.
Definition at line 360 of file AudioDeviceManager.h.
References Initialized, and InitPhase.
IsPlayAllDeviceAudio()
bool FAudioDeviceManager::IsPlayAllDeviceAudio () const inline
Gets whether or not all devices should play their audio.
Definition at line 266 of file AudioDeviceManager.h.
References bPlayAllDeviceAudio, and IsPlayAllDeviceAudio().
Referenced by IsPlayAllDeviceAudio().
IsValidAudioDevice()
bool FAudioDeviceManager::IsValidAudioDevice (Audio::FDeviceId DeviceID) const
Returns whether the audio device handle is valid (i.e.
points to an actual audio device instance)
References DeviceID.
IsVisualizeDebug3dEnabled()
bool FAudioDeviceManager::IsVisualizeDebug3dEnabled () const
Is debug visualization of 3d sounds enabled.
IterateOverAllDevices() [1/2]
void FAudioDeviceManager::IterateOverAllDevices (TUniqueFunction< void(Audio::FDeviceId, const FAudioDevice *)> ForEachDevice) const
IterateOverAllDevices() [2/2]
void FAudioDeviceManager::IterateOverAllDevices (TUniqueFunction< void(Audio::FDeviceId, FAudioDevice *)> ForEachDevice)
Iterates over all managed audio devices.
LoadDefaultAudioDeviceModule()
bool FAudioDeviceManager::LoadDefaultAudioDeviceModule () private
Load audio device module.
LogListOfAudioDevices()
void FAudioDeviceManager::LogListOfAudioDevices ()
PreInitialize()
bool FAudioDeviceManager::PreInitialize () static
Pre-initializes the Manager.
This starts up and initializes the manager early without need for the Engine to be available, so that we can load essential services ahead of Engine Startup.
Returns
True if success, false otherwise
PreInitializeManager()
bool FAudioDeviceManager::PreInitializeManager () private
Pre-initializes the Manager This starts up and intializes the manager early without need for the Engine to be available, so that we can load essential services ahead of Engine Startup.
This is optional in the flow, as InitializeManager will also call this if required.
Returns
True if success, false otherwise
RegisterAudioInfoFactories()
void FAudioDeviceManager::RegisterAudioInfoFactories () private
RegisterSoundClass()
void FAudioDeviceManager::RegisterSoundClass (USoundClass * SoundClass)
Registers the Sound Class for all active devices.
RegisterSoundSubmix()
void FAudioDeviceManager::RegisterSoundSubmix (USoundSubmixBase * SoundSubmix)
Registers the Sound Mix for all active devices.
RegisterWorld()
void FAudioDeviceManager::RegisterWorld (UWorld * InWorld, Audio::FDeviceId DeviceId)
Registers the world with the provided device Id.
RemoveSoundMix()
void FAudioDeviceManager::RemoveSoundMix (USoundMix * SoundMix)
Removes sound mix from all audio devices.
References RemoveSoundMix().
Referenced by RemoveSoundMix().
RequestAudioDevice()
FAudioDeviceHandle FAudioDeviceManager::RequestAudioDevice (const FAudioDeviceParams & InParams)
Creates or requests an audio device instance internally and returns a handle to the audio device.
This audio device is guaranteed to be alive as long as the returned handle is in scope.
References FAudioDeviceHandle.
ResetAllDynamicSoundVolumes()
void FAudioDeviceManager::ResetAllDynamicSoundVolumes ()
Reset all sound cue trims.
ResetDynamicSoundVolume()
void FAudioDeviceManager::ResetDynamicSoundVolume (ESoundType SoundType, const FName & SoundName)
SetActiveDevice()
void FAudioDeviceManager::SetActiveDevice (uint32 InAudioDeviceHandle)
Sets which audio device is the active audio device.
References SetActiveDevice().
Referenced by SetActiveDevice().
SetAudioDevice()
void FAudioDeviceManager::SetAudioDevice (UWorld & InWorld, Audio::FDeviceId InDeviceID)
Sets the device associated with the given world.
SetDynamicSoundVolume()
void FAudioDeviceManager::SetDynamicSoundVolume (ESoundType SoundType, const FName & SoundName, float Volume)
References Volume.
SetSoloDevice()
void FAudioDeviceManager::SetSoloDevice (Audio::FDeviceId InAudioDeviceHandle)
Sets an audio device to be solo'd.
References SetSoloDevice().
Referenced by SetSoloDevice().
Shutdown()
void FAudioDeviceManager::Shutdown () static
Shuts down the AudioDeviceManager and all AudioDevices.
StopSoundsUsingResource()
void FAudioDeviceManager::StopSoundsUsingResource (class USoundWave * InSoundWave, TArray< UAudioComponent * > * StoppedComponents = nullptr)
Stops sounds using the given resource on all audio devices.
TogglePlayAllDeviceAudio()
void FAudioDeviceManager::TogglePlayAllDeviceAudio ()
Toggles playing audio for all active PIE sessions (and all devices).
References TogglePlayAllDeviceAudio().
Referenced by TogglePlayAllDeviceAudio().
ToggleVisualize3dDebug()
void FAudioDeviceManager::ToggleVisualize3dDebug ()
Toggles 3d visualization of 3d sounds on/off.
UE_DEPRECATED() [1/8]
FAudioDeviceManager::UE_DEPRECATED (5. 4, "Will be removed in upcoming versions of this code")
Initialize all sound effect presets.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used and should not be accessed directly.")
Array of all created buffers.
UE_DEPRECATED() [3/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used and should not be accessed directly.")
Look up associating a USoundWave's resource ID with sound buffers.
References UE_DEPRECATED().
UE_DEPRECATED() [4/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used. Existing calls may be deleted")
References UE_DEPRECATED().
UE_DEPRECATED() [5/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used. Existing calls may be deleted")
References UE_DEPRECATED().
UE_DEPRECATED() [6/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used. Existing calls may be deleted")
Removes the sound buffer for the given resource id.
References UE_DEPRECATED().
UE_DEPRECATED() [7/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used. Existing calls may be deleted")
References Buffer, and UE_DEPRECATED().
UE_DEPRECATED() [8/8]
FAudioDeviceManager::UE_DEPRECATED (5. 5, "This is no longer used. Existing calls may be deleted")
References UE_DEPRECATED().
UnregisterSoundClass()
void FAudioDeviceManager::UnregisterSoundClass (USoundClass * SoundClass)
Unregisters the Sound Class for all active devices.
UnregisterSoundSubmix()
void FAudioDeviceManager::UnregisterSoundSubmix (const USoundSubmixBase * SoundSubmix)
Registers the Sound Mix for all active devices.
UnregisterWorld()
void FAudioDeviceManager::UnregisterWorld (UWorld * InWorld, Audio::FDeviceId DeviceId)
Unregisters the world from the provided device Id.
UpdateActiveAudioDevices()
void FAudioDeviceManager::UpdateActiveAudioDevices (bool bGameTicking)
Updates all active audio devices.
UpdateSourceEffectChain()
void FAudioDeviceManager::UpdateSourceEffectChain (const uint32 SourceEffectChainId, const TArray< FSourceEffectChainEntry > & SourceEffectChain, const bool bPlayEffectChainTails)
Updates source effect chain on all sources currently using the source effect chain.
References UpdateSourceEffectChain().
Referenced by UpdateSourceEffectChain().
UpdateSubmix()
void FAudioDeviceManager::UpdateSubmix (USoundSubmixBase * SoundSubmix)
Updates this submix for any changes made.
Broadcasts to all submix instances.
References UpdateSubmix().
Referenced by UpdateSubmix().
Friends And Related Symbol Documentation
FAudioDeviceHandle
friend class FAudioDeviceHandle friend
Definition at line 477 of file AudioDeviceManager.h.
References FAudioDeviceHandle.
Referenced by BuildNewHandle(), CreateNewDevice(), FAudioDeviceHandle, GetActiveAudioDevice(), GetAudioDevice(), GetMainAudioDeviceHandle(), and RequestAudioDevice().
Field Documentation
ActiveAudioDeviceID
Audio::FDeviceId FAudioDeviceManager::ActiveAudioDeviceID private
Which audio device is currently active.
Definition at line 455 of file AudioDeviceManager.h.
AudioDeviceModule
IAudioDeviceModule* FAudioDeviceManager::AudioDeviceModule private
Audio device module which creates audio devices.
Definition at line 379 of file AudioDeviceManager.h.
AudioFormatSettings
TPimplPtr<Audio::FAudioFormatSettings> FAudioDeviceManager::AudioFormatSettings private
Definition at line 325 of file AudioDeviceManager.h.
AudioMixerModuleName
FString FAudioDeviceManager::AudioMixerModuleName private
The audio mixer module name.
This is the audio mixer module name to use. E.g. AudioMixerXAudio2
Definition at line 382 of file AudioDeviceManager.h.
bEnableAggregateDeviceSupport
bool FAudioDeviceManager::bEnableAggregateDeviceSupport static private
True if aggregate devices are supported.
Static so it can be set prior to initialization of AudioDeviceManager singleton.
Definition at line 329 of file AudioDeviceManager.h.
bPlayAllDeviceAudio
bool FAudioDeviceManager::bPlayAllDeviceAudio private
Whether or not to play all audio in all active audio devices.
Definition at line 461 of file AudioDeviceManager.h.
Referenced by IsPlayAllDeviceAudio().
Buffer
FSoundBuffer* FAudioDeviceManager::Buffer
Definition at line 242 of file AudioDeviceManager.h.
Referenced by UE_DEPRECATED().
DeviceIDCounter
uint32 FAudioDeviceManager::DeviceIDCounter private
Definition at line 446 of file AudioDeviceManager.h.
DeviceMapCriticalSection
FCriticalSection FAudioDeviceManager::DeviceMapCriticalSection mutable private
Definition at line 443 of file AudioDeviceManager.h.
Devices
TMap<Audio::FDeviceId, FAudioDeviceContainer> FAudioDeviceManager::Devices private
Bank of audio devices.
Will increase in size as we create new audio devices,
Definition at line 442 of file AudioDeviceManager.h.
DynamicSoundVolumes
TMap<TTuple<ESoundType, FName>, float> FAudioDeviceManager::DynamicSoundVolumes private
Dynamic volume map.
Definition at line 458 of file AudioDeviceManager.h.
EngineFormats
TArray<TPimplPtr<FSimpleAudioInfoFactory> > FAudioDeviceManager::EngineFormats private
Definition at line 326 of file AudioDeviceManager.h.
InitPhase
EInitPhase FAudioDeviceManager::InitPhase = EInitPhase::Constructed private
Definition at line 475 of file AudioDeviceManager.h.
Referenced by IsInitialized().
MainAudioDeviceHandle
FAudioDeviceHandle FAudioDeviceManager::MainAudioDeviceHandle private
Handle to the main audio device.
Definition at line 385 of file AudioDeviceManager.h.
Referenced by GetMainAudioDeviceHandle(), GetMainAudioDeviceID(), and GetMainAudioDeviceRaw().
NextResourceID
int32 FAudioDeviceManager::NextResourceID private
Next resource ID to assign out to a wave/buffer.
Definition at line 449 of file AudioDeviceManager.h.
Singleton
FAudioDeviceManager* FAudioDeviceManager::Singleton static private
Definition at line 478 of file AudioDeviceManager.h.
SoloDeviceHandle
Audio::FDeviceId FAudioDeviceManager::SoloDeviceHandle private
Which audio device is solo'd.
Definition at line 452 of file AudioDeviceManager.h.
SyncFence
FAudioCommandFence FAudioDeviceManager::SyncFence private
Audio Fence to ensure that we don't allow the audio thread to drift never endingly behind.
Definition at line 464 of file AudioDeviceManager.h.
WaveBufferMap
FSoundBuffer* FAudioDeviceManager::WaveBufferMap
Definition at line 299 of file AudioDeviceManager.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AudioDeviceManager.h