Unreal Engine 5.6 C++ API: UBTDecorator_SetTagCooldown Class Reference
UBTDecorator_SetTagCooldown Class Reference
#include "BTDecorator_SetTagCooldown.h"
Protected Member Functions
virtual AIMODULE_API void OnNodeDeactivation (FBehaviorTreeSearchData &SearchData, EBTNodeResult::Type NodeResult) override
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() FGameplayTag CooldownTag
Gameplay tag that will be used for the cooldown.
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API FString GetStaticDescription () const override
UPROPERTY () FValueOrBBKey_Bool bAddToExistingDuration
True if we are adding to any existing duration, false if we are setting the duration (potentially invalidating an existing end time).
UPROPERTY () FValueOrBBKey_Float CooldownDuration
Value we will add or set to the Cooldown tag when this task runs.
Detailed Description
Definition at line 17 of file BTDecorator_SetTagCooldown.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UBTDecorator_SetTagCooldown::GENERATED_UCLASS_BODY () private
Gameplay tag that will be used for the cooldown.
References Category, and UPROPERTY().
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_SetTagCooldown::GetNodeIconName () const override private virtual
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_SetTagCooldown::GetStaticDescription () const override private virtual
References GetStaticDescription().
Referenced by GetStaticDescription().
OnNodeDeactivation()
virtual AIMODULE_API void UBTDecorator_SetTagCooldown::OnNodeDeactivation (FBehaviorTreeSearchData & SearchData, EBTNodeResult::Type NodeResult) override protected virtual
UPROPERTY() [1/2]
UBTDecorator_SetTagCooldown::UPROPERTY () private
True if we are adding to any existing duration, false if we are setting the duration (potentially invalidating an existing end time).
References Category, and UPROPERTY().
UPROPERTY() [2/2]
UBTDecorator_SetTagCooldown::UPROPERTY () private
Value we will add or set to the Cooldown tag when this task runs.
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/BehaviorTree/Decorators/BTDecorator_SetTagCooldown.h