Unreal Engine 5.6 C++ API: TBulkDataScopedReadLock< ElementType > Class Template Reference
TBulkDataScopedReadLock< ElementType > Class Template Reference
Locks the given bulkdata object for read access.
#include "BulkDataScopedLock.h"
Public Member Functions
TBulkDataScopedReadLock (const TBulkData< ElementType > &InBulkData)
~TBulkDataScopedReadLock ()
int64 GetAllocatedSize () const
Returns the length of the bulkdata payload in bytes.
const ElementType * GetData () const
Returns a raw pointer to the bulkdata payload.
TConstArrayView64< ElementType > GetView () const
Returns the bulkdata payload wrapped in a TConstArrayView64 for added safety.
int64 Num () const
Returns the number of elements in the bulkdata payload.
UE_NONCOPYABLE (TBulkDataScopedReadLock)
Private Attributes
const TBulkData< ElementType > & BulkData
const ElementType * Data
Detailed Description
template<typename ElementType>
class TBulkDataScopedReadLock< ElementType >
Locks the given bulkdata object for read access.
Definition at line 15 of file BulkDataScopedLock.h.
Constructor & Destructor Documentation
TBulkDataScopedReadLock()
template<typename ElementType> TBulkDataScopedReadLock< ElementType >::TBulkDataScopedReadLock (const TBulkData< ElementType > & InBulkData) inline
Definition at line 20 of file BulkDataScopedLock.h.
References BulkData, Data, and FBulkData::LockReadOnly().
Referenced by UE_NONCOPYABLE().
~TBulkDataScopedReadLock()
template<typename ElementType> TBulkDataScopedReadLock< ElementType >::~TBulkDataScopedReadLock () inline
Definition at line 26 of file BulkDataScopedLock.h.
References BulkData.
Member Function Documentation
GetAllocatedSize()
template<typename ElementType> int64 TBulkDataScopedReadLock< ElementType >::GetAllocatedSize () const inline
Returns the length of the bulkdata payload in bytes.
Definition at line 38 of file BulkDataScopedLock.h.
References BulkData.
GetData()
template<typename ElementType> const ElementType * TBulkDataScopedReadLock< ElementType >::GetData () const inline
Returns a raw pointer to the bulkdata payload.
Definition at line 44 of file BulkDataScopedLock.h.
References Data.
GetView()
template<typename ElementType> TConstArrayView64< ElementType > TBulkDataScopedReadLock< ElementType >::GetView () const inline
Returns the bulkdata payload wrapped in a TConstArrayView64 for added safety.
Definition at line 50 of file BulkDataScopedLock.h.
References Data, and Num().
Num()
template<typename ElementType> int64 TBulkDataScopedReadLock< ElementType >::Num () const inline
Returns the number of elements in the bulkdata payload.
Definition at line 32 of file BulkDataScopedLock.h.
References BulkData.
Referenced by GetView().
UE_NONCOPYABLE()
template<typename ElementType> TBulkDataScopedReadLock< ElementType >::UE_NONCOPYABLE (TBulkDataScopedReadLock< ElementType >)
References TBulkDataScopedReadLock().
Field Documentation
BulkData
template<typename ElementType> const TBulkData<ElementType>& TBulkDataScopedReadLock< ElementType >::BulkData private
Definition at line 56 of file BulkDataScopedLock.h.
Referenced by TBulkDataScopedReadLock(), ~TBulkDataScopedReadLock(), GetAllocatedSize(), and Num().
Data
template<typename ElementType> const ElementType* TBulkDataScopedReadLock< ElementType >::Data private
Definition at line 57 of file BulkDataScopedLock.h.
Referenced by TBulkDataScopedReadLock(), GetData(), and GetView().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/BulkDataScopedLock.h