Unreal Engine 5.6 C++ API: UE::Geometry::FConvexDecomposition3 Class Reference
UE::Geometry::FConvexDecomposition3 Class Reference
#include "ConvexDecomposition3.h"
Data Structures
struct FConvexPart
struct FMergeSettings
struct FPreprocessMeshOptions
struct FProximity
Public Member Functions
FConvexDecomposition3 ()
FConvexDecomposition3 (const FDynamicMesh3 &SourceMesh, bool bMergeEdges=true)
FConvexDecomposition3 (const FDynamicMesh3 &SourceMesh, const FPreprocessMeshOptions &Options)
void Compact ()
GEOMETRYCORE_API void Compute (int32 NumOutputHulls, int32 NumAdditionalSplits=10, double ErrorTolerance=0.0, double MinThicknessTolerance=0, int32 MaxOutputHulls=-1, bool bOnlySplitIfNegativeSpaceCovered=false)
Compute a decomposition with the desired number of hulls Note: A future version of this function may replace NumOutputHulls with MaxOutputHulls, but this version keeps both parameters for compatibility / consistent behavior.
double ConvertDistanceToleranceToLocalSpace (double DistTolerance) const
double ConvertDistanceToleranceToLocalVolumeTolerance (double DistTolerance) const
const int32 CountMergedParts () const
GEOMETRYCORE_API void DeleteProximity (TArray< int32 > &&ToRemove, bool bDeleteMapReferences)
GEOMETRYCORE_API void FixHullOverlapsInNegativeSpace (double NegativeSpaceTolerance=UE_DOUBLE_KINDA_SMALL_NUMBER, double NegativeSpaceMinRadius=UE_DOUBLE_KINDA_SMALL_NUMBER)
FDynamicMesh3 GetHullMesh (int32 HullIdx) const
const int32 GetHullSourceID (int32 HullIdx) const
const FDynamicMesh3 & GetInternalMesh (int32 HullIdx) const
const FSphereCovering & GetNegativeSpace () const
TArray< FIndex3i > const & GetTriangles (int32 HullIdx) const
template<typename RealType>
TArray< TVector< RealType > > GetVertices (int32 HullIdx, bool bTransformedToOutput=true) const
GEOMETRYCORE_API void InitializeFromHulls (int32 NumHulls, TFunctionRef< double(int32)> HullVolumes, TFunctionRef< int32(int32)> HullNumVertices, TFunctionRef< FVector3d(int32, int32)> HullVertices, TArrayView< const TPair< int32, int32 > > Proximity)
Initialize from convex hulls allows the caller to only use the hull merging phase of the algorithm.
GEOMETRYCORE_API void InitializeFromIndexMesh (TArrayView< const FVector3f > Vertices, TArrayView< const FIntVector > Faces, bool bMergeEdges, int32 FaceVertexOffset=0)
Initialize convex decomposition with a triangle index mesh.
GEOMETRYCORE_API void InitializeFromIndexMesh (TArrayView< const FVector3f > Vertices, TArrayView< const FIntVector > Faces, const FPreprocessMeshOptions &Options, int32 FaceVertexOffset=0)
Initialize convex decomposition with a triangle index mesh.
GEOMETRYCORE_API void InitializeFromMesh (const FDynamicMesh3 &SourceMesh, bool bMergeEdges)
GEOMETRYCORE_API void InitializeFromMesh (const FDynamicMesh3 &SourceMesh, const FPreprocessMeshOptions &Options)
GEOMETRYCORE_API bool InitializeNegativeSpace (const FNegativeSpaceSampleSettings &Settings, TArrayView< const FVector3d > RequestedSamples=TArrayView< const FVector3d >())
Find negative space that should be protected.
GEOMETRYCORE_API void InitializeProximityFromDecompositionBoundingBoxOverlaps (double BoundsExpandByMinDimFactor, double BoundsExpandByMaxDimFactor, double MinBoundsExpand)
Create the proximity graph from the current decomposition, using bounding box overlaps.
bool IsInputSolid ()
Test whether the input mesh (after preprocessing) is solid.
GEOMETRYCORE_API int32 MergeBest (const FMergeSettings &Settings)
GEOMETRYCORE_API int32 MergeBest (int32 TargetNumParts, double ErrorTolerance=0, double MinThicknessTolerance=0, bool bAllowCompact=true, bool bRequireHullTriangles=false, int32 MaxOutputHulls=-1, const FSphereCovering *OptionalNegativeSpace=nullptr, const FTransform *OptionalTransformIntoNegativeSpace=nullptr)
int32 NumHulls () const
GEOMETRYCORE_API int32 SplitWorst (bool bCanSkipUnreliableGeoVolumes=false, double ErrorTolerance=0.0, bool bOnlySplitIfNegativeSpaceCovered=false, double MinSplitSizeInWorldSpace=-1)
GEOMETRYCORE_API void UpdateProximitiesAfterSplit (int32 SplitIdx, int32 NewIdxStart, FPlane3d CutPlane, int32 SecondSideIdxStart, double OrigHullVolume)
Static Public Member Functions
static GEOMETRYCORE_API bool ConvexPartVsSphereOverlap (const FConvexPart &Part, FVector3d Center, double Radius, const FTransform *TransformIntoSphereSpace=nullptr, double *OutDistanceSq=nullptr)
Data Fields
double BiasToRemoveTooThinParts = .1
bool bSplitDisconnectedComponents = true
bool bTreatAsSolid = true
double ConnectedComponentTolerance = 1e-3
double ConvexEdgeAngleMoreSamplesThreshold = 30
double ConvexEdgeAngleThreshold = 170
double CutLargestAxisErrorScale = .99
TIndirectArray< FConvexPart > Decomposition
TMultiMap< int32, int32 > DecompositionToProximity
int32 MaxConvexEdgePlanes = 50
double OnPlaneTolerance = 1e-7
TArray< FProximity > Proximities
double ProximityTolerance = 1e-3
int32 RestrictMergeSearchToLocalAfterTestNumConnections = -1
FTransformSRT3d ResultTransform = FTransformSRT3d::Identity()
Transform taking the result hull vertices back to the original space of the inputs; automatically applied by GetVertices()
double ThickenAfterHullFailure = 0
Private Member Functions
void InitNegativeSpaceConvexPartMapping ()
bool SplitWorstHelper (bool bCanSkipUnreliableGeoVolumes, double ErrorTolerance, bool bOnlySplitIfNegativeSpaceCovered, double MinSplitSizeInWorldSpace)
Private Attributes
FSphereCovering NegativeSpace
Detailed Description
Definition at line 305 of file ConvexDecomposition3.h.
Constructor & Destructor Documentation
FConvexDecomposition3() [1/3]
UE::Geometry::FConvexDecomposition3::FConvexDecomposition3 () inline
Definition at line 310 of file ConvexDecomposition3.h.
References ResultTransform.
FConvexDecomposition3() [2/3]
UE::Geometry::FConvexDecomposition3::FConvexDecomposition3 (const FDynamicMesh3 & SourceMesh, bool bMergeEdges = true) inline
Definition at line 314 of file ConvexDecomposition3.h.
References InitializeFromMesh().
FConvexDecomposition3() [3/3]
UE::Geometry::FConvexDecomposition3::FConvexDecomposition3 (const FDynamicMesh3 & SourceMesh, const FPreprocessMeshOptions & Options) inline
Definition at line 335 of file ConvexDecomposition3.h.
References InitializeFromMesh(), UE::Geometry::Options, and ThickenAfterHullFailure.
Member Function Documentation
Compact()
void UE::Geometry::FConvexDecomposition3::Compact () inline
Definition at line 539 of file ConvexDecomposition3.h.
References Decomposition.
Compute()
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::Compute (int32 NumOutputHulls, int32 NumAdditionalSplits = 10, double ErrorTolerance = 0.0, double MinThicknessTolerance = 0, int32 MaxOutputHulls = -1, bool bOnlySplitIfNegativeSpaceCovered = false)
Compute a decomposition with the desired number of hulls Note: A future version of this function may replace NumOutputHulls with MaxOutputHulls, but this version keeps both parameters for compatibility / consistent behavior.
Parameters
NumOutputHulls Number of convex hulls to use in the final convex decomposition
NumAdditionalSplits How far to go beyond the target number of hulls when initially the mesh into pieces – larger values will require more computation but can find better convex decompositions
ErrorTolerance Stop splitting when hulls have error less than this (expressed in cm; will be cubed for volumetric error). Overrides NumOutputHulls if specified
MinThicknessTolerance Optionally specify a minimum thickness (in cm) for convex parts; parts below this thickness will always be merged away. Overrides NumOutputHulls and ErrorTolerance when needed
MaxOutputHulls If > 0, maximum number of convex hulls to generate. Overrides ErrorTolerance and TargetNumParts when needed
bOnlySplitIfOverlapNegativeSpace If true, use NegativeSpace to guide splits, and only split parts that overlap negative space
ConvertDistanceToleranceToLocalSpace()
double UE::Geometry::FConvexDecomposition3::ConvertDistanceToleranceToLocalSpace (double DistTolerance) const inline
Definition at line 525 of file ConvexDecomposition3.h.
References ensure, TMathUtilConstants< double >::Epsilon, and ResultTransform.
Referenced by ConvertDistanceToleranceToLocalVolumeTolerance().
ConvertDistanceToleranceToLocalVolumeTolerance()
double UE::Geometry::FConvexDecomposition3::ConvertDistanceToleranceToLocalVolumeTolerance (double DistTolerance) const inline
Definition at line 517 of file ConvexDecomposition3.h.
References ConvertDistanceToleranceToLocalSpace().
ConvexPartVsSphereOverlap()
GEOMETRYCORE_API bool UE::Geometry::FConvexDecomposition3::ConvexPartVsSphereOverlap (const FConvexPart & Part, FVector3d Center, double Radius, const FTransform * TransformIntoSphereSpace = nullptr, double * OutDistanceSq = nullptr) static
CountMergedParts()
const int32 UE::Geometry::FConvexDecomposition3::CountMergedParts () const inline
Definition at line 609 of file ConvexDecomposition3.h.
References UE::Count, and Decomposition.
DeleteProximity()
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::DeleteProximity (TArray< int32 > && ToRemove, bool bDeleteMapReferences)
FixHullOverlapsInNegativeSpace()
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::FixHullOverlapsInNegativeSpace (double NegativeSpaceTolerance = UE_DOUBLE_KINDA_SMALL_NUMBER, double NegativeSpaceMinRadius = UE_DOUBLE_KINDA_SMALL_NUMBER)
References UE_DOUBLE_KINDA_SMALL_NUMBER.
GetHullMesh()
FDynamicMesh3 UE::Geometry::FConvexDecomposition3::GetHullMesh (int32 HullIdx) const inline
Definition at line 577 of file ConvexDecomposition3.h.
References UE::Geometry::FDynamicMesh3::AppendTriangle(), UE::Geometry::FDynamicMesh3::AppendVertex(), Decomposition, ResultTransform, and UE::Math::TVector< double >::ZeroVector.
GetHullSourceID()
const int32 UE::Geometry::FConvexDecomposition3::GetHullSourceID (int32 HullIdx) const inline
Definition at line 604 of file ConvexDecomposition3.h.
References Decomposition.
GetInternalMesh()
const FDynamicMesh3 & UE::Geometry::FConvexDecomposition3::GetInternalMesh (int32 HullIdx) const inline
Definition at line 599 of file ConvexDecomposition3.h.
References Decomposition.
GetNegativeSpace()
const FSphereCovering & UE::Geometry::FConvexDecomposition3::GetNegativeSpace () const inline
Definition at line 818 of file ConvexDecomposition3.h.
References NegativeSpace.
GetTriangles()
TArray< FIndex3i > const & UE::Geometry::FConvexDecomposition3::GetTriangles (int32 HullIdx) const inline
Returns
convex hull triangles
Definition at line 557 of file ConvexDecomposition3.h.
References Decomposition.
GetVertices()
template<typename RealType> TArray< TVector< RealType > > UE::Geometry::FConvexDecomposition3::GetVertices (int32 HullIdx, bool bTransformedToOutput = true) const inline
Definition at line 563 of file ConvexDecomposition3.h.
References Decomposition, ResultTransform, and UE::Geometry::Vertices.
InitializeFromHulls()
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::InitializeFromHulls (int32 NumHulls, TFunctionRef< double(int32)> HullVolumes, TFunctionRef< int32(int32)> HullNumVertices, TFunctionRef< FVector3d(int32, int32)> HullVertices, TArrayView< const TPair< int32, int32 > > Proximity)
Initialize from convex hulls allows the caller to only use the hull merging phase of the algorithm.
Parameters
NumHulls Number of convex hulls in the initial decomposition
HullVolumes Function from Hull Index -> Hull Volume
HullNumVertices Function from Hull Index -> Hull Vertex Count
HullVertices Function from Hull Index, Vertex Index -> Hull Vertex Position
Proximity All the local proximities for the hulls. Hulls will not be merged unless they are connected by this proximity graph.
References NumHulls().
InitializeFromIndexMesh() [1/2]
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::InitializeFromIndexMesh (TArrayView< const FVector3f > Vertices, TArrayView< const FIntVector > Faces, bool bMergeEdges, int32 FaceVertexOffset = 0)
Initialize convex decomposition with a triangle index mesh.
Parameters
Vertices Vertex buffer for mesh to decompose
Faces Triangle buffer for mesh to decompose
bMergeEdges Whether to attempt to weld matching edges before computing the convex hull; this can help the convex decomposition find better cutting planes for meshes that have boundaries e.g. due to seams
FaceVertexOffset Indices from the Faces array are optionally offset by this value. Useful e.g. to take slices of the multi-geometry vertex and face buffers of FGeometryCollection.
References UE::Geometry::Vertices.
InitializeFromIndexMesh() [2/2]
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::InitializeFromIndexMesh (TArrayView< const FVector3f > Vertices, TArrayView< const FIntVector > Faces, const FPreprocessMeshOptions & Options, int32 FaceVertexOffset = 0)
Initialize convex decomposition with a triangle index mesh.
Parameters
Vertices Vertex buffer for mesh to decompose
Faces Triangle buffer for mesh to decompose
Options Options for pre-processing the mesh before decomposition (e.g., to weld matching edges, thicken degenerate inputs, or to run a general pre-process lambda function)
FaceVertexOffset Indices from the Faces array are optionally offset by this value. Useful e.g. to take slices of the multi-geometry vertex and face buffers of FGeometryCollection.
References UE::Geometry::Options, and UE::Geometry::Vertices.
InitializeFromMesh() [1/2]
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::InitializeFromMesh (const FDynamicMesh3 & SourceMesh, bool bMergeEdges)
Referenced by FConvexDecomposition3(), and FConvexDecomposition3().
InitializeFromMesh() [2/2]
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::InitializeFromMesh (const FDynamicMesh3 & SourceMesh, const FPreprocessMeshOptions & Options)
References UE::Geometry::Options.
InitializeNegativeSpace()
GEOMETRYCORE_API bool UE::Geometry::FConvexDecomposition3::InitializeNegativeSpace (const FNegativeSpaceSampleSettings & Settings, TArrayView< const FVector3d > RequestedSamples = TArrayView< const FVector3d >())
Find negative space that should be protected.
Uses the mesh passed on construction or to InitializeFromMesh or InitializeFromIndexMesh
Parameters
Settings Settings to use to find the negative space
Returns
False on failure – e.g., if there was no mesh available
InitializeProximityFromDecompositionBoundingBoxOverlaps()
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::InitializeProximityFromDecompositionBoundingBoxOverlaps (double BoundsExpandByMinDimFactor, double BoundsExpandByMaxDimFactor, double MinBoundsExpand)
Create the proximity graph from the current decomposition, using bounding box overlaps.
To consider non-overlapping proximity, the bounding boxes can be expanded by a factor of their own size or by an absolute amount.
Parameters
BoundsExpandByMinDimFactor Part bounds will be expanded by at least this factor of their own min dimension, before finding overlaps
BoundsExpandByMaxDimFactor Part bounds will be expanded by at least this factor of their own max dimension, before finding overlaps
MinBoundsExpand Part bounds will be expanded by at least this fixed amount, before finding overlaps
InitNegativeSpaceConvexPartMapping()
void UE::Geometry::FConvexDecomposition3::InitNegativeSpaceConvexPartMapping () private
IsInputSolid()
bool UE::Geometry::FConvexDecomposition3::IsInputSolid () inline
Test whether the input mesh (after preprocessing) is solid.
Must be called after initialization, but before decomposition is computed.
Definition at line 344 of file ConvexDecomposition3.h.
References Decomposition, ensureMsgf, and TEXT.
MergeBest() [1/2]
GEOMETRYCORE_API int32 UE::Geometry::FConvexDecomposition3::MergeBest (const FMergeSettings & Settings)
MergeBest() [2/2]
GEOMETRYCORE_API int32 UE::Geometry::FConvexDecomposition3::MergeBest (int32 TargetNumParts, double ErrorTolerance = 0, double MinThicknessTolerance = 0, bool bAllowCompact = true, bool bRequireHullTriangles = false, int32 MaxOutputHulls = -1, const FSphereCovering * OptionalNegativeSpace = nullptr, const FTransform * OptionalTransformIntoNegativeSpace = nullptr)
NumHulls()
int32 UE::Geometry::FConvexDecomposition3::NumHulls () const inline
Definition at line 551 of file ConvexDecomposition3.h.
References Decomposition.
Referenced by InitializeFromHulls().
SplitWorst()
GEOMETRYCORE_API int32 UE::Geometry::FConvexDecomposition3::SplitWorst (bool bCanSkipUnreliableGeoVolumes = false, double ErrorTolerance = 0.0, bool bOnlySplitIfNegativeSpaceCovered = false, double MinSplitSizeInWorldSpace = -1)
SplitWorstHelper()
bool UE::Geometry::FConvexDecomposition3::SplitWorstHelper (bool bCanSkipUnreliableGeoVolumes, double ErrorTolerance, bool bOnlySplitIfNegativeSpaceCovered, double MinSplitSizeInWorldSpace) private
UpdateProximitiesAfterSplit()
GEOMETRYCORE_API void UE::Geometry::FConvexDecomposition3::UpdateProximitiesAfterSplit (int32 SplitIdx, int32 NewIdxStart, FPlane3d CutPlane, int32 SecondSideIdxStart, double OrigHullVolume)
Field Documentation
BiasToRemoveTooThinParts
double UE::Geometry::FConvexDecomposition3::BiasToRemoveTooThinParts = .1
Definition at line 422 of file ConvexDecomposition3.h.
bSplitDisconnectedComponents
bool UE::Geometry::FConvexDecomposition3::bSplitDisconnectedComponents = true
Definition at line 429 of file ConvexDecomposition3.h.
bTreatAsSolid
bool UE::Geometry::FConvexDecomposition3::bTreatAsSolid = true
Definition at line 432 of file ConvexDecomposition3.h.
ConnectedComponentTolerance
double UE::Geometry::FConvexDecomposition3::ConnectedComponentTolerance = 1e-3
Definition at line 408 of file ConvexDecomposition3.h.
ConvexEdgeAngleMoreSamplesThreshold
double UE::Geometry::FConvexDecomposition3::ConvexEdgeAngleMoreSamplesThreshold = 30
Definition at line 416 of file ConvexDecomposition3.h.
ConvexEdgeAngleThreshold
double UE::Geometry::FConvexDecomposition3::ConvexEdgeAngleThreshold = 170
Definition at line 418 of file ConvexDecomposition3.h.
CutLargestAxisErrorScale
double UE::Geometry::FConvexDecomposition3::CutLargestAxisErrorScale = .99
Definition at line 413 of file ConvexDecomposition3.h.
Decomposition
TIndirectArray<FConvexPart> UE::Geometry::FConvexDecomposition3::Decomposition
Definition at line 731 of file ConvexDecomposition3.h.
Referenced by Compact(), CountMergedParts(), GetHullMesh(), GetHullSourceID(), GetInternalMesh(), GetTriangles(), GetVertices(), IsInputSolid(), and NumHulls().
DecompositionToProximity
TMultiMap<int32, int32> UE::Geometry::FConvexDecomposition3::DecompositionToProximity
Definition at line 786 of file ConvexDecomposition3.h.
MaxConvexEdgePlanes
int32 UE::Geometry::FConvexDecomposition3::MaxConvexEdgePlanes = 50
Definition at line 426 of file ConvexDecomposition3.h.
NegativeSpace
FSphereCovering UE::Geometry::FConvexDecomposition3::NegativeSpace private
Definition at line 829 of file ConvexDecomposition3.h.
Referenced by GetNegativeSpace().
OnPlaneTolerance
double UE::Geometry::FConvexDecomposition3::OnPlaneTolerance = 1e-7
Definition at line 410 of file ConvexDecomposition3.h.
Proximities
TArray<FProximity> UE::Geometry::FConvexDecomposition3::Proximities
Definition at line 783 of file ConvexDecomposition3.h.
ProximityTolerance
double UE::Geometry::FConvexDecomposition3::ProximityTolerance = 1e-3
Definition at line 406 of file ConvexDecomposition3.h.
RestrictMergeSearchToLocalAfterTestNumConnections
int32 UE::Geometry::FConvexDecomposition3::RestrictMergeSearchToLocalAfterTestNumConnections = -1
Definition at line 440 of file ConvexDecomposition3.h.
ResultTransform
FTransformSRT3d UE::Geometry::FConvexDecomposition3::ResultTransform = FTransformSRT3d::Identity()
Transform taking the result hull vertices back to the original space of the inputs; automatically applied by GetVertices()
Definition at line 734 of file ConvexDecomposition3.h.
Referenced by FConvexDecomposition3(), ConvertDistanceToleranceToLocalSpace(), GetHullMesh(), and GetVertices().
ThickenAfterHullFailure
double UE::Geometry::FConvexDecomposition3::ThickenAfterHullFailure = 0
Definition at line 436 of file ConvexDecomposition3.h.
Referenced by FConvexDecomposition3().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/CompGeom/ConvexDecomposition3.h