Unreal Engine 5.6 C++ API: UE::Core::Private::TMutableView< T > Class Template Reference
UE::Core::Private::TMutableView< T > Class Template Reference
#include "ObjectPtr.h"
Public Types
using TraitType = UE::Core::Private::TMutableViewTraits<T, ViewType>
using ViewType = typename TObjectPtrDecayTypeOf<T>::Type
Public Member Functions
TMutableView (const TMutableView &)=delete
TMutableView (T &Value)
TMutableView (TMutableView &&)=delete
~TMutableView ()
operator ViewType & () const
TMutableView & operator= (const TMutableView &)=delete
TMutableView & operator= (TMutableView &&)=delete
Private Attributes
ViewType * View
Detailed Description
template<typename T>
class UE::Core::Private::TMutableView< T >
Definition at line 1603 of file ObjectPtr.h.
Member Typedef Documentation
TraitType
template<typename T> using UE::Core::Private::TMutableView< T >::TraitType = UE::Core::Private::TMutableViewTraits<T, ViewType>
Definition at line 1607 of file ObjectPtr.h.
ViewType
template<typename T> using UE::Core::Private::TMutableView< T >::ViewType = typename TObjectPtrDecayTypeOf<T>::Type
Definition at line 1606 of file ObjectPtr.h.
Constructor & Destructor Documentation
TMutableView() [1/3]
template<typename T> UE::Core::Private::TMutableView< T >::TMutableView (T & Value) inline explicit
Definition at line 1609 of file ObjectPtr.h.
References Value, and View.
Referenced by TMutableView(), TMutableView(), operator=(), and operator=().
~TMutableView()
template<typename T> UE::Core::Private::TMutableView< T >::~TMutableView () inline
Definition at line 1614 of file ObjectPtr.h.
References View.
TMutableView() [2/3]
template<typename T> UE::Core::Private::TMutableView< T >::TMutableView (const TMutableView< T > &) delete
References TMutableView().
TMutableView() [3/3]
template<typename T> UE::Core::Private::TMutableView< T >::TMutableView (TMutableView< T > &&) delete
References TMutableView().
Member Function Documentation
operator ViewType &()
template<typename T> UE::Core::Private::TMutableView< T >::operator ViewType & () const inline
Definition at line 1624 of file ObjectPtr.h.
References View.
operator=() [1/2]
template<typename T> TMutableView & UE::Core::Private::TMutableView< T >::operator= (const TMutableView< T > &) delete
References TMutableView().
operator=() [2/2]
template<typename T> TMutableView & UE::Core::Private::TMutableView< T >::operator= (TMutableView< T > &&) delete
References TMutableView().
Field Documentation
View
template<typename T> ViewType* UE::Core::Private::TMutableView< T >::View private
Definition at line 1630 of file ObjectPtr.h.
Referenced by TMutableView(), ~TMutableView(), and operator ViewType &().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ObjectPtr.h