Unreal Engine 5.6 C++ API: UE::Geometry::FVertexLinearization Class Reference
UE::Geometry::FVertexLinearization Class Reference
Used to linearize the VtxIds in a mesh as a single array and allow mapping from array offset to mesh VtxId.
#include "MeshLinearization.h"
Public Member Functions
FVertexLinearization ()=default
template<typename MeshType>
FVertexLinearization (const MeshType &Mesh, bool bRemapBoundary=true)
int32 NumBoundaryVerts () const
int32 NumVerts () const
template<typename MeshType>
void Reset (const MeshType &Mesh, bool bRemapBoundary=true)
Public Member Functions inherited from UE::Geometry::FElementLinearization
FElementLinearization ()=default
void Empty ()
int32 GetId (int32 Index) const
int32 GetIndex (int32 Id) const
bool IsValidId (int32 Id) const
bool IsValidIndex (int32 Index) const
int32 MaxId () const
int32 NumIds () const
int32 NumIndices () const
template<typename IterableType>
void Populate (const int32 MaxId, const int32 Count, IterableType Iterable)
const TArray< int32 > & ToId () const
const TArray< int32 > & ToIndex () const
Private Member Functions
FVertexLinearization (const FVertexLinearization &)
template<typename MeshType>
void RemapBoundaryVerts (const MeshType &DynamicMesh)
Private Attributes
int32 NumBndryVerts = 0
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::FElementLinearization
TArray< int32 > ToIdMap
TArray< int32 > ToIndexMap
Detailed Description
Used to linearize the VtxIds in a mesh as a single array and allow mapping from array offset to mesh VtxId.
Generally, the array offset will correspond to a matrix row when forming a Laplacian. The last NumBoundaryVerts are the boundary verts. This may be zero.
Definition at line 22 of file MeshLinearization.h.
Constructor & Destructor Documentation
FVertexLinearization() [1/3]
UE::Geometry::FVertexLinearization::FVertexLinearization () default
Referenced by FVertexLinearization().
FVertexLinearization() [2/3]
template<typename MeshType> UE::Geometry::FVertexLinearization::FVertexLinearization (const MeshType & Mesh, bool bRemapBoundary = true) inline
Parameters
Mesh The mesh to lineralize.
bRemapBoundary If true, will move the boundary vertices to the end of the arrays and record the number of boundary vertices.
Definition at line 33 of file MeshLinearization.h.
References UE::Geometry::Mesh, and Reset.
FVertexLinearization() [3/3]
UE::Geometry::FVertexLinearization::FVertexLinearization (const FVertexLinearization &) private
References FVertexLinearization().
Member Function Documentation
NumBoundaryVerts()
int32 UE::Geometry::FVertexLinearization::NumBoundaryVerts () const inline
Definition at line 52 of file MeshLinearization.h.
References NumBndryVerts.
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), and UE::MeshDeformation::ConstructValenceWeightedLaplacian().
NumVerts()
int32 UE::Geometry::FVertexLinearization::NumVerts () const inline
Definition at line 50 of file MeshLinearization.h.
References UE::Geometry::FElementLinearization::NumIds().
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), UE::MeshDeformation::ConstructValenceWeightedLaplacian(), and RemapBoundaryVerts().
RemapBoundaryVerts()
template<typename MeshType> void UE::Geometry::FVertexLinearization::RemapBoundaryVerts (const MeshType & DynamicMesh) inline private
Definition at line 58 of file MeshLinearization.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Append(), UE::Geometry::FDynamicMesh3::InvalidID, TArray< InElementType, InAllocatorType >::Num(), NumBndryVerts, NumVerts(), TArray< InElementType, InAllocatorType >::Reserve(), Swap, UE::Geometry::FElementLinearization::ToIdMap, and UE::Geometry::FElementLinearization::ToIndexMap.
Referenced by Reset().
Reset()
template<typename MeshType> void UE::Geometry::FVertexLinearization::Reset (const MeshType & Mesh, bool bRemapBoundary = true) inline
Definition at line 39 of file MeshLinearization.h.
References UE::Geometry::FElementLinearization::Empty(), UE::Geometry::Mesh, UE::Geometry::FElementLinearization::Populate(), and RemapBoundaryVerts().
Field Documentation
NumBndryVerts
int32 UE::Geometry::FVertexLinearization::NumBndryVerts = 0 private
Definition at line 109 of file MeshLinearization.h.
Referenced by NumBoundaryVerts(), and RemapBoundaryVerts().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Solvers/MeshLinearization.h