Unreal Engine 5.6 C++ API: IKeyArea Class Reference
IKeyArea Class Reference
Interface that should be implemented for the UI portion of a key area within a section.
#include "IKeyArea.h"
Public Member Functions
IKeyArea (TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel, const FCurveModelID &InCurveId)
Constructor.
FKeyHandle AddOrUpdateKey (FFrameNumber Time, const FGuid &ObjectBindingID, ISequencer &InSequencer)
Add a key at the specified time with the current value of the channel, updating an existing key if possible.
bool CanCreateKeyEditor () const
Check whether this key area can create an editor on the sequencer node tree.
void CopyKeys (FMovieSceneClipboardBuilder &ClipboardBuilder, TArrayView< const FKeyHandle > KeyMask) const
Copy all the keys specified in KeyMask to the specified clipboard.
TUniquePtr< FCurveModel > CreateCurveEditorModel (TSharedRef< ISequencer > InSequencer) const
Create a new model for this key area that can be used on the curve editor interface.
TSharedRef< SWidget > CreateKeyEditor (TWeakPtr< ISequencer > Sequencer, const FGuid &ObjectBindingID)
Create an editor on the sequencer node tree.
void DeleteKeys (TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime)
Delete the specified keys.
int32 DrawExtra (const FSequencerChannelPaintArgs &PaintArgs, int32 LayerId) const
Draw additional content in addition to keys for a particular IKeyArea.
void DrawKeys (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< FKeyDrawParams > OutKeyDrawParams)
Gather key drawing information for the specified key handles.
FKeyHandle DuplicateKey (FKeyHandle InKeyHandle) const
Duplicate the key represented by the specified handle.
ISequencerChannelInterface * FindChannelEditorInterface () const
Locate the sequencer channel interface for this key area's channel.
const FMovieSceneChannelHandle & GetChannel () const
Access the channel handle that this key area represents.
FName GetChannelTypeName () const
Access the channel type identifier for the channel that this key area wraps.
TOptional< FLinearColor > GetColor () const
Get the color of this channel that should be drawn underneath its keys.
FORCEINLINE void GetKeyHandles (TArray< FKeyHandle > &OutHandles, const TRange< FFrameNumber > &WithinRange=TRange< FFrameNumber >::All()) const
Get all key handles that exist within the given time range.
void GetKeyInfo (TArray< FKeyHandle > *OutHandles, TArray< FFrameNumber > *OutTimes, const TRange< FFrameNumber > &WithinRange=TRange< FFrameNumber >::All()) const
Populate the specified handle and/or time arrays with information pertaining to keys that exist within the given range.
TSharedPtr< FStructOnScope > GetKeyStruct (FKeyHandle KeyHandle) const
Get a key structure for editing a value on this channel.
FORCEINLINE FFrameNumber GetKeyTime (FKeyHandle InKeyHandle) const
Get the time of the key represented by the specified handle.
FORCEINLINE void GetKeyTimes (TArray< FFrameNumber > &OutTimes, const TRange< FFrameNumber > &WithinRange=TRange< FFrameNumber >::All()) const
Get all key times that exist within the given time range.
void GetKeyTimes (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< FFrameNumber > OutTimes) const
Get the times of every key represented by the specified handles.
FName GetName () const
Get this key area's name.
UObject * GetOwningObject () const
Access object that owns the channel this key area represents.
UMovieSceneSection * GetOwningSection () const
Access section that owns the channel this key area represents.
FRichCurve * GetRichCurve () const
TSharedPtr< ISequencerSection > GetSectionInterface () const
Access section editor interface.
TArray< FKeyHandle > PasteKeys (const FMovieSceneClipboardKeyTrack &KeyTrack, const FMovieSceneClipboardEnvironment &SrcEnvironment, const FSequencerPasteEnvironment &DstEnvironment)
Paste the specified key track into this key area.
void Reinitialize (TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel)
Reinitialize this key area with a new channel.
FMovieSceneChannel * ResolveChannel () const
Resolve this key area's channel handle.
void SetKeyTime (FKeyHandle InKeyHandle, FFrameNumber InKeyTime) const
Set the time of the key with the specified handle.
void SetKeyTimes (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< const FFrameNumber > InKeyTimes) const
Set the times of the each key with the specified handles.
void SetName (FName InName)
Set this key area's name.
bool ShouldShowCurve () const
Check whether we should show this key area's curve on its channel UI or not.
Public Member Functions inherited from TSharedFromThis< IKeyArea >
TSharedRef< IKeyArea, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IKeyArea, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
uint32 TreeSerialNumber
Serial number of the node tree from the last time this key area was seen.
Private Attributes
FMovieSceneChannelHandle ChannelHandle
Handle to the channel itself.
FName ChannelName
The name of this channel.
TOptional< FLinearColor > Color
The color of this channel that should be drawn underneath its keys.
const TPimplPtr< FCurveModelID > CurveModelID
Consistent ID that is reused and injected into the curve model every time it is created.
FText DisplayText
The display text of this channel.
TOptional< FTrackInstancePropertyBindings > PropertyBindings
Optional property bindings class where the section resides inside a UMovieScenePropertyTrack.
TWeakPtr< ISequencerSection > WeakSection
A weak pointer back to the originating section interface that owns this channel.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IKeyArea >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IKeyArea >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Interface that should be implemented for the UI portion of a key area within a section.
Definition at line 40 of file IKeyArea.h.
Constructor & Destructor Documentation
IKeyArea()
IKeyArea::IKeyArea (TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel, const FCurveModelID & InCurveId)
Constructor.
Parameters
InSection The section that owns the channel that this key area represents
InChannel Handle to the channel this key area represents
Member Function Documentation
AddOrUpdateKey()
FKeyHandle IKeyArea::AddOrUpdateKey (FFrameNumber Time, const FGuid & ObjectBindingID, ISequencer & InSequencer)
Add a key at the specified time with the current value of the channel, updating an existing key if possible.
Parameters
Time The time at which a key should be added (or updated)
ObjectBindingID The object binding ID this key area's track is bound to
InSequencer The currently active sequencer
Returns
A handle to the key that was added or updated
References Time.
CanCreateKeyEditor()
bool IKeyArea::CanCreateKeyEditor () const
Check whether this key area can create an editor on the sequencer node tree.
CopyKeys()
void IKeyArea::CopyKeys (FMovieSceneClipboardBuilder & ClipboardBuilder, TArrayView< const FKeyHandle > KeyMask) const
Copy all the keys specified in KeyMask to the specified clipboard.
Parameters
ClipboardBuilder The structure responsible for building clipboard information for each key
KeyMask A specific set of keys to copy
CreateCurveEditorModel()
TUniquePtr< FCurveModel > IKeyArea::CreateCurveEditorModel (TSharedRef< ISequencer > InSequencer) const
Create a new model for this key area that can be used on the curve editor interface.
Returns
(Optional) A new model to be added to a curve editor
CreateKeyEditor()
TSharedRef< SWidget > IKeyArea::CreateKeyEditor (TWeakPtr< ISequencer > Sequencer, const FGuid & ObjectBindingID)
Create an editor on the sequencer node tree.
Parameters
Sequencer The currently active sequencer
ObjectBindingID The ID of the object this key area's track is bound to
Returns
The editor widget to display on the key area's node
DeleteKeys()
void IKeyArea::DeleteKeys (TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime)
Delete the specified keys.
If all keys are removed, the current value at that time will be set as the default value for the channel
Parameters
Channel The channel to remove the keys from
InHandles The key handles to delete
InTime The time at which to evaluate for the default value if there are no keys remaining
References InTime.
DrawExtra()
int32 IKeyArea::DrawExtra (const FSequencerChannelPaintArgs & PaintArgs, int32 LayerId) const
Draw additional content in addition to keys for a particular IKeyArea.
Parameters
PaintArgs Paint arguments containing the draw element list, time-to-pixel converter and other structures
LayerId The slate layer to paint onto
Returns
The new slate layer ID for subsequent elements to paint onto
DrawKeys()
void IKeyArea::DrawKeys (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< FKeyDrawParams > OutKeyDrawParams)
Gather key drawing information for the specified key handles.
Parameters
InKeyHandles An array of handles to draw
OutKeyDrawParams Pre-sized array view of parameters to populate with each key
DuplicateKey()
FKeyHandle IKeyArea::DuplicateKey (FKeyHandle InKeyHandle) const
Duplicate the key represented by the specified handle.
Parameters
InKeyHandle A handle to the key to duplicate
Returns
A handle to the new duplicated key
FindChannelEditorInterface()
ISequencerChannelInterface * IKeyArea::FindChannelEditorInterface () const
Locate the sequencer channel interface for this key area's channel.
Note
: Channel interfaces are registered via ISequencerModule::RegisterChannelInterface
Returns
The channel interface, or nullptr if one was not found
GetChannel()
const FMovieSceneChannelHandle & IKeyArea::GetChannel () const inline
Access the channel handle that this key area represents.
Returns
The (potentially invalid) channel handle
Definition at line 88 of file IKeyArea.h.
References ChannelHandle.
GetChannelTypeName()
FName IKeyArea::GetChannelTypeName () const inline
Access the channel type identifier for the channel that this key area wraps.
Returns
The name of the channel type
Definition at line 78 of file IKeyArea.h.
References ChannelHandle.
GetColor()
TOptional< FLinearColor > IKeyArea::GetColor () const inline
Get the color of this channel that should be drawn underneath its keys.
Returns
(Optional) This channel's color
Definition at line 119 of file IKeyArea.h.
References Color.
GetKeyHandles()
FORCEINLINE void IKeyArea::GetKeyHandles (TArray< FKeyHandle > & OutHandles, const TRange< FFrameNumber > & WithinRange = TRange<FFrameNumber>::All()) const inline
Get all key handles that exist within the given time range.
Parameters
OutHandles An array to populate with key handles, any key handles will be appended to this array
WithinRange (Optional) A predicate range to search within
Definition at line 210 of file IKeyArea.h.
References TRange< ElementType >::All(), FORCEINLINE, and GetKeyInfo().
GetKeyInfo()
void IKeyArea::GetKeyInfo (TArray< FKeyHandle > * OutHandles, TArray< FFrameNumber > * OutTimes, const TRange< FFrameNumber > & WithinRange = TRange< FFrameNumber >::All()) const
Populate the specified handle and/or time arrays with information pertaining to keys that exist within the given range.
Parameters
OutHandles (Optional) An array to populate with key handles, any key handles will be appended to this array
OutTimes (Optional) An array to populate with key times, any key times will be appended to this array
WithinRange (Optional) A predicate range to search within
References TRange< ElementType >::All().
Referenced by GetKeyHandles(), and GetKeyTimes().
GetKeyStruct()
TSharedPtr< FStructOnScope > IKeyArea::GetKeyStruct (FKeyHandle KeyHandle) const
Get a key structure for editing a value on this channel.
Returns
The key structure for this channel, or nullptr
GetKeyTime()
FORCEINLINE FFrameNumber IKeyArea::GetKeyTime (FKeyHandle InKeyHandle) const inline
Get the time of the key represented by the specified handle.
Parameters
InKeyHandle A handle to the key to query for
Returns
The key's time, or TNumericLimits<int32>::Lowest() if the handle was not valid
Definition at line 189 of file IKeyArea.h.
References FORCEINLINE, GetKeyTimes(), and Time.
GetKeyTimes() [1/2]
FORCEINLINE void IKeyArea::GetKeyTimes (TArray< FFrameNumber > & OutTimes, const TRange< FFrameNumber > & WithinRange = TRange<FFrameNumber>::All()) const inline
Get all key times that exist within the given time range.
Parameters
OutTimes An array to populate with key times, any key times will be appended to this array
WithinRange (Optional) A predicate range to search within
Definition at line 221 of file IKeyArea.h.
References TRange< ElementType >::All(), FORCEINLINE, and GetKeyInfo().
GetKeyTimes() [2/2]
void IKeyArea::GetKeyTimes (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< FFrameNumber > OutTimes) const
Get the times of every key represented by the specified handles.
Parameters
InKeyHandles A handle to the key to query for
OutTimes A pre-sized array view to populate with key times
Referenced by GetKeyTime().
GetName()
FName IKeyArea::GetName () const
Get this key area's name.
Returns
This key area's name
GetOwningObject()
UObject * IKeyArea::GetOwningObject () const
Access object that owns the channel this key area represents.
Note
: this may return the same as GetOwningSection (the common case)
Returns
The owning object, or nullptr if it has been destroyed
GetOwningSection()
UMovieSceneSection * IKeyArea::GetOwningSection () const
Access section that owns the channel this key area represents.
Returns
The owning section, or nullptr if it has been destroyed
GetRichCurve()
FRichCurve * IKeyArea::GetRichCurve () const inline
Definition at line 300 of file IKeyArea.h.
GetSectionInterface()
TSharedPtr< ISequencerSection > IKeyArea::GetSectionInterface () const
Access section editor interface.
Returns
The owning section interface, or nullptr if it has been destroyed
PasteKeys()
TArray< FKeyHandle > IKeyArea::PasteKeys (const FMovieSceneClipboardKeyTrack & KeyTrack, const FMovieSceneClipboardEnvironment & SrcEnvironment, const FSequencerPasteEnvironment & DstEnvironment)
Paste the specified key track into this key area.
Parameters
KeyTrack The source clipboard data to paste
SrcEnvironment The environment the source data was copied from
DstEnvironment The environment we're pasting into
Reinitialize()
void IKeyArea::Reinitialize (TWeakPtr< ISequencerSection > InSection, FMovieSceneChannelHandle InChannel)
Reinitialize this key area with a new channel.
Parameters
InSection The section that owns the channel that this key area represents
InChannel Handle to the channel this key area represents
ResolveChannel()
FMovieSceneChannel * IKeyArea::ResolveChannel () const
Resolve this key area's channel handle.
Returns
A (potentially invalid) interface to this key area's channel
SetKeyTime()
void IKeyArea::SetKeyTime (FKeyHandle InKeyHandle, FFrameNumber InKeyTime) const inline
Set the time of the key with the specified handle.
Parameters
InKeyHandle The key handle to set
InKeyTime The time to set the key to
Definition at line 241 of file IKeyArea.h.
References SetKeyTimes().
SetKeyTimes()
void IKeyArea::SetKeyTimes (TArrayView< const FKeyHandle > InKeyHandles, TArrayView< const FFrameNumber > InKeyTimes) const
Set the times of the each key with the specified handles.
Parameters
InKeyHandles An array of handles that should have their time set to times in the corresponding InKeyTimes array
InKeyTimes Array of times to set to, one per key handle. Must match the size of InKeyHandles
Referenced by SetKeyTime().
SetName()
void IKeyArea::SetName (FName InName)
Set this key area's name.
Parameters
InName This key area's name
References InName.
ShouldShowCurve()
bool IKeyArea::ShouldShowCurve () const
Check whether we should show this key area's curve on its channel UI or not.
Returns
True to show the curve, false otherwise
Field Documentation
ChannelHandle
FMovieSceneChannelHandle IKeyArea::ChannelHandle private
Handle to the channel itself.
Definition at line 329 of file IKeyArea.h.
Referenced by GetChannel(), and GetChannelTypeName().
ChannelName
FName IKeyArea::ChannelName private
The name of this channel.
Definition at line 338 of file IKeyArea.h.
Color
TOptional<FLinearColor> IKeyArea::Color private
The color of this channel that should be drawn underneath its keys.
Definition at line 335 of file IKeyArea.h.
Referenced by GetColor().
CurveModelID
const TPimplPtr<FCurveModelID> IKeyArea::CurveModelID private
Consistent ID that is reused and injected into the curve model every time it is created.
Pimpl to avoid public build.cs dependency.
Definition at line 344 of file IKeyArea.h.
DisplayText
FText IKeyArea::DisplayText private
The display text of this channel.
Definition at line 341 of file IKeyArea.h.
PropertyBindings
TOptional<FTrackInstancePropertyBindings> IKeyArea::PropertyBindings private
Optional property bindings class where the section resides inside a UMovieScenePropertyTrack.
Definition at line 332 of file IKeyArea.h.
TreeSerialNumber
uint32 IKeyArea::TreeSerialNumber
Serial number of the node tree from the last time this key area was seen.
Definition at line 45 of file IKeyArea.h.
WeakSection
TWeakPtr<ISequencerSection> IKeyArea::WeakSection private
A weak pointer back to the originating section interface that owns this channel.
Definition at line 326 of file IKeyArea.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/IKeyArea.h