Unreal Engine 5.6 C++ API: TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Types
using FFuncPtr = RetValType(*)(ParamTypes..., VarTypes...)
Public Member Functions
template<typename... InVarTypes>
TBaseStaticDelegateInstance (FFuncPtr InStaticFuncPtr, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst UserObject) const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
Private Attributes
FFuncPtr StaticFuncPtr
Additional Inherited Members
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Detailed Description
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes>
class TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >
Definition at line 707 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 711 of file DelegateInstancesImpl.h.
FFuncPtr
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::FFuncPtr = RetValType(*)(ParamTypes..., VarTypes...)
Definition at line 714 of file DelegateInstancesImpl.h.
Super
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 710 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseStaticDelegateInstance()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> template<typename... InVarTypes> TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseStaticDelegateInstance (FFuncPtr InStaticFuncPtr, InVarTypes &&... Vars) inline explicit
Definition at line 717 of file DelegateInstancesImpl.h.
References check, Forward(), and StaticFuncPtr.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 776 of file DelegateInstancesImpl.h.
References TBaseStaticDelegateInstance().
CreateCopy() [2/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 781 of file DelegateInstancesImpl.h.
References TBaseStaticDelegateInstance().
CreateCopy() [3/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 771 of file DelegateInstancesImpl.h.
References TBaseStaticDelegateInstance().
Execute()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> RetValType TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 786 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and StaticFuncPtr.
ExecuteIfSafe()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 794 of file DelegateInstancesImpl.h.
References checkSlow, Forward(), Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and StaticFuncPtr.
GetBoundProgramCounterForTimerManager()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> uint64 TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 745 of file DelegateInstancesImpl.h.
References StaticFuncPtr.
GetObjectForTimerManager()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> const void * TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 740 of file DelegateInstancesImpl.h.
GetUObject()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UObject * TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetUObject () const inline final
Definition at line 735 of file DelegateInstancesImpl.h.
HasSameObject()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::HasSameObject (FDelegateUserObjectConst UserObject) const inline final
Definition at line 755 of file DelegateInstancesImpl.h.
IsSafeToExecute()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 761 of file DelegateInstancesImpl.h.
Field Documentation
StaticFuncPtr
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> FFuncPtr TBaseStaticDelegateInstance< RetValType(ParamTypes...), UserPolicy, VarTypes... >::StaticFuncPtr private
Definition at line 807 of file DelegateInstancesImpl.h.
Referenced by TBaseStaticDelegateInstance(), Execute(), ExecuteIfSafe(), and GetBoundProgramCounterForTimerManager().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstancesImpl.h