Unreal Engine 5.6 C++ API: FDisplayClusterWarpEye Class Reference
FDisplayClusterWarpEye Class Reference
WarpBlend eye data.
#include "DisplayClusterWarpEye.h"
Public Member Functions
FDisplayClusterWarpEye (const TSharedPtr< IDisplayClusterViewport, ESPMode::ThreadSafe > &InViewport, const uint32 InContextNum)
IDisplayClusterViewport * GetViewport () const
bool IsEqual (const FDisplayClusterWarpEye &InEye, float Precision) const
Public Member Functions inherited from TSharedFromThis< FDisplayClusterWarpEye, ESPMode::ThreadSafe >
TSharedRef< FDisplayClusterWarpEye, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDisplayClusterWarpEye, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
const uint32 ContextNum
TOptional< FVector > OverrideViewDirection
TOptional< FVector > OverrideViewTarget
FDisplayClusterWarpViewPoint ViewPoint
const TWeakPtr< IDisplayClusterViewport, ESPMode::ThreadSafe > ViewportWeakPtr
TSharedPtr< IDisplayClusterWarpPolicy, ESPMode::ThreadSafe > WarpPolicy
FTransform World2LocalTransform
float WorldScale = 1.f
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FDisplayClusterWarpEye, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDisplayClusterWarpEye, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
WarpBlend eye data.
Definition at line 13 of file DisplayClusterWarpEye.h.
Constructor & Destructor Documentation
FDisplayClusterWarpEye()
FDisplayClusterWarpEye::FDisplayClusterWarpEye (const TSharedPtr< IDisplayClusterViewport, ESPMode::ThreadSafe > & InViewport, const uint32 InContextNum) inline
Definition at line 17 of file DisplayClusterWarpEye.h.
References ContextNum, and ViewportWeakPtr.
Referenced by IsEqual().
Member Function Documentation
GetViewport()
IDisplayClusterViewport * FDisplayClusterWarpEye::GetViewport () const inline
Definition at line 32 of file DisplayClusterWarpEye.h.
References ViewportWeakPtr.
IsEqual()
bool FDisplayClusterWarpEye::IsEqual (const FDisplayClusterWarpEye & InEye, float Precision) const inline
Definition at line 22 of file DisplayClusterWarpEye.h.
References FDisplayClusterWarpEye(), FMath::IsNearlyEqual(), ViewPoint, and WorldScale.
Field Documentation
ContextNum
const uint32 FDisplayClusterWarpEye::ContextNum
Definition at line 39 of file DisplayClusterWarpEye.h.
Referenced by FDisplayClusterWarpEye().
OverrideViewDirection
TOptional<FVector> FDisplayClusterWarpEye::OverrideViewDirection
Definition at line 56 of file DisplayClusterWarpEye.h.
OverrideViewTarget
TOptional<FVector> FDisplayClusterWarpEye::OverrideViewTarget
Definition at line 53 of file DisplayClusterWarpEye.h.
ViewPoint
FDisplayClusterWarpViewPoint FDisplayClusterWarpEye::ViewPoint
Definition at line 41 of file DisplayClusterWarpEye.h.
Referenced by IsEqual().
ViewportWeakPtr
const TWeakPtr<IDisplayClusterViewport, ESPMode::ThreadSafe> FDisplayClusterWarpEye::ViewportWeakPtr
Definition at line 38 of file DisplayClusterWarpEye.h.
Referenced by FDisplayClusterWarpEye(), and GetViewport().
WarpPolicy
TSharedPtr<IDisplayClusterWarpPolicy, ESPMode::ThreadSafe> FDisplayClusterWarpEye::WarpPolicy
Definition at line 50 of file DisplayClusterWarpEye.h.
World2LocalTransform
FTransform FDisplayClusterWarpEye::World2LocalTransform
Definition at line 47 of file DisplayClusterWarpEye.h.
WorldScale
float FDisplayClusterWarpEye::WorldScale = 1.f
Definition at line 44 of file DisplayClusterWarpEye.h.
Referenced by IsEqual().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterWarp/Public/Containers/DisplayClusterWarpEye.h