Unreal Engine 5.6 C++ API: FDynamicMeshGroupEditBuilder Class Reference
FDynamicMeshGroupEditBuilder Class Reference
FDynamicMeshGroupEditBuilder builds up a FDynamicMeshGroupEdit incrementally.
#include "MeshPolygroupChange.h"
Public Member Functions
MODELINGCOMPONENTS_API FDynamicMeshGroupEditBuilder (FDynamicMesh3 *Mesh)
MODELINGCOMPONENTS_API FDynamicMeshGroupEditBuilder (FDynamicMesh3 *Mesh, int32 GroupLayer)
MODELINGCOMPONENTS_API FDynamicMeshGroupEditBuilder (UE::Geometry::FPolygroupSet *PolygroupSet)
TUniquePtr< FDynamicMeshGroupEdit > ExtractResult ()
MODELINGCOMPONENTS_API void SaveTriangle (int32 TriangleID)
MODELINGCOMPONENTS_API void SaveTriangle (int32 TriangleID, int32 OldGroup, int32 NewGroup)
template<typename EnumerableType>
void SaveTriangles (EnumerableType Enumerable)
Protected Attributes
TUniquePtr< FDynamicMeshGroupEdit > Edit
TPimplPtr< UE::Geometry::FPolygroupSet > PolygroupSet
TMap< int32, int32 > SavedIndexMap
Detailed Description
FDynamicMeshGroupEditBuilder builds up a FDynamicMeshGroupEdit incrementally.
Definition at line 40 of file MeshPolygroupChange.h.
Constructor & Destructor Documentation
FDynamicMeshGroupEditBuilder() [1/3]
MODELINGCOMPONENTS_API FDynamicMeshGroupEditBuilder::FDynamicMeshGroupEditBuilder (FDynamicMesh3 * Mesh)
References Mesh, and UE_API.
FDynamicMeshGroupEditBuilder() [2/3]
MODELINGCOMPONENTS_API FDynamicMeshGroupEditBuilder::FDynamicMeshGroupEditBuilder (FDynamicMesh3 * Mesh, int32 GroupLayer)
References Mesh, and UE_API.
FDynamicMeshGroupEditBuilder() [3/3]
MODELINGCOMPONENTS_API FDynamicMeshGroupEditBuilder::FDynamicMeshGroupEditBuilder (UE::Geometry::FPolygroupSet * PolygroupSet)
References PolygroupSet, and UE_API.
Member Function Documentation
ExtractResult()
TUniquePtr< FDynamicMeshGroupEdit > FDynamicMeshGroupEditBuilder::ExtractResult () inline
Definition at line 47 of file MeshPolygroupChange.h.
References Edit, and MoveTemp().
SaveTriangle() [1/2]
MODELINGCOMPONENTS_API void FDynamicMeshGroupEditBuilder::SaveTriangle (int32 TriangleID)
References UE_API.
Referenced by SaveTriangles().
SaveTriangle() [2/2]
MODELINGCOMPONENTS_API void FDynamicMeshGroupEditBuilder::SaveTriangle (int32 TriangleID, int32 OldGroup, int32 NewGroup)
References UE_API.
SaveTriangles()
template<typename EnumerableType> void FDynamicMeshGroupEditBuilder::SaveTriangles (EnumerableType Enumerable) inline
Definition at line 53 of file MeshPolygroupChange.h.
References SaveTriangle().
Field Documentation
Edit
TUniquePtr<FDynamicMeshGroupEdit> FDynamicMeshGroupEditBuilder::Edit protected
Definition at line 63 of file MeshPolygroupChange.h.
Referenced by ExtractResult().
PolygroupSet
TPimplPtr<UE::Geometry::FPolygroupSet> FDynamicMeshGroupEditBuilder::PolygroupSet protected
Definition at line 62 of file MeshPolygroupChange.h.
Referenced by FDynamicMeshGroupEditBuilder().
SavedIndexMap
TMap<int32, int32> FDynamicMeshGroupEditBuilder::SavedIndexMap protected
Definition at line 64 of file MeshPolygroupChange.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Changes/MeshPolygroupChange.h