Unreal Engine 5.6 C++ API: AwaitableTask_Detail::TPromiseVTableBase< ReturnType > Class Template Reference
AwaitableTask_Detail::TPromiseVTableBase< ReturnType > Class Template Reference
#include "AwaitableTask.h"
Public Member Functions
TPromiseVTableBase ()=default
virtual void Finish ()
virtual ReturnType GetResult ()
virtual void IncrementRefCount ()
virtual bool IsCompleted () const
virtual bool IsLaunched () const
virtual bool IsValid () const
TPromiseVTableBase & operator= (const TPromiseVTableBase &Other)
TPromiseVTableBase & operator= (TPromiseVTableBase &&Other)
virtual bool TryLaunch ()
Protected Member Functions
TPromiseVTableBase (FPromiseBase *InPromise)
Protected Attributes
FPromiseBase * Promise = nullptr
Detailed Description
template<typename ReturnType>
class AwaitableTask_Detail::TPromiseVTableBase< ReturnType >
Definition at line 32 of file AwaitableTask.h.
Constructor & Destructor Documentation
TPromiseVTableBase() [1/2]
template<typename ReturnType> AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::TPromiseVTableBase (FPromiseBase * InPromise) inline protected
Definition at line 36 of file AwaitableTask.h.
Referenced by AwaitableTask_Detail::TPromiseVTable< P >::TPromiseVTable(), operator=(), and operator=().
TPromiseVTableBase() [2/2]
template<typename ReturnType> AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::TPromiseVTableBase () default
Member Function Documentation
Finish()
template<typename ReturnType> virtual void AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::Finish () inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 77 of file AwaitableTask.h.
GetResult()
template<typename ReturnType> virtual ReturnType AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::GetResult () inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 53 of file AwaitableTask.h.
IncrementRefCount()
template<typename ReturnType> virtual void AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::IncrementRefCount () inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 48 of file AwaitableTask.h.
IsCompleted()
template<typename ReturnType> virtual bool AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::IsCompleted () const inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 71 of file AwaitableTask.h.
IsLaunched()
template<typename ReturnType> virtual bool AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::IsLaunched () const inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 59 of file AwaitableTask.h.
IsValid()
template<typename ReturnType> virtual bool AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::IsValid () const inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 65 of file AwaitableTask.h.
operator=() [1/2]
template<typename ReturnType> TPromiseVTableBase< ReturnType > & AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::operator= (const TPromiseVTableBase< ReturnType > & Other) inline
Definition at line 134 of file AwaitableTask.h.
References TPromiseVTableBase(), and Other.
operator=() [2/2]
template<typename ReturnType> TPromiseVTableBase< ReturnType > & AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::operator= (TPromiseVTableBase< ReturnType > && Other) inline
Definition at line 141 of file AwaitableTask.h.
References TPromiseVTableBase(), and Other.
TryLaunch()
template<typename ReturnType> virtual bool AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::TryLaunch () inline virtual
Reimplemented in AwaitableTask_Detail::TPromiseVTable< PromiseType >, AwaitableTask_Detail::TPromiseVTable< P >, AwaitableTask_Detail::TPromiseVTableDummy< ReturnType >, and AwaitableTask_Detail::TPromiseVTableDummy< R >.
Definition at line 42 of file AwaitableTask.h.
Field Documentation
Promise
template<typename ReturnType> FPromiseBase* AwaitableTask_Detail::TPromiseVTableBase< ReturnType >::Promise = nullptr protected
Definition at line 35 of file AwaitableTask.h.
Referenced by AwaitableTask_Detail::TPromiseVTable< P >::TPromiseVTable(), AwaitableTask_Detail::TPromiseVTable< P >::Finish(), AwaitableTask_Detail::TPromiseVTable< P >::GetResult(), AwaitableTask_Detail::TPromiseVTable< P >::IncrementRefCount(), AwaitableTask_Detail::TPromiseVTable< P >::IsCompleted(), AwaitableTask_Detail::TPromiseVTable< P >::IsLaunched(), and AwaitableTask_Detail::TPromiseVTable< P >::TryLaunch().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Async/AwaitableTask.h