Unreal Engine 5.6 C++ API: FProjectedShadowInitializer Class Reference
FProjectedShadowInitializer Class Reference
A projected shadow transform.
#include "SceneManagement.h"
Public Member Functions
FProjectedShadowInitializer ()
Default constructor.
bool IsCachedShadowValid (const FProjectedShadowInitializer &CachedShadow) const
Data Fields
float MaxDistanceToCastInLightW
float MinLightW
FVector PreShadowTranslation
A translation that is applied to world-space before transforming by one of the shadow matrices.
FVector2D Scales
Non-uniform scale to be applied after WorldToLight.
FBoxSphereBounds SubjectBounds
FVector4 WAxis
FMatrix WorldToLight
Detailed Description
A projected shadow transform.
Definition at line 1013 of file SceneManagement.h.
Constructor & Destructor Documentation
FProjectedShadowInitializer()
FProjectedShadowInitializer::FProjectedShadowInitializer () inline
Default constructor.
Definition at line 1030 of file SceneManagement.h.
Referenced by IsCachedShadowValid(), and FWholeSceneProjectedShadowInitializer::IsCachedShadowValid().
Member Function Documentation
IsCachedShadowValid()
bool FProjectedShadowInitializer::IsCachedShadowValid (const FProjectedShadowInitializer & CachedShadow) const inline
Definition at line 1033 of file SceneManagement.h.
References FProjectedShadowInitializer(), UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent, MaxDistanceToCastInLightW, MinLightW, UE::Math::TBoxSphereBounds< T, TExtent >::Origin, PreShadowTranslation, Scales, UE::Math::TBoxSphereBounds< T, TExtent >::SphereRadius, SubjectBounds, WAxis, and WorldToLight.
Referenced by FWholeSceneProjectedShadowInitializer::IsCachedShadowValid().
Field Documentation
MaxDistanceToCastInLightW
float FProjectedShadowInitializer::MaxDistanceToCastInLightW
Definition at line 1027 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
MinLightW
float FProjectedShadowInitializer::MinLightW
Definition at line 1026 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
PreShadowTranslation
FVector FProjectedShadowInitializer::PreShadowTranslation
A translation that is applied to world-space before transforming by one of the shadow matrices.
Definition at line 1018 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
Scales
FVector2D FProjectedShadowInitializer::Scales
Non-uniform scale to be applied after WorldToLight.
Definition at line 1022 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
SubjectBounds
FBoxSphereBounds FProjectedShadowInitializer::SubjectBounds
Definition at line 1024 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
WAxis
FVector4 FProjectedShadowInitializer::WAxis
Definition at line 1025 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
WorldToLight
FMatrix FProjectedShadowInitializer::WorldToLight
Definition at line 1020 of file SceneManagement.h.
Referenced by IsCachedShadowValid().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneManagement.h