Unreal Engine 5.6 C++ API: IAnimBlueprintPostExpansionStepContext Class Reference
IAnimBlueprintPostExpansionStepContext Class Reference abstract
#include "IAnimBlueprintPostExpansionStepContext.h"
Public Member Functions
virtual ~IAnimBlueprintPostExpansionStepContext ()
const TMap< UAnimGraphNode_Base *, int32 > & GetAllocatedAnimNodeIndices () const
const FKismetCompilerOptions & GetCompileOptions () const
UEdGraph * GetConsolidatedEventGraph () const
FCompilerResultsLog & GetMessageLog () const
Protected Member Functions
virtual const TMap< UAnimGraphNode_Base *, int32 > & GetAllocatedAnimNodeIndicesImpl () const =0
virtual const FKismetCompilerOptions & GetCompileOptionsImpl () const =0
virtual UEdGraph * GetConsolidatedEventGraphImpl () const =0
virtual FCompilerResultsLog & GetMessageLogImpl () const =0
Detailed Description
Definition at line 13 of file IAnimBlueprintPostExpansionStepContext.h.
Constructor & Destructor Documentation
~IAnimBlueprintPostExpansionStepContext()
virtual IAnimBlueprintPostExpansionStepContext::~IAnimBlueprintPostExpansionStepContext () inline virtual
Definition at line 16 of file IAnimBlueprintPostExpansionStepContext.h.
Member Function Documentation
GetAllocatedAnimNodeIndices()
const TMap< UAnimGraphNode_Base *, int32 > & IAnimBlueprintPostExpansionStepContext::GetAllocatedAnimNodeIndices () const inline
Definition at line 22 of file IAnimBlueprintPostExpansionStepContext.h.
References GetAllocatedAnimNodeIndicesImpl().
GetAllocatedAnimNodeIndicesImpl()
virtual const TMap< UAnimGraphNode_Base *, int32 > & IAnimBlueprintPostExpansionStepContext::GetAllocatedAnimNodeIndicesImpl () const protected pure virtual
Referenced by GetAllocatedAnimNodeIndices().
GetCompileOptions()
const FKismetCompilerOptions & IAnimBlueprintPostExpansionStepContext::GetCompileOptions () const inline
Definition at line 28 of file IAnimBlueprintPostExpansionStepContext.h.
References GetCompileOptionsImpl().
GetCompileOptionsImpl()
virtual const FKismetCompilerOptions & IAnimBlueprintPostExpansionStepContext::GetCompileOptionsImpl () const protected pure virtual
Referenced by GetCompileOptions().
GetConsolidatedEventGraph()
UEdGraph * IAnimBlueprintPostExpansionStepContext::GetConsolidatedEventGraph () const inline
Definition at line 25 of file IAnimBlueprintPostExpansionStepContext.h.
References GetConsolidatedEventGraphImpl().
GetConsolidatedEventGraphImpl()
virtual UEdGraph * IAnimBlueprintPostExpansionStepContext::GetConsolidatedEventGraphImpl () const protected pure virtual
Referenced by GetConsolidatedEventGraph().
GetMessageLog()
FCompilerResultsLog & IAnimBlueprintPostExpansionStepContext::GetMessageLog () const inline
Definition at line 19 of file IAnimBlueprintPostExpansionStepContext.h.
References GetMessageLogImpl().
GetMessageLogImpl()
virtual FCompilerResultsLog & IAnimBlueprintPostExpansionStepContext::GetMessageLogImpl () const protected pure virtual
Referenced by GetMessageLog().
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/IAnimBlueprintPostExpansionStepContext.h