Unreal Engine 5.6 C++ API: TLruCache< KeyType, ValueType, KeyComp >::TConstIterator Class Reference
TLruCache< KeyType, ValueType, KeyComp >::TConstIterator Class Reference
Cache iterator (const).
#include "LruCache.h"
Public Member Functions
FORCEINLINE TConstIterator ()
FORCEINLINE TConstIterator (const TLruCache &Cache)
Public Member Functions inherited from TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< true >
FORCEINLINE TBaseIterator ()
FORCEINLINE KeyType & Key () const
FORCEINLINE operator bool () const
FORCEINLINE bool operator! () const
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
ValueType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
ValueType & operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
FORCEINLINE ValueType & Value () const
Additional Inherited Members
Protected Member Functions inherited from TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< true >
FCacheEntry * GetCurrentEntry ()
void Increment ()
Detailed Description
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>>
class TLruCache< KeyType, ValueType, KeyComp >::TConstIterator
Cache iterator (const).
Definition at line 723 of file LruCache.h.
Constructor & Destructor Documentation
TConstIterator() [1/2]
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TConstIterator::TConstIterator () inline nodiscard
Definition at line 728 of file LruCache.h.
References TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< true >::TBaseIterator(), and FORCEINLINE.
TConstIterator() [2/2]
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TConstIterator::TConstIterator (const TLruCache & Cache) inline nodiscard
Definition at line 733 of file LruCache.h.
References TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< true >::TBaseIterator(), TLruCache< KeyType, ValueType, KeyComp >::TLruCache(), and FORCEINLINE.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LruCache.h