Unreal Engine 5.6 C++ API: TMapBuilder< KeyType, ValueType, SetAllocator > Class Template Reference
TMapBuilder< KeyType, ValueType, SetAllocator > Class Template Reference
Template for fluent map builders.
#include "MapBuilder.h"
Public Member Functions
TMapBuilder ()
Default constructor.
template<typename OtherAllocator>
TMapBuilder (const TMap< KeyType, ValueType, OtherAllocator > &InMap)
Creates and initializes a new map builder from another map.
TMapBuilder & Add (KeyType InKey, ValueType InValue)
Adds a key-value pair to the map.
TMapBuilder & Append (const TMap< KeyType, ValueType, SetAllocator > &OtherMap)
Appends another map.
TMap< KeyType, ValueType, SetAllocator > Build ()
Builds the map as configured.
operator TMap< KeyType, ValueType, SetAllocator > ()
Implicit conversion operator to build the map as configured.
Private Attributes
TMap< KeyType, ValueType, SetAllocator > Map
Holds the map being built.
Detailed Description
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator>
class TMapBuilder< KeyType, ValueType, SetAllocator >
Template for fluent map builders.
Parameters
KeyType The type of keys stored in the map.
ValueType The type of values stored in the map.
SetAllocator The allocator to use for key-value pairs.
Definition at line 16 of file MapBuilder.h.
Constructor & Destructor Documentation
TMapBuilder() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> TMapBuilder< KeyType, ValueType, SetAllocator >::TMapBuilder () inline nodiscard
Default constructor.
Definition at line 21 of file MapBuilder.h.
Referenced by Add(), and Append().
TMapBuilder() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> template<typename OtherAllocator> TMapBuilder< KeyType, ValueType, SetAllocator >::TMapBuilder (const TMap< KeyType, ValueType, OtherAllocator > & InMap) inline nodiscard
Creates and initializes a new map builder from another map.
Parameters
InMap The map to copy.
Definition at line 31 of file MapBuilder.h.
References Map.
Member Function Documentation
Add()
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> TMapBuilder & TMapBuilder< KeyType, ValueType, SetAllocator >::Add (KeyType InKey, ValueType InValue) inline
Adds a key-value pair to the map.
Parameters
InKey The key of the pair to add.
InValue The value of the pair to add.
Returns
This instance (for method chaining).
Definition at line 45 of file MapBuilder.h.
References TMapBuilder(), and Map.
Append()
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> TMapBuilder & TMapBuilder< KeyType, ValueType, SetAllocator >::Append (const TMap< KeyType, ValueType, SetAllocator > & OtherMap) inline
Appends another map.
Parameters
OtherMap The map to append.
Returns
This instance (for method chaining).
Definition at line 58 of file MapBuilder.h.
References TMapBuilder(), and Map.
Build()
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> TMap< KeyType, ValueType, SetAllocator > TMapBuilder< KeyType, ValueType, SetAllocator >::Build () inline nodiscard
Builds the map as configured.
Returns
A new map.
Definition at line 72 of file MapBuilder.h.
References Map.
Referenced by operator TMap< KeyType, ValueType, SetAllocator >().
operator TMap< KeyType, ValueType, SetAllocator >()
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> TMapBuilder< KeyType, ValueType, SetAllocator >::operator TMap< KeyType, ValueType, SetAllocator > () inline nodiscard
Implicit conversion operator to build the map as configured.
Returns
A new map.
Definition at line 82 of file MapBuilder.h.
References Build().
Field Documentation
Map
template<typename KeyType, typename ValueType, typename SetAllocator = FDefaultSetAllocator> TMap<KeyType, ValueType, SetAllocator> TMapBuilder< KeyType, ValueType, SetAllocator >::Map private
Holds the map being built.
Definition at line 90 of file MapBuilder.h.
Referenced by TMapBuilder(), Add(), Append(), and Build().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/MapBuilder.h