Unreal Engine 5.6 C++ API: FMemoryImageAllocatorBase Class Reference
FMemoryImageAllocatorBase Class Reference
#include "MemoryImage.h"
Public Member Functions
FMemoryImageAllocatorBase ()=default
~FMemoryImageAllocatorBase ()
Destructor.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements, void *Dst) const
FORCEINLINE SIZE_T GetAllocatedSize (int32 CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE FScriptContainerElement * GetAllocation () const
FORCEINLINE int64 GetFrozenOffsetFromThis () const
FORCEINLINE bool HasAllocation ()
void MoveToEmpty (FMemoryImageAllocatorBase &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (int32 PreviousNumElements, int32 NumElements, SIZE_T NumBytesPerElement, uint32 Alignment)
void ToString (const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements, int32 MaxAllocatedElements, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext) const
void WriteMemoryImage (FMemoryImageWriter &Writer, const FTypeLayoutDesc &TypeDesc, int32 NumAllocatedElements, uint32 Alignment) const
Private Member Functions
UE_NONCOPYABLE (FMemoryImageAllocatorBase)
Private Attributes
TMemoryImagePtr< FScriptContainerElement > Data
Detailed Description
Definition at line 599 of file MemoryImage.h.
Constructor & Destructor Documentation
FMemoryImageAllocatorBase()
FMemoryImageAllocatorBase::FMemoryImageAllocatorBase () default
Referenced by MoveToEmpty(), and UE_NONCOPYABLE().
~FMemoryImageAllocatorBase()
FMemoryImageAllocatorBase::~FMemoryImageAllocatorBase ()
Destructor.
Member Function Documentation
CopyUnfrozen()
void FMemoryImageAllocatorBase::CopyUnfrozen (const FMemoryUnfreezeContent & Context, const FTypeLayoutDesc & TypeDesc, int32 NumAllocatedElements, void * Dst) const
GetAllocatedSize()
FORCEINLINE SIZE_T FMemoryImageAllocatorBase::GetAllocatedSize (int32 CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 621 of file MemoryImage.h.
References FORCEINLINE.
GetAllocation()
FORCEINLINE FScriptContainerElement * FMemoryImageAllocatorBase::GetAllocation () const inline
Definition at line 616 of file MemoryImage.h.
References Data, and FORCEINLINE.
Referenced by TMemoryImageAllocator< Alignment >::ForElementType< ElementType >::GetAllocation().
GetFrozenOffsetFromThis()
FORCEINLINE int64 FMemoryImageAllocatorBase::GetFrozenOffsetFromThis () const inline
Definition at line 629 of file MemoryImage.h.
References Data, and FORCEINLINE.
HasAllocation()
FORCEINLINE bool FMemoryImageAllocatorBase::HasAllocation () inline
Definition at line 625 of file MemoryImage.h.
References Data, and FORCEINLINE.
MoveToEmpty()
void FMemoryImageAllocatorBase::MoveToEmpty (FMemoryImageAllocatorBase & Other)
Moves the state of another allocator into this one.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
References FMemoryImageAllocatorBase(), and Other.
ResizeAllocation()
void FMemoryImageAllocatorBase::ResizeAllocation (int32 PreviousNumElements, int32 NumElements, SIZE_T NumBytesPerElement, uint32 Alignment)
Referenced by TMemoryImageAllocator< Alignment >::ForAnyElementType::ResizeAllocation(), and TMemoryImageAllocator< Alignment >::ForAnyElementType::ResizeAllocation().
ToString()
void FMemoryImageAllocatorBase::ToString (const FTypeLayoutDesc & TypeDesc, int32 NumAllocatedElements, int32 MaxAllocatedElements, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext) const
UE_NONCOPYABLE()
FMemoryImageAllocatorBase::UE_NONCOPYABLE (FMemoryImageAllocatorBase) private
References FMemoryImageAllocatorBase().
WriteMemoryImage()
void FMemoryImageAllocatorBase::WriteMemoryImage (FMemoryImageWriter & Writer, const FTypeLayoutDesc & TypeDesc, int32 NumAllocatedElements, uint32 Alignment) const
Referenced by TMemoryImageAllocator< Alignment >::ForAnyElementType::WriteMemoryImage().
Field Documentation
Data
TMemoryImagePtr<FScriptContainerElement> FMemoryImageAllocatorBase::Data private
Definition at line 637 of file MemoryImage.h.
Referenced by GetAllocation(), GetFrozenOffsetFromThis(), and HasAllocation().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/MemoryImage.h