Unreal Engine 5.6 C++ API: FModifierKeysState Class Reference
FModifierKeysState Class Reference
FModifierKeysState stores the pressed state of keys that are commonly used as modifiers.
#include "GenericApplication.h"
Public Member Functions
FModifierKeysState ()
FModifierKeysState (const bool bInIsLeftShiftDown, const bool bInIsRightShiftDown, const bool bInIsLeftControlDown, const bool bInIsRightControlDown, const bool bInIsLeftAltDown, const bool bInIsRightAltDown, const bool bInIsLeftCommandDown, const bool bInIsRightCommandDown, const bool bInAreCapsLocked)
Constructor.
bool AnyModifiersDown () const
bool AreCapsLocked () const
bool AreModifersDown (EModifierKey::Type ModiferKeys) const
bool IsAltDown () const
Returns true if either alt key was down when this event occurred.
bool IsCommandDown () const
Returns true if either command key was down when this event occurred.
bool IsControlDown () const
Returns true if either control key was down when this event occurred.
bool IsLeftAltDown () const
Returns true if left alt key was down when this event occurred.
bool IsLeftCommandDown () const
Returns true if left command key was down when this event occurred.
bool IsLeftControlDown () const
Returns true if left control key was down when this event occurred.
bool IsLeftShiftDown () const
Returns true if left shift key was down when this event occurred.
bool IsRightAltDown () const
Returns true if right alt key was down when this event occurred.
bool IsRightCommandDown () const
Returns true if right command key was down when this event occurred.
bool IsRightControlDown () const
Returns true if right control key was down when this event occurred.
bool IsRightShiftDown () const
Returns true if right shift key was down when this event occurred.
bool IsShiftDown () const
Returns true if either shift key was down when this event occurred.
Private Attributes
uint16 bAreCapsLocked:1
True if the Caps Lock key has been toggled to the enabled state.
uint16 bIsLeftAltDown:1
True if the left alt key was down when this event occurred.
uint16 bIsLeftCommandDown:1
True if the left command key was down when this event occurred.
uint16 bIsLeftControlDown:1
True if the left control key was down when this event occurred.
uint16 bIsLeftShiftDown:1
True if the left shift key was down when this event occurred.
uint16 bIsRightAltDown:1
True if the right alt key was down when this event occurred.
uint16 bIsRightCommandDown:1
True if the right command key was down when this event occurred.
uint16 bIsRightControlDown:1
True if the right control key was down when this event occurred.
uint16 bIsRightShiftDown:1
True if the right shift key was down when this event occurred.
Detailed Description
FModifierKeysState stores the pressed state of keys that are commonly used as modifiers.
Definition at line 74 of file GenericApplication.h.
Constructor & Destructor Documentation
FModifierKeysState() [1/2]
FModifierKeysState::FModifierKeysState (const bool bInIsLeftShiftDown, const bool bInIsRightShiftDown, const bool bInIsLeftControlDown, const bool bInIsRightControlDown, const bool bInIsLeftAltDown, const bool bInIsRightAltDown, const bool bInIsLeftCommandDown, const bool bInIsRightCommandDown, const bool bInAreCapsLocked) inline
Constructor.
Events are immutable once constructed.
Parameters
bInIsLeftShiftDown True if left shift is pressed
bInIsRightShiftDown True if right shift is pressed
bInIsLeftControlDown True if left control is pressed
bInIsRightControlDown True if right control is pressed
bInIsLeftAltDown True if left alt is pressed
bInIsRightAltDown True if right alt is pressed
Definition at line 89 of file GenericApplication.h.
References bAreCapsLocked, bIsLeftAltDown, bIsLeftCommandDown, bIsLeftControlDown, bIsLeftShiftDown, bIsRightAltDown, bIsRightCommandDown, bIsRightControlDown, and bIsRightShiftDown.
FModifierKeysState() [2/2]
FModifierKeysState::FModifierKeysState () inline
Definition at line 110 of file GenericApplication.h.
References bAreCapsLocked, bIsLeftAltDown, bIsLeftCommandDown, bIsLeftControlDown, bIsLeftShiftDown, bIsRightAltDown, bIsRightCommandDown, bIsRightControlDown, and bIsRightShiftDown.
Member Function Documentation
AnyModifiersDown()
bool FModifierKeysState::AnyModifiersDown () const inline
Returns
true if any modifier key is down
Definition at line 283 of file GenericApplication.h.
References IsAltDown(), IsCommandDown(), IsControlDown(), and IsShiftDown().
AreCapsLocked()
bool FModifierKeysState::AreCapsLocked () const inline
Returns
true if the Caps Lock key has been toggled to the enabled state.
Definition at line 247 of file GenericApplication.h.
References bAreCapsLocked.
AreModifersDown()
bool FModifierKeysState::AreModifersDown (EModifierKey::Type ModiferKeys) const inline
Parameters
ModifierKeys the modifier keys to test to see if they are pressed. Returns true if no modifiers are specified.
Returns
true if all modifier keys are pressed specified in the modifier keys.
Definition at line 256 of file GenericApplication.h.
References EModifierKey::Alt, EModifierKey::Command, EModifierKey::Control, IsAltDown(), IsCommandDown(), IsControlDown(), IsShiftDown(), and EModifierKey::Shift.
IsAltDown()
bool FModifierKeysState::IsAltDown () const inline
Returns true if either alt key was down when this event occurred.
Returns
True if alt is pressed
Definition at line 188 of file GenericApplication.h.
References bIsLeftAltDown, and bIsRightAltDown.
Referenced by AnyModifiersDown(), and AreModifersDown().
IsCommandDown()
bool FModifierKeysState::IsCommandDown () const inline
Returns true if either command key was down when this event occurred.
Returns
True if command is pressed
Definition at line 218 of file GenericApplication.h.
References bIsLeftCommandDown, and bIsRightCommandDown.
Referenced by AnyModifiersDown(), and AreModifersDown().
IsControlDown()
bool FModifierKeysState::IsControlDown () const inline
Returns true if either control key was down when this event occurred.
Returns
True if control is pressed
Definition at line 158 of file GenericApplication.h.
References bIsLeftControlDown, and bIsRightControlDown.
Referenced by AnyModifiersDown(), AreModifersDown(), and SSegmentedControl< OptionType >::CommitValue().
IsLeftAltDown()
bool FModifierKeysState::IsLeftAltDown () const inline
Returns true if left alt key was down when this event occurred.
Returns
True if left alt is pressed
Definition at line 198 of file GenericApplication.h.
References bIsLeftAltDown.
IsLeftCommandDown()
bool FModifierKeysState::IsLeftCommandDown () const inline
Returns true if left command key was down when this event occurred.
Returns
True if left command is pressed
Definition at line 228 of file GenericApplication.h.
References bIsLeftCommandDown.
IsLeftControlDown()
bool FModifierKeysState::IsLeftControlDown () const inline
Returns true if left control key was down when this event occurred.
Returns
True if left control is pressed
Definition at line 168 of file GenericApplication.h.
References bIsLeftControlDown.
IsLeftShiftDown()
bool FModifierKeysState::IsLeftShiftDown () const inline
Returns true if left shift key was down when this event occurred.
Returns
True if left shift is pressed
Definition at line 138 of file GenericApplication.h.
References bIsLeftShiftDown.
IsRightAltDown()
bool FModifierKeysState::IsRightAltDown () const inline
Returns true if right alt key was down when this event occurred.
Returns
True if right alt is pressed
Definition at line 208 of file GenericApplication.h.
References bIsRightAltDown.
IsRightCommandDown()
bool FModifierKeysState::IsRightCommandDown () const inline
Returns true if right command key was down when this event occurred.
Returns
True if right command is pressed
Definition at line 238 of file GenericApplication.h.
References bIsRightCommandDown.
IsRightControlDown()
bool FModifierKeysState::IsRightControlDown () const inline
Returns true if right control key was down when this event occurred.
Returns
True if right control is pressed
Definition at line 178 of file GenericApplication.h.
References bIsRightControlDown.
IsRightShiftDown()
bool FModifierKeysState::IsRightShiftDown () const inline
Returns true if right shift key was down when this event occurred.
Returns
True if right shift is pressed
Definition at line 148 of file GenericApplication.h.
References bIsRightShiftDown.
IsShiftDown()
bool FModifierKeysState::IsShiftDown () const inline
Returns true if either shift key was down when this event occurred.
Returns
True if shift is pressed
Definition at line 128 of file GenericApplication.h.
References bIsLeftShiftDown, and bIsRightShiftDown.
Referenced by AnyModifiersDown(), AreModifersDown(), and SSegmentedControl< OptionType >::CommitValue().
Field Documentation
bAreCapsLocked
uint16 FModifierKeysState::bAreCapsLocked private
True if the Caps Lock key has been toggled to the enabled state.
Definition at line 315 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), and AreCapsLocked().
bIsLeftAltDown
uint16 FModifierKeysState::bIsLeftAltDown private
True if the left alt key was down when this event occurred.
Definition at line 303 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsAltDown(), and IsLeftAltDown().
bIsLeftCommandDown
uint16 FModifierKeysState::bIsLeftCommandDown private
True if the left command key was down when this event occurred.
Definition at line 309 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsCommandDown(), and IsLeftCommandDown().
bIsLeftControlDown
uint16 FModifierKeysState::bIsLeftControlDown private
True if the left control key was down when this event occurred.
Definition at line 297 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsControlDown(), and IsLeftControlDown().
bIsLeftShiftDown
uint16 FModifierKeysState::bIsLeftShiftDown private
True if the left shift key was down when this event occurred.
Definition at line 291 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsLeftShiftDown(), and IsShiftDown().
bIsRightAltDown
uint16 FModifierKeysState::bIsRightAltDown private
True if the right alt key was down when this event occurred.
Definition at line 306 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsAltDown(), and IsRightAltDown().
bIsRightCommandDown
uint16 FModifierKeysState::bIsRightCommandDown private
True if the right command key was down when this event occurred.
Definition at line 312 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsCommandDown(), and IsRightCommandDown().
bIsRightControlDown
uint16 FModifierKeysState::bIsRightControlDown private
True if the right control key was down when this event occurred.
Definition at line 300 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsControlDown(), and IsRightControlDown().
bIsRightShiftDown
uint16 FModifierKeysState::bIsRightShiftDown private
True if the right shift key was down when this event occurred.
Definition at line 294 of file GenericApplication.h.
Referenced by FModifierKeysState(), FModifierKeysState(), IsRightShiftDown(), and IsShiftDown().
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/GenericPlatform/GenericApplication.h