Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolExtender Class Reference
UE::SequenceNavigator::FNavigationToolExtender Class Reference
#include "NavigationToolExtender.h"
Data Structures
struct FIconCustomizationKey
Hold the key of the map containing the IconCustomizations.
struct FNavigationToolInstance
Public Member Functions
FNavigationToolExtender ()
virtual ~FNavigationToolExtender ()
Static Public Member Functions
static bool AnyProviderSupportsSequencer (const FName InToolId, const ISequencer &InSequencer)
static SEQUENCENAVIGATOR_API TSharedPtr< INavigationTool > FindNavigationTool (const TSharedRef< ISequencer > &InSequencer)
Find the Navigation Tool instance associated with the given Sequencer instance.
static SEQUENCENAVIGATOR_API FSlateIcon FindOverrideIcon (TSharedPtr< const FNavigationToolItem > InItem)
Get the custom icon for the item if a customization for it exists.
static SEQUENCENAVIGATOR_API TSharedPtr< FNavigationToolProvider > FindToolProvider (const FName InToolId, const FName InProviderId)
static SEQUENCENAVIGATOR_API bool FindToolProviders (const FName InToolId, TSet< TSharedRef< FNavigationToolProvider > > &OutProviders)
Finds the tool providers associated with the given Navigation Tool instance.
static SEQUENCENAVIGATOR_API void ForEachProvider (const TFunction< bool(const FName InToolId, const TSharedRef< FNavigationToolProvider > &InProvider)> &InPredicate)
Iterates over each Navigation Tool provider and executes the predicate function.
static SEQUENCENAVIGATOR_API void ForEachToolProvider (const FName InToolId, const TFunction< bool(const TSharedRef< FNavigationToolProvider > &InProvider)> &InPredicate)
Iterates over each Navigation Tool provider and executes the predicate function associated with the given Navigation Tool instance.
static SEQUENCENAVIGATOR_API FNavigationToolExtender & Get ()
static SEQUENCENAVIGATOR_API FNavigationToolItemProxyRegistry & GetItemProxyRegistry ()
static FName GetModularFeatureName ()
static SEQUENCENAVIGATOR_API FName GetToolInstanceId (const INavigationTool &InTool)
static SEQUENCENAVIGATOR_API FName GetToolInstanceId (const ISequencer &InSequencer)
Retrieves the unique name for the provided Sequencer instance.
static SEQUENCENAVIGATOR_API FOnItemDragDropOpInitialized & OnItemDragDropOpInitialized ()
Event called when the FNavigationToolItemDragDropOp has been created and initialized in FNavigationToolItemDragDropOp::Init.
static SEQUENCENAVIGATOR_API FOnNavigationToolProvidersChanged & OnProvidersChanged ()
Event called when a provider has been added or removed from a tool instance.
static SEQUENCENAVIGATOR_API bool RegisterToolProvider (const TSharedRef< ISequencer > &InSequencer, const TSharedRef< FNavigationToolProvider > &InProvider)
Registers a Navigation Tool provider for a specified Navigation Tool instance.
static SEQUENCENAVIGATOR_API bool UnregisterToolProvider (const FName InToolId, const FName InProviderId)
Unregisters a Navigation Tool provider associated with a specific instance and identifier.
Protected Member Functions
FNavigationToolInstance * FindOrAddToolInstance_Internal (const TSharedRef< ISequencer > &InSequencer)
TSharedPtr< INavigationToolIconCustomization > GetCustomizationForItem (const TSharedPtr< const FNavigationToolItem > &InItem) const
Get the customization for the given item if any.
void OnSequencerActivated (const FName InToolId, FMovieSceneSequenceIDRef InSequenceId)
void OnSequencerClosed (const FName InToolId, const TSharedRef< ISequencer > InSequencer)
void OnSequencerCreated (const TSharedRef< ISequencer > InSequencer)
void RegisterOverridenIcon_Internal (const FNavigationToolItemTypeId &InItemTypeId, const TSharedRef< INavigationToolIconCustomization > &InIconCustomization)
void UnregisterOverriddenIcon_Internal (const FNavigationToolItemTypeId &InItemTypeId, const FName &InSpecializationIdentifier)
Static Protected Member Functions
static void AddSequencerToolBarExtension (const FNavigationToolInstance &InToolInstance)
static TSet< TSharedRef< FNavigationToolProvider > > * FindToolProviders (const FName InToolId)
static void RemoveSequencerToolBarExtension (const FNavigationToolInstance &InToolInstance)
Protected Attributes
TMap< FIconCustomizationKey, TSharedPtr< INavigationToolIconCustomization > > IconRegistry
FOnItemDragDropOpInitialized ItemDragDropOpInitializedDelegate
FNavigationToolItemProxyRegistry ItemProxyRegistry
FOnNavigationToolProvidersChanged ProvidersChangedDelegate
FDelegateHandle SequencerCreatedHandle
TMap< FName, FNavigationToolInstance > ToolInstances
Registered Sequencer types to Navigation Tool instances.
Detailed Description
Definition at line 37 of file NavigationToolExtender.h.
Constructor & Destructor Documentation
FNavigationToolExtender()
UE::SequenceNavigator::FNavigationToolExtender::FNavigationToolExtender ()
Referenced by Get().
~FNavigationToolExtender()
virtual UE::SequenceNavigator::FNavigationToolExtender::~FNavigationToolExtender () virtual
Member Function Documentation
AddSequencerToolBarExtension()
void UE::SequenceNavigator::FNavigationToolExtender::AddSequencerToolBarExtension (const FNavigationToolInstance & InToolInstance) static protected
AnyProviderSupportsSequencer()
bool UE::SequenceNavigator::FNavigationToolExtender::AnyProviderSupportsSequencer (const FName InToolId, const ISequencer & InSequencer) static
FindNavigationTool()
SEQUENCENAVIGATOR_API TSharedPtr< INavigationTool > UE::SequenceNavigator::FNavigationToolExtender::FindNavigationTool (const TSharedRef< ISequencer > & InSequencer) static
Find the Navigation Tool instance associated with the given Sequencer instance.
FindOrAddToolInstance_Internal()
FNavigationToolInstance * UE::SequenceNavigator::FNavigationToolExtender::FindOrAddToolInstance_Internal (const TSharedRef< ISequencer > & InSequencer) protected
FindOverrideIcon()
SEQUENCENAVIGATOR_API FSlateIcon UE::SequenceNavigator::FNavigationToolExtender::FindOverrideIcon (TSharedPtr< const FNavigationToolItem > InItem) static
Get the custom icon for the item if a customization for it exists.
Parameters
InItem The item to find the icon of
Returns
The custom icon for the item if a customization is found, FSlateIcon() otherwise
FindToolProvider()
SEQUENCENAVIGATOR_API TSharedPtr< FNavigationToolProvider > UE::SequenceNavigator::FNavigationToolExtender::FindToolProvider (const FName InToolId, const FName InProviderId) static
FindToolProviders() [1/2]
TSet< TSharedRef< FNavigationToolProvider > > * UE::SequenceNavigator::FNavigationToolExtender::FindToolProviders (const FName InToolId) static protected
FindToolProviders() [2/2]
SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolExtender::FindToolProviders (const FName InToolId, TSet< TSharedRef< FNavigationToolProvider > > & OutProviders) static
Finds the tool providers associated with the given Navigation Tool instance.
Parameters
InToolId The Navigation Tool Id for which to find associated providers.
OutProviders A set that will be populated with the found tool providers as weak pointers.
Returns
True if tool providers were found and populated into OutProviders; otherwise, false.
ForEachProvider()
SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolExtender::ForEachProvider (const TFunction< bool(const FName InToolId, const TSharedRef< FNavigationToolProvider > &InProvider)> & InPredicate) static
Iterates over each Navigation Tool provider and executes the predicate function.
The provided predicate function determines whether the iteration continues or stops.
Parameters
InPredicate A function that accepts a reference to an INavigationTool and a shared reference to FNavigationToolProvider. Should return true to continue iteration or false to stop.
ForEachToolProvider()
SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolExtender::ForEachToolProvider (const FName InToolId, const TFunction< bool(const TSharedRef< FNavigationToolProvider > &InProvider)> & InPredicate) static
Iterates over each Navigation Tool provider and executes the predicate function associated with the given Navigation Tool instance.
The iteration is controlled by the provided predicate function, which determines whether it continues or stops.
Parameters
InToolId The Navigation Tool Id whose providers are to be iterated over.
InPredicate A predicate function that takes a shared reference to a Navigation Tool provider as input. The function should return true to continue iteration or false to stop it.
Get()
SEQUENCENAVIGATOR_API FNavigationToolExtender & UE::SequenceNavigator::FNavigationToolExtender::Get () static
References FNavigationToolExtender().
Referenced by GetItemProxyRegistry(), OnItemDragDropOpInitialized(), and OnProvidersChanged().
GetCustomizationForItem()
TSharedPtr< INavigationToolIconCustomization > UE::SequenceNavigator::FNavigationToolExtender::GetCustomizationForItem (const TSharedPtr< const FNavigationToolItem > & InItem) const protected
Get the customization for the given item if any.
Parameters
InItem Item to search the customization for.
Returns
The customization for the item if any; nullptr otherwise.
GetItemProxyRegistry()
SEQUENCENAVIGATOR_API FNavigationToolItemProxyRegistry & UE::SequenceNavigator::FNavigationToolExtender::GetItemProxyRegistry () inline static
Definition at line 123 of file NavigationToolExtender.h.
References Get(), and ItemProxyRegistry.
Referenced by UE::SequenceNavigator::INavigationTool::GetItemProxyFactory().
GetModularFeatureName()
FName UE::SequenceNavigator::FNavigationToolExtender::GetModularFeatureName () static
GetToolInstanceId() [1/2]
SEQUENCENAVIGATOR_API FName UE::SequenceNavigator::FNavigationToolExtender::GetToolInstanceId (const INavigationTool & InTool) static
GetToolInstanceId() [2/2]
SEQUENCENAVIGATOR_API FName UE::SequenceNavigator::FNavigationToolExtender::GetToolInstanceId (const ISequencer & InSequencer) static
Retrieves the unique name for the provided Sequencer instance.
The Navigation Tool instance name is based on its associated sequencer settings object name. This provides a unique instance name for each Sequencer type.
Parameters
InSequencer The Sequencer instance for which the name is being retrieved.
Returns
The name of the Navigation Tool instance if available; otherwise, NAME_None.
OnItemDragDropOpInitialized()
SEQUENCENAVIGATOR_API FOnItemDragDropOpInitialized & UE::SequenceNavigator::FNavigationToolExtender::OnItemDragDropOpInitialized () inline static
Event called when the FNavigationToolItemDragDropOp has been created and initialized in FNavigationToolItemDragDropOp::Init.
Definition at line 118 of file NavigationToolExtender.h.
References Get(), and ItemDragDropOpInitializedDelegate.
OnProvidersChanged()
SEQUENCENAVIGATOR_API FOnNavigationToolProvidersChanged & UE::SequenceNavigator::FNavigationToolExtender::OnProvidersChanged () inline static
Event called when a provider has been added or removed from a tool instance.
Definition at line 112 of file NavigationToolExtender.h.
References Get(), and ProvidersChangedDelegate.
OnSequencerActivated()
void UE::SequenceNavigator::FNavigationToolExtender::OnSequencerActivated (const FName InToolId, FMovieSceneSequenceIDRef InSequenceId) protected
OnSequencerClosed()
void UE::SequenceNavigator::FNavigationToolExtender::OnSequencerClosed (const FName InToolId, const TSharedRef< ISequencer > InSequencer) protected
OnSequencerCreated()
void UE::SequenceNavigator::FNavigationToolExtender::OnSequencerCreated (const TSharedRef< ISequencer > InSequencer) protected
RegisterOverridenIcon_Internal()
void UE::SequenceNavigator::FNavigationToolExtender::RegisterOverridenIcon_Internal (const FNavigationToolItemTypeId & InItemTypeId, const TSharedRef< INavigationToolIconCustomization > & InIconCustomization) protected
RegisterToolProvider()
SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolExtender::RegisterToolProvider (const TSharedRef< ISequencer > & InSequencer, const TSharedRef< FNavigationToolProvider > & InProvider) static
Registers a Navigation Tool provider for a specified Navigation Tool instance.
This method ensures that the provider is associated with the given tool and replaces any existing provider with the same identifier, if one exists.
Parameters
InSequencer The Sequencer instance to create the Navigation Tool instance for.
InProvider The Navigation Tool provider being registered.
Returns
True if the provider was successfully registered, false otherwise.
RemoveSequencerToolBarExtension()
void UE::SequenceNavigator::FNavigationToolExtender::RemoveSequencerToolBarExtension (const FNavigationToolInstance & InToolInstance) static protected
UnregisterOverriddenIcon_Internal()
void UE::SequenceNavigator::FNavigationToolExtender::UnregisterOverriddenIcon_Internal (const FNavigationToolItemTypeId & InItemTypeId, const FName & InSpecializationIdentifier) protected
UnregisterToolProvider()
SEQUENCENAVIGATOR_API bool UE::SequenceNavigator::FNavigationToolExtender::UnregisterToolProvider (const FName InToolId, const FName InProviderId) static
Unregisters a Navigation Tool provider associated with a specific instance and identifier.
Parameters
InToolId The Id of the Navigation Tool from which the provider needs to be unregistered.
InProviderId The identifier of the provider to be unregistered.
Returns
True if the provider was successfully unregistered; false otherwise.
Field Documentation
IconRegistry
TMap<FIconCustomizationKey, TSharedPtr<INavigationToolIconCustomization> > UE::SequenceNavigator::FNavigationToolExtender::IconRegistry protected
Definition at line 209 of file NavigationToolExtender.h.
ItemDragDropOpInitializedDelegate
FOnItemDragDropOpInitialized UE::SequenceNavigator::FNavigationToolExtender::ItemDragDropOpInitializedDelegate protected
Definition at line 183 of file NavigationToolExtender.h.
Referenced by OnItemDragDropOpInitialized().
ItemProxyRegistry
FNavigationToolItemProxyRegistry UE::SequenceNavigator::FNavigationToolExtender::ItemProxyRegistry protected
Definition at line 185 of file NavigationToolExtender.h.
Referenced by GetItemProxyRegistry().
ProvidersChangedDelegate
FOnNavigationToolProvidersChanged UE::SequenceNavigator::FNavigationToolExtender::ProvidersChangedDelegate protected
Definition at line 181 of file NavigationToolExtender.h.
Referenced by OnProvidersChanged().
SequencerCreatedHandle
FDelegateHandle UE::SequenceNavigator::FNavigationToolExtender::SequencerCreatedHandle protected
Definition at line 173 of file NavigationToolExtender.h.
ToolInstances
TMap<FName, FNavigationToolInstance> UE::SequenceNavigator::FNavigationToolExtender::ToolInstances protected
Registered Sequencer types to Navigation Tool instances.
Definition at line 179 of file NavigationToolExtender.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/NavigationToolExtender.h