Unreal Engine 5.6 C++ API: IPackageResourceManager Class Reference
IPackageResourceManager Class Reference abstract
Provides directory queries and Archive payloads for PackagePaths and their PackageSegments from a repository that might be the local content directories, a database running on the current machine, or a remote database.
#include "PackageResourceManager.h"
Public Types
typedef TFunctionRef< bool(const FPackagePath &PackagePath, const FFileStatData &StatData)> FPackagePathStatVisitor
Return value specifies whether iteration should continue.
typedef TFunctionRef< bool(const FPackagePath &PackagePath)> FPackagePathVisitor
Return value specifies whether iteration should continue.
typedef TFunctionRef< bool(const FPackagePath &PackagePath, EPackageSegment PackageSegment, const FFileStatData &StatData)> FPackageSegmentStatVisitor
Return value specifies whether iteration should continue.
typedef TFunctionRef< bool(const FPackagePath &PackagePath, EPackageSegment PackageSegment)> FPackageSegmentVisitor
Return value specifies whether iteration should continue.
Public Member Functions
virtual ~IPackageResourceManager ()=default
virtual bool DoesExternalResourceExist (EPackageExternalResource ResourceType, FStringView Identifier)=0
Report whether a given ExternalResource exists.
bool DoesPackageExist (const FPackagePath &PackagePath, FPackagePath *OutUpdatedPath=nullptr)
Report whether the package exists.
int64 FileSize (const FPackagePath &PackagePath, FPackagePath *OutUpdatedPath=nullptr)
Report the payload size of the package.
void FindPackagesRecursive (TArray< FPackagePath > &OutPackages, FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FStringView BasenameWildcard)
Search the given subdirectory of a package mount for all packages with the given package basename in the package repository.
virtual void FindPackagesRecursive (TArray< TPair< FPackagePath, EPackageSegment > > &OutPackages, FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FStringView BasenameWildcard)=0
FindPackagesRecursive that returns PackageSegments.
void IteratePackagesInLocalOnlyDirectory (FStringView RootDir, FPackagePathVisitor Callback)
Call the callback on all packages in the given local path.
virtual void IteratePackagesInLocalOnlyDirectory (FStringView RootDir, FPackageSegmentVisitor Callback)=0
IteratePackagesInLocalOnlyDirectory that takes a FPackageSegmentStatVisitor.
void IteratePackagesInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackagePathVisitor Callback)
Call the callback on all packages in the package repository that are in the given subdirectory of a package mount.
virtual void IteratePackagesInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackageSegmentVisitor Callback)=0
IteratePackagesInPath that takes a FPackageSegmentVisitor.
void IteratePackagesStatInLocalOnlyDirectory (FStringView RootDir, FPackagePathStatVisitor Callback)
Call the callback - with stat data - on all packages in the given local path.
virtual void IteratePackagesStatInLocalOnlyDirectory (FStringView RootDir, FPackageSegmentStatVisitor Callback)=0
IteratePackagesStatInLocalOnlyDirectory that takes a FPackageSegmentStatVisitor.
void IteratePackagesStatInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackagePathStatVisitor Callback)
Call the callback - with stat data - on all packages in the package repository that are in the given subdirectory of a package mount.
virtual void IteratePackagesStatInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackageSegmentStatVisitor Callback)=0
IteratePackagesStatInPath that takes a FPackageSegmentVisitor.
virtual FOpenAsyncPackageResult OpenAsyncReadExternalResource (EPackageExternalResource ResourceType, FStringView Identifier)=0
Open an IAsyncReadFileHandle to asynchronously read the bytes of the given ExternalResource.
FOpenAsyncPackageResult OpenAsyncReadPackage (const FPackagePath &PackagePath)
Open an IAsyncReadFileHandle to asynchronously read the bytes of the package.
virtual FOpenAsyncPackageResult OpenAsyncReadPackage (const FPackagePath &PackagePath, FBulkDataCookedIndex CookedIndex, EPackageSegment PackageSegment)=0
OpenAsyncReadPackage that takes a PackageSegment.
virtual IMappedFileHandle * OpenMappedHandleToPackage (const FPackagePath &PackagePath, EPackageSegment PackageSegment, FPackagePath *OutUpdatedPath=nullptr)=0
IMappedFileHandle * OpenMappedHandleToPackage (const FPackagePath &PackagePath, FPackagePath *OutUpdatedPath=nullptr)
Open an IMappedFileHandle to the package, if the PackageResourceManager supports it.
virtual TUniquePtr< FArchive > OpenReadExternalResource (EPackageExternalResource ResourceType, FStringView Identifier)=0
Open a seekable binary FArchive to read the bytes of the given External Resource.
FOpenPackageResult OpenReadPackage (const FPackagePath &PackagePath, FPackagePath *OutUpdatedPath=nullptr)
Open an FArchive to read the bytes of the package.
virtual bool SupportsLocalOnlyPaths ()=0
Report whether the PackageResourceManager supports PackagePaths that are unmounted LocalPaths.
virtual bool SupportsPackageOnlyPaths ()=0
Report whether the PackageResourceManager supports PackagePaths that are unmounted PackageNames.
virtual bool TryMatchCaseOnDisk (const FPackagePath &PackagePath, FPackagePath *OutNormalizedPath=nullptr)=0
Find the package in the package repository and set OutNormalizedPath equal to PackagePath, but with capitalization of the PackageName and LocalPath matching the capitalization present in the package repository's internal path string (e.g.
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") bool DoesPackageExist(const FPackagePath &PackagePath
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") FOpenAsyncPackageResult OpenAsyncReadPackage(const FPackagePath &PackagePath
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") FOpenPackageResult OpenReadPackage(const FPackagePath &PackagePath
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") int64 FileSize(const FPackagePath &PackagePath
Static Public Member Functions
static IPackageResourceManager & Get ()
Returns the package resource manager.
static FOnClearPackageResourceManager & GetOnClearPackageResourceManagerDelegate ()
static FSetPackageResourceManager & GetSetPackageResourceManagerDelegate ()
static void Initialize ()
Call during engine startup to choose the appropriate PackageResourceManager for the current configuration and construct it and bind it to be returned from Get.
static void Shutdown ()
Call during engine shutdown to free the PackageResourceManager that was created by Initialize; Get will and return nullptr from this point on.
static bool TryRegisterPreloadableArchive (const FPackagePath &PackagePath, const TSharedPtr< FPreloadableArchive > &PreloadableArchive, const FOpenPackageResult &PackageFormat)
Try to register the given FPreloadableFile instance to handle the next call to TryTakePreloadableArchive for its PackagePath.
static bool TryTakePreloadableArchive (const FPackagePath &PackagePath, FOpenPackageResult &OutResult)
Look up an FPreloadableFile instance registered for the given PackagePath, and return an FOpenPackageResult from it.
static bool UnRegisterPreloadableArchive (const FPackagePath &PackagePath)
Remove any FPreloadableArchive instance that is registered for the given PackagePath.
Data Fields
EPackageSegment FPackagePath * OutUpdatedPath
EPackageSegment PackageSegment
Static Private Attributes
static TMap< FName, TPair< TSharedPtr< FPreloadableArchive >, FOpenPackageResult > > PreloadedPaths
static FCriticalSection PreloadedPathsLock
Detailed Description
Provides directory queries and Archive payloads for PackagePaths and their PackageSegments from a repository that might be the local content directories, a database running on the current machine, or a remote database.
Definition at line 119 of file PackageResourceManager.h.
Member Typedef Documentation
FPackagePathStatVisitor
typedef TFunctionRef<bool(const FPackagePath& PackagePath, const FFileStatData& StatData)> IPackageResourceManager::FPackagePathStatVisitor
Return value specifies whether iteration should continue.
Definition at line 276 of file PackageResourceManager.h.
FPackagePathVisitor
typedef TFunctionRef<bool(const FPackagePath& PackagePath)> IPackageResourceManager::FPackagePathVisitor
Return value specifies whether iteration should continue.
Definition at line 274 of file PackageResourceManager.h.
FPackageSegmentStatVisitor
typedef TFunctionRef<bool(const FPackagePath& PackagePath, EPackageSegment PackageSegment, const FFileStatData& StatData)> IPackageResourceManager::FPackageSegmentStatVisitor
Return value specifies whether iteration should continue.
Definition at line 397 of file PackageResourceManager.h.
FPackageSegmentVisitor
typedef TFunctionRef<bool(const FPackagePath& PackagePath, EPackageSegment PackageSegment)> IPackageResourceManager::FPackageSegmentVisitor
Return value specifies whether iteration should continue.
Definition at line 395 of file PackageResourceManager.h.
Constructor & Destructor Documentation
~IPackageResourceManager()
virtual IPackageResourceManager::~IPackageResourceManager () virtual default
Member Function Documentation
DoesExternalResourceExist()
virtual bool IPackageResourceManager::DoesExternalResourceExist (EPackageExternalResource ResourceType, FStringView Identifier) pure virtual
Report whether a given ExternalResource exists.
The same behavior as OpenReadExternalResource != nullptr, but more performant.
Parameters
ResourceType Id for the method used to map the identifier to an archive.
Identifier Id for which resource to return within the ResourceType's domain.
Returns
true if the ExternalResource exists, else false
DoesPackageExist()
bool IPackageResourceManager::DoesPackageExist (const FPackagePath & PackagePath, FPackagePath * OutUpdatedPath = nullptr)
Report whether the package exists.
Parameters
PackagePath The package to look for
OutUpdatedPath If non-null and the package is found, PackagePath is copied into this path (noop if OutUpdatedPath == &PackagePath), and if the package exists, the specific extension found is set
Returns
true if the package exists, else false
References OutUpdatedPath, and PackagePath.
FileSize()
int64 IPackageResourceManager::FileSize (const FPackagePath & PackagePath, FPackagePath * OutUpdatedPath = nullptr)
Report the payload size of the package.
Parameters
PackagePath The package to look for
OutUpdatedPath If non-null and the package is found, PackagePath is copied into this path (noop if OutUpdatedPath == &PackagePath), and if the package exists, the specific extension found is set
Returns
The size in bytes of the package, or INDEX_NONE if it isn't found
References OutUpdatedPath, and PackagePath.
Referenced by UE_DEPRECATED().
FindPackagesRecursive() [1/2]
void IPackageResourceManager::FindPackagesRecursive (TArray< FPackagePath > & OutPackages, FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FStringView BasenameWildcard)
Search the given subdirectory of a package mount for all packages with the given package basename in the package repository.
Parameters
OutPackages The list of packages found
PackageMount The package name of the mount point to look under
FileMount The local file path of the mount point to look under, must be the local file path that corresponds to PackageMount
RootRelPath A relative path from PackageMount that specifies the subdirectory of the mount point to use as the root of the search
BasenameWildcard The basenamewithoutpath to look for BasenameWildcard can not include path or extension; / and . are invalid characters BasenameWildcard can include *?-type wildcards (FString::MatchesWildcard)
FindPackagesRecursive() [2/2]
virtual void IPackageResourceManager::FindPackagesRecursive (TArray< TPair< FPackagePath, EPackageSegment > > & OutPackages, FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FStringView BasenameWildcard) pure virtual
FindPackagesRecursive that returns PackageSegments.
Get()
IPackageResourceManager & IPackageResourceManager::Get () static
Returns the package resource manager.
It is illegal to call Get before calling initialize.
GetOnClearPackageResourceManagerDelegate()
FOnClearPackageResourceManager & IPackageResourceManager::GetOnClearPackageResourceManagerDelegate () static
GetSetPackageResourceManagerDelegate()
FSetPackageResourceManager & IPackageResourceManager::GetSetPackageResourceManagerDelegate () static
Initialize()
void IPackageResourceManager::Initialize () static
Call during engine startup to choose the appropriate PackageResourceManager for the current configuration and construct it and bind it to be returned from Get.
IteratePackagesInLocalOnlyDirectory() [1/2]
void IPackageResourceManager::IteratePackagesInLocalOnlyDirectory (FStringView RootDir, FPackagePathVisitor Callback)
Call the callback on all packages in the given local path.
PackageResourceManagers that do not support LocalOnly paths will return without calling the Callback
Parameters
RootDir The local path on disk to search
Callback The callback called on each package
IteratePackagesInLocalOnlyDirectory() [2/2]
virtual void IPackageResourceManager::IteratePackagesInLocalOnlyDirectory (FStringView RootDir, FPackageSegmentVisitor Callback) pure virtual
IteratePackagesInLocalOnlyDirectory that takes a FPackageSegmentStatVisitor.
IteratePackagesInPath() [1/2]
void IPackageResourceManager::IteratePackagesInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackagePathVisitor Callback)
Call the callback on all packages in the package repository that are in the given subdirectory of a package mount.
Parameters
PackageMount The package name of the mount point's to look under
FileMount The local file path of the mount point to look under, must be the local file path that corresponds to PackageMount
RootRelPath A relative path from PackageMount that specifies the subdirectory of the mount point to use as the root of the search
Callback The callback called on each package
IteratePackagesInPath() [2/2]
virtual void IPackageResourceManager::IteratePackagesInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackageSegmentVisitor Callback) pure virtual
IteratePackagesInPath that takes a FPackageSegmentVisitor.
IteratePackagesStatInLocalOnlyDirectory() [1/2]
void IPackageResourceManager::IteratePackagesStatInLocalOnlyDirectory (FStringView RootDir, FPackagePathStatVisitor Callback)
Call the callback - with stat data - on all packages in the given local path.
PackageResourceManagers that do not support LocalOnly paths will return without calling the Callback
Parameters
RootDir The local path on disk to search
Callback The callback called on each package
bOutSupported If nonnull, receives a true or false value for whether this PackageResourceManager supports searching LocalOnlyDirectories
IteratePackagesStatInLocalOnlyDirectory() [2/2]
virtual void IPackageResourceManager::IteratePackagesStatInLocalOnlyDirectory (FStringView RootDir, FPackageSegmentStatVisitor Callback) pure virtual
IteratePackagesStatInLocalOnlyDirectory that takes a FPackageSegmentStatVisitor.
IteratePackagesStatInPath() [1/2]
void IPackageResourceManager::IteratePackagesStatInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackagePathStatVisitor Callback)
Call the callback - with stat data - on all packages in the package repository that are in the given subdirectory of a package mount.
Parameters
PackageMount The package name of the mount point's to look under
FileMount The local file path of the mount point to look under, must be the local file path that corresponds to PackageMount
RootRelPath A relative path from PackageMount that specifies the subdirectory of the mount point to use as the root of the search
Callback The callback called on each package
IteratePackagesStatInPath() [2/2]
virtual void IPackageResourceManager::IteratePackagesStatInPath (FStringView PackageMount, FStringView FileMount, FStringView RootRelPath, FPackageSegmentStatVisitor Callback) pure virtual
IteratePackagesStatInPath that takes a FPackageSegmentVisitor.
OpenAsyncReadExternalResource()
virtual FOpenAsyncPackageResult IPackageResourceManager::OpenAsyncReadExternalResource (EPackageExternalResource ResourceType, FStringView Identifier) pure virtual
Open an IAsyncReadFileHandle to asynchronously read the bytes of the given ExternalResource.
An ExternalResource is in a separate domain from the one out of which this ResourceManager serves PackagePaths.
TODO: This call should not hit the disk/network or block, but it currently does, to find the extension. This call will always return a non-null handle, even if the package does not exist
Parameters
ResourceType Id for the method used to map the identifier to an archive.
Identifier Id for which resource to return within the ResourceType's domain.
Returns
An FOpenAsyncPackageResult, with Handle that will read from the package if it exists, or will be in the canceled state if the package does not exist, and with other data describing the returned archive (see FOpenAsyncPackageResult)
OpenAsyncReadPackage() [1/2]
FOpenAsyncPackageResult IPackageResourceManager::OpenAsyncReadPackage (const FPackagePath & PackagePath)
Open an IAsyncReadFileHandle to asynchronously read the bytes of the package.
If the PackagePath specifies the extension, this call does not hit the disk/network or block. Otherwise, this call will read from network/disk to find the extension This call will always return a non-null handle, even if the package does not exist
Parameters
PackagePath The package to look for
Returns
An FOpenAsyncPackageResult, with Handle that will read from the package if it exists, or will be in the canceled state if the package does not exist, and with other data describing the returned archive (see FOpenAsyncPackageResult)
References PackagePath.
Referenced by UE_DEPRECATED().
OpenAsyncReadPackage() [2/2]
virtual FOpenAsyncPackageResult IPackageResourceManager::OpenAsyncReadPackage (const FPackagePath & PackagePath, FBulkDataCookedIndex CookedIndex, EPackageSegment PackageSegment) pure virtual
OpenAsyncReadPackage that takes a PackageSegment.
References PackagePath, and PackageSegment.
OpenMappedHandleToPackage() [1/2]
virtual IMappedFileHandle * IPackageResourceManager::OpenMappedHandleToPackage (const FPackagePath & PackagePath, EPackageSegment PackageSegment, FPackagePath * OutUpdatedPath = nullptr) pure virtual
References OutUpdatedPath, PackagePath, and PackageSegment.
OpenMappedHandleToPackage() [2/2]
IMappedFileHandle * IPackageResourceManager::OpenMappedHandleToPackage (const FPackagePath & PackagePath, FPackagePath * OutUpdatedPath = nullptr)
Open an IMappedFileHandle to the package, if the PackageResourceManager supports it.
Will return nullptr if the package does not exist or if the PackageResourceManager does not support MappedFilesHandles
Parameters
PackagePath The package to look for
OutUpdatedPath If non-null and the package is found, PackagePath is copied into this path (noop if OutUpdatedPath == &PackagePath), and if the package exists, the specific extension found is set
Returns
IMappedFileHandle* or nullptr
References OutUpdatedPath, and PackagePath.
OpenReadExternalResource()
virtual TUniquePtr< FArchive > IPackageResourceManager::OpenReadExternalResource (EPackageExternalResource ResourceType, FStringView Identifier) pure virtual
Open a seekable binary FArchive to read the bytes of the given External Resource.
An ExternalResource is in a separate domain from the one out of which this ResourceManager serves PackagePaths.
Parameters
ResourceType Id for the method used to map the identifier to an archive.
Identifier Id for which resource to return within the ResourceType's domain.
Returns
The opened FArchive, or nullptr if it wasn't found.
OpenReadPackage()
FOpenPackageResult IPackageResourceManager::OpenReadPackage (const FPackagePath & PackagePath, FPackagePath * OutUpdatedPath = nullptr)
Open an FArchive to read the bytes of the package.
Parameters
PackagePath The package to look for
OutUpdatedPath If non-null and the package is found, PackagePath is copied into this path (noop if OutUpdatedPath == &PackagePath), and if the package exists, the specific extension found is set
Returns
An FOpenPackageResult, with Result.Archive == archive for the bytes of the package or nullptr if it isn't found, and with other data describing the returned archive (see FOpenPackageResult)
References OutUpdatedPath, and PackagePath.
Referenced by UE_DEPRECATED().
Shutdown()
void IPackageResourceManager::Shutdown () static
Call during engine shutdown to free the PackageResourceManager that was created by Initialize; Get will and return nullptr from this point on.
SupportsLocalOnlyPaths()
virtual bool IPackageResourceManager::SupportsLocalOnlyPaths () pure virtual
Report whether the PackageResourceManager supports PackagePaths that are unmounted LocalPaths.
If unsupported, functions without LocalOnly in their name that take a PackagePath will behave as if the package does not exist in the repository for unmounted LocalPaths If unsupported, functions with LocalOnly in their name will indicate the lack of support when called with unmounted LocalPaths; see each function's description for its precise behavior
SupportsPackageOnlyPaths()
virtual bool IPackageResourceManager::SupportsPackageOnlyPaths () pure virtual
Report whether the PackageResourceManager supports PackagePaths that are unmounted PackageNames.
If unsupported, functions without PackageNameOnly in their name that take a PackagePath will behave as if the package does not exist in the repository for unmounted PackageNames If unsupported, functions with PackageNameOnly in their name will indicate the lack of support when called with unmounted PackageNames; see each function's description for its precise behavior
TryMatchCaseOnDisk()
virtual bool IPackageResourceManager::TryMatchCaseOnDisk (const FPackagePath & PackagePath, FPackagePath * OutNormalizedPath = nullptr) pure virtual
Find the package in the package repository and set OutNormalizedPath equal to PackagePath, but with capitalization of the PackageName and LocalPath matching the capitalization present in the package repository's internal path string (e.g.
the path on disk)
Parameters
PackagePath The package to look for
OutNormalizedPath If non-null and the package is found, PackagePath is copied into this path (noop if OutUpdatedPath == &PackagePath), with matching capitalization and with the specific extension found
Returns
true if the package exists, else false
References PackagePath.
TryRegisterPreloadableArchive()
bool IPackageResourceManager::TryRegisterPreloadableArchive (const FPackagePath & PackagePath, const TSharedPtr< FPreloadableArchive > & PreloadableArchive, const FOpenPackageResult & PackageFormat) static
Try to register the given FPreloadableFile instance to handle the next call to TryTakePreloadableArchive for its PackagePath.
Only works on PackagePaths with PackageName, will fail on unmounted LocalOnly paths. Will fail if the instance has not been initialized or if another instance has already registered for the PackagePath. Return whether the instance is currently registered. Returns true if the instance was already registered. Registered files are referenced-counted, and the reference will not be dropped until TryTakePreloadableArchive or UnRegister is called
Parameters
PackagePath The path to registry to return the Archive
PreloadableArchive The archive to return from TryTakePreloadableArchive
PackageFormat The format of the archive, as returned from OpenReadPackage
Returns
True if and only if the archive is now registered for the packagepath, False if the packagepath could not be registered or a different archive was already registered
References PackagePath.
TryTakePreloadableArchive()
bool IPackageResourceManager::TryTakePreloadableArchive (const FPackagePath & PackagePath, FOpenPackageResult & OutResult) static
Look up an FPreloadableFile instance registered for the given PackagePath, and return an FOpenPackageResult from it.
If found, removes the registration so no future call to TryTakePreloadableArchive can use the same FArchive. If the instance is in PreloadHandle mode, the Lower-Level FArchive will be detached from the FPreloadableFile and returned using DetachLowerLevel. If the instance is in PreloadBytes mode, a ProxyArchive will be returned that forwards call to the FPreloadableFile instance.
References PackagePath.
UE_DEPRECATED() [1/4]
IPackageResourceManager::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") const &
UE_DEPRECATED() [2/4]
IPackageResourceManager::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") const &
References FBulkDataCookedIndex::Default, OpenAsyncReadPackage(), PackagePath, and PackageSegment.
UE_DEPRECATED() [3/4]
IPackageResourceManager::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") const &
References FBulkDataCookedIndex::Default, OpenReadPackage(), OutUpdatedPath, PackagePath, and PackageSegment.
UE_DEPRECATED() [4/4]
IPackageResourceManager::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") const &
References FBulkDataCookedIndex::Default, FileSize(), OutUpdatedPath, PackagePath, and PackageSegment.
UnRegisterPreloadableArchive()
bool IPackageResourceManager::UnRegisterPreloadableArchive (const FPackagePath & PackagePath) static
Remove any FPreloadableArchive instance that is registered for the given PackagePath.
Returns
True if there was an archive registered for the PackagePath
References PackagePath.
Field Documentation
OutUpdatedPath
EPackageSegment FPackagePath * IPackageResourceManager::OutUpdatedPath
Initial value:
= nullptr)
    {
        return DoesPackageExist(PackagePath, FBulkDataCookedIndex::Default, PackageSegment, OutUpdatedPath);
    }
    virtual bool DoesPackageExist(const FPackagePath& PackagePath, FBulkDataCookedIndex CookedIndex,
        EPackageSegment PackageSegment, FPackagePath* OutUpdatedPath = nullptr) = 0
Definition at line 346 of file PackageResourceManager.h.
Referenced by DoesPackageExist(), FileSize(), OpenMappedHandleToPackage(), OpenMappedHandleToPackage(), OpenReadPackage(), UE_DEPRECATED(), and UE_DEPRECATED().
PackageSegment
EPackageSegment IPackageResourceManager::PackageSegment
Initial value:
{
        return OpenAsyncReadPackage(PackagePath, FBulkDataCookedIndex::Default, PackageSegment)
Definition at line 345 of file PackageResourceManager.h.
Referenced by OpenAsyncReadPackage(), OpenMappedHandleToPackage(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
PreloadedPaths
TMap<FName, TPair<TSharedPtr<FPreloadableArchive>, FOpenPackageResult> > IPackageResourceManager::PreloadedPaths static private
Definition at line 453 of file PackageResourceManager.h.
PreloadedPathsLock
FCriticalSection IPackageResourceManager::PreloadedPathsLock static private
Definition at line 454 of file PackageResourceManager.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/PackageResourceManager.h