Unreal Engine 5.6 C++ API: FRPCDoSDetection::FTickScope Class Reference
FRPCDoSDetection::FTickScope Class Reference
Variables and functions that should only be accessible during TickDispatch.
Public Member Functions
void CondCheckCountQuota (FRPCDoSDetection &This)
Wrapper for CondCheckCountQuota which forces FTickScope acquisition.
void CondCheckTimeQuota (FRPCDoSDetection &This, double TimeSeconds)
Wrapper for CondCheckTimeQuota which forces FTickScope acquisition.
void Reset ()
void UpdateSeverity (FRPCDoSDetection &This, ERPCDoSSeverityUpdate Update, ERPCDoSEscalateReason Reason)
Wrapper for UpdateSeverity which forces FTickScope acquisition.
Public Member Functions inherited from FRPCDoSDetection::TScopeBase< FTickScope >
bool IsActive () const
Whether or not the current code scope is active.
void Reset ()
Resets the properties covered by this scope, at both the start/end of the scope.
void SetActive (bool bInVal)
Sets whether or not the current code scope is active.
Data Fields
FRPCDoSCounters FrameCounter
Per-frame RPC counting (multiple disjointed packets may be processed for same connection, during a frame)
Detailed Description
Variables and functions that should only be accessible during TickDispatch.
Definition at line 947 of file RPCDoSDetection.h.
Member Function Documentation
CondCheckCountQuota()
void FRPCDoSDetection::FTickScope::CondCheckCountQuota (FRPCDoSDetection & This) inline
Wrapper for CondCheckCountQuota which forces FTickScope acquisition.
Definition at line 957 of file RPCDoSDetection.h.
Referenced by FRPCDoSDetection::PostReceivedRPC().
CondCheckTimeQuota()
void FRPCDoSDetection::FTickScope::CondCheckTimeQuota (FRPCDoSDetection & This, double TimeSeconds) inline
Wrapper for CondCheckTimeQuota which forces FTickScope acquisition.
Definition at line 963 of file RPCDoSDetection.h.
Reset()
void FRPCDoSDetection::FTickScope::Reset () inline
Definition at line 968 of file RPCDoSDetection.h.
References FrameCounter.
UpdateSeverity()
void FRPCDoSDetection::FTickScope::UpdateSeverity (FRPCDoSDetection & This, ERPCDoSSeverityUpdate Update, ERPCDoSEscalateReason Reason) inline
Wrapper for UpdateSeverity which forces FTickScope acquisition.
Definition at line 951 of file RPCDoSDetection.h.
References FRPCDoSDetection::Reason.
Referenced by FRPCDoSDetection::CondCheckCountQuota(), and FRPCDoSDetection::CondCheckTimeQuota().
Field Documentation
FrameCounter
FRPCDoSCounters FRPCDoSDetection::FTickScope::FrameCounter
Per-frame RPC counting (multiple disjointed packets may be processed for same connection, during a frame)
Definition at line 975 of file RPCDoSDetection.h.
Referenced by FRPCDoSDetection::CondCheckCountQuota(), FRPCDoSDetection::CondCheckTimeQuota(), FRPCDoSDetection::PostReceivedRPC(), and Reset().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Net/RPCDoSDetection.h