Unreal Engine 5.6 C++ API: SPopupErrorText Class Reference
SPopupErrorText Class Reference
#include "SPopUpErrorText.h"
Public Member Functions
virtual TSharedRef< SWidget > AsWidget () override
virtual bool HasError () const override
virtual void SetError (const FString &InErrorText) override
virtual void SetError (const FText &InErrorText) override
SLATE_ARGUMENT (bool, ShowInNewWindow) SLATE_ATTRIBUTE(FSlateFontInfo
The popup appears in a new window instead of in the same window that this widget is in.
SLATE_BEGIN_ARGS (SPopupErrorText)
Font SLATE_END_ARGS () 1 virtual void Construct(const FArguments &InArgs)
Public Member Functions inherited from SComboButton
void Construct (const FArguments &InArgs)
Construct the widget from a declaration.
void SetButtonContentPadding (FMargin InPadding)
See the padding for button content.
void SetHasDownArrow (bool InHasArrowDown)
add/remove the expanding arrow.
void SetMenuContentWidgetToFocus (TWeakPtr< SWidget > InWidgetToFocusPtr)
void SetOnGetMenuContent (FOnGetContent InOnGetMenuContent)
See the OnGetMenuContent event.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign Method SLATE_ARGUMENT (bool, CollapseMenuOnParentFocus) SLATE_END_ARGS() 1 virtual void SetMenuContent(TSharedRef< SWidget > InContent) override
True if this combo's menu should be collapsed when our parent receives focus, false (default) otherwise.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable SLATE_ARGUMENT (bool, HasDownArrow) SLATE_ATTRIBUTE(FSlateColor
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding HAlign SLATE_ARGUMENT (EVerticalAlignment, VAlign) SLATE_ARGUMENT(TOptional< EPopupMethod >
Spawn a new window or reuse current window for this combo.
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor ContentPadding SLATE_ATTRIBUTE (EMenuPlacement, MenuPlacement) SLATE_ARGUMENT(EHorizontalAlignment
ButtonStyle MenuContent OnMenuOpenChanged IsFocusable ForegroundColor SLATE_ATTRIBUTE (FSlateColor, ButtonColorAndOpacity) SLATE_ATTRIBUTE(FMargin
SLATE_BEGIN_ARGS (SComboButton)
ButtonStyle MenuContent OnMenuOpenChanged SLATE_EVENT (FOnComboBoxOpened, OnComboBoxOpened) SLATE_ARGUMENT(bool
ButtonStyle MenuContent SLATE_EVENT (FOnGetContent, OnGetMenuContent) SLATE_EVENT(FOnIsOpenChanged
Sets an event handler to generate a widget dynamically when the menu is needed.
ButtonStyle SLATE_NAMED_SLOT (FArguments, ButtonContent) SLATE_NAMED_SLOT(FArguments
Optional static menu content.
SLATE_STYLE_ARGUMENT (FComboButtonStyle, ComboButtonStyle) SLATE_STYLE_ARGUMENT(FButtonStyle
The visual style of the button (overrides ComboButtonStyle)
Private Attributes
TSharedPtr< SErrorText > ErrorText
TSharedPtr< SErrorText > HasErrorSymbol
Additional Inherited Members
Protected Member Functions inherited from SComboButton
FText GetFilteredToolTipText (TAttribute< FText > ToolTipText) const
Called to query the tool tip text for this widget, but will return an empty text when the menu is already open.
virtual FReply OnButtonClicked ()
Handle the button being clicked by summoning the ComboButton.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Protected Attributes inherited from SComboButton
bool bIsFocusable
Can this button be focused?
SHorizontalBox::FSlot * ButtonContentSlot
Area where the button's content resides.
TWeakPtr< SWidget > ContentWidgetPtr
The content widget, if any, set by the user on creation.
const FSlateBrush * MenuBorderBrush
Brush to use to add a "menu border" around the drop-down content.
FMargin MenuBorderPadding
Padding to use to add a "menu border" around the drop-down content.
FOnComboBoxOpened OnComboBoxOpened
Delegate to execute when the combo list is opened.
TWeakPtr< SWidget > WidgetToFocusPtr
Detailed Description
Definition at line 12 of file SPopUpErrorText.h.
Member Function Documentation
AsWidget()
virtual TSharedRef< SWidget > SPopupErrorText::AsWidget () override virtual
Implements IErrorReportingWidget.
References AsWidget().
Referenced by AsWidget().
HasError()
virtual bool SPopupErrorText::HasError () const override virtual
Implements IErrorReportingWidget.
References HasError().
Referenced by HasError().
SetError() [1/2]
virtual void SPopupErrorText::SetError (const FString & InErrorText) override virtual
Implements IErrorReportingWidget.
References SetError().
SetError() [2/2]
virtual void SPopupErrorText::SetError (const FText & InErrorText) override virtual
Implements IErrorReportingWidget.
References SetError().
Referenced by SetError(), and SetError().
SLATE_ARGUMENT()
SPopupErrorText::SLATE_ARGUMENT (bool , ShowInNewWindow)
The popup appears in a new window instead of in the same window that this widget is in.
SLATE_BEGIN_ARGS()
SPopupErrorText::SLATE_BEGIN_ARGS (SPopupErrorText) inline
Definition at line 15 of file SPopUpErrorText.h.
SLATE_END_ARGS()
Font SPopupErrorText::SLATE_END_ARGS () const &
References SComboButton::Construct(), and SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Field Documentation
ErrorText
TSharedPtr<SErrorText> SPopupErrorText::ErrorText private
Definition at line 39 of file SPopUpErrorText.h.
HasErrorSymbol
TSharedPtr<SErrorText> SPopupErrorText::HasErrorSymbol private
Definition at line 38 of file SPopUpErrorText.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Notifications/SPopUpErrorText.h