Unreal Engine 5.6 C++ API: FConsoleCommandExecutor Class Reference
FConsoleCommandExecutor Class Reference
Executor for Unreal console commands.
#include "FConsoleCommandExecutor.h"
Public Member Functions
virtual UNREALED_API bool AllowHotKeyClose () const override
True if we allow the console to be closed using the "open console" hot-key.
virtual UNREALED_API bool AllowMultiLine () const override
True if we allow the console to create multi-line commands.
virtual UNREALED_API bool Exec (const TCHAR *Input) override
Execute the given command using this executor.
virtual UNREALED_API FText GetDescription () const override
Get the description of this executor.
virtual UNREALED_API FText GetDisplayName () const override
Get the display name of this executor.
virtual UNREALED_API void GetExecHistory (TArray< FString > &Out) override
Get the list of commands that this executor has recently processed.
virtual UNREALED_API FText GetHintText () const override
Get the hint text of this executor.
virtual FInputChord GetHotKey () const override
Returns the hotkey for this executor.
virtual FInputChord GetIterateExecutorHotKey () const override
Returns the hotkey to switch to the next executor.
virtual UNREALED_API FName GetName () const override
Get the name of this executor.
virtual UNREALED_API void GetSuggestedCompletions (const TCHAR *Input, TArray< FConsoleSuggestion > &Out) override
Get the list of auto-complete suggestions for the given command.
Public Member Functions inherited from IConsoleCommandExecutor
virtual ~IConsoleCommandExecutor ()=default
UE_DEPRECATED (5.5, "Use GetSuggestedCompletions instead") virtual void GetAutoCompleteSuggestions(const TCHAR *Input
Get the list of auto-complete suggestions for the given command.
Static Public Member Functions
static UNREALED_API FName StaticName ()
Static Public Member Functions inherited from IConsoleCommandExecutor
static FName ModularFeatureName ()
Get the name identifying this modular feature set.
Private Member Functions
UNREALED_API bool ExecInternal (const TCHAR *) const
Additional Inherited Members
Data Fields inherited from IConsoleCommandExecutor
TArray< FString > & Out {}
Detailed Description
Executor for Unreal console commands.
Definition at line 13 of file FConsoleCommandExecutor.h.
Member Function Documentation
AllowHotKeyClose()
virtual UNREALED_API bool FConsoleCommandExecutor::AllowHotKeyClose () const override virtual
True if we allow the console to be closed using the "open console" hot-key.
Note
Some scripting languages use the default "open console" hot-key (~) in their code, so these should return false.
Implements IConsoleCommandExecutor.
AllowMultiLine()
virtual UNREALED_API bool FConsoleCommandExecutor::AllowMultiLine () const override virtual
True if we allow the console to create multi-line commands.
Implements IConsoleCommandExecutor.
Exec()
virtual UNREALED_API bool FConsoleCommandExecutor::Exec (const TCHAR * Input) override virtual
Execute the given command using this executor.
Returns
true if the command was recognized.
Implements IConsoleCommandExecutor.
References Input.
ExecInternal()
UNREALED_API bool FConsoleCommandExecutor::ExecInternal (const TCHAR *) const private
GetDescription()
virtual UNREALED_API FText FConsoleCommandExecutor::GetDescription () const override virtual
Get the description of this executor.
Implements IConsoleCommandExecutor.
GetDisplayName()
virtual UNREALED_API FText FConsoleCommandExecutor::GetDisplayName () const override virtual
Get the display name of this executor.
Implements IConsoleCommandExecutor.
GetExecHistory()
virtual UNREALED_API void FConsoleCommandExecutor::GetExecHistory (TArray< FString > & Out) override virtual
Get the list of commands that this executor has recently processed.
Implements IConsoleCommandExecutor.
References IConsoleCommandExecutor::Out.
GetHintText()
virtual UNREALED_API FText FConsoleCommandExecutor::GetHintText () const override virtual
Get the hint text of this executor.
Implements IConsoleCommandExecutor.
GetHotKey()
virtual FInputChord FConsoleCommandExecutor::GetHotKey () const inline override virtual
Returns the hotkey for this executor.
Implements IConsoleCommandExecutor.
Definition at line 27 of file FConsoleCommandExecutor.h.
References TCommands< FGlobalEditorCommonCommands >::Get(), FUICommandInfo::GetActiveChord(), and FGlobalEditorCommonCommands::OpenConsoleCommandBox.
GetIterateExecutorHotKey()
virtual FInputChord FConsoleCommandExecutor::GetIterateExecutorHotKey () const inline override virtual
Returns the hotkey to switch to the next executor.
This is usually the same hotkey as GetHotKey but with a modifier, such as "`" turning into "Ctrl + `".
Implements IConsoleCommandExecutor.
Definition at line 32 of file FConsoleCommandExecutor.h.
References TCommands< FGlobalEditorCommonCommands >::Get(), FUICommandInfo::GetActiveChord(), and FGlobalEditorCommonCommands::SelectNextConsoleExecutor.
GetName()
virtual UNREALED_API FName FConsoleCommandExecutor::GetName () const override virtual
Get the name of this executor.
Implements IConsoleCommandExecutor.
GetSuggestedCompletions()
virtual UNREALED_API void FConsoleCommandExecutor::GetSuggestedCompletions (const TCHAR * Input, TArray< FConsoleSuggestion > & Out) override virtual
Get the list of auto-complete suggestions for the given command.
Implements IConsoleCommandExecutor.
References Input, and IConsoleCommandExecutor::Out.
StaticName()
UNREALED_API FName FConsoleCommandExecutor::StaticName () static
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Toolkits/FConsoleCommandExecutor.h