Unreal Engine 5.6 C++ API: FShadowMap Class Reference
FShadowMap Class Reference abstract
The abstract base class of 1D and 2D shadow-maps.
#include "ShadowMap.h"
Public Types
enum { SMT_None = 0 , SMT_2D = 2 }
Public Member Functions
FShadowMap ()
Default constructor.
FShadowMap (TArray< FGuid > InLightGuids)
virtual ~FShadowMap ()
Destructor.
void AddRef ()
virtual void AddReferencedObjects (FReferenceCollector &Collector)
bool ContainsLight (const FGuid &LightGuid) const
Checks if a light is stored in this shadow-map.
virtual FShadowMapInteraction GetInteraction () const =0
virtual FShadowMap2D * GetShadowMap2D ()
virtual const FShadowMap2D * GetShadowMap2D () const
void Release ()
virtual void Serialize (FArchive &Ar)
Data Fields
TArray< FGuid > LightGuids
The GUIDs of lights which this shadow-map stores.
Protected Member Functions
virtual void Cleanup ()
Called when the light-map is no longer referenced.
Private Attributes
int32 NumRefs
Additional Inherited Members
Private Member Functions inherited from FDeferredCleanupInterface
virtual ~FDeferredCleanupInterface ()
Detailed Description
The abstract base class of 1D and 2D shadow-maps.
Definition at line 226 of file ShadowMap.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SMT_None
SMT_2D
Definition at line 229 of file ShadowMap.h.
Constructor & Destructor Documentation
FShadowMap() [1/2]
FShadowMap::FShadowMap () inline
Default constructor.
Definition at line 239 of file ShadowMap.h.
References NumRefs.
FShadowMap() [2/2]
FShadowMap::FShadowMap (TArray< FGuid > InLightGuids) inline
Definition at line 244 of file ShadowMap.h.
References LightGuids, MoveTemp(), and NumRefs.
~FShadowMap()
virtual FShadowMap::~FShadowMap () inline virtual
Destructor.
Definition at line 251 of file ShadowMap.h.
References check, and NumRefs.
Member Function Documentation
AddRef()
void FShadowMap::AddRef () inline
Definition at line 273 of file ShadowMap.h.
References check, IsInAsyncLoadingThread, IsInGameThread(), and NumRefs.
AddReferencedObjects()
virtual void FShadowMap::AddReferencedObjects (FReferenceCollector & Collector) inline virtual
Reimplemented in FShadowMap2D.
Definition at line 264 of file ShadowMap.h.
Cleanup()
virtual void FShadowMap::Cleanup () protected virtual
Called when the light-map is no longer referenced.
Should release the lightmap's resources.
Referenced by Release().
ContainsLight()
bool FShadowMap::ContainsLight (const FGuid & LightGuid) const inline
Checks if a light is stored in this shadow-map.
Parameters
LightGuid - The GUID of the light to check for.
Returns
True if the light is stored in the light-map.
Definition at line 258 of file ShadowMap.h.
References INDEX_NONE, and LightGuids.
GetInteraction()
virtual FShadowMapInteraction FShadowMap::GetInteraction () const pure virtual
Implemented in FShadowMap2D.
GetShadowMap2D() [1/2]
virtual FShadowMap2D * FShadowMap::GetShadowMap2D () inline virtual
Reimplemented in FShadowMap2D.
Definition at line 269 of file ShadowMap.h.
GetShadowMap2D() [2/2]
virtual const FShadowMap2D * FShadowMap::GetShadowMap2D () const inline virtual
Reimplemented in FShadowMap2D.
Definition at line 270 of file ShadowMap.h.
Release()
void FShadowMap::Release () inline
Definition at line 278 of file ShadowMap.h.
References check, checkSlow, Cleanup(), IsInAsyncLoadingThread, IsInGameThread(), and NumRefs.
Serialize()
virtual void FShadowMap::Serialize (FArchive & Ar) virtual
Reimplemented in FShadowMap2D.
References Ar.
Field Documentation
LightGuids
TArray<FGuid> FShadowMap::LightGuids
The GUIDs of lights which this shadow-map stores.
Definition at line 236 of file ShadowMap.h.
Referenced by FShadowMap(), FShadowMap2D::FShadowMap2D(), and ContainsLight().
NumRefs
int32 FShadowMap::NumRefs private
Definition at line 296 of file ShadowMap.h.
Referenced by FShadowMap(), FShadowMap(), ~FShadowMap(), AddRef(), and Release().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ShadowMap.h