Unreal Engine 5.6 C++ API: FMessageLogScopedOverride Class Reference
FMessageLogScopedOverride Class Reference final
Scoped override for FMessageLog behavior.
#include "MessageLog.h"
Public Member Functions
FMessageLogScopedOverride (const FName InLogName)
~FMessageLogScopedOverride ()
FMessageLogScopedOverride & RemapMessageSeverity (const EMessageSeverity::Type SrcSeverity, const EMessageSeverity::Type DestSeverity)
Map category X to category Y when adding messages to this log.
FMessageLogScopedOverride & SuppressLoggingToOutputLog (const bool bShouldSuppress=true)
Should we mirror message log messages to the output log during flush?
UE_NONCOPYABLE (FMessageLogScopedOverride)
Private Attributes
TOptional< bool > bSuppressLoggingToOutputLog
FName LogName
TSortedMap< EMessageSeverity::Type, EMessageSeverity::Type > MessageSeverityRemapping
Friends
class FMessageLog
Detailed Description
Scoped override for FMessageLog behavior.
This can override the log behavior of a given named FMessageLog for the duration of the overrides lifetime, optionally suppressing output log mirroring, or promoting/demoting log categories (eg, to make errors act as warnings, or warnings act as errors).
Definition at line 155 of file MessageLog.h.
Constructor & Destructor Documentation
FMessageLogScopedOverride()
FMessageLogScopedOverride::FMessageLogScopedOverride (const FName InLogName) explicit
Referenced by RemapMessageSeverity(), SuppressLoggingToOutputLog(), and UE_NONCOPYABLE().
~FMessageLogScopedOverride()
FMessageLogScopedOverride::~FMessageLogScopedOverride ()
Member Function Documentation
RemapMessageSeverity()
FMessageLogScopedOverride & FMessageLogScopedOverride::RemapMessageSeverity (const EMessageSeverity::Type SrcSeverity, const EMessageSeverity::Type DestSeverity)
Map category X to category Y when adding messages to this log.
References FMessageLogScopedOverride().
SuppressLoggingToOutputLog()
FMessageLogScopedOverride & FMessageLogScopedOverride::SuppressLoggingToOutputLog (const bool bShouldSuppress = true)
Should we mirror message log messages to the output log during flush?
References FMessageLogScopedOverride().
UE_NONCOPYABLE()
FMessageLogScopedOverride::UE_NONCOPYABLE (FMessageLogScopedOverride)
References FMessageLogScopedOverride().
Friends And Related Symbol Documentation
FMessageLog
friend class FMessageLog friend
Definition at line 170 of file MessageLog.h.
References FMessageLog.
Referenced by FMessageLog.
Field Documentation
bSuppressLoggingToOutputLog
TOptional<bool> FMessageLogScopedOverride::bSuppressLoggingToOutputLog private
Definition at line 173 of file MessageLog.h.
LogName
FName FMessageLogScopedOverride::LogName private
Definition at line 172 of file MessageLog.h.
MessageSeverityRemapping
TSortedMap<EMessageSeverity::Type, EMessageSeverity::Type> FMessageLogScopedOverride::MessageSeverityRemapping private
Definition at line 174 of file MessageLog.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Logging/MessageLog.h