Unreal Engine 5.6 C++ API: FLocMetadataValueObject Class Reference
FLocMetadataValueObject Class Reference
A LocMetadata Object Value.
#include "InternationalizationMetadata.h"
Public Member Functions
FLocMetadataValueObject (FStructuredArchive::FSlot Slot)
FLocMetadataValueObject (TSharedPtr< FLocMetadataObject > InObject)
virtual TSharedPtr< FLocMetadataObject > AsObject () override
Returns this value as an object, throwing an error if this is not an Metadata Object.
virtual TSharedRef< FLocMetadataValue > Clone () const override
virtual ELocMetadataType GetType () const override
virtual FString ToString () const override
Public Member Functions inherited from FLocMetadataValue
virtual ~FLocMetadataValue ()=0
virtual TArray< TSharedPtr< FLocMetadataValue > > AsArray ()
Returns this value as an array, throwing an error if this is not an Metadata Array.
virtual bool AsBool ()
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
virtual FString AsString ()
Returns this value as a string, throwing an error if this is not a Metadata String.
bool operator< (const FLocMetadataValue &Other) const
bool operator== (const FLocMetadataValue &Other) const
Static Public Member Functions
static void Serialize (FLocMetadataValueObject &Value, FStructuredArchive::FSlot Slot)
Protected Member Functions
virtual bool EqualTo (const FLocMetadataValue &Other) const override
virtual FString GetTypeString () const override
virtual bool LessThan (const FLocMetadataValue &Other) const override
Protected Member Functions inherited from FLocMetadataValue
FLocMetadataValue ()
void ErrorMessage (const FString &InType)
Protected Attributes
TSharedPtr< FLocMetadataObject > Value
Detailed Description
A LocMetadata Object Value.
Definition at line 258 of file InternationalizationMetadata.h.
Constructor & Destructor Documentation
FLocMetadataValueObject() [1/2]
FLocMetadataValueObject::FLocMetadataValueObject (TSharedPtr< FLocMetadataObject > InObject) inline
Definition at line 261 of file InternationalizationMetadata.h.
References Value.
Referenced by Serialize().
FLocMetadataValueObject() [2/2]
FLocMetadataValueObject::FLocMetadataValueObject (FStructuredArchive::FSlot Slot)
Member Function Documentation
AsObject()
virtual TSharedPtr< FLocMetadataObject > FLocMetadataValueObject::AsObject () inline override virtual
Returns this value as an object, throwing an error if this is not an Metadata Object.
Reimplemented from FLocMetadataValue.
Definition at line 265 of file InternationalizationMetadata.h.
References Value.
Clone()
virtual TSharedRef< FLocMetadataValue > FLocMetadataValueObject::Clone () const override virtual
Implements FLocMetadataValue.
EqualTo()
virtual bool FLocMetadataValueObject::EqualTo (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
GetType()
virtual ELocMetadataType FLocMetadataValueObject::GetType () const inline override virtual
Implements FLocMetadataValue.
Definition at line 271 of file InternationalizationMetadata.h.
References Object.
GetTypeString()
virtual FString FLocMetadataValueObject::GetTypeString () const inline override protected virtual
Implements FLocMetadataValue.
Definition at line 279 of file InternationalizationMetadata.h.
References TEXT.
LessThan()
virtual bool FLocMetadataValueObject::LessThan (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
Serialize()
void FLocMetadataValueObject::Serialize (FLocMetadataValueObject & Value, FStructuredArchive::FSlot Slot) static
References FLocMetadataValueObject(), and Value.
ToString()
virtual FString FLocMetadataValueObject::ToString () const override virtual
Implements FLocMetadataValue.
Field Documentation
Value
TSharedPtr<FLocMetadataObject> FLocMetadataValueObject::Value protected
Definition at line 274 of file InternationalizationMetadata.h.
Referenced by FLocMetadataValueObject(), AsObject(), and Serialize().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/InternationalizationMetadata.h