Unreal Engine 5.6 C++ API: FCanvasRenderThreadScope Class Reference
FCanvasRenderThreadScope Class Reference
#include "CanvasRender.h"
Public Member Functions
FCanvasRenderThreadScope (const FCanvas &Canvas)
~FCanvasRenderThreadScope ()
template<typename ExecuteLambdaType>
void AddPass (const TCHAR *PassName, ExecuteLambdaType &&Lambda)
template<typename T>
void DeferredDelete (const T *Ptr)
void EnqueueRenderCommand (RenderCommandFunction &&Lambda)
Private Types
using RenderCommandFunction = TFunction<void(FCanvasRenderContext&)>
using RenderCommandFunctionArray = TArray<RenderCommandFunction>
Private Attributes
const FCanvas & Canvas
RenderCommandFunctionArray * RenderCommands
Detailed Description
Definition at line 94 of file CanvasRender.h.
Member Typedef Documentation
RenderCommandFunction
using FCanvasRenderThreadScope::RenderCommandFunction = TFunction<void(FCanvasRenderContext&)> private
Definition at line 96 of file CanvasRender.h.
RenderCommandFunctionArray
using FCanvasRenderThreadScope::RenderCommandFunctionArray = TArray<RenderCommandFunction> private
Definition at line 97 of file CanvasRender.h.
Constructor & Destructor Documentation
FCanvasRenderThreadScope()
FCanvasRenderThreadScope::FCanvasRenderThreadScope (const FCanvas & Canvas)
References Canvas.
~FCanvasRenderThreadScope()
FCanvasRenderThreadScope::~FCanvasRenderThreadScope ()
Member Function Documentation
AddPass()
template<typename ExecuteLambdaType> void FCanvasRenderThreadScope::AddPass (const TCHAR * PassName, ExecuteLambdaType && Lambda) inline
Definition at line 108 of file CanvasRender.h.
References FCanvasRenderContext::AddPass(), EnqueueRenderCommand(), Forward(), and RDG_EVENT_NAME.
DeferredDelete()
template<typename T> void FCanvasRenderThreadScope::DeferredDelete (const T * Ptr) inline
Definition at line 119 of file CanvasRender.h.
References FCanvasRenderContext::DeferredDelete(), and EnqueueRenderCommand().
EnqueueRenderCommand()
void FCanvasRenderThreadScope::EnqueueRenderCommand (RenderCommandFunction && Lambda) inline
Definition at line 102 of file CanvasRender.h.
References MoveTemp(), and RenderCommands.
Referenced by AddPass(), and DeferredDelete().
Field Documentation
Canvas
const FCanvas& FCanvasRenderThreadScope::Canvas private
Definition at line 128 of file CanvasRender.h.
Referenced by FCanvasRenderThreadScope().
RenderCommands
RenderCommandFunctionArray* FCanvasRenderThreadScope::RenderCommands private
Definition at line 129 of file CanvasRender.h.
Referenced by EnqueueRenderCommand().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/CanvasRender.h