Unreal Engine 5.6 C++ API: UBoxComponent Class Reference
UBoxComponent Class Reference
#include "BoxComponent.h"
Public Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual struct FCollisionShape GetCollisionShape (float Inflation=0.0f) const override
FEngineShowFlags GetShowFlags () const
FORCEINLINE void InitBoxExtent (const FVector &InBoxExtent)
virtual bool IsZeroExtent () const override
void SetShowFlags (const FEngineShowFlags &InShowFlags)
UFUNCTION () 1 FVector GetScaledBoxExtent() const
UFUNCTION () 1 FVector GetUnscaledBoxExtent() const
UFUNCTION () 1 void SetBoxExtent(FVector InBoxExtent
Change the box extent size.
virtual void UpdateBodySetup () override
Update the body setup parameters based on shape information.
Public Member Functions inherited from UShapeComponent
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual class UBodySetup * GetBodySetup () override
TSubclassOf< class UNavAreaBase > GetDesiredAreaClass () const
virtual bool GetIgnoreBoundsForEditorFocus () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
virtual bool IsNavigationRelevant () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void Serialize (FArchive &Ar) override
void SetAreaClassOverride (TSubclassOf< class UNavAreaBase > InAreaClassOverride)
void SetUseSystemDefaultObstacleAreaClass ()
virtual bool ShouldCollideWhenPlacing () const override
UFUNCTION () 1 void SetLineThickness(float Thickness)
Data Fields
bool bUpdateOverlaps =true)
Private Attributes
GENERATED_UCLASS_BODY() protected FEngineShowFlags ShowFlags
The extents (radii dimensions) of the box.
Additional Inherited Members
Protected Member Functions inherited from UShapeComponent
template<typename ShapeElemType>
void AddShapeToGeomArray ()
template<typename ShapeElemType>
void CreateShapeBodySetupIfNeeded ()
template<typename ComponentType>
bool PrepareSharedBodySetup ()
Checks if a shared body setup is available (and if we're eligible for it).
template<typename ShapeElemType>
void SetShapeToNewGeom (const FPhysicsShapeHandle &Shape)
UPROPERTY () float LineThickness
Used to control the line thickness when rendering.
UPROPERTY ()) TSubclassOf< class UNavAreaBase > AreaClassOverride
Navigation area type override, null / none = no change to nav mesh.
Protected Attributes inherited from UShapeComponent
UPROPERTY()) uint8 bUseSystemDefaultObstacleAreaClass uint8 bUseArchetypeBodySetup: 1
Only show this component if the actor is selected.
Detailed Description
Definition at line 18 of file BoxComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UBoxComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
Reimplemented from UShapeComponent.
References CalcBounds().
Referenced by CalcBounds().
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UBoxComponent::CreateSceneProxy () override virtual
Reimplemented from UShapeComponent.
References CreateSceneProxy().
Referenced by CreateSceneProxy().
GetCollisionShape()
virtual struct FCollisionShape UBoxComponent::GetCollisionShape (float Inflation = 0.0f) const override virtual
References GetCollisionShape().
Referenced by GetCollisionShape().
GetShowFlags()
FEngineShowFlags UBoxComponent::GetShowFlags () const inline
Definition at line 67 of file BoxComponent.h.
References ShowFlags.
InitBoxExtent()
FORCEINLINE void UBoxComponent::InitBoxExtent (const FVector & InBoxExtent) inline
Definition at line 64 of file BoxComponent.h.
References FORCEINLINE, FVector, and InitBoxExtent().
Referenced by InitBoxExtent().
IsZeroExtent()
virtual bool UBoxComponent::IsZeroExtent () const override virtual
References IsZeroExtent().
Referenced by IsZeroExtent().
SetShowFlags()
void UBoxComponent::SetShowFlags (const FEngineShowFlags & InShowFlags)
UFUNCTION() [1/3]
UBoxComponent::UFUNCTION () const
References Category, FVector, and UFUNCTION().
UFUNCTION() [2/3]
UBoxComponent::UFUNCTION () const
References Category, FVector, and UFUNCTION().
UFUNCTION() [3/3]
UBoxComponent::UFUNCTION ()
Change the box extent size.
This is the unscaled size, before component scale is applied.
Parameters
InBoxExtent new extent (radius) for the box.
bUpdateOverlaps if true and this shape is registered and collides, updates touching array for owner actor.
References Category.
Referenced by UFUNCTION(), and UFUNCTION().
UpdateBodySetup()
virtual void UBoxComponent::UpdateBodySetup () override virtual
Update the body setup parameters based on shape information.
Reimplemented from UShapeComponent.
References UpdateBodySetup().
Referenced by UpdateBodySetup().
Field Documentation
bUpdateOverlaps
bool UBoxComponent::bUpdateOverlaps =true)
Definition at line 39 of file BoxComponent.h.
ShowFlags
GENERATED_UCLASS_BODY () protected FEngineShowFlags UBoxComponent::ShowFlags private
The extents (radii dimensions) of the box.
List of all show flags this box component visualizer should respect.
Definition at line 29 of file BoxComponent.h.
Referenced by GetShowFlags().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/BoxComponent.h