Unreal Engine 5.6 C++ API: FUnrealEdMisc Class Reference
FUnrealEdMisc Class Reference
The public interface for the unreal editor misc singleton.
#include "UnrealEdMisc.h"
Public Member Functions
UNREALED_API FUnrealEdMisc ()
Constructor, private - use Get() function.
virtual UNREALED_API ~FUnrealEdMisc ()
Destructor.
UNREALED_API void BeginPerformanceSurvey ()
Start the performance survey that attempts to monitor editor performance in the default or simple startup maps.
UNREALED_API void CancelPerformanceSurvey ()
End the performance survey that attempts to monitor editor performance in the default or simple startup maps.
UNREALED_API void CB_DisplayLoadErrors ()
UNREALED_API void CB_EditorModeWindowClosed (const TSharedRef< SWindow > &)
UNREALED_API void CB_LevelActorsAdded (class AActor *InActor)
UNREALED_API void CB_MapChange (uint32 InFlags)
Tells the editor that something has been done to change the map.
UNREALED_API void CB_PostAutomationTesting ()
Called right after unit testing concludes.
UNREALED_API void CB_PreAutomationTesting ()
Called right before unit testing is about to begin.
UNREALED_API void CB_RedrawAllViewports ()
UNREALED_API void CB_RefreshEditor ()
UNREALED_API void CB_SelectedProps ()
Displays a property dialog based upon what is currently selected.
void ClearConfigRestoreFilename (FString Destination)
Clears the config restore name for restoring the specified config file.
void ClearConfigRestoreFilenames ()
Clears all the restore names for restoring config files.
void ClearPendingProjectName ()
Clear the project name we will use to reload the editor when switching projects.
UNREALED_API void EditorAnalyticsHeartbeat ()
Called when the heartbeat event should be sent to engine analytics.
UNREALED_API bool EnableWorldComposition (UWorld *InWorld, bool bEnable)
Handles "Enable World Composition" option in WorldSettings.
UNREALED_API FString FindMapFileFromPartialName (const FString &PartialMapName)
Finds a map using only the map name, no extension, no path, also caches it for faster lookup next time.
void ForceDeletePreferences (bool bIsEnabled)
Sets whether the preferences file should be deleted.
const TMap< FString, FString > & GetConfigRestoreFilenames ()
Retrieves the map of config->backup config filenames to be used for restoring config files.
UNREALED_API FString GetExecutableForCommandlets () const
Returns the editor executable to use to execute commandlets.
bool GetMapBuildCancelled () const
Whether or not the map build in progressed was cancelled by the user.
const FString & GetPendingProjectName () const
Get the project name we will use to reload the editor when switching projects.
UNREALED_API bool GetURL (const TCHAR *InKey, FString &OutURL, const bool bCheckRocket=false) const
Fetches a URL from the config and optionally switches it to rocket if required.
UNREALED_API void InitEngineAnalytics ()
Initialize engine analytics.
bool IsDeletePreferences ()
Returns true if preferences should be deleted.
UNREALED_API void LogAssetUpdate (UObject *UpdatedAsset, FObjectPreSaveContext SaveContext)
Logs an update to an asset.
UNREALED_API void MountTemplateSharedPaths ()
UNREALED_API void OnActorTokenActivated (const TSharedRef< class IMessageToken > &Token)
Delegate used on message log AActor token activation.
UNREALED_API void OnAssetDataTokenActivated (const TSharedRef< class IMessageToken > &Token)
Delegate used on message log FAssetData token activation.
UNREALED_API void OnDeferCommand (const FString &DeferredCommand)
Delegate that gets called by modules that can't directly access Engine.
UNREALED_API void OnEditorChangeMode (FEditorModeID NewEditorMode)
UNREALED_API void OnEditorPostModal ()
UNREALED_API void OnEditorPreModal ()
virtual UNREALED_API void OnExit ()
UNREALED_API FText OnGetAssetDataDisplayName (const FAssetData &InObject, const bool bFullPath)
Delegate used to get a display name for a message log FAssetData token.
UNREALED_API FText OnGetDisplayName (const UObject *InObject, const bool bFullPath)
Delegate for (default) display name of UObject tokens.
UNREALED_API void OnGotoAsset (const FString &InAssetPath) const
Delegate used to go to assets in the content browser.
virtual UNREALED_API void OnInit ()
Initalizes various systems.
UNREALED_API void OnMapChanged (UWorld *World, EMapChangeType MapChangeType)
Called when a map is changed (loaded,saved,new map, etc)
UNREALED_API void OnMessageSelectionChanged (TArray< TSharedRef< class FTokenizedMessage > > &Selection)
Delegate for (default) message log message selection - selects the objects that the tokens refer to (if any)
UNREALED_API void OnMessageTokenActivated (const TSharedRef< class IMessageToken > &Token)
Delegate for (default) message log UObject token activation - selects the object that the token refers to (if any)
UNREALED_API void OnObjectSaved (UObject *SavedObject, FObjectPreSaveContext SaveContext)
Delegate used to update the map of asset update counts.
UNREALED_API void OnTabForegrounded (TSharedPtr< SDockTab > ForegroundTab, TSharedPtr< SDockTab > BackgroundTab)
UNREALED_API void OnUserActivityTabChanged (TSharedPtr< SDockTab > InTab)
UNREALED_API void OnUserDefinedChordChanged (const FUICommandInfo &CommandInfo)
Called when the input manager records a user-defined chord.
UNREALED_API void OpenMarketplace (const FString &CustomLocation=TEXT(""))
Opens the Unreal Engine Launcher marketplace page.
UNREALED_API void ReplaceDocumentationURLWildcards (FString &Url, const FCultureRef &Culture, const FString &PageId=FString())
UNREALED_API void RestartEditor (bool bWarn=true, const TOptional< FString > &NewCommandLine=TOptional< FString >())
Restarts the editor, reopening the current project, if any.
void SetConfigRestoreFilename (FString InBackupFile, FString InConfigFile)
Sets the config file to use for restoring Config files.
void SetMapBuildCancelled (const bool InCancelled)
Sets the flag that states whether or not the map build was cancelled.
void SetPendingProjectName (const FString &ProjectName)
Set the project name we will use to reload the editor when switching projects.
virtual UNREALED_API void ShutdownAfterError ()
Performs any required cleanup in the case of a fatal error.
UNREALED_API bool SpawnEditorInstance (const FString &ProjectName)
Launch an editor instance, passing ProjectName and the command line args from this running instance.
UNREALED_API void SwitchProject (const FString &GameOrProjectFileName, bool bWarn=true, const TOptional< FString > &NewCommandLine=TOptional< FString >())
Opens the specified project file or game.
UNREALED_API void TickAssetAnalytics ()
Triggers asset analytics if it hasn't been run yet.
UNREALED_API void TickPerformanceAnalytics ()
Ticks the performance analytics used by the analytics heartbeat.
UE_DEPRECATED (5.0, "Blueprint Nativization has been removed as a supported feature. This delegate method will eventually be removed.") void OnNativizeBlueprintsSettingChanged(const FString &PackageName
BP nativization settings.
UE_DEPRECATED (5.6, "Please use FGlobalTabmanager::Get()->CanSavePersistentLayouts instead.") UNREALED_API bool IsSavingLayoutOnClosedAllowed()
Returns true if saving layout on close is allowed.
UE_DEPRECATED (5.6, "Please use FGlobalTabmanager::Get()->SetCanSavePersistentLayouts instead.") UNREALED_API void AllowSavingLayoutOnClose(bool bIsEnabled)
Sets whether saving the layout on close is allowed.
Static Public Member Functions
static UNREALED_API FUnrealEdMisc & Get ()
Singleton accessor.
static UNREALED_API FString GetProjectEditorBinaryPath ()
Get the path to the executable that runs the editor.
Data Fields
bool bSelect
Private Member Functions
UNREALED_API void PreSaveWorld (class UWorld *World, FObjectPreSaveContext ObjectSaveContext)
UNREALED_API void SelectActorFromMessageToken (AActor *InActor)
Private Attributes
bool bCancelBuild
Stores whether or not the current map build was cancelled.
bool bDeletePreferences
true if the preferences config file should be deleted.
bool bInitialized
Has the system has been initialized?
bool bIsAssetAnalyticsPending
true if an asset analytics pass is pending
bool bIsSurveyingPerformance
true if editor performance is being monitored
TUniquePtr< FConsoleCommandExecutor > CmdExec
Pointer to the classic "Cmd" executor.
FTimerHandle EditorAnalyticsHeartbeatTimerHandle
TUniquePtr< FEditorAxisDisplayInfo > EditorAxisDisplayInfo
Pointer to the EditorAxisDisplayInfo implementation.
TArray< float > FrameRateSamples
An array of frame rate samples used by the performance survey.
FDateTime LastFrameRateTime
The time that the last performance survey frame rate sample happened.
TSharedPtr< FTickableEditorObject > NavigationBuildingNotificationHandler
handler to notify about navigation building process
TMap< FName, uint32 > NumUpdatesByAssetName
Package names and the number of times they have been updated.
FDelegateHandle OnActiveTabChangedDelegateHandle
Handle to the registered OnActiveTabChanged delegate.
FDelegateHandle OnMapChangedDelegateHandle
Handle to the registered OnMapChanged delegate.
FDelegateHandle OnProfileGPUHandle
Handle used to register the "OnProfileGPU" delegate in the RHI.
FDelegateHandle OnTabForegroundedDelegateHandle
Handle to the registered OnTabForegrounded delegate.
FDelegateHandle OnUserDefinedChordChangedDelegateHandle
Handle to the registered OnUserDefinedChordChanged delegate.
TOptional< FString > PendingCommandLine
Optional alt command-line to use when the editor shuts down and switches projects (if unset, the restart will use the same command-line as the current process).
FString PendingProjectName
The name of a pending project.
TUniquePtr< FPerformanceAnalyticsStats > PerformanceAnalyticsStats
Statistical information needed by the analytics to report editor performance.
TMap< FString, FString > RestoreConfigFiles
Map of config->backup filenames to restore on shutdown of the editor.
Detailed Description
The public interface for the unreal editor misc singleton.
Definition at line 32 of file UnrealEdMisc.h.
Constructor & Destructor Documentation
~FUnrealEdMisc()
virtual UNREALED_API FUnrealEdMisc::~FUnrealEdMisc () virtual
Destructor.
FUnrealEdMisc()
UNREALED_API FUnrealEdMisc::FUnrealEdMisc ()
Constructor, private - use Get() function.
Referenced by Get().
Member Function Documentation
BeginPerformanceSurvey()
UNREALED_API void FUnrealEdMisc::BeginPerformanceSurvey ()
Start the performance survey that attempts to monitor editor performance in the default or simple startup maps.
CancelPerformanceSurvey()
UNREALED_API void FUnrealEdMisc::CancelPerformanceSurvey ()
End the performance survey that attempts to monitor editor performance in the default or simple startup maps.
CB_DisplayLoadErrors()
UNREALED_API void FUnrealEdMisc::CB_DisplayLoadErrors ()
CB_EditorModeWindowClosed()
UNREALED_API void FUnrealEdMisc::CB_EditorModeWindowClosed (const TSharedRef< SWindow > &)
CB_LevelActorsAdded()
UNREALED_API void FUnrealEdMisc::CB_LevelActorsAdded (class AActor * InActor)
CB_MapChange()
UNREALED_API void FUnrealEdMisc::CB_MapChange (uint32 InFlags)
Tells the editor that something has been done to change the map.
Can be anything from loading a whole new map to changing the BSP.
CB_PostAutomationTesting()
UNREALED_API void FUnrealEdMisc::CB_PostAutomationTesting ()
Called right after unit testing concludes.
CB_PreAutomationTesting()
UNREALED_API void FUnrealEdMisc::CB_PreAutomationTesting ()
Called right before unit testing is about to begin.
CB_RedrawAllViewports()
UNREALED_API void FUnrealEdMisc::CB_RedrawAllViewports ()
CB_RefreshEditor()
UNREALED_API void FUnrealEdMisc::CB_RefreshEditor ()
CB_SelectedProps()
UNREALED_API void FUnrealEdMisc::CB_SelectedProps ()
Displays a property dialog based upon what is currently selected.
If any actors are selected, the actor property dialog is displayed.
ClearConfigRestoreFilename()
void FUnrealEdMisc::ClearConfigRestoreFilename (FString Destination) inline
Clears the config restore name for restoring the specified config file.
Definition at line 125 of file UnrealEdMisc.h.
References RestoreConfigFiles.
ClearConfigRestoreFilenames()
void FUnrealEdMisc::ClearConfigRestoreFilenames () inline
Clears all the restore names for restoring config files.
Definition at line 131 of file UnrealEdMisc.h.
References RestoreConfigFiles.
ClearPendingProjectName()
void FUnrealEdMisc::ClearPendingProjectName () inline
Clear the project name we will use to reload the editor when switching projects.
Definition at line 95 of file UnrealEdMisc.h.
References PendingCommandLine, and PendingProjectName.
EditorAnalyticsHeartbeat()
UNREALED_API void FUnrealEdMisc::EditorAnalyticsHeartbeat ()
Called when the heartbeat event should be sent to engine analytics.
EnableWorldComposition()
UNREALED_API bool FUnrealEdMisc::EnableWorldComposition (UWorld * InWorld, bool bEnable)
Handles "Enable World Composition" option in WorldSettings.
FindMapFileFromPartialName()
UNREALED_API FString FUnrealEdMisc::FindMapFileFromPartialName (const FString & PartialMapName)
Finds a map using only the map name, no extension, no path, also caches it for faster lookup next time.
ForceDeletePreferences()
void FUnrealEdMisc::ForceDeletePreferences (bool bIsEnabled) inline
Sets whether the preferences file should be deleted.
Parameters
bIsEnabled true if the preferences should be deleted.
Definition at line 147 of file UnrealEdMisc.h.
References bDeletePreferences.
Get()
UNREALED_API FUnrealEdMisc & FUnrealEdMisc::Get () static
Singleton accessor.
References FUnrealEdMisc().
GetConfigRestoreFilenames()
const TMap< FString, FString > & FUnrealEdMisc::GetConfigRestoreFilenames () inline
Retrieves the map of config->backup config filenames to be used for restoring config files.
Definition at line 137 of file UnrealEdMisc.h.
References RestoreConfigFiles.
GetExecutableForCommandlets()
UNREALED_API FString FUnrealEdMisc::GetExecutableForCommandlets () const
Returns the editor executable to use to execute commandlets.
GetMapBuildCancelled()
bool FUnrealEdMisc::GetMapBuildCancelled () const inline
Whether or not the map build in progressed was cancelled by the user.
Returns
bool the current state of the flag
Definition at line 59 of file UnrealEdMisc.h.
References bCancelBuild.
GetPendingProjectName()
const FString & FUnrealEdMisc::GetPendingProjectName () const inline
Get the project name we will use to reload the editor when switching projects.
Returns
FString Name of the project the editor will switch to
Definition at line 79 of file UnrealEdMisc.h.
References PendingProjectName.
GetProjectEditorBinaryPath()
UNREALED_API FString FUnrealEdMisc::GetProjectEditorBinaryPath () static
Get the path to the executable that runs the editor.
GetURL()
UNREALED_API bool FUnrealEdMisc::GetURL (const TCHAR * InKey, FString & OutURL, const bool bCheckRocket = false) const
Fetches a URL from the config and optionally switches it to rocket if required.
Parameters
InKey The key to lookup in the config file
OutURL The URL string listed for the key in the config
bCheckRocket if true, will attempt to change the URL from udn to rocket if possible
Returns
true if successful
InitEngineAnalytics()
UNREALED_API void FUnrealEdMisc::InitEngineAnalytics ()
Initialize engine analytics.
IsDeletePreferences()
bool FUnrealEdMisc::IsDeletePreferences () inline
Returns true if preferences should be deleted.
Definition at line 153 of file UnrealEdMisc.h.
References bDeletePreferences.
LogAssetUpdate()
UNREALED_API void FUnrealEdMisc::LogAssetUpdate (UObject * UpdatedAsset, FObjectPreSaveContext SaveContext)
Logs an update to an asset.
MountTemplateSharedPaths()
UNREALED_API void FUnrealEdMisc::MountTemplateSharedPaths ()
OnActorTokenActivated()
UNREALED_API void FUnrealEdMisc::OnActorTokenActivated (const TSharedRef< class IMessageToken > & Token)
Delegate used on message log AActor token activation.
OnAssetDataTokenActivated()
UNREALED_API void FUnrealEdMisc::OnAssetDataTokenActivated (const TSharedRef< class IMessageToken > & Token)
Delegate used on message log FAssetData token activation.
OnDeferCommand()
UNREALED_API void FUnrealEdMisc::OnDeferCommand (const FString & DeferredCommand)
Delegate that gets called by modules that can't directly access Engine.
OnEditorChangeMode()
UNREALED_API void FUnrealEdMisc::OnEditorChangeMode (FEditorModeID NewEditorMode)
OnEditorPostModal()
UNREALED_API void FUnrealEdMisc::OnEditorPostModal ()
OnEditorPreModal()
UNREALED_API void FUnrealEdMisc::OnEditorPreModal ()
OnExit()
virtual UNREALED_API void FUnrealEdMisc::OnExit () virtual
OnGetAssetDataDisplayName()
UNREALED_API FText FUnrealEdMisc::OnGetAssetDataDisplayName (const FAssetData & InObject, const bool bFullPath)
Delegate used to get a display name for a message log FAssetData token.
OnGetDisplayName()
UNREALED_API FText FUnrealEdMisc::OnGetDisplayName (const UObject * InObject, const bool bFullPath)
Delegate for (default) display name of UObject tokens.
Can display the name of the actor if an object is/is part of one
OnGotoAsset()
UNREALED_API void FUnrealEdMisc::OnGotoAsset (const FString & InAssetPath) const
Delegate used to go to assets in the content browser.
OnInit()
virtual UNREALED_API void FUnrealEdMisc::OnInit () virtual
Initalizes various systems.
OnMapChanged()
UNREALED_API void FUnrealEdMisc::OnMapChanged (UWorld * World, EMapChangeType MapChangeType)
Called when a map is changed (loaded,saved,new map, etc)
OnMessageSelectionChanged()
UNREALED_API void FUnrealEdMisc::OnMessageSelectionChanged (TArray< TSharedRef< class FTokenizedMessage > > & Selection)
Delegate for (default) message log message selection - selects the objects that the tokens refer to (if any)
OnMessageTokenActivated()
UNREALED_API void FUnrealEdMisc::OnMessageTokenActivated (const TSharedRef< class IMessageToken > & Token)
Delegate for (default) message log UObject token activation - selects the object that the token refers to (if any)
OnObjectSaved()
UNREALED_API void FUnrealEdMisc::OnObjectSaved (UObject * SavedObject, FObjectPreSaveContext SaveContext)
Delegate used to update the map of asset update counts.
OnTabForegrounded()
UNREALED_API void FUnrealEdMisc::OnTabForegrounded (TSharedPtr< SDockTab > ForegroundTab, TSharedPtr< SDockTab > BackgroundTab)
OnUserActivityTabChanged()
UNREALED_API void FUnrealEdMisc::OnUserActivityTabChanged (TSharedPtr< SDockTab > InTab)
OnUserDefinedChordChanged()
UNREALED_API void FUnrealEdMisc::OnUserDefinedChordChanged (const FUICommandInfo & CommandInfo)
Called when the input manager records a user-defined chord.
OpenMarketplace()
UNREALED_API void FUnrealEdMisc::OpenMarketplace (const FString & CustomLocation = TEXT(""))
Opens the Unreal Engine Launcher marketplace page.
Parameters
CustomLocation Optional custom location within the marketplace to navigate to. If not specified the launcher will open to the root marketplace page
PreSaveWorld()
UNREALED_API void FUnrealEdMisc::PreSaveWorld (class UWorld * World, FObjectPreSaveContext ObjectSaveContext) private
ReplaceDocumentationURLWildcards()
UNREALED_API void FUnrealEdMisc::ReplaceDocumentationURLWildcards (FString & Url, const FCultureRef & Culture, const FString & PageId = FString())
RestartEditor()
UNREALED_API void FUnrealEdMisc::RestartEditor (bool bWarn = true, const TOptional< FString > & NewCommandLine = TOptional< FString >())
Restarts the editor, reopening the current project, if any.
SelectActorFromMessageToken()
UNREALED_API void FUnrealEdMisc::SelectActorFromMessageToken (AActor * InActor) private
SetConfigRestoreFilename()
void FUnrealEdMisc::SetConfigRestoreFilename (FString InBackupFile, FString InConfigFile) inline
Sets the config file to use for restoring Config files.
Parameters
InBackupFile The filename of the backup file to restore
InConfigFile The config filename to overwrite
Definition at line 119 of file UnrealEdMisc.h.
References RestoreConfigFiles, and SetConfigRestoreFilename().
Referenced by SetConfigRestoreFilename().
SetMapBuildCancelled()
void FUnrealEdMisc::SetMapBuildCancelled (const bool InCancelled) inline
Sets the flag that states whether or not the map build was cancelled.
Parameters
InCancelled New state for the cancelled flag.
Definition at line 69 of file UnrealEdMisc.h.
References bCancelBuild.
SetPendingProjectName()
void FUnrealEdMisc::SetPendingProjectName (const FString & ProjectName) inline
Set the project name we will use to reload the editor when switching projects.
Parameters
ProjectName Name of the project to switch to
Definition at line 89 of file UnrealEdMisc.h.
References PendingProjectName.
ShutdownAfterError()
virtual UNREALED_API void FUnrealEdMisc::ShutdownAfterError () virtual
Performs any required cleanup in the case of a fatal error.
SpawnEditorInstance()
UNREALED_API bool FUnrealEdMisc::SpawnEditorInstance (const FString & ProjectName)
Launch an editor instance, passing ProjectName and the command line args from this running instance.
SwitchProject()
UNREALED_API void FUnrealEdMisc::SwitchProject (const FString & GameOrProjectFileName, bool bWarn = true, const TOptional< FString > & NewCommandLine = TOptional< FString >())
Opens the specified project file or game.
Restarts the editor
TickAssetAnalytics()
UNREALED_API void FUnrealEdMisc::TickAssetAnalytics ()
Triggers asset analytics if it hasn't been run yet.
TickPerformanceAnalytics()
UNREALED_API void FUnrealEdMisc::TickPerformanceAnalytics ()
Ticks the performance analytics used by the analytics heartbeat.
UE_DEPRECATED() [1/3]
FUnrealEdMisc::UE_DEPRECATED (5. 0, "Blueprint Nativization has been removed as a supported feature. This delegate method will eventually be removed.") const &
BP nativization settings.
UE_DEPRECATED() [2/3]
FUnrealEdMisc::UE_DEPRECATED (5. 6, "Please use FGlobalTabmanager::Get()->CanSavePersistentLayouts instead.")
Returns true if saving layout on close is allowed.
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FUnrealEdMisc::UE_DEPRECATED (5. 6, "Please use FGlobalTabmanager::Get()->SetCanSavePersistentLayouts instead.")
Sets whether saving the layout on close is allowed.
Parameters
bIsEnabled true if saving on close is allowed.
Referenced by UE_DEPRECATED().
Field Documentation
bCancelBuild
bool FUnrealEdMisc::bCancelBuild private
Stores whether or not the current map build was cancelled.
Definition at line 294 of file UnrealEdMisc.h.
Referenced by GetMapBuildCancelled(), and SetMapBuildCancelled().
bDeletePreferences
bool FUnrealEdMisc::bDeletePreferences private
true if the preferences config file should be deleted.
Definition at line 309 of file UnrealEdMisc.h.
Referenced by ForceDeletePreferences(), and IsDeletePreferences().
bInitialized
bool FUnrealEdMisc::bInitialized private
Has the system has been initialized?
Definition at line 297 of file UnrealEdMisc.h.
bIsAssetAnalyticsPending
bool FUnrealEdMisc::bIsAssetAnalyticsPending private
true if an asset analytics pass is pending
Definition at line 315 of file UnrealEdMisc.h.
bIsSurveyingPerformance
bool FUnrealEdMisc::bIsSurveyingPerformance private
true if editor performance is being monitored
Definition at line 312 of file UnrealEdMisc.h.
bSelect
bool FUnrealEdMisc::bSelect
Initial value:
{}
    UNREALED_API void OnActiveTabChanged(TSharedPtr<SDockTab> PreviouslyActive, TSharedPtr<SDockTab> NewlyActivated)
Definition at line 219 of file UnrealEdMisc.h.
CmdExec
TUniquePtr<FConsoleCommandExecutor> FUnrealEdMisc::CmdExec private
Pointer to the classic "Cmd" executor.
Definition at line 333 of file UnrealEdMisc.h.
EditorAnalyticsHeartbeatTimerHandle
FTimerHandle FUnrealEdMisc::EditorAnalyticsHeartbeatTimerHandle private
Definition at line 350 of file UnrealEdMisc.h.
EditorAxisDisplayInfo
TUniquePtr<FEditorAxisDisplayInfo> FUnrealEdMisc::EditorAxisDisplayInfo private
Pointer to the EditorAxisDisplayInfo implementation.
Definition at line 336 of file UnrealEdMisc.h.
FrameRateSamples
TArray<float> FUnrealEdMisc::FrameRateSamples private
An array of frame rate samples used by the performance survey.
Definition at line 321 of file UnrealEdMisc.h.
LastFrameRateTime
FDateTime FUnrealEdMisc::LastFrameRateTime private
The time that the last performance survey frame rate sample happened.
Definition at line 318 of file UnrealEdMisc.h.
NavigationBuildingNotificationHandler
TSharedPtr<FTickableEditorObject> FUnrealEdMisc::NavigationBuildingNotificationHandler private
handler to notify about navigation building process
Definition at line 327 of file UnrealEdMisc.h.
NumUpdatesByAssetName
TMap<FName, uint32> FUnrealEdMisc::NumUpdatesByAssetName private
Package names and the number of times they have been updated.
Definition at line 330 of file UnrealEdMisc.h.
OnActiveTabChangedDelegateHandle
FDelegateHandle FUnrealEdMisc::OnActiveTabChangedDelegateHandle private
Handle to the registered OnActiveTabChanged delegate.
Definition at line 345 of file UnrealEdMisc.h.
OnMapChangedDelegateHandle
FDelegateHandle FUnrealEdMisc::OnMapChangedDelegateHandle private
Handle to the registered OnMapChanged delegate.
Definition at line 342 of file UnrealEdMisc.h.
OnProfileGPUHandle
FDelegateHandle FUnrealEdMisc::OnProfileGPUHandle private
Handle used to register the "OnProfileGPU" delegate in the RHI.
Definition at line 353 of file UnrealEdMisc.h.
OnTabForegroundedDelegateHandle
FDelegateHandle FUnrealEdMisc::OnTabForegroundedDelegateHandle private
Handle to the registered OnTabForegrounded delegate.
Definition at line 348 of file UnrealEdMisc.h.
OnUserDefinedChordChangedDelegateHandle
FDelegateHandle FUnrealEdMisc::OnUserDefinedChordChangedDelegateHandle private
Handle to the registered OnUserDefinedChordChanged delegate.
Definition at line 339 of file UnrealEdMisc.h.
PendingCommandLine
TOptional<FString> FUnrealEdMisc::PendingCommandLine private
Optional alt command-line to use when the editor shuts down and switches projects (if unset, the restart will use the same command-line as the current process).
Definition at line 303 of file UnrealEdMisc.h.
Referenced by ClearPendingProjectName().
PendingProjectName
FString FUnrealEdMisc::PendingProjectName private
The name of a pending project.
When the editor shuts down it will switch to this project if not empty
Definition at line 300 of file UnrealEdMisc.h.
Referenced by ClearPendingProjectName(), GetPendingProjectName(), and SetPendingProjectName().
PerformanceAnalyticsStats
TUniquePtr<FPerformanceAnalyticsStats> FUnrealEdMisc::PerformanceAnalyticsStats private
Statistical information needed by the analytics to report editor performance.
Definition at line 324 of file UnrealEdMisc.h.
RestoreConfigFiles
TMap<FString, FString> FUnrealEdMisc::RestoreConfigFiles private
Map of config->backup filenames to restore on shutdown of the editor.
Definition at line 306 of file UnrealEdMisc.h.
Referenced by ClearConfigRestoreFilename(), ClearConfigRestoreFilenames(), GetConfigRestoreFilenames(), and SetConfigRestoreFilename().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/UnrealEdMisc.h