Unreal Engine 5.6 C++ API: FTextStringHelper Class Reference
FTextStringHelper Class Reference
#include "Text.h"
Public Member Functions
UE_DEPRECATED (4.22, "FTextStringHelper::ReadFromString is deprecated. Use FTextStringHelper::ReadFromBuffer instead.") static 1 bool ReadFromString(const TCHAR *Buffer
UE_DEPRECATED (4.22, "FTextStringHelper::WriteToString is deprecated. Use FTextStringHelper::WriteToBuffer instead.") static 1 bool WriteToString(FString &Buffer
Static Public Member Functions
static FText CreateFromBuffer (const TCHAR *Buffer, const TCHAR *TextNamespace=nullptr, const TCHAR *PackageNamespace=nullptr, const bool bRequiresQuotes=false)
Create an FText instance from the given stream of text.
static bool IsComplexText (const TCHAR *Buffer)
Test to see whether a given buffer contains complex text.
static const TCHAR * ReadFromBuffer (const TCHAR *Buffer, FText &OutValue, const TCHAR *TextNamespace=nullptr, const TCHAR *PackageNamespace=nullptr, const bool bRequiresQuotes=false)
Attempt to extract an FText instance from the given stream of text.
static void WriteToBuffer (FString &Buffer, const FText &Value, const bool bRequiresQuotes=false, const bool bStripPackageNamespace=false)
Write the given FText instance to a stream of text.
Data Fields
FText const TCHAR const TCHAR int32 const bool bRequiresQuotes = false
const FText const bool bRequiresQuotes = false)
FText const TCHAR const TCHAR int32 const bool const EStringTableLoadingPolicy InLoadingPolicy = EStringTableLoadingPolicy::FindOrLoad)
FText const TCHAR const TCHAR int32 * OutNumCharsRead = nullptr
FText & OutValue
FText const TCHAR const TCHAR * PackageNamespace = nullptr
FText const TCHAR * TextNamespace = nullptr
const FText & Value
Static Private Member Functions
static const TCHAR * ReadFromBuffer_ComplexText (const TCHAR *Buffer, FText &OutValue, const TCHAR *TextNamespace, const TCHAR *PackageNamespace)
Detailed Description
Definition at line 1257 of file Text.h.
Member Function Documentation
CreateFromBuffer()
FText FTextStringHelper::CreateFromBuffer (const TCHAR * Buffer, const TCHAR * TextNamespace = nullptr, const TCHAR * PackageNamespace = nullptr, const bool bRequiresQuotes = false) static
Create an FText instance from the given stream of text.
Note
This uses ReadFromBuffer internally, but will fallback to FText::FromString if ReadFromBuffer fails to parse the buffer.
Parameters
Buffer The buffer of text to read from (null terminated).
TextNamespace An optional namespace to use when parsing texts that use LOCTEXT (default is an empty namespace).
PackageNamespace The package namespace of the containing object (if loading for a property - see TextNamespaceUtil::GetPackageNamespace).
bRequiresQuotes True if the read text literal must be surrounded by quotes (eg, when loading from a delimited list).
Returns
The parsed FText instance.
References bRequiresQuotes, Buffer, PackageNamespace, and TextNamespace.
IsComplexText()
bool FTextStringHelper::IsComplexText (const TCHAR * Buffer) static
Test to see whether a given buffer contains complex text.
Returns
True if it does, false otherwise
References Buffer, and IsComplexText().
Referenced by IsComplexText().
ReadFromBuffer()
const TCHAR * FTextStringHelper::ReadFromBuffer (const TCHAR * Buffer, FText & OutValue, const TCHAR * TextNamespace = nullptr, const TCHAR * PackageNamespace = nullptr, const bool bRequiresQuotes = false) static
Attempt to extract an FText instance from the given stream of text.
Parameters
Buffer The buffer of text to read from (null terminated).
OutValue The text value to fill with the read text.
TextNamespace An optional namespace to use when parsing texts that use LOCTEXT (default is an empty namespace).
PackageNamespace The package namespace of the containing object (if loading for a property - see TextNamespaceUtil::GetPackageNamespace).
bRequiresQuotes True if the read text literal must be surrounded by quotes (eg, when loading from a delimited list).
Returns
The updated buffer after we parsed this text, or nullptr on failure
References bRequiresQuotes, Buffer, OutValue, PackageNamespace, and TextNamespace.
ReadFromBuffer_ComplexText()
const TCHAR * FTextStringHelper::ReadFromBuffer_ComplexText (const TCHAR * Buffer, FText & OutValue, const TCHAR * TextNamespace, const TCHAR * PackageNamespace) static private
References Buffer, OutValue, PackageNamespace, ReadFromBuffer_ComplexText(), and TextNamespace.
Referenced by ReadFromBuffer_ComplexText().
UE_DEPRECATED() [1/2]
FTextStringHelper::UE_DEPRECATED (4. 22, "FTextStringHelper::ReadFromString is deprecated. Use FTextStringHelper::ReadFromBuffer instead.") const
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FTextStringHelper::UE_DEPRECATED (4. 22, "FTextStringHelper::WriteToString is deprecated. Use FTextStringHelper::WriteToBuffer instead.") &
References UE_DEPRECATED().
WriteToBuffer()
void FTextStringHelper::WriteToBuffer (FString & Buffer, const FText & Value, const bool bRequiresQuotes = false, const bool bStripPackageNamespace = false) static
Write the given FText instance to a stream of text.
Parameters
Buffer The buffer of text to write to.
Value The text value to write into the buffer.
bRequiresQuotes True if the written text literal must be surrounded by quotes (eg, when saving as a delimited list)
bStripPackageNamespace True to strip the package namespace from the written NSLOCTEXT value (eg, when saving cooked data)
References bRequiresQuotes, Buffer, Value, and WriteToBuffer().
Referenced by WriteToBuffer().
Field Documentation
bRequiresQuotes [1/2]
FText const TCHAR const TCHAR int32 const bool FTextStringHelper::bRequiresQuotes = false
Definition at line 1287 of file Text.h.
Referenced by CreateFromBuffer(), ReadFromBuffer(), and WriteToBuffer().
bRequiresQuotes [2/2]
const FText const bool FTextStringHelper::bRequiresQuotes = false)
Definition at line 1300 of file Text.h.
InLoadingPolicy
FText const TCHAR const TCHAR int32 const bool const EStringTableLoadingPolicy FTextStringHelper::InLoadingPolicy = EStringTableLoadingPolicy::FindOrLoad)
Definition at line 1287 of file Text.h.
OutNumCharsRead
FText const TCHAR const TCHAR int32* FTextStringHelper::OutNumCharsRead = nullptr
Definition at line 1287 of file Text.h.
OutValue
FText& FTextStringHelper::OutValue
Definition at line 1287 of file Text.h.
Referenced by ReadFromBuffer(), and ReadFromBuffer_ComplexText().
PackageNamespace
FText const TCHAR const TCHAR* FTextStringHelper::PackageNamespace = nullptr
Definition at line 1287 of file Text.h.
Referenced by CreateFromBuffer(), ReadFromBuffer(), and ReadFromBuffer_ComplexText().
TextNamespace
FText const TCHAR* FTextStringHelper::TextNamespace = nullptr
Definition at line 1287 of file Text.h.
Referenced by CreateFromBuffer(), ReadFromBuffer(), and ReadFromBuffer_ComplexText().
Value
const FText& FTextStringHelper::Value
Definition at line 1300 of file Text.h.
Referenced by WriteToBuffer().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/Text.h