Unreal Engine 5.6 C++ API: Metasound::VertexDataPrivate::FInputBinding Class Reference
Metasound::VertexDataPrivate::FInputBinding Class Reference
#include "MetasoundVertexData.h"
Public Member Functions
METASOUNDGRAPHCORE_API FInputBinding (const FInputDataVertex &InVertex)
METASOUNDGRAPHCORE_API FInputBinding (const FVertexName &InVertexName, FAnyDataReference &&InReference)
METASOUNDGRAPHCORE_API FInputBinding (FInputDataVertex &&InVertex)
template<typename DataReferenceType>
void Bind (DataReferenceType &InOutDataReference)
METASOUNDGRAPHCORE_API void Bind (FInputBinding &InBinding)
template<typename DataReferenceType>
void BindRead (DataReferenceType &InOutDataReference)
template<typename DataType>
void BindWrite (TDataWriteReference< DataType > &InOutDataReference)
METASOUNDGRAPHCORE_API EDataReferenceAccessType GetAccessType () const
METASOUNDGRAPHCORE_API const FAnyDataReference * GetDataReference () const
template<typename AsType>
AsType GetDataReferenceAs () const
METASOUNDGRAPHCORE_API FDataReferenceID GetDataReferenceID () const
template<typename AsType, typename ... ArgTypes>
AsType GetOrConstructAs (ArgTypes &&... Args) const
template<typename AsType>
AsType GetOrCreateDefaultAs (const FOperatorSettings &InSettings) const
METASOUNDGRAPHCORE_API const FInputDataVertex & GetVertex () const
METASOUNDGRAPHCORE_API bool IsBound () const
template<typename DataReferenceType>
void Set (const DataReferenceType &InDataReference)
METASOUNDGRAPHCORE_API void Set (FAnyDataReference &&InAnyDataReference)
METASOUNDGRAPHCORE_API void SetDefaultLiteral (const FLiteral &InLiteral)
template<typename DataType>
void SetValue (const DataType &InValue)
Private Attributes
TOptional< FAnyDataReference > Data
FInputDataVertex Vertex
Detailed Description
Definition at line 171 of file MetasoundVertexData.h.
Constructor & Destructor Documentation
FInputBinding() [1/3]
METASOUNDGRAPHCORE_API Metasound::VertexDataPrivate::FInputBinding::FInputBinding (FInputDataVertex && InVertex)
References UE_API.
Referenced by Bind().
FInputBinding() [2/3]
METASOUNDGRAPHCORE_API Metasound::VertexDataPrivate::FInputBinding::FInputBinding (const FInputDataVertex & InVertex)
References UE_API.
FInputBinding() [3/3]
METASOUNDGRAPHCORE_API Metasound::VertexDataPrivate::FInputBinding::FInputBinding (const FVertexName & InVertexName, FAnyDataReference && InReference)
References UE_API.
Member Function Documentation
Bind() [1/2]
template<typename DataReferenceType> void Metasound::VertexDataPrivate::FInputBinding::Bind (DataReferenceType & InOutDataReference) inline
Definition at line 206 of file MetasoundVertexData.h.
References Bind(), Data, and Set().
Referenced by Bind().
Bind() [2/2]
METASOUNDGRAPHCORE_API void Metasound::VertexDataPrivate::FInputBinding::Bind (FInputBinding & InBinding)
References FInputBinding(), and UE_API.
BindRead()
template<typename DataReferenceType> void Metasound::VertexDataPrivate::FInputBinding::BindRead (DataReferenceType & InOutDataReference) inline
Definition at line 180 of file MetasoundVertexData.h.
References Data, and Set().
BindWrite()
template<typename DataType> void Metasound::VertexDataPrivate::FInputBinding::BindWrite (TDataWriteReference< DataType > & InOutDataReference) inline
Definition at line 193 of file MetasoundVertexData.h.
References Data, and Set().
GetAccessType()
METASOUNDGRAPHCORE_API EDataReferenceAccessType Metasound::VertexDataPrivate::FInputBinding::GetAccessType () const
References UE_API.
GetDataReference()
METASOUNDGRAPHCORE_API const FAnyDataReference * Metasound::VertexDataPrivate::FInputBinding::GetDataReference () const
References UE_API.
GetDataReferenceAs()
template<typename AsType> AsType Metasound::VertexDataPrivate::FInputBinding::GetDataReferenceAs () const inline
Definition at line 264 of file MetasoundVertexData.h.
References check, and Data.
Referenced by Metasound::FInputVertexInterfaceData::GetDataReadReference(), Metasound::FInputVertexInterfaceData::GetDataWriteReference(), GetOrConstructAs(), GetOrCreateDefaultAs(), and Metasound::FInputVertexInterfaceData::GetValue().
GetDataReferenceID()
METASOUNDGRAPHCORE_API FDataReferenceID Metasound::VertexDataPrivate::FInputBinding::GetDataReferenceID () const
References UE_API.
GetOrConstructAs()
template<typename AsType, typename ... ArgTypes> AsType Metasound::VertexDataPrivate::FInputBinding::GetOrConstructAs (ArgTypes &&... Args) const inline
Definition at line 290 of file MetasoundVertexData.h.
References Metasound::VertexDataPrivate::TFactoryFacade< Type >::CreateWithArgs(), Data, Forward(), and GetDataReferenceAs().
GetOrCreateDefaultAs()
template<typename AsType> AsType Metasound::VertexDataPrivate::FInputBinding::GetOrCreateDefaultAs (const FOperatorSettings & InSettings) const inline
Definition at line 274 of file MetasoundVertexData.h.
References Metasound::VertexDataPrivate::TFactoryFacade< Type >::CreateWithLiteral(), Data, GetDataReferenceAs(), and Vertex.
Referenced by Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataValueReference(), and Metasound::FInputVertexInterfaceData::GetOrCreateDefaultValue().
GetVertex()
METASOUNDGRAPHCORE_API const FInputDataVertex & Metasound::VertexDataPrivate::FInputBinding::GetVertex () const
References UE_API.
IsBound()
METASOUNDGRAPHCORE_API bool Metasound::VertexDataPrivate::FInputBinding::IsBound () const
References UE_API.
Referenced by Metasound::FInputVertexInterfaceData::GetValue().
Set() [1/2]
template<typename DataReferenceType> void Metasound::VertexDataPrivate::FInputBinding::Set (const DataReferenceType & InDataReference) inline
Definition at line 239 of file MetasoundVertexData.h.
References check, Metasound::VertexDataPrivate::CheckAccessTypeCompatibility(), Data, and Vertex.
Referenced by Bind(), BindRead(), and BindWrite().
Set() [2/2]
METASOUNDGRAPHCORE_API void Metasound::VertexDataPrivate::FInputBinding::Set (FAnyDataReference && InAnyDataReference)
References UE_API.
SetDefaultLiteral()
METASOUNDGRAPHCORE_API void Metasound::VertexDataPrivate::FInputBinding::SetDefaultLiteral (const FLiteral & InLiteral)
References UE_API.
SetValue()
template<typename DataType> void Metasound::VertexDataPrivate::FInputBinding::SetValue (const DataType & InValue) inline
Definition at line 305 of file MetasoundVertexData.h.
References check, Metasound::VertexDataPrivate::CheckAccessTypeCompatibility(), Metasound::TDataValueReference< DataType >::CreateNew(), Data, Metasound::GetMetasoundDataTypeName(), and Vertex.
Field Documentation
Data
TOptional<FAnyDataReference> Metasound::VertexDataPrivate::FInputBinding::Data private
Definition at line 315 of file MetasoundVertexData.h.
Referenced by Bind(), BindRead(), BindWrite(), GetDataReferenceAs(), GetOrConstructAs(), GetOrCreateDefaultAs(), Set(), and SetValue().
Vertex
FInputDataVertex Metasound::VertexDataPrivate::FInputBinding::Vertex private
Definition at line 314 of file MetasoundVertexData.h.
Referenced by GetOrCreateDefaultAs(), Set(), and SetValue().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertexData.h