Unreal Engine 5.6 C++ API: UE::Geometry::THemisphericalFibonacci< RealType > Class Template Reference
UE::Geometry::THemisphericalFibonacci< RealType > Class Template Reference
A hemisphere point set generated using a Fibonacci lattice where the i'th point of an N point set can be computed directly.
#include "SphericalFibonacci.h"
Public Types
enum class EDistribution { Uniform , Cosine }
Public Member Functions
THemisphericalFibonacci (int32 NumPoints=64, EDistribution Dist=EDistribution::Uniform)
int32 Num () const
TVector< RealType > operator[] (int32 Index) const
TVector< RealType > Point (int32 Index) const
Data Fields
EDistribution Distribution = EDistribution::Uniform
int32 N = 64
Detailed Description
template<typename RealType>
class UE::Geometry::THemisphericalFibonacci< RealType >
A hemisphere point set generated using a Fibonacci lattice where the i'th point of an N point set can be computed directly.
Z is "up" in the hemisphere.
Definition at line 219 of file SphericalFibonacci.h.
Member Enumeration Documentation
EDistribution
template<typename RealType> enum class UE::Geometry::THemisphericalFibonacci::EDistribution strong
Enumerator
Uniform
Cosine
Definition at line 224 of file SphericalFibonacci.h.
Constructor & Destructor Documentation
THemisphericalFibonacci()
template<typename RealType> UE::Geometry::THemisphericalFibonacci< RealType >::THemisphericalFibonacci (int32 NumPoints = 64, EDistribution Dist = EDistribution::Uniform) inline
Definition at line 232 of file SphericalFibonacci.h.
References Distribution, N, and Uniform.
Member Function Documentation
Num()
template<typename RealType> int32 UE::Geometry::THemisphericalFibonacci< RealType >::Num () const inline
Definition at line 237 of file SphericalFibonacci.h.
References N.
operator[]()
template<typename RealType> TVector< RealType > UE::Geometry::THemisphericalFibonacci< RealType >::operator[] (int32 Index) const inline
Parameters
Index point index in range [0,Num()-1]
Returns
sphere point for given Index
Definition at line 284 of file SphericalFibonacci.h.
References Point.
Point()
template<typename RealType> TVector< RealType > UE::Geometry::THemisphericalFibonacci< RealType >::Point (int32 Index) const inline
Parameters
Index point index in range [0,Num()-1]
Returns
sphere point for given Index
Definition at line 246 of file SphericalFibonacci.h.
References checkSlow, Cosine, UE::Geometry::TFibonacciLattice< RealType >::Disc, Distribution, TMathUtil< RealType >::Max(), N, Point(), Points, TMathUtil< RealType >::Sqrt(), Uniform, UE::Math::TVector2< T >::X, UE::Math::TVector2< T >::Y, and Z.
Referenced by Point().
Field Documentation
Distribution
template<typename RealType> EDistribution UE::Geometry::THemisphericalFibonacci< RealType >::Distribution = EDistribution::Uniform
Definition at line 229 of file SphericalFibonacci.h.
Referenced by THemisphericalFibonacci(), and Point().
N
template<typename RealType> int32 UE::Geometry::THemisphericalFibonacci< RealType >::N = 64
Definition at line 222 of file SphericalFibonacci.h.
Referenced by THemisphericalFibonacci(), Num(), and Point().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Sampling/SphericalFibonacci.h