Unreal Engine 5.6 C++ API: FShadowMapInteraction Class Reference
FShadowMapInteraction Class Reference
Information about the static shadowing information for a primitive.
#include "SceneManagement.h"
Public Member Functions
FShadowMapInteraction ()
Default constructor.
bool GetChannelValid (int32 ChannelIndex) const
const FVector2D & GetCoordinateBias () const
const FVector2D & GetCoordinateScale () const
FVector4f GetInvUniformPenumbraSize () const
UShadowMapTexture2D * GetTexture () const
EShadowMapInteractionType GetType () const
const ULightMapVirtualTexture2D * GetVirtualTexture () const
Static Public Member Functions
static FShadowMapInteraction GlobalVolume ()
static FShadowMapInteraction InitVirtualTexture (class ULightMapVirtualTexture2D *InTexture, const FVector2D &InCoordinateScale, const FVector2D &InCoordinateBias, const bool *InChannelValid, const FVector4f &InInvUniformPenumbraSize)
static FShadowMapInteraction None ()
static FShadowMapInteraction Texture (class UShadowMapTexture2D *InTexture, const FVector2D &InCoordinateScale, const FVector2D &InCoordinateBias, const bool *InChannelValid, const FVector4f &InInvUniformPenumbraSize)
Private Attributes
bool bChannelValid [4]
FVector2D CoordinateBias
FVector2D CoordinateScale
FVector4f InvUniformPenumbraSize
UShadowMapTexture2D * ShadowTexture
EShadowMapInteractionType Type
const ULightMapVirtualTexture2D * VirtualTexture
Detailed Description
Information about the static shadowing information for a primitive.
Definition at line 621 of file SceneManagement.h.
Constructor & Destructor Documentation
FShadowMapInteraction()
FShadowMapInteraction::FShadowMapInteraction () inline
Default constructor.
Definition at line 684 of file SceneManagement.h.
References bChannelValid, InvUniformPenumbraSize, ShadowTexture, SMIT_None, Type, UE_ARRAY_COUNT, and VirtualTexture.
Referenced by GlobalVolume(), InitVirtualTexture(), None(), and Texture().
Member Function Documentation
GetChannelValid()
bool FShadowMapInteraction::GetChannelValid (int32 ChannelIndex) const inline
Definition at line 723 of file SceneManagement.h.
References bChannelValid, checkSlow, SMIT_Texture, and Type.
GetCoordinateBias()
const FVector2D & FShadowMapInteraction::GetCoordinateBias () const inline
Definition at line 717 of file SceneManagement.h.
References checkSlow, CoordinateBias, SMIT_Texture, and Type.
GetCoordinateScale()
const FVector2D & FShadowMapInteraction::GetCoordinateScale () const inline
Definition at line 711 of file SceneManagement.h.
References checkSlow, CoordinateScale, SMIT_Texture, and Type.
GetInvUniformPenumbraSize()
FVector4f FShadowMapInteraction::GetInvUniformPenumbraSize () const inline
Definition at line 729 of file SceneManagement.h.
References InvUniformPenumbraSize.
GetTexture()
UShadowMapTexture2D * FShadowMapInteraction::GetTexture () const inline
Definition at line 699 of file SceneManagement.h.
References checkSlow, ShadowTexture, SMIT_Texture, and Type.
GetType()
EShadowMapInteractionType FShadowMapInteraction::GetType () const inline
Definition at line 697 of file SceneManagement.h.
References Type.
GetVirtualTexture()
const ULightMapVirtualTexture2D * FShadowMapInteraction::GetVirtualTexture () const inline
Definition at line 705 of file SceneManagement.h.
References checkSlow, SMIT_Texture, Type, and VirtualTexture.
GlobalVolume()
FShadowMapInteraction FShadowMapInteraction::GlobalVolume () inline static
Definition at line 633 of file SceneManagement.h.
References FShadowMapInteraction(), and SMIT_GlobalVolume.
InitVirtualTexture()
FShadowMapInteraction FShadowMapInteraction::InitVirtualTexture (class ULightMapVirtualTexture2D * InTexture, const FVector2D & InCoordinateScale, const FVector2D & InCoordinateBias, const bool * InChannelValid, const FVector4f & InInvUniformPenumbraSize) inline static
Definition at line 662 of file SceneManagement.h.
References FShadowMapInteraction(), and SMIT_Texture.
None()
FShadowMapInteraction FShadowMapInteraction::None () inline static
Definition at line 626 of file SceneManagement.h.
References FShadowMapInteraction(), and SMIT_None.
Referenced by FLightMap::GetShadowInteraction().
Texture()
FShadowMapInteraction FShadowMapInteraction::Texture (class UShadowMapTexture2D * InTexture, const FVector2D & InCoordinateScale, const FVector2D & InCoordinateBias, const bool * InChannelValid, const FVector4f & InInvUniformPenumbraSize) inline static
Definition at line 640 of file SceneManagement.h.
References FShadowMapInteraction(), and SMIT_Texture.
Field Documentation
bChannelValid
bool FShadowMapInteraction::bChannelValid[4] private
Definition at line 739 of file SceneManagement.h.
Referenced by FShadowMapInteraction(), and GetChannelValid().
CoordinateBias
FVector2D FShadowMapInteraction::CoordinateBias private
Definition at line 738 of file SceneManagement.h.
Referenced by GetCoordinateBias().
CoordinateScale
FVector2D FShadowMapInteraction::CoordinateScale private
Definition at line 737 of file SceneManagement.h.
Referenced by GetCoordinateScale().
InvUniformPenumbraSize
FVector4f FShadowMapInteraction::InvUniformPenumbraSize private
Definition at line 740 of file SceneManagement.h.
Referenced by FShadowMapInteraction(), and GetInvUniformPenumbraSize().
ShadowTexture
UShadowMapTexture2D* FShadowMapInteraction::ShadowTexture private
Definition at line 735 of file SceneManagement.h.
Referenced by FShadowMapInteraction(), and GetTexture().
Type
EShadowMapInteractionType FShadowMapInteraction::Type private
Definition at line 741 of file SceneManagement.h.
Referenced by FShadowMapInteraction(), GetChannelValid(), GetCoordinateBias(), GetCoordinateScale(), GetTexture(), GetType(), and GetVirtualTexture().
VirtualTexture
const ULightMapVirtualTexture2D* FShadowMapInteraction::VirtualTexture private
Definition at line 736 of file SceneManagement.h.
Referenced by FShadowMapInteraction(), and GetVirtualTexture().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneManagement.h