Unreal Engine 5.6 C++ API: UE::Geometry::TBlockData3< bool, BlockSize_ > Class Template Reference
UE::Geometry::TBlockData3< bool, BlockSize_ > Class Template Reference
#include "BlockedDenseGrid3.h"
Public Types
typedef TInlineAllocator< DataLayout::ElemCount > AllocatorType
typedef TConstSetBitIterator< AllocatorType > BitArrayConstIterator
typedef TBitArray< AllocatorType > BlockDataBitMask
typedef TBlockData3Layout< BlockSize_ > DataLayout
typedef bool ElemType
typedef TStaticArray< ElemType, DataLayout::ElemCount > LinearDataStorageType
Public Member Functions
TBlockData3 (const ElemType &Value, const int32 ID)
FBitReference At (int32 LocalIndex)
bool At (int32 LocalIndex) const
template<typename FuncType>
void ModifyValue (const int32 Index, FuncType Func)
void Reset (const ElemType &Value)
void TopologyUnion (const TBlockData3< bool, BlockSize_ > &OtherBlockData)
Data Fields
BlockDataBitMask BitArray
LinearDataStorageType Data
int32 Id
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::TBlockData3Layout< BlockSize_ >
static int32 ToLinear (const int32 &LocalI, const int32 &LocalJ, const int32 &LocalK)
static FVector3i ToLocalIJK (int32 LocalLinear)
Static Public Attributes inherited from UE::Geometry::TBlockData3Layout< BlockSize_ >
static constexpr int32 BlockSize = BlockSize_
static constexpr int32 ElemCount = BlockSize_ * BlockSize_ * BlockSize_
Detailed Description
template<int32 BlockSize_>
class UE::Geometry::TBlockData3< bool, BlockSize_ >
Definition at line 76 of file BlockedDenseGrid3.h.
Member Typedef Documentation
AllocatorType
template<int32 BlockSize_> typedef TInlineAllocator<DataLayout::ElemCount> UE::Geometry::TBlockData3< bool, BlockSize_ >::AllocatorType
Definition at line 81 of file BlockedDenseGrid3.h.
BitArrayConstIterator
template<int32 BlockSize_> typedef TConstSetBitIterator<AllocatorType> UE::Geometry::TBlockData3< bool, BlockSize_ >::BitArrayConstIterator
Definition at line 83 of file BlockedDenseGrid3.h.
BlockDataBitMask
template<int32 BlockSize_> typedef TBitArray<AllocatorType> UE::Geometry::TBlockData3< bool, BlockSize_ >::BlockDataBitMask
Definition at line 82 of file BlockedDenseGrid3.h.
DataLayout
template<int32 BlockSize_> typedef TBlockData3Layout<BlockSize_> UE::Geometry::TBlockData3< bool, BlockSize_ >::DataLayout
Definition at line 79 of file BlockedDenseGrid3.h.
ElemType
template<int32 BlockSize_> typedef bool UE::Geometry::TBlockData3< bool, BlockSize_ >::ElemType
Definition at line 80 of file BlockedDenseGrid3.h.
LinearDataStorageType
typedef TStaticArray<ElemType, DataLayout::ElemCount> UE::Geometry::TBlockData3< bool, BlockSize_ >::LinearDataStorageType
Definition at line 28 of file BlockedDenseGrid3.h.
Constructor & Destructor Documentation
TBlockData3()
template<int32 BlockSize_> UE::Geometry::TBlockData3< bool, BlockSize_ >::TBlockData3 (const ElemType & Value, const int32 ID) inline
Definition at line 85 of file BlockedDenseGrid3.h.
References ID, Id, Reset, and Value.
Referenced by TopologyUnion().
Member Function Documentation
At() [1/2]
template<int32 BlockSize_> FBitReference UE::Geometry::TBlockData3< bool, BlockSize_ >::At (int32 LocalIndex) inline
Definition at line 96 of file BlockedDenseGrid3.h.
References BitArray, checkSlow, and UE::Geometry::TBlockData3Layout< BlockSize_ >::ElemCount.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial().
At() [2/2]
template<int32 BlockSize_> bool UE::Geometry::TBlockData3< bool, BlockSize_ >::At (int32 LocalIndex) const inline
Definition at line 102 of file BlockedDenseGrid3.h.
References BitArray, checkSlow, and UE::Geometry::TBlockData3Layout< BlockSize_ >::ElemCount.
ModifyValue()
template<int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBlockData3< bool, BlockSize_ >::ModifyValue (const int32 Index, FuncType Func) inline
Definition at line 109 of file BlockedDenseGrid3.h.
References BitArray, and Value.
Reset()
template<int32 BlockSize_> void UE::Geometry::TBlockData3< bool, BlockSize_ >::Reset (const ElemType & Value) inline
Definition at line 91 of file BlockedDenseGrid3.h.
References BitArray, UE::Geometry::TBlockData3Layout< BlockSize_ >::ElemCount, and Value.
TopologyUnion()
template<int32 BlockSize_> void UE::Geometry::TBlockData3< bool, BlockSize_ >::TopologyUnion (const TBlockData3< bool, BlockSize_ > & OtherBlockData) inline
Definition at line 117 of file BlockedDenseGrid3.h.
References TBlockData3(), BitArray, and MaintainSize.
Field Documentation
BitArray
template<int32 BlockSize_> BlockDataBitMask UE::Geometry::TBlockData3< bool, BlockSize_ >::BitArray
Definition at line 124 of file BlockedDenseGrid3.h.
Referenced by At(), At(), ModifyValue(), Reset(), and TopologyUnion().
Data
LinearDataStorageType UE::Geometry::TBlockData3< bool, BlockSize_ >::Data
Definition at line 70 of file BlockedDenseGrid3.h.
Id
template<int32 BlockSize_> int32 UE::Geometry::TBlockData3< bool, BlockSize_ >::Id
Definition at line 123 of file BlockedDenseGrid3.h.
Referenced by TBlockData3().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/BlockedDenseGrid3.h