Unreal Engine 5.6 C++ API: FWorldDataLayersActorDesc Class Reference
FWorldDataLayersActorDesc Class Reference
ActorDesc for AWorldDataLayers actors.
#include "WorldDataLayersActorDesc.h"
Public Member Functions
FWorldDataLayersActorDesc ()
const FDataLayerInstanceDesc * GetDataLayerInstanceFromAssetPath (FName InDataLayerAssetPath) const
const FDataLayerInstanceDesc * GetDataLayerInstanceFromInstanceName (FName InDataLayerInstanceName) const
const TArray< FDataLayerInstanceDesc > & GetDataLayerInstances () const
bool IsValid () const
Public Member Functions inherited from FWorldPartitionActorDesc
virtual ~FWorldPartitionActorDesc ()
void AddProperty (FName PropertyName, FName PropertyValue=NAME_None)
virtual void CheckForErrors (const IWorldPartitionActorDescInstanceView *InActorDescView, IStreamingGenerationErrorHandler *ErrorHandler) const
bool GetActorIsEditorOnly () const
bool GetActorIsEditorOnlyLoadedInPIE () const
bool GetActorIsHLODRelevant () const
bool GetActorIsRuntimeOnly () const
FName GetActorLabel () const
FName GetActorLabelOrName () const
const FString & GetActorLabelString () const
FName GetActorName () const
const FString & GetActorNameString () const
UClass * GetActorNativeClass () const
FName GetActorPackage () const
FSoftObjectPath GetActorSoftPath () const
const FTransform & GetActorTransform () const
FTopLevelAssetPath GetBaseClass () const
virtual UActorDescContainer * GetChildContainer () const
virtual const FWorldPartitionActorFilter * GetChildContainerFilter () const
virtual EWorldPartitionActorFilterType GetChildContainerFilterType () const
virtual FString GetChildContainerName () const
virtual FName GetChildContainerPackage () const
FGuid GetContentBundleGuid () const
TArray< FName > GetDataLayers (bool bIncludeExternalDataLayer=true) const
FName GetDisplayClassName () const
const FString & GetDisplayClassNameString () const
FBox GetEditorBounds () const
FName GetExternalDataLayer () const
const FSoftObjectPath & GetExternalDataLayerAsset () const
const FGuid & GetFolderGuid () const
FName GetFolderPath () const
const FGuid & GetGuid () const
FSoftObjectPath GetHLODLayer () const
bool GetIsSpatiallyLoaded () const
bool GetIsSpatiallyLoadedRaw () const
FTopLevelAssetPath GetNativeClass () const
const FGuid & GetParentActor () const
bool GetProperty (FName PropertyName, FName *PropertyValue) const
FBox GetRuntimeBounds () const
FName GetRuntimeGrid () const
virtual const FGuid & GetSceneOutlinerParent () const
const TArray< FName > & GetTags () const
bool HasProperty (FName PropertyName) const
virtual bool HasStandaloneHLOD () const
virtual void Init (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsChildContainerInstance () const
bool IsDefaultActorDesc () const
bool IsListedInSceneOutliner () const
bool IsMainWorldOnly () const
bool IsUsingDataLayerAsset () const
bool operator== (const FWorldPartitionActorDesc &Other) const
void SerializeTo (TArray< uint8 > &OutData, FWorldPartitionActorDesc *BaseDesc=nullptr) const
virtual bool ShouldResave (const FWorldPartitionActorDesc *Other) const
Returns true if resaving this actor will have an impact on streaming generation.
FString ToString (EToStringMode Mode=EToStringMode::Compact) const
UE_DEPRECATED (5.1, "SetIsSpatiallyLoadedRaw is deprecated and should not be used.") inline void SetIsSpatiallyLoadedRaw(bool bNewIsSpatiallyLoaded)
UE_DEPRECATED (5.2, "GetBounds is deprecated, GetEditorBounds or GetRuntimeBounds should be used instead.") FBox GetBounds() const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "GetOrigin is deprecated.") inline FVector GetOrigin() const
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "ShouldValidateRuntimeGrid is deprecated and should not be used") virtual bool ShouldValidateRuntimeGrid() const
UE_DEPRECATED (5.3, "GetLevelPackage is deprecated use GetChildContainerPackage instead") virtual FName GetLevelPackage() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::GetUnloadedReason") FText GetUnloadedReason() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::SetUnloadedReason") void SetUnloadedReason(FText *InUnloadedReason)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::GetDataLayerInstanceNames") TArray< FName > GetDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::HasResolvedDataLayerInstanceNames") inline bool HasResolvedDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsEditorRelevant instead") virtual bool IsEditorRelevant() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsRuntimeRelevant instead") virtual bool IsRuntimeRelevant(const FActorContainerID &InContainerID) const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::SetDataLayerInstanceNames") inline void SetDataLayerInstanceNames(const TArray< FName > &InDataLayerInstanceNames)
UE_DEPRECATED (5.4, "Use GetChildContainerFilter instead") virtual const FWorldPartitionActorFilter *GetContainerFilter() const
UE_DEPRECATED (5.4, "Use GetChildContainerFilterType instead") virtual EWorldPartitionActorFilterType GetContainerFilterType() const
UE_DEPRECATED (5.4, "Use GetChildContainerInstance instead") virtual bool GetContainerInstance(FContainerInstance &OutContainerInstance) const
UE_DEPRECATED (5.4, "Use GetChildContainerPackage instead") virtual FName GetContainerPackage() const
UE_DEPRECATED (5.4, "Use IsChildContainerInstance instead") virtual bool IsContainerInstance() const
UE_DEPRECATED (5.4, "Use SetContainer without World param") virtual void SetContainer(UActorDescContainer *InContainer
Protected Member Functions
virtual bool Equals (const FWorldPartitionActorDesc *Other) const override
virtual uint32 GetSizeOf () const override
virtual void Init (const AActor *InActor) override
virtual bool IsResaveNeeded () const override
virtual bool IsRuntimeRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const override
virtual void Serialize (FArchive &Ar) override
Protected Member Functions inherited from FWorldPartitionActorDesc
FWorldPartitionActorDesc ()
virtual UActorDescContainerInstance * CreateChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual bool GetChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance, FContainerInstance &OutContainerInstance) const
virtual UWorldPartition * GetLoadedChildWorldPartition (const FWorldPartitionActorDescInstance *InActorDescInstance) const
void InitTransientProperties (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsEditorRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const
void SetEditorBounds (const FBox &InEditorBounds)
void SetRuntimeBounds (const FBox &InRuntimeBounds)
virtual void TransferFrom (const FWorldPartitionActorDesc *From)
virtual void TransferWorldData (const FWorldPartitionActorDesc *From)
Private Member Functions
void ForEachDataLayerInstanceDesc (TFunctionRef< bool(const FDataLayerInstanceDesc &)> Func) const
const TArray< FDataLayerInstanceDesc > & GetExternalPackageDataLayerInstances () const
Private Attributes
bool bIsExternalDataLayerWorldDataLayers
bool bIsValid
bool bUseExternalPackageDataLayerInstances
TArray< FDataLayerInstanceDesc > DataLayerInstances
TOptional< TArray< FDataLayerInstanceDesc > > ExternalPackageDataLayerInstances
Additional Inherited Members
Public Types inherited from FWorldPartitionActorDesc
enum class EToStringMode : uint8 {
Guid , Compact , Full , Verbose ,
ForDiff
}
using FActorDescDeprecator = TFunction<void(FArchive&, FWorldPartitionActorDesc*)>
Static Public Member Functions inherited from FWorldPartitionActorDesc
static void Patch (const FWorldPartitionActorDescInitData &DescData, TArray< uint8 > &OutData, FWorldPartitionAssetDataPatcher *InAssetDataPatcher)
static void RegisterActorDescDeprecator (TSubclassOf< AActor > ActorClass, const FActorDescDeprecator &Deprecator)
Data Fields inherited from FWorldPartitionActorDesc
UWorld * InWorldContext
Protected Attributes inherited from FWorldPartitionActorDesc
FString ActorDisplayClassNameString
FName ActorLabel
FString ActorLabelString
FName ActorName
FString ActorNameString
UClass * ActorNativeClass
FName ActorPackage
FSoftObjectPath ActorPath
FTransform ActorTransform
FTransform ActorTransformRelative
bool bActorIsEditorOnly
bool bActorIsHLODRelevant
bool bActorIsListedInSceneOutliner
bool bActorIsMainWorldOnly
bool bActorIsRuntimeOnly
FTopLevelAssetPath BaseClass
bool bHasValidRelativeBounds
bool bIsDefaultActorDesc
bool bIsSpatiallyLoaded
bool bIsUsingDataLayerAsset
UActorDescContainer * Container
FGuid ContentBundleGuid
TArray< FName > DataLayers
FBox EditorBounds
FWorldPartitionRelativeBounds EditorBoundsRelative
TArray< FGuid > EditorOnlyReferences
FSoftObjectPath ExternalDataLayerAsset
FGuid FolderGuid
FName FolderPath
FGuid Guid
FSoftObjectPath HLODLayer
FTopLevelAssetPath NativeClass
FGuid ParentActor
FPropertyPairsMap Properties
TArray< FGuid > References
FBox RuntimeBounds
FWorldPartitionRelativeBounds RuntimeBoundsRelative
FName RuntimeGrid
TArray< FName > Tags
Static Protected Attributes inherited from FWorldPartitionActorDesc
static TMap< TSubclassOf< AActor >, FActorDescDeprecator > Deprecators
Detailed Description
ActorDesc for AWorldDataLayers actors.
Definition at line 63 of file WorldDataLayersActorDesc.h.
Constructor & Destructor Documentation
FWorldDataLayersActorDesc()
FWorldDataLayersActorDesc::FWorldDataLayersActorDesc ()
Referenced by GetSizeOf().
Member Function Documentation
Equals()
virtual bool FWorldDataLayersActorDesc::Equals (const FWorldPartitionActorDesc * Other) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDesc(), and Other.
ForEachDataLayerInstanceDesc()
void FWorldDataLayersActorDesc::ForEachDataLayerInstanceDesc (TFunctionRef< bool(const FDataLayerInstanceDesc &)> Func) const private
GetDataLayerInstanceFromAssetPath()
const FDataLayerInstanceDesc * FWorldDataLayersActorDesc::GetDataLayerInstanceFromAssetPath (FName InDataLayerAssetPath) const
GetDataLayerInstanceFromInstanceName()
const FDataLayerInstanceDesc * FWorldDataLayersActorDesc::GetDataLayerInstanceFromInstanceName (FName InDataLayerInstanceName) const
GetDataLayerInstances()
const TArray< FDataLayerInstanceDesc > & FWorldDataLayersActorDesc::GetDataLayerInstances () const
GetExternalPackageDataLayerInstances()
const TArray< FDataLayerInstanceDesc > & FWorldDataLayersActorDesc::GetExternalPackageDataLayerInstances () const private
GetSizeOf()
virtual uint32 FWorldDataLayersActorDesc::GetSizeOf () const inline override protected virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 76 of file WorldDataLayersActorDesc.h.
References FWorldDataLayersActorDesc().
Init()
virtual void FWorldDataLayersActorDesc::Init (const AActor * InActor) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::AActor.
IsResaveNeeded()
virtual bool FWorldDataLayersActorDesc::IsResaveNeeded () const inline override protected virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 78 of file WorldDataLayersActorDesc.h.
References IsValid().
IsRuntimeRelevant()
virtual bool FWorldDataLayersActorDesc::IsRuntimeRelevant (const FWorldPartitionActorDescInstance * InActorDescInstance) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDescInstance.
IsValid()
bool FWorldDataLayersActorDesc::IsValid () const inline
Definition at line 67 of file WorldDataLayersActorDesc.h.
References bIsValid.
Referenced by IsResaveNeeded().
Serialize()
virtual void FWorldDataLayersActorDesc::Serialize (FArchive & Ar) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References Ar.
Field Documentation
bIsExternalDataLayerWorldDataLayers
bool FWorldDataLayersActorDesc::bIsExternalDataLayerWorldDataLayers private
Definition at line 90 of file WorldDataLayersActorDesc.h.
bIsValid
bool FWorldDataLayersActorDesc::bIsValid private
Definition at line 89 of file WorldDataLayersActorDesc.h.
Referenced by IsValid().
bUseExternalPackageDataLayerInstances
bool FWorldDataLayersActorDesc::bUseExternalPackageDataLayerInstances private
Definition at line 91 of file WorldDataLayersActorDesc.h.
DataLayerInstances
TArray<FDataLayerInstanceDesc> FWorldDataLayersActorDesc::DataLayerInstances private
Definition at line 87 of file WorldDataLayersActorDesc.h.
ExternalPackageDataLayerInstances
TOptional<TArray<FDataLayerInstanceDesc> > FWorldDataLayersActorDesc::ExternalPackageDataLayerInstances mutable private
Definition at line 88 of file WorldDataLayersActorDesc.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/DataLayer/WorldDataLayersActorDesc.h