Unreal Engine 5.6 C++ API: FName Class Reference
FName Class Reference
Public name, available to the world.
#include "NameTypes.h"
Public Types
using IntrusiveUnsetOptionalStateType = FName
Public Member Functions
FORCEINLINE FName ()
Default constructor, initialized to None.
FName (const ANSICHAR *Name, EFindName FindType=FNAME_Add)
FName (const ANSICHAR *Name, int32 Number)
FName (const FNameEntrySerialized &LoadedEntry)
Constructor used by FLinkerLoad when loading its name table; Creates an FName with an instance number of 0 that does not attempt to split the FName into string and number portions.
FName (const TCHAR *Name, int32 InNumber, bool bSplitName)
Create an FName.
FName (const UTF8CHAR *Name, EFindName FindType=FNAME_Add)
FName (const UTF8CHAR *Name, int32 Number)
FName (const WIDECHAR *Name, EFindName FindType=FNAME_Add)
Create an FName.
FName (const WIDECHAR *Name, int32 Number)
Create an FName.
FORCEINLINE FName (EName Ename)
Create an FName with a hardcoded string index.
FORCEINLINE FName (EName Ename, int32 InNumber)
Create an FName with a hardcoded string index and (instance).
FName (ENoInit)
Scary no init constructor, used for something obscure in UObjectBase.
FName (FIntrusiveUnsetOptionalState I)
Special constructor used by TOptional<FName>
FORCEINLINE FName (FMemoryImageName InName)
FORCEINLINE FName (FMinimalName InName)
FORCEINLINE FName (FName Other, int32 InNumber)
Create an FName from an existing string, but with a different instance.
FORCEINLINE FName (FNameEntryId InComparisonIndex, FNameEntryId InDisplayIndex, int32 InNumber)
Create an FName from its component parts Only call this if you really know what you're doing.
FORCEINLINE FName (FScriptName InName)
FName (int32 Len, const ANSICHAR *Name, EFindName FindType=FNAME_Add)
FName (int32 Len, const ANSICHAR *Name, int32 Number)
FName (int32 Len, const UTF8CHAR *Name, EFindName FindType=FNAME_Add)
FName (int32 Len, const UTF8CHAR *Name, int32 Number)
FName (int32 Len, const WIDECHAR *Name, EFindName FindType=FNAME_Add)
Create FName from non-null string with known length.
FName (int32 Len, const WIDECHAR *Name, int32 Number)
FName (TStringView< ANSICHAR > View, EFindName FindType=FNAME_Add)
FName (TStringView< ANSICHAR > View, int32 InNumber)
FName (TStringView< UTF8CHAR > View, EFindName FindType=FNAME_Add)
FName (TStringView< UTF8CHAR > View, int32 InNumber)
FName (TStringView< WIDECHAR > View, EFindName FindType=FNAME_Add)
FName (TStringView< WIDECHAR > View, int32 InNumber)
void AppendString (FUtf8String &Out) const
void AppendString (FUtf8StringBuilderBase &Out) const
void AppendString (FWideString &Out) const
Converts an FName to a readable format, in place, appending to an existing string (ala GetFullName)
void AppendString (FWideStringBuilderBase &Out) const
Converts an FName to a readable format, in place, appending to an existing string (ala GetFullName)
int32 Compare (const FName &Other) const
Compares name to passed in one.
FORCEINLINE int32 CompareIndexes (const FName &Other) const
Fast non-alphabetical order that is only stable during this process' lifetime.
FORCEINLINE bool FastLess (const FName &Other) const
Fast non-alphabetical order that is only stable during this process' lifetime.
FORCEINLINE FNameEntryId GetComparisonIndex () const
const FNameEntry * GetComparisonNameEntry () const
FORCEINLINE FNameEntryId GetDisplayIndex () const
const FNameEntry * GetDisplayNameEntry () const
FORCEINLINE int32 GetNumber () const
void GetPlainANSIString (ANSICHAR(&AnsiName)[NAME_SIZE]) const
Copy ANSI name without number part.
FString GetPlainNameString () const
Get name without number part as a dynamically allocated string.
uint32 GetPlainNameString (TCHAR(&OutName)[NAME_SIZE]) const
Convert name without number part into TCHAR buffer and returns string length.
void GetPlainWIDEString (WIDECHAR(&WideName)[NAME_SIZE]) const
Copy wide name without number part.
uint32 GetStringLength () const
Get the number of characters, excluding null-terminator, that ToString() would yield.
FORCEINLINE bool IsEqual (const FName &Other, const ENameCase CompareMethod=ENameCase::IgnoreCase, const bool bCompareNumber=true) const
Check to see if this FName matches the other FName, potentially also checking for any case variations.
FORCEINLINE bool IsNone () const
True for FName(), FName(NAME_None) and FName("None")
bool IsValid () const
Paranoid sanity check.
bool IsValidGroupName (FText &OutReason, bool bIsGroupName=false) const
Takes an FName and checks to see that it follows the rules that Unreal requires for package or group names.
bool IsValidIndexFast () const
Paranoid sanity check, same as IsValid()
bool IsValidObjectName (FText &OutReason) const
Takes an FName and checks to see that it follows the rules that Unreal requires for object names.
bool IsValidXName () const
bool IsValidXName (const FString &InInvalidChars, FText *OutReason=nullptr, const FText *InErrorCtx=nullptr) const
Checks to see that a FName follows the rules that Unreal requires.
bool IsValidXName (FText &OutReason) const
bool IsValidXName (FText &OutReason, const FString &InInvalidChars) const
Takes an FName and checks to see that it follows the rules that Unreal requires.
FORCEINLINE bool LexicalLess (const FName &Other) const
Slow alphabetical order that is stable / deterministic over process runs.
FORCEINLINE bool operator!= (FName Other) const
bool operator== (FIntrusiveUnsetOptionalState I) const
Special comparison operator for TOptional<FName>::IsSet.
FORCEINLINE bool operator== (FName Other) const
FORCEINLINE void SetNumber (const int32 NewNumber)
const EName * ToEName () const
Get the EName that this FName represents or nullptr.
FString ToString () const
Converts an FName to a readable format.
void ToString (FUtf8String &Out) const
void ToString (FUtf8StringBuilderBase &Out) const
void ToString (FWideString &Out) const
Converts an FName to a readable format, in place.
void ToString (FWideStringBuilderBase &Out) const
Converts an FName to a readable format, in place.
template<uint32 N>
uint32 ToString (TCHAR(&Out)[N]) const
Converts the FName to a string buffer, avoiding dynamic allocations.
uint32 ToStringTruncate (TCHAR *Out, uint32 OutSize) const
Converts the FName to a string buffer, avoiding dynamic allocations.
template<uint32 N>
uint32 ToStringTruncate (TCHAR(&Out)[N]) const
FORCEINLINE uint64 ToUnstableInt () const
Returns an integer that compares equal in the same way FNames do, only usable within the current process.
FUtf8String ToUtf8String () const
Converts an FName to a readable format.
bool TryAppendAnsiString (FAnsiStringBuilderBase &Out) const
Converts an ANSI FName to a readable format appended to the string builder.
UE_DEPRECATED (5.6, "FName::ToString(TCHAR* Out, uint32 OutSize) is dangerous and can lead to buffer overflow if the provided " "buffer is smaller than FName::StringBufferSize, even if the OutSize parameter indicates the buffer is " "smaller than this value. Use the templated ToString() or ToStringTruncate() functions to format the name " "string into a pre-allocated array, or use the allocating ToString() functions that return an FString.") uint32 ToString(TCHAR *Out
Convert to string buffer to avoid dynamic allocations and returns string length.
Static Public Member Functions
static void AddNameToDisplayStringExemption (const FString &InExemption)
Add/remove an exemption to the formatting applied by NameToDisplayString.
static void AutoTest ()
Run autotest on FNames.
static FName CreateFromDisplayId (FNameEntryId DisplayId, int32 Number)
Only call this if you really know what you're doing.
static TArray< const FNameEntry * > DebugDump ()
static void DisplayHash (class FOutputDevice &Ar)
static FNameEntryId GetComparisonIdFromDisplayId (FNameEntryId DisplayId)
static FNameEntry const * GetEntry (EName Ename)
static FNameEntry const * GetEntry (FNameEntryId Id)
static int32 GetNameEntryMemoryEstimatedAvailable ()
static int32 GetNameEntryMemorySize ()
static int32 GetNameTableMemorySize ()
static int32 GetNumAnsiNames ()
static int32 GetNumWideNames ()
static bool IsValidXName (const FName InName, const FString &InInvalidChars, FText *OutReason=nullptr, const FText *InErrorCtx=nullptr)
Checks to see that a given name-like string follows the rules that Unreal requires.
static bool IsValidXName (const FString &InName, const FString &InInvalidChars, FText *OutReason=nullptr, const FText *InErrorCtx=nullptr)
static bool IsValidXName (const FStringView &InName, const FString &InInvalidChars, FText *OutReason=nullptr, const FText *InErrorCtx=nullptr)
static bool IsValidXName (const TCHAR *InName, const FString &InInvalidChars, FText *OutReason=nullptr, const FText *InErrorCtx=nullptr)
static FString NameToDisplayString (const FString &InDisplayName, const bool bIsBool)
Takes a string and breaks it down into a human readable string.
static void RemoveNameToDisplayStringExemption (const FString &InExemption)
static void Reserve (uint32 NumBytes, uint32 NumNames)
static FString SafeString (FNameEntryId InDisplayIndex, int32 InstanceNumber=0)
static FString SanitizeWhitespace (const FString &FNameString)
Printing FNames in logging or on screen can be problematic when they contain Whitespace characters such as
and \r, so this will return an FName based upon the calling FName, but with any Whitespace characters potentially problematic for showing in a log or on screen omitted.
static void TearDown ()
Tear down system and free all allocated memory.
Data Fields
uint32 OutSize const
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
static constexpr uint32 StringBufferSize = NAME_SIZE + 1 + 10
Buffer size required for any null-terminated FName string, i.e.
Private Member Functions
template<typename StringBufferType>
FORCEINLINE void AppendStringInternal (StringBufferType &Out) const
friend FMemoryImageName::FMemoryImageName (const FName &Name)
friend FMinimalName::FMinimalName (const FName &Name)
friend FScriptName::FScriptName (const FName &Name)
FORCEINLINE FNameEntryId GetComparisonIndexInternal () const
FORCEINLINE FNameEntryId GetDisplayIndexFast () const
FORCEINLINE FNameEntryId GetDisplayIndexInternal () const
uint32 ToStringInternal (TCHAR *Out, uint32 OutSize) const
Internal implementation of non-allocating ToString().
Static Private Member Functions
static FORCEINLINE FName CreateNumberedNameIfNecessary (FNameEntryId ComparisonId, FNameEntryId DisplayId, int32 Number)
static FORCEINLINE FName CreateNumberedNameIfNecessary (FNameEntryId ComparisonId, int32 Number)
static bool Equals (FName A, const ANSICHAR *B)
static bool Equals (FName A, const WIDECHAR *B)
static FORCEINLINE bool Equals (FName A, EName B)
static bool Equals (FName A, FAnsiStringView B)
static FORCEINLINE bool Equals (FName A, FMemoryImageName B)
static FORCEINLINE bool Equals (FName A, FMinimalName B)
static bool Equals (FName A, FName B)=delete
static FORCEINLINE bool Equals (FName A, FScriptName B)
static bool Equals (FName A, FWideStringView B)
static bool IsWithinBounds (FNameEntryId Id)
static const FNameEntry * ResolveEntry (FNameEntryId LookupId)
static const FNameEntry * ResolveEntryRecursive (FNameEntryId LookupId)
Private Attributes
FNameEntryId ComparisonIndex
Index into the Names array (used to find String portion of the string/number pair used for comparison)
uint32 Number
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Friends
const TCHAR * DebugFName (FName &)
const TCHAR * DebugFName (int32)
const TCHAR * DebugFName (int32, int32)
struct FNameHelper
FORCEINLINE uint32 GetTypeHash (FName Name)
FMinimalName NameToMinimalName (FName InName)
FScriptName NameToScriptName (FName InName)
template<typename T>
FORCEINLINE auto operator!= (FName N, T O) -> decltype(FName::Equals(N, O))
template<typename T>
FORCEINLINE auto operator!= (T O, FName N) -> decltype(FName::Equals(N, O))
template<typename T>
FORCEINLINE auto operator== (FName N, T O) -> decltype(FName::Equals(N, O))
template<typename T>
FORCEINLINE auto operator== (T O, FName N) -> decltype(FName::Equals(N, O))
Detailed Description
Public name, available to the world.
Names are stored as a combination of an index into a table of unique strings and an instance number. Names are case-insensitive, but case-preserving (when WITH_CASE_PRESERVING_NAME is 1)
Definition at line 575 of file NameTypes.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
using FName::IntrusiveUnsetOptionalStateType = FName
Definition at line 579 of file NameTypes.h.
Constructor & Destructor Documentation
FName() [1/30]
FORCEINLINE FName::FName (EName Ename) inline
Create an FName with a hardcoded string index.
Parameters
N The hardcoded value the string portion of the name will have. The number portion will be NAME_NO_NUMBER
Definition at line 918 of file NameTypes.h.
References FName(), FORCEINLINE, and NAME_NO_NUMBER_INTERNAL.
Referenced by FName(), FName(), FName(), FName(), FName(), FName(), FName(), FName(), FName(), FName(), Compare(), CompareIndexes(), CreateFromDisplayId(), CreateNumberedNameIfNecessary(), CreateNumberedNameIfNecessary(), DebugFName, Equals(), Equals(), Equals(), Equals(), Equals(), Equals(), Equals(), Equals(), Equals(), FastLess(), FMemoryImageName::FMemoryImageName(), FMinimalName::FMinimalName(), FNameHelper, FScriptName::FScriptName(), GetEntry(), GetTypeHash, IsEqual(), IsValidXName(), IsWithinBounds(), LexicalLess(), NameToMinimalName, NameToScriptName, operator!=, operator!=(), operator!=, operator==, operator==(), operator==, ToUnstableInt(), and TryAppendAnsiString().
FName() [2/30]
FORCEINLINE FName::FName (EName Ename, int32 InNumber) inline
Create an FName with a hardcoded string index and (instance).
Parameters
N The hardcoded value the string portion of the name will have
InNumber The hardcoded value for the number portion of the name
Definition at line 926 of file NameTypes.h.
References FName(), CreateNumberedNameIfNecessary(), and FORCEINLINE.
FName() [3/30]
FORCEINLINE FName::FName (FName Other, int32 InNumber) inline
Create an FName from an existing string, but with a different instance.
Parameters
Other The FName to take the string values from
InNumber The hardcoded value for the number portion of the name
Definition at line 938 of file NameTypes.h.
References FName(), CreateNumberedNameIfNecessary(), FORCEINLINE, GetComparisonIndex(), GetDisplayIndex(), and Other.
FName() [4/30]
FORCEINLINE FName::FName (FNameEntryId InComparisonIndex, FNameEntryId InDisplayIndex, int32 InNumber) inline
Create an FName from its component parts Only call this if you really know what you're doing.
Definition at line 947 of file NameTypes.h.
References FName(), CreateNumberedNameIfNecessary(), and FORCEINLINE.
FName() [5/30]
FORCEINLINE FName::FName () inline
Default constructor, initialized to None.
Definition at line 976 of file NameTypes.h.
References FORCEINLINE, and NAME_NO_NUMBER_INTERNAL.
Referenced by FName(), FName(), FName(), FName(), FName(), FName(), CreateFromDisplayId(), and Equals().
FName() [6/30]
FName::FName (ENoInit) inline explicit
Scary no init constructor, used for something obscure in UObjectBase.
Definition at line 986 of file NameTypes.h.
References ComparisonIndex, NoInit, and WITH_CASE_PRESERVING_NAME.
FName() [7/30]
FName::FName (FIntrusiveUnsetOptionalState I) inline explicit
Special constructor used by TOptional<FName>
Definition at line 994 of file NameTypes.h.
References ComparisonIndex, NAME_NO_NUMBER_INTERNAL, Number, UE_FNAME_OUTLINE_NUMBER, and WITH_CASE_PRESERVING_NAME.
FName() [8/30]
FORCEINLINE FName::FName (FMinimalName InName) explicit
Definition at line 1492 of file NameTypes.h.
References ComparisonIndex, FMinimalName::FMinimalName(), FORCEINLINE, InName, Number, and WITH_CASE_PRESERVING_NAME.
FName() [9/30]
FORCEINLINE FName::FName (FScriptName InName) explicit
Definition at line 1501 of file NameTypes.h.
References ComparisonIndex, FORCEINLINE, FScriptName::FScriptName(), InName, Number, and WITH_CASE_PRESERVING_NAME.
FName() [10/30]
FORCEINLINE FName::FName (FMemoryImageName InName)
Definition at line 1510 of file NameTypes.h.
References ComparisonIndex, FMemoryImageName::FMemoryImageName(), FORCEINLINE, InName, Number, and WITH_CASE_PRESERVING_NAME.
FName() [11/30]
FName::FName (const WIDECHAR * Name, EFindName FindType = FNAME_Add)
Create an FName.
If FindType is FNAME_Find, and the name doesn't already exist, then the name will be NAME_None. The check for existance or not depends on UE_FNAME_OUTLINE_NUMBER. When UE_FNAME_OUTLINE_NUMBER is 0, we only check for the string part. When UE_FNAME_OUTLINE_NUMBER is 1, we check for whole name including the number.
Parameters
Name Value for the string portion of the name
FindType Action to take (see EFindName)
References FNAME_Add, and Name.
FName() [12/30]
FName::FName (const ANSICHAR * Name, EFindName FindType = FNAME_Add)
References FNAME_Add, and Name.
FName() [13/30]
FName::FName (const UTF8CHAR * Name, EFindName FindType = FNAME_Add)
References FNAME_Add, and Name.
FName() [14/30]
FName::FName (int32 Len, const WIDECHAR * Name, EFindName FindType = FNAME_Add)
Create FName from non-null string with known length.
References FNAME_Add, and Name.
FName() [15/30]
FName::FName (int32 Len, const ANSICHAR * Name, EFindName FindType = FNAME_Add)
References FNAME_Add, and Name.
FName() [16/30]
FName::FName (int32 Len, const UTF8CHAR * Name, EFindName FindType = FNAME_Add)
References FNAME_Add, and Name.
FName() [17/30]
FName::FName (TStringView< ANSICHAR > View, EFindName FindType = FNAME_Add) inline explicit
Definition at line 1028 of file NameTypes.h.
References FName(), FName(), FNAME_Add, TStringView< CharType >::GetData(), TStringView< CharType >::Len(), and NoInit.
FName() [18/30]
FName::FName (TStringView< WIDECHAR > View, EFindName FindType = FNAME_Add) inline explicit
Definition at line 1033 of file NameTypes.h.
References FName(), FName(), FNAME_Add, TStringView< CharType >::GetData(), TStringView< CharType >::Len(), and NoInit.
FName() [19/30]
FName::FName (TStringView< UTF8CHAR > View, EFindName FindType = FNAME_Add) inline explicit
Definition at line 1038 of file NameTypes.h.
References FName(), FName(), FNAME_Add, TStringView< CharType >::GetData(), TStringView< CharType >::Len(), and NoInit.
FName() [20/30]
FName::FName (const WIDECHAR * Name, int32 Number)
Create an FName.
Will add the string to the name table if it does not exist. When UE_FNAME_OUTLINE_NUMBER is set, will also add the combination of base string and number to the name table if it doesn't exist.
Parameters
Name Value for the string portion of the name
Number Value for the number portion of the name
References Name, and Number.
FName() [21/30]
FName::FName (const ANSICHAR * Name, int32 Number)
References Name, and Number.
FName() [22/30]
FName::FName (const UTF8CHAR * Name, int32 Number)
References Name, and Number.
FName() [23/30]
FName::FName (int32 Len, const WIDECHAR * Name, int32 Number)
References Name, and Number.
FName() [24/30]
FName::FName (int32 Len, const ANSICHAR * Name, int32 Number)
References Name, and Number.
FName() [25/30]
FName::FName (int32 Len, const UTF8CHAR * Name, int32 Number)
References Name, and Number.
FName() [26/30]
FName::FName (TStringView< ANSICHAR > View, int32 InNumber) inline
Definition at line 1059 of file NameTypes.h.
References FName(), FName(), TStringView< CharType >::GetData(), TStringView< CharType >::Len(), and NoInit.
FName() [27/30]
FName::FName (TStringView< WIDECHAR > View, int32 InNumber) inline
Definition at line 1064 of file NameTypes.h.
References FName(), FName(), TStringView< CharType >::GetData(), TStringView< CharType >::Len(), and NoInit.
FName() [28/30]
FName::FName (TStringView< UTF8CHAR > View, int32 InNumber) inline
Definition at line 1069 of file NameTypes.h.
References FName(), FName(), TStringView< CharType >::GetData(), TStringView< CharType >::Len(), and NoInit.
FName() [29/30]
FName::FName (const TCHAR * Name, int32 InNumber, bool bSplitName)
Create an FName.
If FindType is FNAME_Find, and the string part of the name doesn't already exist, then the name will be NAME_None
Parameters
Name Value for the string portion of the name
Number Value for the number portion of the name
FindType Action to take (see EFindName)
bSplitName true if the trailing number should be split from the name when Number == NAME_NO_NUMBER_INTERNAL, or false to always use the name as-is
References Name.
FName() [30/30]
FName::FName (const FNameEntrySerialized & LoadedEntry)
Constructor used by FLinkerLoad when loading its name table; Creates an FName with an instance number of 0 that does not attempt to split the FName into string and number portions.
Also, this version skips calculating the hashes of the names if possible
Member Function Documentation
AddNameToDisplayStringExemption()
void FName::AddNameToDisplayStringExemption (const FString & InExemption) static
Add/remove an exemption to the formatting applied by NameToDisplayString.
Example: exempt the compound word "MetaHuman" to ensure its not reformatted as "Meta Human".
AppendString() [1/4]
void FName::AppendString (FUtf8String & Out) const
AppendString() [2/4]
void FName::AppendString (FUtf8StringBuilderBase & Out) const
AppendString() [3/4]
void FName::AppendString (FWideString & Out) const
Converts an FName to a readable format, in place, appending to an existing string (ala GetFullName)
Parameters
Out String to append with the string representation of the name
Referenced by FField::AppendName(), and UObjectBaseUtility::AppendName().
AppendString() [4/4]
void FName::AppendString (FWideStringBuilderBase & Out) const
Converts an FName to a readable format, in place, appending to an existing string (ala GetFullName)
Parameters
Out StringBuilder to append with the string representation of the name
AppendStringInternal()
template<typename StringBufferType> FORCEINLINE void FName::AppendStringInternal (StringBufferType & Out) const private
References FORCEINLINE.
AutoTest()
void FName::AutoTest () static
Run autotest on FNames.
Compare()
int32 FName::Compare (const FName & Other) const nodiscard
Compares name to passed in one.
Sort is alphabetical ascending.
Parameters
Other Name to compare this against
Returns
< 0 is this < Other, 0 if this == Other, > 0 if this > Other
References FName(), and Other.
Referenced by LexicalLess(), and UE::FPropertyPathNameTree::FKey::operator<.
CompareIndexes()
FORCEINLINE int32 FName::CompareIndexes (const FName & Other) const inline nodiscard
Fast non-alphabetical order that is only stable during this process' lifetime.
Parameters
Other Name to compare this against
Returns
< 0 is this < Other, 0 if this == Other, > 0 if this > Other
Definition at line 899 of file NameTypes.h.
References FName(), ComparisonIndex, FORCEINLINE, GetNumber(), and Other.
Referenced by FastLess().
CreateFromDisplayId()
FName FName::CreateFromDisplayId (FNameEntryId DisplayId, int32 Number) inline static nodiscard
Only call this if you really know what you're doing.
Definition at line 961 of file NameTypes.h.
References FName(), FName(), checkSlow, GetComparisonIdFromDisplayId(), Number, and ResolveEntry().
Referenced by FLinkerLoad::operator<<().
CreateNumberedNameIfNecessary() [1/2]
FORCEINLINE FName FName::CreateNumberedNameIfNecessary (FNameEntryId ComparisonId, FNameEntryId DisplayId, int32 Number) inline static nodiscard private
Definition at line 1256 of file NameTypes.h.
References FName(), ComparisonIndex, FORCEINLINE, NAME_NO_NUMBER_INTERNAL, and Number.
Referenced by FName(), FName(), FName(), and CreateNumberedNameIfNecessary().
CreateNumberedNameIfNecessary() [2/2]
FORCEINLINE FName FName::CreateNumberedNameIfNecessary (FNameEntryId ComparisonId, int32 Number) inline static nodiscard private
Definition at line 1277 of file NameTypes.h.
References FName(), CreateNumberedNameIfNecessary(), FORCEINLINE, and Number.
DebugDump()
TArray< const FNameEntry * > FName::DebugDump () static nodiscard
DisplayHash()
void FName::DisplayHash (class FOutputDevice & Ar) static
References Ar.
Equals() [1/9]
bool FName::Equals (FName A, const ANSICHAR * B) static nodiscard private
References FName(), A, and B.
Equals() [2/9]
bool FName::Equals (FName A, const WIDECHAR * B) static nodiscard private
References FName(), A, and B.
Equals() [3/9]
FORCEINLINE bool FName::Equals (FName A, EName B) inline static nodiscard private
Definition at line 1289 of file NameTypes.h.
References FName(), FName(), A, B, and FORCEINLINE.
Equals() [4/9]
bool FName::Equals (FName A, FAnsiStringView B) static nodiscard private
References FName(), A, and B.
Equals() [5/9]
FORCEINLINE bool FName::Equals (FName A, FMemoryImageName B) inline static nodiscard private
Definition at line 1323 of file NameTypes.h.
References FName(), A, B, FMemoryImageName::FMemoryImageName(), and FORCEINLINE.
Equals() [6/9]
FORCEINLINE bool FName::Equals (FName A, FMinimalName B) inline static nodiscard private
Definition at line 1315 of file NameTypes.h.
References FName(), A, B, FMinimalName::FMinimalName(), and FORCEINLINE.
Equals() [7/9]
bool FName::Equals (FName A, FName B) static nodiscard private delete
References FName(), A, and B.
Referenced by operator!=, operator!=, operator==, and operator==.
Equals() [8/9]
FORCEINLINE bool FName::Equals (FName A, FScriptName B) inline static nodiscard private
Definition at line 1319 of file NameTypes.h.
References FName(), A, B, FORCEINLINE, and FScriptName::FScriptName().
Equals() [9/9]
bool FName::Equals (FName A, FWideStringView B) static nodiscard private
References FName(), A, and B.
FastLess()
FORCEINLINE bool FName::FastLess (const FName & Other) const inline nodiscard
Fast non-alphabetical order that is only stable during this process' lifetime.
Definition at line 779 of file NameTypes.h.
References FName(), CompareIndexes(), FORCEINLINE, and Other.
Referenced by UE::Anim::FCurveUtils::BuildSortedFiltered().
FMemoryImageName::FMemoryImageName()
FName::FMemoryImageName::FMemoryImageName (const FName & Name) private
References FName(), and Name.
Referenced by FName(), and Equals().
FMinimalName::FMinimalName()
FName::FMinimalName::FMinimalName (const FName & Name) private
References FName(), and Name.
Referenced by FName(), Equals(), FNameHelper, and NameToMinimalName.
FScriptName::FScriptName()
FName::FScriptName::FScriptName (const FName & Name) private
References FName(), and Name.
Referenced by FName(), Equals(), FNameHelper, and NameToScriptName.
GetComparisonIdFromDisplayId()
FNameEntryId FName::GetComparisonIdFromDisplayId (FNameEntryId DisplayId) inline static nodiscard
Definition at line 955 of file NameTypes.h.
Referenced by CreateFromDisplayId().
GetComparisonIndex()
FORCEINLINE FNameEntryId FName::GetComparisonIndex () const inline nodiscard
Definition at line 585 of file NameTypes.h.
References checkName, ComparisonIndex, FORCEINLINE, and IsWithinBounds().
Referenced by FName(), and IsEqual().
GetComparisonIndexInternal()
FORCEINLINE FNameEntryId FName::GetComparisonIndexInternal () const inline nodiscard private
Definition at line 1229 of file NameTypes.h.
References ComparisonIndex, and FORCEINLINE.
GetComparisonNameEntry()
const FNameEntry * FName::GetComparisonNameEntry () const nodiscard
GetDisplayIndex()
FORCEINLINE FNameEntryId FName::GetDisplayIndex () const inline nodiscard
Definition at line 591 of file NameTypes.h.
References checkName, FORCEINLINE, GetDisplayIndexFast(), and IsWithinBounds().
Referenced by FName().
GetDisplayIndexFast()
FORCEINLINE FNameEntryId FName::GetDisplayIndexFast () const inline private
Definition at line 1219 of file NameTypes.h.
References ComparisonIndex, and FORCEINLINE.
Referenced by GetDisplayIndex(), and IsEqual().
GetDisplayIndexInternal()
FORCEINLINE FNameEntryId FName::GetDisplayIndexInternal () const inline nodiscard private
Definition at line 1235 of file NameTypes.h.
References ComparisonIndex, and FORCEINLINE.
GetDisplayNameEntry()
const FNameEntry * FName::GetDisplayNameEntry () const nodiscard
GetEntry() [1/2]
FNameEntry const * FName::GetEntry (EName Ename) static nodiscard
GetEntry() [2/2]
FNameEntry const * FName::GetEntry (FNameEntryId Id) static nodiscard
References FName(), and Name.
GetNameEntryMemoryEstimatedAvailable()
int32 FName::GetNameEntryMemoryEstimatedAvailable () static nodiscard
Returns
Estimated remaining size the name entry table is willing to allocate.
GetNameEntryMemorySize()
int32 FName::GetNameEntryMemorySize () static nodiscard
Returns
Size of all name entries.
GetNameTableMemorySize()
int32 FName::GetNameTableMemorySize () static nodiscard
Returns
Size of Name Table object as a whole
GetNumAnsiNames()
int32 FName::GetNumAnsiNames () static nodiscard
Returns
number of ansi names in name table
GetNumber()
FORCEINLINE int32 FName::GetNumber () const inline nodiscard
Definition at line 603 of file NameTypes.h.
References FORCEINLINE, and Number.
Referenced by CompareIndexes(), TProperty_Numeric< InTCppType >::ConvertFromType(), IsEqual(), IsNone(), and UE::FPropertyPathNameSegment::SetNameWithIndex().
GetNumWideNames()
int32 FName::GetNumWideNames () static nodiscard
Returns
number of wide names in name table
GetPlainANSIString()
void FName::GetPlainANSIString (ANSICHAR(&) AnsiName[NAME_SIZE]) const
Copy ANSI name without number part.
Must only be used for ANSI FNames. Doesn't allocate.
References NAME_SIZE.
GetPlainNameString() [1/2]
FString FName::GetPlainNameString () const nodiscard
Get name without number part as a dynamically allocated string.
GetPlainNameString() [2/2]
uint32 FName::GetPlainNameString (TCHAR(&) OutName[NAME_SIZE]) const
Convert name without number part into TCHAR buffer and returns string length.
Doesn't allocate.
References NAME_SIZE.
GetPlainWIDEString()
void FName::GetPlainWIDEString (WIDECHAR(&) WideName[NAME_SIZE]) const
Copy wide name without number part.
Must only be used for wide FNames. Doesn't allocate.
References NAME_SIZE.
GetStringLength()
uint32 FName::GetStringLength () const nodiscard
Get the number of characters, excluding null-terminator, that ToString() would yield.
IsEqual()
FORCEINLINE bool FName::IsEqual (const FName & Other, const ENameCase CompareMethod = ENameCase::IgnoreCase, const bool bCompareNumber = true) const nodiscard
Check to see if this FName matches the other FName, potentially also checking for any case variations.
Definition at line 1564 of file NameTypes.h.
References FName(), FORCEINLINE, GetComparisonIndex(), GetDisplayIndexFast(), GetNumber(), and IgnoreCase.
Referenced by FRigVMStringTag::Equals().
IsNone()
FORCEINLINE bool FName::IsNone () const inline nodiscard
True for FName(), FName(NAME_None) and FName("None")
Definition at line 791 of file NameTypes.h.
References ComparisonIndex, FORCEINLINE, GetNumber(), NAME_NO_NUMBER_INTERNAL, and ToUnstableInt().
Referenced by FBindingContext::FBindingContext(), FAssetData::AppendObjectPath(), FindFProperty(), RigVMTypeUtils::FindObjectGlobally(), FindUField(), FWorldPartitionActorDescInstance::GetActorLabelOrName(), IWorldPartitionActorDescInstanceView::GetActorLabelOrName(), UDeprecatedDataLayerInstance::GetDataLayerFName(), FFolder::IsNone(), TListTypeTraits< FName >::IsPtrValid(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FRigVMBranchInfoKey::operator==(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
IsValid()
bool FName::IsValid () const inline nodiscard
Paranoid sanity check.
All FNames are valid except for stomped memory, dangling pointers, etc. Should only be used to investigate such bugs and not in production code.
Definition at line 806 of file NameTypes.h.
References ComparisonIndex, and IsWithinBounds().
Referenced by TWidgetSlotWithAttributeSupport< SlotType >::Construct(), and IsValidIndexFast().
IsValidGroupName()
bool FName::IsValidGroupName (FText & OutReason, bool bIsGroupName = false) const
Takes an FName and checks to see that it follows the rules that Unreal requires for package or group names.
Parameters
OutReason If the check fails, this string is filled in with the reason why.
bIsGroupName if true, check legality for a group name, else check legality for a package name
Returns
true if the name is valid
IsValidIndexFast()
bool FName::IsValidIndexFast () const inline nodiscard
Paranoid sanity check, same as IsValid()
Definition at line 809 of file NameTypes.h.
References IsValid().
IsValidObjectName()
bool FName::IsValidObjectName (FText & OutReason) const
Takes an FName and checks to see that it follows the rules that Unreal requires for object names.
Parameters
OutReason If the check fails, this string is filled in with the reason why.
Returns
true if the name is valid
IsValidXName() [1/8]
bool FName::IsValidXName () const
Referenced by IsValidXName(), and IsValidXName().
IsValidXName() [2/8]
bool FName::IsValidXName (const FName InName, const FString & InInvalidChars, FText * OutReason = nullptr, const FText * InErrorCtx = nullptr) static
Checks to see that a given name-like string follows the rules that Unreal requires.
Parameters
InName String containing the name to test.
InInvalidChars The set of invalid characters that the name cannot contain.
OutReason If the check fails, this string is filled in with the reason why.
InErrorCtx Error context information to show in the error message (default is "Name").
Returns
true if the name is valid
References FName(), and InName.
IsValidXName() [3/8]
bool FName::IsValidXName (const FString & InInvalidChars, FText * OutReason = nullptr, const FText * InErrorCtx = nullptr) const inline
Checks to see that a FName follows the rules that Unreal requires.
Parameters
InInvalidChars The set of invalid characters that the name cannot contain
OutReason If the check fails, this string is filled in with the reason why.
InErrorCtx Error context information to show in the error message (default is "Name").
Returns
true if the name is valid
Definition at line 836 of file NameTypes.h.
References IsValidXName().
IsValidXName() [4/8]
bool FName::IsValidXName (const FString & InName, const FString & InInvalidChars, FText * OutReason = nullptr, const FText * InErrorCtx = nullptr) static
References InName.
IsValidXName() [5/8]
bool FName::IsValidXName (const FStringView & InName, const FString & InInvalidChars, FText * OutReason = nullptr, const FText * InErrorCtx = nullptr) static
References InName.
IsValidXName() [6/8]
bool FName::IsValidXName (const TCHAR * InName, const FString & InInvalidChars, FText * OutReason = nullptr, const FText * InErrorCtx = nullptr) static
References InName.
IsValidXName() [7/8]
bool FName::IsValidXName (FText & OutReason) const
IsValidXName() [8/8]
bool FName::IsValidXName (FText & OutReason, const FString & InInvalidChars) const inline
Takes an FName and checks to see that it follows the rules that Unreal requires.
Parameters
OutReason If the check fails, this string is filled in with the reason why.
InInvalidChars The set of invalid characters that the name cannot contain
Returns
true if the name is valid
Definition at line 850 of file NameTypes.h.
References IsValidXName().
IsWithinBounds()
bool FName::IsWithinBounds (FNameEntryId Id) static nodiscard private
References FName(), and Number.
Referenced by GetComparisonIndex(), GetDisplayIndex(), and IsValid().
LexicalLess()
FORCEINLINE bool FName::LexicalLess (const FName & Other) const inline nodiscard
Slow alphabetical order that is stable / deterministic over process runs.
Definition at line 785 of file NameTypes.h.
References FName(), Compare(), FORCEINLINE, and Other.
Referenced by UE_DEPRECATED().
NameToDisplayString()
FString FName::NameToDisplayString (const FString & InDisplayName, const bool bIsBool) static nodiscard
Takes a string and breaks it down into a human readable string.
For example - "bCreateSomeStuff" becomes "Create Some Stuff?" and "DrawScale3D" becomes "Draw Scale 3D".
Parameters
InDisplayName [In, Out] The name to sanitize
bIsBool True if the name is a bool
Returns
the sanitized version of the display name
Referenced by FGameModeInfoCustomizer::CreateGameModePropertyLabelWidget().
operator!=()
FORCEINLINE bool FName::operator!= (FName Other) const inline nodiscard
Definition at line 767 of file NameTypes.h.
References FName(), FORCEINLINE, and Other.
operator==() [1/2]
bool FName::operator== (FIntrusiveUnsetOptionalState I) const inline nodiscard
Special comparison operator for TOptional<FName>::IsSet.
Definition at line 773 of file NameTypes.h.
References ComparisonIndex.
operator==() [2/2]
FORCEINLINE bool FName::operator== (FName Other) const inline nodiscard
Definition at line 762 of file NameTypes.h.
References FName(), FORCEINLINE, Other, and ToUnstableInt().
RemoveNameToDisplayStringExemption()
void FName::RemoveNameToDisplayStringExemption (const FString & InExemption) static
Reserve()
void FName::Reserve (uint32 NumBytes, uint32 NumNames) static
ResolveEntry()
const FNameEntry * FName::ResolveEntry (FNameEntryId LookupId) static nodiscard private
Referenced by CreateFromDisplayId().
ResolveEntryRecursive()
const FNameEntry * FName::ResolveEntryRecursive (FNameEntryId LookupId) static nodiscard private
SafeString()
FString FName::SafeString (FNameEntryId InDisplayIndex, int32 InstanceNumber = 0) static nodiscard
References NAME_NO_NUMBER_INTERNAL.
SanitizeWhitespace()
FString FName::SanitizeWhitespace (const FString & FNameString) static nodiscard
Printing FNames in logging or on screen can be problematic when they contain Whitespace characters such as
and \r, so this will return an FName based upon the calling FName, but with any Whitespace characters potentially problematic for showing in a log or on screen omitted.
Returns
the new FName based upon the calling FName, but with any Whitespace characters potentially problematic for showing in a log or on screen omitted.
SetNumber()
FORCEINLINE void FName::SetNumber (const int32 NewNumber) inline
Definition at line 608 of file NameTypes.h.
References FORCEINLINE, and Number.
TearDown()
void FName::TearDown () static
Tear down system and free all allocated memory.
FName must not be used after teardown
References ComparisonIndex, and FORCEINLINE.
ToEName()
const EName * FName::ToEName () const nodiscard
Get the EName that this FName represents or nullptr.
Referenced by TProperty_Numeric< InTCppType >::ConvertFromType().
ToString() [1/6]
FString FName::ToString () const nodiscard
Converts an FName to a readable format.
Returns
String representation of the name
Referenced by FRigVMVariableMappingInfo::FRigVMVariableMappingInfo(), Metasound::TEnum< EDelayFilterType, EDelayFilterType::LowPass >::TEnum(), Metasound::MetasoundInputNodePrivate::TResetablePostExecutableInputOperator< DataType >::TResetablePostExecutableInputOperator(), Metasound::IDataTransmissionBase::CheckType(), TWidgetSlotWithAttributeSupport< SlotType >::Construct(), FDynamicStats::CreateMemoryStatId(), TListTypeTraits< FName >::DebugDump(), FindFieldChecked(), RigVMTypeUtils::FindObjectGlobally(), MaterialExpressionUtils::FormatUnsupportedMaterialDomainError(), Metasound::FAnyDataReference::TGetAs< TDataWriteReference< DataType > >::Get(), FShaderCode::GetFinalizedResource(), FLinkerInstancingContext::GetInstancedPackageName(), FFolder::GetLeafName(), FModuleManager::GetModuleChecked(), FObjectPtr::GetName(), UObjectBaseUtility::GetName(), UObjectBaseUtility::GetName(), UE::MovieScene::FBoolPropertyTraits::GetObjectPropertyValue(), UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue(), GetOverriddenOperationFromName(), FCommonNativeListItem::GetStaticItemTypeName(), FRigVMBranchInfoKey::GetTypeHash, FSkinWeightProfileStack::GetUniqueId(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), FMemoryArchive::operator<<(), FShaderCompilerDefinitions::FPairType::operator<<, FFolder::PathIsChildOf(), FFolder::ToString(), FPropertyPath::ToString(), TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::ToString(), UE_DEPRECATED(), UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateAnimatedBoneAttributes(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
ToString() [2/6]
void FName::ToString (FUtf8String & Out) const
ToString() [3/6]
void FName::ToString (FUtf8StringBuilderBase & Out) const
ToString() [4/6]
void FName::ToString (FWideString & Out) const
Converts an FName to a readable format, in place.
Parameters
Out String to fill with the string representation of the name
ToString() [5/6]
void FName::ToString (FWideStringBuilderBase & Out) const
Converts an FName to a readable format, in place.
Parameters
Out StringBuilder to fill with the string representation of the name
ToString() [6/6]
template<uint32 N> uint32 FName::ToString (TCHAR(&) Out[N]) const inline
Converts the FName to a string buffer, avoiding dynamic allocations.
Returns the length of the string, excluding the null terminator.
Note that a default constructed FName returns "None" instead of ""
Definition at line 703 of file NameTypes.h.
References StringBufferSize, ToStringInternal(), and UE_STATIC_DEPRECATE.
ToStringInternal()
uint32 FName::ToStringInternal (TCHAR * Out, uint32 OutSize) const private
Internal implementation of non-allocating ToString().
OutSize is the number of valid elements in the buffer, including the null terminator. Must be > 0. Returns the length of the string, excluding the null terminator.
Referenced by ToString(), and ToStringTruncate().
ToStringTruncate() [1/2]
uint32 FName::ToStringTruncate (TCHAR * Out, uint32 OutSize) const inline
Converts the FName to a string buffer, avoiding dynamic allocations.
Truncates the name if it does not fit in the specified output buffer. Use a buffer size of at least FName::StringBufferSize to avoid truncation.
Returns the length of the (possibly truncated) string, excluding the null terminator.
Note that a default constructed FName returns "None" instead of ""
Definition at line 720 of file NameTypes.h.
References ToStringInternal().
Referenced by ToStringTruncate().
ToStringTruncate() [2/2]
template<uint32 N> uint32 FName::ToStringTruncate (TCHAR(&) Out[N]) const inline
Definition at line 726 of file NameTypes.h.
References ToStringTruncate().
ToUnstableInt()
FORCEINLINE uint64 FName::ToUnstableInt () const inline nodiscard
Returns an integer that compares equal in the same way FNames do, only usable within the current process.
Definition at line 1181 of file NameTypes.h.
References FName(), ComparisonIndex, FORCEINLINE, FMemory::Memcpy(), Number, and STRUCT_OFFSET.
Referenced by IsNone(), and operator==().
ToUtf8String()
FUtf8String FName::ToUtf8String () const nodiscard
Converts an FName to a readable format.
Returns
String representation of the name
TryAppendAnsiString()
bool FName::TryAppendAnsiString (FAnsiStringBuilderBase & Out) const
Converts an ANSI FName to a readable format appended to the string builder.
Parameters
Out A string builder to write the readable representation of the name into.
Returns
Whether the string is ANSI. A return of false indicates that the string was wide and was not written.
References FName(), FORCEINLINE, IgnoreCase, and Other.
UE_DEPRECATED()
FName::UE_DEPRECATED (5. 6, "FName::ToString(TCHAR* Out, uint32 OutSize) is dangerous and can lead to buffer overflow if the provided " "buffer is smaller than FName::StringBufferSize , even if the OutSize parameter indicates the buffer is " "smaller than this value. Use the templated ToString() or ToStringTruncate() functions to format the name " "string into a pre-allocated array, or use the allocating ToString() functions that return an FString.")
Convert to string buffer to avoid dynamic allocations and returns string length.
Fails hard if OutLen < GetStringLength() + 1. StringBufferSize guarantees success.
Note that a default constructed FName returns "None" instead of ""
Friends And Related Symbol Documentation
DebugFName [1/3]
const TCHAR * DebugFName (FName &) friend
References FName().
DebugFName [2/3]
const TCHAR * DebugFName (int32) friend
DebugFName [3/3]
const TCHAR * DebugFName (int32 , int32) friend
FNameHelper
friend struct FNameHelper friend
Definition at line 1209 of file NameTypes.h.
References FName(), FMinimalName::FMinimalName(), FNameHelper, FScriptName::FScriptName(), and InName.
Referenced by FNameHelper.
GetTypeHash
FORCEINLINE uint32 GetTypeHash (FName Name) friend
Definition at line 1327 of file NameTypes.h.
References FName(), FORCEINLINE, GetTypeHash, and Name.
Referenced by GetTypeHash.
NameToMinimalName
FMinimalName NameToMinimalName (FName InName) friend
Definition at line 1581 of file NameTypes.h.
References FName(), FMinimalName::FMinimalName(), FORCEINLINE, and InName.
NameToScriptName
FScriptName NameToScriptName (FName InName) friend
Definition at line 1586 of file NameTypes.h.
References FName(), FORCEINLINE, FScriptName::FScriptName(), and InName.
operator!= [1/2]
template<typename T> FORCEINLINE auto operator!= (FName N, T O) -> decltype(FName::Equals(N, O)) friend
Definition at line 1347 of file NameTypes.h.
References FName(), Equals(), and FORCEINLINE.
operator!= [2/2]
template<typename T> FORCEINLINE auto operator!= (T O, FName N) -> decltype(FName::Equals(N, O)) friend
Definition at line 1353 of file NameTypes.h.
References FName(), Equals(), and FORCEINLINE.
operator== [1/2]
template<typename T> FORCEINLINE auto operator== (FName N, T O) -> decltype(FName::Equals(N, O)) friend
Definition at line 1334 of file NameTypes.h.
References FName(), Equals(), and FORCEINLINE.
operator== [2/2]
template<typename T> FORCEINLINE auto operator== (T O, FName N) -> decltype(FName::Equals(N, O)) friend
Definition at line 1340 of file NameTypes.h.
References FName(), Equals(), and FORCEINLINE.
Field Documentation
bHasIntrusiveUnsetOptionalState
bool FName::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 578 of file NameTypes.h.
ComparisonIndex
FNameEntryId FName::ComparisonIndex private
Index into the Names array (used to find String portion of the string/number pair used for comparison)
Definition at line 1195 of file NameTypes.h.
Referenced by FName(), FName(), FName(), FName(), FName(), CompareIndexes(), CreateNumberedNameIfNecessary(), GetComparisonIndex(), GetComparisonIndexInternal(), GetDisplayIndexFast(), GetDisplayIndexInternal(), IsNone(), IsValid(), operator==(), TearDown(), and ToUnstableInt().
const
uint32 OutSize FName::const
Initial value:
{
        return ToStringInternal(Out, StringBufferSize)
Definition at line 690 of file NameTypes.h.
Number
uint32 FName::Number private
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Definition at line 1198 of file NameTypes.h.
Referenced by FName(), FName(), FName(), FName(), FName(), FName(), FName(), FName(), FName(), FName(), CreateFromDisplayId(), CreateNumberedNameIfNecessary(), CreateNumberedNameIfNecessary(), GetNumber(), IsWithinBounds(), SetNumber(), and ToUnstableInt().
StringBufferSize
uint32 FName::StringBufferSize = NAME_SIZE + 1 + 10 inline static constexpr
Buffer size required for any null-terminated FName string, i.e.
[name] '_' [digits] '\0'
Definition at line 667 of file NameTypes.h.
Referenced by FShaderCompilerDefinitions::FPairType::operator<<, ToString(), and UE::Private::WorldPartition::UpdateHash().
The documentation for this class was generated from the following file:
Runtime/Core/Public/UObject/NameTypes.h