Unreal Engine 5.6 C++ API: IConsoleVariable Class Reference
IConsoleVariable Class Reference abstract
Interface for console variables.
#include "IConsoleManager.h"
Public Member Functions
virtual bool GetBool () const =0
Get the internal value as a bool, works on bools, ints and floats.
virtual FString GetDefaultValue ()=0
Get the value this CVar was constructed with.
virtual float GetFloat () const =0
Get the internal value as float (works on all types).
virtual SIZE_T GetHistorySize ()=0
Track memory used by history data.
virtual int32 GetInt () const =0
Get the internal value as int (should not be used on strings).
virtual FString GetString () const =0
Get the internal value as string (works on all types).
void GetValue (bool &OutBoolValue) const
void GetValue (float &OutFloatValue) const
void GetValue (FString &OutStringValue) const
void GetValue (int32 &OutIntValue) const
Generic versions for templated code.
virtual void LogHistory (FOutputDevice &Ar)=0
Print the history to a log.
virtual FConsoleVariableMulticastDelegate & OnChangedDelegate ()=0
void Set (bool InValue, EConsoleVariableFlags SetBy=ECVF_SetByCode, FName Tag=NAME_None)
Set the internal value from the specified bool.
virtual void Set (const TCHAR *InValue, EConsoleVariableFlags SetBy=ECVF_SetByCode, FName Tag=NAME_None)=0
Set the internal value from the specified string.
void Set (float InValue, EConsoleVariableFlags SetBy=ECVF_SetByCode, FName Tag=NAME_None)
Set the internal value from the specified float.
void Set (int32 InValue, EConsoleVariableFlags SetBy=ECVF_SetByCode, FName Tag=NAME_None)
Set the internal value from the specified int.
virtual void SetOnChangedCallback (const FConsoleVariableDelegate &Callback)=0
Allows to specify a callback function that is called when the console variable value changes.
void SetWithCurrentPriority (bool InValue, FName Tag=NAME_None)
void SetWithCurrentPriority (const TCHAR *InValue, FName Tag=NAME_None)
void SetWithCurrentPriority (float InValue, FName Tag=NAME_None)
void SetWithCurrentPriority (int32 InValue, FName Tag=NAME_None)
UE_DEPRECATED (5.4, "Use GetDefaultValue() instead") virtual IConsoleVariable *GetDefaultValueVariable()
Get the saved off default value, in a cvar variable, if one was created.
virtual void Unset (EConsoleVariableFlags SetBy, FName Tag=NAME_None)=0
Unsets the value at a certain SetBy priority (this is only useful when UE_ALLOW_CVAR_HISTORY is set).
Public Member Functions inherited from IConsoleObject
IConsoleObject ()
virtual ~IConsoleObject ()
virtual struct IConsoleCommand * AsCommand ()
Casts this object to an IConsoleCommand, verifying first that it is safe to do so.
virtual class IConsoleVariable * AsVariable ()
Casts this object to an IConsoleVariable, returns 0 if it's not.
virtual class TConsoleVariableData< bool > * AsVariableBool ()
virtual class TConsoleVariableData< float > * AsVariableFloat ()
virtual class TConsoleVariableData< int32 > * AsVariableInt ()
virtual class TConsoleVariableData< FString > * AsVariableString ()
void ClearFlags (const EConsoleVariableFlags Value)
Removes the specified flags in the internal state.
virtual FText GetDetailedHelp () const
virtual EConsoleVariableFlags GetFlags () const =0
Get the internal state of the flags.
virtual const TCHAR * GetHelp () const =0
virtual IConsoleObject * GetParentObject () const
If the object has a parent (for instance the main cvar that owns an other-platform cvar), return it.
virtual IConsoleObject * GetShadowedObject () const
If IsShadowObject() returns true, this function will return the "real" variable the shadow cvar is shadowing.
virtual bool IsDeprecated () const
bool IsEnabled () const
Test the validity of the variable wrt its flags and current build type (e.g.
virtual bool IsShadowObject () const
A shadow ConsoleObject is one that exists and can be used, but shouldn't be iterated over in anything that walks over every object and acts on it.
virtual bool IsVariableBool () const
virtual bool IsVariableFloat () const
virtual bool IsVariableInt () const
virtual bool IsVariableString () const
virtual void SetFlags (const EConsoleVariableFlags Value)=0
Sets the internal flag state to the specified value.
virtual void SetHelp (const TCHAR *Value)=0
bool TestFlags (const EConsoleVariableFlags Value) const
Test is any of the specified flags is set in the internal state.
Detailed Description
Interface for console variables.
Definition at line 553 of file IConsoleManager.h.
Member Function Documentation
GetBool()
virtual bool IConsoleVariable::GetBool () const pure virtual
Get the internal value as a bool, works on bools, ints and floats.
Referenced by GetValue().
GetDefaultValue()
virtual FString IConsoleVariable::GetDefaultValue () pure virtual
Get the value this CVar was constructed with.
GetFloat()
virtual float IConsoleVariable::GetFloat () const pure virtual
Get the internal value as float (works on all types).
Referenced by DEFINE_LOG_CATEGORY_STATIC(), and GetValue().
GetHistorySize()
virtual SIZE_T IConsoleVariable::GetHistorySize () pure virtual
Track memory used by history data.
GetInt()
virtual int32 IConsoleVariable::GetInt () const pure virtual
Get the internal value as int (should not be used on strings).
Returns
value is not rounded (simple cast)
Referenced by DEFINE_LOG_CATEGORY_STATIC(), GetValue(), and FSkeletalMeshStreamIn_IO::SetIORequest().
GetString()
virtual FString IConsoleVariable::GetString () const pure virtual
Get the internal value as string (works on all types).
Referenced by GetValue().
GetValue() [1/4]
void IConsoleVariable::GetValue (bool & OutBoolValue) const inline
Definition at line 591 of file IConsoleManager.h.
References GetBool().
GetValue() [2/4]
void IConsoleVariable::GetValue (float & OutFloatValue) const inline
Definition at line 595 of file IConsoleManager.h.
References GetFloat().
GetValue() [3/4]
void IConsoleVariable::GetValue (FString & OutStringValue) const inline
Definition at line 599 of file IConsoleManager.h.
References GetString().
GetValue() [4/4]
void IConsoleVariable::GetValue (int32 & OutIntValue) const inline
Generic versions for templated code.
Definition at line 587 of file IConsoleManager.h.
References GetInt().
LogHistory()
virtual void IConsoleVariable::LogHistory (FOutputDevice & Ar) pure virtual
Print the history to a log.
References Ar.
OnChangedDelegate()
virtual FConsoleVariableMulticastDelegate & IConsoleVariable::OnChangedDelegate () pure virtual
Set() [1/4]
void IConsoleVariable::Set (bool InValue, EConsoleVariableFlags SetBy = ECVF_SetByCode, FName Tag = NAME_None) inline
Set the internal value from the specified bool.
Definition at line 668 of file IConsoleManager.h.
References ECVF_SetByCode, Set(), SetBy, and TEXT.
Set() [2/4]
virtual void IConsoleVariable::Set (const TCHAR * InValue, EConsoleVariableFlags SetBy = ECVF_SetByCode, FName Tag = NAME_None) pure virtual
Set the internal value from the specified string.
Parameters
SetBy anything in ECVF_LastSetMask e.g. ECVF_SetByScalability
Tag optional Tag to set with the value - only useful when UE_ALLOW_CVAR_HISTORY is set, and when setting in an ARRAY type SetBy
References ECVF_SetByCode, and SetBy.
Referenced by Set(), Set(), Set(), SetWithCurrentPriority(), SetWithCurrentPriority(), SetWithCurrentPriority(), and SetWithCurrentPriority().
Set() [3/4]
void IConsoleVariable::Set (float InValue, EConsoleVariableFlags SetBy = ECVF_SetByCode, FName Tag = NAME_None) inline
Set the internal value from the specified float.
Definition at line 683 of file IConsoleManager.h.
References ECVF_SetByCode, Set(), SetBy, and TEXT.
Set() [4/4]
void IConsoleVariable::Set (int32 InValue, EConsoleVariableFlags SetBy = ECVF_SetByCode, FName Tag = NAME_None) inline
Set the internal value from the specified int.
Definition at line 677 of file IConsoleManager.h.
References ECVF_SetByCode, Set(), SetBy, and TEXT.
SetOnChangedCallback()
virtual void IConsoleVariable::SetOnChangedCallback (const FConsoleVariableDelegate & Callback) pure virtual
Allows to specify a callback function that is called when the console variable value changes.
Is even called if the value is the same as the value before. Will always be on the game thread. This can be dangerous (instead try to use RegisterConsoleVariableSink())
Setting other console variables in the delegate can cause infinite loops
Setting many console variables could result in wasteful cycles (e.g. if multiple console variables require to reattach all objects it would happen for each one)
The call can be at any time during initialization. As this cannot be specified during constructions you are not called on creation. We also don't call for the SetOnChangedCallback() call as this is up to the caller.
Referenced by FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariable::FAutoConsoleVariable(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), FAutoConsoleVariableRef::FAutoConsoleVariableRef(), and TAutoConsoleVariable< T >::TAutoConsoleVariable().
SetWithCurrentPriority() [1/4]
void IConsoleVariable::SetWithCurrentPriority (bool InValue, FName Tag = NAME_None) inline
Definition at line 689 of file IConsoleManager.h.
References ECVF_SetByMask, IConsoleObject::GetFlags(), and Set().
SetWithCurrentPriority() [2/4]
void IConsoleVariable::SetWithCurrentPriority (const TCHAR * InValue, FName Tag = NAME_None) inline
Definition at line 704 of file IConsoleManager.h.
References ECVF_SetByMask, IConsoleObject::GetFlags(), and Set().
SetWithCurrentPriority() [3/4]
void IConsoleVariable::SetWithCurrentPriority (float InValue, FName Tag = NAME_None) inline
Definition at line 699 of file IConsoleManager.h.
References ECVF_SetByMask, IConsoleObject::GetFlags(), and Set().
SetWithCurrentPriority() [4/4]
void IConsoleVariable::SetWithCurrentPriority (int32 InValue, FName Tag = NAME_None) inline
Definition at line 694 of file IConsoleManager.h.
References ECVF_SetByMask, IConsoleObject::GetFlags(), and Set().
UE_DEPRECATED()
IConsoleVariable::UE_DEPRECATED (5. 4, "Use GetDefaultValue() instead") inline
Get the saved off default value, in a cvar variable, if one was created.
Definition at line 621 of file IConsoleManager.h.
Unset()
virtual void IConsoleVariable::Unset (EConsoleVariableFlags SetBy, FName Tag = NAME_None) pure virtual
Unsets the value at a certain SetBy priority (this is only useful when UE_ALLOW_CVAR_HISTORY is set).
The value of the CVar will be recalculated based on remaining History levels
Parameters
SetBy anything in ECVF_LastSetMask e.g. ECVF_SetByScalability
Tag tag used to remove a setting from an ARRAY type SetBy
References SetBy.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h