Unreal Engine 5.6 C++ API: TMatrix2x2< T > Class Template Reference
TMatrix2x2< T > Class Template Reference
2x2 generalized matrix.
#include "TransformCalculus2D.h"
Public Types
using FReal = T
using Vector2Type = UE::Math::TVector2<T>
Public Member Functions
TMatrix2x2 ()
Ctor.
TMatrix2x2 (const TQuat2< T > &Rotation)
Ctor.
TMatrix2x2 (const TScale2< T > &Scale)
Ctor.
TMatrix2x2 (const TShear2< T > &Shear)
Factory function.
TMatrix2x2 (T m00, T m01, T m10, T m11)
TMatrix2x2 (T UniformScale)
Ctor.
TMatrix2x2 Concatenate (const TMatrix2x2 &RHS) const
Concatenate 2 matrices: [A B] * [E F] == [AE+BG AF+BH] [C D] [G H] [CE+DG CF+DH].
bool ContainsNaN () const
T Determinant () const
FORCEINLINE void DiagnosticCheckNaN () const
void GetMatrix (double &A, double &B, double &C, double &D) const
void GetMatrix (float &A, float &B, float &C, float &D) const
T GetRotationAngle () const
Gets the rotation angle of the matrix.
TScale2< T > GetScale () const
Gets the scale from the matrix.
TScale2< T > GetScaleSquared () const
Extracts the squared scale from the matrix (avoids sqrt).
TMatrix2x2 Inverse () const
Invert the transform.
T InverseDeterminant () const
bool IsIdentity () const
Determines if the matrix is identity or not.
bool IsNearlyIdentity (T ErrorTolerance=UE_KINDA_SMALL_NUMBER) const
bool operator!= (const TMatrix2x2 &Other) const
Inequality.
bool operator== (const TMatrix2x2 &RHS) const
Equality.
template<typename ArgType>
UE::Math::TVector2< ArgType > TransformPoint (const UE::Math::TVector2< ArgType > &Point) const
Transform a 2D point [X Y] * [m00 m01] [m10 m11].
template<typename ArgType>
UE::Math::TVector2< ArgType > TransformVector (const UE::Math::TVector2< ArgType > &Vector) const
Vector transformation is equivalent to point transformation as our matrix is not homogeneous.
Private Attributes
T M [2][2]
Detailed Description
template<typename T>
class TMatrix2x2< T >
2x2 generalized matrix.
As FMatrix, we assume row vectors, row major storage: [X Y] * [m00 m01] [m10 m11]
Definition at line 403 of file TransformCalculus2D.h.
Member Typedef Documentation
FReal
template<typename T> using TMatrix2x2< T >::FReal = T
Definition at line 408 of file TransformCalculus2D.h.
Vector2Type
template<typename T> using TMatrix2x2< T >::Vector2Type = UE::Math::TVector2<T>
Definition at line 409 of file TransformCalculus2D.h.
Constructor & Destructor Documentation
TMatrix2x2() [1/6]
template<typename T> TMatrix2x2< T >::TMatrix2x2 () inline
Ctor.
initialize to an identity.
Definition at line 412 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::Concatenate(), and TMatrix2x2< float >::Inverse().
TMatrix2x2() [2/6]
template<typename T> TMatrix2x2< T >::TMatrix2x2 (T m00, T m01, T m10, T m11) inline
Definition at line 418 of file TransformCalculus2D.h.
TMatrix2x2() [3/6]
template<typename T> TMatrix2x2< T >::TMatrix2x2 (T UniformScale) inline explicit
Ctor.
initialize from a scale.
Definition at line 427 of file TransformCalculus2D.h.
TMatrix2x2() [4/6]
template<typename T> TMatrix2x2< T >::TMatrix2x2 (const TScale2< T > & Scale) inline explicit
Ctor.
initialize from a scale.
Definition at line 435 of file TransformCalculus2D.h.
TMatrix2x2() [5/6]
template<typename T> TMatrix2x2< T >::TMatrix2x2 (const TShear2< T > & Shear) inline explicit
Factory function.
initialize from a 2D shear.
Definition at line 445 of file TransformCalculus2D.h.
TMatrix2x2() [6/6]
template<typename T> TMatrix2x2< T >::TMatrix2x2 (const TQuat2< T > & Rotation) inline explicit
Ctor.
initialize from a rotation.
Definition at line 455 of file TransformCalculus2D.h.
Member Function Documentation
Concatenate()
template<typename T> TMatrix2x2 TMatrix2x2< T >::Concatenate (const TMatrix2x2< T > & RHS) const inline
Concatenate 2 matrices: [A B] * [E F] == [AE+BG AF+BH] [C D] [G H] [CE+DG CF+DH].
Definition at line 489 of file TransformCalculus2D.h.
ContainsNaN()
template<typename T> bool TMatrix2x2< T >::ContainsNaN () const inline
Definition at line 601 of file TransformCalculus2D.h.
Determinant()
template<typename T> T TMatrix2x2< T >::Determinant () const inline
Definition at line 548 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::InverseDeterminant().
DiagnosticCheckNaN()
template<typename T> FORCEINLINE void TMatrix2x2< T >::DiagnosticCheckNaN () const inline
Definition at line 619 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::TMatrix2x2(), TMatrix2x2< float >::TMatrix2x2(), TMatrix2x2< float >::TMatrix2x2(), TMatrix2x2< float >::TMatrix2x2(), and TMatrix2x2< float >::TMatrix2x2().
GetMatrix() [1/2]
template<typename T> void TMatrix2x2< T >::GetMatrix (double & A, double & B, double & C, double & D) const inline
Definition at line 542 of file TransformCalculus2D.h.
GetMatrix() [2/2]
template<typename T> void TMatrix2x2< T >::GetMatrix (float & A, float & B, float & C, float & D) const inline
Definition at line 536 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::Concatenate(), TMatrix2x2< float >::Determinant(), TMatrix2x2< float >::GetRotationAngle(), TMatrix2x2< float >::GetScaleSquared(), TMatrix2x2< float >::Inverse(), TMatrix2x2< float >::operator==(), FCurveEditorScreenSpaceH::ToCurveSpace(), and FCurveEditorScreenSpaceV::ToCurveSpace().
GetRotationAngle()
template<typename T> T TMatrix2x2< T >::GetRotationAngle () const inline
Gets the rotation angle of the matrix.
Definition at line 578 of file TransformCalculus2D.h.
GetScale()
template<typename T> TScale2< T > TMatrix2x2< T >::GetScale () const inline
Gets the scale from the matrix.
Definition at line 571 of file TransformCalculus2D.h.
GetScaleSquared()
template<typename T> TScale2< T > TMatrix2x2< T >::GetScaleSquared () const inline
Extracts the squared scale from the matrix (avoids sqrt).
Definition at line 563 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::GetScale().
Inverse()
template<typename T> TMatrix2x2 TMatrix2x2< T >::Inverse () const inline
Invert the transform.
Definition at line 504 of file TransformCalculus2D.h.
InverseDeterminant()
template<typename T> T TMatrix2x2< T >::InverseDeterminant () const inline
Definition at line 555 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::Inverse().
IsIdentity()
template<typename T> bool TMatrix2x2< T >::IsIdentity () const inline
Determines if the matrix is identity or not.
Uses exact float comparison, so rounding error is not considered.
Definition at line 586 of file TransformCalculus2D.h.
IsNearlyIdentity()
template<typename T> bool TMatrix2x2< T >::IsNearlyIdentity (T ErrorTolerance = UE_KINDA_SMALL_NUMBER) const inline
Definition at line 592 of file TransformCalculus2D.h.
operator!=()
template<typename T> bool TMatrix2x2< T >::operator!= (const TMatrix2x2< T > & Other) const inline
Inequality.
Definition at line 531 of file TransformCalculus2D.h.
operator==()
template<typename T> bool TMatrix2x2< T >::operator== (const TMatrix2x2< T > & RHS) const inline
Equality.
Definition at line 517 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::operator!=().
TransformPoint()
template<typename T> template<typename ArgType> UE::Math::TVector2< ArgType > TMatrix2x2< T >::TransformPoint (const UE::Math::TVector2< ArgType > & Point) const inline
Transform a 2D point [X Y] * [m00 m01] [m10 m11].
Definition at line 470 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::TransformVector().
TransformVector()
template<typename T> template<typename ArgType> UE::Math::TVector2< ArgType > TMatrix2x2< T >::TransformVector (const UE::Math::TVector2< ArgType > & Vector) const inline
Vector transformation is equivalent to point transformation as our matrix is not homogeneous.
Definition at line 480 of file TransformCalculus2D.h.
Field Documentation
M
template<typename T> T TMatrix2x2< T >::M[2][2] private
Definition at line 623 of file TransformCalculus2D.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/TransformCalculus2D.h