Unreal Engine 5.6 C++ API: FTriangleRasterizer< RasterPolicyType > Class Template Reference
FTriangleRasterizer< RasterPolicyType > Class Template Reference
#include "Raster.h"
Public Types
typedef RasterPolicyType::InterpolantType InterpolantType
Public Member Functions
FTriangleRasterizer (const RasterPolicyType &InRasterPolicy)
void DrawTriangle (const InterpolantType &I0, const InterpolantType &I1, const InterpolantType &I2, const FVector2D &P0, const FVector2D &P1, const FVector2D &P2, bool BackFacing)
Private Member Functions
void DrawTriangleTrapezoid (const InterpolantType &TopMinInterpolant, const InterpolantType &DeltaMinInterpolant, const InterpolantType &TopMaxInterpolant, const InterpolantType &DeltaMaxInterpolant, float TopMinX, float DeltaMinX, float TopMaxX, float DeltaMaxX, float InMinY, float InMaxY, bool BackFacing)
Detailed Description
template<class RasterPolicyType>
class FTriangleRasterizer< RasterPolicyType >
Definition at line 15 of file Raster.h.
Member Typedef Documentation
InterpolantType
template<class RasterPolicyType> typedef RasterPolicyType::InterpolantType FTriangleRasterizer< RasterPolicyType >::InterpolantType
Definition at line 19 of file Raster.h.
Constructor & Destructor Documentation
FTriangleRasterizer()
template<class RasterPolicyType> FTriangleRasterizer< RasterPolicyType >::FTriangleRasterizer (const RasterPolicyType & InRasterPolicy) inline
Definition at line 105 of file Raster.h.
Member Function Documentation
DrawTriangle()
template<class RasterPolicyType> void FTriangleRasterizer< RasterPolicyType >::DrawTriangle (const InterpolantType & I0, const InterpolantType & I1, const InterpolantType & I2, const FVector2D & P0, const FVector2D & P1, const FVector2D & P2, bool BackFacing) inline
Definition at line 21 of file Raster.h.
References DrawTriangleTrapezoid(), Exchange(), FMath::IsNearlyZero(), Points, UE_SMALL_NUMBER, X, and Y.
DrawTriangleTrapezoid()
template<class RasterPolicyType> void FTriangleRasterizer< RasterPolicyType >::DrawTriangleTrapezoid (const InterpolantType & TopMinInterpolant, const InterpolantType & DeltaMinInterpolant, const InterpolantType & TopMaxInterpolant, const InterpolantType & DeltaMaxInterpolant, float TopMinX, float DeltaMinX, float TopMaxX, float DeltaMaxX, float InMinY, float InMaxY, bool BackFacing) inline private
Definition at line 109 of file Raster.h.
References FMath::Clamp(), Exchange(), X, and Y.
Referenced by DrawTriangle().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Raster.h