Unreal Engine 5.6 C++ API: FShaderPipelineTypeDependency Class Reference
FShaderPipelineTypeDependency Class Reference
#include "Shader.h"
Public Member Functions
FShaderPipelineTypeDependency ()
FShaderPipelineTypeDependency (const FShaderPipelineType *InShaderPipelineType, EShaderPlatform ShaderPlatform)
bool operator!= (const FShaderPipelineTypeDependency &Reference) const
bool operator== (const FShaderPipelineTypeDependency &Reference) const
RENDERCORE_API void RefreshCachedSourceHash (EShaderPlatform ShaderPlatform)
Call GetShaderFileHash to get the cached value for the filename's hash in the current process.
Data Fields
FHashedName ShaderPipelineTypeName
Shader Pipeline type.
FSHAHash StagesSourceHash
Used to detect changes to the shader source files.
Private Member Functions
RENDERCORE_API void Save (FCbWriter &Writer) const
bool TryLoad (FCbFieldView Field)
Friends
RENDERCORE_API bool LoadFromCompactBinary (FCbFieldView Field, FShaderPipelineTypeDependency &OutValue)
FArchive & operator<< (FArchive &Ar, class FShaderPipelineTypeDependency &Ref)
FCbWriter & operator<< (FCbWriter &Writer, const FShaderPipelineTypeDependency &Value)
Detailed Description
Definition at line 2140 of file Shader.h.
Constructor & Destructor Documentation
FShaderPipelineTypeDependency() [1/2]
FShaderPipelineTypeDependency::FShaderPipelineTypeDependency () inline
Definition at line 2143 of file Shader.h.
Referenced by LoadFromCompactBinary, operator!=(), operator<<, operator<<, and operator==().
FShaderPipelineTypeDependency() [2/2]
FShaderPipelineTypeDependency::FShaderPipelineTypeDependency (const FShaderPipelineType * InShaderPipelineType, EShaderPlatform ShaderPlatform) inline
Definition at line 2144 of file Shader.h.
References FShaderPipelineType::GetSourceHash(), ShaderPipelineTypeName, ShaderPlatform, and StagesSourceHash.
Member Function Documentation
operator!=()
bool FShaderPipelineTypeDependency::operator!= (const FShaderPipelineTypeDependency & Reference) const inline
Definition at line 2171 of file Shader.h.
References FShaderPipelineTypeDependency().
operator==()
bool FShaderPipelineTypeDependency::operator== (const FShaderPipelineTypeDependency & Reference) const inline
Definition at line 2166 of file Shader.h.
References FShaderPipelineTypeDependency(), ShaderPipelineTypeName, and StagesSourceHash.
RefreshCachedSourceHash()
RENDERCORE_API void FShaderPipelineTypeDependency::RefreshCachedSourceHash (EShaderPlatform ShaderPlatform)
Call GetShaderFileHash to get the cached value for the filename's hash in the current process.
References ShaderPlatform.
Save()
RENDERCORE_API void FShaderPipelineTypeDependency::Save (FCbWriter & Writer) const private
TryLoad()
bool FShaderPipelineTypeDependency::TryLoad (FCbFieldView Field) private
Friends And Related Symbol Documentation
LoadFromCompactBinary
RENDERCORE_API bool LoadFromCompactBinary (FCbFieldView Field, FShaderPipelineTypeDependency & OutValue) friend
References FShaderPipelineTypeDependency().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, class FShaderPipelineTypeDependency & Ref) friend
Definition at line 2159 of file Shader.h.
References FShaderPipelineTypeDependency(), and Ar.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FShaderPipelineTypeDependency & Value) friend
Definition at line 2184 of file Shader.h.
References FShaderPipelineTypeDependency(), and Value.
Field Documentation
ShaderPipelineTypeName
FHashedName FShaderPipelineTypeDependency::ShaderPipelineTypeName
Shader Pipeline type.
Definition at line 2154 of file Shader.h.
Referenced by FShaderPipelineTypeDependency(), and operator==().
StagesSourceHash
FSHAHash FShaderPipelineTypeDependency::StagesSourceHash
Used to detect changes to the shader source files.
Definition at line 2157 of file Shader.h.
Referenced by FShaderPipelineTypeDependency(), and operator==().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h