Unreal Engine 5.6 C++ API: FRDGAllocator Class Reference
FRDGAllocator Class Reference
#include "RenderGraphAllocator.h"
Data Structures
class FObject
class TObject
Public Member Functions
FRDGAllocator ()
FRDGAllocator (FRDGAllocator &&)
~FRDGAllocator ()
template<typename T, typename... TArgs>
FORCEINLINE T * Alloc (TArgs &&... Args)
Allocates and constructs an object and tracks it for destruction.
FORCEINLINE void * Alloc (uint64 SizeInBytes, uint32 AlignInBytes)
Allocates raw memory.
template<typename T, typename... TArgs>
FORCEINLINE T * AllocNoDestruct (TArgs &&... Args)
Allocates a C++ object with no destructor tracking (dangerous!).
template<typename PODType>
FORCEINLINE PODType * AllocUninitialized (uint64 Count=1)
Allocates an uninitialized type without destructor tracking.
FORCEINLINE int32 GetByteCount () const
FRDGAllocator & operator= (FRDGAllocator &&)
void ReleaseAll ()
Static Public Member Functions
static RENDERCORE_API FRDGAllocator & GetTLS ()
Private Attributes
FMemStackBase MemStack
TArray< FObject * > Objects
Static Private Attributes
static uint32 AllocatorTLSSlot
Friends
class FRDGAllocatorScope
Detailed Description
Definition at line 23 of file RenderGraphAllocator.h.
Constructor & Destructor Documentation
FRDGAllocator() [1/2]
FRDGAllocator::FRDGAllocator ()
Referenced by FRDGAllocator(), GetTLS(), and operator=().
FRDGAllocator() [2/2]
FRDGAllocator::FRDGAllocator (FRDGAllocator &&)
References FRDGAllocator().
~FRDGAllocator()
FRDGAllocator::~FRDGAllocator ()
Member Function Documentation
Alloc() [1/2]
template<typename T, typename... TArgs> FORCEINLINE T * FRDGAllocator::Alloc (TArgs &&... Args) inline
Allocates and constructs an object and tracks it for destruction.
Definition at line 85 of file RenderGraphAllocator.h.
References check, FORCEINLINE, Forward(), MemStack, Object, and Objects.
Alloc() [2/2]
FORCEINLINE void * FRDGAllocator::Alloc (uint64 SizeInBytes, uint32 AlignInBytes) inline
Allocates raw memory.
Definition at line 53 of file RenderGraphAllocator.h.
References FORCEINLINE, Memory, and MemStack.
Referenced by AllocUninitialized().
AllocNoDestruct()
template<typename T, typename... TArgs> FORCEINLINE T * FRDGAllocator::AllocNoDestruct (TArgs &&... Args) inline
Allocates a C++ object with no destructor tracking (dangerous!).
Definition at line 108 of file RenderGraphAllocator.h.
References AllocUninitialized(), FORCEINLINE, and Forward().
AllocUninitialized()
template<typename PODType> FORCEINLINE PODType * FRDGAllocator::AllocUninitialized (uint64 Count = 1) inline
Allocates an uninitialized type without destructor tracking.
Definition at line 78 of file RenderGraphAllocator.h.
References Alloc(), Count, and FORCEINLINE.
Referenced by AllocNoDestruct().
GetByteCount()
FORCEINLINE int32 FRDGAllocator::GetByteCount () const inline
Definition at line 113 of file RenderGraphAllocator.h.
References FORCEINLINE, and MemStack.
GetTLS()
RENDERCORE_API FRDGAllocator & FRDGAllocator::GetTLS () static
References FRDGAllocator().
Referenced by TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation().
operator=()
FRDGAllocator & FRDGAllocator::operator= (FRDGAllocator &&)
References FRDGAllocator().
ReleaseAll()
void FRDGAllocator::ReleaseAll ()
Friends And Related Symbol Documentation
FRDGAllocatorScope
friend class FRDGAllocatorScope friend
Definition at line 141 of file RenderGraphAllocator.h.
References FRDGAllocatorScope.
Referenced by FRDGAllocatorScope.
Field Documentation
AllocatorTLSSlot
uint32 FRDGAllocator::AllocatorTLSSlot static private
Definition at line 142 of file RenderGraphAllocator.h.
MemStack
FMemStackBase FRDGAllocator::MemStack private
Definition at line 129 of file RenderGraphAllocator.h.
Referenced by Alloc(), Alloc(), and GetByteCount().
Objects
TArray<FObject*> FRDGAllocator::Objects private
Definition at line 131 of file RenderGraphAllocator.h.
Referenced by Alloc().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphAllocator.h