Unreal Engine 5.6 C++ API: UE::FExternalMutex Class Reference
UE::FExternalMutex Class Reference final
A mutex which takes it state from an external source and uses only its 2 LSBs.
#include "ExternalMutex.h"
Public Member Functions
FExternalMutex (const FExternalMutex &)=delete
constexpr FExternalMutex (std::atomic< uint8 > &InState)
FExternalMutex (std::atomic< uint8 > &InState, FAcquireLock)
Construct in a locked state.
bool IsLocked () const
void Lock ()
FExternalMutex & operator= (const FExternalMutex &)=delete
bool TryLock ()
void Unlock ()
Private Member Functions
void LockSlow ()
void WakeWaitingThread ()
Private Attributes
std::atomic< uint8 > & State
Static Private Attributes
static constexpr bool bUnlockImmediately = true
static constexpr uint8 IsLockedFlag = 1 << 0
static constexpr uint8 MayHaveWaitingLockFlag = 1 << 1
Detailed Description
A mutex which takes it state from an external source and uses only its 2 LSBs.
The external source must ensure that the state is valid for the lifetime of the mutex.
Note: Changes to this class should also be ported to FMutex. These classes could be merged via templatization but we would want to make sure this doesn't cause any undesired code-bloat / side effects.
Definition at line 22 of file ExternalMutex.h.
Constructor & Destructor Documentation
FExternalMutex() [1/3]
UE::FExternalMutex::FExternalMutex (std::atomic< uint8 > & InState) inline explicit constexpr
Definition at line 25 of file ExternalMutex.h.
References State.
Referenced by FExternalMutex(), and operator=().
FExternalMutex() [2/3]
UE::FExternalMutex::FExternalMutex (std::atomic< uint8 > & InState, FAcquireLock) inline explicit
Construct in a locked state.
Avoids an expensive compare-and-swap at creation time.
Definition at line 31 of file ExternalMutex.h.
References IsLockedFlag, and State.
FExternalMutex() [3/3]
UE::FExternalMutex::FExternalMutex (const FExternalMutex &) delete
References FExternalMutex().
Member Function Documentation
IsLocked()
bool UE::FExternalMutex::IsLocked () const inline
Definition at line 40 of file ExternalMutex.h.
References IsLockedFlag, and State.
Lock()
void UE::FExternalMutex::Lock () inline
Definition at line 52 of file ExternalMutex.h.
References IsLockedFlag, LIKELY, LockSlow(), MayHaveWaitingLockFlag, and State.
LockSlow()
void UE::FExternalMutex::LockSlow () private
References UE_API.
Referenced by Lock().
operator=()
FExternalMutex & UE::FExternalMutex::operator= (const FExternalMutex &) delete
References FExternalMutex().
TryLock()
bool UE::FExternalMutex::TryLock () inline
Definition at line 45 of file ExternalMutex.h.
References IsLockedFlag, and State.
Unlock()
void UE::FExternalMutex::Unlock () inline
Definition at line 62 of file ExternalMutex.h.
References bUnlockImmediately, IsLockedFlag, LIKELY, MayHaveWaitingLockFlag, State, and WakeWaitingThread().
WakeWaitingThread()
void UE::FExternalMutex::WakeWaitingThread () private
References UE_API.
Referenced by Unlock().
Field Documentation
bUnlockImmediately
bool UE::FExternalMutex::bUnlockImmediately = true static constexpr private
Definition at line 92 of file ExternalMutex.h.
Referenced by Unlock().
IsLockedFlag
uint8 UE::FExternalMutex::IsLockedFlag = 1 << 0 static constexpr private
Definition at line 89 of file ExternalMutex.h.
Referenced by FExternalMutex(), IsLocked(), Lock(), TryLock(), and Unlock().
MayHaveWaitingLockFlag
uint8 UE::FExternalMutex::MayHaveWaitingLockFlag = 1 << 1 static constexpr private
Definition at line 90 of file ExternalMutex.h.
Referenced by Lock(), and Unlock().
State
std::atomic<uint8>& UE::FExternalMutex::State private
Definition at line 94 of file ExternalMutex.h.
Referenced by FExternalMutex(), FExternalMutex(), IsLocked(), Lock(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/ExternalMutex.h