Unreal Engine 5.6 C++ API: IPixelStreaming2StreamerFactory Class Reference
IPixelStreaming2StreamerFactory Class Reference abstract
The IPixelStreaming2StreamerFactory interface provides functionality for creating custom streamers based on an identifier.
#include "IPixelStreaming2Streamer.h"
Public Member Functions
IPixelStreaming2StreamerFactory ()
virtual ~IPixelStreaming2StreamerFactory ()
virtual FString GetStreamType ()=0
Static Public Member Functions
static IPixelStreaming2StreamerFactory * Get (const FString &InType)
static TArray< FString > GetAvailableFactoryTypes ()
static void RegisterStreamerFactory (IPixelStreaming2StreamerFactory *InFactory)
static void UnregisterStreamerFactory (IPixelStreaming2StreamerFactory *InFactory)
Private Member Functions
virtual TSharedPtr< IPixelStreaming2Streamer > CreateNewStreamer (const FString &StreamerId)=0
Detailed Description
The IPixelStreaming2StreamerFactory interface provides functionality for creating custom streamers based on an identifier.
Definition at line 274 of file IPixelStreaming2Streamer.h.
Constructor & Destructor Documentation
IPixelStreaming2StreamerFactory()
IPixelStreaming2StreamerFactory::IPixelStreaming2StreamerFactory ()
Referenced by Get(), RegisterStreamerFactory(), and UnregisterStreamerFactory().
~IPixelStreaming2StreamerFactory()
virtual IPixelStreaming2StreamerFactory::~IPixelStreaming2StreamerFactory () virtual
Member Function Documentation
CreateNewStreamer()
virtual TSharedPtr< IPixelStreaming2Streamer > IPixelStreaming2StreamerFactory::CreateNewStreamer (const FString & StreamerId) private pure virtual
Get()
IPixelStreaming2StreamerFactory * IPixelStreaming2StreamerFactory::Get (const FString & InType) static
References IPixelStreaming2StreamerFactory().
GetAvailableFactoryTypes()
TArray< FString > IPixelStreaming2StreamerFactory::GetAvailableFactoryTypes () static
GetStreamType()
virtual FString IPixelStreaming2StreamerFactory::GetStreamType () pure virtual
RegisterStreamerFactory()
void IPixelStreaming2StreamerFactory::RegisterStreamerFactory (IPixelStreaming2StreamerFactory * InFactory) static
References IPixelStreaming2StreamerFactory().
UnregisterStreamerFactory()
void IPixelStreaming2StreamerFactory::UnregisterStreamerFactory (IPixelStreaming2StreamerFactory * InFactory) static
References IPixelStreaming2StreamerFactory().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2Core/Public/IPixelStreaming2Streamer.h