Unreal Engine 5.6 C++ API: FGlobalShaderMap Class Reference
FGlobalShaderMap Class Reference
#include "GlobalShader.h"
Public Member Functions
RENDERCORE_API FGlobalShaderMap (EShaderPlatform InPlatform)
RENDERCORE_API ~FGlobalShaderMap ()
RENDERCORE_API void AddSection (FGlobalShaderMapSection *InSection)
RENDERCORE_API void BeginCreateAllShaders ()
RENDERCORE_API void Empty ()
RENDERCORE_API FGlobalShaderMapSection * FindOrAddSection (const FShaderType *ShaderType)
RENDERCORE_API FShader * FindOrAddShader (const FShaderType *ShaderType, int32 PermutationId, FShader *Shader)
RENDERCORE_API FShaderPipeline * FindOrAddShaderPipeline (const FShaderPipelineType *ShaderPipelineType, FShaderPipeline *ShaderPipeline)
RENDERCORE_API FGlobalShaderMapSection * FindSection (const FHashedName &HashedShaderFilename)
const FGlobalShaderMapSection * GetFirstSection ()
RENDERCORE_API void GetOutdatedTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
template<typename ShaderType>
TShaderRef< ShaderType > GetShader () const
template<typename ShaderType>
TShaderRef< ShaderType > GetShader (const typename ShaderType::FPermutationDomain &PermutationVector) const
Finds the shader with the given type.
RENDERCORE_API TShaderRef< FShader > GetShader (FShaderType *ShaderType, int32 PermutationId=0) const
template<typename ShaderType>
TShaderRef< ShaderType > GetShader (int32 PermutationId) const
RENDERCORE_API FShaderPipelineRef GetShaderPipeline (const FShaderPipelineType *PipelineType) const
bool HasShader (FShaderType *Type, int32 PermutationId) const
bool HasShaderPipeline (const FShaderPipelineType *ShaderPipelineType) const
RENDERCORE_API bool IsComplete (const ITargetPlatform *TargetPlatform) const
Whether the shadermap has all the shader types it needs (i.e.
RENDERCORE_API bool IsEmpty () const
RENDERCORE_API void LoadFromGlobalArchive (FArchive &Ar)
RENDERCORE_API void ReleaseAllSections ()
RENDERCORE_API void RemoveShaderPipelineType (const FShaderPipelineType *ShaderPipelineType)
RENDERCORE_API void RemoveShaderTypePermutaion (const FShaderType *Type, int32 PermutationId)
RENDERCORE_API void SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform)
RENDERCORE_API void SaveToGlobalArchive (FArchive &Ar)
Private Attributes
EShaderPlatform Platform
TMap< FHashedName, FGlobalShaderMapSection * > SectionMap
Detailed Description
Definition at line 178 of file GlobalShader.h.
Constructor & Destructor Documentation
FGlobalShaderMap()
RENDERCORE_API FGlobalShaderMap::FGlobalShaderMap (EShaderPlatform InPlatform) explicit
~FGlobalShaderMap()
RENDERCORE_API FGlobalShaderMap::~FGlobalShaderMap ()
Member Function Documentation
AddSection()
RENDERCORE_API void FGlobalShaderMap::AddSection (FGlobalShaderMapSection * InSection)
BeginCreateAllShaders()
RENDERCORE_API void FGlobalShaderMap::BeginCreateAllShaders ()
Empty()
RENDERCORE_API void FGlobalShaderMap::Empty ()
FindOrAddSection()
RENDERCORE_API FGlobalShaderMapSection * FGlobalShaderMap::FindOrAddSection (const FShaderType * ShaderType)
FindOrAddShader()
RENDERCORE_API FShader * FGlobalShaderMap::FindOrAddShader (const FShaderType * ShaderType, int32 PermutationId, FShader * Shader)
FindOrAddShaderPipeline()
RENDERCORE_API FShaderPipeline * FGlobalShaderMap::FindOrAddShaderPipeline (const FShaderPipelineType * ShaderPipelineType, FShaderPipeline * ShaderPipeline)
FindSection()
RENDERCORE_API FGlobalShaderMapSection * FGlobalShaderMap::FindSection (const FHashedName & HashedShaderFilename)
GetFirstSection()
const FGlobalShaderMapSection * FGlobalShaderMap::GetFirstSection () inline
Definition at line 252 of file GlobalShader.h.
References SectionMap.
GetOutdatedTypes()
RENDERCORE_API void FGlobalShaderMap::GetOutdatedTypes (TArray< const FShaderType * > & OutdatedShaderTypes, TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > & OutdatedFactoryTypes) const
GetShader() [1/4]
template<typename ShaderType> TShaderRef< ShaderType > FGlobalShaderMap::GetShader () const inline
Definition at line 188 of file GlobalShader.h.
References ensureMsgf, GetShader(), and TEXT.
Referenced by GetShader(), GetShader(), GetShader(), and HasShader().
GetShader() [2/4]
template<typename ShaderType> TShaderRef< ShaderType > FGlobalShaderMap::GetShader (const typename ShaderType::FPermutationDomain & PermutationVector) const inline
Finds the shader with the given type.
Asserts on failure.
Definition at line 209 of file GlobalShader.h.
References GetShader().
GetShader() [3/4]
RENDERCORE_API TShaderRef< FShader > FGlobalShaderMap::GetShader (FShaderType * ShaderType, int32 PermutationId = 0) const
Referenced by FPixelShaderUtils::AddRasterizeToRectsPass(), FCopyTextureCS::SelectShader(), and FUpdateTexture2DSubresourceCS::SelectShader().
GetShader() [4/4]
template<typename ShaderType> TShaderRef< ShaderType > FGlobalShaderMap::GetShader (int32 PermutationId) const inline
Definition at line 195 of file GlobalShader.h.
References TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), checkf, ensureMsgf, GetShader(), TShaderRefBase< ShaderType, PointerTableType >::IsValid(), NotUsed, Platform, TEXT, and ToString().
GetShaderPipeline()
RENDERCORE_API FShaderPipelineRef FGlobalShaderMap::GetShaderPipeline (const FShaderPipelineType * PipelineType) const
Referenced by HasShaderPipeline().
HasShader()
bool FGlobalShaderMap::HasShader (FShaderType * Type, int32 PermutationId) const inline
Definition at line 214 of file GlobalShader.h.
References GetShader().
HasShaderPipeline()
bool FGlobalShaderMap::HasShaderPipeline (const FShaderPipelineType * ShaderPipelineType) const inline
Definition at line 219 of file GlobalShader.h.
References GetShaderPipeline(), and FShaderPipelineRef::IsValid().
IsComplete()
RENDERCORE_API bool FGlobalShaderMap::IsComplete (const ITargetPlatform * TargetPlatform) const
Whether the shadermap has all the shader types it needs (i.e.
ones that returned ShouldCompilePermutation)
IsEmpty()
RENDERCORE_API bool FGlobalShaderMap::IsEmpty () const
LoadFromGlobalArchive()
RENDERCORE_API void FGlobalShaderMap::LoadFromGlobalArchive (FArchive & Ar)
References Ar.
ReleaseAllSections()
RENDERCORE_API void FGlobalShaderMap::ReleaseAllSections ()
RemoveShaderPipelineType()
RENDERCORE_API void FGlobalShaderMap::RemoveShaderPipelineType (const FShaderPipelineType * ShaderPipelineType)
RemoveShaderTypePermutaion()
RENDERCORE_API void FGlobalShaderMap::RemoveShaderTypePermutaion (const FShaderType * Type, int32 PermutationId)
SaveShaderStableKeys()
RENDERCORE_API void FGlobalShaderMap::SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform)
SaveToGlobalArchive()
RENDERCORE_API void FGlobalShaderMap::SaveToGlobalArchive (FArchive & Ar)
References Ar.
Field Documentation
Platform
EShaderPlatform FGlobalShaderMap::Platform private
Definition at line 263 of file GlobalShader.h.
Referenced by GetShader().
SectionMap
TMap<FHashedName, FGlobalShaderMapSection*> FGlobalShaderMap::SectionMap private
Definition at line 262 of file GlobalShader.h.
Referenced by GetFirstSection().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/GlobalShader.h