Unreal Engine 5.6 C++ API: Metasound::Frontend::FVertexAnalyzerBase Class Reference
Metasound::Frontend::FVertexAnalyzerBase Class Reference
#include "MetasoundFrontendVertexAnalyzer.h"
Public Member Functions
FVertexAnalyzerBase (const FAnalyzerAddress &InAnalyzerAddress, const FAnyDataReference &InDataReference)
virtual ~FVertexAnalyzerBase ()=default
virtual const FAnalyzerAddress & GetAnalyzerAddress () const override
virtual FDataReferenceID GetDataReferenceId () const override final
virtual void SetDataReference (const FAnyDataReference &NewDataRef) override final
Public Member Functions inherited from Metasound::Frontend::IVertexAnalyzer
virtual ~IVertexAnalyzer ()=default
DECLARE_DELEGATE_TwoParams (FOnOutputDataChanged, FName, TSharedPtr< IOutputStorage >)
virtual void Execute ()=0
Protected Types
using FBoundOutputDataPtr = TSharedPtr<IBoundAnalyzerOutput>
Protected Member Functions
template<typename DataType>
void BindOutputData (FName InAnalyzerOutputName, const FOperatorSettings &InOperatorSettings, TDataReadReference< DataType > InData)
template<typename DataType>
const DataType & GetVertexData () const
void MarkOutputDirty ()
bool UnbindOutputData (FName InAnalyzerOutputName)
Private Attributes
FAnalyzerAddress AnalyzerAddress
TMap< FName, FBoundOutputDataPtr > BoundOutputData
FAnyDataReference VertexDataReference
Additional Inherited Members
Data Fields inherited from Metasound::Frontend::IVertexAnalyzer
FOnOutputDataChanged OnOutputDataChanged
Detailed Description
Definition at line 134 of file MetasoundFrontendVertexAnalyzer.h.
Member Typedef Documentation
FBoundOutputDataPtr
using Metasound::Frontend::FVertexAnalyzerBase::FBoundOutputDataPtr = TSharedPtr<IBoundAnalyzerOutput> protected
Definition at line 161 of file MetasoundFrontendVertexAnalyzer.h.
Constructor & Destructor Documentation
FVertexAnalyzerBase()
Metasound::Frontend::FVertexAnalyzerBase::FVertexAnalyzerBase (const FAnalyzerAddress & InAnalyzerAddress, const FAnyDataReference & InDataReference) inline
Definition at line 137 of file MetasoundFrontendVertexAnalyzer.h.
References AnalyzerAddress, and VertexDataReference.
Referenced by Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::TVertexAnalyzerForwardValue().
~FVertexAnalyzerBase()
virtual Metasound::Frontend::FVertexAnalyzerBase::~FVertexAnalyzerBase () virtual default
Member Function Documentation
BindOutputData()
template<typename DataType> void Metasound::Frontend::FVertexAnalyzerBase::BindOutputData (FName InAnalyzerOutputName, const FOperatorSettings & InOperatorSettings, TDataReadReference< DataType > InData) inline protected
Definition at line 186 of file MetasoundFrontendVertexAnalyzer.h.
References AnalyzerAddress, Metasound::Frontend::FAnalyzerAddress::AnalyzerMemberName, BoundOutputData, Metasound::Frontend::FAnalyzerAddress::DataType, Metasound::GetMetasoundDataTypeName(), and MoveTemp().
Referenced by Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::TVertexAnalyzerForwardValue().
GetAnalyzerAddress()
virtual const FAnalyzerAddress & Metasound::Frontend::FVertexAnalyzerBase::GetAnalyzerAddress () const inline override virtual
Implements Metasound::Frontend::IVertexAnalyzer.
Definition at line 145 of file MetasoundFrontendVertexAnalyzer.h.
References AnalyzerAddress.
GetDataReferenceId()
virtual FDataReferenceID Metasound::Frontend::FVertexAnalyzerBase::GetDataReferenceId () const inline final override virtual
Implements Metasound::Frontend::IVertexAnalyzer.
Definition at line 150 of file MetasoundFrontendVertexAnalyzer.h.
References Metasound::GetDataReferenceID(), and VertexDataReference.
GetVertexData()
template<typename DataType> const DataType & Metasound::Frontend::FVertexAnalyzerBase::GetVertexData () const inline protected
Definition at line 197 of file MetasoundFrontendVertexAnalyzer.h.
References VertexDataReference.
Referenced by Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::Execute().
MarkOutputDirty()
void Metasound::Frontend::FVertexAnalyzerBase::MarkOutputDirty () inline protected
Definition at line 166 of file MetasoundFrontendVertexAnalyzer.h.
References BoundOutputData, and Metasound::Frontend::IVertexAnalyzer::OnOutputDataChanged.
Referenced by Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::UpdateValue().
SetDataReference()
virtual void Metasound::Frontend::FVertexAnalyzerBase::SetDataReference (const FAnyDataReference & NewDataRef) inline final override virtual
Implements Metasound::Frontend::IVertexAnalyzer.
Definition at line 155 of file MetasoundFrontendVertexAnalyzer.h.
References VertexDataReference.
UnbindOutputData()
bool Metasound::Frontend::FVertexAnalyzerBase::UnbindOutputData (FName InAnalyzerOutputName) inline protected
Definition at line 179 of file MetasoundFrontendVertexAnalyzer.h.
References BoundOutputData.
Field Documentation
AnalyzerAddress
FAnalyzerAddress Metasound::Frontend::FVertexAnalyzerBase::AnalyzerAddress private
Definition at line 203 of file MetasoundFrontendVertexAnalyzer.h.
Referenced by FVertexAnalyzerBase(), Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::TVertexAnalyzerForwardValue(), BindOutputData(), and GetAnalyzerAddress().
BoundOutputData
TMap<FName, FBoundOutputDataPtr> Metasound::Frontend::FVertexAnalyzerBase::BoundOutputData private
Definition at line 204 of file MetasoundFrontendVertexAnalyzer.h.
Referenced by BindOutputData(), MarkOutputDirty(), and UnbindOutputData().
VertexDataReference
FAnyDataReference Metasound::Frontend::FVertexAnalyzerBase::VertexDataReference private
Definition at line 205 of file MetasoundFrontendVertexAnalyzer.h.
Referenced by FVertexAnalyzerBase(), Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::TVertexAnalyzerForwardValue(), GetDataReferenceId(), GetVertexData(), and SetDataReference().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/Analysis/MetasoundFrontendVertexAnalyzer.h