Unreal Engine 5.6 C++ API: FThreadSingletonInitializer Class Reference
FThreadSingletonInitializer Class Reference
Thread singleton initializer.
#include "ThreadSingleton.h"
Static Public Member Functions
static FTlsAutoCleanup * Get (TFunctionRef< FTlsAutoCleanup *()> CreateInstance, uint32 &TlsSlot)
static FTlsAutoCleanup * Inject (FTlsAutoCleanup *Instance, uint32 &TlsSlot)
static FTlsAutoCleanup * TryGet (uint32 &TlsSlot)
Detailed Description
Thread singleton initializer.
Definition at line 15 of file ThreadSingleton.h.
Member Function Documentation
Get()
FTlsAutoCleanup * FThreadSingletonInitializer::Get (TFunctionRef< FTlsAutoCleanup *()> CreateInstance, uint32 & TlsSlot) static
Returns
an instance of a singleton for the current thread.
Referenced by TThreadSingleton< T >::Get(), and TThreadSingleton< T >::Get().
Inject()
FTlsAutoCleanup * FThreadSingletonInitializer::Inject (FTlsAutoCleanup * Instance, uint32 & TlsSlot) static
Returns
sets the TLS store to the instance and returns the previous instance.
References Instance.
Referenced by TThreadSingleton< T >::Inject().
TryGet()
FTlsAutoCleanup * FThreadSingletonInitializer::TryGet (uint32 & TlsSlot) static
Returns
an instance of the singleton if it exists on the current thread.
Referenced by TThreadSingleton< T >::TryGet().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/ThreadSingleton.h