Unreal Engine 5.6 C++ API: FArchive Class Reference
FArchive Class Reference
Base class for archives that can be used for loading, saving, and garbage collecting in a byte order neutral way.
#include "Archive.h"
Data Structures
class FScopeAddDebugData
class FScopeSeekTo
Seeks to and restores the position of an archive.
class FScopeSetDebugSerializationFlags
Public Member Functions
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData)
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData)
Attaches/ associates the passed in bulk data object with the linker.
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback)
Adds external read dependency.
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
virtual bool Close ()
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
Detaches the passed in bulk data object from the linker.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
virtual void Flush ()
Attempts to finish writing any buffered data to disk/permanent storage.
virtual void FlushCache ()
Flushes cache and frees internal data.
virtual void ForceBlueprintFinalization ()
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj)
Called to retrieve the archetype from the event driven loader.
virtual FString GetArchiveName () const
Returns the name of the Archive.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
virtual FArchive * GetCacheableArchive ()
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
virtual FLinker * GetLinker ()
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
virtual bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
virtual void MarkScriptSerializationEnd (const UObject *Obj)
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj)
Called when an object begins serializing property data using script serialization.
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
virtual FArchive & operator<< (FField *&Value)
Serializes a Field value from or into this archive.
virtual FArchive & operator<< (FName &Value)
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (FText &Value)
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (struct FLazyObjectPtr &Value)
Serializes a lazy object pointer value from or into this archive.
virtual FArchive & operator<< (struct FObjectPtr &Value)
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (struct FSoftObjectPath &Value)
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (struct FSoftObjectPtr &Value)
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (struct FWeakObjectPtr &Value)
Serializes FWeakObjectPtr value from or into this archive.
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
virtual FArchive & operator<< (UObject *&Value)
Serializes an UObject value from or into this archive.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopDebugDataString ()
virtual void PopFileRegionType ()
virtual void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Pop a property that was previously being serialized off the property stack.
virtual bool Precache (int64 PrecacheOffset, int64 PrecacheSize)
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
virtual void Preload (UObject *Object)
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
virtual void PushDebugDataString (const FName &DebugData)
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
virtual void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Push a property that is currently being serialized onto the property stack.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
virtual void Seek (int64 InPos)
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
virtual void Serialize (void *V, int64 Length)
virtual void SerializeBits (void *V, int64 LengthBits)
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params)
Serialize bulk data.
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeInt (uint32 &Value, uint32 Max)
virtual void SerializeIntPacked (uint32 &Value)
Packs int value into bytes of 7 bits with 8th bit for 'more'.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags)
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags)
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetFilterEditorOnly (bool InFilterEditorOnly)
Sets a flag indicating that this archive needs to filter editor-only content.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
virtual void SetSerializedProperty (FProperty *InProperty)
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr)
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const
Checks whether the archive wants to skip the property independent of the other flags.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
virtual int64 Tell ()
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
virtual int64 TotalSize ()
Returns total size of the backing data storage.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
virtual void UsingCustomVersion (const struct FGuid &Guid)
Registers the custom version to the archive.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Data Fields
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Protected Member Functions
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Static Protected Member Functions
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Private Member Functions
template<typename T>
FArchive & ByteOrderSerialize (T &Value)
void VARARGS LogfImpl (const TCHAR *Fmt,...)
FArchive & SerializeByteOrderSwapped (uint16 &Value)
FArchive & SerializeByteOrderSwapped (uint32 &Value)
FArchive & SerializeByteOrderSwapped (uint64 &Value)
FArchive & SerializeByteOrderSwapped (void *V, int32 Length)
Private Member Functions inherited from FArchiveState
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
FORCEINLINE FArchiveCookContext * GetCookContext ()
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FObjectSavePackageSerializeContext * GetSavePackageSerializeContext ()
Return the API object used to record extra data for SavePackage calls (e.g.
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
void SetError ()
Sets ArIsError to true.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
UE_DEPRECATED (5.5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") virtual FUObjectSerializeContext *GetSerializeContext()
Gets the current UObject serialization context for this archive.
UE_DEPRECATED (5.5, "SetSerializeContext is not supported. Remove calls to it.") virtual void SetSerializeContext(FUObjectSerializeContext *InLoadContext)
Sets the current UObject serialization context for this archive.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData.") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
void CopyTrivialFArchiveStatusMembers (const FArchiveState &ArchiveStatusToCopy)
Copies all of the members except CustomVersionContainer.
Private Attributes
FEngineVersionBase ArEngineVer
Holds the engine version.
uint8 ArForceUnicode: 1
Whether this archive wants to always save strings in UTF16 format even if they are ANSI characters.
uint8 ArIsLoading: 1
Whether this archive is for loading data.
uint8 ArIsLoadingFromCookedPackage: 1
Whether this archive is loading from a cooked package.
uint8 ArIsPersistent: 1
Whether this archive saves to persistent storage.
uint8 ArIsSaving: 1
Whether this archive is for saving data.
uint8 ArIsTextFormat: 1
Whether this archive serializes to a text format.
uint8 ArIsTransacting: 1
Whether archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
int32 ArLicenseeUEVer
Holds the archive version for licensees.
FPackageFileVersion ArUEVer
Holds the archive version.
uint8 ArUseUnversionedPropertySerialization: 1
Whether tagged property serialization is replaced by faster unversioned serialization.
uint8 ArWantBinaryPropertySerialization: 1
Whether this archive wants properties to be serialized in binary form instead of tagged.
bool bCustomVersionsAreReset
Indicates if the custom versions container is in a 'reset' state.
FCustomVersionContainer * CustomVersionContainer
All the custom versions stored in the archive.
FProperty * SerializedProperty
Holds the pointer to the property that is currently being serialized.
FArchiveSerializedPropertyChain * SerializedPropertyChain
Holds the chain of properties that are currently being serialized.
Private Attributes inherited from FArchiveState
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
FEngineVersionBase ArEngineVer
Holds the engine version.
uint8 ArForceUnicode: 1
Whether this archive wants to always save strings in UTF16 format even if they are ANSI characters.
uint8 ArIsLoading: 1
Whether this archive is for loading data.
uint8 ArIsLoadingFromCookedPackage: 1
Whether this archive is loading from a cooked package.
uint8 ArIsPersistent: 1
Whether this archive saves to persistent storage.
uint8 ArIsSaving: 1
Whether this archive is for saving data.
uint8 ArIsTextFormat: 1
Whether this archive serializes to a text format.
uint8 ArIsTransacting: 1
Whether archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
int32 ArLicenseeUEVer
Holds the archive version for licensees.
FPackageFileVersion ArUEVer
Holds the archive version.
uint8 ArUseUnversionedPropertySerialization: 1
Whether tagged property serialization is replaced by faster unversioned serialization.
uint8 ArWantBinaryPropertySerialization: 1
Whether this archive wants properties to be serialized in binary form instead of tagged.
bool bCustomVersionsAreReset
Indicates if the custom versions container is in a 'reset' state.
FCustomVersionContainer * CustomVersionContainer = nullptr
All the custom versions stored in the archive.
FArchiveSavePackageData * SavePackageData = nullptr
Provider of data and API specific to UPackage::Save2.
FProperty * SerializedProperty
Holds the pointer to the property that is currently being serialized.
FArchiveSerializedPropertyChain * SerializedPropertyChain
Holds the chain of properties that are currently being serialized.
Friends
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, ANSICHAR &Value)
Serializes an ANSICHAR value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, bool &D)
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, double &Value)
Serializes a double precision floating point value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, float &Value)
Serializes a single precision floating point value from or into an archive.
FArchive & operator<< (FArchive &Ar, FString &Value)
Serializes an FString value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int16 &Value)
Serializes a signed 16-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int32 &Value)
Serializes a signed 32-bit integer value from or into an archive.
FArchive & operator<< (FArchive &Ar, int64 &Value)
Serializes a signed 64-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int8 &Value)
Serializes a signed 8-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint16 &Value)
Serializes an unsigned 16-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint32 &Value)
Serializes an unsigned 32-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint64 &Value)
Serializes a unsigned 64-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint8 &Value)
Serializes an unsigned 8-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, UTF32CHAR &Value)
Serializes a UTF32CHAR value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, WIDECHAR &Value)
Serializes a WIDECHAR value from or into an archive.
Additional Inherited Members
Static Private Member Functions inherited from FArchiveState
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Detailed Description
Base class for archives that can be used for loading, saving, and garbage collecting in a byte order neutral way.
Definition at line 1180 of file Archive.h.
Constructor & Destructor Documentation
FArchive() [1/2]
FArchive::FArchive () default
Referenced by FActorDescArchive::FActorDescArchive(), FActorDescArchivePatcher::FActorDescArchivePatcher(), FArchive(), FArchiveProxy::FArchiveProxy(), FAsyncWriter::FAsyncWriter(), FHierarchicalLogArchive::FHierarchicalLogArchive(), FMaterialResourceProxyReader::FMaterialResourceProxyReader(), FMemoryArchive::FMemoryArchive(), FNameAsStringIndexProxyArchive::FNameAsStringIndexProxyArchive(), FNameAsStringProxyArchive::FNameAsStringProxyArchive(), FObjectAndNameAsStringProxyArchive::FObjectAndNameAsStringProxyArchive(), FPropertyProxyArchive::FPropertyProxyArchive(), FArchive::FScopeAddDebugData::FScopeAddDebugData(), FArchive::FScopeSeekTo::FScopeSeekTo(), FArchive::FScopeSetDebugSerializationFlags::FScopeSetDebugSerializationFlags(), UE::AnimNext::FTraitReader::FTraitReader(), FLinkerSave::AssignSaver(), FLinkerSave::AssignSaverInternal(), ByteOrderSerialize(), ByteOrderSerialize(), FBitReader::CountMemory(), FBitWriter::CountMemory(), FNetBitReader::CountMemory(), FNetBitWriter::CountMemory(), FLinkerLoad::CreateLinker(), FPreloadableArchive::DetachLowerLevel(), FTransactionallySafeArchiveWriter::DoDeferredWrites(), GetCacheableArchive(), FArchiveProxy::GetCacheableArchive(), FLinkerLoad::GetLoader(), FLinkerLoad::GetLoader_Unsafe(), IsProxyOf(), FArchiveProxy::IsProxyOf(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::operator<<(), FActorDescArchive::TDeltaSerializer< DestPropertyType, SourcePropertyType >::operator<<, FActorDescArchivePatcher::operator<<(), FActorDescArchivePatcher::operator<<(), FActorDescArchivePatcher::operator<<(), operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<, operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), FArchiveCrc32::operator<<(), FArchiveCrc32::operator<<(), FArchiveFindCulprit::operator<<(), FArchiveGenerateReferenceGraph::operator<<(), FArchiveHasReferences::operator<<(), FArchiveMD5::operator<<(), FArchiveMD5::operator<<(), FArchiveObjectCrc32::operator<<(), FArchiveObjectCrc32::operator<<(), FArchiveObjectCrc32::operator<<(), FArchiveObjectPropertyMapper::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveProxy::operator<<(), FArchiveReferenceMarker::operator<<(), FArchiveScriptReferenceCollector::operator<<(), FArchiveScriptReferenceCollector::operator<<(), FArchiveScriptReferenceCollector::operator<<(), FArchiveShowReferences::operator<<(), FArchiveUObject::operator<<(), FArchiveUObject::operator<<(), FArchiveUObject::operator<<(), FArchiveUObject::operator<<(), FArchiveUObject::operator<<(), FBulkDataReader::operator<<(), FBulkDataWriter::operator<<(), FDuplicateDataReader::operator<<(), FDuplicateDataReader::operator<<(), FDuplicateDataReader::operator<<(), FDuplicateDataReader::operator<<(), FDuplicateDataReader::operator<<(), FDuplicateDataWriter::operator<<(), FDuplicateDataWriter::operator<<(), FDuplicateDataWriter::operator<<(), FDuplicateDataWriter::operator<<(), FDuplicateDataWriter::operator<<(), FFindAssetsArchive::operator<<(), FFindReferencersArchive::operator<<(), FHLODHashBuilder::operator<<(), FHLODHashBuilder::operator<<(), FHLODHashBuilder::operator<<(), FHLODHashBuilder::operator<<(), FHLODHashBuilder::operator<<(), FHLODHashBuilder::operator<<(), FHLODHashBuilder::operator<<(), FLinkerLoad::operator<<(), FLinkerLoad::operator<<(), FLinkerLoad::operator<<(), FLinkerLoad::operator<<(), FLinkerLoad::operator<<(), FLinkerLoad::operator<<(), FLinkerSave::operator<<(), FLinkerSave::operator<<(), FLinkerSave::operator<<(), FLinkerSave::operator<<(), FLinkerSave::operator<<(), FMaterialResourceProxyReader::operator<<(), FMemoryArchive::operator<<(), FMemoryArchive::operator<<(), FNameAsStringIndexProxyArchive::operator<<(), FNameAsStringProxyArchive::operator<<(), FNetBitReader::operator<<(), FNetBitReader::operator<<(), FNetBitReader::operator<<(), FNetBitReader::operator<<(), FNetBitReader::operator<<(), FNetBitReader::operator<<(), FNetBitWriter::operator<<(), FNetBitWriter::operator<<(), FNetBitWriter::operator<<(), FNetBitWriter::operator<<(), FNetBitWriter::operator<<(), FNetBitWriter::operator<<(), FObjectAndNameAsStringProxyArchive::operator<<(), FObjectAndNameAsStringProxyArchive::operator<<(), FObjectAndNameAsStringProxyArchive::operator<<(), FObjectAndNameAsStringProxyArchive::operator<<(), FObjectAndNameAsStringProxyArchive::operator<<(), FObjectReader::operator<<(), FObjectReader::operator<<(), FObjectReader::operator<<(), FObjectReader::operator<<(), FObjectReader::operator<<(), FObjectReader::operator<<(), FObjectReader::operator<<(), FPropertyProxyArchive::operator<<(), FReferenceCollectorArchive::operator<<(), FReferenceCollectorArchive::operator<<(), FRigVMObjectArchiveReader::operator<<(), FRigVMObjectArchiveReader::operator<<(), FRigVMObjectArchiveReader::operator<<(), FRigVMObjectArchiveWriter::operator<<(), FRigVMObjectArchiveWriter::operator<<(), FRigVMObjectArchiveWriter::operator<<(), FSoftObjectPathFixupArchive::operator<<(), FSoftObjectPathFixupArchive::operator<<(), ObjectTools::FArchiveTopLevelReferenceCollector::operator<<(), UE::AnimNext::FTraitReader::operator<<(), UE::AnimNext::FTraitReader::operator<<(), UE::AnimNext::FTraitReader::operator<<(), UE::AnimNext::FTraitReader::operator<<(), UE::AnimNext::FTraitReader::operator<<(), UE::AnimNext::FTraitWriter::operator<<(), UE::AnimNext::FTraitWriter::operator<<(), UE::AnimNext::FTraitWriter::operator<<(), UE::AnimNext::FTraitWriter::operator<<(), UE::AnimNext::FTraitWriter::operator<<(), UE::Transaction::FDiffableObjectDataWriter::operator<<(), UE::Transaction::FDiffableObjectDataWriter::operator<<(), UE::Transaction::FSerializedObjectDataReader::operator<<(), UE::Transaction::FSerializedObjectDataReader::operator<<(), UE::Transaction::FSerializedObjectDataWriter::operator<<(), UE::Transaction::FSerializedObjectDataWriter::operator<<(), operator=(), SerializeByteOrderSwapped(), SerializeByteOrderSwapped(), SerializeByteOrderSwapped(), SerializeByteOrderSwapped(), FArchiveUObject::SerializeLazyObjectPtr(), FArchiveUObject::SerializeObjectPtr(), FArchiveUObject::SerializeSoftObjectPath(), FArchiveUObject::SerializeSoftObjectPtr(), FArchiveUObject::SerializeWeakObjectPtr(), FLinkerLoad::SetLoader(), FBitReader::SetNetVersionsFromArchive(), and FPreloadableFile::TryTakeArchive().
FArchive() [2/2]
FArchive::FArchive (const FArchive &) default
References FArchive().
~FArchive()
virtual FArchive::~FArchive () virtual
References FArchiveState::LinkProxy(), and FArchiveState::UnlinkProxy().
Member Function Documentation
AtEnd()
virtual bool FArchiveState::AtEnd () inline virtual
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, FBitReader, FBufferReaderBase, FBufferWriter, and FBulkDataWriter.
Definition at line 161 of file Archive.h.
AttachBulkData() [1/2]
virtual void FArchive::AttachBulkData (UE::Serialization::FEditorBulkData * BulkData) inline virtual
Reimplemented in FLinkerLoad.
Definition at line 1735 of file Archive.h.
References BulkData.
AttachBulkData() [2/2]
virtual void FArchive::AttachBulkData (UObject * Owner, FBulkData * BulkData) inline virtual
Attaches/ associates the passed in bulk data object with the linker.
Parameters
Owner UObject owning the bulk data
BulkData Bulk data object to associate
Reimplemented in FArchiveProxy, and FLinkerLoad.
Definition at line 1734 of file Archive.h.
References BulkData, and Owner.
AttachExternalReadDependency()
virtual bool FArchive::AttachExternalReadDependency (FExternalReadCallback & ReadCallback) inline virtual
Adds external read dependency.
Returns
true if dependency has been added, false if Archive does not support them
Reimplemented in FArchiveProxy, and FLinkerLoad.
Definition at line 2063 of file Archive.h.
ByteOrderSerialize() [1/2]
template<typename T> FArchive & FArchive::ByteOrderSerialize (T & Value) inline private
Definition at line 2126 of file Archive.h.
References FArchive(), IsByteSwapping(), Serialize(), SerializeByteOrderSwapped(), TIsSigned< T >::Value, and Value.
ByteOrderSerialize() [2/2]
FORCEINLINE FArchive & FArchive::ByteOrderSerialize (void * V, int32 Length) inline
Serialize data of Length bytes, taking into account byte swapping if needed.
Definition at line 1878 of file Archive.h.
References FArchive(), FORCEINLINE, IsByteSwapping(), Serialize(), and SerializeByteOrderSwapped().
Referenced by SerializeInt().
ByteSwap()
void FArchive::ByteSwap (void * V, int32 Length)
Used to do byte swapping on small items.
This does not happen usually, so we don't want it inline.
ClearError()
void FArchiveState::ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
Close()
virtual bool FArchive::Close () inline virtual
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
Reimplemented in FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveProxy, FBufferReaderBase, FBufferReaderWithSHA, FBufferWriter, FPreloadableArchive, and FPreloadableArchiveProxy.
Definition at line 1820 of file Archive.h.
References IsError().
Referenced by WriteCustomReport().
ContainsCode()
FORCEINLINE bool FArchiveState::ContainsCode () const inline
Returns true if this archive contains native or generated code.
Definition at line 379 of file Archive.h.
ContainsMap()
FORCEINLINE bool FArchiveState::ContainsMap () const inline
Returns true if this archive contains a ULevel or UWorld object.
Definition at line 385 of file Archive.h.
CookingTarget()
FORCEINLINE const ITargetPlatform * FArchiveState::CookingTarget () const inline
Returns the cooking target platform.
Returns null if not being serialized from Savepackage, or if it is an editor save rather than a cook save.
Returns
Target platform.
Definition at line 675 of file Archive.h.
CountBytes()
virtual void FArchiveState::CountBytes (SIZE_T InNum, SIZE_T InMax) inline virtual
Called to get the computed size from a size-detecting archive after it has finished serializing.
Reimplemented from FArchiveState.
Reimplemented in FArchiveCountMem, and FArchiveProxy.
Definition at line 125 of file Archive.h.
CustomVer()
int32 FArchiveState::CustomVer (const struct FGuid & Key) const
Queries a custom version from the archive.
If the archive is being used to write, the custom version must have already been registered.
Parameters
Key The guid of the custom version to query.
Returns
The version number, or -1 if the custom tag isn't stored in the archive.
DetachBulkData() [1/2]
virtual void FArchive::DetachBulkData (FBulkData * BulkData, bool bEnsureBulkDataIsLoaded) inline virtual
Detaches the passed in bulk data object from the linker.
Parameters
BulkData Bulk data object to detach
bEnsureBulkDataIsLoaded Whether to ensure that the bulk data is loaded before detaching
Reimplemented in FArchiveProxy, and FLinkerLoad.
Definition at line 1743 of file Archive.h.
References BulkData.
DetachBulkData() [2/2]
virtual void FArchive::DetachBulkData (UE::Serialization::FEditorBulkData * BulkData, bool bEnsureBulkDataIsLoaded) inline virtual
Reimplemented in FLinkerLoad.
Definition at line 1744 of file Archive.h.
References BulkData.
DoDelta()
FORCEINLINE bool FArchiveState::DoDelta () const inline
Returns true if this archive should handle delta serialization for properties.
Definition at line 417 of file Archive.h.
DoIntraPropertyDelta()
FORCEINLINE bool FArchiveState::DoIntraPropertyDelta () const inline
Returns true if this archive should perform delta serialization within properties (e.g.
TMaps and TSets).
Definition at line 423 of file Archive.h.
EngineNetVer()
virtual uint32 FArchiveState::EngineNetVer () const virtual
Returns the engine-global network protocol version for this archive.
Reimplemented from FArchiveState.
Reimplemented in FInBunch.
EngineVer()
FORCEINLINE FEngineVersionBase FArchiveState::EngineVer () const inline
Returns the compiled engine version used for this archive.
Definition at line 216 of file Archive.h.
FastPathLoad()
template<SIZE_T Size> FORCEINLINE bool FArchive::FastPathLoad (void * InDest) inline
Definition at line 2077 of file Archive.h.
References ActiveFPLB, FORCEINLINE, FGenericPlatformMemory::ReadUnaligned(), RESTRICT, and TSequenceHistory< HistorySize >::Size.
Flush()
virtual void FArchive::Flush () inline virtual
Attempts to finish writing any buffered data to disk/permanent storage.
Reimplemented in FArchiveFileWriterGeneric, FArchiveProxy, FArchiveSaveCompressedProxy, FAsyncWriter, and FTransactionallySafeArchiveWriter.
Definition at line 1815 of file Archive.h.
FlushCache()
virtual void FArchive::FlushCache () inline virtual
Flushes cache and frees internal data.
Reimplemented in FArchiveFileReaderGeneric, FArchiveProxy, and FLinkerLoad.
Definition at line 1795 of file Archive.h.
ForceBlueprintFinalization()
virtual void FArchive::ForceBlueprintFinalization () inline virtual
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
Reimplemented in FArchiveProxy, and FLinkerLoad.
Definition at line 1352 of file Archive.h.
ForceByteSwapping()
FORCEINLINE bool FArchiveState::ForceByteSwapping () const inline
Returns true if this archive should always swap bytes, ignoring endian rules.
Definition at line 399 of file Archive.h.
GameNetVer()
virtual uint32 FArchiveState::GameNetVer () const virtual
Returns the game-specific network protocol version for this archive.
Reimplemented from FArchiveState.
Reimplemented in FInBunch.
GetArchetypeFromLoader()
virtual UObject * FArchiveState::GetArchetypeFromLoader (const UObject * Obj) inline virtual
Called to retrieve the archetype from the event driven loader.
If this returns null, then call GetArchetype yourself.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, and FLinkerLoad.
Definition at line 198 of file Archive.h.
GetArchiveName()
virtual FString FArchiveState::GetArchiveName () const virtual
Returns the name of the Archive.
Useful for getting the name of the package a struct or object is in when a loading error occurs.
This is overridden for the specific Archive Types
Reimplemented from FArchiveState.
Reimplemented in FArchiveCountMem, FArchiveCrc32, FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveFindCulprit, FArchiveMD5, FArchiveObjectCrc32, FArchiveProxy, FArchiveReplaceObjectRefBase, FArchiveShowReferences, FArrayReader, FBufferReader, FBufferReaderBase, FBufferReaderWithSHA, FBufferWriter, FBulkDataReader, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FFindReferencersArchive, FLargeMemoryReader, FLargeMemoryWriter, FLinkerLoad, FLinkerSave, FMaterialResourceMemoryWriter, FMaterialResourceProxyReader, FMemoryArchive, FMemoryReader, FMemoryReaderView, FObjectReader, FObjectWriter, FPreloadableArchive, FPreloadableArchiveProxy, FStaticMemoryReader, FTransactionallySafeArchiveWriter, TBufferArchive< IndexSize >, TBufferArchive< 32 >, TBufferArchive< 64 >, TMemoryHasher< HashBuilder, HashDigest >, TMemoryHasher< FBlake3, FBlake3Hash >, TMemoryHasher< FSHA1, FSHAHash >, TMemoryWriterBase< ArrayAllocatorType >, and TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >.
Referenced by TProperty_Numeric< InTCppType >::TConvertAndSet< FromType, ToType >::TConvertAndSet().
GetArchiveState() [1/2]
FArchiveState & FArchive::GetArchiveState () inline
Returns the low level archive state for this archive.
Definition at line 1703 of file Archive.h.
References FArchiveState::FArchiveState(), and ImplicitConv().
Referenced by FStructuredArchive::GetArchiveState().
GetArchiveState() [2/2]
const FArchiveState & FArchive::GetArchiveState () const inline
Definition at line 1708 of file Archive.h.
References FArchiveState::FArchiveState(), and ImplicitConv().
GetCacheableArchive()
virtual FArchive * FArchive::GetCacheableArchive () inline virtual
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
If the archive is actually a temporary proxy to another archive, and has a shorter lifecycle than the source archive, it should return either a pointer to the underlying archive, or if the data becomes inaccessible when the proxy object disappears (as is the case with text format archives) then nullptr
Reimplemented in FArchiveProxy.
Definition at line 1957 of file Archive.h.
References FArchive().
GetCookContext()
FORCEINLINE FArchiveCookContext * FArchiveState::GetCookContext () inline
Definition at line 664 of file Archive.h.
GetCustomVersions()
virtual const FCustomVersionContainer & FArchiveState::GetCustomVersions () const virtual
Gets the custom version numbers for this archive.
These are used to check for system or game-specific version numbers.
Returns
The container of custom versions in the archive.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, and FMaterialResourceMemoryWriter.
GetDebugSerializationFlags()
FORCEINLINE uint32 FArchiveState::GetDebugSerializationFlags () const inline
Returns the editor-only debug serialization flags.
Definition at line 492 of file Archive.h.
GetError()
FORCEINLINE bool FArchiveState::GetError () const inline
Definition at line 367 of file Archive.h.
GetInnermostState()
virtual FArchiveState & FArchiveState::GetInnermostState () inline virtual
Returns lowest level archive state, proxy archives will override this.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy.
Definition at line 97 of file Archive.h.
GetLinker()
virtual FLinker * FArchiveState::GetLinker () inline virtual
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
Returns
The linker, or nullptr if the archive is not a linker.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 140 of file Archive.h.
GetMaxSerializeSize()
FORCEINLINE int64 FArchiveState::GetMaxSerializeSize () const inline
Returns the maximum size of data that this archive is allowed to serialize.
Definition at line 508 of file Archive.h.
GetMigrationContext()
virtual const FUObjectMigrationContext * FArchiveState::GetMigrationContext () const inline virtual
When migrating objects, we may need some context as to the intent of the migration during serialization.
Reimplemented from FArchiveState.
Definition at line 343 of file Archive.h.
GetPortFlags()
FORCEINLINE uint32 FArchiveState::GetPortFlags () const inline
Returns this archive's property serialization modifier flags.
Definition at line 474 of file Archive.h.
Referenced by FProperty::SerializeNonMatchingBinProperty().
GetSavePackageData()
FArchiveSavePackageData * FArchiveState::GetSavePackageData () inline
Definition at line 640 of file Archive.h.
GetSerializedProperty()
FORCEINLINE class FProperty * FArchiveState::GetSerializedProperty () const inline
Gets the property that is currently being serialized.
Returns
Pointer to the property that is currently being serialized
Definition at line 724 of file Archive.h.
Referenced by FArchiveObjectPropertyMapper::operator<<().
GetSerializedPropertyChain() [1/2]
FORCEINLINE const FArchiveSerializedPropertyChain * FArchiveState::GetSerializedPropertyChain () const inline
Get the raw serialized property chain for this archive.
Note
Accessing this directly can avoid an array allocation depending on your use-case
Definition at line 739 of file Archive.h.
GetSerializedPropertyChain() [2/2]
void FArchiveState::GetSerializedPropertyChain (TArray< class FProperty * > & OutProperties) const
Gets the chain of properties that are currently being serialized.
Note
This populates the array in stack order, so the 0th entry in the array is the top of the stack of properties
HasAllPortFlags()
FORCEINLINE bool FArchiveState::HasAllPortFlags (uint32 Flags) const inline
Checks to see if all of the passed in property serialization modifier flags are set.
Definition at line 486 of file Archive.h.
HasAnyPortFlags()
FORCEINLINE bool FArchiveState::HasAnyPortFlags (uint32 Flags) const inline
Checks to see if any of the passed in property serialization modifier flags are set.
Definition at line 480 of file Archive.h.
IsAllowingLazyLoading()
FORCEINLINE bool FArchiveState::IsAllowingLazyLoading () const inline
Returns true if this archive sould allow lazy loading of bulk / secondary data.
Definition at line 447 of file Archive.h.
IsByteSwapping()
FORCEINLINE bool FArchiveState::IsByteSwapping () inline
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
Definition at line 169 of file Archive.h.
Referenced by ByteOrderSerialize(), and ByteOrderSerialize().
IsCooking()
FORCEINLINE bool FArchiveState::IsCooking () const inline
Checks whether the archive is used for cooking.
Returns
true if the archive is used for cooking, false otherwise.
Definition at line 617 of file Archive.h.
IsCountingMemory()
FORCEINLINE bool FArchiveState::IsCountingMemory () const inline
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
Definition at line 468 of file Archive.h.
IsCriticalError()
FORCEINLINE bool FArchiveState::IsCriticalError () const inline
Returns true if this archive contains critical errors that cannot be recovered from.
Definition at line 373 of file Archive.h.
IsError()
FORCEINLINE bool FArchiveState::IsError () const inline
Returns true if this archive contains errors, which means that further serialization is generally not safe.
Definition at line 362 of file Archive.h.
Referenced by FBitReader::AtEnd(), Close(), FBufferReaderBase::Close(), FBufferWriter::Close(), FBitWriter::GetBuffer(), FBitWriter::GetData(), FBitWriter::GetData(), FBitWriterMark::Init(), FBitReader::ReadBit(), UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Receive(), FArrayReader::Serialize(), FMemoryReader::Serialize(), FMemoryReaderView::Serialize(), FObjectReader::Serialize(), FStaticMemoryReader::Serialize(), FBitReader::SerializeBits(), and FBitReader::SerializeInt().
IsFilterEditorOnly()
bool FArchiveState::IsFilterEditorOnly () const inline
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
Returns
true if the archive filters editor-only content, false otherwise.
Definition at line 578 of file Archive.h.
IsForcingUnicode()
FORCEINLINE bool FArchiveState::IsForcingUnicode () const inline
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
Definition at line 291 of file Archive.h.
IsIgnoringArchetypeRef()
FORCEINLINE bool FArchiveState::IsIgnoringArchetypeRef () const inline
Returns true if this archive should ignore archetype references for structs and classes.
Definition at line 411 of file Archive.h.
IsIgnoringClassGeneratedByRef()
FORCEINLINE bool FArchiveState::IsIgnoringClassGeneratedByRef () const inline
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
Definition at line 435 of file Archive.h.
IsIgnoringClassRef()
FORCEINLINE bool FArchiveState::IsIgnoringClassRef () const inline
Returns true if this archive should ignore the Class reference in UObject.
Definition at line 441 of file Archive.h.
IsIgnoringOuterRef()
FORCEINLINE bool FArchiveState::IsIgnoringOuterRef () const inline
Returns true if this archive should ignore the Outer reference in UObject.
Definition at line 429 of file Archive.h.
IsLoading()
FORCEINLINE bool FArchiveState::IsLoading () const inline
Returns true if this archive is for loading data.
Definition at line 236 of file Archive.h.
Referenced by operator<<(), FConfigValue::operator<<, FMemoryArchive::operator<<(), FPropertyProxyArchive::operator<<(), operator<<(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::operator<<, UE::Math::operator<<(), UE::Math::operator<<(), SerializeBits(), PerPlatformProperty::Private::FNameFuncs< FMemoryImageName >::SerializePerPlatformMap(), TSetPrivateFriend::SerializeStructured(), and UE::Core::PagedArray::Private::SerializeStructured().
IsLoadingFromCookedPackage()
FORCEINLINE bool FArchiveState::IsLoadingFromCookedPackage () const inline
Returns true if this archive is loading from a cooked package.
Definition at line 242 of file Archive.h.
IsMigratingRemoteObjects()
FORCEINLINE constexpr bool FArchiveState::IsMigratingRemoteObjects () const inline constexpr
Returns true if this Archive is migrating remote object.
Definition at line 355 of file Archive.h.
IsModifyingWeakAndStrongReferences()
FORCEINLINE bool FArchiveState::IsModifyingWeakAndStrongReferences () const inline
Returns true if this archive should modify/search weak object references as well as strong ones.
Definition at line 462 of file Archive.h.
Referenced by TSetPrivateFriend::SerializeStructured().
IsNetArchive()
FORCEINLINE bool FArchiveState::IsNetArchive () const inline
Whether or not this archive is serializing data being sent/received by the netcode.
Definition at line 607 of file Archive.h.
IsObjectReferenceCollector()
FORCEINLINE bool FArchiveState::IsObjectReferenceCollector () const inline
Returns true if this archive is only looking for UObject references.
This can be false for reference collectors looking for more general references.
Definition at line 456 of file Archive.h.
Referenced by FPropertyProxyArchive::operator<<().
IsPersistent()
FORCEINLINE bool FArchiveState::IsPersistent () const inline
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
This is also true for some intermediate archives for tasks like duplication that are eventually destined for persistent storage.
Definition at line 300 of file Archive.h.
Referenced by FPropertyProxyArchive::operator<<().
IsProxyOf()
virtual bool FArchive::IsProxyOf (FArchive * InOther) const inline virtual
Determine if the given archive is a valid "child" of this archive.
In general, this means "is exactly the same" but this function allows a derived archive to support "child" or "internal" archives which are different objects that proxy the original one in some way.
Parameters
BulkData Bulk data object to detach
bEnsureBulkDataIsLoaded Whether to ensure that the bulk data is loaded before detaching
Reimplemented in FArchiveProxy.
Definition at line 1767 of file Archive.h.
References FArchive().
IsSaveGame()
bool FArchiveState::IsSaveGame () const inline
Indicates whether this archive is saving or loading game state.
Note
This is intended for game-specific archives and is not true for any of the build in save methods
Returns
true if the archive is dealing with save games, false otherwise.
Definition at line 599 of file Archive.h.
IsSaving()
FORCEINLINE bool FArchiveState::IsSaving () const inline
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
Definition at line 248 of file Archive.h.
Referenced by operator<<(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::operator<<, and TSetPrivateFriend::SerializeStructured().
IsSerializingDefaults()
FORCEINLINE bool FArchiveState::IsSerializingDefaults () const inline
Returns true if this archive is currently serializing class/struct default values.
Definition at line 405 of file Archive.h.
IsTextFormat()
FORCEINLINE bool FArchiveState::IsTextFormat () const inline
Returns true if this archive serializes to a structured text format.
Text format archives should use high level constructs from FStructuredArchive for delimiting data rather than manually seeking through the file.
Definition at line 270 of file Archive.h.
IsTransacting()
FORCEINLINE bool FArchiveState::IsTransacting () const inline
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
Definition at line 254 of file Archive.h.
LicenseeUEVer()
FORCEINLINE int32 FArchiveState::LicenseeUEVer () const inline
Returns the licensee-specific version used for this archive, will be 0 by default.
Definition at line 210 of file Archive.h.
LinkProxy()
void FArchiveState::LinkProxy (FArchiveState & Inner, FArchiveState & Proxy) static protected
Logf()
template<typename FmtType, typename... Types> void FArchive::Logf (const FmtType & Fmt, Types... Args) inline
Definition at line 1927 of file Archive.h.
References LogfImpl(), TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
LogfImpl()
void VARARGS FArchive::LogfImpl (const TCHAR * Fmt, ...) private
References VARARGS.
Referenced by Logf().
MarkScriptSerializationEnd()
virtual void FArchive::MarkScriptSerializationEnd (const UObject * Obj) inline virtual
Called when an object stops serializing property data using script serialization.
Reimplemented in FArchiveProxy, FLinkerLoad, FLinkerSave, and UE::Transaction::FDiffableObjectDataWriter.
Definition at line 1912 of file Archive.h.
MarkScriptSerializationStart()
virtual void FArchive::MarkScriptSerializationStart (const UObject * Obj) inline virtual
Called when an object begins serializing property data using script serialization.
Reimplemented in FArchiveProxy, FLinkerLoad, FLinkerSave, and UE::Transaction::FDiffableObjectDataWriter.
Definition at line 1907 of file Archive.h.
MarkSearchableName()
virtual void FArchive::MarkSearchableName (const TObjectPtr< const UObject > & TypeObject, const FName & ValueName) const inline virtual
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
Const so it can be called from PostSerialize
Reimplemented in FArchiveProxy.
Definition at line 1917 of file Archive.h.
operator<<() [1/10]
virtual FArchive & FArchive::operator<< (FField *& Value) inline virtual
Serializes a Field value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FArchiveMD5, FArchiveProxy, FArchiveScriptReferenceCollector, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FDuplicateDataWriter, FLinkerLoad, FLinkerSave, FMemoryArchive, FPropertyProxyArchive, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
Definition at line 1237 of file Archive.h.
References FArchive(), and Value.
operator<<() [2/10]
virtual FArchive & FArchive::operator<< (FName & Value) inline virtual
Serializes an FName value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FName instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FActorDescArchivePatcher, FArchiveCrc32, FArchiveMD5, FArchiveObjectCrc32, FArchiveProxy, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FControlChannelOutBunch, FDuplicateDataReader, FDuplicateDataWriter, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMaterialResourceMemoryWriter, FMaterialResourceProxyReader, FMemoryArchive, FNameAsStringIndexProxyArchive, FNameAsStringProxyArchive, FNetBitReader, FNetBitWriter, FObjectReader, FObjectWriter, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
Definition at line 1203 of file Archive.h.
References FArchive(), and Value.
operator<<() [3/10]
virtual FArchive & FArchive::operator<< (FText & Value) virtual
Serializes an FText value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Reimplemented in FActorDescArchive, FArchiveMD5, FArchiveProxy, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FLinkerLoad, FLinkerSave, FMemoryArchive, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
References FArchive(), and Value.
operator<<() [4/10]
virtual FArchive & FArchive::operator<< (struct FLazyObjectPtr & Value) virtual
Serializes a lazy object pointer value from or into this archive.
Most of the time, FLazyObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FArchiveCrc32, FArchiveMD5, FArchiveProxy, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMemoryArchive, FObjectReader, FObjectWriter, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
References FArchive(), and Value.
operator<<() [5/10]
virtual FArchive & FArchive::operator<< (struct FObjectPtr & Value) virtual
Serializes a wrapped object pointer value from or into this archive.
Most of the time, FObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FArchiveCrc32, FArchiveMD5, FArchiveObjectCrc32, FArchiveProxy, FArchiveScriptReferenceCollector, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMemoryArchive, FNetBitReader, FNetBitWriter, FObjectAndNameAsStringProxyArchive, FObjectReader, FObjectWriter, FReferenceCollectorArchive, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, FSoftObjectPathFixupArchive, UE::AnimNext::FTraitReader, UE::AnimNext::FTraitWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
References FArchive(), and Value.
operator<<() [6/10]
virtual FArchive & FArchive::operator<< (struct FSoftObjectPath & Value) virtual
Serializes soft object paths from or into this archive.
Parameters
Value Soft object path to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FActorDescArchivePatcher, FArchiveCrc32, FArchiveMD5, FArchiveProxy, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FDuplicateDataReader, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMemoryArchive, FNetBitReader, FNetBitWriter, FObjectAndNameAsStringProxyArchive, FObjectReader, FObjectWriter, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, FSoftObjectPathFixupArchive, UE::AnimNext::FTraitReader, UE::AnimNext::FTraitWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
References FArchive(), and Value.
operator<<() [7/10]
virtual FArchive & FArchive::operator<< (struct FSoftObjectPtr & Value) virtual
Serializes asset pointer from or into this archive.
Most of the time, FSoftObjectPtr are serialized as UObject *, but some archives need to override this.
Parameters
Value The asset pointer to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FArchiveCrc32, FArchiveMD5, FArchiveProxy, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMemoryArchive, FNetBitReader, FNetBitWriter, FObjectAndNameAsStringProxyArchive, FObjectReader, FObjectWriter, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, UE::AnimNext::FTraitReader, UE::AnimNext::FTraitWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
References FArchive(), and Value.
operator<<() [8/10]
virtual FArchive & FArchive::operator<< (struct FWeakObjectPtr & Value) virtual
Serializes FWeakObjectPtr value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FWeakObjectPtr instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FArchiveCrc32, FArchiveMD5, FArchiveProxy, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMemoryArchive, FNetBitReader, FNetBitWriter, FObjectAndNameAsStringProxyArchive, FObjectReader, FObjectWriter, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, UE::AnimNext::FTraitReader, UE::AnimNext::FTraitWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
References FArchive(), and Value.
operator<<() [9/10]
template<class T> FORCEINLINE FArchive & FArchive::operator<< (TCheckedObjPtr< T > & Value) inline
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
Parameters
Value The value to serialize.
Returns
This instance.
Definition at line 1264 of file Archive.h.
References FArchive(), FORCEINLINE, IsLoading(), IsSaving(), and Value.
operator<<() [10/10]
virtual FArchive & FArchive::operator<< (UObject *& Value) inline virtual
Serializes an UObject value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented in FActorDescArchive, FArchiveCrc32, FArchiveFindCulprit, FArchiveGenerateReferenceGraph, FArchiveHasReferences, FArchiveMD5, FArchiveObjectCrc32, FArchiveObjectPropertyMapper, FArchiveProxy, FArchiveReferenceMarker, FArchiveScriptReferenceCollector, FArchiveShowReferences, FArchiveUObject, FBulkDataReader, FBulkDataWriter, FControlChannelOutBunch, FDuplicateDataReader, FDuplicateDataWriter, FFindAssetsArchive, FFindReferencersArchive, FHLODHashBuilder, FLinkerLoad, FLinkerSave, FMemoryArchive, FNetBitReader, FNetBitWriter, FObjectAndNameAsStringProxyArchive, FObjectReader, FObjectWriter, FReferenceCollectorArchive, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, ObjectTools::FArchiveTopLevelReferenceCollector, UE::AnimNext::FTraitReader, UE::AnimNext::FTraitWriter, UE::Transaction::FDiffableObjectDataWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::FSerializedObjectDataWriter.
Definition at line 1224 of file Archive.h.
References FArchive(), and Value.
operator=()
FArchive & FArchive::operator= (const FArchive & ArchiveToCopy) default
References FArchive().
PopDebugDataString()
virtual void FArchive::PopDebugDataString () inline virtual
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 2275 of file Archive.h.
Referenced by FLinkerLoad::PopDebugDataString().
PopFileRegionType()
virtual void FArchive::PopFileRegionType () inline virtual
Reimplemented in TFileRegionArchive< FLargeMemoryWriter >.
Definition at line 2317 of file Archive.h.
PopSerializedProperty()
virtual void FArchive::PopSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) virtual
Pop a property that was previously being serialized off the property stack.
Parameters
InProperty Pointer to the property that was previously being serialized
bIsEditorOnlyProperty True if the property is editor only (call FProperty::IsEditorOnlyProperty to work this out, as the archive can't since it can't access CoreUObject types)
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Referenced by FArchiveProxy::PopSerializedProperty(), and FLinkerLoad::PopSerializedProperty().
Precache()
virtual bool FArchive::Precache (int64 PrecacheOffset, int64 PrecacheSize) inline virtual
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
The function returns whether the precache operation has completed or not which is an important hint for code knowing that it deals with potential async I/O. The archive is free to either not implement this function or only partially precache so it is required that given sufficient time the function will return true. Archives not based on async I/O should always return true.
This function will not change the current archive position.
Parameters
PrecacheOffset Offset at which to begin precaching.
PrecacheSize Number of bytes to precache
Returns
false if precache operation is still pending, true otherwise
Reimplemented in FArchiveFileReaderGeneric, FArchiveProxy, and FLinkerLoad.
Definition at line 1787 of file Archive.h.
Preload()
virtual void FArchive::Preload (UObject * Object) inline virtual
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
Reimplemented in FArchiveProxy, FLinkerLoad, and FTransaction::FObjectRecord::FReader.
Definition at line 1700 of file Archive.h.
References Object.
PushDebugDataString()
virtual void FArchive::PushDebugDataString (const FName & DebugData) virtual
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Referenced by FLinkerLoad::PushDebugDataString().
PushFileRegionType()
virtual void FArchive::PushFileRegionType (EFileRegionType Type) inline virtual
Called whilst cooking to provide file region hints to the cooker.
Reimplemented in TFileRegionArchive< FLargeMemoryWriter >.
Definition at line 2316 of file Archive.h.
PushSerializedProperty()
virtual void FArchive::PushSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) virtual
Push a property that is currently being serialized onto the property stack.
Parameters
InProperty Pointer to the property that is currently being serialized
bIsEditorOnlyProperty True if the property is editor only (call FProperty::IsEditorOnlyProperty to work this out, as the archive can't since it can't access CoreUObject types)
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Referenced by FArchiveProxy::PushSerializedProperty(), and FLinkerLoad::PushSerializedProperty().
RequiresLocalizationGather()
FORCEINLINE bool FArchiveState::RequiresLocalizationGather () const inline
Returns true if this archive contains data required to be gathered for localization.
Definition at line 391 of file Archive.h.
Reset()
virtual void FArchiveState::Reset () virtual
Resets all of the base archive members.
Reimplemented from FArchiveState.
Reimplemented in FArchiveMD5, FBitWriter, and FOutBunch.
Referenced by FArchiveMD5::Reset().
ResetCustomVersions()
virtual void FArchiveState::ResetCustomVersions () virtual
Resets the custom version numbers for this archive.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy.
Seek()
virtual void FArchive::Seek (int64 InPos) inline virtual
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
Reimplemented in FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveLoadCompressedProxy, FArchiveProxy, FArchiveSaveCompressedProxy, FBufferReaderBase, FBufferWriter, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FLinkerLoad, FLinkerSave, FMaterialResourceProxyReader, FMemoryArchive, FPreloadableArchive, FPreloadableArchiveProxy, FRigVMObjectArchiveWriter, FTransactionallySafeArchiveWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::Internal::FSerializedObjectDataWriterCommon.
Definition at line 1726 of file Archive.h.
Serialize()
virtual void FArchive::Serialize (void * V, int64 Length) inline virtual
Reimplemented in FActorDescArchivePatcher, FArchiveCrc32, FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveLoadCompressedProxy, FArchiveMD5, FArchiveObjectCrc32, FArchiveProxy, FArchiveSaveCompressedProxy, FArchiveStackTraceReader, FArrayReader, FAsyncWriter, FBitReader, FBitWriter, FBufferReaderBase, FBufferWriter, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FLargeMemoryReader, FLargeMemoryWriter, FLinkerLoad, FLinkerSave, FMemoryReader, FMemoryReaderView, FObjectReader, FOutputDeviceMemory::FOutputDeviceMemoryProxyArchive, FPreloadableArchive, FPreloadableArchiveProxy, FRigVMObjectArchiveReader, FRigVMObjectArchiveWriter, FStaticMemoryReader, FTransactionallySafeArchiveWriter, TMemoryHasher< HashBuilder, HashDigest >, TMemoryHasher< FBlake3, FBlake3Hash >, TMemoryHasher< FSHA1, FSHAHash >, TMemoryWriterBase< ArrayAllocatorType >, TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::Internal::FSerializedObjectDataWriterCommon.
Definition at line 1662 of file Archive.h.
Referenced by ByteOrderSerialize(), ByteOrderSerialize(), FQuantizedShadowSignedDistanceFieldData2D::Serialize(), FShadowSignedDistanceFieldData2D::Serialize(), SerializeBits(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and WriteCustomReport().
SerializeBits()
virtual void FArchive::SerializeBits (void * V, int64 LengthBits) inline virtual
Reimplemented in FArchiveProxy, FBitReader, and FBitWriter.
Definition at line 1680 of file Archive.h.
References IsLoading(), and Serialize().
SerializeBool()
virtual void FArchive::SerializeBool (bool & D) protected virtual
Serializes a Boolean value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
SerializeBulkData()
virtual bool FArchive::SerializeBulkData (FBulkData & BulkData, const FBulkDataSerializationParams & Params) inline virtual
Serialize bulk data.
Parameters
BulkData Bulk data object to serialize
Params Serialization parameters
Returns
true if the bulk data was serialized, false to fallback to default serialization (inline)
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 1754 of file Archive.h.
References BulkData, and Params.
SerializeByteOrderSwapped() [1/4]
FArchive & FArchive::SerializeByteOrderSwapped (uint16 & Value) private
References FArchive(), and Value.
SerializeByteOrderSwapped() [2/4]
FArchive & FArchive::SerializeByteOrderSwapped (uint32 & Value) private
References FArchive(), and Value.
SerializeByteOrderSwapped() [3/4]
FArchive & FArchive::SerializeByteOrderSwapped (uint64 & Value) private
References FArchive(), and Value.
SerializeByteOrderSwapped() [4/4]
FArchive & FArchive::SerializeByteOrderSwapped (void * V, int32 Length) private
References FArchive().
Referenced by ByteOrderSerialize(), and ByteOrderSerialize().
SerializeCompressed()
void FArchive::SerializeCompressed (void * V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags = COMPRESS_NoFlags, bool bTreatBufferAsFileReader = false)
Serializes and compresses/ uncompresses data.
This is a shared helper function for compression support.
Do not use SerializeCompressed in new code, prefer SerializeCompressedNew instead. SerializeCompressedNew can be dropped in to any existing use of SerializeCompressed.
Parameters
V Data pointer to serialize data from/ to
Length Length of source data if we're saving, unused otherwise
CompressionFormatCannotChange Compression Format to use for encoding & decoding - cannot be changed without breaking file compatibility
Flags Flags to control what method to use for [de]compression and optionally control memory vs speed when compressing
bTreatBufferAsFileReader true if V is actually an FArchive, which is used when saving to read data - helps to avoid single huge allocations of source data
References COMPRESS_NoFlags, and Flags.
SerializeCompressedNew() [1/2]
void FArchive::SerializeCompressedNew (void * V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
Default compressors are Oodle for new data and Zlib when loading legacy data.
Parameters
V Data pointer to serialize data from/ to
Length Length of source data if we're saving, unused otherwise
References FArchiveState::IsByteSwapping().
SerializeCompressedNew() [2/2]
void FArchive::SerializeCompressedNew (void * V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags = COMPRESS_NoFlags, bool bTreatBufferAsFileReader = false, int64 * OutPartialReadLength = nullptr)
Serializes and compresses/ uncompresses data.
This is a shared helper function for compression support.
call SerializeCompressedNew instead of SerializeCompressed Typically you should not serializing data compressed if it will be packaged or stored in the DDC. Prefer to allow the package/iostore system to do the compression for you instead.
SerializeCompressedNew can read existing data written by old SerializeCompressed calls.
Parameters
V Data pointer to serialize data from/ to
Length Length of source data if we're saving, unused otherwise
CompressionFormatToEncode Compression Format to use for encoding, can be changed freely without breaking compatibility
CompressionFormatToDecodeOldV1Files Compression Format to decode old data with that didn't write compressor in header, cannot change, usually NAME_Zlib
Flags Flags to control what method to use for [de]compression and optionally control memory vs speed when compressing
bTreatBufferAsFileReader true if V is actually an FArchive, which is used when saving to read data - helps to avoid single huge allocations of source data
OutPartialReadLength if not null, partial reads are allowed and the size is filled here
References COMPRESS_NoFlags, and Flags.
SerializeInt()
virtual void FArchive::SerializeInt (uint32 & Value, uint32 Max) inline virtual
Reimplemented in FArchiveProxy, FBitReader, and FBitWriter.
Definition at line 1690 of file Archive.h.
References ByteOrderSerialize(), Max, and Value.
SerializeIntPacked()
virtual void FArchive::SerializeIntPacked (uint32 & Value) virtual
Packs int value into bytes of 7 bits with 8th bit for 'more'.
Reimplemented in FArchiveProxy, FBitReader, and FBitWriter.
References Value.
SerializeIntPacked64()
virtual void FArchive::SerializeIntPacked64 (uint64 & Value) virtual
References Value.
SetArchiveState()
void FArchiveState::SetArchiveState (const FArchiveState & InState)
Modifies current archive state, can be used to override flags.
SetByteSwapping()
void FArchiveState::SetByteSwapping (bool Enabled) inline
Toggle byte order swapping.
This is needed in rare cases when we already know that the data swapping has already occurred or if we know that it will be handled later.
Parameters
Enabled set to true to enable byte order swapping
Definition at line 546 of file Archive.h.
SetCompressionMap()
virtual bool FArchive::SetCompressionMap (TArray< FCompressedChunk > * CompressedChunks, ECompressionFlags CompressionFlags) inline virtual
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
If the archive supports dealing with compression in this way it is going to return true.
Parameters
CompressedChunks Pointer to array containing information about [un]compressed chunks
CompressionFlags Flags determining compression format associated with mapping
Returns
true if archive supports translating offsets & uncompressing on read, false otherwise
Reimplemented in FArchiveProxy.
Definition at line 1807 of file Archive.h.
SetCriticalError()
void FArchiveState::SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
Also sets CriticalError in the proxy archiver if one is wrapping this.
Referenced by FLinkerLoad::operator<<().
SetCustomVersion()
void FArchiveState::SetCustomVersion (const struct FGuid & Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
Parameters
Key - The guid of the custom version to query.
Version - The version number to set key to
FriendlyName - Friendly name corresponding to the key
SetCustomVersions()
virtual void FArchiveState::SetCustomVersions (const FCustomVersionContainer & CustomVersionContainer) virtual
Sets the custom version numbers for this archive.
Parameters
CustomVersionContainer - The container of custom versions to copy into the archive.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy.
SetDebugSerializationFlags()
virtual void FArchiveState::SetDebugSerializationFlags (uint32 InCustomFlags) inline virtual
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
Parameters
InCustomFlags the new flags to use for custom serialization
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 566 of file Archive.h.
Referenced by FArchiveProxy::SetDebugSerializationFlags().
SetEngineNetVer()
virtual void FArchiveState::SetEngineNetVer (const uint32 InEngineNetVer) virtual
Sets the archive engine network version.
Reimplemented from FArchiveState.
Reimplemented in FInBunch.
SetEngineVer()
virtual void FArchiveState::SetEngineVer (const FEngineVersionBase & InVer) virtual
Sets the archive engine version.
Used by the code that makes sure that FLinkerLoad's internal archive versions match the file reader it creates.
Parameters
InVer new version number
Reimplemented from FArchiveState.
SetError()
void FArchiveState::SetError ()
Sets ArIsError to true.
Also sets error in the proxy archiver if one is wrapping this.
Referenced by FControlChannelOutBunch::operator<<(), FControlChannelOutBunch::operator<<(), FArrayReader::Serialize(), FMemoryReader::Serialize(), FMemoryReaderView::Serialize(), FObjectReader::Serialize(), and FStaticMemoryReader::Serialize().
SetFilterEditorOnly()
virtual void FArchiveState::SetFilterEditorOnly (bool InFilterEditorOnly) inline virtual
Sets a flag indicating that this archive needs to filter editor-only content.
Parameters
InFilterEditorOnly Whether to filter editor-only content.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, and FLinkerSave.
Definition at line 588 of file Archive.h.
Referenced by FArchiveProxy::SetFilterEditorOnly().
SetForceUnicode()
virtual void FArchiveState::SetForceUnicode (bool bInForceUnicode) virtual
Sets whether this archive wants to force saving as Unicode.
This is needed when we need to make sure ANSI strings are saved as Unicode.
Parameters
bInForceUnicode true if this archive wants to force saving as Unicode, false otherwise.
Reimplemented from FArchiveState.
SetGameNetVer()
virtual void FArchiveState::SetGameNetVer (const uint32 InGameNetVer) virtual
Sets the archive game network version.
Reimplemented from FArchiveState.
Reimplemented in FInBunch.
SetIsLoading()
virtual void FArchiveState::SetIsLoading (bool bInIsLoading) virtual
Sets whether this archive is for loading data.
Parameters
bInIsLoading true if this archive is for loading, false otherwise.
Reimplemented from FArchiveState.
Referenced by FArchiveMD5::FArchiveMD5(), FArrayReader::FArrayReader(), FBufferReaderBase::FBufferReaderBase(), FMemoryReader::FMemoryReader(), FMemoryReaderView::FMemoryReaderView(), FObjectReader::FObjectReader(), FObjectReader::FObjectReader(), and FStaticMemoryReader::FStaticMemoryReader().
SetIsLoadingFromCookedPackage()
virtual void FArchiveState::SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage) virtual
Sets whether the archive is loading from a cooked package.
Parameters
bInIsLoadingFromCookedPackage true if this archive is loading from a cooked package, false otherwise
Reimplemented from FArchiveState.
SetIsPersistent()
virtual void FArchiveState::SetIsPersistent (bool bInIsPersistent) virtual
Sets whether this archive is to persistent storage.
Parameters
bInIsPersistent true if this archive is to persistent storage, false otherwise.
Reimplemented from FArchiveState.
Referenced by FArchiveMD5::FArchiveMD5(), FArchiveScriptReferenceCollector::FArchiveScriptReferenceCollector(), FArrayReader::FArrayReader(), FBufferReaderBase::FBufferReaderBase(), FBulkDataWriter::FBulkDataWriter(), FMemoryReader::FMemoryReader(), FMemoryReaderView::FMemoryReaderView(), FObjectReader::FObjectReader(), FObjectReader::FObjectReader(), TMemoryHasher< FSHA1, FSHAHash >::TMemoryHasher(), and TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >< 32 >::TMemoryWriterBase().
SetIsSaving()
virtual void FArchiveState::SetIsSaving (bool bInIsSaving) virtual
Sets whether this archive is for saving data.
Parameters
bInIsSaving true if this archive is for saving, false otherwise.
Reimplemented from FArchiveState.
Referenced by FArchiveMD5::FArchiveMD5(), FBufferWriter::FBufferWriter(), FBulkDataWriter::FBulkDataWriter(), FSoftObjectPathFixupArchive::FSoftObjectPathFixupArchive(), FTransactionallySafeArchiveWriter::FTransactionallySafeArchiveWriter(), TMemoryHasher< FSHA1, FSHAHash >::TMemoryHasher(), and TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >< 32 >::TMemoryWriterBase().
SetIsTextFormat()
virtual void FArchiveState::SetIsTextFormat (bool bInIsTextFormat) virtual
Sets whether this archive is in text format.
Parameters
bInIsTextFormat true if this archive is in text format, false otherwise.
Reimplemented from FArchiveState.
SetIsTransacting()
virtual void FArchiveState::SetIsTransacting (bool bInIsTransacting) virtual
Sets whether this archive is for transacting.
Parameters
bInIsTransacting true if this archive is for transacting, false otherwise.
Reimplemented from FArchiveState.
Referenced by FTransaction::FObjectRecord::FReader::FReader(), and FTransaction::FObjectRecord::FWriter::FWriter().
SetLicenseeUEVer()
virtual void FArchiveState::SetLicenseeUEVer (int32 InVer) virtual
Sets the archive licensee version number.
Used by the code that makes sure that FLinkerLoad's internal archive versions match the file reader it creates.
Parameters
Ver new version number
Reimplemented from FArchiveState.
SetMigratingRemoteObjects()
void FArchiveState::SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
Parameters
bMigrating Whether this archive is migrating remote objects
SetPortFlags()
void FArchiveState::SetPortFlags (uint32 InPortFlags) inline
Sets the archive's property serialization modifier flags.
Parameters
InPortFlags the new flags to use for property serialization
Definition at line 556 of file Archive.h.
SetSavePackageData()
void FArchiveState::SetSavePackageData (FArchiveSavePackageData * InSavePackageData) inline
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
Must be set only after setting the loading/saving/transacting flags.
Definition at line 628 of file Archive.h.
SetSerializedProperty()
virtual void FArchiveState::SetSerializedProperty (FProperty * InProperty) inline virtual
Overrides the property that is currently being serialized.
Note
: You likely want to call PushSerializedProperty/PopSerializedProperty instead
Parameters
InProperty Pointer to the property that is currently being serialized
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Definition at line 714 of file Archive.h.
Referenced by FArchiveProxy::SetSerializedProperty().
SetSerializedPropertyChain()
virtual void FArchiveState::SetSerializedPropertyChain (const FArchiveSerializedPropertyChain * InSerializedPropertyChain, class FProperty * InSerializedPropertyOverride = nullptr) virtual
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, FLinkerLoad, and FLinkerSave.
Referenced by FArchiveProxy::SetSerializedPropertyChain().
SetShouldSkipCompilingAssets()
void FArchiveState::SetShouldSkipCompilingAssets (bool Enabled) inline protected
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Parameters
Enabled Set to true to enable skip serialization on compiling assets.
Definition at line 310 of file Archive.h.
Referenced by FArchiveReferenceMarker::FArchiveReferenceMarker(), and FSoftObjectPathFixupArchive::FSoftObjectPathFixupArchive().
SetShouldSkipUpdateCustomVersion()
void FArchiveState::SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
Querying the version registry is not cheap, and the look up time increases as more custom versions are registered, therefore if you don't change the registered custom version data once is set in the archive Setting this to true should improve serialization performance by skipping the step entirely.
Parameters
bShouldSkip Whether we should skip the checking the version registry for new version data if the version key is already set
SetUEVer()
virtual void FArchiveState::SetUEVer (FPackageFileVersion InVer) virtual
Sets the archive version number.
Used by the code that makes sure that FLinkerLoad's internal archive versions match the file reader it creates.
Parameters
UEVer new version number
Reimplemented from FArchiveState.
SetUseUnversionedPropertySerialization()
virtual void FArchiveState::SetUseUnversionedPropertySerialization (bool bInUseUnversioned) virtual
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Reimplemented from FArchiveState.
Reimplemented in FLinkerSave.
SetWantBinaryPropertySerialization()
virtual void FArchiveState::SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization) virtual
Sets whether this archive wants binary property serialization.
Parameters
bInWantBinaryPropertySerialization true if this archive wants binary serialization, false otherwise.
Reimplemented from FArchiveState.
Referenced by FTransaction::FObjectRecord::FReader::FReader(), and FTransaction::FObjectRecord::FWriter::FWriter().
ShouldSkipBulkData()
FORCEINLINE bool FArchiveState::ShouldSkipBulkData () const inline
Returns true if this archive should ignore bulk data.
Definition at line 502 of file Archive.h.
ShouldSkipCompilingAssets()
FORCEINLINE bool FArchiveState::ShouldSkipCompilingAssets () const inline
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Definition at line 318 of file Archive.h.
ShouldSkipProperty()
virtual bool FArchiveState::ShouldSkipProperty (const FProperty * InProperty) const inline virtual
Checks whether the archive wants to skip the property independent of the other flags.
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy, FLinkerSave, and UE::Transaction::FDiffableObjectDataWriter.
Definition at line 703 of file Archive.h.
ShouldSkipUpdateCustomVersion()
FORCEINLINE bool FArchiveState::ShouldSkipUpdateCustomVersion () const inline
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
Definition at line 331 of file Archive.h.
StartSerializingDefaults()
void FArchive::StartSerializingDefaults () inline
Sets a flag indicating that this archive is currently serializing class/struct defaults.
Definition at line 1893 of file Archive.h.
References ArSerializingDefaults.
StopSerializingDefaults()
void FArchive::StopSerializingDefaults () inline
Indicate that this archive is no longer serializing class/struct defaults.
Definition at line 1899 of file Archive.h.
References ArSerializingDefaults.
Tell()
virtual int64 FArchiveState::Tell () inline virtual
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
If this returns -1, there is no backing data storage and Seek will not function.
Reimplemented from FArchiveState.
Reimplemented in FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveLoadCompressedProxy, FArchiveProxy, FArchiveSaveCompressedProxy, FBufferReaderBase, FBufferWriter, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FLinkerLoad, FLinkerSave, FMaterialResourceProxyReader, FMemoryArchive, FPreloadableArchive, FPreloadableArchiveProxy, FRigVMObjectArchiveWriter, FTransactionallySafeArchiveWriter, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::Internal::FSerializedObjectDataWriterCommon.
Definition at line 149 of file Archive.h.
Referenced by FArchive::FScopeSeekTo::FScopeSeekTo().
ThisContainsCode()
void FArchiveState::ThisContainsCode () inline
Sets a flag indicating that this archive contains native or generated code.
Definition at line 180 of file Archive.h.
ThisContainsMap()
void FArchiveState::ThisContainsMap () inline
Sets a flag indicating that this archive contains a ULevel or UWorld object.
Definition at line 186 of file Archive.h.
ThisRequiresLocalizationGather()
void FArchiveState::ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
TotalSize()
virtual int64 FArchiveState::TotalSize () inline virtual
Returns total size of the backing data storage.
Reimplemented from FArchiveState.
Reimplemented in FArchiveFileReaderGeneric, FArchiveFileWriterGeneric, FArchiveProxy, FArrayReader, FBufferReaderBase, FBufferWriter, FBulkDataWriter, FDuplicateDataReader, FDuplicateDataWriter, FLargeMemoryReader, FLargeMemoryWriter, FLinkerLoad, FMemoryReader, FMemoryReaderView, FObjectReader, FPreloadableArchive, FPreloadableArchiveProxy, FRigVMObjectArchiveWriter, FStaticMemoryReader, TMemoryHasher< HashBuilder, HashDigest >, TMemoryHasher< FBlake3, FBlake3Hash >, TMemoryHasher< FSHA1, FSHAHash >, TMemoryWriterBase< ArrayAllocatorType >, TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >, UE::Transaction::FSerializedObjectDataReader, and UE::Transaction::Internal::FSerializedObjectDataWriterCommon.
Definition at line 155 of file Archive.h.
UE_DEPRECATED() [1/2]
FArchive::UE_DEPRECATED (5. 5, "Use GetCookContext or CookingTarget or GetSavePackageData") inline
Definition at line 2018 of file Archive.h.
References check.
UE_DEPRECATED() [2/2]
FArchive::UE_DEPRECATED (5. 5, "Use SetSavePackageData.") inline
Definition at line 2008 of file Archive.h.
References check.
UEVer()
FORCEINLINE FPackageFileVersion FArchiveState::UEVer () const inline
Returns the global engine serialization version used for this archive.
Definition at line 204 of file Archive.h.
Referenced by UE::Math::operator<<(), and UE::Math::operator<<().
UnlinkProxy()
void FArchiveState::UnlinkProxy (FArchiveState & Inner, FArchiveState & Proxy) static protected
UseToResolveEnumerators()
virtual bool FArchiveState::UseToResolveEnumerators () const inline virtual
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
Returns
true if the archive is used to resolve out-of-date enum indexes
Reimplemented from FArchiveState.
Reimplemented in FArchiveProxy.
Definition at line 695 of file Archive.h.
UseUnversionedPropertySerialization()
FORCEINLINE bool FArchiveState::UseUnversionedPropertySerialization () const inline
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Definition at line 285 of file Archive.h.
UsingCustomVersion()
virtual void FArchive::UsingCustomVersion (const struct FGuid & Guid) virtual
Registers the custom version to the archive.
This is used to inform the archive that custom version information is about to be stored. There is no effect when the archive is being loaded from.
Parameters
Guid The guid of the custom version. This must have previously been registered with FCustomVersionRegistration.
Reimplemented in FLinkerSave.
References FArchiveState::CustomVer(), and Guid.
WantBinaryPropertySerialization()
FORCEINLINE bool FArchiveState::WantBinaryPropertySerialization () const inline
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Definition at line 276 of file Archive.h.
Friends And Related Symbol Documentation
operator<< [1/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, ANSICHAR & Value) friend
Serializes an ANSICHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1360 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [2/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, bool & D) friend
Definition at line 1500 of file Archive.h.
References FArchive(), Ar, and FORCEINLINE.
operator<< [3/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, double & Value) friend
Serializes a double precision floating point value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1607 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [4/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, float & Value) friend
Serializes a single precision floating point value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1589 of file Archive.h.
References FArchive(), Ar, float, FORCEINLINE, and Value.
operator<< [5/15]
FArchive & operator<< (FArchive & Ar, FString & Value) friend
Serializes an FString value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
References FArchive(), Ar, and Value.
operator<< [6/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int16 & Value) friend
Serializes a signed 16-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1462 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [7/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int32 & Value) friend
Serializes a signed 32-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1553 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [8/15]
FArchive & operator<< (FArchive & Ar, int64 & Value) friend
Serializes a signed 64-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1642 of file Archive.h.
References FArchive(), Ar, and Value.
operator<< [9/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int8 & Value) friend
Serializes a signed 8-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1428 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [10/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint16 & Value) friend
Serializes an unsigned 16-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1445 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [11/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint32 & Value) friend
Serializes an unsigned 32-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1479 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [12/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint64 & Value) friend
Serializes a unsigned 64-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1625 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [13/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint8 & Value) friend
Serializes an unsigned 8-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1411 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [14/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, UTF32CHAR & Value) friend
Serializes a UTF32CHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1394 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
operator<< [15/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, WIDECHAR & Value) friend
Serializes a WIDECHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 1377 of file Archive.h.
References FArchive(), Ar, FORCEINLINE, and Value.
Field Documentation
ActiveFPLB
FFastPathLoadBuffer* FArchiveState::ActiveFPLB
Definition at line 799 of file Archive.h.
Referenced by FastPathLoad().
ArAllowLazyLoading
uint8 FArchiveState::ArAllowLazyLoading
Whether to allow lazy loading of bulk/secondary data.
Definition at line 888 of file Archive.h.
ArContainsCode
uint8 FArchiveState::ArContainsCode
Quickly tell if an archive contains script code.
Definition at line 857 of file Archive.h.
ArContainsMap
uint8 FArchiveState::ArContainsMap
Used to determine whether FArchive contains a level or world.
Definition at line 860 of file Archive.h.
ArCustomPropertyList
const struct FCustomPropertyListNode* FArchiveState::ArCustomPropertyList
Custom property list attribute.
If the flag below is set, only these properties will be iterated during serialization. If NULL, then no properties will be iterated.
Definition at line 1042 of file Archive.h.
ArDebugSerializationFlags
uint32 FArchiveState::ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
Definition at line 1046 of file Archive.h.
ArEngineVer
FEngineVersionBase FArchiveState::ArEngineVer private
Holds the engine version.
Definition at line 1031 of file Archive.h.
ArForceByteSwapping
UE_DEPRECATED (5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 FArchiveState::ArForceByteSwapping
Used to determine whether FArchive contains data required to be gathered for localization.
Whether we should forcefully swap bytes.
Definition at line 867 of file Archive.h.
ArForceUnicode
uint8 FArchiveState::ArForceUnicode private
Whether this archive wants to always save strings in UTF16 format even if they are ANSI characters.
Definition at line 830 of file Archive.h.
ArIgnoreArchetypeRef
uint8 FArchiveState::ArIgnoreArchetypeRef
If true, we will not serialize archetype references for structs and classes.
Definition at line 870 of file Archive.h.
Referenced by FArchiveScriptReferenceCollector::FArchiveScriptReferenceCollector(), FObjectReader::FObjectReader(), FObjectReader::FObjectReader(), FObjectWriter::FObjectWriter(), and FObjectWriter::FObjectWriter().
ArIgnoreClassGeneratedByRef
uint8 FArchiveState::ArIgnoreClassGeneratedByRef
If true, we will not serialize ClassGeneratedBy reference in UClass.
Definition at line 882 of file Archive.h.
ArIgnoreClassRef
uint8 FArchiveState::ArIgnoreClassRef
If true, UObject::Serialize will skip serialization of the Class property.
Definition at line 885 of file Archive.h.
Referenced by FObjectReader::FObjectReader(), FObjectReader::FObjectReader(), FObjectWriter::FObjectWriter(), and FObjectWriter::FObjectWriter().
ArIgnoreOuterRef
uint8 FArchiveState::ArIgnoreOuterRef
If true, we will not serialize the Outer reference in UObject.
Definition at line 879 of file Archive.h.
Referenced by FArchiveReferenceMarker::FArchiveReferenceMarker().
ArIsCountingMemory
uint8 FArchiveState::ArIsCountingMemory
Whether this archive is counting memory.
Definition at line 897 of file Archive.h.
Referenced by FArchiveCountMem::FArchiveCountMem().
ArIsFilterEditorOnly
uint8 FArchiveState::ArIsFilterEditorOnly
Whether editor only properties are being filtered from the archive (or has been filtered).
Definition at line 903 of file Archive.h.
Referenced by FArchiveCountMem::FArchiveCountMem(), and FPropertyProxyArchive::FPropertyProxyArchive().
ArIsLoading
uint8 FArchiveState::ArIsLoading private
Whether this archive is for loading data.
Definition at line 809 of file Archive.h.
ArIsLoadingFromCookedPackage
uint8 FArchiveState::ArIsLoadingFromCookedPackage private
Whether this archive is loading from a cooked package.
Definition at line 812 of file Archive.h.
ArIsModifyingWeakAndStrongReferences
uint8 FArchiveState::ArIsModifyingWeakAndStrongReferences
Whether a reference collector is modifying the references and wants both weak and strong ones.
Definition at line 894 of file Archive.h.
ArIsNetArchive
uint8 FArchiveState::ArIsNetArchive
Whether or not this archive is sending/receiving network data.
Definition at line 909 of file Archive.h.
ArIsObjectReferenceCollector
uint8 FArchiveState::ArIsObjectReferenceCollector
Whether this archive only cares about serializing object references.
Definition at line 891 of file Archive.h.
Referenced by FArchiveObjectPropertyMapper::FArchiveObjectPropertyMapper(), FArchiveReferenceMarker::FArchiveReferenceMarker(), and FArchiveScriptReferenceCollector::FArchiveScriptReferenceCollector().
ArIsPersistent
uint8 FArchiveState::ArIsPersistent private
Whether this archive saves to persistent storage.
This is also true for some intermediate archives like DuplicateObject that are expected to go to persistent storage but may be discarded
Definition at line 833 of file Archive.h.
ArIsSaveGame
uint8 FArchiveState::ArIsSaveGame
Whether this archive is saving/loading game state.
Definition at line 906 of file Archive.h.
ArIsSaving
uint8 FArchiveState::ArIsSaving private
Whether this archive is for saving data.
Definition at line 815 of file Archive.h.
ArIsTextFormat
uint8 FArchiveState::ArIsTextFormat private
Whether this archive serializes to a text format.
Text format archives should use high level constructs from FStructuredArchive for delimiting data rather than manually seeking through the file.
Definition at line 821 of file Archive.h.
ArIsTransacting
uint8 FArchiveState::ArIsTransacting private
Whether archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
Definition at line 818 of file Archive.h.
ArLicenseeUEVer
int32 FArchiveState::ArLicenseeUEVer private
Holds the archive version for licensees.
Definition at line 1028 of file Archive.h.
ArMaxSerializeSize
int64 FArchiveState::ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
Definition at line 927 of file Archive.h.
ArMergeOverrides
uint8 FArchiveState::ArMergeOverrides
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
Definition at line 915 of file Archive.h.
ArNoDelta
uint8 FArchiveState::ArNoDelta
If true, do not perform delta serialization of properties.
Definition at line 873 of file Archive.h.
Referenced by FObjectWriter::FObjectWriter().
ArNoIntraPropertyDelta
uint8 FArchiveState::ArNoIntraPropertyDelta
If true, do not perform delta serialization within properties (e.g.
TMaps and TSets).
Definition at line 876 of file Archive.h.
ArPortFlags
uint32 FArchiveState::ArPortFlags
Modifier flags that be used when serializing UProperties.
Definition at line 924 of file Archive.h.
Referenced by FObjectReader::FObjectReader(), and FObjectWriter::FObjectWriter().
ArPreserveArrayElements
uint8 FArchiveState::ArPreserveArrayElements
Set TRUE to stop arrays from being cleared before they're loaded.
Instead, array data will be merged
Definition at line 918 of file Archive.h.
ArSerializingDefaults
int32 FArchiveState::ArSerializingDefaults
Whether we are currently serializing defaults.
> 0 means yes, <= 0 means no.
Definition at line 921 of file Archive.h.
Referenced by StartSerializingDefaults(), and StopSerializingDefaults().
ArShouldSkipBulkData
uint8 FArchiveState::ArShouldSkipBulkData
Whether bulk data serialization should be skipped or not.
Definition at line 900 of file Archive.h.
Referenced by FSoftObjectPathFixupArchive::FSoftObjectPathFixupArchive().
ArUEVer
FPackageFileVersion FArchiveState::ArUEVer private
Holds the archive version.
Definition at line 1025 of file Archive.h.
ArUseCustomPropertyList
uint8 FArchiveState::ArUseCustomPropertyList
Set TRUE to use the custom property list attribute for serialization.
Definition at line 912 of file Archive.h.
ArUseUnversionedPropertySerialization
uint8 FArchiveState::ArUseUnversionedPropertySerialization private
Whether tagged property serialization is replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Definition at line 827 of file Archive.h.
ArWantBinaryPropertySerialization
uint8 FArchiveState::ArWantBinaryPropertySerialization private
Whether this archive wants properties to be serialized in binary form instead of tagged.
Definition at line 824 of file Archive.h.
bCustomVersionsAreReset
bool FArchiveState::bCustomVersionsAreReset mutable private
Indicates if the custom versions container is in a 'reset' state.
This will be used to defer the choice about how to populate the container until it is needed, where the read/write state will be known.
Definition at line 1082 of file Archive.h.
CustomVersionContainer
FCustomVersionContainer* FArchiveState::CustomVersionContainer mutable private
All the custom versions stored in the archive.
Stored as a pointer to a heap-allocated object because of a 3-way dependency between TArray, FCustomVersionContainer and FArchive, which is too much work to change right now. Keeping it as a heap-allocated object also helps with performance in some cases as we don't need to construct it for archives that don't care about custom versions.
Definition at line 1038 of file Archive.h.
InlineFPLB
FFastPathLoadBuffer FArchiveState::InlineFPLB
Definition at line 800 of file Archive.h.
SerializedProperty
FProperty* FArchiveState::SerializedProperty private
Holds the pointer to the property that is currently being serialized.
Definition at line 1058 of file Archive.h.
SerializedPropertyChain
FArchiveSerializedPropertyChain* FArchiveState::SerializedPropertyChain private
Holds the chain of properties that are currently being serialized.
Definition at line 1061 of file Archive.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/Archive.h