Unreal Engine 5.6 C++ API: FGCObject Class Reference
FGCObject Class Reference abstract
This class provides common registration for garbage collection for non-UObject classes.
#include "GCObject.h"
Public Types
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Public Member Functions
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual void AddReferencedObjects (FReferenceCollector &Collector)=0
Pure virtual that must be overloaded by the inheriting class.
virtual FString GetReferencerName () const =0
Overload this method to report a name for your referencer.
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Public Member Functions
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Private Attributes
const bool bCanMakeInitialReferences = false
bool bReferenceAdded = false
friend UGCObjectReferencer
Static Private Attributes
static const TCHAR * UnknownGCObjectName
Detailed Description
This class provides common registration for garbage collection for non-UObject classes.
It is an abstract base class requiring you to implement the AddReferencedObjects() method.
Definition at line 113 of file GCObject.h.
Member Enumeration Documentation
EFlags
enum class FGCObject::EFlags : uint32 strong
Enumerator
None
RegisterLater
Manually call RegisterGCObject() later to avoid collecting references from empty / late-initialized FGCObjects.
AddStableNativeReferencesOnly
Declare that AddReferencedObjects only calls FReferenceCollector::AddStableReference*() functions instead of the older FReferenceCollector::AddReferenceObject*() and only adds native references.
Allows gathering initial references before reachability analysis starts.
Definition at line 144 of file GCObject.h.
Constructor & Destructor Documentation
FGCObject() [1/4]
FGCObject::FGCObject () inline
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
Definition at line 129 of file GCObject.h.
References RegisterGCObject().
Referenced by FGCObject(), FGCObject(), operator=(), and operator=().
FGCObject() [2/4]
FGCObject::FGCObject (const FGCObject & Other) inline
Definition at line 134 of file GCObject.h.
References FGCObject(), Other, and RegisterGCObject().
FGCObject() [3/4]
FGCObject::FGCObject (FGCObject && Other) inline
Definition at line 139 of file GCObject.h.
References FGCObject(), Other, and RegisterGCObject().
FGCObject() [4/4]
FORCEINLINE_DEBUGGABLE FGCObject::FGCObject (EFlags Flags) explicit
Definition at line 202 of file GCObject.h.
References AddStableNativeReferencesOnly, bCanMakeInitialReferences, EnumHasAllFlags(), EnumHasAnyFlags(), Flags, FORCEINLINE_DEBUGGABLE, RegisterGCObject(), and RegisterLater.
~FGCObject()
virtual FGCObject::~FGCObject () inline virtual
Definition at line 161 of file GCObject.h.
References UnregisterGCObject().
Member Function Documentation
AddReferencedObjects()
virtual void FGCObject::AddReferencedObjects (FReferenceCollector & Collector) pure virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implemented in Audio::FSoundWavePCMLoader, ConstructorHelpers::FClassFinder< T >, ConstructorHelpers::FObjectFinder< T >, ConstructorHelpers::FObjectFinderOptional< T >, FActorFolders, FAssetEditorToolkit::FGCEditingObjects, FBlueprintActionDatabase, FBlueprintCompileReinstancer, FBlueprintEditor, FBlueprintNodeTemplateCache, FCameraShakePreviewer, FDataflowConnectionDrawingPolicy, FDataflowConstructionViewportClient, FDataflowEditorToolkit, FDataflowEditorViewportClientBase, FDataflowNodeView, FDataflowSkeletonView, FDebugCanvasDrawer, FDeferredCleanupSlateBrush, FEditorModeTools, FEditorStateCollectionGCObject, FEditorViewportClient, FEdMode, FFindReferencedAssets, FForceFeedbackManager, FFractureEditorModeToolkit, FGraphSelectionManager, FGridWidget, FLevelEditorDragDropWorldSurrogateReferencingObject, FLevelEditorViewportClient, FMediaThumbnailSection, FOverridableManager, FParticleSystemWorldManager, FPhysicsDebugMode, FPhysicsManipulationEdMode, FPreviewScene, FReimportManager, FRepLayout, FRigVMNewEditor, FRigVMRegistry_NoLock, FSequencerKeyStructGenerator, FSlateDrawBuffer, FSlateGameResources, FSlateInvalidationRoot, FSMInstanceElementIdMap, FStandaloneCompositeFont, FStreamableManager, FSubsystemCollection< TBaseType >, FSubsystemCollection< UAudioEngineSubsystem >, FViewport::FHitProxyMap, FWidget, FWidgetBlueprintEditor, FWorldGridPreviewer, IPersonaEditorModeManager, ObjectTools::FConsolidationResults, SDataflowEdNode, SDataflowGraphEditor, SDesignerView, SGraphActionMenu, SGraphPanel, SKismetInspector, SRigVMDetailsInspector, TGCObjectScopeGuard< ObjectType >, TGCObjectScopeGuard< const UObject >, TGCObjectsScopeGuard< ObjectType >, TWidgetFactory< WidgetType >, TWidgetFactory< UUserWidget >, UE::CurveEditor::FPromotedFilterContainer, UE::CurveEditor::FTransactionManager, UE::MovieScene::FSequenceDirectorPlaybackCapability::FDirectorInstanceCache, UE::MovieScene::FSystemInterrogator, and UE::Sequencer::FCommonAnimationTrackEditor.
GetReferencerName()
virtual FString FGCObject::GetReferencerName () const pure virtual
Overload this method to report a name for your referencer.
Implemented in Audio::FSoundWavePCMLoader, ConstructorHelpers::FClassFinder< T >, ConstructorHelpers::FObjectFinder< T >, ConstructorHelpers::FObjectFinderOptional< T >, FActorFolders, FAssetEditorToolkit::FGCEditingObjects, FBlueprintActionDatabase, FBlueprintCompileReinstancer, FBlueprintEditor, FBlueprintNodeTemplateCache, FCameraShakePreviewer, FDataflowConnectionDrawingPolicy, FDataflowConstructionViewportClient, FDataflowEditorToolkit, FDataflowNodeView, FDataflowSimulationViewportClient, FDebugCanvasDrawer, FDeferredCleanupSlateBrush, FEditorModeTools, FEditorStateCollectionGCObject, FEditorViewportClient, FEdMode, FFindReferencedAssets, FForceFeedbackManager, FFractureEditorModeToolkit, FGraphSelectionManager, FGridWidget, FLevelEditorDragDropWorldSurrogateReferencingObject, FMediaThumbnailSection, FOverridableManager, FParticleSystemWorldManager, FPhysicsManipulationEdMode, FPreviewScene, FReimportManager, FRepLayout, FRigVMNewEditor, FRigVMRegistry_NoLock, FSequencerKeyStructGenerator, FSlateDrawBuffer, FSlateGameResources, FSlateInvalidationRoot, FSMInstanceElementIdMap, FStandaloneCompositeFont, FStreamableManager, FSubsystemCollection< TBaseType >, FSubsystemCollection< UAudioEngineSubsystem >, FViewport::FHitProxyMap, FWidget, FWorldGridPreviewer, ObjectTools::FConsolidationResults, SDataflowEdNode, SDataflowGraphEditor, SDesignerView, SGraphActionMenu, SGraphPanel, SKismetInspector, SRigVMDetailsInspector, TGCObjectScopeGuard< ObjectType >, TGCObjectScopeGuard< const UObject >, TGCObjectsScopeGuard< ObjectType >, TWidgetFactory< WidgetType >, TWidgetFactory< UUserWidget >, UE::CurveEditor::FPromotedFilterContainer, UE::CurveEditor::FTransactionManager, UE::MovieScene::FSequenceDirectorPlaybackCapability::FDirectorInstanceCache, UE::MovieScene::FSystemInterrogator, and UE::Sequencer::FCommonAnimationTrackEditor.
GetReferencerPropertyName()
virtual bool FGCObject::GetReferencerPropertyName (UObject * Object, FString & OutPropertyName) const inline virtual
Overload this method to report how the specified object is referenced, if necessary.
Reimplemented in FStreamableManager.
Definition at line 187 of file GCObject.h.
References Object.
operator=() [1/2]
FGCObject & FGCObject::operator= (const FGCObject &) inline
Definition at line 166 of file GCObject.h.
References FGCObject().
operator=() [2/2]
FGCObject & FGCObject::operator= (FGCObject &&) inline
Definition at line 167 of file GCObject.h.
References FGCObject().
RegisterGCObject()
void FGCObject::RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
Referenced by FGCObject(), FGCObject(), FGCObject(), and FGCObject().
StaticInit()
void FGCObject::StaticInit () static
Initializes the global object referencer and adds it to the root set.
UnregisterGCObject()
void FGCObject::UnregisterGCObject ()
Unregister ahead of destruction.
Safe to call multiple times.
Referenced by ~FGCObject().
Field Documentation
bCanMakeInitialReferences
const bool FGCObject::bCanMakeInitialReferences = false private
Definition at line 196 of file GCObject.h.
Referenced by FGCObject().
bReferenceAdded
bool FGCObject::bReferenceAdded = false private
Definition at line 197 of file GCObject.h.
GGCObjectReferencer
UGCObjectReferencer* FGCObject::GGCObjectReferencer static
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Definition at line 120 of file GCObject.h.
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray().
UGCObjectReferencer
friend FGCObject::UGCObjectReferencer private
Definition at line 193 of file GCObject.h.
UnknownGCObjectName
const TCHAR* FGCObject::UnknownGCObjectName static private
Definition at line 194 of file GCObject.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/GCObject.h