Unreal Engine 5.6 C++ API: UKismetMathLibrary Class Reference
UKismetMathLibrary Class Reference
#include "KismetMathLibrary.h"
Private Member Functions
DECLARE_FUNCTION (execPercent_FloatFloat)
Custom thunk to allow script stack trace in case of modulo by zero.
GENERATED_UCLASS_BODY () UFUNCTION()) static bool RandomBool()
Returns a uniformly distributed random bool.
UE_DEPRECATED (5.2, "This method has been deprecated and will be removed. Use the double version instead.") static FLinearColor Conv_FloatToLinearColor(float InFloat)
Converts a float into a LinearColor, where each element is a float.
UE_DEPRECATED (5.2, "This method has been deprecated and will be removed. Use the double version instead.") static float Conv_BoolToFloat(bool InBool)
Converts a bool to a float (0.0f or 1.0f)
UE_DEPRECATED (5.2, "This method has been deprecated and will be removed. Use the double version instead.") static float Conv_ByteToFloat(uint8 InByte)
Converts a byte to a float.
UE_DEPRECATED (5.2, "This method has been deprecated and will be removed. Use the double version instead.") static float Conv_IntToFloat(int32 InInt)
Converts an integer to a float.
UE_DEPRECATED (5.2, "This method has been deprecated and will be removed. Use the double version instead.") static FVector Conv_FloatToVector(float InFloat)
Converts a float into a vector, where each element is that float.
UE_DEPRECATED (5.2, "Use RandomBoolWithWeightFromStream taking the FRandomStream as the first argument.") static bool RandomBoolWithWeightFromStream(float Weight
UE_DEPRECATED (5.2, "Use RandomFloatInRangeFromStream taking the FRandomStream as the first argument.") static float RandomFloatInRangeFromStream(float Min
UE_DEPRECATED (5.2, "Use RandomIntegerFromStream taking the FRandomStream as the first argument.") static int32 RandomIntegerFromStream(int32 Max
UE_DEPRECATED (5.2, "Use RandomIntegerInRangeFromStream taking the FRandomStream as the first argument.") static int32 RandomIntegerInRangeFromStream(int32 Min
UE_DEPRECATED (5.2, "Use RandomPointInBoundingBoxFromStream taking the FRandomStream as the first argument.") static FVector RandomPointInBoundingBoxFromStream(const FVector Center
UE_DEPRECATED (5.2, "Use RandomPointInBoundingBoxFromStream_Box taking the FRandomStream as the first argument.") static FVector RandomPointInBoundingBoxFromStream_Box(const FBox Box
UE_DEPRECATED (5.2, "Use RandomRotatorFromStream taking the FRandomStream as the first argument.") static FRotator RandomRotatorFromStream(bool bRoll
UE_DEPRECATED (5.2, "Use RandomUnitVectorInConeInDegreesFromStream taking the FRandomStream as the first argument.") static inline FVector RandomUnitVectorInConeInDegreesFromStream(const FVector &ConeDir
UE_DEPRECATED (5.2, "Use RandomUnitVectorInConeInRadiansFromStream taking the FRandomStream as the first argument.") static FVector RandomUnitVectorInConeInRadiansFromStream(const FVector &ConeDir
UE_DEPRECATED (5.2, "Use RandomUnitVectorInEllipticalConeInDegreesFromStream taking the FRandomStream as the first argument.") static inline FVector RandomUnitVectorInEllipticalConeInDegreesFromStream(const FVector &ConeDir
UE_DEPRECATED (5.2, "Use RandomUnitVectorInEllipticalConeInRadiansFromStream taking the FRandomStream as the first argument.") static FVector RandomUnitVectorInEllipticalConeInRadiansFromStream(const FVector &ConeDir
UE_DEPRECATED (5.3, "This method has been deprecated and will be removed. Use the double version instead.") static void BreakVector3f(FVector3f InVec
UFUNCTION ()
Returns the logical complement of the Boolean value (NOT A)
UFUNCTION ()
Returns the logical AND of two values (A AND B)
UFUNCTION ()
Returns the logical NAND of two values (A AND B)
UFUNCTION ()
Returns the logical OR of two values (A OR B)
UFUNCTION ()
Returns the logical eXclusive OR of two values (A XOR B)
UFUNCTION ()
Returns the logical Not OR of two values (A NOR B)
UFUNCTION ()
Multiplication (A * B)
UFUNCTION ()
Division (A / B)
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Returns true if A is less than B (A < B)
UFUNCTION ()
Returns true if A is greater than B (A > B)
UFUNCTION ()
Returns true if A is less than or equal to B (A <= B)
UFUNCTION ()
Returns true if A is greater than or equal to B (A >= B)
UFUNCTION ()
Multiplication (A * B)
UFUNCTION ()
Division (A / B)
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Returns true if A is less than B (A < B)
UFUNCTION ()
Returns true if A is greater than B (A > B)
UFUNCTION ()
Returns true if A is less than or equal to B (A <= B)
UFUNCTION ()
Returns true if A is greater than or equal to B (A >= B)
UFUNCTION ()
Bitwise AND (A & B)
UFUNCTION ()
Bitwise XOR (A ^ B)
UFUNCTION ()
Bitwise OR (A | B)
UFUNCTION ()
Bitwise NOT (~A)
UFUNCTION ()
Multiplication (A * B)
UFUNCTION ()
Division (A / B)
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Returns true if A is less than B (A < B)
UFUNCTION ()
Returns true if A is greater than B (A > B)
UFUNCTION ()
Returns true if A is less than or equal to B (A <= B)
UFUNCTION ()
Returns true if A is greater than or equal to B (A >= B)
UFUNCTION ()
Bitwise AND (A & B)
UFUNCTION ()
Bitwise XOR (A ^ B)
UFUNCTION ()
Bitwise OR (A | B)
UFUNCTION ()
Bitwise NOT (~A)
UFUNCTION ()
Power (Base to the Exp-th power)
UFUNCTION ()
Multiplication (A * B)
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Multiplication (A * B)
UFUNCTION ()
Division (A / B)
UFUNCTION ()
Returns true if A is Less than B (A < B)
UFUNCTION ()
Returns true if A is greater than B (A > B)
UFUNCTION ()
Returns true if A is Less than or equal to B (A <= B)
UFUNCTION ()
Returns true if A is greater than or equal to B (A >= B)
UFUNCTION ()
Returns the hypotenuse of a right-angled triangle given the width and height.
UFUNCTION ()
Returns the value of PI.
UFUNCTION ()
Returns the value of TAU (= 2 * PI)
UFUNCTION ()
Returns radians value based on the input degrees.
UFUNCTION ()
Returns degrees value based on the input radians.
UFUNCTION ()
Clamps an arbitrary angle to be between the given angles.
UFUNCTION ()
Easeing between A and B using a specified easing function.
UFUNCTION ()
Rounds A down towards negative infinity / down to the previous integer (e.g., -1.6 becomes -2 and 1.6 becomes 1)
UFUNCTION ()
Rounds A towards zero, truncating the fractional part (e.g., -1.6 becomes -1 and 1.6 becomes 1)
UFUNCTION ()
Rounds A to the nearest integer (e.g., -1.6 becomes -2 and 1.6 becomes 2)
UFUNCTION ()
Rounds A down towards negative infinity / down to the previous integer (e.g., -1.6 becomes -2 and 1.6 becomes 1)
UFUNCTION ()
Rounds A towards zero, truncating the fractional part (e.g., -1.6 becomes -1 and 1.6 becomes 1)
UFUNCTION ()
Rounds A up towards positive infinity / up to the next integer (e.g., -1.6 becomes -1 and 1.6 becomes 2)
UFUNCTION ()
Multiplies the input value by pi.
UFUNCTION ()
Zero Int Point (0, 0)
UFUNCTION ()
One Int Point (1, 1)
UFUNCTION ()
Up Int Point (0, -1)
UFUNCTION ()
Left Int Point (-1, 0)
UFUNCTION ()
Right Int Point (1, 0)
UFUNCTION ()
Down Int Point (0, 1)
UFUNCTION ()
Returns IntPoint A added by B.
UFUNCTION ()
Addition (A - B)
UFUNCTION ()
Returns IntPoint A subtracted by B.
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Returns IntPoint A multiplied by B.
UFUNCTION ()
Multiplication (A * B)
UFUNCTION ()
Returns IntPoint A divided by B.
UFUNCTION ()
Division (A * B)
UFUNCTION ()
2D one vector constant (1,1)
UFUNCTION ()
2D unit vector constant along the 45 degree angle or symmetrical positive axes (sqrt(.5),sqrt(.5)) or (.707,.707).
UFUNCTION ()
2D zero vector constant (0,0)
UFUNCTION ()
Returns addition of Vector A and Vector B (A + B)
UFUNCTION ()
Returns Vector A added by B.
UFUNCTION ()
Returns subtraction of Vector B from Vector A (A - B)
UFUNCTION ()
Returns Vector A subtracted by B.
UFUNCTION ()
Element-wise Vector multiplication (Result = {A.x*B.x, A.y*B.y})
UFUNCTION ()
Returns Vector A scaled by B.
UFUNCTION ()
Element-wise Vector divide (Result = {A.x/B.x, A.y/B.y})
UFUNCTION ()
Returns Vector A divided by B.
UFUNCTION ()
Gets a negated copy of the vector.
UFUNCTION ()
Set the values of the vector directly.
UFUNCTION ()
Creates a copy of this vector with both axes clamped to the given range.
UFUNCTION ()
Distance between two 2D points.
UFUNCTION ()
Squared distance between two 2D points.
UFUNCTION ()
Get a copy of this vector with absolute value of each component.
UFUNCTION ()
Get the maximum absolute value of the vector's components.
UFUNCTION ()
Get the maximum value of the vector's components.
UFUNCTION ()
Get the minimum value of the vector's components.
UFUNCTION ()
Rotates around axis (0,0,1)
UFUNCTION ()
Checks whether vector is near to zero within a specified tolerance.
UFUNCTION ()
Checks whether all components of the vector are exactly zero.
UFUNCTION ()
Returns a unit normal version of the 2D vector.
UFUNCTION ()
Converts spherical coordinates on the unit sphere into a Cartesian unit length vector.
UFUNCTION ()
Util to convert this vector into a unit direction vector and its original length.
UFUNCTION ()
Returns the length of a 2D Vector.
UFUNCTION ()
Returns the squared length of a 2D Vector.
UFUNCTION ()
3D vector zero constant (0,0,0)
UFUNCTION ()
3D vector one constant (1,1,1)
UFUNCTION ()
3D vector Unreal forward direction constant (1,0,0)
UFUNCTION ()
3D vector Unreal backward direction constant (-1,0,0)
UFUNCTION ()
3D vector Unreal up direction constant (0,0,1)
UFUNCTION ()
3D vector Unreal down direction constant (0,0,-1)
UFUNCTION ()
3D vector Unreal right direction constant (0,1,0)
UFUNCTION ()
3D vector Unreal left direction constant (0,-1,0)
UFUNCTION ()
Assign the values of the supplied vector.
UFUNCTION ()
Set the values of the vector directly.
UFUNCTION ()
Return the FRotator orientation corresponding to the direction in which the vector points.
UFUNCTION ()
Create a rotation from an axis and supplied angle (in degrees)
UFUNCTION ()
Interpolate from a vector to the direction of another vector along a spherical path.
UFUNCTION ()
Interpolate from normalized vector A to normalized vector B along a spherical path.
UFUNCTION ()
Vector addition.
UFUNCTION ()
Adds a float to each component of a vector.
UFUNCTION ()
Adds an integer to each component of a vector.
UFUNCTION ()
Vector subtraction.
UFUNCTION ()
Subtracts a float from each component of a vector.
UFUNCTION ()
Subtracts an integer from each component of a vector.
UFUNCTION ()
Element-wise Vector multiplication (Result = {A.x*B.x, A.y*B.y, A.z*B.z})
UFUNCTION ()
Scales Vector A by B.
UFUNCTION ()
Scales Vector A by B.
UFUNCTION ()
Element-wise Vector division (Result = {A.x/B.x, A.y/B.y, A.z/B.z})
UFUNCTION ()
Vector divide by a float.
UFUNCTION ()
Vector divide by an integer.
UFUNCTION ()
Negate a vector.
UFUNCTION ()
Returns the dot product of two 3d vectors - see http://mathworld.wolfram.com/DotProduct.html.
UFUNCTION ()
Returns the cross product of two 3d vectors - see http://mathworld.wolfram.com/CrossProduct.html.
UFUNCTION ()
Returns result of vector A rotated by Rotator B.
UFUNCTION ()
Returns result of vector A rotated by AngleDeg around Axis.
UFUNCTION ()
Returns result of vector A rotated by the inverse of Rotator B.
UFUNCTION ()
When this vector contains Euler angles (degrees), ensure that angles are between +/-180.
UFUNCTION ()
Create a copy of this vector, with its magnitude/size/length clamped between Min and Max.
UFUNCTION ()
Create a copy of this vector, with the 2D magnitude/size/length clamped between Min and Max.
UFUNCTION ()
Create a copy of this vector, with its maximum magnitude/size/length clamped to MaxSize.
UFUNCTION ()
Create a copy of this vector, with the maximum 2D magnitude/size/length clamped to MaxSize.
UFUNCTION ()
Find the minimum element (X, Y or Z) of a vector.
UFUNCTION ()
Find the maximum element (X, Y or Z) of a vector.
UFUNCTION ()
Find the maximum absolute element (abs(X), abs(Y) or abs(Z)) of a vector.
UFUNCTION ()
Find the minimum absolute element (abs(X), abs(Y) or abs(Z)) of a vector.
UFUNCTION ()
Get a copy of this vector with absolute value of each component.
UFUNCTION ()
Find the minimum elements (X, Y and Z) between the two vector's components.
UFUNCTION ()
Find the maximum elements (X, Y and Z) between the two vector's components.
UFUNCTION ()
Get a copy of the vector as sign only.
UFUNCTION ()
Projects 2D components of vector based on Z.
UFUNCTION ()
Convert a direction vector into a 'heading' angle.
UFUNCTION ()
Returns the cosine of the angle between this vector and another projected onto the XY plane (no Z).
UFUNCTION ()
Converts a vector containing degree values to a vector containing radian values.
UFUNCTION ()
Converts a vector containing radian values to a vector containing degree values.
UFUNCTION ()
Converts a Cartesian unit vector into spherical coordinates on the unit sphere.
UFUNCTION ()
Returns the length of the vector.
UFUNCTION ()
Returns the squared length of the vector.
UFUNCTION ()
Returns the length of the vector's XY components.
UFUNCTION ()
Returns the squared length of the vector's XY components.
UFUNCTION ()
Checks whether vector is near to zero within a specified tolerance.
UFUNCTION ()
Checks whether all components of the vector are exactly zero.
UFUNCTION ()
Determines if any component is not a number (NAN)
UFUNCTION ()
Gets a normalized unit copy of the vector, ensuring it is safe to do so based on the length.
UFUNCTION ()
Uses a simple spring model to interpolate a vector from Current to Target.
UFUNCTION ()
Uses a simple spring model to interpolate a quaternion from Current to Target.
UFUNCTION ()
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
UFUNCTION ()
Mirrors a vector about a plane.
UFUNCTION ()
Gets a copy of this vector snapped to a grid.
UFUNCTION ()
Get a copy of this vector, clamped inside of an axis aligned cube centered at the origin.
UFUNCTION ()
Add a vector to this and clamp the result to an axis aligned cube centered at the origin.
UFUNCTION ()
Get a copy of this vector, clamped inside of the specified axis aligned cube.
UFUNCTION ()
Gets a copy of this vector projected onto the input vector, which is assumed to be unit length.
UFUNCTION ()
Projects one vector (V) onto another (Target) and returns the projected vector.
UFUNCTION ()
Projects/snaps a point onto a plane defined by a point on the plane and a plane normal.
UFUNCTION ()
Projects a vector onto a plane defined by a normalized vector (PlaneNormal).
UFUNCTION ()
4D vector zero constant (0,0,0)
UFUNCTION ()
Makes a 4D vector {X, Y, Z, W}.
UFUNCTION ()
Breaks a 4D vector apart into X, Y, Z, W.
UFUNCTION ()
Returns addition of Vector A and Vector B (A + B)
UFUNCTION ()
Returns subtraction of Vector B from Vector A (A - B)
UFUNCTION ()
Element-wise Vector multiplication (Result = {A.x*B.x, A.y*B.y, A.z*B.z, A.w*B.w})
UFUNCTION ()
Element-wise Vector divide (Result = {A.x/B.x, A.y/B.y, A.z/B.z, A.w/B.w})
UFUNCTION ()
Assign the values of the supplied vector.
UFUNCTION ()
Set the values of the vector directly.
UFUNCTION ()
Determines if any component is not a number (NAN)
UFUNCTION ()
Checks whether vector is near to zero within a specified tolerance.
UFUNCTION ()
Checks whether all components of the vector are exactly zero.
UFUNCTION ()
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
UFUNCTION ()
Transform the input vector4 by a provided matrix4x4 and returns the resulting vector4.
UFUNCTION ()
Combine 2 rotations to give you the resulting rotation of first applying A, then B.
UFUNCTION ()
Negate a rotator.
UFUNCTION ()
Rotate the world forward vector by the given rotation.
UFUNCTION ()
Rotate the world right vector by the given rotation.
UFUNCTION ()
Rotate the world up vector by the given rotation.
UFUNCTION ()
Get the X direction vector after this rotation.
UFUNCTION ()
Get the reference frame direction vectors (axes) described by this rotation.
UFUNCTION ()
Gets the result of multiplying a Matrix to this.
UFUNCTION ()
Gets the result of adding a matrix to this.
UFUNCTION ()
Multiplies all values of the matrix by a float.
UFUNCTION ()
Identity quaternion constant.
UFUNCTION ()
Returns addition of Vector A and Vector B (A + B)
UFUNCTION ()
Returns subtraction of Vector B from Vector A (A - B)
UFUNCTION ()
Gets the result of multiplying two quaternions (A * B).
UFUNCTION ()
Generates the 'smallest' (geodesic) rotation around a sphere between two vectors of arbitrary length.
UFUNCTION ()
Generates the 'smallest' (geodesic) rotation around a sphere between two normals (assumed to be unit length).
UFUNCTION ()
White linear color.
UFUNCTION ()
Grey linear color.
UFUNCTION ()
Black linear color.
UFUNCTION ()
Red linear color.
UFUNCTION ()
Green linear color.
UFUNCTION ()
Blue linear color.
UFUNCTION ()
Yellow linear color.
UFUNCTION ()
Transparent linear color - black with 0 opacity/alpha.
UFUNCTION ()
Assign contents of InColor.
UFUNCTION ()
Assign individual linear RGBA components.
UFUNCTION ()
Assigns an HSV color to a linear space RGB color.
UFUNCTION ()
Assigns an FColor coming from an observed sRGB output, into a linear color.
UFUNCTION ()
Assigns an FColor coming from an observed Pow(1/2.2) output, into a linear color.
UFUNCTION ()
Converts temperature in Kelvins of a black body radiator to RGB chromaticity.
UFUNCTION ()
Sets to a random color.
UFUNCTION ()
Converts a HSV linear color (where H is in R, S is in G, and V is in B) to linear RGB.
UFUNCTION ()
Breaks apart a color into individual HSV components (as well as alpha) (Hue is [0..360) while Saturation and Value are 0..1)
UFUNCTION ()
Element-wise addition of two linear colors (R+R, G+G, B+B, A+A)
UFUNCTION ()
Element-wise subtraction of two linear colors (R-R, G-G, B-B, A-A)
UFUNCTION ()
Element-wise multiplication of two linear colors (R*R, G*G, B*B, A*A)
UFUNCTION ()
Element-wise multiplication of a linear color by a float (F*R, F*G, F*B, F*A)
UFUNCTION ()
Element-wise multiplication of two linear colors (R/R, G/G, B/B, A/A)
UFUNCTION ()
Converts this color value to a hexadecimal string.
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Returns true if A is greater than B (A > B)
UFUNCTION ()
Returns true if A is greater than or equal to B (A >= B)
UFUNCTION ()
Returns true if A is less than B (A < B)
UFUNCTION ()
Returns true if A is less than or equal to B (A <= B)
UFUNCTION ()
Returns the date component of A.
UFUNCTION ()
Returns the day component of A (1 to 31)
UFUNCTION ()
Returns the day of year of A.
UFUNCTION ()
Returns the hour component of A (24h format)
UFUNCTION ()
Returns the hour component of A (12h format)
UFUNCTION ()
Returns the millisecond component of A.
UFUNCTION ()
Returns the minute component of A.
UFUNCTION ()
Returns the month component of A.
UFUNCTION ()
Returns the second component of A.
UFUNCTION ()
Returns the time elapsed since midnight of A.
UFUNCTION ()
Returns the year component of A.
UFUNCTION ()
Returns whether A's time is in the afternoon.
UFUNCTION ()
Returns whether A's time is in the morning.
UFUNCTION ()
Returns the number of days in the given year and month.
UFUNCTION ()
Returns the number of days in the given year.
UFUNCTION ()
Returns whether given year is a leap year.
UFUNCTION ()
Returns the local date and time on this computer.
UFUNCTION ()
Returns the local date on this computer.
UFUNCTION ()
Returns the UTC date and time on this computer.
UFUNCTION ()
Addition (A + B)
UFUNCTION ()
Subtraction (A - B)
UFUNCTION ()
Scalar multiplication (A * s)
UFUNCTION ()
Scalar division (A / s)
UFUNCTION ()
Returns true if A is greater than B (A > B)
UFUNCTION ()
Returns true if A is greater than or equal to B (A >= B)
UFUNCTION ()
Returns true if A is less than B (A < B)
UFUNCTION ()
Returns true if A is less than or equal to B (A <= B)
UFUNCTION ()
Returns the days component of A.
UFUNCTION ()
Returns the absolute value of A.
UFUNCTION ()
Returns the hours component of A.
UFUNCTION ()
Returns the milliseconds component of A.
UFUNCTION ()
Returns the minutes component of A.
UFUNCTION ()
Returns the seconds component of A.
UFUNCTION ()
Returns the total number of days in A.
UFUNCTION ()
Returns the total number of hours in A.
UFUNCTION ()
Returns the total number of milliseconds in A.
UFUNCTION ()
Returns the total number of minutes in A.
UFUNCTION ()
Returns the total number of seconds in A.
UFUNCTION ()
Returns a time span that represents the specified number of days.
UFUNCTION ()
Returns a time span that represents the specified number of hours.
UFUNCTION ()
Returns a time span that represents the specified number of milliseconds.
UFUNCTION ()
Returns a time span that represents the specified number of minutes.
UFUNCTION ()
Returns a time span that represents the specified number of seconds.
UFUNCTION ()
Returns the ratio between two time spans (A / B), handles zero values.
UFUNCTION ()
Convert a float into a vector, where each element is that float.
UFUNCTION ()
Makes an FBoxSphereBounds given an origin, extent, and radius.
UFUNCTION ()
Breaks an FBoxSphereBounds into origin, extent, and radius.
UFUNCTION ()
Makes a SRand-based random number generator.
UFUNCTION ()
Make a transform from location, rotation and scale.
UFUNCTION ()
Compose two transforms in order: A * B.
UFUNCTION ()
Transform a position by the supplied transform.
UFUNCTION ()
Transform a direction vector by the supplied transform - will not change its length.
UFUNCTION ()
Transform a rotator by the supplied transform.
UFUNCTION ()
Transform a position by the inverse of the supplied transform.
UFUNCTION ()
Transform a direction vector by the inverse of the supplied transform - will not change its length.
UFUNCTION ()
Transform a rotator by the inverse of the supplied transform.
UFUNCTION ()
Computes a relative transform of one transform compared to another.
UFUNCTION ()
Returns the inverse of the given transform T.
UFUNCTION ()
Tries to reach Target transform based on distance from Current position, giving a nice smooth feeling when tracking a position.
UFUNCTION () "
Returns true if the values are equal (A == B)
UFUNCTION () "
Returns true if the values are not equal (A != B)
UFUNCTION () "
Modulo (A % B)
UFUNCTION () "
Returns the minimum value of A and B.
UFUNCTION () "
Returns the maximum value of A and B.
UFUNCTION () "
Returns true if A is equal to B (A == B)
UFUNCTION () "
Returns true if A is not equal to B (A != B)
UFUNCTION () "
Modulo (A % B)
UFUNCTION () "
Returns true if A is equal to B (A == B)
UFUNCTION () "
Returns true if A is not equal to B (A != B)
UFUNCTION () "
Returns true if value is between Min and Max (V >= Min && V <= Max) If InclusiveMin is true, value needs to be equal or larger than Min, else it needs to be larger If InclusiveMax is true, value needs to be smaller or equal than Max, else it needs to be smaller.
UFUNCTION () "
Returns the minimum value of A and B.
UFUNCTION () "
Returns the maximum value of A and B.
UFUNCTION () "
Returns Value between A and B (inclusive) that wraps around.
UFUNCTION () "
Returns the absolute (positive) value of A.
UFUNCTION () "
Modulo (A % B)
UFUNCTION () "
Returns true if A is equal to B (A == B)
UFUNCTION () "
Returns true if A is not equal to B (A != B)
UFUNCTION () "
Returns true if value is between Min and Max (V >= Min && V <= Max) If InclusiveMin is true, value needs to be equal or larger than Min, else it needs to be larger If InclusiveMax is true, value needs to be smaller or equal than Max, else it needs to be smaller.
UFUNCTION () "
Returns the minimum value of A and B.
UFUNCTION () "
Returns the maximum value of A and B.
UFUNCTION () "
Returns the absolute (positive) value of A.
UFUNCTION () "
Modulo (A % B)
UFUNCTION () "
Returns true if A is exactly equal to B (A == B)
UFUNCTION () "
Returns true if A is nearly equal to B (|A - B| < ErrorTolerance)
UFUNCTION () "
Returns true if A does not equal B (A != B)
UFUNCTION () "
Returns true if value is between Min and Max (V >= Min && V <= Max) If InclusiveMin is true, value needs to be equal or larger than Min, else it needs to be larger If InclusiveMax is true, value needs to be smaller or equal than Max, else it needs to be smaller.
UFUNCTION () "
Returns the absolute (positive) value of A.
UFUNCTION () "
Returns the sine of A (expects Radians)
UFUNCTION () "
Returns the inverse sine (arcsin) of A (result is in Radians)
UFUNCTION () "
Returns the cosine of A (expects Radians)
UFUNCTION () "
Returns the inverse cosine (arccos) of A (result is in Radians)
UFUNCTION () "
Returns the tan of A (expects Radians)
UFUNCTION () "
Returns the sin of A (expects Degrees)
UFUNCTION () "
Returns the inverse sin (arcsin) of A (result is in Degrees)
UFUNCTION () "
Returns the cos of A (expects Degrees)
UFUNCTION () "
Returns the inverse cos (arccos) of A (result is in Degrees)
UFUNCTION () "
Returns the tan of A (expects Degrees)
UFUNCTION () "
Returns the minimum value of A and B.
UFUNCTION () "
Returns the maximum value of A and B.
UFUNCTION () "
Returns Value clamped between A and B (inclusive)
UFUNCTION () "
Returns Value wrapped from A and B (inclusive)
UFUNCTION () "
Converts an IntPoint to a Vector2D.
UFUNCTION () "
Returns true if IntPoint A is equal to IntPoint B (A == B)
UFUNCTION () "
Returns true if IntPoint A is NOT equal to IntPoint B (A != B)
UFUNCTION () "
Converts a Vector2D to a Vector.
UFUNCTION () "
Converts a Vector2D to an IntPoint.
UFUNCTION () "
Returns true if vector A is equal to vector B (A == B)
UFUNCTION () "
Returns true if vector2D A is equal to vector2D B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if vector2D A is not equal to vector2D B (A != B) within a specified error tolerance.
UFUNCTION () "
Returns true if vector2D A is not equal to vector2D B (A != B) within a specified error tolerance.
UFUNCTION () "
Returns the cross product of two 2d vectors - see http://mathworld.wolfram.com/CrossProduct.html.
UFUNCTION () "
Returns the dot product of two 2d vectors - see http://mathworld.wolfram.com/DotProduct.html.
UFUNCTION () "
Gets a normalized copy of the vector, checking it is safe to do so based on the length.
UFUNCTION () "
Normalize this vector in-place if it is large enough, set it to (0,0) otherwise.
UFUNCTION () "
Get this vector as a vector where each component has been rounded to the nearest int.
UFUNCTION () "
Converts a vector to LinearColor.
UFUNCTION () "
Converts a vector to a transform.
UFUNCTION () "
Converts a Vector to a Vector2D using the Vector's (X, Y) coordinates.
UFUNCTION () "
Return the Quaternion orientation corresponding to the direction in which the vector points.
UFUNCTION () "
Returns true if vector A is equal to vector B (A == B)
UFUNCTION () "
Returns true if vector A is equal to vector B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if vector A is not equal to vector B (A != B)
UFUNCTION () "
Returns true if vector A is not equal to vector B (A != B) within a specified error tolerance.
UFUNCTION () "
Find the unit direction vector from one position to another or (0,0,0) if positions are the same.
UFUNCTION () "
Rounds A to an integer with truncation towards zero for each element in a vector.
UFUNCTION () "
Rounds A to an integer with truncation towards zero for each element in a vector2D.
UFUNCTION () "
Distance between two points.
UFUNCTION () "
Squared distance between two points.
UFUNCTION () "
Euclidean distance between two points in the XY plane (ignoring Z).
UFUNCTION () "
Squared euclidean distance between two points in the XY plane (ignoring Z).
UFUNCTION () "
Checks whether all components of this vector are the same, within a tolerance.
UFUNCTION () "
Determines if vector is normalized / unit (length 1) within specified squared tolerance.
UFUNCTION () "
Determines if vector is normalized / unit (length 1).
UFUNCTION () "
Gets a normalized unit copy of the 2D components of the vector, ensuring it is safe to do so.
UFUNCTION () "
Calculates normalized unit version of vector without checking for zero length.
UFUNCTION () "
Normalize this vector in-place if it is large enough or set it to (0,0,0) otherwise.
UFUNCTION () "
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
UFUNCTION () "
Easing between A and B using a specified easing function.
UFUNCTION () "
Gets the reciprocal of this vector, avoiding division by zero.
UFUNCTION () "
Returns a random point within the specified bounding box.
UFUNCTION () "
Converts a Vector4 to a Vector (dropping the W element)
UFUNCTION () "
Return the FRotator orientation corresponding to the direction in which the vector points.
UFUNCTION () "
Return the Quaternion orientation corresponding to the direction in which the vector points.
UFUNCTION () "
Returns true if vector A is equal to vector B (A == B)
UFUNCTION () "
Returns true if vector A is equal to vector B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if vector A is not equal to vector B (A != B) within a specified error tolerance.
UFUNCTION () "
Returns true if vector A is not equal to vector B (A != B) within a specified error tolerance.
UFUNCTION () "
Gets a negated copy of the vector.
UFUNCTION () "
Returns the cross product of two vectors - see http://mathworld.wolfram.com/CrossProduct.html.
UFUNCTION () "
Returns the dot product of two vectors - see http://mathworld.wolfram.com/DotProduct.html.
UFUNCTION () "
Returns the dot product of two vectors - see http://mathworld.wolfram.com/DotProduct.html The W element is ignored.
UFUNCTION () "
Returns the length of the vector.
UFUNCTION () "
Returns the squared length of the vector.
UFUNCTION () "
Returns the length of the vector.
UFUNCTION () "
Returns the squared length of the vector.
UFUNCTION () "
Determines if vector is normalized / unit (length 1) within specified squared tolerance.
UFUNCTION () "
Determines if vector is normalized / unit (length 1).
UFUNCTION () "
Gets a normalized unit copy of the vector, ensuring it is safe to do so based on the length.
UFUNCTION () "
Calculates normalized unit version of vector without checking for zero length.
UFUNCTION () "
Normalize this vector in-place if it is large enough or set it to (0,0,0,0) otherwise.
UFUNCTION () "
Returns true if rotator A is equal to rotator B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if rotator A is not equal to rotator B (A != B) within a specified error tolerance.
UFUNCTION () "
Returns rotator representing rotator A scaled by B.
UFUNCTION () "
Returns rotator representing rotator A scaled by B.
UFUNCTION () "
Converts Rotator to Transform.
UFUNCTION () "
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
UFUNCTION () "
Easing between A and B using a specified easing function.
UFUNCTION () "
Normalized A-B.
UFUNCTION () "
Converts a Matrix to a Transform (Assumes Matrix represents a transform)
UFUNCTION () "
Converts a Matrix to a Rotator (Assumes Matrix represents a transform)
UFUNCTION () "
Get the origin of the co-ordinate system (Assumes Matrix represents a transform)
UFUNCTION () "
UFUNCTION () "
Checks whether another Matrix is equal to this, within specified tolerance.
UFUNCTION () "
Checks whether another Matrix is not equal to this, within specified tolerance.
UFUNCTION () "
Transform a vector by the matrix.
UFUNCTION () "
Transform a location - will take into account translation part of the FMatrix.
UFUNCTION () "
Inverts the matrix and then transforms V - correctly handles scaling in this matrix.
UFUNCTION () "
Transform a direction vector - will not take into account translation part of the FMatrix.
UFUNCTION () "
Transform a direction vector by the inverse of this matrix - will not take into account translation part.
UFUNCTION () "
UFUNCTION () "
UFUNCTION () "
UFUNCTION () "
Get the inverse of the Matrix.
UFUNCTION () "
Get the Transose Adjoint of the Matrix.
UFUNCTION () "
Remove any scaling from this matrix (ie magnitude of each row is 1) with error Tolerance (Assumes Matrix represents a transform)
UFUNCTION () "
Returns matrix after RemoveScaling with error Tolerance (Assumes Matrix represents a transform)
UFUNCTION () "
return a 3D scale vector calculated from this matrix (where each component is the magnitude of a row vector) with error Tolerance.
UFUNCTION () "
Remove any translation from this matrix (Assumes Matrix represents a transform)
UFUNCTION () "
Returns a matrix with an additional translation concatenated.
UFUNCTION () "
Returns true if any element of this matrix is NaN.
UFUNCTION () "
Scale the translation part of the matrix by the supplied vector.
UFUNCTION () "
UFUNCTION () "
Apply Scale to this matrix (Assumes Matrix represents a transform)
UFUNCTION () "
get axis of this matrix scaled by the scale of the matrix (Assumes Matrix represents a transform)
UFUNCTION () "
get axes of this matrix scaled by the scale of the matrix (Assumes Matrix represents a transform)
UFUNCTION () "
get unit length axis of this matrix (Assumes Matrix represents a transform)
UFUNCTION () "
get unit length axes of this matrix (Assumes Matrix represents a transform)
UFUNCTION () "
set an axis of this matrix (Assumes Matrix represents a transform)
UFUNCTION () "
Set the origin of the coordinate system to the given vector (Assumes Matrix represents a transform)
UFUNCTION () "
get a column of this matrix
UFUNCTION () "
UFUNCTION () "
Get the rotator representation of this matrix (Assumes Matrix represents a transform)
UFUNCTION () "
Transform a rotation matrix into a quaternion.
UFUNCTION () "
Get the near plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
UFUNCTION () "
Get the far plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
UFUNCTION () "
Get the left plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
UFUNCTION () "
Get the right plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
UFUNCTION () "
Get the top plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
UFUNCTION () "
Get the bottom plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
UFUNCTION () "
Utility for mirroring this transform across a certain plane, and flipping one of the axis as well.
UFUNCTION () "
Returns true if Quaternion A is equal to Quaternion B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if Quat A is not equal to Quat B (A != B) within a specified error tolerance.
UFUNCTION () "
Checks whether this Quaternion is an Identity Quaternion.
UFUNCTION () "
Return true if this quaternion is normalized.
UFUNCTION () "
Determine if all the values are finite (not NaN nor Inf) in this Quat.
UFUNCTION () "
Determine if there are any non-finite values (NaN or Inf) in this Quat.
UFUNCTION () "
Find the angular distance/difference between two rotation quaternions.
UFUNCTION () "
Modify the quaternion to ensure that the delta between it and B represents the shortest possible rotation angle.
UFUNCTION () "
Convert a Quaternion into floating-point Euler angles (in degrees).
UFUNCTION () "
Used in combination with Log().
UFUNCTION () "
Get the angle of this quaternion.
UFUNCTION () "
Get the forward direction (X axis) after it has been rotated by this Quaternion.
UFUNCTION () "
Get the right direction (Y axis) after it has been rotated by this Quaternion.
UFUNCTION () "
Get the up direction (Z axis) after it has been rotated by this Quaternion.
UFUNCTION () "
Get the forward direction (X axis) after it has been rotated by this Quaternion.
UFUNCTION () "
Get the right direction (Y axis) after it has been rotated by this Quaternion.
UFUNCTION () "
Get the up direction (Z axis) after it has been rotated by this Quaternion.
UFUNCTION () "
Normalize this quaternion if it is large enough as compared to the supplied tolerance.
UFUNCTION () "
Get a normalized copy of this quaternion.
UFUNCTION () "
Get the axis of rotation of the Quaternion.
UFUNCTION () "
Return an inversed copy of this quaternion.
UFUNCTION () "
Quaternion with W=0 and V=theta*v.
UFUNCTION () "
Set X, Y, Z, W components of Quaternion.
UFUNCTION () "
Convert a vector of floating-point Euler angles (in degrees) into a Quaternion.
UFUNCTION () "
Converts to Rotator representation of this Quaternion.
UFUNCTION () "
Converts to Quaternion representation of this Rotator.
UFUNCTION () "
Get the length of the quaternion.
UFUNCTION () "
Get the squared length of the quaternion.
UFUNCTION () "
Rotate a vector by this quaternion.
UFUNCTION () "
Rotate a vector by the inverse of this quaternion.
UFUNCTION () "
Spherical interpolation between Quaternions.
UFUNCTION () "
Converts a float into a LinearColor, where each RGB element is that float.
UFUNCTION () "
Converts a HSV linear color (where H is in R (0..360), S is in G (0..1), and V is in B (0..1)) to RGB.
UFUNCTION () "
Converts a RGB linear color to HSV (where H is in R (0..360), S is in G (0..1), and V is in B (0..1))
UFUNCTION () "
Converts a RGB linear color to HSV (where H is in R, S is in G, and V is in B)
UFUNCTION () "
Converts a LinearColor to a vector.
UFUNCTION () "
Converts from linear to 8-bit RGBE as outlined in Gregory Ward's Real Pixels article, Graphics Gems II, page 80.
UFUNCTION () "
Quantizes the linear color and returns the result as a FColor with optional sRGB conversion and quality as goal.
UFUNCTION () "
Quantizes the linear color and returns the result as an 8-bit color.
UFUNCTION () "
Quantizes the linear color with rounding and returns the result as an 8-bit color.
UFUNCTION () "
Returns a desaturated color, with 0 meaning no desaturation and 1 == full desaturation.
UFUNCTION () "
Euclidean distance between two color points.
UFUNCTION () "
Returns a copy of this color using the specified opacity/alpha.
UFUNCTION () "
Returns the perceived brightness of a color on a display taking into account the impact on the human eye per color channel: green > red > blue.
UFUNCTION () "
Returns the maximum color channel value in this color structure.
UFUNCTION () "
Returns the minimum color channel value in this color structure.
UFUNCTION () "
Interpolate Linear Color from Current to Target.
UFUNCTION () "
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
UFUNCTION () "
Linearly interpolates between two colors by the specified Alpha amount (100% of A when Alpha=0 and 100% of B when Alpha=1).
UFUNCTION () "
Returns true if linear color A is equal to linear color B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if linear color A is equal to linear color B (A == B) within a specified error tolerance.
UFUNCTION () "
Returns true if linear color A is not equal to linear color B (A != B) within a specified error tolerance.
UFUNCTION () "
Returns true if the values are equal (A == B)
UFUNCTION () "
Returns true if the values are not equal (A != B)
UFUNCTION () "
Returns the maximum time span value.
UFUNCTION () "
Returns the minimum time span value.
UFUNCTION () "
Returns a zero time span value.
UFUNCTION () "
Returns true if the values are equal (A == B)
UFUNCTION () "
Returns true if the values are not equal (A != B)
UFUNCTION () "
Converts a byte to a float.
UFUNCTION () "
Converts an integer to a float.
UFUNCTION () "
Converts an integer to a 64 bit integer.
UFUNCTION () "
Converts an integer to a byte (if the integer is too large, returns the low 8 bits)
UFUNCTION () "
Converts a 64 bit integer to a 32 bit integer (if the integer is too large, returns the low 32 bits)
UFUNCTION () "
Converts a 64 bit integer to a byte (if the integer is too large, returns the low 8 bits)
UFUNCTION () "
Converts a float to a 64 bit integer.
UFUNCTION () "
Converts a 64 bit integer to a float.
UFUNCTION () "
Converts an integer to an IntVector.
UFUNCTION () "
Converts an integer to an IntVector2.
UFUNCTION () "
Converts an integer to a FVector.
UFUNCTION () "
Converts a int to a bool.
UFUNCTION () "
Converts a bool to an int.
UFUNCTION () "
Converts a bool to a float (0.0 or 1.0)
UFUNCTION () "
Converts a bool to a byte.
UFUNCTION () "
Converts a byte to an integer.
UFUNCTION () "
Converts a byte to an integer.
UFUNCTION () "
Converts a color to LinearColor.
UFUNCTION () "
Converts an IntVector to a vector.
UFUNCTION () "
Converts an IntVector2 to a vector2D.
UFUNCTION () "
Converts a double into a vector, where each element is that float.
UFUNCTION () "
Returns true if A and B are equal (A == B)
UFUNCTION () "
Returns true if A and B are not equal (A != B)
UFUNCTION () "
Returns true if A and B are equal (A == B)
UFUNCTION () "
Returns true if A and B are not equal (A != B)
UFUNCTION () "
Returns true if A and B are equal (A == B)
UFUNCTION () "
Returns true if A and B are not equal (A != B)
UFUNCTION () "
Returns true if transform A is equal to transform B.
UFUNCTION () "
Returns true if transform A is nearly equal to B.
UFUNCTION () "
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1).
UFUNCTION () "
Ease between A and B using a specified easing function.
UFUNCTION () "
Converts a Transform to a Matrix with scale.
UFUNCTION () ")
Sign (integer, returns -1 if A < 0, 0 if A is zero, and +1 if A > 0)
UFUNCTION () ")
Returns Value clamped to be between A and B (inclusive)
UFUNCTION () ")
Sign (integer64, returns -1 if A < 0, 0 if A is zero, and +1 if A > 0)
UFUNCTION () ")
Returns Value clamped to be between A and B (inclusive)
UFUNCTION () ")
Snaps a value to the nearest grid multiple.
UFUNCTION () ")
Returns the inverse tan (atan) (result is in Radians)
UFUNCTION () ")
Returns the inverse tan (atan2) of A/B (result is in Radians)
UFUNCTION () ")
Returns the inverse tan (atan) (result is in Degrees)
UFUNCTION () ")
Returns the inverse tan (atan2) of A/B (result is in Degrees)
UFUNCTION () ")
Returns the number of times Divisor will go into Dividend (i.e., Dividend divided by Divisor), as well as the remainder.
UFUNCTION () ")
Sign (float, returns -1 if A < 0, 0 if A is zero, and +1 if A > 0)
UFUNCTION () ")
Convert a vector of floating-point Euler angles (in degrees) into a Quaternion.
UFUNCTION () ")
Returns the maximum date and time value.
UFUNCTION () ")
Returns the minimum date and time value.
UFUNCTION () ")
Returns a random point within the specified bounding box.
UFUNCTION () ")) static 1 bool Box_Intersects(const FBox & A
Checks whether the given bounding box A intersects this bounding box B.
UFUNCTION () ")) static 1 bool Box_IsInside(const FBox & InnerTest
Returns true if the InnerTest Box is is completely inside of the OuterTest Box.
UFUNCTION () ")) static 1 bool Box_IsInsideOrOn(const FBox & InnerTest
Returns true if the InnerTest Box is is completely inside or on OuterTest Box.
UFUNCTION () ")) static 1 bool Box_IsPointInside(const FBox & Box
Checks whether the given location is inside this box.
UFUNCTION () ")) static 1 bool IsPointInBox_Box(FVector Point
Determines whether the given point is in a box.
UFUNCTION () ")) static 1 bool IsPointInBoxWithTransform_Box(FVector Point
Determines whether a given point is in a box with a given transform.
UFUNCTION () ")) static 1 bool LinePlaneIntersection_OriginNormal(const FVector & LineStart
Computes the intersection point between a line and a plane.
UFUNCTION () ")) static 1 double GetBoxVolume(const FBox & InBox)
Gets the volume of this box.
UFUNCTION () ")) static 1 FBox Box_ExpandBy(const FBox & Box
Returns a box of increased size.
UFUNCTION () ")) static 1 FBox Box_Overlap(const FBox & A
Returns the overlap TBox<T> of two boxes.
UFUNCTION () ")) static 1 FVector Box_GetClosestPointTo(const FBox & Box
Calculates the closest point on or inside the box to a given point in space.
UFUNCTION () ")) static 1 FVector GetBoxCenter(const FBox & InBox)
Gets the center point of this box.
UFUNCTION () ")) static 1 FVector GetBoxSize(const FBox & InBox)
Gets the size of this box.
UFUNCTION () 2D"
Get a copy of the vector as sign only.
UFUNCTION () static 1 bool ClassIsChildOf(TSubclassOf< class UObject > TestClass
Determine if a class is a child of another class.
UFUNCTION () static 1 bool IsPointInBox(FVector Point
Determines whether the given point is in a box.
UFUNCTION () static 1 bool IsPointInBoxWithTransform(FVector Point
Determines whether a given point is in a box with a given transform.
UFUNCTION () static 1 bool LinePlaneIntersection(const FVector &LineStart
Computes the intersection point between a line and a plane.
UFUNCTION () static 1 double FInterpEaseInOut(double A
Interpolate between A and B, applying an ease in/out function.
UFUNCTION () static 1 double Lerp(double A
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
UFUNCTION () static 1 double Log(double A
Returns log of A base B (if B^R == A, returns R)
UFUNCTION () static 1 double NormalizeToRange(double Value
Returns Value normalized to the given range.
UFUNCTION () static 1 double SelectFloat(double A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 FLinearColor SelectColor(FLinearColor A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 float ClampAxis(float Angle)
Clamps an angle to the range of [0, 360].
UFUNCTION () static 1 float GetRuntimeFloatCurveValue(const FRuntimeFloatCurve &Curve
Evaluate this runtime float curve at the specified time.
UFUNCTION () static 1 float MakePulsatingValue(float InCurrentTime
Simple function to create a pulsating scalar value.
UFUNCTION () static 1 float NormalizeAxis(float Angle)
Clamps an angle to the range of [-180, 180].
UFUNCTION () static 1 float PerlinNoise1D(const float Value)
Generates a 1D Perlin noise from the given value.
UFUNCTION () static 1 FName SelectName(const FName A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 FString SelectString(const FString &A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 FText SelectText(const FText A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 FTransform SelectTransform(const FTransform &A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 FVector FindClosestPointOnLine(FVector Point
Find the closest point on an infinite line to a given point.
UFUNCTION () static 1 FVector GetVectorArrayAverage(const TArray< FVector > &Vectors)
Find the average of an array of vectors.
UFUNCTION () static 1 FVector SelectVector(FVector A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 int32 SelectInt(int32 A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static 1 void AverageOfIntArray(const TArray< int32 > &IntArray
Returns average of all array entries.
UFUNCTION () static 1 void GetSlopeDegreeAngles(const FVector &MyRightYAxis
Returns Slope Pitch and Roll angles in degrees based on the following information:
UFUNCTION () static 1 void MaxOfByteArray(const TArray< uint8 > &ByteArray
Returns max of all array entries and the index at which it was found.
UFUNCTION () static 1 void MaxOfFloatArray(const TArray< float > &FloatArray
Returns max of all array entries and the index at which it was found.
UFUNCTION () static 1 void MaxOfIntArray(const TArray< int32 > &IntArray
Returns max of all array entries and the index at which it was found.
UFUNCTION () static 1 void MedianOfIntArray(TArray< int32 > IntArray
Returns median of all array entries.
UFUNCTION () static 1 void MinOfByteArray(const TArray< uint8 > &ByteArray
Returns min of all array entries and the index at which it was found.
UFUNCTION () static 1 void MinOfFloatArray(const TArray< float > &FloatArray
Returns min of all array entries and the index at which it was found.
UFUNCTION () static 1 void MinOfIntArray(const TArray< int32 > &IntArray
Returns min of all array entries and the index at which it was found.
UFUNCTION () static 1 void ResetFloatSpringState(UPARAM(ref) FFloatSpringState &SpringState)
Resets the state of a float spring.
UFUNCTION () static 1 void ResetQuaternionSpringState(UPARAM(ref) FQuaternionSpringState &SpringState)
Resets the state of a quaternion spring.
UFUNCTION () static 1 void ResetVectorSpringState(UPARAM(ref) FVectorSpringState &SpringState)
Resets the state of a vector spring.
UFUNCTION () static 1 void SetFloatSpringStateVelocity(UPARAM(ref) FFloatSpringState &SpringState
Sets the state velocity of a float spring.
UFUNCTION () static 1 void SetQuaternionSpringStateAngularVelocity(UPARAM(ref) FQuaternionSpringState &SpringState
Sets the state angular velocity of a quaternion spring.
UFUNCTION () static 1 void SetVectorSpringStateVelocity(UPARAM(ref) FVectorSpringState &SpringState
Sets the state velocity of a vector spring.
UFUNCTION () static bool DateTimeFromIsoString(FString IsoString
Converts a date string in ISO-8601 format to a DateTime object.
UFUNCTION () static bool DateTimeFromString(FString DateTimeString
Converts a date string to a DateTime object.
UFUNCTION () static bool PointsAreCoplanar(const TArray< FVector > &Points
Determines whether a given set of points are coplanar, with a tolerance.
UFUNCTION () static bool TimespanFromString(FString TimespanString
Converts a time span string to a Timespan object.
UFUNCTION () static double FInterpTo(double Current
Tries to reach Target based on distance from Current position, giving a nice smooth feeling when tracking a position.
UFUNCTION () static double FInterpTo_Constant(double Current
Tries to reach Target at a constant rate.
UFUNCTION () static double Fraction(double A)
Returns the fractional part of a float.
UFUNCTION () static double Loge(double A)
Returns natural log of A (if e^R == A, returns R)
UFUNCTION () static double ToUnixTimestampDouble(const FDateTime &Time)
Returns this date as the number of seconds since the Unix Epoch (January 1st of 1970).
UFUNCTION () static FDateTime FromUnixTimestamp(const int64 UnixTime)
Returns the date from Unix time (seconds from midnight 1970-01-01)
UFUNCTION () static float FixedTurn(float InCurrent
Returns a new rotation component value.
UFUNCTION () static float GetPointDistanceToLine(FVector Point
Find the distance from a point to the closest point on an infinite line.
UFUNCTION () static float GetPointDistanceToSegment(FVector Point
Find the distance from a point to the closest point on a segment.
UFUNCTION () static FVector FindClosestPointOnSegment(FVector Point
Find the closest point on a segment to a given point.
UFUNCTION () static FVector MirrorVectorByNormal(FVector InVect
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
UFUNCTION () static int32 Round(double A)
Rounds A to the nearest integer (e.g., -1.6 becomes -2 and 1.6 becomes 2)
UFUNCTION () static int64 ToUnixTimestamp(const FDateTime &Time)
Returns this date as the number of seconds since the Unix Epoch (January 1st of 1970).
UFUNCTION () static UClass *SelectClass(UClass *A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static UObject *SelectObject(UObject *A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION () static void BreakColor(FLinearColor InColor
Breaks apart a color into individual RGB components (as well as alpha)
UFUNCTION () static void FindNearestPointsOnLineSegments(FVector Segment1Start
Find closest points between 2 segments.
UFUNCTION () to Integer64")
Returns the number of times Divisor will go into Dividend (i.e., Dividend divided by Divisor), as well as the remainder.
UFUNCTION ()) static 1 bool RandomBoolFromStream(const FRandomStream &Stream)
Returns a random bool.
UFUNCTION ()) static 1 bool RandomBoolWithWeight(float Weight)
Get a random chance with the specified weight.
UFUNCTION ()) static 1 bool RandomBoolWithWeightFromStream(const FRandomStream &RandomStream
Get a random chance with the specified weight.
UFUNCTION ()) static 1 double MapRangeClamped(double Value
Returns Value mapped from one range into another where the Value is clamped to the Input Range.
UFUNCTION ()) static 1 double MapRangeUnclamped(double Value
Returns Value mapped from one range into another.
UFUNCTION ()) static 1 double SafeDivide(double A
This functions returns 0 if B (the denominator) is zero.
UFUNCTION ()) static 1 FBox MakeBoxWithOrigin(const FVector &Origin
Utility function to build an box from an Origin and Extent.
UFUNCTION ()) static 1 FDateTime MakeDateTime(int32 Year
Makes a DateTime struct.
UFUNCTION ()) static 1 FFrameRate MakeFrameRate(int32 Numerator
Creates a FFrameRate from a Numerator and a Denominator.
UFUNCTION ()) static 1 FIntPoint Convert1DTo2D(int32 Index1D
Maps a 1D array index to a 2D array index.
UFUNCTION ()) static 1 FIntVector Convert1DTo3D(int32 Index1D
Maps a 1D array index to a 3D array index.
UFUNCTION ()) static 1 float DynamicWeightedMovingAverage_Float(float CurrentSample
Calculates the new value in a weighted moving average series using the previous value and a weight range.
UFUNCTION ()) static 1 float FloatSpringInterp(float Current
Uses a simple spring model to interpolate a float from Current to Target.
UFUNCTION ()) static 1 float RandomFloatFromStream(const FRandomStream &Stream)
Returns a random float between 0 and 1.
UFUNCTION ()) static 1 float RandomFloatInRangeFromStream(const FRandomStream &Stream
Generate a random number between Min and Max.
UFUNCTION ()) static 1 float Transform_Determinant(const FTransform &Transform)
Calculates the determinant of the transform (converts to FMatrix internally)
UFUNCTION ()) static 1 float WeightedMovingAverage_Float(float CurrentSample
Calculates the new value in a weighted moving average series using the previous value and the weight.
UFUNCTION ()) static 1 FPlane MakePlaneFromPointAndNormal(FVector Point
Creates a plane with a facing direction of Normal at the given Point.
UFUNCTION ()) static 1 FQualifiedFrameTime MakeQualifiedFrameTime(FFrameNumber Frame
Creates a FQualifiedFrameTime out of a frame number, frame rate, and optional 0-1 clamped subframe.
UFUNCTION ()) static 1 FRandomStream MakeRandomStreamFromLocation(const FVector &Location
Makes a random stream that will generate deterministic values, optionally grouping outputs within cells on a grid.
UFUNCTION ()) static 1 FRotator DynamicWeightedMovingAverage_FRotator(FRotator CurrentSample
Calculates the new value in a weighted moving average series using the previous value and a weight range.
UFUNCTION ()) static 1 FRotator FindRelativeLookAtRotation(const FTransform &StartTransform
Find a local rotation (range of [-180, 180]) for an object with StartTransform to point at TargetLocation.
UFUNCTION ()) static 1 FRotator MakeRotationFromAxes(FVector Forward
UFUNCTION ()) static 1 FRotator MakeRotator(UPARAM(DisplayName
Makes a rotator {Roll, Pitch, Yaw} from rotation values supplied in degrees.
UFUNCTION ()) static 1 FRotator RandomRotator(bool bRoll
Generates a random rotation, with optional random roll.
UFUNCTION ()) static 1 FRotator RandomRotatorFromStream(const FRandomStream &Stream
Create a random rotation.
UFUNCTION ()) static 1 FRotator SelectRotator(FRotator A
If bPickA is true, A is returned, otherwise B is.
UFUNCTION ()) static 1 FRotator WeightedMovingAverage_FRotator(FRotator CurrentSample
Calculates the new value in a weighted moving average series using the previous value and the weight.
UFUNCTION ()) static 1 FTimespan MakeTimespan(int32 Days
Makes a Timespan struct.
UFUNCTION ()) static 1 FTimespan MakeTimespan2(int32 Days
Makes a Timespan struct.
UFUNCTION ()) static 1 FVector CreateVectorFromYawPitch(float Yaw
Creates a directional vector from rotation values {Pitch, Yaw} supplied in degrees with specified Length.
UFUNCTION ()) static 1 FVector DynamicWeightedMovingAverage_FVector(FVector CurrentSample
Calculates the new value in a weighted moving average series using the previous value and a weight range.
UFUNCTION ()) static 1 FVector RandomPointInBoundingBoxFromStream(const FRandomStream &Stream
Returns a random point within the specified bounding box using the first vector as an origin and the second as the half size of the AABB.
UFUNCTION ()) static 1 FVector RandomUnitVector()
Returns a random vector with length of 1.
UFUNCTION ()) static 1 FVector RandomUnitVectorFromStream(const FRandomStream &Stream)
Returns a random vector with length of 1.0.
UFUNCTION ()) static 1 FVector RandomUnitVectorInConeInRadiansFromStream(const FRandomStream &Stream
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static 1 FVector RandomUnitVectorInEllipticalConeInRadians(FVector ConeDir
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static 1 FVector RandomUnitVectorInEllipticalConeInRadiansFromStream(const FRandomStream &Stream
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static 1 FVector WeightedMovingAverage_FVector(FVector CurrentSample
Calculates the new value in a weighted moving average series using the previous value and the weight.
UFUNCTION ()) static 1 int32 Convert2DTo1D(const FIntPoint &Index2D
Maps a 2D array index to a 1D array index.
UFUNCTION ()) static 1 int32 Convert3DTo1D(const FIntVector &Index3D
Maps a 3D array index to a 1D array index.
UFUNCTION ()) static 1 int32 RandomInteger(UPARAM(DisplayName
Returns a uniformly distributed random number between 0 and Max - 1.
UFUNCTION ()) static 1 int32 RandomIntegerFromStream(const FRandomStream &Stream
Returns a uniformly distributed random number between 0 and Max - 1.
UFUNCTION ()) static 1 int32 RandomIntegerInRangeFromStream(const FRandomStream &Stream
Return a random integer between Min and Max (>= Min and <= Max)
UFUNCTION ()) static 1 int64 RandomInteger64(UPARAM(DisplayName
Returns a uniformly distributed random number between 0 and Max - 1.
UFUNCTION ()) static 1 void BreakDateTime(FDateTime InDateTime
Breaks a DateTime into its components.
UFUNCTION ()) static 1 void BreakFrameRate(const FFrameRate &InFrameRate
Breaks a FFrameRate into a numerator and denominator.
UFUNCTION ()) static 1 void BreakQualifiedFrameTime(const FQualifiedFrameTime &InFrameTime
Breaks a FQualifiedFrameTime into its component parts again.
UFUNCTION ()) static 1 void BreakRandomStream(const FRandomStream &InRandomStream
Breaks apart a random number generator.
UFUNCTION ()) static 1 void BreakRotator(UPARAM(DisplayName
Breaks apart a rotator into {Roll, Pitch, Yaw} angles in degrees.
UFUNCTION ()) static 1 void BreakRotIntoAxes(const FRotator &InRot
Breaks apart a rotator into its component axes.
UFUNCTION ()) static 1 void BreakTimespan(FTimespan InTimespan
Breaks a Timespan into its components.
UFUNCTION ()) static 1 void BreakTimespan2(FTimespan InTimespan
Breaks a Timespan into its components.
UFUNCTION ()) static 1 void BreakTransform(const FTransform &InTransform
Breaks apart a transform into location, rotation and scale.
UFUNCTION ()) static 1 void GetAzimuthAndElevation(FVector InDirection
Breaks a direction vector apart into Azimuth (Yaw) and Elevation (Pitch) rotation values given in degrees.
UFUNCTION ()) static 1 void GetYawPitchFromVector(FVector InVec
Breaks a vector apart into Yaw, Pitch rotation values given in degrees.
UFUNCTION ()) static 1 void MinAreaRectangle(UObject *WorldContextObject
Finds the minimum area rectangle that encloses a set of coplanar points.
UFUNCTION ()) static 1 void ResetRandomStream(const FRandomStream &Stream)
Reset a random stream.
UFUNCTION ()) static 1 void SeedRandomStream(UPARAM(ref) FRandomStream &Stream)
Create a new random seed for a random stream.
UFUNCTION ()) static 1 void SetRandomStreamSeed(UPARAM(ref) FRandomStream &Stream
Set the seed of a random stream to a specific number.
UFUNCTION ()) static double Conv_FloatToDouble(float InFloat)
Converts a 32 bit floating point to a 64 bit floating point.
UFUNCTION ()) static double Exp(double A)
Returns exponential(e) to the power A (e^A)
UFUNCTION ()) static double RandomFloat()
Returns a random float between 0 and 1.
UFUNCTION ()) static double RandomFloatInRange(double Min
Generate a random number between Min and Max.
UFUNCTION ()) static double Sqrt(double A)
Returns square root of A.
UFUNCTION ()) static double Square(double A)
Returns square of A (A*A)
UFUNCTION ()) static FBox MakeBox(FVector Min
Makes an FBox from Min and Max and sets IsValid to true.
UFUNCTION ()) static FBox2D MakeBox2D(FVector2D Min
Makes an FBox2D from Min and Max and sets IsValid to true.
UFUNCTION ()) static FLinearColor HSVToRGB(float H
Make a color from individual color components (HSV space; Hue is [0..360) while Saturation and Value are 0..1)
UFUNCTION ()) static FLinearColor MakeColor(float R
Make a color from individual color components (RGB space)
UFUNCTION ()) static float Conv_DoubleToFloat(double InDouble)
Converts a 64 bit floating point to a 32 bit floating point (if the float is too large, returns the low 32 bits)
UFUNCTION ()) static FQuat MakeQuat(float X
Makes a quat {X, Y, Z, W}.
UFUNCTION ()) static FRotator FindLookAtRotation(const FVector &Start
Find a rotation for an object at Start location to point at Target location.
UFUNCTION ()) static FRotator MakeRotFromX(const FVector &X)
Builds a rotator given only a XAxis.
UFUNCTION ()) static FRotator MakeRotFromXY(const FVector &X
Builds a matrix with given X and Y axes.
UFUNCTION ()) static FRotator MakeRotFromXZ(const FVector &X
Builds a matrix with given X and Z axes.
UFUNCTION ()) static FRotator MakeRotFromY(const FVector &Y)
Builds a rotation matrix given only a YAxis.
UFUNCTION ()) static FRotator MakeRotFromYX(const FVector &Y
Builds a matrix with given Y and X axes.
UFUNCTION ()) static FRotator MakeRotFromYZ(const FVector &Y
Builds a matrix with given Y and Z axes.
UFUNCTION ()) static FRotator MakeRotFromZ(const FVector &Z)
Builds a rotation matrix given only a ZAxis.
UFUNCTION ()) static FRotator MakeRotFromZX(const FVector &Z
Builds a matrix with given Z and X axes.
UFUNCTION ()) static FRotator MakeRotFromZY(const FVector &Z
Builds a matrix with given Z and Y axes.
UFUNCTION ()) static FRotator RInterpTo(FRotator Current
Tries to reach Target rotation based on Current rotation, giving a nice smooth feeling when rotating to Target rotation.
UFUNCTION ()) static FRotator RInterpTo_Constant(FRotator Current
Tries to reach Target rotation at a constant rate.
UFUNCTION ()) static FVector MakeVector(double X
Makes a vector {X, Y, Z}.
UFUNCTION ()) static FVector RandomPointInBoundingBox(const FVector Center
Returns a random point within the specified bounding box using the first vector as an origin and the second as the box extents.
UFUNCTION ()) static FVector RandomUnitVectorInConeInRadians(FVector ConeDir
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static FVector VInterpTo(FVector Current
Tries to reach Target based on distance from Current position, giving a nice smooth feeling when tracking a position.
UFUNCTION ()) static FVector VInterpTo_Constant(FVector Current
Tries to reach Target at a constant rate.
UFUNCTION ()) static FVector2D MakeVector2D(double X
Makes a 2d vector {X, Y}.
UFUNCTION ()) static FVector2D Vector2DInterpTo(FVector2D Current
Tries to reach Target based on distance from Current position, giving a nice smooth feeling when tracking a position.
UFUNCTION ()) static FVector2D Vector2DInterpTo_Constant(FVector2D Current
Tries to reach Target at a constant rate.
UFUNCTION ()) static FVector_NetQuantize MakeVector_NetQuantize(double X
UFUNCTION ()) static FVector_NetQuantize10 MakeVector_NetQuantize10(double X
UFUNCTION ()) static FVector_NetQuantize100 MakeVector_NetQuantize100(double X
UFUNCTION ()) static FVector_NetQuantizeNormal MakeVector_NetQuantizeNormal(double X
UFUNCTION ()) static inline FVector RandomUnitVectorInConeInDegrees(FVector ConeDir
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static inline FVector RandomUnitVectorInConeInDegreesFromStream(const FRandomStream &Stream
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static inline FVector RandomUnitVectorInEllipticalConeInDegrees(FVector ConeDir
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static inline FVector RandomUnitVectorInEllipticalConeInDegreesFromStream(const FRandomStream &Stream
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
UFUNCTION ()) static int32 FCeil(double A)
Rounds A up towards positive infinity / up to the next integer (e.g., -1.6 becomes -1 and 1.6 becomes 2)
UFUNCTION ()) static int32 RandomIntegerInRange(int32 Min
Return a random integer between Min and Max (>= Min and <= Max)
UFUNCTION ()) static int64 RandomInteger64InRange(int64 Min
Return a random integer64 between Min and Max (>= Min and <= Max)
UFUNCTION ()) static void BreakQuat(const FQuat &InQuat
Breaks a quat apart into X, Y, Z, W.
UFUNCTION ()) static void BreakVector(FVector InVec
Breaks a vector apart into X, Y, Z.
UFUNCTION ()) static void BreakVector2D(FVector2D InVec
Breaks a 2D vector apart into X, Y.
UFUNCTION ()) static void BreakVector_NetQuantize(FVector_NetQuantize InVec
UFUNCTION ()) static void BreakVector_NetQuantize10(FVector_NetQuantize10 InVec
UFUNCTION ()) static void BreakVector_NetQuantize100(FVector_NetQuantize100 InVec
UFUNCTION ()) static void BreakVector_NetQuantizeNormal(FVector_NetQuantizeNormal InVec
float UPARAM (ref) FFloatSpringState &SpringState
Static Private Member Functions
static BlueprintAutocast FMatrix Conv_TransformToMatrix (const FTransform &Transform)
static double GenericPercent_FloatFloat (double A, double B)
static NotBlueprintThreadSafe FVector RandomPointInBoundingBox_Box (const FBox Box)
static void ReportError_DaysInMonth ()
static void ReportError_Divide_ByteByte ()
static void ReportError_Divide_DoubleDouble ()
static void ReportError_Divide_FloatFloat ()
static void ReportError_Divide_Int64Int64 ()
static void ReportError_Divide_IntInt ()
static void ReportError_Divide_IntPointOnInt ()
static void ReportError_Divide_IntPointOnIntPoint ()
static void ReportError_Divide_Vector2DFloat ()
static void ReportError_Divide_Vector2DVector2D ()
static void ReportError_Divide_VectorFloat ()
static void ReportError_Divide_VectorInt ()
static void ReportError_Divide_VectorVector ()
static void ReportError_Percent_ByteByte ()
static void ReportError_Percent_Int64Int64 ()
static void ReportError_Percent_IntInt ()
static void ReportError_ProjectVectorOnToVector ()
static void ReportError_Sqrt ()
Private Attributes
float float float A = 1.0f)
float float float float & A
AdvancedDisplay = "3"
double double Alpha
FVector AngularVelocity
const FVector const FPlane & APlane
float & AverageValue
const FTransform float & Azimuth
double B
float float B
float float float & B
const FBox & B
const FString & B
const FText B
const FName B
int32 B
FVector B
FRotator B
FLinearColor B
const FTransform & B
UObject * B
UClass * B
double Base = 1.0)
float float float float float float bool bClamp = false
const TArray< FVector > const FVector FVector FRotator float float bool bDebugDraw = false)
float bool bIncludeZ = false)
float float float float float float bool float float bool bInitializeFromTarget = false)
BlueprintAutocast
BlueprintInternalUseOnly
FBox Box
FVector FVector BoxExtent
const FTransform FVector BoxExtent
const FTransform FBox BoxExtent
FVector BoxOrigin
const FTransform & BoxWorldTransform
const FString bool bPickA
const FText bool bPickA
const FName bool bPickA
int32 bool bPickA
double bool bPickA
FVector bool bPickA
FRotator bool bPickA
FLinearColor bool bPickA
const FTransform bool bPickA
bool bRoll
UObject bool bSelectA
UClass bool bSelectA
Category
const FVector Center
CommutativeAssociativeBinaryOperator
CompactNodeTitle = "=="
const FVector & ConeDir
float ConeHalfAngleInDegrees
const FVector float ConeHalfAngleInDegrees
float ConeHalfAngleInRadians
const FVector float ConeHalfAngleInRadians
float float float CriticalDampingFactor
int32 int32 Day
int32 int32 int32 & Day
int32 & Days
FVector2D float DeltaTime
FVector float DeltaTime
double double DeltaTime
FRotator float DeltaTime
float float float float DeltaTime
int32 Denominator = 1)
int32 int32 & Denominator
float DistanceInterval = 200.f
const FTransform float float & Elevation
double double double Exponent
const FVector & Extent
const FVector & FloorNormal
int32 int32 int32 int32 FractionNano
int32 int32 int32 int32 int32 & FractionNano
FFrameNumber & Frame
FFrameRate FrameRate
FFrameNumber FFrameRate & FrameRate
float G
float float & G
const FVector HalfSize
const FVector const FVector HalfSize
int32 int32 int32 Hour = 0
int32 int32 int32 int32 & Hour
int32 Hours
int32 int32 & Hours
const float const float InDefaultValue = 0.0f)
float float InDeltaRate
float InDesired
int32 & IndexOfMaxValue
int32 & IndexOfMinValue
int32 & InitialSeed
FVector InNormal
float float InPhase = 0.0f)
const TArray< FVector > & InPoints
float InPulsesPerSecond = 1.0f
double InRangeA
double double InRangeB
FVector2D float float InterpSpeed
FVector float float InterpSpeed
double double double InterpSpeed
FRotator float float InterpSpeed
const FVector const FPlane float FVector & Intersection
const FVector FVector FVector float FVector & Intersection
const float InTime
Keywords
float float Length = 1.0f)
FVector FVector LineDirection
const FVector & LineEnd
FVector LineOrigin
FVector & Location
float float float float float Mass = 1.f
Max
int32 Max
int64 Max
double Max
FVector Max
FVector2D Max
int32 int32 Max
float float Max
float Max
float float MaxDistance
FVector float MaxDistance
FRotator float MaxDistance
float float MaxPitchInDegrees
const FVector float float MaxPitchInDegrees
float float MaxPitchInRadians
const FVector float float MaxPitchInRadians
int32 int32 & MaxValue
int32 float & MaxValue
int32 uint8 & MaxValue
float float float float float float bool float float MaxValue = 1.f
float float float float MaxWeight
FVector float float float MaxWeight
FRotator float float float MaxWeight
float MaxYawInDegrees
const FVector float MaxYawInDegrees
float MaxYawInRadians
const FVector float MaxYawInRadians
float & MedianValue
meta
int32 int32 int32 int32 int32 int32 Millisecond = 0)
int32 int32 int32 int32 int32 int32 int32 & Millisecond
int32 int32 int32 int32 Milliseconds
int32 int32 int32 int32 int32 & Milliseconds
Min = "0"
int32 Min
float Min
int32 int32 int32 int32 Minute = 0
int32 int32 int32 int32 int32 & Minute
int32 int32 Minutes
int32 int32 int32 & Minutes
int32 int32 & MinValue
int32 float & MinValue
int32 uint8 & MinValue
float float float float float float bool float MinValue = -1.f
float float float MinWeight
FVector float float MinWeight
FRotator float float MinWeight
int32 Month
int32 int32 & Month
const FVector & Negative
int32 NewSeed
FVector Normal
int32 & Numerator
const FBox & OuterTest
double double double OutRangeA
double double double double OutRangeB
const TArray< FVector > const FVector FVector & OutRectCenter
const TArray< FVector > const FVector FVector FRotator float & OutRectLengthX
const TArray< FVector > const FVector FVector FRotator float float & OutRectLengthY
const TArray< FVector > const FVector FVector FRotator & OutRectRotation
const FVector const FVector float & OutSlopePitchDegreeAngle
const FVector const FVector float float & OutSlopeRollDegreeAngle
TSubclassOf< class UObject > ParentClass
float Pitch
float float & Pitch
const FVector FVector FVector PlaneNormal
const FVector FVector PlaneOrigin
const FVector & Point
const FVector const FVector & Positive
float PreviousSample
FVector PreviousSample
FRotator PreviousSample
float & R
const FRandomStream & RandomStream
double double RangeMax
double RangeMin
const FTransform & ReferenceFrame
FDateTime & Result
FTimespan & Result
FVector Right
FVector FRotator & Rotation
float S
const TArray< FVector > const FVector & SampleSurfaceNormal
FVector FRotator FVector & Scale
ScriptConstant = "Identity"
ScriptConstantHost
ScriptMethod = "Vector2D"
ScriptOperator = "=="
int32 int32 int32 int32 int32 Second = 0
int32 int32 int32 int32 int32 int32 & Second
int32 int32 int32 Seconds
int32 int32 int32 int32 & Seconds
FVector Segment1End
FVector FVector FVector FVector & Segment1Point
FVector FVector FVector Segment2End
FVector FVector FVector FVector FVector & Segment2Point
FVector FVector Segment2Start
FVector FVector SegmentEnd
FVector SegmentStart
float float Stiffness
const FRandomStream & Stream
int32 const FRandomStream & Stream
float const FRandomStream & Stream
const FVector const FRandomStream & Stream
float float const FRandomStream & Stream
FFrameRate float SubFrame = 0.f)
FFrameNumber FFrameRate float & SubFrame
const FVector const FPlane float & T
const FVector FVector FVector float & T
FVector2D Target
FVector Target
const FVector & Target
double Target
FRotator Target
float Target
const FVector & TargetLocation
float float float float float float TargetVelocityAmount = 1.f
float Tolerance = 0.1f)
FVector FVector Up
const FVector const FVector & UpVector
float float V
float Velocity
FVector Velocity
float float float W
float float float float & W
float Weight
float float Weight
FVector float Weight
FRotator float Weight
double & X
float & X
const FVector & X
FVector & X
int32 XSize
double Y
double double & Y
float float & Y
const FVector & Y
FVector FVector & Y
float Y
float & Yaw
int32 & Year
int32 int32 YSize
double double Z { return FVector_NetQuantize(X, Y, Z)
double double double & Z { BreakVector((FVector)InVec, X, Y, Z)
float float float & Z
const FVector & Z
FVector FVector FVector & Z
float float Z
Detailed Description
Definition at line 189 of file KismetMathLibrary.h.
Member Function Documentation
Conv_TransformToMatrix()
BlueprintAutocast FMatrix UKismetMathLibrary::Conv_TransformToMatrix (const FTransform & Transform) static private
References Conv_TransformToMatrix(), and Transform.
Referenced by Conv_TransformToMatrix().
DECLARE_FUNCTION()
UKismetMathLibrary::DECLARE_FUNCTION (execPercent_FloatFloat) inline private
Custom thunk to allow script stack trace in case of modulo by zero.
Definition at line 530 of file KismetMathLibrary.h.
References A, B, DECLARE_FUNCTION(), GenericPercent_FloatFloat(), FFrame::KismetExecutionMessage(), P_FINISH, P_GET_PROPERTY, RESULT_PARAM, TEXT, and ELogVerbosity::Warning.
Referenced by DECLARE_FUNCTION().
GENERATED_UCLASS_BODY()
UKismetMathLibrary::GENERATED_UCLASS_BODY () private
Returns a uniformly distributed random bool.
References Category, meta, UE_INL_API, and UFUNCTION().
GenericPercent_FloatFloat()
double UKismetMathLibrary::GenericPercent_FloatFloat (double A, double B) static private
References A, B, and GenericPercent_FloatFloat().
Referenced by DECLARE_FUNCTION(), and GenericPercent_FloatFloat().
RandomPointInBoundingBox_Box()
NotBlueprintThreadSafe FVector UKismetMathLibrary::RandomPointInBoundingBox_Box (const FBox Box) static private
References Box, FVector, RandomPointInBoundingBox_Box(), and UE_INL_API.
Referenced by RandomPointInBoundingBox_Box().
ReportError_DaysInMonth()
void UKismetMathLibrary::ReportError_DaysInMonth () static private
ReportError_Divide_ByteByte()
void UKismetMathLibrary::ReportError_Divide_ByteByte () static private
ReportError_Divide_DoubleDouble()
void UKismetMathLibrary::ReportError_Divide_DoubleDouble () static private
ReportError_Divide_FloatFloat()
void UKismetMathLibrary::ReportError_Divide_FloatFloat () static private
ReportError_Divide_Int64Int64()
void UKismetMathLibrary::ReportError_Divide_Int64Int64 () static private
ReportError_Divide_IntInt()
void UKismetMathLibrary::ReportError_Divide_IntInt () static private
ReportError_Divide_IntPointOnInt()
void UKismetMathLibrary::ReportError_Divide_IntPointOnInt () static private
ReportError_Divide_IntPointOnIntPoint()
void UKismetMathLibrary::ReportError_Divide_IntPointOnIntPoint () static private
ReportError_Divide_Vector2DFloat()
void UKismetMathLibrary::ReportError_Divide_Vector2DFloat () static private
ReportError_Divide_Vector2DVector2D()
void UKismetMathLibrary::ReportError_Divide_Vector2DVector2D () static private
ReportError_Divide_VectorFloat()
void UKismetMathLibrary::ReportError_Divide_VectorFloat () static private
ReportError_Divide_VectorInt()
void UKismetMathLibrary::ReportError_Divide_VectorInt () static private
ReportError_Divide_VectorVector()
void UKismetMathLibrary::ReportError_Divide_VectorVector () static private
ReportError_Percent_ByteByte()
void UKismetMathLibrary::ReportError_Percent_ByteByte () static private
ReportError_Percent_Int64Int64()
void UKismetMathLibrary::ReportError_Percent_Int64Int64 () static private
ReportError_Percent_IntInt()
void UKismetMathLibrary::ReportError_Percent_IntInt () static private
ReportError_ProjectVectorOnToVector()
void UKismetMathLibrary::ReportError_ProjectVectorOnToVector () static private
ReportError_Sqrt()
void UKismetMathLibrary::ReportError_Sqrt () static private
UE_DEPRECATED() [1/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "This method has been deprecated and will be removed. Use the double version instead.") private
Converts a float into a LinearColor, where each element is a float.
References UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [2/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "This method has been deprecated and will be removed. Use the double version instead.") private
Converts a bool to a float (0.0f or 1.0f)
References UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [3/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "This method has been deprecated and will be removed. Use the double version instead.") private
Converts a byte to a float.
References UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [4/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "This method has been deprecated and will be removed. Use the double version instead.") private
Converts an integer to a float.
References UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [5/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "This method has been deprecated and will be removed. Use the double version instead.") private
Converts a float into a vector, where each element is that float.
References FVector, UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [6/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomBoolWithWeightFromStream taking the FRandomStream as the first argument.") private
References UE_DEPRECATED().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [7/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomFloatInRangeFromStream taking the FRandomStream as the first argument.") private
References UE_DEPRECATED().
UE_DEPRECATED() [8/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomIntegerFromStream taking the FRandomStream as the first argument.") private
References UE_DEPRECATED().
UE_DEPRECATED() [9/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomIntegerInRangeFromStream taking the FRandomStream as the first argument.") private
References UE_DEPRECATED().
UE_DEPRECATED() [10/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomPointInBoundingBoxFromStream taking the FRandomStream as the first argument.") const private
References UE_DEPRECATED().
UE_DEPRECATED() [11/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomPointInBoundingBoxFromStream_Box taking the FRandomStream as the first argument.") const private
References Box, FVector, Stream, and UE_INL_API.
UE_DEPRECATED() [12/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomRotatorFromStream taking the FRandomStream as the first argument.") private
References bRoll, Stream, UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [13/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomUnitVectorInConeInDegreesFromStream taking the FRandomStream as the first argument.") const & private
References ConeDir, ConeHalfAngleInDegrees, FVector, and Stream.
UE_DEPRECATED() [14/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomUnitVectorInConeInRadiansFromStream taking the FRandomStream as the first argument.") const & private
References ConeDir, ConeHalfAngleInRadians, FVector, Stream, UE_DEPRECATED(), and UE_INL_API.
UE_DEPRECATED() [15/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomUnitVectorInEllipticalConeInDegreesFromStream taking the FRandomStream as the first argument.") const & private
References ConeDir, FVector, MaxPitchInDegrees, MaxYawInDegrees, and Stream.
UE_DEPRECATED() [16/17]
UKismetMathLibrary::UE_DEPRECATED (5. 2, "Use RandomUnitVectorInEllipticalConeInRadiansFromStream taking the FRandomStream as the first argument.") const & private
References UE_DEPRECATED().
UE_DEPRECATED() [17/17]
UKismetMathLibrary::UE_DEPRECATED (5. 3, "This method has been deprecated and will be removed. Use the double version instead.") private
References UE_DEPRECATED().
UFUNCTION() [1/736]
UKismetMathLibrary::UFUNCTION () private
Returns the logical complement of the Boolean value (NOT A)
UFUNCTION() [2/736]
UKismetMathLibrary::UFUNCTION () private
Returns the logical AND of two values (A AND B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [3/736]
UKismetMathLibrary::UFUNCTION () private
Returns the logical NAND of two values (A AND B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [4/736]
UKismetMathLibrary::UFUNCTION () private
Returns the logical OR of two values (A OR B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [5/736]
UKismetMathLibrary::UFUNCTION () private
Returns the logical eXclusive OR of two values (A XOR B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [6/736]
UKismetMathLibrary::UFUNCTION () private
Returns the logical Not OR of two values (A NOR B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [7/736]
UKismetMathLibrary::UFUNCTION () private
Multiplication (A * B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [8/736]
UKismetMathLibrary::UFUNCTION () private
Division (A / B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [9/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [10/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [11/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than B (A < B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [12/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than B (A > B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [13/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than or equal to B (A <= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [14/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than or equal to B (A >= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [15/736]
UKismetMathLibrary::UFUNCTION () private
Multiplication (A * B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [16/736]
UKismetMathLibrary::UFUNCTION () private
Division (A / B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [17/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [18/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [19/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than B (A < B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [20/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than B (A > B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [21/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than or equal to B (A <= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [22/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than or equal to B (A >= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [23/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise AND (A & B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [24/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise XOR (A ^ B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [25/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise OR (A | B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [26/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise NOT (~A)
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [27/736]
UKismetMathLibrary::UFUNCTION () private
Multiplication (A * B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [28/736]
UKismetMathLibrary::UFUNCTION () private
Division (A / B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [29/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [30/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [31/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than B (A < B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [32/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than B (A > B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [33/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than or equal to B (A <= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [34/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than or equal to B (A >= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [35/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise AND (A & B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [36/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise XOR (A ^ B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [37/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise OR (A | B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [38/736]
UKismetMathLibrary::UFUNCTION () private
Bitwise NOT (~A)
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [39/736]
UKismetMathLibrary::UFUNCTION () private
Power (Base to the Exp-th power)
References Base, Category, Exp, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [40/736]
UKismetMathLibrary::UFUNCTION () private
Multiplication (A * B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [41/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [42/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [43/736]
UKismetMathLibrary::UFUNCTION () private
Multiplication (A * B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [44/736]
UKismetMathLibrary::UFUNCTION () private
Division (A / B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [45/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is Less than B (A < B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [46/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than B (A > B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [47/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is Less than or equal to B (A <= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [48/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than or equal to B (A >= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [49/736]
UKismetMathLibrary::UFUNCTION () private
Returns the hypotenuse of a right-angled triangle given the width and height.
References Category, Keywords, meta, UFUNCTION(), and Width.
UFUNCTION() [50/736]
UKismetMathLibrary::UFUNCTION () private
Returns the value of PI.
References Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [51/736]
UKismetMathLibrary::UFUNCTION () private
Returns the value of TAU (= 2 * PI)
References Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [52/736]
UKismetMathLibrary::UFUNCTION () private
Returns radians value based on the input degrees.
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [53/736]
UKismetMathLibrary::UFUNCTION () private
Returns degrees value based on the input radians.
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [54/736]
UKismetMathLibrary::UFUNCTION () private
Clamps an arbitrary angle to be between the given angles.
Will clamp to nearest boundary.
Parameters
MinAngleDegrees "from" angle that defines the beginning of the range of valid angles (sweeping clockwise)
MaxAngleDegrees "to" angle that defines the end of the range of valid angles
Returns
Returns clamped angle in the range -180..180.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [55/736]
UKismetMathLibrary::UFUNCTION () private
Easeing between A and B using a specified easing function.
References A, Alpha, B, BlueprintInternalUseOnly, Category, meta, and UFUNCTION().
UFUNCTION() [56/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A down towards negative infinity / down to the previous integer (e.g., -1.6 becomes -2 and 1.6 becomes 1)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [57/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A towards zero, truncating the fractional part (e.g., -1.6 becomes -1 and 1.6 becomes 1)
References A, BlueprintAutocast, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [58/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A to the nearest integer (e.g., -1.6 becomes -2 and 1.6 becomes 2)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [59/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A down towards negative infinity / down to the previous integer (e.g., -1.6 becomes -2 and 1.6 becomes 1)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [60/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A towards zero, truncating the fractional part (e.g., -1.6 becomes -1 and 1.6 becomes 1)
References A, BlueprintAutocast, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [61/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A up towards positive infinity / up to the next integer (e.g., -1.6 becomes -1 and 1.6 becomes 2)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [62/736]
UKismetMathLibrary::UFUNCTION () private
Multiplies the input value by pi.
References Category, Keywords, meta, UE_INL_API, UFUNCTION(), and Value.
UFUNCTION() [63/736]
UKismetMathLibrary::UFUNCTION () private
Zero Int Point (0, 0)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [64/736]
UKismetMathLibrary::UFUNCTION () private
One Int Point (1, 1)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [65/736]
UKismetMathLibrary::UFUNCTION () private
Up Int Point (0, -1)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [66/736]
UKismetMathLibrary::UFUNCTION () private
Left Int Point (-1, 0)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [67/736]
UKismetMathLibrary::UFUNCTION () private
Right Int Point (1, 0)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [68/736]
UKismetMathLibrary::UFUNCTION () private
Down Int Point (0, 1)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [69/736]
UKismetMathLibrary::UFUNCTION () private
Returns IntPoint A added by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [70/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [71/736]
UKismetMathLibrary::UFUNCTION () private
Returns IntPoint A subtracted by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [72/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [73/736]
UKismetMathLibrary::UFUNCTION () private
Returns IntPoint A multiplied by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [74/736]
UKismetMathLibrary::UFUNCTION () private
Multiplication (A * B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [75/736]
UKismetMathLibrary::UFUNCTION () private
Returns IntPoint A divided by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [76/736]
UKismetMathLibrary::UFUNCTION () private
Division (A * B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [77/736]
UKismetMathLibrary::UFUNCTION () private
2D one vector constant (1,1)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [78/736]
UKismetMathLibrary::UFUNCTION () private
2D unit vector constant along the 45 degree angle or symmetrical positive axes (sqrt(.5),sqrt(.5)) or (.707,.707).
https://en.wikipedia.org/wiki/Unit_vector
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [79/736]
UKismetMathLibrary::UFUNCTION () private
2D zero vector constant (0,0)
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [80/736]
UKismetMathLibrary::UFUNCTION () private
Returns addition of Vector A and Vector B (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [81/736]
UKismetMathLibrary::UFUNCTION () private
Returns Vector A added by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [82/736]
UKismetMathLibrary::UFUNCTION () private
Returns subtraction of Vector B from Vector A (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [83/736]
UKismetMathLibrary::UFUNCTION () private
Returns Vector A subtracted by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [84/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise Vector multiplication (Result = {A.x*B.x, A.y*B.y})
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [85/736]
UKismetMathLibrary::UFUNCTION () private
Returns Vector A scaled by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [86/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise Vector divide (Result = {A.x/B.x, A.y/B.y})
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [87/736]
UKismetMathLibrary::UFUNCTION () private
Returns Vector A divided by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [88/736]
UKismetMathLibrary::UFUNCTION () private
Gets a negated copy of the vector.
References A, Category, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [89/736]
UKismetMathLibrary::UFUNCTION () private
Set the values of the vector directly.
Parameters
InX New X coordinate.
InY New Y coordinate.
References A, Category, meta, ScriptMethod, UFUNCTION(), UPARAM(), X, and Y.
UFUNCTION() [90/736]
UKismetMathLibrary::UFUNCTION () private
Creates a copy of this vector with both axes clamped to the given range.
Returns
New vector with clamped axes.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [91/736]
UKismetMathLibrary::UFUNCTION () private
Distance between two 2D points.
Parameters
V1 The first point.
V2 The second point.
Returns
The distance between two 2D points.
References Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [92/736]
UKismetMathLibrary::UFUNCTION () private
Squared distance between two 2D points.
Parameters
V1 The first point.
V2 The second point.
Returns
The squared distance between two 2D points.
References Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [93/736]
UKismetMathLibrary::UFUNCTION () private
Get a copy of this vector with absolute value of each component.
Returns
A copy of this vector with absolute value of each component.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [94/736]
UKismetMathLibrary::UFUNCTION () private
Get the maximum absolute value of the vector's components.
Returns
The maximum absolute value of the vector's components.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [95/736]
UKismetMathLibrary::UFUNCTION () private
Get the maximum value of the vector's components.
Returns
The maximum value of the vector's components.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [96/736]
UKismetMathLibrary::UFUNCTION () private
Get the minimum value of the vector's components.
Returns
The minimum value of the vector's components.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [97/736]
UKismetMathLibrary::UFUNCTION () private
Rotates around axis (0,0,1)
Parameters
AngleDeg Angle to rotate (in degrees)
Returns
Rotated Vector
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [98/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether vector is near to zero within a specified tolerance.
Parameters
Tolerance Error tolerance.
Returns
true if vector is in tolerance to zero, otherwise false.
References A, Category, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [99/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether all components of the vector are exactly zero.
Returns
true if vector is exactly zero, otherwise false.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [100/736]
UKismetMathLibrary::UFUNCTION () private
Returns a unit normal version of the 2D vector.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [101/736]
UKismetMathLibrary::UFUNCTION () private
Converts spherical coordinates on the unit sphere into a Cartesian unit length vector.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [102/736]
UKismetMathLibrary::UFUNCTION () private
Util to convert this vector into a unit direction vector and its original length.
Parameters
OutDir Reference passed in to store unit direction vector.
OutLength Reference passed in to store length of the vector.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [103/736]
UKismetMathLibrary::UFUNCTION () private
Returns the length of a 2D Vector.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [104/736]
UKismetMathLibrary::UFUNCTION () private
Returns the squared length of a 2D Vector.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [105/736]
UKismetMathLibrary::UFUNCTION () private
3D vector zero constant (0,0,0)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [106/736]
UKismetMathLibrary::UFUNCTION () private
3D vector one constant (1,1,1)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [107/736]
UKismetMathLibrary::UFUNCTION () private
3D vector Unreal forward direction constant (1,0,0)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [108/736]
UKismetMathLibrary::UFUNCTION () private
3D vector Unreal backward direction constant (-1,0,0)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [109/736]
UKismetMathLibrary::UFUNCTION () private
3D vector Unreal up direction constant (0,0,1)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [110/736]
UKismetMathLibrary::UFUNCTION () private
3D vector Unreal down direction constant (0,0,-1)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [111/736]
UKismetMathLibrary::UFUNCTION () private
3D vector Unreal right direction constant (0,1,0)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [112/736]
UKismetMathLibrary::UFUNCTION () private
3D vector Unreal left direction constant (0,-1,0)
References Category, FVector, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [113/736]
UKismetMathLibrary::UFUNCTION () private
Assign the values of the supplied vector.
Parameters
InVector Vector to copy values from.
References A, Category, FVector, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [114/736]
UKismetMathLibrary::UFUNCTION () private
Set the values of the vector directly.
Parameters
InX New X coordinate.
InY New Y coordinate.
InZ New Z coordinate.
References A, Category, FVector, meta, ScriptMethod, UFUNCTION(), UPARAM(), X, Y, and Z.
UFUNCTION() [115/736]
UKismetMathLibrary::UFUNCTION () private
Return the FRotator orientation corresponding to the direction in which the vector points.
Sets Yaw and Pitch to the proper numbers, and sets Roll to zero because the roll can't be determined from a vector.
Returns
FRotator from the Vector's direction, without any roll.
References BlueprintAutocast, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [116/736]
UKismetMathLibrary::UFUNCTION () private
Create a rotation from an axis and supplied angle (in degrees)
References Angle, Axis, Category, FVector, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [117/736]
UKismetMathLibrary::UFUNCTION () private
Interpolate from a vector to the direction of another vector along a spherical path.
Parameters
Vector Vector we interpolate from
Direction Target direction we interpolate to
Alpha interpolation amount, usually between 0-1
Returns
Vector after interpolating between Vector and Direction along a spherical path. The magnitude will remain the length of the starting vector.
References Alpha, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and Vector.
UFUNCTION() [118/736]
UKismetMathLibrary::UFUNCTION () private
Interpolate from normalized vector A to normalized vector B along a spherical path.
Parameters
NormalA Start direction of interpolation, must be normalized.
NormalB End target direction of interpolation, must be normalized.
Alpha interpolation amount, usually between 0-1
Returns
Vector after interpolating between A and B along a spherical path.
References Alpha, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [119/736]
UKismetMathLibrary::UFUNCTION () private
Vector addition.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [120/736]
UKismetMathLibrary::UFUNCTION () private
Adds a float to each component of a vector.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [121/736]
UKismetMathLibrary::UFUNCTION () private
Adds an integer to each component of a vector.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [122/736]
UKismetMathLibrary::UFUNCTION () private
Vector subtraction.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [123/736]
UKismetMathLibrary::UFUNCTION () private
Subtracts a float from each component of a vector.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [124/736]
UKismetMathLibrary::UFUNCTION () private
Subtracts an integer from each component of a vector.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [125/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise Vector multiplication (Result = {A.x*B.x, A.y*B.y, A.z*B.z})
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [126/736]
UKismetMathLibrary::UFUNCTION () private
Scales Vector A by B.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [127/736]
UKismetMathLibrary::UFUNCTION () private
Scales Vector A by B.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [128/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise Vector division (Result = {A.x/B.x, A.y/B.y, A.z/B.z})
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, and UFUNCTION().
UFUNCTION() [129/736]
UKismetMathLibrary::UFUNCTION () private
Vector divide by a float.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [130/736]
UKismetMathLibrary::UFUNCTION () private
Vector divide by an integer.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [131/736]
UKismetMathLibrary::UFUNCTION () private
Negate a vector.
References A, Category, FVector, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [132/736]
UKismetMathLibrary::UFUNCTION () private
Returns the dot product of two 3d vectors - see http://mathworld.wolfram.com/DotProduct.html.
References A, B, Category, CompactNodeTitle, FVector, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [133/736]
UKismetMathLibrary::UFUNCTION () private
Returns the cross product of two 3d vectors - see http://mathworld.wolfram.com/CrossProduct.html.
References A, B, Category, CompactNodeTitle, FVector, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [134/736]
UKismetMathLibrary::UFUNCTION () private
Returns result of vector A rotated by Rotator B.
References A, B, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [135/736]
UKismetMathLibrary::UFUNCTION () private
Returns result of vector A rotated by AngleDeg around Axis.
References Axis, Category, FVector, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [136/736]
UKismetMathLibrary::UFUNCTION () private
Returns result of vector A rotated by the inverse of Rotator B.
References A, B, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [137/736]
UKismetMathLibrary::UFUNCTION () private
When this vector contains Euler angles (degrees), ensure that angles are between +/-180.
References A, Category, FVector, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [138/736]
UKismetMathLibrary::UFUNCTION () private
Create a copy of this vector, with its magnitude/size/length clamped between Min and Max.
References A, Category, FVector, Max, meta, Min, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [139/736]
UKismetMathLibrary::UFUNCTION () private
Create a copy of this vector, with the 2D magnitude/size/length clamped between Min and Max.
Z is unchanged.
References A, Category, FVector, Max, meta, Min, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [140/736]
UKismetMathLibrary::UFUNCTION () private
Create a copy of this vector, with its maximum magnitude/size/length clamped to MaxSize.
References A, Category, FVector, Max, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [141/736]
UKismetMathLibrary::UFUNCTION () private
Create a copy of this vector, with the maximum 2D magnitude/size/length clamped to MaxSize.
Z is unchanged.
References A, Category, FVector, Max, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [142/736]
UKismetMathLibrary::UFUNCTION () private
Find the minimum element (X, Y or Z) of a vector.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [143/736]
UKismetMathLibrary::UFUNCTION () private
Find the maximum element (X, Y or Z) of a vector.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [144/736]
UKismetMathLibrary::UFUNCTION () private
Find the maximum absolute element (abs(X), abs(Y) or abs(Z)) of a vector.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [145/736]
UKismetMathLibrary::UFUNCTION () private
Find the minimum absolute element (abs(X), abs(Y) or abs(Z)) of a vector.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [146/736]
UKismetMathLibrary::UFUNCTION () private
Get a copy of this vector with absolute value of each component.
Returns
A copy of this vector with absolute value of each component.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [147/736]
UKismetMathLibrary::UFUNCTION () private
Find the minimum elements (X, Y and Z) between the two vector's components.
References A, B, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [148/736]
UKismetMathLibrary::UFUNCTION () private
Find the maximum elements (X, Y and Z) between the two vector's components.
References A, B, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [149/736]
UKismetMathLibrary::UFUNCTION () private
Get a copy of the vector as sign only.
Each component is set to +1 or -1, with the sign of zero treated as +1.
Parameters
A copy of the vector with each component set to +1 or -1
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [150/736]
UKismetMathLibrary::UFUNCTION () private
Projects 2D components of vector based on Z.
Returns
Projected version of vector based on Z.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [151/736]
UKismetMathLibrary::UFUNCTION () private
Convert a direction vector into a 'heading' angle.
Returns
'Heading' angle between +/-PI radians. 0 is pointing down +X.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [152/736]
UKismetMathLibrary::UFUNCTION () private
Returns the cosine of the angle between this vector and another projected onto the XY plane (no Z).
Parameters
B the other vector to find the 2D cosine of the angle with.
Returns
The cosine.
References A, B, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [153/736]
UKismetMathLibrary::UFUNCTION () private
Converts a vector containing degree values to a vector containing radian values.
Returns
Vector containing radian values
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [154/736]
UKismetMathLibrary::UFUNCTION () private
Converts a vector containing radian values to a vector containing degree values.
Returns
Vector containing degree values
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [155/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Cartesian unit vector into spherical coordinates on the unit sphere.
Returns
Output Theta will be in the range [0, PI], and output Phi will be in the range [-PI, PI].
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [156/736]
UKismetMathLibrary::UFUNCTION () private
Returns the length of the vector.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [157/736]
UKismetMathLibrary::UFUNCTION () private
Returns the squared length of the vector.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [158/736]
UKismetMathLibrary::UFUNCTION () private
Returns the length of the vector's XY components.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [159/736]
UKismetMathLibrary::UFUNCTION () private
Returns the squared length of the vector's XY components.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [160/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether vector is near to zero within a specified tolerance.
Parameters
Tolerance Error tolerance.
Returns
true if vector is in tolerance to zero, otherwise false.
References A, Category, FVector, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [161/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether all components of the vector are exactly zero.
Returns
true if vector is exactly zero, otherwise false.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [162/736]
UKismetMathLibrary::UFUNCTION () private
Determines if any component is not a number (NAN)
Returns
true if one or more components is NAN, otherwise false.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [163/736]
UKismetMathLibrary::UFUNCTION () private
Gets a normalized unit copy of the vector, ensuring it is safe to do so based on the length.
Returns zero vector if vector length is too small to safely normalize.
Parameters
Tolerance Minimum squared vector length.
Returns
A normalized copy if safe, (0,0,0) otherwise.
References A, Category, FVector, Keywords, meta, Normal, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [164/736]
UKismetMathLibrary::UFUNCTION () private
Uses a simple spring model to interpolate a vector from Current to Target.
Parameters
Current Current value
Target Target value
SpringState Data related to spring model (velocity, error, etc..) - Create a unique variable per spring
Stiffness How stiff the spring model is (more stiffness means more oscillation around the target value)
CriticalDampingFactor How much damping to apply to the spring (0 means no damping, 1 means critically damped which means no oscillation)
DeltaTime Time difference since the last update
Mass Multiplier that acts like mass on a spring
TargetVelocityAmount If 1 then the target velocity will be calculated and used, which results following the target more closely/without lag. Values down to zero (recommended when using this to smooth data) will progressively disable this effect.
bClamp Whether to use the Min/Max values to clamp the motion
MinValue Clamps the minimum output value and cancels the velocity if it reaches this limit
MaxValue Clamps the maximum output value and cancels the velocity if it reaches this limit
bInitializeFromTarget If set then the current value will be set from the target on the first update
References AdvancedDisplay, bClamp, bInitializeFromTarget, Category, CriticalDampingFactor, DeltaTime, FVector, Keywords, Mass, MaxValue, meta, MinValue, ScriptMethod, Stiffness, Target, TargetVelocityAmount, UFUNCTION(), and UPARAM().
UFUNCTION() [165/736]
UKismetMathLibrary::UFUNCTION () private
Uses a simple spring model to interpolate a quaternion from Current to Target.
Parameters
Current Current value
Target Target value
SpringState Data related to spring model (velocity, error, etc..) - Create a unique variable per spring
Stiffness How stiff the spring model is (more stiffness means more oscillation around the target value)
CriticalDampingFactor How much damping to apply to the spring (0 means no damping, 1 means critically damped which means no oscillation)
DeltaTime Time difference since the last update
Mass Multiplier that acts like mass on a spring
TargetVelocityAmount If 1 then the target velocity will be calculated and used, which results following the target more closely/without lag. Values down to zero (recommended when using this to smooth data) will progressively disable this effect.
bInitializeFromTarget If set then the current value will be set from the target on the first update
References AdvancedDisplay, bInitializeFromTarget, Category, CriticalDampingFactor, DeltaTime, Keywords, Mass, meta, ScriptMethod, Stiffness, Target, TargetVelocityAmount, UFUNCTION(), and UPARAM().
UFUNCTION() [166/736]
UKismetMathLibrary::UFUNCTION () private
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
Produces a result like shining a laser at a mirror!
Parameters
Direction Direction vector the ray is coming from.
SurfaceNormal A normal of the surface the ray should be reflected on.
Returns
Reflected vector.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [167/736]
UKismetMathLibrary::UFUNCTION () private
Mirrors a vector about a plane.
Parameters
Plane Plane to mirror about.
Returns
Mirrored vector.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [168/736]
UKismetMathLibrary::UFUNCTION () private
Gets a copy of this vector snapped to a grid.
Parameters
InGridSize Grid dimension / step.
Returns
A copy of this vector snapped to a grid.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [169/736]
UKismetMathLibrary::UFUNCTION () private
Get a copy of this vector, clamped inside of an axis aligned cube centered at the origin.
Parameters
InRadius Half size of the cube (or radius of sphere circumscribed in the cube).
Returns
A copy of this vector, bound by cube.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [170/736]
UKismetMathLibrary::UFUNCTION () private
Add a vector to this and clamp the result to an axis aligned cube centered at the origin.
Parameters
InAddVect Vector to add.
InRadius Half size of the cube.
References A, Category, FVector, Keywords, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [171/736]
UKismetMathLibrary::UFUNCTION () private
Get a copy of this vector, clamped inside of the specified axis aligned cube.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [172/736]
UKismetMathLibrary::UFUNCTION () private
Gets a copy of this vector projected onto the input vector, which is assumed to be unit length.
Parameters
InNormal Vector to project onto (assumed to be unit length).
Returns
Projected vector.
References Category, FVector, InNormal, Keywords, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [173/736]
UKismetMathLibrary::UFUNCTION () private
Projects one vector (V) onto another (Target) and returns the projected vector.
If Target is nearly zero in length, returns the zero vector.
Parameters
V Vector to project.
Target Vector on which we are projecting.
Returns
V projected on to Target.
References Category, FVector, Keywords, meta, ScriptMethod, Target, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [174/736]
UKismetMathLibrary::UFUNCTION () private
Projects/snaps a point onto a plane defined by a point on the plane and a plane normal.
Parameters
Point Point to project onto the plane.
PlaneBase A point on the plane.
PlaneNormal Normal of the plane.
Returns
Point projected onto the plane.
References Category, FVector, Keywords, meta, PlaneNormal, Point, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [175/736]
UKismetMathLibrary::UFUNCTION () private
Projects a vector onto a plane defined by a normalized vector (PlaneNormal).
Parameters
V Vector to project onto the plane.
PlaneNormal Normal of the plane.
Returns
Vector projected onto the plane.
References Category, FVector, Keywords, meta, PlaneNormal, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [176/736]
UKismetMathLibrary::UFUNCTION () private
4D vector zero constant (0,0,0)
References Category, meta, ScriptConstant, ScriptConstantHost, and UE_INL_API.
UFUNCTION() [177/736]
UKismetMathLibrary::UFUNCTION () private
Makes a 4D vector {X, Y, Z, W}.
References Category, Keywords, meta, UE_INL_API, UFUNCTION(), W, X, Y, and Z.
UFUNCTION() [178/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a 4D vector apart into X, Y, Z, W.
References Category, meta, UE_INL_API, UFUNCTION(), W, X, Y, and Z.
UFUNCTION() [179/736]
UKismetMathLibrary::UFUNCTION () private
Returns addition of Vector A and Vector B (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [180/736]
UKismetMathLibrary::UFUNCTION () private
Returns subtraction of Vector B from Vector A (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [181/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise Vector multiplication (Result = {A.x*B.x, A.y*B.y, A.z*B.z, A.w*B.w})
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [182/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise Vector divide (Result = {A.x/B.x, A.y/B.y, A.z/B.z, A.w/B.w})
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [183/736]
UKismetMathLibrary::UFUNCTION () private
Assign the values of the supplied vector.
Parameters
InVector Vector to copy values from.
References A, Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [184/736]
UKismetMathLibrary::UFUNCTION () private
Set the values of the vector directly.
Parameters
InX New X coordinate.
InY New Y coordinate.
InZ New Z coordinate.
InW New W coordinate.
References A, Category, meta, ScriptMethod, UFUNCTION(), UPARAM(), W, X, Y, and Z.
UFUNCTION() [185/736]
UKismetMathLibrary::UFUNCTION () private
Determines if any component is not a number (NAN)
Returns
true if one or more components is NAN, otherwise false.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [186/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether vector is near to zero within a specified tolerance.
The W element is ignored.
Parameters
Tolerance Error tolerance.
Returns
true if vector is in tolerance to zero, otherwise false.
References A, Category, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [187/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether all components of the vector are exactly zero.
Returns
true if vector is exactly zero, otherwise false.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [188/736]
UKismetMathLibrary::UFUNCTION () private
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
Produces a result like shining a laser at a mirror! The W element is ignored.
Parameters
Direction Direction vector the ray is coming from.
SurfaceNormal A normal of the surface the ray should be reflected on.
Returns
Reflected vector.
References Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [189/736]
UKismetMathLibrary::UFUNCTION () private
Transform the input vector4 by a provided matrix4x4 and returns the resulting vector4.
Returns
Transformed vector4.
References Category, Matrix, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [190/736]
UKismetMathLibrary::UFUNCTION () private
Combine 2 rotations to give you the resulting rotation of first applying A, then B.
References A, B, Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [191/736]
UKismetMathLibrary::UFUNCTION () private
Negate a rotator.
References A, Category, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [192/736]
UKismetMathLibrary::UFUNCTION () private
Rotate the world forward vector by the given rotation.
References Category, FVector, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [193/736]
UKismetMathLibrary::UFUNCTION () private
Rotate the world right vector by the given rotation.
References Category, FVector, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [194/736]
UKismetMathLibrary::UFUNCTION () private
Rotate the world up vector by the given rotation.
References Category, FVector, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [195/736]
UKismetMathLibrary::UFUNCTION () private
Get the X direction vector after this rotation.
References BlueprintAutocast, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [196/736]
UKismetMathLibrary::UFUNCTION () private
Get the reference frame direction vectors (axes) described by this rotation.
References A, Category, FVector, Keywords, meta, ScriptMethod, UFUNCTION(), X, Y, and Z.
UFUNCTION() [197/736]
UKismetMathLibrary::UFUNCTION () private
Gets the result of multiplying a Matrix to this.
Parameters
Other The matrix to multiply this by.
Returns
The result of multiplication.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, and UFUNCTION().
UFUNCTION() [198/736]
UKismetMathLibrary::UFUNCTION () private
Gets the result of adding a matrix to this.
Parameters
Other The Matrix to add.
Returns
The result of addition.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, and UFUNCTION().
UFUNCTION() [199/736]
UKismetMathLibrary::UFUNCTION () private
Multiplies all values of the matrix by a float.
If your Matrix represents a Transform that you wish to scale you should use Apply Scale instead
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, and UFUNCTION().
UFUNCTION() [200/736]
UKismetMathLibrary::UFUNCTION () private
Identity quaternion constant.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [201/736]
UKismetMathLibrary::UFUNCTION () private
Returns addition of Vector A and Vector B (A + B)
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [202/736]
UKismetMathLibrary::UFUNCTION () private
Returns subtraction of Vector B from Vector A (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [203/736]
UKismetMathLibrary::UFUNCTION () private
Gets the result of multiplying two quaternions (A * B).
Order matters when composing quaternions: C = A * B will yield a quaternion C that logically first applies B then A to any subsequent transformation (right first, then left).
Parameters
B The Quaternion to multiply by.
Returns
The result of multiplication (A * B).
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [204/736]
UKismetMathLibrary::UFUNCTION () private
Generates the 'smallest' (geodesic) rotation around a sphere between two vectors of arbitrary length.
Parameters
Start Vector the rotation starts from
End Vector the rotation ends at
Returns
Quat that will rotate from Start to End
References Category, End, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [205/736]
UKismetMathLibrary::UFUNCTION () private
Generates the 'smallest' (geodesic) rotation around a sphere between two normals (assumed to be unit length).
Parameters
Start Normalized vector the rotation starts from
End Normalized vector the rotation ends at
Returns
Quat that will rotate from Start to End
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [206/736]
UKismetMathLibrary::UFUNCTION () private
White linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [207/736]
UKismetMathLibrary::UFUNCTION () private
Grey linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [208/736]
UKismetMathLibrary::UFUNCTION () private
Black linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [209/736]
UKismetMathLibrary::UFUNCTION () private
Red linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [210/736]
UKismetMathLibrary::UFUNCTION () private
Green linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [211/736]
UKismetMathLibrary::UFUNCTION () private
Blue linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [212/736]
UKismetMathLibrary::UFUNCTION () private
Yellow linear color.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [213/736]
UKismetMathLibrary::UFUNCTION () private
Transparent linear color - black with 0 opacity/alpha.
References Category, meta, ScriptConstant, ScriptConstantHost, UE_INL_API, and UFUNCTION().
UFUNCTION() [214/736]
UKismetMathLibrary::UFUNCTION () private
Assign contents of InColor.
References Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [215/736]
UKismetMathLibrary::UFUNCTION () private
Assign individual linear RGBA components.
References A, B, Category, G, meta, R, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [216/736]
UKismetMathLibrary::UFUNCTION () private
Assigns an HSV color to a linear space RGB color.
References A, Category, meta, S, ScriptMethod, UFUNCTION(), UPARAM(), and V.
UFUNCTION() [217/736]
UKismetMathLibrary::UFUNCTION () private
Assigns an FColor coming from an observed sRGB output, into a linear color.
Parameters
InSRGB The sRGB color that needs to be converted into linear space.
References Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [218/736]
UKismetMathLibrary::UFUNCTION () private
Assigns an FColor coming from an observed Pow(1/2.2) output, into a linear color.
Parameters
InColor The Pow(1/2.2) color that needs to be converted into linear space.
References Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [219/736]
UKismetMathLibrary::UFUNCTION () private
Converts temperature in Kelvins of a black body radiator to RGB chromaticity.
References Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [220/736]
UKismetMathLibrary::UFUNCTION () private
Sets to a random color.
Choses a quite nice color based on a random hue.
References Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [221/736]
UKismetMathLibrary::UFUNCTION () private
Converts a HSV linear color (where H is in R, S is in G, and V is in B) to linear RGB.
References Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [222/736]
UKismetMathLibrary::UFUNCTION () private
Breaks apart a color into individual HSV components (as well as alpha) (Hue is [0..360) while Saturation and Value are 0..1)
References A, Category, meta, S, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [223/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise addition of two linear colors (R+R, G+G, B+B, A+A)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [224/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise subtraction of two linear colors (R-R, G-G, B-B, A-A)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [225/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise multiplication of two linear colors (R*R, G*G, B*B, A*A)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [226/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise multiplication of a linear color by a float (F*R, F*G, F*B, F*A)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [227/736]
UKismetMathLibrary::UFUNCTION () private
Element-wise multiplication of two linear colors (R/R, G/G, B/B, A/A)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [228/736]
UKismetMathLibrary::UFUNCTION () private
Converts this color value to a hexadecimal string.
The format of the string is RRGGBBAA.
References Category, meta, and UFUNCTION().
UFUNCTION() [229/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [230/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [231/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [232/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [233/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than B (A > B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [234/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than or equal to B (A >= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [235/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than B (A < B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [236/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than or equal to B (A <= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [237/736]
UKismetMathLibrary::UFUNCTION () private
Returns the date component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [238/736]
UKismetMathLibrary::UFUNCTION () private
Returns the day component of A (1 to 31)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [239/736]
UKismetMathLibrary::UFUNCTION () private
Returns the day of year of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [240/736]
UKismetMathLibrary::UFUNCTION () private
Returns the hour component of A (24h format)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [241/736]
UKismetMathLibrary::UFUNCTION () private
Returns the hour component of A (12h format)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [242/736]
UKismetMathLibrary::UFUNCTION () private
Returns the millisecond component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [243/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minute component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [244/736]
UKismetMathLibrary::UFUNCTION () private
Returns the month component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [245/736]
UKismetMathLibrary::UFUNCTION () private
Returns the second component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [246/736]
UKismetMathLibrary::UFUNCTION () private
Returns the time elapsed since midnight of A.
References A, Category, meta, and UFUNCTION().
UFUNCTION() [247/736]
UKismetMathLibrary::UFUNCTION () private
Returns the year component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [248/736]
UKismetMathLibrary::UFUNCTION () private
Returns whether A's time is in the afternoon.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [249/736]
UKismetMathLibrary::UFUNCTION () private
Returns whether A's time is in the morning.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [250/736]
UKismetMathLibrary::UFUNCTION () private
Returns the number of days in the given year and month.
References Category, meta, Month, UE_INL_API, UFUNCTION(), and Year.
UFUNCTION() [251/736]
UKismetMathLibrary::UFUNCTION () private
Returns the number of days in the given year.
References Category, meta, UE_INL_API, UFUNCTION(), and Year.
UFUNCTION() [252/736]
UKismetMathLibrary::UFUNCTION () private
Returns whether given year is a leap year.
References Category, meta, UE_INL_API, UFUNCTION(), and Year.
UFUNCTION() [253/736]
UKismetMathLibrary::UFUNCTION () private
Returns the local date and time on this computer.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [254/736]
UKismetMathLibrary::UFUNCTION () private
Returns the local date on this computer.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [255/736]
UKismetMathLibrary::UFUNCTION () private
Returns the UTC date and time on this computer.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [256/736]
UKismetMathLibrary::UFUNCTION () private
Addition (A + B)
References A, B, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [257/736]
UKismetMathLibrary::UFUNCTION () private
Subtraction (A - B)
References A, B, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [258/736]
UKismetMathLibrary::UFUNCTION () private
Scalar multiplication (A * s)
References A, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [259/736]
UKismetMathLibrary::UFUNCTION () private
Scalar division (A / s)
References A, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [260/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than B (A > B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [261/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is greater than or equal to B (A >= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [262/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than B (A < B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [263/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is less than or equal to B (A <= B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [264/736]
UKismetMathLibrary::UFUNCTION () private
Returns the days component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [265/736]
UKismetMathLibrary::UFUNCTION () private
Returns the absolute value of A.
References A, Category, meta, and UFUNCTION().
UFUNCTION() [266/736]
UKismetMathLibrary::UFUNCTION () private
Returns the hours component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [267/736]
UKismetMathLibrary::UFUNCTION () private
Returns the milliseconds component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [268/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minutes component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [269/736]
UKismetMathLibrary::UFUNCTION () private
Returns the seconds component of A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [270/736]
UKismetMathLibrary::UFUNCTION () private
Returns the total number of days in A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [271/736]
UKismetMathLibrary::UFUNCTION () private
Returns the total number of hours in A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [272/736]
UKismetMathLibrary::UFUNCTION () private
Returns the total number of milliseconds in A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [273/736]
UKismetMathLibrary::UFUNCTION () private
Returns the total number of minutes in A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [274/736]
UKismetMathLibrary::UFUNCTION () private
Returns the total number of seconds in A.
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [275/736]
UKismetMathLibrary::UFUNCTION () private
Returns a time span that represents the specified number of days.
References Category, Days, meta, and UFUNCTION().
UFUNCTION() [276/736]
UKismetMathLibrary::UFUNCTION () private
Returns a time span that represents the specified number of hours.
References Category, Hours, meta, and UFUNCTION().
UFUNCTION() [277/736]
UKismetMathLibrary::UFUNCTION () private
Returns a time span that represents the specified number of milliseconds.
References Category, meta, Milliseconds, and UFUNCTION().
UFUNCTION() [278/736]
UKismetMathLibrary::UFUNCTION () private
Returns a time span that represents the specified number of minutes.
References Category, meta, Minutes, and UFUNCTION().
UFUNCTION() [279/736]
UKismetMathLibrary::UFUNCTION () private
Returns a time span that represents the specified number of seconds.
References Category, meta, Seconds, and UFUNCTION().
UFUNCTION() [280/736]
UKismetMathLibrary::UFUNCTION () private
Returns the ratio between two time spans (A / B), handles zero values.
References A, B, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [281/736]
UKismetMathLibrary::UFUNCTION () private
Convert a float into a vector, where each element is that float.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [282/736]
UKismetMathLibrary::UFUNCTION () private
Makes an FBoxSphereBounds given an origin, extent, and radius.
References BoxExtent, Category, FVector, Keywords, meta, Origin, and UFUNCTION().
UFUNCTION() [283/736]
UKismetMathLibrary::UFUNCTION () private
Breaks an FBoxSphereBounds into origin, extent, and radius.
References BoxExtent, Category, FVector, meta, Origin, UE_INL_API, and UFUNCTION().
UFUNCTION() [284/736]
UKismetMathLibrary::UFUNCTION () private
Makes a SRand-based random number generator.
References Category, InitialSeed, Keywords, meta, and UFUNCTION().
UFUNCTION() [285/736]
UKismetMathLibrary::UFUNCTION () private
Make a transform from location, rotation and scale.
References Category, FVector, Keywords, Location, meta, Rotation, Scale, and UFUNCTION().
UFUNCTION() [286/736]
UKismetMathLibrary::UFUNCTION () private
Compose two transforms in order: A * B.
Order matters when composing transforms: A * B will yield a transform that logically first applies A then B to any subsequent transformation.
Example: LocalToWorld = ComposeTransforms(DeltaRotation, LocalToWorld) will change rotation in local space by DeltaRotation. Example: LocalToWorld = ComposeTransforms(LocalToWorld, DeltaRotation) will change rotation in world space by DeltaRotation.
Returns
New transform: A * B
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [287/736]
UKismetMathLibrary::UFUNCTION () private
Transform a position by the supplied transform.
For example, if T was an object's transform, this would transform a position from local space to world space.
References Category, FVector, Keywords, Location, meta, ScriptMethod, T, UE_INL_API, and UFUNCTION().
UFUNCTION() [288/736]
UKismetMathLibrary::UFUNCTION () private
Transform a direction vector by the supplied transform - will not change its length.
For example, if T was an object's transform, this would transform a direction from local space to world space.
References Category, FVector, meta, ScriptMethod, T, UE_INL_API, and UFUNCTION().
UFUNCTION() [289/736]
UKismetMathLibrary::UFUNCTION () private
Transform a rotator by the supplied transform.
For example, if T was an object's transform, this would transform a rotation from local space to world space.
References Category, meta, Rotation, ScriptMethod, T, and UFUNCTION().
UFUNCTION() [290/736]
UKismetMathLibrary::UFUNCTION () private
Transform a position by the inverse of the supplied transform.
For example, if T was an object's transform, this would transform a position from world space to local space.
References Category, FVector, Keywords, Location, meta, ScriptMethod, T, UE_INL_API, and UFUNCTION().
UFUNCTION() [291/736]
UKismetMathLibrary::UFUNCTION () private
Transform a direction vector by the inverse of the supplied transform - will not change its length.
For example, if T was an object's transform, this would transform a direction from world space to local space.
References Category, FVector, meta, ScriptMethod, T, UE_INL_API, and UFUNCTION().
UFUNCTION() [292/736]
UKismetMathLibrary::UFUNCTION () private
Transform a rotator by the inverse of the supplied transform.
For example, if T was an object's transform, this would transform a rotation from world space to local space.
References Category, meta, Rotation, ScriptMethod, T, and UFUNCTION().
UFUNCTION() [293/736]
UKismetMathLibrary::UFUNCTION () private
Computes a relative transform of one transform compared to another.
Example: ChildOffset = MakeRelativeTransform(Child.GetActorTransform(), Parent.GetActorTransform()) This computes the relative transform of the Child from the Parent.
Parameters
A The object's transform
RelativeTo The transform the result is relative to (in the same space as A)
Returns
The new relative transform
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [294/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse of the given transform T.
Example: Given a LocalToWorld transform, WorldToLocal will be returned.
Parameters
T The transform you wish to invert
Returns
The inverse of T.
References Category, Keywords, meta, ScriptMethod, T, UE_INL_API, and UFUNCTION().
UFUNCTION() [295/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target transform based on distance from Current position, giving a nice smooth feeling when tracking a position.
Parameters
Current Actual transform
Target Target transform
DeltaTime Time since last tick
InterpSpeed Interpolation speed, if the speed given is 0, then jump to the target.
Returns
New interpolated transform
References Category, DeltaTime, InterpSpeed, meta, ScriptMethod, Target, and UFUNCTION().
UFUNCTION() [296/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if the values are equal (A == B)
UFUNCTION() [297/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if the values are not equal (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [298/736]
UKismetMathLibrary::UFUNCTION () private
Modulo (A % B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [299/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum value of A and B.
UFUNCTION() [300/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [301/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is equal to B (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [302/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is not equal to B (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [303/736]
UKismetMathLibrary::UFUNCTION () private
Modulo (A % B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [304/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is equal to B (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [305/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is not equal to B (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [306/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if value is between Min and Max (V >= Min && V <= Max) If InclusiveMin is true, value needs to be equal or larger than Min, else it needs to be larger If InclusiveMax is true, value needs to be smaller or equal than Max, else it needs to be smaller.
UFUNCTION() [307/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, meta, Min, UE_INL_API, and UFUNCTION().
UFUNCTION() [308/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, Max, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [309/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value between A and B (inclusive) that wraps around.
References Category, Max, meta, Min, UE_INL_API, UFUNCTION(), Value, and Wrap.
UFUNCTION() [310/736]
UKismetMathLibrary::UFUNCTION () private
Returns the absolute (positive) value of A.
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [311/736]
UKismetMathLibrary::UFUNCTION () private
Modulo (A % B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [312/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is equal to B (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [313/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is not equal to B (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [314/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if value is between Min and Max (V >= Min && V <= Max) If InclusiveMin is true, value needs to be equal or larger than Min, else it needs to be larger If InclusiveMax is true, value needs to be smaller or equal than Max, else it needs to be smaller.
References Category, Max, meta, Min, UFUNCTION(), and Value.
UFUNCTION() [315/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [316/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [317/736]
UKismetMathLibrary::UFUNCTION () private
Returns the absolute (positive) value of A.
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [318/736]
UKismetMathLibrary::UFUNCTION () private
Modulo (A % B)
References A, B, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [319/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is exactly equal to B (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [320/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A is nearly equal to B (|A - B| < ErrorTolerance)
References A, B, Category, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [321/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A does not equal B (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [322/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if value is between Min and Max (V >= Min && V <= Max) If InclusiveMin is true, value needs to be equal or larger than Min, else it needs to be larger If InclusiveMax is true, value needs to be smaller or equal than Max, else it needs to be smaller.
References Category, Max, meta, Min, UFUNCTION(), and Value.
UFUNCTION() [323/736]
UKismetMathLibrary::UFUNCTION () private
Returns the absolute (positive) value of A.
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [324/736]
UKismetMathLibrary::UFUNCTION () private
Returns the sine of A (expects Radians)
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [325/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse sine (arcsin) of A (result is in Radians)
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [326/736]
UKismetMathLibrary::UFUNCTION () private
Returns the cosine of A (expects Radians)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [327/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse cosine (arccos) of A (result is in Radians)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [328/736]
UKismetMathLibrary::UFUNCTION () private
Returns the tan of A (expects Radians)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [329/736]
UKismetMathLibrary::UFUNCTION () private
Returns the sin of A (expects Degrees)
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [330/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse sin (arcsin) of A (result is in Degrees)
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [331/736]
UKismetMathLibrary::UFUNCTION () private
Returns the cos of A (expects Degrees)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [332/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse cos (arccos) of A (result is in Degrees)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [333/736]
UKismetMathLibrary::UFUNCTION () private
Returns the tan of A (expects Degrees)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [334/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [335/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum value of A and B.
References A, B, Category, CommutativeAssociativeBinaryOperator, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [336/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value clamped between A and B (inclusive)
References Category, Max, meta, Min, UFUNCTION(), and Value.
UFUNCTION() [337/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value wrapped from A and B (inclusive)
References Category, Max, meta, Min, UE_INL_API, UFUNCTION(), and Value.
UFUNCTION() [338/736]
UKismetMathLibrary::UFUNCTION () private
Converts an IntPoint to a Vector2D.
UFUNCTION() [339/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if IntPoint A is equal to IntPoint B (A == B)
UFUNCTION() [340/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if IntPoint A is NOT equal to IntPoint B (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [341/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Vector2D to a Vector.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UFUNCTION(), and Z.
UFUNCTION() [342/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Vector2D to an IntPoint.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [343/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is equal to vector B (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [344/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector2D A is equal to vector2D B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [345/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector2D A is not equal to vector2D B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [346/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector2D A is not equal to vector2D B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [347/736]
UKismetMathLibrary::UFUNCTION () private
Returns the cross product of two 2d vectors - see http://mathworld.wolfram.com/CrossProduct.html.
References A, B, Category, CompactNodeTitle, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [348/736]
UKismetMathLibrary::UFUNCTION () private
Returns the dot product of two 2d vectors - see http://mathworld.wolfram.com/DotProduct.html.
References A, B, Category, CompactNodeTitle, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [349/736]
UKismetMathLibrary::UFUNCTION () private
Gets a normalized copy of the vector, checking it is safe to do so based on the length.
Returns zero vector if vector length is too small to safely normalize.
Parameters
Tolerance Minimum squared length of vector for normalization.
Returns
A normalized copy of the vector if safe, (0,0) otherwise.
References A, Category, Keywords, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [350/736]
UKismetMathLibrary::UFUNCTION () private
Normalize this vector in-place if it is large enough, set it to (0,0) otherwise.
Parameters
Tolerance Minimum squared length of vector for normalization.
See also
NormalSafe2D()
References A, Category, Keywords, meta, ScriptMethod, Tolerance, UFUNCTION(), and UPARAM().
UFUNCTION() [351/736]
UKismetMathLibrary::UFUNCTION () private
Get this vector as a vector where each component has been rounded to the nearest int.
Returns
New FVector2D from this vector that is rounded.
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [352/736]
UKismetMathLibrary::UFUNCTION () private
Converts a vector to LinearColor.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [353/736]
UKismetMathLibrary::UFUNCTION () private
Converts a vector to a transform.
Uses vector as location
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [354/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Vector to a Vector2D using the Vector's (X, Y) coordinates.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [355/736]
UKismetMathLibrary::UFUNCTION () private
Return the Quaternion orientation corresponding to the direction in which the vector points.
Similar to the FRotator version, returns a result without roll such that it preserves the up vector.
Note
If you don't care about preserving the up vector and just want the most direct rotation, you can use the faster 'FindBetweenVectors(ForwardVector, YourVector)' or 'FindBetweenNormals(...)' if you know the vector is of unit length.
Returns
Quaternion from the Vector's direction, without any roll.
References BlueprintAutocast, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [356/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is equal to vector B (A == B)
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [357/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is equal to vector B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [358/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is not equal to vector B (A != B)
References A, B, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [359/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is not equal to vector B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [360/736]
UKismetMathLibrary::UFUNCTION () private
Find the unit direction vector from one position to another or (0,0,0) if positions are the same.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [361/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A to an integer with truncation towards zero for each element in a vector.
(e.g. -1.7 truncated to -1, 2.8 truncated to 2)
References BlueprintAutocast, Category, FVector, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [362/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A to an integer with truncation towards zero for each element in a vector2D.
(e.g. -1.7 truncated to -1, 2.8 truncated to 2)
References BlueprintAutocast, Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [363/736]
UKismetMathLibrary::UFUNCTION () private
Distance between two points.
Parameters
V1 The first point.
V2 The second point.
Returns
The distance between two points.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [364/736]
UKismetMathLibrary::UFUNCTION () private
Squared distance between two points.
Parameters
V1 The first point.
V2 The second point.
Returns
The squared distance between two points.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [365/736]
UKismetMathLibrary::UFUNCTION () private
Euclidean distance between two points in the XY plane (ignoring Z).
Parameters
V1 The first point.
V2 The second point.
Returns
The distance between two points in the XY plane.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [366/736]
UKismetMathLibrary::UFUNCTION () private
Squared euclidean distance between two points in the XY plane (ignoring Z).
Parameters
V1 The first point.
V2 The second point.
Returns
The distance between two points in the XY plane.
References Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [367/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether all components of this vector are the same, within a tolerance.
Parameters
Tolerance Error tolerance.
Returns
true if the vectors are equal within tolerance limits, false otherwise.
References A, Category, FVector, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [368/736]
UKismetMathLibrary::UFUNCTION () private
Determines if vector is normalized / unit (length 1) within specified squared tolerance.
Returns
true if unit, false otherwise.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [369/736]
UKismetMathLibrary::UFUNCTION () private
Determines if vector is normalized / unit (length 1).
Returns
true if normalized, false otherwise.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [370/736]
UKismetMathLibrary::UFUNCTION () private
Gets a normalized unit copy of the 2D components of the vector, ensuring it is safe to do so.
Z is set to zero. Returns zero vector if vector length is too small to normalize.
Parameters
Tolerance Minimum squared vector length.
Returns
Normalized copy if safe, (0,0,0) otherwise.
References A, Category, FVector, Keywords, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [371/736]
UKismetMathLibrary::UFUNCTION () private
Calculates normalized unit version of vector without checking for zero length.
Returns
Normalized version of vector.
References A, Category, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [372/736]
UKismetMathLibrary::UFUNCTION () private
Normalize this vector in-place if it is large enough or set it to (0,0,0) otherwise.
Parameters
Tolerance Minimum squared length of vector for normalization.
References A, Category, FVector, Keywords, meta, ScriptMethod, Tolerance, UFUNCTION(), and UPARAM().
UFUNCTION() [373/736]
UKismetMathLibrary::UFUNCTION () private
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
References A, Alpha, B, Category, FVector, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [374/736]
UKismetMathLibrary::UFUNCTION () private
Easing between A and B using a specified easing function.
UFUNCTION() [375/736]
UKismetMathLibrary::UFUNCTION () private
Gets the reciprocal of this vector, avoiding division by zero.
Zero components are set to BIG_NUMBER.
Returns
Reciprocal of this vector.
References A, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [376/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random point within the specified bounding box.
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [377/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Vector4 to a Vector (dropping the W element)
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [378/736]
UKismetMathLibrary::UFUNCTION () private
Return the FRotator orientation corresponding to the direction in which the vector points.
Sets Yaw and Pitch to the proper numbers, and sets Roll to zero because the roll can't be determined from a vector.
Returns
FRotator from the Vector's direction, without any roll.
References BlueprintAutocast, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [379/736]
UKismetMathLibrary::UFUNCTION () private
Return the Quaternion orientation corresponding to the direction in which the vector points.
Similar to the FRotator version, returns a result without roll such that it preserves the up vector.
Note
If you don't care about preserving the up vector and just want the most direct rotation, you can use the faster 'FindBetweenVectors(ForwardVector, YourVector)' or 'FindBetweenNormals(...)' if you know the vector is of unit length.
Returns
Quaternion from the Vector's direction, without any roll.
References BlueprintAutocast, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [380/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is equal to vector B (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [381/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is equal to vector B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [382/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is not equal to vector B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [383/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if vector A is not equal to vector B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [384/736]
UKismetMathLibrary::UFUNCTION () private
Gets a negated copy of the vector.
Equivalent to -Vector for scripts.
References A, Category, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [385/736]
UKismetMathLibrary::UFUNCTION () private
Returns the cross product of two vectors - see http://mathworld.wolfram.com/CrossProduct.html.
References A, B, Category, CompactNodeTitle, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [386/736]
UKismetMathLibrary::UFUNCTION () private
Returns the dot product of two vectors - see http://mathworld.wolfram.com/DotProduct.html.
References A, B, Category, CompactNodeTitle, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [387/736]
UKismetMathLibrary::UFUNCTION () private
Returns the dot product of two vectors - see http://mathworld.wolfram.com/DotProduct.html The W element is ignored.
References A, B, Category, CompactNodeTitle, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [388/736]
UKismetMathLibrary::UFUNCTION () private
Returns the length of the vector.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [389/736]
UKismetMathLibrary::UFUNCTION () private
Returns the squared length of the vector.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [390/736]
UKismetMathLibrary::UFUNCTION () private
Returns the length of the vector.
The W element is ignored.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [391/736]
UKismetMathLibrary::UFUNCTION () private
Returns the squared length of the vector.
The W element is ignored.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [392/736]
UKismetMathLibrary::UFUNCTION () private
Determines if vector is normalized / unit (length 1) within specified squared tolerance.
The W element is ignored.
Returns
true if unit, false otherwise.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [393/736]
UKismetMathLibrary::UFUNCTION () private
Determines if vector is normalized / unit (length 1).
The W element is ignored.
Returns
true if normalized, false otherwise.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [394/736]
UKismetMathLibrary::UFUNCTION () private
Gets a normalized unit copy of the vector, ensuring it is safe to do so based on the length.
The W element is ignored and the returned vector has W=0. Returns zero vector if vector length is too small to safely normalize.
Parameters
Tolerance Minimum squared vector length.
Returns
A normalized copy if safe, (0,0,0) otherwise.
References A, Category, Keywords, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [395/736]
UKismetMathLibrary::UFUNCTION () private
Calculates normalized unit version of vector without checking for zero length.
The W element is ignored and the returned vector has W=0.
Returns
Normalized version of vector.
References A, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [396/736]
UKismetMathLibrary::UFUNCTION () private
Normalize this vector in-place if it is large enough or set it to (0,0,0,0) otherwise.
The W element is ignored and the returned vector has W=0.
Parameters
Tolerance Minimum squared length of vector for normalization.
References A, Category, Keywords, meta, ScriptMethod, Tolerance, UFUNCTION(), and UPARAM().
UFUNCTION() [397/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if rotator A is equal to rotator B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [398/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if rotator A is not equal to rotator B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [399/736]
UKismetMathLibrary::UFUNCTION () private
Returns rotator representing rotator A scaled by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [400/736]
UKismetMathLibrary::UFUNCTION () private
Returns rotator representing rotator A scaled by B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [401/736]
UKismetMathLibrary::UFUNCTION () private
Converts Rotator to Transform.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [402/736]
UKismetMathLibrary::UFUNCTION () private
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
References A, Alpha, B, Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [403/736]
UKismetMathLibrary::UFUNCTION () private
Easing between A and B using a specified easing function.
References A, Alpha, B, BlueprintInternalUseOnly, Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [404/736]
UKismetMathLibrary::UFUNCTION () private
Normalized A-B.
References A, B, Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [405/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Matrix to a Transform (Assumes Matrix represents a transform)
References Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [406/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Matrix to a Rotator (Assumes Matrix represents a transform)
References Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [407/736]
UKismetMathLibrary::UFUNCTION () private
Get the origin of the co-ordinate system (Assumes Matrix represents a transform)
Returns
co-ordinate system origin
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [408/736]
UKismetMathLibrary::UFUNCTION () private
UFUNCTION() [409/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether another Matrix is equal to this, within specified tolerance.
Parameters
Other The other Matrix.
Tolerance Error Tolerance.
Returns
true if two Matrix are equal, within specified tolerance, otherwise false.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [410/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether another Matrix is not equal to this, within specified tolerance.
Parameters
Other The other Matrix.
Returns
true if two Matrix are not equal, within specified tolerance, otherwise false.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [411/736]
UKismetMathLibrary::UFUNCTION () private
Transform a vector by the matrix.
(Assumes Matrix represents a transform)
References Category, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [412/736]
UKismetMathLibrary::UFUNCTION () private
Transform a location - will take into account translation part of the FMatrix.
(Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [413/736]
UKismetMathLibrary::UFUNCTION () private
Inverts the matrix and then transforms V - correctly handles scaling in this matrix.
(Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [414/736]
UKismetMathLibrary::UFUNCTION () private
Transform a direction vector - will not take into account translation part of the FMatrix.
If you want to transform a surface normal (or plane) and correctly account for non-uniform scaling you should use TransformByUsingAdjointT. (Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [415/736]
UKismetMathLibrary::UFUNCTION () private
Transform a direction vector by the inverse of this matrix - will not take into account translation part.
If you want to transform a surface normal (or plane) and correctly account for non-uniform scaling you should use TransformByUsingAdjointT with adjoint of matrix inverse. (Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [416/736]
UKismetMathLibrary::UFUNCTION () private
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [417/736]
UKismetMathLibrary::UFUNCTION () private
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [418/736]
UKismetMathLibrary::UFUNCTION () private
Returns
the determinant of rotation 3x3 matrix (Assumes Top Left 3x3 Submatrix represents a Rotation)
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [419/736]
UKismetMathLibrary::UFUNCTION () private
Get the inverse of the Matrix.
Handles nil matrices.
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [420/736]
UKismetMathLibrary::UFUNCTION () private
Get the Transose Adjoint of the Matrix.
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [421/736]
UKismetMathLibrary::UFUNCTION () private
Remove any scaling from this matrix (ie magnitude of each row is 1) with error Tolerance (Assumes Matrix represents a transform)
References Category, meta, ScriptMethod, Tolerance, UFUNCTION(), and UPARAM().
UFUNCTION() [422/736]
UKismetMathLibrary::UFUNCTION () private
Returns matrix after RemoveScaling with error Tolerance (Assumes Matrix represents a transform)
References Category, meta, ScriptMethod, Tolerance, and UFUNCTION().
UFUNCTION() [423/736]
UKismetMathLibrary::UFUNCTION () private
return a 3D scale vector calculated from this matrix (where each component is the magnitude of a row vector) with error Tolerance.
(Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [424/736]
UKismetMathLibrary::UFUNCTION () private
Remove any translation from this matrix (Assumes Matrix represents a transform)
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [425/736]
UKismetMathLibrary::UFUNCTION () private
Returns a matrix with an additional translation concatenated.
(Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, Translation, and UFUNCTION().
UFUNCTION() [426/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if any element of this matrix is NaN.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [427/736]
UKismetMathLibrary::UFUNCTION () private
Scale the translation part of the matrix by the supplied vector.
(Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [428/736]
UKismetMathLibrary::UFUNCTION () private
Returns
the maximum magnitude of any row of the matrix. (Assumes Matrix represents a transform)
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [429/736]
UKismetMathLibrary::UFUNCTION () private
Apply Scale to this matrix (Assumes Matrix represents a transform)
References Category, meta, Scale, ScriptMethod, and UFUNCTION().
UFUNCTION() [430/736]
UKismetMathLibrary::UFUNCTION () private
get axis of this matrix scaled by the scale of the matrix (Assumes Matrix represents a transform)
Parameters
i index into the axis of the matrix @ return vector of the axis
References Axis, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [431/736]
UKismetMathLibrary::UFUNCTION () private
get axes of this matrix scaled by the scale of the matrix (Assumes Matrix represents a transform)
Parameters
X axes returned to this param
Y axes returned to this param
Z axes returned to this param
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), X, Y, and Z.
UFUNCTION() [432/736]
UKismetMathLibrary::UFUNCTION () private
get unit length axis of this matrix (Assumes Matrix represents a transform)
Parameters
i index into the axis of the matrix
Returns
vector of the axis
References Axis, Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [433/736]
UKismetMathLibrary::UFUNCTION () private
get unit length axes of this matrix (Assumes Matrix represents a transform)
Parameters
X axes returned to this param
Y axes returned to this param
Z axes returned to this param
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), X, Y, and Z.
UFUNCTION() [434/736]
UKismetMathLibrary::UFUNCTION () private
set an axis of this matrix (Assumes Matrix represents a transform)
Parameters
i index into the axis of the matrix
Axis vector of the axis
References Axis, Category, FVector, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [435/736]
UKismetMathLibrary::UFUNCTION () private
Set the origin of the coordinate system to the given vector (Assumes Matrix represents a transform)
References Category, FVector, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [436/736]
UKismetMathLibrary::UFUNCTION () private
get a column of this matrix
Parameters
i index into the column of the matrix
Returns
vector of the column
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [437/736]
UKismetMathLibrary::UFUNCTION () private
References Category, FVector, meta, ScriptMethod, UFUNCTION(), UPARAM(), and Value.
UFUNCTION() [438/736]
UKismetMathLibrary::UFUNCTION () private
Get the rotator representation of this matrix (Assumes Matrix represents a transform)
Returns
rotator representation of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [439/736]
UKismetMathLibrary::UFUNCTION () private
Transform a rotation matrix into a quaternion.
(Assumes Matrix represents a transform)
Warning
rotation part will need to be unit length for this to be right!
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [440/736]
UKismetMathLibrary::UFUNCTION () private
Get the near plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
Parameters
OutPlane the near plane of the Frustum of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [441/736]
UKismetMathLibrary::UFUNCTION () private
Get the far plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
Parameters
OutPlane the far plane of the Frustum of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [442/736]
UKismetMathLibrary::UFUNCTION () private
Get the left plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
Parameters
OutPlane the left plane of the Frustum of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [443/736]
UKismetMathLibrary::UFUNCTION () private
Get the right plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
Parameters
OutPlane the right plane of the Frustum of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [444/736]
UKismetMathLibrary::UFUNCTION () private
Get the top plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
Parameters
OutPlane the top plane of the Frustum of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [445/736]
UKismetMathLibrary::UFUNCTION () private
Get the bottom plane of the Frustum of this matrix (Assumes Matrix represents a View Projection Matrix)
Parameters
OutPlane the bottom plane of the Frustum of this matrix
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [446/736]
UKismetMathLibrary::UFUNCTION () private
Utility for mirroring this transform across a certain plane, and flipping one of the axis as well.
(Assumes Matrix represents a transform)
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [447/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if Quaternion A is equal to Quaternion B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [448/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if Quat A is not equal to Quat B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, and UFUNCTION().
UFUNCTION() [449/736]
UKismetMathLibrary::UFUNCTION () private
Checks whether this Quaternion is an Identity Quaternion.
Assumes Quaternion tested is normalized.
Parameters
Tolerance Error tolerance for comparison with Identity Quaternion.
Returns
true if Quaternion is a normalized Identity Quaternion.
References Category, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [450/736]
UKismetMathLibrary::UFUNCTION () private
Return true if this quaternion is normalized.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [451/736]
UKismetMathLibrary::UFUNCTION () private
Determine if all the values are finite (not NaN nor Inf) in this Quat.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [452/736]
UKismetMathLibrary::UFUNCTION () private
Determine if there are any non-finite values (NaN or Inf) in this Quat.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [453/736]
UKismetMathLibrary::UFUNCTION () private
Find the angular distance/difference between two rotation quaternions.
Parameters
B Quaternion to find angle distance to
Returns
angular distance in radians
References A, B, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [454/736]
UKismetMathLibrary::UFUNCTION () private
Modify the quaternion to ensure that the delta between it and B represents the shortest possible rotation angle.
References A, B, Category, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [455/736]
UKismetMathLibrary::UFUNCTION () private
Convert a Quaternion into floating-point Euler angles (in degrees).
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [456/736]
UKismetMathLibrary::UFUNCTION () private
Used in combination with Log().
Assumes a quaternion with W=0 and V=theta*v (where |v| = 1). Exp(q) = (sin(theta)*v, cos(theta))
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [457/736]
UKismetMathLibrary::UFUNCTION () private
Get the angle of this quaternion.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [458/736]
UKismetMathLibrary::UFUNCTION () private
Get the forward direction (X axis) after it has been rotated by this Quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [459/736]
UKismetMathLibrary::UFUNCTION () private
Get the right direction (Y axis) after it has been rotated by this Quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [460/736]
UKismetMathLibrary::UFUNCTION () private
Get the up direction (Z axis) after it has been rotated by this Quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [461/736]
UKismetMathLibrary::UFUNCTION () private
Get the forward direction (X axis) after it has been rotated by this Quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [462/736]
UKismetMathLibrary::UFUNCTION () private
Get the right direction (Y axis) after it has been rotated by this Quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [463/736]
UKismetMathLibrary::UFUNCTION () private
Get the up direction (Z axis) after it has been rotated by this Quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [464/736]
UKismetMathLibrary::UFUNCTION () private
Normalize this quaternion if it is large enough as compared to the supplied tolerance.
If it is too small then set it to the identity quaternion.
Parameters
Tolerance Minimum squared length of quaternion for normalization.
References Category, meta, ScriptMethod, Tolerance, UFUNCTION(), and UPARAM().
UFUNCTION() [465/736]
UKismetMathLibrary::UFUNCTION () private
Get a normalized copy of this quaternion.
If it is too small, returns an identity quaternion.
Parameters
Tolerance Minimum squared length of quaternion for normalization.
References Category, meta, ScriptMethod, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [466/736]
UKismetMathLibrary::UFUNCTION () private
Get the axis of rotation of the Quaternion.
This is the axis around which rotation occurs to transform the canonical coordinate system to the target orientation. For the identity Quaternion which has no such rotation, FVector(1,0,0) is returned.
References Category, FVector, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [467/736]
UKismetMathLibrary::UFUNCTION () private
Return an inversed copy of this quaternion.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [468/736]
UKismetMathLibrary::UFUNCTION () private
Quaternion with W=0 and V=theta*v.
Used in combination with Exp().
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [469/736]
UKismetMathLibrary::UFUNCTION () private
Set X, Y, Z, W components of Quaternion.
References Category, meta, ScriptMethod, UFUNCTION(), UPARAM(), W, X, Y, and Z.
UFUNCTION() [470/736]
UKismetMathLibrary::UFUNCTION () private
Convert a vector of floating-point Euler angles (in degrees) into a Quaternion.
Parameters
Q Quaternion to update
Euler the Euler angles
References Category, FVector, meta, ScriptMethod, UFUNCTION(), and UPARAM().
UFUNCTION() [471/736]
UKismetMathLibrary::UFUNCTION () private
Converts to Rotator representation of this Quaternion.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [472/736]
UKismetMathLibrary::UFUNCTION () private
Converts to Quaternion representation of this Rotator.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [473/736]
UKismetMathLibrary::UFUNCTION () private
Get the length of the quaternion.
Returns
The length of the quaternion.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [474/736]
UKismetMathLibrary::UFUNCTION () private
Get the squared length of the quaternion.
Returns
The squared length of the quaternion.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [475/736]
UKismetMathLibrary::UFUNCTION () private
Rotate a vector by this quaternion.
Parameters
V the vector to be rotated
Returns
vector after rotation
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [476/736]
UKismetMathLibrary::UFUNCTION () private
Rotate a vector by the inverse of this quaternion.
Parameters
V the vector to be rotated
Returns
vector after rotation by the inverse of this quaternion.
References Category, FVector, meta, ScriptMethod, UE_INL_API, UFUNCTION(), and V.
UFUNCTION() [477/736]
UKismetMathLibrary::UFUNCTION () private
Spherical interpolation between Quaternions.
Result is normalized.
Parameters
A The starting quat we interp from
B The target quat we interp to
Alpha The interpolation amount, usually 0 to 1.
Returns
Quat after spherical interpolation
References A, Alpha, B, Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [478/736]
UKismetMathLibrary::UFUNCTION () private
Converts a float into a LinearColor, where each RGB element is that float.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [479/736]
UKismetMathLibrary::UFUNCTION () private
Converts a HSV linear color (where H is in R (0..360), S is in G (0..1), and V is in B (0..1)) to RGB.
References Category, Keywords, meta, RGB, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [480/736]
UKismetMathLibrary::UFUNCTION () private
Converts a RGB linear color to HSV (where H is in R (0..360), S is in G (0..1), and V is in B (0..1))
References Category, Keywords, meta, RGB, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [481/736]
UKismetMathLibrary::UFUNCTION () private
Converts a RGB linear color to HSV (where H is in R, S is in G, and V is in B)
References Category, Keywords, meta, RGB, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [482/736]
UKismetMathLibrary::UFUNCTION () private
Converts a LinearColor to a vector.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [483/736]
UKismetMathLibrary::UFUNCTION () private
Converts from linear to 8-bit RGBE as outlined in Gregory Ward's Real Pixels article, Graphics Gems II, page 80.
References BlueprintAutocast, Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [484/736]
UKismetMathLibrary::UFUNCTION () private
Quantizes the linear color and returns the result as a FColor with optional sRGB conversion and quality as goal.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [485/736]
UKismetMathLibrary::UFUNCTION () private
Quantizes the linear color and returns the result as an 8-bit color.
This bypasses the SRGB conversion.
References Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [486/736]
UKismetMathLibrary::UFUNCTION () private
Quantizes the linear color with rounding and returns the result as an 8-bit color.
This bypasses the SRGB conversion.
References Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [487/736]
UKismetMathLibrary::UFUNCTION () private
Returns a desaturated color, with 0 meaning no desaturation and 1 == full desaturation.
Parameters
Desaturation Desaturation factor in range [0..1]
Returns
Desaturated color
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [488/736]
UKismetMathLibrary::UFUNCTION () private
Euclidean distance between two color points.
References Category, Keywords, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [489/736]
UKismetMathLibrary::UFUNCTION () private
Returns a copy of this color using the specified opacity/alpha.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [490/736]
UKismetMathLibrary::UFUNCTION () private
Returns the perceived brightness of a color on a display taking into account the impact on the human eye per color channel: green > red > blue.
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [491/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum color channel value in this color structure.
Returns
The maximum color channel value
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [492/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum color channel value in this color structure.
Returns
The minimum color channel value
References Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [493/736]
UKismetMathLibrary::UFUNCTION () private
Interpolate Linear Color from Current to Target.
Scaled by distance to Target, so it has a strong start speed and ease out.
Parameters
Current Current Color
Target Target Color
DeltaTime Time since last tick
InterpSpeed Interpolation speed, if the speed given is 0, then jump to the target.
Returns
New interpolated Color
References Category, DeltaTime, InterpSpeed, Keywords, meta, ScriptMethod, Target, UE_INL_API, and UFUNCTION().
UFUNCTION() [494/736]
UKismetMathLibrary::UFUNCTION () private
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
References A, Alpha, B, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [495/736]
UKismetMathLibrary::UFUNCTION () private
Linearly interpolates between two colors by the specified Alpha amount (100% of A when Alpha=0 and 100% of B when Alpha=1).
The interpolation is performed in HSV color space taking the shortest path to the new color's hue. This can give better results than a normal lerp, but is much more expensive. The incoming colors are in RGB space, and the output color will be RGB. The alpha value will also be interpolated.
Parameters
A The color and alpha to interpolate from as linear RGBA
B The color and alpha to interpolate to as linear RGBA
Alpha Scalar interpolation amount (usually between 0.0 and 1.0 inclusive)
Returns
The interpolated color in linear RGB space along with the interpolated alpha value
References A, Alpha, B, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [496/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if linear color A is equal to linear color B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, Tolerance, UE_INL_API, and UFUNCTION().
UFUNCTION() [497/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if linear color A is equal to linear color B (A == B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [498/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if linear color A is not equal to linear color B (A != B) within a specified error tolerance.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [499/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if the values are equal (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [500/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if the values are not equal (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [501/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum time span value.
References Category, meta, ScriptConstant, ScriptConstantHost, and UFUNCTION().
UFUNCTION() [502/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum time span value.
References Category, meta, ScriptConstant, ScriptConstantHost, and UFUNCTION().
UFUNCTION() [503/736]
UKismetMathLibrary::UFUNCTION () private
Returns a zero time span value.
References Category, meta, ScriptConstant, ScriptConstantHost, and UFUNCTION().
UFUNCTION() [504/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if the values are equal (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [505/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if the values are not equal (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [506/736]
UKismetMathLibrary::UFUNCTION () private
Converts a byte to a float.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [507/736]
UKismetMathLibrary::UFUNCTION () private
Converts an integer to a float.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [508/736]
UKismetMathLibrary::UFUNCTION () private
Converts an integer to a 64 bit integer.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [509/736]
UKismetMathLibrary::UFUNCTION () private
Converts an integer to a byte (if the integer is too large, returns the low 8 bits)
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [510/736]
UKismetMathLibrary::UFUNCTION () private
Converts a 64 bit integer to a 32 bit integer (if the integer is too large, returns the low 32 bits)
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [511/736]
UKismetMathLibrary::UFUNCTION () private
Converts a 64 bit integer to a byte (if the integer is too large, returns the low 8 bits)
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [512/736]
UKismetMathLibrary::UFUNCTION () private
Converts a float to a 64 bit integer.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [513/736]
UKismetMathLibrary::UFUNCTION () private
Converts a 64 bit integer to a float.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [514/736]
UKismetMathLibrary::UFUNCTION () private
Converts an integer to an IntVector.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [515/736]
UKismetMathLibrary::UFUNCTION () private
Converts an integer to an IntVector2.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
UFUNCTION() [516/736]
UKismetMathLibrary::UFUNCTION () private
Converts an integer to a FVector.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [517/736]
UKismetMathLibrary::UFUNCTION () private
Converts a int to a bool.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [518/736]
UKismetMathLibrary::UFUNCTION () private
Converts a bool to an int.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [519/736]
UKismetMathLibrary::UFUNCTION () private
Converts a bool to a float (0.0 or 1.0)
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [520/736]
UKismetMathLibrary::UFUNCTION () private
Converts a bool to a byte.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [521/736]
UKismetMathLibrary::UFUNCTION () private
Converts a byte to an integer.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [522/736]
UKismetMathLibrary::UFUNCTION () private
Converts a byte to an integer.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [523/736]
UKismetMathLibrary::UFUNCTION () private
Converts a color to LinearColor.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [524/736]
UKismetMathLibrary::UFUNCTION () private
Converts an IntVector to a vector.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [525/736]
UKismetMathLibrary::UFUNCTION () private
Converts an IntVector2 to a vector2D.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [526/736]
UKismetMathLibrary::UFUNCTION () private
Converts a double into a vector, where each element is that float.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [527/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A and B are equal (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [528/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A and B are not equal (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [529/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A and B are equal (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [530/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A and B are not equal (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [531/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A and B are equal (A == B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [532/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if A and B are not equal (A != B)
References A, B, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [533/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if transform A is equal to transform B.
References A, B, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, ScriptOperator, UE_INL_API, and UFUNCTION().
UFUNCTION() [534/736]
UKismetMathLibrary::UFUNCTION () private
Returns true if transform A is nearly equal to B.
Parameters
LocationTolerance How close position of transforms need to be to be considered equal
RotationTolerance How close rotations of transforms need to be to be considered equal
Scale3DTolerance How close scale of transforms need to be to be considered equal
References A, B, Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [535/736]
UKismetMathLibrary::UFUNCTION () private
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1).
UFUNCTION() [536/736]
UKismetMathLibrary::UFUNCTION () private
Ease between A and B using a specified easing function.
References A, Alpha, B, BlueprintInternalUseOnly, Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [537/736]
UKismetMathLibrary::UFUNCTION () private
Converts a Transform to a Matrix with scale.
References BlueprintAutocast, Category, CompactNodeTitle, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [538/736]
UKismetMathLibrary::UFUNCTION () private
Sign (integer, returns -1 if A < 0, 0 if A is zero, and +1 if A > 0)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [539/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value clamped to be between A and B (inclusive)
References Category, Max, meta, Min, UFUNCTION(), and Value.
UFUNCTION() [540/736]
UKismetMathLibrary::UFUNCTION () private
Sign (integer64, returns -1 if A < 0, 0 if A is zero, and +1 if A > 0)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [541/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value clamped to be between A and B (inclusive)
References Category, Max, meta, Min, UFUNCTION(), and Value.
UFUNCTION() [542/736]
UKismetMathLibrary::UFUNCTION () private
Snaps a value to the nearest grid multiple.
E.g., Location = 5.1, GridSize = 10.0 : return value = 10.0 If GridSize is 0 Location is returned if GridSize is very small precision issues may occur.
References Category, Location, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [543/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse tan (atan) (result is in Radians)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [544/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse tan (atan2) of A/B (result is in Radians)
References Category, meta, UE_INL_API, UFUNCTION(), X, and Y.
UFUNCTION() [545/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse tan (atan) (result is in Degrees)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [546/736]
UKismetMathLibrary::UFUNCTION () private
Returns the inverse tan (atan2) of A/B (result is in Degrees)
References Category, meta, UE_INL_API, UFUNCTION(), X, and Y.
UFUNCTION() [547/736]
UKismetMathLibrary::UFUNCTION () private
Returns the number of times Divisor will go into Dividend (i.e., Dividend divided by Divisor), as well as the remainder.
References Category, meta, and UFUNCTION().
UFUNCTION() [548/736]
UKismetMathLibrary::UFUNCTION () private
Sign (float, returns -1 if A < 0, 0 if A is zero, and +1 if A > 0)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [549/736]
UKismetMathLibrary::UFUNCTION () private
Convert a vector of floating-point Euler angles (in degrees) into a Quaternion.
Parameters
Euler the Euler angles
Returns
constructed Quat
References Category, FVector, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [550/736]
UKismetMathLibrary::UFUNCTION () private
Returns the maximum date and time value.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [551/736]
UKismetMathLibrary::UFUNCTION () private
Returns the minimum date and time value.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [552/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random point within the specified bounding box.
UFUNCTION() [553/736]
UKismetMathLibrary::UFUNCTION () const & private
Checks whether the given bounding box A intersects this bounding box B.
Parameters
A The bounding box to check intersection against
B The bounding box to intersect with.
Returns
true if the boxes intersect, false otherwise.
Note
This function assumes boxes have closed bounds, i.e. boxes with coincident borders on any edge will overlap.
References Category, meta, and UFUNCTION().
UFUNCTION() [554/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns true if the InnerTest Box is is completely inside of the OuterTest Box.
Parameters
InnerTest The box to check if it is on the inside
OuterTest The box to check if InnerTest is within.
Returns
True if InnerTest Box is is completely inside of OuterTest Box
References Category, meta, and UFUNCTION().
UFUNCTION() [555/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns true if the InnerTest Box is is completely inside or on OuterTest Box.
Parameters
InnerTest The box to check if it is on the inside
OuterTest The box to check if InnerTest is within or on.
Returns
True if InnerTest Box is is completely inside of or on OuterTest Box
References Category, meta, OuterTest, and UFUNCTION().
UFUNCTION() [556/736]
UKismetMathLibrary::UFUNCTION () const & private
Checks whether the given location is inside this box.
Parameters
Box The box to test
Point The location to test for inside the bounding volume.
Returns
true if location is inside this volume.
Note
This function assumes boxes have open bounds, i.e. points lying on the border of the box are not inside. Use IsPointInBox_Box to include borders in the test.
References Category, meta, and UFUNCTION().
UFUNCTION() [557/736]
UKismetMathLibrary::UFUNCTION () private
Determines whether the given point is in a box.
Includes points on the box.
Parameters
Point Point to test
Box Box to test against
Returns
Whether the point is in the box.
References Category, meta, and UFUNCTION().
UFUNCTION() [558/736]
UKismetMathLibrary::UFUNCTION () private
Determines whether a given point is in a box with a given transform.
Includes points on the box.
Parameters
Point Point to test
BoxWorldTransform Component-to-World transform of the box.
Box Box to test agains in component space.
Returns
Whether the point is in the box.
References Category, meta, and UFUNCTION().
UFUNCTION() [559/736]
UKismetMathLibrary::UFUNCTION () const & private
Computes the intersection point between a line and a plane.
Parameters
T - The t of the intersection between the line and the plane
Intersection - The point of intersection between the line and the plane
Returns
True if the intersection test was successful.
References Category, meta, and UFUNCTION().
UFUNCTION() [560/736]
UKismetMathLibrary::UFUNCTION () const & private
Gets the volume of this box.
Returns
The box volume.
References Category, meta, and UFUNCTION().
UFUNCTION() [561/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a box of increased size.
Parameters
Negative The size to increase the volume by in the negative direction (positive values move the bounds outwards)
Positive The size to increase the volume by in the positive direction (positive values move the bounds outwards)
Returns
A new bounding box.
References Category, meta, and UFUNCTION().
UFUNCTION() [562/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns the overlap TBox<T> of two boxes.
Parameters
A The bounding box to test
B The bounding box to test overlap against
Returns
the overlap box. It can be 0 if they don't overlap
References A, B, Category, meta, and UFUNCTION().
UFUNCTION() [563/736]
UKismetMathLibrary::UFUNCTION () const & private
Calculates the closest point on or inside the box to a given point in space.
Parameters
Box The box to check if the point is inside of
Point The point in space
Returns
The closest point on or inside the box.
References Box, Category, FVector, meta, Point, and UFUNCTION().
UFUNCTION() [564/736]
UKismetMathLibrary::UFUNCTION () const & private
Gets the center point of this box.
Returns
The center point.
References Category, FVector, meta, and UFUNCTION().
UFUNCTION() [565/736]
UKismetMathLibrary::UFUNCTION () const & private
Gets the size of this box.
Returns
The box size.
References Category, FVector, meta, and UFUNCTION().
UFUNCTION() [566/736]
UKismetMathLibrary::UFUNCTION () private
Get a copy of the vector as sign only.
Each component is set to +1 or -1, with the sign of zero treated as +1.
Returns
A copy of the vector with each component set to +1 or -1
References A, Category, meta, ScriptMethod, UE_INL_API, and UFUNCTION().
UFUNCTION() [567/736]
UKismetMathLibrary::UFUNCTION () private
Determine if a class is a child of another class.
Returns
true if TestClass == ParentClass, or if TestClass is a child of ParentClass; false otherwise, or if either the value for either parameter is 'None'.
References Category, and UFUNCTION().
UFUNCTION() [568/736]
UKismetMathLibrary::UFUNCTION () private
Determines whether the given point is in a box.
Includes points on the box.
Parameters
Point Point to test
BoxOrigin Origin of the box
BoxExtent Extents of the box (distance in each axis from origin)
Returns
Whether the point is in the box.
References Category, and UFUNCTION().
UFUNCTION() [569/736]
UKismetMathLibrary::UFUNCTION () private
Determines whether a given point is in a box with a given transform.
Includes points on the box.
Parameters
Point Point to test
BoxWorldTransform Component-to-World transform of the box.
BoxExtent Extents of the box (distance in each axis from origin), in component space.
Returns
Whether the point is in the box.
References Category, and UFUNCTION().
UFUNCTION() [570/736]
UKismetMathLibrary::UFUNCTION () const & private
Computes the intersection point between a line and a plane.
Parameters
T - The t of the intersection between the line and the plane
Intersection - The point of intersection between the line and the plane
Returns
True if the intersection test was successful.
References Category, and UFUNCTION().
UFUNCTION() [571/736]
UKismetMathLibrary::UFUNCTION () private
Interpolate between A and B, applying an ease in/out function.
Exp controls the degree of the curve.
References Category, and UFUNCTION().
UFUNCTION() [572/736]
UKismetMathLibrary::UFUNCTION () private
Linearly interpolates between A and B based on Alpha (100% of A when Alpha=0 and 100% of B when Alpha=1)
References Category, and UFUNCTION().
UFUNCTION() [573/736]
UKismetMathLibrary::UFUNCTION () private
Returns log of A base B (if B^R == A, returns R)
References Category, and UFUNCTION().
UFUNCTION() [574/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value normalized to the given range.
(e.g. 20 normalized to the range 10->50 would result in 0.25)
References Category, and UFUNCTION().
UFUNCTION() [575/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [576/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [577/736]
UKismetMathLibrary::UFUNCTION () private
Clamps an angle to the range of [0, 360].
Parameters
Angle The angle to clamp.
Returns
The clamped angle.
References Angle, Category, and UFUNCTION().
UFUNCTION() [578/736]
UKismetMathLibrary::UFUNCTION () const & private
Evaluate this runtime float curve at the specified time.
Parameters
Curve The runtime float curve to evaluate
InTime The time at which to evaluate the curve
InDefaultValue The default value which should be used if the curve cannot be evaluated at the given time.
Returns
The curve's value at the given time.
See also
FRichCurve::Eval
References Category, and UFUNCTION().
UFUNCTION() [579/736]
UKismetMathLibrary::UFUNCTION () private
Simple function to create a pulsating scalar value.
Parameters
InCurrentTime Current absolute time
InPulsesPerSecond How many full pulses per second?
InPhase Optional phase amount, between 0.0 and 1.0 (to synchronize pulses)
Returns
Pulsating value (0.0-1.0)
References Category, and UFUNCTION().
UFUNCTION() [580/736]
UKismetMathLibrary::UFUNCTION () private
Clamps an angle to the range of [-180, 180].
Parameters
Angle The Angle to clamp.
Returns
The clamped angle.
References Angle, Category, and UFUNCTION().
UFUNCTION() [581/736]
UKismetMathLibrary::UFUNCTION () const private
Generates a 1D Perlin noise from the given value.
Returns a continuous random value between -1.0 and 1.0.
Parameters
Value The input value that Perlin noise will be generated from. This is usually a steadily incrementing time value.
Returns
Perlin noise in the range of -1.0 to 1.0
References Category, and Value.
UFUNCTION() [582/736]
UKismetMathLibrary::UFUNCTION () const private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [583/736]
UKismetMathLibrary::UFUNCTION () const & private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [584/736]
UKismetMathLibrary::UFUNCTION () const private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [585/736]
UKismetMathLibrary::UFUNCTION () const & private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [586/736]
UKismetMathLibrary::UFUNCTION () private
Find the closest point on an infinite line to a given point.
Parameters
Point Point for which we find the closest point on the line.
LineOrigin Point of reference on the line.
LineDirection Direction of the line. Not required to be normalized.
Returns
The closest point on the line to the given point.
References Category, and UFUNCTION().
UFUNCTION() [587/736]
UKismetMathLibrary::UFUNCTION () const & private
Find the average of an array of vectors.
References Category, FVector, and UFUNCTION().
UFUNCTION() [588/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [589/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [590/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns average of all array entries.
Returns value of 0 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [591/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns Slope Pitch and Roll angles in degrees based on the following information:
Parameters
MyRightYAxis Right (Y) direction unit vector of Actor standing on Slope.
FloorNormal Floor Normal (unit) vector.
UpVector UpVector of reference frame. @outparam OutSlopePitchDegreeAngle Slope Pitch angle (degrees) @outparam OutSlopeRollDegreeAngle Slope Roll angle (degrees)
References Category, and UFUNCTION().
UFUNCTION() [592/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns max of all array entries and the index at which it was found.
Returns value of 0 and index of -1 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [593/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns max of all array entries and the index at which it was found.
Returns value of 0 and index of -1 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [594/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns max of all array entries and the index at which it was found.
Returns value of 0 and index of -1 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [595/736]
UKismetMathLibrary::UFUNCTION () private
Returns median of all array entries.
Returns value of 0 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [596/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns min of all array entries and the index at which it was found.
Returns value of 0 and index of -1 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [597/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns min of all array entries and the index at which it was found.
Returns value of 0 and index of -1 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [598/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns min of all array entries and the index at which it was found.
Returns value of 0 and index of -1 if the supplied array is empty.
References Category, and UFUNCTION().
UFUNCTION() [599/736]
UKismetMathLibrary::UFUNCTION () & private
Resets the state of a float spring.
References Category, UFUNCTION(), and UPARAM().
UFUNCTION() [600/736]
UKismetMathLibrary::UFUNCTION () & private
Resets the state of a quaternion spring.
References Category, UFUNCTION(), and UPARAM().
UFUNCTION() [601/736]
UKismetMathLibrary::UFUNCTION () & private
Resets the state of a vector spring.
References Category, UFUNCTION(), and UPARAM().
UFUNCTION() [602/736]
UKismetMathLibrary::UFUNCTION () & private
Sets the state velocity of a float spring.
References Category, and UFUNCTION().
UFUNCTION() [603/736]
UKismetMathLibrary::UFUNCTION () & private
Sets the state angular velocity of a quaternion spring.
References Category, and UFUNCTION().
UFUNCTION() [604/736]
UKismetMathLibrary::UFUNCTION () & private
Sets the state velocity of a vector spring.
References Category, and UFUNCTION().
UFUNCTION() [605/736]
UKismetMathLibrary::UFUNCTION () private
Converts a date string in ISO-8601 format to a DateTime object.
References Category, and UFUNCTION().
UFUNCTION() [606/736]
UKismetMathLibrary::UFUNCTION () private
Converts a date string to a DateTime object.
References Category, Result, UE_INL_API, and UFUNCTION().
UFUNCTION() [607/736]
UKismetMathLibrary::UFUNCTION () const & private
Determines whether a given set of points are coplanar, with a tolerance.
Any three points or less are always coplanar.
Parameters
Points - The set of points to determine coplanarity for.
Tolerance - Larger numbers means more variance is allowed.
Returns
Whether the points are relatively coplanar, based on the tolerance
References Category, and UFUNCTION().
UFUNCTION() [608/736]
UKismetMathLibrary::UFUNCTION () private
Converts a time span string to a Timespan object.
References Category, and UFUNCTION().
UFUNCTION() [609/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target based on distance from Current position, giving a nice smooth feeling when tracking a position.
Parameters
Current Actual position
Target Target position
DeltaTime Time since last tick
InterpSpeed Interpolation speed, if the speed given is 0, then jump to the target.
Returns
New interpolated position
References Category, and UFUNCTION().
UFUNCTION() [610/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target at a constant rate.
Parameters
Current Actual position
Target Target position
DeltaTime Time since last tick
InterpSpeed Interpolation speed
Returns
New interpolated position
References Category, DeltaTime, InterpSpeed, Target, UE_INL_API, and UFUNCTION().
UFUNCTION() [611/736]
UKismetMathLibrary::UFUNCTION () private
Returns the fractional part of a float.
References A, Category, and UE_INL_API.
UFUNCTION() [612/736]
UKismetMathLibrary::UFUNCTION () private
Returns natural log of A (if e^R == A, returns R)
References A, Category, UE_INL_API, and UFUNCTION().
UFUNCTION() [613/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns this date as the number of seconds since the Unix Epoch (January 1st of 1970).
Returns
Time of day.
See also
FromUnixTimestamp
References Category, Time, UE_INL_API, and UFUNCTION().
UFUNCTION() [614/736]
UKismetMathLibrary::UFUNCTION () const private
Returns the date from Unix time (seconds from midnight 1970-01-01)
Parameters
UnixTime Unix time (seconds from midnight 1970-01-01)
Returns
Gregorian date and time.
See also
ToUnixTimestamp
References Category, UE_INL_API, and UFUNCTION().
UFUNCTION() [615/736]
UKismetMathLibrary::UFUNCTION () private
Returns a new rotation component value.
Parameters
InCurrent is the current rotation value
InDesired is the desired rotation value
InDeltaRate is the rotation amount to apply
Returns
a new rotation component value clamped in the range (-360,360)
References Category, and UFUNCTION().
UFUNCTION() [616/736]
UKismetMathLibrary::UFUNCTION () private
Find the distance from a point to the closest point on an infinite line.
Parameters
Point Point for which we find the distance to the closest point on the line.
LineOrigin Point of reference on the line.
LineDirection Direction of the line. Not required to be normalized.
Returns
The distance from the given point to the closest point on the line.
References Category, FVector, LineDirection, LineOrigin, Point, UE_INL_API, and UFUNCTION().
UFUNCTION() [617/736]
UKismetMathLibrary::UFUNCTION () private
Find the distance from a point to the closest point on a segment.
Parameters
Point Point for which we find the distance to the closest point on the segment.
SegmentStart Start of the segment.
SegmentEnd End of the segment.
Returns
The distance from the given point to the closest point on the segment.
References Category, FVector, Point, SegmentEnd, SegmentStart, UE_INL_API, and UFUNCTION().
UFUNCTION() [618/736]
UKismetMathLibrary::UFUNCTION () private
Find the closest point on a segment to a given point.
Parameters
Point Point for which we find the closest point on the segment.
SegmentStart Start of the segment.
SegmentEnd End of the segment.
Returns
The closest point on the segment to the given point.
References Category, and UFUNCTION().
UFUNCTION() [619/736]
UKismetMathLibrary::UFUNCTION () private
Given a direction vector and a surface normal, returns the vector reflected across the surface normal.
Produces a result like shining a laser at a mirror!
Parameters
InVect Direction vector the ray is coming from.
InNormal A normal of the surface the ray should be reflected on.
Returns
Reflected vector.
References Category, and UFUNCTION().
UFUNCTION() [620/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A to the nearest integer (e.g., -1.6 becomes -2 and 1.6 becomes 2)
References A, Category, UE_INL_API, and UFUNCTION().
UFUNCTION() [621/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns this date as the number of seconds since the Unix Epoch (January 1st of 1970).
Returns
Time of day.
See also
FromUnixTimestamp
References Category, Time, UE_INL_API, and UFUNCTION().
UFUNCTION() [622/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [623/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, and UFUNCTION().
UFUNCTION() [624/736]
UKismetMathLibrary::UFUNCTION () private
Breaks apart a color into individual RGB components (as well as alpha)
References Category, and UFUNCTION().
UFUNCTION() [625/736]
UKismetMathLibrary::UFUNCTION () private
Find closest points between 2 segments.
Parameters
Segment1Start Start of the 1st segment.
Segment1End End of the 1st segment.
Segment2Start Start of the 2nd segment.
Segment2End End of the 2nd segment.
Segment1Point Closest point on segment 1 to segment 2.
Segment2Point Closest point on segment 2 to segment 1.
References Category, and UFUNCTION().
UFUNCTION() [626/736]
UKismetMathLibrary::UFUNCTION () private
Returns the number of times Divisor will go into Dividend (i.e., Dividend divided by Divisor), as well as the remainder.
References Category, meta, and UFUNCTION().
UFUNCTION() [627/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random bool.
References Category, meta, ScriptMethod, and Stream.
UFUNCTION() [628/736]
UKismetMathLibrary::UFUNCTION () private
Get a random chance with the specified weight.
Range of weight is 0.0 - 1.0 E.g., Weight = .6 return value = True 60% of the time
References Category, meta, UFUNCTION(), and Weight.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [629/736]
UKismetMathLibrary::UFUNCTION () const & private
Get a random chance with the specified weight.
Range of weight is 0.0 - 1.0 E.g., Weight = .6 return value = True 60% of the time
References Category, meta, ScriptMethod, UFUNCTION(), and Weight.
UFUNCTION() [630/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value mapped from one range into another where the Value is clamped to the Input Range.
(e.g. 0.5 normalized from the range 0->1 to 0->50 would result in 25)
References Category, InRangeA, InRangeB, Keywords, meta, OutRangeA, OutRangeB, UFUNCTION(), and Value.
UFUNCTION() [631/736]
UKismetMathLibrary::UFUNCTION () private
Returns Value mapped from one range into another.
(e.g. 20 normalized from the range 10->50 to 20->40 would result in 25)
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [632/736]
UKismetMathLibrary::UFUNCTION () private
This functions returns 0 if B (the denominator) is zero.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [633/736]
UKismetMathLibrary::UFUNCTION () const & private
Utility function to build an box from an Origin and Extent.
Parameters
Origin The location of the bounding box.
Extent Half size of the bounding box.
Returns
A new axis-aligned bounding box.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [634/736]
UKismetMathLibrary::UFUNCTION () private
Makes a DateTime struct.
References AdvancedDisplay, Category, meta, and UFUNCTION().
UFUNCTION() [635/736]
UKismetMathLibrary::UFUNCTION () private
Creates a FFrameRate from a Numerator and a Denominator.
Enforces that the Denominator is at least one.
References Category, meta, and UFUNCTION().
UFUNCTION() [636/736]
UKismetMathLibrary::UFUNCTION () private
Maps a 1D array index to a 2D array index.
Parameters
Index1D - The 1D array index
XSize - X dimension of the 2D array
Returns
The equivalent 2D index of the array
References Category, meta, and UFUNCTION().
UFUNCTION() [637/736]
UKismetMathLibrary::UFUNCTION () private
Maps a 1D array index to a 3D array index.
Parameters
Index1D - The 1D array index
XSize - X dimension of the 3D array
YSize - Y dimension of the 3D array
Returns
The equivalent 3D index of the array
References Category, meta, and UFUNCTION().
UFUNCTION() [638/736]
UKismetMathLibrary::UFUNCTION () private
Calculates the new value in a weighted moving average series using the previous value and a weight range.
The weight range is used to dynamically adjust based upon distance between the samples This allows you to smooth a value more aggressively for small noise and let large movements be smoothed less (or vice versa)
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
MaxDistance - Distance to use as the blend between min weight or max weight
MinWeight - The weight use when the distance is small
MaxWeight - The weight use when the distance is large
Returns
the next value in the series
References Category, meta, and UFUNCTION().
UFUNCTION() [639/736]
UKismetMathLibrary::UFUNCTION () private
Uses a simple spring model to interpolate a float from Current to Target.
Parameters
Current Current value
Target Target value
SpringState Data related to spring model (velocity, error, etc..) - Create a unique variable per spring
Stiffness How stiff the spring model is (more stiffness means more oscillation around the target value)
CriticalDampingFactor How much damping to apply to the spring (0 means no damping, 1 means critically damped which means no oscillation)
DeltaTime Time difference since the last update
Mass Multiplier that acts like mass on a spring
TargetVelocityAmount If 1 then the target velocity will be calculated and used, which results following the target more closely/without lag. Values down to zero (recommended when using this to smooth data) will progressively disable this effect.
bClamp Whether to use the Min/Max values to clamp the motion
MinValue Clamps the minimum output value and cancels the velocity if it reaches this limit
MaxValue Clamps the maximum output value and cancels the velocity if it reaches this limit
bInitializeFromTarget If set then the current value will be set from the target on the first update
References AdvancedDisplay, Category, meta, and UFUNCTION().
UFUNCTION() [640/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random float between 0 and 1.
References Category, meta, ScriptMethod, and Stream.
UFUNCTION() [641/736]
UKismetMathLibrary::UFUNCTION () const & private
Generate a random number between Min and Max.
References Category, meta, and ScriptMethod.
UFUNCTION() [642/736]
UKismetMathLibrary::UFUNCTION () const & private
Calculates the determinant of the transform (converts to FMatrix internally)
References Category, meta, ScriptMethod, Transform, and UFUNCTION().
UFUNCTION() [643/736]
UKismetMathLibrary::UFUNCTION () private
Calculates the new value in a weighted moving average series using the previous value and the weight.
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
Weight - The weight to blend with
Returns
the next value in the series
References Category, meta, and UFUNCTION().
UFUNCTION() [644/736]
UKismetMathLibrary::UFUNCTION () private
Creates a plane with a facing direction of Normal at the given Point.
Parameters
Point A point on the plane
Normal The Normal of the plane at Point
Returns
Plane instance
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [645/736]
UKismetMathLibrary::UFUNCTION () private
Creates a FQualifiedFrameTime out of a frame number, frame rate, and optional 0-1 clamped subframe.
References Category, meta, and UFUNCTION().
UFUNCTION() [646/736]
UKismetMathLibrary::UFUNCTION () const & private
Makes a random stream that will generate deterministic values, optionally grouping outputs within cells on a grid.
Parameters
Location The input location to return the stream for
DistanceInterval If non-zero, the grid size for which all locations within a grid cell will return the same random stream
bIncludeZ Whether to factor in the Z-coordinate of the input location
References Category, meta, and UFUNCTION().
UFUNCTION() [647/736]
UKismetMathLibrary::UFUNCTION () private
Calculates the new value in a weighted moving average series using the previous value and a weight range.
The weight range is used to dynamically adjust based upon distance between the samples This allows you to smooth a value more aggressively for small noise and let large movements be smoothed less (or vice versa)
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
MaxDistance - Distance to use as the blend between min weight or max weight
MinWeight - The weight use when the distance is small
MaxWeight - The weight use when the distance is large
Returns
the next value in the series
References Category, meta, and UFUNCTION().
UFUNCTION() [648/736]
UKismetMathLibrary::UFUNCTION () const & private
Find a local rotation (range of [-180, 180]) for an object with StartTransform to point at TargetLocation.
Useful for getting LookAt Azimuth or Pawn Aim Offset.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [649/736]
UKismetMathLibrary::UFUNCTION () private
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [650/736]
UKismetMathLibrary::UFUNCTION () private
Makes a rotator {Roll, Pitch, Yaw} from rotation values supplied in degrees.
References Category, Keywords, meta, Pitch, UFUNCTION(), UPARAM(), and Yaw.
UFUNCTION() [651/736]
UKismetMathLibrary::UFUNCTION () private
Generates a random rotation, with optional random roll.
References bRoll, Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [652/736]
UKismetMathLibrary::UFUNCTION () const & private
Create a random rotation.
References Category, meta, and ScriptMethod.
UFUNCTION() [653/736]
UKismetMathLibrary::UFUNCTION () private
If bPickA is true, A is returned, otherwise B is.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [654/736]
UKismetMathLibrary::UFUNCTION () private
Calculates the new value in a weighted moving average series using the previous value and the weight.
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
Weight - The weight to blend with
Returns
the next value in the series
References Category, meta, and UFUNCTION().
UFUNCTION() [655/736]
UKismetMathLibrary::UFUNCTION () private
Makes a Timespan struct.
References Category, meta, and UFUNCTION().
UFUNCTION() [656/736]
UKismetMathLibrary::UFUNCTION () private
Makes a Timespan struct.
References Category, meta, and UFUNCTION().
UFUNCTION() [657/736]
UKismetMathLibrary::UFUNCTION () private
Creates a directional vector from rotation values {Pitch, Yaw} supplied in degrees with specified Length.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [658/736]
UKismetMathLibrary::UFUNCTION () private
Calculates the new value in a weighted moving average series using the previous value and a weight range.
The weight range is used to dynamically adjust based upon distance between the samples This allows you to smooth a value more aggressively for small noise and let large movements be smoothed less (or vice versa)
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
MaxDistance - Distance to use as the blend between min weight or max weight
MinWeight - The weight use when the distance is small
MaxWeight - The weight use when the distance is large
Returns
the next value in the series
References Category, meta, and UFUNCTION().
UFUNCTION() [659/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random point within the specified bounding box using the first vector as an origin and the second as the half size of the AABB.
References Category, meta, and ScriptMethod.
UFUNCTION() [660/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random vector with length of 1.
References Category, FVector, meta, and UFUNCTION().
UFUNCTION() [661/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random vector with length of 1.0.
References Category, FVector, meta, ScriptMethod, and Stream.
UFUNCTION() [662/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
Parameters
ConeDir The base "center" direction of the cone.
ConeHalfAngleInRadians The half-angle of the cone (from ConeDir to edge), in radians.
Stream The random stream from which to obtain the vector.
References Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [663/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
The shape of the cone can be modified according to the yaw and pitch angles.
Parameters
MaxYawInRadians The yaw angle of the cone (from ConeDir to horizontal edge), in radians.
MaxPitchInRadians The pitch angle of the cone (from ConeDir to vertical edge), in radians.
References Category, Keywords, and meta.
UFUNCTION() [664/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
The shape of the cone can be modified according to the yaw and pitch angles.
Parameters
MaxYawInRadians The yaw angle of the cone (from ConeDir to horizontal edge), in radians.
MaxPitchInRadians The pitch angle of the cone (from ConeDir to vertical edge), in radians.
Stream The random stream from which to obtain the vector.
References Category, Keywords, meta, and ScriptMethod.
UFUNCTION() [665/736]
UKismetMathLibrary::UFUNCTION () private
Calculates the new value in a weighted moving average series using the previous value and the weight.
Parameters
CurrentSample - The value to blend with the previous sample to get a new weighted value
PreviousSample - The last value from the series
Weight - The weight to blend with
Returns
the next value in the series
References Category, meta, and UFUNCTION().
UFUNCTION() [666/736]
UKismetMathLibrary::UFUNCTION () const & private
Maps a 2D array index to a 1D array index.
Parameters
Index2D - The 2D array index
XSize - X dimension of the 2D array
Returns
The equivalent 1D index of the array
References Category, meta, UFUNCTION(), and XSize.
UFUNCTION() [667/736]
UKismetMathLibrary::UFUNCTION () const & private
Maps a 3D array index to a 1D array index.
Parameters
Index3D - The 3D array index
XSize - X dimension of the 3D array
YSize - Y dimension of the 3D array
Returns
The equivalent 1D index of the array
References Category, meta, UFUNCTION(), XSize, and YSize.
UFUNCTION() [668/736]
UKismetMathLibrary::UFUNCTION () private
Returns a uniformly distributed random number between 0 and Max - 1.
References Category, Max, meta, UFUNCTION(), and UPARAM().
UFUNCTION() [669/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a uniformly distributed random number between 0 and Max - 1.
References Category, Max, meta, ScriptMethod, Stream, and UFUNCTION().
UFUNCTION() [670/736]
UKismetMathLibrary::UFUNCTION () const & private
Return a random integer between Min and Max (>= Min and <= Max)
References Category, meta, and ScriptMethod.
UFUNCTION() [671/736]
UKismetMathLibrary::UFUNCTION () private
Returns a uniformly distributed random number between 0 and Max - 1.
References Category, Max, meta, UFUNCTION(), and UPARAM().
UFUNCTION() [672/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a DateTime into its components.
References AdvancedDisplay, Category, meta, and UFUNCTION().
UFUNCTION() [673/736]
UKismetMathLibrary::UFUNCTION () const & private
Breaks a FFrameRate into a numerator and denominator.
References Category, meta, and UFUNCTION().
UFUNCTION() [674/736]
UKismetMathLibrary::UFUNCTION () const & private
Breaks a FQualifiedFrameTime into its component parts again.
References Category, meta, and UFUNCTION().
UFUNCTION() [675/736]
UKismetMathLibrary::UFUNCTION () const & private
Breaks apart a random number generator.
References Category, meta, and UFUNCTION().
UFUNCTION() [676/736]
UKismetMathLibrary::UFUNCTION () private
Breaks apart a rotator into {Roll, Pitch, Yaw} angles in degrees.
References Category, Keywords, meta, Pitch, UFUNCTION(), UPARAM(), and Yaw.
UFUNCTION() [677/736]
UKismetMathLibrary::UFUNCTION () const & private
Breaks apart a rotator into its component axes.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [678/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a Timespan into its components.
References Category, meta, and UFUNCTION().
UFUNCTION() [679/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a Timespan into its components.
References Category, meta, and UFUNCTION().
UFUNCTION() [680/736]
UKismetMathLibrary::UFUNCTION () const & private
Breaks apart a transform into location, rotation and scale.
References Category, meta, and UFUNCTION().
UFUNCTION() [681/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a direction vector apart into Azimuth (Yaw) and Elevation (Pitch) rotation values given in degrees.
(non-clamped) Relative to the provided reference frame (an Actor's WorldTransform for example)
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [682/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a vector apart into Yaw, Pitch rotation values given in degrees.
(non-clamped)
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [683/736]
UKismetMathLibrary::UFUNCTION () private
Finds the minimum area rectangle that encloses a set of coplanar points.
Uses the exhaustive search algorithm in http://www.geometrictools.com/Documentation/MinimumAreaRectangle.pdf
Parameters
WorldContextObject - Pointer to world context; only used when debug draw is enabled
InPoints - Points to enclose in the rectangle; need to be within the same plane for correct results
SampleSurfaceNormal - Normal indicating the surface direction for the points
OutRectCenter - Translation for the output rectangle from the origin
OutRectRotation - Rotation for the output rectangle from the XY plane
OutRectLengthX - Length of the output rectangle along the X axis before rotation
OutRectLengthY - Length of the output rectangle along the Y axis before rotation
bDebugDraw - Draws the output rectangle for debugging purposes provided the world context is set as well
References Category, meta, and UFUNCTION().
UFUNCTION() [684/736]
UKismetMathLibrary::UFUNCTION () const & private
Reset a random stream.
References Category, meta, ScriptMethod, and Stream.
UFUNCTION() [685/736]
UKismetMathLibrary::UFUNCTION () & private
Create a new random seed for a random stream.
References Category, meta, ScriptMethod, Stream, and UPARAM().
UFUNCTION() [686/736]
UKismetMathLibrary::UFUNCTION () & private
Set the seed of a random stream to a specific number.
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [687/736]
UKismetMathLibrary::UFUNCTION () private
Converts a 32 bit floating point to a 64 bit floating point.
References BlueprintInternalUseOnly, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [688/736]
UKismetMathLibrary::UFUNCTION () private
Returns exponential(e) to the power A (e^A)
References A, Category, CompactNodeTitle, Exp, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [689/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random float between 0 and 1.
References Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [690/736]
UKismetMathLibrary::UFUNCTION () private
Generate a random number between Min and Max.
References Category, meta, and UFUNCTION().
UFUNCTION() [691/736]
UKismetMathLibrary::UFUNCTION () private
Returns square root of A.
References A, Category, CompactNodeTitle, Keywords, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [692/736]
UKismetMathLibrary::UFUNCTION () private
Returns square of A (A*A)
References A, Category, CompactNodeTitle, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [693/736]
UKismetMathLibrary::UFUNCTION () private
Makes an FBox from Min and Max and sets IsValid to true.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [694/736]
UKismetMathLibrary::UFUNCTION () private
Makes an FBox2D from Min and Max and sets IsValid to true.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [695/736]
UKismetMathLibrary::UFUNCTION () private
Make a color from individual color components (HSV space; Hue is [0..360) while Saturation and Value are 0..1)
References Category, meta, and UFUNCTION().
UFUNCTION() [696/736]
UKismetMathLibrary::UFUNCTION () private
Make a color from individual color components (RGB space)
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [697/736]
UKismetMathLibrary::UFUNCTION () private
Converts a 64 bit floating point to a 32 bit floating point (if the float is too large, returns the low 32 bits)
References BlueprintInternalUseOnly, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [698/736]
UKismetMathLibrary::UFUNCTION () private
Makes a quat {X, Y, Z, W}.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [699/736]
UKismetMathLibrary::UFUNCTION () const & private
Find a rotation for an object at Start location to point at Target location.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [700/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a rotator given only a XAxis.
Y and Z are unspecified but will be orthonormal. XAxis need not be normalized.
References Category, FVector, Keywords, meta, UE_INL_API, UFUNCTION(), and X.
UFUNCTION() [701/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a matrix with given X and Y axes.
X will remain fixed, Y may be changed minimally to enforce orthogonality. Z will be computed. Inputs need not be normalized.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [702/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a matrix with given X and Z axes.
X will remain fixed, Z may be changed minimally to enforce orthogonality. Y will be computed. Inputs need not be normalized.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [703/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a rotation matrix given only a YAxis.
X and Z are unspecified but will be orthonormal. YAxis need not be normalized.
References Category, FVector, Keywords, meta, UE_INL_API, UFUNCTION(), and Y.
UFUNCTION() [704/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a matrix with given Y and X axes.
Y will remain fixed, X may be changed minimally to enforce orthogonality. Z will be computed. Inputs need not be normalized.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [705/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a matrix with given Y and Z axes.
Y will remain fixed, Z may be changed minimally to enforce orthogonality. X will be computed. Inputs need not be normalized.
References Category, FVector, Keywords, meta, UE_INL_API, UFUNCTION(), Y, and Z.
UFUNCTION() [706/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a rotation matrix given only a ZAxis.
X and Y are unspecified but will be orthonormal. ZAxis need not be normalized.
References Category, FVector, Keywords, meta, UE_INL_API, UFUNCTION(), and Z.
UFUNCTION() [707/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a matrix with given Z and X axes.
Z will remain fixed, X may be changed minimally to enforce orthogonality. Y will be computed. Inputs need not be normalized.
References Category, FVector, Keywords, meta, UE_INL_API, UFUNCTION(), X, and Z.
UFUNCTION() [708/736]
UKismetMathLibrary::UFUNCTION () const & private
Builds a matrix with given Z and Y axes.
Z will remain fixed, Y may be changed minimally to enforce orthogonality. X will be computed. Inputs need not be normalized.
References Category, FVector, Keywords, meta, UE_INL_API, UFUNCTION(), Y, and Z.
UFUNCTION() [709/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target rotation based on Current rotation, giving a nice smooth feeling when rotating to Target rotation.
Parameters
Current Actual rotation
Target Target rotation
DeltaTime Time since last tick
InterpSpeed Interpolation speed, if the speed given is 0, then jump to the target.
Returns
New interpolated position
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [710/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target rotation at a constant rate.
Parameters
Current Actual rotation
Target Target rotation
DeltaTime Time since last tick
InterpSpeed Interpolation speed
Returns
New interpolated position
References Category, DeltaTime, InterpSpeed, Keywords, meta, Target, UE_INL_API, and UFUNCTION().
UFUNCTION() [711/736]
UKismetMathLibrary::UFUNCTION () private
Makes a vector {X, Y, Z}.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [712/736]
UKismetMathLibrary::UFUNCTION () const private
Returns a random point within the specified bounding box using the first vector as an origin and the second as the box extents.
References Category, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [713/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
Parameters
ConeDir The base "center" direction of the cone.
ConeHalfAngleInRadians The half-angle of the cone (from ConeDir to edge), in radians.
References Category, meta, and UFUNCTION().
UFUNCTION() [714/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target based on distance from Current position, giving a nice smooth feeling when tracking a position.
Parameters
Current Actual position
Target Target position
DeltaTime Time since last tick
InterpSpeed Interpolation speed, if the speed given is 0, then jump to the target.
Returns
New interpolated position
References Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [715/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target at a constant rate.
Parameters
Current Actual position
Target Target position
DeltaTime Time since last tick
InterpSpeed Interpolation speed
Returns
New interpolated position
References Category, DeltaTime, FVector, InterpSpeed, Keywords, meta, ScriptMethod, Target, UE_INL_API, and UFUNCTION().
UFUNCTION() [716/736]
UKismetMathLibrary::UFUNCTION () private
Makes a 2d vector {X, Y}.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [717/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target based on distance from Current position, giving a nice smooth feeling when tracking a position.
Parameters
Current Actual position
Target Target position
DeltaTime Time since last tick
InterpSpeed Interpolation speed, if the speed given is 0, then jump to the target.
Returns
New interpolated position
References Category, Keywords, meta, ScriptMethod, and UFUNCTION().
UFUNCTION() [718/736]
UKismetMathLibrary::UFUNCTION () private
Tries to reach Target at a constant rate.
Parameters
Current Actual position
Target Target position
DeltaTime Time since last tick
InterpSpeed Interpolation speed
Returns
New interpolated position
References Category, DeltaTime, InterpSpeed, Keywords, meta, ScriptMethod, Target, UE_INL_API, and UFUNCTION().
UFUNCTION() [719/736]
UKismetMathLibrary::UFUNCTION () private
References Category, meta, UE_INL_API, UFUNCTION(), X, Y, and Z.
UFUNCTION() [720/736]
UKismetMathLibrary::UFUNCTION () private
References Category, meta, UE_INL_API, X, Y, and Z.
UFUNCTION() [721/736]
UKismetMathLibrary::UFUNCTION () private
References Category, meta, UE_INL_API, X, Y, and Z.
UFUNCTION() [722/736]
UKismetMathLibrary::UFUNCTION () private
References Category, meta, UE_INL_API, X, Y, and Z.
UFUNCTION() [723/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
Parameters
ConeDir The base "center" direction of the cone.
ConeHalfAngleInDegrees The half-angle of the cone (from ConeDir to edge), in degrees.
References Category, meta, and UFUNCTION().
UFUNCTION() [724/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
Parameters
ConeDir The base "center" direction of the cone.
ConeHalfAngleInDegrees The half-angle of the cone (from ConeDir to edge), in degrees.
Stream The random stream from which to obtain the vector.
References Category, Keywords, meta, and ScriptMethod.
UFUNCTION() [725/736]
UKismetMathLibrary::UFUNCTION () private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
The shape of the cone can be modified according to the yaw and pitch angles.
Parameters
MaxYawInDegrees The yaw angle of the cone (from ConeDir to horizontal edge), in degrees.
MaxPitchInDegrees The pitch angle of the cone (from ConeDir to vertical edge), in degrees.
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [726/736]
UKismetMathLibrary::UFUNCTION () const & private
Returns a random vector with length of 1, within the specified cone, with uniform random distribution.
The shape of the cone can be modified according to the yaw and pitch angles.
Parameters
MaxYawInDegrees The yaw angle of the cone (from ConeDir to horizontal edge), in degrees.
MaxPitchInDegrees The pitch angle of the cone (from ConeDir to vertical edge), in degrees.
Stream The random stream from which to obtain the vector.
References Category, Keywords, meta, and ScriptMethod.
UFUNCTION() [727/736]
UKismetMathLibrary::UFUNCTION () private
Rounds A up towards positive infinity / up to the next integer (e.g., -1.6 becomes -1 and 1.6 becomes 2)
References A, Category, meta, UE_INL_API, and UFUNCTION().
UFUNCTION() [728/736]
UKismetMathLibrary::UFUNCTION () private
Return a random integer between Min and Max (>= Min and <= Max)
References Category, meta, and UFUNCTION().
UFUNCTION() [729/736]
UKismetMathLibrary::UFUNCTION () private
Return a random integer64 between Min and Max (>= Min and <= Max)
References Category, meta, and UFUNCTION().
UFUNCTION() [730/736]
UKismetMathLibrary::UFUNCTION () const & private
Breaks a quat apart into X, Y, Z, W.
References Category, meta, and UFUNCTION().
UFUNCTION() [731/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a vector apart into X, Y, Z.
References Category, meta, and UFUNCTION().
UFUNCTION() [732/736]
UKismetMathLibrary::UFUNCTION () private
Breaks a 2D vector apart into X, Y.
References Category, meta, and UFUNCTION().
UFUNCTION() [733/736]
UKismetMathLibrary::UFUNCTION () private
References Category, FVector, meta, UE_INL_API, X, Y, and Z.
UFUNCTION() [734/736]
UKismetMathLibrary::UFUNCTION () private
References Category, FVector, meta, UE_INL_API, X, Y, and Z.
UFUNCTION() [735/736]
UKismetMathLibrary::UFUNCTION () private
References Category, FVector, meta, UE_INL_API, X, Y, and Z.
UFUNCTION() [736/736]
UKismetMathLibrary::UFUNCTION () private
References Category, FVector, meta, UE_INL_API, X, Y, and Z.
UPARAM()
float UKismetMathLibrary::UPARAM (ref) & private
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Field Documentation
A [1/2]
float float float UKismetMathLibrary::A = 1.0f) private
Definition at line 3028 of file KismetMathLibrary.h.
Referenced by DECLARE_FUNCTION(), GenericPercent_FloatFloat(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
A [2/2]
float float float float& UKismetMathLibrary::A private
Definition at line 3032 of file KismetMathLibrary.h.
AdvancedDisplay
UKismetMathLibrary::AdvancedDisplay = "3" private
Definition at line 4030 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Alpha
double double UKismetMathLibrary::Alpha private
Definition at line 782 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
AngularVelocity
FVector UKismetMathLibrary::AngularVelocity private
Definition at line 4155 of file KismetMathLibrary.h.
APlane
const FVector const FPlane& UKismetMathLibrary::APlane private
Definition at line 4447 of file KismetMathLibrary.h.
AverageValue
float& UKismetMathLibrary::AverageValue private
Definition at line 762 of file KismetMathLibrary.h.
Azimuth
const FTransform float& UKismetMathLibrary::Azimuth private
Definition at line 1584 of file KismetMathLibrary.h.
B [1/14]
double UKismetMathLibrary::B private
Definition at line 746 of file KismetMathLibrary.h.
Referenced by DECLARE_FUNCTION(), GenericPercent_FloatFloat(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
B [2/14]
float float UKismetMathLibrary::B private
Definition at line 3028 of file KismetMathLibrary.h.
B [3/14]
float float float& UKismetMathLibrary::B private
Definition at line 3032 of file KismetMathLibrary.h.
B [4/14]
const FBox& UKismetMathLibrary::B private
Definition at line 3755 of file KismetMathLibrary.h.
B [5/14]
const FString& UKismetMathLibrary::B private
Definition at line 3834 of file KismetMathLibrary.h.
B [6/14]
const FText UKismetMathLibrary::B private
Definition at line 3838 of file KismetMathLibrary.h.
B [7/14]
const FName UKismetMathLibrary::B private
Definition at line 3842 of file KismetMathLibrary.h.
B [8/14]
int32 UKismetMathLibrary::B private
Definition at line 3846 of file KismetMathLibrary.h.
B [9/14]
FVector UKismetMathLibrary::B private
Definition at line 3854 of file KismetMathLibrary.h.
B [10/14]
FRotator UKismetMathLibrary::B private
Definition at line 3858 of file KismetMathLibrary.h.
B [11/14]
FLinearColor UKismetMathLibrary::B private
Definition at line 3862 of file KismetMathLibrary.h.
B [12/14]
const FTransform& UKismetMathLibrary::B private
Definition at line 3866 of file KismetMathLibrary.h.
B [13/14]
UObject* UKismetMathLibrary::B private
Definition at line 3870 of file KismetMathLibrary.h.
B [14/14]
UClass* UKismetMathLibrary::B private
Definition at line 3874 of file KismetMathLibrary.h.
Base
double UKismetMathLibrary::Base = 1.0) private
Definition at line 652 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
bClamp
float float float float float float bool UKismetMathLibrary::bClamp = false private
Definition at line 4130 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
bDebugDraw
const TArray<FVector> const FVector FVector FRotator float float bool UKismetMathLibrary::bDebugDraw = false) private
Definition at line 4344 of file KismetMathLibrary.h.
bIncludeZ
float bool UKismetMathLibrary::bIncludeZ = false) private
Definition at line 3826 of file KismetMathLibrary.h.
bInitializeFromTarget
float float float float float float bool float float bool UKismetMathLibrary::bInitializeFromTarget = false) private
Definition at line 4131 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
BlueprintAutocast
UKismetMathLibrary::BlueprintAutocast private
Definition at line 924 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
BlueprintInternalUseOnly
UKismetMathLibrary::BlueprintInternalUseOnly private
Initial value:
= "true"), Category = "Math|Interpolation")
    static 1 FVector VEase(FVector A, FVector B, float Alpha, TEnumAsByte<EEasingFunc::Type> EasingFunc, float BlendExp = 2, int32 Steps = 2)
Definition at line 1745 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Box
FBox UKismetMathLibrary::Box private
Definition at line 4376 of file KismetMathLibrary.h.
Referenced by RandomPointInBoundingBox_Box(), UE_DEPRECATED(), and UFUNCTION().
BoxExtent [1/3]
FVector FVector UKismetMathLibrary::BoxExtent private
Definition at line 4366 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
BoxExtent [2/3]
const FTransform FVector UKismetMathLibrary::BoxExtent private
Definition at line 4411 of file KismetMathLibrary.h.
BoxExtent [3/3]
const FTransform FBox UKismetMathLibrary::BoxExtent private
Definition at line 4422 of file KismetMathLibrary.h.
BoxOrigin
FVector UKismetMathLibrary::BoxOrigin private
Definition at line 4366 of file KismetMathLibrary.h.
BoxWorldTransform
const FTransform & UKismetMathLibrary::BoxWorldTransform private
Definition at line 4411 of file KismetMathLibrary.h.
bPickA [1/9]
const FString bool UKismetMathLibrary::bPickA private
Definition at line 3834 of file KismetMathLibrary.h.
bPickA [2/9]
const FText bool UKismetMathLibrary::bPickA private
Definition at line 3838 of file KismetMathLibrary.h.
bPickA [3/9]
const FName bool UKismetMathLibrary::bPickA private
Definition at line 3842 of file KismetMathLibrary.h.
bPickA [4/9]
int32 bool UKismetMathLibrary::bPickA private
Definition at line 3846 of file KismetMathLibrary.h.
bPickA [5/9]
double bool UKismetMathLibrary::bPickA private
Definition at line 3850 of file KismetMathLibrary.h.
bPickA [6/9]
FVector bool UKismetMathLibrary::bPickA private
Definition at line 3854 of file KismetMathLibrary.h.
bPickA [7/9]
FRotator bool UKismetMathLibrary::bPickA private
Definition at line 3858 of file KismetMathLibrary.h.
bPickA [8/9]
FLinearColor bool UKismetMathLibrary::bPickA private
Definition at line 3862 of file KismetMathLibrary.h.
bPickA [9/9]
const FTransform bool UKismetMathLibrary::bPickA private
Definition at line 3866 of file KismetMathLibrary.h.
bRoll
bool UKismetMathLibrary::bRoll private
Definition at line 4225 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED(), and UFUNCTION().
bSelectA [1/2]
UObject bool UKismetMathLibrary::bSelectA private
Definition at line 3870 of file KismetMathLibrary.h.
bSelectA [2/2]
UClass bool UKismetMathLibrary::bSelectA private
Definition at line 3874 of file KismetMathLibrary.h.
Category
UKismetMathLibrary::Category private
Initial value:
="Math|Boolean")
    static  bool Not_PreBool(bool A)
Definition at line 222 of file KismetMathLibrary.h.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Center
const FVector UKismetMathLibrary::Center private
Definition at line 4205 of file KismetMathLibrary.h.
CommutativeAssociativeBinaryOperator
UKismetMathLibrary::CommutativeAssociativeBinaryOperator private
Initial value:
= "true"), Category = "Math|Byte")
    static  uint8 BMin(uint8 A, uint8 B)
Definition at line 278 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
CompactNodeTitle
UKismetMathLibrary::CompactNodeTitle = "==" private
Definition at line 226 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
ConeDir
const FVector & UKismetMathLibrary::ConeDir private
Definition at line 4252 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
ConeHalfAngleInDegrees [1/2]
float UKismetMathLibrary::ConeHalfAngleInDegrees private
Initial value:
{
        return RandomUnitVectorInConeInRadians(ConeDir, FMath::DegreesToRadians(ConeHalfAngleInDegrees))
Definition at line 2011 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED().
ConeHalfAngleInDegrees [2/2]
const FVector float UKismetMathLibrary::ConeHalfAngleInDegrees private
Initial value:
{
        return RandomUnitVectorInConeInRadiansFromStream(Stream, ConeDir, FMath::DegreesToRadians(ConeHalfAngleInDegrees))
Definition at line 4267 of file KismetMathLibrary.h.
ConeHalfAngleInRadians [1/2]
float UKismetMathLibrary::ConeHalfAngleInRadians private
Definition at line 2003 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED().
ConeHalfAngleInRadians [2/2]
const FVector float UKismetMathLibrary::ConeHalfAngleInRadians private
Definition at line 4252 of file KismetMathLibrary.h.
CriticalDampingFactor
float float float UKismetMathLibrary::CriticalDampingFactor private
Definition at line 4128 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Day [1/2]
int32 int32 UKismetMathLibrary::Day private
Definition at line 3242 of file KismetMathLibrary.h.
Day [2/2]
int32 int32 int32& UKismetMathLibrary::Day private
Definition at line 3246 of file KismetMathLibrary.h.
Days
int32 & UKismetMathLibrary::Days private
Definition at line 3438 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
DeltaTime [1/5]
FRotator float UKismetMathLibrary::DeltaTime private
Definition at line 1168 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
DeltaTime [2/5]
FVector float UKismetMathLibrary::DeltaTime private
Definition at line 1758 of file KismetMathLibrary.h.
DeltaTime [3/5]
double double UKismetMathLibrary::DeltaTime private
Definition at line 4072 of file KismetMathLibrary.h.
DeltaTime [4/5]
FRotator float UKismetMathLibrary::DeltaTime private
Definition at line 4096 of file KismetMathLibrary.h.
DeltaTime [5/5]
float float float float UKismetMathLibrary::DeltaTime private
Definition at line 4128 of file KismetMathLibrary.h.
Denominator [1/2]
int32 UKismetMathLibrary::Denominator = 1) private
Definition at line 3570 of file KismetMathLibrary.h.
Denominator [2/2]
int32 int32& UKismetMathLibrary::Denominator private
Definition at line 3574 of file KismetMathLibrary.h.
DistanceInterval
float UKismetMathLibrary::DistanceInterval = 200.f private
Definition at line 3826 of file KismetMathLibrary.h.
Elevation
const FTransform float float& UKismetMathLibrary::Elevation private
Definition at line 1584 of file KismetMathLibrary.h.
Exponent
double double double UKismetMathLibrary::Exponent private
Definition at line 850 of file KismetMathLibrary.h.
Extent
const FVector& UKismetMathLibrary::Extent private
Definition at line 3706 of file KismetMathLibrary.h.
FloorNormal
const FVector& UKismetMathLibrary::FloorNormal private
Definition at line 4434 of file KismetMathLibrary.h.
FractionNano [1/2]
int32 int32 int32 int32 UKismetMathLibrary::FractionNano private
Definition at line 3434 of file KismetMathLibrary.h.
FractionNano [2/2]
int32 int32 int32 int32 int32& UKismetMathLibrary::FractionNano private
Definition at line 3442 of file KismetMathLibrary.h.
Frame
FFrameNumber& UKismetMathLibrary::Frame private
Definition at line 3566 of file KismetMathLibrary.h.
FrameRate [1/2]
FFrameRate UKismetMathLibrary::FrameRate private
Definition at line 3562 of file KismetMathLibrary.h.
FrameRate [2/2]
FFrameNumber FFrameRate& UKismetMathLibrary::FrameRate private
Definition at line 3566 of file KismetMathLibrary.h.
G [1/2]
float UKismetMathLibrary::G private
Definition at line 3028 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
G [2/2]
float float& UKismetMathLibrary::G private
Definition at line 3032 of file KismetMathLibrary.h.
HalfSize [1/2]
const FVector UKismetMathLibrary::HalfSize private
Definition at line 1991 of file KismetMathLibrary.h.
HalfSize [2/2]
const FVector const FVector UKismetMathLibrary::HalfSize private
Definition at line 4205 of file KismetMathLibrary.h.
Hour [1/2]
int32 int32 int32 UKismetMathLibrary::Hour = 0 private
Definition at line 3242 of file KismetMathLibrary.h.
Hour [2/2]
int32 int32 int32 int32& UKismetMathLibrary::Hour private
Definition at line 3246 of file KismetMathLibrary.h.
Hours [1/2]
int32 int32 & UKismetMathLibrary::Hours private
Definition at line 3430 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Hours [2/2]
int32 int32& UKismetMathLibrary::Hours private
Definition at line 3438 of file KismetMathLibrary.h.
InDefaultValue
const float const float UKismetMathLibrary::InDefaultValue = 0.0f) private
Definition at line 864 of file KismetMathLibrary.h.
InDeltaRate
float float UKismetMathLibrary::InDeltaRate private
Definition at line 888 of file KismetMathLibrary.h.
InDesired
float UKismetMathLibrary::InDesired private
Definition at line 888 of file KismetMathLibrary.h.
IndexOfMaxValue
int32 & UKismetMathLibrary::IndexOfMaxValue private
Definition at line 750 of file KismetMathLibrary.h.
IndexOfMinValue
int32 & UKismetMathLibrary::IndexOfMinValue private
Definition at line 754 of file KismetMathLibrary.h.
InitialSeed
int32& UKismetMathLibrary::InitialSeed private
Definition at line 3830 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
InNormal
FVector UKismetMathLibrary::InNormal private
Definition at line 1845 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
InPhase
float float UKismetMathLibrary::InPhase = 0.0f) private
Definition at line 876 of file KismetMathLibrary.h.
InPoints
const TArray<FVector>& UKismetMathLibrary::InPoints private
Definition at line 4343 of file KismetMathLibrary.h.
InPulsesPerSecond
float UKismetMathLibrary::InPulsesPerSecond = 1.0f private
Definition at line 876 of file KismetMathLibrary.h.
InRangeA
double UKismetMathLibrary::InRangeA private
Definition at line 838 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
InRangeB
double double UKismetMathLibrary::InRangeB private
Definition at line 838 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
InterpSpeed [1/4]
FRotator float float UKismetMathLibrary::InterpSpeed private
Definition at line 1168 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
InterpSpeed [2/4]
FVector float float UKismetMathLibrary::InterpSpeed private
Definition at line 1758 of file KismetMathLibrary.h.
InterpSpeed [3/4]
double double double UKismetMathLibrary::InterpSpeed private
Definition at line 4072 of file KismetMathLibrary.h.
InterpSpeed [4/4]
FRotator float float UKismetMathLibrary::InterpSpeed private
Definition at line 4096 of file KismetMathLibrary.h.
Intersection [1/2]
const FVector const FPlane float FVector& UKismetMathLibrary::Intersection private
Definition at line 4447 of file KismetMathLibrary.h.
Intersection [2/2]
const FVector FVector FVector float FVector& UKismetMathLibrary::Intersection private
Definition at line 4456 of file KismetMathLibrary.h.
InTime
const float UKismetMathLibrary::InTime private
Definition at line 864 of file KismetMathLibrary.h.
Keywords
UKismetMathLibrary::Keywords private
Initial value:
= "== equal"), Category="Math|Boolean")
    static  bool EqualEqual_BoolBool(bool A, bool B)
Definition at line 226 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Length
float float UKismetMathLibrary::Length = 1.0f) private
Definition at line 1290 of file KismetMathLibrary.h.
LineDirection
FVector FVector UKismetMathLibrary::LineDirection private
Definition at line 1961 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
LineEnd
const FVector & UKismetMathLibrary::LineEnd private
Definition at line 4447 of file KismetMathLibrary.h.
LineOrigin
FVector UKismetMathLibrary::LineOrigin private
Definition at line 1961 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Location
FVector& UKismetMathLibrary::Location private
Definition at line 3934 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Mass
float float float float float UKismetMathLibrary::Mass = 1.f private
Definition at line 4129 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Max [1/9]
int32 UKismetMathLibrary::Max private
Initial value:
= "10"), Category = "Math|Integer")
    static 1 bool InRange_IntInt(int32 Value, int32 Min, int32 Max, bool InclusiveMin = true, bool InclusiveMax = true)
Definition at line 361 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Max [2/9]
int32 UKismetMathLibrary::Max private
Definition at line 390 of file KismetMathLibrary.h.
Max [3/9]
int64 UKismetMathLibrary::Max private
Definition at line 493 of file KismetMathLibrary.h.
Max [4/9]
double UKismetMathLibrary::Max private
Definition at line 672 of file KismetMathLibrary.h.
Max [5/9]
FVector UKismetMathLibrary::Max private
Definition at line 3696 of file KismetMathLibrary.h.
Max [6/9]
FVector2D UKismetMathLibrary::Max private
Definition at line 3794 of file KismetMathLibrary.h.
Max [7/9]
int32 int32 UKismetMathLibrary::Max private
Definition at line 4173 of file KismetMathLibrary.h.
Max [8/9]
float float UKismetMathLibrary::Max private
Definition at line 4191 of file KismetMathLibrary.h.
Max [9/9]
float UKismetMathLibrary::Max private
Definition at line 4194 of file KismetMathLibrary.h.
MaxDistance [1/3]
float float UKismetMathLibrary::MaxDistance private
Definition at line 4508 of file KismetMathLibrary.h.
MaxDistance [2/3]
FVector float UKismetMathLibrary::MaxDistance private
Definition at line 4524 of file KismetMathLibrary.h.
MaxDistance [3/3]
FRotator float UKismetMathLibrary::MaxDistance private
Definition at line 4540 of file KismetMathLibrary.h.
MaxPitchInDegrees [1/2]
float float UKismetMathLibrary::MaxPitchInDegrees private
Initial value:
{
        return RandomUnitVectorInEllipticalConeInRadians(ConeDir, FMath::DegreesToRadians(MaxYawInDegrees), FMath::DegreesToRadians(MaxPitchInDegrees))
Definition at line 2034 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED().
MaxPitchInDegrees [2/2]
const FVector float float UKismetMathLibrary::MaxPitchInDegrees private
Initial value:
{
        return RandomUnitVectorInEllipticalConeInRadiansFromStream(Stream, ConeDir, FMath::DegreesToRadians(MaxYawInDegrees), FMath::DegreesToRadians(MaxPitchInDegrees))
Definition at line 4304 of file KismetMathLibrary.h.
MaxPitchInRadians [1/2]
float float UKismetMathLibrary::MaxPitchInRadians private
Definition at line 2024 of file KismetMathLibrary.h.
MaxPitchInRadians [2/2]
const FVector float float UKismetMathLibrary::MaxPitchInRadians private
Definition at line 4287 of file KismetMathLibrary.h.
MaxValue [1/4]
int32 int32& UKismetMathLibrary::MaxValue private
Definition at line 750 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
MaxValue [2/4]
int32 float& UKismetMathLibrary::MaxValue private
Definition at line 766 of file KismetMathLibrary.h.
MaxValue [3/4]
int32 uint8& UKismetMathLibrary::MaxValue private
Definition at line 774 of file KismetMathLibrary.h.
MaxValue [4/4]
float float float float float float bool float float UKismetMathLibrary::MaxValue = 1.f private
Definition at line 4130 of file KismetMathLibrary.h.
MaxWeight [1/3]
float float float float UKismetMathLibrary::MaxWeight private
Definition at line 4508 of file KismetMathLibrary.h.
MaxWeight [2/3]
FVector float float float UKismetMathLibrary::MaxWeight private
Definition at line 4524 of file KismetMathLibrary.h.
MaxWeight [3/3]
FRotator float float float UKismetMathLibrary::MaxWeight private
Definition at line 4540 of file KismetMathLibrary.h.
MaxYawInDegrees [1/2]
float UKismetMathLibrary::MaxYawInDegrees private
Definition at line 2034 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED().
MaxYawInDegrees [2/2]
const FVector float UKismetMathLibrary::MaxYawInDegrees private
Definition at line 4304 of file KismetMathLibrary.h.
MaxYawInRadians [1/2]
float UKismetMathLibrary::MaxYawInRadians private
Definition at line 2024 of file KismetMathLibrary.h.
MaxYawInRadians [2/2]
const FVector float UKismetMathLibrary::MaxYawInRadians private
Definition at line 4287 of file KismetMathLibrary.h.
MedianValue
float& UKismetMathLibrary::MedianValue private
Definition at line 758 of file KismetMathLibrary.h.
meta
UKismetMathLibrary::meta private
Initial value:
=(ScriptMethod="RandomPointInBox", ScriptMethodMutable))
    static 1 FVector RandomPointInBoundingBoxFromStream_Box(const FRandomStream& Stream, const FBox Box)
Definition at line 4214 of file KismetMathLibrary.h.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Millisecond [1/2]
int32 int32 int32 int32 int32 int32 UKismetMathLibrary::Millisecond = 0) private
Definition at line 3242 of file KismetMathLibrary.h.
Millisecond [2/2]
int32 int32 int32 int32 int32 int32 int32& UKismetMathLibrary::Millisecond private
Definition at line 3246 of file KismetMathLibrary.h.
Milliseconds [1/2]
int32 int32 int32 int32 UKismetMathLibrary::Milliseconds private
Definition at line 3430 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Milliseconds [2/2]
int32 int32 int32 int32 int32& UKismetMathLibrary::Milliseconds private
Definition at line 3438 of file KismetMathLibrary.h.
Min [1/3]
UKismetMathLibrary::Min = "0" private
Definition at line 361 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
Min [2/3]
int32 UKismetMathLibrary::Min private
Definition at line 4173 of file KismetMathLibrary.h.
Min [3/3]
float UKismetMathLibrary::Min private
Definition at line 4191 of file KismetMathLibrary.h.
Minute [1/2]
int32 int32 int32 int32 UKismetMathLibrary::Minute = 0 private
Definition at line 3242 of file KismetMathLibrary.h.
Minute [2/2]
int32 int32 int32 int32 int32& UKismetMathLibrary::Minute private
Definition at line 3246 of file KismetMathLibrary.h.
Minutes [1/2]
int32 int32 int32 & UKismetMathLibrary::Minutes private
Definition at line 3430 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Minutes [2/2]
int32 int32 int32& UKismetMathLibrary::Minutes private
Definition at line 3438 of file KismetMathLibrary.h.
MinValue [1/4]
int32 int32& UKismetMathLibrary::MinValue private
Definition at line 754 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
MinValue [2/4]
int32 float& UKismetMathLibrary::MinValue private
Definition at line 770 of file KismetMathLibrary.h.
MinValue [3/4]
int32 uint8& UKismetMathLibrary::MinValue private
Definition at line 778 of file KismetMathLibrary.h.
MinValue [4/4]
float float float float float float bool float UKismetMathLibrary::MinValue = -1.f private
Definition at line 4130 of file KismetMathLibrary.h.
MinWeight [1/3]
float float float UKismetMathLibrary::MinWeight private
Definition at line 4508 of file KismetMathLibrary.h.
MinWeight [2/3]
FVector float float UKismetMathLibrary::MinWeight private
Definition at line 4524 of file KismetMathLibrary.h.
MinWeight [3/3]
FRotator float float UKismetMathLibrary::MinWeight private
Definition at line 4540 of file KismetMathLibrary.h.
Month [1/2]
int32 UKismetMathLibrary::Month private
Definition at line 3242 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Month [2/2]
int32 int32& UKismetMathLibrary::Month private
Definition at line 3246 of file KismetMathLibrary.h.
Negative
const FVector& UKismetMathLibrary::Negative private
Definition at line 3765 of file KismetMathLibrary.h.
NewSeed
int32 UKismetMathLibrary::NewSeed private
Definition at line 4243 of file KismetMathLibrary.h.
Normal
FVector UKismetMathLibrary::Normal private
Definition at line 3233 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Numerator
int32& UKismetMathLibrary::Numerator private
Definition at line 3574 of file KismetMathLibrary.h.
OuterTest
const FBox & UKismetMathLibrary::OuterTest private
Definition at line 3717 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
OutRangeA
double double double UKismetMathLibrary::OutRangeA private
Definition at line 838 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
OutRangeB
double double double double UKismetMathLibrary::OutRangeB private
Definition at line 838 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
OutRectCenter
const TArray<FVector> const FVector FVector& UKismetMathLibrary::OutRectCenter private
Definition at line 4343 of file KismetMathLibrary.h.
OutRectLengthX
const TArray<FVector> const FVector FVector FRotator float& UKismetMathLibrary::OutRectLengthX private
Definition at line 4344 of file KismetMathLibrary.h.
OutRectLengthY
const TArray<FVector> const FVector FVector FRotator float float& UKismetMathLibrary::OutRectLengthY private
Definition at line 4344 of file KismetMathLibrary.h.
OutRectRotation
const TArray<FVector> const FVector FVector FRotator& UKismetMathLibrary::OutRectRotation private
Definition at line 4344 of file KismetMathLibrary.h.
OutSlopePitchDegreeAngle
const FVector const FVector float& UKismetMathLibrary::OutSlopePitchDegreeAngle private
Definition at line 4434 of file KismetMathLibrary.h.
OutSlopeRollDegreeAngle
const FVector const FVector float float& UKismetMathLibrary::OutSlopeRollDegreeAngle private
Definition at line 4434 of file KismetMathLibrary.h.
ParentClass
TSubclassOf<class UObject> UKismetMathLibrary::ParentClass private
Definition at line 3908 of file KismetMathLibrary.h.
Pitch [1/2]
float UKismetMathLibrary::Pitch private
Definition at line 1290 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Pitch [2/2]
float float& UKismetMathLibrary::Pitch private
Definition at line 1579 of file KismetMathLibrary.h.
PlaneNormal
const FVector FVector FVector UKismetMathLibrary::PlaneNormal private
Definition at line 4456 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
PlaneOrigin
const FVector FVector UKismetMathLibrary::PlaneOrigin private
Definition at line 4456 of file KismetMathLibrary.h.
Point
const FVector & UKismetMathLibrary::Point private
Definition at line 3741 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Positive
const FVector const FVector& UKismetMathLibrary::Positive private
Definition at line 3765 of file KismetMathLibrary.h.
PreviousSample [1/3]
FRotator UKismetMathLibrary::PreviousSample private
Definition at line 4468 of file KismetMathLibrary.h.
PreviousSample [2/3]
FVector UKismetMathLibrary::PreviousSample private
Definition at line 4480 of file KismetMathLibrary.h.
PreviousSample [3/3]
FRotator UKismetMathLibrary::PreviousSample private
Definition at line 4492 of file KismetMathLibrary.h.
R
float& UKismetMathLibrary::R private
Definition at line 3032 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
RandomStream
const FRandomStream& UKismetMathLibrary::RandomStream private
Initial value:
{
        return RandomBoolWithWeightFromStream(RandomStream, Weight)
Definition at line 216 of file KismetMathLibrary.h.
RangeMax
double double UKismetMathLibrary::RangeMax private
Definition at line 834 of file KismetMathLibrary.h.
RangeMin
double UKismetMathLibrary::RangeMin private
Definition at line 834 of file KismetMathLibrary.h.
ReferenceFrame
const FTransform& UKismetMathLibrary::ReferenceFrame private
Definition at line 1584 of file KismetMathLibrary.h.
Result [1/2]
FDateTime & UKismetMathLibrary::Result private
Definition at line 3374 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Result [2/2]
FTimespan& UKismetMathLibrary::Result private
Definition at line 3554 of file KismetMathLibrary.h.
Right
FVector UKismetMathLibrary::Right private
Definition at line 2305 of file KismetMathLibrary.h.
Rotation
FVector FRotator& UKismetMathLibrary::Rotation private
Definition at line 3934 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
S
float UKismetMathLibrary::S private
Definition at line 3078 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
SampleSurfaceNormal
const TArray<FVector> const FVector& UKismetMathLibrary::SampleSurfaceNormal private
Definition at line 4343 of file KismetMathLibrary.h.
Scale
FVector FRotator FVector& UKismetMathLibrary::Scale private
Definition at line 3934 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
ScriptConstant
UKismetMathLibrary::ScriptConstant = "Identity" private
Definition at line 2439 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
ScriptConstantHost
UKismetMathLibrary::ScriptConstantHost private
Initial value:
= "/Script/CoreUObject.Matrix"), Category = "Math|Matrix")
    static FMatrix Matrix_Identity()
Definition at line 2439 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
ScriptMethod
UKismetMathLibrary::ScriptMethod = "Vector2D" private
Definition at line 924 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
ScriptOperator
UKismetMathLibrary::ScriptOperator = "==" private
Definition at line 960 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Second [1/2]
int32 int32 int32 int32 int32 UKismetMathLibrary::Second = 0 private
Definition at line 3242 of file KismetMathLibrary.h.
Second [2/2]
int32 int32 int32 int32 int32 int32& UKismetMathLibrary::Second private
Definition at line 3246 of file KismetMathLibrary.h.
Seconds [1/2]
int32 int32 int32 int32 & UKismetMathLibrary::Seconds private
Definition at line 3430 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Seconds [2/2]
int32 int32 int32 int32& UKismetMathLibrary::Seconds private
Definition at line 3438 of file KismetMathLibrary.h.
Segment1End
FVector UKismetMathLibrary::Segment1End private
Definition at line 1939 of file KismetMathLibrary.h.
Segment1Point
FVector FVector FVector FVector& UKismetMathLibrary::Segment1Point private
Definition at line 1939 of file KismetMathLibrary.h.
Segment2End
FVector FVector FVector UKismetMathLibrary::Segment2End private
Definition at line 1939 of file KismetMathLibrary.h.
Segment2Point
FVector FVector FVector FVector FVector& UKismetMathLibrary::Segment2Point private
Definition at line 1939 of file KismetMathLibrary.h.
Segment2Start
FVector FVector UKismetMathLibrary::Segment2Start private
Definition at line 1939 of file KismetMathLibrary.h.
SegmentEnd
FVector FVector UKismetMathLibrary::SegmentEnd private
Definition at line 1950 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
SegmentStart
FVector UKismetMathLibrary::SegmentStart private
Definition at line 1950 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Stiffness
float float UKismetMathLibrary::Stiffness private
Definition at line 4128 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Stream [1/5]
float float const FRandomStream & UKismetMathLibrary::Stream private
Initial value:
{
        return RandomIntegerFromStream(Stream, Max)
Definition at line 4166 of file KismetMathLibrary.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Stream [2/5]
int32 const FRandomStream& UKismetMathLibrary::Stream private
Initial value:
{
        return RandomIntegerInRangeFromStream(Stream, Min, Max)
Definition at line 4176 of file KismetMathLibrary.h.
Stream [3/5]
float const FRandomStream& UKismetMathLibrary::Stream private
Initial value:
{
        return RandomFloatInRangeFromStream(Stream, Min, Max)
Definition at line 4194 of file KismetMathLibrary.h.
Stream [4/5]
const FVector const FRandomStream& UKismetMathLibrary::Stream private
Initial value:
{
        return RandomPointInBoundingBoxFromStream(Stream, Center, HalfSize)
Definition at line 4208 of file KismetMathLibrary.h.
Stream [5/5]
float float const FRandomStream& UKismetMathLibrary::Stream private
Initial value:
{
        return RandomUnitVectorInEllipticalConeInRadiansFromStream(Stream, ConeDir, MaxYawInRadians, MaxPitchInRadians)
Definition at line 4290 of file KismetMathLibrary.h.
SubFrame [1/2]
FFrameRate float UKismetMathLibrary::SubFrame = 0.f) private
Definition at line 3562 of file KismetMathLibrary.h.
SubFrame [2/2]
FFrameNumber FFrameRate float& UKismetMathLibrary::SubFrame private
Definition at line 3566 of file KismetMathLibrary.h.
T [1/2]
const FVector const FPlane float& UKismetMathLibrary::T private
Definition at line 4447 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
T [2/2]
const FVector FVector FVector float& UKismetMathLibrary::T private
Definition at line 4456 of file KismetMathLibrary.h.
Target [1/6]
FRotator UKismetMathLibrary::Target private
Definition at line 1168 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Target [2/6]
FVector UKismetMathLibrary::Target private
Definition at line 1758 of file KismetMathLibrary.h.
Target [3/6]
const FVector& UKismetMathLibrary::Target private
Definition at line 2309 of file KismetMathLibrary.h.
Target [4/6]
double UKismetMathLibrary::Target private
Definition at line 4072 of file KismetMathLibrary.h.
Target [5/6]
FRotator UKismetMathLibrary::Target private
Definition at line 4096 of file KismetMathLibrary.h.
Target [6/6]
float UKismetMathLibrary::Target private
Definition at line 4127 of file KismetMathLibrary.h.
TargetLocation
const FVector& UKismetMathLibrary::TargetLocation private
Definition at line 2316 of file KismetMathLibrary.h.
TargetVelocityAmount
float float float float float float UKismetMathLibrary::TargetVelocityAmount = 1.f private
Definition at line 4129 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Tolerance
float UKismetMathLibrary::Tolerance = 0.1f) private
Definition at line 4355 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Up
FVector FVector UKismetMathLibrary::Up private
Definition at line 2305 of file KismetMathLibrary.h.
UpVector
const FVector const FVector& UKismetMathLibrary::UpVector private
Definition at line 4434 of file KismetMathLibrary.h.
V
float float UKismetMathLibrary::V private
Definition at line 3078 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Velocity [1/2]
float UKismetMathLibrary::Velocity private
Definition at line 4147 of file KismetMathLibrary.h.
Velocity [2/2]
FVector UKismetMathLibrary::Velocity private
Definition at line 4151 of file KismetMathLibrary.h.
W [1/2]
float float float UKismetMathLibrary::W private
Definition at line 2763 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
W [2/2]
float float float float& UKismetMathLibrary::W private
Definition at line 2767 of file KismetMathLibrary.h.
Weight [1/4]
float UKismetMathLibrary::Weight private
Definition at line 213 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Weight [2/4]
float float UKismetMathLibrary::Weight private
Definition at line 4468 of file KismetMathLibrary.h.
Weight [3/4]
FVector float UKismetMathLibrary::Weight private
Definition at line 4480 of file KismetMathLibrary.h.
Weight [4/4]
FRotator float UKismetMathLibrary::Weight private
Definition at line 4492 of file KismetMathLibrary.h.
X [1/4]
double & UKismetMathLibrary::X private
Definition at line 994 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
X [2/4]
float& UKismetMathLibrary::X private
Definition at line 1315 of file KismetMathLibrary.h.
X [3/4]
const FVector& UKismetMathLibrary::X private
Definition at line 2289 of file KismetMathLibrary.h.
X [4/4]
FVector& UKismetMathLibrary::X private
Definition at line 2328 of file KismetMathLibrary.h.
XSize
int32 UKismetMathLibrary::XSize private
Definition at line 4556 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Y [1/6]
double double & UKismetMathLibrary::Y private
Definition at line 990 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Y [2/6]
double double& UKismetMathLibrary::Y private
Definition at line 994 of file KismetMathLibrary.h.
Y [3/6]
float float& UKismetMathLibrary::Y private
Definition at line 1315 of file KismetMathLibrary.h.
Y [4/6]
const FVector& UKismetMathLibrary::Y private
Definition at line 2281 of file KismetMathLibrary.h.
Y [5/6]
FVector FVector& UKismetMathLibrary::Y private
Definition at line 2328 of file KismetMathLibrary.h.
Y [6/6]
float UKismetMathLibrary::Y private
Definition at line 2763 of file KismetMathLibrary.h.
Yaw
float& UKismetMathLibrary::Yaw private
Definition at line 1579 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Year
int32& UKismetMathLibrary::Year private
Definition at line 3246 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
YSize
int32 int32 UKismetMathLibrary::YSize private
Definition at line 4569 of file KismetMathLibrary.h.
Referenced by UFUNCTION().
Z [1/6]
double double double & UKismetMathLibrary::Z { return FVector_NetQuantize(X, Y, Z) private
Definition at line 1286 of file KismetMathLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Z [2/6]
double double double& UKismetMathLibrary::Z { BreakVector((FVector)InVec, X, Y, Z) private
Definition at line 1312 of file KismetMathLibrary.h.
Z [3/6]
float float float& UKismetMathLibrary::Z private
Definition at line 1315 of file KismetMathLibrary.h.
Z [4/6]
const FVector& UKismetMathLibrary::Z private
Definition at line 2285 of file KismetMathLibrary.h.
Z [5/6]
FVector FVector FVector& UKismetMathLibrary::Z private
Definition at line 2328 of file KismetMathLibrary.h.
Z [6/6]
float float UKismetMathLibrary::Z private
Definition at line 2763 of file KismetMathLibrary.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/KismetMathLibrary.h