Unreal Engine 5.6 C++ API: HHitProxyType Class Reference
HHitProxyType Class Reference
The priority a hit proxy has when choosing between several hit proxies near the point the user clicked.
#include "HitProxies.h"
Public Member Functions
HHitProxyType (HHitProxyType *InParent, const TCHAR *InName)
const TCHAR * GetName () const
HHitProxyType * GetParent () const
Private Attributes
const TCHAR * Name
HHitProxyType * Parent
Detailed Description
The priority a hit proxy has when choosing between several hit proxies near the point the user clicked.
HPP_World - this is the default priority HPP_Wireframe - the priority of items that are drawn in wireframe, such as volumes HPP_UI - the priority of the UI components such as the translation widget Represents a hit proxy class for runtime type checks.
Definition at line 37 of file HitProxies.h.
Constructor & Destructor Documentation
HHitProxyType()
HHitProxyType::HHitProxyType (HHitProxyType * InParent, const TCHAR * InName) inline
Definition at line 40 of file HitProxies.h.
References HHitProxyType(), InName, Name, and Parent.
Referenced by HHitProxyType(), and GetParent().
Member Function Documentation
GetName()
const TCHAR * HHitProxyType::GetName () const inline
Definition at line 45 of file HitProxies.h.
References Name.
GetParent()
HHitProxyType * HHitProxyType::GetParent () const inline
Definition at line 44 of file HitProxies.h.
References HHitProxyType(), and Parent.
Field Documentation
Name
const TCHAR* HHitProxyType::Name private
Definition at line 48 of file HitProxies.h.
Referenced by HHitProxyType(), and GetName().
Parent
HHitProxyType* HHitProxyType::Parent private
Definition at line 47 of file HitProxies.h.
Referenced by HHitProxyType(), and GetParent().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/HitProxies.h