Unreal Engine 5.6 C++ API: FObjectPostSaveContext Class Reference
FObjectPostSaveContext Class Reference
Interface used by PostSave to access the save parameters.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectPostSaveContext (const FObjectPostSaveContext &Other)
FObjectPostSaveContext (FObjectSaveContextData &InData)
UE::Cook::ECookingDLC GetCookingDLC () const
UE::Cook::ECookType GetCookType () const
uint32 GetOriginalPackageFlags () const
Package->GetPackageFlags before the save, or 0 if no package.
EObjectSaveContextPhase GetPhase () const
Return which phase of SavePackage callbacks are active.
uint32 GetSaveFlags () const
Return the save flags (ESaveFlags) of the save.
const TCHAR * GetTargetFilename () const
The target Filename being saved into (not the temporary file for saving).
const ITargetPlatform * GetTargetPlatform () const
Return the targetplatform of the save, if cooking.
bool IsCookByTheBook () const
bool IsCooking () const
Report whether this is a save into a target-specific cooked format.
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
bool IsLastConcurrentSave () const
Always true normally.
bool IsProceduralSave () const
Return whether the package is being saved due to a procedural save.
bool IsUpdatingLoadedPath () const
Return whether LoadedPath of the package being saved is being updated.
bool SaveSucceeded () const
Return whether the Save was successful.
Protected Attributes
FObjectSaveContextData & Data
Friends
class UObject
Detailed Description
Interface used by PostSave to access the save parameters.
Definition at line 448 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectPostSaveContext() [1/2]
FObjectPostSaveContext::FObjectPostSaveContext (FObjectSaveContextData & InData) inline explicit
Definition at line 451 of file ObjectSaveContext.h.
References Data.
Referenced by FObjectPostSaveContext(), FObjectPostSaveRootContext::FObjectPostSaveRootContext(), and FObjectPostSaveRootContext::FObjectPostSaveRootContext().
FObjectPostSaveContext() [2/2]
FObjectPostSaveContext::FObjectPostSaveContext (const FObjectPostSaveContext & Other) inline
Definition at line 457 of file ObjectSaveContext.h.
References FObjectPostSaveContext(), Data, and Other.
Member Function Documentation
GetCookingDLC()
UE::Cook::ECookingDLC FObjectPostSaveContext::GetCookingDLC () const inline
Definition at line 480 of file ObjectSaveContext.h.
References Data.
GetCookType()
UE::Cook::ECookType FObjectPostSaveContext::GetCookType () const inline
Definition at line 479 of file ObjectSaveContext.h.
References Data.
Referenced by IsCookByTheBook(), IsCookOnTheFly(), and IsCookTypeUnknown().
GetOriginalPackageFlags()
uint32 FObjectPostSaveContext::GetOriginalPackageFlags () const inline
Package->GetPackageFlags before the save, or 0 if no package.
Definition at line 499 of file ObjectSaveContext.h.
References Data.
GetPhase()
EObjectSaveContextPhase FObjectPostSaveContext::GetPhase () const inline
Return which phase of SavePackage callbacks are active.
See also
EObjectSaveContextPhase.
Definition at line 511 of file ObjectSaveContext.h.
References Data.
GetSaveFlags()
uint32 FObjectPostSaveContext::GetSaveFlags () const inline
Return the save flags (ESaveFlags) of the save.
Definition at line 496 of file ObjectSaveContext.h.
References Data.
GetTargetFilename()
const TCHAR * FObjectPostSaveContext::GetTargetFilename () const inline
The target Filename being saved into (not the temporary file for saving).
The path is in the standard UnrealEngine form - it is as a relative path from the process binary directory. Empty string if the saved bytes are not being saved to a file. Never null.
Definition at line 468 of file ObjectSaveContext.h.
References Data.
GetTargetPlatform()
const ITargetPlatform * FObjectPostSaveContext::GetTargetPlatform () const inline
Return the targetplatform of the save, if cooking.
Null if not cooking.
Definition at line 474 of file ObjectSaveContext.h.
References Data.
IsCookByTheBook()
bool FObjectPostSaveContext::IsCookByTheBook () const inline
Definition at line 476 of file ObjectSaveContext.h.
References UE::Cook::ByTheBook, and GetCookType().
IsCooking()
bool FObjectPostSaveContext::IsCooking () const inline
Report whether this is a save into a target-specific cooked format.
Definition at line 471 of file ObjectSaveContext.h.
References Data.
IsCookOnTheFly()
bool FObjectPostSaveContext::IsCookOnTheFly () const inline
Definition at line 477 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::OnTheFly.
IsCookTypeUnknown()
bool FObjectPostSaveContext::IsCookTypeUnknown () const inline
Definition at line 478 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::Unknown.
IsLastConcurrentSave()
bool FObjectPostSaveContext::IsLastConcurrentSave () const inline
Always true normally.
When a system is executing multiple PreSaves and PostSaves concurrently before a single save, PostSaves are executed in reverse order of the PreSaves, and this function returns false for all but the last one.
Definition at line 508 of file ObjectSaveContext.h.
References Data.
IsProceduralSave()
bool FObjectPostSaveContext::IsProceduralSave () const inline
Return whether the package is being saved due to a procedural save.
Any save without the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
Definition at line 487 of file ObjectSaveContext.h.
References Data.
IsUpdatingLoadedPath()
bool FObjectPostSaveContext::IsUpdatingLoadedPath () const inline
Return whether LoadedPath of the package being saved is being updated.
This allows us to update the in-memory package when it is saved in editor to match its new save file.
Definition at line 493 of file ObjectSaveContext.h.
References Data.
SaveSucceeded()
bool FObjectPostSaveContext::SaveSucceeded () const inline
Return whether the Save was successful.
Note that some PostSave operations are only called when this is true.
Definition at line 502 of file ObjectSaveContext.h.
References Data.
Friends And Related Symbol Documentation
UObject
friend class UObject friend
Definition at line 515 of file ObjectSaveContext.h.
References UObject.
Referenced by UObject.
Field Documentation
Data
FObjectSaveContextData& FObjectPostSaveContext::Data protected
Definition at line 514 of file ObjectSaveContext.h.
Referenced by FObjectPostSaveContext(), FObjectPostSaveContext(), FObjectPostSaveRootContext::FObjectPostSaveRootContext(), GetCookingDLC(), GetCookType(), GetOriginalPackageFlags(), GetPhase(), GetSaveFlags(), GetTargetFilename(), GetTargetPlatform(), FObjectPostSaveRootContext::IsCleanupRequired(), IsCooking(), IsLastConcurrentSave(), IsProceduralSave(), IsUpdatingLoadedPath(), and SaveSucceeded().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ObjectSaveContext.h