Unreal Engine 5.6 C++ API: USphereComponent Class Reference
USphereComponent Class Reference
#include "SphereComponent.h"
Public Member Functions
virtual bool AreSymmetricRotations (const FQuat &A, const FQuat &B, const FVector &Scale3D) const override
virtual void CalcBoundingCylinder (float &CylinderRadius, float &CylinderHalfHeight) const override
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual struct FCollisionShape GetCollisionShape (float Inflation=0.0f) const override
FORCEINLINE void InitSphereRadius (float InSphereRadius)
virtual bool IsZeroExtent () const override
UFUNCTION () 1 void SetSphereRadius(float InSphereRadius
The radius of the sphere.
UFUNCTION () float GetScaledSphereRadius() const
UFUNCTION () float GetShapeScale() const
UFUNCTION () float GetUnscaledSphereRadius() const
virtual void UpdateBodySetup () override
Update the body setup parameters based on shape information.
Public Member Functions inherited from UShapeComponent
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual class UBodySetup * GetBodySetup () override
TSubclassOf< class UNavAreaBase > GetDesiredAreaClass () const
virtual bool GetIgnoreBoundsForEditorFocus () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
virtual bool IsNavigationRelevant () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void Serialize (FArchive &Ar) override
void SetAreaClassOverride (TSubclassOf< class UNavAreaBase > InAreaClassOverride)
void SetUseSystemDefaultObstacleAreaClass ()
virtual bool ShouldCollideWhenPlacing () const override
UFUNCTION () 1 void SetLineThickness(float Thickness)
Data Fields
bool bUpdateOverlaps =true)
Additional Inherited Members
Protected Member Functions inherited from UShapeComponent
template<typename ShapeElemType>
void AddShapeToGeomArray ()
template<typename ShapeElemType>
void CreateShapeBodySetupIfNeeded ()
template<typename ComponentType>
bool PrepareSharedBodySetup ()
Checks if a shared body setup is available (and if we're eligible for it).
template<typename ShapeElemType>
void SetShapeToNewGeom (const FPhysicsShapeHandle &Shape)
UPROPERTY () float LineThickness
Used to control the line thickness when rendering.
UPROPERTY ()) TSubclassOf< class UNavAreaBase > AreaClassOverride
Navigation area type override, null / none = no change to nav mesh.
Protected Attributes inherited from UShapeComponent
UPROPERTY()) uint8 bUseSystemDefaultObstacleAreaClass uint8 bUseArchetypeBodySetup: 1
Only show this component if the actor is selected.
Detailed Description
Definition at line 17 of file SphereComponent.h.
Member Function Documentation
AreSymmetricRotations()
virtual bool USphereComponent::AreSymmetricRotations (const FQuat & A, const FQuat & B, const FVector & Scale3D) const override virtual
References A, AreSymmetricRotations(), B, and FVector.
Referenced by AreSymmetricRotations().
CalcBoundingCylinder()
virtual void USphereComponent::CalcBoundingCylinder (float & CylinderRadius, float & CylinderHalfHeight) const override virtual
References CalcBoundingCylinder().
Referenced by CalcBoundingCylinder().
CalcBounds()
virtual FBoxSphereBounds USphereComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
Reimplemented from UShapeComponent.
References CalcBounds().
Referenced by CalcBounds().
CreateSceneProxy()
virtual FPrimitiveSceneProxy * USphereComponent::CreateSceneProxy () override virtual
Reimplemented from UShapeComponent.
References CreateSceneProxy().
Referenced by CreateSceneProxy().
GetCollisionShape()
virtual struct FCollisionShape USphereComponent::GetCollisionShape (float Inflation = 0.0f) const override virtual
References GetCollisionShape().
Referenced by GetCollisionShape().
InitSphereRadius()
FORCEINLINE void USphereComponent::InitSphereRadius (float InSphereRadius) inline
Definition at line 65 of file SphereComponent.h.
References FORCEINLINE, and InitSphereRadius().
Referenced by InitSphereRadius().
IsZeroExtent()
virtual bool USphereComponent::IsZeroExtent () const override virtual
References IsZeroExtent().
Referenced by IsZeroExtent().
UFUNCTION() [1/4]
USphereComponent::UFUNCTION ()
The radius of the sphere.
Change the sphere radius. This is the unscaled radius, before component scale is applied.
Parameters
InSphereRadius the new sphere radius
bUpdateOverlaps if true and this shape is registered and collides, updates touching array for owner actor.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/4]
USphereComponent::UFUNCTION () const
References Category, and UFUNCTION().
UFUNCTION() [3/4]
USphereComponent::UFUNCTION () const
References Category, and UFUNCTION().
UFUNCTION() [4/4]
USphereComponent::UFUNCTION () const
References Category, and UFUNCTION().
UpdateBodySetup()
virtual void USphereComponent::UpdateBodySetup () override virtual
Update the body setup parameters based on shape information.
Reimplemented from UShapeComponent.
References UpdateBodySetup().
Referenced by UpdateBodySetup().
Field Documentation
bUpdateOverlaps
bool USphereComponent::bUpdateOverlaps =true)
Definition at line 33 of file SphereComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/SphereComponent.h