Unreal Engine 5.6 C++ API: UE::Insights::FFilterWithSuggestions Class Reference
UE::Insights::FFilterWithSuggestions Class Reference
#include "Filters.h"
Public Types
typedef TFunction< void(const FString &, TArray< FString > &OutSuggestions)> FGetSuggestionsCallback
Public Member Functions
FFilterWithSuggestions (int32 InKey, FText InName, FText InDesc, EFilterDataType InDataType, TSharedPtr< IFilterValueConverter > InConverter, SupportedOperatorsArrayPtr InSupportedOperators)
virtual ~FFilterWithSuggestions ()
const FGetSuggestionsCallback & GetCallback () const
void GetSuggestions (const FString &Text, TArray< FString > &OutSuggestions)
virtual const FName & GetTypeName () const override
virtual bool IsKindOf (const FName &InTypeName) const override
void SetCallback (FGetSuggestionsCallback InCallback)
Public Member Functions inherited from UE::Insights::FFilter
FFilter (int32 InKey, FText InName, FText InDesc, EFilterDataType InDataType, TSharedPtr< IFilterValueConverter > InConverter, SupportedOperatorsArrayPtr InSupportedOperators)
virtual ~FFilter ()
template<typename Type>
Type & As ()
template<typename Type>
const Type & As () const
virtual TSharedRef< FFilterState > BuildFilterState ()
virtual TSharedRef< FFilterState > BuildFilterState (const FFilterState &Other)
const TSharedPtr< IFilterValueConverter > & GetConverter () const
EFilterDataType GetDataType () const
const FText & GetDesc () const
int32 GetKey () const
const FText & GetName () const
SupportedOperatorsArrayConstPtr GetSupportedOperators () const
template<typename Type>
bool Is () const
Public Member Functions inherited from TSharedFromThis< FFilter >
TSharedRef< FFilter, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FFilter, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static const FName & GetStaticTypeName ()
Static Public Member Functions inherited from UE::Insights::FFilter
static const FName & GetStaticTypeName ()
Private Attributes
FGetSuggestionsCallback Callback
Static Private Attributes
static const FName TypeName
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FFilter >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FFilter >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Insights::FFilter
TSharedPtr< IFilterValueConverter > Converter
EFilterDataType DataType
FText Desc
int32 Key
FText Name
SupportedOperatorsArrayPtr SupportedOperators
Detailed Description
Definition at line 284 of file Filters.h.
Member Typedef Documentation
FGetSuggestionsCallback
typedef TFunction<void(const FString& , TArray<FString>& OutSuggestions)> UE::Insights::FFilterWithSuggestions::FGetSuggestionsCallback
Definition at line 289 of file Filters.h.
Constructor & Destructor Documentation
FFilterWithSuggestions()
UE::Insights::FFilterWithSuggestions::FFilterWithSuggestions (int32 InKey, FText InName, FText InDesc, EFilterDataType InDataType, TSharedPtr< IFilterValueConverter > InConverter, SupportedOperatorsArrayPtr InSupportedOperators) inline
Definition at line 292 of file Filters.h.
References UE::Insights::FFilter::FFilter(), InName, and TSharedPtr< ObjectType, InMode >::IsValid().
Referenced by GetStaticTypeName().
~FFilterWithSuggestions()
virtual UE::Insights::FFilterWithSuggestions::~FFilterWithSuggestions () inline virtual
Definition at line 302 of file Filters.h.
Member Function Documentation
GetCallback()
const FGetSuggestionsCallback & UE::Insights::FFilterWithSuggestions::GetCallback () const inline
Definition at line 306 of file Filters.h.
References Callback.
GetStaticTypeName()
const FName & UE::Insights::FFilterWithSuggestions::GetStaticTypeName () inline static
Definition at line 286 of file Filters.h.
References UE::Insights::FFilter::FFilter(), and FFilterWithSuggestions().
GetSuggestions()
void UE::Insights::FFilterWithSuggestions::GetSuggestions (const FString & Text, TArray< FString > & OutSuggestions) inline
Definition at line 308 of file Filters.h.
References Callback, and UE::Insights::Text.
GetTypeName()
virtual const FName & UE::Insights::FFilterWithSuggestions::GetTypeName () const inline override virtual
Reimplemented from UE::Insights::FFilter.
Definition at line 286 of file Filters.h.
IsKindOf()
virtual bool UE::Insights::FFilterWithSuggestions::IsKindOf (const FName & InTypeName) const inline override virtual
Reimplemented from UE::Insights::FFilter.
Definition at line 286 of file Filters.h.
SetCallback()
void UE::Insights::FFilterWithSuggestions::SetCallback (FGetSuggestionsCallback InCallback) inline
Definition at line 307 of file Filters.h.
References Callback.
Field Documentation
Callback
FGetSuggestionsCallback UE::Insights::FFilterWithSuggestions::Callback private
Definition at line 311 of file Filters.h.
Referenced by GetCallback(), GetSuggestions(), and SetCallback().
TypeName
const FName UE::Insights::FFilterWithSuggestions::TypeName static private
Definition at line 286 of file Filters.h.
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Filter/ViewModels/Filters.h