Unreal Engine 5.6 C++ API: TRDGTextureAccess< InAccess > Class Template Reference
TRDGTextureAccess< InAccess > Class Template Reference
#include "ShaderParameterMacros.h"
Public Member Functions
TRDGTextureAccess ()=default
TRDGTextureAccess (FRDGTexture *InTexture)
TRDGTextureAccess (FRDGTexture *InTexture, FRDGTextureSubresourceRange InSubresourceRange)
TRDGTextureAccess (FRDGTextureSRV *InTextureSRV)
TRDGTextureAccess (FRDGTextureUAV *InTextureUAV)
Public Member Functions inherited from FRDGTextureAccess
FRDGTextureAccess ()=default
RENDERCORE_API FRDGTextureAccess (FRDGTexture *InTexture, ERHIAccess InAccess)
FRDGTextureAccess (FRDGTexture *InTexture, FRDGTextureSubresourceRange InSubresourceRange, ERHIAccess InAccess)
RENDERCORE_API FRDGTextureAccess (FRDGTextureSRV *InTextureSRV, ERHIAccess InAccess)
RENDERCORE_API FRDGTextureAccess (FRDGTextureUAV *InTextureUAV, ERHIAccess InAccess)
FORCEINLINE ERHIAccess GetAccess () const
FORCEINLINE FRDGTextureSubresourceRange GetSubresourceRange () const
FORCEINLINE FRDGTexture * GetTexture () const
FORCEINLINE operator bool () const
FORCEINLINE operator FRDGTexture * () const
FORCEINLINE bool operator!= (const FRDGTextureAccess &RHS) const
FORCEINLINE FRDGTexture * operator-> () const
FORCEINLINE bool operator== (const FRDGTextureAccess &RHS) const
Detailed Description
template<ERHIAccess InAccess>
class TRDGTextureAccess< InAccess >
Definition at line 480 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
TRDGTextureAccess() [1/5]
template<ERHIAccess InAccess> TRDGTextureAccess< InAccess >::TRDGTextureAccess () default
TRDGTextureAccess() [2/5]
template<ERHIAccess InAccess> TRDGTextureAccess< InAccess >::TRDGTextureAccess (FRDGTexture * InTexture, FRDGTextureSubresourceRange InSubresourceRange) inline
Definition at line 488 of file ShaderParameterMacros.h.
References FRDGTextureAccess::FRDGTextureAccess().
TRDGTextureAccess() [3/5]
template<ERHIAccess InAccess> TRDGTextureAccess< InAccess >::TRDGTextureAccess (FRDGTexture * InTexture) inline
Definition at line 492 of file ShaderParameterMacros.h.
References FRDGTextureAccess::FRDGTextureAccess().
TRDGTextureAccess() [4/5]
template<ERHIAccess InAccess> TRDGTextureAccess< InAccess >::TRDGTextureAccess (FRDGTextureSRV * InTextureSRV) inline
Definition at line 496 of file ShaderParameterMacros.h.
References FRDGTextureAccess::FRDGTextureAccess().
TRDGTextureAccess() [5/5]
template<ERHIAccess InAccess> TRDGTextureAccess< InAccess >::TRDGTextureAccess (FRDGTextureUAV * InTextureUAV) inline
Definition at line 500 of file ShaderParameterMacros.h.
References FRDGTextureAccess::FRDGTextureAccess().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameterMacros.h