Unreal Engine 5.6 C++ API: TScriptSparseArray< AllocatorType, InDerivedType > Class Template Reference
TScriptSparseArray< AllocatorType, InDerivedType > Class Template Reference
#include "SparseArray.h"
Data Structures
struct FFreeListLink
Public Types
using IntrusiveUnsetOptionalStateType = TScriptSparseArray
Public Member Functions
TScriptSparseArray ()
TScriptSparseArray (const TScriptSparseArray &)
TScriptSparseArray (FIntrusiveUnsetOptionalState Tag)
int32 AddUninitialized (const FScriptSparseArrayLayout &Layout)
Adds an uninitialized object to the array.
void Empty (int32 Slack, const FScriptSparseArrayLayout &Layout)
void * GetData (int32 Index, const FScriptSparseArrayLayout &Layout)
const void * GetData (int32 Index, const FScriptSparseArrayLayout &Layout) const
int32 GetMaxIndex () const
bool IsAllocated (int32 Index) const
bool IsCompact () const
bool IsEmpty () const
bool IsValidIndex (int32 Index) const
void MoveAssign (DerivedType &Other, const FScriptSparseArrayLayout &Layout)
int32 Num () const
int32 NumUnchecked () const
void operator= (const TScriptSparseArray &)
bool operator== (FIntrusiveUnsetOptionalState Tag) const
void RemoveAtUninitialized (const FScriptSparseArrayLayout &Layout, int32 Index, int32 Count=1)
Removes Count elements from the array, starting from Index, without destructing them.
Static Public Member Functions
static FScriptSparseArrayLayout GetScriptLayout (int32 ElementSize, int32 ElementAlignment)
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
using DerivedType = std::conditional_t<std::is_void_v<InDerivedType>, TScriptSparseArray, InDerivedType>
Private Member Functions
FORCEINLINE FFreeListLink * GetFreeListLink (int32 Index, const FScriptSparseArrayLayout &Layout)
Accessor for the element or free list data.
Static Private Member Functions
static void CheckConstraints ()
Private Attributes
TScriptBitArray< typename AllocatorType::BitArrayAllocator > AllocationFlags
TScriptArray< typename AllocatorType::ElementAllocator > Data
int32 FirstFreeIndex = -1
int32 NumFreeIndices = 0
Detailed Description
template<typename AllocatorType, typename InDerivedType>
class TScriptSparseArray< AllocatorType, InDerivedType >
Definition at line 1371 of file SparseArray.h.
Member Typedef Documentation
DerivedType
template<typename AllocatorType, typename InDerivedType> using TScriptSparseArray< AllocatorType, InDerivedType >::DerivedType = std::conditional_t<std::is_void_v<InDerivedType>, TScriptSparseArray, InDerivedType> private
Definition at line 1373 of file SparseArray.h.
IntrusiveUnsetOptionalStateType
template<typename AllocatorType, typename InDerivedType> using TScriptSparseArray< AllocatorType, InDerivedType >::IntrusiveUnsetOptionalStateType = TScriptSparseArray
Definition at line 1395 of file SparseArray.h.
Constructor & Destructor Documentation
TScriptSparseArray() [1/3]
template<typename AllocatorType, typename InDerivedType> TScriptSparseArray< AllocatorType, InDerivedType >::TScriptSparseArray () inline nodiscard
Definition at line 1385 of file SparseArray.h.
TScriptSparseArray() [2/3]
template<typename AllocatorType, typename InDerivedType> TScriptSparseArray< AllocatorType, InDerivedType >::TScriptSparseArray (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 1397 of file SparseArray.h.
TScriptSparseArray() [3/3]
template<typename AllocatorType, typename InDerivedType> TScriptSparseArray< AllocatorType, InDerivedType >::TScriptSparseArray (const TScriptSparseArray< AllocatorType, InDerivedType > &) inline
Definition at line 1579 of file SparseArray.h.
Member Function Documentation
AddUninitialized()
template<typename AllocatorType, typename InDerivedType> int32 TScriptSparseArray< AllocatorType, InDerivedType >::AddUninitialized (const FScriptSparseArrayLayout & Layout) inline
Adds an uninitialized object to the array.
Returns
The index of the added element.
Definition at line 1478 of file SparseArray.h.
CheckConstraints()
template<typename AllocatorType, typename InDerivedType> void TScriptSparseArray< AllocatorType, InDerivedType >::CheckConstraints () inline static private
Definition at line 1535 of file SparseArray.h.
Empty()
template<typename AllocatorType, typename InDerivedType> void TScriptSparseArray< AllocatorType, InDerivedType >::Empty (int32 Slack, const FScriptSparseArrayLayout & Layout) inline
Definition at line 1464 of file SparseArray.h.
GetData() [1/2]
template<typename AllocatorType, typename InDerivedType> void * TScriptSparseArray< AllocatorType, InDerivedType >::GetData (int32 Index, const FScriptSparseArrayLayout & Layout) inline nodiscard
Definition at line 1444 of file SparseArray.h.
Referenced by TScriptSparseArray< typename Allocator::SparseArrayAllocator >::GetFreeListLink().
GetData() [2/2]
template<typename AllocatorType, typename InDerivedType> const void * TScriptSparseArray< AllocatorType, InDerivedType >::GetData (int32 Index, const FScriptSparseArrayLayout & Layout) const inline nodiscard
Definition at line 1449 of file SparseArray.h.
GetFreeListLink()
template<typename AllocatorType, typename InDerivedType> FORCEINLINE FFreeListLink * TScriptSparseArray< AllocatorType, InDerivedType >::GetFreeListLink (int32 Index, const FScriptSparseArrayLayout & Layout) inline private
Accessor for the element or free list data.
Definition at line 1571 of file SparseArray.h.
Referenced by TScriptSparseArray< typename Allocator::SparseArrayAllocator >::AddUninitialized(), and TScriptSparseArray< typename Allocator::SparseArrayAllocator >::RemoveAtUninitialized().
GetMaxIndex()
template<typename AllocatorType, typename InDerivedType> int32 TScriptSparseArray< AllocatorType, InDerivedType >::GetMaxIndex () const inline nodiscard
Definition at line 1434 of file SparseArray.h.
GetScriptLayout()
template<typename AllocatorType, typename InDerivedType> FScriptSparseArrayLayout TScriptSparseArray< AllocatorType, InDerivedType >::GetScriptLayout (int32 ElementSize, int32 ElementAlignment) inline static nodiscard
Definition at line 1376 of file SparseArray.h.
IsAllocated()
template<typename AllocatorType, typename InDerivedType> bool TScriptSparseArray< AllocatorType, InDerivedType >::IsAllocated (int32 Index) const inline nodiscard
Definition at line 1414 of file SparseArray.h.
IsCompact()
template<typename AllocatorType, typename InDerivedType> bool TScriptSparseArray< AllocatorType, InDerivedType >::IsCompact () const inline nodiscard
Definition at line 1439 of file SparseArray.h.
IsEmpty()
template<typename AllocatorType, typename InDerivedType> bool TScriptSparseArray< AllocatorType, InDerivedType >::IsEmpty () const inline nodiscard
Definition at line 1419 of file SparseArray.h.
IsValidIndex()
template<typename AllocatorType, typename InDerivedType> bool TScriptSparseArray< AllocatorType, InDerivedType >::IsValidIndex (int32 Index) const inline nodiscard
Definition at line 1409 of file SparseArray.h.
MoveAssign()
template<typename AllocatorType, typename InDerivedType> void TScriptSparseArray< AllocatorType, InDerivedType >::MoveAssign (DerivedType & Other, const FScriptSparseArrayLayout & Layout) inline
Definition at line 1454 of file SparseArray.h.
Num()
template<typename AllocatorType, typename InDerivedType> int32 TScriptSparseArray< AllocatorType, InDerivedType >::Num () const inline nodiscard
Definition at line 1424 of file SparseArray.h.
NumUnchecked()
template<typename AllocatorType, typename InDerivedType> int32 TScriptSparseArray< AllocatorType, InDerivedType >::NumUnchecked () const inline nodiscard
Definition at line 1429 of file SparseArray.h.
operator=()
template<typename AllocatorType, typename InDerivedType> void TScriptSparseArray< AllocatorType, InDerivedType >::operator= (const TScriptSparseArray< AllocatorType, InDerivedType > &) inline
Definition at line 1580 of file SparseArray.h.
operator==()
template<typename AllocatorType, typename InDerivedType> bool TScriptSparseArray< AllocatorType, InDerivedType >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 1401 of file SparseArray.h.
RemoveAtUninitialized()
template<typename AllocatorType, typename InDerivedType> void TScriptSparseArray< AllocatorType, InDerivedType >::RemoveAtUninitialized (const FScriptSparseArrayLayout & Layout, int32 Index, int32 Count = 1) inline
Removes Count elements from the array, starting from Index, without destructing them.
Definition at line 1505 of file SparseArray.h.
Field Documentation
AllocationFlags
template<typename AllocatorType, typename InDerivedType> TScriptBitArray<typename AllocatorType::BitArrayAllocator> TScriptSparseArray< AllocatorType, InDerivedType >::AllocationFlags private
Definition at line 1530 of file SparseArray.h.
bHasIntrusiveUnsetOptionalState
template<typename AllocatorType, typename InDerivedType> bool TScriptSparseArray< AllocatorType, InDerivedType >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 1394 of file SparseArray.h.
Data
template<typename AllocatorType, typename InDerivedType> TScriptArray<typename AllocatorType::ElementAllocator> TScriptSparseArray< AllocatorType, InDerivedType >::Data private
Definition at line 1529 of file SparseArray.h.
FirstFreeIndex
template<typename AllocatorType, typename InDerivedType> int32 TScriptSparseArray< AllocatorType, InDerivedType >::FirstFreeIndex = -1 private
Definition at line 1531 of file SparseArray.h.
NumFreeIndices
template<typename AllocatorType, typename InDerivedType> int32 TScriptSparseArray< AllocatorType, InDerivedType >::NumFreeIndices = 0 private
Definition at line 1532 of file SparseArray.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SparseArray.h