Unreal Engine 5.6 C++ API: FIoHashBuilder Class Reference
FIoHashBuilder Class Reference
Calculates a BLAKE3-160 hash.
#include "IoHash.h"
Public Member Functions
FIoHash Finalize () const
Finalize the hash of the input data.
Public Member Functions inherited from FBlake3
FBlake3 ()
FBlake3 (const FBlake3 &)=delete
FBlake3Hash Finalize () const
Finalize the hash of the input data.
FBlake3 & operator= (const FBlake3 &)=delete
void Reset ()
Reset to the default state in which no input has been written.
void Update (const FCompositeBuffer &Buffer)
void Update (const void *Data, uint64 Size)
void Update (FMemoryView View)
Add the buffer as input to the hash.
Static Public Member Functions
static FIoHash HashBuffer (const FCompositeBuffer &Buffer)
static FIoHash HashBuffer (const void *Data, uint64 Size)
static FIoHash HashBuffer (FMemoryView View)
Calculate the hash of the buffer.
Static Public Member Functions inherited from FBlake3
static FBlake3Hash HashBuffer (const FCompositeBuffer &Buffer)
static FBlake3Hash HashBuffer (const void *Data, uint64 Size)
static FBlake3Hash HashBuffer (FMemoryView View)
Calculate the hash of the buffer.
Detailed Description
Calculates a BLAKE3-160 hash.
Definition at line 190 of file IoHash.h.
Member Function Documentation
Finalize()
FIoHash FIoHashBuilder::Finalize () const inline nodiscard
Finalize the hash of the input data.
May be called any number of times, and more input may be added after.
Definition at line 198 of file IoHash.h.
References FBlake3::Finalize().
HashBuffer() [1/3]
FIoHash FIoHashBuilder::HashBuffer (const FCompositeBuffer & Buffer) inline static nodiscard
Definition at line 203 of file IoHash.h.
References Buffer, and FBlake3::HashBuffer().
HashBuffer() [2/3]
FIoHash FIoHashBuilder::HashBuffer (const void * Data, uint64 Size) inline static nodiscard
Definition at line 202 of file IoHash.h.
References FBlake3::HashBuffer(), and TSequenceHistory< HistorySize >::Size.
HashBuffer() [3/3]
FIoHash FIoHashBuilder::HashBuffer (FMemoryView View) inline static nodiscard
Calculate the hash of the buffer.
Definition at line 201 of file IoHash.h.
References FBlake3::HashBuffer().
The documentation for this class was generated from the following file:
Runtime/Core/Public/IO/IoHash.h