Unreal Engine 5.6 C++ API: TScriptSet< Allocator, InDerivedType > Class Template Reference
TScriptSet< Allocator, InDerivedType > Class Template Reference
#include "Set.h"
Public Types
using IntrusiveUnsetOptionalStateType = TScriptSet
Public Member Functions
TScriptSet ()
TScriptSet (const TScriptSet &)
TScriptSet (FIntrusiveUnsetOptionalState Tag)
void Add (const void *Element, const FScriptSetLayout &Layout, TFunctionRef< uint32(const void *)> GetKeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn, TFunctionRef< void(void *)> ConstructFn, TFunctionRef< void(void *)> DestructFn)
int32 AddUninitialized (const FScriptSetLayout &Layout)
Adds an uninitialized object to the set.
void Empty (int32 Slack, const FScriptSetLayout &Layout)
int32 FindIndex (const void *Element, const FScriptSetLayout &Layout, TFunctionRef< uint32(const void *)> GetKeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn) const
int32 FindIndexByHash (const void *Element, const FScriptSetLayout &Layout, uint32 KeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn) const
int32 FindOrAdd (const void *Element, const FScriptSetLayout &Layout, TFunctionRef< uint32(const void *)> GetKeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn, TFunctionRef< void(void *)> ConstructFn)
void * GetData (int32 Index, const FScriptSetLayout &Layout)
const void * GetData (int32 Index, const FScriptSetLayout &Layout) const
int32 GetMaxIndex () const
bool IsEmpty () const
bool IsValidIndex (int32 Index) const
void MoveAssign (DerivedType &Other, const FScriptSetLayout &Layout)
int32 Num () const
int32 NumUnchecked () const
void operator= (const TScriptSet &)
bool operator== (FIntrusiveUnsetOptionalState Tag) const
void Rehash (const FScriptSetLayout &Layout, TFunctionRef< uint32(const void *)> GetKeyHash)
void RemoveAt (int32 Index, const FScriptSetLayout &Layout)
Static Public Member Functions
static FScriptSetLayout GetScriptLayout (int32 ElementSize, int32 ElementAlignment)
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
using DerivedType = std::conditional_t<std::is_void_v<InDerivedType>, TScriptSet, InDerivedType>
typedef TScriptSparseArray< typename Allocator::SparseArrayAllocator > ElementArrayType
typedef Allocator::HashAllocator::template ForElementType< FSetElementId > HashType
Private Member Functions
int32 AddNewElement (const FScriptSetLayout &Layout, TFunctionRef< uint32(const void *)> GetKeyHash, uint32 KeyHash, TFunctionRef< void(void *)> ConstructFn)
int32 FindIndexImpl (const void *Element, const FScriptSetLayout &Layout, uint32 KeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn) const
FORCEINLINE FSetElementId & GetTypedHash (int32 HashIndex) const
Static Private Member Functions
static void CheckConstraints ()
static int32 & GetHashIndexRef (const void *Element, const FScriptSetLayout &Layout)
static FSetElementId & GetHashNextIdRef (const void *Element, const FScriptSetLayout &Layout)
Private Attributes
ElementArrayType Elements
HashType Hash
int32 HashSize
Detailed Description
template<typename Allocator, typename InDerivedType>
class TScriptSet< Allocator, InDerivedType >
Definition at line 1754 of file Set.h.
Member Typedef Documentation
DerivedType
template<typename Allocator, typename InDerivedType> using TScriptSet< Allocator, InDerivedType >::DerivedType = std::conditional_t<std::is_void_v<InDerivedType>, TScriptSet, InDerivedType> private
Definition at line 1756 of file Set.h.
ElementArrayType
template<typename Allocator, typename InDerivedType> typedef TScriptSparseArray<typename Allocator::SparseArrayAllocator> TScriptSet< Allocator, InDerivedType >::ElementArrayType private
Definition at line 2049 of file Set.h.
HashType
template<typename Allocator, typename InDerivedType> typedef Allocator::HashAllocator::template ForElementType<FSetElementId> TScriptSet< Allocator, InDerivedType >::HashType private
Definition at line 2050 of file Set.h.
IntrusiveUnsetOptionalStateType
template<typename Allocator, typename InDerivedType> using TScriptSet< Allocator, InDerivedType >::IntrusiveUnsetOptionalStateType = TScriptSet
Definition at line 1785 of file Set.h.
Constructor & Destructor Documentation
TScriptSet() [1/3]
template<typename Allocator, typename InDerivedType> TScriptSet< Allocator, InDerivedType >::TScriptSet () inline nodiscard
Definition at line 1776 of file Set.h.
TScriptSet() [2/3]
template<typename Allocator, typename InDerivedType> TScriptSet< Allocator, InDerivedType >::TScriptSet (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 1787 of file Set.h.
TScriptSet() [3/3]
template<typename Allocator, typename InDerivedType> TScriptSet< Allocator, InDerivedType >::TScriptSet (const TScriptSet< Allocator, InDerivedType > &) inline
Definition at line 2095 of file Set.h.
Member Function Documentation
Add()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::Add (const void * Element, const FScriptSetLayout & Layout, TFunctionRef< uint32(const void *)> GetKeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn, TFunctionRef< void(void *)> ConstructFn, TFunctionRef< void(void *)> DestructFn) inline
Definition at line 1998 of file Set.h.
AddNewElement()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::AddNewElement (const FScriptSetLayout & Layout, TFunctionRef< uint32(const void *)> GetKeyHash, uint32 KeyHash, TFunctionRef< void(void *)> ConstructFn) inline private
Definition at line 2023 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::Add(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::FindOrAdd().
AddUninitialized()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::AddUninitialized (const FScriptSetLayout & Layout) inline
Adds an uninitialized object to the set.
The set will need rehashing at some point after this call to make it valid.
Returns
The index of the added element.
Definition at line 1893 of file Set.h.
CheckConstraints()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::CheckConstraints () inline static private
Definition at line 2072 of file Set.h.
Empty()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::Empty (int32 Slack, const FScriptSetLayout & Layout) inline
Definition at line 1843 of file Set.h.
FindIndex()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::FindIndex (const void * Element, const FScriptSetLayout & Layout, TFunctionRef< uint32(const void *)> GetKeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn) const inline nodiscard
Definition at line 1965 of file Set.h.
FindIndexByHash()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::FindIndexByHash (const void * Element, const FScriptSetLayout & Layout, uint32 KeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn) const inline nodiscard
Definition at line 1976 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::Add(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::FindOrAdd().
FindIndexImpl()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::FindIndexImpl (const void * Element, const FScriptSetLayout & Layout, uint32 KeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn) const inline nodiscard private
Definition at line 1944 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::FindIndex(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::FindIndexByHash().
FindOrAdd()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::FindOrAdd (const void * Element, const FScriptSetLayout & Layout, TFunctionRef< uint32(const void *)> GetKeyHash, TFunctionRef< bool(const void *, const void *)> EqualityFn, TFunctionRef< void(void *)> ConstructFn) inline
Definition at line 1986 of file Set.h.
GetData() [1/2]
template<typename Allocator, typename InDerivedType> void * TScriptSet< Allocator, InDerivedType >::GetData (int32 Index, const FScriptSetLayout & Layout) inline nodiscard
Definition at line 1824 of file Set.h.
GetData() [2/2]
template<typename Allocator, typename InDerivedType> const void * TScriptSet< Allocator, InDerivedType >::GetData (int32 Index, const FScriptSetLayout & Layout) const inline nodiscard
Definition at line 1829 of file Set.h.
GetHashIndexRef()
template<typename Allocator, typename InDerivedType> int32 & TScriptSet< Allocator, InDerivedType >::GetHashIndexRef (const void * Element, const FScriptSetLayout & Layout) inline static nodiscard private
Definition at line 2066 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::AddNewElement(), TScriptSet< FDefaultSetAllocator, FScriptSet >::Rehash(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::RemoveAt().
GetHashNextIdRef()
template<typename Allocator, typename InDerivedType> FSetElementId & TScriptSet< Allocator, InDerivedType >::GetHashNextIdRef (const void * Element, const FScriptSetLayout & Layout) inline static nodiscard private
Definition at line 2061 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::AddNewElement(), TScriptSet< FDefaultSetAllocator, FScriptSet >::FindIndexImpl(), TScriptSet< FDefaultSetAllocator, FScriptSet >::Rehash(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::RemoveAt().
GetMaxIndex()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::GetMaxIndex () const inline nodiscard
Definition at line 1819 of file Set.h.
GetScriptLayout()
template<typename Allocator, typename InDerivedType> FScriptSetLayout TScriptSet< Allocator, InDerivedType >::GetScriptLayout (int32 ElementSize, int32 ElementAlignment) inline static nodiscard
Definition at line 1759 of file Set.h.
GetTypedHash()
template<typename Allocator, typename InDerivedType> FORCEINLINE FSetElementId & TScriptSet< Allocator, InDerivedType >::GetTypedHash (int32 HashIndex) const inline nodiscard private
Definition at line 2056 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::AddNewElement(), TScriptSet< FDefaultSetAllocator, FScriptSet >::FindIndexImpl(), TScriptSet< FDefaultSetAllocator, FScriptSet >::Rehash(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::RemoveAt().
IsEmpty()
template<typename Allocator, typename InDerivedType> bool TScriptSet< Allocator, InDerivedType >::IsEmpty () const inline nodiscard
Definition at line 1804 of file Set.h.
IsValidIndex()
template<typename Allocator, typename InDerivedType> bool TScriptSet< Allocator, InDerivedType >::IsValidIndex (int32 Index) const inline nodiscard
Definition at line 1799 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::RemoveAt().
MoveAssign()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::MoveAssign (DerivedType & Other, const FScriptSetLayout & Layout) inline
Definition at line 1834 of file Set.h.
Num()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::Num () const inline nodiscard
Definition at line 1809 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::AddNewElement().
NumUnchecked()
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::NumUnchecked () const inline nodiscard
Definition at line 1814 of file Set.h.
operator=()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::operator= (const TScriptSet< Allocator, InDerivedType > &) inline
Definition at line 2096 of file Set.h.
operator==()
template<typename Allocator, typename InDerivedType> bool TScriptSet< Allocator, InDerivedType >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 1791 of file Set.h.
Rehash()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::Rehash (const FScriptSetLayout & Layout, TFunctionRef< uint32(const void *)> GetKeyHash) inline
Definition at line 1899 of file Set.h.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::AddNewElement().
RemoveAt()
template<typename Allocator, typename InDerivedType> void TScriptSet< Allocator, InDerivedType >::RemoveAt (int32 Index, const FScriptSetLayout & Layout) inline
Definition at line 1867 of file Set.h.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename Allocator, typename InDerivedType> bool TScriptSet< Allocator, InDerivedType >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 1784 of file Set.h.
Elements
template<typename Allocator, typename InDerivedType> ElementArrayType TScriptSet< Allocator, InDerivedType >::Elements private
Definition at line 2052 of file Set.h.
Hash
template<typename Allocator, typename InDerivedType> HashType TScriptSet< Allocator, InDerivedType >::Hash private
Definition at line 2053 of file Set.h.
HashSize
template<typename Allocator, typename InDerivedType> int32 TScriptSet< Allocator, InDerivedType >::HashSize private
Definition at line 2054 of file Set.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Set.h