Unreal Engine 5.6 C++ API: IDelegateInstance Class Reference
IDelegateInstance Class Reference abstract
#include "IDelegateInstance.h"
Public Member Functions
virtual ~IDelegateInstance ()=default
Virtual destructor.
virtual uint64 GetBoundProgramCounterForTimerManager () const =0
Returns the address of the method pointer which can be used to learn the address of the function that will be executed.
virtual FDelegateHandle GetHandle () const =0
Returns a handle for the delegate.
virtual const void * GetObjectForTimerManager () const =0
Returns a pointer to an object bound to this delegate instance, intended for quick lookup in the timer manager,.
virtual UObject * GetUObject () const =0
Returns the UObject that this delegate instance is bound to.
virtual bool HasSameObject (FDelegateUserObjectConst InUserObject) const =0
Returns true if this delegate is bound to the specified UserObject,.
virtual bool IsCompactable () const
Checks to see if the user object bound to this delegate can ever be valid again.
virtual bool IsSafeToExecute () const =0
Checks to see if the user object bound to this delegate is still valid.
Detailed Description
Definition at line 111 of file IDelegateInstance.h.
Constructor & Destructor Documentation
~IDelegateInstance()
virtual IDelegateInstance::~IDelegateInstance () virtual default
Virtual destructor.
Member Function Documentation
GetBoundProgramCounterForTimerManager()
virtual uint64 IDelegateInstance::GetBoundProgramCounterForTimerManager () const pure virtual
Returns the address of the method pointer which can be used to learn the address of the function that will be executed.
Returns nullptr if this delegate type does not directly invoke a function pointer.
Note: Only intended to be used to aid debugging of delegates.
Returns
The address of the function pointer that would be executed by this delegate
Referenced by TDelegateBase< FThreadSafetyMode >::GetBoundProgramCounterForTimerManager().
GetHandle()
virtual FDelegateHandle IDelegateInstance::GetHandle () const pure virtual
Returns a handle for the delegate.
Referenced by TDelegateBase< FThreadSafetyMode >::GetHandle(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveDelegateInstance().
GetObjectForTimerManager()
virtual const void * IDelegateInstance::GetObjectForTimerManager () const pure virtual
Returns a pointer to an object bound to this delegate instance, intended for quick lookup in the timer manager,.
Returns
A pointer to an object referenced by the delegate instance.
Referenced by TDelegateBase< FThreadSafetyMode >::GetObjectForTimerManager().
GetUObject()
virtual UObject * IDelegateInstance::GetUObject () const pure virtual
Returns the UObject that this delegate instance is bound to.
Returns
Pointer to the UObject, or nullptr if not bound to a UObject.
Referenced by TDelegateBase< FThreadSafetyMode >::GetUObject().
HasSameObject()
virtual bool IDelegateInstance::HasSameObject (FDelegateUserObjectConst InUserObject) const pure virtual
Returns true if this delegate is bound to the specified UserObject,.
Deprecated.
Parameters
InUserObject
Returns
True if delegate is bound to the specified UserObject
Referenced by TDelegateBase< FThreadSafetyMode >::IsBoundToObject(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::IsBoundToObject(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveAll().
IsCompactable()
virtual bool IDelegateInstance::IsCompactable () const inline virtual
Checks to see if the user object bound to this delegate can ever be valid again.
used to compact multicast delegate arrays so they don't expand without limit.
Returns
True if the user object can never be used again
Definition at line 174 of file IDelegateInstance.h.
References IsSafeToExecute().
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::CompactInvocationList(), TDelegateBase< FThreadSafetyMode >::IsCompactable(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveAll().
IsSafeToExecute()
virtual bool IDelegateInstance::IsSafeToExecute () const pure virtual
Checks to see if the user object bound to this delegate is still valid.
Returns
True if the user object is still valid and it's safe to execute the function call
Referenced by TDelegateBase< FThreadSafetyMode >::IsBound(), and IsCompactable().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/IDelegateInstance.h