Unreal Engine 5.6 C++ API: FTabManager::FSplitter Class Reference
FTabManager::FSplitter Class Reference
#include "TabManager.h"
Public Member Functions
virtual ~FSplitter ()
virtual TSharedPtr< FSplitter > AsSplitter () override
EOrientation GetOrientation () const
TSharedRef< FSplitter > InsertAfter (TSharedRef< FLayoutNode > NodeToInsertAfter, TSharedRef< FLayoutNode > NodeToInsert)
TSharedRef< FSplitter > InsertBefore (TSharedRef< FLayoutNode > NodeToInsertBefore, TSharedRef< FLayoutNode > NodeToInsert)
TSharedRef< FSplitter > SetOrientation (const EOrientation InOrientation)
TSharedRef< FSplitter > SetSizeCoefficient (const float InSizeCoefficient)
TSharedRef< FSplitter > Split (TSharedRef< FLayoutNode > InNode)
Public Member Functions inherited from FTabManager::FLayoutNode
virtual ~FLayoutNode ()
virtual TSharedPtr< FArea > AsArea ()
virtual TSharedPtr< FStack > AsStack ()
float GetSizeCoefficient () const
Public Member Functions inherited from TSharedFromThis< FLayoutNode >
TSharedRef< FLayoutNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FLayoutNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
FSplitter ()
Protected Member Functions inherited from FTabManager::FLayoutNode
FLayoutNode ()
Protected Member Functions inherited from TSharedFromThis< FLayoutNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TArray< TSharedRef< FLayoutNode > > ChildNodes
EOrientation Orientation
Protected Attributes inherited from FTabManager::FLayoutNode
float SizeCoefficient
Friends
class FLayoutExtender
class FTabManager
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FLayoutNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 556 of file TabManager.h.
Constructor & Destructor Documentation
~FSplitter()
virtual FTabManager::FSplitter::~FSplitter () inline virtual
Definition at line 605 of file TabManager.h.
FSplitter()
FTabManager::FSplitter::FSplitter () inline protected
Definition at line 610 of file TabManager.h.
References Orientation.
Member Function Documentation
AsSplitter()
virtual TSharedPtr< FSplitter > FTabManager::FSplitter::AsSplitter () inline override virtual
Reimplemented from FTabManager::FLayoutNode.
Definition at line 598 of file TabManager.h.
References TSharedFromThis< FLayoutNode >::SharedThis().
GetOrientation()
EOrientation FTabManager::FSplitter::GetOrientation () const inline
Definition at line 603 of file TabManager.h.
References Orientation.
InsertAfter()
TSharedRef< FSplitter > FTabManager::FSplitter::InsertAfter (TSharedRef< FLayoutNode > NodeToInsertAfter, TSharedRef< FLayoutNode > NodeToInsert) inline
Definition at line 577 of file TabManager.h.
References check, ChildNodes, INDEX_NONE, and TSharedFromThis< FLayoutNode >::SharedThis().
InsertBefore()
TSharedRef< FSplitter > FTabManager::FSplitter::InsertBefore (TSharedRef< FLayoutNode > NodeToInsertBefore, TSharedRef< FLayoutNode > NodeToInsert) inline
Definition at line 569 of file TabManager.h.
References check, ChildNodes, INDEX_NONE, and TSharedFromThis< FLayoutNode >::SharedThis().
SetOrientation()
TSharedRef< FSplitter > FTabManager::FSplitter::SetOrientation (const EOrientation InOrientation) inline
Definition at line 592 of file TabManager.h.
References Orientation, and TSharedFromThis< FLayoutNode >::SharedThis().
SetSizeCoefficient()
TSharedRef< FSplitter > FTabManager::FSplitter::SetSizeCoefficient (const float InSizeCoefficient) inline
Definition at line 586 of file TabManager.h.
References TSharedFromThis< FLayoutNode >::SharedThis(), and FTabManager::FLayoutNode::SizeCoefficient.
Split()
TSharedRef< FSplitter > FTabManager::FSplitter::Split (TSharedRef< FLayoutNode > InNode) inline
Definition at line 563 of file TabManager.h.
References ChildNodes, and TSharedFromThis< FLayoutNode >::SharedThis().
Friends And Related Symbol Documentation
FLayoutExtender
friend class FLayoutExtender friend
Definition at line 559 of file TabManager.h.
References FLayoutExtender.
Referenced by FLayoutExtender.
FTabManager
friend class FTabManager friend
Definition at line 558 of file TabManager.h.
References FTabManager.
Referenced by FTabManager.
Field Documentation
ChildNodes
TArray< TSharedRef<FLayoutNode> > FTabManager::FSplitter::ChildNodes protected
Definition at line 616 of file TabManager.h.
Referenced by InsertAfter(), InsertBefore(), FTabManager::FArea::Split(), Split(), and FTabManager::FArea::SplitAt().
Orientation
EOrientation FTabManager::FSplitter::Orientation protected
Definition at line 615 of file TabManager.h.
Referenced by FSplitter(), GetOrientation(), FTabManager::FArea::SetOrientation(), and SetOrientation().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Docking/TabManager.h