Unreal Engine 5.6 C++ API: UE::Geometry::FIntrinsicMesh Class Reference
UE::Geometry::FIntrinsicMesh Class Reference
FIntrinsicMesh extends the FSimpleIntrinsicMesh with the addition of a 'normal coordinate' based correspondence with the surface mesh.
#include "IntrinsicTriangulationMesh.h"
Public Types
using FEdge = FSimpleIntrinsicMesh::FEdge
using FEdgeAndCrossingIdx = IntrinsicCorrespondenceUtils::FNormalCoordinates::FEdgeAndCrossingIdx
typedef TEdgeCorrespondence< FIntrinsicMesh > FEdgeCorrespondence
using FEdgeFlipInfo = FSimpleIntrinsicMesh::FEdgeFlipInfo
using FEdgeSplitInfo = DynamicMeshInfo::FEdgeSplitInfo
using FPokeTriangleInfo = DynamicMeshInfo::FPokeTriangleInfo
using FSurfacePoint = IntrinsicCorrespondenceUtils::FSurfacePoint
typedef FSimpleIntrinsicMesh MyBase
Public Types inherited from UE::Geometry::FSimpleIntrinsicMesh
using FEdge = FSimpleIntrinsicEdgeFlipMesh::FEdge
using FEdgeFlipInfo = FSimpleIntrinsicEdgeFlipMesh::FEdgeFlipInfo
using FEdgeSplitInfo = DynamicMeshInfo::FEdgeSplitInfo
using FPokeTriangleInfo = DynamicMeshInfo::FPokeTriangleInfo
typedef FSimpleIntrinsicEdgeFlipMesh MyBase
Public Types inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
using FEdge = FDynamicMesh3::FEdge
Public Member Functions
FIntrinsicMesh ()=delete
DYNAMICMESH_API FIntrinsicMesh (const FDynamicMesh3 &SurfaceMesh)
FIntrinsicMesh (const FIntrinsicMesh &)=delete
FEdgeCorrespondence ComputeEdgeCorrespondence () const
DYNAMICMESH_API EMeshResult FlipEdge (int32 EID, FEdgeFlipInfo &EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
const FDynamicMesh3 * GetExtrinsicMesh () const
DYNAMICMESH_API TArray< FEdgeAndCrossingIdx > GetImplicitEdgeCrossings (const int32 SurfaceEID, const bool bReverse=false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
const IntrinsicCorrespondenceUtils::FNormalCoordinates & GetNormalCoordinates () const
FVector3d GetVertexPosition (int32 VID) const
FSurfacePoint GetVertexSurfacePoint (int32 VID) const
DYNAMICMESH_API EMeshResult PokeTriangle (int32 TID, const FVector3d &BaryCoordinates, FPokeTriangleInfo &PokeInfo)
Insert a new vertex inside an intrinsic triangle, ie do a 1 to 3 triangle split.
DYNAMICMESH_API EMeshResult SplitEdge (int32 EdgeAB, FEdgeSplitInfo &SplitInfo, double SplitParameterT=0.5)
Split an intrinsic edge of the mesh by inserting a vertex.
DYNAMICMESH_API TArray< FSurfacePoint > TraceEdge (int32 IntrinsicEID, double CoalesceThreshold=0., bool bReverse=false) const
DYNAMICMESH_API TArray< FSurfacePoint > TraceSurfaceEdge (int32 SurfaceEID, double CoalesceThreshold, bool bReverse=false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
Public Member Functions inherited from UE::Geometry::FSimpleIntrinsicMesh
FSimpleIntrinsicMesh ()
FSimpleIntrinsicMesh (const FDynamicMesh3 &SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
FSimpleIntrinsicMesh (const FSimpleIntrinsicMesh &)=delete
DYNAMICMESH_API EMeshResult PokeTriangle (int32 TID, const FVector3d &BaryCoordinates, FPokeTriangleInfo &PokeInfo)
Insert a new vertex inside an intrinsic triangle, ie do a 1 to 3 triangle split.
DYNAMICMESH_API EMeshResult SplitEdge (int32 EdgeAB, FEdgeSplitInfo &SplitInfo, double SplitParameterT=0.5)
Split an intrinsic edge of the mesh by inserting a vertex.
Public Member Functions inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
FSimpleIntrinsicEdgeFlipMesh ()
DYNAMICMESH_API FSimpleIntrinsicEdgeFlipMesh (const FDynamicMesh3 &SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
FSimpleIntrinsicEdgeFlipMesh (const FSimpleIntrinsicEdgeFlipMesh &)=delete
bool AreSameOrientation (int32 EID) const
DYNAMICMESH_API void Clear ()
Discard all data.
DYNAMICMESH_API double EdgeCotanWeight (int32 EID) const
return 1/2 (cot(alpha_{ij}) + cot(beta_{ij})) where alpha_{ij} and beta_{ij} are the to interior angles opposite the specified edge, EID.
int32 EdgeCount () const
FRefCountVector::IndexEnumerable EdgeIndicesItr () const
DYNAMICMESH_API FVector2d EdgeOpposingAngles (int32 EID) const
return FVector2(alpha_{ij} , beta_{ij}) where alpha_{ij} and beta_{ij} are the two interior angles opposite the specified edge, EID.
DYNAMICMESH_API EMeshResult FlipEdge (int32 EID, FEdgeFlipInfo &EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
FEdge GetEdge (int32 EdgeID) const
double GetEdgeLength (int32 EID) const
DYNAMICMESH_API FIndex2i GetEdgeOpposingV (int32 EID) const
FIndex2i GetEdgeT (int32 EdgeID) const
FIndex2i GetEdgeV (int32 EdgeID) const
FIndex3i GetTriangle (int32 TriangleID) const
const FIndex3i & GetTriangleRef (int TriangleID) const
FVector3d GetTriEdgeLengths (const int32 TID) const
FIndex3i GetTriEdges (int32 TriangleID) const
double GetTriInternalAngleR (const int32 TID, const int32 IndexOf) const
FVector3d GetVertex (int32 VertexID) const
int32 GetVtxEdgeCount (int32 VID) const
bool IsBoundaryEdge (int32 EdgeID) const
bool IsBoundaryVertex (int32 VertexID) const
bool IsEdge (int32 EdgeID) const
bool IsTriangle (int32 TriangleID) const
bool IsVertex (int32 VertexID) const
int32 MaxEdgeID () const
int32 MaxTriangleID () const
int32 MaxVertexID () const
template<typename Vector3Type>
Vector3Type Permute (int32 Index, const Vector3Type &Src) const
cyclic permutation of the src vector such that the 'Index' entry in the src is the first entry in the result NB: Index must be 0, 1, or 2.
DYNAMICMESH_API void Reset (const FDynamicMesh3 &SrcMesh)
Reset the mesh to an ID-matching deep copy the basic mesh topology (but no attributes or groups)
int32 TriangleCount () const
FRefCountVector::IndexEnumerable TriangleIndicesItr () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int32 VID) const
Protected Types
using FNormalCoordinates = IntrinsicCorrespondenceUtils::FNormalCoordinates
Protected Attributes
TDynamicVector< FSurfacePoint > IntrinsicVertexPositions
FNormalCoordinates NormalCoordinates
Protected Attributes inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
const int32 AddOneModThree [3] = { 1, 2, 0 }
const int32 AddTwoModThree [3] = { 2, 0, 1 }
TDynamicVector< double > EdgeLengths
FRefCountVector EdgeRefCounts {}
TDynamicVector< FEdge > Edges
TDynamicVector< FVector3d > InternalAngles
TDynamicVector< FIndex3i > TriangleEdges
FRefCountVector TriangleRefCounts {}
TDynamicVector< FIndex3i > Triangles
FSmallListSet VertexEdgeLists
FRefCountVector VertexRefCounts {}
TDynamicVector< FVector3d > Vertices {}
Additional Inherited Members
Static Public Attributes inherited from UE::Geometry::FSimpleIntrinsicMesh
static constexpr int InvalidID = IndexConstants::InvalidID
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Static Public Attributes inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
static constexpr int InvalidID = IndexConstants::InvalidID
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Protected Member Functions inherited from UE::Geometry::FSimpleIntrinsicMesh
int32 AddEdgeInternal (int32 vA, int32 vB, int32 tA, int32 tB=InvalidID)
add new edge to the mesh topology, does not update any of the intrinsic quantities
int32 AddTriangleInternal (int32 a, int32 b, int32 c, int32 e0, int32 e1, int32 e2)
add new triangle to the mesh topology, does not update any of the intrinsic quantities
void AllocateEdgesList (int32 VertexID)
allocate, or clear existing edge list for specified vertex
int32 AppendVertex (const FVector3d &vPos)
add new vertex to the mesh topology, does not update any of the intrinsic quantities
DYNAMICMESH_API EMeshResult PokeTriangleTopology (int32 TID, FPokeTriangleInfo &PokeInfo)
Updates the mesh connectivity by adding a new vertex at the vertex-averaged location.
DYNAMICMESH_API EMeshResult SplitEdgeTopology (int32 EdgeAB, FEdgeSplitInfo &SplitInfo)
Updates the mesh connectivity by adding a new vertex at the vertex-averaged location.
Protected Member Functions inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
DYNAMICMESH_API FVector3d ComputeTriInternalAnglesR (const int32 TID) const
computes the angles based on the edge lengths, so must have valid EdgeLengths for this tri before calling.
DYNAMICMESH_API EMeshResult FlipEdgeTopology (int32 eab, FEdgeFlipInfo &FlipInfo)
update the mesh topology (e.g.
FVector3d GetEdgeLengthTriple (const FIndex3i &EIDs) const
DYNAMICMESH_API double GetOpposingVerticesDistance (int32 EID) const
DYNAMICMESH_API FIndex2i GetOrientedEdgeV (int32 EID, int32 TID) const
DYNAMICMESH_API int32 ReplaceEdgeTriangle (int32 eID, int32 tOld, int32 tNew)
replace tOld with tNew in an existing edge
int32 ReplaceTriangleEdge (int32 tID, int32 eOld, int32 eNew)
replace eOld with eNew in and existing triangle
void SetEdgeTrianglesInternal (int32 EdgeID, int32 t0, int32 t1)
update the existing edge to reference triangles t0 and t1
void SetEdgeVerticesInternal (int32 EdgeID, int32 a, int32 b)
update the existing edge to reference vertices 'a' and 'b'.
Detailed Description
FIntrinsicMesh extends the FSimpleIntrinsicMesh with the addition of a 'normal coordinate' based correspondence with the surface mesh.
This class supports both the trace of intrinsic mesh edges across the surface mesh, and the trace of surface mesh edges across the intrinsic mesh.
This supports mesh operations that: SplitEdge, PokeTriangle, FlipEdge.
Both SplitEdge and PokeTriangle will generate new vertices and triangles in the intrinsic triangulation. These vertices will live on the surface of the original mesh and their location (in R3 and relative to the original surface) is computed by interpolation.
NB: The lifetime of this structure should not exceed that of the original FDynamicMesh as this class holds a pointer to that mesh to reference locations on its surface. Also, this class isn't currently expected to work with surface meshes that have bow-ties.
Note: This assumes but does not check that the FDynamicMesh3 "Surface Mesh" has consistent orientation of all triangles.
Definition at line 766 of file IntrinsicTriangulationMesh.h.
Member Typedef Documentation
FEdge
using UE::Geometry::FIntrinsicMesh::FEdge = FSimpleIntrinsicMesh::FEdge
Definition at line 771 of file IntrinsicTriangulationMesh.h.
FEdgeAndCrossingIdx
using UE::Geometry::FIntrinsicMesh::FEdgeAndCrossingIdx = IntrinsicCorrespondenceUtils::FNormalCoordinates::FEdgeAndCrossingIdx
Definition at line 774 of file IntrinsicTriangulationMesh.h.
FEdgeCorrespondence
typedef TEdgeCorrespondence< FIntrinsicMesh > UE::Geometry::FIntrinsicMesh::FEdgeCorrespondence
Definition at line 865 of file IntrinsicTriangulationMesh.h.
FEdgeFlipInfo
using UE::Geometry::FIntrinsicMesh::FEdgeFlipInfo = FSimpleIntrinsicMesh::FEdgeFlipInfo
Definition at line 772 of file IntrinsicTriangulationMesh.h.
FEdgeSplitInfo
using UE::Geometry::FIntrinsicMesh::FEdgeSplitInfo = DynamicMeshInfo::FEdgeSplitInfo
Definition at line 776 of file IntrinsicTriangulationMesh.h.
FNormalCoordinates
using UE::Geometry::FIntrinsicMesh::FNormalCoordinates = IntrinsicCorrespondenceUtils::FNormalCoordinates protected
Definition at line 891 of file IntrinsicTriangulationMesh.h.
FPokeTriangleInfo
using UE::Geometry::FIntrinsicMesh::FPokeTriangleInfo = DynamicMeshInfo::FPokeTriangleInfo
Definition at line 775 of file IntrinsicTriangulationMesh.h.
FSurfacePoint
using UE::Geometry::FIntrinsicMesh::FSurfacePoint = IntrinsicCorrespondenceUtils::FSurfacePoint
Definition at line 773 of file IntrinsicTriangulationMesh.h.
MyBase
typedef FSimpleIntrinsicMesh UE::Geometry::FIntrinsicMesh::MyBase
Definition at line 769 of file IntrinsicTriangulationMesh.h.
Constructor & Destructor Documentation
FIntrinsicMesh() [1/3]
UE::Geometry::FIntrinsicMesh::FIntrinsicMesh () delete
Referenced by FIntrinsicMesh().
FIntrinsicMesh() [2/3]
UE::Geometry::FIntrinsicMesh::FIntrinsicMesh (const FIntrinsicMesh &) delete
References FIntrinsicMesh().
FIntrinsicMesh() [3/3]
DYNAMICMESH_API UE::Geometry::FIntrinsicMesh::FIntrinsicMesh (const FDynamicMesh3 & SurfaceMesh)
References UE_API.
Member Function Documentation
ComputeEdgeCorrespondence()
FEdgeCorrespondence UE::Geometry::FIntrinsicMesh::ComputeEdgeCorrespondence () const inline
Definition at line 867 of file IntrinsicTriangulationMesh.h.
FlipEdge()
DYNAMICMESH_API EMeshResult UE::Geometry::FIntrinsicMesh::FlipEdge (int32 EID, FEdgeFlipInfo & EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
Parameters
EdgeFlipInfo [out] populated on return.
Returns
a success or failure info.
References UE_API.
GetExtrinsicMesh()
const FDynamicMesh3 * UE::Geometry::FIntrinsicMesh::GetExtrinsicMesh () const inline
Returns
pointer the reference mesh, note the FIntrinsicTriangulation does not manage the lifetime of this mesh
Definition at line 784 of file IntrinsicTriangulationMesh.h.
References NormalCoordinates.
GetImplicitEdgeCrossings()
DYNAMICMESH_API TArray< FEdgeAndCrossingIdx > UE::Geometry::FIntrinsicMesh::GetImplicitEdgeCrossings (const int32 SurfaceEID, const bool bReverse = false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
By default this traces from vertex EdgeV.A to vertex EdgeV.B where EdgeV = SurfaceMesh.GetEdgeV(SurfaceEID).
Parameters
SurfaceEID - the surface edge to be traced
bReverse - reverses the direction of the trace giving EdgeV.B -> EdgeV.A
Returns
array of intrinsic edges crossed between the specified vertices. This can be used to compute the actual MeshPoints on the surface if desired.
References UE_API.
GetNormalCoordinates()
const IntrinsicCorrespondenceUtils::FNormalCoordinates & UE::Geometry::FIntrinsicMesh::GetNormalCoordinates () const inline
Returns
NormalCoordinate data structure that counts regular surface (extrinsic) mesh edge-crossing for each intrinsic mesh edge.
Definition at line 826 of file IntrinsicTriangulationMesh.h.
References NormalCoordinates.
GetVertexPosition()
FVector3d UE::Geometry::FIntrinsicMesh::GetVertexPosition (int32 VID) const inline
Returns
position in r3 of an intrinsic vertex.
Definition at line 876 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetVertex().
GetVertexSurfacePoint()
FSurfacePoint UE::Geometry::FIntrinsicMesh::GetVertexSurfacePoint (int32 VID) const inline
Returns
the position of the intrinsic vertex relative to the underlying surface mesh
Definition at line 884 of file IntrinsicTriangulationMesh.h.
References IntrinsicVertexPositions.
PokeTriangle()
DYNAMICMESH_API EMeshResult UE::Geometry::FIntrinsicMesh::PokeTriangle (int32 TID, const FVector3d & BaryCoordinates, FPokeTriangleInfo & PokeInfo)
Insert a new vertex inside an intrinsic triangle, ie do a 1 to 3 triangle split.
Parameters
TID - index of triangle to poke
BaryCoordinates - barycentric coordinates of poke position
PokeInfo - returned information about new and modified mesh elements
Returns
Ok on success, or enum value indicates why operation cannot be applied. Mesh remains unmodified on error.
References UE_API.
SplitEdge()
DYNAMICMESH_API EMeshResult UE::Geometry::FIntrinsicMesh::SplitEdge (int32 EdgeAB, FEdgeSplitInfo & SplitInfo, double SplitParameterT = 0.5)
Split an intrinsic edge of the mesh by inserting a vertex.
This creates a new triangle on either side of the edge (ie a 2-4 split). If the original edge had vertices [a,b], with triangles t0=[a,b,c] and t1=[b,a,d], then the split inserts new vertex f. After the split t0=[a,f,c] and t1=[f,a,d], and we have t2=[f,b,c] and t3=[f,d,b] (it's best to draw it out on paper...) SplitInfo.OriginalTriangles = {t0, t1} and SplitInfo.NewTriangles = {t2, t3}
Parameters
EdgeAB - index of the edge to be split
SplitInfo - returned information about new and modified mesh elements
SplitParameterT - defines the position along the edge that we split at, must be between 0 and 1, and is assumed to be based on the order of vertices in t0
Returns
Ok on success, or enum value indicates why operation cannot be applied. Mesh remains unmodified on error.
References UE_API.
TraceEdge()
DYNAMICMESH_API TArray< FSurfacePoint > UE::Geometry::FIntrinsicMesh::TraceEdge (int32 IntrinsicEID, double CoalesceThreshold = 0., bool bReverse = false) const
Returns
Array of FSurfacePoints relative to the surface mesh that represent the specified intrinsic mesh edge. This is directed relative to traversal of the first adjacent triangle (GetEdgeT()[0]), unless bReverse is true
Parameters
CoalesceThreshold - in barycentric units [0,1], edge crossings with in this threshold are snapped to the nearest vertex. and any resulting repetitions of vertex surface points are replaced with a single vertex surface point.
bReverse - if true, trace edge direction is reversed
Note: when tracing few edges, this method is preferred to using the FEdgeCorrespondence based tracing (see FEdgeCorrespondence below).
But when tracing a large percentage of the mesh edges the FEdgeCorrespondence will be faster as it reuses intermediate results.
References UE_API.
TraceSurfaceEdge()
DYNAMICMESH_API TArray< FSurfacePoint > UE::Geometry::FIntrinsicMesh::TraceSurfaceEdge (int32 SurfaceEID, double CoalesceThreshold, bool bReverse = false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
By default this traces from vertex EdgeV.A to vertex EdgeV.B where EdgeV = SurfaceMesh.GetEdgeV(SurfaceEID).
Parameters
SurfaceEID - the surface edge to be traced
bReverse - reverses the direction of the trace giving EdgeV.B -> EdgeV.A
Returns
array of surface points defined relative to the intrinsic mesh. In particular, the array will be a vertex followed by a sequence of (intrinsic) edge crossings.
References UE_API.
Field Documentation
IntrinsicVertexPositions
TDynamicVector<FSurfacePoint> UE::Geometry::FIntrinsicMesh::IntrinsicVertexPositions protected
Definition at line 894 of file IntrinsicTriangulationMesh.h.
Referenced by GetVertexSurfacePoint().
NormalCoordinates
FNormalCoordinates UE::Geometry::FIntrinsicMesh::NormalCoordinates protected
Definition at line 892 of file IntrinsicTriangulationMesh.h.
Referenced by GetExtrinsicMesh(), and GetNormalCoordinates().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/IntrinsicTriangulationMesh.h