Unreal Engine 5.6 C++ API: TAllFieldsIterator< T > Class Template Reference
TAllFieldsIterator< T > Class Template Reference
#include "FieldIterator.h"
Public Member Functions
TAllFieldsIterator (EObjectFlags AdditionalExclusionFlags=RF_ClassDefaultObject, EInternalObjectFlags InternalExclusionFlags=EInternalObjectFlags::None)
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
bool operator!= (const TAllFieldsIterator< T > &Rhs) const
T * operator* ()
void operator++ ()
T * operator-> ()
bool operator== (const TAllFieldsIterator< T > &Rhs) const
Protected Member Functions
void ConditionallyIterateToNextStruct ()
void InitCurrentFields ()
Initializes CurrentFields array with the currently iterated field as well as the fields it owns.
void InitFieldIterator ()
Initializes the field iterator for the current struct.
void IterateToNextField ()
Advances to the next field of the specified template type.
Private Attributes
int32 CurrentFieldIndex = -1
Currently iterated field index in CurrentFields array.
TArray< typename T::BaseFieldClass * > CurrentFields
List containing the currently iterated field as well as all fields it owns and all fields the fields it owns own etc.
TFieldIterator< typename T::BaseFieldClass > FieldIterator
Iterator for iterating over all child UFields or FFields Note that we're going to be iterating over all fields (BaseFieldClass is either FField or UField), not just the ones that match the template argument because we also want to be able to iterate inner fields (for example FArrayProperty::Inner, FSetProperty::ElementProp etc)
TObjectIterator< UStruct > StructIterator
Iterator for iterating over all UStructs.
Detailed Description
template<class T>
class TAllFieldsIterator< T >
Definition at line 38 of file FieldIterator.h.
Constructor & Destructor Documentation
TAllFieldsIterator()
template<class T> TAllFieldsIterator< T >::TAllFieldsIterator (EObjectFlags AdditionalExclusionFlags = RF_ClassDefaultObject, EInternalObjectFlags InternalExclusionFlags = EInternalObjectFlags::None) inline
Definition at line 55 of file FieldIterator.h.
References CurrentFields, FieldIterator, InitFieldIterator(), None, RF_ClassDefaultObject, and StructIterator.
Referenced by operator!=(), and operator==().
Member Function Documentation
ConditionallyIterateToNextStruct()
template<class T> void TAllFieldsIterator< T >::ConditionallyIterateToNextStruct () inline protected
Definition at line 181 of file FieldIterator.h.
References FieldIterator, InitFieldIterator(), and StructIterator.
Referenced by operator++().
InitCurrentFields()
template<class T> void TAllFieldsIterator< T >::InitCurrentFields () inline protected
Initializes CurrentFields array with the currently iterated field as well as the fields it owns.
Definition at line 110 of file FieldIterator.h.
References CurrentFieldIndex, CurrentFields, FieldIterator, and GetInnerFieldsFromField().
Referenced by InitFieldIterator(), and IterateToNextField().
InitFieldIterator()
template<class T> void TAllFieldsIterator< T >::InitFieldIterator () inline protected
Initializes the field iterator for the current struct.
Definition at line 152 of file FieldIterator.h.
References CurrentFieldIndex, EFieldIteratorFlags::ExcludeSuper, FieldIterator, EFieldIteratorFlags::IncludeDeprecated, EFieldIteratorFlags::IncludeInterfaces, InitCurrentFields(), IterateToNextField(), and StructIterator.
Referenced by TAllFieldsIterator(), and ConditionallyIterateToNextStruct().
IterateToNextField()
template<class T> void TAllFieldsIterator< T >::IterateToNextField () inline protected
Advances to the next field of the specified template type.
Definition at line 120 of file FieldIterator.h.
References CurrentFieldIndex, CurrentFields, FieldIterator, and InitCurrentFields().
Referenced by InitFieldIterator(), and operator++().
operator bool()
template<class T> FORCEINLINE TAllFieldsIterator< T >::operator bool () const inline explicit
conversion to "bool" returning true if the iterator is valid.
Definition at line 67 of file FieldIterator.h.
References bool, FieldIterator, FORCEINLINE, and StructIterator.
operator!()
template<class T> FORCEINLINE bool TAllFieldsIterator< T >::operator! () const inline
inverse of the "bool" operator
Definition at line 72 of file FieldIterator.h.
References bool, and FORCEINLINE.
operator!=()
template<class T> bool TAllFieldsIterator< T >::operator!= (const TAllFieldsIterator< T > & Rhs) const inline
Definition at line 81 of file FieldIterator.h.
References TAllFieldsIterator(), CurrentFieldIndex, and FieldIterator.
operator*()
template<class T> T * TAllFieldsIterator< T >::operator* () inline
Definition at line 91 of file FieldIterator.h.
References CastFieldChecked(), CurrentFieldIndex, and CurrentFields.
operator++()
template<class T> void TAllFieldsIterator< T >::operator++ () inline
Definition at line 86 of file FieldIterator.h.
References ConditionallyIterateToNextStruct(), and IterateToNextField().
operator->()
template<class T> T * TAllFieldsIterator< T >::operator-> () inline
Definition at line 99 of file FieldIterator.h.
References CastFieldChecked(), CurrentFieldIndex, and CurrentFields.
operator==()
template<class T> bool TAllFieldsIterator< T >::operator== (const TAllFieldsIterator< T > & Rhs) const inline
Definition at line 77 of file FieldIterator.h.
References TAllFieldsIterator(), CurrentFieldIndex, and FieldIterator.
Field Documentation
CurrentFieldIndex
template<class T> int32 TAllFieldsIterator< T >::CurrentFieldIndex = -1 private
Currently iterated field index in CurrentFields array.
Definition at line 52 of file FieldIterator.h.
Referenced by InitCurrentFields(), InitFieldIterator(), IterateToNextField(), operator!=(), operator*(), operator->(), and operator==().
CurrentFields
template<class T> TArray<typename T::BaseFieldClass*> TAllFieldsIterator< T >::CurrentFields private
List containing the currently iterated field as well as all fields it owns and all fields the fields it owns own etc.
Definition at line 50 of file FieldIterator.h.
Referenced by TAllFieldsIterator(), InitCurrentFields(), IterateToNextField(), operator*(), and operator->().
FieldIterator
template<class T> TFieldIterator<typename T::BaseFieldClass> TAllFieldsIterator< T >::FieldIterator private
Iterator for iterating over all child UFields or FFields Note that we're going to be iterating over all fields (BaseFieldClass is either FField or UField), not just the ones that match the template argument because we also want to be able to iterate inner fields (for example FArrayProperty::Inner, FSetProperty::ElementProp etc)
Definition at line 48 of file FieldIterator.h.
Referenced by TAllFieldsIterator(), ConditionallyIterateToNextStruct(), InitCurrentFields(), InitFieldIterator(), IterateToNextField(), operator bool(), operator!=(), and operator==().
StructIterator
template<class T> TObjectIterator<UStruct> TAllFieldsIterator< T >::StructIterator private
Iterator for iterating over all UStructs.
Definition at line 42 of file FieldIterator.h.
Referenced by TAllFieldsIterator(), ConditionallyIterateToNextStruct(), InitFieldIterator(), and operator bool().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/FieldIterator.h