Unreal Engine 5.6 C++ API: FSoundWaveLoadingBehaviorUtil Class Reference
FSoundWaveLoadingBehaviorUtil Class Reference
Data Structures
struct FAnnotatedClassData
Public Member Functions
FSoundWaveLoadingBehaviorUtil ()
virtual ~FSoundWaveLoadingBehaviorUtil () override=default
Public Member Functions inherited from ISoundWaveLoadingBehaviorUtil
virtual ~ISoundWaveLoadingBehaviorUtil ()=default
Private Member Functions
void CacheAllClassLoadingBehaviors ()
void CollectAllRelevantSoundClassAssetData (const FName InWaveName, TSet< FAssetData > &OutClassAssetData) const
virtual FClassData FindOwningLoadingBehavior (const USoundWave *InWave, const ITargetPlatform *InTargetPlatform) const override
void GetChainOfClassesForLoadingBehaviorInheritance (FName StartingClass, TArray< FName > &OutClasses)
FClassData LoadAndCacheClass (const FAssetData &InAssetData) const
FAnnotatedClassData WalkClassHierarchy (USoundClass *InClass) const
Private Attributes
IAssetRegistry & AssetRegistry
TMap< FName, FAnnotatedClassData > CacheClassLoadingBehaviors
FCriticalSection CacheCS
Friends
void UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook (FCbFieldViewIterator Args, UE::Cook::FCookDependencyContext &Context)
void UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook (UE::Cook::FCookEventContext &CookContext, const USoundWave *SoundWave)
Additional Inherited Members
Static Public Member Functions inherited from ISoundWaveLoadingBehaviorUtil
static ISoundWaveLoadingBehaviorUtil * Get ()
Detailed Description
Definition at line 61 of file SoundWaveLoadingBehavior.cpp.
Constructor & Destructor Documentation
FSoundWaveLoadingBehaviorUtil()
FSoundWaveLoadingBehaviorUtil::FSoundWaveLoadingBehaviorUtil () inline
Definition at line 64 of file SoundWaveLoadingBehavior.cpp.
References AssetRegistry, CacheAllClassLoadingBehaviors(), ISoundWaveLoadingBehaviorUtil::Get(), SoundWaveLoadingBehaviorUtil_CacheAllOnStartup, and TEXT.
~FSoundWaveLoadingBehaviorUtil()
virtual FSoundWaveLoadingBehaviorUtil::~FSoundWaveLoadingBehaviorUtil () override virtual default
Member Function Documentation
CacheAllClassLoadingBehaviors()
void FSoundWaveLoadingBehaviorUtil::CacheAllClassLoadingBehaviors () inline private
Definition at line 87 of file SoundWaveLoadingBehavior.cpp.
References AssetRegistry, ensureMsgf, LoadAndCacheClass(), and TEXT.
Referenced by FSoundWaveLoadingBehaviorUtil().
CollectAllRelevantSoundClassAssetData()
void FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData (const FName InWaveName, TSet< FAssetData > & OutClassAssetData) const inline private
Definition at line 143 of file SoundWaveLoadingBehavior.cpp.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), AssetRegistry, FARFilter::ClassPaths, Filter, UStruct::IsChildOf(), TArray< InElementType, InAllocatorType >::IsEmpty(), MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), FARFilter::PackageNames, TArray< InElementType, InAllocatorType >::RemoveAtSwap(), TEXT, UE_LOG, and Warning.
Referenced by FindOwningLoadingBehavior(), UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook(), and UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
FindOwningLoadingBehavior()
virtual FClassData FSoundWaveLoadingBehaviorUtil::FindOwningLoadingBehavior (const USoundWave * InWave, const ITargetPlatform * InTargetPlatform) const inline override private virtual
Implements ISoundWaveLoadingBehaviorUtil.
Definition at line 216 of file SoundWaveLoadingBehavior.cpp.
References AssetRegistry, CacheClassLoadingBehaviors, CacheCS, Class, CollectAllRelevantSoundClassAssetData(), ISoundWaveLoadingBehaviorUtil::FClassData::CompareGreater(), FindOwningLoadingBehavior(), Found, UObjectBase::GetFName(), LoadAndCacheClass(), TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, UE_LOG, and Warning.
Referenced by FindOwningLoadingBehavior().
GetChainOfClassesForLoadingBehaviorInheritance()
void FSoundWaveLoadingBehaviorUtil::GetChainOfClassesForLoadingBehaviorInheritance (FName StartingClass, TArray< FName > & OutClasses) inline private
Definition at line 275 of file SoundWaveLoadingBehavior.cpp.
References CacheClassLoadingBehaviors, CacheCS, FSoundWaveLoadingBehaviorUtil::FAnnotatedClassData::ClassHierarchy, and TArray< InElementType, InAllocatorType >::Reset().
Referenced by UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
LoadAndCacheClass()
FClassData FSoundWaveLoadingBehaviorUtil::LoadAndCacheClass (const FAssetData & InAssetData) const inline private
Definition at line 132 of file SoundWaveLoadingBehavior.cpp.
References CacheClassLoadingBehaviors, Cast(), FAssetData::GetAsset(), FAssetData::PackageName, and WalkClassHierarchy().
Referenced by CacheAllClassLoadingBehaviors(), and FindOwningLoadingBehavior().
WalkClassHierarchy()
FAnnotatedClassData FSoundWaveLoadingBehaviorUtil::WalkClassHierarchy (USoundClass * InClass) const inline private
Definition at line 104 of file SoundWaveLoadingBehavior.cpp.
References TArray< InElementType, InAllocatorType >::Add(), FSoundWaveLoadingBehaviorUtil::FAnnotatedClassData::BaseData, FSoundWaveLoadingBehaviorUtil::FAnnotatedClassData::ClassHierarchy, FName, USoundWave::GetDefaultLoadingBehavior(), ISoundWaveLoadingBehaviorUtil::FClassData::LengthOfFirstChunkInSeconds, ISoundWaveLoadingBehaviorUtil::FClassData::LoadingBehavior, RF_NeedLoad, and RF_NeedPostLoad.
Referenced by LoadAndCacheClass().
Friends And Related Symbol Documentation
UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook
void UE::SoundWaveLoadingUtil::Private::HashSoundWaveLoadingBehaviorDependenciesForCook (FCbFieldViewIterator Args, UE::Cook::FCookDependencyContext & Context) friend
UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook
void UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook (UE::Cook::FCookEventContext & CookContext, const USoundWave * SoundWave) friend
Field Documentation
AssetRegistry
IAssetRegistry& FSoundWaveLoadingBehaviorUtil::AssetRegistry private
Definition at line 291 of file SoundWaveLoadingBehavior.cpp.
Referenced by FSoundWaveLoadingBehaviorUtil(), CacheAllClassLoadingBehaviors(), CollectAllRelevantSoundClassAssetData(), and FindOwningLoadingBehavior().
CacheClassLoadingBehaviors
TMap<FName, FAnnotatedClassData> FSoundWaveLoadingBehaviorUtil::CacheClassLoadingBehaviors mutable private
Definition at line 292 of file SoundWaveLoadingBehavior.cpp.
Referenced by FindOwningLoadingBehavior(), GetChainOfClassesForLoadingBehaviorInheritance(), and LoadAndCacheClass().
CacheCS
FCriticalSection FSoundWaveLoadingBehaviorUtil::CacheCS mutable private
Definition at line 293 of file SoundWaveLoadingBehavior.cpp.
Referenced by FindOwningLoadingBehavior(), and GetChainOfClassesForLoadingBehaviorInheritance().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Sound/SoundWaveLoadingBehavior.cpp