Unreal Engine 5.6 C++ API: FWorkflowCentricApplication Class Reference
FWorkflowCentricApplication Class Reference
#include "WorkflowCentricApplication.h"
Public Member Functions
UNREALED_API FName GetCurrentMode () const
TSharedPtr< FApplicationMode > GetCurrentModePtr () const
virtual UNREALED_API FName GetToolMenuToolbarName (FName &OutParentName) const override
Get name used by tool menu.
UNREALED_API FName GetToolMenuToolbarNameForMode (const FName InModeName, FName &OutParentName) const
bool IsModeCurrent (FName ModeToCheck) const
virtual UNREALED_API void OnClose () override
Called when this toolkit is being closed.
virtual UNREALED_API bool OnRequestClose (EAssetEditorCloseReason InCloseReason) override
Called when this toolkit is requested to close.
UNREALED_API void PushTabFactories (FWorkflowAllowedTabSet &FactorySetToPush) const
virtual UNREALED_API UToolMenu * RegisterModeToolbarIfUnregistered (const FName InModeName)
Registers toolbar for a mode if not already registered.
virtual UNREALED_API void RegisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
IToolkit interface.
virtual UNREALED_API void SetCurrentMode (FName NewMode)
virtual UNREALED_API void UnregisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
Public Member Functions inherited from FAssetEditorToolkit
UNREALED_API FAssetEditorToolkit ()
Default constructor.
FAssetEditorToolkit (const FAssetEditorToolkit &)=delete
virtual UNREALED_API ~FAssetEditorToolkit ()
Virtual destructor, so that we can clean up our app when destroyed.
virtual void AddGraphEditorPinActionsToContextMenu (FToolMenuSection &InSection) const
UNREALED_API void AddMenuExtender (TSharedPtr< FExtender > Extender)
Adds or removes extenders to the default menu or the toolbar menu this asset editor.
UNREALED_API void AddToolbarExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void AddToolbarWidget (TSharedRef< SWidget > Widget)
Adds or removes widgets from the default toolbar in this asset editor.
virtual void AddViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget, int32 ZOrder=INDEX_NONE)
virtual UNREALED_API bool CloseWindow (EAssetEditorCloseReason InCloseReason) override
virtual UNREALED_API TSharedPtr< SWidget > CreateMenuBar (const TSharedPtr< FTabManager > &InTabManager, const FName InMenuName, FToolMenuContext &InToolMenuContext)
Method that can be overriden by derived classes to provide a custom MenuBar to the Standalone Toolkit Host.
UNREALED_API void FillDefaultAssetMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for modifying this asset that are generally common to most asset editors.
UNREALED_API void FillDefaultFileMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultFileMenuOpenCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultHelpMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for the help menu.
virtual UNREALED_API void FocusWindow (UObject *ObjectToFocusOn=nullptr) override
UNREALED_API void GenerateToolbar ()
Makes a default asset editing toolbar.
virtual UNREALED_API TSharedPtr< FTabManager > GetAssociatedTabManager () override
virtual FText GetBaseToolkitName () const override=0
virtual UNREALED_API FName GetEditingAssetTypeName () const override
virtual UNREALED_API FEditorModeTools & GetEditorModeManager () const final
virtual UNREALED_API FName GetEditorName () const override
IAssetEditorInstance interface.
virtual UNREALED_API double GetLastActivationTime () override
virtual UNREALED_API const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const override
virtual UNREALED_API EAssetOpenMethod GetOpenMethod () const override
UNREALED_API TSharedPtr< IToolkitHost > GetPreviousWorldCentricToolkitHost ()
virtual UNREALED_API UE::Editor::Toolbars::ECreateStatusBarOptions GetStatusBarCreationOptions () const
Called by StandaloneAssetEditorToolkitHost to determine what sections of the StatusBar should be created.
TSharedPtr< FTabManager > GetTabManager ()
virtual UNREALED_API FText GetTabSuffix () const override
virtual FName GetToolkitFName () const override=0
virtual UNREALED_API FText GetToolkitName () const override
virtual UNREALED_API FText GetToolkitToolTipText () const override
UNREALED_API FName GetToolMenuAppName () const
UNREALED_API FName GetToolMenuName () const
UNREALED_API FName GetToolMenuToolbarName () const
virtual FString GetWorldCentricTabPrefix () const override=0
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
Initializes this asset editor.
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject *ObjectToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
virtual UNREALED_API void InitToolMenuContext (FToolMenuContext &MenuContext)
virtual UNREALED_API void InvokeTab (const FTabId &TabId) override
UNREALED_API bool IsActuallyAnAsset () const
True if this actually is editing an asset.
virtual UNREALED_API bool IsAssetEditor () const override
virtual bool IsPrimaryEditor () const override
virtual void OnToolkitHostingFinished (const TSharedRef< IToolkit > &Toolkit)
virtual void OnToolkitHostingStarted (const TSharedRef< IToolkit > &Toolkit)
virtual void OnViewportDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
React to a Drag&Drop events from the viewport.
virtual void OnViewportDragLeave (const FDragDropEvent &DragDropEvent)
virtual FReply OnViewportDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
FAssetEditorToolkit & operator= (const FAssetEditorToolkit &)=delete
virtual void PostRegenerateMenusAndToolbars ()
Called at the end of RegenerateMenusAndToolbars()
UNREALED_API void RegenerateMenusAndToolbars ()
Regenerates the menubar and toolbar widgets.
UNREALED_API void RegisterDrawer (struct FWidgetDrawerConfig &&Drawer, int32 SlotIndex=INDEX_NONE)
Registers a drawer for the asset editor status bar.
UNREALED_API void RemoveAllToolbarWidgets ()
virtual UNREALED_API void RemoveEditingAsset (UObject *Asset) override
UNREALED_API void RemoveMenuExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void RemoveToolbarExtender (TSharedPtr< FExtender > Extender)
virtual void RemoveViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget)
Called when a toolkit requests the overlay widget to be removed.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout)
Applies the passed in layout (or the saved user-modified version if available).
UNREALED_API void SetMenuOverlay (TSharedRef< SWidget > Widget)
Allows the caller to set a menu overlay, displayed to the far right of the editor's menu bar.
UE_DEPRECATED (4.26, "Override CreateEditorModeManager on the toolkit class instead.") UNREALED_API void SetAssetEditorModeManager(class FAssetEditorModeManager *InModeManager)
Set the asset editor mode manager we are using.
UE_DEPRECATED (4.26, "Use GetEditorModeManager instead.") UNREALED_API class FAssetEditorModeManager *GetAssetEditorModeManager() const
Get the asset editor mode manager we are using.
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") UNREALED_API virtual bool CloseWindow() override
Public Member Functions inherited from IAssetEditorInstance
virtual bool IncludeAssetInRestoreOpenAssetsPrompt (UObject *Asset) const
virtual void InvokeTab (const struct FTabId &TabId)=0
UE_DEPRECATED (5.0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") virtual FName GetToolbarTabId() const
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") virtual bool CloseWindow()
UE_DEPRECATED (5.4, "Use the override that takes in an UObject instead") virtual bool IncludeAssetInRestoreOpenAssetsPrompt() const
If false, the asset being edited will not be included in reopen assets prompt on restart.
Public Member Functions inherited from FBaseToolkit
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API FName GetToolkitContextFName () const override
virtual UNREALED_API const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsBlueprintEditor () const override
virtual UNREALED_API bool IsHosted () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Public Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedRef< FAssetEditorToolkit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAssetEditorToolkit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TArray< FWorkflowApplicationModeExtender > & GetModeExtenderList ()
Static Public Member Functions inherited from FAssetEditorToolkit
static UNREALED_API FText GetLabelForObject (const UObject *InObject)
Gets the text to display in a toolkit titlebar for an object.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedMenuExtensibilityManager ()
Returns the default extensibility managers, these are applied for all asset types.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedToolBarExtensibilityManager ()
static UNREALED_API FText GetToolTipTextForObject (const UObject *InObject)
Gets the text to display in a toolkit tooltip for an object.
static UNREALED_API void RegisterDefaultToolBar ()
Registers default tool bar.
static UNREALED_API void SetPreviousWorldCentricToolkitHostForNewAssetEditor (TSharedRef< IToolkitHost > ToolkitHost)
Static: Used internally to set the world-centric toolkit host for a newly-created standalone asset editing toolkit.
Protected Member Functions
virtual UNREALED_API void AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode)
virtual UNREALED_API const TMap< FName, TSharedPtr< FApplicationMode > > & GetApplicationModeList () const
virtual UNREALED_API void RemoveAllApplicationModes ()
virtual UNREALED_API bool RemoveApplicationMode (FName ModeName)
Protected Member Functions inherited from FAssetEditorToolkit
virtual UNREALED_API void AddEditingObject (UObject *Object)
Adds an item to the Editing Objects list.
virtual UNREALED_API void BrowseDocumentation_Execute () const
Called when "Browse Documentation" is clicked for this asset.
virtual bool CanFindInContentBrowser () const
Called to test if "Find in Content Browser" should be enabled for this asset.
virtual UNREALED_API bool CanReimport () const
Called to check to see if there's an asset capable of being reimported.
virtual UNREALED_API bool CanReimport (UObject *EditingObject) const
bool CanReimport_Internal () const
Internal function to check if the asset can be reimported that calls CanReimport.
virtual bool CanSaveAsset () const
Called to test if "Save" should be enabled for this asset.
bool CanSaveAsset_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAsset.
virtual bool CanSaveAssetAs () const
Called to test if "Save As" should be enabled for this asset.
bool CanSaveAssetAs_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAssetAs.
virtual UNREALED_API void CreateEditorModeManager () override
virtual UNREALED_API void FindInContentBrowser_Execute ()
Called when "Find in Content Browser" is clicked for this asset.
virtual UNREALED_API UToolMenu * GenerateCommonActionsToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for common asset actions like Save.
UToolMenu * GenerateReadOnlyToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for read only mode specific content.
virtual UNREALED_API FLinearColor GetDefaultTabColor () const
virtual UNREALED_API const FSlateBrush * GetDefaultTabIcon () const
virtual UNREALED_API FString GetDocumentationLink () const
UNREALED_API UObject * GetEditingObject () const
Returns the single object currently being edited.
UNREALED_API TArray< TObjectPtr< UObject > > & GetEditingObjectPtrs ()
UNREALED_API const TArray< UObject * > & GetEditingObjects () const
Returns an array of all the objects currently being edited.
virtual UNREALED_API FName GetReadOnlyMenuProfileName ()
Get the name of the profile registered with UToolMenus for read only menu customizations.
virtual UNREALED_API void GetSaveableObjects (TArray< UObject * > &OutObjects) const
Get the collection of edited objects that can be saved.
virtual UNREALED_API EVisibility GetVisibilityWhileAssetCompiling () const
Called to get the desired visibility when the asset is compiling.
bool HasEditingObject () const
Returns true if this toolkit has any objects being edited.
virtual bool IsFindInContentBrowserButtonVisible () const
Called to test if "Find in Content Browser" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetAsVisible () const
Called to test if "Save As" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetVisible () const
Called to test if "Save" should be visible for this asset.
virtual UNREALED_API void MapToolkitCommands ()
Can be overriden to prevent registering the default commands.
virtual void OnAssetsSaved (const TArray< UObject * > &SavedObjects)
Called from SaveAsset_Execute when assets have been saved.
virtual void OnAssetsSavedAs (const TArray< UObject * > &SavedObjects)
Called from SaveAssetAs_Execute when assets have been saved.
virtual void PostInitAssetEditor ()
Perform any initialization that should happen after the basic toolkit needs are created for the asset editor.
virtual UNREALED_API void Reimport_Execute ()
Called when "Reimport" is clicked for this asset.
virtual UNREALED_API void Reimport_Execute (UObject *EditingObject)
virtual UNREALED_API void RemoveEditingObject (UObject *Object)
Removes an item from the Editing Objects list.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout, bool bLoadUserLayout)
Applies the passed in layout.
virtual UNREALED_API void SaveAsset_Execute ()
Called when "Save" is clicked for this asset.
virtual UNREALED_API void SaveAssetAs_Execute ()
Called when "Save As" is clicked for this asset.
virtual UNREALED_API void SetupReadOnlyMenuProfiles (FReadOnlyAssetEditorCustomization &OutReadOnlyCustomization)
Specify the permission lists to use in read only mode.
virtual UNREALED_API bool ShouldPromptForNewFilesOnReload (const UObject &object) const
Called to determine if the user should be prompted for a new file if one is missing during an asset reload.
virtual bool ShouldReopenEditorForSavedAsset (const UObject *Asset) const
Whether to open a new asset editor for the newly-saved Asset.
UE_DEPRECATED (4.26, "Use EditorModeManager instead.") FAssetEditorModeManager *AssetEditorModeManager
UE_DEPRECATED (5.3, "Use OnRequestClose that takes in an EAssetEditorCloseReason instead") virtual bool OnRequestClose()
Called when this toolkit is requested to close.
Protected Member Functions inherited from FBaseToolkit
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TSharedPtr< FApplicationMode > CurrentAppModePtr
Protected Attributes inherited from FAssetEditorToolkit
TSharedPtr< FWorkspaceItem > AssetEditorTabsCategory
The base category that tabs are registered to, allows for child classes to register to the same point.
bool bCheckDirtyOnAssetSave
Whether only dirty assets should be prompted about on save - otherwise all edited assets will be prompted to the user for save/check-out.
TSharedPtr< FEditorModeTools > EditorModeManager
The editor mode manager.
TArray< TSharedPtr< FLayoutExtender > > LayoutExtenders
Array of layout extenders.
FString LayoutIni = GEditorLayoutIni
What ini file should be used to persist and restore the user's layout.
TWeakPtr< IToolkitHost > PreviousWorldCentricToolkitHost
For standalone asset editing tool-kits that were switched from world-centric mode on the fly, this stores the toolkit host (level editor) that hosted this toolkit last.
TSharedPtr< FTabManager > TabManager
Controls our internal layout.
Protected Attributes inherited from FBaseToolkit
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Private Attributes
TMap< FName, TSharedPtr< FApplicationMode > > ApplicationModeList
Static Private Attributes
static UNREALED_API TArray< FWorkflowApplicationModeExtender > ModeExtenderList
Additional Inherited Members
Static Protected Member Functions inherited from FAssetEditorToolkit
static UNREALED_API void SwitchToStandaloneEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to Standalone Editor" is clicked for the asset editor.
static UNREALED_API void SwitchToWorldCentricEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to World-Centric Editor" is clicked for the asset editor.
Static Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 19 of file WorkflowCentricApplication.h.
Member Function Documentation
AddApplicationMode()
virtual UNREALED_API void FWorkflowCentricApplication::AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode) protected virtual
Reimplemented in FRigVMNewEditor.
Referenced by FRigVMNewEditor::AddApplicationMode().
GetApplicationModeList()
virtual UNREALED_API const TMap< FName, TSharedPtr< FApplicationMode > > & FWorkflowCentricApplication::GetApplicationModeList () const protected virtual
GetCurrentMode()
UNREALED_API FName FWorkflowCentricApplication::GetCurrentMode () const
Referenced by IsModeCurrent().
GetCurrentModePtr()
TSharedPtr< FApplicationMode > FWorkflowCentricApplication::GetCurrentModePtr () const inline
Definition at line 38 of file WorkflowCentricApplication.h.
References CurrentAppModePtr.
GetModeExtenderList()
TArray< FWorkflowApplicationModeExtender > & FWorkflowCentricApplication::GetModeExtenderList () inline static
Definition at line 47 of file WorkflowCentricApplication.h.
References ModeExtenderList.
GetToolMenuToolbarName()
virtual UNREALED_API FName FWorkflowCentricApplication::GetToolMenuToolbarName (FName & OutParentName) const override virtual
Get name used by tool menu.
Reimplemented from FAssetEditorToolkit.
GetToolMenuToolbarNameForMode()
UNREALED_API FName FWorkflowCentricApplication::GetToolMenuToolbarNameForMode (const FName InModeName, FName & OutParentName) const
IsModeCurrent()
bool FWorkflowCentricApplication::IsModeCurrent (FName ModeToCheck) const inline
Definition at line 39 of file WorkflowCentricApplication.h.
References GetCurrentMode().
OnClose()
virtual UNREALED_API void FWorkflowCentricApplication::OnClose () override virtual
Called when this toolkit is being closed.
Reimplemented from FAssetEditorToolkit.
Reimplemented in FBlueprintEditor, and FRigVMNewEditor.
OnRequestClose()
virtual UNREALED_API bool FWorkflowCentricApplication::OnRequestClose (EAssetEditorCloseReason InCloseReason) override virtual
Called when this toolkit is requested to close.
Returns false if closing should be prevented.
Reimplemented from FAssetEditorToolkit.
Reimplemented in FBlueprintEditor, and FWidgetBlueprintEditor.
PushTabFactories()
UNREALED_API void FWorkflowCentricApplication::PushTabFactories (FWorkflowAllowedTabSet & FactorySetToPush) const
RegisterModeToolbarIfUnregistered()
virtual UNREALED_API UToolMenu * FWorkflowCentricApplication::RegisterModeToolbarIfUnregistered (const FName InModeName) virtual
Registers toolbar for a mode if not already registered.
Parameters
InModeName - Name of the mode to register toolbar for
Returns
nullptr if toolbar already registered.
RegisterTabSpawners()
virtual UNREALED_API void FWorkflowCentricApplication::RegisterTabSpawners (const TSharedRef< class FTabManager > & TabManager) override virtual
IToolkit interface.
Reimplemented from FAssetEditorToolkit.
Reimplemented in FBlueprintEditor, and FRigVMNewEditor.
References FAssetEditorToolkit::TabManager.
RemoveAllApplicationModes()
virtual UNREALED_API void FWorkflowCentricApplication::RemoveAllApplicationModes () protected virtual
RemoveApplicationMode()
virtual UNREALED_API bool FWorkflowCentricApplication::RemoveApplicationMode (FName ModeName) protected virtual
SetCurrentMode()
virtual UNREALED_API void FWorkflowCentricApplication::SetCurrentMode (FName NewMode) virtual
Reimplemented in FBlueprintEditor, and FRigVMNewEditor.
UnregisterTabSpawners()
virtual UNREALED_API void FWorkflowCentricApplication::UnregisterTabSpawners (const TSharedRef< class FTabManager > & TabManager) override virtual
Reimplemented from FAssetEditorToolkit.
References FAssetEditorToolkit::TabManager.
Field Documentation
ApplicationModeList
TMap< FName, TSharedPtr<FApplicationMode> > FWorkflowCentricApplication::ApplicationModeList private
Definition at line 75 of file WorkflowCentricApplication.h.
CurrentAppModePtr
TSharedPtr<FApplicationMode> FWorkflowCentricApplication::CurrentAppModePtr protected
Definition at line 71 of file WorkflowCentricApplication.h.
Referenced by GetCurrentModePtr().
ModeExtenderList
UNREALED_API TArray<FWorkflowApplicationModeExtender> FWorkflowCentricApplication::ModeExtenderList static private
Definition at line 77 of file WorkflowCentricApplication.h.
Referenced by GetModeExtenderList().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/WorkflowOrientedApp/WorkflowCentricApplication.h