Unreal Engine 5.6 C++ API: UE::Geometry::TPointHashGrid3< PointDataType, RealType > Class Template Reference
UE::Geometry::TPointHashGrid3< PointDataType, RealType > Class Template Reference
Hash Grid for values associated with 3D points.
#include "PointHashGrid3.h"
Public Member Functions
TPointHashGrid3 (RealType CellSize, PointDataType InvalidValue)
Construct 3D hash grid.
void EnumeratePointsInBall (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(PointDataType, double)> ProcessPointFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc=[](const PointDataType &data) { return false;}) const
Call ProcessPointFunc on all points in grid within a given sphere, or until the function returns false Note: Not thread-safe to update, remove or insert points during enumeration.
TPair< PointDataType, RealType > FindAnyInRadius (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc) const
TPair< PointDataType, RealType > FindAnyInRadius (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc) const
Find any point within radius.
TPair< PointDataType, RealType > FindNearestInRadius (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc) const
TPair< PointDataType, RealType > FindNearestInRadius (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc) const
Find nearest point within radius.
int FindPointsInBall (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TArray< PointDataType > &ResultsOut, TFunctionRef< bool(const PointDataType &)> IgnoreFunc=[](const PointDataType &data) { return false;}) const
Find all points in grid within a given sphere.
PointDataType GetInvalidValue () const
Invalid grid value.
void InsertPoint (const PointDataType &Value, const TVector< RealType > &Position)
Insert at given position.
void InsertPointUnsafe (const PointDataType &Value, const TVector< RealType > &Position)
Insert at given position, without locking / thread-safety.
bool IsCellEmpty (const TVector< RealType > &Position)
Test if the cell containing Position is empty.
bool IsCellEmptyUnsafe (const TVector< RealType > &Position)
Test if the whole cell containing Position is empty, without locking / thread-safety Can be used to skip a more expensive range search, in some cases.
bool RemovePoint (const PointDataType &Value, const TVector< RealType > &Position)
Remove at given position.
bool RemovePointUnsafe (const PointDataType &Value, const TVector< RealType > &Position)
Remove at given position, without locking / thread-safety.
void Reserve (int32 Num)
Reserve space in the underlying hash map.
void Reset (RealType NewCellSize)
Remove all entries in the underlying hash map, without resizing or releasing any allocations, and reset the cell size.
void UpdatePoint (const PointDataType &Value, const TVector< RealType > &OldPosition, const TVector< RealType > &NewPosition)
Move value from old to new position.
void UpdatePointUnsafe (const PointDataType &Value, const TVector< RealType > &OldPosition, const TVector< RealType > &NewPosition)
Move value from old to new position, without locking / thread-safety.
Private Member Functions
template<bool bEarlyOut = false>
TPair< PointDataType, RealType > FindInRadiusHelper (const TVector< RealType > &QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc) const
Private Attributes
FCriticalSection CriticalSection
TMultiMap< FVector3i, PointDataType > Hash
TScaleGridIndexer3< RealType > Indexer
PointDataType InvalidValue
Detailed Description
template<typename PointDataType, typename RealType>
class UE::Geometry::TPointHashGrid3< PointDataType, RealType >
Hash Grid for values associated with 3D points.
This class addresses the situation where you have a list of (point, point_data) and you would like to be able to do efficient proximity queries, i.e. find the nearest point_data for a given query point.
We don't store copies of the 3D points. You provide a point_data type. This could just be the integer index into your list for example, a pointer to something more complex, etc. Insert and Remove functions require you to pass in the 3D point for the point_data. To Update a point you need to know its old and new 3D coordinates.
Definition at line 31 of file PointHashGrid3.h.
Constructor & Destructor Documentation
TPointHashGrid3()
template<typename PointDataType, typename RealType> UE::Geometry::TPointHashGrid3< PointDataType, RealType >::TPointHashGrid3 (RealType CellSize, PointDataType InvalidValue) inline
Construct 3D hash grid.
Parameters
CellSize size of grid cells. Clamped to at least a small tolerance size.
InvalidValue this value will be returned by queries if no valid result is found (e.g. bounded-distance query)
Definition at line 46 of file PointHashGrid3.h.
Member Function Documentation
EnumeratePointsInBall()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::EnumeratePointsInBall (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(PointDataType, double)> ProcessPointFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc = [](const PointDataType& data) { return false; }) const inline
Call ProcessPointFunc on all points in grid within a given sphere, or until the function returns false Note: Not thread-safe to update, remove or insert points during enumeration.
Parameters
QueryPoint the center of the query sphere
Radius the radius of the query sphere
DistanceSqFunc Function you provide which measures the squared distance between QueryPoint and a Value
ProcessPointFunc Function you provide to process each found point. Takes point data and the distance squared; returns true to continue iteration, or false to stop.
IgnoreFunc optional Function you may provide which will result in a Value being ignored if IgnoreFunc(Value) returns true
Definition at line 318 of file PointHashGrid3.h.
Referenced by UE::Geometry::FVertexConnectedComponents::ConnectCloseVertices().
FindAnyInRadius() [1/2]
template<typename PointDataType, typename RealType> TPair< PointDataType, RealType > UE::Geometry::TPointHashGrid3< PointDataType, RealType >::FindAnyInRadius (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc) const inline
Definition at line 247 of file PointHashGrid3.h.
FindAnyInRadius() [2/2]
template<typename PointDataType, typename RealType> TPair< PointDataType, RealType > UE::Geometry::TPointHashGrid3< PointDataType, RealType >::FindAnyInRadius (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc) const inline
Find any point within radius.
Note: Not thread-safe to update, remove or insert points during this query.
Parameters
QueryPoint the center of the query sphere
Radius the radius of the query sphere
DistanceSqFunc Function you provide which measures the squared distance between QueryPoint and a Value
IgnoreFunc optional Function you may provide which will result in a Value being ignored if IgnoreFunc(Value) returns true
Returns
the found pair (Value,DistanceSqFunc(Value)), or (InvalidValue,MaxDouble) if not found
Definition at line 239 of file PointHashGrid3.h.
FindInRadiusHelper()
template<typename PointDataType, typename RealType> template<bool bEarlyOut = false> TPair< PointDataType, RealType > UE::Geometry::TPointHashGrid3< PointDataType, RealType >::FindInRadiusHelper (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc) const inline private
Definition at line 364 of file PointHashGrid3.h.
Referenced by UE::Geometry::TPointHashGrid3< PointDataType, double >::FindAnyInRadius(), UE::Geometry::TPointHashGrid3< PointDataType, double >::FindAnyInRadius(), UE::Geometry::TPointHashGrid3< PointDataType, double >::FindNearestInRadius(), and UE::Geometry::TPointHashGrid3< PointDataType, double >::FindNearestInRadius().
FindNearestInRadius() [1/2]
template<typename PointDataType, typename RealType> TPair< PointDataType, RealType > UE::Geometry::TPointHashGrid3< PointDataType, RealType >::FindNearestInRadius (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc) const inline
Definition at line 223 of file PointHashGrid3.h.
FindNearestInRadius() [2/2]
template<typename PointDataType, typename RealType> TPair< PointDataType, RealType > UE::Geometry::TPointHashGrid3< PointDataType, RealType >::FindNearestInRadius (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TFunctionRef< bool(const PointDataType &)> IgnoreFunc) const inline
Find nearest point within radius.
Note: Not thread-safe to update, remove or insert points during this query.
Parameters
QueryPoint the center of the query sphere
Radius the radius of the query sphere
DistanceSqFunc Function you provide which measures the squared distance between QueryPoint and a Value
IgnoreFunc optional Function you may provide which will result in a Value being ignored if IgnoreFunc(Value) returns true
Returns
the found pair (Value,DistanceSqFunc(Value)), or (InvalidValue,MaxDouble) if not found
Definition at line 215 of file PointHashGrid3.h.
FindPointsInBall()
template<typename PointDataType, typename RealType> int UE::Geometry::TPointHashGrid3< PointDataType, RealType >::FindPointsInBall (const TVector< RealType > & QueryPoint, RealType Radius, TFunctionRef< RealType(const PointDataType &)> DistanceSqFunc, TArray< PointDataType > & ResultsOut, TFunctionRef< bool(const PointDataType &)> IgnoreFunc = [](const PointDataType& data) { return false; }) const inline
Find all points in grid within a given sphere.
Note: Not thread-safe to update, remove or insert points during this query.
Parameters
QueryPoint the center of the query sphere
Radius the radius of the query sphere
DistanceSqFunc Function you provide which measures the squared distance between QueryPoint and a Value
ResultsOut Array that points in sphere will be added to
IgnoreFunc optional Function you may provide which will result in a Value being ignored if IgnoreFunc(Value) returns true
Returns
the number of found points
Definition at line 265 of file PointHashGrid3.h.
GetInvalidValue()
template<typename PointDataType, typename RealType> PointDataType UE::Geometry::TPointHashGrid3< PointDataType, RealType >::GetInvalidValue () const inline
Invalid grid value.
Definition at line 70 of file PointHashGrid3.h.
Referenced by UE::Geometry::TPointHashGrid3< PointDataType, double >::FindInRadiusHelper().
InsertPoint()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::InsertPoint (const PointDataType & Value, const TVector< RealType > & Position) inline
Insert at given position.
This function is thread-safe.
Parameters
Value the point/value to insert
Position the position associated with this value
Definition at line 80 of file PointHashGrid3.h.
InsertPointUnsafe()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::InsertPointUnsafe (const PointDataType & Value, const TVector< RealType > & Position) inline
Insert at given position, without locking / thread-safety.
Parameters
Value the point/value to insert
Position the position associated with this value
Definition at line 94 of file PointHashGrid3.h.
Referenced by UE::Geometry::FVertexConnectedComponents::ConnectCloseVertices().
IsCellEmpty()
template<typename PointDataType, typename RealType> bool UE::Geometry::TPointHashGrid3< PointDataType, RealType >::IsCellEmpty (const TVector< RealType > & Position) inline
Test if the cell containing Position is empty.
This function is thread-safe. Can be used to skip a more expensive range search, in some cases.
Returns
true if the cell containing Position is empty
Definition at line 135 of file PointHashGrid3.h.
IsCellEmptyUnsafe()
template<typename PointDataType, typename RealType> bool UE::Geometry::TPointHashGrid3< PointDataType, RealType >::IsCellEmptyUnsafe (const TVector< RealType > & Position) inline
Test if the whole cell containing Position is empty, without locking / thread-safety Can be used to skip a more expensive range search, in some cases.
Returns
true if the cell containing Position is empty
Definition at line 151 of file PointHashGrid3.h.
RemovePoint()
template<typename PointDataType, typename RealType> bool UE::Geometry::TPointHashGrid3< PointDataType, RealType >::RemovePoint (const PointDataType & Value, const TVector< RealType > & Position) inline
Remove at given position.
This function is thread-safe.
Parameters
Value the point/value to remove
Position the position associated with this value
Returns
true if the value existed at this position
Definition at line 107 of file PointHashGrid3.h.
RemovePointUnsafe()
template<typename PointDataType, typename RealType> bool UE::Geometry::TPointHashGrid3< PointDataType, RealType >::RemovePointUnsafe (const PointDataType & Value, const TVector< RealType > & Position) inline
Remove at given position, without locking / thread-safety.
Parameters
Value the point/value to remove
Position the position associated with this value
Returns
true if the value existed at this position
Definition at line 122 of file PointHashGrid3.h.
Reserve()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::Reserve (int32 Num) inline
Reserve space in the underlying hash map.
Parameters
Num amount of elements to reserve
Definition at line 54 of file PointHashGrid3.h.
Reset()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::Reset (RealType NewCellSize) inline
Remove all entries in the underlying hash map, without resizing or releasing any allocations, and reset the cell size.
Parameters
NewCellSize The size of grid cells. Clamped to at least a small tolerance size.
Definition at line 63 of file PointHashGrid3.h.
UpdatePoint()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::UpdatePoint (const PointDataType & Value, const TVector< RealType > & OldPosition, const TVector< RealType > & NewPosition) inline
Move value from old to new position.
This function is thread-safe.
Parameters
Value the point/value to update
OldPosition the current position associated with this value
NewPosition the new position for this value
Definition at line 164 of file PointHashGrid3.h.
UpdatePointUnsafe()
template<typename PointDataType, typename RealType> void UE::Geometry::TPointHashGrid3< PointDataType, RealType >::UpdatePointUnsafe (const PointDataType & Value, const TVector< RealType > & OldPosition, const TVector< RealType > & NewPosition) inline
Move value from old to new position, without locking / thread-safety.
Parameters
Value the point/value to update
OldPosition the current position associated with this value
NewPosition the new position for this value
Definition at line 192 of file PointHashGrid3.h.
Field Documentation
CriticalSection
template<typename PointDataType, typename RealType> FCriticalSection UE::Geometry::TPointHashGrid3< PointDataType, RealType >::CriticalSection private
Definition at line 35 of file PointHashGrid3.h.
Hash
template<typename PointDataType, typename RealType> TMultiMap<FVector3i, PointDataType> UE::Geometry::TPointHashGrid3< PointDataType, RealType >::Hash private
Definition at line 34 of file PointHashGrid3.h.
Indexer
template<typename PointDataType, typename RealType> TScaleGridIndexer3<RealType> UE::Geometry::TPointHashGrid3< PointDataType, RealType >::Indexer private
Definition at line 36 of file PointHashGrid3.h.
InvalidValue
template<typename PointDataType, typename RealType> PointDataType UE::Geometry::TPointHashGrid3< PointDataType, RealType >::InvalidValue private
Definition at line 37 of file PointHashGrid3.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/PointHashGrid3.h