Unreal Engine 5.6 C++ API: UAbilitySystemTestAttributeSet Class Reference
UAbilitySystemTestAttributeSet Class Reference
#include "AbilitySystemTestAttributeSet.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY()) mutable float MaxHealth
NOTE ON MUTABLE: This is only done so that UAbilitySystemTestAttributeSet can be initialized directly in GameplayEffectsTest.cpp without doing a const_cast in 100+ places.
virtual GAMEPLAYABILITIES_API void PostGameplayEffectExecute (const struct FGameplayEffectModCallbackData &Data) override
virtual GAMEPLAYABILITIES_API bool PreGameplayEffectExecute (struct FGameplayEffectModCallbackData &Data) override
UPROPERTY () mutable FGameplayAttributeData Mana
UPROPERTY () mutable float ArmorDamageReduction
UPROPERTY () mutable float CritChance
UPROPERTY () mutable float CritMultiplier
UPROPERTY () mutable float Damage
This Damage is just used for applying negative health mods.
UPROPERTY () mutable float DodgeChance
UPROPERTY () mutable float LifeSteal
UPROPERTY () mutable float MaxMana
UPROPERTY () mutable float NoStackAttribute
UPROPERTY () mutable float PhysicalDamage
This Attribute is the actual physical damage for this actor.
UPROPERTY () mutable float SpellDamage
This Attribute is the actual spell damage for this actor.
UPROPERTY () mutable float StackingAttribute1
UPROPERTY () mutable float StackingAttribute2
UPROPERTY () mutable float Strength
UPROPERTY ()) mutable float Health
Detailed Description
Definition at line 13 of file AbilitySystemTestAttributeSet.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UAbilitySystemTestAttributeSet::GENERATED_UCLASS_BODY () private
NOTE ON MUTABLE: This is only done so that UAbilitySystemTestAttributeSet can be initialized directly in GameplayEffectsTest.cpp without doing a const_cast in 100+ places.
Mutable is not required and should never be used on normal attribute sets.
References Category, meta, and UPROPERTY().
PostGameplayEffectExecute()
virtual GAMEPLAYABILITIES_API void UAbilitySystemTestAttributeSet::PostGameplayEffectExecute (const struct FGameplayEffectModCallbackData & Data) override private virtual
References PostGameplayEffectExecute(), and UE_API.
Referenced by PostGameplayEffectExecute().
PreGameplayEffectExecute()
virtual GAMEPLAYABILITIES_API bool UAbilitySystemTestAttributeSet::PreGameplayEffectExecute (struct FGameplayEffectModCallbackData & Data) override private virtual
References PreGameplayEffectExecute(), and UE_API.
Referenced by PreGameplayEffectExecute().
UPROPERTY() [1/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [2/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [3/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [4/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [5/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
This Damage is just used for applying negative health mods.
Its not a 'persistent' attribute.
References Category, Damage, and UPROPERTY().
UPROPERTY() [6/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [7/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [8/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [9/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [10/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
This Attribute is the actual physical damage for this actor.
It will power physical based GameplayEffects
References Category, and UPROPERTY().
UPROPERTY() [11/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
This Attribute is the actual spell damage for this actor.
It will power spell based GameplayEffects
References Category, and UPROPERTY().
UPROPERTY() [12/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [13/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [14/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [15/15]
UAbilitySystemTestAttributeSet::UPROPERTY () private
References Category, meta, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/AbilitySystemTestAttributeSet.h