Unreal Engine 5.6 C++ API: FStringOutputDeviceCountLines Class Reference
FStringOutputDeviceCountLines Class Reference
#include "UnrealString.h"
Public Member Functions
FStringOutputDeviceCountLines (const FStringOutputDeviceCountLines &)=default
FStringOutputDeviceCountLines (const TCHAR *OutputDeviceName=TEXT(""))
FORCEINLINE FStringOutputDeviceCountLines (FStringOutputDeviceCountLines &&Other)
int32 GetLineCount () const
virtual FString & operator+= (const FString &Other) override
Appends other FString (as well as its specializations like FStringOutputDevice) object to this.
virtual FStringOutputDeviceCountLines & operator+= (const FStringOutputDeviceCountLines &Other)
Appends other FStringOutputDeviceCountLines object to this one.
FStringOutputDeviceCountLines & operator= (const FStringOutputDeviceCountLines &)=default
FORCEINLINE FStringOutputDeviceCountLines & operator= (FStringOutputDeviceCountLines &&Other)
virtual void Serialize (const TCHAR *InData, ELogVerbosity::Type Verbosity, const class FName &Category) override
Public Member Functions inherited from FStringOutputDevice
FStringOutputDevice (const FStringOutputDevice &)=default
FStringOutputDevice (const TCHAR *OutputDeviceName=TEXT(""))
FStringOutputDevice (FStringOutputDevice &&)=default
FStringOutputDevice & operator= (const FStringOutputDevice &)=default
FStringOutputDevice & operator= (FStringOutputDevice &&)=default
Public Member Functions inherited from FOutputDevice
FOutputDevice ()
FOutputDevice (const FOutputDevice &)
FOutputDevice (FOutputDevice &&)
virtual ~FOutputDevice ()
virtual bool CanBeUsedOnAnyThread () const
virtual bool CanBeUsedOnMultipleThreads () const
virtual bool CanBeUsedOnPanicThread () const
template<typename FmtType, typename... Types>
FORCEINLINE void CategorizedLogf (const FName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
virtual void Dump (class FArchive &Ar)
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
virtual void Flush ()
FORCEINLINE bool GetAutoEmitLineTerminator () const
FORCEINLINE bool GetSuppressEventTag () const
virtual bool IsMemoryOnly () const
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const FString &S)
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Str)
void Log (const FString &S)
void Log (const FText &S)
void Log (const TCHAR *S)
void Log (ELogVerbosity::Type Verbosity, const FString &S)
void Log (ELogVerbosity::Type Verbosity, const TCHAR *S)
template<typename FmtType>
void Logf (const FmtType &Fmt)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
FOutputDevice & operator= (const FOutputDevice &)
FOutputDevice & operator= (FOutputDevice &&)
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category)=0
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category, const double Time)
virtual void SerializeRecord (const UE::FLogRecord &Record)
void SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator)
void SetSuppressEventTag (bool bInSuppressEventTag)
virtual void TearDown ()
Closes output device and cleans up.
Private Types
typedef FStringOutputDevice Super
Private Attributes
int32 LineCount
Additional Inherited Members
Protected Attributes inherited from FOutputDevice
bool bAutoEmitLineTerminator
Whether to output a line-terminator after each log call...
bool bSuppressEventTag
Whether to output the 'Log: ' type front...
Detailed Description
Definition at line 326 of file UnrealString.h.
Member Typedef Documentation
Super
typedef FStringOutputDevice FStringOutputDeviceCountLines::Super private
Definition at line 328 of file UnrealString.h.
Constructor & Destructor Documentation
FStringOutputDeviceCountLines() [1/3]
FStringOutputDeviceCountLines::FStringOutputDeviceCountLines (const TCHAR * OutputDeviceName = TEXT("")) inline
Definition at line 332 of file UnrealString.h.
References LineCount.
Referenced by FStringOutputDeviceCountLines(), FStringOutputDeviceCountLines(), operator+=(), operator=(), and operator=().
FStringOutputDeviceCountLines() [2/3]
FStringOutputDeviceCountLines::FStringOutputDeviceCountLines (const FStringOutputDeviceCountLines &) default
References FStringOutputDeviceCountLines().
FStringOutputDeviceCountLines() [3/3]
FORCEINLINE FStringOutputDeviceCountLines::FStringOutputDeviceCountLines (FStringOutputDeviceCountLines && Other) inline
Definition at line 389 of file UnrealString.h.
References FStringOutputDeviceCountLines(), FORCEINLINE, LineCount, and Other.
Member Function Documentation
GetLineCount()
int32 FStringOutputDeviceCountLines::GetLineCount () const inline
Definition at line 381 of file UnrealString.h.
References LineCount.
operator+=() [1/2]
virtual FString & FStringOutputDeviceCountLines::operator+= (const FString & Other) inline override virtual
Appends other FString (as well as its specializations like FStringOutputDevice) object to this.
Reimplemented from FStringOutputDevice.
Definition at line 374 of file UnrealString.h.
References Log, and Other.
operator+=() [2/2]
virtual FStringOutputDeviceCountLines & FStringOutputDeviceCountLines::operator+= (const FStringOutputDeviceCountLines & Other) inline virtual
Appends other FStringOutputDeviceCountLines object to this one.
Definition at line 361 of file UnrealString.h.
References FStringOutputDeviceCountLines(), LineCount, and Other.
operator=() [1/2]
FStringOutputDeviceCountLines & FStringOutputDeviceCountLines::operator= (const FStringOutputDeviceCountLines &) default
References FStringOutputDeviceCountLines().
operator=() [2/2]
FORCEINLINE FStringOutputDeviceCountLines & FStringOutputDeviceCountLines::operator= (FStringOutputDeviceCountLines && Other) inline
Definition at line 396 of file UnrealString.h.
References FStringOutputDeviceCountLines(), FORCEINLINE, LineCount, and Other.
Serialize()
virtual void FStringOutputDeviceCountLines::Serialize (const TCHAR * InData, ELogVerbosity::Type Verbosity, const class FName & Category) inline override virtual
Reimplemented from FStringOutputDevice.
Definition at line 337 of file UnrealString.h.
References FOutputDevice::bAutoEmitLineTerminator, Category, LINE_TERMINATOR, LineCount, FStringOutputDevice::Serialize(), TCString< TCHAR >::Strlen(), and TCString< TCHAR >::Strstr().
Field Documentation
LineCount
int32 FStringOutputDeviceCountLines::LineCount private
Definition at line 330 of file UnrealString.h.
Referenced by FStringOutputDeviceCountLines(), FStringOutputDeviceCountLines(), GetLineCount(), operator+=(), operator=(), and Serialize().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/UnrealString.h