Unreal Engine 5.6 C++ API: FUnixSignalGameHitchHeartBeat Class Reference
FUnixSignalGameHitchHeartBeat Class Reference
#include "UnixSignalHeartBeat.h"
Public Member Functions
void FrameStart (bool bSkipThisFrame=false)
Called at the start of a frame to register the time we are looking to detect a hitch.
double GetCurrentTime ()
double GetFrameStartTime ()
bool IsStartedSuspended ()
Check if started suspended.
void PostFork ()
void Restart ()
void ResumeHeartBeat ()
Resume heartbeat hitch detection.
void Stop ()
void SuspendHeartBeat ()
Suspend heartbeat hitch detection.
Static Public Member Functions
static FUnixSignalGameHitchHeartBeat & Get ()
Gets the heartbeat singleton.
static FUnixSignalGameHitchHeartBeat * GetNoInit ()
Static Public Attributes
static FUnixSignalGameHitchHeartBeat * Singleton
Private Member Functions
FUnixSignalGameHitchHeartBeat ()
~FUnixSignalGameHitchHeartBeat ()
void Init ()
void InitSettings ()
Private Attributes
bool bDisabled = false
bool bHasCmdLine = false
bool bStartSuspended = false
bool bTimerCreated = false
double HitchThresholdS = -1.0
double StartTime = 0.0
int32 SuspendCount = 0
timer_t TimerId = 0
Detailed Description
Definition at line 9 of file UnixSignalHeartBeat.h.
Constructor & Destructor Documentation
FUnixSignalGameHitchHeartBeat()
FUnixSignalGameHitchHeartBeat::FUnixSignalGameHitchHeartBeat () private
Referenced by Get(), and GetNoInit().
~FUnixSignalGameHitchHeartBeat()
FUnixSignalGameHitchHeartBeat::~FUnixSignalGameHitchHeartBeat () private
Member Function Documentation
FrameStart()
void FUnixSignalGameHitchHeartBeat::FrameStart (bool bSkipThisFrame = false)
Called at the start of a frame to register the time we are looking to detect a hitch.
Get()
FUnixSignalGameHitchHeartBeat & FUnixSignalGameHitchHeartBeat::Get () static
Gets the heartbeat singleton.
References FUnixSignalGameHitchHeartBeat().
GetCurrentTime()
double FUnixSignalGameHitchHeartBeat::GetCurrentTime ()
GetFrameStartTime()
double FUnixSignalGameHitchHeartBeat::GetFrameStartTime ()
GetNoInit()
FUnixSignalGameHitchHeartBeat * FUnixSignalGameHitchHeartBeat::GetNoInit () static
References FUnixSignalGameHitchHeartBeat().
Init()
void FUnixSignalGameHitchHeartBeat::Init () private
InitSettings()
void FUnixSignalGameHitchHeartBeat::InitSettings () private
IsStartedSuspended()
bool FUnixSignalGameHitchHeartBeat::IsStartedSuspended ()
Check if started suspended.
PostFork()
void FUnixSignalGameHitchHeartBeat::PostFork ()
Restart()
void FUnixSignalGameHitchHeartBeat::Restart ()
ResumeHeartBeat()
void FUnixSignalGameHitchHeartBeat::ResumeHeartBeat ()
Resume heartbeat hitch detection.
Call only after first calling SuspendHeartBeat.
Stop()
void FUnixSignalGameHitchHeartBeat::Stop ()
SuspendHeartBeat()
void FUnixSignalGameHitchHeartBeat::SuspendHeartBeat ()
Suspend heartbeat hitch detection.
Must call ResumeHeartBeat later to resume.
Field Documentation
bDisabled
bool FUnixSignalGameHitchHeartBeat::bDisabled = false private
Definition at line 56 of file UnixSignalHeartBeat.h.
bHasCmdLine
bool FUnixSignalGameHitchHeartBeat::bHasCmdLine = false private
Definition at line 55 of file UnixSignalHeartBeat.h.
bStartSuspended
bool FUnixSignalGameHitchHeartBeat::bStartSuspended = false private
Definition at line 59 of file UnixSignalHeartBeat.h.
bTimerCreated
bool FUnixSignalGameHitchHeartBeat::bTimerCreated = false private
Definition at line 58 of file UnixSignalHeartBeat.h.
HitchThresholdS
double FUnixSignalGameHitchHeartBeat::HitchThresholdS = -1.0 private
Definition at line 53 of file UnixSignalHeartBeat.h.
Singleton
FUnixSignalGameHitchHeartBeat* FUnixSignalGameHitchHeartBeat::Singleton static
Definition at line 12 of file UnixSignalHeartBeat.h.
StartTime
double FUnixSignalGameHitchHeartBeat::StartTime = 0.0 private
Definition at line 54 of file UnixSignalHeartBeat.h.
SuspendCount
int32 FUnixSignalGameHitchHeartBeat::SuspendCount = 0 private
Definition at line 57 of file UnixSignalHeartBeat.h.
TimerId
timer_t FUnixSignalGameHitchHeartBeat::TimerId = 0 private
Definition at line 60 of file UnixSignalHeartBeat.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Unix/UnixSignalHeartBeat.h