Unreal Engine 5.6 C++ API: FPThreadSemaphore Class Reference
FPThreadSemaphore Class Reference
#include "PThreadSemaphore.h"
Public Member Functions
FPThreadSemaphore (int32 InitialCount, int32 MaxCount)
~FPThreadSemaphore ()
void Acquire ()
void Release (int32 Count=1)
bool TryAcquire (FTimespan Timeout=FTimespan::Zero())
UE_NONCOPYABLE (FPThreadSemaphore)
Private Attributes
sem_t Semaphore
Detailed Description
Definition at line 14 of file PThreadSemaphore.h.
Constructor & Destructor Documentation
FPThreadSemaphore()
FPThreadSemaphore::FPThreadSemaphore (int32 InitialCount, int32 MaxCount) inline
Definition at line 19 of file PThreadSemaphore.h.
References checkfSlow, Semaphore, and TEXT.
Referenced by UE_NONCOPYABLE().
~FPThreadSemaphore()
FPThreadSemaphore::~FPThreadSemaphore () inline
Definition at line 25 of file PThreadSemaphore.h.
References checkfSlow, Semaphore, and TEXT.
Member Function Documentation
Acquire()
void FPThreadSemaphore::Acquire () inline
Definition at line 31 of file PThreadSemaphore.h.
References checkfSlow, Semaphore, and TEXT.
Release()
void FPThreadSemaphore::Release (int32 Count = 1) inline
Definition at line 50 of file PThreadSemaphore.h.
References checkfSlow, Count, Semaphore, and TEXT.
TryAcquire()
bool FPThreadSemaphore::TryAcquire (FTimespan Timeout = FTimespan::Zero()) inline
Definition at line 37 of file PThreadSemaphore.h.
References checkfSlow, Semaphore, TEXT, Timeout, and FTimespan::Zero().
UE_NONCOPYABLE()
FPThreadSemaphore::UE_NONCOPYABLE (FPThreadSemaphore)
References FPThreadSemaphore().
Field Documentation
Semaphore
sem_t FPThreadSemaphore::Semaphore private
Definition at line 61 of file PThreadSemaphore.h.
Referenced by FPThreadSemaphore(), ~FPThreadSemaphore(), Acquire(), Release(), and TryAcquire().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/PThreadSemaphore.h