Unreal Engine 5.6 C++ API: UE::FManualResetEvent Class Reference
UE::FManualResetEvent Class Reference
A type of event that remains notified until manually reset.
#include "ManualResetEvent.h"
Public Member Functions
constexpr FManualResetEvent ()=default
FManualResetEvent (const FManualResetEvent &)=delete
bool IsNotified () const
Returns true if the event is notified, otherwise false.
void Notify ()
Notifies all waiting threads and leaves the event notified until the next call to Reset().
FManualResetEvent & operator= (const FManualResetEvent &)=delete
void Reset ()
Resets the event to a non-notified state.
void Wait ()
Wait until the event is notified.
bool WaitFor (FMonotonicTimeSpan WaitTime)
Wait until the event is notified.
bool WaitUntil (FMonotonicTimePoint WaitTime)
Wait until the event is notified.
Private Attributes
std::atomic< uint8 > State = 0
Static Private Attributes
static constexpr uint8 IsNotifiedFlag = 1 << 0
static constexpr uint8 MaybeWaitingFlag = 1 << 1
Detailed Description
A type of event that remains notified until manually reset.
Definition at line 14 of file ManualResetEvent.h.
Constructor & Destructor Documentation
FManualResetEvent() [1/2]
UE::FManualResetEvent::FManualResetEvent () constexpr default
Referenced by FManualResetEvent(), and operator=().
FManualResetEvent() [2/2]
UE::FManualResetEvent::FManualResetEvent (const FManualResetEvent &) delete
References FManualResetEvent().
Member Function Documentation
IsNotified()
bool UE::FManualResetEvent::IsNotified () const inline
Returns true if the event is notified, otherwise false.
Definition at line 25 of file ManualResetEvent.h.
References IsNotifiedFlag, and State.
Referenced by WaitFor().
Notify()
void UE::FManualResetEvent::Notify () inline
Notifies all waiting threads and leaves the event notified until the next call to Reset().
Definition at line 83 of file ManualResetEvent.h.
References IsNotifiedFlag, MaybeWaitingFlag, State, and UE::ParkingLot::WakeAll().
operator=()
FManualResetEvent & UE::FManualResetEvent::operator= (const FManualResetEvent &) delete
References FManualResetEvent().
Reset()
void UE::FManualResetEvent::Reset () inline
Resets the event to a non-notified state.
Definition at line 95 of file ManualResetEvent.h.
References IsNotifiedFlag, and State.
Wait()
void UE::FManualResetEvent::Wait () inline
Wait until the event is notified.
Definition at line 33 of file ManualResetEvent.h.
References UE::FMonotonicTimePoint::Infinity(), and WaitUntil().
WaitFor()
bool UE::FManualResetEvent::WaitFor (FMonotonicTimeSpan WaitTime) inline
Wait until the event is notified.
Parameters
WaitTime Relative time after which waiting is automatically canceled and the thread wakes.
Returns
True if the event was notified before the wait time elapsed, otherwise false.
Definition at line 44 of file ManualResetEvent.h.
References IsNotified(), UE::FMonotonicTimeSpan::IsZero(), UE::FMonotonicTimePoint::Now(), and WaitUntil().
WaitUntil()
bool UE::FManualResetEvent::WaitUntil (FMonotonicTimePoint WaitTime) inline
Wait until the event is notified.
Parameters
WaitTime Absolute time after which waiting is automatically canceled and the thread wakes.
Returns
True if the event was notified before the wait time elapsed, otherwise false.
Definition at line 55 of file ManualResetEvent.h.
References UE::FMonotonicTimePoint::IsInfinity(), IsNotifiedFlag, MaybeWaitingFlag, UE::FMonotonicTimePoint::Now(), State, and UE::ParkingLot::WaitUntil().
Referenced by Wait(), and WaitFor().
Field Documentation
IsNotifiedFlag
uint8 UE::FManualResetEvent::IsNotifiedFlag = 1 << 0 static constexpr private
Definition at line 101 of file ManualResetEvent.h.
Referenced by IsNotified(), Notify(), Reset(), and WaitUntil().
MaybeWaitingFlag
uint8 UE::FManualResetEvent::MaybeWaitingFlag = 1 << 1 static constexpr private
Definition at line 102 of file ManualResetEvent.h.
Referenced by Notify(), and WaitUntil().
State
std::atomic<uint8> UE::FManualResetEvent::State = 0 private
Definition at line 104 of file ManualResetEvent.h.
Referenced by IsNotified(), Notify(), Reset(), and WaitUntil().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/ManualResetEvent.h