Unreal Engine 5.6 C++ API: FFindReferencersArchive::FTargetObjectContainer Class Reference
FFindReferencersArchive::FTargetObjectContainer Class Reference
#include "FindReferencersArchive.h"
Public Member Functions
void AddObject (UObject *Object)
void Freeze ()
UObject * GetObject (int32 Index) const
int32 GetRefCount (int32 Index) const
int32 * GetRefCountPtr (UObject *Object)
int32 RefCountNum () const
void Reserve (int32 Num)
void ResetRefCounts ()
const int32 * TryGetRefCountPtr (UObject *Object) const
Private Member Functions
FORCEINLINE void CheckFrozen () const
FORCEINLINE void CheckUnfrozen () const
Private Attributes
bool bFrozen = false
TArray< int32 > RefCounts
TArray< UObject * > TargetObjects
Detailed Description
Definition at line 92 of file FindReferencersArchive.h.
Member Function Documentation
AddObject()
void FFindReferencersArchive::FTargetObjectContainer::AddObject (UObject * Object) inline
Definition at line 104 of file FindReferencersArchive.h.
References CheckUnfrozen(), Object, and TargetObjects.
CheckFrozen()
FORCEINLINE void FFindReferencersArchive::FTargetObjectContainer::CheckFrozen () const inline private
Definition at line 177 of file FindReferencersArchive.h.
References bFrozen, checkf, FORCEINLINE, and TEXT.
Referenced by GetRefCountPtr(), and TryGetRefCountPtr().
CheckUnfrozen()
FORCEINLINE void FFindReferencersArchive::FTargetObjectContainer::CheckUnfrozen () const inline private
Definition at line 182 of file FindReferencersArchive.h.
References bFrozen, checkf, FORCEINLINE, and TEXT.
Referenced by AddObject(), Freeze(), and Reserve().
Freeze()
void FFindReferencersArchive::FTargetObjectContainer::Freeze () inline
Definition at line 111 of file FindReferencersArchive.h.
References bFrozen, CheckUnfrozen(), ResetRefCounts(), Algo::Sort(), and TargetObjects.
GetObject()
UObject * FFindReferencersArchive::FTargetObjectContainer::GetObject (int32 Index) const inline
Definition at line 165 of file FindReferencersArchive.h.
References TargetObjects.
GetRefCount()
int32 FFindReferencersArchive::FTargetObjectContainer::GetRefCount (int32 Index) const inline
Definition at line 171 of file FindReferencersArchive.h.
References RefCounts.
GetRefCountPtr()
int32 * FFindReferencersArchive::FTargetObjectContainer::GetRefCountPtr (UObject * Object) inline
Definition at line 123 of file FindReferencersArchive.h.
References Algo::BinarySearch(), CheckFrozen(), INDEX_NONE, No, Object, RefCounts, and TargetObjects.
RefCountNum()
int32 FFindReferencersArchive::FTargetObjectContainer::RefCountNum () const inline
Definition at line 160 of file FindReferencersArchive.h.
References RefCounts.
Reserve()
void FFindReferencersArchive::FTargetObjectContainer::Reserve (int32 Num) inline
Definition at line 97 of file FindReferencersArchive.h.
References CheckUnfrozen(), Num, and TargetObjects.
ResetRefCounts()
void FFindReferencersArchive::FTargetObjectContainer::ResetRefCounts () inline
Definition at line 155 of file FindReferencersArchive.h.
References RefCounts, and TargetObjects.
Referenced by Freeze().
TryGetRefCountPtr()
const int32 * FFindReferencersArchive::FTargetObjectContainer::TryGetRefCountPtr (UObject * Object) const inline
Definition at line 142 of file FindReferencersArchive.h.
References Algo::BinarySearch(), CheckFrozen(), INDEX_NONE, Object, RefCounts, and TargetObjects.
Field Documentation
bFrozen
bool FFindReferencersArchive::FTargetObjectContainer::bFrozen = false private
Definition at line 187 of file FindReferencersArchive.h.
Referenced by CheckFrozen(), CheckUnfrozen(), and Freeze().
RefCounts
TArray<int32> FFindReferencersArchive::FTargetObjectContainer::RefCounts private
Definition at line 189 of file FindReferencersArchive.h.
Referenced by GetRefCount(), GetRefCountPtr(), RefCountNum(), ResetRefCounts(), and TryGetRefCountPtr().
TargetObjects
TArray<UObject*> FFindReferencersArchive::FTargetObjectContainer::TargetObjects private
Definition at line 188 of file FindReferencersArchive.h.
Referenced by AddObject(), Freeze(), GetObject(), GetRefCountPtr(), Reserve(), ResetRefCounts(), and TryGetRefCountPtr().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/FindReferencersArchive.h