Unreal Engine 5.6 C++ API: IDisplayClusterBlueprintAPI Class Reference
IDisplayClusterBlueprintAPI Class Reference abstract
Blueprint API interface.
#include "IDisplayClusterBlueprintAPI.h"
Public Member Functions
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual ADisplayClusterRootActor *GetRootActor() const =0
Returns DisplayCluster root actor.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual bool IsBackup() const =0
Returns true if current node is a backup node in a cluster.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual bool IsPrimary() const =0
Returns true if current node is a primary node in a cluster.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual bool IsSecondary() const =0
Returns true if current node is a secondary node in a cluster.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual EDisplayClusterNodeRole GetClusterRole() const =0
Returns the role of the current cluster node.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual FString GetNodeId() const =0
Returns Id of the current node in a cluster.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual int32 GetActiveNodesAmount() const =0
Returns amount of active nodes in a cluster.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void AddClusterEventListener(TScriptInterface< IDisplayClusterClusterEventListener > Listener)=0
Adds cluster event listener.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void EmitClusterEventBinary(const FDisplayClusterClusterEventBinary &Event
Emits binary cluster event.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void EmitClusterEventJson(const FDisplayClusterClusterEventJson &Event
Emits JSON cluster event.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void GetActiveNodeIds(TArray< FString > &OutNodeIds) const =0
Returns List of the active nodes in the runtime cluster node in a cluster.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void RemoveClusterEventListener(TScriptInterface< IDisplayClusterClusterEventListener > Listener)=0
Removes cluster event listener.
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void SendClusterEventBinaryTo(const FString &Address
Sends binary cluster event to a specific target (outside of the cluster).
UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual void SendClusterEventJsonTo(const FString &Address
Sends JSON cluster event to a specific target (outside of the cluster).
Data Fields
bool bPrimaryOnly = 0
const int32 const FDisplayClusterClusterEventJson bool bPrimaryOnly = 0
const int32 const FDisplayClusterClusterEventBinary bool bPrimaryOnly = 0
const int32 const FDisplayClusterClusterEventJson & Event
const int32 const FDisplayClusterClusterEventBinary & Event
const int32 Port
Private Member Functions
GENERATED_BODY() public UE_DEPRECATED (5.4, "This function has been moved to UDisplayClusterBlueprintLib.") UFUNCTION()) virtual EDisplayClusterOperationMode GetOperationMode() const =0
Returns current operation mode.
Detailed Description
Blueprint API interface.
Definition at line 38 of file IDisplayClusterBlueprintAPI.h.
Member Function Documentation
UE_DEPRECATED() [1/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns DisplayCluster root actor.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [2/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns true if current node is a backup node in a cluster.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [3/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns true if current node is a primary node in a cluster.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [4/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns true if current node is a secondary node in a cluster.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [5/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns the role of the current cluster node.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [6/15]
GENERATED_BODY() public IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const private pure virtual
Returns current operation mode.
References meta, and UFUNCTION.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [7/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns Id of the current node in a cluster.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [8/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const pure virtual
Returns amount of active nodes in a cluster.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [9/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") pure virtual
Adds cluster event listener.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [10/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const &
Emits binary cluster event.
References bPrimaryOnly, Event, meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [11/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const &
Emits JSON cluster event.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [12/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const & pure virtual
Returns List of the active nodes in the runtime cluster node in a cluster.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [13/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") pure virtual
Removes cluster event listener.
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [14/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const &
Sends binary cluster event to a specific target (outside of the cluster).
References meta, UE_DEPRECATED(), and UFUNCTION.
UE_DEPRECATED() [15/15]
IDisplayClusterBlueprintAPI::UE_DEPRECATED (5. 4, "This function has been moved to UDisplayClusterBlueprintLib.") const &
Sends JSON cluster event to a specific target (outside of the cluster).
References meta, UE_DEPRECATED(), and UFUNCTION.
Field Documentation
bPrimaryOnly [1/3]
bool IDisplayClusterBlueprintAPI::bPrimaryOnly = 0
Definition at line 111 of file IDisplayClusterBlueprintAPI.h.
Referenced by UE_DEPRECATED().
bPrimaryOnly [2/3]
const int32 const FDisplayClusterClusterEventJson bool IDisplayClusterBlueprintAPI::bPrimaryOnly = 0
Definition at line 121 of file IDisplayClusterBlueprintAPI.h.
bPrimaryOnly [3/3]
const int32 const FDisplayClusterClusterEventBinary bool IDisplayClusterBlueprintAPI::bPrimaryOnly = 0
Definition at line 126 of file IDisplayClusterBlueprintAPI.h.
Event [1/2]
const int32 const FDisplayClusterClusterEventJson& IDisplayClusterBlueprintAPI::Event
Definition at line 121 of file IDisplayClusterBlueprintAPI.h.
Referenced by UE_DEPRECATED().
Event [2/2]
const int32 const FDisplayClusterClusterEventBinary& IDisplayClusterBlueprintAPI::Event
Definition at line 126 of file IDisplayClusterBlueprintAPI.h.
Port
const int32 IDisplayClusterBlueprintAPI::Port
Definition at line 121 of file IDisplayClusterBlueprintAPI.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Blueprints/IDisplayClusterBlueprintAPI.h