Unreal Engine 5.6 C++ API: UInterpToMovementComponent Class Reference
UInterpToMovementComponent Class Reference
#include "InterpToMovementComponent.h"
Protected Member Functions
float CalculateNewTime (float TimeNow, float Delta, FHitResult &HitResult, bool InBroadcastEvent, bool &OutStopped, float &OutTimeRemainder)
virtual FVector ComputeMoveDelta (float Time) const
Compute the distance for the given time.
bool HandleHitWall (const FHitResult &Hit, float TimeTick, const FVector &MoveDelta)
virtual void HandleImpact (const FHitResult &Hit, float TimeSlice=0.f, const FVector &MoveDelta=FVector::ZeroVector) override
Deal with an impact.
void ReverseDirection (const FHitResult &Hit, float Time, bool InBroadcastEvent)
virtual void UpdateControlPoints (bool InForceUpdate)
Protected Attributes
bool bContainsActorControlPoints
bool bIsWaiting
bool bStopped
float CurrentDirection
float CurrentTime
float TimeMultiplier
Static Protected Attributes
static const float MIN_TICK_TIME
Minimum delta time considered when ticking.
Private Member Functions
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift) override
virtual void BeginPlay () override
virtual bool CheckStillInWorld ()
This will check to see if the InterpTo is still in the world.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToResetDelegate, const FHitResult &, ImpactResult, float, Time)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToStopDelegate, const FHitResult &, ImpactResult, float, Time)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToWaitBeginDelegate, const FHitResult &, ImpactResult, float, Time)
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToWaitEndDelegate, const FHitResult &, ImpactResult, float, Time)
GENERATED_UCLASS_BODY () DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnInterpToReverseDelegate
float GetSimulationTimeStep (float RemainingTime, int32 Iterations) const
Compute remaining time step given remaining time and current iterations.
bool HasStoppedSimulation ()
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual bool ShouldUseSubStepping () const
Determine whether or not to use substepping in the InterpTo motion update.
virtual void StopMovementImmediately () override
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
UFUNCTION () 1 virtual void AddControlPointPosition(FVector Pos
UFUNCTION () 1 void FinaliseControlPoints()
UFUNCTION () 1 void ResetControlPoints()
UFUNCTION () 1 void RestartMovement(float InitialDirection
UFUNCTION () 1 void StopSimulating(const FHitResult &HitResult)
Clears the reference to UpdatedComponent, fires stop event, and stops ticking.
UPROPERTY ()
Max time delta for each discrete simulation step.
UPROPERTY ()
Max number of iterations used for each discrete simulation step.
UPROPERTY () bool bCheckIfStillInWorld
UPROPERTY() uint32 bPauseOnImpact UPROPERTY () bool bSweep
If true, will pause movement on impact.
UPROPERTY () EInterpToBehaviourType BehaviourType
UPROPERTY () ETeleportType TeleportType
Physics teleport type.
UPROPERTY () float SpeedMultiplier
Change the speed of movement.
UPROPERTY () FOnInterpToResetDelegate OnResetDelegate
Called when InterpTo reached the end and reset back to start .
UPROPERTY() uint32 bForceSubStepping UPROPERTY () FOnInterpToReverseDelegate OnInterpToReverse
If true, forces sub-stepping to break up movement into discrete smaller steps to improve accuracy of the trajectory.
UPROPERTY () FOnInterpToStopDelegate OnInterpToStop
Called when InterpTo has come to a stop.
UPROPERTY () FOnInterpToWaitBeginDelegate OnWaitBeginDelegate
Called when InterpTo has come to a stop but will resume when possible.
UPROPERTY () FOnInterpToWaitEndDelegate OnWaitEndDelegate
Called when InterpTo has resumed following a stop.
UPROPERTY () TArray< FInterpControlPoint > ControlPoints
UPROPERTY ()) float Duration
Private Attributes
bool bPointsFinalized
bool bPositionIsRelative = true)
Category
const FHitResult float
const FHitResult ImpactResult
FVector StartLocation
const FHitResult Time
float TotalDistance
Detailed Description
Definition at line 66 of file InterpToMovementComponent.h.
Member Function Documentation
ApplyWorldOffset()
virtual void UInterpToMovementComponent::ApplyWorldOffset (const FVector & InOffset, bool bWorldShift) override private virtual
References ApplyWorldOffset(), and FVector.
Referenced by ApplyWorldOffset().
BeginPlay()
virtual void UInterpToMovementComponent::BeginPlay () override private virtual
References BeginPlay().
Referenced by BeginPlay().
CalculateNewTime()
float UInterpToMovementComponent::CalculateNewTime (float TimeNow, float Delta, FHitResult & HitResult, bool InBroadcastEvent, bool & OutStopped, float & OutTimeRemainder) protected
CheckStillInWorld()
virtual bool UInterpToMovementComponent::CheckStillInWorld () private virtual
This will check to see if the InterpTo is still in the world.
It will check things like the KillZ, outside world bounds, etc. and handle the situation.
References CheckStillInWorld().
Referenced by CheckStillInWorld().
ComputeMoveDelta()
virtual FVector UInterpToMovementComponent::ComputeMoveDelta (float Time) const protected virtual
Compute the distance for the given time.
References FVector, and Time.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams() [1/4]
UInterpToMovementComponent::DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToResetDelegate , const FHitResult & , ImpactResult , float , Time) private
References DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), ImpactResult, and Time.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams() [2/4]
UInterpToMovementComponent::DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToStopDelegate , const FHitResult & , ImpactResult , float , Time) private
References DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), ImpactResult, and Time.
Referenced by DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), and DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams().
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams() [3/4]
UInterpToMovementComponent::DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToWaitBeginDelegate , const FHitResult & , ImpactResult , float , Time) private
References DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), ImpactResult, and Time.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams() [4/4]
UInterpToMovementComponent::DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams (FOnInterpToWaitEndDelegate , const FHitResult & , ImpactResult , float , Time) private
References DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), ImpactResult, and Time.
GENERATED_UCLASS_BODY()
UInterpToMovementComponent::GENERATED_UCLASS_BODY () private
GetSimulationTimeStep()
float UInterpToMovementComponent::GetSimulationTimeStep (float RemainingTime, int32 Iterations) const private
Compute remaining time step given remaining time and current iterations.
The last iteration (limited by MaxSimulationIterations) always returns the remaining time, which may violate MaxSimulationTimeStep.
Parameters
RemainingTime Remaining time in the tick.
Iterations Current iteration of the tick (starting at 1).
Returns
The remaining time step to use for the next sub-step of iteration.
See also
MaxSimulationTimeStep, MaxSimulationIterations
ShouldUseSubStepping()
HandleHitWall()
bool UInterpToMovementComponent::HandleHitWall (const FHitResult & Hit, float TimeTick, const FVector & MoveDelta) protected
Returns
true if the simulation should stop.
References FVector.
HandleImpact()
virtual void UInterpToMovementComponent::HandleImpact (const FHitResult & Hit, float TimeSlice = 0.f, const FVector & MoveDelta = FVector::ZeroVector) override protected virtual
Deal with an impact.
Change direction, stop etc depending on the current behaviour setting.
References FVector, and UE::Math::TVector< double >::ZeroVector.
HasStoppedSimulation()
bool UInterpToMovementComponent::HasStoppedSimulation () inline private
Definition at line 149 of file InterpToMovementComponent.h.
References HasStoppedSimulation().
Referenced by HasStoppedSimulation().
PostEditChangeProperty()
virtual void UInterpToMovementComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
ReverseDirection()
void UInterpToMovementComponent::ReverseDirection (const FHitResult & Hit, float Time, bool InBroadcastEvent) protected
References Time.
ShouldUseSubStepping()
virtual bool UInterpToMovementComponent::ShouldUseSubStepping () const private virtual
Determine whether or not to use substepping in the InterpTo motion update.
If true, GetSimulationTimeStep() will be used to time-slice the update. If false, all remaining time will be used during the tick.
Returns
Whether or not to use substepping in the InterpTo motion update.
See also
GetSimulationTimeStep()
StopMovementImmediately()
virtual void UInterpToMovementComponent::StopMovementImmediately () override private virtual
References StopMovementImmediately().
Referenced by StopMovementImmediately().
TickComponent()
virtual void UInterpToMovementComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override private virtual
References DeltaTime, and TickComponent().
Referenced by TickComponent().
UFUNCTION() [1/5]
UInterpToMovementComponent::UFUNCTION () private
References Category.
UFUNCTION() [2/5]
UInterpToMovementComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [3/5]
UInterpToMovementComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [4/5]
UInterpToMovementComponent::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/5]
UInterpToMovementComponent::UFUNCTION () const & private
Clears the reference to UpdatedComponent, fires stop event, and stops ticking.
References Category, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UpdateControlPoints()
virtual void UInterpToMovementComponent::UpdateControlPoints (bool InForceUpdate) protected virtual
UPROPERTY() [1/14]
UInterpToMovementComponent::UPROPERTY () private
Max time delta for each discrete simulation step.
Lowering this value can address issues with fast-moving objects or complex collision scenarios, at the cost of performance.
WARNING: if (MaxSimulationTimeStep * MaxSimulationIterations) is too low for the min framerate, the last simulation step may exceed MaxSimulationTimeStep to complete the simulation.
See also
MaxSimulationIterations, bForceSubStepping
UPROPERTY() [2/14]
UInterpToMovementComponent::UPROPERTY () private
Max number of iterations used for each discrete simulation step.
Increasing this value can address issues with fast-moving objects or complex collision scenarios, at the cost of performance.
WARNING: if (MaxSimulationTimeStep * MaxSimulationIterations) is too low for the min framerate, the last simulation step may exceed MaxSimulationTimeStep to complete the simulation.
See also
MaxSimulationTimeStep, bForceSubStepping
References Category, and meta.
UPROPERTY() [3/14]
UInterpToMovementComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [4/14]
UPROPERTY() uint32 bPauseOnImpact UInterpToMovementComponent::UPROPERTY () private
If true, will pause movement on impact.
If false it will behave as if the end of the movement range was reached based on the BehaviourType. If true, will sweep for blocking collision during movement. If false, it will simply teleport to the next position and ignore collision.
References Category, and UPROPERTY().
UPROPERTY() [5/14]
UInterpToMovementComponent::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [6/14]
UInterpToMovementComponent::UPROPERTY () private
Physics teleport type.
References Category, None, and UPROPERTY().
UPROPERTY() [7/14]
UInterpToMovementComponent::UPROPERTY () private
Change the speed of movement.
References Category.
UPROPERTY() [8/14]
UInterpToMovementComponent::UPROPERTY () private
Called when InterpTo reached the end and reset back to start .
References UPROPERTY().
UPROPERTY() [9/14]
UPROPERTY() uint32 bForceSubStepping UInterpToMovementComponent::UPROPERTY () private
If true, forces sub-stepping to break up movement into discrete smaller steps to improve accuracy of the trajectory.
Objects that move in a straight line typically do not need to set this, as movement always uses continuous collision detection (sweeps) so collision is not missed. Sub-stepping is automatically enabled when under the effects of gravity or when homing towards a target.
See also
MaxSimulationTimeStep, MaxSimulationIterations Called when InterpTo impacts something and reverse is enabled.
References UPROPERTY().
UPROPERTY() [10/14]
UInterpToMovementComponent::UPROPERTY () private
Called when InterpTo has come to a stop.
References UPROPERTY().
UPROPERTY() [11/14]
UInterpToMovementComponent::UPROPERTY () private
Called when InterpTo has come to a stop but will resume when possible.
References UPROPERTY().
UPROPERTY() [12/14]
UInterpToMovementComponent::UPROPERTY () private
Called when InterpTo has resumed following a stop.
References UPROPERTY().
UPROPERTY() [13/14]
UInterpToMovementComponent::UPROPERTY () private
References Category, Control, and ControlPoints.
UPROPERTY() [14/14]
UInterpToMovementComponent::UPROPERTY () private
References Category, Control, Duration, meta, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Field Documentation
bContainsActorControlPoints
bool UInterpToMovementComponent::bContainsActorControlPoints protected
Definition at line 253 of file InterpToMovementComponent.h.
bIsWaiting
bool UInterpToMovementComponent::bIsWaiting protected
Definition at line 247 of file InterpToMovementComponent.h.
bPointsFinalized
bool UInterpToMovementComponent::bPointsFinalized private
Definition at line 268 of file InterpToMovementComponent.h.
bPositionIsRelative
bool UInterpToMovementComponent::bPositionIsRelative = true) private
Definition at line 203 of file InterpToMovementComponent.h.
bStopped
bool UInterpToMovementComponent::bStopped protected
Definition at line 250 of file InterpToMovementComponent.h.
Category
UInterpToMovementComponent::Category private
Initial value:
=Simulation)
    float MaxSimulationTimeStep
Definition at line 178 of file InterpToMovementComponent.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
CurrentDirection
float UInterpToMovementComponent::CurrentDirection protected
Definition at line 244 of file InterpToMovementComponent.h.
CurrentTime
float UInterpToMovementComponent::CurrentTime protected
Definition at line 238 of file InterpToMovementComponent.h.
float
const FHitResult UInterpToMovementComponent::float private
Definition at line 70 of file InterpToMovementComponent.h.
ImpactResult
const FHitResult UInterpToMovementComponent::ImpactResult private
Definition at line 70 of file InterpToMovementComponent.h.
Referenced by DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), and DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams().
MIN_TICK_TIME
const float UInterpToMovementComponent::MIN_TICK_TIME static protected
Minimum delta time considered when ticking.
Delta times below this are not considered. This is a very small non-zero positive value to avoid potential divide-by-zero in simulation code.
Definition at line 256 of file InterpToMovementComponent.h.
StartLocation
FVector UInterpToMovementComponent::StartLocation private
Definition at line 267 of file InterpToMovementComponent.h.
Time
const FHitResult UInterpToMovementComponent::Time private
Definition at line 70 of file InterpToMovementComponent.h.
Referenced by ComputeMoveDelta(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), and ReverseDirection().
TimeMultiplier
float UInterpToMovementComponent::TimeMultiplier protected
Definition at line 241 of file InterpToMovementComponent.h.
TotalDistance
float UInterpToMovementComponent::TotalDistance private
Definition at line 265 of file InterpToMovementComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/InterpToMovementComponent.h