Unreal Engine 5.6 C++ API: TExternalDirtyActorsTracker< StoreType > Class Template Reference
TExternalDirtyActorsTracker< StoreType > Class Template Reference
TExternalDirtyActorsTracker is a tracker for dirty external actors, with custom storage through the StoreType interface.
#include "ExternalDirtyActorsTracker.h"
Public Types
using MapType = TMap<TWeakObjectPtr<AActor>, typename StoreType::Type>
using Super = TExternalDirtyActorsTracker<StoreType>
Public Member Functions
TExternalDirtyActorsTracker (const ULevel *InLevel, typename StoreType::OwnerType *InOwner)
~TExternalDirtyActorsTracker ()
const MapType & GetDirtyActors () const
virtual bool OnAddDirtyActor (const TWeakObjectPtr< AActor > InActor)
Returns false if tracking this actor in unnecessary.
virtual void OnRemoveInvalidDirtyActor (const TWeakObjectPtr< AActor > InActor, typename StoreType::Type &InValue)
virtual void OnRemoveNonDirtyActor (const TWeakObjectPtr< AActor > InActor, typename StoreType::Type &InValue)
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Protected Member Functions
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
void OnEditorActorReplaced (AActor *InOldActor, AActor *InNewActor)
void OnObjectsReplaced (const TMap< UObject *, UObject * > &OldToNewObjectMap)
void OnPackageDirtyStateChanged (UPackage *InPackage)
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
Protected Attributes
MapType DirtyActors
const ULevel * Level
StoreType::OwnerType * Owner
Additional Inherited Members
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
template<typename StoreType>
class TExternalDirtyActorsTracker< StoreType >
TExternalDirtyActorsTracker is a tracker for dirty external actors, with custom storage through the StoreType interface.
Definition at line 18 of file ExternalDirtyActorsTracker.h.
Member Typedef Documentation
MapType
template<typename StoreType> using TExternalDirtyActorsTracker< StoreType >::MapType = TMap<TWeakObjectPtr<AActor>, typename StoreType::Type>
Definition at line 22 of file ExternalDirtyActorsTracker.h.
Super
template<typename StoreType> using TExternalDirtyActorsTracker< StoreType >::Super = TExternalDirtyActorsTracker<StoreType>
Definition at line 21 of file ExternalDirtyActorsTracker.h.
Constructor & Destructor Documentation
TExternalDirtyActorsTracker()
template<typename StoreType> TExternalDirtyActorsTracker< StoreType >::TExternalDirtyActorsTracker (const ULevel * InLevel, typename StoreType::OwnerType * InOwner) inline
Definition at line 24 of file ExternalDirtyActorsTracker.h.
References Level, FEditorDelegates::OnEditorActorReplaced, OnEditorActorReplaced(), FCoreUObjectDelegates::OnObjectsReplaced, OnObjectsReplaced(), OnPackageDirtyStateChanged(), Owner, and UPackage::PackageDirtyStateChangedEvent.
~TExternalDirtyActorsTracker()
template<typename StoreType> TExternalDirtyActorsTracker< StoreType >::~TExternalDirtyActorsTracker () inline
Definition at line 33 of file ExternalDirtyActorsTracker.h.
References FEditorDelegates::OnEditorActorReplaced, FCoreUObjectDelegates::OnObjectsReplaced, and UPackage::PackageDirtyStateChangedEvent.
Member Function Documentation
GetDirtyActors()
template<typename StoreType> const MapType & TExternalDirtyActorsTracker< StoreType >::GetDirtyActors () const inline
Definition at line 40 of file ExternalDirtyActorsTracker.h.
References DirtyActors.
GetStatId()
template<typename StoreType> virtual TStatId TExternalDirtyActorsTracker< StoreType >::GetStatId () const inline override protected virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
Definition at line 109 of file ExternalDirtyActorsTracker.h.
OnAddDirtyActor()
template<typename StoreType> virtual bool TExternalDirtyActorsTracker< StoreType >::OnAddDirtyActor (const TWeakObjectPtr< AActor > InActor) inline virtual
Returns false if tracking this actor in unnecessary.
Definition at line 43 of file ExternalDirtyActorsTracker.h.
Referenced by OnPackageDirtyStateChanged().
OnEditorActorReplaced()
template<typename StoreType> void TExternalDirtyActorsTracker< StoreType >::OnEditorActorReplaced (AActor * InOldActor, AActor * InNewActor) inline protected
Definition at line 97 of file ExternalDirtyActorsTracker.h.
References DirtyActors, and Value.
Referenced by TExternalDirtyActorsTracker(), and OnObjectsReplaced().
OnObjectsReplaced()
template<typename StoreType> void TExternalDirtyActorsTracker< StoreType >::OnObjectsReplaced (const TMap< UObject *, UObject * > & OldToNewObjectMap) inline protected
Definition at line 83 of file ExternalDirtyActorsTracker.h.
References Cast(), NewObject(), and OnEditorActorReplaced().
Referenced by TExternalDirtyActorsTracker().
OnPackageDirtyStateChanged()
template<typename StoreType> void TExternalDirtyActorsTracker< StoreType >::OnPackageDirtyStateChanged (UPackage * InPackage) inline protected
Definition at line 48 of file ExternalDirtyActorsTracker.h.
References Actor, DirtyActors, UPackage::IsDirty(), IsValid(), Level, OnAddDirtyActor(), OnRemoveInvalidDirtyActor(), OnRemoveNonDirtyActor(), Owner, and Value.
Referenced by TExternalDirtyActorsTracker().
OnRemoveInvalidDirtyActor()
template<typename StoreType> virtual void TExternalDirtyActorsTracker< StoreType >::OnRemoveInvalidDirtyActor (const TWeakObjectPtr< AActor > InActor, typename StoreType::Type & InValue) inline virtual
Definition at line 44 of file ExternalDirtyActorsTracker.h.
Referenced by OnPackageDirtyStateChanged(), and Tick().
OnRemoveNonDirtyActor()
template<typename StoreType> virtual void TExternalDirtyActorsTracker< StoreType >::OnRemoveNonDirtyActor (const TWeakObjectPtr< AActor > InActor, typename StoreType::Type & InValue) inline virtual
Definition at line 45 of file ExternalDirtyActorsTracker.h.
Referenced by OnPackageDirtyStateChanged(), and Tick().
Tick()
template<typename StoreType> virtual void TExternalDirtyActorsTracker< StoreType >::Tick (float DeltaTime) inline override protected virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
Definition at line 114 of file ExternalDirtyActorsTracker.h.
References DeltaTime, DirtyActors, OnRemoveInvalidDirtyActor(), and OnRemoveNonDirtyActor().
Field Documentation
DirtyActors
template<typename StoreType> MapType TExternalDirtyActorsTracker< StoreType >::DirtyActors protected
Definition at line 137 of file ExternalDirtyActorsTracker.h.
Referenced by GetDirtyActors(), OnEditorActorReplaced(), OnPackageDirtyStateChanged(), and Tick().
Level
template<typename StoreType> const ULevel* TExternalDirtyActorsTracker< StoreType >::Level protected
Definition at line 135 of file ExternalDirtyActorsTracker.h.
Referenced by TExternalDirtyActorsTracker(), and OnPackageDirtyStateChanged().
Owner
template<typename StoreType> StoreType::OwnerType* TExternalDirtyActorsTracker< StoreType >::Owner protected
Definition at line 136 of file ExternalDirtyActorsTracker.h.
Referenced by TExternalDirtyActorsTracker(), and OnPackageDirtyStateChanged().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ExternalDirtyActorsTracker.h