Unreal Engine 5.6 C++ API: UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize > Class Template Reference
UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize > Class Template Reference
Compute discretely-sampled (ie gridded) signed distance field for a mesh The basic approach is, first compute exact Distances in a narrow band, and then extend out to rest of Grid using fast "sweeping" (ie like a distance transform).
#include "SweepingMeshSDF.h"
Public Types
using CellSizeType = std::conditional_t<bScalarCellSize, float, FVector3f>
using CellSizeTyped = std::conditional_t<bScalarCellSize, double, FVector3d>
enum EComputeModes { FullGrid = 0 , NarrowBandOnly = 1 , NarrowBand_SpatialFloodFill = 2 }
enum EInsideModes { CrossingCount = 0 , WindingCount = 1 }
Public Member Functions
TSweepingMeshSDF (const TriangleMeshType *Mesh=nullptr, CellSizeType InCellSize=UnitCellSize(), TMeshAABBTree3< TriangleMeshType > *Spatial=nullptr)
float At (int I, int J, int K) const
FVector3f CellCenter (int I, int J, int K) const
bool Compute (FAxisAlignedBox3d Bounds)
Compute the SDF enclosing the given bounds, with a 'safe' buffer zone.
bool Compute (FVector3f InGridOrigin, FVector3i InDimensions)
Compute the SDF with exactly specified grid origin and dimensions.
FVector3i Dimensions () const
void Empty ()
Empty out all computed result data (leaves input data alone)
const FDenseGrid3i & GetClosestTriGrid () const
const FDenseGrid3i & GetIntersectionsGrid () const
float GetValue (FVector3i Idx) const
template<typename InterpolantRealType = double>
TTriLinearGridInterpolant< FDenseGrid3f, InterpolantRealType, bScalarCellSize > MakeInterpolant ()
float operator[] (const FVector3i &Idx) const
void SetCellSize (float InCellSize)
bool Validate (const FAxisAlignedBox3d &Bounds)
Static Public Member Functions
static FORCEINLINE float GetDiagLength (CellSizeType CellSize)
static FORCEINLINE float GetDim (CellSizeType CellSize, int32 Axis)
static FORCEINLINE double GetDim (CellSizeTyped CellSize, int32 Axis)
static FORCEINLINE bool IsValid (CellSizeType CellSize)
static int Orientation (double X1, double Y1, double X2, double Y2, double &TwiceSignedArea)
static bool PointInTriangle2d (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3, double &A, double &B, double &C)
static double PointSegmentDistance (const FVector3d &x0, const FVector3d &x1, const FVector3d &x2)
static float PointSegmentDistance (const FVector3f &x0, const FVector3f &x1, const FVector3f &x2)
static double PointTriangleDistance (const FVector3d &x0, const FVector3d &x1, const FVector3d &x2, const FVector3d &x3)
static float PointTriangleDistance (const FVector3f &x0, const FVector3f &x1, const FVector3f &x2, const FVector3f &x3)
static bool ShouldUseSpatial (int ExactCells, double CellSize, double AvgEdgeLen)
Encodes heuristic for deciding whether it will be faster to use.
static CellSizeType UnitCellSize ()
Data Fields
int ApproxMaxCellsPerDimension = 4096
bool bComputeSigns = true
bool bUseParallel = true
bool bWantClosestTriGrid = false
bool bWantIntersectionsGrid = false
TFunction< bool()> CancelF
if this function returns true, we should abort calculation
CellSizeType CellSize
EComputeModes ComputeMode = EComputeModes::NarrowBandOnly
int ExactBandWidth = 1
FVector3d ExpandBounds = FVector3d::Zero()
FDenseGrid3f Grid
FVector3f GridOrigin
EInsideModes InsideMode = EInsideModes::WindingCount
const TriangleMeshType * Mesh
double NarrowBandMaxDistance = 0
TMeshAABBTree3< TriangleMeshType > * Spatial
Protected Attributes
FDenseGrid3i ClosestTriGrid
FDenseGrid3i IntersectionsGrid
Private Member Functions
FVector3f cell_center (FVector3i IJK) const
float cell_tri_dist (const FVector3i &Idx, int TID) const
void check_neighbour (FDenseGrid3f &phi, FDenseGrid3i &closest_tri, const FVector3d &gx, int i0, int j0, int k0, int i1, int j1, int k1)
void CleanupUnwanted ()
void compute_intersections (FVector3f Origin, CellSizeType DX, int32 NI, int32 NJ, int32 NK, FDenseGrid3i &IntersectionCount)
void compute_signs (int NI, int NJ, int NK, FDenseGrid3f &Distances, FDenseGrid3i &IntersectionCount)
void make_level_set3 (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f &Distances, int ExactBand)
void make_level_set3_parallel (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f &Distances, int ExactBand)
void make_level_set3_parallel_floodfill (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f &Distances)
void make_level_set3_parallel_spatial (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f &Distances, int ExactBand)
void sweep (FDenseGrid3f &phi, FDenseGrid3i &closest_tri, FVector3f Origin, CellSizeType DX, int di, int dj, int dk)
void sweep_pass (FVector3f Origin, CellSizeType DX, FDenseGrid3f &Distances, FDenseGrid3i &closest_tri)
float upper_bound (const FDenseGrid3f &GridIn) const
Detailed Description
template<class TriangleMeshType, bool bScalarCellSize = true>
class UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >
Compute discretely-sampled (ie gridded) signed distance field for a mesh The basic approach is, first compute exact Distances in a narrow band, and then extend out to rest of Grid using fast "sweeping" (ie like a distance transform).
The resulting unsigned Grid is then signed using ray-intersection counting, which is also computed on the Grid, so no BVH is necessary
If you set ComputeMode to NarrowBandOnly, result is a narrow-band signed distance field. This is quite a bit faster as the sweeping is the most computationally-intensive step.
You can optionally provide a spatial data structure to allow faster computation of narrow-band Distances; this is most beneficial if we want a wider band
Caveats:
the "narrow band" is based on triangle bounding boxes, so it is not necessarily that "narrow" if you have large triangles on a diagonal to Grid axes
TODO: a number of utility function could & should be shared between this and CachingMeshSDF!
This code is based on the implementation found at https://github.com/christopherbatty/SDFGen
Definition at line 45 of file SweepingMeshSDF.h.
Member Typedef Documentation
CellSizeType
template<class TriangleMeshType, bool bScalarCellSize = true> using UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::CellSizeType = std::conditional_t<bScalarCellSize, float, FVector3f>
Definition at line 50 of file SweepingMeshSDF.h.
CellSizeTyped
template<class TriangleMeshType, bool bScalarCellSize = true> using UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::CellSizeTyped = std::conditional_t<bScalarCellSize, double, FVector3d>
Definition at line 52 of file SweepingMeshSDF.h.
Member Enumeration Documentation
EComputeModes
template<class TriangleMeshType, bool bScalarCellSize = true> enum UE::Geometry::TSweepingMeshSDF::EComputeModes
Enumerator
FullGrid
NarrowBandOnly
NarrowBand_SpatialFloodFill
Definition at line 86 of file SweepingMeshSDF.h.
EInsideModes
template<class TriangleMeshType, bool bScalarCellSize = true> enum UE::Geometry::TSweepingMeshSDF::EInsideModes
Enumerator
CrossingCount
WindingCount
Definition at line 109 of file SweepingMeshSDF.h.
Constructor & Destructor Documentation
TSweepingMeshSDF()
template<class TriangleMeshType, bool bScalarCellSize = true> UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::TSweepingMeshSDF (const TriangleMeshType * Mesh = nullptr, CellSizeType InCellSize = UnitCellSize(), TMeshAABBTree3< TriangleMeshType > * Spatial = nullptr) inline
Parameters
Mesh Triangle mesh to build an SDF around
InCellSize Spacing between Grid points
Spatial Optional AABB tree; note it must be provided if ComputeMode is set to NarrowBand_SpatialFloodFill
Definition at line 147 of file SweepingMeshSDF.h.
References CellSize, GridOrigin, Mesh, and Spatial.
Member Function Documentation
At()
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::At (int I, int J, int K) const inline
Definition at line 328 of file SweepingMeshSDF.h.
References Grid.
cell_center()
template<class TriangleMeshType, bool bScalarCellSize = true> FVector3f UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::cell_center (FVector3i IJK) const inline private
Definition at line 349 of file SweepingMeshSDF.h.
References CellSize, GetDim(), GridOrigin, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by cell_tri_dist(), CellCenter(), and make_level_set3_parallel_floodfill().
cell_tri_dist()
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::cell_tri_dist (const FVector3i & Idx, int TID) const inline private
Definition at line 361 of file SweepingMeshSDF.h.
References cell_center(), Mesh, and PointTriangleDistance().
CellCenter()
template<class TriangleMeshType, bool bScalarCellSize = true> FVector3f UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::CellCenter (int I, int J, int K) const inline
Definition at line 338 of file SweepingMeshSDF.h.
References cell_center().
check_neighbour()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::check_neighbour (FDenseGrid3f & phi, FDenseGrid3i & closest_tri, const FVector3d & gx, int i0, int j0, int k0, int i1, int j1, int k1) inline private
Definition at line 1075 of file SweepingMeshSDF.h.
References UE::Geometry::TDenseGrid3< ElemType >::At(), float, Mesh, and PointTriangleDistance().
Referenced by sweep().
CleanupUnwanted()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::CleanupUnwanted () inline private
Definition at line 1002 of file SweepingMeshSDF.h.
References bWantClosestTriGrid, bWantIntersectionsGrid, ClosestTriGrid, IntersectionsGrid, and Yes.
Referenced by Compute().
Compute() [1/2]
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute (FAxisAlignedBox3d Bounds) inline
Compute the SDF enclosing the given bounds, with a 'safe' buffer zone.
Parameters
Bounds Bounding box for the mesh data (passed as param it is usually already available, depending on TriangleMeshType and whether an AABB tree was provided)
Returns
false if cancelled or failed (e.g. due to invalid arguments); true otherwise
Definition at line 207 of file SweepingMeshSDF.h.
References ApproxMaxCellsPerDimension, CellSize, Compute, ComputeMode, UE::Geometry::TAxisAlignedBox3< RealType >::Diagonal(), ensure, ensureMsgf, ExactBandWidth, ExpandBounds, float, GetDim(), IsValid(), FMath::Max, UE::Geometry::TAxisAlignedBox3< RealType >::Max, UE::Geometry::VectorUtil::Max3Index(), UE::Geometry::TAxisAlignedBox3< RealType >::Min, NarrowBand_SpatialFloodFill, NarrowBandMaxDistance, UE::Math::TVector< float >::One(), TEXT, Validate(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Compute() [2/2]
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute (FVector3f InGridOrigin, FVector3i InDimensions) inline
Compute the SDF with exactly specified grid origin and dimensions.
Parameters
InGridOrigin Origin of the output grid
InDimensions Dimensions of the output grid
Returns
false if cancelled or failed (e.g. due to invalid arguments); true otherwise
Definition at line 264 of file SweepingMeshSDF.h.
References bUseParallel, CancelF, CellSize, CleanupUnwanted(), ComputeMode, ensureMsgf, ExactBandWidth, Grid, GridOrigin, make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), make_level_set3_parallel_spatial(), NarrowBand_SpatialFloodFill, NarrowBandMaxDistance, Spatial, TEXT, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
compute_intersections()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections (FVector3f Origin, CellSizeType DX, int32 NI, int32 NJ, int32 NK, FDenseGrid3i & IntersectionCount) inline private
Definition at line 1093 of file SweepingMeshSDF.h.
References A, UE::Geometry::DenseGrid::AtomicIncDec(), B, CancelF, FMath::Clamp(), GetDim(), InsideMode, FMath::Max3(), Mesh, FMath::Min3(), UE::Geometry::VectorUtil::NormalDirection(), UE::Geometry::Origin, ParallelFor(), PointInTriangle2d(), UnitCellSize(), WindingCount, UE::Math::TVector< T >::X, and UE::Math::TVector< double >::Zero().
Referenced by make_level_set3().
compute_signs()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_signs (int NI, int NJ, int NK, FDenseGrid3f & Distances, FDenseGrid3i & IntersectionCount) inline private
Definition at line 1175 of file SweepingMeshSDF.h.
References UE::Geometry::TDenseGrid3< ElemType >::At(), bUseParallel, CancelF, CrossingCount, InsideMode, ParallelFor(), and WindingCount.
Referenced by make_level_set3().
Dimensions()
template<class TriangleMeshType, bool bScalarCellSize = true> FVector3i UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Dimensions () const inline
Definition at line 311 of file SweepingMeshSDF.h.
References Grid.
Referenced by MakeInterpolant().
Empty()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Empty () inline
Empty out all computed result data (leaves input data alone)
Definition at line 154 of file SweepingMeshSDF.h.
References ClosestTriGrid, Grid, IntersectionsGrid, and Yes.
GetClosestTriGrid()
template<class TriangleMeshType, bool bScalarCellSize = true> const FDenseGrid3i & UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GetClosestTriGrid () const inline
Definition at line 317 of file SweepingMeshSDF.h.
References bWantClosestTriGrid, checkf, ClosestTriGrid, and TEXT.
GetDiagLength()
template<class TriangleMeshType, bool bScalarCellSize = true> FORCEINLINE float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GetDiagLength (CellSizeType CellSize) inline static
Definition at line 1417 of file SweepingMeshSDF.h.
References CellSize, FORCEINLINE, and TMathUtilConstants< float >::Sqrt3.
GetDim() [1/2]
template<class TriangleMeshType, bool bScalarCellSize = true> FORCEINLINE float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GetDim (CellSizeType CellSize, int32 Axis) inline static
Definition at line 1406 of file SweepingMeshSDF.h.
References Axis, CellSize, and FORCEINLINE.
GetDim() [2/2]
template<class TriangleMeshType, bool bScalarCellSize = true> FORCEINLINE double UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GetDim (CellSizeTyped CellSize, int32 Axis) inline static
Definition at line 1395 of file SweepingMeshSDF.h.
References Axis, CellSize, and FORCEINLINE.
Referenced by cell_center(), Compute(), compute_intersections(), make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), make_level_set3_parallel_spatial(), sweep(), and upper_bound().
GetIntersectionsGrid()
template<class TriangleMeshType, bool bScalarCellSize = true> const FDenseGrid3i & UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GetIntersectionsGrid () const inline
Definition at line 322 of file SweepingMeshSDF.h.
References bWantIntersectionsGrid, checkf, IntersectionsGrid, and TEXT.
GetValue()
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GetValue (FVector3i Idx) const inline
Definition at line 343 of file SweepingMeshSDF.h.
References Grid.
IsValid()
template<class TriangleMeshType, bool bScalarCellSize = true> FORCEINLINE bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::IsValid (CellSizeType CellSize) inline static
Definition at line 1428 of file SweepingMeshSDF.h.
References CellSize, and FORCEINLINE.
make_level_set3()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3 (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f & Distances, int ExactBand) inline private
Definition at line 370 of file SweepingMeshSDF.h.
References UE::Geometry::TDenseGrid3< ElemType >::Assign(), UE::Geometry::TDenseGrid3< ElemType >::At(), bComputeSigns, bWantClosestTriGrid, bWantIntersectionsGrid, CancelF, FMath::Clamp(), ClosestTriGrid, compute_intersections(), compute_signs(), ComputeMode, float, FullGrid, GetDim(), IntersectionsGrid, FMath::Max3(), Mesh, FMath::Min3(), UE::Geometry::Origin, PointTriangleDistance(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), sweep_pass(), upper_bound(), and Yes.
Referenced by Compute().
make_level_set3_parallel()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f & Distances, int ExactBand) inline private
Definition at line 489 of file SweepingMeshSDF.h.
References UE::Geometry::TDenseGrid3< ElemType >::Assign(), UE::Geometry::TDenseGrid3< ElemType >::At(), CancelF, FMath::Clamp(), ClosestTriGrid, float, GetDim(), Grid, IntersectionsGrid, FMath::Max3(), Mesh, FMath::Min3(), UE::Geometry::Origin, ParallelFor(), PointTriangleDistance(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), UnitCellSize(), upper_bound(), and UE::Math::TVector< double >::Zero().
Referenced by Compute().
make_level_set3_parallel_floodfill()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f & Distances) inline private
Definition at line 772 of file SweepingMeshSDF.h.
References Add, TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::TDenseGrid3< ElemType >::Assign(), bUseParallel, CancelF, cell_center(), checkSlow, FMath::Clamp(), ClosestTriGrid, float, GetDim(), IntersectionsGrid, MAX_int32, Mesh, UE::Geometry::Origin, ParallelFor(), TArray< InElementType, InAllocatorType >::Reset(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), TArray< InElementType, InAllocatorType >::SetNum(), TArray< InElementType, InAllocatorType >::SetNumZeroed(), UE::Geometry::TDenseGrid3< ElemType >::Size(), Spatial, TMathUtil< double >::Sqrt(), UE::Geometry::TDenseGrid3< ElemType >::ToLinear(), TRACE_CPUPROFILER_EVENT_SCOPE, UnitCellSize(), upper_bound(), Value, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by Compute().
make_level_set3_parallel_spatial()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial (FVector3f Origin, CellSizeType DX, int NI, int NJ, int NK, FDenseGrid3f & Distances, int ExactBand) inline private
Definition at line 621 of file SweepingMeshSDF.h.
References UE::Geometry::TDenseGrid3< ElemType >::Assign(), UE::Geometry::TDenseGrid3< ElemType >::At(), CancelF, FMath::Clamp(), ClosestTriGrid, GetDim(), IntersectionsGrid, FMath::Max3(), Mesh, FMath::Min3(), UE::Geometry::Origin, ParallelFor(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), UnitCellSize(), upper_bound(), and UE::Math::TVector< double >::Zero().
Referenced by Compute().
MakeInterpolant()
template<class TriangleMeshType, bool bScalarCellSize = true> template<typename InterpolantRealType = double> TTriLinearGridInterpolant< FDenseGrid3f, InterpolantRealType, bScalarCellSize > UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::MakeInterpolant () inline
Definition at line 163 of file SweepingMeshSDF.h.
References CellSize, Dimensions(), Grid, and GridOrigin.
operator[]()
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::operator[] (const FVector3i & Idx) const inline
Definition at line 333 of file SweepingMeshSDF.h.
References Grid.
Orientation()
template<class TriangleMeshType, bool bScalarCellSize = true> int UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Orientation (double X1, double Y1, double X2, double Y2, double & TwiceSignedArea) inline static
Definition at line 1245 of file SweepingMeshSDF.h.
Referenced by PointInTriangle2d().
PointInTriangle2d()
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointInTriangle2d (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3, double & A, double & B, double & C) inline static
Definition at line 1260 of file SweepingMeshSDF.h.
References A, B, checkf, Orientation(), and TEXT.
Referenced by compute_intersections().
PointSegmentDistance() [1/2]
template<class TriangleMeshType, bool bScalarCellSize = true> double UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointSegmentDistance (const FVector3d & x0, const FVector3d & x1, const FVector3d & x2) inline static
Definition at line 1303 of file SweepingMeshSDF.h.
References Distance, UE::Math::TVector< T >::Dot(), and UE::Math::TVector< T >::SquaredLength().
PointSegmentDistance() [2/2]
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointSegmentDistance (const FVector3f & x0, const FVector3f & x1, const FVector3f & x2) inline static
Definition at line 1283 of file SweepingMeshSDF.h.
References Distance, UE::Math::TVector< T >::Dot(), and UE::Math::TVector< T >::SquaredLength().
Referenced by PointTriangleDistance(), and PointTriangleDistance().
PointTriangleDistance() [1/2]
template<class TriangleMeshType, bool bScalarCellSize = true> double UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance (const FVector3d & x0, const FVector3d & x1, const FVector3d & x2, const FVector3d & x3) inline static
Definition at line 1360 of file SweepingMeshSDF.h.
References Distance, UE::Math::TVector< T >::Dot(), FMath::Max, FMath::Min, PointSegmentDistance(), and UE::Math::TVector< T >::SquaredLength().
PointTriangleDistance() [2/2]
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance (const FVector3f & x0, const FVector3f & x1, const FVector3f & x2, const FVector3f & x3) inline static
Definition at line 1324 of file SweepingMeshSDF.h.
References Distance, UE::Math::TVector< T >::Dot(), FMath::Max, FMath::Min, PointSegmentDistance(), and UE::Math::TVector< T >::SquaredLength().
Referenced by cell_tri_dist(), check_neighbour(), make_level_set3(), and make_level_set3_parallel().
SetCellSize()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::SetCellSize (float InCellSize) inline
Definition at line 62 of file SweepingMeshSDF.h.
References CellSize.
ShouldUseSpatial()
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::ShouldUseSpatial (int ExactCells, double CellSize, double AvgEdgeLen) inline static
Encodes heuristic for deciding whether it will be faster to use.
NarrowBand_SpatialFloodFill
Or NarrowBandOnly The heuristic is to use the Spatial method unless you have relatively long edges relative to the width of the narrow band. For a 1-cell wide band, or one where few triangles interact w/ each cell in the band the spatial overhead will probably not be worthwhile. TODO: test and tune this ...
Definition at line 178 of file SweepingMeshSDF.h.
References CellSize.
sweep()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::sweep (FDenseGrid3f & phi, FDenseGrid3i & closest_tri, FVector3f Origin, CellSizeType DX, int di, int dj, int dk) inline private
Definition at line 1039 of file SweepingMeshSDF.h.
References CancelF, check_neighbour(), GetDim(), UE::Geometry::TDenseGrid3< ElemType >::GetDimensions(), UE::Geometry::Origin, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by sweep_pass().
sweep_pass()
template<class TriangleMeshType, bool bScalarCellSize = true> void UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::sweep_pass (FVector3f Origin, CellSizeType DX, FDenseGrid3f & Distances, FDenseGrid3i & closest_tri) inline private
Definition at line 1018 of file SweepingMeshSDF.h.
References CancelF, UE::Geometry::Origin, and sweep().
Referenced by make_level_set3().
UnitCellSize()
template<class TriangleMeshType, bool bScalarCellSize = true> CellSizeType UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::UnitCellSize () inline static
Definition at line 54 of file SweepingMeshSDF.h.
Referenced by compute_intersections(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), and make_level_set3_parallel_spatial().
upper_bound()
template<class TriangleMeshType, bool bScalarCellSize = true> float UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::upper_bound (const FDenseGrid3f & GridIn) const inline private
Definition at line 356 of file SweepingMeshSDF.h.
References CellSize, float, GetDim(), UE::Geometry::TDenseGrid3< ElemType >::GetDimensions(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), and make_level_set3_parallel_spatial().
Validate()
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Validate (const FAxisAlignedBox3d & Bounds) inline
Definition at line 185 of file SweepingMeshSDF.h.
References ApproxMaxCellsPerDimension, CellSize, UE::Geometry::TAxisAlignedBox3< RealType >::IsEmpty(), IsValid(), and UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim().
Referenced by Compute().
Field Documentation
ApproxMaxCellsPerDimension
template<class TriangleMeshType, bool bScalarCellSize = true> int UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::ApproxMaxCellsPerDimension = 4096
Definition at line 79 of file SweepingMeshSDF.h.
Referenced by Compute(), and Validate().
bComputeSigns
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::bComputeSigns = true
Definition at line 101 of file SweepingMeshSDF.h.
Referenced by make_level_set3().
bUseParallel
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::bUseParallel = true
Definition at line 76 of file SweepingMeshSDF.h.
Referenced by Compute(), compute_signs(), and make_level_set3_parallel_floodfill().
bWantClosestTriGrid
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::bWantClosestTriGrid = false
Definition at line 118 of file SweepingMeshSDF.h.
Referenced by CleanupUnwanted(), GetClosestTriGrid(), and make_level_set3().
bWantIntersectionsGrid
template<class TriangleMeshType, bool bScalarCellSize = true> bool UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::bWantIntersectionsGrid = false
Definition at line 121 of file SweepingMeshSDF.h.
Referenced by CleanupUnwanted(), GetIntersectionsGrid(), and make_level_set3().
CancelF
template<class TriangleMeshType, bool bScalarCellSize = true> TFunction<bool()> UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::CancelF
Initial value:
= []()
    {
        return false;
    }
if this function returns true, we should abort calculation
Definition at line 124 of file SweepingMeshSDF.h.
Referenced by Compute(), compute_intersections(), compute_signs(), make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), make_level_set3_parallel_spatial(), sweep(), and sweep_pass().
CellSize
template<class TriangleMeshType, bool bScalarCellSize = true> CellSizeType UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::CellSize
Definition at line 60 of file SweepingMeshSDF.h.
Referenced by TSweepingMeshSDF(), cell_center(), Compute(), Compute(), GetDiagLength(), GetDim(), GetDim(), IsValid(), MakeInterpolant(), SetCellSize(), ShouldUseSpatial(), upper_bound(), and Validate().
ClosestTriGrid
template<class TriangleMeshType, bool bScalarCellSize = true> FDenseGrid3i UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::ClosestTriGrid protected
Definition at line 136 of file SweepingMeshSDF.h.
Referenced by CleanupUnwanted(), Empty(), GetClosestTriGrid(), make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), and make_level_set3_parallel_spatial().
ComputeMode
template<class TriangleMeshType, bool bScalarCellSize = true> EComputeModes UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::ComputeMode = EComputeModes::NarrowBandOnly
Definition at line 92 of file SweepingMeshSDF.h.
Referenced by Compute(), Compute(), and make_level_set3().
ExactBandWidth
template<class TriangleMeshType, bool bScalarCellSize = true> int UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::ExactBandWidth = 1
Definition at line 69 of file SweepingMeshSDF.h.
Referenced by Compute(), and Compute().
ExpandBounds
template<class TriangleMeshType, bool bScalarCellSize = true> FVector3d UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::ExpandBounds = FVector3d::Zero()
Definition at line 73 of file SweepingMeshSDF.h.
Referenced by Compute().
Grid
template<class TriangleMeshType, bool bScalarCellSize = true> FDenseGrid3f UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Grid
Definition at line 132 of file SweepingMeshSDF.h.
Referenced by At(), Compute(), Dimensions(), Empty(), GetValue(), make_level_set3_parallel(), MakeInterpolant(), and operator[]().
GridOrigin
template<class TriangleMeshType, bool bScalarCellSize = true> FVector3f UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::GridOrigin
Definition at line 131 of file SweepingMeshSDF.h.
Referenced by TSweepingMeshSDF(), cell_center(), Compute(), and MakeInterpolant().
InsideMode
template<class TriangleMeshType, bool bScalarCellSize = true> EInsideModes UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::InsideMode = EInsideModes::WindingCount
Definition at line 114 of file SweepingMeshSDF.h.
Referenced by compute_intersections(), and compute_signs().
IntersectionsGrid
template<class TriangleMeshType, bool bScalarCellSize = true> FDenseGrid3i UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::IntersectionsGrid protected
Definition at line 138 of file SweepingMeshSDF.h.
Referenced by CleanupUnwanted(), Empty(), GetIntersectionsGrid(), make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), and make_level_set3_parallel_spatial().
Mesh
template<class TriangleMeshType, bool bScalarCellSize = true> const TriangleMeshType* UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Mesh
Definition at line 58 of file SweepingMeshSDF.h.
Referenced by TSweepingMeshSDF(), cell_tri_dist(), check_neighbour(), compute_intersections(), make_level_set3(), make_level_set3_parallel(), make_level_set3_parallel_floodfill(), and make_level_set3_parallel_spatial().
NarrowBandMaxDistance
template<class TriangleMeshType, bool bScalarCellSize = true> double UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::NarrowBandMaxDistance = 0
Definition at line 98 of file SweepingMeshSDF.h.
Referenced by Compute(), and Compute().
Spatial
template<class TriangleMeshType, bool bScalarCellSize = true> TMeshAABBTree3<TriangleMeshType>* UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Spatial
Definition at line 59 of file SweepingMeshSDF.h.
Referenced by TSweepingMeshSDF(), Compute(), and make_level_set3_parallel_floodfill().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Implicit/SweepingMeshSDF.h