Unreal Engine 5.6 C++ API: Experimental::FHashType Class Reference
Experimental::FHashType Class Reference
#include "RobinHoodHashTable.h"
Public Types
using IntType = uint32
Public Member Functions
FHashType ()
IntType AsUInt () const
bool operator!= (FHashType Other) const
bool operator== (FHashType Other) const
Private Member Functions
FHashType (IntType InHash)
bool IsFree () const
bool IsOccupied () const
Private Attributes
IntType Hash
Static Private Attributes
static constexpr const IntType InvalidHash = (IntType(1)) << (sizeof(IntType) * 8 - 1)
Friends
template<typename, typename, typename, typename>
class RobinHoodHashTable_Private::TRobinHoodHashTable
Detailed Description
Definition at line 26 of file RobinHoodHashTable.h.
Member Typedef Documentation
IntType
using Experimental::FHashType::IntType = uint32
Definition at line 41 of file RobinHoodHashTable.h.
Constructor & Destructor Documentation
FHashType() [1/2]
Experimental::FHashType::FHashType () inline explicit
Definition at line 29 of file RobinHoodHashTable.h.
References Hash, and InvalidHash.
Referenced by operator!=(), and operator==().
FHashType() [2/2]
Experimental::FHashType::FHashType (IntType InHash) inline explicit private
Definition at line 52 of file RobinHoodHashTable.h.
References checkSlow, Hash, and InvalidHash.
Member Function Documentation
AsUInt()
IntType Experimental::FHashType::AsUInt () const inline
Definition at line 43 of file RobinHoodHashTable.h.
References Hash.
Referenced by Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindIdByHash(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrUpdateIdByHashInternal(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::RemoveByElementId(), and Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::RemoveByHash().
IsFree()
bool Experimental::FHashType::IsFree () const inline private
Definition at line 62 of file RobinHoodHashTable.h.
References Hash, and InvalidHash.
IsOccupied()
bool Experimental::FHashType::IsOccupied () const inline private
Definition at line 57 of file RobinHoodHashTable.h.
References Hash, and InvalidHash.
operator!=()
bool Experimental::FHashType::operator!= (FHashType Other) const inline
Definition at line 36 of file RobinHoodHashTable.h.
References FHashType(), Hash, and Other.
operator==()
bool Experimental::FHashType::operator== (FHashType Other) const inline
Definition at line 31 of file RobinHoodHashTable.h.
References FHashType(), Hash, and Other.
Friends And Related Symbol Documentation
RobinHoodHashTable_Private::TRobinHoodHashTable
template<typename, typename, typename, typename> friend class RobinHoodHashTable_Private::TRobinHoodHashTable friend
Definition at line 50 of file RobinHoodHashTable.h.
Field Documentation
Hash
IntType Experimental::FHashType::Hash private
Definition at line 68 of file RobinHoodHashTable.h.
Referenced by FHashType(), FHashType(), AsUInt(), IsFree(), IsOccupied(), operator!=(), and operator==().
InvalidHash
const IntType Experimental::FHashType::InvalidHash = (IntType(1)) << (sizeof(IntType) * 8 - 1) static constexpr private
Definition at line 67 of file RobinHoodHashTable.h.
Referenced by FHashType(), FHashType(), IsFree(), and IsOccupied().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Containers/RobinHoodHashTable.h