Unreal Engine 5.6 C++ API: IGameplayCueInterface Class Reference
IGameplayCueInterface Class Reference
Interface for actors that wish to handle GameplayCue events from GameplayEffects.
#include "GameplayCueInterface.h"
Private Member Functions
IGameplayCueInterface ()
virtual GAMEPLAYABILITIES_API void GameplayCueDefaultHandler (EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Default native handler, called if no tag matches found.
virtual void GetGameplayCueSets (TArray< class UGameplayCueSet * > &OutSets) const
Return the cue sets used by this object.
virtual GAMEPLAYABILITIES_API void HandleGameplayCue (AActor *Self, FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Handle a single gameplay cue.
virtual GAMEPLAYABILITIES_API void HandleGameplayCues (AActor *Self, const FGameplayTagContainer &GameplayCueTags, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Wrapper that handles multiple cues.
GENERATED_IINTERFACE_BODY() public virtual GAMEPLAYABILITIES_API void HandleGameplayCues (UObject *Self, const FGameplayTagContainer &GameplayCueTags, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Handle a single gameplay cue.
virtual GAMEPLAYABILITIES_API bool ShouldAcceptGameplayCue (AActor *Self, FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Returns true if the actor can currently accept gameplay cues associated with the given tag.
virtual GAMEPLAYABILITIES_API bool ShouldAcceptGameplayCue (UObject *Self, FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Returns true if the object can currently accept gameplay cues associated with the given tag.
UFUNCTION()) GAMEPLAYABILITIES_API void BlueprintCustomHandler(EGameplayCueEvent UFUNCTION () GAMEPLAYABILITIES_API virtual void ForwardGameplayCueToParent()
Internal function to map ufunctions directly to gameplaycue tags.
Static Private Member Functions
static GAMEPLAYABILITIES_API void ClearTagToFunctionMap ()
Clears internal cache of what classes implement which functions.
static GAMEPLAYABILITIES_API void DispatchBlueprintCustomHandler (UObject *Object, UFunction *Func, EGameplayCueEvent::Type EventType, const FGameplayCueParameters &Parameters)
Calls the UFunction override for a specific gameplay cue.
Private Attributes
bool bForwardToParent
If true, keep checking for additional handlers.
Detailed Description
Interface for actors that wish to handle GameplayCue events from GameplayEffects.
Native only because blueprints can't implement interfaces with native functions
Definition at line 32 of file GameplayCueInterface.h.
Constructor & Destructor Documentation
IGameplayCueInterface()
IGameplayCueInterface::IGameplayCueInterface () inline private
Definition at line 85 of file GameplayCueInterface.h.
References IGameplayCueInterface(), and bForwardToParent.
Referenced by IGameplayCueInterface().
Member Function Documentation
ClearTagToFunctionMap()
GAMEPLAYABILITIES_API void IGameplayCueInterface::ClearTagToFunctionMap () static private
Clears internal cache of what classes implement which functions.
References ClearTagToFunctionMap(), and UE_API.
Referenced by ClearTagToFunctionMap().
DispatchBlueprintCustomHandler()
GAMEPLAYABILITIES_API void IGameplayCueInterface::DispatchBlueprintCustomHandler (UObject * Object, UFunction * Func, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) static private
Calls the UFunction override for a specific gameplay cue.
References DispatchBlueprintCustomHandler(), Object, and UE_API.
Referenced by DispatchBlueprintCustomHandler().
GameplayCueDefaultHandler()
virtual GAMEPLAYABILITIES_API void IGameplayCueInterface::GameplayCueDefaultHandler (EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) private virtual
Default native handler, called if no tag matches found.
References Category, meta, and UE_API.
GetGameplayCueSets()
virtual void IGameplayCueInterface::GetGameplayCueSets (TArray< class UGameplayCueSet * > & OutSets) const inline private virtual
Return the cue sets used by this object.
This is optional and it is possible to leave this list empty.
Definition at line 66 of file GameplayCueInterface.h.
HandleGameplayCue()
virtual GAMEPLAYABILITIES_API void IGameplayCueInterface::HandleGameplayCue (AActor * Self, FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) private virtual
Handle a single gameplay cue.
References Self, and UE_API.
HandleGameplayCues() [1/2]
virtual GAMEPLAYABILITIES_API void IGameplayCueInterface::HandleGameplayCues (AActor * Self, const FGameplayTagContainer & GameplayCueTags, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) private virtual
Wrapper that handles multiple cues.
References Self, and UE_API.
HandleGameplayCues() [2/2]
GENERATED_IINTERFACE_BODY() public virtual GAMEPLAYABILITIES_API void IGameplayCueInterface::HandleGameplayCues (UObject * Self, const FGameplayTagContainer & GameplayCueTags, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) private virtual
Handle a single gameplay cue.
Wrapper that handles multiple cues
References Self, and UE_API.
ShouldAcceptGameplayCue() [1/2]
virtual GAMEPLAYABILITIES_API bool IGameplayCueInterface::ShouldAcceptGameplayCue (AActor * Self, FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) private virtual
Returns true if the actor can currently accept gameplay cues associated with the given tag.
Returns true by default. Allows actors to opt out of cues in cases such as pending death
References Self, and UE_API.
ShouldAcceptGameplayCue() [2/2]
virtual GAMEPLAYABILITIES_API bool IGameplayCueInterface::ShouldAcceptGameplayCue (UObject * Self, FGameplayTag GameplayCueTag, EGameplayCueEvent::Type EventType, const FGameplayCueParameters & Parameters) private virtual
Returns true if the object can currently accept gameplay cues associated with the given tag.
Returns true by default. Allows objects to opt out of cues in cases such as pending death
References Self, and UE_API.
UFUNCTION()
UFUNCTION()) GAMEPLAYABILITIES_API void BlueprintCustomHandler(EGameplayCueEvent IGameplayCueInterface::UFUNCTION () private
Internal function to map ufunctions directly to gameplaycue tags.
Call from a Cue handler event to continue checking for additional, more generic handlers. Called from the ability system blueprint library
References Category, UE_API, and UFUNCTION().
Referenced by UFUNCTION().
Field Documentation
bForwardToParent
bool IGameplayCueInterface::bForwardToParent private
If true, keep checking for additional handlers.
Definition at line 89 of file GameplayCueInterface.h.
Referenced by IGameplayCueInterface().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/GameplayCueInterface.h