Unreal Engine 5.6 C++ API: UE::Geometry::TImplicitBlend< TriangleMeshType > Class Template Reference
UE::Geometry::TImplicitBlend< TriangleMeshType > Class Template Reference
#include "Blend.h"
Public Member Functions
virtual ~TImplicitBlend ()
const FMeshShapeGenerator & Generate (bool bReuseComputed=false)
void SetCellSizesAndFalloff (FAxisAlignedBox3d Bounds, double BlendFalloffIn, int TargetInputVoxelCount, int TargetOutputVoxelCount)
bool Validate ()
Data Fields
double BlendFalloff = 5.0
double BlendPower = 2.0
bool bSubtract = false
TFunction< bool(void)> CancelF
if this function returns true, we should abort calculation
double GridCellSize = 1.0
double MeshCellSize = 1.0
TArray< FAxisAlignedBox3d > SourceBounds
TArray< const TriangleMeshType * > Sources
Inputs.
Protected Member Functions
void ComputeBounds ()
void ComputeLazySDFs (bool bReuseComputed)
void ComputeSpatials (bool bReuseComputed)
void GenerateBlendAnalytic (bool bReuseComputed)
Protected Attributes
FAxisAlignedBox3d CombinedBounds
Intermediate.
TArray< TCachingMeshSDF< TriangleMeshType > > ComputedSDFs
TArray< TMeshAABBTree3< TriangleMeshType > > ComputedSpatials
FMarchingCubes MarchingCubes
TArray< double > SDFMaxDistances
Detailed Description
template<typename TriangleMeshType>
class UE::Geometry::TImplicitBlend< TriangleMeshType >
Definition at line 23 of file Blend.h.
Constructor & Destructor Documentation
~TImplicitBlend()
template<typename TriangleMeshType> virtual UE::Geometry::TImplicitBlend< TriangleMeshType >::~TImplicitBlend () inline virtual
Definition at line 27 of file Blend.h.
Member Function Documentation
ComputeBounds()
template<typename TriangleMeshType> void UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputeBounds () inline protected
Definition at line 114 of file Blend.h.
References UE::Geometry::Box, CombinedBounds, UE::Geometry::TAxisAlignedBox3< double >::Empty(), and SourceBounds.
Referenced by Generate().
ComputeLazySDFs()
template<typename TriangleMeshType> void UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputeLazySDFs (bool bReuseComputed) inline protected
Definition at line 136 of file Blend.h.
References BlendFalloff, CancelF, ComputedSDFs, ComputedSpatials, ComputeSpatials(), GridCellSize, ParallelFor(), SDFMaxDistances, and Sources.
Referenced by GenerateBlendAnalytic().
ComputeSpatials()
template<typename TriangleMeshType> void UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputeSpatials (bool bReuseComputed) inline protected
Definition at line 123 of file Blend.h.
References ComputedSpatials, ParallelFor(), and Sources.
Referenced by ComputeLazySDFs(), and GenerateBlendAnalytic().
Generate()
template<typename TriangleMeshType> const FMeshShapeGenerator & UE::Geometry::TImplicitBlend< TriangleMeshType >::Generate (bool bReuseComputed = false) inline
Parameters
bReuseComputed If true, will attempt to reuse previously-computed AABB trees and SDFs where possible
Definition at line 98 of file Blend.h.
References ComputeBounds(), ensure, GenerateBlendAnalytic(), MarchingCubes, and Validate().
GenerateBlendAnalytic()
template<typename TriangleMeshType> void UE::Geometry::TImplicitBlend< TriangleMeshType >::GenerateBlendAnalytic (bool bReuseComputed) inline protected
..... then remove this line
Definition at line 175 of file Blend.h.
References TArray< InElementType, InAllocatorType >::Add(), BlendFalloff, BlendPower, UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::BlendPower, bSubtract, UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::bSubtract, CancelF, UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::Children, CombinedBounds, ComputedSDFs, ComputeLazySDFs(), ComputeSpatials(), TArray< InElementType, InAllocatorType >::Emplace(), UE::Geometry::LerpSteps, MarchingCubes, MeshCellSize, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Reserve(), Seed, Source, Sources, and UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::Value().
Referenced by Generate().
SetCellSizesAndFalloff()
template<typename TriangleMeshType> void UE::Geometry::TImplicitBlend< TriangleMeshType >::SetCellSizesAndFalloff (FAxisAlignedBox3d Bounds, double BlendFalloffIn, int TargetInputVoxelCount, int TargetOutputVoxelCount) inline
Definition at line 54 of file Blend.h.
References BlendFalloff, GridCellSize, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), and MeshCellSize.
Validate()
template<typename TriangleMeshType> bool UE::Geometry::TImplicitBlend< TriangleMeshType >::Validate () inline
Definition at line 80 of file Blend.h.
References BlendFalloff, BlendPower, GridCellSize, MeshCellSize, SourceBounds, and Sources.
Referenced by Generate().
Field Documentation
BlendFalloff
template<typename TriangleMeshType> double UE::Geometry::TImplicitBlend< TriangleMeshType >::BlendFalloff = 5.0
Definition at line 42 of file Blend.h.
Referenced by ComputeLazySDFs(), GenerateBlendAnalytic(), SetCellSizesAndFalloff(), and Validate().
BlendPower
template<typename TriangleMeshType> double UE::Geometry::TImplicitBlend< TriangleMeshType >::BlendPower = 2.0
Definition at line 39 of file Blend.h.
Referenced by GenerateBlendAnalytic(), and Validate().
bSubtract
template<typename TriangleMeshType> bool UE::Geometry::TImplicitBlend< TriangleMeshType >::bSubtract = false
Definition at line 51 of file Blend.h.
Referenced by GenerateBlendAnalytic().
CancelF
template<typename TriangleMeshType> TFunction<bool(void)> UE::Geometry::TImplicitBlend< TriangleMeshType >::CancelF
Initial value:
= []()
    {
        return false;
    }
if this function returns true, we should abort calculation
Definition at line 62 of file Blend.h.
Referenced by ComputeLazySDFs(), and GenerateBlendAnalytic().
CombinedBounds
template<typename TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TImplicitBlend< TriangleMeshType >::CombinedBounds protected
Intermediate.
Definition at line 73 of file Blend.h.
Referenced by ComputeBounds(), and GenerateBlendAnalytic().
ComputedSDFs
template<typename TriangleMeshType> TArray<TCachingMeshSDF<TriangleMeshType> > UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputedSDFs protected
Definition at line 75 of file Blend.h.
Referenced by ComputeLazySDFs(), and GenerateBlendAnalytic().
ComputedSpatials
template<typename TriangleMeshType> TArray<TMeshAABBTree3<TriangleMeshType> > UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputedSpatials protected
Definition at line 74 of file Blend.h.
Referenced by ComputeLazySDFs(), and ComputeSpatials().
GridCellSize
template<typename TriangleMeshType> double UE::Geometry::TImplicitBlend< TriangleMeshType >::GridCellSize = 1.0
Definition at line 45 of file Blend.h.
Referenced by ComputeLazySDFs(), SetCellSizesAndFalloff(), and Validate().
MarchingCubes
template<typename TriangleMeshType> FMarchingCubes UE::Geometry::TImplicitBlend< TriangleMeshType >::MarchingCubes protected
Definition at line 69 of file Blend.h.
Referenced by Generate(), and GenerateBlendAnalytic().
MeshCellSize
template<typename TriangleMeshType> double UE::Geometry::TImplicitBlend< TriangleMeshType >::MeshCellSize = 1.0
Definition at line 48 of file Blend.h.
Referenced by GenerateBlendAnalytic(), SetCellSizesAndFalloff(), and Validate().
SDFMaxDistances
template<typename TriangleMeshType> TArray<double> UE::Geometry::TImplicitBlend< TriangleMeshType >::SDFMaxDistances protected
Definition at line 76 of file Blend.h.
Referenced by ComputeLazySDFs().
SourceBounds
template<typename TriangleMeshType> TArray<FAxisAlignedBox3d> UE::Geometry::TImplicitBlend< TriangleMeshType >::SourceBounds
Definition at line 36 of file Blend.h.
Referenced by ComputeBounds(), and Validate().
Sources
template<typename TriangleMeshType> TArray<const TriangleMeshType*> UE::Geometry::TImplicitBlend< TriangleMeshType >::Sources
Inputs.
Definition at line 35 of file Blend.h.
Referenced by ComputeLazySDFs(), ComputeSpatials(), GenerateBlendAnalytic(), and Validate().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Implicit/Blend.h