Unreal Engine 5.6 C++ API: FQueuedThreadPoolWrapper Class Reference
FQueuedThreadPoolWrapper Class Reference
ThreadPool wrapper implementation allowing to schedule up to MaxConcurrency tasks at a time making sub-partitioning another thread-pool a breeze and allowing more fine-grained control over scheduling by effectively giving another set of priorities.
#include "QueuedThreadPoolWrapper.h"
Data Structures
class FScheduledWork
Public Member Functions
FQueuedThreadPoolWrapper (FQueuedThreadPool *InWrappedQueuedThreadPool, int32 InMaxConcurrency=-1, TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper=DefaultQueuedWorkPriorityWrapper)
InWrappedQueuedThreadPool Underlying thread pool to schedule task to.
~FQueuedThreadPoolWrapper ()
void AddQueuedWork (IQueuedWork *InQueuedWork, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal) override
Checks to see if there is a thread available to perform the task.
int32 GetCurrentConcurrency () const
int32 GetNumThreads () const override
Get the number of queued threads.
void Pause ()
Queued task are not scheduled against the wrapped thread-pool until resumed.
void Resume (int32 InNumQueuedWork=-1)
Resume a specified amount of queued work, or -1 to unpause.
bool RetractQueuedWork (IQueuedWork *InQueuedWork) override
Attempts to retract a previously queued task.
void SetMaxConcurrency (int32 MaxConcurrency=-1)
Dynamically adjust the maximum number of concurrent tasks, -1 for unlimited.
Public Member Functions inherited from FQueuedThreadPool
FQueuedThreadPool ()
virtual ~FQueuedThreadPool ()
virtual bool CreateForkable (uint32 InNumQueuedThreads, uint32 StackSize=(32 *1024), EThreadPriority ThreadPriority=TPri_Normal, const TCHAR *Name=TEXT("UnknownThreadPool"))
Creates the thread pool with the specified number of forkable threads (see FForkProcessHelper)
Protected Member Functions
virtual FScheduledWork * AllocateScheduledWork ()
virtual int32 GetMaxConcurrency () const
virtual void OnScheduled (const IQueuedWork *)
virtual void OnUnscheduled (const IQueuedWork *)
Protected Attributes
FCriticalSection Lock
FThreadPoolPriorityQueue QueuedWork
Private Member Functions
FScheduledWork * AllocateWork (IQueuedWork *InnerWork, EQueuedWorkPriority Priority)
bool CanSchedule (EQueuedWorkPriority Priority) const
bool Create (uint32 InNumQueuedThreads, uint32 StackSize, EThreadPriority ThreadPriority, const TCHAR *Name) override
Creates the thread pool with the specified number of threads.
void Destroy () override
Tells the pool to clean up all background threads.
void ReleaseWorkNoLock (FScheduledWork *Work)
void Schedule (FScheduledWork *Work=nullptr)
bool TryRetractWorkNoLock (EQueuedWorkPriority InPriority)
Private Attributes
bool bIsScheduling = false
std::atomic< int32 > CurrentConcurrency
std::atomic< int32 > MaxConcurrency
int32 MaxTaskToSchedule
TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> PriorityMapper
TMap< IQueuedWork *, FScheduledWork * > ScheduledWork
TArray< FScheduledWork * > WorkPool
FQueuedThreadPool * WrappedQueuedThreadPool
EQueuedWorkPriority WrappedQueuePriority
Additional Inherited Members
Static Public Member Functions inherited from FQueuedThreadPool
static FQueuedThreadPool * Allocate ()
Allocates a thread pool.
Static Public Attributes inherited from FQueuedThreadPool
static uint32 OverrideStackSize
Stack size for threads created for the thread pool.
Detailed Description
ThreadPool wrapper implementation allowing to schedule up to MaxConcurrency tasks at a time making sub-partitioning another thread-pool a breeze and allowing more fine-grained control over scheduling by effectively giving another set of priorities.
Definition at line 43 of file QueuedThreadPoolWrapper.h.
Constructor & Destructor Documentation
FQueuedThreadPoolWrapper()
FQueuedThreadPoolWrapper::FQueuedThreadPoolWrapper (FQueuedThreadPool * InWrappedQueuedThreadPool, int32 InMaxConcurrency = -1, TFunction< EQueuedWorkPriority(EQueuedWorkPriority)> InPriorityMapper = DefaultQueuedWorkPriorityWrapper)
InWrappedQueuedThreadPool Underlying thread pool to schedule task to.
InMaxConcurrency Maximum number of concurrent tasks allowed, -1 will limit concurrency to number of threads available in the underlying thread pool. InPriorityMapper Thread-safe function used to map any priority from this Queue to the priority that should be used when scheduling the task on the underlying thread pool.
References FQueuedThreadPool::FQueuedThreadPool(), and DefaultQueuedWorkPriorityWrapper.
Referenced by FQueuedThreadPoolDynamicWrapper::FQueuedThreadPoolDynamicWrapper().
~FQueuedThreadPoolWrapper()
FQueuedThreadPoolWrapper::~FQueuedThreadPoolWrapper ()
Member Function Documentation
AddQueuedWork()
void FQueuedThreadPoolWrapper::AddQueuedWork (IQueuedWork * InQueuedWork, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) override virtual
Checks to see if there is a thread available to perform the task.
If not, it queues the work for later. Otherwise it is immediately dispatched.
Parameters
InQueuedWork The work that needs to be done asynchronously
InQueuedWorkPriority The priority at which to process this task
See also
RetractQueuedWork
Implements FQueuedThreadPool.
References Normal.
Referenced by FQueuedThreadPoolDynamicWrapper::AddQueuedWork().
AllocateScheduledWork()
virtual FScheduledWork * FQueuedThreadPoolWrapper::AllocateScheduledWork () inline protected virtual
Definition at line 203 of file QueuedThreadPoolWrapper.h.
AllocateWork()
FScheduledWork * FQueuedThreadPoolWrapper::AllocateWork (IQueuedWork * InnerWork, EQueuedWorkPriority Priority) private
CanSchedule()
bool FQueuedThreadPoolWrapper::CanSchedule (EQueuedWorkPriority Priority) const private
Create()
bool FQueuedThreadPoolWrapper::Create (uint32 InNumQueuedThreads, uint32 StackSize, EThreadPriority ThreadPriority, const TCHAR * Name) override private virtual
Creates the thread pool with the specified number of threads.
Parameters
InNumQueuedThreads Specifies the number of threads to use in the pool
StackSize The size of stack the threads in the pool need (32K default)
ThreadPriority priority of new pool thread
Name optional name for the pool to be used for instrumentation
Returns
Whether the pool creation was successful or not
Implements FQueuedThreadPool.
References Name.
Destroy()
void FQueuedThreadPoolWrapper::Destroy () override private virtual
Tells the pool to clean up all background threads.
Implements FQueuedThreadPool.
GetCurrentConcurrency()
int32 FQueuedThreadPoolWrapper::GetCurrentConcurrency () const inline
Definition at line 72 of file QueuedThreadPoolWrapper.h.
References CurrentConcurrency.
GetMaxConcurrency()
virtual int32 FQueuedThreadPoolWrapper::GetMaxConcurrency () const inline protected virtual
Definition at line 194 of file QueuedThreadPoolWrapper.h.
References MaxConcurrency.
GetNumThreads()
int32 FQueuedThreadPoolWrapper::GetNumThreads () const override virtual
Get the number of queued threads.
Implements FQueuedThreadPool.
OnScheduled()
virtual void FQueuedThreadPoolWrapper::OnScheduled (const IQueuedWork *) inline protected virtual
Definition at line 197 of file QueuedThreadPoolWrapper.h.
OnUnscheduled()
virtual void FQueuedThreadPoolWrapper::OnUnscheduled (const IQueuedWork *) inline protected virtual
Definition at line 200 of file QueuedThreadPoolWrapper.h.
Pause()
void FQueuedThreadPoolWrapper::Pause ()
Queued task are not scheduled against the wrapped thread-pool until resumed.
ReleaseWorkNoLock()
void FQueuedThreadPoolWrapper::ReleaseWorkNoLock (FScheduledWork * Work) private
Resume()
void FQueuedThreadPoolWrapper::Resume (int32 InNumQueuedWork = -1)
Resume a specified amount of queued work, or -1 to unpause.
RetractQueuedWork()
bool FQueuedThreadPoolWrapper::RetractQueuedWork (IQueuedWork * InQueuedWork) override virtual
Attempts to retract a previously queued task.
Parameters
InQueuedWork The work to try to retract
Returns
true if the work was retracted
See also
AddQueuedWork
Implements FQueuedThreadPool.
Schedule()
void FQueuedThreadPoolWrapper::Schedule (FScheduledWork * Work = nullptr) private
SetMaxConcurrency()
void FQueuedThreadPoolWrapper::SetMaxConcurrency (int32 MaxConcurrency = -1)
Dynamically adjust the maximum number of concurrent tasks, -1 for unlimited.
References MaxConcurrency.
TryRetractWorkNoLock()
bool FQueuedThreadPoolWrapper::TryRetractWorkNoLock (EQueuedWorkPriority InPriority) private
Field Documentation
bIsScheduling
bool FQueuedThreadPoolWrapper::bIsScheduling = false private
Definition at line 222 of file QueuedThreadPoolWrapper.h.
CurrentConcurrency
std::atomic<int32> FQueuedThreadPoolWrapper::CurrentConcurrency private
Definition at line 220 of file QueuedThreadPoolWrapper.h.
Referenced by GetCurrentConcurrency().
Lock
FCriticalSection FQueuedThreadPoolWrapper::Lock protected
Definition at line 190 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedThreadPoolDynamicWrapper::Sort().
MaxConcurrency
std::atomic<int32> FQueuedThreadPoolWrapper::MaxConcurrency private
Definition at line 218 of file QueuedThreadPoolWrapper.h.
Referenced by GetMaxConcurrency(), and SetMaxConcurrency().
MaxTaskToSchedule
int32 FQueuedThreadPoolWrapper::MaxTaskToSchedule private
Definition at line 219 of file QueuedThreadPoolWrapper.h.
PriorityMapper
TFunction<EQueuedWorkPriority(EQueuedWorkPriority)> FQueuedThreadPoolWrapper::PriorityMapper private
Definition at line 213 of file QueuedThreadPoolWrapper.h.
QueuedWork
FThreadPoolPriorityQueue FQueuedThreadPoolWrapper::QueuedWork protected
Definition at line 191 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedThreadPoolDynamicWrapper::Sort().
ScheduledWork
TMap<IQueuedWork*, FScheduledWork*> FQueuedThreadPoolWrapper::ScheduledWork private
Definition at line 217 of file QueuedThreadPoolWrapper.h.
WorkPool
TArray<FScheduledWork*> FQueuedThreadPoolWrapper::WorkPool private
Definition at line 216 of file QueuedThreadPoolWrapper.h.
WrappedQueuedThreadPool
FQueuedThreadPool* FQueuedThreadPoolWrapper::WrappedQueuedThreadPool private
Definition at line 215 of file QueuedThreadPoolWrapper.h.
WrappedQueuePriority
EQueuedWorkPriority FQueuedThreadPoolWrapper::WrappedQueuePriority private
Definition at line 221 of file QueuedThreadPoolWrapper.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/QueuedThreadPoolWrapper.h