Unreal Engine 5.6 C++ API: FQueuedThreadPoolWrapper::FScheduledWork Class Reference
FQueuedThreadPoolWrapper::FScheduledWork Class Reference
#include "QueuedThreadPoolWrapper.h"
Public Member Functions
FScheduledWork ()
FScheduledWork (const FScheduledWork &&)=delete
FScheduledWork (const FScheduledWork &)=delete
~FScheduledWork () override
const TCHAR * GetDebugName () const final
Returns text to identify the Work, for debug/log purposes only.
FScheduledWork & operator= (const FScheduledWork &&)=delete
FScheduledWork & operator= (const FScheduledWork &)=delete
Public Member Functions inherited from IQueuedWork
virtual ~IQueuedWork ()
Virtual destructor so that child implementations are guaranteed a chance to clean up any resources they allocated.
Public Member Functions inherited from IExecutionResource
virtual ~IExecutionResource ()
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Private Member Functions
void Abandon () override
Tells the queued work that it is being abandoned so that it can do per object clean up as needed.
FReturnedRefCountValue AddRef () const override
void Assign (FQueuedThreadPoolWrapper *InParentPool, IQueuedWork *InWork, EQueuedWorkPriority InPriority)
void DoThreadedWork () override
This is where the real thread work is done.
IQueuedWork * GetInnerWork () const
EQueuedWorkPriority GetPriority () const
EQueuedWorkFlags GetQueuedWorkFlags () const override
Returns any special work flags.
uint32 GetRefCount () const override
int64 GetRequiredMemory () const override
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
uint32 Release () const override
void Reset ()
Private Attributes
FThreadSafeCounter NumRefs
FQueuedThreadPoolWrapper * ParentPool
EQueuedWorkPriority Priority
IQueuedWork * Work
Friends
class FQueuedThreadPoolWrapper
Additional Inherited Members
Public Types inherited from IQueuedWork
using IInternalDataType = TRefCountPtr<IQueuedWorkInternalData>
Internal data can be used by the pool.
Data Fields inherited from IQueuedWork
IInternalDataType InternalData
Detailed Description
Definition at line 75 of file QueuedThreadPoolWrapper.h.
Constructor & Destructor Documentation
FScheduledWork() [1/3]
FQueuedThreadPoolWrapper::FScheduledWork::FScheduledWork ()
Referenced by FScheduledWork(), FScheduledWork(), operator=(), operator=(), and Release().
FScheduledWork() [2/3]
FQueuedThreadPoolWrapper::FScheduledWork::FScheduledWork (const FScheduledWork &) delete
References FScheduledWork().
FScheduledWork() [3/3]
FQueuedThreadPoolWrapper::FScheduledWork::FScheduledWork (const FScheduledWork &&) delete
References FScheduledWork().
~FScheduledWork()
FQueuedThreadPoolWrapper::FScheduledWork::~FScheduledWork () override
Member Function Documentation
Abandon()
void FQueuedThreadPoolWrapper::FScheduledWork::Abandon () inline override private virtual
Tells the queued work that it is being abandoned so that it can do per object clean up as needed.
This will only be called if it is being abandoned before completion. NOTE: This requires the object to delete itself using whatever heap it was allocated in.
Implements IQueuedWork.
Definition at line 150 of file QueuedThreadPoolWrapper.h.
References Release(), and Work.
AddRef()
FReturnedRefCountValue FQueuedThreadPoolWrapper::FScheduledWork::AddRef () const inline override private virtual
Implements IRefCountedObject.
Definition at line 102 of file QueuedThreadPoolWrapper.h.
References NumRefs.
Referenced by Assign().
Assign()
void FQueuedThreadPoolWrapper::FScheduledWork::Assign (FQueuedThreadPoolWrapper * InParentPool, IQueuedWork * InWork, EQueuedWorkPriority InPriority) inline private
Definition at line 126 of file QueuedThreadPoolWrapper.h.
References AddRef(), check, FQueuedThreadPoolWrapper, GetRefCount(), ParentPool, Priority, and Work.
DoThreadedWork()
void FQueuedThreadPoolWrapper::FScheduledWork::DoThreadedWork () inline override private virtual
This is where the real thread work is done.
All work that is done for this queued object should be done from within the call to this function.
Implements IQueuedWork.
Definition at line 135 of file QueuedThreadPoolWrapper.h.
References Release(), and Work.
GetDebugName()
const TCHAR * FQueuedThreadPoolWrapper::FScheduledWork::GetDebugName () const inline final virtual
Returns text to identify the Work, for debug/log purposes only.
Reimplemented from IQueuedWork.
Definition at line 88 of file QueuedThreadPoolWrapper.h.
References TEXT, and Work.
GetInnerWork()
IQueuedWork * FQueuedThreadPoolWrapper::FScheduledWork::GetInnerWork () const inline private
Definition at line 167 of file QueuedThreadPoolWrapper.h.
References Work.
GetPriority()
EQueuedWorkPriority FQueuedThreadPoolWrapper::FScheduledWork::GetPriority () const inline private
Definition at line 172 of file QueuedThreadPoolWrapper.h.
References Priority.
GetQueuedWorkFlags()
EQueuedWorkFlags FQueuedThreadPoolWrapper::FScheduledWork::GetQueuedWorkFlags () const inline override private virtual
Returns any special work flags.
Reimplemented from IQueuedWork.
Definition at line 157 of file QueuedThreadPoolWrapper.h.
References Work.
GetRefCount()
uint32 FQueuedThreadPoolWrapper::FScheduledWork::GetRefCount () const inline override private virtual
Implements IRefCountedObject.
Definition at line 121 of file QueuedThreadPoolWrapper.h.
References NumRefs.
Referenced by Assign().
GetRequiredMemory()
int64 FQueuedThreadPoolWrapper::FScheduledWork::GetRequiredMemory () const inline override private virtual
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
Reimplemented from IQueuedWork.
Definition at line 162 of file QueuedThreadPoolWrapper.h.
References Work.
operator=() [1/2]
FScheduledWork & FQueuedThreadPoolWrapper::FScheduledWork::operator= (const FScheduledWork &&) delete
References FScheduledWork().
operator=() [2/2]
FScheduledWork & FQueuedThreadPoolWrapper::FScheduledWork::operator= (const FScheduledWork &) delete
References FScheduledWork().
Release()
uint32 FQueuedThreadPoolWrapper::FScheduledWork::Release () const inline override private virtual
Implements IRefCountedObject.
Definition at line 107 of file QueuedThreadPoolWrapper.h.
References FScheduledWork(), NumRefs, and ParentPool.
Referenced by Abandon(), and DoThreadedWork().
Reset()
void FQueuedThreadPoolWrapper::FScheduledWork::Reset () inline private
Definition at line 177 of file QueuedThreadPoolWrapper.h.
References Work.
Friends And Related Symbol Documentation
FQueuedThreadPoolWrapper
friend class FQueuedThreadPoolWrapper friend
Definition at line 183 of file QueuedThreadPoolWrapper.h.
References FQueuedThreadPoolWrapper.
Referenced by Assign(), and FQueuedThreadPoolWrapper.
Field Documentation
NumRefs
FThreadSafeCounter FQueuedThreadPoolWrapper::FScheduledWork::NumRefs mutable private
Definition at line 182 of file QueuedThreadPoolWrapper.h.
Referenced by AddRef(), GetRefCount(), and Release().
ParentPool
FQueuedThreadPoolWrapper* FQueuedThreadPoolWrapper::FScheduledWork::ParentPool private
Definition at line 184 of file QueuedThreadPoolWrapper.h.
Referenced by Assign(), and Release().
Priority
EQueuedWorkPriority FQueuedThreadPoolWrapper::FScheduledWork::Priority private
Definition at line 186 of file QueuedThreadPoolWrapper.h.
Referenced by Assign(), and GetPriority().
Work
IQueuedWork* FQueuedThreadPoolWrapper::FScheduledWork::Work private
Definition at line 185 of file QueuedThreadPoolWrapper.h.
Referenced by Abandon(), Assign(), DoThreadedWork(), GetDebugName(), GetInnerWork(), GetQueuedWorkFlags(), GetRequiredMemory(), and Reset().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/QueuedThreadPoolWrapper.h