Unreal Engine 5.6 C++ API: UE::Insights::FCustomTableTreeNode Class Reference
UE::Insights::FCustomTableTreeNode Class Reference
#include "TableTreeNode.h"
Private Member Functions
FCustomTableTreeNode (const FName InName, TWeakPtr< FTable > InParentTable, const FSlateBrush *InIconBrush, FLinearColor InColor)
Initialization constructor for the group node.
FCustomTableTreeNode (const FName InName, TWeakPtr< FTable > InParentTable, const FSlateBrush *InIconBrush, FLinearColor InIconColor, FLinearColor InColor)
Initialization constructor for the group node.
FCustomTableTreeNode (const FName InName, TWeakPtr< FTable > InParentTable, int32 InRowIndex, const FSlateBrush *InIconBrush, FLinearColor InIconColor, FLinearColor InColor, bool IsGroup)
Initialization constructor for a table record node.
virtual ~FCustomTableTreeNode ()
virtual FLinearColor GetColor () const override
virtual const FSlateBrush * GetIcon () const override
virtual FLinearColor GetIconColor () const override
INSIGHTS_DECLARE_RTTI (FCustomTableTreeNode, FTableTreeNode) public
Initialization constructor for a table record node.
void SetIcon (const FSlateBrush *InIconBrush)
Sets an icon brush for this node.
Private Attributes
FLinearColor Color
The color tint for the name text of this node.
const FSlateBrush * IconBrush
The icon of this node.
FLinearColor IconColor
The color tint for the icon of this node.
Additional Inherited Members
Public Member Functions inherited from UE::Insights::FBaseTreeNode
FBaseTreeNode (const FName InName, bool bInIsGroup)
Initialization constructor for the node.
virtual ~FBaseTreeNode ()
void AddChild (const FBaseTreeNodePtr &ChildPtr)
Adds specified node to the children nodes.
void AddChildAndSetParent (const FBaseTreeNodePtr &ChildPtr)
Adds specified node to the children nodes.
void AddFilteredChild (const FBaseTreeNodePtr &ChildPtr)
Adds specified child to the filtered children nodes.
void ClearChildren (int32 NewSize=0)
Clears children.
void ClearFilteredChildren (int32 NewSize=0)
Clears (removes all) the filtered children nodes.
void EnumerateChildren (TFunction< bool(const FBaseTreeNodePtr &)> Callback) const
Enumerates the children nodes.
void EnumerateFilteredChildren (TFunction< bool(const FBaseTreeNodePtr &)> Callback) const
Enumerates the filtered children nodes.
const TArray< FBaseTreeNodePtr > & GetChildren () const
int32 GetChildrenCount () const
uint32 GetDefaultSortOrder () const
virtual const FText GetDisplayName () const
virtual const FText GetExtraDisplayName () const
FBaseTreeNodePtr & GetFilteredChildNode (int32 Index)
const FBaseTreeNodePtr & GetFilteredChildNode (int32 Index) const
const TArray< FBaseTreeNodePtr > & GetFilteredChildren () const
int32 GetFilteredChildrenCount () const
const FName & GetName () const
FBaseTreeNodePtr GetParent () const
FBaseTreeNodeWeak GetParentWeak () const
virtual const FText GetTooltipText () const
virtual bool HasExtraDisplayName () const
void InitGroupData ()
Initializes the group data, allowing this node to accept children.
bool IsExpanded () const
bool IsGroup () const
int32 RemoveChild (const FBaseTreeNodePtr &ChildPtr)
Removes the specified node from the children nodes (preserving the order).
int32 RemoveChildSwap (const FBaseTreeNodePtr &ChildPtr)
Removes the specified node from the children nodes (not preserving the order).
void RemoveFromParent ()
Removes this node from the parent's children nodes (preserving the order).
void RemoveFromParentSwap ()
Removes this node from the parent's children nodes (not preserving the order).
void RemoveGroupData ()
void ResetFilteredChildren ()
Resets the filtered children nodes.
void ResetFilteredChildrenRec ()
Resets the filtered children for this node and also recursively for all children nodes.
void ResetParentForChildren ()
void ResetParentForChildrenRec ()
void SetDefaultSortOrder (uint32 Order)
void SetExpansion (bool bOnOff)
void SetParent (const FBaseTreeNodeWeak &InParentWeak)
void SetParentForChildren ()
void SetParentForChildrenRec ()
void SortChildren (const ITableCellValueSorter &Sorter, ESortMode SortMode)
template<typename PredicateType>
void SortChildren (PredicateType Predicate)
void SortFilteredChildren (const ITableCellValueSorter &Sorter, ESortMode SortMode)
template<typename PredicateType>
void SortFilteredChildren (PredicateType Predicate)
void SwapChildren (TArray< FBaseTreeNodePtr > &NewChildren)
void SwapChildrenFast (TArray< FBaseTreeNodePtr > &NewChildren)
Public Member Functions inherited from TSharedFromThis< FBaseTreeNode >
TSharedRef< FBaseTreeNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBaseTreeNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions inherited from UE::Insights::FBaseTreeNode
static FLinearColor GetDefaultColor (bool bIsGroupNode)
static const FSlateBrush * GetDefaultIcon (bool bIsGroupNode)
static FLinearColor GetDefaultIconColor (bool bIsGroupNode)
Protected Member Functions inherited from UE::Insights::FBaseTreeNode
TArray< FBaseTreeNodePtr > & GetChildrenMutable ()
Protected Member Functions inherited from TSharedFromThis< FBaseTreeNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FBaseTreeNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Insights::FTableTreeNode
TMap< FName, FTableCellValue > * AggregatedValues
TWeakPtr< FTable > ParentTable
FTableRowId RowId
Detailed Description
Definition at line 170 of file TableTreeNode.h.
Constructor & Destructor Documentation
FCustomTableTreeNode() [1/3]
UE::Insights::FCustomTableTreeNode::FCustomTableTreeNode (const FName InName, TWeakPtr< FTable > InParentTable, int32 InRowIndex, const FSlateBrush * InIconBrush, FLinearColor InIconColor, FLinearColor InColor, bool IsGroup) inline explicit private
Initialization constructor for a table record node.
Definition at line 185 of file TableTreeNode.h.
References UE::Insights::FTableTreeNode::FTableTreeNode(), Color, IconBrush, IconColor, InName, and UE::Insights::FBaseTreeNode::IsGroup().
Referenced by INSIGHTS_DECLARE_RTTI().
FCustomTableTreeNode() [2/3]
UE::Insights::FCustomTableTreeNode::FCustomTableTreeNode (const FName InName, TWeakPtr< FTable > InParentTable, const FSlateBrush * InIconBrush, FLinearColor InColor) inline explicit private
Initialization constructor for the group node.
Definition at line 194 of file TableTreeNode.h.
References UE::Insights::FTableTreeNode::FTableTreeNode(), Color, IconBrush, IconColor, and InName.
FCustomTableTreeNode() [3/3]
UE::Insights::FCustomTableTreeNode::FCustomTableTreeNode (const FName InName, TWeakPtr< FTable > InParentTable, const FSlateBrush * InIconBrush, FLinearColor InIconColor, FLinearColor InColor) inline explicit private
Initialization constructor for the group node.
Definition at line 203 of file TableTreeNode.h.
References UE::Insights::FTableTreeNode::FTableTreeNode(), Color, IconBrush, IconColor, and InName.
~FCustomTableTreeNode()
virtual UE::Insights::FCustomTableTreeNode::~FCustomTableTreeNode () inline private virtual
Definition at line 211 of file TableTreeNode.h.
Member Function Documentation
GetColor()
virtual FLinearColor UE::Insights::FCustomTableTreeNode::GetColor () const inline override private virtual
Returns
the color tint to be used for the name text of this node.
Reimplemented from UE::Insights::FBaseTreeNode.
Definition at line 233 of file TableTreeNode.h.
References Color.
GetIcon()
virtual const FSlateBrush * UE::Insights::FCustomTableTreeNode::GetIcon () const inline override private virtual
Returns
the brush icon for this node.
Reimplemented from UE::Insights::FBaseTreeNode.
Definition at line 215 of file TableTreeNode.h.
References IconBrush.
GetIconColor()
virtual FLinearColor UE::Insights::FCustomTableTreeNode::GetIconColor () const inline override private virtual
Returns
the color tint to be used for the icon of this node.
Reimplemented from UE::Insights::FBaseTreeNode.
Definition at line 228 of file TableTreeNode.h.
References IconColor.
INSIGHTS_DECLARE_RTTI()
UE::Insights::FCustomTableTreeNode::INSIGHTS_DECLARE_RTTI (FCustomTableTreeNode , FTableTreeNode) inline private
Initialization constructor for a table record node.
Definition at line 172 of file TableTreeNode.h.
References FCustomTableTreeNode(), UE::Insights::FTableTreeNode::FTableTreeNode(), Color, IconBrush, IconColor, InName, and UE::Insights::FBaseTreeNode::IsGroup().
SetIcon()
void UE::Insights::FCustomTableTreeNode::SetIcon (const FSlateBrush * InIconBrush) inline private
Sets an icon brush for this node.
Definition at line 223 of file TableTreeNode.h.
References IconBrush.
Field Documentation
Color
FLinearColor UE::Insights::FCustomTableTreeNode::Color private
The color tint for the name text of this node.
Definition at line 246 of file TableTreeNode.h.
Referenced by FCustomTableTreeNode(), FCustomTableTreeNode(), FCustomTableTreeNode(), GetColor(), and INSIGHTS_DECLARE_RTTI().
IconBrush
const FSlateBrush* UE::Insights::FCustomTableTreeNode::IconBrush private
The icon of this node.
Definition at line 240 of file TableTreeNode.h.
Referenced by FCustomTableTreeNode(), FCustomTableTreeNode(), FCustomTableTreeNode(), GetIcon(), INSIGHTS_DECLARE_RTTI(), and SetIcon().
IconColor
FLinearColor UE::Insights::FCustomTableTreeNode::IconColor private
The color tint for the icon of this node.
Definition at line 243 of file TableTreeNode.h.
Referenced by FCustomTableTreeNode(), FCustomTableTreeNode(), FCustomTableTreeNode(), GetIconColor(), and INSIGHTS_DECLARE_RTTI().
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Table/ViewModels/TableTreeNode.h