Unreal Engine 5.6 C++ API: UE::GC::FSchemaView Class Reference
UE::GC::FSchemaView Class Reference
Describes all strong GC references in a class or struct.
#include "GarbageCollectionSchema.h"
Public Member Functions
FSchemaView ()
FSchemaView (const FMemberWord *Data, EOrigin Origin=EOrigin::Other)
FSchemaView (ENoInit)
FSchemaView (FSchemaView View, EOrigin Origin)
FSchemaHeader & GetHeader ()
EOrigin GetOrigin () const
uint32 GetStructStride () const
const FMemberWord * GetWords () const
bool IsEmpty () const
void SetOrigin (EOrigin Origin)
FSchemaHeader * TryGetHeader ()
Private Attributes
uint64 Handle
Static Private Attributes
static constexpr uint64 OriginBit = 1
Detailed Description
Describes all strong GC references in a class or struct.
Definition at line 113 of file GarbageCollectionSchema.h.
Constructor & Destructor Documentation
FSchemaView() [1/4]
UE::GC::FSchemaView::FSchemaView () inline
Definition at line 119 of file GarbageCollectionSchema.h.
References Handle.
Referenced by FSchemaView().
FSchemaView() [2/4]
UE::GC::FSchemaView::FSchemaView (ENoInit) inline
Definition at line 120 of file GarbageCollectionSchema.h.
FSchemaView() [3/4]
UE::GC::FSchemaView::FSchemaView (FSchemaView View, EOrigin Origin) inline
Definition at line 121 of file GarbageCollectionSchema.h.
References FSchemaView(), GetWords(), and Origin.
FSchemaView() [4/4]
UE::GC::FSchemaView::FSchemaView (const FMemberWord * Data, EOrigin Origin = EOrigin::Other) inline explicit
Definition at line 122 of file GarbageCollectionSchema.h.
References Handle, Origin, and UE::GC::Other.
Member Function Documentation
GetHeader()
FSchemaHeader & UE::GC::FSchemaView::GetHeader ()
GetOrigin()
EOrigin UE::GC::FSchemaView::GetOrigin () const inline
Definition at line 130 of file GarbageCollectionSchema.h.
References Handle, and OriginBit.
Referenced by UE::GC::Private::VisitMembers().
GetStructStride()
uint32 UE::GC::FSchemaView::GetStructStride () const inline
Precondition
!IsEmpty()
Definition at line 135 of file GarbageCollectionSchema.h.
References GetWords().
Referenced by UE::GC::Private::VisitOptional(), UE::GC::Private::VisitSparseStructArray(), and UE::GC::Private::VisitStructs().
GetWords()
const FMemberWord * UE::GC::FSchemaView::GetWords () const inline
Definition at line 129 of file GarbageCollectionSchema.h.
References Handle, and OriginBit.
Referenced by FSchemaView(), GetStructStride(), IsEmpty(), and UE::GC::Private::VisitMembers().
IsEmpty()
bool UE::GC::FSchemaView::IsEmpty () const inline
Definition at line 131 of file GarbageCollectionSchema.h.
References GetWords().
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects(), UE::GC::Private::VisitMembers(), UE::GC::Private::VisitOptional(), UE::GC::Private::VisitSparseStructArray(), and UE::GC::Private::VisitStructs().
SetOrigin()
void UE::GC::FSchemaView::SetOrigin (EOrigin Origin) inline
Definition at line 132 of file GarbageCollectionSchema.h.
References Handle, Origin, and OriginBit.
TryGetHeader()
FSchemaHeader * UE::GC::FSchemaView::TryGetHeader ()
Field Documentation
Handle
uint64 UE::GC::FSchemaView::Handle private
Definition at line 116 of file GarbageCollectionSchema.h.
Referenced by FSchemaView(), FSchemaView(), GetOrigin(), GetWords(), and SetOrigin().
OriginBit
uint64 UE::GC::FSchemaView::OriginBit = 1 static constexpr private
Definition at line 115 of file GarbageCollectionSchema.h.
Referenced by GetOrigin(), GetWords(), and SetOrigin().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/GarbageCollectionSchema.h