Unreal Engine 5.6 C++ API: ICurveEditorToolExtension Class Reference
ICurveEditorToolExtension Class Reference abstract
You can extend the Curve Editor toolset by implementing this interface.
#include "ICurveEditorToolExtension.h"
Public Member Functions
ICurveEditorToolExtension ()
virtual ~ICurveEditorToolExtension ()
virtual void BindCommands (TSharedRef< FUICommandList > CommandBindings)
Allows the tool to bind commands.
virtual FText GetDescription () const =0
virtual FSlateIcon GetIcon () const =0
virtual FText GetLabel () const =0
virtual TSharedPtr< FStructOnScope > GetToolOptions () const
virtual void OnFinishedPointerInput ()
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
virtual FReply OnKeyDown (TSharedRef< SWidget > OwningWidget, const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
virtual FReply OnKeyUp (TSharedRef< SWidget > OwningWidget, const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
virtual FReply OnMouseButtonDoubleClick (TSharedRef< SWidget > OwningWidget, const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
virtual FReply OnMouseButtonDown (TSharedRef< SWidget > OwningWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
virtual FReply OnMouseButtonUp (TSharedRef< SWidget > OwningWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
virtual FReply OnMouseMove (TSharedRef< SWidget > OwningWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
virtual void OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 PaintOnLayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const =0
virtual void OnToolActivated ()=0
This is called when the tool is activated by switching from another tool.
virtual void OnToolDeactivated ()=0
This is called when the tool is deactivated by switching to another tool.
virtual void OnToolOptionsUpdated (const FPropertyChangedEvent &PropertyChangedEvent)
virtual void SetToolID (const FCurveEditorToolID InToolID)
Allows the tool to add menu items to the toolbar in the Curve Editor.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Data Fields
FOnOptionsRefresh OnOptionsRefreshDelegate
Protected Attributes
FCurveEditorToolID ToolID
Detailed Description
You can extend the Curve Editor toolset by implementing this interface.
The Curve Editor guarantees that only one tool will be active at any given time. A tool needs to specify if they handled certain mouse events so that these events can be bubbled to the rest of the Curve Editor to allow common functionality of selecting/deselecting keys, panning, etc.
Definition at line 83 of file ICurveEditorToolExtension.h.
Constructor & Destructor Documentation
ICurveEditorToolExtension()
ICurveEditorToolExtension::ICurveEditorToolExtension () inline
Definition at line 86 of file ICurveEditorToolExtension.h.
References ToolID, and Unset.
~ICurveEditorToolExtension()
virtual ICurveEditorToolExtension::~ICurveEditorToolExtension () inline virtual
Definition at line 91 of file ICurveEditorToolExtension.h.
Member Function Documentation
BindCommands()
virtual void ICurveEditorToolExtension::BindCommands (TSharedRef< FUICommandList > CommandBindings) inline virtual
Allows the tool to bind commands.
Parameters
CommandBindings The existing command bindings to map to.
Definition at line 125 of file ICurveEditorToolExtension.h.
GetDescription()
virtual FText ICurveEditorToolExtension::GetDescription () const pure virtual
Returns
Description for this tool. Displayed by toolbar combo button.
GetIcon()
virtual FSlateIcon ICurveEditorToolExtension::GetIcon () const pure virtual
Returns
Icon for this tool. Displayed by toolbar combo button.
GetLabel()
virtual FText ICurveEditorToolExtension::GetLabel () const pure virtual
Returns
Label for this tool. Displayed by toolbar combo button.
GetToolOptions()
virtual TSharedPtr< FStructOnScope > ICurveEditorToolExtension::GetToolOptions () const inline virtual
Definition at line 104 of file ICurveEditorToolExtension.h.
OnFinishedPointerInput()
virtual void ICurveEditorToolExtension::OnFinishedPointerInput () inline virtual
Definition at line 102 of file ICurveEditorToolExtension.h.
OnFocusLost()
virtual void ICurveEditorToolExtension::OnFocusLost (const FFocusEvent & InFocusEvent) inline virtual
Definition at line 103 of file ICurveEditorToolExtension.h.
OnKeyDown()
virtual FReply ICurveEditorToolExtension::OnKeyDown (TSharedRef< SWidget > OwningWidget, const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline virtual
Definition at line 96 of file ICurveEditorToolExtension.h.
References FReply::Unhandled().
OnKeyUp()
virtual FReply ICurveEditorToolExtension::OnKeyUp (TSharedRef< SWidget > OwningWidget, const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline virtual
Definition at line 97 of file ICurveEditorToolExtension.h.
References FReply::Unhandled().
OnMouseButtonDoubleClick()
virtual FReply ICurveEditorToolExtension::OnMouseButtonDoubleClick (TSharedRef< SWidget > OwningWidget, const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) inline virtual
Definition at line 101 of file ICurveEditorToolExtension.h.
References FReply::Unhandled().
OnMouseButtonDown()
virtual FReply ICurveEditorToolExtension::OnMouseButtonDown (TSharedRef< SWidget > OwningWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Definition at line 98 of file ICurveEditorToolExtension.h.
References MouseEvent, and FReply::Unhandled().
OnMouseButtonUp()
virtual FReply ICurveEditorToolExtension::OnMouseButtonUp (TSharedRef< SWidget > OwningWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Definition at line 99 of file ICurveEditorToolExtension.h.
References MouseEvent, and FReply::Unhandled().
OnMouseMove()
virtual FReply ICurveEditorToolExtension::OnMouseMove (TSharedRef< SWidget > OwningWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline virtual
Definition at line 100 of file ICurveEditorToolExtension.h.
References MouseEvent, and FReply::Unhandled().
OnPaint()
virtual void ICurveEditorToolExtension::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 PaintOnLayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const pure virtual
OnToolActivated()
virtual void ICurveEditorToolExtension::OnToolActivated () pure virtual
This is called when the tool is activated by switching from another tool.
The current tool (if any) will have OnToolDeactivated called first before the new tool has OnToolActivated called.
OnToolDeactivated()
virtual void ICurveEditorToolExtension::OnToolDeactivated () pure virtual
This is called when the tool is deactivated by switching to another tool.
This will be called before the new tool has OnToolActivated called.
OnToolOptionsUpdated()
virtual void ICurveEditorToolExtension::OnToolOptionsUpdated (const FPropertyChangedEvent & PropertyChangedEvent) inline virtual
Definition at line 105 of file ICurveEditorToolExtension.h.
SetToolID()
virtual void ICurveEditorToolExtension::SetToolID (const FCurveEditorToolID InToolID) inline virtual
Allows the tool to add menu items to the toolbar in the Curve Editor.
Parameters
ToolbarBuilder The existing toolbar builder to add new columns to or to hook into existing sections for.
Definition at line 134 of file ICurveEditorToolExtension.h.
References ToolID.
Tick()
virtual void ICurveEditorToolExtension::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) inline virtual
Definition at line 95 of file ICurveEditorToolExtension.h.
Field Documentation
OnOptionsRefreshDelegate
FOnOptionsRefresh ICurveEditorToolExtension::OnOptionsRefreshDelegate
Definition at line 146 of file ICurveEditorToolExtension.h.
ToolID
FCurveEditorToolID ICurveEditorToolExtension::ToolID protected
Definition at line 149 of file ICurveEditorToolExtension.h.
Referenced by ICurveEditorToolExtension(), and SetToolID().
The documentation for this class was generated from the following file:
Editor/CurveEditor/Public/ICurveEditorToolExtension.h