Unreal Engine 5.6 C++ API: IDisplayClusterConfiguration Class Reference
IDisplayClusterConfiguration Class Reference abstract
Display Cluster configuration module interface.
#include "IDisplayClusterConfiguration.h"
Public Member Functions
virtual ~IDisplayClusterConfiguration ()=default
virtual bool ConfigAsString (const UDisplayClusterConfigurationData *Config, FString &OutString) const =0
Converts configuration data to string.
virtual EDisplayClusterConfigurationVersion GetConfigVersion (const FString &FilePath)=0
Returns version of a specified config file.
virtual bool IsTransactingSnapshot () const =0
Gets the current transaction snapshot status.
virtual UDisplayClusterConfigurationData * LoadConfig (const FString &FilePath, UObject *Owner=nullptr)=0
Load configuration data from specified file.
virtual bool SaveConfig (const UDisplayClusterConfigurationData *Config, const FString &FilePath)=0
Save configuration data to a specified file.
virtual void SetIsSnapshotTransacting (bool bIsSnapshot)=0
Sets the transaction flags so that we don't necessarily re-run the construction scripts all the time.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterConfiguration & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterConfiguration")
Detailed Description
Display Cluster configuration module interface.
Definition at line 17 of file IDisplayClusterConfiguration.h.
Constructor & Destructor Documentation
~IDisplayClusterConfiguration()
virtual IDisplayClusterConfiguration::~IDisplayClusterConfiguration () virtual default
Member Function Documentation
ConfigAsString()
virtual bool IDisplayClusterConfiguration::ConfigAsString (const UDisplayClusterConfigurationData * Config, FString & OutString) const pure virtual
Converts configuration data to string.
Parameters
Config - Configuration data
OutString - String to contain the configuration data
Returns
true if succeeded
Get()
IDisplayClusterConfiguration & IDisplayClusterConfiguration::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 32 of file IDisplayClusterConfiguration.h.
References FModuleManager::GetModuleChecked(), and ModuleName.
GetConfigVersion()
virtual EDisplayClusterConfigurationVersion IDisplayClusterConfiguration::GetConfigVersion (const FString & FilePath) pure virtual
Returns version of a specified config file.
Parameters
FilePath - Config file path
Returns
Config version if succeeded, otherwise nulltpr
IsAvailable()
bool IDisplayClusterConfiguration::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 42 of file IDisplayClusterConfiguration.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
IsTransactingSnapshot()
virtual bool IDisplayClusterConfiguration::IsTransactingSnapshot () const pure virtual
Gets the current transaction snapshot status.
LoadConfig()
virtual UDisplayClusterConfigurationData * IDisplayClusterConfiguration::LoadConfig (const FString & FilePath, UObject * Owner = nullptr) pure virtual
Load configuration data from specified file.
Parameters
FilePath - Config file path
Owner - UObject owner for the configuration data object
Returns
Configuration data if succeeded, otherwise nulltpr
References Owner.
SaveConfig()
virtual bool IDisplayClusterConfiguration::SaveConfig (const UDisplayClusterConfigurationData * Config, const FString & FilePath) pure virtual
Save configuration data to a specified file.
Parameters
Config - Configuration data
FilePath - File to save
Returns
true if succeeded
SetIsSnapshotTransacting()
virtual void IDisplayClusterConfiguration::SetIsSnapshotTransacting (bool bIsSnapshot) pure virtual
Sets the transaction flags so that we don't necessarily re-run the construction scripts all the time.
Field Documentation
ModuleName
const TCHAR* IDisplayClusterConfiguration::ModuleName = TEXT("DisplayClusterConfiguration") static constexpr
Definition at line 20 of file IDisplayClusterConfiguration.h.
Referenced by Get(), and IsAvailable().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterConfiguration/Public/IDisplayClusterConfiguration.h