Unreal Engine 5.6 C++ API: FScriptMapHelper Class Reference
FScriptMapHelper Class Reference
FScriptMapHelper: Pseudo dynamic map.
#include "UnrealType.h"
Public Types
using FIterator = TScriptContainerIterator<FScriptMapHelper>
Public Member Functions
FScriptMapHelper (const FMapProperty *InProperty, const void *InMap)
Constructor, brings together a property and an instance of the property located in memory.
FScriptMapHelper (FProperty *InKeyProp, FProperty *InValueProp, const void *InMap, const FScriptMapLayout &InMapLayout, EMapPropertyFlags InMapFlags)
int32 AddDefaultValue_Invalid_NeedsRehash ()
Adds a blank, constructed value to a given size.
void AddPair (const void *KeyPtr, const void *ValuePtr)
Adds the (key, value) pair to the map, returning true if the element was added, or false if the element was already present and has been overwritten.
FORCEINLINE int32 AddUninitializedValue ()
Add an uninitialized value to the end of the map.
FIterator CreateIterator () const
FIterator CreateIterator (const int32 InLogicalIndex) const
void EmptyValues (int32 Slack=0)
Remove all values from the map, calling destructors, etc as appropriate.
int32 FindInternalIndex (int32 LogicalIdx) const
Maps have gaps in their indices, so this function translates a logical index (ie.
int32 FindLogicalIndex (int32 InternalIdx) const
Maps have gaps in their indices, so this function translates a internal index to an logical index (ie.
int32 FindMapIndexWithKey (const void *PairWithKeyToFind, int32 IndexHint=0) const
Finds the index of an element in a map which matches the key in another pair.
int32 FindMapPairIndexFromHash (const void *KeyPtr)
Finds the associated pair from hash, rather than linearly searching.
uint8 * FindMapPairPtrFromHash (const void *KeyPtr)
Finds the associated pair from hash, rather than linearly searching.
FORCEINLINE uint8 * FindMapPairPtrWithKey (const void *PairWithKeyToFind, int32 IndexHint=0)
Finds the pair in a map which matches the key in another pair.
uint8 * FindNthKeyPtr (int32 N)
Returns a uint8 pointer to the the Nth valid key in the map (skipping invalid entries).
uint8 * FindNthPairPtr (int32 N)
Returns a uint8 pointer to the the Nth valid pair in the map (skipping invalid entries).
const uint8 * FindNthPairPtr (int32 N) const
Returns a uint8 pointer to the the Nth valid pair in the map (skipping invalid entries).
uint8 * FindNthValuePtr (int32 N)
Returns a uint8 pointer to the the Nth valid value in the map (skipping invalid entries).
void * FindOrAdd (const void *KeyPtr)
Finds or adds a new default-constructed value.
uint8 * FindValueFromHash (const void *KeyPtr)
Finds the associated value from hash, rather than linearly searching.
FProperty * GetKeyProperty () const
Returns the property representing the key of the map pair.
FORCEINLINE uint8 * GetKeyPtr (const FIterator Iterator)
Returns a uint8 pointer to the Key (first element) in the map.
FORCEINLINE const uint8 * GetKeyPtr (const FIterator Iterator) const
Returns a const uint8 pointer to the Key (first element) in the map.
FORCEINLINE uint8 * GetKeyPtr (int32 InternalIndex)
Returns a uint8 pointer to the Key (first element) in the map.
FORCEINLINE int32 GetMaxIndex () const
Returns the (non-inclusive) maximum index of elements in the map.
FORCEINLINE uint8 * GetPairPtr (const FIterator Iterator)
Returns a uint8 pointer to the pair in the map.
FORCEINLINE const uint8 * GetPairPtr (const FIterator Iterator) const
Returns a uint8 pointer to the pair in the map.
FORCEINLINE const uint8 * GetPairPtr (const int32 InternalIndex) const
Returns a uint8 pointer to the pair in the map.
FORCEINLINE uint8 * GetPairPtr (int32 InternalIndex)
Returns a uint8 pointer to the pair in the map.
FProperty * GetValueProperty () const
Returns the property representing the value of the map pair.
FORCEINLINE uint8 * GetValuePtr (const FIterator Iterator)
Returns a uint8 pointer to the Value (second element) in the map.
FORCEINLINE const uint8 * GetValuePtr (const FIterator Iterator) const
Returns a const uint8 pointer to the Value (second element) in the map.
FORCEINLINE uint8 * GetValuePtr (int32 InternalIndex)
Returns a uint8 pointer to the Value (second element) in the map.
FORCEINLINE bool IsValidIndex (int32 InternalIndex) const
Index range check.
void MoveAssign (void *InOtherMap)
Move the allocation from another map and make it our own.
FORCEINLINE int32 Num () const
Returns the number of elements in the map.
FORCEINLINE int32 NumUnchecked () const
Returns the number of elements in the map.
void Rehash ()
Rehashes the keys in the map.
void RemoveAt (int32 InternalIndex, int32 Count=1)
Removes an element at the specified index, destroying it.
bool RemovePair (const void *KeyPtr)
Removes the key and its associated value from the map.
Static Public Member Functions
static FScriptMapHelper CreateHelperFormInnerProperties (FProperty *InKeyProperty, FProperty *InValProperty, const void *InMap, EMapPropertyFlags InMapFlags=EMapPropertyFlags::None)
Data Fields
union {
FFreezableScriptMap * FreezableMap
FScriptMap * HeapMap
};
FProperty * KeyProp
EMapPropertyFlags MapFlags
FScriptMapLayout MapLayout
FProperty * ValueProp
Private Types
enum EInternal { Internal }
Private Member Functions
FORCEINLINE FScriptMapHelper (EInternal, FProperty *InKeyProp, FProperty *InValueProp, const void *InMap, const FScriptMapLayout &InMapLayout, EMapPropertyFlags InMapFlags)
void ConstructItem (int32 InternalIndex)
Internal function to call into the property system to construct / initialize elements.
void DestructItems (int32 InternalIndex, int32 Count)
Internal function to call into the property system to destruct elements.
FORCEINLINE uint8 * GetKeyPtrWithoutCheck (int32 InternalIndex)
Returns a uint8 pointer to the key in the array without checking the index.
FORCEINLINE const uint8 * GetKeyPtrWithoutCheck (int32 InternalIndex) const
Returns a const uint8 pointer to the pair in the array without checking the index.
FORCEINLINE uint8 * GetPairPtrWithoutCheck (int32 InternalIndex)
Returns a uint8 pointer to the pair in the array without checking the index.
FORCEINLINE const uint8 * GetPairPtrWithoutCheck (int32 InternalIndex) const
Returns a uint8 pointer to the pair in the array without checking the index.
FORCEINLINE uint8 * GetValuePtrWithoutCheck (int32 InternalIndex)
Returns a uint8 pointer to the pair in the array without checking the index.
FORCEINLINE const uint8 * GetValuePtrWithoutCheck (int32 InternalIndex) const
Returns a const uint8 pointer to the pair in the array without checking the index.
template<typename CallableType>
auto WithScriptMap (CallableType &&Callable) const
Friends
class FMapProperty
Detailed Description
FScriptMapHelper: Pseudo dynamic map.
Used to work with map properties in a sensible way. Note that map can contain invalid entries some number of valid entries (i.e. Num()) can be smaller that the actual number of elements (i.e. GetMaxIndex()).
Internal index naming is used to identify the actual index in the container which can point to an invalid entry. It can be used for methods like Get<Item>Ptr, Get<Item>PtrWithoutCheck or IsValidIndex.
Logical index naming is used to identify only valid entries in the container so it can be smaller than the internal index in case we skipped invalid entries to reach the next valid one. This index is used on method like FindNth<Item>Ptr or FindInternalIndex. This is also the type of index we receive from most editor events (e.g. property change events) so it is strongly suggested to rely on FScriptMapHelper::FIterator to iterate or convert to internal index.
Definition at line 4352 of file UnrealType.h.
Member Typedef Documentation
FIterator
using FScriptMapHelper::FIterator = TScriptContainerIterator<FScriptMapHelper>
Definition at line 4388 of file UnrealType.h.
Member Enumeration Documentation
EInternal
enum FScriptMapHelper::EInternal private
Enumerator
Internal
Definition at line 4354 of file UnrealType.h.
Constructor & Destructor Documentation
FScriptMapHelper() [1/3]
FScriptMapHelper::FScriptMapHelper (const FMapProperty * InProperty, const void * InMap) inline
Constructor, brings together a property and an instance of the property located in memory.
Parameters
InProperty The property associated with this memory
InMap Pointer to raw memory that corresponds to this map. This can be NULL, and sometimes is, but in that case almost all operations will crash.
Definition at line 4378 of file UnrealType.h.
References FScriptMapHelper(), FMapProperty, KeyProp, MapFlags, MapLayout, and ValueProp.
Referenced by FScriptMapHelper(), FScriptMapHelper(), FScriptMapHelper_InContainer::FScriptMapHelper_InContainer(), CreateHelperFormInnerProperties(), GetKeyPtr(), GetKeyPtrWithoutCheck(), GetPairPtr(), GetPairPtr(), GetPairPtrWithoutCheck(), GetValuePtr(), and GetValuePtrWithoutCheck().
FScriptMapHelper() [2/3]
FScriptMapHelper::FScriptMapHelper (FProperty * InKeyProp, FProperty * InValueProp, const void * InMap, const FScriptMapLayout & InMapLayout, EMapPropertyFlags InMapFlags) inline
Definition at line 4383 of file UnrealType.h.
References FScriptMapHelper().
FScriptMapHelper() [3/3]
FORCEINLINE FScriptMapHelper::FScriptMapHelper (EInternal , FProperty * InKeyProp, FProperty * InValueProp, const void * InMap, const FScriptMapLayout & InMapLayout, EMapPropertyFlags InMapFlags) inline private
Definition at line 5104 of file UnrealType.h.
References check, FORCEINLINE, FreezableMap, HeapMap, KeyProp, MapFlags, MapLayout, and ValueProp.
Member Function Documentation
AddDefaultValue_Invalid_NeedsRehash()
int32 FScriptMapHelper::AddDefaultValue_Invalid_NeedsRehash () inline
Adds a blank, constructed value to a given size.
Note that this will create an invalid map because all the keys will be default constructed, and the map needs rehashing.
Returns
The index of the first element added.
Definition at line 4727 of file UnrealType.h.
References checkSlow, ConstructItem(), Map, MapLayout, and WithScriptMap().
AddPair()
void FScriptMapHelper::AddPair (const void * KeyPtr, const void * ValuePtr) inline
Adds the (key, value) pair to the map, returning true if the element was added, or false if the element was already present and has been overwritten.
Definition at line 4966 of file UnrealType.h.
References A, B, Map, MapLayout, FMemory::Memzero(), and WithScriptMap().
AddUninitializedValue()
FORCEINLINE int32 FScriptMapHelper::AddUninitializedValue () inline
Add an uninitialized value to the end of the map.
Returns
The index of the added element.
Definition at line 4689 of file UnrealType.h.
References checkSlow, FORCEINLINE, Map, MapLayout, and WithScriptMap().
ConstructItem()
void FScriptMapHelper::ConstructItem (int32 InternalIndex) inline private
Internal function to call into the property system to construct / initialize elements.
Parameters
InternalIndex First item to construct.
Count Number of items to construct.
Definition at line 5131 of file UnrealType.h.
References check, IsValidIndex(), KeyProp, Map, MapLayout, FMemory::Memzero(), ValueProp, and WithScriptMap().
Referenced by AddDefaultValue_Invalid_NeedsRehash().
CreateHelperFormInnerProperties()
FScriptMapHelper FScriptMapHelper::CreateHelperFormInnerProperties (FProperty * InKeyProperty, FProperty * InValProperty, const void * InMap, EMapPropertyFlags InMapFlags = EMapPropertyFlags::None) inline static
Definition at line 5091 of file UnrealType.h.
References FScriptMapHelper(), FProperty::GetMinAlignment(), TScriptMap< FDefaultSetAllocator, FScriptMap >::GetScriptLayout(), and FProperty::GetSize().
CreateIterator() [1/2]
FIterator FScriptMapHelper::CreateIterator () const inline
Definition at line 4390 of file UnrealType.h.
CreateIterator() [2/2]
FIterator FScriptMapHelper::CreateIterator (const int32 InLogicalIndex) const inline
Definition at line 4395 of file UnrealType.h.
DestructItems()
void FScriptMapHelper::DestructItems (int32 InternalIndex, int32 Count) inline private
Internal function to call into the property system to destruct elements.
Definition at line 5160 of file UnrealType.h.
References check, Count, IsValidIndex(), KeyProp, Map, MapLayout, ValueProp, and WithScriptMap().
EmptyValues()
void FScriptMapHelper::EmptyValues (int32 Slack = 0) inline
Remove all values from the map, calling destructors, etc as appropriate.
Parameters
Slack used to presize the set for a subsequent add, to avoid reallocation.
Definition at line 4703 of file UnrealType.h.
References checkSlow, DestructItems(), Map, MapLayout, NumUnchecked(), and WithScriptMap().
FindInternalIndex()
int32 FScriptMapHelper::FindInternalIndex (int32 LogicalIdx) const inline
Maps have gaps in their indices, so this function translates a logical index (ie.
Nth element) to an internal index that can be used for the other functions in this class. NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Definition at line 4794 of file UnrealType.h.
References GetMaxIndex(), INDEX_NONE, IsValidIndex(), Map, Num, and WithScriptMap().
Referenced by FindNthKeyPtr(), FindNthPairPtr(), FindNthPairPtr(), and FindNthValuePtr().
FindLogicalIndex()
int32 FScriptMapHelper::FindLogicalIndex (int32 InternalIdx) const inline
Maps have gaps in their indices, so this function translates a internal index to an logical index (ie.
Nth element). NOTE: This is slow, do not use this for iteration!
Definition at line 4831 of file UnrealType.h.
References GetMaxIndex(), INDEX_NONE, IsValidIndex(), Map, Num, and WithScriptMap().
FindMapIndexWithKey()
int32 FScriptMapHelper::FindMapIndexWithKey (const void * PairWithKeyToFind, int32 IndexHint = 0) const inline
Finds the index of an element in a map which matches the key in another pair.
Parameters
PairWithKeyToFind The address of a map pair which contains the key to search for.
IndexHint The index to start searching from.
Returns
The index of an element found in MapHelper, or -1 if none was found.
Definition at line 4868 of file UnrealType.h.
References check, FProperty::Identical, INDEX_NONE, Map, MapLayout, and WithScriptMap().
Referenced by FindMapPairPtrWithKey().
FindMapPairIndexFromHash()
int32 FScriptMapHelper::FindMapPairIndexFromHash (const void * KeyPtr) inline
Finds the associated pair from hash, rather than linearly searching.
Definition at line 4929 of file UnrealType.h.
References A, B, Map, MapLayout, and WithScriptMap().
Referenced by FindMapPairPtrFromHash().
FindMapPairPtrFromHash()
uint8 * FScriptMapHelper::FindMapPairPtrFromHash (const void * KeyPtr) inline
Finds the associated pair from hash, rather than linearly searching.
Definition at line 4944 of file UnrealType.h.
References FindMapPairIndexFromHash(), and GetPairPtrWithoutCheck().
FindMapPairPtrWithKey()
FORCEINLINE uint8 * FScriptMapHelper::FindMapPairPtrWithKey (const void * PairWithKeyToFind, int32 IndexHint = 0) inline
Finds the pair in a map which matches the key in another pair.
Parameters
PairWithKeyToFind The address of a map pair which contains the key to search for.
IndexHint The index to start searching from.
Returns
A pointer to the found pair, or nullptr if none was found.
Definition at line 4921 of file UnrealType.h.
References FindMapIndexWithKey(), FORCEINLINE, and GetPairPtrWithoutCheck().
FindNthKeyPtr()
uint8 * FScriptMapHelper::FindNthKeyPtr (int32 N) inline
Returns a uint8 pointer to the the Nth valid key in the map (skipping invalid entries).
NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Returns
Pointer to the element, or nullptr if the index is invalid.
Definition at line 4637 of file UnrealType.h.
References FindInternalIndex(), GetKeyPtrWithoutCheck(), and INDEX_NONE.
FindNthPairPtr() [1/2]
uint8 * FScriptMapHelper::FindNthPairPtr (int32 N) inline
Returns a uint8 pointer to the the Nth valid pair in the map (skipping invalid entries).
NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Returns
Pointer to the element, or nullptr if the index is invalid.
Definition at line 4625 of file UnrealType.h.
References FindInternalIndex(), GetPairPtrWithoutCheck(), and INDEX_NONE.
FindNthPairPtr() [2/2]
const uint8 * FScriptMapHelper::FindNthPairPtr (int32 N) const inline
Returns a uint8 pointer to the the Nth valid pair in the map (skipping invalid entries).
NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Returns
Pointer to the element, or nullptr if the index is invalid.
Definition at line 4661 of file UnrealType.h.
References FindInternalIndex(), GetPairPtrWithoutCheck(), and INDEX_NONE.
FindNthValuePtr()
uint8 * FScriptMapHelper::FindNthValuePtr (int32 N) inline
Returns a uint8 pointer to the the Nth valid value in the map (skipping invalid entries).
NOTE: This is slow, do not use this for iteration! Use CreateIterator() instead.
Returns
Pointer to the element, or nullptr if the index is invalid.
Definition at line 4649 of file UnrealType.h.
References FindInternalIndex(), GetValuePtrWithoutCheck(), and INDEX_NONE.
FindOrAdd()
void * FScriptMapHelper::FindOrAdd (const void * KeyPtr) inline
Finds or adds a new default-constructed value.
No need to rehash after calling. The hash table must be properly hashed before calling.
Returns
The address to the value, not the pair
Definition at line 5032 of file UnrealType.h.
References A, B, Map, MapLayout, FMemory::Memzero(), and WithScriptMap().
FindValueFromHash()
uint8 * FScriptMapHelper::FindValueFromHash (const void * KeyPtr) inline
Finds the associated value from hash, rather than linearly searching.
Definition at line 4952 of file UnrealType.h.
References A, B, Map, MapLayout, and WithScriptMap().
GetKeyProperty()
FProperty * FScriptMapHelper::GetKeyProperty () const inline
Returns the property representing the key of the map pair.
Returns
The property representing the key of the map pair.
Definition at line 4745 of file UnrealType.h.
References KeyProp.
GetKeyPtr() [1/3]
FORCEINLINE uint8 * FScriptMapHelper::GetKeyPtr (const FIterator Iterator) inline
Returns a uint8 pointer to the Key (first element) in the map.
Currently identical to GetPairPtr, but provides clarity of purpose and avoids exposing implementation details of TMap.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the key, or will fail a check if an invalid iterator is provided.
Definition at line 4568 of file UnrealType.h.
References checkf, FORCEINLINE, TScriptContainerIterator< ContainerType >::GetInternalIndex(), Map, MapLayout, TEXT, and WithScriptMap().
GetKeyPtr() [2/3]
FORCEINLINE const uint8 * FScriptMapHelper::GetKeyPtr (const FIterator Iterator) const inline
Returns a const uint8 pointer to the Key (first element) in the map.
Currently identical to GetPairPtr, but provides clarity of purpose and avoids exposing implementation details of TMap.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the key, or will fail a check if an invalid iterator is provided.
Definition at line 4586 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetKeyPtr().
GetKeyPtr() [3/3]
FORCEINLINE uint8 * FScriptMapHelper::GetKeyPtr (int32 InternalIndex) inline
Returns a uint8 pointer to the Key (first element) in the map.
Currently identical to GetPairPtr, but provides clarity of purpose and avoids exposing implementation details of TMap.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the key, or nullptr if the map is empty.
Definition at line 4494 of file UnrealType.h.
References checkf, FORCEINLINE, IsValidIndex(), Map, MapLayout, TEXT, and WithScriptMap().
Referenced by GetKeyPtr().
GetKeyPtrWithoutCheck() [1/2]
FORCEINLINE uint8 * FScriptMapHelper::GetKeyPtrWithoutCheck (int32 InternalIndex) inline private
Returns a uint8 pointer to the key in the array without checking the index.
Parameters
InternalIndex index of the key to return a pointer to.
Returns
Pointer to the key, or nullptr if the map is empty.
Definition at line 5251 of file UnrealType.h.
References FORCEINLINE, Map, MapLayout, and WithScriptMap().
Referenced by FindNthKeyPtr(), and GetKeyPtrWithoutCheck().
GetKeyPtrWithoutCheck() [2/2]
FORCEINLINE const uint8 * FScriptMapHelper::GetKeyPtrWithoutCheck (int32 InternalIndex) const inline private
Returns a const uint8 pointer to the pair in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 5263 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetKeyPtrWithoutCheck().
GetMaxIndex()
FORCEINLINE int32 FScriptMapHelper::GetMaxIndex () const inline
Returns the (non-inclusive) maximum index of elements in the map.
Returns
The (non-inclusive) maximum index of elements in the map.
Definition at line 4441 of file UnrealType.h.
References checkSlow, FORCEINLINE, Map, and WithScriptMap().
Referenced by FindInternalIndex(), and FindLogicalIndex().
GetPairPtr() [1/4]
FORCEINLINE uint8 * FScriptMapHelper::GetPairPtr (const FIterator Iterator) inline
Returns a uint8 pointer to the pair in the map.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the pair, or will fail a check if an invalid iterator is provided.
Definition at line 4538 of file UnrealType.h.
References checkf, FORCEINLINE, TScriptContainerIterator< ContainerType >::GetInternalIndex(), Map, MapLayout, TEXT, and WithScriptMap().
GetPairPtr() [2/4]
FORCEINLINE const uint8 * FScriptMapHelper::GetPairPtr (const FIterator Iterator) const inline
Returns a uint8 pointer to the pair in the map.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the pair, or will fail a check if an invalid iterator is provided.
Definition at line 4554 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetPairPtr().
GetPairPtr() [3/4]
FORCEINLINE const uint8 * FScriptMapHelper::GetPairPtr (const int32 InternalIndex) const inline
Returns a uint8 pointer to the pair in the map.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 4480 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetPairPtr().
GetPairPtr() [4/4]
FORCEINLINE uint8 * FScriptMapHelper::GetPairPtr (int32 InternalIndex) inline
Returns a uint8 pointer to the pair in the map.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 4458 of file UnrealType.h.
References checkf, FORCEINLINE, IsValidIndex(), Map, MapLayout, TEXT, and WithScriptMap().
Referenced by GetPairPtr(), and GetPairPtr().
GetPairPtrWithoutCheck() [1/2]
FORCEINLINE uint8 * FScriptMapHelper::GetPairPtrWithoutCheck (int32 InternalIndex) inline private
Returns a uint8 pointer to the pair in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 5227 of file UnrealType.h.
References FORCEINLINE, Map, MapLayout, and WithScriptMap().
Referenced by FindMapPairPtrFromHash(), FindMapPairPtrWithKey(), FindNthPairPtr(), FindNthPairPtr(), and GetPairPtrWithoutCheck().
GetPairPtrWithoutCheck() [2/2]
FORCEINLINE const uint8 * FScriptMapHelper::GetPairPtrWithoutCheck (int32 InternalIndex) const inline private
Returns a uint8 pointer to the pair in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 5239 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetPairPtrWithoutCheck().
GetValueProperty()
FProperty * FScriptMapHelper::GetValueProperty () const inline
Returns the property representing the value of the map pair.
Returns
The property representing the value of the map pair.
Definition at line 4755 of file UnrealType.h.
References ValueProp.
GetValuePtr() [1/3]
FORCEINLINE uint8 * FScriptMapHelper::GetValuePtr (const FIterator Iterator) inline
Returns a uint8 pointer to the Value (second element) in the map.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the value, or will fail a check if an invalid iterator is provided.
Definition at line 4598 of file UnrealType.h.
References checkf, FORCEINLINE, TScriptContainerIterator< ContainerType >::GetInternalIndex(), Map, MapLayout, TEXT, and WithScriptMap().
GetValuePtr() [2/3]
FORCEINLINE const uint8 * FScriptMapHelper::GetValuePtr (const FIterator Iterator) const inline
Returns a const uint8 pointer to the Value (second element) in the map.
Parameters
Iterator A valid iterator of the item to return a pointer to.
Returns
Pointer to the value, or will fail a check if an invalid iterator is provided.
Definition at line 4614 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetValuePtr().
GetValuePtr() [3/3]
FORCEINLINE uint8 * FScriptMapHelper::GetValuePtr (int32 InternalIndex) inline
Returns a uint8 pointer to the Value (second element) in the map.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the value, or nullptr if the map is empty.
Definition at line 4516 of file UnrealType.h.
References checkf, FORCEINLINE, IsValidIndex(), Map, MapLayout, TEXT, and WithScriptMap().
Referenced by GetValuePtr().
GetValuePtrWithoutCheck() [1/2]
FORCEINLINE uint8 * FScriptMapHelper::GetValuePtrWithoutCheck (int32 InternalIndex) inline private
Returns a uint8 pointer to the pair in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 5275 of file UnrealType.h.
References FORCEINLINE, Map, MapLayout, and WithScriptMap().
Referenced by FindNthValuePtr(), and GetValuePtrWithoutCheck().
GetValuePtrWithoutCheck() [2/2]
FORCEINLINE const uint8 * FScriptMapHelper::GetValuePtrWithoutCheck (int32 InternalIndex) const inline private
Returns a const uint8 pointer to the pair in the array without checking the index.
Parameters
InternalIndex index of the item to return a pointer to.
Returns
Pointer to the pair, or nullptr if the map is empty.
Definition at line 5287 of file UnrealType.h.
References FScriptMapHelper(), FORCEINLINE, and GetValuePtrWithoutCheck().
IsValidIndex()
FORCEINLINE bool FScriptMapHelper::IsValidIndex (int32 InternalIndex) const inline
Index range check.
Parameters
InternalIndex Index to check
Returns
true if accessing this element is legal.
Definition at line 4407 of file UnrealType.h.
References FORCEINLINE, Map, and WithScriptMap().
Referenced by ConstructItem(), DestructItems(), FindInternalIndex(), FindLogicalIndex(), GetKeyPtr(), GetPairPtr(), and GetValuePtr().
MoveAssign()
void FScriptMapHelper::MoveAssign (void * InOtherMap) inline
Move the allocation from another map and make it our own.
Note
The maps MUST be of the same type, and this function will NOT validate that!
Parameters
InOtherMap The map to move the allocation from.
Definition at line 4673 of file UnrealType.h.
References checkSlow, DestructItems(), Map, MapLayout, Num, and WithScriptMap().
Num()
FORCEINLINE int32 FScriptMapHelper::Num () const inline
Returns the number of elements in the map.
Returns
The number of elements in the map.
Definition at line 4417 of file UnrealType.h.
References checkSlow, FORCEINLINE, Map, and WithScriptMap().
NumUnchecked()
FORCEINLINE int32 FScriptMapHelper::NumUnchecked () const inline
Returns the number of elements in the map.
Needed to allow reading of the num when the map is 'invalid' during its intrusive unset state.
Returns
The number of elements in the map.
Definition at line 4429 of file UnrealType.h.
References checkSlow, FORCEINLINE, Map, and WithScriptMap().
Referenced by EmptyValues().
Rehash()
void FScriptMapHelper::Rehash ()
Rehashes the keys in the map.
This function must be called to create a valid map.
RemoveAt()
void FScriptMapHelper::RemoveAt (int32 InternalIndex, int32 Count = 1) inline
Removes an element at the specified index, destroying it.
Parameters
InternalIndex The index of the element to remove.
Definition at line 4765 of file UnrealType.h.
References check, Count, DestructItems(), Map, MapLayout, and WithScriptMap().
Referenced by RemovePair().
RemovePair()
bool FScriptMapHelper::RemovePair (const void * KeyPtr) inline
Removes the key and its associated value from the map.
Definition at line 5069 of file UnrealType.h.
References A, B, Map, MapLayout, RemoveAt(), and WithScriptMap().
WithScriptMap()
template<typename CallableType> auto FScriptMapHelper::WithScriptMap (CallableType && Callable) const inline private
Definition at line 4359 of file UnrealType.h.
References FreezableMap, HeapMap, and MapFlags.
Referenced by AddDefaultValue_Invalid_NeedsRehash(), AddPair(), AddUninitializedValue(), ConstructItem(), DestructItems(), EmptyValues(), FindInternalIndex(), FindLogicalIndex(), FindMapIndexWithKey(), FindMapPairIndexFromHash(), FindOrAdd(), FindValueFromHash(), GetKeyPtr(), GetKeyPtr(), GetKeyPtrWithoutCheck(), GetMaxIndex(), GetPairPtr(), GetPairPtr(), GetPairPtrWithoutCheck(), GetValuePtr(), GetValuePtr(), GetValuePtrWithoutCheck(), IsValidIndex(), MoveAssign(), Num(), NumUnchecked(), RemoveAt(), and RemovePair().
Friends And Related Symbol Documentation
FMapProperty
friend class FMapProperty friend
Definition at line 4356 of file UnrealType.h.
References FMapProperty.
Referenced by FScriptMapHelper(), FScriptMapHelper_InContainer::FScriptMapHelper_InContainer(), and FMapProperty.
Field Documentation
[union]
union { ... } FScriptMapHelper
FreezableMap
FFreezableScriptMap* FScriptMapHelper::FreezableMap
Definition at line 5298 of file UnrealType.h.
Referenced by FScriptMapHelper(), and WithScriptMap().
HeapMap
FScriptMap* FScriptMapHelper::HeapMap
Definition at line 5297 of file UnrealType.h.
Referenced by FScriptMapHelper(), and WithScriptMap().
KeyProp
FProperty* FScriptMapHelper::KeyProp
Definition at line 5293 of file UnrealType.h.
Referenced by FScriptMapHelper(), FScriptMapHelper(), ConstructItem(), DestructItems(), and GetKeyProperty().
MapFlags
EMapPropertyFlags FScriptMapHelper::MapFlags
Definition at line 5301 of file UnrealType.h.
Referenced by FScriptMapHelper(), FScriptMapHelper(), and WithScriptMap().
MapLayout
FScriptMapLayout FScriptMapHelper::MapLayout
Definition at line 5300 of file UnrealType.h.
Referenced by FScriptMapHelper(), FScriptMapHelper(), AddDefaultValue_Invalid_NeedsRehash(), AddPair(), AddUninitializedValue(), ConstructItem(), DestructItems(), EmptyValues(), FindMapIndexWithKey(), FindMapPairIndexFromHash(), FindOrAdd(), FindValueFromHash(), GetKeyPtr(), GetKeyPtr(), GetKeyPtrWithoutCheck(), GetPairPtr(), GetPairPtr(), GetPairPtrWithoutCheck(), GetValuePtr(), GetValuePtr(), GetValuePtrWithoutCheck(), MoveAssign(), RemoveAt(), and RemovePair().
ValueProp
FProperty* FScriptMapHelper::ValueProp
Definition at line 5294 of file UnrealType.h.
Referenced by FScriptMapHelper(), FScriptMapHelper(), ConstructItem(), DestructItems(), and GetValueProperty().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h