Unreal Engine 5.6 C++ API: FDeferredForces Class Reference
FDeferredForces Class Reference
#include "DeferredForces.h"
Data Structures
struct FAddImpulseAtPositionData
struct FAddImpulseData
struct FAddTorqueInRadiansData
struct FApplyForceAtPositionData
struct FApplyForceData
Public Member Functions
void Add (const FAddImpulseAtPositionData &ApplyImpulseAtPositionDataIn)
void Add (const FAddImpulseData &ApplyImpulseDataIn)
void Add (const FAddTorqueInRadiansData &ApplyTorqueDataIn)
void Add (const FApplyForceAtPositionData &ApplyForceAtPositionDataIn)
void Add (const FApplyForceData &ApplyForceDataIn)
void Apply (Chaos::FRigidBodyHandle_Internal *RigidHandle)
Private Member Functions
void AddForce (Chaos::FRigidBodyHandle_Internal *RigidHandle, const FApplyForceData &DataIn)
void AddForceAtPosition (Chaos::FRigidBodyHandle_Internal *RigidHandle, const FApplyForceAtPositionData &DataIn)
void AddImpulse (Chaos::FRigidBodyHandle_Internal *RigidHandle, const FAddImpulseData &DataIn)
void AddImpulseAtPosition (Chaos::FRigidBodyHandle_Internal *RigidHandle, const FAddImpulseAtPositionData &DataIn)
void AddTorque (Chaos::FRigidBodyHandle_Internal *RigidHandle, const FAddTorqueInRadiansData &DataIn)
Private Attributes
TArray< FApplyForceAtPositionData > ApplyForceAtPositionDatas
TArray< FApplyForceData > ApplyForceDatas
TArray< FAddImpulseAtPositionData > ApplyImpulseAtPositionDatas
TArray< FAddImpulseData > ApplyImpulseDatas
TArray< FAddTorqueInRadiansData > ApplyTorqueDatas
Detailed Description
Definition at line 27 of file DeferredForces.h.
Member Function Documentation
Add() [1/5]
void FDeferredForces::Add (const FAddImpulseAtPositionData & ApplyImpulseAtPositionDataIn) inline
Definition at line 125 of file DeferredForces.h.
References ApplyImpulseAtPositionDatas.
Add() [2/5]
void FDeferredForces::Add (const FAddImpulseData & ApplyImpulseDataIn) inline
Definition at line 120 of file DeferredForces.h.
References ApplyImpulseDatas.
Add() [3/5]
void FDeferredForces::Add (const FAddTorqueInRadiansData & ApplyTorqueDataIn) inline
Definition at line 115 of file DeferredForces.h.
References ApplyTorqueDatas.
Add() [4/5]
void FDeferredForces::Add (const FApplyForceAtPositionData & ApplyForceAtPositionDataIn) inline
Definition at line 110 of file DeferredForces.h.
References ApplyForceAtPositionDatas.
Add() [5/5]
void FDeferredForces::Add (const FApplyForceData & ApplyForceDataIn) inline
Definition at line 105 of file DeferredForces.h.
References ApplyForceDatas.
AddForce()
void FDeferredForces::AddForce (Chaos::FRigidBodyHandle_Internal * RigidHandle, const FApplyForceData & DataIn) private
Referenced by Apply().
AddForceAtPosition()
void FDeferredForces::AddForceAtPosition (Chaos::FRigidBodyHandle_Internal * RigidHandle, const FApplyForceAtPositionData & DataIn) private
Referenced by Apply().
AddImpulse()
void FDeferredForces::AddImpulse (Chaos::FRigidBodyHandle_Internal * RigidHandle, const FAddImpulseData & DataIn) private
Referenced by Apply().
AddImpulseAtPosition()
void FDeferredForces::AddImpulseAtPosition (Chaos::FRigidBodyHandle_Internal * RigidHandle, const FAddImpulseAtPositionData & DataIn) private
Referenced by Apply().
AddTorque()
void FDeferredForces::AddTorque (Chaos::FRigidBodyHandle_Internal * RigidHandle, const FAddTorqueInRadiansData & DataIn) private
Referenced by Apply().
Apply()
void FDeferredForces::Apply (Chaos::FRigidBodyHandle_Internal * RigidHandle) inline
Definition at line 131 of file DeferredForces.h.
References AddForce(), AddForceAtPosition(), AddImpulse(), AddImpulseAtPosition(), AddTorque(), ApplyForceAtPositionDatas, ApplyForceDatas, ApplyImpulseAtPositionDatas, ApplyImpulseDatas, and ApplyTorqueDatas.
Field Documentation
ApplyForceAtPositionDatas
TArray<FApplyForceAtPositionData> FDeferredForces::ApplyForceAtPositionDatas private
Definition at line 174 of file DeferredForces.h.
Referenced by Add(), and Apply().
ApplyForceDatas
TArray<FApplyForceData> FDeferredForces::ApplyForceDatas private
Definition at line 173 of file DeferredForces.h.
Referenced by Add(), and Apply().
ApplyImpulseAtPositionDatas
TArray<FAddImpulseAtPositionData> FDeferredForces::ApplyImpulseAtPositionDatas private
Definition at line 177 of file DeferredForces.h.
Referenced by Add(), and Apply().
ApplyImpulseDatas
TArray<FAddImpulseData> FDeferredForces::ApplyImpulseDatas private
Definition at line 176 of file DeferredForces.h.
Referenced by Add(), and Apply().
ApplyTorqueDatas
TArray<FAddTorqueInRadiansData> FDeferredForces::ApplyTorqueDatas private
Definition at line 175 of file DeferredForces.h.
Referenced by Add(), and Apply().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosVehiclesPlugin/Source/ChaosVehicles/Public/DeferredForces.h