Unreal Engine 5.6 C++ API: FScopedDurationTimer Class Reference
FScopedDurationTimer Class Reference
Utility class for tracking the duration of a scoped action (the user doesn't have to call Start() and Stop() manually).
#include "ScopedTimers.h"
Public Member Functions
FScopedDurationTimer (double &AccumulatorIn)
~FScopedDurationTimer ()
Dtor, updating seconds with time delta.
Public Member Functions inherited from FDurationTimer
FDurationTimer (double &AccumulatorIn)
double Start ()
double Stop ()
Additional Inherited Members
Protected Attributes inherited from FDurationTimer
double & Accumulator
Time variable to update.
double StartTime
Start time, captured in ctor.
Detailed Description
Utility class for tracking the duration of a scoped action (the user doesn't have to call Start() and Stop() manually).
Definition at line 65 of file ScopedTimers.h.
Constructor & Destructor Documentation
FScopedDurationTimer()
FScopedDurationTimer::FScopedDurationTimer (double & AccumulatorIn) inline explicit
Definition at line 68 of file ScopedTimers.h.
References FDurationTimer::FDurationTimer().
Referenced by FAutoScopedDurationTimer::FAutoScopedDurationTimer().
~FScopedDurationTimer()
FScopedDurationTimer::~FScopedDurationTimer () inline
Dtor, updating seconds with time delta.
Definition at line 74 of file ScopedTimers.h.
References FDurationTimer::Stop().
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/ScopedTimers.h