Unreal Engine 5.6 C++ API: TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Class Template Reference
TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Class Template Reference
The base class of maps from keys to values.
#include "Map.h"
Data Structures
class TBaseIterator
The base of TMapBase iterators.
class TBaseKeyIterator
The base type of iterators that iterate over the values associated with a specified key.
class TConstIterator
Const map iterator.
class TConstKeyIterator
Iterates over values associated with a specified key in a const map.
class TIterator
Map iterator.
class TKeyIterator
Iterates over values associated with a specified key in a map.
Public Types
typedef TPair< KeyType, ValueType > ElementType
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
using TRangedForConstIterator = TBaseIterator<true, true>
using TRangedForIterator = TBaseIterator<false, true>
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
Public Member Functions
FORCEINLINE ValueType & Add (const KeyType &InKey)
Set a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (const TTuple< KeyType, ValueType > &InKeyValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (TTuple< KeyType, ValueType > &&InKeyValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, const ValueType &InValue)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, ValueType &&InValue)
TArray< ElementType > Array () const
Copy the key/value pairs in this map into an array.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void Compact ()
Compacts the pair set to remove holes.
FORCEINLINE void CompactStable ()
Compacts the pair set to remove holes.
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Check if map contains the specified key.
template<typename ComparableKey>
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
See Contains() and class documentation section on ByHash() functions.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Track the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
template<typename InitKeyType = KeyType>
ValueType & Emplace (InitKeyType &&InKey)
Set a default value associated with a key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
template<typename InitKeyType = KeyType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey)
See Emplace() and class documentation section on ByHash() functions.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey, InitValueType &&InValue)
See Emplace() and class documentation section on ByHash() functions.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
template<typename Predicate>
TMap< KeyType, ValueType, SetAllocator, KeyFuncs > FilterByPredicate (Predicate Pred) const
Filters the elements in the map based on a predicate functor.
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Find the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
template<typename ComparableKey>
FORCEINLINE ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key)
See Find() and class documentation section on ByHash() functions.
template<typename ComparableKey>
FORCEINLINE const ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key) const
template<typename ComparableKey>
FORCEINLINE ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key)
template<typename ComparableKey>
FORCEINLINE const ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key) const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Find a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
Find a reference to the value associated with a specified key.
FORCEINLINE FSetElementId FindId (KeyInitType Key) const
Finds the index of the first element that is assigned to the specified key.
template<typename ComparableKey>
FORCEINLINE FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
See FindId() and class documentation section on ByHash() functions.
const KeyType * FindKey (ValueInitType Value) const
Find the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, const ValueType &Value)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, const ValueType &Value)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Find the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Find the value associated with a specified key.
template<typename Allocator>
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generate an array from the keys in this map.
template<typename Allocator>
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generate an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container .
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Get the unique keys contained within this map.
template<typename InSetKeyFuncs, typename InSetAllocator>
int32 GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > &OutKeys) const
Get the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
bool OrderIndependentCompareEqual (const TMapBase &Other) const
Compare this map with another for equality.
FORCEINLINE void Remove (FSetElementId Id)
Removes the element at the specified index.
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
template<typename ComparableKey>
FORCEINLINE int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
See Remove() and class documentation section on ByHash() functions.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Public Member Functions
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Protected Types
typedef TSet< ElementType, KeyFuncs, SetAllocator > ElementSetType
using IntrusiveUnsetOptionalStateType = TMapBase
Protected Member Functions
TMapBase ()=default
TMapBase (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMapBase (FIntrusiveUnsetOptionalState Tag)
TMapBase (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TMapBase & operator= (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase & operator= (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMapBase & operator= (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase & operator= (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Protected Attributes
ElementSetType Pairs
A set of the key-value pairs in the map.
Static Protected Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Member Functions
template<typename InitKeyType>
ValueType & FindOrAddImpl (uint32 KeyHash, InitKeyType &&Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
template<typename InitKeyType, typename InitValueType>
ValueType & FindOrAddImpl (uint32 KeyHash, InitKeyType &&Key, InitValueType &&Value)
Find the value associated with a specified key, or if none exists, adds the value.
Static Private Member Functions
static FORCEINLINE uint32 HashKey (const KeyType &Key)
Friends
template<typename OtherKeyType, typename OtherValueType, typename OtherSetAllocator, typename OtherKeyFuncs>
class TMapBase
uint32 GetTypeHash (const TMapBase &Map)=delete
bool operator!= (const TMapBase &, const TMapBase &)=delete
bool operator== (const TMapBase &, const TMapBase &)=delete
struct TMapPrivateFriend
Detailed Description
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
class TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
The base class of maps from keys to values.
Implemented using a TSet of key-value pairs with a custom KeyFuncs, with the same O(1) addition, removal, and finding.
The ByHash() functions are somewhat dangerous but particularly useful in two scenarios: – Heterogeneous lookup to avoid creating expensive keys like FString when looking up by const TCHAR*. You must ensure the hash is calculated in the same way as ElementType is hashed. If possible put both ComparableKey and ElementType hash functions next to each other in the same header to avoid bugs when the ElementType hash function is changed. – Reducing contention around hash tables protected by a lock. It is often important to incur the cache misses of reading key data and doing the hashing before acquiring the lock.
Definition at line 131 of file Map.h.
Member Typedef Documentation
ElementSetType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TSet<ElementType, KeyFuncs, SetAllocator> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ElementSetType protected
Definition at line 845 of file Map.h.
ElementType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TPair<KeyType, ValueType> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ElementType
Definition at line 140 of file Map.h.
IntrusiveUnsetOptionalStateType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> using TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::IntrusiveUnsetOptionalStateType = TMapBase protected
Definition at line 167 of file Map.h.
KeyConstPointerType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TTypeTraits<KeyType>::ConstPointerType TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::KeyConstPointerType
Definition at line 137 of file Map.h.
KeyInitType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TTypeTraits<KeyType>::ConstInitType TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::KeyInitType
Definition at line 138 of file Map.h.
TRangedForConstIterator
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> using TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TRangedForConstIterator = TBaseIterator<true, true>
Definition at line 1050 of file Map.h.
TRangedForIterator
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> using TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TRangedForIterator = TBaseIterator<false, true>
Definition at line 1049 of file Map.h.
ValueInitType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TTypeTraits<ValueType>::ConstInitType TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ValueInitType
Definition at line 139 of file Map.h.
Constructor & Destructor Documentation
TMapBase() [1/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase () nodiscard protected default
TMapBase() [2/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase (TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &&) nodiscard protected default
References TMapBase.
TMapBase() [3/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &) nodiscard protected default
References TMapBase.
TMapBase() [4/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline nodiscard protected
Constructor for moving elements from a TMap with a different SetAllocator.
Definition at line 151 of file Map.h.
References TMapBase, MoveTemp(), Other, and Pairs.
TMapBase() [5/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline nodiscard protected
Constructor for copying elements from a TMap with a different SetAllocator.
Definition at line 158 of file Map.h.
References TMapBase, Other, and Pairs.
TMapBase() [6/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TMapBase (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard protected
Definition at line 169 of file Map.h.
References Pairs.
Member Function Documentation
Add() [1/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (const KeyType & InKey) inline
Set a default value associated with a key.
Parameters
InKey The key to associate the value with.
Returns
A reference to the value as stored in the map. The reference is only valid until the next change to any key in the map.
Definition at line 425 of file Map.h.
References Emplace(), and FORCEINLINE.
Add() [2/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (const KeyType & InKey, const ValueType & InValue) inline
Set the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Returns
A reference to the value as stored in the map. The reference is only valid until the next change to any key in the map.
Definition at line 408 of file Map.h.
References Emplace(), and FORCEINLINE.
Referenced by FAutoRegisterLocalizationDataGatheringCallback::FAutoRegisterLocalizationDataGatheringCallback(), FAutoRegisterLocalizationDataGatheringCallback::FAutoRegisterLocalizationDataGatheringCallback(), FAutoRegisterTextReferenceCollectorCallback::FAutoRegisterTextReferenceCollectorCallback(), FConfigFile::Add(), FConfigFile::Add(), FConfigFile::Add(), FConfigFile::Add(), UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), EditorAnimUtils::DuplicateAssets(), TConstKeyIterator< FFixedObjectBindingID, FName >::EmplaceUnique(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), FilterByPredicate(), FPersistentStorageManager::GenerateCategoryStats(), SMultiColumnTableRow< ItemType >::GenerateColumns(), FBlueprintEditorApplicationModes::GetLocalizedMode(), FRigVMEditorModes::GetLocalizedMode(), FSkelMeshSourceSectionUserData::GetSourceSectionUserData(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes(), TAllocPlaybackLog< FModifier, FAllocOp >::Load(), UE::MediaIO::LogThrottle(), UE::Geometry::FVertexConnectedComponents::MakeComponentMap(), UE::Geometry::FVertexConnectedComponents::MakeComponentMap(), UE::Geometry::FVertexConnectedComponents::MakeContiguousComponentsArray(), FVertexFactoryType::ModifyCompilationEnvironment(), UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::OnObjectsReplaced(), TAllocPlaybackLog< FModifier, FAllocOp >::Play(), STreeView< FRigVMSearchResult >::PopulateLinearizedItems(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), PerPlatformProperty::Private::FNameFuncs< FMemoryImageName >::SerializePerPlatformMap(), PerPlatformProperty::Private::FNameFuncs< FMemoryImageName >::SerializePerPlatformMap(), FGrowableMallocChunk::ShowFullAllocationList(), and USTRUCT().
Add() [3/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (const KeyType & InKey, ValueType && InValue) inline
Definition at line 409 of file Map.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
Add() [4/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (const TTuple< KeyType, ValueType > & InKeyValue) inline
Set the value associated with a key.
Parameters
InKeyValue A Tuple containing the Key and Value to associate together
Returns
A reference to the value as stored in the map. The reference is only valid until the next change to any key in the map.
Definition at line 438 of file Map.h.
References Emplace(), and FORCEINLINE.
Add() [5/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (KeyType && InKey) inline
Definition at line 426 of file Map.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
Add() [6/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (KeyType && InKey, const ValueType & InValue) inline
Definition at line 410 of file Map.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
Add() [7/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (KeyType && InKey, ValueType && InValue) inline
Definition at line 411 of file Map.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
Add() [8/8]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add (TTuple< KeyType, ValueType > && InKeyValue) inline
Definition at line 439 of file Map.h.
References Emplace(), FORCEINLINE, and MoveTempIfPossible().
AddByHash() [1/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash (uint32 KeyHash, const KeyType & InKey) inline
See Add() and class documentation section on ByHash() functions.
Definition at line 429 of file Map.h.
References EmplaceByHash(), and FORCEINLINE.
AddByHash() [2/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash (uint32 KeyHash, const KeyType & InKey, const ValueType & InValue) inline
See Add() and class documentation section on ByHash() functions.
Definition at line 414 of file Map.h.
References EmplaceByHash(), and FORCEINLINE.
Referenced by FindOrAddImpl(), FindOrAddImpl(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduce(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduceAndApply(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApply().
AddByHash() [3/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash (uint32 KeyHash, const KeyType & InKey, ValueType && InValue) inline
Definition at line 415 of file Map.h.
References EmplaceByHash(), FORCEINLINE, and MoveTempIfPossible().
AddByHash() [4/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash (uint32 KeyHash, KeyType && InKey) inline
Definition at line 430 of file Map.h.
References EmplaceByHash(), FORCEINLINE, and MoveTempIfPossible().
AddByHash() [5/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash (uint32 KeyHash, KeyType && InKey, const ValueType & InValue) inline
Definition at line 416 of file Map.h.
References EmplaceByHash(), FORCEINLINE, and MoveTempIfPossible().
AddByHash() [6/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AddByHash (uint32 KeyHash, KeyType && InKey, ValueType && InValue) inline
Definition at line 417 of file Map.h.
References EmplaceByHash(), FORCEINLINE, and MoveTempIfPossible().
AppendHash()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AppendHash (const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher) inline static
Definition at line 995 of file Map.h.
References TSet< ElementType, KeyFuncs, SetAllocator >::AppendHash().
Referenced by Freeze::IntrinsicAppendHash().
Array()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TArray< ElementType > TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Array () const inline nodiscard
Copy the key/value pairs in this map into an array.
Definition at line 801 of file Map.h.
References Pairs.
begin() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TRangedForIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::begin () inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 1121 of file Map.h.
References FORCEINLINE, and Pairs.
begin() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TRangedForConstIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::begin () const inline nodiscard
Definition at line 1122 of file Map.h.
References FORCEINLINE, and Pairs.
Compact()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Compact () inline
Compacts the pair set to remove holes.
Definition at line 259 of file Map.h.
References FORCEINLINE, and Pairs.
CompactStable()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CompactStable () inline
Compacts the pair set to remove holes.
Does not change the iteration order of the elements.
Definition at line 265 of file Map.h.
References FORCEINLINE, and Pairs.
Contains()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Contains (KeyConstPointerType Key) const inline nodiscard
Check if map contains the specified key.
Parameters
Key The key to check for.
Returns
true if the map contains the key.
Definition at line 788 of file Map.h.
References FORCEINLINE, Key, and Pairs.
Referenced by FConfigFile::Contains(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), UE::Geometry::FVertexConnectedComponents::MakeComponentMap(), UE::Geometry::FVertexConnectedComponents::MakeComponentMap(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), and FGrowableMallocChunk::ShowFullAllocationList().
ContainsByHash()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ContainsByHash (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard
See Contains() and class documentation section on ByHash() functions.
Definition at line 795 of file Map.h.
References FORCEINLINE, Key, and Pairs.
CopyUnfrozen()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CopyUnfrozen (const FMemoryUnfreezeContent & Context, void * Dst) const inline
Definition at line 990 of file Map.h.
References Pairs.
CountBytes()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CountBytes (FArchive & Ar) const inline
Track the container's memory use through an archive.
Parameters
Ar The archive to use.
See also
GetAllocatedSize
Definition at line 396 of file Map.h.
References Ar, FORCEINLINE, and Pairs.
Referenced by USTRUCT().
CreateConstIterator()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TConstIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateConstIterator () const inline nodiscard
Creates a const iterator over all the pairs in this map.
Definition at line 1097 of file Map.h.
References FORCEINLINE.
Referenced by TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstIterator::TConstIterator(), and UE::Geometry::FVertexConnectedComponents::ConnectOverlappingComponents().
CreateConstKeyIterator()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TConstKeyIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const inline nodiscard
Creates a const iterator over the values associated with a specified key in a map.
Definition at line 1109 of file Map.h.
References FORCEINLINE.
CreateIterator()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateIterator () inline nodiscard
Creates an iterator over all the pairs in this map.
Definition at line 1091 of file Map.h.
References FORCEINLINE.
Referenced by TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TIterator::TIterator(), EditorAnimUtils::DuplicateAssets(), and FGrowableMallocChunk::ShowFullAllocationList().
CreateKeyIterator()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TKeyIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey) inline nodiscard
Creates an iterator over the values associated with a specified key in a map.
Definition at line 1103 of file Map.h.
References FORCEINLINE.
Dump()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Dump (FOutputDevice & Ar) inline
Describes the map's contents through an output device.
Parameters
Ar The output device to describe the map's contents through.
Definition at line 839 of file Map.h.
References Ar, and Pairs.
Emplace() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType = KeyType> ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace (InitKeyType && InKey) inline
Set a default value associated with a key.
Parameters
InKey The key to associate the value with.
Returns
A reference to the value as stored in the map. The reference is only valid until the next change to any key in the map.
Definition at line 471 of file Map.h.
References Forward(), and Pairs.
Emplace() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType = KeyType, typename InitValueType = ValueType> ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Emplace (InitKeyType && InKey, InitValueType && InValue) inline
Sets the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Returns
A reference to the value as stored in the map. The reference is only valid until the next change to any key in the map.
Definition at line 448 of file Map.h.
References Forward(), and Pairs.
Referenced by Add(), Add(), Add(), Add(), Add(), Add(), Add(), Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Add(), and DisplayClusterHelpers::str::StrToMap().
EmplaceByHash() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType = KeyType> ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::EmplaceByHash (uint32 KeyHash, InitKeyType && InKey) inline
See Emplace() and class documentation section on ByHash() functions.
Definition at line 480 of file Map.h.
References Forward(), and Pairs.
EmplaceByHash() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType = KeyType, typename InitValueType = ValueType> ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::EmplaceByHash (uint32 KeyHash, InitKeyType && InKey, InitValueType && InValue) inline
See Emplace() and class documentation section on ByHash() functions.
Definition at line 457 of file Map.h.
References Forward(), and Pairs.
Referenced by AddByHash(), AddByHash(), AddByHash(), AddByHash(), AddByHash(), and AddByHash().
Empty()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Empty (int32 ExpectedNumElements = 0) inline
Removes all elements from the map.
This method potentially leaves space allocated for an expected number of elements about to be added.
Parameters
ExpectedNumElements The number of elements about to be added to the set.
Definition at line 241 of file Map.h.
References FORCEINLINE, and Pairs.
Referenced by FConfigFile::Empty().
end() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TRangedForIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::end () inline nodiscard
Definition at line 1123 of file Map.h.
References FORCEINLINE, and Pairs.
end() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE TRangedForConstIterator TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::end () const inline nodiscard
Definition at line 1124 of file Map.h.
References FORCEINLINE, and Pairs.
FilterByPredicate()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Predicate> TMap< KeyType, ValueType, SetAllocator, KeyFuncs > TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FilterByPredicate (Predicate Pred) const inline nodiscard
Filters the elements in the map based on a predicate functor.
Parameters
Pred The functor to apply to each element.
Returns
TMap with the same type as this object which contains the subset of elements for which the functor returns true.
Definition at line 546 of file Map.h.
References Add(), Pairs, Predicate, and Reserve().
Find() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find (KeyConstPointerType Key) inline nodiscard
Find the value associated with a specified key.
Parameters
Key The key to search for.
Returns
A pointer to the value associated with the specified key, or nullptr if the key isn't contained in this map. The pointer is only valid until the next change to any key in the map.
Definition at line 567 of file Map.h.
References FORCEINLINE, Key, and Pairs.
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill(), UE::Graph::ConvertToGraph(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom(), FGenericMemoryStats::FGenericMemoryStatsMap::Find(), FMovieSceneClipboardKey::TKey< T >::FindConversionTo(), FConfigFile::FindInternal(), FConfigFile::FindSection(), FBlueprintEditorApplicationModes::GetLocalizedMode(), FRigVMEditorModes::GetLocalizedMode(), FSkelMeshSourceSectionUserData::GetSourceSectionUserData(), FShaderPipelineCache::GetTask(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), TAllocPlaybackLog< FModifier, FAllocOp >::Load(), UE::MediaIO::LogThrottle(), UE::Geometry::FVertexConnectedComponents::MakeContiguousComponentsArray(), TAllocPlaybackLog< FModifier, FAllocOp >::Play(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), UE::MovieScene::Private::ReplaceGroupKeyObjectElement(), FConfigFile::UE_DEPRECATED(), FConfigFile::UE_DEPRECATED(), USTRUCT(), and USTRUCT().
Find() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE const ValueType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find (KeyConstPointerType Key) const inline nodiscard
Definition at line 576 of file Map.h.
References TMapBase, Find, FORCEINLINE, and Key.
FindArbitraryElement() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> ElementType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindArbitraryElement () inline nodiscard
Finds any pair in the map and returns a pointer to it.
Callers should not depend on particular patterns in the behaviour of this function.
Returns
A pointer to an arbitrary pair, or nullptr if the container is empty.
Definition at line 771 of file Map.h.
References Pairs.
Referenced by FindArbitraryElement().
FindArbitraryElement() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> const ElementType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindArbitraryElement () const inline nodiscard
Definition at line 777 of file Map.h.
References TMapBase, and FindArbitraryElement().
FindByHash() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE ValueType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindByHash (uint32 KeyHash, const ComparableKey & Key) inline nodiscard
See Find() and class documentation section on ByHash() functions.
Definition at line 583 of file Map.h.
References FORCEINLINE, Key, and Pairs.
Referenced by FindByHash(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduce(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrProduceAndApply(), and TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::FindOrTryProduceAndApply().
FindByHash() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE const ValueType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindByHash (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard
Definition at line 593 of file Map.h.
References TMapBase, FindByHash(), FORCEINLINE, and Key.
FindByHashChecked() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindByHashChecked (uint32 KeyHash, const ComparableKey & Key) inline nodiscard
Definition at line 599 of file Map.h.
References check, FORCEINLINE, Key, and Pairs.
Referenced by FindByHashChecked().
FindByHashChecked() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE const ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindByHashChecked (uint32 KeyHash, const ComparableKey & Key) const inline nodiscard
Definition at line 606 of file Map.h.
References TMapBase, FindByHashChecked(), FORCEINLINE, and Key.
FindChecked() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindChecked (KeyConstPointerType Key) inline nodiscard
Find a reference to the value associated with a specified key.
Parameters
Key The key to search for.
Returns
The value associated with the specified key, or triggers an assertion if the key does not exist.
Definition at line 726 of file Map.h.
References check, FORCEINLINE, Key, and Pairs.
FindChecked() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE const ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindChecked (KeyConstPointerType Key) const inline nodiscard
Find a reference to the value associated with a specified key.
Parameters
Key The key to search for.
Returns
The value associated with the specified key, or triggers an assertion if the key does not exist.
Definition at line 713 of file Map.h.
References check, FORCEINLINE, Key, and Pairs.
Referenced by UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator[](), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator[](), and FGrowableMallocChunk::ShowFullAllocationList().
FindId()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE FSetElementId TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindId (KeyInitType Key) const inline
Finds the index of the first element that is assigned to the specified key.
The returned index is only valid until the map is changed.
Parameters
Key The key to search for.
Definition at line 617 of file Map.h.
References FORCEINLINE, Key, and Pairs.
FindIdByHash()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE FSetElementId TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindIdByHash (uint32 KeyHash, const ComparableKey & Key) const inline
See FindId() and class documentation section on ByHash() functions.
Definition at line 624 of file Map.h.
References FORCEINLINE, Key, and Pairs.
FindKey()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> const KeyType * TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindKey (ValueInitType Value) const inline nodiscard
Find the key associated with the specified value.
The time taken is O(N) in the number of pairs.
Parameters
Value The value to search for
Returns
A pointer to the key associated with the specified value, or nullptr if the value isn't contained in this map. The pointer is only valid until the next change to any key in the map.
Definition at line 526 of file Map.h.
References Pairs, and Value.
FindOrAdd() [1/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd (const KeyType & Key) inline
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
Parameters
Key The key to search for.
Returns
A reference to the value associated with the specified key.
Definition at line 681 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, HashKey(), and Key.
Referenced by UE::Geometry::FVertexConnectedComponents::ConnectOverlappingComponents(), UE::Graph::ConvertToGraph(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), and FConfigFile::UE_DEPRECATED().
FindOrAdd() [2/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd (const KeyType & Key, const ValueType & Value) inline
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
Parameters
Key The key to search for.
Value The value to associate with the key.
Returns
A reference to the value associated with the specified key.
Definition at line 696 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, HashKey(), Key, and Value.
FindOrAdd() [3/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd (const KeyType & Key, ValueType && Value) inline
Definition at line 697 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, HashKey(), Key, MoveTempIfPossible(), and Value.
FindOrAdd() [4/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd (KeyType && Key) inline
Definition at line 682 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, HashKey(), Key, and MoveTempIfPossible().
FindOrAdd() [5/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd (KeyType && Key, const ValueType & Value) inline
Definition at line 698 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, HashKey(), Key, MoveTempIfPossible(), and Value.
FindOrAdd() [6/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd (KeyType && Key, ValueType && Value) inline
Definition at line 699 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, HashKey(), Key, MoveTempIfPossible(), and Value.
FindOrAddByHash() [1/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash (uint32 KeyHash, const KeyType & Key) inline
See FindOrAdd() and class documentation section on ByHash() functions.
Definition at line 685 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, and Key.
FindOrAddByHash() [2/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash (uint32 KeyHash, const KeyType & Key, const ValueType & Value) inline
See FindOrAdd() and class documentation section on ByHash() functions.
Definition at line 702 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, Key, and Value.
FindOrAddByHash() [3/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash (uint32 KeyHash, const KeyType & Key, ValueType && Value) inline
Definition at line 703 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, Key, MoveTempIfPossible(), and Value.
FindOrAddByHash() [4/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash (uint32 KeyHash, KeyType && Key) inline
Definition at line 686 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, Key, and MoveTempIfPossible().
FindOrAddByHash() [5/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash (uint32 KeyHash, KeyType && Key, const ValueType & Value) inline
Definition at line 704 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, Key, MoveTempIfPossible(), and Value.
FindOrAddByHash() [6/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddByHash (uint32 KeyHash, KeyType && Key, ValueType && Value) inline
Definition at line 705 of file Map.h.
References FindOrAddImpl(), FORCEINLINE, Key, MoveTempIfPossible(), and Value.
FindOrAddImpl() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType> ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddImpl (uint32 KeyHash, InitKeyType && Key) inline nodiscard private
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
Parameters
Key The key to search for.
Returns
A reference to the value associated with the specified key.
Definition at line 643 of file Map.h.
References AddByHash(), Forward(), Key, and Pairs.
Referenced by FindOrAdd(), FindOrAdd(), FindOrAdd(), FindOrAdd(), FindOrAdd(), FindOrAdd(), FindOrAddByHash(), FindOrAddByHash(), FindOrAddByHash(), FindOrAddByHash(), FindOrAddByHash(), and FindOrAddByHash().
FindOrAddImpl() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InitKeyType, typename InitValueType> ValueType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAddImpl (uint32 KeyHash, InitKeyType && Key, InitValueType && Value) inline nodiscard private
Find the value associated with a specified key, or if none exists, adds the value.
Parameters
Key The key to search for.
Value The value to associate with the key.
Returns
A reference to the value associated with the specified key.
Definition at line 662 of file Map.h.
References AddByHash(), Forward(), Key, Pairs, and Value.
FindRef() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindRef (KeyConstPointerType Key) const inline nodiscard
Find the value associated with a specified key.
Parameters
Key The key to search for.
Returns
The value associated with the specified key, or the default value for the ValueType if the key isn't contained in this map.
Definition at line 739 of file Map.h.
References FORCEINLINE, Key, and Pairs.
Referenced by FGenericMemoryStats::FGenericMemoryStatsMap::FindRef(), and FBuoyancyComponentSim::GetWaterHeight().
FindRef() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ValueType TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindRef (KeyConstPointerType Key, ValueType DefaultValue) const inline nodiscard
Find the value associated with a specified key.
Parameters
Key The key to search for.
DefaultValue The fallback value if the key is not found.
Returns
The value associated with the specified key, or DefaultValue if the key isn't contained in this map.
Definition at line 756 of file Map.h.
References FORCEINLINE, Key, and Pairs.
GenerateKeyArray()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Allocator> void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateKeyArray (TArray< KeyType, Allocator > & OutArray) const inline
Generate an array from the keys in this map.
Parameters
OutArray Will contain the collection of keys.
Definition at line 811 of file Map.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Empty(), and Pairs.
Referenced by TFindObjectReferencers< T >::TFindObjectReferencers().
GenerateValueArray()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Allocator> void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GenerateValueArray (TArray< ValueType, Allocator > & OutArray) const inline
Generate an array from the values in this map.
Parameters
OutArray Will contain the collection of values.
Definition at line 825 of file Map.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Empty(), and Pairs.
Get() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE ElementType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Get (FSetElementId Id) inline nodiscard
Return a mapped pair by internal identifier.
Element must be valid (see @IsValidId).
Definition at line 310 of file Map.h.
References FORCEINLINE, and Pairs.
Get() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE const ElementType & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Get (FSetElementId Id) const inline nodiscard
Return a mapped pair by internal identifier.
Element must be valid (see @IsValidId).
Definition at line 316 of file Map.h.
References FORCEINLINE, and Pairs.
GetAllocatedSize()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE SIZE_T TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetAllocatedSize () const inline nodiscard
Helper function to return the amount of memory allocated by this container .
Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
Number of bytes allocated by this container.
See also
CountBytes
Definition at line 385 of file Map.h.
References FORCEINLINE, and Pairs.
GetKeys() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename Allocator> int32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys (TArray< KeyType, Allocator > & OutKeys) const inline
Get the unique keys contained within this map.
Parameters
OutKeys Upon return, contains the set of unique keys in this map.
Returns
The number of unique keys in the map.
Definition at line 327 of file Map.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Contains(), TArray< InElementType, InAllocatorType >::Num(), Num(), Pairs, TArray< InElementType, InAllocatorType >::Reserve(), TSet< InElementType, KeyFuncs, Allocator >::Reserve(), and TArray< InElementType, InAllocatorType >::Reset().
Referenced by FConfigFile::GetKeys(), and FConfigFile::GetKeys().
GetKeys() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename InSetKeyFuncs, typename InSetAllocator> int32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > & OutKeys) const inline
Get the unique keys contained within this map.
Parameters
OutKeys Upon return, contains the set of unique keys in this map.
Returns
The number of unique keys in the map.
Definition at line 360 of file Map.h.
References TSet< InElementType, KeyFuncs, Allocator >::Add(), Num(), TSet< InElementType, KeyFuncs, Allocator >::Num(), Pairs, TSet< InElementType, KeyFuncs, Allocator >::Reserve(), and TSet< InElementType, KeyFuncs, Allocator >::Reset().
GetMaxIndex()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE int32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::GetMaxIndex () const inline nodiscard
Returns
The max valid index of the elements in the sparse storage.
Definition at line 294 of file Map.h.
References FORCEINLINE, and Pairs.
HashKey()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE uint32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::HashKey (const KeyType & Key) inline static nodiscard private
Definition at line 630 of file Map.h.
References FORCEINLINE, and Key.
Referenced by FindOrAdd(), FindOrAdd(), FindOrAdd(), FindOrAdd(), FindOrAdd(), and FindOrAdd().
IsEmpty()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::IsEmpty () const inline nodiscard
Returns true if the map is empty and contains no elements.
Returns
True if the map is empty.
See also
Num
Definition at line 282 of file Map.h.
References Pairs.
Referenced by FConfigFile::IsEmpty(), and USTRUCT().
IsValidId()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::IsValidId (FSetElementId Id) const inline nodiscard
Checks whether an element id is valid.
Parameters
Id - The element id to check.
Returns
true if the element identifier refers to a valid element in this map.
Definition at line 304 of file Map.h.
References FORCEINLINE, and Pairs.
Num()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE int32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num () const inline nodiscard
Returns
The number of elements in the map.
Definition at line 288 of file Map.h.
References FORCEINLINE, and Pairs.
Referenced by TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::Append(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append(), FStaticLightingTextureMapping_InstancedStaticMesh::Apply(), UE::Anim::FCurveUtils::BuildUnsorted(), FActorDescList::GetActorDescCount(), GetKeys(), GetKeys(), FBlueprintEditorApplicationModes::GetLocalizedMode(), FRigVMEditorModes::GetLocalizedMode(), TActorDescList< DescType >::IsEmpty(), FConfigFile::Num(), FUObjectAnnotationSparseBool::Num(), TConstKeyIterator< FFixedObjectBindingID, FName >::Num(), and OrderIndependentCompareEqual().
operator=() [1/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMapBase & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &) protected default
References TMapBase.
operator=() [2/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMapBase & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline protected
Assignment operator for copying elements from a TMap with a different SetAllocator.
Definition at line 191 of file Map.h.
References TMapBase, Other, and Pairs.
operator=() [3/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TMapBase & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &&) protected default
References TMapBase.
operator=() [4/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TMapBase & TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline protected
Assignment operator for moving elements from a TMap with a different SetAllocator.
Definition at line 183 of file Map.h.
References TMapBase, MoveTemp(), Other, and Pairs.
operator==()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard protected
Definition at line 173 of file Map.h.
References Pairs.
Referenced by TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator==().
OrderIndependentCompareEqual()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::OrderIndependentCompareEqual (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & Other) const inline nodiscard
Compare this map with another for equality.
Does not make any assumptions about Key order. NOTE: this might be a candidate for operator== but it was decided to make it an explicit function since it can potentially be quite slow.
Parameters
Other The other map to compare against
Returns
True if both this and Other contain the same keys with values that compare ==
Definition at line 207 of file Map.h.
References TMapBase, Num(), Other, and Pairs.
Remove() [1/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Remove (FSetElementId Id) inline
Removes the element at the specified index.
The caller has to ensure that the index is valid.
Parameters
Id The index of the element to remove.
Definition at line 511 of file Map.h.
References FORCEINLINE, and Pairs.
Remove() [2/2]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE int32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Remove (KeyConstPointerType InKey) inline
Remove all value associations for a key.
Parameters
InKey The key to remove associated values for.
Returns
The number of values that were associated with the key.
Definition at line 493 of file Map.h.
References FORCEINLINE, and Pairs.
Referenced by TAllocPlaybackLog< FModifier, FAllocOp >::Play(), FConfigFile::Remove(), and TConstKeyIterator< FFixedObjectBindingID, FName >::Remove().
RemoveByHash()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename ComparableKey> FORCEINLINE int32 TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::RemoveByHash (uint32 KeyHash, const ComparableKey & Key) inline
See Remove() and class documentation section on ByHash() functions.
Definition at line 501 of file Map.h.
References FORCEINLINE, Key, and Pairs.
Reserve()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve (int32 Number) inline
Preallocates enough memory to contain Number elements.
Definition at line 271 of file Map.h.
References FORCEINLINE, and Pairs.
Referenced by UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::TThreadSafeMap(), TConstKeyIterator< FFixedObjectBindingID, FName >::Append(), TConstKeyIterator< FFixedObjectBindingID, FName >::Append(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Append(), UE::Graph::ConvertToGraph(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), FilterByPredicate(), FPersistentStorageManager::GenerateCategoryStats(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::ReindexBoneIndicesToSkeleton(), and TConstKeyIterator< FFixedObjectBindingID, FName >::TMultiMap().
Reset()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reset () inline
Efficiently empties out the map but preserves all allocations and capacities.
Definition at line 247 of file Map.h.
References FORCEINLINE, and Pairs.
Referenced by TFindObjectReferencers< T >::TFindObjectReferencers(), and FConfigFile::Reset().
Shrink()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> FORCEINLINE void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Shrink () inline
Shrinks the pair set to avoid slack.
Definition at line 253 of file Map.h.
References FORCEINLINE, and Pairs.
WriteMemoryImage()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::WriteMemoryImage (FMemoryImageWriter & Writer) const inline
Definition at line 985 of file Map.h.
References Pairs.
Friends And Related Symbol Documentation
TMapBase
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherKeyType, typename OtherValueType, typename OtherSetAllocator, typename OtherKeyFuncs> friend class TMapBase friend
Definition at line 134 of file Map.h.
References TMapBase.
Referenced by TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstIterator::TConstIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstKeyIterator::TConstKeyIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TIterator::TIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TKeyIterator::TKeyIterator(), TMapBase, TMapBase(), TMapBase(), TMapBase(), TMapBase(), Find(), FindArbitraryElement(), FindByHash(), FindByHashChecked(), GetTypeHash, operator!=, operator=(), operator=(), operator=(), operator=(), operator==, and OrderIndependentCompareEqual().
GetTypeHash
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> uint32 GetTypeHash (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & Map) friend
References TMapBase, and Map.
operator!=
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool operator!= (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & , const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &) friend
References TMapBase.
operator==
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool operator== (const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > & , const TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &) friend
References TMapBase.
TMapPrivateFriend
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> friend struct TMapPrivateFriend friend
Definition at line 1114 of file Map.h.
References TMapPrivateFriend.
Referenced by TMapPrivateFriend.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::bHasIntrusiveUnsetOptionalState = true static constexpr protected
Definition at line 166 of file Map.h.
Pairs
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> ElementSetType TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs protected
A set of the key-value pairs in the map.
Definition at line 982 of file Map.h.
Referenced by TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstIterator::TConstIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TConstKeyIterator::TConstKeyIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TIterator::TIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TKeyIterator::TKeyIterator(), TMapBase(), TMapBase(), TMapBase(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Apply(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::ApplyUntil(), Array(), FConfigFile::begin(), begin(), begin(), Compact(), CompactStable(), Contains(), ContainsByHash(), CopyUnfrozen(), CountBytes(), Dump(), Emplace(), Emplace(), EmplaceByHash(), EmplaceByHash(), Empty(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::Empty(), FConfigFile::end(), end(), end(), FilterByPredicate(), Find(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::FindAndRemoveChecked(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::FindAndRemoveChecked(), FindArbitraryElement(), FindByHash(), FindByHashChecked(), FindChecked(), FindChecked(), FindId(), FindIdByHash(), FindKey(), FindOrAddImpl(), FindOrAddImpl(), FindRef(), FindRef(), GenerateKeyArray(), GenerateValueArray(), Get(), Get(), GetAllocatedSize(), GetKeys(), GetKeys(), GetMaxIndex(), IsEmpty(), IsValidId(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::KeySort(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::KeyStableSort(), FConfigSection::MultiFind(), Num(), operator=(), operator=(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), operator==(), OrderIndependentCompareEqual(), Remove(), Remove(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::RemoveAndCopyValue(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValue(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::RemoveAndCopyValueByHash(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValueByHash(), RemoveByHash(), Reserve(), Reset(), TMapPrivateFriend::SerializeStructured(), Shrink(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::SortFreeList(), FConfigFile::UE_DEPRECATED(), FConfigFile::UE_DEPRECATED(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ValueSort(), TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ValueStableSort(), and WriteMemoryImage().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Map.h