Unreal Engine 5.6 C++ API: UE::Net::Private::FRefCountedNetGUIDArray Class Reference
UE::Net::Private::FRefCountedNetGUIDArray Class Reference
Simple class to manage a reference-counted array of FNetworkGUIDs.
#include "PackageMapClient.h"
Public Member Functions
FRefCountedNetGUIDArray ()
FRefCountedNetGUIDArray (const FRefCountedNetGUIDArray &)=delete
FRefCountedNetGUIDArray (FRefCountedNetGUIDArray &&Other)=default
~FRefCountedNetGUIDArray ()=default
void Add (FNetworkGUID NetGUID)
const TArray< FNetworkGUID > & GetNetGUIDs () const
FRefCountedNetGUIDArray & operator= (const FRefCountedNetGUIDArray &)=delete
FRefCountedNetGUIDArray & operator= (FRefCountedNetGUIDArray &&Other)=default
void RemoveSwap (FNetworkGUID NetGUID)
Private Attributes
TArray< FNetworkGUID > NetGUIDs
TArray< int32 > RefCounts
Detailed Description
Simple class to manage a reference-counted array of FNetworkGUIDs.
Definition at line 172 of file PackageMapClient.h.
Constructor & Destructor Documentation
FRefCountedNetGUIDArray() [1/3]
UE::Net::Private::FRefCountedNetGUIDArray::FRefCountedNetGUIDArray () inline
Definition at line 175 of file PackageMapClient.h.
Referenced by FRefCountedNetGUIDArray(), FRefCountedNetGUIDArray(), operator=(), and operator=().
FRefCountedNetGUIDArray() [2/3]
UE::Net::Private::FRefCountedNetGUIDArray::FRefCountedNetGUIDArray (const FRefCountedNetGUIDArray &) delete
References FRefCountedNetGUIDArray().
FRefCountedNetGUIDArray() [3/3]
UE::Net::Private::FRefCountedNetGUIDArray::FRefCountedNetGUIDArray (FRefCountedNetGUIDArray && Other) default
References FRefCountedNetGUIDArray(), and Other.
~FRefCountedNetGUIDArray()
UE::Net::Private::FRefCountedNetGUIDArray::~FRefCountedNetGUIDArray () default
Member Function Documentation
Add()
void UE::Net::Private::FRefCountedNetGUIDArray::Add (FNetworkGUID NetGUID)
GetNetGUIDs()
const TArray< FNetworkGUID > & UE::Net::Private::FRefCountedNetGUIDArray::GetNetGUIDs () const inline
Definition at line 186 of file PackageMapClient.h.
References NetGUIDs.
operator=() [1/2]
FRefCountedNetGUIDArray & UE::Net::Private::FRefCountedNetGUIDArray::operator= (const FRefCountedNetGUIDArray &) delete
References FRefCountedNetGUIDArray().
operator=() [2/2]
FRefCountedNetGUIDArray & UE::Net::Private::FRefCountedNetGUIDArray::operator= (FRefCountedNetGUIDArray && Other) default
References FRefCountedNetGUIDArray(), and Other.
RemoveSwap()
void UE::Net::Private::FRefCountedNetGUIDArray::RemoveSwap (FNetworkGUID NetGUID)
Field Documentation
NetGUIDs
TArray<FNetworkGUID> UE::Net::Private::FRefCountedNetGUIDArray::NetGUIDs private
Definition at line 189 of file PackageMapClient.h.
Referenced by GetNetGUIDs().
RefCounts
TArray<int32> UE::Net::Private::FRefCountedNetGUIDArray::RefCounts private
Definition at line 190 of file PackageMapClient.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/PackageMapClient.h