Unreal Engine 5.6 C++ API: IDisplayClusterViewport Class Reference
IDisplayClusterViewport Class Reference abstract
nDisplay: Viewport (interface for GameThread)
#include "IDisplayClusterViewport.h"
Public Member Functions
virtual ~IDisplayClusterViewport ()=default
virtual void CalculateProjectionMatrix (const uint32 InContextNum, float Left, float Right, float Top, float Bottom, float ZNear, float ZFar, bool bIsAnglesInput)=0
Calculate projection matrices for viewport context (also created overscan matrices, etc)
virtual bool CalculateView (const uint32 InContextNum, FVector &InOutViewLocation, FRotator &InOutViewRotation, const float WorldToMeters)=0
Calculate viewport projection.
virtual FVector2D GetClippingPlanes () const =0
Get clipping planes used by this viewport.
virtual FString GetClusterNodeId () const =0
virtual const IDisplayClusterViewportConfiguration & GetConfiguration () const =0
[const] Get viewport manager configuration interface.
virtual IDisplayClusterViewportConfiguration & GetConfiguration ()=0
Get viewport manager configuration interface.
virtual const TSharedRef< const IDisplayClusterViewportConfiguration, ESPMode::ThreadSafe > GetConfigurationRef () const =0
[const] Get viewport manager configuration interface reference.
virtual const TSharedRef< IDisplayClusterViewportConfiguration, ESPMode::ThreadSafe > GetConfigurationRef ()=0
Get viewport manager configuration interface reference.
virtual const TArray< FDisplayClusterViewport_Context > & GetContexts () const =0
Get viewport contexts.
virtual class UDisplayClusterDisplayDeviceBaseComponent * GetDisplayDeviceComponent (const EDisplayClusterRootActorType InRootActorType) const =0
Return a DisplayDevice component for this viewport.
virtual FString GetId () const =0
virtual bool GetOCIOConversionSettings (FOpenColorIOColorConversionSettings &OutOCIOConversionSettings) const =0
Returns OCIO configuration if any set.
virtual const FDisplayClusterViewport_PostRenderSettings & GetPostRenderSettings () const =0
Get post-render settings.
virtual bool GetProjectionMatrix (const uint32 InContextNum, FMatrix &OutPrjMatrix)=0
Get projection matrix for viewport context.
virtual const TSharedPtr< class IDisplayClusterProjectionPolicy, ESPMode::ThreadSafe > & GetProjectionPolicy () const =0
Get projection policy ref.
virtual const FDisplayClusterViewport_RenderSettings & GetRenderSettings () const =0
Get main viewport render settings.
virtual const FDisplayClusterViewport_RenderSettingsICVFX & GetRenderSettingsICVFX () const =0
Get ICVFX render settings.
virtual float GetStereoEyeOffsetDistance (const uint32 InContextNum)=0
Get the distance from the eye to the viewpoint location.
virtual class UDisplayClusterCameraComponent * GetViewPointCameraComponent (const EDisplayClusterRootActorType InRootActorType) const =0
Return view point camera component for this viewport.
virtual bool GetViewPointCameraEye (const uint32 InContextNum, FVector &OutViewLocation, FRotator &OutViewRotation, FVector &OutViewOffset)=0
Retrieves the view position from the ViewPoint component used by this viewport.
virtual const IDisplayClusterViewport_CustomPostProcessSettings & GetViewport_CustomPostProcessSettings () const =0
[const] Get custom postprocess settings for this viewport.
virtual IDisplayClusterViewport_CustomPostProcessSettings & GetViewport_CustomPostProcessSettings ()=0
Get custom postprocess settings for this viewport.
virtual IDisplayClusterViewportPreview & GetViewportPreview () const =0
Get viewport preview API.
virtual void SetContexts (TArray< FDisplayClusterViewport_Context > &InContexts)=0
Change viewport contexts data.
virtual void SetRenderSettings (const FDisplayClusterViewport_RenderSettings &InRenderSettings)=0
Change render setting for viewport.
virtual void SetupSceneView (uint32 ContextNum, class UWorld *World, class FSceneViewFamily &InViewFamily, FSceneView &InView) const =0
Setup scene view for rendering specified Context.
virtual bool SetupViewPoint (const uint32 InContextNum, struct FMinimalViewInfo &InOutViewInfo)=0
Setup viewpoint for this viewport.
virtual TSharedPtr< const IDisplayClusterViewport, ESPMode::ThreadSafe > ToSharedPtr () const =0
virtual TSharedPtr< IDisplayClusterViewport, ESPMode::ThreadSafe > ToSharedPtr ()=0
Get TSharedPtr from self.
virtual TSharedRef< const class FDisplayClusterViewport, ESPMode::ThreadSafe > ToSharedRef () const =0
virtual TSharedRef< class FDisplayClusterViewport, ESPMode::ThreadSafe > ToSharedRef ()=0
Internal functions.
UE_DEPRECATED (5.3, "This function has been deprecated. Please use 'CalculateView()'.") virtual bool CalculateView(const uint32 InContextNum
Calculate viewport projection (This function has been deprecated.)
UE_DEPRECATED (5.3, "This function has beend deprecate. Please use 'GetViewportManager()'.") virtual class IDisplayClusterViewportManager &GetOwner() const
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetConfiguration()'.") virtual bool IsCurrentWorldHasAnyType(const EWorldType
Returns true if the current world type is equal to one of the input types.
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetConfiguration()'.") virtual bool IsSceneOpened() const
Returns true if the scene is open now (The current world is assigned and DCRA has already initialized for it).
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetConfiguration()'.") virtual class ADisplayClusterRootActor *GetRootActor() const
Gets a reference to the DCRA with actual configuration inside.
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetConfiguration()'.") virtual class IDisplayClusterViewportManager *GetViewportManager() const
Return the viewport manager that owns this viewport.
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetConfiguration()'.") virtual class UWorld *GetCurrentWorld() const
Return current world.
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetConfiguration()'.") virtual EDisplayClusterRenderFrameMode GetRenderMode() const
Return current render mode.
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'GetViewPointCameraComponent(EDisplayClusterRootActorType)'.") virtual class UDisplayClusterCameraComponent *GetViewPointCameraComponent() const
Return view point camera component for this viewport.
virtual bool UseSameOCIO (const IDisplayClusterViewport *InViewport) const =0
Returns true if both viewports use the same OCIO.
Static Public Member Functions
static bool GetCameraComponentView (UCameraComponent *InCameraComponent, const float InDeltaTime, const bool bUseCameraPostprocess, FMinimalViewInfo &InOutViewInfo, float *OutCustomNearClippingPlane=nullptr)
Get View from CameraComponent.
static bool GetPlayerCameraView (UWorld *InWorld, const bool bUseCameraPostprocess, FMinimalViewInfo &InOutViewInfo)
Get View from current player camera.
static FMatrix MakeProjectionMatrix (float InLeft, float InRight, float InTop, float InBottom, float ZNear, float ZFar)
Make asymmetrical projection matrix for nDisplay.
Data Fields
FVector FRotator const FVector const float const float const float FCP
FVector & InOutViewLocation
FVector FRotator & InOutViewRotation
FVector FRotator const FVector const float const float NCP
FVector FRotator const FVector & ViewOffset
FVector FRotator const FVector const float WorldToMeters
Detailed Description
nDisplay: Viewport (interface for GameThread)
Definition at line 28 of file IDisplayClusterViewport.h.
Constructor & Destructor Documentation
~IDisplayClusterViewport()
virtual IDisplayClusterViewport::~IDisplayClusterViewport () virtual default
Member Function Documentation
CalculateProjectionMatrix()
virtual void IDisplayClusterViewport::CalculateProjectionMatrix (const uint32 InContextNum, float Left, float Right, float Top, float Bottom, float ZNear, float ZFar, bool bIsAnglesInput) pure virtual
Calculate projection matrices for viewport context (also created overscan matrices, etc)
Parameters
InContextNum - viewport eye context index
Left - frustum left angle
Right - frustum right angle
Top - frustum top angle
Bottom - frustum bottom angle
NCP - Near clipping plane
FCP - Far clipping plane
bIsAnglesInput - true, if projection angles in degrees
References Bottom, Left, Right, and Top.
CalculateView()
virtual bool IDisplayClusterViewport::CalculateView (const uint32 InContextNum, FVector & InOutViewLocation, FRotator & InOutViewRotation, const float WorldToMeters) pure virtual
Calculate viewport projection.
Parameters
InContextNum - viewport eye context index
InOutViewLocation - (in, out) View location
InOutViewRotation - (in,out) View rotator
WorldToMeters - UE world scale
Returns
- true, if the calculation of the viewport projection is successful.
References FVector, InOutViewLocation, InOutViewRotation, and WorldToMeters.
GetCameraComponentView()
bool IDisplayClusterViewport::GetCameraComponentView (UCameraComponent * InCameraComponent, const float InDeltaTime, const bool bUseCameraPostprocess, FMinimalViewInfo & InOutViewInfo, float * OutCustomNearClippingPlane = nullptr) static
Get View from CameraComponent.
Parameters
InCameraComponent - Ptr to the camera component used for rendering. if this ptr is nullptr, then the active player camera is used
InDeltaTime - delta time in current frame
bUseCameraPostprocess - If false, then InOutViewInfo.PostProcessBlendWeight is set to 0.
InOutViewInfo - ViewPoint data
OutCustomNearClippingPlane - Custom NCP, or a value less than zero if not defined.
Returns
false if the viewpoint data cannot be retrieved.
GetClippingPlanes()
virtual FVector2D IDisplayClusterViewport::GetClippingPlanes () const pure virtual
Get clipping planes used by this viewport.
Returns
Clipping planes as FVector2D(ZNear, ZFar)
GetClusterNodeId()
virtual FString IDisplayClusterViewport::GetClusterNodeId () const pure virtual
GetConfiguration() [1/2]
virtual const IDisplayClusterViewportConfiguration & IDisplayClusterViewport::GetConfiguration () const pure virtual
[const] Get viewport manager configuration interface.
GetConfiguration() [2/2]
virtual IDisplayClusterViewportConfiguration & IDisplayClusterViewport::GetConfiguration () pure virtual
Get viewport manager configuration interface.
Referenced by UE_DEPRECATED().
GetConfigurationRef() [1/2]
virtual const TSharedRef< const IDisplayClusterViewportConfiguration, ESPMode::ThreadSafe > IDisplayClusterViewport::GetConfigurationRef () const pure virtual
[const] Get viewport manager configuration interface reference.
GetConfigurationRef() [2/2]
virtual const TSharedRef< IDisplayClusterViewportConfiguration, ESPMode::ThreadSafe > IDisplayClusterViewport::GetConfigurationRef () pure virtual
Get viewport manager configuration interface reference.
GetContexts()
virtual const TArray< FDisplayClusterViewport_Context > & IDisplayClusterViewport::GetContexts () const pure virtual
Get viewport contexts.
GetDisplayDeviceComponent()
virtual class UDisplayClusterDisplayDeviceBaseComponent * IDisplayClusterViewport::GetDisplayDeviceComponent (const EDisplayClusterRootActorType InRootActorType) const pure virtual
Return a DisplayDevice component for this viewport.
Parameters
InRootActorType - the root type
GetId()
virtual FString IDisplayClusterViewport::GetId () const pure virtual
GetOCIOConversionSettings()
virtual bool IDisplayClusterViewport::GetOCIOConversionSettings (FOpenColorIOColorConversionSettings & OutOCIOConversionSettings) const pure virtual
Returns OCIO configuration if any set.
Returns
true if OCIO is configured
GetPlayerCameraView()
bool IDisplayClusterViewport::GetPlayerCameraView (UWorld * InWorld, const bool bUseCameraPostprocess, FMinimalViewInfo & InOutViewInfo) static
Get View from current player camera.
Parameters
InWorld - In this world, an active game camera will be searched for.
bUseCameraPostprocess - if false, then InOutViewInfo.PostProcessBlendWeight is set to 0.
InOutViewInfo - (in,out) ViewPoint data
Returns
false if the viewpoint data cannot be retrieved.
GetPostRenderSettings()
virtual const FDisplayClusterViewport_PostRenderSettings & IDisplayClusterViewport::GetPostRenderSettings () const pure virtual
Get post-render settings.
GetProjectionMatrix()
virtual bool IDisplayClusterViewport::GetProjectionMatrix (const uint32 InContextNum, FMatrix & OutPrjMatrix) pure virtual
Get projection matrix for viewport context.
Parameters
InContextNum - viewport eye context index
OutPrjMatrix - (out) Projection matrix
Returns
true, if projection matrix valid.
GetProjectionPolicy()
virtual const TSharedPtr< class IDisplayClusterProjectionPolicy, ESPMode::ThreadSafe > & IDisplayClusterViewport::GetProjectionPolicy () const pure virtual
Get projection policy ref.
GetRenderSettings()
virtual const FDisplayClusterViewport_RenderSettings & IDisplayClusterViewport::GetRenderSettings () const pure virtual
Get main viewport render settings.
GetRenderSettingsICVFX()
virtual const FDisplayClusterViewport_RenderSettingsICVFX & IDisplayClusterViewport::GetRenderSettingsICVFX () const pure virtual
Get ICVFX render settings.
GetStereoEyeOffsetDistance()
virtual float IDisplayClusterViewport::GetStereoEyeOffsetDistance (const uint32 InContextNum) pure virtual
Get the distance from the eye to the viewpoint location.
Parameters
InContextNum - eye context of this viewport
GetViewPointCameraComponent()
virtual class UDisplayClusterCameraComponent * IDisplayClusterViewport::GetViewPointCameraComponent (const EDisplayClusterRootActorType InRootActorType) const pure virtual
Return view point camera component for this viewport.
Parameters
InRootActorType - the root type
Referenced by UE_DEPRECATED().
GetViewPointCameraEye()
virtual bool IDisplayClusterViewport::GetViewPointCameraEye (const uint32 InContextNum, FVector & OutViewLocation, FRotator & OutViewRotation, FVector & OutViewOffset) pure virtual
Retrieves the view position from the ViewPoint component used by this viewport.
The CalculateView() function receives arguments that may not match this position because they can be overridden. Therefore, projection policies that expect values from the ViewPoint component must use this function to get the correct values.
References FVector.
GetViewport_CustomPostProcessSettings() [1/2]
virtual const IDisplayClusterViewport_CustomPostProcessSettings & IDisplayClusterViewport::GetViewport_CustomPostProcessSettings () const pure virtual
[const] Get custom postprocess settings for this viewport.
GetViewport_CustomPostProcessSettings() [2/2]
virtual IDisplayClusterViewport_CustomPostProcessSettings & IDisplayClusterViewport::GetViewport_CustomPostProcessSettings () pure virtual
Get custom postprocess settings for this viewport.
GetViewportPreview()
virtual IDisplayClusterViewportPreview & IDisplayClusterViewport::GetViewportPreview () const pure virtual
Get viewport preview API.
MakeProjectionMatrix()
FMatrix IDisplayClusterViewport::MakeProjectionMatrix (float InLeft, float InRight, float InTop, float InBottom, float ZNear, float ZFar) static
Make asymmetrical projection matrix for nDisplay.
SetContexts()
virtual void IDisplayClusterViewport::SetContexts (TArray< FDisplayClusterViewport_Context > & InContexts) pure virtual
Change viewport contexts data.
This function must be called in a valid moment in time.
SetRenderSettings()
virtual void IDisplayClusterViewport::SetRenderSettings (const FDisplayClusterViewport_RenderSettings & InRenderSettings) pure virtual
Change render setting for viewport.
This function must be called in a valid moment in time.
SetupSceneView()
virtual void IDisplayClusterViewport::SetupSceneView (uint32 ContextNum, class UWorld * World, class FSceneViewFamily & InViewFamily, FSceneView & InView) const pure virtual
Setup scene view for rendering specified Context.
SetupViewPoint()
virtual bool IDisplayClusterViewport::SetupViewPoint (const uint32 InContextNum, struct FMinimalViewInfo & InOutViewInfo) pure virtual
Setup viewpoint for this viewport.
Parameters
InOutViewInfo - [in\out] viewinfo
Returns
- true if there is an internal viewpoint for the given viewport.
ToSharedPtr() [1/2]
virtual TSharedPtr< const IDisplayClusterViewport, ESPMode::ThreadSafe > IDisplayClusterViewport::ToSharedPtr () const pure virtual
ToSharedPtr() [2/2]
virtual TSharedPtr< IDisplayClusterViewport, ESPMode::ThreadSafe > IDisplayClusterViewport::ToSharedPtr () pure virtual
Get TSharedPtr from self.
ToSharedRef() [1/2]
virtual TSharedRef< const class FDisplayClusterViewport, ESPMode::ThreadSafe > IDisplayClusterViewport::ToSharedRef () const pure virtual
ToSharedRef() [2/2]
virtual TSharedRef< class FDisplayClusterViewport, ESPMode::ThreadSafe > IDisplayClusterViewport::ToSharedRef () pure virtual
Internal functions.
Get TSharedRef from Self.
UE_DEPRECATED() [1/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 3, "This function has been deprecated. Please use 'CalculateView()'.") const
Calculate viewport projection (This function has been deprecated.)
Parameters
InContextNum - viewport eye context index
InOutViewLocation - (in, out) View location
InOutViewRotation - (in,out) View rotator
ViewOffset - eye offset from view location
WorldToMeters - UE world scale
NCP - Near clipping plane
FCP - Far clipping plane
Returns
- true, if the calculation of the viewport projection is successful.
UE_DEPRECATED() [2/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 3, "This function has beend deprecate. Please use 'GetViewportManager()'.") const & inline
Definition at line 210 of file IDisplayClusterViewport.h.
References check, and GetConfiguration().
UE_DEPRECATED() [3/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetConfiguration()'.") const inline
Returns true if the current world type is equal to one of the input types.
Setup viewpoint for this viewport
Parameters
InOutViewInfo - [in\out] viewinfo
Returns
- true if there is an internal viewpoint for the given viewport.
Definition at line 280 of file IDisplayClusterViewport.h.
References None.
UE_DEPRECATED() [4/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetConfiguration()'.") const inline
Returns true if the scene is open now (The current world is assigned and DCRA has already initialized for it).
Definition at line 273 of file IDisplayClusterViewport.h.
UE_DEPRECATED() [5/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetConfiguration()'.") const inline
Gets a reference to the DCRA with actual configuration inside.
Definition at line 252 of file IDisplayClusterViewport.h.
UE_DEPRECATED() [6/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetConfiguration()'.") const inline
Return the viewport manager that owns this viewport.
Definition at line 245 of file IDisplayClusterViewport.h.
UE_DEPRECATED() [7/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetConfiguration()'.") const inline
Return current world.
Definition at line 266 of file IDisplayClusterViewport.h.
UE_DEPRECATED() [8/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetConfiguration()'.") const inline
Return current render mode.
Definition at line 259 of file IDisplayClusterViewport.h.
References Unknown.
UE_DEPRECATED() [9/9]
IDisplayClusterViewport::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'GetViewPointCameraComponent(EDisplayClusterRootActorType)'.") const inline
Return view point camera component for this viewport.
Definition at line 238 of file IDisplayClusterViewport.h.
References GetViewPointCameraComponent().
UseSameOCIO()
virtual bool IDisplayClusterViewport::UseSameOCIO (const IDisplayClusterViewport * InViewport) const pure virtual
Returns true if both viewports use the same OCIO.
Field Documentation
FCP
FVector FRotator const FVector const float const float const float IDisplayClusterViewport::FCP
Initial value:
{
        return false
Definition at line 231 of file IDisplayClusterViewport.h.
InOutViewLocation
FVector& IDisplayClusterViewport::InOutViewLocation
Definition at line 231 of file IDisplayClusterViewport.h.
Referenced by CalculateView().
InOutViewRotation
FVector FRotator& IDisplayClusterViewport::InOutViewRotation
Definition at line 231 of file IDisplayClusterViewport.h.
Referenced by CalculateView().
NCP
FVector FRotator const FVector const float const float IDisplayClusterViewport::NCP
Definition at line 231 of file IDisplayClusterViewport.h.
ViewOffset
FVector FRotator const FVector& IDisplayClusterViewport::ViewOffset
Definition at line 231 of file IDisplayClusterViewport.h.
WorldToMeters
FVector FRotator const FVector const float IDisplayClusterViewport::WorldToMeters
Definition at line 231 of file IDisplayClusterViewport.h.
Referenced by CalculateView().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Render/Viewport/IDisplayClusterViewport.h