Unreal Engine 5.6 C++ API: UE::Geometry::FBCSplineFilter< SplineType, bIsRadial > Class Template Reference
UE::Geometry::FBCSplineFilter< SplineType, bIsRadial > Class Template Reference
#include "BCSplineFilter.h"
Public Member Functions
FBCSplineFilter (const float RadiusIn)
float GetWeight (const FVector2d &Dist) const
bool IsInFilterRegion (const FVector2d &Dist) const
Private Attributes
float Coeff1 [3] = {0.0f, 0.0f, 0.0f}
float Coeff2 [4] = {0.0f, 0.0f, 0.0f, 0.0f}
float InvRadius = 1.0f
Detailed Description
template<EBCSplineType SplineType, bool bIsRadial>
class UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >
Parameters
SplineType The BC-spline filter type (predefined B/C parameters)
bIsRadial When true, use Euclidean distance to compute filter weights: Weight = Filter(sqrt(X*X + Y*Y)). Otherwise use linear 1D distance in X/Y separately: WX = Filter(X), WY = Filter(Y), Weight = WX*WY
TODO The Unreal naming convention uses the T prefix for template functions. This would require deprecation. TODO Consider removing the Abs from GetWeight since distances are non-negative. This would require deprecation. TODO Consider using constexpr polynomial coefficients to make this class smaller
Definition at line 30 of file BCSplineFilter.h.
Constructor & Destructor Documentation
FBCSplineFilter()
template<EBCSplineType SplineType, bool bIsRadial> UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::FBCSplineFilter (const float RadiusIn)
Definition at line 51 of file BCSplineFilter.h.
References B, UE::Geometry::BSpline, UE::Geometry::CatmullRom, Coeff1, Coeff2, InvRadius, and UE::Geometry::MitchellNetravali.
Member Function Documentation
GetWeight()
template<EBCSplineType SplineType, bool bIsRadial> float UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::GetWeight (const FVector2d & Dist) const
Returns
The filter weight given a 2D distance vector
Note
Works on general 2D point sets i.e., does not assume Cartesian/pixel grids
Definition at line 89 of file BCSplineFilter.h.
References TMathUtil< float >::Abs(), Coeff1, Coeff2, InvRadius, UE::Math::TVector2< T >::Length(), Weight, UE::Math::TVector2< T >::X, X, and UE::Math::TVector2< T >::Y.
IsInFilterRegion()
template<EBCSplineType SplineType, bool bIsRadial> bool UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::IsInFilterRegion (const FVector2d & Dist) const
Returns
true if the given 2D distance vector is in the region where the filter is defined and false otherwise
Definition at line 123 of file BCSplineFilter.h.
References TMathUtil< float >::Abs(), InvRadius, UE::Math::TVector2< T >::Length(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Field Documentation
Coeff1
template<EBCSplineType SplineType, bool bIsRadial> float UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::Coeff1[3] = {0.0f, 0.0f, 0.0f} private
Definition at line 35 of file BCSplineFilter.h.
Referenced by FBCSplineFilter(), and GetWeight().
Coeff2
template<EBCSplineType SplineType, bool bIsRadial> float UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::Coeff2[4] = {0.0f, 0.0f, 0.0f, 0.0f} private
Definition at line 36 of file BCSplineFilter.h.
Referenced by FBCSplineFilter(), and GetWeight().
InvRadius
template<EBCSplineType SplineType, bool bIsRadial> float UE::Geometry::FBCSplineFilter< SplineType, bIsRadial >::InvRadius = 1.0f private
Definition at line 33 of file BCSplineFilter.h.
Referenced by FBCSplineFilter(), GetWeight(), and IsInFilterRegion().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Image/BCSplineFilter.h