Unreal Engine 5.6 C++ API: FVectorIntervalFixed32NoW Class Reference
FVectorIntervalFixed32NoW Class Reference
#include "AnimationCompression.h"
Public Member Functions
FVectorIntervalFixed32NoW ()
FVectorIntervalFixed32NoW (const FVector3f &Value, const float *Mins, const float *Ranges)
void FromVector (const FVector3f &Value, const float *Mins, const float *Ranges)
void ToVector (FVector3f &Out, const float *Mins, const float *Ranges) const
Static Public Member Functions
template<bool bIsDataAligned = true>
static FVector3f ToVector (const float *Mins, const float *Ranges, const uint32 *PackedValue)
Data Fields
uint32 Packed
Friends
FArchive & operator<< (FArchive &Ar, FVectorIntervalFixed32NoW &Value)
Detailed Description
Definition at line 338 of file AnimationCompression.h.
Constructor & Destructor Documentation
FVectorIntervalFixed32NoW() [1/2]
FVectorIntervalFixed32NoW::FVectorIntervalFixed32NoW () inline
Definition at line 343 of file AnimationCompression.h.
Referenced by operator<<.
FVectorIntervalFixed32NoW() [2/2]
FVectorIntervalFixed32NoW::FVectorIntervalFixed32NoW (const FVector3f & Value, const float * Mins, const float * Ranges) inline explicit
Definition at line 346 of file AnimationCompression.h.
References FromVector(), and Value.
Member Function Documentation
FromVector()
void FVectorIntervalFixed32NoW::FromVector (const FVector3f & Value, const float * Mins, const float * Ranges) inline
Definition at line 351 of file AnimationCompression.h.
References Packed, Quant10BitFactor, Quant10BitOffs, Quant11BitFactor, Quant11BitOffs, Value, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by FVectorIntervalFixed32NoW().
ToVector() [1/2]
template<bool bIsDataAligned = true> FVector3f FVectorIntervalFixed32NoW::ToVector (const float * Mins, const float * Ranges, const uint32 * PackedValue) inline static
Definition at line 370 of file AnimationCompression.h.
References Packed, Quant10BitDiv, Quant10BitOffs, Quant11BitDiv, Quant11BitOffs, AnimationCompressionUtils::UnalignedRead(), X, Y, and Z.
Referenced by DecompressScale(), FAnimationCompression_PerTrackUtils::DecompressScale(), DecompressTranslation(), FAnimationCompression_PerTrackUtils::DecompressTranslation(), and ToVector().
ToVector() [2/2]
void FVectorIntervalFixed32NoW::ToVector (FVector3f & Out, const float * Mins, const float * Ranges) const inline
Definition at line 390 of file AnimationCompression.h.
References Packed, and ToVector().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FVectorIntervalFixed32NoW & Value) friend
Definition at line 395 of file AnimationCompression.h.
References FVectorIntervalFixed32NoW(), Ar, and Value.
Field Documentation
Packed
uint32 FVectorIntervalFixed32NoW::Packed
Definition at line 341 of file AnimationCompression.h.
Referenced by FromVector(), ToVector(), and ToVector().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AnimationCompression.h