Unreal Engine 5.6 C++ API: TInteractiveToolCommands< CommandContextType > Class Template Reference
TInteractiveToolCommands< CommandContextType > Class Template Reference abstract
TInteractiveToolCommands is a base class that handles connecting up Tool Actions (ie the FInteractiveToolAction provided by a UInteractiveTool) to the UnrealEditor Command system, which allows for remappable hotkeys, etc.
#include "InteractiveToolsCommands.h"
Data Structures
struct FToolActionCommand
List of pairs of known Tool Actions and their associated UICommands.
Public Member Functions
virtual void BindCommandsForCurrentTool (TSharedPtr< FUICommandList > UICommandList, UInteractiveTool *Tool) const override
Bind any of the registered UICommands to the given Tool, if they are compatible.
virtual void GetToolDefaultObjectList (TArray< UInteractiveTool * > &ToolCDOs)=0
RegisterCommands() needs actual UInteractiveTool instances for all the Tools that want to provide Actions which will be connected to hotkeys.
virtual void RegisterCommands () override
Initialize commands.
virtual void UnbindActiveCommands (TSharedPtr< FUICommandList > UICommandList) const override
Unbind all of the currently-registered commands.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
TInteractiveToolCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Forwarding constructor.
bool FindOrCreateSharedCommand (EStandardToolActions ActionID, FToolActionCommand &FoundOut)
Find or Create a UICommand for a standard Tool Action, that will be shared across Tools.
virtual TSharedPtr< FUICommandInfo > FindStandardCommand (EStandardToolActions ToolActionID)
Query FStandardToolModeCommands to find an existing command/hotkey for this standard tool action.
virtual bool IntializeStandardToolAction (EStandardToolActions ActionID, FInteractiveToolAction &ToolActionOut)
Create a suitable FInteractiveToolAction for the standard Tool Action, ie with suitable command name and description strings and hotkeys.
void RegisterUIToolCommand (const FInteractiveToolAction &ToolAction, TSharedPtr< FUICommandInfo > &UICommandInfo)
Utility function that registeres a Tool Aciton as a UICommand.
Protected Member Functions inherited from TCommands< CommandContextType >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TArray< FToolActionCommand > ActionCommands
TMap< EStandardToolActions, FToolActionCommand > SharedActionCommands
List FToolActionCommands for standard Tool Actions.
Additional Inherited Members
Static Public Member Functions inherited from TCommands< CommandContextType >
static CommandContextType & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Static Protected Member Functions inherited from TCommands< CommandContextType >
static TWeakPtr< CommandContextType > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename CommandContextType>
class TInteractiveToolCommands< CommandContextType >
TInteractiveToolCommands is a base class that handles connecting up Tool Actions (ie the FInteractiveToolAction provided by a UInteractiveTool) to the UnrealEditor Command system, which allows for remappable hotkeys, etc.
Usage is as follows:
in your EdMode Module, create a subclass-instance of this, say FMyToolCommands and call FMyToolCommands::Register() in your ::StartupModule() function
subclass must implement GetToolDefaultObjectList(), here you just add GetMutableDefault<MyToolX> to the input list for all your Tools
add a member TSharedPtr<FUICommandList> UICommandList; to your EdMode impl
when you start a new Tool, call FMyToolCommands::Get().BindCommandsForCurrentTool(UICommandList, NewTool)
when you end a Tool, call FMyToolCommands::Get().UnbindActiveCommands()
in your EdModeImpl::InputKey override, call UICommandList->ProcessCommandBindings()
Definition at line 49 of file InteractiveToolsCommands.h.
Constructor & Destructor Documentation
TInteractiveToolCommands()
template<typename CommandContextType> TInteractiveToolCommands< CommandContextType >::TInteractiveToolCommands (const FName InContextName, const FText & InContextDesc, const FName InContextParent, const FName InStyleSetName) inline protected
Forwarding constructor.
Definition at line 89 of file InteractiveToolsCommands.h.
References TCommands< CommandContextType >::TCommands().
Member Function Documentation
BindCommandsForCurrentTool()
template<typename CommandContextType> void TInteractiveToolCommands< CommandContextType >::BindCommandsForCurrentTool (TSharedPtr< FUICommandList > UICommandList, UInteractiveTool * Tool) const override virtual
Bind any of the registered UICommands to the given Tool, if they are compatible.
Implements UE::IInteractiveToolCommandsInterface.
Definition at line 210 of file InteractiveToolsCommands.h.
References ActionCommands, FInteractiveToolAction::ActionID, FInteractiveToolAction::ClassType, TInteractiveToolCommands< CommandContextType >::FToolActionCommand::ToolAction, and TInteractiveToolCommands< CommandContextType >::FToolActionCommand::UICommand.
FindOrCreateSharedCommand()
template<typename CommandContextType> bool TInteractiveToolCommands< CommandContextType >::FindOrCreateSharedCommand (EStandardToolActions ActionID, FToolActionCommand & FoundOut) protected
Find or Create a UICommand for a standard Tool Action, that will be shared across Tools.
Definition at line 280 of file InteractiveToolsCommands.h.
References FInteractiveToolAction::ActionID, check, IntializeStandardToolAction(), RegisterUIToolCommand(), SharedActionCommands, TInteractiveToolCommands< CommandContextType >::FToolActionCommand::ToolAction, and TInteractiveToolCommands< CommandContextType >::FToolActionCommand::UICommand.
Referenced by RegisterCommands().
FindStandardCommand()
template<typename CommandContextType> TSharedPtr< FUICommandInfo > TInteractiveToolCommands< CommandContextType >::FindStandardCommand (EStandardToolActions ToolActionID) protected virtual
Query FStandardToolModeCommands to find an existing command/hotkey for this standard tool action.
Definition at line 253 of file InteractiveToolsCommands.h.
References DecreaseBrushSize, FStandardToolModeCommands::FindStandardCommand(), TCommands< FStandardToolModeCommands >::Get(), IncreaseBrushSize, and ToggleWireframe.
Referenced by RegisterCommands().
GetToolDefaultObjectList()
template<typename CommandContextType> virtual void TInteractiveToolCommands< CommandContextType >::GetToolDefaultObjectList (TArray< UInteractiveTool * > & ToolCDOs) pure virtual
RegisterCommands() needs actual UInteractiveTool instances for all the Tools that want to provide Actions which will be connected to hotkeys.
We can do this based on the CDO's for each tool, returned by GetMutableDefault<UYourInteractiveToolType>(). The Tool CDOs are not owned by a ToolManager and we will only call .GetActionSet() on them.
Referenced by RegisterCommands().
IntializeStandardToolAction()
template<typename CommandContextType> bool TInteractiveToolCommands< CommandContextType >::IntializeStandardToolAction (EStandardToolActions ActionID, FInteractiveToolAction & ToolActionOut) protected virtual
Create a suitable FInteractiveToolAction for the standard Tool Action, ie with suitable command name and description strings and hotkeys.
This info will be used to create the shared UICommand.
Definition at line 305 of file InteractiveToolsCommands.h.
Referenced by FindOrCreateSharedCommand().
RegisterCommands()
template<typename CommandContextType> void TInteractiveToolCommands< CommandContextType >::RegisterCommands () override virtual
Initialize commands.
Collects possible Actions from the available UInteractiveTools (provided by GetToolDefaultObjectList) and then registers a FUICommandInfo for each. This needs to be called in ::StartupModule for your EdMode Module
Implements TCommands< CommandContextType >.
Definition at line 142 of file InteractiveToolsCommands.h.
References ActionCommands, FInteractiveToolAction::ActionID, BaseClientDefinedActionID, ensureMsgf, FindOrCreateSharedCommand(), FindStandardCommand(), GetToolDefaultObjectList(), TSharedPtr< ObjectType, InMode >::IsValid(), TArray< InElementType, InAllocatorType >::Num(), TCommands< FStandardToolModeCommands >::Register(), RegisterUIToolCommand(), TEXT, and TInteractiveToolCommands< CommandContextType >::FToolActionCommand::UICommand.
RegisterUIToolCommand()
template<typename CommandContextType> void TInteractiveToolCommands< CommandContextType >::RegisterUIToolCommand (const FInteractiveToolAction & ToolAction, TSharedPtr< FUICommandInfo > & UICommandInfo) protected
Utility function that registeres a Tool Aciton as a UICommand.
Definition at line 317 of file InteractiveToolsCommands.h.
References FInteractiveToolAction::ActionName, TSharedFromThis< FBindingContext >::AsShared(), FInteractiveToolAction::DefaultKey, FInteractiveToolAction::DefaultModifiers, FInteractiveToolAction::Description, FBindingContext::GetContextName(), FBindingContext::GetStyleSetName(), ISlateStyle::Join(), FUICommandInfo::MakeCommandInfo(), FInteractiveToolAction::ShortName, TCHAR_TO_ANSI, and TEXT.
Referenced by FindOrCreateSharedCommand(), and RegisterCommands().
UnbindActiveCommands()
template<typename CommandContextType> void TInteractiveToolCommands< CommandContextType >::UnbindActiveCommands (TSharedPtr< FUICommandList > UICommandList) const override virtual
Unbind all of the currently-registered commands.
Implements UE::IInteractiveToolCommandsInterface.
Definition at line 230 of file InteractiveToolsCommands.h.
References ActionCommands.
Field Documentation
ActionCommands
template<typename CommandContextType> TArray<FToolActionCommand> TInteractiveToolCommands< CommandContextType >::ActionCommands protected
Definition at line 108 of file InteractiveToolsCommands.h.
Referenced by BindCommandsForCurrentTool(), RegisterCommands(), and UnbindActiveCommands().
SharedActionCommands
template<typename CommandContextType> TMap<EStandardToolActions, FToolActionCommand> TInteractiveToolCommands< CommandContextType >::SharedActionCommands protected
List FToolActionCommands for standard Tool Actions.
Definition at line 117 of file InteractiveToolsCommands.h.
Referenced by FindOrCreateSharedCommand().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Tools/InteractiveToolsCommands.h