Unreal Engine 5.6 C++ API: TBulkDataScopedWriteLock< ElementType > Class Template Reference
TBulkDataScopedWriteLock< ElementType > Class Template Reference
Locks the given bulkdata object for read/write access.
#include "BulkDataScopedLock.h"
Public Member Functions
TBulkDataScopedWriteLock (TBulkData< ElementType > &InBulkData)
~TBulkDataScopedWriteLock ()
int64 GetAllocatedSize () const
Returns the length of the bulkdata payload in bytes.
ElementType * GetData () const
Returns a raw pointer to the bulkdata payload.
TArrayView64< ElementType > GetView () const
Returns the bulkdata payload wrapped in a TArrayView64 for added safety.
int64 Num () const
Returns the number of elements in the bulkdata payload.
UE_NONCOPYABLE (TBulkDataScopedWriteLock)
Private Attributes
TBulkData< ElementType > & BulkData
ElementType * Data
Detailed Description
template<typename ElementType>
class TBulkDataScopedWriteLock< ElementType >
Locks the given bulkdata object for read/write access.
Note that performing actions on the original bulkdata object while this scope is active (such as calls to realloc) may cause problems. Only use this object for bulkdata operations while it is active.
Definition at line 67 of file BulkDataScopedLock.h.
Constructor & Destructor Documentation
TBulkDataScopedWriteLock()
template<typename ElementType> TBulkDataScopedWriteLock< ElementType >::TBulkDataScopedWriteLock (TBulkData< ElementType > & InBulkData) inline
Definition at line 72 of file BulkDataScopedLock.h.
References BulkData, Data, FBulkData::Lock(), and LOCK_READ_WRITE.
Referenced by UE_NONCOPYABLE().
~TBulkDataScopedWriteLock()
template<typename ElementType> TBulkDataScopedWriteLock< ElementType >::~TBulkDataScopedWriteLock () inline
Definition at line 78 of file BulkDataScopedLock.h.
References BulkData.
Member Function Documentation
GetAllocatedSize()
template<typename ElementType> int64 TBulkDataScopedWriteLock< ElementType >::GetAllocatedSize () const inline
Returns the length of the bulkdata payload in bytes.
Definition at line 90 of file BulkDataScopedLock.h.
References BulkData.
GetData()
template<typename ElementType> ElementType * TBulkDataScopedWriteLock< ElementType >::GetData () const inline
Returns a raw pointer to the bulkdata payload.
Definition at line 96 of file BulkDataScopedLock.h.
References Data.
GetView()
template<typename ElementType> TArrayView64< ElementType > TBulkDataScopedWriteLock< ElementType >::GetView () const inline
Returns the bulkdata payload wrapped in a TArrayView64 for added safety.
Definition at line 102 of file BulkDataScopedLock.h.
References Data, and Num().
Num()
template<typename ElementType> int64 TBulkDataScopedWriteLock< ElementType >::Num () const inline
Returns the number of elements in the bulkdata payload.
Definition at line 84 of file BulkDataScopedLock.h.
References BulkData.
Referenced by GetView().
UE_NONCOPYABLE()
template<typename ElementType> TBulkDataScopedWriteLock< ElementType >::UE_NONCOPYABLE (TBulkDataScopedWriteLock< ElementType >)
References TBulkDataScopedWriteLock().
Field Documentation
BulkData
template<typename ElementType> TBulkData<ElementType>& TBulkDataScopedWriteLock< ElementType >::BulkData private
Definition at line 109 of file BulkDataScopedLock.h.
Referenced by TBulkDataScopedWriteLock(), ~TBulkDataScopedWriteLock(), GetAllocatedSize(), and Num().
Data
template<typename ElementType> ElementType* TBulkDataScopedWriteLock< ElementType >::Data private
Definition at line 110 of file BulkDataScopedLock.h.
Referenced by TBulkDataScopedWriteLock(), GetData(), and GetView().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/BulkDataScopedLock.h