Unreal Engine 5.6 C++ API: HHitProxy Class Reference
HHitProxy Class Reference
Base class for detecting user-interface hits.
#include "HitProxies.h"
Public Member Functions
HHitProxy (EHitProxyPriority InPriority, EHitProxyPriority InOrthoPriority)
HHitProxy (EHitProxyPriority InPriority=HPP_World)
virtual ~HHitProxy ()
virtual void AddReferencedObjects (FReferenceCollector &Collector)
virtual bool AlwaysAllowsTranslucentPrimitives () const
Method that specifies whether the hit proxy always allows translucent primitives to be associated with it or not, regardless of any other engine/editor setting.
virtual FTypedElementHandle GetElementHandle () const
Get the element handle associated with this hit proxy, if any.
virtual EMouseCursor::Type GetMouseCursor ()
Override to change the mouse based on what it is hovering over.
virtual HHitProxyType * GetType () const
bool IsA (HHitProxyType *TestType) const
Determines whether the hit proxy is of the given type.
Public Member Functions inherited from FRefCountedObject
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Static Public Member Functions
static HHitProxyType * StaticGetType ()
Data Fields
FHitProxyId Id
The hit proxy's ID.
const EHitProxyPriority OrthoPriority
Used in the ortho views, defaults to the same value as Priority.
const EHitProxyPriority Priority
The priority a hit proxy has when choosing between several hit proxies near the point the user clicked.
Private Member Functions
void InitHitProxy ()
Detailed Description
Base class for detecting user-interface hits.
Definition at line 134 of file HitProxies.h.
Constructor & Destructor Documentation
HHitProxy() [1/2]
HHitProxy::HHitProxy (EHitProxyPriority InPriority = HPP_World)
Referenced by HActor::HActor(), HActor::HActor(), HBSPBrushVert::HBSPBrushVert(), HComponentVisProxy::HComponentVisProxy(), HInstancedStaticMeshInstance::HInstancedStaticMeshInstance(), HLevelSocketProxy::HLevelSocketProxy(), HObject::HObject(), HPersonaBoneHitProxy::HPersonaBoneHitProxy(), HPersonaSocketHitProxy::HPersonaSocketHitProxy(), HStaticMeshVert::HStaticMeshVert(), and HWidgetUtilProxy::HWidgetUtilProxy().
HHitProxy() [2/2]
HHitProxy::HHitProxy (EHitProxyPriority InPriority, EHitProxyPriority InOrthoPriority)
~HHitProxy()
virtual HHitProxy::~HHitProxy () virtual
Member Function Documentation
AddReferencedObjects()
virtual void HHitProxy::AddReferencedObjects (FReferenceCollector & Collector) inline virtual
Reimplemented in HActor, HBSPBrushVert, HInstancedStaticMeshInstance, HLandscapeSplineProxy_ControlPoint, HLandscapeSplineProxy_Segment, HLandscapeSplineProxy_Tangent, HLevelSocketProxy, HModel, and HStaticMeshVert.
Definition at line 158 of file HitProxies.h.
AlwaysAllowsTranslucentPrimitives()
virtual bool HHitProxy::AlwaysAllowsTranslucentPrimitives () const inline virtual
Method that specifies whether the hit proxy always allows translucent primitives to be associated with it or not, regardless of any other engine/editor setting.
For example, if translucent selection was disabled, any hit proxies returning true would still allow translucent selection.
Returns
true if translucent primitives are always allowed with this hit proxy; false otherwise
Reimplemented in HActor, HTranslucentActor, and HWidgetAxis.
Definition at line 177 of file HitProxies.h.
GetElementHandle()
virtual FTypedElementHandle HHitProxy::GetElementHandle () const virtual
Get the element handle associated with this hit proxy, if any.
Reimplemented in HActor, HComponentVisProxy, and HInstancedStaticMeshInstance.
GetMouseCursor()
virtual EMouseCursor::Type HHitProxy::GetMouseCursor () virtual
Override to change the mouse based on what it is hovering over.
Reimplemented in HActor, HComponentVisProxy, HInstancedStaticMeshInstance, HLandscapeSplineProxy, HLandscapeSplineProxy_Tangent, HModel, HMovieSceneKeyProxy, HMovieSceneSkeletalAnimationRootHitProxy, HPersonaBoneHitProxy, HPersonaSocketHitProxy, HTranslucentActor, and HWidgetAxis.
GetType()
virtual HHitProxyType * HHitProxy::GetType () const inline virtual
Reimplemented in HActor, HBSPBrushVert, HModel, HObject, HStaticMeshVert, and HTranslucentActor.
Definition at line 140 of file HitProxies.h.
References GetType(), and StaticGetType().
Referenced by GetType().
InitHitProxy()
void HHitProxy::InitHitProxy () private
IsA()
bool HHitProxy::IsA (HHitProxyType * TestType) const
Determines whether the hit proxy is of the given type.
Referenced by HitProxyCast().
StaticGetType()
HHitProxyType * HHitProxy::StaticGetType () static
Referenced by GetType().
Field Documentation
Id
FHitProxyId HHitProxy::Id
The hit proxy's ID.
Definition at line 153 of file HitProxies.h.
OrthoPriority
const EHitProxyPriority HHitProxy::OrthoPriority
Used in the ortho views, defaults to the same value as Priority.
Definition at line 150 of file HitProxies.h.
Priority
const EHitProxyPriority HHitProxy::Priority
The priority a hit proxy has when choosing between several hit proxies near the point the user clicked.
Definition at line 147 of file HitProxies.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/HitProxies.h