Unreal Engine 5.6 C++ API: TValueWatcher< ValueType > Class Template Reference
TValueWatcher< ValueType > Class Template Reference
TValueWatcher is used to implement a common Tool pattern where it is necessary to essentially poll a value to see if it has changed, and if it has, call a function.
#include "ValueWatcher.h"
Public Member Functions
void CheckAndUpdate ()
void Initialize (TFunction< ValueType(void)> GetValueFuncIn, TFunction< void(ValueType)> OnValueChangedFuncIn, ValueType InitialValue)
void SilentUpdate ()
Update known value without calling OnValueChangedFunc.
Private Attributes
ValueType CachedValue
TFunction< ValueType(void)> GetValueFunc
TFunction< void(ValueType)> OnValueChangedFunc
Detailed Description
template<typename ValueType>
class TValueWatcher< ValueType >
TValueWatcher is used to implement a common Tool pattern where it is necessary to essentially poll a value to see if it has changed, and if it has, call a function.
For example UObject UProperties are frequently directly modified by (eg) DetailsView/etc, this results in PropertyChange events that can be used in the editor to respond to changes. However at Runtime no such events are generated and so the Tool has no way of knowing when UProperties change except by polling and comparing with a cached value. The purpose of this class is simply to encapsulate this common pattern/logic.
Definition at line 18 of file ValueWatcher.h.
Member Function Documentation
CheckAndUpdate()
template<typename ValueType> void TValueWatcher< ValueType >::CheckAndUpdate () inline
Definition at line 35 of file ValueWatcher.h.
References CachedValue, GetValueFunc, and OnValueChangedFunc.
Initialize()
template<typename ValueType> void TValueWatcher< ValueType >::Initialize (TFunction< ValueType(void)> GetValueFuncIn, TFunction< void(ValueType)> OnValueChangedFuncIn, ValueType InitialValue) inline
Definition at line 25 of file ValueWatcher.h.
References CachedValue, GetValueFunc, and OnValueChangedFunc.
SilentUpdate()
template<typename ValueType> void TValueWatcher< ValueType >::SilentUpdate () inline
Update known value without calling OnValueChangedFunc.
Sometimes necessary during undo/redo.
Definition at line 48 of file ValueWatcher.h.
References CachedValue, and GetValueFunc.
Field Documentation
CachedValue
template<typename ValueType> ValueType TValueWatcher< ValueType >::CachedValue private
Definition at line 20 of file ValueWatcher.h.
Referenced by CheckAndUpdate(), Initialize(), and SilentUpdate().
GetValueFunc
template<typename ValueType> TFunction<ValueType(void)> TValueWatcher< ValueType >::GetValueFunc private
Definition at line 21 of file ValueWatcher.h.
Referenced by CheckAndUpdate(), Initialize(), and SilentUpdate().
OnValueChangedFunc
template<typename ValueType> TFunction<void(ValueType)> TValueWatcher< ValueType >::OnValueChangedFunc private
Definition at line 22 of file ValueWatcher.h.
Referenced by CheckAndUpdate(), and Initialize().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Changes/ValueWatcher.h