Unreal Engine 5.6 C++ API: UKismetNodeHelperLibrary Class Reference
UKismetNodeHelperLibrary Class Reference
#include "KismetNodeHelperLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION()) static 1 bool BitIsMarked(int32 Data
Returns whether the bit at index "Index" is set or not in the data.
UFUNCTION ()) static 1 bool HasMarkedBit(int32 Data
Returns whether there exists a marked bit in the data.
UFUNCTION ()) static 1 bool HasUnmarkedBit(int32 Data
Returns whether there exists an unmarked bit in the data.
UFUNCTION ()) static 1 FName GetEnumeratorName(const UEnum *Enum
Gets enumerator name.
UFUNCTION ()) static 1 FString GetEnumeratorUserFriendlyName(const UEnum *Enum
Gets enumerator name as FString.
UFUNCTION ()) static 1 int32 GetFirstUnmarkedBit(int32 Data
Gets the first index not already marked starting from a specific index and returns the bit index selected.
UFUNCTION ()) static 1 int32 GetRandomUnmarkedBit(int32 Data
Gets a random not already marked bit and returns the bit index selected.
UFUNCTION ()) static 1 int32 GetUnmarkedBit(int32 Data
Gets an already unmarked bit and returns the bit index selected.
UFUNCTION ()) static 1 uint8 GetEnumeratorValueFromIndex(const UEnum *Enum
UFUNCTION ()) static 1 uint8 GetValidValue(const UEnum *Enum
UFUNCTION ()) static 1 void ClearAllBits(int32 &Data)
Clears all of the bit in the data.
UFUNCTION ()) static 1 void ClearBit(int32 &Data
Clears the bit at index "Index" in the data.
UFUNCTION ()) static 1 void MarkBit(int32 &Data
Sets the bit at index "Index" in the data.
Private Attributes
int32 int32 bool bRandom
uint8 EnumeratorIndex
uint8 EnumeratorValue
int32 Index
int32 NumBits
int32 int32 NumBits
int32 StartIdx
Detailed Description
Definition at line 16 of file KismetNodeHelperLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UKismetNodeHelperLibrary::GENERATED_UCLASS_BODY () private
Returns whether the bit at index "Index" is set or not in the data.
Parameters
Data - The integer containing the bits that are being tested against
Index - The bit index into the Data that we are inquiring
Returns
- Whether the bit at index "Index" is set or not
References meta, and UFUNCTION().
UFUNCTION() [1/12]
UKismetNodeHelperLibrary::UFUNCTION () private
Returns whether there exists a marked bit in the data.
Parameters
Data - The data being tested against
NumBits - The logical number of bits we want to track
Returns
- Whether there is a bit marked in the data
References meta, NumBits, and UFUNCTION().
UFUNCTION() [2/12]
UKismetNodeHelperLibrary::UFUNCTION () private
Returns whether there exists an unmarked bit in the data.
Parameters
Data - The data being tested against
NumBits - The logical number of bits we want to track
Returns
- Whether there is a bit not marked in the data
References meta, and UFUNCTION().
UFUNCTION() [3/12]
UKismetNodeHelperLibrary::UFUNCTION () const private
Gets enumerator name.
Parameters
Enum - Enumeration
EnumeratorValue - Value of searched enumeration
Returns
- name of the searched enumerator, or NAME_None
References meta, and UFUNCTION().
UFUNCTION() [4/12]
UKismetNodeHelperLibrary::UFUNCTION () const private
Gets enumerator name as FString.
Use DeisplayName when possible.
Parameters
Enum - Enumeration
EnumeratorValue - Value of searched enumeration
Returns
- name of the searched enumerator, or NAME_None
References Enum, EnumeratorValue, meta, and UFUNCTION().
UFUNCTION() [5/12]
UKismetNodeHelperLibrary::UFUNCTION () private
Gets the first index not already marked starting from a specific index and returns the bit index selected.
Parameters
Data - The integer containing the bits that are being set
StartIdx - The index to start looking for an available index from
NumBits - The logical number of bits we want to track
Returns
- The index that was selected (returns INDEX_NONE if there was no unmarked bits to choose from)
References meta, NumBits, StartIdx, and UFUNCTION().
UFUNCTION() [6/12]
UKismetNodeHelperLibrary::UFUNCTION () private
Gets a random not already marked bit and returns the bit index selected.
Parameters
Data - The integer containing the bits that are being set
NumBits - The logical number of bits we want to track
Returns
- The index that was selected (returns INDEX_NONE if there was no unmarked bits to choose from)
References meta, NumBits, StartIdx, and UFUNCTION().
UFUNCTION() [7/12]
UKismetNodeHelperLibrary::UFUNCTION () private
Gets an already unmarked bit and returns the bit index selected.
Parameters
Data - The integer containing the bits that are being set
StartIdx - The index to start with when determining the selection'
NumBits - The logical number of bits we want to track
bRandom - Whether to select a random index or not
Returns
- The index that was selected (returns INDEX_NONE if there was no unmarked bits to choose from)
References meta, and UFUNCTION().
UFUNCTION() [8/12]
UKismetNodeHelperLibrary::UFUNCTION () const private
Parameters
Enum - Enumeration
EnumeratorIndex - Input index
Returns
- The value of the enumerator, or INDEX_NONE
References meta, and UFUNCTION().
UFUNCTION() [9/12]
UKismetNodeHelperLibrary::UFUNCTION () const private
Parameters
Enum - Enumeration
EnumeratorIndex - Input value
Returns
- if EnumeratorIndex is valid return EnumeratorIndex, otherwise return MAX value of Enum
References Enum, EnumeratorValue, meta, and UFUNCTION().
UFUNCTION() [10/12]
UKismetNodeHelperLibrary::UFUNCTION () & private
Clears all of the bit in the data.
Parameters
Data - The integer containing the bits that are being cleared
References meta, and UFUNCTION().
UFUNCTION() [11/12]
UKismetNodeHelperLibrary::UFUNCTION () & private
Clears the bit at index "Index" in the data.
Parameters
Data - The integer containing the bits that are being cleared
Index - The bit index into the Data that we are clearing
References Index, meta, and UFUNCTION().
UFUNCTION() [12/12]
UKismetNodeHelperLibrary::UFUNCTION () & private
Sets the bit at index "Index" in the data.
Parameters
Data - The integer containing the bits that are being set
Index - The bit index into the Data that we are setting
References Index, meta, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Field Documentation
bRandom
int32 int32 bool UKismetNodeHelperLibrary::bRandom private
Definition at line 88 of file KismetNodeHelperLibrary.h.
EnumeratorIndex
uint8 UKismetNodeHelperLibrary::EnumeratorIndex private
Definition at line 147 of file KismetNodeHelperLibrary.h.
EnumeratorValue
uint8 UKismetNodeHelperLibrary::EnumeratorValue private
Definition at line 121 of file KismetNodeHelperLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
Index
int32 UKismetNodeHelperLibrary::Index private
Definition at line 30 of file KismetNodeHelperLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
NumBits [1/2]
int32 int32 UKismetNodeHelperLibrary::NumBits private
Definition at line 66 of file KismetNodeHelperLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
NumBits [2/2]
int32 int32 UKismetNodeHelperLibrary::NumBits private
Definition at line 88 of file KismetNodeHelperLibrary.h.
StartIdx
int32 UKismetNodeHelperLibrary::StartIdx private
Definition at line 88 of file KismetNodeHelperLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/KismetNodeHelperLibrary.h