Unreal Engine 5.6 C++ API: FGainMatrix Class Reference
FGainMatrix Class Reference
#include "GainMatrix.h"
Public Member Functions
FGainMatrix ()
FGainMatrix (const FGainMatrix &start, const FGainMatrix &end, float lerpPos)
FGainMatrix (EAudioBufferChannelLayout layout)
FGainMatrix (EAudioBufferChannelLayout layout, float InGain)
FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout)
FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout, float InGain)
FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout, uint32 InChannelMask)
FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout, uint32 InChannelMask, float InGain)
void ApplyAndAccumulateToBuffer (float *src, int32 InChannel, float *dest, int32 OutChannel, int32 InNumFrames) const
void ApplyToBuffer (float *src, int32 inChannel, float *dest, int32 outChannel, int32 numFrames, bool clear=false) const
void Configure (int32 InNumInChannels, const TAudioBuffer< float > &OutputBuffer)
void ConfigureForOutputBuffer (const TAudioBuffer< float > &OutputBuffer)
EAudioBufferChannelLayout GetChannelLayout () const
uint32 GetChannelMask () const
int32 GetNumInChannels () const
int32 GetNumOutChannels () const
FGainMatrix & Lerp (const FGainMatrix &start, const FGainMatrix &end, float lerpPos)
FGainMatrix operator* (const FGainMatrix &Other) const
FGainMatrix operator* (const float &m) const
FGainMatrix & operator*= (float gain)
FGainMatrix & operator= (float gain)
FChannelGains & operator[] (int32 index)
const FChannelGains & operator[] (int32 index) const
void PanSample (float sample, int32 InChannel, float *out, int32 InNumOutChannels)
HARMONIXDSP_API void Set (float InGain, const FPannerDetails &InPannerDetails, const FGainTable *InGainTable=nullptr)
HARMONIXDSP_API void Set (float InGain, ESpeakerChannelAssignment InChannelAssignment, const FGainTable *InGainTable=nullptr)
HARMONIXDSP_API void Set (float InGain, float InPanValue, const FGainTable *InGainTable=nullptr)
FGainMatrix & Set (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout layout, uint32 InChannelMask, float InGain)
HARMONIXDSP_API void SetFromLegacyStereo (float InGain, float InPan)
HARMONIXDSP_API void SetFromMinusOneToOneSurroundPan (float InGain, float InPan, const FGainTable *InGainTable=nullptr)
HARMONIXDSP_API void SetFromNewStereo (float InGain, float InPan, float InMax, const FGainTable *InGainTable=nullptr)
HARMONIXDSP_API void SetFromPolarDegrees (float InGain, float InPan, const FGainTable *InGainTable=nullptr)
Static Public Member Functions
static HARMONIXDSP_API void Init ()
static HARMONIXDSP_API bool SpeakerChannelAssignmentMapsToOneSpeaker (ESpeakerChannelAssignment InChannelrAssignment, EAudioBufferChannelLayout InChannelLayout)
static HARMONIXDSP_API int32 SpeakerChannelAssignmentToChannelIndex (ESpeakerChannelAssignment InChannelAssignment, EAudioBufferChannelLayout InChannelLayout)
static const FGainMatrix & Unity ()
Static Private Member Functions
static int32 SpeakerToFive (ESpeakerChannelAssignment InChannelAssignment)
static int32 SpeakerToFivePointOne (ESpeakerChannelAssignment InChannelAssignment)
static int32 SpeakerToQuad (ESpeakerChannelAssignment InChannelAssignment)
static int32 SpeakerToQuadPointOne (ESpeakerChannelAssignment InChannelAssignment)
static int32 SpeakerToSevenPointOne (ESpeakerChannelAssignment InChannelAssignment)
static int32 SpeakerToStereo (ESpeakerChannelAssignment InChannelAssignment)
static int32 SpeakerToStereoPointOne (ESpeakerChannelAssignment InChannelAssignment)
Private Attributes
EAudioBufferChannelLayout ChannelLayout = EAudioBufferChannelLayout::Raw
uint32 ChannelMask = ESpeakerMask::AllSpeakers
FChannelGains GainsArray [HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer] = {}
uint8 NumInChannels = HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer
uint8 NumOutChannels = HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer
Static Private Attributes
static HARMONIXDSP_API FGainMatrix * sUnity
Detailed Description
Definition at line 17 of file GainMatrix.h.
Constructor & Destructor Documentation
FGainMatrix() [1/8]
FGainMatrix::FGainMatrix () inline
Definition at line 23 of file GainMatrix.h.
References check, GainsArray, Raw, Set(), and ESpeakerMask::UnspecifiedMono.
Referenced by FGainMatrix(), Lerp(), operator*(), operator*(), operator*=(), operator=(), Set(), and Unity().
FGainMatrix() [2/8]
FGainMatrix::FGainMatrix (EAudioBufferChannelLayout layout) inline
Definition at line 29 of file GainMatrix.h.
References ChannelMask, check, and GainsArray.
FGainMatrix() [3/8]
FGainMatrix::FGainMatrix (EAudioBufferChannelLayout layout, float InGain) inline
Definition at line 34 of file GainMatrix.h.
References ESpeakerMask::AllSpeakers, check, GainsArray, HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer, and Set().
FGainMatrix() [4/8]
FGainMatrix::FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout) inline
Definition at line 41 of file GainMatrix.h.
References ESpeakerMask::AllSpeakers, check, GainsArray, and Set().
FGainMatrix() [5/8]
FGainMatrix::FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout, uint32 InChannelMask) inline
Definition at line 47 of file GainMatrix.h.
References check, GainsArray, and Set().
FGainMatrix() [6/8]
FGainMatrix::FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout, float InGain) inline
Definition at line 53 of file GainMatrix.h.
References ESpeakerMask::AllSpeakers, check, GainsArray, and Set().
FGainMatrix() [7/8]
FGainMatrix::FGainMatrix (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout InChannelLayout, uint32 InChannelMask, float InGain) inline
Definition at line 59 of file GainMatrix.h.
References check, GainsArray, and Set().
FGainMatrix() [8/8]
FGainMatrix::FGainMatrix (const FGainMatrix & start, const FGainMatrix & end, float lerpPos) inline
Definition at line 180 of file GainMatrix.h.
References FGainMatrix(), end(), and Lerp.
Member Function Documentation
ApplyAndAccumulateToBuffer()
void FGainMatrix::ApplyAndAccumulateToBuffer (float * src, int32 InChannel, float * dest, int32 OutChannel, int32 InNumFrames) const inline
Definition at line 125 of file GainMatrix.h.
References checkSlow, GainsArray, HarmonixDsp::kTinyGain, NumInChannels, NumOutChannels, VectorAdd(), VectorLoadAligned(), VectorMultiply(), VectorSetFloat1(), and VectorStoreAligned().
ApplyToBuffer()
void FGainMatrix::ApplyToBuffer (float * src, int32 inChannel, float * dest, int32 outChannel, int32 numFrames, bool clear = false) const inline
Definition at line 98 of file GainMatrix.h.
References checkSlow, GainsArray, HarmonixDsp::kTinyGain, FMemory::Memset(), NumInChannels, NumOutChannels, VectorLoadAligned(), VectorMultiply(), VectorSetFloat1(), and VectorStoreAligned().
Configure()
void FGainMatrix::Configure (int32 InNumInChannels, const TAudioBuffer< float > & OutputBuffer) inline
Definition at line 83 of file GainMatrix.h.
References ChannelLayout, ChannelMask, TAudioBuffer< DataType >::GetChannelLayout(), TAudioBuffer< DataType >::GetChannelMask(), TAudioBuffer< DataType >::GetNumValidChannels(), NumInChannels, and NumOutChannels.
ConfigureForOutputBuffer()
void FGainMatrix::ConfigureForOutputBuffer (const TAudioBuffer< float > & OutputBuffer) inline
Definition at line 91 of file GainMatrix.h.
References ChannelLayout, ChannelMask, TAudioBuffer< DataType >::GetChannelLayout(), TAudioBuffer< DataType >::GetChannelMask(), TAudioBuffer< DataType >::GetNumValidChannels(), and NumOutChannels.
GetChannelLayout()
EAudioBufferChannelLayout FGainMatrix::GetChannelLayout () const inline
Definition at line 68 of file GainMatrix.h.
References ChannelLayout.
GetChannelMask()
uint32 FGainMatrix::GetChannelMask () const inline
Definition at line 67 of file GainMatrix.h.
References ChannelMask.
GetNumInChannels()
int32 FGainMatrix::GetNumInChannels () const inline
Definition at line 65 of file GainMatrix.h.
References NumInChannels.
GetNumOutChannels()
int32 FGainMatrix::GetNumOutChannels () const inline
Definition at line 66 of file GainMatrix.h.
References NumOutChannels.
Init()
HARMONIXDSP_API void FGainMatrix::Init () static
Lerp()
FGainMatrix & FGainMatrix::Lerp (const FGainMatrix & start, const FGainMatrix & end, float lerpPos) inline
Definition at line 185 of file GainMatrix.h.
References FGainMatrix(), end(), GainsArray, NumInChannels, NumOutChannels, VectorAdd(), VectorMultiply(), and VectorSetFloat1().
operator*() [1/2]
FGainMatrix FGainMatrix::operator* (const FGainMatrix & Other) const inline
Definition at line 213 of file GainMatrix.h.
References FGainMatrix(), ChannelLayout, ChannelMask, GainsArray, NumInChannels, NumOutChannels, and Other.
operator*() [2/2]
FGainMatrix FGainMatrix::operator* (const float & m) const inline
Definition at line 228 of file GainMatrix.h.
References FGainMatrix(), GainsArray, NumInChannels, NumOutChannels, VectorMultiply(), and VectorSetFloat1().
operator*=()
FGainMatrix & FGainMatrix::operator*= (float gain) inline
Definition at line 250 of file GainMatrix.h.
References FGainMatrix(), GainsArray, NumInChannels, NumOutChannels, VectorMultiply(), and VectorSetFloat1().
operator=()
FGainMatrix & FGainMatrix::operator= (float gain) inline
Definition at line 271 of file GainMatrix.h.
References FGainMatrix(), GainsArray, NumInChannels, and VectorSetFloat1().
Referenced by Set().
operator[]() [1/2]
FChannelGains & FGainMatrix::operator[] (int32 index) inline
Definition at line 299 of file GainMatrix.h.
References checkSlow, GainsArray, and NumInChannels.
operator[]() [2/2]
const FChannelGains & FGainMatrix::operator[] (int32 index) const inline
Definition at line 293 of file GainMatrix.h.
References checkSlow, GainsArray, and NumInChannels.
PanSample()
void FGainMatrix::PanSample (float sample, int32 InChannel, float * out, int32 InNumOutChannels) inline
Definition at line 152 of file GainMatrix.h.
References checkSlow, GainsArray, HarmonixDsp::kTinyGain, and NumOutChannels.
Set() [1/4]
HARMONIXDSP_API void FGainMatrix::Set (float InGain, const FPannerDetails & InPannerDetails, const FGainTable * InGainTable = nullptr)
Set() [2/4]
HARMONIXDSP_API void FGainMatrix::Set (float InGain, ESpeakerChannelAssignment InChannelAssignment, const FGainTable * InGainTable = nullptr)
Set() [3/4]
HARMONIXDSP_API void FGainMatrix::Set (float InGain, float InPanValue, const FGainTable * InGainTable = nullptr)
Referenced by FGainMatrix(), FGainMatrix(), FGainMatrix(), FGainMatrix(), FGainMatrix(), and FGainMatrix().
Set() [4/4]
FGainMatrix & FGainMatrix::Set (int32 InNumInChannels, int32 InNumOutChannels, EAudioBufferChannelLayout layout, uint32 InChannelMask, float InGain) inline
Definition at line 166 of file GainMatrix.h.
References FGainMatrix(), ChannelLayout, ChannelMask, GainsArray, NumInChannels, NumOutChannels, and operator=().
SetFromLegacyStereo()
HARMONIXDSP_API void FGainMatrix::SetFromLegacyStereo (float InGain, float InPan)
SetFromMinusOneToOneSurroundPan()
HARMONIXDSP_API void FGainMatrix::SetFromMinusOneToOneSurroundPan (float InGain, float InPan, const FGainTable * InGainTable = nullptr)
SetFromNewStereo()
HARMONIXDSP_API void FGainMatrix::SetFromNewStereo (float InGain, float InPan, float InMax, const FGainTable * InGainTable = nullptr)
SetFromPolarDegrees()
HARMONIXDSP_API void FGainMatrix::SetFromPolarDegrees (float InGain, float InPan, const FGainTable * InGainTable = nullptr)
SpeakerChannelAssignmentMapsToOneSpeaker()
HARMONIXDSP_API bool FGainMatrix::SpeakerChannelAssignmentMapsToOneSpeaker (ESpeakerChannelAssignment InChannelrAssignment, EAudioBufferChannelLayout InChannelLayout) static
SpeakerChannelAssignmentToChannelIndex()
HARMONIXDSP_API int32 FGainMatrix::SpeakerChannelAssignmentToChannelIndex (ESpeakerChannelAssignment InChannelAssignment, EAudioBufferChannelLayout InChannelLayout) static
SpeakerToFive()
int32 FGainMatrix::SpeakerToFive (ESpeakerChannelAssignment InChannelAssignment) static private
SpeakerToFivePointOne()
int32 FGainMatrix::SpeakerToFivePointOne (ESpeakerChannelAssignment InChannelAssignment) static private
SpeakerToQuad()
int32 FGainMatrix::SpeakerToQuad (ESpeakerChannelAssignment InChannelAssignment) static private
SpeakerToQuadPointOne()
int32 FGainMatrix::SpeakerToQuadPointOne (ESpeakerChannelAssignment InChannelAssignment) static private
SpeakerToSevenPointOne()
int32 FGainMatrix::SpeakerToSevenPointOne (ESpeakerChannelAssignment InChannelAssignment) static private
SpeakerToStereo()
int32 FGainMatrix::SpeakerToStereo (ESpeakerChannelAssignment InChannelAssignment) static private
SpeakerToStereoPointOne()
int32 FGainMatrix::SpeakerToStereoPointOne (ESpeakerChannelAssignment InChannelAssignment) static private
Unity()
const FGainMatrix & FGainMatrix::Unity () inline static
Definition at line 81 of file GainMatrix.h.
References FGainMatrix(), and sUnity.
Field Documentation
ChannelLayout
EAudioBufferChannelLayout FGainMatrix::ChannelLayout = EAudioBufferChannelLayout::Raw private
Definition at line 317 of file GainMatrix.h.
Referenced by Configure(), ConfigureForOutputBuffer(), GetChannelLayout(), operator*(), and Set().
ChannelMask
uint32 FGainMatrix::ChannelMask = ESpeakerMask::AllSpeakers private
Definition at line 319 of file GainMatrix.h.
Referenced by FGainMatrix(), Configure(), ConfigureForOutputBuffer(), GetChannelMask(), operator*(), and Set().
GainsArray
FChannelGains FGainMatrix::GainsArray[HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer] = {} private
Definition at line 310 of file GainMatrix.h.
Referenced by FGainMatrix(), FGainMatrix(), FGainMatrix(), FGainMatrix(), FGainMatrix(), FGainMatrix(), FGainMatrix(), ApplyAndAccumulateToBuffer(), ApplyToBuffer(), Lerp(), operator*(), operator*(), operator*=(), operator=(), operator[](), operator[](), PanSample(), and Set().
NumInChannels
uint8 FGainMatrix::NumInChannels = HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer private
Definition at line 314 of file GainMatrix.h.
Referenced by ApplyAndAccumulateToBuffer(), ApplyToBuffer(), Configure(), GetNumInChannels(), Lerp(), operator*(), operator*(), operator*=(), operator=(), operator[](), operator[](), and Set().
NumOutChannels
uint8 FGainMatrix::NumOutChannels = HarmonixDsp::FAudioBuffer::kMaxChannelsInAudioBuffer private
Definition at line 315 of file GainMatrix.h.
Referenced by ApplyAndAccumulateToBuffer(), ApplyToBuffer(), Configure(), ConfigureForOutputBuffer(), GetNumOutChannels(), Lerp(), operator*(), operator*(), operator*=(), PanSample(), and Set().
sUnity
HARMONIXDSP_API FGainMatrix* FGainMatrix::sUnity static private
Definition at line 312 of file GainMatrix.h.
Referenced by Unity().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixDsp/Public/HarmonixDsp/GainMatrix.h