Unreal Engine 5.6 C++ API: SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn Class Reference
SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn Class Reference
Describes a single column.
#include "SMediaPermutationsSelector.h"
Public Member Functions
SLATE_ARGUMENT (FName, ColumnName) SLATE_ATTRIBUTE(FText
A unique ID for this property, so that it can be saved and restored.
Label SLATE_ATTRIBUTE (FText, Tooltip) SLATE_EVENT(FIsColumnVisible
Text to use as the Column tooltip.
SLATE_BEGIN_ARGS (FColumn)
Label IsColumnVisible SLATE_END_ARGS () FColumn(const FArguments &InArgs)
Data Fields
FName ColumnName
A unique ID for this property, so that it can be saved and restored.
FIsColumnVisible IsColumnVisible
Delegate to invoke when build the column and check the visibility.
TAttribute< FText > Label
Text to use as the Column header.
TAttribute< FText > Tooltip
Text to use as the Column tooltip.
TSharedPtr< SWidget > Widget
Widget created by this menu.
Detailed Description
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>>
class SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn
Describes a single column.
Definition at line 87 of file SMediaPermutationsSelector.h.
Member Function Documentation
SLATE_ARGUMENT()
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::SLATE_ARGUMENT (FName , ColumnName)
A unique ID for this property, so that it can be saved and restored.
Text to use as the Column header.
References ColumnName, and Label.
SLATE_ATTRIBUTE()
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> Label SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::SLATE_ATTRIBUTE (FText , Tooltip)
Text to use as the Column tooltip.
Delegate to invoke when build the column and check the visibility.
References IsColumnVisible, SLATE_ATTRIBUTE(), SMediaPermutationsSelector< ItemType, ItemBuilder >::SLATE_EVENT(), and Tooltip.
Referenced by SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::SLATE_BEGIN_ARGS (FColumn) inline
Definition at line 90 of file SMediaPermutationsSelector.h.
SLATE_END_ARGS()
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> Label IsColumnVisible SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::SLATE_END_ARGS () const & inline
Definition at line 101 of file SMediaPermutationsSelector.h.
References ColumnName, IsColumnVisible, Label, SLATE_END_ARGS(), and Tooltip.
Referenced by SLATE_END_ARGS().
Field Documentation
ColumnName
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> FName SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::ColumnName
A unique ID for this property, so that it can be saved and restored.
Definition at line 112 of file SMediaPermutationsSelector.h.
Referenced by SLATE_ARGUMENT(), and SLATE_END_ARGS().
IsColumnVisible
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> FIsColumnVisible SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::IsColumnVisible
Delegate to invoke when build the column and check the visibility.
Definition at line 124 of file SMediaPermutationsSelector.h.
Referenced by SLATE_ATTRIBUTE(), and SLATE_END_ARGS().
Label
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> TAttribute< FText > SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::Label
Text to use as the Column header.
Definition at line 115 of file SMediaPermutationsSelector.h.
Referenced by SLATE_ARGUMENT(), and SLATE_END_ARGS().
Tooltip
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> TAttribute< FText > SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::Tooltip
Text to use as the Column tooltip.
Definition at line 118 of file SMediaPermutationsSelector.h.
Referenced by SLATE_ATTRIBUTE(), and SLATE_END_ARGS().
Widget
template<typename ItemType, typename ItemBuilder = TMediaPermutationsSelectorBuilder<ItemType>> TSharedPtr< SWidget > SMediaPermutationsSelector< ItemType, ItemBuilder >::FColumn::Widget
Widget created by this menu.
Definition at line 121 of file SMediaPermutationsSelector.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaIOFramework/Source/MediaIOEditor/Public/Widgets/SMediaPermutationsSelector.h