Unreal Engine 5.6 C++ API: FSceneInterface Class Reference
FSceneInterface Class Reference abstract
An interface to the private scene manager implementation of a scene.
#include "SceneInterface.h"
Data Structures
struct FCustomRenderPassRendererInput
Contains settings used to construct scene view for custom render pass during the renderer construction.
Public Member Functions
FSceneInterface (ERHIFeatureLevel::Type InFeatureLevel)
virtual bool AddCustomRenderPass (const FSceneViewFamily *ViewFamily, const FCustomRenderPassRendererInput &CustomRenderPassInput)
Enqueues a new custom render pass to execute the next time this scene is rendered by ANY scene renderer.
virtual void AddDecal (UDecalComponent *Component)=0
Adds a new decal component to the scene.
virtual void AddExponentialHeightFog (uint64 Id, const FExponentialHeightFogDynamicState &State)=0
Adds a new exponential height fog component to the scene.
virtual void AddHairStrands (FHairStrandsInstance *Proxy)=0
Adds a hair strands proxy to the scene.
virtual void AddInvisibleLight (ULightComponent *Light)=0
Adds a new light component to the scene which is currently invisible, but needed for editor previewing.
virtual void AddLight (ULightComponent *Light)=0
Adds a new light component to the scene.
virtual void AddLocalFogVolume (class FLocalFogVolumeSceneProxy *FogProxy)=0
Adds a new local height fog component to the scene.
virtual void AddLumenSceneCard (class ULumenSceneCardComponent *LumenSceneCardComponent)
virtual bool AddPixelInspectorRequest (class FPixelInspectorRequest *PixelInspectorRequest)
Add a pixel inspector request.
virtual void AddPlanarReflection (class UPlanarReflectionComponent *Component)
virtual void AddPrecomputedLightVolume (const class FPrecomputedLightVolume *Volume)
virtual void AddPrecomputedVolumetricLightmap (const class FPrecomputedVolumetricLightmap *Volume, bool bIsPersistentLevel)
virtual void AddPrimitive (FPrimitiveSceneDesc *Primitive)=0
virtual void AddPrimitive (UPrimitiveComponent *Primitive)=0
Adds a new primitive component to the scene.
virtual void AddReflectionCapture (class UReflectionCaptureComponent *Component)
Adds a reflection capture to the scene.
virtual void AddRuntimeVirtualTexture (URuntimeVirtualTextureComponent *Component)
Add a runtime virtual texture object to the scene.
virtual void AddSkyAtmosphere (FSkyAtmosphereSceneProxy *SkyAtmosphereSceneProxy, bool bStaticLightingBuilt)=0
Adds the unique volumetric cloud component to the scene.
virtual void AddSparseVolumeTextureViewer (FSparseVolumeTextureViewerSceneProxy *SVTV)=0
virtual void AddSpeedTreeWind (class FVertexFactory *VertexFactory, const class UStaticMesh *StaticMesh)=0
Adds a SpeedTree wind computation object to the scene.
virtual void AddVolumetricCloud (FVolumetricCloudSceneProxy *VolumetricCloudSceneProxy)=0
Adds the unique volumetric cloud component to the scene.
virtual void AddWindSource (class UWindDirectionalSourceComponent *WindComponent)=0
Adds a wind source component to the scene.
virtual void AllocateReflectionCaptures (const TArray< UReflectionCaptureComponent * > &NewCaptures, const TCHAR *CaptureReason, bool bVerifyOnlyCapturing, bool bCapturingForMobile, bool bInsideTick)
Allocates reflection captures in the scene's reflection cubemap array and updates them by recapturing the scene.
virtual void ApplyWorldOffset (const FVector &InOffset)
Shifts scene data by provided delta Called on world origin changes.
virtual void BatchAddPrimitives (TArrayView< FPrimitiveSceneDesc * > InPrimitives)=0
virtual void BatchAddPrimitives (TArrayView< UPrimitiveComponent * > InPrimitives)=0
Batched versions of Add / Remove / ReleasePrimitive, for improved CPU performance.
virtual void BatchReleasePrimitives (TArrayView< FPrimitiveSceneDesc * > InPrimitives)=0
virtual void BatchReleasePrimitives (TArrayView< UPrimitiveComponent * > InPrimitives)=0
virtual void BatchRemovePrimitives (TArray< FPrimitiveSceneProxy * > &&InPrimitives)=0
virtual void BatchRemovePrimitives (TArrayView< FPrimitiveSceneDesc * > InPrimitives)=0
virtual void BatchRemovePrimitives (TArrayView< UPrimitiveComponent * > InPrimitives)=0
virtual void BatchUpdateDecals (TArray< FDeferredDecalUpdateParams > &&UpdateParams)=0
virtual void DisableSkyLight (FSkyLightSceneProxy *Light)=0
virtual void DumpUnbuiltLightInteractions (FOutputDevice &Ar) const
virtual void EndFrame (FRHICommandListImmediate &RHICmdList)
virtual void Export (FArchive &Ar) const
Exports the scene.
virtual void FinishUpdatePrimitiveTransform ()=0
virtual void GetComputeTaskWorkers (TArray< class IComputeTaskWorker * > &OutWorkers) const
Gets the compute work scheduler objects associated with the scene.
virtual void GetDirectionalWindParameters (FVector &OutDirection, float &OutSpeed, float &OutMinGustAmt, float &OutMaxGustAmt) const =0
Same as GetWindParameters, but ignores point wind sources.
ERHIFeatureLevel::Type GetFeatureLevel () const
virtual uint32 GetFrameNumber () const
virtual class FFXSystemInterface * GetFXSystem ()=0
Get the FX system associated with the scene.
virtual class FGPUSkinCache * GetGPUSkinCache ()
Gets the GPU Skin Cache system associated with the scene.
virtual void GetLightIESAtlasSlot (const FLightSceneProxy *Proxy, FLightRenderParameters *Out)=0
Return the IES profile index corresponding to the local light proxy.
virtual bool GetPreviousLocalToWorld (const FPrimitiveSceneInfo *PrimitiveSceneInfo, FMatrix &OutPreviousLocalToWorld) const
Get the primitive previous local to world (used for motion blur).
virtual FPrimitiveSceneInfo * GetPrimitiveSceneInfo (const FPersistentPrimitiveIndex &PersistentPrimitiveIndex) const =0
virtual FPrimitiveSceneInfo * GetPrimitiveSceneInfo (FPrimitiveComponentId PrimitiveId) const =0
Finds the primitive with the associated component id.
virtual FPrimitiveSceneInfo * GetPrimitiveSceneInfo (int32 PrimitiveIndex) const =0
Finds the primitive with the associated index into the primitive array.
virtual TConstArrayView< FPrimitiveSceneProxy * > GetPrimitiveSceneProxies () const =0
virtual void GetRectLightAtlasSlot (const FRectLightSceneProxy *Proxy, FLightRenderParameters *Out)=0
Return the rect.
virtual void GetReflectionCaptureData (UReflectionCaptureComponent *Component, class FReflectionCaptureData &OutCaptureData)
Reads back reflection capture data from the GPU.
virtual void GetRelevantLights (UPrimitiveComponent *Primitive, TArray< const ULightComponent * > *RelevantLights) const =0
Retrieves the lights interacting with the passed in primitive and adds them to the out array.
virtual const FScene * GetRenderScene () const =0
virtual FScene * GetRenderScene ()=0
Return the scene to be used for rendering.
virtual void GetRuntimeVirtualTextureHidePrimitiveMask (uint8 &bHideMaskEditor, uint8 &bHideMaskGame) const
virtual TConstArrayView< FPrimitiveComponentId > GetScenePrimitiveComponentIds () const =0
Returns the FPrimitiveComponentId for all primitives in the scene.
EShaderPlatform GetShaderPlatform () const
EShadingPath GetShadingPath () const
virtual class FSkeletalMeshUpdater * GetSkeletalMeshUpdater ()
virtual const FSkyAtmosphereRenderSceneInfo * GetSkyAtmosphereSceneInfo () const =0
virtual FSkyAtmosphereRenderSceneInfo * GetSkyAtmosphereSceneInfo ()=0
Returns the scene's unique info if it exists.
virtual FRHIUniformBuffer * GetSpeedTreeUniformBuffer (const FVertexFactory *VertexFactory) const =0
Looks up the SpeedTree uniform buffer for the passed in vertex factory.
virtual const FVolumetricCloudRenderSceneInfo * GetVolumetricCloudSceneInfo () const =0
virtual void GetWindParameters (const FVector &Position, FVector &OutDirection, float &OutSpeed, float &OutMinGustAmt, float &OutMaxGustAmt) const =0
Accesses wind parameters.
virtual void GetWindParameters_GameThread (const FVector &Position, FVector &OutDirection, float &OutSpeed, float &OutMinGustAmt, float &OutMaxGustAmt) const =0
Accesses wind parameters safely for game thread applications.
virtual const TArray< class FWindSourceSceneProxy * > & GetWindSources_RenderThread () const =0
Accesses the wind source list.
virtual class UWorld * GetWorld () const =0
Get the optional UWorld that is associated with this scene.
virtual bool HasAnyExponentialHeightFog () const =0
virtual bool HasAnyLights () const =0
virtual bool HasAnyLocalFogVolume () const =0
virtual bool HasAtmosphereLightRequiringLightingBuild () const =0
virtual bool HasPrecomputedVolumetricLightmap_RenderThread () const
virtual bool HasSkyLightRequiringLightingBuild () const =0
virtual void IncrementFrameNumber ()
virtual bool InitializePixelInspector (FRenderTarget *BufferFinalColor, FRenderTarget *BufferSceneColor, FRenderTarget *BufferDepth, FRenderTarget *BufferHDR, FRenderTarget *BufferA, FRenderTarget *BufferBCDEF, int32 BufferIndex)
Initialize the pixel inspector buffers.
virtual void InvalidateRuntimeVirtualTexture (URuntimeVirtualTextureComponent *Component, FBoxSphereBounds const &WorldBounds, EVTInvalidatePriority InvalidatePriority)
Invalidates pages in a runtime virtual texture object.
virtual bool IsEditorScene () const
virtual void OnLevelAddedToWorld (const FName &InLevelName, UWorld *InWorld, bool bIsLightingScenario)
Notification that level was added to a world.
virtual void OnLevelRemovedFromWorld (const FName &InLevelName, UWorld *InWorld, bool bIsLightingScenario)
virtual void OnWorldCleanup ()
virtual void RefreshNaniteRasterBins (FPrimitiveSceneInfo &PrimitiveSceneInfo)
virtual TArray< FAnimBankRecordHandle > RegisterAnimBank (const TConstArrayView< FAnimBankDesc > Descs)=0
virtual void Release ()=0
Release this scene and remove it from the rendering thread.
virtual void ReleasePrimitive (FPrimitiveSceneDesc *Primitive)=0
virtual void ReleasePrimitive (UPrimitiveComponent *Primitive)=0
Called when a primitive is being unregistered and will not be immediately re-registered.
virtual void ReleaseReflectionCubemap (UReflectionCaptureComponent *CaptureComponent)
virtual void ReloadNaniteFixedFunctionBins ()
virtual void RemoveDecal (UDecalComponent *Component)=0
Removes a decal component from the scene.
virtual void RemoveExponentialHeightFog (uint64 Id)=0
Removes a exponential height fog component from the scene.
virtual void RemoveHairStrands (FHairStrandsInstance *Proxy)=0
Removes a hair strands proxy to the scene.
virtual void RemoveLight (ULightComponent *Light)=0
Removes a light component from the scene.
virtual void RemoveLocalFogVolume (class FLocalFogVolumeSceneProxy *FogProxy)=0
Removes a local height fog component from the scene.
virtual void RemoveLumenSceneCard (class ULumenSceneCardComponent *LumenSceneCardComponent)
virtual void RemovePlanarReflection (class UPlanarReflectionComponent *Component)
virtual void RemovePrecomputedLightVolume (const class FPrecomputedLightVolume *Volume)
virtual void RemovePrecomputedVolumetricLightmap (const class FPrecomputedVolumetricLightmap *Volume)
virtual void RemovePrimitive (FPrimitiveSceneDesc *Primitive)=0
virtual void RemovePrimitive (UPrimitiveComponent *Primitive)=0
Removes a primitive component from the scene.
virtual void RemoveReflectionCapture (class UReflectionCaptureComponent *Component)
Removes a reflection capture from the scene.
virtual void RemoveRuntimeVirtualTexture (URuntimeVirtualTextureComponent *Component)
Removes a runtime virtual texture object from the scene.
virtual void RemoveSkyAtmosphere (FSkyAtmosphereSceneProxy *SkyAtmosphereSceneProxy)=0
Removes the unique volumetric cloud component to the scene.
virtual void RemoveSparseVolumeTextureViewer (FSparseVolumeTextureViewerSceneProxy *SVTV)=0
virtual void RemoveSpeedTreeWind_RenderThread (class FVertexFactory *VertexFactory, const class UStaticMesh *StaticMesh)=0
Removes a SpeedTree wind computation object to the scene.
virtual void RemoveVolumetricCloud (FVolumetricCloudSceneProxy *VolumetricCloudSceneProxy)=0
Removes the unique volumetric cloud component to the scene.
virtual void RemoveWindSource (class UWindDirectionalSourceComponent *WindComponent)=0
Removes a wind source component from the scene.
virtual bool RequestGPUSceneUpdate (FPrimitiveSceneInfo &PrimitiveSceneInfo, EPrimitiveDirtyState PrimitiveDirtyState)
virtual bool RequestUniformBufferUpdate (FPrimitiveSceneInfo &PrimitiveSceneInfo)
virtual bool RequiresHitProxies () const =0
Indicates if hit proxies should be processed by this scene.
virtual void ResetPhysicsField ()=0
Reset the physics field scene proxy.
virtual void ResetReflectionCaptures (bool bOnlyIfOOM)
Resets reflection capture data to allow it to be rebuilt from scratch.
virtual void SetFXSystem (class FFXSystemInterface *InFXSystem)=0
Sets the FX system associated with the scene.
virtual void SetPhysicsField (class FPhysicsFieldSceneProxy *PhysicsFieldSceneProxy)=0
Set the physics field scene proxy to the scene.
virtual void SetPrecomputedVisibility (const class FPrecomputedVisibilityHandler *PrecomputedVisibilityHandler)
Sets the precomputed visibility handler for the scene, or NULL to clear the current one.
virtual void SetPrecomputedVolumeDistanceField (const class FPrecomputedVolumeDistanceField *PrecomputedVolumeDistanceField)
Sets the precomputed volume distance field for the scene, or NULL to clear the current one.
virtual void SetSkyLight (FSkyLightSceneProxy *Light)=0
virtual void ShowPhysicsField ()=0
Set the shader print/debug cvars to be able to show the fields.
virtual void StartFrame ()
virtual void StartUpdatePrimitiveTransform (int32 NumPrimitives)=0
UE_DEPRECATED (5.0, "This method has been refactored to use an FRDGBuilder instead.") virtual void UpdatePhysicsField(FRHICommandListImmediate &RHICmdList
UE_DEPRECATED (5.1, "This method now accepts a bInsideTick parameter, which specifies whether it's called during the frame Tick.") inline void AllocateReflectionCaptures(const TArray< UReflectionCaptureComponent * > &NewCaptures
UE_DEPRECATED (5.2, "AllocateAndCaptureFrameSkyEnvMap now takes an FRDGExternalAccessQueue") virtual void AllocateAndCaptureFrameSkyEnvMap(FRDGBuilder &GraphBuilder
UE_DEPRECATED (5.6, "FRayTracingDynamicGeometryCollection has been removed - all raytracing dynamic geometries are collected via the FRayTracingInstanceCollector during GetDynamicRayTracingInstances on the proxy.") virtual class FRayTracingDynamicGeometryCollection *GetRayTracingDynamicGeometryCollection()
UE_DEPRECATED (5.6, "FRayTracingSkinnedGeometryUpdateQueue has been removed - all raytracing dynamic geometries are collected via the FRayTracingInstanceCollector during GetDynamicRayTracingInstances on the proxy.") virtual class FRayTracingSkinnedGeometryUpdateQueue *GetRayTracingSkinnedGeometryUpdateQueue()
UE_DEPRECATED (5.6, "StaticMeshBounds is no longer a parameter of this interface, please update FPrimitiveSceneDesc version.") virtual void UpdatePrimitiveInstances(FInstancedStaticMeshSceneDesc *Primitive)=0
UE_DEPRECATED (5.6, "Use the alternate prototype with the Priority param") virtual void InvalidateRuntimeVirtualTexture(URuntimeVirtualTextureComponent *Component
UE_EXPERIMENTAL (5.6, "Experimental API, scene writing delegate may be internalized in the future.") virtual void UpdatePrimitiveInstancesFromCompute(FPrimitiveSceneDesc *Primitive
virtual void UnregisterAnimBank (const TConstArrayView< FAnimBankRecordHandle > Handles)=0
virtual void UpdateAllPrimitiveSceneInfos (FRDGBuilder &GraphBuilder, EUpdateAllPrimitiveSceneInfosAsyncOps AsyncOps=EUpdateAllPrimitiveSceneInfosAsyncOps::None)=0
Updates all primitive scene info additions, remobals and translation changes.
void UpdateAllPrimitiveSceneInfos (FRHICommandListImmediate &RHICmdList)
virtual void UpdateCachedRayTracingState (class FPrimitiveSceneProxy *SceneProxy)
virtual void UpdateCachedRenderStates (class FPrimitiveSceneProxy *SceneProxy)
Update render states that possibly cached inside renderer, like mesh draw commands.
virtual void UpdateCustomPrimitiveData (FPrimitiveSceneDesc *Primitive, const FCustomPrimitiveData &CustomPrimitiveData)=0
virtual void UpdateCustomPrimitiveData (UPrimitiveComponent *Primitive)=0
Updates the custom primitive data of a primitive component which has already been added to the scene.
virtual void UpdateDecalFadeInTime (UDecalComponent *Component)=0
virtual void UpdateDecalFadeOutTime (UDecalComponent *Component)=0
virtual void UpdateDecalTransform (UDecalComponent *Component)=0
Updates the transform of a decal which has already been added to the scene.
virtual void UpdateEarlyZPassMode ()
virtual void UpdateInstanceCullDistance (UPrimitiveComponent *Primitive, float StartCullDistance, float EndCullDistance)=0
virtual void UpdateLightColorAndBrightness (ULightComponent *Light)=0
Updates the color and brightness of a light which has already been added to the scene.
virtual void UpdateLumenSceneCardTransform (class ULumenSceneCardComponent *LumenSceneCardComponent)
virtual void UpdateParameterCollections (const TArray< class FMaterialParameterCollectionInstanceResource * > &InParameterCollections)
Updates the scene's list of parameter collection id's and their uniform buffers.
virtual void UpdatePhysicsField (FRDGBuilder &GraphBuilder, FViewInfo &View)=0
Reset the physics field scene proxy.
virtual void UpdatePlanarReflectionContents (class UPlanarReflectionComponent *CaptureComponent, class FSceneRenderer &MainSceneRenderer, class ISceneRenderBuilder &SceneRenderBuilder)
virtual void UpdatePlanarReflectionTransform (UPlanarReflectionComponent *Component)
virtual void UpdatePrimitiveAttachment (UPrimitiveComponent *Primitive)=0
Updates primitive attachment state.
virtual void UpdatePrimitiveDistanceFieldSceneData_GameThread (UPrimitiveComponent *Primitive)
Updates distance field scene data (transforms, uv scale, self-shadow bias, etc.) but doesn't change allocation in the atlas.
virtual void UpdatePrimitiveDrawDistance (UPrimitiveComponent *Primitive, float MinDrawDistance, float MaxDrawDistance, float VirtualTextureMaxDrawDistance)=0
virtual void UpdatePrimitiveInstances (FPrimitiveSceneDesc *Primitive)=0
virtual void UpdatePrimitiveInstances (UPrimitiveComponent *Primitive)=0
Call to notify that an instace proxy update has been queued for the primitive.
virtual void UpdatePrimitiveOcclusionBoundsSlack (UPrimitiveComponent *Primitive, float NewSlack)=0
virtual void UpdatePrimitivesDrawnInGame_RenderThread (TArrayView< FPrimitiveSceneProxy * > PrimitiveSceneProxies, bool bDrawnInGame)=0
virtual void UpdatePrimitiveSelectedState_RenderThread (const FPrimitiveSceneInfo *PrimitiveSceneInfo, bool bIsSelected)
Updates the selected state values that might be cached inside the renderer.
virtual void UpdatePrimitiveTransform (FPrimitiveSceneDesc *Primitive)=0
virtual void UpdatePrimitiveTransform (UPrimitiveComponent *Primitive)=0
Updates the transform of a primitive which has already been added to the scene.
virtual void UpdatePrimitiveVelocityState_RenderThread (FPrimitiveSceneInfo *PrimitiveSceneInfo, bool bIsBeingMoved)
Updates the velocity state values that might be cached inside the renderer.
virtual void UpdateReflectionCaptureTransform (class UReflectionCaptureComponent *Component)
Updates a reflection capture's transform, and then re-captures the scene.
virtual void UpdateSceneCaptureContents (class USceneCaptureComponent2D *CaptureComponent, class ISceneRenderBuilder &SceneRenderBuilder)
Updates the contents of the given scene capture by rendering the scene.
virtual void UpdateSceneCaptureContents (class USceneCaptureComponentCube *CaptureComponent, class ISceneRenderBuilder &SceneRenderBuilder)
virtual void UpdateSceneSettings (AWorldSettings *WorldSettings)
virtual void UpdateSkyCaptureContents (const USkyLightComponent *CaptureComponent, bool bCaptureEmissiveOnly, UTextureCube *SourceCubemap, FTexture *OutProcessedTexture, float &OutAverageBrightness, FSHVectorRGB3 &OutIrradianceEnvironmentMap, TArray< FFloat16Color > *OutRadianceMap, FLinearColor *SpecifiedCubemapColorScale)
Updates the contents of the given sky capture by rendering the scene.
virtual void UpdateSpeedTreeWind (double CurrentTime)=0
Ticks the SpeedTree wind object and updates the uniform buffer.
virtual void UpdateStaticDrawLists ()
Updates all static draw lists.
virtual void UpdateWindSource (class UWindDirectionalSourceComponent *WindComponent)=0
Update a wind source component from the scene.
Static Public Member Functions
static EShadingPath GetShadingPath (ERHIFeatureLevel::Type InFeatureLevel)
Data Fields
const TCHAR bool bool bCapturingForMobile
FSceneRenderer FViewInfo bool bShouldRenderSkyAtmosphere
FSceneRenderer FViewInfo bool bool bShouldRenderVolumetricCloud
const TCHAR bool bVerifyOnlyCapturing
const TCHAR * CaptureReason
FGPUSceneWriteDelegate && DataWriterGPU = 0
FSceneRenderer FViewInfo bool bool FInstanceCullingManager & InstanceCullingManager
FSceneRenderer FViewInfo & MainView
FSceneRenderer & SceneRenderer
FViewInfo & View
FBoxSphereBounds const & WorldBounds
Protected Member Functions
virtual ~FSceneInterface ()
Protected Attributes
ERHIFeatureLevel::Type FeatureLevel
This scene's feature level.
Friends
class FSceneViewStateReference
Detailed Description
An interface to the private scene manager implementation of a scene.
Use GetRendererModule().AllocateScene to create. The scene
Definition at line 105 of file SceneInterface.h.
Constructor & Destructor Documentation
FSceneInterface()
FSceneInterface::FSceneInterface (ERHIFeatureLevel::Type InFeatureLevel)
~FSceneInterface()
virtual FSceneInterface::~FSceneInterface () inline protected virtual
Definition at line 756 of file SceneInterface.h.
Member Function Documentation
AddCustomRenderPass()
virtual bool FSceneInterface::AddCustomRenderPass (const FSceneViewFamily * ViewFamily, const FCustomRenderPassRendererInput & CustomRenderPassInput) inline virtual
Enqueues a new custom render pass to execute the next time this scene is rendered by ANY scene renderer.
It will be immediately removed from the scene afterwards.
Definition at line 753 of file SceneInterface.h.
AddDecal()
virtual void FSceneInterface::AddDecal (UDecalComponent * Component) pure virtual
Adds a new decal component to the scene.
Parameters
Component - component to add
References Component.
AddExponentialHeightFog()
virtual void FSceneInterface::AddExponentialHeightFog (uint64 Id, const FExponentialHeightFogDynamicState & State) pure virtual
Adds a new exponential height fog component to the scene.
Parameters
FogComponent - fog component to add
References State.
AddHairStrands()
virtual void FSceneInterface::AddHairStrands (FHairStrandsInstance * Proxy) pure virtual
Adds a hair strands proxy to the scene.
Parameters
Proxy - the hair strands proxy
AddInvisibleLight()
virtual void FSceneInterface::AddInvisibleLight (ULightComponent * Light) pure virtual
Adds a new light component to the scene which is currently invisible, but needed for editor previewing.
Parameters
Light - light component to add
References Light.
AddLight()
virtual void FSceneInterface::AddLight (ULightComponent * Light) pure virtual
Adds a new light component to the scene.
Parameters
Light - light component to add
References Light.
AddLocalFogVolume()
virtual void FSceneInterface::AddLocalFogVolume (class FLocalFogVolumeSceneProxy * FogProxy) pure virtual
Adds a new local height fog component to the scene.
Parameters
FogProxy - fog proxy to add
AddLumenSceneCard()
virtual void FSceneInterface::AddLumenSceneCard (class ULumenSceneCardComponent * LumenSceneCardComponent) inline virtual
Definition at line 537 of file SceneInterface.h.
AddPixelInspectorRequest()
virtual bool FSceneInterface::AddPixelInspectorRequest (class FPixelInspectorRequest * PixelInspectorRequest) inline virtual
Add a pixel inspector request.
Returns
True if implemented false otherwise.
Definition at line 695 of file SceneInterface.h.
AddPlanarReflection()
virtual void FSceneInterface::AddPlanarReflection (class UPlanarReflectionComponent * Component) inline virtual
Definition at line 272 of file SceneInterface.h.
References AddPlanarReflection(), and Component.
Referenced by AddPlanarReflection().
AddPrecomputedLightVolume()
virtual void FSceneInterface::AddPrecomputedLightVolume (const class FPrecomputedLightVolume * Volume) inline virtual
Definition at line 284 of file SceneInterface.h.
References Volume.
AddPrecomputedVolumetricLightmap()
virtual void FSceneInterface::AddPrecomputedVolumetricLightmap (const class FPrecomputedVolumetricLightmap * Volume, bool bIsPersistentLevel) inline virtual
Definition at line 288 of file SceneInterface.h.
References Volume.
AddPrimitive() [1/2]
virtual void FSceneInterface::AddPrimitive (FPrimitiveSceneDesc * Primitive) pure virtual
AddPrimitive() [2/2]
virtual void FSceneInterface::AddPrimitive (UPrimitiveComponent * Primitive) pure virtual
Adds a new primitive component to the scene.
Parameters
Primitive - primitive component to add
Referenced by FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Execute().
AddReflectionCapture()
virtual void FSceneInterface::AddReflectionCapture (class UReflectionCaptureComponent * Component) inline virtual
Adds a reflection capture to the scene.
Definition at line 224 of file SceneInterface.h.
References Component.
AddRuntimeVirtualTexture()
virtual void FSceneInterface::AddRuntimeVirtualTexture (URuntimeVirtualTextureComponent * Component) inline virtual
Add a runtime virtual texture object to the scene.
Definition at line 292 of file SceneInterface.h.
References Component.
AddSkyAtmosphere()
virtual void FSceneInterface::AddSkyAtmosphere (FSkyAtmosphereSceneProxy * SkyAtmosphereSceneProxy, bool bStaticLightingBuilt) pure virtual
Adds the unique volumetric cloud component to the scene.
Parameters
SkyAtmosphereSceneProxy - the sky atmosphere proxy
AddSparseVolumeTextureViewer()
virtual void FSceneInterface::AddSparseVolumeTextureViewer (FSparseVolumeTextureViewerSceneProxy * SVTV) pure virtual
AddSpeedTreeWind()
virtual void FSceneInterface::AddSpeedTreeWind (class FVertexFactory * VertexFactory, const class UStaticMesh * StaticMesh) pure virtual
Adds a SpeedTree wind computation object to the scene.
Parameters
StaticMesh - The SpeedTree static mesh whose wind to add.
References StaticMesh, and VertexFactory.
AddVolumetricCloud()
virtual void FSceneInterface::AddVolumetricCloud (FVolumetricCloudSceneProxy * VolumetricCloudSceneProxy) pure virtual
Adds the unique volumetric cloud component to the scene.
Parameters
VolumetricCloudSceneProxy - the sky atmosphere proxy
AddWindSource()
virtual void FSceneInterface::AddWindSource (class UWindDirectionalSourceComponent * WindComponent) pure virtual
Adds a wind source component to the scene.
Parameters
WindComponent - The component to add.
AllocateReflectionCaptures()
virtual void FSceneInterface::AllocateReflectionCaptures (const TArray< UReflectionCaptureComponent * > & NewCaptures, const TCHAR * CaptureReason, bool bVerifyOnlyCapturing, bool bCapturingForMobile, bool bInsideTick) inline virtual
Allocates reflection captures in the scene's reflection cubemap array and updates them by recapturing the scene.
Existing captures will only be updated. Must be called from the game thread.
Definition at line 239 of file SceneInterface.h.
References bCapturingForMobile, bVerifyOnlyCapturing, and CaptureReason.
ApplyWorldOffset()
virtual void FSceneInterface::ApplyWorldOffset (const FVector & InOffset) inline virtual
Shifts scene data by provided delta Called on world origin changes.
Parameters
InOffset Delta to shift scene by
Definition at line 651 of file SceneInterface.h.
References FVector.
BatchAddPrimitives() [1/2]
virtual void FSceneInterface::BatchAddPrimitives (TArrayView< FPrimitiveSceneDesc * > InPrimitives) pure virtual
BatchAddPrimitives() [2/2]
virtual void FSceneInterface::BatchAddPrimitives (TArrayView< UPrimitiveComponent * > InPrimitives) pure virtual
Batched versions of Add / Remove / ReleasePrimitive, for improved CPU performance.
BatchReleasePrimitives() [1/2]
virtual void FSceneInterface::BatchReleasePrimitives (TArrayView< FPrimitiveSceneDesc * > InPrimitives) pure virtual
BatchReleasePrimitives() [2/2]
virtual void FSceneInterface::BatchReleasePrimitives (TArrayView< UPrimitiveComponent * > InPrimitives) pure virtual
BatchRemovePrimitives() [1/3]
virtual void FSceneInterface::BatchRemovePrimitives (TArray< FPrimitiveSceneProxy * > && InPrimitives) pure virtual
BatchRemovePrimitives() [2/3]
virtual void FSceneInterface::BatchRemovePrimitives (TArrayView< FPrimitiveSceneDesc * > InPrimitives) pure virtual
BatchRemovePrimitives() [3/3]
virtual void FSceneInterface::BatchRemovePrimitives (TArrayView< UPrimitiveComponent * > InPrimitives) pure virtual
BatchUpdateDecals()
virtual void FSceneInterface::BatchUpdateDecals (TArray< FDeferredDecalUpdateParams > && UpdateParams) pure virtual
DisableSkyLight()
virtual void FSceneInterface::DisableSkyLight (FSkyLightSceneProxy * Light) pure virtual
References Light.
DumpUnbuiltLightInteractions()
virtual void FSceneInterface::DumpUnbuiltLightInteractions (FOutputDevice & Ar) const inline virtual
Definition at line 632 of file SceneInterface.h.
References Ar.
EndFrame()
virtual void FSceneInterface::EndFrame (FRHICommandListImmediate & RHICmdList) inline virtual
Definition at line 709 of file SceneInterface.h.
Export()
virtual void FSceneInterface::Export (FArchive & Ar) const inline virtual
Exports the scene.
Parameters
Ar The Archive used for exporting.
Definition at line 642 of file SceneInterface.h.
References Ar.
FinishUpdatePrimitiveTransform()
virtual void FSceneInterface::FinishUpdatePrimitiveTransform () pure virtual
GetComputeTaskWorkers()
virtual void FSceneInterface::GetComputeTaskWorkers (TArray< class IComputeTaskWorker * > & OutWorkers) const inline virtual
Gets the compute work scheduler objects associated with the scene.
Definition at line 620 of file SceneInterface.h.
GetDirectionalWindParameters()
virtual void FSceneInterface::GetDirectionalWindParameters (FVector & OutDirection, float & OutSpeed, float & OutMinGustAmt, float & OutMaxGustAmt) const pure virtual
Same as GetWindParameters, but ignores point wind sources.
References FVector.
GetFeatureLevel()
ERHIFeatureLevel::Type FSceneInterface::GetFeatureLevel () const inline
Definition at line 670 of file SceneInterface.h.
References FeatureLevel.
Referenced by GetShadingPath().
GetFrameNumber()
virtual uint32 FSceneInterface::GetFrameNumber () const inline virtual
Definition at line 710 of file SceneInterface.h.
GetFXSystem()
virtual class FFXSystemInterface * FSceneInterface::GetFXSystem () pure virtual
Get the FX system associated with the scene.
GetGPUSkinCache()
virtual class FGPUSkinCache * FSceneInterface::GetGPUSkinCache () inline virtual
Gets the GPU Skin Cache system associated with the scene.
Definition at line 607 of file SceneInterface.h.
GetLightIESAtlasSlot()
virtual void FSceneInterface::GetLightIESAtlasSlot (const FLightSceneProxy * Proxy, FLightRenderParameters * Out) pure virtual
Return the IES profile index corresponding to the local light proxy.
Parameters
Proxy - the local light proxy
Out - the light parameters which will be filled with the IES profile index information
GetPreviousLocalToWorld()
virtual bool FSceneInterface::GetPreviousLocalToWorld (const FPrimitiveSceneInfo * PrimitiveSceneInfo, FMatrix & OutPreviousLocalToWorld) const inline virtual
Get the primitive previous local to world (used for motion blur).
Returns true if the matrix was set.
Definition at line 176 of file SceneInterface.h.
GetPrimitiveSceneInfo() [1/3]
virtual FPrimitiveSceneInfo * FSceneInterface::GetPrimitiveSceneInfo (const FPersistentPrimitiveIndex & PersistentPrimitiveIndex) const pure virtual
GetPrimitiveSceneInfo() [2/3]
virtual FPrimitiveSceneInfo * FSceneInterface::GetPrimitiveSceneInfo (FPrimitiveComponentId PrimitiveId) const pure virtual
Finds the primitive with the associated component id.
GetPrimitiveSceneInfo() [3/3]
virtual FPrimitiveSceneInfo * FSceneInterface::GetPrimitiveSceneInfo (int32 PrimitiveIndex) const pure virtual
Finds the primitive with the associated index into the primitive array.
GetPrimitiveSceneProxies()
virtual TConstArrayView< FPrimitiveSceneProxy * > FSceneInterface::GetPrimitiveSceneProxies () const pure virtual
GetRectLightAtlasSlot()
virtual void FSceneInterface::GetRectLightAtlasSlot (const FRectLightSceneProxy * Proxy, FLightRenderParameters * Out) pure virtual
Return the rect.
light atlas slot information corresponding to the rect light proxy
Parameters
Proxy - the rect light proxy
Out - the light parameters which will be filled with the rect light atlas information
GetReflectionCaptureData()
virtual void FSceneInterface::GetReflectionCaptureData (UReflectionCaptureComponent * Component, class FReflectionCaptureData & OutCaptureData) inline virtual
Reads back reflection capture data from the GPU.
Very slow operation that blocks the GPU and rendering thread many times.
Definition at line 230 of file SceneInterface.h.
References Component.
GetRelevantLights()
virtual void FSceneInterface::GetRelevantLights (UPrimitiveComponent * Primitive, TArray< const ULightComponent * > * RelevantLights) const pure virtual
Retrieves the lights interacting with the passed in primitive and adds them to the out array.
Parameters
Primitive Primitive to retrieve interacting lights for
RelevantLights [out] Array of lights interacting with primitive
References GetRelevantLights().
Referenced by GetRelevantLights().
GetRenderScene() [1/2]
virtual const FScene * FSceneInterface::GetRenderScene () const pure virtual
References GetRenderScene().
GetRenderScene() [2/2]
virtual FScene * FSceneInterface::GetRenderScene () pure virtual
Return the scene to be used for rendering.
Note that this can return null if rendering has been disabled!
References GetRenderScene().
Referenced by GetRenderScene(), and GetRenderScene().
GetRuntimeVirtualTextureHidePrimitiveMask()
virtual void FSceneInterface::GetRuntimeVirtualTextureHidePrimitiveMask (uint8 & bHideMaskEditor, uint8 & bHideMaskGame) const inline virtual
Definition at line 296 of file SceneInterface.h.
GetScenePrimitiveComponentIds()
virtual TConstArrayView< FPrimitiveComponentId > FSceneInterface::GetScenePrimitiveComponentIds () const pure virtual
Returns the FPrimitiveComponentId for all primitives in the scene.
GetShaderPlatform()
EShaderPlatform FSceneInterface::GetShaderPlatform () const
GetShadingPath() [1/2]
EShadingPath FSceneInterface::GetShadingPath () const inline
Definition at line 676 of file SceneInterface.h.
References GetFeatureLevel(), and GetShadingPath().
Referenced by GetShadingPath().
GetShadingPath() [2/2]
EShadingPath FSceneInterface::GetShadingPath (ERHIFeatureLevel::Type InFeatureLevel) static
GetSkeletalMeshUpdater()
virtual class FSkeletalMeshUpdater * FSceneInterface::GetSkeletalMeshUpdater () inline virtual
Definition at line 612 of file SceneInterface.h.
GetSkyAtmosphereSceneInfo() [1/2]
virtual const FSkyAtmosphereRenderSceneInfo * FSceneInterface::GetSkyAtmosphereSceneInfo () const pure virtual
GetSkyAtmosphereSceneInfo() [2/2]
virtual FSkyAtmosphereRenderSceneInfo * FSceneInterface::GetSkyAtmosphereSceneInfo () pure virtual
Returns the scene's unique info if it exists.
GetSpeedTreeUniformBuffer()
virtual FRHIUniformBuffer * FSceneInterface::GetSpeedTreeUniformBuffer (const FVertexFactory * VertexFactory) const pure virtual
Looks up the SpeedTree uniform buffer for the passed in vertex factory.
Parameters
VertexFactory - The vertex factory registered for SpeedTree.
References VertexFactory.
GetVolumetricCloudSceneInfo()
virtual const FVolumetricCloudRenderSceneInfo * FSceneInterface::GetVolumetricCloudSceneInfo () const pure virtual
GetWindParameters()
virtual void FSceneInterface::GetWindParameters (const FVector & Position, FVector & OutDirection, float & OutSpeed, float & OutMinGustAmt, float & OutMaxGustAmt) const pure virtual
Accesses wind parameters.
XYZ will contain wind direction * Strength, W contains wind speed.
References FVector, and Position.
GetWindParameters_GameThread()
virtual void FSceneInterface::GetWindParameters_GameThread (const FVector & Position, FVector & OutDirection, float & OutSpeed, float & OutMinGustAmt, float & OutMaxGustAmt) const pure virtual
Accesses wind parameters safely for game thread applications.
References FVector, and Position.
GetWindSources_RenderThread()
virtual const TArray< class FWindSourceSceneProxy * > & FSceneInterface::GetWindSources_RenderThread () const pure virtual
Accesses the wind source list.
Must be called in the rendering thread.
Returns
The list of wind sources in the scene.
GetWorld()
virtual class UWorld * FSceneInterface::GetWorld () const pure virtual
Get the optional UWorld that is associated with this scene.
Returns
UWorld instance used by this scene
References GetWorld().
Referenced by GetWorld().
HasAnyExponentialHeightFog()
virtual bool FSceneInterface::HasAnyExponentialHeightFog () const pure virtual
Returns
True if there are any exponential height fog potentially enabled in the scene
HasAnyLights()
virtual bool FSceneInterface::HasAnyLights () const pure virtual
Returns
True if there are any lights in the scene
HasAnyLocalFogVolume()
virtual bool FSceneInterface::HasAnyLocalFogVolume () const pure virtual
Returns
True if there are any local height fog potentially enabled in the scene
HasAtmosphereLightRequiringLightingBuild()
virtual bool FSceneInterface::HasAtmosphereLightRequiringLightingBuild () const pure virtual
HasPrecomputedVolumetricLightmap_RenderThread()
virtual bool FSceneInterface::HasPrecomputedVolumetricLightmap_RenderThread () const inline virtual
Definition at line 287 of file SceneInterface.h.
HasSkyLightRequiringLightingBuild()
virtual bool FSceneInterface::HasSkyLightRequiringLightingBuild () const pure virtual
IncrementFrameNumber()
virtual void FSceneInterface::IncrementFrameNumber () inline virtual
Definition at line 711 of file SceneInterface.h.
InitializePixelInspector()
virtual bool FSceneInterface::InitializePixelInspector (FRenderTarget * BufferFinalColor, FRenderTarget * BufferSceneColor, FRenderTarget * BufferDepth, FRenderTarget * BufferHDR, FRenderTarget * BufferA, FRenderTarget * BufferBCDEF, int32 BufferIndex) inline virtual
Initialize the pixel inspector buffers.
Returns
True if implemented false otherwise.
Definition at line 686 of file SceneInterface.h.
InvalidateRuntimeVirtualTexture()
virtual void FSceneInterface::InvalidateRuntimeVirtualTexture (URuntimeVirtualTextureComponent * Component, FBoxSphereBounds const & WorldBounds, EVTInvalidatePriority InvalidatePriority) inline virtual
Invalidates pages in a runtime virtual texture object.
Parameters
Component RVT component containing the runtime virtual texture to invalidate
WorldBounds World-space bounds of the area of the runtime virtual texture to invalidate
InvalidatePriority Ensures the corresponding pages get processed in priority. This allows increased responsiveness when there are more pages being updated than can be handled in a given frame (when throttling)
Definition at line 305 of file SceneInterface.h.
References Component, and WorldBounds.
IsEditorScene()
virtual bool FSceneInterface::IsEditorScene () const inline virtual
Definition at line 666 of file SceneInterface.h.
OnLevelAddedToWorld()
virtual void FSceneInterface::OnLevelAddedToWorld (const FName & InLevelName, UWorld * InWorld, bool bIsLightingScenario) inline virtual
Notification that level was added to a world.
Parameters
InLevelName Level name
Definition at line 658 of file SceneInterface.h.
OnLevelRemovedFromWorld()
virtual void FSceneInterface::OnLevelRemovedFromWorld (const FName & InLevelName, UWorld * InWorld, bool bIsLightingScenario) inline virtual
Definition at line 659 of file SceneInterface.h.
OnWorldCleanup()
virtual void FSceneInterface::OnWorldCleanup () inline virtual
Definition at line 596 of file SceneInterface.h.
References OnWorldCleanup().
Referenced by OnWorldCleanup().
RefreshNaniteRasterBins()
virtual void FSceneInterface::RefreshNaniteRasterBins (FPrimitiveSceneInfo & PrimitiveSceneInfo) inline virtual
Definition at line 723 of file SceneInterface.h.
RegisterAnimBank()
virtual TArray< FAnimBankRecordHandle > FSceneInterface::RegisterAnimBank (const TConstArrayView< FAnimBankDesc > Descs) pure virtual
Release()
virtual void FSceneInterface::Release () pure virtual
Release this scene and remove it from the rendering thread.
References Release().
Referenced by Release().
ReleasePrimitive() [1/2]
virtual void FSceneInterface::ReleasePrimitive (FPrimitiveSceneDesc * Primitive) pure virtual
ReleasePrimitive() [2/2]
virtual void FSceneInterface::ReleasePrimitive (UPrimitiveComponent * Primitive) pure virtual
Called when a primitive is being unregistered and will not be immediately re-registered.
ReleaseReflectionCubemap()
virtual void FSceneInterface::ReleaseReflectionCubemap (UReflectionCaptureComponent * CaptureComponent) inline virtual
Definition at line 240 of file SceneInterface.h.
ReloadNaniteFixedFunctionBins()
virtual void FSceneInterface::ReloadNaniteFixedFunctionBins () inline virtual
Definition at line 724 of file SceneInterface.h.
RemoveDecal()
virtual void FSceneInterface::RemoveDecal (UDecalComponent * Component) pure virtual
Removes a decal component from the scene.
Parameters
Component - component to remove
References Component.
RemoveExponentialHeightFog()
virtual void FSceneInterface::RemoveExponentialHeightFog (uint64 Id) pure virtual
Removes a exponential height fog component from the scene.
Parameters
FogComponent - fog component to remove
RemoveHairStrands()
virtual void FSceneInterface::RemoveHairStrands (FHairStrandsInstance * Proxy) pure virtual
Removes a hair strands proxy to the scene.
Parameters
Proxy - the hair strands proxy
RemoveLight()
virtual void FSceneInterface::RemoveLight (ULightComponent * Light) pure virtual
Removes a light component from the scene.
Parameters
Light - light component to remove
References Light.
RemoveLocalFogVolume()
virtual void FSceneInterface::RemoveLocalFogVolume (class FLocalFogVolumeSceneProxy * FogProxy) pure virtual
Removes a local height fog component from the scene.
Parameters
FogProxy - fog proxy to remove
RemoveLumenSceneCard()
virtual void FSceneInterface::RemoveLumenSceneCard (class ULumenSceneCardComponent * LumenSceneCardComponent) inline virtual
Definition at line 539 of file SceneInterface.h.
RemovePlanarReflection()
virtual void FSceneInterface::RemovePlanarReflection (class UPlanarReflectionComponent * Component) inline virtual
Definition at line 273 of file SceneInterface.h.
References Component.
RemovePrecomputedLightVolume()
virtual void FSceneInterface::RemovePrecomputedLightVolume (const class FPrecomputedLightVolume * Volume) inline virtual
Definition at line 285 of file SceneInterface.h.
References Volume.
RemovePrecomputedVolumetricLightmap()
virtual void FSceneInterface::RemovePrecomputedVolumetricLightmap (const class FPrecomputedVolumetricLightmap * Volume) inline virtual
Definition at line 289 of file SceneInterface.h.
References Volume.
RemovePrimitive() [1/2]
virtual void FSceneInterface::RemovePrimitive (FPrimitiveSceneDesc * Primitive) pure virtual
RemovePrimitive() [2/2]
virtual void FSceneInterface::RemovePrimitive (UPrimitiveComponent * Primitive) pure virtual
Removes a primitive component from the scene.
Parameters
Primitive - primitive component to remove
RemoveReflectionCapture()
virtual void FSceneInterface::RemoveReflectionCapture (class UReflectionCaptureComponent * Component) inline virtual
Removes a reflection capture from the scene.
Definition at line 227 of file SceneInterface.h.
References Component.
RemoveRuntimeVirtualTexture()
virtual void FSceneInterface::RemoveRuntimeVirtualTexture (URuntimeVirtualTextureComponent * Component) inline virtual
Removes a runtime virtual texture object from the scene.
Definition at line 294 of file SceneInterface.h.
References Component.
RemoveSkyAtmosphere()
virtual void FSceneInterface::RemoveSkyAtmosphere (FSkyAtmosphereSceneProxy * SkyAtmosphereSceneProxy) pure virtual
Removes the unique volumetric cloud component to the scene.
Parameters
SkyAtmosphereSceneProxy - the sky atmosphere proxy
RemoveSparseVolumeTextureViewer()
virtual void FSceneInterface::RemoveSparseVolumeTextureViewer (FSparseVolumeTextureViewerSceneProxy * SVTV) pure virtual
RemoveSpeedTreeWind_RenderThread()
virtual void FSceneInterface::RemoveSpeedTreeWind_RenderThread (class FVertexFactory * VertexFactory, const class UStaticMesh * StaticMesh) pure virtual
Removes a SpeedTree wind computation object to the scene.
Parameters
StaticMesh - The SpeedTree static mesh whose wind to remove.
References StaticMesh, and VertexFactory.
RemoveVolumetricCloud()
virtual void FSceneInterface::RemoveVolumetricCloud (FVolumetricCloudSceneProxy * VolumetricCloudSceneProxy) pure virtual
Removes the unique volumetric cloud component to the scene.
Parameters
VolumetricCloudSceneProxy - the sky atmosphere proxy
RemoveWindSource()
virtual void FSceneInterface::RemoveWindSource (class UWindDirectionalSourceComponent * WindComponent) pure virtual
Removes a wind source component from the scene.
Parameters
WindComponent - The component to remove.
RequestGPUSceneUpdate()
virtual bool FSceneInterface::RequestGPUSceneUpdate (FPrimitiveSceneInfo & PrimitiveSceneInfo, EPrimitiveDirtyState PrimitiveDirtyState) inline virtual
Definition at line 720 of file SceneInterface.h.
RequestUniformBufferUpdate()
virtual bool FSceneInterface::RequestUniformBufferUpdate (FPrimitiveSceneInfo & PrimitiveSceneInfo) inline virtual
Definition at line 721 of file SceneInterface.h.
RequiresHitProxies()
virtual bool FSceneInterface::RequiresHitProxies () const pure virtual
Indicates if hit proxies should be processed by this scene.
Returns
true if hit proxies should be rendered in this scene.
References RequiresHitProxies().
Referenced by RequiresHitProxies().
ResetPhysicsField()
virtual void FSceneInterface::ResetPhysicsField () pure virtual
Reset the physics field scene proxy.
ResetReflectionCaptures()
virtual void FSceneInterface::ResetReflectionCaptures (bool bOnlyIfOOM) inline virtual
Resets reflection capture data to allow it to be rebuilt from scratch.
Allows shrinking of the number of items in the capture array, which otherwise only grows. This can allow the user to solve cases where an out of memory (OOM) condition prevented captures from being generated. The user can remove some items or reduce the capture resolution to fix the issue, and run "Build Reflection Captures" (which calls this function), instead of needing to restart the editor. The flag "bOnlyIfOOM" only does the reset if an OOM had occurred.
Definition at line 249 of file SceneInterface.h.
SetFXSystem()
virtual void FSceneInterface::SetFXSystem (class FFXSystemInterface * InFXSystem) pure virtual
Sets the FX system associated with the scene.
SetPhysicsField()
virtual void FSceneInterface::SetPhysicsField (class FPhysicsFieldSceneProxy * PhysicsFieldSceneProxy) pure virtual
Set the physics field scene proxy to the scene.
Parameters
PhysicsFieldSceneProxy - the physics field scene proxy
SetPrecomputedVisibility()
virtual void FSceneInterface::SetPrecomputedVisibility (const class FPrecomputedVisibilityHandler * PrecomputedVisibilityHandler) inline virtual
Sets the precomputed visibility handler for the scene, or NULL to clear the current one.
Definition at line 337 of file SceneInterface.h.
SetPrecomputedVolumeDistanceField()
virtual void FSceneInterface::SetPrecomputedVolumeDistanceField (const class FPrecomputedVolumeDistanceField * PrecomputedVolumeDistanceField) inline virtual
Sets the precomputed volume distance field for the scene, or NULL to clear the current one.
Definition at line 340 of file SceneInterface.h.
SetSkyLight()
virtual void FSceneInterface::SetSkyLight (FSkyLightSceneProxy * Light) pure virtual
References Light.
ShowPhysicsField()
virtual void FSceneInterface::ShowPhysicsField () pure virtual
Set the shader print/debug cvars to be able to show the fields.
StartFrame()
virtual void FSceneInterface::StartFrame () inline virtual
Definition at line 708 of file SceneInterface.h.
StartUpdatePrimitiveTransform()
virtual void FSceneInterface::StartUpdatePrimitiveTransform (int32 NumPrimitives) pure virtual
UE_DEPRECATED() [1/7]
FSceneInterface::UE_DEPRECATED (5. 0, "This method has been refactored to use an FRDGBuilder instead.") &
UE_DEPRECATED() [2/7]
FSceneInterface::UE_DEPRECATED (5. 1, "This method now accepts a bInsideTick parameter, which specifies whether it 's called during the frame Tick.") const &
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/7]
FSceneInterface::UE_DEPRECATED (5. 2, "AllocateAndCaptureFrameSkyEnvMap now takes an FRDGExternalAccessQueue") &
UE_DEPRECATED() [4/7]
FSceneInterface::UE_DEPRECATED (5. 6, "FRayTracingDynamicGeometryCollection has been removed - all raytracing dynamic geometries are collected via the FRayTracingInstanceCollector during GetDynamicRayTracingInstances on the proxy.") inline
Definition at line 715 of file SceneInterface.h.
UE_DEPRECATED() [5/7]
FSceneInterface::UE_DEPRECATED (5. 6, "FRayTracingSkinnedGeometryUpdateQueue has been removed - all raytracing dynamic geometries are collected via the FRayTracingInstanceCollector during GetDynamicRayTracingInstances on the proxy.") inline
Definition at line 717 of file SceneInterface.h.
UE_DEPRECATED() [6/7]
FSceneInterface::UE_DEPRECATED (5. 6, "StaticMeshBounds is no longer a parameter of this interface, please update FPrimitiveSceneDesc version.") pure virtual
References UE_DEPRECATED(), and UpdatePrimitiveInstances().
UE_DEPRECATED() [7/7]
FSceneInterface::UE_DEPRECATED (5. 6, "Use the alternate prototype with the Priority param")
UE_EXPERIMENTAL()
FSceneInterface::UE_EXPERIMENTAL (5. 6, "Experimental API, scene writing delegate may be internalized in the future.")
UnregisterAnimBank()
virtual void FSceneInterface::UnregisterAnimBank (const TConstArrayView< FAnimBankRecordHandle > Handles) pure virtual
UpdateAllPrimitiveSceneInfos() [1/2]
virtual void FSceneInterface::UpdateAllPrimitiveSceneInfos (FRDGBuilder & GraphBuilder, EUpdateAllPrimitiveSceneInfosAsyncOps AsyncOps = EUpdateAllPrimitiveSceneInfosAsyncOps::None) pure virtual
Updates all primitive scene info additions, remobals and translation changes.
References None.
UpdateAllPrimitiveSceneInfos() [2/2]
void FSceneInterface::UpdateAllPrimitiveSceneInfos (FRHICommandListImmediate & RHICmdList)
UpdateCachedRayTracingState()
virtual void FSceneInterface::UpdateCachedRayTracingState (class FPrimitiveSceneProxy * SceneProxy) inline virtual
Definition at line 713 of file SceneInterface.h.
UpdateCachedRenderStates()
virtual void FSceneInterface::UpdateCachedRenderStates (class FPrimitiveSceneProxy * SceneProxy) inline virtual
Update render states that possibly cached inside renderer, like mesh draw commands.
More lightweight than re-registering the scene proxy.
Definition at line 346 of file SceneInterface.h.
UpdateCustomPrimitiveData() [1/2]
virtual void FSceneInterface::UpdateCustomPrimitiveData (FPrimitiveSceneDesc * Primitive, const FCustomPrimitiveData & CustomPrimitiveData) pure virtual
References CustomPrimitiveData.
UpdateCustomPrimitiveData() [2/2]
virtual void FSceneInterface::UpdateCustomPrimitiveData (UPrimitiveComponent * Primitive) pure virtual
Updates the custom primitive data of a primitive component which has already been added to the scene.
Parameters
Primitive - Primitive component to update
UpdateDecalFadeInTime()
virtual void FSceneInterface::UpdateDecalFadeInTime (UDecalComponent * Component) pure virtual
References Component.
UpdateDecalFadeOutTime()
virtual void FSceneInterface::UpdateDecalFadeOutTime (UDecalComponent * Component) pure virtual
References Component.
UpdateDecalTransform()
virtual void FSceneInterface::UpdateDecalTransform (UDecalComponent * Component) pure virtual
Updates the transform of a decal which has already been added to the scene.
Parameters
Decal - Decal component to update
References Component.
UpdateEarlyZPassMode()
virtual void FSceneInterface::UpdateEarlyZPassMode () inline virtual
Definition at line 668 of file SceneInterface.h.
UpdateInstanceCullDistance()
virtual void FSceneInterface::UpdateInstanceCullDistance (UPrimitiveComponent * Primitive, float StartCullDistance, float EndCullDistance) pure virtual
UpdateLightColorAndBrightness()
virtual void FSceneInterface::UpdateLightColorAndBrightness (ULightComponent * Light) pure virtual
Updates the color and brightness of a light which has already been added to the scene.
Parameters
Light - light component to update
References Light.
UpdateLumenSceneCardTransform()
virtual void FSceneInterface::UpdateLumenSceneCardTransform (class ULumenSceneCardComponent * LumenSceneCardComponent) inline virtual
Definition at line 538 of file SceneInterface.h.
UpdateParameterCollections()
virtual void FSceneInterface::UpdateParameterCollections (const TArray< class FMaterialParameterCollectionInstanceResource * > & InParameterCollections) inline virtual
Updates the scene's list of parameter collection id's and their uniform buffers.
Definition at line 635 of file SceneInterface.h.
UpdatePhysicsField()
virtual void FSceneInterface::UpdatePhysicsField (FRDGBuilder & GraphBuilder, FViewInfo & View) pure virtual
Reset the physics field scene proxy.
References View.
UpdatePlanarReflectionContents()
virtual void FSceneInterface::UpdatePlanarReflectionContents (class UPlanarReflectionComponent * CaptureComponent, class FSceneRenderer & MainSceneRenderer, class ISceneRenderBuilder & SceneRenderBuilder) inline virtual
Definition at line 282 of file SceneInterface.h.
UpdatePlanarReflectionTransform()
virtual void FSceneInterface::UpdatePlanarReflectionTransform (UPlanarReflectionComponent * Component) inline virtual
Definition at line 274 of file SceneInterface.h.
References Component.
UpdatePrimitiveAttachment()
virtual void FSceneInterface::UpdatePrimitiveAttachment (UPrimitiveComponent * Primitive) pure virtual
Updates primitive attachment state.
UpdatePrimitiveDistanceFieldSceneData_GameThread()
virtual void FSceneInterface::UpdatePrimitiveDistanceFieldSceneData_GameThread (UPrimitiveComponent * Primitive) inline virtual
Updates distance field scene data (transforms, uv scale, self-shadow bias, etc.) but doesn't change allocation in the atlas.
Definition at line 166 of file SceneInterface.h.
UpdatePrimitiveDrawDistance()
virtual void FSceneInterface::UpdatePrimitiveDrawDistance (UPrimitiveComponent * Primitive, float MinDrawDistance, float MaxDrawDistance, float VirtualTextureMaxDrawDistance) pure virtual
UpdatePrimitiveInstances() [1/2]
virtual void FSceneInterface::UpdatePrimitiveInstances (FPrimitiveSceneDesc * Primitive) pure virtual
UpdatePrimitiveInstances() [2/2]
virtual void FSceneInterface::UpdatePrimitiveInstances (UPrimitiveComponent * Primitive) pure virtual
Call to notify that an instace proxy update has been queued for the primitive.
Parameters
Primitive - primitive component to update
Referenced by UE_DEPRECATED().
UpdatePrimitiveOcclusionBoundsSlack()
virtual void FSceneInterface::UpdatePrimitiveOcclusionBoundsSlack (UPrimitiveComponent * Primitive, float NewSlack) pure virtual
UpdatePrimitivesDrawnInGame_RenderThread()
virtual void FSceneInterface::UpdatePrimitivesDrawnInGame_RenderThread (TArrayView< FPrimitiveSceneProxy * > PrimitiveSceneProxies, bool bDrawnInGame) pure virtual
References UpdatePrimitivesDrawnInGame_RenderThread().
Referenced by UpdatePrimitivesDrawnInGame_RenderThread().
UpdatePrimitiveSelectedState_RenderThread()
virtual void FSceneInterface::UpdatePrimitiveSelectedState_RenderThread (const FPrimitiveSceneInfo * PrimitiveSceneInfo, bool bIsSelected) inline virtual
Updates the selected state values that might be cached inside the renderer.
Definition at line 349 of file SceneInterface.h.
UpdatePrimitiveTransform() [1/2]
virtual void FSceneInterface::UpdatePrimitiveTransform (FPrimitiveSceneDesc * Primitive) pure virtual
UpdatePrimitiveTransform() [2/2]
virtual void FSceneInterface::UpdatePrimitiveTransform (UPrimitiveComponent * Primitive) pure virtual
Updates the transform of a primitive which has already been added to the scene.
Parameters
Primitive - primitive component to update
UpdatePrimitiveVelocityState_RenderThread()
virtual void FSceneInterface::UpdatePrimitiveVelocityState_RenderThread (FPrimitiveSceneInfo * PrimitiveSceneInfo, bool bIsBeingMoved) inline virtual
Updates the velocity state values that might be cached inside the renderer.
Definition at line 352 of file SceneInterface.h.
UpdateReflectionCaptureTransform()
virtual void FSceneInterface::UpdateReflectionCaptureTransform (class UReflectionCaptureComponent * Component) inline virtual
Updates a reflection capture's transform, and then re-captures the scene.
Definition at line 233 of file SceneInterface.h.
References Component.
UpdateSceneCaptureContents() [1/2]
virtual void FSceneInterface::UpdateSceneCaptureContents (class USceneCaptureComponent2D * CaptureComponent, class ISceneRenderBuilder & SceneRenderBuilder) inline virtual
Updates the contents of the given scene capture by rendering the scene.
This must be called on the game thread.
Definition at line 280 of file SceneInterface.h.
UpdateSceneCaptureContents() [2/2]
virtual void FSceneInterface::UpdateSceneCaptureContents (class USceneCaptureComponentCube * CaptureComponent, class ISceneRenderBuilder & SceneRenderBuilder) inline virtual
Definition at line 281 of file SceneInterface.h.
UpdateSceneSettings()
virtual void FSceneInterface::UpdateSceneSettings (AWorldSettings * WorldSettings) inline virtual
Definition at line 599 of file SceneInterface.h.
UpdateSkyCaptureContents()
virtual void FSceneInterface::UpdateSkyCaptureContents (const USkyLightComponent * CaptureComponent, bool bCaptureEmissiveOnly, UTextureCube * SourceCubemap, FTexture * OutProcessedTexture, float & OutAverageBrightness, FSHVectorRGB3 & OutIrradianceEnvironmentMap, TArray< FFloat16Color > * OutRadianceMap, FLinearColor * SpecifiedCubemapColorScale) inline virtual
Updates the contents of the given sky capture by rendering the scene.
This must be called on the game thread.
Definition at line 261 of file SceneInterface.h.
UpdateSpeedTreeWind()
virtual void FSceneInterface::UpdateSpeedTreeWind (double CurrentTime) pure virtual
Ticks the SpeedTree wind object and updates the uniform buffer.
UpdateStaticDrawLists()
virtual void FSceneInterface::UpdateStaticDrawLists () inline virtual
Updates all static draw lists.
Definition at line 343 of file SceneInterface.h.
UpdateWindSource()
virtual void FSceneInterface::UpdateWindSource (class UWindDirectionalSourceComponent * WindComponent) pure virtual
Update a wind source component from the scene.
Parameters
WindComponent - The component to update.
Friends And Related Symbol Documentation
FSceneViewStateReference
friend class FSceneViewStateReference friend
Definition at line 761 of file SceneInterface.h.
References FSceneViewStateReference.
Referenced by FSceneViewStateReference.
Field Documentation
bCapturingForMobile
const TCHAR bool bool FSceneInterface::bCapturingForMobile
Initial value:
{
        AllocateReflectionCaptures(NewCaptures, CaptureReason, bVerifyOnlyCapturing, bCapturingForMobile, false)
Definition at line 252 of file SceneInterface.h.
Referenced by AllocateReflectionCaptures().
bShouldRenderSkyAtmosphere
FSceneRenderer FViewInfo bool FSceneInterface::bShouldRenderSkyAtmosphere
Definition at line 264 of file SceneInterface.h.
bShouldRenderVolumetricCloud
FSceneRenderer FViewInfo bool bool FSceneInterface::bShouldRenderVolumetricCloud
Definition at line 264 of file SceneInterface.h.
bVerifyOnlyCapturing
const TCHAR bool FSceneInterface::bVerifyOnlyCapturing
Definition at line 252 of file SceneInterface.h.
Referenced by AllocateReflectionCaptures().
CaptureReason
const TCHAR* FSceneInterface::CaptureReason
Definition at line 252 of file SceneInterface.h.
Referenced by AllocateReflectionCaptures().
DataWriterGPU
FGPUSceneWriteDelegate&& FSceneInterface::DataWriterGPU = 0
Definition at line 558 of file SceneInterface.h.
FeatureLevel
ERHIFeatureLevel::Type FSceneInterface::FeatureLevel protected
This scene's feature level.
Definition at line 759 of file SceneInterface.h.
Referenced by GetFeatureLevel().
InstanceCullingManager
FSceneRenderer FViewInfo bool bool FInstanceCullingManager& FSceneInterface::InstanceCullingManager
Initial value:
{}
    virtual void AllocateAndCaptureFrameSkyEnvMap(FRDGBuilder& GraphBuilder, FSceneRenderer& SceneRenderer, FViewInfo& MainView, bool bShouldRenderSkyAtmosphere, bool bShouldRenderVolumetricCloud, FInstanceCullingManager& InstanceCullingManager, FRDGExternalAccessQueue& ExternalAccessQueue) {}
    virtual void ValidateSkyLightRealTimeCapture(FRDGBuilder& GraphBuilder, const FViewInfo& View, FRDGTextureRef SceneColorTexture) {}
    UE_DEPRECATED(5.4, "This method has been refactored to be a proper visualization post process. It should have never been added on the FSceneInterface in the first place.")
    1 virtual void ProcessAndRenderIlluminanceMeter(FRDGBuilder& GraphBuilder, TArrayView<FViewInfo> Views, FRDGTextureRef SceneColorTexture)
Definition at line 264 of file SceneInterface.h.
MainView
FSceneRenderer FViewInfo& FSceneInterface::MainView
Definition at line 264 of file SceneInterface.h.
SceneRenderer
FSceneRenderer& FSceneInterface::SceneRenderer
Definition at line 264 of file SceneInterface.h.
View
FViewInfo& FSceneInterface::View
Initial value:
{}
    virtual FVolumetricCloudRenderSceneInfo* GetVolumetricCloudSceneInfo() = 0
Definition at line 478 of file SceneInterface.h.
Referenced by UpdatePhysicsField().
WorldBounds
FBoxSphereBounds const& FSceneInterface::WorldBounds
Initial value:
{}
    virtual void RequestPreloadRuntimeVirtualTexture(class URuntimeVirtualTextureComponent* Component, FBoxSphereBounds const& WorldBounds, int32 Level) {}
    virtual void InvalidatePathTracedOutput(PathTracing::EInvalidateReason InvalidateReason = PathTracing::EInvalidateReason::Uncategorized) {}
    virtual void InvalidateLumenSurfaceCache_GameThread(UPrimitiveComponent* Component) {}
    virtual void GetPrimitiveUniformShaderParameters_RenderThread(const FPrimitiveSceneInfo* PrimitiveSceneInfo, bool& bHasPrecomputedVolumetricLightmap, FMatrix& PreviousLocalToWorld, int32& SingleCaptureIndex, bool& OutputVelocity) const {}
    virtual void UpdateLightTransform(ULightComponent* Light) = 0
Definition at line 307 of file SceneInterface.h.
Referenced by InvalidateRuntimeVirtualTexture().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneInterface.h