Unreal Engine 5.6 C++ API: UAbilityAsync Class Reference
UAbilityAsync Class Reference
#include "AbilityAsync.h"
Private Member Functions
virtual GAMEPLAYABILITIES_API UAbilitySystemComponent * GetAbilitySystemComponent () const
Returns the ability system component this action is bound to.
virtual GAMEPLAYABILITIES_API void SetAbilityActor (AActor *InActor)
Sets the bound component by searching actor for one.
virtual GAMEPLAYABILITIES_API void SetAbilitySystemComponent (UAbilitySystemComponent *InAbilitySystemComponent)
Sets the bound component.
virtual GAMEPLAYABILITIES_API bool ShouldBroadcastDelegates () const
This should be called prior to broadcasting delegates back into the event graph, this ensures the action and ability system component are still valid.
GENERATED_BODY() public UFUNCTION () GAMEPLAYABILITIES_API virtual void EndAction()
Explicitly end the action, will disable any callbacks and allow action to be destroyed.
Private Attributes
TWeakObjectPtr< UAbilitySystemComponent > AbilitySystemComponent
Detailed Description
Definition at line 22 of file AbilityAsync.h.
Member Function Documentation
GetAbilitySystemComponent()
virtual GAMEPLAYABILITIES_API UAbilitySystemComponent * UAbilityAsync::GetAbilitySystemComponent () const private virtual
Returns the ability system component this action is bound to.
References GetAbilitySystemComponent(), and UE_API.
Referenced by GetAbilitySystemComponent().
SetAbilityActor()
virtual GAMEPLAYABILITIES_API void UAbilityAsync::SetAbilityActor (AActor * InActor) private virtual
Sets the bound component by searching actor for one.
References SetAbilityActor(), and UE_API.
Referenced by SetAbilityActor().
SetAbilitySystemComponent()
virtual GAMEPLAYABILITIES_API void UAbilityAsync::SetAbilitySystemComponent (UAbilitySystemComponent * InAbilitySystemComponent) private virtual
Sets the bound component.
References SetAbilitySystemComponent(), and UE_API.
Referenced by SetAbilitySystemComponent().
ShouldBroadcastDelegates()
virtual GAMEPLAYABILITIES_API bool UAbilityAsync::ShouldBroadcastDelegates () const private virtual
This should be called prior to broadcasting delegates back into the event graph, this ensures the action and ability system component are still valid.
Reimplemented from UCancellableAsyncAction.
References ShouldBroadcastDelegates(), and UE_API.
Referenced by ShouldBroadcastDelegates().
UFUNCTION()
GENERATED_BODY() public UAbilityAsync::UFUNCTION () private
Explicitly end the action, will disable any callbacks and allow action to be destroyed.
References Category, and UE_API.
Field Documentation
AbilitySystemComponent
TWeakObjectPtr<UAbilitySystemComponent> UAbilityAsync::AbilitySystemComponent private
Definition at line 46 of file AbilityAsync.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/Abilities/Async/AbilityAsync.h