Unreal Engine 5.6 C++ API: TUniqueMemoryImagePtr< T > Class Template Reference
TUniqueMemoryImagePtr< T > Class Template Reference
#include "MemoryImage.h"
Public Member Functions
TUniqueMemoryImagePtr ()
TUniqueMemoryImagePtr (T *InPtr)
TUniqueMemoryImagePtr (TUniqueMemoryImagePtr &&Other)
~TUniqueMemoryImagePtr ()
TUniqueMemoryImagePtr & operator= (T *InPtr)
TUniqueMemoryImagePtr & operator= (TUniqueMemoryImagePtr &&Other)
Public Member Functions inherited from TMemoryImagePtr< T >
TMemoryImagePtr ()
TMemoryImagePtr (const TMemoryImagePtr< T > &InPtr)
TMemoryImagePtr (T *InPtr)
~TMemoryImagePtr ()
T * Get () const
T * GetChecked () const
int64 GetFrozenOffsetFromThis () const
int32 GetFrozenTypeIndex () const
bool IsFrozen () const
bool IsNull () const
bool IsValid () const
operator T* () const
T & operator* () const
T * operator-> () const
TMemoryImagePtr & operator= (const TMemoryImagePtr< T > &InPtr)
TMemoryImagePtr & operator= (T *InPtr)
void SafeDelete (const FPointerTableBase *PtrTable=nullptr)
void WriteMemoryImageWithDerivedType (FMemoryImageWriter &Writer, const FTypeLayoutDesc *DerivedTypeDesc) const
Additional Inherited Members
Protected Attributes inherited from TMemoryImagePtr< T >
union {
FFrozenMemoryImagePtr Frozen
uint64 Packed
T * UnfrozenPtr
};
Detailed Description
template<typename T>
class TUniqueMemoryImagePtr< T >
Definition at line 558 of file MemoryImage.h.
Constructor & Destructor Documentation
TUniqueMemoryImagePtr() [1/3]
template<typename T> TUniqueMemoryImagePtr< T >::TUniqueMemoryImagePtr () inline
Definition at line 561 of file MemoryImage.h.
References TMemoryImagePtr< T >::TMemoryImagePtr().
Referenced by TUniqueMemoryImagePtr(), operator=(), and operator=().
TUniqueMemoryImagePtr() [2/3]
template<typename T> TUniqueMemoryImagePtr< T >::TUniqueMemoryImagePtr (T * InPtr) inline explicit
Definition at line 564 of file MemoryImage.h.
References TMemoryImagePtr< T >::TMemoryImagePtr().
TUniqueMemoryImagePtr() [3/3]
template<typename T> TUniqueMemoryImagePtr< T >::TUniqueMemoryImagePtr (TUniqueMemoryImagePtr< T > && Other) inline
Definition at line 568 of file MemoryImage.h.
References TUniqueMemoryImagePtr(), Other, and TMemoryImagePtr< T >::SafeDelete().
~TUniqueMemoryImagePtr()
template<typename T> TUniqueMemoryImagePtr< T >::~TUniqueMemoryImagePtr () inline
Definition at line 574 of file MemoryImage.h.
References TMemoryImagePtr< T >::SafeDelete().
Member Function Documentation
operator=() [1/2]
template<typename T> TUniqueMemoryImagePtr & TUniqueMemoryImagePtr< T >::operator= (T * InPtr) inline
Definition at line 578 of file MemoryImage.h.
References TUniqueMemoryImagePtr(), and TMemoryImagePtr< T >::SafeDelete().
operator=() [2/2]
template<typename T> TUniqueMemoryImagePtr & TUniqueMemoryImagePtr< T >::operator= (TUniqueMemoryImagePtr< T > && Other) inline
Definition at line 584 of file MemoryImage.h.
References TUniqueMemoryImagePtr(), Other, and TMemoryImagePtr< T >::SafeDelete().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/MemoryImage.h