Unreal Engine 5.6 C++ API: Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType > Class Template Reference
Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType > Class Template Reference
TInputValueOperator provides an input for value references.
#include "MetasoundInputNode.h"
Public Member Functions
TInputValueOperator (const FName &InVertexName, const TDataValueReference< DataType > &InValueRef)
Construct an TInputValueOperator with the name of the vertex and the value reference associated with input.
TInputValueOperator (const FVertexName &InVertexName, const FOperatorSettings &InSettings, const FInputVertexInterfaceData &InInterfaceData)
TInputValueOperator (const FVertexName &InVertexName, const FOperatorSettings &InSettings, const FLiteral &InLiteral)
Public Member Functions inherited from Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase
virtual METASOUNDFRONTEND_API void BindInputs (FInputVertexInterfaceData &InOutVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual METASOUNDFRONTEND_API void BindOutputs (FOutputVertexInterfaceData &InOutVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
virtual METASOUNDFRONTEND_API IOperator::FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual METASOUNDFRONTEND_API IOperator::FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual METASOUNDFRONTEND_API IOperator::FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Additional Inherited Members
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Protected Member Functions inherited from Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase
METASOUNDFRONTEND_API FNonExecutableInputOperatorBase (const FVertexName &InVertexName, FAnyDataReference &&InDataRef)
Protected Attributes inherited from Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase
FAnyDataReference DataRef
FVertexName VertexName
Detailed Description
template<typename DataType>
class Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >
TInputValueOperator provides an input for value references.
Definition at line 60 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
TInputValueOperator() [1/3]
template<typename DataType> Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >::TInputValueOperator (const FName & InVertexName, const TDataValueReference< DataType > & InValueRef) inline explicit
Construct an TInputValueOperator with the name of the vertex and the value reference associated with input.
Definition at line 66 of file MetasoundInputNode.h.
References Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::FNonExecutableInputOperatorBase().
TInputValueOperator() [2/3]
template<typename DataType> Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >::TInputValueOperator (const FVertexName & InVertexName, const FOperatorSettings & InSettings, const FLiteral & InLiteral) inline
Definition at line 71 of file MetasoundInputNode.h.
References Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::FNonExecutableInputOperatorBase().
TInputValueOperator() [3/3]
template<typename DataType> Metasound::MetasoundInputNodePrivate::TInputValueOperator< DataType >::TInputValueOperator (const FVertexName & InVertexName, const FOperatorSettings & InSettings, const FInputVertexInterfaceData & InInterfaceData) inline
Definition at line 76 of file MetasoundInputNode.h.
References Metasound::MetasoundInputNodePrivate::FNonExecutableInputOperatorBase::FNonExecutableInputOperatorBase().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundInputNode.h