Unreal Engine 5.6 C++ API: IDisplayClusterOperator Class Reference
IDisplayClusterOperator Class Reference abstract
Display Cluster Operator module interface.
#include "IDisplayClusterOperator.h"
Public Member Functions
virtual ~IDisplayClusterOperator ()=default
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAppendOperatorPanelCommands, TSharedRef< FUICommandList >) DECLARE_DELEGATE_RetVal_OneParam(TSharedRef< IDisplayClusterOperatorApp >
DECLARE_MULTICAST_DELEGATE_OneParam (FOnRegisterLayoutExtensions, FLayoutExtender &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnRegisterStatusBarExtensions, FDisplayClusterOperatorStatusBarExtender &)
virtual void ForceDismissDrawers ()=0
Forces the operator panel to dismiss any open drawers.
virtual FName GetAuxilliaryOperatorExtensionId ()=0
Gets the extension ID for the auxilliary window region intended for lower-thirds windows (e.g log output) that can be used to add tabs to the operator panel.
virtual FName GetDetailsTabId ()=0
Gets the tab ID used for the details panel.
virtual TSharedPtr< FExtensibilityManager > GetOperatorMenuExtensibilityManager ()=0
Gets the extensibility manager for the operator panel's menu bar.
virtual TSharedPtr< FExtensibilityManager > GetOperatorToolBarExtensibilityManager ()=0
Gets the extensibility manager for the operator panel's toolbar.
virtual TSharedRef< IDisplayClusterOperatorViewModel > GetOperatorViewModel ()=0
Gets the operator panel's view model, which stores any state used by the operator panel.
virtual FName GetPrimaryOperatorExtensionId ()=0
Gets the extension ID for the main window region that can be used to add tabs to the operator panel.
virtual void GetRootActorLevelInstances (TArray< ADisplayClusterRootActor * > &OutRootActorInstances)=0
Gets a list of all nDisplay root actor instances that are on the currently loaded level.
virtual FOnAppendOperatorPanelCommands & OnAppendOperatorPanelCommands ()=0
Gets the event handler that is raised when the operator panel binds commands to its command list.
virtual FOnRegisterLayoutExtensions & OnRegisterLayoutExtensions ()=0
Gets the event handler that is raised when the operator panel processes extensions to its layout.
virtual FOnRegisterStatusBarExtensions & OnRegisterStatusBarExtensions ()=0
Gets the event handler that is raised when the operator panel processes extensions to its status bar.
virtual FDelegateHandle RegisterApp (const FOnGetAppInstance &InGetAppInstanceDelegate)=0
Register an app with the operator panel.
virtual void ToggleDrawer (const FName DrawerId)=0
Toggles the state of a drawer with the specified ID, closing the drawer if it is open, and opening the drawer if it is closed.
virtual void UnregisterApp (const FDelegateHandle &InHandle)=0
Unregisters an app from the operator panel.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterOperator & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Data Fields
FOnGetAppInstance
TSharedRef< IDisplayClusterOperatorViewModel >
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterOperator")
Detailed Description
Display Cluster Operator module interface.
Definition at line 21 of file IDisplayClusterOperator.h.
Constructor & Destructor Documentation
~IDisplayClusterOperator()
virtual IDisplayClusterOperator::~IDisplayClusterOperator () virtual default
Member Function Documentation
DECLARE_MULTICAST_DELEGATE_OneParam() [1/3]
IDisplayClusterOperator::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAppendOperatorPanelCommands , TSharedRef< FUICommandList >)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/3]
IDisplayClusterOperator::DECLARE_MULTICAST_DELEGATE_OneParam (FOnRegisterLayoutExtensions , FLayoutExtender &)
DECLARE_MULTICAST_DELEGATE_OneParam() [3/3]
IDisplayClusterOperator::DECLARE_MULTICAST_DELEGATE_OneParam (FOnRegisterStatusBarExtensions , FDisplayClusterOperatorStatusBarExtender &)
ForceDismissDrawers()
virtual void IDisplayClusterOperator::ForceDismissDrawers () pure virtual
Forces the operator panel to dismiss any open drawers.
Get()
IDisplayClusterOperator & IDisplayClusterOperator::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 40 of file IDisplayClusterOperator.h.
References Get(), FModuleManager::GetModuleChecked(), and ModuleName.
Referenced by Get().
GetAuxilliaryOperatorExtensionId()
virtual FName IDisplayClusterOperator::GetAuxilliaryOperatorExtensionId () pure virtual
Gets the extension ID for the auxilliary window region intended for lower-thirds windows (e.g log output) that can be used to add tabs to the operator panel.
GetDetailsTabId()
virtual FName IDisplayClusterOperator::GetDetailsTabId () pure virtual
Gets the tab ID used for the details panel.
GetOperatorMenuExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > IDisplayClusterOperator::GetOperatorMenuExtensibilityManager () pure virtual
Gets the extensibility manager for the operator panel's menu bar.
GetOperatorToolBarExtensibilityManager()
virtual TSharedPtr< FExtensibilityManager > IDisplayClusterOperator::GetOperatorToolBarExtensibilityManager () pure virtual
Gets the extensibility manager for the operator panel's toolbar.
GetOperatorViewModel()
virtual TSharedRef< IDisplayClusterOperatorViewModel > IDisplayClusterOperator::GetOperatorViewModel () pure virtual
Gets the operator panel's view model, which stores any state used by the operator panel.
GetPrimaryOperatorExtensionId()
virtual FName IDisplayClusterOperator::GetPrimaryOperatorExtensionId () pure virtual
Gets the extension ID for the main window region that can be used to add tabs to the operator panel.
GetRootActorLevelInstances()
virtual void IDisplayClusterOperator::GetRootActorLevelInstances (TArray< ADisplayClusterRootActor * > & OutRootActorInstances) pure virtual
Gets a list of all nDisplay root actor instances that are on the currently loaded level.
IsAvailable()
bool IDisplayClusterOperator::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 50 of file IDisplayClusterOperator.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
OnAppendOperatorPanelCommands()
virtual FOnAppendOperatorPanelCommands & IDisplayClusterOperator::OnAppendOperatorPanelCommands () pure virtual
Gets the event handler that is raised when the operator panel binds commands to its command list.
OnRegisterLayoutExtensions()
virtual FOnRegisterLayoutExtensions & IDisplayClusterOperator::OnRegisterLayoutExtensions () pure virtual
Gets the event handler that is raised when the operator panel processes extensions to its layout.
OnRegisterStatusBarExtensions()
virtual FOnRegisterStatusBarExtensions & IDisplayClusterOperator::OnRegisterStatusBarExtensions () pure virtual
Gets the event handler that is raised when the operator panel processes extensions to its status bar.
RegisterApp()
virtual FDelegateHandle IDisplayClusterOperator::RegisterApp (const FOnGetAppInstance & InGetAppInstanceDelegate) pure virtual
Register an app with the operator panel.
References FOnGetAppInstance.
ToggleDrawer()
virtual void IDisplayClusterOperator::ToggleDrawer (const FName DrawerId) pure virtual
Toggles the state of a drawer with the specified ID, closing the drawer if it is open, and opening the drawer if it is closed.
UnregisterApp()
virtual void IDisplayClusterOperator::UnregisterApp (const FDelegateHandle & InHandle) pure virtual
Unregisters an app from the operator panel.
Field Documentation
FOnGetAppInstance
IDisplayClusterOperator::FOnGetAppInstance
Definition at line 29 of file IDisplayClusterOperator.h.
Referenced by RegisterApp().
ModuleName
const TCHAR* IDisplayClusterOperator::ModuleName = TEXT("DisplayClusterOperator") static constexpr
Definition at line 24 of file IDisplayClusterOperator.h.
Referenced by Get(), and IsAvailable().
TSharedRef< IDisplayClusterOperatorViewModel >
IDisplayClusterOperator::TSharedRef< IDisplayClusterOperatorViewModel >
Definition at line 29 of file IDisplayClusterOperator.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterOperator/Public/IDisplayClusterOperator.h