Unreal Engine 5.6 C++ API: UE::Sequencer::TSelectionSetBase< MixinType, KeyType > Class Template Reference
UE::Sequencer::TSelectionSetBase< MixinType, KeyType > Class Template Reference
Typed selection set for keeping track of an externally provided key type KeyType is what is stored within the selection set (ie, an FObjectKey, TWeakPtr or int32) MixinType is the type of the derived class.
#include "SequencerCoreSelectionTypes.h"
Public Member Functions
FORCEINLINE TSelectionSetIteratorState< KeyType > begin () const
Ranged-for iteration support.
void Deselect (KeyType InKey)
Deselect an item.
void Empty ()
Empty this selection.
FORCEINLINE TSelectionSetIteratorState< KeyType > end () const
const TSet< KeyType > & GetSelected () const
Returns the underlying selection set (including potentially invalid items)
bool IsSelected (KeyType InKey) const
Check whether a given item is currently selected.
int32 Num () const
Returns the number of selected items (including potentially invalid items)
template<typename Filter>
void RemoveByPredicate (Filter &&InFilter)
void ReplaceWith (TSelectionSetBase< MixinType, KeyType > &&OtherSelection)
Replace this selection set with the contents from another.
void Select (KeyType InKey, bool *OutNewlySelected=nullptr)
Select a key, optionally supplying a boolean to receieve a value indicating whether it was already selected or not.
template<typename RangeType>
void SelectRange (RangeType Range, bool *OutAnySelected=nullptr)
Selects a range of keys, optionally supplying a boolean to receieve a value indicating whether any were newly selected or not.
Public Member Functions inherited from UE::Sequencer::FSelectionBase
SEQUENCERCORE_API void Empty ()
Empty this selection set.
bool HasPendingChanges () const
Check whether this selection set has reported changes that are currently pending.
Static Public Member Functions
static FORCEINLINE constexpr void OnDeselectItem (const KeyType &)
static FORCEINLINE constexpr bool OnSelectItem (const KeyType &)
Fallback functions for use when derived classes do not implement them.
Protected Member Functions
void EmptyImpl () override
Abstract function for emptying this selection.
Protected Member Functions inherited from UE::Sequencer::FSelectionBase
FSelectionBase ()
Should only be used by derived types.
virtual ~FSelectionBase ()
FSequencerCoreSelection * GetOwner () const
Retrieve the owner of this instance, assuming it has been added to one.
SEQUENCERCORE_API void ReportChanges (bool bInSelectionChanged=true)
Called by derived classes when they have changed.
Protected Attributes
TSet< KeyType > SelectionSet
Additional Inherited Members
Data Fields inherited from UE::Sequencer::FSelectionBase
FSimpleMulticastDelegate OnChanged
Broadcast if this selection set has changed when all event suppressors have been destroyed.
Detailed Description
template<typename MixinType, typename KeyType>
class UE::Sequencer::TSelectionSetBase< MixinType, KeyType >
Typed selection set for keeping track of an externally provided key type KeyType is what is stored within the selection set (ie, an FObjectKey, TWeakPtr or int32) MixinType is the type of the derived class.
This allows for compile-time injection of OnSelect/OnDeselect behavior without needing virtual function calls:
 bool OnSelectItem(const KeyType&){ return true; }
 void OnDeselectItem(const KeyType&){}
Example implementation: class FMySelection : TSelectionSetBase<FMySelection, uint32> { public: // Both these functions are optional: bool OnSelectItem(uint32 In){ return In != 0; } void OnDeselectItem(uint32){} };
Iteration is supported for all types (weak ptrs are skipped and iterated as shared pointers):
class FMySelection : TSelectionSetBase<FMySelection, FWeakViewModelPtr>{};
FMySelection& Selection = ...;
for (FViewModelPtr ViewModel : Selection)
{
    //...;
}
// Filtered iteration is also supported for TWeakViewModelPtr<> types:
for (TViewModelPtr<IOutlinerExtension> Outliner : Selection.Filter<IOutlinerExtension>())
{
    // Only viewmodels that implement the IOutlinerExtension will be iterated
}
Definition at line 119 of file SequencerCoreSelectionTypes.h.
Member Function Documentation
begin()
template<typename MixinType, typename KeyType> FORCEINLINE TSelectionSetIteratorState< KeyType > UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::begin () const inline
Ranged-for iteration support.
Do not use directly
Definition at line 295 of file SequencerCoreSelectionTypes.h.
References FORCEINLINE, and SelectionSet.
Deselect()
template<typename MixinType, typename KeyType> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Deselect (KeyType InKey) inline
Deselect an item.
Definition at line 236 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), OnDeselectItem(), UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Empty()
template<typename MixinType, typename KeyType> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Empty () inline
Empty this selection.
Definition at line 251 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), Key, OnDeselectItem(), UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Referenced by EmptyImpl().
EmptyImpl()
template<typename MixinType, typename KeyType> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::EmptyImpl () inline override protected virtual
Abstract function for emptying this selection.
Implements UE::Sequencer::FSelectionBase.
Definition at line 304 of file SequencerCoreSelectionTypes.h.
References Empty().
end()
template<typename MixinType, typename KeyType> FORCEINLINE TSelectionSetIteratorState< KeyType > UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::end () const inline
Definition at line 296 of file SequencerCoreSelectionTypes.h.
References FORCEINLINE, and SelectionSet.
GetSelected()
template<typename MixinType, typename KeyType> const TSet< KeyType > & UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::GetSelected () const inline
Returns the underlying selection set (including potentially invalid items)
Definition at line 134 of file SequencerCoreSelectionTypes.h.
References SelectionSet.
IsSelected()
template<typename MixinType, typename KeyType> bool UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::IsSelected (KeyType InKey) const inline
Check whether a given item is currently selected.
Definition at line 142 of file SequencerCoreSelectionTypes.h.
References SelectionSet.
Num()
template<typename MixinType, typename KeyType> int32 UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Num () const inline
Returns the number of selected items (including potentially invalid items)
Definition at line 126 of file SequencerCoreSelectionTypes.h.
References SelectionSet.
OnDeselectItem()
template<typename MixinType, typename KeyType> FORCEINLINE constexpr void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::OnDeselectItem (const KeyType &) inline static constexpr
Definition at line 300 of file SequencerCoreSelectionTypes.h.
References FORCEINLINE.
Referenced by Deselect(), Empty(), and ReplaceWith().
OnSelectItem()
template<typename MixinType, typename KeyType> FORCEINLINE constexpr bool UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::OnSelectItem (const KeyType &) inline static constexpr
Fallback functions for use when derived classes do not implement them.
Should be completely compiled out
Definition at line 299 of file SequencerCoreSelectionTypes.h.
References FORCEINLINE.
Referenced by ReplaceWith(), and SelectRange().
RemoveByPredicate()
template<typename MixinType, typename KeyType> template<typename Filter> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::RemoveByPredicate (Filter && InFilter) inline
Remove all selected items that pass the specified filter
Definition at line 271 of file SequencerCoreSelectionTypes.h.
References Filter, UE::Sequencer::FSelectionBase::GetOwner(), Key, UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
ReplaceWith()
template<typename MixinType, typename KeyType> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::ReplaceWith (TSelectionSetBase< MixinType, KeyType > && OtherSelection) inline
Replace this selection set with the contents from another.
Parameters
OtherSelection The selection set to replace this one with
Definition at line 211 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), Key, MoveTemp(), OnDeselectItem(), OnSelectItem(), UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Select()
template<typename MixinType, typename KeyType> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::Select (KeyType InKey, bool * OutNewlySelected = nullptr) inline
Select a key, optionally supplying a boolean to receieve a value indicating whether it was already selected or not.
Parameters
InKey The item to select
OutNewlySelected (Optional) When non-null, will be assigned true of false based on whether this item was newly selected as a result of this call
Definition at line 153 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), MakeArrayView(), SelectionSet, and SelectRange().
SelectRange()
template<typename MixinType, typename KeyType> template<typename RangeType> void UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::SelectRange (RangeType Range, bool * OutAnySelected = nullptr) inline
Selects a range of keys, optionally supplying a boolean to receieve a value indicating whether any were newly selected or not.
Parameters
Range An arbitrary range of items to select. Must be implicitly convertible to KeyType.
OutNewlySelected (Optional) When non-null, will be assigned true of false based on whether this item was newly selected as a result of this call
Definition at line 175 of file SequencerCoreSelectionTypes.h.
References UE::Sequencer::FSelectionBase::GetOwner(), Key, OnSelectItem(), UE::Sequencer::FSelectionBase::ReportChanges(), and SelectionSet.
Referenced by Select().
Field Documentation
SelectionSet
template<typename MixinType, typename KeyType> TSet<KeyType> UE::Sequencer::TSelectionSetBase< MixinType, KeyType >::SelectionSet protected
Definition at line 309 of file SequencerCoreSelectionTypes.h.
Referenced by begin(), Deselect(), Empty(), end(), GetSelected(), IsSelected(), Num(), RemoveByPredicate(), ReplaceWith(), Select(), and SelectRange().
The documentation for this class was generated from the following files:
Editor/SequencerCore/Public/MVVM/Selection/SequencerCoreSelectionIterators.h
Editor/SequencerCore/Public/MVVM/Selection/SequencerCoreSelectionTypes.h