Unreal Engine 5.6 C++ API: UEnvQueryGenerator_Composite Class Reference
UEnvQueryGenerator_Composite Class Reference
#include "EnvQueryGenerator_Composite.h"
Protected Member Functions
virtual AIMODULE_API void GenerateItems (FEnvQueryInstance &QueryInstance) const override
if set, tests will be automatically sorted for best performance before running query
virtual AIMODULE_API FText GetDescriptionTitle () const override
virtual AIMODULE_API bool IsValidGenerator () const override
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() TArray< TObjectPtr< UEnvQueryGenerator > > Generators
UPROPERTY() uint32 bAllowDifferentItemTypes UPROPERTY() uint32 bHasMatchingItemType UPROPERTY () TSubclassOf< UEnvQueryItemType > ForcedItemType
allow generators with different item types, use at own risk!
AIMODULE_API void VerifyItemTypes ()
Detailed Description
Definition at line 16 of file EnvQueryGenerator_Composite.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UEnvQueryGenerator_Composite::GENERATED_UCLASS_BODY () private
References Category, and UPROPERTY().
GenerateItems()
virtual AIMODULE_API void UEnvQueryGenerator_Composite::GenerateItems (FEnvQueryInstance & QueryInstance) const override protected virtual
if set, tests will be automatically sorted for best performance before running query
Reimplemented from UEnvQueryGenerator.
References GenerateItems().
Referenced by GenerateItems().
GetDescriptionTitle()
virtual AIMODULE_API FText UEnvQueryGenerator_Composite::GetDescriptionTitle () const override protected virtual
References GetDescriptionTitle().
Referenced by GetDescriptionTitle().
IsValidGenerator()
virtual AIMODULE_API bool UEnvQueryGenerator_Composite::IsValidGenerator () const override protected virtual
Reimplemented from UEnvQueryGenerator.
References IsValidGenerator().
Referenced by IsValidGenerator().
UPROPERTY()
UPROPERTY() uint32 bAllowDifferentItemTypes UPROPERTY() uint32 bHasMatchingItemType UEnvQueryGenerator_Composite::UPROPERTY () private
allow generators with different item types, use at own risk!
WARNING: generator will use ForcedItemType for raw data, you MUST ensure proper memory layout child generators will be writing to memory block through their own item types:
data must fit info block allocated by ForcedItemType
tests will read item location/properties through ForcedItemType
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
VerifyItemTypes()
AIMODULE_API void UEnvQueryGenerator_Composite::VerifyItemTypes () private
References VerifyItemTypes().
Referenced by VerifyItemTypes().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/EnvironmentQuery/Generators/EnvQueryGenerator_Composite.h