Unreal Engine 5.6 C++ API: FEventRef Class Reference
FEventRef Class Reference final
RAII-style pooled FEvent
#include "Event.h"
Public Member Functions
FEventRef (const FEventRef &)=delete
FEventRef (EEventMode Mode=EEventMode::AutoReset)
FEventRef (FEventRef &&Other)=delete
~FEventRef ()
FEvent * Get ()
FEvent * operator-> () const
FEventRef & operator= (const FEventRef &)=delete
FEventRef & operator= (FEventRef &&Other)=delete
Private Attributes
FEvent * Event
Detailed Description
RAII-style pooled FEvent
non-copyable, non-movable
Definition at line 134 of file Event.h.
Constructor & Destructor Documentation
FEventRef() [1/3]
FEventRef::FEventRef (EEventMode Mode = EEventMode::AutoReset) explicit
References AutoReset.
Referenced by FEventRef(), FEventRef(), operator=(), and operator=().
~FEventRef()
FEventRef::~FEventRef ()
FEventRef() [2/3]
FEventRef::FEventRef (const FEventRef &) delete
References FEventRef().
FEventRef() [3/3]
FEventRef::FEventRef (FEventRef && Other) delete
References FEventRef(), and Other.
Member Function Documentation
Get()
FEvent * FEventRef::Get () inline
Definition at line 151 of file Event.h.
References Event.
operator->()
FEvent * FEventRef::operator-> () const inline
Definition at line 146 of file Event.h.
References Event.
operator=() [1/2]
FEventRef & FEventRef::operator= (const FEventRef &) delete
References FEventRef().
operator=() [2/2]
FEventRef & FEventRef::operator= (FEventRef && Other) delete
References FEventRef(), and Other.
Field Documentation
Event
FEvent* FEventRef::Event private
Definition at line 157 of file Event.h.
Referenced by Get(), and operator->().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/Event.h