Unreal Engine 5.6 C++ API: FMaterialCompiler Class Reference
FMaterialCompiler Class Reference abstract
The interface used to translate material expressions into executable code.
#include "MaterialCompiler.h"
Public Member Functions
virtual ~FMaterialCompiler ()
virtual int32 Abs (int32 X)=0
virtual int32 AccessCollectionParameter (UMaterialParameterCollection *ParameterCollection, int32 ParameterIndex, int32 ComponentIndex)=0
virtual int32 ActorWorldPosition (EPositionOrigin OriginType)=0
virtual int32 Add (int32 A, int32 B)=0
virtual int32 AntialiasedTextureMask (int32 Tex, int32 UV, float Threshold, uint8 Channel)=0
virtual void AppendExpressionError (UMaterialExpression *Expression, const TCHAR *Text)=0
virtual int32 AppendVector (int32 A, int32 B)=0
virtual int32 Arccosine (int32 X)=0
virtual int32 ArccosineFast (int32 X)=0
virtual int32 Arcsine (int32 X)=0
virtual int32 ArcsineFast (int32 X)=0
virtual int32 Arctangent (int32 X)=0
virtual int32 Arctangent2 (int32 Y, int32 X)=0
virtual int32 Arctangent2Fast (int32 Y, int32 X)=0
virtual int32 ArctangentFast (int32 X)=0
virtual int32 AtmosphericFogColor (int32 WorldPosition, EPositionOrigin PositionOrigin)=0
virtual int32 AtmosphericLightColor ()=0
virtual int32 AtmosphericLightVector ()=0
virtual int32 BeginScope ()=0
virtual int32 BeginScope_Else ()=0
virtual int32 BeginScope_For (const UMaterialExpression *Expression, int32 StartIndex, int32 EndIndex, int32 IndexStep)=0
virtual int32 BeginScope_If (int32 Condition)=0
virtual int32 BlackBody (int32 Temp)=0
virtual int32 CallExpression (FMaterialExpressionKey ExpressionKey, FMaterialCompiler *InCompiler)=0
virtual int32 CallExpressionExec (UMaterialExpression *Expression)=0
virtual int32 CameraVector ()=0
virtual int32 CastShadingModelToFloat (int32 Code)=0
Cast shading model integer to float value.
virtual int32 Ceil (int32 X)=0
virtual int32 Clamp (int32 X, int32 A, int32 B)=0
virtual int32 CollectionTransform (int32 InputIndex, const TStaticArray< int32, 5 > &CollectionParameters, EParameterCollectionTransformType TransformType)=0
virtual int32 ComponentMask (int32 Vector, bool R, bool G, bool B, bool A)=0
virtual int32 Constant (float X)=0
virtual int32 Constant2 (float X, float Y)=0
virtual int32 Constant3 (float X, float Y, float Z)=0
virtual int32 Constant4 (float X, float Y, float Z, float W)=0
virtual int32 Cosine (int32 X)=0
virtual int32 Cross (int32 A, int32 B)=0
virtual int32 CustomExpression (class UMaterialExpressionCustom *Custom, int32 OutputIndex, TArray< int32 > &CompiledInputs)=0
virtual int32 CustomOutput (class UMaterialExpressionCustomOutput *Custom, int32 OutputIndex, int32 OutputCode, EMaterialCustomOutputFlags Flags=EMaterialCustomOutputFlags::None)=0
virtual int32 CustomPrimitiveData (int32 OutputIndex, EMaterialValueType Type)=0
virtual int32 DBufferTextureLookup (int32 ViewportUV, uint32 DBufferTextureIndex)=0
virtual int32 DDX (int32 X)=0
virtual int32 DDY (int32 X)=0
virtual int32 DecalColor ()=0
virtual int32 DecalLifetimeOpacity ()=0
virtual int32 DefaultMaterialAttributes ()=0
virtual int32 DeltaTime ()=0
virtual int32 DepthOfFieldFunction (int32 Depth, int32 FunctionValueIndex)=0
virtual int32 DistanceCullFade ()=0
virtual int32 DistanceFieldApproxAO (int32 PositionArg, EPositionOrigin PositionOrigin, int32 NormalArg, int32 BaseDistanceArg, int32 RadiusArg, uint32 NumSteps, float StepScale)=0
virtual int32 DistanceFieldGradient (int32 PositionArg, EPositionOrigin PositionOrigin)=0
virtual int32 DistanceToNearestSurface (int32 PositionArg, EPositionOrigin PositionOrigin)=0
virtual int32 Div (int32 A, int32 B)=0
virtual int32 Dot (int32 A, int32 B)=0
virtual int32 DynamicBoolParameter (FName ParameterName, bool bDefaultValue)=0
virtual int32 DynamicBranch (int32 Condition, int32 A, int32 B)=0
virtual int32 DynamicParameter (FLinearColor &DefaultValue, uint32 ParameterIndex=0)=0
virtual int32 EndScope ()=0
virtual int32 Error (const TCHAR *Text)=0
int32 Errorf (const TCHAR *Format,...)
virtual int32 Exponential (int32 X)=0
virtual int32 Exponential2 (int32 X)=0
virtual int32 ExternalCode (const FMaterialExternalCodeDeclaration &InExternalCode)=0
Adds code to the material that is defined by an external function definition.
virtual int32 ExternalTexture (const FGuid &ExternalTextureGuid)=0
int32 ExternalTexture (UTexture *DefaultTexture)
virtual int32 ExternalTexture (UTexture *InTexture, int32 &TextureReferenceIndex)=0
virtual int32 ExternalTextureCoordinateOffset (const FGuid &ExternalTextureGuid)=0
virtual int32 ExternalTextureCoordinateOffset (int32 TextureReferenceIndex, TOptional< FName > ParameterName)=0
virtual int32 ExternalTextureCoordinateScaleRotation (const FGuid &ExternalTextureGuid)=0
virtual int32 ExternalTextureCoordinateScaleRotation (int32 TextureReferenceIndex, TOptional< FName > ParameterName)=0
int32 ExternalTextureParameter (FName ParameterName, UTexture *DefaultTexture)
virtual int32 ExternalTextureParameter (FName ParameterName, UTexture *DefaultValue, int32 &TextureReferenceIndex)=0
virtual int32 EyeAdaptation ()=0
virtual int32 EyeAdaptationInverse (int32 LightValueArg, int32 AlphaArg)=0
virtual void FeedbackMaterialLayersInstancedGraphFromCompilation (const FMaterialLayersFunctions *InLayers)
virtual int32 FindOrAddUserSceneTexture (FName UserSceneTextureName)=0
virtual int32 Floor (int32 X)=0
virtual int32 Fmod (int32 A, int32 B)=0
virtual int32 FontSignedDistanceData ()=0
virtual int32 ForceCast (int32 Code, EMaterialValueType DestType, uint32 ForceCastFlags=0)=0
virtual int32 ForLoopIndex (const UMaterialExpression *Expression)=0
virtual int32 Frac (int32 X)=0
virtual int32 GameTime (bool bPeriodic, float Period)=0
virtual int32 GenericConstant (const UE::Shader::FValue &Value)=0
virtual int32 GetCloudEmptySpaceSkippingSphereCenterWorldPosition ()=0
virtual int32 GetCloudEmptySpaceSkippingSphereRadius ()=0
virtual int32 GetCloudSampleAltitude ()=0
virtual int32 GetCloudSampleAltitudeInLayer ()=0
virtual int32 GetCloudSampleNormAltitudeInLayer ()=0
virtual int32 GetCloudSampleShadowSampleDistance ()=0
virtual FMaterialShadingModelField GetCompiledShadingModels () const =0
Get the shading models that were encountered when compiling a material's Shading Model attribute graph.
virtual EMaterialCompilerType GetCompilerType () const
virtual int32 GetCurrentFunctionStackDepth ()=0
virtual EShaderFrequency GetCurrentShaderFrequency () const =0
virtual ERHIFeatureLevel::Type GetFeatureLevel ()=0
virtual int32 GetHairAO ()=0
virtual int32 GetHairAtlasUVs ()=0
virtual int32 GetHairAuxilaryData ()=0
virtual int32 GetHairBaseColor ()=0
virtual int32 GetHairClumpID ()=0
virtual int32 GetHairColorFromMelanin (int32 Melanin, int32 Redness, int32 DyeColor)=0
virtual int32 GetHairCoverage ()=0
virtual int32 GetHairDepth ()=0
virtual int32 GetHairDimensions ()=0
virtual int32 GetHairGroupIndex ()=0
virtual int32 GetHairRootUV ()=0
virtual int32 GetHairRoughness ()=0
virtual int32 GetHairSeed ()=0
virtual int32 GetHairTangent (bool bUseTangentSpace)=0
virtual int32 GetHairUV ()=0
virtual int32 GetLocal (const FName &LocalName)=0
virtual const FGuid GetMaterialAttribute ()=0
Gets the current top of the MaterialAttributes property stack.
virtual int32 GetMaterialCacheAttribute (int32 MaterialCacheIndex, const FGuid &Attribute)=0
virtual const FMaterialLayersFunctions * GetMaterialLayers ()=0
virtual FMaterialShadingModelField GetMaterialShadingModels () const =0
virtual EMaterialValueType GetParameterType (int32 Index) const =0
virtual FMaterialUniformExpression * GetParameterUniformExpression (int32 Index) const =0
virtual int32 GetPixelPosition ()=0
virtual EMaterialQualityLevel::Type GetQualityLevel ()=0
virtual UObject * GetReferencedTexture (int32 Index)
virtual UTextureCollection * GetReferencedTextureCollection (int32 Index)
virtual int32 GetSceneTextureViewSize (int32 SceneTextureId, bool InvProperty)=0
virtual EShaderPlatform GetShaderPlatform ()=0
virtual bool GetStaticBoolValue (int32 BoolIndex, bool &bSucceeded)=0
ESubstrateMaterialExportContext GetSubstrateMaterialExportContext () const
uint8 GetSubstrateMaterialExportLegacyBlendMode () const
ESubstrateMaterialExport GetSubstrateMaterialExportType () const
virtual FString GetSubstrateSharedLocalBasisIndexMacro (const FSubstrateRegisteredSharedLocalBasis &SharedLocalBasis)=0
virtual bool GetSubstrateTreeOutOfStackDepthOccurred ()=0
This can be used to know if the Substrate tree we are trying to build is too deep and we should stop the compilation.
virtual const ITargetPlatform * GetTargetPlatform () const =0
virtual bool GetTextureCollectionForExpression (int32 Index, int32 &OutTextureCollectionIndex, TOptional< FName > &OutParameterName) const =0
virtual bool GetTextureForExpression (int32 Index, int32 &OutTextureIndex, EMaterialSamplerType &OutSamplerType, TOptional< FName > &OutParameterName) const =0
virtual class UMaterialExpressionCustomOutput * GetTopCustomOutput ()=0
virtual EMaterialValueType GetType (int32 Code)=0
virtual int32 GetViewportUV ()=0
virtual int32 GetVolumeSampleConservativeDensity ()=0
virtual int32 GIReplace (int32 Direct, int32 StaticIndirect, int32 DynamicIndirect)=0
virtual int32 HsvToRgb (int32 X)=0
virtual int32 If (int32 A, int32 B, int32 AGreaterThanB, int32 AEqualsB, int32 ALessThanB, int32 Threshold)=0
virtual int32 InstanceLocalBounds (int32 OutputIndex)=0
virtual int32 InvLerp (int32 X, int32 Y, int32 A)=0
virtual bool IsCurrentlyCompilingForPreviousFrame () const
virtual bool IsDevelopmentFeatureEnabled (const FName &FeatureName) const
virtual int32 IsFirstPerson ()=0
virtual bool IsInRuntimeVirtualTextureOutput () const =0
bool IsLightmassCompiler () const
virtual bool IsMaterialPropertyUsed (EMaterialProperty Property, int32 CodeChunkIdx) const =0
bool IsMaterialProxyCompiler () const
virtual int32 IsOrthographic ()=0
virtual bool IsTangentSpaceNormal () const =0
bool IsVertexInterpolatorBypass () const
virtual int32 Length (int32 X)=0
virtual int32 Lerp (int32 X, int32 Y, int32 A)=0
virtual int32 LightmapUVs ()=0
virtual int32 LightmassReplace (int32 Realtime, int32 Lightmass)=0
virtual int32 LightVector ()=0
virtual int32 LocalPosition (EPositionIncludedOffsets IncludedOffsets, ELocalPositionOrigin OriginType)=0
virtual int32 Logarithm (int32 X)=0
virtual int32 Logarithm10 (int32 X)=0
virtual int32 Logarithm2 (int32 X)=0
virtual int32 MapARPassthroughCameraUV (int32 UV)=0
virtual int32 MaterialBakingWorldPosition ()=0
virtual int32 MaterialCache (int32 Default, int32 MaterialCache)=0
virtual int32 MaterialCacheTextureDescriptor (uint32 LayerIndex)=0
virtual int32 Max (int32 A, int32 B)=0
virtual int32 MeshPaintTextureCoordinateIndex ()=0
virtual int32 MeshPaintTextureDescriptor ()=0
virtual int32 MeshPaintTextureReplace (int32 Invalid, int32 Valid)=0
virtual int32 Min (int32 A, int32 B)=0
virtual int32 Modulo (int32 A, int32 B)=0
virtual int32 Mul (int32 A, int32 B)=0
virtual int32 NaniteReplace (int32 Default, int32 Nanite)=0
virtual int32 NeuralOutput (int32 ViewportUV, uint32 NeuralIndexType)=0
virtual int32 Noise (int32 Position, EPositionOrigin PositionOrigin, float Scale, int32 Quality, uint8 NoiseFunction, bool bTurbulence, int32 Levels, float OutputMin, float OutputMax, float LevelScale, int32 FilterWidth, bool bTiling, uint32 RepeatSize)=0
virtual int32 Normalize (int32 X)=0
virtual int32 NumericParameter (EMaterialParameterType ParameterType, FName ParameterName, const UE::Shader::FValue &DefaultValue)=0
virtual int32 ObjectBounds ()=0
virtual int32 ObjectLocalBounds (int32 OutputIndex)=0
virtual int32 ObjectOrientation ()=0
virtual int32 ObjectRadius ()=0
virtual int32 ObjectWorldPosition (EPositionOrigin OriginType)=0
virtual int32 ParticleColor ()=0
virtual int32 ParticleDirection ()=0
virtual int32 ParticleMacroUV ()=0
virtual int32 ParticleMotionBlurFade ()=0
virtual int32 ParticlePosition (EPositionOrigin OriginType)=0
virtual int32 ParticleRadius ()=0
virtual int32 ParticleRandom ()=0
virtual int32 ParticleRelativeTime ()=0
virtual int32 ParticleSize ()=0
virtual int32 ParticleSpeed ()=0
virtual int32 ParticleSpriteRotation ()=0
virtual int32 ParticleSubUV (int32 TextureIndex, EMaterialSamplerType SamplerType, int32 MipValue0Index, int32 MipValue1Index, ETextureMipValueMode MipValueMode, bool bBlend)=0
virtual int32 ParticleSubUVProperty (int32 PropertyIndex)=0
virtual int32 PathTracingBufferTextureLookup (int32 ViewportUV, uint32 PathTracingBufferTextureIndex)=0
virtual int32 PathTracingQualitySwitchReplace (int32 Normal, int32 PathTraced)=0
virtual int32 PathTracingRayTypeSwitch (int32 Main, int32 Shadow, int32 IndirectDiffuse, int32 IndirectSpecular, int32 IndirectVolume)=0
virtual int32 PerInstanceCustomData (int32 DataIndex, int32 DefaultValueIndex)=0
virtual int32 PerInstanceCustomData3Vector (int32 DataIndex, int32 DefaultValueIndex)=0
virtual int32 PerInstanceFadeAmount ()=0
virtual int32 PerInstanceRandom ()=0
virtual int32 PeriodicHint (int32 PeriodicCode)
virtual int32 PixelDepth ()=0
virtual int32 PixelNormalWS ()=0
virtual FMaterialFunctionCompileState * PopFunction ()=0
Pops a function from the compiler's function stack, which indicates that compilation is leaving a function.
virtual FGuid PopMaterialAttribute ()=0
Pops a MaterialAttributes property off the stack.
virtual FMaterialParameterInfo PopParameterOwner ()=0
Pops a parameter owner off the stack.
virtual int32 PopRuntimeVirtualTextureOutput (uint8 AttributeMask)=0
virtual int32 PostVolumeUserFlagTestFunction (int32 Input)=0
virtual int32 Power (int32 Base, int32 Exponent)=0
virtual int32 PrecomputedAOMask ()=0
virtual int32 PreSkinnedLocalBounds (int32 OutputIndex)=0
virtual int32 PreSkinnedNormal ()=0
virtual int32 PreSkinnedPosition ()=0
virtual void PushFunction (FMaterialFunctionCompileState *FunctionState)=0
Pushes a function onto the compiler's function stack, which indicates that compilation is entering a function.
virtual void PushMaterialAttribute (const FGuid &InAttributeID)=0
Pushes a material attributes property onto the stack.
virtual void PushParameterOwner (const FMaterialParameterInfo &InOwnerInfo)=0
Pushes a parameter owner onto the stack.
virtual int32 PushRuntimeVirtualTextureOutput ()=0
virtual int32 RayTracingQualitySwitchReplace (int32 Normal, int32 RayTraced)=0
virtual int32 RealTime (bool bPeriodic, float Period)=0
virtual int32 ReflectionAboutCustomWorldNormal (int32 CustomWorldNormal, int32 bNormalizeCustomWorldNormal)=0
virtual int32 ReflectionCapturePassSwitch (int32 Default, int32 Reflection)=0
virtual int32 ReflectionVector ()=0
virtual int32 ReturnMaterialAttributes (int32 MaterialAttributes)=0
virtual int32 RgbToHsv (int32 X)=0
virtual int32 RotateAboutAxis (int32 NormalizedRotationAxisAndAngleIndex, int32 PositionOnAxisIndex, int32 PositionIndex)=0
virtual int32 RotateScaleOffsetTexCoords (int32 TexCoordCodeIndex, int32 RotationScale, int32 Offset)=0
virtual int32 Round (int32 X)=0
virtual int32 SampleMaterialCache (int32 TexCoordIndexLiteral)=0
virtual int32 SamplePhysicsField (int32 PositionArg, EPositionOrigin PositionOrigin, const int32 OutputType, const int32 TargetIndex)=0
virtual int32 Saturate (int32 X)=0
virtual int32 ScalarBlueNoise ()=0
int32 ScalarParameter (FName ParameterName, float DefaultValue)
virtual int32 SceneColor (int32 Offset, int32 ViewportUV, bool bUseOffset)=0
virtual int32 SceneDepth (int32 Offset, int32 ViewportUV, bool bUseOffset)=0
virtual int32 SceneDepthWithoutWater (int32 Offset, int32 ViewportUV, bool bUseOffset, float FallbackDepth)=0
virtual int32 SceneTextureLookup (int32 ViewportUV, uint32 SceneTextureId, bool bFiltered, bool bClamped, bool bUnused)=0
virtual void SetBaseMaterialAttribute (const FGuid &InAttributeID)=0
Sets the bottom MaterialAttributes property of the stack.
virtual int32 SetLocal (const FName &LocalName, int32 Value)=0
virtual int32 SetMaterialAttribute (int32 MaterialAttributes, int32 Value, const FGuid &AttributeID)=0
virtual void SetMaterialProperty (EMaterialProperty InProperty, EShaderFrequency OverrideShaderFrequency=SF_NumFrequencies, bool bUsePreviousFrameTime=false)=0
virtual void SetPotentiallyManipulateTexCoords ()=0
void SetSubstrateMaterialExportType (ESubstrateMaterialExport InSubstrateMaterialExport, ESubstrateMaterialExportContext InSubstrateMaterialExportContext, uint8 InSubstrateMaterialExportLegacyBlendMode)
virtual int32 ShadingModel (EMaterialShadingModel InSelectedShadingModel)=0
virtual int32 ShadowReplace (int32 Default, int32 Shadow)=0
virtual bool ShouldStopTranslating () const =0
Whether material translation should abort.
virtual int32 Sign (int32 X)=0
virtual int32 Sine (int32 X)=0
virtual int32 SkyAtmosphereAerialPerspective (int32 WorldPosition, EPositionOrigin PositionOrigin)=0
virtual int32 SkyAtmosphereDistantLightScatteredLuminance ()=0
virtual int32 SkyAtmosphereLightDirection (int32 LightIndex)=0
virtual int32 SkyAtmosphereLightDiskLuminance (int32 LightIndex, int32 OverrideAtmosphereLightDiscCosHalfApexAngle)=0
virtual int32 SkyAtmosphereLightIlluminance (int32 WorldPosition, EPositionOrigin PositionOrigin, int32 LightIndex)=0
virtual int32 SkyAtmosphereLightIlluminanceOnGround (int32 LightIndex)=0
virtual int32 SkyAtmosphereViewLuminance (int32 WorldDirectionOverrideCodeChunk)=0
virtual int32 SkyLightEnvMapSample (int32 DirectionCodeChunk, int32 RoughnessCodeChunk)=0
virtual int32 SmoothStep (int32 X, int32 Y, int32 A)=0
virtual int32 Sobol (int32 Cell, int32 Index, int32 Seed)=0
int32 SparseVolumeTexture (USparseVolumeTexture *Texture, EMaterialSamplerType SamplerType)
virtual int32 SparseVolumeTexture (USparseVolumeTexture *Texture, int32 &TextureReferenceIndex, EMaterialSamplerType SamplerType)=0
Register a sparse volume texture to be sampled.
virtual int32 SparseVolumeTextureParameter (FName ParameterName, USparseVolumeTexture *InDefaultTexture, int32 &TextureReferenceIndex, EMaterialSamplerType SamplerType)=0
Register a parameterized sparse volume texture to be sampled.
virtual int32 SparseVolumeTextureSample (int32 SparseVolumeTextureIndex, int32 UVWIndex, int32 MipValue0Index, int32 MipValue1Index, int32 PhysicalTileDataIdxIndex, ETextureMipValueMode MipValueMode, ESamplerSourceMode SamplerSource)=0
virtual int32 SparseVolumeTextureSamplePageTable (int32 SparseVolumeTextureIndex, int32 UVWIndex, int32 MipLevelIndex, ESamplerSourceMode SamplerSource, bool bIsManualLinearMipMapSecondSample)=0
Sample a sparse volume texture page table.
virtual int32 SparseVolumeTextureSamplePhysicalTileData (int32 SparseVolumeTextureIndex, int32 VoxelCoordIndex, int32 PhysicalTileDataIdxIndex, bool bIsManualLinearMipMapSecondSample)=0
Sample a sparse volume texture physical tile data texture.
virtual int32 SparseVolumeTextureUniform (int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type)=0
Register a uniform parameter required to be able to sample a sparse volume texture.
virtual int32 SparseVolumeTextureUniformParameter (FName ParameterName, int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type)=0
Register a uniform parameter required to be able to sample a parameterizes sparse volume texture.
virtual int32 SpeedTree (int32 GeometryArg, int32 WindArg, int32 LODArg, float BillboardThreshold, bool bAccurateWindVelocities, bool bExtraBend, int32 ExtraBendArg)=0
virtual int32 SphericalParticleOpacity (int32 Density)=0
virtual int32 SquareRoot (int32 X)=0
virtual int32 StaticBool (bool Value)=0
virtual int32 StaticBoolParameter (FName ParameterName, bool bDefaultValue)=0
virtual int32 StaticComponentMask (int32 Vector, FName ParameterName, bool bDefaultR, bool bDefaultG, bool bDefaultB, bool bDefaultA)=0
virtual int32 StaticTerrainLayerWeight (FName ParameterName, int32 Default, bool bTextureArray=false)=0
virtual int32 Step (int32 Y, int32 X)=0
virtual int32 Sub (int32 A, int32 B)=0
virtual int32 SubstrateAdd (int32 A, int32 B, int OperatorIndex, uint32 MaxDistanceFromLeaves)=0
virtual int32 SubstrateAddParameterBlending (int32 A, int32 B, int32 AMixWeight, const FString &SharedLocalBasisIndexMacro, int32 ABSDFNormalCodeChunk, int32 BBSDFNormalCodeChunk, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateAddParameterBlendingBSDFCoverageToNormalMixCodeChunk (int32 ACodeChunk, int32 BCodeChunk)=0
virtual FSubstrateOperator & SubstrateCompilationGetOperator (FGuid SubstrateExpressionGuid)=0
Return the operator information for a given expression.
virtual FSubstrateOperator * SubstrateCompilationGetOperatorFromIndex (int32 OperatorIndex)=0
Return the operator information for a given index.
virtual FSubstrateRegisteredSharedLocalBasis SubstrateCompilationInfoRegisterSharedLocalBasis (int32 NormalCodeChunk)=0
virtual FSubstrateRegisteredSharedLocalBasis SubstrateCompilationInfoRegisterSharedLocalBasis (int32 NormalCodeChunk, int32 TangentCodeChunk)=0
virtual FSubstrateOperator & SubstrateCompilationRegisterOperator (int32 OperatorType, FGuid SubstrateExpressionGuid, FGuid ChildMaterialExpressionGuid, UMaterialExpression *Parent, FGuid SubstrateParentExpressionGuid, bool bUseParameterBlending=false)=0
Register an operator of the tree representation the Substrate material and its topology.
virtual int32 SubstrateCompilePreview (int32 SubstrateDataCodeChunk)=0
virtual int32 SubstrateConversionFromLegacy (bool bHasDynamicShadingModels, int32 BaseColor, int32 Specular, int32 Metallic, int32 Roughness, int32 Anisotropy, int32 SubSurfaceColor, int32 SubSurfaceProfileId, int32 ClearCoat, int32 ClearCoatRoughness, int32 EmissiveColor, int32 Opacity, int32 ThinTranslucentTransmittanceColor, int32 ThinTranslucentSurfaceCoverage, int32 WaterScatteringCoefficients, int32 WaterAbsorptionCoefficients, int32 WaterPhaseG, int32 ColorScaleBehindWater, int32 ShadingModel, int32 Normal, int32 Tangent, const FString &SharedLocalBasisIndexMacro, int32 ClearCoat_Normal, int32 ClearCoat_Tangent, const FString &ClearCoat_SharedLocalBasisIndexMacro, int32 CustomTangent_Tangent, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateCreateAndRegisterNullMaterial ()=0
virtual int32 SubstrateEyeBSDF (int32 DiffuseAlbedo, int32 Roughness, int32 IrisMask, int32 IrisDistance, int32 IrisNormal, int32 IrisPlaneNormal, int32 SSSProfileId, int32 EmissiveColor, int32 CorneaNormal, const FString &SharedLocalBasisIndexMacro, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateHairBSDF (int32 BaseColor, int32 Scatter, int32 Specular, int32 Roughness, int32 Backlit, int32 EmissiveColor, int32 Tangent, const FString &SharedLocalBasisIndexMacro, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateHazinessToSecondaryRoughness (int32 BaseRoughness, int32 Haziness, int32 OutputIndex)=0
virtual int32 SubstrateHorizontalMixing (int32 Background, int32 Foreground, int32 Mix, int OperatorIndex, uint32 MaxDistanceFromLeaves)=0
virtual int32 SubstrateHorizontalMixingParameterBlending (int32 Background, int32 Foreground, int32 HorizontalMixCodeChunk, int32 NormalMixCodeChunk, const FString &SharedLocalBasisIndexMacro, int32 BackgroundBSDFNormalCodeChunk, int32 ForegroundBSDFNormalCodeChunk, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateHorizontalMixingParameterBlendingBSDFCoverageToNormalMixCodeChunk (int32 BackgroundCodeChunk, int32 ForegroundCodeChunk, int32 HorizontalMixCodeChunk)=0
virtual int32 SubstrateMetalnessToDiffuseAlbedoF0 (int32 BaseColor, int32 Specular, int32 Metallic, int32 OutputIndex)=0
virtual int32 SubstrateSelectParameterBlending (int32 A, int32 B, int32 SelectValue, const FString &SharedLocalBasisIndexMacro, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateSingleLayerWaterBSDF (int32 BaseColor, int32 Metallic, int32 Specular, int32 Roughness, int32 EmissiveColor, int32 TopMaterialOpacity, int32 WaterAlbedo, int32 WaterExtinction, int32 WaterPhaseG, int32 ColorScaleBehindWater, int32 Normal, const FString &SharedLocalBasisIndexMacro, FSubstrateOperator *PromoteToOperator)=0
virtual bool SubstrateSkipsOpacityEvaluation ()=0
This is dedicated to skip evaluating any opacity input when a material instance toggles the translucent blend mode to opaque.
virtual int32 SubstrateSlabBSDF (int32 DiffuseAlbedo, int32 F0, int32 F90, int32 Roughness, int32 Anisotropy, int32 SSSProfileId, int32 SSSMFP, int32 SSSMFPScale, int32 SSSPhaseAniso, int32 SSSType, int32 EmissiveColor, int32 SecondRoughness, int32 SecondRoughnessWeight, int32 SecondRoughnessAsSimpleClearCoat, int32 ClearCoatBottomNormal, int32 FuzzAmount, int32 FuzzColor, int32 FuzzRoughness, int32 Thickness, int32 GlintValue, int32 GlintUV, int32 SpecularProfileId, bool bIsAtTheBottomOfTopology, int32 Normal, int32 Tangent, const FString &SharedLocalBasisIndexMacro, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateThicknessStackGetThicknessCode (int32 Index)=0
virtual int32 SubstrateThicknessStackGetThicknessIndex ()=0
virtual void SubstrateThicknessStackPop ()=0
virtual int32 SubstrateThicknessStackPush (UMaterialExpression *Expression, FExpressionInput *Input)=0
virtual int32 SubstrateThinFilm (int32 NormalCodeChunk, int32 SpecularColorCodeChunk, int32 EdgeSpecularColorCodeChunk, int32 ThicknessCodeChunk, int32 IORCodeChunk, int32 OutputIndex)=0
virtual int32 SubstrateTransmittanceToMFP (int32 TransmittanceColor, int32 DesiredThickness, int32 OutputIndex)=0
virtual FGuid SubstrateTreeStackGetParentPathUniqueId ()=0
Returns the unique id of the Substrate tree path for the parent node of the current node position.
virtual FGuid SubstrateTreeStackGetPathUniqueId ()=0
Returns the unique id of the Substrate tree path, identifying the current node we have reached.
virtual void SubstrateTreeStackPop ()=0
Pops a node node of the Substrate tree being walked.
virtual FGuid SubstrateTreeStackPush (UMaterialExpression *Expression, uint32 InputIndex)=0
Pushes a node of the Substrate tree being walked.
virtual int32 SubstrateUIBSDF (int32 EmissiveColor, int32 Opacity, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateUnlitBSDF (int32 EmissiveColor, int32 TransmittanceColor, int32 Normal, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateVerticalLayering (int32 Top, int32 Base, int32 Thickness, int OperatorIndex, uint32 MaxDistanceFromLeaves)=0
virtual int32 SubstrateVerticalLayeringParameterBlending (int32 Top, int32 Base, int32 Thickness, const FString &SharedLocalBasisIndexMacro, int32 TopBSDFNormalCodeChunk, int32 BaseBSDFNormalCodeChunk, FSubstrateOperator *PromoteToOperator)=0
virtual int32 SubstrateVerticalLayeringParameterBlendingBSDFCoverageToNormalMixCodeChunk (int32 TopCodeChunk)=0
virtual int32 SubstrateVolumetricFogCloudBSDF (int32 Albedo, int32 Extinction, int32 EmissiveColor, int32 AmbientOcclusion, bool bEmissiveOnly)=0
virtual int32 SubstrateWeight (int32 A, int32 Weight, int OperatorIndex, uint32 MaxDistanceFromLeaves)=0
virtual int32 SubstrateWeightParameterBlending (int32 A, int32 Weight, FSubstrateOperator *PromoteToOperator)=0
virtual int32 Switch (int32 SwitchValueInput, int32 DefaultInput, TArray< int32 > &CompiledInputs)=0
virtual int32 Tangent (int32 X)=0
virtual int32 TemporalSobol (int32 Index, int32 Seed)=0
int32 Texture (UTexture *InTexture, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource=SSM_FromTextureAsset)
virtual int32 Texture (UTexture *Texture, int32 &TextureReferenceIndex, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource=SSM_FromTextureAsset, ETextureMipValueMode MipValueMode=TMVM_None)=0
int32 TextureCollection (UTextureCollection *InTextureCollection)
virtual int32 TextureCollection (UTextureCollection *TextureCollection, int32 &TextureCollectionReferenceIndex)=0
virtual int32 TextureCollectionCount (int32 InTextureCollectionCodeIndex)=0
int32 TextureCollectionParameter (FName ParameterName, UTextureCollection *DefaultValue)
virtual int32 TextureCollectionParameter (FName ParameterName, UTextureCollection *DefaultValue, int32 &TextureCollectionReferenceIndex)=0
virtual int32 TextureCoordinate (uint32 CoordinateIndex, bool UnMirrorU, bool UnMirrorV)=0
virtual int32 TextureDecalDerivative (bool bDDY)=0
virtual int32 TextureDecalMipmapLevel (int32 TextureSizeInput)=0
virtual int32 TextureFromCollection (int32 TextureCollectionCodeIndex, int32 IndexIntoCollectionCodeIndex, EMaterialValueType ResultTextureType)=0
int32 TextureParameter (FName ParameterName, UTexture *DefaultTexture, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource=SSM_FromTextureAsset)
virtual int32 TextureParameter (FName ParameterName, UTexture *DefaultTexture, int32 &TextureReferenceIndex, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource=SSM_FromTextureAsset)=0
virtual int32 TextureProperty (int32 InTexture, EMaterialExposedTextureProperty Property)=0
virtual int32 TextureSample (int32 Texture, int32 Coordinate, enum EMaterialSamplerType SamplerType, int32 MipValue0Index=INDEX_NONE, int32 MipValue1Index=INDEX_NONE, ETextureMipValueMode MipValueMode=TMVM_None, ESamplerSourceMode SamplerSource=SSM_FromTextureAsset, ETextureGatherMode GatherMode=TGM_None, int32 TextureReferenceIndex=INDEX_NONE, bool AutomaticViewMipBias=false, bool AdaptiveVirtualTexture=false, bool EnableFeedback=true)=0
virtual int32 TextureStreamingInfo (int32 TextureReferenceIndex, int32 TextureIndex, int32 CoordinateIndex)=0
int32 TransformFromPeriodicWorldPosition (EMaterialCommonBasis DestCoordBasis, int TileScaleIndex, int32 A)
virtual int32 TransformNormalFromRequestedBasisToWorld (int32 NormalCodeChunk)=0
virtual int32 TransformPosition (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, FTransformParameters &Parameters, int32 A)=0
int32 TransformPosition (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, int32 A)
int32 TransformToPeriodicWorldPosition (EMaterialCommonBasis SourceCoordBasis, int TileScaleIndex, int32 A)
virtual int32 TransformVector (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, FTransformParameters &Parameters, int32 A)=0
int32 TransformVector (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, int32 A)
virtual int32 Truncate (int32 X)=0
virtual int32 TruncateLWC (int32 Code)=0
virtual int32 TwoSidedSign ()=0
virtual int32 ValidCast (int32 Code, EMaterialValueType DestType)=0
Casts the passed in code to DestType, or generates a compile error if the cast is not valid.
virtual int32 VectorNoise (int32 Position, EPositionOrigin PositionOrigin, int32 Quality, uint8 NoiseFunction, bool bTiling, uint32 RepeatSize)=0
int32 VectorParameter (FName ParameterName, const FLinearColor &DefaultValue)
virtual int32 VertexColor ()=0
virtual int32 VertexInterpolator (uint32 InterpolatorIndex)=0
virtual int32 VertexNormal ()=0
virtual int32 VertexTangent ()=0
virtual int32 ViewProperty (EMaterialExposedViewProperty Property, bool InvProperty=false)=0
int32 VirtualTexture (URuntimeVirtualTexture *InTexture, int32 TextureLayerIndex, int32 PageTableLayerIndex, EMaterialSamplerType SamplerType)
virtual int32 VirtualTexture (URuntimeVirtualTexture *InTexture, int32 TextureLayerIndex, int32 PageTableLayerIndex, int32 &TextureReferenceIndex, EMaterialSamplerType SamplerType)=0
virtual int32 VirtualTextureCustomData ()=0
int32 VirtualTextureParameter (FName ParameterName, URuntimeVirtualTexture *DefaultValue, int32 TextureLayerIndex, int32 PageTableLayerIndex, EMaterialSamplerType SamplerType)
virtual int32 VirtualTextureParameter (FName ParameterName, URuntimeVirtualTexture *DefaultValue, int32 TextureLayerIndex, int32 PageTableLayerIndex, int32 &TextureReferenceIndex, EMaterialSamplerType SamplerType)=0
virtual int32 VirtualTextureUniform (FName ParameterName, int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type)=0
virtual int32 VirtualTextureUniform (int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type)=0
virtual int32 VirtualTextureUnpack (int32 CodeIndex0, int32 CodeIndex1, int32 CodeIndex2, int32 P0, EVirtualTextureUnpackType UnpackType)=0
virtual int32 VirtualTextureWorldToUV (int32 WorldPositionIndex, int32 P0, int32 P1, int32 P2, EPositionOrigin PositionOrigin)=0
virtual int32 WorldPosition (EWorldPositionIncludedOffsets WorldPositionIncludedOffsets)=0
Protected Member Functions
FString GetSubstrateSharedLocalBasisIndexMacroInner (const FSubstrateRegisteredSharedLocalBasis &SharedLocalBasis, uint32 Mode)
Private Attributes
ESubstrateMaterialExport SubstrateMaterialExport = SME_None
ESubstrateMaterialExportContext SubstrateMaterialExportContext = SMEC_Opaque
uint8 SubstrateMaterialExportLegacyBlendMode = 0
Detailed Description
The interface used to translate material expressions into executable code.
Note: Most member functions should be pure virtual to force a FProxyMaterialCompiler override!
Definition at line 119 of file MaterialCompiler.h.
Constructor & Destructor Documentation
~FMaterialCompiler()
virtual FMaterialCompiler::~FMaterialCompiler () inline virtual
Definition at line 122 of file MaterialCompiler.h.
Member Function Documentation
Abs()
virtual int32 FMaterialCompiler::Abs (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
AccessCollectionParameter()
virtual int32 FMaterialCompiler::AccessCollectionParameter (UMaterialParameterCollection * ParameterCollection, int32 ParameterIndex, int32 ComponentIndex) pure virtual
Implemented in FProxyMaterialCompiler.
ActorWorldPosition()
virtual int32 FMaterialCompiler::ActorWorldPosition (EPositionOrigin OriginType) pure virtual
Implemented in FProxyMaterialCompiler.
Add()
virtual int32 FMaterialCompiler::Add (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
AntialiasedTextureMask()
virtual int32 FMaterialCompiler::AntialiasedTextureMask (int32 Tex, int32 UV, float Threshold, uint8 Channel) pure virtual
Implemented in FProxyMaterialCompiler.
References UV.
AppendExpressionError()
virtual void FMaterialCompiler::AppendExpressionError (UMaterialExpression * Expression, const TCHAR * Text) pure virtual
Implemented in FProxyMaterialCompiler.
References Text.
AppendVector()
virtual int32 FMaterialCompiler::AppendVector (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
Arccosine()
virtual int32 FMaterialCompiler::Arccosine (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
ArccosineFast()
virtual int32 FMaterialCompiler::ArccosineFast (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Arcsine()
virtual int32 FMaterialCompiler::Arcsine (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
ArcsineFast()
virtual int32 FMaterialCompiler::ArcsineFast (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Arctangent()
virtual int32 FMaterialCompiler::Arctangent (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Arctangent2()
virtual int32 FMaterialCompiler::Arctangent2 (int32 Y, int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X, and Y.
Arctangent2Fast()
virtual int32 FMaterialCompiler::Arctangent2Fast (int32 Y, int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X, and Y.
ArctangentFast()
virtual int32 FMaterialCompiler::ArctangentFast (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
AtmosphericFogColor()
virtual int32 FMaterialCompiler::AtmosphericFogColor (int32 WorldPosition, EPositionOrigin PositionOrigin) pure virtual
Implemented in FProxyMaterialCompiler.
References WorldPosition().
AtmosphericLightColor()
virtual int32 FMaterialCompiler::AtmosphericLightColor () pure virtual
Implemented in FProxyMaterialCompiler.
AtmosphericLightVector()
virtual int32 FMaterialCompiler::AtmosphericLightVector () pure virtual
Implemented in FProxyMaterialCompiler.
BeginScope()
virtual int32 FMaterialCompiler::BeginScope () pure virtual
Implemented in FProxyMaterialCompiler.
BeginScope_Else()
virtual int32 FMaterialCompiler::BeginScope_Else () pure virtual
Implemented in FProxyMaterialCompiler.
BeginScope_For()
virtual int32 FMaterialCompiler::BeginScope_For (const UMaterialExpression * Expression, int32 StartIndex, int32 EndIndex, int32 IndexStep) pure virtual
Implemented in FProxyMaterialCompiler.
BeginScope_If()
virtual int32 FMaterialCompiler::BeginScope_If (int32 Condition) pure virtual
Implemented in FProxyMaterialCompiler.
BlackBody()
virtual int32 FMaterialCompiler::BlackBody (int32 Temp) pure virtual
Implemented in FProxyMaterialCompiler.
CallExpression()
virtual int32 FMaterialCompiler::CallExpression (FMaterialExpressionKey ExpressionKey, FMaterialCompiler * InCompiler) pure virtual
Implemented in FProxyMaterialCompiler.
CallExpressionExec()
virtual int32 FMaterialCompiler::CallExpressionExec (UMaterialExpression * Expression) pure virtual
Implemented in FProxyMaterialCompiler.
CameraVector()
virtual int32 FMaterialCompiler::CameraVector () pure virtual
Implemented in FProxyMaterialCompiler.
CastShadingModelToFloat()
virtual int32 FMaterialCompiler::CastShadingModelToFloat (int32 Code) pure virtual
Cast shading model integer to float value.
Implemented in FProxyMaterialCompiler.
Ceil()
virtual int32 FMaterialCompiler::Ceil (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Clamp()
virtual int32 FMaterialCompiler::Clamp (int32 X, int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, B, and X.
CollectionTransform()
virtual int32 FMaterialCompiler::CollectionTransform (int32 InputIndex, const TStaticArray< int32, 5 > & CollectionParameters, EParameterCollectionTransformType TransformType) pure virtual
Implemented in FProxyMaterialCompiler.
ComponentMask()
virtual int32 FMaterialCompiler::ComponentMask (int32 Vector, bool R, bool G, bool B, bool A) pure virtual
Implemented in FProxyMaterialCompiler.
References A, B, G, R, and Vector.
Constant()
virtual int32 FMaterialCompiler::Constant (float X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Constant2()
virtual int32 FMaterialCompiler::Constant2 (float X, float Y) pure virtual
Implemented in FProxyMaterialCompiler.
References X, and Y.
Constant3()
virtual int32 FMaterialCompiler::Constant3 (float X, float Y, float Z) pure virtual
Implemented in FProxyMaterialCompiler.
References X, Y, and Z.
Constant4()
virtual int32 FMaterialCompiler::Constant4 (float X, float Y, float Z, float W) pure virtual
Implemented in FProxyMaterialCompiler.
References X, Y, and Z.
Cosine()
virtual int32 FMaterialCompiler::Cosine (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Cross()
virtual int32 FMaterialCompiler::Cross (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
CustomExpression()
virtual int32 FMaterialCompiler::CustomExpression (class UMaterialExpressionCustom * Custom, int32 OutputIndex, TArray< int32 > & CompiledInputs) pure virtual
Implemented in FProxyMaterialCompiler.
References Custom.
CustomOutput()
virtual int32 FMaterialCompiler::CustomOutput (class UMaterialExpressionCustomOutput * Custom, int32 OutputIndex, int32 OutputCode, EMaterialCustomOutputFlags Flags = EMaterialCustomOutputFlags::None) pure virtual
Implemented in FProxyMaterialCompiler.
References Custom, Flags, and None.
CustomPrimitiveData()
virtual int32 FMaterialCompiler::CustomPrimitiveData (int32 OutputIndex, EMaterialValueType Type) pure virtual
Implemented in FProxyMaterialCompiler.
DBufferTextureLookup()
virtual int32 FMaterialCompiler::DBufferTextureLookup (int32 ViewportUV, uint32 DBufferTextureIndex) pure virtual
Implemented in FProxyMaterialCompiler.
DDX()
virtual int32 FMaterialCompiler::DDX (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
DDY()
virtual int32 FMaterialCompiler::DDY (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
DecalColor()
virtual int32 FMaterialCompiler::DecalColor () pure virtual
Implemented in FProxyMaterialCompiler.
DecalLifetimeOpacity()
virtual int32 FMaterialCompiler::DecalLifetimeOpacity () pure virtual
Implemented in FProxyMaterialCompiler.
DefaultMaterialAttributes()
virtual int32 FMaterialCompiler::DefaultMaterialAttributes () pure virtual
Implemented in FProxyMaterialCompiler.
DeltaTime()
virtual int32 FMaterialCompiler::DeltaTime () pure virtual
Implemented in FProxyMaterialCompiler.
DepthOfFieldFunction()
virtual int32 FMaterialCompiler::DepthOfFieldFunction (int32 Depth, int32 FunctionValueIndex) pure virtual
Implemented in FProxyMaterialCompiler.
References Depth.
DistanceCullFade()
virtual int32 FMaterialCompiler::DistanceCullFade () pure virtual
Implemented in FProxyMaterialCompiler.
DistanceFieldApproxAO()
virtual int32 FMaterialCompiler::DistanceFieldApproxAO (int32 PositionArg, EPositionOrigin PositionOrigin, int32 NormalArg, int32 BaseDistanceArg, int32 RadiusArg, uint32 NumSteps, float StepScale) pure virtual
Implemented in FProxyMaterialCompiler.
DistanceFieldGradient()
virtual int32 FMaterialCompiler::DistanceFieldGradient (int32 PositionArg, EPositionOrigin PositionOrigin) pure virtual
Implemented in FProxyMaterialCompiler.
DistanceToNearestSurface()
virtual int32 FMaterialCompiler::DistanceToNearestSurface (int32 PositionArg, EPositionOrigin PositionOrigin) pure virtual
Implemented in FProxyMaterialCompiler.
Div()
virtual int32 FMaterialCompiler::Div (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
Dot()
virtual int32 FMaterialCompiler::Dot (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
DynamicBoolParameter()
virtual int32 FMaterialCompiler::DynamicBoolParameter (FName ParameterName, bool bDefaultValue) pure virtual
Implemented in FProxyMaterialCompiler.
DynamicBranch()
virtual int32 FMaterialCompiler::DynamicBranch (int32 Condition, int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
DynamicParameter()
virtual int32 FMaterialCompiler::DynamicParameter (FLinearColor & DefaultValue, uint32 ParameterIndex = 0) pure virtual
Implemented in FProxyMaterialCompiler.
EndScope()
virtual int32 FMaterialCompiler::EndScope () pure virtual
Implemented in FProxyMaterialCompiler.
Error()
virtual int32 FMaterialCompiler::Error (const TCHAR * Text) pure virtual
Implemented in FProxyMaterialCompiler.
References Text.
Errorf()
int32 FMaterialCompiler::Errorf (const TCHAR * Format, ...)
References Format.
Exponential()
virtual int32 FMaterialCompiler::Exponential (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Exponential2()
virtual int32 FMaterialCompiler::Exponential2 (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
ExternalCode()
virtual int32 FMaterialCompiler::ExternalCode (const FMaterialExternalCodeDeclaration & InExternalCode) pure virtual
Adds code to the material that is defined by an external function definition.
Implemented in FProxyMaterialCompiler.
ExternalTexture() [1/3]
virtual int32 FMaterialCompiler::ExternalTexture (const FGuid & ExternalTextureGuid) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by ExternalTexture().
ExternalTexture() [2/3]
int32 FMaterialCompiler::ExternalTexture (UTexture * DefaultTexture) inline
Definition at line 439 of file MaterialCompiler.h.
References ExternalTexture(), and INDEX_NONE.
ExternalTexture() [3/3]
virtual int32 FMaterialCompiler::ExternalTexture (UTexture * InTexture, int32 & TextureReferenceIndex) pure virtual
Implemented in FProxyMaterialCompiler.
ExternalTextureCoordinateOffset() [1/2]
virtual int32 FMaterialCompiler::ExternalTextureCoordinateOffset (const FGuid & ExternalTextureGuid) pure virtual
Implemented in FProxyMaterialCompiler.
ExternalTextureCoordinateOffset() [2/2]
virtual int32 FMaterialCompiler::ExternalTextureCoordinateOffset (int32 TextureReferenceIndex, TOptional< FName > ParameterName) pure virtual
Implemented in FProxyMaterialCompiler.
ExternalTextureCoordinateScaleRotation() [1/2]
virtual int32 FMaterialCompiler::ExternalTextureCoordinateScaleRotation (const FGuid & ExternalTextureGuid) pure virtual
Implemented in FProxyMaterialCompiler.
ExternalTextureCoordinateScaleRotation() [2/2]
virtual int32 FMaterialCompiler::ExternalTextureCoordinateScaleRotation (int32 TextureReferenceIndex, TOptional< FName > ParameterName) pure virtual
Implemented in FProxyMaterialCompiler.
ExternalTextureParameter() [1/2]
int32 FMaterialCompiler::ExternalTextureParameter (FName ParameterName, UTexture * DefaultTexture) inline
Definition at line 451 of file MaterialCompiler.h.
References ExternalTextureParameter(), and INDEX_NONE.
ExternalTextureParameter() [2/2]
virtual int32 FMaterialCompiler::ExternalTextureParameter (FName ParameterName, UTexture * DefaultValue, int32 & TextureReferenceIndex) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by ExternalTextureParameter().
EyeAdaptation()
virtual int32 FMaterialCompiler::EyeAdaptation () pure virtual
Implemented in FProxyMaterialCompiler.
EyeAdaptationInverse()
virtual int32 FMaterialCompiler::EyeAdaptationInverse (int32 LightValueArg, int32 AlphaArg) pure virtual
Implemented in FProxyMaterialCompiler.
FeedbackMaterialLayersInstancedGraphFromCompilation()
virtual void FMaterialCompiler::FeedbackMaterialLayersInstancedGraphFromCompilation (const FMaterialLayersFunctions * InLayers) inline virtual
Definition at line 490 of file MaterialCompiler.h.
FindOrAddUserSceneTexture()
virtual int32 FMaterialCompiler::FindOrAddUserSceneTexture (FName UserSceneTextureName) pure virtual
Implemented in FProxyMaterialCompiler.
Floor()
virtual int32 FMaterialCompiler::Floor (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Fmod()
virtual int32 FMaterialCompiler::Fmod (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
FontSignedDistanceData()
virtual int32 FMaterialCompiler::FontSignedDistanceData () pure virtual
Implemented in FProxyMaterialCompiler.
ForceCast()
virtual int32 FMaterialCompiler::ForceCast (int32 Code, EMaterialValueType DestType, uint32 ForceCastFlags = 0) pure virtual
Implemented in FProxyMaterialCompiler.
ForLoopIndex()
virtual int32 FMaterialCompiler::ForLoopIndex (const UMaterialExpression * Expression) pure virtual
Implemented in FProxyMaterialCompiler.
Frac()
virtual int32 FMaterialCompiler::Frac (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
GameTime()
virtual int32 FMaterialCompiler::GameTime (bool bPeriodic, float Period) pure virtual
Implemented in FProxyMaterialCompiler.
GenericConstant()
virtual int32 FMaterialCompiler::GenericConstant (const UE::Shader::FValue & Value) pure virtual
Implemented in FProxyMaterialCompiler.
References Value.
GetCloudEmptySpaceSkippingSphereCenterWorldPosition()
virtual int32 FMaterialCompiler::GetCloudEmptySpaceSkippingSphereCenterWorldPosition () pure virtual
Implemented in FProxyMaterialCompiler.
GetCloudEmptySpaceSkippingSphereRadius()
virtual int32 FMaterialCompiler::GetCloudEmptySpaceSkippingSphereRadius () pure virtual
Implemented in FProxyMaterialCompiler.
GetCloudSampleAltitude()
virtual int32 FMaterialCompiler::GetCloudSampleAltitude () pure virtual
Implemented in FProxyMaterialCompiler.
GetCloudSampleAltitudeInLayer()
virtual int32 FMaterialCompiler::GetCloudSampleAltitudeInLayer () pure virtual
Implemented in FProxyMaterialCompiler.
GetCloudSampleNormAltitudeInLayer()
virtual int32 FMaterialCompiler::GetCloudSampleNormAltitudeInLayer () pure virtual
Implemented in FProxyMaterialCompiler.
GetCloudSampleShadowSampleDistance()
virtual int32 FMaterialCompiler::GetCloudSampleShadowSampleDistance () pure virtual
Implemented in FProxyMaterialCompiler.
GetCompiledShadingModels()
virtual FMaterialShadingModelField FMaterialCompiler::GetCompiledShadingModels () const pure virtual
Get the shading models that were encountered when compiling a material's Shading Model attribute graph.
This will represent the actually used Shading Models for a particular material given its static switches, feature levels and material quality for example.
Will return all Shading Models in the material if this is called before that attribute has been compiled.
Implemented in FProxyMaterialCompiler.
GetCompilerType()
virtual EMaterialCompilerType FMaterialCompiler::GetCompilerType () const inline virtual
Definition at line 158 of file MaterialCompiler.h.
References Standard.
Referenced by IsLightmassCompiler(), IsMaterialProxyCompiler(), and IsVertexInterpolatorBypass().
GetCurrentFunctionStackDepth()
virtual int32 FMaterialCompiler::GetCurrentFunctionStackDepth () pure virtual
Implemented in FProxyMaterialCompiler.
GetCurrentShaderFrequency()
virtual EShaderFrequency FMaterialCompiler::GetCurrentShaderFrequency () const pure virtual
Implemented in FProxyMaterialCompiler.
GetFeatureLevel()
virtual ERHIFeatureLevel::Type FMaterialCompiler::GetFeatureLevel () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairAO()
virtual int32 FMaterialCompiler::GetHairAO () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairAtlasUVs()
virtual int32 FMaterialCompiler::GetHairAtlasUVs () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairAuxilaryData()
virtual int32 FMaterialCompiler::GetHairAuxilaryData () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairBaseColor()
virtual int32 FMaterialCompiler::GetHairBaseColor () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairClumpID()
virtual int32 FMaterialCompiler::GetHairClumpID () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairColorFromMelanin()
virtual int32 FMaterialCompiler::GetHairColorFromMelanin (int32 Melanin, int32 Redness, int32 DyeColor) pure virtual
Implemented in FProxyMaterialCompiler.
GetHairCoverage()
virtual int32 FMaterialCompiler::GetHairCoverage () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairDepth()
virtual int32 FMaterialCompiler::GetHairDepth () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairDimensions()
virtual int32 FMaterialCompiler::GetHairDimensions () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairGroupIndex()
virtual int32 FMaterialCompiler::GetHairGroupIndex () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairRootUV()
virtual int32 FMaterialCompiler::GetHairRootUV () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairRoughness()
virtual int32 FMaterialCompiler::GetHairRoughness () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairSeed()
virtual int32 FMaterialCompiler::GetHairSeed () pure virtual
Implemented in FProxyMaterialCompiler.
GetHairTangent()
virtual int32 FMaterialCompiler::GetHairTangent (bool bUseTangentSpace) pure virtual
Implemented in FProxyMaterialCompiler.
GetHairUV()
virtual int32 FMaterialCompiler::GetHairUV () pure virtual
Implemented in FProxyMaterialCompiler.
GetLocal()
virtual int32 FMaterialCompiler::GetLocal (const FName & LocalName) pure virtual
Implemented in FProxyMaterialCompiler.
GetMaterialAttribute()
virtual const FGuid FMaterialCompiler::GetMaterialAttribute () pure virtual
Gets the current top of the MaterialAttributes property stack.
Implemented in FProxyMaterialCompiler.
GetMaterialCacheAttribute()
virtual int32 FMaterialCompiler::GetMaterialCacheAttribute (int32 MaterialCacheIndex, const FGuid & Attribute) pure virtual
Implemented in FProxyMaterialCompiler.
References Attribute.
GetMaterialLayers()
virtual const FMaterialLayersFunctions * FMaterialCompiler::GetMaterialLayers () pure virtual
Implemented in FProxyMaterialCompiler.
GetMaterialShadingModels()
virtual FMaterialShadingModelField FMaterialCompiler::GetMaterialShadingModels () const pure virtual
Implemented in FProxyMaterialCompiler.
GetParameterType()
virtual EMaterialValueType FMaterialCompiler::GetParameterType (int32 Index) const pure virtual
Implemented in FProxyMaterialCompiler.
GetParameterUniformExpression()
virtual FMaterialUniformExpression * FMaterialCompiler::GetParameterUniformExpression (int32 Index) const pure virtual
Implemented in FProxyMaterialCompiler.
GetPixelPosition()
virtual int32 FMaterialCompiler::GetPixelPosition () pure virtual
Implemented in FProxyMaterialCompiler.
GetQualityLevel()
virtual EMaterialQualityLevel::Type FMaterialCompiler::GetQualityLevel () pure virtual
Implemented in FProxyMaterialCompiler.
GetReferencedTexture()
virtual UObject * FMaterialCompiler::GetReferencedTexture (int32 Index) inline virtual
Reimplemented in FProxyMaterialCompiler.
Definition at line 405 of file MaterialCompiler.h.
GetReferencedTextureCollection()
virtual UTextureCollection * FMaterialCompiler::GetReferencedTextureCollection (int32 Index) inline virtual
Reimplemented in FProxyMaterialCompiler.
Definition at line 410 of file MaterialCompiler.h.
GetSceneTextureViewSize()
virtual int32 FMaterialCompiler::GetSceneTextureViewSize (int32 SceneTextureId, bool InvProperty) pure virtual
Implemented in FProxyMaterialCompiler.
GetShaderPlatform()
virtual EShaderPlatform FMaterialCompiler::GetShaderPlatform () pure virtual
Implemented in FProxyMaterialCompiler.
GetStaticBoolValue()
virtual bool FMaterialCompiler::GetStaticBoolValue (int32 BoolIndex, bool & bSucceeded) pure virtual
Implemented in FProxyMaterialCompiler.
GetSubstrateMaterialExportContext()
ESubstrateMaterialExportContext FMaterialCompiler::GetSubstrateMaterialExportContext () const inline
Definition at line 169 of file MaterialCompiler.h.
References SubstrateMaterialExportContext.
GetSubstrateMaterialExportLegacyBlendMode()
uint8 FMaterialCompiler::GetSubstrateMaterialExportLegacyBlendMode () const inline
Definition at line 170 of file MaterialCompiler.h.
References SubstrateMaterialExportLegacyBlendMode.
GetSubstrateMaterialExportType()
ESubstrateMaterialExport FMaterialCompiler::GetSubstrateMaterialExportType () const inline
Definition at line 168 of file MaterialCompiler.h.
References SubstrateMaterialExport.
GetSubstrateSharedLocalBasisIndexMacro()
virtual FString FMaterialCompiler::GetSubstrateSharedLocalBasisIndexMacro (const FSubstrateRegisteredSharedLocalBasis & SharedLocalBasis) pure virtual
Implemented in FProxyMaterialCompiler.
GetSubstrateSharedLocalBasisIndexMacroInner()
FString FMaterialCompiler::GetSubstrateSharedLocalBasisIndexMacroInner (const FSubstrateRegisteredSharedLocalBasis & SharedLocalBasis, uint32 Mode) inline protected
Definition at line 800 of file MaterialCompiler.h.
References TEXT.
GetSubstrateTreeOutOfStackDepthOccurred()
virtual bool FMaterialCompiler::GetSubstrateTreeOutOfStackDepthOccurred () pure virtual
This can be used to know if the Substrate tree we are trying to build is too deep and we should stop the compilation.
This can be used by all nodes taking as input SubstrateData in order to detect node re-entry leading to cyclic graph we cannot handle and compile internally: we must fail the compilation.
Implemented in FProxyMaterialCompiler.
GetTargetPlatform()
virtual const ITargetPlatform * FMaterialCompiler::GetTargetPlatform () const pure virtual
Implemented in FProxyMaterialCompiler.
GetTextureCollectionForExpression()
virtual bool FMaterialCompiler::GetTextureCollectionForExpression (int32 Index, int32 & OutTextureCollectionIndex, TOptional< FName > & OutParameterName) const pure virtual
Implemented in FProxyMaterialCompiler.
GetTextureForExpression()
virtual bool FMaterialCompiler::GetTextureForExpression (int32 Index, int32 & OutTextureIndex, EMaterialSamplerType & OutSamplerType, TOptional< FName > & OutParameterName) const pure virtual
Implemented in FProxyMaterialCompiler.
GetTopCustomOutput()
virtual class UMaterialExpressionCustomOutput * FMaterialCompiler::GetTopCustomOutput () pure virtual
Implemented in FProxyMaterialCompiler.
GetType()
virtual EMaterialValueType FMaterialCompiler::GetType (int32 Code) pure virtual
Implemented in FProxyMaterialCompiler.
GetViewportUV()
virtual int32 FMaterialCompiler::GetViewportUV () pure virtual
Implemented in FProxyMaterialCompiler.
GetVolumeSampleConservativeDensity()
virtual int32 FMaterialCompiler::GetVolumeSampleConservativeDensity () pure virtual
Implemented in FProxyMaterialCompiler.
GIReplace()
virtual int32 FMaterialCompiler::GIReplace (int32 Direct, int32 StaticIndirect, int32 DynamicIndirect) pure virtual
Implemented in FProxyMaterialCompiler.
References Direct.
HsvToRgb()
virtual int32 FMaterialCompiler::HsvToRgb (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
If()
virtual int32 FMaterialCompiler::If (int32 A, int32 B, int32 AGreaterThanB, int32 AEqualsB, int32 ALessThanB, int32 Threshold) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
InstanceLocalBounds()
virtual int32 FMaterialCompiler::InstanceLocalBounds (int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
InvLerp()
virtual int32 FMaterialCompiler::InvLerp (int32 X, int32 Y, int32 A) pure virtual
Implemented in FProxyMaterialCompiler.
References A, X, and Y.
IsCurrentlyCompilingForPreviousFrame()
virtual bool FMaterialCompiler::IsCurrentlyCompilingForPreviousFrame () const inline virtual
Definition at line 796 of file MaterialCompiler.h.
IsDevelopmentFeatureEnabled()
virtual bool FMaterialCompiler::IsDevelopmentFeatureEnabled (const FName & FeatureName) const inline virtual
Reimplemented in FProxyMaterialCompiler.
Definition at line 797 of file MaterialCompiler.h.
IsFirstPerson()
virtual int32 FMaterialCompiler::IsFirstPerson () pure virtual
Implemented in FProxyMaterialCompiler.
IsInRuntimeVirtualTextureOutput()
virtual bool FMaterialCompiler::IsInRuntimeVirtualTextureOutput () const pure virtual
Implemented in FProxyMaterialCompiler.
IsLightmassCompiler()
bool FMaterialCompiler::IsLightmassCompiler () const inline
Definition at line 160 of file MaterialCompiler.h.
References GetCompilerType(), and Lightmass.
IsMaterialPropertyUsed()
virtual bool FMaterialCompiler::IsMaterialPropertyUsed (EMaterialProperty Property, int32 CodeChunkIdx) const pure virtual
Implemented in FProxyMaterialCompiler.
References Property.
IsMaterialProxyCompiler()
bool FMaterialCompiler::IsMaterialProxyCompiler () const inline
Definition at line 159 of file MaterialCompiler.h.
References GetCompilerType(), and MaterialProxy.
IsOrthographic()
virtual int32 FMaterialCompiler::IsOrthographic () pure virtual
Implemented in FProxyMaterialCompiler.
IsTangentSpaceNormal()
virtual bool FMaterialCompiler::IsTangentSpaceNormal () const pure virtual
Implemented in FProxyMaterialCompiler.
IsVertexInterpolatorBypass()
bool FMaterialCompiler::IsVertexInterpolatorBypass () const inline
Definition at line 172 of file MaterialCompiler.h.
References GetCompilerType(), and Lightmass.
Length()
virtual int32 FMaterialCompiler::Length (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Lerp()
virtual int32 FMaterialCompiler::Lerp (int32 X, int32 Y, int32 A) pure virtual
Implemented in FProxyMaterialCompiler.
References A, X, and Y.
LightmapUVs()
virtual int32 FMaterialCompiler::LightmapUVs () pure virtual
Implemented in FProxyMaterialCompiler.
LightmassReplace()
virtual int32 FMaterialCompiler::LightmassReplace (int32 Realtime, int32 Lightmass) pure virtual
Implemented in FProxyMaterialCompiler.
References Lightmass, and Realtime.
LightVector()
virtual int32 FMaterialCompiler::LightVector () pure virtual
Implemented in FProxyMaterialCompiler.
LocalPosition()
virtual int32 FMaterialCompiler::LocalPosition (EPositionIncludedOffsets IncludedOffsets, ELocalPositionOrigin OriginType) pure virtual
Implemented in FProxyMaterialCompiler.
Logarithm()
virtual int32 FMaterialCompiler::Logarithm (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Logarithm10()
virtual int32 FMaterialCompiler::Logarithm10 (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Logarithm2()
virtual int32 FMaterialCompiler::Logarithm2 (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
MapARPassthroughCameraUV()
virtual int32 FMaterialCompiler::MapARPassthroughCameraUV (int32 UV) pure virtual
Implemented in FProxyMaterialCompiler.
References UV.
MaterialBakingWorldPosition()
virtual int32 FMaterialCompiler::MaterialBakingWorldPosition () pure virtual
MaterialCache()
virtual int32 FMaterialCompiler::MaterialCache (int32 Default, int32 MaterialCache) pure virtual
Implemented in FProxyMaterialCompiler.
References Default, and MaterialCache().
Referenced by MaterialCache().
MaterialCacheTextureDescriptor()
virtual int32 FMaterialCompiler::MaterialCacheTextureDescriptor (uint32 LayerIndex) pure virtual
Implemented in FProxyMaterialCompiler.
Max()
virtual int32 FMaterialCompiler::Max (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
MeshPaintTextureCoordinateIndex()
virtual int32 FMaterialCompiler::MeshPaintTextureCoordinateIndex () pure virtual
Implemented in FProxyMaterialCompiler.
MeshPaintTextureDescriptor()
virtual int32 FMaterialCompiler::MeshPaintTextureDescriptor () pure virtual
Implemented in FProxyMaterialCompiler.
MeshPaintTextureReplace()
virtual int32 FMaterialCompiler::MeshPaintTextureReplace (int32 Invalid, int32 Valid) pure virtual
Implemented in FProxyMaterialCompiler.
References Invalid, and Valid.
Min()
virtual int32 FMaterialCompiler::Min (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
Modulo()
virtual int32 FMaterialCompiler::Modulo (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
Mul()
virtual int32 FMaterialCompiler::Mul (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
NaniteReplace()
virtual int32 FMaterialCompiler::NaniteReplace (int32 Default, int32 Nanite) pure virtual
Implemented in FProxyMaterialCompiler.
References Default.
NeuralOutput()
virtual int32 FMaterialCompiler::NeuralOutput (int32 ViewportUV, uint32 NeuralIndexType) pure virtual
Implemented in FProxyMaterialCompiler.
Noise()
virtual int32 FMaterialCompiler::Noise (int32 Position, EPositionOrigin PositionOrigin, float Scale, int32 Quality, uint8 NoiseFunction, bool bTurbulence, int32 Levels, float OutputMin, float OutputMax, float LevelScale, int32 FilterWidth, bool bTiling, uint32 RepeatSize) pure virtual
Implemented in FProxyMaterialCompiler.
References Position, and Scale.
Normalize()
virtual int32 FMaterialCompiler::Normalize (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
NumericParameter()
virtual int32 FMaterialCompiler::NumericParameter (EMaterialParameterType ParameterType, FName ParameterName, const UE::Shader::FValue & DefaultValue) pure virtual
Implemented in FProxyMaterialCompiler.
ObjectBounds()
virtual int32 FMaterialCompiler::ObjectBounds () pure virtual
Implemented in FProxyMaterialCompiler.
ObjectLocalBounds()
virtual int32 FMaterialCompiler::ObjectLocalBounds (int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
ObjectOrientation()
virtual int32 FMaterialCompiler::ObjectOrientation () pure virtual
Implemented in FProxyMaterialCompiler.
ObjectRadius()
virtual int32 FMaterialCompiler::ObjectRadius () pure virtual
Implemented in FProxyMaterialCompiler.
ObjectWorldPosition()
virtual int32 FMaterialCompiler::ObjectWorldPosition (EPositionOrigin OriginType) pure virtual
Implemented in FProxyMaterialCompiler.
ParticleColor()
virtual int32 FMaterialCompiler::ParticleColor () pure virtual
Implemented in FProxyMaterialCompiler.
ParticleDirection()
virtual int32 FMaterialCompiler::ParticleDirection () pure virtual
ParticleMacroUV()
virtual int32 FMaterialCompiler::ParticleMacroUV () pure virtual
Implemented in FProxyMaterialCompiler.
ParticleMotionBlurFade()
virtual int32 FMaterialCompiler::ParticleMotionBlurFade () pure virtual
ParticlePosition()
virtual int32 FMaterialCompiler::ParticlePosition (EPositionOrigin OriginType) pure virtual
Implemented in FProxyMaterialCompiler.
ParticleRadius()
virtual int32 FMaterialCompiler::ParticleRadius () pure virtual
Implemented in FProxyMaterialCompiler.
ParticleRandom()
virtual int32 FMaterialCompiler::ParticleRandom () pure virtual
ParticleRelativeTime()
virtual int32 FMaterialCompiler::ParticleRelativeTime () pure virtual
ParticleSize()
virtual int32 FMaterialCompiler::ParticleSize () pure virtual
ParticleSpeed()
virtual int32 FMaterialCompiler::ParticleSpeed () pure virtual
ParticleSpriteRotation()
virtual int32 FMaterialCompiler::ParticleSpriteRotation () pure virtual
ParticleSubUV()
virtual int32 FMaterialCompiler::ParticleSubUV (int32 TextureIndex, EMaterialSamplerType SamplerType, int32 MipValue0Index, int32 MipValue1Index, ETextureMipValueMode MipValueMode, bool bBlend) pure virtual
Implemented in FProxyMaterialCompiler.
ParticleSubUVProperty()
virtual int32 FMaterialCompiler::ParticleSubUVProperty (int32 PropertyIndex) pure virtual
Implemented in FProxyMaterialCompiler.
PathTracingBufferTextureLookup()
virtual int32 FMaterialCompiler::PathTracingBufferTextureLookup (int32 ViewportUV, uint32 PathTracingBufferTextureIndex) pure virtual
Implemented in FProxyMaterialCompiler.
PathTracingQualitySwitchReplace()
virtual int32 FMaterialCompiler::PathTracingQualitySwitchReplace (int32 Normal, int32 PathTraced) pure virtual
Implemented in FProxyMaterialCompiler.
References Normal.
PathTracingRayTypeSwitch()
virtual int32 FMaterialCompiler::PathTracingRayTypeSwitch (int32 Main, int32 Shadow, int32 IndirectDiffuse, int32 IndirectSpecular, int32 IndirectVolume) pure virtual
Implemented in FProxyMaterialCompiler.
References Main.
PerInstanceCustomData()
virtual int32 FMaterialCompiler::PerInstanceCustomData (int32 DataIndex, int32 DefaultValueIndex) pure virtual
Implemented in FProxyMaterialCompiler.
PerInstanceCustomData3Vector()
virtual int32 FMaterialCompiler::PerInstanceCustomData3Vector (int32 DataIndex, int32 DefaultValueIndex) pure virtual
Implemented in FProxyMaterialCompiler.
PerInstanceFadeAmount()
virtual int32 FMaterialCompiler::PerInstanceFadeAmount () pure virtual
Implemented in FProxyMaterialCompiler.
PerInstanceRandom()
virtual int32 FMaterialCompiler::PerInstanceRandom () pure virtual
Implemented in FProxyMaterialCompiler.
PeriodicHint()
virtual int32 FMaterialCompiler::PeriodicHint (int32 PeriodicCode) inline virtual
Reimplemented in FProxyMaterialCompiler.
Definition at line 247 of file MaterialCompiler.h.
PixelDepth()
virtual int32 FMaterialCompiler::PixelDepth () pure virtual
Implemented in FProxyMaterialCompiler.
PixelNormalWS()
virtual int32 FMaterialCompiler::PixelNormalWS () pure virtual
Implemented in FProxyMaterialCompiler.
PopFunction()
virtual FMaterialFunctionCompileState * FMaterialCompiler::PopFunction () pure virtual
Pops a function from the compiler's function stack, which indicates that compilation is leaving a function.
Implemented in FProxyMaterialCompiler.
PopMaterialAttribute()
virtual FGuid FMaterialCompiler::PopMaterialAttribute () pure virtual
Pops a MaterialAttributes property off the stack.
Called as we finish compiling a property through a MaterialAttributes pin.
Implemented in FProxyMaterialCompiler.
PopParameterOwner()
virtual FMaterialParameterInfo FMaterialCompiler::PopParameterOwner () pure virtual
Pops a parameter owner off the stack.
Called as we finish compiling each layer function of MaterialAttributeLayers.
Implemented in FProxyMaterialCompiler.
PopRuntimeVirtualTextureOutput()
virtual int32 FMaterialCompiler::PopRuntimeVirtualTextureOutput (uint8 AttributeMask) pure virtual
Implemented in FProxyMaterialCompiler.
PostVolumeUserFlagTestFunction()
virtual int32 FMaterialCompiler::PostVolumeUserFlagTestFunction (int32 Input) pure virtual
Implemented in FProxyMaterialCompiler.
References Input.
Power()
virtual int32 FMaterialCompiler::Power (int32 Base, int32 Exponent) pure virtual
Implemented in FProxyMaterialCompiler.
PrecomputedAOMask()
virtual int32 FMaterialCompiler::PrecomputedAOMask () pure virtual
Implemented in FProxyMaterialCompiler.
PreSkinnedLocalBounds()
virtual int32 FMaterialCompiler::PreSkinnedLocalBounds (int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
PreSkinnedNormal()
virtual int32 FMaterialCompiler::PreSkinnedNormal () pure virtual
Implemented in FProxyMaterialCompiler.
PreSkinnedPosition()
virtual int32 FMaterialCompiler::PreSkinnedPosition () pure virtual
Implemented in FProxyMaterialCompiler.
PushFunction()
virtual void FMaterialCompiler::PushFunction (FMaterialFunctionCompileState * FunctionState) pure virtual
Pushes a function onto the compiler's function stack, which indicates that compilation is entering a function.
Implemented in FProxyMaterialCompiler.
PushMaterialAttribute()
virtual void FMaterialCompiler::PushMaterialAttribute (const FGuid & InAttributeID) pure virtual
Pushes a material attributes property onto the stack.
Called as we begin compiling a property through a MaterialAttributes pin.
Implemented in FProxyMaterialCompiler.
PushParameterOwner()
virtual void FMaterialCompiler::PushParameterOwner (const FMaterialParameterInfo & InOwnerInfo) pure virtual
Pushes a parameter owner onto the stack.
Called as we begin compiling each layer function of MaterialAttributeLayers.
Implemented in FProxyMaterialCompiler.
PushRuntimeVirtualTextureOutput()
virtual int32 FMaterialCompiler::PushRuntimeVirtualTextureOutput () pure virtual
Implemented in FProxyMaterialCompiler.
RayTracingQualitySwitchReplace()
virtual int32 FMaterialCompiler::RayTracingQualitySwitchReplace (int32 Normal, int32 RayTraced) pure virtual
Implemented in FProxyMaterialCompiler.
References Normal.
RealTime()
virtual int32 FMaterialCompiler::RealTime (bool bPeriodic, float Period) pure virtual
Implemented in FProxyMaterialCompiler.
ReflectionAboutCustomWorldNormal()
virtual int32 FMaterialCompiler::ReflectionAboutCustomWorldNormal (int32 CustomWorldNormal, int32 bNormalizeCustomWorldNormal) pure virtual
ReflectionCapturePassSwitch()
virtual int32 FMaterialCompiler::ReflectionCapturePassSwitch (int32 Default, int32 Reflection) pure virtual
Implemented in FProxyMaterialCompiler.
References Default.
ReflectionVector()
virtual int32 FMaterialCompiler::ReflectionVector () pure virtual
Implemented in FProxyMaterialCompiler.
ReturnMaterialAttributes()
virtual int32 FMaterialCompiler::ReturnMaterialAttributes (int32 MaterialAttributes) pure virtual
Implemented in FProxyMaterialCompiler.
RgbToHsv()
virtual int32 FMaterialCompiler::RgbToHsv (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
RotateAboutAxis()
virtual int32 FMaterialCompiler::RotateAboutAxis (int32 NormalizedRotationAxisAndAngleIndex, int32 PositionOnAxisIndex, int32 PositionIndex) pure virtual
Implemented in FProxyMaterialCompiler.
RotateScaleOffsetTexCoords()
virtual int32 FMaterialCompiler::RotateScaleOffsetTexCoords (int32 TexCoordCodeIndex, int32 RotationScale, int32 Offset) pure virtual
Implemented in FProxyMaterialCompiler.
Round()
virtual int32 FMaterialCompiler::Round (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
SampleMaterialCache()
virtual int32 FMaterialCompiler::SampleMaterialCache (int32 TexCoordIndexLiteral) pure virtual
Implemented in FProxyMaterialCompiler.
SamplePhysicsField()
virtual int32 FMaterialCompiler::SamplePhysicsField (int32 PositionArg, EPositionOrigin PositionOrigin, const int32 OutputType, const int32 TargetIndex) pure virtual
Implemented in FProxyMaterialCompiler.
Saturate()
virtual int32 FMaterialCompiler::Saturate (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
ScalarBlueNoise()
virtual int32 FMaterialCompiler::ScalarBlueNoise () pure virtual
Implemented in FProxyMaterialCompiler.
ScalarParameter()
int32 FMaterialCompiler::ScalarParameter (FName ParameterName, float DefaultValue)
SceneColor()
virtual int32 FMaterialCompiler::SceneColor (int32 Offset, int32 ViewportUV, bool bUseOffset) pure virtual
Implemented in FProxyMaterialCompiler.
SceneDepth()
virtual int32 FMaterialCompiler::SceneDepth (int32 Offset, int32 ViewportUV, bool bUseOffset) pure virtual
Implemented in FProxyMaterialCompiler.
SceneDepthWithoutWater()
virtual int32 FMaterialCompiler::SceneDepthWithoutWater (int32 Offset, int32 ViewportUV, bool bUseOffset, float FallbackDepth) pure virtual
Implemented in FProxyMaterialCompiler.
SceneTextureLookup()
virtual int32 FMaterialCompiler::SceneTextureLookup (int32 ViewportUV, uint32 SceneTextureId, bool bFiltered, bool bClamped, bool bUnused) pure virtual
Implemented in FProxyMaterialCompiler.
SetBaseMaterialAttribute()
virtual void FMaterialCompiler::SetBaseMaterialAttribute (const FGuid & InAttributeID) pure virtual
Sets the bottom MaterialAttributes property of the stack.
Implemented in FProxyMaterialCompiler.
SetLocal()
virtual int32 FMaterialCompiler::SetLocal (const FName & LocalName, int32 Value) pure virtual
Implemented in FProxyMaterialCompiler.
References Value.
SetMaterialAttribute()
virtual int32 FMaterialCompiler::SetMaterialAttribute (int32 MaterialAttributes, int32 Value, const FGuid & AttributeID) pure virtual
Implemented in FProxyMaterialCompiler.
References Value.
SetMaterialProperty()
virtual void FMaterialCompiler::SetMaterialProperty (EMaterialProperty InProperty, EShaderFrequency OverrideShaderFrequency = SF_NumFrequencies, bool bUsePreviousFrameTime = false) pure virtual
Implemented in FProxyMaterialCompiler.
SetPotentiallyManipulateTexCoords()
virtual void FMaterialCompiler::SetPotentiallyManipulateTexCoords () pure virtual
Implemented in FProxyMaterialCompiler.
SetSubstrateMaterialExportType()
void FMaterialCompiler::SetSubstrateMaterialExportType (ESubstrateMaterialExport InSubstrateMaterialExport, ESubstrateMaterialExportContext InSubstrateMaterialExportContext, uint8 InSubstrateMaterialExportLegacyBlendMode) inline
Definition at line 162 of file MaterialCompiler.h.
References SubstrateMaterialExport, SubstrateMaterialExportContext, and SubstrateMaterialExportLegacyBlendMode.
ShadingModel()
virtual int32 FMaterialCompiler::ShadingModel (EMaterialShadingModel InSelectedShadingModel) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by SubstrateConversionFromLegacy().
ShadowReplace()
virtual int32 FMaterialCompiler::ShadowReplace (int32 Default, int32 Shadow) pure virtual
Implemented in FProxyMaterialCompiler.
References Default.
ShouldStopTranslating()
virtual bool FMaterialCompiler::ShouldStopTranslating () const pure virtual
Whether material translation should abort.
Implemented in FProxyMaterialCompiler.
Sign()
virtual int32 FMaterialCompiler::Sign (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Sine()
virtual int32 FMaterialCompiler::Sine (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
SkyAtmosphereAerialPerspective()
virtual int32 FMaterialCompiler::SkyAtmosphereAerialPerspective (int32 WorldPosition, EPositionOrigin PositionOrigin) pure virtual
Implemented in FProxyMaterialCompiler.
References WorldPosition().
SkyAtmosphereDistantLightScatteredLuminance()
virtual int32 FMaterialCompiler::SkyAtmosphereDistantLightScatteredLuminance () pure virtual
Implemented in FProxyMaterialCompiler.
SkyAtmosphereLightDirection()
virtual int32 FMaterialCompiler::SkyAtmosphereLightDirection (int32 LightIndex) pure virtual
Implemented in FProxyMaterialCompiler.
SkyAtmosphereLightDiskLuminance()
virtual int32 FMaterialCompiler::SkyAtmosphereLightDiskLuminance (int32 LightIndex, int32 OverrideAtmosphereLightDiscCosHalfApexAngle) pure virtual
Implemented in FProxyMaterialCompiler.
SkyAtmosphereLightIlluminance()
virtual int32 FMaterialCompiler::SkyAtmosphereLightIlluminance (int32 WorldPosition, EPositionOrigin PositionOrigin, int32 LightIndex) pure virtual
Implemented in FProxyMaterialCompiler.
References WorldPosition().
SkyAtmosphereLightIlluminanceOnGround()
virtual int32 FMaterialCompiler::SkyAtmosphereLightIlluminanceOnGround (int32 LightIndex) pure virtual
Implemented in FProxyMaterialCompiler.
SkyAtmosphereViewLuminance()
virtual int32 FMaterialCompiler::SkyAtmosphereViewLuminance (int32 WorldDirectionOverrideCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SkyLightEnvMapSample()
virtual int32 FMaterialCompiler::SkyLightEnvMapSample (int32 DirectionCodeChunk, int32 RoughnessCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SmoothStep()
virtual int32 FMaterialCompiler::SmoothStep (int32 X, int32 Y, int32 A) pure virtual
Implemented in FProxyMaterialCompiler.
References A, X, and Y.
Sobol()
virtual int32 FMaterialCompiler::Sobol (int32 Cell, int32 Index, int32 Seed) pure virtual
Implemented in FProxyMaterialCompiler.
References Cell, and Seed.
SparseVolumeTexture() [1/2]
int32 FMaterialCompiler::SparseVolumeTexture (USparseVolumeTexture * Texture, EMaterialSamplerType SamplerType) inline
Definition at line 421 of file MaterialCompiler.h.
References INDEX_NONE, SparseVolumeTexture(), and Texture().
SparseVolumeTexture() [2/2]
virtual int32 FMaterialCompiler::SparseVolumeTexture (USparseVolumeTexture * Texture, int32 & TextureReferenceIndex, EMaterialSamplerType SamplerType) pure virtual
Register a sparse volume texture to be sampled.
Parameters
Texture The sparse volume texture to sample.
TextureReferenceIndex Output the index of the texture in the referenced textures of the material.
SamplerType The sampler type
Returns
The code chunk index of the texture.
Implemented in FProxyMaterialCompiler.
References Texture().
Referenced by SparseVolumeTexture().
SparseVolumeTextureParameter()
virtual int32 FMaterialCompiler::SparseVolumeTextureParameter (FName ParameterName, USparseVolumeTexture * InDefaultTexture, int32 & TextureReferenceIndex, EMaterialSamplerType SamplerType) pure virtual
Register a parameterized sparse volume texture to be sampled.
Parameters
ParameterName The sparse volume texture parameter name.
InDefaultTexture The default static sparse volume texture to sample.
TextureReferenceIndex Output the index of the texture in the referenced textures of the material.
SamplerType The sampler type
Returns
The code chunk index of the texture parameter.
Implemented in FProxyMaterialCompiler.
SparseVolumeTextureSample()
virtual int32 FMaterialCompiler::SparseVolumeTextureSample (int32 SparseVolumeTextureIndex, int32 UVWIndex, int32 MipValue0Index, int32 MipValue1Index, int32 PhysicalTileDataIdxIndex, ETextureMipValueMode MipValueMode, ESamplerSourceMode SamplerSource) pure virtual
Implemented in FProxyMaterialCompiler.
SparseVolumeTextureSamplePageTable()
virtual int32 FMaterialCompiler::SparseVolumeTextureSamplePageTable (int32 SparseVolumeTextureIndex, int32 UVWIndex, int32 MipLevelIndex, ESamplerSourceMode SamplerSource, bool bIsManualLinearMipMapSecondSample) pure virtual
Sample a sparse volume texture page table.
Parameters
SparseVolumeTextureIndex The code chunk index of the texture.
UVWIndex The UVW coordinate at which to sample the texture.
MipLevelIndex The mip level at which to sample the texture.
SamplerSource The type of sampler to use to sample the texture.
bIsManualLinearMipMapSecondSample is true when this is the second/higher sample for manual linear mip map interpolation.
Returns
The code chunk index of the result of the texture sample.
Implemented in FProxyMaterialCompiler.
SparseVolumeTextureSamplePhysicalTileData()
virtual int32 FMaterialCompiler::SparseVolumeTextureSamplePhysicalTileData (int32 SparseVolumeTextureIndex, int32 VoxelCoordIndex, int32 PhysicalTileDataIdxIndex, bool bIsManualLinearMipMapSecondSample) pure virtual
Sample a sparse volume texture physical tile data texture.
Parameters
SparseVolumeTextureIndex The code chunk index of the texture.
VoxelCoordIndex The coordinate at which to sample the texture.
PhysicalTileDataIdxIndex The code chunk of the index (0 or 1) of the physical tile data texture to sample.
bIsManualLinearMipMapSecondSample is true when this is the second/higher sample for manual linear mip map interpolation.
Returns
The code chunk index of the result of the texture sample.
Implemented in FProxyMaterialCompiler.
SparseVolumeTextureUniform()
virtual int32 FMaterialCompiler::SparseVolumeTextureUniform (int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type) pure virtual
Register a uniform parameter required to be able to sample a sparse volume texture.
Parameters
TextureIndex The TextureReferenceIndex.
VectorIndex The index of the vector in the list of vector to bind.
Type The type of the vector.
Returns
The code chunk index of the uniform.
Implemented in FProxyMaterialCompiler.
SparseVolumeTextureUniformParameter()
virtual int32 FMaterialCompiler::SparseVolumeTextureUniformParameter (FName ParameterName, int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type) pure virtual
Register a uniform parameter required to be able to sample a parameterizes sparse volume texture.
Parameters
ParameterName The sparse volume texture parameter name.
TextureIndex The TextureReferenceIndex.
VectorIndex The index of the vector in the list of vector to bind.
Type The type of the vector.
Returns
The code chunk index of the uniform.
Implemented in FProxyMaterialCompiler.
SpeedTree()
virtual int32 FMaterialCompiler::SpeedTree (int32 GeometryArg, int32 WindArg, int32 LODArg, float BillboardThreshold, bool bAccurateWindVelocities, bool bExtraBend, int32 ExtraBendArg) pure virtual
Implemented in FProxyMaterialCompiler.
SphericalParticleOpacity()
virtual int32 FMaterialCompiler::SphericalParticleOpacity (int32 Density) pure virtual
Implemented in FProxyMaterialCompiler.
References Density.
SquareRoot()
virtual int32 FMaterialCompiler::SquareRoot (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
StaticBool()
virtual int32 FMaterialCompiler::StaticBool (bool Value) pure virtual
Implemented in FProxyMaterialCompiler.
References Value.
StaticBoolParameter()
virtual int32 FMaterialCompiler::StaticBoolParameter (FName ParameterName, bool bDefaultValue) pure virtual
Implemented in FProxyMaterialCompiler.
StaticComponentMask()
virtual int32 FMaterialCompiler::StaticComponentMask (int32 Vector, FName ParameterName, bool bDefaultR, bool bDefaultG, bool bDefaultB, bool bDefaultA) pure virtual
Implemented in FProxyMaterialCompiler.
References Vector.
StaticTerrainLayerWeight()
virtual int32 FMaterialCompiler::StaticTerrainLayerWeight (FName ParameterName, int32 Default, bool bTextureArray = false) pure virtual
Implemented in FProxyMaterialCompiler.
References Default.
Step()
virtual int32 FMaterialCompiler::Step (int32 Y, int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X, and Y.
Sub()
virtual int32 FMaterialCompiler::Sub (int32 A, int32 B) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
SubstrateAdd()
virtual int32 FMaterialCompiler::SubstrateAdd (int32 A, int32 B, int OperatorIndex, uint32 MaxDistanceFromLeaves) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
SubstrateAddParameterBlending()
virtual int32 FMaterialCompiler::SubstrateAddParameterBlending (int32 A, int32 B, int32 AMixWeight, const FString & SharedLocalBasisIndexMacro, int32 ABSDFNormalCodeChunk, int32 BBSDFNormalCodeChunk, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
SubstrateAddParameterBlendingBSDFCoverageToNormalMixCodeChunk()
virtual int32 FMaterialCompiler::SubstrateAddParameterBlendingBSDFCoverageToNormalMixCodeChunk (int32 ACodeChunk, int32 BCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateCompilationGetOperator()
virtual FSubstrateOperator & FMaterialCompiler::SubstrateCompilationGetOperator (FGuid SubstrateExpressionGuid) pure virtual
Return the operator information for a given expression.
Implemented in FProxyMaterialCompiler.
SubstrateCompilationGetOperatorFromIndex()
virtual FSubstrateOperator * FMaterialCompiler::SubstrateCompilationGetOperatorFromIndex (int32 OperatorIndex) pure virtual
Return the operator information for a given index.
Implemented in FProxyMaterialCompiler.
SubstrateCompilationInfoRegisterSharedLocalBasis() [1/2]
virtual FSubstrateRegisteredSharedLocalBasis FMaterialCompiler::SubstrateCompilationInfoRegisterSharedLocalBasis (int32 NormalCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateCompilationInfoRegisterSharedLocalBasis() [2/2]
virtual FSubstrateRegisteredSharedLocalBasis FMaterialCompiler::SubstrateCompilationInfoRegisterSharedLocalBasis (int32 NormalCodeChunk, int32 TangentCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateCompilationRegisterOperator()
virtual FSubstrateOperator & FMaterialCompiler::SubstrateCompilationRegisterOperator (int32 OperatorType, FGuid SubstrateExpressionGuid, FGuid ChildMaterialExpressionGuid, UMaterialExpression * Parent, FGuid SubstrateParentExpressionGuid, bool bUseParameterBlending = false) pure virtual
Register an operator of the tree representation the Substrate material and its topology.
Implemented in FProxyMaterialCompiler.
References Parent.
SubstrateCompilePreview()
virtual int32 FMaterialCompiler::SubstrateCompilePreview (int32 SubstrateDataCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateConversionFromLegacy()
virtual int32 FMaterialCompiler::SubstrateConversionFromLegacy (bool bHasDynamicShadingModels, int32 BaseColor, int32 Specular, int32 Metallic, int32 Roughness, int32 Anisotropy, int32 SubSurfaceColor, int32 SubSurfaceProfileId, int32 ClearCoat, int32 ClearCoatRoughness, int32 EmissiveColor, int32 Opacity, int32 ThinTranslucentTransmittanceColor, int32 ThinTranslucentSurfaceCoverage, int32 WaterScatteringCoefficients, int32 WaterAbsorptionCoefficients, int32 WaterPhaseG, int32 ColorScaleBehindWater, int32 ShadingModel, int32 Normal, int32 Tangent, const FString & SharedLocalBasisIndexMacro, int32 ClearCoat_Normal, int32 ClearCoat_Tangent, const FString & ClearCoat_SharedLocalBasisIndexMacro, int32 CustomTangent_Tangent, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References BaseColor, Normal, Roughness, ShadingModel(), Specular, and Tangent().
SubstrateCreateAndRegisterNullMaterial()
virtual int32 FMaterialCompiler::SubstrateCreateAndRegisterNullMaterial () pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateEyeBSDF()
virtual int32 FMaterialCompiler::SubstrateEyeBSDF (int32 DiffuseAlbedo, int32 Roughness, int32 IrisMask, int32 IrisDistance, int32 IrisNormal, int32 IrisPlaneNormal, int32 SSSProfileId, int32 EmissiveColor, int32 CorneaNormal, const FString & SharedLocalBasisIndexMacro, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References Roughness.
SubstrateHairBSDF()
virtual int32 FMaterialCompiler::SubstrateHairBSDF (int32 BaseColor, int32 Scatter, int32 Specular, int32 Roughness, int32 Backlit, int32 EmissiveColor, int32 Tangent, const FString & SharedLocalBasisIndexMacro, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References BaseColor, Roughness, Specular, and Tangent().
SubstrateHazinessToSecondaryRoughness()
virtual int32 FMaterialCompiler::SubstrateHazinessToSecondaryRoughness (int32 BaseRoughness, int32 Haziness, int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateHorizontalMixing()
virtual int32 FMaterialCompiler::SubstrateHorizontalMixing (int32 Background, int32 Foreground, int32 Mix, int OperatorIndex, uint32 MaxDistanceFromLeaves) pure virtual
Implemented in FProxyMaterialCompiler.
References Background.
SubstrateHorizontalMixingParameterBlending()
virtual int32 FMaterialCompiler::SubstrateHorizontalMixingParameterBlending (int32 Background, int32 Foreground, int32 HorizontalMixCodeChunk, int32 NormalMixCodeChunk, const FString & SharedLocalBasisIndexMacro, int32 BackgroundBSDFNormalCodeChunk, int32 ForegroundBSDFNormalCodeChunk, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References Background.
SubstrateHorizontalMixingParameterBlendingBSDFCoverageToNormalMixCodeChunk()
virtual int32 FMaterialCompiler::SubstrateHorizontalMixingParameterBlendingBSDFCoverageToNormalMixCodeChunk (int32 BackgroundCodeChunk, int32 ForegroundCodeChunk, int32 HorizontalMixCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateMetalnessToDiffuseAlbedoF0()
virtual int32 FMaterialCompiler::SubstrateMetalnessToDiffuseAlbedoF0 (int32 BaseColor, int32 Specular, int32 Metallic, int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
References BaseColor, and Specular.
SubstrateSelectParameterBlending()
virtual int32 FMaterialCompiler::SubstrateSelectParameterBlending (int32 A, int32 B, int32 SelectValue, const FString & SharedLocalBasisIndexMacro, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and B.
SubstrateSingleLayerWaterBSDF()
virtual int32 FMaterialCompiler::SubstrateSingleLayerWaterBSDF (int32 BaseColor, int32 Metallic, int32 Specular, int32 Roughness, int32 EmissiveColor, int32 TopMaterialOpacity, int32 WaterAlbedo, int32 WaterExtinction, int32 WaterPhaseG, int32 ColorScaleBehindWater, int32 Normal, const FString & SharedLocalBasisIndexMacro, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References BaseColor, Normal, Roughness, and Specular.
SubstrateSkipsOpacityEvaluation()
virtual bool FMaterialCompiler::SubstrateSkipsOpacityEvaluation () pure virtual
This is dedicated to skip evaluating any opacity input when a material instance toggles the translucent blend mode to opaque.
Implemented in FProxyMaterialCompiler.
SubstrateSlabBSDF()
virtual int32 FMaterialCompiler::SubstrateSlabBSDF (int32 DiffuseAlbedo, int32 F0, int32 F90, int32 Roughness, int32 Anisotropy, int32 SSSProfileId, int32 SSSMFP, int32 SSSMFPScale, int32 SSSPhaseAniso, int32 SSSType, int32 EmissiveColor, int32 SecondRoughness, int32 SecondRoughnessWeight, int32 SecondRoughnessAsSimpleClearCoat, int32 ClearCoatBottomNormal, int32 FuzzAmount, int32 FuzzColor, int32 FuzzRoughness, int32 Thickness, int32 GlintValue, int32 GlintUV, int32 SpecularProfileId, bool bIsAtTheBottomOfTopology, int32 Normal, int32 Tangent, const FString & SharedLocalBasisIndexMacro, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References Normal, Roughness, and Tangent().
SubstrateThicknessStackGetThicknessCode()
virtual int32 FMaterialCompiler::SubstrateThicknessStackGetThicknessCode (int32 Index) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateThicknessStackGetThicknessIndex()
virtual int32 FMaterialCompiler::SubstrateThicknessStackGetThicknessIndex () pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateThicknessStackPop()
virtual void FMaterialCompiler::SubstrateThicknessStackPop () pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateThicknessStackPush()
virtual int32 FMaterialCompiler::SubstrateThicknessStackPush (UMaterialExpression * Expression, FExpressionInput * Input) pure virtual
Implemented in FProxyMaterialCompiler.
References Input.
SubstrateThinFilm()
virtual int32 FMaterialCompiler::SubstrateThinFilm (int32 NormalCodeChunk, int32 SpecularColorCodeChunk, int32 EdgeSpecularColorCodeChunk, int32 ThicknessCodeChunk, int32 IORCodeChunk, int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateTransmittanceToMFP()
virtual int32 FMaterialCompiler::SubstrateTransmittanceToMFP (int32 TransmittanceColor, int32 DesiredThickness, int32 OutputIndex) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateTreeStackGetParentPathUniqueId()
virtual FGuid FMaterialCompiler::SubstrateTreeStackGetParentPathUniqueId () pure virtual
Returns the unique id of the Substrate tree path for the parent node of the current node position.
Implemented in FProxyMaterialCompiler.
SubstrateTreeStackGetPathUniqueId()
virtual FGuid FMaterialCompiler::SubstrateTreeStackGetPathUniqueId () pure virtual
Returns the unique id of the Substrate tree path, identifying the current node we have reached.
That is used as a unique identifier for each BSDF, recover their Substrate tree operator and apply some simplifications if required.
Implemented in FProxyMaterialCompiler.
SubstrateTreeStackPop()
virtual void FMaterialCompiler::SubstrateTreeStackPop () pure virtual
Pops a node node of the Substrate tree being walked.
Used when walking up the tree back to its root level.
Implemented in FProxyMaterialCompiler.
SubstrateTreeStackPush()
virtual FGuid FMaterialCompiler::SubstrateTreeStackPush (UMaterialExpression * Expression, uint32 InputIndex) pure virtual
Pushes a node of the Substrate tree being walked.
A node is caracterised by an expression and its input path taken.
Implemented in FProxyMaterialCompiler.
SubstrateUIBSDF()
virtual int32 FMaterialCompiler::SubstrateUIBSDF (int32 EmissiveColor, int32 Opacity, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateUnlitBSDF()
virtual int32 FMaterialCompiler::SubstrateUnlitBSDF (int32 EmissiveColor, int32 TransmittanceColor, int32 Normal, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References Normal.
SubstrateVerticalLayering()
virtual int32 FMaterialCompiler::SubstrateVerticalLayering (int32 Top, int32 Base, int32 Thickness, int OperatorIndex, uint32 MaxDistanceFromLeaves) pure virtual
Implemented in FProxyMaterialCompiler.
References Top.
SubstrateVerticalLayeringParameterBlending()
virtual int32 FMaterialCompiler::SubstrateVerticalLayeringParameterBlending (int32 Top, int32 Base, int32 Thickness, const FString & SharedLocalBasisIndexMacro, int32 TopBSDFNormalCodeChunk, int32 BaseBSDFNormalCodeChunk, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References Top.
SubstrateVerticalLayeringParameterBlendingBSDFCoverageToNormalMixCodeChunk()
virtual int32 FMaterialCompiler::SubstrateVerticalLayeringParameterBlendingBSDFCoverageToNormalMixCodeChunk (int32 TopCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateVolumetricFogCloudBSDF()
virtual int32 FMaterialCompiler::SubstrateVolumetricFogCloudBSDF (int32 Albedo, int32 Extinction, int32 EmissiveColor, int32 AmbientOcclusion, bool bEmissiveOnly) pure virtual
Implemented in FProxyMaterialCompiler.
SubstrateWeight()
virtual int32 FMaterialCompiler::SubstrateWeight (int32 A, int32 Weight, int OperatorIndex, uint32 MaxDistanceFromLeaves) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and Weight.
SubstrateWeightParameterBlending()
virtual int32 FMaterialCompiler::SubstrateWeightParameterBlending (int32 A, int32 Weight, FSubstrateOperator * PromoteToOperator) pure virtual
Implemented in FProxyMaterialCompiler.
References A, and Weight.
Switch()
virtual int32 FMaterialCompiler::Switch (int32 SwitchValueInput, int32 DefaultInput, TArray< int32 > & CompiledInputs) pure virtual
Implemented in FProxyMaterialCompiler.
Tangent()
virtual int32 FMaterialCompiler::Tangent (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
Referenced by SubstrateConversionFromLegacy(), SubstrateHairBSDF(), and SubstrateSlabBSDF().
TemporalSobol()
virtual int32 FMaterialCompiler::TemporalSobol (int32 Index, int32 Seed) pure virtual
Implemented in FProxyMaterialCompiler.
References Seed.
Texture() [1/2]
int32 FMaterialCompiler::Texture (UTexture * InTexture, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource = SSM_FromTextureAsset) inline
Definition at line 415 of file MaterialCompiler.h.
References INDEX_NONE, and Texture.
Texture() [2/2]
virtual int32 FMaterialCompiler::Texture (UTexture * Texture, int32 & TextureReferenceIndex, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource = SSM_FromTextureAsset, ETextureMipValueMode MipValueMode = TMVM_None) pure virtual
Implemented in FProxyMaterialCompiler.
References Texture().
Referenced by SparseVolumeTexture(), SparseVolumeTexture(), Texture(), and TextureSample().
TextureCollection() [1/2]
int32 FMaterialCompiler::TextureCollection (UTextureCollection * InTextureCollection) inline
Definition at line 457 of file MaterialCompiler.h.
References INDEX_NONE, and TextureCollection().
TextureCollection() [2/2]
virtual int32 FMaterialCompiler::TextureCollection (UTextureCollection * TextureCollection, int32 & TextureCollectionReferenceIndex) pure virtual
Implemented in FProxyMaterialCompiler.
References TextureCollection().
Referenced by TextureCollection(), and TextureCollection().
TextureCollectionCount()
virtual int32 FMaterialCompiler::TextureCollectionCount (int32 InTextureCollectionCodeIndex) pure virtual
Implemented in FProxyMaterialCompiler.
TextureCollectionParameter() [1/2]
int32 FMaterialCompiler::TextureCollectionParameter (FName ParameterName, UTextureCollection * DefaultValue) inline
Definition at line 463 of file MaterialCompiler.h.
References INDEX_NONE, and TextureCollectionParameter().
TextureCollectionParameter() [2/2]
virtual int32 FMaterialCompiler::TextureCollectionParameter (FName ParameterName, UTextureCollection * DefaultValue, int32 & TextureCollectionReferenceIndex) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by TextureCollectionParameter().
TextureCoordinate()
virtual int32 FMaterialCompiler::TextureCoordinate (uint32 CoordinateIndex, bool UnMirrorU, bool UnMirrorV) pure virtual
Implemented in FProxyMaterialCompiler.
TextureDecalDerivative()
virtual int32 FMaterialCompiler::TextureDecalDerivative (bool bDDY) pure virtual
Implemented in FProxyMaterialCompiler.
TextureDecalMipmapLevel()
virtual int32 FMaterialCompiler::TextureDecalMipmapLevel (int32 TextureSizeInput) pure virtual
Implemented in FProxyMaterialCompiler.
TextureFromCollection()
virtual int32 FMaterialCompiler::TextureFromCollection (int32 TextureCollectionCodeIndex, int32 IndexIntoCollectionCodeIndex, EMaterialValueType ResultTextureType) pure virtual
Implemented in FProxyMaterialCompiler.
TextureParameter() [1/2]
int32 FMaterialCompiler::TextureParameter (FName ParameterName, UTexture * DefaultTexture, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource = SSM_FromTextureAsset) inline
Definition at line 445 of file MaterialCompiler.h.
References INDEX_NONE, and TextureParameter().
TextureParameter() [2/2]
virtual int32 FMaterialCompiler::TextureParameter (FName ParameterName, UTexture * DefaultTexture, int32 & TextureReferenceIndex, EMaterialSamplerType SamplerType, ESamplerSourceMode SamplerSource = SSM_FromTextureAsset) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by TextureParameter().
TextureProperty()
virtual int32 FMaterialCompiler::TextureProperty (int32 InTexture, EMaterialExposedTextureProperty Property) pure virtual
Implemented in FProxyMaterialCompiler.
References Property.
TextureSample()
virtual int32 FMaterialCompiler::TextureSample (int32 Texture, int32 Coordinate, enum EMaterialSamplerType SamplerType, int32 MipValue0Index = INDEX_NONE, int32 MipValue1Index = INDEX_NONE, ETextureMipValueMode MipValueMode = TMVM_None, ESamplerSourceMode SamplerSource = SSM_FromTextureAsset, ETextureGatherMode GatherMode = TGM_None, int32 TextureReferenceIndex = INDEX_NONE, bool AutomaticViewMipBias = false, bool AdaptiveVirtualTexture = false, bool EnableFeedback = true) pure virtual
Implemented in FProxyMaterialCompiler.
References INDEX_NONE, and Texture().
TextureStreamingInfo()
virtual int32 FMaterialCompiler::TextureStreamingInfo (int32 TextureReferenceIndex, int32 TextureIndex, int32 CoordinateIndex) pure virtual
Implemented in FProxyMaterialCompiler.
TransformFromPeriodicWorldPosition()
int32 FMaterialCompiler::TransformFromPeriodicWorldPosition (EMaterialCommonBasis DestCoordBasis, int TileScaleIndex, int32 A) inline
Definition at line 555 of file MaterialCompiler.h.
References A, MCB_PeriodicWorld, FTransformParameters::PeriodicWorldTileSizeIndex, TransformFromPeriodicWorldPosition(), and TransformPosition().
Referenced by TransformFromPeriodicWorldPosition().
TransformNormalFromRequestedBasisToWorld()
virtual int32 FMaterialCompiler::TransformNormalFromRequestedBasisToWorld (int32 NormalCodeChunk) pure virtual
Implemented in FProxyMaterialCompiler.
TransformPosition() [1/2]
virtual int32 FMaterialCompiler::TransformPosition (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, FTransformParameters & Parameters, int32 A) pure virtual
Implemented in FProxyMaterialCompiler.
References A.
Referenced by TransformFromPeriodicWorldPosition(), TransformPosition(), and TransformToPeriodicWorldPosition().
TransformPosition() [2/2]
int32 FMaterialCompiler::TransformPosition (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, int32 A) inline
Definition at line 549 of file MaterialCompiler.h.
References A, and TransformPosition().
TransformToPeriodicWorldPosition()
int32 FMaterialCompiler::TransformToPeriodicWorldPosition (EMaterialCommonBasis SourceCoordBasis, int TileScaleIndex, int32 A) inline
Definition at line 562 of file MaterialCompiler.h.
References A, MCB_PeriodicWorld, FTransformParameters::PeriodicWorldTileSizeIndex, TransformPosition(), and TransformToPeriodicWorldPosition().
Referenced by TransformToPeriodicWorldPosition().
TransformVector() [1/2]
virtual int32 FMaterialCompiler::TransformVector (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, FTransformParameters & Parameters, int32 A) pure virtual
Implemented in FProxyMaterialCompiler.
References A.
Referenced by TransformVector().
TransformVector() [2/2]
int32 FMaterialCompiler::TransformVector (EMaterialCommonBasis SourceCoordBasis, EMaterialCommonBasis DestCoordBasis, int32 A) inline
Definition at line 544 of file MaterialCompiler.h.
References A, and TransformVector().
Truncate()
virtual int32 FMaterialCompiler::Truncate (int32 X) pure virtual
Implemented in FProxyMaterialCompiler.
References X.
TruncateLWC()
virtual int32 FMaterialCompiler::TruncateLWC (int32 Code) pure virtual
Implemented in FProxyMaterialCompiler.
TwoSidedSign()
virtual int32 FMaterialCompiler::TwoSidedSign () pure virtual
Implemented in FProxyMaterialCompiler.
ValidCast()
virtual int32 FMaterialCompiler::ValidCast (int32 Code, EMaterialValueType DestType) pure virtual
Casts the passed in code to DestType, or generates a compile error if the cast is not valid.
This will truncate a type (float4 -> float3) but not add components (float2 -> float3), however a float1 can be cast to any float type by replication.
Implemented in FProxyMaterialCompiler.
VectorNoise()
virtual int32 FMaterialCompiler::VectorNoise (int32 Position, EPositionOrigin PositionOrigin, int32 Quality, uint8 NoiseFunction, bool bTiling, uint32 RepeatSize) pure virtual
Implemented in FProxyMaterialCompiler.
References Position.
VectorParameter()
int32 FMaterialCompiler::VectorParameter (FName ParameterName, const FLinearColor & DefaultValue)
VertexColor()
virtual int32 FMaterialCompiler::VertexColor () pure virtual
Implemented in FProxyMaterialCompiler.
VertexInterpolator()
virtual int32 FMaterialCompiler::VertexInterpolator (uint32 InterpolatorIndex) pure virtual
VertexNormal()
virtual int32 FMaterialCompiler::VertexNormal () pure virtual
Implemented in FProxyMaterialCompiler.
VertexTangent()
virtual int32 FMaterialCompiler::VertexTangent () pure virtual
Implemented in FProxyMaterialCompiler.
ViewProperty()
virtual int32 FMaterialCompiler::ViewProperty (EMaterialExposedViewProperty Property, bool InvProperty = false) pure virtual
Implemented in FProxyMaterialCompiler.
References Property.
VirtualTexture() [1/2]
int32 FMaterialCompiler::VirtualTexture (URuntimeVirtualTexture * InTexture, int32 TextureLayerIndex, int32 PageTableLayerIndex, EMaterialSamplerType SamplerType) inline
Definition at line 427 of file MaterialCompiler.h.
References INDEX_NONE, and VirtualTexture().
VirtualTexture() [2/2]
virtual int32 FMaterialCompiler::VirtualTexture (URuntimeVirtualTexture * InTexture, int32 TextureLayerIndex, int32 PageTableLayerIndex, int32 & TextureReferenceIndex, EMaterialSamplerType SamplerType) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by VirtualTexture().
VirtualTextureCustomData()
virtual int32 FMaterialCompiler::VirtualTextureCustomData () pure virtual
Implemented in FProxyMaterialCompiler.
VirtualTextureParameter() [1/2]
int32 FMaterialCompiler::VirtualTextureParameter (FName ParameterName, URuntimeVirtualTexture * DefaultValue, int32 TextureLayerIndex, int32 PageTableLayerIndex, EMaterialSamplerType SamplerType) inline
Definition at line 433 of file MaterialCompiler.h.
References INDEX_NONE, and VirtualTextureParameter().
VirtualTextureParameter() [2/2]
virtual int32 FMaterialCompiler::VirtualTextureParameter (FName ParameterName, URuntimeVirtualTexture * DefaultValue, int32 TextureLayerIndex, int32 PageTableLayerIndex, int32 & TextureReferenceIndex, EMaterialSamplerType SamplerType) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by VirtualTextureParameter().
VirtualTextureUniform() [1/2]
virtual int32 FMaterialCompiler::VirtualTextureUniform (FName ParameterName, int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type) pure virtual
Implemented in FProxyMaterialCompiler.
VirtualTextureUniform() [2/2]
virtual int32 FMaterialCompiler::VirtualTextureUniform (int32 TextureIndex, int32 VectorIndex, UE::Shader::EValueType Type) pure virtual
Implemented in FProxyMaterialCompiler.
VirtualTextureUnpack()
virtual int32 FMaterialCompiler::VirtualTextureUnpack (int32 CodeIndex0, int32 CodeIndex1, int32 CodeIndex2, int32 P0, EVirtualTextureUnpackType UnpackType) pure virtual
Implemented in FProxyMaterialCompiler.
VirtualTextureWorldToUV()
virtual int32 FMaterialCompiler::VirtualTextureWorldToUV (int32 WorldPositionIndex, int32 P0, int32 P1, int32 P2, EPositionOrigin PositionOrigin) pure virtual
Implemented in FProxyMaterialCompiler.
WorldPosition()
virtual int32 FMaterialCompiler::WorldPosition (EWorldPositionIncludedOffsets WorldPositionIncludedOffsets) pure virtual
Implemented in FProxyMaterialCompiler.
Referenced by AtmosphericFogColor(), SkyAtmosphereAerialPerspective(), and SkyAtmosphereLightIlluminance().
Field Documentation
SubstrateMaterialExport
ESubstrateMaterialExport FMaterialCompiler::SubstrateMaterialExport = SME_None private
Definition at line 811 of file MaterialCompiler.h.
Referenced by GetSubstrateMaterialExportType(), and SetSubstrateMaterialExportType().
SubstrateMaterialExportContext
ESubstrateMaterialExportContext FMaterialCompiler::SubstrateMaterialExportContext = SMEC_Opaque private
Definition at line 812 of file MaterialCompiler.h.
Referenced by GetSubstrateMaterialExportContext(), and SetSubstrateMaterialExportType().
SubstrateMaterialExportLegacyBlendMode
uint8 FMaterialCompiler::SubstrateMaterialExportLegacyBlendMode = 0 private
Definition at line 813 of file MaterialCompiler.h.
Referenced by GetSubstrateMaterialExportLegacyBlendMode(), and SetSubstrateMaterialExportType().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialCompiler.h