Unreal Engine 5.6 C++ API: TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > Class Template Reference
TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > Class Template Reference
A Map of keys to value, implemented as a sorted TArray of TPairs.
#include "SortedMap.h"
Data Structures
struct FKeyForward
Forwards sorting into Key of pair.
class TBaseIterator
The base of TSortedMap iterators.
class TBaseReverseIterator
The base of TSortedMap reverse iterators.
class TConstIterator
Const map iterator.
class TConstKeyIterator
Iterates over values associated with a specified key in a const map.
class TConstReverseIterator
Const map iterator.
class TIterator
Map iterator.
class TKeyIterator
Iterates over values associated with a specified key in a map.
class TReverseIterator
Reverse Map iterator.
Public Types
typedef TPair< KeyType, ValueType > ElementType
using IntrusiveUnsetOptionalStateType = TSortedMap
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
typedef InKeyType KeyType
typedef ElementArrayType::RangedForConstIteratorType RangedForConstIteratorType
typedef ElementArrayType::RangedForIteratorType RangedForIteratorType
Ranged For iterators.
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
typedef InValueType ValueType
Public Member Functions
TSortedMap ()=default
TSortedMap (const TSortedMap &)=default
template<typename OtherArrayAllocator>
TSortedMap (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > &Other)
Constructor for copying elements from a TSortedMap with a different ArrayAllocator.
TSortedMap (FIntrusiveUnsetOptionalState Tag)
TSortedMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Constructor which gets its elements from a native initializer list.
TSortedMap (TSortedMap &&)=default
template<typename OtherArrayAllocator>
TSortedMap (TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > &&Other)
Constructor for moving elements from a TSortedMap with a different ArrayAllocator.
FORCEINLINE ValueType & Add (const KeyType &InKey)
Sets a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Sets the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
template<typename OtherArrayAllocator, typename OtherSortPredicate>
void Append (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, OtherSortPredicate > &OtherMap)
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
template<typename OtherArrayAllocator, typename OtherSortPredicate>
void Append (TSortedMap< KeyType, ValueType, OtherArrayAllocator, OtherSortPredicate > &&OtherMap)
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
FORCEINLINE RangedForIteratorType begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE RangedForConstIteratorType begin () const
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Checks if map contains the specified key.
FORCEINLINE void CountBytes (FArchive &Ar) const
Tracks the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (KeyInitType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (KeyInitType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
template<typename InitKeyType = KeyType>
ValueType & Emplace (InitKeyType &&InKey)
Sets a default value associated with a key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map, potentially leaving space allocated for an expected number of elements about to be added.
FORCEINLINE RangedForIteratorType end ()
FORCEINLINE RangedForConstIteratorType end () const
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Returns the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
FORCEINLINE ValueType FindAndRemoveChecked (KeyConstPointerType Key)
Finds a pair with the specified key, removes it from the map, and returns the value part of the pair.
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Returns a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
const KeyType * FindKey (ValueInitType Value) const
Returns the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Returns the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Returns the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Returns the value associated with a specified key.
template<typename Allocator>
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generates an array from the keys in this map.
template<typename Allocator>
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generates an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container.
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Returns the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
FORCEINLINE bool operator!= (const TSortedMap &Other) const
Inequality operator.
TSortedMap & operator= (const TSortedMap &)=default
template<typename OtherArrayAllocator>
TSortedMap & operator= (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > &Other)
Assignment operator for copying elements from a TSortedMap with a different ArrayAllocator.
TSortedMap & operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Assignment operator which gets its elements from a native initializer list.
TSortedMap & operator= (TSortedMap &&)=default
template<typename OtherArrayAllocator>
TSortedMap & operator= (TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > &&Other)
Assignment operator for moving elements from a TSortedMap with a different ArrayAllocator.
FORCEINLINE bool operator== (const TSortedMap &Other) const
Equality operator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE ValueType & operator[] (KeyConstPointerType Key)
FORCEINLINE const ValueType & operator[] (KeyConstPointerType Key) const
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Removes all value associations for a key.
FORCEINLINE bool RemoveAndCopyValue (KeyInitType Key, ValueType &OutRemovedValue)
Removes the pair with the specified key and copies the value that was removed to the ref parameter.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
typedef TArray< ElementType, ArrayAllocator > ElementArrayType
Private Member Functions
template<typename InitKeyType>
FORCEINLINE ElementType * AllocateMemoryForEmplace (InitKeyType &&InKey)
Allocates raw memory for emplacing.
FORCEINLINE int32 FindIndex (KeyConstPointerType Key) const
Find index of key.
template<typename ArgType>
FORCEINLINE ValueType & FindOrAddImpl (ArgType &&Key)
Implementation of find and add.
Private Attributes
ElementArrayType Pairs
An array of the key-value pairs in the map.
Friends
template<typename OtherKeyType, typename OtherValueType, typename OtherArrayAllocator, typename OtherSortPredicate>
class TSortedMap
struct TSortedMapPrivateFriend
Detailed Description
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate>
class TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >
A Map of keys to value, implemented as a sorted TArray of TPairs.
It has a mostly identical interface to TMap and is designed as a drop in replacement. Keys must be unique, there is no equivalent sorted version of TMultiMap. It uses half as much memory as TMap, but adding and removing elements is O(n), and finding is O(Log n). In practice it is faster than TMap for low element counts, and slower as n increases, This map is always kept sorted by the key type so cannot be sorted manually.
Definition at line 19 of file SortedMap.h.
Member Typedef Documentation
ElementArrayType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef TArray<ElementType, ArrayAllocator> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::ElementArrayType private
Definition at line 549 of file SortedMap.h.
ElementType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef TPair<KeyType, ValueType> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::ElementType
Definition at line 30 of file SortedMap.h.
IntrusiveUnsetOptionalStateType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> using TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::IntrusiveUnsetOptionalStateType = TSortedMap
Definition at line 66 of file SortedMap.h.
KeyConstPointerType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef TTypeTraits<KeyType>::ConstPointerType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::KeyConstPointerType
Definition at line 27 of file SortedMap.h.
KeyInitType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef TTypeTraits<KeyType>::ConstInitType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::KeyInitType
Definition at line 28 of file SortedMap.h.
KeyType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef InKeyType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::KeyType
Definition at line 25 of file SortedMap.h.
RangedForConstIteratorType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef ElementArrayType::RangedForConstIteratorType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::RangedForConstIteratorType
Definition at line 896 of file SortedMap.h.
RangedForIteratorType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef ElementArrayType::RangedForIteratorType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::RangedForIteratorType
Ranged For iterators.
Unlike normal TMap these are not the same as the normal iterator for performance reasons
Definition at line 895 of file SortedMap.h.
ValueInitType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef TTypeTraits<ValueType>::ConstInitType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::ValueInitType
Definition at line 29 of file SortedMap.h.
ValueType
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> typedef InValueType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::ValueType
Definition at line 26 of file SortedMap.h.
Constructor & Destructor Documentation
TSortedMap() [1/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap () nodiscard default
TSortedMap() [2/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap (TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > &&) nodiscard default
TSortedMap() [3/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap (const TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > &) nodiscard default
TSortedMap() [4/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherArrayAllocator> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap (TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > && Other) inline nodiscard
Constructor for moving elements from a TSortedMap with a different ArrayAllocator.
Definition at line 40 of file SortedMap.h.
TSortedMap() [5/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherArrayAllocator> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > & Other) inline nodiscard
Constructor for copying elements from a TSortedMap with a different ArrayAllocator.
Definition at line 47 of file SortedMap.h.
TSortedMap() [6/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList) inline nodiscard
Constructor which gets its elements from a native initializer list.
Definition at line 53 of file SortedMap.h.
TSortedMap() [7/7]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 68 of file SortedMap.h.
Member Function Documentation
Add() [1/6]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add (const KeyType & InKey) inline
Sets a default value associated with a key.
Parameters
InKey The key to associate the value with.
Returns
A reference to the value as stored in the map. The reference is only valid until the next change to any key in the map.
Definition at line 199 of file SortedMap.h.
Add() [2/6]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add (const KeyType & InKey, const ValueType & InValue) inline
Sets the value associated with a key.
Parameters
InKey The key to associate the value with.
InValue The value to associate with the key.
Returns
A reference to the value as stored in the map (only valid until the next change to any key in the map).
Definition at line 188 of file SortedMap.h.
Referenced by UE::Math::TVector< T >::ToCompactText(), FErrorTrackerWorstAnimation::ToText(), FErrorTrackerWorstBone::ToText(), FTabId::ToText(), and UE::Math::TVector< T >::ToText().
Add() [3/6]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add (const KeyType & InKey, ValueType && InValue) inline
Definition at line 189 of file SortedMap.h.
Add() [4/6]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add (KeyType && InKey) inline
Definition at line 200 of file SortedMap.h.
Add() [5/6]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add (KeyType && InKey, const ValueType & InValue) inline
Definition at line 190 of file SortedMap.h.
Add() [6/6]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add (KeyType && InKey, ValueType && InValue) inline
Definition at line 191 of file SortedMap.h.
AllocateMemoryForEmplace()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename InitKeyType> FORCEINLINE ElementType * TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::AllocateMemoryForEmplace (InitKeyType && InKey) inline private
Allocates raw memory for emplacing.
Definition at line 571 of file SortedMap.h.
Referenced by TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Emplace(), and TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Emplace().
Append() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherArrayAllocator, typename OtherSortPredicate> void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Append (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, OtherSortPredicate > & OtherMap) inline
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
Parameters
OtherMap The other map of items to add.
Definition at line 500 of file SortedMap.h.
Append() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherArrayAllocator, typename OtherSortPredicate> void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Append (TSortedMap< KeyType, ValueType, OtherArrayAllocator, OtherSortPredicate > && OtherMap) inline
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
Parameters
OtherMap The other map of items to move the elements from.
Definition at line 483 of file SortedMap.h.
begin() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE RangedForIteratorType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::begin () inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 903 of file SortedMap.h.
begin() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE RangedForConstIteratorType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::begin () const inline nodiscard
Definition at line 904 of file SortedMap.h.
Contains()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Contains (KeyConstPointerType Key) const inline nodiscard
Checks if map contains the specified key.
Parameters
Key The key to check for.
Returns
true if the map contains the key.
Definition at line 381 of file SortedMap.h.
CountBytes()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CountBytes (FArchive & Ar) const inline
Tracks the container's memory use through an archive.
Definition at line 176 of file SortedMap.h.
CreateConstIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TConstIterator TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateConstIterator () const inline nodiscard
Creates a const iterator over all the pairs in this map.
Definition at line 877 of file SortedMap.h.
Referenced by TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator::TConstIterator(), and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::TConstKeyIterator().
CreateConstKeyIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TConstKeyIterator TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateConstKeyIterator (KeyInitType InKey) const inline nodiscard
Creates a const iterator over the values associated with a specified key in a map.
This will be at most one value because keys must be unique
Definition at line 889 of file SortedMap.h.
CreateIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TIterator TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateIterator () inline nodiscard
Creates an iterator over all the pairs in this map.
Definition at line 871 of file SortedMap.h.
Referenced by TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TIterator::TIterator(), and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::TKeyIterator().
CreateKeyIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TKeyIterator TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateKeyIterator (KeyInitType InKey) inline nodiscard
Creates an iterator over the values associated with a specified key in a map.
This will be at most one value because keys must be unique
Definition at line 883 of file SortedMap.h.
Dump()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Dump (FOutputDevice & Ar) inline
Describes the map's contents through an output device.
Parameters
Ar The output device to describe the map's contents through.
Definition at line 435 of file SortedMap.h.
Emplace() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename InitKeyType = KeyType> ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Emplace (InitKeyType && InKey) inline
Sets a default value associated with a key.
Parameters
InKey The key to associate the value with.
Returns
A reference to the value as stored in the map (only valid until the next change to any key in the map).
Definition at line 226 of file SortedMap.h.
Emplace() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename InitKeyType = KeyType, typename InitValueType = ValueType> ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Emplace (InitKeyType && InKey, InitValueType && InValue) inline
Sets the value associated with a key.
Parameters
InKey - The key to associate the value with.
InValue - The value to associate with the key.
Returns
A reference to the value as stored in the map (only valid until the next change to any key in the map).
Definition at line 210 of file SortedMap.h.
Referenced by TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add(), and TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Add().
Empty()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Empty (int32 ExpectedNumElements = 0) inline
Removes all elements from the map, potentially leaving space allocated for an expected number of elements about to be added.
Parameters
ExpectedNumElements The number of elements about to be added to the set.
Definition at line 124 of file SortedMap.h.
end() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE RangedForIteratorType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::end () inline nodiscard
Definition at line 905 of file SortedMap.h.
end() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE RangedForConstIteratorType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::end () const inline nodiscard
Definition at line 906 of file SortedMap.h.
Find() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType * TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Find (KeyConstPointerType Key) inline nodiscard
Returns the value associated with a specified key.
Parameters
Key The key to search for.
Returns
A pointer to the value associated with the specified key, or nullptr if the key isn't contained in this map. The pointer (only valid until the next change to any key in the map).
Definition at line 279 of file SortedMap.h.
Find() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE const ValueType * TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Find (KeyConstPointerType Key) const inline nodiscard
Definition at line 291 of file SortedMap.h.
FindAndRemoveChecked()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindAndRemoveChecked (KeyConstPointerType Key) inline
Finds a pair with the specified key, removes it from the map, and returns the value part of the pair.
If no pair was found, an exception is thrown.
Parameters
Key The key to search for
Returns
Whether or not the key was found
Definition at line 467 of file SortedMap.h.
FindArbitraryElement() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> ElementType * TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindArbitraryElement () inline nodiscard
Finds any pair in the map and returns a pointer to it.
Callers should not depend on particular patterns in the behaviour of this function.
Returns
A pointer to an arbitrary pair, or nullptr if the container is empty.
Definition at line 364 of file SortedMap.h.
Referenced by TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindArbitraryElement().
FindArbitraryElement() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> const ElementType * TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindArbitraryElement () const inline nodiscard
Definition at line 370 of file SortedMap.h.
FindChecked() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindChecked (KeyConstPointerType Key) inline nodiscard
Returns a reference to the value associated with a specified key.
Parameters
Key The key to search for.
Returns
The value associated with the specified key, or triggers an assertion if the key does not exist.
Definition at line 312 of file SortedMap.h.
Referenced by TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::operator[](), and TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::operator[]().
FindChecked() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE const ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindChecked (KeyConstPointerType Key) const inline nodiscard
Definition at line 319 of file SortedMap.h.
FindIndex()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE int32 TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindIndex (KeyConstPointerType Key) const inline nodiscard private
Find index of key.
Definition at line 564 of file SortedMap.h.
Referenced by TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::TConstKeyIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::TKeyIterator(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Find(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindAndRemoveChecked(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Remove(), and TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::RemoveAndCopyValue().
FindKey()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> const KeyType * TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindKey (ValueInitType Value) const inline nodiscard
Returns the key associated with the specified value.
The time taken is O(N) in the number of pairs.
Parameters
Value The value to search for.
Returns
A pointer to the key associated with the specified value, or nullptr if the value isn't contained in this map (only valid until the next change to any key in the map).
Definition at line 261 of file SortedMap.h.
FindOrAdd() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindOrAdd (const KeyType & Key) inline
Returns the value associated with a specified key, or if none exists, adds a value using the default constructor.
Parameters
Key The key to search for.
Returns
A reference to the value associated with the specified key.
Definition at line 303 of file SortedMap.h.
FindOrAdd() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindOrAdd (KeyType && Key) inline
Definition at line 304 of file SortedMap.h.
FindOrAddImpl()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename ArgType> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindOrAddImpl (ArgType && Key) inline nodiscard private
Implementation of find and add.
Definition at line 553 of file SortedMap.h.
Referenced by TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindOrAdd(), and TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::FindOrAdd().
FindRef() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindRef (KeyConstPointerType Key) const inline nodiscard
Returns the value associated with a specified key.
Parameters
Key The key to search for.
Returns
The value associated with the specified key, or the default value for the ValueType if the key isn't contained in this map.
Definition at line 332 of file SortedMap.h.
FindRef() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindRef (KeyConstPointerType Key, ValueType DefaultValue) const inline nodiscard
Returns the value associated with a specified key.
Parameters
Key The key to search for.
DefaultValue The fallback value if the key is not found.
Returns
The value associated with the specified key, or DefaultValue if the key isn't contained in this map.
Definition at line 349 of file SortedMap.h.
GenerateKeyArray()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename Allocator> void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::GenerateKeyArray (TArray< KeyType, Allocator > & OutArray) const inline
Generates an array from the keys in this map.
Definition at line 409 of file SortedMap.h.
GenerateValueArray()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename Allocator> void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::GenerateValueArray (TArray< ValueType, Allocator > & OutArray) const inline
Generates an array from the values in this map.
Definition at line 421 of file SortedMap.h.
Get() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ElementType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Get (FSetElementId Id) inline nodiscard
Return a mapped pair by internal identifier.
Element must be valid (see @IsValidId).
Definition at line 537 of file SortedMap.h.
Get() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE const ElementType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Get (FSetElementId Id) const inline nodiscard
Return a mapped pair by internal identifier.
Element must be valid (see @IsValidId).
Definition at line 543 of file SortedMap.h.
GetAllocatedSize()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE SIZE_T TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::GetAllocatedSize () const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
number of bytes allocated by this container.
Definition at line 170 of file SortedMap.h.
GetKeys()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename Allocator> int32 TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::GetKeys (TArray< KeyType, Allocator > & OutKeys) const inline
Returns the unique keys contained within this map.
Parameters
OutKeys Upon return, contains the set of unique keys in this map.
Returns
The number of unique keys in the map.
Definition at line 396 of file SortedMap.h.
GetMaxIndex()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE int32 TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::GetMaxIndex () const inline nodiscard
Returns
The max valid index of the elements in the sparse storage.
Definition at line 521 of file SortedMap.h.
IsEmpty()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::IsEmpty () const inline nodiscard
Returns true if the map is empty and contains no elements.
Returns
True if the map is empty.
See also
Num
Definition at line 153 of file SortedMap.h.
IsValidId()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::IsValidId (FSetElementId Id) const inline nodiscard
Checks whether an element id is valid.
Parameters
Id - The element id to check.
Returns
true if the element identifier refers to a valid element in this map.
Definition at line 531 of file SortedMap.h.
Num()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE int32 TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Num () const inline nodiscard
Returns
The number of elements in the map.
Definition at line 159 of file SortedMap.h.
Referenced by TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator::TConstReverseIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TReverseIterator::TReverseIterator(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Append(), and TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Append().
operator!=()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator!= (const TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > & Other) const inline
Inequality operator.
This is efficient because pairs are always sorted.
Definition at line 114 of file SortedMap.h.
operator=() [1/5]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator= (const TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > &) default
operator=() [2/5]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherArrayAllocator> TSortedMap & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator= (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > & Other) inline
Assignment operator for copying elements from a TSortedMap with a different ArrayAllocator.
Definition at line 90 of file SortedMap.h.
operator=() [3/5]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList) inline
Assignment operator which gets its elements from a native initializer list.
Definition at line 97 of file SortedMap.h.
operator=() [4/5]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> TSortedMap & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator= (TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > &&) default
operator=() [5/5]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherArrayAllocator> TSortedMap & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator= (TSortedMap< KeyType, ValueType, OtherArrayAllocator, SortPredicate > && Other) inline
Assignment operator for moving elements from a TSortedMap with a different ArrayAllocator.
Definition at line 82 of file SortedMap.h.
operator==() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator== (const TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate > & Other) const inline
Equality operator.
This is efficient because pairs are always sorted.
Definition at line 108 of file SortedMap.h.
operator==() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 72 of file SortedMap.h.
operator[]() [1/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator[] (KeyConstPointerType Key) inline nodiscard
Definition at line 509 of file SortedMap.h.
operator[]() [2/2]
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE const ValueType & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::operator[] (KeyConstPointerType Key) const inline nodiscard
Definition at line 513 of file SortedMap.h.
Remove()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE int32 TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Remove (KeyConstPointerType InKey) inline
Removes all value associations for a key.
Parameters
InKey The key to remove associated values for.
Returns
The number of values that were associated with the key.
Definition at line 241 of file SortedMap.h.
RemoveAndCopyValue()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::RemoveAndCopyValue (KeyInitType Key, ValueType & OutRemovedValue) inline
Removes the pair with the specified key and copies the value that was removed to the ref parameter.
Parameters
Key The key to search for
OutRemovedValue If found, the value that was removed (not modified if the key was not found)
Returns
Whether or not the key was found
Definition at line 447 of file SortedMap.h.
Reserve()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Reserve (int32 Number) inline
Preallocates enough memory to contain Number elements.
Definition at line 142 of file SortedMap.h.
Referenced by TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::TSortedMap(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Append(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Append(), and FText::FormatNamed().
Reset()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Reset () inline
Efficiently empties out the map but preserves all allocations and capacities.
Definition at line 130 of file SortedMap.h.
Shrink()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Shrink () inline
Shrinks the pair set to avoid slack.
Definition at line 136 of file SortedMap.h.
Friends And Related Symbol Documentation
TSortedMap
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> template<typename OtherKeyType, typename OtherValueType, typename OtherArrayAllocator, typename OtherSortPredicate> friend class TSortedMap friend
Definition at line 22 of file SortedMap.h.
Referenced by TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator::TConstIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::TConstKeyIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator::TConstReverseIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TIterator::TIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::TKeyIterator(), and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TReverseIterator::TReverseIterator().
TSortedMapPrivateFriend
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> friend struct TSortedMapPrivateFriend friend
Definition at line 908 of file SortedMap.h.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> bool TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 65 of file SortedMap.h.
Pairs
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> ElementArrayType TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Pairs private
An array of the key-value pairs in the map.
Definition at line 742 of file SortedMap.h.
Referenced by TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstIterator::TConstIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstKeyIterator::TConstKeyIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator::TConstReverseIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TIterator::TIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::TKeyIterator(), and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TReverseIterator::TReverseIterator().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SortedMap.h