Unreal Engine 5.6 C++ API: FUICommandInfoDecl Class Reference
FUICommandInfoDecl Class Reference
#include "UICommandInfo.h"
Public Member Functions
FUICommandInfoDecl (const TSharedRef< class FBindingContext > &InContext, const FName InCommandName, const FText &InLabel, const FText &InDesc, const FName InBundle=NAME_None)
FUICommandInfoDecl & DefaultChord (const FInputChord &InDefaultChord, const EMultipleKeyBindingIndex InChordIndex=EMultipleKeyBindingIndex::Primary)
FUICommandInfoDecl & Description (const FText &InDesc)
FUICommandInfoDecl & Icon (const FSlateIcon &InIcon)
operator TSharedPtr< FUICommandInfo > () const
operator TSharedRef< FUICommandInfo > () const
FUICommandInfoDecl & UserInterfaceType (EUserInterfaceActionType InType)
Private Attributes
const TSharedRef< FBindingContext > & Context
TSharedPtr< class FUICommandInfo > Info
Friends
class FBindingContext
Detailed Description
Definition at line 54 of file UICommandInfo.h.
Constructor & Destructor Documentation
FUICommandInfoDecl()
FUICommandInfoDecl::FUICommandInfoDecl (const TSharedRef< class FBindingContext > & InContext, const FName InCommandName, const FText & InLabel, const FText & InDesc, const FName InBundle = NAME_None)
Referenced by DefaultChord(), Description(), Icon(), and UserInterfaceType().
Member Function Documentation
DefaultChord()
FUICommandInfoDecl & FUICommandInfoDecl::DefaultChord (const FInputChord & InDefaultChord, const EMultipleKeyBindingIndex InChordIndex = EMultipleKeyBindingIndex::Primary)
References FUICommandInfoDecl().
Description()
FUICommandInfoDecl & FUICommandInfoDecl::Description (const FText & InDesc)
References FUICommandInfoDecl().
Icon()
FUICommandInfoDecl & FUICommandInfoDecl::Icon (const FSlateIcon & InIcon)
References FUICommandInfoDecl().
operator TSharedPtr< FUICommandInfo >()
FUICommandInfoDecl::operator TSharedPtr< FUICommandInfo > () const
operator TSharedRef< FUICommandInfo >()
FUICommandInfoDecl::operator TSharedRef< FUICommandInfo > () const
UserInterfaceType()
FUICommandInfoDecl & FUICommandInfoDecl::UserInterfaceType (EUserInterfaceActionType InType)
References FUICommandInfoDecl().
Friends And Related Symbol Documentation
FBindingContext
friend class FBindingContext friend
Definition at line 56 of file UICommandInfo.h.
References FBindingContext.
Referenced by FBindingContext.
Field Documentation
Context
const TSharedRef<FBindingContext>& FUICommandInfoDecl::Context private
Definition at line 75 of file UICommandInfo.h.
Info
TSharedPtr<class FUICommandInfo> FUICommandInfoDecl::Info private
Definition at line 74 of file UICommandInfo.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Commands/UICommandInfo.h