Unreal Engine 5.6 C++ API: FDragDropOperation Class Reference
FDragDropOperation Class Reference
A base class for a DragAndDrop operation which supports reflection.
#include "DragAndDrop.h"
Public Member Functions
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const
Gets the widget that will serve as the decorator unless overridden.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual void Construct ()
Constructs the window and widget if applicable.
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A base class for a DragAndDrop operation which supports reflection.
Drag and Drop is inherently quite stateful. Implementing a custom DragDropOperation allows for dedicated handling of a drag drop operation which keeps a decorator window (optionally) Implement derived types with DRAG_DROP_OPERATOR_TYPE (see below)
Definition at line 19 of file DragAndDrop.h.
Constructor & Destructor Documentation
FDragDropOperation()
FDragDropOperation::FDragDropOperation ()
Default constructor.
Referenced by FGraphNodeDragDropOp::DECLARE_DELEGATE_FourParams(), FGraphNodeDragDropOp::DECLARE_DELEGATE_FourParams(), FBoneDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FBrushBuilderDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FClassDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FDecoratedDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FDragAndDropVerticalBoxOp::DRAG_DROP_OPERATOR_TYPE(), FExportTextDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FGraphEditorDragDropAction::DRAG_DROP_OPERATOR_TYPE(), FSocketDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FUICommandDragDropOp::DRAG_DROP_OPERATOR_TYPE(), SRigVMNodeLayoutWidget::FRigVMNodeLayoutDragDropOp::DRAG_DROP_OPERATOR_TYPE(), FExternalDragOperation::GetTypeId(), and FGameDragDropOperation::GetTypeId().
~FDragDropOperation()
virtual FDragDropOperation::~FDragDropOperation () virtual
Destructor.
Member Function Documentation
AffectedByPointerEvent()
virtual bool FDragDropOperation::AffectedByPointerEvent (const FPointerEvent & PointerEvent) inline virtual
Checks if this drag and drop operation is affected by a given PointerEvent.
Parameters
PointerEvent The mouse event we are checking against
Returns
true if the the pointer event affects this drag and drop operation (default true).
Definition at line 46 of file DragAndDrop.h.
Construct()
virtual void FDragDropOperation::Construct () protected virtual
Constructs the window and widget if applicable.
Reimplemented in FBrushBuilderDragDropOp, FDecoratedDragDropOp, FGraphEditorDragDropAction, FRigVMGraphExplorerDragDropOp, and UE::Sequencer::FOutlinerViewModelDragDropOp.
Referenced by FDecoratedDragDropOp::Construct().
ConvertTo()
virtual TSharedPtr< FDragDropOperation > FDragDropOperation::ConvertTo (const FString & TypeId) inline protected virtual
Definition at line 115 of file DragAndDrop.h.
References TSharedFromThis< FDragDropOperation >::AsShared(), and IsOfTypeImpl().
CreateCursorDecoratorWindow()
void FDragDropOperation::CreateCursorDecoratorWindow () protected
Creates a window for the cursor decorator.
DestroyCursorDecoratorWindow()
void FDragDropOperation::DestroyCursorDecoratorWindow () protected
Destroys the cursor decorator window.
GetDecoratorPosition()
virtual FVector2D FDragDropOperation::GetDecoratorPosition () const inline virtual
Gets the desired position of the decorator in absolute space.
Reimplemented in FGameDragDropOperation, and SRigVMNodeLayoutWidget::FRigVMNodeLayoutDragDropOp.
Definition at line 73 of file DragAndDrop.h.
GetDefaultDecorator()
virtual TSharedPtr< SWidget > FDragDropOperation::GetDefaultDecorator () const inline virtual
Gets the widget that will serve as the decorator unless overridden.
If you do not override, you will have no decorator
Reimplemented in FAssetDragDropOp, FBoneDragDropOp, FBrushBuilderDragDropOp, FClassDragDropOp, FCollectionDragDropOp, FDecoratedDragDropOp, FLevelDragDropOp, FUICommandDragDropOp, and SRigVMNodeLayoutWidget::FRigVMNodeLayoutDragDropOp.
Definition at line 70 of file DragAndDrop.h.
IsExternalOperation()
virtual bool FDragDropOperation::IsExternalOperation () const inline virtual
Is this drag Drop operation going to interact with applications outside of Slate.
Reimplemented in FExternalDragOperation.
Definition at line 79 of file DragAndDrop.h.
IsOfType()
template<class TType> bool FDragDropOperation::IsOfType () const inline
Check if this drag and drop operation can cast safely to the specified template type.
Definition at line 35 of file DragAndDrop.h.
References IsOfTypeImpl().
IsOfTypeImpl()
virtual bool FDragDropOperation::IsOfTypeImpl (const FString & Type) const inline virtual
Checks whether this drag and drop operation can cast safely to the specified type.
Reimplemented in FExternalDragOperation, FGameDragDropOperation, and FRigVMFunctionDragDropAction.
Definition at line 94 of file DragAndDrop.h.
Referenced by ConvertTo(), and IsOfType().
IsWindowlessOperation()
virtual bool FDragDropOperation::IsWindowlessOperation () const inline virtual
Returns
true if the operation does not create a decorator window. Used for game drag drop operations.
Reimplemented in SRigVMNodeLayoutWidget::FRigVMNodeLayoutDragDropOp.
Definition at line 82 of file DragAndDrop.h.
References bCreateNewWindow.
OnCursorQuery()
virtual FCursorReply FDragDropOperation::OnCursorQuery () virtual
Allows drag/drop operations to override the current cursor.
OnDragged()
virtual void FDragDropOperation::OnDragged (const class FDragDropEvent & DragDropEvent) virtual
Called when the mouse was moved during a drag and drop operation.
Parameters
DragDropEvent The event that describes this drag drop operation.
Reimplemented in FUICommandDragDropOp.
Referenced by FBrushBuilderDragDropOp::OnDragged().
OnDrop()
virtual void FDragDropOperation::OnDrop (bool bDropWasHandled, const FPointerEvent & MouseEvent) virtual
Invoked when the drag and drop operation has ended.
Parameters
bDropWasHandled true when the drop was handled by some widget; false otherwise
MouseEvent The mouse event which caused the on drop to be called.
Reimplemented in FBrushBuilderDragDropOp, FUICommandDragDropOp, and FWidgetPropertyDragDropOp.
References MouseEvent.
Referenced by FBrushBuilderDragDropOp::OnDrop().
SetCursorOverride()
void FDragDropOperation::SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
SetDecoratorVisibility()
virtual void FDragDropOperation::SetDecoratorVisibility (bool bVisible) virtual
Alters the visibility of the window.
Field Documentation
bCreateNewWindow
bool FDragDropOperation::bCreateNewWindow protected
Create a new window for the decorator content.
If this is false, SlateApplication will draw the decorator directly using the
Definition at line 126 of file DragAndDrop.h.
Referenced by IsWindowlessOperation().
CursorDecoratorWindow
TSharedPtr<SWindow> FDragDropOperation::CursorDecoratorWindow protected
The window that owns the decorator widget.
Definition at line 129 of file DragAndDrop.h.
Referenced by FBrushBuilderDragDropOp::OnDragged().
MouseCursor
TOptional<EMouseCursor::Type> FDragDropOperation::MouseCursor protected
Mouse cursor used by the drag drop operation.
Definition at line 132 of file DragAndDrop.h.
MouseCursorOverride
TOptional<EMouseCursor::Type> FDragDropOperation::MouseCursorOverride protected
Mouse cursor used to temporarily replace the drag drops cursor.
Definition at line 135 of file DragAndDrop.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/DragAndDrop.h