Unreal Engine 5.6 C++ API: FRigVMTreeFunctionRefNode Class Reference
FRigVMTreeFunctionRefNode Class Reference
#include "SRigVMSwapFunctionsWidget.h"
Public Member Functions
FRigVMTreeFunctionRefNode (const FRigVMReferenceNodeData &InRefNodeData)
DEFINE_RIGVMTREETOOLKIT_ELEMENT (FRigVMTreeFunctionRefNode, FRigVMTreeNode) FRigVMTreeFunctionRefNode(const URigVMFunctionReferenceNode *InFunctionReferenceNode)
virtual const FSlateBrush * GetIconAndTint (FLinearColor &OutColor) const override
const FRigVMGraphFunctionIdentifier & GetIdentifier () const
virtual bool IsCheckable () const override
Public Member Functions inherited from FRigVMTreeNode
FRigVMTreeNode (const FString &InPath)
virtual void DirtyChildren ()
virtual void DirtyVisibleChildren ()
TSharedPtr< FRigVMTreeNode > FindVisibleChild (const FString &InFullPath, const TSharedRef< FRigVMTreeContext > &InContext) const
virtual FAssetData GetAssetData () const
virtual FSlateColor GetBackgroundColor (bool bIsHovered, bool bIsSelected) const
virtual const FSlateBrush * GetBackgroundImage (bool bIsHovered, bool bIsSelected) const
virtual URigVMBlueprint * GetBlueprint () const
ECheckBoxState GetCheckState () const
TArray< TSharedRef< FRigVMTreeNode > > GetChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
virtual void GetContextMenu (FMenuBuilder &InMenuBuilder)
int32 GetDepth () const
virtual FText GetLabel () const
TSharedPtr< FRigVMTreeNode > GetParent () const
virtual const FString & GetPath () const
TSharedRef< FRigVMTreeNode > GetRoot () const
virtual const TArray< FRigVMTag > & GetTags () const
virtual FName GetType () const override
const TArray< TSharedRef< FRigVMTreeNode > > & GetVisibleChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
virtual bool HasVisibleChildren () const
virtual bool IsLoaded () const
virtual bool IsOfType (const FName &InType) const override
void RequestRefresh (bool bForce=false)
void ResetCheckState ()
void SetCheckState (ECheckBoxState InNewState)
virtual bool ShouldExpandByDefault () const
TSharedPtr< FRigVMTreeNode > ToSharedPtr () const
TSharedRef< FRigVMTreeNode > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Attributes
FRigVMGraphFunctionIdentifier Identifier
Additional Inherited Members
Public Types inherited from FRigVMTreeNode
typedef FRigVMTreeElement Super
Static Public Member Functions inherited from FRigVMTreeNode
template<typename... Types>
static TSharedRef< FRigVMTreeNode > Create (Types... Args)
Static Public Attributes inherited from FRigVMTreeNode
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeNode"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Protected Member Functions inherited from FRigVMTreeNode
void AddChildImpl (const TSharedRef< FRigVMTreeNode > &InChild) const
bool ContainsAnyVisibleCheckedNode () const
DECLARE_DELEGATE_OneParam (FRefreshDelegate, bool) FRefreshDelegate RefreshDelegate
void DirtyVisibleParent () const
virtual TArray< TSharedRef< FRigVMTreeNode > > GetChildrenImpl (const TSharedRef< FRigVMTreeContext > &InContext) const
void UpdateChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
void UpdateVisibleChildren (const TSharedRef< FRigVMTreeContext > &InContext) const
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from FRigVMTreeNode
static TSharedPtr< FRigVMTreeNode > FindVisibleNodeInSet (const TArray< TSharedRef< FRigVMTreeNode > > &InNodes, const FString &InPath, const TSharedRef< FRigVMTreeContext > &InContext)
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FRigVMTreeNode
bool bIsDirtyingParent = false
TOptional< ECheckBoxState > CheckState
TOptional< TArray< TSharedRef< FRigVMTreeNode > > > Children
const FRigVMTreeNode * Parent = nullptr
FString Path
TArray< FRigVMTag > Tags
TArray< TSharedRef< FRigVMTreeNode > > VisibleChildren
uint32 VisibleChildrenHash = UINT32_MAX
Detailed Description
Definition at line 46 of file SRigVMSwapFunctionsWidget.h.
Constructor & Destructor Documentation
FRigVMTreeFunctionRefNode()
FRigVMTreeFunctionRefNode::FRigVMTreeFunctionRefNode (const FRigVMReferenceNodeData & InRefNodeData) inline
Definition at line 57 of file SRigVMSwapFunctionsWidget.h.
References FRigVMTreeNode::FRigVMTreeNode(), and Identifier.
Referenced by DEFINE_RIGVMTREETOOLKIT_ELEMENT().
Member Function Documentation
DEFINE_RIGVMTREETOOLKIT_ELEMENT()
FRigVMTreeFunctionRefNode::DEFINE_RIGVMTREETOOLKIT_ELEMENT (FRigVMTreeFunctionRefNode , FRigVMTreeNode) const inline
Definition at line 49 of file SRigVMSwapFunctionsWidget.h.
References FRigVMTreeFunctionRefNode(), FRigVMTreeNode::FRigVMTreeNode(), and Identifier.
GetIconAndTint()
virtual const FSlateBrush * FRigVMTreeFunctionRefNode::GetIconAndTint (FLinearColor & OutColor) const override virtual
Reimplemented from FRigVMTreeNode.
GetIdentifier()
const FRigVMGraphFunctionIdentifier & FRigVMTreeFunctionRefNode::GetIdentifier () const inline
Definition at line 68 of file SRigVMSwapFunctionsWidget.h.
References Identifier.
IsCheckable()
virtual bool FRigVMTreeFunctionRefNode::IsCheckable () const inline override virtual
Reimplemented from FRigVMTreeNode.
Definition at line 63 of file SRigVMSwapFunctionsWidget.h.
Field Documentation
Identifier
FRigVMGraphFunctionIdentifier FRigVMTreeFunctionRefNode::Identifier private
Definition at line 76 of file SRigVMSwapFunctionsWidget.h.
Referenced by FRigVMTreeFunctionRefNode(), DEFINE_RIGVMTREETOOLKIT_ELEMENT(), and GetIdentifier().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Widgets/SRigVMSwapFunctionsWidget.h