Unreal Engine 5.6 C++ API: UE::Geometry::FSmallListSet::ValueIterator Class Reference
UE::Geometry::FSmallListSet::ValueIterator Class Reference
ValueIterator iterates over the values of a small list.
#include "SmallListSet.h"
Public Member Functions
ValueIterator ()
int32 operator* () const
const ValueIterator & operator++ ()
Public Member Functions inherited from UE::Geometry::FSmallListSet::BaseValueIterator
BaseValueIterator ()
bool operator!= (const BaseValueIterator &Other) const
bool operator== (const BaseValueIterator &Other) const
Protected Member Functions
ValueIterator (const FSmallListSet *ListSetIn, int32 ListIndex, bool is_end)
Protected Member Functions inherited from UE::Geometry::FSmallListSet::BaseValueIterator
BaseValueIterator (const FSmallListSet *ListSetIn, int32 ListIndex, bool is_end)
void GotoNext ()
void GotoNextOverflow ()
void SetToEnd ()
Friends
class FSmallListSet
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::FSmallListSet::BaseValueIterator
int32 block_ptr
int32 cur_ptr
int32 cur_value
int32 iCur
int32 iEnd
int32 ListIndex
const FSmallListSet * ListSet
int32 N
Detailed Description
ValueIterator iterates over the values of a small list.
Definition at line 505 of file SmallListSet.h.
Constructor & Destructor Documentation
ValueIterator() [1/2]
UE::Geometry::FSmallListSet::ValueIterator::ValueIterator () inline
Definition at line 508 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BaseValueIterator::BaseValueIterator().
Referenced by operator++().
ValueIterator() [2/2]
UE::Geometry::FSmallListSet::ValueIterator::ValueIterator (const FSmallListSet * ListSetIn, int32 ListIndex, bool is_end) inline protected
Definition at line 522 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BaseValueIterator::BaseValueIterator(), FSmallListSet, and UE::Geometry::FSmallListSet::BaseValueIterator::ListIndex.
Member Function Documentation
operator*()
int32 UE::Geometry::FSmallListSet::ValueIterator::operator* () const inline
Definition at line 510 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BaseValueIterator::cur_value.
operator++()
const ValueIterator & UE::Geometry::FSmallListSet::ValueIterator::operator++ () inline
Definition at line 515 of file SmallListSet.h.
References ValueIterator(), and UE::Geometry::FSmallListSet::BaseValueIterator::GotoNext().
Friends And Related Symbol Documentation
FSmallListSet
friend class FSmallListSet friend
Definition at line 525 of file SmallListSet.h.
References FSmallListSet.
Referenced by ValueIterator(), and FSmallListSet.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/SmallListSet.h