Unreal Engine 5.6 C++ API: UE::Geometry::TImplicitMorphology< TriangleMeshType > Class Template Reference
UE::Geometry::TImplicitMorphology< TriangleMeshType > Class Template Reference
#include "Morphology.h"
Public Types
enum class EMorphologyOp { Dilate = 0 , Contract = 1 , Close = 2 , Open = 3 }
Morphology operation types.
Public Member Functions
const FMeshShapeGenerator & Generate ()
void SetCellSizesAndDistance (FAxisAlignedBox3d Bounds, double DistanceIn, int TargetInputVoxelCount, int TargetOutputVoxelCount)
void SetGridCellSize (FAxisAlignedBox3d Bounds, double DistanceIn, int TargetInputVoxelCount)
void SetMeshCellSize (FAxisAlignedBox3d Bounds, double DistanceIn, int TargetInputVoxelCount)
bool Validate ()
Data Fields
bool bUseCustomBounds = false
Whether to use a custom bounding box instead of the input mesh bounds to define the domain to solidify.
TFunction< bool(void)> CancelF
if this function returns true, we should abort calculation
FAxisAlignedBox3d CustomBounds
Custom bounds to use, if bUseCustomBounds == true; ignored otherwise.
double Distance = 1.0
double GridCellSize = 1.0
double MeshCellSize = 1.0
EMorphologyOp MorphologyOp = EMorphologyOp::Dilate
const TriangleMeshType * Source = nullptr
Inputs.
TMeshAABBTree3< TriangleMeshType > * SourceSpatial = nullptr
Protected Types
template<typename MeshType>
using TMeshSDF = TSparseNarrowBandMeshSDF<MeshType>
Protected Member Functions
void ComputeFirstPass (double UnsignedOffset, double SignedOffset)
void ComputeSecondPass (double UnsignedOffset, double SignedOffset)
Protected Attributes
FMarchingCubes MarchingCubes
double NarrowBandMaxDistance
Static Private Member Functions
static double GetSafeCellSize (double BoundsWidth, double InitialCellSize, int32 ExtraCellCount)
Static Private Attributes
static constexpr int32 MaxTargetVoxelCount = 1200
Detailed Description
template<typename TriangleMeshType>
class UE::Geometry::TImplicitMorphology< TriangleMeshType >
Definition at line 24 of file Morphology.h.
Member Typedef Documentation
TMeshSDF
template<typename TriangleMeshType> template<typename MeshType> using UE::Geometry::TImplicitMorphology< TriangleMeshType >::TMeshSDF = TSparseNarrowBandMeshSDF<MeshType> protected
Definition at line 140 of file Morphology.h.
Member Enumeration Documentation
EMorphologyOp
template<typename TriangleMeshType> enum class UE::Geometry::TImplicitMorphology::EMorphologyOp strong
Morphology operation types.
Enumerator
Dilate
Expand the shapes outward.
Contract
Shrink the shapes inward.
Close
Dilate and then contract, to delete small negative features (sharp inner corners, small holes)
Open
Contract and then dilate, to delete small positive features (sharp outer corners, small isolated pieces)
Definition at line 28 of file Morphology.h.
Member Function Documentation
ComputeFirstPass()
template<typename TriangleMeshType> void UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeFirstPass (double UnsignedOffset, double SignedOffset) inline protected
..... then remove this line
Definition at line 142 of file Morphology.h.
References UE::Geometry::TMeshQueries< TriangleMeshType >::AverageEdgeLength(), bUseCustomBounds, CancelF, CustomBounds, float, GetSafeCellSize(), GridCellSize, MarchingCubes, MeshCellSize, NarrowBandMaxDistance, UE::Geometry::SingleLerp, Source, SourceSpatial, TRACE_CPUPROFILER_EVENT_SCOPE, and UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value().
Referenced by Generate().
ComputeSecondPass()
template<typename TriangleMeshType> void UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeSecondPass (double UnsignedOffset, double SignedOffset) inline protected
..... then remove this line
Definition at line 215 of file Morphology.h.
References UE::Geometry::TMeshAABBTree3< TriangleMeshType >::Build(), bUseCustomBounds, CancelF, UE::Geometry::TAxisAlignedBox3< RealType >::Expand(), float, UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetBoundingBox(), GetSafeCellSize(), GridCellSize, MarchingCubes, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), MeshCellSize, NarrowBandMaxDistance, TRACE_CPUPROFILER_EVENT_SCOPE, and UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value().
Referenced by Generate().
Generate()
template<typename TriangleMeshType> const FMeshShapeGenerator & UE::Geometry::TImplicitMorphology< TriangleMeshType >::Generate () inline
Definition at line 108 of file Morphology.h.
References TMathUtil< double >::Abs(), Close, ComputeFirstPass(), ComputeSecondPass(), Dilate, Distance, ensure, MarchingCubes, MorphologyOp, Open, and Validate().
GetSafeCellSize()
template<typename TriangleMeshType> double UE::Geometry::TImplicitMorphology< TriangleMeshType >::GetSafeCellSize (double BoundsWidth, double InitialCellSize, int32 ExtraCellCount) inline static private
Definition at line 320 of file Morphology.h.
References MaxTargetVoxelCount.
Referenced by ComputeFirstPass(), and ComputeSecondPass().
SetCellSizesAndDistance()
template<typename TriangleMeshType> void UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetCellSizesAndDistance (FAxisAlignedBox3d Bounds, double DistanceIn, int TargetInputVoxelCount, int TargetOutputVoxelCount) inline
Definition at line 66 of file Morphology.h.
References Distance, SetGridCellSize(), and SetMeshCellSize().
SetGridCellSize()
template<typename TriangleMeshType> void UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetGridCellSize (FAxisAlignedBox3d Bounds, double DistanceIn, int TargetInputVoxelCount) inline
Definition at line 74 of file Morphology.h.
References bUseCustomBounds, GridCellSize, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), MaxTargetVoxelCount, and FMath::Min.
Referenced by SetCellSizesAndDistance().
SetMeshCellSize()
template<typename TriangleMeshType> void UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetMeshCellSize (FAxisAlignedBox3d Bounds, double DistanceIn, int TargetInputVoxelCount) inline
Definition at line 81 of file Morphology.h.
References bUseCustomBounds, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), MaxTargetVoxelCount, MeshCellSize, and FMath::Min.
Referenced by SetCellSizesAndDistance().
Validate()
template<typename TriangleMeshType> bool UE::Geometry::TImplicitMorphology< TriangleMeshType >::Validate () inline
Definition at line 101 of file Morphology.h.
References Distance, GridCellSize, MeshCellSize, Source, and SourceSpatial.
Referenced by Generate().
Field Documentation
bUseCustomBounds
template<typename TriangleMeshType> bool UE::Geometry::TImplicitMorphology< TriangleMeshType >::bUseCustomBounds = false
Whether to use a custom bounding box instead of the input mesh bounds to define the domain to solidify.
Definition at line 60 of file Morphology.h.
Referenced by ComputeFirstPass(), ComputeSecondPass(), SetGridCellSize(), and SetMeshCellSize().
CancelF
template<typename TriangleMeshType> TFunction<bool(void)> UE::Geometry::TImplicitMorphology< TriangleMeshType >::CancelF
Initial value:
= []()
    {
        return false;
    }
if this function returns true, we should abort calculation
Definition at line 88 of file Morphology.h.
Referenced by ComputeFirstPass(), and ComputeSecondPass().
CustomBounds
template<typename TriangleMeshType> FAxisAlignedBox3d UE::Geometry::TImplicitMorphology< TriangleMeshType >::CustomBounds
Custom bounds to use, if bUseCustomBounds == true; ignored otherwise.
Definition at line 63 of file Morphology.h.
Referenced by ComputeFirstPass().
Distance
template<typename TriangleMeshType> double UE::Geometry::TImplicitMorphology< TriangleMeshType >::Distance = 1.0
Definition at line 51 of file Morphology.h.
Referenced by Generate(), SetCellSizesAndDistance(), and Validate().
GridCellSize
template<typename TriangleMeshType> double UE::Geometry::TImplicitMorphology< TriangleMeshType >::GridCellSize = 1.0
Definition at line 54 of file Morphology.h.
Referenced by ComputeFirstPass(), ComputeSecondPass(), SetGridCellSize(), and Validate().
MarchingCubes
template<typename TriangleMeshType> FMarchingCubes UE::Geometry::TImplicitMorphology< TriangleMeshType >::MarchingCubes protected
Definition at line 95 of file Morphology.h.
Referenced by ComputeFirstPass(), ComputeSecondPass(), and Generate().
MaxTargetVoxelCount
template<typename TriangleMeshType> int32 UE::Geometry::TImplicitMorphology< TriangleMeshType >::MaxTargetVoxelCount = 1200 static constexpr private
Definition at line 316 of file Morphology.h.
Referenced by GetSafeCellSize(), SetGridCellSize(), and SetMeshCellSize().
MeshCellSize
template<typename TriangleMeshType> double UE::Geometry::TImplicitMorphology< TriangleMeshType >::MeshCellSize = 1.0
Definition at line 57 of file Morphology.h.
Referenced by ComputeFirstPass(), ComputeSecondPass(), SetMeshCellSize(), and Validate().
MorphologyOp
template<typename TriangleMeshType> EMorphologyOp UE::Geometry::TImplicitMorphology< TriangleMeshType >::MorphologyOp = EMorphologyOp::Dilate
Definition at line 48 of file Morphology.h.
Referenced by Generate().
NarrowBandMaxDistance
template<typename TriangleMeshType> double UE::Geometry::TImplicitMorphology< TriangleMeshType >::NarrowBandMaxDistance protected
Definition at line 98 of file Morphology.h.
Referenced by ComputeFirstPass(), and ComputeSecondPass().
Source
template<typename TriangleMeshType> const TriangleMeshType* UE::Geometry::TImplicitMorphology< TriangleMeshType >::Source = nullptr
Inputs.
Definition at line 46 of file Morphology.h.
Referenced by ComputeFirstPass(), and Validate().
SourceSpatial
template<typename TriangleMeshType> TMeshAABBTree3<TriangleMeshType>* UE::Geometry::TImplicitMorphology< TriangleMeshType >::SourceSpatial = nullptr
Definition at line 47 of file Morphology.h.
Referenced by ComputeFirstPass(), and Validate().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Implicit/Morphology.h