Unreal Engine 5.6 C++ API: UMovieSceneCondition Class Reference
UMovieSceneCondition Class Reference
#include "MovieSceneCondition.h"
Protected Member Functions
virtual MOVIESCENE_API bool EvaluateConditionInternal (FGuid BindingGuid, FMovieSceneSequenceID SequenceID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) const
virtual MOVIESCENE_API EMovieSceneConditionCheckFrequency GetCheckFrequencyInternal () const
virtual MOVIESCENE_API EMovieSceneConditionScope GetScopeInternal () const
UFUNCTION ()) MOVIESCENE_API bool BP_EvaluateCondition(const FMovieSceneConditionContext &ConditionContext) const
UFUNCTION ()) MOVIESCENE_API EMovieSceneConditionCheckFrequency BP_GetCheckFrequency() const
UFUNCTION ()) MOVIESCENE_API EMovieSceneConditionScope BP_GetScope() const
UPROPERTY () bool bInvert
Private Member Functions
virtual MOVIESCENE_API bool CanCacheResult (TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) const
GENERATED_BODY() public virtual MOVIESCENE_API uint32 ComputeCacheKey (FGuid BindingGuid, FMovieSceneSequenceID SequenceID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState, UObject *EntityOwner) const
MOVIESCENE_API EMovieSceneConditionScope GetConditionScope () const
Detailed Description
Definition at line 86 of file MovieSceneCondition.h.
Member Function Documentation
CanCacheResult()
virtual MOVIESCENE_API bool UMovieSceneCondition::CanCacheResult (TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) const private virtual
ComputeCacheKey()
GENERATED_BODY() public virtual MOVIESCENE_API uint32 UMovieSceneCondition::ComputeCacheKey (FGuid BindingGuid, FMovieSceneSequenceID SequenceID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState, UObject * EntityOwner) const private virtual
EvaluateConditionInternal()
virtual MOVIESCENE_API bool UMovieSceneCondition::EvaluateConditionInternal (FGuid BindingGuid, FMovieSceneSequenceID SequenceID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) const protected virtual
References EvaluateConditionInternal().
Referenced by EvaluateConditionInternal().
GetCheckFrequencyInternal()
virtual MOVIESCENE_API EMovieSceneConditionCheckFrequency UMovieSceneCondition::GetCheckFrequencyInternal () const protected virtual
References GetCheckFrequencyInternal().
Referenced by GetCheckFrequencyInternal().
GetConditionScope()
MOVIESCENE_API EMovieSceneConditionScope UMovieSceneCondition::GetConditionScope () const private
References bool, and Category.
GetScopeInternal()
virtual MOVIESCENE_API EMovieSceneConditionScope UMovieSceneCondition::GetScopeInternal () const protected virtual
References GetScopeInternal().
Referenced by GetScopeInternal().
UFUNCTION() [1/3]
UMovieSceneCondition::UFUNCTION () const & protected
References meta.
Referenced by UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/3]
UMovieSceneCondition::UFUNCTION () const protected
References meta, and UFUNCTION().
UFUNCTION() [3/3]
UMovieSceneCondition::UFUNCTION () const protected
References meta, and UFUNCTION().
UPROPERTY()
UMovieSceneCondition::UPROPERTY () protected
References Category, and UPROPERTY().
Referenced by UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Conditions/MovieSceneCondition.h