Unreal Engine 5.6 C++ API: FSelectClickedAction Class Reference
FSelectClickedAction Class Reference
BehaviorTarget to do world raycast selection from a click Currently used to click-select reference planes in the world.
#include "SelectClickedAction.h"
Public Member Functions
virtual FInputRayHit IsHitByClick (const FInputDeviceRay &ClickPos) override
Test if target is hit by a click.
virtual void OnClicked (const FInputDeviceRay &ClickPos) override
Notify Target that click ocurred.
virtual void OnUpdateModifierState (int ModifierID, bool bIsOn)
Notify target of current modifier state.
Public Member Functions inherited from IClickBehaviorTarget
virtual ~IClickBehaviorTarget ()
Public Member Functions inherited from IModifierToggleBehaviorTarget
virtual ~IModifierToggleBehaviorTarget ()
virtual void OnForceEndCapture ()
Notify Target that capture is ending.
Data Fields
bool bShiftModifierToggle = false
TUniqueFunction< bool()> ExternalCanClickPredicate = nullptr
TArray< const UPrimitiveComponent * > InvisibleComponentsToHitTest
TFunction< void(const FHitResult &)> OnClickedPositionFunc = nullptr
USceneSnappingManager * SnapManager = nullptr
TArray< const UPrimitiveComponent * > VisibleComponentsToIgnore
UWorld * World = nullptr
Static Public Attributes
static const int ShiftModifier = 1
Private Member Functions
MODELINGCOMPONENTS_API FInputRayHit DoRayCast (const FInputDeviceRay &ClickPos, bool callbackOnHit)
Detailed Description
BehaviorTarget to do world raycast selection from a click Currently used to click-select reference planes in the world.
Definition at line 18 of file SelectClickedAction.h.
Member Function Documentation
DoRayCast()
MODELINGCOMPONENTS_API FInputRayHit FSelectClickedAction::DoRayCast (const FInputDeviceRay & ClickPos, bool callbackOnHit) private
Referenced by IsHitByClick(), and OnClicked().
IsHitByClick()
virtual FInputRayHit FSelectClickedAction::IsHitByClick (const FInputDeviceRay & ClickPos) inline override virtual
Test if target is hit by a click.
Parameters
ClickPos device position/ray at click point
Returns
hit information at this point
Implements IClickBehaviorTarget.
Definition at line 37 of file SelectClickedAction.h.
References DoRayCast(), and ExternalCanClickPredicate.
OnClicked()
virtual void FSelectClickedAction::OnClicked (const FInputDeviceRay & ClickPos) inline override virtual
Notify Target that click ocurred.
Parameters
ClickPos device position/ray at click point
Implements IClickBehaviorTarget.
Definition at line 46 of file SelectClickedAction.h.
References DoRayCast().
OnUpdateModifierState()
virtual void FSelectClickedAction::OnUpdateModifierState (int ModifierID, bool bIsOn) inline virtual
Notify target of current modifier state.
Parameters
ModifierID client-defined integer that identifiers modifier
bIsOn is modifier current on or off
Reimplemented from IModifierToggleBehaviorTarget.
Definition at line 52 of file SelectClickedAction.h.
References bShiftModifierToggle, and ShiftModifier.
Field Documentation
bShiftModifierToggle
bool FSelectClickedAction::bShiftModifierToggle = false
Definition at line 35 of file SelectClickedAction.h.
Referenced by OnUpdateModifierState().
ExternalCanClickPredicate
TUniqueFunction<bool()> FSelectClickedAction::ExternalCanClickPredicate = nullptr
Definition at line 26 of file SelectClickedAction.h.
Referenced by IsHitByClick().
InvisibleComponentsToHitTest
TArray<const UPrimitiveComponent*> FSelectClickedAction::InvisibleComponentsToHitTest
Definition at line 31 of file SelectClickedAction.h.
OnClickedPositionFunc
TFunction<void(const FHitResult&)> FSelectClickedAction::OnClickedPositionFunc = nullptr
Definition at line 25 of file SelectClickedAction.h.
ShiftModifier
const int FSelectClickedAction::ShiftModifier = 1 static
Definition at line 34 of file SelectClickedAction.h.
Referenced by OnUpdateModifierState().
SnapManager
USceneSnappingManager* FSelectClickedAction::SnapManager = nullptr
Definition at line 23 of file SelectClickedAction.h.
VisibleComponentsToIgnore
TArray<const UPrimitiveComponent*> FSelectClickedAction::VisibleComponentsToIgnore
Definition at line 30 of file SelectClickedAction.h.
World
UWorld* FSelectClickedAction::World = nullptr
Definition at line 24 of file SelectClickedAction.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Selection/SelectClickedAction.h