Unreal Engine 5.6 C++ API: FMacSemaphore Class Reference
FMacSemaphore Class Reference
#include "MacSemaphore.h"
Public Member Functions
FMacSemaphore (int32 InitialCount, int32)
virtual ~FMacSemaphore ()
void Acquire ()
void Release (int32 Count=1)
bool TryAcquire (FTimespan Timeout=FTimespan::Zero())
UE_NONCOPYABLE (FMacSemaphore)
Private Attributes
dispatch_semaphore_t Semaphore
Detailed Description
Definition at line 11 of file MacSemaphore.h.
Constructor & Destructor Documentation
FMacSemaphore()
FMacSemaphore::FMacSemaphore (int32 InitialCount, int32) inline
Definition at line 16 of file MacSemaphore.h.
References checkfSlow, Semaphore, and TEXT.
Referenced by UE_NONCOPYABLE().
~FMacSemaphore()
virtual FMacSemaphore::~FMacSemaphore () inline virtual
Definition at line 22 of file MacSemaphore.h.
References Semaphore.
Member Function Documentation
Acquire()
void FMacSemaphore::Acquire () inline
Definition at line 27 of file MacSemaphore.h.
References checkfSlow, Semaphore, and TEXT.
Release()
void FMacSemaphore::Release (int32 Count = 1) inline
Definition at line 40 of file MacSemaphore.h.
References checkfSlow, Count, Semaphore, and TEXT.
TryAcquire()
bool FMacSemaphore::TryAcquire (FTimespan Timeout = FTimespan::Zero()) inline
Definition at line 33 of file MacSemaphore.h.
References Semaphore, Timeout, and FTimespan::Zero().
UE_NONCOPYABLE()
FMacSemaphore::UE_NONCOPYABLE (FMacSemaphore)
References FMacSemaphore().
Field Documentation
Semaphore
dispatch_semaphore_t FMacSemaphore::Semaphore private
Definition at line 50 of file MacSemaphore.h.
Referenced by FMacSemaphore(), ~FMacSemaphore(), Acquire(), Release(), and TryAcquire().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Mac/MacSemaphore.h