Unreal Engine 5.6 C++ API: TGlobalResource< ResourceType, InInitPhase > Class Template Reference
TGlobalResource< ResourceType, InInitPhase > Class Template Reference
Used to declare a render resource that is initialized/released by static initialization/destruction.
#include "RenderResource.h"
Public Member Functions
TGlobalResource ()
Default constructor.
template<typename... Args>
TGlobalResource (Args... InArgs)
Initialization constructor: 1 parameter.
virtual ~TGlobalResource ()
Destructor.
Private Member Functions
void InitGlobalResource ()
Initialize the global resource.
void ReleaseGlobalResource ()
Release the global resource.
Detailed Description
template<class ResourceType, FRenderResource::EInitPhase InInitPhase = FRenderResource::EInitPhase::Default>
class TGlobalResource< ResourceType, InInitPhase >
Used to declare a render resource that is initialized/released by static initialization/destruction.
Definition at line 539 of file RenderResource.h.
Constructor & Destructor Documentation
TGlobalResource() [1/2]
template<class ResourceType, FRenderResource::EInitPhase InInitPhase = FRenderResource::EInitPhase::Default> TGlobalResource< ResourceType, InInitPhase >::TGlobalResource () inline
Default constructor.
Definition at line 543 of file RenderResource.h.
TGlobalResource() [2/2]
template<class ResourceType, FRenderResource::EInitPhase InInitPhase = FRenderResource::EInitPhase::Default> template<typename... Args> TGlobalResource< ResourceType, InInitPhase >::TGlobalResource (Args... InArgs) inline explicit
Initialization constructor: 1 parameter.
Definition at line 550 of file RenderResource.h.
~TGlobalResource()
template<class ResourceType, FRenderResource::EInitPhase InInitPhase = FRenderResource::EInitPhase::Default> virtual TGlobalResource< ResourceType, InInitPhase >::~TGlobalResource () inline virtual
Destructor.
Definition at line 557 of file RenderResource.h.
Member Function Documentation
InitGlobalResource()
template<class ResourceType, FRenderResource::EInitPhase InInitPhase = FRenderResource::EInitPhase::Default> void TGlobalResource< ResourceType, InInitPhase >::InitGlobalResource () inline private
Initialize the global resource.
Definition at line 567 of file RenderResource.h.
Referenced by TGlobalResource< FGlobalBoundShaderStateResource >::TGlobalResource(), and TGlobalResource< FGlobalBoundShaderStateResource >::TGlobalResource().
ReleaseGlobalResource()
template<class ResourceType, FRenderResource::EInitPhase InInitPhase = FRenderResource::EInitPhase::Default> void TGlobalResource< ResourceType, InInitPhase >::ReleaseGlobalResource () inline private
Release the global resource.
Definition at line 586 of file RenderResource.h.
Referenced by TGlobalResource< FGlobalBoundShaderStateResource >::~TGlobalResource().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderResource.h