Unreal Engine 5.6 C++ API: Metasound::FOutputVertexInterfaceData Class Reference
Metasound::FOutputVertexInterfaceData Class Reference
An output vertex interface with optionally bound data references.
#include "MetasoundVertexData.h"
Public Types
using FRangedForConstIteratorType = typename TArray<FOutputBinding>::RangedForConstIteratorType
using FRangedForIteratorType = typename TArray<FOutputBinding>::RangedForIteratorType
Public Member Functions
METASOUNDGRAPHCORE_API FOutputVertexInterfaceData ()
Construct with an FOutputVertexInterface.
METASOUNDGRAPHCORE_API FOutputVertexInterfaceData (const FOutputVertexInterface &InVertexInterface)
Construct with an FOutputVertexInterface.
METASOUNDGRAPHCORE_API void AddVertex (const FOutputDataVertex &InVertex)
Add a vertex.
Apply (InVertexName, TCreateOutputBinding(InVertexName, InOutDataReference), BindData)
METASOUNDGRAPHCORE_API bool AreAllVerticesBound () const
Returns true if all vertices in the FInputVertexInterface are bound to data references.
FRangedForIteratorType begin ()
FRangedForConstIteratorType begin () const
METASOUNDGRAPHCORE_API void Bind (FOutputVertexInterfaceData &InOutOutputVertexData)
Bind vertex data using other vertex data.
template<typename DataType>
void BindReadVertex (const FVertexName &InVertexName, TDataReadReference< DataType > &InOutDataReference)
Bind a read vertex from a read reference.
template<typename DataType>
void BindReadVertex (const FVertexName &InVertexName, TDataWriteReference< DataType > &InOutDataReference)
Bind a read vertex from a write reference.
template<typename DataReferenceType>
void BindVertex (const FVertexName &InVertexName, DataReferenceType &InOutDataReference)
Bind a vertex with a data reference.
METASOUNDGRAPHCORE_API void BindVertex (const FVertexName &InVertexName, FAnyDataReference &InOutDataReference)
Bind a vertex with any data reference.
template<typename DataType>
void BindWriteVertex (const FVertexName &InVertexName, TDataWriteReference< DataType > &InOutDataReference)
Bind a write vertex from a write reference.
METASOUNDGRAPHCORE_API bool Contains (const FVertexName &InVertexName) const
Returns true if a vertex exists with the provided name.
FRangedForIteratorType end ()
FRangedForConstIteratorType end () const
METASOUNDGRAPHCORE_API const FAnyDataReference * FindDataReference (const FVertexName &InVertexName) const
Find data reference bound to vertex.
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InOutDataReferences.Num(), BindData)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InOutDataReferences.Num(), BindData)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InOutDataReferences.Num(), BindData)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InValues.Num(), BindData)
template<typename DataType>
TDataReadReference< DataType > GetDataReadReference (const FVertexName &InVertexName) const
Get data read reference assuming data is bound and read or write accessible.
template<typename DataType>
TDataWriteReference< DataType > GetDataWriteReference (const FVertexName &InVertexName) const
Get data write reference assuming data is bound and write accessible.
template<typename DataType, typename ... ConstructorArgTypes>
TDataReadReference< DataType > GetOrConstructDataReadReference (const FVertexName &InVertexName, ConstructorArgTypes &&... ConstructorArgs) const
Get the bound data read reference if it exists.
template<typename DataType, typename ... ConstructorArgTypes>
TDataWriteReference< DataType > GetOrConstructDataWriteReference (const FVertexName &InVertexName, ConstructorArgTypes &&... ConstructorArgs) const
Get the bound data write reference if it exists.
template<typename DataType>
const DataType * GetValue (const FVertexName &InVertexName) const
Returns the current value of a vertex.
METASOUNDGRAPHCORE_API const FOutputDataVertex & GetVertex (const FVertexName &InVertexName) const
Return the vertex associated with the vertex name.
METASOUNDGRAPHCORE_API EDataReferenceAccessType GetVertexDataAccessType (const FVertexName &InVertexName) const
Returns the access type of a bound vertex.
METASOUNDGRAPHCORE_API bool IsVertexBound (const FVertexName &InVertexName) const
Returns true if a vertex with the given vertex name exists and is bound to a data reference.
METASOUNDGRAPHCORE_API bool IsVertexInterfaceFrozen () const
Returns true if the vertex interface is frozen.
METASOUNDGRAPHCORE_API void RemoveVertex (const FVertexName &InVertexName)
Remove a vertex.
METASOUNDGRAPHCORE_API void SetIsVertexInterfaceFrozen (bool bInIsVertexInterfaceFrozen)
Set whether the vertex interface is frozen or not.
template<typename DataType>
void SetValue (const FVertexName &InVertexName, const DataType &InValue)
Set the value of a vertex.
METASOUNDGRAPHCORE_API void SetVertex (const FVertexName &InVertexName, const FAnyDataReference &InDataReference)
Set a data reference to a vertex, ignoring any existing data bound to the vertex.
METASOUNDGRAPHCORE_API void SetVertex (const FVertexName &InVertexName, FAnyDataReference &&InDataReference)
Set a data reference to a vertex, ignoring any existing data bound to the vertex.
UE_DEPRECATED (5.6, "Do not use FDataReferenceCollection.") METASOUNDGRAPHCORE_API FDataReferenceCollection ToDataReferenceCollection() const
Converts the vertex data to a data reference collection.
UE_DEPRECATED (5.6, "Do not use FDataReferenceCollection.") METASOUNDGRAPHCORE_API void Set(const FDataReferenceCollection &InCollection)
Set a data references to vertices with matching vertex names.
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") METASOUNDGRAPHCORE_API void Bind(const FOutputVertexInterfaceData &InOutOutputVertexData)
Bind vertex data using other vertex data.
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") METASOUNDGRAPHCORE_API void BindVertex(const FVertexName &InVertexName
Bind a vertex with a any data reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindReadVertex(const FVertexName &InVertexName
Bind a read vertex from a value reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindReadVertex(const FVertexName &InVertexName
Bind a read vertex from a read reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindReadVertex(const FVertexName &InVertexName
Bind a read vertex from a write reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindValueVertex(const FVertexName &InVertexName
Bind a value vertex from a value reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindWriteVertex(const FVertexName &InVertexName
Bind a write vertex from a write reference.
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") METASOUNDGRAPHCORE_API TArray< const FAnyDataReference * > FindSubInterfaceReferences(const FName &InSubInterfaceName
Find data references bound to the sub interface vertices.
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") METASOUNDGRAPHCORE_API uint32 GetNumSubInterfaceInstances(const FName &InSubInterfaceName) const
Return the number of instances of a particular sub interface.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void BindSubInterfaceReadVertices(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex as read references.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void BindSubInterfaceVertices(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void BindSubInterfaceWriteVertices(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex as write references.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void SetSubInterfaceValues(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex as value references.
Data Fields
auto BindData = [&](FOutputBinding& Binding) { Binding.BindValue(InOutDataReference); }
const FVertexName &InVertexName const
const TDataValueReference< DataType > & InOutDataReference
const TDataReadReference< DataType > & InOutDataReference
const TDataWriteReference< DataType > & InOutDataReference
const FAnyDataReference & InOutDataReference
const FName RangeType & InOutDataReferences
const FName const RangeType & InValues
const FName & InVertexName
Private Types
using FOutputBinding = VertexDataPrivate::FOutputBinding
Private Member Functions
METASOUNDGRAPHCORE_API void Apply (const FVertexName &InVertexName, TFunctionRef< FOutputBinding()> InCreateFunc, TFunctionRef< void(FOutputBinding &)> InBindFunc)
METASOUNDGRAPHCORE_API FOutputBinding * Find (const FVertexName &InVertexName)
METASOUNDGRAPHCORE_API const FOutputBinding * Find (const FVertexName &InVertexName) const
METASOUNDGRAPHCORE_API FOutputBinding * FindChecked (const FVertexName &InVertexName)
METASOUNDGRAPHCORE_API const FOutputBinding * FindChecked (const FVertexName &InVertexName) const
METASOUNDGRAPHCORE_API const VertexPrivate::FSubInterfaceLayout * FindSubInterface (const FName &InSubInterfaceName) const
METASOUNDGRAPHCORE_API void ForEachSubInterfaceBinding (const FName &InSubInterfaceName, const FVertexName &InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, const FOutputBinding &)> InApplyFunc) const
METASOUNDGRAPHCORE_API void ForEachSubInterfaceBinding (const FName &InSubInterfaceName, const FVertexName &InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, FOutputBinding &)> InApplyFunc)
Private Attributes
TArray< FOutputBinding > Bindings
bool bIsVertexInterfaceFrozen = false
TArray< VertexPrivate::FSubInterfaceLayout > SubInterfaces
Friends
METASOUNDGRAPHCORE_API void CompareVertexInterfaceDataToPriorState (const FOutputVertexInterfaceData &InCurrentInterface, const TArray< FVertexDataState > &InPriorState, TSortedVertexNameMap< FAnyDataReference > &OutUpdates)
Compares the current data bound to the vertex interface with a prior cached state.
METASOUNDGRAPHCORE_API void GetVertexInterfaceDataState (const FOutputVertexInterfaceData &InVertexInterface, TArray< FVertexDataState > &OutState)
Caches a representation of the current data references bound to the vertex interface.
Detailed Description
An output vertex interface with optionally bound data references.
Definition at line 1002 of file MetasoundVertexData.h.
Member Typedef Documentation
FOutputBinding
using Metasound::FOutputVertexInterfaceData::FOutputBinding = VertexDataPrivate::FOutputBinding private
Definition at line 1004 of file MetasoundVertexData.h.
FRangedForConstIteratorType
using Metasound::FOutputVertexInterfaceData::FRangedForConstIteratorType = typename TArray<FOutputBinding>::RangedForConstIteratorType
Definition at line 1009 of file MetasoundVertexData.h.
FRangedForIteratorType
using Metasound::FOutputVertexInterfaceData::FRangedForIteratorType = typename TArray<FOutputBinding>::RangedForIteratorType
Definition at line 1008 of file MetasoundVertexData.h.
Constructor & Destructor Documentation
FOutputVertexInterfaceData() [1/2]
METASOUNDGRAPHCORE_API Metasound::FOutputVertexInterfaceData::FOutputVertexInterfaceData ()
Construct with an FOutputVertexInterface.
This will default to a unfrozen vertex interface.
References UE_API.
Referenced by Bind(), CompareVertexInterfaceDataToPriorState, GetVertexInterfaceDataState, and UE_DEPRECATED().
FOutputVertexInterfaceData() [2/2]
METASOUNDGRAPHCORE_API Metasound::FOutputVertexInterfaceData::FOutputVertexInterfaceData (const FOutputVertexInterface & InVertexInterface)
Construct with an FOutputVertexInterface.
This will default to a frozen vertex interface.
References UE_API.
Member Function Documentation
AddVertex()
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::AddVertex (const FOutputDataVertex & InVertex)
Add a vertex.
VertexInterfaceData must be unfrozen.
References AddVertex(), const, and UE_API.
Referenced by AddVertex().
Apply() [1/2]
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::Apply (const FVertexName & InVertexName, TFunctionRef< FOutputBinding()> InCreateFunc, TFunctionRef< void(FOutputBinding &)> InBindFunc) private
References Apply(), const, InVertexName, and UE_API.
Apply() [2/2]
Metasound::FOutputVertexInterfaceData::Apply (InVertexName , TCreateOutputBinding(InVertexName, InOutDataReference) , BindData)
References BindData, InOutDataReference, and InVertexName.
Referenced by Apply().
AreAllVerticesBound()
METASOUNDGRAPHCORE_API bool Metasound::FOutputVertexInterfaceData::AreAllVerticesBound () const
Returns true if all vertices in the FInputVertexInterface are bound to data references.
References AreAllVerticesBound(), const, and UE_API.
Referenced by AreAllVerticesBound().
begin() [1/2]
FRangedForIteratorType Metasound::FOutputVertexInterfaceData::begin () inline
Definition at line 1249 of file MetasoundVertexData.h.
References begin(), and Bindings.
Referenced by begin().
begin() [2/2]
FRangedForConstIteratorType Metasound::FOutputVertexInterfaceData::begin () const inline
Definition at line 1259 of file MetasoundVertexData.h.
References Bindings.
Bind()
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::Bind (FOutputVertexInterfaceData & InOutOutputVertexData)
Bind vertex data using other vertex data.
References FOutputVertexInterfaceData(), Bind(), and UE_API.
Referenced by Bind(), and UE_DEPRECATED().
BindReadVertex() [1/2]
template<typename DataType> void Metasound::FOutputVertexInterfaceData::BindReadVertex (const FVertexName & InVertexName, TDataReadReference< DataType > & InOutDataReference) inline
Bind a read vertex from a read reference.
Definition at line 1075 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::Apply(), BindData, InOutDataReference, and InVertexName.
Referenced by Metasound::TVariable< DataType >::BindDataReference(), Metasound::TVariable< DataType >::BindDelayedDataReference(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::BindOutputs(), Metasound::TArrayConcatOperator< ArrayType >::BindOutputs(), Metasound::TArrayGetOperator< ArrayType >::BindOutputs(), Metasound::TArrayLastIndexOperator< ArrayType >::BindOutputs(), Metasound::TArrayNumOperator< ArrayType >::BindOutputs(), Metasound::TArrayRandomGetOperator< ArrayType >::BindOutputs(), Metasound::TArraySetOperator< ArrayType >::BindOutputs(), Metasound::TArrayShuffleOperator< ArrayType >::BindOutputs(), Metasound::TArraySubsetOperator< ArrayType >::BindOutputs(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::BindOutputs(), and UE_DEPRECATED().
BindReadVertex() [2/2]
template<typename DataType> void Metasound::FOutputVertexInterfaceData::BindReadVertex (const FVertexName & InVertexName, TDataWriteReference< DataType > & InOutDataReference) inline
Bind a read vertex from a write reference.
Definition at line 1092 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::Apply(), BindData, InOutDataReference, and InVertexName.
BindVertex() [1/2]
template<typename DataReferenceType> void Metasound::FOutputVertexInterfaceData::BindVertex (const FVertexName & InVertexName, DataReferenceType & InOutDataReference) inline
Bind a vertex with a data reference.
Definition at line 1122 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::Apply(), BindData, BindVertex(), const, InOutDataReference, and InVertexName.
Referenced by Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::BindOutputs(), and BindVertex().
BindVertex() [2/2]
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::BindVertex (const FVertexName & InVertexName, FAnyDataReference & InOutDataReference)
Bind a vertex with any data reference.
References InOutDataReference, InVertexName, and UE_API.
BindWriteVertex()
template<typename DataType> void Metasound::FOutputVertexInterfaceData::BindWriteVertex (const FVertexName & InVertexName, TDataWriteReference< DataType > & InOutDataReference) inline
Bind a write vertex from a write reference.
Definition at line 1109 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::Apply(), BindData, InOutDataReference, and InVertexName.
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::BindOutputs(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::BindOutputs(), Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::BindOutputs(), Metasound::MetasoundVariableNodesPrivate::TVariableOperator< DataType >::BindOutputs(), and UE_DEPRECATED().
Contains()
METASOUNDGRAPHCORE_API bool Metasound::FOutputVertexInterfaceData::Contains (const FVertexName & InVertexName) const
Returns true if a vertex exists with the provided name.
This does not reflect whether the vertex is bound or not.
References InVertexName, and UE_API.
end() [1/2]
FRangedForIteratorType Metasound::FOutputVertexInterfaceData::end () inline
Definition at line 1254 of file MetasoundVertexData.h.
References Bindings.
end() [2/2]
FRangedForConstIteratorType Metasound::FOutputVertexInterfaceData::end () const inline
Definition at line 1264 of file MetasoundVertexData.h.
References Bindings.
Find() [1/2]
METASOUNDGRAPHCORE_API FOutputBinding * Metasound::FOutputVertexInterfaceData::Find (const FVertexName & InVertexName) private
References const, Find(), InVertexName, and UE_API.
Referenced by Find(), and Find().
Find() [2/2]
METASOUNDGRAPHCORE_API const FOutputBinding * Metasound::FOutputVertexInterfaceData::Find (const FVertexName & InVertexName) const private
References const, Find(), InVertexName, and UE_API.
FindChecked() [1/2]
METASOUNDGRAPHCORE_API FOutputBinding * Metasound::FOutputVertexInterfaceData::FindChecked (const FVertexName & InVertexName) private
References const, FindChecked(), InVertexName, and UE_API.
Referenced by FindChecked(), and FindChecked().
FindChecked() [2/2]
METASOUNDGRAPHCORE_API const FOutputBinding * Metasound::FOutputVertexInterfaceData::FindChecked (const FVertexName & InVertexName) const private
References const, FindChecked(), InVertexName, and UE_API.
FindDataReference()
METASOUNDGRAPHCORE_API const FAnyDataReference * Metasound::FOutputVertexInterfaceData::FindDataReference (const FVertexName & InVertexName) const
Find data reference bound to vertex.
Returns a nullptr if no data reference is bound.
References InVertexName, and UE_API.
FindSubInterface()
METASOUNDGRAPHCORE_API const VertexPrivate::FSubInterfaceLayout * Metasound::FOutputVertexInterfaceData::FindSubInterface (const FName & InSubInterfaceName) const private
References const, FindSubInterface(), and UE_API.
Referenced by FindSubInterface().
ForEachSubInterfaceBinding() [1/6]
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::ForEachSubInterfaceBinding (const FName & InSubInterfaceName, const FVertexName & InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, const FOutputBinding &)> InApplyFunc) const private
References const, ForEachSubInterfaceBinding(), InVertexName, and UE_API.
ForEachSubInterfaceBinding() [2/6]
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::ForEachSubInterfaceBinding (const FName & InSubInterfaceName, const FVertexName & InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, FOutputBinding &)> InApplyFunc) private
References const, ForEachSubInterfaceBinding(), InVertexName, and UE_API.
ForEachSubInterfaceBinding() [3/6]
Metasound::FOutputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InOutDataReferences. Num(), BindData)
References BindData, InOutDataReferences, and InVertexName.
Referenced by ForEachSubInterfaceBinding(), and ForEachSubInterfaceBinding().
ForEachSubInterfaceBinding() [4/6]
Metasound::FOutputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InOutDataReferences. Num(), BindData)
References BindData, InOutDataReferences, and InVertexName.
ForEachSubInterfaceBinding() [5/6]
Metasound::FOutputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InOutDataReferences. Num(), BindData)
References BindData, InOutDataReferences, and InVertexName.
ForEachSubInterfaceBinding() [6/6]
Metasound::FOutputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InValues. Num(), BindData)
References BindData, InValues, and InVertexName.
GetDataReadReference()
template<typename DataType> TDataReadReference< DataType > Metasound::FOutputVertexInterfaceData::GetDataReadReference (const FVertexName & InVertexName) const inline
Get data read reference assuming data is bound and read or write accessible.
Definition at line 1290 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::FindChecked(), Metasound::VertexDataPrivate::FOutputBinding::GetDataReferenceAs(), and InVertexName.
GetDataWriteReference()
template<typename DataType> TDataWriteReference< DataType > Metasound::FOutputVertexInterfaceData::GetDataWriteReference (const FVertexName & InVertexName) const inline
Get data write reference assuming data is bound and write accessible.
Definition at line 1318 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::FindChecked(), Metasound::VertexDataPrivate::FOutputBinding::GetDataReferenceAs(), and InVertexName.
GetOrConstructDataReadReference()
template<typename DataType, typename ... ConstructorArgTypes> TDataReadReference< DataType > Metasound::FOutputVertexInterfaceData::GetOrConstructDataReadReference (const FVertexName & InVertexName, ConstructorArgTypes &&... ConstructorArgs) const inline
Get the bound data read reference if it exists.
Otherwise create and return a data read reference by constructing one the supplied constructor arguments.
Definition at line 1301 of file MetasoundVertexData.h.
References Metasound::TDataReadReference< DataType >::CreateNew(), Find, Forward(), InVertexName, TEXT, UE_LOG, and Warning.
GetOrConstructDataWriteReference()
template<typename DataType, typename ... ConstructorArgTypes> TDataWriteReference< DataType > Metasound::FOutputVertexInterfaceData::GetOrConstructDataWriteReference (const FVertexName & InVertexName, ConstructorArgTypes &&... ConstructorArgs) const inline
Get the bound data write reference if it exists.
Otherwise create and return a data write reference by constructing one the supplied constructor arguments.
Definition at line 1329 of file MetasoundVertexData.h.
References Metasound::TDataWriteReference< DataType >::CreateNew(), Find, Forward(), InVertexName, TEXT, UE_LOG, and Warning.
GetValue()
template<typename DataType> const DataType * Metasound::FOutputVertexInterfaceData::GetValue (const FVertexName & InVertexName) const inline
Returns the current value of a vertex.
Definition at line 1274 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::FindChecked(), Metasound::VertexDataPrivate::FOutputBinding::GetDataReferenceAs(), InVertexName, and Metasound::VertexDataPrivate::FOutputBinding::IsBound().
GetVertex()
METASOUNDGRAPHCORE_API const FOutputDataVertex & Metasound::FOutputVertexInterfaceData::GetVertex (const FVertexName & InVertexName) const
Return the vertex associated with the vertex name.
References const, GetVertex(), InVertexName, and UE_API.
Referenced by GetVertex().
GetVertexDataAccessType()
METASOUNDGRAPHCORE_API EDataReferenceAccessType Metasound::FOutputVertexInterfaceData::GetVertexDataAccessType (const FVertexName & InVertexName) const
Returns the access type of a bound vertex.
If the vertex does not exist or if it is unbound, this will return EDataReferenceAccessType::None
References const, GetVertexDataAccessType(), InVertexName, and UE_API.
Referenced by GetVertexDataAccessType().
IsVertexBound()
METASOUNDGRAPHCORE_API bool Metasound::FOutputVertexInterfaceData::IsVertexBound (const FVertexName & InVertexName) const
Returns true if a vertex with the given vertex name exists and is bound to a data reference.
References const, InVertexName, IsVertexBound(), and UE_API.
Referenced by IsVertexBound().
IsVertexInterfaceFrozen()
METASOUNDGRAPHCORE_API bool Metasound::FOutputVertexInterfaceData::IsVertexInterfaceFrozen () const
Returns true if the vertex interface is frozen.
References UE_API.
RemoveVertex()
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::RemoveVertex (const FVertexName & InVertexName)
Remove a vertex.
VertexInterfaceData must be unfrozen.
References const, InVertexName, RemoveVertex(), and UE_API.
Referenced by RemoveVertex().
SetIsVertexInterfaceFrozen()
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::SetIsVertexInterfaceFrozen (bool bInIsVertexInterfaceFrozen)
Set whether the vertex interface is frozen or not.
If frozen, attempts to access vertices which do not already exist will result in an error.
If not frozen, attempts to bind to a missing vertex will automatically add the missing vertex.
References UE_API.
SetValue()
template<typename DataType> void Metasound::FOutputVertexInterfaceData::SetValue (const FVertexName & InVertexName, const DataType & InValue) inline
Set the value of a vertex.
Definition at line 1035 of file MetasoundVertexData.h.
References Metasound::FInputVertexInterfaceData::Apply(), BindData, Metasound::GetMetasoundDataTypeName(), InVertexName, Metasound::Value, and Vertex.
SetVertex() [1/2]
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::SetVertex (const FVertexName & InVertexName, const FAnyDataReference & InDataReference)
Set a data reference to a vertex, ignoring any existing data bound to the vertex.
References const, InVertexName, SetVertex(), and UE_API.
Referenced by SetVertex(), and SetVertex().
SetVertex() [2/2]
METASOUNDGRAPHCORE_API void Metasound::FOutputVertexInterfaceData::SetVertex (const FVertexName & InVertexName, FAnyDataReference && InDataReference)
Set a data reference to a vertex, ignoring any existing data bound to the vertex.
References const, InVertexName, SetVertex(), and UE_API.
UE_DEPRECATED() [1/9]
Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Do not use FDataReferenceCollection.") const
Converts the vertex data to a data reference collection.
References const, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [2/9]
Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Do not use FDataReferenceCollection.") const &
Set a data references to vertices with matching vertex names.
References const, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [3/9]
Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind vertex data using other vertex data.
References FOutputVertexInterfaceData(), Bind(), const, and UE_API.
UE_DEPRECATED() [4/9]
Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a vertex with a any data reference.
UE_DEPRECATED() [5/9]
template<typename DataType> Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a read vertex from a value reference.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), BindReadVertex(), const, InOutDataReference, and InVertexName.
UE_DEPRECATED() [6/9]
template<typename DataType> Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a read vertex from a read reference.
UE_DEPRECATED() [7/9]
template<typename DataType> Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a read vertex from a write reference.
UE_DEPRECATED() [8/9]
template<typename DataType> Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a value vertex from a value reference.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [9/9]
template<typename DataType> Metasound::FOutputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a write vertex from a write reference.
References Metasound::FInputVertexInterfaceData::BindWriteVertex(), BindWriteVertex(), const, InOutDataReference, and InVertexName.
UE_EXPERIMENTAL() [1/6]
Metasound::FOutputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Find data references bound to the sub interface vertices.
If there is no bound data for a sub interface instance, the array element will be a nullptr.
Parameters
InSubInterfaceName - Name of the sub interface
InVertexName - Name of the prototype vertex in the sub interface.
UE_EXPERIMENTAL() [2/6]
Metasound::FOutputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Return the number of instances of a particular sub interface.
References const, and UE_API.
Referenced by UE_EXPERIMENTAL().
UE_EXPERIMENTAL() [3/6]
template<typename RangeType> Metasound::FOutputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex as read references.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
References BindData, const, InOutDataReferences, and InVertexName.
UE_EXPERIMENTAL() [4/6]
template<typename RangeType> Metasound::FOutputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
References UE_EXPERIMENTAL().
UE_EXPERIMENTAL() [5/6]
template<typename RangeType> Metasound::FOutputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex as write references.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
References BindData, const, InOutDataReferences, and InVertexName.
UE_EXPERIMENTAL() [6/6]
template<typename RangeType> Metasound::FOutputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex as value references.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
Friends And Related Symbol Documentation
CompareVertexInterfaceDataToPriorState
METASOUNDGRAPHCORE_API void CompareVertexInterfaceDataToPriorState (const FOutputVertexInterfaceData & InCurrentInterface, const TArray< FVertexDataState > & InPriorState, TSortedVertexNameMap< FAnyDataReference > & OutUpdates) friend
Compares the current data bound to the vertex interface with a prior cached state.
References FOutputVertexInterfaceData(), CompareVertexInterfaceDataToPriorState, and const.
Referenced by CompareVertexInterfaceDataToPriorState.
GetVertexInterfaceDataState
METASOUNDGRAPHCORE_API void GetVertexInterfaceDataState (const FOutputVertexInterfaceData & InVertexInterface, TArray< FVertexDataState > & OutState) friend
Caches a representation of the current data references bound to the vertex interface.
References FOutputVertexInterfaceData(), const, and GetVertexInterfaceDataState.
Referenced by GetVertexInterfaceDataState.
Field Documentation
BindData
auto Metasound::FOutputVertexInterfaceData::BindData = [&](FOutputBinding& Binding) { Binding.BindValue(InOutDataReference); }
Definition at line 1053 of file MetasoundVertexData.h.
Referenced by Apply(), BindReadVertex(), BindReadVertex(), BindVertex(), BindWriteVertex(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), SetValue(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
Bindings
TArray<FOutputBinding> Metasound::FOutputVertexInterfaceData::Bindings private
Definition at line 1370 of file MetasoundVertexData.h.
Referenced by begin(), begin(), end(), and end().
bIsVertexInterfaceFrozen
bool Metasound::FOutputVertexInterfaceData::bIsVertexInterfaceFrozen = false private
Definition at line 1369 of file MetasoundVertexData.h.
const
const FVertexName& InVertexName Metasound::FOutputVertexInterfaceData::const
Definition at line 1352 of file MetasoundVertexData.h.
Referenced by AddVertex(), Apply(), AreAllVerticesBound(), BindVertex(), CompareVertexInterfaceDataToPriorState, Find(), Find(), FindChecked(), FindChecked(), FindSubInterface(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), GetVertex(), GetVertexDataAccessType(), GetVertexInterfaceDataState, IsVertexBound(), RemoveVertex(), SetVertex(), SetVertex(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InOutDataReference [1/4]
const TDataWriteReference< DataType > & Metasound::FOutputVertexInterfaceData::InOutDataReference
Initial value:
{
            using namespace VertexDataPrivate
Definition at line 1050 of file MetasoundVertexData.h.
Referenced by Apply(), BindReadVertex(), BindReadVertex(), BindVertex(), BindVertex(), BindWriteVertex(), UE_DEPRECATED(), and UE_DEPRECATED().
InOutDataReference [2/4]
const TDataReadReference<DataType>& Metasound::FOutputVertexInterfaceData::InOutDataReference
Initial value:
{
            BindReadVertex(InVertexName, const_cast<TDataReadReference<DataType>&>(InOutDataReference))
Definition at line 1068 of file MetasoundVertexData.h.
InOutDataReference [3/4]
const TDataWriteReference<DataType>& Metasound::FOutputVertexInterfaceData::InOutDataReference
Initial value:
{
            BindReadVertex(InVertexName, const_cast<TDataWriteReference<DataType>&>(InOutDataReference))
Definition at line 1085 of file MetasoundVertexData.h.
InOutDataReference [4/4]
const FAnyDataReference& Metasound::FOutputVertexInterfaceData::InOutDataReference
Definition at line 1118 of file MetasoundVertexData.h.
InOutDataReferences
const FName RangeType & Metasound::FOutputVertexInterfaceData::InOutDataReferences
Initial value:
{
            using namespace VertexDataPrivate
Definition at line 1143 of file MetasoundVertexData.h.
Referenced by ForEachSubInterfaceBinding(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InValues
const FName const RangeType& Metasound::FOutputVertexInterfaceData::InValues
Initial value:
{
            using namespace VertexDataPrivate
Definition at line 1197 of file MetasoundVertexData.h.
Referenced by ForEachSubInterfaceBinding().
InVertexName
const FName & Metasound::FOutputVertexInterfaceData::InVertexName
Definition at line 1143 of file MetasoundVertexData.h.
Referenced by Apply(), Apply(), BindReadVertex(), BindReadVertex(), BindVertex(), BindVertex(), BindWriteVertex(), Contains(), Find(), Find(), FindChecked(), FindChecked(), FindDataReference(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), GetDataReadReference(), GetDataWriteReference(), GetOrConstructDataReadReference(), GetOrConstructDataWriteReference(), GetValue(), GetVertex(), GetVertexDataAccessType(), IsVertexBound(), RemoveVertex(), SetValue(), SetVertex(), SetVertex(), UE_DEPRECATED(), UE_DEPRECATED(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
SubInterfaces
TArray<VertexPrivate::FSubInterfaceLayout> Metasound::FOutputVertexInterfaceData::SubInterfaces private
Definition at line 1371 of file MetasoundVertexData.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertexData.h