Unreal Engine 5.6 C++ API: FThreadSafeCounter Class Reference
FThreadSafeCounter Class Reference
Thread safe counter.
#include "ThreadSafeCounter.h"
Public Types
using IntegerType = int32
Public Member Functions
FThreadSafeCounter (const FThreadSafeCounter &Other)
Copy Constructor.
FThreadSafeCounter (int32 Value=0)
Constructor, initializing counter to passed in value.
int32 Add (int32 Amount)
Adds an amount and returns the old value.
int32 Decrement ()
Decrement and return new value.
int32 GetValue () const
Gets the current value.
int32 Increment ()
Increment and return new value.
int32 Reset ()
Resets the counter's value to zero.
int32 Set (int32 Value)
Sets the counter to a specific value and returns the old value.
int32 Subtract (int32 Amount)
Subtracts an amount and returns the old value.
Private Member Functions
void operator= (const FThreadSafeCounter &Other)=delete
Assignment is intentionally disallowed, as usage wouldn't be thread safe.
Private Attributes
volatile int32 Counter
Thread-safe counter.
Detailed Description
Thread safe counter.
Definition at line 13 of file ThreadSafeCounter.h.
Member Typedef Documentation
IntegerType
using FThreadSafeCounter::IntegerType = int32
Definition at line 16 of file ThreadSafeCounter.h.
Constructor & Destructor Documentation
FThreadSafeCounter() [1/2]
FThreadSafeCounter::FThreadSafeCounter (int32 Value = 0) inline
Constructor, initializing counter to passed in value.
Parameters
Value Value to initialize counter to
Definition at line 23 of file ThreadSafeCounter.h.
References Counter, and Value.
Referenced by FThreadSafeBool::FThreadSafeBool(), FThreadSafeCounter(), and operator=().
FThreadSafeCounter() [2/2]
FThreadSafeCounter::FThreadSafeCounter (const FThreadSafeCounter & Other) inline
Copy Constructor.
If the counter in the Other parameter is changing from other threads, there are no guarantees as to which values you will get up to the caller to not care, synchronize or other way to make those guarantees.
Parameters
Other The other thread safe counter to copy
Definition at line 41 of file ThreadSafeCounter.h.
References FThreadSafeCounter(), GetValue(), and Other.
Member Function Documentation
Add()
int32 FThreadSafeCounter::Add (int32 Amount) inline
Adds an amount and returns the old value.
Parameters
Amount Amount to increase the counter by
Returns
the old value
See also
Decrement, Increment, Reset, Set, Subtract
Definition at line 64 of file ThreadSafeCounter.h.
References Counter.
Decrement()
int32 FThreadSafeCounter::Decrement () inline
Decrement and return new value.
Returns
the new, decremented value
See also
Add, Increment, Reset, Set, Subtract
Definition at line 75 of file ThreadSafeCounter.h.
References Counter.
Referenced by FQuartzTickableObject::OnCommandEvent().
GetValue()
int32 FThreadSafeCounter::GetValue () const inline
Gets the current value.
Returns
the current value
Definition at line 120 of file ThreadSafeCounter.h.
References Counter.
Referenced by FThreadSafeCounter(), and FThreadSafeBool::operator bool().
Increment()
int32 FThreadSafeCounter::Increment () inline
Increment and return new value.
Returns
the new, incremented value
See also
Add, Decrement, Reset, Set, Subtract
Definition at line 52 of file ThreadSafeCounter.h.
References Counter.
Referenced by FQuartzTickableObject::OnCommandEvent().
operator=()
void FThreadSafeCounter::operator= (const FThreadSafeCounter & Other) private delete
Assignment is intentionally disallowed, as usage wouldn't be thread safe.
References FThreadSafeCounter(), and Other.
Reset()
int32 FThreadSafeCounter::Reset () inline
Resets the counter's value to zero.
Returns
the old value.
See also
Add, Decrement, Increment, Set, Subtract
Definition at line 110 of file ThreadSafeCounter.h.
References Set().
Referenced by FQuartzTickableObject::OnCommandEvent().
Set()
int32 FThreadSafeCounter::Set (int32 Value) inline
Sets the counter to a specific value and returns the old value.
Parameters
Value Value to set the counter to
Returns
The old value
See also
Add, Decrement, Increment, Reset, Subtract
Definition at line 99 of file ThreadSafeCounter.h.
References Counter, and Value.
Referenced by FThreadSafeBool::AtomicSet(), FThreadSafeBool::operator=(), and Reset().
Subtract()
int32 FThreadSafeCounter::Subtract (int32 Amount) inline
Subtracts an amount and returns the old value.
Parameters
Amount Amount to decrease the counter by
Returns
the old value
See also
Add, Decrement, Increment, Reset, Set
Definition at line 87 of file ThreadSafeCounter.h.
References Counter.
Field Documentation
Counter
volatile int32 FThreadSafeCounter::Counter private
Thread-safe counter.
Definition at line 131 of file ThreadSafeCounter.h.
Referenced by FThreadSafeCounter(), Add(), Decrement(), GetValue(), Increment(), Set(), and Subtract().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/ThreadSafeCounter.h