Unreal Engine 5.6 C++ API: GPUMessage::FSocket Class Reference
GPUMessage::FSocket Class Reference
A socket object mapped to a persistently registered handler.
#include "GPUMessaging.h"
Public Member Functions
FSocket ()=default
FSocket (FSocket &&Other)
~FSocket ()
const FMessageId GetMessageId () const
FSocket & operator= (FSocket &&Other)
RENDERCORE_API void Reset ()
Private Member Functions
FSocket (FMessageId InMessageId)
Private Attributes
friend FSystem
FMessageId MessageId
Detailed Description
A socket object mapped to a persistently registered handler.
Supports only move construction. Will unregister the handler on destruction.
Definition at line 39 of file GPUMessaging.h.
Constructor & Destructor Documentation
FSocket() [1/3]
GPUMessage::FSocket::FSocket () default
Referenced by FSocket(), and operator=().
FSocket() [2/3]
GPUMessage::FSocket::FSocket (FSocket && Other) inline
Definition at line 44 of file GPUMessaging.h.
References FSocket(), MoveTemp(), and Other.
~FSocket()
GPUMessage::FSocket::~FSocket () inline
Definition at line 57 of file GPUMessaging.h.
References Reset().
FSocket() [3/3]
GPUMessage::FSocket::FSocket (FMessageId InMessageId) inline private
Definition at line 67 of file GPUMessaging.h.
References MessageId.
Member Function Documentation
GetMessageId()
const FMessageId GPUMessage::FSocket::GetMessageId () const inline
Definition at line 62 of file GPUMessaging.h.
References MessageId.
operator=()
FSocket & GPUMessage::FSocket::operator= (FSocket && Other) inline
Definition at line 49 of file GPUMessaging.h.
References FSocket(), MessageId, TRDGHandle< FSocket, uint32 >::Null, Other, and Reset().
Reset()
RENDERCORE_API void GPUMessage::FSocket::Reset ()
Referenced by ~FSocket(), and operator=().
Field Documentation
FSystem
friend GPUMessage::FSocket::FSystem private
Definition at line 73 of file GPUMessaging.h.
MessageId
FMessageId GPUMessage::FSocket::MessageId private
Definition at line 71 of file GPUMessaging.h.
Referenced by FSocket(), GetMessageId(), and operator=().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/GPUMessaging.h