Unreal Engine 5.6 C++ API: FAndroidWindow Class Reference
FAndroidWindow Class Reference
A platform specific implementation of FNativeWindow.
#include "AndroidWindow.h"
Data Structures
class FNativeAccessor
Public Member Functions
APPLICATIONCORE_API ~FAndroidWindow ()
virtual APPLICATIONCORE_API void Destroy () override
Native windows should implement this function by asking the OS to destroy OS-specific resource associated with the window (e.g.
FNativeAccessor GetANativeAccessor (bool bWriteAccess)
virtual APPLICATIONCORE_API bool GetFullScreenInfo (int32 &X, int32 &Y, int32 &Width, int32 &Height) const override
Returns the rectangle of the screen the window is associated with.
APPLICATIONCORE_API bool GetNativeWindowResolution (int32_t &OutWidth, int32_t &OutHeight) const
virtual void * GetOSWindowHandle () const override
Gets the OS Window handle in the form of a void pointer for other API's.
APPLICATIONCORE_API void Initialize (class FAndroidApplication *const Application, const TSharedRef< FGenericWindowDefinition > &InDefinition, const TSharedPtr< FAndroidWindow > &InParent, const bool bShowImmediately)
virtual APPLICATIONCORE_API void SetOSWindowHandle (void *)
virtual void SetWindowMode (EWindowMode::Type InNewWindowMode)
Toggle native window between fullscreen and normal mode.
Public Member Functions inherited from FGenericWindow
APPLICATIONCORE_API FGenericWindow ()
virtual APPLICATIONCORE_API ~FGenericWindow ()
virtual APPLICATIONCORE_API void AdjustCachedSize (FVector2D &Size) const
virtual APPLICATIONCORE_API void BringToFront (bool bForce=false)
Native windows should implement BringToFront by making this window the top-most window (i.e.
virtual APPLICATIONCORE_API void DrawAttention (const FWindowDrawAttentionParameters &Parameters)
Attempts to draw the user's attention to this window in whatever way is appropriate for the platform if this window is not the current active window.
virtual APPLICATIONCORE_API void Enable (bool bEnable)
Enables or disables the window.
virtual APPLICATIONCORE_API const FGenericWindowDefinition & GetDefinition () const
virtual APPLICATIONCORE_API float GetDPIScaleFactor () const
virtual APPLICATIONCORE_API bool GetRestoredDimensions (int32 &X, int32 &Y, int32 &Width, int32 &Height)
Populates the size and location of the window when it is restored.
virtual APPLICATIONCORE_API int32 GetWindowBorderSize () const
Gets OS specific window border size.
virtual APPLICATIONCORE_API int32 GetWindowTitleBarSize () const
Gets OS specific window title bar size.
virtual APPLICATIONCORE_API void HACK_ForceToFront ()
@hack Force a window to front even if a different application is in front.
virtual APPLICATIONCORE_API void Hide ()
Native window should hide itself.
virtual APPLICATIONCORE_API bool IsDefinitionValid () const
virtual APPLICATIONCORE_API bool IsForegroundWindow () const
virtual APPLICATIONCORE_API bool IsFullscreenSupported () const
virtual APPLICATIONCORE_API bool IsManualManageDPIChanges () const
determines whether or not this window does its own DPI management
virtual APPLICATIONCORE_API bool IsMaximized () const
virtual APPLICATIONCORE_API bool IsMinimized () const
virtual APPLICATIONCORE_API bool IsPointInWindow (int32 X, int32 Y) const
virtual APPLICATIONCORE_API bool IsVisible () const
virtual APPLICATIONCORE_API void Maximize ()
Native window should implement this function by performing the equivalent of the Win32 maximize operation.
virtual APPLICATIONCORE_API void Minimize ()
Native window should implement this function by performing the equivalent of the Win32 minimize-to-taskbar operation.
virtual APPLICATIONCORE_API void MoveWindowTo (int32 X, int32 Y)
Native windows should implement MoveWindowTo by relocating the platform-specific window to (X,Y).
virtual APPLICATIONCORE_API void ReshapeWindow (int32 X, int32 Y, int32 Width, int32 Height)
Native windows should implement ReshapeWindow by changing the platform-specific window to be located at (X,Y) and be the dimensions Width x Height.
virtual APPLICATIONCORE_API void Restore ()
Native window should implement this function by performing the equivalent of the Win32 restore operation.
virtual APPLICATIONCORE_API void SetDPIScaleFactor (const float Factor)
sets a new DPI scale factor
virtual APPLICATIONCORE_API void SetManualManageDPIChanges (const bool bAutoHandle)
call with a true argument if this window need to do its custom size management in response to DPI variations
virtual APPLICATIONCORE_API void SetNativeWindowButtonsVisibility (bool bVisible)
Shows or hides native window buttons on platforms that use them.
virtual APPLICATIONCORE_API void SetOpacity (const float InOpacity)
Sets the opacity of this window.
virtual APPLICATIONCORE_API void SetText (const TCHAR *const Text)
Sets the window text - usually the title but can also be text content for things like controls.
virtual APPLICATIONCORE_API void SetWindowFocus ()
Native windows should implement SetWindowFocus to let the OS know that a window has taken focus.
virtual APPLICATIONCORE_API void Show ()
Native window should make itself visible.
Public Member Functions inherited from TSharedFromThis< FAndroidWindow >
TSharedRef< FAndroidWindow, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAndroidWindow, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static APPLICATIONCORE_API void AcquireWindowRef (ANativeWindow *InWindow)
static APPLICATIONCORE_API void CalculateSurfaceSize (int32_t &SurfaceWidth, int32_t &SurfaceHeight, bool bUseEventThreadWindow=false)
static APPLICATIONCORE_API void EventManagerUpdateWindowDimensions (int32 Width, int32 Height)
static APPLICATIONCORE_API int32 GetDepthBufferPreference ()
static APPLICATIONCORE_API void * GetHardwareWindow_EventThread ()
static APPLICATIONCORE_API FVector4 GetSafezone (bool bPortrait)
static APPLICATIONCORE_API FPlatformRect GetScreenRect (bool bUseEventThreadWindow=false)
static APPLICATIONCORE_API void InvalidateCachedScreenRect ()
static APPLICATIONCORE_API bool IsPortraitOrientation ()
static APPLICATIONCORE_API TSharedRef< FAndroidWindow > Make ()
Create a new FAndroidWindow.
static APPLICATIONCORE_API bool OnWindowOrientationChanged (EDeviceScreenOrientation DeviceScreenOrientation)
static APPLICATIONCORE_API void ReleaseWindowRef (ANativeWindow *InWindow)
static APPLICATIONCORE_API void SetHardwareWindow_EventThread (void *InWindow)
static APPLICATIONCORE_API void SetWindowDimensions_EventThread (ANativeWindow *DimensionWindow)
static APPLICATIONCORE_API void * WaitForHardwareWindow ()
Waits on the current thread for a hardware window and returns it.
Protected Member Functions
virtual EWindowMode::Type GetWindowMode () const override
Protected Member Functions inherited from TSharedFromThis< FAndroidWindow >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
APPLICATIONCORE_API FAndroidWindow ()
Protect the constructor; only TSharedRefs of this class can be made.
Static Private Member Functions
static APPLICATIONCORE_API bool WaitForWindowDimensions ()
Private Attributes
UE::FSharedMutex ANativeHandleMutex
ANativeWindow * CurrentANativeHandle = nullptr
FAndroidApplication * OwningApplication
ANativeWindow * PreviousANativeHandle = nullptr
EWindowMode::Type WindowMode = EWindowMode::Fullscreen
Static Private Attributes
static APPLICATIONCORE_API bool bAreCachedNativeDimensionsValid
static APPLICATIONCORE_API int32 CachedNativeWindowHeight
static APPLICATIONCORE_API int32 CachedNativeWindowWidth
static APPLICATIONCORE_API void * NativeWindow
Friends
class FAndroidWindowManager
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FAndroidWindow >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FGenericWindow
TSharedPtr< FGenericWindowDefinition > Definition
Detailed Description
A platform specific implementation of FNativeWindow.
Native windows provide platform-specific backing for and are always owned by an SWindow.
Definition at line 21 of file AndroidWindow.h.
Constructor & Destructor Documentation
~FAndroidWindow()
APPLICATIONCORE_API FAndroidWindow::~FAndroidWindow ()
FAndroidWindow()
APPLICATIONCORE_API FAndroidWindow::FAndroidWindow () private
Protect the constructor; only TSharedRefs of this class can be made.
Referenced by FAndroidWindow::FNativeAccessor::FNativeAccessor(), FAndroidWindow::FNativeAccessor::Get(), FAndroidWindow::FNativeAccessor::Get(), FAndroidWindow::FNativeAccessor::operator->(), and FAndroidWindow::FNativeAccessor::operator->().
Member Function Documentation
AcquireWindowRef()
APPLICATIONCORE_API void FAndroidWindow::AcquireWindowRef (ANativeWindow * InWindow) static
CalculateSurfaceSize()
APPLICATIONCORE_API void FAndroidWindow::CalculateSurfaceSize (int32_t & SurfaceWidth, int32_t & SurfaceHeight, bool bUseEventThreadWindow = false) static
Destroy()
virtual APPLICATIONCORE_API void FAndroidWindow::Destroy () override virtual
Native windows should implement this function by asking the OS to destroy OS-specific resource associated with the window (e.g.
Win32 window handle)
Reimplemented from FGenericWindow.
EventManagerUpdateWindowDimensions()
APPLICATIONCORE_API void FAndroidWindow::EventManagerUpdateWindowDimensions (int32 Width, int32 Height) static
References Width.
GetANativeAccessor()
FNativeAccessor FAndroidWindow::GetANativeAccessor (bool bWriteAccess) inline
Definition at line 136 of file AndroidWindow.h.
Referenced by FAndroidWindowManager::FindFromANativeWindow().
GetDepthBufferPreference()
APPLICATIONCORE_API int32 FAndroidWindow::GetDepthBufferPreference () static
GetFullScreenInfo()
virtual APPLICATIONCORE_API bool FAndroidWindow::GetFullScreenInfo (int32 & X, int32 & Y, int32 & Width, int32 & Height) const override virtual
Returns the rectangle of the screen the window is associated with.
Reimplemented from FGenericWindow.
References Width, X, and Y.
GetHardwareWindow_EventThread()
APPLICATIONCORE_API void * FAndroidWindow::GetHardwareWindow_EventThread () static
GetNativeWindowResolution()
APPLICATIONCORE_API bool FAndroidWindow::GetNativeWindowResolution (int32_t & OutWidth, int32_t & OutHeight) const
GetOSWindowHandle()
virtual void * FAndroidWindow::GetOSWindowHandle () const inline override virtual
Gets the OS Window handle in the form of a void pointer for other API's.
Reimplemented from FGenericWindow.
Definition at line 35 of file AndroidWindow.h.
GetSafezone()
APPLICATIONCORE_API FVector4 FAndroidWindow::GetSafezone (bool bPortrait) static
GetScreenRect()
APPLICATIONCORE_API FPlatformRect FAndroidWindow::GetScreenRect (bool bUseEventThreadWindow = false) static
GetWindowMode()
virtual EWindowMode::Type FAndroidWindow::GetWindowMode () const inline override protected virtual
Returns
true if the native window is currently in fullscreen mode, false otherwise
Reimplemented from FGenericWindow.
Definition at line 143 of file AndroidWindow.h.
References WindowMode.
Initialize()
APPLICATIONCORE_API void FAndroidWindow::Initialize (class FAndroidApplication *const Application, const TSharedRef< FGenericWindowDefinition > & InDefinition, const TSharedPtr< FAndroidWindow > & InParent, const bool bShowImmediately)
InvalidateCachedScreenRect()
APPLICATIONCORE_API void FAndroidWindow::InvalidateCachedScreenRect () static
IsPortraitOrientation()
APPLICATIONCORE_API bool FAndroidWindow::IsPortraitOrientation () static
Make()
APPLICATIONCORE_API TSharedRef< FAndroidWindow > FAndroidWindow::Make () static
Create a new FAndroidWindow.
Parameters
OwnerWindow The SlateWindow for which we are crating a backing AndroidWindow
InParent Parent iOS window; usually NULL.
OnWindowOrientationChanged()
APPLICATIONCORE_API bool FAndroidWindow::OnWindowOrientationChanged (EDeviceScreenOrientation DeviceScreenOrientation) static
ReleaseWindowRef()
APPLICATIONCORE_API void FAndroidWindow::ReleaseWindowRef (ANativeWindow * InWindow) static
SetHardwareWindow_EventThread()
APPLICATIONCORE_API void FAndroidWindow::SetHardwareWindow_EventThread (void * InWindow) static
SetOSWindowHandle()
virtual APPLICATIONCORE_API void FAndroidWindow::SetOSWindowHandle (void *) virtual
SetWindowDimensions_EventThread()
APPLICATIONCORE_API void FAndroidWindow::SetWindowDimensions_EventThread (ANativeWindow * DimensionWindow) static
SetWindowMode()
virtual void FAndroidWindow::SetWindowMode (EWindowMode::Type InNewWindowMode) inline virtual
Toggle native window between fullscreen and normal mode.
Reimplemented from FGenericWindow.
Definition at line 77 of file AndroidWindow.h.
References WindowMode.
WaitForHardwareWindow()
APPLICATIONCORE_API void * FAndroidWindow::WaitForHardwareWindow () static
Waits on the current thread for a hardware window and returns it.
May return nullptr if the application is shutting down.
WaitForWindowDimensions()
APPLICATIONCORE_API bool FAndroidWindow::WaitForWindowDimensions () static private
Friends And Related Symbol Documentation
FAndroidWindowManager
friend class FAndroidWindowManager friend
Definition at line 167 of file AndroidWindow.h.
References FAndroidWindowManager.
Referenced by FAndroidWindowManager.
Field Documentation
ANativeHandleMutex
UE::FSharedMutex FAndroidWindow::ANativeHandleMutex private
Definition at line 148 of file AndroidWindow.h.
bAreCachedNativeDimensionsValid
APPLICATIONCORE_API bool FAndroidWindow::bAreCachedNativeDimensionsValid static private
Definition at line 163 of file AndroidWindow.h.
CachedNativeWindowHeight
APPLICATIONCORE_API int32 FAndroidWindow::CachedNativeWindowHeight static private
Definition at line 165 of file AndroidWindow.h.
CachedNativeWindowWidth
APPLICATIONCORE_API int32 FAndroidWindow::CachedNativeWindowWidth static private
Definition at line 164 of file AndroidWindow.h.
CurrentANativeHandle
ANativeWindow* FAndroidWindow::CurrentANativeHandle = nullptr private
Definition at line 146 of file AndroidWindow.h.
NativeWindow
APPLICATIONCORE_API void* FAndroidWindow::NativeWindow static private
Definition at line 158 of file AndroidWindow.h.
OwningApplication
FAndroidApplication* FAndroidWindow::OwningApplication private
Definition at line 156 of file AndroidWindow.h.
PreviousANativeHandle
ANativeWindow* FAndroidWindow::PreviousANativeHandle = nullptr private
Definition at line 147 of file AndroidWindow.h.
WindowMode
EWindowMode::Type FAndroidWindow::WindowMode = EWindowMode::Fullscreen private
Definition at line 149 of file AndroidWindow.h.
Referenced by GetWindowMode(), and SetWindowMode().
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/Android/AndroidWindow.h