Unreal Engine 5.6 C++ API: FMovieSceneInstancePreAnimatedState Class Reference
FMovieSceneInstancePreAnimatedState Class Reference
Class that caches pre-animated state for objects that were manipulated by sequencer.
#include "MovieScenePreAnimatedState.h"
Public Member Functions
FMovieSceneInstancePreAnimatedState (const FMovieSceneInstancePreAnimatedState &)=delete
FMovieSceneInstancePreAnimatedState (UMovieSceneEntitySystemLinker *InLinker, UE::MovieScene::FRootInstanceHandle InInstanceHandle)
MOVIESCENE_API ~FMovieSceneInstancePreAnimatedState ()
MOVIESCENE_API bool ContainsAnyStateForSequence () const
Search the global pre-animated state extension for any captured state that originated from this sequence WARNING: This is a linear search across all state, and so is potentially very slow.
MOVIESCENE_API void DiscardAndRemoveEntityTokensForObject (UObject &Object)
Discard any tokens that relate to the requested object (ie sections or tracks) without restoring the values.
MOVIESCENE_API void DiscardEntityTokens ()
Discard any tokens that relate to entity animation (ie sections or tracks) without restoring the values.
MOVIESCENE_API void DiscardPreAnimatedState ()
MOVIESCENE_API void EnableGlobalPreAnimatedStateCapture ()
Check whether this sequence instance is capturing any and all changes of state so they can be restored later.
MOVIESCENE_API UMovieSceneEntitySystemLinker * GetLinker () const
Retrieve the linker this container is bound to.
MOVIESCENE_API bool IsCapturingGlobalPreAnimatedState () const
Check whether this sequence instance is capturing any and all changes of state so they can be restored later.
FMovieSceneInstancePreAnimatedState & operator= (const FMovieSceneInstancePreAnimatedState &)=delete
MOVIESCENE_API void RestorePreAnimatedState ()
MOVIESCENE_API void RestorePreAnimatedState (UClass *GeneratedClass)
MOVIESCENE_API void RestorePreAnimatedState (UObject &Object)
MOVIESCENE_API void RestorePreAnimatedState (UObject &Object, TFunctionRef< bool(FMovieSceneAnimTypeID)> InFilter)
MOVIESCENE_API void SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer &Producer)
Save the current state of the environment as defined by the specified token producer, identified by a specific anim type ID This will use the currently evaluating track template, evaluation hook or track instance (and its 'When Finished' property) as the capture source.
MOVIESCENE_API void SavePreAnimatedState (UObject &InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer &Producer)
Save the current state of an object as defined by the specified token producer, identified by a specific anim type ID This will use the currently evaluating track template, evaluation hook or track instance (and its 'When Finished' property) as the capture source.
Private Member Functions
void ConditionalInitializeEntityStorage (bool bOverrideWantsRestoreState)
Private Attributes
bool bCapturingGlobalPreAnimatedState
Whether global pre-animated state capture has been requested on the linker extension.
UE::MovieScene::FRootInstanceHandle InstanceHandle
The instance handle for the root sequence instance.
TWeakObjectPtr< UMovieSceneEntitySystemLinker > WeakLinker
Weak pointer to the linker that we're associated with.
Detailed Description
Class that caches pre-animated state for objects that were manipulated by sequencer.
Definition at line 25 of file MovieScenePreAnimatedState.h.
Constructor & Destructor Documentation
FMovieSceneInstancePreAnimatedState() [1/2]
FMovieSceneInstancePreAnimatedState::FMovieSceneInstancePreAnimatedState (UMovieSceneEntitySystemLinker * InLinker, UE::MovieScene::FRootInstanceHandle InInstanceHandle)
Referenced by FMovieSceneInstancePreAnimatedState(), and operator=().
FMovieSceneInstancePreAnimatedState() [2/2]
FMovieSceneInstancePreAnimatedState::FMovieSceneInstancePreAnimatedState (const FMovieSceneInstancePreAnimatedState &) delete
References FMovieSceneInstancePreAnimatedState().
~FMovieSceneInstancePreAnimatedState()
MOVIESCENE_API FMovieSceneInstancePreAnimatedState::~FMovieSceneInstancePreAnimatedState ()
Member Function Documentation
ConditionalInitializeEntityStorage()
void FMovieSceneInstancePreAnimatedState::ConditionalInitializeEntityStorage (bool bOverrideWantsRestoreState) private
ContainsAnyStateForSequence()
MOVIESCENE_API bool FMovieSceneInstancePreAnimatedState::ContainsAnyStateForSequence () const
Search the global pre-animated state extension for any captured state that originated from this sequence WARNING: This is a linear search across all state, and so is potentially very slow.
DiscardAndRemoveEntityTokensForObject()
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::DiscardAndRemoveEntityTokensForObject (UObject & Object)
Discard any tokens that relate to the requested object (ie sections or tracks) without restoring the values.
Any global pre-animated state tokens for this object will be removed.
References Object.
DiscardEntityTokens()
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::DiscardEntityTokens ()
Discard any tokens that relate to entity animation (ie sections or tracks) without restoring the values.
Any global pre-animated state tokens (that reset the animation when saving a map, for instance) will remain.
DiscardPreAnimatedState()
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::DiscardPreAnimatedState ()
EnableGlobalPreAnimatedStateCapture()
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::EnableGlobalPreAnimatedStateCapture ()
Check whether this sequence instance is capturing any and all changes of state so they can be restored later.
GetLinker()
MOVIESCENE_API UMovieSceneEntitySystemLinker * FMovieSceneInstancePreAnimatedState::GetLinker () const
Retrieve the linker this container is bound to.
IsCapturingGlobalPreAnimatedState()
MOVIESCENE_API bool FMovieSceneInstancePreAnimatedState::IsCapturingGlobalPreAnimatedState () const
Check whether this sequence instance is capturing any and all changes of state so they can be restored later.
operator=()
FMovieSceneInstancePreAnimatedState & FMovieSceneInstancePreAnimatedState::operator= (const FMovieSceneInstancePreAnimatedState &) delete
References FMovieSceneInstancePreAnimatedState().
RestorePreAnimatedState() [1/4]
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::RestorePreAnimatedState ()
RestorePreAnimatedState() [2/4]
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::RestorePreAnimatedState (UClass * GeneratedClass)
RestorePreAnimatedState() [3/4]
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::RestorePreAnimatedState (UObject & Object)
References Object.
RestorePreAnimatedState() [4/4]
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::RestorePreAnimatedState (UObject & Object, TFunctionRef< bool(FMovieSceneAnimTypeID)> InFilter)
References Object.
SavePreAnimatedState() [1/2]
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer & Producer)
Save the current state of the environment as defined by the specified token producer, identified by a specific anim type ID This will use the currently evaluating track template, evaluation hook or track instance (and its 'When Finished' property) as the capture source.
SavePreAnimatedState() [2/2]
MOVIESCENE_API void FMovieSceneInstancePreAnimatedState::SavePreAnimatedState (UObject & InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer & Producer)
Save the current state of an object as defined by the specified token producer, identified by a specific anim type ID This will use the currently evaluating track template, evaluation hook or track instance (and its 'When Finished' property) as the capture source.
Field Documentation
bCapturingGlobalPreAnimatedState
bool FMovieSceneInstancePreAnimatedState::bCapturingGlobalPreAnimatedState private
Whether global pre-animated state capture has been requested on the linker extension.
Definition at line 111 of file MovieScenePreAnimatedState.h.
InstanceHandle
UE::MovieScene::FRootInstanceHandle FMovieSceneInstancePreAnimatedState::InstanceHandle private
The instance handle for the root sequence instance.
Definition at line 108 of file MovieScenePreAnimatedState.h.
WeakLinker
TWeakObjectPtr<UMovieSceneEntitySystemLinker> FMovieSceneInstancePreAnimatedState::WeakLinker private
Weak pointer to the linker that we're associated with.
Definition at line 105 of file MovieScenePreAnimatedState.h.
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieScenePreAnimatedState.h