Unreal Engine 5.6 C++ API: FMovieScenePreAnimatedState Class Reference
FMovieScenePreAnimatedState Class Reference
A class similar to FMovieSceneInstancePreAnimatedState (above), which doesn't manage global pre-animated state requests, deferring those to the other class.
#include "MovieScenePreAnimatedState.h"
Public Member Functions
FMovieScenePreAnimatedState ()=default
FMovieScenePreAnimatedState (const FMovieScenePreAnimatedState &)=delete
MOVIESCENE_API bool ContainsAnyStateForSequence () const
MOVIESCENE_API void DiscardAndRemoveEntityTokensForObject (UObject &Object)
MOVIESCENE_API void DiscardEntityTokens ()
MOVIESCENE_API void DiscardPreAnimatedState ()
MOVIESCENE_API void EnableGlobalPreAnimatedStateCapture ()
MOVIESCENE_API UMovieSceneEntitySystemLinker * GetLinker () const
MOVIESCENE_API void Initialize (UMovieSceneEntitySystemLinker *Linker, UE::MovieScene::FRootInstanceHandle InstanceHandle)
MOVIESCENE_API bool IsCapturingGlobalPreAnimatedState () const
FMovieScenePreAnimatedState & operator= (const FMovieScenePreAnimatedState &)=delete
MOVIESCENE_API void RestorePreAnimatedState ()
MOVIESCENE_API void RestorePreAnimatedState (UClass *GeneratedClass)
MOVIESCENE_API void RestorePreAnimatedState (UObject &Object)
MOVIESCENE_API void RestorePreAnimatedState (UObject &Object, TFunctionRef< bool(FMovieSceneAnimTypeID)> InFilter)
MOVIESCENE_API void SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer &Producer)
MOVIESCENE_API void SavePreAnimatedState (UObject &InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer &Producer)
Private Member Functions
FMovieSceneInstancePreAnimatedState * GetState () const
Private Attributes
UE::MovieScene::FRootInstanceHandle InstanceHandle
TWeakObjectPtr< UMovieSceneEntitySystemLinker > WeakLinker
Friends
struct FScopedPreAnimatedCaptureSource
Detailed Description
A class similar to FMovieSceneInstancePreAnimatedState (above), which doesn't manage global pre-animated state requests, deferring those to the other class.
This class is mostly for IMovieScenePlayer, for backwards compatibility.
Definition at line 119 of file MovieScenePreAnimatedState.h.
Constructor & Destructor Documentation
FMovieScenePreAnimatedState() [1/2]
FMovieScenePreAnimatedState::FMovieScenePreAnimatedState () default
Referenced by FMovieScenePreAnimatedState(), and operator=().
FMovieScenePreAnimatedState() [2/2]
FMovieScenePreAnimatedState::FMovieScenePreAnimatedState (const FMovieScenePreAnimatedState &) delete
References FMovieScenePreAnimatedState().
Member Function Documentation
ContainsAnyStateForSequence()
MOVIESCENE_API bool FMovieScenePreAnimatedState::ContainsAnyStateForSequence () const
DiscardAndRemoveEntityTokensForObject()
MOVIESCENE_API void FMovieScenePreAnimatedState::DiscardAndRemoveEntityTokensForObject (UObject & Object)
References Object.
DiscardEntityTokens()
MOVIESCENE_API void FMovieScenePreAnimatedState::DiscardEntityTokens ()
DiscardPreAnimatedState()
MOVIESCENE_API void FMovieScenePreAnimatedState::DiscardPreAnimatedState ()
EnableGlobalPreAnimatedStateCapture()
MOVIESCENE_API void FMovieScenePreAnimatedState::EnableGlobalPreAnimatedStateCapture ()
GetLinker()
MOVIESCENE_API UMovieSceneEntitySystemLinker * FMovieScenePreAnimatedState::GetLinker () const
GetState()
FMovieSceneInstancePreAnimatedState * FMovieScenePreAnimatedState::GetState () const private
Initialize()
MOVIESCENE_API void FMovieScenePreAnimatedState::Initialize (UMovieSceneEntitySystemLinker * Linker, UE::MovieScene::FRootInstanceHandle InstanceHandle)
References InstanceHandle.
IsCapturingGlobalPreAnimatedState()
MOVIESCENE_API bool FMovieScenePreAnimatedState::IsCapturingGlobalPreAnimatedState () const
operator=()
FMovieScenePreAnimatedState & FMovieScenePreAnimatedState::operator= (const FMovieScenePreAnimatedState &) delete
References FMovieScenePreAnimatedState().
RestorePreAnimatedState() [1/4]
MOVIESCENE_API void FMovieScenePreAnimatedState::RestorePreAnimatedState ()
RestorePreAnimatedState() [2/4]
MOVIESCENE_API void FMovieScenePreAnimatedState::RestorePreAnimatedState (UClass * GeneratedClass)
RestorePreAnimatedState() [3/4]
MOVIESCENE_API void FMovieScenePreAnimatedState::RestorePreAnimatedState (UObject & Object)
References Object.
RestorePreAnimatedState() [4/4]
MOVIESCENE_API void FMovieScenePreAnimatedState::RestorePreAnimatedState (UObject & Object, TFunctionRef< bool(FMovieSceneAnimTypeID)> InFilter)
References Object.
SavePreAnimatedState() [1/2]
MOVIESCENE_API void FMovieScenePreAnimatedState::SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer & Producer)
SavePreAnimatedState() [2/2]
MOVIESCENE_API void FMovieScenePreAnimatedState::SavePreAnimatedState (UObject & InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer & Producer)
Friends And Related Symbol Documentation
FScopedPreAnimatedCaptureSource
friend struct FScopedPreAnimatedCaptureSource friend
Definition at line 149 of file MovieScenePreAnimatedState.h.
References FScopedPreAnimatedCaptureSource.
Referenced by FScopedPreAnimatedCaptureSource.
Field Documentation
InstanceHandle
UE::MovieScene::FRootInstanceHandle FMovieScenePreAnimatedState::InstanceHandle private
Definition at line 147 of file MovieScenePreAnimatedState.h.
Referenced by Initialize().
WeakLinker
TWeakObjectPtr<UMovieSceneEntitySystemLinker> FMovieScenePreAnimatedState::WeakLinker private
Definition at line 146 of file MovieScenePreAnimatedState.h.
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieScenePreAnimatedState.h