Unreal Engine 5.6 C++ API: IDisplayCluster Class Reference
IDisplayCluster Class Reference abstract
Public module interface.
#include "IDisplayCluster.h"
Public Member Functions
virtual ~IDisplayCluster ()=default
virtual IDisplayClusterCallbacks & GetCallbacks ()=0
Access to the DisplayCluster callbacks API.
virtual IDisplayClusterClusterManager * GetClusterMgr () const =0
Access to the cluster manager.
virtual IDisplayClusterConfigManager * GetConfigMgr () const =0
Access to the config manager.
virtual IDisplayClusterGameManager * GetGameMgr () const =0
Access to the game manager.
virtual EDisplayClusterOperationMode GetOperationMode () const =0
Returns current operation mode.
virtual IDisplayClusterRenderManager * GetRenderMgr () const =0
Access to the device manager.
UE_DEPRECATED (5.4, "This function has been deprecated and will be removed soon.") virtual bool IsModuleInitialized() const
[DEPRECATED] Checks if the module has been initialized.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayCluster & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayCluster")
Detailed Description
Public module interface.
Definition at line 21 of file IDisplayCluster.h.
Constructor & Destructor Documentation
~IDisplayCluster()
virtual IDisplayCluster::~IDisplayCluster () virtual default
Member Function Documentation
Get()
IDisplayCluster & IDisplayCluster::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 37 of file IDisplayCluster.h.
References FModuleManager::GetModuleChecked(), and ModuleName.
Referenced by DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs().
GetCallbacks()
virtual IDisplayClusterCallbacks & IDisplayCluster::GetCallbacks () pure virtual
Access to the DisplayCluster callbacks API.
Returns
Callbacks API
GetClusterMgr()
virtual IDisplayClusterClusterManager * IDisplayCluster::GetClusterMgr () const pure virtual
Access to the cluster manager.
Returns
Current cluster manager or nullptr
GetConfigMgr()
virtual IDisplayClusterConfigManager * IDisplayCluster::GetConfigMgr () const pure virtual
Access to the config manager.
Returns
Current config manager or nullptr
Referenced by DisplayClusterHelpers::filesystem::GetOrderedConfigResourceDirs().
GetGameMgr()
virtual IDisplayClusterGameManager * IDisplayCluster::GetGameMgr () const pure virtual
Access to the game manager.
Returns
Current game manager or nullptr
GetOperationMode()
virtual EDisplayClusterOperationMode IDisplayCluster::GetOperationMode () const pure virtual
Returns current operation mode.
Returns
Display Cluster operation mode
GetRenderMgr()
virtual IDisplayClusterRenderManager * IDisplayCluster::GetRenderMgr () const pure virtual
Access to the device manager.
Returns
Current device manager or nullptr
IsAvailable()
bool IDisplayCluster::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 48 of file IDisplayCluster.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
UE_DEPRECATED()
IDisplayCluster::UE_DEPRECATED (5. 4, "This function has been deprecated and will be removed soon.") const inline
[DEPRECATED] Checks if the module has been initialized.
Returns
Is initialized
Definition at line 59 of file IDisplayCluster.h.
Field Documentation
ModuleName
const TCHAR* IDisplayCluster::ModuleName = TEXT("DisplayCluster") static constexpr
Definition at line 25 of file IDisplayCluster.h.
Referenced by Get(), and IsAvailable().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/IDisplayCluster.h