Unreal Engine 5.6 C++ API: FGPUDriverHelper Class Reference
FGPUDriverHelper Class Reference
#include "GenericPlatformDriver.h"
Public Member Functions
FGPUDriverHelper (const FGPUDriverInfo &InDriverInfo)
TOptional< FDriverDenyListEntry > FindDriverDenyListEntry () const
TOptional< FSuggestedDriverEntry > FindSuggestedDriverVersion () const
Private Member Functions
template<typename TEntryType>
TOptional< TEntryType > GetBestConfigEntry (const TCHAR *ConfigEntryName) const
FString GetVendorSectionName () const
Private Attributes
FGPUDriverInfo DriverInfo
Detailed Description
Definition at line 479 of file GenericPlatformDriver.h.
Constructor & Destructor Documentation
FGPUDriverHelper()
FGPUDriverHelper::FGPUDriverHelper (const FGPUDriverInfo & InDriverInfo) inline
Definition at line 482 of file GenericPlatformDriver.h.
References DriverInfo.
Member Function Documentation
FindDriverDenyListEntry()
TOptional< FDriverDenyListEntry > FGPUDriverHelper::FindDriverDenyListEntry () const inline
Definition at line 494 of file GenericPlatformDriver.h.
References GetBestConfigEntry(), and TEXT.
FindSuggestedDriverVersion()
TOptional< FSuggestedDriverEntry > FGPUDriverHelper::FindSuggestedDriverVersion () const inline
Definition at line 488 of file GenericPlatformDriver.h.
References GetBestConfigEntry(), and TEXT.
GetBestConfigEntry()
template<typename TEntryType> TOptional< TEntryType > FGPUDriverHelper::GetBestConfigEntry (const TCHAR * ConfigEntryName) const inline private
Definition at line 501 of file GenericPlatformDriver.h.
References DriverInfo, ensure, GConfig, GetVendorSectionName(), and GHardwareIni.
Referenced by FindDriverDenyListEntry(), and FindSuggestedDriverVersion().
GetVendorSectionName()
FString FGPUDriverHelper::GetVendorSectionName () const inline private
Definition at line 541 of file GenericPlatformDriver.h.
References ANSI_TO_TCHAR, DriverInfo, and TEXT.
Referenced by GetBestConfigEntry().
Field Documentation
DriverInfo
FGPUDriverInfo FGPUDriverHelper::DriverInfo private
Definition at line 565 of file GenericPlatformDriver.h.
Referenced by FGPUDriverHelper(), GetBestConfigEntry(), and GetVendorSectionName().
The documentation for this class was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformDriver.h