Unreal Engine 5.6 C++ API: FStaticMeshStaticLightingTextureMapping Class Reference
FStaticMeshStaticLightingTextureMapping Class Reference
Represents a static mesh primitive with texture mapped static lighting.
#include "StaticMeshLight.h"
Public Member Functions
FStaticMeshStaticLightingTextureMapping (const FArchive &Ar)
FStaticMeshStaticLightingTextureMapping (UStaticMeshComponent *InPrimitive, int32 InLODIndex, FStaticLightingMesh *InMesh, int32 InSizeX, int32 InSizeY, int32 InTextureCoordinateIndex, bool bPerformFullQualityRebuild)
Initialization constructor.
virtual void Apply (FQuantizedLightmapData *QuantizedData, const TMap< ULightComponent *, FShadowMapData2D * > &ShadowMapData, const FStaticLightingBuildContext *LightingContext) override
Called when the static lighting has been computed to apply it to the mapping's owner.
virtual UNREALED_API void ExportMapping (class FLightmassExporter *Exporter) override
Export static lighting mapping instance data to an exporter.
virtual FString GetDescription () const override
int32 GetLODIndex ()
virtual bool IsValidMapping () const override
Whether or not this mapping should be processed or imported.
virtual void Serialize (FArchive &Ar)
Public Member Functions inherited from FStaticLightingTextureMapping
FStaticLightingTextureMapping (const FArchive &Ar)
Default constructor used by serializer.
FStaticLightingTextureMapping (FStaticLightingMesh *InMesh, UObject *InOwner, int32 InSizeX, int32 InSizeY, int32 InLightmapTextureCoordinateIndex, bool bInBilinearFilter=true)
Initialization constructor.
virtual UNREALED_API bool DebugThisMapping () const
virtual int32 GetTexelCount () const
virtual FStaticLightingTextureMapping * GetTextureMapping ()
virtual bool IsTextureMapping () const
Public Member Functions inherited from FStaticLightingMapping
FStaticLightingMapping (const FArchive &)
FStaticLightingMapping (FStaticLightingMesh *InMesh, UObject *InOwner)
Initialization constructor.
virtual ~FStaticLightingMapping ()
Virtual destructor.
virtual const FGuid & GetLightingGuid () const
Returns the Guid used for static lighting.
virtual UObject * GetMappedObject () const
bool IsDeferred () const
Public Member Functions inherited from FRefCountedObject
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Protected Attributes
int32 LODIndex
The LOD this mapping represents.
TWeakObjectPtr< UStaticMeshComponent > Primitive
The primitive this mapping represents.
Additional Inherited Members
Data Fields inherited from FStaticLightingTextureMapping
bool bBilinearFilter
Whether to apply a bilinear filter to the sample or not.
int32 LightmapTextureCoordinateIndex
The lightmap texture coordinate index which is used for the mapping.
int32 SizeX
The width of the static lighting textures used by the mapping.
int32 SizeY
The height of the static lighting textures used by the mapping.
Data Fields inherited from FStaticLightingMapping
uint32 bIsDeferred: 1
true if the mapping should be deferred until a finalizing pass.
uint32 bProcessMapping: 1
true if the mapping should be processed by Lightmass.
class FStaticLightingMesh * Mesh
The mesh associated with the mapping.
UObject * Owner
The object which owns the mapping.
Detailed Description
Represents a static mesh primitive with texture mapped static lighting.
Definition at line 108 of file StaticMeshLight.h.
Constructor & Destructor Documentation
FStaticMeshStaticLightingTextureMapping() [1/2]
FStaticMeshStaticLightingTextureMapping::FStaticMeshStaticLightingTextureMapping (UStaticMeshComponent * InPrimitive, int32 InLODIndex, FStaticLightingMesh * InMesh, int32 InSizeX, int32 InSizeY, int32 InTextureCoordinateIndex, bool bPerformFullQualityRebuild)
Initialization constructor.
Referenced by FStaticLightingTextureMapping_InstancedStaticMesh::FStaticLightingTextureMapping_InstancedStaticMesh(), and FStaticLightingTextureMapping_InstancedStaticMesh::FStaticLightingTextureMapping_InstancedStaticMesh().
FStaticMeshStaticLightingTextureMapping() [2/2]
FStaticMeshStaticLightingTextureMapping::FStaticMeshStaticLightingTextureMapping (const FArchive & Ar) inline
Definition at line 118 of file StaticMeshLight.h.
References FStaticLightingTextureMapping::FStaticLightingTextureMapping(), and Ar.
Member Function Documentation
Apply()
virtual void FStaticMeshStaticLightingTextureMapping::Apply (FQuantizedLightmapData * QuantizedData, const TMap< ULightComponent *, FShadowMapData2D * > & ShadowMapData, const FStaticLightingBuildContext * LightingContext) override virtual
Called when the static lighting has been computed to apply it to the mapping's owner.
This function is responsible for deleting ShadowMapData and QuantizedData.
Parameters
LightMapData - The light-map data which has been computed for the mapping.
Implements FStaticLightingTextureMapping.
Reimplemented in FStaticLightingTextureMapping_InstancedStaticMesh.
ExportMapping()
virtual UNREALED_API void FStaticMeshStaticLightingTextureMapping::ExportMapping (class FLightmassExporter * Exporter) override virtual
Export static lighting mapping instance data to an exporter.
Parameters
Exporter - export interface to process static lighting data
Reimplemented from FStaticLightingMapping.
GetDescription()
virtual FString FStaticMeshStaticLightingTextureMapping::GetDescription () const inline override virtual
Reimplemented from FStaticLightingTextureMapping.
Reimplemented in FStaticLightingTextureMapping_InstancedStaticMesh.
Definition at line 132 of file StaticMeshLight.h.
References TEXT.
GetLODIndex()
int32 FStaticMeshStaticLightingTextureMapping::GetLODIndex () inline
Definition at line 140 of file StaticMeshLight.h.
References LODIndex.
IsValidMapping()
virtual bool FStaticMeshStaticLightingTextureMapping::IsValidMapping () const inline override virtual
Whether or not this mapping should be processed or imported.
Reimplemented from FStaticLightingTextureMapping.
Definition at line 138 of file StaticMeshLight.h.
References Primitive.
Serialize()
virtual void FStaticMeshStaticLightingTextureMapping::Serialize (FArchive & Ar) virtual
Reimplemented from FStaticLightingTextureMapping.
Reimplemented in FStaticLightingTextureMapping_InstancedStaticMesh.
References Ar.
Field Documentation
LODIndex
int32 FStaticMeshStaticLightingTextureMapping::LODIndex protected
The LOD this mapping represents.
Definition at line 148 of file StaticMeshLight.h.
Referenced by FStaticLightingTextureMapping_InstancedStaticMesh::FStaticLightingTextureMapping_InstancedStaticMesh(), and GetLODIndex().
Primitive
TWeakObjectPtr<UStaticMeshComponent> FStaticMeshStaticLightingTextureMapping::Primitive protected
The primitive this mapping represents.
Definition at line 145 of file StaticMeshLight.h.
Referenced by FStaticLightingTextureMapping_InstancedStaticMesh::Apply(), and IsValidMapping().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/StaticMeshLight.h