Unreal Engine 5.6 C++ API: FWorldPartitionActorDesc Class Reference
FWorldPartitionActorDesc Class Reference
Represents a Actor Metadata (editor-only)
#include "WorldPartitionActorDesc.h"
Data Structures
struct FContainerInstance
Public Types
enum class EToStringMode : uint8 {
Guid , Compact , Full , Verbose ,
ForDiff
}
using FActorDescDeprecator = TFunction<void(FArchive&, FWorldPartitionActorDesc*)>
Public Member Functions
virtual ~FWorldPartitionActorDesc ()
void AddProperty (FName PropertyName, FName PropertyValue=NAME_None)
virtual void CheckForErrors (const IWorldPartitionActorDescInstanceView *InActorDescView, IStreamingGenerationErrorHandler *ErrorHandler) const
virtual bool Equals (const FWorldPartitionActorDesc *Other) const
bool GetActorIsEditorOnly () const
bool GetActorIsEditorOnlyLoadedInPIE () const
bool GetActorIsHLODRelevant () const
bool GetActorIsRuntimeOnly () const
FName GetActorLabel () const
FName GetActorLabelOrName () const
const FString & GetActorLabelString () const
FName GetActorName () const
const FString & GetActorNameString () const
UClass * GetActorNativeClass () const
FName GetActorPackage () const
FSoftObjectPath GetActorSoftPath () const
const FTransform & GetActorTransform () const
FTopLevelAssetPath GetBaseClass () const
virtual UActorDescContainer * GetChildContainer () const
virtual const FWorldPartitionActorFilter * GetChildContainerFilter () const
virtual EWorldPartitionActorFilterType GetChildContainerFilterType () const
virtual FString GetChildContainerName () const
virtual FName GetChildContainerPackage () const
FGuid GetContentBundleGuid () const
TArray< FName > GetDataLayers (bool bIncludeExternalDataLayer=true) const
FName GetDisplayClassName () const
const FString & GetDisplayClassNameString () const
FBox GetEditorBounds () const
FName GetExternalDataLayer () const
const FSoftObjectPath & GetExternalDataLayerAsset () const
const FGuid & GetFolderGuid () const
FName GetFolderPath () const
const FGuid & GetGuid () const
FSoftObjectPath GetHLODLayer () const
bool GetIsSpatiallyLoaded () const
bool GetIsSpatiallyLoadedRaw () const
FTopLevelAssetPath GetNativeClass () const
const FGuid & GetParentActor () const
bool GetProperty (FName PropertyName, FName *PropertyValue) const
FBox GetRuntimeBounds () const
FName GetRuntimeGrid () const
virtual const FGuid & GetSceneOutlinerParent () const
const TArray< FName > & GetTags () const
bool HasProperty (FName PropertyName) const
virtual bool HasStandaloneHLOD () const
virtual void Init (const AActor *InActor)
virtual void Init (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsChildContainerInstance () const
bool IsDefaultActorDesc () const
bool IsListedInSceneOutliner () const
bool IsMainWorldOnly () const
virtual bool IsResaveNeeded () const
bool IsUsingDataLayerAsset () const
bool operator== (const FWorldPartitionActorDesc &Other) const
void SerializeTo (TArray< uint8 > &OutData, FWorldPartitionActorDesc *BaseDesc=nullptr) const
virtual bool ShouldResave (const FWorldPartitionActorDesc *Other) const
Returns true if resaving this actor will have an impact on streaming generation.
FString ToString (EToStringMode Mode=EToStringMode::Compact) const
UE_DEPRECATED (5.1, "SetIsSpatiallyLoadedRaw is deprecated and should not be used.") inline void SetIsSpatiallyLoadedRaw(bool bNewIsSpatiallyLoaded)
UE_DEPRECATED (5.2, "GetBounds is deprecated, GetEditorBounds or GetRuntimeBounds should be used instead.") FBox GetBounds() const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "GetOrigin is deprecated.") inline FVector GetOrigin() const
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "ShouldValidateRuntimeGrid is deprecated and should not be used") virtual bool ShouldValidateRuntimeGrid() const
UE_DEPRECATED (5.3, "GetLevelPackage is deprecated use GetChildContainerPackage instead") virtual FName GetLevelPackage() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::GetUnloadedReason") FText GetUnloadedReason() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::SetUnloadedReason") void SetUnloadedReason(FText *InUnloadedReason)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::GetDataLayerInstanceNames") TArray< FName > GetDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::HasResolvedDataLayerInstanceNames") inline bool HasResolvedDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsEditorRelevant instead") virtual bool IsEditorRelevant() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsRuntimeRelevant instead") virtual bool IsRuntimeRelevant(const FActorContainerID &InContainerID) const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::SetDataLayerInstanceNames") inline void SetDataLayerInstanceNames(const TArray< FName > &InDataLayerInstanceNames)
UE_DEPRECATED (5.4, "Use GetChildContainerFilter instead") virtual const FWorldPartitionActorFilter *GetContainerFilter() const
UE_DEPRECATED (5.4, "Use GetChildContainerFilterType instead") virtual EWorldPartitionActorFilterType GetContainerFilterType() const
UE_DEPRECATED (5.4, "Use GetChildContainerInstance instead") virtual bool GetContainerInstance(FContainerInstance &OutContainerInstance) const
UE_DEPRECATED (5.4, "Use GetChildContainerPackage instead") virtual FName GetContainerPackage() const
UE_DEPRECATED (5.4, "Use IsChildContainerInstance instead") virtual bool IsContainerInstance() const
UE_DEPRECATED (5.4, "Use SetContainer without World param") virtual void SetContainer(UActorDescContainer *InContainer
Static Public Member Functions
static void Patch (const FWorldPartitionActorDescInitData &DescData, TArray< uint8 > &OutData, FWorldPartitionAssetDataPatcher *InAssetDataPatcher)
static void RegisterActorDescDeprecator (TSubclassOf< AActor > ActorClass, const FActorDescDeprecator &Deprecator)
Data Fields
UWorld * InWorldContext
Protected Member Functions
FWorldPartitionActorDesc ()
virtual UActorDescContainerInstance * CreateChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual bool GetChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance, FContainerInstance &OutContainerInstance) const
virtual UWorldPartition * GetLoadedChildWorldPartition (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual uint32 GetSizeOf () const
void InitTransientProperties (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsEditorRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual bool IsRuntimeRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual void Serialize (FArchive &Ar)
void SetEditorBounds (const FBox &InEditorBounds)
void SetRuntimeBounds (const FBox &InRuntimeBounds)
virtual void TransferFrom (const FWorldPartitionActorDesc *From)
virtual void TransferWorldData (const FWorldPartitionActorDesc *From)
Protected Attributes
FString ActorDisplayClassNameString
FName ActorLabel
FString ActorLabelString
FName ActorName
FString ActorNameString
UClass * ActorNativeClass
FName ActorPackage
FSoftObjectPath ActorPath
FTransform ActorTransform
FTransform ActorTransformRelative
bool bActorIsEditorOnly
bool bActorIsHLODRelevant
bool bActorIsListedInSceneOutliner
bool bActorIsMainWorldOnly
bool bActorIsRuntimeOnly
FTopLevelAssetPath BaseClass
bool bHasValidRelativeBounds
bool bIsDefaultActorDesc
bool bIsSpatiallyLoaded
bool bIsUsingDataLayerAsset
UActorDescContainer * Container
FGuid ContentBundleGuid
TArray< FName > DataLayers
FBox EditorBounds
FWorldPartitionRelativeBounds EditorBoundsRelative
TArray< FGuid > EditorOnlyReferences
FSoftObjectPath ExternalDataLayerAsset
FGuid FolderGuid
FName FolderPath
FGuid Guid
FSoftObjectPath HLODLayer
FTopLevelAssetPath NativeClass
FGuid ParentActor
FPropertyPairsMap Properties
TArray< FGuid > References
FBox RuntimeBounds
FWorldPartitionRelativeBounds RuntimeBoundsRelative
FName RuntimeGrid
TArray< FName > Tags
Static Protected Attributes
static TMap< TSubclassOf< AActor >, FActorDescDeprecator > Deprecators
Private Member Functions
void FixupStreamingBounds ()
Friends
class AActor
class FActorDescArchive
class FAssetHeaderPatcherInner
class FPropertyOverrideUtils
class FStreamingGenerationTempActorDescInstance
class FWorldPartitionActorDescInstance
struct FWorldPartitionActorDescUnitTestAcccessor
struct FWorldPartitionActorDescUtils
struct FWorldPartitionHandleImpl
struct FWorldPartitionReferenceImpl
uint32 GetTypeHash (const FWorldPartitionActorDesc &Key)
template<class U>
class TActorDescContainerCollection
class UWorldPartition
Detailed Description
Represents a Actor Metadata (editor-only)
Definition at line 236 of file WorldPartitionActorDesc.h.
Member Typedef Documentation
FActorDescDeprecator
using FWorldPartitionActorDesc::FActorDescDeprecator = TFunction<void(FArchive&, FWorldPartitionActorDesc*)>
Definition at line 499 of file WorldPartitionActorDesc.h.
Member Enumeration Documentation
EToStringMode
enum class FWorldPartitionActorDesc::EToStringMode : uint8 strong
Enumerator
Guid
Compact
Full
Verbose
ForDiff
Definition at line 471 of file WorldPartitionActorDesc.h.
Constructor & Destructor Documentation
~FWorldPartitionActorDesc()
virtual FWorldPartitionActorDesc::~FWorldPartitionActorDesc () inline virtual
Definition at line 270 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDesc().
FWorldPartitionActorDesc()
FWorldPartitionActorDesc::FWorldPartitionActorDesc () protected
Referenced by ~FWorldPartitionActorDesc(), FHLODActorDesc::Equals(), FLandscapeActorDesc::Equals(), FLevelInstanceActorDesc::Equals(), FMapBuildDataActorDesc::Equals(), FPackedLevelActorDesc::Equals(), FPartitionActorDesc::Equals(), FWorldDataLayersActorDesc::Equals(), Equals(), GetSizeOf(), GetTypeHash, operator==(), SerializeTo(), ShouldResave(), FLevelInstanceActorDesc::TransferFrom(), TransferFrom(), FPartitionActorDesc::TransferWorldData(), and TransferWorldData().
Member Function Documentation
AddProperty()
void FWorldPartitionActorDesc::AddProperty (FName PropertyName, FName PropertyValue = NAME_None) inline
Definition at line 305 of file WorldPartitionActorDesc.h.
References Properties, and PropertyName.
CheckForErrors()
virtual void FWorldPartitionActorDesc::CheckForErrors (const IWorldPartitionActorDescInstanceView * InActorDescView, IStreamingGenerationErrorHandler * ErrorHandler) const virtual
Reimplemented in FLevelInstanceActorDesc.
Referenced by FWorldPartitionActorDescInstanceView::CheckForErrors().
CreateChildContainerInstance()
virtual UActorDescContainerInstance * FWorldPartitionActorDesc::CreateChildContainerInstance (const FWorldPartitionActorDescInstance * InActorDescInstance) const inline protected virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 508 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInstance.
Equals()
virtual bool FWorldPartitionActorDesc::Equals (const FWorldPartitionActorDesc * Other) const virtual
Reimplemented in FHLODActorDesc, FLandscapeActorDesc, FLevelInstanceActorDesc, FMapBuildDataActorDesc, FPackedLevelActorDesc, FPartitionActorDesc, and FWorldDataLayersActorDesc.
References FWorldPartitionActorDesc(), and Other.
FixupStreamingBounds()
void FWorldPartitionActorDesc::FixupStreamingBounds () private
GetActorIsEditorOnly()
bool FWorldPartitionActorDesc::GetActorIsEditorOnly () const inline
Definition at line 281 of file WorldPartitionActorDesc.h.
References bActorIsEditorOnly.
GetActorIsEditorOnlyLoadedInPIE()
bool FWorldPartitionActorDesc::GetActorIsEditorOnlyLoadedInPIE () const
GetActorIsHLODRelevant()
bool FWorldPartitionActorDesc::GetActorIsHLODRelevant () const inline
Definition at line 285 of file WorldPartitionActorDesc.h.
References bActorIsHLODRelevant.
GetActorIsRuntimeOnly()
bool FWorldPartitionActorDesc::GetActorIsRuntimeOnly () const inline
Definition at line 283 of file WorldPartitionActorDesc.h.
References bActorIsRuntimeOnly.
GetActorLabel()
FName FWorldPartitionActorDesc::GetActorLabel () const inline
Definition at line 295 of file WorldPartitionActorDesc.h.
References ActorLabel.
GetActorLabelOrName()
FName FWorldPartitionActorDesc::GetActorLabelOrName () const
GetActorLabelString()
const FString & FWorldPartitionActorDesc::GetActorLabelString () const
GetActorName()
FName FWorldPartitionActorDesc::GetActorName () const
GetActorNameString()
const FString & FWorldPartitionActorDesc::GetActorNameString () const
GetActorNativeClass()
UClass * FWorldPartitionActorDesc::GetActorNativeClass () const inline
Definition at line 276 of file WorldPartitionActorDesc.h.
References ActorNativeClass.
GetActorPackage()
FName FWorldPartitionActorDesc::GetActorPackage () const inline
Definition at line 293 of file WorldPartitionActorDesc.h.
References ActorPackage.
GetActorSoftPath()
FSoftObjectPath FWorldPartitionActorDesc::GetActorSoftPath () const inline
Definition at line 294 of file WorldPartitionActorDesc.h.
References ActorPath.
GetActorTransform()
const FTransform & FWorldPartitionActorDesc::GetActorTransform () const inline
Definition at line 298 of file WorldPartitionActorDesc.h.
References ActorTransform.
GetBaseClass()
FTopLevelAssetPath FWorldPartitionActorDesc::GetBaseClass () const inline
Definition at line 274 of file WorldPartitionActorDesc.h.
References BaseClass.
GetChildContainer()
virtual UActorDescContainer * FWorldPartitionActorDesc::GetChildContainer () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 325 of file WorldPartitionActorDesc.h.
GetChildContainerFilter()
virtual const FWorldPartitionActorFilter * FWorldPartitionActorDesc::GetChildContainerFilter () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 324 of file WorldPartitionActorDesc.h.
GetChildContainerFilterType()
virtual EWorldPartitionActorFilterType FWorldPartitionActorDesc::GetChildContainerFilterType () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 323 of file WorldPartitionActorDesc.h.
References None.
GetChildContainerInstance()
virtual bool FWorldPartitionActorDesc::GetChildContainerInstance (const FWorldPartitionActorDescInstance * InActorDescInstance, FContainerInstance & OutContainerInstance) const inline protected virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 507 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInstance.
GetChildContainerName()
virtual FString FWorldPartitionActorDesc::GetChildContainerName () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 322 of file WorldPartitionActorDesc.h.
GetChildContainerPackage()
virtual FName FWorldPartitionActorDesc::GetChildContainerPackage () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 321 of file WorldPartitionActorDesc.h.
Referenced by UE_DEPRECATED().
GetContentBundleGuid()
FGuid FWorldPartitionActorDesc::GetContentBundleGuid () const
GetDataLayers()
TArray< FName > FWorldPartitionActorDesc::GetDataLayers (bool bIncludeExternalDataLayer = true) const
GetDisplayClassName()
FName FWorldPartitionActorDesc::GetDisplayClassName () const
GetDisplayClassNameString()
const FString & FWorldPartitionActorDesc::GetDisplayClassNameString () const
GetEditorBounds()
FBox FWorldPartitionActorDesc::GetEditorBounds () const
Referenced by UE_DEPRECATED().
GetExternalDataLayer()
FName FWorldPartitionActorDesc::GetExternalDataLayer () const
GetExternalDataLayerAsset()
const FSoftObjectPath & FWorldPartitionActorDesc::GetExternalDataLayerAsset () const inline
Definition at line 289 of file WorldPartitionActorDesc.h.
References ExternalDataLayerAsset.
GetFolderGuid()
const FGuid & FWorldPartitionActorDesc::GetFolderGuid () const inline
Definition at line 297 of file WorldPartitionActorDesc.h.
References FolderGuid.
GetFolderPath()
FName FWorldPartitionActorDesc::GetFolderPath () const inline
Definition at line 296 of file WorldPartitionActorDesc.h.
References FolderPath.
GetGuid()
const FGuid & FWorldPartitionActorDesc::GetGuid () const inline
Definition at line 272 of file WorldPartitionActorDesc.h.
References Guid.
Referenced by TActorDescViewMap< Type >::Emplace().
GetHLODLayer()
FSoftObjectPath FWorldPartitionActorDesc::GetHLODLayer () const inline
Definition at line 286 of file WorldPartitionActorDesc.h.
References HLODLayer.
GetIsSpatiallyLoaded()
bool FWorldPartitionActorDesc::GetIsSpatiallyLoaded () const inline
Definition at line 279 of file WorldPartitionActorDesc.h.
References bIsSpatiallyLoaded, and RuntimeBounds.
GetIsSpatiallyLoadedRaw()
bool FWorldPartitionActorDesc::GetIsSpatiallyLoadedRaw () const inline
Definition at line 280 of file WorldPartitionActorDesc.h.
References bIsSpatiallyLoaded.
GetLoadedChildWorldPartition()
virtual UWorldPartition * FWorldPartitionActorDesc::GetLoadedChildWorldPartition (const FWorldPartitionActorDescInstance * InActorDescInstance) const inline protected virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 509 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInstance, and UWorldPartition.
GetNativeClass()
FTopLevelAssetPath FWorldPartitionActorDesc::GetNativeClass () const inline
Definition at line 275 of file WorldPartitionActorDesc.h.
References NativeClass.
GetParentActor()
const FGuid & FWorldPartitionActorDesc::GetParentActor () const inline
Definition at line 303 of file WorldPartitionActorDesc.h.
References ParentActor.
Referenced by GetSceneOutlinerParent().
GetProperty()
bool FWorldPartitionActorDesc::GetProperty (FName PropertyName, FName * PropertyValue) const inline
Definition at line 306 of file WorldPartitionActorDesc.h.
References Properties, and PropertyName.
GetRuntimeBounds()
FBox FWorldPartitionActorDesc::GetRuntimeBounds () const
GetRuntimeGrid()
FName FWorldPartitionActorDesc::GetRuntimeGrid () const inline
Definition at line 278 of file WorldPartitionActorDesc.h.
References RuntimeGrid.
GetSceneOutlinerParent()
virtual const FGuid & FWorldPartitionActorDesc::GetSceneOutlinerParent () const inline virtual
Reimplemented in FLandscapeActorDesc.
Definition at line 329 of file WorldPartitionActorDesc.h.
References GetParentActor().
GetSizeOf()
virtual uint32 FWorldPartitionActorDesc::GetSizeOf () const inline protected virtual
Reimplemented in FHLODActorDesc, FLandscapeActorDesc, FLevelInstanceActorDesc, FMapBuildDataActorDesc, FPackedLevelActorDesc, FPartitionActorDesc, and FWorldDataLayersActorDesc.
Definition at line 530 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDesc().
GetTags()
const TArray< FName > & FWorldPartitionActorDesc::GetTags () const inline
Definition at line 291 of file WorldPartitionActorDesc.h.
References Tags.
HasProperty()
bool FWorldPartitionActorDesc::HasProperty (FName PropertyName) const inline
Definition at line 307 of file WorldPartitionActorDesc.h.
References Properties, and PropertyName.
HasStandaloneHLOD()
virtual bool FWorldPartitionActorDesc::HasStandaloneHLOD () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 489 of file WorldPartitionActorDesc.h.
Init() [1/2]
virtual void FWorldPartitionActorDesc::Init (const AActor * InActor) virtual
Reimplemented in FHLODActorDesc, FLandscapeActorDesc, FLevelInstanceActorDesc, FMapBuildDataActorDesc, FPackedLevelActorDesc, FPartitionActorDesc, and FWorldDataLayersActorDesc.
References AActor.
Init() [2/2]
virtual void FWorldPartitionActorDesc::Init (const FWorldPartitionActorDescInitData & DescData) virtual
Reimplemented in FLevelInstanceActorDesc, and FPackedLevelActorDesc.
InitTransientProperties()
void FWorldPartitionActorDesc::InitTransientProperties (const FWorldPartitionActorDescInitData & DescData) protected
IsChildContainerInstance()
virtual bool FWorldPartitionActorDesc::IsChildContainerInstance () const inline virtual
Reimplemented in FLevelInstanceActorDesc.
Definition at line 320 of file WorldPartitionActorDesc.h.
IsDefaultActorDesc()
bool FWorldPartitionActorDesc::IsDefaultActorDesc () const inline
Definition at line 318 of file WorldPartitionActorDesc.h.
References bIsDefaultActorDesc.
IsEditorRelevant()
virtual bool FWorldPartitionActorDesc::IsEditorRelevant (const FWorldPartitionActorDescInstance * InActorDescInstance) const protected virtual
References FWorldPartitionActorDescInstance.
Referenced by UE_DEPRECATED().
IsListedInSceneOutliner()
bool FWorldPartitionActorDesc::IsListedInSceneOutliner () const
IsMainWorldOnly()
bool FWorldPartitionActorDesc::IsMainWorldOnly () const
IsResaveNeeded()
virtual bool FWorldPartitionActorDesc::IsResaveNeeded () const inline virtual
Reimplemented in FWorldDataLayersActorDesc.
Definition at line 330 of file WorldPartitionActorDesc.h.
References bIsSpatiallyLoaded, and RuntimeBounds.
IsRuntimeRelevant()
virtual bool FWorldPartitionActorDesc::IsRuntimeRelevant (const FWorldPartitionActorDescInstance * InActorDescInstance) const protected virtual
Reimplemented in FHLODActorDesc, FMapBuildDataActorDesc, and FWorldDataLayersActorDesc.
References FWorldPartitionActorDescInstance.
Referenced by UE_DEPRECATED().
IsUsingDataLayerAsset()
bool FWorldPartitionActorDesc::IsUsingDataLayerAsset () const inline
Definition at line 304 of file WorldPartitionActorDesc.h.
References bIsUsingDataLayerAsset.
operator==()
bool FWorldPartitionActorDesc::operator== (const FWorldPartitionActorDesc & Other) const inline
Definition at line 334 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDesc(), Guid, and Other.
Patch()
void FWorldPartitionActorDesc::Patch (const FWorldPartitionActorDescInitData & DescData, TArray< uint8 > & OutData, FWorldPartitionAssetDataPatcher * InAssetDataPatcher) static
RegisterActorDescDeprecator()
void FWorldPartitionActorDesc::RegisterActorDescDeprecator (TSubclassOf< AActor > ActorClass, const FActorDescDeprecator & Deprecator) static
Serialize()
virtual void FWorldPartitionActorDesc::Serialize (FArchive & Ar) protected virtual
Reimplemented in FHLODActorDesc, FLandscapeActorDesc, FLevelInstanceActorDesc, FMapBuildDataActorDesc, FPackedLevelActorDesc, FPartitionActorDesc, and FWorldDataLayersActorDesc.
References Ar.
SerializeTo()
void FWorldPartitionActorDesc::SerializeTo (TArray< uint8 > & OutData, FWorldPartitionActorDesc * BaseDesc = nullptr) const
References FWorldPartitionActorDesc().
SetEditorBounds()
void FWorldPartitionActorDesc::SetEditorBounds (const FBox & InEditorBounds) protected
SetRuntimeBounds()
void FWorldPartitionActorDesc::SetRuntimeBounds (const FBox & InRuntimeBounds) protected
ShouldResave()
virtual bool FWorldPartitionActorDesc::ShouldResave (const FWorldPartitionActorDesc * Other) const virtual
Returns true if resaving this actor will have an impact on streaming generation.
Before class descriptors, properties changed on a Blueprint that would affect streaming generation weren't taken into account until the actors affected by the change were resaved.
References FWorldPartitionActorDesc(), and Other.
ToString()
FString FWorldPartitionActorDesc::ToString (EToStringMode Mode = EToStringMode::Compact) const
References Compact.
TransferFrom()
virtual void FWorldPartitionActorDesc::TransferFrom (const FWorldPartitionActorDesc * From) protected virtual
Reimplemented in FLevelInstanceActorDesc.
References FWorldPartitionActorDesc().
TransferWorldData()
virtual void FWorldPartitionActorDesc::TransferWorldData (const FWorldPartitionActorDesc * From) inline protected virtual
Reimplemented in FPartitionActorDesc.
Definition at line 517 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDesc(), ActorTransform, ActorTransformRelative, bHasValidRelativeBounds, EditorBounds, EditorBoundsRelative, RuntimeBounds, and RuntimeBoundsRelative.
UE_DEPRECATED() [1/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 1, "SetIsSpatiallyLoadedRaw is deprecated and should not be used.") inline
Definition at line 345 of file WorldPartitionActorDesc.h.
References bIsSpatiallyLoaded.
UE_DEPRECATED() [2/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 2, "GetBounds is deprecated, GetEditorBounds or GetRuntimeBounds should be used instead.") const inline
Definition at line 352 of file WorldPartitionActorDesc.h.
References GetEditorBounds().
UE_DEPRECATED() [3/18]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FWorldPartitionActorDesc::UE_DEPRECATED (5. 2, "GetOrigin is deprecated.") const inline
Definition at line 349 of file WorldPartitionActorDesc.h.
References FVector.
UE_DEPRECATED() [4/18]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FWorldPartitionActorDesc::UE_DEPRECATED (5. 2, "ShouldValidateRuntimeGrid is deprecated and should not be used") const inline
Definition at line 356 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [5/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 3, "GetLevelPackage is deprecated use GetChildContainerPackage instead") const inline
Definition at line 359 of file WorldPartitionActorDesc.h.
References GetChildContainerPackage().
UE_DEPRECATED() [6/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Please use FWorldPartitionActorDescInstance::GetUnloadedReason") const inline
Definition at line 377 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [7/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Please use FWorldPartitionActorDescInstance::SetUnloadedReason") inline
Definition at line 380 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [8/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance::GetDataLayerInstanceNames") const inline
Definition at line 365 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [9/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance::HasResolvedDataLayerInstanceNames") const inline
Definition at line 362 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [10/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance::IsEditorRelevant instead") const inline
Definition at line 374 of file WorldPartitionActorDesc.h.
References IsEditorRelevant().
UE_DEPRECATED() [11/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance::IsRuntimeRelevant instead") const & inline
Definition at line 371 of file WorldPartitionActorDesc.h.
References IsRuntimeRelevant().
UE_DEPRECATED() [12/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance::SetDataLayerInstanceNames") const & inline
Definition at line 368 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [13/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use GetChildContainerFilter instead") const inline
Definition at line 392 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [14/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use GetChildContainerFilterType instead") const inline
Definition at line 389 of file WorldPartitionActorDesc.h.
References None.
UE_DEPRECATED() [15/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use GetChildContainerInstance instead") const & inline
Definition at line 395 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [16/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use GetChildContainerPackage instead") const inline
Definition at line 386 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [17/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use IsChildContainerInstance instead") const inline
Definition at line 383 of file WorldPartitionActorDesc.h.
UE_DEPRECATED() [18/18]
FWorldPartitionActorDesc::UE_DEPRECATED (5. 4, "Use SetContainer without World param")
Friends And Related Symbol Documentation
AActor
friend class AActor friend
Definition at line 239 of file WorldPartitionActorDesc.h.
References AActor.
Referenced by AActor, FHLODActorDesc::Init(), FLandscapeActorDesc::Init(), FLevelInstanceActorDesc::Init(), FMapBuildDataActorDesc::Init(), FPackedLevelActorDesc::Init(), FPartitionActorDesc::Init(), FWorldDataLayersActorDesc::Init(), and Init().
FActorDescArchive
friend class FActorDescArchive friend
Definition at line 246 of file WorldPartitionActorDesc.h.
References FActorDescArchive.
Referenced by FActorDescArchive.
FAssetHeaderPatcherInner
friend class FAssetHeaderPatcherInner friend
Definition at line 245 of file WorldPartitionActorDesc.h.
References FAssetHeaderPatcherInner.
Referenced by FAssetHeaderPatcherInner.
FPropertyOverrideUtils
friend class FPropertyOverrideUtils friend
Definition at line 249 of file WorldPartitionActorDesc.h.
References FPropertyOverrideUtils.
Referenced by FPropertyOverrideUtils.
FStreamingGenerationTempActorDescInstance
friend class FStreamingGenerationTempActorDescInstance friend
Definition at line 248 of file WorldPartitionActorDesc.h.
References FStreamingGenerationTempActorDescInstance.
Referenced by FStreamingGenerationTempActorDescInstance.
FWorldPartitionActorDescInstance
friend class FWorldPartitionActorDescInstance friend
Definition at line 247 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInstance.
Referenced by FLevelInstanceActorDesc::CreateChildContainerInstance(), CreateChildContainerInstance(), FWorldPartitionActorDescInstance, FLevelInstanceActorDesc::GetChildContainerInstance(), GetChildContainerInstance(), FLevelInstanceActorDesc::GetLoadedChildWorldPartition(), GetLoadedChildWorldPartition(), IsEditorRelevant(), FHLODActorDesc::IsRuntimeRelevant(), FMapBuildDataActorDesc::IsRuntimeRelevant(), FWorldDataLayersActorDesc::IsRuntimeRelevant(), and IsRuntimeRelevant().
FWorldPartitionActorDescUnitTestAcccessor
friend struct FWorldPartitionActorDescUnitTestAcccessor friend
Definition at line 244 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescUnitTestAcccessor.
Referenced by FWorldPartitionActorDescUnitTestAcccessor.
FWorldPartitionActorDescUtils
friend struct FWorldPartitionActorDescUtils friend
Definition at line 243 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescUtils.
Referenced by FWorldPartitionActorDescUtils.
FWorldPartitionHandleImpl
friend struct FWorldPartitionHandleImpl friend
Definition at line 241 of file WorldPartitionActorDesc.h.
References FWorldPartitionHandleImpl.
Referenced by FWorldPartitionHandleImpl.
FWorldPartitionReferenceImpl
friend struct FWorldPartitionReferenceImpl friend
Definition at line 242 of file WorldPartitionActorDesc.h.
References FWorldPartitionReferenceImpl.
Referenced by FWorldPartitionReferenceImpl.
GetTypeHash
uint32 GetTypeHash (const FWorldPartitionActorDesc & Key) friend
Definition at line 339 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDesc(), GetTypeHash, and Key.
Referenced by GetTypeHash.
TActorDescContainerCollection
template<class U> friend class TActorDescContainerCollection friend
Definition at line 250 of file WorldPartitionActorDesc.h.
References TActorDescContainerCollection.
Referenced by TActorDescContainerCollection.
UWorldPartition
friend class UWorldPartition friend
Definition at line 240 of file WorldPartitionActorDesc.h.
References UWorldPartition.
Referenced by FLevelInstanceActorDesc::GetLoadedChildWorldPartition(), GetLoadedChildWorldPartition(), and UWorldPartition.
Field Documentation
ActorDisplayClassNameString
FString FWorldPartitionActorDesc::ActorDisplayClassNameString protected
Definition at line 572 of file WorldPartitionActorDesc.h.
ActorLabel
FName FWorldPartitionActorDesc::ActorLabel protected
Definition at line 543 of file WorldPartitionActorDesc.h.
Referenced by GetActorLabel().
ActorLabelString
FString FWorldPartitionActorDesc::ActorLabelString protected
Definition at line 571 of file WorldPartitionActorDesc.h.
ActorName
FName FWorldPartitionActorDesc::ActorName protected
Definition at line 569 of file WorldPartitionActorDesc.h.
ActorNameString
FString FWorldPartitionActorDesc::ActorNameString protected
Definition at line 570 of file WorldPartitionActorDesc.h.
ActorNativeClass
UClass* FWorldPartitionActorDesc::ActorNativeClass protected
Definition at line 568 of file WorldPartitionActorDesc.h.
Referenced by GetActorNativeClass().
ActorPackage
FName FWorldPartitionActorDesc::ActorPackage protected
Definition at line 541 of file WorldPartitionActorDesc.h.
Referenced by GetActorPackage().
ActorPath
FSoftObjectPath FWorldPartitionActorDesc::ActorPath protected
Definition at line 542 of file WorldPartitionActorDesc.h.
Referenced by GetActorSoftPath().
ActorTransform
FTransform FWorldPartitionActorDesc::ActorTransform protected
Definition at line 574 of file WorldPartitionActorDesc.h.
Referenced by GetActorTransform(), and TransferWorldData().
ActorTransformRelative
FTransform FWorldPartitionActorDesc::ActorTransformRelative protected
Definition at line 544 of file WorldPartitionActorDesc.h.
Referenced by TransferWorldData().
bActorIsEditorOnly
bool FWorldPartitionActorDesc::bActorIsEditorOnly protected
Definition at line 549 of file WorldPartitionActorDesc.h.
Referenced by GetActorIsEditorOnly().
bActorIsHLODRelevant
bool FWorldPartitionActorDesc::bActorIsHLODRelevant protected
Definition at line 552 of file WorldPartitionActorDesc.h.
Referenced by GetActorIsHLODRelevant().
bActorIsListedInSceneOutliner
bool FWorldPartitionActorDesc::bActorIsListedInSceneOutliner protected
Definition at line 553 of file WorldPartitionActorDesc.h.
bActorIsMainWorldOnly
bool FWorldPartitionActorDesc::bActorIsMainWorldOnly protected
Definition at line 551 of file WorldPartitionActorDesc.h.
bActorIsRuntimeOnly
bool FWorldPartitionActorDesc::bActorIsRuntimeOnly protected
Definition at line 550 of file WorldPartitionActorDesc.h.
Referenced by GetActorIsRuntimeOnly().
BaseClass
FTopLevelAssetPath FWorldPartitionActorDesc::BaseClass protected
Definition at line 539 of file WorldPartitionActorDesc.h.
Referenced by GetBaseClass().
bHasValidRelativeBounds
bool FWorldPartitionActorDesc::bHasValidRelativeBounds protected
Definition at line 578 of file WorldPartitionActorDesc.h.
Referenced by TransferWorldData().
bIsDefaultActorDesc
bool FWorldPartitionActorDesc::bIsDefaultActorDesc protected
Definition at line 577 of file WorldPartitionActorDesc.h.
Referenced by IsDefaultActorDesc().
bIsSpatiallyLoaded
bool FWorldPartitionActorDesc::bIsSpatiallyLoaded protected
Definition at line 548 of file WorldPartitionActorDesc.h.
Referenced by GetIsSpatiallyLoaded(), GetIsSpatiallyLoadedRaw(), IsResaveNeeded(), and UE_DEPRECATED().
bIsUsingDataLayerAsset
bool FWorldPartitionActorDesc::bIsUsingDataLayerAsset protected
Definition at line 554 of file WorldPartitionActorDesc.h.
Referenced by IsUsingDataLayerAsset().
Container
UActorDescContainer* FWorldPartitionActorDesc::Container protected
Definition at line 573 of file WorldPartitionActorDesc.h.
Referenced by FWorldPartitionActorDesc::FContainerInstance::UE_DEPRECATED().
ContentBundleGuid
FGuid FWorldPartitionActorDesc::ContentBundleGuid protected
Definition at line 565 of file WorldPartitionActorDesc.h.
DataLayers
TArray<FName> FWorldPartitionActorDesc::DataLayers protected
Definition at line 556 of file WorldPartitionActorDesc.h.
Deprecators
TMap<TSubclassOf<AActor>, FActorDescDeprecator> FWorldPartitionActorDesc::Deprecators static protected
Definition at line 580 of file WorldPartitionActorDesc.h.
EditorBounds
FBox FWorldPartitionActorDesc::EditorBounds protected
Definition at line 576 of file WorldPartitionActorDesc.h.
Referenced by TransferWorldData().
EditorBoundsRelative
FWorldPartitionRelativeBounds FWorldPartitionActorDesc::EditorBoundsRelative protected
Definition at line 546 of file WorldPartitionActorDesc.h.
Referenced by TransferWorldData().
EditorOnlyReferences
TArray<FGuid> FWorldPartitionActorDesc::EditorOnlyReferences protected
Definition at line 559 of file WorldPartitionActorDesc.h.
ExternalDataLayerAsset
FSoftObjectPath FWorldPartitionActorDesc::ExternalDataLayerAsset protected
Definition at line 557 of file WorldPartitionActorDesc.h.
Referenced by GetExternalDataLayerAsset().
FolderGuid
FGuid FWorldPartitionActorDesc::FolderGuid protected
Definition at line 563 of file WorldPartitionActorDesc.h.
Referenced by GetFolderGuid().
FolderPath
FName FWorldPartitionActorDesc::FolderPath protected
Definition at line 562 of file WorldPartitionActorDesc.h.
Referenced by GetFolderPath().
Guid
FGuid FWorldPartitionActorDesc::Guid protected
Definition at line 538 of file WorldPartitionActorDesc.h.
Referenced by GetGuid(), and operator==().
HLODLayer
FSoftObjectPath FWorldPartitionActorDesc::HLODLayer protected
Definition at line 555 of file WorldPartitionActorDesc.h.
Referenced by GetHLODLayer().
InWorldContext
UWorld* FWorldPartitionActorDesc::InWorldContext
Definition at line 399 of file WorldPartitionActorDesc.h.
NativeClass
FTopLevelAssetPath FWorldPartitionActorDesc::NativeClass protected
Definition at line 540 of file WorldPartitionActorDesc.h.
Referenced by GetNativeClass().
ParentActor
FGuid FWorldPartitionActorDesc::ParentActor protected
Definition at line 564 of file WorldPartitionActorDesc.h.
Referenced by GetParentActor().
Properties
FPropertyPairsMap FWorldPartitionActorDesc::Properties protected
Definition at line 561 of file WorldPartitionActorDesc.h.
Referenced by AddProperty(), GetProperty(), and HasProperty().
References
TArray<FGuid> FWorldPartitionActorDesc::References protected
Definition at line 558 of file WorldPartitionActorDesc.h.
RuntimeBounds
FBox FWorldPartitionActorDesc::RuntimeBounds protected
Definition at line 575 of file WorldPartitionActorDesc.h.
Referenced by GetIsSpatiallyLoaded(), IsResaveNeeded(), and TransferWorldData().
RuntimeBoundsRelative
FWorldPartitionRelativeBounds FWorldPartitionActorDesc::RuntimeBoundsRelative protected
Definition at line 545 of file WorldPartitionActorDesc.h.
Referenced by TransferWorldData().
RuntimeGrid
FName FWorldPartitionActorDesc::RuntimeGrid protected
Definition at line 547 of file WorldPartitionActorDesc.h.
Referenced by GetRuntimeGrid().
Tags
TArray<FName> FWorldPartitionActorDesc::Tags protected
Definition at line 560 of file WorldPartitionActorDesc.h.
Referenced by GetTags().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionActorDesc.h