Unreal Engine 5.6 C++ API: FShaderParametersMetadataBuilder Class Reference
FShaderParametersMetadataBuilder Class Reference
#include "ShaderParameterMetadataBuilder.h"
Public Member Functions
FShaderParametersMetadataBuilder ()
FShaderParametersMetadataBuilder (const FShaderParametersMetadata *RootParametersMetadata)
RENDERCORE_API void AddBufferSRV (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddBufferUAV (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddIncludedStruct (const FShaderParametersMetadata *StructMetadata, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
template<typename T>
void AddIncludedStruct (EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API uint32 AddNestedStruct (const TCHAR *Name, const FShaderParametersMetadata *StructMetadata, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
template<typename T>
uint32 AddNestedStruct (const TCHAR *Name, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
template<typename T>
void AddParam (const TCHAR *Name, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
template<typename T>
void AddParamArray (const TCHAR *Name, int32 NumElements, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddRDGBufferSRV (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddRDGBufferUAV (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddRDGTexture (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddReferencedStruct (const TCHAR *Name, const FShaderParametersMetadata *StructMetadata, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
template<typename T>
void AddReferencedStruct (const TCHAR *Name, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddRenderTargetBindingSlots (const TCHAR *Name=TEXT("RenderTargets"), const TCHAR *ShaderType=TEXT(""), EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddSampler (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
RENDERCORE_API void AddTexture (const TCHAR *Name, const TCHAR *ShaderType, EShaderPrecisionModifier::Type Precision=EShaderPrecisionModifier::Float)
void AlignNextMemberToStruct ()
RENDERCORE_API FShaderParametersMetadata * Build (FShaderParametersMetadata::EUseCase InUseCase, EUniformBufferBindingFlags InBindingFlags, const TCHAR *InLayoutName, const TCHAR *InStructTypeName, const TCHAR *InShaderVariableName, const TCHAR *InStaticSlotName, const ANSICHAR *InFileName, const int32 InFileLine, bool bForceCompleteInitialization=false, FRHIUniformBufferLayoutInitializer *OutLayoutInitializer=nullptr, FShaderParametersMetadata::EUsageFlags InUsageFlags=FShaderParametersMetadata::EUsageFlags::None)
RENDERCORE_API FShaderParametersMetadata * Build (FShaderParametersMetadata::EUseCase UseCase, const TCHAR *ShaderParameterName)
uint32 GetNextMemberOffset () const
Private Attributes
TArray< FShaderParametersMetadata::FMember > Members
uint32 NextMemberOffset = 0
Detailed Description
Definition at line 14 of file ShaderParameterMetadataBuilder.h.
Constructor & Destructor Documentation
FShaderParametersMetadataBuilder() [1/2]
FShaderParametersMetadataBuilder::FShaderParametersMetadataBuilder () inline
Definition at line 17 of file ShaderParameterMetadataBuilder.h.
FShaderParametersMetadataBuilder() [2/2]
FShaderParametersMetadataBuilder::FShaderParametersMetadataBuilder (const FShaderParametersMetadata * RootParametersMetadata) inline explicit
Definition at line 19 of file ShaderParameterMetadataBuilder.h.
References FShaderParametersMetadata::GetMembers(), FShaderParametersMetadata::GetSize(), Members, and NextMemberOffset.
Member Function Documentation
AddBufferSRV()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddBufferSRV (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddBufferUAV()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddBufferUAV (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddIncludedStruct() [1/2]
RENDERCORE_API void FShaderParametersMetadataBuilder::AddIncludedStruct (const FShaderParametersMetadata * StructMetadata, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float.
AddIncludedStruct() [2/2]
template<typename T> void FShaderParametersMetadataBuilder::AddIncludedStruct (EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float) inline
Definition at line 97 of file ShaderParameterMetadataBuilder.h.
References AddIncludedStruct(), EShaderPrecisionModifier::Float, and TShaderParameterStructTypeInfo< StructType >::GetStructMetadata().
Referenced by AddIncludedStruct().
AddNestedStruct() [1/2]
RENDERCORE_API uint32 FShaderParametersMetadataBuilder::AddNestedStruct (const TCHAR * Name, const FShaderParametersMetadata * StructMetadata, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddNestedStruct() [2/2]
template<typename T> uint32 FShaderParametersMetadataBuilder::AddNestedStruct (const TCHAR * Name, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float) inline
Definition at line 110 of file ShaderParameterMetadataBuilder.h.
References Align, EShaderPrecisionModifier::Float, Members, Name, NextMemberOffset, and TEXT.
AddParam()
template<typename T> void FShaderParametersMetadataBuilder::AddParam (const TCHAR * Name, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float) inline
Definition at line 29 of file ShaderParameterMetadataBuilder.h.
References Align, EShaderPrecisionModifier::Float, Members, Name, NextMemberOffset, and TEXT.
AddParamArray()
template<typename T> void FShaderParametersMetadataBuilder::AddParamArray (const TCHAR * Name, int32 NumElements, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float) inline
Definition at line 55 of file ShaderParameterMetadataBuilder.h.
References Align, EShaderPrecisionModifier::Float, Members, Name, NextMemberOffset, and TEXT.
AddRDGBufferSRV()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddRDGBufferSRV (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddRDGBufferUAV()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddRDGBufferUAV (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddRDGTexture()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddRDGTexture (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddReferencedStruct() [1/2]
RENDERCORE_API void FShaderParametersMetadataBuilder::AddReferencedStruct (const TCHAR * Name, const FShaderParametersMetadata * StructMetadata, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddReferencedStruct() [2/2]
template<typename T> void FShaderParametersMetadataBuilder::AddReferencedStruct (const TCHAR * Name, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float) inline
Definition at line 82 of file ShaderParameterMetadataBuilder.h.
References AddReferencedStruct(), EShaderPrecisionModifier::Float, TShaderParameterStructTypeInfo< StructType >::GetStructMetadata(), and Name.
Referenced by AddReferencedStruct().
AddRenderTargetBindingSlots()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddRenderTargetBindingSlots (const TCHAR * Name = TEXT("RenderTargets"), const TCHAR * ShaderType = TEXT(""), EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddSampler()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddSampler (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AddTexture()
RENDERCORE_API void FShaderParametersMetadataBuilder::AddTexture (const TCHAR * Name, const TCHAR * ShaderType, EShaderPrecisionModifier::Type Precision = EShaderPrecisionModifier::Float)
References EShaderPrecisionModifier::Float, and Name.
AlignNextMemberToStruct()
void FShaderParametersMetadataBuilder::AlignNextMemberToStruct () inline
Definition at line 191 of file ShaderParameterMetadataBuilder.h.
References Align, and NextMemberOffset.
Build() [1/2]
RENDERCORE_API FShaderParametersMetadata * FShaderParametersMetadataBuilder::Build (FShaderParametersMetadata::EUseCase InUseCase, EUniformBufferBindingFlags InBindingFlags, const TCHAR * InLayoutName, const TCHAR * InStructTypeName, const TCHAR * InShaderVariableName, const TCHAR * InStaticSlotName, const ANSICHAR * InFileName, const int32 InFileLine, bool bForceCompleteInitialization = false, FRHIUniformBufferLayoutInitializer * OutLayoutInitializer = nullptr, FShaderParametersMetadata::EUsageFlags InUsageFlags = FShaderParametersMetadata::EUsageFlags::None)
References FShaderParametersMetadata::None.
Build() [2/2]
RENDERCORE_API FShaderParametersMetadata * FShaderParametersMetadataBuilder::Build (FShaderParametersMetadata::EUseCase UseCase, const TCHAR * ShaderParameterName)
GetNextMemberOffset()
uint32 FShaderParametersMetadataBuilder::GetNextMemberOffset () const inline
Definition at line 196 of file ShaderParameterMetadataBuilder.h.
References NextMemberOffset.
Field Documentation
Members
TArray<FShaderParametersMetadata::FMember> FShaderParametersMetadataBuilder::Members private
Definition at line 218 of file ShaderParameterMetadataBuilder.h.
Referenced by FShaderParametersMetadataBuilder(), AddNestedStruct(), AddParam(), and AddParamArray().
NextMemberOffset
uint32 FShaderParametersMetadataBuilder::NextMemberOffset = 0 private
Definition at line 219 of file ShaderParameterMetadataBuilder.h.
Referenced by FShaderParametersMetadataBuilder(), AddNestedStruct(), AddParam(), AddParamArray(), AlignNextMemberToStruct(), and GetNextMemberOffset().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameterMetadataBuilder.h