Unreal Engine 5.6 C++ API: UAbilitySystemBlueprintLibrary Class Reference
UAbilitySystemBlueprintLibrary Class Reference
#include "AbilitySystemBlueprintLibrary.h"
Public Member Functions
UE_DEPRECATED (5.3, "Linked GameplayEffects aren't replicated. The new UAdditionalGameplayEffectsComponent renders this functionality obsolete (and since it's configured in the Asset, it is properly synced).") UFUNCTION()) static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AddLinkedGameplayEffect(FGameplayEffectSpecHandle SpecHandle
Adds LinkedGameplayEffect to SpecHandles.
UE_DEPRECATED (5.3, "Linked GameplayEffects aren't replicated. The new UAdditionalGameplayEffectsComponent renders this functionality obsolete (and since it's configured in the Asset, it is properly synced).") UFUNCTION()) static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AddLinkedGameplayEffectSpec(FGameplayEffectSpecHandle SpecHandle
Adds LinkedGameplayEffectSpec to SpecHandles.
UE_DEPRECATED (5.3, "Linked GameplayEffects aren't replicated. The new UAdditionalGameplayEffectsComponent renders this functionality obsolete (and since it's configured in the Asset, it is properly synced).") UFUNCTION()) static GAMEPLAYABILITIES_API TArray< FGameplayEffectSpecHandle > GetAllLinkedGameplayEffectSpecHandles(FGameplayEffectSpecHandle SpecHandle)
Returns handles for all Linked GE Specs that SpecHandle may apply.
UE_DEPRECATED (5.5, "Use MakeSpecHandleByClass. It's safer as InGameplayEffect needs to be a CDO") UFUNCTION() ")) static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle MakeSpecHandle(UGameplayEffect* InGameplayEffect
Create a spec handle, filling out all fields.
UFUNCTION () "
Simple equality operator for gameplay attributes.
UFUNCTION () "
Simple inequality operator for gameplay attributes.
UFUNCTION () "
Equality operator for two Active Gameplay Effect Handles.
UFUNCTION () "
Inequality operator for two Active Gameplay Effect Handles.
UFUNCTION () "
Equality operator for two Gameplay Ability Spec Handles.
UFUNCTION () "
Inequality operator for two Gameplay Ability Spec Handles.
UFUNCTION () "
Converts the given Scalable float to the value at the given level.
UFUNCTION () "
Converts the given Scalable float to the value at the given level.
UFUNCTION () ")) static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle MakeSpecHandleByClass(TSubclassOf<UGameplayEffect> GameplayEffect
Create a spec handle, filling out all fields.
UFUNCTION () static GAMEPLAYABILITIES_API AActor *GetActorByIndex(FGameplayCueParameters Parameters
Returns actor stored in the Effect Context used by this cue.
UFUNCTION () static GAMEPLAYABILITIES_API AActor *GetInstigatorActor(FGameplayCueParameters Parameters)
Gets the instigating actor (that holds the ability system component) of the GameplayCue.
UFUNCTION () static GAMEPLAYABILITIES_API bool AddLooseGameplayTags(AActor *Actor
Manually adds a set of tags to a given actor, and optionally replicates them.
UFUNCTION () static GAMEPLAYABILITIES_API bool DoesGameplayCueMeetTagRequirements(FGameplayCueParameters Parameters
Returns true if the aggregated source and target tags from the effect spec meets the tag requirements.
UFUNCTION () static GAMEPLAYABILITIES_API bool DoesTargetDataContainActor(const FGameplayAbilityTargetDataHandle &TargetData
Returns true if the given TargetData has the actor passed in targeted.
UFUNCTION () static GAMEPLAYABILITIES_API bool GetGameplayCueDirection(AActor *TargetActor
Gets the best normalized effect direction for this gameplay cue.
UFUNCTION () static GAMEPLAYABILITIES_API bool GetGameplayCueEndLocationAndNormal(AActor *TargetActor
Gets the best end location and normal for this gameplay cue.
UFUNCTION () static GAMEPLAYABILITIES_API bool HasHitResult(FGameplayCueParameters Parameters)
Checks if the effect context has a hit reslt stored inside.
UFUNCTION () static GAMEPLAYABILITIES_API bool IsInstigatorLocallyControlled(FGameplayCueParameters Parameters)
Returns true if the ability system component that spawned this cue is locally controlled.
UFUNCTION () static GAMEPLAYABILITIES_API bool IsInstigatorLocallyControlledPlayer(FGameplayCueParameters Parameters)
Returns true if the ability system component that spawned this cue is locally controlled and a player.
UFUNCTION () static GAMEPLAYABILITIES_API bool IsValid(FGameplayAttribute Attribute)
Returns true if the attribute actually exists.
UFUNCTION () static GAMEPLAYABILITIES_API bool RemoveLooseGameplayTags(AActor *Actor
Manually removes a set of tags from a given actor, with optional replication.
UFUNCTION () static GAMEPLAYABILITIES_API bool TargetDataHasActor(const FGameplayAbilityTargetDataHandle &TargetData
Returns true if the given TargetData has at least 1 actor targeted.
UFUNCTION () static GAMEPLAYABILITIES_API bool TargetDataHasEndPoint(const FGameplayAbilityTargetDataHandle &TargetData
Returns true if the target data has an end point.
UFUNCTION () static GAMEPLAYABILITIES_API bool TargetDataHasHitResult(const FGameplayAbilityTargetDataHandle &HitResult
Returns true if the target data has a hit result.
UFUNCTION () static GAMEPLAYABILITIES_API bool TargetDataHasOrigin(const FGameplayAbilityTargetDataHandle &TargetData
Returns true if the target data has an origin.
UFUNCTION () static GAMEPLAYABILITIES_API const UGameplayAbility *GetGameplayAbilityFromSpecHandle(UAbilitySystemComponent *AbilitySystem
Provides the Gameplay Ability object associated with an Ability Spec Handle This can be either an instanced ability, or in the case of shared abilities, the Class Default Object.
UFUNCTION () static GAMEPLAYABILITIES_API const UGameplayEffect *GetGameplayEffectFromActiveEffectHandle(const FActiveGameplayEffectHandle &ActiveHandle)
Returns the Gameplay Effect CDO from an active handle.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayAbilityTargetDataHandle AbilityTargetDataFromActor(AActor *Actor)
Creates single actor target data.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayAbilityTargetDataHandle AbilityTargetDataFromActorArray(const TArray< AActor * > &ActorArray
Creates actor array target data.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayAbilityTargetDataHandle AbilityTargetDataFromHitResult(const FHitResult &HitResult)
Creates a target data with a single hit result.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayAbilityTargetDataHandle AbilityTargetDataFromLocations(const FGameplayAbilityTargetingLocationInfo &SourceLocation
Creates a target data with a source and destination location.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayAbilityTargetDataHandle AppendTargetDataHandle(FGameplayAbilityTargetDataHandle TargetHandle
Copies targets from HandleToAdd to TargetHandle.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayAbilityTargetDataHandle FilterTargetData(const FGameplayAbilityTargetDataHandle &TargetDataHandle
Create a new target data handle with filtration performed on the data.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectContextHandle GetEffectContext(FGameplayEffectSpecHandle SpecHandle)
Gets the GameplayEffectSpec's effect context handle.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AddAssetTag(FGameplayEffectSpecHandle SpecHandle
Adds NewGameplayTag to this instance of the effect.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AddAssetTags(FGameplayEffectSpecHandle SpecHandle
Adds NewGameplayTags to this instance of the effect.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AddGrantedTag(FGameplayEffectSpecHandle SpecHandle
This instance of the effect will now grant NewGameplayTag to the object that this effect is applied to.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AddGrantedTags(FGameplayEffectSpecHandle SpecHandle
This instance of the effect will now grant NewGameplayTags to the object that this effect is applied to.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AssignSetByCallerMagnitude(FGameplayEffectSpecHandle SpecHandle
Sets a raw name Set By Caller magnitude value, the tag version should normally be used.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle CloneSpecHandle(AActor *InNewInstigator
Create a spec handle, cloning another.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle SetDuration(FGameplayEffectSpecHandle SpecHandle
Manually sets the duration on a specific effect.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle SetStackCount(FGameplayEffectSpecHandle SpecHandle
Sets the GameplayEffectSpec's StackCount to the specified amount (prior to applying)
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle SetStackCountToMax(FGameplayEffectSpecHandle SpecHandle)
Sets the GameplayEffectSpec's StackCount to the max stack count defined in the GameplayEffect definition.
UFUNCTION () static GAMEPLAYABILITIES_API FGameplayTargetDataFilterHandle MakeFilterHandle(FGameplayTargetDataFilter Filter
Create a handle for filtering target data, filling out all fields.
UFUNCTION () static GAMEPLAYABILITIES_API FHitResult GetHitResult(FGameplayCueParameters Parameters)
Returns a hit result stored in the effect context if valid.
UFUNCTION () static GAMEPLAYABILITIES_API FHitResult GetHitResultFromTargetData(const FGameplayAbilityTargetDataHandle &HitResult
Returns the hit result for a given index if it exists.
UFUNCTION () static GAMEPLAYABILITIES_API float EvaluateAttributeValueWithTags(UAbilitySystemComponent *AbilitySystem
Returns the value of Attribute from the ability system component AbilitySystem after evaluating it with source and target tags.
UFUNCTION () static GAMEPLAYABILITIES_API float EvaluateAttributeValueWithTagsAndBase(UAbilitySystemComponent *AbilitySystem
Returns the value of Attribute from the ability system component AbilitySystem after evaluating it with source and target tags using the passed in base value instead of the real base value.
UFUNCTION () static GAMEPLAYABILITIES_API float GetActiveGameplayEffectExpectedEndTime(FActiveGameplayEffectHandle ActiveHandle)
Returns the expected end time (when we think the GE will expire) for a given GameplayEffect (note someone could remove or change it before that happens!)
UFUNCTION () static GAMEPLAYABILITIES_API float GetActiveGameplayEffectStartTime(FActiveGameplayEffectHandle ActiveHandle)
Returns the start time (time which the GE was added) for a given GameplayEffect.
UFUNCTION () static GAMEPLAYABILITIES_API float GetActiveGameplayEffectTotalDuration(FActiveGameplayEffectHandle ActiveHandle)
Returns the total duration for a given GameplayEffect.
UFUNCTION () static GAMEPLAYABILITIES_API float GetFloatAttribute(const AActor *Actor
Returns the value of Attribute from the ability system component belonging to Actor.
UFUNCTION () static GAMEPLAYABILITIES_API float GetFloatAttributeBase(const AActor *Actor
Returns the base value of Attribute from the ability system component belonging to Actor.
UFUNCTION () static GAMEPLAYABILITIES_API float GetFloatAttributeBaseFromAbilitySystemComponent(const UAbilitySystemComponent *AbilitySystemComponent
Returns the base value of Attribute from the ability system component AbilitySystemComponent.
UFUNCTION () static GAMEPLAYABILITIES_API float GetFloatAttributeFromAbilitySystemComponent(const UAbilitySystemComponent *AbilitySystem
Returns the value of Attribute from the ability system component AbilitySystem.
UFUNCTION () static GAMEPLAYABILITIES_API float GetModifiedAttributeMagnitude(FGameplayEffectSpecHandle SpecHandle
Gets the magnitude of change for an attribute on an APPLIED GameplayEffectSpec.
UFUNCTION () static GAMEPLAYABILITIES_API FString GetDebugStringFromGameplayAttribute(const FGameplayAttribute &Attribute)
Returns FString representation of a gameplay attribute's set class and name, in the form of AttrSetName.AttrName (or just AttrName if not part of a set).
UFUNCTION () static GAMEPLAYABILITIES_API FTransform GetInstigatorTransform(FGameplayCueParameters Parameters)
Gets instigating world location.
UFUNCTION () static GAMEPLAYABILITIES_API FTransform GetTargetDataEndPointTransform(const FGameplayAbilityTargetDataHandle &TargetData
Returns the end point transform for a given index if it exists.
UFUNCTION () static GAMEPLAYABILITIES_API FTransform GetTargetDataOrigin(const FGameplayAbilityTargetDataHandle &TargetData
Returns the origin for a given index if it exists.
UFUNCTION () static GAMEPLAYABILITIES_API FVector GetOrigin(FGameplayCueParameters Parameters)
Gets instigating world location.
UFUNCTION () static GAMEPLAYABILITIES_API FVector GetTargetDataEndPoint(const FGameplayAbilityTargetDataHandle &TargetData
Returns the end point for a given index if it exists.
UFUNCTION () static GAMEPLAYABILITIES_API int32 GetActiveGameplayEffectStackCount(FActiveGameplayEffectHandle ActiveHandle)
Returns current stack count of an active Gameplay Effect.
UFUNCTION () static GAMEPLAYABILITIES_API int32 GetActiveGameplayEffectStackLimitCount(FActiveGameplayEffectHandle ActiveHandle)
Returns stack limit count of an active Gameplay Effect.
UFUNCTION () static GAMEPLAYABILITIES_API int32 GetActorCount(FGameplayCueParameters Parameters)
Returns number of actors stored in the Effect Context used by this cue.
UFUNCTION () static GAMEPLAYABILITIES_API int32 GetDataCountFromTargetData(const FGameplayAbilityTargetDataHandle &TargetData)
Returns number of target data objects, not necessarily number of distinct targets.
UFUNCTION () static GAMEPLAYABILITIES_API TArray< AActor * > GetActorsFromTargetData(const FGameplayAbilityTargetDataHandle &TargetData
Returns all actors targeted, for a given index.
UFUNCTION () static GAMEPLAYABILITIES_API TArray< AActor * > GetAllActorsFromTargetData(const FGameplayAbilityTargetDataHandle &TargetData)
Returns all actors targeted.
UFUNCTION () static GAMEPLAYABILITIES_API void ForwardGameplayCueToTarget(TScriptInterface< IGameplayCueInterface > TargetCueInterface
Forwards the gameplay cue to another gameplay cue interface object.
UFUNCTION ()) static GAMEPLAYABILITIES_API AActor *EffectContextGetEffectCauser(FGameplayEffectContextHandle EffectContext)
Gets the physical actor that caused the effect, possibly a projectile or weapon.
UFUNCTION ()) static GAMEPLAYABILITIES_API AActor *EffectContextGetInstigatorActor(FGameplayEffectContextHandle EffectContext)
Gets the instigating actor (that holds the ability system component) of the EffectContext.
UFUNCTION ()) static GAMEPLAYABILITIES_API AActor *EffectContextGetOriginalInstigatorActor(FGameplayEffectContextHandle EffectContext)
Gets the original instigator actor that started the chain of events to cause this effect.
UFUNCTION ()) static GAMEPLAYABILITIES_API bool EffectContextHasHitResult(FGameplayEffectContextHandle EffectContext)
Returns true if there is a valid hit result inside the effect context.
UFUNCTION ()) static GAMEPLAYABILITIES_API bool EffectContextIsInstigatorLocallyControlled(FGameplayEffectContextHandle EffectContext)
Returns true if the ability system component that instigated this is locally controlled.
UFUNCTION ()) static GAMEPLAYABILITIES_API bool EffectContextIsValid(FGameplayEffectContextHandle EffectContext)
Returns true if this context has ever been initialized.
UFUNCTION ()) static GAMEPLAYABILITIES_API bool IsGameplayAbilityActive(const UGameplayAbility *GameplayAbility)
Returns true if the passed-in Gameplay Ability instance is active (activated and not yet ended).
UFUNCTION ()) static GAMEPLAYABILITIES_API const FGameplayTagContainer &GetGameplayEffectAssetTags(TSubclassOf< UGameplayEffect > EffectClass)
Returns all tags that the Gameplay Effect has (that denote the GE Asset itself) and does not grant to any Actor.
UFUNCTION ()) static GAMEPLAYABILITIES_API const FGameplayTagContainer &GetGameplayEffectGrantedTags(TSubclassOf< UGameplayEffect > EffectClass)
Returns all tags that the Gameplay Effect grants to the target Actor.
UFUNCTION ()) static GAMEPLAYABILITIES_API const UGameplayEffectUIData *GetGameplayEffectUIData(TSubclassOf< UGameplayEffect > EffectClass
Returns the UI data for a gameplay effect class (if any)
UFUNCTION ()) static GAMEPLAYABILITIES_API FGameplayCueParameters MakeGameplayCueParameters(float NormalizedMagnitude
Native make, to avoid having to deal with quantized vector types.
UFUNCTION ()) static GAMEPLAYABILITIES_API FGameplayEffectSpecHandle AssignTagSetByCallerMagnitude(FGameplayEffectSpecHandle SpecHandle
Sets a gameplay tag Set By Caller magnitude value.
UFUNCTION ()) static GAMEPLAYABILITIES_API FHitResult EffectContextGetHitResult(FGameplayEffectContextHandle EffectContext)
Extracts a hit result from the effect context if it is set.
UFUNCTION ()) static GAMEPLAYABILITIES_API float GetActiveGameplayEffectRemainingDuration(UObject *WorldContextObject
Returns the total duration for a given GameplayEffect, basically ExpectedEndTime - Current Time.
UFUNCTION ()) static GAMEPLAYABILITIES_API FString GetActiveGameplayEffectDebugString(FActiveGameplayEffectHandle ActiveHandle)
Returns a debug string for display.
UFUNCTION ()) static GAMEPLAYABILITIES_API FVector EffectContextGetOrigin(FGameplayEffectContextHandle EffectContext)
Gets the location the effect originated from.
UFUNCTION ()) static GAMEPLAYABILITIES_API UObject *EffectContextGetSourceObject(FGameplayEffectContextHandle EffectContext)
Gets the source object of the effect.
UFUNCTION ()) static GAMEPLAYABILITIES_API void BreakGameplayCueParameters(const struct FGameplayCueParameters &Parameters
Native break, to avoid having to deal with quantized vector types.
UFUNCTION ()) static GAMEPLAYABILITIES_API void EffectContextAddHitResult(FGameplayEffectContextHandle EffectContext
Adds a hit result to the effect context.
UFUNCTION ()) static GAMEPLAYABILITIES_API void EffectContextSetOrigin(FGameplayEffectContextHandle EffectContext
Sets the location the effect originated from.
Static Public Member Functions
static IgnoreTypePromotion GAMEPLAYABILITIES_API double Conv_ScalableFloatToDouble (const FScalableFloat &Input, float Level=0.0f)
static IgnoreTypePromotion GAMEPLAYABILITIES_API float Conv_ScalableFloatToFloat (const FScalableFloat &Input, float Level=0.0f)
static GAMEPLAYABILITIES_API float GetModifiedAttributeMagnitude (const FGameplayEffectSpec &SpecHandle, FGameplayAttribute Attribute)
Helper function that may be useful to call from native as well.
Data Fields
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 AbilityLevel
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 & AbilityLevel
const FGameplayAbilitySpecHandle & AbilitySpecHandle
FActiveGameplayEffectHandle ActiveHandle
int32 AActor * Actor
FGameplayTargetDataFilterHandle ActorFilterClass
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer AggregatedSourceTags
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer & AggregatedSourceTags
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer AggregatedTargetTags
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer & AggregatedTargetTags
FGameplayAttribute Attribute
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer float BaseValue
const FGameplayAbilitySpecHandle bool & bIsInstance
BlueprintAutocast
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent bool bReplicateLocationWhenUsingMinimalRepProxy
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent bool & bReplicateLocationWhenUsingMinimalRepProxy
FHitResult bool bReset
const FGameplayTagContainer bool bShouldReplicate =false)
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer bool & bSuccess
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer float bool & bSuccess
FGameplayAttribute bool & bSuccessfullyFoundAttribute
CompactNodeTitle = "=="
FName DataName
FGameplayTag DataTag
TSubclassOf< UGameplayEffectUIData > DataType
FGameplayCueParameters FVector & Direction
float Duration
AActor AActor * EffectCauser
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor * EffectCauser
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor *& EffectCauser
float FGameplayEffectContextHandle EffectContext
float float FGameplayEffectContextHandle & EffectContext
EGameplayCueEvent::Type EventType
AActor * FilterActor
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 GameplayEffectLevel
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 & GameplayEffectLevel
AActor FGameplayEffectSpecHandle GameplayEffectSpecHandle_Clone
const FGameplayTagContainer & GameplayTags
const FGameplayAbilityTargetDataHandle & HandleToAdd
FHitResult HitResult
int32 Index
AActor AActor * InEffectCauser
AActor * InEffectCauser
AActor * InInstigator
AActor AActor float InLevel = 1.0f)
AActor * Instigator
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor * Instigator
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor *& Instigator
Keywords
AActor AActor float Level = 1.0f)
TSubclassOf< UGameplayEffect > LinkedGameplayEffect
FGameplayEffectSpecHandle LinkedGameplayEffectSpec
FGameplayCueParameters FVector & Location
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector Location
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector & Location
FName float Magnitude
FGameplayTag float Magnitude
float FGameplayEffectContextHandle FGameplayTag MatchedTagName
float float FGameplayEffectContextHandle FGameplayTag & MatchedTagName
FGameplayTag NewGameplayTag
FGameplayTagContainer NewGameplayTags
FGameplayCueParameters FVector FVector & Normal
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector Normal
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector & Normal
float & NormalizedMagnitude
bool OneTargetPerHandle
FVector Origin
float FGameplayEffectContextHandle FGameplayTag FGameplayTag OriginalTag
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag & OriginalTag
EGameplayCueEvent::Type FGameplayCueParameters Parameters
FGameplayCueParameters Parameters
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial * PhysicalMaterial
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial *& PhysicalMaterial
float RawMagnitude
float float & RawMagnitude
ScriptOperator
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject * SourceObject
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject *& SourceObject
const FGameplayTagRequirements & SourceTagReqs
FGameplayAttribute const FGameplayTagContainer & SourceTags
int32 StackCount
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent * TargetAttachComponent
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent *& TargetAttachComponent
const FGameplayAbilityTargetingLocationInfo & TargetLocation
const FGameplayTagRequirements const FGameplayTagRequirements & TargetTagReqs
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer & TargetTags
Static Protected Member Functions
static GAMEPLAYABILITIES_API void ProcessGameplayTagChangedEventWrapper (const FGameplayTag GameplayTag, int32 GameplayTagCount, FOnGameplayTagChangedEventWrapperSignature GameplayTagChangedEventWrapperDelegate)
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION()) static GAMEPLAYABILITIES_API UAbilitySystemComponent *GetAbilitySystemComponent(AActor *Actor)
Tries to find an ability system component on the actor, will use AbilitySystemInterface or fall back to a component search.
UFUNCTION () static GAMEPLAYABILITIES_API void UnbindAllGameplayTagChangedEventWrappersForHandle(FGameplayTagChangedEventWrapperSpecHandle Handle)
Unbinds the event wrapper tag change event bound via a BindEventWrapper<to gameplay tag(s)> method that is tied to the given Handle.
UFUNCTION () static GAMEPLAYABILITIES_API void UnbindGameplayTagChangedEventWrapperForHandle(FGameplayTag Tag
Unbinds the event wrapper tag change event bound via a BindEventWrapper<to gameplay tag(s)> method that is tied to the given Handle, for the specific tag.
UFUNCTION ()) static GAMEPLAYABILITIES_API FGameplayTagChangedEventWrapperSpecHandle BindEventWrapperToAnyOfGameplayTagContainerChanged(UAbilitySystemComponent *AbilitySystemComponent
Binds to changes in the given TagContainer on the given ASC's owned tags.
UFUNCTION ()) static GAMEPLAYABILITIES_API FGameplayTagChangedEventWrapperSpecHandle BindEventWrapperToAnyOfGameplayTagsChanged(UAbilitySystemComponent *AbilitySystemComponent
Binds to changes in the given Tags on the given ASC's owned tags.
UFUNCTION ()) static GAMEPLAYABILITIES_API FGameplayTagChangedEventWrapperSpecHandle BindEventWrapperToGameplayTagChanged(UAbilitySystemComponent *AbilitySystemComponent
Binds to changes in the given Tag on the given ASC's owned tags.
UFUNCTION ()) static GAMEPLAYABILITIES_API void SendGameplayEventToActor(AActor *Actor
This function can be used to trigger an ability on the actor in question with useful payload data.
UPARAM (meta=(GameplayTagFilter="GameplayEventTagsCategory")) FGameplayTag EventTag
Private Attributes
FGameplayTag FOnGameplayTagChangedEventWrapperSignature bool bExecuteImmediatelyIfTagApplied = true
const TArray< FGameplayTag > FOnGameplayTagChangedEventWrapperSignature bool bExecuteImmediatelyIfTagApplied = true
const FGameplayTagContainer FOnGameplayTagChangedEventWrapperSignature bool bExecuteImmediatelyIfTagApplied = true
FGameplayTag FOnGameplayTagChangedEventWrapperSignature GameplayTagChangedEventWrapperDelegate
const TArray< FGameplayTag > FOnGameplayTagChangedEventWrapperSignature GameplayTagChangedEventWrapperDelegate
const FGameplayTagContainer FOnGameplayTagChangedEventWrapperSignature GameplayTagChangedEventWrapperDelegate
FGameplayTagChangedEventWrapperSpecHandle Handle
FGameplayEventData Payload
FGameplayTag Tag
const FGameplayTagContainer TagContainer
FGameplayTag FOnGameplayTagChangedEventWrapperSignature bool EGameplayTagEventType::Type TagListeningPolicy = EGameplayTagEventType::NewOrRemoved)
const TArray< FGameplayTag > FOnGameplayTagChangedEventWrapperSignature bool EGameplayTagEventType::Type TagListeningPolicy = EGameplayTagEventType::NewOrRemoved)
const FGameplayTagContainer FOnGameplayTagChangedEventWrapperSignature bool EGameplayTagEventType::Type TagListeningPolicy = EGameplayTagEventType::NewOrRemoved)
const TArray< FGameplayTag > & Tags
Detailed Description
Definition at line 69 of file AbilitySystemBlueprintLibrary.h.
Member Function Documentation
Conv_ScalableFloatToDouble()
IgnoreTypePromotion GAMEPLAYABILITIES_API double UAbilitySystemBlueprintLibrary::Conv_ScalableFloatToDouble (const FScalableFloat & Input, float Level = 0.0f) static
References Conv_ScalableFloatToDouble(), Input, Level, and UE_API.
Referenced by Conv_ScalableFloatToDouble().
Conv_ScalableFloatToFloat()
IgnoreTypePromotion GAMEPLAYABILITIES_API float UAbilitySystemBlueprintLibrary::Conv_ScalableFloatToFloat (const FScalableFloat & Input, float Level = 0.0f) static
References Conv_ScalableFloatToFloat(), Input, Level, and UE_API.
Referenced by Conv_ScalableFloatToFloat().
GENERATED_UCLASS_BODY()
UAbilitySystemBlueprintLibrary::GENERATED_UCLASS_BODY () private
Tries to find an ability system component on the actor, will use AbilitySystemInterface or fall back to a component search.
References Actor, Category, Meta, UE_API, and UFUNCTION().
GetModifiedAttributeMagnitude()
GAMEPLAYABILITIES_API float UAbilitySystemBlueprintLibrary::GetModifiedAttributeMagnitude (const FGameplayEffectSpec & SpecHandle, FGameplayAttribute Attribute) static
Helper function that may be useful to call from native as well.
References Attribute, GetModifiedAttributeMagnitude(), and UE_API.
Referenced by GetModifiedAttributeMagnitude(), and UFUNCTION().
ProcessGameplayTagChangedEventWrapper()
GAMEPLAYABILITIES_API void UAbilitySystemBlueprintLibrary::ProcessGameplayTagChangedEventWrapper (const FGameplayTag GameplayTag, int32 GameplayTagCount, FOnGameplayTagChangedEventWrapperSignature GameplayTagChangedEventWrapperDelegate) static protected
References GameplayTagChangedEventWrapperDelegate, ProcessGameplayTagChangedEventWrapper(), and UE_API.
Referenced by ProcessGameplayTagChangedEventWrapper().
UE_DEPRECATED() [1/4]
UAbilitySystemBlueprintLibrary::UE_DEPRECATED (5. 3, "Linked GameplayEffects aren't replicated. The new UAdditionalGameplayEffectsComponent renders this functionality obsolete (and since it's configured in the Asset, it is properly synced).")
Adds LinkedGameplayEffect to SpecHandles.
LinkedGameplayEffectSpec will be applied when/if SpecHandle is applied successfully. This will initialize the LinkedGameplayEffect's Spec for you. Returns to NEW linked spec in case you want to add more to it.
References Category, meta, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [2/4]
UAbilitySystemBlueprintLibrary::UE_DEPRECATED (5. 3, "Linked GameplayEffects aren't replicated. The new UAdditionalGameplayEffectsComponent renders this functionality obsolete (and since it's configured in the Asset, it is properly synced).")
Adds LinkedGameplayEffectSpec to SpecHandles.
LinkedGameplayEffectSpec will be applied when/if SpecHandle is applied successfully. LinkedGameplayEffectSpec will not be modified here. Returns the ORIGINAL SpecHandle (legacy decision)
References Category, meta, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [3/4]
UAbilitySystemBlueprintLibrary::UE_DEPRECATED (5. 3, "Linked GameplayEffects aren't replicated. The new UAdditionalGameplayEffectsComponent renders this functionality obsolete (and since it's configured in the Asset, it is properly synced).")
Returns handles for all Linked GE Specs that SpecHandle may apply.
Useful if you want to append additional information to them.
References Category, meta, UE_API, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [4/4]
UAbilitySystemBlueprintLibrary::UE_DEPRECATED (5. 5, "Use MakeSpecHandleByClass. It's safer as InGameplayEffect needs to be a CDO")
Create a spec handle, filling out all fields.
References Category, meta, UE_DEPRECATED(), and UFUNCTION().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UFUNCTION() [1/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Simple equality operator for gameplay attributes.
UFUNCTION() [2/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Simple inequality operator for gameplay attributes.
References Category, CompactNodeTitle, Keywords, meta, UE_API, and UFUNCTION().
UFUNCTION() [3/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Equality operator for two Active Gameplay Effect Handles.
UFUNCTION() [4/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Inequality operator for two Active Gameplay Effect Handles.
References A, B, Category, CompactNodeTitle, meta, ScriptOperator, UE_API, and UFUNCTION().
UFUNCTION() [5/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Equality operator for two Gameplay Ability Spec Handles.
References A, B, Category, CompactNodeTitle, meta, ScriptOperator, UE_API, and UFUNCTION().
UFUNCTION() [6/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Inequality operator for two Gameplay Ability Spec Handles.
References A, B, Category, CompactNodeTitle, meta, ScriptOperator, UE_API, and UFUNCTION().
UFUNCTION() [7/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Converts the given Scalable float to the value at the given level.
Parameters
Input The scalable float to get the value from
Level The Level of which to get the value at
Returns
The single-precision float value at the given level from the scalable float
UFUNCTION() [8/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Converts the given Scalable float to the value at the given level.
Parameters
Input The scalable float to get the value from
Level The Level of which to get the value at
Returns
The double-precision float value at the given level from the scalable float
References BlueprintAutocast, Category, meta, and UFUNCTION().
UFUNCTION() [9/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Create a spec handle, filling out all fields.
References Category, meta, and UFUNCTION().
UFUNCTION() [10/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns actor stored in the Effect Context used by this cue.
References Category, Index, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [11/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the instigating actor (that holds the ability system component) of the GameplayCue.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [12/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Manually adds a set of tags to a given actor, and optionally replicates them.
References Category, and UFUNCTION().
UFUNCTION() [13/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if the aggregated source and target tags from the effect spec meets the tag requirements.
References Category, and UFUNCTION().
UFUNCTION() [14/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns true if the given TargetData has the actor passed in targeted.
References Category, and UFUNCTION().
UFUNCTION() [15/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the best normalized effect direction for this gameplay cue.
This is useful for effects that require the direction of an enemy attack. Returns true if a valid direction could be calculated.
References Category, and UFUNCTION().
UFUNCTION() [16/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the best end location and normal for this gameplay cue.
If there is hit result data, it will return this. Otherwise it will return the target actor's location/rotation. If none of this is available, it will return false.
References Category, and UFUNCTION().
UFUNCTION() [17/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Checks if the effect context has a hit reslt stored inside.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [18/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if the ability system component that spawned this cue is locally controlled.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [19/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if the ability system component that spawned this cue is locally controlled and a player.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [20/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if the attribute actually exists.
References Attribute, Category, IsValid(), UE_API, and UFUNCTION().
UFUNCTION() [21/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Manually removes a set of tags from a given actor, with optional replication.
References Actor, bShouldReplicate, Category, GameplayTags, UE_API, and UFUNCTION().
UFUNCTION() [22/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns true if the given TargetData has at least 1 actor targeted.
References Category, Index, UE_API, and UFUNCTION().
UFUNCTION() [23/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns true if the target data has an end point.
References Category, Index, UE_API, and UFUNCTION().
UFUNCTION() [24/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns true if the target data has a hit result.
References Category, HitResult, Index, UE_API, and UFUNCTION().
UFUNCTION() [25/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns true if the target data has an origin.
References Category, Index, UE_API, and UFUNCTION().
UFUNCTION() [26/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Provides the Gameplay Ability object associated with an Ability Spec Handle This can be either an instanced ability, or in the case of shared abilities, the Class Default Object.
Parameters
AbilitySpec The Gameplay Ability Spec you want to get the object from
bIsInstance Set to true if this is an instanced ability instead of a shared CDO
Returns
Pointer to the Gameplay Ability object
References Category, and UFUNCTION().
UFUNCTION() [27/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns the Gameplay Effect CDO from an active handle.
This reference should be considered read only, but you can use it to read additional Gameplay Effect info, such as icon, description, etc.
References ActiveHandle, Category, UE_API, and UFUNCTION().
UFUNCTION() [28/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Creates single actor target data.
References Actor, Category, UE_API, and UFUNCTION().
UFUNCTION() [29/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Creates actor array target data.
References Category, and UFUNCTION().
UFUNCTION() [30/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Creates a target data with a single hit result.
References Category, HitResult, UE_API, and UFUNCTION().
UFUNCTION() [31/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Creates a target data with a source and destination location.
References Category, and UFUNCTION().
UFUNCTION() [32/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Copies targets from HandleToAdd to TargetHandle.
References Category, and UFUNCTION().
UFUNCTION() [33/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Create a new target data handle with filtration performed on the data.
References Category, and UFUNCTION().
UFUNCTION() [34/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the GameplayEffectSpec's effect context handle.
References Category, UE_API, and UFUNCTION().
UFUNCTION() [35/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Adds NewGameplayTag to this instance of the effect.
References Category, NewGameplayTag, UE_API, and UFUNCTION().
UFUNCTION() [36/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Adds NewGameplayTags to this instance of the effect.
References Category, NewGameplayTags, UE_API, and UFUNCTION().
UFUNCTION() [37/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
This instance of the effect will now grant NewGameplayTag to the object that this effect is applied to.
References Category, and UFUNCTION().
UFUNCTION() [38/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
This instance of the effect will now grant NewGameplayTags to the object that this effect is applied to.
References Category, and UFUNCTION().
UFUNCTION() [39/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Sets a raw name Set By Caller magnitude value, the tag version should normally be used.
References Category, and UFUNCTION().
UFUNCTION() [40/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Create a spec handle, cloning another.
References Category, and UFUNCTION().
UFUNCTION() [41/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Manually sets the duration on a specific effect.
References Category, and UFUNCTION().
UFUNCTION() [42/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Sets the GameplayEffectSpec's StackCount to the specified amount (prior to applying)
References Category, and UFUNCTION().
UFUNCTION() [43/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Sets the GameplayEffectSpec's StackCount to the max stack count defined in the GameplayEffect definition.
References Category, UE_API, and UFUNCTION().
UFUNCTION() [44/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Create a handle for filtering target data, filling out all fields.
References Category, and UFUNCTION().
UFUNCTION() [45/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns a hit result stored in the effect context if valid.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [46/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns the hit result for a given index if it exists.
References Category, HitResult, Index, UE_API, and UFUNCTION().
UFUNCTION() [47/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns the value of Attribute from the ability system component AbilitySystem after evaluating it with source and target tags.
bSuccess indicates the success or failure of this operation.
References Category, and UFUNCTION().
UFUNCTION() [48/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns the value of Attribute from the ability system component AbilitySystem after evaluating it with source and target tags using the passed in base value instead of the real base value.
bSuccess indicates the success or failure of this operation.
References Category, and UFUNCTION().
UFUNCTION() [49/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns the expected end time (when we think the GE will expire) for a given GameplayEffect (note someone could remove or change it before that happens!)
References ActiveHandle, Category, UE_API, and UFUNCTION().
UFUNCTION() [50/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns the start time (time which the GE was added) for a given GameplayEffect.
References ActiveHandle, Category, UE_API, and UFUNCTION().
UFUNCTION() [51/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns the total duration for a given GameplayEffect.
References ActiveHandle, Category, UE_API, and UFUNCTION().
UFUNCTION() [52/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Returns the value of Attribute from the ability system component belonging to Actor.
References Category, and UFUNCTION().
UFUNCTION() [53/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Returns the base value of Attribute from the ability system component belonging to Actor.
References Actor, Attribute, bSuccessfullyFoundAttribute, Category, UE_API, and UFUNCTION().
UFUNCTION() [54/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Returns the base value of Attribute from the ability system component AbilitySystemComponent.
References Attribute, bSuccessfullyFoundAttribute, Category, UE_API, and UFUNCTION().
UFUNCTION() [55/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Returns the value of Attribute from the ability system component AbilitySystem.
References Attribute, bSuccessfullyFoundAttribute, Category, UE_API, and UFUNCTION().
UFUNCTION() [56/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the magnitude of change for an attribute on an APPLIED GameplayEffectSpec.
References Attribute, Category, GetModifiedAttributeMagnitude(), UE_API, and UFUNCTION().
UFUNCTION() [57/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns FString representation of a gameplay attribute's set class and name, in the form of AttrSetName.AttrName (or just AttrName if not part of a set).
References Attribute, Category, UE_API, and UFUNCTION().
UFUNCTION() [58/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets instigating world location.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [59/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns the end point transform for a given index if it exists.
References Category, Index, UE_API, and UFUNCTION().
UFUNCTION() [60/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns the origin for a given index if it exists.
References Category, Index, UE_API, and UFUNCTION().
UFUNCTION() [61/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets instigating world location.
References Category, FVector, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [62/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns the end point for a given index if it exists.
References Category, FVector, Index, UE_API, and UFUNCTION().
UFUNCTION() [63/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns current stack count of an active Gameplay Effect.
Will return 0 if the GameplayEffect is no longer valid.
References ActiveHandle, Category, UE_API, and UFUNCTION().
UFUNCTION() [64/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns stack limit count of an active Gameplay Effect.
Will return 0 if the GameplayEffect is no longer valid.
References ActiveHandle, Category, UE_API, and UFUNCTION().
UFUNCTION() [65/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns number of actors stored in the Effect Context used by this cue.
References Category, Parameters, UE_API, and UFUNCTION().
UFUNCTION() [66/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns number of target data objects, not necessarily number of distinct targets.
References Category, UE_API, and UFUNCTION().
UFUNCTION() [67/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns all actors targeted, for a given index.
References Category, and UFUNCTION().
UFUNCTION() [68/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns all actors targeted.
References Category, UE_API, and UFUNCTION().
UFUNCTION() [69/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Forwards the gameplay cue to another gameplay cue interface object.
References Category, and UFUNCTION().
UFUNCTION() [70/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () private
Unbinds the event wrapper tag change event bound via a BindEventWrapper<to gameplay tag(s)> method that is tied to the given Handle.
(expected to unbind 1 or none)
Parameters
Handle FGameplayTagChangedEventWrapperSpecHandle Handle provided when binding to a delegate
References Category, Handle, UE_API, and UFUNCTION().
UFUNCTION() [71/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () private
Unbinds the event wrapper tag change event bound via a BindEventWrapper<to gameplay tag(s)> method that is tied to the given Handle, for the specific tag.
and were bound to the given Tag. (expected to unbind 1 or none, only makes sense to call if the original binding was for listening to multiple tags.)
Parameters
Tag FGameplayTag to unbind from
Handle int Handle provided when binding to a delegate
References Category, and UFUNCTION().
UFUNCTION() [72/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the physical actor that caused the effect, possibly a projectile or weapon.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [73/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the instigating actor (that holds the ability system component) of the EffectContext.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [74/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the original instigator actor that started the chain of events to cause this effect.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [75/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if there is a valid hit result inside the effect context.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [76/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if the ability system component that instigated this is locally controlled.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [77/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns true if this context has ever been initialized.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [78/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Returns true if the passed-in Gameplay Ability instance is active (activated and not yet ended).
References Category, meta, UE_API, and UFUNCTION().
UFUNCTION() [79/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns all tags that the Gameplay Effect has (that denote the GE Asset itself) and does not grant to any Actor.
References Category, meta, UE_API, and UFUNCTION().
UFUNCTION() [80/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Returns all tags that the Gameplay Effect grants to the target Actor.
References Category, meta, UE_API, and UFUNCTION().
UFUNCTION() [81/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const
Returns the UI data for a gameplay effect class (if any)
References Category, Meta, and UFUNCTION().
UFUNCTION() [82/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Native make, to avoid having to deal with quantized vector types.
References AbilityLevel, Category, GameplayEffectLevel, Location, meta, Normal, and UFUNCTION().
UFUNCTION() [83/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Sets a gameplay tag Set By Caller magnitude value.
References Category, meta, and UFUNCTION().
UFUNCTION() [84/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () private
Binds to changes in the given TagContainer on the given ASC's owned tags.
Cache off the returned handle and call one of the 'Unbind'...'EventWrapper' fns and pass in the handle when you are finished with the binding.
Parameters
TagContainer FGameplayTagContainer of tags to listen for changes on
BindingObject UObject owning the Event (usually self)
GameplayTagChangedEventWrapperDelegate Tag Changed Event to trigger
bExecuteImmediatelyIfTagApplied If true, the bound event will immediately execute if we already have the tag.
TagListeningPolicy Whether we are listening for any tag change or just applied/removed.
Returns
FGameplayTagChangedEventWrapperSpecHandle Handle by which this binding request can be unbound.
References Category, meta, UE_API, and UFUNCTION().
UFUNCTION() [85/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () private
Binds to changes in the given Tags on the given ASC's owned tags.
Cache off the returned handle and call one of the 'Unbind'...'EventWrapper' fns and pass in the handle when you are finished with the binding.
Parameters
Tags TArray of FGameplayTag to listen for changes on
BindingObject UObject owning the Event (usually self)
GameplayTagChangedEventWrapperDelegate Tag Changed Event to trigger
bExecuteImmediatelyIfTagApplied If true, the bound event will immediately execute if we already have the tag.
TagListeningPolicy Whether we are listening for any tag change or just applied/removed.
Returns
FGameplayTagChangedEventWrapperSpecHandle Handle by which this binding request can be unbound.
References Category, meta, UE_API, and UFUNCTION().
UFUNCTION() [86/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () private
Binds to changes in the given Tag on the given ASC's owned tags.
Cache off the returned handle and call one of the 'Unbind'...'EventWrapper' fns and pass in the handle when you are finished with the binding.
Parameters
Tag FGameplayTag to listen for changes on
BindingObject UObject owning the Event (usually self)
GameplayTagChangedEventWrapperDelegate Tag Changed Event to trigger
bExecuteImmediatelyIfTagApplied If true, the bound event will immediately execute if we already have the tag.
TagListeningPolicy Whether we are listening for any tag change or just applied/removed.
Returns
FGameplayTagChangedEventWrapperSpecHandle Handle by which this binding request can be unbound.
References Category, meta, UE_API, and UFUNCTION().
UFUNCTION() [87/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Extracts a hit result from the effect context if it is set.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [88/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns the total duration for a given GameplayEffect, basically ExpectedEndTime - Current Time.
References Category, meta, and UFUNCTION().
UFUNCTION() [89/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Returns a debug string for display.
References ActiveHandle, Category, Meta, UE_API, and UFUNCTION().
UFUNCTION() [90/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the location the effect originated from.
References Category, EffectContext, FVector, Meta, UE_API, and UFUNCTION().
UFUNCTION() [91/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Gets the source object of the effect.
References Category, EffectContext, Meta, UE_API, and UFUNCTION().
UFUNCTION() [92/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () const &
Native break, to avoid having to deal with quantized vector types.
References Category, meta, and UFUNCTION().
UFUNCTION() [93/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Adds a hit result to the effect context.
References Category, Meta, and UFUNCTION().
UFUNCTION() [94/95]
UAbilitySystemBlueprintLibrary::UFUNCTION ()
Sets the location the effect originated from.
References Category, Meta, and UFUNCTION().
UFUNCTION() [95/95]
UAbilitySystemBlueprintLibrary::UFUNCTION () private
This function can be used to trigger an ability on the actor in question with useful payload data.
NOTE: GetAbilitySystemComponent is called on the actor to find a good component, and if the component isn't found, the event will not be sent.
References Category, Meta, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UPARAM()
UAbilitySystemBlueprintLibrary::UPARAM (meta = (GameplayTagFilter="GameplayEventTagsCategory")) private
Field Documentation
AbilityLevel [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 UAbilitySystemBlueprintLibrary::AbilityLevel
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
AbilityLevel [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32& UAbilitySystemBlueprintLibrary::AbilityLevel
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
AbilitySpecHandle
const FGameplayAbilitySpecHandle& UAbilitySystemBlueprintLibrary::AbilitySpecHandle
Definition at line 573 of file AbilitySystemBlueprintLibrary.h.
ActiveHandle
FActiveGameplayEffectHandle UAbilitySystemBlueprintLibrary::ActiveHandle
Definition at line 521 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Actor
int32 AActor* UAbilitySystemBlueprintLibrary::Actor
Definition at line 271 of file AbilitySystemBlueprintLibrary.h.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
ActorFilterClass
FGameplayTargetDataFilterHandle UAbilitySystemBlueprintLibrary::ActorFilterClass
Definition at line 242 of file AbilitySystemBlueprintLibrary.h.
AggregatedSourceTags [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer UAbilitySystemBlueprintLibrary::AggregatedSourceTags
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
AggregatedSourceTags [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer& UAbilitySystemBlueprintLibrary::AggregatedSourceTags
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
AggregatedTargetTags [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer UAbilitySystemBlueprintLibrary::AggregatedTargetTags
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
AggregatedTargetTags [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer& UAbilitySystemBlueprintLibrary::AggregatedTargetTags
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
Attribute
FGameplayAttribute UAbilitySystemBlueprintLibrary::Attribute
Definition at line 178 of file AbilitySystemBlueprintLibrary.h.
Referenced by GetModifiedAttributeMagnitude(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
BaseValue
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer float UAbilitySystemBlueprintLibrary::BaseValue
Definition at line 198 of file AbilitySystemBlueprintLibrary.h.
bExecuteImmediatelyIfTagApplied [1/3]
FGameplayTag FOnGameplayTagChangedEventWrapperSignature bool UAbilitySystemBlueprintLibrary::bExecuteImmediatelyIfTagApplied = true private
Definition at line 104 of file AbilitySystemBlueprintLibrary.h.
bExecuteImmediatelyIfTagApplied [2/3]
const TArray<FGameplayTag> FOnGameplayTagChangedEventWrapperSignature bool UAbilitySystemBlueprintLibrary::bExecuteImmediatelyIfTagApplied = true private
Definition at line 122 of file AbilitySystemBlueprintLibrary.h.
bExecuteImmediatelyIfTagApplied [3/3]
const FGameplayTagContainer FOnGameplayTagChangedEventWrapperSignature bool UAbilitySystemBlueprintLibrary::bExecuteImmediatelyIfTagApplied = true private
Definition at line 140 of file AbilitySystemBlueprintLibrary.h.
bIsInstance
const FGameplayAbilitySpecHandle bool& UAbilitySystemBlueprintLibrary::bIsInstance
Definition at line 573 of file AbilitySystemBlueprintLibrary.h.
BlueprintAutocast
UAbilitySystemBlueprintLibrary::BlueprintAutocast
Definition at line 594 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
bReplicateLocationWhenUsingMinimalRepProxy [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent bool UAbilitySystemBlueprintLibrary::bReplicateLocationWhenUsingMinimalRepProxy
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
bReplicateLocationWhenUsingMinimalRepProxy [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent bool& UAbilitySystemBlueprintLibrary::bReplicateLocationWhenUsingMinimalRepProxy
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
bReset
FHitResult bool UAbilitySystemBlueprintLibrary::bReset
Definition at line 327 of file AbilitySystemBlueprintLibrary.h.
bShouldReplicate
const FGameplayTagContainer bool UAbilitySystemBlueprintLibrary::bShouldReplicate =false)
Definition at line 478 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
bSuccess [1/2]
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer bool& UAbilitySystemBlueprintLibrary::bSuccess
Definition at line 194 of file AbilitySystemBlueprintLibrary.h.
bSuccess [2/2]
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer float bool& UAbilitySystemBlueprintLibrary::bSuccess
Definition at line 198 of file AbilitySystemBlueprintLibrary.h.
bSuccessfullyFoundAttribute
FGameplayAttribute bool & UAbilitySystemBlueprintLibrary::bSuccessfullyFoundAttribute
Definition at line 178 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
CompactNodeTitle
UAbilitySystemBlueprintLibrary::CompactNodeTitle = "=="
Definition at line 201 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
DataName
FName UAbilitySystemBlueprintLibrary::DataName
Definition at line 423 of file AbilitySystemBlueprintLibrary.h.
DataTag
FGameplayTag UAbilitySystemBlueprintLibrary::DataTag
Definition at line 427 of file AbilitySystemBlueprintLibrary.h.
DataType
TSubclassOf<UGameplayEffectUIData> UAbilitySystemBlueprintLibrary::DataType
Definition at line 529 of file AbilitySystemBlueprintLibrary.h.
Direction
FGameplayCueParameters FVector& UAbilitySystemBlueprintLibrary::Direction
Definition at line 403 of file AbilitySystemBlueprintLibrary.h.
Duration
float UAbilitySystemBlueprintLibrary::Duration
Definition at line 431 of file AbilitySystemBlueprintLibrary.h.
EffectCauser [1/3]
AActor AActor* UAbilitySystemBlueprintLibrary::EffectCauser
Definition at line 255 of file AbilitySystemBlueprintLibrary.h.
EffectCauser [2/3]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor* UAbilitySystemBlueprintLibrary::EffectCauser
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
EffectCauser [3/3]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor*& UAbilitySystemBlueprintLibrary::EffectCauser
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
EffectContext [1/2]
float FGameplayEffectContextHandle UAbilitySystemBlueprintLibrary::EffectContext
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
EffectContext [2/2]
float float FGameplayEffectContextHandle& UAbilitySystemBlueprintLibrary::EffectContext
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
EventType
EGameplayCueEvent::Type UAbilitySystemBlueprintLibrary::EventType
Definition at line 383 of file AbilitySystemBlueprintLibrary.h.
FilterActor
AActor* UAbilitySystemBlueprintLibrary::FilterActor
Definition at line 246 of file AbilitySystemBlueprintLibrary.h.
GameplayEffectLevel [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 UAbilitySystemBlueprintLibrary::GameplayEffectLevel
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
GameplayEffectLevel [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32& UAbilitySystemBlueprintLibrary::GameplayEffectLevel
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
GameplayEffectSpecHandle_Clone
AActor FGameplayEffectSpecHandle UAbilitySystemBlueprintLibrary::GameplayEffectSpecHandle_Clone
Definition at line 259 of file AbilitySystemBlueprintLibrary.h.
GameplayTagChangedEventWrapperDelegate [1/3]
FGameplayTag FOnGameplayTagChangedEventWrapperSignature UAbilitySystemBlueprintLibrary::GameplayTagChangedEventWrapperDelegate private
Definition at line 103 of file AbilitySystemBlueprintLibrary.h.
Referenced by ProcessGameplayTagChangedEventWrapper().
GameplayTagChangedEventWrapperDelegate [2/3]
const TArray<FGameplayTag> FOnGameplayTagChangedEventWrapperSignature UAbilitySystemBlueprintLibrary::GameplayTagChangedEventWrapperDelegate private
Definition at line 121 of file AbilitySystemBlueprintLibrary.h.
GameplayTagChangedEventWrapperDelegate [3/3]
const FGameplayTagContainer FOnGameplayTagChangedEventWrapperSignature UAbilitySystemBlueprintLibrary::GameplayTagChangedEventWrapperDelegate private
Definition at line 139 of file AbilitySystemBlueprintLibrary.h.
GameplayTags
const FGameplayTagContainer & UAbilitySystemBlueprintLibrary::GameplayTags
Definition at line 478 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
Handle
FGameplayTagChangedEventWrapperSpecHandle UAbilitySystemBlueprintLibrary::Handle private
Definition at line 159 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
HandleToAdd
const FGameplayAbilityTargetDataHandle& UAbilitySystemBlueprintLibrary::HandleToAdd
Definition at line 218 of file AbilitySystemBlueprintLibrary.h.
HitResult
FHitResult UAbilitySystemBlueprintLibrary::HitResult
Definition at line 327 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
Index
int32 UAbilitySystemBlueprintLibrary::Index
Definition at line 263 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
InEffectCauser [1/2]
AActor AActor* UAbilitySystemBlueprintLibrary::InEffectCauser
Definition at line 251 of file AbilitySystemBlueprintLibrary.h.
InEffectCauser [2/2]
AActor* UAbilitySystemBlueprintLibrary::InEffectCauser
Definition at line 259 of file AbilitySystemBlueprintLibrary.h.
InInstigator
AActor* UAbilitySystemBlueprintLibrary::InInstigator
Definition at line 251 of file AbilitySystemBlueprintLibrary.h.
InLevel
AActor AActor float UAbilitySystemBlueprintLibrary::InLevel = 1.0f)
Definition at line 251 of file AbilitySystemBlueprintLibrary.h.
Instigator [1/3]
AActor* UAbilitySystemBlueprintLibrary::Instigator
Definition at line 255 of file AbilitySystemBlueprintLibrary.h.
Instigator [2/3]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor* UAbilitySystemBlueprintLibrary::Instigator
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
Instigator [3/3]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor*& UAbilitySystemBlueprintLibrary::Instigator
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
Keywords
UAbilitySystemBlueprintLibrary::Keywords
Initial value:
= "== equal"), Category="Ability|Attribute")
    static GAMEPLAYABILITIES_API bool EqualEqual_GameplayAttributeGameplayAttribute(FGameplayAttribute AttributeA, FGameplayAttribute AttributeB)
Definition at line 201 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
Level
AActor AActor float UAbilitySystemBlueprintLibrary::Level = 1.0f)
Definition at line 255 of file AbilitySystemBlueprintLibrary.h.
Referenced by Conv_ScalableFloatToDouble(), and Conv_ScalableFloatToFloat().
LinkedGameplayEffect
TSubclassOf<UGameplayEffect> UAbilitySystemBlueprintLibrary::LinkedGameplayEffect
Definition at line 457 of file AbilitySystemBlueprintLibrary.h.
LinkedGameplayEffectSpec
FGameplayEffectSpecHandle UAbilitySystemBlueprintLibrary::LinkedGameplayEffectSpec
Definition at line 452 of file AbilitySystemBlueprintLibrary.h.
Location [1/3]
FGameplayCueParameters FVector& UAbilitySystemBlueprintLibrary::Location
Definition at line 399 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
Location [2/3]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector UAbilitySystemBlueprintLibrary::Location
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
Location [3/3]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector& UAbilitySystemBlueprintLibrary::Location
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
Magnitude [1/2]
FName float UAbilitySystemBlueprintLibrary::Magnitude
Definition at line 423 of file AbilitySystemBlueprintLibrary.h.
Magnitude [2/2]
FGameplayTag float UAbilitySystemBlueprintLibrary::Magnitude
Definition at line 427 of file AbilitySystemBlueprintLibrary.h.
MatchedTagName [1/2]
float FGameplayEffectContextHandle FGameplayTag UAbilitySystemBlueprintLibrary::MatchedTagName
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
MatchedTagName [2/2]
float float FGameplayEffectContextHandle FGameplayTag& UAbilitySystemBlueprintLibrary::MatchedTagName
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
NewGameplayTag
FGameplayTag UAbilitySystemBlueprintLibrary::NewGameplayTag
Definition at line 435 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
NewGameplayTags
FGameplayTagContainer UAbilitySystemBlueprintLibrary::NewGameplayTags
Definition at line 439 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
Normal [1/3]
FGameplayCueParameters FVector FVector& UAbilitySystemBlueprintLibrary::Normal
Definition at line 399 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
Normal [2/3]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector UAbilitySystemBlueprintLibrary::Normal
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
Normal [3/3]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector& UAbilitySystemBlueprintLibrary::Normal
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
NormalizedMagnitude
float& UAbilitySystemBlueprintLibrary::NormalizedMagnitude
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
OneTargetPerHandle
bool UAbilitySystemBlueprintLibrary::OneTargetPerHandle
Definition at line 238 of file AbilitySystemBlueprintLibrary.h.
Origin
FVector UAbilitySystemBlueprintLibrary::Origin
Definition at line 335 of file AbilitySystemBlueprintLibrary.h.
OriginalTag [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag UAbilitySystemBlueprintLibrary::OriginalTag
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
OriginalTag [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag& UAbilitySystemBlueprintLibrary::OriginalTag
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
Parameters [1/2]
FGameplayCueParameters UAbilitySystemBlueprintLibrary::Parameters
Definition at line 383 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Parameters [2/2]
FGameplayCueParameters UAbilitySystemBlueprintLibrary::Parameters
Definition at line 399 of file AbilitySystemBlueprintLibrary.h.
Payload
FGameplayEventData UAbilitySystemBlueprintLibrary::Payload private
Definition at line 83 of file AbilitySystemBlueprintLibrary.h.
PhysicalMaterial [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial* UAbilitySystemBlueprintLibrary::PhysicalMaterial
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
PhysicalMaterial [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial*& UAbilitySystemBlueprintLibrary::PhysicalMaterial
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
RawMagnitude [1/2]
float UAbilitySystemBlueprintLibrary::RawMagnitude
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
RawMagnitude [2/2]
float float& UAbilitySystemBlueprintLibrary::RawMagnitude
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
ScriptOperator
UAbilitySystemBlueprintLibrary::ScriptOperator
Initial value:
= "=="))
    static GAMEPLAYABILITIES_API bool EqualEqual_ActiveGameplayEffectHandle(const FActiveGameplayEffectHandle& A, const FActiveGameplayEffectHandle& B)
Definition at line 532 of file AbilitySystemBlueprintLibrary.h.
Referenced by UFUNCTION().
SourceObject [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject* UAbilitySystemBlueprintLibrary::SourceObject
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
SourceObject [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject*& UAbilitySystemBlueprintLibrary::SourceObject
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
SourceTagReqs
const FGameplayTagRequirements& UAbilitySystemBlueprintLibrary::SourceTagReqs
Definition at line 407 of file AbilitySystemBlueprintLibrary.h.
SourceTags
FGameplayAttribute const FGameplayTagContainer & UAbilitySystemBlueprintLibrary::SourceTags
Definition at line 194 of file AbilitySystemBlueprintLibrary.h.
StackCount
int32 UAbilitySystemBlueprintLibrary::StackCount
Definition at line 461 of file AbilitySystemBlueprintLibrary.h.
Tag
FGameplayTag UAbilitySystemBlueprintLibrary::Tag private
Definition at line 102 of file AbilitySystemBlueprintLibrary.h.
TagContainer
const FGameplayTagContainer UAbilitySystemBlueprintLibrary::TagContainer private
Definition at line 138 of file AbilitySystemBlueprintLibrary.h.
TagListeningPolicy [1/3]
FGameplayTag FOnGameplayTagChangedEventWrapperSignature bool EGameplayTagEventType::Type UAbilitySystemBlueprintLibrary::TagListeningPolicy = EGameplayTagEventType::NewOrRemoved) private
Definition at line 105 of file AbilitySystemBlueprintLibrary.h.
TagListeningPolicy [2/3]
const TArray<FGameplayTag> FOnGameplayTagChangedEventWrapperSignature bool EGameplayTagEventType::Type UAbilitySystemBlueprintLibrary::TagListeningPolicy = EGameplayTagEventType::NewOrRemoved) private
Definition at line 123 of file AbilitySystemBlueprintLibrary.h.
TagListeningPolicy [3/3]
const FGameplayTagContainer FOnGameplayTagChangedEventWrapperSignature bool EGameplayTagEventType::Type UAbilitySystemBlueprintLibrary::TagListeningPolicy = EGameplayTagEventType::NewOrRemoved) private
Definition at line 141 of file AbilitySystemBlueprintLibrary.h.
Tags
const TArray<FGameplayTag>& UAbilitySystemBlueprintLibrary::Tags private
Definition at line 120 of file AbilitySystemBlueprintLibrary.h.
TargetAttachComponent [1/2]
float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent* UAbilitySystemBlueprintLibrary::TargetAttachComponent
Definition at line 411 of file AbilitySystemBlueprintLibrary.h.
TargetAttachComponent [2/2]
float float FGameplayEffectContextHandle FGameplayTag FGameplayTag FGameplayTagContainer FGameplayTagContainer FVector FVector AActor AActor UObject UPhysicalMaterial int32 int32 USceneComponent*& UAbilitySystemBlueprintLibrary::TargetAttachComponent
Definition at line 415 of file AbilitySystemBlueprintLibrary.h.
TargetLocation
const FGameplayAbilityTargetingLocationInfo& UAbilitySystemBlueprintLibrary::TargetLocation
Definition at line 222 of file AbilitySystemBlueprintLibrary.h.
TargetTagReqs
const FGameplayTagRequirements const FGameplayTagRequirements& UAbilitySystemBlueprintLibrary::TargetTagReqs
Definition at line 407 of file AbilitySystemBlueprintLibrary.h.
TargetTags
FGameplayAttribute const FGameplayTagContainer const FGameplayTagContainer & UAbilitySystemBlueprintLibrary::TargetTags
Definition at line 194 of file AbilitySystemBlueprintLibrary.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/AbilitySystemBlueprintLibrary.h