Unreal Engine 5.6 C++ API: FCoreStyle Class Reference
FCoreStyle Class Reference
Core slate style.
#include "CoreStyle.h"
Public Member Functions
UE_DEPRECATED (5.6, "IsStarshipStyle is deprecated, this function will always return true. Please remove any special case handling for the legacy slate style and calls to this function.") static const expr bool IsStarshipStyle()
Static Public Member Functions
static TSharedRef< class ISlateStyle > Create (const FName &InStyleSetName="CoreStyle")
static const ISlateStyle & Get ()
static const ISlateStyle & GetCoreStyle ()
static TSharedRef< const FCompositeFont > GetDefaultFont ()
Get the default font for Slate.
static FSlateFontInfo GetDefaultFontStyle (const FName InTypefaceFontName, const float InSize, const FFontOutlineSettings &InOutlineSettings=FFontOutlineSettings())
Get a font style using the default font for Slate.
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, class UTexture2D *TextureResource, FName TextureName)
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, const ANSICHAR *Specifier, class UTexture2D *TextureResource, FName TextureName)
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, FName TextureName, const ANSICHAR *Specifier=nullptr)
static TSharedRef< const FCompositeFont > GetIconFont ()
Get the icon font for Slate (works only in Editor, otherwise the DefaultFont is returned)
static FSlateFontInfo GetRegularIconFontStyle (const float InSize, const FFontOutlineSettings &InOutlineSettings=FFontOutlineSettings())
Get a font style using the icon font for Slate (always using "Regular" typeface.
static bool IsInitialized ()
static void ResetToDefault ()
static void SetFocusBrush (FSlateBrush *NewBrush)
static void SetInactiveSelectionColor (const FLinearColor &NewColor)
static void SetPressedSelectionColor (const FLinearColor &NewColor)
static void SetSelectionColor (const FLinearColor &NewColor)
static void SetSelectorColor (const FLinearColor &NewColor)
Used to override the default selection colors.
Static Public Attributes
static const int32 RegularTextSize = 9
static const int32 SmallTextSize = 8
Static Private Member Functions
static void SetStyle (const TSharedRef< class ISlateStyle > &NewStyle)
Static Private Attributes
static TSharedPtr< class ISlateStyle > Instance
Singleton instances of this style.
Detailed Description
Core slate style.
Definition at line 14 of file CoreStyle.h.
Member Function Documentation
Create()
TSharedRef< class ISlateStyle > FCoreStyle::Create (const FName & InStyleSetName = "CoreStyle") static
Get()
const ISlateStyle & FCoreStyle::Get () inline static
Returns
the Application Style
NOTE: Until the Editor can be fully updated, calling FCoreStyle::Get() will return the AppStyle instead of the style definied in this class.
Using the AppStyle is preferred in most cases as it allows the style to be changed and restyled more easily.
In cases requiring explicit use of the CoreStyle where a Slate Widget should not take on the appearance of the rest of the application, use FCoreStyle::GetCoreStyle().
Definition at line 33 of file CoreStyle.h.
References FAppStyle::Get().
Referenced by FBaseMenuBuilder::FBaseMenuBuilder(), FMenuBarBuilder::FMenuBarBuilder(), FMenuBuilder::FMenuBuilder(), FRigVMEditorStyle::FRigVMEditorStyle(), SNumericEntryBox< NumericType >::BuildLabel(), FArguments< ItemType >::GetBorder(), and STimecodeProvider::SLATE_BEGIN_ARGS().
GetCoreStyle()
const ISlateStyle & FCoreStyle::GetCoreStyle () inline static
Returns
the singleton instance of the style created in .
Definition at line 39 of file CoreStyle.h.
References Instance.
GetDefaultFont()
TSharedRef< const FCompositeFont > FCoreStyle::GetDefaultFont () static
Get the default font for Slate.
GetDefaultFontStyle()
FSlateFontInfo FCoreStyle::GetDefaultFontStyle (const FName InTypefaceFontName, const float InSize, const FFontOutlineSettings & InOutlineSettings = FFontOutlineSettings()) static
Get a font style using the default font for Slate.
GetDynamicImageBrush() [1/3]
const TSharedPtr< FSlateDynamicImageBrush > FCoreStyle::GetDynamicImageBrush (FName BrushTemplate, class UTexture2D * TextureResource, FName TextureName) static
GetDynamicImageBrush() [2/3]
const TSharedPtr< FSlateDynamicImageBrush > FCoreStyle::GetDynamicImageBrush (FName BrushTemplate, const ANSICHAR * Specifier, class UTexture2D * TextureResource, FName TextureName) static
GetDynamicImageBrush() [3/3]
const TSharedPtr< FSlateDynamicImageBrush > FCoreStyle::GetDynamicImageBrush (FName BrushTemplate, FName TextureName, const ANSICHAR * Specifier = nullptr) static
GetIconFont()
TSharedRef< const FCompositeFont > FCoreStyle::GetIconFont () static
Get the icon font for Slate (works only in Editor, otherwise the DefaultFont is returned)
GetRegularIconFontStyle()
FSlateFontInfo FCoreStyle::GetRegularIconFontStyle (const float InSize, const FFontOutlineSettings & InOutlineSettings = FFontOutlineSettings()) static
Get a font style using the icon font for Slate (always using "Regular" typeface.
IsInitialized()
bool FCoreStyle::IsInitialized () inline static
Definition at line 76 of file CoreStyle.h.
References Instance.
ResetToDefault()
void FCoreStyle::ResetToDefault () static
SetFocusBrush()
void FCoreStyle::SetFocusBrush (FSlateBrush * NewBrush) static
SetInactiveSelectionColor()
void FCoreStyle::SetInactiveSelectionColor (const FLinearColor & NewColor) static
SetPressedSelectionColor()
void FCoreStyle::SetPressedSelectionColor (const FLinearColor & NewColor) static
SetSelectionColor()
void FCoreStyle::SetSelectionColor (const FLinearColor & NewColor) static
SetSelectorColor()
void FCoreStyle::SetSelectorColor (const FLinearColor & NewColor) static
Used to override the default selection colors.
SetStyle()
void FCoreStyle::SetStyle (const TSharedRef< class ISlateStyle > & NewStyle) static private
UE_DEPRECATED()
FCoreStyle::UE_DEPRECATED (5. 6, "IsStarshipStyle is deprecated, this function will always return true. Please remove any special case handling for the legacy slate style and calls to this function.") const inline
Definition at line 73 of file CoreStyle.h.
Field Documentation
Instance
TSharedPtr< class ISlateStyle > FCoreStyle::Instance static private
Singleton instances of this style.
Definition at line 85 of file CoreStyle.h.
Referenced by GetCoreStyle(), and IsInitialized().
RegularTextSize
const int32 FCoreStyle::RegularTextSize = 9 static
Definition at line 70 of file CoreStyle.h.
SmallTextSize
const int32 FCoreStyle::SmallTextSize = 8 static
Definition at line 71 of file CoreStyle.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Styling/CoreStyle.h