Unreal Engine 5.6 C++ API: FMediaIOAudioCapture Class Reference
FMediaIOAudioCapture Class Reference
Handles capturing audio samples rendered by the engine and dispatching them to outputs.
#include "MediaIOCoreAudioOutput.h"
Public Member Functions
FMediaIOAudioCapture ()=default
virtual ~FMediaIOAudioCapture () override
TSharedPtr< FMediaIOAudioOutput > CreateAudioOutput (int32 InNumOutputChannels, FFrameRate InTargetFrameRate, uint32 InMaxSampleLatency, uint32 InOutputSampleRate)
Create an audio output that will receive audio samples.
DECLARE_DELEGATE_TwoParams (FOnAudioCaptured, float *, int32)
virtual const FString & GetListenerName () const override
int32 GetNumInputChannels () const
Returns the number of channels from the audio mixer device (engine side).
void Initialize (const FAudioDeviceHandle &InAudioDeviceHandle, const FOnAudioCaptured &InAudioCapturedDelegate)
Initializes audio capture for the given audio device The audio capture delegate can't be changed post Initialize.
virtual void OnNewSubmixBuffer (const USoundSubmix *InOwningSubmix, float *InAudioData, int32 InNumSamples, int32 InNumChannels, const int32 InSampleRate, double InAudioClock) override
Called when a new buffer has been rendered for a given submix.
UE_DEPRECATED (5.6, "This function is not thread safe. AudioCapturedDelegate must be passed as parameter to Initialize instead.") FOnAudioCaptured &OnAudioCaptured_RenderThread()
UE_DEPRECATED (5.6, "Use the version that takes in the AudioCapturedDelegate.") void Initialize(const FAudioDeviceHandle &InAudioDeviceHandle)
Public Member Functions inherited from ISubmixBufferListener
virtual ~ISubmixBufferListener ()=default
virtual bool IsRenderingAudio () const
Called if the submix is evaluating disabling itself for the next buffer of audio in FMixerSubmix::IsRenderingAudio() if this returns true, FMixerSubmix::IsRenderingAudio() will return true.
Public Member Functions inherited from TSharedFromThis< ISubmixBufferListener, ESPMode::ThreadSafe >
TSharedRef< ISubmixBufferListener, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< ISubmixBufferListener, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
void RegisterAudioDevice (const FAudioDeviceHandle &InAudioDeviceHandle)
void RegisterBufferListener (FAudioDevice *AudioDevice)
void SetAudioCapturedDelegate (const FOnAudioCaptured &InAudioCapturedDelegate)
This must be called in Initialize only, and before calling RegisterBufferListener.
void UnregisterAudioDevice ()
void UnregisterBufferListener (FAudioDevice *AudioDevice)
Protected Member Functions inherited from TSharedFromThis< ISubmixBufferListener, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
FOnAudioCaptured AudioCapturedDelegate
Callback for a audio rendered event.
Audio::FPatchSplitter AudioSplitter
Utility that allows pushing audio samples to multiple outputs.
int32 NumChannels = 0
Number of channels on the engine side.
FName PrimarySubmixName
Used to make sure we only accumulate audio from the primary submix.
Audio::FDeviceId RegisteredDeviceId = INDEX_NONE
Audio device Id this buffer listener is registered to.
uint32 SampleRate = 0
Sample rate on the engine side.
TSharedPtr< ISubmixBufferListener > SubmixBufferListenerProxy
We need to proxy the submit buffer listener to be able to unregister it in the destructor.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< ISubmixBufferListener, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Handles capturing audio samples rendered by the engine and dispatching them to outputs.
Definition at line 178 of file MediaIOCoreAudioOutput.h.
Constructor & Destructor Documentation
FMediaIOAudioCapture()
FMediaIOAudioCapture::FMediaIOAudioCapture () default
~FMediaIOAudioCapture()
virtual FMediaIOAudioCapture::~FMediaIOAudioCapture () override virtual
Member Function Documentation
CreateAudioOutput()
TSharedPtr< FMediaIOAudioOutput > FMediaIOAudioCapture::CreateAudioOutput (int32 InNumOutputChannels, FFrameRate InTargetFrameRate, uint32 InMaxSampleLatency, uint32 InOutputSampleRate)
Create an audio output that will receive audio samples.
References CreateAudioOutput().
Referenced by CreateAudioOutput().
DECLARE_DELEGATE_TwoParams()
FMediaIOAudioCapture::DECLARE_DELEGATE_TwoParams (FOnAudioCaptured , float * , int32)
GetListenerName()
virtual const FString & FMediaIOAudioCapture::GetListenerName () const override virtual
Reimplemented from ISubmixBufferListener.
GetNumInputChannels()
int32 FMediaIOAudioCapture::GetNumInputChannels () const inline
Returns the number of channels from the audio mixer device (engine side).
Definition at line 211 of file MediaIOCoreAudioOutput.h.
References NumChannels.
Initialize()
void FMediaIOAudioCapture::Initialize (const FAudioDeviceHandle & InAudioDeviceHandle, const FOnAudioCaptured & InAudioCapturedDelegate)
Initializes audio capture for the given audio device The audio capture delegate can't be changed post Initialize.
References Initialize().
Referenced by Initialize(), and UE_DEPRECATED().
OnNewSubmixBuffer()
virtual void FMediaIOAudioCapture::OnNewSubmixBuffer (const USoundSubmix * OwningSubmix, float * AudioData, int32 NumSamples, int32 NumChannels, const int32 SampleRate, double AudioClock) override virtual
Called when a new buffer has been rendered for a given submix.
Parameters
OwningSubmix The submix object which has rendered a new buffer
AudioData Ptr to the audio buffer
NumSamples The number of audio samples in the audio buffer
NumChannels The number of channels of audio in the buffer (e.g. 2 for stereo, 6 for 5.1, etc)
SampleRate The sample rate of the audio buffer
AudioClock Double audio clock value, from start of audio rendering.
Implements ISubmixBufferListener.
RegisterAudioDevice()
void FMediaIOAudioCapture::RegisterAudioDevice (const FAudioDeviceHandle & InAudioDeviceHandle) protected
RegisterBufferListener()
void FMediaIOAudioCapture::RegisterBufferListener (FAudioDevice * AudioDevice) protected
SetAudioCapturedDelegate()
void FMediaIOAudioCapture::SetAudioCapturedDelegate (const FOnAudioCaptured & InAudioCapturedDelegate) protected
This must be called in Initialize only, and before calling RegisterBufferListener.
UE_DEPRECATED() [1/2]
FMediaIOAudioCapture::UE_DEPRECATED (5. 6, "This function is not thread safe. AudioCapturedDelegate must be passed as parameter to Initialize instead.") & inline
Definition at line 204 of file MediaIOCoreAudioOutput.h.
References AudioCapturedDelegate, and UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FMediaIOAudioCapture::UE_DEPRECATED (5. 6, "Use the version that takes in the AudioCapturedDelegate.") const &
References Initialize().
Referenced by UE_DEPRECATED().
UnregisterAudioDevice()
void FMediaIOAudioCapture::UnregisterAudioDevice () protected
UnregisterBufferListener()
void FMediaIOAudioCapture::UnregisterBufferListener (FAudioDevice * AudioDevice) protected
Field Documentation
AudioCapturedDelegate
FOnAudioCaptured FMediaIOAudioCapture::AudioCapturedDelegate private
Callback for a audio rendered event.
Definition at line 249 of file MediaIOCoreAudioOutput.h.
Referenced by UE_DEPRECATED().
AudioSplitter
Audio::FPatchSplitter FMediaIOAudioCapture::AudioSplitter private
Utility that allows pushing audio samples to multiple outputs.
Definition at line 246 of file MediaIOCoreAudioOutput.h.
NumChannels
int32 FMediaIOAudioCapture::NumChannels = 0 private
Number of channels on the engine side.
Definition at line 243 of file MediaIOCoreAudioOutput.h.
Referenced by GetNumInputChannels().
PrimarySubmixName
FName FMediaIOAudioCapture::PrimarySubmixName private
Used to make sure we only accumulate audio from the primary submix.
Definition at line 240 of file MediaIOCoreAudioOutput.h.
RegisteredDeviceId
Audio::FDeviceId FMediaIOAudioCapture::RegisteredDeviceId = INDEX_NONE private
Audio device Id this buffer listener is registered to.
Definition at line 228 of file MediaIOCoreAudioOutput.h.
SampleRate
uint32 FMediaIOAudioCapture::SampleRate = 0 private
Sample rate on the engine side.
Definition at line 231 of file MediaIOCoreAudioOutput.h.
SubmixBufferListenerProxy
TSharedPtr<ISubmixBufferListener> FMediaIOAudioCapture::SubmixBufferListenerProxy private
We need to proxy the submit buffer listener to be able to unregister it in the destructor.
Definition at line 237 of file MediaIOCoreAudioOutput.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaIOFramework/Source/MediaIOCore/Public/MediaIOCoreAudioOutput.h