Unreal Engine 5.6 C++ API: TValueOrError< ValueType, void > Class Template Reference
TValueOrError< ValueType, void > Class Template Reference
#include "ValueOrError.h"
Public Member Functions
TValueOrError (TValueOrError_ErrorProxy<> &&Proxy)
Construct the error from a proxy from MakeError.
template<typename... ArgTypes>
TValueOrError (TValueOrError_ValueProxy< ArgTypes... > &&Proxy)
Construct the value from a proxy from MakeValue.
void & GetError () &
Access the error.
ValueType & GetValue () &
Access the value.
ValueType GetValue () &&
const ValueType & GetValue () const &
bool HasError () const
Whether the error is set.
bool HasValue () const
Whether the value is set.
bool IsValid () const
Check whether a value is set.
void StealError ()
Steal the error.
ValueType StealValue ()
Steal the value.
void * TryGetError ()
Access the error if it is set.
ValueType * TryGetValue ()
Access the value if it is set.
const ValueType * TryGetValue () const
Private Member Functions
template<typename... ArgTypes, uint32... ArgIndices>
TValueOrError (TValueOrError_ValueProxy< ArgTypes... > &&Proxy, TIntegerSequence< uint32, ArgIndices... >)
Private Attributes
TOptional< ValueType > Value
TVariant< ValueType, FWrapErrorType, FEmptyType > Variant
Detailed Description
template<typename ValueType>
class TValueOrError< ValueType, void >
Definition at line 152 of file ValueOrError.h.
Constructor & Destructor Documentation
TValueOrError() [1/3]
template<typename ValueType> template<typename... ArgTypes, uint32... ArgIndices> TValueOrError< ValueType, void >::TValueOrError (TValueOrError_ValueProxy< ArgTypes... > && Proxy, TIntegerSequence< uint32, ArgIndices... >) inline private
Definition at line 155 of file ValueOrError.h.
References InPlace, MoveTemp(), and Value.
Referenced by TValueOrError().
TValueOrError() [2/3]
template<typename ValueType> template<typename... ArgTypes> TValueOrError< ValueType, void >::TValueOrError (TValueOrError_ValueProxy< ArgTypes... > && Proxy) inline
Construct the value from a proxy from MakeValue.
Definition at line 163 of file ValueOrError.h.
References TValueOrError(), and MoveTemp().
TValueOrError() [3/3]
template<typename ValueType> TValueOrError< ValueType, void >::TValueOrError (TValueOrError_ErrorProxy<> && Proxy) inline
Construct the error from a proxy from MakeError.
Definition at line 169 of file ValueOrError.h.
Member Function Documentation
GetError()
void & TValueOrError< ValueType, void >::GetError () & inline
Access the error.
Asserts if this does not have an error.
Definition at line 97 of file ValueOrError.h.
GetValue() [1/3]
template<typename ValueType> ValueType & TValueOrError< ValueType, void >::GetValue () & inline
Access the value.
Asserts if this does not have a value.
Definition at line 180 of file ValueOrError.h.
References Value.
GetValue() [2/3]
template<typename ValueType> ValueType TValueOrError< ValueType, void >::GetValue () && inline
Definition at line 182 of file ValueOrError.h.
References MoveTemp(), and Value.
GetValue() [3/3]
template<typename ValueType> const ValueType & TValueOrError< ValueType, void >::GetValue () const & inline
Definition at line 181 of file ValueOrError.h.
References Value.
HasError()
template<typename ValueType> bool TValueOrError< ValueType, void >::HasError () const inline
Whether the error is set.
An error does imply no value.
Definition at line 174 of file ValueOrError.h.
References Value.
HasValue()
template<typename ValueType> bool TValueOrError< ValueType, void >::HasValue () const inline
Whether the value is set.
A value does imply no error.
Definition at line 177 of file ValueOrError.h.
References Value.
IsValid()
bool TValueOrError< ValueType, void >::IsValid () const inline
Check whether a value is set.
Prefer HasValue and HasError to this. !IsValid() does not imply HasError().
Definition at line 91 of file ValueOrError.h.
StealError()
void TValueOrError< ValueType, void >::StealError () inline
Steal the error.
Asserts if this does not have an error. This causes the error to be unset.
Definition at line 120 of file ValueOrError.h.
StealValue()
template<typename ValueType> ValueType TValueOrError< ValueType, void >::StealValue () inline
Steal the value.
Asserts if this does not have a value. This causes the value to be unset.
Definition at line 189 of file ValueOrError.h.
References TValueOrError< ValueType, ErrorType >::GetValue(), MoveTemp(), and Value.
TryGetError()
void * TValueOrError< ValueType, void >::TryGetError () inline
Access the error if it is set.
Definition at line 102 of file ValueOrError.h.
TryGetValue() [1/2]
template<typename ValueType> ValueType * TValueOrError< ValueType, void >::TryGetValue () inline
Access the value if it is set.
Definition at line 185 of file ValueOrError.h.
References Value.
TryGetValue() [2/2]
template<typename ValueType> const ValueType * TValueOrError< ValueType, void >::TryGetValue () const inline
Definition at line 186 of file ValueOrError.h.
References Value.
Field Documentation
Value
template<typename ValueType> TOptional<ValueType> TValueOrError< ValueType, void >::Value private
Definition at line 197 of file ValueOrError.h.
Referenced by TValueOrError(), GetValue(), GetValue(), GetValue(), HasError(), HasValue(), StealValue(), TryGetValue(), and TryGetValue().
Variant
TVariant<ValueType, FWrapErrorType, FEmptyType> TValueOrError< ValueType, void >::Variant private
Definition at line 148 of file ValueOrError.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/ValueOrError.h