Unreal Engine 5.6 C++ API: USoundSourceBus Class Reference
USoundSourceBus Class Reference
#include "SoundSourceBus.h"
Protected Member Functions
void Init ()
virtual void SerializeCuePoints (FArchive &Ar, const bool bIsLoadingFromCookedArchive)
Protected Member Functions inherited from USoundWave
UPROPERTY () int32 SampleRate
Cooked sample rate of the asset.
UPROPERTY () TObjectPtr< class UCurveTable > Curves
Curves associated with this sound wave.
UPROPERTY () TObjectPtr< class UCurveTable > InternalCurves
Hold a reference to our internal curve so we can switch back to it if we want to.
Private Member Functions
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
virtual bool CanVisualizeAsset () const override
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform) override
virtual float GetDuration () const override
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
virtual bool IsPlayable () const override
virtual bool IsSeekable () const override
Queries if Seeking is supported by the Decoder for this Wave.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual UPROPERTY()) uint32 bAutoDeactivateWhenSilent void PostLoad () override
Stop the source bus when the volume goes to zero.
virtual void Serialize (FArchive &InArchive) override
virtual void SerializeCookedPlatformData (FArchive &Ar) override
Serializes cooked platform data.
UPROPERTY () TObjectPtr< UAudioBus > AudioBus
Audio bus to use as audio for this source bus.
GENERATED_UCLASS_BODY() public UPROPERTY ()) float SourceBusDuration
How many channels to use for the source bus if the audio bus is not specified, otherwise it will use the audio bus object's channel count.
Additional Inherited Members
Public Types inherited from USoundWave
typedef FAsyncTask< class FAsyncAudioDecompressWorker > FAsyncAudioDecompress
Async worker that decompresses the audio data on a different thread.
using FSoundWaveClientPtr = ISoundWaveClient*
Public Member Functions inherited from USoundWave
void AddPlayingSource ()
void AddPlayingSource (const FSoundWaveClientPtr &Source)
virtual void BeginDestroy () override
virtual void BeginGetCompressedData (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides, const ITargetPlatform *InTargetPlatform)
virtual bool CanEditChange (const FProperty *InProperty) const override
void CleanupCachedRunningPlatformData ()
bool CleanupDecompressor (bool bForceCleanup=false)
Will clean up the decompressor task if the task has finished or force it finish.
TArray< uint8 > CreateNewCueData (const char ChunkName[4])
virtual TSharedPtr< Audio::IProxyData > CreateProxyData (const Audio::FProxyDataInitParams &InitParams) override
FSoundWaveProxyPtr CreateSoundWaveProxy ()
virtual void FinishDestroy () override
void FreeResources (bool bStopSoundsUsingThisResource=true)
Frees up all the resources allocated in this class.
virtual int32 GeneratePCMData (uint8 *PCMData, const int32 SamplesNeeded)
This is only used for DTYPE_Procedural audio.
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override
bool GetChunkData (int32 ChunkIndex, uint8 **OutChunkData, bool bMakeSureChunkIsLoaded=false)
Get Chunk data for a specified chunk index.
void GetChunkSizeStats (uint32 &OutTotalBytesOfAudioData, uint32 &OutMaxChunkBytesOfAudioData) const
virtual FByteBulkData * GetCompressedData (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides=GetPlatformCompressionOverridesForCurrentPlatform(), const ITargetPlatform *InTargetPlatform=GetRunningPlatform())
Gets the compressed data from derived data cache for the specified platform Warning, the returned pointer isn't valid after we add new formats.
SIZE_T GetCompressedDataSize (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides=GetPlatformCompressionOverridesForCurrentPlatform())
Gets the compressed data size from derived data cache for the specified format.
int32 GetCompressionQuality () const
virtual class UCurveTable * GetCurveData () const override
Returns curves associated with this sound wave.
virtual FString GetDesc () override
virtual FName GetExporterName () override
virtual Audio::EAudioMixerStreamDataFormat::Type GetGeneratedPCMDataFormat () const
Return the format of the generated PCM data type.
void GetHandleForChunkOfAudio (TFunction< void(FAudioChunkHandle &&)> OnLoadCompleted, bool bForceSync=false, int32 ChunkIndex=1, ENamedThreads::Type CallbackThread=ENamedThreads::GameThread)
If stream caching is enabled, allows the user to retain a strong handle to the first chunk of audio in the cache.
uint32 GetImportedSampleRate () const
bool GetImportedSoundWaveData (TArray< uint8 > &OutRawPCMData, uint32 &OutSampleRate, TArray< EAudioSpeakers > &OutChannelOrder) const
Utility which returns imported PCM data and the parsed header for the file.
bool GetImportedSoundWaveData (TArray< uint8 > &OutRawPCMData, uint32 &OutSampleRate, uint16 &OutNumChannels) const
Utility which returns imported PCM data and the parsed header for the file.
class UCurveTable * GetInternalCurveData () const
These functions are required for support for some custom details/editor functionality.
bool GetInterpolatedCookedEnvelopeDataForTime (float InTime, uint32 &InOutLastIndex, float &OutAmplitude, bool bLoop)
bool GetInterpolatedCookedFFTDataForTime (float InTime, uint32 &InOutLastIndex, TArray< FSoundWaveSpectralData > &OutData, bool bLoop)
Helper function to get interpolated cooked FFT data for a given time value.
ESoundWaveLoadingBehavior GetLoadingBehavior (bool bCheckSoundClasses=true) const
Returns the loading behavior we should use for this sound wave.
uint32 GetNumChunks () const
uint32 GetNumFrames () const
Return the number of frames.
ESoundWavePrecacheState GetPrecacheState () const
const uint8 * GetResourceData () const
Memory containing the data copied from the compressed bulk data.
int32 GetResourceSize () const
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
virtual int32 GetResourceSizeForFormat (FName Format)
FName GetRuntimeFormat () const
Returns the Runtime format of the wave.
float GetSampleRateForCompressionOverrides (const FPlatformAudioCookOverrides *CompressionOverrides) const
float GetSampleRateForCurrentPlatform () const
uint32 GetSizeOfChunk (uint32 ChunkIndex) const
ESoundAssetCompressionType GetSoundAssetCompressionTypeEnum () const
will return the raw value, (i.e.
TArray< FSoundWaveCuePoint > GetSoundWaveCuePoints () const
virtual bool GetSoundWavesWithCookedAnalysisData (TArray< USoundWave * > &OutSoundWaves) override
virtual float GetSubtitlePriority () const override
const FWaveTransformUObjectConfiguration & GetTransformationChainConfig () const
FWaveformTransformationInfo GetWaveformTransformationInfo () const
TArrayView< const uint8 > GetZerothChunk (bool bForImmediatePlayback=false)
This returns the initial chunk of compressed data for streaming data sources.
FWaveInstance & HandleStart (FActiveSound &ActiveSound, const UPTRINT WaveInstanceHash) const
Handle any special requirements when the sound starts (e.g.
virtual bool HasCompressedData (FName Format, ITargetPlatform *TargetPlatform=GetRunningPlatform()) const
virtual bool HasCookedAmplitudeEnvelopeData () const override
virtual bool HasCookedFFTData () const override
bool HasError () const
bool HasInternalCurves () const
Returns whether this sound wave has internal curves.
bool HasStreamingChunks ()
virtual void InitAudioResource (FByteBulkData &CompressedData)
Copy the compressed audio data from the bulk data.
virtual bool InitAudioResource (FName Format)
Copy the compressed audio data from derived data cache.
void InvalidateCompressedData (bool bFreeResources=false, bool bRebuildStreamingChunks=true)
Change the guid and flush all compressed data.
void InvalidateSoundWaveIfNeccessary ()
This function can be called before playing or using a SoundWave to check if any cook settings have been modified since this SoundWave was last cooked.
bool IsAsyncWorkComplete () const
IInterface_AsyncCompilation end.
virtual bool IsCompiling () const override
IInterface_AsyncCompilation begin.
bool IsCompressedDataReady (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides) const
Returns if an async task for a certain platform has finished.
bool IsGeneratingAudio () const
bool IsLoadedFromCookedData () const
virtual bool IsProcedurallyGenerated () const override
virtual bool IsReadyForFinishDestroy () override
bool IsRetainingAudio ()
bool IsStreaming (const FPlatformAudioCookOverrides &Overrides) const
bool IsStreaming (const TCHAR *PlatformName=nullptr) const
Checks whether sound has been categorized as streaming.
bool LoadZerothChunk ()
void LogBakedData ()
virtual void OnBeginGenerate ()
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &CookContext) override
virtual void OnEndGenerate ()
virtual void OnEndGenerate (ISoundGeneratorPtr Generator)
void OverrideLoadingBehavior (ESoundWaveLoadingBehavior InLoadingBehavior)
If Stream Caching is enabled, this can be used to override the default loading behavior of this USoundWave.
void OverwriteSoundWaveDataWithTransformationData ()
virtual void Parse (class FAudioDevice *AudioDevice, const UPTRINT NodeWaveInstanceHash, FActiveSound &ActiveSound, const FSoundParseParameters &ParseParams, TArray< FWaveInstance * > &WaveInstances) override
void PostImport ()
virtual void PostInitProperties () override
virtual void PreSave (FObjectPreSaveContext SaveContext) override
void ReleaseCompressedAudio ()
If stream caching is enabled and au.streamcache.KeepFirstChunkInMemory is 1, this will release this USoundWave's first chunk, allowing it to be deleted.
void RemoveAudioResource ()
Remove the compressed audio data associated with the passed in wave.
void RemovePlayingSource ()
void RemovePlayingSource (const FSoundWaveClientPtr &Source)
void ResetError ()
void RetainCompressedAudio (bool bForceSync=false)
If stream caching is enabled, set this sound wave to retain a strong handle to its first chunk.
void SetAllCuePoints (TArray< FSoundWaveCuePoint > InCuePoints) const
void SetCurveData (UCurveTable *InCurves)
Sets the curve data for this sound wave.
void SetError (const TCHAR *InErrorMsg=nullptr)
void SetImportedSampleRate (uint32 InImportedSampleRate)
void SetInternalCurveData (UCurveTable *InCurves)
Sets the internal curve data for this sound wave.
void SetNumFrames (uint32 InNumFrames)
Overwrite number of frames.
void SetPrecacheState (ESoundWavePrecacheState InState)
void SetSampleRate (uint32 InSampleRate, const bool bFromDecoders=false)
Overwrite sample rate.
void SetSoundWaveCuePoints (const TArray< FSoundWaveCuePoint > &InCuePoints)
bool ShouldUseStreamCaching () const
Checks whether we should use the load on demand cache.
virtual bool SupportsSubtitles () const override
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const override
UFUNCTION () 1 ESoundAssetCompressionType GetSoundAssetCompressionType() const
Returns the sound's asset compression type.
UFUNCTION () 1 TArray< FSoundWaveCuePoint > GetCuePoints() const
Filters for the cue points that are not loop regions and returns those as a new array.
UFUNCTION () 1 TArray< FSoundWaveCuePoint > GetLoopRegions() const
Filters for the cue points that are loop regions and returns those as a new array.
UFUNCTION () 1 void SetSoundAssetCompressionType(ESoundAssetCompressionType InSoundAssetCompressionType
Procedurally set the compression type.
void UpdatePlatformData ()
Attempts to update the cached platform data after any changes that might affect it.
const FWaveTransformUObjectConfiguration & UpdateTransformations ()
UPROPERTY ()
Playback volume of sound 0 to 1 - Default is 1.0.
UPROPERTY ()
Playback pitch for sound.
UPROPERTY () ESoundwaveSampleRateSettings SampleRateQuality
Determines the max sample rate to use if the platform enables "Resampling For Device" in project settings.
UPROPERTY () float SubtitlePriority
The priority of the subtitle.
UPROPERTY () FSoundModulationDefaultRoutingSettings ModulationSettings
Modulation Settings.
UPROPERTY () int32 NumChannels
Number of channels of multichannel data; 1 or 2 for regular mono and stereo files.
UPROPERTY () TArray< FSoundWaveEnvelopeTimeData > CookedEnvelopeTimeData
The cooked cooked envelope data.
UPROPERTY () TArray< FSoundWaveSpectralTimeData > CookedSpectralTimeData
The cooked spectral time data.
UPROPERTY () TArray< struct FSubtitleCue > Subtitles
Subtitle cues.
UPROPERTY ()) FString SpokenText_DEPRECATED
A localized version of the text that is actually spoken phonetically in the audio.
UPROPERTY ()) int32 StreamingPriority
Platform agnostic compression quality.
UPROPERTY ()) mutable ESoundWaveLoadingBehavior LoadingBehavior
Specifies how and when compressed audio data is loaded for asset if stream caching is enabled.
UPROPERTY ()) TArray< float > FrequenciesToAnalyze
The frequencies (in hz) to analyze when doing baked FFT analysis.
UPROPERTY ()) TEnumAsByte< ESoundGroup > SoundGroup
Static Public Member Functions inherited from USoundWave
static FName GetCurvePropertyName ()
Gets the member name for the Curves property of the USoundWave object.
static ESoundWaveLoadingBehavior GetDefaultLoadingBehavior ()
static const TCHAR * GetDefaultLoadingBehaviorCVarName ()
Used to ensure that we recook USoundWaves if the default loading behavior has changed.
static const FPlatformAudioCookOverrides * GetPlatformCompressionOverridesForCurrentPlatform ()
Return the platform compression overrides set for the current platform.
static FName GetPlatformSpecificFormat (FName Format, const FPlatformAudioCookOverrides *CompressionOverrides)
static ITargetPlatform * GetRunningPlatform ()
helper function for getting the cached name of the current platform.
Data Fields inherited from USoundWave
FAsyncAudioDecompress * AudioDecompressor
uint8 bCanProcessAsync: 1
Set to true for procedural waves that can be processed asynchronously.
UPROPERTY() uint8 bMature UPROPERTY() uint8 bManualWordWrap UPROPERTY() uint8 bSingleLine UPROPERTY() uint8 bIsAmbisonics uint8 bDecompressedFromOgg: 1
If set to true if this sound is considered to contain mature/adult content.
uint8 bDynamicResource: 1
Whether to free the resource data after it has been uploaded to the hardware.
uint8 bIsSourceBus: 1
Set to true of this is a bus sound source.
bool bMarkDirty = true)
uint8 bProcedural: 1
Set to true for programmatically generated audio.
uint8 bRequiresStopFade:1
Set to true if fade is required when sound is abruptly stopped.
uint8 * CachedRealtimeFirstBuffer
Pointer to 16 bit PCM data - used to avoid synchronous operation to obtain first block of the realtime decompressed buffer.
FGuid CompressedDataGuid
GUID used to uniquely identify this node so it can be found in the DDC.
TSortedMap< FString, FStreamedAudioPlatformData * > CookedPlatformData
cooked streaming platform data for this sound
std::atomic< int32 > CurrentChunkRevision = 0
The current revision of our compressed audio data.
TEnumAsByte< EDecompressionType > DecompressionType
Type of buffer this wave uses.
int32 NumPrecacheFrames
The number of frames which have been precached for this sound wave.
FThreadSafeCounter NumSourcesPlaying
the number of sounds currently playing this sound wave.
EditAnywhere float Pitch
uint8 * RawPCMData
Pointer to 16 bit PCM data - used to decompress data to and preview sounds.
int32 RawPCMDataSize
Size of RawPCMData, or what RawPCMData would be if the sound was fully decompressed.
int32 ResourceID
Resource index to cross reference with buffers.
int32 TrackedMemoryUsage
Cache the total used memory recorded for this SoundWave to keep INC/DEC consistent.
EditAnywhere float Volume
Detailed Description
Definition at line 26 of file SoundSourceBus.h.
Member Function Documentation
BeginCacheForCookedPlatformData()
virtual void USoundSourceBus::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform) inline override private virtual
Definition at line 59 of file SoundSourceBus.h.
CanVisualizeAsset()
virtual bool USoundSourceBus::CanVisualizeAsset () const inline override private virtual
Definition at line 51 of file SoundSourceBus.h.
ClearCachedCookedPlatformData()
virtual void USoundSourceBus::ClearCachedCookedPlatformData (const ITargetPlatform * TargetPlatform) inline override private virtual
Definition at line 61 of file SoundSourceBus.h.
GetDuration()
virtual float USoundSourceBus::GetDuration () const override private virtual
Reimplemented from USoundWave.
Init()
void USoundSourceBus::Init () protected
IsCachedCookedPlatformDataLoaded()
virtual bool USoundSourceBus::IsCachedCookedPlatformDataLoaded (const ITargetPlatform * TargetPlatform) inline override private virtual
Definition at line 60 of file SoundSourceBus.h.
IsPlayable()
virtual bool USoundSourceBus::IsPlayable () const override private virtual
Reimplemented from USoundWave.
IsSeekable()
virtual bool USoundSourceBus::IsSeekable () const inline override private virtual
Queries if Seeking is supported by the Decoder for this Wave.
Returns
true if Seeking is supported, false otherwise.
Reimplemented from USoundWave.
Definition at line 74 of file SoundSourceBus.h.
PostEditChangeProperty()
virtual void USoundSourceBus::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
Reimplemented from USoundWave.
PostLoad()
virtual UPROPERTY()) uint32 bAutoDeactivateWhenSilent void USoundSourceBus::PostLoad () override private virtual
Stop the source bus when the volume goes to zero.
Reimplemented from USoundWave.
References PostLoad().
Referenced by PostLoad().
Serialize()
virtual void USoundSourceBus::Serialize (FArchive & InArchive) override private virtual
Reimplemented from USoundWave.
SerializeCookedPlatformData()
virtual void USoundSourceBus::SerializeCookedPlatformData (FArchive & Ar) inline override private virtual
Serializes cooked platform data.
Reimplemented from USoundWave.
Definition at line 73 of file SoundSourceBus.h.
References Ar.
SerializeCuePoints()
virtual void USoundSourceBus::SerializeCuePoints (FArchive & Ar, const bool bIsLoadingFromCookedArchive) inline protected virtual
Reimplemented from USoundWave.
Definition at line 86 of file SoundSourceBus.h.
References Ar.
UPROPERTY() [1/2]
USoundSourceBus::UPROPERTY () private
Audio bus to use as audio for this source bus.
This source bus will sonify the audio from the audio bus.
References Category, meta, and UPROPERTY().
UPROPERTY() [2/2]
GENERATED_UCLASS_BODY() public USoundSourceBus::UPROPERTY () private
How many channels to use for the source bus if the audio bus is not specified, otherwise it will use the audio bus object's channel count.
The duration (in seconds) to use for the source bus. A duration of 0.0 indicates to play the source bus indefinitely.
References Category, float, and meta.
Referenced by UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Sound/SoundSourceBus.h