Unreal Engine 5.6 C++ API: FHairCardsVertexFactory Class Reference
FHairCardsVertexFactory Class Reference
A vertex factory which simply transforms explicit vertex attributes from local to world space.
#include "HairCardsVertexFactory.h"
Data Structures
struct FDataType
struct FDebugName
Public Member Functions
HAIRSTRANDSCORE_API FHairCardsVertexFactory (FHairGroupInstance *Instance, uint32 LODIndex, EHairGeometryType GeometryType, EShaderPlatform InShaderPlatform, ERHIFeatureLevel::Type InFeatureLevel, const char *InDebugName)
HAIRSTRANDSCORE_API void Copy (const FHairCardsVertexFactory &Other)
Copy the data from another vertex factory.
const FDataType & GetData () const
HAIRSTRANDSCORE_API EPrimitiveIdMode GetPrimitiveIdMode (ERHIFeatureLevel::Type In) const
HAIRSTRANDSCORE_API void InitResources (FRHICommandListBase &RHICmdList)
virtual HAIRSTRANDSCORE_API void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual HAIRSTRANDSCORE_API void ReleaseResource () override
Prepares the resource for deletion.
virtual HAIRSTRANDSCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
HAIRSTRANDSCORE_API void SetData (const FDataType &InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Public Member Functions inherited from FVertexFactory
FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
virtual RENDERCORE_API ~FVertexFactory ()
FVertexDeclarationRHIRef & GetDeclaration ()
const FVertexDeclarationRHIRef & GetDeclaration (EVertexInputStreamType InputStreamType) const
int32 GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const
RENDERCORE_API void GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &OutVertexStreams) const
virtual FShaderResourceViewRHIRef GetTriangleSortingPositionSRV () const
virtual FVertexFactoryType * GetType () const
bool NeedsDeclaration () const
RENDERCORE_API void OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &VertexStreams) const
virtual bool RendersPrimitivesAsCameraFacingSprites () const
void SetDeclaration (FVertexDeclarationRHIRef &NewDeclaration)
bool SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsNullPixelShader () const
Indicates whether the vertex factory supports a null pixel shader.
virtual bool SupportsPositionAndNormalOnlyStream () const
Indicates whether the vertex factory supports a position-and-normal-only stream.
virtual bool SupportsPositionOnlyStream () const
Indicates whether the vertex factory supports a position-only stream.
bool SupportsTriangleSorting () const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static HAIRSTRANDSCORE_API void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
static HAIRSTRANDSCORE_API void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static HAIRSTRANDSCORE_API bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Should we cache the material's shadertype on this platform with this vertex factory?
static HAIRSTRANDSCORE_API void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Static Public Member Functions inherited from FVertexFactory
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields
FDataType Data
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Attributes
bool bIsInitialized = false
struct FHairCardsVertexFactory::FDebugName DebugName
FRDGWrapperVertexBuffer DeformedNormalVertexBuffer
FRDGWrapperVertexBuffer DeformedPositionVertexBuffer [2]
Protected Attributes inherited from FVertexFactory
bool bNeedsDeclaration = true
FVertexStreamList Streams
The vertex streams used to render the factory.
Private Member Functions
DECLARE_VERTEX_FACTORY_TYPE (FHairCardsVertexFactory)
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Protected Types inherited from FVertexFactory
typedef TArray< FVertexStream, TInlineAllocator< 8 > > FVertexStreamList
Protected Member Functions inherited from FVertexFactory
FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex)
Creates a vertex element for a vertex stream components.
RENDERCORE_API FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType)
Creates a vertex element for a vertex stream component.
RENDERCORE_API bool AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList &Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile)
RENDERCORE_API void InitDeclaration (const FVertexDeclarationElementList &Elements, EVertexInputStreamType StreamType=EVertexInputStreamType::Default)
Initializes the vertex declaration.
void SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FVertexFactory
template<typename VertexStreamListType>
static FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, VertexStreamListType &InOutStreams)
Creates a vertex element for a vertex stream components.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A vertex factory which simply transforms explicit vertex attributes from local to world space.
Definition at line 43 of file HairCardsVertexFactory.h.
Constructor & Destructor Documentation
FHairCardsVertexFactory()
HAIRSTRANDSCORE_API FHairCardsVertexFactory::FHairCardsVertexFactory (FHairGroupInstance * Instance, uint32 LODIndex, EHairGeometryType GeometryType, EShaderPlatform InShaderPlatform, ERHIFeatureLevel::Type InFeatureLevel, const char * InDebugName)
References Instance, and UE_API.
Referenced by Copy(), and DECLARE_VERTEX_FACTORY_TYPE().
Member Function Documentation
Copy()
HAIRSTRANDSCORE_API void FHairCardsVertexFactory::Copy (const FHairCardsVertexFactory & Other)
Copy the data from another vertex factory.
Parameters
Other - factory to copy from
References FHairCardsVertexFactory(), Other, and UE_API.
DECLARE_VERTEX_FACTORY_TYPE()
FHairCardsVertexFactory::DECLARE_VERTEX_FACTORY_TYPE (FHairCardsVertexFactory) private
References FHairCardsVertexFactory().
GetData()
const FDataType & FHairCardsVertexFactory::GetData () const inline
Definition at line 84 of file HairCardsVertexFactory.h.
References Data.
GetPrimitiveIdMode()
HAIRSTRANDSCORE_API EPrimitiveIdMode FHairCardsVertexFactory::GetPrimitiveIdMode (ERHIFeatureLevel::Type In) const
References UE_API.
GetPSOPrecacheVertexFetchElements()
HAIRSTRANDSCORE_API void FHairCardsVertexFactory::GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList & Elements) static
References UE_API.
InitResources()
HAIRSTRANDSCORE_API void FHairCardsVertexFactory::InitResources (FRHICommandListBase & RHICmdList)
References UE_API.
InitRHI()
virtual HAIRSTRANDSCORE_API void FHairCardsVertexFactory::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
References UE_API.
ModifyCompilationEnvironment()
HAIRSTRANDSCORE_API void FHairCardsVertexFactory::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) static
References UE_API.
ReleaseResource()
virtual HAIRSTRANDSCORE_API void FHairCardsVertexFactory::ReleaseResource () override virtual
Prepares the resource for deletion.
This is only called by the rendering thread.
Reimplemented from FRenderResource.
References UE_API.
ReleaseRHI()
virtual HAIRSTRANDSCORE_API void FHairCardsVertexFactory::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FVertexFactory.
References UE_API.
SetData()
HAIRSTRANDSCORE_API void FHairCardsVertexFactory::SetData (const FDataType & InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
References UE_API.
ShouldCompilePermutation()
HAIRSTRANDSCORE_API bool FHairCardsVertexFactory::ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters & Parameters) static
Should we cache the material's shadertype on this platform with this vertex factory?
References UE_API.
ValidateCompiledResult()
HAIRSTRANDSCORE_API void FHairCardsVertexFactory::ValidateCompiledResult (const FVertexFactoryType * Type, EShaderPlatform Platform, const FShaderParameterMap & ParameterMap, TArray< FString > & OutErrors) static
References Platform, and UE_API.
Field Documentation
bIsInitialized
bool FHairCardsVertexFactory::bIsInitialized = false protected
Definition at line 88 of file HairCardsVertexFactory.h.
Data
FDataType FHairCardsVertexFactory::Data
Definition at line 85 of file HairCardsVertexFactory.h.
Referenced by GetData().
DebugName
struct FHairCardsVertexFactory::FDebugName FHairCardsVertexFactory::DebugName protected
DeformedNormalVertexBuffer
FRDGWrapperVertexBuffer FHairCardsVertexFactory::DeformedNormalVertexBuffer protected
Definition at line 91 of file HairCardsVertexFactory.h.
DeformedPositionVertexBuffer
FRDGWrapperVertexBuffer FHairCardsVertexFactory::DeformedPositionVertexBuffer[2] protected
Definition at line 90 of file HairCardsVertexFactory.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/HairCardsVertexFactory.h