Unreal Engine 5.6 C++ API: UE::Geometry::TFibonacciLattice< RealType > Class Template Reference
UE::Geometry::TFibonacciLattice< RealType > Class Template Reference
A 2D point set based on the Fibonacci sequence where the i'th point of an N point set can be directly computed.
#include "SphericalFibonacci.h"
Public Types
enum class EType { Square , Disc }
Public Member Functions
TFibonacciLattice (int32 NumPoints=64, EType InType=EType::Square)
int32 Num () const
TVector2< RealType > operator[] (int32 Index) const
TVector2< RealType > Point (int32 Index) const
Data Fields
int32 N = 64
EType Type = EType::Square
Detailed Description
template<typename RealType>
class UE::Geometry::TFibonacciLattice< RealType >
A 2D point set based on the Fibonacci sequence where the i'th point of an N point set can be directly computed.
Reference: Spherical Fibonacci Point Sets for Illumination Integrals https://repositori.upf.edu/bitstream/handle/10230/35552/marques_CGForum32_sphe.pdf?sequence=1&isAllowed=y
Definition at line 145 of file SphericalFibonacci.h.
Member Enumeration Documentation
EType
template<typename RealType> enum class UE::Geometry::TFibonacciLattice::EType strong
Enumerator
Square
Disc
Definition at line 150 of file SphericalFibonacci.h.
Constructor & Destructor Documentation
TFibonacciLattice()
template<typename RealType> UE::Geometry::TFibonacciLattice< RealType >::TFibonacciLattice (int32 NumPoints = 64, EType InType = EType::Square) inline
Definition at line 158 of file SphericalFibonacci.h.
References N, Square, and Type.
Member Function Documentation
Num()
template<typename RealType> int32 UE::Geometry::TFibonacciLattice< RealType >::Num () const inline
Definition at line 163 of file SphericalFibonacci.h.
References N.
operator[]()
template<typename RealType> TVector2< RealType > UE::Geometry::TFibonacciLattice< RealType >::operator[] (int32 Index) const inline
Parameters
Index point index in range [0,Num()-1]
Returns
sphere point for given Index
Definition at line 205 of file SphericalFibonacci.h.
References Point.
Point()
template<typename RealType> TVector2< RealType > UE::Geometry::TFibonacciLattice< RealType >::Point (int32 Index) const inline
Parameters
Index point index in range [0,Num()-1]
Returns
sphere point for given Index
Definition at line 172 of file SphericalFibonacci.h.
References checkSlow, TMathUtil< RealType >::Cos(), Disc, TMathUtil< RealType >::Floor(), N, R, TMathUtil< RealType >::Sin(), TMathUtil< RealType >::Sqrt(), Type, X, and Y.
Field Documentation
N
template<typename RealType> int32 UE::Geometry::TFibonacciLattice< RealType >::N = 64
Definition at line 148 of file SphericalFibonacci.h.
Referenced by TFibonacciLattice(), Num(), and Point().
Type
template<typename RealType> EType UE::Geometry::TFibonacciLattice< RealType >::Type = EType::Square
Definition at line 155 of file SphericalFibonacci.h.
Referenced by TFibonacciLattice(), and Point().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Sampling/SphericalFibonacci.h