Unreal Engine 5.6 C++ API: UE::Solvers::TSparseMatrixAssembler< RealType > Class Template Reference
UE::Solvers::TSparseMatrixAssembler< RealType > Class Template Reference
Generic adapter for building a Sparse Matrix.
#include "MatrixInterfaces.h"
Data Structures
struct FTupleData
Data Fields
TUniqueFunction< void(const FTupleData *, int32)> AddEntriesFunc
Add matrix entries (i,j,Value) and size of tuples.
TUniqueFunction< void(int32, int32, RealType)> AddEntryFunc
Add matrix entry tuple (i,j,Value)
TUniqueFunction< void(int32)> ReserveEntriesFunc
Hint to reserve space for at least this many entries.
Detailed Description
template<typename RealType>
class UE::Solvers::TSparseMatrixAssembler< RealType >
Generic adapter for building a Sparse Matrix.
Generally sparse-matrix assembly code emits matrix entries as tuples of form (i,j,Value).
Definition at line 20 of file MatrixInterfaces.h.
Field Documentation
AddEntriesFunc
template<typename RealType> TUniqueFunction<void(const FTupleData*, int32)> UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntriesFunc
Add matrix entries (i,j,Value) and size of tuples.
Definition at line 42 of file MatrixInterfaces.h.
Referenced by UE::MeshDeformation::ConstructFullCotangentLaplacian().
AddEntryFunc
template<typename RealType> TUniqueFunction<void(int32, int32, RealType)> UE::Solvers::TSparseMatrixAssembler< RealType >::AddEntryFunc
Add matrix entry tuple (i,j,Value)
Definition at line 27 of file MatrixInterfaces.h.
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), and UE::MeshDeformation::ConstructValenceWeightedLaplacian().
ReserveEntriesFunc
template<typename RealType> TUniqueFunction<void(int32)> UE::Solvers::TSparseMatrixAssembler< RealType >::ReserveEntriesFunc
Hint to reserve space for at least this many entries.
Definition at line 24 of file MatrixInterfaces.h.
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), UE::MeshDeformation::ConstructMeanValueWeightLaplacian(), UE::MeshDeformation::ConstructUmbrellaLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), and UE::MeshDeformation::ConstructValenceWeightedLaplacian().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Solvers/MatrixInterfaces.h