Unreal Engine 5.6 C++ API: FInputDeviceScope Class Reference
FInputDeviceScope Class Reference
Context scope that indicates which IInputDevice is currently being handled.
#include "GenericApplicationMessageHandler.h"
Public Member Functions
FInputDeviceScope ()=delete
Cannot be copied/moved.
FInputDeviceScope (const FInputDeviceScope &)=delete
FInputDeviceScope (FInputDeviceScope &&)=delete
APPLICATIONCORE_API FInputDeviceScope (IInputDevice *InInputDevice, FName InInputDeviceName, int32 InHardwareDeviceHandle=-1, FString InHardwareDeviceIdentifier=FString())
Constructor, this should only be allocated directly on the stack.
APPLICATIONCORE_API ~FInputDeviceScope ()
FInputDeviceScope & operator= (const FInputDeviceScope &)=delete
FInputDeviceScope & operator= (FInputDeviceScope &&)=delete
Static Public Member Functions
static APPLICATIONCORE_API const FInputDeviceScope * GetCurrent ()
Returns the currently active InputDeviceScope.
Data Fields
int32 HardwareDeviceHandle
A system-specific device id, this is not the same as controllerId and represents a physical device instead of logical user.
FString HardwareDeviceIdentifier
Logical string identifying the hardware device.
class IInputDevice * InputDevice
The specific InputDevice that is currently being polled.
FName InputDeviceName
Logical name of the input device interface.
Detailed Description
Context scope that indicates which IInputDevice is currently being handled.
This can be used to determine hardware-specific information when handling input from FGenericApplicationMessageHandler subclasses. This is generally set during SendControllerEvents or Tick and is only valid on the game thread.
Definition at line 177 of file GenericApplicationMessageHandler.h.
Constructor & Destructor Documentation
FInputDeviceScope() [1/4]
APPLICATIONCORE_API FInputDeviceScope::FInputDeviceScope (IInputDevice * InInputDevice, FName InInputDeviceName, int32 InHardwareDeviceHandle = -1, FString InHardwareDeviceIdentifier = FString())
Constructor, this should only be allocated directly on the stack.
Referenced by FInputDeviceScope(), FInputDeviceScope(), GetCurrent(), operator=(), and operator=().
~FInputDeviceScope()
APPLICATIONCORE_API FInputDeviceScope::~FInputDeviceScope ()
FInputDeviceScope() [2/4]
FInputDeviceScope::FInputDeviceScope () delete
Cannot be copied/moved.
FInputDeviceScope() [3/4]
FInputDeviceScope::FInputDeviceScope (const FInputDeviceScope &) delete
References FInputDeviceScope().
FInputDeviceScope() [4/4]
FInputDeviceScope::FInputDeviceScope (FInputDeviceScope &&) delete
References FInputDeviceScope().
Member Function Documentation
GetCurrent()
APPLICATIONCORE_API const FInputDeviceScope * FInputDeviceScope::GetCurrent () static
Returns the currently active InputDeviceScope.
This is only valid to call on the game thread and may return null
References FInputDeviceScope().
operator=() [1/2]
FInputDeviceScope & FInputDeviceScope::operator= (const FInputDeviceScope &) delete
References FInputDeviceScope().
operator=() [2/2]
FInputDeviceScope & FInputDeviceScope::operator= (FInputDeviceScope &&) delete
References FInputDeviceScope().
Field Documentation
HardwareDeviceHandle
int32 FInputDeviceScope::HardwareDeviceHandle
A system-specific device id, this is not the same as controllerId and represents a physical device instead of logical user.
-1 represents an unknown device
Definition at line 187 of file GenericApplicationMessageHandler.h.
HardwareDeviceIdentifier
FString FInputDeviceScope::HardwareDeviceIdentifier
Logical string identifying the hardware device.
This is not translated and is system-specific, it may be empty
Definition at line 190 of file GenericApplicationMessageHandler.h.
InputDevice
class IInputDevice* FInputDeviceScope::InputDevice
The specific InputDevice that is currently being polled.
This is only valid within the current function scope and may be null
Definition at line 181 of file GenericApplicationMessageHandler.h.
InputDeviceName
FName FInputDeviceScope::InputDeviceName
Logical name of the input device interface.
This is not translated but is platform-specific
Definition at line 184 of file GenericApplicationMessageHandler.h.
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/GenericPlatform/GenericApplicationMessageHandler.h