Unreal Engine 5.6 C++ API: UE::Geometry::FRefCountVector::IndexIterator Class Reference
UE::Geometry::FRefCountVector::IndexIterator Class Reference
#include "RefCountVector.h"
Public Member Functions
IndexIterator ()
int operator* () const
IndexIterator & operator++ ()
IndexIterator operator++ (int)
Public Member Functions inherited from UE::Geometry::FRefCountVector::BaseIterator
BaseIterator ()
bool operator!= (const BaseIterator &Other) const
bool operator== (const BaseIterator &Other) const
Protected Member Functions
IndexIterator (const FRefCountVector *VectorIn, int Index, int Last)
Protected Member Functions inherited from UE::Geometry::FRefCountVector::BaseIterator
BaseIterator (const FRefCountVector *VectorIn, int IndexIn, int LastIn)
void goto_next ()
Friends
class FRefCountVector
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::FRefCountVector::BaseIterator
int Index
int LastIndex
const FRefCountVector * Vector
Detailed Description
Definition at line 383 of file RefCountVector.h.
Constructor & Destructor Documentation
IndexIterator() [1/2]
UE::Geometry::FRefCountVector::IndexIterator::IndexIterator () inline
Definition at line 386 of file RefCountVector.h.
References UE::Geometry::FRefCountVector::BaseIterator::BaseIterator().
Referenced by operator++(), and operator++().
IndexIterator() [2/2]
UE::Geometry::FRefCountVector::IndexIterator::IndexIterator (const FRefCountVector * VectorIn, int Index, int Last) inline protected
Definition at line 406 of file RefCountVector.h.
References UE::Geometry::FRefCountVector::BaseIterator::BaseIterator(), FRefCountVector, UE::Geometry::FRefCountVector::BaseIterator::Index, and Last.
Member Function Documentation
operator*()
int UE::Geometry::FRefCountVector::IndexIterator::operator* () const inline
Definition at line 388 of file RefCountVector.h.
References UE::Geometry::FRefCountVector::BaseIterator::Index.
operator++() [1/2]
IndexIterator & UE::Geometry::FRefCountVector::IndexIterator::operator++ () inline
Definition at line 393 of file RefCountVector.h.
References IndexIterator(), and UE::Geometry::FRefCountVector::BaseIterator::goto_next().
operator++() [2/2]
IndexIterator UE::Geometry::FRefCountVector::IndexIterator::operator++ (int) inline
Definition at line 398 of file RefCountVector.h.
References IndexIterator(), and UE::Geometry::FRefCountVector::BaseIterator::goto_next().
Friends And Related Symbol Documentation
FRefCountVector
friend class FRefCountVector friend
Definition at line 408 of file RefCountVector.h.
References FRefCountVector.
Referenced by IndexIterator(), and FRefCountVector.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/RefCountVector.h