Unreal Engine 5.6 C++ API: TCommands< CommandContextType > Class Template Reference
TCommands< CommandContextType > Class Template Reference abstract
A base class for a set of commands.
#include "Commands.h"
Static Public Member Functions
static CommandContextType & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Protected Member Functions
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
virtual void RegisterCommands ()=0
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static TWeakPtr< CommandContextType > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Additional Inherited Members
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Detailed Description
template<typename CommandContextType>
class TCommands< CommandContextType >
A base class for a set of commands.
Inherit from it to make a set of commands. See MainFrameActions for an example.
Definition at line 32 of file Commands.h.
Constructor & Destructor Documentation
TCommands()
template<typename CommandContextType> TCommands< CommandContextType >::TCommands (const FName InContextName, const FText & InContextDesc, const FName InContextParent, const FName InStyleSetName) inline protected
Construct a set of commands; call this from your custom commands class.
Definition at line 110 of file Commands.h.
References FBindingContext::FBindingContext().
Referenced by TInteractiveToolCommands< CommandContextType >::TInteractiveToolCommands().
~TCommands()
template<typename CommandContextType> virtual TCommands< CommandContextType >::~TCommands () inline protected virtual
Definition at line 114 of file Commands.h.
Member Function Documentation
Get()
template<typename CommandContextType> CommandContextType & TCommands< CommandContextType >::Get () inline static
Get the singleton instance of this set of commands.
Definition at line 73 of file Commands.h.
References GetInstance().
Referenced by FPersonaCommonCommands::Get().
GetContext()
template<typename CommandContextType> const FBindingContext & TCommands< CommandContextType >::GetContext () inline static
Get the BindingContext for this set of commands.
Definition at line 100 of file Commands.h.
References FBindingContext::FBindingContext(), check, GetInstance(), and Instance.
GetInstance()
template<typename CommandContextType> TWeakPtr< CommandContextType > & TCommands< CommandContextType >::GetInstance () inline static protected
A static instance of the command set.
Definition at line 126 of file Commands.h.
Referenced by Get(), GetContext(), IsRegistered(), Register(), and Unregister().
IsRegistered()
template<typename CommandContextType> bool TCommands< CommandContextType >::IsRegistered () inline static
Definition at line 67 of file Commands.h.
References GetInstance().
Register()
template<typename CommandContextType> void TCommands< CommandContextType >::Register () inline static
Use this method to register commands.
Usually done in StartupModule().
Definition at line 38 of file Commands.h.
References FBindingContext::CommandsChanged, FInputBindingManager::Get(), FInputBindingManager::GetContextByName(), GetInstance(), Instance, TSharedPtr< ObjectType, InMode >::IsValid(), MakeShareable(), and StaticCastSharedPtr().
RegisterCommands()
template<typename CommandContextType> virtual void TCommands< CommandContextType >::RegisterCommands () protected pure virtual
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Implemented in FAnimGraphCommands, FCachingEditorCommands, FCurveEditorCommands, FEditorViewportCommands, FFullBlueprintEditorCommands, FGlobalEditorCommonCommands, FGPUSkinCacheVisualizationMenuCommands, FGraphEditorCommandsImpl, FMyBlueprintCommands, FPersonaCommonCommands, FPlayWorldCommands, FRayTracingDebugVisualizationMenuCommands, FRigVMEditorGraphExplorerCommands, FRigVMExecutionStackCommands, FSequencerCommands, FSoundClassEditorCommands, FSoundCueGraphEditorCommands, FStandardToolModeCommands, FTabCommands, FViewportNavigationCommands, and TInteractiveToolCommands< CommandContextType >.
Unregister()
template<typename CommandContextType> void TCommands< CommandContextType >::Unregister () inline static
Use this method to clean up any resources used by the command set.
Usually done in ShutdownModule()
Definition at line 82 of file Commands.h.
References check, FBindingContext::CommandsChanged, FInputBindingManager::Get(), GetInstance(), Instance, and FInputBindingManager::RemoveContextByName().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Commands/Commands.h