Unreal Engine 5.6 C++ API: UE::Geometry::FTwistKelvinlet Class Reference
UE::Geometry::FTwistKelvinlet Class Reference
#include "Kelvinlets.h"
Public Types
typedef TBaseKelvinlet< FTwistKelvinlet > MyBase
Public Member Functions
FTwistKelvinlet (const FTwistKelvinlet &Other)
FTwistKelvinlet (const FVector3d &Twist, const double Size, const double ShearModulus, const double PoissonRatio)
double Divergence (const FVector3d &Pos) const
FVector3d Evaluate (const FVector3d &Pos) const
Public Member Functions inherited from UE::Geometry::TBaseKelvinlet< FTwistKelvinlet >
TBaseKelvinlet (const double Size, const double ShearModulus, const double PoissonRatio)
void SetMaterialParameters (const double ShearModulus, const double PoissonRatio)
void UpdateRegularization (const double R)
Public Member Functions inherited from UE::Geometry::TKelvinletIntegrator< KelvinletModelType >
FVector3d Evaluate (const FVector3d &Pos) const
FVector3d IntegrateRK3 (const FVector3d &Pos, double dt) const
Protected Attributes
FMatrix3d F
Protected Attributes inherited from UE::Geometry::TBaseKelvinlet< FTwistKelvinlet >
double a
double bhat
double E
Detailed Description
Definition at line 454 of file Kelvinlets.h.
Member Typedef Documentation
MyBase
typedef TBaseKelvinlet< FTwistKelvinlet> UE::Geometry::FTwistKelvinlet::MyBase
Definition at line 457 of file Kelvinlets.h.
Constructor & Destructor Documentation
FTwistKelvinlet() [1/2]
UE::Geometry::FTwistKelvinlet::FTwistKelvinlet (const FVector3d & Twist, const double Size, const double ShearModulus, const double PoissonRatio) inline
Definition at line 459 of file Kelvinlets.h.
References UE::Geometry::CrossProductMatrix(), F, and TSequenceHistory< HistorySize >::Size.
Referenced by FTwistKelvinlet().
FTwistKelvinlet() [2/2]
UE::Geometry::FTwistKelvinlet::FTwistKelvinlet (const FTwistKelvinlet & Other) inline
Definition at line 465 of file Kelvinlets.h.
References FTwistKelvinlet(), F, and Other.
Member Function Documentation
Divergence()
double UE::Geometry::FTwistKelvinlet::Divergence (const FVector3d & Pos) const inline
Definition at line 500 of file Kelvinlets.h.
Evaluate()
FVector3d UE::Geometry::FTwistKelvinlet::Evaluate (const FVector3d & Pos) const inline
Definition at line 473 of file Kelvinlets.h.
References UE::Geometry::TBaseKelvinlet< FTwistKelvinlet >::E, F, and UE::Math::TVector< T >::SquaredLength().
Field Documentation
F
FMatrix3d UE::Geometry::FTwistKelvinlet::F protected
Definition at line 508 of file Kelvinlets.h.
Referenced by FTwistKelvinlet(), FTwistKelvinlet(), and Evaluate().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Deformers/Kelvinlets.h