Unreal Engine 5.6 C++ API: SCheckBox Class Reference
SCheckBox Class Reference
Check box Slate control.
#include "SCheckBox.h"
Public Member Functions
Style OnCheckStateChanged HAlign CheckBoxContentUsesAutoWidth virtual SLATE_ATTRIBUTE(FMargin, Padding) SLATE_ARGUMENT(EButtonClickMethod ~SCheckBox ()
Spacing between the check box image and its content (set by the Style arg but the Style can be overridden with this)
void Construct (const FArguments &InArgs)
Construct this widget.
ECheckBoxState GetCheckedState () const
virtual FSlateColor GetForegroundColor () const
bool IsChecked () const
Returns true if the checkbox is currently checked.
virtual bool IsInteractable () const override
bool IsPressed () const
Returns true if this button is currently pressed.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
void SetCheckedHoveredImage (const FSlateBrush *Brush)
See the CheckedHoveredImage attribute.
void SetCheckedImage (const FSlateBrush *Brush)
See the CheckedImage attribute.
void SetCheckedPressedImage (const FSlateBrush *Brush)
See the CheckedPressedImage attribute.
void SetClickMethod (EButtonClickMethod::Type InClickMethod)
void SetContent (const TSharedRef< SWidget > &InContent)
See the Content slot.
void SetIsChecked (TAttribute< ECheckBoxState > InIsChecked)
See the IsChecked attribute.
void SetPressMethod (EButtonPressMethod::Type InPressMethod)
void SetStyle (const FCheckBoxStyle *InStyle)
See the Style attribute.
void SetTouchMethod (EButtonTouchMethod::Type InTouchMethod)
void SetUncheckedHoveredImage (const FSlateBrush *Brush)
See the UncheckedHoveredImage attribute.
void SetUncheckedImage (const FSlateBrush *Brush)
See the UncheckedImage attribute.
void SetUncheckedPressedImage (const FSlateBrush *Brush)
See the UncheckedPressedImage attribute.
void SetUndeterminedHoveredImage (const FSlateBrush *Brush)
See the UndeterminedHoveredImage attribute.
void SetUndeterminedImage (const FSlateBrush *Brush)
See the UndeterminedImage attribute.
void SetUndeterminedPressedImage (const FSlateBrush *Brush)
See the UndeterminedPressedImage attribute.
Style OnCheckStateChanged HAlign SLATE_ARGUMENT (EVerticalAlignment, CheckBoxImageVAlign) SLATE_ARGUMENT(bool
How the image of the checkbox should align vertically within the given space.
Style SLATE_ARGUMENT (TOptional< ESlateCheckBoxType::Type >, Type) SLATE_EVENT(FOnCheckStateChanged
Type of check box (set by the Style arg but the Style can be overridden with this)
Style OnCheckStateChanged SLATE_ATTRIBUTE (ECheckBoxState, IsChecked) SLATE_ARGUMENT(EHorizontalAlignment
Whether the check box is currently in a checked state.
SLATE_BEGIN_ARGS (SCheckBox)
SLATE_DEFAULT_SLOT (FArguments, Content) SLATE_STYLE_ARGUMENT(FCheckBoxStyle
Content to be placed next to the check box, or for a toggle button, the content to be placed inside the button.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
void ToggleCheckedState ()
Toggles the checked state for this check box, fire events as needed.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
void BuildCheckBox (TSharedRef< SWidget > InContent)
Rebuilds the checkbox based on the current ESlateCheckBoxType.
const FSlateBrush * GetBackgroundHoveredImage () const
const FSlateBrush * GetBackgroundImage () const
const FSlateBrush * GetBackgroundPressedImage () const
const FSlateBrush * GetCheckedHoveredImage () const
const FSlateBrush * GetCheckedImage () const
const FSlateBrush * GetCheckedPressedImage () const
TEnumAsByte< EButtonClickMethod::Type > GetClickMethodFromInputType (const FPointerEvent &MouseEvent) const
Utility function to translate other input click methods to regular ones.
const FSlateBrush * GetUncheckedHoveredImage () const
const FSlateBrush * GetUncheckedImage () const
const FSlateBrush * GetUncheckedPressedImage () const
const FSlateBrush * GetUndeterminedHoveredImage () const
const FSlateBrush * GetUndeterminedImage () const
const FSlateBrush * GetUndeterminedPressedImage () const
bool IsPreciseTapOrClick (const FPointerEvent &MouseEvent) const
Utility function to determine if the incoming mouse event is for a precise tap or click.
const FSlateBrush * OnGetBackgroundImage () const
Attribute getter for the background image.
FSlateColor OnGetBorderBackgroundColor () const
Attribute getter for the border background color.
ESlateCheckBoxType::Type OnGetCheckBoxType () const
Attribute getter for the checkbox type.
const FSlateBrush * OnGetCheckImage () const
Gets the check image to display for the current state of the check box.
FMargin OnGetPadding () const
Attribute getter for the padding.
void PlayCheckedSound () const
Play the checked sound.
void PlayHoverSound () const
Play the hovered sound.
void PlayUncheckedSound () const
Play the unchecked sound.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
const FSlateBrush * BackgroundHoveredImage
Image to use for the checkbox background when hovered.
const FSlateBrush * BackgroundImage
Image to use for the checkbox background.
const FSlateBrush * BackgroundPressedImage
Image to use for the checkbox background when pressed.
bool bCheckBoxContentUsesAutoWidth
Whether or not the checkbox content is arranged using auto-width when in checkbox mode.
bool bIsFocusable
When true, this checkbox will be keyboard focusable.
bool bIsPressed
True if this check box is currently in a pressed state.
TAttribute< FSlateColor > BorderBackgroundColorOverride
Overrides border background color in the widget style, if set.
EVerticalAlignment CheckBoxImageVAlign
How the image of the checkbox should align vertically within the given space.
TOptional< ESlateCheckBoxType::Type > CheckBoxTypeOverride
Overrides checkbox type in the widget style, if set.
const FSlateBrush * CheckedHoveredImage
Image to use when the checkbox is checked and hovered.
const FSlateBrush * CheckedImage
Image to use when the checkbox is checked.
const FSlateBrush * CheckedPressedImage
Image to use when the checkbox is checked and pressed.
FSlateSound CheckedSound
The Sound to play when the check box is checked.
EButtonClickMethod::Type ClickMethod
Sets whether a click should be triggered on mouse down, mouse up, or that both a mouse down and up are required.
TSharedPtr< SBorder > ContentContainer
When in toggle button mode, this will hold the pointer to the toggle button's border.
TAttribute< FSlateColor > ForegroundColorOverride
Overrides foreground color in the widget style, if set.
EHorizontalAlignment HorizontalAlignment
How the content of the toggle button should align within the given space.
FSlateSound HoveredSound
The Sound to play when the check box is hovered.
TAttribute< ECheckBoxState > IsCheckboxChecked
Are we checked.
FOnCheckStateChanged OnCheckStateChanged
Delegate called when the check box changes state.
FOnGetContent OnGetMenuContent
Delegate to execute to get the menu content of this button.
TAttribute< FMargin > PaddingOverride
Overrides padding in the widget style, if set.
TEnumAsByte< EButtonPressMethod::Type > PressMethod
How should the button be clicked with keyboard/controller button events?
const FCheckBoxStyle * Style
TEnumAsByte< EButtonTouchMethod::Type > TouchMethod
How should the button be clicked with touch events?
const FSlateBrush * UncheckedHoveredImage
Image to use when the checkbox is unchecked and hovered.
const FSlateBrush * UncheckedImage
Image to use when the checkbox is unchecked.
const FSlateBrush * UncheckedPressedImage
Image to use when the checkbox is unchecked and pressed.
FSlateSound UncheckedSound
The Sound to play when the check box is unchecked.
const FSlateBrush * UndeterminedHoveredImage
Image to use when the checkbox is in an ambiguous state and hovered.
const FSlateBrush * UndeterminedImage
Image to use when the checkbox is in an ambiguous state.
const FSlateBrush * UndeterminedPressedImage
Image to use when the checkbox is in an ambiguous state and pressed.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Check box Slate control.
Definition at line 29 of file SCheckBox.h.
Constructor & Destructor Documentation
~SCheckBox()
Style OnCheckStateChanged HAlign CheckBoxContentUsesAutoWidth virtual SLATE_ATTRIBUTE(FMargin, Padding) SLATE_ARGUMENT(EButtonClickMethod SCheckBox::~SCheckBox () virtual
Spacing between the check box image and its content (set by the Style arg but the Style can be overridden with this)
Sets the rules to use for determining whether the button was clicked. This is an advanced setting and generally should be left as the default. How should the button be clicked with touch events? How should the button be clicked with keyboard/controller button events? Foreground color for the checkbox's content and parts (set by the Style arg but the Style can be overridden with this) The color of the background border (set by the Style arg but the Style can be overridden with this) The sound to play when the check box is checked The sound to play when the check box is unchecked The sound to play when the check box is hovered The unchecked image for the checkbox - overrides the style's The unchecked hovered image for the checkbox - overrides the style's The unchecked pressed image for the checkbox - overrides the style's The checked image for the checkbox - overrides the style's The checked hovered image for the checkbox - overrides the style's The checked pressed image for the checkbox - overrides the style's The undetermined image for the checkbox - overrides the style's The undetermined hovered image for the checkbox - overrides the style's The undetermined pressed image for the checkbox - overrides the style's The background image for the checkbox - overrides the style's The background hovered image for the checkbox - overrides the style's The background pressed image for the checkbox - overrides the style's
Member Function Documentation
BuildCheckBox()
void SCheckBox::BuildCheckBox (TSharedRef< SWidget > InContent) protected
Rebuilds the checkbox based on the current ESlateCheckBoxType.
Construct()
void SCheckBox::Construct (const FArguments & InArgs)
Construct this widget.
Parameters
InArgs The declaration data for this widget
References Construct().
Referenced by Construct().
GetBackgroundHoveredImage()
const FSlateBrush * SCheckBox::GetBackgroundHoveredImage () const protected
GetBackgroundImage()
const FSlateBrush * SCheckBox::GetBackgroundImage () const protected
GetBackgroundPressedImage()
const FSlateBrush * SCheckBox::GetBackgroundPressedImage () const protected
GetCheckedHoveredImage()
const FSlateBrush * SCheckBox::GetCheckedHoveredImage () const protected
GetCheckedImage()
const FSlateBrush * SCheckBox::GetCheckedImage () const protected
GetCheckedPressedImage()
const FSlateBrush * SCheckBox::GetCheckedPressedImage () const protected
GetCheckedState()
ECheckBoxState SCheckBox::GetCheckedState () const
Returns
The current checked state of the checkbox.
GetClickMethodFromInputType()
TEnumAsByte< EButtonClickMethod::Type > SCheckBox::GetClickMethodFromInputType (const FPointerEvent & MouseEvent) const protected
Utility function to translate other input click methods to regular ones.
References MouseEvent.
GetForegroundColor()
virtual FSlateColor SCheckBox::GetForegroundColor () const virtual
Returns
the Foreground color that this widget sets; unset options if the widget does not set a foreground color
Reimplemented from SCompoundWidget.
References GetForegroundColor().
Referenced by GetForegroundColor().
GetUncheckedHoveredImage()
const FSlateBrush * SCheckBox::GetUncheckedHoveredImage () const protected
GetUncheckedImage()
const FSlateBrush * SCheckBox::GetUncheckedImage () const protected
GetUncheckedPressedImage()
const FSlateBrush * SCheckBox::GetUncheckedPressedImage () const protected
GetUndeterminedHoveredImage()
const FSlateBrush * SCheckBox::GetUndeterminedHoveredImage () const protected
GetUndeterminedImage()
const FSlateBrush * SCheckBox::GetUndeterminedImage () const protected
GetUndeterminedPressedImage()
const FSlateBrush * SCheckBox::GetUndeterminedPressedImage () const protected
IsChecked()
bool SCheckBox::IsChecked () const inline
Returns true if the checkbox is currently checked.
Returns
True if checked, otherwise false
Definition at line 191 of file SCheckBox.h.
References IsCheckboxChecked.
Referenced by SLATE_ATTRIBUTE().
IsInteractable()
virtual bool SCheckBox::IsInteractable () const override virtual
Returns
Is this widget interactive or not? Defaults to false
Reimplemented from SWidget.
References IsInteractable().
Referenced by IsInteractable().
IsPreciseTapOrClick()
bool SCheckBox::IsPreciseTapOrClick (const FPointerEvent & MouseEvent) const protected
Utility function to determine if the incoming mouse event is for a precise tap or click.
References MouseEvent.
IsPressed()
bool SCheckBox::IsPressed () const inline
Returns true if this button is currently pressed.
Returns
True if pressed, otherwise false
Definition at line 204 of file SCheckBox.h.
References bIsPressed.
OnGetBackgroundImage()
const FSlateBrush * SCheckBox::OnGetBackgroundImage () const protected
Attribute getter for the background image.
OnGetBorderBackgroundColor()
FSlateColor SCheckBox::OnGetBorderBackgroundColor () const protected
Attribute getter for the border background color.
OnGetCheckBoxType()
ESlateCheckBoxType::Type SCheckBox::OnGetCheckBoxType () const protected
Attribute getter for the checkbox type.
OnGetCheckImage()
const FSlateBrush * SCheckBox::OnGetCheckImage () const protected
Gets the check image to display for the current state of the check box.
Returns
The name of the image to display
OnGetPadding()
FMargin SCheckBox::OnGetPadding () const protected
Attribute getter for the padding.
OnKeyDown()
virtual FReply SCheckBox::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnKeyUp()
virtual FReply SCheckBox::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyUp().
Referenced by OnKeyUp().
OnMouseButtonDoubleClick()
virtual FReply SCheckBox::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) override virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnMouseButtonDoubleClick().
Referenced by OnMouseButtonDoubleClick().
OnMouseButtonDown()
virtual FReply SCheckBox::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonDown().
Referenced by OnMouseButtonDown().
OnMouseButtonUp()
virtual FReply SCheckBox::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonUp().
Referenced by OnMouseButtonUp().
OnMouseEnter()
virtual void SCheckBox::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent, and OnMouseEnter().
Referenced by OnMouseEnter().
OnMouseLeave()
virtual void SCheckBox::OnMouseLeave (const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent, and OnMouseLeave().
Referenced by OnMouseLeave().
PlayCheckedSound()
void SCheckBox::PlayCheckedSound () const protected
Play the checked sound.
PlayHoverSound()
void SCheckBox::PlayHoverSound () const protected
Play the hovered sound.
PlayUncheckedSound()
void SCheckBox::PlayUncheckedSound () const protected
Play the unchecked sound.
SetCheckedHoveredImage()
void SCheckBox::SetCheckedHoveredImage (const FSlateBrush * Brush)
See the CheckedHoveredImage attribute.
SetCheckedImage()
void SCheckBox::SetCheckedImage (const FSlateBrush * Brush)
See the CheckedImage attribute.
SetCheckedPressedImage()
void SCheckBox::SetCheckedPressedImage (const FSlateBrush * Brush)
See the CheckedPressedImage attribute.
SetClickMethod()
void SCheckBox::SetClickMethod (EButtonClickMethod::Type InClickMethod)
SetContent()
void SCheckBox::SetContent (const TSharedRef< SWidget > & InContent)
See the Content slot.
SetIsChecked()
void SCheckBox::SetIsChecked (TAttribute< ECheckBoxState > InIsChecked)
See the IsChecked attribute.
SetPressMethod()
void SCheckBox::SetPressMethod (EButtonPressMethod::Type InPressMethod)
SetStyle()
void SCheckBox::SetStyle (const FCheckBoxStyle * InStyle)
See the Style attribute.
SetTouchMethod()
void SCheckBox::SetTouchMethod (EButtonTouchMethod::Type InTouchMethod)
SetUncheckedHoveredImage()
void SCheckBox::SetUncheckedHoveredImage (const FSlateBrush * Brush)
See the UncheckedHoveredImage attribute.
SetUncheckedImage()
void SCheckBox::SetUncheckedImage (const FSlateBrush * Brush)
See the UncheckedImage attribute.
SetUncheckedPressedImage()
void SCheckBox::SetUncheckedPressedImage (const FSlateBrush * Brush)
See the UncheckedPressedImage attribute.
SetUndeterminedHoveredImage()
void SCheckBox::SetUndeterminedHoveredImage (const FSlateBrush * Brush)
See the UndeterminedHoveredImage attribute.
SetUndeterminedImage()
void SCheckBox::SetUndeterminedImage (const FSlateBrush * Brush)
See the UndeterminedImage attribute.
SetUndeterminedPressedImage()
void SCheckBox::SetUndeterminedPressedImage (const FSlateBrush * Brush)
See the UndeterminedPressedImage attribute.
SLATE_ARGUMENT() [1/2]
Style OnCheckStateChanged HAlign SCheckBox::SLATE_ARGUMENT (EVerticalAlignment , CheckBoxImageVAlign)
How the image of the checkbox should align vertically within the given space.
Whether or not the content portion of the checkbox should layout using auto-width. When true the content will always be arranged at its desired size as opposed to resizing to the available space.
References BackgroundHoveredImage, BackgroundImage, BackgroundPressedImage, CheckBoxImageVAlign, CheckedHoveredImage, CheckedImage, CheckedPressedImage, ClickMethod, OnGetMenuContent, Padding, PressMethod, SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_END_ARGS, SLATE_EVENT, TouchMethod, UncheckedHoveredImage, UncheckedImage, UncheckedPressedImage, UndeterminedHoveredImage, UndeterminedImage, and UndeterminedPressedImage.
SLATE_ARGUMENT() [2/2]
Style SCheckBox::SLATE_ARGUMENT (TOptional< ESlateCheckBoxType::Type > , Type)
Type of check box (set by the Style arg but the Style can be overridden with this)
Called when the checked state has changed
References OnCheckStateChanged, SLATE_ARGUMENT(), and SLATE_EVENT.
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE()
Style OnCheckStateChanged SCheckBox::SLATE_ATTRIBUTE (ECheckBoxState , IsChecked)
Whether the check box is currently in a checked state.
How the content of the toggle button should align within the given space
References IsChecked(), SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SCheckBox::SLATE_BEGIN_ARGS (SCheckBox) inline
Definition at line 33 of file SCheckBox.h.
References Unchecked.
SLATE_DEFAULT_SLOT()
SCheckBox::SLATE_DEFAULT_SLOT (FArguments , Content)
Content to be placed next to the check box, or for a toggle button, the content to be placed inside the button.
The style structure for this checkbox' visual style
References Style.
SupportsKeyboardFocus()
virtual bool SCheckBox::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
References SupportsKeyboardFocus().
Referenced by SupportsKeyboardFocus().
ToggleCheckedState()
void SCheckBox::ToggleCheckedState ()
Toggles the checked state for this check box, fire events as needed.
Field Documentation
BackgroundHoveredImage
const FSlateBrush* SCheckBox::BackgroundHoveredImage protected
Image to use for the checkbox background when hovered.
Definition at line 320 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
BackgroundImage
const FSlateBrush* SCheckBox::BackgroundImage protected
Image to use for the checkbox background.
Definition at line 318 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
BackgroundPressedImage
const FSlateBrush* SCheckBox::BackgroundPressedImage protected
Image to use for the checkbox background when pressed.
Definition at line 322 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
bCheckBoxContentUsesAutoWidth
bool SCheckBox::bCheckBoxContentUsesAutoWidth protected
Whether or not the checkbox content is arranged using auto-width when in checkbox mode.
Definition at line 340 of file SCheckBox.h.
bIsFocusable
bool SCheckBox::bIsFocusable protected
When true, this checkbox will be keyboard focusable.
Defaults to true.
Definition at line 352 of file SCheckBox.h.
bIsPressed
bool SCheckBox::bIsPressed protected
True if this check box is currently in a pressed state.
Definition at line 291 of file SCheckBox.h.
Referenced by IsPressed().
BorderBackgroundColorOverride
TAttribute<FSlateColor> SCheckBox::BorderBackgroundColorOverride protected
Overrides border background color in the widget style, if set.
Definition at line 329 of file SCheckBox.h.
CheckBoxImageVAlign
EVerticalAlignment SCheckBox::CheckBoxImageVAlign protected
How the image of the checkbox should align vertically within the given space.
Definition at line 337 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
CheckBoxTypeOverride
TOptional<ESlateCheckBoxType::Type> SCheckBox::CheckBoxTypeOverride protected
Overrides checkbox type in the widget style, if set.
Definition at line 331 of file SCheckBox.h.
CheckedHoveredImage
const FSlateBrush* SCheckBox::CheckedHoveredImage protected
Image to use when the checkbox is checked and hovered.
Definition at line 308 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
CheckedImage
const FSlateBrush* SCheckBox::CheckedImage protected
Image to use when the checkbox is checked.
Definition at line 306 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
CheckedPressedImage
const FSlateBrush* SCheckBox::CheckedPressedImage protected
Image to use when the checkbox is checked and pressed.
Definition at line 310 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
CheckedSound
FSlateSound SCheckBox::CheckedSound protected
The Sound to play when the check box is checked.
Definition at line 376 of file SCheckBox.h.
ClickMethod
EButtonClickMethod::Type SCheckBox::ClickMethod protected
Sets whether a click should be triggered on mouse down, mouse up, or that both a mouse down and up are required.
Definition at line 343 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
ContentContainer
TSharedPtr<SBorder> SCheckBox::ContentContainer protected
When in toggle button mode, this will hold the pointer to the toggle button's border.
Definition at line 383 of file SCheckBox.h.
ForegroundColorOverride
TAttribute<FSlateColor> SCheckBox::ForegroundColorOverride protected
Overrides foreground color in the widget style, if set.
Definition at line 327 of file SCheckBox.h.
HorizontalAlignment
EHorizontalAlignment SCheckBox::HorizontalAlignment protected
How the content of the toggle button should align within the given space.
Definition at line 334 of file SCheckBox.h.
HoveredSound
FSlateSound SCheckBox::HoveredSound protected
The Sound to play when the check box is hovered.
Definition at line 373 of file SCheckBox.h.
IsCheckboxChecked
TAttribute<ECheckBoxState> SCheckBox::IsCheckboxChecked protected
Are we checked.
Definition at line 294 of file SCheckBox.h.
Referenced by IsChecked().
OnCheckStateChanged
FOnCheckStateChanged SCheckBox::OnCheckStateChanged protected
Delegate called when the check box changes state.
Definition at line 297 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
OnGetMenuContent
FOnGetContent SCheckBox::OnGetMenuContent protected
Delegate to execute to get the menu content of this button.
Definition at line 355 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
PaddingOverride
TAttribute<FMargin> SCheckBox::PaddingOverride protected
Overrides padding in the widget style, if set.
Definition at line 325 of file SCheckBox.h.
PressMethod
TEnumAsByte<EButtonPressMethod::Type> SCheckBox::PressMethod protected
How should the button be clicked with keyboard/controller button events?
Definition at line 349 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
Style
const FCheckBoxStyle* SCheckBox::Style protected
Definition at line 288 of file SCheckBox.h.
Referenced by SLATE_DEFAULT_SLOT().
TouchMethod
TEnumAsByte<EButtonTouchMethod::Type> SCheckBox::TouchMethod protected
How should the button be clicked with touch events?
Definition at line 346 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
UncheckedHoveredImage
const FSlateBrush* SCheckBox::UncheckedHoveredImage protected
Image to use when the checkbox is unchecked and hovered.
Definition at line 302 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
UncheckedImage
const FSlateBrush* SCheckBox::UncheckedImage protected
Image to use when the checkbox is unchecked.
Definition at line 300 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
UncheckedPressedImage
const FSlateBrush* SCheckBox::UncheckedPressedImage protected
Image to use when the checkbox is unchecked and pressed.
Definition at line 304 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
UncheckedSound
FSlateSound SCheckBox::UncheckedSound protected
The Sound to play when the check box is unchecked.
Definition at line 379 of file SCheckBox.h.
UndeterminedHoveredImage
const FSlateBrush* SCheckBox::UndeterminedHoveredImage protected
Image to use when the checkbox is in an ambiguous state and hovered.
Definition at line 314 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
UndeterminedImage
const FSlateBrush* SCheckBox::UndeterminedImage protected
Image to use when the checkbox is in an ambiguous state.
Definition at line 312 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
UndeterminedPressedImage
const FSlateBrush* SCheckBox::UndeterminedPressedImage protected
Image to use when the checkbox is in an ambiguous state and pressed.
Definition at line 316 of file SCheckBox.h.
Referenced by SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SCheckBox.h