Unreal Engine 5.6 C++ API: FPropertyUpdatedWidgetBuilder Class Reference
FPropertyUpdatedWidgetBuilder Class Reference
#include "PropertyUpdatedWidgetBuilder.h"
Public Member Functions
PROPERTYEDITOR_API FPropertyUpdatedWidgetBuilder ()
default constructor
PROPERTYEDITOR_API void Bind_IsRowHovered (TAttribute< bool > InIsRowHoveredAttr)
binds the IsRowHovered Attribute
PROPERTYEDITOR_API FPropertyUpdatedWidgetBuilder & Bind_IsVisible (TAttribute< EVisibility > InIsVisible)
Set the IsVisible delegate for the menu that this button is responsible for.
DECLARE_DELEGATE (FResetToDefault)
PROPERTYEDITOR_API FResetToDefault Get_ResetToDefault ()
returns the ResetToDefault delegate
PROPERTYEDITOR_API FPropertyUpdatedWidgetBuilder & Set_ResetToDefault (FResetToDefault InResetToDefault)
Sets the ResetToDefault delegate.
Data Fields
TAttribute< bool > IsRowHoveredAttr
If true, the row that this is associated with is currently hovered over.
Protected Attributes
TAttribute< EVisibility > IsVisible
the attribute which tells whether this menu button is visible
FResetToDefault ResetToDefault
A delegate for resetting the active property row.
Detailed Description
Definition at line 9 of file PropertyUpdatedWidgetBuilder.h.
Constructor & Destructor Documentation
FPropertyUpdatedWidgetBuilder()
PROPERTYEDITOR_API FPropertyUpdatedWidgetBuilder::FPropertyUpdatedWidgetBuilder ()
default constructor
Referenced by Bind_IsVisible(), and Set_ResetToDefault().
Member Function Documentation
Bind_IsRowHovered()
PROPERTYEDITOR_API void FPropertyUpdatedWidgetBuilder::Bind_IsRowHovered (TAttribute< bool > InIsRowHoveredAttr)
binds the IsRowHovered Attribute
Parameters
bInIsRowHoveredAttr the attribute which will determine if the row for this property is hovered
Bind_IsVisible()
PROPERTYEDITOR_API FPropertyUpdatedWidgetBuilder & FPropertyUpdatedWidgetBuilder::Bind_IsVisible (TAttribute< EVisibility > InIsVisible)
Set the IsVisible delegate for the menu that this button is responsible for.
References FPropertyUpdatedWidgetBuilder().
DECLARE_DELEGATE()
FPropertyUpdatedWidgetBuilder::DECLARE_DELEGATE (FResetToDefault)
Get_ResetToDefault()
PROPERTYEDITOR_API FResetToDefault FPropertyUpdatedWidgetBuilder::Get_ResetToDefault ()
returns the ResetToDefault delegate
Set_ResetToDefault()
PROPERTYEDITOR_API FPropertyUpdatedWidgetBuilder & FPropertyUpdatedWidgetBuilder::Set_ResetToDefault (FResetToDefault InResetToDefault)
Sets the ResetToDefault delegate.
Parameters
InResetToDefault the FResetToDefault delegate to set for this widget builder
References FPropertyUpdatedWidgetBuilder().
Field Documentation
IsRowHoveredAttr
TAttribute<bool> FPropertyUpdatedWidgetBuilder::IsRowHoveredAttr
If true, the row that this is associated with is currently hovered over.
Definition at line 47 of file PropertyUpdatedWidgetBuilder.h.
IsVisible
TAttribute<EVisibility> FPropertyUpdatedWidgetBuilder::IsVisible protected
the attribute which tells whether this menu button is visible
Definition at line 53 of file PropertyUpdatedWidgetBuilder.h.
ResetToDefault
FResetToDefault FPropertyUpdatedWidgetBuilder::ResetToDefault protected
A delegate for resetting the active property row.
Definition at line 58 of file PropertyUpdatedWidgetBuilder.h.
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/UserInterface/Widgets/PropertyUpdatedWidgetBuilder.h