Unreal Engine 5.6 C++ API: FDataflowEditorCommandsImpl Class Reference
FDataflowEditorCommandsImpl Class Reference
#include "DataflowEditorCommands.h"
Public Member Functions
FDataflowEditorCommandsImpl ()
FDataflowEditorCommandsImpl (const FDataflowEditorCommandsImpl &)=default
FDataflowEditorCommandsImpl (FDataflowEditorCommandsImpl &&)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS ~FDataflowEditorCommandsImpl ()=default
virtual void GetToolDefaultObjectList (TArray< UInteractiveTool * > &ToolCDOs) override
FDataflowEditorCommandsImpl & operator= (const FDataflowEditorCommandsImpl &)=default
FDataflowEditorCommandsImpl & operator= (FDataflowEditorCommandsImpl &&)=default
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void RegisterCommands () override
UE_DEPRECATED (5.5, "Dataflow Tool commands are now stored in FDataflowToolRegistry") const static FString BeginWeightMapPaintToolIdentifier
UE_DEPRECATED (5.5, "Dataflow Tool commands are now stored in FDataflowToolRegistry") TSharedPtr< FUICommandInfo > BeginWeightMapPaintTool
Static Public Member Functions
static void UpdateToolCommandBinding (UInteractiveTool *Tool, TSharedPtr< FUICommandList > UICommandList, bool bUnbind=false)
Add or remove commands relevant to Tool to the given UICommandList.
Data Fields
TSharedPtr< FUICommandInfo > AddNewSubGraph
TSharedPtr< FUICommandInfo > AddNewVariable
TSharedPtr< FUICommandInfo > AddOptionPin
TSharedPtr< FUICommandInfo > AddWeightMapNode
TSharedPtr< FUICommandInfo > ClearGraphCache
TSharedPtr< FUICommandInfo > ConvertToBasicSubGraph
TSharedPtr< FUICommandInfo > ConvertToForEachSubGraph
TSharedPtr< FUICommandInfo > CreateComment
TSharedPtr< FUICommandInfo > EvaluateGraph
TSharedPtr< FUICommandInfo > EvaluateGraphAutomatic
TSharedPtr< FUICommandInfo > EvaluateGraphManual
TSharedPtr< FUICommandInfo > EvaluateNode
TSharedPtr< FUICommandInfo > FreezeNodes
TSharedPtr< FUICommandInfo > PauseSimulationScene
TSharedPtr< FUICommandInfo > RebuildSimulationScene
TSharedPtr< FUICommandInfo > RemoveOptionPin
TMap< FName, TSharedPtr< FUICommandInfo > > SetConstructionViewModeCommands
TSharedPtr< FUICommandInfo > StartSimulationScene
TSharedPtr< FUICommandInfo > StepSimulationScene
TSharedPtr< FUICommandInfo > ToggleAsyncEvaluation
TSharedPtr< FUICommandInfo > ToggleEnabledState
TSharedPtr< FUICommandInfo > ToggleFaceSelection
TSharedPtr< FUICommandInfo > ToggleObjectSelection
TSharedPtr< FUICommandInfo > TogglePerfData
TSharedPtr< FUICommandInfo > ToggleVertexSelection
TSharedPtr< FUICommandInfo > UnfreezeNodes
TSharedPtr< FUICommandInfo > ZoomToFitGraph
Static Public Attributes
static const FString AddWeightMapNodeIdentifier
static const FString PauseSimulationSceneIdentifier
static const FString RebuildSimulationSceneIdentifier
static const FString StartSimulationSceneIdentifier
static const FString StepSimulationSceneIdentifier
Detailed Description
Definition at line 28 of file DataflowEditorCommands.h.
Constructor & Destructor Documentation
FDataflowEditorCommandsImpl() [1/3]
FDataflowEditorCommandsImpl::FDataflowEditorCommandsImpl ()
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by FDataflowEditorCommandsImpl(), FDataflowEditorCommandsImpl(), operator=(), and operator=().
~FDataflowEditorCommandsImpl()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FDataflowEditorCommandsImpl::~FDataflowEditorCommandsImpl () default
FDataflowEditorCommandsImpl() [2/3]
FDataflowEditorCommandsImpl::FDataflowEditorCommandsImpl (const FDataflowEditorCommandsImpl &) default
References FDataflowEditorCommandsImpl().
FDataflowEditorCommandsImpl() [3/3]
FDataflowEditorCommandsImpl::FDataflowEditorCommandsImpl (FDataflowEditorCommandsImpl &&) default
References FDataflowEditorCommandsImpl().
Member Function Documentation
GetToolDefaultObjectList()
virtual void FDataflowEditorCommandsImpl::GetToolDefaultObjectList (TArray< UInteractiveTool * > & ToolCDOs) inline override virtual
Definition at line 49 of file DataflowEditorCommands.h.
operator=() [1/2]
FDataflowEditorCommandsImpl & FDataflowEditorCommandsImpl::operator= (const FDataflowEditorCommandsImpl &) default
References FDataflowEditorCommandsImpl().
operator=() [2/2]
FDataflowEditorCommandsImpl & FDataflowEditorCommandsImpl::operator= (FDataflowEditorCommandsImpl &&) default
References FDataflowEditorCommandsImpl(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
RegisterCommands()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void FDataflowEditorCommandsImpl::RegisterCommands () override virtual
UE_DEPRECATED() [1/2]
FDataflowEditorCommandsImpl::UE_DEPRECATED (5. 5, "Dataflow Tool commands are now stored in FDataflowToolRegistry") const
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FDataflowEditorCommandsImpl::UE_DEPRECATED (5. 5, "Dataflow Tool commands are now stored in FDataflowToolRegistry")
References UE_DEPRECATED().
UpdateToolCommandBinding()
void FDataflowEditorCommandsImpl::UpdateToolCommandBinding (UInteractiveTool * Tool, TSharedPtr< FUICommandList > UICommandList, bool bUnbind = false) static
Add or remove commands relevant to Tool to the given UICommandList.
Call this when the active tool changes (eg on ToolManager.OnToolStarted / OnToolEnded)
Parameters
bUnbind if true, commands are removed, otherwise added
Field Documentation
AddNewSubGraph
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::AddNewSubGraph
Definition at line 75 of file DataflowEditorCommands.h.
AddNewVariable
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::AddNewVariable
Definition at line 74 of file DataflowEditorCommands.h.
AddOptionPin
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::AddOptionPin
Definition at line 71 of file DataflowEditorCommands.h.
AddWeightMapNode
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::AddWeightMapNode
Definition at line 88 of file DataflowEditorCommands.h.
AddWeightMapNodeIdentifier
const FString FDataflowEditorCommandsImpl::AddWeightMapNodeIdentifier static
Definition at line 87 of file DataflowEditorCommands.h.
ClearGraphCache
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ClearGraphCache
Definition at line 62 of file DataflowEditorCommands.h.
ConvertToBasicSubGraph
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ConvertToBasicSubGraph
Definition at line 76 of file DataflowEditorCommands.h.
ConvertToForEachSubGraph
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ConvertToForEachSubGraph
Definition at line 77 of file DataflowEditorCommands.h.
CreateComment
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::CreateComment
Definition at line 66 of file DataflowEditorCommands.h.
EvaluateGraph
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::EvaluateGraph
Definition at line 59 of file DataflowEditorCommands.h.
EvaluateGraphAutomatic
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::EvaluateGraphAutomatic
Definition at line 60 of file DataflowEditorCommands.h.
EvaluateGraphManual
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::EvaluateGraphManual
Definition at line 61 of file DataflowEditorCommands.h.
EvaluateNode
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::EvaluateNode
Definition at line 58 of file DataflowEditorCommands.h.
FreezeNodes
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::FreezeNodes
Definition at line 64 of file DataflowEditorCommands.h.
PauseSimulationScene
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::PauseSimulationScene
Definition at line 94 of file DataflowEditorCommands.h.
PauseSimulationSceneIdentifier
const FString FDataflowEditorCommandsImpl::PauseSimulationSceneIdentifier static
Definition at line 93 of file DataflowEditorCommands.h.
RebuildSimulationScene
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::RebuildSimulationScene
Definition at line 91 of file DataflowEditorCommands.h.
RebuildSimulationSceneIdentifier
const FString FDataflowEditorCommandsImpl::RebuildSimulationSceneIdentifier static
Definition at line 90 of file DataflowEditorCommands.h.
RemoveOptionPin
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::RemoveOptionPin
Definition at line 72 of file DataflowEditorCommands.h.
SetConstructionViewModeCommands
TMap<FName, TSharedPtr<FUICommandInfo> > FDataflowEditorCommandsImpl::SetConstructionViewModeCommands
Definition at line 80 of file DataflowEditorCommands.h.
StartSimulationScene
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::StartSimulationScene
Definition at line 97 of file DataflowEditorCommands.h.
StartSimulationSceneIdentifier
const FString FDataflowEditorCommandsImpl::StartSimulationSceneIdentifier static
Definition at line 96 of file DataflowEditorCommands.h.
StepSimulationScene
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::StepSimulationScene
Definition at line 100 of file DataflowEditorCommands.h.
StepSimulationSceneIdentifier
const FString FDataflowEditorCommandsImpl::StepSimulationSceneIdentifier static
Definition at line 99 of file DataflowEditorCommands.h.
ToggleAsyncEvaluation
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ToggleAsyncEvaluation
Definition at line 78 of file DataflowEditorCommands.h.
ToggleEnabledState
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ToggleEnabledState
Definition at line 67 of file DataflowEditorCommands.h.
ToggleFaceSelection
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ToggleFaceSelection
Definition at line 69 of file DataflowEditorCommands.h.
ToggleObjectSelection
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ToggleObjectSelection
Definition at line 68 of file DataflowEditorCommands.h.
TogglePerfData
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::TogglePerfData
Definition at line 63 of file DataflowEditorCommands.h.
ToggleVertexSelection
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ToggleVertexSelection
Definition at line 70 of file DataflowEditorCommands.h.
UnfreezeNodes
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::UnfreezeNodes
Definition at line 65 of file DataflowEditorCommands.h.
ZoomToFitGraph
TSharedPtr<FUICommandInfo> FDataflowEditorCommandsImpl::ZoomToFitGraph
Definition at line 73 of file DataflowEditorCommands.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Dataflow/Source/DataflowEditor/Public/Dataflow/DataflowEditorCommands.h