Unreal Engine 5.6 C++ API: FRamper Class Reference
FRamper Class Reference
#include "Ramper.h"
Public Types
typedef void(* FCallback) (void *)
typedef float Type
Public Member Functions
FRamper (float InNumRampCallsPerSecond=1.0f)
Type GetCurrent () const
float GetRampTimeMs () const
Type GetTarget () const
void Ramp ()
void SetRampTimeMs (float InNumRampCallsPerSecond, float InRampTimeMs, ERamperMode InMode)
void SetTarget (Type InTarget, FCallback InCallback=nullptr, void *InData=nullptr)
void SnapTo (Type InValue)
void SnapToTarget ()
Private Member Functions
void ExponentialRamp ()
void LinearRamp ()
void LogRamp ()
void SetTargetExponential (float InTarget, FCallback InCallback=nullptr, void *InData=nullptr)
void SetTargetLinear (Type InTarget, FCallback InCallback, void *InData)
void SetTargetLog (Type InTarget, FCallback InCallback, void *InData)
Private Attributes
FCallback Callback
Type Current
void * Data
Type Increment
volatile bool IsSettingTarget
ERamperMode Mode
Type Multiplier
Type NormalIncrement
float NumRampCallsPerSecond
Type Target
Detailed Description
Definition at line 16 of file Ramper.h.
Member Typedef Documentation
FCallback
typedef void(* FRamper::FCallback) (void *)
Definition at line 20 of file Ramper.h.
Type
typedef float FRamper::Type
Definition at line 21 of file Ramper.h.
Constructor & Destructor Documentation
FRamper()
FRamper::FRamper (float InNumRampCallsPerSecond = 1.0f) inline
Definition at line 23 of file Ramper.h.
References Callback, Current, IsSettingTarget, Linear, NumRampCallsPerSecond, SetRampTimeMs(), SetTarget(), and SnapToTarget().
Member Function Documentation
ExponentialRamp()
void FRamper::ExponentialRamp () inline private
Definition at line 275 of file Ramper.h.
References Current, IsSettingTarget, Multiplier, SnapToTarget(), and Target.
Referenced by Ramp().
GetCurrent()
Type FRamper::GetCurrent () const inline
Definition at line 72 of file Ramper.h.
References Current.
GetRampTimeMs()
float FRamper::GetRampTimeMs () const inline
Definition at line 42 of file Ramper.h.
References NormalIncrement, and NumRampCallsPerSecond.
Referenced by SetTargetLog().
GetTarget()
Type FRamper::GetTarget () const inline
Definition at line 73 of file Ramper.h.
References Target.
LinearRamp()
void FRamper::LinearRamp () inline private
Definition at line 139 of file Ramper.h.
References Current, Increment, IsSettingTarget, SnapToTarget(), and Target.
Referenced by Ramp().
LogRamp()
void FRamper::LogRamp () inline private
Definition at line 205 of file Ramper.h.
References Current, IsSettingTarget, Multiplier, SnapToTarget(), and Target.
Referenced by Ramp().
Ramp()
void FRamper::Ramp () inline
Definition at line 75 of file Ramper.h.
References checkNoEntry, Exp, ExponentialRamp(), Linear, LinearRamp(), Log, LogRamp(), and Mode.
SetRampTimeMs()
void FRamper::SetRampTimeMs (float InNumRampCallsPerSecond, float InRampTimeMs, ERamperMode InMode) inline
Definition at line 34 of file Ramper.h.
References Mode, NormalIncrement, and NumRampCallsPerSecond.
Referenced by FRamper().
SetTarget()
void FRamper::SetTarget (Type InTarget, FCallback InCallback = nullptr, void * InData = nullptr) inline
Definition at line 47 of file Ramper.h.
References checkNoEntry, Exp, Linear, Log, Mode, SetTargetExponential(), SetTargetLinear(), and SetTargetLog().
Referenced by FRamper(), and SnapTo().
SetTargetExponential()
void FRamper::SetTargetExponential (float InTarget, FCallback InCallback = nullptr, void * InData = nullptr) inline private
Definition at line 248 of file Ramper.h.
References Callback, Current, Data, IsSettingTarget, Multiplier, NormalIncrement, and Target.
Referenced by SetTarget().
SetTargetLinear()
void FRamper::SetTargetLinear (Type InTarget, FCallback InCallback, void * InData) inline private
Definition at line 120 of file Ramper.h.
References Callback, check, Current, Data, Increment, IsSettingTarget, NormalIncrement, and Target.
Referenced by SetTarget().
SetTargetLog()
void FRamper::SetTargetLog (Type InTarget, FCallback InCallback, void * InData) inline private
Definition at line 182 of file Ramper.h.
References Callback, check, Current, Data, GetRampTimeMs(), IsSettingTarget, FMath::Log2(), Multiplier, NumRampCallsPerSecond, and Target.
Referenced by SetTarget().
SnapTo()
void FRamper::SnapTo (Type InValue) inline
Definition at line 66 of file Ramper.h.
References SetTarget(), and SnapToTarget().
SnapToTarget()
void FRamper::SnapToTarget () inline
Definition at line 93 of file Ramper.h.
References Callback, Current, Data, Increment, IsSettingTarget, Multiplier, and Target.
Referenced by FRamper(), ExponentialRamp(), LinearRamp(), LogRamp(), and SnapTo().
Field Documentation
Callback
FCallback FRamper::Callback private
Definition at line 334 of file Ramper.h.
Referenced by FRamper(), SetTargetExponential(), SetTargetLinear(), SetTargetLog(), and SnapToTarget().
Current
Type FRamper::Current private
Definition at line 322 of file Ramper.h.
Referenced by FRamper(), ExponentialRamp(), GetCurrent(), LinearRamp(), LogRamp(), SetTargetExponential(), SetTargetLinear(), SetTargetLog(), and SnapToTarget().
Data
void* FRamper::Data private
Definition at line 335 of file Ramper.h.
Referenced by SetTargetExponential(), SetTargetLinear(), SetTargetLog(), and SnapToTarget().
Increment
Type FRamper::Increment private
Definition at line 326 of file Ramper.h.
Referenced by LinearRamp(), SetTargetLinear(), and SnapToTarget().
IsSettingTarget
volatile bool FRamper::IsSettingTarget private
Definition at line 332 of file Ramper.h.
Referenced by FRamper(), ExponentialRamp(), LinearRamp(), LogRamp(), SetTargetExponential(), SetTargetLinear(), SetTargetLog(), and SnapToTarget().
Mode
ERamperMode FRamper::Mode private
Definition at line 324 of file Ramper.h.
Referenced by Ramp(), SetRampTimeMs(), and SetTarget().
Multiplier
Type FRamper::Multiplier private
Definition at line 329 of file Ramper.h.
Referenced by ExponentialRamp(), LogRamp(), SetTargetExponential(), SetTargetLog(), and SnapToTarget().
NormalIncrement
Type FRamper::NormalIncrement private
Definition at line 327 of file Ramper.h.
Referenced by GetRampTimeMs(), SetRampTimeMs(), SetTargetExponential(), and SetTargetLinear().
NumRampCallsPerSecond
float FRamper::NumRampCallsPerSecond private
Definition at line 331 of file Ramper.h.
Referenced by FRamper(), GetRampTimeMs(), SetRampTimeMs(), and SetTargetLog().
Target
Type FRamper::Target private
Definition at line 323 of file Ramper.h.
Referenced by ExponentialRamp(), GetTarget(), LinearRamp(), LogRamp(), SetTargetExponential(), SetTargetLinear(), SetTargetLog(), and SnapToTarget().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixDsp/Public/HarmonixDsp/Ramper.h