Unreal Engine 5.6 C++ API: FSlateStyleRegistry Class Reference
FSlateStyleRegistry Class Reference
A central repository that can be used to track and manage chunks of slate style data.
#include "SlateStyleRegistry.h"
Static Public Member Functions
static const ISlateStyle * FindSlateStyle (const FName &InSlateStyleName)
Find a slate style in the repository.
static void GetAllResources (TArray< const FSlateBrush * > &OutResources)
Populate an array of slate brushes with all of the resources used by the registered styles.
static TArray< FName > GetSylesUsingBrush (const FName BrushName)
Gets the names of every style entry using a brush Note: this function is expensive and is not designed to be used in performance critical situations.
static bool IterateAllStyles (const TFunctionRef< bool(const ISlateStyle &)> &Iter)
Iterate all the slate style known to this registry.
static void RegisterSlateStyle (const ISlateStyle &InSlateStyle)
Add a slate style to the repository.
static void UnRegisterSlateStyle (const FName StyleSetName)
Removes a slate style from the repository (by name).
static void UnRegisterSlateStyle (const ISlateStyle &InSlateStyle)
Remove a slate style from the repository.
Static Private Attributes
static TMap< FName, const ISlateStyle * > SlateStyleRepository
Repository is just a collection of shared style pointers.
Detailed Description
A central repository that can be used to track and manage chunks of slate style data.
Definition at line 13 of file SlateStyleRegistry.h.
Member Function Documentation
FindSlateStyle()
const ISlateStyle * FSlateStyleRegistry::FindSlateStyle (const FName & InSlateStyleName) static
Find a slate style in the repository.
Parameters
InSlateStyleName The name of the slate style to find.
Returns
The slate style, or null if it couldn't be found
Referenced by SAudioRadialSlider::SLATE_BEGIN_ARGS(), SAudioSliderBase::SLATE_BEGIN_ARGS(), and SAudioTextBox::SLATE_BEGIN_ARGS().
GetAllResources()
void FSlateStyleRegistry::GetAllResources (TArray< const FSlateBrush * > & OutResources) static
Populate an array of slate brushes with all of the resources used by the registered styles.
Parameters
OutResources Array of slate brushes to populate.
GetSylesUsingBrush()
TArray< FName > FSlateStyleRegistry::GetSylesUsingBrush (const FName BrushName) static
Gets the names of every style entry using a brush Note: this function is expensive and is not designed to be used in performance critical situations.
Parameters
BrushName The name of the brush to find style entries from
Returns
Array of style names using the brush
IterateAllStyles()
bool FSlateStyleRegistry::IterateAllStyles (const TFunctionRef< bool(const ISlateStyle &)> & Iter) static
Iterate all the slate style known to this registry.
Parameters
Iter A predicate to call for each known style that returns true to continue iteration, and false to terminate iteration
Returns
true where to loop completed, of false if it was terminated by the predicate
RegisterSlateStyle()
void FSlateStyleRegistry::RegisterSlateStyle (const ISlateStyle & InSlateStyle) static
Add a slate style to the repository.
Parameters
ISlateStyle interface to a user-definable style to add.
Referenced by FRigVMEditorStyle::Register().
UnRegisterSlateStyle() [1/2]
void FSlateStyleRegistry::UnRegisterSlateStyle (const FName StyleSetName) static
Removes a slate style from the repository (by name).
Parameters
StyleSetName The name of the style set to remove.
UnRegisterSlateStyle() [2/2]
void FSlateStyleRegistry::UnRegisterSlateStyle (const ISlateStyle & InSlateStyle) static
Remove a slate style from the repository.
Parameters
ISlateStyle Interface to the style to remove.
Referenced by FRigVMEditorStyle::Unregister().
Field Documentation
SlateStyleRepository
TMap<FName, const ISlateStyle*> FSlateStyleRegistry::SlateStyleRepository static private
Repository is just a collection of shared style pointers.
Definition at line 73 of file SlateStyleRegistry.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Styling/SlateStyleRegistry.h