Unreal Engine 5.6 C++ API: FShaderCompilerFlags Class Reference
FShaderCompilerFlags Class Reference
#include "ShaderCore.h"
Public Member Functions
FShaderCompilerFlags (uint64 InData=0)
void Add (uint32 InFlag)
void Append (const FShaderCompilerFlags &In)
bool Contains (uint32 InFlag) const
uint64 GetData () const
void Iterate (TFunction< void(uint32)> Callback) const
void Remove (uint32 InFlag)
Private Attributes
uint64 Data
Friends
FArchive & operator<< (FArchive &Ar, FShaderCompilerFlags &F)
Detailed Description
Definition at line 398 of file ShaderCore.h.
Constructor & Destructor Documentation
FShaderCompilerFlags()
FShaderCompilerFlags::FShaderCompilerFlags (uint64 InData = 0) inline
Definition at line 401 of file ShaderCore.h.
References Data.
Referenced by Append(), and operator<<.
Member Function Documentation
Add()
void FShaderCompilerFlags::Add (uint32 InFlag) inline
Definition at line 411 of file ShaderCore.h.
References Data.
Referenced by FCopyTextureCS::ModifyCompilationEnvironment(), FUpdateTextureShaderBase::ModifyCompilationEnvironment(), and TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds >::ModifyCompilationEnvironment().
Append()
void FShaderCompilerFlags::Append (const FShaderCompilerFlags & In) inline
Definition at line 406 of file ShaderCore.h.
References FShaderCompilerFlags(), and Data.
Contains()
bool FShaderCompilerFlags::Contains (uint32 InFlag) const inline
Definition at line 423 of file ShaderCore.h.
References Data.
GetData()
uint64 FShaderCompilerFlags::GetData () const inline
Definition at line 450 of file ShaderCore.h.
References Data.
Iterate()
void FShaderCompilerFlags::Iterate (TFunction< void(uint32)> Callback) const inline
Definition at line 429 of file ShaderCore.h.
References Data.
Remove()
void FShaderCompilerFlags::Remove (uint32 InFlag) inline
Definition at line 417 of file ShaderCore.h.
References Data.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderCompilerFlags & F) friend
Definition at line 444 of file ShaderCore.h.
References FShaderCompilerFlags(), Ar, and Data.
Field Documentation
Data
uint64 FShaderCompilerFlags::Data private
Definition at line 456 of file ShaderCore.h.
Referenced by FShaderCompilerFlags(), Add(), Append(), Contains(), GetData(), Iterate(), operator<<, and Remove().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderCore.h