Unreal Engine 5.6 C++ API: TSharedPtr< ObjectType, InMode > Class Template Reference
TSharedPtr< ObjectType, InMode > Class Template Reference
TSharedPtr is a non-intrusive reference-counted authoritative object pointer.
#include "SharedPointer.h"
Public Types
using ElementType = ObjectType
using IntrusiveUnsetOptionalStateType = TSharedPtr
Public Member Functions
TSharedPtr (FIntrusiveUnsetOptionalState)
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr (OtherType *InObject)
Constructs a shared pointer that owns the specified object.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedPtr (OtherType *InObject, DeleterType &&InDeleter)
Constructs a shared pointer that owns the specified object.
FORCEINLINE TSharedPtr (SharedPointerInternals::FNullTag *=nullptr)
Constructs an empty shared pointer.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr (SharedPointerInternals::TRawPtrProxy< OtherType > const &InRawPtrProxy)
Constructs a shared pointer using a proxy reference to a raw pointer.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedPtr (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > &&InRawPtrProxy)
Constructs a shared pointer using a proxy reference to a raw pointer.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedPtr (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const &InRawPtrProxy)
Constructs a shared pointer using a proxy reference to a raw pointer.
FORCEINLINE TSharedPtr (TSharedPtr &&InSharedPtr)
FORCEINLINE TSharedPtr (TSharedPtr const &InSharedPtr)
template<typename OtherType>
FORCEINLINE TSharedPtr (TSharedPtr< OtherType, Mode > &&OtherSharedPtr, ObjectType *InObject)
Aliasing constructor used to create a shared pointer which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr (TSharedPtr< OtherType, Mode > const &InSharedPtr)
Constructs a shared pointer as a shared reference to an existing shared pointer's object.
template<typename OtherType>
FORCEINLINE TSharedPtr (TSharedPtr< OtherType, Mode > const &InSharedPtr, SharedPointerInternals::FConstCastTag)
Special constructor used internally to cast a 'const' shared pointer a 'mutable' pointer.
template<typename OtherType>
FORCEINLINE TSharedPtr (TSharedPtr< OtherType, Mode > const &InSharedPtr, SharedPointerInternals::FStaticCastTag)
Special constructor used internally to statically cast one shared pointer type to another.
template<typename OtherType>
FORCEINLINE TSharedPtr (TSharedPtr< OtherType, Mode > const &OtherSharedPtr, ObjectType *InObject)
Aliasing constructor used to create a shared pointer which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr (TSharedRef< OtherType, Mode > const &InSharedRef)
Implicitly converts a shared reference to a shared pointer, adding a reference to the object.
template<typename OtherType>
FORCEINLINE TSharedPtr (TSharedRef< OtherType, Mode > const &OtherSharedRef, ObjectType *InObject)
Aliasing constructor used to create a shared pointer which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
FORCEINLINE ObjectType * Get () const
Returns the object referenced by this pointer, or nullptr if no object is reference.
FORCEINLINE int32 GetSharedReferenceCount () const
Returns the number of shared references to this object (including this reference.) IMPORTANT: Not necessarily fast!
FORCEINLINE bool IsUnique () const
Returns true if this is the only shared reference to this object.
FORCEINLINE const bool IsValid () const
Checks to see if this shared pointer is actually pointing to an object.
FORCEINLINE operator bool () const
Checks to see if this shared pointer is actually pointing to an object.
template<typename DummyObjectType = ObjectType UE_REQUIRES(UE_REQUIRES_EXPR(*(DummyObjectType*)nullptr))>
FORCEINLINE DummyObjectType & operator* () const
Dereference operator returns a reference to the object this shared pointer points to.
FORCEINLINE ObjectType * operator-> () const
Arrow operator returns a pointer to the object this shared pointer references.
FORCEINLINE TSharedPtr & operator= (SharedPointerInternals::FNullTag *)
Assignment to a nullptr pointer.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr & operator= (SharedPointerInternals::TRawPtrProxy< OtherType > const &InRawPtrProxy)
Assignment operator replaces this shared pointer with the specified shared pointer.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedPtr & operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > &&InRawPtrProxy)
Assignment operator replaces this shared pointer with the specified shared pointer.
template<typename OtherType, typename DeleterType UE_REQUIRES>
FORCEINLINE TSharedPtr & operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const &InRawPtrProxy)
Assignment operator replaces this shared pointer with the specified shared pointer.
FORCEINLINE TSharedPtr & operator= (TSharedPtr &&InSharedPtr)
FORCEINLINE TSharedPtr & operator= (TSharedPtr const &InSharedPtr)
Assignment operator replaces this shared pointer with the specified shared pointer.
bool operator== (FIntrusiveUnsetOptionalState) const
FORCEINLINE void Reset ()
Resets this shared pointer, removing a reference to the object.
FORCEINLINE TSharedRef< ObjectType, Mode > ToSharedRef () &&
Converts a shared pointer to a shared reference.
FORCEINLINE TSharedRef< ObjectType, Mode > ToSharedRef () const &
Converts a shared pointer to a shared reference.
FORCEINLINE TWeakPtr< ObjectType, Mode > ToWeakPtr () const
Converts a shared pointer to a weak ptr.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
static constexpr ESPMode Mode = InMode
Private Member Functions
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr (TWeakPtr< OtherType, Mode > &&InWeakPtr)
Constructs a shared pointer from a weak pointer, allowing you to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the shared pointer will not be valid.
template<typename OtherType UE_REQUIRES>
FORCEINLINE TSharedPtr (TWeakPtr< OtherType, Mode > const &InWeakPtr)
Constructs a shared pointer from a weak pointer, allowing you to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the shared pointer will not be valid.
Private Attributes
ObjectType * Object
The object we're holding a reference to.
SharedPointerInternals::FSharedReferencer< Mode > SharedReferenceCount
Interface to the reference counter for this object.
Friends
template<class OtherType, ESPMode OtherMode>
class TSharedPtr
template<class OtherType, ESPMode OtherMode>
class TSharedFromThis
template<class OtherType, ESPMode OtherMode>
class TSharedRef
template<class OtherType, ESPMode OtherMode>
class TWeakPtr
Detailed Description
template<class ObjectType, ESPMode InMode>
class TSharedPtr< ObjectType, InMode >
TSharedPtr is a non-intrusive reference-counted authoritative object pointer.
This shared pointer will be conditionally thread-safe when the optional Mode template argument is set to ThreadSafe.
Definition at line 664 of file SharedPointer.h.
Member Typedef Documentation
ElementType
template<class ObjectType, ESPMode InMode> using TSharedPtr< ObjectType, InMode >::ElementType = ObjectType
Definition at line 667 of file SharedPointer.h.
IntrusiveUnsetOptionalStateType
template<class ObjectType, ESPMode InMode> using TSharedPtr< ObjectType, InMode >::IntrusiveUnsetOptionalStateType = TSharedPtr
Definition at line 1122 of file SharedPointer.h.
Constructor & Destructor Documentation
TSharedPtr() [1/18]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (SharedPointerInternals::FNullTag * = nullptr) inline
Constructs an empty shared pointer.
Definition at line 674 of file SharedPointer.h.
TSharedPtr() [2/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (OtherType * InObject) inline explicit
Constructs a shared pointer that owns the specified object.
Note that passing nullptr here will still create a tracked reference to a nullptr pointer. (Consistent with std::shared_ptr)
Parameters
InObject Object this shared pointer to retain a reference to
Definition at line 690 of file SharedPointer.h.
TSharedPtr() [3/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (OtherType * InObject, DeleterType && InDeleter) inline
Constructs a shared pointer that owns the specified object.
Note that passing nullptr here will still create a tracked reference to a nullptr pointer. (Consistent with std::shared_ptr)
Parameters
InObject Object this shared pointer to retain a reference to
InDeleter Deleter object used to destroy the object when it is no longer referenced.
Definition at line 711 of file SharedPointer.h.
TSharedPtr() [4/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (SharedPointerInternals::TRawPtrProxy< OtherType > const & InRawPtrProxy) inline
Constructs a shared pointer using a proxy reference to a raw pointer.
(See MakeShareable())
Parameters
InRawPtrProxy Proxy raw pointer that contains the object that the new shared pointer will reference
Definition at line 730 of file SharedPointer.h.
TSharedPtr() [5/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const & InRawPtrProxy) inline
Constructs a shared pointer using a proxy reference to a raw pointer.
(See MakeShareable())
Parameters
InRawPtrProxy Proxy raw pointer that contains the object that the new shared pointer will reference
Definition at line 750 of file SharedPointer.h.
TSharedPtr() [6/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > && InRawPtrProxy) inline
Constructs a shared pointer using a proxy reference to a raw pointer.
(See MakeShareable())
Parameters
InRawPtrProxy Proxy raw pointer that contains the object that the new shared pointer will reference
Definition at line 770 of file SharedPointer.h.
TSharedPtr() [7/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< OtherType, Mode > const & InSharedPtr) inline
Constructs a shared pointer as a shared reference to an existing shared pointer's object.
This constructor is needed so that we can implicitly upcast to base classes.
Parameters
InSharedPtr The shared pointer whose object we should create an additional reference to
Definition at line 789 of file SharedPointer.h.
TSharedPtr() [8/18]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< ObjectType, InMode > const & InSharedPtr) inline
Definition at line 795 of file SharedPointer.h.
TSharedPtr() [9/18]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< ObjectType, InMode > && InSharedPtr) inline
Definition at line 801 of file SharedPointer.h.
TSharedPtr() [10/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedRef< OtherType, Mode > const & InSharedRef) inline
Implicitly converts a shared reference to a shared pointer, adding a reference to the object.
NOTE: We allow an implicit conversion from TSharedRef to TSharedPtr because it's always a safe conversion.
Parameters
InSharedRef The shared reference that will be converted to a shared pointer
Definition at line 819 of file SharedPointer.h.
TSharedPtr() [11/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< OtherType, Mode > const & InSharedPtr, SharedPointerInternals::FStaticCastTag) inline
Special constructor used internally to statically cast one shared pointer type to another.
You should never call this constructor directly. Instead, use the StaticCastSharedPtr() function. This constructor creates a shared pointer as a shared reference to an existing shared pointer after statically casting that pointer's object. This constructor is needed for static casts.
Parameters
InSharedPtr The shared pointer whose object we should create an additional reference to
Definition at line 836 of file SharedPointer.h.
TSharedPtr() [12/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< OtherType, Mode > const & InSharedPtr, SharedPointerInternals::FConstCastTag) inline
Special constructor used internally to cast a 'const' shared pointer a 'mutable' pointer.
You should never call this constructor directly. Instead, use the ConstCastSharedPtr() function. This constructor creates a shared pointer as a shared reference to an existing shared pointer after const casting that pointer's object. This constructor is needed for const casts.
Parameters
InSharedPtr The shared pointer whose object we should create an additional reference to
Definition at line 851 of file SharedPointer.h.
TSharedPtr() [13/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< OtherType, Mode > const & OtherSharedPtr, ObjectType * InObject) inline
Aliasing constructor used to create a shared pointer which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
Parameters
OtherSharedPtr The shared pointer whose reference count should be shared.
InObject The object pointer to use (instead of the incoming shared pointer's object)
Definition at line 865 of file SharedPointer.h.
TSharedPtr() [14/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedPtr< OtherType, Mode > && OtherSharedPtr, ObjectType * InObject) inline
Aliasing constructor used to create a shared pointer which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
Parameters
OtherSharedPtr The shared pointer whose reference count should be shared.
InObject The object pointer to use (instead of the incoming shared pointer's object)
Definition at line 879 of file SharedPointer.h.
TSharedPtr() [15/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TSharedRef< OtherType, Mode > const & OtherSharedRef, ObjectType * InObject) inline
Aliasing constructor used to create a shared pointer which shares its reference count with another shared object, but pointing to a different object, typically a subobject.
Parameters
OtherSharedRef The shared reference whose reference count should be shared.
InObject The object pointer to use (instead of the incoming shared pointer's object)
Definition at line 894 of file SharedPointer.h.
TSharedPtr() [16/18]
template<class ObjectType, ESPMode InMode> TSharedPtr< ObjectType, InMode >::TSharedPtr (FIntrusiveUnsetOptionalState) inline explicit
Definition at line 1124 of file SharedPointer.h.
TSharedPtr() [17/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TWeakPtr< OtherType, Mode > const & InWeakPtr) inline explicit private
Constructs a shared pointer from a weak pointer, allowing you to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the shared pointer will not be valid.
You should always check to make sure this shared pointer is valid before trying to dereference the shared pointer!
NOTE: This constructor is private to force users to be explicit when converting a weak pointer to a shared pointer. Use the weak pointer's Pin() method instead!
Definition at line 1150 of file SharedPointer.h.
TSharedPtr() [18/18]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr< ObjectType, InMode >::TSharedPtr (TWeakPtr< OtherType, Mode > && InWeakPtr) inline explicit private
Constructs a shared pointer from a weak pointer, allowing you to access the object (if it hasn't expired yet.) Remember, if there are no more shared references to the object, the shared pointer will not be valid.
You should always check to make sure this shared pointer is valid before trying to dereference the shared pointer!
NOTE: This constructor is private to force users to be explicit when converting a weak pointer to a shared pointer. Use the weak pointer's Pin() method instead!
Definition at line 1175 of file SharedPointer.h.
Member Function Documentation
Get()
template<class ObjectType, ESPMode InMode> FORCEINLINE ObjectType * TSharedPtr< ObjectType, InMode >::Get () const inline nodiscard
Returns the object referenced by this pointer, or nullptr if no object is reference.
Returns
The object owned by this shared pointer, or nullptr
Definition at line 1035 of file SharedPointer.h.
Referenced by UE::Sequencer::TViewModelPtr< FViewModel >::TViewModelPtr(), FSlateCachedElementData::AddCachedElement(), FToolCommandChangeSequence::Apply(), UE::MovieScene::TPreAnimatedPropertyStorageImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::CachePreAnimatedValues(), Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs(), FSequencerKeyStructGenerator::CreateKeyStructInstance(), TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::DebugDump(), TListTypeTraits< TSharedPtr< T, ESPMode::ThreadSafe > >::DebugDump(), TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::DebugDump(), DECLARE_MULTICAST_DELEGATE_TwoParams(), TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute(), FStreamableHandle::FindOrAddContextData(), FRPCDoSDetection::FindOrAddRPCTracking(), TStateTreeInstanceDataStructRef< T >::GetPtr(), GetTypeHash(), UE::Sequencer::HotspotCast(), UE::MovieScene::TPlaybackCapabilityInterfaceCast< TSharedPtr< PointedType > >::InterfaceCast(), UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeStateDataAsReplayData(), SRigVMActionMenu::OnCreateWidgetForAction(), operator!=(), operator!=(), operator!=(), operator!=(), operator<<(), UE::Sequencer::TViewModelPtr< FViewModel >::operator=(), operator==(), operator==(), operator==(), operator==(), UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Push(), FToolCommandChangeSequence::Revert(), FBoneContainer::SetRefPoseOverride(), IDetailTreeNode::UE_DEPRECATED(), FScopedSkeletalMeshRenderData::USkeletalMesh, USTRUCT(), UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitAllocation(), and UE::MovieScene::TInitialValueProcessorImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... > >::VisitAllocationCached().
GetSharedReferenceCount()
template<class ObjectType, ESPMode InMode> FORCEINLINE int32 TSharedPtr< ObjectType, InMode >::GetSharedReferenceCount () const inline nodiscard
Returns the number of shared references to this object (including this reference.) IMPORTANT: Not necessarily fast!
Should only be used for debugging purposes!
Returns
Number of shared references to the object (including this reference.)
Definition at line 1101 of file SharedPointer.h.
IsUnique()
template<class ObjectType, ESPMode InMode> FORCEINLINE bool TSharedPtr< ObjectType, InMode >::IsUnique () const inline nodiscard
Returns true if this is the only shared reference to this object.
Note that there may be outstanding weak references left. IMPORTANT: Not necessarily fast! Should only be used for debugging purposes!
Returns
True if there is only one shared reference to the object, and this is it!
Definition at line 1113 of file SharedPointer.h.
IsValid()
template<class ObjectType, ESPMode InMode> FORCEINLINE const bool TSharedPtr< ObjectType, InMode >::IsValid () const inline nodiscard
Checks to see if this shared pointer is actually pointing to an object.
Returns
True if the shared pointer is valid and can be dereferenced
Definition at line 1055 of file SharedPointer.h.
Referenced by UE::Insights::FFilterWithSuggestions::FFilterWithSuggestions(), FMetasoundParameterStorageWrapper::FMetasoundParameterStorageWrapper(), UE::SequenceNavigator::FNavigationToolItemFlagGuard::FNavigationToolItemFlagGuard(), FPropertyTrackEditor< TrackType >::~FPropertyTrackEditor(), UE::Net::TStructNetTokenDataStoreHelper< T >::AddStateToReplayExportGroup(), FToolCommandChangeSequence::Apply(), TWeakChild< ChildType >::AttachWidget(), FTabPayload_UObject::CastChecked(), SMultiColumnTableRow< ItemType >::Construct(), TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::DebugDump(), TListTypeTraits< TSharedPtr< T, ESPMode::ThreadSafe > >::DebugDump(), TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), TBaseSPMethodDelegateInstance< bConst, UserClass, SPMode, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute(), FMediaIOCoreSampleContainer< SampleType >::FetchSample(), UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType(), UE::SequenceNavigator::INavigationToolItem::FindAncestorOfType(), UE::SequenceNavigator::INavigationToolItem::FindAncestorsOfType(), FStructOnScopeStructureDataProvider::FindBaseStructure(), UE::SequenceNavigator::INavigationTool::FindOrAdd(), FStreamableHandle::FindOrAddContextData(), FRPCDoSDetection::FindOrAddRPCTracking(), UE::SequenceNavigator::INavigationToolItem::FindPath(), UE::SequenceNavigator::INavigationToolItem::FindValidChildren(), SListView< TSharedPtr< FString > >::GeneratePinnedWidgetForItem(), SListView< TSharedPtr< FString > >::GenerateWidgetForItem(), FShaderPlatformCachedIniValue< Type >::Get(), TWeakChild< ChildType >::GetChildRefAt(), TWeakChild< ChildType >::GetChildRefAt(), FSlateApplication::GetCursorUser(), FSlateApplication::GetCursorUser(), FLocMetadataObject::GetField(), FArguments< ItemType >::GetForegroundBasedOnSelection(), UE::SequenceNavigator::INavigationToolItem::GetFullPath(), TTypeContainer< Mode >::GetInstance(), UE::SequenceNavigator::INavigationToolItem::GetItemTreeHeight(), FMediaIOCoreSampleContainer< SampleType >::GetNextSampleTime(), UE::SequenceNavigator::INavigationTool::GetOrCreateItemProxy(), UE::SequenceNavigator::INavigationToolItem::GetParents(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), FRigVMGraphMathTypeDetailCustomization::GetPropertyChain(), SNodePanel::SNode::GetRelativeLayoutScale(), UE::Net::TStructNetTokenDataStoreHelper< T >::GetStateFromReplayExportGroup(), TWeakChild< ChildType >::GetWidget(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetWidget(), FWorkspaceItem::HasChildrenIn(), FLocMetadataObject::HasField(), StatelessConnectHandlerComponent::HasPassedChallenge(), FLocMetadataObject::HasTypedField(), TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::IsPtrValid(), TListTypeTraits< TSharedPtr< T, ESPMode::ThreadSafe > >::IsPtrValid(), TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::IsPtrValid(), TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::IsPtrValid(), UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeStateDataAsReplayData(), SRigVMActionMenu::OnCreateWidgetForAction(), SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), FResetToDefaultOverride::OnResetToDefaultClicked(), operator!=(), operator!=(), operator!=(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator*(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator->(), operator==(), operator==(), operator==(), SListView< TSharedPtr< FString > >::Private_SetItemSelection(), UE::Sequencer::FInputHandlerStack::ProcessReply(), FFbxSceneInfo::RecursiveFindLODParentNode(), TCommands< CommandContextType >::Register(), TInteractiveToolCommands< CommandContextType >::RegisterCommands(), UE::Insights::FBaseTreeNode::RemoveFromParent(), UE::Insights::FBaseTreeNode::RemoveFromParentSwap(), FToolCommandChangeSequence::Revert(), STileView< ItemType >::ScrollIntoView(), UE::Net::TStructNetTokenDataStoreHelper< T >::SerializeHelper(), FSlateShapedTextElement::SetOverflowArgs(), UE::Net::TStructNetTokenDataStoreHelper< T >::SetupReplayExportGroup(), SRigVMBulkEditDialog< InWidgetType >::ShowNormal(), FQuartzSubscriptionToken::Subscribe(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::ToSharedRef(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::ToSharedRef(), Metasound::Frontend::FMetasoundAnalyzerView::TryGetOutputData(), FDeferredCleanupSlateBrush::TrySlateBrush(), and FQuartzSubscriptionToken::Unsubscribe().
operator bool()
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr< ObjectType, InMode >::operator bool () const inline explicit nodiscard
Checks to see if this shared pointer is actually pointing to an object.
Returns
True if the shared pointer is valid and can be dereferenced
Definition at line 1045 of file SharedPointer.h.
operator*()
template<class ObjectType, ESPMode InMode> template<typename DummyObjectType = ObjectType UE_REQUIRES(UE_REQUIRES_EXPR(*(DummyObjectType*)nullptr))> FORCEINLINE DummyObjectType & TSharedPtr< ObjectType, InMode >::operator* () const inline nodiscard
Dereference operator returns a reference to the object this shared pointer points to.
Returns
Reference to the object
Definition at line 1069 of file SharedPointer.h.
operator->()
template<class ObjectType, ESPMode InMode> FORCEINLINE ObjectType * TSharedPtr< ObjectType, InMode >::operator-> () const inline nodiscard
Arrow operator returns a pointer to the object this shared pointer references.
Returns
Returns a pointer to the object referenced by this shared pointer
Definition at line 1080 of file SharedPointer.h.
operator=() [1/6]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr & TSharedPtr< ObjectType, InMode >::operator= (SharedPointerInternals::FNullTag *) inline
Assignment to a nullptr pointer.
The object currently referenced by this shared pointer will no longer be referenced and will be deleted if there are no other referencers.
Definition at line 905 of file SharedPointer.h.
operator=() [2/6]
template<class ObjectType, ESPMode InMode> template<typename OtherType UE_REQUIRES> FORCEINLINE TSharedPtr & TSharedPtr< ObjectType, InMode >::operator= (SharedPointerInternals::TRawPtrProxy< OtherType > const & InRawPtrProxy) inline
Assignment operator replaces this shared pointer with the specified shared pointer.
The object currently referenced by this shared pointer will no longer be referenced and will be deleted if there are no other referencers.
Parameters
InRawPtrProxy Proxy object used to assign the object (see MakeShareable helper function)
Definition at line 948 of file SharedPointer.h.
operator=() [3/6]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedPtr & TSharedPtr< ObjectType, InMode >::operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > && InRawPtrProxy) inline
Assignment operator replaces this shared pointer with the specified shared pointer.
The object currently referenced by this shared pointer will no longer be referenced and will be deleted if there are no other referencers.
Parameters
InRawPtrProxy Proxy object used to assign the object (see MakeShareable helper function)
Definition at line 986 of file SharedPointer.h.
operator=() [4/6]
template<class ObjectType, ESPMode InMode> template<typename OtherType, typename DeleterType UE_REQUIRES> FORCEINLINE TSharedPtr & TSharedPtr< ObjectType, InMode >::operator= (SharedPointerInternals::TRawPtrProxyWithDeleter< OtherType, DeleterType > const & InRawPtrProxy) inline
Assignment operator replaces this shared pointer with the specified shared pointer.
The object currently referenced by this shared pointer will no longer be referenced and will be deleted if there are no other referencers.
Parameters
InRawPtrProxy Proxy object used to assign the object (see MakeShareable helper function)
Definition at line 967 of file SharedPointer.h.
operator=() [5/6]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr & TSharedPtr< ObjectType, InMode >::operator= (TSharedPtr< ObjectType, InMode > && InSharedPtr) inline
Definition at line 925 of file SharedPointer.h.
operator=() [6/6]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedPtr & TSharedPtr< ObjectType, InMode >::operator= (TSharedPtr< ObjectType, InMode > const & InSharedPtr) inline
Assignment operator replaces this shared pointer with the specified shared pointer.
The object currently referenced by this shared pointer will no longer be referenced and will be deleted if there are no other referencers.
Parameters
InSharedPtr Shared pointer to replace with
Definition at line 918 of file SharedPointer.h.
operator==()
template<class ObjectType, ESPMode InMode> bool TSharedPtr< ObjectType, InMode >::operator== (FIntrusiveUnsetOptionalState) const inline
Definition at line 1128 of file SharedPointer.h.
Reset()
template<class ObjectType, ESPMode InMode> FORCEINLINE void TSharedPtr< ObjectType, InMode >::Reset () inline
Resets this shared pointer, removing a reference to the object.
If there are no other shared references to the object then it will be destroyed.
Definition at line 1090 of file SharedPointer.h.
Referenced by TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator=(), UE::Insights::FBaseTreeNode::RemoveChild(), UE::Insights::FBaseTreeNode::RemoveChildSwap(), UE::Insights::FBaseTreeNode::ResetParentForChildren(), UE::Insights::FBaseTreeNode::ResetParentForChildrenRec(), TListTypeTraits< TSharedPtr< T, ESPMode::NotThreadSafe > >::ResetPtr(), TListTypeTraits< TSharedPtr< T, ESPMode::ThreadSafe > >::ResetPtr(), TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::ResetPtr(), and TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::ResetPtr().
ToSharedRef() [1/2]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef< ObjectType, Mode > TSharedPtr< ObjectType, InMode >::ToSharedRef () && inline nodiscard
Converts a shared pointer to a shared reference.
The pointer must be valid or an assertion will trigger.
Returns
Reference to the object
Definition at line 1012 of file SharedPointer.h.
ToSharedRef() [2/2]
template<class ObjectType, ESPMode InMode> FORCEINLINE TSharedRef< ObjectType, Mode > TSharedPtr< ObjectType, InMode >::ToSharedRef () const & inline nodiscard
Converts a shared pointer to a shared reference.
The pointer must be valid or an assertion will trigger.
Returns
Reference to the object
Definition at line 998 of file SharedPointer.h.
Referenced by SMultiColumnTableRow< ItemType >::Construct(), SNumericEntryBox< NumericType >::Construct(), SNumericRotatorInputBox< float >::Construct(), TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), TObjectInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene(), FDetailArrayBuilder::GenerateHeaderRowContent(), SListView< TSharedPtr< FString > >::GeneratePinnedWidgetForItem(), SListView< TSharedPtr< FString > >::GenerateWidgetForItem(), TWeakChild< ChildType >::GetChildRefAt(), TWeakChild< ChildType >::GetChildRefAt(), SBreadcrumbTrail< ItemType >::GetCrumbMenuContent(), FArguments< ItemType >::GetForegroundBasedOnSelection(), TWeakChild< ChildType >::GetWidget(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetWidget(), FWorkspaceItem::HasChildrenIn(), TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::NullableItemTypeConvertToItemType(), TListTypeTraits< TSharedRef< T, ESPMode::ThreadSafe > >::NullableItemTypeConvertToItemType(), SRigVMActionMenu::OnCreateWidgetForAction(), SNumericEntryBox< NumericType >::OnFocusReceived(), SListViewSelectorDropdownMenu< ListType >::OnKeyDown(), SBreadcrumbTrail< ItemType >::PushCrumb(), SSegmentedControl< OptionType >::RebuildChildren(), SGraphEditor::RegisterActiveTimer(), SRigVMBulkEditDialog< InWidgetType >::ShowNormal(), SComboBox< OptionType >::SLATE_ARGUMENT(), UE::Sequencer::TViewModelPtr< FViewModel >::ToSharedRef(), and UE::PixelStreaming2::ToString().
ToWeakPtr()
template<class ObjectType, ESPMode InMode> FORCEINLINE TWeakPtr< ObjectType, Mode > TSharedPtr< ObjectType, InMode >::ToWeakPtr () const inline nodiscard
Converts a shared pointer to a weak ptr.
Returns
Weak pointer to the object
Definition at line 1025 of file SharedPointer.h.
Friends And Related Symbol Documentation
TSharedPtr
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TSharedPtr friend
Definition at line 1189 of file SharedPointer.h.
Referenced by TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator=(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator=(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::operator=(), and TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::Reset().
TSharedFromThis
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TSharedFromThis friend
Definition at line 1194 of file SharedPointer.h.
TSharedRef
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TSharedRef friend
Definition at line 1192 of file SharedPointer.h.
Referenced by TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::ToSharedRef(), and TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::ToSharedRef().
TWeakPtr
template<class ObjectType, ESPMode InMode> template<class OtherType, ESPMode OtherMode> friend class TWeakPtr friend
Definition at line 1193 of file SharedPointer.h.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<class ObjectType, ESPMode InMode> bool TSharedPtr< ObjectType, InMode >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 1121 of file SharedPointer.h.
Mode
template<class ObjectType, ESPMode InMode> ESPMode TSharedPtr< ObjectType, InMode >::Mode = InMode static constexpr
Definition at line 668 of file SharedPointer.h.
Object
template<class ObjectType, ESPMode InMode> ObjectType* TSharedPtr< ObjectType, InMode >::Object private
The object we're holding a reference to.
Can be nullptr.
Definition at line 1199 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::operator=().
SharedReferenceCount
template<class ObjectType, ESPMode InMode> SharedPointerInternals::FSharedReferencer< Mode > TSharedPtr< ObjectType, InMode >::SharedReferenceCount private
Interface to the reference counter for this object.
Note that the actual reference controller object is shared by all shared and weak pointers that refer to the object
Definition at line 1203 of file SharedPointer.h.
Referenced by TWeakPtr< INavigationToolItem >::operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/SharedPointer.h