Unreal Engine 5.6 C++ API: FBoneDragDropOp Class Reference
FBoneDragDropOp Class Reference
#include "BoneDragDropOp.h"
Public Member Functions
DRAG_DROP_OPERATOR_TYPE (FBoneDragDropOp, FDragDropOperation) TWeakPtr< class IEditableSkeleton > EditableSkeleton
virtual TSharedPtr< SWidget > GetDefaultDecorator () const override
The widget decorator to use.
FText GetHoverText () const
const FSlateBrush * GetIcon () const
void SetIcon (const FSlateBrush *InIcon)
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FBoneDragDropOp > New (TSharedRef< class IEditableSkeleton > EditableSkeleton, const FName &InBoneName)
Data Fields
FName BoneName
Private Attributes
const FSlateBrush * CurrentIconBrush
Additional Inherited Members
Protected Member Functions inherited from FDragDropOperation
virtual void Construct ()
Constructs the window and widget if applicable.
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Detailed Description
Definition at line 17 of file BoneDragDropOp.h.
Member Function Documentation
DRAG_DROP_OPERATOR_TYPE()
FBoneDragDropOp::DRAG_DROP_OPERATOR_TYPE (FBoneDragDropOp , FDragDropOperation)
References FDragDropOperation::FDragDropOperation().
GetDefaultDecorator()
virtual TSharedPtr< SWidget > FBoneDragDropOp::GetDefaultDecorator () const inline override virtual
The widget decorator to use.
Reimplemented from FDragDropOperation.
Definition at line 26 of file BoneDragDropOp.h.
References FAppStyle::GetBrush(), GetHoverText(), GetIcon(), SHorizontalBox::Slot(), and SNew.
GetHoverText()
FText FBoneDragDropOp::GetHoverText () const inline
Definition at line 49 of file BoneDragDropOp.h.
References BoneName, FText::Format(), FText::FromString(), and NSLOCTEXT.
Referenced by GetDefaultDecorator().
GetIcon()
const FSlateBrush * FBoneDragDropOp::GetIcon () const inline
Definition at line 54 of file BoneDragDropOp.h.
References CurrentIconBrush.
Referenced by GetDefaultDecorator().
New()
TSharedRef< FBoneDragDropOp > FBoneDragDropOp::New (TSharedRef< class IEditableSkeleton > EditableSkeleton, const FName & InBoneName) inline static
Definition at line 64 of file BoneDragDropOp.h.
References FAppStyle::GetBrush(), MakeShareable(), and TEXT.
SetIcon()
void FBoneDragDropOp::SetIcon (const FSlateBrush * InIcon) inline
Definition at line 59 of file BoneDragDropOp.h.
References CurrentIconBrush.
Field Documentation
BoneName
FName FBoneDragDropOp::BoneName
Definition at line 23 of file BoneDragDropOp.h.
Referenced by GetHoverText().
CurrentIconBrush
const FSlateBrush* FBoneDragDropOp::CurrentIconBrush private
Definition at line 75 of file BoneDragDropOp.h.
Referenced by GetIcon(), and SetIcon().
The documentation for this class was generated from the following file:
Editor/Persona/Public/BoneDragDropOp.h