Unreal Engine 5.6 C++ API: TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter > Class Template Reference
TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter > Class Template Reference
#include "LockFreeFixedSizeAllocator.h"
Data Structures
struct FThreadLocalCache
struct for the TLS cache.
Public Member Functions
TLockFreeFixedSizeAllocator_TLSCacheBase ()
~TLockFreeFixedSizeAllocator_TLSCacheBase ()
Destructor, leaks all of the memory.
FORCEINLINE void * Allocate ()
Allocates a memory block of size SIZE.
FORCEINLINE void Free (void *Item)
Puts a memory block previously obtained from Allocate() back on the free list for future use.
const TTrackingCounter & GetNumFree () const
Gets the number of allocated memory blocks that are currently unused.
const TTrackingCounter & GetNumUsed () const
Gets the number of allocated memory blocks that are currently in use.
Private Types
enum { SIZE_PER_BUNDLE = 65536 , NUM_PER_BUNDLE = SIZE_PER_BUNDLE / SIZE }
Private Member Functions
FThreadLocalCache & GetTLS ()
Private Attributes
TBundleRecycler GlobalFreeListBundles
Lock free list of free memory blocks, these are all linked into a bundle of NUM_PER_BUNDLE.
TTrackingCounter NumFree
Total number of blocks in the free list.
TTrackingCounter NumUsed
Total number of blocks outstanding and not in the free list.
uint32 TlsSlot
Slot for TLS struct.
Additional Inherited Members
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Detailed Description
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter>
class TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >
Definition at line 22 of file LockFreeFixedSizeAllocator.h.
Member Enumeration Documentation
anonymous enum
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> anonymous enum private
Enumerator
SIZE_PER_BUNDLE
NUM_PER_BUNDLE
Definition at line 24 of file LockFreeFixedSizeAllocator.h.
Constructor & Destructor Documentation
TLockFreeFixedSizeAllocator_TLSCacheBase()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::TLockFreeFixedSizeAllocator_TLSCacheBase () inline
Definition at line 32 of file LockFreeFixedSizeAllocator.h.
References FAndroidTLS::AllocTlsSlot(), check, FGenericPlatformTLS::IsValidTlsSlot(), and TlsSlot.
~TLockFreeFixedSizeAllocator_TLSCacheBase()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::~TLockFreeFixedSizeAllocator_TLSCacheBase () inline
Destructor, leaks all of the memory.
Definition at line 39 of file LockFreeFixedSizeAllocator.h.
References FAndroidTLS::FreeTlsSlot(), FGenericPlatformTLS::InvalidTlsSlot, and TlsSlot.
Member Function Documentation
Allocate()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> FORCEINLINE void * TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::Allocate () inline
Allocates a memory block of size SIZE.
Returns
Pointer to the allocated memory.
See also
Free
Definition at line 51 of file LockFreeFixedSizeAllocator.h.
References check, FORCEINLINE, TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::FThreadLocalCache::FullBundle, GetTLS(), GlobalFreeListBundles, NUM_PER_BUNDLE, NumFree, TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::FThreadLocalCache::NumPartial, NumUsed, TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::FThreadLocalCache::PartialBundle, and SIZE_PER_BUNDLE.
Referenced by FGraphEventImpl::operator new().
Free()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> FORCEINLINE void TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::Free (void * Item) inline
Puts a memory block previously obtained from Allocate() back on the free list for future use.
Parameters
Item The item to free.
See also
Allocate
Definition at line 100 of file LockFreeFixedSizeAllocator.h.
References FORCEINLINE, FMemory::Free(), TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::FThreadLocalCache::FullBundle, GetTLS(), GlobalFreeListBundles, Item, NUM_PER_BUNDLE, NumFree, TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::FThreadLocalCache::NumPartial, NumUsed, and TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::FThreadLocalCache::PartialBundle.
Referenced by FGraphEventImpl::operator delete().
GetNumFree()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> const TTrackingCounter & TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GetNumFree () const inline
Gets the number of allocated memory blocks that are currently unused.
Returns
Number of unused memory blocks.
See also
GetNumUsed
Definition at line 142 of file LockFreeFixedSizeAllocator.h.
References NumFree.
GetNumUsed()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> const TTrackingCounter & TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GetNumUsed () const inline
Gets the number of allocated memory blocks that are currently in use.
Returns
Number of used memory blocks.
See also
GetNumFree
Definition at line 131 of file LockFreeFixedSizeAllocator.h.
References NumUsed.
GetTLS()
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> FThreadLocalCache & TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GetTLS () inline private
Definition at line 164 of file LockFreeFixedSizeAllocator.h.
References checkSlow, FAndroidTLS::GetTlsValue(), FGenericPlatformTLS::IsValidTlsSlot(), FAndroidTLS::SetTlsValue(), and TlsSlot.
Referenced by Allocate(), and Free().
Field Documentation
GlobalFreeListBundles
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> TBundleRecycler TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::GlobalFreeListBundles private
Lock free list of free memory blocks, these are all linked into a bundle of NUM_PER_BUNDLE.
Definition at line 180 of file LockFreeFixedSizeAllocator.h.
Referenced by Allocate(), and Free().
NumFree
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> TTrackingCounter TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::NumFree private
Total number of blocks in the free list.
Definition at line 186 of file LockFreeFixedSizeAllocator.h.
Referenced by Allocate(), Free(), and GetNumFree().
NumUsed
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> TTrackingCounter TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::NumUsed private
Total number of blocks outstanding and not in the free list.
Definition at line 183 of file LockFreeFixedSizeAllocator.h.
Referenced by Allocate(), Free(), and GetNumUsed().
TlsSlot
template<int32 SIZE, typename TBundleRecycler, typename TTrackingCounter = FNoopCounter> uint32 TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::TlsSlot private
Slot for TLS struct.
Definition at line 177 of file LockFreeFixedSizeAllocator.h.
Referenced by TLockFreeFixedSizeAllocator_TLSCacheBase(), ~TLockFreeFixedSizeAllocator_TLSCacheBase(), and GetTLS().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LockFreeFixedSizeAllocator.h