Unreal Engine 5.6 C++ API: SDataflowSimulationViewportToolBar Class Reference
SDataflowSimulationViewportToolBar Class Reference
Base toolbar for the dataflow.
#include "DataflowSimulationViewportToolbar.h"
Public Member Functions
virtual void ExtendLeftAlignedToolbarSlots (TSharedPtr< SHorizontalBox > MainBoxPtr, TSharedPtr< SViewportToolBar > ParentToolBarPtr) const override
SLATE_ARGUMENT (TSharedPtr< FUICommandList >, CommandList) SLATE_ARGUMENT(TSharedPtr< FExtender >
SLATE_BEGIN_ARGS (SDataflowSimulationViewportToolBar)
Extenders SLATE_END_ARGS () void Construct(const FArguments &InArgs
Constructs this widget with the given parameters.
Data Fields
Extenders TSharedPtr< SDataflowSimulationViewport > InDataflowViewport
Private Member Functions
FText LODButtonLabel () const
EVisibility LODButtonVisibility () const
TSharedRef< SWidget > MakeLODMenu () const
TSharedRef< SWidget > MakeToolBar (const TSharedPtr< FExtender > InExtenders) const
int32 NumLODs () const
Private Attributes
TSharedPtr< FUICommandList > CommandList
TWeakPtr< SDataflowSimulationViewport > EditorViewport
Reference to the parent viewport.
TSharedPtr< FExtender > Extenders
Detailed Description
Base toolbar for the dataflow.
Should be extended to add more features
Definition at line 13 of file DataflowSimulationViewportToolbar.h.
Member Function Documentation
ExtendLeftAlignedToolbarSlots()
virtual void SDataflowSimulationViewportToolBar::ExtendLeftAlignedToolbarSlots (TSharedPtr< SHorizontalBox > MainBoxPtr, TSharedPtr< SViewportToolBar > ParentToolBarPtr) const override virtual
References ExtendLeftAlignedToolbarSlots().
Referenced by ExtendLeftAlignedToolbarSlots().
LODButtonLabel()
FText SDataflowSimulationViewportToolBar::LODButtonLabel () const private
References LODButtonLabel().
Referenced by LODButtonLabel().
LODButtonVisibility()
EVisibility SDataflowSimulationViewportToolBar::LODButtonVisibility () const private
References LODButtonVisibility().
Referenced by LODButtonVisibility().
MakeLODMenu()
TSharedRef< SWidget > SDataflowSimulationViewportToolBar::MakeLODMenu () const private
References MakeLODMenu().
Referenced by MakeLODMenu().
MakeToolBar()
TSharedRef< SWidget > SDataflowSimulationViewportToolBar::MakeToolBar (const TSharedPtr< FExtender > InExtenders) const private
References MakeToolBar().
Referenced by MakeToolBar().
NumLODs()
int32 SDataflowSimulationViewportToolBar::NumLODs () const private
References NumLODs().
Referenced by NumLODs().
SLATE_ARGUMENT()
SDataflowSimulationViewportToolBar::SLATE_ARGUMENT (TSharedPtr< FUICommandList > , CommandList)
References CommandList, and Extenders.
SLATE_BEGIN_ARGS()
SDataflowSimulationViewportToolBar::SLATE_BEGIN_ARGS (SDataflowSimulationViewportToolBar) inline
Definition at line 16 of file DataflowSimulationViewportToolbar.h.
SLATE_END_ARGS()
Extenders SDataflowSimulationViewportToolBar::SLATE_END_ARGS () const &
Constructs this widget with the given parameters.
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Field Documentation
CommandList
TSharedPtr<FUICommandList> SDataflowSimulationViewportToolBar::CommandList private
Definition at line 36 of file DataflowSimulationViewportToolbar.h.
Referenced by SLATE_ARGUMENT().
EditorViewport
TWeakPtr<SDataflowSimulationViewport> SDataflowSimulationViewportToolBar::EditorViewport private
Reference to the parent viewport.
Definition at line 27 of file DataflowSimulationViewportToolbar.h.
Extenders
TSharedPtr<FExtender> SDataflowSimulationViewportToolBar::Extenders private
Definition at line 37 of file DataflowSimulationViewportToolbar.h.
Referenced by SLATE_ARGUMENT().
InDataflowViewport
Extenders TSharedPtr<SDataflowSimulationViewport> SDataflowSimulationViewportToolBar::InDataflowViewport
Definition at line 22 of file DataflowSimulationViewportToolbar.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Dataflow/Source/DataflowEditor/Public/Dataflow/DataflowSimulationViewportToolbar.h