Unreal Engine 5.6 C++ API: SDataflowConstructionViewport Class Reference
SDataflowConstructionViewport Class Reference
#include "DataflowConstructionViewport.h"
Public Member Functions
virtual void BindCommands () override
virtual TSharedPtr< SWidget > BuildViewportToolbar () override
void Construct (const FArguments &InArgs, const FAssetEditorViewportConstructionArgs &InViewportConstructionArgs)
virtual TSharedPtr< IPreviewProfileController > CreatePreviewProfileController () override
FDataflowConstructionScene * GetConstructionScene () const
virtual TSharedPtr< FExtender > GetExtenders () const override
FText GetOverlayText () const
virtual TSharedRef< class SEditorViewport > GetViewportWidget () override
virtual bool IsVisible () const override
virtual TSharedPtr< SWidget > MakeViewportToolbar () override
virtual void OnFloatingButtonClicked () override
virtual void OnFocusViewportToSelection () override
virtual void PopulateViewportOverlays (TSharedRef< SOverlay > Overlay) override
SLATE_ARGUMENT (TSharedPtr< FEditorViewportClient >, ViewportClient) SLATE_END_ARGS() SDataflowConstructionViewport()
SLATE_BEGIN_ARGS (SDataflowConstructionViewport)
Private Member Functions
UDataflowEditorMode * GetEdMode () const
FMargin GetOverlayMargin () const
Private Attributes
TSharedPtr< SRichTextBlock > OverlayText
Pointer to the box into which the overlay text items are added.
Detailed Description
Definition at line 17 of file DataflowConstructionViewport.h.
Member Function Documentation
BindCommands()
virtual void SDataflowConstructionViewport::BindCommands () override virtual
References BindCommands().
Referenced by BindCommands().
BuildViewportToolbar()
virtual TSharedPtr< SWidget > SDataflowConstructionViewport::BuildViewportToolbar () override virtual
References BuildViewportToolbar().
Referenced by BuildViewportToolbar().
Construct()
void SDataflowConstructionViewport::Construct (const FArguments & InArgs, const FAssetEditorViewportConstructionArgs & InViewportConstructionArgs)
References Construct().
Referenced by Construct().
CreatePreviewProfileController()
virtual TSharedPtr< IPreviewProfileController > SDataflowConstructionViewport::CreatePreviewProfileController () override virtual
References CreatePreviewProfileController().
Referenced by CreatePreviewProfileController().
GetConstructionScene()
FDataflowConstructionScene * SDataflowConstructionViewport::GetConstructionScene () const
References GetConstructionScene().
Referenced by GetConstructionScene().
GetEdMode()
UDataflowEditorMode * SDataflowConstructionViewport::GetEdMode () const private
References GetEdMode().
Referenced by GetEdMode().
GetExtenders()
virtual TSharedPtr< FExtender > SDataflowConstructionViewport::GetExtenders () const override virtual
Implements ICommonEditorViewportToolbarInfoProvider.
References GetExtenders().
Referenced by GetExtenders().
GetOverlayMargin()
FMargin SDataflowConstructionViewport::GetOverlayMargin () const private
References GetOverlayMargin().
Referenced by GetOverlayMargin().
GetOverlayText()
FText SDataflowConstructionViewport::GetOverlayText () const
References GetOverlayText().
Referenced by GetOverlayText().
GetViewportWidget()
virtual TSharedRef< class SEditorViewport > SDataflowConstructionViewport::GetViewportWidget () override virtual
Implements ICommonEditorViewportToolbarInfoProvider.
References GetViewportWidget().
Referenced by GetViewportWidget().
IsVisible()
virtual bool SDataflowConstructionViewport::IsVisible () const override virtual
References IsVisible().
Referenced by IsVisible().
MakeViewportToolbar()
virtual TSharedPtr< SWidget > SDataflowConstructionViewport::MakeViewportToolbar () override virtual
References MakeViewportToolbar().
Referenced by MakeViewportToolbar().
OnFloatingButtonClicked()
virtual void SDataflowConstructionViewport::OnFloatingButtonClicked () override virtual
Implements ICommonEditorViewportToolbarInfoProvider.
References OnFloatingButtonClicked().
Referenced by OnFloatingButtonClicked().
OnFocusViewportToSelection()
virtual void SDataflowConstructionViewport::OnFocusViewportToSelection () override virtual
References OnFocusViewportToSelection().
Referenced by OnFocusViewportToSelection().
PopulateViewportOverlays()
virtual void SDataflowConstructionViewport::PopulateViewportOverlays (TSharedRef< SOverlay > Overlay) override virtual
References PopulateViewportOverlays().
Referenced by PopulateViewportOverlays().
SLATE_ARGUMENT()
SDataflowConstructionViewport::SLATE_ARGUMENT (TSharedPtr< FEditorViewportClient > , ViewportClient)
SLATE_BEGIN_ARGS()
SDataflowConstructionViewport::SLATE_BEGIN_ARGS (SDataflowConstructionViewport) inline
Definition at line 20 of file DataflowConstructionViewport.h.
Field Documentation
OverlayText
TSharedPtr<SRichTextBlock> SDataflowConstructionViewport::OverlayText private
Pointer to the box into which the overlay text items are added.
Definition at line 50 of file DataflowConstructionViewport.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Dataflow/Source/DataflowEditor/Public/Dataflow/DataflowConstructionViewport.h