Unreal Engine 5.6 C++ API: TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator Class Reference
TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator Class Reference
Iterates over values associated with a specified key in a map.
#include "SortedMap.h"
Public Member Functions
FORCEINLINE TKeyIterator (TSortedMap &InMap, KeyInitType InKey)
FORCEINLINE TKeyIterator & operator++ ()
FORCEINLINE void RemoveCurrent ()
Removes the current key-value pair from the map.
Public Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >
FORCEINLINE FSetElementId GetId () const
FORCEINLINE ItKeyType & Key () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
FORCEINLINE PairType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
FORCEINLINE PairType * operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
FORCEINLINE ItValueType & Value () const
Private Types
using Super = TBaseIterator<false>
Additional Inherited Members
Public Types inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >
typedef std::conditional_t< bConst, typename ElementArrayType::TConstIterator, typename ElementArrayType::TIterator > PairItType
Protected Member Functions inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >
FORCEINLINE TBaseIterator (const PairItType &InElementIt)
Protected Attributes inherited from TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >
PairItType PairIt
Detailed Description
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate>
class TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator
Iterates over values associated with a specified key in a map.
This will be at most one value because keys must be unique
Definition at line 836 of file SortedMap.h.
Member Typedef Documentation
Super
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> using TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::Super = TBaseIterator<false> private
Definition at line 838 of file SortedMap.h.
Constructor & Destructor Documentation
TKeyIterator()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::TKeyIterator (TSortedMap & InMap, KeyInitType InKey) inline nodiscard
Definition at line 841 of file SortedMap.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TSortedMap, TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::CreateIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::FindIndex(), FORCEINLINE, INDEX_NONE, TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >::PairIt, and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Pairs.
Referenced by operator++().
Member Function Documentation
operator++()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE TKeyIterator & TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::operator++ () inline
Definition at line 856 of file SortedMap.h.
References TKeyIterator(), FORCEINLINE, and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >::PairIt.
RemoveCurrent()
template<typename InKeyType, typename InValueType, typename ArrayAllocator, typename SortPredicate> FORCEINLINE void TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TKeyIterator::RemoveCurrent () inline
Removes the current key-value pair from the map.
Definition at line 863 of file SortedMap.h.
References FORCEINLINE, and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< false >::PairIt.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SortedMap.h