Unreal Engine 5.6 C++ API: UE::Geometry::TPolygon2< T > Class Template Reference
UE::Geometry::TPolygon2< T > Class Template Reference
TPolygon2 is a 2D polygon represented as a list of Vertices.
#include "Polygon2.h"
Data Structures
class SegmentEnumerable
Wrapper around SegmentIterator that has begin() and end() suitable for range-based for loop.
class SegmentIterator
SegmentIterator is used to iterate over the TSegment2<T> segments of the polygon.
Public Member Functions
TPolygon2 ()
template<typename OtherVertexType>
TPolygon2 (const TArray< OtherVertexType > &VertexList)
TPolygon2 (const TArray< TVector2< T > > &VertexList)
Construct polygon with given list of vertices.
TPolygon2 (TArrayView< const TVector2< T > > VertexArray, TArrayView< const int32 > VertexIndices)
Construct polygon with given indices into a vertex array.
void AppendVertex (const TVector2< T > &Position)
Add a vertex to the Polygon.
void AppendVertices (const TArray< TVector2< T > > &NewVertices)
Add a list of Vertices to the Polygon.
T Area () const
T AverageEdgeLength () const
TAxisAlignedBox2< T > Bounds () const
void Chamfer (T ChamferDist, T MinConvexAngleDeg=30, T MinConcaveAngleDeg=30)
Chamfer each vertex corner of the Polygon.
void ClipConvex (const TAxisAlignedBox2< T > &Bounds)
Clip polygon to the given bounds.
bool Contains (const TPolygon2< T > &OtherPoly) const
bool Contains (const TSegment2< T > &Segment) const
bool Contains (const TVector2< T > &QueryPoint) const
T DistanceSquared (const TVector2< T > &QueryPoint) const
Calculate the squared distance from a point to the polygon.
T DistanceSquared (const TVector2< T > &QueryPoint, int &NearestSegIndexOut, T &NearestSegParamOut) const
Calculate the squared distance from a point to the polygon.
bool FindIntersections (const TPolygon2< T > &OtherPoly, TArray< TVector2< T > > &OutArray) const
Find all the points where an edge of the Polygon intersects an edge of the OtherPolygon.
TVector2< T > GetNormal (int iSeg, T SegmentParam) const
TVector2< T > GetNormal (int VertexIndex) const
Get the normal vector at a vertex of the polygon, which is perpendicular to GetTangent() Points "inward" for a Clockwise Polygon, and outward for CounterClockwise.
TVector2< T > GetNormal_FaceAvg (int VertexIndex) const
Construct a normal at a vertex of the Polygon by averaging the adjacent face normals.
TVector2< T > GetSegmentPoint (int SegmentIndex, T SegmentParam) const
TVector2< T > GetSegmentPointUnitParam (int SegmentIndex, T SegmentParam) const
TVector2< T > GetTangent (int VertexIndex) const
Get the tangent vector at a vertex of the polygon, which is the normalized vector from the previous vertex to the next vertex.
const TArray< TVector2< T > > & GetVertices () const
bool Intersects (const TPolygon2< T > &OtherPoly) const
bool Intersects (const TSegment2< T > &Segment) const
bool IsClockwise () const
bool IsConvex (T RadiansTolerance=TMathUtil< T >::ZeroTolerance, bool bDegenerateIsConvex=true) const
void NeighbourPoints (int VertexIdx, TVector2< T > &OutPrevNbr, TVector2< T > &OutNextNbr) const
Get the previous and next vertex positions for a given vertex of the Polygon.
void NeighbourVectors (int VertexIdx, TVector2< T > &OutToPrev, TVector2< T > &OutToNext, bool bNormalize=false) const
Get the vectors from a given vertex to the previous and next Vertices, optionally normalized.
T OpeningAngleDeg (int iVertex) const
TVector2< T > & operator[] (int Index)
Get the vertex at a given index.
const TVector2< T > & operator[] (int Index) const
Get the vertex at a given index.
bool Overlaps (const TPolygon2< T > &OtherPoly) const
Check for polygon overlap, aka solid intersection.
T Perimeter () const
void PolyOffset (T OffsetDistance)
Offset polygon by fixed distance, by offsetting and intersecting edges.
void RemoveVertex (int VertexIndex)
Remove a vertex of the Polygon (existing Vertices are shifted)
void Reverse ()
Reverse the order of the Vertices in the Polygon (ie switch between Clockwise and CounterClockwise)
TPolygon2< T > & Scale (const TVector2< T > &Scale, const TVector2< T > &Origin)
Scale the Polygon relative to a given point.
TSegment2< T > Segment (int SegmentIndex) const
SegmentIterator SegmentItr () const
SegmentEnumerable Segments () const
void Set (int VertexIndex, const TVector2< T > &Position)
Set vertex at given index to a new Position.
void SetVertices (const TArray< TVector2< T > > &NewVertices)
Replace the list of Vertices with a new list.
T SignedArea () const
void Simplify (T ClusterTolerance=0.0001, T LineDeviationTolerance=0.01)
Simplify the Polygon to reduce the vertex count.
const TVector2< T > & Start () const
TPolygon2< T > & Transform (const TFunction< TVector2< T >(const TVector2< T > &)> &TransformFunc)
Apply an arbitrary transformation to the Polygon.
TPolygon2< T > & Translate (const TVector2< T > &Translate)
Translate the polygon.
int VertexCount () const
void VtxNormalOffset (T OffsetDistance, bool bUseFaceAvg=false)
Offset each point by the given Distance along vertex "normal" direction.
T WindingIntegral (const TVector2< T > &QueryPoint) const
Static Public Member Functions
static TPolygon2< T > MakeCircle (T Radius, int Steps, T AngleShiftRadians=0)
Construct a circular polygon.
static TPolygon2< T > MakeRectangle (const TVector2< T > &Center, T Width, T Height)
Construct a four-vertex rectangle polygon.
static TPolygon2< T > MakeRoundedRectangle (const TVector2< T > &Center, T Width, T Height, T Corner, int CornerSteps)
Construct a rounded rectangle polygon.
Protected Attributes
TArray< TVector2< T > > Vertices
The list of vertices/corners of the polygon.
Static Private Member Functions
static void SimplifyDouglasPeucker (T Tolerance, const TArray< TVector2< T > > &Vertices, int j, int k, TArray< bool > &Marked)
Friends
class SegmentIterator
Detailed Description
template<typename T>
class UE::Geometry::TPolygon2< T >
TPolygon2 is a 2D polygon represented as a list of Vertices.
Definition at line 29 of file Polygon2.h.
Constructor & Destructor Documentation
TPolygon2() [1/4]
template<typename T> UE::Geometry::TPolygon2< T >::TPolygon2 () inline
Definition at line 38 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< T >::SegmentEnumerable::SegmentEnumerable().
TPolygon2() [2/4]
template<typename T> UE::Geometry::TPolygon2< T >::TPolygon2 (const TArray< TVector2< T > > & VertexList) inline
Construct polygon with given list of vertices.
Definition at line 45 of file Polygon2.h.
TPolygon2() [3/4]
template<typename T> template<typename OtherVertexType> UE::Geometry::TPolygon2< T >::TPolygon2 (const TArray< OtherVertexType > & VertexList) inline
Definition at line 50 of file Polygon2.h.
TPolygon2() [4/4]
template<typename T> UE::Geometry::TPolygon2< T >::TPolygon2 (TArrayView< const TVector2< T > > VertexArray, TArrayView< const int32 > VertexIndices) inline
Construct polygon with given indices into a vertex array.
Definition at line 63 of file Polygon2.h.
Member Function Documentation
AppendVertex()
template<typename T> void UE::Geometry::TPolygon2< T >::AppendVertex (const TVector2< T > & Position) inline
Add a vertex to the Polygon.
Definition at line 116 of file Polygon2.h.
AppendVertices()
template<typename T> void UE::Geometry::TPolygon2< T >::AppendVertices (const TArray< TVector2< T > > & NewVertices) inline
Add a list of Vertices to the Polygon.
Definition at line 124 of file Polygon2.h.
Area()
template<typename T> T UE::Geometry::TPolygon2< T >::Area () const inline
Returns
the unsigned area of the Polygon
Definition at line 286 of file Polygon2.h.
AverageEdgeLength()
template<typename T> T UE::Geometry::TPolygon2< T >::AverageEdgeLength () const inline
Returns
average edge length of all the edges of the Polygon
Definition at line 645 of file Polygon2.h.
Bounds()
template<typename T> TAxisAlignedBox2< T > UE::Geometry::TPolygon2< T >::Bounds () const inline
Returns
the bounding box of the Polygon Vertices
Definition at line 197 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::FindIntersections(), UE::Geometry::TPolygon2< double >::Intersects(), and UE::Geometry::TPolygon2< double >::Overlaps().
Chamfer()
template<typename T> void UE::Geometry::TPolygon2< T >::Chamfer (T ChamferDist, T MinConvexAngleDeg = 30, T MinConcaveAngleDeg = 30) inline
Chamfer each vertex corner of the Polygon.
Parameters
ChamferDist offset distance from corner that we cut at
Definition at line 939 of file Polygon2.h.
ClipConvex()
template<typename T> void UE::Geometry::TPolygon2< T >::ClipConvex (const TAxisAlignedBox2< T > & Bounds) inline
Clip polygon to the given bounds.
Note that if the polygon is not convex, it may have overlapping edges at the bounds.
Definition at line 446 of file Polygon2.h.
Contains() [1/3]
template<typename T> bool UE::Geometry::TPolygon2< T >::Contains (const TPolygon2< T > & OtherPoly) const inline
Returns
true if the Polygon fully contains the OtherPolygon
Definition at line 400 of file Polygon2.h.
Contains() [2/3]
template<typename T> bool UE::Geometry::TPolygon2< T >::Contains (const TSegment2< T > & Segment) const inline
Returns
true if the Segment is fully contained inside the Polygon
Definition at line 425 of file Polygon2.h.
Contains() [3/3]
template<typename T> bool UE::Geometry::TPolygon2< T >::Contains (const TVector2< T > & QueryPoint) const inline
Returns
true if the given query point is inside the Polygon, based on the winding integral
Definition at line 351 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::Contains(), UE::Geometry::TPolygon2< double >::Contains(), UE::Geometry::TPlanarComplex< double >::FindSolidRegions(), UE::Geometry::TPolygon2< double >::Intersects(), and UE::Geometry::TPolygon2< double >::Overlaps().
DistanceSquared() [1/2]
template<typename T> T UE::Geometry::TPolygon2< T >::DistanceSquared (const TVector2< T > & QueryPoint) const inline
Calculate the squared distance from a point to the polygon.
Parameters
QueryPoint the query point
Returns
squared distance to the polygon
Definition at line 635 of file Polygon2.h.
DistanceSquared() [2/2]
template<typename T> T UE::Geometry::TPolygon2< T >::DistanceSquared (const TVector2< T > & QueryPoint, int & NearestSegIndexOut, T & NearestSegParamOut) const inline
Calculate the squared distance from a point to the polygon.
Parameters
QueryPoint the query point
NearestSegIndexOut The index of the nearest segment
NearestSegParamOut the parameter value of the nearest point on the segment
Returns
squared distance to the polygon
Definition at line 595 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared().
FindIntersections()
template<typename T> bool UE::Geometry::TPolygon2< T >::FindIntersections (const TPolygon2< T > & OtherPoly, TArray< TVector2< T > > & OutArray) const inline
Find all the points where an edge of the Polygon intersects an edge of the OtherPolygon.
Parameters
OtherPoly polygon to test against
OutArray intersection points are stored here
Returns
true if any intersections were found
Definition at line 505 of file Polygon2.h.
GetNormal() [1/2]
template<typename T> TVector2< T > UE::Geometry::TPolygon2< T >::GetNormal (int iSeg, T SegmentParam) const inline
Parameters
SegmentIndex index of first vertex of the edge
SegmentParam parameter in range [0,1] along segment
Returns
interpolated normal to the segment at the given parameter value
Definition at line 576 of file Polygon2.h.
GetNormal() [2/2]
template<typename T> TVector2< T > UE::Geometry::TPolygon2< T >::GetNormal (int VertexIndex) const inline
Get the normal vector at a vertex of the polygon, which is perpendicular to GetTangent() Points "inward" for a Clockwise Polygon, and outward for CounterClockwise.
Definition at line 177 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::GetNormal(), and UE::Geometry::TPolygon2< double >::VtxNormalOffset().
GetNormal_FaceAvg()
template<typename T> TVector2< T > UE::Geometry::TPolygon2< T >::GetNormal_FaceAvg (int VertexIndex) const inline
Construct a normal at a vertex of the Polygon by averaging the adjacent face normals.
This vector is independent of the lengths of the adjacent segments. Points "inward" for a Clockwise Polygon, and outward for CounterClockwise
Definition at line 188 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::PolyOffset(), and UE::Geometry::TPolygon2< double >::VtxNormalOffset().
GetSegmentPoint()
template<typename T> TVector2< T > UE::Geometry::TPolygon2< T >::GetSegmentPoint (int SegmentIndex, T SegmentParam) const inline
Parameters
SegmentIndex index of first vertex of the edge
SegmentParam parameter in range [-Extent,Extent] along segment
Returns
point on the segment at the given parameter value
Definition at line 553 of file Polygon2.h.
GetSegmentPointUnitParam()
template<typename T> TVector2< T > UE::Geometry::TPolygon2< T >::GetSegmentPointUnitParam (int SegmentIndex, T SegmentParam) const inline
Parameters
SegmentIndex index of first vertex of the edge
SegmentParam parameter in range [0,1] along segment
Returns
point on the segment at the given parameter value
Definition at line 564 of file Polygon2.h.
GetTangent()
template<typename T> TVector2< T > UE::Geometry::TPolygon2< T >::GetTangent (int VertexIndex) const inline
Get the tangent vector at a vertex of the polygon, which is the normalized vector from the previous vertex to the next vertex.
Definition at line 167 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::GetNormal().
GetVertices()
template<typename T> const TArray< TVector2< T > > & UE::Geometry::TPolygon2< T >::GetVertices () const inline
Returns
list of Vertices of Polygon
Definition at line 100 of file Polygon2.h.
Intersects() [1/2]
template<typename T> bool UE::Geometry::TPolygon2< T >::Intersects (const TPolygon2< T > & OtherPoly) const inline
Returns
true if at least one edge of the OtherPolygon intersects the Polygon
Definition at line 455 of file Polygon2.h.
Intersects() [2/2]
template<typename T> bool UE::Geometry::TPolygon2< T >::Intersects (const TSegment2< T > & Segment) const inline
Returns
true if the Segment intersects an edge of the Polygon
Definition at line 479 of file Polygon2.h.
IsClockwise()
template<typename T> bool UE::Geometry::TPolygon2< T >::IsClockwise () const inline
Returns
true if the Polygon Vertices have Clockwise winding order / orientation (signed area is negative)
Definition at line 270 of file Polygon2.h.
Referenced by UE::Geometry::TGeneralPolygon2< double >::TGeneralPolygon2(), UE::Geometry::TGeneralPolygon2< double >::AddHole(), UE::Geometry::TPolygon2< double >::Chamfer(), UE::Geometry::TGeneralPolygon2< double >::SetOuter(), and UE::Geometry::TGeneralPolygon2< double >::SetOuterWithOrientation().
IsConvex()
template<typename T> bool UE::Geometry::TPolygon2< T >::IsConvex (T RadiansTolerance = TMathUtil<T>::ZeroTolerance, bool bDegenerateIsConvex = true) const inline
Parameters
RadiansTolerance Maximum turn in the 'wrong' direction that will still be considered convex (in radians)
bDegenerateIsConvex What to return for degenerate input (less than 3 points or equivalent due to repeated points)
Returns
true if polygon is convex
Definition at line 342 of file Polygon2.h.
MakeCircle()
template<typename T> TPolygon2< T > UE::Geometry::TPolygon2< T >::MakeCircle (T Radius, int Steps, T AngleShiftRadians = 0) inline static
Construct a circular polygon.
Definition at line 1049 of file Polygon2.h.
MakeRectangle()
template<typename T> TPolygon2< T > UE::Geometry::TPolygon2< T >::MakeRectangle (const TVector2< T > & Center, T Width, T Height) inline static
Construct a four-vertex rectangle polygon.
Definition at line 1002 of file Polygon2.h.
MakeRoundedRectangle()
template<typename T> TPolygon2< T > UE::Geometry::TPolygon2< T >::MakeRoundedRectangle (const TVector2< T > & Center, T Width, T Height, T Corner, int CornerSteps) inline static
Construct a rounded rectangle polygon.
Definition at line 1016 of file Polygon2.h.
NeighbourPoints()
template<typename T> void UE::Geometry::TPolygon2< T >::NeighbourPoints (int VertexIdx, TVector2< T > & OutPrevNbr, TVector2< T > & OutNextNbr) const inline
Get the previous and next vertex positions for a given vertex of the Polygon.
Definition at line 303 of file Polygon2.h.
NeighbourVectors()
template<typename T> void UE::Geometry::TPolygon2< T >::NeighbourVectors (int VertexIdx, TVector2< T > & OutToPrev, TVector2< T > & OutToNext, bool bNormalize = false) const inline
Get the vectors from a given vertex to the previous and next Vertices, optionally normalized.
Definition at line 312 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::OpeningAngleDeg().
OpeningAngleDeg()
template<typename T> T UE::Geometry::TPolygon2< T >::OpeningAngleDeg (int iVertex) const inline
Returns
the opening angle in degrees at a vertex of the Polygon
Definition at line 321 of file Polygon2.h.
operator[]() [1/2]
template<typename T> TVector2< T > & UE::Geometry::TPolygon2< T >::operator[] (int Index) inline
Get the vertex at a given index.
Definition at line 83 of file Polygon2.h.
operator[]() [2/2]
template<typename T> const TVector2< T > & UE::Geometry::TPolygon2< T >::operator[] (int Index) const inline
Get the vertex at a given index.
Definition at line 75 of file Polygon2.h.
Overlaps()
template<typename T> bool UE::Geometry::TPolygon2< T >::Overlaps (const TPolygon2< T > & OtherPoly) const inline
Check for polygon overlap, aka solid intersection.
(In contrast, note that the "Intersects" method checks for edge intersection)
Returns
true if the Polygon overlaps the OtherPolygon.
Definition at line 361 of file Polygon2.h.
Referenced by UE::Geometry::TGeneralPolygon2< double >::AddHole().
Perimeter()
template<typename T> T UE::Geometry::TPolygon2< T >::Perimeter () const inline
Returns
the total perimeter length of the Polygon
Definition at line 294 of file Polygon2.h.
PolyOffset()
template<typename T> void UE::Geometry::TPolygon2< T >::PolyOffset (T OffsetDistance) inline
Offset polygon by fixed distance, by offsetting and intersecting edges.
CounterClockWise Polygon offsets "outwards", ClockWise "inwards".
Definition at line 736 of file Polygon2.h.
RemoveVertex()
template<typename T> void UE::Geometry::TPolygon2< T >::RemoveVertex (int VertexIndex) inline
Remove a vertex of the Polygon (existing Vertices are shifted)
Definition at line 140 of file Polygon2.h.
Reverse()
template<typename T> void UE::Geometry::TPolygon2< T >::Reverse () inline
Reverse the order of the Vertices in the Polygon (ie switch between Clockwise and CounterClockwise)
Definition at line 157 of file Polygon2.h.
Scale()
template<typename T> TPolygon2< T > & UE::Geometry::TPolygon2< T >::Scale (const TVector2< T > & Scale, const TVector2< T > & Origin) inline
Scale the Polygon relative to a given point.
Returns
the Polygon, so that you can chain calls like Translate().Scale()
Definition at line 674 of file Polygon2.h.
Segment()
template<typename T> TSegment2< T > UE::Geometry::TPolygon2< T >::Segment (int SegmentIndex) const inline
Returns
edge of the polygon starting at vertex SegmentIndex
Definition at line 543 of file Polygon2.h.
SegmentItr()
template<typename T> SegmentIterator UE::Geometry::TPolygon2< T >::SegmentItr () const inline
Definition at line 240 of file Polygon2.h.
Segments()
template<typename T> SegmentEnumerable UE::Geometry::TPolygon2< T >::Segments () const inline
Returns
an object that can be used in a range-based for loop to iterate over the Segments of the Polygon
Definition at line 261 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::Contains(), UE::Geometry::TPolygon2< double >::FindIntersections(), UE::Geometry::TPolygon2< double >::Intersects(), UE::Geometry::TPolygon2< double >::Intersects(), and UE::Geometry::TPolygon2< double >::Overlaps().
Set()
template<typename T> void UE::Geometry::TPolygon2< T >::Set (int VertexIndex, const TVector2< T > & Position) inline
Set vertex at given index to a new Position.
Definition at line 132 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::MakeRectangle(), and UE::Geometry::TPolygon2< double >::MakeRoundedRectangle().
SetVertices()
template<typename T> void UE::Geometry::TPolygon2< T >::SetVertices (const TArray< TVector2< T > > & NewVertices) inline
Replace the list of Vertices with a new list.
Definition at line 148 of file Polygon2.h.
SignedArea()
template<typename T> T UE::Geometry::TPolygon2< T >::SignedArea () const inline
Returns
the signed area of the Polygon
Definition at line 278 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::Area(), and UE::Geometry::TPolygon2< double >::IsClockwise().
Simplify()
template<typename T> void UE::Geometry::TPolygon2< T >::Simplify (T ClusterTolerance = 0.0001, T LineDeviationTolerance = 0.01) inline
Simplify the Polygon to reduce the vertex count.
Parameters
ClusterTolerance Vertices closer than this distance will be merged into a single vertex
LineDeviationTolerance Vertices are allowed to deviate this much from the input polygon lines
Definition at line 819 of file Polygon2.h.
SimplifyDouglasPeucker()
template<typename T> void UE::Geometry::TPolygon2< T >::SimplifyDouglasPeucker (T Tolerance, const TArray< TVector2< T > > & Vertices, int j, int k, TArray< bool > & Marked) inline static private
Definition at line 776 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::Simplify(), and UE::Geometry::TPolygon2< double >::SimplifyDouglasPeucker().
Start()
template<typename T> const TVector2< T > & UE::Geometry::TPolygon2< T >::Start () const inline
Returns
first vertex of Polygon
Definition at line 92 of file Polygon2.h.
Transform()
template<typename T> TPolygon2< T > & UE::Geometry::TPolygon2< T >::Transform (const TFunction< TVector2< T >(const TVector2< T > &)> & TransformFunc) inline
Apply an arbitrary transformation to the Polygon.
Returns
the Polygon, so that you can chain calls like Translate().Scale()
Definition at line 689 of file Polygon2.h.
Translate()
template<typename T> TPolygon2< T > & UE::Geometry::TPolygon2< T >::Translate (const TVector2< T > & Translate) inline
Translate the polygon.
Returns
the Polygon, so that you can chain calls like Translate().Scale()
Definition at line 660 of file Polygon2.h.
VertexCount()
template<typename T> int UE::Geometry::TPolygon2< T >::VertexCount () const inline
Returns
number of Vertices in Polygon
Definition at line 108 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::Contains(), UE::Geometry::FArrangement2d::Insert(), UE::Geometry::TPolygon2< T >::SegmentIterator::operator*(), and UE::Geometry::TPolygon2< double >::Overlaps().
VtxNormalOffset()
template<typename T> void UE::Geometry::TPolygon2< T >::VtxNormalOffset (T OffsetDistance, bool bUseFaceAvg = false) inline
Offset each point by the given Distance along vertex "normal" direction.
Parameters
OffsetDistance the distance to offset
bUseFaceAvg if true, we offset by the average-face normal instead of the perpendicular-tangent normal
Definition at line 707 of file Polygon2.h.
WindingIntegral()
template<typename T> T UE::Geometry::TPolygon2< T >::WindingIntegral (const TVector2< T > & QueryPoint) const inline
Returns
analytic winding integral for this Polygon at an arbitrary point
Definition at line 332 of file Polygon2.h.
Friends And Related Symbol Documentation
SegmentIterator
template<typename T> friend class SegmentIterator friend
Definition at line 238 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< T >::SegmentEnumerable::end(), and UE::Geometry::TPolygon2< double >::SegmentItr().
Field Documentation
Vertices
template<typename T> TArray<TVector2<T> > UE::Geometry::TPolygon2< T >::Vertices protected
The list of vertices/corners of the polygon.
Definition at line 34 of file Polygon2.h.
Referenced by UE::Geometry::TPolygon2< double >::MakeRectangle(), and UE::Geometry::TPolygon2< double >::MakeRoundedRectangle().
The documentation for this class was generated from the following files:
Runtime/GeometryCore/Public/CompGeom/Delaunay2.h
Runtime/GeometryCore/Public/Polygon2.h