Unreal Engine 5.6 C++ API: FTextLocalizationResource Class Reference
FTextLocalizationResource Class Reference
Utility class for working with Localization Resource (LocRes) files.
#include "TextLocalizationResource.h"
Data Structures
struct FEntry
Data struct for tracking a localization entry from a localization resource.
Public Types
typedef TMap< FTextId, FEntry > FEntriesTable
Public Member Functions
FTextLocalizationResource ()=default
FTextLocalizationResource (const FTextLocalizationResource &)=default
FTextLocalizationResource (FTextLocalizationResource &&)=default
void AddEntry (const FTextKey &InNamespace, const FTextKey &InKey, const FString &InSourceString, const FString &InLocalizedString, const int32 InPriority, const FTextKey &InLocResID=FTextKey())
Add a single entry to this resource.
void AddEntry (const FTextKey &InNamespace, const FTextKey &InKey, const FString &InSourceString, const FTextConstDisplayStringRef &InLocalizedString, const int32 InPriority, const FTextKey &InLocResID=FTextKey())
void AddEntry (const FTextKey &InNamespace, const FTextKey &InKey, const uint32 InSourceStringHash, const FString &InLocalizedString, const int32 InPriority, const FTextKey &InLocResID=FTextKey())
void AddEntry (const FTextKey &InNamespace, const FTextKey &InKey, const uint32 InSourceStringHash, const FTextConstDisplayStringRef &InLocalizedString, const int32 InPriority, const FTextKey &InLocResID=FTextKey())
bool IsEmpty () const
Is this resource empty?
bool LoadFromArchive (FArchive &Archive, const FTextKey &LocResID, const int32 Priority)
Load the given LocRes archive into this resource.
void LoadFromDirectory (const FString &DirectoryPath, const int32 Priority)
Load all LocRes files in the specified directory into this resource.
bool LoadFromFile (const FString &FilePath, const int32 Priority)
Load the given LocRes file into this resource.
FTextLocalizationResource & operator= (const FTextLocalizationResource &)=default
FTextLocalizationResource & operator= (FTextLocalizationResource &&)=default
bool SaveToArchive (FArchive &Archive, const FTextKey &LocResID) const
Save this resource to the given LocRes archive.
bool SaveToFile (const FString &FilePath) const
Save this resource to the given LocRes file.
Static Public Member Functions
static FORCEINLINE uint32 HashString (const FString &InStr, const uint32 InBaseHash=0)
Utility to produce a hash for a string (as used by SourceStringHash)
static FORCEINLINE uint32 HashString (const TCHAR *InStr, const uint32 InBaseHash=0)
Utility to produce a hash for a string (as used by SourceStringHash)
Data Fields
FEntriesTable Entries
Static Private Member Functions
static bool ShouldReplaceEntry (const FTextKey &Namespace, const FTextKey &Key, const FEntry &CurrentEntry, const FEntry &NewEntry)
Test whether the new entry should replace the current entry, optionally logging a conflict.
Detailed Description
Utility class for working with Localization Resource (LocRes) files.
Definition at line 52 of file TextLocalizationResource.h.
Member Typedef Documentation
FEntriesTable
typedef TMap<FTextId, FEntry> FTextLocalizationResource::FEntriesTable
Definition at line 73 of file TextLocalizationResource.h.
Constructor & Destructor Documentation
FTextLocalizationResource() [1/3]
FTextLocalizationResource::FTextLocalizationResource () default
Referenced by FTextLocalizationResource(), FTextLocalizationResource(), operator=(), and operator=().
FTextLocalizationResource() [2/3]
FTextLocalizationResource::FTextLocalizationResource (const FTextLocalizationResource &) default
References FTextLocalizationResource().
FTextLocalizationResource() [3/3]
FTextLocalizationResource::FTextLocalizationResource (FTextLocalizationResource &&) default
References FTextLocalizationResource().
Member Function Documentation
AddEntry() [1/4]
void FTextLocalizationResource::AddEntry (const FTextKey & InNamespace, const FTextKey & InKey, const FString & InSourceString, const FString & InLocalizedString, const int32 InPriority, const FTextKey & InLocResID = FTextKey())
Add a single entry to this resource.
AddEntry() [2/4]
void FTextLocalizationResource::AddEntry (const FTextKey & InNamespace, const FTextKey & InKey, const FString & InSourceString, const FTextConstDisplayStringRef & InLocalizedString, const int32 InPriority, const FTextKey & InLocResID = FTextKey())
AddEntry() [3/4]
void FTextLocalizationResource::AddEntry (const FTextKey & InNamespace, const FTextKey & InKey, const uint32 InSourceStringHash, const FString & InLocalizedString, const int32 InPriority, const FTextKey & InLocResID = FTextKey())
AddEntry() [4/4]
void FTextLocalizationResource::AddEntry (const FTextKey & InNamespace, const FTextKey & InKey, const uint32 InSourceStringHash, const FTextConstDisplayStringRef & InLocalizedString, const int32 InPriority, const FTextKey & InLocResID = FTextKey())
HashString() [1/2]
FORCEINLINE uint32 FTextLocalizationResource::HashString (const FString & InStr, const uint32 InBaseHash = 0) inline static
Utility to produce a hash for a string (as used by SourceStringHash)
Definition at line 83 of file TextLocalizationResource.h.
References FORCEINLINE, and FCrc::StrCrc32().
HashString() [2/2]
FORCEINLINE uint32 FTextLocalizationResource::HashString (const TCHAR * InStr, const uint32 InBaseHash = 0) inline static
Utility to produce a hash for a string (as used by SourceStringHash)
Definition at line 77 of file TextLocalizationResource.h.
References FORCEINLINE, and FCrc::StrCrc32().
Referenced by FConfigValue::FConfigValue(), FConfigValue::FConfigValue(), FConfigValue::FConfigValue(), and FConfigValue::operator=().
IsEmpty()
bool FTextLocalizationResource::IsEmpty () const
Is this resource empty?
LoadFromArchive()
bool FTextLocalizationResource::LoadFromArchive (FArchive & Archive, const FTextKey & LocResID, const int32 Priority)
Load the given LocRes archive into this resource.
LoadFromDirectory()
void FTextLocalizationResource::LoadFromDirectory (const FString & DirectoryPath, const int32 Priority)
Load all LocRes files in the specified directory into this resource.
LoadFromFile()
bool FTextLocalizationResource::LoadFromFile (const FString & FilePath, const int32 Priority)
Load the given LocRes file into this resource.
operator=() [1/2]
FTextLocalizationResource & FTextLocalizationResource::operator= (const FTextLocalizationResource &) default
References FTextLocalizationResource().
operator=() [2/2]
FTextLocalizationResource & FTextLocalizationResource::operator= (FTextLocalizationResource &&) default
References FTextLocalizationResource().
SaveToArchive()
bool FTextLocalizationResource::SaveToArchive (FArchive & Archive, const FTextKey & LocResID) const
Save this resource to the given LocRes archive.
SaveToFile()
bool FTextLocalizationResource::SaveToFile (const FString & FilePath) const
Save this resource to the given LocRes file.
ShouldReplaceEntry()
bool FTextLocalizationResource::ShouldReplaceEntry (const FTextKey & Namespace, const FTextKey & Key, const FEntry & CurrentEntry, const FEntry & NewEntry) static private
Test whether the new entry should replace the current entry, optionally logging a conflict.
References Key.
Field Documentation
Entries
FEntriesTable FTextLocalizationResource::Entries
Definition at line 74 of file TextLocalizationResource.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/TextLocalizationResource.h