Unreal Engine 5.6 C++ API: FContentHelper Class Reference
FContentHelper Class Reference
Collection helper Used to create and update ContentBrowser collections.
#include "PackageHelperFunctions.h"
Public Member Functions
FContentHelper (const TSharedRef< ICollectionContainer > &InCollectionContainer)
~FContentHelper ()
bool ClearCollection (FName InCollectionName, ECollectionShareType::Type InType)
Clear the given collection.
bool CreateCollection (FName CollectionName, ECollectionShareType::Type InType)
Create a new tag.
UNREALED_API bool Initialize ()
Initialize the Collection helper.
UNREALED_API bool QueryAssetsInCollection (FName InCollectionName, ECollectionShareType::Type InType, TArray< FSoftObjectPath > &OutAssetPaths)
Retrieve the assets contained in the given collection.
bool SetCollection (FName InCollectionName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > &InAssetList)
Fill the given collection with the given list of assets.
UNREALED_API void Shutdown ()
Shutdown the collection helper.
UE_DEPRECATED (5.6, "Use the ICollectionContainer overload instead.") FContentHelper()
bool UpdateCollection (FName InCollectionName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > &InAddList, const TArray< FSoftObjectPath > &InRemoveList)
Update the given collection with the lists of adds/removes.
Protected Member Functions
template<class AssetSetPolicy>
bool AssignSetContent (FName InSetName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > &InAssetList)
Sets the contents of a Tag or Collection to be the InAssetList.
template<class AssetSetPolicy>
bool ClearAssetSet (FName InSetName, ECollectionShareType::Type InSetType)
Clears the content of a Tag or Collection.
template<class AssetSetPolicy>
bool CreateAssetSet (FName InSetName, ECollectionShareType::Type InSetType)
Creates a new collection.
template<class AssetSetPolicy>
bool QuerySetContent (FName InCollectionName, ECollectionShareType::Type InType, TArray< FSoftObjectPath > &OutAssetPaths)
Get the list of all assets in the specified Collection or Tag.
template<class AssetSetPolicy>
bool UpdateSetContent (FName InSetName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > &InAddList, const TArray< FSoftObjectPath > &InRemoveList)
Add and remove assets for the specified Tag or Connection.
Protected Attributes
bool bInitialized
TSharedPtr< ICollectionContainer > CollectionContainer
Detailed Description
Collection helper Used to create and update ContentBrowser collections.
Definition at line 86 of file PackageHelperFunctions.h.
Constructor & Destructor Documentation
FContentHelper()
FContentHelper::FContentHelper (const TSharedRef< ICollectionContainer > & InCollectionContainer) explicit
References FContentHelper().
Referenced by FContentHelper(), ~FContentHelper(), and UE_DEPRECATED().
~FContentHelper()
FContentHelper::~FContentHelper () inline
Definition at line 94 of file PackageHelperFunctions.h.
References FContentHelper(), bInitialized, and Shutdown().
Member Function Documentation
AssignSetContent()
template<class AssetSetPolicy> bool FContentHelper::AssignSetContent (FName InSetName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > & InAssetList) protected
Sets the contents of a Tag or Collection to be the InAssetList.
Assets not mentioned in the list will be untagged.
ClearAssetSet()
template<class AssetSetPolicy> bool FContentHelper::ClearAssetSet (FName InSetName, ECollectionShareType::Type InSetType) protected
Clears the content of a Tag or Collection.
ClearCollection()
bool FContentHelper::ClearCollection (FName InCollectionName, ECollectionShareType::Type InType)
Clear the given collection.
Parameters
InCollectionName The name of the collection to clear
InType Type of collection
Returns
bool true if successful, false if failed
CreateAssetSet()
template<class AssetSetPolicy> bool FContentHelper::CreateAssetSet (FName InSetName, ECollectionShareType::Type InSetType) protected
Creates a new collection.
CreateCollection()
bool FContentHelper::CreateCollection (FName CollectionName, ECollectionShareType::Type InType)
Create a new tag.
Parameters
CollectionName The name of the tag to create
Returns
bool true if successful, false if failed
Initialize()
UNREALED_API bool FContentHelper::Initialize ()
Initialize the Collection helper.
Returns
bool true if successful, false if failed
QueryAssetsInCollection()
UNREALED_API bool FContentHelper::QueryAssetsInCollection (FName InCollectionName, ECollectionShareType::Type InType, TArray< FSoftObjectPath > & OutAssetPaths)
Retrieve the assets contained in the given collection.
Parameters
InCollectionName Name of collection to query
InType Type of collection
OutAssetPaths The assets contained in the collection
Returns
True if collection was created successfully
QuerySetContent()
template<class AssetSetPolicy> bool FContentHelper::QuerySetContent (FName InCollectionName, ECollectionShareType::Type InType, TArray< FSoftObjectPath > & OutAssetPaths) protected
Get the list of all assets in the specified Collection or Tag.
SetCollection()
bool FContentHelper::SetCollection (FName InCollectionName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > & InAssetList)
Fill the given collection with the given list of assets.
Parameters
InCollectionName The name of the collection to fill
InType Type of collection
InAssetList The list of items to fill the collection with (can be empty)
Returns
bool true if successful, false if not.
Shutdown()
UNREALED_API void FContentHelper::Shutdown ()
Shutdown the collection helper.
Referenced by ~FContentHelper().
UE_DEPRECATED()
FContentHelper::UE_DEPRECATED (5. 6, "Use the ICollectionContainer overload instead.")
References FContentHelper().
UpdateCollection()
bool FContentHelper::UpdateCollection (FName InCollectionName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > & InAddList, const TArray< FSoftObjectPath > & InRemoveList)
Update the given collection with the lists of adds/removes.
Parameters
InCollectionName The name of the collection to update
InType Type of collection
InAddList The list of items to ADD to the collection (can be empty)
InRemoveList The list of items to REMOVE from the collection (can be empty)
Returns
bool true if successful, false if not.
UpdateSetContent()
template<class AssetSetPolicy> bool FContentHelper::UpdateSetContent (FName InSetName, ECollectionShareType::Type InType, const TArray< FSoftObjectPath > & InAddList, const TArray< FSoftObjectPath > & InRemoveList) protected
Add and remove assets for the specified Tag or Connection.
Assets from InAddList are added; assets from InRemoveList are removed.
Field Documentation
bInitialized
bool FContentHelper::bInitialized protected
Definition at line 183 of file PackageHelperFunctions.h.
Referenced by ~FContentHelper().
CollectionContainer
TSharedPtr<ICollectionContainer> FContentHelper::CollectionContainer protected
Definition at line 184 of file PackageHelperFunctions.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/PackageHelperFunctions.h