Unreal Engine 5.6 C++ API: IKeyFrameManipulator< TimeType > Class Template Reference
IKeyFrameManipulator< TimeType > Class Template Reference abstract
Templated key frame manipulator that knows how to add, remove and (re)arrange key times.
#include "IKeyFrameManipulator.h"
Public Types
typedef TCallTraits< TimeType >::ParamType TimeTypeRef
Public Member Functions
FORCEINLINE FKeyHandle AddKey (TimeTypeRef InTime)
Add a new key time to the data structure.
FORCEINLINE TOptional< FKeyHandle > FindKey (TimeTypeRef KeyTime, TimeTypeRef KeyTimeTolerance) const
Attempt to find a key using a custom predicate.
FORCEINLINE TOptional< TimeType > GetKeyTime (FKeyHandle KeyHandle) const
Get the time that corresponds to the specified key handle.
FORCEINLINE void RemoveKey (FKeyHandle KeyHandle)
Remove a key that corresponds to the specified key handle.
FORCEINLINE void SetKeyTime (FKeyHandle KeyHandle, TimeTypeRef NewTime)
Set the time for a key that corresponds to the specified key handle.
Private Member Functions
virtual FKeyHandle AddKeyImpl (TimeTypeRef InTime)=0
Add a new key time to the data structure.
virtual TOptional< FKeyHandle > FindKeyImpl (const TFunctionRef< bool(TimeTypeRef)> &InPredicate) const =0
Attempt to find a key using a custom predicate.
virtual TOptional< TimeType > GetKeyTimeImpl (FKeyHandle KeyHandle) const =0
Get the time that corresponds to the specified key handle.
virtual TKeyTimeIterator< TimeType > IterateKeysImpl () const =0
Iterate the times stored in the external data structure.
virtual void RemoveKeyImpl (FKeyHandle KeyHandle)=0
Remove a key that corresponds to the specified key handle.
virtual void SetKeyTimeImpl (FKeyHandle KeyHandle, TimeTypeRef NewTime)=0
Set the time for a key that corresponds to the specified key handle.
Detailed Description
template<typename TimeType = float>
class IKeyFrameManipulator< TimeType >
Templated key frame manipulator that knows how to add, remove and (re)arrange key times.
Should guarantee that any manipulation of a previously sorted time array, will remain sorted.
Definition at line 16 of file IKeyFrameManipulator.h.
Member Typedef Documentation
TimeTypeRef
template<typename TimeType = float> typedef TCallTraits<TimeType>::ParamType IKeyFrameManipulator< TimeType >::TimeTypeRef
Definition at line 21 of file IKeyFrameManipulator.h.
Member Function Documentation
AddKey()
template<typename TimeType = float> FORCEINLINE FKeyHandle IKeyFrameManipulator< TimeType >::AddKey (TimeTypeRef InTime) inline
Add a new key time to the data structure.
Parameters
InTime The value of the time to add
Returns
A key handle for the new key
Definition at line 29 of file IKeyFrameManipulator.h.
References AddKeyImpl(), FORCEINLINE, and InTime.
AddKeyImpl()
template<typename TimeType = float> virtual FKeyHandle IKeyFrameManipulator< TimeType >::AddKeyImpl (TimeTypeRef InTime) private pure virtual
Add a new key time to the data structure.
Parameters
InTime The value of the time to add
Returns
A key handle for the new key
Implemented in TKeyFrameManipulator< TimeType >.
References InTime.
Referenced by AddKey().
FindKey()
template<typename TimeType = float> FORCEINLINE TOptional< FKeyHandle > IKeyFrameManipulator< TimeType >::FindKey (TimeTypeRef KeyTime, TimeTypeRef KeyTimeTolerance) const inline
Attempt to find a key using a custom predicate.
Parameters
InPredicate Predicate function to use when searching
Returns
The key's handle if found, or an empty container if not
Definition at line 73 of file IKeyFrameManipulator.h.
References FindKeyImpl(), FORCEINLINE, InTime, FMath::IsNearlyEqual(), and Predicate.
FindKeyImpl()
template<typename TimeType = float> virtual TOptional< FKeyHandle > IKeyFrameManipulator< TimeType >::FindKeyImpl (const TFunctionRef< bool(TimeTypeRef)> & InPredicate) const private pure virtual
Attempt to find a key using a custom predicate.
Parameters
InPredicate Predicate function to use when searching
Returns
The key's handle if found, or an empty container if not
Implemented in TKeyFrameManipulator< TimeType >.
Referenced by FindKey().
GetKeyTime()
template<typename TimeType = float> FORCEINLINE TOptional< TimeType > IKeyFrameManipulator< TimeType >::GetKeyTime (FKeyHandle KeyHandle) const inline
Get the time that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to get the time for.
Returns
The time that this key exists at, or an empty container if it was not found
Definition at line 62 of file IKeyFrameManipulator.h.
References FORCEINLINE, and GetKeyTimeImpl().
GetKeyTimeImpl()
template<typename TimeType = float> virtual TOptional< TimeType > IKeyFrameManipulator< TimeType >::GetKeyTimeImpl (FKeyHandle KeyHandle) const private pure virtual
Get the time that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to get the time for.
Returns
The time that this key exists at, or an empty container if it was not found
Implemented in TKeyFrameManipulator< TimeType >.
Referenced by GetKeyTime().
IterateKeysImpl()
template<typename TimeType = float> virtual TKeyTimeIterator< TimeType > IKeyFrameManipulator< TimeType >::IterateKeysImpl () const private pure virtual
Iterate the times stored in the external data structure.
Returns
An iterator that iterates the keys in order, and can optionally supply handles
Implemented in TKeyFrameManipulator< TimeType >.
RemoveKey()
template<typename TimeType = float> FORCEINLINE void IKeyFrameManipulator< TimeType >::RemoveKey (FKeyHandle KeyHandle) inline
Remove a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to remove
Definition at line 51 of file IKeyFrameManipulator.h.
References FORCEINLINE, and RemoveKeyImpl().
RemoveKeyImpl()
template<typename TimeType = float> virtual void IKeyFrameManipulator< TimeType >::RemoveKeyImpl (FKeyHandle KeyHandle) private pure virtual
Remove a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to remove
Implemented in TKeyFrameManipulator< TimeType >.
Referenced by RemoveKey().
SetKeyTime()
template<typename TimeType = float> FORCEINLINE void IKeyFrameManipulator< TimeType >::SetKeyTime (FKeyHandle KeyHandle, TimeTypeRef NewTime) inline
Set the time for a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to set the time for
NewTime The time to assign to this key
Definition at line 40 of file IKeyFrameManipulator.h.
References FORCEINLINE, and SetKeyTimeImpl().
SetKeyTimeImpl()
template<typename TimeType = float> virtual void IKeyFrameManipulator< TimeType >::SetKeyTimeImpl (FKeyHandle KeyHandle, TimeTypeRef NewTime) private pure virtual
Set the time for a key that corresponds to the specified key handle.
Parameters
KeyHandle Handle to the key to set the time for
NewTime The time to assign to this key
Implemented in TKeyFrameManipulator< TimeType >.
Referenced by SetKeyTime().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Curves/IKeyFrameManipulator.h