Unreal Engine 5.6 C++ API: SDesignerView Class Reference
SDesignerView Class Reference
The designer for widgets.
#include "SDesignerView.h"
Data Structures
struct FDropPreview
struct FWidgetHitResult
Public Member Functions
virtual ~SDesignerView ()
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void BeginResizingArea ()
TSharedRef< SWidget > CreateOverlayUI ()
void EndResizingArea ()
EActiveTimerReturnType EnsureTick (double InCurrentTime, float InDeltaTime)
virtual FGeometry GetDesignerGeometry () const override
FOptionalSize GetPreviewAreaHeight () const
The height of the preview screen for the UI.
FOptionalSize GetPreviewAreaWidth () const
The width of the preview screen for the UI.
float GetPreviewDPIScale () const
Gets the DPI scale that would be applied given the current preview width and height.
virtual float GetPreviewScale () const override
FOptionalSize GetPreviewSizeHeight () const
The height of the preview widget for the UI.
FOptionalSize GetPreviewSizeWidth () const
The width of the preview widget for the UI.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
const UWidgetEditingProjectSettings * GetRelevantSettings () const
virtual FWidgetReference GetSelectedWidget () const override
virtual const TSet< FWidgetReference > & GetSelectedWidgets () const override
virtual ETransformMode::Type GetTransformMode () const override
virtual bool GetWidgetGeometry (const FWidgetReference &Widget, FGeometry &Geometry) const override
Gets the previous frames widget geometry.
virtual bool GetWidgetGeometry (const UWidget *PreviewWidget, FGeometry &Geometry) const override
Gets the previous frames widget geometry.
virtual FVector2D GetWidgetOriginAbsolute () const
virtual bool GetWidgetParentGeometry (const FWidgetReference &Widget, FGeometry &Geometry) const override
Gets the previous frames widget geometry of the parent of the provided widget.
virtual FGeometry MakeGeometryWindowLocal (const FGeometry &WidgetGeometry) const override
Takes geometry and adds the inverse of the window transform to get the geometry in the space of the window.
virtual void MarkDesignModifed (bool bRequiresRecompile) override
Marks the designer content as being modified.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual void PopDesignerMessage () override
Removes the last message from the message stack.
virtual void PushDesignerMessage (const FText &Message) override
Push a new designer message to show at the bottom of the screen.
void Register (TSharedRef< FDesignerExtension > Extension)
void SetPreviewAreaSize (int32 Width, int32 Height)
Set the size of the preview screen for the UI.
SLATE_BEGIN_ARGS (SDesignerView)
SLATE_END_ARGS () void Construct(const FArguments &InArgs
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
void Unregister (TSharedRef< FDesignerExtension > Extension)
Public Member Functions inherited from SDesignSurface
float GetZoomAmount () const
Gets the current zoom factor.
FVector2D GraphCoordToPanelCoord (const FVector2D &GraphSpaceCoordinate) const
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when the mouse wheel is spun.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent) override
Called when the user performs a gesture on trackpad.
FVector2D PanelCoordToGraphCoord (const FVector2D &PanelSpaceCoordinate) const
SLATE_BEGIN_ARGS (SDesignSurface)
SLATE_DEFAULT_SLOT (FArguments, Content) SLATE_ATTRIBUTE(bool
Slot for this designers content (optional)
AllowContinousZoomInterpolation SLATE_END_ARGS () void Construct(const FArguments &InArgs)
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Data Fields
TSharedPtr< class FWidgetBlueprintEditor > InBlueprintEditor
Protected Member Functions
virtual FSlateRect ComputeAreaBounds () const override
void DrawResolution (const FDebugResolution &Resolution, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId) const
virtual int32 GetGraphRulePeriod () const override
virtual float GetGridScaleAmount () const override
virtual int32 GetSnapGridSize () const override
virtual void OnPaintBackground (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId) const override
Protected Member Functions inherited from SDesignSurface
void ChangeZoomLevel (int32 ZoomLevelDelta, const FVector2D &WidgetSpaceZoomOrigin, bool bOverrideZoomLimiting)
FSlateRect ComputeSensibleBounds () const
FVector2D GetViewOffset () const
FText GetZoomText () const
FSlateColor GetZoomTextColorAndOpacity () const
void PaintBackgroundAsLines (const FSlateBrush *BackgroundImage, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 &DrawLayerId) const
void PostChangedZoom ()
bool ScrollToLocation (const FGeometry &MyGeometry, FVector2D DesiredCenterPosition, const float InDeltaTime)
void ZoomToFit (bool bInstantZoom)
bool ZoomToLocation (const FVector2D &CurrentSizeWithoutZoom, const FVector2D &DesiredSize, bool bDoneScrolling)
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
void BeginTransaction (const FText &SessionName)
void BindCommands ()
void BroadcastDesignerChanged ()
bool CanSetTransformMode (ETransformMode::Type InTransformMode) const
void ClearDropPreviews ()
void ClearExtensionWidgets ()
void CreateExtensionWidgetsForSelection ()
void CreateScreenFillEntry (FMenuBuilder &MenuBuilder, EDesignPreviewSizeMode SizeMode)
void DeselectNonSequencerWidgets ()
void DetermineDragDropPreviewWidgets (TArray< UWidget * > &OutWidgets, const FDragDropEvent &DragDropEvent, UWidgetTree *RootWidgetTree)
void DrawSafeZone (const FOnPaintHandlerParams &PaintArgs)
void DrawSelectionAndHoverOutline (const FOnPaintHandlerParams &PaintArgs)
void EndTransaction (bool bCancel)
bool FindWidgetUnderCursor (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent, TSubclassOf< UWidget > FindType, FWidgetHitResult &HitResult)
FVector2D GetAreaResizeHandlePosition () const
EVisibility GetAreaResizeHandleVisibility () const
bool GetAspectRatioSwitchEnabled () const
const FSlateBrush * GetAspectRatioSwitchImage () const
UWidgetBlueprint * GetBlueprint () const
Gets the blueprint being edited by the designer.
FSlateColor GetCurrentDPIScaleColor () const
FText GetCurrentDPIScaleText () const
FText GetCurrentResolutionText () const
FText GetCurrentSafeZoneText () const
FText GetCurrentScaleFactorText () const
FText GetCursorPositionText () const
EVisibility GetCursorPositionTextVisibility () const
EVisibility GetCustomResolutionEntryVisibility () const
TOptional< int32 > GetCustomResolutionHeight () const
TOptional< int32 > GetCustomResolutionWidth () const
UUserWidget * GetDefaultWidget () const
FSlateColor GetDesignerOutlineColor () const
FText GetDesignerOutlineText () const
EVisibility GetDesignerOutlineVisibility () const
EVisibility GetExtensionCanvasVisibility () const
FVector2D GetExtensionPosition (TSharedRef< FDesignerSurfaceElement > ExtensionElement) const
FVector2D GetExtensionSize (TSharedRef< FDesignerSurfaceElement > ExtensionElement) const
bool GetFlipDeviceEnabled () const
FText GetInfoBarText () const
EVisibility GetInfoBarVisibility () const
bool GetIsScreenFillRuleSelected (EDesignPreviewSizeMode SizeMode) const
const FSlateBrush * GetPreviewBackground () const
FUIAction GetResolutionMenuAction (const FPlayScreenResolution &ScreenResolution)
TSharedRef< SWidget > GetResolutionsMenu ()
FText GetResolutionText (int32 Width, int32 Height, const FString &AspectRatio) const
FSlateColor GetResolutionTextColorAndOpacity () const
EVisibility GetResolutionTextVisibility () const
EVisibility GetRulerVisibility () const
TSharedRef< SWidget > GetScreenSizingFillMenu ()
FText GetScreenSizingFillText () const
FText GetSelectedWidgetDimensionsText () const
EVisibility GetSelectedWidgetDimensionsVisibility () const
EVisibility GetSelectionLimitedTextVisibility () const
UWidget * GetWidgetInDesignScopeFromSlateWidget (TSharedRef< SWidget > &InWidget)
FReply HandleDPISettingsClicked ()
int32 HandleEffectsPainting (const FOnPaintHandlerParams &PaintArgs)
FReply HandleFlipSafeZonesClicked ()
bool HandleIsCommonResolutionSelected (const FPlayScreenResolution InResolution) const
void HandleOnCommonResolutionSelected (const FPlayScreenResolution InResolution)
FReply HandleSwapAspectRatioClicked ()
FReply HandleZoomToFitClicked ()
bool InTransaction () const
bool IsRespectingLocks () const
bool IsSelectableInSequencer (UWidget *const InWidget) const
bool IsShowingOutlines () const
bool IsTransformModeActive (ETransformMode::Type InTransformMode) const
void MoveWidgets (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent, const bool bIsPreview, UWidget *Target, const bool bAnyWidgetChangingParent)
FReply NudgeSelectedWidget (FVector2D Nudge)
Move the selected widget by the nudge amount.
void OnCustomResolutionHeightChanged (int32 InValue)
void OnCustomResolutionWidthChanged (int32 InValue)
void OnEditorSelectionChanged ()
void OnHoveredWidgetCleared ()
Called when a widget is no longer being hovered.
void OnHoveredWidgetSet (const FWidgetReference &InHoveredWidget)
Called when a new widget is being hovered.
void OnPreviewNeedsRecreation ()
Called whenever the blueprint is recompiled or the preview is updated.
void OnScreenFillRuleSelected (EDesignPreviewSizeMode SizeMode)
void OnSelectedAnimationChanged ()
void OnSelectionLimitedChanged (const bool bInEnabled)
void PopulateWidgetGeometryCache (FArrangedWidget &Root)
void PopulateWidgetGeometryCache_Loop (FArrangedWidget &Parent)
void ProcessDropAndAddWidget (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent, const bool bIsPreview)
void RegisterExtensions ()
void ResolvePendingSelectedWidgets ()
Adds any pending selected widgets to the selection set.
void SetStartupResolution ()
Establishes the resolution and aspect ratio to use on construction from config settings.
void SetTransformMode (ETransformMode::Type InTransformMode)
void ShowContextMenu (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Displays the context menu when you right click.
void SwapSafeZoneTypes ()
void ToggleRespectingLocks ()
void ToggleShowingOutlines ()
void UpdatePreviewWidget (bool bForceUpdate)
Updates the designer to display the latest preview widget.
Private Attributes
FSlateBrush BackgroundImage
The slate brush we use to hold the background image shown in the designer.
bool bCanPreviewSwapAspectRatio
bool bCommonResolutionSelected
TWeakPtr< FWidgetBlueprintEditor > BlueprintEditor
A reference to the BP Editor that owns this designer.
bool bMovingExistingWidget
An existing widget is being moved in its current container, or in to a new container.
bool bPreviewIsPortrait
bool bSafeZoneFlipped
bool bShowResolutionOutlines
FVector2D CachedMousePosition
Cache last mouse position to be used as a paste drop location.
FVector2D CachedPreviewDesiredSize
We cache the desired preview desired size to maintain the same size between compiles when it lags a frame behind and no widget is available.
TMap< TSharedRef< SWidget >, FArrangedWidget > CachedWidgetGeometry
TSharedPtr< FUICommandList > CommandList
The designer command list.
TArray< FVector2D > CustomSafeZoneDimensions
TArray< FVector2D > CustomSafeZoneStarts
TSharedPtr< SCanvas > DesignerControls
TArray< TSharedRef< FDesignerExtension > > DesignerExtensions
Extensions for the designer to allow for custom widgets to be inserted onto the design surface as selection changes.
TSharedPtr< FHittestGrid > DesignerHittestGrid
TArray< FText > DesignerMessageStack
The message stack to display the last item to the user in a non-modal fashion.
FMargin DesignerSafeZoneOverride
TSharedPtr< SCanvas > DesignerWidgetCanvas
FVector2D DraggingStartPositionScreenSpace
The position in screen space where the user began dragging a widget.
TArray< FDropPreview > DropPreviews
TSharedPtr< SPaintSurface > EffectsLayer
TSharedPtr< SCanvas > ExtensionWidgetCanvas
int32 HeightReadFromSettings
The original Height of the preview area, read from the settings file.
FCurveSequence HoveredWidgetOutlineFade
Curve to handle the fade-in of the border around the hovered widget.
FWidgetReference PendingSelectedWidget
Holds onto a temporary widget that the user may be getting ready to select, or may just be the widget that got hit on the initial mouse down before moving the parent.
TSharedPtr< SBox > PreviewAreaConstraint
FString PreviewAspectRatio
int32 PreviewHeight
The configured Height of the preview area, simulates screen size.
TSharedPtr< SWidget > PreviewHitTestRoot
FString PreviewOverrideName
TSharedPtr< SBox > PreviewSizeConstraint
TWeakPtr< SWidget > PreviewSlateWidget
The current preview widget's slate widget.
TSharedPtr< SDPIScaler > PreviewSurface
TObjectPtr< UUserWidget > PreviewWidget
The current preview widget.
int32 PreviewWidth
The configured Width of the preview area, simulates screen size.
FCurveSequence ResolutionTextFade
Curve to handle fading of the resolution.
float ScaleFactor
FScopedTransaction * ScopedTransaction
The transaction used to commit undoable actions from resize, move...etc.
FVector2D SelectedWidgetContextMenuLocation
The location in selected widget local space where the context menu was summoned.
FWeakWidgetPath SelectedWidgetPath
TSet< FWidgetReference > SelectedWidgetsCache
The currently selected preview widgets in the preview GUI, just a cache used to determine changes between selection changes.
TSharedPtr< SRuler > SideRuler
The ruler bar on the left side of the designer.
TSharedPtr< SRuler > TopRuler
The ruler bar at the top of the designer.
ETransformMode::Type TransformMode
int32 WidthReadFromSettings
The original Width of the preview area, read from the settings file.
Static Private Attributes
static const FString ConfigSectionName
static const FString DefaultPreviewOverrideName
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SDesignSurface
TAttribute< bool > AllowContinousZoomInterpolation
Allow continuous zoom interpolation?
bool bAllowContinousZoomInterpolation
bool bDrawGridLines
Should we render the grid lines?
bool bIsPanning
Are we panning the view at the moment?
bool bIsZooming
Are we zooming the view with trackpad at the moment?
bool bRequireControlToOverZoom
Does the user need to press Control in order to over-zoom.
bool bTeleportInsteadOfScrollingWhenZoomingToFit
FVector2D GridOrigin
The position in the grid to begin drawing at.
FVector2D MouseDownPositionAbsolute
int32 PreviousZoomLevel
Previous Zoom Level.
float TotalGestureMagnify
Cumulative magnify delta from trackpad gesture.
double TotalMouseDelta
The Y component of mouse drag (used when zooming)
FVector2D ViewOffset
The position within the graph at which the user is looking.
FVector2D ViewOffsetStart
int32 ZoomLevel
How zoomed in/out we are.
FCurveSequence ZoomLevelFade
Curve that handles fading the 'Zoom +X' text.
FCurveSequence ZoomLevelGraphFade
Fade on zoom for graph.
TUniquePtr< FZoomLevelsContainer > ZoomLevels
FVector2D ZoomStartOffset
Offset in the panel the user started the LMB+RMB zoom from.
FVector2D ZoomTargetBottomRight
FVector2D ZoomTargetTopLeft
FVector2D ZoomToFitPadding
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
The designer for widgets.
Allows for laying out widgets in a drag and drop environment.
Definition at line 46 of file SDesignerView.h.
Constructor & Destructor Documentation
~SDesignerView()
virtual SDesignerView::~SDesignerView () virtual
Member Function Documentation
AddReferencedObjects()
virtual void SDesignerView::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
References AddReferencedObjects().
Referenced by AddReferencedObjects().
BeginResizingArea()
void SDesignerView::BeginResizingArea ()
BeginTransaction()
void SDesignerView::BeginTransaction (const FText & SessionName) private
BindCommands()
void SDesignerView::BindCommands () private
BroadcastDesignerChanged()
void SDesignerView::BroadcastDesignerChanged () private
CanSetTransformMode()
bool SDesignerView::CanSetTransformMode (ETransformMode::Type InTransformMode) const private
ClearDropPreviews()
void SDesignerView::ClearDropPreviews () private
ClearExtensionWidgets()
void SDesignerView::ClearExtensionWidgets () private
ComputeAreaBounds()
virtual FSlateRect SDesignerView::ComputeAreaBounds () const override protected virtual
Reimplemented from SDesignSurface.
CreateExtensionWidgetsForSelection()
void SDesignerView::CreateExtensionWidgetsForSelection () private
CreateOverlayUI()
TSharedRef< SWidget > SDesignerView::CreateOverlayUI ()
References SWidget::SWidget(), and CreateOverlayUI().
Referenced by CreateOverlayUI().
CreateScreenFillEntry()
void SDesignerView::CreateScreenFillEntry (FMenuBuilder & MenuBuilder, EDesignPreviewSizeMode SizeMode) private
DeselectNonSequencerWidgets()
void SDesignerView::DeselectNonSequencerWidgets () private
DetermineDragDropPreviewWidgets()
void SDesignerView::DetermineDragDropPreviewWidgets (TArray< UWidget * > & OutWidgets, const FDragDropEvent & DragDropEvent, UWidgetTree * RootWidgetTree) private
DrawResolution()
void SDesignerView::DrawResolution (const FDebugResolution & Resolution, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId) const protected
References SWidget::FSlateWindowElementList.
DrawSafeZone()
void SDesignerView::DrawSafeZone (const FOnPaintHandlerParams & PaintArgs) private
DrawSelectionAndHoverOutline()
void SDesignerView::DrawSelectionAndHoverOutline (const FOnPaintHandlerParams & PaintArgs) private
EndResizingArea()
void SDesignerView::EndResizingArea ()
EndTransaction()
void SDesignerView::EndTransaction (bool bCancel) private
EnsureTick()
EActiveTimerReturnType SDesignerView::EnsureTick (double InCurrentTime, float InDeltaTime)
References EnsureTick().
Referenced by EnsureTick().
FindWidgetUnderCursor()
bool SDesignerView::FindWidgetUnderCursor (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent, TSubclassOf< UWidget > FindType, FWidgetHitResult & HitResult) private
Returns
Gets the widget under the cursor based on a mouse pointer event.
References MouseEvent.
GetAreaResizeHandlePosition()
FVector2D SDesignerView::GetAreaResizeHandlePosition () const private
GetAreaResizeHandleVisibility()
EVisibility SDesignerView::GetAreaResizeHandleVisibility () const private
GetAspectRatioSwitchEnabled()
bool SDesignerView::GetAspectRatioSwitchEnabled () const private
GetAspectRatioSwitchImage()
const FSlateBrush * SDesignerView::GetAspectRatioSwitchImage () const private
GetBlueprint()
UWidgetBlueprint * SDesignerView::GetBlueprint () const private
Gets the blueprint being edited by the designer.
GetCurrentDPIScaleColor()
FSlateColor SDesignerView::GetCurrentDPIScaleColor () const private
GetCurrentDPIScaleText()
FText SDesignerView::GetCurrentDPIScaleText () const private
GetCurrentResolutionText()
FText SDesignerView::GetCurrentResolutionText () const private
GetCurrentSafeZoneText()
FText SDesignerView::GetCurrentSafeZoneText () const private
GetCurrentScaleFactorText()
FText SDesignerView::GetCurrentScaleFactorText () const private
GetCursorPositionText()
FText SDesignerView::GetCursorPositionText () const private
GetCursorPositionTextVisibility()
EVisibility SDesignerView::GetCursorPositionTextVisibility () const private
GetCustomResolutionEntryVisibility()
EVisibility SDesignerView::GetCustomResolutionEntryVisibility () const private
GetCustomResolutionHeight()
TOptional< int32 > SDesignerView::GetCustomResolutionHeight () const private
GetCustomResolutionWidth()
TOptional< int32 > SDesignerView::GetCustomResolutionWidth () const private
GetDefaultWidget()
UUserWidget * SDesignerView::GetDefaultWidget () const private
GetDesignerGeometry()
virtual FGeometry SDesignerView::GetDesignerGeometry () const override virtual
Returns
The Geometry representing the designer area, useful for when you need to convert mouse into designer space.
Implements IUMGDesigner.
References GetDesignerGeometry().
Referenced by GetDesignerGeometry().
GetDesignerOutlineColor()
FSlateColor SDesignerView::GetDesignerOutlineColor () const private
GetDesignerOutlineText()
FText SDesignerView::GetDesignerOutlineText () const private
GetDesignerOutlineVisibility()
EVisibility SDesignerView::GetDesignerOutlineVisibility () const private
GetExtensionCanvasVisibility()
EVisibility SDesignerView::GetExtensionCanvasVisibility () const private
GetExtensionPosition()
FVector2D SDesignerView::GetExtensionPosition (TSharedRef< FDesignerSurfaceElement > ExtensionElement) const private
GetExtensionSize()
FVector2D SDesignerView::GetExtensionSize (TSharedRef< FDesignerSurfaceElement > ExtensionElement) const private
GetFlipDeviceEnabled()
bool SDesignerView::GetFlipDeviceEnabled () const private
GetGraphRulePeriod()
virtual int32 SDesignerView::GetGraphRulePeriod () const override protected virtual
Reimplemented from SDesignSurface.
GetGridScaleAmount()
virtual float SDesignerView::GetGridScaleAmount () const override protected virtual
Reimplemented from SDesignSurface.
GetInfoBarText()
FText SDesignerView::GetInfoBarText () const private
GetInfoBarVisibility()
EVisibility SDesignerView::GetInfoBarVisibility () const private
GetIsScreenFillRuleSelected()
bool SDesignerView::GetIsScreenFillRuleSelected (EDesignPreviewSizeMode SizeMode) const private
GetPreviewAreaHeight()
FOptionalSize SDesignerView::GetPreviewAreaHeight () const
The height of the preview screen for the UI.
GetPreviewAreaWidth()
FOptionalSize SDesignerView::GetPreviewAreaWidth () const
The width of the preview screen for the UI.
GetPreviewBackground()
const FSlateBrush * SDesignerView::GetPreviewBackground () const private
GetPreviewDPIScale()
float SDesignerView::GetPreviewDPIScale () const
Gets the DPI scale that would be applied given the current preview width and height.
GetPreviewScale()
virtual float SDesignerView::GetPreviewScale () const override virtual
Returns
the effective preview scale after both the DPI and Zoom scale has been applied.
Implements IUMGDesigner.
References GetPreviewScale().
Referenced by GetPreviewScale().
GetPreviewSizeHeight()
FOptionalSize SDesignerView::GetPreviewSizeHeight () const
The height of the preview widget for the UI.
GetPreviewSizeWidth()
FOptionalSize SDesignerView::GetPreviewSizeWidth () const
The width of the preview widget for the UI.
GetReferencerName()
virtual FString SDesignerView::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 100 of file SDesignerView.h.
References GetReferencerName(), and TEXT.
Referenced by GetReferencerName().
GetRelevantSettings()
const UWidgetEditingProjectSettings * SDesignerView::GetRelevantSettings () const
GetResolutionMenuAction()
FUIAction SDesignerView::GetResolutionMenuAction (const FPlayScreenResolution & ScreenResolution) private
GetResolutionsMenu()
TSharedRef< SWidget > SDesignerView::GetResolutionsMenu () private
GetResolutionText()
FText SDesignerView::GetResolutionText (int32 Width, int32 Height, const FString & AspectRatio) const private
Returns
Formatted text for the given resolution params
References Width.
GetResolutionTextColorAndOpacity()
FSlateColor SDesignerView::GetResolutionTextColorAndOpacity () const private
GetResolutionTextVisibility()
EVisibility SDesignerView::GetResolutionTextVisibility () const private
GetRulerVisibility()
EVisibility SDesignerView::GetRulerVisibility () const private
GetScreenSizingFillMenu()
TSharedRef< SWidget > SDesignerView::GetScreenSizingFillMenu () private
GetScreenSizingFillText()
FText SDesignerView::GetScreenSizingFillText () const private
GetSelectedWidget()
virtual FWidgetReference SDesignerView::GetSelectedWidget () const override virtual
Returns
The currently selected widget.
Implements IUMGDesigner.
References GetSelectedWidget().
Referenced by GetSelectedWidget().
GetSelectedWidgetDimensionsText()
FText SDesignerView::GetSelectedWidgetDimensionsText () const private
GetSelectedWidgetDimensionsVisibility()
EVisibility SDesignerView::GetSelectedWidgetDimensionsVisibility () const private
GetSelectedWidgets()
virtual const TSet< FWidgetReference > & SDesignerView::GetSelectedWidgets () const override virtual
Returns
The currently selected widgets
Implements IUMGDesigner.
References GetSelectedWidgets().
Referenced by GetSelectedWidgets().
GetSelectionLimitedTextVisibility()
EVisibility SDesignerView::GetSelectionLimitedTextVisibility () const private
GetSnapGridSize()
virtual int32 SDesignerView::GetSnapGridSize () const override protected virtual
Implements SDesignSurface.
GetTransformMode()
virtual ETransformMode::Type SDesignerView::GetTransformMode () const override virtual
Returns
Get the transform mode currently in use in the designer.
Implements IUMGDesigner.
References GetTransformMode().
Referenced by GetTransformMode().
GetWidgetGeometry() [1/2]
virtual bool SDesignerView::GetWidgetGeometry (const FWidgetReference & Widget, FGeometry & Geometry) const override virtual
Gets the previous frames widget geometry.
Implements IUMGDesigner.
References Geometry, and GetWidgetGeometry().
Referenced by GetWidgetGeometry(), and GetWidgetGeometry().
GetWidgetGeometry() [2/2]
virtual bool SDesignerView::GetWidgetGeometry (const UWidget * PreviewWidget, FGeometry & Geometry) const override virtual
Gets the previous frames widget geometry.
Implements IUMGDesigner.
References Geometry, GetWidgetGeometry(), and PreviewWidget.
GetWidgetInDesignScopeFromSlateWidget()
UWidget * SDesignerView::GetWidgetInDesignScopeFromSlateWidget (TSharedRef< SWidget > & InWidget) private
GetWidgetOriginAbsolute()
virtual FVector2D SDesignerView::GetWidgetOriginAbsolute () const virtual
References GetWidgetOriginAbsolute().
Referenced by GetWidgetOriginAbsolute().
GetWidgetParentGeometry()
virtual bool SDesignerView::GetWidgetParentGeometry (const FWidgetReference & Widget, FGeometry & Geometry) const override virtual
Gets the previous frames widget geometry of the parent of the provided widget.
Implements IUMGDesigner.
References Geometry, and GetWidgetParentGeometry().
Referenced by GetWidgetParentGeometry().
HandleDPISettingsClicked()
FReply SDesignerView::HandleDPISettingsClicked () private
HandleEffectsPainting()
int32 SDesignerView::HandleEffectsPainting (const FOnPaintHandlerParams & PaintArgs) private
HandleFlipSafeZonesClicked()
FReply SDesignerView::HandleFlipSafeZonesClicked () private
HandleIsCommonResolutionSelected()
bool SDesignerView::HandleIsCommonResolutionSelected (const FPlayScreenResolution InResolution) const private
HandleOnCommonResolutionSelected()
void SDesignerView::HandleOnCommonResolutionSelected (const FPlayScreenResolution InResolution) private
HandleSwapAspectRatioClicked()
FReply SDesignerView::HandleSwapAspectRatioClicked () private
HandleZoomToFitClicked()
FReply SDesignerView::HandleZoomToFitClicked () private
InTransaction()
bool SDesignerView::InTransaction () const private
IsRespectingLocks()
bool SDesignerView::IsRespectingLocks () const private
IsSelectableInSequencer()
bool SDesignerView::IsSelectableInSequencer (UWidget *const InWidget) const private
IsShowingOutlines()
bool SDesignerView::IsShowingOutlines () const private
IsTransformModeActive()
bool SDesignerView::IsTransformModeActive (ETransformMode::Type InTransformMode) const private
MakeGeometryWindowLocal()
virtual FGeometry SDesignerView::MakeGeometryWindowLocal (const FGeometry & WidgetGeometry) const override virtual
Takes geometry and adds the inverse of the window transform to get the geometry in the space of the window.
Implements IUMGDesigner.
References MakeGeometryWindowLocal().
Referenced by MakeGeometryWindowLocal().
MarkDesignModifed()
virtual void SDesignerView::MarkDesignModifed (bool bRequiresRecompile) override virtual
Marks the designer content as being modified.
Implements IUMGDesigner.
References MarkDesignModifed().
Referenced by MarkDesignModifed().
MoveWidgets()
void SDesignerView::MoveWidgets (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent, const bool bIsPreview, UWidget * Target, const bool bAnyWidgetChangingParent) private
References Target.
NudgeSelectedWidget()
FReply SDesignerView::NudgeSelectedWidget (FVector2D Nudge) private
Move the selected widget by the nudge amount.
OnCustomResolutionHeightChanged()
void SDesignerView::OnCustomResolutionHeightChanged (int32 InValue) private
OnCustomResolutionWidthChanged()
void SDesignerView::OnCustomResolutionWidthChanged (int32 InValue) private
OnDragDetected()
virtual FReply SDesignerView::OnDragDetected (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Called when Slate detects that a widget started to be dragged.
Usage: A widget can ask Slate to detect a drag. OnMouseDown() reply with FReply::Handled().DetectDrag(SharedThis(this)). Slate will either send an OnDragDetected() event or do nothing. If the user releases a mouse button or leaves the widget before a drag is triggered (maybe user started at the very edge) then no event will be sent.
Parameters
InMyGeometry Widget geometry
InMouseEvent MouseMove that triggered the drag
Reimplemented from SWidget.
References MouseEvent, and OnDragDetected().
Referenced by OnDragDetected().
OnDragEnter()
virtual void SDesignerView::OnDragEnter (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the drag enters a widget.
Enter/Leave events in slate are meant as lightweight notifications. So we do not want to capture mouse or set focus in response to these. However, OnDragEnter must also support external APIs (e.g. OLE Drag/Drop) Those require that we let them know whether we can handle the content being dragged OnDragEnter.
The concession is to return a can_handled/cannot_handle boolean rather than a full FReply.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether the contents of the DragDropEvent can potentially be processed by this widget.
Reimplemented from SWidget.
References OnDragEnter().
Referenced by OnDragEnter().
OnDragLeave()
virtual void SDesignerView::OnDragLeave (const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the drag leaves a widget.
Parameters
DragDropEvent The drag and drop event.
Reimplemented from SWidget.
References OnDragLeave().
Referenced by OnDragLeave().
OnDragOver()
virtual FReply SDesignerView::OnDragOver (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the the mouse is being dragged over a widget.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References OnDragOver().
Referenced by OnDragOver().
OnDrop()
virtual FReply SDesignerView::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References OnDrop().
Referenced by OnDrop().
OnEditorSelectionChanged()
void SDesignerView::OnEditorSelectionChanged () private
OnHoveredWidgetCleared()
void SDesignerView::OnHoveredWidgetCleared () private
Called when a widget is no longer being hovered.
OnHoveredWidgetSet()
void SDesignerView::OnHoveredWidgetSet (const FWidgetReference & InHoveredWidget) private
Called when a new widget is being hovered.
OnKeyDown()
virtual FReply SDesignerView::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
OnKeyUp()
virtual FReply SDesignerView::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyUp().
Referenced by OnKeyUp().
OnMouseButtonDown()
virtual FReply SDesignerView::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SDesignSurface.
References MouseEvent, and OnMouseButtonDown().
Referenced by OnMouseButtonDown().
OnMouseButtonUp()
virtual FReply SDesignerView::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SDesignSurface.
References MouseEvent, and OnMouseButtonUp().
Referenced by OnMouseButtonUp().
OnMouseEnter()
virtual void SDesignerView::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent, and OnMouseEnter().
Referenced by OnMouseEnter().
OnMouseLeave()
virtual void SDesignerView::OnMouseLeave (const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent, and OnMouseLeave().
Referenced by OnMouseLeave().
OnMouseMove()
virtual FReply SDesignerView::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SDesignSurface.
References MouseEvent, and OnMouseMove().
Referenced by OnMouseMove().
OnPaintBackground()
virtual void SDesignerView::OnPaintBackground (const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId) const override protected virtual
Reimplemented from SDesignSurface.
References SWidget::FSlateWindowElementList.
OnPreviewNeedsRecreation()
void SDesignerView::OnPreviewNeedsRecreation () private
Called whenever the blueprint is recompiled or the preview is updated.
OnScreenFillRuleSelected()
void SDesignerView::OnScreenFillRuleSelected (EDesignPreviewSizeMode SizeMode) private
OnSelectedAnimationChanged()
void SDesignerView::OnSelectedAnimationChanged () private
OnSelectionLimitedChanged()
void SDesignerView::OnSelectionLimitedChanged (const bool bInEnabled) private
PopDesignerMessage()
virtual void SDesignerView::PopDesignerMessage () override virtual
Removes the last message from the message stack.
Implements IUMGDesigner.
References PopDesignerMessage().
Referenced by PopDesignerMessage().
PopulateWidgetGeometryCache()
void SDesignerView::PopulateWidgetGeometryCache (FArrangedWidget & Root) private
References Root.
PopulateWidgetGeometryCache_Loop()
void SDesignerView::PopulateWidgetGeometryCache_Loop (FArrangedWidget & Parent) private
References Parent.
ProcessDropAndAddWidget()
void SDesignerView::ProcessDropAndAddWidget (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent, const bool bIsPreview) private
PushDesignerMessage()
virtual void SDesignerView::PushDesignerMessage (const FText & Message) override virtual
Push a new designer message to show at the bottom of the screen.
Don't forget to call PopDesignerMessage when complete.
Implements IUMGDesigner.
References PushDesignerMessage().
Referenced by PushDesignerMessage().
Register()
void SDesignerView::Register (TSharedRef< FDesignerExtension > Extension)
References Register().
Referenced by Register().
RegisterExtensions()
void SDesignerView::RegisterExtensions () private
ResolvePendingSelectedWidgets()
void SDesignerView::ResolvePendingSelectedWidgets () private
Adds any pending selected widgets to the selection set.
SetPreviewAreaSize()
void SDesignerView::SetPreviewAreaSize (int32 Width, int32 Height)
Set the size of the preview screen for the UI.
References Width.
SetStartupResolution()
void SDesignerView::SetStartupResolution () private
Establishes the resolution and aspect ratio to use on construction from config settings.
SetTransformMode()
void SDesignerView::SetTransformMode (ETransformMode::Type InTransformMode) private
ShowContextMenu()
void SDesignerView::ShowContextMenu (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) private
Displays the context menu when you right click.
References MouseEvent.
SLATE_BEGIN_ARGS()
SDesignerView::SLATE_BEGIN_ARGS (SDesignerView) inline
Definition at line 50 of file SDesignerView.h.
SLATE_END_ARGS()
SDesignerView::SLATE_END_ARGS () const &
SwapSafeZoneTypes()
void SDesignerView::SwapSafeZoneTypes () private
Tick()
virtual void SDesignerView::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SDesignSurface.
References Tick().
Referenced by Tick().
ToggleRespectingLocks()
void SDesignerView::ToggleRespectingLocks () private
ToggleShowingOutlines()
void SDesignerView::ToggleShowingOutlines () private
Unregister()
void SDesignerView::Unregister (TSharedRef< FDesignerExtension > Extension)
References Unregister().
Referenced by Unregister().
UpdatePreviewWidget()
void SDesignerView::UpdatePreviewWidget (bool bForceUpdate) private
Updates the designer to display the latest preview widget.
Field Documentation
BackgroundImage
FSlateBrush SDesignerView::BackgroundImage mutable private
The slate brush we use to hold the background image shown in the designer.
Definition at line 387 of file SDesignerView.h.
bCanPreviewSwapAspectRatio
bool SDesignerView::bCanPreviewSwapAspectRatio private
Definition at line 396 of file SDesignerView.h.
bCommonResolutionSelected
bool SDesignerView::bCommonResolutionSelected private
Definition at line 381 of file SDesignerView.h.
BlueprintEditor
TWeakPtr<FWidgetBlueprintEditor> SDesignerView::BlueprintEditor private
A reference to the BP Editor that owns this designer.
Definition at line 314 of file SDesignerView.h.
bMovingExistingWidget
bool SDesignerView::bMovingExistingWidget private
An existing widget is being moved in its current container, or in to a new container.
Definition at line 366 of file SDesignerView.h.
bPreviewIsPortrait
bool SDesignerView::bPreviewIsPortrait private
Definition at line 405 of file SDesignerView.h.
bSafeZoneFlipped
bool SDesignerView::bSafeZoneFlipped private
Definition at line 402 of file SDesignerView.h.
bShowResolutionOutlines
bool SDesignerView::bShowResolutionOutlines private
Definition at line 384 of file SDesignerView.h.
CachedMousePosition
FVector2D SDesignerView::CachedMousePosition private
Cache last mouse position to be used as a paste drop location.
Definition at line 329 of file SDesignerView.h.
CachedPreviewDesiredSize
FVector2D SDesignerView::CachedPreviewDesiredSize private
We cache the desired preview desired size to maintain the same size between compiles when it lags a frame behind and no widget is available.
Definition at line 390 of file SDesignerView.h.
CachedWidgetGeometry
TMap<TSharedRef<SWidget>, FArrangedWidget> SDesignerView::CachedWidgetGeometry private
Definition at line 426 of file SDesignerView.h.
CommandList
TSharedPtr<FUICommandList> SDesignerView::CommandList private
The designer command list.
Definition at line 317 of file SDesignerView.h.
ConfigSectionName
const FString SDesignerView::ConfigSectionName static private
Definition at line 270 of file SDesignerView.h.
CustomSafeZoneDimensions
TArray<FVector2D> SDesignerView::CustomSafeZoneDimensions private
Definition at line 436 of file SDesignerView.h.
CustomSafeZoneStarts
TArray<FVector2D> SDesignerView::CustomSafeZoneStarts private
Definition at line 434 of file SDesignerView.h.
DefaultPreviewOverrideName
const FString SDesignerView::DefaultPreviewOverrideName static private
Definition at line 271 of file SDesignerView.h.
DesignerControls
TSharedPtr<SCanvas> SDesignerView::DesignerControls private
Definition at line 345 of file SDesignerView.h.
DesignerExtensions
TArray< TSharedRef<FDesignerExtension> > SDesignerView::DesignerExtensions private
Extensions for the designer to allow for custom widgets to be inserted onto the design surface as selection changes.
Definition at line 274 of file SDesignerView.h.
DesignerHittestGrid
TSharedPtr<FHittestGrid> SDesignerView::DesignerHittestGrid private
Definition at line 429 of file SDesignerView.h.
DesignerMessageStack
TArray<FText> SDesignerView::DesignerMessageStack private
The message stack to display the last item to the user in a non-modal fashion.
Definition at line 432 of file SDesignerView.h.
DesignerSafeZoneOverride
FMargin SDesignerView::DesignerSafeZoneOverride private
Definition at line 438 of file SDesignerView.h.
DesignerWidgetCanvas
TSharedPtr<SCanvas> SDesignerView::DesignerWidgetCanvas private
Definition at line 346 of file SDesignerView.h.
DraggingStartPositionScreenSpace
FVector2D SDesignerView::DraggingStartPositionScreenSpace private
The position in screen space where the user began dragging a widget.
Definition at line 363 of file SDesignerView.h.
DropPreviews
TArray<FDropPreview> SDesignerView::DropPreviews private
Definition at line 338 of file SDesignerView.h.
EffectsLayer
TSharedPtr<SPaintSurface> SDesignerView::EffectsLayer private
Definition at line 348 of file SDesignerView.h.
ExtensionWidgetCanvas
TSharedPtr<SCanvas> SDesignerView::ExtensionWidgetCanvas private
Definition at line 347 of file SDesignerView.h.
HeightReadFromSettings
int32 SDesignerView::HeightReadFromSettings private
The original Height of the preview area, read from the settings file.
Definition at line 378 of file SDesignerView.h.
HoveredWidgetOutlineFade
FCurveSequence SDesignerView::HoveredWidgetOutlineFade private
Curve to handle the fade-in of the border around the hovered widget.
Definition at line 411 of file SDesignerView.h.
InBlueprintEditor
TSharedPtr<class FWidgetBlueprintEditor> SDesignerView::InBlueprintEditor
Definition at line 53 of file SDesignerView.h.
PendingSelectedWidget
FWidgetReference SDesignerView::PendingSelectedWidget private
Holds onto a temporary widget that the user may be getting ready to select, or may just be the widget that got hit on the initial mouse down before moving the parent.
Definition at line 360 of file SDesignerView.h.
PreviewAreaConstraint
TSharedPtr<SBox> SDesignerView::PreviewAreaConstraint private
Definition at line 341 of file SDesignerView.h.
PreviewAspectRatio
FString SDesignerView::PreviewAspectRatio private
Definition at line 393 of file SDesignerView.h.
PreviewHeight
int32 SDesignerView::PreviewHeight private
The configured Height of the preview area, simulates screen size.
Definition at line 372 of file SDesignerView.h.
PreviewHitTestRoot
TSharedPtr<SWidget> SDesignerView::PreviewHitTestRoot private
Definition at line 340 of file SDesignerView.h.
PreviewOverrideName
FString SDesignerView::PreviewOverrideName private
Definition at line 398 of file SDesignerView.h.
PreviewSizeConstraint
TSharedPtr<SBox> SDesignerView::PreviewSizeConstraint private
Definition at line 343 of file SDesignerView.h.
PreviewSlateWidget
TWeakPtr<SWidget> SDesignerView::PreviewSlateWidget private
The current preview widget's slate widget.
Definition at line 326 of file SDesignerView.h.
PreviewSurface
TSharedPtr<SDPIScaler> SDesignerView::PreviewSurface private
Definition at line 342 of file SDesignerView.h.
PreviewWidget
TObjectPtr<UUserWidget> SDesignerView::PreviewWidget private
The current preview widget.
Definition at line 323 of file SDesignerView.h.
Referenced by GetWidgetGeometry().
PreviewWidth
int32 SDesignerView::PreviewWidth private
The configured Width of the preview area, simulates screen size.
Definition at line 369 of file SDesignerView.h.
ResolutionTextFade
FCurveSequence SDesignerView::ResolutionTextFade private
Curve to handle fading of the resolution.
Definition at line 408 of file SDesignerView.h.
ScaleFactor
float SDesignerView::ScaleFactor private
Definition at line 400 of file SDesignerView.h.
ScopedTransaction
FScopedTransaction* SDesignerView::ScopedTransaction private
The transaction used to commit undoable actions from resize, move...etc.
Definition at line 320 of file SDesignerView.h.
SelectedWidgetContextMenuLocation
FVector2D SDesignerView::SelectedWidgetContextMenuLocation private
The location in selected widget local space where the context menu was summoned.
Definition at line 354 of file SDesignerView.h.
SelectedWidgetPath
FWeakWidgetPath SDesignerView::SelectedWidgetPath private
Definition at line 414 of file SDesignerView.h.
SelectedWidgetsCache
TSet< FWidgetReference > SDesignerView::SelectedWidgetsCache private
The currently selected preview widgets in the preview GUI, just a cache used to determine changes between selection changes.
Definition at line 351 of file SDesignerView.h.
SideRuler
TSharedPtr<SRuler> SDesignerView::SideRuler private
The ruler bar on the left side of the designer.
Definition at line 420 of file SDesignerView.h.
TopRuler
TSharedPtr<SRuler> SDesignerView::TopRuler private
The ruler bar at the top of the designer.
Definition at line 417 of file SDesignerView.h.
TransformMode
ETransformMode::Type SDesignerView::TransformMode private
Definition at line 423 of file SDesignerView.h.
WidthReadFromSettings
int32 SDesignerView::WidthReadFromSettings private
The original Width of the preview area, read from the settings file.
Definition at line 375 of file SDesignerView.h.
The documentation for this class was generated from the following file:
Editor/UMGEditor/Public/Designer/SDesignerView.h