Unreal Engine 5.6 C++ API: FDetailWidgetDecl Class Reference
FDetailWidgetDecl Class Reference
Widget declaration for custom widgets in a widget row.
#include "DetailWidgetRow.h"
Data Structures
class SInvalidDetailWidget
Public Member Functions
FDetailWidgetDecl (class FDetailWidgetRow &InParentDecl, const FDetailWidgetDecl &Other)
FDetailWidgetDecl (class FDetailWidgetRow &InParentDecl, float InMinWidth, float InMaxWidth, EHorizontalAlignment InHAlign, EVerticalAlignment InVAlign)
FDetailWidgetDecl & HAlign (EHorizontalAlignment InAlignment)
FDetailWidgetDecl & MaxDesiredWidth (TOptional< float > InMaxWidth)
FDetailWidgetDecl & MinDesiredWidth (TOptional< float > InMinWidth)
FDetailWidgetRow & operator[] (TSharedRef< SWidget > InWidget)
FDetailWidgetDecl & VAlign (EVerticalAlignment InAlignment)
Data Fields
EHorizontalAlignment HorizontalAlignment
TOptional< float > MaxWidth
TOptional< float > MinWidth
EVerticalAlignment VerticalAlignment
TSharedRef< SWidget > Widget
Private Attributes
class FDetailWidgetRow * ParentDecl
Detailed Description
Widget declaration for custom widgets in a widget row.
Definition at line 22 of file DetailWidgetRow.h.
Constructor & Destructor Documentation
FDetailWidgetDecl() [1/2]
FDetailWidgetDecl::FDetailWidgetDecl (class FDetailWidgetRow & InParentDecl, float InMinWidth, float InMaxWidth, EHorizontalAlignment InHAlign, EVerticalAlignment InVAlign) inline
Definition at line 26 of file DetailWidgetRow.h.
References HorizontalAlignment, MaxWidth, MinWidth, ParentDecl, SNew, VerticalAlignment, and Widget.
Referenced by FDetailWidgetDecl(), HAlign(), MaxDesiredWidth(), MinDesiredWidth(), and VAlign().
FDetailWidgetDecl() [2/2]
FDetailWidgetDecl::FDetailWidgetDecl (class FDetailWidgetRow & InParentDecl, const FDetailWidgetDecl & Other) inline
Definition at line 36 of file DetailWidgetRow.h.
References FDetailWidgetDecl(), HorizontalAlignment, MaxWidth, MinWidth, Other, ParentDecl, VerticalAlignment, and Widget.
Member Function Documentation
HAlign()
FDetailWidgetDecl & FDetailWidgetDecl::HAlign (EHorizontalAlignment InAlignment) inline
Definition at line 58 of file DetailWidgetRow.h.
References FDetailWidgetDecl(), and HorizontalAlignment.
MaxDesiredWidth()
FDetailWidgetDecl & FDetailWidgetDecl::MaxDesiredWidth (TOptional< float > InMaxWidth) inline
Definition at line 70 of file DetailWidgetRow.h.
References FDetailWidgetDecl(), and MaxWidth.
Referenced by FGameModeInfoCustomizer::CustomizeGameModeSetting().
MinDesiredWidth()
FDetailWidgetDecl & FDetailWidgetDecl::MinDesiredWidth (TOptional< float > InMinWidth) inline
Definition at line 64 of file DetailWidgetRow.h.
References FDetailWidgetDecl(), and MinWidth.
operator[]()
FDetailWidgetRow & FDetailWidgetDecl::operator[] (TSharedRef< SWidget > InWidget) inline
Definition at line 46 of file DetailWidgetRow.h.
References ParentDecl, and Widget.
VAlign()
FDetailWidgetDecl & FDetailWidgetDecl::VAlign (EVerticalAlignment InAlignment) inline
Definition at line 52 of file DetailWidgetRow.h.
References FDetailWidgetDecl(), and VerticalAlignment.
Field Documentation
HorizontalAlignment
EHorizontalAlignment FDetailWidgetDecl::HorizontalAlignment
Definition at line 91 of file DetailWidgetRow.h.
Referenced by FDetailWidgetDecl(), FDetailWidgetDecl(), and HAlign().
MaxWidth
TOptional<float> FDetailWidgetDecl::MaxWidth
Definition at line 94 of file DetailWidgetRow.h.
Referenced by FDetailWidgetDecl(), FDetailWidgetDecl(), and MaxDesiredWidth().
MinWidth
TOptional<float> FDetailWidgetDecl::MinWidth
Definition at line 93 of file DetailWidgetRow.h.
Referenced by FDetailWidgetDecl(), FDetailWidgetDecl(), and MinDesiredWidth().
ParentDecl
class FDetailWidgetRow* FDetailWidgetDecl::ParentDecl private
Definition at line 96 of file DetailWidgetRow.h.
Referenced by FDetailWidgetDecl(), FDetailWidgetDecl(), and operator[]().
VerticalAlignment
EVerticalAlignment FDetailWidgetDecl::VerticalAlignment
Definition at line 92 of file DetailWidgetRow.h.
Referenced by FDetailWidgetDecl(), FDetailWidgetDecl(), and VAlign().
Widget
TSharedRef<SWidget> FDetailWidgetDecl::Widget
Definition at line 90 of file DetailWidgetRow.h.
Referenced by FDetailWidgetDecl(), FDetailWidgetDecl(), and operator[]().
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/DetailWidgetRow.h