Unreal Engine 5.6 C++ API: UE::UnifiedError::FTextFormatArgsPropertyExtractor Class Reference
UE::UnifiedError::FTextFormatArgsPropertyExtractor Class Reference
#include "UnifiedError.h"
Public Member Functions
FTextFormatArgsPropertyExtractor (FFormatNamedArguments &InArguments)
virtual void AddProperty (const FUtf8StringView &PropertyName, const double PropertyValue) override
virtual void AddProperty (const FUtf8StringView &PropertyName, const float PropertyValue) override
virtual void AddProperty (const FUtf8StringView &PropertyName, const FStringView &PropertyValue) override
virtual void AddProperty (const FUtf8StringView &PropertyName, const FText &PropertyValue) override
virtual void AddProperty (const FUtf8StringView &PropertyName, const FUtf8StringView &PropertyValue) override
virtual void AddProperty (const FUtf8StringView &PropertyName, const int32 PropertyValue) override
virtual void AddProperty (const FUtf8StringView &PropertyName, const int64 PropertyValue) override
Private Attributes
FFormatNamedArguments & Arguments
Detailed Description
Definition at line 530 of file UnifiedError.h.
Constructor & Destructor Documentation
FTextFormatArgsPropertyExtractor()
UE::UnifiedError::FTextFormatArgsPropertyExtractor::FTextFormatArgsPropertyExtractor (FFormatNamedArguments & InArguments) inline
Definition at line 535 of file UnifiedError.h.
References Arguments.
Member Function Documentation
AddProperty() [1/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const double PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 564 of file UnifiedError.h.
References Arguments, PropertyName, and UTF8_TO_TCHAR.
AddProperty() [2/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const float PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 559 of file UnifiedError.h.
References Arguments, PropertyName, and UTF8_TO_TCHAR.
AddProperty() [3/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const FStringView & PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 539 of file UnifiedError.h.
References Arguments, FText::FromString(), TStringView< CharType >::GetData(), PropertyName, and UTF8_TO_TCHAR.
AddProperty() [4/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const FText & PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 569 of file UnifiedError.h.
References Arguments, PropertyName, and UTF8_TO_TCHAR.
AddProperty() [5/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const FUtf8StringView & PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 544 of file UnifiedError.h.
References Arguments, FText::FromStringView(), TStringView< CharType >::GetData(), PropertyName, and UTF8_TO_TCHAR.
AddProperty() [6/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const int32 PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 554 of file UnifiedError.h.
References Arguments, PropertyName, and UTF8_TO_TCHAR.
AddProperty() [7/7]
virtual void UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty (const FUtf8StringView & PropertyName, const int64 PropertyValue) inline override virtual
Implements UE::UnifiedError::IErrorPropertyExtractor.
Definition at line 549 of file UnifiedError.h.
References Arguments, PropertyName, and UTF8_TO_TCHAR.
Field Documentation
Arguments
FFormatNamedArguments& UE::UnifiedError::FTextFormatArgsPropertyExtractor::Arguments private
Definition at line 533 of file UnifiedError.h.
Referenced by FTextFormatArgsPropertyExtractor(), AddProperty(), AddProperty(), AddProperty(), AddProperty(), AddProperty(), AddProperty(), and AddProperty().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/UnifiedError/UnifiedError.h