Unreal Engine 5.6 C++ API: FLazyObjectProperty Class Reference
FLazyObjectProperty Class Reference
#include "UnrealType.h"
Public Member Functions
virtual bool AllowCrossLevel () const override
Public Member Functions inherited from TFObjectPropertyBase< FLazyObjectPtr >
TFObjectPropertyBase (EInternal InInernal, FFieldClass *InClass)
virtual bool ContainsObjectReference (TArray< const FStructProperty * > &EncounteredStructProps, EPropertyObjectReferenceType InReferenceType=EPropertyObjectReferenceType::Strong) const override
Returns true if this property, or in the case of e.g.
Public Member Functions inherited from TProperty< FLazyObjectPtr, FObjectPropertyBase >
TProperty (EInternal InInernal, FFieldClass *InClass)
virtual void ClearIntrusiveOptionalValue (void *Data) const override
virtual void ClearValueInternal (void *Data) const override
virtual void CopyValuesInternal (void *Dest, void const *Src, int32 Count) const override
virtual void DestroyValueInternal (void *Dest) const override
virtual int32 GetMinAlignment () const override
FORCEINLINE TCppType GetOptionalPropertyValue_InContainer (void const *B, int32 ArrayIndex=0) const
Get the value of the property from a container address, unless it is NULL, then return the default value.
FORCEINLINE TCppType const & GetPropertyValue_InContainer (void const *A, int32 ArrayIndex=0) const
Get the value of the property from a container address.
FORCEINLINE TCppType const * GetPropertyValuePtr_InContainer (void const *A, int32 ArrayIndex=0) const
Convert the address of a container to the address of the property value, in the proper type.
FORCEINLINE void GetValue_InContainer (void const *InContainer, TCppType *OutValue) const
virtual bool HasIntrusiveUnsetOptionalState () const override
virtual void InitializeIntrusiveUnsetOptionalValue (void *Data) const override
virtual void InitializeValueInternal (void *Dest) const override
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const override
virtual void LinkInternal (FArchive &Ar) override
FORCEINLINE void SetPropertyValue_InContainer (void *A, TCppType const &Value, int32 ArrayIndex=0) const
Set the value of a property in a container.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const TCppType &InValue) const
Public Member Functions inherited from FObjectPropertyBase
virtual bool AllowObjectTypeReinterpretationTo (const FObjectPropertyBase *Other) const
virtual void CheckValidObject (void *ValueAddress, TObjectPtr< UObject > OldValue, const void *Defaults=nullptr) const
virtual void InstanceSubobjects (void *Data, void const *DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph *InstanceGraph) override
Creates new copies of components.
virtual UObject * LoadObjectPropertyValue (const void *PropertyValueAddress) const
FORCEINLINE UObject * LoadObjectPropertyValue_InContainer (const void *PropertyValueAddress, int32 ArrayIndex=0) const
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const override
Attempt to resolve the given inner path info against this outer property to get the inner property value.
virtual bool SameType (const FProperty *Other) const override
returns true, if Other is property of exactly the same type
void SetObjectPropertyValue (void *PropertyValueAddress, UObject *Value) const
void SetObjectPropertyValue_InContainer (void *ContainerAddress, UObject *Value, int32 ArrayIndex=0) const
void SetObjectPtrPropertyValue (void *PropertyValueAddress, TObjectPtr< UObject > Ptr) const
void SetObjectPtrPropertyValue_InContainer (void *ContainerAddress, TObjectPtr< UObject > Ptr, int32 ArrayIndex=0) const
FORCEINLINE void SetPropertyClass (UClass *NewPropertyClass)
Setter function for this property's PropertyClass member.
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const override
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from FProperty
FProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithoutOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
void * AllocateAndInitializeValue () const
Allocates and initializes memory to hold a value this property represents.
virtual void CallGetter (const void *Container, void *OutValue) const
Calls the native getter function for this property.
virtual void CallSetter (void *Container, const void *InValue) const
Calls the native setter function for this property.
virtual bool CanSerializeFromTypeName (UE::FPropertyTypeName Type) const
Returns true if the type of this property matches the type name.
FORCEINLINE void ClearPropertyFlags (EPropertyFlags NewFlags)
FORCEINLINE void ClearValue (void *Data) const
Zeros the value for this property.
FORCEINLINE void ClearValue_InContainer (void *Data, int32 ArrayIndex=0) const
Zeros the value for this property.
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (UObject *ContainerPtr, int32 ArrayIndex=0) const
Get the pointer to property value in a supplied 'container'.
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (void const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void const *ContainerPtr, int32 ArrayIndex=0) const
bool ContainsFinishDestroy (TArray< const FStructProperty * > &EncounteredStructProps) const
Returns true if the property or any of the child properties should be cleared on FinishDestroy.
FORCEINLINE bool ContainsInstancedObjectProperty () const
Returns true if this property, or in the case of e.g.
bool ContainsWeakObjectReference () const
Returns true if this property, or in the case of e.g.
virtual EConvertFromTypeResult ConvertFromType (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, const uint8 *Defaults)
Allows a property to implement backwards compatibility handling for tagged properties.
FORCEINLINE void CopyCompleteValue (void *Dest, void const *Src) const
Copy the value for all elements of this property.
FORCEINLINE void CopyCompleteValue_InContainer (void *Dest, void const *Src) const
FORCEINLINE void CopySingleValue (void *Dest, void const *Src) const
Copy the value for a single element of this property.
void DestroyAndFreeValue (void *InMemory) const
Destroys and frees memory with a value this property represents.
FORCEINLINE void DestroyValue (void *Dest) const
Destroys the value for this property.
FORCEINLINE void DestroyValue_InContainer (void *Dest) const
Destroys the value for this property.
virtual void EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
virtual void EmitReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
bool ExportText_Direct (FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
FORCEINLINE bool ExportText_InContainer (int32 Index, FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_Direct (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_InContainer (FString &ValueStr, const void *Container, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void FinishDestroy (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
void FinishDestroy_InContainer (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
ELifetimeCondition GetBlueprintReplicationCondition () const
int32 GetElementSize () const
FString GetNameCPP () const
Returns the C++ name of the property, including the _DEPRECATED suffix if the property is deprecated.
FORCEINLINE int32 GetOffset_ForDebug () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForGC () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForInternal () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForUFunction () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ReplaceWith_ContainerPtrToValuePtr () const
Return offset of property from container base.
FProperty * GetOwnerProperty ()
Returns the first FProperty in this property's Outer chain that does not have a FProperty for an Outer.
const FProperty * GetOwnerProperty () const
FORCEINLINE EPropertyFlags GetPropertyFlags () const
Returns this property's propertyflags.
FORCEINLINE FProperty * GetRepOwner ()
Returns the replication owner, which is the property itself, or NULL if this isn't important for replication.
void GetSingleValue_InContainer (const void *InContainer, void *OutValue, int32 ArrayIndex) const
Copies a single value to OutValue even if the property represents a static array of values.
FORCEINLINE int32 GetSize () const
FORCEINLINE void GetValue_InContainer (void const *InContainer, void *OutValue) const
virtual void * GetValueAddressAtIndex_Direct (const FProperty *Inner, void *InValueAddress, int32 Index) const
Gets value address at given index inside of a static array or container.
uint32 GetValueTypeHash (const void *Src) const
Returns the hash value for an element of this property.
FORCEINLINE bool HasAllPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAnyPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
virtual bool HasGetter () const
Checks if this property as a native getter function.
virtual bool HasSetter () const
Checks if this property as a native setter function.
virtual bool HasSetterOrGetter () const
Checks if this property as a native setter or getter function.
bool Identical_InContainer (const void *A, const void *B, int32 ArrayIndex=0, uint32 PortFlags=0) const
Determines whether the property values are identical.
const TCHAR * ImportText_Direct (const TCHAR *Buffer, void *PropertyPtr, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
const TCHAR * ImportText_InContainer (const TCHAR *Buffer, void *Container, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
FORCEINLINE void InitializeValue (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE void InitializeValue_InContainer (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE bool IsEditorOnlyProperty () const
Editor-only properties are those that only are used with the editor is present or cannot be removed from serialisation.
FORCEINLINE bool IsInContainer (const UStruct *ContainerClass) const
See if the offset of this property is below the supplied container size.
FORCEINLINE bool IsInContainer (int32 ContainerSize) const
See if the offset of this property is below the supplied container size.
int32 Link (FArchive &Ar)
void LinkWithoutChangingOffset (FArchive &Ar)
virtual bool LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag *Tag=nullptr)
Restores this property and its owned properties from the type name.
void PerformOperationWithGetter (void *OutContainer, const void *DirectPropertyAddress, TFunctionRef< void(const void *)> DirectValueAccessFunc) const
Helper function for getting container / struct property value and performing operation directly on the value memory.
void PerformOperationWithSetter (void *OutContainer, void *DirectPropertyAddress, TFunctionRef< void(void *)> DirectValueAccessFunc) const
Helper function for setting container / struct property value and performing operation directly on the value memory.
virtual void SaveTypeName (UE::FPropertyTypeNameBuilder &Type) const
Saves the type name of this property and its owned properties.
void SerializeBinProperty (FStructuredArchive::FSlot Slot, void *Data, int32 ArrayIdx=-1)
Serializes the property with the struct's data residing in Data.
void SerializeNonMatchingBinProperty (FStructuredArchive::FSlot Slot, void *Data, void const *DefaultData, UStruct *DefaultStruct)
Serializes the property with the struct's data residing in Data, unless it matches the default.
void SetBlueprintReplicationCondition (ELifetimeCondition InBlueprintReplicationCondition)
void SetElementSize (int32 NewSize)
FORCEINLINE void SetPropertyFlags (EPropertyFlags NewFlags)
void SetSingleValue_InContainer (void *OutContainer, const void *InValue, int32 ArrayIndex) const
Copies a single value to the property even if the property represents a static array of values.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const void *InValue) const
bool ShouldDuplicateValue () const
Determines whether this property value is eligible for copying when duplicating an object.
bool ShouldPort (uint32 PortFlags=0) const
bool ShouldSerializeValue (FArchive &Ar) const
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow Visit(const FPropertyVisitorData &Data
virtual bool UseBinaryOrNativeSerialization (const FArchive &Ar) const
bool ValidateImportFlags (uint32 PortFlags, FOutputDevice *ErrorText=NULL) const
Verify that modifying this property's value via ImportText is allowed.
EPropertyVisitorControlFlow Visit (const FPropertyVisitorData &Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from FField
FField (EInternal InInernal, FFieldClass *InClass)
FField (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
virtual ~FField ()
virtual void AddCppProperty (FProperty *Property)
void AppendName (FString &ResultString) const
virtual void Bind ()
void ClearFlags (EObjectFlags NewFlags)
FString GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
uint64 GetCastFlags () const
FFieldClass * GetClass () const
virtual SIZE_T GetFieldSize () const
EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
FString GetFullName () const
virtual FField * GetInnerFieldByName (const FName &InName)
Returns an inner field by name if the field has any.
virtual void GetInnerFields (TArray< FField * > &OutFields)
Fills the provided array with all inner fields this field owns (recursively)
FLinkerLoad * GetLinker () const
FORCEINLINE FString GetName () const
FORCEINLINE void GetName (FString &OutName) const
UPackage * GetOutermost () const
Goes up the outer chain to look for the outermost package.
template<typename T>
T * GetOwner () const
template<typename T>
FUNCTION_NON_NULL_RETURN_START T * GetOwnerChecked () const FUNCTION_NON_NULL_RETURN_END
UClass * GetOwnerClass () const
Goes up the outer chain to look for a UClass.
UStruct * GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
UField * GetOwnerUField () const
Goes up the outer chain to look for a UField.
FORCEINLINE UObject * GetOwnerUObject () const
Goes up the outer chain to look for a UObject.
FFieldVariant GetOwnerVariant () const
Gets the owner container for this field.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=nullptr) const
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
template<typename T>
T * GetTypedOwner () const
FField * GetTypedOwner (FFieldClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
UObject * GetTypedOwner (UClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE UObject * InternalGetOwnerAsUObjectUnsafe () const
Internal function for quickly getting the owner of this object as UObject.
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *FieldType) const
bool IsIn (const FField *InOwner) const
bool IsIn (const UObject *InOwner) const
bool IsNative () const
bool IsRooted () const
bool IsValidLowLevel () const
virtual void PostLoad ()
void Rename (const FName &NewName)
void SetFlags (EObjectFlags NewFlags)
UE_DEPRECATED (5.0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAllCastFlags(const uint64 InCastFlags) const
UE_DEPRECATED (5.0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAnyCastFlags(const uint64 InCastFlags) const
Protected Member Functions
virtual void SetObjectPropertyValueUnchecked (void *PropertyValueAddress, UObject *Value) const override
virtual void SetObjectPropertyValueUnchecked_InContainer (void *ContainerAddress, UObject *Value, int32 ArrayIndex=0) const override
virtual void SetObjectPtrPropertyValueUnchecked (void *PropertyValueAddress, TObjectPtr< UObject > Ptr) const override
virtual void SetObjectPtrPropertyValueUnchecked_InContainer (void *ContainerAddress, TObjectPtr< UObject > Ptr, int32 ArrayIndex=0) const override
Protected Member Functions inherited from FObjectPropertyBase
UObject * ConstructDefaultObjectValueIfNecessary (UObject *ExistingValue, FString *OutFailureReason=nullptr, const void *Defaults=nullptr) const
Constructs a new object if the existing one is missing or is not compatible with the property class Used for making sure non-nullable properties have valid values.
virtual void ExportText_Internal (FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const override
template<typename T, typename OutType>
PRAGMA_DISABLE_BUFFER_OVERRUN_WARNING void GetWrappedUObjectPtrValues (OutType *OutObjects, const void *SrcAddress, EPropertyMemoryAccess SrcAccess, int32 ArrayIndex, int32 ArrayCount) const
virtual const TCHAR * ImportText_Internal (const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const override
template<typename T, typename ValueType>
PRAGMA_ENABLE_BUFFER_OVERRUN_WARNING void SetWrappedUObjectPtrValues (void *DestAddress, EPropertyMemoryAccess DestAccess, ValueType *InValues, int32 ArrayIndex, int32 ArrayCount) const
Protected Member Functions inherited from FProperty
virtual bool ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > &EncounteredStructProps) const
virtual void FinishDestroyInternal (void *Data) const
void Init ()
Initializes internal state.
FORCEINLINE void * PointerToValuePtr (void const *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, int32 ArrayIndex=0) const
void SetOffset_Internal (int32 NewOffset)
Set the alignment offset for this property - added for FMapProperty.
Protected Member Functions inherited from FField
void SetFlagsTo (EObjectFlags NewFlags)
Set the object flags directly.
Private Member Functions
FLazyObjectProperty (FFieldVariant InOwner, const UECodeGen_Private::FLazyObjectPropertyParams &Prop)
Constructor used for constructing compiled in properties.
virtual void CopyCompleteValueFromScriptVM (void *Dest, void const *Src) const override
Copy the value for all elements of this property.
virtual void CopyCompleteValueFromScriptVM_InContainer (void *OutContainer, void const *InValue) const override
virtual void CopyCompleteValueToScriptVM (void *Dest, void const *Src) const override
Copy the value for all elements of this property.
virtual void CopyCompleteValueToScriptVM_InContainer (void *OutValue, void const *InContainer) const override
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
virtual void CopySingleValueFromScriptVM (void *Dest, void const *Src) const override
Copy the value for a single element of this property.
virtual void CopySingleValueToScriptVM (void *Dest, void const *Src) const override
Copy the value for a single element of this property.
DECLARE_FIELD_API (FLazyObjectProperty, TFObjectPropertyBase< FLazyObjectPtr >, CASTCLASS_FLazyObjectProperty, 1) 1 FLazyObjectProperty(FFieldVariant InOwner
virtual FString GetCPPMacroType (FString &ExtendedTypeText) const override
virtual FString GetCPPType (FString *ExtendedTypeText, uint32 CPPExportFlags) const override
virtual FString GetCPPTypeCustom (FString *ExtendedTypeText, uint32 CPPExportFlags, const FString &InnerNativeTypeName) const override
virtual FName GetID () const override
virtual UObject * GetObjectPropertyValue (const void *PropertyValueAddress) const override
virtual UObject * GetObjectPropertyValue_InContainer (const void *ContainerAddress, int32 ArrayIndex=0) const override
virtual TObjectPtr< UObject > GetObjectPtrPropertyValue (const void *PropertyValueAddress) const override
virtual TObjectPtr< UObject > GetObjectPtrPropertyValue_InContainer (const void *ContainerAddress, int32 ArrayIndex=0) const override
virtual uint32 GetValueTypeHashInternal (const void *Src) const override
virtual bool Identical (const void *A, const void *B, uint32 PortFlags) const override
virtual void SerializeItem (FStructuredArchive::FSlot Slot, void *Value, void const *Defaults) const override
Private Attributes
const FName & InName
const FName EObjectFlags InObjectFlags
Additional Inherited Members
Public Types inherited from TFObjectPropertyBase< FLazyObjectPtr >
typedef TProperty< FLazyObjectPtr, FObjectPropertyBase > Super
typedef FLazyObjectPtr TCppType
typedef Super::TTypeFundamentals TTypeFundamentals
Public Types inherited from TProperty< FLazyObjectPtr, FObjectPropertyBase >
typedef FObjectPropertyBase Super
typedef FLazyObjectPtr TCppType
typedef TPropertyTypeFundamentals< FLazyObjectPtr > TTypeFundamentals
Public Types inherited from FField
typedef FField BaseFieldClass
typedef FFieldClass FieldTypeClass
using FLinkedListBuilder = TLinkedListBuilder<FField>
typedef FField Super
typedef FField ThisClass
Public Types inherited from TPropertyTypeFundamentals< FLazyObjectPtr >
enum
typedef FLazyObjectPtr TCppType
Type of the CPP property.
Static Public Member Functions inherited from FObjectPropertyBase
static TObjectPtr< UObject > FindImportedObject (const FProperty *Property, UObject *OwnerObject, UClass *ObjectClass, UClass *RequiredMetaClass, const TCHAR *Text, uint32 PortFlags=0, FUObjectSerializeContext *InSerializeContext=nullptr, bool bAllowAnyPackage=true)
static FString GetExportPath (const TObjectPtr< const UObject > &Object, const UObject *Parent=nullptr, const UObject *ExportRootScope=nullptr, const uint32 PortFlags=PPF_None)
Returns the qualified export path for a given object, parent, and export root scope.
static FString GetExportPath (FTopLevelAssetPath ClassPathName, const FString &ObjectPathName)
Returns the qualified export path given a class path name and object path name.
static bool ParseObjectPropertyValue (const FProperty *Property, UObject *OwnerObject, UClass *RequiredMetaClass, uint32 PortFlags, const TCHAR *&Buffer, TObjectPtr< UObject > &out_ResolvedValue, FUObjectSerializeContext *InSerializeContext=nullptr, bool bAllowAnyPackage=true)
Parses a text buffer into an object reference.
static bool StaticIdentical (UObject *A, UObject *B, uint32 PortFlags)
Static Public Member Functions inherited from FProperty
static FName FindRedirectedPropertyName (const UStruct *ObjectStruct, FName OldName)
Gets a redirected property name, will return NAME_None if no redirection was found.
static const TCHAR * ImportSingleProperty (const TCHAR *Str, void *DestData, const UStruct *ObjectStruct, UObject *SubobjectOuter, int32 PortFlags, FOutputDevice *Warn, TArray< struct FDefinedProperty > &DefinedProperties)
parses and imports a text definition of a single property's value (if array, may be an individual element) also includes parsing of special operations for array properties (Add/Remove/RemoveIndex/Empty)
Static Public Member Functions inherited from FField
static FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given its class.
static FField * Construct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given the name of its class.
static FField * Duplicate (const FField *InField, FFieldVariant DestOwner, const FName DestName=NAME_None, EObjectFlags FlagMask=RF_AllFlags, EInternalObjectFlags InternalFlagsMask=EInternalObjectFlags_AllFlags)
Duplicates an FField.
static FName GenerateFFieldName (FFieldVariant InOwner, FFieldClass *InClass)
Generates a name for a Field of a given type.
static FFieldClass * StaticClass ()
static constexpr uint64 StaticClassCastFlags ()
static constexpr uint64 StaticClassCastFlagsPrivate ()
static FField * TryConstruct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Tries to construct a new field given the name of its class.
Static Public Member Functions inherited from TPropertyTypeFundamentals< FLazyObjectPtr >
static FORCEINLINE void ClearIntrusiveOptionalValue (void *A)
static FORCEINLINE void DestroyPropertyValue (void *A)
Destroy the value of a property at an address.
static FORCEINLINE TCppType GetDefaultPropertyValue ()
Get the default value of the cpp type, just the default constructor, which works even for things like in32.
static FORCEINLINE TCppType GetOptionalPropertyValue (void const *B)
Get the value of the property from an address, unless it is NULL, then return the default value.
static FORCEINLINE TCppType const & GetPropertyValue (void const *A)
Get the value of the property from an address.
static FORCEINLINE TCppType const * GetPropertyValuePtr (void const *A)
Convert the address of a value of the property to the proper type.
static FORCEINLINE TCHAR const * GetTypeName ()
static FORCEINLINE bool HasIntrusiveUnsetOptionalState ()
static FORCEINLINE void InitializeIntrusiveUnsetOptionalValue (void *Data)
static FORCEINLINE TCppType * InitializePropertyValue (void *A)
Initialize the value of a property at an address, this assumes over uninitialized memory.
static FORCEINLINE bool IsIntrusiveOptionalValueSet (const void *A)
static FORCEINLINE void SetPropertyValue (void *A, TCppType const &Value)
Set the value of a property at an address.
Data Fields inherited from FObjectPropertyBase
virtual FString GetCPPTypeCustom (FString *ExtendedTypeText, uint32 CPPExportFlags, const FString &InnerNativeTypeName) const PURE_VIRTUAL(FObjectPropertyBase
Data Fields inherited from FProperty
const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc const
FProperty * DestructorLinkNext
In memory only: Linked list of properties requiring destruction.
virtual FString GetCPPType (FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const PURE_VIRTUAL(FProperty
Returns the text to use for exporting this property to header file.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags=0) const PURE_VIRTUAL(FProperty
Determines whether the property values are identical.
virtual void virtual SerializeItem(FStructuredArchive::FSlot Slot, void *Value, void const *Defaults=NULL) const PURE_VIRTUAL(FProperty boo NetSerializeItem)(FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const
FProperty * NextRef
In memory only: Linked list of object reference properties from most-derived to base.
FProperty * PostConstructLinkNext
In memory only: Linked list of properties requiring post constructor initialization.
EPropertyFlags PropertyFlags
FProperty * PropertyLinkNext
In memory only: Linked list of properties from most-derived to base.
uint16 RepIndex
FName RepNotifyFunc
Data Fields inherited from FField
EObjectFlags FlagsPrivate
Object flags.
FName NamePrivate
Name of this field.
FField * Next
Next Field in the linked list.
FFieldVariant Owner
Owner of this field.
Static Protected Member Functions inherited from TPropertyTypeFundamentals< FLazyObjectPtr >
static FORCEINLINE EPropertyFlags GetComputedFlagsPropertyFlags ()
Get the property flags corresponding to this C++ type, from the C++ type traits system.
Protected Attributes inherited from FProperty
virtual void virtual ExportText_Internal(FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const PURE_VIRTUAL(FProperty const TCHAR ImportText_Internal)(const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const PURE_VIRTUAL(FProperty
Detailed Description
Definition at line 3031 of file UnrealType.h.
Constructor & Destructor Documentation
FLazyObjectProperty()
FLazyObjectProperty::FLazyObjectProperty (FFieldVariant InOwner, const UECodeGen_Private::FLazyObjectPropertyParams & Prop) private
Constructor used for constructing compiled in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
References FLazyObjectProperty(), FProperty::const, and UE_API.
Referenced by FLazyObjectProperty(), and DECLARE_FIELD_API().
Member Function Documentation
AllowCrossLevel()
virtual bool FLazyObjectProperty::AllowCrossLevel () const override virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
CopyCompleteValueFromScriptVM()
virtual void FLazyObjectProperty::CopyCompleteValueFromScriptVM (void * Dest, void const * Src) const override private virtual
Copy the value for all elements of this property.
From the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented from FProperty.
References UE_API.
CopyCompleteValueFromScriptVM_InContainer()
virtual void FLazyObjectProperty::CopyCompleteValueFromScriptVM_InContainer (void * OutContainer, void const * InValue) const override private virtual
Reimplemented from FProperty.
References UE_API.
CopyCompleteValueToScriptVM()
virtual void FLazyObjectProperty::CopyCompleteValueToScriptVM (void * Dest, void const * Src) const override private virtual
Copy the value for all elements of this property.
To the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented from FProperty.
References UE_API.
CopyCompleteValueToScriptVM_InContainer()
virtual void FLazyObjectProperty::CopyCompleteValueToScriptVM_InContainer (void * OutValue, void const * InContainer) const override private virtual
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
Reimplemented from FProperty.
References InContainer, and UE_API.
CopySingleValueFromScriptVM()
virtual void FLazyObjectProperty::CopySingleValueFromScriptVM (void * Dest, void const * Src) const override private virtual
Copy the value for a single element of this property.
From the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET + INDEX * SIZE, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty INDEX = the index that you want to copy. for properties which are not arrays, this should always be 0 SIZE = the ElementSize of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented from FProperty.
References UE_API.
CopySingleValueToScriptVM()
virtual void FLazyObjectProperty::CopySingleValueToScriptVM (void * Dest, void const * Src) const override private virtual
Copy the value for a single element of this property.
To the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET + INDEX * SIZE, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty INDEX = the index that you want to copy. for properties which are not arrays, this should always be 0 SIZE = the ElementSize of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented from FProperty.
References UE_API.
DECLARE_FIELD_API()
FLazyObjectProperty::DECLARE_FIELD_API (FLazyObjectProperty , TFObjectPropertyBase< FLazyObjectPtr > , CASTCLASS_FLazyObjectProperty , 1) private
References FLazyObjectProperty(), TFObjectPropertyBase< FLazyObjectPtr >::TFObjectPropertyBase(), CASTCLASS_FLazyObjectProperty, and UE_API.
GetCPPMacroType()
virtual FString FLazyObjectProperty::GetCPPMacroType (FString & ExtendedTypeText) const override private virtual
Reimplemented from FProperty.
References UE_API.
GetCPPType()
virtual FString FLazyObjectProperty::GetCPPType (FString * ExtendedTypeText, uint32 CPPExportFlags) const override private virtual
Reimplemented from TFObjectPropertyBase< FLazyObjectPtr >.
References UE_API.
GetCPPTypeCustom()
virtual FString FLazyObjectProperty::GetCPPTypeCustom (FString * ExtendedTypeText, uint32 CPPExportFlags, const FString & InnerNativeTypeName) const override private virtual
References UE_API.
GetID()
virtual FName FLazyObjectProperty::GetID () const override private virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
GetObjectPropertyValue()
virtual UObject * FLazyObjectProperty::GetObjectPropertyValue (const void * PropertyValueAddress) const override private virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
GetObjectPropertyValue_InContainer()
virtual UObject * FLazyObjectProperty::GetObjectPropertyValue_InContainer (const void * ContainerAddress, int32 ArrayIndex = 0) const override private virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
GetObjectPtrPropertyValue()
virtual TObjectPtr< UObject > FLazyObjectProperty::GetObjectPtrPropertyValue (const void * PropertyValueAddress) const override private virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
GetObjectPtrPropertyValue_InContainer()
virtual TObjectPtr< UObject > FLazyObjectProperty::GetObjectPtrPropertyValue_InContainer (const void * ContainerAddress, int32 ArrayIndex = 0) const override private virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
GetValueTypeHashInternal()
virtual uint32 FLazyObjectProperty::GetValueTypeHashInternal (const void * Src) const override private virtual
Reimplemented from FProperty.
References UE_API.
Identical()
virtual bool FLazyObjectProperty::Identical (const void * A, const void * B, uint32 PortFlags) const override private virtual
Reimplemented from FObjectPropertyBase.
References A, B, and UE_API.
SerializeItem()
virtual void FLazyObjectProperty::SerializeItem (FStructuredArchive::FSlot Slot, void * Value, void const * Defaults) const override private virtual
References UE_API, and Value.
SetObjectPropertyValueUnchecked()
virtual void FLazyObjectProperty::SetObjectPropertyValueUnchecked (void * PropertyValueAddress, UObject * Value) const override protected virtual
Reimplemented from FObjectPropertyBase.
References UE_API, and Value.
SetObjectPropertyValueUnchecked_InContainer()
virtual void FLazyObjectProperty::SetObjectPropertyValueUnchecked_InContainer (void * ContainerAddress, UObject * Value, int32 ArrayIndex = 0) const override protected virtual
Reimplemented from FObjectPropertyBase.
References UE_API, and Value.
SetObjectPtrPropertyValueUnchecked()
virtual void FLazyObjectProperty::SetObjectPtrPropertyValueUnchecked (void * PropertyValueAddress, TObjectPtr< UObject > Ptr) const override protected virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
SetObjectPtrPropertyValueUnchecked_InContainer()
virtual void FLazyObjectProperty::SetObjectPtrPropertyValueUnchecked_InContainer (void * ContainerAddress, TObjectPtr< UObject > Ptr, int32 ArrayIndex = 0) const override protected virtual
Reimplemented from FObjectPropertyBase.
References UE_API.
Field Documentation
InName
const FName& FLazyObjectProperty::InName private
Definition at line 3035 of file UnrealType.h.
InObjectFlags
const FName EObjectFlags FLazyObjectProperty::InObjectFlags private
Definition at line 3035 of file UnrealType.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h