Unreal Engine 5.6 C++ API: TNonNullSubclassOf< T > Class Template Reference
TNonNullSubclassOf< T > Class Template Reference
Template to allow TClassType's to be passed around with type safety.
#include "NonNullSubclassOf.h"
Public Types
using IntrusiveUnsetOptionalStateType = TNonNullSubclassOf
Public Types inherited from TSubclassOf< T >
using ElementType = T
Public Member Functions
template<typename U UE_REQUIRES>
FORCEINLINE TNonNullSubclassOf (const TSubclassOf< U > &From)
Copy Constructor, will only compile if types are compatible.
FORCEINLINE TNonNullSubclassOf (EDefaultConstructNonNullSubclassOf)
Default Constructor, defaults to null.
FORCEINLINE TNonNullSubclassOf (FIntrusiveUnsetOptionalState)
template<typename PtrType UE_REQUIRES>
FORCEINLINE TNonNullSubclassOf (PtrType *From)
Constructor that takes a UClass* or FFieldClass* if T is a UObject or a FField type respectively.
template<typename U UE_REQUIRES>
FORCEINLINE TNonNullSubclassOf & operator= (const TSubclassOf< U > &From)
Assignment operator, will only compile if types are compatible.
template<typename PtrType>
FORCEINLINE TNonNullSubclassOf & operator= (PtrType *From)
Assignment operator from UClass, the type is checked on get not on set.
FORCEINLINE bool operator== (FIntrusiveUnsetOptionalState) const
Public Member Functions inherited from TSubclassOf< T >
TSubclassOf ()=default
TSubclassOf (const TSubclassOf &)=default
template<typename OtherT UE_REQUIRES>
FORCEINLINE TSubclassOf (const TSubclassOf< OtherT > &Other)
Construct from another TSubclassOf, only if types are compatible.
TSubclassOf (TSubclassOf &&)=default
template<typename U UE_REQUIRES>
FORCEINLINE TSubclassOf (U &&From)
Construct from a UClass* (or something implicitly convertible to it)
FORCEINLINE TSubclassOf (UClass *From)
Constructor that takes a UClass*.
~TSubclassOf ()=default
FORCEINLINE UClass * Get () const
Dereference back into a UClass*, does runtime type checking.
FORCEINLINE T * GetDefaultObject () const
Get the CDO if we are referencing a valid class.
TObjectPtr< UClass > & GetGCPtr ()
FORCEINLINE operator UClass * () const
Implicit conversion to UClass*, does runtime type checking.
FORCEINLINE UClass * operator* () const
Dereference back into a UClass*, does runtime type checking.
FORCEINLINE UClass * operator-> () const
Dereference back into a UClass*, does runtime type checking.
TSubclassOf & operator= (const TSubclassOf &)=default
template<typename OtherT UE_REQUIRES>
FORCEINLINE TSubclassOf & operator= (const TSubclassOf< OtherT > &Other)
Assign from another TSubclassOf, only if types are compatible.
TSubclassOf & operator= (TSubclassOf &&)=default
template<typename U UE_REQUIRES>
FORCEINLINE TSubclassOf & operator= (U &&From)
Assign from a UClass* (or something implicitly convertible to it).
FORCEINLINE TSubclassOf & operator= (UClass *From)
Assign from a UClass*.
FORCEINLINE void Serialize (FArchive &Ar)
FORCEINLINE void Serialize (FStructuredArchiveSlot &Slot)
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
using Super = TSubclassOf<T>
Detailed Description
template<typename T>
class TNonNullSubclassOf< T >
Template to allow TClassType's to be passed around with type safety.
Definition at line 18 of file NonNullSubclassOf.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
template<typename T> using TNonNullSubclassOf< T >::IntrusiveUnsetOptionalStateType = TNonNullSubclassOf
Definition at line 75 of file NonNullSubclassOf.h.
Super
template<typename T> using TNonNullSubclassOf< T >::Super = TSubclassOf<T> private
Definition at line 20 of file NonNullSubclassOf.h.
Constructor & Destructor Documentation
TNonNullSubclassOf() [1/4]
template<typename T> FORCEINLINE TNonNullSubclassOf< T >::TNonNullSubclassOf (EDefaultConstructNonNullSubclassOf) inline nodiscard
Default Constructor, defaults to null.
Definition at line 24 of file NonNullSubclassOf.h.
References FORCEINLINE.
Referenced by operator=(), and operator=().
TNonNullSubclassOf() [2/4]
template<typename T> template<typename PtrType UE_REQUIRES> FORCEINLINE TNonNullSubclassOf< T >::TNonNullSubclassOf (PtrType * From) inline nodiscard
Constructor that takes a UClass* or FFieldClass* if T is a UObject or a FField type respectively.
Definition at line 33 of file NonNullSubclassOf.h.
References checkf, FORCEINLINE, and TEXT.
TNonNullSubclassOf() [3/4]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TNonNullSubclassOf< T >::TNonNullSubclassOf (const TSubclassOf< U > & From) inline nodiscard
Copy Constructor, will only compile if types are compatible.
Definition at line 44 of file NonNullSubclassOf.h.
References TSubclassOf< T >::TSubclassOf, and FORCEINLINE.
TNonNullSubclassOf() [4/4]
template<typename T> FORCEINLINE TNonNullSubclassOf< T >::TNonNullSubclassOf (FIntrusiveUnsetOptionalState) inline explicit nodiscard
Definition at line 76 of file NonNullSubclassOf.h.
References FORCEINLINE.
Member Function Documentation
operator=() [1/2]
template<typename T> template<typename U UE_REQUIRES> FORCEINLINE TNonNullSubclassOf & TNonNullSubclassOf< T >::operator= (const TSubclassOf< U > & From) inline
Assignment operator, will only compile if types are compatible.
Definition at line 55 of file NonNullSubclassOf.h.
References TNonNullSubclassOf(), TSubclassOf< T >::TSubclassOf, checkf, FORCEINLINE, TSubclassOf< T >::operator=(), and TEXT.
operator=() [2/2]
template<typename T> template<typename PtrType> FORCEINLINE TNonNullSubclassOf & TNonNullSubclassOf< T >::operator= (PtrType * From) inline
Assignment operator from UClass, the type is checked on get not on set.
Definition at line 64 of file NonNullSubclassOf.h.
References TNonNullSubclassOf(), checkf, FORCEINLINE, TSubclassOf< T >::operator=(), and TEXT.
operator==()
template<typename T> FORCEINLINE bool TNonNullSubclassOf< T >::operator== (FIntrusiveUnsetOptionalState) const inline nodiscard
Definition at line 81 of file NonNullSubclassOf.h.
References FORCEINLINE, and TSubclassOf< T >::Get().
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename T> bool TNonNullSubclassOf< T >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 74 of file NonNullSubclassOf.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Templates/NonNullSubclassOf.h