Unreal Engine 5.6 C++ API: FSkeletalMeshVertexClothBuffer Class Reference
FSkeletalMeshVertexClothBuffer Class Reference
A vertex buffer for holding skeletal mesh clothing information only.
#include "SkeletalMeshVertexClothBuffer.h"
Public Member Functions
FSkeletalMeshVertexClothBuffer ()
Constructor.
FSkeletalMeshVertexClothBuffer (const FSkeletalMeshVertexClothBuffer &Other)
Constructor (copy)
virtual ~FSkeletalMeshVertexClothBuffer ()
Destructor.
void CleanUp ()
Delete existing resources.
void ClearMetaData ()
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI vertex buffer with CPU data.
const TArray< FClothBufferIndexMapping > & GetClothIndexMapping () const
virtual FString GetFriendlyName () const override
FORCEINLINE uint32 GetNumVertices () const
FShaderResourceViewRHIRef GetSRV () const
FORCEINLINE uint32 GetStride () const
FORCEINLINE uint32 GetVertexDataSize () const
void Init (const TArray< FMeshToMeshVertData > &InMappingData, const TArray< FClothBufferIndexMapping > &InClothIndexMapping)
Initializes the buffer with the given vertices.
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initialize the RHI resource for this vertex buffer.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
FORCEINLINE FMeshToMeshVertData & MappingData (uint32 VertexIndex)
FORCEINLINE const FMeshToMeshVertData & MappingData (uint32 VertexIndex) const
FSkeletalMeshVertexClothBuffer & operator= (const FSkeletalMeshVertexClothBuffer &Other)
Assignment.
virtual void ReleaseRHI () override
Release the RHI resource for this vertex buffer.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void SerializeMetaData (FArchive &Ar)
void SetMetadata (const TArray< FClothBufferIndexMapping > &ClothIndexMapping, uint32 Stride, uint32 NumVertices)
Public Member Functions inherited from FVertexBuffer
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Member Functions
void AllocateData ()
Allocates the vertex data storage type.
Private Attributes
TArray< FClothBufferIndexMapping > ClothIndexMapping
The Cloth deformer mapping to the simulation LODs.
uint8 * Data
The cached vertex data pointer.
uint32 NumVertices
The cached number of vertices.
uint32 Stride
The cached vertex stride.
FShaderResourceViewRHIRef VertexBufferSRV
FSkeletalMeshVertexDataInterface * VertexData
The vertex data storage type.
Friends
FArchive & operator<< (FArchive &Ar, FSkeletalMeshVertexClothBuffer &VertexBuffer)
Serializer for this class.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FVertexBuffer
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A vertex buffer for holding skeletal mesh clothing information only.
This buffer sits along side the other skeletal mesh buffers per LOD
Definition at line 14 of file SkeletalMeshVertexClothBuffer.h.
Constructor & Destructor Documentation
FSkeletalMeshVertexClothBuffer() [1/2]
FSkeletalMeshVertexClothBuffer::FSkeletalMeshVertexClothBuffer ()
Constructor.
Referenced by FSkeletalMeshVertexClothBuffer(), operator<<, and operator=().
~FSkeletalMeshVertexClothBuffer()
virtual FSkeletalMeshVertexClothBuffer::~FSkeletalMeshVertexClothBuffer () virtual
Destructor.
FSkeletalMeshVertexClothBuffer() [2/2]
FSkeletalMeshVertexClothBuffer::FSkeletalMeshVertexClothBuffer (const FSkeletalMeshVertexClothBuffer & Other)
Constructor (copy)
References FSkeletalMeshVertexClothBuffer(), and Other.
Member Function Documentation
AllocateData()
void FSkeletalMeshVertexClothBuffer::AllocateData () private
Allocates the vertex data storage type.
CleanUp()
void FSkeletalMeshVertexClothBuffer::CleanUp ()
Delete existing resources.
ClearMetaData()
void FSkeletalMeshVertexClothBuffer::ClearMetaData ()
CreateRHIBuffer()
FBufferRHIRef FSkeletalMeshVertexClothBuffer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Create an RHI vertex buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
GetClothIndexMapping()
const TArray< FClothBufferIndexMapping > & FSkeletalMeshVertexClothBuffer::GetClothIndexMapping () const inline
Definition at line 121 of file SkeletalMeshVertexClothBuffer.h.
References ClothIndexMapping.
GetFriendlyName()
virtual FString FSkeletalMeshVertexClothBuffer::GetFriendlyName () const override virtual
Returns
text description for the resource type
Reimplemented from FVertexBuffer.
GetNumVertices()
FORCEINLINE uint32 FSkeletalMeshVertexClothBuffer::GetNumVertices () const inline
Returns
number of vertices in this vertex buffer
Definition at line 96 of file SkeletalMeshVertexClothBuffer.h.
References FORCEINLINE, and NumVertices.
Referenced by MappingData(), and MappingData().
GetSRV()
FShaderResourceViewRHIRef FSkeletalMeshVertexClothBuffer::GetSRV () const inline
Definition at line 116 of file SkeletalMeshVertexClothBuffer.h.
References VertexBufferSRV.
GetStride()
FORCEINLINE uint32 FSkeletalMeshVertexClothBuffer::GetStride () const inline
Returns
cached stride for vertex data type for this vertex buffer
Definition at line 104 of file SkeletalMeshVertexClothBuffer.h.
References FORCEINLINE, and Stride.
GetVertexDataSize()
FORCEINLINE uint32 FSkeletalMeshVertexClothBuffer::GetVertexDataSize () const inline
Returns
total size of data in resource array
Definition at line 111 of file SkeletalMeshVertexClothBuffer.h.
References FORCEINLINE, NumVertices, and Stride.
Init()
void FSkeletalMeshVertexClothBuffer::Init (const TArray< FMeshToMeshVertData > & InMappingData, const TArray< FClothBufferIndexMapping > & InClothIndexMapping)
Initializes the buffer with the given vertices.
Parameters
InVertices - The vertices to initialize the buffer with.
InClothIndexMapping - The cloth deformer mapping data offset for a specific section/LODBias.
InitRHI()
virtual void FSkeletalMeshVertexClothBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initialize the RHI resource for this vertex buffer.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FSkeletalMeshVertexClothBuffer::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
References IntermediateBuffer.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
MappingData() [1/2]
FORCEINLINE FMeshToMeshVertData & FSkeletalMeshVertexClothBuffer::MappingData (uint32 VertexIndex) inline
Definition at line 82 of file SkeletalMeshVertexClothBuffer.h.
References checkSlow, Data, FORCEINLINE, GetNumVertices(), and Stride.
MappingData() [2/2]
FORCEINLINE const FMeshToMeshVertData & FSkeletalMeshVertexClothBuffer::MappingData (uint32 VertexIndex) const inline
Definition at line 87 of file SkeletalMeshVertexClothBuffer.h.
References checkSlow, Data, FORCEINLINE, GetNumVertices(), and Stride.
operator=()
FSkeletalMeshVertexClothBuffer & FSkeletalMeshVertexClothBuffer::operator= (const FSkeletalMeshVertexClothBuffer & Other)
Assignment.
Assumes that vertex buffer will be rebuilt
References FSkeletalMeshVertexClothBuffer(), and Other.
ReleaseRHI()
virtual void FSkeletalMeshVertexClothBuffer::ReleaseRHI () override virtual
Release the RHI resource for this vertex buffer.
Reimplemented from FVertexBuffer.
ReleaseRHIForStreaming()
void FSkeletalMeshVertexClothBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
SerializeMetaData()
void FSkeletalMeshVertexClothBuffer::SerializeMetaData (FArchive & Ar)
References Ar.
SetMetadata()
void FSkeletalMeshVertexClothBuffer::SetMetadata (const TArray< FClothBufferIndexMapping > & ClothIndexMapping, uint32 Stride, uint32 NumVertices)
References ClothIndexMapping, NumVertices, and Stride.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FSkeletalMeshVertexClothBuffer & VertexBuffer) friend
Serializer for this class.
Parameters
Ar - archive to serialize to
B - data to serialize
References FSkeletalMeshVertexClothBuffer(), Ar, and VertexBuffer.
Field Documentation
ClothIndexMapping
TArray<FClothBufferIndexMapping> FSkeletalMeshVertexClothBuffer::ClothIndexMapping private
The Cloth deformer mapping to the simulation LODs.
Definition at line 139 of file SkeletalMeshVertexClothBuffer.h.
Referenced by GetClothIndexMapping(), and SetMetadata().
Data
uint8* FSkeletalMeshVertexClothBuffer::Data private
The cached vertex data pointer.
Definition at line 144 of file SkeletalMeshVertexClothBuffer.h.
Referenced by MappingData(), and MappingData().
NumVertices
uint32 FSkeletalMeshVertexClothBuffer::NumVertices private
The cached number of vertices.
Definition at line 148 of file SkeletalMeshVertexClothBuffer.h.
Referenced by GetNumVertices(), GetVertexDataSize(), and SetMetadata().
Stride
uint32 FSkeletalMeshVertexClothBuffer::Stride private
The cached vertex stride.
Definition at line 146 of file SkeletalMeshVertexClothBuffer.h.
Referenced by GetStride(), GetVertexDataSize(), MappingData(), MappingData(), and SetMetadata().
VertexBufferSRV
FShaderResourceViewRHIRef FSkeletalMeshVertexClothBuffer::VertexBufferSRV private
Definition at line 136 of file SkeletalMeshVertexClothBuffer.h.
Referenced by GetSRV().
VertexData
FSkeletalMeshVertexDataInterface* FSkeletalMeshVertexClothBuffer::VertexData private
The vertex data storage type.
Definition at line 142 of file SkeletalMeshVertexClothBuffer.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/SkeletalMeshVertexClothBuffer.h