Unreal Engine 5.6 C++ API: FUObjectAnnotationDense< TAnnotation, bAutoRemove > Class Template Reference
FUObjectAnnotationDense< TAnnotation, bAutoRemove > Class Template Reference
FUObjectAnnotationDense is a helper class that is used to store dense, fast, temporary, editor only, external or other tangential information about UObjects.
#include "UObjectAnnotation.h"
Public Member Functions
virtual ~FUObjectAnnotationDense ()
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
void AddAnnotation (const UObjectBase *Object, const TAnnotation &Annotation)
Add an annotation to the annotation list.
void AddAnnotation (const UObjectBase *Object, TAnnotation &&Annotation)
void AddAnnotation (int32 Index, const TAnnotation &Annotation)
Add an annotation to the annotation list.
void AddAnnotation (int32 Index, TAnnotation &&Annotation)
virtual SIZE_T GetAllocatedSize () const override
Returns the memory allocated by the internal array.
FORCEINLINE TAnnotation GetAnnotation (const UObjectBase *Object)
Return the annotation associated with a uobject.
FORCEINLINE TAnnotation GetAnnotation (int32 Index)
Return the annotation associated with a uobject.
FORCEINLINE TAnnotation & GetAnnotationRef (const UObjectBase *Object)
Return the annotation associated with a uobject.
FORCEINLINE TAnnotation & GetAnnotationRef (int32 Index)
Return the annotation associated with a uobject.
virtual void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index)
Interface for FUObjectAllocator::FUObjectDeleteListener.
virtual void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list.
void RemoveAnnotation (int32 Index)
Removes an annotation from the annotation list.
Public Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Private Member Functions
template<typename T>
void AddAnnotationInternal (int32 Index, T &&Annotation)
void RemoveAnnotationInternal (int32 Index)
Private Attributes
TArray< TAnnotation > AnnotationArray
Map from live objects to an annotation.
FRWLock AnnotationArrayCritical
Detailed Description
template<typename TAnnotation, bool bAutoRemove>
class FUObjectAnnotationDense< TAnnotation, bAutoRemove >
FUObjectAnnotationDense is a helper class that is used to store dense, fast, temporary, editor only, external or other tangential information about UObjects.
There is a notion of a default annotation and UObjects default to this annotation.
Annotations are automatically returned to the default when UObjects are destroyed. Annotation are not "garbage collection aware", so it isn't safe to store pointers to other UObjects in an annotation unless external guarantees are made such that destruction of the other object removes the annotation.
Parameters
TAnnotation type of the annotation
bAutoRemove if true, annotation will automatically be removed, otherwise in non-final builds it will verify that the annotation was removed by other means prior to destruction.
Definition at line 1097 of file UObjectAnnotation.h.
Constructor & Destructor Documentation
~FUObjectAnnotationDense()
template<typename TAnnotation, bool bAutoRemove> virtual FUObjectAnnotationDense< TAnnotation, bAutoRemove >::~FUObjectAnnotationDense () inline virtual
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
Definition at line 1131 of file UObjectAnnotation.h.
References RemoveAllAnnotations().
Member Function Documentation
AddAnnotation() [1/4]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotation (const UObjectBase * Object, const TAnnotation & Annotation) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Object Object to annotate.
Annotation Annotation to associate with Object.
Definition at line 1142 of file UObjectAnnotation.h.
References AddAnnotation(), check, GUObjectArray, and Object.
Referenced by AddAnnotation(), and AddAnnotation().
AddAnnotation() [2/4]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotation (const UObjectBase * Object, TAnnotation && Annotation) inline
Definition at line 1148 of file UObjectAnnotation.h.
References AddAnnotation(), check, GUObjectArray, MoveTemp(), and Object.
AddAnnotation() [3/4]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotation (int32 Index, const TAnnotation & Annotation) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Index Index of object to annotate.
Annotation Annotation to associate with Object.
Definition at line 1160 of file UObjectAnnotation.h.
References AddAnnotationInternal(), AnnotationArrayCritical, and SLT_Write.
AddAnnotation() [4/4]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotation (int32 Index, TAnnotation && Annotation) inline
Definition at line 1166 of file UObjectAnnotation.h.
References AddAnnotationInternal(), AnnotationArrayCritical, MoveTemp(), and SLT_Write.
AddAnnotationInternal()
template<typename TAnnotation, bool bAutoRemove> template<typename T> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AddAnnotationInternal (int32 Index, T && Annotation) inline private
Definition at line 1175 of file UObjectAnnotation.h.
References AnnotationArray, check, Forward(), GUObjectArray, and RemoveAnnotationInternal().
Referenced by AddAnnotation(), AddAnnotation(), and GetAnnotationRef().
GetAllocatedSize()
template<typename TAnnotation, bool bAutoRemove> virtual SIZE_T FUObjectAnnotationDense< TAnnotation, bAutoRemove >::GetAllocatedSize () const inline override virtual
Returns the memory allocated by the internal array.
Reimplemented from FUObjectArray::FUObjectDeleteListener.
Definition at line 1324 of file UObjectAnnotation.h.
References AnnotationArray.
GetAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove> FORCEINLINE TAnnotation FUObjectAnnotationDense< TAnnotation, bAutoRemove >::GetAnnotation (const UObjectBase * Object) inline
Return the annotation associated with a uobject.
Parameters
Object Object to return the annotation for
Definition at line 1266 of file UObjectAnnotation.h.
References check, checkf, ensureAlwaysMsgf, FORCEINLINE, GetAnnotation(), GUObjectArray, Object, and TEXT.
Referenced by GetAnnotation().
GetAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove> FORCEINLINE TAnnotation FUObjectAnnotationDense< TAnnotation, bAutoRemove >::GetAnnotation (int32 Index) inline
Return the annotation associated with a uobject.
Parameters
Index Index of the annotation to return
Definition at line 1283 of file UObjectAnnotation.h.
References AnnotationArray, AnnotationArrayCritical, check, FORCEINLINE, and SLT_ReadOnly.
GetAnnotationRef() [1/2]
template<typename TAnnotation, bool bAutoRemove> FORCEINLINE TAnnotation & FUObjectAnnotationDense< TAnnotation, bAutoRemove >::GetAnnotationRef (const UObjectBase * Object) inline
Return the annotation associated with a uobject.
Parameters
Object Object to return the annotation for
Returns
Reference to annotation.
Definition at line 1300 of file UObjectAnnotation.h.
References check, FORCEINLINE, GetAnnotationRef(), GUObjectArray, and Object.
Referenced by GetAnnotationRef().
GetAnnotationRef() [2/2]
template<typename TAnnotation, bool bAutoRemove> FORCEINLINE TAnnotation & FUObjectAnnotationDense< TAnnotation, bAutoRemove >::GetAnnotationRef (int32 Index) inline
Return the annotation associated with a uobject.
Adds one if the object has no annotation yet.
Parameters
Index Index of the annotation to return
Returns
Reference to the annotation.
Definition at line 1313 of file UObjectAnnotation.h.
References AddAnnotationInternal(), AnnotationArray, AnnotationArrayCritical, FORCEINLINE, and SLT_Write.
NotifyUObjectDeleted()
template<typename TAnnotation, bool bAutoRemove> virtual void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::NotifyUObjectDeleted (const UObjectBase * Object, int32 Index) inline virtual
Interface for FUObjectAllocator::FUObjectDeleteListener.
Parameters
Object object that has been destroyed
Index index of object that is being deleted
Definition at line 1107 of file UObjectAnnotation.h.
References AnnotationArray, check, Object, and RemoveAnnotation().
OnUObjectArrayShutdown()
template<typename TAnnotation, bool bAutoRemove> virtual void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::OnUObjectArrayShutdown () inline override virtual
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
Implements FUObjectArray::FUObjectDeleteListener.
Definition at line 1122 of file UObjectAnnotation.h.
References GUObjectArray, and RemoveAllAnnotations().
RemoveAllAnnotations()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::RemoveAllAnnotations () inline
Removes all annotation from the annotation list.
Definition at line 1244 of file UObjectAnnotation.h.
References AnnotationArray, AnnotationArrayCritical, GUObjectArray, and SLT_Write.
Referenced by ~FUObjectAnnotationDense(), and OnUObjectArrayShutdown().
RemoveAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::RemoveAnnotation (const UObjectBase * Object) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 1213 of file UObjectAnnotation.h.
References check, GUObjectArray, Object, and RemoveAnnotation().
Referenced by NotifyUObjectDeleted(), and RemoveAnnotation().
RemoveAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::RemoveAnnotation (int32 Index) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 1223 of file UObjectAnnotation.h.
References AnnotationArrayCritical, RemoveAnnotationInternal(), and SLT_Write.
RemoveAnnotationInternal()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationDense< TAnnotation, bAutoRemove >::RemoveAnnotationInternal (int32 Index) inline private
Definition at line 1230 of file UObjectAnnotation.h.
References AnnotationArray, and check.
Referenced by AddAnnotationInternal(), and RemoveAnnotation().
Field Documentation
AnnotationArray
template<typename TAnnotation, bool bAutoRemove> TArray<TAnnotation> FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AnnotationArray private
Map from live objects to an annotation.
Definition at line 1334 of file UObjectAnnotation.h.
Referenced by AddAnnotationInternal(), GetAllocatedSize(), GetAnnotation(), GetAnnotationRef(), NotifyUObjectDeleted(), RemoveAllAnnotations(), and RemoveAnnotationInternal().
AnnotationArrayCritical
template<typename TAnnotation, bool bAutoRemove> FRWLock FUObjectAnnotationDense< TAnnotation, bAutoRemove >::AnnotationArrayCritical private
Definition at line 1335 of file UObjectAnnotation.h.
Referenced by AddAnnotation(), AddAnnotation(), GetAnnotation(), GetAnnotationRef(), RemoveAllAnnotations(), and RemoveAnnotation().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectAnnotation.h