Unreal Engine 5.6 C++ API: AGameplayCueNotify_BurstLatent Class Reference
AGameplayCueNotify_BurstLatent Class Reference
#include "GameplayCueNotify_BurstLatent.h"
Protected Member Functions
virtual GAMEPLAYABILITIES_API EDataValidationResult IsDataValid (class FDataValidationContext &Context) const override
virtual GAMEPLAYABILITIES_API bool OnExecute_Implementation (AActor *Target, const FGameplayCueParameters &Parameters) override
virtual GAMEPLAYABILITIES_API bool Recycle () override
UFUNCTION () GAMEPLAYABILITIES_API void OnBurst(AActor *Target
UPROPERTY () FGameplayCueNotify_BurstEffects BurstEffects
UPROPERTY () FGameplayCueNotify_PlacementInfo DefaultPlacementInfo
UPROPERTY () FGameplayCueNotify_SpawnCondition DefaultSpawnCondition
UPROPERTY () FGameplayCueNotify_SpawnResult BurstSpawnResults
Protected Attributes
const FGameplayCueParameters & Parameters
const FGameplayCueParameters const FGameplayCueNotify_SpawnResult & SpawnResults
Detailed Description
Definition at line 20 of file GameplayCueNotify_BurstLatent.h.
Member Function Documentation
IsDataValid()
virtual GAMEPLAYABILITIES_API EDataValidationResult AGameplayCueNotify_BurstLatent::IsDataValid (class FDataValidationContext & Context) const override protected virtual
References UE_API.
OnExecute_Implementation()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_BurstLatent::OnExecute_Implementation (AActor * Target, const FGameplayCueParameters & Parameters) override protected virtual
References Parameters, Target, and UE_API.
Recycle()
virtual GAMEPLAYABILITIES_API bool AGameplayCueNotify_BurstLatent::Recycle () override protected virtual
References UE_API.
UFUNCTION()
AGameplayCueNotify_BurstLatent::UFUNCTION () protected
UPROPERTY() [1/4]
AGameplayCueNotify_BurstLatent::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [2/4]
AGameplayCueNotify_BurstLatent::UPROPERTY () protected
References Category, and UPROPERTY().
UPROPERTY() [3/4]
AGameplayCueNotify_BurstLatent::UPROPERTY () protected
References Category.
Referenced by UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/4]
AGameplayCueNotify_BurstLatent::UPROPERTY () protected
References Category, and UPROPERTY().
Field Documentation
Parameters
const FGameplayCueParameters& AGameplayCueNotify_BurstLatent::Parameters protected
Definition at line 35 of file GameplayCueNotify_BurstLatent.h.
Referenced by OnExecute_Implementation().
SpawnResults
const FGameplayCueParameters const FGameplayCueNotify_SpawnResult& AGameplayCueNotify_BurstLatent::SpawnResults protected
Definition at line 35 of file GameplayCueNotify_BurstLatent.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/GameplayCueNotify_BurstLatent.h