Unreal Engine 5.6 C++ API: FRefCountedObject Class Reference
FRefCountedObject Class Reference
The base class of reference counted objects.
#include "RefCounting.h"
Public Member Functions
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Private Attributes
int32 NumRefs
Detailed Description
The base class of reference counted objects.
This class should not be used for new code as it does not use atomic operations to update the reference count.
Definition at line 251 of file RefCounting.h.
Constructor & Destructor Documentation
FRefCountedObject() [1/2]
FRefCountedObject::FRefCountedObject () inline
Definition at line 254 of file RefCounting.h.
References NumRefs.
Referenced by FRefCountedObject(), and operator=().
~FRefCountedObject()
virtual FRefCountedObject::~FRefCountedObject () inline virtual
Definition at line 255 of file RefCounting.h.
References check, and NumRefs.
FRefCountedObject() [2/2]
FRefCountedObject::FRefCountedObject (const FRefCountedObject & Rhs) delete
References FRefCountedObject().
Member Function Documentation
AddRef()
FReturnedRefCountValue FRefCountedObject::AddRef () const inline
Definition at line 258 of file RefCounting.h.
References NumRefs.
GetRefCount()
uint32 FRefCountedObject::GetRefCount () const inline
Definition at line 271 of file RefCounting.h.
References NumRefs.
operator=()
FRefCountedObject & FRefCountedObject::operator= (const FRefCountedObject & Rhs) delete
References FRefCountedObject().
Release()
uint32 FRefCountedObject::Release () const inline
Definition at line 262 of file RefCounting.h.
References NumRefs.
Field Documentation
NumRefs
int32 FRefCountedObject::NumRefs mutable private
Definition at line 276 of file RefCounting.h.
Referenced by FRefCountedObject(), ~FRefCountedObject(), AddRef(), GetRefCount(), and Release().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/RefCounting.h