Unreal Engine 5.6 C++ API: SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode > Class Template Reference
SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode > Class Template Reference
#include "SharedPointerInternals.h"
Public Member Functions
TReferenceControllerWithDeleter (const TReferenceControllerWithDeleter &)=delete
TReferenceControllerWithDeleter (ObjectType *InObject, DeleterType &&Deleter)
virtual void DestroyObject () override
Destroys the object associated with this reference counter.
TReferenceControllerWithDeleter & operator= (const TReferenceControllerWithDeleter &)=delete
Public Member Functions inherited from SharedPointerInternals::TReferenceControllerBase< Mode >
FORCEINLINE TReferenceControllerBase ()=default
TReferenceControllerBase (const TReferenceControllerBase &)=delete
virtual ~TReferenceControllerBase ()
FORCEINLINE void AddSharedReference ()
Adds a shared reference to this counter.
FORCEINLINE void AddWeakReference ()
Adds a weak reference to this counter.
bool ConditionallyAddSharedReference ()
Adds a shared reference to this counter ONLY if there is already at least one reference.
FORCEINLINE int32 GetSharedReferenceCount () const
Returns the shared reference count.
FORCEINLINE bool IsUnique () const
Checks if there is exactly one reference left to the object.
TReferenceControllerBase & operator= (const TReferenceControllerBase &)=delete
FORCEINLINE void ReleaseSharedReference ()
Releases a shared reference to this counter.
void ReleaseWeakReference ()
Releases a weak reference to this counter.
Private Attributes
ObjectType * Object
The object associated with this reference counter.
Additional Inherited Members
Data Fields inherited from SharedPointerInternals::TReferenceControllerBase< Mode >
RefCountType SharedReferenceCount {1}
RefCountType WeakReferenceCount {1}
Private Member Functions inherited from SharedPointerInternals::TDeleterHolder< DeleterType, bIsZeroSize >
TDeleterHolder (DeleterType &&Arg)
template<typename ObjectType>
void InvokeDeleter (ObjectType *Object)
Detailed Description
template<typename ObjectType, typename DeleterType, ESPMode Mode>
class SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >
Definition at line 364 of file SharedPointerInternals.h.
Constructor & Destructor Documentation
TReferenceControllerWithDeleter() [1/2]
template<typename ObjectType, typename DeleterType, ESPMode Mode> SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >::TReferenceControllerWithDeleter (ObjectType * InObject, DeleterType && Deleter) inline explicit
Definition at line 367 of file SharedPointerInternals.h.
References SharedPointerInternals::TDeleterHolder< DeleterType, bIsZeroSize >::TDeleterHolder(), MoveTemp(), and Object.
Referenced by TReferenceControllerWithDeleter(), and operator=().
TReferenceControllerWithDeleter() [2/2]
template<typename ObjectType, typename DeleterType, ESPMode Mode> SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >::TReferenceControllerWithDeleter (const TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode > &) delete
References TReferenceControllerWithDeleter().
Member Function Documentation
DestroyObject()
template<typename ObjectType, typename DeleterType, ESPMode Mode> virtual void SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >::DestroyObject () inline override virtual
Destroys the object associated with this reference counter.
Implements SharedPointerInternals::TReferenceControllerBase< Mode >.
Definition at line 373 of file SharedPointerInternals.h.
References SharedPointerInternals::TDeleterHolder< DeleterType, bIsZeroSize >::InvokeDeleter(), and Object.
operator=()
template<typename ObjectType, typename DeleterType, ESPMode Mode> TReferenceControllerWithDeleter & SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >::operator= (const TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode > &) delete
References TReferenceControllerWithDeleter().
Field Documentation
Object
template<typename ObjectType, typename DeleterType, ESPMode Mode> ObjectType* SharedPointerInternals::TReferenceControllerWithDeleter< ObjectType, DeleterType, Mode >::Object private
The object associated with this reference counter.
Definition at line 384 of file SharedPointerInternals.h.
Referenced by TReferenceControllerWithDeleter(), and DestroyObject().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/SharedPointerInternals.h