Unreal Engine 5.6 C++ API: FMetasoundAssetProxy Class Reference
FMetasoundAssetProxy Class Reference final
#include "MetasoundAssetBase.h"
Data Structures
struct FParameters
Public Member Functions
METASOUNDFRONTEND_API FMetasoundAssetProxy (const FMetasoundAssetProxy &Other)
METASOUNDFRONTEND_API FMetasoundAssetProxy (const FParameters &InParams)
const Metasound::IGraph * GetGraph () const
const TSet< FMetasoundFrontendVersion > & GetInterfaces () const
IMPL_AUDIOPROXY_CLASS (FMetasoundAssetProxy)
Private Attributes
TSharedPtr< const Metasound::IGraph > Graph
TSet< FMetasoundFrontendVersion > Interfaces
Detailed Description
Definition at line 273 of file MetasoundAssetBase.h.
Constructor & Destructor Documentation
FMetasoundAssetProxy() [1/2]
METASOUNDFRONTEND_API FMetasoundAssetProxy::FMetasoundAssetProxy (const FParameters & InParams) explicit
References UE_API.
Referenced by FMetasoundAssetProxy(), and IMPL_AUDIOPROXY_CLASS().
FMetasoundAssetProxy() [2/2]
METASOUNDFRONTEND_API FMetasoundAssetProxy::FMetasoundAssetProxy (const FMetasoundAssetProxy & Other)
References FMetasoundAssetProxy(), Other, and UE_API.
Member Function Documentation
GetGraph()
const Metasound::IGraph * FMetasoundAssetProxy::GetGraph () const inline
Definition at line 289 of file MetasoundAssetBase.h.
References Graph.
GetInterfaces()
const TSet< FMetasoundFrontendVersion > & FMetasoundAssetProxy::GetInterfaces () const inline
Definition at line 294 of file MetasoundAssetBase.h.
References Interfaces.
IMPL_AUDIOPROXY_CLASS()
FMetasoundAssetProxy::IMPL_AUDIOPROXY_CLASS (FMetasoundAssetProxy)
References FMetasoundAssetProxy().
Field Documentation
Graph
TSharedPtr<const Metasound::IGraph> FMetasoundAssetProxy::Graph private
Definition at line 302 of file MetasoundAssetBase.h.
Referenced by GetGraph().
Interfaces
TSet<FMetasoundFrontendVersion> FMetasoundAssetProxy::Interfaces private
Definition at line 301 of file MetasoundAssetBase.h.
Referenced by GetInterfaces().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundAssetBase.h