Unreal Engine 5.6 C++ API: Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num > Class Template Reference
Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num > Class Template Reference
#include "BiquadFilter.h"
Public Member Functions
TMultipassBiquadFilter ()
~TMultipassBiquadFilter ()
void Process (float const *input, float *output, uint32 InNumSamples, const FBiquadFilterCoefs &InCoefs, double InGain=1.0, int32 InNumPasses=Num)
void ProcessInterleaved (TDynamicStridePtr< float > &input, TDynamicStridePtr< float > &output, int32 InNumSamples, const FBiquadFilterCoefs &InCoefs, double InGain=1.0, int32 InNumPasses=Num)
void ResetState ()
Private Attributes
T History [2 *Num]
Detailed Description
template<typename T, int32 Num>
class Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >
Definition at line 306 of file BiquadFilter.h.
Constructor & Destructor Documentation
TMultipassBiquadFilter()
template<typename T, int32 Num> Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::TMultipassBiquadFilter () inline
Definition at line 310 of file BiquadFilter.h.
References ResetState().
~TMultipassBiquadFilter()
template<typename T, int32 Num> Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::~TMultipassBiquadFilter () inline
Definition at line 311 of file BiquadFilter.h.
Member Function Documentation
Process()
template<typename T, int32 Num> void Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::Process (float const * input, float * output, uint32 InNumSamples, const FBiquadFilterCoefs & InCoefs, double InGain = 1.0, int32 InNumPasses = Num) inline
Definition at line 318 of file BiquadFilter.h.
References Harmonix::Dsp::Effects::FBiquadFilterCoefs::A1, Harmonix::Dsp::Effects::FBiquadFilterCoefs::A2, Harmonix::Dsp::Effects::FBiquadFilterCoefs::B0, Harmonix::Dsp::Effects::FBiquadFilterCoefs::B1, Harmonix::Dsp::Effects::FBiquadFilterCoefs::B2, float, History, and Num.
ProcessInterleaved()
template<typename T, int32 Num> void Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::ProcessInterleaved (TDynamicStridePtr< float > & input, TDynamicStridePtr< float > & output, int32 InNumSamples, const FBiquadFilterCoefs & InCoefs, double InGain = 1.0, int32 InNumPasses = Num) inline
Definition at line 380 of file BiquadFilter.h.
References Harmonix::Dsp::Effects::FBiquadFilterCoefs::A1, Harmonix::Dsp::Effects::FBiquadFilterCoefs::A2, Harmonix::Dsp::Effects::FBiquadFilterCoefs::B0, Harmonix::Dsp::Effects::FBiquadFilterCoefs::B1, Harmonix::Dsp::Effects::FBiquadFilterCoefs::B2, float, History, and Num.
ResetState()
template<typename T, int32 Num> void Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::ResetState () inline
Definition at line 313 of file BiquadFilter.h.
References History, FMemory::Memset(), and Num.
Referenced by TMultipassBiquadFilter().
Field Documentation
History
template<typename T, int32 Num> T Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::History[2 *Num] private
Definition at line 442 of file BiquadFilter.h.
Referenced by Process(), ProcessInterleaved(), and ResetState().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixDsp/Public/HarmonixDsp/Effects/BiquadFilter.h