Unreal Engine 5.6 C++ API: FFieldVariant Class Reference
FFieldVariant Class Reference
Special container that can hold either UObject or FField.
#include "Field.h"
Data Structures
union FFieldObjectUnion
Public Member Functions
FFieldVariant ()
FFieldVariant (const FField *InField)
FFieldVariant (const FFieldVariant &Other)
FFieldVariant (FFieldVariant &&Other)
template<typename T UE_REQUIRES>
FFieldVariant (T &&InObject)
FFieldVariant (TYPE_OF_NULLPTR)
template<typename T>
T * Get () const
FString GetClassName () const
FName GetFName () const
FString GetFullName () const
FString GetName () const
UPackage * GetOutermost () const
UClass * GetOwnerClass () const
FFieldVariant GetOwnerVariant () const
FString GetPathName () const
void * GetRawPointer () const
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *InClass) const
bool IsA (const UClass *InClass) const
bool IsNative () const
bool IsUObject () const
bool IsValid () const
bool IsValidLowLevel () const
operator bool () const
bool operator!= (const FFieldVariant &Other) const
FFieldVariant & operator= (const FFieldVariant &Other)
FFieldVariant & operator= (FFieldVariant &&Other)
bool operator== (const FFieldVariant &Other) const
FField * ToField () const
FORCEINLINE FField * ToFieldUnsafe () const
FOR INTERNAL USE ONLY: Function that returns the owner as FField without checking if it's actually an FField.
UObject * ToUObject () const
FORCEINLINE UObject * ToUObjectUnsafe () const
FOR INTERNAL USE ONLY: Function that returns the owner as UObject without checking if it's actually a UObject.
Private Member Functions
void ConditionallyMarkAsReachable ()
Private Attributes
union FFieldVariant::FFieldObjectUnion Container
Static Private Attributes
static constexpr uintptr_t UObjectMask = 0x1
Friends
uint32 GetTypeHash (const FFieldVariant &InFieldVariant)
Support comparison functions that make this usable as a KeyValue for a TSet<>
Detailed Description
Special container that can hold either UObject or FField.
Exposes common interface of FFields and UObjects for easier transition from UProperties to FProperties. DO NOT ABUSE. IDEALLY THIS SHOULD ONLY BE FFIELD INTERNAL STRUCTURE FOR HOLDING A POINTER TO THE OWNER OF AN FFIELD.
Definition at line 270 of file Field.h.
Constructor & Destructor Documentation
FFieldVariant() [1/6]
FFieldVariant::FFieldVariant () inline
Definition at line 290 of file Field.h.
References Container.
Referenced by FFieldVariant(), FFieldVariant(), FFieldVariant(), GetOwnerVariant(), GetTypeHash, operator!=(), operator=(), operator=(), and operator==().
FFieldVariant() [2/6]
FFieldVariant::FFieldVariant (const FField * InField) inline
Definition at line 295 of file Field.h.
References check, Container, and IsUObject().
FFieldVariant() [3/6]
template<typename T UE_REQUIRES> FFieldVariant::FFieldVariant (T && InObject) inline
Definition at line 305 of file Field.h.
References ConditionallyMarkAsReachable(), Container, ImplicitConv(), and UObjectMask.
FFieldVariant() [4/6]
FFieldVariant::FFieldVariant (TYPE_OF_NULLPTR) inline
Definition at line 312 of file Field.h.
References FFieldVariant().
FFieldVariant() [5/6]
FFieldVariant::FFieldVariant (const FFieldVariant & Other) inline
Definition at line 317 of file Field.h.
References FFieldVariant(), ConditionallyMarkAsReachable(), Container, and Other.
FFieldVariant() [6/6]
FFieldVariant::FFieldVariant (FFieldVariant && Other) inline
Definition at line 330 of file Field.h.
References FFieldVariant(), ConditionallyMarkAsReachable(), Container, and Other.
Member Function Documentation
ConditionallyMarkAsReachable()
void FFieldVariant::ConditionallyMarkAsReachable () inline private
Definition at line 280 of file Field.h.
References UE::GC::GIsIncrementalReachabilityPending, IsUObject(), UE::GC::MarkAsReachable(), and ToUObjectUnsafe().
Referenced by FFieldVariant(), FFieldVariant(), FFieldVariant(), operator=(), and operator=().
Get()
template<typename T> T * FFieldVariant::Get () const inline
Definition at line 366 of file Field.h.
References Container, IsA(), and ToUObjectUnsafe().
Referenced by USTRUCT().
GetClassName()
FString FFieldVariant::GetClassName () const
GetFName()
FName FFieldVariant::GetFName () const
GetFullName()
FString FFieldVariant::GetFullName () const
GetName()
FString FFieldVariant::GetName () const
GetOutermost()
UPackage * FFieldVariant::GetOutermost () const
GetOwnerClass()
UClass * FFieldVariant::GetOwnerClass () const
GetOwnerVariant()
FFieldVariant FFieldVariant::GetOwnerVariant () const
References FFieldVariant().
GetPathName()
FString FFieldVariant::GetPathName () const
GetRawPointer()
void * FFieldVariant::GetRawPointer () const inline
Definition at line 416 of file Field.h.
References Container.
Referenced by FClassNetCache::GetFromField(), and GetTypeHash.
IsA() [1/3]
template<typename T> bool FFieldVariant::IsA () const inline
Definition at line 359 of file Field.h.
References IsA().
Referenced by Get(), and IsA().
IsA() [2/3]
bool FFieldVariant::IsA (const FFieldClass * InClass) const
IsA() [3/3]
bool FFieldVariant::IsA (const UClass * InClass) const
IsNative()
bool FFieldVariant::IsNative () const
IsUObject()
bool FFieldVariant::IsUObject () const inline
Definition at line 343 of file Field.h.
References Container, and UObjectMask.
Referenced by FBindingObject::FBindingObject(), FFieldVariant(), ConditionallyMarkAsReachable(), FField::GetOwnerUObject(), ToField(), and ToUObject().
IsValid()
bool FFieldVariant::IsValid () const inline
Definition at line 347 of file Field.h.
References ToUObjectUnsafe().
Referenced by FField::GetOwnerUObject(), and operator bool().
IsValidLowLevel()
bool FFieldVariant::IsValidLowLevel () const
operator bool()
FFieldVariant::operator bool () const inline
Definition at line 352 of file Field.h.
References IsValid().
operator!=()
bool FFieldVariant::operator!= (const FFieldVariant & Other) const inline
Definition at line 434 of file Field.h.
References FFieldVariant(), Container, and Other.
operator=() [1/2]
FFieldVariant & FFieldVariant::operator= (const FFieldVariant & Other) inline
Definition at line 323 of file Field.h.
References FFieldVariant(), ConditionallyMarkAsReachable(), Container, and Other.
operator=() [2/2]
FFieldVariant & FFieldVariant::operator= (FFieldVariant && Other) inline
Definition at line 336 of file Field.h.
References FFieldVariant(), ConditionallyMarkAsReachable(), Container, and Other.
operator==()
bool FFieldVariant::operator== (const FFieldVariant & Other) const inline
Definition at line 430 of file Field.h.
References FFieldVariant(), Container, and Other.
ToField()
FField * FFieldVariant::ToField () const inline
Definition at line 394 of file Field.h.
References Container, and IsUObject().
Referenced by FBindingObject::FBindingObject().
ToFieldUnsafe()
FORCEINLINE FField * FFieldVariant::ToFieldUnsafe () const inline
FOR INTERNAL USE ONLY: Function that returns the owner as FField without checking if it's actually an FField.
Definition at line 406 of file Field.h.
References Container, and FORCEINLINE.
Referenced by FField::GetOwnerUObject().
ToUObject()
UObject * FFieldVariant::ToUObject () const inline
Definition at line 383 of file Field.h.
References IsUObject(), and ToUObjectUnsafe().
Referenced by FBindingObject::FBindingObject(), and FField::GetOwnerUObject().
ToUObjectUnsafe()
FORCEINLINE UObject * FFieldVariant::ToUObjectUnsafe () const inline
FOR INTERNAL USE ONLY: Function that returns the owner as UObject without checking if it's actually a UObject.
Definition at line 411 of file Field.h.
References Container, FORCEINLINE, and UObjectMask.
Referenced by ConditionallyMarkAsReachable(), Get(), IsValid(), and ToUObject().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FFieldVariant & InFieldVariant) friend
Support comparison functions that make this usable as a KeyValue for a TSet<>
Definition at line 444 of file Field.h.
References FFieldVariant(), GetRawPointer(), and GetTypeHash.
Referenced by GetTypeHash.
Field Documentation
Container
union FFieldVariant::FFieldObjectUnion FFieldVariant::Container private
Referenced by FFieldVariant(), FFieldVariant(), FFieldVariant(), FFieldVariant(), FFieldVariant(), Get(), GetRawPointer(), IsUObject(), operator!=(), operator=(), operator=(), operator==(), ToField(), ToFieldUnsafe(), and ToUObjectUnsafe().
UObjectMask
uintptr_t FFieldVariant::UObjectMask = 0x1 static constexpr private
Definition at line 278 of file Field.h.
Referenced by FFieldVariant(), IsUObject(), and ToUObjectUnsafe().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/Field.h