Unreal Engine 5.6 C++ API: IMovieSceneObjectSpawner Class Reference
IMovieSceneObjectSpawner Class Reference abstract
Interface used to extend spawn registers to support extra types.
#include "IMovieSceneObjectSpawner.h"
Public Member Functions
virtual ~IMovieSceneObjectSpawner ()
Virtual destructor.
virtual bool CanConvertSpawnableToPossessable (FMovieSceneSpawnable &Spawnable) const
Check whether the specified Spawnable can become a Possessable.
virtual bool CanSetupDefaultsForSpawnable (UObject *SpawnedObject) const
virtual TValueOrError< FNewSpawnable, FText > CreateNewSpawnableType (UObject &SourceObject, UMovieScene &OwnerMovieScene, UActorFactory *ActorFactory=nullptr)
Create a new spawnable type from the given source object.
virtual void DestroySpawnedObject (UObject &Object)=0
Destroy a specific previously spawned object.
virtual int32 GetSpawnerPriority () const
virtual UClass * GetSupportedTemplateType () const =0
Returns the type of object we can spawn.
virtual bool IsEditor () const
virtual void SetupDefaultsForSpawnable (UObject *SpawnedObject, const FGuid &Guid, const TOptional< FTransformData > &TransformData, TSharedRef< ISequencer > Sequencer, USequencerSettings *Settings)
Setup a new spawnable object with some default tracks and keys.
virtual UObject * SpawnObject (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState)=0
Spawn an object for the specified GUID, from the specified sequence instance.
Detailed Description
Interface used to extend spawn registers to support extra types.
Definition at line 41 of file IMovieSceneObjectSpawner.h.
Constructor & Destructor Documentation
~IMovieSceneObjectSpawner()
virtual IMovieSceneObjectSpawner::~IMovieSceneObjectSpawner () inline virtual
Virtual destructor.
Definition at line 123 of file IMovieSceneObjectSpawner.h.
Member Function Documentation
CanConvertSpawnableToPossessable()
virtual bool IMovieSceneObjectSpawner::CanConvertSpawnableToPossessable (FMovieSceneSpawnable & Spawnable) const inline virtual
Check whether the specified Spawnable can become a Possessable.
Parameters
Spawnable The spawnable to check
Returns
whether the conversion from Spawnable to Possessable can occur.
Definition at line 116 of file IMovieSceneObjectSpawner.h.
CanSetupDefaultsForSpawnable()
virtual bool IMovieSceneObjectSpawner::CanSetupDefaultsForSpawnable (UObject * SpawnedObject) const inline virtual
Definition at line 109 of file IMovieSceneObjectSpawner.h.
References GetSupportedTemplateType(), and UObjectBaseUtility::IsA().
CreateNewSpawnableType()
virtual TValueOrError< FNewSpawnable, FText > IMovieSceneObjectSpawner::CreateNewSpawnableType (UObject & SourceObject, UMovieScene & OwnerMovieScene, UActorFactory * ActorFactory = nullptr) inline virtual
Create a new spawnable type from the given source object.
Parameters
SourceObject The source object to create the spawnable from
OwnerMovieScene The owner movie scene that this spawnable type should reside in
ActorFactory Optional actor factory to use to create spawnable type
Returns
the new spawnable type, or error
Definition at line 90 of file IMovieSceneObjectSpawner.h.
References MakeError(), and NSLOCTEXT.
DestroySpawnedObject()
virtual void IMovieSceneObjectSpawner::DestroySpawnedObject (UObject & Object) pure virtual
Destroy a specific previously spawned object.
Parameters
Object The object to destroy
Implemented in FLevelSequenceActorSpawner.
References Object.
GetSpawnerPriority()
virtual int32 IMovieSceneObjectSpawner::GetSpawnerPriority () const inline virtual
Returns
Spawner priority in order to sort the list of the spawners. If several spawners match the template type, the one with the highest priority will be picked.
Reimplemented in FChaosCacheObjectSpawner.
Definition at line 78 of file IMovieSceneObjectSpawner.h.
GetSupportedTemplateType()
virtual UClass * IMovieSceneObjectSpawner::GetSupportedTemplateType () const pure virtual
Returns the type of object we can spawn.
Returns
the class of the object we support for spawning
Implemented in FLevelSequenceActorSpawner.
Referenced by CanSetupDefaultsForSpawnable().
IsEditor()
virtual bool IMovieSceneObjectSpawner::IsEditor () const inline virtual
Returns
true if this spawner is used in the editor, or false if it is purely runtime. We use this to prioritize the use of editor spawners when in editor
Reimplemented in FChaosCacheObjectSpawner.
Definition at line 72 of file IMovieSceneObjectSpawner.h.
SetupDefaultsForSpawnable()
virtual void IMovieSceneObjectSpawner::SetupDefaultsForSpawnable (UObject * SpawnedObject, const FGuid & Guid, const TOptional< FTransformData > & TransformData, TSharedRef< ISequencer > Sequencer, USequencerSettings * Settings) inline virtual
Setup a new spawnable object with some default tracks and keys.
Parameters
SpawnedObject The newly spawned object. This may be NULL in the case of a spawnable that has not yet neen spawned.
Guid The ID of the spawnable to setup defaults for
TransformData The transform of the object to be spawned. This will usually be valid in the case of converting a possessable to a spawnable.
Sequencer The sequencer this spawnable was just created by
Settings The settings for this sequencer
Definition at line 101 of file IMovieSceneObjectSpawner.h.
References Guid.
SpawnObject()
virtual UObject * IMovieSceneObjectSpawner::SpawnObject (FMovieSceneSpawnable & Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) pure virtual
Spawn an object for the specified GUID, from the specified sequence instance.
Parameters
Object ID of the object to spawn
TemplateID Identifier for the current template we're evaluating
Player Movie scene player that is ultimately responsible for spawning the object
Returns
the spawned object, or nullptr on failure
Implemented in FLevelSequenceActorSpawner.
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/IMovieSceneObjectSpawner.h