Unreal Engine 5.6 C++ API: FBlake3 Class Reference
FBlake3 Class Reference
Calculates a BLAKE3 hash.
#include "Blake3.h"
Public Member Functions
FBlake3 ()
FBlake3 (const FBlake3 &)=delete
FBlake3Hash Finalize () const
Finalize the hash of the input data.
FBlake3 & operator= (const FBlake3 &)=delete
void Reset ()
Reset to the default state in which no input has been written.
void Update (const FCompositeBuffer &Buffer)
void Update (const void *Data, uint64 Size)
void Update (FMemoryView View)
Add the buffer as input to the hash.
Static Public Member Functions
static FBlake3Hash HashBuffer (const FCompositeBuffer &Buffer)
static FBlake3Hash HashBuffer (const void *Data, uint64 Size)
static FBlake3Hash HashBuffer (FMemoryView View)
Calculate the hash of the buffer.
Private Attributes
TAlignedBytes< 1912, 8 > HasherBytes
Detailed Description
Calculates a BLAKE3 hash.
Definition at line 93 of file Blake3.h.
Constructor & Destructor Documentation
FBlake3() [1/2]
FBlake3::FBlake3 () inline
Definition at line 96 of file Blake3.h.
References Reset().
Referenced by FBlake3(), and operator=().
FBlake3() [2/2]
FBlake3::FBlake3 (const FBlake3 &) delete
References FBlake3().
Member Function Documentation
Finalize()
FBlake3Hash FBlake3::Finalize () const nodiscard
Finalize the hash of the input data.
May be called any number of times, and more input may be added after.
Referenced by FIoHashBuilder::Finalize().
HashBuffer() [1/3]
FBlake3Hash FBlake3::HashBuffer (const FCompositeBuffer & Buffer) static nodiscard
References Buffer.
HashBuffer() [2/3]
FBlake3Hash FBlake3::HashBuffer (const void * Data, uint64 Size) static nodiscard
References TSequenceHistory< HistorySize >::Size.
HashBuffer() [3/3]
FBlake3Hash FBlake3::HashBuffer (FMemoryView View) static nodiscard
Calculate the hash of the buffer.
Referenced by FIoHash::HashBuffer(), FIoHash::HashBuffer(), FIoHash::HashBuffer(), FIoHashBuilder::HashBuffer(), FIoHashBuilder::HashBuffer(), and FIoHashBuilder::HashBuffer().
operator=()
FBlake3 & FBlake3::operator= (const FBlake3 &) delete
References FBlake3().
Reset()
void FBlake3::Reset ()
Reset to the default state in which no input has been written.
Referenced by FBlake3().
Update() [1/3]
void FBlake3::Update (const FCompositeBuffer & Buffer)
References Buffer.
Update() [2/3]
void FBlake3::Update (const void * Data, uint64 Size)
References TSequenceHistory< HistorySize >::Size.
Update() [3/3]
void FBlake3::Update (FMemoryView View)
Add the buffer as input to the hash.
May be called any number of times.
Field Documentation
HasherBytes
TAlignedBytes<1912, 8> FBlake3::HasherBytes private
Definition at line 122 of file Blake3.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Hash/Blake3.h