Unreal Engine 5.6 C++ API: Metasound::FMetaSoundParameterTransmitter Class Reference
Metasound::FMetaSoundParameterTransmitter Class Reference
FMetaSoundParameterTransmitter provides a communication interface for sending values to a MetaSound instance.
#include "MetasoundParameterTransmitter.h"
Data Structures
struct FInitParams
Initialization parameters for a FMetaSoundParameterTransmitter.
struct FParameter
struct FSendInfo
FSendInfo describes the MetaSounds input parameters as well as the necessary information to route data to the instances inputs.
Public Member Functions
METASOUNDFRONTEND_API FMetaSoundParameterTransmitter (FMetaSoundParameterTransmitter::FInitParams &&InInitParams)
virtual ~FMetaSoundParameterTransmitter ()=default
METASOUNDFRONTEND_API void AddAvailableParameter (FName InName)
METASOUNDFRONTEND_API void RemoveAvailableParameter (FName InName)
virtual METASOUNDFRONTEND_API bool SetParameters (TArray< FAudioParameter > &&InParameters) override
Sets parameters using array of AudioParameter structs.
METASOUNDFRONTEND_API bool SetParameterWithLiteral (FName InParameterName, const FLiteral &InValue)
Set a parameter using a literal.
UE_DEPRECATED (5.3, "This function is no longer used. Send addresses are no longer used when communicating with MetaSound inputs") static METASOUNDFRONTEND_API FSendAddress CreateSendAddressFromEnvironment(const FMetasoundEnvironment &InEnvironment
Creates a unique send address using the given MetaSound environment.
UE_DEPRECATED (5.3, "This function is no longer used. Send addresses are no longer used when communicating with MetaSound inputs") static METASOUNDFRONTEND_API FSendAddress CreateSendAddressFromInstanceID(uint64 InInstanceID
Creates a unique send address using the given InstanceID.
Data Fields
const FVertexName const FName & InTypeName
const FVertexName & InVertexName
Private Member Functions
FMetaSoundParameterTransmitter (const FMetaSoundParameterTransmitter &)=delete
FMetaSoundParameterTransmitter & operator= (const FMetaSoundParameterTransmitter &)=delete
METASOUNDFRONTEND_API bool SetVirtualizedParameters (TArray< FAudioParameter > &&InParameters)
Set parameters when virtualized.
Private Attributes
TArray< FName > AvailableParameterNames
TSharedPtr< TSpscQueue< FParameter > > DataChannel
FName DebugMetaSoundName
uint64 InstanceID
Detailed Description
FMetaSoundParameterTransmitter provides a communication interface for sending values to a MetaSound instance.
It relies on the send/receive transmission system to ferry data from the transmitter to the MetaSound instance. Data will be safely ushered across thread boundaries in scenarios where the instance transmitter and metasound instance live on different threads.
Definition at line 38 of file MetasoundParameterTransmitter.h.
Constructor & Destructor Documentation
FMetaSoundParameterTransmitter() [1/2]
Metasound::FMetaSoundParameterTransmitter::FMetaSoundParameterTransmitter (const FMetaSoundParameterTransmitter &) private delete
References FMetaSoundParameterTransmitter().
Referenced by FMetaSoundParameterTransmitter(), FMetaSoundParameterTransmitter(), ~FMetaSoundParameterTransmitter(), and operator=().
FMetaSoundParameterTransmitter() [2/2]
METASOUNDFRONTEND_API Metasound::FMetaSoundParameterTransmitter::FMetaSoundParameterTransmitter (FMetaSoundParameterTransmitter::FInitParams && InInitParams)
References FMetaSoundParameterTransmitter(), and UE_API.
~FMetaSoundParameterTransmitter()
virtual Metasound::FMetaSoundParameterTransmitter::~FMetaSoundParameterTransmitter () virtual default
References FMetaSoundParameterTransmitter().
Member Function Documentation
AddAvailableParameter()
METASOUNDFRONTEND_API void Metasound::FMetaSoundParameterTransmitter::AddAvailableParameter (FName InName)
References AddAvailableParameter(), InName, and UE_API.
Referenced by AddAvailableParameter().
operator=()
FMetaSoundParameterTransmitter & Metasound::FMetaSoundParameterTransmitter::operator= (const FMetaSoundParameterTransmitter &) private delete
References FMetaSoundParameterTransmitter().
RemoveAvailableParameter()
METASOUNDFRONTEND_API void Metasound::FMetaSoundParameterTransmitter::RemoveAvailableParameter (FName InName)
References InName, RemoveAvailableParameter(), and UE_API.
Referenced by RemoveAvailableParameter().
SetParameters()
virtual METASOUNDFRONTEND_API bool Metasound::FMetaSoundParameterTransmitter::SetParameters (TArray< FAudioParameter > && InParameters) override virtual
Sets parameters using array of AudioParameter structs.
Parameters
InParameter - Parameter to set.
References SetParameters(), and UE_API.
Referenced by SetParameters().
SetParameterWithLiteral()
METASOUNDFRONTEND_API bool Metasound::FMetaSoundParameterTransmitter::SetParameterWithLiteral (FName InParameterName, const FLiteral & InValue)
Set a parameter using a literal.
Parameters
InParameterName - Name of MetaSound instance parameter.
InValue - Literal value used to construct parameter value.
Returns
true on success, false on failure.
References SetParameterWithLiteral(), and UE_API.
Referenced by SetParameterWithLiteral().
SetVirtualizedParameters()
METASOUNDFRONTEND_API bool Metasound::FMetaSoundParameterTransmitter::SetVirtualizedParameters (TArray< FAudioParameter > && InParameters) private
Set parameters when virtualized.
Returns
true if all non trigger parameters are set on the parameter base (trigger parameters are removed on virtualized sounds and parameters are not actually set on the MetaSound until realization)
References SetVirtualizedParameters(), and UE_API.
Referenced by SetVirtualizedParameters().
UE_DEPRECATED() [1/2]
Metasound::FMetaSoundParameterTransmitter::UE_DEPRECATED (5. 3, "This function is no longer used. Send addresses are no longer used when communicating with MetaSound inputs") const &
Creates a unique send address using the given MetaSound environment.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
Metasound::FMetaSoundParameterTransmitter::UE_DEPRECATED (5. 3, "This function is no longer used. Send addresses are no longer used when communicating with MetaSound inputs")
Creates a unique send address using the given InstanceID.
References InTypeName, InVertexName, UE_API, and UE_DEPRECATED().
Field Documentation
AvailableParameterNames
TArray<FName> Metasound::FMetaSoundParameterTransmitter::AvailableParameterNames private
Definition at line 141 of file MetasoundParameterTransmitter.h.
DataChannel
TSharedPtr<TSpscQueue<FParameter> > Metasound::FMetaSoundParameterTransmitter::DataChannel private
Definition at line 142 of file MetasoundParameterTransmitter.h.
DebugMetaSoundName
FName Metasound::FMetaSoundParameterTransmitter::DebugMetaSoundName private
Definition at line 140 of file MetasoundParameterTransmitter.h.
InstanceID
uint64 Metasound::FMetaSoundParameterTransmitter::InstanceID private
Definition at line 139 of file MetasoundParameterTransmitter.h.
InTypeName
const FVertexName const FName & Metasound::FMetaSoundParameterTransmitter::InTypeName
Definition at line 103 of file MetasoundParameterTransmitter.h.
Referenced by UE_DEPRECATED().
InVertexName
const FVertexName & Metasound::FMetaSoundParameterTransmitter::InVertexName
Definition at line 103 of file MetasoundParameterTransmitter.h.
Referenced by UE_DEPRECATED().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundParameterTransmitter.h