Unreal Engine 5.6 C++ API: FUObjectArray::TIterator Class Reference
FUObjectArray::TIterator Class Reference
Low level iterator.
#include "UObjectArray.h"
Public Types
enum EEndTagType { EndTag }
Public Member Functions
TIterator (const FUObjectArray &InArray, bool bOnlyGCedObjects=false)
Constructor.
TIterator (EEndTagType, const TIterator &InIter)
Constructor.
FORCEINLINE int32 GetIndex () const
FORCEINLINE operator bool () const
Conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
bool operator!= (const TIterator &Rhs) const
FORCEINLINE void operator++ ()
Iterator advance.
bool operator== (const TIterator &Rhs) const
Protected Member Functions
FORCEINLINE bool Advance ()
Iterator advance with ordinary name for clarity in subclasses.
const FUObjectArray & GetIteratedArray () const
Gets the array this iterator iterates over.
FORCEINLINE FUObjectItem * GetObject () const
Dereferences the iterator with an ordinary name for clarity in derived classes.
Private Attributes
const FUObjectArray & Array
the array that we are iterating on, probably always GUObjectArray
FUObjectItem * CurrentObject
Current object.
int32 Index
index of the current element in the object array
Detailed Description
Low level iterator.
Definition at line 1290 of file UObjectArray.h.
Member Enumeration Documentation
EEndTagType
enum FUObjectArray::TIterator::EEndTagType
Enumerator
EndTag
Definition at line 1293 of file UObjectArray.h.
Constructor & Destructor Documentation
TIterator() [1/2]
FUObjectArray::TIterator::TIterator (const FUObjectArray & InArray, bool bOnlyGCedObjects = false) inline
Constructor.
Parameters
InArray the array to iterate on
bOnlyGCedObjects if true, skip all of the permanent objects
Definition at line 1304 of file UObjectArray.h.
References FUObjectArray::FUObjectArray(), Advance(), Array, CurrentObject, and Index.
Referenced by FRawObjectIterator::FRawObjectIterator(), TIterator(), TObjectIterator< UObject >::TObjectIterator(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), operator!=(), and operator==().
TIterator() [2/2]
FUObjectArray::TIterator::TIterator (EEndTagType , const TIterator & InIter) inline
Constructor.
Parameters
InArray the array to iterate on
bOnlyGCedObjects if true, skip all of the permanent objects
Definition at line 1322 of file UObjectArray.h.
References TIterator(), Array, Index, Num, and FUObjectArray::ObjObjects.
Member Function Documentation
Advance()
FORCEINLINE bool FUObjectArray::TIterator::Advance () inline protected
Iterator advance with ordinary name for clarity in subclasses.
Returns
true if the iterator points to a valid object, false if iteration is complete
Definition at line 1370 of file UObjectArray.h.
References Array, CurrentObject, FORCEINLINE, FUObjectItem::GetObject(), and Index.
Referenced by TIterator(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::AdvanceIterator(), and operator++().
GetIndex()
FORCEINLINE int32 FUObjectArray::TIterator::GetIndex () const inline
Definition at line 1350 of file UObjectArray.h.
References FORCEINLINE, and Index.
GetIteratedArray()
const FUObjectArray & FUObjectArray::TIterator::GetIteratedArray () const inline protected
Gets the array this iterator iterates over.
Definition at line 1388 of file UObjectArray.h.
References FUObjectArray::FUObjectArray(), and Array.
Referenced by TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::~TObjectIteratorBase(), and TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::AdvanceIterator().
GetObject()
FORCEINLINE FUObjectItem * FUObjectArray::TIterator::GetObject () const inline protected
Dereferences the iterator with an ordinary name for clarity in derived classes.
Returns
the UObject at the iterator
Definition at line 1362 of file UObjectArray.h.
References CurrentObject, and FORCEINLINE.
Referenced by FRawObjectIterator::operator*(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::operator*(), FRawObjectIterator::operator->(), and TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::operator->().
operator bool()
FORCEINLINE FUObjectArray::TIterator::operator bool () const inline explicit
Conversion to "bool" returning true if the iterator is valid.
Definition at line 1340 of file UObjectArray.h.
References CurrentObject, and FORCEINLINE.
operator!()
FORCEINLINE bool FUObjectArray::TIterator::operator! () const inline
inverse of the "bool" operator
Definition at line 1345 of file UObjectArray.h.
References bool, and FORCEINLINE.
operator!=()
bool FUObjectArray::TIterator::operator!= (const TIterator & Rhs) const inline
Definition at line 1337 of file UObjectArray.h.
References TIterator(), and Index.
operator++()
FORCEINLINE void FUObjectArray::TIterator::operator++ () inline
Iterator advance.
Definition at line 1331 of file UObjectArray.h.
References Advance(), and FORCEINLINE.
operator==()
bool FUObjectArray::TIterator::operator== (const TIterator & Rhs) const inline
Definition at line 1336 of file UObjectArray.h.
References TIterator(), and Index.
Field Documentation
Array
const FUObjectArray& FUObjectArray::TIterator::Array private
the array that we are iterating on, probably always GUObjectArray
Definition at line 1395 of file UObjectArray.h.
Referenced by TIterator(), TIterator(), Advance(), and GetIteratedArray().
CurrentObject
FUObjectItem* FUObjectArray::TIterator::CurrentObject mutable private
Current object.
Definition at line 1399 of file UObjectArray.h.
Referenced by TIterator(), Advance(), GetObject(), and operator bool().
Index
int32 FUObjectArray::TIterator::Index private
index of the current element in the object array
Definition at line 1397 of file UObjectArray.h.
Referenced by TIterator(), TIterator(), Advance(), GetIndex(), operator!=(), and operator==().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectArray.h