Unreal Engine 5.6 C++ API: FGCObjectInfo Class Reference
FGCObjectInfo Class Reference
Structure containing information about a UObject participating in Garbage Collection.
#include "GCObjectInfo.h"
Public Member Functions
FGCObjectInfo ()=default
FGCObjectInfo (const UObject *Obj)
FGCObjectInfo * GetClass () const
FString GetClassName () const
FString GetFullName () const
FGCObjectInfo * GetOuter () const
int32 GetOwnerIndex () const
FString GetPathName () const
void GetPathName (FStringBuilderBase &ResultString) const
int32 GetRefCount () const
bool HasAnyFlags (EObjectFlags InFlags) const
bool HasAnyInternalFlags (EInternalObjectFlags InFlags) const
bool IsDisregardForGC () const
bool IsGarbage () const
bool IsIn (const FGCObjectInfo *MaybeOuter) const
bool IsNative () const
bool IsRooted () const
bool IsValid () const
UObject * TryResolveObject ()
Tries to find an existing object matching the stored Path.
Static Public Member Functions
static FGCObjectInfo * FindOrAddInfoHelper (const UObject *InObject, TMap< const UObject *, FGCObjectInfo * > &InOutObjectToInfoMap)
Helper function for adding info about an UObject into UObject to FGCObjectInfo map.
Private Attributes
bool bDisregardForGC = false
True if the object was inside of the disregard for GC set.
FGCObjectInfo * Class = nullptr
Pointer to class info.
int32 ClusterRootIndex = -1
Object's FGCObjectItem cluster root index.
EObjectFlags Flags = RF_NoFlags
Captured Object flags.
EInternalObjectFlags InternalFlags = EInternalObjectFlags::None
Captured Internal flags.
FName Name
Name of the object.
FGCObjectInfo * Outer = nullptr
Pointer to Outer info.
int32 RefCount = 0
Current ref-count of the UObject.
Friends
uint32 GetTypeHash (const FGCObjectInfo &Info)
Detailed Description
Structure containing information about a UObject participating in Garbage Collection.
It's purpose is to avoid holding onto direct references to UObjects which may have already been Garbage Collected. FGCObjectInfo interface mimics that of UObject.
Definition at line 27 of file GCObjectInfo.h.
Constructor & Destructor Documentation
FGCObjectInfo() [1/2]
FGCObjectInfo::FGCObjectInfo () default
Referenced by FindOrAddInfoHelper(), GetClass(), GetOuter(), GetTypeHash, and IsIn().
FGCObjectInfo() [2/2]
FGCObjectInfo::FGCObjectInfo (const UObject * Obj) inline explicit
Definition at line 32 of file GCObjectInfo.h.
References bDisregardForGC, ClusterRootIndex, Flags, GetOwnerIndex(), GetRefCount(), GUObjectArray, InternalFlags, IsDisregardForGC(), Name, and RefCount.
Member Function Documentation
FindOrAddInfoHelper()
FGCObjectInfo * FGCObjectInfo::FindOrAddInfoHelper (const UObject * InObject, TMap< const UObject *, FGCObjectInfo * > & InOutObjectToInfoMap) static
Helper function for adding info about an UObject into UObject to FGCObjectInfo map.
References FGCObjectInfo().
GetClass()
FGCObjectInfo * FGCObjectInfo::GetClass () const inline
Definition at line 70 of file GCObjectInfo.h.
References FGCObjectInfo(), and Class.
GetClassName()
FString FGCObjectInfo::GetClassName () const inline
Definition at line 122 of file GCObjectInfo.h.
References check, and Class.
GetFullName()
FString FGCObjectInfo::GetFullName () const
GetOuter()
FGCObjectInfo * FGCObjectInfo::GetOuter () const inline
Definition at line 75 of file GCObjectInfo.h.
References FGCObjectInfo(), and Outer.
GetOwnerIndex()
int32 FGCObjectInfo::GetOwnerIndex () const inline
Definition at line 117 of file GCObjectInfo.h.
References ClusterRootIndex.
Referenced by FGCObjectInfo().
GetPathName() [1/2]
FString FGCObjectInfo::GetPathName () const
GetPathName() [2/2]
void FGCObjectInfo::GetPathName (FStringBuilderBase & ResultString) const
GetRefCount()
int32 FGCObjectInfo::GetRefCount () const inline
Definition at line 128 of file GCObjectInfo.h.
References RefCount.
Referenced by FGCObjectInfo().
HasAnyFlags()
bool FGCObjectInfo::HasAnyFlags (EObjectFlags InFlags) const inline
Definition at line 92 of file GCObjectInfo.h.
References Flags.
HasAnyInternalFlags()
bool FGCObjectInfo::HasAnyInternalFlags (EInternalObjectFlags InFlags) const inline
Definition at line 97 of file GCObjectInfo.h.
References InternalFlags.
Referenced by IsGarbage(), IsNative(), IsRooted(), and IsValid().
IsDisregardForGC()
bool FGCObjectInfo::IsDisregardForGC () const inline
Definition at line 138 of file GCObjectInfo.h.
References bDisregardForGC.
Referenced by FGCObjectInfo().
IsGarbage()
bool FGCObjectInfo::IsGarbage () const inline
Definition at line 112 of file GCObjectInfo.h.
References Garbage, and HasAnyInternalFlags().
IsIn()
bool FGCObjectInfo::IsIn (const FGCObjectInfo * MaybeOuter) const inline
Definition at line 80 of file GCObjectInfo.h.
References FGCObjectInfo().
IsNative()
bool FGCObjectInfo::IsNative () const inline
Definition at line 107 of file GCObjectInfo.h.
References HasAnyInternalFlags(), and Native.
IsRooted()
bool FGCObjectInfo::IsRooted () const inline
Definition at line 102 of file GCObjectInfo.h.
References HasAnyInternalFlags(), and RootSet.
IsValid()
bool FGCObjectInfo::IsValid () const inline
Definition at line 133 of file GCObjectInfo.h.
References Garbage, and HasAnyInternalFlags().
TryResolveObject()
UObject * FGCObjectInfo::TryResolveObject ()
Tries to find an existing object matching the stored Path.
Returns
Pointer to an object this info struct represents if the object is still alive, nullptr otherwise
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FGCObjectInfo & Info) friend
Definition at line 147 of file GCObjectInfo.h.
References FGCObjectInfo(), GetTypeHash, HashCombine(), and Info.
Referenced by GetTypeHash.
Field Documentation
bDisregardForGC
bool FGCObjectInfo::bDisregardForGC = false private
True if the object was inside of the disregard for GC set.
Definition at line 58 of file GCObjectInfo.h.
Referenced by FGCObjectInfo(), and IsDisregardForGC().
Class
FGCObjectInfo* FGCObjectInfo::Class = nullptr private
Pointer to class info.
Definition at line 48 of file GCObjectInfo.h.
Referenced by GetClass(), and GetClassName().
ClusterRootIndex
int32 FGCObjectInfo::ClusterRootIndex = -1 private
Object's FGCObjectItem cluster root index.
Definition at line 56 of file GCObjectInfo.h.
Referenced by FGCObjectInfo(), and GetOwnerIndex().
Flags
EObjectFlags FGCObjectInfo::Flags = RF_NoFlags private
Captured Object flags.
Definition at line 52 of file GCObjectInfo.h.
Referenced by FGCObjectInfo(), and HasAnyFlags().
InternalFlags
EInternalObjectFlags FGCObjectInfo::InternalFlags = EInternalObjectFlags::None private
Captured Internal flags.
Definition at line 54 of file GCObjectInfo.h.
Referenced by FGCObjectInfo(), and HasAnyInternalFlags().
Name
FName FGCObjectInfo::Name private
Name of the object.
Definition at line 46 of file GCObjectInfo.h.
Referenced by FGCObjectInfo().
Outer
FGCObjectInfo* FGCObjectInfo::Outer = nullptr private
Pointer to Outer info.
Definition at line 50 of file GCObjectInfo.h.
Referenced by GetOuter().
RefCount
int32 FGCObjectInfo::RefCount = 0 private
Current ref-count of the UObject.
Definition at line 60 of file GCObjectInfo.h.
Referenced by FGCObjectInfo(), and GetRefCount().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/GCObjectInfo.h