Unreal Engine 5.6 C++ API: FHitProxyId Class Reference
FHitProxyId Class Reference
Encapsulates a hit proxy ID.
#include "HitProxies.h"
Public Member Functions
FHitProxyId ()
Default constructor.
FHitProxyId (FColor Color)
Color conversion constructor.
FColor GetColor () const
Maps the ID to a color which can be used to represent the ID.
Static Public Attributes
static const FHitProxyId InvisibleHitProxyId
A special hit proxy ID that can be used to omit rendering a primitive to the hit proxy buffer entirely.
Private Member Functions
FHitProxyId (int32 InIndex)
Initialization constructor.
Private Attributes
int32 Index
A uniquely identifying index for the hit proxy.
Friends
class HHitProxy * GetHitProxyById (FHitProxyId Id)
Maps a hit proxy ID to its hit proxy.
class HHitProxy
bool operator!= (FHitProxyId X, FHitProxyId Y)
bool operator== (FHitProxyId X, FHitProxyId Y)
Detailed Description
Encapsulates a hit proxy ID.
Definition at line 85 of file HitProxies.h.
Constructor & Destructor Documentation
FHitProxyId() [1/3]
FHitProxyId::FHitProxyId () inline
Default constructor.
Definition at line 95 of file HitProxies.h.
References Index, and INDEX_NONE.
Referenced by GetHitProxyById, operator!=, and operator==.
FHitProxyId() [2/3]
FHitProxyId::FHitProxyId (FColor Color)
Color conversion constructor.
References Color.
FHitProxyId() [3/3]
FHitProxyId::FHitProxyId (int32 InIndex) inline private
Initialization constructor.
Definition at line 125 of file HitProxies.h.
References Index.
Member Function Documentation
GetColor()
FColor FHitProxyId::GetColor () const
Maps the ID to a color which can be used to represent the ID.
Friends And Related Symbol Documentation
GetHitProxyById
class HHitProxy * GetHitProxyById (FHitProxyId Id) friend
Maps a hit proxy ID to its hit proxy.
If the ID doesn't map to a valid hit proxy, NULL is returned.
Parameters
ID - The hit proxy ID to match.
Returns
The hit proxy with matching ID, or NULL if no match.
References FHitProxyId(), and HHitProxy.
HHitProxy
friend class HHitProxy friend
Definition at line 87 of file HitProxies.h.
References HHitProxy.
Referenced by GetHitProxyById, and HHitProxy.
operator!=
bool operator!= (FHitProxyId X, FHitProxyId Y) friend
Definition at line 117 of file HitProxies.h.
References FHitProxyId(), X, and Y.
operator==
bool operator== (FHitProxyId X, FHitProxyId Y) friend
Definition at line 112 of file HitProxies.h.
References FHitProxyId(), X, and Y.
Field Documentation
Index
int32 FHitProxyId::Index private
A uniquely identifying index for the hit proxy.
Definition at line 128 of file HitProxies.h.
Referenced by FHitProxyId(), and FHitProxyId().
InvisibleHitProxyId
const FHitProxyId FHitProxyId::InvisibleHitProxyId static
A special hit proxy ID that can be used to omit rendering a primitive to the hit proxy buffer entirely.
This is useful when rendering translucent primitives that you never want to obscure selection of objects behind them
Definition at line 92 of file HitProxies.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/HitProxies.h