Unreal Engine 5.6 C++ API: FBulkDataRequest Class Reference
FBulkDataRequest Class Reference
Handle to a bulk data I/O request.
#include "BulkData.h"
Data Structures
class IHandle
Public Types
enum class EStatus : uint32 {
None , Pending , Ok , Cancelled ,
Error
}
Bulk data request status.
using FCompletionCallback = TFunction<void(EStatus)>
Completion callback.
Public Member Functions
FBulkDataRequest ()=default
Constructs a new handle to bulk data request.
FBulkDataRequest (const FBulkDataRequest &)=delete
Not copy constructable or copy assignable.
FBulkDataRequest (FBulkDataRequest &&)=default
Moves ownership from an invalid or pending request.
~FBulkDataRequest ()=default
Destructor, cancels and waits for any pending requests.
void Cancel ()
Cancel the pending request.
EStatus GetStatus () const
Returns current status of the request.
bool IsCompleted () const
Returns whether the request has been completed.
bool IsNone () const
Returns whether the request is associated with a pending or completed request.
bool IsOk () const
Returns whether the request completed successfully.
bool IsPending () const
Returns whether the request is pending.
FBulkDataRequest & operator= (const FBulkDataRequest &)=delete
FBulkDataRequest & operator= (FBulkDataRequest &&)=default
void Reset ()
Reset the request handle to an invalid state.
Static Public Attributes
static constexpr EAsyncIOPriorityAndFlags DefaultPriority = AIOP_BelowNormal
Default bulk data I/O request priority.
Protected Member Functions
FBulkDataRequest (FBulkDataRequest::IHandle *InHandle)
Protected Attributes
TRefCountPtr< IHandle > Handle
Friends
class FBulkDataBatchRequest
class FChunkBatchReadRequest
class FHandleBase
Detailed Description
Handle to a bulk data I/O request.
Definition at line 1192 of file BulkData.h.
Member Typedef Documentation
FCompletionCallback
using FBulkDataRequest::FCompletionCallback = TFunction<void(EStatus)>
Completion callback.
Definition at line 1228 of file BulkData.h.
Member Enumeration Documentation
EStatus
enum class FBulkDataRequest::EStatus : uint32 strong
Bulk data request status.
Enumerator
None
The request hasn't been issued.
Pending
The request is pending.
Ok
The request has been completed successfully.
Cancelled
The request was cancelled.
Error
An error occured while issuing the request.
Definition at line 1196 of file BulkData.h.
Constructor & Destructor Documentation
FBulkDataRequest() [1/4]
FBulkDataRequest::FBulkDataRequest () default
Constructs a new handle to bulk data request.
Referenced by FBulkDataRequest(), FBulkDataRequest(), operator=(), and operator=().
~FBulkDataRequest()
FBulkDataRequest::~FBulkDataRequest () default
Destructor, cancels and waits for any pending requests.
FBulkDataRequest() [2/4]
FBulkDataRequest::FBulkDataRequest (FBulkDataRequest &&) default
Moves ownership from an invalid or pending request.
References FBulkDataRequest().
FBulkDataRequest() [3/4]
FBulkDataRequest::FBulkDataRequest (const FBulkDataRequest &) delete
Not copy constructable or copy assignable.
References FBulkDataRequest().
FBulkDataRequest() [4/4]
FBulkDataRequest::FBulkDataRequest (FBulkDataRequest::IHandle * InHandle) inline protected
Definition at line 1273 of file BulkData.h.
References check, and Handle.
Member Function Documentation
Cancel()
void FBulkDataRequest::Cancel () inline
Cancel the pending request.
Cancelling an invalid request will immediately return.
Definition at line 1263 of file BulkData.h.
References Handle.
GetStatus()
EStatus FBulkDataRequest::GetStatus () const inline
Returns current status of the request.
Definition at line 1248 of file BulkData.h.
References Handle, and None.
Referenced by IsCompleted(), IsNone(), IsOk(), and IsPending().
IsCompleted()
bool FBulkDataRequest::IsCompleted () const inline
Returns whether the request has been completed.
Definition at line 1260 of file BulkData.h.
References GetStatus(), and Pending.
IsNone()
bool FBulkDataRequest::IsNone () const inline
Returns whether the request is associated with a pending or completed request.
Definition at line 1251 of file BulkData.h.
References GetStatus(), and None.
IsOk()
bool FBulkDataRequest::IsOk () const inline
Returns whether the request completed successfully.
Definition at line 1257 of file BulkData.h.
References GetStatus(), and Ok.
IsPending()
bool FBulkDataRequest::IsPending () const inline
Returns whether the request is pending.
Definition at line 1254 of file BulkData.h.
References GetStatus(), and Pending.
operator=() [1/2]
FBulkDataRequest & FBulkDataRequest::operator= (const FBulkDataRequest &) delete
References FBulkDataRequest().
operator=() [2/2]
FBulkDataRequest & FBulkDataRequest::operator= (FBulkDataRequest &&) default
References FBulkDataRequest().
Reset()
void FBulkDataRequest::Reset () inline
Reset the request handle to an invalid state.
Will cancel and wait if the request is not completed.
Definition at line 1266 of file BulkData.h.
References Handle.
Friends And Related Symbol Documentation
FBulkDataBatchRequest
friend class FBulkDataBatchRequest friend
Definition at line 1271 of file BulkData.h.
References FBulkDataBatchRequest.
Referenced by FBulkDataBatchRequest, FBulkDataBatchRequest::FBatchBuilder::Issue(), FBulkDataBatchRequest::FBatchBuilder::Issue(), FBulkDataBatchRequest::FScatterGatherBuilder::Issue(), and FBulkDataBatchRequest::FBuilder::IssueBatch().
FChunkBatchReadRequest
friend class FChunkBatchReadRequest friend
Definition at line 1270 of file BulkData.h.
References FChunkBatchReadRequest.
Referenced by FChunkBatchReadRequest.
FHandleBase
friend class FHandleBase friend
Definition at line 1269 of file BulkData.h.
References FHandleBase.
Referenced by FHandleBase.
Field Documentation
DefaultPriority
EAsyncIOPriorityAndFlags FBulkDataRequest::DefaultPriority = AIOP_BelowNormal static constexpr
Default bulk data I/O request priority.
Definition at line 1231 of file BulkData.h.
Referenced by FBulkDataBatchRequest::FBatchBuilder::Read().
Handle
TRefCountPtr<IHandle> FBulkDataRequest::Handle protected
Definition at line 1279 of file BulkData.h.
Referenced by FBulkDataRequest(), Cancel(), GetStatus(), and Reset().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/BulkData.h