Unreal Engine 5.6 C++ API: TConsoleVariableData< T > Class Template Reference
TConsoleVariableData< T > Class Template Reference
#include "IConsoleManager.h"
Public Member Functions
TConsoleVariableData (const T DefaultValue)
T GetValueOnAnyThread (bool bForceGameThread=false) const
T GetValueOnGameThread () const
T GetValueOnRenderThread () const
Private Member Functions
T & GetReferenceOnAnyThread (bool bForceGameThread=false)
Static Private Member Functions
static uint32 GetShadowIndex (bool bForceGameThread=false)
Private Attributes
T ShadowedValue [2]
Friends
template<class T2>
class FConsoleVariable
template<class T2>
class TAutoConsoleVariable
Detailed Description
template<class T>
class TConsoleVariableData< T >
Definition at line 1682 of file IConsoleManager.h.
Constructor & Destructor Documentation
TConsoleVariableData()
template<class T> TConsoleVariableData< T >::TConsoleVariableData (const T DefaultValue) inline
Definition at line 1686 of file IConsoleManager.h.
References ShadowedValue, and UE_ARRAY_COUNT.
Member Function Documentation
GetReferenceOnAnyThread()
template<class T> T & TConsoleVariableData< T >::GetReferenceOnAnyThread (bool bForceGameThread = false) inline private
Definition at line 1738 of file IConsoleManager.h.
References UE::AccessDetection::CVar, GetShadowIndex(), UE::AccessDetection::ReportAccess(), and ShadowedValue.
GetShadowIndex()
template<class T> uint32 TConsoleVariableData< T >::GetShadowIndex (bool bForceGameThread = false) inline static private
Definition at line 1727 of file IConsoleManager.h.
References cvarCheckCode, ensure, IsInActualRenderingThread(), IsInGameThread(), and IsInParallelGameThread().
Referenced by GetReferenceOnAnyThread(), GetValueOnAnyThread(), and GetValueOnGameThread().
GetValueOnAnyThread()
template<class T> T TConsoleVariableData< T >::GetValueOnAnyThread (bool bForceGameThread = false) const inline
Definition at line 1715 of file IConsoleManager.h.
References UE::AccessDetection::CVar, GetShadowIndex(), UE::AccessDetection::ReportAccess(), and ShadowedValue.
Referenced by FMaterial::FMaterial(), Nanite::FNaniteResourcesHelper::AuditMaterials(), and FPrimitiveUniformShaderParametersBuilder::Build().
GetValueOnGameThread()
template<class T> T TConsoleVariableData< T >::GetValueOnGameThread () const inline
Definition at line 1695 of file IConsoleManager.h.
References UE::AccessDetection::CVar, cvarCheckCode, ensure, GetShadowIndex(), UE::AccessDetection::ReportAccess(), and ShadowedValue.
GetValueOnRenderThread()
template<class T> T TConsoleVariableData< T >::GetValueOnRenderThread () const inline
Definition at line 1704 of file IConsoleManager.h.
References UE::AccessDetection::CVar, cvarCheckCode, ensure, IsInParallelRenderingThread(), UE::AccessDetection::ReportAccess(), and ShadowedValue.
Friends And Related Symbol Documentation
FConsoleVariable
template<class T> template<class T2> friend class FConsoleVariable friend
Definition at line 1744 of file IConsoleManager.h.
References FConsoleVariable.
Referenced by FConsoleVariable.
TAutoConsoleVariable
template<class T> template<class T2> friend class TAutoConsoleVariable friend
Definition at line 1745 of file IConsoleManager.h.
References TAutoConsoleVariable.
Referenced by TAutoConsoleVariable.
Field Documentation
ShadowedValue
template<class T> T TConsoleVariableData< T >::ShadowedValue[2] private
Definition at line 1724 of file IConsoleManager.h.
Referenced by TConsoleVariableData(), GetReferenceOnAnyThread(), GetValueOnAnyThread(), GetValueOnGameThread(), and GetValueOnRenderThread().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h