Unreal Engine 5.6 C++ API: FInternetAddrDemo Class Reference
FInternetAddrDemo Class Reference
#include "ReplayTypes.h"
Public Member Functions
FInternetAddrDemo ()
virtual TSharedRef< FInternetAddr > Clone () const override
uint32 GetConstTypeHash () const
void GetIp (uint32 &OutAddr) const override
int32 GetPort () const override
void GetPort (int32 &OutPort) const override
virtual TArray< uint8 > GetRawIp () const override
virtual uint32 GetTypeHash () const override
virtual bool IsValid () const override
bool operator!= (const FInternetAddrDemo &Other) const
virtual bool operator== (const FInternetAddr &Other) const override
void SetAnyAddress () override
void SetBroadcastAddress () override
void SetIp (const TCHAR *InAddr, bool &bIsValid) override
void SetIp (uint32 InAddr) override
void SetLoopbackAddress () override
void SetPort (int32 InPort) override
virtual void SetRawIp (const TArray< uint8 > &RawAddr) override
FString ToString (bool bAppendPort) const override
Static Public Attributes
static TSharedPtr< FInternetAddr > DemoInternetAddr
Friends
uint32 GetTypeHash (const FInternetAddrDemo &A)
Detailed Description
Definition at line 302 of file ReplayTypes.h.
Constructor & Destructor Documentation
FInternetAddrDemo()
FInternetAddrDemo::FInternetAddrDemo () inline
Definition at line 306 of file ReplayTypes.h.
Referenced by GetTypeHash, and operator!=().
Member Function Documentation
Clone()
virtual TSharedRef< FInternetAddr > FInternetAddrDemo::Clone () const inline override virtual
Definition at line 396 of file ReplayTypes.h.
References DemoInternetAddr.
GetConstTypeHash()
uint32 FInternetAddrDemo::GetConstTypeHash () const inline
Definition at line 381 of file ReplayTypes.h.
References GetTypeHashHelper(), and ToString().
Referenced by GetTypeHash().
GetIp()
void FInternetAddrDemo::GetIp (uint32 & OutAddr) const inline override
Definition at line 328 of file ReplayTypes.h.
GetPort() [1/2]
int32 FInternetAddrDemo::GetPort () const inline override
Definition at line 344 of file ReplayTypes.h.
GetPort() [2/2]
void FInternetAddrDemo::GetPort (int32 & OutPort) const inline override
Definition at line 338 of file ReplayTypes.h.
GetRawIp()
virtual TArray< uint8 > FInternetAddrDemo::GetRawIp () const inline override virtual
Definition at line 310 of file ReplayTypes.h.
GetTypeHash()
virtual uint32 FInternetAddrDemo::GetTypeHash () const inline override virtual
Definition at line 376 of file ReplayTypes.h.
References GetConstTypeHash().
IsValid()
virtual bool FInternetAddrDemo::IsValid () const inline override virtual
Definition at line 391 of file ReplayTypes.h.
operator!=()
bool FInternetAddrDemo::operator!= (const FInternetAddrDemo & Other) const inline
Definition at line 371 of file ReplayTypes.h.
References FInternetAddrDemo(), operator==(), and Other.
operator==()
virtual bool FInternetAddrDemo::operator== (const FInternetAddr & Other) const inline override virtual
Definition at line 366 of file ReplayTypes.h.
References Other, and ToString().
Referenced by operator!=().
SetAnyAddress()
void FInternetAddrDemo::SetAnyAddress () inline override
Definition at line 349 of file ReplayTypes.h.
SetBroadcastAddress()
void FInternetAddrDemo::SetBroadcastAddress () inline override
Definition at line 353 of file ReplayTypes.h.
SetIp() [1/2]
void FInternetAddrDemo::SetIp (const TCHAR * InAddr, bool & bIsValid) inline override
Definition at line 324 of file ReplayTypes.h.
SetIp() [2/2]
void FInternetAddrDemo::SetIp (uint32 InAddr) inline override
Definition at line 319 of file ReplayTypes.h.
SetLoopbackAddress()
void FInternetAddrDemo::SetLoopbackAddress () inline override
Definition at line 357 of file ReplayTypes.h.
SetPort()
void FInternetAddrDemo::SetPort (int32 InPort) inline override
Definition at line 333 of file ReplayTypes.h.
SetRawIp()
virtual void FInternetAddrDemo::SetRawIp (const TArray< uint8 > & RawAddr) inline override virtual
Definition at line 315 of file ReplayTypes.h.
ToString()
FString FInternetAddrDemo::ToString (bool bAppendPort) const inline override
Definition at line 361 of file ReplayTypes.h.
References TEXT.
Referenced by GetConstTypeHash(), and operator==().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FInternetAddrDemo & A) friend
Definition at line 386 of file ReplayTypes.h.
References FInternetAddrDemo(), and A.
Field Documentation
DemoInternetAddr
TSharedPtr<FInternetAddr> FInternetAddrDemo::DemoInternetAddr static
Definition at line 401 of file ReplayTypes.h.
Referenced by Clone().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ReplayTypes.h