Unreal Engine 5.6 C++ API: UKismetInputLibrary Class Reference
UKismetInputLibrary Class Reference
#include "KismetInputLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION() static 1 void CalibrateTilt()
Calibrate the tilt for the input device.
UFUNCTION ()
Returns true if the key is a modifier key: Ctrl, Command, Alt, Shift.
UFUNCTION ()
Returns true if the key is a gamepad button.
UFUNCTION ()
Returns true if the key is a mouse button.
UFUNCTION ()
Returns true if the key is a keyboard button.
UFUNCTION ()
Returns true if the key is a 1D (float) axis.
UFUNCTION ()
Returns true if the key is a 2D (vector) axis.
UFUNCTION ()
Returns true if the key is a 3D (vector) axis.
UFUNCTION ()
Returns true if the key is a 1D axis emulating a digital button press.
UFUNCTION ()
Returns true if the key is an analog axis.
UFUNCTION ()
Returns true if the key is a digital button press.
UFUNCTION ()
Returns true if this is a valid key.
UFUNCTION ()
UFUNCTION ()
Returns the navigation action corresponding to this key, or Invalid if not found.
UFUNCTION ()
Returns the navigation action corresponding to this key, or Invalid if not found.
UFUNCTION ()
Returns the navigation action corresponding to this key, or Invalid if not found.
UFUNCTION ()
Returns the display name of the key.
UFUNCTION ()
Returns whether or not this character is an auto-repeated keystroke.
UFUNCTION ()
Returns true if either shift key was down when this event occurred.
UFUNCTION ()
Returns true if left shift key was down when this event occurred.
UFUNCTION ()
Returns true if right shift key was down when this event occurred.
UFUNCTION ()
Returns true if either control key was down when this event occurred.
UFUNCTION ()
Returns true if left control key was down when this event occurred.
UFUNCTION ()
Returns true if left control key was down when this event occurred.
UFUNCTION ()
Returns true if either alt key was down when this event occurred.
UFUNCTION ()
Returns true if left alt key was down when this event occurred.
UFUNCTION ()
Returns true if right alt key was down when this event occurred.
UFUNCTION ()
Returns true if either command key was down when this event occurred.
UFUNCTION ()
Returns true if left command key was down when this event occurred.
UFUNCTION ()
Returns true if right command key was down when this event occurred.
UFUNCTION ()
Returns true if either shift key was down when the key state was captured.
UFUNCTION ()
Returns true if either control key was down when the key state was captured.
UFUNCTION ()
Returns true if either alt key was down when the key state was captured.
UFUNCTION ()
Returns true if either command key was down when the key state was captured.
UFUNCTION ()
UFUNCTION ()
Returns The position of the cursor in screen space.
UFUNCTION ()
Returns the position of the cursor in screen space last time we handled an input event.
UFUNCTION ()
Returns the distance the mouse traveled since the last event was handled.
UFUNCTION ()
Mouse buttons that are currently pressed.
UFUNCTION ()
Mouse button that caused this event to be raised (possibly FKey::Invalid)
UFUNCTION ()
How much did the mouse wheel turn since the last mouse event.
UFUNCTION ()
Returns the index of the user that caused the event.
UFUNCTION ()
Returns the unique identifier of the pointer (e.g., finger index)
UFUNCTION ()
Returns the index of the touch pad that generated this event (for platforms with multiple touch pads per user)
UFUNCTION ()
Returns true if this event a result from a touch (as opposed to a mouse)
UFUNCTION ()
Returns the change in gesture value since the last gesture event of the same type.
UFUNCTION () "
Test if the input key are equal (A == B)
UFUNCTION () "
Test if the input chords are equal (A == B)
UFUNCTION () static 1 ESlateGesture PointerEvent_GetGestureType(const FPointerEvent &Input)
Returns the type of touch gesture.
UFUNCTION () static 1 FKey GetKey(const FKeyEvent &Input)
Returns the key for this event.
UFUNCTION () static 1 float GetAnalogValue(const FAnalogInputEvent &Input)
UFUNCTION () static 1 FSlateModifierKeysState GetModifierKeysState()
Returns a snapshot of the cached modifier-keys state for the application.
UFUNCTION () static 1 int32 GetUserIndex(const FKeyEvent &Input)
Private Attributes
Category
CompactNodeTitle
Detailed Description
Definition at line 40 of file KismetInputLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UKismetInputLibrary::GENERATED_UCLASS_BODY () private
Calibrate the tilt for the input device.
References Category, and UFUNCTION().
UFUNCTION() [1/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a modifier key: Ctrl, Command, Alt, Shift.
UFUNCTION() [2/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a gamepad button.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [3/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a mouse button.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [4/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a keyboard button.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [5/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a 1D (float) axis.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [6/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a 2D (vector) axis.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [7/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a 3D (vector) axis.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [8/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a 1D axis emulating a digital button press.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [9/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is an analog axis.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [10/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if the key is a digital button press.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [11/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if this is a valid key.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [12/52]
UKismetInputLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
UFUNCTION() [13/52]
UKismetInputLibrary::UFUNCTION () private
Returns the navigation action corresponding to this key, or Invalid if not found.
References Category, meta, and UFUNCTION().
UFUNCTION() [14/52]
UKismetInputLibrary::UFUNCTION () private
Returns the navigation action corresponding to this key, or Invalid if not found.
References Category, meta, and UFUNCTION().
UFUNCTION() [15/52]
UKismetInputLibrary::UFUNCTION () private
Returns the navigation action corresponding to this key, or Invalid if not found.
References Category, meta, and UFUNCTION().
UFUNCTION() [16/52]
UKismetInputLibrary::UFUNCTION () private
Returns the display name of the key.
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [17/52]
UKismetInputLibrary::UFUNCTION () private
Returns whether or not this character is an auto-repeated keystroke.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [18/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either shift key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [19/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if left shift key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [20/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if right shift key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [21/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either control key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [22/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if left control key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [23/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if left control key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [24/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either alt key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [25/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if left alt key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [26/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if right alt key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [27/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either command key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [28/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if left command key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [29/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if right command key was down when this event occurred.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [30/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either shift key was down when the key state was captured.
References Category, meta, and UFUNCTION().
UFUNCTION() [31/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either control key was down when the key state was captured.
References Category, meta, and UFUNCTION().
UFUNCTION() [32/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either alt key was down when the key state was captured.
References Category, meta, and UFUNCTION().
UFUNCTION() [33/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if either command key was down when the key state was captured.
References Category, meta, and UFUNCTION().
UFUNCTION() [34/52]
UKismetInputLibrary::UFUNCTION () private
Returns
The display name of the input chord
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [35/52]
UKismetInputLibrary::UFUNCTION () private
Returns The position of the cursor in screen space.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [36/52]
UKismetInputLibrary::UFUNCTION () private
Returns the position of the cursor in screen space last time we handled an input event.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [37/52]
UKismetInputLibrary::UFUNCTION () private
Returns the distance the mouse traveled since the last event was handled.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [38/52]
UKismetInputLibrary::UFUNCTION () private
Mouse buttons that are currently pressed.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [39/52]
UKismetInputLibrary::UFUNCTION () private
Mouse button that caused this event to be raised (possibly FKey::Invalid)
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [40/52]
UKismetInputLibrary::UFUNCTION () private
How much did the mouse wheel turn since the last mouse event.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [41/52]
UKismetInputLibrary::UFUNCTION () private
Returns the index of the user that caused the event.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [42/52]
UKismetInputLibrary::UFUNCTION () private
Returns the unique identifier of the pointer (e.g., finger index)
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [43/52]
UKismetInputLibrary::UFUNCTION () private
Returns the index of the touch pad that generated this event (for platforms with multiple touch pads per user)
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [44/52]
UKismetInputLibrary::UFUNCTION () private
Returns true if this event a result from a touch (as opposed to a mouse)
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [45/52]
UKismetInputLibrary::UFUNCTION () private
Returns the change in gesture value since the last gesture event of the same type.
References Category, Input, meta, and UFUNCTION().
UFUNCTION() [46/52]
UKismetInputLibrary::UFUNCTION () private
Test if the input key are equal (A == B)
Parameters
A - The key to compare against
B - The key to compare Returns true if the key are equal, false otherwise
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [47/52]
UKismetInputLibrary::UFUNCTION () private
Test if the input chords are equal (A == B)
Parameters
A - The chord to compare against
B - The chord to compare Returns true if the chords are equal, false otherwise
References A, B, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [48/52]
UKismetInputLibrary::UFUNCTION () const & private
Returns the type of touch gesture.
References Category, Input, and UFUNCTION().
UFUNCTION() [49/52]
UKismetInputLibrary::UFUNCTION () const & private
Returns the key for this event.
Returns
Key name
References Category, Input, and UFUNCTION().
UFUNCTION() [50/52]
UKismetInputLibrary::UFUNCTION () const & private
References Category, Input, and UFUNCTION().
UFUNCTION() [51/52]
UKismetInputLibrary::UFUNCTION () private
Returns a snapshot of the cached modifier-keys state for the application.
References Category, and UFUNCTION().
UFUNCTION() [52/52]
UKismetInputLibrary::UFUNCTION () const & private
References Category, Input, and UFUNCTION().
Field Documentation
Category
UKismetInputLibrary::Category private
Initial value:
="Input|Key")
    static 1 bool Key_IsModifierKey(const FKey& Key)
Definition at line 69 of file KismetInputLibrary.h.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
CompactNodeTitle
UKismetInputLibrary::CompactNodeTitle private
Initial value:
= "=="), Category="Input|Key")
    static 1 bool EqualEqual_KeyKey(FKey A, FKey B)
Definition at line 54 of file KismetInputLibrary.h.
Referenced by UFUNCTION().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/KismetInputLibrary.h