Unreal Engine 5.6 C++ API: UStaticMeshComponent Class Reference
UStaticMeshComponent Class Reference abstract
#include "StaticMeshComponent.h"
Public Member Functions
virtual ~UStaticMeshComponent ()
virtual UObject const * AdditionalStatObject () const override
virtual void AddMapBuildDataGUIDs (TSet< FGuid > &InGUIDs) const override
virtual FStaticMeshStaticLightingMesh * AllocateStaticLightingMesh (int32 LODIndex, const TArray< ULightComponent * > &InRelevantLights)
Allocates an implementation of FStaticLightingMesh that will handle static lighting for this component.
virtual bool AllowsAsyncPhysicsStateCreation () const override
virtual bool AllowsAsyncPhysicsStateDestruction () const override
void ApplyComponentInstanceData (struct FStaticMeshComponentInstanceData *ComponentInstanceData)
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const override
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
virtual void BeginDestroy () override
virtual void BeginPlay () override
virtual bool BuildTextureStreamingDataImpl (ETextureStreamingBuildType BuildType, EMaterialQualityLevel::Type QualityLevel, ERHIFeatureLevel::Type FeatureLevel, TSet< FGuid > &DependentResources, bool &bOutSupportsBuildTextureStreamingData) override
Build the data to compute accuracte StreaminTexture data.
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual bool CanEditSimulatePhysics () override
bool CanMeshPaintTextureColors () const
bool CanMeshPaintVertexColors () const
virtual void CheckForErrors () override
virtual bool ComponentIsTouchingSelectionBox (const FBox &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual bool ComponentIsTouchingSelectionFrustum (const FConvexVolume &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual uint32 ComputeHashTextureStreamingBuiltData () const override
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const override
virtual HHitProxy * CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex) const override
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
DECLARE_DELEGATE_RetVal (const Nanite::FResources *, FOnGetNaniteResources)
Called during scene proxy creation to get the Nanite resource data.
DECLARE_EVENT_OneParam (UStaticMeshComponent, FOnStaticMeshChanged, UStaticMeshComponent *)
Called when the static mesh changes.
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual bool DoesSocketExist (FName InSocketName) const override
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent) override
int32 GetBlueprintCreatedComponentIndex () const
Get this components index in its parents blueprint created components array (used for matching instance data)
virtual class UBodySetup * GetBodySetup () override
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const override
Get all default LOD sections overlay materials used by a mesh.
virtual FString GetDetailedInfoInternal () const override
virtual float GetDiffuseBoost (int32 ElementIndex) const override
virtual UMaterialInterface * GetEditorMaterial (int32 MaterialIndex) const override
virtual float GetEmissiveBoost (int32 ElementIndex) const override
virtual bool GetEstimatedLightAndShadowMapMemoryUsage (int32 &TextureLightMapMemoryUsage, int32 &TextureShadowMapMemoryUsage, int32 &VertexLightMapMemoryUsage, int32 &VertexShadowMapMemoryUsage, int32 &StaticLightingResolution, bool &bIsUsingTextureMapping, bool &bHasLightmapTexCoords) const
Returns the light and shadow map memory for this primite in its out variables.
virtual void GetEstimatedLightMapResolution (int32 &Width, int32 &Height) const
Returns the lightmap resolution used for this primitive instance in the case of it supporting texture light/ shadow maps.
FORCEINLINE int32 GetForcedLodModel () const
FORCEINLINE bool GetForceNaniteForMasked () const
virtual void GetLightAndShadowMapMemoryUsage (int32 &LightMapMemoryUsage, int32 &ShadowMapMemoryUsage) const override
virtual bool GetLightMapResolution (int32 &Width, int32 &Height) const override
virtual UMaterialInterface * GetMaterial (int32 MaterialIndex) const final
virtual UMaterialInterface * GetMaterialFromCollisionFaceIndex (int32 FaceIndex, int32 &SectionIndex) const override
virtual int32 GetMaterialIndex (FName MaterialSlotName) const override
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual TArray< FName > GetMaterialSlotNames () const override
virtual bool GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo &MaterialData) const override
Get material, UV density and bounds for a given material index.
const FMeshMapBuildData * GetMeshMapBuildData (const FStaticMeshComponentLODInfo &LODInfo, bool bCheckForResourceCluster=true) const
virtual UTexture * GetMeshPaintTexture () const override
Get the mesh paint texture set on this component.
virtual int32 GetMeshPaintTextureCoordinateIndex () const override
Get the default coordinate index for painting to the mesh paint texture on this component.
int32 GetMeshPaintTextureResolution () const
Returns the size to use when creating a mesh paint texture on this component.
FORCEINLINE int32 GetMinLOD () const
UMaterialInterface * GetNaniteAuditMaterial (int32 MaterialIndex) const
virtual const Nanite::FResources * GetNaniteResources () const
virtual FBox GetNavigationBounds () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
virtual int32 GetNumMaterials () const override
FORCEINLINE bool GetOverrideMinLOD () const
virtual void GetPrimitiveStats (FPrimitiveStats &PrimitiveStats) const override
virtual bool GetShadowIndirectOnly () const override
class UStaticMeshSocket const * GetSocketByName (FName InSocketName) const
Returns the named socket on the static mesh component.
virtual FTransform GetSocketTransform (FName InSocketName, ERelativeTransformSpace TransformSpace=RTS_World) const override
virtual void GetStaticLightingInfo (FStaticLightingPrimitiveInfo &OutPrimitiveInfo, const TArray< ULightComponent * > &InRelevantLights, const FLightingBuildOptions &Options) override
virtual ELightMapInteractionType GetStaticLightingType () const override
virtual int32 GetStaticLightMapResolution () const override
TObjectPtr< UStaticMesh > GetStaticMesh () const
Get the StaticMesh used by this instance.
virtual void GetStreamingRenderAssetInfo (FStreamingTextureLevelContext &LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamingRenderAssets) const override
Get the StreaminTexture data.
virtual float GetStreamingScale () const override
virtual void GetTextureLightAndShadowMapMemoryUsage (int32 InWidth, int32 InHeight, int32 &OutLightMapMemoryUsage, int32 &OutShadowMapMemoryUsage) const
Get the memory used for texture-based light and shadow maps of the given width and height.
virtual float GetTextureStreamingTransformScale () const
Get the scale comming form the component, when computing StreamingTexture data.
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const final
virtual void GetUsedTextures (TArray< UTexture * > &OutTextures, EMaterialQualityLevel::Type QualityLevel) override
FColor GetWireframeColor () const
Returns the wireframe color to use for this component.
virtual bool HasAnySockets () const override
virtual bool HasLightmapTextureCoordinates () const
Returns true if the static mesh the component uses has valid lightmap texture coordinates.
virtual bool HasValidNaniteData () const
Returns true if the component has valid Nanite render data.
virtual bool HasValidSettingsForStaticLighting (bool bOverlookInvalidComponents) const override
Returns true if the component is static AND has the right static mesh setup to support lightmaps.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn) override
virtual void InitializeComponent () override
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly) override
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
virtual bool IsCompiling () const override
FORCEINLINE bool IsDisallowNanite () const
FORCEINLINE bool IsForceDisableNanite () const
FORCEINLINE bool IsForceNaniteForMasked () const
virtual bool IsHLODRelevant () const override
virtual bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
virtual bool IsNavigationRelevant () const override
virtual bool IsPostLoadThreadSafe () const override
virtual bool IsPrecomputedLightingValid () const override
FORCEINLINE bool IsReverseCulling () const
virtual bool IsShown (const FEngineShowFlags &ShowFlags) const override
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
virtual void OnCreatePhysicsState () override
virtual void OnDestroyPhysicsState () override
virtual FOnGetNaniteResources & OnGetNaniteResources ()
virtual const FOnGetNaniteResources & OnGetNaniteResources () const
void OnMeshRebuild (bool bRenderDataChanged)
virtual FOnStaticMeshChanged & OnStaticMeshChanged ()
virtual UE_DECLARE_COMPONENT_ACTOR_INTERFACE(StaticMeshComponent) protected void OnUnregister () override
virtual void PostApplyToComponent () override
virtual void PostDuplicate (bool bDuplicateForPIE) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostEditImport () override
virtual void PostEditUndo () override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PostReinitProperties () override
virtual void PostStaticMeshCompilation ()
virtual void PrecachePSOs () override
virtual void PreEditUndo () override
virtual void PreStaticMeshCompilation ()
virtual bool PrestreamMeshLODs (float Seconds) override
virtual void PropagateLightingScenarioChange () override
virtual void QuerySupportedSockets (TArray< FComponentSocketDescription > &OutSockets) const override
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn) override
Register a one-time callback that will be called when criteria met.
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&CallbackStreamingStart, FLODStreamingCallback &&CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs) override
Register a one-time callback that will be called when streaming starts or ends.
void ReleaseResources ()
virtual bool RemapActorTextureStreamingBuiltDataToLevel (const class UActorTextureStreamingBuildDataComponent *InActorTextureBuildData) override
void RemoveInstanceVertexColorsFromLOD (int32 LODToRemoveColorsFrom)
Removes instance vertex colors from the specified LOD.
virtual bool RequiresGameThreadEndOfFrameRecreate () const override
virtual void Serialize (FArchive &Ar) override
virtual void SetCollisionProfileName (FName InCollisionProfileName, bool bUpdateOverlaps=true) override
bool SetLODDataCount (const uint32 MinSize, const uint32 MaxSize)
Add or remove elements to have the size in the specified range.
virtual void SetMeshPaintTexture (UTexture *Texture) override
Set the mesh paint texture on this component.
virtual void SetMeshPaintTextureOverride (UTexture *OverrideTexture) override
Set a transient override mesh paint texture on this component.
virtual bool SetStaticLightingMapping (bool bTextureMapping, int32 ResolutionToUse)
Switches the static mesh component to use either Texture or Vertex static lighting.
virtual bool ShouldCollideWhenPlacing () const override
virtual bool ShouldCreatePhysicsState () const override
virtual bool ShouldCreateRenderState () const override
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const override
virtual bool ShouldRecreateProxyOnUpdateTransform () const override
virtual bool ShouldRenderSelected () const override
virtual bool SupportsDefaultCollision ()
Whether or not the component supports default collision from its static mesh asset.
virtual bool SupportsDitheredLODTransitions (ERHIFeatureLevel::Type FeatureLevel)
Whether we can support dithered LOD transitions (default behavior checks all materials).
virtual bool SupportsWorldPositionOffsetVelocity () const override
UE_DEPRECATED (5.6, "Use UPrimitiveComponent::IsFirstPersonRelevant() instead.") bool IsStaticMeshFirstPersonRelevant() const
UFUNCTION () 1 virtual bool SetStaticMesh(class UStaticMesh *NewMesh)
Change the StaticMesh used by this instance.
UFUNCTION () 1 void GetLocalBounds(FVector &Min
Get Local bounds.
UFUNCTION () 1 void OnRep_StaticMesh(class UStaticMesh *OldStaticMesh)
UFUNCTION () 1 void SetDistanceFieldSelfShadowBias(float NewValue)
Sets the component's DistanceFieldSelfShadowBias.
UFUNCTION () 1 void SetEvaluateWorldPositionOffset(bool NewValue)
UFUNCTION () 1 void SetEvaluateWorldPositionOffsetInRayTracing(bool NewValue)
UFUNCTION () 1 void SetForceDisableNanite(bool bInForceDisableNanite)
Force disabling of Nanite rendering.
UFUNCTION () 1 void SetForcedLodModel(int32 NewForcedLodModel)
UFUNCTION () 1 void SetReverseCulling(bool ReverseCulling)
Set forced reverse culling.
UFUNCTION () 1 void SetWorldPositionOffsetDisableDistance(int32 NewValue)
UFUNCTION () bool GetInitialEvaluateWorldPositionOffset()
Get the initial value of bEvaluateWorldPositionOffset.
UFUNCTION () void UpdateInitialEvaluateWorldPositionOffset()
This manually updates the initial value of bEvaluateWorldPositionOffset to be the current value.
virtual void UpdateBounds () override
void UpdateCollisionFromStaticMesh ()
Sets the BodyInstance to use the mesh's body setup for external collision information.
void UpdateMapBuildDataId ()
void UpdateStaticLightingData ()
UPROPERTY () float DistanceFieldSelfShadowBias
Useful for reducing self shadowing from distance field methods when using world position offset to animate the mesh's vertices.
UPROPERTY () float NanitePixelProgrammableDistance
Used to forcefully disable pixel programmable rasterization of Nanite when the mesh is further than a given distance from the camera.
UPROPERTY () int32 WorldPositionOffsetDisableDistance=0
Distance at which to disable World Position Offset for an entire instance (0 = Never disable WPO).
UPROPERTY () struct FLightmassPrimitiveSettings LightmassSettings
The Lightmass settings for this object.
UPROPERTY () TArray< FStreamingTextureBuildInfo > StreamingTextureData
The list of texture, bounds and scales.
UPROPERTY () TArray< struct FStaticMeshComponentLODInfo > LODData
Static mesh LOD data.
UPROPERTY () TObjectPtr< UTexture > MaterialCacheTexture
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureCooked
Cooked pointer to texture containing mesh painting for this mesh component.
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureOverride
Set this to override the locally stored mesh paint texture.
UPROPERTY ()) float DistanceFieldIndirectShadowMinVisibility
Controls how dark the dynamic indirect shadow can be.
UPROPERTY ()) float StreamingDistanceMultiplier
Allows adjusting the desired streaming distance of streaming textures that uses UV 0.
UPROPERTY ()) int32 OverriddenLightMapRes
Light map resolution to use on this component, used if bOverrideLightMapRes is true and there is a valid StaticMesh.
UPROPERTY()) uint8 bOverrideWireframeColor UPROPERTY() uint8 bOverrideMinLOD UPROPERTY() uint8 bOverrideNavigationExport UPROPERTY() uint8 bForceNavigationObstacle UPROPERTY() uint8 bDisallowMeshPaintPerInstance_DEPRECATED UPROPERTY() uint8 bIgnoreInstanceForTextureStreaming UPROPERTY()) uint8 bOverrideLightMapRes UPROPERTY()) uint8 bCastDistanceFieldIndirectShadow UPROPERTY() uint8 bOverrideDistanceFieldSelfShadowBias UPROPERTY() uint8 bUseSubDivisions UPROPERTY() uint8 bUseDefaultCollision UPROPERTY()) uint8 bSortTriangles UPROPERTY() uint8 bReverseCulling UPROPERTY() uint8 bEnableVertexColorMeshPainting UPROPERTY() uint8 bEnableTextureColorMeshPainting UPROPERTY()) uint8 bOverrideMeshPaintTextureCoordinateIndex UPROPERTY()) uint8 bOverrideMeshPaintTextureResolution UPROPERTY ()) int32 OverriddenMeshPaintTextureCoordinateIndex
If true, WireframeColorOverride will be used.
UPROPERTY ()) int32 OverriddenMeshPaintTextureResolution
The overriden resolution of texture color mesh paint textures on this component.
virtual bool UseNaniteOverrideMaterials () const override
Determines if we use the nanite overrides from any materials.
virtual bool UsesOnlyUnlitMaterials () const override
virtual bool UsesTextureLightmaps (int32 InWidth, int32 InHeight) const
Returns true if the component uses texture lightmaps.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Static Public Member Functions
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static const FName GetMemberNameChecked_StaticMesh ()
Helper function to get the FName of the private static mesh member.
Data Fields
FVector &Max const
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Types
using GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)>
Shared implementation for all StaticMesh derived components.
Protected Member Functions
virtual void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
Collect all the PSO precache data used by the static mesh component.
void CollectPSOPrecacheDataImpl (const FVertexFactoryType *VFType, const FPSOPrecacheParams &BasePrecachePSOParams, GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList &OutParams) const
virtual FPrimitiveSceneProxy * CreateStaticMeshSceneProxy (Nanite::FMaterialAudit &NaniteMaterials, bool bCreateNanite)
bool ShouldCreateNaniteProxy (Nanite::FMaterialAudit *OutNaniteMaterials=nullptr) const
bool ShouldExportAsObstacle (const UNavCollisionBase &InNavCollision) const
virtual bool SupportsStaticLighting () const override
Whether the component type supports static lighting.
Protected Member Functions inherited from UMeshComponent
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
uint8 bInitialEvaluateWorldPositionOffset: 1
Forces this component to always use Nanite for masked materials, even if FNaniteSettings::bAllowMaskedMaterials=false.
uint8 bMipLevelCallbackRegistered: 1
Whether mip callbacks have been registered and need to be removed on destroy.
uint8 bPrecachedPSOs: 1
Whether PrecachedPSOs was called.
uint8 bSupportMeshPainting: 1
Whether mesh painting is supported.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Member Functions
void ClearStreamingTextureData ()
Clears texture streaming data.
GENERATED_UCLASS_BODY () UPROPERTY() int32 ForcedLodModel
If 0, auto-select LOD level.
UMaterialInterface * GetMaterial (int32 MaterialIndex, bool bDoingNaniteMaterialAudit) const
void InitResources ()
Initializes the resources used by the static mesh component.
void NotifyIfStaticMeshChanged ()
void OutdatedKnownStaticMeshDetected () const
Called when the StaticMesh property gets overwritten without us knowing about it.
void PrivateFixupOverrideColors ()
Update the vertex override colors.
void SetStaticMeshInternal (UStaticMesh *StaticMesh)
UPROPERTY () int32 SubDivisionStepSize
Subdivision step size for static vertex lighting.
UPROPERTY ()) FColor WireframeColorOverride
Wireframe color to use if bOverrideWireframeColor is true.
UPROPERTY ()) int32 MinLOD
Specifies the smallest LOD that will be used for this component.
UPROPERTY ()) TObjectPtr< class UStaticMesh > StaticMesh
The static mesh that this component uses to render.
bool UseNaniteOverrideMaterials (bool bDoingMaterialAudit) const
Private Attributes
class UStaticMesh * KnownStaticMesh = nullptr
Used to track down when StaticMesh has been modified for notification purpose.
FOnGetNaniteResources OnGetNaniteResourcesEvent
FOnStaticMeshChanged OnStaticMeshChangedEvent
Friends
class FInstancedStaticMeshComponentHelper
class FStaticMeshComponentHelper
class FStaticMeshComponentRecreateRenderStateContext
Detailed Description
Definition at line 102 of file StaticMeshComponent.h.
Member Typedef Documentation
GetPSOVertexElementsFn
using UStaticMeshComponent::GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)> protected
Shared implementation for all StaticMesh derived components.
Definition at line 837 of file StaticMeshComponent.h.
Constructor & Destructor Documentation
~UStaticMeshComponent()
virtual UStaticMeshComponent::~UStaticMeshComponent () virtual
Member Function Documentation
AdditionalStatObject()
virtual UObject const * UStaticMeshComponent::AdditionalStatObject () const override virtual
AddMapBuildDataGUIDs()
virtual void UStaticMeshComponent::AddMapBuildDataGUIDs (TSet< FGuid > & InGUIDs) const override virtual
AddReferencedObjects()
void UStaticMeshComponent::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static
AllocateStaticLightingMesh()
virtual FStaticMeshStaticLightingMesh * UStaticMeshComponent::AllocateStaticLightingMesh (int32 LODIndex, const TArray< ULightComponent * > & InRelevantLights) virtual
Allocates an implementation of FStaticLightingMesh that will handle static lighting for this component.
Reimplemented in USplineMeshComponent.
AllowsAsyncPhysicsStateCreation()
virtual bool UStaticMeshComponent::AllowsAsyncPhysicsStateCreation () const override virtual
AllowsAsyncPhysicsStateDestruction()
virtual bool UStaticMeshComponent::AllowsAsyncPhysicsStateDestruction () const override virtual
ApplyComponentInstanceData()
void UStaticMeshComponent::ApplyComponentInstanceData (struct FStaticMeshComponentInstanceData * ComponentInstanceData)
AreNativePropertiesIdenticalTo()
virtual bool UStaticMeshComponent::AreNativePropertiesIdenticalTo (UObject * Other) const override virtual
References Other.
BeginCacheForCookedPlatformData()
virtual void UStaticMeshComponent::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform) override virtual
Reimplemented in UInstancedStaticMeshComponent.
BeginDestroy()
virtual void UStaticMeshComponent::BeginDestroy () override virtual
Reimplemented from UMeshComponent.
Reimplemented in UInstancedStaticMeshComponent.
References BeginDestroy().
Referenced by BeginDestroy().
BeginPlay()
virtual void UStaticMeshComponent::BeginPlay () override virtual
BuildTextureStreamingDataImpl()
virtual bool UStaticMeshComponent::BuildTextureStreamingDataImpl (ETextureStreamingBuildType BuildType, EMaterialQualityLevel::Type QualityLevel, ERHIFeatureLevel::Type FeatureLevel, TSet< FGuid > & DependentResources, bool & bOutSupportsBuildTextureStreamingData) override virtual
Build the data to compute accuracte StreaminTexture data.
Reimplemented in UInstancedStaticMeshComponent.
CalcBounds()
virtual FBoxSphereBounds UStaticMeshComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, UInstancedStaticMeshComponent, and USplineMeshComponent.
CanEditChange()
virtual bool UStaticMeshComponent::CanEditChange (const FProperty * InProperty) const override virtual
Reimplemented in UInstancedStaticMeshComponent.
CanEditSimulatePhysics()
virtual bool UStaticMeshComponent::CanEditSimulatePhysics () override virtual
Reimplemented in UInstancedStaticMeshComponent.
CanMeshPaintTextureColors()
bool UStaticMeshComponent::CanMeshPaintTextureColors () const
CanMeshPaintVertexColors()
bool UStaticMeshComponent::CanMeshPaintVertexColors () const
CheckForErrors()
virtual void UStaticMeshComponent::CheckForErrors () override virtual
ClearStreamingTextureData()
void UStaticMeshComponent::ClearStreamingTextureData () private
Clears texture streaming data.
CollectPSOPrecacheData()
virtual void UStaticMeshComponent::CollectPSOPrecacheData (const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) override protected virtual
Collect all the PSO precache data used by the static mesh component.
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
CollectPSOPrecacheDataImpl()
void UStaticMeshComponent::CollectPSOPrecacheDataImpl (const FVertexFactoryType * VFType, const FPSOPrecacheParams & BasePrecachePSOParams, GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList & OutParams) const protected
ComponentIsTouchingSelectionBox()
virtual bool UStaticMeshComponent::ComponentIsTouchingSelectionBox (const FBox & InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override virtual
Reimplemented in UInstancedStaticMeshComponent.
ComponentIsTouchingSelectionFrustum()
virtual bool UStaticMeshComponent::ComponentIsTouchingSelectionFrustum (const FConvexVolume & InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override virtual
Reimplemented in UInstancedStaticMeshComponent.
ComputeHashTextureStreamingBuiltData()
virtual uint32 UStaticMeshComponent::ComputeHashTextureStreamingBuiltData () const override virtual
ComputeHLODHash()
virtual void UStaticMeshComponent::ComputeHLODHash (class FHLODHashBuilder & HashBuilder) const override virtual
Reimplemented in UInstancedStaticMeshComponent.
CreateMeshHitProxy()
virtual HHitProxy * UStaticMeshComponent::CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex) const override virtual
CreateRenderState_Concurrent()
virtual void UStaticMeshComponent::CreateRenderState_Concurrent (FRegisterComponentContext * Context) override virtual
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UStaticMeshComponent::CreateSceneProxy () override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
CreateStaticMeshSceneProxy()
virtual FPrimitiveSceneProxy * UStaticMeshComponent::CreateStaticMeshSceneProxy (Nanite::FMaterialAudit & NaniteMaterials, bool bCreateNanite) protected virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
DECLARE_DELEGATE_RetVal()
UStaticMeshComponent::DECLARE_DELEGATE_RetVal (const Nanite::FResources * , FOnGetNaniteResources)
Called during scene proxy creation to get the Nanite resource data.
DECLARE_EVENT_OneParam()
UStaticMeshComponent::DECLARE_EVENT_OneParam (UStaticMeshComponent , FOnStaticMeshChanged , UStaticMeshComponent *)
Called when the static mesh changes.
DoCustomNavigableGeometryExport()
virtual bool UStaticMeshComponent::DoCustomNavigableGeometryExport (FNavigableGeometryExport & GeomExport) const override virtual
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
DoesSocketExist()
virtual bool UStaticMeshComponent::DoesSocketExist (FName InSocketName) const override virtual
ExportCustomProperties()
virtual void UStaticMeshComponent::ExportCustomProperties (FOutputDevice & Out, uint32 Indent) override virtual
References ExportCustomProperties().
Referenced by ExportCustomProperties().
GENERATED_UCLASS_BODY()
UStaticMeshComponent::GENERATED_UCLASS_BODY () private
If 0, auto-select LOD level.
if >0, force to (ForcedLodModel-1).
References Category, LOD, and UPROPERTY().
GetBlueprintCreatedComponentIndex()
int32 UStaticMeshComponent::GetBlueprintCreatedComponentIndex () const
Get this components index in its parents blueprint created components array (used for matching instance data)
GetBodySetup()
virtual class UBodySetup * UStaticMeshComponent::GetBodySetup () override virtual
Reimplemented in USplineMeshComponent.
GetComponentInstanceData()
virtual TStructOnScope< FActorComponentInstanceData > UStaticMeshComponent::GetComponentInstanceData () const override virtual
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
GetDefaultMaterialSlotsOverlayMaterial()
virtual void UStaticMeshComponent::GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > & OutMaterialSlotOverlayMaterials) const override virtual
Get all default LOD sections overlay materials used by a mesh.
The implementer must add all LOD sections and set them to null if there is no value. We need all sections in case they are all active we wont add the global mesh MaterialOverlay in GetUseMaterials or GetMaterialRelevance.
Reimplemented from UMeshComponent.
GetDetailedInfoInternal()
virtual FString UStaticMeshComponent::GetDetailedInfoInternal () const override virtual
GetDiffuseBoost()
virtual float UStaticMeshComponent::GetDiffuseBoost (int32 ElementIndex) const override virtual
GetEditorMaterial()
virtual UMaterialInterface * UStaticMeshComponent::GetEditorMaterial (int32 MaterialIndex) const override virtual
GetEmissiveBoost()
virtual float UStaticMeshComponent::GetEmissiveBoost (int32 ElementIndex) const override virtual
GetEstimatedLightAndShadowMapMemoryUsage()
virtual bool UStaticMeshComponent::GetEstimatedLightAndShadowMapMemoryUsage (int32 & TextureLightMapMemoryUsage, int32 & TextureShadowMapMemoryUsage, int32 & VertexLightMapMemoryUsage, int32 & VertexShadowMapMemoryUsage, int32 & StaticLightingResolution, bool & bIsUsingTextureMapping, bool & bHasLightmapTexCoords) const virtual
Returns the light and shadow map memory for this primite in its out variables.
Shadow map memory usage is per light whereof lightmap data is independent of number of lights, assuming at least one.
Parameters
[out] TextureLightMapMemoryUsage Estimated memory usage in bytes for light map texel data
[out] TextureShadowMapMemoryUsage Estimated memory usage in bytes for shadow map texel data
[out] VertexLightMapMemoryUsage Estimated memory usage in bytes for light map vertex data
[out] VertexShadowMapMemoryUsage Estimated memory usage in bytes for shadow map vertex data
[out] StaticLightingResolution The StaticLightingResolution used for Texture estimates
[out] bIsUsingTextureMapping Set to true if the mesh is using texture mapping currently; false if vertex
[out] bHasLightmapTexCoords Set to true if the mesh has the proper UV channels
Returns
bool true if the mesh has static lighting; false if not
GetEstimatedLightMapResolution()
virtual void UStaticMeshComponent::GetEstimatedLightMapResolution (int32 & Width, int32 & Height) const virtual
Returns the lightmap resolution used for this primitive instance in the case of it supporting texture light/ shadow maps.
This will return the value assuming the primitive will be automatically switched to use texture mapping.
Parameters
Width [out] Width of light/shadow map
Height [out] Height of light/shadow map
References Width.
GetForcedLodModel()
FORCEINLINE int32 UStaticMeshComponent::GetForcedLodModel () const inline
Definition at line 805 of file StaticMeshComponent.h.
References FORCEINLINE.
GetForceNaniteForMasked()
FORCEINLINE bool UStaticMeshComponent::GetForceNaniteForMasked () const inline
Definition at line 808 of file StaticMeshComponent.h.
References FORCEINLINE.
GetLightAndShadowMapMemoryUsage()
virtual void UStaticMeshComponent::GetLightAndShadowMapMemoryUsage (int32 & LightMapMemoryUsage, int32 & ShadowMapMemoryUsage) const override virtual
Reimplemented in UInstancedStaticMeshComponent.
GetLightMapResolution()
virtual bool UStaticMeshComponent::GetLightMapResolution (int32 & Width, int32 & Height) const override virtual
References Width.
GetMaterial() [1/2]
virtual UMaterialInterface * UStaticMeshComponent::GetMaterial (int32 MaterialIndex) const final virtual
Reimplemented from UMeshComponent.
References const, and GetMaterial().
Referenced by GetMaterial().
GetMaterial() [2/2]
UMaterialInterface * UStaticMeshComponent::GetMaterial (int32 MaterialIndex, bool bDoingNaniteMaterialAudit) const private
GetMaterialFromCollisionFaceIndex()
virtual UMaterialInterface * UStaticMeshComponent::GetMaterialFromCollisionFaceIndex (int32 FaceIndex, int32 & SectionIndex) const override virtual
GetMaterialIndex()
virtual int32 UStaticMeshComponent::GetMaterialIndex (FName MaterialSlotName) const override virtual
GetMaterialPropertyPath()
virtual bool UStaticMeshComponent::GetMaterialPropertyPath (int32 ElementIndex, UObject *& OutOwner, FString & OutPropertyPath, FProperty *& OutProperty) override virtual
GetMaterialSlotNames()
virtual TArray< FName > UStaticMeshComponent::GetMaterialSlotNames () const override virtual
GetMaterialStreamingData()
virtual bool UStaticMeshComponent::GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo & MaterialData) const override virtual
Get material, UV density and bounds for a given material index.
Reimplemented from UMeshComponent.
Reimplemented in UInstancedStaticMeshComponent.
GetMemberNameChecked_StaticMesh()
const FName UStaticMeshComponent::GetMemberNameChecked_StaticMesh () inline static
Helper function to get the FName of the private static mesh member.
Definition at line 144 of file StaticMeshComponent.h.
References GET_MEMBER_NAME_CHECKED, and StaticMesh.
GetMeshMapBuildData()
const FMeshMapBuildData * UStaticMeshComponent::GetMeshMapBuildData (const FStaticMeshComponentLODInfo & LODInfo, bool bCheckForResourceCluster = true) const
GetMeshPaintTexture()
virtual UTexture * UStaticMeshComponent::GetMeshPaintTexture () const override virtual
Get the mesh paint texture set on this component.
This does not take into account any transient override.
Reimplemented from UMeshComponent.
GetMeshPaintTextureCoordinateIndex()
virtual int32 UStaticMeshComponent::GetMeshPaintTextureCoordinateIndex () const override virtual
Get the default coordinate index for painting to the mesh paint texture on this component.
Reimplemented from UMeshComponent.
GetMeshPaintTextureResolution()
int32 UStaticMeshComponent::GetMeshPaintTextureResolution () const
Returns the size to use when creating a mesh paint texture on this component.
GetMinLOD()
FORCEINLINE int32 UStaticMeshComponent::GetMinLOD () const inline
Definition at line 807 of file StaticMeshComponent.h.
References FORCEINLINE, and MinLOD.
GetNaniteAuditMaterial()
UMaterialInterface * UStaticMeshComponent::GetNaniteAuditMaterial (int32 MaterialIndex) const
GetNaniteResources()
virtual const Nanite::FResources * UStaticMeshComponent::GetNaniteResources () const virtual
GetNavigationBounds()
virtual FBox UStaticMeshComponent::GetNavigationBounds () const override virtual
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
GetNavigationData()
virtual void UStaticMeshComponent::GetNavigationData (FNavigationRelevantData & Data) const override virtual
Reimplemented in UInstancedStaticMeshComponent.
GetNumMaterials()
virtual int32 UStaticMeshComponent::GetNumMaterials () const override virtual
Reimplemented from UMeshComponent.
GetOverrideMinLOD()
FORCEINLINE bool UStaticMeshComponent::GetOverrideMinLOD () const inline
Definition at line 806 of file StaticMeshComponent.h.
References FORCEINLINE.
GetPrimitiveStats()
virtual void UStaticMeshComponent::GetPrimitiveStats (FPrimitiveStats & PrimitiveStats) const override virtual
GetShadowIndirectOnly()
virtual bool UStaticMeshComponent::GetShadowIndirectOnly () const inline override virtual
Definition at line 598 of file StaticMeshComponent.h.
GetSocketByName()
class UStaticMeshSocket const * UStaticMeshComponent::GetSocketByName (FName InSocketName) const
Returns the named socket on the static mesh component.
Returns
UStaticMeshSocket of named socket on the static mesh component. None if not found.
References const.
GetSocketTransform()
virtual FTransform UStaticMeshComponent::GetSocketTransform (FName InSocketName, ERelativeTransformSpace TransformSpace = RTS_World) const override virtual
Reimplemented in USplineMeshComponent.
GetStaticLightingInfo()
virtual void UStaticMeshComponent::GetStaticLightingInfo (FStaticLightingPrimitiveInfo & OutPrimitiveInfo, const TArray< ULightComponent * > & InRelevantLights, const FLightingBuildOptions & Options) override virtual
Reimplemented in UInstancedStaticMeshComponent.
GetStaticLightingType()
virtual ELightMapInteractionType UStaticMeshComponent::GetStaticLightingType () const override virtual
GetStaticLightMapResolution()
virtual int32 UStaticMeshComponent::GetStaticLightMapResolution () const override virtual
GetStaticMesh()
TObjectPtr< UStaticMesh > UStaticMeshComponent::GetStaticMesh () const inline
Get the StaticMesh used by this instance.
Definition at line 429 of file StaticMeshComponent.h.
References GetStaticMesh(), KnownStaticMesh, OutdatedKnownStaticMeshDetected(), and StaticMesh.
Referenced by GetStaticMesh().
GetStreamingRenderAssetInfo()
virtual void UStaticMeshComponent::GetStreamingRenderAssetInfo (FStreamingTextureLevelContext & LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > & OutStreamingRenderAssets) const override virtual
Get the StreaminTexture data.
Reimplemented in UInstancedStaticMeshComponent.
GetStreamingScale()
virtual float UStaticMeshComponent::GetStreamingScale () const inline override virtual
Definition at line 650 of file StaticMeshComponent.h.
GetTextureLightAndShadowMapMemoryUsage()
virtual void UStaticMeshComponent::GetTextureLightAndShadowMapMemoryUsage (int32 InWidth, int32 InHeight, int32 & OutLightMapMemoryUsage, int32 & OutShadowMapMemoryUsage) const virtual
Get the memory used for texture-based light and shadow maps of the given width and height.
Parameters
InWidth The desired width of the light/shadow map
InHeight The desired height of the light/shadow map
OutLightMapMemoryUsage The resulting lightmap memory used
OutShadowMapMemoryUsage The resulting shadowmap memory used
GetTextureStreamingTransformScale()
virtual float UStaticMeshComponent::GetTextureStreamingTransformScale () const virtual
Get the scale comming form the component, when computing StreamingTexture data.
Used to support instanced meshes.
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
GetUsedMaterials()
virtual void UStaticMeshComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const final virtual
Reimplemented from UMeshComponent.
References const.
GetUsedTextures()
virtual void UStaticMeshComponent::GetUsedTextures (TArray< UTexture * > & OutTextures, EMaterialQualityLevel::Type QualityLevel) override virtual
GetWireframeColor()
FColor UStaticMeshComponent::GetWireframeColor () const
Returns the wireframe color to use for this component.
HasAnySockets()
virtual bool UStaticMeshComponent::HasAnySockets () const override virtual
HasLightmapTextureCoordinates()
virtual bool UStaticMeshComponent::HasLightmapTextureCoordinates () const virtual
Returns true if the static mesh the component uses has valid lightmap texture coordinates.
HasValidNaniteData()
virtual bool UStaticMeshComponent::HasValidNaniteData () const virtual
Returns true if the component has valid Nanite render data.
HasValidSettingsForStaticLighting()
virtual bool UStaticMeshComponent::HasValidSettingsForStaticLighting (bool bOverlookInvalidComponents) const override virtual
Returns true if the component is static AND has the right static mesh setup to support lightmaps.
ImportCustomProperties()
virtual void UStaticMeshComponent::ImportCustomProperties (const TCHAR * SourceText, FFeedbackContext * Warn) override virtual
References const, ImportCustomProperties(), and Warn.
Referenced by ImportCustomProperties().
InitializeComponent()
virtual void UStaticMeshComponent::InitializeComponent () override virtual
InitResources()
void UStaticMeshComponent::InitResources () private
Initializes the resources used by the static mesh component.
InvalidateLightingCacheDetailed()
virtual void UStaticMeshComponent::InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly) override virtual
IsCachedCookedPlatformDataLoaded()
virtual bool UStaticMeshComponent::IsCachedCookedPlatformDataLoaded (const ITargetPlatform * TargetPlatform) override virtual
Reimplemented in UInstancedStaticMeshComponent.
IsCompiling()
virtual bool UStaticMeshComponent::IsCompiling () const override virtual
IsDisallowNanite()
FORCEINLINE bool UStaticMeshComponent::IsDisallowNanite () const inline
Definition at line 802 of file StaticMeshComponent.h.
References FORCEINLINE.
IsForceDisableNanite()
FORCEINLINE bool UStaticMeshComponent::IsForceDisableNanite () const inline
Definition at line 803 of file StaticMeshComponent.h.
References FORCEINLINE.
IsForceNaniteForMasked()
FORCEINLINE bool UStaticMeshComponent::IsForceNaniteForMasked () const inline
Definition at line 804 of file StaticMeshComponent.h.
References FORCEINLINE.
IsHLODRelevant()
virtual bool UStaticMeshComponent::IsHLODRelevant () const override virtual
Reimplemented in UInstancedStaticMeshComponent.
IsMaterialSlotNameValid()
virtual bool UStaticMeshComponent::IsMaterialSlotNameValid (FName MaterialSlotName) const override virtual
IsNavigationRelevant()
virtual bool UStaticMeshComponent::IsNavigationRelevant () const override virtual
Reimplemented in UInstancedStaticMeshComponent.
IsPostLoadThreadSafe()
virtual bool UStaticMeshComponent::IsPostLoadThreadSafe () const override virtual
IsPrecomputedLightingValid()
virtual bool UStaticMeshComponent::IsPrecomputedLightingValid () const override virtual
IsReverseCulling()
FORCEINLINE bool UStaticMeshComponent::IsReverseCulling () const inline
Definition at line 801 of file StaticMeshComponent.h.
References FORCEINLINE.
IsShown()
virtual bool UStaticMeshComponent::IsShown (const FEngineShowFlags & ShowFlags) const override virtual
NotifyIfStaticMeshChanged()
void UStaticMeshComponent::NotifyIfStaticMeshChanged () private
OnAsyncDestroyPhysicsStateEnd_GameThread()
virtual void UStaticMeshComponent::OnAsyncDestroyPhysicsStateEnd_GameThread () override virtual
OnCreatePhysicsState()
virtual void UStaticMeshComponent::OnCreatePhysicsState () override virtual
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
OnDestroyPhysicsState()
virtual void UStaticMeshComponent::OnDestroyPhysicsState () override virtual
Reimplemented in UInstancedStaticMeshComponent.
OnGetNaniteResources() [1/2]
virtual FOnGetNaniteResources & UStaticMeshComponent::OnGetNaniteResources () inline virtual
Definition at line 899 of file StaticMeshComponent.h.
References OnGetNaniteResourcesEvent.
OnGetNaniteResources() [2/2]
virtual const FOnGetNaniteResources & UStaticMeshComponent::OnGetNaniteResources () const inline virtual
Definition at line 900 of file StaticMeshComponent.h.
References OnGetNaniteResourcesEvent.
OnMeshRebuild()
void UStaticMeshComponent::OnMeshRebuild (bool bRenderDataChanged)
OnStaticMeshChanged()
virtual FOnStaticMeshChanged & UStaticMeshComponent::OnStaticMeshChanged () inline virtual
Definition at line 905 of file StaticMeshComponent.h.
References OnStaticMeshChangedEvent.
OnUnregister()
virtual UE_DECLARE_COMPONENT_ACTOR_INTERFACE(StaticMeshComponent) protected void UStaticMeshComponent::OnUnregister () override virtual
Reimplemented in UInstancedStaticMeshComponent.
OutdatedKnownStaticMeshDetected()
void UStaticMeshComponent::OutdatedKnownStaticMeshDetected () const private
Called when the StaticMesh property gets overwritten without us knowing about it.
Referenced by GetStaticMesh().
PostApplyToComponent()
virtual void UStaticMeshComponent::PostApplyToComponent () override virtual
References PostApplyToComponent().
Referenced by PostApplyToComponent().
PostDuplicate()
virtual void UStaticMeshComponent::PostDuplicate (bool bDuplicateForPIE) override virtual
PostEditChangeProperty()
virtual void UStaticMeshComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented in USplineMeshComponent.
PostEditImport()
virtual void UStaticMeshComponent::PostEditImport () override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent.
PostEditUndo()
virtual void UStaticMeshComponent::PostEditUndo () override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
PostInitProperties()
virtual void UStaticMeshComponent::PostInitProperties () override virtual
References PostInitProperties().
Referenced by PostInitProperties().
PostLoad()
virtual void UStaticMeshComponent::PostLoad () override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
PostReinitProperties()
virtual void UStaticMeshComponent::PostReinitProperties () override virtual
References PostReinitProperties().
Referenced by PostReinitProperties().
PostStaticMeshCompilation()
virtual void UStaticMeshComponent::PostStaticMeshCompilation () virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
PrecachePSOs()
virtual void UStaticMeshComponent::PrecachePSOs () override virtual
PreEditUndo()
virtual void UStaticMeshComponent::PreEditUndo () override virtual
PreStaticMeshCompilation()
virtual void UStaticMeshComponent::PreStaticMeshCompilation () virtual
PrestreamMeshLODs()
virtual bool UStaticMeshComponent::PrestreamMeshLODs (float Seconds) override virtual
References Seconds.
PrivateFixupOverrideColors()
void UStaticMeshComponent::PrivateFixupOverrideColors () private
Update the vertex override colors.
PropagateLightingScenarioChange()
virtual void UStaticMeshComponent::PropagateLightingScenarioChange () override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, and UInstancedStaticMeshComponent.
QuerySupportedSockets()
virtual void UStaticMeshComponent::QuerySupportedSockets (TArray< FComponentSocketDescription > & OutSockets) const override virtual
RegisterLODStreamingCallback() [1/2]
virtual void UStaticMeshComponent::RegisterLODStreamingCallback (FLODStreamingCallback && Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn) override virtual
Register a one-time callback that will be called when criteria met.
Parameters
Callback
LODIdx The LOD index expected. Specify -1 for the MinLOD.
TimeoutSecs Timeout in seconds
bOnStreamIn To get notified when the expected LOD is streamed in or out
Reimplemented from UMeshComponent.
RegisterLODStreamingCallback() [2/2]
virtual void UStaticMeshComponent::RegisterLODStreamingCallback (FLODStreamingCallback && CallbackStreamingStart, FLODStreamingCallback && CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs) override virtual
Register a one-time callback that will be called when streaming starts or ends.
Parameters
CallbackStreamingStart The callback to notify when streaming new LODs in begins. The callback will not always be called if the asset is not streamable, or the asset or component is unloaded.
CallbackStreamingDone The callback to notify when streaming is done. The callback will not be called if the start timeout expired.
TimeoutStartSecs Timeout for streaming to start, in seconds
TimeoutDoneSecs Timeout for streaming to end, in seconds
Reimplemented from UMeshComponent.
ReleaseResources()
void UStaticMeshComponent::ReleaseResources ()
Referenced by USTRUCT().
RemapActorTextureStreamingBuiltDataToLevel()
virtual bool UStaticMeshComponent::RemapActorTextureStreamingBuiltDataToLevel (const class UActorTextureStreamingBuildDataComponent * InActorTextureBuildData) override virtual
RemoveInstanceVertexColorsFromLOD()
void UStaticMeshComponent::RemoveInstanceVertexColorsFromLOD (int32 LODToRemoveColorsFrom)
Removes instance vertex colors from the specified LOD.
Parameters
LODToRemoveColorsFrom Index of the LOD to remove instance colors from
RequiresGameThreadEndOfFrameRecreate()
virtual bool UStaticMeshComponent::RequiresGameThreadEndOfFrameRecreate () const override virtual
Serialize()
virtual void UStaticMeshComponent::Serialize (FArchive & Ar) override virtual
Reimplemented in UHierarchicalInstancedStaticMeshComponent, UInstancedStaticMeshComponent, and USplineMeshComponent.
References Ar, and Serialize().
Referenced by Serialize().
SetCollisionProfileName()
virtual void UStaticMeshComponent::SetCollisionProfileName (FName InCollisionProfileName, bool bUpdateOverlaps = true) override virtual
References SetCollisionProfileName().
Referenced by SetCollisionProfileName().
SetLODDataCount()
bool UStaticMeshComponent::SetLODDataCount (const uint32 MinSize, const uint32 MaxSize)
Add or remove elements to have the size in the specified range.
Reconstructs elements if MaxSize<MinSize. Returns true if an element was added or removed.
References MaxSize, and MinSize.
SetMeshPaintTexture()
virtual void UStaticMeshComponent::SetMeshPaintTexture (UTexture * Texture) override virtual
Set the mesh paint texture on this component.
Reimplemented from UMeshComponent.
References Texture.
SetMeshPaintTextureOverride()
virtual void UStaticMeshComponent::SetMeshPaintTextureOverride (UTexture * OverrideTexture) override virtual
Set a transient override mesh paint texture on this component.
Reimplemented from UMeshComponent.
SetStaticLightingMapping()
virtual bool UStaticMeshComponent::SetStaticLightingMapping (bool bTextureMapping, int32 ResolutionToUse) virtual
Switches the static mesh component to use either Texture or Vertex static lighting.
Parameters
bTextureMapping If true, set the component to use texture light mapping. If false, set it to use vertex light mapping.
ResolutionToUse If != 0, set the resolution to the given value.
Returns
bool true if successfully set; false if not If false, set it to use vertex light mapping.
SetStaticMeshInternal()
void UStaticMeshComponent::SetStaticMeshInternal (UStaticMesh * StaticMesh) private
References SetStaticMeshInternal(), and StaticMesh.
Referenced by SetStaticMeshInternal().
ShouldCollideWhenPlacing()
virtual bool UStaticMeshComponent::ShouldCollideWhenPlacing () const inline override virtual
Definition at line 536 of file StaticMeshComponent.h.
ShouldCreateNaniteProxy()
bool UStaticMeshComponent::ShouldCreateNaniteProxy (Nanite::FMaterialAudit * OutNaniteMaterials = nullptr) const protected
ShouldCreatePhysicsState()
virtual bool UStaticMeshComponent::ShouldCreatePhysicsState () const override virtual
Reimplemented in UInstancedStaticMeshComponent.
ShouldCreateRenderState()
virtual bool UStaticMeshComponent::ShouldCreateRenderState () const override virtual
ShouldExportAsObstacle()
bool UStaticMeshComponent::ShouldExportAsObstacle (const UNavCollisionBase & InNavCollision) const protected
ShouldIncrementalPreRegister()
virtual bool UStaticMeshComponent::ShouldIncrementalPreRegister (UWorld * WorldContext) const override virtual
ShouldRecreateProxyOnUpdateTransform()
virtual bool UStaticMeshComponent::ShouldRecreateProxyOnUpdateTransform () const override virtual
ShouldRenderSelected()
virtual bool UStaticMeshComponent::ShouldRenderSelected () const override virtual
Reimplemented in USplineMeshComponent.
SupportsDefaultCollision()
virtual bool UStaticMeshComponent::SupportsDefaultCollision () virtual
Whether or not the component supports default collision from its static mesh asset.
SupportsDitheredLODTransitions()
virtual bool UStaticMeshComponent::SupportsDitheredLODTransitions (ERHIFeatureLevel::Type FeatureLevel) virtual
Whether we can support dithered LOD transitions (default behavior checks all materials).
Used for HISMC LOD.
SupportsStaticLighting()
virtual bool UStaticMeshComponent::SupportsStaticLighting () const inline override protected virtual
Whether the component type supports static lighting.
Reimplemented in UInstancedStaticMeshComponent.
Definition at line 841 of file StaticMeshComponent.h.
SupportsWorldPositionOffsetVelocity()
virtual bool UStaticMeshComponent::SupportsWorldPositionOffsetVelocity () const inline override virtual
Definition at line 651 of file StaticMeshComponent.h.
UE_DEPRECATED()
UStaticMeshComponent::UE_DEPRECATED (5. 6, "Use UPrimitiveComponent::IsFirstPersonRelevant() instead.") const inline
Definition at line 753 of file StaticMeshComponent.h.
References bool.
UFUNCTION() [1/12]
UStaticMeshComponent::UFUNCTION ()
Change the StaticMesh used by this instance.
References Category.
UFUNCTION() [2/12]
UStaticMeshComponent::UFUNCTION () &
Get Local bounds.
References Category.
UFUNCTION() [3/12]
UStaticMeshComponent::UFUNCTION ()
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [4/12]
UStaticMeshComponent::UFUNCTION ()
Sets the component's DistanceFieldSelfShadowBias.
bOverrideDistanceFieldSelfShadowBias must be enabled for this to have an effect.
References Category, and UFUNCTION().
UFUNCTION() [5/12]
UStaticMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [6/12]
UStaticMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [7/12]
UStaticMeshComponent::UFUNCTION ()
Force disabling of Nanite rendering.
When true, Will swap to the the fallback mesh instead.
References Category, and UFUNCTION().
UFUNCTION() [8/12]
UStaticMeshComponent::UFUNCTION ()
References Category.
UFUNCTION() [9/12]
UStaticMeshComponent::UFUNCTION ()
Set forced reverse culling.
References Category, and UFUNCTION().
UFUNCTION() [10/12]
UStaticMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [11/12]
UStaticMeshComponent::UFUNCTION () inline
Get the initial value of bEvaluateWorldPositionOffset.
This is the value when BeginPlay() was last called, or if UpdateInitialEvaluateWorldPositionOffset is called.
Definition at line 468 of file StaticMeshComponent.h.
References bInitialEvaluateWorldPositionOffset, Category, and UFUNCTION().
UFUNCTION() [12/12]
UStaticMeshComponent::UFUNCTION () inline
This manually updates the initial value of bEvaluateWorldPositionOffset to be the current value.
This is useful if the default value of bEvaluateWorldPositionOffset is changed after constructing the component.
Definition at line 474 of file StaticMeshComponent.h.
References bInitialEvaluateWorldPositionOffset, and Category.
UpdateBounds()
virtual void UStaticMeshComponent::UpdateBounds () override virtual
Reimplemented in UInstancedStaticMeshComponent, and USplineMeshComponent.
UpdateCollisionFromStaticMesh()
void UStaticMeshComponent::UpdateCollisionFromStaticMesh ()
Sets the BodyInstance to use the mesh's body setup for external collision information.
UpdateMapBuildDataId()
void UStaticMeshComponent::UpdateMapBuildDataId ()
UpdateStaticLightingData()
void UStaticMeshComponent::UpdateStaticLightingData ()
UPROPERTY() [1/18]
UStaticMeshComponent::UPROPERTY ()
Useful for reducing self shadowing from distance field methods when using world position offset to animate the mesh's vertices.
References Category, and UPROPERTY().
UPROPERTY() [2/18]
UStaticMeshComponent::UPROPERTY ()
Used to forcefully disable pixel programmable rasterization of Nanite when the mesh is further than a given distance from the camera.
References Category, and UPROPERTY().
UPROPERTY() [3/18]
UStaticMeshComponent::UPROPERTY () private
Subdivision step size for static vertex lighting.
References UPROPERTY().
UPROPERTY() [4/18]
UStaticMeshComponent::UPROPERTY () pure virtual
Distance at which to disable World Position Offset for an entire instance (0 = Never disable WPO).
Implemented in UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UHierarchicalInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, UInstancedStaticMeshComponent, USplineMeshComponent, USplineMeshComponent, USplineMeshComponent, USplineMeshComponent, USplineMeshComponent, and USplineMeshComponent.
References Category, and UPROPERTY().
UPROPERTY() [5/18]
UStaticMeshComponent::UPROPERTY ()
The Lightmass settings for this object.
References Category.
UPROPERTY() [6/18]
UStaticMeshComponent::UPROPERTY ()
The list of texture, bounds and scales.
As computed in the texture streaming build process.
References UPROPERTY().
UPROPERTY() [7/18]
UStaticMeshComponent::UPROPERTY ()
Static mesh LOD data.
Contains static lighting data along with instanced mesh vertex colors.
References transient.
UPROPERTY() [8/18]
UStaticMeshComponent::UPROPERTY ()
References Transient.
UPROPERTY() [9/18]
UStaticMeshComponent::UPROPERTY ()
Cooked pointer to texture containing mesh painting for this mesh component.
This will be taken from MeshPaintTexture but can be empty on some platforms if we choose to strip the data.
UPROPERTY() [10/18]
UStaticMeshComponent::UPROPERTY ()
Set this to override the locally stored mesh paint texture.
References Transient.
UPROPERTY() [11/18]
UStaticMeshComponent::UPROPERTY () private
Wireframe color to use if bOverrideWireframeColor is true.
References Category, meta, and UPROPERTY().
UPROPERTY() [12/18]
UStaticMeshComponent::UPROPERTY ()
Controls how dark the dynamic indirect shadow can be.
References Category, float, and meta.
UPROPERTY() [13/18]
UStaticMeshComponent::UPROPERTY ()
Allows adjusting the desired streaming distance of streaming textures that uses UV 0.
1.0 is the default, whereas a higher value makes the textures stream in sooner from far away. A lower value (0.0-1.0) makes the textures stream in later (you have to be closer). Value can be < 0 (from legcay content, or code changes)
References Category, meta, ToolTip, and UPROPERTY().
UPROPERTY() [14/18]
UStaticMeshComponent::UPROPERTY () private
Specifies the smallest LOD that will be used for this component.
This is ignored if ForcedLodModel is enabled.
References Category, LOD, meta, MinLOD, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [15/18]
UStaticMeshComponent::UPROPERTY ()
Light map resolution to use on this component, used if bOverrideLightMapRes is true and there is a valid StaticMesh.
References Category, meta, and UPROPERTY().
UPROPERTY() [16/18]
UPROPERTY()) uint8 bOverrideWireframeColor UPROPERTY() uint8 bOverrideMinLOD UPROPERTY() uint8 bOverrideNavigationExport UPROPERTY() uint8 bForceNavigationObstacle UPROPERTY() uint8 bDisallowMeshPaintPerInstance_DEPRECATED UPROPERTY() uint8 bIgnoreInstanceForTextureStreaming UPROPERTY()) uint8 bOverrideLightMapRes UPROPERTY()) uint8 bCastDistanceFieldIndirectShadow UPROPERTY() uint8 bOverrideDistanceFieldSelfShadowBias UPROPERTY() uint8 bUseSubDivisions UPROPERTY() uint8 bUseDefaultCollision UPROPERTY()) uint8 bSortTriangles UPROPERTY() uint8 bReverseCulling UPROPERTY() uint8 bEnableVertexColorMeshPainting UPROPERTY() uint8 bEnableTextureColorMeshPainting UPROPERTY()) uint8 bOverrideMeshPaintTextureCoordinateIndex UPROPERTY()) uint8 bOverrideMeshPaintTextureResolution UStaticMeshComponent::UPROPERTY ()
If true, WireframeColorOverride will be used.
If false, color is determined based on mobility and physics simulation settings Whether to override the MinLOD setting of the static mesh asset with the MinLOD of this component. If true, bForceNavigationObstacle flag will take priority over navigation data stored in StaticMesh Allows overriding navigation export behavior per component: full collisions or dynamic obstacle Deprecated. Use bEnableVertexColorMeshPainting instead. Ignore this instance of this static mesh when calculating streaming information. This can be useful when doing things like applying character textures to static geometry, to avoid them using distance-based streaming. Whether to override the lightmap resolution defined in the static mesh. Whether to use the mesh distance field representation (when present) for shadowing indirect lighting (from lightmaps or skylight) on Movable components. This works like capsule shadows on skeletal meshes, except using the mesh distance field so no physics asset is required. The StaticMesh must have 'Generate Mesh Distance Field' enabled, or the project must have 'Generate Mesh Distance Fields' enabled for this feature to work. Whether to override the DistanceFieldSelfShadowBias setting of the static mesh asset with the DistanceFieldSelfShadowBias of this component. Whether to use subdivisions or just the triangle's vertices. Use the collision profile specified in the StaticMesh asset. Enable dynamic sort mesh's triangles to remove ordering issue when rendered with a translucent material Controls whether the static mesh component's backface culling should be reversed If false, vertex color mesh painting is disabled on this component. This may be set to false by blueprint functions that override vertex colors in construction script. If false, texture color mesh painting is disabled on this component. Whether to override the MeshPaintTextureCoordinateIndex set on the static mesh. Whether to override the MeshPaintTextureCoordinateIndex set on the static mesh. The overriden coordinate index to use when texture color painting on this component.
References Category, meta, and UPROPERTY().
UPROPERTY() [17/18]
UStaticMeshComponent::UPROPERTY ()
The overriden resolution of texture color mesh paint textures on this component.
References Category, meta, and UPROPERTY().
UPROPERTY() [18/18]
UStaticMeshComponent::UPROPERTY () private
The static mesh that this component uses to render.
References Category, meta, StaticMesh, and UPROPERTY().
UseNaniteOverrideMaterials() [1/2]
virtual bool UStaticMeshComponent::UseNaniteOverrideMaterials () const override virtual
Determines if we use the nanite overrides from any materials.
Reimplemented from UMeshComponent.
UseNaniteOverrideMaterials() [2/2]
bool UStaticMeshComponent::UseNaniteOverrideMaterials (bool bDoingMaterialAudit) const private
UsesOnlyUnlitMaterials()
virtual bool UStaticMeshComponent::UsesOnlyUnlitMaterials () const override virtual
UsesTextureLightmaps()
virtual bool UStaticMeshComponent::UsesTextureLightmaps (int32 InWidth, int32 InHeight) const virtual
Returns true if the component uses texture lightmaps.
Parameters
InWidth [in] The width of the light/shadow map
InHeight [in] The width of the light/shadow map
Returns
bool true if texture lightmaps are used, false if not
Friends And Related Symbol Documentation
FInstancedStaticMeshComponentHelper
friend class FInstancedStaticMeshComponentHelper friend
Definition at line 916 of file StaticMeshComponent.h.
References FInstancedStaticMeshComponentHelper.
Referenced by FInstancedStaticMeshComponentHelper.
FStaticMeshComponentHelper
friend class FStaticMeshComponentHelper friend
Definition at line 915 of file StaticMeshComponent.h.
References FStaticMeshComponentHelper.
Referenced by FStaticMeshComponentHelper.
FStaticMeshComponentRecreateRenderStateContext
friend class FStaticMeshComponentRecreateRenderStateContext friend
Definition at line 914 of file StaticMeshComponent.h.
References FStaticMeshComponentRecreateRenderStateContext.
Referenced by FStaticMeshComponentRecreateRenderStateContext.
Field Documentation
bInitialEvaluateWorldPositionOffset
uint8 UStaticMeshComponent::bInitialEvaluateWorldPositionOffset protected
Forces this component to always use Nanite for masked materials, even if FNaniteSettings::bAllowMaskedMaterials=false.
Forces this component to use fallback mesh for rendering if Nanite is enabled on the mesh. Forces this component to use fallback mesh for rendering if Nanite is enabled on the mesh (run-time override) Whether to evaluate World Position Offset. Whether world position offset turns on velocity writes. If the WPO isn't static then setting false may give incorrect motion vectors. But if we know that the WPO is static then setting false may save performance. Whether to evaluate World Position Offset for ray tracing. This is only used when running with r.RayTracing.Geometry.StaticMeshes.WPO=1 Initial value of bEvaluateWorldPositionOffset when BeginPlay() was called. Can be useful if we want to reset to initial state.
Definition at line 190 of file StaticMeshComponent.h.
Referenced by UFUNCTION(), and UFUNCTION().
bMipLevelCallbackRegistered
uint8 UStaticMeshComponent::bMipLevelCallbackRegistered protected
Whether mip callbacks have been registered and need to be removed on destroy.
Definition at line 193 of file StaticMeshComponent.h.
bPrecachedPSOs
uint8 UStaticMeshComponent::bPrecachedPSOs protected
Whether PrecachedPSOs was called.
Definition at line 199 of file StaticMeshComponent.h.
bSupportMeshPainting
uint8 UStaticMeshComponent::bSupportMeshPainting protected
Whether mesh painting is supported.
This is can be set by derived component types that don't support mesh painting.
Definition at line 196 of file StaticMeshComponent.h.
const
FVector& Max UStaticMeshComponent::const
Definition at line 481 of file StaticMeshComponent.h.
Referenced by GetMaterial(), GetSocketByName(), GetUsedMaterials(), ImportCustomProperties(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), USplineMeshComponent::UFUNCTION(), and USplineMeshComponent::UFUNCTION().
KnownStaticMesh
class UStaticMesh* UStaticMeshComponent::KnownStaticMesh = nullptr private
Used to track down when StaticMesh has been modified for notification purpose.
Definition at line 134 of file StaticMeshComponent.h.
Referenced by GetStaticMesh().
OnGetNaniteResourcesEvent
FOnGetNaniteResources UStaticMeshComponent::OnGetNaniteResourcesEvent private
Definition at line 912 of file StaticMeshComponent.h.
Referenced by OnGetNaniteResources(), and OnGetNaniteResources().
OnStaticMeshChangedEvent
FOnStaticMeshChanged UStaticMeshComponent::OnStaticMeshChangedEvent private
Definition at line 910 of file StaticMeshComponent.h.
Referenced by OnStaticMeshChanged().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/StaticMeshComponent.h