Unreal Engine 5.6 C++ API: UE::Geometry::TModelingOpTask< OpType > Class Template Reference
UE::Geometry::TModelingOpTask< OpType > Class Template Reference
TModelingOpTask is an FAbortableBackgroundTask that executes a modeling operator of template type OpType.
#include "BackgroundModelingComputeSource.h"
Public Member Functions
TModelingOpTask (TUniquePtr< OpType > OperatorIn)
TUniquePtr< OpType > ExtractOperator ()
Public Member Functions inherited from UE::Geometry::FAbortableBackgroundTask
FAbortableBackgroundTask ()
FProgressCancel * GetProgress ()
bool IsAborted () const
void SetAbortSource (bool *bAbortFlagLocation)
Set the abort source flag.
Public Member Functions inherited from FNonAbandonableTask
void Abandon ()
bool CanAbandon ()
Protected Member Functions
void DoWork ()
FORCEINLINE TStatId GetStatId () const
Protected Attributes
TUniquePtr< OpType > Operator
Friends
class FAsyncTask< TModelingOpTask< OpType > >
Detailed Description
template<typename OpType>
class UE::Geometry::TModelingOpTask< OpType >
TModelingOpTask is an FAbortableBackgroundTask that executes a modeling operator of template type OpType.
OpType must implement a function with signature void CalculateResult(FProgressCancel*)
After work completes, ExtractOperator() can be used to recover the internal OpType instance, to get access to the completed work.
See TBackgroundModelingComputeSource for example usage (however this class can be used by itself)
Definition at line 27 of file BackgroundModelingComputeSource.h.
Constructor & Destructor Documentation
TModelingOpTask()
template<typename OpType> UE::Geometry::TModelingOpTask< OpType >::TModelingOpTask (TUniquePtr< OpType > OperatorIn) inline
Definition at line 33 of file BackgroundModelingComputeSource.h.
References MoveTemp(), and Operator.
Referenced by GetStatId().
Member Function Documentation
DoWork()
template<typename OpType> void UE::Geometry::TModelingOpTask< OpType >::DoWork () inline protected
Definition at line 49 of file BackgroundModelingComputeSource.h.
References UE::Geometry::FAbortableBackgroundTask::GetProgress(), Operator, and TRACE_CPUPROFILER_EVENT_SCOPE.
ExtractOperator()
template<typename OpType> TUniquePtr< OpType > UE::Geometry::TModelingOpTask< OpType >::ExtractOperator () inline
Returns
the contained computation Operator
Definition at line 40 of file BackgroundModelingComputeSource.h.
References MoveTemp(), and Operator.
GetStatId()
template<typename OpType> FORCEINLINE TStatId UE::Geometry::TModelingOpTask< OpType >::GetStatId () const inline protected
Definition at line 60 of file BackgroundModelingComputeSource.h.
References TModelingOpTask(), FORCEINLINE, and RETURN_QUICK_DECLARE_CYCLE_STAT.
Friends And Related Symbol Documentation
FAsyncTask< TModelingOpTask< OpType > >
template<typename OpType> friend class FAsyncTask< TModelingOpTask< OpType > > friend
Definition at line 367 of file BackgroundModelingComputeSource.h.
Field Documentation
Operator
template<typename OpType> TUniquePtr<OpType> UE::Geometry::TModelingOpTask< OpType >::Operator protected
Definition at line 46 of file BackgroundModelingComputeSource.h.
Referenced by TModelingOpTask(), DoWork(), and ExtractOperator().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingOperators/Public/BackgroundModelingComputeSource.h