Unreal Engine 5.6 C++ API: IConsoleObject Class Reference
IConsoleObject Class Reference abstract
Interface for console objects (variables and commands)
#include "IConsoleManager.h"
Public Member Functions
IConsoleObject ()
virtual ~IConsoleObject ()
virtual struct IConsoleCommand * AsCommand ()
Casts this object to an IConsoleCommand, verifying first that it is safe to do so.
virtual class IConsoleVariable * AsVariable ()
Casts this object to an IConsoleVariable, returns 0 if it's not.
virtual class TConsoleVariableData< bool > * AsVariableBool ()
virtual class TConsoleVariableData< float > * AsVariableFloat ()
virtual class TConsoleVariableData< int32 > * AsVariableInt ()
virtual class TConsoleVariableData< FString > * AsVariableString ()
void ClearFlags (const EConsoleVariableFlags Value)
Removes the specified flags in the internal state.
virtual FText GetDetailedHelp () const
virtual EConsoleVariableFlags GetFlags () const =0
Get the internal state of the flags.
virtual const TCHAR * GetHelp () const =0
virtual IConsoleObject * GetParentObject () const
If the object has a parent (for instance the main cvar that owns an other-platform cvar), return it.
virtual IConsoleObject * GetShadowedObject () const
If IsShadowObject() returns true, this function will return the "real" variable the shadow cvar is shadowing.
virtual bool IsDeprecated () const
bool IsEnabled () const
Test the validity of the variable wrt its flags and current build type (e.g.
virtual bool IsShadowObject () const
A shadow ConsoleObject is one that exists and can be used, but shouldn't be iterated over in anything that walks over every object and acts on it.
virtual bool IsVariableBool () const
virtual bool IsVariableFloat () const
virtual bool IsVariableInt () const
virtual bool IsVariableString () const
virtual void SetFlags (const EConsoleVariableFlags Value)=0
Sets the internal flag state to the specified value.
virtual void SetHelp (const TCHAR *Value)=0
bool TestFlags (const EConsoleVariableFlags Value) const
Test is any of the specified flags is set in the internal state.
Private Member Functions
virtual void Release ()=0
should only be called by the manager, needs to be implemented for each instance
Private Attributes
uint32 FindCallCount
Friends
class FConsoleManager
Detailed Description
Interface for console objects (variables and commands)
Definition at line 382 of file IConsoleManager.h.
Constructor & Destructor Documentation
IConsoleObject()
IConsoleObject::IConsoleObject () inline
Definition at line 387 of file IConsoleManager.h.
Referenced by GetParentObject(), and GetShadowedObject().
~IConsoleObject()
virtual IConsoleObject::~IConsoleObject () inline virtual
Definition at line 393 of file IConsoleManager.h.
Member Function Documentation
AsCommand()
virtual struct IConsoleCommand * IConsoleObject::AsCommand () inline virtual
Casts this object to an IConsoleCommand, verifying first that it is safe to do so.
Definition at line 506 of file IConsoleManager.h.
AsVariable()
virtual class IConsoleVariable * IConsoleObject::AsVariable () inline virtual
Casts this object to an IConsoleVariable, returns 0 if it's not.
Definition at line 469 of file IConsoleManager.h.
AsVariableBool()
virtual class TConsoleVariableData< bool > * IConsoleObject::AsVariableBool () inline virtual
Definition at line 479 of file IConsoleManager.h.
References bool, ensureMsgf, and TEXT.
Referenced by TAutoConsoleVariable< T >::TAutoConsoleVariable(), and IConsoleManager::FindTConsoleVariableDataBool().
AsVariableFloat()
virtual class TConsoleVariableData< float > * IConsoleObject::AsVariableFloat () inline virtual
Definition at line 491 of file IConsoleManager.h.
References ensureMsgf, float, and TEXT.
Referenced by TAutoConsoleVariable< T >::TAutoConsoleVariable(), and IConsoleManager::FindTConsoleVariableDataFloat().
AsVariableInt()
virtual class TConsoleVariableData< int32 > * IConsoleObject::AsVariableInt () inline virtual
Definition at line 485 of file IConsoleManager.h.
References ensureMsgf, and TEXT.
Referenced by TAutoConsoleVariable< T >::TAutoConsoleVariable(), and IConsoleManager::FindTConsoleVariableDataInt().
AsVariableString()
virtual class TConsoleVariableData< FString > * IConsoleObject::AsVariableString () inline virtual
Definition at line 497 of file IConsoleManager.h.
References ensureMsgf, and TEXT.
Referenced by TAutoConsoleVariable< T >::TAutoConsoleVariable().
ClearFlags()
void IConsoleObject::ClearFlags (const EConsoleVariableFlags Value) inline
Removes the specified flags in the internal state.
Definition at line 425 of file IConsoleManager.h.
References GetFlags(), New(), SetFlags(), and Value.
GetDetailedHelp()
virtual FText IConsoleObject::GetDetailedHelp () const inline virtual
Returns
a (potentially) more detailed help than GetHelp (e.g. current value for console variables)
Definition at line 414 of file IConsoleManager.h.
References FText::FromString(), and GetHelp().
GetFlags()
virtual EConsoleVariableFlags IConsoleObject::GetFlags () const pure virtual
Get the internal state of the flags.
Referenced by ClearFlags(), IConsoleVariable::SetWithCurrentPriority(), IConsoleVariable::SetWithCurrentPriority(), IConsoleVariable::SetWithCurrentPriority(), IConsoleVariable::SetWithCurrentPriority(), and TestFlags().
GetHelp()
virtual const TCHAR * IConsoleObject::GetHelp () const pure virtual
Returns
never 0, can be multi line ('
')
Referenced by GetDetailedHelp().
GetParentObject()
virtual IConsoleObject * IConsoleObject::GetParentObject () const inline virtual
If the object has a parent (for instance the main cvar that owns an other-platform cvar), return it.
Definition at line 461 of file IConsoleManager.h.
References IConsoleObject().
GetShadowedObject()
virtual IConsoleObject * IConsoleObject::GetShadowedObject () const inline virtual
If IsShadowObject() returns true, this function will return the "real" variable the shadow cvar is shadowing.
Generally not needed, as most functions (like GetInt, Set, etc) will operate on the real variable already
Definition at line 524 of file IConsoleManager.h.
References IConsoleObject().
IsDeprecated()
virtual bool IConsoleObject::IsDeprecated () const inline virtual
Definition at line 529 of file IConsoleManager.h.
IsEnabled()
bool IConsoleObject::IsEnabled () const inline
Test the validity of the variable wrt its flags and current build type (e.g.
ECVF_Cheat variables are disabled on some targets)
Definition at line 442 of file IConsoleManager.h.
References ECVF_Cheat, ECVF_Unregistered, and TestFlags().
IsShadowObject()
virtual bool IConsoleObject::IsShadowObject () const inline virtual
A shadow ConsoleObject is one that exists and can be used, but shouldn't be iterated over in anything that walks over every object and acts on it.
Definition at line 515 of file IConsoleManager.h.
IsVariableBool()
virtual bool IConsoleObject::IsVariableBool () const inline virtual
Definition at line 474 of file IConsoleManager.h.
IsVariableFloat()
virtual bool IConsoleObject::IsVariableFloat () const inline virtual
Definition at line 476 of file IConsoleManager.h.
IsVariableInt()
virtual bool IConsoleObject::IsVariableInt () const inline virtual
Definition at line 475 of file IConsoleManager.h.
IsVariableString()
virtual bool IConsoleObject::IsVariableString () const inline virtual
Definition at line 477 of file IConsoleManager.h.
Release()
virtual void IConsoleObject::Release () private pure virtual
should only be called by the manager, needs to be implemented for each instance
SetFlags()
virtual void IConsoleObject::SetFlags (const EConsoleVariableFlags Value) pure virtual
Sets the internal flag state to the specified value.
References Value.
Referenced by ClearFlags().
SetHelp()
virtual void IConsoleObject::SetHelp (const TCHAR * Value) pure virtual
Returns
never 0, can be multi line ('
')
References Value.
TestFlags()
bool IConsoleObject::TestFlags (const EConsoleVariableFlags Value) const inline
Test is any of the specified flags is set in the internal state.
Definition at line 434 of file IConsoleManager.h.
References GetFlags(), and Value.
Referenced by IsEnabled().
Friends And Related Symbol Documentation
FConsoleManager
friend class FConsoleManager friend
Definition at line 547 of file IConsoleManager.h.
References FConsoleManager.
Referenced by FConsoleManager.
Field Documentation
FindCallCount
uint32 IConsoleObject::FindCallCount private
Definition at line 539 of file IConsoleManager.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h