Unreal Engine 5.6 C++ API: FModeToolkit Class Reference
FModeToolkit Class Reference
This FModeToolkit just creates a basic UI panel that allows various InteractiveTools to be initialized, and a DetailsView used to show properties of the active Tool.
#include "BaseToolkit.h"
Data Structures
struct FEdModeToolbarRow
Public Member Functions
UNREALED_API ~FModeToolkit ()
virtual UNREALED_API void BuildToolPalette (FName Palette, class FToolBarBuilder &ToolbarBuilder)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPaletteChanged, FName)
virtual void ExtendSecondaryModeToolbar (UToolMenu *InModeToolbarMenu)
Override this function to extend the secondary mode toolbar (that appears below the main toolbar) for your mode by filling in the UToolMenu that is passed in.
virtual FText GetActiveToolDisplayName () const
virtual FText GetActiveToolMessage () const
virtual UNREALED_API FText GetBaseToolkitName () const override
UNREALED_API FName GetCurrentPalette () const
virtual UNREALED_API FEdMode * GetEditorMode () const
virtual UNREALED_API FText GetEditorModeDisplayName () const
virtual UNREALED_API FSlateIcon GetEditorModeIcon () const
virtual UNREALED_API FEditorModeTools & GetEditorModeManager () const final
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const
virtual UNREALED_API const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const override
virtual UNREALED_API TWeakObjectPtr< UEdMode > GetScriptableEditorMode () const final
virtual UNREALED_API FName GetToolkitFName () const override
virtual FText GetToolkitName () const override
virtual FText GetToolkitToolTipText () const override
virtual FText GetToolPaletteDisplayName (FName Palette) const
virtual void GetToolPaletteNames (TArray< FName > &PaletteNames) const
Returns the number of Mode specific tabs in the mode toolbar.
virtual UNREALED_API FLinearColor GetWorldCentricTabColorScale () const override
virtual UNREALED_API FString GetWorldCentricTabPrefix () const override
virtual bool HasExclusiveToolPalettes () const
virtual bool HasIntegratedToolPalettes () const
virtual UNREALED_API void Init (const TSharedPtr< IToolkitHost > &InitToolkitHost)
Initializes the mode toolkit.
virtual UNREALED_API void Init (const TSharedPtr< IToolkitHost > &InitToolkitHost, TWeakObjectPtr< UEdMode > InOwningMode)
virtual UNREALED_API void InvokeUI ()
virtual UNREALED_API bool IsAssetEditor () const override
FOnPaletteChanged & OnPaletteChanged ()
virtual void OnToolPaletteChanged (FName PaletteName)
virtual UNREALED_API void RebuildModeToolPalette ()
Force the Mode Toolbar/Palette to be repopulated with the current ToolPaletteNames.
virtual UNREALED_API void RegisterTabSpawners (const TSharedRef< FTabManager > &TabManager) final
UNREALED_API void SetCurrentPalette (FName InName)
UNREALED_API void SetModeSettingsObject (UObject *InSettingsObject)
virtual UNREALED_API void SetModeUILayer (const TSharedPtr< FAssetEditorModeUILayer > InLayer) override
virtual void ShutdownUI ()
Override this function to perform any UI cleanup before the ModeUILayer is no longer valid.
virtual UNREALED_API void UnregisterTabSpawners (const TSharedRef< FTabManager > &TabManager) final
Public Member Functions inherited from FBaseToolkit
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual FText GetTabSuffix () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API FName GetToolkitContextFName () const override
virtual UNREALED_API const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsBlueprintEditor () const override
virtual UNREALED_API bool IsHosted () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Public Member Functions inherited from TSharedFromThis< FModeToolkit >
TSharedRef< FModeToolkit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FModeToolkit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual UNREALED_API TSharedRef< SWidget > CreatePaletteWidget (TSharedPtr< FUICommandList > InCommandList, FName InToolbarCustomizationName, FName InPaletteName)
Creates the entire tool palette widget, override to specify toolbar style.
UNREALED_API TSharedRef< SDockTab > CreatePrimaryModePanel (const FSpawnTabArgs &Args)
virtual void CustomizeDetailsViewArgs (FDetailsViewArgs &ArgsInOut)
virtual void CustomizeModeDetailsViewArgs (FDetailsViewArgs &ArgsInOut)
UNREALED_API const FEditorModeInfo * GetEditorModeInfo () const
UNREALED_API EVisibility GetInlineContentHolderVisibility () const
UNREALED_API EVisibility GetNoToolSelectedTextVisibility () const
UNREALED_API bool HasToolkitBuilder () const
returns whether or not this FModeToolkit has a ToolkitBuilder defined
UNREALED_API TSharedRef< SDockTab > MakeModeToolbarTab (const FSpawnTabArgs &Args)
Creates the mode toolbar tab if needed.
UNREALED_API void OnModeIDChanged (const FEditorModeID &InID, bool bIsEntering)
virtual UNREALED_API void OnToolEnded (UInteractiveToolManager *Manager, UInteractiveTool *Tool)
virtual UNREALED_API void OnToolStarted (UInteractiveToolManager *Manager, UInteractiveTool *Tool)
virtual UNREALED_API void RebuildModeToolBar ()
virtual UNREALED_API void RequestModeUITabs ()
virtual UNREALED_API bool ShouldShowModeToolbar () const
Whether or not the mode toolbar should be shown.
UNREALED_API void SpawnOrUpdateModeToolbar ()
UNREALED_API void UpdatePrimaryModePanel ()
Protected Member Functions inherited from FBaseToolkit
virtual UNREALED_API void CreateEditorModeManager ()
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Member Functions inherited from TSharedFromThis< FModeToolkit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TArray< FEdModeToolbarRow > ActiveToolBarRows
All toolbar rows generated by active modes.
bool bUsesToolkitBuilder = false
a feature flag that can be set to true in order to make and use a ToolkitBuilder, if one is defined for a given mode.
TArray< TSharedPtr< SDockTab > > CreatedTabs
FName CurrentPaletteName
TSharedPtr< IDetailsView > DetailsView
TSharedPtr< SBorder > InlineContentHolder
Inline content area for editor modes.
TSharedPtr< IDetailsView > ModeDetailsView
TWeakPtr< SVerticalBox > ModeToolbarBox
The actual toolbar rows will be placed in this vertical box.
TSharedPtr< SBorder > ModeToolBarContainer
The container holding the mode toolbar.
TWeakPtr< SWidgetSwitcher > ModeToolbarPaletteSwitcher
The modes palette toolbar.
TWeakPtr< SDockTab > ModeToolbarTab
The dock tab for any modes that generate a toolbar.
TSharedPtr< SBorder > ModeToolHeader
The active tool header area.
TWeakPtr< FAssetEditorModeUILayer > ModeUILayer
FOnPaletteChanged OnPaletteChangedDelegate
TWeakObjectPtr< UEdMode > OwningEditorMode
TWeakPtr< SDockTab > PrimaryTab
FMinorTabConfig PrimaryTabInfo
FMinorTabConfig ToolbarInfo
TSharedPtr< FToolkitBuilder > ToolkitBuilder
The FToolkitBuilder which will build the UI for this mode, if defined.
TSharedPtr< FToolkitSections > ToolkitSections
The sections of the toolkit, defined for the ToolkitBuilder (if present)
TSharedPtr< SWidget > ToolkitWidget
Protected Attributes inherited from FBaseToolkit
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FModeToolkit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
This FModeToolkit just creates a basic UI panel that allows various InteractiveTools to be initialized, and a DetailsView used to show properties of the active Tool.
Definition at line 98 of file BaseToolkit.h.
Constructor & Destructor Documentation
~FModeToolkit()
UNREALED_API FModeToolkit::~FModeToolkit ()
Member Function Documentation
BuildToolPalette()
virtual UNREALED_API void FModeToolkit::BuildToolPalette (FName Palette, class FToolBarBuilder & ToolbarBuilder) virtual
Parameters
PaletteIndex The index of the ToolPalette to build
ToolbarBuilder The builder to use for given PaletteIndex
Reimplemented in FFractureEditorModeToolkit.
CreatePaletteWidget()
virtual UNREALED_API TSharedRef< SWidget > FModeToolkit::CreatePaletteWidget (TSharedPtr< FUICommandList > InCommandList, FName InToolbarCustomizationName, FName InPaletteName) protected virtual
Creates the entire tool palette widget, override to specify toolbar style.
CreatePrimaryModePanel()
UNREALED_API TSharedRef< SDockTab > FModeToolkit::CreatePrimaryModePanel (const FSpawnTabArgs & Args) protected
CustomizeDetailsViewArgs()
virtual void FModeToolkit::CustomizeDetailsViewArgs (FDetailsViewArgs & ArgsInOut) inline protected virtual
Definition at line 190 of file BaseToolkit.h.
CustomizeModeDetailsViewArgs()
virtual void FModeToolkit::CustomizeModeDetailsViewArgs (FDetailsViewArgs & ArgsInOut) inline protected virtual
Definition at line 189 of file BaseToolkit.h.
DECLARE_MULTICAST_DELEGATE_OneParam()
FModeToolkit::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPaletteChanged , FName)
ExtendSecondaryModeToolbar()
virtual void FModeToolkit::ExtendSecondaryModeToolbar (UToolMenu * InModeToolbarMenu) inline virtual
Override this function to extend the secondary mode toolbar (that appears below the main toolbar) for your mode by filling in the UToolMenu that is passed in.
Definition at line 178 of file BaseToolkit.h.
GetActiveToolDisplayName()
virtual FText FModeToolkit::GetActiveToolDisplayName () const inline virtual
Reimplemented in FFractureEditorModeToolkit.
Definition at line 154 of file BaseToolkit.h.
GetActiveToolMessage()
virtual FText FModeToolkit::GetActiveToolMessage () const inline virtual
Reimplemented in FFractureEditorModeToolkit.
Definition at line 155 of file BaseToolkit.h.
GetBaseToolkitName()
virtual UNREALED_API FText FModeToolkit::GetBaseToolkitName () const override virtual
Reimplemented in FFractureEditorModeToolkit.
Referenced by GetToolkitName(), and GetToolkitToolTipText().
GetCurrentPalette()
UNREALED_API FName FModeToolkit::GetCurrentPalette () const
GetEditorMode()
virtual UNREALED_API FEdMode * FModeToolkit::GetEditorMode () const virtual
Reimplemented in FFractureEditorModeToolkit.
References GetEditorMode().
Referenced by GetEditorMode().
GetEditorModeDisplayName()
virtual UNREALED_API FText FModeToolkit::GetEditorModeDisplayName () const virtual
References GetEditorModeDisplayName().
Referenced by GetEditorModeDisplayName().
GetEditorModeIcon()
virtual UNREALED_API FSlateIcon FModeToolkit::GetEditorModeIcon () const virtual
References GetEditorModeIcon().
Referenced by GetEditorModeIcon().
GetEditorModeInfo()
UNREALED_API const FEditorModeInfo * FModeToolkit::GetEditorModeInfo () const protected
GetEditorModeManager()
virtual UNREALED_API FEditorModeTools & FModeToolkit::GetEditorModeManager () const final virtual
Implements FBaseToolkit.
GetInlineContent()
virtual UNREALED_API TSharedPtr< SWidget > FModeToolkit::GetInlineContent () const virtual
Reimplemented from FBaseToolkit.
Reimplemented in FFractureEditorModeToolkit.
References GetInlineContent().
Referenced by GetInlineContent().
GetInlineContentHolderVisibility()
UNREALED_API EVisibility FModeToolkit::GetInlineContentHolderVisibility () const protected
GetNoToolSelectedTextVisibility()
UNREALED_API EVisibility FModeToolkit::GetNoToolSelectedTextVisibility () const protected
GetObjectsCurrentlyBeingEdited()
virtual UNREALED_API const TArray< UObject * > * FModeToolkit::GetObjectsCurrentlyBeingEdited () const override virtual
GetScriptableEditorMode()
virtual UNREALED_API TWeakObjectPtr< UEdMode > FModeToolkit::GetScriptableEditorMode () const final virtual
References GetScriptableEditorMode().
Referenced by GetScriptableEditorMode().
GetToolkitFName()
virtual UNREALED_API FName FModeToolkit::GetToolkitFName () const override virtual
Reimplemented in FFractureEditorModeToolkit.
GetToolkitName()
virtual FText FModeToolkit::GetToolkitName () const inline override virtual
Definition at line 120 of file BaseToolkit.h.
References GetBaseToolkitName().
GetToolkitToolTipText()
virtual FText FModeToolkit::GetToolkitToolTipText () const inline override virtual
Definition at line 121 of file BaseToolkit.h.
References GetBaseToolkitName().
GetToolPaletteDisplayName()
virtual FText FModeToolkit::GetToolPaletteDisplayName (FName Palette) const inline virtual
Parameters
PaletteIndex The index of the ToolPalette to build
Returns
the name of Tool Palette
Reimplemented in FFractureEditorModeToolkit.
Definition at line 140 of file BaseToolkit.h.
GetToolPaletteNames()
virtual void FModeToolkit::GetToolPaletteNames (TArray< FName > & PaletteNames) const inline virtual
Returns the number of Mode specific tabs in the mode toolbar.
Reimplemented in FFractureEditorModeToolkit.
Definition at line 134 of file BaseToolkit.h.
References GetToolPaletteNames().
Referenced by GetToolPaletteNames().
GetWorldCentricTabColorScale()
virtual UNREALED_API FLinearColor FModeToolkit::GetWorldCentricTabColorScale () const override virtual
GetWorldCentricTabPrefix()
virtual UNREALED_API FString FModeToolkit::GetWorldCentricTabPrefix () const override virtual
HasExclusiveToolPalettes()
virtual bool FModeToolkit::HasExclusiveToolPalettes () const inline virtual
Reimplemented in FFractureEditorModeToolkit.
Definition at line 143 of file BaseToolkit.h.
HasIntegratedToolPalettes()
virtual bool FModeToolkit::HasIntegratedToolPalettes () const inline virtual
Reimplemented in FFractureEditorModeToolkit.
Definition at line 146 of file BaseToolkit.h.
HasToolkitBuilder()
UNREALED_API bool FModeToolkit::HasToolkitBuilder () const protected
returns whether or not this FModeToolkit has a ToolkitBuilder defined
Init() [1/2]
virtual UNREALED_API void FModeToolkit::Init (const TSharedPtr< IToolkitHost > & InitToolkitHost) virtual
Initializes the mode toolkit.
Init() [2/2]
virtual UNREALED_API void FModeToolkit::Init (const TSharedPtr< IToolkitHost > & InitToolkitHost, TWeakObjectPtr< UEdMode > InOwningMode) virtual
Reimplemented in FFractureEditorModeToolkit.
InvokeUI()
virtual UNREALED_API void FModeToolkit::InvokeUI () virtual
Reimplemented in FFractureEditorModeToolkit.
IsAssetEditor()
virtual UNREALED_API bool FModeToolkit::IsAssetEditor () const override virtual
MakeModeToolbarTab()
UNREALED_API TSharedRef< SDockTab > FModeToolkit::MakeModeToolbarTab (const FSpawnTabArgs & Args) protected
Creates the mode toolbar tab if needed.
OnModeIDChanged()
UNREALED_API void FModeToolkit::OnModeIDChanged (const FEditorModeID & InID, bool bIsEntering) protected
OnPaletteChanged()
FOnPaletteChanged & FModeToolkit::OnPaletteChanged () inline
Definition at line 158 of file BaseToolkit.h.
References OnPaletteChangedDelegate.
OnToolEnded()
virtual UNREALED_API void FModeToolkit::OnToolEnded (UInteractiveToolManager * Manager, UInteractiveTool * Tool) protected virtual
OnToolPaletteChanged()
virtual void FModeToolkit::OnToolPaletteChanged (FName PaletteName) inline virtual
Reimplemented in FFractureEditorModeToolkit.
Definition at line 160 of file BaseToolkit.h.
OnToolStarted()
virtual UNREALED_API void FModeToolkit::OnToolStarted (UInteractiveToolManager * Manager, UInteractiveTool * Tool) protected virtual
RebuildModeToolBar()
virtual UNREALED_API void FModeToolkit::RebuildModeToolBar () protected virtual
RebuildModeToolPalette()
virtual UNREALED_API void FModeToolkit::RebuildModeToolPalette () virtual
Force the Mode Toolbar/Palette to be repopulated with the current ToolPaletteNames.
RegisterTabSpawners()
virtual UNREALED_API void FModeToolkit::RegisterTabSpawners (const TSharedRef< FTabManager > & TabManager) final virtual
RequestModeUITabs()
virtual UNREALED_API void FModeToolkit::RequestModeUITabs () protected virtual
Reimplemented in FFractureEditorModeToolkit.
SetCurrentPalette()
UNREALED_API void FModeToolkit::SetCurrentPalette (FName InName)
References InName.
SetModeSettingsObject()
UNREALED_API void FModeToolkit::SetModeSettingsObject (UObject * InSettingsObject)
SetModeUILayer()
virtual UNREALED_API void FModeToolkit::SetModeUILayer (const TSharedPtr< FAssetEditorModeUILayer > InLayer) override virtual
ShouldShowModeToolbar()
virtual UNREALED_API bool FModeToolkit::ShouldShowModeToolbar () const protected virtual
Whether or not the mode toolbar should be shown.
If any active modes generated a toolbar this method will return true
ShutdownUI()
virtual void FModeToolkit::ShutdownUI () inline virtual
Override this function to perform any UI cleanup before the ModeUILayer is no longer valid.
Note: If you had an existing delegate binding to ModeUILayer.Pin()->ToolkitHostShutdownUI() you will need to remove that in order for this method to be invoked. Overriding this method is preferred.
Definition at line 172 of file BaseToolkit.h.
SpawnOrUpdateModeToolbar()
UNREALED_API void FModeToolkit::SpawnOrUpdateModeToolbar () protected
UnregisterTabSpawners()
virtual UNREALED_API void FModeToolkit::UnregisterTabSpawners (const TSharedRef< FTabManager > & TabManager) final virtual
UpdatePrimaryModePanel()
UNREALED_API void FModeToolkit::UpdatePrimaryModePanel () protected
Field Documentation
ActiveToolBarRows
TArray<FEdModeToolbarRow> FModeToolkit::ActiveToolBarRows protected
All toolbar rows generated by active modes.
There will be one row per active mode that generates a toolbar
Definition at line 270 of file BaseToolkit.h.
bUsesToolkitBuilder
bool FModeToolkit::bUsesToolkitBuilder = false protected
a feature flag that can be set to true in order to make and use a ToolkitBuilder, if one is defined for a given mode.
Definition at line 274 of file BaseToolkit.h.
CreatedTabs
TArray<TSharedPtr<SDockTab> > FModeToolkit::CreatedTabs protected
Definition at line 253 of file BaseToolkit.h.
CurrentPaletteName
FName FModeToolkit::CurrentPaletteName protected
Definition at line 227 of file BaseToolkit.h.
DetailsView
TSharedPtr<IDetailsView> FModeToolkit::DetailsView protected
Definition at line 223 of file BaseToolkit.h.
InlineContentHolder
TSharedPtr<SBorder> FModeToolkit::InlineContentHolder protected
Inline content area for editor modes.
Definition at line 231 of file BaseToolkit.h.
ModeDetailsView
TSharedPtr<IDetailsView> FModeToolkit::ModeDetailsView protected
Definition at line 222 of file BaseToolkit.h.
ModeToolbarBox
TWeakPtr<SVerticalBox> FModeToolkit::ModeToolbarBox protected
The actual toolbar rows will be placed in this vertical box.
Definition at line 246 of file BaseToolkit.h.
ModeToolBarContainer
TSharedPtr<SBorder> FModeToolkit::ModeToolBarContainer protected
The container holding the mode toolbar.
Definition at line 234 of file BaseToolkit.h.
ModeToolbarPaletteSwitcher
TWeakPtr<SWidgetSwitcher> FModeToolkit::ModeToolbarPaletteSwitcher protected
The modes palette toolbar.
Definition at line 249 of file BaseToolkit.h.
ModeToolbarTab
TWeakPtr<SDockTab> FModeToolkit::ModeToolbarTab protected
The dock tab for any modes that generate a toolbar.
Definition at line 240 of file BaseToolkit.h.
ModeToolHeader
TSharedPtr<SBorder> FModeToolkit::ModeToolHeader protected
The active tool header area.
Definition at line 237 of file BaseToolkit.h.
ModeUILayer
TWeakPtr<FAssetEditorModeUILayer> FModeToolkit::ModeUILayer protected
Definition at line 251 of file BaseToolkit.h.
OnPaletteChangedDelegate
FOnPaletteChanged FModeToolkit::OnPaletteChangedDelegate protected
Definition at line 228 of file BaseToolkit.h.
Referenced by OnPaletteChanged().
OwningEditorMode
TWeakObjectPtr<UEdMode> FModeToolkit::OwningEditorMode protected
Definition at line 225 of file BaseToolkit.h.
PrimaryTab
TWeakPtr<SDockTab> FModeToolkit::PrimaryTab protected
Definition at line 238 of file BaseToolkit.h.
PrimaryTabInfo
FMinorTabConfig FModeToolkit::PrimaryTabInfo protected
Definition at line 241 of file BaseToolkit.h.
ToolbarInfo
FMinorTabConfig FModeToolkit::ToolbarInfo protected
Definition at line 242 of file BaseToolkit.h.
ToolkitBuilder
TSharedPtr<FToolkitBuilder> FModeToolkit::ToolkitBuilder protected
The FToolkitBuilder which will build the UI for this mode, if defined.
Definition at line 277 of file BaseToolkit.h.
ToolkitSections
TSharedPtr<FToolkitSections> FModeToolkit::ToolkitSections protected
The sections of the toolkit, defined for the ToolkitBuilder (if present)
Definition at line 283 of file BaseToolkit.h.
ToolkitWidget
TSharedPtr<SWidget> FModeToolkit::ToolkitWidget protected
Definition at line 221 of file BaseToolkit.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Toolkits/BaseToolkit.h