Unreal Engine 5.6 C++ API: Metasound::TArrayNumOperator< ArrayType > Class Template Reference
Metasound::TArrayNumOperator< ArrayType > Class Template Reference
TArrayNumOperator gets the number of elements in an Array.
#include "MetasoundArrayNodes.h"
Public Types
using FArrayDataReadReference = TDataReadReference<ArrayType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArrayNumOperator (FArrayDataReadReference InArray)
virtual ~TArrayNumOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
virtual FDataReferenceCollection GetInputs () const override
virtual FDataReferenceCollection GetOutputs () const override
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArrayNumOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Attributes
FArrayDataReadReference Array
TDataWriteReference< int32 > Num
Detailed Description
template<typename ArrayType>
class Metasound::TArrayNumOperator< ArrayType >
TArrayNumOperator gets the number of elements in an Array.
The operator uses the FNodeFacade and defines the vertex, metadata and vertex interface statically on the operator class.
Definition at line 79 of file MetasoundArrayNodes.h.
Member Typedef Documentation
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArrayNumOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 82 of file MetasoundArrayNodes.h.
Constructor & Destructor Documentation
TArrayNumOperator()
template<typename ArrayType> Metasound::TArrayNumOperator< ArrayType >::TArrayNumOperator (FArrayDataReadReference InArray) inline
Definition at line 137 of file MetasoundArrayNodes.h.
References Array, and Num.
~TArrayNumOperator()
template<typename ArrayType> virtual Metasound::TArrayNumOperator< ArrayType >::~TArrayNumOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArrayNumOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 159 of file MetasoundArrayNodes.h.
References Array, Metasound::FInputVertexInterfaceData::BindReadVertex(), and METASOUND_GET_PARAM_NAME.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArrayNumOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 165 of file MetasoundArrayNodes.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), METASOUND_GET_PARAM_NAME, and Num.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArrayNumOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 124 of file MetasoundArrayNodes.h.
References Array, Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, and Metasound::FBuildOperatorParams::OperatorSettings.
Execute()
template<typename ArrayType> void Metasound::TArrayNumOperator< ArrayType >::Execute () inline
Definition at line 172 of file MetasoundArrayNodes.h.
References Array, and Num.
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArrayNumOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 85 of file MetasoundArrayNodes.h.
References METASOUND_GET_PARAM_NAME_AND_METADATA.
Referenced by GetNodeInfo().
GetInputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayNumOperator< ArrayType >::GetInputs () const inline override virtual
Definition at line 147 of file MetasoundArrayNodes.h.
References checkNoEntry.
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArrayNumOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 101 of file MetasoundArrayNodes.h.
References TArray< InElementType, InAllocatorType >::Append(), Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metasound::FNodeClassMetadata::Keywords, Metadata, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, and TEXT.
GetOutputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArrayNumOperator< ArrayType >::GetOutputs () const inline override virtual
Definition at line 153 of file MetasoundArrayNodes.h.
References checkNoEntry.
Reset()
template<typename ArrayType> void Metasound::TArrayNumOperator< ArrayType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 177 of file MetasoundArrayNodes.h.
References Execute.
Field Documentation
Array
template<typename ArrayType> FArrayDataReadReference Metasound::TArrayNumOperator< ArrayType >::Array private
Definition at line 184 of file MetasoundArrayNodes.h.
Referenced by TArrayNumOperator(), BindInputs(), CreateOperator(), and Execute().
Num
template<typename ArrayType> TDataWriteReference<int32> Metasound::TArrayNumOperator< ArrayType >::Num private
Definition at line 185 of file MetasoundArrayNodes.h.
Referenced by TArrayNumOperator(), BindOutputs(), and Execute().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundArrayNodes.h