Unreal Engine 5.6 C++ API: FPageAllocator Class Reference
FPageAllocator Class Reference
#include "MemStack.h"
Public Types
enum { PageSize = 64 * 1024 , SmallPageSize = 1024-16 }
typedef TLockFreeFixedSizeAllocator< PageSize, PLATFORM_CACHE_LINE_SIZE, FThreadSafeCounter > TPageAllocator
Public Member Functions
~FPageAllocator ()
void * Alloc (int32 Alignment=MIN_ALIGNMENT)
void * AllocSmall ()
uint64 BytesFree ()
uint64 BytesUsed ()
void Free (void *Mem)
void FreeSmall (void *Mem)
void LatchProtectedMode ()
Static Public Member Functions
static FPageAllocator & Get ()
Private Member Functions
FPageAllocator ()
Static Private Member Functions
static FPageAllocator & Construct ()
Private Attributes
TPageAllocator TheAllocator
Static Private Attributes
static FPageAllocator * Instance
Detailed Description
Definition at line 35 of file MemStack.h.
Member Typedef Documentation
TPageAllocator
typedef TLockFreeFixedSizeAllocator<PageSize, PLATFORM_CACHE_LINE_SIZE, FThreadSafeCounter> FPageAllocator::TPageAllocator
Definition at line 46 of file MemStack.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PageSize
SmallPageSize
Definition at line 38 of file MemStack.h.
Constructor & Destructor Documentation
~FPageAllocator()
FPageAllocator::~FPageAllocator ()
FPageAllocator()
FPageAllocator::FPageAllocator () private
Referenced by Construct(), and Get().
Member Function Documentation
Alloc()
void * FPageAllocator::Alloc (int32 Alignment = MIN_ALIGNMENT)
References MIN_ALIGNMENT.
Referenced by TBlockAllocationLockFreeCache< BlockSize, FAlignedAllocator >::Malloc().
AllocSmall()
void * FPageAllocator::AllocSmall ()
BytesFree()
uint64 FPageAllocator::BytesFree ()
BytesUsed()
uint64 FPageAllocator::BytesUsed ()
Construct()
FPageAllocator & FPageAllocator::Construct () static private
References FPageAllocator().
Free()
void FPageAllocator::Free (void * Mem)
Referenced by TBlockAllocationLockFreeCache< BlockSize, FAlignedAllocator >::Free().
FreeSmall()
void FPageAllocator::FreeSmall (void * Mem)
Get()
FPageAllocator & FPageAllocator::Get () static
References FPageAllocator().
Referenced by TBlockAllocationLockFreeCache< BlockSize, FAlignedAllocator >::Free(), and TBlockAllocationLockFreeCache< BlockSize, FAlignedAllocator >::Malloc().
LatchProtectedMode()
void FPageAllocator::LatchProtectedMode ()
Field Documentation
Instance
FPageAllocator* FPageAllocator::Instance static private
Definition at line 61 of file MemStack.h.
TheAllocator
TPageAllocator FPageAllocator::TheAllocator private
Definition at line 68 of file MemStack.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/MemStack.h