Unreal Engine 5.6 C++ API: FSkeletalMeshUpdateHandle Class Reference
FSkeletalMeshUpdateHandle Class Reference
#include "SkeletalMeshUpdater.h"
Public Member Functions
FSkeletalMeshUpdateHandle ()=default
FSkeletalMeshUpdateHandle (FSkeletalMeshUpdateHandle &&RHS)
~FSkeletalMeshUpdateHandle ()
bool IsValid () const
FSkeletalMeshUpdateHandle & operator= (FSkeletalMeshUpdateHandle &&RHS)
void Release ()
template<typename SkeletalMeshDynamicDataType>
bool Update (SkeletalMeshDynamicDataType *MeshDynamicData)
Private Attributes
FSkeletalMeshUpdateChannel * Channel
friend FSkeletalMeshUpdateChannel
uint32 Index = INDEX_NONE
Detailed Description
Definition at line 209 of file SkeletalMeshUpdater.h.
Constructor & Destructor Documentation
FSkeletalMeshUpdateHandle() [1/2]
FSkeletalMeshUpdateHandle::FSkeletalMeshUpdateHandle () default
Referenced by FSkeletalMeshUpdateHandle(), and operator=().
FSkeletalMeshUpdateHandle() [2/2]
FSkeletalMeshUpdateHandle::FSkeletalMeshUpdateHandle (FSkeletalMeshUpdateHandle && RHS) inline
Definition at line 214 of file SkeletalMeshUpdater.h.
References FSkeletalMeshUpdateHandle(), Channel, and Index.
~FSkeletalMeshUpdateHandle()
FSkeletalMeshUpdateHandle::~FSkeletalMeshUpdateHandle () inline
Definition at line 230 of file SkeletalMeshUpdater.h.
References Channel, checkf, and TEXT.
Member Function Documentation
IsValid()
bool FSkeletalMeshUpdateHandle::IsValid () const inline
Definition at line 235 of file SkeletalMeshUpdater.h.
References Channel.
operator=()
FSkeletalMeshUpdateHandle & FSkeletalMeshUpdateHandle::operator= (FSkeletalMeshUpdateHandle && RHS) inline
Definition at line 221 of file SkeletalMeshUpdater.h.
References FSkeletalMeshUpdateHandle(), Channel, Index, and INDEX_NONE.
Release()
void FSkeletalMeshUpdateHandle::Release ()
Update()
template<typename SkeletalMeshDynamicDataType> bool FSkeletalMeshUpdateHandle::Update (SkeletalMeshDynamicDataType * MeshDynamicData) nodiscard
Field Documentation
Channel
FSkeletalMeshUpdateChannel* FSkeletalMeshUpdateHandle::Channel private
Definition at line 246 of file SkeletalMeshUpdater.h.
Referenced by FSkeletalMeshUpdateHandle(), ~FSkeletalMeshUpdateHandle(), IsValid(), and operator=().
FSkeletalMeshUpdateChannel
friend FSkeletalMeshUpdateHandle::FSkeletalMeshUpdateChannel private
Definition at line 249 of file SkeletalMeshUpdater.h.
Index
uint32 FSkeletalMeshUpdateHandle::Index = INDEX_NONE private
Definition at line 247 of file SkeletalMeshUpdater.h.
Referenced by FSkeletalMeshUpdateHandle(), and operator=().
The documentation for this class was generated from the following file:
Runtime/Engine/Internal/SkeletalMeshUpdater.h