Unreal Engine 5.6 C++ API: FGameModeInfoCustomizer Class Reference
FGameModeInfoCustomizer Class Reference
Class to help customize a GameMode class picker, to show settings 'withing' GameMode.
#include "GameModeInfoCustomizer.h"
Public Member Functions
FGameModeInfoCustomizer (UObject *InOwningObject, FName InGameModePropertyName)
bool AllowModifyGameMode () const
Are we allowed to modify the currently selected GameMode.
bool CanBrowseDefaultClass (FName ClassPropertyName) const
bool CanBrowseGameMode () const
bool CanSyncToClass (const UClass *Class) const
TSharedRef< SWidget > CreateGameModePropertyLabelWidget (FName PropertyName)
Create widget for the name of a default class property.
void CustomizeGameModeDefaultClass (IDetailGroup &Group, FName DefaultClassPropertyName)
Create widget fo modifying a default class within the current GameMode.
void CustomizeGameModeSetting (IDetailLayoutBuilder &LayoutBuilder, IDetailCategoryBuilder &CategoryBuilder)
Add special customization for the GameMode setting.
AGameModeBase * GetCurrentGameModeCDO () const
Get the CDO from the currently set GameMode class.
const UClass * GetCurrentGameModeClass () const
Get the currently set GameMode class.
void OnBrowseDefaultClassClicked (FName ClassPropertyName)
void OnBrowseGameModeClicked ()
void OnClickNewGameMode ()
const UClass * OnGetDefaultClass (FName ClassPropertyName) const
Find the current default class by property name.
void OnMakeNewDefaultClassClicked (FName ClassPropertyName)
void OnMakeSelectedDefaultClassClicked (FName ClassPropertyName)
void OnSetDefaultClass (const UClass *NewDefaultClass, FName ClassPropertyName)
Set a new default class by property name.
void OnUseSelectedGameModeClicked ()
void SetCurrentGameModeClass (const UClass *NewGameModeClass)
void SyncBrowserToClass (const UClass *Class)
Public Member Functions inherited from TSharedFromThis< FGameModeInfoCustomizer >
TSharedRef< FGameModeInfoCustomizer, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FGameModeInfoCustomizer, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Attributes
TWeakObjectPtr< UClass > CachedGameModeClass
Cached class pointer from the DefaultGameModeClassHandle.
TSharedPtr< IPropertyHandle > DefaultGameModeClassHandle
Handle to the DefaultGameMode property.
FName GameModePropertyName
Name of GameMode property inside OwningObject.
TWeakObjectPtr< UObject > OwningObject
Object that owns the pointer to the GameMode we want to customize.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FGameModeInfoCustomizer >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FGameModeInfoCustomizer >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Class to help customize a GameMode class picker, to show settings 'withing' GameMode.
Definition at line 35 of file GameModeInfoCustomizer.h.
Constructor & Destructor Documentation
FGameModeInfoCustomizer()
FGameModeInfoCustomizer::FGameModeInfoCustomizer (UObject * InOwningObject, FName InGameModePropertyName) inline
Definition at line 38 of file GameModeInfoCustomizer.h.
References CachedGameModeClass, GameModePropertyName, and OwningObject.
Member Function Documentation
AllowModifyGameMode()
bool FGameModeInfoCustomizer::AllowModifyGameMode () const inline
Are we allowed to modify the currently selected GameMode.
Definition at line 350 of file GameModeInfoCustomizer.h.
References Cast(), and GetCurrentGameModeClass().
Referenced by CustomizeGameModeDefaultClass(), and OnSetDefaultClass().
CanBrowseDefaultClass()
bool FGameModeInfoCustomizer::CanBrowseDefaultClass (FName ClassPropertyName) const inline
Definition at line 262 of file GameModeInfoCustomizer.h.
References CanSyncToClass(), and OnGetDefaultClass().
CanBrowseGameMode()
bool FGameModeInfoCustomizer::CanBrowseGameMode () const inline
Definition at line 298 of file GameModeInfoCustomizer.h.
References CanSyncToClass(), and GetCurrentGameModeClass().
CanSyncToClass()
bool FGameModeInfoCustomizer::CanSyncToClass (const UClass * Class) const inline
Definition at line 308 of file GameModeInfoCustomizer.h.
References Class.
Referenced by CanBrowseDefaultClass(), CanBrowseGameMode(), and SyncBrowserToClass().
CreateGameModePropertyLabelWidget()
TSharedRef< SWidget > FGameModeInfoCustomizer::CreateGameModePropertyLabelWidget (FName PropertyName) inline
Create widget for the name of a default class property.
Definition at line 46 of file GameModeInfoCustomizer.h.
References FindFieldChecked(), FText::FromString(), IDetailLayoutBuilder::GetDetailFont(), FField::GetName(), FName::NameToDisplayString(), PropertyName, SNew, and TEXT.
Referenced by CustomizeGameModeDefaultClass().
CustomizeGameModeDefaultClass()
void FGameModeInfoCustomizer::CustomizeGameModeDefaultClass (IDetailGroup & Group, FName DefaultClassPropertyName) inline
Create widget fo modifying a default class within the current GameMode.
Definition at line 65 of file GameModeInfoCustomizer.h.
References AllowModifyGameMode(), CreateGameModePropertyLabelWidget(), FindFieldChecked(), Group, PropertyCustomizationHelpers::MakeBrowseButton(), PropertyCustomizationHelpers::MakeNewBlueprintButton(), PropertyCustomizationHelpers::MakeUseSelectedButton(), OnBrowseDefaultClassClicked(), OnGetDefaultClass(), OnMakeNewDefaultClassClicked(), OnMakeSelectedDefaultClassClicked(), OnSetDefaultClass(), FProperty::PropertyFlags, SHorizontalBox::Slot(), and SNew.
Referenced by CustomizeGameModeSetting().
CustomizeGameModeSetting()
void FGameModeInfoCustomizer::CustomizeGameModeSetting (IDetailLayoutBuilder & LayoutBuilder, IDetailCategoryBuilder & CategoryBuilder) inline
Add special customization for the GameMode setting.
Definition at line 119 of file GameModeInfoCustomizer.h.
References IDetailCategoryBuilder::AddGroup(), IDetailCategoryBuilder::AddProperty(), check, CustomizeGameModeDefaultClass(), IDetailPropertyRow::CustomWidget(), DefaultGameModeClassHandle, GameModePropertyName, GET_MEMBER_NAME_CHECKED, GetCurrentGameModeClass(), IDetailLayoutBuilder::GetProperty(), Group, LOCTEXT, PropertyCustomizationHelpers::MakeBrowseButton(), PropertyCustomizationHelpers::MakeNewBlueprintButton(), PropertyCustomizationHelpers::MakeUseSelectedButton(), FDetailWidgetDecl::MaxDesiredWidth(), FDetailWidgetRow::NameContent(), OnBrowseGameModeClicked(), OnClickNewGameMode(), OnUseSelectedGameModeClicked(), SetCurrentGameModeClass(), IDetailPropertyRow::ShowPropertyButtons(), SHorizontalBox::Slot(), SNew, and TEXT.
GetCurrentGameModeCDO()
AGameModeBase * FGameModeInfoCustomizer::GetCurrentGameModeCDO () const inline
Get the CDO from the currently set GameMode class.
Definition at line 217 of file GameModeInfoCustomizer.h.
References GetCurrentGameModeClass(), and UClass::GetDefaultObject().
Referenced by OnGetDefaultClass(), and OnSetDefaultClass().
GetCurrentGameModeClass()
const UClass * FGameModeInfoCustomizer::GetCurrentGameModeClass () const inline
Get the currently set GameMode class.
Definition at line 190 of file GameModeInfoCustomizer.h.
References CachedGameModeClass, DefaultGameModeClassHandle, FEditorClassUtils::GetClassFromString(), UObjectBaseUtility::GetPathName(), GIsSavingPackage, MakeWeakObjectPtr(), and ConstructorHelpers::StripObjectClass().
Referenced by AllowModifyGameMode(), CanBrowseGameMode(), CustomizeGameModeSetting(), GetCurrentGameModeCDO(), OnBrowseGameModeClicked(), OnGetDefaultClass(), and OnSetDefaultClass().
OnBrowseDefaultClassClicked()
void FGameModeInfoCustomizer::OnBrowseDefaultClassClicked (FName ClassPropertyName) inline
Definition at line 267 of file GameModeInfoCustomizer.h.
References OnGetDefaultClass(), and SyncBrowserToClass().
Referenced by CustomizeGameModeDefaultClass().
OnBrowseGameModeClicked()
void FGameModeInfoCustomizer::OnBrowseGameModeClicked () inline
Definition at line 303 of file GameModeInfoCustomizer.h.
References GetCurrentGameModeClass(), and SyncBrowserToClass().
Referenced by CustomizeGameModeSetting().
OnClickNewGameMode()
void FGameModeInfoCustomizer::OnClickNewGameMode () inline
Definition at line 338 of file GameModeInfoCustomizer.h.
References DefaultGameModeClassHandle, LOCTEXT, and TEXT.
Referenced by CustomizeGameModeSetting().
OnGetDefaultClass()
const UClass * FGameModeInfoCustomizer::OnGetDefaultClass (FName ClassPropertyName) const inline
Find the current default class by property name.
Definition at line 231 of file GameModeInfoCustomizer.h.
References FProperty::ContainerPtrToValuePtr(), FindFieldChecked(), GetCurrentGameModeCDO(), GetCurrentGameModeClass(), and FObjectProperty::GetObjectPropertyValue().
Referenced by CanBrowseDefaultClass(), CustomizeGameModeDefaultClass(), and OnBrowseDefaultClassClicked().
OnMakeNewDefaultClassClicked()
void FGameModeInfoCustomizer::OnMakeNewDefaultClassClicked (FName ClassPropertyName) inline
Definition at line 272 of file GameModeInfoCustomizer.h.
References FindFieldChecked(), GEditor, FField::GetName(), LOCTEXT, OnSetDefaultClass(), and TEXT.
Referenced by CustomizeGameModeDefaultClass().
OnMakeSelectedDefaultClassClicked()
void FGameModeInfoCustomizer::OnMakeSelectedDefaultClassClicked (FName ClassPropertyName) inline
Definition at line 286 of file GameModeInfoCustomizer.h.
References FindFieldChecked(), GEditor, FEditorDelegates::LoadSelectedAssetsIfNeeded, and OnSetDefaultClass().
Referenced by CustomizeGameModeDefaultClass().
OnSetDefaultClass()
void FGameModeInfoCustomizer::OnSetDefaultClass (const UClass * NewDefaultClass, FName ClassPropertyName) inline
Set a new default class by property name.
Definition at line 244 of file GameModeInfoCustomizer.h.
References AllowModifyGameMode(), Cast(), FProperty::ContainerPtrToValuePtr(), FindFieldChecked(), GetCurrentGameModeCDO(), GetCurrentGameModeClass(), and FBlueprintEditorUtils::MarkBlueprintAsModified().
Referenced by CustomizeGameModeDefaultClass(), OnMakeNewDefaultClassClicked(), and OnMakeSelectedDefaultClassClicked().
OnUseSelectedGameModeClicked()
void FGameModeInfoCustomizer::OnUseSelectedGameModeClicked () inline
Definition at line 327 of file GameModeInfoCustomizer.h.
References DefaultGameModeClassHandle, GEditor, UObjectBaseUtility::GetPathName(), and FEditorDelegates::LoadSelectedAssetsIfNeeded.
Referenced by CustomizeGameModeSetting().
SetCurrentGameModeClass()
void FGameModeInfoCustomizer::SetCurrentGameModeClass (const UClass * NewGameModeClass) inline
Definition at line 208 of file GameModeInfoCustomizer.h.
References CachedGameModeClass, DefaultGameModeClassHandle, UObjectBaseUtility::GetPathName(), MakeWeakObjectPtr(), FPropertyAccess::Success, and TEXT.
Referenced by CustomizeGameModeSetting().
SyncBrowserToClass()
void FGameModeInfoCustomizer::SyncBrowserToClass (const UClass * Class) inline
Definition at line 313 of file GameModeInfoCustomizer.h.
References TArray< InElementType, InAllocatorType >::Add(), CanSyncToClass(), Cast(), Class, ensure, and GEditor.
Referenced by OnBrowseDefaultClassClicked(), and OnBrowseGameModeClicked().
Field Documentation
CachedGameModeClass
TWeakObjectPtr<UClass> FGameModeInfoCustomizer::CachedGameModeClass mutable private
Cached class pointer from the DefaultGameModeClassHandle.
Definition at line 365 of file GameModeInfoCustomizer.h.
Referenced by FGameModeInfoCustomizer(), GetCurrentGameModeClass(), and SetCurrentGameModeClass().
DefaultGameModeClassHandle
TSharedPtr<IPropertyHandle> FGameModeInfoCustomizer::DefaultGameModeClassHandle private
Handle to the DefaultGameMode property.
Definition at line 363 of file GameModeInfoCustomizer.h.
Referenced by CustomizeGameModeSetting(), GetCurrentGameModeClass(), OnClickNewGameMode(), OnUseSelectedGameModeClicked(), and SetCurrentGameModeClass().
GameModePropertyName
FName FGameModeInfoCustomizer::GameModePropertyName private
Name of GameMode property inside OwningObject.
Definition at line 361 of file GameModeInfoCustomizer.h.
Referenced by FGameModeInfoCustomizer(), and CustomizeGameModeSetting().
OwningObject
TWeakObjectPtr<UObject> FGameModeInfoCustomizer::OwningObject private
Object that owns the pointer to the GameMode we want to customize.
Definition at line 359 of file GameModeInfoCustomizer.h.
Referenced by FGameModeInfoCustomizer().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/GameModeInfoCustomizer.h