Unreal Engine 5.6 C++ API: Metasound::Frontend::FGraphAnalyzerAddress Class Reference
Metasound::Frontend::FGraphAnalyzerAddress Class Reference
#include "MetasoundFrontendGraphAnalyzer.h"
Public Member Functions
FGraphAnalyzerAddress (uint64 InInstanceID)
virtual ~FGraphAnalyzerAddress ()=default
virtual TUniquePtr< FTransmissionAddress > Clone () const override
Clone the address.
virtual FName GetAddressType () const override
Return the type of address.
virtual FName GetDataType () const override
Return the data type.
virtual uint32 GetHash () const override
Create a hash of the address.
virtual bool IsEqual (const FTransmissionAddress &InOther) const override
Determine if the given address is equal to this address.
virtual FString ToString () const override
Return a string representation of the address for debugging.
Public Member Functions inherited from Metasound::FTransmissionAddress
FTransmissionAddress ()=default
virtual ~FTransmissionAddress ()=default
METASOUNDFRONTEND_API bool operator!= (const FTransmissionAddress &InOther) const
METASOUNDFRONTEND_API bool operator== (const FTransmissionAddress &InOther) const
Private Attributes
uint64 InstanceID = INDEX_NONE
Detailed Description
Definition at line 20 of file MetasoundFrontendGraphAnalyzer.h.
Constructor & Destructor Documentation
FGraphAnalyzerAddress()
Metasound::Frontend::FGraphAnalyzerAddress::FGraphAnalyzerAddress (uint64 InInstanceID) inline
Definition at line 25 of file MetasoundFrontendGraphAnalyzer.h.
References InstanceID.
Referenced by Clone(), and IsEqual().
~FGraphAnalyzerAddress()
virtual Metasound::Frontend::FGraphAnalyzerAddress::~FGraphAnalyzerAddress () virtual default
Member Function Documentation
Clone()
virtual TUniquePtr< FTransmissionAddress > Metasound::Frontend::FGraphAnalyzerAddress::Clone () const inline override virtual
Clone the address.
Implements Metasound::FTransmissionAddress.
Definition at line 42 of file MetasoundFrontendGraphAnalyzer.h.
References FGraphAnalyzerAddress().
GetAddressType()
virtual FName Metasound::Frontend::FGraphAnalyzerAddress::GetAddressType () const inline override virtual
Return the type of address.
The AddressType must be unique per a subclass of FTransmissionAddress as it is used to determine the validity of a static_cast from FTransmissionAddress to the derived address type.
Implements Metasound::FTransmissionAddress.
Definition at line 32 of file MetasoundFrontendGraphAnalyzer.h.
Referenced by IsEqual(), and ToString().
GetDataType()
virtual FName Metasound::Frontend::FGraphAnalyzerAddress::GetDataType () const inline override virtual
Return the data type.
Implements Metasound::FTransmissionAddress.
Definition at line 37 of file MetasoundFrontendGraphAnalyzer.h.
References Metasound::GetMetasoundDataTypeName().
GetHash()
virtual uint32 Metasound::Frontend::FGraphAnalyzerAddress::GetHash () const inline override virtual
Create a hash of the address.
Implements Metasound::FTransmissionAddress.
Definition at line 52 of file MetasoundFrontendGraphAnalyzer.h.
References InstanceID.
IsEqual()
virtual bool Metasound::Frontend::FGraphAnalyzerAddress::IsEqual (const FTransmissionAddress & InOther) const inline override virtual
Determine if the given address is equal to this address.
Implements Metasound::FTransmissionAddress.
Definition at line 57 of file MetasoundFrontendGraphAnalyzer.h.
References FGraphAnalyzerAddress(), Metasound::FTransmissionAddress::FTransmissionAddress(), GetAddressType(), Metasound::FTransmissionAddress::GetAddressType(), and InstanceID.
ToString()
virtual FString Metasound::Frontend::FGraphAnalyzerAddress::ToString () const inline override virtual
Return a string representation of the address for debugging.
Implements Metasound::FTransmissionAddress.
Definition at line 47 of file MetasoundFrontendGraphAnalyzer.h.
References GetAddressType(), InstanceID, METASOUND_ANALYZER_PATH_SEPARATOR, TEXT, and ToString().
Referenced by ToString().
Field Documentation
InstanceID
uint64 Metasound::Frontend::FGraphAnalyzerAddress::InstanceID = INDEX_NONE private
Definition at line 22 of file MetasoundFrontendGraphAnalyzer.h.
Referenced by FGraphAnalyzerAddress(), GetHash(), IsEqual(), and ToString().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/Analysis/MetasoundFrontendGraphAnalyzer.h