Unreal Engine 5.6 C++ API: FSceneViewExtensions Class Reference
FSceneViewExtensions Class Reference
Repository of all registered scene view extensions.
#include "SceneViewExtension.h"
Public Member Functions
const TArray< FSceneViewExtensionRef > GatherActiveExtensions (const FSceneViewExtensionContext &InContext) const
Gathers all ViewExtensions that want to be active in a given context (.
Static Public Member Functions
static void ForEachActiveViewExtension (const TArray< TWeakPtr< ISceneViewExtension, ESPMode::ThreadSafe > > &InExtensions, const FSceneViewExtensionContext &InContext, const TFunctionRef< void(const FSceneViewExtensionRef &)> &Func)
Executes a function on each view extension which is active in a given context.
template<typename ExtensionType, typename... TArgs>
static TSharedRef< ExtensionType, ESPMode::ThreadSafe > NewExtension (TArgs &&... Args)
Create a new extension of type ExtensionType.
Static Private Member Functions
static void RegisterExtension (const FSceneViewExtensionRef &RegisterMe)
Private Attributes
TArray< TWeakPtr< ISceneViewExtension, ESPMode::ThreadSafe > > KnownExtensions
Friends
class FSceneViewExtensionBase
Detailed Description
Repository of all registered scene view extensions.
Definition at line 295 of file SceneViewExtension.h.
Member Function Documentation
ForEachActiveViewExtension()
void FSceneViewExtensions::ForEachActiveViewExtension (const TArray< TWeakPtr< ISceneViewExtension, ESPMode::ThreadSafe > > & InExtensions, const FSceneViewExtensionContext & InContext, const TFunctionRef< void(const FSceneViewExtensionRef &)> & Func) static
Executes a function on each view extension which is active in a given context.
GatherActiveExtensions()
const TArray< FSceneViewExtensionRef > FSceneViewExtensions::GatherActiveExtensions (const FSceneViewExtensionContext & InContext) const
Gathers all ViewExtensions that want to be active in a given context (.
See also
ISceneViewExtension::IsActiveThisFrame()). The list is sorted by priority (
ISceneViewExtension::GetPriority())
NewExtension()
template<typename ExtensionType, typename... TArgs> TSharedRef< ExtensionType, ESPMode::ThreadSafe > FSceneViewExtensions::NewExtension (TArgs &&... Args) inline static
Create a new extension of type ExtensionType.
Definition at line 304 of file SceneViewExtension.h.
References Forward(), MakeShareable(), NewExtension(), and RegisterExtension().
Referenced by NewExtension().
RegisterExtension()
void FSceneViewExtensions::RegisterExtension (const FSceneViewExtensionRef & RegisterMe) static private
Referenced by NewExtension().
Friends And Related Symbol Documentation
FSceneViewExtensionBase
friend class FSceneViewExtensionBase friend
Definition at line 297 of file SceneViewExtension.h.
References FSceneViewExtensionBase.
Referenced by FSceneViewExtensionBase.
Field Documentation
KnownExtensions
TArray< TWeakPtr<ISceneViewExtension, ESPMode::ThreadSafe> > FSceneViewExtensions::KnownExtensions private
Definition at line 327 of file SceneViewExtension.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneViewExtension.h