Unreal Engine 5.6 C++ API: FMaterialFunctionCompileState Class Reference
FMaterialFunctionCompileState Class Reference
Function specific compiler state.
#include "MaterialShared.h"
Public Member Functions
FMaterialFunctionCompileState (UMaterialExpressionMaterialFunctionCall *InFunctionCall)
~FMaterialFunctionCompileState ()
void ClearSharedFunctionStates ()
FMaterialFunctionCompileState * FindOrAddSharedFunctionState (FMaterialExpressionKey &ExpressionKey, class UMaterialExpressionMaterialFunctionCall *SharedFunctionCall)
void Reset ()
Data Fields
TMap< UMaterialExpression *, int32 > ExecExpressionCodeMap
TMap< FMaterialExpressionKey, int32 > ExpressionCodeMap
A map from material expression to the index into CodeChunks of the code for the material expression.
TArray< FMaterialExpressionKey > ExpressionStack
class UMaterialExpressionMaterialFunctionCall * FunctionCall
Private Attributes
TMap< FMaterialExpressionKey, FMaterialFunctionCompileState * > SharedFunctionStates
Cache of MaterialFunctionOutput CodeChunks.
Detailed Description
Function specific compiler state.
Definition at line 1902 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterialFunctionCompileState()
FMaterialFunctionCompileState::FMaterialFunctionCompileState (UMaterialExpressionMaterialFunctionCall * InFunctionCall) inline explicit
Definition at line 1905 of file MaterialShared.h.
References FunctionCall.
Referenced by ClearSharedFunctionStates(), and FindOrAddSharedFunctionState().
~FMaterialFunctionCompileState()
FMaterialFunctionCompileState::~FMaterialFunctionCompileState () inline
Definition at line 1909 of file MaterialShared.h.
References ClearSharedFunctionStates().
Member Function Documentation
ClearSharedFunctionStates()
void FMaterialFunctionCompileState::ClearSharedFunctionStates () inline
Definition at line 1923 of file MaterialShared.h.
References FMaterialFunctionCompileState(), ClearSharedFunctionStates(), and SharedFunctionStates.
Referenced by ~FMaterialFunctionCompileState(), ClearSharedFunctionStates(), and Reset().
FindOrAddSharedFunctionState()
FMaterialFunctionCompileState * FMaterialFunctionCompileState::FindOrAddSharedFunctionState (FMaterialExpressionKey & ExpressionKey, class UMaterialExpressionMaterialFunctionCall * SharedFunctionCall) inline
Definition at line 1914 of file MaterialShared.h.
References FMaterialFunctionCompileState(), and SharedFunctionStates.
Reset()
void FMaterialFunctionCompileState::Reset () inline
Definition at line 1934 of file MaterialShared.h.
References ClearSharedFunctionStates(), ExpressionCodeMap, and ExpressionStack.
Field Documentation
ExecExpressionCodeMap
TMap<UMaterialExpression*, int32> FMaterialFunctionCompileState::ExecExpressionCodeMap
Definition at line 1949 of file MaterialShared.h.
ExpressionCodeMap
TMap<FMaterialExpressionKey,int32> FMaterialFunctionCompileState::ExpressionCodeMap
A map from material expression to the index into CodeChunks of the code for the material expression.
Definition at line 1947 of file MaterialShared.h.
Referenced by Reset().
ExpressionStack
TArray<FMaterialExpressionKey> FMaterialFunctionCompileState::ExpressionStack
Definition at line 1944 of file MaterialShared.h.
Referenced by Reset().
FunctionCall
class UMaterialExpressionMaterialFunctionCall* FMaterialFunctionCompileState::FunctionCall
Definition at line 1941 of file MaterialShared.h.
Referenced by FMaterialFunctionCompileState().
SharedFunctionStates
TMap<FMaterialExpressionKey, FMaterialFunctionCompileState*> FMaterialFunctionCompileState::SharedFunctionStates private
Cache of MaterialFunctionOutput CodeChunks.
Allows for further reuse than just the ExpressionCodeMap
Definition at line 1953 of file MaterialShared.h.
Referenced by ClearSharedFunctionStates(), and FindOrAddSharedFunctionState().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialShared.h