Unreal Engine 5.6 C++ API: ABrush Class Reference
ABrush Class Reference
#include "Brush.h"
Public Member Functions
virtual bool CanDeleteSelectedActor (FText &OutReason) const override
bool CanEverAffectBSP () const
virtual bool CanReplaceSelectedActor (FText &OutReason) const override
virtual void CheckForErrors () override
FORCEINLINE void ClearNotForClientOrServer ()
Indicate that brush need should be loaded on client or servers.
virtual void CopyPosRotScaleFrom (ABrush *Other)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnBrushRegistered, ABrush *)
Delegate used for notifications when PostRegisterAllComponents is called for a Brush.
virtual void Destroyed () override
class UBrushComponent * GetBrushComponent () const
Returns BrushComponent subobject.
virtual FName GetCustomIconName () const override
virtual FColor GetWireColor () const
Figures out the best color to use for this brushes wireframe drawing.
virtual void InitPosRotScale ()
virtual bool IsActorLabelEditable () const override
virtual bool IsBrushShape () const
virtual bool IsComponentRelevantForNavigation (UActorComponent *Component) const override
virtual bool IsLevelBoundsRelevant () const override
FORCEINLINE bool IsNotForClientOrServer () const
Return if true if this brush is not used for gameplay (i.e.
virtual bool IsStaticBrush () const
virtual bool IsVolumeBrush () const
virtual bool Modify (bool bAlwaysMarkDirty=true) override
virtual bool NeedsLoadForClient () const override
virtual bool NeedsLoadForServer () const override
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostEditMove (bool bFinished) override
virtual void PostLoad () override
virtual void PostRegisterAllComponents () override
virtual void RebuildNavigationData ()
virtual bool SetIsHiddenEdLayer (bool bIsHiddenEdLayer) override
virtual void SetIsTemporarilyHiddenInEditor (bool bIsHidden) override
FORCEINLINE void SetNotForClientOrServer ()
Indicate that this brush need not be loaded on client or servers.
bool ShouldExportStaticNavigableGeometry () const
virtual bool SupportsExternalPackaging () const override
virtual bool SupportsLayers () const override
UPROPERTY() uint32 bInManipulation UPROPERTY () TArray< struct FGeomSelection > SavedSelections
Flag set when we are in a manipulation (scaling, translation, brush builder param change etc.)
Static Public Member Functions
static FOnBrushRegistered & GetOnBrushRegisteredDelegate ()
Function to get the 'brush registered' delegate.
static bool GetSuppressBSPRegeneration ()
static bool NeedsRebuild (TArray< TWeakObjectPtr< ULevel > > *OutLevels=nullptr)
Called to see if any of the levels need rebuilding.
static void OnRebuildDone ()
Called upon finishing the csg rebuild to clear the rebuild bool.
static void SetNeedRebuild (ULevel *InLevel)
Called to make not of the level that needs rebuilding.
static void SetSuppressBSPRegeneration (bool bSuppress)
Static Public Attributes
static const TCHAR * GGeometryRebuildCause
Debug purposes only; an attempt to catch the cause of UE-36265.
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY()) TEnumAsByte< enum EBrushType > BrushType
Type of brush.
UPROPERTY () FColor BrushColor
UPROPERTY () int32 PolyFlags
UPROPERTY() uint32 bColored UPROPERTY() uint32 bSolidWhenSelected UPROPERTY() uint32 bPlaceableFromClassBrowser UPROPERTY() uint32 bNotForClientOrServer UPROPERTY () TObjectPtr< class UModel > Brush
If true, this brush class can be placed using the class browser like other simple class types.
UPROPERTY ()) TObjectPtr< class UBrushComponent > BrushComponent
Static Private Attributes
static bool bSuppressBSPRegeneration
Global bool to suppress automatic BSP regeneration.
static TArray< TWeakObjectPtr< ULevel > > LevelsToRebuild
An array to keep track of all the levels that need rebuilding.
static FOnBrushRegistered OnBrushRegistered
Delegate called when PostRegisterAllComponents is called for a Brush.
Detailed Description
Definition at line 76 of file Brush.h.
Member Function Documentation
CanDeleteSelectedActor()
virtual bool ABrush::CanDeleteSelectedActor (FText & OutReason) const override virtual
CanEverAffectBSP()
bool ABrush::CanEverAffectBSP () const
Returns
true if its Brush Component should ever participate in BSP Rebuild
CanReplaceSelectedActor()
virtual bool ABrush::CanReplaceSelectedActor (FText & OutReason) const override virtual
CheckForErrors()
virtual void ABrush::CheckForErrors () override virtual
Reimplemented in ALevelStreamingVolume, and AVolume.
ClearNotForClientOrServer()
FORCEINLINE void ABrush::ClearNotForClientOrServer () inline
Indicate that brush need should be loaded on client or servers.
Definition at line 269 of file Brush.h.
References FORCEINLINE.
CopyPosRotScaleFrom()
virtual void ABrush::CopyPosRotScaleFrom (ABrush * Other) virtual
References Other.
DECLARE_MULTICAST_DELEGATE_OneParam()
ABrush::DECLARE_MULTICAST_DELEGATE_OneParam (FOnBrushRegistered , ABrush *)
Delegate used for notifications when PostRegisterAllComponents is called for a Brush.
Destroyed()
virtual void ABrush::Destroyed () override virtual
Reimplemented in ACullDistanceVolume.
GENERATED_UCLASS_BODY()
ABrush::GENERATED_UCLASS_BODY () private
Type of brush.
References Category, meta, and UPROPERTY().
GetBrushComponent()
class UBrushComponent * ABrush::GetBrushComponent () const inline
Returns BrushComponent subobject.
Definition at line 281 of file Brush.h.
GetCustomIconName()
virtual FName ABrush::GetCustomIconName () const override virtual
Reimplemented in AVolume.
GetOnBrushRegisteredDelegate()
FOnBrushRegistered & ABrush::GetOnBrushRegisteredDelegate () inline static
Function to get the 'brush registered' delegate.
Definition at line 142 of file Brush.h.
References OnBrushRegistered.
GetSuppressBSPRegeneration()
bool ABrush::GetSuppressBSPRegeneration () inline static
Definition at line 200 of file Brush.h.
References bSuppressBSPRegeneration.
GetWireColor()
virtual FColor ABrush::GetWireColor () const virtual
Figures out the best color to use for this brushes wireframe drawing.
InitPosRotScale()
virtual void ABrush::InitPosRotScale () virtual
IsActorLabelEditable()
virtual bool ABrush::IsActorLabelEditable () const override virtual
IsBrushShape()
virtual bool ABrush::IsBrushShape () const inline virtual
Returns
false
Definition at line 245 of file Brush.h.
IsComponentRelevantForNavigation()
virtual bool ABrush::IsComponentRelevantForNavigation (UActorComponent * Component) const override virtual
References Component.
IsLevelBoundsRelevant()
virtual bool ABrush::IsLevelBoundsRelevant () const override virtual
Reimplemented in AHierarchicalLODVolume, and AVolume.
IsNotForClientOrServer()
FORCEINLINE bool ABrush::IsNotForClientOrServer () const inline
Return if true if this brush is not used for gameplay (i.e.
builder brush)
Returns
true if brush is not for client or server
Definition at line 257 of file Brush.h.
References FORCEINLINE.
Referenced by NeedsLoadForClient(), and NeedsLoadForServer().
IsStaticBrush()
virtual bool ABrush::IsStaticBrush () const virtual
Returns
true if this is a static brush
Reimplemented in AVolume.
IsVolumeBrush()
virtual bool ABrush::IsVolumeBrush () const inline virtual
Returns
false
Reimplemented in AVolume.
Definition at line 242 of file Brush.h.
Modify()
virtual bool ABrush::Modify (bool bAlwaysMarkDirty = true) override virtual
NeedsLoadForClient()
virtual bool ABrush::NeedsLoadForClient () const inline override virtual
Reimplemented in AHierarchicalLODVolume.
Definition at line 160 of file Brush.h.
References IsNotForClientOrServer().
NeedsLoadForServer()
virtual bool ABrush::NeedsLoadForServer () const inline override virtual
Reimplemented in AHierarchicalLODVolume.
Definition at line 165 of file Brush.h.
References IsNotForClientOrServer().
NeedsRebuild()
bool ABrush::NeedsRebuild (TArray< TWeakObjectPtr< ULevel > > * OutLevels = nullptr) static
Called to see if any of the levels need rebuilding.
Parameters
OutLevels if specified, provides a copy of the levels array
Returns
true if the csg needs to be rebuilt on the next editor tick.
OnRebuildDone()
void ABrush::OnRebuildDone () inline static
Called upon finishing the csg rebuild to clear the rebuild bool.
Definition at line 225 of file Brush.h.
References LevelsToRebuild.
PostEditChangeChainProperty()
virtual void ABrush::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
PostEditChangeProperty()
virtual void ABrush::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented in AAudioVolume, ACullDistanceVolume, and AVolume.
PostEditMove()
virtual void ABrush::PostEditMove (bool bFinished) override virtual
Reimplemented in ACullDistanceVolume, and ALightmassImportanceVolume.
PostLoad()
virtual void ABrush::PostLoad () override virtual
Reimplemented in ALevelStreamingVolume.
PostRegisterAllComponents()
virtual void ABrush::PostRegisterAllComponents () override virtual
Reimplemented in AAudioVolume, and ALocationVolume.
Referenced by UCLASS().
RebuildNavigationData()
virtual void ABrush::RebuildNavigationData () virtual
SetIsHiddenEdLayer()
virtual bool ABrush::SetIsHiddenEdLayer (bool bIsHiddenEdLayer) override virtual
SetIsTemporarilyHiddenInEditor()
virtual void ABrush::SetIsTemporarilyHiddenInEditor (bool bIsHidden) override virtual
SetNeedRebuild()
void ABrush::SetNeedRebuild (ULevel * InLevel) static
Called to make not of the level that needs rebuilding.
Parameters
InLevel The level that needs rebuilding
SetNotForClientOrServer()
FORCEINLINE void ABrush::SetNotForClientOrServer () inline
Indicate that this brush need not be loaded on client or servers.
Definition at line 263 of file Brush.h.
References FORCEINLINE.
SetSuppressBSPRegeneration()
void ABrush::SetSuppressBSPRegeneration (bool bSuppress) inline static
Definition at line 199 of file Brush.h.
References bSuppressBSPRegeneration.
ShouldExportStaticNavigableGeometry()
bool ABrush::ShouldExportStaticNavigableGeometry () const
Returns
true if its Brush Component should be considered when building the level's static navigable geometry
SupportsExternalPackaging()
virtual bool ABrush::SupportsExternalPackaging () const override virtual
SupportsLayers()
virtual bool ABrush::SupportsLayers () const override virtual
UPROPERTY() [1/5]
ABrush::UPROPERTY () private
References UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), ACullDistanceVolume::GENERATED_UCLASS_BODY(), AVolumetricLightmapDensityVolume::GENERATED_UCLASS_BODY(), UCLASS(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/5]
ABrush::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [3/5]
UPROPERTY() uint32 bInManipulation ABrush::UPROPERTY ()
Flag set when we are in a manipulation (scaling, translation, brush builder param change etc.)
Stores selection information from geometry mode. This is the only information that we can't regenerate by looking at the source brushes following an undo operation.
References UPROPERTY().
UPROPERTY() [4/5]
UPROPERTY() uint32 bColored UPROPERTY() uint32 bSolidWhenSelected UPROPERTY() uint32 bPlaceableFromClassBrowser UPROPERTY() uint32 bNotForClientOrServer ABrush::UPROPERTY () private
If true, this brush class can be placed using the class browser like other simple class types.
If true, this brush is a builder or otherwise does not need to be loaded into the game
References UPROPERTY().
UPROPERTY() [5/5]
ABrush::UPROPERTY () private
References Category, float, meta, Transient, and UPROPERTY().
Field Documentation
bSuppressBSPRegeneration
bool ABrush::bSuppressBSPRegeneration static private
Global bool to suppress automatic BSP regeneration.
Definition at line 210 of file Brush.h.
Referenced by GetSuppressBSPRegeneration(), and SetSuppressBSPRegeneration().
GGeometryRebuildCause
const TCHAR* ABrush::GGeometryRebuildCause static
Debug purposes only; an attempt to catch the cause of UE-36265.
Definition at line 285 of file Brush.h.
LevelsToRebuild
TArray< TWeakObjectPtr< ULevel > > ABrush::LevelsToRebuild static private
An array to keep track of all the levels that need rebuilding.
This is checked via NeedsRebuild() in the editor tick and triggers a csg rebuild.
Definition at line 204 of file Brush.h.
Referenced by OnRebuildDone().
OnBrushRegistered
FOnBrushRegistered ABrush::OnBrushRegistered static private
Delegate called when PostRegisterAllComponents is called for a Brush.
Definition at line 207 of file Brush.h.
Referenced by GetOnBrushRegisteredDelegate().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/Brush.h