Unreal Engine 5.6 C++ API: Metasound::FTransmissionAddress Class Reference
Metasound::FTransmissionAddress Class Reference abstract
A FTranmissionAddress acts as a identifier for a data channel shared by one or more senders and or receivers.
#include "MetasoundRouter.h"
Data Structures
struct THasStaticAddressType
Public Member Functions
FTransmissionAddress ()=default
virtual ~FTransmissionAddress ()=default
virtual TUniquePtr< FTransmissionAddress > Clone () const =0
Clone the address.
virtual FName GetAddressType () const =0
Return the type of address.
virtual FName GetDataType () const =0
Return the data type.
METASOUNDFRONTEND_API bool operator!= (const FTransmissionAddress &InOther) const
METASOUNDFRONTEND_API bool operator== (const FTransmissionAddress &InOther) const
virtual FString ToString () const =0
Return a string representation of the address for debugging.
Private Member Functions
virtual uint32 GetHash () const =0
Create a hash of the address.
virtual bool IsEqual (const FTransmissionAddress &InOther) const =0
Determine if the given address is equal to this address.
Friends
template<typename DerivedAddressType>
const DerivedAddressType * CastAddressType (const FTransmissionAddress &InOther)
Attempt to cast a FTransmissionAddress to a derived address type.
uint32 GetTypeHash (const ::Metasound::FTransmissionAddress &)
Detailed Description
A FTranmissionAddress acts as a identifier for a data channel shared by one or more senders and or receivers.
Different addressing schemes are supported by deriving a system specific address type from a FTransmissionAddress. This allows different systems to construct and store address information in their desired format while all utilizing the same system for transmission.
Definition at line 59 of file MetasoundRouter.h.
Constructor & Destructor Documentation
FTransmissionAddress()
Metasound::FTransmissionAddress::FTransmissionAddress () default
Referenced by Metasound::FAddressRouter::FTransmissionAddressKey::FTransmissionAddressKey(), CastAddressType, GetTypeHash, Metasound::FAddressRouter::FTransmissionAddressKey::IsEqual(), Metasound::Frontend::FAnalyzerAddress::IsEqual(), Metasound::Frontend::FGraphAnalyzerAddress::IsEqual(), Metasound::FSendAddress::IsEqual(), IsEqual(), operator!=(), Metasound::FAddressRouter::FTransmissionAddressKey::operator=(), and operator==().
~FTransmissionAddress()
virtual Metasound::FTransmissionAddress::~FTransmissionAddress () virtual default
Member Function Documentation
Clone()
virtual TUniquePtr< FTransmissionAddress > Metasound::FTransmissionAddress::Clone () const pure virtual
Clone the address.
Implemented in Metasound::FAddressRouter::FTransmissionAddressKey, Metasound::Frontend::FAnalyzerAddress, Metasound::Frontend::FGraphAnalyzerAddress, and Metasound::FSendAddress.
GetAddressType()
virtual FName Metasound::FTransmissionAddress::GetAddressType () const pure virtual
Return the type of address.
The AddressType must be unique per a subclass of FTransmissionAddress as it is used to determine the validity of a static_cast from FTransmissionAddress to the derived address type.
Implemented in Metasound::FAddressRouter::FTransmissionAddressKey, Metasound::Frontend::FAnalyzerAddress, Metasound::Frontend::FGraphAnalyzerAddress, and Metasound::FSendAddress.
Referenced by CastAddressType, and Metasound::Frontend::FGraphAnalyzerAddress::IsEqual().
GetDataType()
virtual FName Metasound::FTransmissionAddress::GetDataType () const pure virtual
Return the data type.
Implemented in Metasound::FAddressRouter::FTransmissionAddressKey, Metasound::Frontend::FAnalyzerAddress, Metasound::Frontend::FGraphAnalyzerAddress, and Metasound::FSendAddress.
GetHash()
virtual uint32 Metasound::FTransmissionAddress::GetHash () const private pure virtual
Create a hash of the address.
Implemented in Metasound::FAddressRouter::FTransmissionAddressKey, Metasound::Frontend::FAnalyzerAddress, Metasound::Frontend::FGraphAnalyzerAddress, and Metasound::FSendAddress.
Referenced by Metasound::GetTypeHash().
IsEqual()
virtual bool Metasound::FTransmissionAddress::IsEqual (const FTransmissionAddress & InOther) const private pure virtual
Determine if the given address is equal to this address.
Implemented in Metasound::FAddressRouter::FTransmissionAddressKey, Metasound::Frontend::FAnalyzerAddress, Metasound::Frontend::FGraphAnalyzerAddress, and Metasound::FSendAddress.
References FTransmissionAddress().
operator!=()
METASOUNDFRONTEND_API bool Metasound::FTransmissionAddress::operator!= (const FTransmissionAddress & InOther) const
References FTransmissionAddress(), and UE_API.
operator==()
METASOUNDFRONTEND_API bool Metasound::FTransmissionAddress::operator== (const FTransmissionAddress & InOther) const
References FTransmissionAddress(), and UE_API.
ToString()
virtual FString Metasound::FTransmissionAddress::ToString () const pure virtual
Return a string representation of the address for debugging.
Implemented in Metasound::FAddressRouter::FTransmissionAddressKey, Metasound::Frontend::FAnalyzerAddress, Metasound::Frontend::FGraphAnalyzerAddress, and Metasound::FSendAddress.
Friends And Related Symbol Documentation
CastAddressType
template<typename DerivedAddressType> const DerivedAddressType * CastAddressType (const FTransmissionAddress & InOther) friend
Attempt to cast a FTransmissionAddress to a derived address type.
This function uses the FTransmissionAddress::GetAddressType() method to determine whether the cast is legal. Each subclass of FTransmissionAddress MUST provide a unique address type to protect against invalid casts.
Definition at line 126 of file MetasoundRouter.h.
References FTransmissionAddress(), GetAddressType(), and Metasound::FTransmissionAddress::THasStaticAddressType< DerivedAddressType >::Value.
GetTypeHash
uint32 GetTypeHash (const ::Metasound::FTransmissionAddress &) friend
References FTransmissionAddress().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h