Unreal Engine 5.6 C++ API: FLightMap2D Class Reference
FLightMap2D Class Reference
A 2D array of incident lighting data.
#include "LightMap.h"
Public Member Functions
FLightMap2D ()
FLightMap2D (bool InAllowHighQualityLightMaps)
virtual void AddReferencedObjects (FReferenceCollector &Collector)
UTexture2D * GetAOMaterialMaskTexture () const
const FVector2D & GetCoordinateBias () const
const FVector2D & GetCoordinateScale () const
virtual FLightMapInteraction GetInteraction (ERHIFeatureLevel::Type InFeatureLevel) const
virtual FLightMap2D * GetLightMap2D ()
virtual const FLightMap2D * GetLightMap2D () const
void GetReferencedTextures (TArray< UTexture2D * > &OutTextures) const
virtual FShadowMapInteraction GetShadowInteraction (ERHIFeatureLevel::Type InFeatureLevel) const
UTexture2D * GetSkyOcclusionTexture () const
Returns SkyOcclusionTexture.
UTexture2D * GetTexture (uint32 BasisIndex)
const UTexture2D * GetTexture (uint32 BasisIndex) const
Returns the texture containing the RGB coefficients for a specific basis.
ULightMapVirtualTexture2D * GetVirtualTexture (uint32 BasisIndex) const
bool IsValid (uint32 BasisIndex) const
Returns whether the specified basis has a valid lightmap texture or not.
bool IsVirtualTextureValid () const
virtual void Serialize (FArchive &Ar)
Public Member Functions inherited from FLightMap
FLightMap ()
Default constructor.
virtual ~FLightMap ()
Destructor.
void AddRef ()
FORCEINLINE bool AllowsHighQualityLightmaps () const
bool ContainsLight (const FGuid &LightGuid) const
Checks if a light is stored in this light-map.
void Release ()
Static Public Member Functions
static TRefCountPtr< FLightMap2D > AllocateInstancedLightMap (UObject *LightMapOuter, UInstancedStaticMeshComponent *Component, TArray< TUniquePtr< FQuantizedLightmapData > > SourceQuantizedData, TArray< TMap< ULightComponent *, TUniquePtr< FShadowMapData2D > > > &&InstancedShadowMapData, UMapBuildDataRegistry *Registry, FGuid MapBuildDataId, const FBoxSphereBounds &Bounds, ELightMapPaddingType InPaddingType, ELightMapFlags LightmapFlags)
Allocates texture space for the light-map and stores the light-map's raw data for deferred encoding.
static TRefCountPtr< FLightMap2D > AllocateLightMap (UObject *LightMapOuter, FQuantizedLightmapData *&SourceQuantizedData, const TMap< ULightComponent *, FShadowMapData2D * > &SourceShadowMapData, const FBoxSphereBounds &Bounds, ELightMapPaddingType InPaddingType, ELightMapFlags InLightmapFlags)
Allocates texture space for the light-map and stores the light-map's raw data for deferred encoding.
static int32 EncodeShadowTexture (const FStaticLightingBuildContext *LightingContext, struct FLightMapPendingTexture &PendingTexture, TArray< TArray< FFourDistanceFieldSamples > > &MipData)
Constructs mip maps for a single shadowmap texture.
static void EncodeTextures (const FStaticLightingBuildContext *LightingContext, bool bLightingSuccessful, bool bMultithreadedEncode=false)
Executes all pending light-map encoding requests.
static bool GetStatusUpdate ()
static void SetStatusUpdate (bool bInEnable)
Call to enable/disable status update of LightMap encoding.
Data Fields
FVector4f AddVectors [NUM_STORED_LIGHTMAP_COEF]
Bias value to apply to the coefficients.
TObjectPtr< ULightMapTexture2D > AOMaterialMaskTexture
bool bShadowChannelValid [4]
Tracks which of the 4 channels has valid texture data.
FVector2D CoordinateBias
The bias which is applied to the light-map coordinates before sampling the light-map textures.
FVector2D CoordinateScale
The scale which is applied to the light-map coordinates before sampling the light-map textures.
FVector4f InvUniformPenumbraSize
Stores the inverse of the penumbra size, normalized.
FVector4f ScaleVectors [NUM_STORED_LIGHTMAP_COEF]
A scale to apply to the coefficients.
TObjectPtr< UShadowMapTexture2D > ShadowMapTexture
TObjectPtr< ULightMapTexture2D > SkyOcclusionTexture
TObjectPtr< ULightMapTexture2D > Textures [2]
The textures containing the light-map data.
TObjectPtr< ULightMapVirtualTexture2D > VirtualTextures [2]
The virtual textures containing the light-map data.
Data Fields inherited from FLightMap
TArray< FGuid > LightGuids
The GUIDs of lights which this light-map stores.
Protected Member Functions
FLightMap2D (const TArray< FGuid > &InLightGuids)
Protected Member Functions inherited from FLightMap
virtual void Cleanup ()
Called when the light-map is no longer referenced.
Static Protected Attributes
static bool bUpdateStatus
If true, update the status when encoding light maps.
Additional Inherited Members
Public Types inherited from FLightMap
enum { LMT_None = 0 , LMT_1D = 1 , LMT_2D = 2 }
Protected Attributes inherited from FLightMap
bool bAllowHighQualityLightMaps
Indicates whether the lightmap is being used for directional or simple lighting.
Detailed Description
A 2D array of incident lighting data.
Definition at line 198 of file LightMap.h.
Constructor & Destructor Documentation
FLightMap2D() [1/3]
FLightMap2D::FLightMap2D ()
Referenced by GetLightMap2D(), and GetLightMap2D().
FLightMap2D() [2/3]
FLightMap2D::FLightMap2D (bool InAllowHighQualityLightMaps)
FLightMap2D() [3/3]
FLightMap2D::FLightMap2D (const TArray< FGuid > & InLightGuids) protected
Member Function Documentation
AddReferencedObjects()
virtual void FLightMap2D::AddReferencedObjects (FReferenceCollector & Collector) virtual
Reimplemented from FLightMap.
AllocateInstancedLightMap()
TRefCountPtr< FLightMap2D > FLightMap2D::AllocateInstancedLightMap (UObject * LightMapOuter, UInstancedStaticMeshComponent * Component, TArray< TUniquePtr< FQuantizedLightmapData > > SourceQuantizedData, TArray< TMap< ULightComponent *, TUniquePtr< FShadowMapData2D > > > && InstancedShadowMapData, UMapBuildDataRegistry * Registry, FGuid MapBuildDataId, const FBoxSphereBounds & Bounds, ELightMapPaddingType InPaddingType, ELightMapFlags LightmapFlags) static
Allocates texture space for the light-map and stores the light-map's raw data for deferred encoding.
If the light-map has no lights in it, it will return NULL. SourceQuantizedData will be deleted by this function.
Parameters
Component - The component that owns this lightmap
SourceQuantizedData - If the data is already quantized, the values will be in here, and not in RawData.
Bounds - The bounds of the primitive the light-map will be rendered on. Used as a hint to pack light-maps on nearby primitives in the same texture.
InPaddingType - the method for padding the lightmap.
LightmapFlags - flags that determine how the lightmap is stored (e.g. streamed or not)
References Component, and Registry.
AllocateLightMap()
TRefCountPtr< FLightMap2D > FLightMap2D::AllocateLightMap (UObject * LightMapOuter, FQuantizedLightmapData *& SourceQuantizedData, const TMap< ULightComponent *, FShadowMapData2D * > & SourceShadowMapData, const FBoxSphereBounds & Bounds, ELightMapPaddingType InPaddingType, ELightMapFlags InLightmapFlags) static
Allocates texture space for the light-map and stores the light-map's raw data for deferred encoding.
If the light-map has no lights in it, it will return NULL. SourceQuantizedData will be deleted by this function.
Parameters
LightMapOuter - The package to create the light-map and textures in.
SourceQuantizedData - If the data is already quantized, the values will be in here, and not in RawData.
SourceShadowMapData - Shadow map data to be combined into the lightmap atlas, used when creating VT lightmaps
Bounds - The bounds of the primitive the light-map will be rendered on. Used as a hint to pack light-maps on nearby primitives in the same texture.
InPaddingType - the method for padding the lightmap.
LightmapFlags - flags that determine how the lightmap is stored (e.g. streamed or not)
EncodeShadowTexture()
int32 FLightMap2D::EncodeShadowTexture (const FStaticLightingBuildContext * LightingContext, struct FLightMapPendingTexture & PendingTexture, TArray< TArray< FFourDistanceFieldSamples > > & MipData) static
Constructs mip maps for a single shadowmap texture.
EncodeTextures()
void FLightMap2D::EncodeTextures (const FStaticLightingBuildContext * LightingContext, bool bLightingSuccessful, bool bMultithreadedEncode = false) static
Executes all pending light-map encoding requests.
Parameters
bLightingSuccessful Whether the lighting build was successful or not.
bForceCompletion Force all encoding to be fully completed (they may be asynchronous).
GetAOMaterialMaskTexture()
UTexture2D * FLightMap2D::GetAOMaterialMaskTexture () const
Referenced by GetReferencedTextures().
GetCoordinateBias()
const FVector2D & FLightMap2D::GetCoordinateBias () const inline
Definition at line 256 of file LightMap.h.
References CoordinateBias.
GetCoordinateScale()
const FVector2D & FLightMap2D::GetCoordinateScale () const inline
Definition at line 255 of file LightMap.h.
References CoordinateScale.
GetInteraction()
virtual FLightMapInteraction FLightMap2D::GetInteraction (ERHIFeatureLevel::Type InFeatureLevel) const virtual
Implements FLightMap.
GetLightMap2D() [1/2]
virtual FLightMap2D * FLightMap2D::GetLightMap2D () inline virtual
Reimplemented from FLightMap.
Definition at line 267 of file LightMap.h.
References FLightMap2D().
GetLightMap2D() [2/2]
virtual const FLightMap2D * FLightMap2D::GetLightMap2D () const inline virtual
Reimplemented from FLightMap.
Definition at line 266 of file LightMap.h.
References FLightMap2D().
GetReferencedTextures()
void FLightMap2D::GetReferencedTextures (TArray< UTexture2D * > & OutTextures) const inline
Definition at line 215 of file LightMap.h.
References TArray< InElementType, InAllocatorType >::Add(), GetAOMaterialMaskTexture(), GetSkyOcclusionTexture(), Textures, and UE_ARRAY_COUNT.
GetShadowInteraction()
virtual FShadowMapInteraction FLightMap2D::GetShadowInteraction (ERHIFeatureLevel::Type InFeatureLevel) const virtual
Reimplemented from FLightMap.
GetSkyOcclusionTexture()
UTexture2D * FLightMap2D::GetSkyOcclusionTexture () const
Returns SkyOcclusionTexture.
Returns
The SkyOcclusionTexture.
Referenced by GetReferencedTextures().
GetStatusUpdate()
bool FLightMap2D::GetStatusUpdate () inline static
Definition at line 320 of file LightMap.h.
References bUpdateStatus.
GetTexture() [1/2]
UTexture2D * FLightMap2D::GetTexture (uint32 BasisIndex)
GetTexture() [2/2]
const UTexture2D * FLightMap2D::GetTexture (uint32 BasisIndex) const
Returns the texture containing the RGB coefficients for a specific basis.
Parameters
BasisIndex - The basis index.
Returns
The RGB coefficient texture.
GetVirtualTexture()
ULightMapVirtualTexture2D * FLightMap2D::GetVirtualTexture (uint32 BasisIndex) const inline
Definition at line 244 of file LightMap.h.
References VirtualTextures.
IsValid()
bool FLightMap2D::IsValid (uint32 BasisIndex) const
Returns whether the specified basis has a valid lightmap texture or not.
Parameters
BasisIndex - The basis index.
Returns
true if the specified basis has a valid lightmap texture, otherwise false
IsVirtualTextureValid()
bool FLightMap2D::IsVirtualTextureValid () const
Serialize()
virtual void FLightMap2D::Serialize (FArchive & Ar) virtual
Reimplemented from FLightMap.
References Ar.
SetStatusUpdate()
void FLightMap2D::SetStatusUpdate (bool bInEnable) inline static
Call to enable/disable status update of LightMap encoding.
Definition at line 315 of file LightMap.h.
References bUpdateStatus.
Field Documentation
AddVectors
FVector4f FLightMap2D::AddVectors[NUM_STORED_LIGHTMAP_COEF]
Bias value to apply to the coefficients.
Definition at line 341 of file LightMap.h.
AOMaterialMaskTexture
TObjectPtr<ULightMapTexture2D> FLightMap2D::AOMaterialMaskTexture
Definition at line 330 of file LightMap.h.
bShadowChannelValid
bool FLightMap2D::bShadowChannelValid[4]
Tracks which of the 4 channels has valid texture data.
Definition at line 353 of file LightMap.h.
bUpdateStatus
bool FLightMap2D::bUpdateStatus static protected
If true, update the status when encoding light maps.
Definition at line 359 of file LightMap.h.
Referenced by GetStatusUpdate(), and SetStatusUpdate().
CoordinateBias
FVector2D FLightMap2D::CoordinateBias
The bias which is applied to the light-map coordinates before sampling the light-map textures.
Definition at line 347 of file LightMap.h.
Referenced by GetCoordinateBias().
CoordinateScale
FVector2D FLightMap2D::CoordinateScale
The scale which is applied to the light-map coordinates before sampling the light-map textures.
Definition at line 344 of file LightMap.h.
Referenced by GetCoordinateScale().
InvUniformPenumbraSize
FVector4f FLightMap2D::InvUniformPenumbraSize
Stores the inverse of the penumbra size, normalized.
Stores 1 to interpret the shadowmap as a shadow factor directly, instead of as a distance field.
Definition at line 350 of file LightMap.h.
ScaleVectors
FVector4f FLightMap2D::ScaleVectors[NUM_STORED_LIGHTMAP_COEF]
A scale to apply to the coefficients.
Definition at line 338 of file LightMap.h.
ShadowMapTexture
TObjectPtr<UShadowMapTexture2D> FLightMap2D::ShadowMapTexture
Definition at line 332 of file LightMap.h.
SkyOcclusionTexture
TObjectPtr<ULightMapTexture2D> FLightMap2D::SkyOcclusionTexture
Definition at line 328 of file LightMap.h.
Textures
TObjectPtr<ULightMapTexture2D> FLightMap2D::Textures[2]
The textures containing the light-map data.
Definition at line 326 of file LightMap.h.
Referenced by GetReferencedTextures().
VirtualTextures
TObjectPtr<ULightMapVirtualTexture2D > FLightMap2D::VirtualTextures[2]
The virtual textures containing the light-map data.
Definition at line 335 of file LightMap.h.
Referenced by GetVirtualTexture().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/LightMap.h