Unreal Engine 5.6 C++ API: TQueue< T, Mode > Class Template Reference
TQueue< T, Mode > Class Template Reference
Template for queues.
#include "Queue.h"
Data Structures
struct TNode
Public Types
using FElementType = T
Public Member Functions
TQueue ()
Default constructor.
~TQueue ()
Destructor.
bool Dequeue (FElementType &OutItem)
Removes and returns the item from the tail of the queue.
void Empty ()
Empty the queue, discarding all items.
bool Enqueue (const FElementType &Item)
Adds an item to the head of the queue.
bool Enqueue (FElementType &&Item)
Adds an item to the head of the queue.
bool IsEmpty () const
Checks whether the queue is empty.
FElementType * Peek ()
Peek at the queue's tail item without removing it.
FORCEINLINE const FElementType * Peek () const
bool Peek (FElementType &OutItem) const
Peeks at the queue's tail item without removing it.
bool Pop ()
Removes the item from the tail of the queue.
UE_NONCOPYABLE (TQueue)
Private Types
using TNodeVolatilePtr = std::conditional_t<Mode == EQueueMode::SingleThreaded, TNode*, TNode* volatile>
Private Member Functions
MS_ALIGN (16) TNodeVolatilePtr Head GCC_ALIGN(16)
Holds a pointer to the head of the list.
Private Attributes
TNode * Tail
Holds a pointer to the tail of the list.
Detailed Description
template<typename T, EQueueMode Mode = EQueueMode::Spsc>
class TQueue< T, Mode >
Template for queues.
This template implements an unbounded non-intrusive queue using a lock-free linked list that stores copies of the queued items. The template can operate in two modes: Multiple-producers single-consumer (MPSC) and Single-producer single-consumer (SPSC).
The queue is thread-safe in both modes. The Dequeue() method ensures thread-safety by writing it in a way that does not depend on possible instruction reordering on the CPU. The Enqueue() method uses an atomic compare-and-swap in multiple-producers scenarios.
Parameters
T The type of items stored in the queue.
Mode The queue mode (single-producer, single-consumer by default).
Todo
gmp: Implement node pooling.
Definition at line 45 of file Queue.h.
Member Typedef Documentation
FElementType
template<typename T, EQueueMode Mode = EQueueMode::Spsc> using TQueue< T, Mode >::FElementType = T
Definition at line 48 of file Queue.h.
TNodeVolatilePtr
template<typename T, EQueueMode Mode = EQueueMode::Spsc> using TQueue< T, Mode >::TNodeVolatilePtr = std::conditional_t<Mode == EQueueMode::SingleThreaded, TNode*, TNode* volatile> private
Definition at line 285 of file Queue.h.
Constructor & Destructor Documentation
TQueue()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> TQueue< T, Mode >::TQueue () inline nodiscard
Default constructor.
Definition at line 51 of file Queue.h.
References Tail.
Referenced by Peek(), and UE_NONCOPYABLE().
~TQueue()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> TQueue< T, Mode >::~TQueue () inline
Destructor.
Definition at line 57 of file Queue.h.
References Tail.
Member Function Documentation
Dequeue()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> bool TQueue< T, Mode >::Dequeue (FElementType & OutItem) inline
Removes and returns the item from the tail of the queue.
Parameters
OutValue Will hold the returned value.
Returns
true if a value was returned, false if the queue was empty.
Note
To be called only from consumer thread.
See also
Empty, Enqueue, IsEmpty, Peek, Pop
Definition at line 78 of file Queue.h.
References TQueue< T, Mode >::TNode::Item, MoveTemp(), SingleThreaded, Tail, and TSAN_AFTER.
Empty()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> void TQueue< T, Mode >::Empty () inline
Empty the queue, discarding all items.
Note
To be called only from consumer thread.
See also
Dequeue, IsEmpty, Peek, Pop
Definition at line 108 of file Queue.h.
References Pop().
Enqueue() [1/2]
template<typename T, EQueueMode Mode = EQueueMode::Spsc> bool TQueue< T, Mode >::Enqueue (const FElementType & Item) inline
Adds an item to the head of the queue.
Parameters
Item The item to add.
Returns
true if the item was added, false otherwise.
Note
To be called only from producer thread(s).
See also
Dequeue, Pop
Definition at line 121 of file Queue.h.
References Item, FAndroidMisc::MemoryBarrier(), Mpsc, TQueue< T, Mode >::TNode::NextNode, Spsc, and TSAN_BEFORE.
Enqueue() [2/2]
template<typename T, EQueueMode Mode = EQueueMode::Spsc> bool TQueue< T, Mode >::Enqueue (FElementType && Item) inline
Adds an item to the head of the queue.
Parameters
Item The item to add.
Returns
true if the item was added, false otherwise.
Note
To be called only from producer thread(s).
See also
Dequeue, Pop
Definition at line 163 of file Queue.h.
References Item, FAndroidMisc::MemoryBarrier(), MoveTemp(), Mpsc, TQueue< T, Mode >::TNode::NextNode, Spsc, and TSAN_BEFORE.
IsEmpty()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> bool TQueue< T, Mode >::IsEmpty () const inline nodiscard
Checks whether the queue is empty.
Returns
true if the queue is empty, false otherwise.
Note
To be called only from consumer thread.
See also
Dequeue, Empty, Peek, Pop
Definition at line 204 of file Queue.h.
References Tail.
MS_ALIGN()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> TQueue< T, Mode >::MS_ALIGN (16) private
Holds a pointer to the head of the list.
References GCC_ALIGN.
Peek() [1/3]
template<typename T, EQueueMode Mode = EQueueMode::Spsc> FElementType * TQueue< T, Mode >::Peek () inline nodiscard
Peek at the queue's tail item without removing it.
This version of Peek allows peeking at a queue of items that do not allow copying, such as TUniquePtr.
Returns
Pointer to the item, or nullptr if queue is empty
Definition at line 237 of file Queue.h.
References Tail.
Referenced by Peek().
Peek() [2/3]
template<typename T, EQueueMode Mode = EQueueMode::Spsc> FORCEINLINE const FElementType * TQueue< T, Mode >::Peek () const inline nodiscard
Definition at line 247 of file Queue.h.
References TQueue(), FORCEINLINE, and Peek().
Peek() [3/3]
template<typename T, EQueueMode Mode = EQueueMode::Spsc> bool TQueue< T, Mode >::Peek (FElementType & OutItem) const inline
Peeks at the queue's tail item without removing it.
Parameters
OutItem Will hold the peeked at item.
Returns
true if an item was returned, false if the queue was empty.
Note
To be called only from consumer thread.
See also
Dequeue, Empty, IsEmpty, Pop
Definition at line 217 of file Queue.h.
References Tail.
Pop()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> bool TQueue< T, Mode >::Pop () inline
Removes the item from the tail of the queue.
Returns
true if a value was removed, false if the queue was empty.
Note
To be called only from consumer thread.
See also
Dequeue, Empty, Enqueue, IsEmpty, Peek
Definition at line 259 of file Queue.h.
References SingleThreaded, Tail, and TSAN_AFTER.
Referenced by Empty().
UE_NONCOPYABLE()
template<typename T, EQueueMode Mode = EQueueMode::Spsc> TQueue< T, Mode >::UE_NONCOPYABLE (TQueue< T, Mode >)
References TQueue().
Field Documentation
Tail
template<typename T, EQueueMode Mode = EQueueMode::Spsc> TNode* TQueue< T, Mode >::Tail private
Holds a pointer to the tail of the list.
Definition at line 315 of file Queue.h.
Referenced by TQueue(), ~TQueue(), Dequeue(), IsEmpty(), Peek(), Peek(), and Pop().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Queue.h