Unreal Engine 5.6 C++ API: FSlateApplication::InputPreProcessorsHelper Class Reference
FSlateApplication::InputPreProcessorsHelper Class Reference
A helper class to wrap the list of input pre-processors.
Public Member Functions
bool Add (const FInputPreprocessorRegistration &Registration)
Adds or inserts an unique input pre-processor.
int32 Find (TSharedPtr< IInputProcessor > InputProcessor, const EInputPreProcessorType &Type) const
Get the index of an input pre-processor.
bool HandleAnalogInputEvent (FSlateApplication &SlateApp, const FAnalogInputEvent &InAnalogInputEvent)
bool HandleKeyDownEvent (FSlateApplication &SlateApp, const FKeyEvent &InKeyEvent)
bool HandleKeyUpEvent (FSlateApplication &SlateApp, const FKeyEvent &InKeyEvent)
bool HandleMotionDetectedEvent (FSlateApplication &SlateApp, const FMotionEvent &MotionEvent)
bool HandleMouseButtonDoubleClickEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
bool HandleMouseButtonDownEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
bool HandleMouseButtonUpEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
bool HandleMouseMoveEvent (FSlateApplication &SlateApp, const FPointerEvent &MouseEvent)
bool HandleMouseWheelOrGestureEvent (FSlateApplication &SlateApp, const FPointerEvent &WheelEvent, const FPointerEvent *GestureEvent)
void Remove (TSharedPtr< IInputProcessor > InputProcessor)
Remove an input pre-processor.
void RemoveAll ()
Remove all registered input pre-processors.
void Tick (const float DeltaTime, FSlateApplication &SlateApp, TSharedRef< ICursor > Cursor)
Private Types
using FInputProcessorStorage = TSparseArray<FProcessorTypeStorage, TInlineSparseArrayAllocator<(uint32)EInputPreProcessorType::Count>>
using FProcessorTypeStorage = TArray<TSharedPtr<IInputProcessor>>
Private Member Functions
void AddInternal (const FInputPreprocessorRegistration &Registration)
bool PreProcessInput (ESlateDebuggingInputEvent InputEvent, TFunctionRef< bool(IInputProcessor &)> InputProcessFunc)
Private Attributes
bool bIsIteratingPreProcessors = false
Guard value for if we are currently iterating our preprocessors.
FInputProcessorStorage InputPreProcessors
The container of input pre-processors, indexed by type and ordered by priority.
TArray< TSharedPtr< IInputProcessor > > InputPreProcessorsIteratorList
Flat array built from the ordered contents of the InputPreProcessors map to speed iteration.
TArray< FInputPreprocessorRegistration > ProcessorsPendingAddition
A list of pre-processors to add if we are iterating them while addition is requested.
TArray< TSharedPtr< IInputProcessor > > ProcessorsPendingRemoval
A list of pre-processors to remove if we are iterating them while removal is requested.
Detailed Description
A helper class to wrap the list of input pre-processors.
Definition at line 2175 of file SlateApplication.h.
Member Typedef Documentation
FInputProcessorStorage
using FSlateApplication::InputPreProcessorsHelper::FInputProcessorStorage = TSparseArray<FProcessorTypeStorage, TInlineSparseArrayAllocator<(uint32)EInputPreProcessorType::Count>> private
Definition at line 2221 of file SlateApplication.h.
FProcessorTypeStorage
using FSlateApplication::InputPreProcessorsHelper::FProcessorTypeStorage = TArray<TSharedPtr<IInputProcessor>> private
Definition at line 2220 of file SlateApplication.h.
Member Function Documentation
Add()
bool FSlateApplication::InputPreProcessorsHelper::Add (const FInputPreprocessorRegistration & Registration)
Adds or inserts an unique input pre-processor.
Parameters
Registration Information needed for the processor registration, including the processor itself, its type, priority and (in legacy mode) index.
AddInternal()
void FSlateApplication::InputPreProcessorsHelper::AddInternal (const FInputPreprocessorRegistration & Registration) private
Find()
int32 FSlateApplication::InputPreProcessorsHelper::Find (TSharedPtr< IInputProcessor > InputProcessor, const EInputPreProcessorType & Type) const
Get the index of an input pre-processor.
Parameters
InputProcessor The InputProcessor to find.
Type The priority bucket in which the InputProcessor was registered
Returns
The index of the pre-processor, or INDEX_NONE if not registered.
HandleAnalogInputEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleAnalogInputEvent (FSlateApplication & SlateApp, const FAnalogInputEvent & InAnalogInputEvent)
References FSlateApplication::FSlateApplication().
HandleKeyDownEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleKeyDownEvent (FSlateApplication & SlateApp, const FKeyEvent & InKeyEvent)
References FSlateApplication::FSlateApplication().
HandleKeyUpEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleKeyUpEvent (FSlateApplication & SlateApp, const FKeyEvent & InKeyEvent)
References FSlateApplication::FSlateApplication().
HandleMotionDetectedEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleMotionDetectedEvent (FSlateApplication & SlateApp, const FMotionEvent & MotionEvent)
References FSlateApplication::FSlateApplication().
HandleMouseButtonDoubleClickEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleMouseButtonDoubleClickEvent (FSlateApplication & SlateApp, const FPointerEvent & MouseEvent)
References FSlateApplication::FSlateApplication(), and MouseEvent.
HandleMouseButtonDownEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleMouseButtonDownEvent (FSlateApplication & SlateApp, const FPointerEvent & MouseEvent)
References FSlateApplication::FSlateApplication(), and MouseEvent.
HandleMouseButtonUpEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleMouseButtonUpEvent (FSlateApplication & SlateApp, const FPointerEvent & MouseEvent)
References FSlateApplication::FSlateApplication(), and MouseEvent.
HandleMouseMoveEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleMouseMoveEvent (FSlateApplication & SlateApp, const FPointerEvent & MouseEvent)
References FSlateApplication::FSlateApplication(), and MouseEvent.
HandleMouseWheelOrGestureEvent()
bool FSlateApplication::InputPreProcessorsHelper::HandleMouseWheelOrGestureEvent (FSlateApplication & SlateApp, const FPointerEvent & WheelEvent, const FPointerEvent * GestureEvent)
References FSlateApplication::FSlateApplication().
PreProcessInput()
bool FSlateApplication::InputPreProcessorsHelper::PreProcessInput (ESlateDebuggingInputEvent InputEvent, TFunctionRef< bool(IInputProcessor &)> InputProcessFunc) private
Remove()
void FSlateApplication::InputPreProcessorsHelper::Remove (TSharedPtr< IInputProcessor > InputProcessor)
Remove an input pre-processor.
Parameters
InputProcessor The InputProcessor to remove.
RemoveAll()
void FSlateApplication::InputPreProcessorsHelper::RemoveAll ()
Remove all registered input pre-processors.
Tick()
void FSlateApplication::InputPreProcessorsHelper::Tick (const float DeltaTime, FSlateApplication & SlateApp, TSharedRef< ICursor > Cursor)
References FSlateApplication::FSlateApplication(), and DeltaTime.
Field Documentation
bIsIteratingPreProcessors
bool FSlateApplication::InputPreProcessorsHelper::bIsIteratingPreProcessors = false private
Guard value for if we are currently iterating our preprocessors.
Definition at line 2230 of file SlateApplication.h.
InputPreProcessors
FInputProcessorStorage FSlateApplication::InputPreProcessorsHelper::InputPreProcessors private
The container of input pre-processors, indexed by type and ordered by priority.
Definition at line 2224 of file SlateApplication.h.
InputPreProcessorsIteratorList
TArray<TSharedPtr<IInputProcessor> > FSlateApplication::InputPreProcessorsHelper::InputPreProcessorsIteratorList private
Flat array built from the ordered contents of the InputPreProcessors map to speed iteration.
Definition at line 2227 of file SlateApplication.h.
ProcessorsPendingAddition
TArray<FInputPreprocessorRegistration> FSlateApplication::InputPreProcessorsHelper::ProcessorsPendingAddition private
A list of pre-processors to add if we are iterating them while addition is requested.
Definition at line 2236 of file SlateApplication.h.
ProcessorsPendingRemoval
TArray<TSharedPtr<IInputProcessor> > FSlateApplication::InputPreProcessorsHelper::ProcessorsPendingRemoval private
A list of pre-processors to remove if we are iterating them while removal is requested.
Definition at line 2233 of file SlateApplication.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Application/SlateApplication.h