Unreal Engine 5.6 C++ API: TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const > Class Template Reference
TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const > Class Template Reference
Base class for cache iterators.
#include "LruCache.h"
Public Member Functions
FORCEINLINE TBaseIterator ()
FORCEINLINE TBaseIterator (const TLruCache &Cache)
FORCEINLINE KeyType & Key () const
FORCEINLINE operator bool () const
FORCEINLINE bool operator! () const
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
ValueType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
ValueType & operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
FORCEINLINE ValueType & Value () const
Protected Member Functions
FCacheEntry * GetCurrentEntry ()
void Increment ()
Private Attributes
FCacheEntry * CurrentEntry
Detailed Description
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>>
template<bool Const>
class TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >
Base class for cache iterators.
Iteration begins at the most recent entry.
Definition at line 633 of file LruCache.h.
Constructor & Destructor Documentation
TBaseIterator() [1/2]
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::TBaseIterator () inline nodiscard
Definition at line 637 of file LruCache.h.
References CurrentEntry, and FORCEINLINE.
Referenced by operator!=(), operator++(), and operator==().
TBaseIterator() [2/2]
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::TBaseIterator (const TLruCache & Cache) inline nodiscard
Definition at line 642 of file LruCache.h.
References TLruCache< KeyType, ValueType, KeyComp >::TLruCache(), CurrentEntry, FORCEINLINE, and TLruCache< KeyType, ValueType, KeyComp >::MostRecent.
Member Function Documentation
GetCurrentEntry()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FCacheEntry * TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::GetCurrentEntry () inline nodiscard protected
Definition at line 703 of file LruCache.h.
References CurrentEntry.
Increment()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> void TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::Increment () inline protected
Definition at line 708 of file LruCache.h.
References check, and CurrentEntry.
Referenced by operator++().
Key()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE KeyType & TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::Key () const inline nodiscard
Definition at line 689 of file LruCache.h.
References check, CurrentEntry, and FORCEINLINE.
operator bool()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator bool () const inline explicit nodiscard
Definition at line 677 of file LruCache.h.
References CurrentEntry, and FORCEINLINE.
operator!()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE bool TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator! () const inline nodiscard
Definition at line 682 of file LruCache.h.
References bool, and FORCEINLINE.
operator!=()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE bool TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator!= (const TBaseIterator< Const > & Rhs) const inline nodiscard
Definition at line 660 of file LruCache.h.
References TBaseIterator(), CurrentEntry, and FORCEINLINE.
operator*()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> ValueType & TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator* () const inline nodiscard
Definition at line 671 of file LruCache.h.
References check, and CurrentEntry.
operator++()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE TBaseIterator & TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator++ () inline
Definition at line 649 of file LruCache.h.
References TBaseIterator(), FORCEINLINE, and Increment().
operator->()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> ValueType & TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator-> () const inline nodiscard
Definition at line 665 of file LruCache.h.
References check, and CurrentEntry.
operator==()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE bool TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::operator== (const TBaseIterator< Const > & Rhs) const inline nodiscard
Definition at line 655 of file LruCache.h.
References TBaseIterator(), CurrentEntry, and FORCEINLINE.
Value()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FORCEINLINE ValueType & TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::Value () const inline nodiscard
Definition at line 695 of file LruCache.h.
References check, CurrentEntry, and FORCEINLINE.
Field Documentation
CurrentEntry
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> template<bool Const> FCacheEntry* TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< Const >::CurrentEntry private
Definition at line 716 of file LruCache.h.
Referenced by TBaseIterator(), TBaseIterator(), GetCurrentEntry(), Increment(), Key(), operator bool(), operator!=(), operator*(), operator->(), operator==(), and Value().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LruCache.h