Unreal Engine 5.6 C++ API: TMemoryImagePtr< T > Class Template Reference
TMemoryImagePtr< T > Class Template Reference
#include "MemoryImage.h"
Public Member Functions
TMemoryImagePtr ()
TMemoryImagePtr (const TMemoryImagePtr< T > &InPtr)
TMemoryImagePtr (T *InPtr)
~TMemoryImagePtr ()
T * Get () const
T * GetChecked () const
int64 GetFrozenOffsetFromThis () const
int32 GetFrozenTypeIndex () const
bool IsFrozen () const
bool IsNull () const
bool IsValid () const
operator T* () const
T & operator* () const
T * operator-> () const
TMemoryImagePtr & operator= (const TMemoryImagePtr< T > &InPtr)
TMemoryImagePtr & operator= (T *InPtr)
void SafeDelete (const FPointerTableBase *PtrTable=nullptr)
void WriteMemoryImageWithDerivedType (FMemoryImageWriter &Writer, const FTypeLayoutDesc *DerivedTypeDesc) const
Protected Attributes
union {
FFrozenMemoryImagePtr Frozen
uint64 Packed
T * UnfrozenPtr
};
Private Member Functions
T * GetFrozenPtrInternal () const
Detailed Description
template<typename T>
class TMemoryImagePtr< T >
Definition at line 381 of file MemoryImage.h.
Constructor & Destructor Documentation
TMemoryImagePtr() [1/3]
template<typename T> TMemoryImagePtr< T >::TMemoryImagePtr () inline
Definition at line 388 of file MemoryImage.h.
References UnfrozenPtr.
Referenced by TMemoryImagePtr(), TUniqueMemoryImagePtr< T >::TUniqueMemoryImagePtr(), TUniqueMemoryImagePtr< T >::TUniqueMemoryImagePtr(), operator=(), and operator=().
TMemoryImagePtr() [2/3]
template<typename T> TMemoryImagePtr< T >::TMemoryImagePtr (T * InPtr) inline
Definition at line 389 of file MemoryImage.h.
References check, Frozen, and UnfrozenPtr.
TMemoryImagePtr() [3/3]
template<typename T> TMemoryImagePtr< T >::TMemoryImagePtr (const TMemoryImagePtr< T > & InPtr) inline
Definition at line 390 of file MemoryImage.h.
References TMemoryImagePtr(), check, Frozen, Get(), and UnfrozenPtr.
~TMemoryImagePtr()
template<typename T> TMemoryImagePtr< T >::~TMemoryImagePtr () inline
Definition at line 394 of file MemoryImage.h.
Member Function Documentation
Get()
template<typename T> T * TMemoryImagePtr< T >::Get () const inline
Definition at line 402 of file MemoryImage.h.
References GetFrozenPtrInternal(), IsFrozen(), and UnfrozenPtr.
Referenced by TMemoryImagePtr(), GetChecked(), TMemoryImagePtr< FScriptContainerElement >::operator FScriptContainerElement *(), operator=(), SafeDelete(), and WriteMemoryImageWithDerivedType().
GetChecked()
template<typename T> T * TMemoryImagePtr< T >::GetChecked () const inline
Definition at line 407 of file MemoryImage.h.
References check, Get(), and Value.
Referenced by operator*(), and operator->().
GetFrozenOffsetFromThis()
template<typename T> int64 TMemoryImagePtr< T >::GetFrozenOffsetFromThis () const inline
Definition at line 399 of file MemoryImage.h.
References check, Frozen, and IsFrozen().
GetFrozenPtrInternal()
template<typename T> T * TMemoryImagePtr< T >::GetFrozenPtrInternal () const inline private
Definition at line 439 of file MemoryImage.h.
References Frozen.
Referenced by Get().
GetFrozenTypeIndex()
template<typename T> int32 TMemoryImagePtr< T >::GetFrozenTypeIndex () const inline
Definition at line 400 of file MemoryImage.h.
References check, Frozen, and IsFrozen().
IsFrozen()
template<typename T> bool TMemoryImagePtr< T >::IsFrozen () const inline
Definition at line 384 of file MemoryImage.h.
References Frozen.
Referenced by Get(), GetFrozenOffsetFromThis(), GetFrozenTypeIndex(), and SafeDelete().
IsNull()
template<typename T> bool TMemoryImagePtr< T >::IsNull () const inline
Definition at line 386 of file MemoryImage.h.
References UnfrozenPtr.
IsValid()
template<typename T> bool TMemoryImagePtr< T >::IsValid () const inline
Definition at line 385 of file MemoryImage.h.
References UnfrozenPtr.
operator T*()
template<typename T> TMemoryImagePtr< T >::operator T* () const inline
Definition at line 410 of file MemoryImage.h.
operator*()
template<typename T> T & TMemoryImagePtr< T >::operator* () const inline
Definition at line 409 of file MemoryImage.h.
References GetChecked().
operator->()
template<typename T> T * TMemoryImagePtr< T >::operator-> () const inline
Definition at line 408 of file MemoryImage.h.
References GetChecked().
operator=() [1/2]
template<typename T> TMemoryImagePtr & TMemoryImagePtr< T >::operator= (const TMemoryImagePtr< T > & InPtr) inline
Definition at line 392 of file MemoryImage.h.
References TMemoryImagePtr(), check, Frozen, Get(), and UnfrozenPtr.
operator=() [2/2]
template<typename T> TMemoryImagePtr & TMemoryImagePtr< T >::operator= (T * InPtr) inline
Definition at line 391 of file MemoryImage.h.
References TMemoryImagePtr(), check, Frozen, and UnfrozenPtr.
SafeDelete()
template<typename T> void TMemoryImagePtr< T >::SafeDelete (const FPointerTableBase * PtrTable = nullptr) inline
Definition at line 412 of file MemoryImage.h.
References DeleteObjectFromLayout(), Get(), IsFrozen(), and UnfrozenPtr.
Referenced by TUniqueMemoryImagePtr< T >::TUniqueMemoryImagePtr(), TUniqueMemoryImagePtr< T >::~TUniqueMemoryImagePtr(), TUniqueMemoryImagePtr< T >::operator=(), and TUniqueMemoryImagePtr< T >::operator=().
WriteMemoryImageWithDerivedType()
template<typename T> void TMemoryImagePtr< T >::WriteMemoryImageWithDerivedType (FMemoryImageWriter & Writer, const FTypeLayoutDesc * DerivedTypeDesc) const inline
Definition at line 422 of file MemoryImage.h.
References check, Get(), StaticGetTypeLayoutDesc(), FMemoryImageWriter::WriteNullPointer(), FMemoryImageWriter::WriteObject(), and FMemoryImageWriter::WritePointer().
Field Documentation
[union]
union { ... } TMemoryImagePtr< T >
Frozen
template<typename T> FFrozenMemoryImagePtr TMemoryImagePtr< T >::Frozen
Definition at line 448 of file MemoryImage.h.
Referenced by TMemoryImagePtr(), TMemoryImagePtr(), GetFrozenOffsetFromThis(), GetFrozenPtrInternal(), GetFrozenTypeIndex(), IsFrozen(), operator=(), and operator=().
Packed
template<typename T> uint64 TMemoryImagePtr< T >::Packed
Definition at line 447 of file MemoryImage.h.
UnfrozenPtr
template<typename T> T* TMemoryImagePtr< T >::UnfrozenPtr
Definition at line 449 of file MemoryImage.h.
Referenced by TMemoryImagePtr(), TMemoryImagePtr(), TMemoryImagePtr(), Get(), IsNull(), IsValid(), operator=(), operator=(), and SafeDelete().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/MemoryImage.h