Unreal Engine 5.6 C++ API: FFloat16Color Class Reference
FFloat16Color Class Reference
RGBA Color made up of FFloat16.
#include "Float16Color.h"
Public Member Functions
FFloat16Color ()
Default constructor.
FFloat16Color (const FFloat16Color &Src)
Copy constructor.
FFloat16Color (const FLinearColor &Src)
Constructor from a linear color.
const FLinearColor GetFloats () const
uint16 * GetFourHalves ()
const uint16 * GetFourHalves () const
FFloat16Color & operator= (const FFloat16Color &Src)
assignment operator
bool operator== (const FFloat16Color &Src) const
Checks whether two colors are identical.
Data Fields
FFloat16 A
FFloat16 B
FFloat16 G
FFloat16 R
Detailed Description
RGBA Color made up of FFloat16.
Definition at line 12 of file Float16Color.h.
Constructor & Destructor Documentation
FFloat16Color() [1/3]
FORCEINLINE FFloat16Color::FFloat16Color () nodiscard
Default constructor.
Definition at line 55 of file Float16Color.h.
References FORCEINLINE.
Referenced by FFloat16Color(), operator=(), and operator==().
FFloat16Color() [2/3]
FORCEINLINE FFloat16Color::FFloat16Color (const FFloat16Color & Src) nodiscard
Copy constructor.
Definition at line 58 of file Float16Color.h.
References FFloat16Color(), A, B, FORCEINLINE, G, and R.
FFloat16Color() [3/3]
FORCEINLINE FFloat16Color::FFloat16Color (const FLinearColor & Src) nodiscard
Constructor from a linear color.
Definition at line 67 of file Float16Color.h.
References FORCEINLINE, and GetFourHalves().
Member Function Documentation
GetFloats()
FORCEINLINE const FLinearColor FFloat16Color::GetFloats () const nodiscard
Definition at line 73 of file Float16Color.h.
References FORCEINLINE, and GetFourHalves().
GetFourHalves() [1/2]
uint16 * FFloat16Color::GetFourHalves () inline nodiscard
Definition at line 22 of file Float16Color.h.
Referenced by FFloat16Color(), and GetFloats().
GetFourHalves() [2/2]
const uint16 * FFloat16Color::GetFourHalves () const inline nodiscard
Definition at line 26 of file Float16Color.h.
operator=()
FORCEINLINE FFloat16Color & FFloat16Color::operator= (const FFloat16Color & Src)
assignment operator
Definition at line 81 of file Float16Color.h.
References FFloat16Color(), A, B, FORCEINLINE, G, and R.
operator==()
FORCEINLINE bool FFloat16Color::operator== (const FFloat16Color & Src) const nodiscard
Checks whether two colors are identical.
Parameters
Src The other color.
Returns
true if the two colors are identical, otherwise false.
Definition at line 90 of file Float16Color.h.
References FFloat16Color(), A, B, FORCEINLINE, G, and R.
Field Documentation
A
FFloat16 FFloat16Color::A
Definition at line 19 of file Float16Color.h.
Referenced by FFloat16Color(), operator=(), and operator==().
B
FFloat16 FFloat16Color::B
Definition at line 18 of file Float16Color.h.
Referenced by FFloat16Color(), operator=(), and operator==().
G
FFloat16 FFloat16Color::G
Definition at line 17 of file Float16Color.h.
Referenced by FFloat16Color(), operator=(), and operator==().
R
FFloat16 FFloat16Color::R
Definition at line 16 of file Float16Color.h.
Referenced by FFloat16Color(), operator=(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/Float16Color.h