Unreal Engine 5.6 C++ API: IPixelStreamingInputModule Class Reference
IPixelStreamingInputModule Class Reference abstract
The public interface of the Pixel Streaming Input module.
#include "IPixelStreamingInputModule.h"
Public Member Functions
virtual TSharedPtr< class IInputDevice > CreateInputDevice (const TSharedRef< FGenericApplicationMessageHandler > &InMessageHandler) override=0
Attempts to create a new input device interface.
virtual TSharedPtr< IPixelStreamingInputHandler > CreateInputHandler ()=0
Create a Input Handler object.
DECLARE_MULTICAST_DELEGATE (FOnProtocolUpdated)
Static Public Member Functions
static IPixelStreamingInputModule & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Data Fields
FOnProtocolUpdated OnProtocolUpdated
Detailed Description
The public interface of the Pixel Streaming Input module.
Definition at line 13 of file IPixelStreamingInputModule.h.
Member Function Documentation
CreateInputDevice()
virtual TSharedPtr< class IInputDevice > IPixelStreamingInputModule::CreateInputDevice (const TSharedRef< FGenericApplicationMessageHandler > & InMessageHandler) override pure virtual
Attempts to create a new input device interface.
Returns
Interface to the new input device, if we were able to successfully create one
CreateInputHandler()
virtual TSharedPtr< IPixelStreamingInputHandler > IPixelStreamingInputModule::CreateInputHandler () pure virtual
Create a Input Handler object.
Returns
TSharedPtr<IPixelStreamingInputHandler> the input handler for this streamer
DECLARE_MULTICAST_DELEGATE()
IPixelStreamingInputModule::DECLARE_MULTICAST_DELEGATE (FOnProtocolUpdated)
Get()
IPixelStreamingInputModule & IPixelStreamingInputModule::Get () inline static
Singleton-like access to this module's interface.
Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 22 of file IPixelStreamingInputModule.h.
References FModuleManager::LoadModuleChecked().
IsAvailable()
bool IPixelStreamingInputModule::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 32 of file IPixelStreamingInputModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
Field Documentation
OnProtocolUpdated
FOnProtocolUpdated IPixelStreamingInputModule::OnProtocolUpdated
Definition at line 49 of file IPixelStreamingInputModule.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingInput/Public/IPixelStreamingInputModule.h