Unreal Engine 5.6 C++ API: FSkinWeightImportOptionsCustomization Class Reference
FSkinWeightImportOptionsCustomization Class Reference
Details customization for the import object, used to hide certain properties when needed and ensure we do not get duplicate profile names.
#include "SSkinWeightProfileImportOptions.h"
Public Member Functions
FSkinWeightImportOptionsCustomization (USkeletalMesh *InSkeletalMesh)
virtual void CustomizeDetails (IDetailLayoutBuilder &DetailBuilder) override
Called when details should be customized.
const bool IsProfileNameValid (const FString &NewName) const
FText OnGetProfileName () const
Public Member Functions inherited from IDetailCustomization
virtual ~IDetailCustomization ()
virtual void CustomizeDetails (const TSharedPtr< IDetailLayoutBuilder > &DetailBuilder)
Called when details should be customized, this version allows the customization to store a weak ptr to the layout builder.
virtual void PendingDelete ()
Called when no longer used and will be deleted.
Public Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedRef< IDetailCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDetailCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IDetailCustomization > MakeInstance (USkeletalMesh *InSkeletalMesh)
Protected Member Functions
void OnProfileNameChanged (const FText &InNewText)
void OnProfileNameCommitted (const FText &InNewText, ETextCommit::Type InTextCommit)
void UpdateNameRestriction ()
Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TSharedPtr< SEditableTextBox > NameEditTextBox
TSharedPtr< IPropertyHandle > ProfileNameHandle
TArray< FString > RestrictedNames
TWeakObjectPtr< USkeletalMesh > WeakSkeletalMesh
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Details customization for the import object, used to hide certain properties when needed and ensure we do not get duplicate profile names.
Definition at line 45 of file SSkinWeightProfileImportOptions.h.
Constructor & Destructor Documentation
FSkinWeightImportOptionsCustomization()
FSkinWeightImportOptionsCustomization::FSkinWeightImportOptionsCustomization (USkeletalMesh * InSkeletalMesh) inline
Definition at line 48 of file SSkinWeightProfileImportOptions.h.
References WeakSkeletalMesh.
Referenced by MakeInstance().
Member Function Documentation
CustomizeDetails()
virtual void FSkinWeightImportOptionsCustomization::CustomizeDetails (IDetailLayoutBuilder & DetailBuilder) override virtual
Called when details should be customized.
Implements IDetailCustomization.
IsProfileNameValid()
const bool FSkinWeightImportOptionsCustomization::IsProfileNameValid (const FString & NewName) const
MakeInstance()
TSharedRef< IDetailCustomization > FSkinWeightImportOptionsCustomization::MakeInstance (USkeletalMesh * InSkeletalMesh) inline static
Definition at line 49 of file SSkinWeightProfileImportOptions.h.
References FSkinWeightImportOptionsCustomization(), and MakeShareable().
OnGetProfileName()
FText FSkinWeightImportOptionsCustomization::OnGetProfileName () const
OnProfileNameChanged()
void FSkinWeightImportOptionsCustomization::OnProfileNameChanged (const FText & InNewText) protected
OnProfileNameCommitted()
void FSkinWeightImportOptionsCustomization::OnProfileNameCommitted (const FText & InNewText, ETextCommit::Type InTextCommit) protected
UpdateNameRestriction()
void FSkinWeightImportOptionsCustomization::UpdateNameRestriction () protected
Field Documentation
NameEditTextBox
TSharedPtr<SEditableTextBox> FSkinWeightImportOptionsCustomization::NameEditTextBox protected
Definition at line 55 of file SSkinWeightProfileImportOptions.h.
ProfileNameHandle
TSharedPtr<IPropertyHandle> FSkinWeightImportOptionsCustomization::ProfileNameHandle protected
Definition at line 56 of file SSkinWeightProfileImportOptions.h.
RestrictedNames
TArray<FString> FSkinWeightImportOptionsCustomization::RestrictedNames protected
Definition at line 58 of file SSkinWeightProfileImportOptions.h.
WeakSkeletalMesh
TWeakObjectPtr<USkeletalMesh> FSkinWeightImportOptionsCustomization::WeakSkeletalMesh protected
Definition at line 57 of file SSkinWeightProfileImportOptions.h.
Referenced by FSkinWeightImportOptionsCustomization().
The documentation for this class was generated from the following file:
Editor/Persona/Public/SSkinWeightProfileImportOptions.h