Unreal Engine 5.6 C++ API: HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef Class Reference
HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef Class Reference
#include "SpmcAnalysisResultQueue.h"
Public Member Functions
FScopedItemConsumeRef ()
FScopedItemConsumeRef (const FEntry *InEntry, FReadCursor *InReadCursor)
FScopedItemConsumeRef (const FScopedItemConsumeRef &Other)=delete
FScopedItemConsumeRef (FScopedItemConsumeRef &&Other)
~FScopedItemConsumeRef ()
operator bool () const
const T & operator* ()
const T * operator-> ()
FScopedItemConsumeRef & operator= (const FScopedItemConsumeRef &Other)=delete
Data Fields
bool DiscontinuityDetectedInLastRead { false }
const FEntry * Entry
FReadCursor * ReadCursor
Detailed Description
template<typename T>
class HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef
Definition at line 116 of file SpmcAnalysisResultQueue.h.
Constructor & Destructor Documentation
FScopedItemConsumeRef() [1/4]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef () inline
Definition at line 119 of file SpmcAnalysisResultQueue.h.
References Entry, and ReadCursor.
Referenced by FScopedItemConsumeRef(), FScopedItemConsumeRef(), and operator=().
FScopedItemConsumeRef() [2/4]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef (const FEntry * InEntry, FReadCursor * InReadCursor) inline
Definition at line 125 of file SpmcAnalysisResultQueue.h.
References Entry, HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::IncrementIndex(), HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::NextExpectedSerialNumber, HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::Queue, and ReadCursor.
FScopedItemConsumeRef() [3/4]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef (const FScopedItemConsumeRef & Other) delete
References FScopedItemConsumeRef(), and Other.
FScopedItemConsumeRef() [4/4]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef (FScopedItemConsumeRef && Other) inline
Definition at line 154 of file SpmcAnalysisResultQueue.h.
References FScopedItemConsumeRef(), DiscontinuityDetectedInLastRead, Entry, Other, and ReadCursor.
~FScopedItemConsumeRef()
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::~FScopedItemConsumeRef () inline
Definition at line 163 of file SpmcAnalysisResultQueue.h.
References check, and Entry.
Member Function Documentation
operator bool()
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::operator bool () const inline
Definition at line 183 of file SpmcAnalysisResultQueue.h.
References Entry.
operator*()
template<typename T> const T & HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::operator* () inline
Definition at line 177 of file SpmcAnalysisResultQueue.h.
References check, and Entry.
operator->()
template<typename T> const T * HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::operator-> () inline
Definition at line 172 of file SpmcAnalysisResultQueue.h.
References Entry.
operator=()
template<typename T> FScopedItemConsumeRef & HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::operator= (const FScopedItemConsumeRef & Other) delete
References FScopedItemConsumeRef(), and Other.
Field Documentation
DiscontinuityDetectedInLastRead
template<typename T> bool HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::DiscontinuityDetectedInLastRead { false }
Definition at line 188 of file SpmcAnalysisResultQueue.h.
Referenced by FScopedItemConsumeRef().
Entry
template<typename T> const FEntry* HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::Entry
Definition at line 189 of file SpmcAnalysisResultQueue.h.
Referenced by FScopedItemConsumeRef(), FScopedItemConsumeRef(), FScopedItemConsumeRef(), ~FScopedItemConsumeRef(), operator bool(), operator*(), and operator->().
ReadCursor
template<typename T> FReadCursor* HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::ReadCursor
Definition at line 190 of file SpmcAnalysisResultQueue.h.
Referenced by FScopedItemConsumeRef(), FScopedItemConsumeRef(), and FScopedItemConsumeRef().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixMetasound/Public/HarmonixMetasound/Analysis/SpmcAnalysisResultQueue.h