Unreal Engine 5.6 C++ API: FRDGPooledBuffer Class Reference
FRDGPooledBuffer Class Reference final
#include "RenderGraphResources.h"
Public Member Functions
FRDGPooledBuffer (FRHICommandListBase &RHICmdList, TRefCountPtr< FRHIBuffer > InBuffer, const FRDGBufferDesc &InDesc, uint32 InNumAllocatedElements, const TCHAR *InName)
RENDERCORE_API FRDGPooledBuffer (TRefCountPtr< FRHIBuffer > InBuffer, const FRDGBufferDesc &InDesc, uint32 InNumAllocatedElements, const TCHAR *InName)
FORCEINLINE uint32 GetAlignedSize () const
FORCEINLINE uint64 GetCommittedSize () const
const TCHAR * GetName () const
FORCEINLINE FRHIShaderResourceView * GetOrCreateSRV (FRHICommandListBase &RHICmdList, const FRHIBufferSRVCreateInfo &SRVDesc)
Finds a SRV matching the descriptor in the cache or creates a new one and updates the cache.
FORCEINLINE FRHIUnorderedAccessView * GetOrCreateUAV (FRHICommandListBase &RHICmdList, const FRHIBufferUAVCreateInfo &UAVDesc)
Finds a UAV matching the descriptor in the cache or creates a new one and updates the cache.
FORCEINLINE FRHIBuffer * GetRHI () const
Returns the RHI buffer.
FORCEINLINE uint32 GetSize () const
FORCEINLINE FRHIShaderResourceView * GetSRV ()
Returns the default SRV.
FORCEINLINE FRHIShaderResourceView * GetSRV (FRHICommandListBase &RHICmdList, const FRHIBufferSRVCreateInfo &SRVDesc)
UE_DEPRECATED (5.3, "GetOrCreateSRV now requires a command list.") FORCEINLINE FRHIShaderResourceView *GetOrCreateSRV(const FRHIBufferSRVCreateInfo &SRVDesc)
UE_DEPRECATED (5.3, "GetOrCreateUAV now requires a command list.") FORCEINLINE FRHIUnorderedAccessView *GetOrCreateUAV(const FRHIBufferUAVCreateInfo &UAVDesc)
UE_DEPRECATED (5.3, "GetSRV now requires a command list.") FORCEINLINE FRHIShaderResourceView *GetSRV(const FRHIBufferSRVCreateInfo &SRVDesc)
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Data Fields
const FRDGBufferDesc Desc
Private Member Functions
FRDGBufferDesc GetAlignedDesc () const
void SetCommittedSize (uint64 InCommittedSizeInBytes)
void SetDebugLabelName (FRHICommandListBase &RHICmdList, const TCHAR *InName)
Private Attributes
TRefCountPtr< FRHIBuffer > Buffer
FRHIShaderResourceView * CachedSRV = nullptr
uint64 CommittedSizeInBytes = UINT64_MAX
TOptional< FRHITransientAllocationFences > Fences
friend FRDGBufferPool
friend FRDGBuilder
uint32 LastUsedFrame = 0
const TCHAR * Name = nullptr
const uint32 NumAllocatedElements
FRHIBufferViewCache ViewCache
Detailed Description
Definition at line 1194 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGPooledBuffer() [1/2]
FRDGPooledBuffer::FRDGPooledBuffer (FRHICommandListBase & RHICmdList, TRefCountPtr< FRHIBuffer > InBuffer, const FRDGBufferDesc & InDesc, uint32 InNumAllocatedElements, const TCHAR * InName) inline
Definition at line 1198 of file RenderGraphResources.h.
References Buffer, Desc, EnumHasAnyFlags(), Fences, InName, MoveTemp(), Name, NumAllocatedElements, and FRDGBufferDesc::Usage.
FRDGPooledBuffer() [2/2]
RENDERCORE_API FRDGPooledBuffer::FRDGPooledBuffer (TRefCountPtr< FRHIBuffer > InBuffer, const FRDGBufferDesc & InDesc, uint32 InNumAllocatedElements, const TCHAR * InName)
References InName.
Member Function Documentation
GetAlignedDesc()
FRDGBufferDesc FRDGPooledBuffer::GetAlignedDesc () const inline private
Definition at line 1274 of file RenderGraphResources.h.
References Desc, NumAllocatedElements, and FRDGBufferDesc::NumElements.
GetAlignedSize()
FORCEINLINE uint32 FRDGPooledBuffer::GetAlignedSize () const inline
Definition at line 1254 of file RenderGraphResources.h.
References Desc, FORCEINLINE, and NumAllocatedElements.
GetCommittedSize()
FORCEINLINE uint64 FRDGPooledBuffer::GetCommittedSize () const inline
Definition at line 1259 of file RenderGraphResources.h.
References CommittedSizeInBytes, FORCEINLINE, GetSize(), and FMath::Min.
GetName()
const TCHAR * FRDGPooledBuffer::GetName () const inline
Definition at line 1264 of file RenderGraphResources.h.
References Name.
GetOrCreateSRV()
FORCEINLINE FRHIShaderResourceView * FRDGPooledBuffer::GetOrCreateSRV (FRHICommandListBase & RHICmdList, const FRHIBufferSRVCreateInfo & SRVDesc) inline
Finds a SRV matching the descriptor in the cache or creates a new one and updates the cache.
Definition at line 1220 of file RenderGraphResources.h.
References Buffer, FORCEINLINE, and ViewCache.
Referenced by GetSRV(), UE_DEPRECATED(), and UE_DEPRECATED().
GetOrCreateUAV()
FORCEINLINE FRHIUnorderedAccessView * FRDGPooledBuffer::GetOrCreateUAV (FRHICommandListBase & RHICmdList, const FRHIBufferUAVCreateInfo & UAVDesc) inline
Finds a UAV matching the descriptor in the cache or creates a new one and updates the cache.
Definition at line 1217 of file RenderGraphResources.h.
References Buffer, FORCEINLINE, and ViewCache.
Referenced by UE_DEPRECATED().
GetRHI()
FORCEINLINE FRHIBuffer * FRDGPooledBuffer::GetRHI () const inline
Returns the RHI buffer.
Definition at line 1229 of file RenderGraphResources.h.
References Buffer, and FORCEINLINE.
GetSize()
FORCEINLINE uint32 FRDGPooledBuffer::GetSize () const inline
Definition at line 1249 of file RenderGraphResources.h.
References Desc, and FORCEINLINE.
Referenced by GetCommittedSize(), and SetCommittedSize().
GetSRV() [1/2]
FORCEINLINE FRHIShaderResourceView * FRDGPooledBuffer::GetSRV () inline
Returns the default SRV.
Definition at line 1232 of file RenderGraphResources.h.
References CachedSRV, checkf, FORCEINLINE, and TEXT.
Referenced by UE_DEPRECATED().
GetSRV() [2/2]
FORCEINLINE FRHIShaderResourceView * FRDGPooledBuffer::GetSRV (FRHICommandListBase & RHICmdList, const FRHIBufferSRVCreateInfo & SRVDesc) inline
Definition at line 1244 of file RenderGraphResources.h.
References FORCEINLINE, and GetOrCreateSRV().
SetCommittedSize()
void FRDGPooledBuffer::SetCommittedSize (uint64 InCommittedSizeInBytes) inline private
Definition at line 1285 of file RenderGraphResources.h.
References checkf, CommittedSizeInBytes, Desc, EnumHasAllFlags(), GetSize(), and TEXT.
SetDebugLabelName()
void FRDGPooledBuffer::SetDebugLabelName (FRHICommandListBase & RHICmdList, const TCHAR * InName) private
References InName.
UE_DEPRECATED() [1/3]
FRDGPooledBuffer::UE_DEPRECATED (5. 3, "GetOrCreateSRV now requires a command list.") const & inline
Definition at line 1225 of file RenderGraphResources.h.
References Buffer, FORCEINLINE, GetOrCreateSRV(), and ViewCache.
UE_DEPRECATED() [2/3]
FRDGPooledBuffer::UE_DEPRECATED (5. 3, "GetOrCreateUAV now requires a command list.") const & inline
Definition at line 1222 of file RenderGraphResources.h.
References Buffer, FORCEINLINE, GetOrCreateUAV(), and ViewCache.
UE_DEPRECATED() [3/3]
FRDGPooledBuffer::UE_DEPRECATED (5. 3, "GetSRV now requires a command list.") const & inline
Definition at line 1238 of file RenderGraphResources.h.
References FORCEINLINE, GetOrCreateSRV(), and GetSRV().
Field Documentation
Buffer
TRefCountPtr<FRHIBuffer> FRDGPooledBuffer::Buffer private
Definition at line 1270 of file RenderGraphResources.h.
Referenced by FRDGPooledBuffer(), GetOrCreateSRV(), GetOrCreateUAV(), GetRHI(), UE_DEPRECATED(), and UE_DEPRECATED().
CachedSRV
FRHIShaderResourceView* FRDGPooledBuffer::CachedSRV = nullptr private
Definition at line 1271 of file RenderGraphResources.h.
Referenced by GetSRV().
CommittedSizeInBytes
uint64 FRDGPooledBuffer::CommittedSizeInBytes = UINT64_MAX private
Definition at line 1302 of file RenderGraphResources.h.
Referenced by GetCommittedSize(), and SetCommittedSize().
Desc
const FRDGBufferDesc FRDGPooledBuffer::Desc
Definition at line 1214 of file RenderGraphResources.h.
Referenced by FRDGPooledBuffer(), GetAlignedDesc(), GetAlignedSize(), GetSize(), and SetCommittedSize().
Fences
TOptional<FRHITransientAllocationFences> FRDGPooledBuffer::Fences private
Definition at line 1312 of file RenderGraphResources.h.
Referenced by FRDGPooledBuffer().
FRDGBufferPool
friend FRDGPooledBuffer::FRDGBufferPool private
Definition at line 1315 of file RenderGraphResources.h.
FRDGBuilder
friend FRDGPooledBuffer::FRDGBuilder private
Definition at line 1314 of file RenderGraphResources.h.
LastUsedFrame
uint32 FRDGPooledBuffer::LastUsedFrame = 0 private
Definition at line 1310 of file RenderGraphResources.h.
Name
const TCHAR* FRDGPooledBuffer::Name = nullptr private
Definition at line 1298 of file RenderGraphResources.h.
Referenced by FRDGPooledBuffer(), and GetName().
NumAllocatedElements
const uint32 FRDGPooledBuffer::NumAllocatedElements private
Definition at line 1309 of file RenderGraphResources.h.
Referenced by FRDGPooledBuffer(), GetAlignedDesc(), and GetAlignedSize().
ViewCache
FRHIBufferViewCache FRDGPooledBuffer::ViewCache private
Definition at line 1272 of file RenderGraphResources.h.
Referenced by GetOrCreateSRV(), GetOrCreateUAV(), UE_DEPRECATED(), and UE_DEPRECATED().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphResources.h