Unreal Engine 5.6 C++ API: FManagedStorageScopeFileLock Class Reference
FManagedStorageScopeFileLock Class Reference
#include "IPlatformFileManagedStorageWrapper.h"
Public Member Functions
FManagedStorageScopeFileLock (const FManagedStorageScopeFileLock &)=delete
FManagedStorageScopeFileLock (FManagedStorageScopeFileLock &&InOther)=delete
FManagedStorageScopeFileLock (FPersistentManagedFile InManagedFile)
~FManagedStorageScopeFileLock ()
FManagedStorageScopeFileLock & operator= (const FManagedStorageScopeFileLock &)=delete
FManagedStorageScopeFileLock & operator= (FManagedStorageScopeFileLock &&InOther)=delete
void Unlock ()
Private Member Functions
void Lock ()
Private Attributes
FPersistentManagedFile ManagedFile
FCriticalSection * pFileCS = nullptr
Detailed Description
Definition at line 109 of file IPlatformFileManagedStorageWrapper.h.
Constructor & Destructor Documentation
FManagedStorageScopeFileLock() [1/3]
FManagedStorageScopeFileLock::FManagedStorageScopeFileLock (FPersistentManagedFile InManagedFile) inline
Definition at line 112 of file IPlatformFileManagedStorageWrapper.h.
References Lock(), ManagedFile, and MoveTemp().
Referenced by FManagedStorageScopeFileLock(), FManagedStorageScopeFileLock(), operator=(), and operator=().
~FManagedStorageScopeFileLock()
FManagedStorageScopeFileLock::~FManagedStorageScopeFileLock () inline
Definition at line 118 of file IPlatformFileManagedStorageWrapper.h.
References Unlock().
FManagedStorageScopeFileLock() [2/3]
FManagedStorageScopeFileLock::FManagedStorageScopeFileLock (const FManagedStorageScopeFileLock &) delete
References FManagedStorageScopeFileLock().
FManagedStorageScopeFileLock() [3/3]
FManagedStorageScopeFileLock::FManagedStorageScopeFileLock (FManagedStorageScopeFileLock && InOther) delete
References FManagedStorageScopeFileLock().
Member Function Documentation
Lock()
void FManagedStorageScopeFileLock::Lock () private
Referenced by FManagedStorageScopeFileLock().
operator=() [1/2]
FManagedStorageScopeFileLock & FManagedStorageScopeFileLock::operator= (const FManagedStorageScopeFileLock &) delete
References FManagedStorageScopeFileLock().
operator=() [2/2]
FManagedStorageScopeFileLock & FManagedStorageScopeFileLock::operator= (FManagedStorageScopeFileLock && InOther) delete
References FManagedStorageScopeFileLock().
Unlock()
void FManagedStorageScopeFileLock::Unlock ()
Referenced by ~FManagedStorageScopeFileLock().
Field Documentation
ManagedFile
FPersistentManagedFile FManagedStorageScopeFileLock::ManagedFile private
Definition at line 135 of file IPlatformFileManagedStorageWrapper.h.
Referenced by FManagedStorageScopeFileLock().
pFileCS
FCriticalSection* FManagedStorageScopeFileLock::pFileCS = nullptr private
Definition at line 136 of file IPlatformFileManagedStorageWrapper.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IPlatformFileManagedStorageWrapper.h