Unreal Engine 5.6 C++ API: FSceneViewStateInterface Class Reference
FSceneViewStateInterface Class Reference abstract
The scene manager's persistent view state.
#include "SceneManagement.h"
Public Member Functions
FSceneViewStateInterface ()
virtual void ActivateFrozenViewMatrices (FSceneView &SceneView)=0
If frozen view matrices are available, set those as active on the SceneView.
virtual void AddLumenSceneData (FSceneInterface *InScene, float SurfaceCacheResolution=1.0f)
Similar to above, but adds Lumen Scene Data.
virtual void AddReferencedObjects (FReferenceCollector &Collector)=0
virtual void ClearMIDPool (FStringView MidParentRootPath={})=0
Clears the pool of mids being referenced by this view state.
virtual void Destroy ()=0
Called in the game thread to destroy the view state.
virtual FSceneViewState * GetConcreteViewState ()=0
virtual FRDGPooledBuffer * GetCurrentEyeAdaptationBuffer () const =0
Returns the eye adaptation buffer.
virtual uint32 GetCurrentTemporalAASampleIndex () const =0
virtual uint32 GetDistanceFieldTemporalSampleIndex () const =0
returns the distance field temporal sample index
virtual const FViewMatrices * GetFrozenViewMatrices () const =0
If frozen view matrices are available, return a pointer to them.
virtual float GetLastEyeAdaptationExposure () const =0
Returns the eye adaptation exposure.
virtual uint32 GetOcclusionFrameCounter () const =0
returns the occlusion frame counter
virtual float GetPreExposure () const =0
Returns the current PreExposure value.
virtual UMaterialInstanceDynamic * GetReusableMID (class UMaterialInterface *InSource)=0
Allows MIDs being created and released during view rendering without the overhead of creating and releasing objects As MID are not allowed to be parent of MID this gets fixed up by parenting it to the next Material or MIC.
virtual ESequencerState GetSequencerState ()=0
virtual SIZE_T GetSizeBytes () const
virtual const FTemporalLODState & GetTemporalLODState () const =0
virtual FTemporalLODState & GetTemporalLODState ()=0
Returns the temporal LOD struct from the viewstate.
virtual float GetTemporalLODTransition () const =0
Returns the blend factor between the last two LOD samples.
virtual uint32 GetViewKey () const =0
returns a unique key for the view state, non-zero
virtual FRDGTextureRef GetVolumetricCloudTexture (FRDGBuilder &GraphBuilder)=0
virtual FVector2f GetVolumetricCloudTextureUVMax () const =0
virtual FVector2f GetVolumetricCloudTextureUVScale () const =0
virtual bool HasLumenSceneData () const =0
bool HasValidEyeAdaptationBuffer () const
Tells if the eye adaptation buffer exists without attempting to allocate it.
virtual void OnStartPostProcessing (FSceneView &CurrentView)=0
Resets pool for GetReusableMID()
virtual void RemoveLumenSceneData (FSceneInterface *InScene)
virtual void ResetViewState ()=0
virtual void RestoreUnfrozenViewMatrices (FSceneView &SceneView)=0
If frozen view matrices were set, restore the previous view matrices.
virtual void SetSequencerState (ESequencerState InSequencerState)=0
virtual void SystemMemoryMirrorBackup (FSceneViewStateSystemMemoryMirror *SystemMemoryMirror)=0
virtual void SystemMemoryMirrorRestore (FSceneViewStateSystemMemoryMirror *SystemMemoryMirror)=0
UE_DEPRECATED (5.2, "Use GetCurrentEyeAdaptationBuffer() instead.") virtual IPooledRenderTarget *GetCurrentEyeAdaptationTexture() const =0
UE_DEPRECATED (5.2, "Use HasValidEyeAdaptationBuffer() instead.") bool HasValidEyeAdaptationTexture() const
UE_DEPRECATED (5.3, "GetViewParent is deprecated") const FSceneViewStateInterface *GetViewParent() const
UE_DEPRECATED (5.3, "GetViewParent is deprecated") FSceneViewStateInterface *GetViewParent()
UE_DEPRECATED (5.3, "HasViewParent is deprecated") bool HasViewParent() const
UE_DEPRECATED (5.3, "IsViewParent is deprecated") bool IsViewParent() const
UE_DEPRECATED (5.3, "SetViewParent is deprecated") void SetViewParent(FSceneViewStateInterface *)
Static Public Member Functions
static TPimplPtr< FSceneViewStateSystemMemoryMirror > SystemMemoryMirrorAllocate ()
Scene view state mirroring to system memory, useful for offline high resolution tiled rendering (such as via Movie Render Queue).
Protected Member Functions
virtual ~FSceneViewStateInterface ()
Protected Attributes
UE_DEPRECATED(5.2, "Use bValidEyeAdaptationBuffer instead.") uint8 bValidEyeAdaptationTexture uint8 bValidEyeAdaptationBuffer: 1
Friends
class FScene
Detailed Description
The scene manager's persistent view state.
Definition at line 127 of file SceneManagement.h.
Constructor & Destructor Documentation
FSceneViewStateInterface()
FSceneViewStateInterface::FSceneViewStateInterface () inline
Definition at line 130 of file SceneManagement.h.
References bValidEyeAdaptationBuffer.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
~FSceneViewStateInterface()
virtual FSceneViewStateInterface::~FSceneViewStateInterface () inline protected virtual
Definition at line 280 of file SceneManagement.h.
Member Function Documentation
ActivateFrozenViewMatrices()
virtual void FSceneViewStateInterface::ActivateFrozenViewMatrices (FSceneView & SceneView) pure virtual
If frozen view matrices are available, set those as active on the SceneView.
AddLumenSceneData()
virtual void FSceneViewStateInterface::AddLumenSceneData (FSceneInterface * InScene, float SurfaceCacheResolution = 1.0f) inline virtual
Similar to above, but adds Lumen Scene Data.
Definition at line 249 of file SceneManagement.h.
AddReferencedObjects()
virtual void FSceneViewStateInterface::AddReferencedObjects (FReferenceCollector & Collector) pure virtual
ClearMIDPool()
virtual void FSceneViewStateInterface::ClearMIDPool (FStringView MidParentRootPath = {}) pure virtual
Clears the pool of mids being referenced by this view state.
Destroy()
virtual void FSceneViewStateInterface::Destroy () pure virtual
Called in the game thread to destroy the view state.
GetConcreteViewState()
virtual FSceneViewState * FSceneViewStateInterface::GetConcreteViewState () pure virtual
Returns
the derived view state object
GetCurrentEyeAdaptationBuffer()
virtual FRDGPooledBuffer * FSceneViewStateInterface::GetCurrentEyeAdaptationBuffer () const pure virtual
Returns the eye adaptation buffer.
References GetCurrentEyeAdaptationBuffer().
Referenced by GetCurrentEyeAdaptationBuffer().
GetCurrentTemporalAASampleIndex()
virtual uint32 FSceneViewStateInterface::GetCurrentTemporalAASampleIndex () const pure virtual
GetDistanceFieldTemporalSampleIndex()
virtual uint32 FSceneViewStateInterface::GetDistanceFieldTemporalSampleIndex () const pure virtual
returns the distance field temporal sample index
GetFrozenViewMatrices()
virtual const FViewMatrices * FSceneViewStateInterface::GetFrozenViewMatrices () const pure virtual
If frozen view matrices are available, return a pointer to them.
GetLastEyeAdaptationExposure()
virtual float FSceneViewStateInterface::GetLastEyeAdaptationExposure () const pure virtual
Returns the eye adaptation exposure.
References GetLastEyeAdaptationExposure().
Referenced by GetLastEyeAdaptationExposure().
GetOcclusionFrameCounter()
virtual uint32 FSceneViewStateInterface::GetOcclusionFrameCounter () const pure virtual
returns the occlusion frame counter
References GetOcclusionFrameCounter().
Referenced by GetOcclusionFrameCounter().
GetPreExposure()
virtual float FSceneViewStateInterface::GetPreExposure () const pure virtual
Returns the current PreExposure value.
PreExposure is a custom scale applied to the scene color to prevent buffer overflow.
References GetPreExposure().
Referenced by GetPreExposure().
GetReusableMID()
virtual UMaterialInstanceDynamic * FSceneViewStateInterface::GetReusableMID (class UMaterialInterface * InSource) pure virtual
Allows MIDs being created and released during view rendering without the overhead of creating and releasing objects As MID are not allowed to be parent of MID this gets fixed up by parenting it to the next Material or MIC.
Parameters
InSource can be Material, MIC or MID, must not be 0
GetSequencerState()
virtual ESequencerState FSceneViewStateInterface::GetSequencerState () pure virtual
References GetSequencerState().
Referenced by GetSequencerState().
GetSizeBytes()
virtual SIZE_T FSceneViewStateInterface::GetSizeBytes () const inline virtual
Definition at line 144 of file SceneManagement.h.
GetTemporalLODState() [1/2]
virtual const FTemporalLODState & FSceneViewStateInterface::GetTemporalLODState () const pure virtual
GetTemporalLODState() [2/2]
virtual FTemporalLODState & FSceneViewStateInterface::GetTemporalLODState () pure virtual
Returns the temporal LOD struct from the viewstate.
GetTemporalLODTransition()
virtual float FSceneViewStateInterface::GetTemporalLODTransition () const pure virtual
Returns the blend factor between the last two LOD samples.
GetViewKey()
virtual uint32 FSceneViewStateInterface::GetViewKey () const pure virtual
returns a unique key for the view state, non-zero
GetVolumetricCloudTexture()
virtual FRDGTextureRef FSceneViewStateInterface::GetVolumetricCloudTexture (FRDGBuilder & GraphBuilder) pure virtual
GetVolumetricCloudTextureUVMax()
virtual FVector2f FSceneViewStateInterface::GetVolumetricCloudTextureUVMax () const pure virtual
GetVolumetricCloudTextureUVScale()
virtual FVector2f FSceneViewStateInterface::GetVolumetricCloudTextureUVScale () const pure virtual
HasLumenSceneData()
virtual bool FSceneViewStateInterface::HasLumenSceneData () const pure virtual
HasValidEyeAdaptationBuffer()
bool FSceneViewStateInterface::HasValidEyeAdaptationBuffer () const inline
Tells if the eye adaptation buffer exists without attempting to allocate it.
Definition at line 210 of file SceneManagement.h.
References bValidEyeAdaptationBuffer.
OnStartPostProcessing()
virtual void FSceneViewStateInterface::OnStartPostProcessing (FSceneView & CurrentView) pure virtual
Resets pool for GetReusableMID()
RemoveLumenSceneData()
virtual void FSceneViewStateInterface::RemoveLumenSceneData (FSceneInterface * InScene) inline virtual
Definition at line 250 of file SceneManagement.h.
ResetViewState()
virtual void FSceneViewStateInterface::ResetViewState () pure virtual
RestoreUnfrozenViewMatrices()
virtual void FSceneViewStateInterface::RestoreUnfrozenViewMatrices (FSceneView & SceneView) pure virtual
If frozen view matrices were set, restore the previous view matrices.
SetSequencerState()
virtual void FSceneViewStateInterface::SetSequencerState (ESequencerState InSequencerState) pure virtual
References SetSequencerState().
Referenced by SetSequencerState().
SystemMemoryMirrorAllocate()
TPimplPtr< FSceneViewStateSystemMemoryMirror > FSceneViewStateInterface::SystemMemoryMirrorAllocate () static
Scene view state mirroring to system memory, useful for offline high resolution tiled rendering (such as via Movie Render Queue).
Very slow and memory intensive! A single instance of FSceneViewStateSystemMemoryMirror should be shared for all tile scene view states, as it can internally share some of the memory cost.
SystemMemoryMirrorBackup()
virtual void FSceneViewStateInterface::SystemMemoryMirrorBackup (FSceneViewStateSystemMemoryMirror * SystemMemoryMirror) pure virtual
SystemMemoryMirrorRestore()
virtual void FSceneViewStateInterface::SystemMemoryMirrorRestore (FSceneViewStateSystemMemoryMirror * SystemMemoryMirror) pure virtual
UE_DEPRECATED() [1/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 2, "Use GetCurrentEyeAdaptationBuffer() instead.") const pure virtual
UE_DEPRECATED() [2/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 2, "Use HasValidEyeAdaptationBuffer() instead.") const inline
Definition at line 201 of file SceneManagement.h.
References bool, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED() [3/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 3, "GetViewParent is deprecated") const inline
Definition at line 259 of file SceneManagement.h.
References FSceneViewStateInterface().
UE_DEPRECATED() [4/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 3, "GetViewParent is deprecated") inline
Definition at line 256 of file SceneManagement.h.
References FSceneViewStateInterface().
UE_DEPRECATED() [5/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 3, "HasViewParent is deprecated") const inline
Definition at line 262 of file SceneManagement.h.
References bool.
UE_DEPRECATED() [6/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 3, "IsViewParent is deprecated") const inline
Definition at line 265 of file SceneManagement.h.
References bool.
UE_DEPRECATED() [7/7]
FSceneViewStateInterface::UE_DEPRECATED (5. 3, "SetViewParent is deprecated") inline
Definition at line 253 of file SceneManagement.h.
References FSceneViewStateInterface().
Friends And Related Symbol Documentation
FScene
friend class FScene friend
Definition at line 287 of file SceneManagement.h.
References FScene.
Referenced by FScene.
Field Documentation
bValidEyeAdaptationBuffer
UE_DEPRECATED (5.2, "Use bValidEyeAdaptationBuffer instead.") uint8 bValidEyeAdaptationTexture uint8 FSceneViewStateInterface::bValidEyeAdaptationBuffer protected
Definition at line 284 of file SceneManagement.h.
Referenced by FSceneViewStateInterface(), and HasValidEyeAdaptationBuffer().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneManagement.h