Unreal Engine 5.6 C++ API: FMallocBinned2 Class Reference
FMallocBinned2 Class Reference
#include "MallocBinned2.h"
Data Structures
struct FFreeBlock
Information about a piece of free memory.
struct FPoolInfo
struct FPoolList
struct FPoolTable
Pool table.
Public Member Functions
FMallocBinned2 ()
virtual ~FMallocBinned2 ()
void CanaryFail (const FFreeBlock *Block) const
FORCEINLINE void CanaryTest (const FFreeBlock *Block) const
virtual void DumpAllocatorStats (class FOutputDevice &Ar) override
Dumps current allocator stats to the log.
void FlushCurrentThreadCacheInternal (bool bNewEpochOnly=false)
UE_AUTORTFM_NOAUTORTFM virtual FORCEINLINE void Free (void *Ptr) override
Free.
void FreeBundles (FBundleNode *Bundles, uint32 PoolIndex)
void FreeExternal (void *Ptr)
virtual FORCEINLINE bool GetAllocationSize (void *Ptr, SIZE_T &SizeOut) override
If possible determine the size of the memory allocated at the given address.
virtual const TCHAR * GetDescriptiveName () override
Gets descriptive name for logging purposes.
virtual uint64 GetImmediatelyFreeableCachedMemorySize () const override
Returns the amount of free memory cached by the allocator that can be returned to the system in case of a memory shortage.
FORCEINLINE bool GetSmallAllocationSize (void *Ptr, SIZE_T &SizeOut) const
virtual uint64 GetTotalFreeCachedMemorySize () const override
Returns the amount of total free memory cached by the allocator.
virtual bool IsInternallyThreadSafe () const override
Returns if the allocator is guaranteed to be thread-safe and therefore doesn't need a unnecessary thread-safety wrapper around it.
UE_AUTORTFM_NOAUTORTFM virtual FORCEINLINE void * Malloc (SIZE_T Size, uint32 Alignment) override
Malloc.
void * MallocExternalLarge (SIZE_T Size, uint32 Alignment)
void * MallocExternalSmall (SIZE_T Size, uint32 Alignment)
virtual void OnMallocInitialized () override
Notifies the malloc implementation that initialization of all allocators in GMalloc is complete, so it's safe to initialize any extra features that require "regular" allocations.
virtual void OnPostFork () override
Notifies the malloc implementation that the process has forked so we can try and avoid dirtying pre-fork pages.
virtual void OnPreFork () override
Notifies the malloc implementation that the process is about to fork.
FORCEINLINE uint32 PoolIndexToBinSize (uint32 PoolIndex) const
virtual FORCEINLINE SIZE_T QuantizeSize (SIZE_T Count, uint32 Alignment) override
For some allocators this will return the actual size that should be requested to eliminate internal fragmentation.
UE_AUTORTFM_NOAUTORTFM virtual FORCEINLINE void * Realloc (void *Ptr, SIZE_T NewSize, uint32 Alignment) override
Realloc.
void * ReallocExternal (void *Ptr, SIZE_T NewSize, uint32 Alignment)
virtual void Trim (bool bTrimThreadCaches) override
Releases as much memory as possible.
virtual void UpdateStats () override
Called once per frame, gathers and sets all memory allocator statistics into the corresponding stats.
virtual bool ValidateHeap () override
Validates the allocator's heap.
Public Member Functions inherited from TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >
virtual void GetAllocatorStats (FGenericMemoryStats &OutStats) override
Writes allocator stats from the last update into the specified destination.
Public Member Functions inherited from FMalloc
virtual void InitializeStatsMetadata ()
Initializes stats metadata.
virtual void * MallocZeroed (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Malloc zeroed memory.
virtual void * TryMalloc (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryMalloc - like Malloc(), but may return a nullptr result if the allocation request cannot be satisfied.
virtual void * TryMallocZeroed (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryMalloc - like MallocZeroed(), but may return a nullptr result if the allocation request cannot be satisfied.
virtual void * TryRealloc (void *Original, SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryRealloc - like Realloc(), but may return a nullptr if the allocation request cannot be satisfied.
Public Member Functions inherited from FUseSystemMallocForNew
void operator delete (void *Ptr)
Overloaded delete operator using the system allocator.
void operator delete[] (void *Ptr)
Overloaded array delete operator using the system allocator.
void * operator new (size_t Size)
Overloaded new operator using the system allocator.
void * operator new[] (size_t Size)
Overloaded array new operator using the system allocator.
Public Member Functions inherited from FExec
virtual ~FExec ()
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Exec handler.
Static Public Member Functions
static void * AllocateMetaDataMemory (SIZE_T Size)
static void FreeMetaDataMemory (void *Ptr, SIZE_T Size)
Data Fields
FPoolTable SmallPoolTables [51]
Static Public Attributes
static FMallocBinned2 * MallocBinned2
static uint8 MemSizeToPoolIndex [1+((32768-16) > > UE_MBC_MIN_SMALL_POOL_ALIGNMENT_SHIFT)]
static uint16 SmallBinSizes [51]
Static Public Attributes inherited from FMalloc
static TAtomic< uint64 > MaxSingleAlloc
Limits the maximum single allocation, to this many bytes, for debugging.
Protected Member Functions
FORCEINLINE void FreeInline (void *Ptr)
FORCEINLINE void * MallocInline (SIZE_T Size, uint32 Alignment)
FORCEINLINE void * MallocSelect (SIZE_T Size, uint32 Alignment)
void * MallocSelect (SIZE_T Size, uint32 Alignment, bool bUseSmallPool)
FORCEINLINE void * ReallocInline (void *Ptr, SIZE_T NewSize, uint32 Alignment)
Protected Member Functions inherited from TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >
void AllocateHashBuckets ()
FORCEINLINE uint32 BoundSizeToPoolIndex (SIZE_T Size, const uint8(&MemSizeToPoolIndex)[1+(MAX_SMALL_POOL_SIZE > > 4)]) const
virtual void ClearAndDisableTLSCachesOnCurrentThread () override
Clears the TLS caches on the current thread and disables any future caching.
bool GetAllocationSizeExternal (void *Ptr, SIZE_T &SizeOut)
int64 GetTotalAllocatedSmallPoolMemory () const
virtual void MarkTLSCachesAsUnusedOnCurrentThread () override
Mark TLS caches for current thread as unused.
virtual void MarkTLSCachesAsUsedOnCurrentThread () override
Mark TLS caches for the current thread as used.
bool PromoteToLargerBin (SIZE_T &Size, uint32 &Alignment, const FMallocBinned2 &Alloc) const
FORCEINLINE SIZE_T QuantizeSizeCommon (SIZE_T Count, uint32 Alignment, const FMallocBinned2 &Alloc) const
virtual void SetupTLSCachesOnCurrentThread () override
Set up TLS caches on the current thread.
void UpdateStatsCommon (const FMallocBinned2 &Alloc)
Protected Member Functions inherited from FMallocBinnedCommonBase
void GetAllocatorStatsInternal (FGenericMemoryStats &OutStats, int64 TotalAllocatedSmallPoolMemory)
Protected Member Functions inherited from FExec
virtual bool Exec_Dev (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in non-shipping targets.
virtual bool Exec_Editor (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in editor.
virtual bool Exec_Runtime (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is called on all targets where UE_ALLOW_EXEC_COMMANDS is true.
Static Protected Member Functions
static FORCEINLINE bool UseSmallAlloc (SIZE_T Size, uint32 Alignment)
Static Protected Member Functions inherited from TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >
static UE::FPlatformRecursiveMutex & GetFreeBlockListsRegistrationMutex ()
static TArray< FPerThreadFreeBlockLists * > & GetRegisteredFreeBlockLists ()
Static Protected Member Functions inherited from FMallocBinnedCommonBase
static CA_NO_RETURN void OutOfMemory (uint64 Size, uint32 Alignment=0)
Private Member Functions
FORCEINLINE bool IsOSAllocation (const void *Ptr) const
Static Private Member Functions
static FORCEINLINE FFreeBlock * GetPoolHeaderFromPointer (void *Ptr)
Private Attributes
TCachedOSPageAllocator<(64),(16 *1024 *1024) > CachedOSPageAllocator
Static Private Attributes
static constexpr EBlockCanary CurrentCanary = EBlockCanary::Value
Additional Inherited Members
Protected Attributes inherited from FMallocBinnedCommonBase
UE::FPlatformRecursiveMutex ExternalAllocMutex
std::atomic< uint64 > MemoryTrimEpoch { 0 }
uint64 NumPoolsPerPage
FPtrToPoolMapping PtrToPoolMapping
Static Protected Attributes inherited from FMallocBinnedCommonBase
static std::atomic< int64 > AllocatedLargePoolMemory
static std::atomic< int64 > AllocatedLargePoolMemoryWAlignment
static std::atomic< int64 > AllocatedOSSmallPoolMemory
static std::atomic< int64 > AllocatedSmallPoolMemory
static uint32 BinnedTlsSlot
static std::atomic< int64 > ConsolidatedMemory
static int64 HashMemory
static uint32 OsAllocationGranularity
static int64 PoolInfoMemory
static std::atomic< int64 > TLSMemory
Detailed Description
Definition at line 70 of file MallocBinned2.h.
Constructor & Destructor Documentation
FMallocBinned2()
FMallocBinned2::FMallocBinned2 ()
Referenced by FMallocBinned2::FPoolList::PushNewPoolToFront().
~FMallocBinned2()
virtual FMallocBinned2::~FMallocBinned2 () virtual
Member Function Documentation
AllocateMetaDataMemory()
void * FMallocBinned2::AllocateMetaDataMemory (SIZE_T Size) static
References TSequenceHistory< HistorySize >::Size.
CanaryFail()
void FMallocBinned2::CanaryFail (const FFreeBlock * Block) const
Referenced by CanaryTest().
CanaryTest()
FORCEINLINE void FMallocBinned2::CanaryTest (const FFreeBlock * Block) const inline
Definition at line 509 of file MallocBinned2.h.
References CanaryFail(), CurrentCanary, and FORCEINLINE.
Referenced by GetSmallAllocationSize().
DumpAllocatorStats()
virtual void FMallocBinned2::DumpAllocatorStats (class FOutputDevice & Ar) override virtual
Dumps current allocator stats to the log.
Reimplemented from FMalloc.
References Ar.
FlushCurrentThreadCacheInternal()
void FMallocBinned2::FlushCurrentThreadCacheInternal (bool bNewEpochOnly = false)
Free()
UE_AUTORTFM_NOAUTORTFM virtual FORCEINLINE void FMallocBinned2::Free (void * Original) inline override virtual
Free.
Implements FMalloc.
Definition at line 412 of file MallocBinned2.h.
References check, ensure, FORCEINLINE, FreeInline(), GetAllocationSize(), TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::GetTotalAllocatedSmallPoolMemory(), IsOSAllocation(), and UE_DEBUG_BREAK.
Referenced by GetSmallAllocationSize(), and ReallocInline().
FreeBundles()
void FMallocBinned2::FreeBundles (FBundleNode * Bundles, uint32 PoolIndex)
FreeExternal()
void FMallocBinned2::FreeExternal (void * Ptr)
Referenced by FreeInline().
FreeInline()
FORCEINLINE void FMallocBinned2::FreeInline (void * Ptr) inline protected
Definition at line 439 of file MallocBinned2.h.
References FMallocBinned2::FFreeBlock::BinSize, FMallocBinned2::FFreeBlock::CanaryAndForkState, CurrentCanary, FORCEINLINE, FreeExternal(), GetPoolHeaderFromPointer(), GMallocBinnedPerThreadCaches, IsOSAllocation(), FMallocBinned2::FFreeBlock::PoolIndex, and UE_MBC_UPDATE_STATS.
Referenced by Free().
FreeMetaDataMemory()
void FMallocBinned2::FreeMetaDataMemory (void * Ptr, SIZE_T Size) static
References TSequenceHistory< HistorySize >::Size.
GetAllocationSize()
virtual FORCEINLINE bool FMallocBinned2::GetAllocationSize (void * Original, SIZE_T & SizeOut) inline override virtual
If possible determine the size of the memory allocated at the given address.
Parameters
Original - Pointer to memory we are checking the size of
SizeOut - If possible, this value is set to the size of the passed in pointer
Returns
true if succeeded
Reimplemented from FMalloc.
Definition at line 472 of file MallocBinned2.h.
References FORCEINLINE, TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::GetAllocationSizeExternal(), and GetSmallAllocationSize().
Referenced by Free(), Malloc(), and Realloc().
GetDescriptiveName()
virtual const TCHAR * FMallocBinned2::GetDescriptiveName () override virtual
Gets descriptive name for logging purposes.
Returns
pointer to human-readable malloc name
Reimplemented from FMalloc.
GetImmediatelyFreeableCachedMemorySize()
virtual uint64 FMallocBinned2::GetImmediatelyFreeableCachedMemorySize () const inline override virtual
Returns the amount of free memory cached by the allocator that can be returned to the system in case of a memory shortage.
Reimplemented from FMalloc.
Definition at line 493 of file MallocBinned2.h.
References CachedOSPageAllocator.
GetPoolHeaderFromPointer()
FORCEINLINE FFreeBlock * FMallocBinned2::GetPoolHeaderFromPointer (void * Ptr) inline static private
Definition at line 234 of file MallocBinned2.h.
References AlignDown(), FORCEINLINE, and UE_MB2_LARGE_ALLOC.
Referenced by FreeInline(), GetSmallAllocationSize(), and ReallocInline().
GetSmallAllocationSize()
FORCEINLINE bool FMallocBinned2::GetSmallAllocationSize (void * Ptr, SIZE_T & SizeOut) const inline
Definition at line 460 of file MallocBinned2.h.
References CanaryTest(), FORCEINLINE, Free(), GetPoolHeaderFromPointer(), and IsOSAllocation().
Referenced by GetAllocationSize().
GetTotalFreeCachedMemorySize()
virtual uint64 FMallocBinned2::GetTotalFreeCachedMemorySize () const inline override virtual
Returns the amount of total free memory cached by the allocator.
This includes memory that can be returned to the system in case of a memory shortage, see GetImmediatelyFreeableCachedMemorySize() as well as any memory that can't be returned back to the kernel, but can be used to satisfy some of the allocation requirements.
Reimplemented from FMalloc.
Definition at line 497 of file MallocBinned2.h.
References CachedOSPageAllocator.
IsInternallyThreadSafe()
virtual bool FMallocBinned2::IsInternallyThreadSafe () const override virtual
Returns if the allocator is guaranteed to be thread-safe and therefore doesn't need a unnecessary thread-safety wrapper around it.
Reimplemented from FMalloc.
IsOSAllocation()
FORCEINLINE bool FMallocBinned2::IsOSAllocation (const void * Ptr) const inline private
Definition at line 225 of file MallocBinned2.h.
References CachedOSPageAllocator, FORCEINLINE, IsAligned(), and UE_MB2_LARGE_ALLOC.
Referenced by Free(), FreeInline(), GetSmallAllocationSize(), Malloc(), Realloc(), and ReallocInline().
Malloc()
UE_AUTORTFM_NOAUTORTFM virtual FORCEINLINE void * FMallocBinned2::Malloc (SIZE_T Count, uint32 Alignment) inline override virtual
Malloc.
Implements FMalloc.
Definition at line 247 of file MallocBinned2.h.
References check, ensure, FORCEINLINE, GetAllocationSize(), TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::GetTotalAllocatedSmallPoolMemory(), IsOSAllocation(), MallocInline(), TSequenceHistory< HistorySize >::Size, and UE_DEBUG_BREAK.
MallocExternalLarge()
void * FMallocBinned2::MallocExternalLarge (SIZE_T Size, uint32 Alignment)
References TSequenceHistory< HistorySize >::Size.
MallocExternalSmall()
void * FMallocBinned2::MallocExternalSmall (SIZE_T Size, uint32 Alignment)
References TSequenceHistory< HistorySize >::Size.
MallocInline()
FORCEINLINE void * FMallocBinned2::MallocInline (SIZE_T Size, uint32 Alignment) inline protected
Definition at line 275 of file MallocBinned2.h.
References TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::BoundSizeToPoolIndex(), FORCEINLINE, GMallocBinnedPerThreadCaches, MallocSelect(), MemSizeToPoolIndex, PoolIndexToBinSize(), TSequenceHistory< HistorySize >::Size, and UseSmallAlloc().
Referenced by Malloc().
MallocSelect() [1/2]
FORCEINLINE void * FMallocBinned2::MallocSelect (SIZE_T Size, uint32 Alignment) inline protected
Definition at line 306 of file MallocBinned2.h.
References FORCEINLINE, MallocSelect(), TSequenceHistory< HistorySize >::Size, and UseSmallAlloc().
MallocSelect() [2/2]
void * FMallocBinned2::MallocSelect (SIZE_T Size, uint32 Alignment, bool bUseSmallPool) protected
References TSequenceHistory< HistorySize >::Size.
Referenced by MallocInline(), and MallocSelect().
OnMallocInitialized()
virtual void FMallocBinned2::OnMallocInitialized () override virtual
Notifies the malloc implementation that initialization of all allocators in GMalloc is complete, so it's safe to initialize any extra features that require "regular" allocations.
Reimplemented from FMalloc.
OnPostFork()
virtual void FMallocBinned2::OnPostFork () override virtual
Notifies the malloc implementation that the process has forked so we can try and avoid dirtying pre-fork pages.
Reimplemented from FMalloc.
OnPreFork()
virtual void FMallocBinned2::OnPreFork () override virtual
Notifies the malloc implementation that the process is about to fork.
May be used to trim caches etc.
Reimplemented from FMalloc.
PoolIndexToBinSize()
FORCEINLINE uint32 FMallocBinned2::PoolIndexToBinSize (uint32 PoolIndex) const inline
Definition at line 533 of file MallocBinned2.h.
References FORCEINLINE, and SmallBinSizes.
Referenced by MallocInline(), and ReallocInline().
QuantizeSize()
virtual FORCEINLINE SIZE_T FMallocBinned2::QuantizeSize (SIZE_T Count, uint32 Alignment) inline override virtual
For some allocators this will return the actual size that should be requested to eliminate internal fragmentation.
The return value will always be >= Count. This can be used to grow and shrink containers to optimal sizes. This call is always fast and threadsafe with no locking.
Reimplemented from FMalloc.
Definition at line 481 of file MallocBinned2.h.
References Count, FORCEINLINE, and TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::QuantizeSizeCommon().
Realloc()
UE_AUTORTFM_NOAUTORTFM virtual FORCEINLINE void * FMallocBinned2::Realloc (void * Original, SIZE_T Count, uint32 Alignment) inline override virtual
Realloc.
Implements FMalloc.
Definition at line 313 of file MallocBinned2.h.
References check, ensure, FORCEINLINE, GetAllocationSize(), TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::GetTotalAllocatedSmallPoolMemory(), IsOSAllocation(), ReallocInline(), and UE_DEBUG_BREAK.
ReallocExternal()
void * FMallocBinned2::ReallocExternal (void * Ptr, SIZE_T NewSize, uint32 Alignment)
Referenced by ReallocInline().
ReallocInline()
FORCEINLINE void * FMallocBinned2::ReallocInline (void * Ptr, SIZE_T NewSize, uint32 Alignment) inline protected
Definition at line 352 of file MallocBinned2.h.
References TMallocBinnedCommon< FMallocBinned2, 51,(32768-16) >::BoundSizeToPoolIndex(), checkSlow, CurrentCanary, FORCEINLINE, Free(), GetPoolHeaderFromPointer(), GMallocBinnedPerThreadCaches, IsOSAllocation(), FMemory::Memcpy(), MemSizeToPoolIndex, PoolIndexToBinSize(), ReallocExternal(), UE_MB2_MAX_SMALL_POOL_SIZE, UE_MBC_MIN_SMALL_POOL_ALIGNMENT, and UE_MBC_UPDATE_STATS.
Referenced by Realloc().
Trim()
virtual void FMallocBinned2::Trim (bool bTrimThreadCaches) override virtual
Releases as much memory as possible.
Must be called from the main thread.
Reimplemented from FMalloc.
UpdateStats()
virtual void FMallocBinned2::UpdateStats () override virtual
Called once per frame, gathers and sets all memory allocator statistics into the corresponding stats.
MUST BE THREAD SAFE.
Reimplemented from FMalloc.
UseSmallAlloc()
FORCEINLINE bool FMallocBinned2::UseSmallAlloc (SIZE_T Size, uint32 Alignment) inline static protected
Definition at line 300 of file MallocBinned2.h.
References FORCEINLINE, TSequenceHistory< HistorySize >::Size, UE_MB2_MAX_SMALL_POOL_SIZE, and UE_MBC_MIN_SMALL_POOL_ALIGNMENT.
Referenced by MallocInline(), and MallocSelect().
ValidateHeap()
virtual bool FMallocBinned2::ValidateHeap () override virtual
Validates the allocator's heap.
Reimplemented from FMalloc.
Field Documentation
CachedOSPageAllocator
TCachedOSPageAllocator< (64) , (16*1024*1024) > FMallocBinned2::CachedOSPageAllocator private
Definition at line 219 of file MallocBinned2.h.
Referenced by GetImmediatelyFreeableCachedMemorySize(), GetTotalFreeCachedMemorySize(), and IsOSAllocation().
CurrentCanary
EBlockCanary FMallocBinned2::CurrentCanary = EBlockCanary::Value static constexpr private
Definition at line 212 of file MallocBinned2.h.
Referenced by CanaryTest(), FreeInline(), and ReallocInline().
MallocBinned2
FMallocBinned2* FMallocBinned2::MallocBinned2 static
Definition at line 526 of file MallocBinned2.h.
MemSizeToPoolIndex
uint8 FMallocBinned2::MemSizeToPoolIndex[1+((32768-16) > > UE_MBC_MIN_SMALL_POOL_ALIGNMENT_SHIFT)] static
Definition at line 528 of file MallocBinned2.h.
Referenced by MallocInline(), and ReallocInline().
SmallBinSizes
uint16 FMallocBinned2::SmallBinSizes[51] static
Definition at line 525 of file MallocBinned2.h.
Referenced by PoolIndexToBinSize().
SmallPoolTables
FPoolTable FMallocBinned2::SmallPoolTables[51]
Definition at line 205 of file MallocBinned2.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/MallocBinned2.h