Unreal Engine 5.6 C++ API: FShaderUniformBufferParameter Class Reference
FShaderUniformBufferParameter Class Reference
#include "ShaderParameters.h"
Public Member Functions
FShaderUniformBufferParameter ()
RENDERCORE_API void Bind (const FShaderParameterMap &ParameterMap, const TCHAR *ParameterName, EShaderParameterFlags Flags=SPF_Optional)
uint32 GetBaseIndex () const
FORCEINLINE bool IsBound () const
bool IsInitialized () const
void Serialize (FArchive &Ar)
Static Public Member Functions
static RENDERCORE_API void ModifyCompilationEnvironment (const TCHAR *ParameterName, const FShaderParametersMetadata &Struct, EShaderPlatform Platform, FShaderCompilerEnvironment &OutEnvironment)
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderUniformBufferParameter, RENDERCORE_API, NonVirtual)
LAYOUT_FIELD (uint16, BaseIndex)
Friends
FArchive & operator<< (FArchive &Ar, FShaderUniformBufferParameter &P)
Detailed Description
Definition at line 112 of file ShaderParameters.h.
Constructor & Destructor Documentation
FShaderUniformBufferParameter()
FShaderUniformBufferParameter::FShaderUniformBufferParameter () inline
Definition at line 116 of file ShaderParameters.h.
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT(), and operator<<.
Member Function Documentation
Bind()
RENDERCORE_API void FShaderUniformBufferParameter::Bind (const FShaderParameterMap & ParameterMap, const TCHAR * ParameterName, EShaderParameterFlags Flags = SPF_Optional)
References Flags, and SPF_Optional.
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderUniformBufferParameter::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderUniformBufferParameter , RENDERCORE_API , NonVirtual) private
References FShaderUniformBufferParameter().
GetBaseIndex()
uint32 FShaderUniformBufferParameter::GetBaseIndex () const inline
Definition at line 143 of file ShaderParameters.h.
References ensure, and IsBound().
IsBound()
FORCEINLINE bool FShaderUniformBufferParameter::IsBound () const inline
Definition at line 132 of file ShaderParameters.h.
References FORCEINLINE.
Referenced by GetBaseIndex().
IsInitialized()
bool FShaderUniformBufferParameter::IsInitialized () const inline
Definition at line 139 of file ShaderParameters.h.
LAYOUT_FIELD()
FShaderUniformBufferParameter::LAYOUT_FIELD (uint16 , BaseIndex) private
ModifyCompilationEnvironment()
RENDERCORE_API void FShaderUniformBufferParameter::ModifyCompilationEnvironment (const TCHAR * ParameterName, const FShaderParametersMetadata & Struct, EShaderPlatform Platform, FShaderCompilerEnvironment & OutEnvironment) static
References Platform, and Struct.
Referenced by TShaderUniformBufferParameter< TBufferStruct >::ModifyCompilationEnvironment().
Serialize()
void FShaderUniformBufferParameter::Serialize (FArchive & Ar) inline
Definition at line 134 of file ShaderParameters.h.
References Ar.
Referenced by operator<<, and TShaderUniformBufferParameter< TBufferStruct >::operator<<.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FShaderUniformBufferParameter & P) friend
Definition at line 126 of file ShaderParameters.h.
References FShaderUniformBufferParameter(), Ar, and Serialize().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameters.h