Unreal Engine 5.6 C++ API: Metasound::FInputDataVertex Class Reference
Metasound::FInputDataVertex Class Reference
FInputDataVertex.
#include "MetasoundVertex.h"
Public Member Functions
FInputDataVertex ()=default
FInputDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType, const FLiteral &InLiteral)
template<typename LiteralValueType>
FInputDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType, const LiteralValueType &InLiteralValue)
Construct an FInputDataVertex with a default literal.
FInputDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType=EVertexAccessType::Reference)
Construct an FInputDataVertex.
FLiteral GetDefaultLiteral () const
Returns the default literal associated with this input.
void SetDefaultLiteral (const FLiteral &InLiteral)
Set the default literal for this vertex.
Public Member Functions inherited from Metasound::FDataVertex
FDataVertex ()=default
FDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType)
FDataVertex Constructor.
virtual ~FDataVertex ()=default
Private Attributes
FLiteral Literal
Friends
bool METASOUNDGRAPHCORE_API operator!= (const FInputDataVertex &InLHS, const FInputDataVertex &InRHS)
bool METASOUNDGRAPHCORE_API operator< (const FInputDataVertex &InLHS, const FInputDataVertex &InRHS)
bool METASOUNDGRAPHCORE_API operator== (const FInputDataVertex &InLHS, const FInputDataVertex &InRHS)
Additional Inherited Members
Data Fields inherited from Metasound::FDataVertex
EVertexAccessType AccessType
Access type of the vertex.
FName DataTypeName
Type name of data.
FVertexName VertexName
Name of vertex.
Detailed Description
FInputDataVertex.
Definition at line 135 of file MetasoundVertex.h.
Constructor & Destructor Documentation
FInputDataVertex() [1/4]
Metasound::FInputDataVertex::FInputDataVertex () default
Referenced by Metasound::TInputConstructorVertex< DataType >::TInputConstructorVertex(), Metasound::TInputDataVertex< DataType >::TInputDataVertex(), operator!=, operator<, and operator==.
FInputDataVertex() [2/4]
Metasound::FInputDataVertex::FInputDataVertex (const FVertexName & InVertexName, const FName & InDataTypeName, const FDataVertexMetadata & InMetadata, EVertexAccessType InAccessType = EVertexAccessType::Reference) inline
Construct an FInputDataVertex.
Definition at line 142 of file MetasoundVertex.h.
References Metasound::FDataVertex::FDataVertex(), Literal, and Metasound::Reference.
FInputDataVertex() [3/4]
template<typename LiteralValueType> Metasound::FInputDataVertex::FInputDataVertex (const FVertexName & InVertexName, const FName & InDataTypeName, const FDataVertexMetadata & InMetadata, EVertexAccessType InAccessType, const LiteralValueType & InLiteralValue) inline
Construct an FInputDataVertex with a default literal.
Definition at line 150 of file MetasoundVertex.h.
References Metasound::FDataVertex::FDataVertex(), and Literal.
FInputDataVertex() [4/4]
Metasound::FInputDataVertex::FInputDataVertex (const FVertexName & InVertexName, const FName & InDataTypeName, const FDataVertexMetadata & InMetadata, EVertexAccessType InAccessType, const FLiteral & InLiteral) inline
Definition at line 156 of file MetasoundVertex.h.
References Metasound::FDataVertex::FDataVertex(), and Literal.
Member Function Documentation
GetDefaultLiteral()
FLiteral Metasound::FInputDataVertex::GetDefaultLiteral () const inline
Returns the default literal associated with this input.
Definition at line 163 of file MetasoundVertex.h.
References Literal.
SetDefaultLiteral()
void Metasound::FInputDataVertex::SetDefaultLiteral (const FLiteral & InLiteral) inline
Set the default literal for this vertex.
Definition at line 169 of file MetasoundVertex.h.
References Literal.
Friends And Related Symbol Documentation
operator!=
bool METASOUNDGRAPHCORE_API operator!= (const FInputDataVertex & InLHS, const FInputDataVertex & InRHS) friend
References FInputDataVertex().
operator<
bool METASOUNDGRAPHCORE_API operator< (const FInputDataVertex & InLHS, const FInputDataVertex & InRHS) friend
References FInputDataVertex().
operator==
bool METASOUNDGRAPHCORE_API operator== (const FInputDataVertex & InLHS, const FInputDataVertex & InRHS) friend
References FInputDataVertex().
Field Documentation
Literal
FLiteral Metasound::FInputDataVertex::Literal private
Definition at line 180 of file MetasoundVertex.h.
Referenced by FInputDataVertex(), FInputDataVertex(), FInputDataVertex(), GetDefaultLiteral(), and SetDefaultLiteral().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertex.h