Unreal Engine 5.6 C++ API: TDiscardableKeyValueCache< KeyType, ValueType > Class Template Reference
TDiscardableKeyValueCache< KeyType, ValueType > Class Template Reference
#include "DiscardableKeyValueCache.h"
Data Structures
struct LockFlags
Public Types
typedef TMap< KeyType, ValueType > TypedMap
Public Member Functions
TDiscardableKeyValueCache ()
bool Add (const KeyType &Key, const ValueType &Value)
Add an entry to the current map.
bool Add (const KeyType &Key, const ValueType &Value, const uint32 LockFlags)
Add an entry to the current map.
uint32 ApplyLock (uint32 CurrentFlags, uint32 NewFlags)
TypedMap & Backfill ()
TypedMap & Current ()
int32 Discard ()
template<typename DeleteFunc>
int32 Discard (DeleteFunc Func)
template<typename DeleteFunc>
int32 Discard (uint32 InCurrentLockFlags, uint32 &OutNewLockFlags, DeleteFunc Func)
Discard all items in the backfill and swap the current & backfill pointers.
bool Find (const KeyType &Key, ValueType &OutType)
Returns true and sets OutType to the value with the associated key if it exists.
bool Find (const KeyType &Key, ValueType &OutType, uint32 InCurrentLockFlags, uint32 &OutLockFlags)
Externally-lock-aware Find function.
int32 Num ()
FRWLock & RWLock ()
void Unlock (uint32 Flags)
Protected Member Functions
bool InternalFindWhileLocked (const KeyType &Key, ValueType &OutType, uint32 InCurrentLockFlags, uint32 &OutFlags)
Checks for the entry in our current map, and if not found the backfill.
Protected Attributes
TypedMap * BackfillMap
TypedMap * CurrentMap
FRWLock LockObject
TypedMap Map1
TypedMap Map2
Detailed Description
template<class KeyType, class ValueType>
class TDiscardableKeyValueCache< KeyType, ValueType >
Definition at line 20 of file DiscardableKeyValueCache.h.
Member Typedef Documentation
TypedMap
template<class KeyType, class ValueType> typedef TMap<KeyType, ValueType> TDiscardableKeyValueCache< KeyType, ValueType >::TypedMap
Definition at line 35 of file DiscardableKeyValueCache.h.
Constructor & Destructor Documentation
TDiscardableKeyValueCache()
template<class KeyType, class ValueType> TDiscardableKeyValueCache< KeyType, ValueType >::TDiscardableKeyValueCache () inline nodiscard
Definition at line 37 of file DiscardableKeyValueCache.h.
References BackfillMap, CurrentMap, Map1, and Map2.
Member Function Documentation
Add() [1/2]
template<class KeyType, class ValueType> bool TDiscardableKeyValueCache< KeyType, ValueType >::Add (const KeyType & Key, const ValueType & Value) inline
Add an entry to the current map.
Can fail if another thread has inserted a matching object, in which case another call to Find() should succeed
Definition at line 101 of file DiscardableKeyValueCache.h.
References Add, ApplyLock(), Key, Success, Unlock(), Value, and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
Add() [2/2]
template<class KeyType, class ValueType> bool TDiscardableKeyValueCache< KeyType, ValueType >::Add (const KeyType & Key, const ValueType & Value, const uint32 LockFlags) inline
Add an entry to the current map.
Can fail if another thread has inserted a matching object, in which case another call to Find() should succeed
Definition at line 113 of file DiscardableKeyValueCache.h.
References checkf, CurrentMap, Key, Success, TEXT, Value, and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
ApplyLock()
template<class KeyType, class ValueType> uint32 TDiscardableKeyValueCache< KeyType, ValueType >::ApplyLock (uint32 CurrentFlags, uint32 NewFlags) inline
Definition at line 196 of file DiscardableKeyValueCache.h.
References LockObject, TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::ReadLock, Unlock(), and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
Referenced by Add(), Discard(), Discard(), Discard(), Find(), InternalFindWhileLocked(), and Num().
Backfill()
template<class KeyType, class ValueType> TypedMap & TDiscardableKeyValueCache< KeyType, ValueType >::Backfill () inline nodiscard
Definition at line 56 of file DiscardableKeyValueCache.h.
References BackfillMap.
Current()
template<class KeyType, class ValueType> TypedMap & TDiscardableKeyValueCache< KeyType, ValueType >::Current () inline nodiscard
Definition at line 50 of file DiscardableKeyValueCache.h.
References CurrentMap.
Discard() [1/3]
template<class KeyType, class ValueType> int32 TDiscardableKeyValueCache< KeyType, ValueType >::Discard () inline
Definition at line 136 of file DiscardableKeyValueCache.h.
References ApplyLock(), Discard(), Unlock(), and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
Referenced by Discard(), and Discard().
Discard() [2/3]
template<class KeyType, class ValueType> template<typename DeleteFunc> int32 TDiscardableKeyValueCache< KeyType, ValueType >::Discard (DeleteFunc Func) inline
Definition at line 148 of file DiscardableKeyValueCache.h.
References ApplyLock(), Discard(), Unlock(), and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
Discard() [3/3]
template<class KeyType, class ValueType> template<typename DeleteFunc> int32 TDiscardableKeyValueCache< KeyType, ValueType >::Discard (uint32 InCurrentLockFlags, uint32 & OutNewLockFlags, DeleteFunc Func) inline
Discard all items in the backfill and swap the current & backfill pointers.
Definition at line 163 of file DiscardableKeyValueCache.h.
References ApplyLock(), BackfillMap, CurrentMap, Map1, Map2, and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
Find() [1/2]
template<class KeyType, class ValueType> bool TDiscardableKeyValueCache< KeyType, ValueType >::Find (const KeyType & Key, ValueType & OutType) inline nodiscard
Returns true and sets OutType to the value with the associated key if it exists.
Definition at line 76 of file DiscardableKeyValueCache.h.
References ApplyLock(), Found, InternalFindWhileLocked(), Key, TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::ReadLock, and Unlock().
Find() [2/2]
template<class KeyType, class ValueType> bool TDiscardableKeyValueCache< KeyType, ValueType >::Find (const KeyType & Key, ValueType & OutType, uint32 InCurrentLockFlags, uint32 & OutLockFlags) inline nodiscard
Externally-lock-aware Find function.
InFlags represents the currently locked state of the object, OutFlags the state after the find operation has completed. Caller should be sure to unlock this object with OutFlags
Definition at line 92 of file DiscardableKeyValueCache.h.
References InternalFindWhileLocked(), and Key.
InternalFindWhileLocked()
template<class KeyType, class ValueType> bool TDiscardableKeyValueCache< KeyType, ValueType >::InternalFindWhileLocked (const KeyType & Key, ValueType & OutType, uint32 InCurrentLockFlags, uint32 & OutFlags) inline nodiscard protected
Checks for the entry in our current map, and if not found the backfill.
If the entry is in the backfill it is moved to the current map so it will not be discarded when DiscardUnusedEntries is called
Definition at line 253 of file DiscardableKeyValueCache.h.
References ApplyLock(), BackfillMap, checkf, CurrentMap, Found, Key, TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::ReadLock, TEXT, TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock, and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLockOnAddFail.
Referenced by Find(), and Find().
Num()
template<class KeyType, class ValueType> int32 TDiscardableKeyValueCache< KeyType, ValueType >::Num () inline nodiscard
Definition at line 62 of file DiscardableKeyValueCache.h.
References ApplyLock(), Count, Map1, Map2, TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::ReadLock, and Unlock().
RWLock()
template<class KeyType, class ValueType> FRWLock & TDiscardableKeyValueCache< KeyType, ValueType >::RWLock () inline nodiscard
Definition at line 44 of file DiscardableKeyValueCache.h.
References LockObject.
Unlock()
template<class KeyType, class ValueType> void TDiscardableKeyValueCache< KeyType, ValueType >::Unlock (uint32 Flags) inline
Definition at line 232 of file DiscardableKeyValueCache.h.
References Flags, LockObject, TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::ReadLock, and TDiscardableKeyValueCache< KeyType, ValueType >::LockFlags::WriteLock.
Referenced by Add(), ApplyLock(), Discard(), Discard(), Find(), and Num().
Field Documentation
BackfillMap
template<class KeyType, class ValueType> TypedMap* TDiscardableKeyValueCache< KeyType, ValueType >::BackfillMap protected
Definition at line 312 of file DiscardableKeyValueCache.h.
Referenced by TDiscardableKeyValueCache(), Backfill(), Discard(), and InternalFindWhileLocked().
CurrentMap
template<class KeyType, class ValueType> TypedMap* TDiscardableKeyValueCache< KeyType, ValueType >::CurrentMap protected
Definition at line 311 of file DiscardableKeyValueCache.h.
Referenced by TDiscardableKeyValueCache(), Add(), Current(), Discard(), and InternalFindWhileLocked().
LockObject
template<class KeyType, class ValueType> FRWLock TDiscardableKeyValueCache< KeyType, ValueType >::LockObject protected
Definition at line 310 of file DiscardableKeyValueCache.h.
Referenced by ApplyLock(), RWLock(), and Unlock().
Map1
template<class KeyType, class ValueType> TypedMap TDiscardableKeyValueCache< KeyType, ValueType >::Map1 protected
Definition at line 313 of file DiscardableKeyValueCache.h.
Referenced by TDiscardableKeyValueCache(), Discard(), and Num().
Map2
template<class KeyType, class ValueType> TypedMap TDiscardableKeyValueCache< KeyType, ValueType >::Map2 protected
Definition at line 314 of file DiscardableKeyValueCache.h.
Referenced by TDiscardableKeyValueCache(), Discard(), and Num().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/DiscardableKeyValueCache.h