Unreal Engine 5.6 C++ API: FDisplayClusterTickableGameObject Class Reference
FDisplayClusterTickableGameObject Class Reference
Tickable game object: has an OnTick() callback to start all subscribers.
#include "DisplayClusterTickableGameObject.h"
Public Member Functions
FDisplayClusterTickableGameObject ()=default
virtual ~FDisplayClusterTickableGameObject ()=default
DECLARE_EVENT_OneParam (FDisplayClusterTickableGameObject, FTickEvent, float)
Callback on tick.
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
virtual ETickableTickType GetTickableTickType () const override
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickableInEditor () const override
Used to determine whether the object should be ticked in the editor when there is no gameplay world.
FTickEvent & OnTick ()
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
Public Member Functions inherited from FTickableGameObject
FTickableGameObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableGameObject ()
Removes this instance from the static array of tickable objects.
virtual UWorld * GetTickableGameObjectWorld () const
Used to determine the specific world this object is associated with.
virtual bool IsTickableWhenPaused () const
Used to determine if an object should be ticked when the game is paused.
void SetTickableTickType (ETickableTickType NewTickType)
Call to modify the tickable type of this instance.
UE_NONCOPYABLE (FTickableGameObject)
Tickable objects cannot be copied safely due to the auto registration.
Public Member Functions inherited from FTickableObjectBase
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Private Attributes
FTickEvent TickEvent
Additional Inherited Members
Static Public Member Functions inherited from FTickableGameObject
static void TickObjects (UWorld *World, ELevelTick LevelTickType, bool bIsPaused, float DeltaSeconds)
Tick all FTickableGameObject instances that match the parameters.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Tickable game object: has an OnTick() callback to start all subscribers.
Definition at line 11 of file DisplayClusterTickableGameObject.h.
Constructor & Destructor Documentation
FDisplayClusterTickableGameObject()
FDisplayClusterTickableGameObject::FDisplayClusterTickableGameObject () default
Referenced by DECLARE_EVENT_OneParam(), and GetStatId().
~FDisplayClusterTickableGameObject()
virtual FDisplayClusterTickableGameObject::~FDisplayClusterTickableGameObject () virtual default
Member Function Documentation
DECLARE_EVENT_OneParam()
FDisplayClusterTickableGameObject::DECLARE_EVENT_OneParam (FDisplayClusterTickableGameObject , FTickEvent , float)
Callback on tick.
References FDisplayClusterTickableGameObject().
GetStatId()
virtual TStatId FDisplayClusterTickableGameObject::GetStatId () const inline override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
Definition at line 37 of file DisplayClusterTickableGameObject.h.
References FDisplayClusterTickableGameObject(), and RETURN_QUICK_DECLARE_CYCLE_STAT.
GetTickableTickType()
virtual ETickableTickType FDisplayClusterTickableGameObject::GetTickableTickType () const inline override virtual
Virtual that can be overloaded by the inheriting class and is called before first tick.
It is used to determine whether an object can possibly tick, and if not, it will not get added to the tickable objects array. If the tickable tick type is Conditional then the virtual IsTickable will be called to determine whether to tick the object on each given frame.
Returns
an enum defining the rules for ticking this object.
Reimplemented from FTickableObjectBase.
Definition at line 32 of file DisplayClusterTickableGameObject.h.
References Always.
IsTickableInEditor()
virtual bool FDisplayClusterTickableGameObject::IsTickableInEditor () const inline override virtual
Used to determine whether the object should be ticked in the editor when there is no gameplay world.
Objects will still be ticked in Play in Editor if they are associated with a PIE world.
Returns
true if this tickable object should always be ticked in the editor, even if there is no gameplay world
Reimplemented from FTickableGameObject.
Definition at line 25 of file DisplayClusterTickableGameObject.h.
OnTick()
FTickEvent & FDisplayClusterTickableGameObject::OnTick () inline
Definition at line 20 of file DisplayClusterTickableGameObject.h.
References TickEvent.
Tick()
virtual void FDisplayClusterTickableGameObject::Tick (float DeltaTime) override virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
References DeltaTime.
Field Documentation
TickEvent
FTickEvent FDisplayClusterTickableGameObject::TickEvent private
Definition at line 43 of file DisplayClusterTickableGameObject.h.
Referenced by OnTick().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Misc/DisplayClusterTickableGameObject.h