Unreal Engine 5.6 C++ API: TScale< T > Class Template Reference
TScale< T > Class Template Reference
Represents a 3D non-uniform scale (to disambiguate from an UE::Math::TVector<T>, which is used for translation).
#include "TransformCalculus3D.h"
Public Types
using Vector3Type = UE::Math::TVector<T>
Public Member Functions
TScale ()
Ctor.
template<typename VType>
TScale (const UE::Math::TVector< VType > &InScale)
Ctor.
TScale (T InScale)
Ctor.
TScale Concatenate (const TScale &RHS) const
Concatenate two scales.
const Vector3Type & GetVector () const
Access to the underlying UE::Math::TVector<T> that stores the scale.
TScale Inverse () const
Invert the scale.
Private Attributes
Vector3Type Scale
Underlying storage of the 3D scale.
Detailed Description
template<typename T>
class TScale< T >
Represents a 3D non-uniform scale (to disambiguate from an UE::Math::TVector<T>, which is used for translation).
Serves as a good base example of how to write a class that supports the basic transform calculus operations.
Definition at line 38 of file TransformCalculus3D.h.
Member Typedef Documentation
Vector3Type
template<typename T> using TScale< T >::Vector3Type = UE::Math::TVector<T>
Definition at line 43 of file TransformCalculus3D.h.
Constructor & Destructor Documentation
TScale() [1/3]
template<typename T> TScale< T >::TScale () inline nodiscard
Ctor.
initialize to an identity scale, 1.0.
Definition at line 46 of file TransformCalculus3D.h.
Referenced by TScale< float >::Concatenate(), and TScale< float >::Inverse().
TScale() [2/3]
template<typename T> TScale< T >::TScale (T InScale) inline explicit nodiscard
Ctor.
initialize from a uniform scale.
Definition at line 48 of file TransformCalculus3D.h.
TScale() [3/3]
template<typename T> template<typename VType> TScale< T >::TScale (const UE::Math::TVector< VType > & InScale) inline explicit nodiscard
Ctor.
initialize from an UE::Math::TVector<T> defining the 3D scale.
Definition at line 51 of file TransformCalculus3D.h.
Member Function Documentation
Concatenate()
template<typename T> TScale TScale< T >::Concatenate (const TScale< T > & RHS) const inline nodiscard
Concatenate two scales.
Definition at line 58 of file TransformCalculus3D.h.
GetVector()
template<typename T> const Vector3Type & TScale< T >::GetVector () const inline nodiscard
Access to the underlying UE::Math::TVector<T> that stores the scale.
Definition at line 53 of file TransformCalculus3D.h.
Referenced by TScale< float >::Concatenate().
Inverse()
template<typename T> TScale TScale< T >::Inverse () const inline nodiscard
Invert the scale.
Definition at line 63 of file TransformCalculus3D.h.
Field Documentation
Scale
template<typename T> Vector3Type TScale< T >::Scale private
Underlying storage of the 3D scale.
Definition at line 69 of file TransformCalculus3D.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/TransformCalculus3D.h