Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator Class Reference
UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator Class Reference
#include "DynamicVector.h"
Public Member Functions
bool operator!= (const FIterator &Itr2) const
Type & operator* ()
const Type & operator* () const
FIterator & operator++ ()
FIterator operator++ (int)
bool operator== (const FIterator &Itr2) const
Private Member Functions
FIterator (TDynamicVector *DVectorIn, unsigned int IdxIn)
Private Attributes
TDynamicVector * DVector {}
unsigned int Idx {0}
Friends
class TDynamicVector
Detailed Description
template<typename Type, int32 BlockSize = 512>
class UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator
Definition at line 219 of file DynamicVector.h.
Constructor & Destructor Documentation
FIterator()
template<typename Type, int32 BlockSize = 512> UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::FIterator (TDynamicVector * DVectorIn, unsigned int IdxIn) inline private
Definition at line 252 of file DynamicVector.h.
References DVector, Idx, and TDynamicVector.
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename Type, int32 BlockSize = 512> bool UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::operator!= (const FIterator & Itr2) const inline
Definition at line 245 of file DynamicVector.h.
References FIterator(), DVector, and Idx.
operator*() [1/2]
template<typename Type, int32 BlockSize = 512> Type & UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::operator* () inline
Definition at line 226 of file DynamicVector.h.
References DVector, and Idx.
operator*() [2/2]
template<typename Type, int32 BlockSize = 512> const Type & UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::operator* () const inline
Definition at line 222 of file DynamicVector.h.
References DVector, and Idx.
operator++() [1/2]
template<typename Type, int32 BlockSize = 512> FIterator & UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::operator++ () inline
Definition at line 230 of file DynamicVector.h.
References FIterator(), and Idx.
operator++() [2/2]
template<typename Type, int32 BlockSize = 512> FIterator UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::operator++ (int) inline
Definition at line 235 of file DynamicVector.h.
References FIterator(), Copy, and Idx.
operator==()
template<typename Type, int32 BlockSize = 512> bool UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::operator== (const FIterator & Itr2) const inline
Definition at line 241 of file DynamicVector.h.
References FIterator(), DVector, and Idx.
Friends And Related Symbol Documentation
TDynamicVector
template<typename Type, int32 BlockSize = 512> friend class TDynamicVector friend
Definition at line 251 of file DynamicVector.h.
References TDynamicVector.
Referenced by FIterator(), and TDynamicVector.
Field Documentation
DVector
template<typename Type, int32 BlockSize = 512> TDynamicVector* UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::DVector {} private
Definition at line 254 of file DynamicVector.h.
Referenced by FIterator(), operator!=(), operator*(), operator*(), and operator==().
Idx
template<typename Type, int32 BlockSize = 512> unsigned int UE::Geometry::TDynamicVector< Type, BlockSize >::FIterator::Idx {0} private
Definition at line 255 of file DynamicVector.h.
Referenced by FIterator(), operator!=(), operator*(), operator*(), operator++(), operator++(), and operator==().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/DynamicVector.h