Unreal Engine 5.6 C++ API: FLandscapeSharedBuffers Class Reference
FLandscapeSharedBuffers Class Reference
#include "LandscapeRender.h"
Data Structures
struct FLandscapeIndexRanges
Public Member Functions
LANDSCAPE_API FLandscapeSharedBuffers (FRHICommandListBase &RHICmdList, int32 SharedBuffersKey, int32 SubsectionSizeQuads, int32 NumSubsections, int32 NumRayTracingSections, ERHIFeatureLevel::Type FeatureLevel, const FName &OwnerName=NAME_None)
virtual LANDSCAPE_API ~FLandscapeSharedBuffers ()
template<typename INDEX_TYPE>
void CreateGrassIndexBuffer (FRHICommandListBase &RHICmdList, const FName &InOwnerName)
template<typename INDEX_TYPE>
void CreateIndexBuffers (FRHICommandListBase &RHICmdList, const FName &OwnerName)
UE_DEPRECATED (5.6, "This constructor has been deprecated. Please use constructor which also provides the number of raytracing sections.") LANDSCAPE_API FLandscapeSharedBuffers(FRHICommandListBase &RHICmdList
Public Member Functions inherited from FRefCountedObject
FRefCountedObject ()
FRefCountedObject (const FRefCountedObject &Rhs)=delete
virtual ~FRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountedObject & operator= (const FRefCountedObject &Rhs)=delete
uint32 Release () const
Data Fields
bool bUse32BitIndices
int32 int32 int32 ERHIFeatureLevel::Type FeatureLevel
FLandscapeVertexFactory * FixedGridVertexFactory
FIndexBuffer * GrassIndexBuffer
TArray< int32, TInlineAllocator< 8 > > GrassIndexMipOffsets
FIndexBuffer ** IndexBuffers
FLandscapeIndexRanges * IndexRanges
TArray< TUniformBuffer< FLandscapeFixedGridUniformShaderParameters > > LandscapeFixedGridUniformShaderParameters
int32 NumIndexBuffers
int32 NumRayTracingSections
int32 NumSubsections
int32 int32 int32 NumSubsections
int32 NumVertices
int32 int32 int32 ERHIFeatureLevel::Type const FName & OwnerName = NAME_None)
int32 SharedBuffersKey
int32 int32 SubsectionSizeQuads
int32 SubsectionSizeVerts
FVertexBuffer * TileDataBuffer
FRenderResource * TileMesh
FLandscapeVertexFactory * TileVertexFactory
FLandscapeVertexBuffer * VertexBuffer
FLandscapeVertexFactory * VertexFactory
Detailed Description
Definition at line 364 of file LandscapeRender.h.
Constructor & Destructor Documentation
FLandscapeSharedBuffers()
LANDSCAPE_API FLandscapeSharedBuffers::FLandscapeSharedBuffers (FRHICommandListBase & RHICmdList, int32 SharedBuffersKey, int32 SubsectionSizeQuads, int32 NumSubsections, int32 NumRayTracingSections, ERHIFeatureLevel::Type FeatureLevel, const FName & OwnerName = NAME_None)
References FLandscapeSharedBuffers(), FeatureLevel, NumRayTracingSections, NumSubsections, OwnerName, SharedBuffersKey, and SubsectionSizeQuads.
Referenced by FLandscapeSharedBuffers(), and ~FLandscapeSharedBuffers().
~FLandscapeSharedBuffers()
virtual LANDSCAPE_API FLandscapeSharedBuffers::~FLandscapeSharedBuffers () virtual
References FLandscapeSharedBuffers().
Member Function Documentation
CreateGrassIndexBuffer()
template<typename INDEX_TYPE> void FLandscapeSharedBuffers::CreateGrassIndexBuffer (FRHICommandListBase & RHICmdList, const FName & InOwnerName)
References CreateGrassIndexBuffer().
Referenced by CreateGrassIndexBuffer().
CreateIndexBuffers()
template<typename INDEX_TYPE> void FLandscapeSharedBuffers::CreateIndexBuffers (FRHICommandListBase & RHICmdList, const FName & OwnerName)
References CreateIndexBuffers(), and OwnerName.
Referenced by CreateIndexBuffers().
UE_DEPRECATED()
FLandscapeSharedBuffers::UE_DEPRECATED (5. 6, "This constructor has been deprecated. Please use constructor which also provides the number of raytracing sections.") &
Field Documentation
bUse32BitIndices
bool FLandscapeSharedBuffers::bUse32BitIndices
Definition at line 398 of file LandscapeRender.h.
FeatureLevel
int32 int32 int32 ERHIFeatureLevel::Type FLandscapeSharedBuffers::FeatureLevel
Definition at line 407 of file LandscapeRender.h.
Referenced by FLandscapeSharedBuffers().
FixedGridVertexFactory
FLandscapeVertexFactory* FLandscapeSharedBuffers::FixedGridVertexFactory
Definition at line 383 of file LandscapeRender.h.
GrassIndexBuffer
FIndexBuffer* FLandscapeSharedBuffers::GrassIndexBuffer
Definition at line 399 of file LandscapeRender.h.
GrassIndexMipOffsets
TArray<int32, TInlineAllocator<8> > FLandscapeSharedBuffers::GrassIndexMipOffsets
Definition at line 400 of file LandscapeRender.h.
IndexBuffers
FIndexBuffer** FLandscapeSharedBuffers::IndexBuffers
Definition at line 393 of file LandscapeRender.h.
IndexRanges
FLandscapeIndexRanges* FLandscapeSharedBuffers::IndexRanges
Definition at line 396 of file LandscapeRender.h.
LandscapeFixedGridUniformShaderParameters
TArray<TUniformBuffer<FLandscapeFixedGridUniformShaderParameters> > FLandscapeSharedBuffers::LandscapeFixedGridUniformShaderParameters
Definition at line 386 of file LandscapeRender.h.
NumIndexBuffers
int32 FLandscapeSharedBuffers::NumIndexBuffers
Definition at line 377 of file LandscapeRender.h.
NumRayTracingSections
int32 FLandscapeSharedBuffers::NumRayTracingSections
Definition at line 380 of file LandscapeRender.h.
Referenced by FLandscapeSharedBuffers().
NumSubsections [1/2]
int32 FLandscapeSharedBuffers::NumSubsections
Definition at line 379 of file LandscapeRender.h.
Referenced by FLandscapeSharedBuffers().
NumSubsections [2/2]
int32 int32 int32 FLandscapeSharedBuffers::NumSubsections
Definition at line 407 of file LandscapeRender.h.
NumVertices
int32 FLandscapeSharedBuffers::NumVertices
Definition at line 375 of file LandscapeRender.h.
OwnerName
int32 int32 int32 ERHIFeatureLevel::Type const FName& FLandscapeSharedBuffers::OwnerName = NAME_None)
Definition at line 407 of file LandscapeRender.h.
Referenced by FLandscapeSharedBuffers(), and CreateIndexBuffers().
SharedBuffersKey
int32 FLandscapeSharedBuffers::SharedBuffersKey
Definition at line 376 of file LandscapeRender.h.
Referenced by FLandscapeSharedBuffers().
SubsectionSizeQuads
int32 int32 FLandscapeSharedBuffers::SubsectionSizeQuads
Definition at line 407 of file LandscapeRender.h.
Referenced by FLandscapeSharedBuffers().
SubsectionSizeVerts
int32 FLandscapeSharedBuffers::SubsectionSizeVerts
Definition at line 378 of file LandscapeRender.h.
TileDataBuffer
FVertexBuffer* FLandscapeSharedBuffers::TileDataBuffer
Definition at line 390 of file LandscapeRender.h.
TileMesh
FRenderResource* FLandscapeSharedBuffers::TileMesh
Definition at line 388 of file LandscapeRender.h.
TileVertexFactory
FLandscapeVertexFactory* FLandscapeSharedBuffers::TileVertexFactory
Definition at line 389 of file LandscapeRender.h.
VertexBuffer
FLandscapeVertexBuffer* FLandscapeSharedBuffers::VertexBuffer
Definition at line 384 of file LandscapeRender.h.
VertexFactory
FLandscapeVertexFactory* FLandscapeSharedBuffers::VertexFactory
Definition at line 382 of file LandscapeRender.h.
The documentation for this class was generated from the following file:
Runtime/Landscape/Public/LandscapeRender.h