Unreal Engine 5.6 C++ API: FUnixPlatformMemory::FPlatformVirtualMemoryBlock Class Reference
FUnixPlatformMemory::FPlatformVirtualMemoryBlock Class Reference
#include "UnixPlatformMemory.h"
Public Member Functions
FPlatformVirtualMemoryBlock ()
FPlatformVirtualMemoryBlock (const FPlatformVirtualMemoryBlock &Other)=default
FPlatformVirtualMemoryBlock (void *InPtr, uint32 InVMSizeDivVirtualSizeAlignment)
FORCEINLINE void Commit ()
void Commit (size_t InOffset, size_t InSize)
FORCEINLINE void CommitByPtr (void *InPtr, size_t InSize)
FORCEINLINE void Decommit ()
void Decommit (size_t InOffset, size_t InSize)
FORCEINLINE void DecommitByPtr (void *InPtr, size_t InSize)
void FreeVirtual ()
FORCEINLINE size_t GetActualSize () const
FPlatformVirtualMemoryBlock & operator= (const FPlatformVirtualMemoryBlock &Other)=default
Public Member Functions inherited from FGenericPlatformMemory::FBasicVirtualMemoryBlock
FBasicVirtualMemoryBlock ()
FBasicVirtualMemoryBlock (const FBasicVirtualMemoryBlock &Other)=default
FBasicVirtualMemoryBlock (void *InPtr, uint32 InVMSizeDivVirtualSizeAlignment)
FORCEINLINE uint32 GetActualSizeInPages () const
FORCEINLINE void * GetVirtualPointer () const
FBasicVirtualMemoryBlock & operator= (const FBasicVirtualMemoryBlock &Other)=default
Static Public Member Functions
static FPlatformVirtualMemoryBlock AllocateVirtual (size_t Size, size_t InAlignment=FPlatformVirtualMemoryBlock::GetVirtualSizeAlignment())
static size_t GetCommitAlignment ()
static size_t GetVirtualSizeAlignment ()
Additional Inherited Members
Protected Attributes inherited from FGenericPlatformMemory::FBasicVirtualMemoryBlock
void * Ptr
uint32 VMSizeDivVirtualSizeAlignment
Detailed Description
Definition at line 88 of file UnixPlatformMemory.h.
Constructor & Destructor Documentation
FPlatformVirtualMemoryBlock() [1/3]
FUnixPlatformMemory::FPlatformVirtualMemoryBlock::FPlatformVirtualMemoryBlock () inline
Definition at line 92 of file UnixPlatformMemory.h.
Referenced by FPlatformVirtualMemoryBlock(), AllocateVirtual(), and operator=().
FPlatformVirtualMemoryBlock() [2/3]
FUnixPlatformMemory::FPlatformVirtualMemoryBlock::FPlatformVirtualMemoryBlock (void * InPtr, uint32 InVMSizeDivVirtualSizeAlignment) inline
Definition at line 96 of file UnixPlatformMemory.h.
References FGenericPlatformMemory::FBasicVirtualMemoryBlock::FBasicVirtualMemoryBlock().
FPlatformVirtualMemoryBlock() [3/3]
FUnixPlatformMemory::FPlatformVirtualMemoryBlock::FPlatformVirtualMemoryBlock (const FPlatformVirtualMemoryBlock & Other) default
References FPlatformVirtualMemoryBlock(), and Other.
Member Function Documentation
AllocateVirtual()
FPlatformVirtualMemoryBlock FUnixPlatformMemory::FPlatformVirtualMemoryBlock::AllocateVirtual (size_t Size, size_t InAlignment = FPlatformVirtualMemoryBlock::GetVirtualSizeAlignment()) static
References FPlatformVirtualMemoryBlock(), GetVirtualSizeAlignment(), and TSequenceHistory< HistorySize >::Size.
Commit() [1/2]
FORCEINLINE void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::Commit () inline
Definition at line 117 of file UnixPlatformMemory.h.
References Commit(), FORCEINLINE, and GetActualSize().
Referenced by Commit(), and CommitByPtr().
Commit() [2/2]
void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::Commit (size_t InOffset, size_t InSize)
CommitByPtr()
FORCEINLINE void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::CommitByPtr (void * InPtr, size_t InSize) inline
Definition at line 107 of file UnixPlatformMemory.h.
References Commit(), FORCEINLINE, and FGenericPlatformMemory::FBasicVirtualMemoryBlock::Ptr.
Decommit() [1/2]
FORCEINLINE void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::Decommit () inline
Definition at line 122 of file UnixPlatformMemory.h.
References Decommit(), FORCEINLINE, and GetActualSize().
Referenced by Decommit(), and DecommitByPtr().
Decommit() [2/2]
void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::Decommit (size_t InOffset, size_t InSize)
DecommitByPtr()
FORCEINLINE void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::DecommitByPtr (void * InPtr, size_t InSize) inline
Definition at line 112 of file UnixPlatformMemory.h.
References Decommit(), FORCEINLINE, and FGenericPlatformMemory::FBasicVirtualMemoryBlock::Ptr.
FreeVirtual()
void FUnixPlatformMemory::FPlatformVirtualMemoryBlock::FreeVirtual ()
GetActualSize()
FORCEINLINE size_t FUnixPlatformMemory::FPlatformVirtualMemoryBlock::GetActualSize () const inline
Definition at line 127 of file UnixPlatformMemory.h.
References FORCEINLINE, GetVirtualSizeAlignment(), and FGenericPlatformMemory::FBasicVirtualMemoryBlock::VMSizeDivVirtualSizeAlignment.
Referenced by Commit(), and Decommit().
GetCommitAlignment()
size_t FUnixPlatformMemory::FPlatformVirtualMemoryBlock::GetCommitAlignment () static
GetVirtualSizeAlignment()
size_t FUnixPlatformMemory::FPlatformVirtualMemoryBlock::GetVirtualSizeAlignment () static
Referenced by AllocateVirtual(), and GetActualSize().
operator=()
FPlatformVirtualMemoryBlock & FUnixPlatformMemory::FPlatformVirtualMemoryBlock::operator= (const FPlatformVirtualMemoryBlock & Other) default
References FPlatformVirtualMemoryBlock(), and Other.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Unix/UnixPlatformMemory.h