Unreal Engine 5.6 C++ API: UE::UnifiedError::FErrorRegistry Class Reference
UE::UnifiedError::FErrorRegistry Class Reference
#include "UnifiedError.h"
Public Member Functions
int32 RegisterErrorCode (const FStringView &ErrorName, int32 ModuleId, int32 ErrorCode)
uint32 RegisterModule (const FStringView &ModuleName)
Static Public Member Functions
static FErrorRegistry & Get ()
Private Member Functions
FErrorRegistry ()
Private Attributes
TMap< TPair< int32, int32 >, FString > ErrorCodeNameMap
TMap< int32, FString > ModuleNameMap
Detailed Description
Definition at line 492 of file UnifiedError.h.
Constructor & Destructor Documentation
FErrorRegistry()
UE::UnifiedError::FErrorRegistry::FErrorRegistry () inline private
Definition at line 504 of file UnifiedError.h.
Referenced by Get().
Member Function Documentation
Get()
FErrorRegistry & UE::UnifiedError::FErrorRegistry::Get () inline static
Definition at line 495 of file UnifiedError.h.
References FErrorRegistry().
RegisterErrorCode()
int32 UE::UnifiedError::FErrorRegistry::RegisterErrorCode (const FStringView & ErrorName, int32 ModuleId, int32 ErrorCode) inline
Definition at line 516 of file UnifiedError.h.
References checkf, ErrorCodeNameMap, and TEXT.
RegisterModule()
uint32 UE::UnifiedError::FErrorRegistry::RegisterModule (const FStringView & ModuleName) inline
Definition at line 507 of file UnifiedError.h.
References checkf, TStringView< CharType >::GetData(), GetTypeHash(), ModuleNameMap, and TEXT.
Field Documentation
ErrorCodeNameMap
TMap<TPair<int32, int32>, FString> UE::UnifiedError::FErrorRegistry::ErrorCodeNameMap private
Definition at line 526 of file UnifiedError.h.
Referenced by RegisterErrorCode().
ModuleNameMap
TMap<int32, FString> UE::UnifiedError::FErrorRegistry::ModuleNameMap private
Definition at line 525 of file UnifiedError.h.
Referenced by RegisterModule().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/UnifiedError/UnifiedError.h