Unreal Engine 5.6 C++ API: FTickableEditorObject Class Reference
FTickableEditorObject Class Reference
This class provides common registration for gamethread editor only tickable objects.
#include "TickableEditorObject.h"
Public Member Functions
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual TStatId GetStatId () const =0
Return the stat id used to track the performance of this object.
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
virtual void Tick (float DeltaTime)=0
Pure virtual that must be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Public Member Functions
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Private Member Functions
static UNREALED_API FTickableStatics & GetStatics ()
Returns the tracking struct for this type.
Static Private Attributes
static UNREALED_API FTickableObjectBase * ObjectBeingTicked
Set if we are in the Tick function for an editor tickable object.
Additional Inherited Members
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
This class provides common registration for gamethread editor only tickable objects.
It is an abstract base class requiring you to implement the GetStatId, IsTickable, and Tick methods. If you need a class that can tick in both the Editor and at Runtime then use FTickableGameObject instead, overriding the IsTickableInEditor() function instead.
Definition at line 20 of file TickableEditorObject.h.
Constructor & Destructor Documentation
FTickableEditorObject()
FTickableEditorObject::FTickableEditorObject () inline
Registers this instance with the static array of tickable objects.
Definition at line 39 of file TickableEditorObject.h.
References ensure, GetStatics(), IsInAsyncLoadingThread, IsInGameThread(), and FTickableObjectBase::FTickableStatics::QueueTickableObjectForAdd().
Referenced by UE_NONCOPYABLE().
~FTickableEditorObject()
virtual FTickableEditorObject::~FTickableEditorObject () inline virtual
Removes this instance from the static array of tickable objects.
Definition at line 48 of file TickableEditorObject.h.
References ensure, ensureMsgf, GetStatics(), IsInAsyncLoadingThread, IsInGameThread(), Never, ObjectBeingTicked, FTickableObjectBase::FTickableStatics::SetTickTypeForTickableObject(), and TEXT.
Member Function Documentation
GetStatics()
UNREALED_API FTickableStatics & FTickableEditorObject::GetStatics () static private
Returns the tracking struct for this type.
Referenced by FTickableEditorObject(), ~FTickableEditorObject(), and TickObjects().
TickObjects()
void FTickableEditorObject::TickObjects (const float DeltaSeconds) inline static
Calls Tick on every tickable editor object with tick enabled.
Definition at line 26 of file TickableEditorObject.h.
References GetStatics(), ObjectBeingTicked, FTickableObjectBase::SimpleTickObjects(), and FTickableObjectBase::Tick().
UE_NONCOPYABLE()
FTickableEditorObject::UE_NONCOPYABLE (FTickableEditorObject)
References FTickableEditorObject().
Field Documentation
ObjectBeingTicked
UNREALED_API FTickableObjectBase* FTickableEditorObject::ObjectBeingTicked static private
Set if we are in the Tick function for an editor tickable object.
Definition at line 59 of file TickableEditorObject.h.
Referenced by ~FTickableEditorObject(), and TickObjects().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/TickableEditorObject.h