Unreal Engine 5.6 C++ API: TDirectoryTree< ValueType > Class Template Reference
TDirectoryTree< ValueType > Class Template Reference
Container for path -> value that can efficiently report whether a parent directory of a given path exists.
#include "DirectoryTree.h"
Data Structures
struct FIterationSentinel
Sentinel type used to mark the end of ranged-for iteration.
struct FIteratorInternal
struct FTreeNode
A tree structure; each node has a sorted array of child paths and a matching array of child nodes.
struct TIterator
Iterator used when iterating paths added to the tree, and skipping implied parent directories that were not added to the tree and have no Value data.
struct TPointerIterator
Iterator used when iterating all paths in the tree, both added or implied.
Public Types
using FConstIterator = TIterator<const ValueType>
using FConstPointerIterator = TPointerIterator<const ValueType>
using FIterator = TIterator<ValueType>
using FPointerIterator = TPointerIterator<ValueType>
Public Member Functions
TDirectoryTree ()
TDirectoryTree (const TDirectoryTree &Other)=default
TDirectoryTree (TDirectoryTree &&Other)=default
FIterator begin ()
Ranged-for accessor for elements in the tree.
FConstIterator begin () const
bool Contains (FStringView Path) const
Return whether the given path has been added to the tree.
bool ContainsChildPaths (FStringView Path) const
Return whether any children of the given path have been added to the tree.
bool ContainsPathOrParent (FStringView Path) const
Return whether the given path or any of its parent paths exist in the tree.
FConstIterator CreateConstIterator () const
FConstPointerIterator CreateConstIteratorForImplied () const
FIterator CreateIterator ()
Iterator accessor for path,value pairs that were added to the tree.
FPointerIterator CreateIteratorForImplied ()
Iterator accessor for all paths, added or implied, in the tree.
void Empty ()
Remove all paths and all memory usage from the tree.
FIterationSentinel end () const
ValueType * Find (FStringView Path)
Return a pointer to the Value set for the given path, or null if it does not exist.
const ValueType * Find (FStringView Path) const
Return a const pointer to the Value set for the given path, or null if it does not exist.
ValueType * FindClosestValue (FStringView Path)
Return a pointer to the path's value if it exists, or to its closest parent path's value, if any of them exist.
const ValueType * FindClosestValue (FStringView Path) const
Return a const pointer to the path's value if it exists, or to its closest parent path's value, if any of them exist.
ValueType & FindOrAdd (FStringView Path, bool *bOutExisted=nullptr)
Add a path to the tree if it does not already exist.
SIZE_T GetAllocatedSize () const
How much memory is used by *this, not counting sizeof(*this).
bool IsEmpty () const
Return true if no paths are in the tree.
int32 Num () const
Return the number of paths in the tree.
TDirectoryTree & operator= (const TDirectoryTree &Other)=default
TDirectoryTree & operator= (TDirectoryTree &&Other)=default
void Remove (FStringView Path, bool *bOutExisted=nullptr)
Remove a path from the tree and optionally report whether it existed.
void Shrink ()
Free unused slack memory throughout the tree by reallocating containers tightly to their current size.
bool TryFindClosestPath (FStringView Path, FString &OutPath, const ValueType **OutValue=nullptr) const
Return whether the given path or any of its parent paths exist in the tree.
bool TryFindClosestPath (FStringView Path, FString &OutPath, ValueType **OutValue)
Return whether the given path or any of its parent paths exist in the tree.
bool TryFindClosestPath (FStringView Path, FStringBuilderBase &OutPath, const ValueType **OutValue=nullptr) const
Return whether the given path or any of its parent paths exist in the tree.
bool TryFindClosestPath (FStringView Path, FStringBuilderBase &OutPath, ValueType **OutValue)
Return whether the given path or any of its parent paths exist in the tree.
bool TryGetChildren (FStringView Path, TArray< FString > &OutRelativeChildNames, EDirectoryTreeGetFlags Flags=EDirectoryTreeGetFlags::None) const
Report the children (optionally recursive or not, optionally implied or not) in the tree of a given Path (optionally skipped if implied).
Private Member Functions
void InitializePathSeparator (TCHAR InPathSeparator)
bool NormalizePathForReading (FStringView &Path, FStringBuilderBase &NormalizeBuffer) const
bool NormalizePathForWriting (FStringView &Path, FStringBuilderBase &NormalizeBuffer)
ValueType * TryFindClosestPathInternal (FStringView Path, FStringBuilderBase *OutPath)
Private Attributes
bool bNeedDriveWithoutPathFixup = false
bool bPathSeparatorInitialized = false
int32 NumPaths = 0
TCHAR PathSeparator = '/'
FTreeNode Root
Detailed Description
template<typename ValueType>
class TDirectoryTree< ValueType >
Container for path -> value that can efficiently report whether a parent directory of a given path exists.
Supports relative and absolute paths. Supports LongPackageNames and LocalPaths.
Note about Value comparisons: Case-insensitive / is treated as equal to \ Presence or absence of terminating separator (/) is ignored in the comparison. Directory elements of . and .. are currently not interpreted and are treated as literal characters. Callers should not rely on this behavior as it may be corrected in the future. callers should instead conform the paths before calling. Relative paths and absolute paths are not resolved, and relative paths will never equal absolute paths. Callers should not rely on this behavior as it may be corrected in the future; callers should instead conform the paths before calling.
For functions that find parent paths, parent paths are only discovered if they are conformed to the same format as the given path: both paths must be either relative or absolute.
For functions that return Values by reference or by pointer, that reference or pointer can be invalidated by any functions that modify the tree, and should be discarded before calling any such functions.
Some functions that report results for directories behave differently for added directories versus implied directories. An added directory is one that was added specifically via FindOrAdd or other mutators. An implied directory is a directory that is not added, but that has a child path that is added to the tree.
Definition at line 84 of file DirectoryTree.h.
Member Typedef Documentation
FConstIterator
template<typename ValueType> using TDirectoryTree< ValueType >::FConstIterator = TIterator<const ValueType>
Definition at line 89 of file DirectoryTree.h.
FConstPointerIterator
template<typename ValueType> using TDirectoryTree< ValueType >::FConstPointerIterator = TPointerIterator<const ValueType>
Definition at line 92 of file DirectoryTree.h.
FIterator
template<typename ValueType> using TDirectoryTree< ValueType >::FIterator = TIterator<ValueType>
Definition at line 88 of file DirectoryTree.h.
FPointerIterator
template<typename ValueType> using TDirectoryTree< ValueType >::FPointerIterator = TPointerIterator<ValueType>
Definition at line 91 of file DirectoryTree.h.
Constructor & Destructor Documentation
TDirectoryTree() [1/3]
template<typename ValueType> TDirectoryTree< ValueType >::TDirectoryTree () inline
Definition at line 434 of file DirectoryTree.h.
References check, and Root.
Referenced by TDirectoryTree(), TDirectoryTree(), TDirectoryTree< ValueType >::TIterator< ViewedValueType >::TIterator(), Find(), FindClosestValue(), TDirectoryTree< ValueType >::FIteratorInternal::operator bool(), TDirectoryTree< ValueType >::TIterator< ValueType >::operator->(), TDirectoryTree< ValueType >::TPointerIterator< ValueType >::operator->(), operator=(), operator=(), TryFindClosestPath(), and TryFindClosestPath().
TDirectoryTree() [2/3]
template<typename ValueType> TDirectoryTree< ValueType >::TDirectoryTree (const TDirectoryTree< ValueType > & Other) default
References TDirectoryTree(), and Other.
TDirectoryTree() [3/3]
template<typename ValueType> TDirectoryTree< ValueType >::TDirectoryTree (TDirectoryTree< ValueType > && Other) default
References TDirectoryTree(), and Other.
Member Function Documentation
begin() [1/2]
template<typename ValueType> TDirectoryTree< ValueType >::FIterator TDirectoryTree< ValueType >::begin () inline
Ranged-for accessor for elements in the tree.
Same behavior as
See also
CreateIterator.
Definition at line 1952 of file DirectoryTree.h.
References CreateIterator().
begin() [2/2]
template<typename ValueType> TDirectoryTree< ValueType >::FConstIterator TDirectoryTree< ValueType >::begin () const inline
Definition at line 1958 of file DirectoryTree.h.
References CreateConstIterator().
Contains()
template<typename ValueType> bool TDirectoryTree< ValueType >::Contains (FStringView Path) const inline
Return whether the given path has been added to the tree.
Definition at line 545 of file DirectoryTree.h.
References Find, and Path.
ContainsChildPaths()
template<typename ValueType> bool TDirectoryTree< ValueType >::ContainsChildPaths (FStringView Path) const inline
Return whether any children of the given path have been added to the tree.
Definition at line 744 of file DirectoryTree.h.
References NormalizePathForReading(), Path, and Root.
ContainsPathOrParent()
template<typename ValueType> bool TDirectoryTree< ValueType >::ContainsPathOrParent (FStringView Path) const inline
Return whether the given path or any of its parent paths exist in the tree.
Definition at line 571 of file DirectoryTree.h.
References FindClosestValue(), and Path.
CreateConstIterator()
template<typename ValueType> TDirectoryTree< ValueType >::FConstIterator TDirectoryTree< ValueType >::CreateConstIterator () const inline
Definition at line 1928 of file DirectoryTree.h.
References PathSeparator, Recursive, and Root.
Referenced by begin().
CreateConstIteratorForImplied()
template<typename ValueType> TDirectoryTree< ValueType >::FConstPointerIterator TDirectoryTree< ValueType >::CreateConstIteratorForImplied () const inline
Definition at line 1944 of file DirectoryTree.h.
References ImpliedChildren, PathSeparator, Recursive, and Root.
CreateIterator()
template<typename ValueType> TDirectoryTree< ValueType >::FIterator TDirectoryTree< ValueType >::CreateIterator () inline
Iterator accessor for path,value pairs that were added to the tree.
See also
FIterator.
Definition at line 1920 of file DirectoryTree.h.
References PathSeparator, Recursive, and Root.
Referenced by begin().
CreateIteratorForImplied()
template<typename ValueType> TDirectoryTree< ValueType >::FPointerIterator TDirectoryTree< ValueType >::CreateIteratorForImplied () inline
Iterator accessor for all paths, added or implied, in the tree.
For paths that were added to the tree, the ValueType* on the iterator is non-null and points to the added Value. For implied paths that are parent directories of child paths in the tree the Value pointer of the iterator is the value of their closest parent in the tree, or nullptr if none of their parents were added to the tree.
See also
FPointerIterator.
Definition at line 1936 of file DirectoryTree.h.
References ImpliedChildren, PathSeparator, Recursive, and Root.
Empty()
template<typename ValueType> void TDirectoryTree< ValueType >::Empty () inline
Remove all paths and all memory usage from the tree.
Definition at line 482 of file DirectoryTree.h.
References bPathSeparatorInitialized, NumPaths, PathSeparator, and Root.
end()
template<typename ValueType> TDirectoryTree< ValueType >::FIterationSentinel TDirectoryTree< ValueType >::end () const inline
Definition at line 1964 of file DirectoryTree.h.
Find() [1/2]
template<typename ValueType> ValueType * TDirectoryTree< ValueType >::Find (FStringView Path) inline
Return a pointer to the Value set for the given path, or null if it does not exist.
Definition at line 557 of file DirectoryTree.h.
References NormalizePathForReading(), Path, and Root.
Find() [2/2]
template<typename ValueType> const ValueType * TDirectoryTree< ValueType >::Find (FStringView Path) const inline
Return a const pointer to the Value set for the given path, or null if it does not exist.
Definition at line 551 of file DirectoryTree.h.
References TDirectoryTree(), Find, and Path.
FindClosestValue() [1/2]
template<typename ValueType> ValueType * TDirectoryTree< ValueType >::FindClosestValue (FStringView Path) inline
Return a pointer to the path's value if it exists, or to its closest parent path's value, if any of them exist.
Otherwise return nullptr.
Definition at line 583 of file DirectoryTree.h.
References Path, and TryFindClosestPathInternal().
FindClosestValue() [2/2]
template<typename ValueType> const ValueType * TDirectoryTree< ValueType >::FindClosestValue (FStringView Path) const inline
Return a const pointer to the path's value if it exists, or to its closest parent path's value, if any of them exist.
Otherwise return nullptr.
Definition at line 577 of file DirectoryTree.h.
References TDirectoryTree(), Path, and TryFindClosestPathInternal().
Referenced by ContainsPathOrParent().
FindOrAdd()
template<typename ValueType> ValueType & TDirectoryTree< ValueType >::FindOrAdd (FStringView Path, bool * bOutExisted = nullptr)
Add a path to the tree if it does not already exist.
Construct default Value for it if it did not already exist. Return a reference to the added or existing Value. Optionally report whether the path already existed. This reference can be invalidated by any operations that modify the tree.
Definition at line 440 of file DirectoryTree.h.
References bPathSeparatorInitialized, InitializePathSeparator(), NormalizePathForWriting(), NumPaths, Path, and Root.
GetAllocatedSize()
template<typename ValueType> SIZE_T TDirectoryTree< ValueType >::GetAllocatedSize () const inline
How much memory is used by *this, not counting sizeof(*this).
Definition at line 539 of file DirectoryTree.h.
References Root.
InitializePathSeparator()
template<typename ValueType> void TDirectoryTree< ValueType >::InitializePathSeparator (TCHAR InPathSeparator) inline private
Definition at line 723 of file DirectoryTree.h.
References bNeedDriveWithoutPathFixup, bPathSeparatorInitialized, check, PathSeparator, and Root.
Referenced by FindOrAdd().
IsEmpty()
template<typename ValueType> bool TDirectoryTree< ValueType >::IsEmpty () const inline
Return true if no paths are in the tree.
Definition at line 527 of file DirectoryTree.h.
References Root.
NormalizePathForReading()
template<typename ValueType> bool TDirectoryTree< ValueType >::NormalizePathForReading (FStringView & Path, FStringBuilderBase & NormalizeBuffer) const inline private
Definition at line 683 of file DirectoryTree.h.
References FPathViews::IsDriveSpecifierWithoutRoot(), Path, PathSeparator, FPathViews::SplitVolumeSpecifier(), TStringBuilderBase< CharType >::ToView(), and Volume.
Referenced by ContainsChildPaths(), Find(), NormalizePathForWriting(), Remove(), TryFindClosestPathInternal(), and TryGetChildren().
NormalizePathForWriting()
template<typename ValueType> bool TDirectoryTree< ValueType >::NormalizePathForWriting (FStringView & Path, FStringBuilderBase & NormalizeBuffer) inline private
Definition at line 709 of file DirectoryTree.h.
References bNeedDriveWithoutPathFixup, bPathSeparatorInitialized, NormalizePathForReading(), and Path.
Referenced by FindOrAdd().
Num()
template<typename ValueType> int32 TDirectoryTree< ValueType >::Num () const inline
Return the number of paths in the tree.
Definition at line 533 of file DirectoryTree.h.
References NumPaths.
Referenced by TDirectoryTree< ValueType >::FTreeNode::FixupDirectChildrenPathSeparator().
operator=() [1/2]
template<typename ValueType> TDirectoryTree & TDirectoryTree< ValueType >::operator= (const TDirectoryTree< ValueType > & Other) default
References TDirectoryTree(), and Other.
operator=() [2/2]
template<typename ValueType> TDirectoryTree & TDirectoryTree< ValueType >::operator= (TDirectoryTree< ValueType > && Other) default
References TDirectoryTree(), and Other.
Remove()
template<typename ValueType> void TDirectoryTree< ValueType >::Remove (FStringView Path, bool * bOutExisted = nullptr)
Remove a path from the tree and optionally report whether it existed.
Definition at line 491 of file DirectoryTree.h.
References check, NormalizePathForReading(), NumPaths, Path, and Root.
Shrink()
template<typename ValueType> void TDirectoryTree< ValueType >::Shrink () inline
Free unused slack memory throughout the tree by reallocating containers tightly to their current size.
Definition at line 521 of file DirectoryTree.h.
References Root.
TryFindClosestPath() [1/4]
template<typename ValueType> bool TDirectoryTree< ValueType >::TryFindClosestPath (FStringView Path, FString & OutPath, const ValueType ** OutValue = nullptr) const inline
Return whether the given path or any of its parent paths exist in the tree.
If it exists, return the discovered path, and optionally return a const pointer to the value of that path.
Definition at line 589 of file DirectoryTree.h.
References TDirectoryTree(), Path, and TryFindClosestPath().
TryFindClosestPath() [2/4]
template<typename ValueType> bool TDirectoryTree< ValueType >::TryFindClosestPath (FStringView Path, FString & OutPath, ValueType ** OutValue) inline
Return whether the given path or any of its parent paths exist in the tree.
If it exists, return the discovered path, and optionally return a pointer to the value of that path.
Definition at line 604 of file DirectoryTree.h.
References Path, and TryFindClosestPathInternal().
TryFindClosestPath() [3/4]
template<typename ValueType> bool TDirectoryTree< ValueType >::TryFindClosestPath (FStringView Path, FStringBuilderBase & OutPath, const ValueType ** OutValue = nullptr) const inline
Return whether the given path or any of its parent paths exist in the tree.
If it exists, return the discovered path, and optionally return a const pointer to the value of that path.
Definition at line 625 of file DirectoryTree.h.
References TDirectoryTree(), Path, and TryFindClosestPath().
Referenced by TryFindClosestPath(), and TryFindClosestPath().
TryFindClosestPath() [4/4]
template<typename ValueType> bool TDirectoryTree< ValueType >::TryFindClosestPath (FStringView Path, FStringBuilderBase & OutPath, ValueType ** OutValue) inline
Return whether the given path or any of its parent paths exist in the tree.
If it exists, return the discovered path, and optionally return a pointer to the value of that path.
Definition at line 640 of file DirectoryTree.h.
References Path, and TryFindClosestPathInternal().
TryFindClosestPathInternal()
template<typename ValueType> ValueType * TDirectoryTree< ValueType >::TryFindClosestPathInternal (FStringView Path, FStringBuilderBase * OutPath) inline private
Definition at line 658 of file DirectoryTree.h.
References NormalizePathForReading(), Path, PathSeparator, TStringBuilderBase< CharType >::Reset(), and Root.
Referenced by FindClosestValue(), FindClosestValue(), TryFindClosestPath(), and TryFindClosestPath().
TryGetChildren()
template<typename ValueType> bool TDirectoryTree< ValueType >::TryGetChildren (FStringView Path, TArray< FString > & OutRelativeChildNames, EDirectoryTreeGetFlags Flags = EDirectoryTreeGetFlags::None) const inline
Report the children (optionally recursive or not, optionally implied or not) in the tree of a given Path (optionally skipped if implied).
See also
EDirectoryTreeGetFlags. Relative paths of discovered children will be appended to OutRelativeChildNames.
Returns
true iff (the path is found in the tree and either it is an added path or ImpliedParent was requested).
Definition at line 753 of file DirectoryTree.h.
References EnumHasAnyFlags(), Flags, ImpliedParent, NormalizePathForReading(), Path, PathSeparator, and Root.
Field Documentation
bNeedDriveWithoutPathFixup
template<typename ValueType> bool TDirectoryTree< ValueType >::bNeedDriveWithoutPathFixup = false private
Definition at line 429 of file DirectoryTree.h.
Referenced by InitializePathSeparator(), and NormalizePathForWriting().
bPathSeparatorInitialized
template<typename ValueType> bool TDirectoryTree< ValueType >::bPathSeparatorInitialized = false private
Definition at line 428 of file DirectoryTree.h.
Referenced by Empty(), FindOrAdd(), InitializePathSeparator(), and NormalizePathForWriting().
NumPaths
template<typename ValueType> int32 TDirectoryTree< ValueType >::NumPaths = 0 private
Definition at line 426 of file DirectoryTree.h.
Referenced by Empty(), FindOrAdd(), Num(), and Remove().
PathSeparator
template<typename ValueType> TCHAR TDirectoryTree< ValueType >::PathSeparator = '/' private
Definition at line 427 of file DirectoryTree.h.
Referenced by CreateConstIterator(), CreateConstIteratorForImplied(), CreateIterator(), CreateIteratorForImplied(), Empty(), InitializePathSeparator(), NormalizePathForReading(), TryFindClosestPathInternal(), and TryGetChildren().
Root
template<typename ValueType> FTreeNode TDirectoryTree< ValueType >::Root private
Definition at line 425 of file DirectoryTree.h.
Referenced by TDirectoryTree< ValueType >::FIteratorInternal::FIteratorInternal(), TDirectoryTree(), TDirectoryTree< ValueType >::TIterator< ViewedValueType >::TIterator(), TDirectoryTree< ValueType >::TIterator< ValueType >::TIterator(), TDirectoryTree< ValueType >::TPointerIterator< ViewedValueType >::TPointerIterator(), TDirectoryTree< ValueType >::TPointerIterator< ValueType >::TPointerIterator(), ContainsChildPaths(), CreateConstIterator(), CreateConstIteratorForImplied(), CreateIterator(), CreateIteratorForImplied(), Empty(), Find(), FindOrAdd(), GetAllocatedSize(), InitializePathSeparator(), IsEmpty(), Remove(), Shrink(), TryFindClosestPathInternal(), and TryGetChildren().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/DirectoryTree.h