Unreal Engine 5.6 C++ API: FTabManager Class Reference
FTabManager Class Reference
#include "TabManager.h"
Data Structures
struct ESearchPreference
class FArea
class FLastMajorOrNomadTab
class FLayout
class FLayoutNode
class FLiveTabSearch
class FPrivateApi
class FRequireClosedTab
class FSearchPreference
class FSplitter
class FStack
struct FTab
Public Member Functions
virtual ~FTabManager ()
TSharedRef< FWorkspaceItem > AddLocalWorkspaceMenuCategory (const FText &CategoryTitle)
Adds a category to the local workspace menu by name.
void AddLocalWorkspaceMenuItem (const TSharedRef< FWorkspaceItem > &CategoryItem)
Adds an existing workspace item to the local workspace menu.
bool AllowsWindowMenuBar () const
Whether or not this tab manager supports a custom menu bar for the active major tab that will be shown on top of the major tab area in the window this tab manager resides in.
void ClearLocalWorkspaceMenuCategories ()
Clears all categories in the local workspace menu.
void ClearPendingLayoutSave ()
Clears the request for a deferred save of the layout.
void CloseAllAreas ()
Close all live areas and wipe all the persisted areas.
TArray< TWeakPtr< FTabSpawnerEntry > > CollectSpawners ()
Return an array of all tab spawners that should have menu items in the main menu.
DECLARE_DELEGATE_OneParam (FOnPersistLayout, const TSharedRef< FLayout > &)
virtual void DrawAttention (const TSharedRef< SDockTab > &TabToHighlight)
TSharedPtr< SDockTab > FindExistingLiveTab (const FTabId &TabId) const
Finds the first instance of an existing tab with the given tab id.
TSharedPtr< FTabSpawnerEntry > FindTabSpawnerFor (FName TabId)
Find a tab spawner by name.
const TSharedPtr< const FTabSpawnerEntry > FindTabSpawnerFor (FName TabId) const
Find a tab spawner by name.
TSharedPtr< FArea > GetAreaFromInitialLayoutWithTabType (const FTabId &InTabIdToMatch) const
Gets a TSharedPtr<FArea> with the given FTabId if present, else it return nullptr.
bool GetCanDoDragOperation ()
const TSharedRef< FWorkspaceItem > GetLocalWorkspaceMenuRoot () const
FOnReadOnlyModeChanged & GetOnReadOnlyModeChangedDelegate ()
TSharedPtr< SDockTab > GetOwnerTab ()
Returns the owner tab (if it exists)
FTabManager::FPrivateApi & GetPrivateApi ()
TSharedRef< FNamePermissionList > & GetTabPermissionList ()
Returns filter for additional control over available tabs.
TOptional< ETabReadOnlyBehavior > GetTabReadOnlyBehavior (const FTabId &TabId) const
FUIAction GetUIActionForTabSpawnerMenuEntry (TSharedPtr< FTabSpawnerEntry > InTabMenuEntry)
bool HasTabSpawner (FName TabId) const
bool HasValidOpenTabs (const TSharedRef< FTabManager::FLayoutNode > &SomeNode) const
It searches for valid and open tabs on SomeNode.
void InsertNewDocumentTab (FName PlaceholderId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
void InsertNewDocumentTab (FName PlaceholderId, ESearchPreference::Type SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
void InsertNewDocumentTab (FName PlaceholderId, FName NewTabId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
bool IsReadOnly ()
Is this Tab Manager in Read Only mode i.e all interactions with panels are disabled.
bool IsTabAllowedInSidebar (const FTabId TabId) const
bool IsTabCloseable (const TSharedRef< const SDockTab > &InTab) const
TSharedRef< FTabManager::FLayout > PersistLayout () const
Gather the persistent layout.
void PopulateLocalTabSpawnerMenu (FMenuBuilder &PopulateMe)
void PopulateTabSpawnerMenu (FMenuBuilder &PopulateMe, const FName &TabType)
void PopulateTabSpawnerMenu (FMenuBuilder &PopulateMe, TSharedRef< FWorkspaceItem > MenuStructure)
void PopulateTabSpawnerMenu (FMenuBuilder &PopulateMe, TSharedRef< FWorkspaceItem > MenuStructure, bool bIncludeOrphanedMenus)
FTabSpawnerEntry & RegisterTabSpawner (const FName TabId, const FOnSpawnTab &OnSpawnTab, const FCanSpawnTab &CanSpawnTab=FCanSpawnTab())
Register a new tab spawner with the tab manager.
void RequestSavePersistentLayout ()
Request a deferred save of the layout.
void RestoreDocumentTab (FName PlaceholderId, ESearchPreference::Type SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
Much like InsertNewDocumentTab, but the UnmanagedTab is not seen by the user as newly-created.
TSharedPtr< SWidget > RestoreFrom (const TSharedRef< FLayout > &Layout, const TSharedPtr< SWindow > &ParentWindow, const bool bEmbedTitleAreaContent=false, const EOutputCanBeNullptr RestoreAreaOutputCanBeNullptr=EOutputCanBeNullptr::Never)
void SavePersistentLayout ()
Gather the persistent layout and execute the custom delegate for saving it to persistent storage (e.g.
void SetAllowWindowMenuBar (bool bInAllowWindowMenuBar)
Sets whether or not this tab manager supports a custom menu bar for the active major tab that will be shown on top of the major tab area in the window this tab manager resides in.
void SetCanDoDragOperation (bool CanDoDragOperation)
void SetMainTab (const FTabId &InMainTabID)
void SetMainTab (const TSharedRef< const SDockTab > &InTab)
Provide a tab that will be the main tab and cannot be closed.
void SetMenuMultiBox (const TSharedPtr< FMultiBox > NewMenuMutliBox, const TSharedPtr< SWidget > MenuWidget)
Set the multi-box to use for generating a global menu bar.
void SetOnPersistLayout (const FOnPersistLayout &InHandler)
void SetReadOnly (bool bInReadOnly)
void ToggleSidebarOpenTabs ()
Temporarily moves all open tabs in this tab manager to a sidebar or restores them from a temporary state.
virtual TSharedPtr< SDockTab > TryInvokeTab (const FTabId &TabId, bool bInvokeAsInactive=false)
Try to open tab if it is closed at the last known location.
void UnregisterAllTabSpawners ()
Unregisters all tab spawners.
bool UnregisterTabSpawner (const FName TabId)
Unregisters the tab spawner matching the provided TabId.
void UpdateMainMenu (TSharedPtr< SDockTab > ForTab, const bool bForce)
Update the native, global menu bar if it is being used.
Public Member Functions inherited from TSharedFromThis< FTabManager >
TSharedRef< FTabManager, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FTabManager, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FArea > NewArea (const float Width, const float Height)
static TSharedRef< FArea > NewArea (const FVector2D &WindowSize)
static TSharedRef< FLayout > NewLayout (const FName LayoutName)
static TSharedRef< FArea > NewPrimaryArea ()
static TSharedRef< FSplitter > NewSplitter ()
static TSharedRef< FStack > NewStack ()
static void RegisterDefaultTabWindowSize (const FTabId &TabName, const FVector2D DefaultSize)
static void UnregisterDefaultTabWindowSize (const FTabId &TabName)
Protected Types
typedef TMap< FName, TSharedRef< FTabSpawnerEntry > > FTabSpawner
Protected Member Functions
FTabManager (const TSharedPtr< SDockTab > &InOwnerTab, const TSharedRef< FTabManager::FTabSpawner > &InNomadTabSpawner)
virtual bool CanCloseManager (const TSet< TSharedRef< SDockTab > > &TabsToIgnore=TSet< TSharedRef< SDockTab > >())
Check these all tabs to see if it is OK to close them.
bool CanRestoreSplitterContent (TArray< TSharedRef< class SDockingNode > > &DockingNodes, const TSharedRef< FSplitter > &SplitterNode, const TSharedPtr< SWindow > &ParentWindow, FSidebarTabLists &OutSidebarTabs, const EOutputCanBeNullptr OutputCanBeNullptr)
Use CanRestoreSplitterContent + RestoreSplitterContent when the output of its internal RestoreArea_Helper can be a nullptr.
TSharedPtr< SDockTab > FindLastTabInWindow (TSharedPtr< SWindow > Window) const
Finds the last major or nomad tab in a particular window.
TSharedPtr< SDockingTabStack > FindPotentiallyClosedTab (const FTabId &ClosedTabId)
int32 FindTabInCollapsedAreas (const FTabMatcher &Matcher)
TSharedPtr< class SDockingTabStack > FindTabInLiveAreas (const FTabMatcher &TabMatcher) const
virtual void FinishRestore ()
Called at the end of RestoreFrom for tab managers to complete any work after all tabs have been restored.
bool HasTabSpawnerFor (FName TabId) const
bool HasValidTabs (const TSharedRef< FTabManager::FLayoutNode > &SomeNode) const
void InsertDocumentTab (FName PlaceholderId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab, bool bPlaySpawnAnim)
void InsertDocumentTab (FName PlaceholderId, FName NewTabId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab, bool bPlaySpawnAnim)
TSharedPtr< SDockTab > InvokeTab_Internal (const FTabId &TabId, bool bInvokeAsInactive=false, bool bForceOpenWindowIfNeeded=false)
void InvokeTabForMenu (FName TabId)
bool IsAllowedTab (const FTabId &TabId) const
bool IsAllowedTabType (const FName TabType) const
bool IsValidTabForSpawning (const FTab &SomeTab) const
void MakeSpawnerMenuEntry (FMenuBuilder &PopulateMe, const TSharedPtr< FTabSpawnerEntry > &InSpawnerNode)
virtual void OnTabClosing (const TSharedRef< SDockTab > &TabBeingClosed)
virtual void OnTabForegrounded (const TSharedPtr< SDockTab > &NewForegroundTab, const TSharedPtr< SDockTab > &BackgroundedTab)
Notify the tab manager that the NewForegroundTab was brought to front and the BackgroundedTab was send to the background as a result.
virtual void OnTabManagerClosing ()
Invoked when a tab manager is closing down.
virtual void OnTabOpening (const TSharedRef< SDockTab > &TabBeingOpened)
virtual void OnTabRelocated (const TSharedRef< SDockTab > &RelocatedTab, const TSharedPtr< SWindow > &NewOwnerWindow)
virtual void OpenUnmanagedTab (FName PlaceholderId, const FSearchPreference &SearchPreference, const TSharedRef< SDockTab > &UnmanagedTab)
void PopulateTabSpawnerMenu_Helper (FMenuBuilder &PopulateMe, struct FPopulateTabSpawnerMenu_Args Args)
void RemoveTabFromCollapsedAreas (const FTabMatcher &Matcher)
TSharedPtr< SDockingArea > RestoreArea (const TSharedRef< FArea > &AreaToRestore, const TSharedPtr< SWindow > &InParentWindow, const bool bEmbedTitleAreaContent=false, const EOutputCanBeNullptr OutputCanBeNullptr=EOutputCanBeNullptr::Never, bool bForceOpenWindowIfNeeded=false)
TSharedPtr< class SDockingNode > RestoreArea_Helper (const TSharedRef< FLayoutNode > &LayoutNode, const TSharedPtr< SWindow > &ParentWindow, const bool bEmbedTitleAreaContent, FSidebarTabLists &OutSidebarTabs, const EOutputCanBeNullptr OutputCanBeNullptr=EOutputCanBeNullptr::Never, bool bForceOpenWindowIfNeeded=false)
void RestoreSplitterContent (const TArray< TSharedRef< class SDockingNode > > &DockingNodes, const TSharedRef< class SDockingSplitter > &SplitterWidget)
void RestoreSplitterContent (const TSharedRef< FSplitter > &SplitterNode, const TSharedRef< class SDockingSplitter > &SplitterWidget, const TSharedPtr< SWindow > &ParentWindow, FSidebarTabLists &OutSidebarTabs)
Use this standalone RestoreSplitterContent when the output of its internal RestoreArea_Helper cannot be a nullptr.
void SetTabsTo (const TSharedRef< FTabManager::FLayoutNode > &SomeNode, const ETabState::Type NewTabState, const ETabState::Type OriginalTabState) const
It sets the desired (or all) tabs in the FTabManager::FLayoutNode to the desired value.
TSharedPtr< SDockTab > SpawnTab (const FTabId &TabId, const TSharedPtr< SWindow > &ParentWindow, const bool bCanOutputBeNullptr=false)
virtual void UpdateStats ()
Called when tab(s) have been added or windows created.
Protected Member Functions inherited from TSharedFromThis< FTabManager >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static TSharedPtr< class SDockingTabStack > FindTabInLiveArea (const FTabMatcher &TabMatcher, const TSharedRef< SDockingArea > &InArea)
static TSharedPtr< FTabManager::FStack > FindTabUnderNode (const FTabMatcher &Matcher, const TSharedRef< FTabManager::FLayoutNode > &NodeToSearchUnder)
static void GetAllStacks (const TSharedRef< SDockingArea > &InDockArea, TArray< TSharedRef< SDockingTabStack > > &OutTabStacks)
static FVector2D GetDefaultTabWindowSize (const FTabId &TabId)
Returns the default window size for the TabId, or the fallback window size if it wasn't registered.
static bool HasAnyMatchingTabs (const TSharedRef< FTabManager::FLayoutNode > &SomeNode, const TFunctionRef< bool(const FTab &)> &Matcher)
static TSharedRef< FTabManager > New (const TSharedPtr< SDockTab > &InOwnerTab, const TSharedRef< FTabSpawner > &InNomadTabSpawner)
Static Protected Member Functions inherited from TSharedFromThis< FTabManager >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
FName ActiveLayoutName
The name of the layout being used.
bool bAllowPerWindowMenu = false
Whether or not this tab manager puts any registered menus in the windows menu bar area.
bool bCanDoDeferredLayoutSave = true
Whether or not this tab manager can perform deferred layout saves at this time; used internally to disable layout saves during drag operations.
bool bCanDoDragOperation = true
bool bEnforceMainTab = false
If true, this tab manager will always have one non-closable tab.
bool bReadOnly = false
Whether this tab manager is in a read only mode (all tabs content disabled by default - overridable per tab)
TArray< TSharedRef< FTabManager::FArea > > CollapsedDockAreas
CollapsedDockAreas refers to areas that were closed (e.g., by the user).
TArray< TWeakPtr< SDockingArea > > DockAreas
TArray< TSharedRef< FTabManager::FArea > > InvalidDockAreas
InvalidDockAreas refers to areas that were not recognized by the Editor (e.g., LiveLink when its plugin its disabled).
int32 LastDocumentUID
Instance ID for document tabs.
TWeakPtr< SWindow > LastMajorDockWindow
The last window we docked a nomad or major tab into.
TSharedPtr< FWorkspaceItem > LocalWorkspaceMenuRoot
The root for the local editor's tab spawner workspace menu.
FTabId MainNonCloseableTabID
The ID of the main tab, which cannot be closed.
TSharedPtr< FMultiBox > MenuMultiBox
The current menu multi-box for the tab, used to construct platform native main menus.
TSharedPtr< SWidget > MenuWidget
TSharedRef< FTabSpawner > NomadTabSpawner
FOnPersistLayout OnPersistLayout_Handler
Invoked when the tab manager is about to close.
FOnReadOnlyModeChanged OnReadOnlyModeChanged
Delegate that broadcasts when the tab manager enters/leaves read only mode.
TWeakPtr< SDockTab > OwnerTabPtr
A Major tab that contains this TabManager's widgets.
FTSTicker::FDelegateHandle PendingLayoutSaveHandle
Handle to a pending layout save.
TSharedPtr< const SDockTab > PendingMainNonClosableTab
To keep track of any pending tabs that want to be the main tab, but don't have their ID set yet.
TSharedRef< FPrivateApi > PrivateApi
Protected private API that must only be accessed by the docking framework internals.
TSharedRef< FNamePermissionList > TabPermissionList
Allow systems to dynamically hide tabs.
FTabSpawner TabSpawner
TArray< TWeakPtr< SDockTab > > TemporarilySidebaredTabs
Tabs which have been temporarily put in the a sidebar.
Static Protected Attributes
static TMap< FTabId, FVector2D > DefaultTabWindowSizeMap
Default tab window sizes for newly-created tabs.
static const FVector2D FallbackWindowSize
The fallback size for a window.
Private Member Functions
TSharedPtr< SDockingTabStack > AttemptToOpenTab (const FTabId &ClosedTabId, bool bForceOpenWindowIfNeeded=false)
TSharedRef< FArea > GetAreaForTabId (const FTabId &TabId)
Given FTabId returns the proper TSharedRef<FArea> to load it.
void GetRecordableStats (int32 &OutTabCount, TArray< TSharedPtr< SWindow > > &OutUniqueParentWindows) const
Checks all dock areas and adds up the number of open tabs and unique parent windows in the manager.
bool HasAnyTabWithTabId (const TSharedRef< FTabManager::FLayoutNode > &SomeNode, const FName &InTabTypeToMatch) const
Returns true if the given FLayoutNode contains a tab with the given FTabId.TabType.
Friends
class FGlobalTabmanager
class FPrivateApi
Detailed Description
Definition at line 386 of file TabManager.h.
Member Typedef Documentation
FTabSpawner
typedef TMap< FName, TSharedRef<FTabSpawnerEntry> > FTabManager::FTabSpawner protected
Definition at line 1067 of file TabManager.h.
Constructor & Destructor Documentation
~FTabManager()
virtual FTabManager::~FTabManager () virtual
FTabManager()
FTabManager::FTabManager (const TSharedPtr< SDockTab > & InOwnerTab, const TSharedRef< FTabManager::FTabSpawner > & InNomadTabSpawner) protected
Referenced by FGlobalTabmanager::FGlobalTabmanager(), FTabManager::FPrivateApi::FPrivateApi(), FProxyTabmanager::FProxyTabmanager(), New(), FTabManager::FLastMajorOrNomadTab::Search(), FTabManager::FLiveTabSearch::Search(), FTabManager::FRequireClosedTab::Search(), and FTabManager::FSearchPreference::Search().
Member Function Documentation
AddLocalWorkspaceMenuCategory()
TSharedRef< FWorkspaceItem > FTabManager::AddLocalWorkspaceMenuCategory (const FText & CategoryTitle)
Adds a category to the local workspace menu by name.
AddLocalWorkspaceMenuItem()
void FTabManager::AddLocalWorkspaceMenuItem (const TSharedRef< FWorkspaceItem > & CategoryItem)
Adds an existing workspace item to the local workspace menu.
AllowsWindowMenuBar()
bool FTabManager::AllowsWindowMenuBar () const inline
Whether or not this tab manager supports a custom menu bar for the active major tab that will be shown on top of the major tab area in the window this tab manager resides in.
Definition at line 965 of file TabManager.h.
References bAllowPerWindowMenu.
AttemptToOpenTab()
TSharedPtr< SDockingTabStack > FTabManager::AttemptToOpenTab (const FTabId & ClosedTabId, bool bForceOpenWindowIfNeeded = false) private
CanCloseManager()
virtual bool FTabManager::CanCloseManager (const TSet< TSharedRef< SDockTab > > & TabsToIgnore = TSet< TSharedRef< SDockTab > >()) protected virtual
Check these all tabs to see if it is OK to close them.
Ignore the TabsToIgnore
Reimplemented in FGlobalTabmanager.
CanRestoreSplitterContent()
bool FTabManager::CanRestoreSplitterContent (TArray< TSharedRef< class SDockingNode > > & DockingNodes, const TSharedRef< FSplitter > & SplitterNode, const TSharedPtr< SWindow > & ParentWindow, FSidebarTabLists & OutSidebarTabs, const EOutputCanBeNullptr OutputCanBeNullptr) protected
Use CanRestoreSplitterContent + RestoreSplitterContent when the output of its internal RestoreArea_Helper can be a nullptr.
Usage example: TArray<TSharedRef<SDockingNode>> DockingNodes; if (CanRestoreSplitterContent(DockingNodes, SplitterNode, ParentWindow, OutputCanBeNullptr)) { // Create SplitterWidget only if it will be filled with at least 1 DockingNodes TSharedRef<SDockingSplitter> SplitterWidget = SNew(SDockingSplitter, SplitterNode); // Restore content RestoreSplitterContent(DockingNodes, SplitterWidget); }
ClearLocalWorkspaceMenuCategories()
void FTabManager::ClearLocalWorkspaceMenuCategories ()
Clears all categories in the local workspace menu.
ClearPendingLayoutSave()
void FTabManager::ClearPendingLayoutSave ()
Clears the request for a deferred save of the layout.
CloseAllAreas()
void FTabManager::CloseAllAreas ()
Close all live areas and wipe all the persisted areas.
CollectSpawners()
TArray< TWeakPtr< FTabSpawnerEntry > > FTabManager::CollectSpawners ()
Return an array of all tab spawners that should have menu items in the main menu.
DECLARE_DELEGATE_OneParam()
FTabManager::DECLARE_DELEGATE_OneParam (FOnPersistLayout , const TSharedRef< FLayout > &)
DrawAttention()
virtual void FTabManager::DrawAttention (const TSharedRef< SDockTab > & TabToHighlight) virtual
Reimplemented in FProxyTabmanager.
FindExistingLiveTab()
TSharedPtr< SDockTab > FTabManager::FindExistingLiveTab (const FTabId & TabId) const
Finds the first instance of an existing tab with the given tab id.
Parameters
TabId The tab identifier.
Returns
The existing tab instance if found, otherwise null.
FindLastTabInWindow()
TSharedPtr< SDockTab > FTabManager::FindLastTabInWindow (TSharedPtr< SWindow > Window) const protected
Finds the last major or nomad tab in a particular window.
FindPotentiallyClosedTab()
TSharedPtr< SDockingTabStack > FTabManager::FindPotentiallyClosedTab (const FTabId & ClosedTabId) protected
FindTabInCollapsedAreas()
int32 FTabManager::FindTabInCollapsedAreas (const FTabMatcher & Matcher) protected
FindTabInLiveArea()
TSharedPtr< class SDockingTabStack > FTabManager::FindTabInLiveArea (const FTabMatcher & TabMatcher, const TSharedRef< SDockingArea > & InArea) static protected
FindTabInLiveAreas()
TSharedPtr< class SDockingTabStack > FTabManager::FindTabInLiveAreas (const FTabMatcher & TabMatcher) const protected
FindTabSpawnerFor() [1/2]
TSharedPtr< FTabSpawnerEntry > FTabManager::FindTabSpawnerFor (FName TabId)
Find a tab spawner by name.
FindTabSpawnerFor() [2/2]
const TSharedPtr< const FTabSpawnerEntry > FTabManager::FindTabSpawnerFor (FName TabId) const
Find a tab spawner by name.
FindTabUnderNode()
TSharedPtr< FTabManager::FStack > FTabManager::FindTabUnderNode (const FTabMatcher & Matcher, const TSharedRef< FTabManager::FLayoutNode > & NodeToSearchUnder) static protected
Returns
the stack that is under NodeToSearchUnder and contains TabIdToFind; Invalid pointer if not found.
FinishRestore()
virtual void FTabManager::FinishRestore () inline protected virtual
Called at the end of RestoreFrom for tab managers to complete any work after all tabs have been restored.
Reimplemented in FGlobalTabmanager.
Definition at line 1162 of file TabManager.h.
GetAllStacks()
void FTabManager::GetAllStacks (const TSharedRef< SDockingArea > & InDockArea, TArray< TSharedRef< SDockingTabStack > > & OutTabStacks) static protected
GetAreaForTabId()
TSharedRef< FArea > FTabManager::GetAreaForTabId (const FTabId & TabId) private
Given FTabId returns the proper TSharedRef<FArea> to load it.
Parameters
TabId the FTabId for which to find the FArea
GetAreaFromInitialLayoutWithTabType()
TSharedPtr< FArea > FTabManager::GetAreaFromInitialLayoutWithTabType (const FTabId & InTabIdToMatch) const
Gets a TSharedPtr<FArea> with the given FTabId if present, else it return nullptr.
Parameters
InTabIdToMatch the const &FTabId for which to find the FArea
GetCanDoDragOperation()
bool FTabManager::GetCanDoDragOperation () inline
Definition at line 998 of file TabManager.h.
References bCanDoDragOperation.
GetDefaultTabWindowSize()
FVector2D FTabManager::GetDefaultTabWindowSize (const FTabId & TabId) static protected
Returns the default window size for the TabId, or the fallback window size if it wasn't registered.
GetLocalWorkspaceMenuRoot()
const TSharedRef< FWorkspaceItem > FTabManager::GetLocalWorkspaceMenuRoot () const
Returns
The local workspace menu root
GetOnReadOnlyModeChangedDelegate()
FOnReadOnlyModeChanged & FTabManager::GetOnReadOnlyModeChangedDelegate () inline
Definition at line 992 of file TabManager.h.
References OnReadOnlyModeChanged.
GetOwnerTab()
TSharedPtr< SDockTab > FTabManager::GetOwnerTab () inline
Returns the owner tab (if it exists)
Definition at line 1030 of file TabManager.h.
References OwnerTabPtr.
GetPrivateApi()
FTabManager::FPrivateApi & FTabManager::GetPrivateApi ()
GetRecordableStats()
void FTabManager::GetRecordableStats (int32 & OutTabCount, TArray< TSharedPtr< SWindow > > & OutUniqueParentWindows) const private
Checks all dock areas and adds up the number of open tabs and unique parent windows in the manager.
GetTabPermissionList()
TSharedRef< FNamePermissionList > & FTabManager::GetTabPermissionList ()
Returns filter for additional control over available tabs.
GetTabReadOnlyBehavior()
TOptional< ETabReadOnlyBehavior > FTabManager::GetTabReadOnlyBehavior (const FTabId & TabId) const
Returns
how the given tab wants to behave in read only mode
GetUIActionForTabSpawnerMenuEntry()
FUIAction FTabManager::GetUIActionForTabSpawnerMenuEntry (TSharedPtr< FTabSpawnerEntry > InTabMenuEntry)
HasAnyMatchingTabs()
bool FTabManager::HasAnyMatchingTabs (const TSharedRef< FTabManager::FLayoutNode > & SomeNode, const TFunctionRef< bool(const FTab &)> & Matcher) static protected
HasAnyTabWithTabId()
bool FTabManager::HasAnyTabWithTabId (const TSharedRef< FTabManager::FLayoutNode > & SomeNode, const FName & InTabTypeToMatch) const private
Returns true if the given FLayoutNode contains a tab with the given FTabId.TabType.
Parameters
InTabTypeToMatch the given FTabId.TabType to look to see if this tab manager manages it
SomeNode the TSharedRef<FLayoutNode> in which to look for the tab with FTabId.TabType == InTabTypeToMatch
HasTabSpawner()
bool FTabManager::HasTabSpawner (FName TabId) const
Returns
true if the tab has a factory registered for it that allows it to be spawned.
HasTabSpawnerFor()
bool FTabManager::HasTabSpawnerFor (FName TabId) const protected
HasValidOpenTabs()
bool FTabManager::HasValidOpenTabs (const TSharedRef< FTabManager::FLayoutNode > & SomeNode) const
It searches for valid and open tabs on SomeNode.
Returns
It returns true if there is at least a valid open tab in the input SomeNode.
HasValidTabs()
bool FTabManager::HasValidTabs (const TSharedRef< FTabManager::FLayoutNode > & SomeNode) const protected
InsertDocumentTab() [1/2]
void FTabManager::InsertDocumentTab (FName PlaceholderId, const FSearchPreference & SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab, bool bPlaySpawnAnim) protected
InsertDocumentTab() [2/2]
void FTabManager::InsertDocumentTab (FName PlaceholderId, FName NewTabId, const FSearchPreference & SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab, bool bPlaySpawnAnim) protected
InsertNewDocumentTab() [1/3]
void FTabManager::InsertNewDocumentTab (FName PlaceholderId, const FSearchPreference & SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
InsertNewDocumentTab() [2/3]
void FTabManager::InsertNewDocumentTab (FName PlaceholderId, ESearchPreference::Type SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
InsertNewDocumentTab() [3/3]
void FTabManager::InsertNewDocumentTab (FName PlaceholderId, FName NewTabId, const FSearchPreference & SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab)
Insert a new UnmanagedTab document tab next to an existing tab (closed or open) that has the PlaceholdId.
Give the New tab NewTabId
InvokeTab_Internal()
TSharedPtr< SDockTab > FTabManager::InvokeTab_Internal (const FTabId & TabId, bool bInvokeAsInactive = false, bool bForceOpenWindowIfNeeded = false) protected
InvokeTabForMenu()
void FTabManager::InvokeTabForMenu (FName TabId) protected
IsAllowedTab()
bool FTabManager::IsAllowedTab (const FTabId & TabId) const protected
IsAllowedTabType()
bool FTabManager::IsAllowedTabType (const FName TabType) const protected
IsReadOnly()
bool FTabManager::IsReadOnly ()
Is this Tab Manager in Read Only mode i.e all interactions with panels are disabled.
IsTabAllowedInSidebar()
bool FTabManager::IsTabAllowedInSidebar (const FTabId TabId) const
Returns
true if a tab is ever allowed in a sidebar
IsTabCloseable()
bool FTabManager::IsTabCloseable (const TSharedRef< const SDockTab > & InTab) const
Returns
if the provided tab can be closed.
IsValidTabForSpawning()
bool FTabManager::IsValidTabForSpawning (const FTab & SomeTab) const protected
MakeSpawnerMenuEntry()
void FTabManager::MakeSpawnerMenuEntry (FMenuBuilder & PopulateMe, const TSharedPtr< FTabSpawnerEntry > & InSpawnerNode) protected
New()
TSharedRef< FTabManager > FTabManager::New (const TSharedPtr< SDockTab > & InOwnerTab, const TSharedRef< FTabSpawner > & InNomadTabSpawner) inline static protected
Definition at line 1069 of file TabManager.h.
References FTabManager(), and MakeShareable().
NewArea() [1/2]
TSharedRef< FArea > FTabManager::NewArea (const float Width, const float Height) inline static
Definition at line 836 of file TabManager.h.
References MakeShareable(), and Width.
NewArea() [2/2]
TSharedRef< FArea > FTabManager::NewArea (const FVector2D & WindowSize) inline static
Definition at line 841 of file TabManager.h.
References MakeShareable(), UE_REAL_TO_FLOAT, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
NewLayout()
TSharedRef< FLayout > FTabManager::NewLayout (const FName LayoutName) inline static
Definition at line 824 of file TabManager.h.
References MakeShareable().
NewPrimaryArea()
TSharedRef< FArea > FTabManager::NewPrimaryArea () inline static
Definition at line 829 of file TabManager.h.
References MakeShareable(), and FTabManager::FArea::Placement_NoWindow.
NewSplitter()
TSharedRef< FSplitter > FTabManager::NewSplitter () inline static
Definition at line 851 of file TabManager.h.
References MakeShareable().
NewStack()
TSharedRef< FStack > FTabManager::NewStack () inline static
Definition at line 846 of file TabManager.h.
References MakeShareable().
OnTabClosing()
virtual void FTabManager::OnTabClosing (const TSharedRef< SDockTab > & TabBeingClosed) protected virtual
Reimplemented in FGlobalTabmanager.
OnTabForegrounded()
virtual void FTabManager::OnTabForegrounded (const TSharedPtr< SDockTab > & NewForegroundTab, const TSharedPtr< SDockTab > & BackgroundedTab) protected virtual
Notify the tab manager that the NewForegroundTab was brought to front and the BackgroundedTab was send to the background as a result.
Reimplemented in FGlobalTabmanager.
OnTabManagerClosing()
virtual void FTabManager::OnTabManagerClosing () protected virtual
Invoked when a tab manager is closing down.
Reimplemented in FGlobalTabmanager.
OnTabOpening()
virtual void FTabManager::OnTabOpening (const TSharedRef< SDockTab > & TabBeingOpened) protected virtual
OnTabRelocated()
virtual void FTabManager::OnTabRelocated (const TSharedRef< SDockTab > & RelocatedTab, const TSharedPtr< SWindow > & NewOwnerWindow) protected virtual
Reimplemented in FGlobalTabmanager.
OpenUnmanagedTab()
virtual void FTabManager::OpenUnmanagedTab (FName PlaceholderId, const FSearchPreference & SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab) protected virtual
Reimplemented in FGlobalTabmanager, and FProxyTabmanager.
PersistLayout()
TSharedRef< FTabManager::FLayout > FTabManager::PersistLayout () const
Gather the persistent layout.
PopulateLocalTabSpawnerMenu()
void FTabManager::PopulateLocalTabSpawnerMenu (FMenuBuilder & PopulateMe)
PopulateTabSpawnerMenu() [1/3]
void FTabManager::PopulateTabSpawnerMenu (FMenuBuilder & PopulateMe, const FName & TabType)
PopulateTabSpawnerMenu() [2/3]
void FTabManager::PopulateTabSpawnerMenu (FMenuBuilder & PopulateMe, TSharedRef< FWorkspaceItem > MenuStructure)
PopulateTabSpawnerMenu() [3/3]
void FTabManager::PopulateTabSpawnerMenu (FMenuBuilder & PopulateMe, TSharedRef< FWorkspaceItem > MenuStructure, bool bIncludeOrphanedMenus)
PopulateTabSpawnerMenu_Helper()
void FTabManager::PopulateTabSpawnerMenu_Helper (FMenuBuilder & PopulateMe, struct FPopulateTabSpawnerMenu_Args Args) protected
RegisterDefaultTabWindowSize()
void FTabManager::RegisterDefaultTabWindowSize (const FTabId & TabName, const FVector2D DefaultSize) inline static
Definition at line 856 of file TabManager.h.
References DefaultTabWindowSizeMap.
RegisterTabSpawner()
FTabSpawnerEntry & FTabManager::RegisterTabSpawner (const FName TabId, const FOnSpawnTab & OnSpawnTab, const FCanSpawnTab & CanSpawnTab = FCanSpawnTab())
Register a new tab spawner with the tab manager.
The spawner will be called when anyone calls InvokeTab().
Parameters
TabId The TabId to register the spawner for.
OnSpawnTab The callback that will be used to spawn the tab.
CanSpawnTab The callback that will be used to ask if spawning the tab is allowed
Returns
The registration entry for the spawner.
RemoveTabFromCollapsedAreas()
void FTabManager::RemoveTabFromCollapsedAreas (const FTabMatcher & Matcher) protected
RequestSavePersistentLayout()
void FTabManager::RequestSavePersistentLayout ()
Request a deferred save of the layout.
RestoreArea()
TSharedPtr< SDockingArea > FTabManager::RestoreArea (const TSharedRef< FArea > & AreaToRestore, const TSharedPtr< SWindow > & InParentWindow, const bool bEmbedTitleAreaContent = false, const EOutputCanBeNullptr OutputCanBeNullptr = EOutputCanBeNullptr::Never, bool bForceOpenWindowIfNeeded = false) protected
References Never.
RestoreArea_Helper()
TSharedPtr< class SDockingNode > FTabManager::RestoreArea_Helper (const TSharedRef< FLayoutNode > & LayoutNode, const TSharedPtr< SWindow > & ParentWindow, const bool bEmbedTitleAreaContent, FSidebarTabLists & OutSidebarTabs, const EOutputCanBeNullptr OutputCanBeNullptr = EOutputCanBeNullptr::Never, bool bForceOpenWindowIfNeeded = false) protected
References Never.
RestoreDocumentTab()
void FTabManager::RestoreDocumentTab (FName PlaceholderId, ESearchPreference::Type SearchPreference, const TSharedRef< SDockTab > & UnmanagedTab)
Much like InsertNewDocumentTab, but the UnmanagedTab is not seen by the user as newly-created.
e.g. Opening an restores multiple previously opened documents; these are not seen as new tabs.
RestoreFrom()
TSharedPtr< SWidget > FTabManager::RestoreFrom (const TSharedRef< FLayout > & Layout, const TSharedPtr< SWindow > & ParentWindow, const bool bEmbedTitleAreaContent = false, const EOutputCanBeNullptr RestoreAreaOutputCanBeNullptr = EOutputCanBeNullptr::Never)
References Layout, and Never.
RestoreSplitterContent() [1/2]
void FTabManager::RestoreSplitterContent (const TArray< TSharedRef< class SDockingNode > > & DockingNodes, const TSharedRef< class SDockingSplitter > & SplitterWidget) protected
RestoreSplitterContent() [2/2]
void FTabManager::RestoreSplitterContent (const TSharedRef< FSplitter > & SplitterNode, const TSharedRef< class SDockingSplitter > & SplitterWidget, const TSharedPtr< SWindow > & ParentWindow, FSidebarTabLists & OutSidebarTabs) protected
Use this standalone RestoreSplitterContent when the output of its internal RestoreArea_Helper cannot be a nullptr.
SavePersistentLayout()
void FTabManager::SavePersistentLayout ()
Gather the persistent layout and execute the custom delegate for saving it to persistent storage (e.g.
into config files)
SetAllowWindowMenuBar()
void FTabManager::SetAllowWindowMenuBar (bool bInAllowWindowMenuBar)
Sets whether or not this tab manager supports a custom menu bar for the active major tab that will be shown on top of the major tab area in the window this tab manager resides in.
SetCanDoDragOperation()
void FTabManager::SetCanDoDragOperation (bool CanDoDragOperation) inline
Definition at line 995 of file TabManager.h.
References bCanDoDragOperation.
SetMainTab() [1/2]
void FTabManager::SetMainTab (const FTabId & InMainTabID)
SetMainTab() [2/2]
void FTabManager::SetMainTab (const TSharedRef< const SDockTab > & InTab)
Provide a tab that will be the main tab and cannot be closed.
Prefer using the version that takes in a TabID so you can set the MainTab before it is actually created
SetMenuMultiBox()
void FTabManager::SetMenuMultiBox (const TSharedPtr< FMultiBox > NewMenuMutliBox, const TSharedPtr< SWidget > MenuWidget)
Set the multi-box to use for generating a global menu bar.
The implementation is platform and setting specific On Mac the menu bar appears globally at the top of the desktop in all cases regardless of whether or not SetAllowWindowMenuBar is called. On other desktop platforms the menu appears at the top of the window this tab manager is a part of only if SetAllowWindowMenuBar(true) is called.
Parameters
NewMenuMutliBox The multi-box to generate the global menu bar from.
References MenuWidget.
SetOnPersistLayout()
void FTabManager::SetOnPersistLayout (const FOnPersistLayout & InHandler)
SetReadOnly()
void FTabManager::SetReadOnly (bool bInReadOnly)
SetTabsTo()
void FTabManager::SetTabsTo (const TSharedRef< FTabManager::FLayoutNode > & SomeNode, const ETabState::Type NewTabState, const ETabState::Type OriginalTabState) const protected
It sets the desired (or all) tabs in the FTabManager::FLayoutNode to the desired value.
Parameters
SomeNode The area whose tabs will be modified.
NewTabState The new TabState value.
OriginalTabState Only the tabs with this value will be modified. Use ETabState::AnyTab to modify them all.
SpawnTab()
TSharedPtr< SDockTab > FTabManager::SpawnTab (const FTabId & TabId, const TSharedPtr< SWindow > & ParentWindow, const bool bCanOutputBeNullptr = false) protected
ToggleSidebarOpenTabs()
void FTabManager::ToggleSidebarOpenTabs ()
Temporarily moves all open tabs in this tab manager to a sidebar or restores them from a temporary state.
TryInvokeTab()
virtual TSharedPtr< SDockTab > FTabManager::TryInvokeTab (const FTabId & TabId, bool bInvokeAsInactive = false) virtual
Try to open tab if it is closed at the last known location.
If it already exists, it will draw attention to the tab.
Parameters
TabId The tab identifier.
bInvokeAsInactive Leave the tab inactive instead of drawing attention to it
Returns
The existing or newly spawned tab instance if successful.
UnregisterAllTabSpawners()
void FTabManager::UnregisterAllTabSpawners ()
Unregisters all tab spawners.
UnregisterDefaultTabWindowSize()
void FTabManager::UnregisterDefaultTabWindowSize (const FTabId & TabName) inline static
Definition at line 861 of file TabManager.h.
References DefaultTabWindowSizeMap.
UnregisterTabSpawner()
bool FTabManager::UnregisterTabSpawner (const FName TabId)
Unregisters the tab spawner matching the provided TabId.
Parameters
TabId The TabId to remove the spawner for.
Returns
true if a spawner was found for this TabId, otherwise false.
UpdateMainMenu()
void FTabManager::UpdateMainMenu (TSharedPtr< SDockTab > ForTab, const bool bForce)
Update the native, global menu bar if it is being used.
Parameters
bForce Used to force an update even if the parent window doesn't contain the widget with keyboard focus.
UpdateStats()
virtual void FTabManager::UpdateStats () protected virtual
Called when tab(s) have been added or windows created.
Reimplemented in FGlobalTabmanager.
Friends And Related Symbol Documentation
FGlobalTabmanager
friend class FGlobalTabmanager friend
Definition at line 388 of file TabManager.h.
References FGlobalTabmanager.
Referenced by FGlobalTabmanager.
FPrivateApi
friend class FPrivateApi friend
Definition at line 752 of file TabManager.h.
Field Documentation
ActiveLayoutName
FName FTabManager::ActiveLayoutName protected
The name of the layout being used.
Definition at line 1217 of file TabManager.h.
bAllowPerWindowMenu
bool FTabManager::bAllowPerWindowMenu = false protected
Whether or not this tab manager puts any registered menus in the windows menu bar area.
Definition at line 1257 of file TabManager.h.
Referenced by AllowsWindowMenuBar().
bCanDoDeferredLayoutSave
bool FTabManager::bCanDoDeferredLayoutSave = true protected
Whether or not this tab manager can perform deferred layout saves at this time; used internally to disable layout saves during drag operations.
Definition at line 1254 of file TabManager.h.
bCanDoDragOperation
bool FTabManager::bCanDoDragOperation = true protected
Definition at line 1251 of file TabManager.h.
Referenced by FProxyTabmanager::FProxyTabmanager(), GetCanDoDragOperation(), and SetCanDoDragOperation().
bEnforceMainTab
bool FTabManager::bEnforceMainTab = false protected
If true, this tab manager will always have one non-closable tab.
Definition at line 1245 of file TabManager.h.
bReadOnly
bool FTabManager::bReadOnly = false protected
Whether this tab manager is in a read only mode (all tabs content disabled by default - overridable per tab)
Definition at line 1269 of file TabManager.h.
CollapsedDockAreas
TArray< TSharedRef<FTabManager::FArea> > FTabManager::CollapsedDockAreas protected
CollapsedDockAreas refers to areas that were closed (e.g., by the user).
We save its location so they can be re-opened in the same location if the user opens thems again.
Definition at line 1196 of file TabManager.h.
DefaultTabWindowSizeMap
TMap<FTabId, FVector2D> FTabManager::DefaultTabWindowSizeMap static protected
Default tab window sizes for newly-created tabs.
Definition at line 1233 of file TabManager.h.
Referenced by RegisterDefaultTabWindowSize(), and UnregisterDefaultTabWindowSize().
DockAreas
TArray< TWeakPtr<SDockingArea> > FTabManager::DockAreas protected
Definition at line 1191 of file TabManager.h.
FallbackWindowSize
const FVector2D FTabManager::FallbackWindowSize static protected
The fallback size for a window.
Definition at line 1230 of file TabManager.h.
InvalidDockAreas
TArray< TSharedRef<FTabManager::FArea> > FTabManager::InvalidDockAreas protected
InvalidDockAreas refers to areas that were not recognized by the Editor (e.g., LiveLink when its plugin its disabled).
We save its location so they can be re-opened whenever they are recognized again (e.g., if its related plugin is re-enabled).
Definition at line 1201 of file TabManager.h.
LastDocumentUID
int32 FTabManager::LastDocumentUID protected
Instance ID for document tabs.
Allows us to distinguish between different document tabs at runtime. This ID is never meant to be persisted, simply used to disambiguate between different documents, since most of thenm will have the same Tab Type (which is usually document).
Definition at line 1227 of file TabManager.h.
LastMajorDockWindow
TWeakPtr<SWindow> FTabManager::LastMajorDockWindow protected
The last window we docked a nomad or major tab into.
Definition at line 1248 of file TabManager.h.
LocalWorkspaceMenuRoot
TSharedPtr<FWorkspaceItem> FTabManager::LocalWorkspaceMenuRoot protected
The root for the local editor's tab spawner workspace menu.
Definition at line 1204 of file TabManager.h.
MainNonCloseableTabID
FTabId FTabManager::MainNonCloseableTabID protected
The ID of the main tab, which cannot be closed.
Definition at line 1239 of file TabManager.h.
MenuMultiBox
TSharedPtr<FMultiBox> FTabManager::MenuMultiBox protected
The current menu multi-box for the tab, used to construct platform native main menus.
Definition at line 1210 of file TabManager.h.
MenuWidget
TSharedPtr<SWidget> FTabManager::MenuWidget protected
Definition at line 1211 of file TabManager.h.
Referenced by SetMenuMultiBox().
NomadTabSpawner
TSharedRef<FTabSpawner> FTabManager::NomadTabSpawner protected
Definition at line 1187 of file TabManager.h.
OnPersistLayout_Handler
FOnPersistLayout FTabManager::OnPersistLayout_Handler protected
Invoked when the tab manager is about to close.
Definition at line 1220 of file TabManager.h.
OnReadOnlyModeChanged
FOnReadOnlyModeChanged FTabManager::OnReadOnlyModeChanged protected
Delegate that broadcasts when the tab manager enters/leaves read only mode.
Definition at line 1272 of file TabManager.h.
Referenced by GetOnReadOnlyModeChangedDelegate().
OwnerTabPtr
TWeakPtr<SDockTab> FTabManager::OwnerTabPtr protected
A Major tab that contains this TabManager's widgets.
Definition at line 1207 of file TabManager.h.
Referenced by GetOwnerTab().
PendingLayoutSaveHandle
FTSTicker::FDelegateHandle FTabManager::PendingLayoutSaveHandle protected
Handle to a pending layout save.
Definition at line 1260 of file TabManager.h.
PendingMainNonClosableTab
TSharedPtr<const SDockTab> FTabManager::PendingMainNonClosableTab protected
To keep track of any pending tabs that want to be the main tab, but don't have their ID set yet.
Definition at line 1242 of file TabManager.h.
PrivateApi
TSharedRef<FPrivateApi> FTabManager::PrivateApi protected
Protected private API that must only be accessed by the docking framework internals.
Definition at line 1214 of file TabManager.h.
TabPermissionList
TSharedRef<FNamePermissionList> FTabManager::TabPermissionList protected
Allow systems to dynamically hide tabs.
Definition at line 1263 of file TabManager.h.
TabSpawner
FTabSpawner FTabManager::TabSpawner protected
Definition at line 1186 of file TabManager.h.
TemporarilySidebaredTabs
TArray<TWeakPtr<SDockTab> > FTabManager::TemporarilySidebaredTabs protected
Tabs which have been temporarily put in the a sidebar.
Definition at line 1266 of file TabManager.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Docking/TabManager.h