Unreal Engine 5.6 C++ API: SInputKeySelector Class Reference
SInputKeySelector Class Reference
A widget for selecting keys or input chords.
#include "SInputKeySelector.h"
Public Member Functions
DECLARE_DELEGATE_OneParam (FOnKeySelected, const FInputChord &) DECLARE_DELEGATE(FOnIsSelectingKeyChanged) SLATE_BEGIN_ARGS(SInputKeySelector)
bool GetIsSelectingKey () const
Returns true whenever key selection mode is active, otherwise returns false.
FInputChord GetSelectedKey () const
Gets the currently selected key chord.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent) override
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Just like OnMouseButtonDown, but tunnels instead of bubbling.
void SetAllowGamepadKeys (const bool bInAllowGamepadKeys)
When true gamepad keys are captured in the selected key chord, otherwise they are ignored.
void SetAllowModifierKeys (const bool bInAllowModifierKeys)
When true modifier keys are captured in the selected key chord, otherwise they are ignored.
void SetButtonStyle (const FButtonStyle *ButtonStyle)
Sets the style of the button which is used enter key selection mode.
void SetEscapeKeys (TArray< FKey > InEscapeKeys)
Sets the escape keys to check against.
void SetKeySelectionText (FText InKeySelectionText)
Sets the text which is displayed when selecting a key.
void SetMargin (TAttribute< FMargin > InMargin)
Sets the margin around the text used to display the currently selected key.
void SetNoKeySpecifiedText (FText InNoKeySpecifiedText)
Sets the text to display when no key text is available or not selecting a key.
void SetSelectedKey (TAttribute< FInputChord > InSelectedKey)
Sets the currently selected key chord.
void SetTextBlockVisibility (EVisibility InVisibility)
Sets the visibility of the text block.
void SetTextStyle (const FTextBlockStyle *InTextStyle)
Sets the style of the text on the button which is used enter key selection mode.
Font ButtonStyle KeySelectionText AllowModifierKeys SLATE_ARGUMENT (bool, AllowGamepadKeys) SLATE_ARGUMENT(bool
When true gamepad keys are captured in the selected key chord, otherwise they are ignored.
Font ButtonStyle KeySelectionText SLATE_ARGUMENT (FText, NoKeySpecifiedText) SLATE_ARGUMENT(bool
The text to display while no key text is available or not selecting a key.
Font ButtonStyle KeySelectionText AllowModifierKeys EscapeCancelsSelection SLATE_ARGUMENT (TArray< FKey >, EscapeKeys) SLATE_EVENT(FOnKeySelected
When EscapeCancelsSelection is true, escape on specific keys that are unbind able by the user.
SLATE_ATTRIBUTE (FInputChord, SelectedKey) SLATE_ATTRIBUTE(FSlateFontInfo
The currently selected key.
Font SLATE_ATTRIBUTE (FMargin, Margin) SLATE_STYLE_ARGUMENT(FButtonStyle
The margin around the selected key text.
Font ButtonStyle KeySelectionText AllowModifierKeys EscapeCancelsSelection OnKeySelected IsFocusable SLATE_END_ARGS () 1 void Construct(const FArguments &InArgs)
Font ButtonStyle KeySelectionText AllowModifierKeys EscapeCancelsSelection OnKeySelected SLATE_EVENT (FOnIsSelectingKeyChanged, OnIsSelectingKeyChanged) SLATE_ARGUMENT(bool
Occurs whenever key selection mode starts and stops.
Font ButtonStyle SLATE_STYLE_ARGUMENT (FTextBlockStyle, TextStyle) SLATE_ARGUMENT(FText
The text style of the button text.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Member Functions
FMargin GetMargin () const
Gets the margin around the text used to display the currently selected key.
FText GetSelectedKeyText () const
Gets the display text for the currently selected key.
bool IsEscapeKey (const FKey &InKey) const
Returns true, if the key has been specified as an escape key, else false.
FReply OnClicked ()
Handles the OnClicked event from the button which enables key selection mode.
void SelectKey (FKey Key, bool bShiftDown, bool bControllDown, bool bAltDown, bool bCommandDown)
Sets the currently selected key and invokes the associated events.
void SetIsSelectingKey (bool bInIsSelectingKey)
Sets bIsSelectingKey and invokes the associated events.
Private Attributes
bool bAllowGamepadKeys
When true gamepad keys are recorded on the selected key chord, otherwise they are ignored.
bool bAllowModifierKeys
When true modifier keys are recorded on the selected key chord, otherwise they are ignored.
bool bEscapeCancelsSelection
When true, pressing escape will cancel the key selection, when false, pressing escape will select the escape key.
bool bIsFocusable
Can this button be focused?
bool bIsSelectingKey
True when key selection mode is active.
TSharedPtr< SButton > Button
The button which starts the key selection mode.
TArray< FKey > EscapeKeys
When EscapeCancelsSelection is true, escape on specific keys that are unbind able by the user.
FText KeySelectionText
The text to display when selecting keys.
TAttribute< FMargin > Margin
The margin around the text used to display the currently selected key.
FText NoKeySpecifiedText
The text to display while no key text is available or not selecting a key.
FOnIsSelectingKeyChanged OnIsSelectingKeyChanged
Delegate which is run when key selection mode starts and stops.
FOnKeySelected OnKeySelected
Delegate which is run any time a new key is selected.
TAttribute< FInputChord > SelectedKey
The currently selected key chord.
TSharedPtr< STextBlock > TextBlock
The text which is rendered on the button.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
A widget for selecting keys or input chords.
Definition at line 26 of file SInputKeySelector.h.
Member Function Documentation
DECLARE_DELEGATE_OneParam()
SInputKeySelector::DECLARE_DELEGATE_OneParam (FOnKeySelected , const FInputChord &) inline
Definition at line 29 of file SInputKeySelector.h.
References Invalid, and NSLOCTEXT.
GetIsSelectingKey()
bool SInputKeySelector::GetIsSelectingKey () const inline
Returns true whenever key selection mode is active, otherwise returns false.
Definition at line 122 of file SInputKeySelector.h.
References bIsSelectingKey.
GetMargin()
FMargin SInputKeySelector::GetMargin () const private
Gets the margin around the text used to display the currently selected key.
GetSelectedKey()
FInputChord SInputKeySelector::GetSelectedKey () const
Gets the currently selected key chord.
References GetSelectedKey().
Referenced by GetSelectedKey().
GetSelectedKeyText()
FText SInputKeySelector::GetSelectedKeyText () const private
Gets the display text for the currently selected key.
IsEscapeKey()
bool SInputKeySelector::IsEscapeKey (const FKey & InKey) const private
Returns true, if the key has been specified as an escape key, else false.
OnClicked()
FReply SInputKeySelector::OnClicked () private
Handles the OnClicked event from the button which enables key selection mode.
OnFocusLost()
virtual void SInputKeySelector::OnFocusLost (const FFocusEvent & InFocusEvent) override virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented from SWidget.
OnKeyDown()
virtual FReply SInputKeySelector::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyUp()
virtual FReply SInputKeySelector::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseButtonDown()
virtual FReply SInputKeySelector::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
OnNavigation()
virtual FNavigationReply SInputKeySelector::OnNavigation (const FGeometry & MyGeometry, const FNavigationEvent & InNavigationEvent) override virtual
Called when navigation is requested e.g.
Left Joystick, Direction Pad, Arrow Keys can generate navigation events.
Parameters
InNavigationEvent The navigation event generated
Reimplemented from SWidget.
OnPreviewKeyDown()
virtual FReply SInputKeySelector::OnPreviewKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
This event is primarily to allow parent widgets to consume an event before a child widget processes it and it should be used only when there is no better design alternative.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnPreviewMouseButtonDown()
virtual FReply SInputKeySelector::OnPreviewMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Just like OnMouseButtonDown, but tunnels instead of bubbling.
If this event is handled, OnMouseButtonDown will not be sent.
Use this event sparingly as preview events generally make UIs more difficult to reason about.
Reimplemented from SWidget.
References MouseEvent.
SelectKey()
void SInputKeySelector::SelectKey (FKey Key, bool bShiftDown, bool bControllDown, bool bAltDown, bool bCommandDown) private
Sets the currently selected key and invokes the associated events.
References Key.
SetAllowGamepadKeys()
void SInputKeySelector::SetAllowGamepadKeys (const bool bInAllowGamepadKeys) inline
When true gamepad keys are captured in the selected key chord, otherwise they are ignored.
Definition at line 116 of file SInputKeySelector.h.
References bAllowGamepadKeys.
SetAllowModifierKeys()
void SInputKeySelector::SetAllowModifierKeys (const bool bInAllowModifierKeys) inline
When true modifier keys are captured in the selected key chord, otherwise they are ignored.
Definition at line 113 of file SInputKeySelector.h.
References bAllowModifierKeys.
SetButtonStyle()
void SInputKeySelector::SetButtonStyle (const FButtonStyle * ButtonStyle)
Sets the style of the button which is used enter key selection mode.
References SetButtonStyle().
Referenced by SetButtonStyle().
SetEscapeKeys()
void SInputKeySelector::SetEscapeKeys (TArray< FKey > InEscapeKeys) inline
Sets the escape keys to check against.
Definition at line 119 of file SInputKeySelector.h.
References EscapeKeys, and MoveTemp().
SetIsSelectingKey()
void SInputKeySelector::SetIsSelectingKey (bool bInIsSelectingKey) private
Sets bIsSelectingKey and invokes the associated events.
SetKeySelectionText()
void SInputKeySelector::SetKeySelectionText (FText InKeySelectionText) inline
Sets the text which is displayed when selecting a key.
Definition at line 107 of file SInputKeySelector.h.
References KeySelectionText, MoveTemp(), and SetKeySelectionText().
Referenced by SetKeySelectionText().
SetMargin()
void SInputKeySelector::SetMargin (TAttribute< FMargin > InMargin)
Sets the margin around the text used to display the currently selected key.
References SetMargin().
Referenced by SetMargin().
SetNoKeySpecifiedText()
void SInputKeySelector::SetNoKeySpecifiedText (FText InNoKeySpecifiedText) inline
Sets the text to display when no key text is available or not selecting a key.
Definition at line 110 of file SInputKeySelector.h.
References MoveTemp(), and NoKeySpecifiedText.
SetSelectedKey()
void SInputKeySelector::SetSelectedKey (TAttribute< FInputChord > InSelectedKey)
Sets the currently selected key chord.
References SetSelectedKey().
Referenced by SetSelectedKey().
SetTextBlockVisibility()
void SInputKeySelector::SetTextBlockVisibility (EVisibility InVisibility)
Sets the visibility of the text block.
SetTextStyle()
void SInputKeySelector::SetTextStyle (const FTextBlockStyle * InTextStyle)
Sets the style of the text on the button which is used enter key selection mode.
References SetTextStyle().
Referenced by SetTextStyle().
SLATE_ARGUMENT() [1/3]
Font ButtonStyle KeySelectionText AllowModifierKeys SInputKeySelector::SLATE_ARGUMENT (bool , AllowGamepadKeys)
When true gamepad keys are captured in the selected key chord, otherwise they are ignored.
When true, pressing escape will cancel the key selection, when false, pressing escape will select the escape key.
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [2/3]
Font ButtonStyle KeySelectionText SInputKeySelector::SLATE_ARGUMENT (FText , NoKeySpecifiedText)
The text to display while no key text is available or not selecting a key.
When true modifier keys are captured in the selected key chord, otherwise they are ignored.
References NoKeySpecifiedText, and SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_EVENT(), and SLATE_STYLE_ARGUMENT().
SLATE_ARGUMENT() [3/3]
Font ButtonStyle KeySelectionText AllowModifierKeys EscapeCancelsSelection SInputKeySelector::SLATE_ARGUMENT (TArray< FKey > , EscapeKeys)
When EscapeCancelsSelection is true, escape on specific keys that are unbind able by the user.
Occurs whenever a new key is selected.
References EscapeKeys, OnKeySelected, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [1/2]
SInputKeySelector::SLATE_ATTRIBUTE (FInputChord , SelectedKey)
The currently selected key.
The font used to display the currently selected key.
References SelectedKey.
Referenced by SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/2]
Font SInputKeySelector::SLATE_ATTRIBUTE (FMargin , Margin)
The margin around the selected key text.
The style of the button used to enable key selection.
References Margin, SLATE_ATTRIBUTE(), and SLATE_STYLE_ARGUMENT().
SLATE_END_ARGS()
Font ButtonStyle KeySelectionText AllowModifierKeys EscapeCancelsSelection OnKeySelected IsFocusable SInputKeySelector::SLATE_END_ARGS () const &
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
SLATE_EVENT()
Font ButtonStyle KeySelectionText AllowModifierKeys EscapeCancelsSelection OnKeySelected SInputKeySelector::SLATE_EVENT (FOnIsSelectingKeyChanged , OnIsSelectingKeyChanged)
Occurs whenever key selection mode starts and stops.
Sometimes a button should only be mouse-clickable and never keyboard focusable.
References OnIsSelectingKeyChanged, SLATE_ARGUMENT(), and SLATE_EVENT().
Referenced by SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_STYLE_ARGUMENT()
Font ButtonStyle SInputKeySelector::SLATE_STYLE_ARGUMENT (FTextBlockStyle , TextStyle)
The text style of the button text.
The text to display while selecting a new key.
References KeySelectionText, SLATE_ARGUMENT(), and SLATE_STYLE_ARGUMENT().
Referenced by SLATE_ATTRIBUTE(), and SLATE_STYLE_ARGUMENT().
SupportsKeyboardFocus()
virtual bool SInputKeySelector::SupportsKeyboardFocus () const inline override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Definition at line 136 of file SInputKeySelector.h.
Field Documentation
bAllowGamepadKeys
bool SInputKeySelector::bAllowGamepadKeys private
When true gamepad keys are recorded on the selected key chord, otherwise they are ignored.
Definition at line 179 of file SInputKeySelector.h.
Referenced by SetAllowGamepadKeys().
bAllowModifierKeys
bool SInputKeySelector::bAllowModifierKeys private
When true modifier keys are recorded on the selected key chord, otherwise they are ignored.
Definition at line 176 of file SInputKeySelector.h.
Referenced by SetAllowModifierKeys().
bEscapeCancelsSelection
bool SInputKeySelector::bEscapeCancelsSelection private
When true, pressing escape will cancel the key selection, when false, pressing escape will select the escape key.
Definition at line 182 of file SInputKeySelector.h.
bIsFocusable
bool SInputKeySelector::bIsFocusable private
Can this button be focused?
Definition at line 200 of file SInputKeySelector.h.
bIsSelectingKey
bool SInputKeySelector::bIsSelectingKey private
True when key selection mode is active.
Definition at line 161 of file SInputKeySelector.h.
Referenced by GetIsSelectingKey().
Button
TSharedPtr<SButton> SInputKeySelector::Button private
The button which starts the key selection mode.
Definition at line 194 of file SInputKeySelector.h.
EscapeKeys
TArray<FKey> SInputKeySelector::EscapeKeys private
When EscapeCancelsSelection is true, escape on specific keys that are unbind able by the user.
Definition at line 185 of file SInputKeySelector.h.
Referenced by SetEscapeKeys(), and SLATE_ARGUMENT().
KeySelectionText
FText SInputKeySelector::KeySelectionText private
The text to display when selecting keys.
Definition at line 170 of file SInputKeySelector.h.
Referenced by SetKeySelectionText(), and SLATE_STYLE_ARGUMENT().
Margin
TAttribute<FMargin> SInputKeySelector::Margin private
The margin around the text used to display the currently selected key.
Definition at line 167 of file SInputKeySelector.h.
Referenced by SLATE_ATTRIBUTE().
NoKeySpecifiedText
FText SInputKeySelector::NoKeySpecifiedText private
The text to display while no key text is available or not selecting a key.
Definition at line 173 of file SInputKeySelector.h.
Referenced by SetNoKeySpecifiedText(), and SLATE_ARGUMENT().
OnIsSelectingKeyChanged
FOnIsSelectingKeyChanged SInputKeySelector::OnIsSelectingKeyChanged private
Delegate which is run when key selection mode starts and stops.
Definition at line 191 of file SInputKeySelector.h.
Referenced by SLATE_EVENT().
OnKeySelected
FOnKeySelected SInputKeySelector::OnKeySelected private
Delegate which is run any time a new key is selected.
Definition at line 188 of file SInputKeySelector.h.
Referenced by SLATE_ARGUMENT().
SelectedKey
TAttribute<FInputChord> SInputKeySelector::SelectedKey private
The currently selected key chord.
Definition at line 164 of file SInputKeySelector.h.
Referenced by SLATE_ATTRIBUTE().
TextBlock
TSharedPtr<STextBlock> SInputKeySelector::TextBlock private
The text which is rendered on the button.
Definition at line 197 of file SInputKeySelector.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SInputKeySelector.h