Unreal Engine 5.6 C++ API: UE::Geometry::TMeshSurfaceUVSampler< SampleType > Class Template Reference
UE::Geometry::TMeshSurfaceUVSampler< SampleType > Class Template Reference
Consider using FMeshSurfaceUVSampler instead, it is more flexible and easier to understand!
#include "MeshSurfaceSampler.h"
Public Member Functions
virtual bool CachedSampleUV (const FMeshUVSampleInfo &CachedSampleInfo, SampleType &ResultOut)
Compute a sample at the given UV/3D location specified by CachedSampleInfo, which presumably was produced by previous calls to SampleUV()
virtual void Initialize (const FDynamicMesh3 *MeshIn, const FDynamicMeshUVOverlay *UVOverlayIn, EMeshSurfaceSamplerQueryType QueryTypeIn, SampleType ZeroValueIn, TUniqueFunction< void(const FMeshUVSampleInfo &SampleInfo, SampleType &SampleValueOut)> SampleValueFunctionIn)
Configure the sampler.
virtual bool SampleUV (const FVector2d &UV, SampleType &ResultOut)
Compute a sample at the given UV location.
virtual bool SampleUV (int32 UVTriangleID, const FVector2d &UV, SampleType &ResultOut)
Compute a sample at the given UV location in the given Triangle.
Public Member Functions inherited from UE::Geometry::FMeshSurfaceUVSamplerFixLayout
virtual ~FMeshSurfaceUVSamplerFixLayout ()=default
Protected Member Functions
void InitializeBVTree ()
Protected Attributes
bool bUVSpatialValid = false
const FDynamicMesh3 * Mesh = nullptr
EMeshSurfaceSamplerQueryType QueryType = EMeshSurfaceSamplerQueryType::TriangleAndUV
TMeshAABBTree3< FDynamicMeshUVMesh > UVBVTree
FDynamicMeshUVMesh UVMeshAdapter
const FDynamicMeshUVOverlay * UVOverlay = nullptr
TUniqueFunction< void(const FMeshUVSampleInfo &SampleInfo, SampleType &SampleValueOut)> ValueFunction
SampleType ZeroValue
Detailed Description
template<typename SampleType>
class UE::Geometry::TMeshSurfaceUVSampler< SampleType >
Consider using FMeshSurfaceUVSampler instead, it is more flexible and easier to understand!
TMeshSurfaceUVSampler computes point samples of the given SampleType at positions on the mesh based on UV-space positions. The standard use case for this class is to compute samples used in building Normal Maps, AO Maps, etc.
Note that for UVOnly sample type, an internal UV-space BVTree will be constructed, and each sample will query that to find the UV/3D correspondence. If you already know the TriangleID, you can use the TriangleAndUV type to avoid the BVTree construction and queries.
Note that if you need to sample multiple things, rather than building up an uber-SampleType, you can first compute a sample with SampleType=FMeshUVSampleInfo to find the correspondence information, and then construction additional samplers of type EMeshSurfaceSamplerQueryType::TriangleAndUV, and call CachedSampleUV(), to avoid expensive BVTree constructions and UV-to-3D recalculation.
Definition at line 189 of file MeshSurfaceSampler.h.
Member Function Documentation
CachedSampleUV()
template<typename SampleType> bool UE::Geometry::TMeshSurfaceUVSampler< SampleType >::CachedSampleUV (const FMeshUVSampleInfo & CachedSampleInfo, SampleType & ResultOut) virtual
Compute a sample at the given UV/3D location specified by CachedSampleInfo, which presumably was produced by previous calls to SampleUV()
Returns
true if valid sample was computed
Definition at line 328 of file MeshSurfaceSampler.h.
References ValueFunction.
Initialize()
template<typename SampleType> virtual void UE::Geometry::TMeshSurfaceUVSampler< SampleType >::Initialize (const FDynamicMesh3 * MeshIn, const FDynamicMeshUVOverlay * UVOverlayIn, EMeshSurfaceSamplerQueryType QueryTypeIn, SampleType ZeroValueIn, TUniqueFunction< void(const FMeshUVSampleInfo &SampleInfo, SampleType &SampleValueOut)> SampleValueFunctionIn) inline virtual
Configure the sampler.
Parameters
MeshIn mesh to sample
UVOverlayIn UV overlay of MeshIn to sample
QueryTypeIn type of query functions we will call. Some queries are simpler and do not require spatial data structures.
ZeroValueIn the value that is returned if a sample cannot be found
SampleValueFunctionIn This function is called to compute the sample at a given UV location. SampleInfo provides the necessary UV/3D correspondence data.
Definition at line 201 of file MeshSurfaceSampler.h.
References InitializeBVTree(), Mesh, MoveTemp(), QueryType, UE::Geometry::UVOnly, UVOverlay, ValueFunction, and ZeroValue.
InitializeBVTree()
template<typename SampleType> void UE::Geometry::TMeshSurfaceUVSampler< SampleType >::InitializeBVTree () protected
Definition at line 258 of file MeshSurfaceSampler.h.
References bUVSpatialValid, check, Mesh, UVBVTree, UVMeshAdapter, and UVOverlay.
Referenced by Initialize().
SampleUV() [1/2]
template<typename SampleType> bool UE::Geometry::TMeshSurfaceUVSampler< SampleType >::SampleUV (const FVector2d & UV, SampleType & ResultOut) virtual
Compute a sample at the given UV location.
Returns
true if valid sample was computed
Definition at line 277 of file MeshSurfaceSampler.h.
References bUVSpatialValid, check, QueryType, SampleUV(), UE::Math::TVector< double >::UnitZ(), UV, UVBVTree, and UE::Geometry::UVOnly.
Referenced by SampleUV().
SampleUV() [2/2]
template<typename SampleType> bool UE::Geometry::TMeshSurfaceUVSampler< SampleType >::SampleUV (int32 UVTriangleID, const FVector2d & UV, SampleType & ResultOut) virtual
Compute a sample at the given UV location in the given Triangle.
Returns
true if valid sample was computed
Definition at line 292 of file MeshSurfaceSampler.h.
References UE::Geometry::FIndex3i::A, UE::Geometry::FIndex3i::B, UE::Geometry::FMeshUVSampleInfo::BaryCoords, UE::Geometry::FIndex3i::C, check, UE::Geometry::TTriangle2< RealType >::GetBarycentricCoords(), Mesh, UE::Geometry::FMeshUVSampleInfo::MeshVertices, QueryType, UE::Geometry::FMeshUVSampleInfo::SurfacePoint, UE::Geometry::FMeshUVSampleInfo::Triangle3D, UE::Geometry::TriangleAndUV, UE::Geometry::FMeshUVSampleInfo::TriangleIndex, UE::Geometry::FMeshUVSampleInfo::TriangleUV, UV, UVOverlay, UE::Geometry::FMeshUVSampleInfo::UVVertices, ValueFunction, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, UE::Math::TVector< T >::Z, and ZeroValue.
Field Documentation
bUVSpatialValid
template<typename SampleType> bool UE::Geometry::TMeshSurfaceUVSampler< SampleType >::bUVSpatialValid = false protected
Definition at line 241 of file MeshSurfaceSampler.h.
Referenced by InitializeBVTree(), and SampleUV().
Mesh
template<typename SampleType> const FDynamicMesh3* UE::Geometry::TMeshSurfaceUVSampler< SampleType >::Mesh = nullptr protected
Definition at line 242 of file MeshSurfaceSampler.h.
Referenced by Initialize(), InitializeBVTree(), and SampleUV().
QueryType
template<typename SampleType> EMeshSurfaceSamplerQueryType UE::Geometry::TMeshSurfaceUVSampler< SampleType >::QueryType = EMeshSurfaceSamplerQueryType::TriangleAndUV protected
Definition at line 240 of file MeshSurfaceSampler.h.
Referenced by Initialize(), SampleUV(), and SampleUV().
UVBVTree
template<typename SampleType> TMeshAABBTree3<FDynamicMeshUVMesh> UE::Geometry::TMeshSurfaceUVSampler< SampleType >::UVBVTree protected
Definition at line 251 of file MeshSurfaceSampler.h.
Referenced by InitializeBVTree(), and SampleUV().
UVMeshAdapter
template<typename SampleType> FDynamicMeshUVMesh UE::Geometry::TMeshSurfaceUVSampler< SampleType >::UVMeshAdapter protected
Definition at line 250 of file MeshSurfaceSampler.h.
Referenced by InitializeBVTree().
UVOverlay
template<typename SampleType> const FDynamicMeshUVOverlay* UE::Geometry::TMeshSurfaceUVSampler< SampleType >::UVOverlay = nullptr protected
Definition at line 243 of file MeshSurfaceSampler.h.
Referenced by Initialize(), InitializeBVTree(), and SampleUV().
ValueFunction
template<typename SampleType> TUniqueFunction<void(const FMeshUVSampleInfo& SampleInfo, SampleType& SampleValueOut)> UE::Geometry::TMeshSurfaceUVSampler< SampleType >::ValueFunction protected
Definition at line 245 of file MeshSurfaceSampler.h.
Referenced by CachedSampleUV(), Initialize(), and SampleUV().
ZeroValue
template<typename SampleType> SampleType UE::Geometry::TMeshSurfaceUVSampler< SampleType >::ZeroValue protected
Definition at line 247 of file MeshSurfaceSampler.h.
Referenced by Initialize(), and SampleUV().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Sampling/MeshSurfaceSampler.h