Unreal Engine 5.6 C++ API: TMeshElementContainer< ElementIDType > Class Template Reference
TMeshElementContainer< ElementIDType > Class Template Reference
Templated specialization for type-safety.
#include "MeshElementContainer.h"
Data Structures
class TElementIDs
This is a special type of iterator which returns successive IDs of valid elements, rather than the elements themselves.
Public Member Functions
ElementIDType Add ()
Add a new element at the next available index, and return the new ID.
FORCEINLINE TAttributesSet< ElementIDType > & GetAttributes ()
Accessor for attributes.
FORCEINLINE const TAttributesSet< ElementIDType > & GetAttributes () const
TElementIDs FORCEINLINE GetElementIDs () const
Return iterable proxy object from container.
ElementIDType GetFirstValidID () const
Returns the first valid ID.
void Insert (const ElementIDType Index)
Inserts a new element with the given index.
bool IsValid (const ElementIDType Index) const
Returns whether the given ID is valid or not.
void Remove (const ElementIDType Index)
Removes the element with the given ID.
Public Member Functions inherited from FMeshElementContainer
FMeshElementContainer ()=default
FMeshElementContainer (const FMeshElementContainer &)=default
FMeshElementContainer (FMeshElementContainer &&Other)
Move constructor which ensures that NumHoles is set correctly in the moved object.
int32 Add ()
Add a new element at the next available index, and return the new ID.
MESHDESCRIPTION_API void Compact (TSparseArray< int32 > &OutIndexRemap)
Compacts elements and returns a remapping table.
int32 GetArraySize () const
Returns the index after the last valid element.
FORCEINLINE FAttributesSetBase & GetAttributes ()
Accessor for attributes.
FORCEINLINE const FAttributesSetBase & GetAttributes () const
FElementIDs FORCEINLINE GetElementIDs () const
Return iterable proxy object from container.
int32 GetFirstValidID () const
Returns the first valid ID.
void Insert (const int32 Index)
Inserts a new element with the given index.
bool IsValid (const int32 Index) const
Returns whether the given ID is valid or not.
int32 Num () const
Returns the number of elements in the container.
FMeshElementContainer & operator= (const FMeshElementContainer &)=default
FMeshElementContainer & operator= (FMeshElementContainer &&Other)
Move assignment operator which ensures that NumHoles is set correctly in the moved object.
MESHDESCRIPTION_API void Remap (const TSparseArray< int32 > &IndexRemap)
Remaps elements according to the passed remapping table.
void Remove (const int32 Index)
Removes the element with the given ID.
void Reserve (const int32 Elements)
Reserves space for the specified total number of elements.
void Reset (const int32 Elements=0)
Resets the container, optionally reserving space for elements to be added.
Friends
FArchive & operator<< (FArchive &Ar, TMeshElementContainer &Container)
Serializer.
Additional Inherited Members
Protected Attributes inherited from FMeshElementContainer
FAttributesSetBase Attributes
Attributes associated with this element container.
TBitArray BitArray
A bit array of all indices currently in use.
int32 NumHoles = 0
A count of the number of unused indices in the bit array.
Detailed Description
template<typename ElementIDType>
class TMeshElementContainer< ElementIDType >
Templated specialization for type-safety.
Definition at line 245 of file MeshElementContainer.h.
Member Function Documentation
Add()
template<typename ElementIDType> ElementIDType TMeshElementContainer< ElementIDType >::Add () inline
Add a new element at the next available index, and return the new ID.
Definition at line 249 of file MeshElementContainer.h.
GetAttributes() [1/2]
template<typename ElementIDType> FORCEINLINE TAttributesSet< ElementIDType > & TMeshElementContainer< ElementIDType >::GetAttributes () inline
Accessor for attributes.
Definition at line 279 of file MeshElementContainer.h.
Referenced by FMeshDescription::EdgeAttributes(), FMeshDescription::EdgeAttributes(), FMeshDescription::PolygonAttributes(), FMeshDescription::PolygonAttributes(), FMeshDescription::PolygonGroupAttributes(), FMeshDescription::PolygonGroupAttributes(), FMeshDescription::TriangleAttributes(), FMeshDescription::TriangleAttributes(), FMeshDescription::UVAttributes(), FMeshDescription::UVAttributes(), FMeshDescription::VertexAttributes(), FMeshDescription::VertexAttributes(), FMeshDescription::VertexInstanceAttributes(), and FMeshDescription::VertexInstanceAttributes().
GetAttributes() [2/2]
template<typename ElementIDType> FORCEINLINE const TAttributesSet< ElementIDType > & TMeshElementContainer< ElementIDType >::GetAttributes () const inline
Definition at line 280 of file MeshElementContainer.h.
GetElementIDs()
template<typename ElementIDType> TElementIDs FORCEINLINE TMeshElementContainer< ElementIDType >::GetElementIDs () const inline
Return iterable proxy object from container.
Definition at line 359 of file MeshElementContainer.h.
GetFirstValidID()
template<typename ElementIDType> ElementIDType TMeshElementContainer< ElementIDType >::GetFirstValidID () const inline
Returns the first valid ID.
Definition at line 267 of file MeshElementContainer.h.
Insert()
template<typename ElementIDType> void TMeshElementContainer< ElementIDType >::Insert (const ElementIDType Index) inline
Inserts a new element with the given index.
Definition at line 255 of file MeshElementContainer.h.
IsValid()
template<typename ElementIDType> bool TMeshElementContainer< ElementIDType >::IsValid (const ElementIDType Index) const inline
Returns whether the given ID is valid or not.
Definition at line 273 of file MeshElementContainer.h.
Remove()
template<typename ElementIDType> void TMeshElementContainer< ElementIDType >::Remove (const ElementIDType Index) inline
Removes the element with the given ID.
Definition at line 261 of file MeshElementContainer.h.
Friends And Related Symbol Documentation
operator<<
template<typename ElementIDType> FArchive & operator<< (FArchive & Ar, TMeshElementContainer< ElementIDType > & Container) friend
Serializer.
Definition at line 283 of file MeshElementContainer.h.
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/MeshElementContainer.h