Unreal Engine 5.6 C++ API: FWidgetPath Class Reference
FWidgetPath Class Reference
A widget path is a vertical slice through the tree.
#include "WidgetPath.h"
Public Member Functions
FWidgetPath ()
FWidgetPath (TArrayView< FWidgetAndPointer > InWidgetsAndPointers)
FWidgetPath (TSharedPtr< SWindow > InTopLevelWindow, const FArrangedChildren &InWidgetPath)
bool ContainsWidget (const SWidget *WidgetToFind) const
template<typename MatcherType>
bool ExtendPathTo (const MatcherType &Matcher, EVisibility VisibilityFilter=EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose=EWidgetPathSearchPurpose::Standard)
Extend the current path such that it reaches some widget that qualifies as a Match The widget to match must be a descendant of the last widget currently in the path.
TOptional< FArrangedWidget > FindArrangedWidget (TSharedRef< const SWidget > WidgetToFind) const
TOptional< FWidgetAndPointer > FindArrangedWidgetAndCursor (TSharedRef< const SWidget > WidgetToFind) const
template<typename MatcherType>
FArrangedChildren GeneratePathToWidget (const MatcherType &Matcher, const FArrangedWidget &FromWidget, EUINavigation NavigationType=EUINavigation::Next, EVisibility VisibilityFilter=EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose=EWidgetPathSearchPurpose::Standard)
Generate a path from FromWidget to WidgetToFind.
TSharedRef< SWindow > GetDeepestWindow () const
Get the deepest (bottom-most) window in this path; assumes path is valid.
TSharedRef< SWidget > GetLastWidget () const
Get the last (leaf-most) widget in this path; assumes path is valid.
FWidgetPath GetPathDownTo (TSharedRef< const SWidget > MarkerWidget) const
TOptional< FVirtualPointerPosition > GetVirtualPointerPosition (int32 Index) const
Get the virtual representation of the mouse at each level in the widget path.
TSharedRef< SWindow > GetWindow () const
Get the first (top-most) widget in this path, which is always a window; assumes path is valid.
bool IsValid () const
A valid path has at least one widget in it.
bool MoveFocus (int32 PathLevel, EUINavigation NavigationType, bool bSearchFromPathWidget=true)
Move focus either forward on backward in the path level specified by PathLevel.
FString ToString () const
Builds a string representation of the widget path.
Data Fields
TSharedPtr< SWindow > TopLevelWindow
The top level window of this widget path.
FArrangedChildren Widgets
The widgets that make up the widget path, the first item is the root widget, the end is the widget this path was built for.
Static Private Member Functions
template<typename MatchRuleType>
static bool SearchForWidgetRecursively (const MatchRuleType &MatchRule, const FArrangedWidget &InCandidate, FArrangedChildren &OutReversedPath, EVisibility VisibilityFilter=EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose=EWidgetPathSearchPurpose::Standard)
Utility function to search recursively through a widget hierarchy for a specific widget.
template<typename MatchRuleType>
static bool SearchForWidgetRecursively_Reverse (const MatchRuleType &MatchRule, const FArrangedWidget &InCandidate, FArrangedChildren &OutReversedPath, EVisibility VisibilityFilter=EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose=EWidgetPathSearchPurpose::Standard)
Identical to SearchForWidgetRecursively, but iterates in reverse order.
Private Attributes
TArray< TOptional< FVirtualPointerPosition > > VirtualPointerPositions
The virtual representation of the mouse at each level in the widget path.
Detailed Description
A widget path is a vertical slice through the tree.
The canonical form for widget paths is "leafmost last". The top-level window always resides at index 0. A widget path also contains a reference to a top-level SWindow that contains all the widgets in the path. The window is needed for its ability to determine its own geometry, from which the geometries of the rest of the widget can be determined.
Definition at line 50 of file WidgetPath.h.
Constructor & Destructor Documentation
FWidgetPath() [1/3]
FWidgetPath::FWidgetPath ()
Referenced by GetPathDownTo().
FWidgetPath() [2/3]
FWidgetPath::FWidgetPath (TSharedPtr< SWindow > InTopLevelWindow, const FArrangedChildren & InWidgetPath)
FWidgetPath() [3/3]
FWidgetPath::FWidgetPath (TArrayView< FWidgetAndPointer > InWidgetsAndPointers)
Member Function Documentation
ContainsWidget()
bool FWidgetPath::ContainsWidget (const SWidget * WidgetToFind) const
Returns
true if the WidgetToFind is in this WidgetPath, false otherwise.
ExtendPathTo()
template<typename MatcherType> bool FWidgetPath::ExtendPathTo (const MatcherType & Matcher, EVisibility VisibilityFilter = EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose = EWidgetPathSearchPurpose::Standard) inline
Extend the current path such that it reaches some widget that qualifies as a Match The widget to match must be a descendant of the last widget currently in the path.
Parameters
Matcher Some struct that has a "bool IsMatch(const TSharedRef<const SWidget>& InWidget) const" method
VisibilityFilter Widgets must have this type of visibility to be included the path
SearchPurpose What is the purpose for extending the path
Returns
true if successful; false otherwise.
Definition at line 112 of file WidgetPath.h.
References GeneratePathToWidget(), FArrangedChildren::Num(), Standard, EVisibility::Visible, and Widgets.
FindArrangedWidget()
TOptional< FArrangedWidget > FWidgetPath::FindArrangedWidget (TSharedRef< const SWidget > WidgetToFind) const
FindArrangedWidgetAndCursor()
TOptional< FWidgetAndPointer > FWidgetPath::FindArrangedWidgetAndCursor (TSharedRef< const SWidget > WidgetToFind) const
GeneratePathToWidget()
template<typename MatcherType> FArrangedChildren FWidgetPath::GeneratePathToWidget (const MatcherType & Matcher, const FArrangedWidget & FromWidget, EUINavigation NavigationType = EUINavigation::Next, EVisibility VisibilityFilter = EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose = EWidgetPathSearchPurpose::Standard) inline
Generate a path from FromWidget to WidgetToFind.
The path will not include FromWidget.
Parameters
Matcher Some struct that has a "bool IsMatch(const TSharedRef<const SWidget>& InWidget) const" method
FromWidget Widget from which we a building a path.AddItem*
VisibilityFilter Widgets must have this type of visibility to be included the path
SearchPurpose What is the purpose for generating the path
Returns
A path from FromWidget to WidgetToFind; will not include FromWidget.
Definition at line 137 of file WidgetPath.h.
References FArrangedChildren::Reverse(), SearchForWidgetRecursively(), SearchForWidgetRecursively_Reverse(), Standard, and EVisibility::Visible.
Referenced by ExtendPathTo().
GetDeepestWindow()
TSharedRef< SWindow > FWidgetPath::GetDeepestWindow () const
Get the deepest (bottom-most) window in this path; assumes path is valid.
Returns
Window at the bottom of this path.
GetLastWidget()
TSharedRef< SWidget > FWidgetPath::GetLastWidget () const inline
Get the last (leaf-most) widget in this path; assumes path is valid.
Definition at line 170 of file WidgetPath.h.
References check, IsValid(), and Widgets.
GetPathDownTo()
FWidgetPath FWidgetPath::GetPathDownTo (TSharedRef< const SWidget > MarkerWidget) const
Parameters
MarkerWidget Copy the path up to and including this widget
Returns
a copy of the widget path down to and including the MarkerWidget. If the MarkerWidget is not found in the path, return an invalid path.
References FWidgetPath().
GetVirtualPointerPosition()
TOptional< FVirtualPointerPosition > FWidgetPath::GetVirtualPointerPosition (int32 Index) const inline
Get the virtual representation of the mouse at each level in the widget path.
Definition at line 67 of file WidgetPath.h.
References VirtualPointerPositions.
GetWindow()
TSharedRef< SWindow > FWidgetPath::GetWindow () const
Get the first (top-most) widget in this path, which is always a window; assumes path is valid.
Returns
Window at the top of this path.
IsValid()
bool FWidgetPath::IsValid () const
A valid path has at least one widget in it.
Referenced by GetLastWidget().
MoveFocus()
bool FWidgetPath::MoveFocus (int32 PathLevel, EUINavigation NavigationType, bool bSearchFromPathWidget = true)
Move focus either forward on backward in the path level specified by PathLevel.
That is, this movement of focus will modify the subtree under Widgets(PathLevel).
Parameters
PathLevel The level in this WidgetPath whose focus to move.
MoveDirectin Move focus forward or backward?
bSearchFromPathWidget if set false the search for the next will simply start at the beginning or end of the list of children dependant on the direction
Returns
true if the focus moved successfully, false if we were unable to move focus
SearchForWidgetRecursively()
template<typename MatchRuleType> bool FWidgetPath::SearchForWidgetRecursively (const MatchRuleType & MatchRule, const FArrangedWidget & InCandidate, FArrangedChildren & OutReversedPath, EVisibility VisibilityFilter = EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose = EWidgetPathSearchPurpose::Standard) static private
Utility function to search recursively through a widget hierarchy for a specific widget.
Parameters
Matcher Some struct that has a "bool IsMatch(const TSharedRef<const SWidget>& InWidget) const" method
InCandidate The current widget-geometry pair we're testing
OutReversedPath The resulting path in reversed order (canonical order is Windows @ index 0, Leafmost widget is last.)
VisibilityFilter Widgets must have this type of visibility to be included the path
SearchPurpose The purpose for searching for the widget in the path
Returns
true if the child widget was found; false otherwise
References Standard, and EVisibility::Visible.
Referenced by GeneratePathToWidget().
SearchForWidgetRecursively_Reverse()
template<typename MatchRuleType> bool FWidgetPath::SearchForWidgetRecursively_Reverse (const MatchRuleType & MatchRule, const FArrangedWidget & InCandidate, FArrangedChildren & OutReversedPath, EVisibility VisibilityFilter = EVisibility::Visible, EWidgetPathSearchPurpose SearchPurpose = EWidgetPathSearchPurpose::Standard) static private
Identical to SearchForWidgetRecursively, but iterates in reverse order.
References Standard, and EVisibility::Visible.
Referenced by GeneratePathToWidget().
ToString()
FString FWidgetPath::ToString () const
Builds a string representation of the widget path.
Field Documentation
TopLevelWindow
TSharedPtr<SWindow> FWidgetPath::TopLevelWindow
The top level window of this widget path.
Definition at line 182 of file WidgetPath.h.
VirtualPointerPositions
TArray<TOptional<FVirtualPointerPosition> > FWidgetPath::VirtualPointerPositions private
The virtual representation of the mouse at each level in the widget path.
Due to 3D widgets, the space you transition to can be completely arbitrary as you traverse the tree.
Definition at line 186 of file WidgetPath.h.
Referenced by GetVirtualPointerPosition().
Widgets
FArrangedChildren FWidgetPath::Widgets
The widgets that make up the widget path, the first item is the root widget, the end is the widget this path was built for.
Definition at line 179 of file WidgetPath.h.
Referenced by ExtendPathTo(), and GetLastWidget().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Layout/WidgetPath.h