Unreal Engine 5.6 C++ API: FThreadHeartBeat Class Reference
FThreadHeartBeat Class Reference
Thread heartbeat check class.
#include "ThreadHeartBeat.h"
Data Structures
struct FHeartBeatInfo
Holds per-thread info about the heartbeat.
Public Types
enum EConstants { InvalidThreadId = (uint32)-1 , PresentThreadId = (uint32)-2 }
Public Member Functions
uint32 CheckCheckpointHeartBeat (double &OutHangDuration)
uint32 CheckFunctionHeartBeat (double &OutHangDuration)
Called by a supervising thread to check all function calls' being monitored health.
uint32 CheckHeartBeat (double &OutHangDuration)
Called by a supervising thread to check the threads' health.
double GetHangDuration () const
uint32 GetLastHungThreadId () const
uint32 GetLastStuckThreadId () const
FOnHangDelegate & GetOnHangDelegate ()
FOnThreadStuck & GetOnThreadStuck ()
FOnThreadUnstuck & GetOnThreadUnstuck ()
void HeartBeat (bool bReadConfig=false)
Called from a thread once per frame to update the heartbeat time.
virtual bool Init ()
Initializes the runnable object.
bool IsBeating ()
Returns true/false if this thread is currently performing heartbeat monitoring.
void KillHeartBeat ()
Called by a thread when it's no longer expecting to be ticked.
void MonitorCheckpointEnd (FName CheckPoint)
void MonitorCheckpointStart (FName EndCheckPoint, double TimeToReachCheckpoint)
void MonitorFunctionEnd ()
Called by a thread when a function has completed and no longer needs to be monitored.
void MonitorFunctionStart ()
Called from a thread once on entry to a function to be monitored.
void PresentFrame ()
Called from the rendering or RHI thread when the platform RHI presents a frame (supported platforms only).
void ResumeHeartBeat (bool bAllThreads=false)
Resume heartbeat measuring for the current thread.
virtual uint32 Run ()
Runs the runnable object.
void SetDurationMultiplier (double NewMultiplier)
Sets a multiplier to the hang duration (>= 1.0).
void Start ()
Begin measuring heartbeat.
virtual void Stop ()
Stops the runnable object.
void SuspendHeartBeat (bool bAllThreads=false)
Suspend heartbeat measuring for the current thread if the thread has already had a heartbeat.
Public Member Functions inherited from FRunnable
virtual ~FRunnable ()
Virtual destructor.
virtual void Exit ()
Exits the runnable object.
virtual class FSingleThreadRunnable * GetSingleThreadInterface ()
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
Static Public Member Functions
static FThreadHeartBeat & Get ()
Gets the heartbeat singleton.
static FThreadHeartBeat * GetNoInit ()
Private Member Functions
FThreadHeartBeat ()
virtual ~FThreadHeartBeat ()
void InitSettings ()
bool IsEnabled ()
void FORCENOINLINE OnHang (double HangDuration, uint32 ThreadThatHung)
void FORCENOINLINE OnPresentHang (double HangDuration)
Private Attributes
bool bHangsAreFatal
FThreadSafeBool bReadyToCheckHeartbeat
True if heartbeat should be measured.
TMap< FName, FHeartBeatInfo > CheckpointHeartBeat
Keeps track of the last heartbeat time for a checkpoint.
FCriticalSection CheckpointHeartBeatCritical
Synch object for the checkpoint heartbeat.
int32 CheckpointSuspendCount
FThreadHeartBeatClock Clock
double ConfigHangDuration
Max time the thread is allowed to not send the heartbeat.
double ConfigPresentDuration
double ConfigStuckDuration
double CurrentHangDuration
double CurrentPresentDuration
double CurrentStuckDuration
TMap< uint32, FHeartBeatInfo > FunctionHeartBeat
Keeps track of the last heartbeat time for a function, can't be nested.
FCriticalSection FunctionHeartBeatCritical
Synch object for the function heartbeat.
FThreadSafeCounter GlobalSuspendCount
double HangDurationMultiplier
FCriticalSection HeartBeatCritical
Synch object for the heartbeat.
uint32 LastHangCallstackCRC
CRC of the last hang's callstack.
uint32 LastHungThreadId
Id of the last thread that hung.
uint32 LastStuckThreadId
FOnHangDelegate OnHangDelegate
FOnThreadStuck OnStuck
FOnThreadUnstuck OnUnstuck
FHeartBeatInfo PresentHeartBeat
The last heartbeat time for the rendering or RHI thread frame present.
FThreadSafeCounter StopTaskCounter
Stops this thread.
FRunnableThread * Thread
Thread to run the worker FRunnable on.
TMap< uint32, FHeartBeatInfo > ThreadHeartBeat
Keeps track of the last heartbeat time for threads.
Static Private Attributes
static FThreadHeartBeat * Singleton
Detailed Description
Thread heartbeat check class.
Used by crash handling code to check for hangs.
Definition at line 49 of file ThreadHeartBeat.h.
Member Enumeration Documentation
EConstants
enum FThreadHeartBeat::EConstants
Enumerator
InvalidThreadId
Invalid thread Id used by CheckHeartBeat.
PresentThreadId
Id used to track presented frames (supported platforms only).
Definition at line 160 of file ThreadHeartBeat.h.
Constructor & Destructor Documentation
FThreadHeartBeat()
FThreadHeartBeat::FThreadHeartBeat () private
Referenced by Get(), and GetNoInit().
~FThreadHeartBeat()
virtual FThreadHeartBeat::~FThreadHeartBeat () private virtual
Member Function Documentation
CheckCheckpointHeartBeat()
uint32 FThreadHeartBeat::CheckCheckpointHeartBeat (double & OutHangDuration)
CheckFunctionHeartBeat()
uint32 FThreadHeartBeat::CheckFunctionHeartBeat (double & OutHangDuration)
Called by a supervising thread to check all function calls' being monitored health.
CheckHeartBeat()
uint32 FThreadHeartBeat::CheckHeartBeat (double & OutHangDuration)
Called by a supervising thread to check the threads' health.
Get()
FThreadHeartBeat & FThreadHeartBeat::Get () static
Gets the heartbeat singleton.
References FThreadHeartBeat().
GetHangDuration()
double FThreadHeartBeat::GetHangDuration () const inline
Definition at line 250 of file ThreadHeartBeat.h.
References ConfigHangDuration.
GetLastHungThreadId()
uint32 FThreadHeartBeat::GetLastHungThreadId () const inline
Definition at line 227 of file ThreadHeartBeat.h.
References LastHungThreadId.
GetLastStuckThreadId()
uint32 FThreadHeartBeat::GetLastStuckThreadId () const inline
Definition at line 233 of file ThreadHeartBeat.h.
References LastStuckThreadId.
GetNoInit()
FThreadHeartBeat * FThreadHeartBeat::GetNoInit () static
References FThreadHeartBeat().
Referenced by FFunctionHeartBeatScope::FFunctionHeartBeatScope(), FSlowHeartBeatScope::FSlowHeartBeatScope(), FFunctionHeartBeatScope::~FFunctionHeartBeatScope(), and FSlowHeartBeatScope::~FSlowHeartBeatScope().
GetOnHangDelegate()
FOnHangDelegate & FThreadHeartBeat::GetOnHangDelegate () inline
Definition at line 245 of file ThreadHeartBeat.h.
References OnHangDelegate.
GetOnThreadStuck()
FOnThreadStuck & FThreadHeartBeat::GetOnThreadStuck () inline
Definition at line 238 of file ThreadHeartBeat.h.
References OnStuck.
GetOnThreadUnstuck()
FOnThreadUnstuck & FThreadHeartBeat::GetOnThreadUnstuck () inline
Definition at line 239 of file ThreadHeartBeat.h.
References OnUnstuck.
HeartBeat()
void FThreadHeartBeat::HeartBeat (bool bReadConfig = false)
Called from a thread once per frame to update the heartbeat time.
Init()
virtual bool FThreadHeartBeat::Init () virtual
Initializes the runnable object.
This method is called in the context of the thread object that aggregates this, not the thread that passes this runnable to a new thread.
Returns
True if initialization was successful, false otherwise
See also
Run, Stop, Exit
Reimplemented from FRunnable.
InitSettings()
void FThreadHeartBeat::InitSettings () private
IsBeating()
bool FThreadHeartBeat::IsBeating ()
Returns true/false if this thread is currently performing heartbeat monitoring.
IsEnabled()
bool FThreadHeartBeat::IsEnabled () private
KillHeartBeat()
void FThreadHeartBeat::KillHeartBeat ()
Called by a thread when it's no longer expecting to be ticked.
MonitorCheckpointEnd()
void FThreadHeartBeat::MonitorCheckpointEnd (FName CheckPoint)
MonitorCheckpointStart()
void FThreadHeartBeat::MonitorCheckpointStart (FName EndCheckPoint, double TimeToReachCheckpoint)
MonitorFunctionEnd()
void FThreadHeartBeat::MonitorFunctionEnd ()
Called by a thread when a function has completed and no longer needs to be monitored.
MonitorFunctionStart()
void FThreadHeartBeat::MonitorFunctionStart ()
Called from a thread once on entry to a function to be monitored.
OnHang()
void FORCENOINLINE FThreadHeartBeat::OnHang (double HangDuration, uint32 ThreadThatHung) private
References FORCENOINLINE.
OnPresentHang()
void FORCENOINLINE FThreadHeartBeat::OnPresentHang (double HangDuration) private
References FORCENOINLINE.
PresentFrame()
void FThreadHeartBeat::PresentFrame ()
Called from the rendering or RHI thread when the platform RHI presents a frame (supported platforms only).
ResumeHeartBeat()
void FThreadHeartBeat::ResumeHeartBeat (bool bAllThreads = false)
Resume heartbeat measuring for the current thread.
Parameters
bAllThreads If true, resumes heartbeat for all threads, not only the current one
Run()
virtual uint32 FThreadHeartBeat::Run () virtual
Runs the runnable object.
This is where all per object thread work is done. This is only called if the initialization was successful.
Returns
The exit code of the runnable object
See also
Init, Stop, Exit
Implements FRunnable.
SetDurationMultiplier()
void FThreadHeartBeat::SetDurationMultiplier (double NewMultiplier)
Sets a multiplier to the hang duration (>= 1.0).
Can be used to extend the duration during loading screens etc.
Start()
void FThreadHeartBeat::Start ()
Begin measuring heartbeat.
Stop()
virtual void FThreadHeartBeat::Stop () virtual
Stops the runnable object.
This is called if a thread is requested to terminate early.
See also
Init, Run, Exit
Reimplemented from FRunnable.
SuspendHeartBeat()
void FThreadHeartBeat::SuspendHeartBeat (bool bAllThreads = false)
Suspend heartbeat measuring for the current thread if the thread has already had a heartbeat.
Parameters
bAllThreads If true, suspends heartbeat for all threads, not only the current one
Field Documentation
bHangsAreFatal
bool FThreadHeartBeat::bHangsAreFatal private
Definition at line 137 of file ThreadHeartBeat.h.
bReadyToCheckHeartbeat
FThreadSafeBool FThreadHeartBeat::bReadyToCheckHeartbeat private
True if heartbeat should be measured.
Definition at line 119 of file ThreadHeartBeat.h.
CheckpointHeartBeat
TMap<FName, FHeartBeatInfo> FThreadHeartBeat::CheckpointHeartBeat private
Keeps track of the last heartbeat time for a checkpoint.
Definition at line 116 of file ThreadHeartBeat.h.
CheckpointHeartBeatCritical
FCriticalSection FThreadHeartBeat::CheckpointHeartBeatCritical private
Synch object for the checkpoint heartbeat.
Definition at line 114 of file ThreadHeartBeat.h.
CheckpointSuspendCount
int32 FThreadHeartBeat::CheckpointSuspendCount private
Definition at line 140 of file ThreadHeartBeat.h.
Clock
FThreadHeartBeatClock FThreadHeartBeat::Clock private
Definition at line 142 of file ThreadHeartBeat.h.
ConfigHangDuration
double FThreadHeartBeat::ConfigHangDuration private
Max time the thread is allowed to not send the heartbeat.
Definition at line 121 of file ThreadHeartBeat.h.
Referenced by GetHangDuration().
ConfigPresentDuration
double FThreadHeartBeat::ConfigPresentDuration private
Definition at line 123 of file ThreadHeartBeat.h.
ConfigStuckDuration
double FThreadHeartBeat::ConfigStuckDuration private
Definition at line 125 of file ThreadHeartBeat.h.
CurrentHangDuration
double FThreadHeartBeat::CurrentHangDuration private
Definition at line 122 of file ThreadHeartBeat.h.
CurrentPresentDuration
double FThreadHeartBeat::CurrentPresentDuration private
Definition at line 124 of file ThreadHeartBeat.h.
CurrentStuckDuration
double FThreadHeartBeat::CurrentStuckDuration private
Definition at line 126 of file ThreadHeartBeat.h.
FunctionHeartBeat
TMap<uint32, FHeartBeatInfo> FThreadHeartBeat::FunctionHeartBeat private
Keeps track of the last heartbeat time for a function, can't be nested.
Definition at line 111 of file ThreadHeartBeat.h.
FunctionHeartBeatCritical
FCriticalSection FThreadHeartBeat::FunctionHeartBeatCritical private
Synch object for the function heartbeat.
Definition at line 109 of file ThreadHeartBeat.h.
GlobalSuspendCount
FThreadSafeCounter FThreadHeartBeat::GlobalSuspendCount private
Definition at line 139 of file ThreadHeartBeat.h.
HangDurationMultiplier
double FThreadHeartBeat::HangDurationMultiplier private
Definition at line 128 of file ThreadHeartBeat.h.
HeartBeatCritical
FCriticalSection FThreadHeartBeat::HeartBeatCritical private
Synch object for the heartbeat.
Definition at line 102 of file ThreadHeartBeat.h.
LastHangCallstackCRC
uint32 FThreadHeartBeat::LastHangCallstackCRC private
CRC of the last hang's callstack.
Definition at line 131 of file ThreadHeartBeat.h.
LastHungThreadId
uint32 FThreadHeartBeat::LastHungThreadId private
Id of the last thread that hung.
Definition at line 133 of file ThreadHeartBeat.h.
Referenced by GetLastHungThreadId().
LastStuckThreadId
uint32 FThreadHeartBeat::LastStuckThreadId private
Definition at line 135 of file ThreadHeartBeat.h.
Referenced by GetLastStuckThreadId().
OnHangDelegate
FOnHangDelegate FThreadHeartBeat::OnHangDelegate private
Definition at line 146 of file ThreadHeartBeat.h.
Referenced by GetOnHangDelegate().
OnStuck
FOnThreadStuck FThreadHeartBeat::OnStuck private
Definition at line 144 of file ThreadHeartBeat.h.
Referenced by GetOnThreadStuck().
OnUnstuck
FOnThreadUnstuck FThreadHeartBeat::OnUnstuck private
Definition at line 145 of file ThreadHeartBeat.h.
Referenced by GetOnThreadUnstuck().
PresentHeartBeat
FHeartBeatInfo FThreadHeartBeat::PresentHeartBeat private
The last heartbeat time for the rendering or RHI thread frame present.
Definition at line 106 of file ThreadHeartBeat.h.
Singleton
FThreadHeartBeat* FThreadHeartBeat::Singleton static private
Definition at line 51 of file ThreadHeartBeat.h.
StopTaskCounter
FThreadSafeCounter FThreadHeartBeat::StopTaskCounter private
Stops this thread.
Definition at line 100 of file ThreadHeartBeat.h.
Thread
FRunnableThread* FThreadHeartBeat::Thread private
Thread to run the worker FRunnable on.
Definition at line 98 of file ThreadHeartBeat.h.
ThreadHeartBeat
TMap<uint32, FHeartBeatInfo> FThreadHeartBeat::ThreadHeartBeat private
Keeps track of the last heartbeat time for threads.
Definition at line 104 of file ThreadHeartBeat.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/ThreadHeartBeat.h