Unreal Engine 5.6 C++ API: FSlateRenderer Class Reference
FSlateRenderer Class Reference abstract
Abstract base class for Slate renderers.
#include "SlateRenderer.h"
Data Structures
struct FScopedAcquireDrawBuffer
Acquire the draw buffer and release it at the end of the scope.
Public Member Functions
FSlateRenderer (const TSharedRef< FSlateFontServices > &InSlateFontServices)
Constructor.
virtual ~FSlateRenderer ()
Virtual destructor.
virtual FSlateDrawBuffer & AcquireDrawBuffer ()=0
Returns a draw buffer that can be used by Slate windows to draw window elements.
virtual void AddWidgetRendererUpdate (const struct FRenderThreadUpdateContext &Context, bool bDeferredRenderTargetUpdate)
Lets the renderer know that we need to render some widgets to a render target.
virtual bool AreShadersInitialized () const
Returns whether shaders that Slate depends on have been compiled.
virtual void BeginFrame () const
Indicates the start of a new frame to the Renderer.
virtual bool CanRenderResource (UObject &InResourceObject) const
The default implementation assumes all things are renderable.
virtual void ClearScenes ()=0
Reset the internal Scene tracking.
virtual void CopyWindowsToVirtualScreenBuffer (const TArray< FString > &KeypressBuffer)
Copies all slate windows out to a buffer at half resolution with debug information like the mouse cursor and any keypresses.
virtual FSlateUpdatableTexture * CreateSharedHandleTexture (void *SharedHandle)=0
Create an updatable texture that can receive new data via a shared handle.
virtual void CreateViewport (const TSharedRef< SWindow > InWindow)=0
Creates a rendering viewport.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPostResizeWindowBackbuffer, void *)
Called on the game thread right after a window backbuffer has been resized.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPreResizeWindowBackbuffer, void *)
Called on the game thread right before a window backbuffer is about to be resized.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSlateWindowDestroyed, void *)
Called on the game thread right before the slate window handle is destroyed.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnSlateWindowRendered, SWindow &, void *)
Callback that fires after Slate has rendered each window, each frame.
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams (FOnAddBackBufferReadyToPresentPass, FRDGBuilder &, SWindow &, FRDGTexture *)
Callback on the render thread after slate rendering finishes and right before present is called.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnBackBufferReadyToPresent, SWindow &, const FTextureRHIRef &)
Callback on the render thread after slate rendering finishes and right before present is called.
virtual void Destroy ()=0
virtual void DestroyCachedFastPathElementData (struct FSlateCachedElementData *ElementData)
virtual void DestroyCachedFastPathRenderingData (struct FSlateCachedFastPathRenderingData *VertexData)
virtual void DrawWindows (FSlateDrawBuffer &InWindowDrawBuffer)=0
Creates necessary resources to render a window and sends draw commands to the rendering thread.
virtual void EndFrame () const
Indicates the end of the current frame to the Renderer.
virtual void FlushCommands () const
Gives the renderer a chance to wait for any render commands to be completed before returning/.
void FlushFontCache (const FString &FlushReason)
Flushes all cached data from the font cache for the current thread.
virtual FIntPoint GenerateDynamicImageResource (const FName InTextureName)
Creates a dynamic image resource and returns its size.
virtual bool GenerateDynamicImageResource (FName ResourceName, FSlateTextureDataRef TextureData)
virtual bool GenerateDynamicImageResource (FName ResourceName, uint32 Width, uint32 Height, const TArray< uint8 > &Bytes)
Creates a dynamic image resource.
virtual int32 GetCurrentSceneIndex () const =0
Get the currently registered scene index (set by RegisterCurrentScene)
virtual ISlateAtlasProvider * GetFontAtlasProvider ()
Returns the way to access the font atlas information for this renderer.
TSharedRef< class FSlateFontCache > GetFontCache () const
Get the font cache to use for the current thread.
TSharedRef< class FSlateFontMeasure > GetFontMeasureService () const
Get access to the font measure service (game thread only!)
TSharedRef< FSlateFontServices > GetFontServices () const
Get access to the font services used by this renderer.
virtual FCriticalSection * GetResourceCriticalSection ()=0
Necessary to grab before flushing the resource pool, as it may be being accessed by multiple threads when loading.
virtual FSlateResourceHandle GetResourceHandle (const FSlateBrush &Brush)
Creates a handle to a Slate resource A handle is used as fast path for looking up a rendering resource for a given brush when adding Slate draw elements This can be cached and stored safely in code.
virtual FSlateResourceHandle GetResourceHandle (const FSlateBrush &Brush, FVector2f LocalSize, float DrawScale)=0
virtual EPixelFormat GetSlateRecommendedColorFormat ()
virtual ISlateAtlasProvider * GetTextureAtlasProvider ()
Returns the way to access the texture atlas information for this renderer.
virtual void * GetViewportResource (const SWindow &Window)
Returns the viewport rendering resource (backbuffer) for the provided window.
virtual bool HasLostDevice () const
virtual bool Initialize ()=0
virtual void InvalidateAllViewports ()
Removes references to FViewportRHI's.
bool IsViewportFullscreen (const SWindow &Window) const
Returns whether or not a viewport should be in fullscreen.
virtual void LoadStyleResources (const ISlateStyle &Style)
Loads all the resources used by the specified SlateStyle.
virtual void MapVirtualScreenBuffer (FMappedTextureBuffer *OutImageData)
Allows and disallows access to the crash tracker buffer data on the CPU.
FOnAddBackBufferReadyToPresentPass & OnAddBackBufferReadyToPresentPass ()
FOnBackBufferReadyToPresent & OnBackBufferReadyToPresent ()
FOnPostResizeWindowBackbuffer & OnPostResizeWindowBackBuffer ()
FOnPreResizeWindowBackbuffer & OnPreResizeWindowBackBuffer ()
FOnSlateWindowDestroyed & OnSlateWindowDestroyed ()
FOnSlateWindowRendered & OnSlateWindowRendered ()
virtual void OnVirtualDesktopSizeChanged (const FDisplayMetrics &NewDisplayMetric)
virtual void OnWindowDestroyed (const TSharedRef< SWindow > &InWindow)=0
Called when a window is destroyed to give the renderer a chance to free resources.
virtual void OnWindowFinishReshaped (const TSharedPtr< SWindow > &InWindow)
Called when a window is finished being reshaped.
virtual void PrepareToTakeHDRScreenshot (const FIntRect &Rect, TArray< FLinearColor > *OutColorData, SWindow *InScreenshotWindow)
Prepares the renderer to take a screenshot of the UI.
virtual void PrepareToTakeScreenshot (const FIntRect &Rect, TArray< FColor > *OutColorData, SWindow *InScreenshotWindow)
Prepares the renderer to take a screenshot of the UI.
virtual int32 RegisterCurrentScene (FSceneInterface *Scene)=0
Register the active scene pointer with the renderer.
virtual void ReleaseAccessedResources (bool bImmediatelyFlush)
A renderer may need to keep a cache of accessed garbage collectible objects alive for the duration of their usage.
virtual void ReleaseDrawBuffer (FSlateDrawBuffer &InWindowDrawBuffer)=0
Return the previously acquired buffer.
virtual void ReleaseDynamicResource (const FSlateBrush &Brush)=0
Releases a specific resource.
virtual void ReleaseUpdatableTexture (FSlateUpdatableTexture *Texture)=0
Return an updatable texture to the renderer for release.
virtual void ReloadTextureResources ()
Reloads all texture resources from disk.
virtual void RemoveDynamicBrushResource (TSharedPtr< FSlateDynamicImageBrush > BrushToRemove)=0
Queues a dynamic brush for removal when it is safe.
virtual void RequestResize (const TSharedPtr< SWindow > &InWindow, uint32 NewSizeX, uint32 NewSizeY)=0
Requests that a rendering viewport be resized.
virtual void RestoreSystemResolution (const TSharedRef< SWindow > InWindow)=0
Restore the given window to the resolution settings currently cached by the engine.
virtual void SetColorVisionDeficiencyType (EColorVisionDeficiency Type, int32 Severity, bool bCorrectDeficiency, bool bShowCorrectionWithDeficiency)
Sets which color vision filter to use.
virtual void SetCurrentSceneIndex (int32 InIndex)=0
Set currently registered scene index.
virtual void SetSystemResolution (uint32 Width, uint32 Height)=0
Set the resolution cached by the engine.
virtual void Sync () const
Gives the renderer a chance to synchronize with another thread in the event that the renderer runs in a multi-threaded environment.
UE_DEPRECATED (5.1, "Use FSlateRenderer::AcquireDrawBuffer instead and release the draw buffer.") virtual FSlateDrawBuffer &GetDrawBuffer()
Returns a draw buffer that can be used by Slate windows to draw window elements.
UE_DEPRECATED (5.5, "SetWindowRenderTarget is no longer used.") virtual void SetWindowRenderTarget(const SWindow &Window
Pushes the rendering of the specified window to the specified render target.
virtual void UnmapVirtualScreenBuffer ()
virtual void UpdateFullscreenState (const TSharedRef< SWindow > InWindow, uint32 OverrideResX=0, uint32 OverrideResY=0)=0
Sets fullscreen state on the window's rendering viewport.
Data Fields
class IViewportRenderTargetProvider * Provider
Protected Attributes
FOnAddBackBufferReadyToPresentPass OnAddBackBufferReadyToPresentPassDelegate
FOnBackBufferReadyToPresent OnBackBufferReadyToPresentDelegate
FOnSlateWindowDestroyed OnSlateWindowDestroyedDelegate
FOnPostResizeWindowBackbuffer PostResizeBackBufferDelegate
FOnPreResizeWindowBackbuffer PreResizeBackBufferDelegate
FCriticalSection ResourceCriticalSection
Necessary to grab before flushing the resource pool, as it may be being accessed by multiple threads when loading.
TSharedPtr< FSlateFontServices > SlateFontServices
The font services used by this renderer when drawing text.
FOnSlateWindowRendered SlateWindowRendered
Callback that fires after Slate has rendered each window, each frame.
Private Member Functions
FSlateRenderer (const FSlateRenderer &)
void HandleFontCacheReleaseResources (const class FSlateFontCache &InFontCache)
FSlateRenderer & operator= (const FSlateRenderer &)
Friends
class FSlateRenderDataHandle
Detailed Description
Abstract base class for Slate renderers.
Definition at line 172 of file SlateRenderer.h.
Constructor & Destructor Documentation
FSlateRenderer() [1/2]
FSlateRenderer::FSlateRenderer (const TSharedRef< FSlateFontServices > & InSlateFontServices) explicit
Constructor.
Referenced by FSlateRenderer::FScopedAcquireDrawBuffer::FScopedAcquireDrawBuffer(), FSlateRenderer(), and operator=().
~FSlateRenderer()
virtual FSlateRenderer::~FSlateRenderer () virtual
Virtual destructor.
FSlateRenderer() [2/2]
FSlateRenderer::FSlateRenderer (const FSlateRenderer &) private
References FSlateRenderer().
Member Function Documentation
AcquireDrawBuffer()
virtual FSlateDrawBuffer & FSlateRenderer::AcquireDrawBuffer () pure virtual
Returns a draw buffer that can be used by Slate windows to draw window elements.
Referenced by FSlateRenderer::FScopedAcquireDrawBuffer::FScopedAcquireDrawBuffer(), and UE_DEPRECATED().
AddWidgetRendererUpdate()
virtual void FSlateRenderer::AddWidgetRendererUpdate (const struct FRenderThreadUpdateContext & Context, bool bDeferredRenderTargetUpdate) inline virtual
Lets the renderer know that we need to render some widgets to a render target.
Parameters
Context The context that describes what we're rendering to
bDeferredRenderTargetUpdate Whether or not the update is deferred until the end of the frame when it is potentially less expensive to update the render target. See GDeferRetainedRenderingRenderThread for more info. Care must be taken to destroy anything referenced in the context when it is safe to do so.
Definition at line 567 of file SlateRenderer.h.
AreShadersInitialized()
virtual bool FSlateRenderer::AreShadersInitialized () const inline virtual
Returns whether shaders that Slate depends on have been compiled.
Definition at line 456 of file SlateRenderer.h.
BeginFrame()
virtual void FSlateRenderer::BeginFrame () const inline virtual
Indicates the start of a new frame to the Renderer.
This is usually handled by the engine loop but certain situations (ie, when the main loop is paused) may require manual calls.
Definition at line 429 of file SlateRenderer.h.
CanRenderResource()
virtual bool FSlateRenderer::CanRenderResource (UObject & InResourceObject) const inline virtual
The default implementation assumes all things are renderable.
Definition at line 353 of file SlateRenderer.h.
ClearScenes()
virtual void FSlateRenderer::ClearScenes () pure virtual
Reset the internal Scene tracking.
CopyWindowsToVirtualScreenBuffer()
virtual void FSlateRenderer::CopyWindowsToVirtualScreenBuffer (const TArray< FString > & KeypressBuffer) inline virtual
Copies all slate windows out to a buffer at half resolution with debug information like the mouse cursor and any keypresses.
Definition at line 530 of file SlateRenderer.h.
CreateSharedHandleTexture()
virtual FSlateUpdatableTexture * FSlateRenderer::CreateSharedHandleTexture (void * SharedHandle) pure virtual
Create an updatable texture that can receive new data via a shared handle.
Parameters
SharedHandle The OS dependant handle that backs the texture data
Returns
Newly created updatable texture
CreateViewport()
virtual void FSlateRenderer::CreateViewport (const TSharedRef< SWindow > InWindow) pure virtual
Creates a rendering viewport.
Parameters
InWindow The window to create the viewport for
DECLARE_MULTICAST_DELEGATE_OneParam() [1/3]
FSlateRenderer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPostResizeWindowBackbuffer , void *)
Called on the game thread right after a window backbuffer has been resized.
Parameters
Pointer to the API specific backbuffer type
DECLARE_MULTICAST_DELEGATE_OneParam() [2/3]
FSlateRenderer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPreResizeWindowBackbuffer , void *)
Called on the game thread right before a window backbuffer is about to be resized.
Parameters
Pointer to the API specific backbuffer type
DECLARE_MULTICAST_DELEGATE_OneParam() [3/3]
FSlateRenderer::DECLARE_MULTICAST_DELEGATE_OneParam (FOnSlateWindowDestroyed , void *)
Called on the game thread right before the slate window handle is destroyed.
This gives users a chance to release any viewport specific resources they may have active when the window is destroyed
Parameters
Pointer to the API specific backbuffer type
DECLARE_MULTICAST_DELEGATE_TwoParams()
FSlateRenderer::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnSlateWindowRendered , SWindow & , void *)
Callback that fires after Slate has rendered each window, each frame.
DECLARE_TS_MULTICAST_DELEGATE_ThreeParams()
FSlateRenderer::DECLARE_TS_MULTICAST_DELEGATE_ThreeParams (FOnAddBackBufferReadyToPresentPass , FRDGBuilder & , SWindow & , FRDGTexture *)
Callback on the render thread after slate rendering finishes and right before present is called.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams()
FSlateRenderer::DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnBackBufferReadyToPresent , SWindow & , const FTextureRHIRef &)
Callback on the render thread after slate rendering finishes and right before present is called.
Destroy()
virtual void FSlateRenderer::Destroy () pure virtual
DestroyCachedFastPathElementData()
virtual void FSlateRenderer::DestroyCachedFastPathElementData (struct FSlateCachedElementData * ElementData) virtual
DestroyCachedFastPathRenderingData()
virtual void FSlateRenderer::DestroyCachedFastPathRenderingData (struct FSlateCachedFastPathRenderingData * VertexData) virtual
DrawWindows()
virtual void FSlateRenderer::DrawWindows (FSlateDrawBuffer & InWindowDrawBuffer) pure virtual
Creates necessary resources to render a window and sends draw commands to the rendering thread.
Parameters
WindowDrawBuffer The buffer containing elements to draw
EndFrame()
virtual void FSlateRenderer::EndFrame () const inline virtual
Indicates the end of the current frame to the Renderer.
This is usually handled by the engine loop but certain situations (ie, when the main loop is paused) may require manual calls.
Definition at line 435 of file SlateRenderer.h.
FlushCommands()
virtual void FSlateRenderer::FlushCommands () const inline virtual
Gives the renderer a chance to wait for any render commands to be completed before returning/.
Definition at line 417 of file SlateRenderer.h.
FlushFontCache()
void FSlateRenderer::FlushFontCache (const FString & FlushReason) inline
Flushes all cached data from the font cache for the current thread.
Definition at line 409 of file SlateRenderer.h.
References SlateFontServices.
GenerateDynamicImageResource() [1/3]
virtual FIntPoint FSlateRenderer::GenerateDynamicImageResource (const FName InTextureName) inline virtual
Creates a dynamic image resource and returns its size.
Parameters
InTextureName The name of the texture resource
Returns
The size of the loaded texture
Definition at line 320 of file SlateRenderer.h.
References check.
GenerateDynamicImageResource() [2/3]
virtual bool FSlateRenderer::GenerateDynamicImageResource (FName ResourceName, FSlateTextureDataRef TextureData) inline virtual
Definition at line 333 of file SlateRenderer.h.
GenerateDynamicImageResource() [3/3]
virtual bool FSlateRenderer::GenerateDynamicImageResource (FName ResourceName, uint32 Width, uint32 Height, const TArray< uint8 > & Bytes) inline virtual
Creates a dynamic image resource.
Parameters
ResourceName The name of the texture resource
Width The width of the resource
Height The height of the image
Bytes The payload for the resource
Returns
true if the resource was successfully generated, otherwise false
Definition at line 331 of file SlateRenderer.h.
References Bytes, and Width.
GetCurrentSceneIndex()
virtual int32 FSlateRenderer::GetCurrentSceneIndex () const pure virtual
Get the currently registered scene index (set by RegisterCurrentScene)
GetFontAtlasProvider()
virtual ISlateAtlasProvider * FSlateRenderer::GetFontAtlasProvider () virtual
Returns the way to access the font atlas information for this renderer.
GetFontCache()
TSharedRef< class FSlateFontCache > FSlateRenderer::GetFontCache () const inline
Get the font cache to use for the current thread.
Definition at line 401 of file SlateRenderer.h.
References SlateFontServices.
GetFontMeasureService()
TSharedRef< class FSlateFontMeasure > FSlateRenderer::GetFontMeasureService () const inline
Get access to the font measure service (game thread only!)
Definition at line 393 of file SlateRenderer.h.
References SlateFontServices.
Referenced by UE::Insights::FDrawContext::DrawTextAligned().
GetFontServices()
TSharedRef< FSlateFontServices > FSlateRenderer::GetFontServices () const inline
Get access to the font services used by this renderer.
Definition at line 385 of file SlateRenderer.h.
References SlateFontServices.
GetResourceCriticalSection()
virtual FCriticalSection * FSlateRenderer::GetResourceCriticalSection () pure virtual
Necessary to grab before flushing the resource pool, as it may be being accessed by multiple threads when loading.
GetResourceHandle() [1/2]
virtual FSlateResourceHandle FSlateRenderer::GetResourceHandle (const FSlateBrush & Brush) inline virtual
Creates a handle to a Slate resource A handle is used as fast path for looking up a rendering resource for a given brush when adding Slate draw elements This can be cached and stored safely in code.
It will become invalid when a resource is destroyed It is expensive to create a resource so do not do it in time sensitive areas
Parameters
Brush The brush to get a rendering resource handle
Returns
The created resource handle.
Definition at line 346 of file SlateRenderer.h.
References GetResourceHandle(), and UE::Math::TVector2< float >::ZeroVector.
GetResourceHandle() [2/2]
virtual FSlateResourceHandle FSlateRenderer::GetResourceHandle (const FSlateBrush & Brush, FVector2f LocalSize, float DrawScale) pure virtual
Referenced by GetResourceHandle().
GetSlateRecommendedColorFormat()
virtual EPixelFormat FSlateRenderer::GetSlateRecommendedColorFormat () inline virtual
Definition at line 569 of file SlateRenderer.h.
References PF_B8G8R8A8.
GetTextureAtlasProvider()
virtual ISlateAtlasProvider * FSlateRenderer::GetTextureAtlasProvider () virtual
Returns the way to access the texture atlas information for this renderer.
GetViewportResource()
virtual void * FSlateRenderer::GetViewportResource (const SWindow & Window) inline virtual
Returns the viewport rendering resource (backbuffer) for the provided window.
Parameters
Window The window to get the viewport from
Definition at line 380 of file SlateRenderer.h.
HandleFontCacheReleaseResources()
void FSlateRenderer::HandleFontCacheReleaseResources (const class FSlateFontCache & InFontCache) private
HasLostDevice()
virtual bool FSlateRenderer::HasLostDevice () const inline virtual
Definition at line 557 of file SlateRenderer.h.
Initialize()
virtual bool FSlateRenderer::Initialize () pure virtual
InvalidateAllViewports()
virtual void FSlateRenderer::InvalidateAllViewports () inline virtual
Removes references to FViewportRHI's.
This has to be done explicitly instead of using the FRenderResource mechanism because FViewportRHI's are managed by the game thread. This is needed before destroying the RHI device.
Definition at line 463 of file SlateRenderer.h.
IsViewportFullscreen()
bool FSlateRenderer::IsViewportFullscreen (const SWindow & Window) const
Returns whether or not a viewport should be in fullscreen.
@Window The window to check for fullscreen
Returns
true if the window's viewport should be fullscreen
LoadStyleResources()
virtual void FSlateRenderer::LoadStyleResources (const ISlateStyle & Style) inline virtual
Loads all the resources used by the specified SlateStyle.
Definition at line 445 of file SlateRenderer.h.
MapVirtualScreenBuffer()
virtual void FSlateRenderer::MapVirtualScreenBuffer (FMappedTextureBuffer * OutImageData) inline virtual
Allows and disallows access to the crash tracker buffer data on the CPU.
Definition at line 533 of file SlateRenderer.h.
OnAddBackBufferReadyToPresentPass()
FOnAddBackBufferReadyToPresentPass & FSlateRenderer::OnAddBackBufferReadyToPresentPass () inline
Definition at line 307 of file SlateRenderer.h.
References OnAddBackBufferReadyToPresentPassDelegate.
OnBackBufferReadyToPresent()
FOnBackBufferReadyToPresent & FSlateRenderer::OnBackBufferReadyToPresent () inline
Definition at line 303 of file SlateRenderer.h.
References OnBackBufferReadyToPresentDelegate.
OnPostResizeWindowBackBuffer()
FOnPostResizeWindowBackbuffer & FSlateRenderer::OnPostResizeWindowBackBuffer () inline
Definition at line 299 of file SlateRenderer.h.
References PostResizeBackBufferDelegate.
OnPreResizeWindowBackBuffer()
FOnPreResizeWindowBackbuffer & FSlateRenderer::OnPreResizeWindowBackBuffer () inline
Definition at line 292 of file SlateRenderer.h.
References PreResizeBackBufferDelegate.
OnSlateWindowDestroyed()
FOnSlateWindowDestroyed & FSlateRenderer::OnSlateWindowDestroyed () inline
Definition at line 285 of file SlateRenderer.h.
References OnSlateWindowDestroyedDelegate.
OnSlateWindowRendered()
FOnSlateWindowRendered & FSlateRenderer::OnSlateWindowRendered () inline
Definition at line 277 of file SlateRenderer.h.
References SlateWindowRendered.
OnVirtualDesktopSizeChanged()
virtual void FSlateRenderer::OnVirtualDesktopSizeChanged (const FDisplayMetrics & NewDisplayMetric) inline virtual
Definition at line 571 of file SlateRenderer.h.
OnWindowDestroyed()
virtual void FSlateRenderer::OnWindowDestroyed (const TSharedRef< SWindow > & InWindow) pure virtual
Called when a window is destroyed to give the renderer a chance to free resources.
OnWindowFinishReshaped()
virtual void FSlateRenderer::OnWindowFinishReshaped (const TSharedPtr< SWindow > & InWindow) inline virtual
Called when a window is finished being reshaped.
Definition at line 373 of file SlateRenderer.h.
operator=()
FSlateRenderer & FSlateRenderer::operator= (const FSlateRenderer &) private
References FSlateRenderer().
PrepareToTakeHDRScreenshot()
virtual void FSlateRenderer::PrepareToTakeHDRScreenshot (const FIntRect & Rect, TArray< FLinearColor > * OutColorData, SWindow * InScreenshotWindow) inline virtual
Prepares the renderer to take a screenshot of the UI.
The Rect is portion of the rendered output that will be stored into the TArray of FColors.
Definition at line 482 of file SlateRenderer.h.
PrepareToTakeScreenshot()
virtual void FSlateRenderer::PrepareToTakeScreenshot (const FIntRect & Rect, TArray< FColor > * OutColorData, SWindow * InScreenshotWindow) inline virtual
Prepares the renderer to take a screenshot of the UI.
The Rect is portion of the rendered output that will be stored into the TArray of FColors.
Definition at line 476 of file SlateRenderer.h.
RegisterCurrentScene()
virtual int32 FSlateRenderer::RegisterCurrentScene (FSceneInterface * Scene) pure virtual
Register the active scene pointer with the renderer.
This will return the scene internal index that will be used for all subsequent elements drawn.
References Scene.
ReleaseAccessedResources()
virtual void FSlateRenderer::ReleaseAccessedResources (bool bImmediatelyFlush) inline virtual
A renderer may need to keep a cache of accessed garbage collectible objects alive for the duration of their usage.
During some operations like ending a game. It becomes important to immediately release game related resources. This should flush any buffer holding onto those referenced objects.
Definition at line 470 of file SlateRenderer.h.
ReleaseDrawBuffer()
virtual void FSlateRenderer::ReleaseDrawBuffer (FSlateDrawBuffer & InWindowDrawBuffer) pure virtual
Return the previously acquired buffer.
ReleaseDynamicResource()
virtual void FSlateRenderer::ReleaseDynamicResource (const FSlateBrush & Brush) pure virtual
Releases a specific resource.
It is unlikely that you want to call this directly. Use RemoveDynamicBrushResource instead
ReleaseUpdatableTexture()
virtual void FSlateRenderer::ReleaseUpdatableTexture (FSlateUpdatableTexture * Texture) pure virtual
Return an updatable texture to the renderer for release.
Parameters
Texture The texture we are releasing (should not use this pointer after calling)
References Texture.
ReloadTextureResources()
virtual void FSlateRenderer::ReloadTextureResources () inline virtual
Reloads all texture resources from disk.
Definition at line 440 of file SlateRenderer.h.
RemoveDynamicBrushResource()
virtual void FSlateRenderer::RemoveDynamicBrushResource (TSharedPtr< FSlateDynamicImageBrush > BrushToRemove) pure virtual
Queues a dynamic brush for removal when it is safe.
The brush is not immediately released but you should consider the brush destroyed and no longer usable
Parameters
BrushToRemove The brush to queue for removal which is no longer valid to use
RequestResize()
virtual void FSlateRenderer::RequestResize (const TSharedPtr< SWindow > & InWindow, uint32 NewSizeX, uint32 NewSizeY) pure virtual
Requests that a rendering viewport be resized.
Parameters
Window The window to resize
Width The new width of the window
Height The new height of the window
RestoreSystemResolution()
virtual void FSlateRenderer::RestoreSystemResolution (const TSharedRef< SWindow > InWindow) pure virtual
Restore the given window to the resolution settings currently cached by the engine.
Parameters
InWindow -> The window to restore to the cached settings
SetColorVisionDeficiencyType()
virtual void FSlateRenderer::SetColorVisionDeficiencyType (EColorVisionDeficiency Type, int32 Severity, bool bCorrectDeficiency, bool bShowCorrectionWithDeficiency) inline virtual
Sets which color vision filter to use.
Definition at line 312 of file SlateRenderer.h.
SetCurrentSceneIndex()
virtual void FSlateRenderer::SetCurrentSceneIndex (int32 InIndex) pure virtual
Set currently registered scene index.
SetSystemResolution()
virtual void FSlateRenderer::SetSystemResolution (uint32 Width, uint32 Height) pure virtual
Set the resolution cached by the engine.
Parameters
Width Width of the system resolution
Height Height of the system resolution
References Width.
Sync()
virtual void FSlateRenderer::Sync () const inline virtual
Gives the renderer a chance to synchronize with another thread in the event that the renderer runs in a multi-threaded environment.
This function does not return until the sync is complete
Definition at line 423 of file SlateRenderer.h.
UE_DEPRECATED() [1/2]
FSlateRenderer::UE_DEPRECATED (5. 1, "Use FSlateRenderer::AcquireDrawBuffer instead and release the draw buffer.") & inline
Returns a draw buffer that can be used by Slate windows to draw window elements.
Definition at line 210 of file SlateRenderer.h.
References AcquireDrawBuffer().
UE_DEPRECATED() [2/2]
FSlateRenderer::UE_DEPRECATED (5. 5, "SetWindowRenderTarget is no longer used.") const &
Pushes the rendering of the specified window to the specified render target.
UnmapVirtualScreenBuffer()
virtual void FSlateRenderer::UnmapVirtualScreenBuffer () inline virtual
Definition at line 534 of file SlateRenderer.h.
UpdateFullscreenState()
virtual void FSlateRenderer::UpdateFullscreenState (const TSharedRef< SWindow > InWindow, uint32 OverrideResX = 0, uint32 OverrideResY = 0) pure virtual
Sets fullscreen state on the window's rendering viewport.
Parameters
InWindow The window to update fullscreen state on
OverrideResX 0 if no override
OverrideResY 0 if no override
Friends And Related Symbol Documentation
FSlateRenderDataHandle
friend class FSlateRenderDataHandle friend
Definition at line 601 of file SlateRenderer.h.
References FSlateRenderDataHandle.
Referenced by FSlateRenderDataHandle.
Field Documentation
OnAddBackBufferReadyToPresentPassDelegate
FOnAddBackBufferReadyToPresentPass FSlateRenderer::OnAddBackBufferReadyToPresentPassDelegate protected
Definition at line 593 of file SlateRenderer.h.
Referenced by OnAddBackBufferReadyToPresentPass().
OnBackBufferReadyToPresentDelegate
FOnBackBufferReadyToPresent FSlateRenderer::OnBackBufferReadyToPresentDelegate protected
Definition at line 592 of file SlateRenderer.h.
Referenced by OnBackBufferReadyToPresent().
OnSlateWindowDestroyedDelegate
FOnSlateWindowDestroyed FSlateRenderer::OnSlateWindowDestroyedDelegate protected
Definition at line 588 of file SlateRenderer.h.
Referenced by OnSlateWindowDestroyed().
PostResizeBackBufferDelegate
FOnPostResizeWindowBackbuffer FSlateRenderer::PostResizeBackBufferDelegate protected
Definition at line 590 of file SlateRenderer.h.
Referenced by OnPostResizeWindowBackBuffer().
PreResizeBackBufferDelegate
FOnPreResizeWindowBackbuffer FSlateRenderer::PreResizeBackBufferDelegate protected
Definition at line 589 of file SlateRenderer.h.
Referenced by OnPreResizeWindowBackBuffer().
Provider
class IViewportRenderTargetProvider* FSlateRenderer::Provider
Initial value:
{}
    virtual FSlateUpdatableTexture* CreateUpdatableTexture(uint32 Width, uint32 Height) = 0
Definition at line 488 of file SlateRenderer.h.
ResourceCriticalSection
FCriticalSection FSlateRenderer::ResourceCriticalSection protected
Necessary to grab before flushing the resource pool, as it may be being accessed by multiple threads when loading.
Definition at line 599 of file SlateRenderer.h.
SlateFontServices
TSharedPtr<FSlateFontServices> FSlateRenderer::SlateFontServices protected
The font services used by this renderer when drawing text.
Definition at line 583 of file SlateRenderer.h.
Referenced by FlushFontCache(), GetFontCache(), GetFontMeasureService(), and GetFontServices().
SlateWindowRendered
FOnSlateWindowRendered FSlateRenderer::SlateWindowRendered protected
Callback that fires after Slate has rendered each window, each frame.
Definition at line 586 of file SlateRenderer.h.
Referenced by OnSlateWindowRendered().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Rendering/SlateRenderer.h