Unreal Engine 5.6 C++ API: TLinearRamper< T > Class Template Reference
TLinearRamper< T > Class Template Reference
#include "Ramper.h"
Public Member Functions
TLinearRamper (float InNumRampCallsPerSecond=1.0f)
TLinearRamper< T > & operator= (const T InValue)
bool Ramp ()
void SetTarget (T InTarget, FRamper::FCallback InCallback=nullptr, void *InData=nullptr)
void SnapTo (const T &InValue)
Public Member Functions inherited from TRamper< T >
TRamper (float InNumRampCallsPerSecond=1.0f)
const T & GetCurrent () const
float GetProgressPct () const
float GetRampTimeMs () const
const T & GetTarget () const
bool IsAtTarget () const
operator T () const
void SetRampTimeMs (float InNumRampCallsPerSecond, float InRampTimeMs)
void SetRampTimeMs (float InRampTimeMs)
void SnapToTarget ()
Additional Inherited Members
Protected Member Functions inherited from TRamper< T >
void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
FORCEINLINE void InitData ()
Protected Attributes inherited from TRamper< T >
FRamper::FCallback Callback
T CurrentValue
void * Data
T Increment
volatile bool IsSettingTarget
float NormalIncrement
float NumRampCallsPerSecond
float ProgressPct
T TargetValue
Detailed Description
template<typename T>
class TLinearRamper< T >
Definition at line 458 of file Ramper.h.
Constructor & Destructor Documentation
TLinearRamper()
template<typename T> TLinearRamper< T >::TLinearRamper (float InNumRampCallsPerSecond = 1.0f) inline explicit
Definition at line 462 of file Ramper.h.
References TRamper< T >::TRamper().
Referenced by operator=().
Member Function Documentation
operator=()
template<typename T> TLinearRamper< T > & TLinearRamper< T >::operator= (const T InValue) inline
Definition at line 512 of file Ramper.h.
References TLinearRamper(), and SetTarget().
Ramp()
template<typename T> bool TLinearRamper< T >::Ramp () inline
Definition at line 488 of file Ramper.h.
References TRamper< T >::CurrentValue, TRamper< T >::Increment, TRamper< T >::NormalIncrement, TRamper< T >::ProgressPct, and TRamper< T >::SnapToTarget().
SetTarget()
template<typename T> void TLinearRamper< T >::SetTarget (T InTarget, FRamper::FCallback InCallback = nullptr, void * InData = nullptr) inline
Definition at line 466 of file Ramper.h.
References TRamper< T >::Callback, TRamper< T >::CurrentValue, TRamper< T >::Data, TRamper< T >::Increment, TRamper< T >::IsSettingTarget, TRamper< T >::NormalIncrement, TRamper< T >::ProgressPct, and TRamper< T >::TargetValue.
Referenced by operator=(), and SnapTo().
SnapTo()
template<typename T> void TLinearRamper< T >::SnapTo (const T & InValue) inline
Definition at line 506 of file Ramper.h.
References SetTarget(), and TRamper< T >::SnapToTarget().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixDsp/Public/HarmonixDsp/Ramper.h