Unreal Engine 5.6 C++ API: UUVEditorTexelDensityToolBuilder Class Reference
UUVEditorTexelDensityToolBuilder Class Reference
#include "UVEditorTexelDensityTool.h"
Public Member Functions
virtual UInteractiveTool * BuildTool (const FToolBuilderState &SceneState) const override
virtual bool CanBuildTool (const FToolBuilderState &SceneState) const override
Data Fields
const TArray< TObjectPtr< UUVEditorToolMeshInput > > * Targets = nullptr
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Definition at line 35 of file UVEditorTexelDensityTool.h.
Member Function Documentation
BuildTool()
virtual UInteractiveTool * UUVEditorTexelDensityToolBuilder::BuildTool (const FToolBuilderState & SceneState) const override virtual
References BuildTool().
Referenced by BuildTool().
CanBuildTool()
virtual bool UUVEditorTexelDensityToolBuilder::CanBuildTool (const FToolBuilderState & SceneState) const override virtual
References CanBuildTool().
Referenced by CanBuildTool().
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorTexelDensityToolBuilder::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 37 of file UVEditorTexelDensityTool.h.
Targets
const TArray<TObjectPtr<UUVEditorToolMeshInput> >* UUVEditorTexelDensityToolBuilder::Targets = nullptr
Definition at line 45 of file UVEditorTexelDensityTool.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/UVEditorTexelDensityTool.h