Unreal Engine 5.6 C++ API: UE::Geometry::TIncrementalMeshDijkstra< PointSetType > Class Template Reference
UE::Geometry::TIncrementalMeshDijkstra< PointSetType > Class Template Reference
TIncrementalMeshDijkstra computes graph distances on a mesh from seed point(s) using Dijkstra's algorithm.
#include "IncrementalMeshDijkstra.h"
Data Structures
struct FGraphNode
struct FSeedPoint
FSeedPoint defines a seed point passed to the various compute methods below.
Public Member Functions
TIncrementalMeshDijkstra (const PointSetType *PointSetIn)
Construct TMeshDijkstra for the given PointSet.
void AddSeedPoints (const TArray< FSeedPoint > &SeedPointsIn)
Add new SeedPoints to the current solution, and then propagate updated graph distances to any points closer to these new seed points than to existing seed points.
int32 FindMaxGraphDistancePointID () const
bool FindPathToNearestSeed (int32 PointID, TArray< int32 > &PathToSeedOut, int32 MaxLength=100000)
Find path from a point to the nearest seed point.
double GetDistance (int32 PointID) const
int32 GetSeedExternalIDForPointSetID (int32 PointID)
bool HasDistance (int32 PointID) const
Static Public Member Functions
static double InvalidDistance ()
Data Fields
TUniqueFunction< FVector3d(int32)> GetPositionFunc
Return the 3D Position of a given Point in the PointSet.
const PointSetType * PointSet
PointSet we are calculating on.
Private Member Functions
void ForceInitializeAllNodes ()
FGraphNode * GetNodeForPointSetID (int32 PointSetID)
const FGraphNode * GetNodeForPointSetID (int32 PointSetID) const
void UpdateNeighboursSparse (FGraphNode *Parent)
Private Attributes
TArray< FGraphNode > AllocatedNodes
int32 CurrentSeedTimestamp = 0
const int32 InvalidFrozenTimestamp = -1
FIndexPriorityQueue Queue
TMap< int32, int32 > SeedPointExternalIDMap
TArray< FSeedPoint > SeedPoints
Detailed Description
template<class PointSetType>
class UE::Geometry::TIncrementalMeshDijkstra< PointSetType >
TIncrementalMeshDijkstra computes graph distances on a mesh from seed point(s) using Dijkstra's algorithm.
Derived from TMeshDijkstra. This Incremental variant allows adding new Seed points to an already-computed solution.
Definition at line 23 of file IncrementalMeshDijkstra.h.
Constructor & Destructor Documentation
TIncrementalMeshDijkstra()
template<class PointSetType> UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::TIncrementalMeshDijkstra (const PointSetType * PointSetIn) inline
Construct TMeshDijkstra for the given PointSet.
We will hold a reference to this PointSet for the lifetime of the class.
Definition at line 41 of file IncrementalMeshDijkstra.h.
References ForceInitializeAllNodes(), GetPositionFunc, PointSet, and Queue.
Member Function Documentation
AddSeedPoints()
template<class PointSetType> void UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::AddSeedPoints (const TArray< FSeedPoint > & SeedPointsIn) inline
Add new SeedPoints to the current solution, and then propagate updated graph distances to any points closer to these new seed points than to existing seed points.
Definition at line 74 of file IncrementalMeshDijkstra.h.
References check, CurrentSeedTimestamp, ensure, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::FrozenTimestamp, GetNodeForPointSetID(), UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, Queue, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::SeedID, SeedPointExternalIDMap, SeedPoints, and UpdateNeighboursSparse().
FindMaxGraphDistancePointID()
template<class PointSetType> int32 UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FindMaxGraphDistancePointID () const inline
Returns
vertex id associated with the maximum graph distance returned by GetMaxGraphDistance()
Definition at line 126 of file IncrementalMeshDijkstra.h.
References UE::Geometry::Distance(), GetDistance(), InvalidDistance(), and PointSet.
FindPathToNearestSeed()
template<class PointSetType> bool UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FindPathToNearestSeed (int32 PointID, TArray< int32 > & PathToSeedOut, int32 MaxLength = 100000) inline
Find path from a point to the nearest seed point.
Parameters
PointID starting point, assumption is that we have computed dijkstra to this point
PathToSeedOut path is returned here, includes PointID and seed point as last element
MaxLength if PathToSeedOut grows beyond this length, we abort the search
Returns
true if valid path was found
Definition at line 173 of file IncrementalMeshDijkstra.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::FrozenTimestamp, GetNodeForPointSetID(), InvalidFrozenTimestamp, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::ParentPointID, and TArray< InElementType, InAllocatorType >::Reset().
ForceInitializeAllNodes()
template<class PointSetType> void UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::ForceInitializeAllNodes () inline private
Definition at line 229 of file IncrementalMeshDijkstra.h.
References AllocatedNodes, InvalidDistance(), InvalidFrozenTimestamp, and PointSet.
Referenced by TIncrementalMeshDijkstra().
GetDistance()
template<class PointSetType> double UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::GetDistance (int32 PointID) const inline
Returns
the distance calculated for index PointID
Definition at line 160 of file IncrementalMeshDijkstra.h.
References UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::FrozenTimestamp, GetNodeForPointSetID(), UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, InvalidDistance(), and InvalidFrozenTimestamp.
Referenced by FindMaxGraphDistancePointID().
GetNodeForPointSetID() [1/2]
template<class PointSetType> FGraphNode * UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::GetNodeForPointSetID (int32 PointSetID) inline private
Definition at line 241 of file IncrementalMeshDijkstra.h.
References AllocatedNodes.
Referenced by AddSeedPoints(), FindPathToNearestSeed(), GetDistance(), GetSeedExternalIDForPointSetID(), HasDistance(), and UpdateNeighboursSparse().
GetNodeForPointSetID() [2/2]
template<class PointSetType> const FGraphNode * UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::GetNodeForPointSetID (int32 PointSetID) const inline private
Definition at line 246 of file IncrementalMeshDijkstra.h.
References AllocatedNodes.
GetSeedExternalIDForPointSetID()
template<class PointSetType> int32 UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::GetSeedExternalIDForPointSetID (int32 PointID) inline
Returns
the ExternalID of the SeedPoint that is closest to PointID, or -1 if PointID does not have a valid graph distance
Definition at line 111 of file IncrementalMeshDijkstra.h.
References UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::FrozenTimestamp, GetNodeForPointSetID(), InvalidFrozenTimestamp, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::SeedID, and SeedPoints.
HasDistance()
template<class PointSetType> bool UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::HasDistance (int32 PointID) const inline
Returns
true if the distance for index PointID was calculated
Definition at line 150 of file IncrementalMeshDijkstra.h.
References UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::FrozenTimestamp, GetNodeForPointSetID(), and InvalidFrozenTimestamp.
InvalidDistance()
template<class PointSetType> double UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::InvalidDistance () inline static
Definition at line 53 of file IncrementalMeshDijkstra.h.
Referenced by FindMaxGraphDistancePointID(), ForceInitializeAllNodes(), and GetDistance().
UpdateNeighboursSparse()
template<class PointSetType> void UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::UpdateNeighboursSparse (FGraphNode * Parent) inline private
Definition at line 255 of file IncrementalMeshDijkstra.h.
References CurrentSeedTimestamp, Distance, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::FrozenTimestamp, GetNodeForPointSetID(), GetPositionFunc, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, Parent, UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::ParentPointID, PointSet, Queue, and UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FGraphNode::SeedID.
Referenced by AddSeedPoints().
Field Documentation
AllocatedNodes
template<class PointSetType> TArray<FGraphNode> UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::AllocatedNodes private
Definition at line 217 of file IncrementalMeshDijkstra.h.
Referenced by ForceInitializeAllNodes(), GetNodeForPointSetID(), and GetNodeForPointSetID().
CurrentSeedTimestamp
template<class PointSetType> int32 UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::CurrentSeedTimestamp = 0 private
Definition at line 226 of file IncrementalMeshDijkstra.h.
Referenced by AddSeedPoints(), and UpdateNeighboursSparse().
GetPositionFunc
template<class PointSetType> TUniqueFunction<FVector3d(int32)> UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::GetPositionFunc
Return the 3D Position of a given Point in the PointSet.
This function is set to PointSet->GetVertex() in the constructor below, but can be replaced with an external function if necessary (eg to provide deformed mesh positions, etc)
Definition at line 34 of file IncrementalMeshDijkstra.h.
Referenced by TIncrementalMeshDijkstra(), and UpdateNeighboursSparse().
InvalidFrozenTimestamp
template<class PointSetType> const int32 UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::InvalidFrozenTimestamp = -1 private
Definition at line 225 of file IncrementalMeshDijkstra.h.
Referenced by FindPathToNearestSeed(), ForceInitializeAllNodes(), GetDistance(), GetSeedExternalIDForPointSetID(), and HasDistance().
PointSet
template<class PointSetType> const PointSetType* UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::PointSet
PointSet we are calculating on.
Definition at line 27 of file IncrementalMeshDijkstra.h.
Referenced by TIncrementalMeshDijkstra(), FindMaxGraphDistancePointID(), ForceInitializeAllNodes(), and UpdateNeighboursSparse().
Queue
template<class PointSetType> FIndexPriorityQueue UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::Queue private
Definition at line 220 of file IncrementalMeshDijkstra.h.
Referenced by TIncrementalMeshDijkstra(), AddSeedPoints(), and UpdateNeighboursSparse().
SeedPointExternalIDMap
template<class PointSetType> TMap<int32, int32> UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::SeedPointExternalIDMap private
Definition at line 223 of file IncrementalMeshDijkstra.h.
Referenced by AddSeedPoints().
SeedPoints
template<class PointSetType> TArray<FSeedPoint> UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::SeedPoints private
Definition at line 222 of file IncrementalMeshDijkstra.h.
Referenced by AddSeedPoints(), and GetSeedExternalIDForPointSetID().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Parameterization/IncrementalMeshDijkstra.h