Unreal Engine 5.6 C++ API: TWeakChild< ChildType > Class Template Reference
TWeakChild< ChildType > Class Template Reference final
For widgets that do not own their content, but are responsible for presenting someone else's content.
#include "Children.h"
Public Member Functions
void AttachWidget (const TSharedPtr< SWidget > &InWidget)
void DetachWidget ()
FChildren (std::nullptr_t)=delete
FChildren (SWidget *InOwner)
FChildren (SWidget *InOwner, FName InName)
virtual TSharedRef< const SWidget > GetChildAt (int32 ChildIndex) const override
virtual TSharedRef< SWidget > GetChildAt (int32 ChildIndex) override
TSharedRef< SWidget > GetWidget () const
virtual int32 Num () const override
Public Member Functions inherited from FChildren
FChildren (std::nullptr_t)=delete
FChildren (SWidget *InOwner)
FChildren (SWidget *InOwner, FName InName)
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred)
Applies the predicate to all the widgets contained by the FChildren.
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred) const
Applies the predicate to all the widgets contained by the FChildren.
FName GetName () const
Option to give a name to Children to SlotAttribute purposes or for debugging.
SWidget & GetOwner () const
void * operator new (size_t)=delete
void * operator new[] (size_t)=delete
virtual bool SupportSlotWithSlateAttribute () const
Private Member Functions
virtual FConstWidgetRef GetChildRefAt (int32 ChildIndex) const override
virtual FWidgetRef GetChildRefAt (int32 ChildIndex) override
virtual const FSlotBase & GetSlotAt (int32 ChildIndex) const override
virtual int32 NumSlot () const override
Private Attributes
TWeakPtr< ChildType > WidgetPtr
Additional Inherited Members
Protected Types inherited from FChildren
enum ECopyConstruct { CopyConstruct }
enum ERefConstruct { ReferenceConstruct }
Protected Member Functions inherited from FChildren
virtual ~FChildren ()
void Debug_TestDestroyTag () const
Detailed Description
template<typename ChildType>
class TWeakChild< ChildType >
For widgets that do not own their content, but are responsible for presenting someone else's content.
e.g. Tooltips are just presented by the owner window; not actually owned by it. They can go away at any time and then they'll just stop being shown.
Definition at line 211 of file Children.h.
Member Function Documentation
AttachWidget()
template<typename ChildType> void TWeakChild< ChildType >::AttachWidget (const TSharedPtr< SWidget > & InWidget) inline
Definition at line 260 of file Children.h.
References ChildOrder, FChildren::GetOwner(), SWidget::Invalidate(), TSharedPtr< ObjectType, InMode >::IsValid(), SNullWidget::NullWidget, and WidgetPtr.
DetachWidget()
template<typename ChildType> void TWeakChild< ChildType >::DetachWidget () inline
Definition at line 274 of file Children.h.
References FChildren::GetOwner(), SNullWidget::NullWidget, and WidgetPtr.
FChildren() [1/3]
template<typename ChildType> FChildren::FChildren (std::nullptr_t) delete
FChildren() [2/3]
template<typename ChildType> FChildren::FChildren (SWidget * InOwner) inline
Definition at line 29 of file ChildrenBase.h.
FChildren() [3/3]
template<typename ChildType> FChildren::FChildren (SWidget * InOwner, FName InName) inline
Definition at line 35 of file ChildrenBase.h.
GetChildAt() [1/2]
template<typename ChildType> virtual TSharedRef< const SWidget > TWeakChild< ChildType >::GetChildAt (int32 Index) const inline override virtual
Returns
const pointer to the Widget at the specified Index.
Implements FChildren.
Definition at line 227 of file Children.h.
References check, and GetWidget().
GetChildAt() [2/2]
template<typename ChildType> virtual TSharedRef< SWidget > TWeakChild< ChildType >::GetChildAt (int32 Index) inline override virtual
Returns
pointer to the Widget at the specified Index.
Implements FChildren.
Definition at line 221 of file Children.h.
References check, and GetWidget().
GetChildRefAt() [1/2]
template<typename ChildType> virtual FConstWidgetRef TWeakChild< ChildType >::GetChildRefAt (int32 Index) const inline override private virtual
Returns
ref to the Widget at the specified Index.
Implements FChildren.
Definition at line 252 of file Children.h.
References check, FChildren::CopyConstruct, TSharedPtr< ObjectType, InMode >::IsValid(), SNullWidget::NullWidget, FChildren::ReferenceConstruct, TSharedPtr< ObjectType, InMode >::ToSharedRef(), and WidgetPtr.
GetChildRefAt() [2/2]
template<typename ChildType> virtual FWidgetRef TWeakChild< ChildType >::GetChildRefAt (int32 Index) inline override private virtual
Returns
ref to the Widget at the specified Index.
Implements FChildren.
Definition at line 246 of file Children.h.
References check, FChildren::CopyConstruct, TSharedPtr< ObjectType, InMode >::IsValid(), SNullWidget::NullWidget, FChildren::ReferenceConstruct, TSharedPtr< ObjectType, InMode >::ToSharedRef(), and WidgetPtr.
GetSlotAt()
template<typename ChildType> virtual const FSlotBase & TWeakChild< ChildType >::GetSlotAt (int32 ChildIndex) const inline override private virtual
Returns
the const reference to the slot at the specified Index
Implements FChildren.
Definition at line 239 of file Children.h.
References check.
GetWidget()
template<typename ChildType> TSharedRef< SWidget > TWeakChild< ChildType >::GetWidget () const inline
Definition at line 287 of file Children.h.
References ensure, TSharedPtr< ObjectType, InMode >::IsValid(), SNullWidget::NullWidget, Num(), TSharedPtr< ObjectType, InMode >::ToSharedRef(), and WidgetPtr.
Referenced by GetChildAt(), and GetChildAt().
Num()
template<typename ChildType> virtual int32 TWeakChild< ChildType >::Num () const inline override virtual
Returns
the number of children
Implements FChildren.
Definition at line 216 of file Children.h.
References WidgetPtr.
Referenced by GetWidget().
NumSlot()
template<typename ChildType> virtual int32 TWeakChild< ChildType >::NumSlot () const inline override private virtual
Returns
the number of slot the children has.
Reimplemented from FChildren.
Definition at line 234 of file Children.h.
Field Documentation
WidgetPtr
template<typename ChildType> TWeakPtr<ChildType> TWeakChild< ChildType >::WidgetPtr private
Definition at line 295 of file Children.h.
Referenced by AttachWidget(), DetachWidget(), GetChildRefAt(), GetChildRefAt(), GetWidget(), and Num().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Layout/Children.h