Unreal Engine 5.6 C++ API: ICurveEditorModule Class Reference
ICurveEditorModule Class Reference abstract
Interface for the Curve Editor module.
#include "ICurveEditorModule.h"
Public Member Functions
virtual ~ICurveEditorModule ()
DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< FExtender >, FCurveEditorMenuExtender, const TSharedRef< FUICommandList >)
virtual TArray< FCurveEditorMenuExtender > & GetAllToolBarMenuExtenders ()=0
virtual TArrayView< const FOnCreateCurveEditorExtension > GetEditorExtensions () const =0
virtual TSharedPtr< UE::CurveEditor::FPromotedFilterContainer > GetGlobalToolbarPromotedFilters () const =0
virtual TArrayView< const FOnCreateCurveEditorToolExtension > GetToolExtensions () const =0
virtual FDelegateHandle RegisterEditorExtension (FOnCreateCurveEditorExtension InOnCreateCurveEditorExtension)=0
virtual FDelegateHandle RegisterToolExtension (FOnCreateCurveEditorToolExtension InOnCreateCurveEditorToolExtension)=0
virtual ECurveEditorViewID RegisterView (FOnCreateCurveEditorView InCreateViewDelegate)=0
Register a new view factory function that can be used on the curve editor when relevant curves are found.
virtual void UnregisterEditorExtension (FDelegateHandle InHandle)=0
virtual void UnregisterToolExtension (FDelegateHandle InHandle)=0
virtual void UnregisterView (ECurveEditorViewID InViewID)=0
Unregister a previously registered view type.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static ICurveEditorModule & Get ()
static bool IsAvailable ()
Detailed Description
Interface for the Curve Editor module.
Definition at line 48 of file ICurveEditorModule.h.
Constructor & Destructor Documentation
~ICurveEditorModule()
virtual ICurveEditorModule::~ICurveEditorModule () inline virtual
Definition at line 62 of file ICurveEditorModule.h.
Member Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
ICurveEditorModule::DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< FExtender > , FCurveEditorMenuExtender , const TSharedRef< FUICommandList >)
Get()
ICurveEditorModule & ICurveEditorModule::Get () inline static
Definition at line 52 of file ICurveEditorModule.h.
References FModuleManager::Get(), and FModuleManager::GetModuleChecked().
GetAllToolBarMenuExtenders()
virtual TArray< FCurveEditorMenuExtender > & ICurveEditorModule::GetAllToolBarMenuExtenders () pure virtual
GetEditorExtensions()
virtual TArrayView< const FOnCreateCurveEditorExtension > ICurveEditorModule::GetEditorExtensions () const pure virtual
GetGlobalToolbarPromotedFilters()
virtual TSharedPtr< UE::CurveEditor::FPromotedFilterContainer > ICurveEditorModule::GetGlobalToolbarPromotedFilters () const pure virtual
Returns
The global setting of which filters should be promoted to the toolbar in the curve editor.
GetToolExtensions()
virtual TArrayView< const FOnCreateCurveEditorToolExtension > ICurveEditorModule::GetToolExtensions () const pure virtual
IsAvailable()
bool ICurveEditorModule::IsAvailable () inline static
Definition at line 56 of file ICurveEditorModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
RegisterEditorExtension()
virtual FDelegateHandle ICurveEditorModule::RegisterEditorExtension (FOnCreateCurveEditorExtension InOnCreateCurveEditorExtension) pure virtual
RegisterToolExtension()
virtual FDelegateHandle ICurveEditorModule::RegisterToolExtension (FOnCreateCurveEditorToolExtension InOnCreateCurveEditorToolExtension) pure virtual
RegisterView()
virtual ECurveEditorViewID ICurveEditorModule::RegisterView (FOnCreateCurveEditorView InCreateViewDelegate) pure virtual
Register a new view factory function that can be used on the curve editor when relevant curves are found.
Note
: A maximum of 64 registered view types are supported. View type IDs are not recycled.
Parameters
InCreateViewDelegate (required) A bound delegate that creates a new instance of the view widget. Delegate signature is TSharedRef<SCurveEditorView> Function(TWeakPtr<FCurveEditor>);
Returns
A new custom view ID that identifies the registered view type. Any curve models that wish to support this view must |= this enum to its FCurveModel::SupportedViews;
UnregisterEditorExtension()
virtual void ICurveEditorModule::UnregisterEditorExtension (FDelegateHandle InHandle) pure virtual
UnregisterToolExtension()
virtual void ICurveEditorModule::UnregisterToolExtension (FDelegateHandle InHandle) pure virtual
UnregisterView()
virtual void ICurveEditorModule::UnregisterView (ECurveEditorViewID InViewID) pure virtual
Unregister a previously registered view type.
Parameters
InViewID The view ID obtained from calling RegisterCustomView. Must be >= ECurveEditorViewID::CUSTOM_START
The documentation for this class was generated from the following file:
Editor/CurveEditor/Public/ICurveEditorModule.h