Unreal Engine 5.6 C++ API: SHeaderRow::FColumn Class Reference
SHeaderRow::FColumn Class Reference
Describes a single column header.
#include "SHeaderRow.h"
Public Member Functions
float GetWidth () const
void SetWidth (float NewWidth)
DefaultLabel ToolTip FixedWidth FillSized HeaderContent SLATE_ARGUMENT (EHorizontalAlignment, HAlignHeader) SLATE_ARGUMENT(EVerticalAlignment
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader HeaderComboVisibility OnGetMenuContent HAlignCell SLATE_ARGUMENT (EVerticalAlignment, VAlignCell) SLATE_ATTRIBUTE(EColumnSortMode
SLATE_ARGUMENT (FName, ColumnId) SLATE_ATTRIBUTE(FText
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader SLATE_ARGUMENT (TOptional< FMargin >, HeaderContentPadding) SLATE_ARGUMENT(EHeaderComboVisibility
DefaultLabel ToolTip SLATE_ATTRIBUTE (float, FillWidth) SLATE_ARGUMENT(TOptional< float >
Set the Column Size Mode to Fill.
DefaultLabel ToolTip FixedWidth SLATE_ATTRIBUTE (float, ManualWidth) SLATE_ARGUMENT(TOptional< float >
Set the Column Size Mode to Manual.
DefaultLabel SLATE_ATTRIBUTE (FText, DefaultTooltip) SLATE_ATTRIBUTE(TSharedPtr< IToolTip >
SLATE_BEGIN_ARGS (FColumn)
DefaultLabel ToolTip FixedWidth FillSized SLATE_EVENT (FOnWidthChanged, OnWidthChanged) SLATE_DEFAULT_SLOT(FArguments
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader HeaderComboVisibility OnGetMenuContent SLATE_EVENT (FPointerEventHandler, OnColumnSplitterDoubleClick) SLATE_ARGUMENT(EHorizontalAlignment
Allow to provide a custom handler when a splitter is double-clicked in Manual column size mode.
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader HeaderComboVisibility SLATE_NAMED_SLOT (FArguments, MenuContent) SLATE_EVENT(FOnGetContent
Data Fields
bool bIsVisible
EHorizontalAlignment CellHAlignment
EVerticalAlignment CellVAlignment
FName ColumnId
A unique ID for this column, so that it can be saved and restored.
TAttribute< FText > DefaultText
Default text to use if no widget is passed in.
TAttribute< FText > DefaultTooltip
Default tooltip to use if no widget is passed in.
float DefaultWidth
A original column width in Slate Units.
EHeaderComboVisibility HeaderComboVisibility
TAlwaysValidWidget HeaderContent
TOptional< FMargin > HeaderContentPadding
EHorizontalAlignment HeaderHAlignment
TAlwaysValidWidget HeaderMenuContent
EVerticalAlignment HeaderVAlignment
TAttribute< EColumnSortMode::Type > InitialSortMode
TAttribute< bool > IsSorting
FPointerEventHandler OnColumnSplitterDoubleClick
FOnGetContent OnGetMenuContent
FOnSortModeChanged OnSortModeChanged
FOnWidthChanged OnWidthChanged
ETextOverflowPolicy OverflowPolicy
TAttribute< bool > ShouldGenerateWidget
EColumnSizeMode::Type SizeRule
TAttribute< EColumnSortMode::Type > SortMode
TAttribute< EColumnSortPriority::Type > SortPriority
TAttribute< TSharedPtr< IToolTip > > ToolTip
Custom tooltip to use.
TAttribute< float > Width
A column width in Slate Units.
Detailed Description
Describes a single column header.
Definition at line 100 of file SHeaderRow.h.
Member Function Documentation
GetWidth()
float SHeaderRow::FColumn::GetWidth () const inline
Definition at line 233 of file SHeaderRow.h.
References Width.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns().
SetWidth()
void SHeaderRow::FColumn::SetWidth (float NewWidth) inline
Definition at line 221 of file SHeaderRow.h.
References OnWidthChanged, and Width.
SLATE_ARGUMENT() [1/4]
DefaultLabel ToolTip FixedWidth FillSized HeaderContent SHeaderRow::FColumn::SLATE_ARGUMENT (EHorizontalAlignment , HAlignHeader)
References SLATE_ARGUMENT().
SLATE_ARGUMENT() [2/4]
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader HeaderComboVisibility OnGetMenuContent HAlignCell SHeaderRow::FColumn::SLATE_ARGUMENT (EVerticalAlignment , VAlignCell) inline
Definition at line 155 of file SHeaderRow.h.
References bIsVisible, CellHAlignment, CellVAlignment, ColumnId, DefaultText, DefaultTooltip, DefaultWidth, HeaderComboVisibility, HeaderContent, HeaderContentPadding, HeaderHAlignment, HeaderMenuContent, HeaderVAlignment, InitialSortMode, IsSorting, OnColumnSplitterDoubleClick, OnGetMenuContent, OnSortModeChanged, OnWidthChanged, OverflowPolicy, ShouldGenerateWidget, SizeRule, SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SBorder::SLATE_END_ARGS(), SLATE_EVENT(), SortMode, SortPriority, ToolTip, and Width.
SLATE_ARGUMENT() [3/4]
SHeaderRow::FColumn::SLATE_ARGUMENT (FName , ColumnId)
References ColumnId.
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ARGUMENT() [4/4]
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader SHeaderRow::FColumn::SLATE_ARGUMENT (TOptional< FMargin > , HeaderContentPadding)
References HeaderComboVisibility, HeaderContentPadding, and SLATE_ARGUMENT().
SLATE_ATTRIBUTE() [1/3]
DefaultLabel ToolTip SHeaderRow::FColumn::SLATE_ATTRIBUTE (float , FillWidth)
Set the Column Size Mode to Fill.
It's a fraction between 0 and 1 Set the Column Size Mode to Fixed.
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/3]
DefaultLabel ToolTip FixedWidth SHeaderRow::FColumn::SLATE_ATTRIBUTE (float , ManualWidth)
Set the Column Size Mode to Manual.
Set the Column Size Mode to Fill Sized.
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/3]
DefaultLabel SHeaderRow::FColumn::SLATE_ATTRIBUTE (FText , DefaultTooltip)
References DefaultTooltip, SLATE_ATTRIBUTE(), and ToolTip.
Referenced by SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SHeaderRow::FColumn::SLATE_BEGIN_ARGS (FColumn) inline
Definition at line 104 of file SHeaderRow.h.
References Ascending, None, and OnHover.
SLATE_EVENT() [1/2]
DefaultLabel ToolTip FixedWidth FillSized SHeaderRow::FColumn::SLATE_EVENT (FOnWidthChanged , OnWidthChanged)
References HeaderContent, OnWidthChanged, SBorder::SLATE_DEFAULT_SLOT(), and SLATE_EVENT().
Referenced by SLATE_ARGUMENT(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_NAMED_SLOT().
SLATE_EVENT() [2/2]
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader HeaderComboVisibility OnGetMenuContent SHeaderRow::FColumn::SLATE_EVENT (FPointerEventHandler , OnColumnSplitterDoubleClick)
Allow to provide a custom handler when a splitter is double-clicked in Manual column size mode.
References OnColumnSplitterDoubleClick, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_NAMED_SLOT()
DefaultLabel ToolTip FixedWidth FillSized HeaderContent VAlignHeader HeaderComboVisibility SHeaderRow::FColumn::SLATE_NAMED_SLOT (FArguments , MenuContent)
References OnGetMenuContent, SLATE_EVENT(), and SLATE_NAMED_SLOT().
Referenced by SLATE_NAMED_SLOT().
Field Documentation
bIsVisible
bool SHeaderRow::FColumn::bIsVisible
Definition at line 283 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
CellHAlignment
EHorizontalAlignment SHeaderRow::FColumn::CellHAlignment
Definition at line 271 of file SHeaderRow.h.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns(), and SLATE_ARGUMENT().
CellVAlignment
EVerticalAlignment SHeaderRow::FColumn::CellVAlignment
Definition at line 272 of file SHeaderRow.h.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns(), and SLATE_ARGUMENT().
ColumnId
FName SHeaderRow::FColumn::ColumnId
A unique ID for this column, so that it can be saved and restored.
Definition at line 239 of file SHeaderRow.h.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns(), SLATE_ARGUMENT(), and SLATE_ARGUMENT().
DefaultText
TAttribute< FText > SHeaderRow::FColumn::DefaultText
Default text to use if no widget is passed in.
Definition at line 242 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
DefaultTooltip
TAttribute< FText > SHeaderRow::FColumn::DefaultTooltip
Default tooltip to use if no widget is passed in.
Definition at line 245 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
DefaultWidth
float SHeaderRow::FColumn::DefaultWidth
A original column width in Slate Units.
Definition at line 254 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
HeaderComboVisibility
EHeaderComboVisibility SHeaderRow::FColumn::HeaderComboVisibility
Definition at line 269 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_ARGUMENT().
HeaderContent
TAlwaysValidWidget SHeaderRow::FColumn::HeaderContent
Definition at line 260 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_EVENT().
HeaderContentPadding
TOptional< FMargin > SHeaderRow::FColumn::HeaderContentPadding
Definition at line 268 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_ARGUMENT().
HeaderHAlignment
EHorizontalAlignment SHeaderRow::FColumn::HeaderHAlignment
Definition at line 266 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
HeaderMenuContent
TAlwaysValidWidget SHeaderRow::FColumn::HeaderMenuContent
Definition at line 261 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
HeaderVAlignment
EVerticalAlignment SHeaderRow::FColumn::HeaderVAlignment
Definition at line 267 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
InitialSortMode
TAttribute< EColumnSortMode::Type > SHeaderRow::FColumn::InitialSortMode
Definition at line 276 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
IsSorting
TAttribute< bool > SHeaderRow::FColumn::IsSorting
Definition at line 279 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
OnColumnSplitterDoubleClick
FPointerEventHandler SHeaderRow::FColumn::OnColumnSplitterDoubleClick
Definition at line 264 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_EVENT().
OnGetMenuContent
FOnGetContent SHeaderRow::FColumn::OnGetMenuContent
Definition at line 263 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_NAMED_SLOT().
OnSortModeChanged
FOnSortModeChanged SHeaderRow::FColumn::OnSortModeChanged
Definition at line 280 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
OnWidthChanged
FOnWidthChanged SHeaderRow::FColumn::OnWidthChanged
Definition at line 256 of file SHeaderRow.h.
Referenced by SetWidth(), SLATE_ARGUMENT(), and SLATE_EVENT().
OverflowPolicy
ETextOverflowPolicy SHeaderRow::FColumn::OverflowPolicy
Definition at line 274 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
ShouldGenerateWidget
TAttribute<bool> SHeaderRow::FColumn::ShouldGenerateWidget
Definition at line 282 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
SizeRule
EColumnSizeMode::Type SHeaderRow::FColumn::SizeRule
Definition at line 258 of file SHeaderRow.h.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns(), and SLATE_ARGUMENT().
SortMode
TAttribute< EColumnSortMode::Type > SHeaderRow::FColumn::SortMode
Definition at line 277 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
SortPriority
TAttribute< EColumnSortPriority::Type > SHeaderRow::FColumn::SortPriority
Definition at line 278 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT().
ToolTip
TAttribute< TSharedPtr< IToolTip > > SHeaderRow::FColumn::ToolTip
Custom tooltip to use.
Definition at line 248 of file SHeaderRow.h.
Referenced by SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Width
TAttribute< float > SHeaderRow::FColumn::Width
A column width in Slate Units.
Definition at line 251 of file SHeaderRow.h.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns(), GetWidth(), SetWidth(), and SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Views/SHeaderRow.h