Unreal Engine 5.6 C++ API: UE::Sequencer::ISequencerCoreModule Class Reference
UE::Sequencer::ISequencerCoreModule Class Reference abstract
Interface for the Sequencer module.
#include "ISequencerCoreModule.h"
Public Member Functions
virtual TSharedPtr< FViewModel > FactoryNewModel (UObject *Object) const =0
Attempt to create a new model type for the specified object.
virtual FDelegateHandle RegisterModelType (const TWeakObjectPtr< UClass > &WeakClass, TFunction< TSharedPtr< FViewModel >(UObject *)> FactoryFunctor)=0
Register a new MVVM view model type factory functor that will be used for any UObjects of the specified class type.
template<typename T>
FDelegateHandle RegisterModelType (const TWeakObjectPtr< UClass > &WeakClass, TViewModelTypeID< T > Type)
Register a new MVVM view model type from a view model type ID that will be used for any UObjects of the specified class type.
virtual void UnRegisterModelType (FDelegateHandle Handle)=0
Unregister a previously registered view model type.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Private Member Functions
SEQUENCERCORE_API void InitializeObjectModel (const FViewModelPtr &ViewModel, UObject *Object)
Detailed Description
Interface for the Sequencer module.
Definition at line 19 of file ISequencerCoreModule.h.
Member Function Documentation
FactoryNewModel()
virtual TSharedPtr< FViewModel > UE::Sequencer::ISequencerCoreModule::FactoryNewModel (UObject * Object) const pure virtual
Attempt to create a new model type for the specified object.
Parameters
Object The object to create a view model for
Returns
A pointer to a new view-model, or nullptr if the object didn't match any registered class.
InitializeObjectModel()
SEQUENCERCORE_API void UE::Sequencer::ISequencerCoreModule::InitializeObjectModel (const FViewModelPtr & ViewModel, UObject * Object) private
Referenced by RegisterModelType().
RegisterModelType() [1/2]
virtual FDelegateHandle UE::Sequencer::ISequencerCoreModule::RegisterModelType (const TWeakObjectPtr< UClass > & WeakClass, TFunction< TSharedPtr< FViewModel >(UObject *)> FactoryFunctor) pure virtual
Register a new MVVM view model type factory functor that will be used for any UObjects of the specified class type.
Note
It is a violation to attempt to register multiple functors for the same class type
Parameters
WeakClass A weak pointer to the class type that should invoke this factory
FactoryFunctor The functor that defines how to create a view model for the object
Returns
A delegate handle that can be passed to UnRegisterModelType to unregister this factory
Referenced by RegisterModelType().
RegisterModelType() [2/2]
template<typename T> FDelegateHandle UE::Sequencer::ISequencerCoreModule::RegisterModelType (const TWeakObjectPtr< UClass > & WeakClass, TViewModelTypeID< T > Type) inline
Register a new MVVM view model type from a view model type ID that will be used for any UObjects of the specified class type.
Parameters
Object The object to create a view model for
Type The view model type ID to create for UObjects of type WeakClass
Returns
A delegate handle that can be passed to UnRegisterModelType to unregister this factory
Definition at line 63 of file ISequencerCoreModule.h.
References InitializeObjectModel(), MakeShared(), and RegisterModelType().
UnRegisterModelType()
virtual void UE::Sequencer::ISequencerCoreModule::UnRegisterModelType (FDelegateHandle Handle) pure virtual
Unregister a previously registered view model type.
Parameters
Handle The handle to the factory functor that was provided from calling RegisterModelType
References Handle.
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/ISequencerCoreModule.h