Unreal Engine 5.6 C++ API: FIoStatus Class Reference
FIoStatus Class Reference
I/O status with error code and message.
#include "IoStatus.h"
Public Types
using FErrorMessage = TCHAR[MaxErrorMessageLength]
Public Member Functions
FIoStatus ()
FIoStatus (EIoErrorCode Code)
FIoStatus (EIoErrorCode Code, const FStringView &InErrorMessage)
~FIoStatus ()
EIoErrorCode GetErrorCode () const
const FErrorMessage & GetErrorMessage () const
bool IsCompleted () const
bool IsOk () const
bool operator!= (const FIoStatus &Other) const
FIoStatus & operator= (const EIoErrorCode InErrorCode)
FIoStatus & operator= (const FIoStatus &Other)
bool operator== (const FIoStatus &Other) const
FString ToString () const
Static Public Attributes
static const FIoStatus Invalid
static constexpr int32 MaxErrorMessageLength = 128
static const FIoStatus Ok
static const FIoStatus Unknown
Private Attributes
EIoErrorCode ErrorCode = EIoErrorCode::Ok
FErrorMessage ErrorMessage
Friends
class FIoStatusBuilder
Detailed Description
I/O status with error code and message.
Definition at line 50 of file IoStatus.h.
Member Typedef Documentation
FErrorMessage
using FIoStatus::FErrorMessage = TCHAR[MaxErrorMessageLength]
Definition at line 74 of file IoStatus.h.
Constructor & Destructor Documentation
FIoStatus() [1/3]
FIoStatus::FIoStatus ()
Referenced by operator!=(), operator=(), operator=(), and operator==().
~FIoStatus()
FIoStatus::~FIoStatus ()
FIoStatus() [2/3]
FIoStatus::FIoStatus (EIoErrorCode Code, const FStringView & InErrorMessage)
FIoStatus() [3/3]
FIoStatus::FIoStatus (EIoErrorCode Code)
Member Function Documentation
GetErrorCode()
EIoErrorCode FIoStatus::GetErrorCode () const inline
Definition at line 66 of file IoStatus.h.
References ErrorCode.
GetErrorMessage()
const FErrorMessage & FIoStatus::GetErrorMessage () const inline
Definition at line 76 of file IoStatus.h.
References ErrorMessage.
IsCompleted()
bool FIoStatus::IsCompleted () const inline
Definition at line 65 of file IoStatus.h.
References ErrorCode, and Unknown.
IsOk()
bool FIoStatus::IsOk () const inline
Definition at line 64 of file IoStatus.h.
References ErrorCode, and Ok.
Referenced by TIoStatusOr< T >::TIoStatusOr(), UE::FPlatformIoDispatcherBase::Initialize(), and TIoStatusOr< T >::operator=().
operator!=()
bool FIoStatus::operator!= (const FIoStatus & Other) const inline
Definition at line 62 of file IoStatus.h.
References FIoStatus(), operator==(), and Other.
operator=() [1/2]
FIoStatus & FIoStatus::operator= (const EIoErrorCode InErrorCode)
References FIoStatus().
operator=() [2/2]
FIoStatus & FIoStatus::operator= (const FIoStatus & Other)
References FIoStatus(), and Other.
operator==()
bool FIoStatus::operator== (const FIoStatus & Other) const
References FIoStatus(), and Other.
Referenced by operator!=().
ToString()
FString FIoStatus::ToString () const
Friends And Related Symbol Documentation
FIoStatusBuilder
friend class FIoStatusBuilder friend
Definition at line 81 of file IoStatus.h.
References FIoStatusBuilder.
Referenced by FIoStatusBuilder.
Field Documentation
ErrorCode
EIoErrorCode FIoStatus::ErrorCode = EIoErrorCode::Ok private
Definition at line 78 of file IoStatus.h.
Referenced by GetErrorCode(), IsCompleted(), and IsOk().
ErrorMessage
FErrorMessage FIoStatus::ErrorMessage private
Definition at line 79 of file IoStatus.h.
Referenced by GetErrorMessage().
Invalid
const FIoStatus FIoStatus::Invalid static
Definition at line 71 of file IoStatus.h.
MaxErrorMessageLength
int32 FIoStatus::MaxErrorMessageLength = 128 static constexpr
Definition at line 73 of file IoStatus.h.
Ok
const FIoStatus FIoStatus::Ok static
Definition at line 69 of file IoStatus.h.
Referenced by TIoStatusOr< T >::TIoStatusOr(), TIoStatusOr< T >::TIoStatusOr(), TIoStatusOr< T >::TIoStatusOr(), UE::FGenericPlatformIoDispatcher::CloseFile(), UE::FGenericPlatformIoDispatcher::OnInitialize(), and UE::FPlatformIoDispatcherBase::OnInitialize().
Unknown
const FIoStatus FIoStatus::Unknown static
Definition at line 70 of file IoStatus.h.
Referenced by TIoStatusOr< T >::ConsumeValueOrDie().
The documentation for this class was generated from the following file:
Runtime/Core/Public/IO/IoStatus.h