Unreal Engine 5.6 C++ API: UE::PixelStreaming2::FEpicRtcFrameDependencyStructure Class Reference
UE::PixelStreaming2::FEpicRtcFrameDependencyStructure Class Reference
#include "EpicRtcVideoCommon.h"
Public Member Functions
FEpicRtcFrameDependencyStructure (const FFrameDependencyStructure &FrameDependencyStructure)
virtual ~FEpicRtcFrameDependencyStructure ()=default
virtual EpicRtcInt32ArrayInterface * GetDecodeTargetProtectedByChain () override
virtual int32_t GetNumChains () override
virtual int32_t GetNumDecodeTargets () override
virtual EpicRtcVideoResolutionArrayInterface * GetResolutions () override
virtual int32_t GetStructureId () override
virtual EpicRtcGenericFrameInfoArrayInterface * GetTemplates () override
Private Attributes
TRefCountPtr< FEpicRtcInt32Array > DecodeTargetProtectedByChain
int NumChains
int NumDecodeTargets
TRefCountPtr< FEpicRtcVideoResolutionArray > Resolutions
int StructureId
TRefCountPtr< FEpicRtcGenericFrameInfoArray > Templates
Friends
bool operator== (FEpicRtcFrameDependencyStructure &Lhs, FEpicRtcFrameDependencyStructure &Rhs)
Detailed Description
Definition at line 920 of file EpicRtcVideoCommon.h.
Constructor & Destructor Documentation
FEpicRtcFrameDependencyStructure()
UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::FEpicRtcFrameDependencyStructure (const FFrameDependencyStructure & FrameDependencyStructure) inline
Definition at line 923 of file EpicRtcVideoCommon.h.
References DecodeTargetProtectedByChain, MakeRefCount(), NumChains, NumDecodeTargets, Resolutions, TArray< InElementType, InAllocatorType >::SetNum(), StructureId, and Templates.
Referenced by operator==.
~FEpicRtcFrameDependencyStructure()
virtual UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::~FEpicRtcFrameDependencyStructure () virtual default
Member Function Documentation
GetDecodeTargetProtectedByChain()
virtual EpicRtcInt32ArrayInterface * UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::GetDecodeTargetProtectedByChain () inline override virtual
Definition at line 953 of file EpicRtcVideoCommon.h.
References DecodeTargetProtectedByChain.
Referenced by operator==.
GetNumChains()
virtual int32_t UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::GetNumChains () inline override virtual
Definition at line 952 of file EpicRtcVideoCommon.h.
References NumChains.
GetNumDecodeTargets()
virtual int32_t UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::GetNumDecodeTargets () inline override virtual
Definition at line 951 of file EpicRtcVideoCommon.h.
References NumDecodeTargets.
GetResolutions()
virtual EpicRtcVideoResolutionArrayInterface * UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::GetResolutions () inline override virtual
Definition at line 954 of file EpicRtcVideoCommon.h.
References Resolutions.
Referenced by operator==.
GetStructureId()
virtual int32_t UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::GetStructureId () inline override virtual
Definition at line 950 of file EpicRtcVideoCommon.h.
References StructureId.
GetTemplates()
virtual EpicRtcGenericFrameInfoArrayInterface * UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::GetTemplates () inline override virtual
Definition at line 955 of file EpicRtcVideoCommon.h.
References Templates.
Referenced by operator==.
Friends And Related Symbol Documentation
operator==
bool operator== (FEpicRtcFrameDependencyStructure & Lhs, FEpicRtcFrameDependencyStructure & Rhs) friend
Definition at line 957 of file EpicRtcVideoCommon.h.
References FEpicRtcFrameDependencyStructure(), GetDecodeTargetProtectedByChain(), GetResolutions(), GetTemplates(), NumChains, and NumDecodeTargets.
Field Documentation
DecodeTargetProtectedByChain
TRefCountPtr<FEpicRtcInt32Array> UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::DecodeTargetProtectedByChain private
Definition at line 979 of file EpicRtcVideoCommon.h.
Referenced by FEpicRtcFrameDependencyStructure(), and GetDecodeTargetProtectedByChain().
NumChains
int UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::NumChains private
Definition at line 978 of file EpicRtcVideoCommon.h.
Referenced by FEpicRtcFrameDependencyStructure(), GetNumChains(), and operator==.
NumDecodeTargets
int UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::NumDecodeTargets private
Definition at line 977 of file EpicRtcVideoCommon.h.
Referenced by FEpicRtcFrameDependencyStructure(), GetNumDecodeTargets(), and operator==.
Resolutions
TRefCountPtr<FEpicRtcVideoResolutionArray> UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::Resolutions private
Definition at line 980 of file EpicRtcVideoCommon.h.
Referenced by FEpicRtcFrameDependencyStructure(), and GetResolutions().
StructureId
int UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::StructureId private
Definition at line 976 of file EpicRtcVideoCommon.h.
Referenced by FEpicRtcFrameDependencyStructure(), and GetStructureId().
Templates
TRefCountPtr<FEpicRtcGenericFrameInfoArray> UE::PixelStreaming2::FEpicRtcFrameDependencyStructure::Templates private
Definition at line 981 of file EpicRtcVideoCommon.h.
Referenced by FEpicRtcFrameDependencyStructure(), and GetTemplates().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2RTC/Internal/EpicRtcVideoCommon.h