Unreal Engine 5.6 C++ API: IAnimBlueprintCompilationContext Class Reference
IAnimBlueprintCompilationContext Class Reference abstract
Interface to the anim BP compiler context for use while compilation is in progress.
#include "IAnimBlueprintCompilationContext.h"
Data Structures
struct FFoldedPropertyRecord
Public Member Functions
virtual ~IAnimBlueprintCompilationContext ()
void AddAttributesToNode (UAnimGraphNode_Base *InNode, TArrayView< const FName > InAttributes) const
UEdGraphPin UEdGraph int32 & GetAllocatedAnimNodeIndices () const
const TMap< UAnimGraphNode_Base *, FProperty * > & GetAllocatedHandlerPropertiesByNode () const
const TMap< int32, FProperty * > & GetAllocatedPropertiesByIndex () const
const TMap< UAnimGraphNode_Base *, FProperty * > & GetAllocatedPropertiesByNode () const
TArrayView< const FName > GetAttributesFromNode (UAnimGraphNode_Base *InNode) const
const FFoldedPropertyRecord * GetFoldedPropertyRecord (UAnimGraphNode_Base *InNode, FName InPropertyName) const
virtual const FStructProperty * GetMutableDataProperty () const
const TMap< UAnimGraphNode_Base *, UAnimGraphNode_Base * > & GetSourceNodeToProcessedNodeMap () const
bool IsAnimGraphNodeFolded (UAnimGraphNode_Base *InNode) const
template<typename NodeType>
NodeType * SpawnIntermediateNode (UEdGraphNode *SourceNode, UEdGraph *ParentGraph=nullptr)
template<typename NodeType>
UE_DEPRECATED (5.4, "SpawnIntermediateEventNode is equivalent to SpawnIntermediateNode, this redundant function has been deprecated.") NodeType *SpawnIntermediateEventNode(UEdGraphNode *SourceNode
Static Public Member Functions
static TUniquePtr< IAnimBlueprintCompilationContext > Get (FKismetCompilerContext &InKismetCompiler)
Data Fields
UEdGraphPin UEdGraph * ParentGraph
UEdGraphPin * SourcePin = nullptr
Protected Member Functions
virtual void AddAttributesToNodeImpl (UAnimGraphNode_Base *InNode, TArrayView< const FName > InAttributes) const =0
virtual void AddPoseLinkMappingRecordImpl (const FPoseLinkMappingRecord &InRecord)=0
virtual void ExpansionStepImpl (UEdGraph *Graph, bool bAllowUbergraphExpansions)=0
virtual const TMap< UAnimGraphNode_Base *, int32 > & GetAllocatedAnimNodeIndicesImpl () const =0
virtual const TMap< UAnimGraphNode_Base *, FProperty * > & GetAllocatedHandlerPropertiesByNodeImpl () const =0
virtual const TMap< int32, FProperty * > & GetAllocatedPropertiesByIndexImpl () const =0
virtual const TMap< UAnimGraphNode_Base *, FProperty * > & GetAllocatedPropertiesByNodeImpl () const =0
virtual int32 GetAllocationIndexOfNodeImpl (UAnimGraphNode_Base *VisualAnimNode) const =0
virtual const UAnimBlueprint * GetAnimBlueprintImpl () const =0
virtual TArrayView< const FName > GetAttributesFromNodeImpl (UAnimGraphNode_Base *InNode) const =0
virtual const UBlueprint * GetBlueprintImpl () const =0
virtual UEdGraph * GetConsolidatedEventGraphImpl () const =0
virtual const FFoldedPropertyRecord * GetFoldedPropertyRecordImpl (UAnimGraphNode_Base *InNode, FName InPropertyName) const =0
virtual FKismetCompilerContext * GetKismetCompiler () const =0
virtual void GetLinkedAnimNodesImpl (UAnimGraphNode_Base *InGraphNode, TArray< UAnimGraphNode_Base * > &LinkedAnimNodes) const =0
virtual FCompilerResultsLog & GetMessageLogImpl () const =0
virtual const FStructProperty * GetMutableDataPropertyImpl () const =0
virtual const TMap< UAnimGraphNode_Base *, UAnimGraphNode_Base * > & GetSourceNodeToProcessedNodeMapImpl () const =0
virtual bool IsAnimGraphNodeFoldedImpl (UAnimGraphNode_Base *InNode) const =0
virtual void ProcessAnimationNodesImpl (TArray< UAnimGraphNode_Base * > &AnimNodeList)=0
virtual void PruneIsolatedAnimationNodesImpl (const TArray< UAnimGraphNode_Base * > &RootSet, TArray< UAnimGraphNode_Base * > &GraphNodes)=0
virtual bool ValidateGraphIsWellFormedImpl (UEdGraph *Graph) const =0
Detailed Description
Interface to the anim BP compiler context for use while compilation is in progress.
Definition at line 23 of file IAnimBlueprintCompilationContext.h.
Constructor & Destructor Documentation
~IAnimBlueprintCompilationContext()
virtual IAnimBlueprintCompilationContext::~IAnimBlueprintCompilationContext () inline virtual
Definition at line 63 of file IAnimBlueprintCompilationContext.h.
Member Function Documentation
AddAttributesToNode()
void IAnimBlueprintCompilationContext::AddAttributesToNode (UAnimGraphNode_Base * InNode, TArrayView< const FName > InAttributes) const inline
Definition at line 139 of file IAnimBlueprintCompilationContext.h.
References AddAttributesToNodeImpl().
AddAttributesToNodeImpl()
virtual void IAnimBlueprintCompilationContext::AddAttributesToNodeImpl (UAnimGraphNode_Base * InNode, TArrayView< const FName > InAttributes) const protected pure virtual
Referenced by AddAttributesToNode().
AddPoseLinkMappingRecordImpl()
virtual void IAnimBlueprintCompilationContext::AddPoseLinkMappingRecordImpl (const FPoseLinkMappingRecord & InRecord) protected pure virtual
ExpansionStepImpl()
virtual void IAnimBlueprintCompilationContext::ExpansionStepImpl (UEdGraph * Graph, bool bAllowUbergraphExpansions) protected pure virtual
Get()
TUniquePtr< IAnimBlueprintCompilationContext > IAnimBlueprintCompilationContext::Get (FKismetCompilerContext & InKismetCompiler) static
GetAllocatedAnimNodeIndices()
UEdGraphPin UEdGraph int32 & IAnimBlueprintCompilationContext::GetAllocatedAnimNodeIndices () const inline
Definition at line 124 of file IAnimBlueprintCompilationContext.h.
References GetAllocatedAnimNodeIndicesImpl().
GetAllocatedAnimNodeIndicesImpl()
virtual const TMap< UAnimGraphNode_Base *, int32 > & IAnimBlueprintCompilationContext::GetAllocatedAnimNodeIndicesImpl () const protected pure virtual
Referenced by GetAllocatedAnimNodeIndices().
GetAllocatedHandlerPropertiesByNode()
const TMap< UAnimGraphNode_Base *, FProperty * > & IAnimBlueprintCompilationContext::GetAllocatedHandlerPropertiesByNode () const inline
Definition at line 136 of file IAnimBlueprintCompilationContext.h.
References GetAllocatedHandlerPropertiesByNodeImpl().
GetAllocatedHandlerPropertiesByNodeImpl()
virtual const TMap< UAnimGraphNode_Base *, FProperty * > & IAnimBlueprintCompilationContext::GetAllocatedHandlerPropertiesByNodeImpl () const protected pure virtual
Referenced by GetAllocatedHandlerPropertiesByNode().
GetAllocatedPropertiesByIndex()
const TMap< int32, FProperty * > & IAnimBlueprintCompilationContext::GetAllocatedPropertiesByIndex () const inline
Definition at line 130 of file IAnimBlueprintCompilationContext.h.
References GetAllocatedPropertiesByIndexImpl().
GetAllocatedPropertiesByIndexImpl()
virtual const TMap< int32, FProperty * > & IAnimBlueprintCompilationContext::GetAllocatedPropertiesByIndexImpl () const protected pure virtual
Referenced by GetAllocatedPropertiesByIndex().
GetAllocatedPropertiesByNode()
const TMap< UAnimGraphNode_Base *, FProperty * > & IAnimBlueprintCompilationContext::GetAllocatedPropertiesByNode () const inline
Definition at line 133 of file IAnimBlueprintCompilationContext.h.
References GetAllocatedPropertiesByNodeImpl().
GetAllocatedPropertiesByNodeImpl()
virtual const TMap< UAnimGraphNode_Base *, FProperty * > & IAnimBlueprintCompilationContext::GetAllocatedPropertiesByNodeImpl () const protected pure virtual
Referenced by GetAllocatedPropertiesByNode().
GetAllocationIndexOfNodeImpl()
virtual int32 IAnimBlueprintCompilationContext::GetAllocationIndexOfNodeImpl (UAnimGraphNode_Base * VisualAnimNode) const protected pure virtual
GetAnimBlueprintImpl()
virtual const UAnimBlueprint * IAnimBlueprintCompilationContext::GetAnimBlueprintImpl () const protected pure virtual
GetAttributesFromNode()
TArrayView< const FName > IAnimBlueprintCompilationContext::GetAttributesFromNode (UAnimGraphNode_Base * InNode) const inline
Definition at line 142 of file IAnimBlueprintCompilationContext.h.
References GetAttributesFromNodeImpl().
GetAttributesFromNodeImpl()
virtual TArrayView< const FName > IAnimBlueprintCompilationContext::GetAttributesFromNodeImpl (UAnimGraphNode_Base * InNode) const protected pure virtual
Referenced by GetAttributesFromNode().
GetBlueprintImpl()
virtual const UBlueprint * IAnimBlueprintCompilationContext::GetBlueprintImpl () const protected pure virtual
GetConsolidatedEventGraphImpl()
virtual UEdGraph * IAnimBlueprintCompilationContext::GetConsolidatedEventGraphImpl () const protected pure virtual
GetFoldedPropertyRecord()
const FFoldedPropertyRecord * IAnimBlueprintCompilationContext::GetFoldedPropertyRecord (UAnimGraphNode_Base * InNode, FName InPropertyName) const inline
Definition at line 148 of file IAnimBlueprintCompilationContext.h.
References GetFoldedPropertyRecordImpl().
GetFoldedPropertyRecordImpl()
virtual const FFoldedPropertyRecord * IAnimBlueprintCompilationContext::GetFoldedPropertyRecordImpl (UAnimGraphNode_Base * InNode, FName InPropertyName) const protected pure virtual
Referenced by GetFoldedPropertyRecord().
GetKismetCompiler()
virtual FKismetCompilerContext * IAnimBlueprintCompilationContext::GetKismetCompiler () const protected pure virtual
Referenced by SpawnIntermediateNode().
GetLinkedAnimNodesImpl()
virtual void IAnimBlueprintCompilationContext::GetLinkedAnimNodesImpl (UAnimGraphNode_Base * InGraphNode, TArray< UAnimGraphNode_Base * > & LinkedAnimNodes) const protected pure virtual
GetMessageLogImpl()
virtual FCompilerResultsLog & IAnimBlueprintCompilationContext::GetMessageLogImpl () const protected pure virtual
GetMutableDataProperty()
virtual const FStructProperty * IAnimBlueprintCompilationContext::GetMutableDataProperty () const inline virtual
Definition at line 151 of file IAnimBlueprintCompilationContext.h.
References GetMutableDataPropertyImpl().
GetMutableDataPropertyImpl()
virtual const FStructProperty * IAnimBlueprintCompilationContext::GetMutableDataPropertyImpl () const protected pure virtual
Referenced by GetMutableDataProperty().
GetSourceNodeToProcessedNodeMap()
const TMap< UAnimGraphNode_Base *, UAnimGraphNode_Base * > & IAnimBlueprintCompilationContext::GetSourceNodeToProcessedNodeMap () const inline
Definition at line 127 of file IAnimBlueprintCompilationContext.h.
References GetSourceNodeToProcessedNodeMapImpl().
GetSourceNodeToProcessedNodeMapImpl()
virtual const TMap< UAnimGraphNode_Base *, UAnimGraphNode_Base * > & IAnimBlueprintCompilationContext::GetSourceNodeToProcessedNodeMapImpl () const protected pure virtual
Referenced by GetSourceNodeToProcessedNodeMap().
IsAnimGraphNodeFolded()
bool IAnimBlueprintCompilationContext::IsAnimGraphNodeFolded (UAnimGraphNode_Base * InNode) const inline
Definition at line 145 of file IAnimBlueprintCompilationContext.h.
References IsAnimGraphNodeFoldedImpl().
IsAnimGraphNodeFoldedImpl()
virtual bool IAnimBlueprintCompilationContext::IsAnimGraphNodeFoldedImpl (UAnimGraphNode_Base * InNode) const protected pure virtual
Referenced by IsAnimGraphNodeFolded().
ProcessAnimationNodesImpl()
virtual void IAnimBlueprintCompilationContext::ProcessAnimationNodesImpl (TArray< UAnimGraphNode_Base * > & AnimNodeList) protected pure virtual
PruneIsolatedAnimationNodesImpl()
virtual void IAnimBlueprintCompilationContext::PruneIsolatedAnimationNodesImpl (const TArray< UAnimGraphNode_Base * > & RootSet, TArray< UAnimGraphNode_Base * > & GraphNodes) protected pure virtual
References RootSet.
SpawnIntermediateNode()
template<typename NodeType> NodeType * IAnimBlueprintCompilationContext::SpawnIntermediateNode (UEdGraphNode * SourceNode, UEdGraph * ParentGraph = nullptr) inline
Definition at line 70 of file IAnimBlueprintCompilationContext.h.
References GetKismetCompiler(), and ParentGraph.
UE_DEPRECATED()
template<typename NodeType> IAnimBlueprintCompilationContext::UE_DEPRECATED (5. 4, "SpawnIntermediateEventNode is equivalent to SpawnIntermediateNode, this redundant function has been deprecated.")
ValidateGraphIsWellFormedImpl()
virtual bool IAnimBlueprintCompilationContext::ValidateGraphIsWellFormedImpl (UEdGraph * Graph) const protected pure virtual
Field Documentation
ParentGraph
UEdGraphPin UEdGraph* IAnimBlueprintCompilationContext::ParentGraph
Definition at line 78 of file IAnimBlueprintCompilationContext.h.
Referenced by SpawnIntermediateNode().
SourcePin
UEdGraphPin* IAnimBlueprintCompilationContext::SourcePin = nullptr
Definition at line 78 of file IAnimBlueprintCompilationContext.h.
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/IAnimBlueprintCompilationContext.h