Unreal Engine 5.6 C++ API: FTraceAuxiliary Class Reference
FTraceAuxiliary Class Reference
#include "TraceAuxiliary.h"
Data Structures
struct FChannelPreset
struct FOptions
Public Types
enum class EConnectionType : uint8 { Network , File , Relay , None }
enum class EEnumerateResult : uint8 { Continue , Stop }
enum class ETraceSystemStatus : uint8 {
NotAvailable , Available , TracingToServer , TracingToFile ,
NumValues
}
This enum is serialized and sent via the trace service.
typedef FLogCategoryBase FLogCategoryAlias
typedef TFunctionRef< EEnumerateResult(const FChannelPreset &Preset)> PresetCallback
Public Member Functions
DECLARE_TS_MULTICAST_DELEGATE (FOnConnection)
Callback type when a new connection is established.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnSnapshotSaved, FTraceAuxiliary::EConnectionType TraceType, const FString &TraceDestination)
Callback whenever a trace snapshot is saved.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnTraceStarted, FTraceAuxiliary::EConnectionType TraceType, const FString &TraceDestination)
Callback whenever a trace is started.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnTraceStopped, FTraceAuxiliary::EConnectionType TraceType, const FString &TraceDestination)
Callback whenever a trace recording is stopped.
UE_DEPRECATED (5.3, "Use GetTraceDestinationString instead.") static 1 const TCHAR *GetTraceDestination()
Returns the destination string that is currently being traced to.
Static Public Member Functions
static void DisableChannels (const TCHAR *Channels=nullptr)
Disable channels to stop recording traces with them.
static void DisableChannels (TConstArrayView< uint32 > ChannelIds)
Disable channels to mute events belonging to this category.
static void EnableChannels (TConstArrayView< uint32 > ChannelIds)
Enable channels to emit events belonging to this category.
static void EnableCommandlineChannels ()
Enable previously selected channels.
static void EnumerateChannelPresetsFromSettings (PresetCallback Callback)
Enumerate the channel presets that are defined in BaseEngine.ini, under the [Trace.ChannelPresets] section.
static void EnumerateFixedChannelPresets (PresetCallback Callback)
Enumerate the channel presets that are defined in code.
static void GetActiveChannelsString (FStringBuilderBase &String)
Adds a comma separated list of currently active channels to the passed in StringBuilder.
static EConnectionType GetConnectionType ()
Returns the current connection type.
static struct UE::Trace::FInitializeDesc const * GetInitializeDesc ()
Get the settings used to initialize TraceLog.
static FString GetTraceDestinationString ()
Returns the destination string that is currently being traced to.
static ETraceSystemStatus GetTraceSystemStatus ()
Returns the current status of the trace system.
static void Initialize (const TCHAR *CommandLine)
Initialize Trace systems.
static void InitializePresets (const TCHAR *CommandLine)
Initialize channels that use the config driven presets.
static bool IsConnected ()
Returns whether the trace system is currently connected to a trace sink (file or network)
static bool IsConnected (FGuid &OutSessionGuid, FGuid &OutTraceGuid)
Returns whether the trace system is currently connected.
static bool IsPaused ()
static void Panic ()
Used when process is panicking.
static bool Pause ()
Pause all tracing by disabling all active channels.
static bool Relay (UPTRINT Handle, UE::Trace::IoWriteFunc WriteFunc, UE::Trace::IoCloseFunc CloseFunc, const TCHAR *Channels=TEXT("default"), const FOptions *Options=nullptr)
Start tracing to a custom target by providing a handle and a write and close function.
static bool Resume ()
Resume tracing by enabling all previously active channels.
static bool SendSnapshot (const TCHAR *Host=nullptr, uint32 Port=0)
Write tailing memory state to a trace server.
static void Shutdown ()
Shut down Trace systems.
static bool Start (EConnectionType Type, const TCHAR *Target, const TCHAR *Channels=TEXT("default"), FOptions *Options=nullptr, const FLogCategoryAlias &LogCategory=LogCore)
Start tracing to a target (network connection or file) with an active set of channels.
static bool Stop ()
Stop tracing.
static void TryAutoConnect ()
Attempts to auto connect to an active trace server if an active session of Unreal Insights Session Browser is running.
static bool WriteSnapshot (const TCHAR *FilePath)
Write tailing memory state to a utrace file.
Static Public Attributes
static FOnConnection OnConnection
Delegate that triggers when a connection is established.
static FOnSnapshotSaved OnSnapshotSaved
Delegate that triggers when a snapshot has been saved.
static FOnTraceStarted OnTraceStarted
Delegate that triggers when a trace session is started.
static FOnTraceStopped OnTraceStopped
Delegate that triggers when a trace has finished recording.
Detailed Description
Definition at line 19 of file TraceAuxiliary.h.
Member Typedef Documentation
FLogCategoryAlias
typedef FLogCategoryBase FTraceAuxiliary::FLogCategoryAlias
Definition at line 72 of file TraceAuxiliary.h.
PresetCallback
typedef TFunctionRef<EEnumerateResult(const FChannelPreset& Preset)> FTraceAuxiliary::PresetCallback
Definition at line 65 of file TraceAuxiliary.h.
Member Enumeration Documentation
EConnectionType
enum class FTraceAuxiliary::EConnectionType : uint8 strong
Enumerator
Network
Connect to a trace server.
Target is IP address or hostname.
File
Write to a file.
Target string is filename. Absolute or relative current working directory. If target is null the current date and time is used.
Relay
Relay connection.
Pass user defined I/O functions to write raw trace data.
None
Don't connect, just start tracing to memory.
Definition at line 75 of file TraceAuxiliary.h.
EEnumerateResult
enum class FTraceAuxiliary::EEnumerateResult : uint8 strong
Enumerator
Continue
Stop
Definition at line 37 of file TraceAuxiliary.h.
ETraceSystemStatus
enum class FTraceAuxiliary::ETraceSystemStatus : uint8 strong
This enum is serialized and sent via the trace service.
Do not change the values or modify the order. Only add new values to the end. Should be kept in sync with FTraceStatus::ETraceSystemStatus from ITraceController.h
Enumerator
NotAvailable
Available
TracingToServer
TracingToFile
NumValues
Definition at line 27 of file TraceAuxiliary.h.
Member Function Documentation
DECLARE_TS_MULTICAST_DELEGATE()
FTraceAuxiliary::DECLARE_TS_MULTICAST_DELEGATE (FOnConnection)
Callback type when a new connection is established.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams() [1/3]
FTraceAuxiliary::DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnSnapshotSaved , FTraceAuxiliary::EConnectionType TraceType, const FString & TraceDestination)
Callback whenever a trace snapshot is saved.
Path is the file system path of the snapshot file.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams() [2/3]
FTraceAuxiliary::DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnTraceStarted , FTraceAuxiliary::EConnectionType TraceType, const FString & TraceDestination)
Callback whenever a trace is started.
DECLARE_TS_MULTICAST_DELEGATE_TwoParams() [3/3]
FTraceAuxiliary::DECLARE_TS_MULTICAST_DELEGATE_TwoParams (FOnTraceStopped , FTraceAuxiliary::EConnectionType TraceType, const FString & TraceDestination)
Callback whenever a trace recording is stopped.
TraceType tells what kind of trace it is. TraceDestination will be either the filename and path for a file trace or the network connection for a network trace
DisableChannels() [1/2]
void FTraceAuxiliary::DisableChannels (const TCHAR * Channels = nullptr) static
Disable channels to stop recording traces with them.
Parameters
Channels List of channels (or a preset) to disable. If null it will disable all active channels.
DisableChannels() [2/2]
void FTraceAuxiliary::DisableChannels (TConstArrayView< uint32 > ChannelIds) static
Disable channels to mute events belonging to this category.
Note
Note that presets cannot be used when specifying channel ids.
Parameters
ChannelIds List of channels (or a preset) to disable.
EnableChannels()
void FTraceAuxiliary::EnableChannels (TConstArrayView< uint32 > ChannelIds) static
Enable channels to emit events belonging to this category.
Note
Note that presets cannot be used when specifying channel ids.
Parameters
ChannelIds List of channels (or a preset) to enable.
EnableCommandlineChannels()
void FTraceAuxiliary::EnableCommandlineChannels () static
Enable previously selected channels.
This method can be called multiple times as channels can be announced on module loading.
EnumerateChannelPresetsFromSettings()
void FTraceAuxiliary::EnumerateChannelPresetsFromSettings (PresetCallback Callback) static
Enumerate the channel presets that are defined in BaseEngine.ini, under the [Trace.ChannelPresets] section.
References EnumerateChannelPresetsFromSettings().
Referenced by EnumerateChannelPresetsFromSettings().
EnumerateFixedChannelPresets()
void FTraceAuxiliary::EnumerateFixedChannelPresets (PresetCallback Callback) static
Enumerate the channel presets that are defined in code.
References EnumerateFixedChannelPresets().
Referenced by EnumerateFixedChannelPresets().
GetActiveChannelsString()
void FTraceAuxiliary::GetActiveChannelsString (FStringBuilderBase & String) static
Adds a comma separated list of currently active channels to the passed in StringBuilder.
References GetActiveChannelsString(), and String.
Referenced by GetActiveChannelsString().
GetConnectionType()
EConnectionType FTraceAuxiliary::GetConnectionType () static
Returns the current connection type.
References GetConnectionType().
Referenced by GetConnectionType().
GetInitializeDesc()
struct UE::Trace::FInitializeDesc const * FTraceAuxiliary::GetInitializeDesc () static
Get the settings used to initialize TraceLog.
References GetInitializeDesc().
Referenced by GetInitializeDesc().
GetTraceDestinationString()
FString FTraceAuxiliary::GetTraceDestinationString () static
Returns the destination string that is currently being traced to.
Contains either a file path or network address. Empty if tracing is disabled.
References GetTraceDestinationString().
Referenced by GetTraceDestinationString().
GetTraceSystemStatus()
ETraceSystemStatus FTraceAuxiliary::GetTraceSystemStatus () static
Returns the current status of the trace system.
References GetTraceSystemStatus(), Start(), and Stop.
Referenced by GetTraceSystemStatus().
Initialize()
void FTraceAuxiliary::Initialize (const TCHAR * CommandLine) static
Initialize Trace systems.
Parameters
CommandLine to use for initializing
InitializePresets()
void FTraceAuxiliary::InitializePresets (const TCHAR * CommandLine) static
Initialize channels that use the config driven presets.
Parameters
CommandLine to use for initializing
IsConnected() [1/2]
bool FTraceAuxiliary::IsConnected () static
Returns whether the trace system is currently connected to a trace sink (file or network)
References IsConnected().
Referenced by IsConnected(), and IsConnected().
IsConnected() [2/2]
bool FTraceAuxiliary::IsConnected (FGuid & OutSessionGuid, FGuid & OutTraceGuid) static
Returns whether the trace system is currently connected.
If connected writes the session/trace identifiers.
Parameters
OutSessionGuid If connected, the session guid
OutTraceGuid If connected, the trace guid
Returns
True if connected
References IsConnected().
IsPaused()
bool FTraceAuxiliary::IsPaused () static
Returns
True if trace was paused and the list of channels to resume exists.
Panic()
void FTraceAuxiliary::Panic () static
Used when process is panicking.
Stops all tracing immediately to avoid further allocations. Process is not expected to continue after this call.
References Panic().
Referenced by Panic().
Pause()
bool FTraceAuxiliary::Pause () static
Pause all tracing by disabling all active channels.
Relay()
bool FTraceAuxiliary::Relay (UPTRINT Handle, UE::Trace::IoWriteFunc WriteFunc, UE::Trace::IoCloseFunc CloseFunc, const TCHAR * Channels = TEXT("default"), const FOptions * Options = nullptr) static
Start tracing to a custom target by providing a handle and a write and close function.
If a connection is already active this call does nothing.
Parameters
Handle Anonymous handle to trace to. This will be passed to the writer and close functions.
WriteFunc A function to handle writing of trace data
CloseFunc A function to handle closing of the data stream.
Channels Comma separated list of channels to enable. Default set of channels are enabled if argument is not specified. If the pointer is null no channels are enabled.
Options Optional additional tracing options.
Returns
True when successfully starting the trace, false if the data connection could not be made.
References Handle.
Resume()
bool FTraceAuxiliary::Resume () static
Resume tracing by enabling all previously active channels.
SendSnapshot()
bool FTraceAuxiliary::SendSnapshot (const TCHAR * Host = nullptr, uint32 Port = 0) static
Write tailing memory state to a trace server.
Parameters
FilePath Path to the file to write the snapshot to. If it is null or empty a file path will be generated.
Shutdown()
void FTraceAuxiliary::Shutdown () static
Shut down Trace systems.
Start()
bool FTraceAuxiliary::Start (EConnectionType Type, const TCHAR * Target, const TCHAR * Channels = TEXT("default"), FOptions * Options = nullptr, const FLogCategoryAlias & LogCategory = LogCore) static
Start tracing to a target (network connection or file) with an active set of channels.
If a connection is already active this call does nothing.
Parameters
Type Type of connection. Network or File type. If a custom target is desired use FTraceAuxiliary::Relay.
Target String to use for connection. See /ref EConnectionType for details.
Channels Comma separated list of channels to enable. Default set of channels are enabled if argument is not specified. If the pointer is null no channels are enabled.
Options Optional additional tracing options.
LogCategory Log channel to output messages to. Default set to 'Core'.
Returns
True when successfully starting the trace, false if the data connection could not be made.
References LogCore, and Target.
Referenced by GetTraceSystemStatus().
Stop()
bool FTraceAuxiliary::Stop () static
Stop tracing.
Returns
True if the trace was stopped, false if there was no data connection.
TryAutoConnect()
void FTraceAuxiliary::TryAutoConnect () static
Attempts to auto connect to an active trace server if an active session of Unreal Insights Session Browser is running.
UE_DEPRECATED()
FTraceAuxiliary::UE_DEPRECATED (5. 3, "Use GetTraceDestinationString instead.") const
Returns the destination string that is currently being traced to.
Contains either a file path or network address. Points to an empty string if tracing is disabled.
WriteSnapshot()
bool FTraceAuxiliary::WriteSnapshot (const TCHAR * FilePath) static
Write tailing memory state to a utrace file.
Parameters
FilePath Path to the file to write the snapshot to. If it is null or empty a file path will be generated.
Field Documentation
OnConnection
FOnConnection FTraceAuxiliary::OnConnection static
Delegate that triggers when a connection is established.
Gives subscribers a chance to trace events that appear after important events but before regular events (including tail). The following restrictions apply:
Only NoSync event types can be emitted.
Important events should not be emitted. They will appear after the events in the tail.
Callback is issued from a worker thread. User is responsible to synchronize shared resources.
Note
This is an advanced feature to avoid using important events in cases where event data can be recalled easily.
Parameters
Callback Delegate to call on new connections.
Definition at line 300 of file TraceAuxiliary.h.
OnSnapshotSaved
FOnSnapshotSaved FTraceAuxiliary::OnSnapshotSaved static
Delegate that triggers when a snapshot has been saved.
The path to the snapshot file is passed to the delegate.
Definition at line 318 of file TraceAuxiliary.h.
OnTraceStarted
FOnTraceStarted FTraceAuxiliary::OnTraceStarted static
Delegate that triggers when a trace session is started.
The type of recording and the destination (filepath or network) is passed to the delegate.
Definition at line 306 of file TraceAuxiliary.h.
OnTraceStopped
FOnTraceStopped FTraceAuxiliary::OnTraceStopped static
Delegate that triggers when a trace has finished recording.
Useful if you need to collect all completed trace files in a session. The type of recording and the destination (filepath or network) is passed to the delegate.
Definition at line 312 of file TraceAuxiliary.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/TraceAuxiliary.h