Unreal Engine 5.6 C++ API: UBlueprintGameplayTagLibrary Class Reference
UBlueprintGameplayTagLibrary Class Reference
#include "BlueprintGameplayTagLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION()) static GAMEPLAYTAGS_API bool MatchesTag(FGameplayTag TagOne
Determine if TagOne matches against TagTwo.
UFUNCTION ()
Converts a UObject to a GameplayTagAssetInterface.
UFUNCTION () "
Returns true if the values are equal (A == B)
UFUNCTION () "
Returns true if the values are not equal (A != B)
UFUNCTION () "
Returns true if the values are equal (A == B)
UFUNCTION () "
Returns true if the values are not equal (A != B)
UFUNCTION ()) static GAMEPLAYTAGS_API bool DoesContainerMatchTagQuery(const FGameplayTagContainer &TagContainer
Check if the specified tag container matches the given Tag Query.
UFUNCTION ()) static GAMEPLAYTAGS_API bool DoesTagAssetInterfaceHaveTag(TScriptInterface< IGameplayTagAssetInterface > TagContainerInterface
Check if the specified tag container has the specified tag, using the specified tag matching types.
UFUNCTION ()) static GAMEPLAYTAGS_API bool HasAllMatchingGameplayTags(TScriptInterface< IGameplayTagAssetInterface > TagContainerInterface
Check Gameplay tags in the interface has all of the specified tags in the tag container (expands to include parents of asset tags)
UFUNCTION ()) static GAMEPLAYTAGS_API bool HasAllTags(const FGameplayTagContainer &TagContainer
Check if the specified tag container has ALL of the tags in the other container.
UFUNCTION ()) static GAMEPLAYTAGS_API bool HasAnyTags(const FGameplayTagContainer &TagContainer
Check if the specified tag container has ANY of the tags in the other container.
UFUNCTION ()) static GAMEPLAYTAGS_API bool HasTag(const FGameplayTagContainer &TagContainer
Check if the tag container has the specified tag.
UFUNCTION ()) static GAMEPLAYTAGS_API bool IsGameplayTagValid(FGameplayTag GameplayTag)
Returns true if the passed in gameplay tag is non-null.
UFUNCTION ()) static GAMEPLAYTAGS_API bool IsTagQueryEmpty(const FGameplayTagQuery &TagQuery)
Check if the specified tag query is empty.
UFUNCTION ()) static GAMEPLAYTAGS_API bool MatchesAnyTags(FGameplayTag TagOne
Determine if TagOne matches against any tag in OtherContainer.
UFUNCTION ()) static GAMEPLAYTAGS_API bool NotEqual_TagContainerTagContainer(FGameplayTagContainer A
Checks if a gameplay tag containers's name and a string are not equal to one another.
UFUNCTION ()) static GAMEPLAYTAGS_API bool NotEqual_TagTag(FGameplayTag A
Checks if a gameplay tag's name and a string are not equal to one another.
UFUNCTION ()) static GAMEPLAYTAGS_API bool RemoveGameplayTag(UPARAM(ref) FGameplayTagContainer &TagContainer
Remove a single tag from the passed in tag container, returns true if found.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTag MakeLiteralGameplayTag(FGameplayTag Value)
Creates a literal FGameplayTag.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagContainer Filter(const FGameplayTagContainer &TagContainer
Returns a filtered version of this container, returns all tags that match against any of the tags in OtherContainer.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagContainer MakeGameplayTagContainerFromArray(const TArray< FGameplayTag > &GameplayTags)
Creates a FGameplayTagContainer from the array of passed in tags.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagContainer MakeGameplayTagContainerFromTag(FGameplayTag SingleTag)
Creates a FGameplayTagContainer containing a single tag.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagContainer MakeLiteralGameplayTagContainer(FGameplayTagContainer Value)
Creates a literal FGameplayTagContainer.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagQuery MakeGameplayTagQuery(FGameplayTagQuery TagQuery)
Creates a literal FGameplayTagQuery.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagQuery MakeGameplayTagQuery_MatchAllTags(const FGameplayTagContainer &InTags)
Creates a literal FGameplayTagQuery with a prepopulated AllTagsMatch expression.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagQuery MakeGameplayTagQuery_MatchAnyTags(const FGameplayTagContainer &InTags)
Creates a literal FGameplayTagQuery with a prepopulated AnyTagsMatch expression.
UFUNCTION ()) static GAMEPLAYTAGS_API FGameplayTagQuery MakeGameplayTagQuery_MatchNoTags(const FGameplayTagContainer &InTags)
Creates a literal FGameplayTagQuery with a prepopulated NoTagsMatch expression.
UFUNCTION ()) static GAMEPLAYTAGS_API FName GetTagName(const FGameplayTag &GameplayTag)
Returns FName of this tag.
UFUNCTION ()) static GAMEPLAYTAGS_API FString GetDebugStringFromGameplayTag(FGameplayTag GameplayTag)
Returns an FString representation of a gameplay tag for debugging purposes.
UFUNCTION ()) static GAMEPLAYTAGS_API FString GetDebugStringFromGameplayTagContainer(const FGameplayTagContainer &TagContainer)
Returns an FString listing all of the gameplay tags in the tag container for debugging purposes.
UFUNCTION ()) static GAMEPLAYTAGS_API int32 GetNumGameplayTagsInContainer(const FGameplayTagContainer &TagContainer)
Get the number of gameplay tags in the specified container.
UFUNCTION ()) static GAMEPLAYTAGS_API UPARAM(DisplayName
UFUNCTION ()) static GAMEPLAYTAGS_API void AddGameplayTag(UPARAM(ref) FGameplayTagContainer &TagContainer
Adds a single tag to the passed in tag container.
UFUNCTION ()) static GAMEPLAYTAGS_API void AppendGameplayTagContainers(UPARAM(ref) FGameplayTagContainer &InOutTagContainer
Appends all tags in the InTagContainer to InOutTagContainer.
UFUNCTION ()) static GAMEPLAYTAGS_API void BreakGameplayTagContainer(const FGameplayTagContainer &GameplayTagContainer
Breaks tag container into explicit array of tags.
UFUNCTION ()) static GAMEPLAYTAGS_API void GetAllActorsOfClassMatchingTagQuery(UObject *WorldContextObject
Get an array of all actors of a specific class (or subclass of that class) which match the specified gameplay tag query.
Private Attributes
TSubclassOf< AActor > ActorClass
FString B
FGameplayTag bool bExactMatch
const FGameplayTagContainer bool bExactMatch
BlueprintThreadSafe
Category
CompactNodeTitle ="=="
TSubclassOf< AActor > const FGameplayTagQuery & GameplayTagQuery
TArray< FGameplayTag > & GameplayTags
const FGameplayTagContainer & InTagContainer
const FGameplayTagContainer & OtherContainer
TSubclassOf< AActor > const FGameplayTagQuery TArray< AActor * > & OutActors
FGameplayTag Tag
const FGameplayTagQuery & TagQuery
FGameplayTag TagTwo
Detailed Description
Definition at line 15 of file BlueprintGameplayTagLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UBlueprintGameplayTagLibrary::GENERATED_UCLASS_BODY () private
Determine if TagOne matches against TagTwo.
Parameters
TagOne Tag to check for match
TagTwo Tag to check match against
bExactMatch If true, the tag has to be exactly present, if false then TagOne will include it's parent tags while matching
Returns
True if TagOne matches TagTwo
References BlueprintThreadSafe, Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [1/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Converts a UObject to a GameplayTagAssetInterface.
This specialty Autocast function exists so we can auto-convert the GameplayTagAssetInterface member functions to static Blueprint functions using redirects.
References Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [2/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns true if the values are equal (A == B)
UFUNCTION() [3/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns true if the values are not equal (A != B)
References A, B, BlueprintThreadSafe, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [4/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns true if the values are equal (A == B)
References A, B, BlueprintThreadSafe, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [5/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns true if the values are not equal (A != B)
References A, B, BlueprintThreadSafe, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [6/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Check if the specified tag container matches the given Tag Query.
Parameters
TagContainer Container to check if it matches all of the tags in the other container
TagQuery Query to match against
Returns
True if the container matches the query, false otherwise.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [7/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Check if the specified tag container has the specified tag, using the specified tag matching types.
Parameters
TagContainerInterface An Interface to a tag container
Tag Tag to check for in the container
Returns
True if the container has the specified tag, false if it does not
References meta, Tag, and UFUNCTION().
UFUNCTION() [8/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Check Gameplay tags in the interface has all of the specified tags in the tag container (expands to include parents of asset tags)
Parameters
TagContainerInterface An Interface to a tag container
OtherContainer A Tag Container
Returns
True if the tagcontainer in the interface has all the tags inside the container.
References meta, OtherContainer, and UFUNCTION().
UFUNCTION() [9/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Check if the specified tag container has ALL of the tags in the other container.
Parameters
TagContainer Container to check if it matches all of the tags in the other container
OtherContainer Container to check against. If this is empty, the check will succeed
bExactMatch If true, the tag has to be exactly present, if false then TagContainer will include it's parent tags while matching
Returns
True if the container has ALL of the tags in the other container
References bExactMatch, BlueprintThreadSafe, Category, Keywords, meta, OtherContainer, and UFUNCTION().
UFUNCTION() [10/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Check if the specified tag container has ANY of the tags in the other container.
Parameters
TagContainer Container to check if it matches any of the tags in the other container
OtherContainer Container to check against.
bExactMatch If true, the tag has to be exactly present, if false then TagContainer will include it's parent tags while matching
Returns
True if the container has ANY of the tags in the other container
References bExactMatch, BlueprintThreadSafe, Category, Keywords, meta, OtherContainer, and UFUNCTION().
UFUNCTION() [11/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Check if the tag container has the specified tag.
Parameters
TagContainer Container to check for the tag
Tag Tag to check for in the container
bExactMatch If true, the tag has to be exactly present, if false then TagContainer will include it's parent tags while matching
Returns
True if the container has the specified tag, false if it does not
References BlueprintThreadSafe, Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [12/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns true if the passed in gameplay tag is non-null.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [13/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Check if the specified tag query is empty.
Parameters
TagQuery Query to check
Returns
True if the query is empty, false otherwise.
References BlueprintThreadSafe, Category, meta, TagQuery, and UFUNCTION().
UFUNCTION() [14/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Determine if TagOne matches against any tag in OtherContainer.
Parameters
TagOne Tag to check for match
OtherContainer Container to check against.
bExactMatch If true, the tag has to be exactly present, if false then TagOne will include it's parent tags while matching
Returns
True if TagOne matches any tags explicitly present in OtherContainer
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [15/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Checks if a gameplay tag containers's name and a string are not equal to one another.
References A, B, Category, meta, and UFUNCTION().
UFUNCTION() [16/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Checks if a gameplay tag's name and a string are not equal to one another.
References Category, meta, and UFUNCTION().
UFUNCTION() [17/35]
UBlueprintGameplayTagLibrary::UFUNCTION () & private
Remove a single tag from the passed in tag container, returns true if found.
Parameters
InOutTagContainer The container that will be appended too.
Tag The tag to add to the container
References BlueprintThreadSafe, Category, meta, Tag, UFUNCTION(), and UPARAM.
UFUNCTION() [18/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Creates a literal FGameplayTag.
References BlueprintThreadSafe, Category, meta, UFUNCTION(), and Value.
UFUNCTION() [19/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Returns a filtered version of this container, returns all tags that match against any of the tags in OtherContainer.
Parameters
OtherContainer The Container to filter against
bExactMatch If true, the tag has to be exactly present, if false then TagContainer will include it's parent tags while matching
Returns
A FGameplayTagContainer containing the filtered tags
References bExactMatch, BlueprintThreadSafe, Category, Filter, meta, OtherContainer, and UFUNCTION().
UFUNCTION() [20/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Creates a FGameplayTagContainer from the array of passed in tags.
References BlueprintThreadSafe, Category, GameplayTags, meta, and UFUNCTION().
UFUNCTION() [21/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Creates a FGameplayTagContainer containing a single tag.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [22/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Creates a literal FGameplayTagContainer.
References BlueprintThreadSafe, Category, meta, UFUNCTION(), and Value.
UFUNCTION() [23/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Creates a literal FGameplayTagQuery.
Parameters
TagQuery value to set the FGameplayTagQuery to
Returns
The literal FGameplayTagQuery
References BlueprintThreadSafe, Category, meta, TagQuery, and UFUNCTION().
UFUNCTION() [24/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Creates a literal FGameplayTagQuery with a prepopulated AllTagsMatch expression.
Parameters
InTags value to set the FGameplayTagQuery expression
Returns
The literal FGameplayTagQuery
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [25/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Creates a literal FGameplayTagQuery with a prepopulated AnyTagsMatch expression.
Parameters
InTags value to set the FGameplayTagQuery expression
Returns
The literal FGameplayTagQuery
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [26/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Creates a literal FGameplayTagQuery with a prepopulated NoTagsMatch expression.
Parameters
InTags value to set the FGameplayTagQuery expression
Returns
The literal FGameplayTagQuery
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [27/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Returns FName of this tag.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [28/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns an FString representation of a gameplay tag for debugging purposes.
Parameters
GameplayTag The tag to get the debug string from.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [29/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Returns an FString listing all of the gameplay tags in the tag container for debugging purposes.
Parameters
TagContainer The tag container to get the debug string from.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [30/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Get the number of gameplay tags in the specified container.
Parameters
TagContainer Tag container to get the number of tags from
Returns
The number of tags in the specified container
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [31/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Returns
the tags currently owned by the TagContainerInterface object
References Category, meta, UFUNCTION(), and UPARAM.
UFUNCTION() [32/35]
UBlueprintGameplayTagLibrary::UFUNCTION () & private
Adds a single tag to the passed in tag container.
Parameters
InOutTagContainer The container that will be appended too.
Tag The tag to add to the container
References BlueprintThreadSafe, Category, meta, Tag, UFUNCTION(), and UPARAM.
UFUNCTION() [33/35]
UBlueprintGameplayTagLibrary::UFUNCTION () & private
Appends all tags in the InTagContainer to InOutTagContainer.
Parameters
InOutTagContainer The container that will be appended too.
InTagContainer The container to append.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [34/35]
UBlueprintGameplayTagLibrary::UFUNCTION () const & private
Breaks tag container into explicit array of tags.
References BlueprintThreadSafe, Category, meta, and UFUNCTION().
UFUNCTION() [35/35]
UBlueprintGameplayTagLibrary::UFUNCTION () private
Get an array of all actors of a specific class (or subclass of that class) which match the specified gameplay tag query.
Parameters
ActorClass Class of actors to fetch
GameplayTagQuery Query to match against
References Category, meta, and UFUNCTION().
Field Documentation
ActorClass
TSubclassOf<AActor> UBlueprintGameplayTagLibrary::ActorClass private
Definition at line 149 of file BlueprintGameplayTagLibrary.h.
B
FString UBlueprintGameplayTagLibrary::B private
Definition at line 266 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
bExactMatch [1/2]
const FGameplayTagContainer bool UBlueprintGameplayTagLibrary::bExactMatch private
Definition at line 29 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
bExactMatch [2/2]
const FGameplayTagContainer bool UBlueprintGameplayTagLibrary::bExactMatch private
Definition at line 41 of file BlueprintGameplayTagLibrary.h.
BlueprintThreadSafe
UBlueprintGameplayTagLibrary::BlueprintThreadSafe private
Definition at line 44 of file BlueprintGameplayTagLibrary.h.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
Category
UBlueprintGameplayTagLibrary::Category private
Initial value:
="GameplayTags")
    static GAMEPLAYTAGS_API bool EqualEqual_GameplayTag( FGameplayTag A, FGameplayTag B )
Definition at line 44 of file BlueprintGameplayTagLibrary.h.
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
CompactNodeTitle
UBlueprintGameplayTagLibrary::CompactNodeTitle ="==" private
Definition at line 44 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
GameplayTagQuery
TSubclassOf<AActor> const FGameplayTagQuery& UBlueprintGameplayTagLibrary::GameplayTagQuery private
Definition at line 149 of file BlueprintGameplayTagLibrary.h.
GameplayTags
TArray<FGameplayTag>& UBlueprintGameplayTagLibrary::GameplayTags private
Definition at line 200 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION().
InTagContainer
const FGameplayTagContainer& UBlueprintGameplayTagLibrary::InTagContainer private
Definition at line 176 of file BlueprintGameplayTagLibrary.h.
OtherContainer
const FGameplayTagContainer & UBlueprintGameplayTagLibrary::OtherContainer private
Definition at line 41 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
OutActors
TSubclassOf<AActor> const FGameplayTagQuery TArray<AActor*>& UBlueprintGameplayTagLibrary::OutActors private
Definition at line 149 of file BlueprintGameplayTagLibrary.h.
Tag
FGameplayTag UBlueprintGameplayTagLibrary::Tag private
Definition at line 83 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
TagQuery
const FGameplayTagQuery& UBlueprintGameplayTagLibrary::TagQuery private
Definition at line 139 of file BlueprintGameplayTagLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
TagTwo
FGameplayTag UBlueprintGameplayTagLibrary::TagTwo private
Definition at line 29 of file BlueprintGameplayTagLibrary.h.
The documentation for this class was generated from the following file:
Runtime/GameplayTags/Classes/BlueprintGameplayTagLibrary.h