Unreal Engine 5.6 C++ API: FIoContainerId Class Reference
FIoContainerId Class Reference
Container ID.
#include "IoContainerId.h"
Public Member Functions
FIoContainerId ()=default
FIoContainerId (const FIoContainerId &Other)=default
FIoContainerId (FIoContainerId &&Other)=default
bool IsValid () const
bool operator!= (FIoContainerId Other) const
bool operator< (FIoContainerId Other) const
FIoContainerId & operator= (const FIoContainerId &Other)=default
bool operator== (FIoContainerId Other) const
uint64 Value () const
Static Public Member Functions
static FIoContainerId FromName (const FName &Name)
Private Member Functions
FIoContainerId (const uint64 InId)
Private Attributes
uint64 Id = InvalidId
Static Private Attributes
static constexpr uint64 InvalidId = uint64(-1)
Friends
uint32 GetTypeHash (const FIoContainerId &In)
FString LexToString (const FIoContainerId &ContainerId)
bool LoadFromCompactBinary (FCbFieldView Field, FIoContainerId &OutContainerId)
FArchive & operator<< (FArchive &Ar, FIoContainerId &ContainerId)
FCbWriter & operator<< (FCbWriter &Writer, const FIoContainerId &ContainerId)
void operator<< (FStructuredArchiveSlot Slot, FIoContainerId &ContainerId)
Detailed Description
Container ID.
Definition at line 17 of file IoContainerId.h.
Constructor & Destructor Documentation
FIoContainerId() [1/4]
FIoContainerId::FIoContainerId () inline default
Referenced by FIoContainerId(), FIoContainerId(), FromName(), GetTypeHash, LexToString, LoadFromCompactBinary, operator!=(), operator<(), operator<<, operator<<, operator<<, operator=(), and operator==().
FIoContainerId() [2/4]
FIoContainerId::FIoContainerId (const FIoContainerId & Other) inline default
References FIoContainerId(), and Other.
FIoContainerId() [3/4]
FIoContainerId::FIoContainerId (FIoContainerId && Other) inline default
References FIoContainerId(), and Other.
FIoContainerId() [4/4]
FIoContainerId::FIoContainerId (const uint64 InId) inline explicit private
Definition at line 68 of file IoContainerId.h.
References Id.
Member Function Documentation
FromName()
FIoContainerId FIoContainerId::FromName (const FName & Name) static
References FIoContainerId(), and Name.
IsValid()
bool FIoContainerId::IsValid () const inline
Definition at line 32 of file IoContainerId.h.
References Id, and InvalidId.
operator!=()
bool FIoContainerId::operator!= (FIoContainerId Other) const inline
Definition at line 47 of file IoContainerId.h.
References FIoContainerId(), Id, and Other.
operator<()
bool FIoContainerId::operator< (FIoContainerId Other) const inline
Definition at line 37 of file IoContainerId.h.
References FIoContainerId(), Id, and Other.
operator=()
FIoContainerId & FIoContainerId::operator= (const FIoContainerId & Other) inline default
References FIoContainerId(), and Other.
operator==()
bool FIoContainerId::operator== (FIoContainerId Other) const inline
Definition at line 42 of file IoContainerId.h.
References FIoContainerId(), Id, and Other.
Value()
uint64 FIoContainerId::Value () const inline
Definition at line 27 of file IoContainerId.h.
References Id.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FIoContainerId & In) friend
Definition at line 52 of file IoContainerId.h.
References FIoContainerId(), and Id.
LexToString
FString LexToString (const FIoContainerId & ContainerId) friend
References FIoContainerId().
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Field, FIoContainerId & OutContainerId) friend
References FIoContainerId().
operator<< [1/3]
FArchive & operator<< (FArchive & Ar, FIoContainerId & ContainerId) friend
References FIoContainerId(), and Ar.
operator<< [2/3]
FCbWriter & operator<< (FCbWriter & Writer, const FIoContainerId & ContainerId) friend
References FIoContainerId().
operator<< [3/3]
void operator<< (FStructuredArchiveSlot Slot, FIoContainerId & ContainerId) friend
References FIoContainerId().
Field Documentation
Id
uint64 FIoContainerId::Id = InvalidId private
Definition at line 73 of file IoContainerId.h.
Referenced by FIoContainerId(), GetTypeHash, IsValid(), operator!=(), operator<(), operator==(), and Value().
InvalidId
uint64 FIoContainerId::InvalidId = uint64(-1) static constexpr private
Definition at line 71 of file IoContainerId.h.
Referenced by IsValid().
The documentation for this class was generated from the following file:
Runtime/Core/Public/IO/IoContainerId.h