Unreal Engine 5.6 C++ API: FCbWriter Class Reference
FCbWriter Class Reference
A writer for compact binary object, arrays, and fields.
#include "CompactBinaryWriter.h"
Data Structures
struct FState
State of the object, array, or top-level field being written.
Public Member Functions
FCbWriter ()
FCbWriter (const FCbWriter &)=delete
~FCbWriter ()
void AddArray (const FCbArray &Value)
void AddArray (const FCbArrayView &Value)
void AddArray (FUtf8StringView Name, const FCbArray &Value)
Copy the value (not the name) of an existing array.
void AddArray (FUtf8StringView Name, const FCbArrayView &Value)
Copy the value (not the name) of an existing array.
void AddAttachment (const FCbAttachment &Attachment)
void AddAttachment (FUtf8StringView Name, const FCbAttachment &Attachment)
Write a field referencing the attachment by its hash.
void AddBinary (const FCompositeBuffer &Value)
void AddBinary (const FSharedBuffer &Value)
void AddBinary (const void *Value, uint64 Size)
void AddBinary (FMemoryView Value)
void AddBinary (FUtf8StringView Name, const FCompositeBuffer &Value)
void AddBinary (FUtf8StringView Name, const FSharedBuffer &Value)
Write a binary field by copying the buffer.
void AddBinary (FUtf8StringView Name, const void *Value, uint64 Size)
Write a binary field by copying Size bytes from Value.
void AddBinary (FUtf8StringView Name, FMemoryView Value)
Write a binary field by copying the view.
void AddBinaryAttachment (const FIoHash &Value)
void AddBinaryAttachment (FUtf8StringView Name, const FIoHash &Value)
Write a field referencing a binary attachment by its hash.
void AddBool (bool bValue)
void AddBool (FUtf8StringView Name, bool bValue)
Write a bool field.
void AddCustom (FUtf8StringView FieldName, FUtf8StringView TypeName, FMemoryView Value)
Write a custom field with a string sub-type identifier.
void AddCustom (FUtf8StringView FieldName, uint64 TypeId, FMemoryView Value)
Write a custom field with an integer sub-type identifier.
void AddCustom (FUtf8StringView TypeName, FMemoryView Value)
void AddCustom (uint64 TypeId, FMemoryView Value)
void AddDateTime (FDateTime Value)
void AddDateTime (FUtf8StringView Name, FDateTime Value)
Write a date/time field.
void AddDateTimeTicks (FUtf8StringView Name, int64 Ticks)
Write a date/time field with the specified count of 100ns ticks since the epoch.
void AddDateTimeTicks (int64 Ticks)
void AddField (const FCbField &Value)
void AddField (const FCbFieldView &Value)
void AddField (FUtf8StringView Name, const FCbField &Value)
Copy the value (not the name) of an existing field.
void AddField (FUtf8StringView Name, const FCbFieldView &Value)
Copy the value (not the name) of an existing field.
void AddFloat (double Value)
void AddFloat (float Value)
void AddFloat (FUtf8StringView Name, double Value)
Write a float field from a 64-bit float value.
void AddFloat (FUtf8StringView Name, float Value)
Write a float field from a 32-bit float value.
void AddHash (const FIoHash &Value)
void AddHash (FUtf8StringView Name, const FIoHash &Value)
Write a hash field.
void AddInteger (FUtf8StringView Name, int32 Value)
Write an integer field.
void AddInteger (FUtf8StringView Name, int64 Value)
Write an integer field.
void AddInteger (FUtf8StringView Name, uint32 Value)
Write an integer field.
void AddInteger (FUtf8StringView Name, uint64 Value)
Write an integer field.
void AddInteger (int32 Value)
void AddInteger (int64 Value)
void AddInteger (uint32 Value)
void AddInteger (uint64 Value)
void AddNull ()
void AddNull (FUtf8StringView Name)
Write a null field.
void AddObject (const FCbObject &Value)
void AddObject (const FCbObjectView &Value)
void AddObject (FUtf8StringView Name, const FCbObject &Value)
Copy the value (not the name) of an existing object.
void AddObject (FUtf8StringView Name, const FCbObjectView &Value)
Copy the value (not the name) of an existing object.
void AddObjectAttachment (const FIoHash &Value)
void AddObjectAttachment (FUtf8StringView Name, const FIoHash &Value)
Write a field referencing an object attachment by its hash.
void AddObjectId (const FCbObjectId &Value)
void AddObjectId (FUtf8StringView Name, const FCbObjectId &Value)
Write an ObjectId field.
void AddString (FUtf8StringView Name, FUtf8StringView Value)
Write a string field by copying the UTF-8 value.
void AddString (FUtf8StringView Name, FWideStringView Value)
Write a string field by converting the UTF-16 value to UTF-8.
void AddString (FUtf8StringView Value)
void AddString (FWideStringView Value)
void AddTimeSpan (FTimespan Value)
void AddTimeSpan (FUtf8StringView Name, FTimespan Value)
Write a time span field.
void AddTimeSpanTicks (FUtf8StringView Name, int64 Ticks)
Write a time span field with the specified count of 100ns ticks.
void AddTimeSpanTicks (int64 Ticks)
void AddUuid (const FGuid &Value)
void AddUuid (FUtf8StringView Name, const FGuid &Value)
Write a UUID field.
void BeginArray ()
void BeginArray (FUtf8StringView Name)
Begin a new array.
void BeginObject ()
void BeginObject (FUtf8StringView Name)
Begin a new object.
void EndArray ()
End an array after its fields have been written.
void EndObject ()
End an object after its fields have been written.
uint64 GetSaveSize () const
The size of buffer (in bytes) required to serialize the fields that have been written.
FCbWriter & operator<< (bool Value)
FCbWriter & operator<< (const ANSICHAR *NameOrValue)
Write the field name if valid in this state, otherwise write the string value.
FCbWriter & operator<< (const FAnsiString &Value)
FCbWriter & operator<< (const FCbArray &Value)
FCbWriter & operator<< (const FCbArrayView &Value)
FCbWriter & operator<< (const FCbAttachment &Attachment)
FCbWriter & operator<< (const FCbField &Value)
FCbWriter & operator<< (const FCbFieldView &Value)
FCbWriter & operator<< (const FCbObject &Value)
FCbWriter & operator<< (const FCbObjectId &Value)
FCbWriter & operator<< (const FCbObjectView &Value)
FCbWriter & operator<< (const FGuid &Value)
FCbWriter & operator<< (const FIoHash &Value)
FCbWriter & operator<< (const FString &Value)
FCbWriter & operator<< (const FUtf8String &Value)
template<typename T, typename Allocator, std::void_t< decltype(std::declval< FCbWriter & >()<< std::declval< const T & >())> * = nullptr>
FCbWriter & operator<< (const TArray< T, Allocator > &Value)
FCbWriter & operator<< (const UTF8CHAR *NameOrValue)
Write the field name if valid in this state, otherwise write the string value.
FCbWriter & operator<< (const WIDECHAR *Value)
FCbWriter & operator<< (double Value)
FCbWriter & operator<< (FDateTime Value)
FCbWriter & operator<< (float Value)
FCbWriter & operator<< (FName Value)
FCbWriter & operator<< (FTimespan Value)
FCbWriter & operator<< (FUtf8StringView NameOrValue)
Write the field name if valid in this state, otherwise write the string value.
FCbWriter & operator<< (FWideStringView Value)
FCbWriter & operator<< (int32 Value)
FCbWriter & operator<< (int64 Value)
FCbWriter & operator<< (nullptr_t)
FCbWriter & operator<< (uint32 Value)
FCbWriter & operator<< (uint64 Value)
FCbWriter & operator= (const FCbWriter &)=delete
void Reset ()
Empty the writer without releasing any allocated memory.
FCbFieldIterator Save () const
Serialize the field(s) to an owned buffer and return it as an iterator.
void Save (FArchive &Ar) const
Serialize the field(s) to an archive.
FCbFieldViewIterator Save (FMutableMemoryView Buffer) const
Serialize the field(s) to memory.
FCbWriter & SetName (FUtf8StringView Name)
Sets the name of the next field to be written.
Protected Member Functions
FCbWriter (int64 InitialSize)
Reserve the specified size up front until the format is optimized.
Private Member Functions
void BeginField ()
Begin writing a field.
void EndField (ECbFieldType Type)
Finish writing a field by writing its type.
FUtf8StringView GetActiveName () const
Returns a view of the name of the active field, if any, otherwise the empty view.
void MakeFieldsUniform (int64 FieldBeginOffset, int64 FieldEndOffset)
Remove field types after the first to make the sequence uniform.
void SetNameOrAddString (FUtf8StringView NameOrValue)
Set the field name if valid in this state, otherwise write add a string field.
Private Attributes
TArray64< uint8 > Data
TArray< FState > States
Detailed Description
A writer for compact binary object, arrays, and fields.
The writer produces a sequence of fields that can be saved to a provided memory buffer or into a new owned buffer. The typical use case is to write a single object, which can be accessed by calling Save().AsObject() or Save(Buffer).AsObjectView().
The writer will assert on most incorrect usage and will always produce valid compact binary if provided with valid input. The writer does not check for invalid UTF-8 string encoding, object fields with duplicate names, or invalid compact binary being copied from another source.
It is most convenient to use the streaming API for the writer, as demonstrated in the example.
When writing a small amount of compact binary data, TCbWriter can be more efficient as it uses a fixed-size stack buffer for storage before spilling onto the heap.
See also
TCbWriter
Example:
FCbObject WriteObject() { TCbWriter<256> Writer; Writer.BeginObject();
Writer << "Resize" << true; Writer << "MaxWidth" << 1024; Writer << "MaxHeight" << 1024;
Writer.BeginArray(); Writer << "FormatA" << "FormatB" << "FormatC"; Writer.EndArray();
Writer.EndObject(); return Writer.Save().AsObject(); }
Definition at line 67 of file CompactBinaryWriter.h.
Constructor & Destructor Documentation
FCbWriter() [1/3]
FCbWriter::FCbWriter ()
Referenced by FCbWriter(), TCbWriter< InlineBufferSize >::TCbWriter(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator=(), and SetName().
~FCbWriter()
FCbWriter::~FCbWriter ()
FCbWriter() [2/3]
FCbWriter::FCbWriter (const FCbWriter &) delete
References FCbWriter().
FCbWriter() [3/3]
FCbWriter::FCbWriter (int64 InitialSize) explicit protected
Reserve the specified size up front until the format is optimized.
Member Function Documentation
AddArray() [1/4]
void FCbWriter::AddArray (const FCbArray & Value)
References Value.
AddArray() [2/4]
void FCbWriter::AddArray (const FCbArrayView & Value)
References Value.
AddArray() [3/4]
void FCbWriter::AddArray (FUtf8StringView Name, const FCbArray & Value) inline
Copy the value (not the name) of an existing array.
Holds a reference if owned.
Definition at line 153 of file CompactBinaryWriter.h.
References AddArray(), Name, SetName(), and Value.
Referenced by AddArray().
AddArray() [4/4]
void FCbWriter::AddArray (FUtf8StringView Name, const FCbArrayView & Value) inline
Copy the value (not the name) of an existing array.
Definition at line 150 of file CompactBinaryWriter.h.
References AddArray(), Name, SetName(), and Value.
Referenced by AddArray(), operator<<(), and operator<<().
AddAttachment() [1/2]
void FCbWriter::AddAttachment (const FCbAttachment & Attachment)
AddAttachment() [2/2]
void FCbWriter::AddAttachment (FUtf8StringView Name, const FCbAttachment & Attachment) inline
Write a field referencing the attachment by its hash.
Definition at line 210 of file CompactBinaryWriter.h.
References AddAttachment(), Name, and SetName().
Referenced by AddAttachment(), and operator<<().
AddBinary() [1/8]
void FCbWriter::AddBinary (const FCompositeBuffer & Value)
References Value.
AddBinary() [2/8]
void FCbWriter::AddBinary (const FSharedBuffer & Value)
References Value.
AddBinary() [3/8]
void FCbWriter::AddBinary (const void * Value, uint64 Size)
References TSequenceHistory< HistorySize >::Size, and Value.
AddBinary() [4/8]
void FCbWriter::AddBinary (FMemoryView Value) inline
Definition at line 165 of file CompactBinaryWriter.h.
References AddBinary(), and Value.
Referenced by AddBinary().
AddBinary() [5/8]
void FCbWriter::AddBinary (FUtf8StringView Name, const FCompositeBuffer & Value) inline
Definition at line 169 of file CompactBinaryWriter.h.
References AddBinary(), Name, SetName(), and Value.
Referenced by AddBinary().
AddBinary() [6/8]
void FCbWriter::AddBinary (FUtf8StringView Name, const FSharedBuffer & Value) inline
Write a binary field by copying the buffer.
Holds a reference if owned.
Definition at line 167 of file CompactBinaryWriter.h.
References AddBinary(), Name, SetName(), and Value.
Referenced by AddBinary().
AddBinary() [7/8]
void FCbWriter::AddBinary (FUtf8StringView Name, const void * Value, uint64 Size) inline
Write a binary field by copying Size bytes from Value.
Definition at line 161 of file CompactBinaryWriter.h.
References AddBinary(), Name, SetName(), TSequenceHistory< HistorySize >::Size, and Value.
Referenced by AddBinary().
AddBinary() [8/8]
void FCbWriter::AddBinary (FUtf8StringView Name, FMemoryView Value) inline
Write a binary field by copying the view.
Definition at line 164 of file CompactBinaryWriter.h.
References AddBinary(), Name, SetName(), and Value.
Referenced by AddBinary().
AddBinaryAttachment() [1/2]
void FCbWriter::AddBinaryAttachment (const FIoHash & Value)
References Value.
AddBinaryAttachment() [2/2]
void FCbWriter::AddBinaryAttachment (FUtf8StringView Name, const FIoHash & Value) inline
Write a field referencing a binary attachment by its hash.
Definition at line 207 of file CompactBinaryWriter.h.
References AddBinaryAttachment(), Name, SetName(), and Value.
Referenced by AddBinaryAttachment().
AddBool() [1/2]
void FCbWriter::AddBool (bool bValue)
AddBool() [2/2]
void FCbWriter::AddBool (FUtf8StringView Name, bool bValue) inline
Write a bool field.
Definition at line 200 of file CompactBinaryWriter.h.
References AddBool(), Name, and SetName().
Referenced by AddBool(), and operator<<().
AddCustom() [1/4]
void FCbWriter::AddCustom (FUtf8StringView FieldName, FUtf8StringView TypeName, FMemoryView Value) inline
Write a custom field with a string sub-type identifier.
Definition at line 245 of file CompactBinaryWriter.h.
References AddCustom(), SetName(), and Value.
Referenced by AddCustom().
AddCustom() [2/4]
void FCbWriter::AddCustom (FUtf8StringView FieldName, uint64 TypeId, FMemoryView Value) inline
Write a custom field with an integer sub-type identifier.
Definition at line 241 of file CompactBinaryWriter.h.
References AddCustom(), SetName(), and Value.
Referenced by AddCustom().
AddCustom() [3/4]
void FCbWriter::AddCustom (FUtf8StringView TypeName, FMemoryView Value)
References Value.
AddCustom() [4/4]
void FCbWriter::AddCustom (uint64 TypeId, FMemoryView Value)
References Value.
AddDateTime() [1/2]
void FCbWriter::AddDateTime (FDateTime Value)
References Value.
AddDateTime() [2/2]
void FCbWriter::AddDateTime (FUtf8StringView Name, FDateTime Value)
Write a date/time field.
References Name, and Value.
AddDateTimeTicks() [1/2]
void FCbWriter::AddDateTimeTicks (FUtf8StringView Name, int64 Ticks) inline
Write a date/time field with the specified count of 100ns ticks since the epoch.
Definition at line 221 of file CompactBinaryWriter.h.
References AddDateTimeTicks(), Name, and SetName().
Referenced by AddDateTimeTicks().
AddDateTimeTicks() [2/2]
void FCbWriter::AddDateTimeTicks (int64 Ticks)
AddField() [1/4]
void FCbWriter::AddField (const FCbField & Value)
References Value.
AddField() [2/4]
void FCbWriter::AddField (const FCbFieldView & Value)
References Value.
AddField() [3/4]
void FCbWriter::AddField (FUtf8StringView Name, const FCbField & Value) inline
Copy the value (not the name) of an existing field.
Holds a reference if owned.
Definition at line 127 of file CompactBinaryWriter.h.
References AddField(), Name, SetName(), and Value.
Referenced by AddField().
AddField() [4/4]
void FCbWriter::AddField (FUtf8StringView Name, const FCbFieldView & Value) inline
Copy the value (not the name) of an existing field.
Definition at line 124 of file CompactBinaryWriter.h.
References AddField(), Name, SetName(), and Value.
Referenced by AddField(), operator<<(), and operator<<().
AddFloat() [1/4]
void FCbWriter::AddFloat (double Value)
References Value.
AddFloat() [2/4]
void FCbWriter::AddFloat (float Value)
References Value.
AddFloat() [3/4]
void FCbWriter::AddFloat (FUtf8StringView Name, double Value) inline
Write a float field from a 64-bit float value.
Definition at line 196 of file CompactBinaryWriter.h.
References AddFloat(), Name, SetName(), and Value.
Referenced by AddFloat().
AddFloat() [4/4]
void FCbWriter::AddFloat (FUtf8StringView Name, float Value) inline
Write a float field from a 32-bit float value.
Definition at line 193 of file CompactBinaryWriter.h.
References AddFloat(), Name, SetName(), and Value.
Referenced by AddFloat(), operator<<(), and operator<<().
AddHash() [1/2]
void FCbWriter::AddHash (const FIoHash & Value)
References Value.
AddHash() [2/2]
void FCbWriter::AddHash (FUtf8StringView Name, const FIoHash & Value) inline
Write a hash field.
Definition at line 214 of file CompactBinaryWriter.h.
References AddHash(), Name, SetName(), and Value.
Referenced by AddHash(), and operator<<().
AddInteger() [1/8]
void FCbWriter::AddInteger (FUtf8StringView Name, int32 Value) inline
Write an integer field.
Definition at line 180 of file CompactBinaryWriter.h.
References AddInteger(), Name, SetName(), and Value.
Referenced by AddInteger(), operator<<(), operator<<(), operator<<(), and operator<<().
AddInteger() [2/8]
void FCbWriter::AddInteger (FUtf8StringView Name, int64 Value) inline
Write an integer field.
Definition at line 183 of file CompactBinaryWriter.h.
References AddInteger(), Name, SetName(), and Value.
Referenced by AddInteger().
AddInteger() [3/8]
void FCbWriter::AddInteger (FUtf8StringView Name, uint32 Value) inline
Write an integer field.
Definition at line 186 of file CompactBinaryWriter.h.
References AddInteger(), Name, SetName(), and Value.
Referenced by AddInteger().
AddInteger() [4/8]
void FCbWriter::AddInteger (FUtf8StringView Name, uint64 Value) inline
Write an integer field.
Definition at line 189 of file CompactBinaryWriter.h.
References AddInteger(), Name, SetName(), and Value.
Referenced by AddInteger().
AddInteger() [5/8]
void FCbWriter::AddInteger (int32 Value)
References Value.
AddInteger() [6/8]
void FCbWriter::AddInteger (int64 Value)
References Value.
AddInteger() [7/8]
void FCbWriter::AddInteger (uint32 Value)
References Value.
AddInteger() [8/8]
void FCbWriter::AddInteger (uint64 Value)
References Value.
AddNull() [1/2]
void FCbWriter::AddNull ()
Referenced by operator<<().
AddNull() [2/2]
void FCbWriter::AddNull (FUtf8StringView Name) inline
Write a null field.
Definition at line 157 of file CompactBinaryWriter.h.
References AddNull(), Name, and SetName().
Referenced by AddNull().
AddObject() [1/4]
void FCbWriter::AddObject (const FCbObject & Value)
References Value.
AddObject() [2/4]
void FCbWriter::AddObject (const FCbObjectView & Value)
References Value.
AddObject() [3/4]
void FCbWriter::AddObject (FUtf8StringView Name, const FCbObject & Value) inline
Copy the value (not the name) of an existing object.
Holds a reference if owned.
Definition at line 140 of file CompactBinaryWriter.h.
References AddObject(), Name, SetName(), and Value.
Referenced by AddObject().
AddObject() [4/4]
void FCbWriter::AddObject (FUtf8StringView Name, const FCbObjectView & Value) inline
Copy the value (not the name) of an existing object.
Definition at line 137 of file CompactBinaryWriter.h.
References AddObject(), Name, SetName(), and Value.
Referenced by AddObject(), operator<<(), and operator<<().
AddObjectAttachment() [1/2]
void FCbWriter::AddObjectAttachment (const FIoHash & Value)
References Value.
AddObjectAttachment() [2/2]
void FCbWriter::AddObjectAttachment (FUtf8StringView Name, const FIoHash & Value) inline
Write a field referencing an object attachment by its hash.
Definition at line 204 of file CompactBinaryWriter.h.
References AddObjectAttachment(), Name, SetName(), and Value.
Referenced by AddObjectAttachment().
AddObjectId() [1/2]
void FCbWriter::AddObjectId (const FCbObjectId & Value)
References Value.
AddObjectId() [2/2]
void FCbWriter::AddObjectId (FUtf8StringView Name, const FCbObjectId & Value) inline
Write an ObjectId field.
Definition at line 237 of file CompactBinaryWriter.h.
References AddObjectId(), Name, SetName(), and Value.
Referenced by AddObjectId(), and operator<<().
AddString() [1/4]
void FCbWriter::AddString (FUtf8StringView Name, FUtf8StringView Value) inline
Write a string field by copying the UTF-8 value.
Definition at line 173 of file CompactBinaryWriter.h.
References AddString(), Name, SetName(), and Value.
Referenced by AddString(), operator<<(), operator<<(), and SerializeForLog().
AddString() [2/4]
void FCbWriter::AddString (FUtf8StringView Name, FWideStringView Value) inline
Write a string field by converting the UTF-16 value to UTF-8.
Definition at line 176 of file CompactBinaryWriter.h.
References AddString(), Name, SetName(), and Value.
Referenced by AddString().
AddString() [3/4]
void FCbWriter::AddString (FUtf8StringView Value)
References Value.
AddString() [4/4]
void FCbWriter::AddString (FWideStringView Value)
References Value.
AddTimeSpan() [1/2]
void FCbWriter::AddTimeSpan (FTimespan Value)
References Value.
AddTimeSpan() [2/2]
void FCbWriter::AddTimeSpan (FUtf8StringView Name, FTimespan Value)
Write a time span field.
References Name, and Value.
AddTimeSpanTicks() [1/2]
void FCbWriter::AddTimeSpanTicks (FUtf8StringView Name, int64 Ticks) inline
Write a time span field with the specified count of 100ns ticks.
Definition at line 229 of file CompactBinaryWriter.h.
References AddTimeSpanTicks(), Name, and SetName().
Referenced by AddTimeSpanTicks().
AddTimeSpanTicks() [2/2]
void FCbWriter::AddTimeSpanTicks (int64 Ticks)
AddUuid() [1/2]
void FCbWriter::AddUuid (const FGuid & Value)
References Value.
AddUuid() [2/2]
void FCbWriter::AddUuid (FUtf8StringView Name, const FGuid & Value) inline
Write a UUID field.
Definition at line 217 of file CompactBinaryWriter.h.
References AddUuid(), Name, SetName(), and Value.
Referenced by AddUuid(), and operator<<().
BeginArray() [1/2]
void FCbWriter::BeginArray ()
Referenced by operator<<().
BeginArray() [2/2]
void FCbWriter::BeginArray (FUtf8StringView Name) inline
Begin a new array.
Must have a matching call to EndArray.
Definition at line 144 of file CompactBinaryWriter.h.
References BeginArray(), Name, and SetName().
Referenced by BeginArray(), operator<<(), and SerializeForLog().
BeginField()
void FCbWriter::BeginField () private
Begin writing a field.
May be called twice for named fields.
BeginObject() [1/2]
void FCbWriter::BeginObject ()
BeginObject() [2/2]
void FCbWriter::BeginObject (FUtf8StringView Name) inline
Begin a new object.
Must have a matching call to EndObject.
Definition at line 131 of file CompactBinaryWriter.h.
References BeginObject(), Name, and SetName().
Referenced by BeginObject(), and SerializeForLog().
EndArray()
void FCbWriter::EndArray ()
End an array after its fields have been written.
Referenced by operator<<(), operator<<(), and SerializeForLog().
EndField()
void FCbWriter::EndField (ECbFieldType Type) private
Finish writing a field by writing its type.
EndObject()
void FCbWriter::EndObject ()
End an object after its fields have been written.
Referenced by SerializeForLog().
GetActiveName()
FUtf8StringView FCbWriter::GetActiveName () const private
Returns a view of the name of the active field, if any, otherwise the empty view.
GetSaveSize()
uint64 FCbWriter::GetSaveSize () const
The size of buffer (in bytes) required to serialize the fields that have been written.
It is not valid to call this function in the middle of writing an object, array, or field.
MakeFieldsUniform()
void FCbWriter::MakeFieldsUniform (int64 FieldBeginOffset, int64 FieldEndOffset) private
Remove field types after the first to make the sequence uniform.
operator<<() [1/30]
FCbWriter & FCbWriter::operator<< (bool Value) inline
Definition at line 416 of file CompactBinaryWriter.h.
References FCbWriter(), AddBool(), and Value.
operator<<() [2/30]
FCbWriter & FCbWriter::operator<< (const ANSICHAR * NameOrValue) inline
Write the field name if valid in this state, otherwise write the string value.
Definition at line 304 of file CompactBinaryWriter.h.
References FCbWriter().
operator<<() [3/30]
FCbWriter & FCbWriter::operator<< (const FAnsiString & Value)
References FCbWriter(), and Value.
operator<<() [4/30]
FCbWriter & FCbWriter::operator<< (const FCbArray & Value) inline
Definition at line 345 of file CompactBinaryWriter.h.
References FCbWriter(), AddArray(), and Value.
operator<<() [5/30]
FCbWriter & FCbWriter::operator<< (const FCbArrayView & Value) inline
Definition at line 339 of file CompactBinaryWriter.h.
References FCbWriter(), AddArray(), and Value.
operator<<() [6/30]
FCbWriter & FCbWriter::operator<< (const FCbAttachment & Attachment) inline
Definition at line 422 of file CompactBinaryWriter.h.
References FCbWriter(), and AddAttachment().
operator<<() [7/30]
FCbWriter & FCbWriter::operator<< (const FCbField & Value) inline
Definition at line 321 of file CompactBinaryWriter.h.
References FCbWriter(), AddField(), and Value.
operator<<() [8/30]
FCbWriter & FCbWriter::operator<< (const FCbFieldView & Value) inline
Definition at line 315 of file CompactBinaryWriter.h.
References FCbWriter(), AddField(), and Value.
operator<<() [9/30]
FCbWriter & FCbWriter::operator<< (const FCbObject & Value) inline
Definition at line 333 of file CompactBinaryWriter.h.
References FCbWriter(), AddObject(), and Value.
operator<<() [10/30]
FCbWriter & FCbWriter::operator<< (const FCbObjectId & Value) inline
Definition at line 443 of file CompactBinaryWriter.h.
References FCbWriter(), AddObjectId(), and Value.
operator<<() [11/30]
FCbWriter & FCbWriter::operator<< (const FCbObjectView & Value) inline
Definition at line 327 of file CompactBinaryWriter.h.
References FCbWriter(), AddObject(), and Value.
operator<<() [12/30]
FCbWriter & FCbWriter::operator<< (const FGuid & Value) inline
Definition at line 434 of file CompactBinaryWriter.h.
References FCbWriter(), AddUuid(), and Value.
operator<<() [13/30]
FCbWriter & FCbWriter::operator<< (const FIoHash & Value) inline
Definition at line 428 of file CompactBinaryWriter.h.
References FCbWriter(), AddHash(), and Value.
operator<<() [14/30]
FCbWriter & FCbWriter::operator<< (const FString & Value)
References FCbWriter(), and Value.
operator<<() [15/30]
FCbWriter & FCbWriter::operator<< (const FUtf8String & Value)
References FCbWriter(), and Value.
operator<<() [16/30]
template<typename T, typename Allocator, std::void_t< decltype(std::declval< FCbWriter & >()<< std::declval< const T & >())> * = nullptr> FCbWriter & FCbWriter::operator<< (const TArray< T, Allocator > & Value) inline
Definition at line 456 of file CompactBinaryWriter.h.
References FCbWriter(), BeginArray(), EndArray(), and Value.
operator<<() [17/30]
FCbWriter & FCbWriter::operator<< (const UTF8CHAR * NameOrValue) inline
Write the field name if valid in this state, otherwise write the string value.
Definition at line 310 of file CompactBinaryWriter.h.
References FCbWriter().
operator<<() [18/30]
FCbWriter & FCbWriter::operator<< (const WIDECHAR * Value) inline
Definition at line 363 of file CompactBinaryWriter.h.
References FCbWriter(), AddString(), and Value.
operator<<() [19/30]
FCbWriter & FCbWriter::operator<< (double Value) inline
Definition at line 410 of file CompactBinaryWriter.h.
References FCbWriter(), AddFloat(), and Value.
operator<<() [20/30]
FCbWriter & FCbWriter::operator<< (FDateTime Value)
References FCbWriter(), and Value.
operator<<() [21/30]
FCbWriter & FCbWriter::operator<< (float Value) inline
Definition at line 404 of file CompactBinaryWriter.h.
References FCbWriter(), AddFloat(), and Value.
operator<<() [22/30]
FCbWriter & FCbWriter::operator<< (FName Value)
References FCbWriter(), Allocator, and Value.
operator<<() [23/30]
FCbWriter & FCbWriter::operator<< (FTimespan Value)
References FCbWriter(), and Value.
operator<<() [24/30]
FCbWriter & FCbWriter::operator<< (FUtf8StringView NameOrValue) inline
Write the field name if valid in this state, otherwise write the string value.
Definition at line 297 of file CompactBinaryWriter.h.
References FCbWriter(), and SetNameOrAddString().
operator<<() [25/30]
FCbWriter & FCbWriter::operator<< (FWideStringView Value) inline
Definition at line 357 of file CompactBinaryWriter.h.
References FCbWriter(), AddString(), and Value.
operator<<() [26/30]
FCbWriter & FCbWriter::operator<< (int32 Value) inline
Definition at line 369 of file CompactBinaryWriter.h.
References FCbWriter(), AddInteger(), and Value.
operator<<() [27/30]
FCbWriter & FCbWriter::operator<< (int64 Value) inline
Definition at line 375 of file CompactBinaryWriter.h.
References FCbWriter(), AddInteger(), and Value.
operator<<() [28/30]
FCbWriter & FCbWriter::operator<< (nullptr_t) inline
Definition at line 351 of file CompactBinaryWriter.h.
References FCbWriter(), and AddNull().
operator<<() [29/30]
FCbWriter & FCbWriter::operator<< (uint32 Value) inline
Definition at line 381 of file CompactBinaryWriter.h.
References FCbWriter(), AddInteger(), and Value.
operator<<() [30/30]
FCbWriter & FCbWriter::operator<< (uint64 Value) inline
Definition at line 387 of file CompactBinaryWriter.h.
References FCbWriter(), AddInteger(), and Value.
operator=()
FCbWriter & FCbWriter::operator= (const FCbWriter &) delete
References FCbWriter().
Reset()
void FCbWriter::Reset ()
Empty the writer without releasing any allocated memory.
Save() [1/3]
FCbFieldIterator FCbWriter::Save () const
Serialize the field(s) to an owned buffer and return it as an iterator.
It is not valid to call this function in the middle of writing an object, array, or field. The writer remains valid for further use when this function returns.
Referenced by UE::Cook::FCookDependency::operator<<, and UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
Save() [2/3]
void FCbWriter::Save (FArchive & Ar) const
Serialize the field(s) to an archive.
It is not valid to call this function in the middle of writing an object, array, or field. The writer remains valid for further use when this function returns.
Parameters
Ar An archive to write to. Exactly GetSaveSize() bytes will be written.
References Ar.
Save() [3/3]
FCbFieldViewIterator FCbWriter::Save (FMutableMemoryView Buffer) const
Serialize the field(s) to memory.
It is not valid to call this function in the middle of writing an object, array, or field. The writer remains valid for further use when this function returns.
Parameters
Buffer A mutable memory view to write to. Must be exactly GetSaveSize() bytes.
Returns
An iterator for the field(s) written to the buffer.
References Buffer.
SetName()
FCbWriter & FCbWriter::SetName (FUtf8StringView Name)
Sets the name of the next field to be written.
It is not valid to call this function when writing a field inside an array. Names must be valid UTF-8 and must be unique within an object.
References FCbWriter(), and Name.
Referenced by AddArray(), AddArray(), AddAttachment(), AddBinary(), AddBinary(), AddBinary(), AddBinary(), AddBinaryAttachment(), AddBool(), AddCustom(), AddCustom(), AddDateTimeTicks(), AddField(), AddField(), AddFloat(), AddFloat(), AddHash(), AddInteger(), AddInteger(), AddInteger(), AddInteger(), AddNull(), AddObject(), AddObject(), AddObjectAttachment(), AddObjectId(), AddString(), AddString(), AddTimeSpanTicks(), AddUuid(), BeginArray(), and BeginObject().
SetNameOrAddString()
void FCbWriter::SetNameOrAddString (FUtf8StringView NameOrValue) private
Set the field name if valid in this state, otherwise write add a string field.
Referenced by operator<<().
Field Documentation
Data
TArray64<uint8> FCbWriter::Data private
Definition at line 292 of file CompactBinaryWriter.h.
States
TArray<FState> FCbWriter::States private
Definition at line 293 of file CompactBinaryWriter.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinaryWriter.h