Unreal Engine 5.6 C++ API: FAAArrayQueue< T > Class Template Reference
FAAArrayQueue< T > Class Template Reference
#include "FAAArrayQueue.h"
Data Structures
class DequeueHazard
class EnqueueHazard
struct Node
Public Member Functions
FAAArrayQueue ()
~FAAArrayQueue ()
T * dequeue ()
T * dequeue (DequeueHazard &Hazard)
void enqueue (T *item)
void enqueue (T *item, EnqueueHazard &Hazard)
DequeueHazard getHeadHazard ()
EnqueueHazard getTailHazard ()
Private Member Functions
bool casHead (Node *cmp, Node *val)
bool casTail (Node *cmp, Node *val)
template<typename HazardType>
T * dequeueInternal (HazardType &Hazard)
template<typename HazardType>
void enqueueInternal (T *item, HazardType &Hazard)
Static Private Member Functions
static T * GetTakenPointer ()
Private Attributes
FHazardPointerCollection Hazards
std::atomic< Node * > head
std::atomic< Node * > tail
Static Private Attributes
static constexpr long BUFFER_SIZE = 1024
Detailed Description
template<typename T>
class FAAArrayQueue< T >
Fetch-And-Add Array Queue
Each node has one array but we don't search for a vacant entry. Instead, we use FAA to obtain an index in the array, for enqueueing or dequeuing.
There are some similarities between this queue and the basic queue in YMC: http://chaoran.me/assets/pdf/wfq-ppopp16.pdf but it's not the same because the queue in listing 1 is obstruction-free, while our algorithm is lock-free. In FAAArrayQueue eventually a new node will be inserted (using Michael-Scott's algorithm) and it will have an item pre-filled in the first position, which means that at most, after BUFFER_SIZE steps, one item will be enqueued (and it can then be dequeued). This kind of progress is lock-free.
Each entry in the array may contain one of three possible values:
A valid item that has been enqueued;
nullptr, which means no item has yet been enqueued in that position;
taken, a special value that means there was an item but it has been dequeued;
Enqueue algorithm: FAA + CAS(null,item) Dequeue algorithm: FAA + CAS(item,taken) Consistency: Linearizable enqueue() progress: lock-free dequeue() progress: lock-free Memory Reclamation: Hazard Pointers (lock-free) Uncontended enqueue: 1 FAA + 1 CAS + 1 HP Uncontended dequeue: 1 FAA + 1 CAS + 1 HP
Lock-Free Linked List as described in Maged Michael and Michael Scott's paper: http://www.cs.rochester.edu/~scott/papers/1996_PODC_queues.pdf Simple, Fast, and Practical Non-Blocking and Blocking Concurrent Queue Algorithms
The paper on Hazard Pointers is named "Hazard Pointers: Safe Memory Reclamation for Lock-Free objects" and it is available here: http://web.cecs.pdx.edu/~walpole/class/cs510/papers/11.pdf
Author
Pedro Ramalhete
Andreia Correia
Definition at line 80 of file FAAArrayQueue.h.
Constructor & Destructor Documentation
FAAArrayQueue()
template<typename T> FAAArrayQueue< T >::FAAArrayQueue () inline
Definition at line 129 of file FAAArrayQueue.h.
~FAAArrayQueue()
template<typename T> FAAArrayQueue< T >::~FAAArrayQueue () inline
Definition at line 137 of file FAAArrayQueue.h.
Member Function Documentation
casHead()
template<typename T> bool FAAArrayQueue< T >::casHead (Node * cmp, Node * val) inline private
Definition at line 113 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< FTask >::dequeueInternal().
casTail()
template<typename T> bool FAAArrayQueue< T >::casTail (Node * cmp, Node * val) inline private
Definition at line 108 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< FTask >::enqueueInternal().
dequeue() [1/2]
template<typename T> T * FAAArrayQueue< T >::dequeue () inline
Definition at line 301 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< FTask >::~FAAArrayQueue().
dequeue() [2/2]
template<typename T> T * FAAArrayQueue< T >::dequeue (DequeueHazard & Hazard) inline
Definition at line 291 of file FAAArrayQueue.h.
dequeueInternal()
template<typename T> template<typename HazardType> T * FAAArrayQueue< T >::dequeueInternal (HazardType & Hazard) inline private
Definition at line 240 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< FTask >::dequeue(), and FAAArrayQueue< FTask >::dequeue().
enqueue() [1/2]
template<typename T> void FAAArrayQueue< T >::enqueue (T * item) inline
Definition at line 214 of file FAAArrayQueue.h.
enqueue() [2/2]
template<typename T> void FAAArrayQueue< T >::enqueue (T * item, EnqueueHazard & Hazard) inline
Definition at line 209 of file FAAArrayQueue.h.
enqueueInternal()
template<typename T> template<typename HazardType> void FAAArrayQueue< T >::enqueueInternal (T * item, HazardType & Hazard) inline private
Definition at line 163 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< FTask >::enqueue(), and FAAArrayQueue< FTask >::enqueue().
getHeadHazard()
template<typename T> DequeueHazard FAAArrayQueue< T >::getHeadHazard () inline
Definition at line 296 of file FAAArrayQueue.h.
getTailHazard()
template<typename T> EnqueueHazard FAAArrayQueue< T >::getTailHazard () inline
Definition at line 204 of file FAAArrayQueue.h.
GetTakenPointer()
template<typename T> T * FAAArrayQueue< T >::GetTakenPointer () inline static private
Definition at line 123 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< FTask >::dequeueInternal().
Field Documentation
BUFFER_SIZE
template<typename T> long FAAArrayQueue< T >::BUFFER_SIZE = 1024 static constexpr private
Definition at line 82 of file FAAArrayQueue.h.
Referenced by FAAArrayQueue< T >::Node::Node().
Hazards
template<typename T> FHazardPointerCollection FAAArrayQueue< T >::Hazards private
Definition at line 122 of file FAAArrayQueue.h.
head
template<typename T> std::atomic<Node*> FAAArrayQueue< T >::head private
Definition at line 119 of file FAAArrayQueue.h.
tail
template<typename T> std::atomic<Node*> FAAArrayQueue< T >::tail private
Definition at line 120 of file FAAArrayQueue.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Containers/FAAArrayQueue.h