Unreal Engine 5.6 C++ API: FMaterialVirtualTextureStack Class Reference
FMaterialVirtualTextureStack Class Reference
#include "MaterialShared.h"
Public Member Functions
FMaterialVirtualTextureStack ()
FMaterialVirtualTextureStack (int32 InPreallocatedStackTextureIndex)
Construct with a texture index when this references a preallocated VT stack (for example when we are using a URuntimeVirtualTexture).
uint32 AddLayer ()
Add space for a layer in the stack.
bool AreLayersFull () const
Returns true if we have allocated the maximum number of layers for this stack.
int32 FindLayer (int32 UniformExpressionIndex) const
Find the layer in the stack that was set with this expression index.
uint32 GetNumLayers () const
Get the number of layers allocated in the stack.
void GetTextureValue (const FMaterialRenderContext &Context, const FUniformExpressionSet &UniformExpressionSet, const URuntimeVirtualTexture *&OutValue) const
Get the URuntimeVirtualTexture object if one was used to initialize this stack.
void GetTextureValue (const FMaterialRenderContext &Context, const FUniformExpressionSet &UniformExpressionSet, const USparseVolumeTexture *&OutValue) const
Get the USparseVolumeTexture object if one was used to initialize this stack.
void GetTextureValues (const FMaterialRenderContext &Context, const FUniformExpressionSet &UniformExpressionSet, UTexture const **OutValues) const
Get the array of UTexture objects for the expressions that in the layers of this stack.
bool IsPreallocatedStack () const
Returns true if this is a stack that with a preallocated layout of layers (for example when we are using a URuntimeVirtualTexture).
LAYOUT_ARRAY (int32, LayerUniformExpressionIndices, VIRTUALTEXTURE_SPACE_MAXLAYERS)
Indices of the expressions that were set to layers in this stack.
LAYOUT_FIELD (int32, PreallocatedStackTextureIndex)
Index of a texture reference if we create a stack from a single known texture that has it's own layer stack.
LAYOUT_FIELD (uint32, NumLayers)
Number of layers that have been allocated in this stack.
void Serialize (FArchive &Ar)
uint32 SetLayer (int32 LayerIndex, int32 UniformExpressionIndex)
Set an expression index at a layer in the stack.
Private Member Functions
DECLARE_TYPE_LAYOUT (FMaterialVirtualTextureStack, NonVirtual)
Friends
bool operator!= (const FMaterialVirtualTextureStack &Lhs, const FMaterialVirtualTextureStack &Rhs)
FArchive & operator<< (FArchive &Ar, FMaterialVirtualTextureStack &Stack)
bool operator== (const FMaterialVirtualTextureStack &Lhs, const FMaterialVirtualTextureStack &Rhs)
Detailed Description
Definition at line 377 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterialVirtualTextureStack() [1/2]
FMaterialVirtualTextureStack::FMaterialVirtualTextureStack ()
Referenced by DECLARE_TYPE_LAYOUT(), operator!=, operator<<, and operator==.
FMaterialVirtualTextureStack() [2/2]
FMaterialVirtualTextureStack::FMaterialVirtualTextureStack (int32 InPreallocatedStackTextureIndex)
Construct with a texture index when this references a preallocated VT stack (for example when we are using a URuntimeVirtualTexture).
Member Function Documentation
AddLayer()
uint32 FMaterialVirtualTextureStack::AddLayer ()
Add space for a layer in the stack.
Returns an index that can be used for SetLayer().
AreLayersFull()
bool FMaterialVirtualTextureStack::AreLayersFull () const inline
Returns true if we have allocated the maximum number of layers for this stack.
Definition at line 392 of file MaterialShared.h.
References VIRTUALTEXTURE_SPACE_MAXLAYERS.
DECLARE_TYPE_LAYOUT()
FMaterialVirtualTextureStack::DECLARE_TYPE_LAYOUT (FMaterialVirtualTextureStack , NonVirtual) private
References FMaterialVirtualTextureStack().
FindLayer()
int32 FMaterialVirtualTextureStack::FindLayer (int32 UniformExpressionIndex) const
Find the layer in the stack that was set with this expression index.
GetNumLayers()
uint32 FMaterialVirtualTextureStack::GetNumLayers () const inline
Get the number of layers allocated in the stack.
Definition at line 390 of file MaterialShared.h.
GetTextureValue() [1/2]
void FMaterialVirtualTextureStack::GetTextureValue (const FMaterialRenderContext & Context, const FUniformExpressionSet & UniformExpressionSet, const URuntimeVirtualTexture *& OutValue) const
Get the URuntimeVirtualTexture object if one was used to initialize this stack.
GetTextureValue() [2/2]
void FMaterialVirtualTextureStack::GetTextureValue (const FMaterialRenderContext & Context, const FUniformExpressionSet & UniformExpressionSet, const USparseVolumeTexture *& OutValue) const
Get the USparseVolumeTexture object if one was used to initialize this stack.
GetTextureValues()
void FMaterialVirtualTextureStack::GetTextureValues (const FMaterialRenderContext & Context, const FUniformExpressionSet & UniformExpressionSet, UTexture const ** OutValues) const
Get the array of UTexture objects for the expressions that in the layers of this stack.
Can return nullptr objects for layers that don't hold UTexture2D references.
IsPreallocatedStack()
bool FMaterialVirtualTextureStack::IsPreallocatedStack () const inline
Returns true if this is a stack that with a preallocated layout of layers (for example when we are using a URuntimeVirtualTexture).
Definition at line 397 of file MaterialShared.h.
References INDEX_NONE.
LAYOUT_ARRAY()
FMaterialVirtualTextureStack::LAYOUT_ARRAY (int32 , LayerUniformExpressionIndices , VIRTUALTEXTURE_SPACE_MAXLAYERS)
Indices of the expressions that were set to layers in this stack.
References VIRTUALTEXTURE_SPACE_MAXLAYERS.
LAYOUT_FIELD() [1/2]
FMaterialVirtualTextureStack::LAYOUT_FIELD (int32 , PreallocatedStackTextureIndex)
Index of a texture reference if we create a stack from a single known texture that has it's own layer stack.
LAYOUT_FIELD() [2/2]
FMaterialVirtualTextureStack::LAYOUT_FIELD (uint32 , NumLayers)
Number of layers that have been allocated in this stack.
Serialize()
void FMaterialVirtualTextureStack::Serialize (FArchive & Ar)
References Ar.
Referenced by operator<<.
SetLayer()
uint32 FMaterialVirtualTextureStack::SetLayer (int32 LayerIndex, int32 UniformExpressionIndex)
Set an expression index at a layer in the stack.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FMaterialVirtualTextureStack & Lhs, const FMaterialVirtualTextureStack & Rhs) friend
Definition at line 429 of file MaterialShared.h.
References FMaterialVirtualTextureStack(), and operator==.
operator<<
FArchive & operator<< (FArchive & Ar, FMaterialVirtualTextureStack & Stack) friend
Definition at line 407 of file MaterialShared.h.
References FMaterialVirtualTextureStack(), Ar, and Serialize().
operator==
bool operator== (const FMaterialVirtualTextureStack & Lhs, const FMaterialVirtualTextureStack & Rhs) friend
Definition at line 413 of file MaterialShared.h.
References FMaterialVirtualTextureStack().
Referenced by operator!=.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialShared.h