Unreal Engine 5.6 C++ API: FLightMap Class Reference
FLightMap Class Reference abstract
The abstract base class of 1D and 2D light-maps.
#include "LightMap.h"
Public Types
enum { LMT_None = 0 , LMT_1D = 1 , LMT_2D = 2 }
Public Member Functions
FLightMap ()
Default constructor.
virtual ~FLightMap ()
Destructor.
void AddRef ()
virtual void AddReferencedObjects (FReferenceCollector &Collector)
FORCEINLINE bool AllowsHighQualityLightmaps () const
bool ContainsLight (const FGuid &LightGuid) const
Checks if a light is stored in this light-map.
virtual FLightMapInteraction GetInteraction (ERHIFeatureLevel::Type InFeatureLevel) const =0
virtual FLightMap2D * GetLightMap2D ()
virtual const FLightMap2D * GetLightMap2D () const
virtual FShadowMapInteraction GetShadowInteraction (ERHIFeatureLevel::Type InFeatureLevel) const
void Release ()
virtual void Serialize (FArchive &Ar)
Data Fields
TArray< FGuid > LightGuids
The GUIDs of lights which this light-map stores.
Protected Member Functions
virtual void Cleanup ()
Called when the light-map is no longer referenced.
Protected Attributes
bool bAllowHighQualityLightMaps
Indicates whether the lightmap is being used for directional or simple lighting.
Private Attributes
int32 NumRefs
Additional Inherited Members
Private Member Functions inherited from FDeferredCleanupInterface
virtual ~FDeferredCleanupInterface ()
Detailed Description
The abstract base class of 1D and 2D light-maps.
Definition at line 49 of file LightMap.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
LMT_None
LMT_1D
LMT_2D
Definition at line 52 of file LightMap.h.
Constructor & Destructor Documentation
FLightMap()
FLightMap::FLightMap ()
Default constructor.
~FLightMap()
virtual FLightMap::~FLightMap () inline virtual
Destructor.
Definition at line 66 of file LightMap.h.
References check, and NumRefs.
Member Function Documentation
AddRef()
void FLightMap::AddRef () inline
Definition at line 89 of file LightMap.h.
References check, IsInAsyncLoadingThread, IsInGameThread(), and NumRefs.
AddReferencedObjects()
virtual void FLightMap::AddReferencedObjects (FReferenceCollector & Collector) inline virtual
Reimplemented in FLightMap2D.
Definition at line 79 of file LightMap.h.
AllowsHighQualityLightmaps()
FORCEINLINE bool FLightMap::AllowsHighQualityLightmaps () const inline
Returns
true if high quality lightmaps are allowed
Definition at line 107 of file LightMap.h.
References bAllowHighQualityLightMaps, and FORCEINLINE.
Cleanup()
virtual void FLightMap::Cleanup () protected virtual
Called when the light-map is no longer referenced.
Should release the lightmap's resources.
Referenced by Release().
ContainsLight()
bool FLightMap::ContainsLight (const FGuid & LightGuid) const inline
Checks if a light is stored in this light-map.
Parameters
LightGuid - The GUID of the light to check for.
Returns
True if the light is stored in the light-map.
Definition at line 73 of file LightMap.h.
References INDEX_NONE, and LightGuids.
GetInteraction()
virtual FLightMapInteraction FLightMap::GetInteraction (ERHIFeatureLevel::Type InFeatureLevel) const pure virtual
Implemented in FLegacyLightMap1D, and FLightMap2D.
GetLightMap2D() [1/2]
virtual FLightMap2D * FLightMap::GetLightMap2D () inline virtual
Reimplemented in FLightMap2D.
Definition at line 85 of file LightMap.h.
GetLightMap2D() [2/2]
virtual const FLightMap2D * FLightMap::GetLightMap2D () const inline virtual
Reimplemented in FLightMap2D.
Definition at line 86 of file LightMap.h.
GetShadowInteraction()
virtual FShadowMapInteraction FLightMap::GetShadowInteraction (ERHIFeatureLevel::Type InFeatureLevel) const inline virtual
Reimplemented in FLightMap2D.
Definition at line 82 of file LightMap.h.
References FShadowMapInteraction::None().
Release()
void FLightMap::Release () inline
Definition at line 94 of file LightMap.h.
References check, checkSlow, Cleanup(), IsInAsyncLoadingThread, IsInGameThread(), and NumRefs.
Serialize()
virtual void FLightMap::Serialize (FArchive & Ar) virtual
Reimplemented in FLegacyLightMap1D, and FLightMap2D.
References Ar.
Field Documentation
bAllowHighQualityLightMaps
bool FLightMap::bAllowHighQualityLightMaps protected
Indicates whether the lightmap is being used for directional or simple lighting.
Definition at line 115 of file LightMap.h.
Referenced by FLegacyLightMap1D::FLegacyLightMap1D(), and AllowsHighQualityLightmaps().
LightGuids
TArray<FGuid> FLightMap::LightGuids
The GUIDs of lights which this light-map stores.
Definition at line 60 of file LightMap.h.
Referenced by ContainsLight().
NumRefs
int32 FLightMap::NumRefs private
Definition at line 123 of file LightMap.h.
Referenced by ~FLightMap(), AddRef(), and Release().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/LightMap.h