Unreal Engine 5.6 C++ API: UE::Core::FVersePath Class Reference
UE::Core::FVersePath Class Reference
#include "VersePath.h"
Public Member Functions
FVersePath ()=default
FVersePath (const FVersePath &)=default
FVersePath (FVersePath &&)=default
~FVersePath ()=default
FStringView AsStringView () const
int32 Compare (const FVersePath &Other) const
Lexicographically tests how this Verse path compares to the Other given Verse path.
bool IsBaseOf (const FVersePath &Other, FStringView *OutLeafPath=nullptr) const
Tests whether this Verse path is a base Verse path of Other.
bool IsValid () const
operator bool () const
const TCHAR * operator* () const
FVersePath & operator= (const FVersePath &)=default
FVersePath & operator= (FVersePath &&)=default
FString ToString () &&
const FString & ToString () const &
Static Public Member Functions
static bool IsValidDomain (const TCHAR *String, FText *OutErrorMessage=nullptr)
static bool IsValidDomain (const TCHAR *String, int32 Len, FText *OutErrorMessage=nullptr)
static bool IsValidFullPath (const TCHAR *String, FText *OutErrorMessage=nullptr)
static bool IsValidFullPath (const TCHAR *String, int32 Len, FText *OutErrorMessage=nullptr)
static bool IsValidIdent (const TCHAR *String, FText *OutErrorMessage=nullptr, const FText *IdentTermReplacement=nullptr)
static bool IsValidIdent (const TCHAR *String, int32 Len, FText *OutErrorMessage=nullptr, const FText *IdentTermReplacement=nullptr)
static bool IsValidSubpath (const TCHAR *String, FText *OutErrorMessage=nullptr)
static bool IsValidSubpath (const TCHAR *String, int32 Len, FText *OutErrorMessage=nullptr)
static bool TryMake (FVersePath &OutPath, const FString &Path, FText *OutErrorMessage=nullptr)
static bool TryMake (FVersePath &OutPath, FString &&Path, FText *OutErrorMessage=nullptr)
Private Attributes
FString PathString
Friends
bool operator!= (const FVersePath &Lhs, const FVersePath &Rhs)
FArchive & operator<< (FArchive &Ar, FVersePath &VersePath)
bool operator== (const FVersePath &Lhs, const FVersePath &Rhs)
Detailed Description
Definition at line 12 of file VersePath.h.
Constructor & Destructor Documentation
FVersePath() [1/3]
UE::Core::FVersePath::FVersePath () nodiscard default
Referenced by FVersePath(), FVersePath(), Compare(), IsBaseOf(), operator!=, operator<<, operator=(), operator=(), operator==, TryMake(), and TryMake().
FVersePath() [2/3]
UE::Core::FVersePath::FVersePath (FVersePath &&) nodiscard default
References FVersePath().
FVersePath() [3/3]
UE::Core::FVersePath::FVersePath (const FVersePath &) nodiscard default
References FVersePath().
~FVersePath()
UE::Core::FVersePath::~FVersePath () default
Member Function Documentation
AsStringView()
FStringView UE::Core::FVersePath::AsStringView () const inline nodiscard
Definition at line 79 of file VersePath.h.
References PathString.
Compare()
int32 UE::Core::FVersePath::Compare (const FVersePath & Other) const inline nodiscard
Lexicographically tests how this Verse path compares to the Other given Verse path.
Parameters
Other The Verse path to test against
Returns
0 if equal, negative if less than, positive if greater than
Definition at line 48 of file VersePath.h.
References FVersePath(), ESearchCase::CaseSensitive, Other, and PathString.
IsBaseOf()
bool UE::Core::FVersePath::IsBaseOf (const FVersePath & Other, FStringView * OutLeafPath = nullptr) const nodiscard
Tests whether this Verse path is a base Verse path of Other.
Examples: "/domain1/path1", "/domain1/path1" -> true, "" "/domain1/path1", "/domain1/path1/leaf" -> true, "leaf" "/domain1/path1", "/domain1/path1/path2/leaf" -> true, "path2/leaf" "/domain1/path1", "/domain1/path2/leaf" -> false, "" "/domain1/path1", "/domain2/path1/leaf" -> false, ""
Parameters
Other The Verse path to test against
OutLeafPath The path segment of Other that is relative to this Verse path, ommiting the leading '/'. Empty if the two Verse paths are equal
Returns
true if Other is relative or equal to this Verse path
References FVersePath(), and Other.
IsValid()
bool UE::Core::FVersePath::IsValid () const inline nodiscard
Definition at line 32 of file VersePath.h.
References PathString.
IsValidDomain() [1/2]
bool UE::Core::FVersePath::IsValidDomain (const TCHAR * String, FText * OutErrorMessage = nullptr) static nodiscard
IsValidDomain() [2/2]
bool UE::Core::FVersePath::IsValidDomain (const TCHAR * String, int32 Len, FText * OutErrorMessage = nullptr) static nodiscard
IsValidFullPath() [1/2]
bool UE::Core::FVersePath::IsValidFullPath (const TCHAR * String, FText * OutErrorMessage = nullptr) static nodiscard
IsValidFullPath() [2/2]
bool UE::Core::FVersePath::IsValidFullPath (const TCHAR * String, int32 Len, FText * OutErrorMessage = nullptr) static nodiscard
IsValidIdent() [1/2]
bool UE::Core::FVersePath::IsValidIdent (const TCHAR * String, FText * OutErrorMessage = nullptr, const FText * IdentTermReplacement = nullptr) static nodiscard
IsValidIdent() [2/2]
bool UE::Core::FVersePath::IsValidIdent (const TCHAR * String, int32 Len, FText * OutErrorMessage = nullptr, const FText * IdentTermReplacement = nullptr) static nodiscard
IsValidSubpath() [1/2]
bool UE::Core::FVersePath::IsValidSubpath (const TCHAR * String, FText * OutErrorMessage = nullptr) static nodiscard
IsValidSubpath() [2/2]
bool UE::Core::FVersePath::IsValidSubpath (const TCHAR * String, int32 Len, FText * OutErrorMessage = nullptr) static nodiscard
operator bool()
UE::Core::FVersePath::operator bool () const inline explicit nodiscard
Definition at line 37 of file VersePath.h.
References PathString.
operator*()
const TCHAR * UE::Core::FVersePath::operator* () const inline nodiscard
Definition at line 27 of file VersePath.h.
References PathString.
operator=() [1/2]
FVersePath & UE::Core::FVersePath::operator= (const FVersePath &) default
References FVersePath().
operator=() [2/2]
FVersePath & UE::Core::FVersePath::operator= (FVersePath &&) default
References FVersePath().
ToString() [1/2]
FString UE::Core::FVersePath::ToString () && inline nodiscard
Definition at line 74 of file VersePath.h.
References MoveTemp(), and PathString.
ToString() [2/2]
const FString & UE::Core::FVersePath::ToString () const & inline nodiscard
Definition at line 69 of file VersePath.h.
References PathString.
TryMake() [1/2]
bool UE::Core::FVersePath::TryMake (FVersePath & OutPath, const FString & Path, FText * OutErrorMessage = nullptr) static
References FVersePath(), and Path.
TryMake() [2/2]
bool UE::Core::FVersePath::TryMake (FVersePath & OutPath, FString && Path, FText * OutErrorMessage = nullptr) static
References FVersePath(), and Path.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FVersePath & Lhs, const FVersePath & Rhs) friend
References FVersePath().
operator<<
FArchive & operator<< (FArchive & Ar, FVersePath & VersePath) friend
References FVersePath(), and Ar.
operator==
bool operator== (const FVersePath & Lhs, const FVersePath & Rhs) friend
References FVersePath().
Field Documentation
PathString
FString UE::Core::FVersePath::PathString private
Definition at line 97 of file VersePath.h.
Referenced by AsStringView(), Compare(), IsValid(), operator bool(), operator*(), UE::Core::operator<<(), UE::Core::operator==(), ToString(), and ToString().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/VersePath.h