Unreal Engine 5.6 C++ API: TLockFreePointerListFIFO< T, TPaddingForCacheContention > Class Template Reference
TLockFreePointerListFIFO< T, TPaddingForCacheContention > Class Template Reference
#include "LockFreeList.h"
Public Member Functions
FORCEINLINE bool IsEmpty () const
Check if the list is empty.
T * Pop ()
Pop an item from the list or return NULL if the list is empty.
template<typename ContainerType>
void PopAll (ContainerType &Output)
Pop all items from the list.
void Push (T *NewItem)
Push an item onto the head of the list.
Additional Inherited Members
Private Member Functions inherited from FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >
FORCEINLINE FLockFreePointerFIFOBase ()
~FLockFreePointerFIFOBase ()
FORCEINLINE bool IsEmpty () const
T * Pop ()
template<typename ContainerType>
void PopAll (ContainerType &OutContainer)
void Push (T *InPayload)
Detailed Description
template<class T, int TPaddingForCacheContention>
class TLockFreePointerListFIFO< T, TPaddingForCacheContention >
Definition at line 909 of file LockFreeList.h.
Member Function Documentation
IsEmpty()
template<class T, int TPaddingForCacheContention> FORCEINLINE bool TLockFreePointerListFIFO< T, TPaddingForCacheContention >::IsEmpty () const inline nodiscard
Check if the list is empty.
Returns
true if the list is empty. CAUTION: This methods safety depends on external assumptions. For example, if another thread could add to the list at any time, the return value is no better than a best guess. As typically used, the list is not being access concurrently when this is called.
Definition at line 950 of file LockFreeList.h.
References FORCEINLINE, and FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::IsEmpty().
Pop()
template<class T, int TPaddingForCacheContention> T * TLockFreePointerListFIFO< T, TPaddingForCacheContention >::Pop () inline nodiscard
Pop an item from the list or return NULL if the list is empty.
Returns
The popped item, if any.
Definition at line 927 of file LockFreeList.h.
References FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop().
PopAll()
template<class T, int TPaddingForCacheContention> template<typename ContainerType> void TLockFreePointerListFIFO< T, TPaddingForCacheContention >::PopAll (ContainerType & Output) inline
Pop all items from the list.
Parameters
Output The array to hold the returned items. Must be empty.
Definition at line 938 of file LockFreeList.h.
References FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAll().
Push()
template<class T, int TPaddingForCacheContention> void TLockFreePointerListFIFO< T, TPaddingForCacheContention >::Push (T * NewItem) inline
Push an item onto the head of the list.
Parameters
NewItem,the new item to push on the list, cannot be NULL.
Definition at line 918 of file LockFreeList.h.
References FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Push().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LockFreeList.h