Unreal Engine 5.6 C++ API: Nanite::FFixupChunk Class Reference
Nanite::FFixupChunk Class Reference
#include "NaniteResources.h"
Data Structures
struct FHeader
Public Member Functions
FClusterFixup & GetClusterFixup (uint32 Index) const
FHierarchyFixup & GetHierarchyFixup (uint32 Index) const
uint32 GetSize () const
Static Public Member Functions
static constexpr uint32 GetSize (uint32 NumHierarchyFixups, uint32 NumClusterFixups)
Data Fields
struct Nanite::FFixupChunk::FHeader Header
Private Member Functions
uint8 * GetData () const
Detailed Description
Definition at line 277 of file NaniteResources.h.
Member Function Documentation
GetClusterFixup()
FClusterFixup & Nanite::FFixupChunk::GetClusterFixup (uint32 Index) const inline
Definition at line 290 of file NaniteResources.h.
References check, GetData(), and Header.
GetData()
uint8 * Nanite::FFixupChunk::GetData () const inline private
Definition at line 295 of file NaniteResources.h.
References Header.
Referenced by GetClusterFixup(), and GetHierarchyFixup().
GetHierarchyFixup()
FHierarchyFixup & Nanite::FFixupChunk::GetHierarchyFixup (uint32 Index) const inline
Definition at line 291 of file NaniteResources.h.
References check, GetData(), and Header.
GetSize() [1/2]
uint32 Nanite::FFixupChunk::GetSize () const inline
Definition at line 292 of file NaniteResources.h.
References GetSize(), and Header.
Referenced by GetSize(), and Nanite::FFixupChunkBuffer::Reserve().
GetSize() [2/2]
constexpr uint32 Nanite::FFixupChunk::GetSize (uint32 NumHierarchyFixups, uint32 NumClusterFixups) inline static constexpr
Definition at line 288 of file NaniteResources.h.
Referenced by Nanite::FFixupChunkBuffer::Add().
Field Documentation
Header
struct Nanite::FFixupChunk::FHeader Nanite::FFixupChunk::Header
Referenced by Nanite::FFixupChunkBuffer::Add(), GetClusterFixup(), GetData(), GetHierarchyFixup(), and GetSize().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/NaniteResources.h