Unreal Engine 5.6 C++ API: AAudioVolume Class Reference
AAudioVolume Class Reference
#include "AudioVolume.h"
Public Member Functions
bool GetEnabled () const
const FInteriorSettings & GetInteriorSettings () const
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
float GetPriority () const
const FReverbSettings & GetReverbSettings () const
const TArray< FAudioVolumeSubmixOverrideSettings > & GetSubmixOverrideSettings () const
const TArray< FAudioVolumeSubmixSendSettings > & GetSubmixSendSettings () const
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostRegisterAllComponents () override
virtual void PostUnregisterAllComponents () override
UFUNCTION () 1 void SetEnabled(bool bNewEnabled)
UFUNCTION () 1 void SetInteriorSettings(const FInteriorSettings &NewInteriorSettings)
UFUNCTION () 1 void SetPriority(float NewPriority)
UFUNCTION () 1 void SetReverbSettings(const FReverbSettings &NewReverbSettings)
UFUNCTION () 1 void SetSubmixOverrideSettings(const TArray< FAudioVolumeSubmixOverrideSettings > &NewSubmixOverrideSettings)
UFUNCTION () 1 void SetSubmixSendSettings(const TArray< FAudioVolumeSubmixSendSettings > &NewSubmixSendSettings)
Public Member Functions inherited from AVolume
virtual void CheckForErrors () override
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
bool EncompassesPoint (FVector Point, float SphereRadius=0.f, float *OutDistanceToPoint=0) const
FBoxSphereBounds GetBounds () const
virtual FName GetCustomIconName () const override
virtual bool IsLevelBoundsRelevant () const override
virtual bool IsStaticBrush () const override
virtual bool IsVolumeBrush () const override
virtual void PostEditImport () override
virtual bool ShouldCheckCollisionComponentForErrors () const
Public Member Functions inherited from ABrush
virtual bool CanDeleteSelectedActor (FText &OutReason) const override
bool CanEverAffectBSP () const
virtual bool CanReplaceSelectedActor (FText &OutReason) const override
FORCEINLINE void ClearNotForClientOrServer ()
Indicate that brush need should be loaded on client or servers.
virtual void CopyPosRotScaleFrom (ABrush *Other)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnBrushRegistered, ABrush *)
Delegate used for notifications when PostRegisterAllComponents is called for a Brush.
virtual void Destroyed () override
class UBrushComponent * GetBrushComponent () const
Returns BrushComponent subobject.
virtual FColor GetWireColor () const
Figures out the best color to use for this brushes wireframe drawing.
virtual void InitPosRotScale ()
virtual bool IsActorLabelEditable () const override
virtual bool IsBrushShape () const
virtual bool IsComponentRelevantForNavigation (UActorComponent *Component) const override
FORCEINLINE bool IsNotForClientOrServer () const
Return if true if this brush is not used for gameplay (i.e.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
virtual bool NeedsLoadForClient () const override
virtual bool NeedsLoadForServer () const override
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditMove (bool bFinished) override
virtual void PostLoad () override
virtual void RebuildNavigationData ()
virtual bool SetIsHiddenEdLayer (bool bIsHiddenEdLayer) override
virtual void SetIsTemporarilyHiddenInEditor (bool bIsHidden) override
FORCEINLINE void SetNotForClientOrServer ()
Indicate that this brush need not be loaded on client or servers.
bool ShouldExportStaticNavigableGeometry () const
virtual bool SupportsExternalPackaging () const override
virtual bool SupportsLayers () const override
UPROPERTY() uint32 bInManipulation UPROPERTY () TArray< struct FGeomSelection > SavedSelections
Flag set when we are in a manipulation (scaling, translation, brush builder param change etc.)
Private Member Functions
void AddProxy () const
void RemoveProxy () const
void TransformUpdated (USceneComponent *RootComponent, EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport)
UFUNCTION () 1 virtual void OnRep_bEnabled()
void UpdateProxy () const
UPROPERTY ()) FInteriorSettings AmbientZoneSettings
Impacts sounds that have "Apply Ambient Volumes" set to true in their Sound Class, based on whether the sound sources and the player are inside or outside the audio volume.
GENERATED_UCLASS_BODY() private UPROPERTY()) uint32 bEnabled UPROPERTY ()) FReverbSettings Settings
Priority of this volume.
UPROPERTY ()) TArray< FAudioVolumeSubmixOverrideSettings > SubmixOverrideSettings
Submix effect chain override settings.
UPROPERTY ()) TArray< FAudioVolumeSubmixSendSettings > SubmixSendSettings
Submix send settings to use for this volume.
Additional Inherited Members
Static Public Member Functions inherited from ABrush
static FOnBrushRegistered & GetOnBrushRegisteredDelegate ()
Function to get the 'brush registered' delegate.
static bool GetSuppressBSPRegeneration ()
static bool NeedsRebuild (TArray< TWeakObjectPtr< ULevel > > *OutLevels=nullptr)
Called to see if any of the levels need rebuilding.
static void OnRebuildDone ()
Called upon finishing the csg rebuild to clear the rebuild bool.
static void SetNeedRebuild (ULevel *InLevel)
Called to make not of the level that needs rebuilding.
static void SetSuppressBSPRegeneration (bool bSuppress)
Static Public Attributes inherited from ABrush
static const TCHAR * GGeometryRebuildCause
Debug purposes only; an attempt to catch the cause of UE-36265.
Detailed Description
Definition at line 152 of file AudioVolume.h.
Member Function Documentation
AddProxy()
void AAudioVolume::AddProxy () const private
References AddProxy().
Referenced by AddProxy().
GetEnabled()
bool AAudioVolume::GetEnabled () const inline
Definition at line 191 of file AudioVolume.h.
GetInteriorSettings()
const FInteriorSettings & AAudioVolume::GetInteriorSettings () const inline
Definition at line 201 of file AudioVolume.h.
GetLifetimeReplicatedProps()
virtual void AAudioVolume::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
GetPriority()
float AAudioVolume::GetPriority () const inline
Definition at line 186 of file AudioVolume.h.
References GetPriority().
Referenced by GetPriority().
GetReverbSettings()
const FReverbSettings & AAudioVolume::GetReverbSettings () const inline
Definition at line 196 of file AudioVolume.h.
GetSubmixOverrideSettings()
const TArray< FAudioVolumeSubmixOverrideSettings > & AAudioVolume::GetSubmixOverrideSettings () const inline
Definition at line 211 of file AudioVolume.h.
GetSubmixSendSettings()
const TArray< FAudioVolumeSubmixSendSettings > & AAudioVolume::GetSubmixSendSettings () const inline
Definition at line 206 of file AudioVolume.h.
PostEditChangeProperty()
virtual void AAudioVolume::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from AVolume.
PostRegisterAllComponents()
virtual void AAudioVolume::PostRegisterAllComponents () override virtual
Reimplemented from ABrush.
PostUnregisterAllComponents()
virtual void AAudioVolume::PostUnregisterAllComponents () override virtual
RemoveProxy()
void AAudioVolume::RemoveProxy () const private
References RemoveProxy().
Referenced by RemoveProxy().
TransformUpdated()
void AAudioVolume::TransformUpdated (USceneComponent * RootComponent, EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport) private
References TransformUpdated().
Referenced by TransformUpdated().
UFUNCTION() [1/7]
AAudioVolume::UFUNCTION () private
UFUNCTION() [2/7]
AAudioVolume::UFUNCTION ()
References Category.
UFUNCTION() [3/7]
AAudioVolume::UFUNCTION () const &
References Category.
UFUNCTION() [4/7]
AAudioVolume::UFUNCTION ()
References Category.
UFUNCTION() [5/7]
AAudioVolume::UFUNCTION () const &
References Category.
UFUNCTION() [6/7]
AAudioVolume::UFUNCTION () const &
References Category.
UFUNCTION() [7/7]
AAudioVolume::UFUNCTION () const &
References Category.
UpdateProxy()
void AAudioVolume::UpdateProxy () const private
References UpdateProxy().
Referenced by UpdateProxy().
UPROPERTY() [1/4]
AAudioVolume::UPROPERTY () private
Impacts sounds that have "Apply Ambient Volumes" set to true in their Sound Class, based on whether the sound sources and the player are inside or outside the audio volume.
References Category, meta, and UPROPERTY().
UPROPERTY() [2/4]
GENERATED_UCLASS_BODY() private UPROPERTY()) uint32 bEnabled AAudioVolume::UPROPERTY () private
Priority of this volume.
In the case of overlapping volumes, the one with the highest priority is chosen. The order is undefined if two or more overlapping volumes have the same priority. Whether this volume is currently enabled and able to affect sounds Reverb settings to use for this volume.
References Category, and meta.
Referenced by UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/4]
AAudioVolume::UPROPERTY () private
Submix effect chain override settings.
Will override the effect chains on the given submixes when the conditions are met.
References Category, meta, and UPROPERTY().
UPROPERTY() [4/4]
AAudioVolume::UPROPERTY () private
Submix send settings to use for this volume.
Allows audio to dynamically send to submixes based on source and listener locations relative to this volume.
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Sound/AudioVolume.h