Unreal Engine 5.6 C++ API: FProgressCancel::FProgressScope Class Reference
FProgressCancel::FProgressScope Class Reference
#include "ProgressCancel.h"
Public Member Functions
FProgressScope ()
Create a dummy/inactive FProgressScope.
FProgressScope (const FProgressScope &Other)=delete
GEOMETRYCORE_API FProgressScope (FProgressCancel *ProgressCancel, float ProgressAmount, const FText &Message=FText())
FProgressScope (FProgressScope &&Other) noexcept
~FProgressScope ()
void AdvanceProgressBy (float Amount)
void AdvanceProgressToward (float TargetProgressFrac, float FractionToward)
Advance current progress a fraction of the way toward a target value For example: if progress is .5, AdvanceProgressToward(1, .5) will take a half step to 1 and set progress to .75 As with all public progress function, progress is expressed relative to the current active progress range and cannot go backward.
GEOMETRYCORE_API void Done ()
Advance to the end of the scope's progress range and close the scope.
float GetDistanceTo (float TargetProgressFrac)
float GetProgress ()
FProgressScope & operator= (const FProgressScope &Other)=delete
FProgressScope & operator= (FProgressScope &&Other) noexcept
void SetProgressTo (float NewProgressFrac)
Note: This function will leave the current progress unchanged if the target value is less than the current progress – it will not allow the progress value to go backward.
Private Attributes
bool bEnded = false
FProgressCancel * ProgressCancel
FProgressData SavedProgressData
Detailed Description
Definition at line 257 of file ProgressCancel.h.
Constructor & Destructor Documentation
FProgressScope() [1/4]
GEOMETRYCORE_API FProgressCancel::FProgressScope::FProgressScope (FProgressCancel * ProgressCancel, float ProgressAmount, const FText & Message = FText())
Parameters
ProgressCancel Progress will be tracked on this. If null, the FProgressScope will do nothing.
ProgressAmount Amount to increase progress w/in this scope (as a fraction of the current outer-scope active progress range)
References ProgressCancel.
Referenced by FProgressScope(), FProgressScope(), operator=(), and operator=().
FProgressScope() [2/4]
FProgressCancel::FProgressScope::FProgressScope () inline
Create a dummy/inactive FProgressScope.
Definition at line 274 of file ProgressCancel.h.
References ProgressCancel.
FProgressScope() [3/4]
FProgressCancel::FProgressScope::FProgressScope (const FProgressScope & Other) delete
References FProgressScope(), and Other.
FProgressScope() [4/4]
FProgressCancel::FProgressScope::FProgressScope (FProgressScope && Other) inline noexcept
Definition at line 279 of file ProgressCancel.h.
References FProgressScope(), and Other.
~FProgressScope()
FProgressCancel::FProgressScope::~FProgressScope () inline
Definition at line 297 of file ProgressCancel.h.
References bEnded, and Done().
Member Function Documentation
AdvanceProgressBy()
void FProgressCancel::FProgressScope::AdvanceProgressBy (float Amount) inline
Parameters
Amount Amount to increase the progress fraction, as a fraction of the current active progress range
Definition at line 313 of file ProgressCancel.h.
References ProgressCancel.
AdvanceProgressToward()
void FProgressCancel::FProgressScope::AdvanceProgressToward (float TargetProgressFrac, float FractionToward) inline
Advance current progress a fraction of the way toward a target value For example: if progress is .5, AdvanceProgressToward(1, .5) will take a half step to 1 and set progress to .75 As with all public progress function, progress is expressed relative to the current active progress range and cannot go backward.
Definition at line 326 of file ProgressCancel.h.
References ProgressCancel.
Done()
GEOMETRYCORE_API void FProgressCancel::FProgressScope::Done ()
Advance to the end of the scope's progress range and close the scope.
Referenced by ~FProgressScope().
GetDistanceTo()
float FProgressCancel::FProgressScope::GetDistanceTo (float TargetProgressFrac) inline
Returns
Amount to progress in the current scope to reach the target (scope-relative) progress value
Definition at line 337 of file ProgressCancel.h.
References ProgressCancel.
GetProgress()
float FProgressCancel::FProgressScope::GetProgress () inline
Returns
Progress in the current scope
Definition at line 350 of file ProgressCancel.h.
References ProgressCancel.
operator=() [1/2]
FProgressScope & FProgressCancel::FProgressScope::operator= (const FProgressScope & Other) delete
References FProgressScope(), and Other.
operator=() [2/2]
FProgressScope & FProgressCancel::FProgressScope::operator= (FProgressScope && Other) inline noexcept
Definition at line 284 of file ProgressCancel.h.
References FProgressScope(), bEnded, MoveTemp(), Other, ProgressCancel, and SavedProgressData.
SetProgressTo()
void FProgressCancel::FProgressScope::SetProgressTo (float NewProgressFrac) inline
Note: This function will leave the current progress unchanged if the target value is less than the current progress – it will not allow the progress value to go backward.
Parameters
ProgressFrac Value to set current progress to, as a fraction of the current active progress range
Definition at line 366 of file ProgressCancel.h.
References ProgressCancel.
Field Documentation
bEnded
bool FProgressCancel::FProgressScope::bEnded = false private
Definition at line 261 of file ProgressCancel.h.
Referenced by ~FProgressScope(), and operator=().
ProgressCancel
FProgressCancel* FProgressCancel::FProgressScope::ProgressCancel private
Definition at line 259 of file ProgressCancel.h.
Referenced by FProgressScope(), FProgressScope(), AdvanceProgressBy(), AdvanceProgressToward(), GetDistanceTo(), GetProgress(), operator=(), and SetProgressTo().
SavedProgressData
FProgressData FProgressCancel::FProgressScope::SavedProgressData private
Definition at line 260 of file ProgressCancel.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/ProgressCancel.h