Unreal Engine 5.6 C++ API: FSkeletalMeshRenderData Class Reference
FSkeletalMeshRenderData Class Reference
#include "SkeletalMeshRenderData.h"
Public Member Functions
FSkeletalMeshRenderData ()
~FSkeletalMeshRenderData ()
bool AnyRenderSectionCastsShadows (int32 MinLODIdx) const
Check if any render section casts shadows.
void Cache (const ITargetPlatform *TargetPlatform, USkinnedAsset *Owner, class FSkinnedAssetCompilationContext *ContextPtr)
SIZE_T GetCPUAccessMemoryOverhead () const
Get the estimated memory overhead of buffers marked as NeedsCPUAccess.
FString GetDerivedDataKey (const ITargetPlatform *TargetPlatform, USkinnedAsset *Owner)
int32 GetFirstValidLODIdx (int32 MinLODIdx) const
Return first valid LOD index starting at MinLODIdx.
int32 GetMaxBonesPerSection () const
Computes the maximum number of bones per section used to render this mesh.
int32 GetMaxBonesPerSection (int32 MinLODIdx) const
Computes the maximum number of bones per section used to render this mesh starting at MinLODIdx.
uint32 GetNumBoneInfluences () const
Returns the number of bone influences per vertex.
uint32 GetNumBoneInfluences (int32 MinLODIdx) const
Returns the number of bone influences per vertex starting at MinLODIdx.
FORCEINLINE const FSkeletalMeshLODRenderData * GetPendingFirstLOD (int32 MinLODIdx) const
Return the pending first LOD that can be used for rendering starting at MinLODIdx.
FORCEINLINE int32 GetPendingFirstLODIdx (int32 MinLODIdx) const
Return the pending first LODIdx that can be used.
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Return the resource size.
bool HasValidNaniteData () const
void InitResources (bool bNeedsVertexColors, TArray< UMorphTarget * > &InMorphTargets, USkinnedAsset *Owner)
Initializes rendering resources.
void InitStaticRayTracingGeometry (int32 LODIndex)
Initializes the static ray tracing geometry for the specified LOD (if necessary).
bool IsInitialized () const
void ReleaseResources ()
Releases rendering resources.
void ReleaseStaticRayTracingGeometry (int32 LODIndex)
Releases the static ray tracing geometry for the specified LOD (if it's the last reference).
bool RequiresCPUSkinning (ERHIFeatureLevel::Type FeatureLevel) const
Returns true if this resource must be skinned on the CPU for the given feature level.
bool RequiresCPUSkinning (ERHIFeatureLevel::Type FeatureLevel, int32 MinLODIdx) const
Returns true if this resource must be skinned on the CPU for the given feature level starting at MinLODIdx.
void Serialize (FArchive &Ar, USkinnedAsset *Owner)
Serialize to/from the specified archive.
void SyncUVChannelData (const TArray< FSkeletalMaterial > &ObjectData)
Data Fields
bool bReadyForStreaming
True if rhi resources are initialized.
bool bSupportRayTracing
Whether ray tracing acceleration structures should be created for this mesh.
uint8 CurrentFirstLODIdx
[RenderThread] Index of the most detailed valid LOD.
uint8 LODBiasModifier
Runtime LOD bias modifier for this skeletal mesh.
TIndirectArray< FSkeletalMeshLODRenderData > LODRenderData
Per-LOD render data.
TPimplPtr< Nanite::FResources > NaniteResourcesPtr
Nanite resource data.
uint8 NumInlinedLODs
Const after serialization.
uint8 NumNonOptionalLODs
Const after serialization.
uint8 PendingFirstLODIdx
[GameThread/RenderThread] Future value of CurrentFirstLODIdx.
Private Member Functions
int32 GetNumNonOptionalLODs () const
Count the number of LODs that not optional and guarantied to be installed.
int32 GetNumNonStreamingLODs () const
Count the number of LODs that are inlined and not streamable.
Private Attributes
bool bInitialized = false
True if the resource has been initialized.
Detailed Description
Definition at line 17 of file SkeletalMeshRenderData.h.
Constructor & Destructor Documentation
FSkeletalMeshRenderData()
FSkeletalMeshRenderData::FSkeletalMeshRenderData ()
~FSkeletalMeshRenderData()
FSkeletalMeshRenderData::~FSkeletalMeshRenderData ()
Member Function Documentation
AnyRenderSectionCastsShadows()
bool FSkeletalMeshRenderData::AnyRenderSectionCastsShadows (int32 MinLODIdx) const
Check if any render section casts shadows.
Cache()
void FSkeletalMeshRenderData::Cache (const ITargetPlatform * TargetPlatform, USkinnedAsset * Owner, class FSkinnedAssetCompilationContext * ContextPtr)
References Owner.
GetCPUAccessMemoryOverhead()
SIZE_T FSkeletalMeshRenderData::GetCPUAccessMemoryOverhead () const
Get the estimated memory overhead of buffers marked as NeedsCPUAccess.
GetDerivedDataKey()
FString FSkeletalMeshRenderData::GetDerivedDataKey (const ITargetPlatform * TargetPlatform, USkinnedAsset * Owner)
References Owner.
GetFirstValidLODIdx()
int32 FSkeletalMeshRenderData::GetFirstValidLODIdx (int32 MinLODIdx) const
Return first valid LOD index starting at MinLODIdx.
Referenced by GetPendingFirstLODIdx().
GetMaxBonesPerSection() [1/2]
int32 FSkeletalMeshRenderData::GetMaxBonesPerSection () const
Computes the maximum number of bones per section used to render this mesh.
GetMaxBonesPerSection() [2/2]
int32 FSkeletalMeshRenderData::GetMaxBonesPerSection (int32 MinLODIdx) const
Computes the maximum number of bones per section used to render this mesh starting at MinLODIdx.
GetNumBoneInfluences() [1/2]
uint32 FSkeletalMeshRenderData::GetNumBoneInfluences () const
Returns the number of bone influences per vertex.
GetNumBoneInfluences() [2/2]
uint32 FSkeletalMeshRenderData::GetNumBoneInfluences (int32 MinLODIdx) const
Returns the number of bone influences per vertex starting at MinLODIdx.
GetNumNonOptionalLODs()
int32 FSkeletalMeshRenderData::GetNumNonOptionalLODs () const private
Count the number of LODs that not optional and guarantied to be installed.
Starting from the last LOD and stopping at the first optional LOD.
GetNumNonStreamingLODs()
int32 FSkeletalMeshRenderData::GetNumNonStreamingLODs () const private
Count the number of LODs that are inlined and not streamable.
Starting from the last LOD and stopping at the first non inlined LOD.
GetPendingFirstLOD()
FORCEINLINE const FSkeletalMeshLODRenderData * FSkeletalMeshRenderData::GetPendingFirstLOD (int32 MinLODIdx) const inline
Return the pending first LOD that can be used for rendering starting at MinLODIdx.
This takes into account the streaming status from PendingFirstLODIdx, and MinLODIdx is expected to be USkeletalMesh::MinLOD, which is platform specific.
Definition at line 132 of file SkeletalMeshRenderData.h.
References FORCEINLINE, GetPendingFirstLODIdx(), INDEX_NONE, and LODRenderData.
GetPendingFirstLODIdx()
FORCEINLINE int32 FSkeletalMeshRenderData::GetPendingFirstLODIdx (int32 MinLODIdx) const inline
Return the pending first LODIdx that can be used.
Definition at line 119 of file SkeletalMeshRenderData.h.
References FORCEINLINE, GetFirstValidLODIdx(), FMath::Max, and PendingFirstLODIdx.
Referenced by GetPendingFirstLOD().
GetResourceSizeEx()
void FSkeletalMeshRenderData::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize)
Return the resource size.
HasValidNaniteData()
bool FSkeletalMeshRenderData::HasValidNaniteData () const
InitResources()
void FSkeletalMeshRenderData::InitResources (bool bNeedsVertexColors, TArray< UMorphTarget * > & InMorphTargets, USkinnedAsset * Owner)
Initializes rendering resources.
References Owner.
InitStaticRayTracingGeometry()
void FSkeletalMeshRenderData::InitStaticRayTracingGeometry (int32 LODIndex)
Initializes the static ray tracing geometry for the specified LOD (if necessary).
IsInitialized()
bool FSkeletalMeshRenderData::IsInitialized () const inline
Definition at line 138 of file SkeletalMeshRenderData.h.
References bInitialized.
ReleaseResources()
void FSkeletalMeshRenderData::ReleaseResources ()
Releases rendering resources.
ReleaseStaticRayTracingGeometry()
void FSkeletalMeshRenderData::ReleaseStaticRayTracingGeometry (int32 LODIndex)
Releases the static ray tracing geometry for the specified LOD (if it's the last reference).
RequiresCPUSkinning() [1/2]
bool FSkeletalMeshRenderData::RequiresCPUSkinning (ERHIFeatureLevel::Type FeatureLevel) const
Returns true if this resource must be skinned on the CPU for the given feature level.
RequiresCPUSkinning() [2/2]
bool FSkeletalMeshRenderData::RequiresCPUSkinning (ERHIFeatureLevel::Type FeatureLevel, int32 MinLODIdx) const
Returns true if this resource must be skinned on the CPU for the given feature level starting at MinLODIdx.
Serialize()
void FSkeletalMeshRenderData::Serialize (FArchive & Ar, USkinnedAsset * Owner)
Serialize to/from the specified archive.
References Ar, and Owner.
SyncUVChannelData()
void FSkeletalMeshRenderData::SyncUVChannelData (const TArray< FSkeletalMaterial > & ObjectData)
Field Documentation
bInitialized
bool FSkeletalMeshRenderData::bInitialized = false private
True if the resource has been initialized.
Definition at line 153 of file SkeletalMeshRenderData.h.
Referenced by IsInitialized().
bReadyForStreaming
bool FSkeletalMeshRenderData::bReadyForStreaming
True if rhi resources are initialized.
Definition at line 27 of file SkeletalMeshRenderData.h.
bSupportRayTracing
bool FSkeletalMeshRenderData::bSupportRayTracing
Whether ray tracing acceleration structures should be created for this mesh.
Derived from owner USkinnedAsset.
Definition at line 45 of file SkeletalMeshRenderData.h.
CurrentFirstLODIdx
uint8 FSkeletalMeshRenderData::CurrentFirstLODIdx
[RenderThread] Index of the most detailed valid LOD.
Definition at line 36 of file SkeletalMeshRenderData.h.
LODBiasModifier
uint8 FSkeletalMeshRenderData::LODBiasModifier
Runtime LOD bias modifier for this skeletal mesh.
Definition at line 42 of file SkeletalMeshRenderData.h.
LODRenderData
TIndirectArray<FSkeletalMeshLODRenderData> FSkeletalMeshRenderData::LODRenderData
Per-LOD render data.
Definition at line 21 of file SkeletalMeshRenderData.h.
Referenced by GetPendingFirstLOD().
NaniteResourcesPtr
TPimplPtr<Nanite::FResources> FSkeletalMeshRenderData::NaniteResourcesPtr
Nanite resource data.
Definition at line 24 of file SkeletalMeshRenderData.h.
NumInlinedLODs
uint8 FSkeletalMeshRenderData::NumInlinedLODs
Const after serialization.
Definition at line 30 of file SkeletalMeshRenderData.h.
NumNonOptionalLODs
uint8 FSkeletalMeshRenderData::NumNonOptionalLODs
Const after serialization.
Definition at line 33 of file SkeletalMeshRenderData.h.
PendingFirstLODIdx
uint8 FSkeletalMeshRenderData::PendingFirstLODIdx
[GameThread/RenderThread] Future value of CurrentFirstLODIdx.
Definition at line 39 of file SkeletalMeshRenderData.h.
Referenced by GetPendingFirstLODIdx().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/SkeletalMeshRenderData.h