Unreal Engine 5.6 C++ API: UE::SharedBuffer::Private::TBufferOwnerPtr< FOps > Class Template Reference
UE::SharedBuffer::Private::TBufferOwnerPtr< FOps > Class Template Reference final
#include "SharedBuffer.h"
Public Member Functions
TBufferOwnerPtr ()=default
TBufferOwnerPtr (const TBufferOwnerPtr &Ptr)
template<typename FOtherOps>
TBufferOwnerPtr (const TBufferOwnerPtr< FOtherOps > &Ptr)
TBufferOwnerPtr (FBufferOwner *const InOwner)
TBufferOwnerPtr (TBufferOwnerPtr &&Ptr)
template<typename FOtherOps>
TBufferOwnerPtr (TBufferOwnerPtr< FOtherOps > &&Ptr)
~TBufferOwnerPtr ()
FBufferOwner * Get () const
bool IsNull () const
operator bool () const
template<typename FOtherOps>
bool operator!= (const TBufferOwnerPtr< FOtherOps > &Ptr) const
FBufferOwner * operator-> () const
TBufferOwnerPtr & operator= (const TBufferOwnerPtr &Ptr)
template<typename FOtherOps>
TBufferOwnerPtr & operator= (const TBufferOwnerPtr< FOtherOps > &Ptr)
template<typename FOtherOps>
TBufferOwnerPtr< FOps > & operator= (const TBufferOwnerPtr< FOtherOps > &Ptr)
TBufferOwnerPtr & operator= (TBufferOwnerPtr &&Ptr)
template<typename FOtherOps>
TBufferOwnerPtr & operator= (TBufferOwnerPtr< FOtherOps > &&Ptr)
template<typename FOtherOps>
TBufferOwnerPtr< FOps > & operator= (TBufferOwnerPtr< FOtherOps > &&Ptr)
template<typename FOtherOps>
bool operator== (const TBufferOwnerPtr< FOtherOps > &Ptr) const
void Reset ()
Static Private Member Functions
template<typename FOtherOps>
static FBufferOwner * CopyFrom (const TBufferOwnerPtr< FOtherOps > &Ptr)
template<typename FOtherOps>
static FBufferOwner * MoveFrom (TBufferOwnerPtr< FOtherOps > &&Ptr)
Private Attributes
FBufferOwner * Owner = nullptr
Static Private Attributes
static constexpr bool bIsWeak = std::is_same<FOps, FWeakOps>::value
Friends
template<typename FOtherOps>
class TBufferOwnerPtr
Detailed Description
template<typename FOps>
class UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >
Definition at line 154 of file SharedBuffer.h.
Constructor & Destructor Documentation
TBufferOwnerPtr() [1/6]
template<typename FOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr () inline default
TBufferOwnerPtr() [2/6]
template<typename FOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr (FBufferOwner *const InOwner) inline explicit
TBufferOwnerPtr() [3/6]
template<typename FOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr (const TBufferOwnerPtr< FOps > & Ptr) inline
Definition at line 793 of file SharedBuffer.h.
References TBufferOwnerPtr, CopyFrom(), and Owner.
TBufferOwnerPtr() [4/6]
template<typename FOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr (TBufferOwnerPtr< FOps > && Ptr) inline
Definition at line 799 of file SharedBuffer.h.
References TBufferOwnerPtr, MoveFrom(), MoveTemp(), and Owner.
TBufferOwnerPtr() [5/6]
template<typename FOps> template<typename FOtherOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr (const TBufferOwnerPtr< FOtherOps > & Ptr) inline explicit
Definition at line 806 of file SharedBuffer.h.
References TBufferOwnerPtr, CopyFrom(), and Owner.
TBufferOwnerPtr() [6/6]
template<typename FOps> template<typename FOtherOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::TBufferOwnerPtr (TBufferOwnerPtr< FOtherOps > && Ptr) inline explicit
Definition at line 813 of file SharedBuffer.h.
References TBufferOwnerPtr, MoveFrom(), MoveTemp(), and Owner.
~TBufferOwnerPtr()
template<typename FOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::~TBufferOwnerPtr () inline
Definition at line 819 of file SharedBuffer.h.
References Owner.
Member Function Documentation
CopyFrom()
template<typename FOps> template<typename FOtherOps> FBufferOwner * UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::CopyFrom (const TBufferOwnerPtr< FOtherOps > & Ptr) inline static private
Definition at line 752 of file SharedBuffer.h.
References TBufferOwnerPtr, bIsWeak, CopyFrom(), and Owner.
Referenced by TBufferOwnerPtr(), TBufferOwnerPtr(), CopyFrom(), and operator=().
Get()
template<typename FOps> FBufferOwner * UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::Get () const inline
Definition at line 194 of file SharedBuffer.h.
Referenced by UE::SharedBuffer::Private::TBufferOwnerPtr< UE::SharedBuffer::Private::FSharedOps >::operator->().
IsNull()
template<typename FOps> bool UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::IsNull () const inline
Definition at line 197 of file SharedBuffer.h.
Referenced by UE::SharedBuffer::Private::TBufferOwnerPtr< UE::SharedBuffer::Private::FSharedOps >::operator bool().
MoveFrom()
template<typename FOps> template<typename FOtherOps> FBufferOwner * UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::MoveFrom (TBufferOwnerPtr< FOtherOps > && Ptr) inline static private
Definition at line 771 of file SharedBuffer.h.
References TBufferOwnerPtr, bIsWeak, and MoveFrom().
Referenced by TBufferOwnerPtr(), TBufferOwnerPtr(), MoveFrom(), and operator=().
operator bool()
template<typename FOps> UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator bool () const inline explicit
Definition at line 196 of file SharedBuffer.h.
operator!=()
template<typename FOps> template<typename FOtherOps> bool UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator!= (const TBufferOwnerPtr< FOtherOps > & Ptr) const inline
Definition at line 871 of file SharedBuffer.h.
References TBufferOwnerPtr, and Owner.
operator->()
template<typename FOps> FBufferOwner * UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator-> () const inline
Definition at line 195 of file SharedBuffer.h.
operator=() [1/6]
template<typename FOps> TBufferOwnerPtr< FOps > & UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator= (const TBufferOwnerPtr< FOps > & Ptr) inline
Definition at line 825 of file SharedBuffer.h.
References TBufferOwnerPtr, CopyFrom(), and Owner.
operator=() [2/6]
template<typename FOps> template<typename FOtherOps> TBufferOwnerPtr & UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator= (const TBufferOwnerPtr< FOtherOps > & Ptr) inline
operator=() [3/6]
template<typename FOps> template<typename FOtherOps> TBufferOwnerPtr< FOps > & UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator= (const TBufferOwnerPtr< FOtherOps > & Ptr) inline
Definition at line 844 of file SharedBuffer.h.
operator=() [4/6]
template<typename FOps> TBufferOwnerPtr< FOps > & UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator= (TBufferOwnerPtr< FOps > && Ptr) inline
Definition at line 834 of file SharedBuffer.h.
References TBufferOwnerPtr, MoveFrom(), MoveTemp(), and Owner.
operator=() [5/6]
template<typename FOps> template<typename FOtherOps> TBufferOwnerPtr & UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator= (TBufferOwnerPtr< FOtherOps > && Ptr) inline
operator=() [6/6]
template<typename FOps> template<typename FOtherOps> TBufferOwnerPtr< FOps > & UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator= (TBufferOwnerPtr< FOtherOps > && Ptr) inline
Definition at line 854 of file SharedBuffer.h.
operator==()
template<typename FOps> template<typename FOtherOps> bool UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::operator== (const TBufferOwnerPtr< FOtherOps > & Ptr) const inline
Definition at line 864 of file SharedBuffer.h.
References TBufferOwnerPtr, and Owner.
Reset()
template<typename FOps> void UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::Reset () inline
Friends And Related Symbol Documentation
TBufferOwnerPtr
template<typename FOps> template<typename FOtherOps> friend class TBufferOwnerPtr friend
Definition at line 159 of file SharedBuffer.h.
Referenced by TBufferOwnerPtr(), TBufferOwnerPtr(), TBufferOwnerPtr(), TBufferOwnerPtr(), CopyFrom(), MoveFrom(), operator!=(), operator=(), operator=(), and operator==().
Field Documentation
bIsWeak
template<typename FOps> bool UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::bIsWeak = std::is_same<FOps, FWeakOps>::value static constexpr private
Definition at line 156 of file SharedBuffer.h.
Referenced by CopyFrom(), and MoveFrom().
Owner
template<typename FOps> FBufferOwner* UE::SharedBuffer::Private::TBufferOwnerPtr< FOps >::Owner = nullptr private
Definition at line 202 of file SharedBuffer.h.
Referenced by TBufferOwnerPtr(), TBufferOwnerPtr(), TBufferOwnerPtr(), TBufferOwnerPtr(), ~TBufferOwnerPtr(), CopyFrom(), operator!=(), operator=(), operator=(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/SharedBuffer.h