Unreal Engine 5.6 C++ API: FCbFieldViewIterator Class Reference
FCbFieldViewIterator Class Reference
Iterator for FCbFieldView.
#include "CompactBinary.h"
Public Member Functions
constexpr FCbFieldViewIterator ()=default
Construct an empty field range.
template<typename OtherFieldType>
FCbFieldViewIterator (const TCbFieldIterator< OtherFieldType > &It)
Construct an iterator from another iterator.
Public Member Functions inherited from TCbFieldIterator< FCbFieldView >
void AppendRangeHash (FIoHashBuilder &Builder) const
Append the hash of every field in the range.
constexpr TCbFieldIterator begin () const
DO NOT USE DIRECTLY.
void CopyRangeTo (FMutableMemoryView Buffer) const
Copy the field range into a buffer of exactly GetRangeSize() bytes.
constexpr FCbIteratorSentinel end () const
constexpr bool Equals (const TCbFieldIterator< OtherFieldType > &Other) const
FIoHash GetRangeHash () const
Calculate the hash of every field in the range.
uint64 GetRangeSize () const
Returns the size of the fields in the range in bytes.
void IterateRangeAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field range.
constexpr bool operator!= (const TCbFieldIterator< OtherFieldType > &Other) const
constexpr FCbFieldView & operator* ()
TCbFieldIterator & operator++ ()
constexpr FCbFieldView * operator-> ()
constexpr bool operator== (const TCbFieldIterator< OtherFieldType > &Other) const
void Reset ()
Reset this to an empty field range.
bool TryGetRangeView (FMemoryView &OutView) const
Try to get a view of every field in the range as they would be serialized.
Public Member Functions inherited from FCbFieldView
constexpr FCbFieldView ()=default
Construct a field with no name and no value.
FCbFieldView (const FCbValue &Value)
Construct a field from a value, without access to the name.
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field from a pointer to its data and an optional externally-provided type.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the field, including the type and name.
FCbArrayView AsArrayView ()
Access the field as an array.
FIoHash AsAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an attachment.
FIoHash AsBinaryAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing a binary attachment.
FMemoryView AsBinaryView (FMemoryView Default=FMemoryView())
Access the field as binary.
bool AsBool (bool bDefault=false)
Access the field as a bool.
FMemoryView AsCustom (FUtf8StringView Name, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with a string identifier.
FMemoryView AsCustom (uint64 Id, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with an integer identifier.
FCbCustomById AsCustomById (FCbCustomById Default=FCbCustomById())
Access the field as a custom sub-type with an integer identifier.
FCbCustomByName AsCustomByName (FCbCustomByName Default=FCbCustomByName())
Access the field as a custom sub-type with a string identifier.
FDateTime AsDateTime ()
Access the field as a date/time.
FDateTime AsDateTime (FDateTime Default)
Access the field as a date/time.
int64 AsDateTimeTicks (int64 Default=0)
Access the field as a date/time tick count.
double AsDouble (double Default=0.0)
Access the field as a double.
float AsFloat (float Default=0.0f)
Access the field as a float.
FIoHash AsHash (const FIoHash &Default=FIoHash())
Access the field as a hash.
int16 AsInt16 (int16 Default=0)
Access the field as an int16.
int32 AsInt32 (int32 Default=0)
Access the field as an int32.
int64 AsInt64 (int64 Default=0)
Access the field as an int64.
int8 AsInt8 (int8 Default=0)
Access the field as an int8.
FIoHash AsObjectAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an object attachment.
FCbObjectId AsObjectId (const FCbObjectId &Default=FCbObjectId())
Access the field as an object identifier.
FCbObjectView AsObjectView ()
Access the field as an object.
FUtf8StringView AsString (FUtf8StringView Default=FUtf8StringView())
Access the field as a string.
FTimespan AsTimeSpan ()
Access the field as a timespan.
FTimespan AsTimeSpan (FTimespan Default)
Access the field as a timespan.
int64 AsTimeSpanTicks (int64 Default=0)
Access the field as a timespan tick count.
uint16 AsUInt16 (uint16 Default=0)
Access the field as a uint16.
uint32 AsUInt32 (uint32 Default=0)
Access the field as a uint32.
uint64 AsUInt64 (uint64 Default=0)
Access the field as a uint64.
uint8 AsUInt8 (uint8 Default=0)
Access the field as a uint8.
FGuid AsUuid ()
Access the field as a UUID.
FGuid AsUuid (const FGuid &Default)
Access the field as a UUID.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the field into an archive, including its type and name.
void CopyTo (FMutableMemoryView Buffer) const
Copy the field into a buffer of exactly GetSize() bytes, including the type and name.
FCbFieldViewIterator CreateViewIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbFieldView &Other) const
Whether this field is identical to the other field.
constexpr ECbFieldError GetError () const
The type of error that occurred on the last field access, or None.
FIoHash GetHash () const
Calculate the hash of the field, including the type and name.
constexpr FUtf8StringView GetName () const
Returns the name of the field if it has a name, otherwise an empty view.
uint64 GetSize () const
Returns the size of the field in bytes, including the type and name.
FCbValue GetValue () const
Returns the value for unchecked access.
constexpr bool HasError () const
Whether the last field access encountered an error.
constexpr bool HasName () const
True if the field has a name.
constexpr bool HasValue () const
Whether the field has a value.
constexpr bool IsArray () const
constexpr bool IsAttachment () const
constexpr bool IsBinary () const
constexpr bool IsBinaryAttachment () const
constexpr bool IsBool () const
constexpr bool IsCustomById () const
constexpr bool IsCustomByName () const
constexpr bool IsDateTime () const
constexpr bool IsFloat () const
Whether the field is a float, or integer that supports implicit conversion.
constexpr bool IsHash () const
constexpr bool IsInteger () const
Whether the field is an integer of unspecified range and sign.
constexpr bool IsNull () const
constexpr bool IsObject () const
constexpr bool IsObjectAttachment () const
constexpr bool IsObjectId () const
constexpr bool IsString () const
constexpr bool IsTimeSpan () const
constexpr bool IsUuid () const
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field.
constexpr operator bool () const
Whether the field has a value.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
constexpr FCbFieldView RemoveName () const
Returns a copy of the field with the name removed.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the field as it would be serialized, such as by CopyTo.
Static Public Member Functions
static FCbFieldViewIterator MakeRange (FMemoryView View, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field range from a buffer containing zero or more valid fields.
static FCbFieldViewIterator MakeSingle (const FCbFieldView &Field)
Construct a field range that contains exactly one field.
Private Member Functions
constexpr TCbFieldIterator ()=default
Construct an empty field range.
constexpr TCbFieldIterator (FieldType &&InField, const void *InFieldsEnd)
Construct a field range from the first field and a pointer to the end of the last field.
constexpr TCbFieldIterator (FieldType InField)
Construct a field range that contains exactly one field.
Additional Inherited Members
Protected Member Functions inherited from FCbFieldView
void Assign (const void *InData, const ECbFieldType InType)
Assign a field from a pointer to its data and an optional externally-provided type.
constexpr ECbFieldType GetType () const
Returns the type of the field excluding flags.
constexpr ECbFieldType GetTypeWithFlags () const
Returns the type of the field including flags.
constexpr const void * GetValueData () const
Returns the start of the value.
const void * GetValueEnd () const
Returns the end of the value.
uint64 GetValueSize () const
Returns the size of the value in bytes, which is the field excluding the type and name.
FMemoryView GetValueView () const
Returns a view of the value, which excludes the type and name.
FMemoryView GetView () const
Returns a view of the field, including the type and name when present.
FMemoryView GetViewNoType () const
Returns a view of the name and value, which excludes the type.
Static Protected Member Functions inherited from TCbFieldIterator< FCbFieldView >
static const void * GetFieldsEnd (const TCbFieldIterator< OtherFieldType > &It)
Returns the end of the last field, or null for an iterator at the end.
Detailed Description
Iterator for FCbFieldView.
See also
TCbFieldIterator
Definition at line 891 of file CompactBinary.h.
Constructor & Destructor Documentation
FCbFieldViewIterator() [1/2]
FCbFieldViewIterator::FCbFieldViewIterator () constexpr default
Construct an empty field range.
Referenced by MakeRange(), and MakeSingle().
FCbFieldViewIterator() [2/2]
template<typename OtherFieldType> FCbFieldViewIterator::FCbFieldViewIterator (const TCbFieldIterator< OtherFieldType > & It) inline
Construct an iterator from another iterator.
Definition at line 916 of file CompactBinary.h.
References TCbFieldIterator< FCbFieldView >::GetFieldsEnd(), ImplicitConv(), and TCbFieldIterator().
Member Function Documentation
MakeRange()
FCbFieldViewIterator FCbFieldViewIterator::MakeRange (FMemoryView View, ECbFieldType Type = ECbFieldType::HasFieldType) inline static nodiscard
Construct a field range from a buffer containing zero or more valid fields.
Parameters
View A buffer containing zero or more valid fields.
Type HasFieldType means that View contains the type. Otherwise, use the given type.
Definition at line 906 of file CompactBinary.h.
References FCbFieldView::FCbFieldView(), FCbFieldViewIterator(), TMemoryView< DataType >::GetData(), TMemoryView< DataType >::GetDataEnd(), HasFieldType, and TMemoryView< DataType >::IsEmpty().
MakeSingle()
FCbFieldViewIterator FCbFieldViewIterator::MakeSingle (const FCbFieldView & Field) inline static nodiscard
Construct a field range that contains exactly one field.
Definition at line 895 of file CompactBinary.h.
References FCbFieldViewIterator().
TCbFieldIterator() [1/3]
TCbFieldIterator< FieldType >::TCbFieldIterator () constexpr private default
Construct an empty field range.
Referenced by FCbFieldViewIterator().
TCbFieldIterator() [2/3]
TCbFieldIterator< FieldType >::TCbFieldIterator (FieldType && InField, const void * InFieldsEnd) inline constexpr private
Construct a field range from the first field and a pointer to the end of the last field.
Parameters
InField The first field, or the default field if there are no fields.
InFieldsEnd A pointer to the end of the value of the last field, or null.
Definition at line 437 of file CompactBinary.h.
TCbFieldIterator() [3/3]
TCbFieldIterator< FieldType >::TCbFieldIterator (FieldType InField) inline explicit constexpr private
Construct a field range that contains exactly one field.
Definition at line 425 of file CompactBinary.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinary.h