Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolItemProxy Class Reference
UE::SequenceNavigator::FNavigationToolItemProxy Class Reference abstract
Item Proxies are Navigation Tool Items that with the sole purpose to group and hold common items together.
#include "NavigationToolItemProxy.h"
Public Member Functions
FNavigationToolItemProxy (INavigationTool &InTool, const FNavigationToolItemPtr &InParentItem)
virtual bool CanAutoExpand () const override
Whether the Item is able to expand when AutoExpand functionality is enabled.
virtual void FindChildren (TArray< FNavigationToolItemPtr > &OutChildren, bool bRecursive) override final
Figures out the Children of this Item.
virtual FText GetClassName () const override
Gets the Class/Type of this Item (e.g.
uint32 GetPriority () const
virtual void GetProxiedItems (const TSharedRef< INavigationToolItem > &InParent, TArray< FNavigationToolItemPtr > &OutChildren, bool bInRecursive)=0
Gets the Items that this Item Proxy is representing / holding (i.e.
virtual ENavigationToolItemViewMode GetSupportedViewModes (const INavigationToolView &InToolView) const override
Gets the View Modes that this Item Supports.
virtual bool IsItemValid () const override
Determines whether the Item properties are in a valid state.
virtual void SetParent (FNavigationToolItemPtr InParent) override
Sets the Parent.
void SetPriority (uint32 InPriority)
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolItemProxy, FNavigationToolItem)
Public Member Functions inherited from UE::SequenceNavigator::FNavigationToolItem
FNavigationToolItem (INavigationTool &InTool, const FNavigationToolItemPtr &InParentItem)
virtual FReply AcceptDrop (const FDragDropEvent &InDragDropEvent, EItemDropZone InDropZone) override
Processes the Drag and Drop Event for this Item.
virtual bool AddChild (const FNavigationToolAddItemParams &InAddItemParams) override
Adds another Child under this Item if such Item is supported.
virtual void AddFlags (ENavigationToolItemFlags Flags) override
virtual TOptional< EItemDropZone > CanAcceptDrop (const FDragDropEvent &InDragDropEvent, EItemDropZone InDropZone) override
Determines if and where the incoming Drag Drop Event can be processed by this item.
virtual bool CanAddChild (const FNavigationToolItemPtr &InChild) const override
Determines whether the given Child is supported and can be added under this Item.
virtual bool CanBeTopLevel () const override
Whether this Item can be at the Top Level just beneath the Root, or it needs to always be under some other Item E.g.
virtual bool CanDelete () const override
Whether this Item can be deleted or not.
virtual bool CanReceiveParentVisibilityPropagation () const override
Whether a change in Parent Visibility should also affect this Item's Visibility.
DECLARE_DELEGATE_RetVal_OneParam (FNavigationToolSaveState *, FNavigationToolGetToolState, const FNavigationToolItemPtr)
virtual bool Delete () override
The implementation to delete the item.
virtual TArray< FNavigationToolItemPtr > FindPath (const TArray< FNavigationToolItemPtr > &InItems) const override
virtual void FindValidChildren (TArray< FNavigationToolItemPtr > &OutChildren, const bool bInRecursive) override
virtual TSharedRef< SWidget > GenerateLabelWidget (const TSharedRef< SNavigationToolTreeRow > &InRow) override
Function responsible of Generating the Label Widget for this Item (i.e.
virtual IndexType GetChildIndex (const FNavigationToolItemPtr &ChildItem) const override
Gets the Index that the given Child Item is at.
virtual const TArray< FNavigationToolItemPtr > & GetChildren () const override
Gets the current Child Items of this Item.
virtual TArray< FNavigationToolItemPtr > & GetChildrenMutable () override
Gets the current Child Items of this Item.
virtual TOptional< FColor > GetColor () const override
virtual FText GetDisplayName () const override
Gets the Display Name Text of the Item.
virtual ENavigationToolItemFlags GetFlags () const override
virtual const FSlateBrush * GetIconBrush () const override
virtual FSlateColor GetIconColor () const override
Gets the color for the item icon.
virtual FNavigationToolItemId GetItemId () const override final
Gets the Id of this Item.
virtual FSlateColor GetItemLabelColor () const override
Gets the color to use for the item label.
virtual FLinearColor GetItemTintColor () const override
Gets the color to use to tint the entire item row (all column content)
virtual INavigationTool & GetOwnerTool () const final override
Gets the Navigation Tool that owns this item.
virtual FNavigationToolItemPtr GetParent () const override
Gets the Parent of this Item.
virtual TSharedPtr< FNavigationToolProvider > GetProvider () const final override
Gets the module provider responsible for the creation of this item.
virtual FNavigationToolSaveState * GetProviderSaveState () const override
Gets the providers saved state.
virtual TArray< FName > GetTags () const override
Gets the Tags found for this Item (e.g.
virtual bool GetVisibility () const override
Whether this Item is currently visible or not for the Given Type.
virtual bool HasAllFlags (ENavigationToolItemFlags Flags) const override
virtual bool HasAnyFlags (ENavigationToolItemFlags Flags) const override
virtual bool IsAllowedInTool () const override
Returns whether this Item (and what it represents) should be allowed to be registered in Navigation Tool.
virtual bool IsExpanded () const override
Gets whether this item is expanded.
virtual FOnExpansionChanged & OnExpansionChanged () override
Called when Expansion state (Expanded/Collapsed) has been changed.
virtual FOnRenameAction & OnRenameAction () override
Broadcasts whenever a rename action takes place from a given view (e.g.
virtual void RefreshChildren () override
Refreshes what the Parent and Children are of this Item.
virtual bool RemoveChild (const FNavigationToolRemoveItemParams &InRemoveItemParams) override
Removes the given child from this Item if it was ever indeed a child.
virtual void RemoveFlags (ENavigationToolItemFlags Flags) override
virtual void ResetChildren () override
Resets both the Cached Visible Children and Children (before doing so, sets all child's parents to null)
virtual void SetColor (const TOptional< FColor > &InColor) override
virtual void SetExpansion (const bool bInExpand) override
Sets the expansion state of this item.
virtual void SetFlags (ENavigationToolItemFlags InFlags) override
virtual bool ShouldSort () const override
Determines whether this item can be sorted by the Navigation Tool or not.
virtual bool ShowVisibility () const override
Whether this Item supports Visibility for the Given Type.
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolItem, INavigationToolItem, IColorExtension)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItem
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false)
Finds the first ancestor view model that implements the given type.
template<typename InItemType>
InItemType * FindAncestorOfType (const bool bInIncludeThis=false) const
template<typename InItemType>
TArray< InItemType * > FindAncestorsOfType (const bool bInIncludeThis=false) const
virtual FNavigationToolItemPtr GetChildAt (const IndexType Index) const
template<typename InItemType>
TArray< InItemType * > GetChildrenOfType (const bool bInIncludeThis=false) const
virtual const FSlateBrush * GetDefaultIconBrush () const
TArray< FNavigationToolItemPtr > GetDescendants (const bool bInIncludeThis=false)
template<typename InItemType>
TArray< InItemType * > GetDescendantsOfType (const bool bInIncludeThis=false) const
FString GetFullPath () const
Returns the path to this item in the tree.
virtual FSlateIcon GetIcon () const =0
Gets the slate icon for the item.
virtual FText GetIconTooltipText () const =0
Gets the tooltip text for the item icon.
virtual UObject * GetItemObject () const
Gets the UObject that this item represents.
virtual void GetItemProxies (TArray< TSharedPtr< FNavigationToolItemProxy > > &OutItemProxies)
Gets the Item Proxies for this Item (e.g.
virtual int32 GetItemTreeHeight () const
Returns the item's height in tree, Root Item should return 0 as it has no Parent.
virtual TSet< FNavigationToolItemPtr > GetParents (const bool bInIncludeRoot=false) const
Gets the list of all parents up the tree from this Item.
bool IsIgnoringPendingKill () const
Whether Ignoring Pending Kill.
virtual bool IsSelectable () const
Whether the Item can be selected in Navigation Tool at all.
virtual bool IsSelected (const FNavigationToolScopedSelection &InSelection) const
Determines whether the given Item is selected in the given Scoped Selection.
virtual bool IsViewModeSupported (const ENavigationToolItemViewMode InViewMode, const INavigationToolView &InToolView) const
Whether this Item should be visualized in the given View Mode, for the given Navigation Tool View.
virtual FNavigationToolSerializedItem MakeSerializedItem ()
Converts this Navigation Tool item to a serialized item that can be saved in the sequence.
virtual void OnDoubleClick ()
Called when an Item is double-clicked with the mouse.
virtual void OnItemRegistered ()
Called when the Item has been registered into the Navigation Tool.
virtual void OnItemSelectionChanged (const bool bInIsSelected)
Called when the Item been selected/deselected from the Tree View.
virtual void OnItemUnregistered ()
Called when the Item has been unregistered from the Navigation Tool.
virtual void OnObjectsReplaced (const TMap< UObject *, UObject * > &InReplacementMap, const bool bInRecursive)
Called when objects have been replaced on the Engine side.
virtual void OnSelect ()
Called when an Item is selected.
virtual void OnVisibilityChanged (const bool bInNewVisibility)
Called when the Visibility on Item has been changed on the Navigation Tool side.
virtual void Select (FNavigationToolScopedSelection &InSelection) const
Used to signal the Scoped Selection that this Item should be Selected.
UE_NAVIGATIONTOOL_INHERITS (INavigationToolItem, INavigationToolItemTypeCastable)
Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
virtual ~INavigationToolItemTypeCastable ()=default
template<typename InType>
InType * CastTo ()
template<typename InType>
const InType * CastTo () const
virtual const void * CastTo_Impl (FNavigationToolItemTypeId InId) const =0
virtual FNavigationToolItemTypeId GetTypeId () const =0
template<typename InType>
bool IsA () const
template<typename InType>
bool IsExactlyA () const
Public Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedRef< INavigationToolItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< INavigationToolItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::SequenceNavigator::IColorExtension
UE_NAVIGATIONTOOL_INHERITS (IColorExtension, INavigationToolItemTypeCastable) SEQUENCENAVIGATOR_API virtual TOptional< FColor > GetColor() const =0
Protected Member Functions
virtual FNavigationToolItemId CalculateItemId () const override
Gets the Item Id with the latest information (e.g.
Protected Member Functions inherited from UE::SequenceNavigator::FNavigationToolItem
void AddChildChecked (const FNavigationToolAddItemParams &InAddItemParams)
The actual implementation of putting the given Item under the Children array.
void HandleNewSortableChildren (TArray< FNavigationToolItemPtr > InSortableChildren)
Careful handling of multiple children being detected and added to this item children array.
void RecalculateItemId ()
Sets the ItemId member var to what CalculateItemId returns.
bool RemoveChildChecked (const FNavigationToolRemoveItemParams &InRemoveItemParams)
The actual implementation of removing the given item from the Children array.
void SetProvider (const TWeakPtr< FNavigationToolProvider > &InWeakProvider)
Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
uint32 Priority = 0
This Item Proxy's Order Priority (i.e.
Additional Inherited Members
Public Types inherited from UE::SequenceNavigator::INavigationToolItem
using FOnExpansionChanged = TMulticastDelegate<void(const TSharedPtr<INavigationToolView>&, bool)>
Delegate signature for when the Item Expansion Changes const TSharedPtr<FNavigationToolView>& - The Navigation Tool View where this Expansion happened bool - Whether the Item is expanded.
using FOnRenameAction = TMulticastDelegate<void(ENavigationToolRenameAction, const TSharedPtr<INavigationToolView>&)>
Delegate signature for relaying an Item Rename action ENavigationToolRenameAction the type of action being relayed (e.g.
Public Types inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
using FNavigationToolItemInherits = TNavigationToolItemInherits<INavigationToolItemTypeCastable,>
Static Public Member Functions inherited from UE::SequenceNavigator::INavigationToolItemTypeCastable
static FNavigationToolItemTypeId GetStaticTypeId ()
Protected Types inherited from UE::SequenceNavigator::INavigationToolItem
using IndexType = TArray<INavigationToolItem>::SizeType
Static Protected Member Functions inherited from TSharedFromThis< INavigationToolItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::SequenceNavigator::FNavigationToolItem
TArray< FNavigationToolItemPtr > Children
Array of Shared pointers to the Child Items.
ENavigationToolItemFlags ItemFlags = ENavigationToolItemFlags::None
The current flags set for this item.
FNavigationToolItemId ItemId
FOnExpansionChanged OnExpansionChangedDelegate
Delegate for when Expansion changes in the Item.
FOnRenameAction OnRenameActionDelegate
The delegate for renaming.
INavigationTool & Tool
Reference to the Owning Navigation Tool.
FNavigationToolItemWeakPtr WeakParent
Weak pointer to the Parent Item.
TWeakPtr< FNavigationToolProvider > WeakProvider
Tool provider that is responsible for the creation of this item.
Detailed Description
Item Proxies are Navigation Tool Items that with the sole purpose to group and hold common items together.
The description or name of such commonality between these Items should be the name of the Proxy that holds them.
NOTE: Although Item Proxies by default require a parent to be visible in Navigation Tool, they can be created without a parent as a means to override behavior (e.g. DisplayName, Icon, etc)
Definition at line 17 of file NavigationToolItemProxy.h.
Constructor & Destructor Documentation
FNavigationToolItemProxy()
UE::SequenceNavigator::FNavigationToolItemProxy::FNavigationToolItemProxy (INavigationTool & InTool, const FNavigationToolItemPtr & InParentItem)
References UE::SequenceNavigator::FNavigationToolItem::INavigationTool.
Referenced by UE::SequenceNavigator::FNavigationToolComponentProxy::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER(), and UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER().
Member Function Documentation
CalculateItemId()
virtual FNavigationToolItemId UE::SequenceNavigator::FNavigationToolItemProxy::CalculateItemId () const override protected virtual
Gets the Item Id with the latest information (e.g.
parent, object, etc)
Implements UE::SequenceNavigator::FNavigationToolItem.
CanAutoExpand()
virtual bool UE::SequenceNavigator::FNavigationToolItemProxy::CanAutoExpand () const override virtual
Whether the Item is able to expand when AutoExpand functionality is enabled.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
FindChildren()
virtual void UE::SequenceNavigator::FNavigationToolItemProxy::FindChildren (TArray< FNavigationToolItemPtr > & OutChildren, bool bInRecursive) final override virtual
Figures out the Children of this Item.
This is only relevant for items that do have that functionality (e.g. Components or Actors)
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
GetClassName()
virtual FText UE::SequenceNavigator::FNavigationToolItemProxy::GetClassName () const inline override virtual
Gets the Class/Type of this Item (e.g.
for Items that represent UObjects, it will be the UObject class)
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
Definition at line 30 of file NavigationToolItemProxy.h.
References FText::GetEmpty().
GetPriority()
uint32 UE::SequenceNavigator::FNavigationToolItemProxy::GetPriority () const inline
Definition at line 33 of file NavigationToolItemProxy.h.
References Priority.
GetProxiedItems()
virtual void UE::SequenceNavigator::FNavigationToolItemProxy::GetProxiedItems (const TSharedRef< INavigationToolItem > & InParent, TArray< FNavigationToolItemPtr > & OutChildren, bool bInRecursive) pure virtual
Gets the Items that this Item Proxy is representing / holding (i.e.
children)
Implemented in UE::SequenceNavigator::FNavigationToolComponentProxy.
GetSupportedViewModes()
virtual ENavigationToolItemViewMode UE::SequenceNavigator::FNavigationToolItemProxy::GetSupportedViewModes (const INavigationToolView & InToolView) const override virtual
Gets the View Modes that this Item Supports.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
Reimplemented in UE::SequenceNavigator::FNavigationToolComponentProxy.
IsItemValid()
virtual bool UE::SequenceNavigator::FNavigationToolItemProxy::IsItemValid () const override virtual
Determines whether the Item properties are in a valid state.
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
SetParent()
virtual void UE::SequenceNavigator::FNavigationToolItemProxy::SetParent (FNavigationToolItemPtr InParent) override virtual
Sets the Parent.
Note that the Parent must've already have this instance as a child (check is done)
Reimplemented from UE::SequenceNavigator::FNavigationToolItem.
SetPriority()
void UE::SequenceNavigator::FNavigationToolItemProxy::SetPriority (uint32 InPriority) inline
Definition at line 34 of file NavigationToolItemProxy.h.
References Priority.
UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER()
UE::SequenceNavigator::FNavigationToolItemProxy::UE_NAVIGATIONTOOL_INHERITS_WITH_SUPER (FNavigationToolItemProxy , FNavigationToolItem)
References UE::SequenceNavigator::FNavigationToolItem::FNavigationToolItem(), and FNavigationToolItemProxy().
Field Documentation
Priority
uint32 UE::SequenceNavigator::FNavigationToolItemProxy::Priority = 0 private
This Item Proxy's Order Priority (i.e.
Highest priority is placed topmost or leftmost (depending on Orientation). Priority 0 is lowest priority
Definition at line 46 of file NavigationToolItemProxy.h.
Referenced by GetPriority(), and SetPriority().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/Items/NavigationToolItemProxy.h