Unreal Engine 5.6 C++ API: UE::Geometry::MappedIterator< FromType, ToType, IteratorT > Class Template Reference
UE::Geometry::MappedIterator< FromType, ToType, IteratorT > Class Template Reference
Wrapper around an object of type IteratorT that provides STL iterator-like semantics, that converts from the iteration type (FromType) to a new type (ToType).
#include "IteratorUtil.h"
Public Member Functions
MappedIterator ()
MappedIterator (const IteratorT &CurItr, const MapFunctionT &MapFunctionIn)
bool operator!= (const MappedIterator &Other) const
ToType operator* () const
const MappedIterator & operator++ ()
bool operator== (const MappedIterator &Other) const
Data Fields
IteratorT Cur
MapFunctionT MapFunction
Private Types
using MapFunctionT = TFunction<ToType(FromType)>
Detailed Description
template<typename FromType, typename ToType, typename IteratorT>
class UE::Geometry::MappedIterator< FromType, ToType, IteratorT >
Wrapper around an object of type IteratorT that provides STL iterator-like semantics, that converts from the iteration type (FromType) to a new type (ToType).
Conversion is done via a provided mapping function
Definition at line 23 of file IteratorUtil.h.
Member Typedef Documentation
MapFunctionT
template<typename FromType, typename ToType, typename IteratorT> using UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::MapFunctionT = TFunction<ToType(FromType)> private
Definition at line 25 of file IteratorUtil.h.
Constructor & Destructor Documentation
MappedIterator() [1/2]
template<typename FromType, typename ToType, typename IteratorT> UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::MappedIterator () inline
Definition at line 28 of file IteratorUtil.h.
Referenced by operator!=(), operator++(), and operator==().
MappedIterator() [2/2]
template<typename FromType, typename ToType, typename IteratorT> UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::MappedIterator (const IteratorT & CurItr, const MapFunctionT & MapFunctionIn) inline
Definition at line 50 of file IteratorUtil.h.
References Cur, and MapFunction.
Member Function Documentation
operator!=()
template<typename FromType, typename ToType, typename IteratorT> bool UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::operator!= (const MappedIterator< FromType, ToType, IteratorT > & Other) const inline
Definition at line 34 of file IteratorUtil.h.
References MappedIterator(), Cur, and Other.
operator*()
template<typename FromType, typename ToType, typename IteratorT> ToType UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::operator* () const inline
Definition at line 39 of file IteratorUtil.h.
References Cur, and MapFunction.
operator++()
template<typename FromType, typename ToType, typename IteratorT> const MappedIterator & UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::operator++ () inline
Definition at line 44 of file IteratorUtil.h.
References MappedIterator(), and Cur.
operator==()
template<typename FromType, typename ToType, typename IteratorT> bool UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::operator== (const MappedIterator< FromType, ToType, IteratorT > & Other) const inline
Definition at line 30 of file IteratorUtil.h.
References MappedIterator(), Cur, and Other.
Field Documentation
Cur
template<typename FromType, typename ToType, typename IteratorT> IteratorT UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::Cur
Definition at line 56 of file IteratorUtil.h.
Referenced by MappedIterator(), operator!=(), operator*(), operator++(), and operator==().
MapFunction
template<typename FromType, typename ToType, typename IteratorT> MapFunctionT UE::Geometry::MappedIterator< FromType, ToType, IteratorT >::MapFunction
Definition at line 57 of file IteratorUtil.h.
Referenced by MappedIterator(), and operator*().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/IteratorUtil.h