Unreal Engine 5.6 C++ API: FSlateFontCache Class Reference
FSlateFontCache Class Reference
Font caching implementation Caches characters into textures as needed.
#include "FontCache.h"
Public Member Functions
FSlateFontCache (TSharedRef< ISlateFontAtlasFactory > InFontAtlasFactory, ESlateTextureAtlasThreadId InOwningThread)
Constructor.
virtual ~FSlateFontCache ()
bool CanLoadCodepoint (const FFontData &InFontData, const UTF32CHAR InCodepoint, EFontFallback MaxFallbackLevel=EFontFallback::FF_NoFallback) const
Whether or not the specified character, within the specified font, can be loaded with the specified maximum font fallback level.
bool ConditionalFlushCache ()
Flush the cache if needed.
void FlushCompositeFont (const FCompositeFont &InCompositeFont)
Flush the given composite font out of the cache.
void FlushData ()
Clears just the cached font data, but leaves the atlases alone.
void FlushObject (const UObject *const InObject)
Flush the given object out of the cache.
virtual FSlateShaderResource * GetAtlasPageResource (const int32 InIndex) const override
Get the page resource for the given index (verify with GetNumAtlasPages)
TArray< FString > GetAvailableFontSubFaces (const FString &InFilename) const
TArray< FString > GetAvailableFontSubFaces (FFontFaceDataConstRef InMemory) const
Get the available sub-face data from the given font.
int16 GetBaseline (const FSlateFontInfo &InFontInfo, float FontScale) const
Returns the baseline for the specified font.
class FCharacterList & GetCharacterList (const FSlateFontInfo &InFontInfo, float FontScale, const FFontOutlineSettings &InOutlineSettings=FFontOutlineSettings::NoOutline)
Gets information for how to draw all non-shaped characters in the specified string.
const FFontData & GetDefaultFontData (const FSlateFontInfo &InFontInfo) const
Returns the font to use from the default typeface.
const TSet< FName > & GetFontAttributes (const FFontData &InFontData) const
Returns the font attributes for the specified font.
SIZE_T GetFontDataAssetResidentMemory (const UObject *FontDataAsset) const
Gets the allocated font face data for a font data asset.
const FFontData & GetFontDataForCodepoint (const FSlateFontInfo &InFontInfo, const UTF32CHAR InCodepoint, float &OutScalingFactor) const
Returns the font to use from the typeface associated with the given codepoint.
ISlateFontTexture * GetFontTexture (uint32 Index)
Get the texture resource for a font atlas at a given index.
int8 GetKerning (const FFontData &InFontData, const float InSize, TCHAR First, TCHAR Second, float Scale) const
Calculates the kerning amount for a pair of characters.
uint16 GetMaxCharacterHeight (const FSlateFontInfo &InFontInfo, float FontScale) const
Returns the height of the largest character in the font.
virtual int32 GetNumAtlasPages () const override
ISlateAtlasProvider.
FSdfGlyphFontAtlasData GetSdfGlyphFontAtlasData (const FShapedGlyphEntry &InShapedGlyph, const FFontOutlineSettings &InOutlineSettings)
Get the atlas information and the scaled metrics of a given shaped sdf glyph.
FShapedGlyphFontAtlasData GetShapedGlyphFontAtlasData (const FShapedGlyphEntry &InShapedGlyph, const FFontOutlineSettings &InOutlineSettings)
Get the atlas information for the given shaped glyph.
void GetStrikeMetrics (const FSlateFontInfo &InFontInfo, const float FontScale, int16 &OutStrikeLinePos, int16 &OutStrikeLineThickness) const
Get the strike metrics for the specified font.
void GetUnderlineMetrics (const FSlateFontInfo &InFontInfo, const float FontScale, int16 &OutUnderlinePos, int16 &OutUnderlineThickness) const
Get the underline metrics for the specified font.
bool HasKerning (const FFontData &InFontData) const
bool HasLoadedFontForCodepoint (const FSlateFontInfo &InFontInfo, const UTF32CHAR InCodepoint) const
Returns true if the font to use from the typeface associated with the given codepoint is already loaded.
virtual bool IsAtlasPageResourceAlphaOnly (const int32 InIndex) const override
Does the page resources for the given index only contain alpha information?
FOnReleaseFontResources & OnReleaseResources ()
Event called after releasing the rendering resources in ReleaseResources.
void ReleaseResources ()
Releases rendering resources.
void RequestFlushCache (const FString &FlushReason)
Issues a request to clear all cached data from the cache.
FShapedGlyphSequenceRef ShapeBidirectionalText (const FString &InText, const FSlateFontInfo &InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InBaseDirection, const ETextShapingMethod InTextShapingMethod) const
Performs text shaping on the given string using the given font info.
FShapedGlyphSequenceRef ShapeBidirectionalText (const TCHAR *InText, const int32 InTextStart, const int32 InTextLen, const FSlateFontInfo &InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InBaseDirection, const ETextShapingMethod InTextShapingMethod) const
FShapedGlyphSequenceRef ShapeOverflowEllipsisText (const FSlateFontInfo &InFontInfo, const float InFontScale)
Performs text shaping on the overflow glyph sequence for a given font.
FShapedGlyphSequenceRef ShapeUnidirectionalText (const FString &InText, const FSlateFontInfo &InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InTextDirection, const ETextShapingMethod InTextShapingMethod) const
Performs text shaping on the given range of the string using the given font info.
FShapedGlyphSequenceRef ShapeUnidirectionalText (const TCHAR *InText, const int32 InTextStart, const int32 InTextLen, const FSlateFontInfo &InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InTextDirection, const ETextShapingMethod InTextShapingMethod) const
UE_DEPRECATED (5.1, "GetOverflowEllipsisText is known to create dangling pointer. Use FShapedTextCache::FindOrAddOverflowEllipsisText.") 1 FShapedGlyphSequenceRef GetOverflowEllipsisText(const FSlateFontInfo &InFontInfo
Gets the overflow glyph sequence for a given font.
void UpdateCache ()
Updates the texture used for rendering.
Public Member Functions inherited from ISlateAtlasProvider
virtual ~ISlateAtlasProvider ()
Virtual destructor.
virtual FAtlasSlotInfo GetAtlasSlotInfoAtPosition (FIntPoint InPosition, int32 AtlasIndex) const =0
Finds a currently occupied slot at a position specified in atlas coordinates where 0,0 is the top left and the size of the atlas is bottom right.
Public Member Functions inherited from FSlateFlushableAtlasCache
FSlateFlushableAtlasCache (const FAtlasFlushParams *InFlushParams)
virtual ~FSlateFlushableAtlasCache ()
void ResetFlushCounters ()
Resets all counters to their initial state to start over flushing logic.
void UpdateFlushCounters (int32 NumGrayscale, int32 NumColor, int32 NumMsdf, int32 NumNonAtlased)
Increments counters that determine if a flush is needed.
Data Fields
const float InFontScale
Private Member Functions
FSlateFontCache (const FSlateFontCache &)
bool AddNewEntry (const FCharacterRenderData InRenderData, uint8 &OutTextureIndex, uint16 &OutGlyphX, uint16 &OutGlyphY, uint16 &OutGlyphWidth, uint16 &OutGlyphHeight, uint8 &OutPaddingOffset)
bool AddNewEntry (const FShapedGlyphEntry &InShapedGlyph, const FFontOutlineSettings &InOutlineSettings, FShapedGlyphFontAtlasData &OutAtlasData)
Add a new entries into a cache atlas.
void ConditionalDumpFontCacheStats () const
Dump statistics about Font cache usage if needed.
bool FlushCache ()
Clears all cached data from the cache.
void FlushFontObjects ()
Clears out any pending UFont objects that were requested to be flushed.
int32 GetAllFontTexturesIndex (const int32 InIndex) const
Returns the index for AllFontTextures array based on index in the concatenation of GrayscaleFontAtlasIndices, ColorFontAtlasIndices, and MsdfFontAtlasIndices.
void HandleCultureChanged ()
Called after the active culture has changed.
FSlateFontCache & operator= (const FSlateFontCache &)
Private Attributes
TArray< TSharedRef< ISlateFontTexture > > AllFontTextures
Array of all font textures - both atlased and non-atlased.
volatile bool bFlushRequested
Whether or not we have a pending request to flush the cache when it is safe to do so.
TArray< uint8 > ColorFontAtlasIndices
Array of color font atlas indices for use with AllFontTextures (cast the element to FSlateFontAtlas)
TUniquePtr< FCompositeFontCache > CompositeFontCache
High-level composite font cache (owned by this font cache)
FText EllipsisText
Overflow text string to use to replace clipped characters.
friend FCharacterList
TSharedRef< ISlateFontAtlasFactory > FontAtlasFactory
Factory for creating new font atlases.
TArray< const UObject * > FontObjectsToFlush
Array of UFont objects that the font cache has been requested to flush.
FCriticalSection FontObjectsToFlushCS
Critical section preventing concurrent access to FontObjectsToFlush.
TUniquePtr< FSlateFontRenderer > FontRenderer
FreeType font renderer (owned by this font cache)
TMap< FSlateFontKey, TUniquePtr< FCharacterList >, FDefaultSetAllocator, FSlateFontKeyFuncs< TUniquePtr< FCharacterList > > > FontToCharacterListCache
Mapping Font keys to cached data.
TUniquePtr< FFreeTypeCacheDirectory > FTCacheDirectory
FreeType low-level cache directory (owned by this font cache)
TUniquePtr< FFreeTypeLibrary > FTLibrary
FreeType library instance (owned by this font cache)
TArray< uint8 > GrayscaleFontAtlasIndices
Array of grayscale font atlas indices for use with AllFontTextures (cast the element to FSlateFontAtlas)
TArray< uint8 > MsdfFontAtlasIndices
Array of multi-channel distance field font atlas indices for use with AllFontTextures (cast the element to FSlateFontAtlas)
TArray< uint8 > NonAtlasedTextureIndices
Array of any non-atlased font texture indices for use with AllFontTextures.
FOnReleaseFontResources OnReleaseResourcesDelegate
Called after releasing the rendering resources in ReleaseResources.
ESlateTextureAtlasThreadId OwningThread
TUniquePtr< FSlateSdfGenerator > SdfGenerator
Sdf Rasterizer for Freetype fonts.
TMap< FSdfGlyphEntryKey, TSharedRef< FSdfGlyphFontAtlasData > > SdfGlyphToAtlasData
Mapping signed distance field glyphs to their cached atlas data.
TMap< FSdfGlyphTaskKey, TSharedRef< FSdfGlyphFontAtlasData > > SdfTaskToAtlasData
Mapping unfinished signed distance field tasks to their cached atlas data.
TMap< FShapedGlyphEntryKey, TSharedRef< FShapedGlyphFontAtlasData > > ShapedGlyphToAtlasData
Mapping shaped glyphs to their cached atlas data.
TUniquePtr< FSlateTextShaper > TextShaper
HarfBuzz text shaper (owned by this font cache)
Detailed Description
Font caching implementation Caches characters into textures as needed.
Definition at line 755 of file FontCache.h.
Constructor & Destructor Documentation
FSlateFontCache() [1/2]
FSlateFontCache::FSlateFontCache (TSharedRef< ISlateFontAtlasFactory > InFontAtlasFactory, ESlateTextureAtlasThreadId InOwningThread)
Constructor.
Parameters
InTextureSize The size of the atlas texture
InFontAlas Platform specific font atlas resource
Referenced by FSlateFontCache(), and operator=().
~FSlateFontCache()
virtual FSlateFontCache::~FSlateFontCache () virtual
FSlateFontCache() [2/2]
FSlateFontCache::FSlateFontCache (const FSlateFontCache &) private
References FSlateFontCache().
Member Function Documentation
AddNewEntry() [1/2]
bool FSlateFontCache::AddNewEntry (const FCharacterRenderData InRenderData, uint8 & OutTextureIndex, uint16 & OutGlyphX, uint16 & OutGlyphY, uint16 & OutGlyphWidth, uint16 & OutGlyphHeight, uint8 & OutPaddingOffset) private
AddNewEntry() [2/2]
bool FSlateFontCache::AddNewEntry (const FShapedGlyphEntry & InShapedGlyph, const FFontOutlineSettings & InOutlineSettings, FShapedGlyphFontAtlasData & OutAtlasData) private
Add a new entries into a cache atlas.
Parameters
InFontInfo Information about the font being used for the characters
Characters The characters to cache
FontScale The font scale to use
Returns
true if the characters could be cached. false if the cache is full
CanLoadCodepoint()
bool FSlateFontCache::CanLoadCodepoint (const FFontData & InFontData, const UTF32CHAR InCodepoint, EFontFallback MaxFallbackLevel = EFontFallback::FF_NoFallback) const
Whether or not the specified character, within the specified font, can be loaded with the specified maximum font fallback level.
Parameters
InFontData Information about the font to load
InCodepoint The codepoint being loaded
MaxFallbackLevel The maximum fallback level to try for the font
Returns
Whether or not the character can be loaded
References FF_NoFallback.
ConditionalDumpFontCacheStats()
void FSlateFontCache::ConditionalDumpFontCacheStats () const private
Dump statistics about Font cache usage if needed.
ConditionalFlushCache()
bool FSlateFontCache::ConditionalFlushCache ()
Flush the cache if needed.
References ConditionalFlushCache().
Referenced by ConditionalFlushCache().
FlushCache()
bool FSlateFontCache::FlushCache () private
Clears all cached data from the cache.
FlushCompositeFont()
void FSlateFontCache::FlushCompositeFont (const FCompositeFont & InCompositeFont)
Flush the given composite font out of the cache.
References FlushCompositeFont().
Referenced by FlushCompositeFont().
FlushData()
void FSlateFontCache::FlushData ()
Clears just the cached font data, but leaves the atlases alone.
FlushFontObjects()
void FSlateFontCache::FlushFontObjects () private
Clears out any pending UFont objects that were requested to be flushed.
FlushObject()
void FSlateFontCache::FlushObject (const UObject *const InObject)
Flush the given object out of the cache.
References FlushObject().
Referenced by FlushObject().
GetAllFontTexturesIndex()
int32 FSlateFontCache::GetAllFontTexturesIndex (const int32 InIndex) const private
Returns the index for AllFontTextures array based on index in the concatenation of GrayscaleFontAtlasIndices, ColorFontAtlasIndices, and MsdfFontAtlasIndices.
GetAtlasPageResource()
virtual FSlateShaderResource * FSlateFontCache::GetAtlasPageResource (const int32 InIndex) const override virtual
Get the page resource for the given index (verify with GetNumAtlasPages)
Implements ISlateAtlasProvider.
GetAvailableFontSubFaces() [1/2]
TArray< FString > FSlateFontCache::GetAvailableFontSubFaces (const FString & InFilename) const
GetAvailableFontSubFaces() [2/2]
TArray< FString > FSlateFontCache::GetAvailableFontSubFaces (FFontFaceDataConstRef InMemory) const
Get the available sub-face data from the given font.
Typically there will only be one face unless this is a TTC/OTC font. The index of the returned entry can be passed as InFaceIndex to the FFreeTypeFace constructor.
GetBaseline()
int16 FSlateFontCache::GetBaseline (const FSlateFontInfo & InFontInfo, float FontScale) const
Returns the baseline for the specified font.
Parameters
InFontInfo A descriptor of the font to get character size for
FontScale The scale to apply to the font
Returns
The offset from the bottom of the max character height to the baseline.
GetCharacterList()
class FCharacterList & FSlateFontCache::GetCharacterList (const FSlateFontInfo & InFontInfo, float FontScale, const FFontOutlineSettings & InOutlineSettings = FFontOutlineSettings::NoOutline)
Gets information for how to draw all non-shaped characters in the specified string.
Caches characters as they are found
Parameters
InFontInfo Information about the font that the string is drawn with
FontScale The scale to apply to the font
OutCharacterEntries Populated array of character entries. Indices of characters in Text match indices in this array
References FCharacterList.
GetDefaultFontData()
const FFontData & FSlateFontCache::GetDefaultFontData (const FSlateFontInfo & InFontInfo) const
Returns the font to use from the default typeface.
Parameters
InFontInfo A descriptor of the font to get the default typeface for
Returns
The raw font data
GetFontAttributes()
const TSet< FName > & FSlateFontCache::GetFontAttributes (const FFontData & InFontData) const
Returns the font attributes for the specified font.
Parameters
InFontData The font to get attributes for
Returns
The font attributes for the specified font.
GetFontDataAssetResidentMemory()
SIZE_T FSlateFontCache::GetFontDataAssetResidentMemory (const UObject * FontDataAsset) const
Gets the allocated font face data for a font data asset.
GetFontDataForCodepoint()
const FFontData & FSlateFontCache::GetFontDataForCodepoint (const FSlateFontInfo & InFontInfo, const UTF32CHAR InCodepoint, float & OutScalingFactor) const
Returns the font to use from the typeface associated with the given codepoint.
Parameters
InFontInfo A descriptor of the font to get the typeface for
InCodepoint The codepoint to get the typeface associated with
OutScalingFactor The scaling factor applied to characters rendered with the given font
Returns
The raw font data
GetFontTexture()
ISlateFontTexture * FSlateFontCache::GetFontTexture (uint32 Index) inline
Get the texture resource for a font atlas at a given index.
Parameters
Index The index of the texture
Returns
Handle to the texture resource
Definition at line 875 of file FontCache.h.
References AllFontTextures.
GetKerning()
int8 FSlateFontCache::GetKerning (const FFontData & InFontData, const float InSize, TCHAR First, TCHAR Second, float Scale) const
Calculates the kerning amount for a pair of characters.
Parameters
InFontData The font that used to draw the string with the first and second characters
InSize The size of the font to draw
First The first character in the pair
Second The second character in the pair
Returns
The kerning amount, 0 if no kerning
References First, Scale, and Second.
GetMaxCharacterHeight()
uint16 FSlateFontCache::GetMaxCharacterHeight (const FSlateFontInfo & InFontInfo, float FontScale) const
Returns the height of the largest character in the font.
Parameters
InFontInfo A descriptor of the font to get character size for
FontScale The scale to apply to the font
Returns
The largest character height
GetNumAtlasPages()
virtual int32 FSlateFontCache::GetNumAtlasPages () const override virtual
ISlateAtlasProvider.
Implements ISlateAtlasProvider.
GetSdfGlyphFontAtlasData()
FSdfGlyphFontAtlasData FSlateFontCache::GetSdfGlyphFontAtlasData (const FShapedGlyphEntry & InShapedGlyph, const FFontOutlineSettings & InOutlineSettings)
Get the atlas information and the scaled metrics of a given shaped sdf glyph.
This information will be cached if required.
GetShapedGlyphFontAtlasData()
FShapedGlyphFontAtlasData FSlateFontCache::GetShapedGlyphFontAtlasData (const FShapedGlyphEntry & InShapedGlyph, const FFontOutlineSettings & InOutlineSettings)
Get the atlas information for the given shaped glyph.
This information will be cached if required
GetStrikeMetrics()
void FSlateFontCache::GetStrikeMetrics (const FSlateFontInfo & InFontInfo, const float FontScale, int16 & OutStrikeLinePos, int16 & OutStrikeLineThickness) const
Get the strike metrics for the specified font.
Parameters
InFontInfo A descriptor of the font to get character size for
FontScale The scale to apply to the font
OutStrikeLinePos The offset from the baseline to the center of the strike bar
OutStrikeLineThickness The thickness of the strike bar
GetUnderlineMetrics()
void FSlateFontCache::GetUnderlineMetrics (const FSlateFontInfo & InFontInfo, const float FontScale, int16 & OutUnderlinePos, int16 & OutUnderlineThickness) const
Get the underline metrics for the specified font.
Parameters
InFontInfo A descriptor of the font to get character size for
FontScale The scale to apply to the font
OutUnderlinePos The offset from the baseline to the center of the underline bar
OutUnderlineThickness The thickness of the underline bar
HandleCultureChanged()
void FSlateFontCache::HandleCultureChanged () private
Called after the active culture has changed.
HasKerning()
bool FSlateFontCache::HasKerning (const FFontData & InFontData) const
Returns
Whether or not the font used has kerning information
HasLoadedFontForCodepoint()
bool FSlateFontCache::HasLoadedFontForCodepoint (const FSlateFontInfo & InFontInfo, const UTF32CHAR InCodepoint) const
Returns true if the font to use from the typeface associated with the given codepoint is already loaded.
Parameters
InFontInfo A descriptor of the font to get the typeface for
InCodepoint The codepoint to get the typeface associated with
Returns
FontData is already loaded
IsAtlasPageResourceAlphaOnly()
virtual bool FSlateFontCache::IsAtlasPageResourceAlphaOnly (const int32 InIndex) const override virtual
Does the page resources for the given index only contain alpha information?
This affects how the atlas visualizer will sample them (verify with GetNumAtlasPages)
Implements ISlateAtlasProvider.
OnReleaseResources()
FOnReleaseFontResources & FSlateFontCache::OnReleaseResources () inline
Event called after releasing the rendering resources in ReleaseResources.
Definition at line 867 of file FontCache.h.
References OnReleaseResources(), and OnReleaseResourcesDelegate.
Referenced by OnReleaseResources().
operator=()
FSlateFontCache & FSlateFontCache::operator= (const FSlateFontCache &) private
References FSlateFontCache().
ReleaseResources()
void FSlateFontCache::ReleaseResources ()
Releases rendering resources.
References ReleaseResources().
Referenced by ReleaseResources().
RequestFlushCache()
void FSlateFontCache::RequestFlushCache (const FString & FlushReason) virtual
Issues a request to clear all cached data from the cache.
Implements FSlateFlushableAtlasCache.
ShapeBidirectionalText() [1/2]
FShapedGlyphSequenceRef FSlateFontCache::ShapeBidirectionalText (const FString & InText, const FSlateFontInfo & InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InBaseDirection, const ETextShapingMethod InTextShapingMethod) const
Performs text shaping on the given string using the given font info.
Returns you the shaped text sequence to use for text rendering via FSlateDrawElement::MakeShapedText. When using the version which takes a start point and length, the text outside of the given range won't be shaped, but will provide context information to allow the shaping to function correctly. ShapeBidirectionalText is used when you have text that may contain a mixture of LTR and RTL text runs.
Parameters
InText The string to shape
InTextStart The start position of the text to shape
InTextLen The length of the text to shape
InFontInfo Information about the font that the string is drawn with
InFontScale The scale to apply to the font
InBaseDirection The overall reading direction of the text (see TextBiDi::ComputeBaseDirection). This will affect where some characters (such as brackets and quotes) are placed within the resultant shaped text
InTextShapingMethod The text shaping method to use
References InFontScale.
ShapeBidirectionalText() [2/2]
FShapedGlyphSequenceRef FSlateFontCache::ShapeBidirectionalText (const TCHAR * InText, const int32 InTextStart, const int32 InTextLen, const FSlateFontInfo & InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InBaseDirection, const ETextShapingMethod InTextShapingMethod) const
References InFontScale.
ShapeOverflowEllipsisText()
FShapedGlyphSequenceRef FSlateFontCache::ShapeOverflowEllipsisText (const FSlateFontInfo & InFontInfo, const float InFontScale)
Performs text shaping on the overflow glyph sequence for a given font.
The overflow sequence is used to replace characters that are clipped
References InFontScale.
ShapeUnidirectionalText() [1/2]
FShapedGlyphSequenceRef FSlateFontCache::ShapeUnidirectionalText (const FString & InText, const FSlateFontInfo & InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InTextDirection, const ETextShapingMethod InTextShapingMethod) const
Performs text shaping on the given range of the string using the given font info.
Returns you the shaped text sequence to use for text rendering via FSlateDrawElement::MakeShapedText. When using the version which takes a start point and length, the text outside of the given range won't be shaped, but will provide context information to allow the shaping to function correctly. ShapeUnidirectionalText is used when you have text that all reads in the same direction (either LTR or RTL).
Parameters
InText The string containing the sub-string to shape
InTextStart The start position of the text to shape
InTextLen The length of the text to shape
InFontInfo Information about the font that the string is drawn with
InFontScale The scale to apply to the font
InTextDirection The reading direction of the text to shape (valid values are LeftToRight or RightToLeft)
InTextShapingMethod The text shaping method to use
References InFontScale.
ShapeUnidirectionalText() [2/2]
FShapedGlyphSequenceRef FSlateFontCache::ShapeUnidirectionalText (const TCHAR * InText, const int32 InTextStart, const int32 InTextLen, const FSlateFontInfo & InFontInfo, const float InFontScale, const TextBiDi::ETextDirection InTextDirection, const ETextShapingMethod InTextShapingMethod) const
References InFontScale.
UE_DEPRECATED()
FSlateFontCache::UE_DEPRECATED (5. 1, "GetOverflowEllipsisText is known to create dangling pointer. Use FShapedTextCache::FindOrAddOverflowEllipsisText.") const &
Gets the overflow glyph sequence for a given font.
The overflow sequence is used to replace characters that are clipped
UpdateCache()
void FSlateFontCache::UpdateCache ()
Updates the texture used for rendering.
References UpdateCache().
Referenced by UpdateCache().
Field Documentation
AllFontTextures
TArray<TSharedRef<ISlateFontTexture> > FSlateFontCache::AllFontTextures private
Array of all font textures - both atlased and non-atlased.
Definition at line 1095 of file FontCache.h.
Referenced by GetFontTexture().
bFlushRequested
volatile bool FSlateFontCache::bFlushRequested private
Whether or not we have a pending request to flush the cache when it is safe to do so.
Definition at line 1101 of file FontCache.h.
ColorFontAtlasIndices
TArray<uint8> FSlateFontCache::ColorFontAtlasIndices private
Array of color font atlas indices for use with AllFontTextures (cast the element to FSlateFontAtlas)
Definition at line 1086 of file FontCache.h.
CompositeFontCache
TUniquePtr<FCompositeFontCache> FSlateFontCache::CompositeFontCache private
High-level composite font cache (owned by this font cache)
Definition at line 1059 of file FontCache.h.
EllipsisText
FText FSlateFontCache::EllipsisText private
Overflow text string to use to replace clipped characters.
Definition at line 1115 of file FontCache.h.
FCharacterList
friend FSlateFontCache::FCharacterList private
Definition at line 757 of file FontCache.h.
Referenced by GetCharacterList().
FontAtlasFactory
TSharedRef<ISlateFontAtlasFactory> FSlateFontCache::FontAtlasFactory private
Factory for creating new font atlases.
Definition at line 1098 of file FontCache.h.
FontObjectsToFlush
TArray<const UObject*> FSlateFontCache::FontObjectsToFlush private
Array of UFont objects that the font cache has been requested to flush.
Since GC can happen while the loading screen is running, the request may be deferred until the next call to ConditionalFlushCache
Definition at line 1107 of file FontCache.h.
FontObjectsToFlushCS
FCriticalSection FSlateFontCache::FontObjectsToFlushCS mutable private
Critical section preventing concurrent access to FontObjectsToFlush.
Definition at line 1104 of file FontCache.h.
FontRenderer
TUniquePtr<FSlateFontRenderer> FSlateFontCache::FontRenderer private
FreeType font renderer (owned by this font cache)
Definition at line 1062 of file FontCache.h.
FontToCharacterListCache
TMap<FSlateFontKey, TUniquePtr<FCharacterList>, FDefaultSetAllocator, FSlateFontKeyFuncs<TUniquePtr<FCharacterList> > > FSlateFontCache::FontToCharacterListCache private
Mapping Font keys to cached data.
Definition at line 1071 of file FontCache.h.
FTCacheDirectory
TUniquePtr<FFreeTypeCacheDirectory> FSlateFontCache::FTCacheDirectory private
FreeType low-level cache directory (owned by this font cache)
Definition at line 1056 of file FontCache.h.
FTLibrary
TUniquePtr<FFreeTypeLibrary> FSlateFontCache::FTLibrary private
FreeType library instance (owned by this font cache)
Definition at line 1053 of file FontCache.h.
GrayscaleFontAtlasIndices
TArray<uint8> FSlateFontCache::GrayscaleFontAtlasIndices private
Array of grayscale font atlas indices for use with AllFontTextures (cast the element to FSlateFontAtlas)
Definition at line 1083 of file FontCache.h.
InFontScale
const float FSlateFontCache::InFontScale
Definition at line 836 of file FontCache.h.
Referenced by ShapeBidirectionalText(), ShapeBidirectionalText(), ShapeOverflowEllipsisText(), ShapeUnidirectionalText(), and ShapeUnidirectionalText().
MsdfFontAtlasIndices
TArray<uint8> FSlateFontCache::MsdfFontAtlasIndices private
Array of multi-channel distance field font atlas indices for use with AllFontTextures (cast the element to FSlateFontAtlas)
Definition at line 1089 of file FontCache.h.
NonAtlasedTextureIndices
TArray<uint8> FSlateFontCache::NonAtlasedTextureIndices private
Array of any non-atlased font texture indices for use with AllFontTextures.
Definition at line 1092 of file FontCache.h.
OnReleaseResourcesDelegate
FOnReleaseFontResources FSlateFontCache::OnReleaseResourcesDelegate private
Called after releasing the rendering resources in ReleaseResources.
Definition at line 1110 of file FontCache.h.
Referenced by OnReleaseResources().
OwningThread
ESlateTextureAtlasThreadId FSlateFontCache::OwningThread private
Definition at line 1112 of file FontCache.h.
SdfGenerator
TUniquePtr<FSlateSdfGenerator> FSlateFontCache::SdfGenerator private
Sdf Rasterizer for Freetype fonts.
Definition at line 1068 of file FontCache.h.
SdfGlyphToAtlasData
TMap<FSdfGlyphEntryKey, TSharedRef<FSdfGlyphFontAtlasData> > FSlateFontCache::SdfGlyphToAtlasData private
Mapping signed distance field glyphs to their cached atlas data.
Definition at line 1077 of file FontCache.h.
SdfTaskToAtlasData
TMap<FSdfGlyphTaskKey, TSharedRef<FSdfGlyphFontAtlasData> > FSlateFontCache::SdfTaskToAtlasData private
Mapping unfinished signed distance field tasks to their cached atlas data.
Definition at line 1080 of file FontCache.h.
ShapedGlyphToAtlasData
TMap<FShapedGlyphEntryKey, TSharedRef<FShapedGlyphFontAtlasData> > FSlateFontCache::ShapedGlyphToAtlasData private
Mapping shaped glyphs to their cached atlas data.
Definition at line 1074 of file FontCache.h.
TextShaper
TUniquePtr<FSlateTextShaper> FSlateFontCache::TextShaper private
HarfBuzz text shaper (owned by this font cache)
Definition at line 1065 of file FontCache.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Fonts/FontCache.h