Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicGraph2< T > Class Template Reference
UE::Geometry::FDynamicGraph2< T > Class Template Reference
#include "DynamicGraph2.h"
Public Member Functions
int AppendVertex (TVector2< T > V)
TAxisAlignedBox2< T > CachedBounds ()
cached bounding box, lazily re-computed on access if mesh has changed
FAxisAlignedBox2d GetBounds () const
TVector2< T > GetEdgeCenter (int EID) const
TSegment2< T > GetEdgeSegment (int EID) const
FIndex2i GetEdgeV (int EID) const
bool GetEdgeV (int EID, UE::Math::TVector2< T > &A, UE::Math::TVector2< T > &B) const
TVector2< T > GetVertex (int VID) const
double OpeningAngle (int VID, double InvalidValue=TNumericLimits< T >::Max()) const
Compute opening angle at vertex VID.
void SetVertex (int VID, TVector2< T > VNewPos)
bool SortedVtxEdges (int VID, TArray< int > &Sorted) const
return edges around VID sorted by angle, in counter-clockwise order
value_iteration< TVector2< T > > Vertices () const
Enumerate positions of all vertices in graph.
Public Member Functions inherited from UE::Geometry::FDynamicGraph
FDynamicGraph ()
virtual ~FDynamicGraph ()
int AllocateEdgeGroup ()
int AppendEdge (const FEdge &E)
int AppendEdge (const FIndex2i &ev, int GID=-1)
int AppendEdge (int v0, int v1, int GID=-1)
virtual bool CheckValidity (EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check) const
This function checks that the graph is well-formed, ie all internal data structures are consistent.
EMeshResult CollapseEdge (int VKeep, int VRemove, FEdgeCollapseInfo &Collapse)
int EdgeCount () const
edge_iterator EdgeIndices () const
value_iteration< FEdge > Edges () const
Enumerate edges.
int FindEdge (int VA, int VB) const
FEdge GetEdge (int EID) const
int GetEdgeGroup (int EID) const
FIndex2i GetEdgeV (int EID) const
int GetMaxVtxEdgeCount () const
int GetVtxEdgeCount (int VID) const
bool IsBoundaryVertex (int VID) const
bool IsCompact () const
bool IsCompactV () const
bool IsEdge (int EID) const
bool IsJunctionVertex (int VID) const
bool IsRegularVertex (int VID) const
bool IsVertex (int VID) const
int MaxEdgeID () const
int MaxGroupID () const
int MaxVertexID () const
EMeshResult RemoveEdge (int EID, bool bRemoveIsolatedVertices)
EMeshResult RemoveVertex (int VID, bool bRemoveIsolatedVertices)
void SetEdgeGroup (int EID, int GroupID)
int ShapeTimestamp () const
EMeshResult SplitEdge (int EAB, FEdgeSplitInfo &Split)
EMeshResult SplitEdge (int VA, int VB, FEdgeSplitInfo &Split)
EMeshResult SplitEdgeWithExistingVertex (int EAB, int ExistingMidVert, FEdgeSplitInfo &Split)
int Timestamp () const
int VertexCount () const
vertex_iterator VertexIndices () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int VID) const
Enumerate edge ids connected to vertex (i.e.
FSmallListSet::MappedValueEnumerable VtxVerticesItr (int VID) const
Enumerate "other" vertices of edges connected to vertex (i.e.
Static Public Member Functions
static TVector2< T > InvalidVertex ()
Static Public Member Functions inherited from UE::Geometry::FDynamicGraph
static FEdge InvalidEdge3 ()
static FIndex2i InvalidEdgeV ()
Protected Member Functions
virtual int append_new_split_vertex (int A, int B) override
virtual void subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const override
Protected Member Functions inherited from UE::Geometry::FDynamicGraph
int add_edge (int A, int B, int GID)
int append_vertex_internal ()
void debug_check_is_edge (int E) const
void debug_check_is_vertex (int V) const
bool edge_has_v (int EID, int VID) const
int edge_other_v (int EID, int VID) const
bool insert_vertex_internal (int32 Vid)
int replace_edge_vertex (int EID, int VOld, int VNew)
void updateTimeStamp (bool bShapeChange)
Private Attributes
TAxisAlignedBox2< T > cached_bounds
int cached_bounds_timestamp = -1
TDynamicVectorN< T, 2 > vertices
Additional Inherited Members
Public Types inherited from UE::Geometry::FDynamicGraph
typedef FRefCountVector::IndexEnumerable edge_iterator
template<typename T>
using value_iteration = FRefCountVector::MappedEnumerable<T>
typedef FRefCountVector::IndexEnumerable vertex_iterator
Static Public Attributes inherited from UE::Geometry::FDynamicGraph
static constexpr int DuplicateEdgeID = -2
static constexpr int InvalidID = IndexConstants::InvalidID
Protected Attributes inherited from UE::Geometry::FDynamicGraph
TDynamicVector< FEdge > edges
FRefCountVector edges_refcount
int max_group_id = 0
int shape_timestamp = 0
int timestamp = 0
FSmallListSet vertex_edges
FRefCountVector vertices_refcount
Detailed Description
template<typename T>
class UE::Geometry::FDynamicGraph2< T >
Definition at line 26 of file DynamicGraph2.h.
Member Function Documentation
append_new_split_vertex()
template<typename T> virtual int UE::Geometry::FDynamicGraph2< T >::append_new_split_vertex (int A, int B) inline override protected virtual
Reimplemented from UE::Geometry::FDynamicGraph.
Definition at line 229 of file DynamicGraph2.h.
AppendVertex()
template<typename T> int UE::Geometry::FDynamicGraph2< T >::AppendVertex (TVector2< T > V) inline
Definition at line 82 of file DynamicGraph2.h.
Referenced by UE::Geometry::FDynamicGraph2< double >::append_new_split_vertex().
CachedBounds()
template<typename T> TAxisAlignedBox2< T > UE::Geometry::FDynamicGraph2< T >::CachedBounds () inline
cached bounding box, lazily re-computed on access if mesh has changed
Definition at line 181 of file DynamicGraph2.h.
GetBounds()
template<typename T> FAxisAlignedBox2d UE::Geometry::FDynamicGraph2< T >::GetBounds () const inline
Definition at line 170 of file DynamicGraph2.h.
Referenced by UE::Geometry::FDynamicGraph2< double >::CachedBounds().
GetEdgeCenter()
template<typename T> TVector2< T > UE::Geometry::FDynamicGraph2< T >::GetEdgeCenter (int EID) const inline
Definition at line 75 of file DynamicGraph2.h.
GetEdgeSegment()
template<typename T> TSegment2< T > UE::Geometry::FDynamicGraph2< T >::GetEdgeSegment (int EID) const inline
Definition at line 66 of file DynamicGraph2.h.
GetEdgeV() [1/2]
template<typename T> FIndex2i UE::Geometry::FDynamicGraph::GetEdgeV (int EID) const inline
Definition at line 152 of file DynamicGraph.h.
GetEdgeV() [2/2]
template<typename T> bool UE::Geometry::FDynamicGraph2< T >::GetEdgeV (int EID, UE::Math::TVector2< T > & A, UE::Math::TVector2< T > & B) const inline
Definition at line 55 of file DynamicGraph2.h.
GetVertex()
template<typename T> TVector2< T > UE::Geometry::FDynamicGraph2< T >::GetVertex (int VID) const inline
Definition at line 39 of file DynamicGraph2.h.
Referenced by UE::Geometry::FDynamicGraph2< double >::append_new_split_vertex(), and UE::Geometry::FDynamicGraph2< double >::subclass_validity_checks().
InvalidVertex()
template<typename T> TVector2< T > UE::Geometry::FDynamicGraph2< T >::InvalidVertex () inline static
Definition at line 34 of file DynamicGraph2.h.
Referenced by UE::Geometry::FDynamicGraph2< double >::GetVertex().
OpeningAngle()
template<typename T> double UE::Geometry::FDynamicGraph2< T >::OpeningAngle (int VID, double InvalidValue = TNumericLimits<T>::Max()) const inline
Compute opening angle at vertex VID.
If not a vertex, or valence != 2, returns InvalidValue argument. If either edge is degenerate, returns InvalidValue argument.
Definition at line 196 of file DynamicGraph2.h.
SetVertex()
template<typename T> void UE::Geometry::FDynamicGraph2< T >::SetVertex (int VID, TVector2< T > VNewPos) inline
Definition at line 44 of file DynamicGraph2.h.
SortedVtxEdges()
template<typename T> bool UE::Geometry::FDynamicGraph2< T >::SortedVtxEdges (int VID, TArray< int > & Sorted) const inline
return edges around VID sorted by angle, in counter-clockwise order
Definition at line 150 of file DynamicGraph2.h.
subclass_validity_checks()
template<typename T> virtual void UE::Geometry::FDynamicGraph2< T >::subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const inline override protected virtual
Reimplemented from UE::Geometry::FDynamicGraph.
Definition at line 236 of file DynamicGraph2.h.
Vertices()
template<typename T> value_iteration< TVector2< T > > UE::Geometry::FDynamicGraph2< T >::Vertices () const inline
Enumerate positions of all vertices in graph.
Definition at line 139 of file DynamicGraph2.h.
Referenced by UE::Geometry::FDynamicGraph2< double >::GetBounds().
Field Documentation
cached_bounds
template<typename T> TAxisAlignedBox2<T> UE::Geometry::FDynamicGraph2< T >::cached_bounds private
Definition at line 28 of file DynamicGraph2.h.
cached_bounds_timestamp
template<typename T> int UE::Geometry::FDynamicGraph2< T >::cached_bounds_timestamp = -1 private
Definition at line 29 of file DynamicGraph2.h.
vertices
template<typename T> TDynamicVectorN<T, 2> UE::Geometry::FDynamicGraph2< T >::vertices private
Definition at line 31 of file DynamicGraph2.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Curve/DynamicGraph2.h