Unreal Engine 5.6 C++ API: FSkinnedAssetAsyncBuildWorker Class Reference
FSkinnedAssetAsyncBuildWorker Class Reference
Worker used to perform async static mesh compilation.
#include "SkinnedAssetAsyncCompileUtils.h"
Public Member Functions
FSkinnedAssetAsyncBuildWorker (USkinnedAsset *InSkinnedAsset, FSkinnedAssetBuildContext &&InBuildContext)
Initialization constructor.
FSkinnedAssetAsyncBuildWorker (USkinnedAsset *InSkinnedAsset, FSkinnedAssetPostLoadContext &&InPostLoadContext)
Initialization constructor.
FSkinnedAssetAsyncBuildWorker (USkinnedAsset *InSkinnedAsset, FSkinnedAsyncTaskContext &&InAsyncTaskContext)
void DoWork ()
FORCEINLINE TStatId GetStatId () const
Public Member Functions inherited from FNonAbandonableTask
void Abandon ()
bool CanAbandon ()
Data Fields
TOptional< FSkinnedAsyncTaskContext > AsyncTaskContext
TOptional< FSkinnedAssetBuildContext > BuildContext
TOptional< FSkinnedAssetPostLoadContext > PostLoadContext
USkinnedAsset * SkinnedAsset
Detailed Description
Worker used to perform async static mesh compilation.
Definition at line 76 of file SkinnedAssetAsyncCompileUtils.h.
Constructor & Destructor Documentation
FSkinnedAssetAsyncBuildWorker() [1/3]
FSkinnedAssetAsyncBuildWorker::FSkinnedAssetAsyncBuildWorker (USkinnedAsset * InSkinnedAsset, FSkinnedAssetBuildContext && InBuildContext) inline
Initialization constructor.
Definition at line 85 of file SkinnedAssetAsyncCompileUtils.h.
References BuildContext, MoveTemp(), and SkinnedAsset.
Referenced by GetStatId().
FSkinnedAssetAsyncBuildWorker() [2/3]
FSkinnedAssetAsyncBuildWorker::FSkinnedAssetAsyncBuildWorker (USkinnedAsset * InSkinnedAsset, FSkinnedAssetPostLoadContext && InPostLoadContext) inline
Initialization constructor.
Definition at line 94 of file SkinnedAssetAsyncCompileUtils.h.
References MoveTemp(), PostLoadContext, and SkinnedAsset.
FSkinnedAssetAsyncBuildWorker() [3/3]
FSkinnedAssetAsyncBuildWorker::FSkinnedAssetAsyncBuildWorker (USkinnedAsset * InSkinnedAsset, FSkinnedAsyncTaskContext && InAsyncTaskContext) inline
Definition at line 102 of file SkinnedAssetAsyncCompileUtils.h.
References AsyncTaskContext, MoveTemp(), and SkinnedAsset.
Member Function Documentation
DoWork()
void FSkinnedAssetAsyncBuildWorker::DoWork ()
GetStatId()
FORCEINLINE TStatId FSkinnedAssetAsyncBuildWorker::GetStatId () const inline
Definition at line 110 of file SkinnedAssetAsyncCompileUtils.h.
References FSkinnedAssetAsyncBuildWorker(), FORCEINLINE, and RETURN_QUICK_DECLARE_CYCLE_STAT.
Field Documentation
AsyncTaskContext
TOptional<FSkinnedAsyncTaskContext> FSkinnedAssetAsyncBuildWorker::AsyncTaskContext
Definition at line 82 of file SkinnedAssetAsyncCompileUtils.h.
Referenced by FSkinnedAssetAsyncBuildWorker().
BuildContext
TOptional<FSkinnedAssetBuildContext> FSkinnedAssetAsyncBuildWorker::BuildContext
Definition at line 81 of file SkinnedAssetAsyncCompileUtils.h.
Referenced by FSkinnedAssetAsyncBuildWorker().
PostLoadContext
TOptional<FSkinnedAssetPostLoadContext> FSkinnedAssetAsyncBuildWorker::PostLoadContext
Definition at line 80 of file SkinnedAssetAsyncCompileUtils.h.
Referenced by FSkinnedAssetAsyncBuildWorker().
SkinnedAsset
USkinnedAsset* FSkinnedAssetAsyncBuildWorker::SkinnedAsset
Definition at line 79 of file SkinnedAssetAsyncCompileUtils.h.
Referenced by FSkinnedAssetAsyncBuildWorker(), FSkinnedAssetAsyncBuildWorker(), and FSkinnedAssetAsyncBuildWorker().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/SkinnedAssetAsyncCompileUtils.h