Unreal Engine 5.6 C++ API: UE::Geometry::FSimpleIntrinsicEdgeFlipMesh Class Reference
UE::Geometry::FSimpleIntrinsicEdgeFlipMesh Class Reference
Intrinsic Meshes:
#include "IntrinsicTriangulationMesh.h"
Data Structures
struct FEdgeFlipInfo
Public Types
using FEdge = FDynamicMesh3::FEdge
Public Member Functions
FSimpleIntrinsicEdgeFlipMesh ()
DYNAMICMESH_API FSimpleIntrinsicEdgeFlipMesh (const FDynamicMesh3 &SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
FSimpleIntrinsicEdgeFlipMesh (const FSimpleIntrinsicEdgeFlipMesh &)=delete
bool AreSameOrientation (int32 EID) const
DYNAMICMESH_API void Clear ()
Discard all data.
DYNAMICMESH_API double EdgeCotanWeight (int32 EID) const
return 1/2 (cot(alpha_{ij}) + cot(beta_{ij})) where alpha_{ij} and beta_{ij} are the to interior angles opposite the specified edge, EID.
int32 EdgeCount () const
FRefCountVector::IndexEnumerable EdgeIndicesItr () const
DYNAMICMESH_API FVector2d EdgeOpposingAngles (int32 EID) const
return FVector2(alpha_{ij} , beta_{ij}) where alpha_{ij} and beta_{ij} are the two interior angles opposite the specified edge, EID.
DYNAMICMESH_API EMeshResult FlipEdge (int32 EID, FEdgeFlipInfo &EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
FEdge GetEdge (int32 EdgeID) const
double GetEdgeLength (int32 EID) const
DYNAMICMESH_API FIndex2i GetEdgeOpposingV (int32 EID) const
FIndex2i GetEdgeT (int32 EdgeID) const
FIndex2i GetEdgeV (int32 EdgeID) const
FIndex3i GetTriangle (int32 TriangleID) const
const FIndex3i & GetTriangleRef (int TriangleID) const
FVector3d GetTriEdgeLengths (const int32 TID) const
FIndex3i GetTriEdges (int32 TriangleID) const
double GetTriInternalAngleR (const int32 TID, const int32 IndexOf) const
FVector3d GetVertex (int32 VertexID) const
int32 GetVtxEdgeCount (int32 VID) const
bool IsBoundaryEdge (int32 EdgeID) const
bool IsBoundaryVertex (int32 VertexID) const
bool IsEdge (int32 EdgeID) const
bool IsTriangle (int32 TriangleID) const
bool IsVertex (int32 VertexID) const
int32 MaxEdgeID () const
int32 MaxTriangleID () const
int32 MaxVertexID () const
template<typename Vector3Type>
Vector3Type Permute (int32 Index, const Vector3Type &Src) const
cyclic permutation of the src vector such that the 'Index' entry in the src is the first entry in the result NB: Index must be 0, 1, or 2.
DYNAMICMESH_API void Reset (const FDynamicMesh3 &SrcMesh)
Reset the mesh to an ID-matching deep copy the basic mesh topology (but no attributes or groups)
int32 TriangleCount () const
FRefCountVector::IndexEnumerable TriangleIndicesItr () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int32 VID) const
Static Public Attributes
static constexpr int InvalidID = IndexConstants::InvalidID
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Protected Member Functions
DYNAMICMESH_API FVector3d ComputeTriInternalAnglesR (const int32 TID) const
computes the angles based on the edge lengths, so must have valid EdgeLengths for this tri before calling.
DYNAMICMESH_API EMeshResult FlipEdgeTopology (int32 eab, FEdgeFlipInfo &FlipInfo)
update the mesh topology (e.g.
FVector3d GetEdgeLengthTriple (const FIndex3i &EIDs) const
DYNAMICMESH_API double GetOpposingVerticesDistance (int32 EID) const
DYNAMICMESH_API FIndex2i GetOrientedEdgeV (int32 EID, int32 TID) const
DYNAMICMESH_API int32 ReplaceEdgeTriangle (int32 eID, int32 tOld, int32 tNew)
replace tOld with tNew in an existing edge
int32 ReplaceTriangleEdge (int32 tID, int32 eOld, int32 eNew)
replace eOld with eNew in and existing triangle
void SetEdgeTrianglesInternal (int32 EdgeID, int32 t0, int32 t1)
update the existing edge to reference triangles t0 and t1
void SetEdgeVerticesInternal (int32 EdgeID, int32 a, int32 b)
update the existing edge to reference vertices 'a' and 'b'.
Protected Attributes
const int32 AddOneModThree [3] = { 1, 2, 0 }
const int32 AddTwoModThree [3] = { 2, 0, 1 }
TDynamicVector< double > EdgeLengths
FRefCountVector EdgeRefCounts {}
TDynamicVector< FEdge > Edges
TDynamicVector< FVector3d > InternalAngles
TDynamicVector< FIndex3i > TriangleEdges
FRefCountVector TriangleRefCounts {}
TDynamicVector< FIndex3i > Triangles
FSmallListSet VertexEdgeLists
FRefCountVector VertexRefCounts {}
TDynamicVector< FVector3d > Vertices {}
Detailed Description
Intrinsic Meshes:
An Intrinsic Mesh can be thought of as a mesh that overlays another mesh, sharing the original surface. The edges of the intrinsic mesh are constrained to be on the original mesh surface, but need not align with the original mesh edges. The lengths of the intrinsic edges are measured on the surface of the original mesh (not the R3 distance). The original mesh vertices are a subset of the intrinsic mesh vertices and intrinsic edge splits and triangle pokes may introduce new intrinsic mesh vertices.
Note: the implementation is a simple triangle-based mesh but there is no restriction that edge(a, b) is unique (e.g. multiple intrinsic edges may connect the same two vertices with different paths). In fact this mesh allows triangles and edges with repeated vertices. Such structures arise naturally with intrinsic triangulation, for example an edge that starts and ends at the same vertex may encircle a mesh.
The bookkeeping that manages the correspondence between locations on the intrinsic mesh and on the surface mesh is implemented either using integer-based "Normal Coordinates" (cf 'Integer Coordinates for Intrinsic Geometry Processing' M. Gillespie, N. Sharp, and K. Crane, TOG , Vol. 40, December 2021.) as used by FIntrinsicEdgeFlipMesh and FIntrinsicMesh; or alternately floating-point based generalized directions "Signpost data" (cf 'Signpost Coordinates inspired by "Navigating Intrinsic Triangulations' Sharp, Soliman and Crane [2019, ACM Transactions on Graphics]) as used by FIntrinsicTriangulation. The FSimpleIntrinsicEdgeFlipMesh is designed to work with the function FlipToDelaunay() to make an Intrinsic Delaunay Triangulation (IDT) of the same surface as a given FDynamicMesh, allowing for more robust cotangent-Laplacians (see LaplacianMatrixAssembly.h)
The vertices in this FSimpleIntrinsicEdgeFlipMesh are exactly those found in the surface mesh since it supports edge flips, but no other operations that change the mesh connectivity, and no operations that affect the vertices.
This mesh alone does not support computing the intersections of intrinsic edges with the surface mesh edges and as a result it can not be used to easily extract the path of an intrinsic edge. To do such computations FIntrinsicEdgeFlipMesh, FIntrinsicMesh or FIntrinsicTriangulation should be used.
The API of FIntrinsicEdgeFlipMesh is similar to FDynamicMesh3, but only has a minimal subset of methods and some such as FlipEdge() and GetEdgeOpposingV() have very different implementations.
In addition to managing vertices, triangles and edges this class also tracks edge lengths (as measured on the surface mesh) and for convenience the internal angles for each triangle.
Definition at line 65 of file IntrinsicTriangulationMesh.h.
Member Typedef Documentation
FEdge
using UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::FEdge = FDynamicMesh3::FEdge
Definition at line 69 of file IntrinsicTriangulationMesh.h.
Constructor & Destructor Documentation
FSimpleIntrinsicEdgeFlipMesh() [1/3]
UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::FSimpleIntrinsicEdgeFlipMesh () inline
Definition at line 80 of file IntrinsicTriangulationMesh.h.
Referenced by FSimpleIntrinsicEdgeFlipMesh().
FSimpleIntrinsicEdgeFlipMesh() [2/3]
DYNAMICMESH_API UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::FSimpleIntrinsicEdgeFlipMesh (const FDynamicMesh3 & SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
References UE_API.
FSimpleIntrinsicEdgeFlipMesh() [3/3]
UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::FSimpleIntrinsicEdgeFlipMesh (const FSimpleIntrinsicEdgeFlipMesh &) delete
References FSimpleIntrinsicEdgeFlipMesh().
Member Function Documentation
AreSameOrientation()
bool UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::AreSameOrientation (int32 EID) const inline
Returns
false if the two triangles adjacent to the indicated edge have the different orientation (eg counter-clockwise and clockwise), otherwise return true. Note: by convention this will return true for boundary edges (or invalid edges).
Definition at line 324 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::Edge, IndexUtil::FindTriOrderedEdge(), GetEdge(), GetTriangle(), InvalidID, and IsEdge().
Clear()
DYNAMICMESH_API void UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Clear ()
Discard all data.
References UE_API.
ComputeTriInternalAnglesR()
DYNAMICMESH_API FVector3d UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::ComputeTriInternalAnglesR (const int32 TID) const protected
computes the angles based on the edge lengths, so must have valid EdgeLengths for this tri before calling.
the order of the angles matches the order of the vertices that define the triangle, e.g. if (a, b, c) = GetTriangle() the (angle at a, angle at b, angle at c) = ComputeTriInternalAnglesR
References UE_API.
EdgeCotanWeight()
DYNAMICMESH_API double UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeCotanWeight (int32 EID) const
return 1/2 (cot(alpha_{ij}) + cot(beta_{ij})) where alpha_{ij} and beta_{ij} are the to interior angles opposite the specified edge, EID.
Note: if EID is a mesh boundary, cot(alpha_ij) is returned
References UE_API.
Referenced by UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), and UE::MeshDeformation::ConstructIDTCotangentLaplacian().
EdgeCount()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeCount () const inline
Returns
number of edges in the intrinsic mesh
Definition at line 185 of file IntrinsicTriangulationMesh.h.
References EdgeRefCounts.
EdgeIndicesItr()
FRefCountVector::IndexEnumerable UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeIndicesItr () const inline
Returns
enumerable object for valid edge indices suitable for use with range-based for, ie for (int i : EdgeIndicesItr())
Definition at line 160 of file IntrinsicTriangulationMesh.h.
References EdgeRefCounts.
EdgeOpposingAngles()
DYNAMICMESH_API FVector2d UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeOpposingAngles (int32 EID) const
return FVector2(alpha_{ij} , beta_{ij}) where alpha_{ij} and beta_{ij} are the two interior angles opposite the specified edge, EID.
Expected angles are in the [0,2pi) range
Note: if EID is a mesh boundary beta_{ij} is replaced by -MAX_DOUBLE
References UE_API.
FlipEdge()
DYNAMICMESH_API EMeshResult UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::FlipEdge (int32 EID, FEdgeFlipInfo & EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
Note: After a successful flip, both triangles will share the same orientation (matching that of the pre-flip Edge.Tri.A) even if they had different orientations (e.g. cw & ccw) prior to flipping.
Parameters
EID indicates the edge to flip.
EdgeFlipInfo [out] populated on return.
Returns
a success or failure info.
References UE_API.
FlipEdgeTopology()
DYNAMICMESH_API EMeshResult UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::FlipEdgeTopology (int32 eab, FEdgeFlipInfo & FlipInfo) protected
update the mesh topology (e.g.
triangles and edges) by doing an edge flip, but does not update the intrinsic edge lengths or angles. Note: this requires precomputed FlipInfo.bHadSameOrientation.
References UE_API.
GetEdge()
FEdge UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdge (int32 EdgeID) const inline
Returns
specified edge
Definition at line 210 of file IntrinsicTriangulationMesh.h.
References checkSlow, Edges, and IsEdge().
Referenced by AreSameOrientation().
GetEdgeLength()
double UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeLength (int32 EID) const inline
Returns
the intrinsic edge length of specified edge
Definition at line 106 of file IntrinsicTriangulationMesh.h.
References checkSlow, EdgeLengths, and IsEdge().
Referenced by UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), and UE::MeshDeformation::ConstructIDTCotangentLaplacian().
GetEdgeLengthTriple()
FVector3d UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeLengthTriple (const FIndex3i & EIDs) const inline protected
Returns
three requested edge lengths
Definition at line 347 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::FIndex3i::A, UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, and EdgeLengths.
Referenced by GetTriEdgeLengths().
GetEdgeOpposingV()
DYNAMICMESH_API FIndex2i UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeOpposingV (int32 EID) const
Returns
the vertex pair opposite specified edge. The second vertex may be InvalidID
References UE_API.
GetEdgeT()
FIndex2i UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeT (int32 EdgeID) const inline
Returns
the triangle pair for an edge. The second triangle may be InvalidID
Definition at line 224 of file IntrinsicTriangulationMesh.h.
References checkSlow, Edges, and IsEdge().
GetEdgeV()
FIndex2i UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetEdgeV (int32 EdgeID) const inline
Returns
the vertex IDs that define the given edge in intrinsic mesh
Definition at line 217 of file IntrinsicTriangulationMesh.h.
References checkSlow, Edges, and IsEdge().
Referenced by UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), and UE::MeshDeformation::ConstructIDTCotangentLaplacian().
GetOpposingVerticesDistance()
DYNAMICMESH_API double UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetOpposingVerticesDistance (int32 EID) const protected
Returns
the intrinsic distance between the two vertices opposite the specified edge NB: Will fail if EID is a boundary edge.
References UE_API.
GetOrientedEdgeV()
DYNAMICMESH_API FIndex2i UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetOrientedEdgeV (int32 EID, int32 TID) const protected
Returns
vertex pair in specified edge, oriented by the given triangle.
note: the vertices may be the same. note: assumes EID is an edge in Triangle TID
References UE_API.
GetTriangle()
FIndex3i UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetTriangle (int32 TriangleID) const inline
Returns
vertex ids for the three corners of the triangle (e.g. a, b, c)
Definition at line 287 of file IntrinsicTriangulationMesh.h.
References checkSlow, IsTriangle(), and Triangles.
Referenced by AreSameOrientation().
GetTriangleRef()
const FIndex3i & UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetTriangleRef (int TriangleID) const inline
Returns
reference to vertex ids for the three corners of the triangle (e.g. a, b, c)
Definition at line 294 of file IntrinsicTriangulationMesh.h.
References checkSlow, IsTriangle(), and Triangles.
GetTriEdgeLengths()
FVector3d UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetTriEdgeLengths (const int32 TID) const inline
Returns
the intrinsic edge lengths for specified tri ordered to match the edges returned by ::GetEdges(TID)
Definition at line 116 of file IntrinsicTriangulationMesh.h.
References checkSlow, GetEdgeLengthTriple(), GetTriEdges(), and IsTriangle().
GetTriEdges()
FIndex3i UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetTriEdges (int32 TriangleID) const inline
Returns
edge ids for the three sides of the triangle (e.g. ab, bc, ca)
Definition at line 301 of file IntrinsicTriangulationMesh.h.
References checkSlow, IsTriangle(), and TriangleEdges.
Referenced by GetTriEdgeLengths().
GetTriInternalAngleR()
double UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetTriInternalAngleR (const int32 TID, const int32 IndexOf) const inline
Returns
the interior angle of specified triangle corner
Parameters
TID - ID of containing triangle
IndexOf - Index (i.e 0, 1, 2) of specified wedge of the triangle
Definition at line 128 of file IntrinsicTriangulationMesh.h.
References checkSlow, and InternalAngles.
GetVertex()
FVector3d UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetVertex (int32 VertexID) const inline
Returns
the r3 position of the specified vertex
Definition at line 256 of file IntrinsicTriangulationMesh.h.
References checkSlow, IsVertex(), and Vertices.
Referenced by UE::Geometry::FIntrinsicMesh::GetVertexPosition(), and UE::Geometry::FIntrinsicTriangulation::GetVertexPosition().
GetVtxEdgeCount()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::GetVtxEdgeCount (int32 VID) const inline
Returns
the valence of a vertex (the number of connected edges)
Definition at line 173 of file IntrinsicTriangulationMesh.h.
References VertexEdgeLists, and VertexRefCounts.
IsBoundaryEdge()
bool UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsBoundaryEdge (int32 EdgeID) const inline
Returns
true if specified edge is on the boundary of intrinsic mesh
Definition at line 203 of file IntrinsicTriangulationMesh.h.
References checkSlow, Edges, InvalidID, and IsEdge().
IsBoundaryVertex()
bool UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsBoundaryVertex (int32 VertexID) const inline
Returns
true if the specified vertex is adjacent to a boundary edge
Definition at line 240 of file IntrinsicTriangulationMesh.h.
References Edges, InvalidID, IsVertex(), and VertexEdgeLists.
IsEdge()
bool UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsEdge (int32 EdgeID) const inline
Returns
true if intrinsic mesh contains specified edge
Definition at line 197 of file IntrinsicTriangulationMesh.h.
References EdgeRefCounts.
Referenced by AreSameOrientation(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructIDTCotangentLaplacian(), GetEdge(), GetEdgeLength(), GetEdgeT(), GetEdgeV(), and IsBoundaryEdge().
IsTriangle()
bool UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsTriangle (int32 TriangleID) const inline
Returns
true if intrinsic mesh contains specified triangle
Definition at line 281 of file IntrinsicTriangulationMesh.h.
References TriangleRefCounts.
Referenced by GetTriangle(), GetTriangleRef(), GetTriEdgeLengths(), and GetTriEdges().
IsVertex()
bool UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsVertex (int32 VertexID) const inline
Returns
true if intrinsic mesh contains specified vertex
Definition at line 234 of file IntrinsicTriangulationMesh.h.
References VertexRefCounts.
Referenced by GetVertex(), UE::Geometry::FIntrinsicTriangulation::GetVertexSurfacePoint(), IsBoundaryVertex(), and UE::Geometry::FIntrinsicEdgeFlipMesh::IsSurfaceVertex().
MaxEdgeID()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::MaxEdgeID () const inline
Returns
upper bound on the edge ID used in the mesh. i.e. all edge IDs < MaxEdgeID
Definition at line 191 of file IntrinsicTriangulationMesh.h.
References EdgeRefCounts.
Referenced by UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), and UE::MeshDeformation::ConstructIDTCotangentLaplacian().
MaxTriangleID()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::MaxTriangleID () const inline
Returns
upper bound on the triangle ID used in the mesh. i.e. all triangle IDs < MaxTriangleID
Definition at line 269 of file IntrinsicTriangulationMesh.h.
References TriangleRefCounts.
MaxVertexID()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::MaxVertexID () const inline
Returns
upper bound on the vertex ID used in the mesh. i.e. all edge IDs < MaxVertexID
Definition at line 263 of file IntrinsicTriangulationMesh.h.
References VertexRefCounts.
Permute()
template<typename Vector3Type> Vector3Type UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Permute (int32 Index, const Vector3Type & Src) const inline
cyclic permutation of the src vector such that the 'Index' entry in the src is the first entry in the result NB: Index must be 0, 1, or 2.
Definition at line 312 of file IntrinsicTriangulationMesh.h.
References AddOneModThree, AddTwoModThree, and checkSlow.
ReplaceEdgeTriangle()
DYNAMICMESH_API int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::ReplaceEdgeTriangle (int32 eID, int32 tOld, int32 tNew) protected
replace tOld with tNew in an existing edge
References UE_API.
ReplaceTriangleEdge()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::ReplaceTriangleEdge (int32 tID, int32 eOld, int32 eNew) inline protected
replace eOld with eNew in and existing triangle
Definition at line 394 of file IntrinsicTriangulationMesh.h.
References TriangleEdges.
Reset()
DYNAMICMESH_API void UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Reset (const FDynamicMesh3 & SrcMesh)
Reset the mesh to an ID-matching deep copy the basic mesh topology (but no attributes or groups)
References UE_API.
SetEdgeTrianglesInternal()
void UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::SetEdgeTrianglesInternal (int32 EdgeID, int32 t0, int32 t1) inline protected
update the existing edge to reference triangles t0 and t1
Definition at line 386 of file IntrinsicTriangulationMesh.h.
References Edges.
SetEdgeVerticesInternal()
void UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::SetEdgeVerticesInternal (int32 EdgeID, int32 a, int32 b) inline protected
update the existing edge to reference vertices 'a' and 'b'.
Definition at line 376 of file IntrinsicTriangulationMesh.h.
References Edges, and Swap.
TriangleCount()
int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::TriangleCount () const inline
Returns
number of triangles in the intrinsic mesh
Definition at line 179 of file IntrinsicTriangulationMesh.h.
References TriangleRefCounts.
TriangleIndicesItr()
FRefCountVector::IndexEnumerable UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::TriangleIndicesItr () const inline
Returns
enumerable object for valid triangle indices suitable for use with range-based for, ie for (int i : TriangleIndicesItr())
Definition at line 275 of file IntrinsicTriangulationMesh.h.
References TriangleRefCounts.
VtxEdgesItr()
FSmallListSet::ValueEnumerable UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VtxEdgesItr (int32 VID) const inline
Returns
enumerable object for one-ring edges of a vertex, suitable for use with range-based for, ie for (int i : VtxEdgesItr(VertexID))
Definition at line 166 of file IntrinsicTriangulationMesh.h.
References checkSlow, VertexEdgeLists, and VertexRefCounts.
Referenced by UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), and UE::MeshDeformation::ConstructIDTCotangentLaplacian().
Field Documentation
AddOneModThree
const int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::AddOneModThree[3] = { 1, 2, 0 } protected
Definition at line 416 of file IntrinsicTriangulationMesh.h.
Referenced by Permute().
AddTwoModThree
const int32 UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::AddTwoModThree[3] = { 2, 0, 1 } protected
Definition at line 417 of file IntrinsicTriangulationMesh.h.
Referenced by Permute().
EdgeLengths
TDynamicVector<double> UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeLengths protected
Definition at line 436 of file IntrinsicTriangulationMesh.h.
Referenced by GetEdgeLength(), and GetEdgeLengthTriple().
EdgeRefCounts
FRefCountVector UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::EdgeRefCounts {} protected
Definition at line 430 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AddEdgeInternal(), EdgeCount(), EdgeIndicesItr(), IsEdge(), and MaxEdgeID().
Edges
TDynamicVector<FEdge> UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Edges protected
Definition at line 429 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AddEdgeInternal(), GetEdge(), GetEdgeT(), GetEdgeV(), IsBoundaryEdge(), IsBoundaryVertex(), SetEdgeTrianglesInternal(), and SetEdgeVerticesInternal().
InternalAngles
TDynamicVector<FVector3d> UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::InternalAngles protected
Definition at line 437 of file IntrinsicTriangulationMesh.h.
Referenced by GetTriInternalAngleR().
InvalidID
int UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::InvalidID = IndexConstants::InvalidID static constexpr
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Definition at line 78 of file IntrinsicTriangulationMesh.h.
Referenced by AreSameOrientation(), IsBoundaryEdge(), and IsBoundaryVertex().
TriangleEdges
TDynamicVector<FIndex3i> UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::TriangleEdges protected
Definition at line 427 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AddTriangleInternal(), GetTriEdges(), and ReplaceTriangleEdge().
TriangleRefCounts
FRefCountVector UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::TriangleRefCounts {} protected
Definition at line 426 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AddTriangleInternal(), IsTriangle(), MaxTriangleID(), TriangleCount(), and TriangleIndicesItr().
Triangles
TDynamicVector<FIndex3i> UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Triangles protected
Definition at line 425 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AddTriangleInternal(), GetTriangle(), and GetTriangleRef().
VertexEdgeLists
FSmallListSet UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VertexEdgeLists protected
Definition at line 423 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AddEdgeInternal(), UE::Geometry::FSimpleIntrinsicMesh::AllocateEdgesList(), GetVtxEdgeCount(), IsBoundaryVertex(), and VtxEdgesItr().
VertexRefCounts
FRefCountVector UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::VertexRefCounts {} protected
Definition at line 422 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AppendVertex(), GetVtxEdgeCount(), IsVertex(), MaxVertexID(), and VtxEdgesItr().
Vertices
TDynamicVector<FVector3d> UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::Vertices {} protected
Definition at line 421 of file IntrinsicTriangulationMesh.h.
Referenced by UE::Geometry::FSimpleIntrinsicMesh::AppendVertex(), and GetVertex().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/IntrinsicTriangulationMesh.h