Unreal Engine 5.6 C++ API: FUObjectAnnotationSparse< TAnnotation, bAutoRemove > Class Template Reference
FUObjectAnnotationSparse< TAnnotation, bAutoRemove > Class Template Reference
FUObjectAnnotationSparse is a helper class that is used to store sparse, slow, temporary, editor only, external or other low priority information about UObjects.
#include "UObjectAnnotation.h"
Public Member Functions
FUObjectAnnotationSparse ()
Constructor, initializes to nothing.
virtual ~FUObjectAnnotationSparse ()
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
void AddAnnotation (const UObjectBase *Object, const TAnnotation &Annotation)
void AddAnnotation (const UObjectBase *Object, TAnnotation &&Annotation)
Add an annotation to the annotation list.
virtual SIZE_T GetAllocatedSize () const override
Returns the size of heap memory allocated internally by this listener.
TAnnotation GetAndRemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list and returns the annotation if it had one.
FORCEINLINE TAnnotation GetAnnotation (const UObjectBase *Object)
Return the annotation associated with a uobject.
const TMap< const UObjectBase *, TAnnotation > & GetAnnotationMap () const
Return the annotation map.
virtual void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index) override
Interface for FUObjectAllocator::FUObjectDeleteListener.
virtual void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list.
void Reserve (int32 ExpectedNumElements)
Reserves memory for the annotation map for the specified number of elements, used to avoid reallocations.
Public Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Protected Attributes
FTransactionallySafeRWLock AnnotationCacheCritical
const UObjectBase * AnnotationCacheKey = nullptr
Key for a one-item cache of the last lookup into AnnotationMap.
TAnnotation AnnotationCacheValue
Value for a one-item cache of the last lookup into AnnotationMap.
TMap< const UObjectBase *, TAnnotation > AnnotationMap
Map from live objects to an annotation.
FTransactionallySafeRWLock AnnotationMapCritical
Guards the annotation map, cache key and cache value.
Private Member Functions
template<typename T>
void AddAnnotationInternal (const UObjectBase *Object, T &&Annotation)
void MaybeRegisterAutoRTFMHandlers ()
void SetAnnotationCacheKeyAndValue (const UObjectBase *Key, const TAnnotation &Value)
void SetAnnotationCacheKeyAndValue (const UObjectBase *Key, TAnnotation &&Value)
Detailed Description
template<typename TAnnotation, bool bAutoRemove>
class FUObjectAnnotationSparse< TAnnotation, bAutoRemove >
FUObjectAnnotationSparse is a helper class that is used to store sparse, slow, temporary, editor only, external or other low priority information about UObjects.
There is a notion of a default annotation and UObjects default to this annotation and this takes no storage.
Annotations are automatically cleaned up when UObjects are destroyed. Annotation are not "garbage collection aware", so it isn't safe to store pointers to other UObjects in an annotation unless external guarantees are made such that destruction of the other object removes the annotation.
Parameters
TAnnotation type of the annotation
bAutoRemove if true, annotation will automatically be removed, otherwise in non-final builds it will verify that the annotation was removed by other means prior to destruction.
Definition at line 31 of file UObjectAnnotation.h.
Constructor & Destructor Documentation
FUObjectAnnotationSparse()
template<typename TAnnotation, bool bAutoRemove> FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::FUObjectAnnotationSparse () inline
Constructor, initializes to nothing.
Definition at line 66 of file UObjectAnnotation.h.
References AnnotationCacheValue, and check.
~FUObjectAnnotationSparse()
template<typename TAnnotation, bool bAutoRemove> virtual FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::~FUObjectAnnotationSparse () inline virtual
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
Definition at line 75 of file UObjectAnnotation.h.
References checkSlow, and RemoveAllAnnotations().
Member Function Documentation
AddAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotation (const UObjectBase * Object, const TAnnotation & Annotation) inline
Definition at line 133 of file UObjectAnnotation.h.
References AddAnnotationInternal(), and Object.
AddAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotation (const UObjectBase * Object, TAnnotation && Annotation) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Object Object to annotate.
Annotation Annotation to associate with Object.
Definition at line 128 of file UObjectAnnotation.h.
References AddAnnotationInternal(), MoveTemp(), and Object.
Referenced by FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotationInternal().
AddAnnotationInternal()
template<typename TAnnotation, bool bAutoRemove> template<typename T> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotationInternal (const UObjectBase * Object, T && Annotation) inline private
Definition at line 92 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, check, Forward(), GUObjectArray, MoveTemp(), Object, RemoveAnnotation(), SetAnnotationCacheKeyAndValue(), and SLT_Write.
Referenced by AddAnnotation(), and AddAnnotation().
GetAllocatedSize()
template<typename TAnnotation, bool bAutoRemove> virtual SIZE_T FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAllocatedSize () const inline override virtual
Returns the size of heap memory allocated internally by this listener.
Reimplemented from FUObjectArray::FUObjectDeleteListener.
Reimplemented in FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >.
Definition at line 283 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, and SLT_ReadOnly.
Referenced by FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::GetAllocatedSize().
GetAndRemoveAnnotation()
template<typename TAnnotation, bool bAutoRemove> TAnnotation FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAndRemoveAnnotation (const UObjectBase * Object) inline
Removes an annotation from the annotation list and returns the annotation if it had one.
Parameters
Object Object to de-annotate.
Returns
Old annotation
Definition at line 143 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, check, GUObjectArray, Object, SetAnnotationCacheKeyAndValue(), and SLT_Write.
Referenced by FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::RemoveAnnotation().
GetAnnotation()
template<typename TAnnotation, bool bAutoRemove> FORCEINLINE TAnnotation FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAnnotation (const UObjectBase * Object) inline
Return the annotation associated with a uobject.
Parameters
Object Object to return the annotation for
Definition at line 234 of file UObjectAnnotation.h.
References AnnotationCacheKey, AnnotationCacheValue, AnnotationMap, AnnotationMapCritical, check, FORCEINLINE, Object, SetAnnotationCacheKeyAndValue(), and SLT_ReadOnly.
Referenced by FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotationInternal().
GetAnnotationMap()
template<typename TAnnotation, bool bAutoRemove> const TMap< const UObjectBase *, TAnnotation > & FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAnnotationMap () const inline
Return the annotation map.
Caution, this is for low level use
Returns
A mapping from UObjectBase to annotation for non-default annotations
Definition at line 269 of file UObjectAnnotation.h.
References AnnotationMap.
MaybeRegisterAutoRTFMHandlers()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::MaybeRegisterAutoRTFMHandlers () inline private
Definition at line 322 of file UObjectAnnotation.h.
References AnnotationCacheKey, and checkSlow.
Referenced by SetAnnotationCacheKeyAndValue(), and SetAnnotationCacheKeyAndValue().
NotifyUObjectDeleted()
template<typename TAnnotation, bool bAutoRemove> virtual void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::NotifyUObjectDeleted (const UObjectBase * Object, int32 Index) inline override virtual
Interface for FUObjectAllocator::FUObjectDeleteListener.
Parameters
Object object that has been destroyed
Index index of object that is being deleted
Reimplemented in FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >.
Definition at line 41 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, check, Object, RemoveAnnotation(), and SLT_ReadOnly.
OnUObjectArrayShutdown()
template<typename TAnnotation, bool bAutoRemove> virtual void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::OnUObjectArrayShutdown () inline override virtual
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
Implements FUObjectArray::FUObjectDeleteListener.
Reimplemented in FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >.
Definition at line 57 of file UObjectAnnotation.h.
References GUObjectArray, and RemoveAllAnnotations().
RemoveAllAnnotations()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::RemoveAllAnnotations () inline
Removes all annotation from the annotation list.
Definition at line 206 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, GUObjectArray, SetAnnotationCacheKeyAndValue(), and SLT_Write.
Referenced by ~FUObjectAnnotationSparse(), OnUObjectArrayShutdown(), and FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::RemoveAllAnnotations().
RemoveAnnotation()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::RemoveAnnotation (const UObjectBase * Object) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 177 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, check, GUObjectArray, Object, SetAnnotationCacheKeyAndValue(), and SLT_Write.
Referenced by AddAnnotationInternal(), and NotifyUObjectDeleted().
Reserve()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::Reserve (int32 ExpectedNumElements) inline
Reserves memory for the annotation map for the specified number of elements, used to avoid reallocations.
Definition at line 277 of file UObjectAnnotation.h.
References AnnotationMap, AnnotationMapCritical, and SLT_Write.
Referenced by FUObjectAnnotationSparseBool::Reserve().
SetAnnotationCacheKeyAndValue() [1/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::SetAnnotationCacheKeyAndValue (const UObjectBase * Key, const TAnnotation & Value) inline private
Definition at line 295 of file UObjectAnnotation.h.
References AnnotationCacheCritical, AnnotationCacheKey, AnnotationCacheValue, Key, MaybeRegisterAutoRTFMHandlers(), SLT_Write, and Value.
Referenced by AddAnnotationInternal(), GetAndRemoveAnnotation(), GetAnnotation(), RemoveAllAnnotations(), and RemoveAnnotation().
SetAnnotationCacheKeyAndValue() [2/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::SetAnnotationCacheKeyAndValue (const UObjectBase * Key, TAnnotation && Value) inline private
Definition at line 309 of file UObjectAnnotation.h.
References AnnotationCacheKey, AnnotationCacheValue, Key, MaybeRegisterAutoRTFMHandlers(), MoveTemp(), and Value.
Field Documentation
AnnotationCacheCritical
template<typename TAnnotation, bool bAutoRemove> FTransactionallySafeRWLock FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AnnotationCacheCritical mutable protected
Definition at line 353 of file UObjectAnnotation.h.
Referenced by SetAnnotationCacheKeyAndValue().
AnnotationCacheKey
template<typename TAnnotation, bool bAutoRemove> const UObjectBase* FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AnnotationCacheKey = nullptr protected
Key for a one-item cache of the last lookup into AnnotationMap.
Guarded by AnnotationCacheCritical. Annotation are often called back-to-back so this is a performance optimization for that.
Definition at line 364 of file UObjectAnnotation.h.
Referenced by GetAnnotation(), MaybeRegisterAutoRTFMHandlers(), SetAnnotationCacheKeyAndValue(), and SetAnnotationCacheKeyAndValue().
AnnotationCacheValue
template<typename TAnnotation, bool bAutoRemove> TAnnotation FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AnnotationCacheValue protected
Value for a one-item cache of the last lookup into AnnotationMap.
Guarded by AnnotationCacheCritical.
Definition at line 369 of file UObjectAnnotation.h.
Referenced by FUObjectAnnotationSparse(), GetAnnotation(), SetAnnotationCacheKeyAndValue(), and SetAnnotationCacheKeyAndValue().
AnnotationMap
template<typename TAnnotation, bool bAutoRemove> TMap<const UObjectBase *, TAnnotation> FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AnnotationMap protected
Map from live objects to an annotation.
Guarded by AnnotationMapCritical.
Definition at line 358 of file UObjectAnnotation.h.
Referenced by AddAnnotationInternal(), GetAllocatedSize(), GetAndRemoveAnnotation(), GetAnnotation(), GetAnnotationMap(), NotifyUObjectDeleted(), RemoveAllAnnotations(), RemoveAnnotation(), and Reserve().
AnnotationMapCritical
template<typename TAnnotation, bool bAutoRemove> FTransactionallySafeRWLock FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AnnotationMapCritical mutable protected
Guards the annotation map, cache key and cache value.
Definition at line 352 of file UObjectAnnotation.h.
Referenced by AddAnnotationInternal(), GetAllocatedSize(), GetAndRemoveAnnotation(), GetAnnotation(), NotifyUObjectDeleted(), RemoveAllAnnotations(), RemoveAnnotation(), and Reserve().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectAnnotation.h