Unreal Engine 5.6 C++ API: Metasound::TArraySetOperator< ArrayType > Class Template Reference
Metasound::TArraySetOperator< ArrayType > Class Template Reference
TArraySetOperator sets an element in an array to a specific value.
#include "MetasoundArrayNodes.h"
Data Structures
struct FInitParams
Public Types
using ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
using FArrayDataReadReference = TDataReadReference<ArrayType>
using FArrayDataWriteReference = TDataWriteReference<ArrayType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArraySetOperator (const FOperatorSettings &InSettings, FInitParams &&InParams)
virtual ~TArraySetOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
virtual FDataReferenceCollection GetInputs () const override
virtual FDataReferenceCollection GetOutputs () const override
void Reset (const IOperator::FResetParams &Inparams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArraySetOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Attributes
FArrayDataWriteReference Array
FString GraphName
TDataReadReference< int32 > Index
FArrayDataReadReference InitArray
FOperatorSettings OperatorSettings
TDataReadReference< FTrigger > Trigger
TDataReadReference< ElementType > Value
Detailed Description
template<typename ArrayType>
class Metasound::TArraySetOperator< ArrayType >
TArraySetOperator sets an element in an array to a specific value.
Definition at line 387 of file MetasoundArrayNodes.h.
Member Typedef Documentation
ElementType
template<typename ArrayType> using Metasound::TArraySetOperator< ArrayType >::ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
Definition at line 392 of file MetasoundArrayNodes.h.
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArraySetOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 390 of file MetasoundArrayNodes.h.
FArrayDataWriteReference
template<typename ArrayType> using Metasound::TArraySetOperator< ArrayType >::FArrayDataWriteReference = TDataWriteReference<ArrayType>
Definition at line 391 of file MetasoundArrayNodes.h.
Constructor & Destructor Documentation
TArraySetOperator()
template<typename ArrayType> Metasound::TArraySetOperator< ArrayType >::TArraySetOperator (const FOperatorSettings & InSettings, FInitParams && InParams) inline
Definition at line 480 of file MetasoundArrayNodes.h.
References Array, GraphName, Index, InitArray, OperatorSettings, Trigger, Value, and WITH_METASOUND_DEBUG_ENVIRONMENT.
~TArraySetOperator()
template<typename ArrayType> virtual Metasound::TArraySetOperator< ArrayType >::~TArraySetOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArraySetOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 507 of file MetasoundArrayNodes.h.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), Index, InitArray, METASOUND_GET_PARAM_NAME, Trigger, and Value.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArraySetOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 517 of file MetasoundArrayNodes.h.
References Array, Metasound::FOutputVertexInterfaceData::BindReadVertex(), and METASOUND_GET_PARAM_NAME.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArraySetOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 442 of file MetasoundArrayNodes.h.
References Array, Metasound::FMetasoundEnvironment::Contains(), Metasound::TDataFactory< DataType, TDataWriteReference< DataType > >::CreateExplicitArgs(), Metasound::FBuildOperatorParams::Environment, Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FMetasoundEnvironment::GetValue(), Metasound::Frontend::SourceInterface::Environment::GraphName, GraphName, Index, InitArray, Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, MoveTemp(), Metasound::FBuildOperatorParams::OperatorSettings, Trigger, and Value.
Execute()
template<typename ArrayType> void Metasound::TArraySetOperator< ArrayType >::Execute () inline
Definition at line 524 of file MetasoundArrayNodes.h.
References Array, GraphName, Index, TEXT, Trigger, UE_LOG, Value, and Warning.
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArraySetOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 394 of file MetasoundArrayNodes.h.
References METASOUND_GET_PARAM_NAME_AND_METADATA.
Referenced by GetNodeInfo().
GetInputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArraySetOperator< ArrayType >::GetInputs () const inline override virtual
Definition at line 495 of file MetasoundArrayNodes.h.
References checkNoEntry.
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArraySetOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 412 of file MetasoundArrayNodes.h.
References Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metadata, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, and TEXT.
GetOutputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArraySetOperator< ArrayType >::GetOutputs () const inline override virtual
Definition at line 501 of file MetasoundArrayNodes.h.
References checkNoEntry.
Reset()
template<typename ArrayType> void Metasound::TArraySetOperator< ArrayType >::Reset (const IOperator::FResetParams & Inparams) inline
Definition at line 544 of file MetasoundArrayNodes.h.
References Array, and InitArray.
Field Documentation
Array
template<typename ArrayType> FArrayDataWriteReference Metasound::TArraySetOperator< ArrayType >::Array private
Definition at line 554 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator(), BindOutputs(), CreateOperator(), Execute(), and Reset().
GraphName
template<typename ArrayType> FString Metasound::TArraySetOperator< ArrayType >::GraphName private
Definition at line 559 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator(), CreateOperator(), and Execute().
Index
template<typename ArrayType> TDataReadReference<int32> Metasound::TArraySetOperator< ArrayType >::Index private
Definition at line 555 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator(), BindInputs(), CreateOperator(), and Execute().
InitArray
template<typename ArrayType> FArrayDataReadReference Metasound::TArraySetOperator< ArrayType >::InitArray private
Definition at line 553 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator(), BindInputs(), CreateOperator(), and Reset().
OperatorSettings
template<typename ArrayType> FOperatorSettings Metasound::TArraySetOperator< ArrayType >::OperatorSettings private
Definition at line 550 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator().
Trigger
template<typename ArrayType> TDataReadReference<FTrigger> Metasound::TArraySetOperator< ArrayType >::Trigger private
Definition at line 552 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator(), BindInputs(), CreateOperator(), and Execute().
Value
template<typename ArrayType> TDataReadReference<ElementType> Metasound::TArraySetOperator< ArrayType >::Value private
Definition at line 556 of file MetasoundArrayNodes.h.
Referenced by TArraySetOperator(), BindInputs(), CreateOperator(), and Execute().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundArrayNodes.h