Unreal Engine 5.6 C++ API: FTabManager::FArea Class Reference
FTabManager::FArea Class Reference
#include "TabManager.h"
Public Types
enum EWindowPlacement { Placement_NoWindow , Placement_Automatic , Placement_Specified }
An enum which specifies how content appears within a window.
Public Member Functions
virtual ~FArea ()
virtual TSharedPtr< FArea > AsArea () override
bool DefinesPositionallySpecifiedFloatingWindow () const
Returns true if this FArea defines a positionally specified window, else it returns false.
FName GetExtensionId () const
TSharedRef< FArea > SetExtensionId (FName InExtensionId)
TSharedRef< FArea > SetOrientation (const EOrientation InOrientation)
TSharedRef< FArea > SetWindow (FVector2D InPosition, bool IsMaximized)
TSharedRef< FArea > Split (TSharedRef< FLayoutNode > InNode)
TSharedRef< FArea > SplitAt (int32 Index, TSharedRef< FLayoutNode > InNode)
Public Member Functions inherited from FTabManager::FSplitter
virtual ~FSplitter ()
virtual TSharedPtr< FSplitter > AsSplitter () override
EOrientation GetOrientation () const
TSharedRef< FSplitter > InsertAfter (TSharedRef< FLayoutNode > NodeToInsertAfter, TSharedRef< FLayoutNode > NodeToInsert)
TSharedRef< FSplitter > InsertBefore (TSharedRef< FLayoutNode > NodeToInsertBefore, TSharedRef< FLayoutNode > NodeToInsert)
TSharedRef< FSplitter > SetOrientation (const EOrientation InOrientation)
TSharedRef< FSplitter > SetSizeCoefficient (const float InSizeCoefficient)
TSharedRef< FSplitter > Split (TSharedRef< FLayoutNode > InNode)
Public Member Functions inherited from FTabManager::FLayoutNode
virtual ~FLayoutNode ()
virtual TSharedPtr< FStack > AsStack ()
float GetSizeCoefficient () const
Public Member Functions inherited from TSharedFromThis< FLayoutNode >
TSharedRef< FLayoutNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FLayoutNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
FArea (const float InWidth, const float InHeight)
Protected Member Functions inherited from FTabManager::FSplitter
FSplitter ()
Protected Member Functions inherited from FTabManager::FLayoutNode
FLayoutNode ()
Protected Member Functions inherited from TSharedFromThis< FLayoutNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bIsMaximized
FName ExtensionId
FVector2D UnscaledWindowPosition
FVector2D UnscaledWindowSize
EWindowPlacement WindowPlacement
Protected Attributes inherited from FTabManager::FSplitter
TArray< TSharedRef< FLayoutNode > > ChildNodes
EOrientation Orientation
Protected Attributes inherited from FTabManager::FLayoutNode
float SizeCoefficient
Friends
class FTabManager
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FLayoutNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 619 of file TabManager.h.
Member Enumeration Documentation
EWindowPlacement
enum FTabManager::FArea::EWindowPlacement
An enum which specifies how content appears within a window.
Enumerator
Placement_NoWindow
The content is docked within a primary window.
Placement_Automatic
The content is docked within a floating window that is initially automatically positioned.
Placement_Specified
The content is docked within a floating window with positioning specified by an FArea.
Definition at line 625 of file TabManager.h.
Constructor & Destructor Documentation
~FArea()
virtual FTabManager::FArea::~FArea () inline virtual
Definition at line 680 of file TabManager.h.
FArea()
FTabManager::FArea::FArea (const float InWidth, const float InHeight) inline protected
Definition at line 693 of file TabManager.h.
References bIsMaximized, Placement_Automatic, UnscaledWindowPosition, UnscaledWindowSize, and WindowPlacement.
Member Function Documentation
AsArea()
virtual TSharedPtr< FArea > FTabManager::FArea::AsArea () inline override virtual
Reimplemented from FTabManager::FLayoutNode.
Definition at line 675 of file TabManager.h.
References TSharedFromThis< FTabManager >::SharedThis().
DefinesPositionallySpecifiedFloatingWindow()
bool FTabManager::FArea::DefinesPositionallySpecifiedFloatingWindow () const inline
Returns true if this FArea defines a positionally specified window, else it returns false.
Definition at line 687 of file TabManager.h.
References Placement_Specified, and WindowPlacement.
GetExtensionId()
FName FTabManager::FArea::GetExtensionId () const inline
Definition at line 670 of file TabManager.h.
References ExtensionId.
SetExtensionId()
TSharedRef< FArea > FTabManager::FArea::SetExtensionId (FName InExtensionId) inline
Definition at line 664 of file TabManager.h.
References ExtensionId, and TSharedFromThis< FTabManager >::SharedThis().
SetOrientation()
TSharedRef< FArea > FTabManager::FArea::SetOrientation (const EOrientation InOrientation) inline
Definition at line 650 of file TabManager.h.
References FTabManager::FSplitter::Orientation, and TSharedFromThis< FTabManager >::SharedThis().
SetWindow()
TSharedRef< FArea > FTabManager::FArea::SetWindow (FVector2D InPosition, bool IsMaximized) inline
Definition at line 656 of file TabManager.h.
References bIsMaximized, Placement_Specified, TSharedFromThis< FTabManager >::SharedThis(), UnscaledWindowPosition, and WindowPlacement.
Split()
TSharedRef< FArea > FTabManager::FArea::Split (TSharedRef< FLayoutNode > InNode) inline
Definition at line 637 of file TabManager.h.
References FTabManager::FSplitter::ChildNodes, and TSharedFromThis< FTabManager >::SharedThis().
SplitAt()
TSharedRef< FArea > FTabManager::FArea::SplitAt (int32 Index, TSharedRef< FLayoutNode > InNode) inline
Definition at line 643 of file TabManager.h.
References check, FTabManager::FSplitter::ChildNodes, FMath::Min, and TSharedFromThis< FTabManager >::SharedThis().
Friends And Related Symbol Documentation
FTabManager
friend class FTabManager friend
Definition at line 621 of file TabManager.h.
References FTabManager.
Referenced by FTabManager.
Field Documentation
bIsMaximized
bool FTabManager::FArea::bIsMaximized protected
Definition at line 704 of file TabManager.h.
Referenced by FArea(), and SetWindow().
ExtensionId
FName FTabManager::FArea::ExtensionId protected
Definition at line 705 of file TabManager.h.
Referenced by GetExtensionId(), and SetExtensionId().
UnscaledWindowPosition
FVector2D FTabManager::FArea::UnscaledWindowPosition protected
Definition at line 702 of file TabManager.h.
Referenced by FArea(), and SetWindow().
UnscaledWindowSize
FVector2D FTabManager::FArea::UnscaledWindowSize protected
Definition at line 703 of file TabManager.h.
Referenced by FArea().
WindowPlacement
EWindowPlacement FTabManager::FArea::WindowPlacement protected
Definition at line 701 of file TabManager.h.
Referenced by FArea(), DefinesPositionallySpecifiedFloatingWindow(), and SetWindow().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Docking/TabManager.h