Unreal Engine 5.6 C++ API: UE::Geometry::FMeshSceneAdapter Class Reference
UE::Geometry::FMeshSceneAdapter Class Reference
FMeshSceneAdapter creates an internal representation of an Actor/Component/Asset hierarchy, so that a minimal set of Mesh data structures can be constructed for the unique Meshes (generally Assets).
#include "MeshSceneAdapter.h"
Data Structures
struct FSpatialCacheInfo
struct FSpatialWrapperInfo
struct FStatistics
Statistics about the Mesh Scene returned by GetGeometryStatistics()
Public Member Functions
FMeshSceneAdapter ()
FMeshSceneAdapter (const FMeshSceneAdapter &)=delete
FMeshSceneAdapter (FMeshSceneAdapter &&)=delete
virtual ~FMeshSceneAdapter ()
MODELINGCOMPONENTS_API void AddActors (const TArray< AActor * > &ActorsSetIn)
Add the given Actors to the Mesh Scene.
MODELINGCOMPONENTS_API void AddComponents (const TArray< UActorComponent * > &ComponentSetIn)
Add the given Components to the Mesh Scene.
MODELINGCOMPONENTS_API void Build (const FMeshSceneAdapterBuildOptions &BuildOptions)
Build the Mesh Scene.
virtual MODELINGCOMPONENTS_API void BuildSpatialEvaluationCache ()
Precompute data structures that accelerate spatial evaluation queries.
virtual MODELINGCOMPONENTS_API void CollectMeshSeedPoints (TArray< FVector3d > &PointsOut)
MODELINGCOMPONENTS_API void FastUpdateTransforms (bool bRebuildSpatialCache)
Update the transforms on all the Components in the current Mesh Scene.
virtual MODELINGCOMPONENTS_API double FastWindingNumber (const FVector3d &WorldPoint, bool bFastEarlyOutIfPossible=true)
virtual MODELINGCOMPONENTS_API bool FindNearestRayIntersection (const FRay3d &WorldRay, FMeshSceneRayHit &HitResultOut)
Intersect the given Ray with the MeshScene and find the nearest mesh hit.
MODELINGCOMPONENTS_API void GenerateBaseClosingMesh (double BaseHeight=1.0, double ExtrudeHeight=0.0)
Generate a new mesh that "caps" the mesh scene on the bottom.
virtual MODELINGCOMPONENTS_API void GetAccumulatedMesh (FDynamicMesh3 &AccumMesh)
Append all instance triangles to a single mesh.
virtual MODELINGCOMPONENTS_API FAxisAlignedBox3d GetBoundingBox ()
virtual MODELINGCOMPONENTS_API void GetGeometryStatistics (FStatistics &StatsOut)
virtual MODELINGCOMPONENTS_API FAxisAlignedBox3d GetMeshBoundingBox (UActorComponent *Component, int32 ComponentIndex=-1)
virtual MODELINGCOMPONENTS_API void GetMeshBoundingBoxes (TArray< FAxisAlignedBox3d > &Bounds)
Get all world-space bounding boxes for all Scene Meshes.
MODELINGCOMPONENTS_API bool IsValid () const
Whether valid actors/components were added to the scene representation.
virtual MODELINGCOMPONENTS_API void ParallelMeshVertexEnumeration (TFunctionRef< bool(int32 NumMeshes)> InitializeFunc, TFunctionRef< bool(int32 MeshIndex, AActor *SourceActor, const FActorChildMesh *ChildMeshInfo, const FAxisAlignedBox3d &WorldBounds)> MeshFilterFunc, TFunctionRef< bool(int32 MeshIndex, AActor *SourceActor, const FActorChildMesh *ChildMeshInfo, const FVector3d &WorldPos)> PerVertexFunc, bool bForceSingleThreaded=false)
Run a custom query across all world-transformed scene mesh vertices.
virtual MODELINGCOMPONENTS_API void ProcessActorChildMeshes (TFunctionRef< void(const FActorAdapter *ActorAdapter, const FActorChildMesh *ChildMesh)> ProcessFunc)
Run a custom query across all scene actor child meshes.
Protected Member Functions
MODELINGCOMPONENTS_API void Build_FullDecompose (const FMeshSceneAdapterBuildOptions &BuildOptions)
MODELINGCOMPONENTS_API void InitializeSpatialWrappers (const TArray< FActorAdapter * > &NewItemsToProcess)
MODELINGCOMPONENTS_API void UpdateActorBounds (FActorAdapter &Actor)
Protected Attributes
bool bHaveSpatialEvaluationCache = false
bool bSceneIsAllSolids = false
FAxisAlignedBox3d CachedWorldBounds
TSharedPtr< FSparseDynamicOctree3 > Octree
TArray< TUniquePtr< FActorAdapter > > SceneActors
TArray< FSpatialCacheInfo > SortedSpatials
TMap< void *, TSharedPtr< FSpatialWrapperInfo > > SpatialAdapters
Detailed Description
FMeshSceneAdapter creates an internal representation of an Actor/Component/Asset hierarchy, so that a minimal set of Mesh data structures can be constructed for the unique Meshes (generally Assets).
This allows queries against the Actor set to be computed without requiring mesh copies or duplicates of the mesh data structures (ie, saving memory, at the cost of some computation overhead).
Currently this builds an AABBTree and FastWindingTree for each unique Mesh, and supports various queries based on those data structures.
Definition at line 268 of file MeshSceneAdapter.h.
Constructor & Destructor Documentation
~FMeshSceneAdapter()
virtual UE::Geometry::FMeshSceneAdapter::~FMeshSceneAdapter () inline virtual
Definition at line 271 of file MeshSceneAdapter.h.
FMeshSceneAdapter() [1/3]
UE::Geometry::FMeshSceneAdapter::FMeshSceneAdapter () inline
Definition at line 273 of file MeshSceneAdapter.h.
Referenced by FMeshSceneAdapter(), and FMeshSceneAdapter().
FMeshSceneAdapter() [2/3]
UE::Geometry::FMeshSceneAdapter::FMeshSceneAdapter (const FMeshSceneAdapter &) delete
References FMeshSceneAdapter().
FMeshSceneAdapter() [3/3]
UE::Geometry::FMeshSceneAdapter::FMeshSceneAdapter (FMeshSceneAdapter &&) delete
References FMeshSceneAdapter().
Member Function Documentation
AddActors()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::AddActors (const TArray< AActor * > & ActorsSetIn)
Add the given Actors to the Mesh Scene.
References UE_API.
AddComponents()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::AddComponents (const TArray< UActorComponent * > & ComponentSetIn)
Add the given Components to the Mesh Scene.
If multiple Components from the same Actor are passed in, duplicate FActorAdapters will be created
References UE_API.
Build()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::Build (const FMeshSceneAdapterBuildOptions & BuildOptions)
Build the Mesh Scene.
This must be called after the functions above, and before any queries below can be run.
References UE_API.
Build_FullDecompose()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::Build_FullDecompose (const FMeshSceneAdapterBuildOptions & BuildOptions) protected
References UE_API.
BuildSpatialEvaluationCache()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::BuildSpatialEvaluationCache () virtual
Precompute data structures that accelerate spatial evaluation queries.
Precondition for calling FastWindingNumber() and FindNearestRayIntersection(). This can be called after Build() has completed
References UE_API.
CollectMeshSeedPoints()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::CollectMeshSeedPoints (TArray< FVector3d > & PointsOut) virtual
Returns
a set of points on the surface of the meshes, can be used to initialize the MarchingCubes mesher
References UE_API.
FastUpdateTransforms()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::FastUpdateTransforms (bool bRebuildSpatialCache)
Update the transforms on all the Components in the current Mesh Scene.
Requires that Build() has been called. This will invalidate any existing SpatialEvaluationCache
Parameters
bRebuildSpatialCache if true, rebuild the SpatialEvaluationCache
References UE_API.
FastWindingNumber()
virtual MODELINGCOMPONENTS_API double UE::Geometry::FMeshSceneAdapter::FastWindingNumber (const FVector3d & WorldPoint, bool bFastEarlyOutIfPossible = true) virtual
Returns
FastWindingNumber computed at WorldPoint across all mesh Actors/Components
Parameters
bFastEarlyOutIfPossible if true, then if any Mesh Scene Element returns a Winding Number of 1, the function returns immediately
References UE_API.
FindNearestRayIntersection()
virtual MODELINGCOMPONENTS_API bool UE::Geometry::FMeshSceneAdapter::FindNearestRayIntersection (const FRay3d & WorldRay, FMeshSceneRayHit & HitResultOut) virtual
Intersect the given Ray with the MeshScene and find the nearest mesh hit.
Parameters
HitResultOut ray-intersection information will be returned here
Returns
true if hit was found and HitResultOut is initialized
References UE_API.
GenerateBaseClosingMesh()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::GenerateBaseClosingMesh (double BaseHeight = 1.0, double ExtrudeHeight = 0.0)
Generate a new mesh that "caps" the mesh scene on the bottom.
This can be used in cases where the geometry is open on the base, to fill in the hole, which allows things like mesh-solidification to work better. The base mesh is a polygon which can be optionally extruded. Currently the closing mesh is a convex hull, todo: implement a better option
Parameters
BaseHeight the height in world units from the bounding-box MinZ to consider as part of the "base".
ExtrudeHeight height in world units to extrude the generated base. Positive is in +Z direction. If zero, an open-boundary polygon is generated instead.
References UE_API.
GetAccumulatedMesh()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::GetAccumulatedMesh (FDynamicMesh3 & AccumMesh) virtual
Append all instance triangles to a single mesh.
May be very large.
References UE_API.
GetBoundingBox()
virtual MODELINGCOMPONENTS_API FAxisAlignedBox3d UE::Geometry::FMeshSceneAdapter::GetBoundingBox () virtual
Returns
bounding box for the Actor set
References UE_API.
GetGeometryStatistics()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::GetGeometryStatistics (FStatistics & StatsOut) virtual
Returns
bounding box for the Actor set
References UE_API.
GetMeshBoundingBox()
virtual MODELINGCOMPONENTS_API FAxisAlignedBox3d UE::Geometry::FMeshSceneAdapter::GetMeshBoundingBox (UActorComponent * Component, int32 ComponentIndex = -1) virtual
Returns
world-space bounding box for the Scene Mesh of the specified Component and ComponentIndex. Requires that SpatialEvaluationCache is available.
References Component, and UE_API.
GetMeshBoundingBoxes()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::GetMeshBoundingBoxes (TArray< FAxisAlignedBox3d > & Bounds) virtual
Get all world-space bounding boxes for all Scene Meshes.
References UE_API.
InitializeSpatialWrappers()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::InitializeSpatialWrappers (const TArray< FActorAdapter * > & NewItemsToProcess) protected
References UE_API.
IsValid()
MODELINGCOMPONENTS_API bool UE::Geometry::FMeshSceneAdapter::IsValid () const
Whether valid actors/components were added to the scene representation.
References UE_API.
ParallelMeshVertexEnumeration()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::ParallelMeshVertexEnumeration (TFunctionRef< bool(int32 NumMeshes)> InitializeFunc, TFunctionRef< bool(int32 MeshIndex, AActor *SourceActor, const FActorChildMesh *ChildMeshInfo, const FAxisAlignedBox3d &WorldBounds)> MeshFilterFunc, TFunctionRef< bool(int32 MeshIndex, AActor *SourceActor, const FActorChildMesh *ChildMeshInfo, const FVector3d &WorldPos)> PerVertexFunc, bool bForceSingleThreaded = false) virtual
Run a custom query across all world-transformed scene mesh vertices.
Requires that SpatialEvaluationCache is available. The internal loop is run as: ParallelFor(SceneMesh, { if (MeshFilterFunc(SceneMesh)) { for (FVector3d Vtx in Scene Mesh) { PerVertexFunc(Vtx) } } }
Parameters
InitializeFunc called with the total number of scene meshes. MeshIndex in later queries will be < NumMeshes Return false to terminate query.
MeshFilterFunc called once for each scene mesh, with unique MeshIndex per scene mesh. Return false to skip this scene mesh.
PerVertexFunc called for each worldspace-transformed scene mesh vertex. Return false to terminate enumeration over this scene mesh.
References UE_API, and WorldBounds.
ProcessActorChildMeshes()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::ProcessActorChildMeshes (TFunctionRef< void(const FActorAdapter *ActorAdapter, const FActorChildMesh *ChildMesh)> ProcessFunc) virtual
Run a custom query across all scene actor child meshes.
References UE_API.
UpdateActorBounds()
MODELINGCOMPONENTS_API void UE::Geometry::FMeshSceneAdapter::UpdateActorBounds (FActorAdapter & Actor) protected
References Actor, and UE_API.
Field Documentation
bHaveSpatialEvaluationCache
bool UE::Geometry::FMeshSceneAdapter::bHaveSpatialEvaluationCache = false protected
Definition at line 464 of file MeshSceneAdapter.h.
bSceneIsAllSolids
bool UE::Geometry::FMeshSceneAdapter::bSceneIsAllSolids = false protected
Definition at line 444 of file MeshSceneAdapter.h.
CachedWorldBounds
FAxisAlignedBox3d UE::Geometry::FMeshSceneAdapter::CachedWorldBounds protected
Definition at line 463 of file MeshSceneAdapter.h.
Octree
TSharedPtr<FSparseDynamicOctree3> UE::Geometry::FMeshSceneAdapter::Octree protected
Definition at line 462 of file MeshSceneAdapter.h.
SceneActors
TArray<TUniquePtr<FActorAdapter> > UE::Geometry::FMeshSceneAdapter::SceneActors protected
Definition at line 398 of file MeshSceneAdapter.h.
SortedSpatials
TArray<FSpatialCacheInfo> UE::Geometry::FMeshSceneAdapter::SortedSpatials protected
Definition at line 460 of file MeshSceneAdapter.h.
SpatialAdapters
TMap<void*, TSharedPtr<FSpatialWrapperInfo> > UE::Geometry::FMeshSceneAdapter::SpatialAdapters protected
Definition at line 440 of file MeshSceneAdapter.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Scene/MeshSceneAdapter.h