Unreal Engine 5.6 C++ API: IMovieSceneConstrainedSection Class Reference
IMovieSceneConstrainedSection Class Reference abstract
Functionality to add to sections that contain constraints.
#include "MovieSceneConstrainedSection.h"
Public Member Functions
virtual void AddConstraintChannel (UTickableConstraint *InConstraint)=0
FConstraintChannelAddedEvent & ConstraintChannelAdded ()
DECLARE_MULTICAST_DELEGATE_TwoParams (FConstraintChannelAddedEvent, IMovieSceneConstrainedSection *, FMovieSceneConstraintChannel *)
GENERATED_BODY () MOVIESCENETRACKS_API IMovieSceneConstrainedSection()
virtual FConstraintAndActiveChannel * GetConstraintChannel (const FGuid &InConstraintGuid)=0
virtual TArray< FConstraintAndActiveChannel > & GetConstraintsChannels ()=0
virtual bool HasConstraintChannel (const FGuid &InGuid) const =0
virtual void OnConstraintsChanged ()
virtual void RemoveConstraintChannel (const UTickableConstraint *InConstraint)=0
virtual void ReplaceConstraint (const FName InConstraintName, UTickableConstraint *InConstraint)=0
MOVIESCENETRACKS_API void SetDoNoRemoveChannel (bool bInDoNotRemoveChannel)
Data Fields
FDelegateHandle OnConstraintRemovedHandle
Protected Attributes
bool bDoNotRemoveChannel = false
FConstraintChannelAddedEvent OnConstraintChannelAdded
Detailed Description
Functionality to add to sections that contain constraints.
Interface to be added to UMovieSceneSection types when they contain entity data
Definition at line 30 of file MovieSceneConstrainedSection.h.
Member Function Documentation
AddConstraintChannel()
virtual void IMovieSceneConstrainedSection::AddConstraintChannel (UTickableConstraint * InConstraint) pure virtual
References AddConstraintChannel().
Referenced by AddConstraintChannel().
ConstraintChannelAdded()
FConstraintChannelAddedEvent & IMovieSceneConstrainedSection::ConstraintChannelAdded () inline
Definition at line 73 of file MovieSceneConstrainedSection.h.
References ConstraintChannelAdded(), and OnConstraintChannelAdded.
Referenced by ConstraintChannelAdded().
DECLARE_MULTICAST_DELEGATE_TwoParams()
IMovieSceneConstrainedSection::DECLARE_MULTICAST_DELEGATE_TwoParams (FConstraintChannelAddedEvent , IMovieSceneConstrainedSection * , FMovieSceneConstraintChannel *)
References DECLARE_MULTICAST_DELEGATE_TwoParams().
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams().
GENERATED_BODY()
IMovieSceneConstrainedSection::GENERATED_BODY ()
GetConstraintChannel()
virtual FConstraintAndActiveChannel * IMovieSceneConstrainedSection::GetConstraintChannel (const FGuid & InConstraintGuid) pure virtual
References GetConstraintChannel().
Referenced by GetConstraintChannel().
GetConstraintsChannels()
virtual TArray< FConstraintAndActiveChannel > & IMovieSceneConstrainedSection::GetConstraintsChannels () pure virtual
References GetConstraintsChannels().
Referenced by GetConstraintsChannels().
HasConstraintChannel()
virtual bool IMovieSceneConstrainedSection::HasConstraintChannel (const FGuid & InGuid) const pure virtual
References HasConstraintChannel().
Referenced by HasConstraintChannel().
OnConstraintsChanged()
virtual void IMovieSceneConstrainedSection::OnConstraintsChanged () inline virtual
Definition at line 78 of file MovieSceneConstrainedSection.h.
RemoveConstraintChannel()
virtual void IMovieSceneConstrainedSection::RemoveConstraintChannel (const UTickableConstraint * InConstraint) pure virtual
References RemoveConstraintChannel().
Referenced by RemoveConstraintChannel().
ReplaceConstraint()
virtual void IMovieSceneConstrainedSection::ReplaceConstraint (const FName InConstraintName, UTickableConstraint * InConstraint) pure virtual
References ReplaceConstraint().
Referenced by ReplaceConstraint().
SetDoNoRemoveChannel()
MOVIESCENETRACKS_API void IMovieSceneConstrainedSection::SetDoNoRemoveChannel (bool bInDoNotRemoveChannel)
Field Documentation
bDoNotRemoveChannel
bool IMovieSceneConstrainedSection::bDoNotRemoveChannel = false protected
Definition at line 94 of file MovieSceneConstrainedSection.h.
OnConstraintChannelAdded
FConstraintChannelAddedEvent IMovieSceneConstrainedSection::OnConstraintChannelAdded protected
Definition at line 93 of file MovieSceneConstrainedSection.h.
Referenced by ConstraintChannelAdded().
OnConstraintRemovedHandle
FDelegateHandle IMovieSceneConstrainedSection::OnConstraintRemovedHandle
Definition at line 88 of file MovieSceneConstrainedSection.h.
The documentation for this class was generated from the following file:
Runtime/MovieSceneTracks/Public/Sections/MovieSceneConstrainedSection.h