Unreal Engine 5.6 C++ API: FToolDataVisualizer Class Reference
FToolDataVisualizer Class Reference
FToolDataVisualizer is a utility class for Tool and Gizmo implementations to use to draw 3D lines, points, etc.
#include "ToolDataVisualizer.h"
Public Member Functions
INTERACTIVETOOLSFRAMEWORK_API FToolDataVisualizer ()
INTERACTIVETOOLSFRAMEWORK_API FToolDataVisualizer (const FToolDataVisualizer &)
virtual INTERACTIVETOOLSFRAMEWORK_API ~FToolDataVisualizer ()
INTERACTIVETOOLSFRAMEWORK_API void BeginFrame (IToolsContextRenderAPI *RenderAPI)
This must be called every frame to allow Visualizer to extract necessary rendering data/objects.
INTERACTIVETOOLSFRAMEWORK_API void BeginFrame (IToolsContextRenderAPI *RenderAPI, const FViewCameraState &CameraState)
This must be called every frame to allow Visualizer to extract necessary rendering data/objects.
template<typename PointType>
void DrawArc (const PointType &Position, const PointType &Normal, float Radius, int Steps, float MinAngle, float MaxAngle, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a 3D arc at given position/normal with the given parameters.
template<typename PointType>
void DrawCircle (const PointType &Position, const PointType &Normal, float Radius, int Steps, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a 3D circle at given position/normal with the given parameters.
template<typename PointType>
void DrawDisc (const PointType &Position, const PointType &Normal, float Radius, int Steps, const FColor &Color, FMaterialRenderProxy *RenderProxy, bool bDepthTestedIn)
Draw a 3D disc at given position/normal with the given parameters.
template<typename PointType>
void DrawLine (const PointType &A, const PointType &B)
Draw a line with default parameters.
template<typename PointType>
void DrawLine (const PointType &A, const PointType &B, const FLinearColor &Color)
Draw a line with the given Color, otherwise use default parameters.
template<typename PointType>
void DrawLine (const PointType &A, const PointType &B, const FLinearColor &Color, float LineThicknessIn)
Draw a line with the given Color and Thickness, otherwise use default parameters.
template<typename PointType>
void DrawLine (const PointType &A, const PointType &B, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a line with the given parameters.
template<typename PointType>
void DrawPoint (const PointType &Position)
Draw a point with default parameters.
template<typename PointType>
void DrawPoint (const PointType &Position, const FLinearColor &Color)
Draw a point with the given Color, otherwise use default parameters.
template<typename PointType>
void DrawPoint (const PointType &Position, const FLinearColor &Color, float PointSizeIn, bool bDepthTestedIn)
Draw a point with the given parameters.
template<typename PointType>
void DrawSquare (const PointType &Center, const PointType &SideA, const PointType &SideB)
template<typename PointType>
void DrawSquare (const PointType &Center, const PointType &SideA, const PointType &SideB, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
template<typename PointType>
void DrawViewFacingArc (const PointType &Position, float Radius, int Steps, float MinAngle, float MaxAngle, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a 3D arc at given position/normal with the given parameters.
template<typename PointType>
void DrawViewFacingCircle (const PointType &Position, float Radius, int Steps, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a 3D circle at given position/normal with the given parameters.
template<typename PointType>
void DrawViewFacingX (const PointType &Position, float Width)
Draw a world-space X facing the viewer at the given position.
template<typename PointType>
void DrawViewFacingX (const PointType &Position, float Width, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a world-space X facing the viewer at the given position.
void DrawWireBox (const FBox &Box)
Draw a 3D box, parameterized the same as the 3D circle but extruded by Height.
void DrawWireBox (const FBox &Box, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
template<typename PointType>
void DrawWireCylinder (const PointType &Position, const PointType &Normal, float Radius, float Height, int Steps)
Draw a 3D cylinder, parameterized the same as the 3D circle but extruded by Height.
template<typename PointType>
void DrawWireCylinder (const PointType &Position, const PointType &Normal, float Radius, float Height, int Steps, const FLinearColor &Color, float LineThicknessIn, bool bDepthTestedIn)
Draw a 3D cylinder, parameterized the same as the 3D circle but extruded by Height.
INTERACTIVETOOLSFRAMEWORK_API void EndFrame ()
this should be called at the end of every frame to allow for necessary cleanup
INTERACTIVETOOLSFRAMEWORK_API void PopAllTransforms ()
Clear the transform stack to identity.
INTERACTIVETOOLSFRAMEWORK_API void PopTransform ()
Pop a transform from the transform stack.
INTERACTIVETOOLSFRAMEWORK_API void PushTransform (const FTransform &Transform)
Push a Transform onto the transform stack.
void SetLineParameters (const FLinearColor &Color, float Thickness)
Update the default line color and thickness.
void SetPointParameters (const FLinearColor &Color, float Size)
Update the default point color and size.
INTERACTIVETOOLSFRAMEWORK_API void SetTransform (const FTransform &Transform)
Clear transform stack and push the given Transform.
FVector TransformN (const FVector &Normal)
FVector TransformP (const FVector &Point)
FVector TransformV (const FVector &Vector)
Data Fields
bool bDepthTested = true
Should lines be clipped by 3D geometry, or should they be drawn with quasi-transparency.
float DepthBias = 0.0f
Depth bias applied to lines.
FLinearColor LineColor
Default color used for drawing lines.
float LineThickness = 1.0f
Default thickness used for drawing lines.
FLinearColor PointColor
Default color used for drawing points.
float PointSize = 1.0f
Default size used for drawing points.
Protected Member Functions
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawArc (const FVector &InPosition, const FVector &InNormal, const float InRadius, int32 InSteps, const float InMinAngle, const float InMaxAngle, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawCircle (const FVector &Position, const FVector &Normal, float Radius, int Steps, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawDisc (const FVector &Position, const FVector &Normal, float Radius, int Steps, const FColor &Color, FMaterialRenderProxy *RenderProxy, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawSquare (const FVector &Center, const FVector &SideA, const FVector &SideB, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawTransformedLine (const FVector &A, const FVector &B, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawTransformedPoint (const FVector &Position, const FLinearColor &Color, float PointSize, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawViewFacingArc (const FVector &InPosition, float InRadius, int32 InSteps, const float InMinAngle, const float InMaxAngle, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawViewFacingCircle (const FVector &Position, float Radius, int Steps, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawViewFacingX (const FVector &Position, float Width, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawWireBox (const FBox &Box, const FLinearColor &Color, float LineThickness, bool bDepthTested)
virtual INTERACTIVETOOLSFRAMEWORK_API void InternalDrawWireCylinder (const FVector &Position, const FVector &Normal, float Radius, float Height, int Steps, const FLinearColor &Color, float LineThickness, bool bDepthTested)
Protected Attributes
bool bHaveCameraState
FViewCameraState CameraState
FPrimitiveDrawInterface * CurrentPDI = nullptr
We use this for drawing, extracted in InitializeFrame.
float PDISizeScale = 1.0
FTransform TotalTransform
TArray< FTransform > TransformStack
Detailed Description
FToolDataVisualizer is a utility class for Tool and Gizmo implementations to use to draw 3D lines, points, etc.
Currently uses PDI drawing but may use different back-ends in the future
Definition at line 18 of file ToolDataVisualizer.h.
Constructor & Destructor Documentation
FToolDataVisualizer() [1/2]
INTERACTIVETOOLSFRAMEWORK_API FToolDataVisualizer::FToolDataVisualizer ()
Referenced by FToolDataVisualizer().
FToolDataVisualizer() [2/2]
INTERACTIVETOOLSFRAMEWORK_API FToolDataVisualizer::FToolDataVisualizer (const FToolDataVisualizer &)
References FToolDataVisualizer().
~FToolDataVisualizer()
virtual INTERACTIVETOOLSFRAMEWORK_API FToolDataVisualizer::~FToolDataVisualizer () virtual
Member Function Documentation
BeginFrame() [1/2]
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::BeginFrame (IToolsContextRenderAPI * RenderAPI)
This must be called every frame to allow Visualizer to extract necessary rendering data/objects.
BeginFrame() [2/2]
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::BeginFrame (IToolsContextRenderAPI * RenderAPI, const FViewCameraState & CameraState)
This must be called every frame to allow Visualizer to extract necessary rendering data/objects.
References CameraState.
DrawArc()
template<typename PointType> void FToolDataVisualizer::DrawArc (const PointType & Position, const PointType & Normal, float Radius, int Steps, float MinAngle, float MaxAngle, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a 3D arc at given position/normal with the given parameters.
Tangent axes are defined internally
Definition at line 185 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawArc(), Normal, and Position.
DrawCircle()
template<typename PointType> void FToolDataVisualizer::DrawCircle (const PointType & Position, const PointType & Normal, float Radius, int Steps, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a 3D circle at given position/normal with the given parameters.
Tangent axes are defined internally
Definition at line 171 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawCircle(), Normal, and Position.
DrawDisc()
template<typename PointType> void FToolDataVisualizer::DrawDisc (const PointType & Position, const PointType & Normal, float Radius, int Steps, const FColor & Color, FMaterialRenderProxy * RenderProxy, bool bDepthTestedIn) inline
Draw a 3D disc at given position/normal with the given parameters.
Tangent axes are defined internally
Definition at line 250 of file ToolDataVisualizer.h.
References Color, InternalDrawDisc(), Normal, and Position.
DrawLine() [1/4]
template<typename PointType> void FToolDataVisualizer::DrawLine (const PointType & A, const PointType & B) inline
Draw a line with default parameters.
Definition at line 120 of file ToolDataVisualizer.h.
References A, B, bDepthTested, FVector, InternalDrawTransformedLine(), LineColor, LineThickness, and TransformP().
DrawLine() [2/4]
template<typename PointType> void FToolDataVisualizer::DrawLine (const PointType & A, const PointType & B, const FLinearColor & Color) inline
Draw a line with the given Color, otherwise use default parameters.
Definition at line 127 of file ToolDataVisualizer.h.
References A, B, bDepthTested, Color, FVector, InternalDrawTransformedLine(), LineThickness, and TransformP().
DrawLine() [3/4]
template<typename PointType> void FToolDataVisualizer::DrawLine (const PointType & A, const PointType & B, const FLinearColor & Color, float LineThicknessIn) inline
Draw a line with the given Color and Thickness, otherwise use default parameters.
Definition at line 134 of file ToolDataVisualizer.h.
References A, B, bDepthTested, Color, FVector, InternalDrawTransformedLine(), and TransformP().
DrawLine() [4/4]
template<typename PointType> void FToolDataVisualizer::DrawLine (const PointType & A, const PointType & B, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a line with the given parameters.
Definition at line 141 of file ToolDataVisualizer.h.
References A, B, Color, FVector, InternalDrawTransformedLine(), and TransformP().
DrawPoint() [1/3]
template<typename PointType> void FToolDataVisualizer::DrawPoint (const PointType & Position) inline
Draw a point with default parameters.
Definition at line 149 of file ToolDataVisualizer.h.
References bDepthTested, FVector, InternalDrawTransformedPoint(), PointColor, PointSize, Position, and TransformP().
DrawPoint() [2/3]
template<typename PointType> void FToolDataVisualizer::DrawPoint (const PointType & Position, const FLinearColor & Color) inline
Draw a point with the given Color, otherwise use default parameters.
Definition at line 156 of file ToolDataVisualizer.h.
References bDepthTested, Color, FVector, InternalDrawTransformedPoint(), PointSize, Position, and TransformP().
DrawPoint() [3/3]
template<typename PointType> void FToolDataVisualizer::DrawPoint (const PointType & Position, const FLinearColor & Color, float PointSizeIn, bool bDepthTestedIn) inline
Draw a point with the given parameters.
Definition at line 163 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawTransformedPoint(), Position, and TransformP().
DrawSquare() [1/2]
template<typename PointType> void FToolDataVisualizer::DrawSquare (const PointType & Center, const PointType & SideA, const PointType & SideB) inline
Definition at line 243 of file ToolDataVisualizer.h.
References bDepthTested, InternalDrawSquare(), LineColor, and LineThickness.
DrawSquare() [2/2]
template<typename PointType> void FToolDataVisualizer::DrawSquare (const PointType & Center, const PointType & SideA, const PointType & SideB, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Definition at line 237 of file ToolDataVisualizer.h.
References Color, and InternalDrawSquare().
DrawViewFacingArc()
template<typename PointType> void FToolDataVisualizer::DrawViewFacingArc (const PointType & Position, float Radius, int Steps, float MinAngle, float MaxAngle, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a 3D arc at given position/normal with the given parameters.
Tangent axes are defined internally
Definition at line 192 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawViewFacingArc(), and Position.
DrawViewFacingCircle()
template<typename PointType> void FToolDataVisualizer::DrawViewFacingCircle (const PointType & Position, float Radius, int Steps, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a 3D circle at given position/normal with the given parameters.
Tangent axes are defined internally
Definition at line 178 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawViewFacingCircle(), and Position.
DrawViewFacingX() [1/2]
template<typename PointType> void FToolDataVisualizer::DrawViewFacingX (const PointType & Position, float Width) inline
Draw a world-space X facing the viewer at the given position.
Definition at line 199 of file ToolDataVisualizer.h.
References bDepthTested, FVector, InternalDrawViewFacingX(), LineColor, LineThickness, Position, and Width.
DrawViewFacingX() [2/2]
template<typename PointType> void FToolDataVisualizer::DrawViewFacingX (const PointType & Position, float Width, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a world-space X facing the viewer at the given position.
Definition at line 206 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawViewFacingX(), Position, and Width.
DrawWireBox() [1/2]
void FToolDataVisualizer::DrawWireBox (const FBox & Box) inline
Draw a 3D box, parameterized the same as the 3D circle but extruded by Height.
Definition at line 226 of file ToolDataVisualizer.h.
References bDepthTested, Box, InternalDrawWireBox(), LineColor, and LineThickness.
DrawWireBox() [2/2]
void FToolDataVisualizer::DrawWireBox (const FBox & Box, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Definition at line 231 of file ToolDataVisualizer.h.
References Box, Color, and InternalDrawWireBox().
DrawWireCylinder() [1/2]
template<typename PointType> void FToolDataVisualizer::DrawWireCylinder (const PointType & Position, const PointType & Normal, float Radius, float Height, int Steps) inline
Draw a 3D cylinder, parameterized the same as the 3D circle but extruded by Height.
Definition at line 220 of file ToolDataVisualizer.h.
References bDepthTested, FVector, InternalDrawWireCylinder(), LineColor, LineThickness, Normal, and Position.
DrawWireCylinder() [2/2]
template<typename PointType> void FToolDataVisualizer::DrawWireCylinder (const PointType & Position, const PointType & Normal, float Radius, float Height, int Steps, const FLinearColor & Color, float LineThicknessIn, bool bDepthTestedIn) inline
Draw a 3D cylinder, parameterized the same as the 3D circle but extruded by Height.
Definition at line 213 of file ToolDataVisualizer.h.
References Color, FVector, InternalDrawWireCylinder(), Normal, and Position.
EndFrame()
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::EndFrame ()
this should be called at the end of every frame to allow for necessary cleanup
InternalDrawArc()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawArc (const FVector & InPosition, const FVector & InNormal, const float InRadius, int32 InSteps, const float InMinAngle, const float InMaxAngle, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, and LineThickness.
Referenced by DrawArc().
InternalDrawCircle()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawCircle (const FVector & Position, const FVector & Normal, float Radius, int Steps, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, LineThickness, Normal, and Position.
Referenced by DrawCircle().
InternalDrawDisc()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawDisc (const FVector & Position, const FVector & Normal, float Radius, int Steps, const FColor & Color, FMaterialRenderProxy * RenderProxy, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, Normal, and Position.
Referenced by DrawDisc().
InternalDrawSquare()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawSquare (const FVector & Center, const FVector & SideA, const FVector & SideB, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, and LineThickness.
Referenced by DrawSquare(), and DrawSquare().
InternalDrawTransformedLine()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawTransformedLine (const FVector & A, const FVector & B, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References A, B, bDepthTested, Color, FVector, and LineThickness.
Referenced by DrawLine(), DrawLine(), DrawLine(), and DrawLine().
InternalDrawTransformedPoint()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawTransformedPoint (const FVector & Position, const FLinearColor & Color, float PointSize, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, PointSize, and Position.
Referenced by DrawPoint(), DrawPoint(), and DrawPoint().
InternalDrawViewFacingArc()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawViewFacingArc (const FVector & InPosition, float InRadius, int32 InSteps, const float InMinAngle, const float InMaxAngle, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, and LineThickness.
Referenced by DrawViewFacingArc().
InternalDrawViewFacingCircle()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawViewFacingCircle (const FVector & Position, float Radius, int Steps, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, LineThickness, and Position.
Referenced by DrawViewFacingCircle().
InternalDrawViewFacingX()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawViewFacingX (const FVector & Position, float Width, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, LineThickness, Position, and Width.
Referenced by DrawViewFacingX(), and DrawViewFacingX().
InternalDrawWireBox()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawWireBox (const FBox & Box, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Box, Color, and LineThickness.
Referenced by DrawWireBox(), and DrawWireBox().
InternalDrawWireCylinder()
virtual INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::InternalDrawWireCylinder (const FVector & Position, const FVector & Normal, float Radius, float Height, int Steps, const FLinearColor & Color, float LineThickness, bool bDepthTested) protected virtual
References bDepthTested, Color, FVector, LineThickness, Normal, and Position.
Referenced by DrawWireCylinder(), and DrawWireCylinder().
PopAllTransforms()
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::PopAllTransforms ()
Clear the transform stack to identity.
PopTransform()
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::PopTransform ()
Pop a transform from the transform stack.
PushTransform()
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::PushTransform (const FTransform & Transform)
Push a Transform onto the transform stack.
References Transform.
SetLineParameters()
void FToolDataVisualizer::SetLineParameters (const FLinearColor & Color, float Thickness) inline
Update the default line color and thickness.
Definition at line 99 of file ToolDataVisualizer.h.
References Color, LineColor, and LineThickness.
SetPointParameters()
void FToolDataVisualizer::SetPointParameters (const FLinearColor & Color, float Size) inline
Update the default point color and size.
Definition at line 106 of file ToolDataVisualizer.h.
References Color, PointColor, PointSize, and TSequenceHistory< HistorySize >::Size.
SetTransform()
INTERACTIVETOOLSFRAMEWORK_API void FToolDataVisualizer::SetTransform (const FTransform & Transform)
Clear transform stack and push the given Transform.
References Transform.
TransformN()
FVector FToolDataVisualizer::TransformN (const FVector & Normal) inline
Returns
input Normal transformed by transform stack
Definition at line 83 of file ToolDataVisualizer.h.
References FVector, Normal, TotalTransform, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
TransformP()
FVector FToolDataVisualizer::TransformP (const FVector & Point) inline
Returns
input Point transformed by transform stack
Definition at line 71 of file ToolDataVisualizer.h.
References FVector, Point, and TotalTransform.
Referenced by DrawLine(), DrawLine(), DrawLine(), DrawLine(), DrawPoint(), DrawPoint(), and DrawPoint().
TransformV()
FVector FToolDataVisualizer::TransformV (const FVector & Vector) inline
Returns
input Vector transformed by transform stack
Definition at line 77 of file ToolDataVisualizer.h.
References FVector, TotalTransform, and Vector.
Field Documentation
bDepthTested
bool FToolDataVisualizer::bDepthTested = true
Should lines be clipped by 3D geometry, or should they be drawn with quasi-transparency.
Definition at line 34 of file ToolDataVisualizer.h.
Referenced by DrawLine(), DrawLine(), DrawLine(), DrawPoint(), DrawPoint(), DrawSquare(), DrawViewFacingX(), DrawWireBox(), DrawWireCylinder(), InternalDrawArc(), InternalDrawCircle(), InternalDrawDisc(), InternalDrawSquare(), InternalDrawTransformedLine(), InternalDrawTransformedPoint(), InternalDrawViewFacingArc(), InternalDrawViewFacingCircle(), InternalDrawViewFacingX(), InternalDrawWireBox(), and InternalDrawWireCylinder().
bHaveCameraState
bool FToolDataVisualizer::bHaveCameraState protected
Definition at line 260 of file ToolDataVisualizer.h.
CameraState
FViewCameraState FToolDataVisualizer::CameraState protected
Definition at line 259 of file ToolDataVisualizer.h.
Referenced by BeginFrame().
CurrentPDI
FPrimitiveDrawInterface* FToolDataVisualizer::CurrentPDI = nullptr protected
We use this for drawing, extracted in InitializeFrame.
Definition at line 257 of file ToolDataVisualizer.h.
DepthBias
float FToolDataVisualizer::DepthBias = 0.0f
Depth bias applied to lines.
Definition at line 32 of file ToolDataVisualizer.h.
LineColor
FLinearColor FToolDataVisualizer::LineColor
Default color used for drawing lines.
Definition at line 22 of file ToolDataVisualizer.h.
Referenced by DrawLine(), DrawSquare(), DrawViewFacingX(), DrawWireBox(), DrawWireCylinder(), and SetLineParameters().
LineThickness
float FToolDataVisualizer::LineThickness = 1.0f
Default thickness used for drawing lines.
Definition at line 24 of file ToolDataVisualizer.h.
Referenced by DrawLine(), DrawLine(), DrawSquare(), DrawViewFacingX(), DrawWireBox(), DrawWireCylinder(), InternalDrawArc(), InternalDrawCircle(), InternalDrawSquare(), InternalDrawTransformedLine(), InternalDrawViewFacingArc(), InternalDrawViewFacingCircle(), InternalDrawViewFacingX(), InternalDrawWireBox(), InternalDrawWireCylinder(), and SetLineParameters().
PDISizeScale
float FToolDataVisualizer::PDISizeScale = 1.0 protected
Definition at line 264 of file ToolDataVisualizer.h.
PointColor
FLinearColor FToolDataVisualizer::PointColor
Default color used for drawing points.
Definition at line 27 of file ToolDataVisualizer.h.
Referenced by DrawPoint(), and SetPointParameters().
PointSize
float FToolDataVisualizer::PointSize = 1.0f
Default size used for drawing points.
Definition at line 29 of file ToolDataVisualizer.h.
Referenced by DrawPoint(), DrawPoint(), InternalDrawTransformedPoint(), and SetPointParameters().
TotalTransform
FTransform FToolDataVisualizer::TotalTransform protected
Definition at line 268 of file ToolDataVisualizer.h.
Referenced by TransformN(), TransformP(), and TransformV().
TransformStack
TArray<FTransform> FToolDataVisualizer::TransformStack protected
Definition at line 267 of file ToolDataVisualizer.h.
The documentation for this class was generated from the following file:
Runtime/InteractiveToolsFramework/Public/ToolDataVisualizer.h