Unreal Engine 5.6 C++ API: TSparseArray< InElementType, Allocator > Class Template Reference
TSparseArray< InElementType, Allocator > Class Template Reference
A dynamically sized array where element indices aren't necessarily contiguous.
#include "SparseArray.h"
Data Structures
class FElementCompareClass
Extracts the element value from the array's element structure and passes it to the user provided comparison class.
class TBaseIterator
The base class of sparse array iterators.
class TConstIterator
Iterates over all allocated elements in a const sparse array.
class TConstSubsetIterator
An iterator which only iterates over the elements of the array which correspond to set bits in a separate bit array.
class TIterator
Iterates over all allocated elements in a sparse array.
class TRangedForConstIterator
class TRangedForIterator
Public Types
using IntrusiveUnsetOptionalStateType = TSparseArray
Public Member Functions
TSparseArray ()
Default constructor.
TSparseArray (const TSparseArray &InCopy)
Copy constructor.
TSparseArray (FIntrusiveUnsetOptionalState Tag)
TSparseArray (TSparseArray &&InCopy)
Move constructor.
~TSparseArray ()
Destructor.
int32 Add (const ElementType &Element)
Adds an element to the array.
int32 Add (ElementType &&Element)
Adds an element to the array.
FSparseArrayAllocationInfo AddUninitialized ()
Allocates space for an element in the array.
FSparseArrayAllocationInfo AddUninitializedAtLowestFreeIndex (int32 &LowestFreeIndexSearchStart)
FSparseArrayAllocationInfo AllocateIndex (int32 Index)
Marks an index as allocated, and returns information about the allocation.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void CheckAddress (const ElementType *Addr) const
Checks that the specified address is not part of an element within the container.
bool Compact ()
Compacts the allocated elements into a contiguous index range.
bool CompactStable ()
Compacts the allocated elements into a contiguous index range.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
void CountBytes (FArchive &Ar) const
Tracks the container's memory use through an archive.
TConstIterator CreateConstIterator () const
Creates a const iterator for the contents of this array.
TIterator CreateIterator ()
Creates an iterator for the contents of this array.
template<typename... ArgsType>
FORCEINLINE int32 Emplace (ArgsType &&... Args)
Constructs a new item at the last freed index of the array.
template<typename... ArgsType>
FORCEINLINE int32 EmplaceAt (int32 Index, ArgsType &&... Args)
Constructs a new item at a given index of the array.
template<typename... ArgsType>
FORCEINLINE int32 EmplaceAtLowestFreeIndex (int32 &LowestFreeIndexSearchStart, ArgsType &&... Args)
Constructs a new item at the lowest free index of the array.
void Empty (int32 ExpectedNumElements=0)
Removes all elements from the array, potentially leaving space allocated for an expected number of elements about to be added.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
int32 FindArbitraryElementIndex () const
Finds the index of an arbitrary element.
SIZE_T GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container Only returns the size of allocations made directly by the container, not the elements themselves.
int32 GetMaxIndex () const
template<typename Predicate>
int32 IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
void Insert (int32 Index, typename TTypeTraits< ElementType >::ConstInitType Element)
Inserts an element to the array.
FSparseArrayAllocationInfo InsertUninitialized (int32 Index)
Allocates space for an element in the array at a given index.
bool IsAllocated (int32 Index) const
bool IsCompact () const
bool IsEmpty () const
bool IsValidIndex (int32 Index) const
new (Allocation) ElementType(Element)
int32 Num () const
bool operator!= (const TSparseArray &B) const
Inequality comparison operator.
TSparseArray & operator+= (const TArray< ElementType > &OtherArray)
TSparseArray & operator+= (const TSparseArray &OtherArray)
Concatenation operators.
TSparseArray & operator= (const TSparseArray &InCopy)
Copy assignment operator.
TSparseArray & operator= (TSparseArray &&InCopy)
Move assignment operator.
bool operator== (const TSparseArray &B) const
Equality comparison operator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
ElementType & operator[] (int32 Index)
const ElementType & operator[] (int32 Index) const
int32 PointerToIndex (const ElementType *Ptr) const
void RemoveAt (int32 Index, int32 Count=1)
Removes Count elements from the array, starting from Index.
void RemoveAtUninitialized (int32 Index, int32 Count=1)
Removes Count elements from the array, starting from Index, without destructing them.
void Reserve (int32 ExpectedNumElements)
Preallocates enough memory to contain the specified number of elements.
void Reset ()
Empties the array, but keep its allocated memory as slack.
void Shrink ()
Shrinks the array's storage to avoid slack.
void Sort ()
Sorts the elements assuming < operator is defined for ElementType.
template<typename PREDICATE_CLASS>
void Sort (const PREDICATE_CLASS &Predicate)
Sorts the elements using the provided comparison class.
void SortFreeList ()
Sort the free element list so that subsequent allocations will occur in the lowest available position resulting in tighter packing without moving any existing items.
void StableSort ()
Stable sorts the elements assuming < operator is defined for ElementType.
template<typename PREDICATE_CLASS>
void StableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the elements using the provided comparison class.
UE_DEPRECATED (4.26, "AddAtLowestFreeIndex API is deprecated; please use EmplaceAtLowestFreeIndex instead.") int32 AddAtLowestFreeIndex(const ElementType &Element
Add an element at the lowest free index, instead of the last freed index.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Public Member Functions
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Data Fields
return Allocation Index
int32 & LowestFreeIndexSearchStart
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Types
typedef TBitArray< typename Allocator::BitArrayAllocator > AllocationBitArrayType
typedef TArray< FElementOrFreeListLink, typename Allocator::ElementAllocator > DataType
using ElementType = InElementType
typedef TSparseArrayElementOrFreeListLink< TAlignedBytes< sizeof(ElementType), alignof(ElementType)> > FElementOrFreeListLink
The element type stored is only indirectly related to the element type requested, to avoid instantiating TArray redundantly for compatible types.
Static Private Member Functions
template<typename SparseArrayType>
static FORCEINLINE void Move (SparseArrayType &ToArray, SparseArrayType &FromArray)
Private Attributes
AllocationBitArrayType AllocationFlags
DataType Data
int32 FirstFreeIndex = -1
The index of an unallocated element in the array that currently contains the head of the linked list of free elements.
int32 NumFreeIndices = 0
The number of elements in the free list.
Friends
template<typename, typename>
class TScriptSparseArray
Detailed Description
template<typename InElementType, typename Allocator>
class TSparseArray< InElementType, Allocator >
A dynamically sized array where element indices aren't necessarily contiguous.
Memory is allocated for all elements in the array's index range, so it doesn't save memory; but it does allow O(1) element removal that doesn't invalidate the indices of subsequent elements. It uses TArray to store the elements, and a TBitArray to store whether each element index is allocated (for fast iteration over allocated elements).
Definition at line 73 of file SparseArray.h.
Member Typedef Documentation
AllocationBitArrayType
template<typename InElementType, typename Allocator> typedef TBitArray<typename Allocator::BitArrayAllocator> TSparseArray< InElementType, Allocator >::AllocationBitArrayType private
Definition at line 1221 of file SparseArray.h.
DataType
template<typename InElementType, typename Allocator> typedef TArray<FElementOrFreeListLink,typename Allocator::ElementAllocator> TSparseArray< InElementType, Allocator >::DataType private
Definition at line 1218 of file SparseArray.h.
ElementType
template<typename InElementType, typename Allocator> using TSparseArray< InElementType, Allocator >::ElementType = InElementType private
Definition at line 75 of file SparseArray.h.
FElementOrFreeListLink
template<typename InElementType, typename Allocator> typedef TSparseArrayElementOrFreeListLink< TAlignedBytes<sizeof(ElementType), alignof(ElementType)> > TSparseArray< InElementType, Allocator >::FElementOrFreeListLink private
The element type stored is only indirectly related to the element type requested, to avoid instantiating TArray redundantly for compatible types.
Definition at line 1198 of file SparseArray.h.
IntrusiveUnsetOptionalStateType
template<typename InElementType, typename Allocator> using TSparseArray< InElementType, Allocator >::IntrusiveUnsetOptionalStateType = TSparseArray
Definition at line 92 of file SparseArray.h.
Constructor & Destructor Documentation
~TSparseArray()
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::~TSparseArray () inline
Destructor.
Definition at line 82 of file SparseArray.h.
TSparseArray() [1/4]
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TSparseArray (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard
Definition at line 94 of file SparseArray.h.
Referenced by TSparseArray< InElementType, Allocator >::TConstIterator::TConstIterator(), TSparseArray< InElementType, Allocator >::TConstIterator::TConstIterator(), TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::TConstSubsetIterator(), TSparseArray< InElementType, Allocator >::TIterator::TIterator(), TSparseArray< InElementType, Allocator >::TIterator::TIterator(), TSparseArray< InElementType, Allocator >::TRangedForConstIterator::TRangedForConstIterator(), and TSparseArray< InElementType, Allocator >::TRangedForIterator::TRangedForIterator().
TSparseArray() [2/4]
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TSparseArray () inline nodiscard
Default constructor.
Definition at line 783 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
TSparseArray() [3/4]
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TSparseArray (TSparseArray< InElementType, Allocator > && InCopy) inline nodiscard
Move constructor.
Definition at line 790 of file SparseArray.h.
TSparseArray() [4/4]
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TSparseArray (const TSparseArray< InElementType, Allocator > & InCopy) inline nodiscard
Copy constructor.
Definition at line 796 of file SparseArray.h.
Member Function Documentation
Add() [1/2]
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::Add (const ElementType & Element) inline
Adds an element to the array.
Definition at line 155 of file SparseArray.h.
Referenced by TMeshElementArrayBase< ElementType >::Compact().
Add() [2/2]
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::Add (ElementType && Element) inline
Adds an element to the array.
Definition at line 163 of file SparseArray.h.
AddUninitialized()
template<typename InElementType, typename Allocator> FSparseArrayAllocationInfo TSparseArray< InElementType, Allocator >::AddUninitialized () inline
Allocates space for an element in the array.
The element is not initialized, and you must use the corresponding placement new operator to construct the element in the allocated memory.
Definition at line 128 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Add(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Add(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CompactStable(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Emplace(), and operator<<().
AddUninitializedAtLowestFreeIndex()
template<typename InElementType, typename Allocator> FSparseArrayAllocationInfo TSparseArray< InElementType, Allocator >::AddUninitializedAtLowestFreeIndex (int32 & LowestFreeIndexSearchStart) inline
Definition at line 170 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::EmplaceAtLowestFreeIndex().
AllocateIndex()
template<typename InElementType, typename Allocator> FSparseArrayAllocationInfo TSparseArray< InElementType, Allocator >::AllocateIndex (int32 Index) inline
Marks an index as allocated, and returns information about the allocation.
Definition at line 107 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::AddUninitialized(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::InsertUninitialized().
AppendHash()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::AppendHash (const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher) inline static
Definition at line 1311 of file SparseArray.h.
Referenced by Freeze::IntrinsicAppendHash().
begin() [1/2]
template<typename InElementType, typename Allocator> FORCEINLINE TRangedForIterator TSparseArray< InElementType, Allocator >::begin () inline nodiscard
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 1115 of file SparseArray.h.
begin() [2/2]
template<typename InElementType, typename Allocator> FORCEINLINE TRangedForConstIterator TSparseArray< InElementType, Allocator >::begin () const inline nodiscard
Definition at line 1116 of file SparseArray.h.
CheckAddress()
template<typename InElementType, typename Allocator> FORCEINLINE void TSparseArray< InElementType, Allocator >::CheckAddress (const ElementType * Addr) const inline
Checks that the specified address is not part of an element within the container.
Used for implementations to check that reference arguments aren't going to be invalidated by possible reallocation.
Parameters
Addr The address to check.
Definition at line 933 of file SparseArray.h.
Compact()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::Compact () inline
Compacts the allocated elements into a contiguous index range.
Returns true if any elements were relocated, false otherwise.
Definition at line 528 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Sort().
CompactStable()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::CompactStable () inline
Compacts the allocated elements into a contiguous index range.
Does not change the iteration order of the elements. Returns true if any elements were relocated, false otherwise.
Definition at line 578 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::StableSort().
CopyUnfrozen()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::CopyUnfrozen (const FMemoryUnfreezeContent & Context, void * Dst) const inline
Definition at line 1276 of file SparseArray.h.
Referenced by TSet< class UObject * >::CopyUnfrozen().
CountBytes()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::CountBytes (FArchive & Ar) const inline
Tracks the container's memory use through an archive.
Definition at line 731 of file SparseArray.h.
CreateConstIterator()
template<typename InElementType, typename Allocator> TConstIterator TSparseArray< InElementType, Allocator >::CreateConstIterator () const inline nodiscard
Creates a const iterator for the contents of this array.
Definition at line 1105 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::IndexOfByPredicate().
CreateIterator()
template<typename InElementType, typename Allocator> TIterator TSparseArray< InElementType, Allocator >::CreateIterator () inline nodiscard
Creates an iterator for the contents of this array.
Definition at line 1099 of file SparseArray.h.
Emplace()
template<typename InElementType, typename Allocator> template<typename... ArgsType> FORCEINLINE int32 TSparseArray< InElementType, Allocator >::Emplace (ArgsType &&... Args) inline
Constructs a new item at the last freed index of the array.
Parameters
Args The arguments to forward to the constructor of the new item.
Returns
Index to the new item
Definition at line 236 of file SparseArray.h.
EmplaceAt()
template<typename InElementType, typename Allocator> template<typename... ArgsType> FORCEINLINE int32 TSparseArray< InElementType, Allocator >::EmplaceAt (int32 Index, ArgsType &&... Args) inline
Constructs a new item at a given index of the array.
Parameters
Index Index at which the new allocation will be done
Args The arguments to forward to the constructor of the new item.
Returns
Index to the new item
Definition at line 267 of file SparseArray.h.
EmplaceAtLowestFreeIndex()
template<typename InElementType, typename Allocator> template<typename... ArgsType> FORCEINLINE int32 TSparseArray< InElementType, Allocator >::EmplaceAtLowestFreeIndex (int32 & LowestFreeIndexSearchStart, ArgsType &&... Args) inline
Constructs a new item at the lowest free index of the array.
This requires a search which can be accelerated with LowestFreeIndexSearchStart.
Parameters
LowestFreeIndexSearchStart Where to start the search for a free index.
Args The arguments to forward to the constructor of the new item.
Returns
Index to the new item
Definition at line 252 of file SparseArray.h.
Empty()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::Empty (int32 ExpectedNumElements = 0) inline
Removes all elements from the array, potentially leaving space allocated for an expected number of elements about to be added.
Parameters
ExpectedNumElements - The expected number of elements about to be added.
Definition at line 393 of file SparseArray.h.
Referenced by TMeshElementArrayBase< ElementType >::Compact(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CompactStable(), and operator<<().
end() [1/2]
template<typename InElementType, typename Allocator> FORCEINLINE TRangedForIterator TSparseArray< InElementType, Allocator >::end () inline nodiscard
Definition at line 1117 of file SparseArray.h.
end() [2/2]
template<typename InElementType, typename Allocator> FORCEINLINE TRangedForConstIterator TSparseArray< InElementType, Allocator >::end () const inline nodiscard
Definition at line 1118 of file SparseArray.h.
FindArbitraryElementIndex()
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::FindArbitraryElementIndex () const inline nodiscard
Finds the index of an arbitrary element.
Callers should not depend on particular patterns in the behaviour of this function.
Returns
The index of any element in the container, or INDEX_NONE if it is empty.
Definition at line 708 of file SparseArray.h.
GetAllocatedSize()
template<typename InElementType, typename Allocator> SIZE_T TSparseArray< InElementType, Allocator >::GetAllocatedSize (void) const inline nodiscard
Helper function to return the amount of memory allocated by this container Only returns the size of allocations made directly by the container, not the elements themselves.
Returns
number of bytes allocated by this container
Definition at line 725 of file SparseArray.h.
GetMaxIndex()
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::GetMaxIndex () const inline nodiscard
Definition at line 914 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::AllocateIndex(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator==(), and TMeshElementArrayBase< ElementType >::Remap().
IndexOfByPredicate()
template<typename InElementType, typename Allocator> template<typename Predicate> int32 TSparseArray< InElementType, Allocator >::IndexOfByPredicate (Predicate Pred) const inline nodiscard
Finds an item by predicate.
Parameters
Pred The predicate to match.
Returns
Index to the first matching element, or INDEX_NONE if none is found.
Definition at line 690 of file SparseArray.h.
Insert()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::Insert (int32 Index, typename TTypeTraits< ElementType >::ConstInitType Element) inline
Inserts an element to the array.
Definition at line 345 of file SparseArray.h.
Referenced by TMeshElementArrayBase< ElementType >::Compact(), and TMeshElementArrayBase< ElementType >::Remap().
InsertUninitialized()
template<typename InElementType, typename Allocator> FSparseArrayAllocationInfo TSparseArray< InElementType, Allocator >::InsertUninitialized (int32 Index) inline
Allocates space for an element in the array at a given index.
The element is not initialized, and you must use the corresponding placement new operator to construct the element in the allocated memory.
Definition at line 288 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::EmplaceAt(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Insert().
IsAllocated()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::IsAllocated (int32 Index) const inline nodiscard
Definition at line 910 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator==(), and TMeshElementArrayBase< ElementType >::Remap().
IsCompact()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::IsCompact () const inline nodiscard
Definition at line 737 of file SparseArray.h.
IsEmpty()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::IsEmpty () const inline nodiscard
Definition at line 918 of file SparseArray.h.
IsValidIndex()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::IsValidIndex (int32 Index) const inline nodiscard
Definition at line 906 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::SortFreeList().
Move()
template<typename InElementType, typename Allocator> template<typename SparseArrayType> FORCEINLINE void TSparseArray< InElementType, Allocator >::Move (SparseArrayType & ToArray, SparseArrayType & FromArray) inline static private
Definition at line 865 of file SparseArray.h.
new()
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::new (Allocation)
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=().
Num()
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::Num () const inline nodiscard
Definition at line 922 of file SparseArray.h.
Referenced by TSparseArray< InElementType, Allocator >::TRangedForConstIterator::TRangedForConstIterator(), TSparseArray< InElementType, Allocator >::TRangedForIterator::TRangedForIterator(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CompactStable(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator+=(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator+=(), operator<<(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Sort(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::StableSort().
operator!=()
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::operator!= (const TSparseArray< InElementType, Allocator > & B) const inline nodiscard
Inequality comparison operator.
Checks that both arrays have the same elements and element indices; that means that unallocated elements are signifigant!
Definition at line 777 of file SparseArray.h.
operator+=() [1/2]
template<typename InElementType, typename Allocator> TSparseArray & TSparseArray< InElementType, Allocator >::operator+= (const TArray< ElementType > & OtherArray) inline
Definition at line 1180 of file SparseArray.h.
operator+=() [2/2]
template<typename InElementType, typename Allocator> TSparseArray & TSparseArray< InElementType, Allocator >::operator+= (const TSparseArray< InElementType, Allocator > & OtherArray) inline
Concatenation operators.
Definition at line 1171 of file SparseArray.h.
operator=() [1/2]
template<typename InElementType, typename Allocator> TSparseArray & TSparseArray< InElementType, Allocator >::operator= (const TSparseArray< InElementType, Allocator > & InCopy) inline
Copy assignment operator.
Definition at line 814 of file SparseArray.h.
operator=() [2/2]
template<typename InElementType, typename Allocator> TSparseArray & TSparseArray< InElementType, Allocator >::operator= (TSparseArray< InElementType, Allocator > && InCopy) inline
Move assignment operator.
Definition at line 804 of file SparseArray.h.
operator==() [1/2]
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::operator== (const TSparseArray< InElementType, Allocator > & B) const inline nodiscard
Equality comparison operator.
Checks that both arrays have the same elements and element indices; that means that unallocated elements are signifigant!
Definition at line 746 of file SparseArray.h.
operator==() [2/2]
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard
Definition at line 98 of file SparseArray.h.
operator[]() [1/2]
template<typename InElementType, typename Allocator> ElementType & TSparseArray< InElementType, Allocator >::operator[] (int32 Index) inline nodiscard
Definition at line 887 of file SparseArray.h.
operator[]() [2/2]
template<typename InElementType, typename Allocator> const ElementType & TSparseArray< InElementType, Allocator >::operator[] (int32 Index) const inline nodiscard
Definition at line 893 of file SparseArray.h.
PointerToIndex()
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::PointerToIndex (const ElementType * Ptr) const inline nodiscard
Definition at line 899 of file SparseArray.h.
RemoveAt()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::RemoveAt (int32 Index, int32 Count = 1) inline
Removes Count elements from the array, starting from Index.
Definition at line 351 of file SparseArray.h.
RemoveAtUninitialized()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::RemoveAtUninitialized (int32 Index, int32 Count = 1) inline
Removes Count elements from the array, starting from Index, without destructing them.
Definition at line 366 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::RemoveAt().
Reserve()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::Reserve (int32 ExpectedNumElements) inline
Preallocates enough memory to contain the specified number of elements.
Parameters
ExpectedNumElements the total number of elements that the array will have
Definition at line 437 of file SparseArray.h.
Referenced by TMeshElementArrayBase< ElementType >::Compact(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator+=(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator+=(), and TMeshElementArrayBase< ElementType >::Remap().
Reset()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::Reset () inline
Empties the array, but keep its allocated memory as slack.
Definition at line 413 of file SparseArray.h.
Shrink()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::Shrink () inline
Shrinks the array's storage to avoid slack.
Definition at line 474 of file SparseArray.h.
Sort() [1/2]
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::Sort () inline
Sorts the elements assuming < operator is defined for ElementType.
Definition at line 614 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Sort().
Sort() [2/2]
template<typename InElementType, typename Allocator> template<typename PREDICATE_CLASS> void TSparseArray< InElementType, Allocator >::Sort (const PREDICATE_CLASS & Predicate) inline
Sorts the elements using the provided comparison class.
Definition at line 601 of file SparseArray.h.
SortFreeList()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::SortFreeList () inline
Sort the free element list so that subsequent allocations will occur in the lowest available position resulting in tighter packing without moving any existing items.
This also means that assigned indices no longer depend on the order in which old items were removed, making it easier to use the container when determinism is required (without a container reset).
E.g., call SortFreeList() each frame to make the container assign the same indices when we perform the following operations: Frame1: Add(A) -> [0]; Add(B) -> [1]; Remove(A); Remove(B); (Free list is now {[1],[0],...}) Frame2: Add(A) -> [1]; Add(B) -> [0]; Remove(A); Remove(B); (Free list is now {[0],[1],...})
NOTE: This is operation is currently O(N) with N = GetMaxIndex(). This could be improved for large mostly-full arrays if necessary.
Definition at line 653 of file SparseArray.h.
StableSort() [1/2]
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::StableSort () inline
Stable sorts the elements assuming < operator is defined for ElementType.
Definition at line 634 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::StableSort().
StableSort() [2/2]
template<typename InElementType, typename Allocator> template<typename PREDICATE_CLASS> void TSparseArray< InElementType, Allocator >::StableSort (const PREDICATE_CLASS & Predicate) inline
Stable sorts the elements using the provided comparison class.
Definition at line 621 of file SparseArray.h.
UE_DEPRECATED()
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::UE_DEPRECATED (4. 26, "AddAtLowestFreeIndex API is deprecated; please use EmplaceAtLowestFreeIndex instead.") const &
Add an element at the lowest free index, instead of the last freed index.
This requires a search which can be accelerated with LowestFreeIndexSearchStart.
WriteMemoryImage()
template<typename InElementType, typename Allocator> void TSparseArray< InElementType, Allocator >::WriteMemoryImage (FMemoryImageWriter & Writer) const inline
Definition at line 1231 of file SparseArray.h.
Referenced by TSet< class UObject * >::WriteMemoryImage().
Friends And Related Symbol Documentation
TScriptSparseArray
template<typename InElementType, typename Allocator> template<typename, typename> friend class TScriptSparseArray friend
Definition at line 78 of file SparseArray.h.
Field Documentation
AllocationFlags
template<typename InElementType, typename Allocator> AllocationBitArrayType TSparseArray< InElementType, Allocator >::AllocationFlags private
Definition at line 1222 of file SparseArray.h.
Referenced by TSparseArray< InElementType, Allocator >::TConstIterator::TConstIterator(), TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::TConstSubsetIterator(), TSparseArray< InElementType, Allocator >::TIterator::TIterator(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=().
bHasIntrusiveUnsetOptionalState
template<typename InElementType, typename Allocator> bool TSparseArray< InElementType, Allocator >::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 91 of file SparseArray.h.
Data
template<typename InElementType, typename Allocator> DataType TSparseArray< InElementType, Allocator >::Data private
Definition at line 1219 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=().
FirstFreeIndex
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::FirstFreeIndex = -1 private
The index of an unallocated element in the array that currently contains the head of the linked list of free elements.
Definition at line 1225 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=().
Index
template<typename InElementType, typename Allocator> return Allocation TSparseArray< InElementType, Allocator >::Index
Definition at line 226 of file SparseArray.h.
LowestFreeIndexSearchStart
template<typename InElementType, typename Allocator> int32& TSparseArray< InElementType, Allocator >::LowestFreeIndexSearchStart
Initial value:
{
        FSparseArrayAllocationInfo Allocation = AddUninitializedAtLowestFreeIndex(LowestFreeIndexSearchStart)
Definition at line 222 of file SparseArray.h.
NumFreeIndices
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::NumFreeIndices = 0 private
The number of elements in the free list.
Definition at line 1228 of file SparseArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::CopyUnfrozen(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SparseArray.h