Unreal Engine 5.6 C++ API: UE::Geometry::TTransformSequence3< RealType > Class Template Reference
UE::Geometry::TTransformSequence3< RealType > Class Template Reference
TTransformSequence3 represents a sequence of 3D transforms.
#include "TransformSequence.h"
Public Member Functions
void Append (const FTransform &Transform)
Add Transform to the end of the sequence, ie Seq(P) becomes NewTransform * Seq(P)
void Append (const TTransformSequence3< RealType > &SequenceToAppend)
Add all transforms in given sequence to the end of this sequence, ie Seq(P) becomes SequenceToAppend * Seq(P)
void Append (const TTransformSRT3< RealType > &Transform)
Add Transform to the end of the sequence, ie Seq(P) becomes NewTransform * Seq(P)
void AppendInverse (const FTransform &Transform, const RealType Tolerance=TMathUtil< RealType >::ZeroTolerance)
void AppendInverse (const TTransformSequence3< RealType > &SequenceToAppend, const RealType Tolerance=TMathUtil< RealType >::ZeroTolerance)
void AppendInverse (const TTransformSRT3< RealType > &Transform, const RealType Tolerance=TMathUtil< RealType >::ZeroTolerance)
void ClearScales ()
Set scales of all transforms to (1,1,1)
TVector< RealType > GetAccumulatedScale () const
TTransformSequence3< RealType > GetInverse (const RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
const TArray< TTransformSRT3< RealType >, TInlineAllocator< 2 > > & GetTransforms () const
bool HasNonUniformScale (RealType Tolerance=TMathUtil< RealType >::ZeroTolerance) const
TVector< RealType > InverseTransformPosition (UE::Math::TVector< RealType > P) const
template<typename TransformsEquivalentFunc>
bool IsEquivalent (const TTransformSequence3< RealType > &OtherSeq, TransformsEquivalentFunc TransformsTest) const
int32 Num () const
TVector< RealType > TransformNormal (UE::Math::TVector< RealType > Normal) const
TVector< RealType > TransformPosition (UE::Math::TVector< RealType > P) const
TVector< RealType > TransformVector (UE::Math::TVector< RealType > V) const
bool WillInvert () const
Protected Attributes
TArray< TTransformSRT3< RealType >, TInlineAllocator< 2 > > Transforms
Detailed Description
template<typename RealType>
class UE::Geometry::TTransformSequence3< RealType >
TTransformSequence3 represents a sequence of 3D transforms.
Definition at line 19 of file TransformSequence.h.
Member Function Documentation
Append() [1/3]
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::Append (const FTransform & Transform) inline
Add Transform to the end of the sequence, ie Seq(P) becomes NewTransform * Seq(P)
Definition at line 37 of file TransformSequence.h.
Append() [2/3]
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::Append (const TTransformSequence3< RealType > & SequenceToAppend) inline
Add all transforms in given sequence to the end of this sequence, ie Seq(P) becomes SequenceToAppend * Seq(P)
Definition at line 45 of file TransformSequence.h.
Append() [3/3]
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::Append (const TTransformSRT3< RealType > & Transform) inline
Add Transform to the end of the sequence, ie Seq(P) becomes NewTransform * Seq(P)
Definition at line 29 of file TransformSequence.h.
Referenced by UE::Geometry::TTransformSequence3< float >::Append(), and UE::Geometry::TTransformSequence3< float >::AppendInverse().
AppendInverse() [1/3]
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::AppendInverse (const FTransform & Transform, const RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) inline
Definition at line 80 of file TransformSequence.h.
Referenced by UE::Geometry::TTransformSequence3< float >::AppendInverse(), UE::Geometry::TTransformSequence3< float >::AppendInverse(), and UE::Geometry::TTransformSequence3< float >::GetInverse().
AppendInverse() [2/3]
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::AppendInverse (const TTransformSequence3< RealType > & SequenceToAppend, const RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) inline
Definition at line 104 of file TransformSequence.h.
AppendInverse() [3/3]
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::AppendInverse (const TTransformSRT3< RealType > & Transform, const RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) inline
Definition at line 85 of file TransformSequence.h.
ClearScales()
template<typename RealType> void UE::Geometry::TTransformSequence3< RealType >::ClearScales () inline
Set scales of all transforms to (1,1,1)
Definition at line 152 of file TransformSequence.h.
GetAccumulatedScale()
template<typename RealType> TVector< RealType > UE::Geometry::TTransformSequence3< RealType >::GetAccumulatedScale () const inline
Returns
Cumulative scale across Transforms.
Definition at line 126 of file TransformSequence.h.
GetInverse()
template<typename RealType> TTransformSequence3< RealType > UE::Geometry::TTransformSequence3< RealType >::GetInverse (const RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const inline
Definition at line 113 of file TransformSequence.h.
GetTransforms()
template<typename RealType> const TArray< TTransformSRT3< RealType >, TInlineAllocator< 2 > > & UE::Geometry::TTransformSequence3< RealType >::GetTransforms () const inline
Returns
transforms in the sequence
Definition at line 61 of file TransformSequence.h.
HasNonUniformScale()
template<typename RealType> bool UE::Geometry::TTransformSequence3< RealType >::HasNonUniformScale (RealType Tolerance = TMathUtil<RealType>::ZeroTolerance) const inline
Returns
true if any transform in the sequence has nonuniform scaling
Definition at line 67 of file TransformSequence.h.
InverseTransformPosition()
template<typename RealType> TVector< RealType > UE::Geometry::TTransformSequence3< RealType >::InverseTransformPosition (UE::Math::TVector< RealType > P) const inline
Returns
point P with inverse transform sequence applied
Definition at line 175 of file TransformSequence.h.
IsEquivalent()
template<typename RealType> template<typename TransformsEquivalentFunc> bool UE::Geometry::TTransformSequence3< RealType >::IsEquivalent (const TTransformSequence3< RealType > & OtherSeq, TransformsEquivalentFunc TransformsTest) const inline
Returns
true if each Transform in this sequence is equivalent to each transform of another sequence under the given test
Definition at line 214 of file TransformSequence.h.
Num()
template<typename RealType> int32 UE::Geometry::TTransformSequence3< RealType >::Num () const inline
Returns
number of transforms in the sequence
Definition at line 56 of file TransformSequence.h.
TransformNormal()
template<typename RealType> TVector< RealType > UE::Geometry::TTransformSequence3< RealType >::TransformNormal (UE::Math::TVector< RealType > Normal) const inline
Returns
Normal with transform sequence applied
Definition at line 201 of file TransformSequence.h.
TransformPosition()
template<typename RealType> TVector< RealType > UE::Geometry::TTransformSequence3< RealType >::TransformPosition (UE::Math::TVector< RealType > P) const inline
Returns
point P with transform sequence applied
Definition at line 163 of file TransformSequence.h.
TransformVector()
template<typename RealType> TVector< RealType > UE::Geometry::TTransformSequence3< RealType >::TransformVector (UE::Math::TVector< RealType > V) const inline
Returns
Vector V with transform sequence applied
Definition at line 188 of file TransformSequence.h.
WillInvert()
template<typename RealType> bool UE::Geometry::TTransformSequence3< RealType >::WillInvert () const inline
Returns
Whether the sequence will invert a shape (by negative scaling) when applied
Definition at line 139 of file TransformSequence.h.
Field Documentation
Transforms
template<typename RealType> TArray<TTransformSRT3<RealType>, TInlineAllocator<2> > UE::Geometry::TTransformSequence3< RealType >::Transforms protected
Definition at line 22 of file TransformSequence.h.
Referenced by UE::Geometry::TTransformSequence3< float >::Append(), and UE::Geometry::TTransformSequence3< float >::IsEquivalent().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/TransformSequence.h