Unreal Engine 5.6 C++ API: FVirtualTexture2DResource Class Reference
FVirtualTexture2DResource Class Reference
#include "TextureResource.h"
Public Member Functions
FVirtualTexture2DResource ()
FVirtualTexture2DResource (const UTexture2D *InOwner, struct FVirtualTextureBuiltData *InVTData, int32 FirstMipToUse)
virtual ~FVirtualTexture2DResource ()
class IAllocatedVirtualTexture * AcquireAllocatedVT ()
uint32 GetAllocatedvAddress () const
class IAllocatedVirtualTexture * GetAllocatedVT () const
FVirtualTexture2DResource may have an AllocatedVT, which represents a page table allocation for the virtual texture.
virtual uint32 GetBorderSize () const
virtual EPixelFormat GetFormat (uint32 LayerIndex) const
virtual uint32 GetNumLayers () const
virtual uint32 GetNumMips () const
virtual uint32 GetNumTilesX () const
virtual uint32 GetNumTilesY () const
virtual FIntPoint GetPhysicalTextureSize (uint32 LayerIndex) const
const FVirtualTextureProducerHandle & GetProducerHandle () const
virtual FIntPoint GetSizeInBlocks () const
virtual uint32 GetSizeX () const override
Returns the width of the texture in pixels.
virtual uint32 GetSizeY () const override
Returns the height of the texture in pixels.
virtual uint32 GetTileSize () const
virtual FVirtualTexture2DResource * GetVirtualTexture2DResource ()
virtual const FVirtualTexture2DResource * GetVirtualTexture2DResource () const
virtual void InitializeEditorResources (class IVirtualTexture *InVirtualTexture)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void ReleaseAllocatedVT ()
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
Public Member Functions inherited from FTextureResource
FTextureResource ()
virtual ~FTextureResource ()
FORCEINLINE int32 GetCurrentMipCount () const
virtual FStreamableTextureResource * GetStreamableTextureResource ()
virtual const FStreamableTextureResource * GetStreamableTextureResource () const
virtual FTexture2DArrayResource * GetTexture2DArrayResource ()
virtual const FTexture2DArrayResource * GetTexture2DArrayResource () const
FORCEINLINE FRHITexture * GetTexture2DArrayRHI () const
virtual FTexture2DResource * GetTexture2DResource ()
virtual const FTexture2DResource * GetTexture2DResource () const
FORCEINLINE FRHITexture * GetTexture2DRHI () const
virtual FTexture3DResource * GetTexture3DResource ()
virtual const FTexture3DResource * GetTexture3DResource () const
FORCEINLINE FRHITexture * GetTexture3DRHI () const
FRHITextureReference * GetTextureReference () const
virtual bool IsProxy () const
Returns true if the resource is proxying another one.
FORCEINLINE bool IsTextureRHIPartiallyResident () const
void SetTextureReference (FRHITextureReference *TextureReference)
Public Member Functions inherited from FTexture
RENDERCORE_API FTexture ()
RENDERCORE_API FTexture (const FTexture &)
RENDERCORE_API FTexture (FTexture &&)
virtual RENDERCORE_API ~FTexture ()
virtual RENDERCORE_API FString GetFriendlyName () const override
virtual RENDERCORE_API uint32 GetSizeZ () const
Returns the depth of the texture in pixels.
const FTextureRHIRef & GetTextureRHI ()
RENDERCORE_API FTexture & operator= (const FTexture &Other)
RENDERCORE_API FTexture & operator= (FTexture &&Other)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Protected Attributes
TEnumAsByte< ESamplerAddressMode > AddressU = AM_Wrap
TEnumAsByte< ESamplerAddressMode > AddressV = AM_Wrap
class IAllocatedVirtualTexture * AllocatedVT = nullptr
Local allocated VT objects used for editor views etc.
bool bRequiresSinglePhysicalPool = false
bool bSinglePhysicalSpace = false
Cached owner settings.
TEnumAsByte< ESamplerFilter > Filter = SF_Point
Cached sampler config.
int32 FirstMipToUse = 0
Mip offset.
FName PackageName
The FName of the texture package for stats.
FVirtualTextureProducerHandle ProducerHandle
ETextureCreateFlags TexCreateFlags = ETextureCreateFlags::None
Cached flags for texture creation.
FName TextureName
The FName of the texture asset.
EVTProducerPriority VirtualTextureStreamingPriority
struct FVirtualTextureBuiltData * VTData = nullptr
Built data owned by texture asset.
Protected Attributes inherited from FTextureResource
FTextureReferenceRHIRef TextureReferenceRHI
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FTexture
bool bGreyScaleFormat = false
bGreyScaleFormat indicates the texture is actually in R channel but should be read as Grey (replicate R to RGBA) this is set from CompressionSettings, not PixelFormat this is only used by Editor/Debug shaders, not real game materials, which use SamplerType from MaterialExpressions
bool bIgnoreGammaConversions = false
true if the texture is in the same gamma space as the intended rendertarget (e.g.
bool bSRGB = false
Is the pixel data in this texture sRGB?
FSamplerStateRHIRef DeferredPassSamplerStateRHI
Sampler state to be used in deferred passes when discontinuities in ddx / ddy would cause too blurry of a mip to be used.
double LastRenderTime = -FLT_MAX
The last time the texture has been bound.
FMipBiasFade MipBiasFade
Base values for fading in/out mip-levels.
FSamplerStateRHIRef SamplerStateRHI
The sampler state to use for the texture.
FTextureRHIRef TextureRHI
The texture's RHI resource.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FTexture
static RENDERCORE_API FRHISamplerState * GetOrCreateSamplerState (const FSamplerStateInitializerRHI &Initializer)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 174 of file TextureResource.h.
Constructor & Destructor Documentation
FVirtualTexture2DResource() [1/2]
FVirtualTexture2DResource::FVirtualTexture2DResource ()
Referenced by GetVirtualTexture2DResource(), and GetVirtualTexture2DResource().
FVirtualTexture2DResource() [2/2]
FVirtualTexture2DResource::FVirtualTexture2DResource (const UTexture2D * InOwner, struct FVirtualTextureBuiltData * InVTData, int32 FirstMipToUse)
References FirstMipToUse.
~FVirtualTexture2DResource()
virtual FVirtualTexture2DResource::~FVirtualTexture2DResource () virtual
Member Function Documentation
AcquireAllocatedVT()
class IAllocatedVirtualTexture * FVirtualTexture2DResource::AcquireAllocatedVT ()
GetAllocatedvAddress()
uint32 FVirtualTexture2DResource::GetAllocatedvAddress () const
GetAllocatedVT()
class IAllocatedVirtualTexture * FVirtualTexture2DResource::GetAllocatedVT () const inline
FVirtualTexture2DResource may have an AllocatedVT, which represents a page table allocation for the virtual texture.
VTs used by materials generally don't need their own allocation, since the material has its own page table allocation for each VT stack. VTs used as lightmaps need their own allocation. Also VTs open in texture editor will have a temporary allocation. GetAllocatedVT() will return the current allocation if one exists. AcquireAllocatedVT() will make a new allocation if needed, and return it. ReleaseAllocatedVT() will free any current allocation.
Definition at line 206 of file TextureResource.h.
References AllocatedVT.
Referenced by PackMaterialCacheTextureDescriptor().
GetBorderSize()
virtual uint32 FVirtualTexture2DResource::GetBorderSize () const virtual
GetFormat()
virtual EPixelFormat FVirtualTexture2DResource::GetFormat (uint32 LayerIndex) const virtual
GetNumLayers()
virtual uint32 FVirtualTexture2DResource::GetNumLayers () const virtual
GetNumMips()
virtual uint32 FVirtualTexture2DResource::GetNumMips () const virtual
GetNumTilesX()
virtual uint32 FVirtualTexture2DResource::GetNumTilesX () const virtual
GetNumTilesY()
virtual uint32 FVirtualTexture2DResource::GetNumTilesY () const virtual
GetPhysicalTextureSize()
virtual FIntPoint FVirtualTexture2DResource::GetPhysicalTextureSize (uint32 LayerIndex) const virtual
GetProducerHandle()
const FVirtualTextureProducerHandle & FVirtualTexture2DResource::GetProducerHandle () const inline
Definition at line 196 of file TextureResource.h.
References ProducerHandle.
GetSizeInBlocks()
virtual FIntPoint FVirtualTexture2DResource::GetSizeInBlocks () const virtual
GetSizeX()
virtual uint32 FVirtualTexture2DResource::GetSizeX () const override virtual
Returns the width of the texture in pixels.
Reimplemented from FTexture.
GetSizeY()
virtual uint32 FVirtualTexture2DResource::GetSizeY () const override virtual
Returns the height of the texture in pixels.
Reimplemented from FTexture.
GetTileSize()
virtual uint32 FVirtualTexture2DResource::GetTileSize () const virtual
GetVirtualTexture2DResource() [1/2]
virtual FVirtualTexture2DResource * FVirtualTexture2DResource::GetVirtualTexture2DResource () inline virtual
Reimplemented from FTextureResource.
Definition at line 185 of file TextureResource.h.
References FVirtualTexture2DResource().
GetVirtualTexture2DResource() [2/2]
virtual const FVirtualTexture2DResource * FVirtualTexture2DResource::GetVirtualTexture2DResource () const inline virtual
Reimplemented from FTextureResource.
Definition at line 187 of file TextureResource.h.
References FVirtualTexture2DResource().
InitializeEditorResources()
virtual void FVirtualTexture2DResource::InitializeEditorResources (class IVirtualTexture * InVirtualTexture) virtual
InitRHI()
virtual void FVirtualTexture2DResource::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseAllocatedVT()
void FVirtualTexture2DResource::ReleaseAllocatedVT ()
ReleaseRHI()
virtual void FVirtualTexture2DResource::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FTexture.
Field Documentation
AddressU
TEnumAsByte<ESamplerAddressMode> FVirtualTexture2DResource::AddressU = AM_Wrap protected
Definition at line 229 of file TextureResource.h.
AddressV
TEnumAsByte<ESamplerAddressMode> FVirtualTexture2DResource::AddressV = AM_Wrap protected
Definition at line 230 of file TextureResource.h.
AllocatedVT
class IAllocatedVirtualTexture* FVirtualTexture2DResource::AllocatedVT = nullptr protected
Local allocated VT objects used for editor views etc.
Definition at line 242 of file TextureResource.h.
Referenced by GetAllocatedVT().
bRequiresSinglePhysicalPool
bool FVirtualTexture2DResource::bRequiresSinglePhysicalPool = false protected
Definition at line 235 of file TextureResource.h.
bSinglePhysicalSpace
bool FVirtualTexture2DResource::bSinglePhysicalSpace = false protected
Cached owner settings.
Definition at line 234 of file TextureResource.h.
Filter
TEnumAsByte<ESamplerFilter> FVirtualTexture2DResource::Filter = SF_Point protected
Cached sampler config.
Definition at line 228 of file TextureResource.h.
FirstMipToUse
int32 FVirtualTexture2DResource::FirstMipToUse = 0 protected
Mip offset.
Definition at line 238 of file TextureResource.h.
Referenced by FVirtualTexture2DResource().
PackageName
FName FVirtualTexture2DResource::PackageName protected
The FName of the texture package for stats.
Definition at line 226 of file TextureResource.h.
ProducerHandle
FVirtualTextureProducerHandle FVirtualTexture2DResource::ProducerHandle protected
Definition at line 243 of file TextureResource.h.
Referenced by GetProducerHandle().
TexCreateFlags
ETextureCreateFlags FVirtualTexture2DResource::TexCreateFlags = ETextureCreateFlags::None protected
Cached flags for texture creation.
Definition at line 232 of file TextureResource.h.
TextureName
FName FVirtualTexture2DResource::TextureName protected
The FName of the texture asset.
Definition at line 224 of file TextureResource.h.
VirtualTextureStreamingPriority
EVTProducerPriority FVirtualTexture2DResource::VirtualTextureStreamingPriority protected
Definition at line 236 of file TextureResource.h.
VTData
struct FVirtualTextureBuiltData* FVirtualTexture2DResource::VTData = nullptr protected
Built data owned by texture asset.
Definition at line 240 of file TextureResource.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/TextureResource.h