Unreal Engine 5.6 C++ API: UE::Geometry::TIntrRay3AxisAlignedBox3< RealType > Class Template Reference
UE::Geometry::TIntrRay3AxisAlignedBox3< RealType > Class Template Reference
Compute intersection between 3D ray and 3D axis-aligned box.
#include "IntrRay3AxisAlignedBox3.h"
Static Public Member Functions
static bool FindIntersection (const TRay< RealType > &Ray, const TAxisAlignedBox3< RealType > &Box, RealType &RayParamOut)
Find intersection of ray with AABB and returns ray T-value of intersection point (or TNumericLimits::Max() on miss)
static bool FindIntersection (const TVector< RealType > &Origin, const TVector< RealType > &Direction, const TAxisAlignedBox3< RealType > &Box, RealType &RayParamOut)
Find intersection of ray with AABB and returns ray T-value of intersection point (or TNumericLimits::Max() on miss)
static bool TestIntersection (const TRay< RealType > &Ray, const TAxisAlignedBox3< RealType > &Box, RealType ExpandExtents=0)
Test if ray intersects box.
Static Protected Member Functions
static FORCEINLINE bool Clip (RealType denom, RealType numer, RealType &t0, RealType &t1)
static FORCEINLINE bool DoClipping (RealType &t0, RealType &t1, const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, const TAxisAlignedBox3< RealType > &Box, bool solid, int &quantity, TVector< RealType > &Point0, TVector< RealType > &Point1, EIntersectionType &intrType)
Detailed Description
template<typename RealType>
class UE::Geometry::TIntrRay3AxisAlignedBox3< RealType >
Compute intersection between 3D ray and 3D axis-aligned box.
Definition at line 21 of file IntrRay3AxisAlignedBox3.h.
Member Function Documentation
Clip()
template<typename RealType> FORCEINLINE bool UE::Geometry::TIntrRay3AxisAlignedBox3< RealType >::Clip (RealType denom, RealType numer, RealType & t0, RealType & t1) inline static protected
Definition at line 194 of file IntrRay3AxisAlignedBox3.h.
Referenced by UE::Geometry::TIntrRay3AxisAlignedBox3< float >::DoClipping().
DoClipping()
template<typename RealType> FORCEINLINE bool UE::Geometry::TIntrRay3AxisAlignedBox3< RealType >::DoClipping (RealType & t0, RealType & t1, const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, const TAxisAlignedBox3< RealType > & Box, bool solid, int & quantity, TVector< RealType > & Point0, TVector< RealType > & Point1, EIntersectionType & intrType) inline static protected
Definition at line 152 of file IntrRay3AxisAlignedBox3.h.
Referenced by UE::Geometry::TIntrRay3AxisAlignedBox3< float >::FindIntersection().
FindIntersection() [1/2]
template<typename RealType> bool UE::Geometry::TIntrRay3AxisAlignedBox3< RealType >::FindIntersection (const TRay< RealType > & Ray, const TAxisAlignedBox3< RealType > & Box, RealType & RayParamOut) inline static
Find intersection of ray with AABB and returns ray T-value of intersection point (or TNumericLimits::Max() on miss)
Parameters
Ray query ray
Box query box
RayParamOut ray intersect T-value, or TNumericLimits::Max()
Returns
true if ray intersects box
Definition at line 110 of file IntrRay3AxisAlignedBox3.h.
Referenced by UE::Geometry::TIntrRay3AxisAlignedBox3< float >::FindIntersection(), and UE::Geometry::TIntrRay3OrientedBox3< float >::FindIntersection().
FindIntersection() [2/2]
template<typename RealType> bool UE::Geometry::TIntrRay3AxisAlignedBox3< RealType >::FindIntersection (const TVector< RealType > & Origin, const TVector< RealType > & Direction, const TAxisAlignedBox3< RealType > & Box, RealType & RayParamOut) inline static
Find intersection of ray with AABB and returns ray T-value of intersection point (or TNumericLimits::Max() on miss)
Parameters
Origin query ray origin
Direction query ray direction
Box query box
RayParamOut ray intersect T-value, or TNumericLimits::Max()
Returns
true if ray intersects box
Definition at line 122 of file IntrRay3AxisAlignedBox3.h.
TestIntersection()
template<typename RealType> bool UE::Geometry::TIntrRay3AxisAlignedBox3< RealType >::TestIntersection (const TRay< RealType > & Ray, const TAxisAlignedBox3< RealType > & Box, RealType ExpandExtents = 0) inline static
Test if ray intersects box.
Parameters
Ray query ray
Box query box
ExpandExtents box is expanded by this amount in each direction, useful for dealing with float imprecision
Returns
true if ray intersects box
Definition at line 36 of file IntrRay3AxisAlignedBox3.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Intersection/IntrRay3AxisAlignedBox3.h