Unreal Engine 5.6 C++ API: IMovieSceneEvaluationHook Class Reference
IMovieSceneEvaluationHook Class Reference
All evaluation hooks are executed at the end of the frame (at a time when re-entrancy is permitted), and cannot have any component dependencies.
#include "IMovieSceneEvaluationHook.h"
Public Types
using FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Public Member Functions
virtual MOVIESCENE_API void End (TSharedRef< FSharedPlaybackState > SharedPlaybackState, const UE::MovieScene::FEvaluationHookParams &Params) const
GENERATED_BODY () MOVIESCENE_API virtual void Begin(TSharedRef< FSharedPlaybackState > SharedPlaybackState
virtual MOVIESCENE_API void Trigger (TSharedRef< FSharedPlaybackState > SharedPlaybackState, const UE::MovieScene::FEvaluationHookParams &Params) const
virtual MOVIESCENE_API void Update (TSharedRef< FSharedPlaybackState > SharedPlaybackState, const UE::MovieScene::FEvaluationHookParams &Params) const
Data Fields
const UE::MovieScene::FEvaluationHookParams &Params const
Protected Member Functions
UE_DEPRECATED (5.5, "Please implement the version that takes a SharedPlaybackState") virtual void Begin(IMovieScenePlayer *Player
Detailed Description
All evaluation hooks are executed at the end of the frame (at a time when re-entrancy is permitted), and cannot have any component dependencies.
Definition at line 60 of file IMovieSceneEvaluationHook.h.
Member Typedef Documentation
FSharedPlaybackState
using IMovieSceneEvaluationHook::FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Definition at line 64 of file IMovieSceneEvaluationHook.h.
Member Function Documentation
End()
virtual MOVIESCENE_API void IMovieSceneEvaluationHook::End (TSharedRef< FSharedPlaybackState > SharedPlaybackState, const UE::MovieScene::FEvaluationHookParams & Params) const virtual
References const, End(), and Params.
Referenced by End().
GENERATED_BODY()
IMovieSceneEvaluationHook::GENERATED_BODY ()
Trigger()
virtual MOVIESCENE_API void IMovieSceneEvaluationHook::Trigger (TSharedRef< FSharedPlaybackState > SharedPlaybackState, const UE::MovieScene::FEvaluationHookParams & Params) const virtual
References const, Params, and Trigger().
Referenced by Trigger().
UE_DEPRECATED()
IMovieSceneEvaluationHook::UE_DEPRECATED (5. 5, "Please implement the version that takes a SharedPlaybackState") protected
References const, Params, and UE_DEPRECATED().
Referenced by UE_DEPRECATED().
Update()
virtual MOVIESCENE_API void IMovieSceneEvaluationHook::Update (TSharedRef< FSharedPlaybackState > SharedPlaybackState, const UE::MovieScene::FEvaluationHookParams & Params) const virtual
References const, Params, and Update().
Referenced by Update().
Field Documentation
const
const UE::MovieScene::FEvaluationHookParams& Params IMovieSceneEvaluationHook::const
Definition at line 68 of file IMovieSceneEvaluationHook.h.
Referenced by End(), Trigger(), UE_DEPRECATED(), and Update().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Evaluation/IMovieSceneEvaluationHook.h