Unreal Engine 5.6 C++ API: FMD5 Class Reference
FMD5 Class Reference
!it would be cool if these were implemented as subclasses of
#include "SecureHash.h"
Data Structures
struct FContext
Public Member Functions
FMD5 ()
~FMD5 ()
void Final (uint8 *digest)
MD5 finalization.
void Update (const uint8 *input, uint64 inputLen)
MD5 block update operation.
Static Public Member Functions
static FString HashAnsiString (const TCHAR *String)
Helper to perform the very common case of hashing an ASCII string into a hex representation.
static FString HashBytes (const uint8 *input, uint64 inputLen)
Helper to perform the very common case of hashing an in-memory array of bytes into a hex representation.
Private Member Functions
void Decode (uint32 *output, const uint8 *input, int32 len)
void Encode (uint8 *output, const uint32 *input, int32 len)
void Transform (uint32 *state, const uint8 *block)
Private Attributes
FContext Context
Detailed Description
!it would be cool if these were implemented as subclasses of
Definition at line 57 of file SecureHash.h.
Constructor & Destructor Documentation
FMD5()
FMD5::FMD5 ()
Referenced by HashBytes().
~FMD5()
FMD5::~FMD5 ()
Member Function Documentation
Decode()
void FMD5::Decode (uint32 * output, const uint8 * input, int32 len) private
Encode()
void FMD5::Encode (uint8 * output, const uint32 * input, int32 len) private
Final()
void FMD5::Final (uint8 * digest)
MD5 finalization.
Ends an MD5 message-digest operation, writing the the message digest and zeroizing the context. Digest is 16 BYTEs.
Parameters
digest pointer to a buffer where the digest should be stored (must have at least 16 bytes)
Referenced by HashBytes(), and FMD5Hash::Set().
HashAnsiString()
FString FMD5::HashAnsiString (const TCHAR * String) inline static
Helper to perform the very common case of hashing an ASCII string into a hex representation.
Parameters
String hex representation of the hash (32 lower-case hex digits)
Definition at line 86 of file SecureHash.h.
References HashBytes(), String, TCString< TCHAR >::Strlen(), and TCHAR_TO_ANSI.
Referenced by TDisplayClusterDataCache< InDataType >::HashString().
HashBytes()
FString FMD5::HashBytes (const uint8 * input, uint64 inputLen) inline static
Helper to perform the very common case of hashing an in-memory array of bytes into a hex representation.
Parameters
String hex representation of the hash (32 lower-case hex digits)
Definition at line 96 of file SecureHash.h.
References FMD5(), Final(), TEXT, and Update().
Referenced by HashAnsiString().
Transform()
void FMD5::Transform (uint32 * state, const uint8 * block) private
Update()
void FMD5::Update (const uint8 * input, uint64 inputLen)
MD5 block update operation.
Continues an MD5 message-digest operation, processing another message block, and updating the context.
Parameters
input input data
inputLen length of the input data in bytes
Referenced by HashBytes().
Field Documentation
Context
FContext FMD5::Context private
Definition at line 125 of file SecureHash.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/SecureHash.h