Unreal Engine 5.6 C++ API: FAudioChunkHandle Class Reference
FAudioChunkHandle Class Reference
This structure allows audio chunk data to be accessed, and guarantees that the chunk in question will not be deleted during it's lifecycle.
#include "ContentStreaming.h"
Public Member Functions
FAudioChunkHandle ()
FAudioChunkHandle (const FAudioChunkHandle &Other)
FAudioChunkHandle (FAudioChunkHandle &&Other)
~FAudioChunkHandle ()
const uint8 * GetData () const
bool IsStale () const
bool IsValid () const
uint32 Num () const
FAudioChunkHandle & operator= (const FAudioChunkHandle &Other)
FAudioChunkHandle & operator= (FAudioChunkHandle &&Other)
Private Member Functions
FAudioChunkHandle (const uint8 *InData, uint32 NumBytes, const FSoundWaveProxyPtr &InSoundWave, const FName &SoundWaveName, uint32 InChunkIndex, uint64 InCacheLookupID)
Private Attributes
const uint8 * CachedData
int32 CachedDataNumBytes
int32 ChunkIndex
uint32 ChunkRevision
TWeakPtr< FSoundWaveData, ESPMode::ThreadSafe > CorrespondingWave
FGuid CorrespondingWaveGuid
FName CorrespondingWaveName
Friends
struct FCachedAudioStreamingManager
struct IAudioStreamingManager
Detailed Description
This structure allows audio chunk data to be accessed, and guarantees that the chunk in question will not be deleted during it's lifecycle.
Definition at line 108 of file ContentStreaming.h.
Constructor & Destructor Documentation
FAudioChunkHandle() [1/4]
FAudioChunkHandle::FAudioChunkHandle ()
Referenced by FAudioChunkHandle(), FAudioChunkHandle(), operator=(), and operator=().
FAudioChunkHandle() [2/4]
FAudioChunkHandle::FAudioChunkHandle (const FAudioChunkHandle & Other)
References FAudioChunkHandle(), and Other.
FAudioChunkHandle() [3/4]
FAudioChunkHandle::FAudioChunkHandle (FAudioChunkHandle && Other)
References FAudioChunkHandle(), and Other.
~FAudioChunkHandle()
FAudioChunkHandle::~FAudioChunkHandle ()
FAudioChunkHandle() [4/4]
FAudioChunkHandle::FAudioChunkHandle (const uint8 * InData, uint32 NumBytes, const FSoundWaveProxyPtr & InSoundWave, const FName & SoundWaveName, uint32 InChunkIndex, uint64 InCacheLookupID) private
Member Function Documentation
GetData()
const uint8 * FAudioChunkHandle::GetData () const
IsStale()
bool FAudioChunkHandle::IsStale () const
IsValid()
bool FAudioChunkHandle::IsValid () const
Num()
uint32 FAudioChunkHandle::Num () const
operator=() [1/2]
FAudioChunkHandle & FAudioChunkHandle::operator= (const FAudioChunkHandle & Other)
References FAudioChunkHandle(), and Other.
operator=() [2/2]
FAudioChunkHandle & FAudioChunkHandle::operator= (FAudioChunkHandle && Other)
References FAudioChunkHandle(), and Other.
Friends And Related Symbol Documentation
FCachedAudioStreamingManager
friend struct FCachedAudioStreamingManager friend
Definition at line 153 of file ContentStreaming.h.
References FCachedAudioStreamingManager.
Referenced by FCachedAudioStreamingManager.
IAudioStreamingManager
friend struct IAudioStreamingManager friend
Definition at line 152 of file ContentStreaming.h.
References IAudioStreamingManager.
Referenced by IAudioStreamingManager.
Field Documentation
CachedData
const uint8* FAudioChunkHandle::CachedData private
Definition at line 138 of file ContentStreaming.h.
CachedDataNumBytes
int32 FAudioChunkHandle::CachedDataNumBytes private
Definition at line 139 of file ContentStreaming.h.
ChunkIndex
int32 FAudioChunkHandle::ChunkIndex private
Definition at line 145 of file ContentStreaming.h.
ChunkRevision
uint32 FAudioChunkHandle::ChunkRevision private
Definition at line 149 of file ContentStreaming.h.
CorrespondingWave
TWeakPtr<FSoundWaveData, ESPMode::ThreadSafe> FAudioChunkHandle::CorrespondingWave private
Definition at line 148 of file ContentStreaming.h.
CorrespondingWaveGuid
FGuid FAudioChunkHandle::CorrespondingWaveGuid private
Definition at line 142 of file ContentStreaming.h.
CorrespondingWaveName
FName FAudioChunkHandle::CorrespondingWaveName private
Definition at line 141 of file ContentStreaming.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ContentStreaming.h