Unreal Engine 5.6 C++ API: AEFVariableKeyLerp< FORMAT > Class Template Reference
AEFVariableKeyLerp< FORMAT > Class Template Reference
#include "AnimEncoding_VariableKeyLerp.h"
Public Member Functions
virtual void GetBoneAtomRotation (FTransform &OutAtom, const FAnimSequenceDecompressionContext &DecompContext, int32 TrackIndex) override
Decompress the Rotation component of a BoneAtom.
virtual void GetBoneAtomScale (FTransform &OutAtom, const FAnimSequenceDecompressionContext &DecompContext, int32 TrackIndex) override
Decompress the Scale component of a BoneAtom.
virtual void GetBoneAtomTranslation (FTransform &OutAtom, const FAnimSequenceDecompressionContext &DecompContext, int32 TrackIndex) override
Decompress the Translation component of a BoneAtom.
virtual void GetPoseRotations (TArrayView< FTransform > &Atoms, const BoneTrackArray &DesiredPairs, FAnimSequenceDecompressionContext &DecompContext) override
Decompress all requested rotation components from an Animation Sequence.
virtual void GetPoseScales (TArrayView< FTransform > &Atoms, const BoneTrackArray &DesiredPairs, FAnimSequenceDecompressionContext &DecompContext) override
Decompress all requested Scale components from an Animation Sequence.
virtual void GetPoseTranslations (TArrayView< FTransform > &Atoms, const BoneTrackArray &DesiredPairs, FAnimSequenceDecompressionContext &DecompContext) override
Decompress all requested translation components from an Animation Sequence.
Public Member Functions inherited from AEFVariableKeyLerpShared
virtual void ByteSwapRotationIn (FUECompressedAnimData &CompressedData, FMemoryReader &MemoryReader, uint8 *&RotTrackData, int32 NumKeysRot) override
Handles the ByteSwap of compressed rotation data on import.
virtual void ByteSwapRotationOut (FUECompressedAnimData &CompressedData, FMemoryWriter &MemoryWriter, uint8 *&RotTrackData, int32 NumKeysRot) override
Handles the ByteSwap of compressed rotation data on export.
virtual void ByteSwapScaleIn (FUECompressedAnimData &CompressedData, FMemoryReader &MemoryReader, uint8 *&ScaleTrackData, int32 NumKeysScale) override
Handles the ByteSwap of compressed Scale data on import.
virtual void ByteSwapScaleOut (FUECompressedAnimData &CompressedData, FMemoryWriter &MemoryWriter, uint8 *&ScaleTrackData, int32 NumKeysScale) override
Handles the ByteSwap of compressed Scale data on export.
virtual void ByteSwapTranslationIn (FUECompressedAnimData &CompressedData, FMemoryReader &MemoryReader, uint8 *&TransTrackData, int32 NumKeysTransn) override
Handles the ByteSwap of compressed translation data on import.
virtual void ByteSwapTranslationOut (FUECompressedAnimData &CompressedData, FMemoryWriter &MemoryWriter, uint8 *&TransTrackData, int32 NumKeysTrans) override
Handles the ByteSwap of compressed translation data on export.
Public Member Functions inherited from AnimEncodingLegacyBase
virtual void ByteSwapOut (FUECompressedAnimData &CompressedData, FMemoryWriter &MemoryWriter) override
Handles Byte-swapping outgoing animation data to an array of BYTEs.
Additional Inherited Members
Data Fields inherited from AnimEncodingLegacyBase
virtual void virtual GetBoneAtomRotation(FTransform &OutAtom, const FAnimSequenceDecompressionContext &DecompContext, int32 TrackIndex) PURE_VIRTUAL(AnimEncoding void virtual GetBoneAtomTranslation(FTransform &OutAtom, const FAnimSequenceDecompressionContext &DecompContext, int32 TrackIndex) PURE_VIRTUAL(AnimEncoding void virtual GetBoneAtomScale(FTransform &OutAtom, const FAnimSequenceDecompressionContext &DecompContext, int32 TrackIndex) PURE_VIRTUAL(AnimEncoding voi ByteSwapIn)(FUECompressedAnimData &CompressedData, FMemoryReader &MemoryReader) override
Decompress the Rotation component of a BoneAtom.
Static Protected Member Functions inherited from AnimEncoding
static float TimeToIndex (EAnimInterpolationType Interpolation, int32 NumberOfFrames, const uint8 *FrameTable, float RelativePos, int32 NumKeys, int32 &PosIndex0Out, int32 &PosIndex1Out)
Utility function to determine the two key indices to interpolate given a relative position in the animation.
static float TimeToIndex (float SequenceLength, float RelativePos, int32 NumKeys, EAnimInterpolationType Interpolation, int32 &PosIndex0Out, int32 &PosIndex1Out)
Handles Byte-swapping incoming animation data from a MemoryReader.
Detailed Description
template<int32 FORMAT>
class AEFVariableKeyLerp< FORMAT >
Definition at line 108 of file AnimEncoding_VariableKeyLerp.h.
Member Function Documentation
GetBoneAtomRotation()
template<int32 FORMAT> FORCEINLINE_DEBUGGABLE void AEFVariableKeyLerp< FORMAT >::GetBoneAtomRotation (FTransform & OutAtom, const FAnimSequenceDecompressionContext & DecompContext, int32 TrackIndex) override virtual
Decompress the Rotation component of a BoneAtom.
Parameters
OutAtom The FTransform to fill in.
DecompContext The decompression context to use.
TrackIndex The index of the track desired in the Animation Sequence.
Definition at line 188 of file AnimEncoding_VariableKeyLerp.h.
References Align, Alpha, FAnimSequenceDecompressionContext::CompressedAnimData, FCompressedAnimDataBase< ContainerTypeMakerTemplate >::CompressedByteStream, ICompressedAnimData::CompressedNumberOfKeys, CompressedRotationNum, CompressedRotationStrides, FCompressedAnimDataBase< ContainerTypeMakerTemplate >::CompressedTrackOffsets, DecompressRotation(), UE::Math::TQuat< float >::FastLerp(), FORCEINLINE_DEBUGGABLE, FAnimSequenceDecompressionContext::GetRelativePosition(), FAnimSequenceDecompressionContext::Interpolation, UE::Math::TQuat< T >::Normalize(), RESTRICT, UE::Math::TTransform< T >::SetRotation(), and AnimEncoding::TimeToIndex().
GetBoneAtomScale()
template<int32 FORMAT> FORCEINLINE_DEBUGGABLE void AEFVariableKeyLerp< FORMAT >::GetBoneAtomScale (FTransform & OutAtom, const FAnimSequenceDecompressionContext & DecompContext, int32 TrackIndex) override virtual
Decompress the Scale component of a BoneAtom.
Parameters
OutAtom The FTransform to fill in.
DecompContext The decompression context to use.
TrackIndex The index of the track desired in the Animation Sequence.
Definition at line 297 of file AnimEncoding_VariableKeyLerp.h.
References Align, Alpha, FAnimSequenceDecompressionContext::CompressedAnimData, FCompressedAnimDataBase< ContainerTypeMakerTemplate >::CompressedByteStream, ICompressedAnimData::CompressedNumberOfKeys, CompressedScaleNum, FCompressedAnimDataBase< ContainerTypeMakerTemplate >::CompressedScaleOffsets, CompressedScaleStrides, DecompressScale(), FORCEINLINE_DEBUGGABLE, FVector, FAnimSequenceDecompressionContext::GetRelativePosition(), FAnimSequenceDecompressionContext::Interpolation, FMath::Lerp(), RESTRICT, UE::Math::TTransform< T >::SetScale3D(), and AnimEncoding::TimeToIndex().
GetBoneAtomTranslation()
template<int32 FORMAT> FORCEINLINE_DEBUGGABLE void AEFVariableKeyLerp< FORMAT >::GetBoneAtomTranslation (FTransform & OutAtom, const FAnimSequenceDecompressionContext & DecompContext, int32 TrackIndex) override virtual
Decompress the Translation component of a BoneAtom.
Parameters
OutAtom The FTransform to fill in.
DecompContext The decompression context to use.
TrackIndex The index of the track desired in the Animation Sequence.
Definition at line 252 of file AnimEncoding_VariableKeyLerp.h.
References Align, Alpha, FAnimSequenceDecompressionContext::CompressedAnimData, FCompressedAnimDataBase< ContainerTypeMakerTemplate >::CompressedByteStream, ICompressedAnimData::CompressedNumberOfKeys, FCompressedAnimDataBase< ContainerTypeMakerTemplate >::CompressedTrackOffsets, CompressedTranslationNum, CompressedTranslationStrides, DecompressTranslation(), FORCEINLINE_DEBUGGABLE, FVector, FAnimSequenceDecompressionContext::GetRelativePosition(), FAnimSequenceDecompressionContext::Interpolation, FMath::Lerp(), RESTRICT, UE::Math::TTransform< T >::SetTranslation(), and AnimEncoding::TimeToIndex().
GetPoseRotations()
template<int32 FORMAT> virtual void AEFVariableKeyLerp< FORMAT >::GetPoseRotations (TArrayView< FTransform > & Atoms, const BoneTrackArray & DesiredPairs, FAnimSequenceDecompressionContext & DecompContext) override virtual
Decompress all requested rotation components from an Animation Sequence.
Parameters
Atoms The FTransform array to fill in.
DesiredPairs Array of requested bone information
DecompContext The decompression context to use.
GetPoseScales()
template<int32 FORMAT> virtual void AEFVariableKeyLerp< FORMAT >::GetPoseScales (TArrayView< FTransform > & Atoms, const BoneTrackArray & DesiredPairs, FAnimSequenceDecompressionContext & DecompContext) override virtual
Decompress all requested Scale components from an Animation Sequence.
Parameters
Atoms The FTransform array to fill in.
DesiredPairs Array of requested bone information
DecompContext The decompression context to use.
GetPoseTranslations()
template<int32 FORMAT> virtual void AEFVariableKeyLerp< FORMAT >::GetPoseTranslations (TArrayView< FTransform > & Atoms, const BoneTrackArray & DesiredPairs, FAnimSequenceDecompressionContext & DecompContext) override virtual
Decompress all requested translation components from an Animation Sequence.
Parameters
Atoms The FTransform array to fill in.
DesiredPairs Array of requested bone information
DecompContext The decompression context to use.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AnimEncoding_VariableKeyLerp.h