Unreal Engine 5.6 C++ API: UE::Geometry::TBlockData3< ElemType_, BlockSize_ > Class Template Reference
UE::Geometry::TBlockData3< ElemType_, BlockSize_ > Class Template Reference
#include "BlockedDenseGrid3.h"
Public Types
typedef TBlockData3Layout< BlockSize_ > DataLayout
typedef ElemType_ ElemType
typedef TStaticArray< ElemType, DataLayout::ElemCount > LinearDataStorageType
Public Member Functions
TBlockData3 ()
TBlockData3 (const ElemType &Value, const int32 ID)
ElemType & At (const int32 Index)
access the data by index into the underlying linear array
ElemType At (const int32 Index) const
access the data by index into the underlying linear array
template<typename FuncType>
void ModifyValue (const int32 Index, FuncType Func)
void Reset (const ElemType &Value)
initialize all the data elements to the specified value
Data Fields
LinearDataStorageType Data
int32 Id
Additional Inherited Members
Static Public Member Functions inherited from UE::Geometry::TBlockData3Layout< BlockSize_ >
static int32 ToLinear (const int32 &LocalI, const int32 &LocalJ, const int32 &LocalK)
static FVector3i ToLocalIJK (int32 LocalLinear)
Static Public Attributes inherited from UE::Geometry::TBlockData3Layout< BlockSize_ >
static constexpr int32 BlockSize = BlockSize_
static constexpr int32 ElemCount = BlockSize_ * BlockSize_ * BlockSize_
Detailed Description
template<typename ElemType_, int32 BlockSize_>
class UE::Geometry::TBlockData3< ElemType_, BlockSize_ >
Definition at line 23 of file BlockedDenseGrid3.h.
Member Typedef Documentation
DataLayout
template<typename ElemType_, int32 BlockSize_> typedef TBlockData3Layout<BlockSize_> UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::DataLayout
Definition at line 26 of file BlockedDenseGrid3.h.
ElemType
template<typename ElemType_, int32 BlockSize_> typedef ElemType_ UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::ElemType
Definition at line 27 of file BlockedDenseGrid3.h.
LinearDataStorageType
template<typename ElemType_, int32 BlockSize_> typedef TStaticArray<ElemType, DataLayout::ElemCount> UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::LinearDataStorageType
Definition at line 28 of file BlockedDenseGrid3.h.
Constructor & Destructor Documentation
TBlockData3() [1/2]
template<typename ElemType_, int32 BlockSize_> UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::TBlockData3 () inline
Definition at line 30 of file BlockedDenseGrid3.h.
TBlockData3() [2/2]
template<typename ElemType_, int32 BlockSize_> UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::TBlockData3 (const ElemType & Value, const int32 ID) inline
Definition at line 34 of file BlockedDenseGrid3.h.
Member Function Documentation
At() [1/2]
template<typename ElemType_, int32 BlockSize_> ElemType & UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::At (const int32 Index) inline
access the data by index into the underlying linear array
Definition at line 50 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial().
At() [2/2]
template<typename ElemType_, int32 BlockSize_> ElemType UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::At (const int32 Index) const inline
access the data by index into the underlying linear array
Definition at line 56 of file BlockedDenseGrid3.h.
ModifyValue()
template<typename ElemType_, int32 BlockSize_> template<typename FuncType> void UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::ModifyValue (const int32 Index, FuncType Func) inline
Definition at line 63 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::WriteValue().
Reset()
template<typename ElemType_, int32 BlockSize_> void UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::Reset (const ElemType & Value) inline
initialize all the data elements to the specified value
Definition at line 41 of file BlockedDenseGrid3.h.
Field Documentation
Data
template<typename ElemType_, int32 BlockSize_> LinearDataStorageType UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::Data
Definition at line 70 of file BlockedDenseGrid3.h.
Id
template<typename ElemType_, int32 BlockSize_> int32 UE::Geometry::TBlockData3< ElemType_, BlockSize_ >::Id
Definition at line 69 of file BlockedDenseGrid3.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/BlockedDenseGrid3.h