Unreal Engine 5.6 C++ API: FSavedMove_Character Class Reference
FSavedMove_Character Class Reference
FSavedMove_Character represents a saved move on the client that has been sent to the server and might need to be played back.
#include "CharacterMovementComponent.h"
Public Types
enum CompressedFlags {
FLAG_JumpPressed = 0x01 , FLAG_WantsToCrouch = 0x02 , FLAG_Reserved_1 = 0x04 , FLAG_Reserved_2 = 0x08 ,
FLAG_Custom_0 = 0x10 , FLAG_Custom_1 = 0x20 , FLAG_Custom_2 = 0x40 , FLAG_Custom_3 = 0x80
}
enum EPostUpdateMode { PostUpdate_Record , PostUpdate_Replay }
Public Member Functions
FSavedMove_Character ()
FSavedMove_Character (const FSavedMove_Character &)
FSavedMove_Character (FSavedMove_Character &&)
virtual ~FSavedMove_Character ()
virtual void AddStructReferencedObjects (FReferenceCollector &Collector) const
Allows references to be considered during GC.
virtual bool CanCombineWith (const FSavedMovePtr &NewMove, ACharacter *InCharacter, float MaxDelta) const
Returns true if this move can be combined with NewMove for replication without changing any behavior.
virtual void Clear ()
Clear saved move properties, so it can be re-used.
virtual void CombineWith (const FSavedMove_Character *OldMove, ACharacter *InCharacter, APlayerController *PC, const FVector &OldStartLocation)
Combine this move with an older move and update relevant state.
virtual uint8 GetCompressedFlags () const
Returns a byte containing encoded special movement information (jumping, crouching, etc.)
virtual void GetPackedAngles (uint32 &YawAndPitchPack, uint8 &RollPack) const
Packs control rotation for network transport.
virtual FVector GetRevertedLocation () const
Returns starting position if we were to revert the move, either absolute StartLocation, or StartRelativeLocation offset from MovementBase's current location (since we want to try to move forward at this time).
virtual bool IsImportantMove (const FSavedMovePtr &LastAckedMove) const
Returns true if this move is an "important" move that should be sent again if not acked by the server.
virtual bool IsMatchingStartControlRotation (const APlayerController *PC) const
Compare current control rotation with stored starting data.
FSavedMove_Character & operator= (const FSavedMove_Character &)
FSavedMove_Character & operator= (FSavedMove_Character &&)
virtual void PostUpdate (ACharacter *C, EPostUpdateMode PostUpdateMode)
Set the properties describing the final position, etc.
virtual void PrepMoveFor (ACharacter *C)
Called before ClientUpdatePosition uses this SavedMove to make a predictive correction.
virtual void SetInitialPosition (ACharacter *C)
Set the properties describing the position, etc.
virtual void SetMoveFor (ACharacter *C, float InDeltaTime, FVector const &NewAccel, class FNetworkPredictionData_Client_Character &ClientData)
Called to set up this saved move (when initially created) to make a predictive correction.
UE_DEPRECATED_FORGAME (4.20, "This property is deprecated, use StartPackedMovementMode or EndPackedMovementMode instead.") uint8 MovementMode
Public Member Functions inherited from FSavedMove_Character_FixLayout
virtual ~FSavedMove_Character_FixLayout ()=default
Data Fields
float AccelDotThreshold
Threshold for deciding this is an "important" move based on DP with last acked acceleration.
float AccelDotThresholdCombine
Threshold for deciding if we can combine two moves, true if cosine of angle between them is <= this.
FVector Acceleration
float AccelMag
float AccelMagThreshold
Threshold for deciding is this is an important move because acceleration magnitude has changed too much.
FVector AccelNormal
uint8 bForceMaxAccel:1
uint8 bForceNoCombine:1
If true, can't combine this move with another move.
uint8 bOldTimeStampBeforeReset:1
If true this move is using an old TimeStamp, before a reset occurred.
uint8 bPressedJump:1
uint8 bWantsToCrouch:1
uint8 bWasJumping:1
ACharacter * CharacterOwner
float CustomTimeDilation
float DeltaTime
uint32 EndActorOverlapCounter
TWeakObjectPtr< USceneComponent > EndAttachParent
FVector EndAttachRelativeLocation
FRotator EndAttachRelativeRotation
FName EndAttachSocketName
TWeakObjectPtr< UPrimitiveComponent > EndBase
FName EndBoneName
uint32 EndComponentOverlapCounter
uint8 EndPackedMovementMode
int32 JumpCurrentCount
float JumpForceTimeRemaining
float JumpKeyHoldTime
int32 JumpMaxCount
float MaxSpeed
float MaxSpeedThresholdCombine
Client saved moves will not combine if the result of GetMaxSpeed() differs by this much between moves.
TWeakObjectPtr< class UAnimMontage > RootMotionMontage
FRootMotionMovementParams RootMotionMovement
float RootMotionPlayRateWithScale
float RootMotionPreviousTrackPosition
float RootMotionTrackPosition
FRotator SavedControlRotation
FVector SavedLocation
FVector SavedRelativeAcceleration
FVector SavedRelativeLocation
FRootMotionSourceGroup SavedRootMotion
FRotator SavedRotation
FVector SavedVelocity
uint32 StartActorOverlapCounter
TWeakObjectPtr< USceneComponent > StartAttachParent
FVector StartAttachRelativeLocation
FRotator StartAttachRelativeRotation
FName StartAttachSocketName
TWeakObjectPtr< UPrimitiveComponent > StartBase
FQuat StartBaseRotation
FName StartBoneName
float StartCapsuleHalfHeight
float StartCapsuleRadius
uint32 StartComponentOverlapCounter
FRotator StartControlRotation
FFindFloorResult StartFloor
FVector StartLocation
uint8 StartPackedMovementMode
FVector StartRelativeLocation
FRotator StartRotation
FVector StartVelocity
float TimeStamp
Detailed Description
FSavedMove_Character represents a saved move on the client that has been sent to the server and might need to be played back.
Definition at line 2895 of file CharacterMovementComponent.h.
Member Enumeration Documentation
CompressedFlags
enum FSavedMove_Character::CompressedFlags
Enumerator
FLAG_JumpPressed
FLAG_WantsToCrouch
FLAG_Reserved_1
FLAG_Reserved_2
FLAG_Custom_0
FLAG_Custom_1
FLAG_Custom_2
FLAG_Custom_3
Definition at line 3040 of file CharacterMovementComponent.h.
EPostUpdateMode
enum FSavedMove_Character::EPostUpdateMode
Enumerator
PostUpdate_Record
PostUpdate_Replay
Definition at line 3009 of file CharacterMovementComponent.h.
Constructor & Destructor Documentation
FSavedMove_Character() [1/3]
FSavedMove_Character::FSavedMove_Character ()
Referenced by FSavedMove_Character(), FSavedMove_Character(), CombineWith(), operator=(), and operator=().
~FSavedMove_Character()
virtual FSavedMove_Character::~FSavedMove_Character () virtual
FSavedMove_Character() [2/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSavedMove_Character::FSavedMove_Character (const FSavedMove_Character &) inline default
References FSavedMove_Character().
FSavedMove_Character() [3/3]
FSavedMove_Character::FSavedMove_Character (FSavedMove_Character &&) inline default
References FSavedMove_Character().
Member Function Documentation
AddStructReferencedObjects()
virtual void FSavedMove_Character::AddStructReferencedObjects (FReferenceCollector & Collector) const virtual
Allows references to be considered during GC.
CanCombineWith()
virtual bool FSavedMove_Character::CanCombineWith (const FSavedMovePtr & NewMove, ACharacter * InCharacter, float MaxDelta) const virtual
Returns true if this move can be combined with NewMove for replication without changing any behavior.
Clear()
virtual void FSavedMove_Character::Clear () virtual
Clear saved move properties, so it can be re-used.
References Clear().
Referenced by Clear().
CombineWith()
virtual void FSavedMove_Character::CombineWith (const FSavedMove_Character * OldMove, ACharacter * InCharacter, APlayerController * PC, const FVector & OldStartLocation) virtual
Combine this move with an older move and update relevant state.
References FSavedMove_Character(), and FVector.
GetCompressedFlags()
virtual uint8 FSavedMove_Character::GetCompressedFlags () const virtual
Returns a byte containing encoded special movement information (jumping, crouching, etc.)
GetPackedAngles()
virtual void FSavedMove_Character::GetPackedAngles (uint32 & YawAndPitchPack, uint8 & RollPack) const virtual
Packs control rotation for network transport.
GetRevertedLocation()
virtual FVector FSavedMove_Character::GetRevertedLocation () const virtual
Returns starting position if we were to revert the move, either absolute StartLocation, or StartRelativeLocation offset from MovementBase's current location (since we want to try to move forward at this time).
References FVector, and GetRevertedLocation().
Referenced by GetRevertedLocation().
IsImportantMove()
virtual bool FSavedMove_Character::IsImportantMove (const FSavedMovePtr & LastAckedMove) const virtual
Returns true if this move is an "important" move that should be sent again if not acked by the server.
References IsImportantMove().
Referenced by IsImportantMove().
IsMatchingStartControlRotation()
virtual bool FSavedMove_Character::IsMatchingStartControlRotation (const APlayerController * PC) const virtual
Compare current control rotation with stored starting data.
operator=() [1/2]
FSavedMove_Character & FSavedMove_Character::operator= (const FSavedMove_Character &) inline default
References FSavedMove_Character().
operator=() [2/2]
FSavedMove_Character & FSavedMove_Character::operator= (FSavedMove_Character &&) inline default
References FSavedMove_Character().
PostUpdate()
virtual void FSavedMove_Character::PostUpdate (ACharacter * C, EPostUpdateMode PostUpdateMode) virtual
Set the properties describing the final position, etc.
of the moved pawn.
PrepMoveFor()
virtual void FSavedMove_Character::PrepMoveFor (ACharacter * C) virtual
Called before ClientUpdatePosition uses this SavedMove to make a predictive correction.
SetInitialPosition()
virtual void FSavedMove_Character::SetInitialPosition (ACharacter * C) virtual
Set the properties describing the position, etc.
of the moved pawn at the start of the move.
References SetInitialPosition().
Referenced by SetInitialPosition().
SetMoveFor()
virtual void FSavedMove_Character::SetMoveFor (ACharacter * C, float InDeltaTime, FVector const & NewAccel, class FNetworkPredictionData_Client_Character & ClientData) virtual
Called to set up this saved move (when initially created) to make a predictive correction.
References FVector, and SetMoveFor().
Referenced by SetMoveFor().
UE_DEPRECATED_FORGAME()
FSavedMove_Character::UE_DEPRECATED_FORGAME (4. 20, "This property is deprecated, use StartPackedMovementMode or EndPackedMovementMode instead.")
Field Documentation
AccelDotThreshold
float FSavedMove_Character::AccelDotThreshold
Threshold for deciding this is an "important" move based on DP with last acked acceleration.
Definition at line 2986 of file CharacterMovementComponent.h.
AccelDotThresholdCombine
float FSavedMove_Character::AccelDotThresholdCombine
Threshold for deciding if we can combine two moves, true if cosine of angle between them is <= this.
Definition at line 2990 of file CharacterMovementComponent.h.
Acceleration
FVector FSavedMove_Character::Acceleration
Definition at line 2970 of file CharacterMovementComponent.h.
AccelMag
float FSavedMove_Character::AccelMag
Definition at line 2975 of file CharacterMovementComponent.h.
AccelMagThreshold
float FSavedMove_Character::AccelMagThreshold
Threshold for deciding is this is an important move because acceleration magnitude has changed too much.
Definition at line 2988 of file CharacterMovementComponent.h.
AccelNormal
FVector FSavedMove_Character::AccelNormal
Definition at line 2974 of file CharacterMovementComponent.h.
bForceMaxAccel
uint8 FSavedMove_Character::bForceMaxAccel
Definition at line 2911 of file CharacterMovementComponent.h.
bForceNoCombine
uint8 FSavedMove_Character::bForceNoCombine
If true, can't combine this move with another move.
Definition at line 2914 of file CharacterMovementComponent.h.
bOldTimeStampBeforeReset
uint8 FSavedMove_Character::bOldTimeStampBeforeReset
If true this move is using an old TimeStamp, before a reset occurred.
Definition at line 2917 of file CharacterMovementComponent.h.
bPressedJump
uint8 FSavedMove_Character::bPressedJump
Definition at line 2909 of file CharacterMovementComponent.h.
bWantsToCrouch
uint8 FSavedMove_Character::bWantsToCrouch
Definition at line 2910 of file CharacterMovementComponent.h.
bWasJumping
uint8 FSavedMove_Character::bWasJumping
Definition at line 2919 of file CharacterMovementComponent.h.
CharacterOwner
ACharacter* FSavedMove_Character::CharacterOwner
Definition at line 2907 of file CharacterMovementComponent.h.
CustomTimeDilation
float FSavedMove_Character::CustomTimeDilation
Definition at line 2930 of file CharacterMovementComponent.h.
DeltaTime
float FSavedMove_Character::DeltaTime
Definition at line 2929 of file CharacterMovementComponent.h.
EndActorOverlapCounter
uint32 FSavedMove_Character::EndActorOverlapCounter
Definition at line 2963 of file CharacterMovementComponent.h.
EndAttachParent
TWeakObjectPtr<USceneComponent> FSavedMove_Character::EndAttachParent
Definition at line 2965 of file CharacterMovementComponent.h.
EndAttachRelativeLocation
FVector FSavedMove_Character::EndAttachRelativeLocation
Definition at line 2967 of file CharacterMovementComponent.h.
EndAttachRelativeRotation
FRotator FSavedMove_Character::EndAttachRelativeRotation
Definition at line 2968 of file CharacterMovementComponent.h.
EndAttachSocketName
FName FSavedMove_Character::EndAttachSocketName
Definition at line 2966 of file CharacterMovementComponent.h.
EndBase
TWeakObjectPtr<UPrimitiveComponent> FSavedMove_Character::EndBase
Definition at line 2961 of file CharacterMovementComponent.h.
EndBoneName
FName FSavedMove_Character::EndBoneName
Definition at line 2962 of file CharacterMovementComponent.h.
EndComponentOverlapCounter
uint32 FSavedMove_Character::EndComponentOverlapCounter
Definition at line 2964 of file CharacterMovementComponent.h.
EndPackedMovementMode
uint8 FSavedMove_Character::EndPackedMovementMode
Definition at line 2926 of file CharacterMovementComponent.h.
JumpCurrentCount
int32 FSavedMove_Character::JumpCurrentCount
Definition at line 2934 of file CharacterMovementComponent.h.
JumpForceTimeRemaining
float FSavedMove_Character::JumpForceTimeRemaining
Definition at line 2932 of file CharacterMovementComponent.h.
JumpKeyHoldTime
float FSavedMove_Character::JumpKeyHoldTime
Definition at line 2931 of file CharacterMovementComponent.h.
JumpMaxCount
int32 FSavedMove_Character::JumpMaxCount
Definition at line 2933 of file CharacterMovementComponent.h.
MaxSpeed
float FSavedMove_Character::MaxSpeed
Definition at line 2971 of file CharacterMovementComponent.h.
MaxSpeedThresholdCombine
float FSavedMove_Character::MaxSpeedThresholdCombine
Client saved moves will not combine if the result of GetMaxSpeed() differs by this much between moves.
Definition at line 2992 of file CharacterMovementComponent.h.
RootMotionMontage
TWeakObjectPtr<class UAnimMontage> FSavedMove_Character::RootMotionMontage mutable
Definition at line 2977 of file CharacterMovementComponent.h.
RootMotionMovement
FRootMotionMovementParams FSavedMove_Character::RootMotionMovement
Definition at line 2981 of file CharacterMovementComponent.h.
RootMotionPlayRateWithScale
float FSavedMove_Character::RootMotionPlayRateWithScale
Definition at line 2980 of file CharacterMovementComponent.h.
RootMotionPreviousTrackPosition
float FSavedMove_Character::RootMotionPreviousTrackPosition
Definition at line 2979 of file CharacterMovementComponent.h.
RootMotionTrackPosition
float FSavedMove_Character::RootMotionTrackPosition
Definition at line 2978 of file CharacterMovementComponent.h.
SavedControlRotation
FRotator FSavedMove_Character::SavedControlRotation
Definition at line 2960 of file CharacterMovementComponent.h.
SavedLocation
FVector FSavedMove_Character::SavedLocation
Definition at line 2955 of file CharacterMovementComponent.h.
SavedRelativeAcceleration
FVector FSavedMove_Character::SavedRelativeAcceleration
Definition at line 2959 of file CharacterMovementComponent.h.
SavedRelativeLocation
FVector FSavedMove_Character::SavedRelativeLocation
Definition at line 2958 of file CharacterMovementComponent.h.
SavedRootMotion
FRootMotionSourceGroup FSavedMove_Character::SavedRootMotion
Definition at line 2983 of file CharacterMovementComponent.h.
SavedRotation
FRotator FSavedMove_Character::SavedRotation
Definition at line 2956 of file CharacterMovementComponent.h.
SavedVelocity
FVector FSavedMove_Character::SavedVelocity
Definition at line 2957 of file CharacterMovementComponent.h.
StartActorOverlapCounter
uint32 FSavedMove_Character::StartActorOverlapCounter
Definition at line 2947 of file CharacterMovementComponent.h.
StartAttachParent
TWeakObjectPtr<USceneComponent> FSavedMove_Character::StartAttachParent
Definition at line 2949 of file CharacterMovementComponent.h.
StartAttachRelativeLocation
FVector FSavedMove_Character::StartAttachRelativeLocation
Definition at line 2951 of file CharacterMovementComponent.h.
StartAttachRelativeRotation
FRotator FSavedMove_Character::StartAttachRelativeRotation
Definition at line 2952 of file CharacterMovementComponent.h.
StartAttachSocketName
FName FSavedMove_Character::StartAttachSocketName
Definition at line 2950 of file CharacterMovementComponent.h.
StartBase
TWeakObjectPtr<UPrimitiveComponent> FSavedMove_Character::StartBase
Definition at line 2945 of file CharacterMovementComponent.h.
StartBaseRotation
FQuat FSavedMove_Character::StartBaseRotation
Definition at line 2942 of file CharacterMovementComponent.h.
StartBoneName
FName FSavedMove_Character::StartBoneName
Definition at line 2946 of file CharacterMovementComponent.h.
StartCapsuleHalfHeight
float FSavedMove_Character::StartCapsuleHalfHeight
Definition at line 2944 of file CharacterMovementComponent.h.
StartCapsuleRadius
float FSavedMove_Character::StartCapsuleRadius
Definition at line 2943 of file CharacterMovementComponent.h.
StartComponentOverlapCounter
uint32 FSavedMove_Character::StartComponentOverlapCounter
Definition at line 2948 of file CharacterMovementComponent.h.
StartControlRotation
FRotator FSavedMove_Character::StartControlRotation
Definition at line 2941 of file CharacterMovementComponent.h.
StartFloor
FFindFloorResult FSavedMove_Character::StartFloor
Definition at line 2939 of file CharacterMovementComponent.h.
StartLocation
FVector FSavedMove_Character::StartLocation
Definition at line 2936 of file CharacterMovementComponent.h.
StartPackedMovementMode
uint8 FSavedMove_Character::StartPackedMovementMode
Definition at line 2925 of file CharacterMovementComponent.h.
StartRelativeLocation
FVector FSavedMove_Character::StartRelativeLocation
Definition at line 2937 of file CharacterMovementComponent.h.
StartRotation
FRotator FSavedMove_Character::StartRotation
Definition at line 2940 of file CharacterMovementComponent.h.
StartVelocity
FVector FSavedMove_Character::StartVelocity
Definition at line 2938 of file CharacterMovementComponent.h.
TimeStamp
float FSavedMove_Character::TimeStamp
Definition at line 2928 of file CharacterMovementComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/GameFramework/CharacterMovementComponent.h