Unreal Engine 5.6 C++ API: FClassDragDropOp Class Reference
FClassDragDropOp Class Reference
#include "ClassDragDropOp.h"
Public Member Functions
DRAG_DROP_OPERATOR_TYPE (FClassDragDropOp, FDragDropOperation) TArray< TWeakObjectPtr< UClass > > ClassesToDrop
The classes to be dropped.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const override
The widget decorator to use.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FClassDragDropOp > New (TWeakObjectPtr< UClass > ClassToDrop)
Protected Attributes
FText HintText
Adding hint text to all drag drop operations that drop locations could set, and the decorator could report.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Additional Inherited Members
Protected Member Functions inherited from FDragDropOperation
virtual void Construct ()
Constructs the window and widget if applicable.
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 14 of file ClassDragDropOp.h.
Member Function Documentation
DRAG_DROP_OPERATOR_TYPE()
FClassDragDropOp::DRAG_DROP_OPERATOR_TYPE (FClassDragDropOp , FDragDropOperation)
The classes to be dropped.
References FDragDropOperation::FDragDropOperation().
GetDefaultDecorator()
virtual TSharedPtr< SWidget > FClassDragDropOp::GetDefaultDecorator () const inline override virtual
The widget decorator to use.
Reimplemented from FDragDropOperation.
Definition at line 23 of file ClassDragDropOp.h.
References FSlateIconFinder::FindIconBrushForClass(), FText::FromString(), FAppStyle::GetBrush(), SHorizontalBox::Slot(), and SNew.
New()
TSharedRef< FClassDragDropOp > FClassDragDropOp::New (TWeakObjectPtr< UClass > ClassToDrop) inline static
Definition at line 67 of file ClassDragDropOp.h.
References MakeShareable().
Field Documentation
HintText
FText FClassDragDropOp::HintText protected
Adding hint text to all drag drop operations that drop locations could set, and the decorator could report.
Definition at line 77 of file ClassDragDropOp.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/DragAndDrop/ClassDragDropOp.h