Unreal Engine 5.6 C++ API: SVirtualKeyboardEntry Class Reference
SVirtualKeyboardEntry Class Reference
#include "SVirtualKeyboardEntry.h"
Public Member Functions
void Construct (const FArguments &InArgs)
Construct this widget.
virtual FText GetHintText () const override
Returns the hint text.
bool GetIsReadOnly () const
virtual bool GetSelection (int &OutSelStart, int &OutSelEnd) override
virtual FText GetText () const override
Returns the text.
virtual FVirtualKeyboardOptions GetVirtualKeyboardOptions () const override
virtual EKeyboardType GetVirtualKeyboardType () const override
Returns the virtual keyboard type.
bool HasTextChangedFromOriginal () const
virtual bool IsIntegratedKeyboardEnabled () const override
Returns whether the entry is using IntegratedKeyboard.
virtual bool IsMultilineEntry () const override
Returns whether the entry is multi-line.
void RestoreOriginalText ()
Restores the text to the original state.
void SetFont (const TAttribute< FSlateFontInfo > &InNewFont)
Sets the font used to draw the text.
virtual void SetSelectionFromVirtualKeyboard (int InSelStart, int InSelEnd) override
void SetText (const TAttribute< FText > &InNewText)
Sets the text currently being edited.
virtual void SetTextFromVirtualKeyboard (const FText &InNewText, ETextEntryType TextEntryType) override
Sets the text to that entered by the virtual keyboard.
HintText ColorAndOpacity ClearKeyboardFocusOnCommit OnTextCommitted KeyboardType SLATE_ARGUMENT (FVirtualKeyboardOptions, VirtualKeyboardOptions) SLATE_ARGUMENT(bool
Sets additional arguments to be used by the virtual keyboard summoned by this widget.
HintText ColorAndOpacity SLATE_ATTRIBUTE (bool, IsReadOnly) SLATE_ATTRIBUTE(bool
Sets whether this text box can actually be modified interactively by the user.
HintText ColorAndOpacity ClearKeyboardFocusOnCommit OnTextCommitted SLATE_ATTRIBUTE (float, MinDesiredWidth) SLATE_ATTRIBUTE(EKeyboardType
Minimum width that a text block should be.
HintText SLATE_ATTRIBUTE (FSlateFontInfo, Font) SLATE_ATTRIBUTE(FSlateColor
Sets the font used to draw the text.
SLATE_ATTRIBUTE (FText, Text) SLATE_ATTRIBUTE(FText
Sets the text content for this editable text widget.
SLATE_BEGIN_ARGS (SVirtualKeyboardEntry)
HintText ColorAndOpacity ClearKeyboardFocusOnCommit OnTextCommitted KeyboardType EnableIntegratedKeyboard SLATE_END_ARGS () 1 SVirtualKeyboardEntry()
Constructor.
HintText ColorAndOpacity ClearKeyboardFocusOnCommit SLATE_EVENT (FOnTextChanged, OnTextChanged) SLATE_EVENT(FOnTextCommitted
Called whenever the text is changed programmatically or interactively by the user.
Public Member Functions inherited from SLeafWidget
SLeafWidget ()
virtual ~SLeafWidget ()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from IVirtualKeyboardEntry
virtual ~IVirtualKeyboardEntry ()
Protected Member Functions
virtual FVector2D ComputeDesiredSize (float) const override
Overwritten from SWidget.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent) override
Called when focus is given to this widget.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
Overwritten from SWidget.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
FString GetStringToRender () const
Private Attributes
TAttribute< bool > bEnableIntegratedKeyboard
Whether to enable integrated keyboard.
bool bIsChangingText
True if we're currently (potentially) changing the text string.
bool bNeedsUpdate
bool bWasFocusedByLastMouseDown
True if the last mouse down caused us to receive keyboard focus.
TAttribute< bool > ClearKeyboardFocusOnCommit
Whether to clear keyboard focus when pressing enter to commit changes.
TAttribute< FSlateColor > ColorAndOpacity
Text color and opacity.
FText EditedText
Text string currently being edited.
TAttribute< FSlateFontInfo > Font
The font used to draw the text.
TAttribute< FText > HintText
TAttribute< bool > IsReadOnly
Sets whether this text box can actually be modified interactively by the user.
TAttribute< EKeyboardType > KeyboardType
TAttribute< float > MinDesiredWidth
Prevents the editabletext from being smaller than desired in certain cases (e.g.
FOnTextChanged OnTextChanged
Called whenever the text is changed programmatically or interactively by the user.
FOnTextCommitted OnTextCommitted
Called whenever the text is committed.
FText OriginalText
Original text prior to user edits.
FScrollHelper ScrollHelper
Current scrolled position.
TAttribute< FText > Text
The text content for this editable text widget.
FVirtualKeyboardOptions VirtualKeyboardOptions
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Data Fields inherited from IVirtualKeyboardEntry
FOnSelectionChangedDelegateVK OnSelectionChanged
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Definition at line 20 of file SVirtualKeyboardEntry.h.
Member Function Documentation
ComputeDesiredSize()
virtual FVector2D SVirtualKeyboardEntry::ComputeDesiredSize (float) const override protected virtual
Overwritten from SWidget.
LeafWidgets should compute their DesiredSize based solely on their visual representation. There is no need to take child widgets into account as LeafWidgets have none by definition. For example, the TextBlock widget simply measures the area necessary to display its text with the given font and font size.
Implements SLeafWidget.
Construct()
void SVirtualKeyboardEntry::Construct (const FArguments & InArgs)
Construct this widget.
Parameters
InArgs The declaration data for this widget
References Construct().
Referenced by Construct().
GetHintText()
virtual FText SVirtualKeyboardEntry::GetHintText () const inline override virtual
Returns the hint text.
Returns
HintText
Implements IVirtualKeyboardEntry.
Definition at line 127 of file SVirtualKeyboardEntry.h.
References check, HintText, and IsInGameThread().
GetIsReadOnly()
bool SVirtualKeyboardEntry::GetIsReadOnly () const
Returns
Whether the user can edit the text.
References GetIsReadOnly().
Referenced by GetIsReadOnly().
GetSelection()
virtual bool SVirtualKeyboardEntry::GetSelection (int & OutSelStart, int & OutSelEnd) inline override virtual
Implements IVirtualKeyboardEntry.
Definition at line 115 of file SVirtualKeyboardEntry.h.
References GetSelection().
Referenced by GetSelection().
GetStringToRender()
FString SVirtualKeyboardEntry::GetStringToRender () const private
Returns
The string that needs to be rendered
GetText()
virtual FText SVirtualKeyboardEntry::GetText () const inline override virtual
Returns the text.
Returns
Text
Implements IVirtualKeyboardEntry.
Definition at line 120 of file SVirtualKeyboardEntry.h.
References check, IsInGameThread(), and Text.
GetVirtualKeyboardOptions()
virtual FVirtualKeyboardOptions SVirtualKeyboardEntry::GetVirtualKeyboardOptions () const inline override virtual
Returns
Returns additional virtual keyboard options
Implements IVirtualKeyboardEntry.
Definition at line 141 of file SVirtualKeyboardEntry.h.
References check, IsInGameThread(), and VirtualKeyboardOptions.
GetVirtualKeyboardType()
virtual EKeyboardType SVirtualKeyboardEntry::GetVirtualKeyboardType () const inline override virtual
Returns the virtual keyboard type.
Returns
VirtualKeyboardType
Implements IVirtualKeyboardEntry.
Definition at line 134 of file SVirtualKeyboardEntry.h.
References check, IsInGameThread(), and KeyboardType.
HasTextChangedFromOriginal()
bool SVirtualKeyboardEntry::HasTextChangedFromOriginal () const
Returns
whether the current text varies from the original
References HasTextChangedFromOriginal().
Referenced by HasTextChangedFromOriginal().
IsIntegratedKeyboardEnabled()
virtual bool SVirtualKeyboardEntry::IsIntegratedKeyboardEnabled () const inline override virtual
Returns whether the entry is using IntegratedKeyboard.
Returns
Whether the entry is using IntegratedKeyboard
Reimplemented from IVirtualKeyboardEntry.
Definition at line 155 of file SVirtualKeyboardEntry.h.
References bEnableIntegratedKeyboard, check, and IsInGameThread().
IsMultilineEntry()
virtual bool SVirtualKeyboardEntry::IsMultilineEntry () const inline override virtual
Returns whether the entry is multi-line.
Returns
Whether the entry is multi-line
Implements IVirtualKeyboardEntry.
Definition at line 148 of file SVirtualKeyboardEntry.h.
References check, and IsInGameThread().
OnFocusLost()
virtual void SVirtualKeyboardEntry::OnFocusLost (const FFocusEvent & InFocusEvent) override protected virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented from SWidget.
OnFocusReceived()
virtual FReply SVirtualKeyboardEntry::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) override protected virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnPaint()
virtual int32 SVirtualKeyboardEntry::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override protected virtual
Overwritten from SWidget.
LeafWidgets provide a visual representation of themselves. They do so by adding DrawElement(s) to the OutDrawElements. DrawElements should have their positions set to absolute coordinates in Window space; for this purpose the Slate system provides the AllottedGeometry parameter. AllottedGeometry describes the space allocated for the visualization of this widget.
Whenever possible, LeafWidgets should avoid dealing with layout properties. See TextBlock for an example.
Implements SLeafWidget.
References SWidget::FSlateWindowElementList.
RestoreOriginalText()
void SVirtualKeyboardEntry::RestoreOriginalText ()
Restores the text to the original state.
References RestoreOriginalText().
Referenced by RestoreOriginalText().
SetFont()
void SVirtualKeyboardEntry::SetFont (const TAttribute< FSlateFontInfo > & InNewFont)
Sets the font used to draw the text.
Parameters
InNewFont The new font to use
References SetFont().
Referenced by SetFont().
SetSelectionFromVirtualKeyboard()
virtual void SVirtualKeyboardEntry::SetSelectionFromVirtualKeyboard (int InSelStart, int InSelEnd) override virtual
Implements IVirtualKeyboardEntry.
References SetSelectionFromVirtualKeyboard().
Referenced by SetSelectionFromVirtualKeyboard().
SetText()
void SVirtualKeyboardEntry::SetText (const TAttribute< FText > & InNewText)
Sets the text currently being edited.
Parameters
InNewText The new text
References SetText().
Referenced by SetText().
SetTextFromVirtualKeyboard()
virtual void SVirtualKeyboardEntry::SetTextFromVirtualKeyboard (const FText & InNewText, ETextEntryType TextEntryType) override virtual
Sets the text to that entered by the virtual keyboard.
Parameters
InNewText The new text
TextEntryType What type of text update is being provided
CommitType If we are sending a TextCommitted event, what commit type is it
Implements IVirtualKeyboardEntry.
References SetTextFromVirtualKeyboard().
Referenced by SetTextFromVirtualKeyboard().
SLATE_ARGUMENT()
HintText ColorAndOpacity ClearKeyboardFocusOnCommit OnTextCommitted KeyboardType SVirtualKeyboardEntry::SLATE_ARGUMENT (FVirtualKeyboardOptions , VirtualKeyboardOptions)
Sets additional arguments to be used by the virtual keyboard summoned by this widget.
Whether the IntegratedKeyboard is enabled
References SLATE_ARGUMENT(), and VirtualKeyboardOptions.
Referenced by SLATE_ARGUMENT().
SLATE_ATTRIBUTE() [1/4]
HintText ColorAndOpacity SVirtualKeyboardEntry::SLATE_ATTRIBUTE (bool , IsReadOnly)
Sets whether this text box can actually be modified interactively by the user.
Whether to clear keyboard focus when pressing enter to commit changes
References ClearKeyboardFocusOnCommit, IsReadOnly, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/4]
HintText ColorAndOpacity ClearKeyboardFocusOnCommit OnTextCommitted SVirtualKeyboardEntry::SLATE_ATTRIBUTE (float , MinDesiredWidth)
Minimum width that a text block should be.
Sets the text content for this editable text widget
References KeyboardType, MinDesiredWidth, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/4]
HintText SVirtualKeyboardEntry::SLATE_ATTRIBUTE (FSlateFontInfo , Font)
Sets the font used to draw the text.
Text color and opacity
References ColorAndOpacity, Font, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [4/4]
SVirtualKeyboardEntry::SLATE_ATTRIBUTE (FText , Text)
Sets the text content for this editable text widget.
The text that appears when there is nothing typed into the search box
References HintText, and Text.
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SVirtualKeyboardEntry::SLATE_BEGIN_ARGS (SVirtualKeyboardEntry) inline
Definition at line 25 of file SVirtualKeyboardEntry.h.
References Keyboard_Default.
SLATE_END_ARGS()
HintText ColorAndOpacity ClearKeyboardFocusOnCommit OnTextCommitted KeyboardType EnableIntegratedKeyboard SVirtualKeyboardEntry::SLATE_END_ARGS ()
Constructor.
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
SLATE_EVENT()
HintText ColorAndOpacity ClearKeyboardFocusOnCommit SVirtualKeyboardEntry::SLATE_EVENT (FOnTextChanged , OnTextChanged)
Called whenever the text is changed programmatically or interactively by the user.
Called whenever the text is committed. This happens when the user presses enter or the text box loses focus.
References OnTextChanged, OnTextCommitted, and SLATE_EVENT().
Referenced by SLATE_EVENT().
SupportsKeyboardFocus()
virtual bool SVirtualKeyboardEntry::SupportsKeyboardFocus () const override protected virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Tick()
virtual void SVirtualKeyboardEntry::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override protected virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
Field Documentation
bEnableIntegratedKeyboard
TAttribute<bool> SVirtualKeyboardEntry::bEnableIntegratedKeyboard private
Whether to enable integrated keyboard.
Definition at line 225 of file SVirtualKeyboardEntry.h.
Referenced by IsIntegratedKeyboardEnabled().
bIsChangingText
bool SVirtualKeyboardEntry::bIsChangingText private
True if we're currently (potentially) changing the text string.
Definition at line 217 of file SVirtualKeyboardEntry.h.
bNeedsUpdate
bool SVirtualKeyboardEntry::bNeedsUpdate private
Definition at line 229 of file SVirtualKeyboardEntry.h.
bWasFocusedByLastMouseDown
bool SVirtualKeyboardEntry::bWasFocusedByLastMouseDown private
True if the last mouse down caused us to receive keyboard focus.
Definition at line 214 of file SVirtualKeyboardEntry.h.
ClearKeyboardFocusOnCommit
TAttribute< bool > SVirtualKeyboardEntry::ClearKeyboardFocusOnCommit private
Whether to clear keyboard focus when pressing enter to commit changes.
Definition at line 196 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_ATTRIBUTE().
ColorAndOpacity
TAttribute<FSlateColor> SVirtualKeyboardEntry::ColorAndOpacity private
Text color and opacity.
Definition at line 190 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_ATTRIBUTE().
EditedText
FText SVirtualKeyboardEntry::EditedText private
Text string currently being edited.
Definition at line 205 of file SVirtualKeyboardEntry.h.
Font
TAttribute< FSlateFontInfo > SVirtualKeyboardEntry::Font private
The font used to draw the text.
Definition at line 187 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_ATTRIBUTE().
HintText
TAttribute< FText > SVirtualKeyboardEntry::HintText private
Definition at line 184 of file SVirtualKeyboardEntry.h.
Referenced by GetHintText(), and SLATE_ATTRIBUTE().
IsReadOnly
TAttribute< bool > SVirtualKeyboardEntry::IsReadOnly private
Sets whether this text box can actually be modified interactively by the user.
Definition at line 193 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_ATTRIBUTE().
KeyboardType
TAttribute<EKeyboardType> SVirtualKeyboardEntry::KeyboardType private
Definition at line 222 of file SVirtualKeyboardEntry.h.
Referenced by GetVirtualKeyboardType(), and SLATE_ATTRIBUTE().
MinDesiredWidth
TAttribute<float> SVirtualKeyboardEntry::MinDesiredWidth private
Prevents the editabletext from being smaller than desired in certain cases (e.g.
when it is empty)
Definition at line 220 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_ATTRIBUTE().
OnTextChanged
FOnTextChanged SVirtualKeyboardEntry::OnTextChanged private
Called whenever the text is changed programmatically or interactively by the user.
Definition at line 199 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_EVENT().
OnTextCommitted
FOnTextCommitted SVirtualKeyboardEntry::OnTextCommitted private
Called whenever the text is committed.
This happens when the user presses enter or the text box loses focus.
Definition at line 202 of file SVirtualKeyboardEntry.h.
Referenced by SLATE_EVENT().
OriginalText
FText SVirtualKeyboardEntry::OriginalText private
Original text prior to user edits.
This is used to restore the text if the user uses the escape key.
Definition at line 208 of file SVirtualKeyboardEntry.h.
ScrollHelper
FScrollHelper SVirtualKeyboardEntry::ScrollHelper private
Current scrolled position.
Definition at line 211 of file SVirtualKeyboardEntry.h.
Text
TAttribute< FText > SVirtualKeyboardEntry::Text private
The text content for this editable text widget.
Definition at line 182 of file SVirtualKeyboardEntry.h.
Referenced by GetText(), and SLATE_ATTRIBUTE().
VirtualKeyboardOptions
FVirtualKeyboardOptions SVirtualKeyboardEntry::VirtualKeyboardOptions private
Definition at line 227 of file SVirtualKeyboardEntry.h.
Referenced by GetVirtualKeyboardOptions(), and SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SVirtualKeyboardEntry.h