Unreal Engine 5.6 C++ API: UE::Geometry::FMeshConstraints Class Reference
UE::Geometry::FMeshConstraints Class Reference
FMeshConstraints is a set of Edge and Vertex constraints for a Triangle Mesh.
#include "MeshConstraints.h"
Public Member Functions
FMeshConstraints ()
int AllocateSetID ()
void ClearEdgeConstraint (int EdgeID)
Clear the constraint on the given EdgeID.
void ClearVertexConstraint (int VertexID)
Clear the constraint on the given VertexID.
void FindConstrainedEdgesBySetID (int SetID, TArray< int > &FoundListOut) const
Find all constraint edges for the given SetID, and return via FoundListOut.
FEdgeConstraint GetEdgeConstraint (int EdgeID) const
bool GetEdgeConstraint (int EdgeID, FEdgeConstraint &ConstraintOut) const
const TMap< int, FEdgeConstraint > & GetEdgeConstraints () const
FVertexConstraint GetVertexConstraint (int VertexID) const
bool GetVertexConstraint (int VertexID, FVertexConstraint &ConstraintOut) const
const TMap< int, FVertexConstraint > & GetVertexConstraints () const
bool HasConstraints () const
bool HasEdgeConstraint (int EdgeID) const
bool HasVertexConstraint (int VertexID) const
void SetOrCombineVertexConstraint (int VertexID, const FVertexConstraint &vc)
void SetOrUpdateEdgeConstraint (int EdgeID, const FEdgeConstraint &ec)
Set the constraint on the given EdgeID.
void SetOrUpdateVertexConstraint (int VertexID, const FVertexConstraint &vc)
Set the constraint on the given VertexID.
Data Fields
FConstraintProjectionData ProjectionData
Additional data for constraint curve projection.
Protected Attributes
TMap< int, FEdgeConstraint > Edges
Map of mesh edge IDs to active EdgeConstraints.
int FixedSetIDCounter
internal counter used to allocate new FixedSetIDs
TMap< int, FVertexConstraint > Vertices
Map of mesh vertex IDs to active VertexConstraints.
Detailed Description
FMeshConstraints is a set of Edge and Vertex constraints for a Triangle Mesh.
Definition at line 235 of file MeshConstraints.h.
Constructor & Destructor Documentation
FMeshConstraints()
UE::Geometry::FMeshConstraints::FMeshConstraints () inline
Definition at line 254 of file MeshConstraints.h.
References FixedSetIDCounter.
Member Function Documentation
AllocateSetID()
int UE::Geometry::FMeshConstraints::AllocateSetID () inline
Returns
an unused Fixed Set ID
Definition at line 260 of file MeshConstraints.h.
References FixedSetIDCounter.
ClearEdgeConstraint()
void UE::Geometry::FMeshConstraints::ClearEdgeConstraint (int EdgeID) inline
Clear the constraint on the given EdgeID.
Definition at line 328 of file MeshConstraints.h.
References Edges.
ClearVertexConstraint()
void UE::Geometry::FMeshConstraints::ClearVertexConstraint (int VertexID) inline
Clear the constraint on the given VertexID.
Definition at line 404 of file MeshConstraints.h.
References Vertices.
FindConstrainedEdgesBySetID()
void UE::Geometry::FMeshConstraints::FindConstrainedEdgesBySetID (int SetID, TArray< int > & FoundListOut) const inline
Find all constraint edges for the given SetID, and return via FoundListOut.
Definition at line 335 of file MeshConstraints.h.
References TArray< InElementType, InAllocatorType >::Add(), and Edges.
GetEdgeConstraint() [1/2]
FEdgeConstraint UE::Geometry::FMeshConstraints::GetEdgeConstraint (int EdgeID) const inline
Returns
EdgeConstraint for give EdgeID, may be Unconstrained
Definition at line 293 of file MeshConstraints.h.
References Edges, Found, and UE::Geometry::FEdgeConstraint::Unconstrained().
GetEdgeConstraint() [2/2]
bool UE::Geometry::FMeshConstraints::GetEdgeConstraint (int EdgeID, FEdgeConstraint & ConstraintOut) const inline
Returns
true if EdgeID is constrained and ConstraintOut is filled
Definition at line 307 of file MeshConstraints.h.
References Edges, and Found.
GetEdgeConstraints()
const TMap< int, FEdgeConstraint > & UE::Geometry::FMeshConstraints::GetEdgeConstraints () const inline
Returns
map of active edge constraints
Definition at line 266 of file MeshConstraints.h.
References Edges.
GetVertexConstraint() [1/2]
FVertexConstraint UE::Geometry::FMeshConstraints::GetVertexConstraint (int VertexID) const inline
Returns
VertexConstraint for give VertexID, may be Unconstrained
Definition at line 356 of file MeshConstraints.h.
References Found, UE::Geometry::FVertexConstraint::Unconstrained(), and Vertices.
GetVertexConstraint() [2/2]
bool UE::Geometry::FMeshConstraints::GetVertexConstraint (int VertexID, FVertexConstraint & ConstraintOut) const inline
Returns
true if VetexID is constrained and ConstraintOut is filled
Definition at line 370 of file MeshConstraints.h.
References Found, and Vertices.
GetVertexConstraints()
const TMap< int, FVertexConstraint > & UE::Geometry::FMeshConstraints::GetVertexConstraints () const inline
Returns
map of active vertex constraints
Definition at line 272 of file MeshConstraints.h.
References Vertices.
HasConstraints()
bool UE::Geometry::FMeshConstraints::HasConstraints () const inline
Returns
true if any edges or vertices are constrained
Definition at line 279 of file MeshConstraints.h.
References Edges, and Vertices.
HasEdgeConstraint()
bool UE::Geometry::FMeshConstraints::HasEdgeConstraint (int EdgeID) const inline
Returns
true if given EdgeID has active constraint
Definition at line 287 of file MeshConstraints.h.
References Edges.
HasVertexConstraint()
bool UE::Geometry::FMeshConstraints::HasVertexConstraint (int VertexID) const inline
Returns
true if given VertexID has active constraint
Definition at line 349 of file MeshConstraints.h.
References Vertices.
SetOrCombineVertexConstraint()
void UE::Geometry::FMeshConstraints::SetOrCombineVertexConstraint (int VertexID, const FVertexConstraint & vc) inline
Definition at line 390 of file MeshConstraints.h.
References Found, and Vertices.
SetOrUpdateEdgeConstraint()
void UE::Geometry::FMeshConstraints::SetOrUpdateEdgeConstraint (int EdgeID, const FEdgeConstraint & ec) inline
Set the constraint on the given EdgeID.
Definition at line 322 of file MeshConstraints.h.
References Edges.
Referenced by UE::Geometry::FMeshConstraintsUtil::ConstrainSeams(), UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges(), and UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges().
SetOrUpdateVertexConstraint()
void UE::Geometry::FMeshConstraints::SetOrUpdateVertexConstraint (int VertexID, const FVertexConstraint & vc) inline
Set the constraint on the given VertexID.
Definition at line 385 of file MeshConstraints.h.
References Vertices.
Referenced by UE::Geometry::FMeshConstraintsUtil::ConstrainSeams(), UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges(), and UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges().
Field Documentation
Edges
TMap<int, FEdgeConstraint> UE::Geometry::FMeshConstraints::Edges protected
Map of mesh edge IDs to active EdgeConstraints.
Definition at line 240 of file MeshConstraints.h.
Referenced by ClearEdgeConstraint(), FindConstrainedEdgesBySetID(), GetEdgeConstraint(), GetEdgeConstraint(), GetEdgeConstraints(), HasConstraints(), HasEdgeConstraint(), and SetOrUpdateEdgeConstraint().
FixedSetIDCounter
int UE::Geometry::FMeshConstraints::FixedSetIDCounter protected
internal counter used to allocate new FixedSetIDs
Definition at line 246 of file MeshConstraints.h.
Referenced by FMeshConstraints(), and AllocateSetID().
ProjectionData
FConstraintProjectionData UE::Geometry::FMeshConstraints::ProjectionData
Additional data for constraint curve projection.
Definition at line 251 of file MeshConstraints.h.
Vertices
TMap<int, FVertexConstraint> UE::Geometry::FMeshConstraints::Vertices protected
Map of mesh vertex IDs to active VertexConstraints.
Definition at line 243 of file MeshConstraints.h.
Referenced by ClearVertexConstraint(), GetVertexConstraint(), GetVertexConstraint(), GetVertexConstraints(), HasConstraints(), HasVertexConstraint(), SetOrCombineVertexConstraint(), and SetOrUpdateVertexConstraint().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/MeshConstraints.h