Unreal Engine 5.6 C++ API: FCustomStatIDGraphTaskBase Class Reference
FCustomStatIDGraphTaskBase Class Reference
Class that generalizes functionality of storing and exposing custom stat id.
#include "TaskGraphInterfaces.h"
Public Member Functions
FCustomStatIDGraphTaskBase (const TStatId &StatId)
Constructor.
FORCEINLINE TStatId GetStatId () const
Gets stat id for this task.
Detailed Description
Class that generalizes functionality of storing and exposing custom stat id.
Should only be used as a base of a task graph class with custom stat id.
Definition at line 821 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
FCustomStatIDGraphTaskBase()
FCustomStatIDGraphTaskBase::FCustomStatIDGraphTaskBase (const TStatId & StatId) inline
Constructor.
Parameters
StatId The stat id for this task.
Definition at line 829 of file TaskGraphInterfaces.h.
Referenced by FDelegateGraphTask::FDelegateGraphTask(), FNullGraphTask::FNullGraphTask(), FSimpleDelegateGraphTask::FSimpleDelegateGraphTask(), and TFunctionGraphTaskImpl< Signature, SubsequentsMode >::TFunctionGraphTaskImpl().
Member Function Documentation
GetStatId()
FORCEINLINE TStatId FCustomStatIDGraphTaskBase::GetStatId () const inline
Gets stat id for this task.
Returns
Stat id.
Definition at line 841 of file TaskGraphInterfaces.h.
References FORCEINLINE.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/TaskGraphInterfaces.h