Unreal Engine 5.6 C++ API: FShader Class Reference
FShader Class Reference
A compiled shader and its parameter bindings.
#include "Shader.h"
Public Types
using CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
using FPermutationDomain = FShaderPermutationNone
using FPermutationParameters = FShaderPermutationParameters
using FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
using ShaderMetaType = FShaderType
using ShaderStatKeyType = FMemoryImageName
Public Member Functions
RENDERCORE_API FShader ()
Used to construct a shader for deserialization.
RENDERCORE_API FShader (const CompiledShaderInitializerType &Initializer)
Construct a shader from shader compiler output.
RENDERCORE_API ~FShader ()
RENDERCORE_API void DumpDebugInfo (const FShaderMapPointerTable &InPtrTable)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API const FShaderParametersMetadata * FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
uint32 GetCodeSize () const
EShaderFrequency GetFrequency () const
RENDERCORE_API const FSHAHash & GetHash () const
Returns the hash of the shader file that this shader was compiled with.
uint32 GetNumInstructions () const
uint32 GetNumTextureSamplers () const
RENDERCORE_API const FSHAHash & GetOutputHash () const
int32 GetResourceIndex () const
EShaderPlatform GetShaderPlatform () const
uint32 GetSortKey () const
Returns an identifier suitable for deterministic sorting of shaders between sessions.
const FShaderTarget GetTarget () const
FShaderType * GetType (const FPointerTableBase *InPointerTable) const
FShaderType * GetType (const FShaderMapPointerTable &InPointerTable) const
FShaderType * GetTypeUnfrozen () const
template<typename UniformBufferStructType>
const TShaderUniformBufferParameter< UniformBufferStructType > & GetUniformBufferParameter () const
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FHashedName SearchName) const
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FShaderParametersMetadata *SearchStruct) const
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
RENDERCORE_API const FSHAHash & GetVertexFactoryHash () const
FVertexFactoryType * GetVertexFactoryType (const FPointerTableBase *InPointerTable) const
FVertexFactoryType * GetVertexFactoryType (const FShaderMapPointerTable &InPointerTable) const
bool IsFrozen () const
LAYOUT_FIELD (FShaderParameterBindings, Bindings)
LAYOUT_FIELD (FShaderParameterMapInfo, ParameterMapInfo)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SetNumInstructions (uint32 Value)
Static Public Member Functions
static EShaderCompileJobPriority GetOverrideJobPriority ()
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
static ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId)
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
static const FShaderParametersMetadata * GetRootParametersMetadata ()
Returns the meta data for the root shader parameter struct.
static const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &)
Get shader binding layout used by the shader.
static void ModifyCompilationEnvironment (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
static bool ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap &InParameterMap, TArray< FString > &OutError)
Can be overridden by FShader subclasses to determine whether compilation is valid.
Protected Member Functions
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, UniformBufferParameterStructs)
LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter >, UniformBufferParameters)
LAYOUT_FIELD_EDITORONLY (FSHAHash, OutputHash)
Hash of the compiled output from this shader and the resulting parameter map.
LAYOUT_FIELD_EDITORONLY (FSHAHash, SourceHash)
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY (FSHAHash, VFSourceHash)
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
Private Member Functions
RENDERCORE_API void BuildParameterMapInfo (const TMap< FString, FParameterAllocation > &ParameterMap)
DECLARE_EXPORTED_TYPE_LAYOUT (FShader, RENDERCORE_API, NonVirtual)
LAYOUT_FIELD (FShaderTarget, Target)
Target platform and frequency.
LAYOUT_FIELD (int32, ResourceIndex)
Index of this shader within the FShaderMapResource.
LAYOUT_FIELD (TIndexedPtr< FShaderType >, Type)
LAYOUT_FIELD (TIndexedPtr< FVertexFactoryType >, VFType)
LAYOUT_FIELD (uint32, SortKey)
Truncated version of OutputHash, intended for sorting.
LAYOUT_FIELD_EDITORONLY (uint32, CodeSize)
Size of shader's compiled code.
LAYOUT_FIELD_EDITORONLY (uint32, NumInstructions)
The number of instructions the shader takes to execute.
LAYOUT_FIELD_EDITORONLY (uint32, NumTextureSamplers)
Number of texture samplers the shader uses.
Friends
class FShaderType
Detailed Description
A compiled shader and its parameter bindings.
Definition at line 845 of file Shader.h.
Member Typedef Documentation
CompiledShaderInitializerType
using FShader::CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
Definition at line 852 of file Shader.h.
FPermutationDomain
using FShader::FPermutationDomain = FShaderPermutationNone
Definition at line 850 of file Shader.h.
FPermutationParameters
using FShader::FPermutationParameters = FShaderPermutationParameters
Definition at line 851 of file Shader.h.
FShaderStatisticMap
using FShader::FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
Definition at line 855 of file Shader.h.
ShaderMetaType
using FShader::ShaderMetaType = FShaderType
Definition at line 853 of file Shader.h.
ShaderStatKeyType
using FShader::ShaderStatKeyType = FMemoryImageName
Definition at line 854 of file Shader.h.
Constructor & Destructor Documentation
FShader() [1/2]
RENDERCORE_API FShader::FShader ()
Used to construct a shader for deserialization.
This still needs to initialize members to safe values since FShaderType::GenerateSerializationHistory uses this constructor.
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT().
FShader() [2/2]
RENDERCORE_API FShader::FShader (const CompiledShaderInitializerType & Initializer)
Construct a shader from shader compiler output.
~FShader()
RENDERCORE_API FShader::~FShader ()
Member Function Documentation
BuildParameterMapInfo()
RENDERCORE_API void FShader::BuildParameterMapInfo (const TMap< FString, FParameterAllocation > & ParameterMap) private
DECLARE_EXPORTED_TYPE_LAYOUT()
FShader::DECLARE_EXPORTED_TYPE_LAYOUT (FShader , RENDERCORE_API , NonVirtual) private
References FShader().
DumpDebugInfo()
RENDERCORE_API void FShader::DumpDebugInfo (const FShaderMapPointerTable & InPtrTable)
Finalize()
RENDERCORE_API void FShader::Finalize (const FShaderMapResourceCode * Code)
FindAutomaticallyBoundUniformBufferStruct()
RENDERCORE_API const FShaderParametersMetadata * FShader::FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
GetCodeSize()
uint32 FShader::GetCodeSize () const inline
Definition at line 930 of file Shader.h.
GetFrequency()
EShaderFrequency FShader::GetFrequency () const inline
Definition at line 912 of file Shader.h.
References Target.
Referenced by FMaterialShaders::TryGetShader(), and FMaterialShaders::TryGetShader().
GetHash()
RENDERCORE_API const FSHAHash & FShader::GetHash () const
Returns the hash of the shader file that this shader was compiled with.
GetNumInstructions()
uint32 FShader::GetNumInstructions () const inline
Definition at line 928 of file Shader.h.
GetNumTextureSamplers()
uint32 FShader::GetNumTextureSamplers () const inline
Definition at line 929 of file Shader.h.
GetOutputHash()
RENDERCORE_API const FSHAHash & FShader::GetOutputHash () const
GetOverrideJobPriority()
EShaderCompileJobPriority FShader::GetOverrideJobPriority () inline static
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
This can only increase priority.
Definition at line 887 of file Shader.h.
References None.
GetRayTracingPayloadType()
ERayTracingPayloadType FShader::GetRayTracingPayloadType (const int32 PermutationId) inline static
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
This method is only called for raytracing shaders.
Definition at line 890 of file Shader.h.
GetResourceIndex()
int32 FShader::GetResourceIndex () const inline
Definition at line 910 of file Shader.h.
References checkSlow, and INDEX_NONE.
GetRootParametersMetadata()
const FShaderParametersMetadata * FShader::GetRootParametersMetadata () inline static
Returns the meta data for the root shader parameter struct.
Definition at line 988 of file Shader.h.
GetShaderBindingLayout()
const FShaderBindingLayout * FShader::GetShaderBindingLayout (const FShaderPermutationParameters &) inline static
Get shader binding layout used by the shader.
Definition at line 874 of file Shader.h.
GetShaderPlatform()
EShaderPlatform FShader::GetShaderPlatform () const inline
Definition at line 911 of file Shader.h.
References Target.
GetSortKey()
uint32 FShader::GetSortKey () const inline
Returns an identifier suitable for deterministic sorting of shaders between sessions.
Definition at line 900 of file Shader.h.
GetTarget()
const FShaderTarget FShader::GetTarget () const inline
Definition at line 913 of file Shader.h.
References Target.
GetType() [1/2]
FShaderType * FShader::GetType (const FPointerTableBase * InPointerTable) const inline
Definition at line 906 of file Shader.h.
References FShaderType.
GetType() [2/2]
FShaderType * FShader::GetType (const FShaderMapPointerTable & InPointerTable) const inline
Definition at line 905 of file Shader.h.
References FShaderType, and FShaderMapPointerTable::ShaderTypes.
Referenced by FShaderPipeline::GetShader().
GetTypeUnfrozen()
FShaderType * FShader::GetTypeUnfrozen () const inline
Definition at line 909 of file Shader.h.
References FShaderType.
GetUniformBufferParameter() [1/3]
template<typename UniformBufferStructType> const TShaderUniformBufferParameter< UniformBufferStructType > & FShader::GetUniformBufferParameter () const inline
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
Definition at line 936 of file Shader.h.
References FORCEINLINE_DEBUGGABLE, and GetUniformBufferParameter().
Referenced by GetUniformBufferParameter(), GetUniformBufferParameter(), and FGlobalShader::SetParameters().
GetUniformBufferParameter() [2/3]
const FShaderUniformBufferParameter & FShader::GetUniformBufferParameter (const FHashedName SearchName) const inline
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
Definition at line 951 of file Shader.h.
References Count, FORCEINLINE_DEBUGGABLE, INDEX_NONE, and TArrayView< InElementType, InSizeType >::Num().
GetUniformBufferParameter() [3/3]
const FShaderUniformBufferParameter & FShader::GetUniformBufferParameter (const FShaderParametersMetadata * SearchStruct) const inline
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
Definition at line 943 of file Shader.h.
References FORCEINLINE_DEBUGGABLE, FShaderParametersMetadata::GetShaderVariableHashedName(), and GetUniformBufferParameter().
GetVertexFactoryHash()
RENDERCORE_API const FSHAHash & FShader::GetVertexFactoryHash () const
GetVertexFactoryType() [1/2]
FVertexFactoryType * FShader::GetVertexFactoryType (const FPointerTableBase * InPointerTable) const inline
Definition at line 908 of file Shader.h.
GetVertexFactoryType() [2/2]
FVertexFactoryType * FShader::GetVertexFactoryType (const FShaderMapPointerTable & InPointerTable) const inline
Definition at line 907 of file Shader.h.
References FShaderMapPointerTable::VFTypes.
IsFrozen()
bool FShader::IsFrozen () const inline
Definition at line 914 of file Shader.h.
LAYOUT_FIELD() [1/9]
FShader::LAYOUT_FIELD (FShaderParameterBindings , Bindings)
LAYOUT_FIELD() [2/9]
FShader::LAYOUT_FIELD (FShaderParameterMapInfo , ParameterMapInfo)
LAYOUT_FIELD() [3/9]
FShader::LAYOUT_FIELD (FShaderTarget , Target) private
Target platform and frequency.
References Target.
LAYOUT_FIELD() [4/9]
FShader::LAYOUT_FIELD (int32 , ResourceIndex) private
Index of this shader within the FShaderMapResource.
LAYOUT_FIELD() [5/9]
FShader::LAYOUT_FIELD (TIndexedPtr< FShaderType > , Type) private
LAYOUT_FIELD() [6/9]
FShader::LAYOUT_FIELD (TIndexedPtr< FVertexFactoryType > , VFType) private
LAYOUT_FIELD() [7/9]
FShader::LAYOUT_FIELD (TMemoryImageArray< FHashedName > , UniformBufferParameterStructs) protected
LAYOUT_FIELD() [8/9]
FShader::LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter > , UniformBufferParameters) protected
LAYOUT_FIELD() [9/9]
FShader::LAYOUT_FIELD (uint32 , SortKey) private
Truncated version of OutputHash, intended for sorting.
Not suitable for unique shader identification.
LAYOUT_FIELD_EDITORONLY() [1/6]
FShader::LAYOUT_FIELD_EDITORONLY (FSHAHash , OutputHash) protected
Hash of the compiled output from this shader and the resulting parameter map.
This is used to find a matching resource.
LAYOUT_FIELD_EDITORONLY() [2/6]
FShader::LAYOUT_FIELD_EDITORONLY (FSHAHash , SourceHash) protected
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY() [3/6]
FShader::LAYOUT_FIELD_EDITORONLY (FSHAHash , VFSourceHash) protected
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
LAYOUT_FIELD_EDITORONLY() [4/6]
FShader::LAYOUT_FIELD_EDITORONLY (uint32 , CodeSize) private
Size of shader's compiled code.
LAYOUT_FIELD_EDITORONLY() [5/6]
FShader::LAYOUT_FIELD_EDITORONLY (uint32 , NumInstructions) private
The number of instructions the shader takes to execute.
LAYOUT_FIELD_EDITORONLY() [6/6]
FShader::LAYOUT_FIELD_EDITORONLY (uint32 , NumTextureSamplers) private
Number of texture samplers the shader uses.
ModifyCompilationEnvironment()
void FShader::ModifyCompilationEnvironment (const FShaderPermutationParameters & , FShaderCompilerEnvironment &) inline static
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
Definition at line 871 of file Shader.h.
SaveShaderStableKeys()
RENDERCORE_API void FShader::SaveShaderStableKeys (const FShaderMapPointerTable & InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue & SaveKeyVal)
SetNumInstructions()
void FShader::SetNumInstructions (uint32 Value) inline
Definition at line 931 of file Shader.h.
References Value.
ShouldCompilePermutation()
bool FShader::ShouldCompilePermutation (const FShaderPermutationParameters &) inline static
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
Definition at line 877 of file Shader.h.
ShouldPrecachePermutation()
EShaderPermutationPrecacheRequest FShader::ShouldPrecachePermutation (const FShaderPermutationParameters & Parameters) inline static
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Definition at line 880 of file Shader.h.
References Precached.
ValidateCompiledResult()
bool FShader::ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap & InParameterMap, TArray< FString > & OutError) inline static
Can be overridden by FShader subclasses to determine whether compilation is valid.
Definition at line 883 of file Shader.h.
Friends And Related Symbol Documentation
FShaderType
friend class FShaderType friend
Definition at line 847 of file Shader.h.
References FShaderType.
Referenced by FShaderType, GetType(), GetType(), and GetTypeUnfrozen().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h