Unreal Engine 5.6 C++ API: FUObjectAnnotationSparseBool Class Reference
FUObjectAnnotationSparseBool Class Reference
FUObjectAnnotationSparseBool is a specialization of FUObjectAnnotationSparse for bools, slow, temporary, editor only, external or other low priority bools about UObjects.
#include "UObjectAnnotation.h"
Public Member Functions
FORCEINLINE void Clear (const UObjectBase *Object)
Removes an annotation from the annotation list.
FORCEINLINE void ClearAll ()
Removes all bool annotations.
FORCEINLINE bool Get (const UObjectBase *Object)
Return the bool annotation associated with a uobject.
FORCEINLINE int32 Num () const
FORCEINLINE void Reserve (int32 ExpectedNumElements)
Reserves memory for the annotation map for the specified number of elements, used to avoid reallocations.
FORCEINLINE void Set (const UObjectBase *Object)
Sets this bool annotation to true for this object.
Additional Inherited Members
Private Member Functions inherited from FUObjectAnnotationSparse< FBoolAnnotation, true >
FUObjectAnnotationSparse ()
Constructor, initializes to nothing.
virtual ~FUObjectAnnotationSparse ()
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
void AddAnnotation (const UObjectBase *Object, FBoolAnnotation &&Annotation)
Add an annotation to the annotation list.
virtual SIZE_T GetAllocatedSize () const override
Returns the size of heap memory allocated internally by this listener.
FBoolAnnotation GetAndRemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list and returns the annotation if it had one.
FORCEINLINE FBoolAnnotation GetAnnotation (const UObjectBase *Object)
Return the annotation associated with a uobject.
const TMap< const UObjectBase *, FBoolAnnotation > & GetAnnotationMap () const
Return the annotation map.
virtual void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index) override
Interface for FUObjectAllocator::FUObjectDeleteListener.
virtual void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list.
void Reserve (int32 ExpectedNumElements)
Reserves memory for the annotation map for the specified number of elements, used to avoid reallocations.
Private Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Private Attributes inherited from FUObjectAnnotationSparse< FBoolAnnotation, true >
FTransactionallySafeRWLock AnnotationCacheCritical
const UObjectBase * AnnotationCacheKey
Key for a one-item cache of the last lookup into AnnotationMap.
FBoolAnnotation AnnotationCacheValue
Value for a one-item cache of the last lookup into AnnotationMap.
TMap< const UObjectBase *, FBoolAnnotation > AnnotationMap
Map from live objects to an annotation.
FTransactionallySafeRWLock AnnotationMapCritical
Guards the annotation map, cache key and cache value.
Detailed Description
FUObjectAnnotationSparseBool is a specialization of FUObjectAnnotationSparse for bools, slow, temporary, editor only, external or other low priority bools about UObjects.
Todo
UE this should probably be reimplemented from scratch as a TSet instead of essentially a map to a value that is always true anyway.
Definition at line 563 of file UObjectAnnotation.h.
Member Function Documentation
Clear()
FORCEINLINE void FUObjectAnnotationSparseBool::Clear (const UObjectBase * Object) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 580 of file UObjectAnnotation.h.
References FORCEINLINE, Object, and FUObjectAnnotationSparse< FBoolAnnotation, true >::RemoveAnnotation().
ClearAll()
FORCEINLINE void FUObjectAnnotationSparseBool::ClearAll () inline
Removes all bool annotations.
Definition at line 589 of file UObjectAnnotation.h.
References FORCEINLINE, and FUObjectAnnotationSparse< FBoolAnnotation, true >::RemoveAllAnnotations().
Get()
FORCEINLINE bool FUObjectAnnotationSparseBool::Get (const UObjectBase * Object) inline
Return the bool annotation associated with a uobject.
Parameters
Object Object to return the bool annotation for
Definition at line 599 of file UObjectAnnotation.h.
References FORCEINLINE, FUObjectAnnotationSparse< FBoolAnnotation, true >::GetAnnotation(), FBoolAnnotation::Mark, and Object.
Num()
FORCEINLINE int32 FUObjectAnnotationSparseBool::Num () const inline
Definition at line 612 of file UObjectAnnotation.h.
References FORCEINLINE, FUObjectAnnotationSparse< FBoolAnnotation, true >::GetAnnotationMap(), and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num().
Reserve()
FORCEINLINE void FUObjectAnnotationSparseBool::Reserve (int32 ExpectedNumElements) inline
Reserves memory for the annotation map for the specified number of elements, used to avoid reallocations.
Definition at line 607 of file UObjectAnnotation.h.
References FORCEINLINE, and FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::Reserve().
Set()
FORCEINLINE void FUObjectAnnotationSparseBool::Set (const UObjectBase * Object) inline
Sets this bool annotation to true for this object.
Parameters
Object Object to annotate.
Definition at line 571 of file UObjectAnnotation.h.
References FUObjectAnnotationSparse< FBoolAnnotation, true >::AddAnnotation(), FORCEINLINE, and Object.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectAnnotation.h