Unreal Engine 5.6 C++ API: FAnimGraphCommands Class Reference
FAnimGraphCommands Class Reference
Anim Graph Commands.
#include "AnimGraphCommands.h"
Public Member Functions
FAnimGraphCommands ()
virtual void RegisterCommands () override
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FUICommandInfo > AddBlendListPin
TSharedPtr< FUICommandInfo > ConvertToAimOffsetGraph
TSharedPtr< FUICommandInfo > ConvertToAimOffsetLookAt
TSharedPtr< FUICommandInfo > ConvertToAimOffsetSimple
TSharedPtr< FUICommandInfo > ConvertToBSEvaluator
TSharedPtr< FUICommandInfo > ConvertToBSGraph
TSharedPtr< FUICommandInfo > ConvertToBSPlayer
TSharedPtr< FUICommandInfo > ConvertToPoseBlender
TSharedPtr< FUICommandInfo > ConvertToPoseByName
TSharedPtr< FUICommandInfo > ConvertToSeqEvaluator
TSharedPtr< FUICommandInfo > ConvertToSeqPlayer
TSharedPtr< FUICommandInfo > HideUnboundPropertyPins
TSharedPtr< FUICommandInfo > OpenRelatedAsset
TSharedPtr< FUICommandInfo > RemoveBlendListPin
TSharedPtr< FUICommandInfo > SelectBone
TSharedPtr< FUICommandInfo > TogglePoseWatch
Additional Inherited Members
Static Public Member Functions inherited from TCommands< FAnimGraphCommands >
static FAnimGraphCommands & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FAnimGraphCommands >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FAnimGraphCommands >
static TWeakPtr< FAnimGraphCommands > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Anim Graph Commands.
Definition at line 17 of file AnimGraphCommands.h.
Constructor & Destructor Documentation
FAnimGraphCommands()
FAnimGraphCommands::FAnimGraphCommands () inline
Definition at line 20 of file AnimGraphCommands.h.
References FAnimGraphCommands(), TCommands< FAnimGraphCommands >::TCommands(), NSLOCTEXT, and TEXT.
Referenced by FAnimGraphCommands().
Member Function Documentation
RegisterCommands()
virtual void FAnimGraphCommands::RegisterCommands () override virtual
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Implements TCommands< FAnimGraphCommands >.
Field Documentation
AddBlendListPin
TSharedPtr< FUICommandInfo > FAnimGraphCommands::AddBlendListPin
Definition at line 38 of file AnimGraphCommands.h.
ConvertToAimOffsetGraph
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToAimOffsetGraph
Definition at line 53 of file AnimGraphCommands.h.
ConvertToAimOffsetLookAt
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToAimOffsetLookAt
Definition at line 51 of file AnimGraphCommands.h.
ConvertToAimOffsetSimple
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToAimOffsetSimple
Definition at line 52 of file AnimGraphCommands.h.
ConvertToBSEvaluator
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToBSEvaluator
Definition at line 46 of file AnimGraphCommands.h.
ConvertToBSGraph
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToBSGraph
Definition at line 48 of file AnimGraphCommands.h.
ConvertToBSPlayer
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToBSPlayer
Definition at line 47 of file AnimGraphCommands.h.
ConvertToPoseBlender
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToPoseBlender
Definition at line 56 of file AnimGraphCommands.h.
ConvertToPoseByName
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToPoseByName
Definition at line 57 of file AnimGraphCommands.h.
ConvertToSeqEvaluator
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToSeqEvaluator
Definition at line 42 of file AnimGraphCommands.h.
ConvertToSeqPlayer
TSharedPtr< FUICommandInfo > FAnimGraphCommands::ConvertToSeqPlayer
Definition at line 43 of file AnimGraphCommands.h.
HideUnboundPropertyPins
TSharedPtr<FUICommandInfo> FAnimGraphCommands::HideUnboundPropertyPins
Definition at line 33 of file AnimGraphCommands.h.
OpenRelatedAsset
TSharedPtr< FUICommandInfo > FAnimGraphCommands::OpenRelatedAsset
Definition at line 60 of file AnimGraphCommands.h.
RemoveBlendListPin
TSharedPtr< FUICommandInfo > FAnimGraphCommands::RemoveBlendListPin
Definition at line 39 of file AnimGraphCommands.h.
SelectBone
TSharedPtr< FUICommandInfo > FAnimGraphCommands::SelectBone
Definition at line 36 of file AnimGraphCommands.h.
TogglePoseWatch
TSharedPtr<FUICommandInfo> FAnimGraphCommands::TogglePoseWatch
Definition at line 30 of file AnimGraphCommands.h.
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/AnimGraphCommands.h