Unreal Engine 5.6 C++ API: UE::Geometry::TDistTriangle3Triangle3< Real > Class Template Reference
UE::Geometry::TDistTriangle3Triangle3< Real > Class Template Reference
Compute unsigned distance between 3D segment and 3D triangle.
#include "DistTriangle3Triangle3.h"
Public Member Functions
TDistTriangle3Triangle3 ()
TDistTriangle3Triangle3 (const TTriangle3< Real > &TriangleA, const TTriangle3< Real > &TriangleB)
Real ComputeResult ()
Real Get ()
Real GetSquared ()
void SetTriangle (int WhichTriangle, const TTriangle3< Real > &TriangleIn)
Data Fields
Real DistanceSquared = -1.0
TVector< Real > TriangleBaryCoords [2]
TVector< Real > TriangleClosest [2]
Private Attributes
TTriangle3< Real > Triangle [2]
Detailed Description
template<typename Real>
class UE::Geometry::TDistTriangle3Triangle3< Real >
Compute unsigned distance between 3D segment and 3D triangle.
Definition at line 26 of file DistTriangle3Triangle3.h.
Constructor & Destructor Documentation
TDistTriangle3Triangle3() [1/2]
template<typename Real> UE::Geometry::TDistTriangle3Triangle3< Real >::TDistTriangle3Triangle3 () inline
Definition at line 35 of file DistTriangle3Triangle3.h.
TDistTriangle3Triangle3() [2/2]
template<typename Real> UE::Geometry::TDistTriangle3Triangle3< Real >::TDistTriangle3Triangle3 (const TTriangle3< Real > & TriangleA, const TTriangle3< Real > & TriangleB) inline
Definition at line 38 of file DistTriangle3Triangle3.h.
Member Function Documentation
ComputeResult()
template<typename Real> Real UE::Geometry::TDistTriangle3Triangle3< Real >::ComputeResult () inline
Definition at line 60 of file DistTriangle3Triangle3.h.
Referenced by UE::Geometry::TDistTriangle3Triangle3< float >::Get(), and UE::Geometry::TDistTriangle3Triangle3< float >::GetSquared().
Get()
template<typename Real> Real UE::Geometry::TDistTriangle3Triangle3< Real >::Get () inline
Definition at line 51 of file DistTriangle3Triangle3.h.
GetSquared()
template<typename Real> Real UE::Geometry::TDistTriangle3Triangle3< Real >::GetSquared () inline
Definition at line 55 of file DistTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
SetTriangle()
template<typename Real> void UE::Geometry::TDistTriangle3Triangle3< Real >::SetTriangle (int WhichTriangle, const TTriangle3< Real > & TriangleIn) inline
Definition at line 44 of file DistTriangle3Triangle3.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
Field Documentation
DistanceSquared
template<typename Real> Real UE::Geometry::TDistTriangle3Triangle3< Real >::DistanceSquared = -1.0
Definition at line 30 of file DistTriangle3Triangle3.h.
Triangle
template<typename Real> TTriangle3<Real> UE::Geometry::TDistTriangle3Triangle3< Real >::Triangle[2] private
Definition at line 133 of file DistTriangle3Triangle3.h.
TriangleBaryCoords
template<typename Real> TVector<Real> UE::Geometry::TDistTriangle3Triangle3< Real >::TriangleBaryCoords[2]
Definition at line 32 of file DistTriangle3Triangle3.h.
TriangleClosest
template<typename Real> TVector<Real> UE::Geometry::TDistTriangle3Triangle3< Real >::TriangleClosest[2]
Definition at line 31 of file DistTriangle3Triangle3.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Distance/DistTriangle3Triangle3.h