Unreal Engine 5.6 C++ API: UMaterialBillboardComponent Class Reference
UMaterialBillboardComponent Class Reference
#include "MaterialBillboardComponent.h"
Private Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
Collect all the PSO precache data used by the material billboard component.
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
GENERATED_UCLASS_BODY () UPROPERTY() TArray< FMaterialSpriteElement > Elements
Current array of material billboard elements.
virtual UMaterialInterface * GetMaterial (int32 Index) const override
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
virtual void PostLoad () override
virtual void SetMaterial (int32 ElementIndex, class UMaterialInterface *Material) override
UFUNCTION () 1 void AddElement(class UMaterialInterface *Material
Adds an element to the sprite.
UFUNCTION () 1 void SetElements(const TArray< FMaterialSpriteElement > &NewElements)
Set all elements of this material billboard component.
Private Attributes
class UCurveFloat bool float BaseSizeX
class UCurveFloat bool float float BaseSizeY
class UCurveFloat bool bSizeIsInScreenSpace
class UCurveFloat * DistanceToOpacityCurve
class UCurveFloat bool float float class UCurveFloat * DistanceToSizeCurve
Detailed Description
Definition at line 61 of file MaterialBillboardComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UMaterialBillboardComponent::CalcBounds (const FTransform & LocalToWorld) const override private virtual
References CalcBounds().
Referenced by CalcBounds().
CollectPSOPrecacheData()
virtual void UMaterialBillboardComponent::CollectPSOPrecacheData (const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) override private virtual
Collect all the PSO precache data used by the material billboard component.
References CollectPSOPrecacheData().
Referenced by CollectPSOPrecacheData().
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UMaterialBillboardComponent::CreateSceneProxy () override private virtual
References CreateSceneProxy().
Referenced by CreateSceneProxy().
GENERATED_UCLASS_BODY()
UMaterialBillboardComponent::GENERATED_UCLASS_BODY () private
Current array of material billboard elements.
References Category, and UPROPERTY.
GetMaterial()
virtual UMaterialInterface * UMaterialBillboardComponent::GetMaterial (int32 Index) const override private virtual
References GetMaterial().
Referenced by GetMaterial().
GetMaterialPropertyPath()
virtual bool UMaterialBillboardComponent::GetMaterialPropertyPath (int32 ElementIndex, UObject *& OutOwner, FString & OutPropertyPath, FProperty *& OutProperty) override private virtual
GetUsedMaterials()
virtual void UMaterialBillboardComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override private virtual
References GetUsedMaterials().
Referenced by GetUsedMaterials().
PostLoad()
virtual void UMaterialBillboardComponent::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
SetMaterial()
virtual void UMaterialBillboardComponent::SetMaterial (int32 ElementIndex, class UMaterialInterface * Material) override private virtual
References Material, and SetMaterial().
Referenced by SetMaterial().
UFUNCTION() [1/2]
UMaterialBillboardComponent::UFUNCTION () private
Adds an element to the sprite.
References Category, Material, and UFUNCTION().
UFUNCTION() [2/2]
UMaterialBillboardComponent::UFUNCTION () const & private
Set all elements of this material billboard component.
References Category, and UFUNCTION().
Referenced by UFUNCTION(), and UFUNCTION().
Field Documentation
BaseSizeX
class UCurveFloat bool float UMaterialBillboardComponent::BaseSizeX private
Definition at line 79 of file MaterialBillboardComponent.h.
BaseSizeY
class UCurveFloat bool float float UMaterialBillboardComponent::BaseSizeY private
Definition at line 80 of file MaterialBillboardComponent.h.
bSizeIsInScreenSpace
class UCurveFloat bool UMaterialBillboardComponent::bSizeIsInScreenSpace private
Definition at line 78 of file MaterialBillboardComponent.h.
DistanceToOpacityCurve
class UCurveFloat* UMaterialBillboardComponent::DistanceToOpacityCurve private
Definition at line 77 of file MaterialBillboardComponent.h.
DistanceToSizeCurve
class UCurveFloat bool float float class UCurveFloat* UMaterialBillboardComponent::DistanceToSizeCurve private
Definition at line 81 of file MaterialBillboardComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/MaterialBillboardComponent.h