Unreal Engine 5.6 C++ API: FApp Class Reference
FApp Class Reference
Provides information about the application.
#include "App.h"
Public Member Functions
UE_DEPRECATED (4.25, "Please use SetQualifiedFrameTime") static void SetTimecodeAndFrameRate(FTimecode InTimecode
Sets the current timecode, and the frame rate to which it's relative.
Static Public Member Functions
static bool AllowUnattendedInput ()
Checks whether this application allows unattended input.
static FORCEINLINE void AuthorizeUser (const FString &UserName)
Add the specified user to the list of authorized session users.
static FORCEINLINE bool CanEverRender ()
Checks whether this application can render anything.
static FORCEINLINE bool CanEverRenderAudio ()
Checks whether this application can render audio.
static FORCEINLINE bool CanEverRenderOrProduceRenderData ()
Checks whether this application can render anything or produce a derived data needed for rednering.
static FORCEINLINE void DenyAllUsers ()
Removes all authorized users.
static FORCEINLINE void DenyUser (const FString &UserName)
Remove the specified user from the list of authorized session users.
static FString GetBranchName ()
Gets the name of the version control branch that this application was built from.
static EBuildConfiguration GetBuildConfiguration ()
Gets the application's build configuration, i.e.
static FString GetBuildDate ()
Gets the date at which this application was built.
static EBuildTargetType GetBuildTargetType ()
Gets the target type of the current application (eg.
static const TCHAR * GetBuildURL ()
static const TCHAR * GetBuildVersion ()
static FORCEINLINE TOptional< FQualifiedFrameTime > GetCurrentFrameTime ()
Gets a frame number generated by the engine's timecode provider.
static FORCEINLINE double GetCurrentTime ()
Gets current time in seconds.
static FORCEINLINE double GetDeltaTime ()
Gets time delta in seconds.
static int32 GetEngineIsPromotedBuild ()
Gets the value of ENGINE_IS_PROMOTED_BUILD.
static FString GetEpicProductIdentifier ()
Gets the identifier for the unreal engine.
static const TCHAR * GetExecutingJobURL ()
static FORCEINLINE double GetFixedDeltaTime ()
Gets time step in seconds if a fixed delta time is wanted.
static FORCEINLINE double GetGameTime ()
Gets overall game time in seconds.
static FString GetGraphicsRHI ()
Gets the name of the graphics RHI currently in use.
static FORCEINLINE double GetIdleTime ()
Gets idle time in seconds.
static FORCEINLINE double GetIdleTimeOvershoot ()
Gets idle time overshoot in seconds (the time beyond the wait time we requested for the frame).
static FGuid GetInstanceId ()
Gets the globally unique identifier of this application instance.
static FString GetInstanceName ()
Gets the name of this application instance.
static bool GetIsWithDebugInfo ()
static FORCEINLINE double GetLastTime ()
Gets previous value of CurrentTime.
static FString GetName ()
Gets the name of the application, i.e.
static FORCEINLINE const TCHAR * GetProjectName ()
Gets the name of the current project.
static FORCEINLINE FGuid GetSessionId ()
Gets the identifier of the session that this application is part of.
static FORCEINLINE FString GetSessionName ()
Gets the name of the session that this application is part of, if any.
static const FCbObjectId & GetSessionObjectId ()
Gets the identifier of the session that this application is part of as a FCbObject.
static FORCEINLINE FString GetSessionOwner ()
Gets the name of the user who owns the session that this application is part of, if any.
static FTimecode GetTimecode ()
Convert the current frame time into a readable timecode.
static FFrameRate GetTimecodeFrameRate ()
Get the frame rate of the current frame time.
static float GetUnfocusedVolumeMultiplier ()
Helper function to get UnfocusedVolumeMultiplier from config and store so it's not retrieved every frame.
static FORCEINLINE float GetVolumeMultiplier ()
Get Volume Multiplier.
static FString GetZenStoreProjectId (FStringView SubProject=FStringView())
Gets the Zen store project id for the current application instance.
static bool HasFocus ()
Gets Focus, Indicates that the application should continue to render Audio and Video as if it had window focus, even though it may not.
static FORCEINLINE bool HasProjectName ()
Reports if the project name has been set.
static FORCEINLINE bool HasVRFocus ()
Gets VRFocus, which indicates that the application should continue to render Audio and Video as if it had window focus, even though it may not.
static void InitializeSession ()
Initializes the application session.
static void InvalidateCurrentFrameTime ()
Invalidate the current frame time.
static FORCEINLINE bool IsAudioMuted ()
Checks whether this application should mute the audio output (-muteaudio) This is a safer alternative to -nosound for users who want to mute the audio of the game but keep the game rendering sound.
static FORCEINLINE bool IsAuthorizedUser (const FString &UserName)
Check whether the specified user is authorized to interact with this session.
static FORCEINLINE bool IsBenchmarking ()
Checks whether application is in benchmark mode.
static bool IsEngineInstalled ()
Checks whether the engine components of this application have been installed.
static FORCEINLINE bool IsGame ()
Checks whether this application is a game.
static bool IsInstalled ()
Checks whether this application has been installed.
static bool IsMultithreadServer ()
Returns if the application is a dedicated server and wants to be multi-threaded.
static FORCEINLINE bool IsProjectNameEmpty ()
Reports if the project name is empty.
static FORCEINLINE bool IsStandalone ()
Checks whether this is a standalone application.
static FORCEINLINE bool IsThisInstance (const FGuid &InInstanceId)
Check whether the given instance ID identifies this instance.
static bool IsUnattended ()
Checks whether this application runs unattended.
static void PrintStartupLogMessages ()
static void SetBenchmarking (bool bVal)
Sets application benchmarking mode.
static void SetCurrentFrameTime (FQualifiedFrameTime InFrameTime)
Sets the current frame time.
static void SetCurrentTime (double Seconds)
Sets current time in seconds.
static void SetDebugGame (bool bIsDebugGame)
For development configurations, sets whether the application should load DebugGame game modules.
static void SetDeltaTime (double Seconds)
Sets time delta in seconds.
static void SetFixedDeltaTime (double Seconds)
Sets time step in seconds if a fixed delta time is wanted.
static void SetGameTime (double Seconds)
Sets overall game time in seconds.
static void SetGraphicsRHI (FString RHIString)
Sets the Graphics RHI currently in use.
static void SetHasFocusFunction (bool(*InHasFocusFunction)())
Sets HasFocus, which is a function that indicates that the application window has focus.
static void SetHasVRFocus (bool bInHasVRFocus)
Sets VRFocus, which indicates that the application should continue to render Audio and Video as if it had window focus, even though it may not.
static void SetIdleTime (double Seconds)
Sets idle time in seconds.
static void SetIdleTimeOvershoot (double Seconds)
Sets idle time overshoot in seconds (the time beyond the wait time we requested for the frame).
static FORCEINLINE void SetProjectName (const TCHAR *InProjectName)
Sets the name of the current project.
static FORCEINLINE void SetSessionName (const FString &NewName)
Set a new session name.
static FORCEINLINE void SetSessionOwner (const FString &NewOwner)
Set a new session owner.
static void SetUnfocusedVolumeMultiplier (float InVolumeMultiplier)
Sets the Unfocused Volume Multiplier.
static void SetUseFixedTimeStep (bool bVal)
Enables or disabled usage of fixed time step.
static void SetUseVRFocus (bool bInUseVRFocus)
Sets if VRFocus should be used.
static FORCEINLINE void SetVolumeMultiplier (float InVolumeMultiplier)
Set Volume Multiplier.
static bool ShouldUseThreadingForPerformance ()
Checks whether the application should run multi-threaded for performance critical features.
static void UpdateLastTime ()
Updates Last time to CurrentTime.
static bool UseFixedTimeStep ()
Gets whether we want to use a fixed time step or not.
static FORCEINLINE bool UseVRFocus ()
Gets if VRFocus should be used.
Data Fields
FFrameRate InTimecodeFrameRate
Static Public Attributes
static bool bUseFixedSeed
Static Private Attributes
static bool bHasVRFocus
Holds a flag indicating if app has focus in side the VR headset.
static bool bIsBenchmarking
Holds a flag Whether we are in benchmark mode or not.
static bool bIsDebugGame
The current build configuration.
static bool bUseFixedTimeStep
Holds a flag whether we want to use a fixed time step or not.
static bool bUseVRFocus
Holds a flag indicating if VRFocus should be used.
static TOptional< FQualifiedFrameTime > CurrentFrameTime
Holds the current frame time and framerate.
static std::atomic< double > CurrentTime
Holds current time.
static std::atomic< double > DeltaTime
Holds current delta time in seconds.
static std::atomic< double > FixedDeltaTime
Holds time step if a fixed delta time is wanted.
static std::atomic< double > GameTime
Holds overall game time.
static FString GraphicsRHI
Holds the name the graphics RHI currently in use.
static bool(* HasFocusFunction)()
Holds a function address that can indicate if application has focus.
static std::atomic< double > IdleTime
Holds time we spent sleeping in UpdateTimeAndHandleMaxTickRate() if our frame time was smaller than one allowed by target FPS.
static std::atomic< double > IdleTimeOvershoot
Holds the amount of IdleTime that was LONGER than we tried to sleep.
static std::atomic< double > LastTime
Holds previous value of CurrentTime.
static FGuid SessionId
Holds the session identifier.
static FString SessionName
Holds the session name.
static FString SessionOwner
Holds the name of the user that launched session.
static TArray< FString > SessionUsers
List of authorized session users.
static bool Standalone
Holds a flag indicating whether this is a standalone session.
static float UnfocusedVolumeMultiplier
Read from config to define the volume when app loses focus.
static float VolumeMultiplier
Use to affect the app volume when it loses focus.
Detailed Description
Provides information about the application.
Definition at line 34 of file App.h.
Member Function Documentation
AllowUnattendedInput()
bool FApp::AllowUnattendedInput () static
Checks whether this application allows unattended input.
Unattended applications usually are unable to receive user input. This method can be used to determine whether to allow input modules to initialize when unattended.
Returns
true if the application allows unattended input, false otherwise.
AuthorizeUser()
FORCEINLINE void FApp::AuthorizeUser (const FString & UserName) inline static
Add the specified user to the list of authorized session users.
Parameters
UserName The name of the user to add.
See also
DenyUser, DenyAllUsers, IsAuthorizedUser
Definition at line 215 of file App.h.
References FORCEINLINE, and SessionUsers.
CanEverRender()
FORCEINLINE bool FApp::CanEverRender () inline static
Checks whether this application can render anything.
Certain application types never render, while for others this behavior may be controlled by switching to NullRHI. This can be used for decisions like omitting code paths that make no sense on servers or games running in headless mode (e.g. automated tests).
Returns
true if the application can render, false otherwise.
Definition at line 400 of file App.h.
References INLINE_CANEVERRENDER, IsAllowCommandletRendering(), IsRunningCommandlet(), IsRunningDedicatedServer(), FParse::Param(), TEXT, and USE_NULL_RHI.
Referenced by CanEverRenderOrProduceRenderData(), FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Execute(), and FAsyncAddPrimitiveQueue::Tick().
CanEverRenderAudio()
FORCEINLINE bool FApp::CanEverRenderAudio () inline static
Checks whether this application can render audio.
Certain application types produce sound, while for others this can be controlled via the -nosound cmdline. This can be used for decisions like omitting code paths that make no sense on servers or games running in headless mode (e.g. automated tests).
Returns
true if the application can render audio, false otherwise.
Definition at line 431 of file App.h.
References INLINE_CANEVERRENDER, IsAllowCommandletAudio(), IsBenchmarking(), IsRunningCommandlet(), IsRunningDedicatedServer(), FParse::Param(), and TEXT.
CanEverRenderOrProduceRenderData()
FORCEINLINE bool FApp::CanEverRenderOrProduceRenderData () inline static
Checks whether this application can render anything or produce a derived data needed for rednering.
Certain application types never render, but produce DDC used during rendering and as such need to step into some rendering paths.
A meaningful distinction from FApp::CanEverRender() is that commandlets like cooker will have FApp::CanEverRender() == false, but FApp::CanEverRenderOrProduceRenderData() == true. As such, this function can be used to guard paths that e.g. load assets' render data.
Returns
true if the application can render, false otherwise.
Definition at line 419 of file App.h.
References CanEverRender(), and INLINE_CANEVERRENDER.
DenyAllUsers()
FORCEINLINE void FApp::DenyAllUsers () inline static
Removes all authorized users.
See also
AuthorizeUser, DenyUser, IsAuthorizedUser
Definition at line 225 of file App.h.
References FORCEINLINE, and SessionUsers.
DenyUser()
FORCEINLINE void FApp::DenyUser (const FString & UserName) inline static
Remove the specified user from the list of authorized session users.
Parameters
UserName The name of the user to remove.
See also
AuthorizeUser, DenyAllUsers, IsAuthorizedUser
Definition at line 236 of file App.h.
References FORCEINLINE, and SessionUsers.
GetBranchName()
FString FApp::GetBranchName () static
Gets the name of the version control branch that this application was built from.
Returns
The branch name.
GetBuildConfiguration()
EBuildConfiguration FApp::GetBuildConfiguration () static
Gets the application's build configuration, i.e.
Debug or Shipping.
Returns
The build configuration.
GetBuildDate()
FString FApp::GetBuildDate () static
Gets the date at which this application was built.
Returns
Build date string.
GetBuildTargetType()
EBuildTargetType FApp::GetBuildTargetType () static
Gets the target type of the current application (eg.
client, server, etc...)
Returns
The build target type
GetBuildURL()
const TCHAR * FApp::GetBuildURL () static
GetBuildVersion()
const TCHAR * FApp::GetBuildVersion () static
GetCurrentFrameTime()
FORCEINLINE TOptional< FQualifiedFrameTime > FApp::GetCurrentFrameTime () inline static
Gets a frame number generated by the engine's timecode provider.
The current frame time is used to generate a timecode value. The optional will be false if no timecode provider was set or is not in a synchronized state.
Returns
the current frame time.
Definition at line 726 of file App.h.
References CurrentFrameTime, and FORCEINLINE.
GetCurrentTime()
FORCEINLINE double FApp::GetCurrentTime () inline static
Gets current time in seconds.
Returns
Current time in seconds.
Definition at line 591 of file App.h.
References CurrentTime, and FORCEINLINE.
Referenced by SetTextureParameter().
GetDeltaTime()
FORCEINLINE double FApp::GetDeltaTime () inline static
Gets time delta in seconds.
Returns
Time delta in seconds.
Definition at line 628 of file App.h.
References DeltaTime, and FORCEINLINE.
GetEngineIsPromotedBuild()
int32 FApp::GetEngineIsPromotedBuild () static
Gets the value of ENGINE_IS_PROMOTED_BUILD.
GetEpicProductIdentifier()
FString FApp::GetEpicProductIdentifier () static
Gets the identifier for the unreal engine.
GetExecutingJobURL()
const TCHAR * FApp::GetExecutingJobURL () static
GetFixedDeltaTime()
FORCEINLINE double FApp::GetFixedDeltaTime () inline static
Gets time step in seconds if a fixed delta time is wanted.
Returns
Time step in seconds for fixed delta time.
Definition at line 547 of file App.h.
References FixedDeltaTime, and FORCEINLINE.
GetGameTime()
FORCEINLINE double FApp::GetGameTime () inline static
Gets overall game time in seconds.
Returns
Overall game time in seconds.
Definition at line 668 of file App.h.
References FORCEINLINE, and GameTime.
GetGraphicsRHI()
FString FApp::GetGraphicsRHI () static
Gets the name of the graphics RHI currently in use.
Returns
name of Graphics RHI
GetIdleTime()
FORCEINLINE double FApp::GetIdleTime () inline static
Gets idle time in seconds.
Returns
Idle time in seconds.
Definition at line 648 of file App.h.
References FORCEINLINE, and IdleTime.
GetIdleTimeOvershoot()
FORCEINLINE double FApp::GetIdleTimeOvershoot () inline static
Gets idle time overshoot in seconds (the time beyond the wait time we requested for the frame).
Only valid when IdleTime is > 0.
Returns
Idle time in seconds.
Definition at line 688 of file App.h.
References FORCEINLINE, and IdleTimeOvershoot.
GetInstanceId()
FGuid FApp::GetInstanceId () static
Gets the globally unique identifier of this application instance.
Every running instance of the engine has a globally unique instance identifier that can be used to identify it from anywhere on the network.
Returns
Instance identifier, or an invalid GUID if there is no local instance.
See also
GetSessionId
Referenced by IsThisInstance().
GetInstanceName()
FString FApp::GetInstanceName () inline static
Gets the name of this application instance.
By default, the instance name is a combination of the computer name and process ID.
Returns
Instance name string.
Definition at line 266 of file App.h.
References FAndroidPlatformProcess::ComputerName(), FAndroidPlatformProcess::GetCurrentProcessId(), and TEXT.
GetIsWithDebugInfo()
bool FApp::GetIsWithDebugInfo () static
GetLastTime()
FORCEINLINE double FApp::GetLastTime () inline static
Gets previous value of CurrentTime.
Returns
Previous value of CurrentTime.
Definition at line 611 of file App.h.
References FORCEINLINE, and LastTime.
GetName()
FString FApp::GetName () inline static
Gets the name of the application, i.e.
"UE" or "Rocket".
Todo
need better application name discovery. this is quite horrible and may not work on future platforms.
Returns
Application name string.
Definition at line 137 of file App.h.
References FAndroidPlatformProcess::ExecutableName(), and TEXT.
GetProjectName()
FORCEINLINE const TCHAR * FApp::GetProjectName () inline static
Gets the name of the current project.
Returns
The project name.
Definition at line 126 of file App.h.
References FORCEINLINE, and GInternalProjectName.
GetSessionId()
FORCEINLINE FGuid FApp::GetSessionId () inline static
Gets the identifier of the session that this application is part of.
A session is group of applications that were launched and logically belong together. For example, when starting a new session in UFE that launches a game on multiple devices, all engine instances running on those devices will have the same session identifier. Conversely, sessions that were launched separately will have different session identifiers.
Returns
Session identifier, or an invalid GUID if there is no local instance.
See also
GetInstanceId
Definition at line 282 of file App.h.
References FORCEINLINE, and SessionId.
GetSessionName()
FORCEINLINE FString FApp::GetSessionName () inline static
Gets the name of the session that this application is part of, if any.
Returns
Session name string.
Definition at line 300 of file App.h.
References FORCEINLINE, and SessionName.
GetSessionObjectId()
const FCbObjectId & FApp::GetSessionObjectId () static
Gets the identifier of the session that this application is part of as a FCbObject.
Returns
Session identifier
See also
GetSessionId
GetSessionOwner()
FORCEINLINE FString FApp::GetSessionOwner () inline static
Gets the name of the user who owns the session that this application is part of, if any.
If this application is part of a session that was launched from UFE, this function will return the name of the user that launched the session. If this application is not part of a session, this function will return the name of the local user account under which the application is running.
Returns
Name of session owner.
Definition at line 315 of file App.h.
References FORCEINLINE, and SessionOwner.
GetTimecode()
FTimecode FApp::GetTimecode () static
Convert the current frame time into a readable timecode.
If the current frame time is not set, the timecode value will be defaulted.
Returns
the current timecode.
GetTimecodeFrameRate()
FFrameRate FApp::GetTimecodeFrameRate () static
Get the frame rate of the current frame time.
If the current frame time is not set, the frame rate value will be defaulted.
Returns
the current timecode frame rate.
GetUnfocusedVolumeMultiplier()
float FApp::GetUnfocusedVolumeMultiplier () static
Helper function to get UnfocusedVolumeMultiplier from config and store so it's not retrieved every frame.
Returns
Volume multiplier to use when app loses focus
GetVolumeMultiplier()
FORCEINLINE float FApp::GetVolumeMultiplier () inline static
Get Volume Multiplier.
Returns
Current volume multiplier
Definition at line 764 of file App.h.
References FORCEINLINE, and VolumeMultiplier.
GetZenStoreProjectId()
FString FApp::GetZenStoreProjectId (FStringView SubProject = FStringView()) static
Gets the Zen store project id for the current application instance.
Returns
Zen store project id.
HasFocus()
bool FApp::HasFocus () static
Gets Focus, Indicates that the application should continue to render Audio and Video as if it had window focus, even though it may not.
HasProjectName()
FORCEINLINE bool FApp::HasProjectName () inline static
Reports if the project name has been set.
Returns
true if the project name has been set
Definition at line 161 of file App.h.
References FORCEINLINE, GInternalProjectName, IsProjectNameEmpty(), TCString< TCHAR >::Stricmp(), and TEXT.
HasVRFocus()
FORCEINLINE bool FApp::HasVRFocus () inline static
Gets VRFocus, which indicates that the application should continue to render Audio and Video as if it had window focus, even though it may not.
Definition at line 817 of file App.h.
References bHasVRFocus, and FORCEINLINE.
InitializeSession()
void FApp::InitializeSession () static
Initializes the application session.
InvalidateCurrentFrameTime()
void FApp::InvalidateCurrentFrameTime () inline static
Invalidate the current frame time.
It will reset the TOptional.
Definition at line 754 of file App.h.
References CurrentFrameTime.
IsAudioMuted()
FORCEINLINE bool FApp::IsAudioMuted () inline static
Checks whether this application should mute the audio output (-muteaudio) This is a safer alternative to -nosound for users who want to mute the audio of the game but keep the game rendering sound.
Unless disabling the audio engine is the intention, this is a preferred method to mute the output as it avoid breaking audio analysis-dependent features (e.g. gameplay) and it prevents content creators from creating content with an incorrect performance and memory profile.
The mute is applied only in non-shipping builds and applied at the final step in the final output submix. Alternative method to do this it to enable the cvar, "au.MuteAudio 1"
Returns
true if the application will mute audio, false otherwise.
Definition at line 453 of file App.h.
References INLINE_CANEVERRENDER, FParse::Param(), and TEXT.
IsAuthorizedUser()
FORCEINLINE bool FApp::IsAuthorizedUser (const FString & UserName) inline static
Check whether the specified user is authorized to interact with this session.
Parameters
UserName The name of the user to check.
Returns
true if the user is authorized, false otherwise.
See also
AuthorizeUser, DenyUser, DenyAllUsers
Definition at line 332 of file App.h.
References FORCEINLINE, SessionOwner, SessionUsers, and FGenericPlatformProcess::UserName().
IsBenchmarking()
FORCEINLINE bool FApp::IsBenchmarking () inline static
Checks whether application is in benchmark mode.
Returns
true if application is in benchmark mode, false otherwise.
Definition at line 527 of file App.h.
References bIsBenchmarking, and FORCEINLINE.
Referenced by CanEverRenderAudio().
IsEngineInstalled()
bool FApp::IsEngineInstalled () static
Checks whether the engine components of this application have been installed.
In binary Unreal Engine releases, the engine can be installed while the game is not. The game IsInstalled() setting will take precedence over this flag.
To override, pass -engineinstalled or -enginenotinstalled on the command line.
Returns
true if the engine is installed, false otherwise.
IsGame()
FORCEINLINE bool FApp::IsGame () inline static
Checks whether this application is a game.
Returns true if a normal or PIE game is active (basically !GIsEdit or || GIsPlayInEditorWorld) This must NOT be accessed on threads other than the game thread! Use View->Family->EnginShowFlags.Game on the rendering thread.
Returns
true if the application is a game, false otherwise.
Definition at line 175 of file App.h.
References FORCEINLINE, GIsEditor, GIsPlayInEditorWorld, and IsRunningGame().
Referenced by MaterialInstance_Private::UpdateParameterSet_FullTraversal(), and MaterialInstance_Private::UpdateParameterSet_WithCachedData().
IsInstalled()
bool FApp::IsInstalled () static
Checks whether this application has been installed.
Non-server desktop shipping builds are assumed to be installed.
Installed applications may not write to the folder in which they exist since they are likely in a system folder (like "Program Files" in windows). Instead, they should write to the OS-specific user folder FPlatformProcess::UserDir() or application data folder FPlatformProcess::ApplicationSettingsDir() User Access Control info for windows Vista and newer: http://en.wikipedia.org/wiki/User_Account_Control
To run an "installed" build without installing, use the -Installed command line parameter. To run a "non-installed" desktop shipping build, use the -NotInstalled command line parameter.
Returns
true if the application is installed, false otherwise.
IsMultithreadServer()
bool FApp::IsMultithreadServer () static
Returns if the application is a dedicated server and wants to be multi-threaded.
IsProjectNameEmpty()
FORCEINLINE bool FApp::IsProjectNameEmpty () inline static
Reports if the project name is empty.
Returns
true if the project name is empty
Definition at line 189 of file App.h.
References FORCEINLINE, and GInternalProjectName.
Referenced by HasProjectName().
IsStandalone()
FORCEINLINE bool FApp::IsStandalone () inline static
Checks whether this is a standalone application.
An application is standalone if it has not been launched as part of a session from UFE. If an application was launched from UFE, it is part of a session and not considered standalone.
Returns
true if this application is standalone, false otherwise.
Definition at line 345 of file App.h.
References FORCEINLINE, and Standalone.
IsThisInstance()
FORCEINLINE bool FApp::IsThisInstance (const FGuid & InInstanceId) inline static
Check whether the given instance ID identifies this instance.
Parameters
InInstanceId The instance ID to check.
Returns
true if the ID identifies this instance, false otherwise.
Definition at line 356 of file App.h.
References FORCEINLINE, and GetInstanceId().
IsUnattended()
bool FApp::IsUnattended () static
Checks whether this application runs unattended.
Unattended applications are not monitored by anyone or are unable to receive user input. This method can be used to determine whether UI pop-ups or other dialogs should be shown.
Returns
true if the application runs unattended, false otherwise.
PrintStartupLogMessages()
void FApp::PrintStartupLogMessages () static
SetBenchmarking()
void FApp::SetBenchmarking (bool bVal) inline static
Sets application benchmarking mode.
Parameters
bVal True sets application in benchmark mode, false sets to non-benchmark mode.
Definition at line 537 of file App.h.
References bIsBenchmarking.
SetCurrentFrameTime()
void FApp::SetCurrentFrameTime (FQualifiedFrameTime InFrameTime) inline static
Sets the current frame time.
Parameters
InFrameTime - current frame time and frame rate.
Definition at line 748 of file App.h.
References CurrentFrameTime.
SetCurrentTime()
void FApp::SetCurrentTime (double Seconds) inline static
Sets current time in seconds.
Parameters
seconds - Time in seconds.
Definition at line 601 of file App.h.
References CurrentTime, and Seconds.
SetDebugGame()
void FApp::SetDebugGame (bool bIsDebugGame) static
For development configurations, sets whether the application should load DebugGame game modules.
Parameters
Whether we're running in debug game or not.
References bIsDebugGame.
SetDeltaTime()
void FApp::SetDeltaTime (double Seconds) inline static
Sets time delta in seconds.
Parameters
seconds Time in seconds.
Definition at line 638 of file App.h.
References DeltaTime, and Seconds.
SetFixedDeltaTime()
void FApp::SetFixedDeltaTime (double Seconds) inline static
Sets time step in seconds if a fixed delta time is wanted.
Parameters
seconds Time step in seconds for fixed delta time.
Definition at line 557 of file App.h.
References FixedDeltaTime, and Seconds.
SetGameTime()
void FApp::SetGameTime (double Seconds) inline static
Sets overall game time in seconds.
Parameters
seconds - Overall game time in seconds.
Definition at line 678 of file App.h.
References GameTime, and Seconds.
SetGraphicsRHI()
void FApp::SetGraphicsRHI (FString RHIString) static
Sets the Graphics RHI currently in use.
SetHasFocusFunction()
void FApp::SetHasFocusFunction (bool(* InHasFocusFunction)()) static
Sets HasFocus, which is a function that indicates that the application window has focus.
Parameters
InHasFocusFunction address of a function that can query the focus state, typically &FPlatformApplicationMisc::IsThisApplicationForeground
SetHasVRFocus()
void FApp::SetHasVRFocus (bool bInHasVRFocus) static
Sets VRFocus, which indicates that the application should continue to render Audio and Video as if it had window focus, even though it may not.
Parameters
bInVRFocus new VRFocus value
SetIdleTime()
void FApp::SetIdleTime (double Seconds) inline static
Sets idle time in seconds.
Parameters
seconds - Idle time in seconds.
Definition at line 658 of file App.h.
References IdleTime, and Seconds.
SetIdleTimeOvershoot()
void FApp::SetIdleTimeOvershoot (double Seconds) inline static
Sets idle time overshoot in seconds (the time beyond the wait time we requested for the frame).
Only valid when IdleTime is > 0.
Parameters
seconds - Idle time in seconds.
Definition at line 698 of file App.h.
References IdleTimeOvershoot, and Seconds.
SetProjectName()
FORCEINLINE void FApp::SetProjectName (const TCHAR * InProjectName) inline static
Sets the name of the current project.
Parameters
InProjectName Name of the current project.
Definition at line 199 of file App.h.
References FORCEINLINE, GInternalProjectName, TCString< TCHAR >::Strncpy(), TEXT, and UE_ARRAY_COUNT.
SetSessionName()
FORCEINLINE void FApp::SetSessionName (const FString & NewName) inline static
Set a new session name.
Parameters
NewName The new session name.
See also
SetSessionOwner
Definition at line 367 of file App.h.
References FORCEINLINE, and SessionName.
SetSessionOwner()
FORCEINLINE void FApp::SetSessionOwner (const FString & NewOwner) inline static
Set a new session owner.
Parameters
NewOwner The name of the new owner.
See also
SetSessionName
Definition at line 378 of file App.h.
References FORCEINLINE, and SessionOwner.
SetUnfocusedVolumeMultiplier()
void FApp::SetUnfocusedVolumeMultiplier (float InVolumeMultiplier) static
Sets the Unfocused Volume Multiplier.
SetUseFixedTimeStep()
void FApp::SetUseFixedTimeStep (bool bVal) inline static
Enables or disabled usage of fixed time step.
Parameters
whether to use fixed time step or not
Definition at line 581 of file App.h.
References bUseFixedTimeStep.
SetUseVRFocus()
void FApp::SetUseVRFocus (bool bInUseVRFocus) static
Sets if VRFocus should be used.
Parameters
bInUseVRFocus new bUseVRFocus value
SetVolumeMultiplier()
FORCEINLINE void FApp::SetVolumeMultiplier (float InVolumeMultiplier) inline static
Set Volume Multiplier.
Parameters
InVolumeMultiplier new volume multiplier
Definition at line 774 of file App.h.
References FORCEINLINE, and VolumeMultiplier.
ShouldUseThreadingForPerformance()
bool FApp::ShouldUseThreadingForPerformance () static
Checks whether the application should run multi-threaded for performance critical features.
This method is used for performance based threads (like rendering, task graph). This will not disable async IO or similar threads needed to disable hitching
Returns
true if this isn't a server, has more than one core, does not have a -onethread command line options, etc.
Referenced by FAsyncRegisterLevelContext::CreateInstance(), ENUM_CLASS_FLAGS(), PhysSingleThreadedMode(), and FMallocBinnedCommonUtils::Trim().
UE_DEPRECATED()
FApp::UE_DEPRECATED (4. 25, "Please use SetQualifiedFrameTime")
Sets the current timecode, and the frame rate to which it's relative.
Parameters
InTimecode - current timecode.
InTimecodeFrameRate - current timecode framerate.
UpdateLastTime()
void FApp::UpdateLastTime () inline static
Updates Last time to CurrentTime.
Definition at line 617 of file App.h.
References CurrentTime, and LastTime.
UseFixedTimeStep()
bool FApp::UseFixedTimeStep () inline static
Gets whether we want to use a fixed time step or not.
Returns
True if using fixed time step, false otherwise.
Definition at line 567 of file App.h.
References bUseFixedTimeStep.
UseVRFocus()
FORCEINLINE bool FApp::UseVRFocus () inline static
Gets if VRFocus should be used.
Definition at line 801 of file App.h.
References bUseVRFocus, and FORCEINLINE.
Field Documentation
bHasVRFocus
bool FApp::bHasVRFocus static private
Holds a flag indicating if app has focus in side the VR headset.
Definition at line 906 of file App.h.
Referenced by HasVRFocus().
bIsBenchmarking
bool FApp::bIsBenchmarking static private
Holds a flag Whether we are in benchmark mode or not.
Definition at line 867 of file App.h.
Referenced by IsBenchmarking(), and SetBenchmarking().
bIsDebugGame
bool FApp::bIsDebugGame static private
The current build configuration.
Definition at line 845 of file App.h.
Referenced by SetDebugGame().
bUseFixedSeed
bool FApp::bUseFixedSeed static
Definition at line 836 of file App.h.
bUseFixedTimeStep
bool FApp::bUseFixedTimeStep static private
Holds a flag whether we want to use a fixed time step or not.
Definition at line 870 of file App.h.
Referenced by SetUseFixedTimeStep(), and UseFixedTimeStep().
bUseVRFocus
bool FApp::bUseVRFocus static private
Holds a flag indicating if VRFocus should be used.
Definition at line 903 of file App.h.
Referenced by UseVRFocus().
CurrentFrameTime
TOptional<FQualifiedFrameTime> FApp::CurrentFrameTime static private
Holds the current frame time and framerate.
Definition at line 894 of file App.h.
Referenced by GetCurrentFrameTime(), InvalidateCurrentFrameTime(), and SetCurrentFrameTime().
CurrentTime
std::atomic<double> FApp::CurrentTime static private
Holds current time.
Definition at line 876 of file App.h.
Referenced by GetCurrentTime(), SetCurrentTime(), and UpdateLastTime().
DeltaTime
std::atomic<double> FApp::DeltaTime static private
Holds current delta time in seconds.
Definition at line 882 of file App.h.
Referenced by GetDeltaTime(), and SetDeltaTime().
FixedDeltaTime
std::atomic<double> FApp::FixedDeltaTime static private
Holds time step if a fixed delta time is wanted.
Definition at line 873 of file App.h.
Referenced by GetFixedDeltaTime(), and SetFixedDeltaTime().
GameTime
std::atomic<double> FApp::GameTime static private
Holds overall game time.
Definition at line 891 of file App.h.
Referenced by GetGameTime(), and SetGameTime().
GraphicsRHI
FString FApp::GraphicsRHI static private
Holds the name the graphics RHI currently in use.
Definition at line 858 of file App.h.
HasFocusFunction
bool(* FApp::HasFocusFunction) () static private
Holds a function address that can indicate if application has focus.
Definition at line 909 of file App.h.
IdleTime
std::atomic<double> FApp::IdleTime static private
Holds time we spent sleeping in UpdateTimeAndHandleMaxTickRate() if our frame time was smaller than one allowed by target FPS.
Definition at line 885 of file App.h.
Referenced by GetIdleTime(), and SetIdleTime().
IdleTimeOvershoot
std::atomic<double> FApp::IdleTimeOvershoot static private
Holds the amount of IdleTime that was LONGER than we tried to sleep.
The OS can't sleep the exact amount of time, so this measures that overshoot.
Definition at line 888 of file App.h.
Referenced by GetIdleTimeOvershoot(), and SetIdleTimeOvershoot().
InTimecodeFrameRate
FFrameRate FApp::InTimecodeFrameRate
Initial value:
{
        CurrentFrameTime = FQualifiedFrameTime(InTimecode, InTimecodeFrameRate)
Definition at line 738 of file App.h.
LastTime
std::atomic<double> FApp::LastTime static private
Holds previous value of CurrentTime.
Definition at line 879 of file App.h.
Referenced by GetLastTime(), and UpdateLastTime().
SessionId
FGuid FApp::SessionId static private
Holds the session identifier.
Definition at line 849 of file App.h.
Referenced by GetSessionId().
SessionName
FString FApp::SessionName static private
Holds the session name.
Definition at line 852 of file App.h.
Referenced by GetSessionName(), and SetSessionName().
SessionOwner
FString FApp::SessionOwner static private
Holds the name of the user that launched session.
Definition at line 855 of file App.h.
Referenced by GetSessionOwner(), IsAuthorizedUser(), and SetSessionOwner().
SessionUsers
TArray<FString> FApp::SessionUsers static private
List of authorized session users.
Definition at line 861 of file App.h.
Referenced by AuthorizeUser(), DenyAllUsers(), DenyUser(), and IsAuthorizedUser().
Standalone
bool FApp::Standalone static private
Holds a flag indicating whether this is a standalone session.
Definition at line 864 of file App.h.
Referenced by IsStandalone().
UnfocusedVolumeMultiplier
float FApp::UnfocusedVolumeMultiplier static private
Read from config to define the volume when app loses focus.
Definition at line 900 of file App.h.
VolumeMultiplier
float FApp::VolumeMultiplier static private
Use to affect the app volume when it loses focus.
Definition at line 897 of file App.h.
Referenced by GetVolumeMultiplier(), and SetVolumeMultiplier().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/App.h