Unreal Engine 5.6 C++ API: UBlackboardData Class Reference
UBlackboardData Class Reference
#include "BlackboardData.h"
Public Member Functions
DECLARE_MULTICAST_DELEGATE_OneParam (FBlackboardDataChanged, UBlackboardData *)
A delegate called on PostEditChangeProperty.
FORCEINLINE FBlackboard::FKey GetFirstKeyID () const
AIMODULE_API const FBlackboardEntry * GetKey (FBlackboard::FKey KeyID) const
AIMODULE_API FBlackboard::FKey GetKeyID (const FName &KeyName) const
AIMODULE_API FName GetKeyName (FBlackboard::FKey KeyID) const
const TArray< FBlackboardEntry > & GetKeys () const
AIMODULE_API TSubclassOf< UBlackboardKeyType > GetKeyType (FBlackboard::FKey KeyID) const
AIMODULE_API int32 GetNumKeys () const
FORCEINLINE bool HasSynchronizedKeys () const
AIMODULE_API bool IsChildOf (const UBlackboardData &OtherAsset) const
returns true if OtherAsset is somewhere up the parent chain of this asset.
AIMODULE_API bool IsKeyInstanceSynced (FBlackboard::FKey KeyID) const
bool IsRelatedTo (const UBlackboardData &OtherAsset) const
returns true if OtherAsset is equal to *this, or is it's parent, or *this is OtherAsset's parent
AIMODULE_API bool IsValid () const
bool IsValidKey (FBlackboard::FKey KeyID) const
virtual AIMODULE_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual AIMODULE_API void PostInitProperties () override
virtual AIMODULE_API void PostLoad () override
AIMODULE_API void PropagateKeyChangesToDerivedBlackboardAssets ()
AIMODULE_API void UpdateDeprecatedKeys ()
fix entries with deprecated key types
AIMODULE_API void UpdateIfHasSynchronizedKeys ()
AIMODULE_API void UpdateKeyIDs ()
forces update of FirstKeyID, which depends on parent chain
AIMODULE_API void UpdateParentKeys ()
updates parent key cache for editor
template<class T>
T * UpdatePersistentKey (const FName &KeyName)
updates persistent key with given name, depending on currently defined entries and parent chain
Static Public Attributes
static AIMODULE_API FBlackboardDataChanged OnBlackboardDataChanged
static AIMODULE_API FKeyUpdate OnUpdateKeys
delegate called for every loaded blackboard asset meant for adding game specific persistent keys
Protected Types
enum EKeyLookupMode { CheckParentKeys , DontCheckParentKeys }
Protected Member Functions
AIMODULE_API FBlackboard::FKey InternalGetKeyID (const FName &KeyName, EKeyLookupMode LookupMode) const
Protected Attributes
FBlackboard::FKey FirstKeyID
Private Member Functions
GENERATED_UCLASS_BODY () DECLARE_MULTICAST_DELEGATE_OneParam(FKeyUpdate
UPROPERTY () TArray< FBlackboardEntry > Keys
blackboard keys
UBlackboardData * UPROPERTY () TObjectPtr< UBlackboardData > Parent
parent blackboard (keys can be overridden)
Detailed Description
Definition at line 45 of file BlackboardData.h.
Member Enumeration Documentation
EKeyLookupMode
enum UBlackboardData::EKeyLookupMode protected
Enumerator
CheckParentKeys
DontCheckParentKeys
Definition at line 171 of file BlackboardData.h.
Member Function Documentation
DECLARE_MULTICAST_DELEGATE_OneParam()
UBlackboardData::DECLARE_MULTICAST_DELEGATE_OneParam (FBlackboardDataChanged , UBlackboardData *)
A delegate called on PostEditChangeProperty.
Can be used in editor to react to asset changes.
Referenced by GENERATED_UCLASS_BODY().
GENERATED_UCLASS_BODY()
UBlackboardData::GENERATED_UCLASS_BODY () private
References DECLARE_MULTICAST_DELEGATE_OneParam().
GetFirstKeyID()
FORCEINLINE FBlackboard::FKey UBlackboardData::GetFirstKeyID () const inline
Definition at line 87 of file BlackboardData.h.
References FirstKeyID, and FORCEINLINE.
GetKey()
AIMODULE_API const FBlackboardEntry * UBlackboardData::GetKey (FBlackboard::FKey KeyID) const
Returns
key data
GetKeyID()
AIMODULE_API FBlackboard::FKey UBlackboardData::GetKeyID (const FName & KeyName) const
Returns
key ID from name
GetKeyName()
AIMODULE_API FName UBlackboardData::GetKeyName (FBlackboard::FKey KeyID) const
Returns
name of key
GetKeys()
const TArray< FBlackboardEntry > & UBlackboardData::GetKeys () const inline
Definition at line 94 of file BlackboardData.h.
GetKeyType()
AIMODULE_API TSubclassOf< UBlackboardKeyType > UBlackboardData::GetKeyType (FBlackboard::FKey KeyID) const
Returns
class of value for given key
GetNumKeys()
AIMODULE_API int32 UBlackboardData::GetNumKeys () const
Returns
number of defined keys, including parent chain
Referenced by IsValidKey().
HasSynchronizedKeys()
FORCEINLINE bool UBlackboardData::HasSynchronizedKeys () const inline
Definition at line 70 of file BlackboardData.h.
References FORCEINLINE, and HasSynchronizedKeys().
Referenced by HasSynchronizedKeys().
InternalGetKeyID()
AIMODULE_API FBlackboard::FKey UBlackboardData::InternalGetKeyID (const FName & KeyName, EKeyLookupMode LookupMode) const protected
Returns
key ID from name
Referenced by UpdatePersistentKey().
IsChildOf()
AIMODULE_API bool UBlackboardData::IsChildOf (const UBlackboardData & OtherAsset) const
returns true if OtherAsset is somewhere up the parent chain of this asset.
Node that it will return false if *this == OtherAsset
Referenced by IsRelatedTo().
IsKeyInstanceSynced()
AIMODULE_API bool UBlackboardData::IsKeyInstanceSynced (FBlackboard::FKey KeyID) const
Returns
true if the key is instance synced
IsRelatedTo()
bool UBlackboardData::IsRelatedTo (const UBlackboardData & OtherAsset) const inline
returns true if OtherAsset is equal to *this, or is it's parent, or *this is OtherAsset's parent
Definition at line 163 of file BlackboardData.h.
References IsChildOf(), and Parent.
IsValid()
AIMODULE_API bool UBlackboardData::IsValid () const
Returns
true if blackboard keys are not conflicting with parent key chain
IsValidKey()
bool UBlackboardData::IsValidKey (FBlackboard::FKey KeyID) const inline
Definition at line 89 of file BlackboardData.h.
References GetNumKeys(), and FBlackboard::InvalidKey.
PostEditChangeProperty()
virtual AIMODULE_API void UBlackboardData::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual AIMODULE_API void UBlackboardData::PostInitProperties () override virtual
PostLoad()
virtual AIMODULE_API void UBlackboardData::PostLoad () override virtual
PropagateKeyChangesToDerivedBlackboardAssets()
AIMODULE_API void UBlackboardData::PropagateKeyChangesToDerivedBlackboardAssets ()
Referenced by UpdatePersistentKey().
UpdateDeprecatedKeys()
AIMODULE_API void UBlackboardData::UpdateDeprecatedKeys ()
fix entries with deprecated key types
UpdateIfHasSynchronizedKeys()
AIMODULE_API void UBlackboardData::UpdateIfHasSynchronizedKeys ()
UpdateKeyIDs()
AIMODULE_API void UBlackboardData::UpdateKeyIDs ()
forces update of FirstKeyID, which depends on parent chain
UpdateParentKeys()
AIMODULE_API void UBlackboardData::UpdateParentKeys ()
updates parent key cache for editor
UpdatePersistentKey()
template<class T> T * UBlackboardData::UpdatePersistentKey (const FName & KeyName) inline
updates persistent key with given name, depending on currently defined entries and parent chain
Returns
key type of newly created entry for further setup
Definition at line 110 of file BlackboardData.h.
References DontCheckParentKeys, FirstKeyID, InternalGetKeyID(), FBlackboard::InvalidKey, NewObject, Parent, and PropagateKeyChangesToDerivedBlackboardAssets().
UPROPERTY() [1/2]
UBlackboardData::UPROPERTY () private
blackboard keys
References Category.
UPROPERTY() [2/2]
UBlackboardData * UBlackboardData::UPROPERTY () private
parent blackboard (keys can be overridden)
References Category, Parent, Transient, and UPROPERTY().
Referenced by UPROPERTY().
Field Documentation
FirstKeyID
FBlackboard::FKey UBlackboardData::FirstKeyID protected
Returns
first ID for keys of this asset (parent keys goes first)
Definition at line 178 of file BlackboardData.h.
Referenced by GetFirstKeyID(), and UpdatePersistentKey().
OnBlackboardDataChanged
AIMODULE_API FBlackboardDataChanged UBlackboardData::OnBlackboardDataChanged static
Definition at line 141 of file BlackboardData.h.
OnUpdateKeys
AIMODULE_API FKeyUpdate UBlackboardData::OnUpdateKeys static
delegate called for every loaded blackboard asset meant for adding game specific persistent keys
Definition at line 146 of file BlackboardData.h.
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/BehaviorTree/BlackboardData.h