Unreal Engine 5.6 C++ API: FSetElementId Class Reference
FSetElementId Class Reference
Either NULL or an identifier for an element of a set.
#include "SetUtilities.h"
Public Member Functions
FORCEINLINE FSetElementId ()=default
Default constructor.
FORCEINLINE int32 AsInteger () const
FORCEINLINE bool IsValidId () const
Static Public Member Functions
static FORCEINLINE FSetElementId FromInteger (int32 Integer)
Private Member Functions
FORCEINLINE FSetElementId (int32 InIndex)
Initialization constructor.
Private Attributes
int32 Index = INDEX_NONE
The index of the element in the set's element array.
Friends
FORCEINLINE friend bool operator!= (const FSetElementId &A, const FSetElementId &B)
FORCEINLINE friend bool operator== (const FSetElementId &A, const FSetElementId &B)
Comparison operators.
Detailed Description
Either NULL or an identifier for an element of a set.
Used to differentiate between int as an element type and an index to a specific location
Definition at line 88 of file SetUtilities.h.
Constructor & Destructor Documentation
FSetElementId() [1/2]
FORCEINLINE FSetElementId::FSetElementId () default
Default constructor.
References FORCEINLINE.
Referenced by FromInteger(), operator!=, and operator==.
FSetElementId() [2/2]
FORCEINLINE FSetElementId::FSetElementId (int32 InIndex) inline explicit nodiscard private
Initialization constructor.
Definition at line 125 of file SetUtilities.h.
References FORCEINLINE, and Index.
Member Function Documentation
AsInteger()
FORCEINLINE int32 FSetElementId::AsInteger () const inline nodiscard
Definition at line 110 of file SetUtilities.h.
References FORCEINLINE, and Index.
Referenced by TSet< class UObject * >::DumpHashElements(), TSet< class UObject * >::Get(), TSet< class UObject * >::Get(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Get(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::Get(), TSet< class UObject * >::IsValidId(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::IsValidId(), TSet< class UObject * >::operator[](), TSet< class UObject * >::operator[](), TSet< class UObject * >::Remove(), TSet< class UObject * >::RemoveByIndex(), TSet< class UObject * >::RemoveImpl(), and TSet< class UObject * >::VerifyHashElementsKey().
FromInteger()
FORCEINLINE FSetElementId FSetElementId::FromInteger (int32 Integer) inline static nodiscard
Definition at line 115 of file SetUtilities.h.
References FSetElementId(), FORCEINLINE, and Integer.
Referenced by TScriptSet< FDefaultSetAllocator, FScriptSet >::AddNewElement(), TSet< class UObject * >::Emplace(), TSet< class UObject * >::EmplaceByHash(), TSet< class UObject * >::FindId(), TSet< class UObject * >::FindIdByHash(), TSet< InElementType, KeyFuncs, Allocator >::TBaseIterator< true, true >::GetId(), TSet< InElementType, KeyFuncs, Allocator >::TBaseKeyIterator< true >::GetId(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseIterator< true >::GetId(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TBaseReverseIterator< bConst >::GetId(), TSet< class UObject * >::LinkElement(), and TScriptSet< FDefaultSetAllocator, FScriptSet >::Rehash().
IsValidId()
FORCEINLINE bool FSetElementId::IsValidId () const inline nodiscard
Returns
a boolean value representing whether the id is NULL.
Definition at line 95 of file SetUtilities.h.
References FORCEINLINE, Index, and INDEX_NONE.
Referenced by TSet< class UObject * >::Dump(), TSet< class UObject * >::DumpHashElements(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::FindAndRemoveChecked(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::FindAndRemoveChecked(), TScriptSet< FDefaultSetAllocator, FScriptSet >::FindIndexImpl(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::RemoveAndCopyValue(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValue(), TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::RemoveAndCopyValueByHash(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::RemoveAndCopyValueByHash(), TScriptSet< FDefaultSetAllocator, FScriptSet >::RemoveAt(), TStripedMapBase< BucketCount, TMap< KeyType, ValueType, SetAllocator, KeyFuncs >, KeyType, ValueType, SetAllocator, KeyFuncs, LockingPolicy >::RemoveIf(), TSet< class UObject * >::RemoveImpl(), and TSet< class UObject * >::VerifyHashElementsKey().
Friends And Related Symbol Documentation
operator!=
FORCEINLINE friend bool operator!= (const FSetElementId & A, const FSetElementId & B) friend
Definition at line 105 of file SetUtilities.h.
References FSetElementId(), A, B, and FORCEINLINE.
operator==
FORCEINLINE friend bool operator== (const FSetElementId & A, const FSetElementId & B) friend
Comparison operators.
Definition at line 101 of file SetUtilities.h.
References FSetElementId(), A, B, and FORCEINLINE.
Field Documentation
Index
int32 FSetElementId::Index = INDEX_NONE private
The index of the element in the set's element array.
Definition at line 122 of file SetUtilities.h.
Referenced by FSetElementId(), AsInteger(), and IsValidId().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SetUtilities.h