Unreal Engine 5.6 C++ API: FArchive::FScopeSeekTo Class Reference
FArchive::FScopeSeekTo Class Reference
Seeks to and restores the position of an archive.
#include "Archive.h"
Public Member Functions
FScopeSeekTo (const FScopeSeekTo &)=delete
FScopeSeekTo (FArchive &InAr, int64 InPos)
~FScopeSeekTo ()
FScopeSeekTo & operator= (const FScopeSeekTo &)=delete
Private Attributes
FArchive & Ar
int64 SavedPos
Detailed Description
Seeks to and restores the position of an archive.
Definition at line 2292 of file Archive.h.
Constructor & Destructor Documentation
FScopeSeekTo() [1/2]
FArchive::FScopeSeekTo::FScopeSeekTo (FArchive & InAr, int64 InPos) inline
Definition at line 2295 of file Archive.h.
References FArchive::FArchive(), Ar, SavedPos, and FArchive::Tell().
Referenced by FScopeSeekTo(), and operator=().
~FScopeSeekTo()
FArchive::FScopeSeekTo::~FScopeSeekTo () inline
Definition at line 2302 of file Archive.h.
References Ar, and SavedPos.
FScopeSeekTo() [2/2]
FArchive::FScopeSeekTo::FScopeSeekTo (const FScopeSeekTo &) delete
References FScopeSeekTo().
Member Function Documentation
operator=()
FScopeSeekTo & FArchive::FScopeSeekTo::operator= (const FScopeSeekTo &) delete
References FScopeSeekTo().
Field Documentation
Ar
FArchive& FArchive::FScopeSeekTo::Ar private
Definition at line 2311 of file Archive.h.
Referenced by FScopeSeekTo(), and ~FScopeSeekTo().
SavedPos
int64 FArchive::FScopeSeekTo::SavedPos private
Definition at line 2312 of file Archive.h.
Referenced by FScopeSeekTo(), and ~FScopeSeekTo().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/Archive.h