Unreal Engine 5.6 C++ API: FIoDirectoryIndexHandle Class Reference
FIoDirectoryIndexHandle Class Reference
#include "IoDispatcher.h"
Public Member Functions
FIoDirectoryIndexHandle ()=default
bool IsValid () const
bool operator< (FIoDirectoryIndexHandle Other) const
bool operator== (FIoDirectoryIndexHandle Other) const
uint32 ToIndex () const
Static Public Member Functions
static FIoDirectoryIndexHandle FromIndex (uint32 Index)
static FIoDirectoryIndexHandle Invalid ()
static FIoDirectoryIndexHandle RootDirectory ()
Private Member Functions
FIoDirectoryIndexHandle (uint32 InHandle)
Private Attributes
uint32 Handle = InvalidHandle
Static Private Attributes
static constexpr uint32 InvalidHandle = ~uint32(0)
static constexpr uint32 RootHandle = 0
Friends
uint32 GetTypeHash (FIoDirectoryIndexHandle InHandle)
Detailed Description
Definition at line 396 of file IoDispatcher.h.
Constructor & Destructor Documentation
FIoDirectoryIndexHandle() [1/2]
FIoDirectoryIndexHandle::FIoDirectoryIndexHandle () default
Referenced by FromIndex(), GetTypeHash, Invalid(), operator<(), operator==(), and RootDirectory().
FIoDirectoryIndexHandle() [2/2]
FIoDirectoryIndexHandle::FIoDirectoryIndexHandle (uint32 InHandle) inline private
Definition at line 445 of file IoDispatcher.h.
References Handle.
Member Function Documentation
FromIndex()
FIoDirectoryIndexHandle FIoDirectoryIndexHandle::FromIndex (uint32 Index) inline static
Definition at line 429 of file IoDispatcher.h.
References FIoDirectoryIndexHandle().
Invalid()
FIoDirectoryIndexHandle FIoDirectoryIndexHandle::Invalid () inline static
Definition at line 439 of file IoDispatcher.h.
References FIoDirectoryIndexHandle(), and InvalidHandle.
IsValid()
bool FIoDirectoryIndexHandle::IsValid () const inline
Definition at line 404 of file IoDispatcher.h.
References Handle, and InvalidHandle.
operator<()
bool FIoDirectoryIndexHandle::operator< (FIoDirectoryIndexHandle Other) const inline
Definition at line 409 of file IoDispatcher.h.
References FIoDirectoryIndexHandle(), Handle, and Other.
operator==()
bool FIoDirectoryIndexHandle::operator== (FIoDirectoryIndexHandle Other) const inline
Definition at line 414 of file IoDispatcher.h.
References FIoDirectoryIndexHandle(), Handle, and Other.
RootDirectory()
FIoDirectoryIndexHandle FIoDirectoryIndexHandle::RootDirectory () inline static
Definition at line 434 of file IoDispatcher.h.
References FIoDirectoryIndexHandle(), and RootHandle.
ToIndex()
uint32 FIoDirectoryIndexHandle::ToIndex () const inline
Definition at line 424 of file IoDispatcher.h.
References Handle.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FIoDirectoryIndexHandle InHandle) friend
Definition at line 419 of file IoDispatcher.h.
References FIoDirectoryIndexHandle(), and Handle.
Field Documentation
Handle
uint32 FIoDirectoryIndexHandle::Handle = InvalidHandle private
Definition at line 448 of file IoDispatcher.h.
Referenced by FIoDirectoryIndexHandle(), GetTypeHash, IsValid(), operator<(), operator==(), and ToIndex().
InvalidHandle
uint32 FIoDirectoryIndexHandle::InvalidHandle = ~uint32(0) static constexpr private
Definition at line 398 of file IoDispatcher.h.
Referenced by Invalid(), and IsValid().
RootHandle
uint32 FIoDirectoryIndexHandle::RootHandle = 0 static constexpr private
Definition at line 399 of file IoDispatcher.h.
Referenced by RootDirectory().
The documentation for this class was generated from the following file:
Runtime/Core/Public/IO/IoDispatcher.h