Unreal Engine 5.6 C++ API: UE::FEncryptionKeyManager Class Reference
UE::FEncryptionKeyManager Class Reference
Manages a set of registered encryption key(s).
#include "EncryptionKeyManager.h"
Public Member Functions
FEncryptionKeyManager (const FEncryptionKeyManager &)=delete
FEncryptionKeyManager (FEncryptionKeyManager &&)=delete
~FEncryptionKeyManager ()
void AddKey (const FGuid &Id, const FAES::FAESKey &Key)
Add a new encryption key, ignored if the key already exist.
bool ContainsKey (const FGuid &Id) const
Returns whether the specified encrypton key exist or not.
DECLARE_MULTICAST_DELEGATE_TwoParams (FEncryptionKeyAddedDelegate, const FGuid &, const FAES::FAESKey &)
TMap< FGuid, FAES::FAESKey > GetAllKeys () const
Returns a map of all available keys.
FEncryptionKeyAddedDelegate & OnKeyAdded ()
Event triggered when a new key as been added.
FEncryptionKeyManager & operator= (const FEncryptionKeyManager &)=delete
FEncryptionKeyManager & operator= (FEncryptionKeyManager &&)=delete
bool TryGetKey (const FGuid &Id, FAES::FAESKey &OutKey) const
Try retrieve the encryption key for the specified key ID.
Static Public Member Functions
static FEncryptionKeyManager & Get ()
Returns the single instance of the key manager.
Private Member Functions
FEncryptionKeyManager ()
Private Attributes
FEncryptionKeyAddedDelegate KeyAdded
TMap< FGuid, FAES::FAESKey > Keys
FMutex Mutex
Detailed Description
Manages a set of registered encryption key(s).
Definition at line 18 of file EncryptionKeyManager.h.
Constructor & Destructor Documentation
FEncryptionKeyManager() [1/3]
UE::FEncryptionKeyManager::FEncryptionKeyManager (const FEncryptionKeyManager &) delete
References FEncryptionKeyManager().
Referenced by FEncryptionKeyManager(), FEncryptionKeyManager(), Get(), operator=(), and operator=().
FEncryptionKeyManager() [2/3]
UE::FEncryptionKeyManager::FEncryptionKeyManager (FEncryptionKeyManager &&) delete
References FEncryptionKeyManager().
~FEncryptionKeyManager()
UE::FEncryptionKeyManager::~FEncryptionKeyManager ()
References UE_API.
FEncryptionKeyManager() [3/3]
UE::FEncryptionKeyManager::FEncryptionKeyManager () private
References UE_API.
Member Function Documentation
AddKey()
void UE::FEncryptionKeyManager::AddKey (const FGuid & Id, const FAES::FAESKey & Key)
Add a new encryption key, ignored if the key already exist.
References Key, and UE_API.
ContainsKey()
bool UE::FEncryptionKeyManager::ContainsKey (const FGuid & Id) const
Returns whether the specified encrypton key exist or not.
References UE_API.
DECLARE_MULTICAST_DELEGATE_TwoParams()
UE::FEncryptionKeyManager::DECLARE_MULTICAST_DELEGATE_TwoParams (FEncryptionKeyAddedDelegate , const FGuid & , const FAES::FAESKey &)
Get()
FEncryptionKeyManager & UE::FEncryptionKeyManager::Get () static
Returns the single instance of the key manager.
References FEncryptionKeyManager(), and UE_API.
GetAllKeys()
TMap< FGuid, FAES::FAESKey > UE::FEncryptionKeyManager::GetAllKeys () const
Returns a map of all available keys.
References UE_API.
OnKeyAdded()
FEncryptionKeyAddedDelegate & UE::FEncryptionKeyManager::OnKeyAdded () inline
Event triggered when a new key as been added.
Definition at line 38 of file EncryptionKeyManager.h.
References KeyAdded.
operator=() [1/2]
FEncryptionKeyManager & UE::FEncryptionKeyManager::operator= (const FEncryptionKeyManager &) delete
References FEncryptionKeyManager().
operator=() [2/2]
FEncryptionKeyManager & UE::FEncryptionKeyManager::operator= (FEncryptionKeyManager &&) delete
References FEncryptionKeyManager().
TryGetKey()
bool UE::FEncryptionKeyManager::TryGetKey (const FGuid & Id, FAES::FAESKey & OutKey) const
Try retrieve the encryption key for the specified key ID.
References UE_API.
Field Documentation
KeyAdded
FEncryptionKeyAddedDelegate UE::FEncryptionKeyManager::KeyAdded private
Definition at line 47 of file EncryptionKeyManager.h.
Referenced by OnKeyAdded().
Keys
TMap<FGuid, FAES::FAESKey> UE::FEncryptionKeyManager::Keys private
Definition at line 46 of file EncryptionKeyManager.h.
Mutex
FMutex UE::FEncryptionKeyManager::Mutex mutable private
Definition at line 45 of file EncryptionKeyManager.h.
The documentation for this class was generated from the following file:
Runtime/Core/Internal/Misc/EncryptionKeyManager.h