Unreal Engine 5.6 C++ API: UAISenseConfig_Hearing Class Reference
UAISenseConfig_Hearing Class Reference
#include "AISenseConfig_Hearing.h"
Private Member Functions
virtual AIMODULE_API TSubclassOf< UAISense > GetSenseImplementation () const override
UE_DEPRECATED (5.2, "LoSHearingRange is deprecated. Use HearingRange instead.") UPROPERTY()) float LoSHearingRange
UE_DEPRECATED(5.2, "bUseLoSHearing is deprecated.") UPROPERTY()) uint32 bUseLoSHearing UPROPERTY () FAISenseAffiliationFilter DetectionByAffiliation
GENERATED_UCLASS_BODY() public UPROPERTY ()) float HearingRange
Detailed Description
Definition at line 18 of file AISenseConfig_Hearing.h.
Member Function Documentation
GetSenseImplementation()
virtual AIMODULE_API TSubclassOf< UAISense > UAISenseConfig_Hearing::GetSenseImplementation () const override private virtual
References GetSenseImplementation().
Referenced by GetSenseImplementation().
UE_DEPRECATED()
UAISenseConfig_Hearing::UE_DEPRECATED (5. 2, "LoSHearingRange is deprecated. Use HearingRange instead.") private
References Category, meta, UE_DEPRECATED(), and UPROPERTY().
Referenced by UE_DEPRECATED().
UPROPERTY() [1/2]
UE_DEPRECATED(5.2, "bUseLoSHearing is deprecated.") UPROPERTY()) uint32 bUseLoSHearing UAISenseConfig_Hearing::UPROPERTY () private
References Category, config, and UPROPERTY().
UPROPERTY() [2/2]
GENERATED_UCLASS_BODY() public UAISenseConfig_Hearing::UPROPERTY () private
References Category, float, and meta.
Referenced by UE_DEPRECATED(), and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/Perception/AISenseConfig_Hearing.h