Unreal Engine 5.6 C++ API: FNoncopyable Class Reference
FNoncopyable Class Reference
utility template for a class that should not be copyable.
#include "UnrealTemplate.h"
Protected Member Functions
FNoncopyable ()
~FNoncopyable ()
Private Member Functions
FNoncopyable (const FNoncopyable &)
FNoncopyable & operator= (const FNoncopyable &)
Detailed Description
utility template for a class that should not be copyable.
Derive from this class to make your class non-copyable
Definition at line 325 of file UnrealTemplate.h.
Constructor & Destructor Documentation
FNoncopyable() [1/2]
FNoncopyable::FNoncopyable () inline protected
Definition at line 329 of file UnrealTemplate.h.
Referenced by FNoncopyable(), and operator=().
~FNoncopyable()
FNoncopyable::~FNoncopyable () inline protected
Definition at line 331 of file UnrealTemplate.h.
FNoncopyable() [2/2]
FNoncopyable::FNoncopyable (const FNoncopyable &) private
References FNoncopyable().
Member Function Documentation
operator=()
FNoncopyable & FNoncopyable::operator= (const FNoncopyable &) private
References FNoncopyable().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/UnrealTemplate.h