Unreal Engine 5.6 C++ API: FMenuBuilder Class Reference
FMenuBuilder Class Reference
Vertical menu builder.
#include "MultiBoxBuilder.h"
Public Member Functions
FMenuBuilder (const bool bInShouldCloseWindowAfterMenuSelection, TSharedPtr< const FUICommandList > InCommandList, TSharedPtr< FExtender > InExtender=TSharedPtr< FExtender >(), const bool bInCloseSelfOnly=false, const ISlateStyle *InStyleSet=&FCoreStyle::Get(), bool bInSearchable=true, FName InMenuName=NAME_None, bool bInRecursivelySearchable=true)
Constructor.
void AddMenuSeparator (FName InExtensionHook=NAME_None, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
Adds a separator.
void AddSearchWidget ()
Adds the widget the multibox will use for searching.
void AddSeparator (FName InExtensionHook=NAME_None, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
void AddSubMenu (const FUIAction &UIAction, const TSharedRef< SWidget > Contents, const FNewMenuDelegate &InSubMenu, const bool bInShouldCloseWindowAfterMenuSelection=true, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
void AddSubMenu (const TAttribute< FText > &InMenuLabel, const TAttribute< FText > &InToolTip, const FNewMenuDelegate &InSubMenu, const bool bInOpenSubMenuOnClick=false, const FSlateIcon &InIcon=FSlateIcon(), const bool bInShouldCloseWindowAfterMenuSelection=true, FName InExtensionHook=NAME_None, FName InTutorialHighlightName=NAME_None, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
void AddSubMenu (const TAttribute< FText > &InMenuLabel, const TAttribute< FText > &InToolTip, const FNewMenuDelegate &InSubMenu, const FUIAction &InUIAction, FName InExtensionHook, const EUserInterfaceActionType InUserInterfaceActionType, const bool bInOpenSubMenuOnClick=false, const FSlateIcon &InIcon=FSlateIcon(), const bool bInShouldCloseWindowAfterMenuSelection=true, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >(), const TAttribute< FText > &InInputBindingOverride=TAttribute< FText >())
Adds a sub-menu which is a menu within a menu.
void AddSubMenu (const TSharedRef< SWidget > Contents, const FNewMenuDelegate &InSubMenu, const bool bInOpenSubMenuOnClick=false, const bool bInShouldCloseWindowAfterMenuSelection=true, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
void AddWidget (const TSharedRef< SWidget > &InWidget, const FText &InLabel, const FMenuEntryStyleParams &InStyleParams, bool bInSearchable=true, const TAttribute< FText > &InToolTipText=FText(), const TAttribute< FSlateIcon > &InIcon=TAttribute< FSlateIcon >(), const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
Adds any widget to the menu.
void AddWidget (const TSharedRef< SWidget > &InWidget, const FText &InLabel, const FMenuEntryStyleParams &InStyleParams, const TAttribute< FMenuEntryResizeParams > &InResizeParams, bool bInSearchable=true, const TAttribute< FText > &InToolTipText=FText(), const TAttribute< FSlateIcon > &InIcon=TAttribute< FSlateIcon >(), const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
Adds any widget to the menu.
void AddWidget (TSharedRef< SWidget > InWidget, const FText &InLabel, bool bInNoIndent=false, bool bInSearchable=true, const TAttribute< FText > &InToolTipText=FText())
Adds any widget to the menu.
void AddWrapperSubMenu (const FText &InMenuLabel, const FText &InToolTip, const FOnGetContent &InSubMenu, const FSlateIcon &InIcon)
Adds a sub-menu which is a menu within a menu.
void AddWrapperSubMenu (const FText &InMenuLabel, const FText &InToolTip, const FOnGetContent &InSubMenu, const FSlateIcon &InIcon, const FUIAction &UIAction)
void AddWrapperSubMenu (const FText &InMenuLabel, const FText &InToolTip, const TSharedPtr< SWidget > &InSubMenu, const FSlateIcon &InIcon)
Adds a sub-menu which is a menu within a menu.
void BeginSection (FName InExtensionHook, const TAttribute< FText > &InHeadingText=TAttribute< FText >(), const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >(), const TAttribute< FMenuEntryResizeParams > &InResizeParams=TAttribute< FMenuEntryResizeParams >())
Starts a section on to the extender section hook stack.
void EndSection ()
Ends the current section.
virtual TSharedRef< class SWidget > MakeWidget (FMultiBox::FOnMakeMultiBoxBuilderOverride *InMakeMultiBoxBuilderOverride, uint32 MaxHeight)
virtual TSharedRef< class SWidget > MakeWidget (FMultiBox::FOnMakeMultiBoxBuilderOverride *InMakeMultiBoxBuilderOverride=nullptr) override
Creates a widget for this MultiBox.
void SetIsEditing (bool bInIsEditing)
void SetSearchable (bool bIsSearchable)
Public Member Functions inherited from FBaseMenuBuilder
FBaseMenuBuilder (const EMultiBoxType InType, const bool bInShouldCloseWindowAfterMenuSelection, TSharedPtr< const FUICommandList > InCommandList, bool bInCloseSelfOnly, TSharedPtr< FExtender > InExtender=TSharedPtr< FExtender >(), const ISlateStyle *InStyleSet=&FCoreStyle::Get(), FName InTutorialHighlightName=NAME_None, FName InMenuName=NAME_None)
Constructor.
void AddMenuEntry (const FMenuEntryParams &InMenuEntryParams)
Adds a menu entry with given param struct.
void AddMenuEntry (const FUIAction &UIAction, const TSharedRef< SWidget > Contents, const FName &InExtensionHook=NAME_None, const TAttribute< FText > &InToolTip=TAttribute< FText >(), const EUserInterfaceActionType UserInterfaceActionType=EUserInterfaceActionType::Button, FName InTutorialHighlightName=NAME_None, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
Adds a menu entry with a custom widget.
void AddMenuEntry (const TAttribute< FText > &InLabel, const TAttribute< FText > &InToolTip, const FSlateIcon &InIcon, const FUIAction &UIAction, FName InExtensionHook=NAME_None, const EUserInterfaceActionType UserInterfaceActionType=EUserInterfaceActionType::Button, FName InTutorialHighlightName=NAME_None, const TAttribute< FText > &InInputBindingOverride=TAttribute< FText >(), const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
Adds a menu entry without the use of a command.
void AddMenuEntry (const TSharedPtr< const FUICommandInfo > InCommand, FName InExtensionHook=NAME_None, const TAttribute< FText > &InLabelOverride=TAttribute< FText >(), const TAttribute< FText > &InToolTipOverride=TAttribute< FText >(), const FSlateIcon &InIconOverride=FSlateIcon(), FName InTutorialHighlightName=NAME_None, const TAttribute< EVisibility > &InVisibility=TAttribute< EVisibility >())
Adds a menu entry.
Public Member Functions inherited from FMultiBoxBuilder
FMultiBoxBuilder (const EMultiBoxType InType, FMultiBoxCustomization InCustomization, const bool bInShouldCloseWindowAfterMenuSelection, const TSharedPtr< const FUICommandList > &InCommandList, TSharedPtr< FExtender > InExtender=TSharedPtr< FExtender >(), FName InTutorialHighlightName=NAME_None, FName InMenuName=NAME_None)
Constructor.
virtual ~FMultiBoxBuilder ()
void AddEditableText (const FText &InLabel, const FText &InToolTip, const FSlateIcon &InIcon, const TAttribute< FText > &InTextAttribute, const FOnTextCommitted &InOnTextCommitted=FOnTextCommitted(), const FOnTextChanged &InOnTextChanged=FOnTextChanged(), bool bInReadOnly=false)
Adds an editable text entry.
void AddVerifiedEditableText (const FText &InLabel, const FText &InToolTip, const FSlateIcon &InIcon, const TAttribute< FText > &InTextAttribute, const FOnVerifyTextChanged &InOnVerifyTextChanged, const FOnTextCommitted &InOnTextCommitted=FOnTextCommitted(), const FOnTextChanged &InOnTextChanged=FOnTextChanged(), bool bInReadOnly=false)
Adds an editable text entry with a VerifyTextChanged delegate.
bool ExtendersEnabled () const
FMultiBoxCustomization GetCustomization () const
TSharedRef< class FMultiBox > GetMultiBox ()
Get the multi-box being built.
const FName & GetStyleName () const
const ISlateStyle * GetStyleSet () const
TSharedPtr< const FUICommandList > GetTopCommandList ()
void PopCommandList ()
Pops the current command list.
void PopExtender ()
Pops the current extender.
void PushCommandList (const TSharedRef< const FUICommandList > CommandList)
Pushes a new command list onto the stack.
void PushExtender (TSharedRef< FExtender > InExtender)
Pushes a new extender onto the stack.
void SetCheckBoxStyle (FName InCheckBoxStyle)
the override for the checkbox style
void SetExtendersEnabled (bool bEnabled)
Sets extender support.
void SetLastSelectedCommandIndex (int32 InLastSelectedCommandIndex)
void SetStyle (const ISlateStyle *InStyleSet, const FName &InStyleName)
Sets the style to use on the multibox widgets.
Protected Member Functions
virtual void ApplyHook (FName InExtensionHook, EExtensionHook::Position HookPosition) override
FMultiBoxBuilder interface.
virtual void ApplySectionBeginning () override
Applies the beginning of a section, including the header and relevant separator.
Private Attributes
bool bIsEditing
Whether menu is currently being edited.
bool bRecursivelySearchable
Whether the search algorithm should walk down this menu sub-menu(s) (if the menu is searchable in first place).
bool bSearchable
Whether this menu is searchable.
bool bSectionNeedsToBeApplied
True if there is a pending section that needs to be applied.
FName CurrentSectionExtensionHook
Current extension hook name for sections to determine where sections begin and end.
FText CurrentSectionHeadingText
Any pending section's heading text.
TAttribute< FMenuEntryResizeParams > CurrentSectionResizeParams
Resize parameters for the current section.
TAttribute< EVisibility > CurrentSectionVisibility
Keep track of current section visibility, in case the section needs to be dynamically hidden.
Additional Inherited Members
Protected Attributes inherited from FBaseMenuBuilder
bool bCloseSelfOnly
True if clicking on a menu entry closes itself only and its children and not the entire stack.
Protected Attributes inherited from FMultiBoxBuilder
bool bExtendersEnabled
If extenders are enabled.
FName CheckBoxStyle
the override for the checkbox style for this menu
TArray< TSharedPtr< const FUICommandList > > CommandListStack
A stack of command lists which map command infos to delegates that should be called.
TArray< TSharedPtr< class FExtender > > ExtenderStack
The extender stack holding all the possible extensions for this menu builder.
FName MenuName
Name of the menu.
TSharedRef< class FMultiBox > MultiBox
The MultiBox we're building up.
FName TutorialHighlightName
Name to identify this widget and highlight during tutorials.
Detailed Description
Vertical menu builder.
Definition at line 309 of file MultiBoxBuilder.h.
Constructor & Destructor Documentation
FMenuBuilder()
FMenuBuilder::FMenuBuilder (const bool bInShouldCloseWindowAfterMenuSelection, TSharedPtr< const FUICommandList > InCommandList, TSharedPtr< FExtender > InExtender = TSharedPtr<FExtender>(), const bool bInCloseSelfOnly = false, const ISlateStyle * InStyleSet = &FCoreStyle::Get(), bool bInSearchable = true, FName InMenuName = NAME_None, bool bInRecursivelySearchable = true) inline
Constructor.
Parameters
bInShouldCloseWindowAfterMenuSelection Sets whether or not the window that contains this multibox should be destroyed after the user clicks on a menu item in this box
InCommandList The action list that maps command infos to delegates that should be called for each command associated with a multiblock widget
bInCloseSelfOnly True if clicking on a menu entry closes itself only and its children but not the entire stack
bInSearchable True if the menu is searchable
bInRecursivelySearchable True if search algorithm should go down the sub-menus when searching. If false, the search will not scan the sub-menus. Recursive search is usually disabled on menus that are automatically generated in a way that the menu can expand indefinitely in a circular fashion. For example, the Blueprint API binding reflected on function return type can do that. Think about a function like "A* A::GetParent()". If a root menu expands "A" functions and expands on the function return types, then selecting "GetParent()" will expand another "A" menu. Without simulation, the reflection API don't know when the recursion finishes, nor does the recursive search algorithm.
Definition at line 325 of file MultiBoxBuilder.h.
References FBaseMenuBuilder::FBaseMenuBuilder(), AddSearchWidget(), bIsEditing, bRecursivelySearchable, bSearchable, bSectionNeedsToBeApplied, FCoreStyle::Get(), and Menu.
Member Function Documentation
AddMenuSeparator()
void FMenuBuilder::AddMenuSeparator (FName InExtensionHook = NAME_None, const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
Adds a separator.
AddSearchWidget()
void FMenuBuilder::AddSearchWidget ()
Adds the widget the multibox will use for searching.
Referenced by FMenuBuilder().
AddSeparator()
void FMenuBuilder::AddSeparator (FName InExtensionHook = NAME_None, const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
AddSubMenu() [1/4]
void FMenuBuilder::AddSubMenu (const FUIAction & UIAction, const TSharedRef< SWidget > Contents, const FNewMenuDelegate & InSubMenu, const bool bInShouldCloseWindowAfterMenuSelection = true, const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
AddSubMenu() [2/4]
void FMenuBuilder::AddSubMenu (const TAttribute< FText > & InMenuLabel, const TAttribute< FText > & InToolTip, const FNewMenuDelegate & InSubMenu, const bool bInOpenSubMenuOnClick = false, const FSlateIcon & InIcon = FSlateIcon(), const bool bInShouldCloseWindowAfterMenuSelection = true, FName InExtensionHook = NAME_None, FName InTutorialHighlightName = NAME_None, const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
AddSubMenu() [3/4]
void FMenuBuilder::AddSubMenu (const TAttribute< FText > & InMenuLabel, const TAttribute< FText > & InToolTip, const FNewMenuDelegate & InSubMenu, const FUIAction & InUIAction, FName InExtensionHook, const EUserInterfaceActionType InUserInterfaceActionType, const bool bInOpenSubMenuOnClick = false, const FSlateIcon & InIcon = FSlateIcon(), const bool bInShouldCloseWindowAfterMenuSelection = true, const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >(), const TAttribute< FText > & InInputBindingOverride = TAttribute< FText >())
Adds a sub-menu which is a menu within a menu.
Parameters
InMenuLabel The text that should be shown for the menu
InToolTip The tooltip that should be shown when the menu is hovered over
InSubMenu Sub-Menu object which creates menu entries for the sub-menu
InUIAction Actions to execute on this menu item.
InExtensionHook The section hook. Can be NAME_None
InUserInterfaceActionType Type of interface action
bInOpenSubMenuOnClick Sub-menu will open only if the sub-menu entry is clicked
InIcon The icon to use
bInShouldCloseWindowAfterMenuSelection Whether the submenu should close after an item is selected
InVisibility Optional Visibility Override. Can be used to show/hide this entry dynamically.
Referenced by FKeyframeTrackEditor< TrackType >::BuildTrackContextMenu().
AddSubMenu() [4/4]
void FMenuBuilder::AddSubMenu (const TSharedRef< SWidget > Contents, const FNewMenuDelegate & InSubMenu, const bool bInOpenSubMenuOnClick = false, const bool bInShouldCloseWindowAfterMenuSelection = true, const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
AddWidget() [1/3]
void FMenuBuilder::AddWidget (const TSharedRef< SWidget > & InWidget, const FText & InLabel, const FMenuEntryStyleParams & InStyleParams, bool bInSearchable = true, const TAttribute< FText > & InToolTipText = FText(), const TAttribute< FSlateIcon > & InIcon = TAttribute< FSlateIcon >(), const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
Adds any widget to the menu.
Parameters
InWidget The widget that should be shown in the menu
InLabel Optional label text to be added to the left of the content
InStyleParams Optional style parameters and overrides,
See also
FMenuEntryStyleParams
Parameters
bInSearchable If true, widget will be searchable (default == true)
InToolTipText Optional tooltip text to be added to the widget and label
InIcon Optional icon to be shown to the left of the label/content
AddWidget() [2/3]
void FMenuBuilder::AddWidget (const TSharedRef< SWidget > & InWidget, const FText & InLabel, const FMenuEntryStyleParams & InStyleParams, const TAttribute< FMenuEntryResizeParams > & InResizeParams, bool bInSearchable = true, const TAttribute< FText > & InToolTipText = FText(), const TAttribute< FSlateIcon > & InIcon = TAttribute< FSlateIcon >(), const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >())
Adds any widget to the menu.
Parameters
InWidget The widget that should be shown in the menu
InLabel Optional label text to be added to the left of the content
InStyleParams Optional style parameters and overrides,
See also
FMenuEntryStyleParams
Parameters
InResizeParams Optional resize parameters and overrides,
See also
FMenuEntryResizeParams
Parameters
bInSearchable If true, widget will be searchable (default == true)
InToolTipText Optional tooltip text to be added to the widget and label
InIcon Optional icon to be shown to the left of the label/content
AddWidget() [3/3]
void FMenuBuilder::AddWidget (TSharedRef< SWidget > InWidget, const FText & InLabel, bool bInNoIndent = false, bool bInSearchable = true, const TAttribute< FText > & InToolTipText = FText())
Adds any widget to the menu.
Parameters
InWidget The widget that should be shown in the menu
InLabel Optional label text to be added to the left of the content
bInNoIndent If true, removes the padding from the left of the widget that lines it up with other menu items (default == false)
bInSearchable If true, widget will be searchable (default == true)
InToolTipText Optional tooltip text to be added to the widget and label
Referenced by SGridLineSpacingList::SLATE_END_ARGS().
AddWrapperSubMenu() [1/3]
void FMenuBuilder::AddWrapperSubMenu (const FText & InMenuLabel, const FText & InToolTip, const FOnGetContent & InSubMenu, const FSlateIcon & InIcon)
Adds a sub-menu which is a menu within a menu.
Parameters
InMenuLabel The text that should be shown for the menu
InToolTip The tooltip that should be shown when the menu is hovered over
InSubMenu Sub-Menu object which creates the sub-menu
AddWrapperSubMenu() [2/3]
void FMenuBuilder::AddWrapperSubMenu (const FText & InMenuLabel, const FText & InToolTip, const FOnGetContent & InSubMenu, const FSlateIcon & InIcon, const FUIAction & UIAction)
AddWrapperSubMenu() [3/3]
void FMenuBuilder::AddWrapperSubMenu (const FText & InMenuLabel, const FText & InToolTip, const TSharedPtr< SWidget > & InSubMenu, const FSlateIcon & InIcon)
Adds a sub-menu which is a menu within a menu.
Parameters
InMenuLabel The text that should be shown for the menu
InToolTip The tooltip that should be shown when the menu is hovered over
InSubMenu Sub-Menu object
ApplyHook()
virtual void FMenuBuilder::ApplyHook (FName InExtensionHook, EExtensionHook::Position HookPosition) override protected virtual
FMultiBoxBuilder interface.
Implements FMultiBoxBuilder.
ApplySectionBeginning()
virtual void FMenuBuilder::ApplySectionBeginning () override protected virtual
Applies the beginning of a section, including the header and relevant separator.
Reimplemented from FMultiBoxBuilder.
BeginSection()
void FMenuBuilder::BeginSection (FName InExtensionHook, const TAttribute< FText > & InHeadingText = TAttribute< FText >(), const TAttribute< EVisibility > & InVisibility = TAttribute< EVisibility >(), const TAttribute< FMenuEntryResizeParams > & InResizeParams = TAttribute< FMenuEntryResizeParams >())
Starts a section on to the extender section hook stack.
Parameters
InExtensionHook The section hook. Can be NAME_None
InHeadingText The heading text to use. If none, only a separator is used
InVisibility Optional Visibility Override. Can be used to show/hide this Section dynamically.
InResizeParams Optional resize parameters and overrides,
See also
FMenuEntryResizeParams
Referenced by SGridLineSpacingList::SLATE_END_ARGS().
EndSection()
void FMenuBuilder::EndSection ()
Ends the current section.
MakeWidget() [1/2]
virtual TSharedRef< class SWidget > FMenuBuilder::MakeWidget (FMultiBox::FOnMakeMultiBoxBuilderOverride * InMakeMultiBoxBuilderOverride, uint32 MaxHeight) virtual
MakeWidget() [2/2]
virtual TSharedRef< class SWidget > FMenuBuilder::MakeWidget (FMultiBox::FOnMakeMultiBoxBuilderOverride * InMakeMultiBoxBuilderOverride = nullptr) override virtual
Creates a widget for this MultiBox.
Returns
New widget object
Reimplemented from FMultiBoxBuilder.
Referenced by SNumericDropDown< NumericType >::BuildMenu(), and SGridLineSpacingList::SLATE_END_ARGS().
SetIsEditing()
void FMenuBuilder::SetIsEditing (bool bInIsEditing) inline
Definition at line 433 of file MultiBoxBuilder.h.
References bIsEditing.
SetSearchable()
void FMenuBuilder::SetSearchable (bool bIsSearchable) inline
Definition at line 461 of file MultiBoxBuilder.h.
References bSearchable.
Field Documentation
bIsEditing
bool FMenuBuilder::bIsEditing private
Whether menu is currently being edited.
Definition at line 486 of file MultiBoxBuilder.h.
Referenced by FMenuBuilder(), and SetIsEditing().
bRecursivelySearchable
bool FMenuBuilder::bRecursivelySearchable private
Whether the search algorithm should walk down this menu sub-menu(s) (if the menu is searchable in first place).
Definition at line 483 of file MultiBoxBuilder.h.
Referenced by FMenuBuilder().
bSearchable
bool FMenuBuilder::bSearchable private
Whether this menu is searchable.
Definition at line 480 of file MultiBoxBuilder.h.
Referenced by FMenuBuilder(), and SetSearchable().
bSectionNeedsToBeApplied
bool FMenuBuilder::bSectionNeedsToBeApplied private
True if there is a pending section that needs to be applied.
Definition at line 477 of file MultiBoxBuilder.h.
Referenced by FMenuBuilder().
CurrentSectionExtensionHook
FName FMenuBuilder::CurrentSectionExtensionHook private
Current extension hook name for sections to determine where sections begin and end.
Definition at line 465 of file MultiBoxBuilder.h.
CurrentSectionHeadingText
FText FMenuBuilder::CurrentSectionHeadingText private
Any pending section's heading text.
Definition at line 468 of file MultiBoxBuilder.h.
CurrentSectionResizeParams
TAttribute<FMenuEntryResizeParams> FMenuBuilder::CurrentSectionResizeParams private
Resize parameters for the current section.
Definition at line 474 of file MultiBoxBuilder.h.
CurrentSectionVisibility
TAttribute<EVisibility> FMenuBuilder::CurrentSectionVisibility private
Keep track of current section visibility, in case the section needs to be dynamically hidden.
Definition at line 471 of file MultiBoxBuilder.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/MultiBox/MultiBoxBuilder.h