Unreal Engine 5.6 C++ API: FMaterialOverlayHelper Class Reference
FMaterialOverlayHelper Class Reference
#include "MaterialOverlayHelper.h"
Static Public Member Functions
static void AppendAllOverlayMaterial (const TArray< TObjectPtr< UMaterialInterface > > &SourceMaterials, TArray< UMaterialInterface * > &OutMaterials)
static void AppendAllOverlayMaterial (const TArray< TObjectPtr< UMaterialInterface > > &SourceMaterials, TArray< UMaterialInterface * > &OutMaterials, bool &bOutHaveNullEntry)
static bool ForceMaterial (TArray< TObjectPtr< UMaterialInterface > > &SourceMaterials, const int32 SlotIndex, UMaterialInterface *ForceMaterial)
static void ForceMaterial (TArray< TObjectPtr< UMaterialInterface > > &SourceMaterials, UMaterialInterface *ForceMaterial)
static UMaterialInterface * GetOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &SourceMaterials, const int32 SlotIndex)
Detailed Description
Definition at line 12 of file MaterialOverlayHelper.h.
Member Function Documentation
AppendAllOverlayMaterial() [1/2]
void FMaterialOverlayHelper::AppendAllOverlayMaterial (const TArray< TObjectPtr< UMaterialInterface > > & SourceMaterials, TArray< UMaterialInterface * > & OutMaterials) inline static
Definition at line 31 of file MaterialOverlayHelper.h.
References AppendAllOverlayMaterial().
AppendAllOverlayMaterial() [2/2]
void FMaterialOverlayHelper::AppendAllOverlayMaterial (const TArray< TObjectPtr< UMaterialInterface > > & SourceMaterials, TArray< UMaterialInterface * > & OutMaterials, bool & bOutHaveNullEntry) inline static
Definition at line 15 of file MaterialOverlayHelper.h.
References TArray< InElementType, InAllocatorType >::Add().
Referenced by AppendAllOverlayMaterial(), FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), FSkinnedMeshComponentHelper::GetUsedMaterials(), and FStaticMeshComponentHelper::GetUsedMaterials().
ForceMaterial() [1/2]
bool FMaterialOverlayHelper::ForceMaterial (TArray< TObjectPtr< UMaterialInterface > > & SourceMaterials, const int32 SlotIndex, UMaterialInterface * ForceMaterial) inline static
Definition at line 45 of file MaterialOverlayHelper.h.
References ForceMaterial().
ForceMaterial() [2/2]
void FMaterialOverlayHelper::ForceMaterial (TArray< TObjectPtr< UMaterialInterface > > & SourceMaterials, UMaterialInterface * ForceMaterial) inline static
Definition at line 37 of file MaterialOverlayHelper.h.
References ForceMaterial().
Referenced by ForceMaterial(), and ForceMaterial().
GetOverlayMaterial()
UMaterialInterface * FMaterialOverlayHelper::GetOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > & SourceMaterials, const int32 SlotIndex) inline static
Definition at line 55 of file MaterialOverlayHelper.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Engine/MaterialOverlayHelper.h