Unreal Engine 5.6 C++ API: TSubSectionMixin< ParentSectionClass > Class Template Reference
TSubSectionMixin< ParentSectionClass > Class Template Reference
Mixin class for sub-sequence section interfaces.
#include "SubTrackEditorBase.h"
Public Member Functions
template<typename... ParentCtorParams>
TSubSectionMixin (TSharedPtr< ISequencer > InSequencer, UMovieSceneSubSection &InSection, ParentCtorParams &&... Params)
virtual void BeginDilateSection () override
Dilation starts with a drag operation.
virtual void BeginResizeSection () override
Resize the section.
virtual void BeginSlipSection () override
Slips the section by a specific factor.
virtual void DilateSection (const TRange< FFrameNumber > &NewRange, float DilationFactor) override
New Range that's set as we Dilate.
virtual float GetSectionHeight (const UE::Sequencer::FViewDensityInfo &ViewDensity) const override
virtual UMovieSceneSection * GetSectionObject () override
The MovieSceneSection data being visualized.
virtual TOptional< FFrameTime > GetSectionTime (FSequencerSectionPainter &InPainter) const override
virtual FText GetSectionTitle () const override
virtual FText GetSectionToolTip () const override
virtual bool IsReadOnly () const override
virtual int32 OnPaintSection (FSequencerSectionPainter &InPainter) const override
Called when the section should be painted.
virtual FReply OnSectionDoubleClicked (const FGeometry &SectionGeometry, const FPointerEvent &MouseEvent) override
Called when the section is double clicked.
virtual bool RequestDeleteKeyArea (const TArray< FName > &KeyAreaNamePath) override
Called when the user requests that a key area from this section be deleted.
virtual void ResizeSection (ESequencerSectionResizeMode ResizeMode, FFrameNumber ResizeTime) override
virtual void SlipSection (FFrameNumber SlipTime) override
Public Member Functions inherited from ISequencerSection
virtual ~ISequencerSection ()
virtual void BuildSectionContextMenu (FMenuBuilder &MenuBuilder, const FGuid &ObjectBinding)
Builds up the section context menu for the outliner.
virtual void BuildSectionSidebarMenu (FMenuBuilder &MenuBuilder, const FGuid &ObjectBinding)
Builds up the section sidebar menu for the outliner.
virtual TSharedPtr< UE::Sequencer::FCategoryModel > ConstructCategoryModel (FName InCategoryName, const FText &InDisplayText, TArrayView< const FChannelData > Channels) const
Create a custom category model.
virtual TSharedPtr< UE::Sequencer::FChannelModel > ConstructChannelModel (FName InChannelName, const FMovieSceneChannelHandle &InChannelHandle) const
Create a custom channel model.
virtual SEQUENCER_API void CreateViewWidgets (const UE::Sequencer::FCreateSectionViewWidgetParams &Params)
Create view widgets for the section by adding the necessary widgets to the overlay widget.
virtual void CustomizePropertiesDetailsView (TSharedRef< IDetailsView > DetailsView, const FSequencerSectionPropertyDetailsViewCustomizationParams &InParams) const
Called when the properties context menu is being built, so this section can customize how the menu's details view looks like.
virtual SEQUENCER_API void GenerateSectionLayout (class ISectionLayoutBuilder &LayoutBuilder)
Generates the inner layout for this section.
virtual TSharedRef< SWidget > GenerateSectionWidget ()
Allows each section to have it's own unique widget for advanced editing functionality OnPaintSection will still be called if a widget is provided.
virtual FMargin GetContentPadding () const
virtual FVector2D GetKeySize () const
@ return The size of keyframe widgets
virtual float GetSectionGripHeight (float InSectionHeight) const
virtual float GetSectionGripSize () const
virtual FReply OnKeyDoubleClicked (const TArray< FKeyHandle > &KeyHandles)
Called when a key on this section is double clicked.
virtual FReply OnSectionDoubleClicked (const FGeometry &SectionGeometry, const FPointerEvent &MouseEvent, const FGuid &ObjectBinding)
Called when the section is double clicked.
virtual bool RequestDeleteCategory (const TArray< FName > &CategoryNamePath)
Called when the user requests that a category from this section be deleted.
virtual bool SectionIsResizable () const
virtual void Tick (const FGeometry &AllottedGeometry, const FGeometry &ClippedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks the section during the Slate tick.
UE_DEPRECATED (5.4, "Please call GetSectionHeight(const FViewDensityInfo& ViewDensity) instead.") SEQUENCER_API virtual float GetSectionHeight() const
Protected Member Functions
FSubSectionEditorUtil & GetEditorUtil ()
template<typename SectionType>
SectionType & GetSectionObjectAs ()
template<typename SectionType>
const SectionType & GetSectionObjectAs () const
TSharedPtr< ISequencer > GetSequencer () const
UMovieSceneSubSection & GetSubSectionObject ()
const UMovieSceneSubSection & GetSubSectionObject () const
Static Protected Attributes
static const float TrackHeight
Private Attributes
FSubSectionEditorUtil EditorUtil
Utility class for resizing/slipping sub-sequence sections.
TWeakPtr< ISequencer > SequencerPtr
The Sequencer this section belongs to.
UMovieSceneSubSection & SubSectionObject
The section object this interface represents.
Detailed Description
template<typename ParentSectionClass = ISequencerSection>
class TSubSectionMixin< ParentSectionClass >
Mixin class for sub-sequence section interfaces.
This mixin effectively wraps the 2 utility classes above, hooks them up to the ISequencerSection interface, and implements a few other ISequencerSection interface methods. As such, it's mostly handy boilerplate code, which you can avoid (if it doesn't fit your use-case) in favour of using the uility classes above directly.
Definition at line 130 of file SubTrackEditorBase.h.
Constructor & Destructor Documentation
TSubSectionMixin()
template<typename ParentSectionClass> template<typename... ParentCtorParams> TSubSectionMixin< ParentSectionClass >::TSubSectionMixin (TSharedPtr< ISequencer > InSequencer, UMovieSceneSubSection & InSection, ParentCtorParams &&... Params)
Definition at line 182 of file SubTrackEditorBase.h.
References EditorUtil, Params, SequencerPtr, and SubSectionObject.
Member Function Documentation
BeginDilateSection()
template<typename ParentSectionClass> void TSubSectionMixin< ParentSectionClass >::BeginDilateSection () override virtual
Dilation starts with a drag operation.
Reimplemented from ISequencerSection.
Definition at line 373 of file SubTrackEditorBase.h.
References EditorUtil.
BeginResizeSection()
template<typename ParentSectionClass> void TSubSectionMixin< ParentSectionClass >::BeginResizeSection () override virtual
Resize the section.
Parameters
ResizeMode Resize either the leading or the trailing edge of the section
ResizeTime The time to resize to
Reimplemented from ISequencerSection.
Definition at line 345 of file SubTrackEditorBase.h.
References EditorUtil.
BeginSlipSection()
template<typename ParentSectionClass> void TSubSectionMixin< ParentSectionClass >::BeginSlipSection () override virtual
Slips the section by a specific factor.
Parameters
SlipTime The amount to slip this section by
Reimplemented from ISequencerSection.
Definition at line 359 of file SubTrackEditorBase.h.
References EditorUtil.
DilateSection()
template<typename ParentSectionClass> void TSubSectionMixin< ParentSectionClass >::DilateSection (const TRange< FFrameNumber > & NewRange, float DilationFactor) override virtual
New Range that's set as we Dilate.
Parameters
NewRange The NewRange.
DilationFactor The factor we have dilated from the beginning of the drag
Reimplemented from ISequencerSection.
Definition at line 380 of file SubTrackEditorBase.h.
References EditorUtil.
GetEditorUtil()
template<typename ParentSectionClass = ISequencerSection> FSubSectionEditorUtil & TSubSectionMixin< ParentSectionClass >::GetEditorUtil () inline protected
Definition at line 159 of file SubTrackEditorBase.h.
References EditorUtil.
GetSectionHeight()
template<typename ParentSectionClass> float TSubSectionMixin< ParentSectionClass >::GetSectionHeight (const UE::Sequencer::FViewDensityInfo & ViewDensity) const override virtual
Reimplemented from ISequencerSection.
Definition at line 294 of file SubTrackEditorBase.h.
References SubSectionObject, and TrackHeight.
GetSectionObject()
template<typename ParentSectionClass> UMovieSceneSection * TSubSectionMixin< ParentSectionClass >::GetSectionObject () override virtual
The MovieSceneSection data being visualized.
Implements ISequencerSection.
Definition at line 190 of file SubTrackEditorBase.h.
References SubSectionObject.
GetSectionObjectAs() [1/2]
template<typename ParentSectionClass = ISequencerSection> template<typename SectionType> SectionType & TSubSectionMixin< ParentSectionClass >::GetSectionObjectAs () inline protected
Definition at line 162 of file SubTrackEditorBase.h.
References CastChecked(), and SubSectionObject.
GetSectionObjectAs() [2/2]
template<typename ParentSectionClass = ISequencerSection> template<typename SectionType> const SectionType & TSubSectionMixin< ParentSectionClass >::GetSectionObjectAs () const inline protected
Definition at line 164 of file SubTrackEditorBase.h.
References CastChecked(), and SubSectionObject.
GetSectionTime()
template<typename ParentSectionClass> TOptional< FFrameTime > TSubSectionMixin< ParentSectionClass >::GetSectionTime (FSequencerSectionPainter & InPainter) const override virtual
Returns
The local section time
Reimplemented from ISequencerSection.
Definition at line 261 of file SubTrackEditorBase.h.
References FSequencerSectionPainter::bIsSelected, FFrameTime::FrameNumber, GetSequencer(), and SubSectionObject.
GetSectionTitle()
template<typename ParentSectionClass> FText TSubSectionMixin< ParentSectionClass >::GetSectionTitle () const override virtual
Returns
The display name of the section in the section view
Reimplemented from ISequencerSection.
Definition at line 197 of file SubTrackEditorBase.h.
References FText::FromString(), LOCTEXT, and SubSectionObject.
GetSectionToolTip()
template<typename ParentSectionClass> FText TSubSectionMixin< ParentSectionClass >::GetSectionToolTip () const override virtual
Returns
The ToolTip for the section in the section view. By default, the section title
Reimplemented from ISequencerSection.
Definition at line 210 of file SubTrackEditorBase.h.
References ConvertFrameTime(), FText::Format(), FText::GetEmpty(), FSubTrackEditorUtil::GetMetaDataText(), FText::IsEmpty(), LOCTEXT, FMath::Min, FFrameTime::RoundToFrame(), SubSectionObject, and FFrameNumber::Value.
GetSequencer()
template<typename ParentSectionClass = ISequencerSection> TSharedPtr< ISequencer > TSubSectionMixin< ParentSectionClass >::GetSequencer () const inline protected
Definition at line 156 of file SubTrackEditorBase.h.
References SequencerPtr.
Referenced by GetSectionTime(), OnPaintSection(), and OnSectionDoubleClicked().
GetSubSectionObject() [1/2]
template<typename ParentSectionClass = ISequencerSection> UMovieSceneSubSection & TSubSectionMixin< ParentSectionClass >::GetSubSectionObject () inline protected
Definition at line 157 of file SubTrackEditorBase.h.
References SubSectionObject.
GetSubSectionObject() [2/2]
template<typename ParentSectionClass = ISequencerSection> const UMovieSceneSubSection & TSubSectionMixin< ParentSectionClass >::GetSubSectionObject () const inline protected
Definition at line 158 of file SubTrackEditorBase.h.
References SubSectionObject.
IsReadOnly()
template<typename ParentSectionClass> bool TSubSectionMixin< ParentSectionClass >::IsReadOnly () const override virtual
Returns
Whether this section is read only.
Reimplemented from ISequencerSection.
Definition at line 304 of file SubTrackEditorBase.h.
References SubSectionObject.
OnPaintSection()
template<typename ParentSectionClass> int32 TSubSectionMixin< ParentSectionClass >::OnPaintSection (FSequencerSectionPainter & InPainter) const override virtual
Called when the section should be painted.
Parameters
Painter Structure that affords common painting operations
Returns
The new LayerId
Implements ISequencerSection.
Definition at line 310 of file SubTrackEditorBase.h.
References ISequencerSection::GetContentPadding(), GetSequencer(), FSequencerSectionPainter::LayerId, FSubSectionPainterUtil::PaintSection(), FSequencerSectionPainter::PaintSectionBackground(), and SubSectionObject.
OnSectionDoubleClicked()
template<typename ParentSectionClass> FReply TSubSectionMixin< ParentSectionClass >::OnSectionDoubleClicked (const FGeometry & SectionGeometry, const FPointerEvent & MouseEvent) override virtual
Called when the section is double clicked.
Parameters
SectionGeometry Geometry of the section
MouseEvent Event causing the double click
Returns
A reply in response to double clicking the section
Reimplemented from ISequencerSection.
Definition at line 320 of file SubTrackEditorBase.h.
References GEditor, GetSequencer(), FReply::Handled(), EKeys::LeftMouseButton, MouseEvent, and SubSectionObject.
RequestDeleteKeyArea()
template<typename ParentSectionClass> bool TSubSectionMixin< ParentSectionClass >::RequestDeleteKeyArea (const TArray< FName > & KeyAreaNamePath) override virtual
Called when the user requests that a key area from this section be deleted.
Parameters
KeyAreaNamePath An array of names representing the path of to the key area to delete, starting with any categories which contain the key area.
Returns
Whether or not the key area was deleted.
Reimplemented from ISequencerSection.
Definition at line 387 of file SubTrackEditorBase.h.
References SubSectionObject.
ResizeSection()
template<typename ParentSectionClass> void TSubSectionMixin< ParentSectionClass >::ResizeSection (ESequencerSectionResizeMode ResizeMode, FFrameNumber ResizeTime) override virtual
Reimplemented from ISequencerSection.
Definition at line 352 of file SubTrackEditorBase.h.
References EditorUtil.
SlipSection()
template<typename ParentSectionClass> void TSubSectionMixin< ParentSectionClass >::SlipSection (FFrameNumber SlipTime) override virtual
Reimplemented from ISequencerSection.
Definition at line 366 of file SubTrackEditorBase.h.
References EditorUtil.
Field Documentation
EditorUtil
template<typename ParentSectionClass = ISequencerSection> FSubSectionEditorUtil TSubSectionMixin< ParentSectionClass >::EditorUtil private
Utility class for resizing/slipping sub-sequence sections.
Definition at line 174 of file SubTrackEditorBase.h.
Referenced by TSubSectionMixin(), BeginDilateSection(), BeginResizeSection(), BeginSlipSection(), DilateSection(), GetEditorUtil(), ResizeSection(), and SlipSection().
SequencerPtr
template<typename ParentSectionClass = ISequencerSection> TWeakPtr<ISequencer> TSubSectionMixin< ParentSectionClass >::SequencerPtr private
The Sequencer this section belongs to.
Definition at line 168 of file SubTrackEditorBase.h.
Referenced by TSubSectionMixin(), and GetSequencer().
SubSectionObject
template<typename ParentSectionClass = ISequencerSection> UMovieSceneSubSection& TSubSectionMixin< ParentSectionClass >::SubSectionObject private
The section object this interface represents.
Definition at line 171 of file SubTrackEditorBase.h.
Referenced by TSubSectionMixin(), GetSectionHeight(), GetSectionObject(), GetSectionObjectAs(), GetSectionObjectAs(), GetSectionTime(), GetSectionTitle(), GetSectionToolTip(), GetSubSectionObject(), GetSubSectionObject(), IsReadOnly(), OnPaintSection(), OnSectionDoubleClicked(), and RequestDeleteKeyArea().
TrackHeight
template<typename ParentSectionClass = ISequencerSection> const float TSubSectionMixin< ParentSectionClass >::TrackHeight static protected
Definition at line 155 of file SubTrackEditorBase.h.
Referenced by GetSectionHeight().
The documentation for this class was generated from the following file:
Editor/MovieSceneTools/Public/TrackEditors/SubTrackEditorBase.h