Unreal Engine 5.6 C++ API: UUVEditorBrushSelectTool Class Reference
UUVEditorBrushSelectTool Class Reference
The brush select tool allows for brush selection of triangles on the unwrap or the live preview.
#include "UVEditorBrushSelectTool.h"
Public Member Functions
virtual bool CanCurrentlyNestedCancel () override
virtual bool ExecuteNestedCancelCommand () override
Called by Editor levels to tell the implementor (eg Tool) to execute a nested Cancel action.
virtual bool HasAccept () const override
virtual bool HasCancel () const override
virtual void OnTick (float DeltaTime) override
virtual void RegisterActions (FInteractiveToolActionSet &ActionSet) override
virtual void Render (IToolsContextRenderAPI *RenderAPI) override
virtual void SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > &TargetsIn)
virtual void Setup () override
virtual void Shutdown (EToolShutdownType ShutdownType) override
virtual bool SupportsNestedCancelCommand () override
virtual bool SupportsUnsetElementAppliedMeshSelections () const
Private Member Functions
void ClearSelections (bool bBroadcastAndEmit=false)
void DecreaseBrushRadiusAction ()
void IncreaseBrushRadiusAction ()
void ProcessPendingLivePreviewHits ()
void ProcessPendingUnwrapHits ()
void UpdateViewportStateFromHoverOrDragEvent (bool bFromUnwrap, bool bIsEndEvent, bool bDragging)
Private Attributes
bool bCtrlToggle = false
bool bCurrentStrokeIsSubtracting = false
bool bDraggingLivePreview = false
bool bDraggingUnwrap = false
bool bHaveInteracted = false
bool bHavePendingLivePreviewHit = false
bool bHavePendingUnwrapHit = false
bool bHoveringLivePreview = false
bool bHoveringUnwrap = false
bool bShiftToggle = false
int32 CtrlModifierID = 2
CURRENT_FILE_ID___LINE___GENERATED_BODY
TObjectPtr< UUVToolEmitChangeAPI > EmitChangeAPI = nullptr
TObjectPtr< UUVToolLivePreviewAPI > LivePreviewAPI = nullptr
TObjectPtr< UInputBehaviorSet > LivePreviewBehaviorSet = nullptr
TObjectPtr< ULocalInputBehaviorSource > LivePreviewBehaviorSource = nullptr
TObjectPtr< UBrushStampIndicator > LivePreviewBrushIndicator = nullptr
TWeakObjectPtr< UInputRouter > LivePreviewInputRouter = nullptr
TArray< UUVEditorMeshSelectionMechanic::FRaycastResult > PendingLivePreviewHits
TArray< FVector2d > PendingUnwrapHits
TObjectPtr< UUVToolSelectionAPI > SelectionAPI = nullptr
TWeakObjectPtr< const UUVEditorMeshSelectionMechanic > SelectionMechanic = nullptr
TObjectPtr< UUVEditorBrushSelectToolProperties > Settings = nullptr
int32 ShiftModifierID = 1
TArray< TObjectPtr< UUVEditorToolMeshInput > > Targets
TArray< int32 > TempROIBuffer
TObjectPtr< UBrushStampIndicator > UnwrapBrushIndicator = nullptr
Detailed Description
The brush select tool allows for brush selection of triangles on the unwrap or the live preview.
Definition at line 57 of file UVEditorBrushSelectTool.h.
Member Function Documentation
CanCurrentlyNestedCancel()
virtual bool UUVEditorBrushSelectTool::CanCurrentlyNestedCancel () override virtual
Returns
true if the implementor of this API can currently consume a Cancel action
Reimplemented from IInteractiveToolNestedAcceptCancelAPI.
ClearSelections()
void UUVEditorBrushSelectTool::ClearSelections (bool bBroadcastAndEmit = false) private
References ClearSelections().
Referenced by ClearSelections().
DecreaseBrushRadiusAction()
void UUVEditorBrushSelectTool::DecreaseBrushRadiusAction () private
References DecreaseBrushRadiusAction().
Referenced by DecreaseBrushRadiusAction().
ExecuteNestedCancelCommand()
virtual bool UUVEditorBrushSelectTool::ExecuteNestedCancelCommand () override virtual
Called by Editor levels to tell the implementor (eg Tool) to execute a nested Cancel action.
Returns
true if the implementor consumed the Cancel action
Reimplemented from IInteractiveToolNestedAcceptCancelAPI.
HasAccept()
virtual bool UUVEditorBrushSelectTool::HasAccept () const inline override virtual
Definition at line 72 of file UVEditorBrushSelectTool.h.
HasCancel()
virtual bool UUVEditorBrushSelectTool::HasCancel () const inline override virtual
Definition at line 71 of file UVEditorBrushSelectTool.h.
References HasCancel().
Referenced by HasCancel().
IncreaseBrushRadiusAction()
void UUVEditorBrushSelectTool::IncreaseBrushRadiusAction () private
References IncreaseBrushRadiusAction().
Referenced by IncreaseBrushRadiusAction().
OnTick()
virtual void UUVEditorBrushSelectTool::OnTick (float DeltaTime) override virtual
References DeltaTime, and OnTick().
Referenced by OnTick().
ProcessPendingLivePreviewHits()
void UUVEditorBrushSelectTool::ProcessPendingLivePreviewHits () private
References ProcessPendingLivePreviewHits().
Referenced by ProcessPendingLivePreviewHits().
ProcessPendingUnwrapHits()
void UUVEditorBrushSelectTool::ProcessPendingUnwrapHits () private
References ProcessPendingUnwrapHits().
Referenced by ProcessPendingUnwrapHits().
RegisterActions()
virtual void UUVEditorBrushSelectTool::RegisterActions (FInteractiveToolActionSet & ActionSet) override virtual
Render()
virtual void UUVEditorBrushSelectTool::Render (IToolsContextRenderAPI * RenderAPI) override virtual
References Render().
Referenced by Render().
SetTargets()
virtual void UUVEditorBrushSelectTool::SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > & TargetsIn) inline virtual
Definition at line 81 of file UVEditorBrushSelectTool.h.
References Targets.
Setup()
virtual void UUVEditorBrushSelectTool::Setup () override virtual
References Setup().
Referenced by Setup().
Shutdown()
virtual void UUVEditorBrushSelectTool::Shutdown (EToolShutdownType ShutdownType) override virtual
References Shutdown().
Referenced by Shutdown().
SupportsNestedCancelCommand()
virtual bool UUVEditorBrushSelectTool::SupportsNestedCancelCommand () inline override virtual
Definition at line 76 of file UVEditorBrushSelectTool.h.
SupportsUnsetElementAppliedMeshSelections()
virtual bool UUVEditorBrushSelectTool::SupportsUnsetElementAppliedMeshSelections () const inline virtual
Definition at line 86 of file UVEditorBrushSelectTool.h.
UpdateViewportStateFromHoverOrDragEvent()
void UUVEditorBrushSelectTool::UpdateViewportStateFromHoverOrDragEvent (bool bFromUnwrap, bool bIsEndEvent, bool bDragging) private
References UpdateViewportStateFromHoverOrDragEvent().
Referenced by UpdateViewportStateFromHoverOrDragEvent().
Field Documentation
bCtrlToggle
bool UUVEditorBrushSelectTool::bCtrlToggle = false private
Definition at line 135 of file UVEditorBrushSelectTool.h.
bCurrentStrokeIsSubtracting
bool UUVEditorBrushSelectTool::bCurrentStrokeIsSubtracting = false private
Definition at line 136 of file UVEditorBrushSelectTool.h.
bDraggingLivePreview
bool UUVEditorBrushSelectTool::bDraggingLivePreview = false private
Definition at line 156 of file UVEditorBrushSelectTool.h.
bDraggingUnwrap
bool UUVEditorBrushSelectTool::bDraggingUnwrap = false private
Definition at line 155 of file UVEditorBrushSelectTool.h.
bHaveInteracted
bool UUVEditorBrushSelectTool::bHaveInteracted = false private
Definition at line 151 of file UVEditorBrushSelectTool.h.
bHavePendingLivePreviewHit
bool UUVEditorBrushSelectTool::bHavePendingLivePreviewHit = false private
Definition at line 130 of file UVEditorBrushSelectTool.h.
bHavePendingUnwrapHit
bool UUVEditorBrushSelectTool::bHavePendingUnwrapHit = false private
Definition at line 129 of file UVEditorBrushSelectTool.h.
bHoveringLivePreview
bool UUVEditorBrushSelectTool::bHoveringLivePreview = false private
Definition at line 154 of file UVEditorBrushSelectTool.h.
bHoveringUnwrap
bool UUVEditorBrushSelectTool::bHoveringUnwrap = false private
Definition at line 153 of file UVEditorBrushSelectTool.h.
bShiftToggle
bool UUVEditorBrushSelectTool::bShiftToggle = false private
Definition at line 134 of file UVEditorBrushSelectTool.h.
CtrlModifierID
int32 UUVEditorBrushSelectTool::CtrlModifierID = 2 private
Definition at line 133 of file UVEditorBrushSelectTool.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorBrushSelectTool::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 62 of file UVEditorBrushSelectTool.h.
EmitChangeAPI
TObjectPtr<UUVToolEmitChangeAPI> UUVEditorBrushSelectTool::EmitChangeAPI = nullptr private
Definition at line 93 of file UVEditorBrushSelectTool.h.
LivePreviewAPI
TObjectPtr<UUVToolLivePreviewAPI> UUVEditorBrushSelectTool::LivePreviewAPI = nullptr private
Definition at line 101 of file UVEditorBrushSelectTool.h.
LivePreviewBehaviorSet
TObjectPtr<UInputBehaviorSet> UUVEditorBrushSelectTool::LivePreviewBehaviorSet = nullptr private
Definition at line 105 of file UVEditorBrushSelectTool.h.
LivePreviewBehaviorSource
TObjectPtr<ULocalInputBehaviorSource> UUVEditorBrushSelectTool::LivePreviewBehaviorSource = nullptr private
Definition at line 107 of file UVEditorBrushSelectTool.h.
LivePreviewBrushIndicator
TObjectPtr<UBrushStampIndicator> UUVEditorBrushSelectTool::LivePreviewBrushIndicator = nullptr private
Definition at line 116 of file UVEditorBrushSelectTool.h.
LivePreviewInputRouter
TWeakObjectPtr<UInputRouter> UUVEditorBrushSelectTool::LivePreviewInputRouter = nullptr private
Definition at line 103 of file UVEditorBrushSelectTool.h.
PendingLivePreviewHits
TArray<UUVEditorMeshSelectionMechanic::FRaycastResult> UUVEditorBrushSelectTool::PendingLivePreviewHits private
Definition at line 118 of file UVEditorBrushSelectTool.h.
PendingUnwrapHits
TArray<FVector2d> UUVEditorBrushSelectTool::PendingUnwrapHits private
Definition at line 121 of file UVEditorBrushSelectTool.h.
SelectionAPI
TObjectPtr<UUVToolSelectionAPI> UUVEditorBrushSelectTool::SelectionAPI = nullptr private
Definition at line 96 of file UVEditorBrushSelectTool.h.
SelectionMechanic
TWeakObjectPtr<const UUVEditorMeshSelectionMechanic> UUVEditorBrushSelectTool::SelectionMechanic = nullptr private
Definition at line 98 of file UVEditorBrushSelectTool.h.
Settings
TObjectPtr<UUVEditorBrushSelectToolProperties> UUVEditorBrushSelectTool::Settings = nullptr private
Definition at line 110 of file UVEditorBrushSelectTool.h.
ShiftModifierID
int32 UUVEditorBrushSelectTool::ShiftModifierID = 1 private
Definition at line 132 of file UVEditorBrushSelectTool.h.
Targets
TArray<TObjectPtr<UUVEditorToolMeshInput> > UUVEditorBrushSelectTool::Targets private
Definition at line 90 of file UVEditorBrushSelectTool.h.
Referenced by SetTargets().
TempROIBuffer
TArray<int32> UUVEditorBrushSelectTool::TempROIBuffer private
Definition at line 147 of file UVEditorBrushSelectTool.h.
UnwrapBrushIndicator
TObjectPtr<UBrushStampIndicator> UUVEditorBrushSelectTool::UnwrapBrushIndicator = nullptr private
Definition at line 113 of file UVEditorBrushSelectTool.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/UVEditorBrushSelectTool.h