Unreal Engine 5.6 C++ API: FShaderCodeResource Class Reference
FShaderCodeResource Class Reference
#include "ShaderCore.h"
Data Structures
struct FHeader
Public Member Functions
FCompositeBuffer GetCacheBuffer () const
FSharedBuffer GetCodeBuffer () const
TConstArrayView< uint8 > GetCodeView () const
EShaderFrequency GetFrequency () const
int32 GetShaderCodeSize () const
FCompressedBuffer GetSymbolsBuffer () const
int32 GetUncompressedSize () const
void PopulateFromComposite (FCompositeBuffer CacheBuffer, FCompressedBuffer SymbolsBuffer)
void PopulateHeader (int32 UncompressedSize, int32 ShaderCodeSize, EShaderFrequency Frequency)
Static Public Member Functions
static FCompositeBuffer Unpack (FSharedBuffer MonolithicBuffer)
Private Attributes
FSharedBuffer Code
FSharedBuffer Header
FCompressedBuffer Symbols
Friends
class FShaderCode
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FShaderCode &Code)
FArchive & operator<< (FArchive &Ar, FShaderCodeResource &Resource)
Detailed Description
Definition at line 1130 of file ShaderCore.h.
Member Function Documentation
GetCacheBuffer()
FCompositeBuffer FShaderCodeResource::GetCacheBuffer () const inline
Definition at line 1175 of file ShaderCore.h.
References Code, and Header.
GetCodeBuffer()
FSharedBuffer FShaderCodeResource::GetCodeBuffer () const inline
Definition at line 1163 of file ShaderCore.h.
References Code.
GetCodeView()
TConstArrayView< uint8 > FShaderCodeResource::GetCodeView () const inline
Definition at line 1157 of file ShaderCore.h.
References Code, and MakeConstArrayView().
GetFrequency()
EShaderFrequency FShaderCodeResource::GetFrequency () const inline
Definition at line 1230 of file ShaderCore.h.
References check, FShaderCodeResource::FHeader::Frequency, and Header.
GetShaderCodeSize()
int32 FShaderCodeResource::GetShaderCodeSize () const inline
Definition at line 1223 of file ShaderCore.h.
References check, Header, and FShaderCodeResource::FHeader::ShaderCodeSize.
GetSymbolsBuffer()
FCompressedBuffer FShaderCodeResource::GetSymbolsBuffer () const inline
Definition at line 1169 of file ShaderCore.h.
References Symbols.
GetUncompressedSize()
int32 FShaderCodeResource::GetUncompressedSize () const inline
Definition at line 1216 of file ShaderCore.h.
References check, Header, and FShaderCodeResource::FHeader::UncompressedSize.
PopulateFromComposite()
void FShaderCodeResource::PopulateFromComposite (FCompositeBuffer CacheBuffer, FCompressedBuffer SymbolsBuffer) inline
Definition at line 1195 of file ShaderCore.h.
References check, Code, FCompositeBuffer::GetSegments(), Header, and Symbols.
PopulateHeader()
void FShaderCodeResource::PopulateHeader (int32 UncompressedSize, int32 ShaderCodeSize, EShaderFrequency Frequency) inline
Definition at line 1208 of file ShaderCore.h.
References check, FSharedBuffer::Clone(), Code, Frequency, Header, and UncompressedSize.
Unpack()
FCompositeBuffer FShaderCodeResource::Unpack (FSharedBuffer MonolithicBuffer) inline static
Definition at line 1183 of file ShaderCore.h.
References FSharedBuffer::GetView(), TMemoryView< DataType >::Left(), FSharedBuffer::MakeView(), and TMemoryView< DataType >::RightChop().
Friends And Related Symbol Documentation
FShaderCode
friend class FShaderCode friend
Definition at line 1148 of file ShaderCore.h.
References FShaderCode.
Referenced by FShaderCode, and operator<<.
operator<< [1/2]
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FShaderCode & Code) friend
References Ar, Code, and FShaderCode.
operator<< [2/2]
FArchive & operator<< (FArchive & Ar, FShaderCodeResource & Resource) friend
References Ar.
Field Documentation
Code
FSharedBuffer FShaderCodeResource::Code private
Definition at line 1145 of file ShaderCore.h.
Referenced by GetCacheBuffer(), GetCodeBuffer(), GetCodeView(), operator<<, PopulateFromComposite(), and PopulateHeader().
Header
FSharedBuffer FShaderCodeResource::Header private
Definition at line 1144 of file ShaderCore.h.
Referenced by GetCacheBuffer(), GetFrequency(), GetShaderCodeSize(), GetUncompressedSize(), PopulateFromComposite(), and PopulateHeader().
Symbols
FCompressedBuffer FShaderCodeResource::Symbols private
Definition at line 1146 of file ShaderCore.h.
Referenced by GetSymbolsBuffer(), and PopulateFromComposite().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderCore.h