Unreal Engine 5.6 C++ API: TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes > Class Template Reference
TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes > Class Template Reference
Handles instancing thumbnail scenes for Class and Blueprint types (use the class or generated class as the key).
#include "ThumbnailHelpers.h"
Public Member Functions
TClassInstanceThumbnailScene ()
Constructor.
void Clear ()
Clears all thumbnail scenes.
TSharedRef< ThumbnailSceneType > EnsureThumbnailScene (const UClass *InClass)
Find or create a thumbnail scene instance for this class type.
TSharedPtr< ThumbnailSceneType > FindThumbnailScene (const UClass *InClass) const
Find an existing thumbnail scene instance for this class type.
void RemoveThumbnailScene (const UClass *InClass)
Removes the thumbnail scene instance for the specified class.
Private Attributes
TMap< FName, TSharedPtr< ThumbnailSceneType > > InstancedThumbnailScenes
Mapping between the class type and its thumbnail scene.
Detailed Description
template<typename ThumbnailSceneType, int32 MaxNumScenes>
class TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >
Handles instancing thumbnail scenes for Class and Blueprint types (use the class or generated class as the key).
Definition at line 353 of file ThumbnailHelpers.h.
Constructor & Destructor Documentation
TClassInstanceThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::TClassInstanceThumbnailScene () inline
Constructor.
Definition at line 357 of file ThumbnailHelpers.h.
References InstancedThumbnailScenes.
Member Function Documentation
Clear()
template<typename ThumbnailSceneType, int32 MaxNumScenes> void TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::Clear () inline
Clears all thumbnail scenes.
Definition at line 402 of file ThumbnailHelpers.h.
References InstancedThumbnailScenes.
EnsureThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> TSharedRef< ThumbnailSceneType > TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::EnsureThumbnailScene (const UClass * InClass) inline
Find or create a thumbnail scene instance for this class type.
Definition at line 372 of file ThumbnailHelpers.h.
References check, CollectGarbage(), GARBAGE_COLLECTION_KEEPFLAGS, UObjectBase::GetFName(), InstancedThumbnailScenes, TSharedPtr< ObjectType, InMode >::IsValid(), MakeShareable(), and TSharedPtr< ObjectType, InMode >::ToSharedRef().
FindThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> TSharedPtr< ThumbnailSceneType > TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::FindThumbnailScene (const UClass * InClass) const inline
Find an existing thumbnail scene instance for this class type.
Definition at line 363 of file ThumbnailHelpers.h.
References check, UObjectBase::GetFName(), and InstancedThumbnailScenes.
RemoveThumbnailScene()
template<typename ThumbnailSceneType, int32 MaxNumScenes> void TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::RemoveThumbnailScene (const UClass * InClass) inline
Removes the thumbnail scene instance for the specified class.
Definition at line 395 of file ThumbnailHelpers.h.
References check, UObjectBase::GetFName(), and InstancedThumbnailScenes.
Field Documentation
InstancedThumbnailScenes
template<typename ThumbnailSceneType, int32 MaxNumScenes> TMap<FName, TSharedPtr<ThumbnailSceneType> > TClassInstanceThumbnailScene< ThumbnailSceneType, MaxNumScenes >::InstancedThumbnailScenes private
Mapping between the class type and its thumbnail scene.
Note
This uses the class name rather than the class pointer to avoid leaving behind stale class instances as Blueprints are re-compiled.
Definition at line 412 of file ThumbnailHelpers.h.
Referenced by TClassInstanceThumbnailScene(), Clear(), EnsureThumbnailScene(), FindThumbnailScene(), and RemoveThumbnailScene().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/ThumbnailHelpers.h