Unreal Engine 5.6 C++ API: IDisplayClusterShaders Class Reference
IDisplayClusterShaders Class Reference abstract
#include "IDisplayClusterShaders.h"
Public Member Functions
virtual ~IDisplayClusterShaders ()=default
virtual void AddLinearToPQPass (FRDGBuilder &GraphBuilder, const FDisplayClusterShaderParameters_MediaPQ &Parameters) const =0
Adds Linear-To-PQ encoding pass.
virtual void AddPQToLinearPass (FRDGBuilder &GraphBuilder, const FDisplayClusterShaderParameters_MediaPQ &Parameters) const =0
Adds PQ-To-Linear decoding pass (API wrapper)
virtual TSharedRef< IDisplayClusterShadersTextureUtils > CreateTextureUtils_RenderThread (FRDGBuilder &GraphBuilder) const =0
Return new instance of the resource utils.
virtual TSharedRef< IDisplayClusterShadersTextureUtils > CreateTextureUtils_RenderThread (FRHICommandListImmediate &RHICmdList) const =0
Return new instance of the resource utils.
virtual bool GenerateMips (FRHICommandListImmediate &RHICmdList, FRHITexture *InOutMipsTexture, const FDisplayClusterShaderParameters_GenerateMips &InSettings) const =0
Generate Mips texture.
virtual bool RenderPostprocess_Blur (FRHICommandListImmediate &RHICmdList, FRHITexture *InSourceTexture, FRHITexture *InRenderTargetableDestTexture, const FDisplayClusterShaderParameters_PostprocessBlur &InSettings) const =0
Render postprocess Blur.
virtual bool RenderPostprocess_OutputRemap (FRHICommandListImmediate &RHICmdList, FRHITexture *InSourceTexture, FRHITexture *InRenderTargetableDestTexture, const IDisplayClusterRender_MeshComponentProxy &MeshProxy) const =0
Render postprocess OutputRemap.
virtual bool RenderPreprocess_UVLightCards (FRHICommandListImmediate &RHICmdList, FSceneInterface *InScene, FRenderTarget *InRenderTarget, const FDisplayClusterShaderParameters_UVLightCards &InParameters) const =0
Render UV light cards to texture that can be sampled by viewports to place light cards in UV space.
virtual bool RenderWarpBlend_ICVFX (FRHICommandListImmediate &RHICmdList, const FDisplayClusterShaderParameters_WarpBlend &InWarpBlendParameters, const FDisplayClusterShaderParameters_ICVFX &InICVFXParameters) const =0
Render ICVFX warp&blend.
virtual bool RenderWarpBlend_MPCDI (FRHICommandListImmediate &RHICmdList, const FDisplayClusterShaderParameters_WarpBlend &InWarpBlendParameters) const =0
Render warp&blend.
UE_DEPRECATED (5.2, "Use version that takes FDisplayClusterShaderParameters_UVLightCards instead") virtual bool RenderPreprocess_UVLightCards(FRHICommandListImmediate &RHICmdList
Render UV light cards to texture that can be sampled by viewports to place light cards in UV space.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterShaders & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Data Fields
FSceneInterface FRenderTarget float bool bRenderFinalColor const = 0
FSceneInterface FRenderTarget * InRenderTarget
FSceneInterface * InScene
FSceneInterface FRenderTarget float ProjectionPlaneSize
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterShaders")
Detailed Description
Definition at line 28 of file IDisplayClusterShaders.h.
Constructor & Destructor Documentation
~IDisplayClusterShaders()
virtual IDisplayClusterShaders::~IDisplayClusterShaders () virtual default
Member Function Documentation
AddLinearToPQPass()
virtual void IDisplayClusterShaders::AddLinearToPQPass (FRDGBuilder & GraphBuilder, const FDisplayClusterShaderParameters_MediaPQ & Parameters) const pure virtual
Adds Linear-To-PQ encoding pass.
Parameters
GraphBuilder - RDG builder
Parameters - Conversion parameters
References AddLinearToPQPass(), and const.
Referenced by AddLinearToPQPass().
AddPQToLinearPass()
virtual void IDisplayClusterShaders::AddPQToLinearPass (FRDGBuilder & GraphBuilder, const FDisplayClusterShaderParameters_MediaPQ & Parameters) const pure virtual
Adds PQ-To-Linear decoding pass (API wrapper)
Parameters
GraphBuilder - RDG builder
Parameters - Conversion parameters
References AddPQToLinearPass(), and const.
Referenced by AddPQToLinearPass().
CreateTextureUtils_RenderThread() [1/2]
virtual TSharedRef< IDisplayClusterShadersTextureUtils > IDisplayClusterShaders::CreateTextureUtils_RenderThread (FRDGBuilder & GraphBuilder) const pure virtual
Return new instance of the resource utils.
Parameters
GraphBuilder - RDG builder
References const, and CreateTextureUtils_RenderThread().
CreateTextureUtils_RenderThread() [2/2]
virtual TSharedRef< IDisplayClusterShadersTextureUtils > IDisplayClusterShaders::CreateTextureUtils_RenderThread (FRHICommandListImmediate & RHICmdList) const pure virtual
Return new instance of the resource utils.
Parameters
RHICmdList - RHI API
References const, and CreateTextureUtils_RenderThread().
Referenced by CreateTextureUtils_RenderThread(), and CreateTextureUtils_RenderThread().
GenerateMips()
virtual bool IDisplayClusterShaders::GenerateMips (FRHICommandListImmediate & RHICmdList, FRHITexture * InOutMipsTexture, const FDisplayClusterShaderParameters_GenerateMips & InSettings) const pure virtual
Generate Mips texture.
Parameters
RHICmdList - RHI command list
InOutMipsTexture - Mips textures with assigned mip0
InSettings - mips settings
Returns
- true if success
References const, and GenerateMips().
Referenced by GenerateMips().
Get()
IDisplayClusterShaders & IDisplayClusterShaders::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 43 of file IDisplayClusterShaders.h.
References FModuleManager::LoadModuleChecked(), and ModuleName.
IsAvailable()
bool IDisplayClusterShaders::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 53 of file IDisplayClusterShaders.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
RenderPostprocess_Blur()
virtual bool IDisplayClusterShaders::RenderPostprocess_Blur (FRHICommandListImmediate & RHICmdList, FRHITexture * InSourceTexture, FRHITexture * InRenderTargetableDestTexture, const FDisplayClusterShaderParameters_PostprocessBlur & InSettings) const pure virtual
Render postprocess Blur.
Parameters
RHICmdList - RHI command list
InSourceTexture - - Source shader resource texture
InRenderTargetableDestTexture - Destination RTT texture
InSettings - Blur pp settings
Returns
- true if success
References const, and RenderPostprocess_Blur().
Referenced by RenderPostprocess_Blur().
RenderPostprocess_OutputRemap()
virtual bool IDisplayClusterShaders::RenderPostprocess_OutputRemap (FRHICommandListImmediate & RHICmdList, FRHITexture * InSourceTexture, FRHITexture * InRenderTargetableDestTexture, const IDisplayClusterRender_MeshComponentProxy & MeshProxy) const pure virtual
Render postprocess OutputRemap.
Parameters
RHICmdList - RHI command list
InSourceTexture - - Source shader resource texture
InRenderTargetableDestTexture - Destination RTT texture
MeshProxy - mesh for output remapping
Returns
- true if success
References const, and RenderPostprocess_OutputRemap().
Referenced by RenderPostprocess_OutputRemap().
RenderPreprocess_UVLightCards()
virtual bool IDisplayClusterShaders::RenderPreprocess_UVLightCards (FRHICommandListImmediate & RHICmdList, FSceneInterface * InScene, FRenderTarget * InRenderTarget, const FDisplayClusterShaderParameters_UVLightCards & InParameters) const pure virtual
Render UV light cards to texture that can be sampled by viewports to place light cards in UV space.
Parameters
RHICmdList - RHI command list
InScene - The scene the light cards live in
InRenderTarget - Destination RTT texture
InParameters - Parameters for the render
Returns
- true if success
References const, InRenderTarget, InScene, and RenderPreprocess_UVLightCards().
Referenced by RenderPreprocess_UVLightCards().
RenderWarpBlend_ICVFX()
virtual bool IDisplayClusterShaders::RenderWarpBlend_ICVFX (FRHICommandListImmediate & RHICmdList, const FDisplayClusterShaderParameters_WarpBlend & InWarpBlendParameters, const FDisplayClusterShaderParameters_ICVFX & InICVFXParameters) const pure virtual
Render ICVFX warp&blend.
Parameters
RHICmdList - RHI command list
InWarpBlendParameters - WarpBlend parameters
InICVFXParameters - ICVFX parameters
Returns
- true if success
RenderWarpBlend_MPCDI()
virtual bool IDisplayClusterShaders::RenderWarpBlend_MPCDI (FRHICommandListImmediate & RHICmdList, const FDisplayClusterShaderParameters_WarpBlend & InWarpBlendParameters) const pure virtual
Render warp&blend.
Parameters
RHICmdList - RHI command list
InWarpBlendParameters - warp blend parameters
Returns
- true if success
UE_DEPRECATED()
IDisplayClusterShaders::UE_DEPRECATED (5. 2, "Use version that takes FDisplayClusterShaderParameters_UVLightCards instead") &
Render UV light cards to texture that can be sampled by viewports to place light cards in UV space.
Parameters
RHICmdList - RHI command list
InScene - The scene the light cards live in
InRenderTargetableDestTexture - Destination RTT texture
ProjectionPlaneSize - The size of the plane the UV light cards are projected to
Returns
- true if success
Field Documentation
const
FSceneInterface FRenderTarget float bool bRenderFinalColor IDisplayClusterShaders::const = 0
Definition at line 91 of file IDisplayClusterShaders.h.
Referenced by AddLinearToPQPass(), AddPQToLinearPass(), CreateTextureUtils_RenderThread(), CreateTextureUtils_RenderThread(), GenerateMips(), RenderPostprocess_Blur(), RenderPostprocess_OutputRemap(), and RenderPreprocess_UVLightCards().
InRenderTarget
FSceneInterface FRenderTarget* IDisplayClusterShaders::InRenderTarget
Definition at line 91 of file IDisplayClusterShaders.h.
Referenced by RenderPreprocess_UVLightCards().
InScene
FSceneInterface* IDisplayClusterShaders::InScene
Definition at line 91 of file IDisplayClusterShaders.h.
Referenced by RenderPreprocess_UVLightCards().
ModuleName
const TCHAR* IDisplayClusterShaders::ModuleName = TEXT("DisplayClusterShaders") static constexpr
Definition at line 31 of file IDisplayClusterShaders.h.
Referenced by Get(), and IsAvailable().
ProjectionPlaneSize
FSceneInterface FRenderTarget float IDisplayClusterShaders::ProjectionPlaneSize
Definition at line 91 of file IDisplayClusterShaders.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterShaders/Public/IDisplayClusterShaders.h