Unreal Engine 5.6 C++ API: UE::FConditionVariable Class Reference
UE::FConditionVariable Class Reference final
A one-byte portable condition variable.
#include "ConditionVariable.h"
Public Member Functions
constexpr FConditionVariable ()=default
FConditionVariable (const FConditionVariable &)=delete
void NotifyAll ()
void NotifyOne ()
FConditionVariable & operator= (const FConditionVariable &)=delete
template<typename TLock>
void Wait (TLock &Lock)
Private Attributes
std::atomic< bool > bHasWaiters = false
Detailed Description
A one-byte portable condition variable.
Gives the same decent performance everywhere.
Definition at line 13 of file ConditionVariable.h.
Constructor & Destructor Documentation
FConditionVariable() [1/2]
UE::FConditionVariable::FConditionVariable () constexpr default
Referenced by FConditionVariable(), and operator=().
FConditionVariable() [2/2]
UE::FConditionVariable::FConditionVariable (const FConditionVariable &) delete
References FConditionVariable().
Member Function Documentation
NotifyAll()
void UE::FConditionVariable::NotifyAll () inline
Definition at line 36 of file ConditionVariable.h.
References bHasWaiters, and UE::ParkingLot::WakeAll().
NotifyOne()
void UE::FConditionVariable::NotifyOne () inline
Definition at line 21 of file ConditionVariable.h.
References bHasWaiters, UE::ParkingLot::FWakeState::bHasWaitingThreads, and UE::ParkingLot::WakeOne().
operator=()
FConditionVariable & UE::FConditionVariable::operator= (const FConditionVariable &) delete
References FConditionVariable().
Wait()
template<typename TLock> void UE::FConditionVariable::Wait (TLock & Lock) inline
Definition at line 46 of file ConditionVariable.h.
References bHasWaiters, and UE::ParkingLot::Wait().
Field Documentation
bHasWaiters
std::atomic<bool> UE::FConditionVariable::bHasWaiters = false private
Definition at line 63 of file ConditionVariable.h.
Referenced by NotifyAll(), NotifyOne(), and Wait().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Async/ConditionVariable.h