Unreal Engine 5.6 C++ API: IWorldPartitionActorDescInstanceView Class Reference
IWorldPartitionActorDescInstanceView Class Reference abstract
Interface for a view on top of an actor descriptor instance, used to cache information that can be different than the actor descriptor instance itself.
#include "WorldPartitionActorDescInstanceViewInterface.h"
Public Member Functions
virtual ~IWorldPartitionActorDescInstanceView ()
virtual void CheckForErrors (IStreamingGenerationErrorHandler *ErrorHandler) const =0
virtual AActor * GetActor (bool bEvenIfPendingKill=true, bool bEvenIfUnreachable=false) const =0
virtual const FWorldPartitionActorDesc * GetActorDesc () const =0
virtual bool GetActorIsEditorOnly () const =0
virtual bool GetActorIsEditorOnlyLoadedInPIE () const =0
virtual bool GetActorIsHLODRelevant () const =0
virtual bool GetActorIsRuntimeOnly () const =0
virtual FName GetActorLabel () const =0
virtual FName GetActorLabelOrName () const
virtual FName GetActorName () const =0
virtual UClass * GetActorNativeClass () const =0
virtual FName GetActorPackage () const =0
virtual FSoftObjectPath GetActorSoftPath () const =0
virtual FTopLevelAssetPath GetBaseClass () const =0
virtual const FWorldPartitionActorFilter * GetChildContainerFilter () const =0
virtual EWorldPartitionActorFilterType GetChildContainerFilterType () const =0
virtual bool GetChildContainerInstance (FWorldPartitionActorDesc::FContainerInstance &OutContainerInstance) const =0
virtual FName GetChildContainerPackage () const =0
virtual UActorDescContainerInstance * GetContainerInstance () const =0
virtual FGuid GetContentBundleGuid () const =0
virtual const FDataLayerInstanceNames & GetDataLayerInstanceNames () const =0
virtual TArray< FName > GetDataLayers () const =0
virtual FBox GetEditorBounds () const =0
virtual const TArray< FGuid > & GetEditorOnlyReferences () const =0
virtual const FSoftObjectPath & GetExternalDataLayerAsset () const =0
virtual const FGuid & GetFolderGuid () const =0
virtual FName GetFolderPath () const =0
virtual const FGuid & GetGuid () const =0
virtual FSoftObjectPath GetHLODLayer () const =0
virtual bool GetIsSpatiallyLoaded () const =0
virtual FTopLevelAssetPath GetNativeClass () const =0
virtual const FGuid & GetParentActor () const =0
virtual bool GetProperty (FName PropertyName, FName *PropertyValue) const =0
virtual const TArray< FGuid > & GetReferences () const =0
virtual FBox GetRuntimeBounds () const =0
virtual FName GetRuntimeGrid () const =0
virtual const FGuid & GetSceneOutlinerParent () const =0
virtual const TArray< FName > & GetTags () const =0
virtual bool HasProperty (FName PropertyName) const =0
virtual bool HasResolvedDataLayerInstanceNames () const =0
virtual bool IsChildContainerInstance () const =0
virtual bool IsEditorOnlyReference (const FGuid &ReferenceGuid) const =0
virtual bool IsEditorRelevant () const =0
virtual bool IsListedInSceneOutliner () const =0
virtual bool IsLoaded (bool bEvenIfPendingKill=false) const =0
virtual bool IsMainWorldOnly () const =0
virtual bool IsRuntimeRelevant () const =0
virtual bool IsUsingDataLayerAsset () const =0
virtual FString ToString (FWorldPartitionActorDesc::EToStringMode Mode) const =0
Detailed Description
Interface for a view on top of an actor descriptor instance, used to cache information that can be different than the actor descriptor instance itself.
Definition at line 18 of file WorldPartitionActorDescInstanceViewInterface.h.
Constructor & Destructor Documentation
~IWorldPartitionActorDescInstanceView()
virtual IWorldPartitionActorDescInstanceView::~IWorldPartitionActorDescInstanceView () inline virtual
Definition at line 21 of file WorldPartitionActorDescInstanceViewInterface.h.
Member Function Documentation
CheckForErrors()
virtual void IWorldPartitionActorDescInstanceView::CheckForErrors (IStreamingGenerationErrorHandler * ErrorHandler) const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActor()
virtual AActor * IWorldPartitionActorDescInstanceView::GetActor (bool bEvenIfPendingKill = true, bool bEvenIfUnreachable = false) const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorDesc()
virtual const FWorldPartitionActorDesc * IWorldPartitionActorDescInstanceView::GetActorDesc () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorIsEditorOnly()
virtual bool IWorldPartitionActorDescInstanceView::GetActorIsEditorOnly () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorIsEditorOnlyLoadedInPIE()
virtual bool IWorldPartitionActorDescInstanceView::GetActorIsEditorOnlyLoadedInPIE () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorIsHLODRelevant()
virtual bool IWorldPartitionActorDescInstanceView::GetActorIsHLODRelevant () const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
GetActorIsRuntimeOnly()
virtual bool IWorldPartitionActorDescInstanceView::GetActorIsRuntimeOnly () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorLabel()
virtual FName IWorldPartitionActorDescInstanceView::GetActorLabel () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
Referenced by GetActorLabelOrName().
GetActorLabelOrName()
virtual FName IWorldPartitionActorDescInstanceView::GetActorLabelOrName () const inline virtual
Definition at line 79 of file WorldPartitionActorDescInstanceViewInterface.h.
References GetActorLabel(), GetActorName(), and FName::IsNone().
GetActorName()
virtual FName IWorldPartitionActorDescInstanceView::GetActorName () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
Referenced by GetActorLabelOrName().
GetActorNativeClass()
virtual UClass * IWorldPartitionActorDescInstanceView::GetActorNativeClass () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorPackage()
virtual FName IWorldPartitionActorDescInstanceView::GetActorPackage () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetActorSoftPath()
virtual FSoftObjectPath IWorldPartitionActorDescInstanceView::GetActorSoftPath () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetBaseClass()
virtual FTopLevelAssetPath IWorldPartitionActorDescInstanceView::GetBaseClass () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetChildContainerFilter()
virtual const FWorldPartitionActorFilter * IWorldPartitionActorDescInstanceView::GetChildContainerFilter () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetChildContainerFilterType()
virtual EWorldPartitionActorFilterType IWorldPartitionActorDescInstanceView::GetChildContainerFilterType () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetChildContainerInstance()
virtual bool IWorldPartitionActorDescInstanceView::GetChildContainerInstance (FWorldPartitionActorDesc::FContainerInstance & OutContainerInstance) const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetChildContainerPackage()
virtual FName IWorldPartitionActorDescInstanceView::GetChildContainerPackage () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetContainerInstance()
virtual UActorDescContainerInstance * IWorldPartitionActorDescInstanceView::GetContainerInstance () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetContentBundleGuid()
virtual FGuid IWorldPartitionActorDescInstanceView::GetContentBundleGuid () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetDataLayerInstanceNames()
virtual const FDataLayerInstanceNames & IWorldPartitionActorDescInstanceView::GetDataLayerInstanceNames () const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
GetDataLayers()
virtual TArray< FName > IWorldPartitionActorDescInstanceView::GetDataLayers () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetEditorBounds()
virtual FBox IWorldPartitionActorDescInstanceView::GetEditorBounds () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetEditorOnlyReferences()
virtual const TArray< FGuid > & IWorldPartitionActorDescInstanceView::GetEditorOnlyReferences () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetExternalDataLayerAsset()
virtual const FSoftObjectPath & IWorldPartitionActorDescInstanceView::GetExternalDataLayerAsset () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetFolderGuid()
virtual const FGuid & IWorldPartitionActorDescInstanceView::GetFolderGuid () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetFolderPath()
virtual FName IWorldPartitionActorDescInstanceView::GetFolderPath () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetGuid()
virtual const FGuid & IWorldPartitionActorDescInstanceView::GetGuid () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetHLODLayer()
virtual FSoftObjectPath IWorldPartitionActorDescInstanceView::GetHLODLayer () const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
GetIsSpatiallyLoaded()
virtual bool IWorldPartitionActorDescInstanceView::GetIsSpatiallyLoaded () const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
GetNativeClass()
virtual FTopLevelAssetPath IWorldPartitionActorDescInstanceView::GetNativeClass () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetParentActor()
virtual const FGuid & IWorldPartitionActorDescInstanceView::GetParentActor () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetProperty()
virtual bool IWorldPartitionActorDescInstanceView::GetProperty (FName PropertyName, FName * PropertyValue) const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
References PropertyName.
GetReferences()
virtual const TArray< FGuid > & IWorldPartitionActorDescInstanceView::GetReferences () const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
GetRuntimeBounds()
virtual FBox IWorldPartitionActorDescInstanceView::GetRuntimeBounds () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetRuntimeGrid()
virtual FName IWorldPartitionActorDescInstanceView::GetRuntimeGrid () const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
GetSceneOutlinerParent()
virtual const FGuid & IWorldPartitionActorDescInstanceView::GetSceneOutlinerParent () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
GetTags()
virtual const TArray< FName > & IWorldPartitionActorDescInstanceView::GetTags () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
HasProperty()
virtual bool IWorldPartitionActorDescInstanceView::HasProperty (FName PropertyName) const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
References PropertyName.
HasResolvedDataLayerInstanceNames()
virtual bool IWorldPartitionActorDescInstanceView::HasResolvedDataLayerInstanceNames () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsChildContainerInstance()
virtual bool IWorldPartitionActorDescInstanceView::IsChildContainerInstance () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsEditorOnlyReference()
virtual bool IWorldPartitionActorDescInstanceView::IsEditorOnlyReference (const FGuid & ReferenceGuid) const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
IsEditorRelevant()
virtual bool IWorldPartitionActorDescInstanceView::IsEditorRelevant () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsListedInSceneOutliner()
virtual bool IWorldPartitionActorDescInstanceView::IsListedInSceneOutliner () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsLoaded()
virtual bool IWorldPartitionActorDescInstanceView::IsLoaded (bool bEvenIfPendingKill = false) const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsMainWorldOnly()
virtual bool IWorldPartitionActorDescInstanceView::IsMainWorldOnly () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsRuntimeRelevant()
virtual bool IWorldPartitionActorDescInstanceView::IsRuntimeRelevant () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
IsUsingDataLayerAsset()
virtual bool IWorldPartitionActorDescInstanceView::IsUsingDataLayerAsset () const pure virtual
Implemented in FWorldPartitionActorDescInstanceView.
ToString()
virtual FString IWorldPartitionActorDescInstanceView::ToString (FWorldPartitionActorDesc::EToStringMode Mode) const pure virtual
Implemented in FStreamingGenerationActorDescView, and FWorldPartitionActorDescInstanceView.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionActorDescInstanceViewInterface.h