Unreal Engine 5.6 C++ API: UStereoLayerShapeCylinder Class Reference
UStereoLayerShapeCylinder Class Reference
#include "StereoLayerComponent.h"
Private Member Functions
virtual void ApplyShape (IStereoLayers::FLayerDesc &LayerDesc) override
virtual void DrawShapeVisualization (const class FSceneView *View, class FPrimitiveDrawInterface *PDI) override
GENERATED_BODY () public
UFUNCTION () 1 void SetHeight(int InHeight)
UFUNCTION () 1 void SetOverlayArc(float InOverlayArc)
UFUNCTION () 1 void SetRadius(float InRadius)
UPROPERTY () float OverlayArc
Arc angle for the stereo layer cylinder.
UPROPERTY () float Radius
Radial size of the rendered stereo layer cylinder.
UPROPERTY () int Height
Height of the stereo layer cylinder.
Detailed Description
Definition at line 85 of file StereoLayerComponent.h.
Member Function Documentation
ApplyShape()
virtual void UStereoLayerShapeCylinder::ApplyShape (IStereoLayers::FLayerDesc & LayerDesc) override private virtual
References ApplyShape().
Referenced by ApplyShape().
DrawShapeVisualization()
virtual void UStereoLayerShapeCylinder::DrawShapeVisualization (const class FSceneView * View, class FPrimitiveDrawInterface * PDI) override private virtual
GENERATED_BODY()
UStereoLayerShapeCylinder::GENERATED_BODY () inline private
Definition at line 87 of file StereoLayerComponent.h.
UFUNCTION() [1/3]
UStereoLayerShapeCylinder::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [2/3]
UStereoLayerShapeCylinder::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [3/3]
UStereoLayerShapeCylinder::UFUNCTION () private
References Category, and UFUNCTION().
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
UPROPERTY() [1/3]
UStereoLayerShapeCylinder::UPROPERTY () private
Arc angle for the stereo layer cylinder.
References Category, and UPROPERTY().
UPROPERTY() [2/3]
UStereoLayerShapeCylinder::UPROPERTY () private
Radial size of the rendered stereo layer cylinder.
References Category, and float.
Referenced by UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/3]
UStereoLayerShapeCylinder::UPROPERTY () private
Height of the stereo layer cylinder.
References Category, and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/StereoLayerComponent.h