Unreal Engine 5.6 C++ API: UE::Sequencer::FInputHandlerStack Class Reference
UE::Sequencer::FInputHandlerStack Class Reference
Class responsible for handling input to multiple objects that reside at the same level in the widget hierarchy.
#include "SequencerInputHandlerStack.h"
Public Member Functions
FInputHandlerStack ()
void AddHandler (ISequencerInputHandler *Handler)
Add a handler to the stack.
int32 GetCapturedIndex () const
Get the index of the currently captured handler, or INDEX_NONE.
FReply HandleKeyDown (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
FReply HandleKeyUp (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
FReply HandleMouseButtonDown (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Handle a mouse down.
FReply HandleMouseButtonUp (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Handle a mouse up.
FReply HandleMouseDoubleClick (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Handle a mouse double click.
FReply HandleMouseMove (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Handle a mouse move.
FReply HandleMouseWheel (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Handle a mouse wheel.
void SetHandlerAt (int32 Index, ISequencerInputHandler *Handler)
Reset an existing entry in the stack to a new handler.
Data Fields
FSimpleMulticastDelegate OnBeginCapture
FSimpleMulticastDelegate OnEndCapture
Private Types
typedef FReply(ISequencerInputHandler::* InputHandlerFunction) (SWidget &, const FGeometry &, const FPointerEvent &)
typedef FReply(ISequencerInputHandler::* KeyInputHandlerFunction) (SWidget &, const FGeometry &, const FKeyEvent &)
Private Member Functions
FReply ProcessEvent (InputHandlerFunction Function, SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
FReply ProcessKeyEvent (KeyInputHandlerFunction Function, SWidget &OwnerWidget, const FGeometry &MyGeometry, const FKeyEvent &KeyEvent)
const FReply & ProcessReply (const FReply &Reply, int32 ThisIndex)
Private Attributes
int32 CapturedIndex
Index of the handler that currently has the mouse captured.
TArray< ISequencerInputHandler * > Handlers
Array o9f input handlers.
Detailed Description
Class responsible for handling input to multiple objects that reside at the same level in the widget hierarchy.
The sequencer track area is one such example of a single widget that delegates its input handling to multiple sources (edit tool, or time slider controller). To alleviate the complexity of handling input for such sources, where each may fight for mouse capture, this class keeps track of which handler captured the mouse and routs input accordingly.
When no mouse capture is active, handlers are called sequentially in the order they were added, until the event is handled.
Definition at line 31 of file SequencerInputHandlerStack.h.
Member Typedef Documentation
InputHandlerFunction
typedef FReply(ISequencerInputHandler::* UE::Sequencer::FInputHandlerStack::InputHandlerFunction) (SWidget &, const FGeometry &, const FPointerEvent &) private
Definition at line 105 of file SequencerInputHandlerStack.h.
KeyInputHandlerFunction
typedef FReply(ISequencerInputHandler::* UE::Sequencer::FInputHandlerStack::KeyInputHandlerFunction) (SWidget &, const FGeometry &, const FKeyEvent &) private
Definition at line 106 of file SequencerInputHandlerStack.h.
Constructor & Destructor Documentation
FInputHandlerStack()
UE::Sequencer::FInputHandlerStack::FInputHandlerStack () inline
Definition at line 38 of file SequencerInputHandlerStack.h.
References CapturedIndex, and INDEX_NONE.
Member Function Documentation
AddHandler()
void UE::Sequencer::FInputHandlerStack::AddHandler (ISequencerInputHandler * Handler) inline
Add a handler to the stack.
Definition at line 41 of file SequencerInputHandlerStack.h.
References Handlers.
GetCapturedIndex()
int32 UE::Sequencer::FInputHandlerStack::GetCapturedIndex () const inline
Get the index of the currently captured handler, or INDEX_NONE.
Definition at line 62 of file SequencerInputHandlerStack.h.
References CapturedIndex.
HandleKeyDown()
FReply UE::Sequencer::FInputHandlerStack::HandleKeyDown (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline
Definition at line 94 of file SequencerInputHandlerStack.h.
References ISequencerInputHandler::OnKeyDown(), and ProcessKeyEvent().
HandleKeyUp()
FReply UE::Sequencer::FInputHandlerStack::HandleKeyUp (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline
Definition at line 99 of file SequencerInputHandlerStack.h.
References ISequencerInputHandler::OnKeyUp(), and ProcessKeyEvent().
HandleMouseButtonDown()
FReply UE::Sequencer::FInputHandlerStack::HandleMouseButtonDown (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline
Handle a mouse down.
Definition at line 65 of file SequencerInputHandlerStack.h.
References MouseEvent, ISequencerInputHandler::OnMouseButtonDown(), and ProcessEvent().
HandleMouseButtonUp()
FReply UE::Sequencer::FInputHandlerStack::HandleMouseButtonUp (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline
Handle a mouse up.
Definition at line 71 of file SequencerInputHandlerStack.h.
References MouseEvent, ISequencerInputHandler::OnMouseButtonUp(), and ProcessEvent().
HandleMouseDoubleClick()
FReply UE::Sequencer::FInputHandlerStack::HandleMouseDoubleClick (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline
Handle a mouse double click.
Definition at line 77 of file SequencerInputHandlerStack.h.
References MouseEvent, ISequencerInputHandler::OnMouseButtonDoubleClick(), and ProcessEvent().
HandleMouseMove()
FReply UE::Sequencer::FInputHandlerStack::HandleMouseMove (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline
Handle a mouse move.
Definition at line 83 of file SequencerInputHandlerStack.h.
References MouseEvent, ISequencerInputHandler::OnMouseMove(), and ProcessEvent().
HandleMouseWheel()
FReply UE::Sequencer::FInputHandlerStack::HandleMouseWheel (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline
Handle a mouse wheel.
Definition at line 89 of file SequencerInputHandlerStack.h.
References MouseEvent, ISequencerInputHandler::OnMouseWheel(), and ProcessEvent().
ProcessEvent()
FReply UE::Sequencer::FInputHandlerStack::ProcessEvent (InputHandlerFunction Function, SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline private
Definition at line 108 of file SequencerInputHandlerStack.h.
References CapturedIndex, Function, Handlers, INDEX_NONE, FReplyBase::IsEventHandled(), MouseEvent, ProcessReply(), and FReply::Unhandled().
Referenced by HandleMouseButtonDown(), HandleMouseButtonUp(), HandleMouseDoubleClick(), HandleMouseMove(), and HandleMouseWheel().
ProcessKeyEvent()
FReply UE::Sequencer::FInputHandlerStack::ProcessKeyEvent (KeyInputHandlerFunction Function, SWidget & OwnerWidget, const FGeometry & MyGeometry, const FKeyEvent & KeyEvent) inline private
Definition at line 155 of file SequencerInputHandlerStack.h.
References CapturedIndex, Function, Handlers, INDEX_NONE, FReplyBase::IsEventHandled(), and FReply::Unhandled().
Referenced by HandleKeyDown(), and HandleKeyUp().
ProcessReply()
const FReply & UE::Sequencer::FInputHandlerStack::ProcessReply (const FReply & Reply, int32 ThisIndex) inline private
Definition at line 139 of file SequencerInputHandlerStack.h.
References CapturedIndex, FReply::GetMouseCaptor(), INDEX_NONE, TSharedPtr< ObjectType, InMode >::IsValid(), OnBeginCapture, OnEndCapture, and FReply::ShouldReleaseMouse().
Referenced by ProcessEvent().
SetHandlerAt()
void UE::Sequencer::FInputHandlerStack::SetHandlerAt (int32 Index, ISequencerInputHandler * Handler) inline
Reset an existing entry in the stack to a new handler.
Definition at line 44 of file SequencerInputHandlerStack.h.
References CapturedIndex, Handlers, INDEX_NONE, and OnEndCapture.
Field Documentation
CapturedIndex
int32 UE::Sequencer::FInputHandlerStack::CapturedIndex private
Index of the handler that currently has the mouse captured.
Definition at line 187 of file SequencerInputHandlerStack.h.
Referenced by FInputHandlerStack(), GetCapturedIndex(), ProcessEvent(), ProcessKeyEvent(), ProcessReply(), and SetHandlerAt().
Handlers
TArray<ISequencerInputHandler*> UE::Sequencer::FInputHandlerStack::Handlers private
Array o9f input handlers.
Definition at line 190 of file SequencerInputHandlerStack.h.
Referenced by AddHandler(), ProcessEvent(), ProcessKeyEvent(), and SetHandlerAt().
OnBeginCapture
FSimpleMulticastDelegate UE::Sequencer::FInputHandlerStack::OnBeginCapture
Definition at line 35 of file SequencerInputHandlerStack.h.
Referenced by ProcessReply().
OnEndCapture
FSimpleMulticastDelegate UE::Sequencer::FInputHandlerStack::OnEndCapture
Definition at line 36 of file SequencerInputHandlerStack.h.
Referenced by ProcessReply(), and SetHandlerAt().
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/Views/SequencerInputHandlerStack.h