Unreal Engine 5.6 C++ API: FHairStrandsCore Class Reference
FHairStrandsCore Class Reference
Implements the HairStrands module.
#include "HairStrandsCore.h"
Public Member Functions
virtual void ShutdownModule () override
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule () override
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsDynamicReloading () override
Override this to set whether your module is allowed to be unloaded on the fly.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
Static Public Member Functions
static HAIRSTRANDSCORE_API FHairAssetHelper & AssetHelper ()
static HAIRSTRANDSCORE_API UGroomBindingAsset * CreateGroomBindingAsset (const FString &InPackageName, UObject *InParent, UGroomAsset *GroomAsset, USkeletalMesh *SourceSkelMesh, USkeletalMesh *TargetSkelMesh, const int32 NumInterpolationPoints, const int32 MatchingSection)
static HAIRSTRANDSCORE_API UGroomBindingAsset * CreateGroomBindingAsset (EGroomBindingMeshType BindingType, const FString &InPackageName, UObject *InParent, UGroomAsset *GroomAsset, UObject *Source, UObject *Target, const int32 NumInterpolationPoints, const int32 MatchingSection, const FName TargetMeshAttribute=NAME_None)
static HAIRSTRANDSCORE_API UGroomBindingAsset * CreateGroomBindingAsset (EGroomBindingMeshType BindingType, UGroomAsset *GroomAsset, UObject *Source, UObject *Target, const int32 NumInterpolationPoints, const int32 MatchingSection, const FName TargetMeshAttribute=NAME_None)
static HAIRSTRANDSCORE_API UGroomBindingAsset * CreateGroomBindingAsset (UGroomAsset *GroomAsset, USkeletalMesh *SourceSkelMesh, USkeletalMesh *TargetSkelMesh, const int32 NumInterpolationPoints, const int32 MatchingSection)
static UStaticMesh * CreateStaticMesh (const FString &InPackageName, const FString &Suffix)
static UTexture2D * CreateTexture (const FString &PackgeName, const FIntPoint &Resolution, const FString &Suffix, TTextureAllocation TextureAllocation)
static HAIRSTRANDSCORE_API void RegisterAssetHelper (const FHairAssetHelper &Helper)
static void ResizeTexture (UTexture2D *InTexture, const FIntPoint &Resolution, TTextureAllocation TextureAllocation)
static HAIRSTRANDSCORE_API void SaveAsset (UObject *Object)
Detailed Description
Implements the HairStrands module.
Definition at line 35 of file HairStrandsCore.h.
Member Function Documentation
AssetHelper()
HAIRSTRANDSCORE_API FHairAssetHelper & FHairStrandsCore::AssetHelper () static
References AssetHelper().
Referenced by AssetHelper().
CreateGroomBindingAsset() [1/4]
HAIRSTRANDSCORE_API UGroomBindingAsset * FHairStrandsCore::CreateGroomBindingAsset (const FString & InPackageName, UObject * InParent, UGroomAsset * GroomAsset, USkeletalMesh * SourceSkelMesh, USkeletalMesh * TargetSkelMesh, const int32 NumInterpolationPoints, const int32 MatchingSection) static
References CreateGroomBindingAsset().
CreateGroomBindingAsset() [2/4]
HAIRSTRANDSCORE_API UGroomBindingAsset * FHairStrandsCore::CreateGroomBindingAsset (EGroomBindingMeshType BindingType, const FString & InPackageName, UObject * InParent, UGroomAsset * GroomAsset, UObject * Source, UObject * Target, const int32 NumInterpolationPoints, const int32 MatchingSection, const FName TargetMeshAttribute = NAME_None) static
References CreateGroomBindingAsset(), Source, and Target.
CreateGroomBindingAsset() [3/4]
HAIRSTRANDSCORE_API UGroomBindingAsset * FHairStrandsCore::CreateGroomBindingAsset (EGroomBindingMeshType BindingType, UGroomAsset * GroomAsset, UObject * Source, UObject * Target, const int32 NumInterpolationPoints, const int32 MatchingSection, const FName TargetMeshAttribute = NAME_None) static
References CreateGroomBindingAsset(), Source, and Target.
CreateGroomBindingAsset() [4/4]
HAIRSTRANDSCORE_API UGroomBindingAsset * FHairStrandsCore::CreateGroomBindingAsset (UGroomAsset * GroomAsset, USkeletalMesh * SourceSkelMesh, USkeletalMesh * TargetSkelMesh, const int32 NumInterpolationPoints, const int32 MatchingSection) static
References CreateGroomBindingAsset(), and UE_DEPRECATED.
Referenced by CreateGroomBindingAsset(), CreateGroomBindingAsset(), CreateGroomBindingAsset(), and CreateGroomBindingAsset().
CreateStaticMesh()
UStaticMesh * FHairStrandsCore::CreateStaticMesh (const FString & InPackageName, const FString & Suffix) static
CreateTexture()
UTexture2D * FHairStrandsCore::CreateTexture (const FString & PackgeName, const FIntPoint & Resolution, const FString & Suffix, TTextureAllocation TextureAllocation) static
RegisterAssetHelper()
HAIRSTRANDSCORE_API void FHairStrandsCore::RegisterAssetHelper (const FHairAssetHelper & Helper) static
ResizeTexture()
void FHairStrandsCore::ResizeTexture (UTexture2D * InTexture, const FIntPoint & Resolution, TTextureAllocation TextureAllocation) static
SaveAsset()
HAIRSTRANDSCORE_API void FHairStrandsCore::SaveAsset (UObject * Object) static
References Object, and SaveAsset().
Referenced by SaveAsset().
ShutdownModule()
virtual void FHairStrandsCore::ShutdownModule () override virtual
Called before the module is unloaded, right before the module object is destroyed.
During normal shutdown, this is called in reverse order that modules finish StartupModule(). This means that, as long as a module references dependent modules in it's StartupModule(), it can safely reference those dependencies in ShutdownModule() as well.
Reimplemented from IModuleInterface.
StartupModule()
virtual void FHairStrandsCore::StartupModule () override virtual
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
ie:
FModuleManager::Get().LoadModuleChecked(TEXT("HTTP"));
Reimplemented from IModuleInterface.
SupportsDynamicReloading()
virtual bool FHairStrandsCore::SupportsDynamicReloading () inline override virtual
Override this to set whether your module is allowed to be unloaded on the fly.
Returns
Whether the module supports shutdown separate from the rest of the engine.
Reimplemented from IModuleInterface.
Definition at line 43 of file HairStrandsCore.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/HairStrandsCore.h