Unreal Engine 5.6 C++ API: TProperty_Numeric< InTCppType > Class Template Reference
TProperty_Numeric< InTCppType > Class Template Reference
#include "UnrealType.h"
Data Structures
struct TConvertAndSet
struct TConvertAndSet< SameType, SameType >
Public Types
typedef TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty > Super
typedef InTCppType TCppType
typedef Super::TTypeFundamentals TTypeFundamentals
Public Types inherited from TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >
typedef TProperty< InTCppType, FNumericProperty > Super
typedef InTCppType TCppType
typedef Super::TTypeFundamentals TTypeFundamentals
Public Types inherited from TProperty< InTCppType, TInPropertyBaseClass >
typedef TInPropertyBaseClass Super
typedef InTCppType TCppType
typedef TPropertyTypeFundamentals< InTCppType > TTypeFundamentals
Public Types inherited from TPropertyTypeFundamentals< InTCppType >
enum { CPPSize = sizeof(TCppType) , CPPAlignment = alignof(TCppType) }
typedef InTCppType TCppType
Type of the CPP property.
Public Member Functions
TProperty_Numeric (EInternal InInernal, FFieldClass *InClass)
TProperty_Numeric (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
TProperty_Numeric (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop)
Constructor used for constructing compiled in properties.
virtual EConvertFromTypeResult ConvertFromType (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, const uint8 *Defaults) override
virtual double GetFloatingPointPropertyValue (void const *Data) const override
virtual FString GetNumericPropertyValueToString (void const *Data) const override
virtual FString GetNumericPropertyValueToString_InContainer (void const *Container) const override
virtual int64 GetSignedIntPropertyValue (void const *Data) const override
virtual int64 GetSignedIntPropertyValue_InContainer (void const *Container) const override
virtual uint64 GetUnsignedIntPropertyValue (void const *Data) const override
virtual uint64 GetUnsignedIntPropertyValue_InContainer (void const *Container) const override
virtual uint32 GetValueTypeHashInternal (const void *Src) const override
virtual bool IsFloatingPoint () const override
virtual bool IsInteger () const override
virtual void SetFloatingPointPropertyValue (void *Data, double Value) const override
virtual void SetIntPropertyValue (void *Data, int64 Value) const override
virtual void SetIntPropertyValue (void *Data, uint64 Value) const override
virtual void SetNumericPropertyValueFromString (void *Data, TCHAR const *Value) const override
virtual void SetNumericPropertyValueFromString_InContainer (void *Container, TCHAR const *Value) const override
Public Member Functions inherited from TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >
TProperty_WithEqualityAndSerializer (EInternal InInernal, FFieldClass *InClass)
TProperty_WithEqualityAndSerializer (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
TProperty_WithEqualityAndSerializer (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop)
Constructor used for constructing compiled in properties.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags=0) const override
virtual void SerializeItem (FStructuredArchive::FSlot Slot, void *Value, void const *Defaults) const override
Public Member Functions inherited from TProperty< InTCppType, TInPropertyBaseClass >
TProperty (EInternal InInernal, FFieldClass *InClass)
TProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
template<typename PropertyParamsType>
TProperty (FFieldVariant InOwner, PropertyParamsType &Prop)
Constructor used for constructing compiled in properties.
virtual void ClearIntrusiveOptionalValue (void *Data) const override
virtual void ClearValueInternal (void *Data) const override
virtual void CopyValuesInternal (void *Dest, void const *Src, int32 Count) const override
virtual void DestroyValueInternal (void *Dest) const override
virtual FString GetCPPType (FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const override
virtual int32 GetMinAlignment () const override
FORCEINLINE TCppType GetOptionalPropertyValue_InContainer (void const *B, int32 ArrayIndex=0) const
Get the value of the property from a container address, unless it is NULL, then return the default value.
FORCEINLINE TCppType const & GetPropertyValue_InContainer (void const *A, int32 ArrayIndex=0) const
Get the value of the property from a container address.
FORCEINLINE TCppType * GetPropertyValuePtr_InContainer (void *A, int32 ArrayIndex=0) const
Convert the address of a container to the address of the property value, in the proper type.
FORCEINLINE TCppType const * GetPropertyValuePtr_InContainer (void const *A, int32 ArrayIndex=0) const
Convert the address of a container to the address of the property value, in the proper type.
FORCEINLINE void GetValue_InContainer (void const *InContainer, TCppType *OutValue) const
virtual bool HasIntrusiveUnsetOptionalState () const override
virtual void InitializeIntrusiveUnsetOptionalValue (void *Data) const override
virtual void InitializeValueInternal (void *Dest) const override
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const override
virtual void LinkInternal (FArchive &Ar) override
FORCEINLINE void SetPropertyValue_InContainer (void *A, TCppType const &Value, int32 ArrayIndex=0) const
Set the value of a property in a container.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const TCppType &InValue) const
Protected Member Functions
template<typename OldNumericType>
FORCEINLINE void ConvertFromArithmeticValue (FStructuredArchive::FSlot Slot, void *Obj, const FPropertyTag &Tag) const
Private Member Functions
virtual bool CanHoldDoubleValueInternal (double Value) const
virtual bool CanHoldSignedValueInternal (int64 Value) const
virtual bool CanHoldUnsignedValueInternal (uint64 Value) const
Additional Inherited Members
Static Public Member Functions inherited from TPropertyTypeFundamentals< InTCppType >
static FORCEINLINE void ClearIntrusiveOptionalValue (void *A)
static FORCEINLINE void DestroyPropertyValue (void *A)
Destroy the value of a property at an address.
static FORCEINLINE TCppType GetDefaultPropertyValue ()
Get the default value of the cpp type, just the default constructor, which works even for things like in32.
static FORCEINLINE TCppType GetOptionalPropertyValue (void const *B)
Get the value of the property from an address, unless it is NULL, then return the default value.
static FORCEINLINE TCppType const & GetPropertyValue (void const *A)
Get the value of the property from an address.
static FORCEINLINE TCppType * GetPropertyValuePtr (void *A)
Convert the address of a value of the property to the proper type.
static FORCEINLINE TCppType const * GetPropertyValuePtr (void const *A)
Convert the address of a value of the property to the proper type.
static FORCEINLINE TCHAR const * GetTypeName ()
static FORCEINLINE bool HasIntrusiveUnsetOptionalState ()
static FORCEINLINE void InitializeIntrusiveUnsetOptionalValue (void *Data)
static FORCEINLINE TCppType * InitializePropertyValue (void *A)
Initialize the value of a property at an address, this assumes over uninitialized memory.
static FORCEINLINE bool IsIntrusiveOptionalValueSet (const void *A)
static FORCEINLINE void SetPropertyValue (void *A, TCppType const &Value)
Set the value of a property at an address.
Static Protected Member Functions inherited from TPropertyTypeFundamentals< InTCppType >
static FORCEINLINE EPropertyFlags GetComputedFlagsPropertyFlags ()
Get the property flags corresponding to this C++ type, from the C++ type traits system.
Detailed Description
template<typename InTCppType>
class TProperty_Numeric< InTCppType >
Definition at line 1802 of file UnrealType.h.
Member Typedef Documentation
Super
template<typename InTCppType> typedef TProperty_WithEqualityAndSerializer<InTCppType, FNumericProperty> TProperty_Numeric< InTCppType >::Super
Definition at line 1805 of file UnrealType.h.
TCppType
template<typename InTCppType> typedef InTCppType TProperty_Numeric< InTCppType >::TCppType
Definition at line 1806 of file UnrealType.h.
TTypeFundamentals
template<typename InTCppType> typedef Super::TTypeFundamentals TProperty_Numeric< InTCppType >::TTypeFundamentals
Definition at line 1807 of file UnrealType.h.
Constructor & Destructor Documentation
TProperty_Numeric() [1/3]
template<typename InTCppType> TProperty_Numeric< InTCppType >::TProperty_Numeric (EInternal InInernal, FFieldClass * InClass) inline
Definition at line 1809 of file UnrealType.h.
References EC_InternalUseOnlyConstructor.
Referenced by TProperty_Numeric< InTCppType >::TConvertAndSet< FromType, ToType >::TConvertAndSet(), and TProperty_Numeric< InTCppType >::TConvertAndSet< SameType, SameType >::TConvertAndSet().
TProperty_Numeric() [2/3]
template<typename InTCppType> TProperty_Numeric< InTCppType >::TProperty_Numeric (FFieldVariant InOwner, const FName & InName, EObjectFlags InObjectFlags) inline
Definition at line 1814 of file UnrealType.h.
References InName.
TProperty_Numeric() [3/3]
template<typename InTCppType> TProperty_Numeric< InTCppType >::TProperty_Numeric (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset & Prop) inline
Constructor used for constructing compiled in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
Definition at line 1824 of file UnrealType.h.
Member Function Documentation
CanHoldDoubleValueInternal()
template<typename InTCppType> virtual bool TProperty_Numeric< InTCppType >::CanHoldDoubleValueInternal (double Value) const inline private virtual
Definition at line 2037 of file UnrealType.h.
References Value.
CanHoldSignedValueInternal()
template<typename InTCppType> virtual bool TProperty_Numeric< InTCppType >::CanHoldSignedValueInternal (int64 Value) const inline private virtual
Definition at line 2042 of file UnrealType.h.
References Value.
CanHoldUnsignedValueInternal()
template<typename InTCppType> virtual bool TProperty_Numeric< InTCppType >::CanHoldUnsignedValueInternal (uint64 Value) const inline private virtual
Definition at line 2047 of file UnrealType.h.
References Value.
ConvertFromArithmeticValue()
template<typename InTCppType> template<typename OldNumericType> FORCEINLINE void TProperty_Numeric< InTCppType >::ConvertFromArithmeticValue (FStructuredArchive::FSlot Slot, void * Obj, const FPropertyTag & Tag) const inline protected
Definition at line 1844 of file UnrealType.h.
References FORCEINLINE.
Referenced by ConvertFromType().
ConvertFromType()
template<typename InTCppType> virtual EConvertFromTypeResult TProperty_Numeric< InTCppType >::ConvertFromType (const FPropertyTag & Tag, FStructuredArchive::FSlot Slot, uint8 * Data, UStruct * DefaultsStruct, const uint8 * Defaults) inline override virtual
Reimplemented in FByteProperty.
Definition at line 1886 of file UnrealType.h.
References FPropertyTag::ArrayIndex, FPropertyTag::BoolVal, Converted, ConvertFromArithmeticValue(), FName::GetNumber(), UE::FPropertyTypeName::GetParameterCount(), FPropertyTag::GetType(), NAME_NO_NUMBER_INTERNAL, PRAGMA_DISABLE_SWITCH_UNHANDLED_ENUM_CASE_WARNINGS, PRAGMA_RESTORE_SWITCH_UNHANDLED_ENUM_CASE_WARNINGS, Serialized, TProperty< InTCppType, TInPropertyBaseClass >::SetPropertyValue_InContainer(), FName::ToEName(), FPropertyTag::Type, and UseSerializeItem.
GetFloatingPointPropertyValue()
template<typename InTCppType> virtual double TProperty_Numeric< InTCppType >::GetFloatingPointPropertyValue (void const * Data) const inline override virtual
Definition at line 2029 of file UnrealType.h.
References check, TPropertyTypeFundamentals< InTCppType >::GetPropertyValue(), and TIsFloatingPoint< T >::Value.
GetNumericPropertyValueToString()
template<typename InTCppType> virtual FString TProperty_Numeric< InTCppType >::GetNumericPropertyValueToString (void const * Data) const inline override virtual
Definition at line 1995 of file UnrealType.h.
References TPropertyTypeFundamentals< InTCppType >::GetPropertyValue(), and LexToString().
GetNumericPropertyValueToString_InContainer()
template<typename InTCppType> virtual FString TProperty_Numeric< InTCppType >::GetNumericPropertyValueToString_InContainer (void const * Container) const inline override virtual
Definition at line 1999 of file UnrealType.h.
References Container, FProperty::GetValue_InContainer(), and LexToString().
GetSignedIntPropertyValue()
template<typename InTCppType> virtual int64 TProperty_Numeric< InTCppType >::GetSignedIntPropertyValue (void const * Data) const inline override virtual
Definition at line 2005 of file UnrealType.h.
References check, TPropertyTypeFundamentals< InTCppType >::GetPropertyValue(), and TIsIntegral< T >::Value.
GetSignedIntPropertyValue_InContainer()
template<typename InTCppType> virtual int64 TProperty_Numeric< InTCppType >::GetSignedIntPropertyValue_InContainer (void const * Container) const inline override virtual
Definition at line 2010 of file UnrealType.h.
References check, Container, FProperty::GetValue_InContainer(), and TIsIntegral< T >::Value.
GetUnsignedIntPropertyValue()
template<typename InTCppType> virtual uint64 TProperty_Numeric< InTCppType >::GetUnsignedIntPropertyValue (void const * Data) const inline override virtual
Definition at line 2017 of file UnrealType.h.
References check, TPropertyTypeFundamentals< InTCppType >::GetPropertyValue(), and TIsIntegral< T >::Value.
GetUnsignedIntPropertyValue_InContainer()
template<typename InTCppType> virtual uint64 TProperty_Numeric< InTCppType >::GetUnsignedIntPropertyValue_InContainer (void const * Container) const inline override virtual
Definition at line 2022 of file UnrealType.h.
References check, Container, FProperty::GetValue_InContainer(), and TIsIntegral< T >::Value.
GetValueTypeHashInternal()
template<typename InTCppType> virtual uint32 TProperty_Numeric< InTCppType >::GetValueTypeHashInternal (const void * Src) const inline override virtual
Reimplemented in FDoubleProperty, and FFloatProperty.
Definition at line 1837 of file UnrealType.h.
References GetTypeHash().
IsFloatingPoint()
template<typename InTCppType> virtual bool TProperty_Numeric< InTCppType >::IsFloatingPoint () const inline override virtual
Definition at line 1962 of file UnrealType.h.
References TIsFloatingPoint< T >::Value.
IsInteger()
template<typename InTCppType> virtual bool TProperty_Numeric< InTCppType >::IsInteger () const inline override virtual
Definition at line 1966 of file UnrealType.h.
References TIsIntegral< T >::Value.
SetFloatingPointPropertyValue()
template<typename InTCppType> virtual void TProperty_Numeric< InTCppType >::SetFloatingPointPropertyValue (void * Data, double Value) const inline override virtual
Definition at line 1980 of file UnrealType.h.
References check, TPropertyTypeFundamentals< InTCppType >::SetPropertyValue(), TIsFloatingPoint< T >::Value, and Value.
SetIntPropertyValue() [1/2]
template<typename InTCppType> virtual void TProperty_Numeric< InTCppType >::SetIntPropertyValue (void * Data, int64 Value) const inline override virtual
Definition at line 1975 of file UnrealType.h.
References check, TPropertyTypeFundamentals< InTCppType >::SetPropertyValue(), TIsIntegral< T >::Value, and Value.
SetIntPropertyValue() [2/2]
template<typename InTCppType> virtual void TProperty_Numeric< InTCppType >::SetIntPropertyValue (void * Data, uint64 Value) const inline override virtual
Definition at line 1970 of file UnrealType.h.
References check, TPropertyTypeFundamentals< InTCppType >::SetPropertyValue(), TIsIntegral< T >::Value, and Value.
SetNumericPropertyValueFromString()
template<typename InTCppType> virtual void TProperty_Numeric< InTCppType >::SetNumericPropertyValueFromString (void * Data, TCHAR const * Value) const inline override virtual
Definition at line 1985 of file UnrealType.h.
References TPropertyTypeFundamentals< InTCppType >::GetPropertyValuePtr(), LexFromString(), and Value.
SetNumericPropertyValueFromString_InContainer()
template<typename InTCppType> virtual void TProperty_Numeric< InTCppType >::SetNumericPropertyValueFromString_InContainer (void * Container, TCHAR const * Value) const inline override virtual
Definition at line 1989 of file UnrealType.h.
References Container, LexFromString(), FProperty::SetValue_InContainer(), and Value.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h