Unreal Engine 5.6 C++ API: UE::Geometry::TMeshTangents< RealType > Class Template Reference
UE::Geometry::TMeshTangents< RealType > Class Template Reference
TMeshTangents is a utility class that can calculate and store various types of tangent vectors for a FDynamicMesh.
#include "MeshTangents.h"
Public Member Functions
TMeshTangents ()
TMeshTangents (const FDynamicMesh3 *Mesh)
GEOMETRYCORE_API void ComputeTriangleTangents (const FDynamicMeshUVOverlay *UVOverlay, bool bOrthogonalize=true)
Compute per-triangle tangents for the given UV Overlay.
GEOMETRYCORE_API void ComputeTriVertexTangents (const FDynamicMeshNormalOverlay *NormalOverlay, const FDynamicMeshUVOverlay *UVOverlay, const FComputeTangentsOptions &Options)
Calculate per-triangle tangent spaces based on the given per-triangle normal and UV overlays.
GEOMETRYCORE_API bool CopyToOverlays (FDynamicMesh3 &MeshToSet) const
Set Tangents on mesh overlays.
GEOMETRYCORE_API bool CopyTriVertexTangents (const FDynamicMesh3 &SourceMesh)
Initialize Tangents from the FDynamicMeshAttributeSet of SourceMesh.
template<typename OtherRealType>
void CopyTriVertexTangents (const TMeshTangents< OtherRealType > &OtherTangents)
Initialize Tangents from other Tangents set.
const TArray< TVector< RealType > > & GetBitangents () const
const TArray< int32 > & GetDegenerateTris () const
void GetInterpolatedTriangleTangent (int32 TriangleID, const UE::Math::TVector< RealType > &BaryCoords, UE::Math::TVector< RealType > &TangentOut, UE::Math::TVector< RealType > &BitangentOut) const
void GetPerTriangleTangent (int32 TriangleID, int32 TriVertIdx, UE::Math::TVector< RealType > &TangentOut, UE::Math::TVector< RealType > &BitangentOut) const
Return tangent and bitangent at a vertex of triangle for per-triangle computed tangents.
template<typename VectorType, typename OtherRealType>
void GetPerTriangleTangent (int32 TriangleID, int32 TriVertIdx, VectorType &TangentOut, VectorType &BitangentOut) const
Return tangent and bitangent at a vertex of triangle for per-triangle computed tangents.
const TArray< TVector< RealType > > & GetTangents () const
template<typename OtherVectorType>
void GetTriangleVertexTangentVectors (int32 TriangleID, int32 TriVertexIndex, OtherVectorType &TangentOut, OtherVectorType &BitangentOut) const
Get tangent and bitangent at a vertex of a triangle for per-triangle computed tangents.
void InitializeTriangleTangents (bool bClearToZero)
Initialize buffer sizes to one tangent/bitangent per mesh triangle.
void InitializeTriVertexTangents (bool bClearToZero)
Set internal buffer sizes suitable for calculating per-triangle tangents.
void SetMesh (const FDynamicMesh3 *MeshIn)
void SetPerTriangleTangent (int TriangleID, int TriVertIdx, const TVector< RealType > &Tangent, const TVector< RealType > &Bitangent)
Set tangent and bitangent at a vertex of triangle for per-triangle computed tangents.
Static Public Member Functions
static bool ComputeDefaultOverlayTangents (FDynamicMesh3 &Mesh)
Convenience function to compute tangents from the mesh attribute set's primary UVs and normals.
Protected Member Functions
void ComputeMikkTStyleTangents (const FDynamicMeshNormalOverlay *NormalOverlay, const FDynamicMeshUVOverlay *UVOverlay, const FComputeTangentsOptions &Options)
void ComputeSeparatePerTriangleTangents (const FDynamicMeshNormalOverlay *NormalOverlay, const FDynamicMeshUVOverlay *UVOverlay, const FComputeTangentsOptions &Options)
GEOMETRYCORE_API void SetTangentCount (int Count, bool bClearToZero)
Set the size of the Tangents array to Count, and optionally clear all values to (0,0,0)
Protected Attributes
TArray< int32 > AllDegenerateTris
Indices of degenerate triangles.
TArray< TVector< RealType > > Bitangents
Set of computed bitangents.
const FDynamicMesh3 * Mesh
Target Mesh.
TArray< TVector< RealType > > Tangents
Set of computed tangents.
Detailed Description
template<typename RealType>
class UE::Geometry::TMeshTangents< RealType >
TMeshTangents is a utility class that can calculate and store various types of tangent vectors for a FDynamicMesh.
Definition at line 75 of file MeshTangents.h.
Constructor & Destructor Documentation
TMeshTangents() [1/2]
template<typename RealType> UE::Geometry::TMeshTangents< RealType >::TMeshTangents () inline
Definition at line 88 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
TMeshTangents() [2/2]
template<typename RealType> UE::Geometry::TMeshTangents< RealType >::TMeshTangents (const FDynamicMesh3 * Mesh) inline
Definition at line 93 of file MeshTangents.h.
Member Function Documentation
ComputeDefaultOverlayTangents()
template<typename RealType> bool UE::Geometry::TMeshTangents< RealType >::ComputeDefaultOverlayTangents (FDynamicMesh3 & Mesh) inline static
Convenience function to compute tangents from the mesh attribute set's primary UVs and normals.
Returns
true if tangents were computed, false otherwise
Definition at line 259 of file MeshTangents.h.
ComputeMikkTStyleTangents()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::ComputeMikkTStyleTangents (const FDynamicMeshNormalOverlay * NormalOverlay, const FDynamicMeshUVOverlay * UVOverlay, const FComputeTangentsOptions & Options) protected
ComputeSeparatePerTriangleTangents()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::ComputeSeparatePerTriangleTangents (const FDynamicMeshNormalOverlay * NormalOverlay, const FDynamicMeshUVOverlay * UVOverlay, const FComputeTangentsOptions & Options) protected
ComputeTriangleTangents()
template<typename RealType> GEOMETRYCORE_API void UE::Geometry::TMeshTangents< RealType >::ComputeTriangleTangents (const FDynamicMeshUVOverlay * UVOverlay, bool bOrthogonalize = true)
Compute per-triangle tangents for the given UV Overlay.
Parameters
bOrthogonalize if true, we orthogonalize the tangents by computing the Bitangent sign and regenerating it. Otherwise the tangents are left non-orthogonal.
ComputeTriVertexTangents()
template<typename RealType> GEOMETRYCORE_API void UE::Geometry::TMeshTangents< RealType >::ComputeTriVertexTangents (const FDynamicMeshNormalOverlay * NormalOverlay, const FDynamicMeshUVOverlay * UVOverlay, const FComputeTangentsOptions & Options)
Calculate per-triangle tangent spaces based on the given per-triangle normal and UV overlays.
In this mode there is no averaging of tangents across triangles. So if we have N triangles in the mesh, then 3*N tangents are generated. These tangents are computed in parallel.
CopyToOverlays()
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TMeshTangents< RealType >::CopyToOverlays (FDynamicMesh3 & MeshToSet) const
Set Tangents on mesh overlays.
Parameters
MeshToSet Mesh to copy overlays to; does not need to be the same as the Mesh member of this class
CopyTriVertexTangents() [1/2]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TMeshTangents< RealType >::CopyTriVertexTangents (const FDynamicMesh3 & SourceMesh)
Initialize Tangents from the FDynamicMeshAttributeSet of SourceMesh.
Returns
false if tangent attributes do not exist
CopyTriVertexTangents() [2/2]
template<typename RealType> template<typename OtherRealType> void UE::Geometry::TMeshTangents< RealType >::CopyTriVertexTangents (const TMeshTangents< OtherRealType > & OtherTangents)
Initialize Tangents from other Tangents set.
Definition at line 300 of file MeshTangents.h.
References TMeshTangents(), AllDegenerateTris, Bitangents, check, GetBitangents(), GetDegenerateTris(), GetTangents(), InitializeTriVertexTangents(), Mesh, Num, TArray< InElementType, InAllocatorType >::Num(), and Tangents.
GetBitangents()
template<typename RealType> const TArray< TVector< RealType > > & UE::Geometry::TMeshTangents< RealType >::GetBitangents () const inline
Definition at line 105 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
GetDegenerateTris()
template<typename RealType> const TArray< int32 > & UE::Geometry::TMeshTangents< RealType >::GetDegenerateTris () const inline
Definition at line 107 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
GetInterpolatedTriangleTangent()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::GetInterpolatedTriangleTangent (int32 TriangleID, const UE::Math::TVector< RealType > & BaryCoords, UE::Math::TVector< RealType > & TangentOut, UE::Math::TVector< RealType > & BitangentOut) const inline
Returns
Interpolated tangent and bitangent at barycentric coordinates inside a triangle, for per-triangle computed tangents
Parameters
TriangleID triangle index in mesh
BaryCoords barycentric coordinates in triangle
TangentOut interpolated tangent
BitangentOut interpolated bitangent
Definition at line 182 of file MeshTangents.h.
GetPerTriangleTangent() [1/2]
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::GetPerTriangleTangent (int32 TriangleID, int32 TriVertIdx, UE::Math::TVector< RealType > & TangentOut, UE::Math::TVector< RealType > & BitangentOut) const inline
Return tangent and bitangent at a vertex of triangle for per-triangle computed tangents.
Parameters
TriangleID triangle index in mesh
TriVertIdx vertex index in range 0,1,2
Definition at line 149 of file MeshTangents.h.
GetPerTriangleTangent() [2/2]
template<typename RealType> template<typename VectorType, typename OtherRealType> void UE::Geometry::TMeshTangents< RealType >::GetPerTriangleTangent (int32 TriangleID, int32 TriVertIdx, VectorType & TangentOut, VectorType & BitangentOut) const inline
Return tangent and bitangent at a vertex of triangle for per-triangle computed tangents.
Parameters
TriangleID triangle index in mesh
TriVertIdx vertex index in range 0,1,2
Definition at line 163 of file MeshTangents.h.
GetTangents()
template<typename RealType> const TArray< TVector< RealType > > & UE::Geometry::TMeshTangents< RealType >::GetTangents () const inline
Definition at line 103 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
GetTriangleVertexTangentVectors()
template<typename RealType> template<typename OtherVectorType> void UE::Geometry::TMeshTangents< RealType >::GetTriangleVertexTangentVectors (int32 TriangleID, int32 TriVertexIndex, OtherVectorType & TangentOut, OtherVectorType & BitangentOut) const inline
Get tangent and bitangent at a vertex of a triangle for per-triangle computed tangents.
Parameters
TriangleID triangle index in mesh
TriVertIdx vertex index in range 0,1,2
Definition at line 221 of file MeshTangents.h.
InitializeTriangleTangents()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::InitializeTriangleTangents (bool bClearToZero) inline
Initialize buffer sizes to one tangent/bitangent per mesh triangle.
Definition at line 235 of file MeshTangents.h.
InitializeTriVertexTangents()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::InitializeTriVertexTangents (bool bClearToZero) inline
Set internal buffer sizes suitable for calculating per-triangle tangents.
This is intended to be used if you wish to calculate your own tangents and use SetPerTriangleTangent()
Definition at line 119 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
SetMesh()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::SetMesh (const FDynamicMesh3 * MeshIn) inline
Definition at line 98 of file MeshTangents.h.
Referenced by UE::Geometry::TMeshTangents< float >::TMeshTangents().
SetPerTriangleTangent()
template<typename RealType> void UE::Geometry::TMeshTangents< RealType >::SetPerTriangleTangent (int TriangleID, int TriVertIdx, const TVector< RealType > & Tangent, const TVector< RealType > & Bitangent) inline
Set tangent and bitangent at a vertex of triangle for per-triangle computed tangents.
Parameters
TriangleID triangle index in mesh
TriVertIdx vertex index in range 0,1,2
Definition at line 208 of file MeshTangents.h.
SetTangentCount()
template<typename RealType> GEOMETRYCORE_API void UE::Geometry::TMeshTangents< RealType >::SetTangentCount (int Count, bool bClearToZero) protected
Set the size of the Tangents array to Count, and optionally clear all values to (0,0,0)
Referenced by UE::Geometry::TMeshTangents< float >::InitializeTriangleTangents(), and UE::Geometry::TMeshTangents< float >::InitializeTriVertexTangents().
Field Documentation
AllDegenerateTris
template<typename RealType> TArray<int32> UE::Geometry::TMeshTangents< RealType >::AllDegenerateTris protected
Indices of degenerate triangles.
This may be useful to know externally, as those tangets are often meaningless
Definition at line 85 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
Bitangents
template<typename RealType> TArray<TVector<RealType> > UE::Geometry::TMeshTangents< RealType >::Bitangents protected
Set of computed bitangents.
Definition at line 83 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
Mesh
template<typename RealType> const FDynamicMesh3* UE::Geometry::TMeshTangents< RealType >::Mesh protected
Target Mesh.
Definition at line 79 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
Tangents
template<typename RealType> TArray<TVector<RealType> > UE::Geometry::TMeshTangents< RealType >::Tangents protected
Set of computed tangents.
Definition at line 81 of file MeshTangents.h.
Referenced by CopyTriVertexTangents().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/MeshTangents.h