Unreal Engine 5.6 C++ API: FRigVMCallExternExprAST Class Reference
FRigVMCallExternExprAST Class Reference
#include "RigVMAST.h"
Public Member Functions
FRigVMCallExternExprAST (const FRigVMCallExternExprAST &)=delete
virtual ~FRigVMCallExternExprAST ()
virtual bool IsA (EType InType) const override
provides type checking for inherited types
Public Member Functions inherited from FRigVMNodeExprAST
FRigVMNodeExprAST (const FRigVMNodeExprAST &)=delete
virtual ~FRigVMNodeExprAST ()
const FRigVMExprAST * FindExprWithPinName (const FName &InPinName) const
const FRigVMVarExprAST * FindVarWithPinName (const FName &InPinName) const
URigVMNode * GetNode () const
virtual const FRigVMASTProxy & GetProxy () const override
returns the model proxy this expression relates to
virtual bool IsConstant () const override
returns true if this expressions is constant (non varying)
virtual bool IsNode () const
returns true if the expression is a node expression
Public Member Functions inherited from FRigVMBlockExprAST
FRigVMBlockExprAST (const FRigVMBlockExprAST &)=delete
virtual ~FRigVMBlockExprAST ()
bool Contains (const FRigVMExprAST *InExpression, TMap< const FRigVMExprAST *, bool > *ContainedExpressionsCache=nullptr) const
bool ContainsEntry () const
bool IsObsolete () const
bool ShouldExecute () const
Public Member Functions inherited from FRigVMExprAST
FRigVMExprAST (const FRigVMExprAST &)=delete
virtual ~FRigVMExprAST ()
TArray< FRigVMExprAST * >::RangedForConstIteratorType begin () const
template<class ObjectType>
const ObjectType * ChildAt (int32 InIndex) const
templated getter to retrieve a child with a given index type checking will occur within the To method and raise
const FRigVMExprAST * ChildAt (int32 InIndex) const
getter to retrieve a child with a given index
TArray< FRigVMExprAST * >::RangedForConstIteratorType end () const
const FRigVMBlockExprAST * GetBlock () const
returns the block of this expression
TOptional< uint32 > GetBlockCombinationHash () const
returns the unique block combination hash for this expression (or INDEX_NONE)
const FString & GetBlockCombinationName () const
returns the unique block combination name for this expression (or an empty string)
FRigVMBlockArray GetBlocks (bool bSortByDepth) const
virtual const FRigVMExprAST * GetFirstChildOfType (EType InExprType) const
returns the first parent in the tree of a given type
virtual const FRigVMExprAST * GetFirstParentOfType (EType InExprType) const
returns the first parent in the tree of a given type
int32 GetIndex () const
returns the index of this expression within the parser's storage
int32 GetMaximumDepth () const
returns the maximum depth of the expression in tree (number of recursive parents)
int32 GetMinChildIndexWithinParent (const FRigVMExprAST *InParentExpr) const
returns the lowest child index found for this expression within a parent (or INDEX_NONE)
FName GetName () const
returns the name of the expression (can be NAME_None)
const FRigVMExprAST * GetParent () const
returns the parent of this expression
const FRigVMParserAST * GetParser () const
returns the parser this expression is owned by
const FRigVMBlockExprAST * GetRootBlock () const
returns the root / top level block of this expression
EType GetType () const
returns the exact type of the expression
FName GetTypeName () const
returns the name of the expression's type
bool IsParentedTo (const FRigVMExprAST *InParentExpr) const
returns true if a given expression is parented to another expression
bool IsParentOf (const FRigVMExprAST *InChildExpr) const
returns true if a given expression is a parent of another expression
bool IsValid () const
returns true if the expressoin is valid
virtual bool IsVar () const
returns true if the expression is a var expression
bool IsVarying () const
returns true if this expressions is varying (non constant)
int32 NumChildren () const
returns the number of children of this expression
int32 NumParents () const
returns the number of parents of this expression
const FRigVMExprAST * operator[] (int32 InIndex) const
accessor operator for a given child
template<class ObjectType>
const ObjectType * ParentAt (int32 InIndex) const
templated getter to retrieve a parent with a given index type checking will occur within the To method and raise
const FRigVMExprAST * ParentAt (int32 InIndex) const
getter to retrieve a parent with a given index
template<class ObjectType>
ObjectType * To ()
templated cast for casting between different expression types.
template<class ObjectType>
const ObjectType * To () const
const templated cast for casting between different expression types.
template<>
const FRigVMBlockExprAST * To () const
template<>
const FRigVMNodeExprAST * To () const
template<>
const FRigVMEntryExprAST * To () const
template<>
const FRigVMInvokeEntryExprAST * To () const
template<>
const FRigVMCallExternExprAST * To () const
template<>
const FRigVMInlineFunctionExprAST * To () const
template<>
const FRigVMNoOpExprAST * To () const
template<>
const FRigVMVarExprAST * To () const
template<>
const FRigVMLiteralExprAST * To () const
template<>
const FRigVMExternalVarExprAST * To () const
template<>
const FRigVMAssignExprAST * To () const
template<>
const FRigVMCopyExprAST * To () const
template<>
const FRigVMCachedValueExprAST * To () const
template<>
const FRigVMExitExprAST * To () const
Protected Member Functions
FRigVMCallExternExprAST (const FRigVMASTProxy &InNodeProxy)
Protected Member Functions inherited from FRigVMNodeExprAST
FRigVMNodeExprAST (EType InType, const FRigVMASTProxy &InNodeProxy)
Protected Member Functions inherited from FRigVMBlockExprAST
FRigVMBlockExprAST (EType InType=EType::Block, const FRigVMASTProxy &InProxy=FRigVMASTProxy())
Protected Member Functions inherited from FRigVMExprAST
FRigVMExprAST (EType InType=EType::Invalid, const FRigVMASTProxy &InProxy=FRigVMASTProxy())
void AddParent (FRigVMExprAST *InParent)
virtual FString DumpText (const FString &InPrefix=FString()) const
void GetBlocksImpl (FRigVMBlockArray &InOutBlocks) const
void InvalidateCaches ()
void InvalidateCachesImpl (TArray< bool > &OutProcessed)
void RemoveChild (FRigVMExprAST *InChild)
void RemoveParent (FRigVMExprAST *InParent)
void ReplaceBy (FRigVMExprAST *InReplacement)
void ReplaceChild (FRigVMExprAST *InCurrentChild, FRigVMExprAST *InNewChild)
void ReplaceParent (FRigVMExprAST *InCurrentParent, FRigVMExprAST *InNewParent)
Friends
class FRigVMParserAST
Additional Inherited Members
Public Types inherited from FRigVMExprAST
enum EType {
Block , Entry , InvokeEntry , CallExtern ,
InlineFunction , NoOp , Var , Literal ,
ExternalVar , Assign , Copy , CachedValue ,
Exit , Invalid
}
typedef TArray< const FRigVMBlockExprAST *, TInlineAllocator< 5 > > FRigVMBlockArray
returns all of the block this expression is in
Protected Attributes inherited from FRigVMExprAST
TOptional< TOptional< uint32 > > BlockCombinationHash
TOptional< int32 > BlocksCacheVersion
FRigVMBlockArray CachedBlocks
TMap< int32, const FRigVMExprAST * > CachedFirstChildOfType
TMap< int32, const FRigVMExprAST * > CachedFirstParentOfType
TArray< FRigVMExprAST * > Children
TOptional< int32 > FirstChildOfTypeCacheVersion
TOptional< int32 > FirstParentOfTypeCacheVersion
int32 Index
TOptional< int32 > MaximumDepth
FName Name
TArray< FRigVMExprAST * > Parents
const FRigVMParserAST * ParserPtr
TMap< FName, int32 > PinNameToChildIndex
EType Type
Detailed Description
Definition at line 704 of file RigVMAST.h.
Constructor & Destructor Documentation
~FRigVMCallExternExprAST()
virtual FRigVMCallExternExprAST::~FRigVMCallExternExprAST () inline virtual
Definition at line 709 of file RigVMAST.h.
FRigVMCallExternExprAST() [1/2]
FRigVMCallExternExprAST::FRigVMCallExternExprAST (const FRigVMCallExternExprAST &) delete
References FRigVMCallExternExprAST().
Referenced by FRigVMCallExternExprAST().
FRigVMCallExternExprAST() [2/2]
FRigVMCallExternExprAST::FRigVMCallExternExprAST (const FRigVMASTProxy & InNodeProxy) inline protected
Definition at line 723 of file RigVMAST.h.
References FRigVMNodeExprAST::FRigVMNodeExprAST(), and FRigVMExprAST::CallExtern.
Member Function Documentation
IsA()
virtual bool FRigVMCallExternExprAST::IsA (EType InType) const inline override virtual
provides type checking for inherited types
Parameters
InType the type to check against
Returns
true if this expression is of a given type
Reimplemented from FRigVMNodeExprAST.
Definition at line 715 of file RigVMAST.h.
References FRigVMExprAST::CallExtern.
Friends And Related Symbol Documentation
FRigVMParserAST
friend class FRigVMParserAST friend
Definition at line 729 of file RigVMAST.h.
References FRigVMParserAST.
Referenced by FRigVMParserAST.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMCompiler/RigVMAST.h