Unreal Engine 5.6 C++ API: FShaderPipelineType Class Reference
FShaderPipelineType Class Reference
#include "Shader.h"
Public Member Functions
RENDERCORE_API FShaderPipelineType (const TCHAR *InName, const FShaderType *InVertexOrMeshShader, const FShaderType *InGeometryOrAmplificationShader, const FShaderType *InPixelShader, bool bInIsMeshPipeline, bool bInShouldOptimizeUnusedOutputs)
RENDERCORE_API ~FShaderPipelineType ()
FName GetFName () const
const FHashedName & GetHashedName () const
const FHashedName & GetHashedPrimaryShaderFilename () const
TCHAR const * GetName () const
const FShaderType * GetShader (EShaderFrequency Frequency) const
RENDERCORE_API const FSHAHash & GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this shader pipeline type stages' source code and includes.
const TArray< const FShaderType * > & GetStages () const
bool HasGeometry () const
bool HasMeshShader () const
bool HasPixelShader () const
bool IsGlobalTypePipeline () const
bool IsMaterialTypePipeline () const
bool IsMeshMaterialTypePipeline () const
RENDERCORE_API bool ShouldCompilePermutation (const FShaderPermutationParameters &Parameters) const
RENDERCORE_API bool ShouldOptimizeUnusedOutputs (EShaderPlatform Platform) const
RENDERCORE_API EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters) const
Static Public Member Functions
static RENDERCORE_API TMap< FHashedName, FShaderPipelineType * > & GetNameToTypeMap ()
static RENDERCORE_API const FShaderPipelineType * GetShaderPipelineTypeByName (const FHashedName &Name)
static RENDERCORE_API TArray< const FShaderPipelineType * > GetShaderPipelineTypesByFilename (const TCHAR *Filename, bool bSearchAsRegexFilter=false)
static RENDERCORE_API TArray< const FShaderPipelineType * > GetShaderPipelineTypesByFilenameFilter (const TFunction< bool(const TCHAR *)> &InFilenameFilter)
static RENDERCORE_API const TArray< FShaderPipelineType * > & GetSortedTypes (FShaderType::EShaderTypeForDynamicCast Type)
static RENDERCORE_API TLinkedList< FShaderPipelineType * > *& GetTypeList ()
static RENDERCORE_API void Initialize ()
Initialize static members, this must be called before any shader types are created.
Protected Attributes
const FShaderType * AllStages [SF_NumFrequencies]
bool bShouldOptimizeUnusedOutputs
TLinkedList< FShaderPipelineType * > GlobalListLink
FHashedName HashedName
FHashedName HashedPrimaryShaderFilename
uint32 HashIndex
const TCHAR *const Name
TArray< const FShaderType * > Stages
FName TypeName
Static Protected Attributes
static RENDERCORE_API bool bInitialized
Friends
uint32 GetTypeHash (const FShaderPipelineType *Ref)
uint32 GetTypeHash (FShaderPipelineType *Ref)
Hashes a pointer to a shader type.
RENDERCORE_API friend FArchive & operator<< (FArchive &Ar, const FShaderPipelineType *&Ref)
Serializes a shader type reference by name.
Detailed Description
Definition at line 1960 of file Shader.h.
Constructor & Destructor Documentation
FShaderPipelineType()
RENDERCORE_API FShaderPipelineType::FShaderPipelineType (const TCHAR * InName, const FShaderType * InVertexOrMeshShader, const FShaderType * InGeometryOrAmplificationShader, const FShaderType * InPixelShader, bool bInIsMeshPipeline, bool bInShouldOptimizeUnusedOutputs)
References InName.
Referenced by GetShaderPipelineTypeByName(), GetTypeHash, GetTypeHash, and operator<<.
~FShaderPipelineType()
RENDERCORE_API FShaderPipelineType::~FShaderPipelineType ()
Member Function Documentation
GetFName()
FName FShaderPipelineType::GetFName () const inline
Definition at line 1984 of file Shader.h.
References FORCEINLINE, and TypeName.
GetHashedName()
const FHashedName & FShaderPipelineType::GetHashedName () const inline
Definition at line 1986 of file Shader.h.
References FORCEINLINE, and HashedName.
Referenced by FShaderMapContent::GetShaderPipeline().
GetHashedPrimaryShaderFilename()
const FHashedName & FShaderPipelineType::GetHashedPrimaryShaderFilename () const inline
Definition at line 1987 of file Shader.h.
References FORCEINLINE, and HashedPrimaryShaderFilename.
GetName()
TCHAR const * FShaderPipelineType::GetName () const inline
Definition at line 1985 of file Shader.h.
References FORCEINLINE, and Name.
GetNameToTypeMap()
RENDERCORE_API TMap< FHashedName, FShaderPipelineType * > & FShaderPipelineType::GetNameToTypeMap () static
Returns
The global shader pipeline name to type map
GetShader()
const FShaderType * FShaderPipelineType::GetShader (EShaderFrequency Frequency) const inline
Definition at line 1978 of file Shader.h.
References AllStages, check, FORCEINLINE, and Frequency.
GetShaderPipelineTypeByName()
RENDERCORE_API const FShaderPipelineType * FShaderPipelineType::GetShaderPipelineTypeByName (const FHashedName & Name) static
References FShaderPipelineType(), and Name.
GetShaderPipelineTypesByFilename()
RENDERCORE_API TArray< const FShaderPipelineType * > FShaderPipelineType::GetShaderPipelineTypesByFilename (const TCHAR * Filename, bool bSearchAsRegexFilter = false) static
References Filename.
GetShaderPipelineTypesByFilenameFilter()
RENDERCORE_API TArray< const FShaderPipelineType * > FShaderPipelineType::GetShaderPipelineTypesByFilenameFilter (const TFunction< bool(const TCHAR *)> & InFilenameFilter) static
GetSortedTypes()
RENDERCORE_API const TArray< FShaderPipelineType * > & FShaderPipelineType::GetSortedTypes (FShaderType::EShaderTypeForDynamicCast Type) static
GetSourceHash()
RENDERCORE_API const FSHAHash & FShaderPipelineType::GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this shader pipeline type stages' source code and includes.
References ShaderPlatform.
Referenced by FShaderPipelineTypeDependency::FShaderPipelineTypeDependency().
GetStages()
const TArray< const FShaderType * > & FShaderPipelineType::GetStages () const inline
Definition at line 1990 of file Shader.h.
References FORCEINLINE, and Stages.
GetTypeList()
RENDERCORE_API TLinkedList< FShaderPipelineType * > *& FShaderPipelineType::GetTypeList () static
HasGeometry()
bool FShaderPipelineType::HasGeometry () const inline
Definition at line 1975 of file Shader.h.
References AllStages, and FORCEINLINE.
HasMeshShader()
bool FShaderPipelineType::HasMeshShader () const inline
Definition at line 1974 of file Shader.h.
References AllStages, and FORCEINLINE.
HasPixelShader()
bool FShaderPipelineType::HasPixelShader () const inline
Definition at line 1976 of file Shader.h.
References AllStages, and FORCEINLINE.
Initialize()
RENDERCORE_API void FShaderPipelineType::Initialize () static
Initialize static members, this must be called before any shader types are created.
IsGlobalTypePipeline()
bool FShaderPipelineType::IsGlobalTypePipeline () const inline
Definition at line 2014 of file Shader.h.
References Stages.
IsMaterialTypePipeline()
bool FShaderPipelineType::IsMaterialTypePipeline () const inline
Definition at line 2015 of file Shader.h.
References Stages.
IsMeshMaterialTypePipeline()
bool FShaderPipelineType::IsMeshMaterialTypePipeline () const inline
Definition at line 2016 of file Shader.h.
References Stages.
ShouldCompilePermutation()
RENDERCORE_API bool FShaderPipelineType::ShouldCompilePermutation (const FShaderPermutationParameters & Parameters) const
ShouldOptimizeUnusedOutputs()
RENDERCORE_API bool FShaderPipelineType::ShouldOptimizeUnusedOutputs (EShaderPlatform Platform) const
References Platform.
ShouldPrecachePermutation()
RENDERCORE_API EShaderPermutationPrecacheRequest FShaderPipelineType::ShouldPrecachePermutation (const FShaderPermutationParameters & Parameters) const
Friends And Related Symbol Documentation
GetTypeHash [1/2]
uint32 GetTypeHash (const FShaderPipelineType * Ref) friend
Definition at line 2011 of file Shader.h.
References FShaderPipelineType().
GetTypeHash [2/2]
uint32 GetTypeHash (FShaderPipelineType * Ref) friend
Hashes a pointer to a shader type.
Definition at line 2010 of file Shader.h.
References FShaderPipelineType().
operator<<
RENDERCORE_API friend FArchive & operator<< (FArchive & Ar, const FShaderPipelineType *& Ref) friend
Serializes a shader type reference by name.
References FShaderPipelineType(), and Ar.
Field Documentation
AllStages
const FShaderType* FShaderPipelineType::AllStages[SF_NumFrequencies] protected
Definition at line 2036 of file Shader.h.
Referenced by GetShader(), HasGeometry(), HasMeshShader(), and HasPixelShader().
bInitialized
RENDERCORE_API bool FShaderPipelineType::bInitialized static protected
Definition at line 2043 of file Shader.h.
bShouldOptimizeUnusedOutputs
bool FShaderPipelineType::bShouldOptimizeUnusedOutputs protected
Definition at line 2041 of file Shader.h.
GlobalListLink
TLinkedList<FShaderPipelineType*> FShaderPipelineType::GlobalListLink protected
Definition at line 2038 of file Shader.h.
HashedName
FHashedName FShaderPipelineType::HashedName protected
Definition at line 2030 of file Shader.h.
Referenced by GetHashedName().
HashedPrimaryShaderFilename
FHashedName FShaderPipelineType::HashedPrimaryShaderFilename protected
Definition at line 2031 of file Shader.h.
Referenced by GetHashedPrimaryShaderFilename().
HashIndex
uint32 FShaderPipelineType::HashIndex protected
Definition at line 2040 of file Shader.h.
Name
const TCHAR* const FShaderPipelineType::Name protected
Definition at line 2028 of file Shader.h.
Referenced by GetName(), and GetShaderPipelineTypeByName().
Stages
TArray<const FShaderType*> FShaderPipelineType::Stages protected
Definition at line 2034 of file Shader.h.
Referenced by GetStages(), IsGlobalTypePipeline(), IsMaterialTypePipeline(), and IsMeshMaterialTypePipeline().
TypeName
FName FShaderPipelineType::TypeName protected
Definition at line 2029 of file Shader.h.
Referenced by GetFName().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h