Unreal Engine 5.6 C++ API: FTrackedMetaData Class Reference
FTrackedMetaData Class Reference
MetaData used to add and remove widgets to the Slate Widget Tracker for the specified tags.
#include "TrackedMetaData.h"
Public Member Functions
FTrackedMetaData (const FTrackedMetaData &)=delete
FTrackedMetaData (const SWidget *InTrackedWidget, FName InTags)
~FTrackedMetaData ()
FTrackedMetaData & operator= (const FTrackedMetaData &)=delete
SLATE_METADATA_TYPE (FTrackedMetaData, ISlateMetaData) 1 FTrackedMetaData(const SWidget *InTrackedWidget
Public Member Functions inherited from ISlateMetaData
virtual ~ISlateMetaData ()
Virtual destructor.
template<class TType>
bool IsOfType () const
Check if this metadata operation can cast safely to the specified template type.
Data Fields
TArray< FName > && InTags
Private Attributes
TArray< FName > Tags
const SWidget * TrackedWidget = nullptr
Additional Inherited Members
Protected Member Functions inherited from ISlateMetaData
virtual bool IsOfTypeImpl (const FName &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
Detailed Description
MetaData used to add and remove widgets to the Slate Widget Tracker for the specified tags.
Definition at line 14 of file TrackedMetaData.h.
Constructor & Destructor Documentation
FTrackedMetaData() [1/2]
FTrackedMetaData::FTrackedMetaData (const SWidget * InTrackedWidget, FName InTags)
References FTrackedMetaData(), and InTags.
Referenced by FTrackedMetaData(), FTrackedMetaData(), ~FTrackedMetaData(), operator=(), and SLATE_METADATA_TYPE().
~FTrackedMetaData()
FTrackedMetaData::~FTrackedMetaData ()
References FTrackedMetaData().
FTrackedMetaData() [2/2]
FTrackedMetaData::FTrackedMetaData (const FTrackedMetaData &) delete
References FTrackedMetaData().
Member Function Documentation
operator=()
FTrackedMetaData & FTrackedMetaData::operator= (const FTrackedMetaData &) delete
References FTrackedMetaData().
SLATE_METADATA_TYPE()
FTrackedMetaData::SLATE_METADATA_TYPE (FTrackedMetaData , ISlateMetaData) const
References FTrackedMetaData().
Field Documentation
InTags
TArray<FName>&& FTrackedMetaData::InTags
Definition at line 20 of file TrackedMetaData.h.
Referenced by FTrackedMetaData().
Tags
TArray<FName> FTrackedMetaData::Tags private
Definition at line 30 of file TrackedMetaData.h.
TrackedWidget
const SWidget* FTrackedMetaData::TrackedWidget = nullptr private
Definition at line 29 of file TrackedMetaData.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Types/TrackedMetaData.h