Unreal Engine 5.6 C++ API: UE::FMacSystemWideMutex Class Reference
UE::FMacSystemWideMutex Class Reference final
A system-wide mutex for Mac.
#include "MacPlatformMutex.h"
Public Member Functions
FMacSystemWideMutex (const FMacSystemWideMutex &)=delete
FMacSystemWideMutex (const FString &InName, FTimespan InTimeout=FTimespan::Zero())
Construct a named, system-wide mutex and attempt to get access/ownership of it.
~FMacSystemWideMutex ()
Destructor releases system-wide mutex if it is currently owned.
bool IsValid () const
Does the calling thread have ownership of the system-wide mutex?
FMacSystemWideMutex & operator= (const FMacSystemWideMutex &)=delete
void Release ()
Releases system-wide mutex if it is currently owned.
Private Attributes
int32 FileHandle
Detailed Description
A system-wide mutex for Mac.
Uses exclusive file locking.
Definition at line 14 of file MacPlatformMutex.h.
Constructor & Destructor Documentation
FMacSystemWideMutex() [1/2]
UE::FMacSystemWideMutex::FMacSystemWideMutex (const FMacSystemWideMutex &) delete
References FMacSystemWideMutex().
Referenced by FMacSystemWideMutex(), and operator=().
FMacSystemWideMutex() [2/2]
UE::FMacSystemWideMutex::FMacSystemWideMutex (const FString & InName, FTimespan InTimeout = FTimespan::Zero()) explicit
Construct a named, system-wide mutex and attempt to get access/ownership of it.
References InName, and FTimespan::Zero().
~FMacSystemWideMutex()
UE::FMacSystemWideMutex::~FMacSystemWideMutex ()
Destructor releases system-wide mutex if it is currently owned.
Member Function Documentation
IsValid()
bool UE::FMacSystemWideMutex::IsValid () const
Does the calling thread have ownership of the system-wide mutex?
Returns
True if obtained. WARNING: Returns true for an owned but previously abandoned locks so shared resources can be in undetermined states. You must handle shared data robustly.
operator=()
FMacSystemWideMutex & UE::FMacSystemWideMutex::operator= (const FMacSystemWideMutex &) delete
References FMacSystemWideMutex().
Release()
void UE::FMacSystemWideMutex::Release ()
Releases system-wide mutex if it is currently owned.
Field Documentation
FileHandle
int32 UE::FMacSystemWideMutex::FileHandle private
Definition at line 37 of file MacPlatformMutex.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Mac/MacPlatformMutex.h