Unreal Engine 5.6 C++ API: IGeometrySelector Class Reference
IGeometrySelector Class Reference abstract
IGeometrySelector is a base API definition for, roughly, "an object that knows how to select elements and/or work with element selections on some other object", where "element" is some "part" of the object, like a mesh edge/vertex/triangle, or intermediate structure (eg a polygroup).
#include "GeometrySelector.h"
Data Structures
struct FWorldRayQueryInfo
struct FWorldShapeQueryInfo
Public Types
enum class EInitializeSelectionMode { All , Connected , AdjacentToBorder }
using FGeometrySelection = UE::Geometry::FGeometrySelection
using FGeometrySelectionBounds = UE::Geometry::FGeometrySelectionBounds
using FGeometrySelectionEditor = UE::Geometry::FGeometrySelectionEditor
using FGeometrySelectionElements = UE::Geometry::FGeometrySelectionElements
using FGeometrySelectionUpdateConfig = UE::Geometry::FGeometrySelectionUpdateConfig
using FGeometrySelectionUpdateResult = UE::Geometry::FGeometrySelectionUpdateResult
Public Member Functions
virtual ~IGeometrySelector ()
virtual void AccumulateElementsFromPredicate (FGeometrySelectionElements &ElementsInOut, bool bTransformToWorld, bool bIsForPreview, bool bUseGroupTopology, TFunctionRef< bool(UE::Geometry::EGeometryElementType, UE::Geometry::FGeoSelectionID)> Predicate)=0
Accumulate all geometric elements (currently 3D triangles, line segments, and points) in the provided ElementsInOut by initializing vertex, edge, and face selections using the provided predicate and then accumulating elements for those selections.
virtual void AccumulateSelectionBounds (const FGeometrySelection &Selection, FGeometrySelectionBounds &BoundsInOut, bool bTransformToWorld)=0
Accumulate the bounds of the provided Selection in the provided BoundsInOut.
virtual void AccumulateSelectionElements (const FGeometrySelection &Selection, FGeometrySelectionElements &ElementsInOut, bool bTransformToWorld, UE::Geometry::EEnumerateSelectionMapping Flags=UE::Geometry::EEnumerateSelectionMapping::Default)=0
Accumulate geometric elements (currently 3D triangles, line segments, and points) for the provided Selection in the provided ElementsInOut.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnGeometryModified, IGeometrySelector *Selector)
virtual FGeometryIdentifier GetIdentifier () const =0
virtual FTransform GetLocalToWorldTransform () const =0
FOnGeometryModified & GetOnGeometryModifed ()
The OnGeometryModified delegate will fire if the geometry of the Selector's Target Object is modified.
virtual void GetSelectionFrame (const FGeometrySelection &Selection, UE::Geometry::FFrame3d &SelectionFrameOut, bool bTransformToWorld)=0
Compute a 3D frame for the provided Selection.
virtual void GetSelectionPreviewForRaycast (const FWorldRayQueryInfo &RayInfo, FGeometrySelectionEditor &PreviewEditor)=0
Query the Selector for a potential selection based on world-space Ray.
virtual void GetTargetFrame (const FGeometrySelection &Selection, UE::Geometry::FFrame3d &SelectionFrameOut)=0
Compute a 3D frame for the Selector's target object.
virtual void InitializeSelectionFromPredicate (FGeometrySelection &SelectionInOut, TFunctionRef< bool(UE::Geometry::FGeoSelectionID)> SelectionIDPredicate, EInitializeSelectionMode InitializeMode=EInitializeSelectionMode::All, const FGeometrySelection *ReferenceSelection=nullptr)=0
Populate a Selection using the provided ReferenceMode, with a Predicate and optional ReferenceSelection.
virtual IGeometrySelectionTransformer * InitializeTransformation (const FGeometrySelection &Selection)=0
Create and initialize a IGeometrySelectionTransformer for the provided Selection.
virtual bool IsLockable () const
virtual bool IsLocked () const
virtual bool RayHitTest (const FWorldRayQueryInfo &RayInfo, UE::Geometry::FGeometrySelectionHitQueryConfig QueryConfig, FInputRayHit &HitResultOut)=0
Check for intersection between a world-space Ray with the Selector's target object and return a FInputRayHit result.
virtual bool Restore ()
Restore a Selector that has had Sleep() called on it.
virtual void SetLockedState (bool bLocked)
virtual void Shutdown ()=0
Disconnect the Selector from its target object and prepare for deletion.
virtual void ShutdownTransformation (IGeometrySelectionTransformer *Transformer)=0
Shutdown an active IGeometrySelectionTransformer.
virtual bool Sleep ()
Temporarily disable the Selector, with the intention of re-enabling it (via Restore()) in the future.
virtual bool SupportsSleep () const
The SelectionManager will call SupportsSleep() to determine if an IGeometrySelector needs to be destroyed when the target object is deselected, or if it can be re-used (generally more efficient)
UE_DEPRECATED (5.5, "AccumulateSelectionElements which takes a bIsForPreview boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") virtual void AccumulateSelectionElements(const FGeometrySelection &Selection
Prefer AccumulateSelectionElements with Flags parameter.
virtual void UpdateSelectionFromSelection (const FGeometrySelection &FromSelection, bool bAllowConversion, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, UE::Geometry::FGeometrySelectionDelta *SelectionDelta=nullptr)=0
Combine FromSelection with the current Selection owned/referenced by the Selector, using the provided SelectionEditor and UpdateConfig.
virtual void UpdateSelectionViaRaycast (const FWorldRayQueryInfo &RayInfo, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut)=0
Update the active selection based on a world-space Ray.
virtual void UpdateSelectionViaShape (const FWorldShapeQueryInfo &ShapeInfo, FGeometrySelectionEditor &SelectionEditor, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut)=0
Update the active selection based on a world-space Shape.
Data Fields
FGeometrySelectionElements bool bool bIsForPreview = 0
FGeometrySelectionElements bool bTransformToWorld
FGeometrySelectionElements & ElementsInOut
Protected Member Functions
void NotifyGeometryModified ()
Protected Attributes
FOnGeometryModified OnGeometryModifed
Detailed Description
IGeometrySelector is a base API definition for, roughly, "an object that knows how to select elements and/or work with element selections on some other object", where "element" is some "part" of the object, like a mesh edge/vertex/triangle, or intermediate structure (eg a polygroup).
Essentially the purpose of IGeometrySelector is to provide the bridge between "object that can have a selection" and "the active selection on that object". The Selection is stored as a FGeometrySelection which has no reference to a type or target object, and standard target objects (eg a StaticMesh, Volume, etc) have no inherent knowledge of, or support for, low-level geometry selections. So the Selector provides these capabilities, as well as related functionality like being able to transform an active selection and emit necessary transactions/etc.
Generally clients will not create a IGeometrySelector instance directly. For a given implmentation, a IGeometrySelectorFactory is registered with the UGeometrySelectionManager, and it creates instances based on the active selection.
Where possible, the UGeometrySelectionManager will also "sleep" a IGeometrySelector for a given target object instead of destroying it when the object is deselected, and then "restore" it if the object is re-selected. This avoids frequent churn in Selectors as the user clicks between objects.
Selector implementations should ideally have a strategy to lazy-construct any large data structures (eg mesh AABBTrees, etc). Again this is to avoid excessive overhead when the user (for example) selects a large object but has no intention of doing element-level selection.
Definition at line 227 of file GeometrySelector.h.
Member Typedef Documentation
FGeometrySelection
using IGeometrySelector::FGeometrySelection = UE::Geometry::FGeometrySelection
Definition at line 230 of file GeometrySelector.h.
FGeometrySelectionBounds
using IGeometrySelector::FGeometrySelectionBounds = UE::Geometry::FGeometrySelectionBounds
Definition at line 232 of file GeometrySelector.h.
FGeometrySelectionEditor
using IGeometrySelector::FGeometrySelectionEditor = UE::Geometry::FGeometrySelectionEditor
Definition at line 231 of file GeometrySelector.h.
FGeometrySelectionElements
using IGeometrySelector::FGeometrySelectionElements = UE::Geometry::FGeometrySelectionElements
Definition at line 233 of file GeometrySelector.h.
FGeometrySelectionUpdateConfig
using IGeometrySelector::FGeometrySelectionUpdateConfig = UE::Geometry::FGeometrySelectionUpdateConfig
Definition at line 234 of file GeometrySelector.h.
FGeometrySelectionUpdateResult
using IGeometrySelector::FGeometrySelectionUpdateResult = UE::Geometry::FGeometrySelectionUpdateResult
Definition at line 235 of file GeometrySelector.h.
Member Enumeration Documentation
EInitializeSelectionMode
enum class IGeometrySelector::EInitializeSelectionMode strong
Enumerator
All
Connected
AdjacentToBorder
Definition at line 285 of file GeometrySelector.h.
Constructor & Destructor Documentation
~IGeometrySelector()
virtual IGeometrySelector::~IGeometrySelector () inline virtual
Definition at line 237 of file GeometrySelector.h.
Member Function Documentation
AccumulateElementsFromPredicate()
virtual void IGeometrySelector::AccumulateElementsFromPredicate (FGeometrySelectionElements & ElementsInOut, bool bTransformToWorld, bool bIsForPreview, bool bUseGroupTopology, TFunctionRef< bool(UE::Geometry::EGeometryElementType, UE::Geometry::FGeoSelectionID)> Predicate) pure virtual
Accumulate all geometric elements (currently 3D triangles, line segments, and points) in the provided ElementsInOut by initializing vertex, edge, and face selections using the provided predicate and then accumulating elements for those selections.
ElementsInOut is not cleared.
Parameters
bTransformToWorld if true each geometric element will be transformed to World space, based on GetLocalToWorldTransform()
bIsForPreview if true, geometry is being collected for a preview of selection. Selector may return simplified geometry in this case
bUseGroupTopology if true, attempt to use group topology when populating ElementsInOut
Predicate if true for a given element type and element ID, this element will be collected, otherwise this element will be skipped.
Implemented in FBaseDynamicMeshSelector.
References AccumulateElementsFromPredicate(), bIsForPreview, bTransformToWorld, ElementsInOut, Geometry, and Predicate.
Referenced by AccumulateElementsFromPredicate().
AccumulateSelectionBounds()
virtual void IGeometrySelector::AccumulateSelectionBounds (const FGeometrySelection & Selection, FGeometrySelectionBounds & BoundsInOut, bool bTransformToWorld) pure virtual
Accumulate the bounds of the provided Selection in the provided BoundsInOut.
BoundsInOut is not cleared.
Parameters
bTransformToWorld if true each bounded point/element will be transformed to World space before being "contained" in BoundsInOut
Implemented in FBaseDynamicMeshSelector.
References bTransformToWorld.
AccumulateSelectionElements()
virtual void IGeometrySelector::AccumulateSelectionElements (const FGeometrySelection & Selection, FGeometrySelectionElements & ElementsInOut, bool bTransformToWorld, UE::Geometry::EEnumerateSelectionMapping Flags = UE::Geometry::EEnumerateSelectionMapping::Default) pure virtual
Accumulate geometric elements (currently 3D triangles, line segments, and points) for the provided Selection in the provided ElementsInOut.
ElementsInOut is not cleared.
Parameters
bTransformToWorld if true each geometric element will be transformed to World space, based on GetLocalToWorldTransform()
Flags determines which pieces of the geometry should be rendered
Implemented in FBaseDynamicMeshSelector.
References AccumulateSelectionElements(), bTransformToWorld, Default, ElementsInOut, Flags, and Geometry.
Referenced by AccumulateSelectionElements().
DECLARE_MULTICAST_DELEGATE_OneParam()
IGeometrySelector::DECLARE_MULTICAST_DELEGATE_OneParam (FOnGeometryModified , IGeometrySelector * Selector)
References DECLARE_MULTICAST_DELEGATE_OneParam().
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
GetIdentifier()
virtual FGeometryIdentifier IGeometrySelector::GetIdentifier () const pure virtual
Returns
a FGeometryIdentifier for this Selector.
Implemented in FBaseDynamicMeshSelector.
GetLocalToWorldTransform()
virtual FTransform IGeometrySelector::GetLocalToWorldTransform () const pure virtual
Returns
the World transform for the Selector's target object
Implemented in FBaseDynamicMeshSelector.
GetOnGeometryModifed()
FOnGeometryModified & IGeometrySelector::GetOnGeometryModifed () inline
The OnGeometryModified delegate will fire if the geometry of the Selector's Target Object is modified.
For example if a UDynamicMesh is edited, OnGeometryModified will be broadcast.
Definition at line 462 of file GeometrySelector.h.
References GetOnGeometryModifed(), and OnGeometryModifed.
Referenced by GetOnGeometryModifed().
GetSelectionFrame()
virtual void IGeometrySelector::GetSelectionFrame (const FGeometrySelection & Selection, UE::Geometry::FFrame3d & SelectionFrameOut, bool bTransformToWorld) pure virtual
Compute a 3D frame for the provided Selection.
For example this could simply be a frame aligned to the XYZ axes at the center of the selection bounding-box, or something more sophisticated, like aligned to the tangent-space of the selected element(s), etc.
Parameters
bTransformToWorld if true the resulting SelectionFrameOut will be in world-space, based on GetLocalToWorldTransform()
Implemented in FBaseDynamicMeshSelector.
References bTransformToWorld.
GetSelectionPreviewForRaycast()
virtual void IGeometrySelector::GetSelectionPreviewForRaycast (const FWorldRayQueryInfo & RayInfo, FGeometrySelectionEditor & PreviewEditor) pure virtual
Query the Selector for a potential selection based on world-space Ray.
The intention of this query is that it be used for "selection preview", eg like hover-highlighting. The PreviewEditor will always be updated in 'Add' mode, and currently no result information will be returned.
Implemented in FBaseDynamicMeshSelector.
GetTargetFrame()
virtual void IGeometrySelector::GetTargetFrame (const FGeometrySelection & Selection, UE::Geometry::FFrame3d & SelectionFrameOut) pure virtual
Compute a 3D frame for the Selector's target object.
Implemented in FBaseDynamicMeshSelector.
InitializeSelectionFromPredicate()
virtual void IGeometrySelector::InitializeSelectionFromPredicate (FGeometrySelection & SelectionInOut, TFunctionRef< bool(UE::Geometry::FGeoSelectionID)> SelectionIDPredicate, EInitializeSelectionMode InitializeMode = EInitializeSelectionMode::All, const FGeometrySelection * ReferenceSelection = nullptr) pure virtual
Populate a Selection using the provided ReferenceMode, with a Predicate and optional ReferenceSelection.
Note that this method does not modify/access any selection that might be "owned" by the Selector. It is part of the IGeometrySelector API because often a Selector has access to internal data structures (like a Mesh, GroupTopology, etc) that are required to initialize a Selection.
Parameters
SelectionInOut the Selection to initialize, the input Geometry/Topology types define what type of element will be selected
SelectionIDPredicate only Elements that pass this predicate will be included in SelectionInOut
InitializeMode method to use to initialize SelectionInOut
ReferenceSelection optional Selection to select "relative to", based on the InitializeMode
Implemented in FBaseDynamicMeshSelector.
References All.
InitializeTransformation()
virtual IGeometrySelectionTransformer * IGeometrySelector::InitializeTransformation (const FGeometrySelection & Selection) pure virtual
Create and initialize a IGeometrySelectionTransformer for the provided Selection.
IGeometrySelector retains ownership of the active Transformer, it should not be deleted by the caller, but instead ShutdownTransformation() should be called.
Implemented in FDynamicMeshSelector.
References InitializeTransformation().
Referenced by InitializeTransformation().
IsLockable()
virtual bool IGeometrySelector::IsLockable () const inline virtual
Definition at line 279 of file GeometrySelector.h.
IsLocked()
virtual bool IGeometrySelector::IsLocked () const inline virtual
Definition at line 280 of file GeometrySelector.h.
NotifyGeometryModified()
void IGeometrySelector::NotifyGeometryModified () inline protected
Definition at line 466 of file GeometrySelector.h.
References OnGeometryModifed.
RayHitTest()
virtual bool IGeometrySelector::RayHitTest (const FWorldRayQueryInfo & RayInfo, UE::Geometry::FGeometrySelectionHitQueryConfig QueryConfig, FInputRayHit & HitResultOut) pure virtual
Check for intersection between a world-space Ray with the Selector's target object and return a FInputRayHit result.
RayHitTest() must return true for other raycast-based functions like UpdateSelectionViaRaycast() to be called.
Returns
true on hit, false on miss
Implemented in FBaseDynamicMeshSelector.
Restore()
virtual bool IGeometrySelector::Restore () inline virtual
Restore a Selector that has had Sleep() called on it.
Returns
true on success
Reimplemented in FBaseDynamicMeshSelector.
Definition at line 263 of file GeometrySelector.h.
SetLockedState()
virtual void IGeometrySelector::SetLockedState (bool bLocked) inline virtual
Definition at line 281 of file GeometrySelector.h.
Shutdown()
virtual void IGeometrySelector::Shutdown () pure virtual
Disconnect the Selector from its target object and prepare for deletion.
Implemented in FBaseDynamicMeshSelector.
ShutdownTransformation()
virtual void IGeometrySelector::ShutdownTransformation (IGeometrySelectionTransformer * Transformer) pure virtual
Shutdown an active IGeometrySelectionTransformer.
Generally only one Transformer may be active at any time, and it is an error to shut it down multiple times.
Implemented in FDynamicMeshSelector.
References ShutdownTransformation().
Referenced by ShutdownTransformation().
Sleep()
virtual bool IGeometrySelector::Sleep () inline virtual
Temporarily disable the Selector, with the intention of re-enabling it (via Restore()) in the future.
Sleep should (currently) free any large memory data structures.
Returns
true if Sleep was successful, if not the Selector will likely be Shutdown
Reimplemented in FBaseDynamicMeshSelector.
Definition at line 257 of file GeometrySelector.h.
SupportsSleep()
virtual bool IGeometrySelector::SupportsSleep () const inline virtual
The SelectionManager will call SupportsSleep() to determine if an IGeometrySelector needs to be destroyed when the target object is deselected, or if it can be re-used (generally more efficient)
Reimplemented in FBaseDynamicMeshSelector.
Definition at line 250 of file GeometrySelector.h.
UE_DEPRECATED()
IGeometrySelector::UE_DEPRECATED (5. 5, "AccumulateSelectionElements which takes a bIsForPreview boolean is deprecated." "Please use the function of the same name which takes EEnumerateSelectionMapping flags instead") const &
Prefer AccumulateSelectionElements with Flags parameter.
UpdateSelectionFromSelection()
virtual void IGeometrySelector::UpdateSelectionFromSelection (const FGeometrySelection & FromSelection, bool bAllowConversion, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, UE::Geometry::FGeometrySelectionDelta * SelectionDelta = nullptr) pure virtual
Combine FromSelection with the current Selection owned/referenced by the Selector, using the provided SelectionEditor and UpdateConfig.
This can be used to explicitly initialize the Selection, restore it to a previous state for undo/redo, etc.
Parameters
bAllowConversion if true, FromSelection's Geometry/Topology type will be converted to the internal types of the Selector/SelectionEditor
SelectionDelta if passed as non-null, this Delta will be initialized based on the change in the internal Selection
Implemented in FBaseDynamicMeshSelector.
UpdateSelectionViaRaycast()
virtual void IGeometrySelector::UpdateSelectionViaRaycast (const FWorldRayQueryInfo & RayInfo, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut) pure virtual
Update the active selection based on a world-space Ray.
Should only be called if RayHitTest() returns true. Uses the provided SelectionEditor and UpdateConfig to do the update Information about any changes actually made to the selection via the SelectionEditor are returned in ResultOut
Implemented in FBaseDynamicMeshSelector.
UpdateSelectionViaShape()
virtual void IGeometrySelector::UpdateSelectionViaShape (const FWorldShapeQueryInfo & ShapeInfo, FGeometrySelectionEditor & SelectionEditor, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut) pure virtual
Update the active selection based on a world-space Shape.
Uses the provided SelectionEditor and UpdateConfig to do the update Information about any changes actually made to the selection via the SelectionEditor are returned in ResultOut
Implemented in FBaseDynamicMeshSelector.
Field Documentation
bIsForPreview
FGeometrySelectionElements bool bool IGeometrySelector::bIsForPreview = 0
Definition at line 415 of file GeometrySelector.h.
Referenced by FBaseDynamicMeshSelector::AccumulateElementsFromPredicate(), and AccumulateElementsFromPredicate().
bTransformToWorld
FGeometrySelectionElements bool IGeometrySelector::bTransformToWorld
Definition at line 415 of file GeometrySelector.h.
Referenced by AccumulateElementsFromPredicate(), AccumulateSelectionBounds(), AccumulateSelectionElements(), and GetSelectionFrame().
ElementsInOut
FGeometrySelectionElements& IGeometrySelector::ElementsInOut
Definition at line 415 of file GeometrySelector.h.
Referenced by AccumulateElementsFromPredicate(), and AccumulateSelectionElements().
OnGeometryModifed
FOnGeometryModified IGeometrySelector::OnGeometryModifed protected
Definition at line 465 of file GeometrySelector.h.
Referenced by GetOnGeometryModifed(), and NotifyGeometryModified().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Selection/GeometrySelector.h