Unreal Engine 5.6 C++ API: UEditorPerformanceProjectSettings Class Reference
UEditorPerformanceProjectSettings Class Reference
#include "EditorProjectSettings.h"
Public Member Functions
virtual UNREALED_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual UNREALED_API void PostInitProperties () override
Private Member Functions
GENERATED_UCLASS_BODY() public UPROPERTY ()) EScreenPercentageMode MobileScreenPercentageMode
UPROPERTY ()) EScreenPercentageMode NonRealtimeScreenPercentageMode
UPROPERTY ()) EScreenPercentageMode PathTracerScreenPercentageMode
UPROPERTY ()) EScreenPercentageMode VRScreenPercentageMode
UPROPERTY ()) float ManualScreenPercentage
UPROPERTY ()) int32 MaxViewportRenderingResolution
UPROPERTY ()) int32 MinViewportRenderingResolution
Static Private Member Functions
static UNREALED_API void ExportResolutionValuesToConsoleVariables ()
Detailed Description
Definition at line 223 of file EditorProjectSettings.h.
Member Function Documentation
ExportResolutionValuesToConsoleVariables()
UNREALED_API void UEditorPerformanceProjectSettings::ExportResolutionValuesToConsoleVariables () static private
References ExportResolutionValuesToConsoleVariables().
Referenced by ExportResolutionValuesToConsoleVariables().
PostEditChangeProperty()
virtual UNREALED_API void UEditorPerformanceProjectSettings::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
References config, defaultconfig, Editor, meta, MinimalAPI, PostEditChangeProperty(), and UCLASS().
Referenced by PostEditChangeProperty().
PostInitProperties()
virtual UNREALED_API void UEditorPerformanceProjectSettings::PostInitProperties () override virtual
References PostInitProperties().
Referenced by PostInitProperties().
UPROPERTY() [1/7]
GENERATED_UCLASS_BODY() public UEditorPerformanceProjectSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/7]
UEditorPerformanceProjectSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
UPROPERTY() [3/7]
UEditorPerformanceProjectSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
UPROPERTY() [4/7]
UEditorPerformanceProjectSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
UPROPERTY() [5/7]
UEditorPerformanceProjectSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
UPROPERTY() [6/7]
UEditorPerformanceProjectSettings::UPROPERTY () private
UPROPERTY() [7/7]
UEditorPerformanceProjectSettings::UPROPERTY () private
References Category, config, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Settings/EditorProjectSettings.h