Unreal Engine 5.6 C++ API: IStructCustomization Class Reference
IStructCustomization Class Reference abstract
Deprecated IStructCustomization interface.
#include "IPropertyTypeCustomization.h"
Public Member Functions
virtual void CustomizeChildren (TSharedRef< IPropertyHandle > PropertyHandle, IDetailChildrenBuilder &ChildBuilder, IPropertyTypeCustomizationUtils &CustomizationUtils)
Called when the children of the property should be customized or extra rows added.
virtual void CustomizeHeader (TSharedRef< IPropertyHandle > PropertyHandle, FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &CustomizationUtils)
Called when the header of the property (the row in the details panel where the property is shown) If nothing is added to the row, the header is not displayed.
virtual void CustomizeStructChildren (TSharedRef< IPropertyHandle > StructPropertyHandle, class IDetailChildrenBuilder &ChildBuilder, IStructCustomizationUtils &StructCustomizationUtils)=0
Called when the children of the struct should be customized.
virtual void CustomizeStructHeader (TSharedRef< IPropertyHandle > StructPropertyHandle, class FDetailWidgetRow &HeaderRow, IStructCustomizationUtils &StructCustomizationUtils)=0
Called when the header of the struct (usually where the name of the struct and information about the struct as a whole is added) If nothing is added to the row, the header is not displayed.
Public Member Functions inherited from IPropertyTypeCustomization
virtual ~IPropertyTypeCustomization ()
virtual bool ShouldInlineKey () const
Public Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedRef< IPropertyTypeCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPropertyTypeCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Deprecated IStructCustomization interface.
Definition at line 97 of file IPropertyTypeCustomization.h.
Member Function Documentation
CustomizeChildren()
virtual void IStructCustomization::CustomizeChildren (TSharedRef< IPropertyHandle > PropertyHandle, IDetailChildrenBuilder & ChildBuilder, IPropertyTypeCustomizationUtils & CustomizationUtils) inline virtual
Called when the children of the property should be customized or extra rows added.
Parameters
PropertyHandle Handle to the property being customized
StructBuilder A builder for adding children
StructCustomizationUtils Utilities for customization
Implements IPropertyTypeCustomization.
Definition at line 105 of file IPropertyTypeCustomization.h.
References CustomizeStructChildren().
CustomizeHeader()
virtual void IStructCustomization::CustomizeHeader (TSharedRef< IPropertyHandle > PropertyHandle, FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & CustomizationUtils) inline virtual
Called when the header of the property (the row in the details panel where the property is shown) If nothing is added to the row, the header is not displayed.
Parameters
PropertyHandle Handle to the property being customized
HeaderRow A row that widgets can be added to
StructCustomizationUtils Utilities for customization
Implements IPropertyTypeCustomization.
Definition at line 100 of file IPropertyTypeCustomization.h.
References CustomizeStructHeader().
CustomizeStructChildren()
virtual void IStructCustomization::CustomizeStructChildren (TSharedRef< IPropertyHandle > StructPropertyHandle, class IDetailChildrenBuilder & ChildBuilder, IStructCustomizationUtils & StructCustomizationUtils) pure virtual
Called when the children of the struct should be customized.
Parameters
StructPropertyHandle Handle to the struct property
StructBuilder A builder for customizing the struct children
StructCustomizationUtils Utilities for struct customization
Referenced by CustomizeChildren().
CustomizeStructHeader()
virtual void IStructCustomization::CustomizeStructHeader (TSharedRef< IPropertyHandle > StructPropertyHandle, class FDetailWidgetRow & HeaderRow, IStructCustomizationUtils & StructCustomizationUtils) pure virtual
Called when the header of the struct (usually where the name of the struct and information about the struct as a whole is added) If nothing is added to the row, the header is not displayed.
Parameters
StructPropertyHandle Handle to the struct property
HeaderRow A row that widgets can be added to
StructCustomizationUtils Utilities for struct customization
Referenced by CustomizeHeader().
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/IPropertyTypeCustomization.h