Unreal Engine 5.6 C++ API: IRVOAvoidanceInterface Class Reference
IRVOAvoidanceInterface Class Reference abstract
#include "RVOAvoidanceInterface.h"
Private Member Functions
GENERATED_IINTERFACE_BODY () virtual void SetRVOAvoidanceUID(int32 UID)=0
Store the AvoidanceUID generated by the Avoidance Manager.
virtual int32 GetAvoidanceGroupMask ()=0
This actor's avoidance group mask.
virtual int32 GetGroupsToAvoidMask ()=0
Agent groups to avoid mask.
virtual int32 GetGroupsToIgnoreMask ()=0
Agent groups to ignore.
virtual float GetRVOAvoidanceConsiderationRadius ()=0
The scaled collider radius to consider for RVO avoidance.
virtual float GetRVOAvoidanceHeight ()=0
The scaled collider height to consider for RVO avoidance.
virtual FVector GetRVOAvoidanceOrigin ()=0
Get the Location from where the RVO avoidance should originate.
virtual float GetRVOAvoidanceRadius ()=0
The scaled collider radius to consider for RVO avoidance.
virtual int32 GetRVOAvoidanceUID ()=0
Return the AvoidanceUID assigned by the Avoidance Manager during registration.
virtual float GetRVOAvoidanceWeight ()=0
Returns the AvoidanceWeight assigned by the Avoidance Manager during registration.
virtual FVector GetVelocityForRVOConsideration ()=0
The velocity of the avoiding entity.
virtual void SetAvoidanceGroupMask (int32 GroupFlags)=0
Store the avoidance group mask.
virtual void SetGroupsToAvoidMask (int32 GroupFlags)=0
Store the groups to avoid mask.
virtual void SetGroupsToIgnoreMask (int32 GroupFlags)=0
Store the groups to ignore mask.
virtual void SetRVOAvoidanceWeight (float Weight)=0
Store the AvoidanceWeight generated by the Avoidance Manager.
Detailed Description
Definition at line 22 of file RVOAvoidanceInterface.h.
Member Function Documentation
GENERATED_IINTERFACE_BODY()
IRVOAvoidanceInterface::GENERATED_IINTERFACE_BODY () private pure virtual
Store the AvoidanceUID generated by the Avoidance Manager.
GetAvoidanceGroupMask()
virtual int32 IRVOAvoidanceInterface::GetAvoidanceGroupMask () private pure virtual
This actor's avoidance group mask.
References GetAvoidanceGroupMask().
Referenced by GetAvoidanceGroupMask().
GetGroupsToAvoidMask()
virtual int32 IRVOAvoidanceInterface::GetGroupsToAvoidMask () private pure virtual
Agent groups to avoid mask.
References GetGroupsToAvoidMask().
Referenced by GetGroupsToAvoidMask().
GetGroupsToIgnoreMask()
virtual int32 IRVOAvoidanceInterface::GetGroupsToIgnoreMask () private pure virtual
Agent groups to ignore.
References GetGroupsToIgnoreMask().
Referenced by GetGroupsToIgnoreMask().
GetRVOAvoidanceConsiderationRadius()
virtual float IRVOAvoidanceInterface::GetRVOAvoidanceConsiderationRadius () private pure virtual
The scaled collider radius to consider for RVO avoidance.
References GetRVOAvoidanceConsiderationRadius().
Referenced by GetRVOAvoidanceConsiderationRadius().
GetRVOAvoidanceHeight()
virtual float IRVOAvoidanceInterface::GetRVOAvoidanceHeight () private pure virtual
The scaled collider height to consider for RVO avoidance.
References GetRVOAvoidanceHeight().
Referenced by GetRVOAvoidanceHeight().
GetRVOAvoidanceOrigin()
virtual FVector IRVOAvoidanceInterface::GetRVOAvoidanceOrigin () private pure virtual
Get the Location from where the RVO avoidance should originate.
References FVector, and GetRVOAvoidanceOrigin().
Referenced by GetRVOAvoidanceOrigin().
GetRVOAvoidanceRadius()
virtual float IRVOAvoidanceInterface::GetRVOAvoidanceRadius () private pure virtual
The scaled collider radius to consider for RVO avoidance.
References GetRVOAvoidanceRadius().
Referenced by GetRVOAvoidanceRadius().
GetRVOAvoidanceUID()
virtual int32 IRVOAvoidanceInterface::GetRVOAvoidanceUID () private pure virtual
Return the AvoidanceUID assigned by the Avoidance Manager during registration.
References GetRVOAvoidanceUID().
Referenced by GetRVOAvoidanceUID().
GetRVOAvoidanceWeight()
virtual float IRVOAvoidanceInterface::GetRVOAvoidanceWeight () private pure virtual
Returns the AvoidanceWeight assigned by the Avoidance Manager during registration.
References GetRVOAvoidanceWeight().
Referenced by GetRVOAvoidanceWeight().
GetVelocityForRVOConsideration()
virtual FVector IRVOAvoidanceInterface::GetVelocityForRVOConsideration () private pure virtual
The velocity of the avoiding entity.
References FVector, and GetVelocityForRVOConsideration().
Referenced by GetVelocityForRVOConsideration().
SetAvoidanceGroupMask()
virtual void IRVOAvoidanceInterface::SetAvoidanceGroupMask (int32 GroupFlags) private pure virtual
Store the avoidance group mask.
References SetAvoidanceGroupMask().
Referenced by SetAvoidanceGroupMask().
SetGroupsToAvoidMask()
virtual void IRVOAvoidanceInterface::SetGroupsToAvoidMask (int32 GroupFlags) private pure virtual
Store the groups to avoid mask.
References SetGroupsToAvoidMask().
Referenced by SetGroupsToAvoidMask().
SetGroupsToIgnoreMask()
virtual void IRVOAvoidanceInterface::SetGroupsToIgnoreMask (int32 GroupFlags) private pure virtual
Store the groups to ignore mask.
References SetGroupsToIgnoreMask().
Referenced by SetGroupsToIgnoreMask().
SetRVOAvoidanceWeight()
virtual void IRVOAvoidanceInterface::SetRVOAvoidanceWeight (float Weight) private pure virtual
Store the AvoidanceWeight generated by the Avoidance Manager.
References SetRVOAvoidanceWeight(), and Weight.
Referenced by SetRVOAvoidanceWeight().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AI/RVOAvoidanceInterface.h