Unreal Engine 5.6 C++ API: UE::Insights::FBaseTreeNode Class Reference
UE::Insights::FBaseTreeNode Class Reference
#include "BaseTreeNode.h"
Data Structures
struct FGroupNodeData
Public Member Functions
FBaseTreeNode (const FName InName, bool bInIsGroup)
Initialization constructor for the node.
virtual ~FBaseTreeNode ()
void AddChild (const FBaseTreeNodePtr &ChildPtr)
Adds specified node to the children nodes.
void AddChildAndSetParent (const FBaseTreeNodePtr &ChildPtr)
Adds specified node to the children nodes.
void AddFilteredChild (const FBaseTreeNodePtr &ChildPtr)
Adds specified child to the filtered children nodes.
void ClearChildren (int32 NewSize=0)
Clears children.
void ClearFilteredChildren (int32 NewSize=0)
Clears (removes all) the filtered children nodes.
void EnumerateChildren (TFunction< bool(const FBaseTreeNodePtr &)> Callback) const
Enumerates the children nodes.
void EnumerateFilteredChildren (TFunction< bool(const FBaseTreeNodePtr &)> Callback) const
Enumerates the filtered children nodes.
const TArray< FBaseTreeNodePtr > & GetChildren () const
int32 GetChildrenCount () const
virtual FLinearColor GetColor () const
uint32 GetDefaultSortOrder () const
virtual const FText GetDisplayName () const
virtual const FText GetExtraDisplayName () const
FBaseTreeNodePtr & GetFilteredChildNode (int32 Index)
const FBaseTreeNodePtr & GetFilteredChildNode (int32 Index) const
const TArray< FBaseTreeNodePtr > & GetFilteredChildren () const
int32 GetFilteredChildrenCount () const
virtual const FSlateBrush * GetIcon () const
virtual FLinearColor GetIconColor () const
const FName & GetName () const
FBaseTreeNodePtr GetParent () const
FBaseTreeNodeWeak GetParentWeak () const
virtual const FText GetTooltipText () const
virtual bool HasExtraDisplayName () const
void InitGroupData ()
Initializes the group data, allowing this node to accept children.
bool IsExpanded () const
virtual bool IsFiltered () const
bool IsGroup () const
int32 RemoveChild (const FBaseTreeNodePtr &ChildPtr)
Removes the specified node from the children nodes (preserving the order).
int32 RemoveChildSwap (const FBaseTreeNodePtr &ChildPtr)
Removes the specified node from the children nodes (not preserving the order).
void RemoveFromParent ()
Removes this node from the parent's children nodes (preserving the order).
void RemoveFromParentSwap ()
Removes this node from the parent's children nodes (not preserving the order).
void RemoveGroupData ()
void ResetFilteredChildren ()
Resets the filtered children nodes.
void ResetFilteredChildrenRec ()
Resets the filtered children for this node and also recursively for all children nodes.
void ResetParentForChildren ()
void ResetParentForChildrenRec ()
void SetDefaultSortOrder (uint32 Order)
void SetExpansion (bool bOnOff)
void SetParent (const FBaseTreeNodeWeak &InParentWeak)
void SetParentForChildren ()
void SetParentForChildrenRec ()
void SortChildren (const ITableCellValueSorter &Sorter, ESortMode SortMode)
template<typename PredicateType>
void SortChildren (PredicateType Predicate)
void SortFilteredChildren (const ITableCellValueSorter &Sorter, ESortMode SortMode)
template<typename PredicateType>
void SortFilteredChildren (PredicateType Predicate)
void SwapChildren (TArray< FBaseTreeNodePtr > &NewChildren)
void SwapChildrenFast (TArray< FBaseTreeNodePtr > &NewChildren)
Public Member Functions inherited from TSharedFromThis< FBaseTreeNode >
TSharedRef< FBaseTreeNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBaseTreeNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static FLinearColor GetDefaultColor (bool bIsGroupNode)
static const FSlateBrush * GetDefaultIcon (bool bIsGroupNode)
static FLinearColor GetDefaultIconColor (bool bIsGroupNode)
Protected Member Functions
TArray< FBaseTreeNodePtr > & GetChildrenMutable ()
Protected Member Functions inherited from TSharedFromThis< FBaseTreeNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
int32 DefaultSortOrder
The default sort order.
FGroupNodeData * GroupData
The struct containing properties of a group node.
const FName Name
The name of this node.
FBaseTreeNodeWeak Parent
A weak pointer to the parent group of this node.
Static Private Attributes
static FGroupNodeData DefaultGroupData
The only group data for "not a group" nodes.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FBaseTreeNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 41 of file BaseTreeNode.h.
Constructor & Destructor Documentation
FBaseTreeNode()
UE::Insights::FBaseTreeNode::FBaseTreeNode (const FName InName, bool bInIsGroup) inline explicit
Initialization constructor for the node.
Definition at line 69 of file BaseTreeNode.h.
References DefaultGroupData, DefaultSortOrder, GroupData, InName, Name, and Parent.
Referenced by UE::Insights::FTableTreeNode::FTableTreeNode(), UE::Insights::FTableTreeNode::FTableTreeNode(), and UE::Insights::FTableTreeNode::INSIGHTS_DECLARE_RTTI().
~FBaseTreeNode()
virtual UE::Insights::FBaseTreeNode::~FBaseTreeNode () inline virtual
Definition at line 77 of file BaseTreeNode.h.
References RemoveGroupData().
Member Function Documentation
AddChild()
void UE::Insights::FBaseTreeNode::AddChild (const FBaseTreeNodePtr & ChildPtr) inline
Adds specified node to the children nodes.
Definition at line 249 of file BaseTreeNode.h.
References GroupData.
AddChildAndSetParent()
void UE::Insights::FBaseTreeNode::AddChildAndSetParent (const FBaseTreeNodePtr & ChildPtr) inline
Adds specified node to the children nodes.
Also sets the current node as the parent group of the specified node.
Definition at line 255 of file BaseTreeNode.h.
References TSharedFromThis< FBaseTreeNode >::AsWeak(), and GroupData.
Referenced by UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes().
AddFilteredChild()
void UE::Insights::FBaseTreeNode::AddFilteredChild (const FBaseTreeNodePtr & ChildPtr) inline
Adds specified child to the filtered children nodes.
Definition at line 438 of file BaseTreeNode.h.
References GroupData.
ClearChildren()
void UE::Insights::FBaseTreeNode::ClearChildren (int32 NewSize = 0) inline
Clears children.
Definition at line 347 of file BaseTreeNode.h.
References GroupData, and ResetParentForChildren().
Referenced by UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GroupNodes().
ClearFilteredChildren()
void UE::Insights::FBaseTreeNode::ClearFilteredChildren (int32 NewSize = 0) inline
Clears (removes all) the filtered children nodes.
Definition at line 428 of file BaseTreeNode.h.
References GroupData.
EnumerateChildren()
void UE::Insights::FBaseTreeNode::EnumerateChildren (TFunction< bool(const FBaseTreeNodePtr &)> Callback) const inline
Enumerates the children nodes.
Definition at line 221 of file BaseTreeNode.h.
References GroupData.
EnumerateFilteredChildren()
void UE::Insights::FBaseTreeNode::EnumerateFilteredChildren (TFunction< bool(const FBaseTreeNodePtr &)> Callback) const inline
Enumerates the filtered children nodes.
Definition at line 400 of file BaseTreeNode.h.
References GroupData.
GetChildren()
const TArray< FBaseTreeNodePtr > & UE::Insights::FBaseTreeNode::GetChildren () const inline
Returns
a const reference to the children nodes of this group.
Definition at line 235 of file BaseTreeNode.h.
References GroupData.
GetChildrenCount()
int32 UE::Insights::FBaseTreeNode::GetChildrenCount () const inline
Returns
the number of children nodes.
Definition at line 213 of file BaseTreeNode.h.
References GroupData.
GetChildrenMutable()
TArray< FBaseTreeNodePtr > & UE::Insights::FBaseTreeNode::GetChildrenMutable () inline protected
Returns
a reference to the children nodes of this group.
Definition at line 509 of file BaseTreeNode.h.
References GroupData.
GetColor()
virtual FLinearColor UE::Insights::FBaseTreeNode::GetColor () const inline virtual
Returns
the color tint to be used for the name text of this node.
Reimplemented in UE::Insights::FCustomTableTreeNode.
Definition at line 147 of file BaseTreeNode.h.
References GetDefaultColor(), and IsGroup().
GetDefaultColor()
FLinearColor UE::Insights::FBaseTreeNode::GetDefaultColor (bool bIsGroupNode) static
Returns
the default color tint for a group or leaf node.
Referenced by GetColor().
GetDefaultIcon()
const FSlateBrush * UE::Insights::FBaseTreeNode::GetDefaultIcon (bool bIsGroupNode) static
Returns
the default icon for a group/leaf node.
Referenced by GetIcon().
GetDefaultIconColor()
FLinearColor UE::Insights::FBaseTreeNode::GetDefaultIconColor (bool bIsGroupNode) static
Returns
the default color tint for a group or leaf node.
Referenced by GetIconColor().
GetDefaultSortOrder()
uint32 UE::Insights::FBaseTreeNode::GetDefaultSortOrder () const inline
Definition at line 495 of file BaseTreeNode.h.
References DefaultSortOrder.
GetDisplayName()
virtual const FText UE::Insights::FBaseTreeNode::GetDisplayName () const virtual
Returns
a name of this node to display in tree view.
GetExtraDisplayName()
virtual const FText UE::Insights::FBaseTreeNode::GetExtraDisplayName () const virtual
Returns
a name suffix for this node to display in tree view. Ex.: group nodes may include additional info, like the number of visible / total children.
GetFilteredChildNode() [1/2]
FBaseTreeNodePtr & UE::Insights::FBaseTreeNode::GetFilteredChildNode (int32 Index) inline
Returns
a reference to the filtered child node at specified index.
Definition at line 392 of file BaseTreeNode.h.
References GroupData.
GetFilteredChildNode() [2/2]
const FBaseTreeNodePtr & UE::Insights::FBaseTreeNode::GetFilteredChildNode (int32 Index) const inline
Returns
a const reference to the filtered child node at specified index.
Definition at line 384 of file BaseTreeNode.h.
References GroupData.
GetFilteredChildren()
const TArray< FBaseTreeNodePtr > & UE::Insights::FBaseTreeNode::GetFilteredChildren () const inline
Returns
a const reference to the children nodes that should be visible to the UI based on filtering.
Definition at line 414 of file BaseTreeNode.h.
References GroupData.
GetFilteredChildrenCount()
int32 UE::Insights::FBaseTreeNode::GetFilteredChildrenCount () const inline
Returns
the number of filtered children nodes.
Definition at line 376 of file BaseTreeNode.h.
References GroupData.
GetIcon()
virtual const FSlateBrush * UE::Insights::FBaseTreeNode::GetIcon () const inline virtual
Returns
the brush icon for this node.
Reimplemented in UE::Insights::FCustomTableTreeNode.
Definition at line 121 of file BaseTreeNode.h.
References GetDefaultIcon(), and IsGroup().
GetIconColor()
virtual FLinearColor UE::Insights::FBaseTreeNode::GetIconColor () const inline virtual
Returns
the color tint to be used for the icon of this node.
Reimplemented in UE::Insights::FCustomTableTreeNode.
Definition at line 134 of file BaseTreeNode.h.
References GetDefaultIconColor(), and IsGroup().
GetName()
const FName & UE::Insights::FBaseTreeNode::GetName () const inline
Returns
a name of this node.
Definition at line 85 of file BaseTreeNode.h.
References Name.
GetParent()
FBaseTreeNodePtr UE::Insights::FBaseTreeNode::GetParent () const inline
Returns
a reference to the parent group of this node; may be invalid.
Definition at line 166 of file BaseTreeNode.h.
References Parent.
GetParentWeak()
FBaseTreeNodeWeak UE::Insights::FBaseTreeNode::GetParentWeak () const inline
Returns
a weak reference to the parent group of this node; may be invalid.
Definition at line 158 of file BaseTreeNode.h.
References Parent.
GetTooltipText()
virtual const FText UE::Insights::FBaseTreeNode::GetTooltipText () const inline virtual
Returns
a descriptive text for this node to display in a tooltip.
Definition at line 108 of file BaseTreeNode.h.
References FText::GetEmpty().
HasExtraDisplayName()
virtual bool UE::Insights::FBaseTreeNode::HasExtraDisplayName () const virtual
Returns
true if the node has an extra display name (a name suffix to display in tree view).
InitGroupData()
void UE::Insights::FBaseTreeNode::InitGroupData () inline
Initializes the group data, allowing this node to accept children.
Definition at line 185 of file BaseTreeNode.h.
References DefaultGroupData, and GroupData.
IsExpanded()
bool UE::Insights::FBaseTreeNode::IsExpanded () const inline
Definition at line 475 of file BaseTreeNode.h.
References GroupData.
IsFiltered()
virtual bool UE::Insights::FBaseTreeNode::IsFiltered () const inline virtual
Reimplemented in UE::Insights::FTableTreeNode.
Definition at line 368 of file BaseTreeNode.h.
IsGroup()
bool UE::Insights::FBaseTreeNode::IsGroup () const inline
Returns
true if this node is a group node.
Definition at line 177 of file BaseTreeNode.h.
References DefaultGroupData, and GroupData.
Referenced by UE::Insights::FCustomTableTreeNode::FCustomTableTreeNode(), UE::Insights::FTableTreeNode::FTableTreeNode(), GetColor(), GetIcon(), GetIconColor(), UE::Insights::FCustomTableTreeNode::INSIGHTS_DECLARE_RTTI(), and SetExpansion().
RemoveChild()
int32 UE::Insights::FBaseTreeNode::RemoveChild (const FBaseTreeNodePtr & ChildPtr) inline
Removes the specified node from the children nodes (preserving the order).
If successful, resets the parent group of the specified node.
Definition at line 284 of file BaseTreeNode.h.
References GroupData, and TSharedPtr< ObjectType, InMode >::Reset().
RemoveChildSwap()
int32 UE::Insights::FBaseTreeNode::RemoveChildSwap (const FBaseTreeNodePtr & ChildPtr) inline
Removes the specified node from the children nodes (not preserving the order).
If successful, resets the parent group of the specified node.
Definition at line 295 of file BaseTreeNode.h.
References GroupData, and TSharedPtr< ObjectType, InMode >::Reset().
RemoveFromParent()
void UE::Insights::FBaseTreeNode::RemoveFromParent () inline
Removes this node from the parent's children nodes (preserving the order).
Also resets the parent group.
Definition at line 262 of file BaseTreeNode.h.
References TSharedFromThis< FBaseTreeNode >::AsShared(), TSharedPtr< ObjectType, InMode >::IsValid(), and Parent.
RemoveFromParentSwap()
void UE::Insights::FBaseTreeNode::RemoveFromParentSwap () inline
Removes this node from the parent's children nodes (not preserving the order).
Also resets the parent group.
Definition at line 273 of file BaseTreeNode.h.
References TSharedFromThis< FBaseTreeNode >::AsShared(), TSharedPtr< ObjectType, InMode >::IsValid(), and Parent.
RemoveGroupData()
void UE::Insights::FBaseTreeNode::RemoveGroupData () inline
Definition at line 193 of file BaseTreeNode.h.
References DefaultGroupData, and GroupData.
Referenced by ~FBaseTreeNode().
ResetFilteredChildren()
void UE::Insights::FBaseTreeNode::ResetFilteredChildren () inline
Resets the filtered children nodes.
The filtered array of children nodes will be initialized with the unfiltered array of children.
Definition at line 451 of file BaseTreeNode.h.
References GroupData.
Referenced by ResetFilteredChildrenRec().
ResetFilteredChildrenRec()
void UE::Insights::FBaseTreeNode::ResetFilteredChildrenRec () inline
Resets the filtered children for this node and also recursively for all children nodes.
The filtered array of children nodes will be initialized with the unfiltered array of children.
Definition at line 464 of file BaseTreeNode.h.
References GroupData, and ResetFilteredChildren().
ResetParentForChildren()
void UE::Insights::FBaseTreeNode::ResetParentForChildren () inline
Definition at line 329 of file BaseTreeNode.h.
References GroupData, and TSharedPtr< ObjectType, InMode >::Reset().
Referenced by ClearChildren(), and SwapChildren().
ResetParentForChildrenRec()
void UE::Insights::FBaseTreeNode::ResetParentForChildrenRec () inline
Definition at line 337 of file BaseTreeNode.h.
References GroupData, and TSharedPtr< ObjectType, InMode >::Reset().
SetDefaultSortOrder()
void UE::Insights::FBaseTreeNode::SetDefaultSortOrder (uint32 Order) inline
Definition at line 500 of file BaseTreeNode.h.
References DefaultSortOrder.
SetExpansion()
void UE::Insights::FBaseTreeNode::SetExpansion (bool bOnOff) inline
Definition at line 480 of file BaseTreeNode.h.
References GroupData, and IsGroup().
SetParent()
void UE::Insights::FBaseTreeNode::SetParent (const FBaseTreeNodeWeak & InParentWeak) inline
Definition at line 305 of file BaseTreeNode.h.
References Parent.
SetParentForChildren()
void UE::Insights::FBaseTreeNode::SetParentForChildren () inline
Definition at line 310 of file BaseTreeNode.h.
References TSharedFromThis< FBaseTreeNode >::AsWeak(), and GroupData.
Referenced by SwapChildren().
SetParentForChildrenRec()
void UE::Insights::FBaseTreeNode::SetParentForChildrenRec () inline
Definition at line 319 of file BaseTreeNode.h.
References TSharedFromThis< FBaseTreeNode >::AsWeak(), and GroupData.
SortChildren() [1/2]
void UE::Insights::FBaseTreeNode::SortChildren (const ITableCellValueSorter & Sorter, ESortMode SortMode)
SortChildren() [2/2]
template<typename PredicateType> void UE::Insights::FBaseTreeNode::SortChildren (PredicateType Predicate) inline
Definition at line 243 of file BaseTreeNode.h.
References GroupData, and Predicate.
SortFilteredChildren() [1/2]
void UE::Insights::FBaseTreeNode::SortFilteredChildren (const ITableCellValueSorter & Sorter, ESortMode SortMode)
SortFilteredChildren() [2/2]
template<typename PredicateType> void UE::Insights::FBaseTreeNode::SortFilteredChildren (PredicateType Predicate) inline
Definition at line 422 of file BaseTreeNode.h.
References GroupData, and Predicate.
SwapChildren()
void UE::Insights::FBaseTreeNode::SwapChildren (TArray< FBaseTreeNodePtr > & NewChildren) inline
Definition at line 353 of file BaseTreeNode.h.
References GroupData, ResetParentForChildren(), SetParentForChildren(), and Swap.
SwapChildrenFast()
void UE::Insights::FBaseTreeNode::SwapChildrenFast (TArray< FBaseTreeNodePtr > & NewChildren) inline
Definition at line 360 of file BaseTreeNode.h.
References GroupData, and Swap.
Field Documentation
DefaultGroupData
FGroupNodeData UE::Insights::FBaseTreeNode::DefaultGroupData static private
The only group data for "not a group" nodes.
Definition at line 528 of file BaseTreeNode.h.
Referenced by FBaseTreeNode(), InitGroupData(), IsGroup(), and RemoveGroupData().
DefaultSortOrder
int32 UE::Insights::FBaseTreeNode::DefaultSortOrder private
The default sort order.
Index used to optimize sorting.
Definition at line 516 of file BaseTreeNode.h.
Referenced by FBaseTreeNode(), GetDefaultSortOrder(), and SetDefaultSortOrder().
GroupData
FGroupNodeData* UE::Insights::FBaseTreeNode::GroupData private
The struct containing properties of a group node.
It is allocated only for group nodes.
Definition at line 525 of file BaseTreeNode.h.
Referenced by FBaseTreeNode(), AddChild(), AddChildAndSetParent(), AddFilteredChild(), ClearChildren(), ClearFilteredChildren(), EnumerateChildren(), EnumerateFilteredChildren(), GetChildren(), GetChildrenCount(), GetChildrenMutable(), GetFilteredChildNode(), GetFilteredChildNode(), GetFilteredChildren(), GetFilteredChildrenCount(), InitGroupData(), IsExpanded(), IsGroup(), RemoveChild(), RemoveChildSwap(), RemoveGroupData(), ResetFilteredChildren(), ResetFilteredChildrenRec(), ResetParentForChildren(), ResetParentForChildrenRec(), SetExpansion(), SetParentForChildren(), SetParentForChildrenRec(), SortChildren(), SortFilteredChildren(), SwapChildren(), and SwapChildrenFast().
Name
const FName UE::Insights::FBaseTreeNode::Name private
The name of this node.
Definition at line 519 of file BaseTreeNode.h.
Referenced by FBaseTreeNode(), and GetName().
Parent
FBaseTreeNodeWeak UE::Insights::FBaseTreeNode::Parent private
A weak pointer to the parent group of this node.
Definition at line 522 of file BaseTreeNode.h.
Referenced by FBaseTreeNode(), GetParent(), GetParentWeak(), RemoveFromParent(), RemoveFromParentSwap(), and SetParent().
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Table/ViewModels/BaseTreeNode.h