Unreal Engine 5.6 C++ API: FSkeletalMeshUpdate Class Reference
FSkeletalMeshUpdate Class Reference
This class provides a framework for loading and unloading the LODs of skeletal meshes.
#include "SkeletalMeshUpdate.h"
Public Member Functions
FSkeletalMeshUpdate (const USkeletalMesh *InMesh)
virtual ~FSkeletalMeshUpdate ()
virtual void Abort ()
Cancel the current update.
Public Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
TRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
EThreadType GetRelevantThread () const final override
Return the thread relevant to the next step of execution.
void PushTask (const FContext &Context, EThreadType InTaskThread, const FCallback &InTaskCallback, EThreadType InCancelationThread, const FCallback &InCancelationCallback)
Defines the next step to be executed.
Public Member Functions inherited from FRenderAssetUpdate
FRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
FReturnedRefCountValue AddRef () const final override
ETaskState DoLock ()
Perform a lock on the object, preventing any other thread from processing a pending task in Tick().
void DoUnlock (ETaskState PreviousTaskState)
Release any lock on the object, allowing other thread to modify it.
uint32 GetRefCount () const final override
bool IsCancelled () const
Returns whether the task was aborted through Abort() or cancelled.
bool IsCompleted () const
Returns whether the task has finished executing and there is no other thread possibly accessing it.
bool IsLocked () const
bool IsSuccessfullyFinished () const
Returns whether this update has finished successfully.
uint32 Release () const final override
void Tick (EThreadType InCurrentThread)
Do or schedule any pending work for a given texture.
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Additional Inherited Members
Public Types inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
typedef TFunction< void(const FContext &Context)> FCallback
A callback used to perform a task in the update process.
typedef FSkelMeshUpdateContext FContext
Public Types inherited from FRenderAssetUpdate
enum ETaskState {
TS_Done , TS_Suspended , TS_InProgress , TS_Locked ,
TS_Init
}
The state of scheduled work for the update process.
enum EThreadType {
TT_None , TT_Render , TT_Async , TT_GameThread ,
TT_GameRunningAsync
}
A thread type used for doing a part of the update process.
Protected Types inherited from FRenderAssetUpdate
typedef FAutoDeleteAsyncTask< FMipUpdateTask > FAsyncMipUpdateTask
The async task to update this object, only one can be active at anytime.
Protected Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
void ClearCallbacks ()
ETaskState TickInternal (EThreadType InCurrentThread, bool bCheckForSuspension) final override
Protected Member Functions inherited from FRenderAssetUpdate
virtual ~FRenderAssetUpdate ()
void MarkAsCancelled ()
Set the task state as cancelled.
void MarkAsSuccessfullyFinished ()
void ScheduleAsyncTask ()
void ScheduleGTTask ()
void ScheduleRenderTask ()
Protected Attributes inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
FCallback CancelationCallback
The callback handling the cancellation of the update (only if the update gets cancelled).
EThreadType CancelationThread
The thread on which to call the cancellation of the update (only if the update gets cancelled).
FCallback TaskCallback
The callback that will perform the next step of the update.
EThreadType TaskThread
The thread on which to call the next step of the update, being TaskCallback.
Protected Attributes inherited from FRenderAssetUpdate
bool bDeferExecution
Defer execution even if a task pushes a new task on the same thread.
bool bIsCancelled
Whether the task has been cancelled because the update could not proceed or because the user called Abort().
bool bSuccess
Whether this update finished successfully.
FCriticalSection CS
Critical Section.
const int32 CurrentFirstLODIdx = INDEX_NONE
const int32 PendingFirstLODIdx = INDEX_NONE
const FStreamableRenderResourceState ResourceState
The streamable state requested.
int32 ScheduledAsyncTasks
Number of Ticks scheduled on async tasks.
int32 ScheduledGTTasks
Number of Ticks scheduled on the game thread.
int32 ScheduledRenderTasks
Number of Ticks scheduled on the render thread.
const UStreamableRenderAsset * StreamableAsset = nullptr
The asset updated.
volatile ETaskState TaskState
The state of the work yet to be performed to complete the update or cancelation.
FThreadSafeCounter TaskSynchronization
Synchronization used for trigger the task next step execution.
Detailed Description
This class provides a framework for loading and unloading the LODs of skeletal meshes.
Each thread essentially calls Tick() until the job is done. The object can be safely deleted when IsCompleted() returns true.
Definition at line 61 of file SkeletalMeshUpdate.h.
Constructor & Destructor Documentation
FSkeletalMeshUpdate()
FSkeletalMeshUpdate::FSkeletalMeshUpdate (const USkeletalMesh * InMesh)
Definition at line 49 of file SkeletalMeshUpdate.cpp.
References TRenderAssetUpdate< FSkelMeshUpdateContext >::TRenderAssetUpdate().
Referenced by FSkeletalMeshStreamIn::FSkeletalMeshStreamIn(), and FSkeletalMeshStreamOut::FSkeletalMeshStreamOut().
~FSkeletalMeshUpdate()
virtual FSkeletalMeshUpdate::~FSkeletalMeshUpdate () inline virtual
Definition at line 66 of file SkeletalMeshUpdate.h.
Member Function Documentation
Abort()
virtual void FSkeletalMeshUpdate::Abort () inline virtual
Cancel the current update.
Will also attempt to cancel pending IO requests, see FTexture2DStreamIn_IO::Abort(). This is called outside of the update loop when a cancelation is required for external events.
Reimplemented from FRenderAssetUpdate.
Reimplemented in FSkeletalMeshStreamIn_IO.
Definition at line 68 of file SkeletalMeshUpdate.h.
References FRenderAssetUpdate::Abort().
Referenced by FSkeletalMeshStreamIn_IO::Abort(), and FSkeletalMeshStreamOut::ConditionalMarkComponentsDirty().
The documentation for this class was generated from the following files:
Runtime/Engine/Internal/Streaming/SkeletalMeshUpdate.h
Runtime/Engine/Internal/Streaming/SkeletalMeshUpdate.cpp