Unreal Engine 5.6 C++ API: UE::Cook::FCookDependency Class Reference
UE::Cook::FCookDependency Class Reference
TargetDomain dependencies that can be reported from the class instances in a package.
#include "CookDependency.h"
Data Structures
struct FFunctionData
struct FTransitiveBuildData
Public Member Functions
FCookDependency ()
Construct an empty dependency; it will never be invalidated.
FCookDependency (const FCookDependency &Other)
FCookDependency (FCookDependency &&Other)
~FCookDependency ()
const FARFilter * GetARFilter () const
Returns the FARFilter if GetType() == AssetRegistryQuery, else nullptr.
FStringView GetClassPath () const
Returns the classpath if GetType() == NativeClass, else empty string.
UE::ConfigAccessTracking::FConfigAccessData GetConfigAccessData () const
Returns the ConfigAccess in its struct form (File,Section,Key) if GetType() == Config, else empty.
FString GetConfigPath () const
Returns the full path of the config access (e.g.
FStringView GetFileName () const
FileName if GetType() == File, else empty.
FCbFieldViewIterator GetFunctionArgs () const
FunctionArgs if GetType() == Function, else FCbFieldViewIterator().
FName GetFunctionName () const
FunctionName if GetType() == Function, else NAME_None.
FName GetPackageName () const
PackageName if GetType() == TransitiveBuild or GetType() == Package, else NAME_None.
const uint8 * GetRawValue () const
Returns the value of the dependency.
const UObject * GetSettingsObject () const
Returns the SettingsObject pointer if GetType() == SettingsObject, else nullptr.
ECookDependency GetType () const
FCookDependency is a vararg type.
bool operator!= (const FCookDependency &Other) const
bool operator< (const FCookDependency &Other) const
Comparison operator for e.g.
FCookDependency & operator= (const FCookDependency &Other)
FCookDependency & operator= (FCookDependency &&Other)
bool operator== (const FCookDependency &Other) const
Equality operator for uniqueness testing.
void SetValue (const FBlake3Hash &Hash)
void SetValue (const FIoHash &Hash)
void SetValue (const FUtf8String &String)
UE_DEPRECATED (5.6, "Add a TransitiveBuild and a Runtime dependency separately.") 1 static FCookDependency TransitiveBuildAndRuntime(FName PackageName)
UE_DEPRECATED (5.6, "This function is only needed for TransitiveBuildAndRuntime dependencies, which are deprecated.") bool IsAlsoAddRuntimeDependency() const
void UpdateHash (FCookDependencyContext &Context)
Calculate the current hash of this CookDependency, and add it into Context.
Static Public Member Functions
static FCookDependency AssetRegistryQuery (FARFilter Filter)
Adds a dependency on the results reported by an AssetRegistry query.
static FCookDependency Config (FName FileName, FName SectionName, FName ValueName)
Create a dependency on the value of a config variable, with LoadType=ConfigSystem and Platform=NAME_None.
static FCookDependency Config (UE::ConfigAccessTracking::ELoadType LoadType, FName Platform, FName FileName, FName SectionName, FName ValueName)
static FCookDependency Config (UE::ConfigAccessTracking::FConfigAccessData AccessData)
Create a dependency on the value of a config variable.
static FCookDependency ConsoleVariable (FStringView VariableName)
Create a dependency on the value of a cvar.
static FCookDependency File (FStringView InFileName)
Create a dependency on the contents of the file.
static FCookDependency Function (FName InFunctionName, FCbFieldIterator &&InArgs)
Create a dependency on a call to the specified function with the given arguments.
static FCookDependency NativeClass (const UClass *InClass)
Adds a dependency on the class schema of a nativeclass.
static FCookDependency NativeClass (FStringView ClassPath)
static FCookDependency Package (FName PackageName)
Create a build dependency on the contents of a package.
static FCookDependency RedirectionTarget (FName PackageName)
Adds a dependency on the ObjectRedirectors and CoreRedirects that affect the given PackageName.
static FCookDependency SettingsObject (const UObject *InObject)
Adds a dependency on the config values and class schema of a settings object.
static FCookDependency TransitiveBuild (FName PackageName)
Create a transitive build dependency on another package.
Static Public Attributes
static const uint8 ValueSizeInBytes = 32
Private Member Functions
FCookDependency (ECookDependency InType)
void Construct ()
void Destruct ()
bool Load (FCbFieldView Value)
void Save (FCbWriter &Writer) const
Static Private Member Functions
static bool ARFilterEqual (const FARFilter &A, const FARFilter &B)
static bool ARFilterLessThan (const FARFilter &A, const FARFilter &B)
static bool ConfigAccessDataEqual (const UE::ConfigAccessTracking::FConfigAccessData &A, const UE::ConfigAccessTracking::FConfigAccessData &B)
static bool ConfigAccessDataLessThan (const UE::ConfigAccessTracking::FConfigAccessData &A, const UE::ConfigAccessTracking::FConfigAccessData &B)
Private Attributes
union {
FBlake3Hash HashedValue
uint8 RawValue [ValueSizeInBytes]
};
This is the value of the dependency stored as 32 bytes.
union {
TUniquePtr< FARFilter > ARFilter
TUniquePtr< UE::ConfigAccessTracking::FConfigAccessData > ConfigAccessData
FFunctionData FunctionData
FName NameData
const UObject * ObjectPtr
FString StringData
FTransitiveBuildData TransitiveBuildData
};
ECookDependency Type
Friends
bool LoadFromCompactBinary (FCbFieldView Value, FCookDependency &CookDependency)
Public hidden friend for LoadFromCompactBinary.
FCbWriter & operator<< (FCbWriter &Writer, const FCookDependency &CookDependency)
Public hidden friend for operator<< into an FCbWriter.
Detailed Description
TargetDomain dependencies that can be reported from the class instances in a package.
These dependencies are stored in the cook oplog and are evaluated during incremental cook. If any of them changes, the package is invalidated and must be recooked (loaded/saved). These dependencies do not impact whether DDC keys built from the package need to be recalculated.
Definition at line 191 of file CookDependency.h.
Constructor & Destructor Documentation
FCookDependency() [1/4]
UE::Cook::FCookDependency::FCookDependency ()
Construct an empty dependency; it will never be invalidated.
References FCookDependency().
Referenced by FCookDependency(), FCookDependency(), FCookDependency(), FCookDependency(), ~FCookDependency(), AssetRegistryQuery(), Config(), Config(), Config(), ConsoleVariable(), File(), Function(), GetRawValue(), LoadFromCompactBinary, NativeClass(), NativeClass(), operator!=(), operator<(), operator<<, operator=(), operator=(), operator==(), Package(), RedirectionTarget(), SettingsObject(), TransitiveBuild(), and UE_DEPRECATED().
~FCookDependency()
UE::Cook::FCookDependency::~FCookDependency ()
References FCookDependency().
FCookDependency() [2/4]
UE::Cook::FCookDependency::FCookDependency (const FCookDependency & Other)
References FCookDependency(), and Other.
FCookDependency() [3/4]
UE::Cook::FCookDependency::FCookDependency (FCookDependency && Other)
References FCookDependency(), and Other.
FCookDependency() [4/4]
UE::Cook::FCookDependency::FCookDependency (ECookDependency InType) explicit private
References FCookDependency().
Member Function Documentation
ARFilterEqual()
bool UE::Cook::FCookDependency::ARFilterEqual (const FARFilter & A, const FARFilter & B) static private
References A, ARFilterEqual(), and B.
Referenced by ARFilterEqual(), and operator==().
ARFilterLessThan()
bool UE::Cook::FCookDependency::ARFilterLessThan (const FARFilter & A, const FARFilter & B) static private
References A, ARFilterLessThan(), and B.
Referenced by ARFilterLessThan(), and operator<().
AssetRegistryQuery()
FCookDependency UE::Cook::FCookDependency::AssetRegistryQuery (FARFilter Filter) static
Adds a dependency on the results reported by an AssetRegistry query.
References FCookDependency(), AssetRegistryQuery(), and Filter.
Referenced by AssetRegistryQuery().
Config() [1/3]
FCookDependency UE::Cook::FCookDependency::Config (FName FileName, FName SectionName, FName ValueName) static
Create a dependency on the value of a config variable, with LoadType=ConfigSystem and Platform=NAME_None.
References FCookDependency(), and Config().
Config() [2/3]
FCookDependency UE::Cook::FCookDependency::Config (UE::ConfigAccessTracking::ELoadType LoadType, FName Platform, FName FileName, FName SectionName, FName ValueName) static
References FCookDependency(), Config(), and Platform.
Config() [3/3]
FCookDependency UE::Cook::FCookDependency::Config (UE::ConfigAccessTracking::FConfigAccessData AccessData) static
Create a dependency on the value of a config variable.
References FCookDependency(), and Config().
Referenced by Config(), Config(), and Config().
ConfigAccessDataEqual()
bool UE::Cook::FCookDependency::ConfigAccessDataEqual (const UE::ConfigAccessTracking::FConfigAccessData & A, const UE::ConfigAccessTracking::FConfigAccessData & B) static private
References A, B, and ConfigAccessDataEqual().
Referenced by ConfigAccessDataEqual(), and operator==().
ConfigAccessDataLessThan()
bool UE::Cook::FCookDependency::ConfigAccessDataLessThan (const UE::ConfigAccessTracking::FConfigAccessData & A, const UE::ConfigAccessTracking::FConfigAccessData & B) static private
References A, B, and ConfigAccessDataLessThan().
Referenced by ConfigAccessDataLessThan(), and operator<().
ConsoleVariable()
FCookDependency UE::Cook::FCookDependency::ConsoleVariable (FStringView VariableName) static
Create a dependency on the value of a cvar.
The cvar will be read and its value (as a string) will be hashed into the oplog data If the cvar value is changed, the packages that depend on it will be invalidated
References FCookDependency(), and ConsoleVariable().
Referenced by ConsoleVariable(), and UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
Construct()
void UE::Cook::FCookDependency::Construct () private
References Construct().
Referenced by Construct().
Destruct()
void UE::Cook::FCookDependency::Destruct () private
References Destruct().
Referenced by Destruct().
File()
FCookDependency UE::Cook::FCookDependency::File (FStringView InFileName) static
Create a dependency on the contents of the file.
Filename will be normalized. Contents are loaded via IFileManager::Get().CreateFileReader and contents are hashed for comparison.
References FCookDependency().
Function()
FCookDependency UE::Cook::FCookDependency::Function (FName InFunctionName, FCbFieldIterator && InArgs) static
Create a dependency on a call to the specified function with the given arguments.
Arguments should be created using FCbWriter Writer; ... <append arbitrary number of fields to Writer> ...; Writer.Save(). The function should read the arguments using the corresponding FCbFieldIteratorView methods and LoadFromCompactBinary calls.
The function must be registered during editor startup for use with FCookDependency via UE_COOK_DEPENDENCY_FUNCTION(CppTokenUsedAsName, CppNameOfFunctionToCall). The name to pass to FCookDependency::Function can be retrieved via UE_COOK_DEPENDENCY_FUNCTION_CALL(CppTokenUsedAsName).
References FCookDependency().
Referenced by UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
GetARFilter()
const FARFilter * UE::Cook::FCookDependency::GetARFilter () const inline
Returns the FARFilter if GetType() == AssetRegistryQuery, else nullptr.
Definition at line 529 of file CookDependency.h.
References ARFilter, UE::Cook::AssetRegistryQuery, and Type.
Referenced by GetConfigPath().
GetClassPath()
FStringView UE::Cook::FCookDependency::GetClassPath () const inline
Returns the classpath if GetType() == NativeClass, else empty string.
Can also be empty for NativeClass that was found to be invalid.
Definition at line 524 of file CookDependency.h.
References UE::Cook::NativeClass, StringData, and Type.
Referenced by GetConfigPath().
GetConfigAccessData()
UE::ConfigAccessTracking::FConfigAccessData UE::Cook::FCookDependency::GetConfigAccessData () const
Returns the ConfigAccess in its struct form (File,Section,Key) if GetType() == Config, else empty.
References GetConfigAccessData().
Referenced by GetConfigAccessData().
GetConfigPath()
FString UE::Cook::FCookDependency::GetConfigPath () const
Returns the full path of the config access (e.g.
Platform.Filename.Section.ValueName) if GetType() == Config, else empty.
References GetARFilter(), GetClassPath(), GetConfigPath(), and GetSettingsObject().
Referenced by GetConfigPath().
GetFileName()
FStringView UE::Cook::FCookDependency::GetFileName () const inline
FileName if GetType() == File, else empty.
StringView points to null or a null-terminated string.
Definition at line 480 of file CookDependency.h.
References UE::Cook::File, StringData, and Type.
Referenced by operator=().
GetFunctionArgs()
FCbFieldViewIterator UE::Cook::FCookDependency::GetFunctionArgs () const inline
FunctionArgs if GetType() == Function, else FCbFieldViewIterator().
Definition at line 490 of file CookDependency.h.
References UE::Cook::Function, FunctionData, and Type.
Referenced by operator=().
GetFunctionName()
FName UE::Cook::FCookDependency::GetFunctionName () const inline
FunctionName if GetType() == Function, else NAME_None.
Definition at line 485 of file CookDependency.h.
References UE::Cook::Function, FunctionData, and Type.
Referenced by operator=().
GetPackageName()
FName UE::Cook::FCookDependency::GetPackageName () const inline
PackageName if GetType() == TransitiveBuild or GetType() == Package, else NAME_None.
Definition at line 495 of file CookDependency.h.
References GetType(), NameData, UE::Cook::Package, PRAGMA_DISABLE_SWITCH_UNHANDLED_ENUM_CASE_WARNINGS, PRAGMA_RESTORE_SWITCH_UNHANDLED_ENUM_CASE_WARNINGS, UE::Cook::RedirectionTarget, UE::Cook::TransitiveBuild, and TransitiveBuildData.
Referenced by operator=().
GetRawValue()
const uint8 * UE::Cook::FCookDependency::GetRawValue () const
Returns the value of the dependency.
It's an array of size FCookDependency::VALUE_MAX_BYTES_SIZE
References FCookDependency(), GetRawValue(), and Other.
Referenced by GetRawValue().
GetSettingsObject()
const UObject * UE::Cook::FCookDependency::GetSettingsObject () const inline
Returns the SettingsObject pointer if GetType() == SettingsObject, else nullptr.
Can also be null for SettingsObject that was found to be invalid.
Definition at line 519 of file CookDependency.h.
References ObjectPtr, UE::Cook::SettingsObject, and Type.
Referenced by GetConfigPath().
GetType()
ECookDependency UE::Cook::FCookDependency::GetType () const inline
FCookDependency is a vararg type.
Return the type of this instance.
Definition at line 475 of file CookDependency.h.
References Type.
Referenced by GetPackageName(), and operator=().
Load()
bool UE::Cook::FCookDependency::Load (FCbFieldView Value) private
References Load(), and Value.
Referenced by Load(), and LoadFromCompactBinary.
NativeClass() [1/2]
FCookDependency UE::Cook::FCookDependency::NativeClass (const UClass * InClass) static
Adds a dependency on the class schema of a nativeclass.
References FCookDependency(), and NativeClass().
Referenced by NativeClass(), and NativeClass().
NativeClass() [2/2]
FCookDependency UE::Cook::FCookDependency::NativeClass (FStringView ClassPath) static
References FCookDependency(), and NativeClass().
operator!=()
bool UE::Cook::FCookDependency::operator!= (const FCookDependency & Other) const inline
Definition at line 688 of file CookDependency.h.
References FCookDependency(), and Other.
operator<()
bool UE::Cook::FCookDependency::operator< (const FCookDependency & Other) const inline
Comparison operator for e.g.
deterministic ordering of dependencies. Uses persistent comparison data and is somewhat expensive.
Definition at line 534 of file CookDependency.h.
References FCookDependency(), ARFilter, ARFilterLessThan(), UE::Cook::AssetRegistryQuery, checkNoEntry, TMemoryView< DataType >::CompareBytes(), UE::Cook::Config, ConfigAccessData, ConfigAccessDataLessThan(), UE::Cook::ConsoleVariable, UE::Cook::Count, UE::Cook::File, UE::Cook::Function, FunctionData, ESearchCase::IgnoreCase, NameData, UE::Cook::NativeClass, UE::Cook::None, ObjectPtr, Other, UE::Cook::Package, UE::Cook::RedirectionTarget, UE::Cook::SettingsObject, StringData, UE::Cook::TransitiveBuild, TransitiveBuildData, and Type.
operator=() [1/2]
FCookDependency & UE::Cook::FCookDependency::operator= (const FCookDependency & Other)
References FCookDependency(), and Other.
operator=() [2/2]
FCookDependency & UE::Cook::FCookDependency::operator= (FCookDependency && Other)
References FCookDependency(), GetFileName(), GetFunctionArgs(), GetFunctionName(), GetPackageName(), GetType(), and Other.
operator==()
bool UE::Cook::FCookDependency::operator== (const FCookDependency & Other) const inline
Equality operator for uniqueness testing.
Definition at line 610 of file CookDependency.h.
References FCookDependency(), ARFilter, ARFilterEqual(), UE::Cook::AssetRegistryQuery, checkNoEntry, TMemoryView< DataType >::CompareBytes(), UE::Cook::Config, ConfigAccessData, ConfigAccessDataEqual(), UE::Cook::ConsoleVariable, UE::Cook::Count, UE::Cook::File, UE::Cook::Function, FunctionData, ESearchCase::IgnoreCase, NameData, UE::Cook::NativeClass, UE::Cook::None, ObjectPtr, Other, UE::Cook::Package, UE::Cook::RedirectionTarget, UE::Cook::SettingsObject, StringData, UE::Cook::TransitiveBuild, TransitiveBuildData, and Type.
Package()
FCookDependency UE::Cook::FCookDependency::Package (FName PackageName) static
Create a build dependency on the contents of a package.
Only the bytes of the .uasset/.umap file are considered.
References FCookDependency(), Package(), and PackageName.
Referenced by Package(), and UE::SoundWaveLoadingUtil::Private::RecordSoundWaveLoadingBehaviorDependenciesForCook().
RedirectionTarget()
FCookDependency UE::Cook::FCookDependency::RedirectionTarget (FName PackageName) static
Adds a dependency on the ObjectRedirectors and CoreRedirects that affect the given PackageName.
References FCookDependency(), PackageName, and RedirectionTarget().
Referenced by RedirectionTarget().
Save()
void UE::Cook::FCookDependency::Save (FCbWriter & Writer) const private
References Save().
Referenced by Save().
SettingsObject()
FCookDependency UE::Cook::FCookDependency::SettingsObject (const UObject * InObject) static
Adds a dependency on the config values and class schema of a settings object.
Gives an error and ignores the object if the object is not a config-driven settings object, such as the CDO of a config UClass or a perObjectConfig object.
SettingsObject dependencies are not directly persistable; all of the dependencies reported by the SettingsObject are copied onto the dependencies of the package declaring the SettingsObject dependency.
References FCookDependency(), and SettingsObject().
Referenced by SettingsObject().
SetValue() [1/3]
void UE::Cook::FCookDependency::SetValue (const FBlake3Hash & Hash)
References Hash, and SetValue().
SetValue() [2/3]
void UE::Cook::FCookDependency::SetValue (const FIoHash & Hash)
References Hash, and SetValue().
Referenced by SetValue(), SetValue(), and SetValue().
SetValue() [3/3]
void UE::Cook::FCookDependency::SetValue (const FUtf8String & String)
References SetValue().
TransitiveBuild()
FCookDependency UE::Cook::FCookDependency::TransitiveBuild (FName PackageName) static
Create a transitive build dependency on another package.
In an incremental cook if the other package was not cooked in a previous cook session, or its previous cook result was invalidated, the current package will also have its cook result invalidated.
References FCookDependency(), and PackageName.
UE_DEPRECATED() [1/2]
UE::Cook::FCookDependency::UE_DEPRECATED (5. 6, "Add a TransitiveBuild and a Runtime dependency separately.")
References FCookDependency(), and PackageName.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Cook::FCookDependency::UE_DEPRECATED (5. 6, "This function is only needed for TransitiveBuildAndRuntime dependencies, which are deprecated.") const
References UE_DEPRECATED().
UpdateHash()
void UE::Cook::FCookDependency::UpdateHash (FCookDependencyContext & Context)
Calculate the current hash of this CookDependency, and add it into Context.
References UpdateHash().
Referenced by UpdateHash().
Friends And Related Symbol Documentation
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Value, FCookDependency & CookDependency) friend
Public hidden friend for LoadFromCompactBinary.
Definition at line 349 of file CookDependency.h.
References FCookDependency(), Load(), and Value.
operator<<
FCbWriter & operator<< (FCbWriter & Writer, const FCookDependency & CookDependency) friend
Public hidden friend for operator<< into an FCbWriter.
Definition at line 343 of file CookDependency.h.
References FCookDependency(), and FCbWriter::Save().
Field Documentation
[union]
union { ... } UE::Cook::FCookDependency
This is the value of the dependency stored as 32 bytes.
Other types can be added to the union as long as it doesn't go above 32 bytes.
[union]
union { ... } UE::Cook::FCookDependency
ARFilter
TUniquePtr<FARFilter> UE::Cook::FCookDependency::ARFilter
Definition at line 374 of file CookDependency.h.
Referenced by GetARFilter(), operator<(), and operator==().
ConfigAccessData
TUniquePtr<UE::ConfigAccessTracking::FConfigAccessData> UE::Cook::FCookDependency::ConfigAccessData
Definition at line 373 of file CookDependency.h.
Referenced by operator<(), and operator==().
FunctionData
FFunctionData UE::Cook::FCookDependency::FunctionData
Definition at line 369 of file CookDependency.h.
Referenced by GetFunctionArgs(), GetFunctionName(), operator<(), and operator==().
HashedValue
FBlake3Hash UE::Cook::FCookDependency::HashedValue
Definition at line 384 of file CookDependency.h.
NameData
FName UE::Cook::FCookDependency::NameData
Definition at line 371 of file CookDependency.h.
Referenced by GetPackageName(), operator<(), and operator==().
ObjectPtr
const UObject* UE::Cook::FCookDependency::ObjectPtr
Definition at line 372 of file CookDependency.h.
Referenced by GetSettingsObject(), operator<(), and operator==().
RawValue
uint8 UE::Cook::FCookDependency::RawValue[ValueSizeInBytes]
Definition at line 383 of file CookDependency.h.
StringData
FString UE::Cook::FCookDependency::StringData
Definition at line 368 of file CookDependency.h.
Referenced by GetClassPath(), GetFileName(), operator<(), and operator==().
TransitiveBuildData
FTransitiveBuildData UE::Cook::FCookDependency::TransitiveBuildData
Definition at line 370 of file CookDependency.h.
Referenced by GetPackageName(), operator<(), and operator==().
Type
ECookDependency UE::Cook::FCookDependency::Type private
Definition at line 355 of file CookDependency.h.
Referenced by GetARFilter(), GetClassPath(), GetFileName(), GetFunctionArgs(), GetFunctionName(), GetSettingsObject(), GetType(), operator<(), and operator==().
ValueSizeInBytes
const uint8 UE::Cook::FCookDependency::ValueSizeInBytes = 32 static
Definition at line 327 of file CookDependency.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Cooker/CookDependency.h