Unreal Engine 5.6 C++ API: FComponentInstanceDataCache Class Reference
FComponentInstanceDataCache Class Reference
Base class for component instance cached data of a particular type.
#include "ComponentInstanceDataCache.h"
Public Member Functions
FComponentInstanceDataCache ()=default
FComponentInstanceDataCache (const AActor *InActor)
Constructor that also populates cache from Actor.
FComponentInstanceDataCache (const FComponentInstanceDataCache &)=delete
Non-copyable.
FComponentInstanceDataCache (FComponentInstanceDataCache &&)=default
Movable.
~FComponentInstanceDataCache ()=default
void AddReferencedObjects (FReferenceCollector &Collector)
void ApplyToActor (AActor *Actor, const ECacheApplyPhase CacheApplyPhase) const
Iterates over an Actor's components and applies the stored component instance data to each.
void FindAndReplaceInstances (const TMap< UObject *, UObject * > &OldToNewInstanceMap)
Iterates over components and replaces any object references with the reinstanced information.
bool HasInstanceData () const
FComponentInstanceDataCache & operator= (const FComponentInstanceDataCache &)=delete
FComponentInstanceDataCache & operator= (FComponentInstanceDataCache &&)=default
void Serialize (FArchive &Ar)
Serialize Instance data for persistence or transmission.
Static Public Member Functions
static void GetComponentHierarchy (const AActor *Actor, TArray< UActorComponent *, TInlineAllocator< NumInlinedActorComponents > > &OutComponentHierarchy)
Private Member Functions
void CopySerializableProperties (TArray< TStructOnScope< FActorComponentInstanceData > > InComponentsInstanceData)
Private Attributes
TArray< TStructOnScope< FActorComponentInstanceData > > ComponentsInstanceData
Map of component instance data struct (template -> instance data)
TMap< TObjectPtr< USceneComponent >, FTransform > InstanceComponentTransformToRootMap
Map of the actor instanced scene component to their transform relative to the root.
Detailed Description
Base class for component instance cached data of a particular type.
Per instance data to be persisted for a given actor Cache for component instance data. Note, does not collect references for GC, so is not safe to GC if the cache is only reference to a UObject.
Definition at line 216 of file ComponentInstanceDataCache.h.
Constructor & Destructor Documentation
FComponentInstanceDataCache() [1/4]
FComponentInstanceDataCache::FComponentInstanceDataCache () default
Referenced by FComponentInstanceDataCache(), FComponentInstanceDataCache(), operator=(), and operator=().
FComponentInstanceDataCache() [2/4]
FComponentInstanceDataCache::FComponentInstanceDataCache (const AActor * InActor)
Constructor that also populates cache from Actor.
~FComponentInstanceDataCache()
FComponentInstanceDataCache::~FComponentInstanceDataCache () default
FComponentInstanceDataCache() [3/4]
FComponentInstanceDataCache::FComponentInstanceDataCache (const FComponentInstanceDataCache &) delete
Non-copyable.
References FComponentInstanceDataCache().
FComponentInstanceDataCache() [4/4]
FComponentInstanceDataCache::FComponentInstanceDataCache (FComponentInstanceDataCache &&) default
Movable.
References FComponentInstanceDataCache().
Member Function Documentation
AddReferencedObjects()
void FComponentInstanceDataCache::AddReferencedObjects (FReferenceCollector & Collector)
ApplyToActor()
void FComponentInstanceDataCache::ApplyToActor (AActor * Actor, const ECacheApplyPhase CacheApplyPhase) const
Iterates over an Actor's components and applies the stored component instance data to each.
References Actor.
CopySerializableProperties()
void FComponentInstanceDataCache::CopySerializableProperties (TArray< TStructOnScope< FActorComponentInstanceData > > InComponentsInstanceData) private
FindAndReplaceInstances()
void FComponentInstanceDataCache::FindAndReplaceInstances (const TMap< UObject *, UObject * > & OldToNewInstanceMap)
Iterates over components and replaces any object references with the reinstanced information.
GetComponentHierarchy()
void FComponentInstanceDataCache::GetComponentHierarchy (const AActor * Actor, TArray< UActorComponent *, TInlineAllocator< NumInlinedActorComponents > > & OutComponentHierarchy) static
References Actor.
HasInstanceData()
bool FComponentInstanceDataCache::HasInstanceData () const inline
Definition at line 244 of file ComponentInstanceDataCache.h.
References ComponentsInstanceData.
operator=() [1/2]
FComponentInstanceDataCache & FComponentInstanceDataCache::operator= (const FComponentInstanceDataCache &) delete
References FComponentInstanceDataCache().
operator=() [2/2]
FComponentInstanceDataCache & FComponentInstanceDataCache::operator= (FComponentInstanceDataCache &&) default
References FComponentInstanceDataCache().
Serialize()
void FComponentInstanceDataCache::Serialize (FArchive & Ar)
Serialize Instance data for persistence or transmission.
References Ar.
Field Documentation
ComponentsInstanceData
TArray<TStructOnScope<FActorComponentInstanceData> > FComponentInstanceDataCache::ComponentsInstanceData private
Map of component instance data struct (template -> instance data)
Definition at line 255 of file ComponentInstanceDataCache.h.
Referenced by HasInstanceData().
InstanceComponentTransformToRootMap
TMap< TObjectPtr<USceneComponent>, FTransform > FComponentInstanceDataCache::InstanceComponentTransformToRootMap private
Map of the actor instanced scene component to their transform relative to the root.
Definition at line 258 of file ComponentInstanceDataCache.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ComponentInstanceDataCache.h