Unreal Engine 5.6 C++ API: FDisplayClusterFillDerivedDataCacheWorker Class Reference
FDisplayClusterFillDerivedDataCacheWorker Class Reference
#include "DisplayClusterFillDerivedDataCacheWorker.h"
Public Member Functions
FDisplayClusterFillDerivedDataCacheWorker ()
virtual ~FDisplayClusterFillDerivedDataCacheWorker () override
void CancelTask ()
void CompleteCommandletAndShowNotification ()
virtual FSingleThreadRunnable * GetSingleThreadInterface () override
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
virtual uint32 Run () override
Runs the runnable object.
virtual void Stop () override
Stops the runnable object.
virtual void Tick () override
Public Member Functions inherited from FRunnable
virtual ~FRunnable ()
Virtual destructor.
virtual void Exit ()
Exits the runnable object.
virtual bool Init ()
Initializes the runnable object.
Public Member Functions inherited from FSingleThreadRunnable
virtual ~FSingleThreadRunnable ()
Protected Member Functions
FString GetDdcCommandletParams () const
FString GetLastWholeLogBlock (const FString &LogString)
FString GetTargetPlatformParams () const
void ReadCommandletOutputAndUpdateEditorNotification ()
void RegexParseForCompilationProgress (const FString &LogString)
void RegexParseForEnumerationCount (const FString &LogString)
void RegexParseForLoadingProgress (const FString &LogString)
Protected Attributes
TUniquePtr< FAsyncTaskNotification > ProgressNotification
Progress notification.
Private Attributes
FString Arguments
int32 AssetsWaitingToCompile = INDEX_NONE
bool bWasCancelled = false
int32 CompileTotal = INDEX_NONE
FString CurrentExecutableName
FString LastPartialLogLine
int32 LoadingTotal = INDEX_NONE
FProcHandle ProcessHandle
void * ReadPipe = nullptr
int32 ResultCode = 0
TUniquePtr< FRunnableThread > Thread
void * WritePipe = nullptr
Detailed Description
Definition at line 16 of file DisplayClusterFillDerivedDataCacheWorker.h.
Constructor & Destructor Documentation
FDisplayClusterFillDerivedDataCacheWorker()
FDisplayClusterFillDerivedDataCacheWorker::FDisplayClusterFillDerivedDataCacheWorker ()
~FDisplayClusterFillDerivedDataCacheWorker()
virtual FDisplayClusterFillDerivedDataCacheWorker::~FDisplayClusterFillDerivedDataCacheWorker () override virtual
Member Function Documentation
CancelTask()
void FDisplayClusterFillDerivedDataCacheWorker::CancelTask ()
Referenced by Stop().
CompleteCommandletAndShowNotification()
void FDisplayClusterFillDerivedDataCacheWorker::CompleteCommandletAndShowNotification ()
GetDdcCommandletParams()
FString FDisplayClusterFillDerivedDataCacheWorker::GetDdcCommandletParams () const protected
GetLastWholeLogBlock()
FString FDisplayClusterFillDerivedDataCacheWorker::GetLastWholeLogBlock (const FString & LogString) protected
GetSingleThreadInterface()
virtual FSingleThreadRunnable * FDisplayClusterFillDerivedDataCacheWorker::GetSingleThreadInterface () inline override virtual
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
If the interface is not implemented, this runnable will not be ticked when FPlatformProcess::SupportsMultithreading() is false.
Returns
Pointer to the single thread interface or nullptr if not implemented.
Reimplemented from FRunnable.
Definition at line 41 of file DisplayClusterFillDerivedDataCacheWorker.h.
GetTargetPlatformParams()
FString FDisplayClusterFillDerivedDataCacheWorker::GetTargetPlatformParams () const protected
ReadCommandletOutputAndUpdateEditorNotification()
void FDisplayClusterFillDerivedDataCacheWorker::ReadCommandletOutputAndUpdateEditorNotification () protected
Referenced by Run(), and Tick().
RegexParseForCompilationProgress()
void FDisplayClusterFillDerivedDataCacheWorker::RegexParseForCompilationProgress (const FString & LogString) protected
RegexParseForEnumerationCount()
void FDisplayClusterFillDerivedDataCacheWorker::RegexParseForEnumerationCount (const FString & LogString) protected
RegexParseForLoadingProgress()
void FDisplayClusterFillDerivedDataCacheWorker::RegexParseForLoadingProgress (const FString & LogString) protected
Run()
virtual uint32 FDisplayClusterFillDerivedDataCacheWorker::Run () inline override virtual
Runs the runnable object.
This is where all per object thread work is done. This is only called if the initialization was successful.
Returns
The exit code of the runnable object
See also
Init, Stop, Exit
Implements FRunnable.
Definition at line 25 of file DisplayClusterFillDerivedDataCacheWorker.h.
References ReadCommandletOutputAndUpdateEditorNotification().
Stop()
virtual void FDisplayClusterFillDerivedDataCacheWorker::Stop () inline override virtual
Stops the runnable object.
This is called if a thread is requested to terminate early.
See also
Init, Run, Exit
Reimplemented from FRunnable.
Definition at line 30 of file DisplayClusterFillDerivedDataCacheWorker.h.
References CancelTask().
Tick()
virtual void FDisplayClusterFillDerivedDataCacheWorker::Tick () inline override virtual
Implements FSingleThreadRunnable.
Definition at line 37 of file DisplayClusterFillDerivedDataCacheWorker.h.
References ReadCommandletOutputAndUpdateEditorNotification().
Field Documentation
Arguments
FString FDisplayClusterFillDerivedDataCacheWorker::Arguments private
Definition at line 84 of file DisplayClusterFillDerivedDataCacheWorker.h.
AssetsWaitingToCompile
int32 FDisplayClusterFillDerivedDataCacheWorker::AssetsWaitingToCompile = INDEX_NONE private
Definition at line 81 of file DisplayClusterFillDerivedDataCacheWorker.h.
bWasCancelled
bool FDisplayClusterFillDerivedDataCacheWorker::bWasCancelled = false private
Definition at line 71 of file DisplayClusterFillDerivedDataCacheWorker.h.
CompileTotal
int32 FDisplayClusterFillDerivedDataCacheWorker::CompileTotal = INDEX_NONE private
Definition at line 80 of file DisplayClusterFillDerivedDataCacheWorker.h.
CurrentExecutableName
FString FDisplayClusterFillDerivedDataCacheWorker::CurrentExecutableName private
Definition at line 83 of file DisplayClusterFillDerivedDataCacheWorker.h.
LastPartialLogLine
FString FDisplayClusterFillDerivedDataCacheWorker::LastPartialLogLine private
Definition at line 77 of file DisplayClusterFillDerivedDataCacheWorker.h.
LoadingTotal
int32 FDisplayClusterFillDerivedDataCacheWorker::LoadingTotal = INDEX_NONE private
Definition at line 79 of file DisplayClusterFillDerivedDataCacheWorker.h.
ProcessHandle
FProcHandle FDisplayClusterFillDerivedDataCacheWorker::ProcessHandle private
Definition at line 72 of file DisplayClusterFillDerivedDataCacheWorker.h.
ProgressNotification
TUniquePtr<FAsyncTaskNotification> FDisplayClusterFillDerivedDataCacheWorker::ProgressNotification protected
Progress notification.
Definition at line 64 of file DisplayClusterFillDerivedDataCacheWorker.h.
ReadPipe
void* FDisplayClusterFillDerivedDataCacheWorker::ReadPipe = nullptr private
Definition at line 74 of file DisplayClusterFillDerivedDataCacheWorker.h.
ResultCode
int32 FDisplayClusterFillDerivedDataCacheWorker::ResultCode = 0 private
Definition at line 70 of file DisplayClusterFillDerivedDataCacheWorker.h.
Thread
TUniquePtr<FRunnableThread> FDisplayClusterFillDerivedDataCacheWorker::Thread private
Definition at line 68 of file DisplayClusterFillDerivedDataCacheWorker.h.
WritePipe
void* FDisplayClusterFillDerivedDataCacheWorker::WritePipe = nullptr private
Definition at line 75 of file DisplayClusterFillDerivedDataCacheWorker.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterFillDerivedDataCache/Public/DisplayClusterFillDerivedDataCacheWorker.h