Unreal Engine 5.6 C++ API: FCompilerResultsLog Class Reference
FCompilerResultsLog Class Reference
This class represents a log of compiler output lines (errors, warnings, and information notes), each of which can be a rich tokenized message.
#include "CompilerResultsLog.h"
Data Structures
struct FCompilerEvent
Public Member Functions
UNREALED_API FCompilerResultsLog (bool bIsCompatibleWithEvents=true)
virtual UNREALED_API ~FCompilerResultsLog ()
void AddTokenizedMessage (TSharedRef< FTokenizedMessage > InMessage)
Store an already tokenized message.
UNREALED_API void Append (FCompilerResultsLog const &Other, bool bWriteToSystemLog=false)
Copy errors from an existing log into this one, and optionally write out to log if it was suppressed the first time.
UNREALED_API void BeginEvent (const TCHAR *InName)
Begin a new compiler event.
UNREALED_API int32 CalculateStableIdentifierForLatentActionManager (const UEdGraphNode *Node)
Returns a int32 used to uniquely identify an action for the latent action manager.
UNREALED_API bool CommitPotentialMessages (UEdGraphNode *Source)
Commit all stored potential messages for a given node.
UNREALED_API void EndEvent ()
End the current compiler event.
template<typename... ArgTypes>
TSharedRef< FTokenizedMessage > Error (const TCHAR *Format, ArgTypes... Args)
Write an error in to the compiler log.
UNREALED_API UObject * FindSourceMacroInstance (const UEdGraphNode *IntermediateNode) const
UNREALED_API UObject * FindSourceObject (UObject *PossiblyDuplicatedObject)
Returns the true source object for the passed in object.
UNREALED_API UObject const * FindSourceObject (UObject const *PossiblyDuplicatedObject) const
template<typename T>
T * FindSourceObjectTypeChecked (UObject *PossiblyDuplicatedObject)
Returns the true source object for the passed in object; does type checking on the result.
template<typename T>
T const * FindSourceObjectTypeChecked (UObject const *PossiblyDuplicatedObject) const
UNREALED_API const UEdGraphPin * FindSourcePin (const UEdGraphPin *PossiblyDuplicatedPin) const
UNREALED_API UEdGraphPin * FindSourcePin (UEdGraphPin *PossiblyDuplicatedPin)
UNREALED_API const UEdGraphNode * GetIntermediateTunnelInstance (const UEdGraphNode *IntermediateNode) const
Returns the intermediate tunnel instance that generated the node.
template<typename... ArgTypes>
TSharedRef< FTokenizedMessage > Note (const TCHAR *Format, ArgTypes... Args)
Write a note in to the compiler log.
UNREALED_API void NotifyIntermediateMacroNode (UEdGraphNode *SourceNode, const UEdGraphNode *IntermediateNode)
Update the map that tracks nodes created by macro instance nodes.
UNREALED_API void NotifyIntermediateObjectCreation (UObject *NewObject, UObject *SourceObject)
Update the source backtrack map to note that NewObject was most closely generated/caused by the SourceObject.
UNREALED_API void NotifyIntermediatePinCreation (UEdGraphPin *NewObject, UEdGraphPin *SourceObject)
UNREALED_API void NotifyIntermediateTunnelNode (const UEdGraphNode *Node, const UEdGraphNode *OuterTunnelInstance)
Update the expansion map to note that Node was expanded from OuterTunnelInstance, both the node and tunnel instance should be intermediate nodes.
UNREALED_API void SetSilentMode (bool bValue)
ICompilerResultsLog implementation.
void SetSourcePath (const FString &InSourcePath)
Set the source name for the final log summary.
template<typename... ArgTypes>
TSharedRef< FTokenizedMessage > StorePotentialError (const UEdGraphNode *Source, const TCHAR *Format, ArgTypes... Args)
Store a potential error for a given node in the compiler log.
template<typename... ArgTypes>
TSharedRef< FTokenizedMessage > StorePotentialNote (const UEdGraphNode *Source, const TCHAR *Format, ArgTypes... Args)
Store a potential note for a given node in the compiler log.
template<typename... ArgTypes>
TSharedRef< FTokenizedMessage > StorePotentialWarning (const UEdGraphNode *Source, const TCHAR *Format, ArgTypes... Args)
Store a potential warning for a given node in the compiler log.
UE_DEPRECATED (5.4, "BP-specific perf tracking has been removed, use Insights") static FCompilerResultsLog *GetEventTarget()
template<typename... ArgTypes>
TSharedRef< FTokenizedMessage > Warning (const TCHAR *Format, ArgTypes... Args)
Write a warning in to the compiler log.
template<typename... ArgTypes>
void Warning (FName ID, const TCHAR *Format, ArgTypes... Args)
Write a warning in to the compiler log.
Static Public Member Functions
static UNREALED_API TSharedRef< IMessageLogListing > GetBlueprintMessageLog (UBlueprint *InBlueprint)
Get the message log listing for this blueprint.
static FName GetLogName ()
Accessor for the LogName, so it can be opened elsewhere.
static UNREALED_API void Register ()
Register this log with the MessageLog module.
static UNREALED_API void Unregister ()
Unregister this log from the MessageLog module.
Data Fields
TSet< TWeakObjectPtr< UEdGraphNode > > AnnotatedNodes
Tracks nodes that produced errors/warnings.
bool bAnnotateMentionedNodes
bool bLogDetailedResults
bool bLogInfoOnly
bool bSilentMode
int EventDisplayThresholdMs
TArray< TSharedRef< FTokenizedMessage > > Messages
int32 NumErrors
int32 NumWarnings
Protected Member Functions
UNREALED_API void AddChildEvent (TSharedPtr< FCompilerEvent > &ParentEventScope, TSharedRef< FCompilerEvent > &ChildEventScope)
Helper method to add a child event to the given parent event scope.
UNREALED_API void AnnotateNode (const TArray< UEdGraphNode * > &Nodes, TSharedRef< FTokenizedMessage > LogLine)
Links the UEdGraphNode with the LogLine:
UNREALED_API void FEdGraphToken_Create (const FField *InField, FTokenizedMessage &OutMessage, TArray< UEdGraphNode * > &OutSourceNodes)
UNREALED_API void FEdGraphToken_Create (const TCHAR *String, FTokenizedMessage &OutMessage, TArray< UEdGraphNode * > &OutSourceNodes)
UNREALED_API void FEdGraphToken_Create (const UEdGraphPin *InPin, FTokenizedMessage &OutMessage, TArray< UEdGraphNode * > &OutSourceNodes)
UNREALED_API void FEdGraphToken_Create (const UObject *InObject, FTokenizedMessage &OutMessage, TArray< UEdGraphNode * > &OutSourceNodes)
void IncrementErrorCount ()
void IncrementWarningCount ()
UNREALED_API void InternalLogEvent (const FCompilerEvent &InEvent, int32 InDepth=0)
Internal helper method to recursively append event details into the MessageLog.
template<typename... ArgTypes>
void InternalLogMessage (FName MessageID, const TCHAR *Format, const TSharedRef< FTokenizedMessage > &Message, ArgTypes... Args)
UNREALED_API void InternalLogMessage (FName MessageID, const TSharedRef< FTokenizedMessage > &Message, const TArray< UEdGraphNode * > &SourceNodes)
UNREALED_API void InternalLogSummary ()
Internal method to append the final compiler results summary to the MessageLog.
UNREALED_API bool IsMessageEnabled (FName ID)
template<typename T, typename... ArgTypes>
void Tokenize (const TCHAR *Format, FTokenizedMessage &OutMessage, TArray< UEdGraphNode * > &OutSourceNode, T First, ArgTypes... Rest)
void Tokenize (const TCHAR *Text, FTokenizedMessage &OutMessage, TArray< UEdGraphNode * > &OutSourceNode)
Protected Attributes
TMap< TWeakObjectPtr< const UEdGraphNode >, TWeakObjectPtr< UEdGraphNode > > FullMacroBacktrackMap
TMap< TWeakObjectPtr< const UEdGraphNode >, TWeakObjectPtr< const UEdGraphNode > > IntermediateTunnelNodeToTunnelInstanceMap
FBacktrackMap SourceBacktrackMap
FString SourcePath
Static Private Member Functions
static UNREALED_API void GetGlobalModuleCompilerDump (const FString &LogDump, ECompilationResult::Type CompilationResult, bool bShowLog)
Callback function for binding the global compiler dump to open the static compiler log.
static UNREALED_API void GetNodesFromTokens (const TArray< TSharedRef< IMessageToken > > &MessageTokens, TArray< UEdGraphNode * > &OutOwnerNodes)
Searches a token list for referenced UEdGraphNodes, used to update the nodes when a log is committed.
static UNREALED_API void OnGotoError (const class TSharedRef< IMessageToken > &Token)
Goes to an error given a Message Token.
static UNREALED_API TArray< TSharedRef< FTokenizedMessage > > ParseCompilerLogDump (const FString &LogDump)
Parses a compiler log dump to generate tokenized output.
Private Attributes
TSharedPtr< FCompilerEvent > CurrentEventScope
TMap< FObjectKey, TArray< TSharedRef< FTokenizedMessage > > > PotentialMessages
Map of stored potential messages indexed by a node.
Static Private Attributes
static UNREALED_API FDelegateHandle GetGlobalModuleCompilerDumpDelegateHandle
Handle to the registered GetGlobalModuleCompilerDump delegate.
static UNREALED_API const FName Name
The log's name, for easy re-use.
Detailed Description
This class represents a log of compiler output lines (errors, warnings, and information notes), each of which can be a rich tokenized message.
Definition at line 68 of file CompilerResultsLog.h.
Constructor & Destructor Documentation
FCompilerResultsLog()
UNREALED_API FCompilerResultsLog::FCompilerResultsLog (bool bIsCompatibleWithEvents = true)
Referenced by Append(), and UE_DEPRECATED().
~FCompilerResultsLog()
virtual UNREALED_API FCompilerResultsLog::~FCompilerResultsLog () virtual
Member Function Documentation
AddChildEvent()
UNREALED_API void FCompilerResultsLog::AddChildEvent (TSharedPtr< FCompilerEvent > & ParentEventScope, TSharedRef< FCompilerEvent > & ChildEventScope) protected
Helper method to add a child event to the given parent event scope.
AddTokenizedMessage()
void FCompilerResultsLog::AddTokenizedMessage (TSharedRef< FTokenizedMessage > InMessage) inline
Store an already tokenized message.
Definition at line 265 of file CompilerResultsLog.h.
References EMessageSeverity::Error, Messages, NumErrors, NumWarnings, EMessageSeverity::PerformanceWarning, and EMessageSeverity::Warning.
AnnotateNode()
UNREALED_API void FCompilerResultsLog::AnnotateNode (const TArray< UEdGraphNode * > & Nodes, TSharedRef< FTokenizedMessage > LogLine) protected
Links the UEdGraphNode with the LogLine:
Append()
UNREALED_API void FCompilerResultsLog::Append (FCompilerResultsLog const & Other, bool bWriteToSystemLog = false)
Copy errors from an existing log into this one, and optionally write out to log if it was suppressed the first time.
References FCompilerResultsLog(), and Other.
BeginEvent()
UNREALED_API void FCompilerResultsLog::BeginEvent (const TCHAR * InName)
Begin a new compiler event.
References InName.
CalculateStableIdentifierForLatentActionManager()
UNREALED_API int32 FCompilerResultsLog::CalculateStableIdentifierForLatentActionManager (const UEdGraphNode * Node)
Returns a int32 used to uniquely identify an action for the latent action manager.
CommitPotentialMessages()
UNREALED_API bool FCompilerResultsLog::CommitPotentialMessages (UEdGraphNode * Source)
Commit all stored potential messages for a given node.
Returns true if any messages were written.
References Source.
EndEvent()
UNREALED_API void FCompilerResultsLog::EndEvent ()
End the current compiler event.
Error()
template<typename... ArgTypes> TSharedRef< FTokenizedMessage > FCompilerResultsLog::Error (const TCHAR * Format, ArgTypes... Args) inline
Write an error in to the compiler log.
Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 169 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), EMessageSeverity::Error, Format, InternalLogMessage(), Line, and NumErrors.
FEdGraphToken_Create() [1/4]
UNREALED_API void FCompilerResultsLog::FEdGraphToken_Create (const FField * InField, FTokenizedMessage & OutMessage, TArray< UEdGraphNode * > & OutSourceNodes) protected
FEdGraphToken_Create() [2/4]
UNREALED_API void FCompilerResultsLog::FEdGraphToken_Create (const TCHAR * String, FTokenizedMessage & OutMessage, TArray< UEdGraphNode * > & OutSourceNodes) protected
References String.
FEdGraphToken_Create() [3/4]
UNREALED_API void FCompilerResultsLog::FEdGraphToken_Create (const UEdGraphPin * InPin, FTokenizedMessage & OutMessage, TArray< UEdGraphNode * > & OutSourceNodes) protected
FEdGraphToken_Create() [4/4]
UNREALED_API void FCompilerResultsLog::FEdGraphToken_Create (const UObject * InObject, FTokenizedMessage & OutMessage, TArray< UEdGraphNode * > & OutSourceNodes) protected
FindSourceMacroInstance()
UNREALED_API UObject * FCompilerResultsLog::FindSourceMacroInstance (const UEdGraphNode * IntermediateNode) const
FindSourceObject() [1/2]
UNREALED_API UObject * FCompilerResultsLog::FindSourceObject (UObject * PossiblyDuplicatedObject)
Returns the true source object for the passed in object.
Referenced by FindSourceObjectTypeChecked(), and FindSourceObjectTypeChecked().
FindSourceObject() [2/2]
UNREALED_API UObject const * FCompilerResultsLog::FindSourceObject (UObject const * PossiblyDuplicatedObject) const
FindSourceObjectTypeChecked() [1/2]
template<typename T> T * FCompilerResultsLog::FindSourceObjectTypeChecked (UObject * PossiblyDuplicatedObject) inline
Returns the true source object for the passed in object; does type checking on the result.
Definition at line 309 of file CompilerResultsLog.h.
References CastChecked(), and FindSourceObject().
FindSourceObjectTypeChecked() [2/2]
template<typename T> T const * FCompilerResultsLog::FindSourceObjectTypeChecked (UObject const * PossiblyDuplicatedObject) const inline
Definition at line 315 of file CompilerResultsLog.h.
References CastChecked(), and FindSourceObject().
FindSourcePin() [1/2]
UNREALED_API const UEdGraphPin * FCompilerResultsLog::FindSourcePin (const UEdGraphPin * PossiblyDuplicatedPin) const
FindSourcePin() [2/2]
UNREALED_API UEdGraphPin * FCompilerResultsLog::FindSourcePin (UEdGraphPin * PossiblyDuplicatedPin)
GetBlueprintMessageLog()
UNREALED_API TSharedRef< IMessageLogListing > FCompilerResultsLog::GetBlueprintMessageLog (UBlueprint * InBlueprint) static
Get the message log listing for this blueprint.
GetGlobalModuleCompilerDump()
UNREALED_API void FCompilerResultsLog::GetGlobalModuleCompilerDump (const FString & LogDump, ECompilationResult::Type CompilationResult, bool bShowLog) static private
Callback function for binding the global compiler dump to open the static compiler log.
GetIntermediateTunnelInstance()
UNREALED_API const UEdGraphNode * FCompilerResultsLog::GetIntermediateTunnelInstance (const UEdGraphNode * IntermediateNode) const
Returns the intermediate tunnel instance that generated the node.
GetLogName()
FName FCompilerResultsLog::GetLogName () inline static
Accessor for the LogName, so it can be opened elsewhere.
Definition at line 156 of file CompilerResultsLog.h.
References Name.
GetNodesFromTokens()
UNREALED_API void FCompilerResultsLog::GetNodesFromTokens (const TArray< TSharedRef< IMessageToken > > & MessageTokens, TArray< UEdGraphNode * > & OutOwnerNodes) static private
Searches a token list for referenced UEdGraphNodes, used to update the nodes when a log is committed.
IncrementErrorCount()
void FCompilerResultsLog::IncrementErrorCount () inline protected
Definition at line 399 of file CompilerResultsLog.h.
References NumErrors.
IncrementWarningCount()
void FCompilerResultsLog::IncrementWarningCount () inline protected
Definition at line 400 of file CompilerResultsLog.h.
References NumWarnings.
InternalLogEvent()
UNREALED_API void FCompilerResultsLog::InternalLogEvent (const FCompilerEvent & InEvent, int32 InDepth = 0) protected
Internal helper method to recursively append event details into the MessageLog.
InternalLogMessage() [1/2]
template<typename... ArgTypes> void FCompilerResultsLog::InternalLogMessage (FName MessageID, const TCHAR * Format, const TSharedRef< FTokenizedMessage > & Message, ArgTypes... Args) inline protected
Definition at line 375 of file CompilerResultsLog.h.
References Format, InternalLogMessage(), and Tokenize().
Referenced by Error(), InternalLogMessage(), Note(), Warning(), and Warning().
InternalLogMessage() [2/2]
UNREALED_API void FCompilerResultsLog::InternalLogMessage (FName MessageID, const TSharedRef< FTokenizedMessage > & Message, const TArray< UEdGraphNode * > & SourceNodes) protected
InternalLogSummary()
UNREALED_API void FCompilerResultsLog::InternalLogSummary () protected
Internal method to append the final compiler results summary to the MessageLog.
IsMessageEnabled()
UNREALED_API bool FCompilerResultsLog::IsMessageEnabled (FName ID) protected
References ID.
Referenced by Warning().
Note()
template<typename... ArgTypes> TSharedRef< FTokenizedMessage > FCompilerResultsLog::Note (const TCHAR * Format, ArgTypes... Args) inline
Write a note in to the compiler log.
Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 213 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), Format, EMessageSeverity::Info, InternalLogMessage(), and Line.
NotifyIntermediateMacroNode()
UNREALED_API void FCompilerResultsLog::NotifyIntermediateMacroNode (UEdGraphNode * SourceNode, const UEdGraphNode * IntermediateNode)
Update the map that tracks nodes created by macro instance nodes.
NotifyIntermediateObjectCreation()
UNREALED_API void FCompilerResultsLog::NotifyIntermediateObjectCreation (UObject * NewObject, UObject * SourceObject)
Update the source backtrack map to note that NewObject was most closely generated/caused by the SourceObject.
References NewObject().
NotifyIntermediatePinCreation()
UNREALED_API void FCompilerResultsLog::NotifyIntermediatePinCreation (UEdGraphPin * NewObject, UEdGraphPin * SourceObject)
References NewObject().
NotifyIntermediateTunnelNode()
UNREALED_API void FCompilerResultsLog::NotifyIntermediateTunnelNode (const UEdGraphNode * Node, const UEdGraphNode * OuterTunnelInstance)
Update the expansion map to note that Node was expanded from OuterTunnelInstance, both the node and tunnel instance should be intermediate nodes.
OnGotoError()
UNREALED_API void FCompilerResultsLog::OnGotoError (const class TSharedRef< IMessageToken > & Token) static private
Goes to an error given a Message Token.
ParseCompilerLogDump()
UNREALED_API TArray< TSharedRef< FTokenizedMessage > > FCompilerResultsLog::ParseCompilerLogDump (const FString & LogDump) static private
Parses a compiler log dump to generate tokenized output.
Register()
UNREALED_API void FCompilerResultsLog::Register () static
Register this log with the MessageLog module.
SetSilentMode()
UNREALED_API void FCompilerResultsLog::SetSilentMode (bool bValue) inline
ICompilerResultsLog implementation.
Definition at line 342 of file CompilerResultsLog.h.
References bSilentMode.
SetSourcePath()
void FCompilerResultsLog::SetSourcePath (const FString & InSourcePath) inline
Set the source name for the final log summary.
Definition at line 159 of file CompilerResultsLog.h.
References SourcePath.
StorePotentialError()
template<typename... ArgTypes> TSharedRef< FTokenizedMessage > FCompilerResultsLog::StorePotentialError (const UEdGraphNode * Source, const TCHAR * Format, ArgTypes... Args) inline
Store a potential error for a given node in the compiler log.
All messages for the node can be committed to the log later by calling CommitPotentialMessages Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 225 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), EMessageSeverity::Error, Format, Line, PotentialMessages, Source, and Tokenize().
StorePotentialNote()
template<typename... ArgTypes> TSharedRef< FTokenizedMessage > FCompilerResultsLog::StorePotentialNote (const UEdGraphNode * Source, const TCHAR * Format, ArgTypes... Args) inline
Store a potential note for a given node in the compiler log.
All messages for the node can be committed to the log later by calling CommitPotentialMessages Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 253 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), Format, EMessageSeverity::Info, Line, PotentialMessages, Source, and Tokenize().
StorePotentialWarning()
template<typename... ArgTypes> TSharedRef< FTokenizedMessage > FCompilerResultsLog::StorePotentialWarning (const UEdGraphNode * Source, const TCHAR * Format, ArgTypes... Args) inline
Store a potential warning for a given node in the compiler log.
All messages for the node can be committed to the log later by calling CommitPotentialMessages Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 239 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), Format, Line, PotentialMessages, Source, Tokenize(), and EMessageSeverity::Warning.
Tokenize() [1/2]
template<typename T, typename... ArgTypes> void FCompilerResultsLog::Tokenize (const TCHAR * Format, FTokenizedMessage & OutMessage, TArray< UEdGraphNode * > & OutSourceNode, T First, ArgTypes... Rest) inline protected
Definition at line 353 of file CompilerResultsLog.h.
References FTokenizedMessage::AddToken(), FEdGraphToken::Create(), FTextToken::Create(), First, Format, FText::FromString(), TCString< TCHAR >::Strlen(), TCString< TCHAR >::Strstr(), TEXT, Tokenize(), and UE_PTRDIFF_TO_INT32.
Tokenize() [2/2]
void FCompilerResultsLog::Tokenize (const TCHAR * Text, FTokenizedMessage & OutMessage, TArray< UEdGraphNode * > & OutSourceNode) inline protected
Definition at line 347 of file CompilerResultsLog.h.
References FTokenizedMessage::AddToken(), FTextToken::Create(), FText::FromString(), and Text.
Referenced by InternalLogMessage(), StorePotentialError(), StorePotentialNote(), StorePotentialWarning(), and Tokenize().
UE_DEPRECATED()
FCompilerResultsLog::UE_DEPRECATED (5. 4, "BP-specific perf tracking has been removed, use Insights") inline
Definition at line 332 of file CompilerResultsLog.h.
References FCompilerResultsLog().
Unregister()
UNREALED_API void FCompilerResultsLog::Unregister () static
Unregister this log from the MessageLog module.
Warning() [1/2]
template<typename... ArgTypes> TSharedRef< FTokenizedMessage > FCompilerResultsLog::Warning (const TCHAR * Format, ArgTypes... Args) inline
Write a warning in to the compiler log.
Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 182 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), Format, InternalLogMessage(), Line, NumWarnings, and EMessageSeverity::Warning.
Warning() [2/2]
template<typename... ArgTypes> void FCompilerResultsLog::Warning (FName ID, const TCHAR * Format, ArgTypes... Args) inline
Write a warning in to the compiler log.
Note: @ will be replaced by node or pin links for nodes/pins passed via varargs
Definition at line 195 of file CompilerResultsLog.h.
References FTokenizedMessage::Create(), Format, ID, InternalLogMessage(), IsMessageEnabled(), Line, NumWarnings, and EMessageSeverity::Warning.
Field Documentation
AnnotatedNodes
TSet< TWeakObjectPtr<UEdGraphNode> > FCompilerResultsLog::AnnotatedNodes
Tracks nodes that produced errors/warnings.
Definition at line 130 of file CompilerResultsLog.h.
bAnnotateMentionedNodes
bool FCompilerResultsLog::bAnnotateMentionedNodes
Definition at line 121 of file CompilerResultsLog.h.
bLogDetailedResults
bool FCompilerResultsLog::bLogDetailedResults
Definition at line 124 of file CompilerResultsLog.h.
bLogInfoOnly
bool FCompilerResultsLog::bLogInfoOnly
Definition at line 118 of file CompilerResultsLog.h.
bSilentMode
bool FCompilerResultsLog::bSilentMode
Definition at line 115 of file CompilerResultsLog.h.
Referenced by SetSilentMode().
CurrentEventScope
TSharedPtr<FCompilerEvent> FCompilerResultsLog::CurrentEventScope private
Definition at line 102 of file CompilerResultsLog.h.
EventDisplayThresholdMs
int FCompilerResultsLog::EventDisplayThresholdMs
Definition at line 127 of file CompilerResultsLog.h.
FullMacroBacktrackMap
TMap<TWeakObjectPtr<const UEdGraphNode>, TWeakObjectPtr<UEdGraphNode> > FCompilerResultsLog::FullMacroBacktrackMap protected
Definition at line 143 of file CompilerResultsLog.h.
GetGlobalModuleCompilerDumpDelegateHandle
UNREALED_API FDelegateHandle FCompilerResultsLog::GetGlobalModuleCompilerDumpDelegateHandle static private
Handle to the registered GetGlobalModuleCompilerDump delegate.
Definition at line 424 of file CompilerResultsLog.h.
IntermediateTunnelNodeToTunnelInstanceMap
TMap<TWeakObjectPtr<const UEdGraphNode>, TWeakObjectPtr<const UEdGraphNode> > FCompilerResultsLog::IntermediateTunnelNodeToTunnelInstanceMap protected
Definition at line 140 of file CompilerResultsLog.h.
Messages
TArray< TSharedRef<FTokenizedMessage> > FCompilerResultsLog::Messages
Definition at line 106 of file CompilerResultsLog.h.
Referenced by AddTokenizedMessage().
Name
UNREALED_API const FName FCompilerResultsLog::Name static private
The log's name, for easy re-use.
Definition at line 421 of file CompilerResultsLog.h.
Referenced by GetLogName().
NumErrors
int32 FCompilerResultsLog::NumErrors
Definition at line 109 of file CompilerResultsLog.h.
Referenced by AddTokenizedMessage(), Error(), and IncrementErrorCount().
NumWarnings
int32 FCompilerResultsLog::NumWarnings
Definition at line 112 of file CompilerResultsLog.h.
Referenced by AddTokenizedMessage(), IncrementWarningCount(), Warning(), and Warning().
PotentialMessages
TMap< FObjectKey, TArray< TSharedRef<FTokenizedMessage> > > FCompilerResultsLog::PotentialMessages private
Map of stored potential messages indexed by a node.
Can be committed to the results log by calling CommitPotentialMessages for that node.
Definition at line 406 of file CompilerResultsLog.h.
Referenced by StorePotentialError(), StorePotentialNote(), and StorePotentialWarning().
SourceBacktrackMap
FBacktrackMap FCompilerResultsLog::SourceBacktrackMap protected
Definition at line 134 of file CompilerResultsLog.h.
SourcePath
FString FCompilerResultsLog::SourcePath protected
Definition at line 137 of file CompilerResultsLog.h.
Referenced by SetSourcePath().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Kismet2/CompilerResultsLog.h