Unreal Engine 5.6 C++ API: FQuatFixed32NoW Class Reference
FQuatFixed32NoW Class Reference
#include "AnimationCompression.h"
Public Member Functions
FQuatFixed32NoW ()
FQuatFixed32NoW (const FQuat4f &Quat)
void FromQuat (const FQuat4f &Quat)
void ToQuat (FQuat4f &Out) const
Static Public Member Functions
template<bool bIsDataAligned>
static FQuat4f ToQuat (const uint32 *PackedValue)
Data Fields
uint32 Packed
Friends
FArchive & operator<< (FArchive &Ar, FQuatFixed32NoW &Quat)
Detailed Description
Definition at line 150 of file AnimationCompression.h.
Constructor & Destructor Documentation
FQuatFixed32NoW() [1/2]
FQuatFixed32NoW::FQuatFixed32NoW () inline
Definition at line 155 of file AnimationCompression.h.
Referenced by operator<<.
FQuatFixed32NoW() [2/2]
FQuatFixed32NoW::FQuatFixed32NoW (const FQuat4f & Quat) inline explicit
Definition at line 158 of file AnimationCompression.h.
References FromQuat(), and Quat.
Member Function Documentation
FromQuat()
void FQuatFixed32NoW::FromQuat (const FQuat4f & Quat) inline
Definition at line 163 of file AnimationCompression.h.
References UE::Math::TQuat< T >::Normalize(), Packed, Quant10BitFactor, Quant10BitOffs, Quant11BitFactor, Quant11BitOffs, Quat, UE::Math::TQuat< T >::W, UE::Math::TQuat< T >::X, UE::Math::TQuat< T >::Y, and UE::Math::TQuat< T >::Z.
Referenced by FQuatFixed32NoW().
ToQuat() [1/2]
template<bool bIsDataAligned> FQuat4f FQuatFixed32NoW::ToQuat (const uint32 * PackedValue) inline static
Definition at line 186 of file AnimationCompression.h.
References Packed, Quant10BitDiv, Quant10BitOffs, Quant11BitDiv, Quant11BitOffs, AnimationCompressionUtils::UnalignedRead(), X, Y, and Z.
Referenced by DecompressRotation(), FAnimationCompression_PerTrackUtils::DecompressRotation(), and ToQuat().
ToQuat() [2/2]
void FQuatFixed32NoW::ToQuat (FQuat4f & Out) const inline
Definition at line 207 of file AnimationCompression.h.
References Packed, and ToQuat().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FQuatFixed32NoW & Quat) friend
Definition at line 212 of file AnimationCompression.h.
References FQuatFixed32NoW(), Ar, and Quat.
Field Documentation
Packed
uint32 FQuatFixed32NoW::Packed
Definition at line 153 of file AnimationCompression.h.
Referenced by FromQuat(), ToQuat(), and ToQuat().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AnimationCompression.h