Unreal Engine 5.6 C++ API: IModularFeatures Class Reference
IModularFeatures Class Reference abstract
Public interface to all known modular features.
#include "IModularFeatures.h"
Data Structures
struct FScopedLockModularFeatureList
Public Member Functions
virtual ~IModularFeatures ()
Virtual destructor, to make polymorphism happy.
DECLARE_EVENT_TwoParams (IModularFeatures, FOnModularFeatureRegistered, const FName &, class IModularFeature *)
Event used to inform clients that a modular feature has been registered.
DECLARE_EVENT_TwoParams (IModularFeatures, FOnModularFeatureUnregistered, const FName &, class IModularFeature *)
Event used to inform clients that a modular feature has been unregistered.
template<typename TModularFeature>
TModularFeature & GetModularFeature (const FName Type)
Queries for a specific feature.
virtual class IModularFeature * GetModularFeatureImplementation (const FName Type, const int32 Index)=0
Queries for a specific modular feature.
virtual int32 GetModularFeatureImplementationCount (const FName Type)=0
Returns the number of registered implementations of the specified feature type.
template<typename TModularFeature>
TArray< TModularFeature * > GetModularFeatureImplementations (const FName Type)
Queries for one or more implementations of a single feature.
bool IsModularFeatureAvailable (const FName Type)
Checks to see if the specified feature is available.
virtual void LockModularFeatureList ()=0
Lock modular features for access from another thread.
virtual FOnModularFeatureRegistered & OnModularFeatureRegistered ()=0
virtual FOnModularFeatureUnregistered & OnModularFeatureUnregistered ()=0
virtual void RegisterModularFeature (const FName Type, class IModularFeature *ModularFeature)=0
Registers a feature.
virtual void UnlockModularFeatureList ()=0
Unlock modular features when finished accessing from another thread.
virtual void UnregisterModularFeature (const FName Type, class IModularFeature *ModularFeature)=0
Unregisters a feature that was registered earlier on.
Static Public Member Functions
static IModularFeatures & Get ()
Static: Access singleton instance.
Detailed Description
Public interface to all known modular features.
Definition at line 14 of file IModularFeatures.h.
Constructor & Destructor Documentation
~IModularFeatures()
virtual IModularFeatures::~IModularFeatures () inline virtual
Virtual destructor, to make polymorphism happy.
Definition at line 27 of file IModularFeatures.h.
Member Function Documentation
DECLARE_EVENT_TwoParams() [1/2]
IModularFeatures::DECLARE_EVENT_TwoParams (IModularFeatures , FOnModularFeatureRegistered , const FName & , class IModularFeature *)
Event used to inform clients that a modular feature has been registered.
Parameters
Type The name of the modular feature type being registered.
DECLARE_EVENT_TwoParams() [2/2]
IModularFeatures::DECLARE_EVENT_TwoParams (IModularFeatures , FOnModularFeatureUnregistered , const FName & , class IModularFeature *)
Event used to inform clients that a modular feature has been unregistered.
Parameters
Type The name of the modular feature type being unregistered.
Get()
IModularFeatures & IModularFeatures::Get () static
Static: Access singleton instance.
Returns
Reference to the singleton object
Referenced by IModularFeatures::FScopedLockModularFeatureList::FScopedLockModularFeatureList(), IModularFeatures::FScopedLockModularFeatureList::~FScopedLockModularFeatureList(), IInputDebuggingInterface::Get(), IRenderCaptureProvider::Get(), ISoundHandleSystem::GetRegisteredInterfaces(), IInputDebuggingInterface::IsAvailable(), IRenderCaptureProvider::IsAvailable(), and ICameraPhotographyModule::StartupModule().
GetModularFeature()
template<typename TModularFeature> TModularFeature & IModularFeatures::GetModularFeature (const FName Type) inline
Queries for a specific feature.
If multiple implementations of the same feature were registered, this will return the first. Will assert or crash if the specified feature is not available! You should call IsModularFeatureAvailable() first!
Parameters
Type The type of feature we're looking for
Returns
The feature.
Definition at line 54 of file IModularFeatures.h.
References GetModularFeatureImplementation().
Referenced by IInputDebuggingInterface::Get(), and IRenderCaptureProvider::Get().
GetModularFeatureImplementation()
virtual class IModularFeature * IModularFeatures::GetModularFeatureImplementation (const FName Type, const int32 Index) pure virtual
Queries for a specific modular feature.
Returns NULL if the feature is not available. Does not assert. Usually you should just call GetModularFeature instead, after calling IsModularFeatureAvailable().
Parameters
Type The type of feature we're looking for
Index The index of the implementation (there may be multiple implementations of the same feature registered.)
Returns
Pointer to the feature interface, or NULL if it's not available right now.
Referenced by GetModularFeature(), and GetModularFeatureImplementations().
GetModularFeatureImplementationCount()
virtual int32 IModularFeatures::GetModularFeatureImplementationCount (const FName Type) pure virtual
Returns the number of registered implementations of the specified feature type.
Parameters
Type The type of feature we're looking for
Returns
Number of implementations of this feature.
Referenced by GetModularFeatureImplementations(), and IsModularFeatureAvailable().
GetModularFeatureImplementations()
template<typename TModularFeature> TArray< TModularFeature * > IModularFeatures::GetModularFeatureImplementations (const FName Type) inline
Queries for one or more implementations of a single feature.
If no feature of this type is registered, will return an empty array.
Parameters
Type The type of feature we're looking for
Returns
List of available implementations of this feature.
Definition at line 68 of file IModularFeatures.h.
References TArray< InElementType, InAllocatorType >::Add(), GetModularFeatureImplementation(), and GetModularFeatureImplementationCount().
Referenced by ISoundHandleSystem::GetRegisteredInterfaces().
IsModularFeatureAvailable()
bool IModularFeatures::IsModularFeatureAvailable (const FName Type) inline
Checks to see if the specified feature is available.
Parameters
Type The type of feature we're looking for
Returns
True if the feature is available right now and it is safe to call GetModularFeature()
Definition at line 39 of file IModularFeatures.h.
References GetModularFeatureImplementationCount().
Referenced by IInputDebuggingInterface::IsAvailable(), and IRenderCaptureProvider::IsAvailable().
LockModularFeatureList()
virtual void IModularFeatures::LockModularFeatureList () pure virtual
Lock modular features for access from another thread.
Referenced by IModularFeatures::FScopedLockModularFeatureList::FScopedLockModularFeatureList(), and ISoundHandleSystem::GetRegisteredInterfaces().
OnModularFeatureRegistered()
virtual FOnModularFeatureRegistered & IModularFeatures::OnModularFeatureRegistered () pure virtual
OnModularFeatureUnregistered()
virtual FOnModularFeatureUnregistered & IModularFeatures::OnModularFeatureUnregistered () pure virtual
RegisterModularFeature()
virtual void IModularFeatures::RegisterModularFeature (const FName Type, class IModularFeature * ModularFeature) pure virtual
Registers a feature.
Usually called by plugins to augment or replace existing modular features.
Parameters
Type The type of feature we're registering
ModularFeature Interface to the modular feature object. We do not assume ownership of this object. It's up to you to keep it allocated until it is unregistered later on.
Referenced by ICameraPhotographyModule::StartupModule().
UnlockModularFeatureList()
virtual void IModularFeatures::UnlockModularFeatureList () pure virtual
Unlock modular features when finished accessing from another thread.
Referenced by IModularFeatures::FScopedLockModularFeatureList::~FScopedLockModularFeatureList(), and ISoundHandleSystem::GetRegisteredInterfaces().
UnregisterModularFeature()
virtual void IModularFeatures::UnregisterModularFeature (const FName Type, class IModularFeature * ModularFeature) pure virtual
Unregisters a feature that was registered earlier on.
After unregistering a feature, other systems will no longer be able to gain access to it through this interface.
Parameters
Type The type of feature we're unregistering
ModularFeature Interface to the modular feature object
The documentation for this class was generated from the following file:
Runtime/Core/Public/Features/IModularFeatures.h