Unreal Engine 5.6 C++ API: IPixelStreaming2EditorModule Class Reference
IPixelStreaming2EditorModule Class Reference abstract
Public interface that manages Pixel Streaming specific functionality within the Unreal Editor.
#include "IPixelStreaming2EditorModule.h"
Public Member Functions
virtual bool GetServeHttps ()=0
Get the bool indicating if frontend content is being served over HTTPS for the inbuilt c++ signalling server.
virtual FString GetSignallingDomain ()=0
Get the domain for the inbuilt c++ signalling server.
virtual TSharedPtr< UE::PixelStreaming2Servers::IServer > GetSignallingServer ()=0
Get the inbuilt C++ signalling server.
virtual FString GetSSLCertificatePath ()=0
Get the path to file containing the SSL certificate.
virtual FString GetSSLPrivateKeyPath ()=0
Get the path to file containing the SSL private key.
virtual int32 GetStreamerPort ()=0
Get the port streamers connect to for the inbuilt c++ signalling server.
virtual int32 GetViewerPort ()=0
Get the port viewers connect to for the inbuilt c++ signalling server.
virtual void SetServeHttps (bool bServeHttps)=0
Set whether frontend content should be served of HTTPS for the inbuilt c++ signalling server.
virtual void SetSignallingDomain (const FString &InSignallingDomain)=0
Set the domain for the inbuilt c++ signalling server.
virtual void SetSSLCertificatePath (const FString &Path)=0
Set the path to file containing the SSL certificate.
virtual void SetSSLPrivateKeyPath (const FString &Path)=0
Set the path to file containing the SSL private key.
virtual void SetStreamerPort (int32 InStreamerPort)=0
Set the port streamers connect to for the inbuilt c++ signalling server.
virtual void SetViewerPort (int32 InViewerPort)=0
Set the port viewers connect to for the inbuilt c++ signalling server.
virtual void StartSignalling ()=0
Start the inbuilt C++ signalling server.
virtual void StartStreaming (EPixelStreaming2EditorStreamTypes InStreamType)=0
Starts the editor specific streamer.
virtual void StopSignalling ()=0
Stop the inbuilt C++ signalling server.
virtual void StopStreaming ()=0
Starts the editor specific streamer.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IPixelStreaming2EditorModule & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Detailed Description
Public interface that manages Pixel Streaming specific functionality within the Unreal Editor.
Provides various features for controlling Pixel Streaming, such as starting and stopping the streamer.
Definition at line 15 of file IPixelStreaming2EditorModule.h.
Member Function Documentation
Get()
IPixelStreaming2EditorModule & IPixelStreaming2EditorModule::Get () inline static
Singleton-like access to this module's interface.
Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 24 of file IPixelStreaming2EditorModule.h.
References FModuleManager::LoadModuleChecked().
GetServeHttps()
virtual bool IPixelStreaming2EditorModule::GetServeHttps () pure virtual
Get the bool indicating if frontend content is being served over HTTPS for the inbuilt c++ signalling server.
Returns
bool true if frontend content is being served over https, else false.
GetSignallingDomain()
virtual FString IPixelStreaming2EditorModule::GetSignallingDomain () pure virtual
Get the domain for the inbuilt c++ signalling server.
Returns
FString The inbuilt c++ signalling server's domain
GetSignallingServer()
virtual TSharedPtr< UE::PixelStreaming2Servers::IServer > IPixelStreaming2EditorModule::GetSignallingServer () pure virtual
Get the inbuilt C++ signalling server.
Returns
TSharedPtr<UE::PixelStreaming2Servers::IServer> The signalling server
GetSSLCertificatePath()
virtual FString IPixelStreaming2EditorModule::GetSSLCertificatePath () pure virtual
Get the path to file containing the SSL certificate.
Returns
FString The path to file containing the SSL certificate.
GetSSLPrivateKeyPath()
virtual FString IPixelStreaming2EditorModule::GetSSLPrivateKeyPath () pure virtual
Get the path to file containing the SSL private key.
Returns
FString The path to file containing the SSL private key.
GetStreamerPort()
virtual int32 IPixelStreaming2EditorModule::GetStreamerPort () pure virtual
Get the port streamers connect to for the inbuilt c++ signalling server.
Returns
int32 The inbuilt c++ signalling server's port for streamers connect to
GetViewerPort()
virtual int32 IPixelStreaming2EditorModule::GetViewerPort () pure virtual
Get the port viewers connect to for the inbuilt c++ signalling server.
Returns
int32 The inbuilt c++ signalling server's port for viewers connect to
IsAvailable()
bool IPixelStreaming2EditorModule::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 34 of file IPixelStreaming2EditorModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
SetServeHttps()
virtual void IPixelStreaming2EditorModule::SetServeHttps (bool bServeHttps) pure virtual
Set whether frontend content should be served of HTTPS for the inbuilt c++ signalling server.
Parameters
bServeHttps
SetSignallingDomain()
virtual void IPixelStreaming2EditorModule::SetSignallingDomain (const FString & InSignallingDomain) pure virtual
Set the domain for the inbuilt c++ signalling server.
Parameters
InSignallingDomain The domain for the inbuilt c++ signalling server
SetSSLCertificatePath()
virtual void IPixelStreaming2EditorModule::SetSSLCertificatePath (const FString & Path) pure virtual
Set the path to file containing the SSL certificate.
Required if frontend content is being served of HTTPS for the inbuilt c++ signalling server
Parameters
Path The path to file containing the SSL certificate.
References Path.
SetSSLPrivateKeyPath()
virtual void IPixelStreaming2EditorModule::SetSSLPrivateKeyPath (const FString & Path) pure virtual
Set the path to file containing the SSL private key.
Required if frontend content is being served of HTTPS for the inbuilt c++ signalling server
Parameters
Path The path to file containing the SSL private key.
References Path.
SetStreamerPort()
virtual void IPixelStreaming2EditorModule::SetStreamerPort (int32 InStreamerPort) pure virtual
Set the port streamers connect to for the inbuilt c++ signalling server.
Parameters
InStreamerPort The port streamers connect to for the inbuilt c++ signalling server
SetViewerPort()
virtual void IPixelStreaming2EditorModule::SetViewerPort (int32 InViewerPort) pure virtual
Set the port viewers connect to for the inbuilt c++ signalling server.
Parameters
InViewerPort The port viewers connect to for the inbuilt c++ signalling server
StartSignalling()
virtual void IPixelStreaming2EditorModule::StartSignalling () pure virtual
Start the inbuilt C++ signalling server.
StartStreaming()
virtual void IPixelStreaming2EditorModule::StartStreaming (EPixelStreaming2EditorStreamTypes InStreamType) pure virtual
Starts the editor specific streamer.
Parameters
InStreamType The stream type for this streamer.
StopSignalling()
virtual void IPixelStreaming2EditorModule::StopSignalling () pure virtual
Stop the inbuilt C++ signalling server.
StopStreaming()
virtual void IPixelStreaming2EditorModule::StopStreaming () pure virtual
Starts the editor specific streamer.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2Editor/Public/IPixelStreaming2EditorModule.h