Unreal Engine 5.6 C++ API: FWorldPartitionHelpers Class Reference
FWorldPartitionHelpers Class Reference
#include "WorldPartitionHelpers.h"
Data Structures
struct FForEachActorWithLoadingParams
struct FForEachActorWithLoadingResult
struct TDeprecated
Public Member Functions
UE_DEPRECATED (5.4, "Use ForEachActorWithLoading with FWorldPartitionActorDescInstance") static void ForEachActorWithLoading(UWorldPartition *WorldPartition
UE_DEPRECATED (5.4, "Use ForEachIntersectingActorDescInstance") static void ForEachIntersectingActorDesc(UWorldPartition *WorldPartition
UE_DEPRECATED (5.4, "Use UAssetRegistryHelpers::FixupRedirectedAssetPath instead.") static 1 bool FixupRedirectedAssetPath(FName &InOutAssetPath)
UE_DEPRECATED (5.4, "Use UAssetRegistryHelpers::FixupRedirectedAssetPath instead.") static 1 bool FixupRedirectedAssetPath(FSoftObjectPath &InOutSoftObjectPath)
Static Public Member Functions
static bool ConvertEditorPathToRuntimePath (const FSoftObjectPath &InPath, FSoftObjectPath &OutPath)
static bool ConvertRuntimePathToEditorPath (const FSoftObjectPath &InPath, FSoftObjectPath &OutPath)
static void DoCollectGarbage ()
static void FakeEngineTick (UWorld *World)
template<class ActorClass = AActor>
static void ForEachActorDesc (UWorldPartition *WorldPartition, TFunctionRef< bool(const FWorldPartitionActorDesc *)> Func)
static void ForEachActorDescInstance (UWorldPartition *WorldPartition, TSubclassOf< AActor > ActorClass, TFunctionRef< bool(const FWorldPartitionActorDescInstance *)> Func)
static void ForEachActorWithLoading (UWorldPartition *WorldPartition, TFunctionRef< bool(const FWorldPartitionActorDescInstance *)> Func, const FForEachActorWithLoadingParams &Params, FForEachActorWithLoadingResult &Result)
template<class ActorClass = AActor>
static void ForEachIntersectingActorDesc (UWorldPartition *WorldPartition, const FBox &Box, TFunctionRef< bool(const FWorldPartitionActorDesc *)> Func)
static TMap< FGuid, AActor * > GetLoadedActorsForLevel (const ULevel *InLevel)
static TMap< FGuid, AActor * > GetRegisteredActorsForLevel (const ULevel *InLevel)
template<class T>
static UWorldPartition * GetWorldPartition (const T *InObject)
Returns the owning World Partition for this object.
static bool HasExceededMaxMemory ()
static void ServerExecConsoleCommand (UWorld *InWorld, const FString &InConsoleCommandName, const TArray< FString > &InArgs)
Sends an RPC console command to the server (non shipping builds only).
static bool ShouldCollectGarbage ()
Data Fields
const FBox TSubclassOf< AActor > ActorClass
const FBox & Box
const FBox TSubclassOf< AActor > TFunctionRef< bool(const FWorldPartitionActorDesc *)> Func
TFunctionRef< bool(const FWorldPartitionActorDesc *)> Func
TFunctionRef< bool(const FWorldPartitionActorDesc *)> const FForEachActorWithLoadingParams & Params
Static Private Member Functions
static bool IsActorDescClassCompatibleWith (const FWorldPartitionActorDesc *ActorDesc, const UClass *Class)
Detailed Description
Definition at line 63 of file WorldPartitionHelpers.h.
Member Function Documentation
ConvertEditorPathToRuntimePath()
bool FWorldPartitionHelpers::ConvertEditorPathToRuntimePath (const FSoftObjectPath & InPath, FSoftObjectPath & OutPath) static
ConvertRuntimePathToEditorPath()
bool FWorldPartitionHelpers::ConvertRuntimePathToEditorPath (const FSoftObjectPath & InPath, FSoftObjectPath & OutPath) static
DoCollectGarbage()
void FWorldPartitionHelpers::DoCollectGarbage () static
FakeEngineTick()
void FWorldPartitionHelpers::FakeEngineTick (UWorld * World) static
ForEachActorDesc()
template<class ActorClass = AActor> void FWorldPartitionHelpers::ForEachActorDesc (UWorldPartition * WorldPartition, TFunctionRef< bool(const FWorldPartitionActorDesc *)> Func) inline static
Definition at line 98 of file WorldPartitionHelpers.h.
References Func.
ForEachActorDescInstance()
void FWorldPartitionHelpers::ForEachActorDescInstance (UWorldPartition * WorldPartition, TSubclassOf< AActor > ActorClass, TFunctionRef< bool(const FWorldPartitionActorDescInstance *)> Func) static
References ActorClass, and Func.
ForEachActorWithLoading()
void FWorldPartitionHelpers::ForEachActorWithLoading (UWorldPartition * WorldPartition, TFunctionRef< bool(const FWorldPartitionActorDescInstance *)> Func, const FForEachActorWithLoadingParams & Params, FForEachActorWithLoadingResult & Result) static
References Func, and Params.
ForEachIntersectingActorDesc()
template<class ActorClass = AActor> void FWorldPartitionHelpers::ForEachIntersectingActorDesc (UWorldPartition * WorldPartition, const FBox & Box, TFunctionRef< bool(const FWorldPartitionActorDesc *)> Func) inline static
Definition at line 92 of file WorldPartitionHelpers.h.
References Box, and Func.
GetLoadedActorsForLevel()
TMap< FGuid, AActor * > FWorldPartitionHelpers::GetLoadedActorsForLevel (const ULevel * InLevel) static
References GetLoadedActorsForLevel().
Referenced by GetLoadedActorsForLevel().
GetRegisteredActorsForLevel()
TMap< FGuid, AActor * > FWorldPartitionHelpers::GetRegisteredActorsForLevel (const ULevel * InLevel) static
References GetRegisteredActorsForLevel().
Referenced by GetRegisteredActorsForLevel().
GetWorldPartition()
template<class T> UWorldPartition * FWorldPartitionHelpers::GetWorldPartition (const T * InObject) inline static
Returns the owning World Partition for this object.
Definition at line 68 of file WorldPartitionHelpers.h.
References FWorldPartitionHelpersPrivate::GetWorldPartition().
HasExceededMaxMemory()
bool FWorldPartitionHelpers::HasExceededMaxMemory () static
IsActorDescClassCompatibleWith()
bool FWorldPartitionHelpers::IsActorDescClassCompatibleWith (const FWorldPartitionActorDesc * ActorDesc, const UClass * Class) static private
References Class.
ServerExecConsoleCommand()
void FWorldPartitionHelpers::ServerExecConsoleCommand (UWorld * InWorld, const FString & InConsoleCommandName, const TArray< FString > & InArgs) static
Sends an RPC console command to the server (non shipping builds only).
ShouldCollectGarbage()
bool FWorldPartitionHelpers::ShouldCollectGarbage () static
UE_DEPRECATED() [1/4]
FWorldPartitionHelpers::UE_DEPRECATED (5. 4, "Use ForEachActorWithLoading with FWorldPartitionActorDescInstance")
UE_DEPRECATED() [2/4]
FWorldPartitionHelpers::UE_DEPRECATED (5. 4, "Use ForEachIntersectingActorDescInstance")
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FWorldPartitionHelpers::UE_DEPRECATED (5. 4, "Use UAssetRegistryHelpers::FixupRedirectedAssetPath instead.") &
UE_DEPRECATED() [4/4]
FWorldPartitionHelpers::UE_DEPRECATED (5. 4, "Use UAssetRegistryHelpers::FixupRedirectedAssetPath instead.") &
References UE_DEPRECATED().
Field Documentation
ActorClass
const FBox TSubclassOf<AActor> FWorldPartitionHelpers::ActorClass
Definition at line 104 of file WorldPartitionHelpers.h.
Referenced by ForEachActorDescInstance().
Box
const FBox& FWorldPartitionHelpers::Box
Definition at line 104 of file WorldPartitionHelpers.h.
Referenced by ForEachIntersectingActorDesc().
Func [1/2]
const FBox TSubclassOf<AActor> TFunctionRef<bool(const FWorldPartitionActorDesc*)> FWorldPartitionHelpers::Func
Initial value:
{}
    UE_DEPRECATED(5.4, "Use ForEachActorDescInstance")
    static void ForEachActorDesc(UWorldPartition* WorldPartition, TSubclassOf<AActor> ActorClass, TFunctionRef<bool(const FWorldPartitionActorDesc*)> Func) {}
    template <class ActorClass = AActor>
    static void ForEachIntersectingActorDescInstance(UWorldPartition* WorldPartition, const FBox& Box, TFunctionRef<bool(const FWorldPartitionActorDescInstance*)> Func)
    {
        ForEachIntersectingActorDescInstance(WorldPartition, Box, ActorClass::StaticClass(), Func);
    }
    template<class ActorClass = AActor>
    static void ForEachActorDescInstance(UWorldPartition* WorldPartition, TFunctionRef<bool(const FWorldPartitionActorDescInstance*)> Func)
    {
        ForEachActorDescInstance(WorldPartition, ActorClass::StaticClass(), Func);
    }
    static 1 void ForEachIntersectingActorDescInstance(UWorldPartition* WorldPartition, const FBox& Box, TSubclassOf<AActor> ActorClass, TFunctionRef<bool(const FWorldPartitionActorDescInstance*)> Func)
Definition at line 104 of file WorldPartitionHelpers.h.
Referenced by ForEachActorDesc(), ForEachActorDescInstance(), ForEachActorWithLoading(), and ForEachIntersectingActorDesc().
Func [2/2]
TFunctionRef<bool(const FWorldPartitionActorDesc*)> FWorldPartitionHelpers::Func
Definition at line 156 of file WorldPartitionHelpers.h.
Params
TFunctionRef<bool(const FWorldPartitionActorDesc*)> const FForEachActorWithLoadingParams& FWorldPartitionHelpers::Params
Initial value:
= FForEachActorWithLoadingParams()) {}
    UE_DEPRECATED(5.4, "Use ForEachActorWithLoading with FWorldPartitionActorDescInstance")
    static void ForEachActorWithLoading(UWorldPartition* WorldPartition, TFunctionRef<bool(const FWorldPartitionActorDesc*)> Func, const FForEachActorWithLoadingParams& Params, FForEachActorWithLoadingResult& Result) {}
    static 1 void ForEachActorWithLoading(UWorldPartition* WorldPartition, TFunctionRef<bool(const FWorldPartitionActorDescInstance*)> Func, const FForEachActorWithLoadingParams& Params = FForEachActorWithLoadingParams())
Definition at line 156 of file WorldPartitionHelpers.h.
Referenced by ForEachActorWithLoading().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionHelpers.h