Unreal Engine 5.6 C++ API: FLogScopedVerbosityOverride Class Reference
FLogScopedVerbosityOverride Class Reference
Helper class that allows setting scoped verbosity for log category.
#include "LogScopedVerbosityOverride.h"
Public Member Functions
FLogScopedVerbosityOverride (const FLogScopedVerbosityOverride &)=delete
FLogScopedVerbosityOverride (FLogCategoryBase *Category, ELogVerbosity::Type Verbosity)
Back up the existing verbosity for the category then sets new verbosity.
~FLogScopedVerbosityOverride ()
Restore the verbosity overrides for the category to the previous value.
FLogScopedVerbosityOverride & operator= (const FLogScopedVerbosityOverride &)=delete
Private Attributes
FLogCategoryBase * SavedCategory
Backup of the category, verbosity pairs that was present when we were constructed.
ELogVerbosity::Type SavedVerbosity
Detailed Description
Helper class that allows setting scoped verbosity for log category.
Saved what was previous verbosity for the category, and recovers it when it goes out of scope. Use Macro LOG_SCOPE_VERBOSITY_OVERRIDE for this
Definition at line 19 of file LogScopedVerbosityOverride.h.
Constructor & Destructor Documentation
FLogScopedVerbosityOverride() [1/2]
FLogScopedVerbosityOverride::FLogScopedVerbosityOverride (FLogCategoryBase * Category, ELogVerbosity::Type Verbosity)
Back up the existing verbosity for the category then sets new verbosity.
References Category.
Referenced by FLogScopedVerbosityOverride(), and operator=().
~FLogScopedVerbosityOverride()
FLogScopedVerbosityOverride::~FLogScopedVerbosityOverride ()
Restore the verbosity overrides for the category to the previous value.
FLogScopedVerbosityOverride() [2/2]
FLogScopedVerbosityOverride::FLogScopedVerbosityOverride (const FLogScopedVerbosityOverride &) delete
References FLogScopedVerbosityOverride().
Member Function Documentation
operator=()
FLogScopedVerbosityOverride & FLogScopedVerbosityOverride::operator= (const FLogScopedVerbosityOverride &) delete
References FLogScopedVerbosityOverride().
Field Documentation
SavedCategory
FLogCategoryBase* FLogScopedVerbosityOverride::SavedCategory private
Backup of the category, verbosity pairs that was present when we were constructed.
Definition at line 23 of file LogScopedVerbosityOverride.h.
SavedVerbosity
ELogVerbosity::Type FLogScopedVerbosityOverride::SavedVerbosity private
Definition at line 24 of file LogScopedVerbosityOverride.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Logging/LogScopedVerbosityOverride.h