Unreal Engine 5.6 C++ API: TOneDynamicChild< SlotType > Class Template Reference
TOneDynamicChild< SlotType > Class Template Reference final
Required to implement GetChildren() in a way that can dynamically return the currently active child.
#include "Children.h"
Public Member Functions
TOneDynamicChild (std::nullptr_t, std::nullptr_t, const TAttribute< int32 > *InWidgetIndex)=delete
TOneDynamicChild (std::nullptr_t, std::nullptr_t, std::nullptr_t)=delete
TOneDynamicChild (std::nullptr_t, TPanelChildren< SlotType > *InAllChildren, std::nullptr_t)=delete
TOneDynamicChild (SWidget *InOwner, std::nullptr_t, const TAttribute< int32 > *InWidgetIndex)=delete
TOneDynamicChild (SWidget *InOwner, std::nullptr_t, std::nullptr_t)=delete
TOneDynamicChild (SWidget *InOwner, TPanelChildren< SlotType > *InAllChildren, const TAttribute< int32 > *InWidgetIndex)
TOneDynamicChild (SWidget *InOwner, TPanelChildren< SlotType > *InAllChildren, std::nullptr_t)=delete
virtual TSharedRef< const SWidget > GetChildAt (int32 Index) const override
virtual TSharedRef< SWidget > GetChildAt (int32 Index) override
virtual int32 Num () const override
Public Member Functions inherited from FChildren
FChildren (std::nullptr_t)=delete
FChildren (SWidget *InOwner)
FChildren (SWidget *InOwner, FName InName)
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred)
Applies the predicate to all the widgets contained by the FChildren.
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred) const
Applies the predicate to all the widgets contained by the FChildren.
FName GetName () const
Option to give a name to Children to SlotAttribute purposes or for debugging.
SWidget & GetOwner () const
virtual int32 NumSlot () const
void * operator new (size_t)=delete
void * operator new[] (size_t)=delete
virtual bool SupportSlotWithSlateAttribute () const
Private Member Functions
virtual FConstWidgetRef GetChildRefAt (int32 ChildIndex) const override
virtual FWidgetRef GetChildRefAt (int32 ChildIndex) override
virtual const FSlotBase & GetSlotAt (int32 ChildIndex) const override
Private Attributes
TPanelChildren< SlotType > * AllChildren
const TAttribute< int32 > * WidgetIndex
Additional Inherited Members
Protected Types inherited from FChildren
enum ECopyConstruct { CopyConstruct }
enum ERefConstruct { ReferenceConstruct }
Protected Member Functions inherited from FChildren
virtual ~FChildren ()
void Debug_TestDestroyTag () const
Detailed Description
template<typename SlotType>
class TOneDynamicChild< SlotType >
Required to implement GetChildren() in a way that can dynamically return the currently active child.
Definition at line 1027 of file Children.h.
Constructor & Destructor Documentation
TOneDynamicChild() [1/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (SWidget * InOwner, TPanelChildren< SlotType > * InAllChildren, const TAttribute< int32 > * InWidgetIndex) inline
Definition at line 1030 of file Children.h.
References FChildren::FChildren(), AllChildren, check, and WidgetIndex.
TOneDynamicChild() [2/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (SWidget * InOwner, TPanelChildren< SlotType > * InAllChildren, std::nullptr_t) delete
TOneDynamicChild() [3/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (SWidget * InOwner, std::nullptr_t , const TAttribute< int32 > * InWidgetIndex) delete
TOneDynamicChild() [4/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (SWidget * InOwner, std::nullptr_t , std::nullptr_t) delete
TOneDynamicChild() [5/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (std::nullptr_t , TPanelChildren< SlotType > * InAllChildren, std::nullptr_t) delete
TOneDynamicChild() [6/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (std::nullptr_t , std::nullptr_t , const TAttribute< int32 > * InWidgetIndex) delete
TOneDynamicChild() [7/7]
template<typename SlotType> TOneDynamicChild< SlotType >::TOneDynamicChild (std::nullptr_t , std::nullptr_t , std::nullptr_t) delete
Member Function Documentation
GetChildAt() [1/2]
template<typename SlotType> virtual TSharedRef< const SWidget > TOneDynamicChild< SlotType >::GetChildAt (int32 Index) const inline override virtual
Returns
const pointer to the Widget at the specified Index.
Implements FChildren.
Definition at line 1054 of file Children.h.
References AllChildren, check, and WidgetIndex.
GetChildAt() [2/2]
template<typename SlotType> virtual TSharedRef< SWidget > TOneDynamicChild< SlotType >::GetChildAt (int32 Index) inline override virtual
Returns
pointer to the Widget at the specified Index.
Implements FChildren.
Definition at line 1048 of file Children.h.
References AllChildren, check, and WidgetIndex.
GetChildRefAt() [1/2]
template<typename SlotType> virtual FConstWidgetRef TOneDynamicChild< SlotType >::GetChildRefAt (int32 Index) const inline override private virtual
Returns
ref to the Widget at the specified Index.
Implements FChildren.
Definition at line 1072 of file Children.h.
References FChildren::FChildren(), AllChildren, check, GetChildRefAt(), and WidgetIndex.
GetChildRefAt() [2/2]
template<typename SlotType> virtual FWidgetRef TOneDynamicChild< SlotType >::GetChildRefAt (int32 Index) inline override private virtual
Returns
ref to the Widget at the specified Index.
Implements FChildren.
Definition at line 1066 of file Children.h.
References FChildren::FChildren(), AllChildren, check, GetChildRefAt(), and WidgetIndex.
Referenced by GetChildRefAt(), and GetChildRefAt().
GetSlotAt()
template<typename SlotType> virtual const FSlotBase & TOneDynamicChild< SlotType >::GetSlotAt (int32 ChildIndex) const inline override private virtual
Returns
the const reference to the slot at the specified Index
Implements FChildren.
Definition at line 1061 of file Children.h.
References AllChildren.
Num()
template<typename SlotType> virtual int32 TOneDynamicChild< SlotType >::Num () const inline override virtual
Returns
the number of children
Implements FChildren.
Definition at line 1046 of file Children.h.
References AllChildren.
Field Documentation
AllChildren
template<typename SlotType> TPanelChildren<SlotType>* TOneDynamicChild< SlotType >::AllChildren private
Definition at line 1078 of file Children.h.
Referenced by TOneDynamicChild(), GetChildAt(), GetChildAt(), GetChildRefAt(), GetChildRefAt(), GetSlotAt(), and Num().
WidgetIndex
template<typename SlotType> const TAttribute<int32>* TOneDynamicChild< SlotType >::WidgetIndex private
Definition at line 1079 of file Children.h.
Referenced by TOneDynamicChild(), GetChildAt(), GetChildAt(), GetChildRefAt(), and GetChildRefAt().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Layout/Children.h