Unreal Engine 5.6 C++ API: FSHA1 Class Reference
FSHA1 Class Reference
#include "SecureHash.h"
Public Types
enum { DigestSize =20 }
Public Member Functions
FSHA1 ()
~FSHA1 ()
void Final ()
FSHAHash Finalize ()
void GetHash (uint8 *puDest)
void Reset ()
template<typename Type UE_REQUIRES>
void Update (const Type &InData)
void Update (const uint8 *data, uint64 len)
void UpdateWithString (const TCHAR *data, uint32 len)
Static Public Member Functions
static bool GetFileSHAHash (const TCHAR *Pathname, uint8 Hash[20], bool bIsFullPackageHash=true)
Gets the stored SHA hash from the platform, if it exists.
static FSHAHash HashBuffer (const void *Data, uint64 DataSize)
Calculate the hash on a single block and return it.
static void HashBuffer (const void *Data, uint64 DataSize, uint8 *OutHash)
Calculate the hash on a single block and return it.
static void HMACBuffer (const void *Key, uint32 KeySize, const void *Data, uint64 DataSize, uint8 *OutHash)
Generate the HMAC (Hash-based Message Authentication Code) for a block of data.
static void InitializeFileHashesFromBuffer (uint8 *Buffer, uint64 BufferSize, bool bDuplicateKeyMemory=false)
Shared hashes.sha reading code (each platform gets a buffer to the data, then passes it to this function for processing)
Data Fields
uint32 __reserved1 [1]
uint32 __reserved2 [3]
uint8 m_buffer [64]
uint64 m_count
uint8 m_digest [20]
uint32 m_state [5]
Private Member Functions
void Transform (const uint8 *buffer, uint64 len)
Static Private Attributes
static TMap< FString, uint8 * > FullFileSHAHashMap
Global map of filename to hash value, filled out in InitializeFileHashesFromBuffer.
static TMap< FString, uint8 * > ScriptSHAHashMap
Global map of filename to hash value, but for script-only SHA hashes.
Detailed Description
Definition at line 313 of file SecureHash.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DigestSize
Definition at line 317 of file SecureHash.h.
Constructor & Destructor Documentation
FSHA1()
FSHA1::FSHA1 ()
~FSHA1()
FSHA1::~FSHA1 ()
Member Function Documentation
Final()
void FSHA1::Final ()
Referenced by Finalize().
Finalize()
FSHAHash FSHA1::Finalize () inline
Definition at line 348 of file SecureHash.h.
References Final(), and GetHash().
GetFileSHAHash()
bool FSHA1::GetFileSHAHash (const TCHAR * Pathname, uint8 Hash[20], bool bIsFullPackageHash = true) static
Gets the stored SHA hash from the platform, if it exists.
This function must be able to be called from any thread.
Parameters
Pathname Pathname to the file to get the SHA for
Hash 20 byte array that receives the hash
bIsFullPackageHash true if we are looking for a full package hash, instead of a script code only hash
Returns
true if the hash was found, false otherwise
References Hash.
GetHash()
void FSHA1::GetHash (uint8 * puDest)
Referenced by Finalize().
HashBuffer() [1/2]
FSHAHash FSHA1::HashBuffer (const void * Data, uint64 DataSize) inline static
Calculate the hash on a single block and return it.
Parameters
Data Input data to hash
DataSize Size of the Data block
Returns
Resulting digest
Definition at line 375 of file SecureHash.h.
References DataSize, Hash, and HashBuffer().
HashBuffer() [2/2]
void FSHA1::HashBuffer (const void * Data, uint64 DataSize, uint8 * OutHash) static
Calculate the hash on a single block and return it.
Parameters
Data Input data to hash
DataSize Size of the Data block
OutHash Resulting hash value (20 byte buffer)
References DataSize.
Referenced by HashBuffer().
HMACBuffer()
void FSHA1::HMACBuffer (const void * Key, uint32 KeySize, const void * Data, uint64 DataSize, uint8 * OutHash) static
Generate the HMAC (Hash-based Message Authentication Code) for a block of data.
https://en.wikipedia.org/wiki/Hash-based_message_authentication_code
Parameters
Key The secret key to be used when generating the HMAC
KeySize The size of the key
Data Input data to hash
DataSize Size of the Data block
OutHash Resulting hash value (20 byte buffer)
References DataSize, and Key.
InitializeFileHashesFromBuffer()
void FSHA1::InitializeFileHashesFromBuffer (uint8 * Buffer, uint64 BufferSize, bool bDuplicateKeyMemory = false) static
Shared hashes.sha reading code (each platform gets a buffer to the data, then passes it to this function for processing)
Parameters
Buffer Contents of hashes.sha (probably loaded from an a section in the executable)
BufferSize Size of Buffer
bDuplicateKeyMemory If Buffer is not always loaded, pass true so that the 20 byte hashes are duplicated
References Buffer.
Reset()
void FSHA1::Reset ()
Transform()
void FSHA1::Transform (const uint8 * buffer, uint64 len) private
Update() [1/2]
template<typename Type UE_REQUIRES> void FSHA1::Update (const Type & InData) inline
Definition at line 339 of file SecureHash.h.
References Update().
Update() [2/2]
void FSHA1::Update (const uint8 * data, uint64 len)
Referenced by UE_DEPRECATED(), Update(), and USTRUCT().
UpdateWithString()
void FSHA1::UpdateWithString (const TCHAR * data, uint32 len)
Field Documentation
__reserved1
uint32 FSHA1::__reserved1[1]
Definition at line 324 of file SecureHash.h.
__reserved2
uint32 FSHA1::__reserved2[3]
Definition at line 327 of file SecureHash.h.
FullFileSHAHashMap
TMap<FString, uint8*> FSHA1::FullFileSHAHashMap static private
Global map of filename to hash value, filled out in InitializeFileHashesFromBuffer.
Definition at line 421 of file SecureHash.h.
m_buffer
uint8 FSHA1::m_buffer[64]
Definition at line 325 of file SecureHash.h.
m_count
uint64 FSHA1::m_count
Definition at line 323 of file SecureHash.h.
m_digest
uint8 FSHA1::m_digest[20]
Definition at line 326 of file SecureHash.h.
m_state
uint32 FSHA1::m_state[5]
Definition at line 322 of file SecureHash.h.
ScriptSHAHashMap
TMap<FString, uint8*> FSHA1::ScriptSHAHashMap static private
Global map of filename to hash value, but for script-only SHA hashes.
Definition at line 424 of file SecureHash.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/SecureHash.h