Unreal Engine 5.6 C++ API: FShaderId Class Reference
FShaderId Class Reference
Uniquely identifies an FShader instance.
#include "Shader.h"
Public Member Functions
FShaderId ()
FShaderId (const FShaderType *InType, const FSHAHash &InMaterialShaderMapHash, const FHashedName &InShaderPipeline, const FVertexFactoryType *InVertexFactoryType, int32 InPermutationId, EShaderPlatform InPlatform)
Data Fields
FSHAHash MaterialShaderMapHash
int32 PermutationId
uint32 Platform: SP_NumBits
FHashedName ShaderPipelineName
const FShaderType * Type
const FVertexFactoryType * VFType
Friends
uint32 GetTypeHash (const FShaderId &Id)
bool operator!= (const FShaderId &X, const FShaderId &Y)
bool operator== (const FShaderId &X, const FShaderId &Y)
Detailed Description
Uniquely identifies an FShader instance.
Used to link FMaterialShaderMaps and FShaders on load.
Definition at line 711 of file Shader.h.
Constructor & Destructor Documentation
FShaderId() [1/2]
FShaderId::FShaderId () inline
Definition at line 714 of file Shader.h.
Referenced by GetTypeHash, operator!=, and operator==.
FShaderId() [2/2]
FShaderId::FShaderId (const FShaderType * InType, const FSHAHash & InMaterialShaderMapHash, const FHashedName & InShaderPipeline, const FVertexFactoryType * InVertexFactoryType, int32 InPermutationId, EShaderPlatform InPlatform) inline
Definition at line 715 of file Shader.h.
References MaterialShaderMapHash, PermutationId, Platform, ShaderPipelineName, Type, and VFType.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FShaderId & Id) friend
Definition at line 731 of file Shader.h.
References FShaderId(), GetTypeHash, HashCombine(), MaterialShaderMapHash, PermutationId, Platform, ShaderPipelineName, Type, and VFType.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FShaderId & X, const FShaderId & Y) friend
Definition at line 751 of file Shader.h.
References FShaderId(), X, and Y.
operator==
bool operator== (const FShaderId & X, const FShaderId & Y) friend
Definition at line 741 of file Shader.h.
References FShaderId(), X, and Y.
Field Documentation
MaterialShaderMapHash
FSHAHash FShaderId::MaterialShaderMapHash
Definition at line 727 of file Shader.h.
Referenced by FShaderId(), and GetTypeHash.
PermutationId
int32 FShaderId::PermutationId
Definition at line 728 of file Shader.h.
Referenced by FShaderId(), and GetTypeHash.
Platform
uint32 FShaderId::Platform
Definition at line 729 of file Shader.h.
Referenced by FShaderId(), and GetTypeHash.
ShaderPipelineName
FHashedName FShaderId::ShaderPipelineName
Definition at line 726 of file Shader.h.
Referenced by FShaderId(), and GetTypeHash.
Type
const FShaderType* FShaderId::Type
Definition at line 724 of file Shader.h.
Referenced by FShaderId(), and GetTypeHash.
VFType
const FVertexFactoryType* FShaderId::VFType
Definition at line 725 of file Shader.h.
Referenced by FShaderId(), and GetTypeHash.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h