Unreal Engine 5.6 C++ API: FFutureState Class Reference
FFutureState Class Reference
Base class for the internal state of asynchronous return values (futures).
#include "Future.h"
Public Member Functions
FFutureState ()=default
Default constructor.
FFutureState (TUniqueFunction< void()> &&InCompletionCallback)
Create and initialize a new instance with a callback.
bool IsComplete () const
Checks whether the asynchronous result has been set.
void SetContinuation (TUniqueFunction< void()> &&Continuation)
Set a continuation to be called on completion of the promise.
bool WaitFor (const FTimespan &Duration) const
Blocks the calling thread until the future result is available.
Protected Member Functions
void MarkComplete ()
Notifies any waiting threads that the result is available.
Private Attributes
TAtomic< bool > bComplete { false }
Whether the asynchronous result is available.
TUniqueFunction< void()> CompletionCallback
An optional callback function that is executed the state is completed.
FPooledSyncEvent CompletionEvent { true }
Holds an event signaling that the result is available.
FCriticalSection Mutex
Mutex used to allow proper handling of continuations.
Detailed Description
Base class for the internal state of asynchronous return values (futures).
Definition at line 38 of file Future.h.
Constructor & Destructor Documentation
FFutureState() [1/2]
FFutureState::FFutureState () default
Default constructor.
Referenced by TFutureState< ResultType >::TFutureState(), and TFutureState< ResultType >::TFutureState().
FFutureState() [2/2]
FFutureState::FFutureState (TUniqueFunction< void()> && InCompletionCallback) inline
Create and initialize a new instance with a callback.
Parameters
InCompletionCallback A function that is called when the state is completed.
Definition at line 50 of file Future.h.
References CompletionCallback, and MoveTemp().
Member Function Documentation
IsComplete()
bool FFutureState::IsComplete () const inline
Checks whether the asynchronous result has been set.
Returns
true if the result has been set, false otherwise.
See also
WaitFor
Definition at line 63 of file Future.h.
References bComplete.
Referenced by TFutureState< ResultType >::~TFutureState(), TFutureState< ResultType >::EmplaceResult(), TFutureState< ResultType >::GetResult(), and SetContinuation().
MarkComplete()
void FFutureState::MarkComplete () inline protected
Notifies any waiting threads that the result is available.
Definition at line 110 of file Future.h.
References bComplete, CompletionCallback, CompletionEvent, MoveTemp(), and Mutex.
Referenced by TFutureState< ResultType >::EmplaceResult().
SetContinuation()
void FFutureState::SetContinuation (TUniqueFunction< void()> && Continuation) inline
Set a continuation to be called on completion of the promise.
Parameters
Continuation
Definition at line 89 of file Future.h.
References CompletionCallback, IsComplete(), MoveTemp(), and Mutex.
WaitFor()
bool FFutureState::WaitFor (const FTimespan & Duration) const inline
Blocks the calling thread until the future result is available.
Parameters
Duration The maximum time span to wait for the future result.
Returns
true if the result is available, false otherwise.
See also
IsComplete
Definition at line 75 of file Future.h.
References CompletionEvent, and Duration.
Referenced by TFutureState< ResultType >::GetResult().
Field Documentation
bComplete
TAtomic<bool> FFutureState::bComplete { false } private
Whether the asynchronous result is available.
Definition at line 137 of file Future.h.
Referenced by IsComplete(), and MarkComplete().
CompletionCallback
TUniqueFunction<void()> FFutureState::CompletionCallback private
An optional callback function that is executed the state is completed.
Definition at line 131 of file Future.h.
Referenced by FFutureState(), TFutureState< ResultType >::TFutureState(), MarkComplete(), and SetContinuation().
CompletionEvent
FPooledSyncEvent FFutureState::CompletionEvent { true } private
Holds an event signaling that the result is available.
Definition at line 134 of file Future.h.
Referenced by MarkComplete(), and WaitFor().
Mutex
FCriticalSection FFutureState::Mutex mutable private
Mutex used to allow proper handling of continuations.
Definition at line 128 of file Future.h.
Referenced by MarkComplete(), and SetContinuation().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/Future.h