Unreal Engine 5.6 C++ API: TAnimatedAttribute< NumericType > Class Template Reference
TAnimatedAttribute< NumericType > Class Template Reference
Animated Attribute object.
#include "AnimatedAttribute.h"
Data Structures
struct FPrivateToken
Public Types
using FGetter = TDelegate<NumericType()>
Attribute 'getter' delegate.
Public Member Functions
template<typename InterpolatorSettings>
TAnimatedAttribute (FPrivateToken, const InterpolatorSettings &InSettings)
Construct only from interpolator settings This is used only for the Create methods and only accessible from there due to the use of a protected FPrivateToken.
void DisableInterpolation ()
Disables the interpolator and returns values in immediate mode.
void EnableInterpolation (bool bEnabled=true)
Enables (or disables) the interpolator and returns values in interpolated or immediate mode.
const NumericType & Get () const
Gets the attribute's current value.
const NumericType & Get (const NumericType &DefaultValue) const
Gets the attribute's current value.
TOptional< NumericType > GetDelay () const
Returns the currently set delay on the interpolator.
const NumericType & GetDesiredValue () const
Returns the desired value this attribute is trying to reach.
double GetOverAllDeltaTime () const
Returns the overall deltatime of the interpolator.
bool IdenticalTo (const TAnimatedAttribute &InOther) const
Is this attribute identical to another TAnimationAttribute.
bool IsBound () const
Checks to see if this attribute has a 'getter' function bound.
bool IsPlaying () const
Returns true if the attribute is currently animating.
bool IsSet () const
Was this TAnimatedAttribute ever assigned?
TAttributeInterpolator< NumericType >::FInterpolatorEvent & OnInterpolationStarted ()
TAttributeInterpolator< NumericType >::FInterpolatorEvent & OnInterpolationStopped ()
template<typename OtherType>
void Set (const OtherType &InNewValue)
Sets the attribute's value while keeping a running interpolation going.
void Set (NumericType &&InNewValue)
Sets the attribute's value while keeping a running interpolation going.
void SetDelayOneShot (double InDelay)
Sets the attribute's delay as a one shot.
void SetTolerance (double Tolerance)
Sets the tolerance of this interpolator.
void SetValueAndStop (const NumericType &InNewValue)
Sets the attribute's value and disables animation.
void SetValueAndStop (NumericType &&InNewValue)
Sets the attribute's value and disables animation.
Public Member Functions inherited from TSharedFromThis< TAnimatedAttributeBase >
TSharedRef< TAnimatedAttributeBase, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< TAnimatedAttributeBase, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename InterpolatorSettings, typename OtherType>
static TSharedRef< TAnimatedAttribute > Create (const InterpolatorSettings &InSettings, OtherType &&InInitialValue)
Static: Creates an animated attribute implicitly from an initial value.
template<typename InterpolatorSettings>
static TSharedRef< TAnimatedAttribute > CreateWithGetter (const InterpolatorSettings &InSettings, const FGetter &InGetter, const TOptional< NumericType > &InDefaultValue=TOptional< NumericType >())
Static: Creates an animated attribute that's pre-bound to the specified 'getter' delegate.
template<typename InterpolatorSettings>
static TSharedRef< TAnimatedAttribute > CreateWithGetter (const InterpolatorSettings &InSettings, FGetter &&InGetter, const TOptional< NumericType > &InDefaultValue=TOptional< NumericType >())
Static: Creates an animated attribute that's pre-bound to the specified 'getter' delegate.
Protected Member Functions
TAnimatedAttribute ()=delete
Default constructor.
Protected Member Functions inherited from TAnimatedAttributeBase
TAnimatedAttributeBase ()
virtual ~TAnimatedAttributeBase ()
void Register ()
void Unregister ()
Protected Member Functions inherited from TSharedFromThis< TAnimatedAttributeBase >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
virtual void Tick (float InDeltaTime) override
Updates the interpolator / ticks the animation.
Private Attributes
TOptional< NumericType > DesiredValue
Current value.
FGetter Getter
Bound member function for this attribute (may be NULL if no function is bound.) When set, all attempts to read the attribute's value will instead call this delegate to generate the value.
TUniquePtr< TAttributeInterpolator< NumericType > > Interpolator
The attribute's interpolator.
Friends
template<class OtherType>
class TAnimatedAttribute
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< TAnimatedAttributeBase >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename NumericType>
class TAnimatedAttribute< NumericType >
Animated Attribute object.
Definition at line 13 of file AnimatedAttribute.h.
Member Typedef Documentation
FGetter
template<typename NumericType> using TAnimatedAttribute< NumericType >::FGetter = TDelegate<NumericType()>
Attribute 'getter' delegate.
NumericType GetValue() const
Returns
The attribute's value
Definition at line 24 of file AnimatedAttribute.h.
Constructor & Destructor Documentation
TAnimatedAttribute() [1/2]
template<typename NumericType> TAnimatedAttribute< NumericType >::TAnimatedAttribute () protected delete
Default constructor.
TAnimatedAttribute() [2/2]
template<typename NumericType> template<typename InterpolatorSettings> TAnimatedAttribute< NumericType >::TAnimatedAttribute (FPrivateToken , const InterpolatorSettings & InSettings) inline
Construct only from interpolator settings This is used only for the Create methods and only accessible from there due to the use of a protected FPrivateToken.
Please rely on the Create methods if you are seeing a compiler error related to this.
Parameters
InSettings The settings for the interpolator
Definition at line 44 of file AnimatedAttribute.h.
References DesiredValue, Getter, Interpolator, and MakeUnique().
Member Function Documentation
Create()
template<typename NumericType> template<typename InterpolatorSettings, typename OtherType> TSharedRef< TAnimatedAttribute > TAnimatedAttribute< NumericType >::Create (const InterpolatorSettings & InSettings, OtherType && InInitialValue) inline static nodiscard
Static: Creates an animated attribute implicitly from an initial value.
Parameters
InSettings The settings for the interpolator
InInitialValue The value for this attribute
Definition at line 58 of file AnimatedAttribute.h.
References Attribute, Forward(), and MakeShared().
CreateWithGetter() [1/2]
template<typename NumericType> template<typename InterpolatorSettings> TSharedRef< TAnimatedAttribute > TAnimatedAttribute< NumericType >::CreateWithGetter (const InterpolatorSettings & InSettings, const FGetter & InGetter, const TOptional< NumericType > & InDefaultValue = TOptional<NumericType>()) inline static nodiscard
Static: Creates an animated attribute that's pre-bound to the specified 'getter' delegate.
Parameters
InSettings The settings for the interpolator
InGetter Delegate to bind
InDefaultValue The optional default value. If not specified the getter will be used to determine the default
Definition at line 74 of file AnimatedAttribute.h.
References Attribute, and MakeShared().
CreateWithGetter() [2/2]
template<typename NumericType> template<typename InterpolatorSettings> TSharedRef< TAnimatedAttribute > TAnimatedAttribute< NumericType >::CreateWithGetter (const InterpolatorSettings & InSettings, FGetter && InGetter, const TOptional< NumericType > & InDefaultValue = TOptional<NumericType>()) inline static nodiscard
Static: Creates an animated attribute that's pre-bound to the specified 'getter' delegate.
Parameters
InSettings The settings for the interpolator
InGetter Delegate to bind
InDefaultValue The optional default value. If not specified the getter will be used to determine the default
Definition at line 91 of file AnimatedAttribute.h.
References Attribute, MakeShared(), and MoveTemp().
DisableInterpolation()
template<typename NumericType> void TAnimatedAttribute< NumericType >::DisableInterpolation () inline
Disables the interpolator and returns values in immediate mode.
Definition at line 283 of file AnimatedAttribute.h.
References EnableInterpolation().
EnableInterpolation()
template<typename NumericType> void TAnimatedAttribute< NumericType >::EnableInterpolation (bool bEnabled = true) inline
Enables (or disables) the interpolator and returns values in interpolated or immediate mode.
Definition at line 275 of file AnimatedAttribute.h.
References Interpolator.
Referenced by DisableInterpolation().
Get() [1/2]
template<typename NumericType> const NumericType & TAnimatedAttribute< NumericType >::Get () const inline
Gets the attribute's current value.
Assumes that the attribute is set.
Returns
The attribute's value
Definition at line 175 of file AnimatedAttribute.h.
References DesiredValue, Getter, and Interpolator.
Referenced by Get().
Get() [2/2]
template<typename NumericType> const NumericType & TAnimatedAttribute< NumericType >::Get (const NumericType & DefaultValue) const inline
Gets the attribute's current value.
The attribute may not be set, in which case use the default value provided. Shorthand for the boilerplate code: MyAttribute.IsSet() ? MyAttribute.Get() : DefaultValue
Definition at line 214 of file AnimatedAttribute.h.
References Get(), and IsSet().
GetDelay()
template<typename NumericType> TOptional< NumericType > TAnimatedAttribute< NumericType >::GetDelay () const inline
Returns the currently set delay on the interpolator.
Definition at line 243 of file AnimatedAttribute.h.
References Interpolator.
GetDesiredValue()
template<typename NumericType> const NumericType & TAnimatedAttribute< NumericType >::GetDesiredValue () const inline
Returns the desired value this attribute is trying to reach.
Definition at line 222 of file AnimatedAttribute.h.
References DesiredValue.
GetOverAllDeltaTime()
template<typename NumericType> double TAnimatedAttribute< NumericType >::GetOverAllDeltaTime () const inline
Returns the overall deltatime of the interpolator.
Definition at line 235 of file AnimatedAttribute.h.
References Interpolator.
IdenticalTo()
template<typename NumericType> bool TAnimatedAttribute< NumericType >::IdenticalTo (const TAnimatedAttribute< NumericType > & InOther) const inline
Is this attribute identical to another TAnimationAttribute.
Parameters
InOther The other attribute to compare with.
Returns
true if the attributes are identical, false otherwise.
Definition at line 304 of file AnimatedAttribute.h.
References TAnimatedAttribute, DesiredValue, TUniquePtr< T, Deleter >::Get(), Getter, Interpolator, IsBound(), and IsSet().
IsBound()
template<typename NumericType> bool TAnimatedAttribute< NumericType >::IsBound () const inline
Checks to see if this attribute has a 'getter' function bound.
Returns
True if attribute is bound to a getter function
Definition at line 293 of file AnimatedAttribute.h.
References Getter.
Referenced by IdenticalTo(), and IsSet().
IsPlaying()
template<typename NumericType> bool TAnimatedAttribute< NumericType >::IsPlaying () const inline
Returns true if the attribute is currently animating.
Definition at line 267 of file AnimatedAttribute.h.
References Interpolator.
IsSet()
template<typename NumericType> bool TAnimatedAttribute< NumericType >::IsSet () const inline
Was this TAnimatedAttribute ever assigned?
Definition at line 164 of file AnimatedAttribute.h.
References DesiredValue, and IsBound().
Referenced by Get(), and IdenticalTo().
OnInterpolationStarted()
template<typename NumericType> TAttributeInterpolator< NumericType >::FInterpolatorEvent & TAnimatedAttribute< NumericType >::OnInterpolationStarted () inline
Definition at line 327 of file AnimatedAttribute.h.
References Interpolator.
OnInterpolationStopped()
template<typename NumericType> TAttributeInterpolator< NumericType >::FInterpolatorEvent & TAnimatedAttribute< NumericType >::OnInterpolationStopped () inline
Definition at line 335 of file AnimatedAttribute.h.
References Interpolator.
Set() [1/2]
template<typename NumericType> template<typename OtherType> void TAnimatedAttribute< NumericType >::Set (const OtherType & InNewValue) inline
Sets the attribute's value while keeping a running interpolation going.
The value will be become the new desired value and the interpolation will continue trying to reach it. If the interpolation is currently stopped the animation / interpolation will restart towards the new provided value.
Parameters
InNewValue The value to set the attribute to
Definition at line 109 of file AnimatedAttribute.h.
References DesiredValue, Getter, and Interpolator.
Referenced by SetValueAndStop(), and SetValueAndStop().
Set() [2/2]
template<typename NumericType> void TAnimatedAttribute< NumericType >::Set (NumericType && InNewValue) inline
Sets the attribute's value while keeping a running interpolation going.
The value will be become the new desired value and the interpolation will continue trying to reach it. If the interpolation is currently stopped the animation / interpolation will restart towards the new provided value.
Parameters
InNewValue The value to set the attribute to
Definition at line 128 of file AnimatedAttribute.h.
References DesiredValue, Getter, and Interpolator.
SetDelayOneShot()
template<typename NumericType> void TAnimatedAttribute< NumericType >::SetDelayOneShot (double InDelay) inline
Sets the attribute's delay as a one shot.
Definition at line 251 of file AnimatedAttribute.h.
References Interpolator.
SetTolerance()
template<typename NumericType> void TAnimatedAttribute< NumericType >::SetTolerance (double Tolerance) inline
Sets the tolerance of this interpolator.
Definition at line 259 of file AnimatedAttribute.h.
References Interpolator.
SetValueAndStop() [1/2]
template<typename NumericType> void TAnimatedAttribute< NumericType >::SetValueAndStop (const NumericType & InNewValue) inline
Sets the attribute's value and disables animation.
The interpolator will be stopped and the value will become the new current value.
Parameters
InNewValue The value to set the attribute to
Definition at line 145 of file AnimatedAttribute.h.
References Interpolator, and Set().
SetValueAndStop() [2/2]
template<typename NumericType> void TAnimatedAttribute< NumericType >::SetValueAndStop (NumericType && InNewValue) inline
Sets the attribute's value and disables animation.
The interpolator will be stopped and the value will become the new current value.
Parameters
InNewValue The value to set the attribute to
Definition at line 157 of file AnimatedAttribute.h.
References Forward(), Interpolator, and Set().
Tick()
template<typename NumericType> virtual void TAnimatedAttribute< NumericType >::Tick (float InDeltaTime) inline override private virtual
Updates the interpolator / ticks the animation.
Implements TAnimatedAttributeBase.
Definition at line 345 of file AnimatedAttribute.h.
References DesiredValue, Getter, and Interpolator.
Friends And Related Symbol Documentation
TAnimatedAttribute
template<typename NumericType> template<class OtherType> friend class TAnimatedAttribute friend
Definition at line 359 of file AnimatedAttribute.h.
References TAnimatedAttribute.
Referenced by TAnimatedAttribute, and IdenticalTo().
Field Documentation
DesiredValue
template<typename NumericType> TOptional< NumericType > TAnimatedAttribute< NumericType >::DesiredValue mutable private
Current value.
Mutable so that we can cache the value locally when using a bound Getter (allows const ref return value.)
Definition at line 370 of file AnimatedAttribute.h.
Referenced by TAnimatedAttribute(), Get(), GetDesiredValue(), IdenticalTo(), IsSet(), Set(), Set(), and Tick().
Getter
template<typename NumericType> FGetter TAnimatedAttribute< NumericType >::Getter private
Bound member function for this attribute (may be NULL if no function is bound.) When set, all attempts to read the attribute's value will instead call this delegate to generate the value.
Our attribute's 'getter' delegate
Definition at line 367 of file AnimatedAttribute.h.
Referenced by TAnimatedAttribute(), Get(), IdenticalTo(), IsBound(), Set(), Set(), and Tick().
Interpolator
template<typename NumericType> TUniquePtr< TAttributeInterpolator< NumericType > > TAnimatedAttribute< NumericType >::Interpolator private
The attribute's interpolator.
Definition at line 362 of file AnimatedAttribute.h.
Referenced by TAnimatedAttribute(), EnableInterpolation(), Get(), GetDelay(), GetOverAllDeltaTime(), IdenticalTo(), IsPlaying(), OnInterpolationStarted(), OnInterpolationStopped(), Set(), Set(), SetDelayOneShot(), SetTolerance(), SetValueAndStop(), SetValueAndStop(), and Tick().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Animation/AnimatedAttribute.h