Unreal Engine 5.6 C++ API: FPathPermissionList Class Reference
FPathPermissionList Class Reference
Set of paths that are allowd and/or denied for certain use cases.
#include "NamePermissionList.h"
Public Member Functions
PRAGMA_ENABLE_DEPRECATION_WARNINGS FPathPermissionList (const FPathPermissionList &)=default
FPathPermissionList (EPathPermissionListType InType=EPathPermissionListType::Default)
FPathPermissionList (FPathPermissionList &&)=default
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS ~FPathPermissionList ()
bool AddAllowListItem (const FName OwnerName, const FName Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
bool AddAllowListItem (const FName OwnerName, const FStringView Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
bool AddAllowListItem (const FName OwnerName, const TCHAR *Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
bool AddDenyListAll (const FName OwnerName)
Set to filter out all items.
bool AddDenyListItem (const FName OwnerName, const FName Item)
Add item to DenyList, this specific item will be filtered out.
bool AddDenyListItem (const FName OwnerName, const FStringView Item)
Add item to DenyList, this specific item will be filtered out.
bool AddDenyListItem (const FName OwnerName, const TCHAR *Item)
Add item to DenyList, this specific item will be filtered out.
bool Append (const FPathPermissionList &Other)
Add the specified filters to this one.
FPathPermissionList CombinePathFilters (const FPathPermissionList &OtherFilter) const
Combine two filters.
bool ContainsDenyListItem (FStringView Item) const
Returns whether the given path has been denied explicitly with a call to AddDenyListItem.
FPermissionListOwners & GetAllowList () const
TArray< FString > GetAllowListEntries () const
Returns a copy of the paths explicity allowed in this list.
FPermissionListOwners & GetDenyList () const
TArray< FString > GetDenyListEntries () const
Get a copy of the paths explicity denied in this list.
TArray< FName > GetOwnerNames () const
Gathers the names of all the owners in this DenyList.
bool HasAllowListEntries () const
Returns whether this list has any explicitly allowed paths, which will lead to it denying access to any paths not listed.
bool HasDenyListEntries () const
Returns whether this list has any explicitly denied paths.
bool HasFiltering () const
True if has filters active.
bool IsDenyListAll () const
Are all items set to be filtered out.
FSimpleMulticastDelegate & OnFilterChanged ()
Triggered when filter changes.
FPathPermissionList & operator= (const FPathPermissionList &)=default
FPathPermissionList & operator= (FPathPermissionList &&)=default
bool PassesFilter (const FName Item) const
Returns true if passes filter restrictions using exact match.
bool PassesFilter (const FStringView Item) const
Returns true if passes filter restrictions using exact match.
bool PassesFilter (const TCHAR *Item) const
Returns true if passes filter restrictions using exact match.
bool PassesStartsWithFilter (const FName Item, const bool bAllowParentPaths=false) const
Returns true if passes filter restrictions for path.
bool PassesStartsWithFilter (const FStringView Item, const bool bAllowParentPaths=false) const
Returns true if passes filter restrictions for path.
bool PassesStartsWithFilter (const TCHAR *Item, const bool bAllowParentPaths=false) const
Returns true if passes filter restrictions for path.
EPathPermissionPrefixResult PassesStartsWithFilterRecursive (const FStringView Item, const bool bAllowParentPaths=false) const
Checks the given path against the restrictions and return whether it's possible for any child paths to succeed or fail as well.
bool RemoveAllowListItem (const FName OwnerName, const FName Item)
Remove item from the AllowList.
bool RemoveAllowListItem (const FName OwnerName, const FStringView Item)
Remove item from the AllowList.
bool RemoveAllowListItem (const FName OwnerName, const TCHAR *Item)
Remove item from the AllowList.
bool RemoveDenyListItem (const FName OwnerName, const FName Item)
Remove item from the DenyList.
bool RemoveDenyListItem (const FName OwnerName, const FStringView Item)
Remove item from the DenyList.
bool RemoveDenyListItem (const FName OwnerName, const TCHAR *Item)
Remove item from the DenyList.
FPermissionListOwners RemoveDenyListItemAndGetOwners (FStringView Item)
Removes an item from the deny list and returns a list of all the owners of that item so that the item can be re-introduced.
FString ToString () const
Dumps the path permission list details into a multi-line string.
UE_DEPRECATED (5.5, "GetAllowList is deprecated. Use GetAllowListEntries instead.") const TMap< FString
Get raw allowlist.
UE_DEPRECATED (5.5, "GetDenyList is deprecated. Use GetDenyListEntries instead.") const TMap< FString
Get raw DenyList.
bool UnregisterOwner (const FName OwnerName)
Removes all filtering changes associated with a specific owner name.
bool UnregisterOwners (const TArray< FName > &OwnerNames)
Removes all filtering changes associated with the specified list of owner names.
bool UnregisterOwnersAndAppend (const TArray< FName > &OwnerNamesToRemove, const FPathPermissionList &FiltersToAdd)
Unregisters specified owners then adds specified filters in one operation (to avoid multiple filters changed events).
Public Member Functions inherited from TSharedFromThis< FPathPermissionList >
TSharedRef< FPathPermissionList, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FPathPermissionList, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
void VerifyItemMatchesListType (const FStringView Item) const
Checks if an item is of a valid format for this list.
Protected Member Functions inherited from TSharedFromThis< FPathPermissionList >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TDirectoryTree< FPermissionListOwners > AllowTree
Compiled path tree produced from AllowList.
bool bSuppressOnFilterChanged = false
Temporarily prevent delegate from being triggered.
FPermissionListOwners DenyListAll
List of owner names that requested all items to be filtered out.
TDirectoryTree< FPermissionListOwners > DenyTree
Compiled path tree produced from DenyList.
EPathPermissionListType ListType
Type of paths this list represent.
FSimpleMulticastDelegate OnFilterChangedDelegate
Triggered when filter changes.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FPathPermissionList >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Set of paths that are allowd and/or denied for certain use cases.
A permission list may contain
Blanket denial
Specifically denied paths
Specifically allowed paths In decreasing order of priority. When performing prefix checks, if a a path matches a denied path, it cannot be allowed again by a more specific allowed path. If any paths are specifically allowed, paths which do NOT match something in the allow list are implicitly denied.
Definition at line 158 of file NamePermissionList.h.
Constructor & Destructor Documentation
FPathPermissionList() [1/3]
FPathPermissionList::FPathPermissionList (EPathPermissionListType InType = EPathPermissionListType::Default)
References Default, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by FPathPermissionList(), FPathPermissionList(), Append(), CombinePathFilters(), operator=(), operator=(), and UnregisterOwnersAndAppend().
~FPathPermissionList()
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS FPathPermissionList::~FPathPermissionList () inline virtual
Definition at line 163 of file NamePermissionList.h.
FPathPermissionList() [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FPathPermissionList::FPathPermissionList (const FPathPermissionList &) default
References FPathPermissionList().
FPathPermissionList() [3/3]
FPathPermissionList::FPathPermissionList (FPathPermissionList &&) default
References FPathPermissionList().
Member Function Documentation
AddAllowListItem() [1/3]
bool FPathPermissionList::AddAllowListItem (const FName OwnerName, const FName Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
Returns
whether the filters changed.
References Item.
AddAllowListItem() [2/3]
bool FPathPermissionList::AddAllowListItem (const FName OwnerName, const FStringView Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
Returns
whether the filters changed.
References Item.
AddAllowListItem() [3/3]
bool FPathPermissionList::AddAllowListItem (const FName OwnerName, const TCHAR * Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
Returns
whether the filters changed.
References Item.
AddDenyListAll()
bool FPathPermissionList::AddDenyListAll (const FName OwnerName)
Set to filter out all items.
Returns
whether the filters changed.
AddDenyListItem() [1/3]
bool FPathPermissionList::AddDenyListItem (const FName OwnerName, const FName Item)
Add item to DenyList, this specific item will be filtered out.
Returns
whether the filters changed.
References Item.
AddDenyListItem() [2/3]
bool FPathPermissionList::AddDenyListItem (const FName OwnerName, const FStringView Item)
Add item to DenyList, this specific item will be filtered out.
Returns
whether the filters changed.
References Item.
AddDenyListItem() [3/3]
bool FPathPermissionList::AddDenyListItem (const FName OwnerName, const TCHAR * Item)
Add item to DenyList, this specific item will be filtered out.
Returns
whether the filters changed.
References Item.
Append()
bool FPathPermissionList::Append (const FPathPermissionList & Other)
Add the specified filters to this one.
Rules are not applied, direct append lists.
Returns
whether the filters changed.
References FPathPermissionList(), and Other.
CombinePathFilters()
FPathPermissionList FPathPermissionList::CombinePathFilters (const FPathPermissionList & OtherFilter) const nodiscard
Combine two filters.
Result will contain all DenyList paths combined. Result will contain AllowList paths that pass both filters.
Returns
new combined filter.
References FPathPermissionList().
ContainsDenyListItem()
bool FPathPermissionList::ContainsDenyListItem (FStringView Item) const
Returns whether the given path has been denied explicitly with a call to AddDenyListItem.
References Item.
GetAllowList()
FPermissionListOwners & FPathPermissionList::GetAllowList () const
References GetAllowList().
Referenced by GetAllowList().
GetAllowListEntries()
TArray< FString > FPathPermissionList::GetAllowListEntries () const
Returns a copy of the paths explicity allowed in this list.
GetDenyList()
FPermissionListOwners & FPathPermissionList::GetDenyList () const
References GetDenyList().
Referenced by GetDenyList().
GetDenyListEntries()
TArray< FString > FPathPermissionList::GetDenyListEntries () const
Get a copy of the paths explicity denied in this list.
GetOwnerNames()
TArray< FName > FPathPermissionList::GetOwnerNames () const
Gathers the names of all the owners in this DenyList.
HasAllowListEntries()
bool FPathPermissionList::HasAllowListEntries () const
Returns whether this list has any explicitly allowed paths, which will lead to it denying access to any paths not listed.
HasDenyListEntries()
bool FPathPermissionList::HasDenyListEntries () const
Returns whether this list has any explicitly denied paths.
HasFiltering()
bool FPathPermissionList::HasFiltering () const
True if has filters active.
IsDenyListAll()
bool FPathPermissionList::IsDenyListAll () const inline
Are all items set to be filtered out.
Definition at line 377 of file NamePermissionList.h.
References DenyListAll, and IsDenyListAll().
Referenced by IsDenyListAll().
OnFilterChanged()
FSimpleMulticastDelegate & FPathPermissionList::OnFilterChanged () inline
Triggered when filter changes.
Definition at line 380 of file NamePermissionList.h.
References OnFilterChangedDelegate.
operator=() [1/2]
FPathPermissionList & FPathPermissionList::operator= (const FPathPermissionList &) default
References FPathPermissionList().
operator=() [2/2]
FPathPermissionList & FPathPermissionList::operator= (FPathPermissionList &&) default
References FPathPermissionList().
PassesFilter() [1/3]
bool FPathPermissionList::PassesFilter (const FName Item) const
Returns true if passes filter restrictions using exact match.
References Item.
PassesFilter() [2/3]
bool FPathPermissionList::PassesFilter (const FStringView Item) const
Returns true if passes filter restrictions using exact match.
References Item.
PassesFilter() [3/3]
bool FPathPermissionList::PassesFilter (const TCHAR * Item) const
Returns true if passes filter restrictions using exact match.
References Item.
PassesStartsWithFilter() [1/3]
bool FPathPermissionList::PassesStartsWithFilter (const FName Item, const bool bAllowParentPaths = false) const
Returns true if passes filter restrictions for path.
References Item.
PassesStartsWithFilter() [2/3]
bool FPathPermissionList::PassesStartsWithFilter (const FStringView Item, const bool bAllowParentPaths = false) const
Returns true if passes filter restrictions for path.
References Item.
PassesStartsWithFilter() [3/3]
bool FPathPermissionList::PassesStartsWithFilter (const TCHAR * Item, const bool bAllowParentPaths = false) const
Returns true if passes filter restrictions for path.
References Item.
PassesStartsWithFilterRecursive()
EPathPermissionPrefixResult FPathPermissionList::PassesStartsWithFilterRecursive (const FStringView Item, const bool bAllowParentPaths = false) const
Checks the given path against the restrictions and return whether it's possible for any child paths to succeed or fail as well.
Returning PassRecursive or FailRecursive guarantees that no child paths of the queried path can fail or pass the filter respectively. Returning Pass or Fail does not guarantee that there is some path which fails or passes the filter respectively.
Examples:
Given no deny or allow lists: Inputs: / -> PassRecursive, because no paths can fail to match the allow list or match the deny list.
Given a deny-list entry: Allow: empty Deny: /Secret Inputs: / -> Pass, because some children of this path may be denied. /Secret -> FailRecursive, because this path is denied and all children will also be denied. /Public -> PassRecursive, because this path is not demied and no children can be denied.
Given an allow-list entry: Allow: /JustThis Deny: empty Inputs: / -> Fail /JustThis -> PassRecursive /SomethingElse -> FailRecursive
Given both allow and deny-lists: Allow: /Stuff Deny: /Stuff/Secret Inputs: / -> Fail /Stuff -> Pass /Stuff/Secret -> Fail /Stuff/Public -> PassRecursive
References Item.
RemoveAllowListItem() [1/3]
bool FPathPermissionList::RemoveAllowListItem (const FName OwnerName, const FName Item)
Remove item from the AllowList.
Returns
whether the filters changed
References Item.
RemoveAllowListItem() [2/3]
bool FPathPermissionList::RemoveAllowListItem (const FName OwnerName, const FStringView Item)
Remove item from the AllowList.
Returns
whether the filters changed
References Item.
RemoveAllowListItem() [3/3]
bool FPathPermissionList::RemoveAllowListItem (const FName OwnerName, const TCHAR * Item)
Remove item from the AllowList.
Returns
whether the filters changed
References Item.
RemoveDenyListItem() [1/3]
bool FPathPermissionList::RemoveDenyListItem (const FName OwnerName, const FName Item)
Remove item from the DenyList.
Returns
whether the filters changed
References Item.
RemoveDenyListItem() [2/3]
bool FPathPermissionList::RemoveDenyListItem (const FName OwnerName, const FStringView Item)
Remove item from the DenyList.
Returns
whether the filters changed
References Item.
RemoveDenyListItem() [3/3]
bool FPathPermissionList::RemoveDenyListItem (const FName OwnerName, const TCHAR * Item)
Remove item from the DenyList.
Returns
whether the filters changed
References Item.
RemoveDenyListItemAndGetOwners()
FPermissionListOwners FPathPermissionList::RemoveDenyListItemAndGetOwners (FStringView Item)
Removes an item from the deny list and returns a list of all the owners of that item so that the item can be re-introduced.
References Item.
ToString()
FString FPathPermissionList::ToString () const
Dumps the path permission list details into a multi-line string.
UE_DEPRECATED() [1/2]
FPathPermissionList::UE_DEPRECATED (5. 5, "GetAllowList is deprecated. Use GetAllowListEntries instead.") const
Get raw allowlist.
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FPathPermissionList::UE_DEPRECATED (5. 5, "GetDenyList is deprecated. Use GetDenyListEntries instead.") const
Get raw DenyList.
Referenced by UE_DEPRECATED().
UnregisterOwner()
bool FPathPermissionList::UnregisterOwner (const FName OwnerName)
Removes all filtering changes associated with a specific owner name.
Returns
whether the filters changed.
UnregisterOwners()
bool FPathPermissionList::UnregisterOwners (const TArray< FName > & OwnerNames)
Removes all filtering changes associated with the specified list of owner names.
Returns
whether the filters changed.
UnregisterOwnersAndAppend()
bool FPathPermissionList::UnregisterOwnersAndAppend (const TArray< FName > & OwnerNamesToRemove, const FPathPermissionList & FiltersToAdd)
Unregisters specified owners then adds specified filters in one operation (to avoid multiple filters changed events).
Returns
whether the filters changed.
References FPathPermissionList().
VerifyItemMatchesListType()
void FPathPermissionList::VerifyItemMatchesListType (const FStringView Item) const protected
Checks if an item is of a valid format for this list.
Returns
True if the item passes list type test.
References Item.
Field Documentation
AllowTree
TDirectoryTree<FPermissionListOwners> FPathPermissionList::AllowTree protected
Compiled path tree produced from AllowList.
Definition at line 397 of file NamePermissionList.h.
bSuppressOnFilterChanged
bool FPathPermissionList::bSuppressOnFilterChanged = false protected
Temporarily prevent delegate from being triggered.
Definition at line 406 of file NamePermissionList.h.
DenyListAll
FPermissionListOwners FPathPermissionList::DenyListAll protected
List of owner names that requested all items to be filtered out.
Definition at line 400 of file NamePermissionList.h.
Referenced by IsDenyListAll().
DenyTree
TDirectoryTree<FPermissionListOwners> FPathPermissionList::DenyTree protected
Compiled path tree produced from DenyList.
Definition at line 394 of file NamePermissionList.h.
ListType
EPathPermissionListType FPathPermissionList::ListType protected
Type of paths this list represent.
Definition at line 409 of file NamePermissionList.h.
OnFilterChangedDelegate
FSimpleMulticastDelegate FPathPermissionList::OnFilterChangedDelegate protected
Triggered when filter changes.
Definition at line 403 of file NamePermissionList.h.
Referenced by OnFilterChanged().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/NamePermissionList.h