Unreal Engine 5.6 C++ API: FLocMetadataValueBoolean Class Reference
FLocMetadataValueBoolean Class Reference
A LocMetadata Boolean Value.
#include "InternationalizationMetadata.h"
Public Member Functions
FLocMetadataValueBoolean (bool InBool)
FLocMetadataValueBoolean (FStructuredArchive::FSlot Slot)
virtual bool AsBool () override
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
virtual TSharedRef< FLocMetadataValue > Clone () const override
virtual ELocMetadataType GetType () const override
virtual FString ToString () const override
Public Member Functions inherited from FLocMetadataValue
virtual ~FLocMetadataValue ()=0
virtual TArray< TSharedPtr< FLocMetadataValue > > AsArray ()
Returns this value as an array, throwing an error if this is not an Metadata Array.
virtual TSharedPtr< FLocMetadataObject > AsObject ()
Returns this value as an object, throwing an error if this is not an Metadata Object.
virtual FString AsString ()
Returns this value as a string, throwing an error if this is not a Metadata String.
bool operator< (const FLocMetadataValue &Other) const
bool operator== (const FLocMetadataValue &Other) const
Static Public Member Functions
static void Serialize (FLocMetadataValueBoolean &Value, FStructuredArchive::FSlot Slot)
Protected Member Functions
virtual bool EqualTo (const FLocMetadataValue &Other) const override
virtual FString GetTypeString () const override
virtual bool LessThan (const FLocMetadataValue &Other) const override
Protected Member Functions inherited from FLocMetadataValue
FLocMetadataValue ()
void ErrorMessage (const FString &InType)
Protected Attributes
bool Value
Detailed Description
A LocMetadata Boolean Value.
Definition at line 208 of file InternationalizationMetadata.h.
Constructor & Destructor Documentation
FLocMetadataValueBoolean() [1/2]
FLocMetadataValueBoolean::FLocMetadataValueBoolean (bool InBool) inline
Definition at line 211 of file InternationalizationMetadata.h.
References Value.
Referenced by Serialize().
FLocMetadataValueBoolean() [2/2]
FLocMetadataValueBoolean::FLocMetadataValueBoolean (FStructuredArchive::FSlot Slot)
Member Function Documentation
AsBool()
virtual bool FLocMetadataValueBoolean::AsBool () inline override virtual
Returns this value as a boolean, throwing an error if this is not an Metadata Bool.
Reimplemented from FLocMetadataValue.
Definition at line 215 of file InternationalizationMetadata.h.
References Value.
Clone()
virtual TSharedRef< FLocMetadataValue > FLocMetadataValueBoolean::Clone () const override virtual
Implements FLocMetadataValue.
EqualTo()
virtual bool FLocMetadataValueBoolean::EqualTo (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
GetType()
virtual ELocMetadataType FLocMetadataValueBoolean::GetType () const inline override virtual
Implements FLocMetadataValue.
Definition at line 221 of file InternationalizationMetadata.h.
References Boolean.
GetTypeString()
virtual FString FLocMetadataValueBoolean::GetTypeString () const inline override protected virtual
Implements FLocMetadataValue.
Definition at line 229 of file InternationalizationMetadata.h.
References TEXT.
LessThan()
virtual bool FLocMetadataValueBoolean::LessThan (const FLocMetadataValue & Other) const override protected virtual
Implements FLocMetadataValue.
References FLocMetadataValue::FLocMetadataValue(), and Other.
Serialize()
void FLocMetadataValueBoolean::Serialize (FLocMetadataValueBoolean & Value, FStructuredArchive::FSlot Slot) static
References FLocMetadataValueBoolean(), and Value.
ToString()
virtual FString FLocMetadataValueBoolean::ToString () const inline override virtual
Implements FLocMetadataValue.
Definition at line 219 of file InternationalizationMetadata.h.
References TEXT, and Value.
Field Documentation
Value
bool FLocMetadataValueBoolean::Value protected
Definition at line 224 of file InternationalizationMetadata.h.
Referenced by FLocMetadataValueBoolean(), AsBool(), Serialize(), and ToString().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/InternationalizationMetadata.h