Unreal Engine 5.6 C++ API: UE::Geometry::TCachingMeshSDF< TriangleMeshType > Class Template Reference
UE::Geometry::TCachingMeshSDF< TriangleMeshType > Class Template Reference
This is variant of TSweepingMeshSDF that does lazy evaluation of actual Distances, using mesh spatial data structure.
#include "CachingMeshSDF.h"
Public Types
enum EInsideModes { CrossingCount = 0 , WindingCount = 1 }
Public Member Functions
TCachingMeshSDF (const TriangleMeshType *MeshIn, float CellSizeIn, const TMeshAABBTree3< TriangleMeshType > *SpatialIn, bool bAutoBuild)
TCachingMeshSDF (float CellSizeIn=10)
float At (int I, int J, int K) const
FVector3f CellCenter (int I, int J, int K)
void CleanupUnwanted ()
FVector3i Dimensions ()
const FDenseGrid3i & GetClosestTriGrid () const
const FDenseGrid3f & GetGrid () const
SDF Grid available after calling Compute()
const FVector3f & GetGridOrigin () const
Origin of the SDF Grid, in same coordinates as mesh.
const FDenseGrid3i & GetIntersectionsGrid () const
float GetValue (FVector3i Idx)
void Initialize ()
TTriLinearGridInterpolant< TCachingMeshSDF > MakeInterpolant ()
constexpr const float operator[] (FVector3i Idx) const
bool Validate ()
Static Public Member Functions
static int Orientation (double X1, double Y1, double X2, double Y2, double &TwiceSignedArea)
static bool PointInTriangle2d (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3, double &A, double &B, double &C)
Data Fields
int ApproxMaxCellsPerDimension = 4096
bool bComputeSigns = true
bool bUseParallel = true
bool bWantClosestTriGrid = false
bool bWantIntersectionsGrid = false
TFunction< bool(void)> CancelF = []() { return false; }
if this function returns true, we should abort calculation
float CellSize
FDenseGrid3i ClosestTriGrid
FVector3d ExpandBounds = FVector3d::Zero()
FDenseGrid3f Grid
FVector3f GridOrigin
EInsideModes InsideMode = EInsideModes::WindingCount
FDenseGrid3i IntersectionsGrid
float MaxOffsetDistance = 0
const TriangleMeshType * Mesh
const TMeshAABBTree3< TriangleMeshType > * Spatial
Protected Attributes
double MaxDistQueryDist
float UpperBoundDistance
Private Member Functions
FVector3f cell_center (const FVector3i &IJK)
void compute_intersections (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FDenseGrid3i &IntersectionCount)
void compute_signs (int NI, int NJ, int NK, FDenseGrid3f &Distances, FDenseGrid3i &IntersectionCount)
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TCachingMeshSDF< TriangleMeshType >
This is variant of TSweepingMeshSDF that does lazy evaluation of actual Distances, using mesh spatial data structure.
This is much faster if we are doing continuation-method marching cubes as only values on surface will be computed!
Compute discretely-sampled (I.e. gridded) signed distance field for a mesh only within a narrow band of the surface (within MaxDistQueryDist = MaxOffsetDistance + (2 * CellSize * FMathf::Sqrt2))
This code is based on the implementation found at https://github.com/christopherbatty/SDFGen
Definition at line 34 of file CachingMeshSDF.h.
Member Enumeration Documentation
EInsideModes
template<class TriangleMeshType> enum UE::Geometry::TCachingMeshSDF::EInsideModes
Enumerator
CrossingCount
WindingCount
Definition at line 66 of file CachingMeshSDF.h.
Constructor & Destructor Documentation
TCachingMeshSDF() [1/2]
template<class TriangleMeshType> UE::Geometry::TCachingMeshSDF< TriangleMeshType >::TCachingMeshSDF (float CellSizeIn = 10) inline
Definition at line 91 of file CachingMeshSDF.h.
References CellSize, Mesh, and Spatial.
TCachingMeshSDF() [2/2]
template<class TriangleMeshType> UE::Geometry::TCachingMeshSDF< TriangleMeshType >::TCachingMeshSDF (const TriangleMeshType * MeshIn, float CellSizeIn, const TMeshAABBTree3< TriangleMeshType > * SpatialIn, bool bAutoBuild) inline
Definition at line 95 of file CachingMeshSDF.h.
References CellSize, Initialize(), Mesh, and Spatial.
Member Function Documentation
At()
template<class TriangleMeshType> float UE::Geometry::TCachingMeshSDF< TriangleMeshType >::At (int I, int J, int K) const inline
Definition at line 280 of file CachingMeshSDF.h.
References Grid.
cell_center()
template<class TriangleMeshType> FVector3f UE::Geometry::TCachingMeshSDF< TriangleMeshType >::cell_center (const FVector3i & IJK) inline private
Definition at line 296 of file CachingMeshSDF.h.
References CellSize, GridOrigin, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by CellCenter(), and GetValue().
CellCenter()
template<class TriangleMeshType> FVector3f UE::Geometry::TCachingMeshSDF< TriangleMeshType >::CellCenter (int I, int J, int K) inline
Definition at line 290 of file CachingMeshSDF.h.
References cell_center().
CleanupUnwanted()
template<class TriangleMeshType> void UE::Geometry::TCachingMeshSDF< TriangleMeshType >::CleanupUnwanted () inline
Definition at line 197 of file CachingMeshSDF.h.
References bWantIntersectionsGrid, and IntersectionsGrid.
Referenced by Initialize().
compute_intersections()
template<class TriangleMeshType> void UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections (FVector3f Origin, float DX, int32 NI, int32 NJ, int32 NK, FDenseGrid3i & IntersectionCount) inline private
Definition at line 304 of file CachingMeshSDF.h.
References A, UE::Geometry::DenseGrid::AtomicIncDec(), B, FMath::Clamp(), InsideMode, FMath::Max3(), Mesh, FMath::Min3(), UE::Geometry::VectorUtil::NormalDirection(), UE::Geometry::Origin, ParallelFor(), PointInTriangle2d(), WindingCount, UE::Math::TVector< T >::X, and UE::Math::TVector< double >::Zero().
Referenced by Initialize().
compute_signs()
template<class TriangleMeshType> void UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_signs (int NI, int NJ, int NK, FDenseGrid3f & Distances, FDenseGrid3i & IntersectionCount) inline private
Definition at line 382 of file CachingMeshSDF.h.
References UE::Geometry::TDenseGrid3< ElemType >::At(), bUseParallel, CancelF, CrossingCount, InsideMode, ParallelFor(), and WindingCount.
Referenced by Initialize().
Dimensions()
template<class TriangleMeshType> FVector3i UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Dimensions () inline
Definition at line 246 of file CachingMeshSDF.h.
References Grid.
Referenced by MakeInterpolant().
GetClosestTriGrid()
template<class TriangleMeshType> const FDenseGrid3i & UE::Geometry::TCachingMeshSDF< TriangleMeshType >::GetClosestTriGrid () const inline
Definition at line 268 of file CachingMeshSDF.h.
References bWantClosestTriGrid, checkf, ClosestTriGrid, and TEXT.
GetGrid()
template<class TriangleMeshType> const FDenseGrid3f & UE::Geometry::TCachingMeshSDF< TriangleMeshType >::GetGrid () const inline
SDF Grid available after calling Compute()
Definition at line 254 of file CachingMeshSDF.h.
References Grid.
GetGridOrigin()
template<class TriangleMeshType> const FVector3f & UE::Geometry::TCachingMeshSDF< TriangleMeshType >::GetGridOrigin () const inline
Origin of the SDF Grid, in same coordinates as mesh.
Definition at line 262 of file CachingMeshSDF.h.
References GridOrigin.
GetIntersectionsGrid()
template<class TriangleMeshType> const FDenseGrid3i & UE::Geometry::TCachingMeshSDF< TriangleMeshType >::GetIntersectionsGrid () const inline
Definition at line 274 of file CachingMeshSDF.h.
References bWantIntersectionsGrid, checkf, IntersectionsGrid, and TEXT.
GetValue()
template<class TriangleMeshType> float UE::Geometry::TCachingMeshSDF< TriangleMeshType >::GetValue (FVector3i Idx) inline
Definition at line 206 of file CachingMeshSDF.h.
References bWantClosestTriGrid, cell_center(), ClosestTriGrid, float, Grid, IndexConstants::InvalidID, MaxDistQueryDist, Spatial, TMathUtil< double >::Sqrt(), and UpperBoundDistance.
Initialize()
template<class TriangleMeshType> void UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize () inline
Definition at line 132 of file CachingMeshSDF.h.
References ApproxMaxCellsPerDimension, UE::Geometry::TDenseGrid3< ElemType >::Assign(), bComputeSigns, bWantClosestTriGrid, CancelF, CellSize, CleanupUnwanted(), ClosestTriGrid, compute_intersections(), compute_signs(), ensure, ensureMsgf, ExpandBounds, float, Grid, GridOrigin, IntersectionsGrid, FMath::Max, UE::Geometry::TAxisAlignedBox3< RealType >::Max, MaxDistQueryDist, UE::Geometry::MaxElement(), MaxOffsetDistance, UE::Geometry::TAxisAlignedBox3< RealType >::Min, UE::Math::TVector< float >::One(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), Spatial, TMathUtilConstants< float >::Sqrt2, TEXT, UpperBoundDistance, Validate(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by TCachingMeshSDF().
MakeInterpolant()
template<class TriangleMeshType> TTriLinearGridInterpolant< TCachingMeshSDF > UE::Geometry::TCachingMeshSDF< TriangleMeshType >::MakeInterpolant () inline
Definition at line 239 of file CachingMeshSDF.h.
References CellSize, Dimensions(), and GridOrigin.
operator[]()
template<class TriangleMeshType> const float UE::Geometry::TCachingMeshSDF< TriangleMeshType >::operator[] (FVector3i Idx) const inline constexpr
Definition at line 285 of file CachingMeshSDF.h.
References Grid.
Orientation()
template<class TriangleMeshType> int UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Orientation (double X1, double Y1, double X2, double Y2, double & TwiceSignedArea) inline static
Definition at line 443 of file CachingMeshSDF.h.
PointInTriangle2d()
template<class TriangleMeshType> bool UE::Geometry::TCachingMeshSDF< TriangleMeshType >::PointInTriangle2d (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3, double & A, double & B, double & C) inline static
Definition at line 458 of file CachingMeshSDF.h.
References A, B, checkf, UE::Geometry::Orientation(), and TEXT.
Referenced by compute_intersections().
Validate()
template<class TriangleMeshType> bool UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Validate () inline
Definition at line 113 of file CachingMeshSDF.h.
References ApproxMaxCellsPerDimension, CellSize, UE::Geometry::TAxisAlignedBox3< RealType >::IsEmpty(), UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), and Spatial.
Referenced by Initialize().
Field Documentation
ApproxMaxCellsPerDimension
template<class TriangleMeshType> int UE::Geometry::TCachingMeshSDF< TriangleMeshType >::ApproxMaxCellsPerDimension = 4096
Definition at line 58 of file CachingMeshSDF.h.
Referenced by Initialize(), and Validate().
bComputeSigns
template<class TriangleMeshType> bool UE::Geometry::TCachingMeshSDF< TriangleMeshType >::bComputeSigns = true
Definition at line 55 of file CachingMeshSDF.h.
Referenced by Initialize().
bUseParallel
template<class TriangleMeshType> bool UE::Geometry::TCachingMeshSDF< TriangleMeshType >::bUseParallel = true
Definition at line 52 of file CachingMeshSDF.h.
Referenced by compute_signs().
bWantClosestTriGrid
template<class TriangleMeshType> bool UE::Geometry::TCachingMeshSDF< TriangleMeshType >::bWantClosestTriGrid = false
Definition at line 75 of file CachingMeshSDF.h.
Referenced by GetClosestTriGrid(), GetValue(), and Initialize().
bWantIntersectionsGrid
template<class TriangleMeshType> bool UE::Geometry::TCachingMeshSDF< TriangleMeshType >::bWantIntersectionsGrid = false
Definition at line 78 of file CachingMeshSDF.h.
Referenced by CleanupUnwanted(), and GetIntersectionsGrid().
CancelF
template<class TriangleMeshType> TFunction<bool(void)> UE::Geometry::TCachingMeshSDF< TriangleMeshType >::CancelF = []() { return false; }
if this function returns true, we should abort calculation
Definition at line 81 of file CachingMeshSDF.h.
Referenced by compute_signs(), and Initialize().
CellSize
template<class TriangleMeshType> float UE::Geometry::TCachingMeshSDF< TriangleMeshType >::CellSize
Definition at line 42 of file CachingMeshSDF.h.
Referenced by TCachingMeshSDF(), TCachingMeshSDF(), cell_center(), Initialize(), MakeInterpolant(), and Validate().
ClosestTriGrid
template<class TriangleMeshType> FDenseGrid3i UE::Geometry::TCachingMeshSDF< TriangleMeshType >::ClosestTriGrid
Definition at line 88 of file CachingMeshSDF.h.
Referenced by GetClosestTriGrid(), GetValue(), and Initialize().
ExpandBounds
template<class TriangleMeshType> FVector3d UE::Geometry::TCachingMeshSDF< TriangleMeshType >::ExpandBounds = FVector3d::Zero()
Definition at line 46 of file CachingMeshSDF.h.
Referenced by Initialize().
Grid
template<class TriangleMeshType> FDenseGrid3f UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Grid
Definition at line 87 of file CachingMeshSDF.h.
Referenced by At(), Dimensions(), GetGrid(), GetValue(), Initialize(), and operator[]().
GridOrigin
template<class TriangleMeshType> FVector3f UE::Geometry::TCachingMeshSDF< TriangleMeshType >::GridOrigin
Definition at line 86 of file CachingMeshSDF.h.
Referenced by cell_center(), GetGridOrigin(), Initialize(), and MakeInterpolant().
InsideMode
template<class TriangleMeshType> EInsideModes UE::Geometry::TCachingMeshSDF< TriangleMeshType >::InsideMode = EInsideModes::WindingCount
Definition at line 71 of file CachingMeshSDF.h.
Referenced by compute_intersections(), and compute_signs().
IntersectionsGrid
template<class TriangleMeshType> FDenseGrid3i UE::Geometry::TCachingMeshSDF< TriangleMeshType >::IntersectionsGrid
Definition at line 89 of file CachingMeshSDF.h.
Referenced by CleanupUnwanted(), GetIntersectionsGrid(), and Initialize().
MaxDistQueryDist
template<class TriangleMeshType> double UE::Geometry::TCachingMeshSDF< TriangleMeshType >::MaxDistQueryDist protected
Definition at line 109 of file CachingMeshSDF.h.
Referenced by GetValue(), and Initialize().
MaxOffsetDistance
template<class TriangleMeshType> float UE::Geometry::TCachingMeshSDF< TriangleMeshType >::MaxOffsetDistance = 0
Definition at line 49 of file CachingMeshSDF.h.
Referenced by Initialize().
Mesh
template<class TriangleMeshType> const TriangleMeshType* UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Mesh
Definition at line 40 of file CachingMeshSDF.h.
Referenced by TCachingMeshSDF(), TCachingMeshSDF(), and compute_intersections().
Spatial
template<class TriangleMeshType> const TMeshAABBTree3<TriangleMeshType>* UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Spatial
Definition at line 41 of file CachingMeshSDF.h.
Referenced by TCachingMeshSDF(), TCachingMeshSDF(), GetValue(), Initialize(), and Validate().
UpperBoundDistance
template<class TriangleMeshType> float UE::Geometry::TCachingMeshSDF< TriangleMeshType >::UpperBoundDistance protected
Definition at line 108 of file CachingMeshSDF.h.
Referenced by GetValue(), and Initialize().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Implicit/CachingMeshSDF.h