Unreal Engine 5.6 C++ API: UE::Sequencer::IGroupableExtension Class Reference
UE::Sequencer::IGroupableExtension Class Reference abstract
#include "IGroupableExtension.h"
Public Member Functions
FString GetIdentifierForGrouping () const
virtual void GetIdentifierForGrouping (TStringBuilder< 128 > &OutString) const =0
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGroupableExtension) virtual ~IGroupableExtension()
Detailed Description
Definition at line 16 of file IGroupableExtension.h.
Member Function Documentation
GetIdentifierForGrouping() [1/2]
FString UE::Sequencer::IGroupableExtension::GetIdentifierForGrouping () const inline
Definition at line 26 of file IGroupableExtension.h.
References GetIdentifierForGrouping(), and TStringBuilderBase< CharType >::ToString().
GetIdentifierForGrouping() [2/2]
virtual void UE::Sequencer::IGroupableExtension::GetIdentifierForGrouping (TStringBuilder< 128 > & OutString) const pure virtual
Implemented in UE::Sequencer::FFolderModel, UE::Sequencer::FObjectBindingModel, and UE::Sequencer::FTrackModel.
Referenced by GetIdentifierForGrouping().
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID()
UE::Sequencer::IGroupableExtension::UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGroupableExtension) inline
Definition at line 20 of file IGroupableExtension.h.
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/IGroupableExtension.h