Unreal Engine 5.6 C++ API: FComponentRecreateRenderStateContext Class Reference
FComponentRecreateRenderStateContext Class Reference
Destroys render state for a component and then recreates it when this object is destroyed.
#include "ComponentRecreateRenderStateContext.h"
Public Member Functions
FComponentRecreateRenderStateContext (const FComponentRecreateRenderStateContext &)=delete
FComponentRecreateRenderStateContext (FComponentRecreateRenderStateContext &&Other)
FComponentRecreateRenderStateContext (IPrimitiveComponent *InComponentInterface, TSet< FSceneInterface * > *InScenesToUpdateAllPrimitiveSceneInfos=nullptr)
FComponentRecreateRenderStateContext (UActorComponent *InComponent, TSet< FSceneInterface * > *InScenesToUpdateAllPrimitiveSceneInfos=nullptr)
~FComponentRecreateRenderStateContext ()
FComponentRecreateRenderStateContext & operator= (const FComponentRecreateRenderStateContext &)=delete
FComponentRecreateRenderStateContext & operator= (FComponentRecreateRenderStateContext &&Other)
Private Attributes
UActorComponent * Component = nullptr
Pointer to component we are recreating render state for.
IPrimitiveComponent * ComponentInterface = nullptr
TSet< FSceneInterface * > * ScenesToUpdateAllPrimitiveSceneInfos = nullptr
Detailed Description
Destroys render state for a component and then recreates it when this object is destroyed.
Definition at line 12 of file ComponentRecreateRenderStateContext.h.
Constructor & Destructor Documentation
FComponentRecreateRenderStateContext() [1/4]
FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext (IPrimitiveComponent * InComponentInterface, TSet< FSceneInterface * > * InScenesToUpdateAllPrimitiveSceneInfos = nullptr) inline
Definition at line 22 of file ComponentRecreateRenderStateContext.h.
References check, checkf, ComponentInterface, IPrimitiveComponent::DestroyRenderState(), IPrimitiveComponent::GetFullName(), IPrimitiveComponent::IsRegistered(), IPrimitiveComponent::IsRenderStateCreated(), IPrimitiveComponent::IsUnreachable(), ScenesToUpdateAllPrimitiveSceneInfos, TEXT, and UpdateAllPrimitiveSceneInfosForSingleComponentInterface().
Referenced by FComponentRecreateRenderStateContext(), FComponentRecreateRenderStateContext(), operator=(), and operator=().
FComponentRecreateRenderStateContext() [2/4]
FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext (UActorComponent * InComponent, TSet< FSceneInterface * > * InScenesToUpdateAllPrimitiveSceneInfos = nullptr) inline
Definition at line 37 of file ComponentRecreateRenderStateContext.h.
References check, checkf, Component, UActorComponent::DestroyRenderState_Concurrent(), UObjectBaseUtility::GetFullName(), UActorComponent::IsRegistered(), UActorComponent::IsRenderStateCreated(), UObjectBaseUtility::IsUnreachable(), ScenesToUpdateAllPrimitiveSceneInfos, TEXT, and UpdateAllPrimitiveSceneInfosForSingleComponent().
FComponentRecreateRenderStateContext() [3/4]
FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext (const FComponentRecreateRenderStateContext &) delete
References FComponentRecreateRenderStateContext().
FComponentRecreateRenderStateContext() [4/4]
FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext (FComponentRecreateRenderStateContext && Other) inline
Definition at line 55 of file ComponentRecreateRenderStateContext.h.
References FComponentRecreateRenderStateContext(), Component, ComponentInterface, Other, and ScenesToUpdateAllPrimitiveSceneInfos.
~FComponentRecreateRenderStateContext()
FComponentRecreateRenderStateContext::~FComponentRecreateRenderStateContext ()
Member Function Documentation
operator=() [1/2]
FComponentRecreateRenderStateContext & FComponentRecreateRenderStateContext::operator= (const FComponentRecreateRenderStateContext &) delete
References FComponentRecreateRenderStateContext().
operator=() [2/2]
FComponentRecreateRenderStateContext & FComponentRecreateRenderStateContext::operator= (FComponentRecreateRenderStateContext && Other) inline
Definition at line 65 of file ComponentRecreateRenderStateContext.h.
References FComponentRecreateRenderStateContext(), Component, ComponentInterface, Other, and ScenesToUpdateAllPrimitiveSceneInfos.
Field Documentation
Component
UActorComponent* FComponentRecreateRenderStateContext::Component = nullptr private
Pointer to component we are recreating render state for.
Definition at line 16 of file ComponentRecreateRenderStateContext.h.
Referenced by FComponentRecreateRenderStateContext(), FComponentRecreateRenderStateContext(), and operator=().
ComponentInterface
IPrimitiveComponent* FComponentRecreateRenderStateContext::ComponentInterface = nullptr private
Definition at line 17 of file ComponentRecreateRenderStateContext.h.
Referenced by FComponentRecreateRenderStateContext(), FComponentRecreateRenderStateContext(), and operator=().
ScenesToUpdateAllPrimitiveSceneInfos
TSet<FSceneInterface*>* FComponentRecreateRenderStateContext::ScenesToUpdateAllPrimitiveSceneInfos = nullptr private
Definition at line 19 of file ComponentRecreateRenderStateContext.h.
Referenced by FComponentRecreateRenderStateContext(), FComponentRecreateRenderStateContext(), FComponentRecreateRenderStateContext(), and operator=().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ComponentRecreateRenderStateContext.h