Unreal Engine 5.6 C++ API: FShaderPipeline Class Reference
FShaderPipeline Class Reference
#include "Shader.h"
Public Types
enum EFilter { EAll , EOnlyShared , EOnlyUnique }
Public Member Functions
FShaderPipeline (const FShaderPipelineType *InType)
RENDERCORE_API ~FShaderPipeline ()
RENDERCORE_API void AddShader (FShader *Shader, int32 PermutationId)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API FShader * FindOrAddShader (FShader *Shader, int32 PermutationId)
uint32 GetNumShaders () const
template<typename ShaderType>
ShaderType * GetShader (const FShaderMapPointerTable &InPtrTable)
FShader * GetShader (EShaderFrequency Frequency)
const FShader * GetShader (EShaderFrequency Frequency) const
TArray< TShaderRef< FShader > > GetShaders (const FShaderMapBase &InShaderMap) const
LAYOUT_ARRAY (int32, PermutationIds, SF_NumGraphicsFrequencies)
LAYOUT_ARRAY (TMemoryImagePtr< FShader >, Shaders, SF_NumGraphicsFrequencies)
LAYOUT_FIELD (FHashedName, TypeName)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal) const
Saves stable keys for the shaders in the pipeline.
RENDERCORE_API void Validate (const FShaderPipelineType *InPipelineType) const
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderPipeline, RENDERCORE_API, NonVirtual)
Detailed Description
Definition at line 2211 of file Shader.h.
Member Enumeration Documentation
EFilter
enum FShaderPipeline::EFilter
Enumerator
EAll
EOnlyShared
EOnlyUnique
Definition at line 2280 of file Shader.h.
Constructor & Destructor Documentation
FShaderPipeline()
FShaderPipeline::FShaderPipeline (const FShaderPipelineType * InType) inline explicit
Definition at line 2215 of file Shader.h.
References FMemory::Memzero().
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT().
~FShaderPipeline()
RENDERCORE_API FShaderPipeline::~FShaderPipeline ()
Member Function Documentation
AddShader()
RENDERCORE_API void FShaderPipeline::AddShader (FShader * Shader, int32 PermutationId)
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderPipeline::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderPipeline , RENDERCORE_API , NonVirtual) private
References FShaderPipeline().
Finalize()
RENDERCORE_API void FShaderPipeline::Finalize (const FShaderMapResourceCode * Code)
FindOrAddShader()
RENDERCORE_API FShader * FShaderPipeline::FindOrAddShader (FShader * Shader, int32 PermutationId)
GetNumShaders()
uint32 FShaderPipeline::GetNumShaders () const inline
Definition at line 2221 of file Shader.h.
References IsValid().
GetShader() [1/3]
template<typename ShaderType> ShaderType * FShaderPipeline::GetShader (const FShaderMapPointerTable & InPtrTable) inline
Definition at line 2236 of file Shader.h.
References Frequency, FShader::GetType(), and IsValid().
GetShader() [2/3]
FShader * FShaderPipeline::GetShader (EShaderFrequency Frequency) inline
Definition at line 2251 of file Shader.h.
References check, and Frequency.
GetShader() [3/3]
const FShader * FShaderPipeline::GetShader (EShaderFrequency Frequency) const inline
Definition at line 2257 of file Shader.h.
References check, and Frequency.
GetShaders()
TArray< TShaderRef< FShader > > FShaderPipeline::GetShaders (const FShaderMapBase & InShaderMap) const inline
Definition at line 2263 of file Shader.h.
References IsValid().
LAYOUT_ARRAY() [1/2]
FShaderPipeline::LAYOUT_ARRAY (int32 , PermutationIds , SF_NumGraphicsFrequencies)
LAYOUT_ARRAY() [2/2]
FShaderPipeline::LAYOUT_ARRAY (TMemoryImagePtr< FShader > , Shaders , SF_NumGraphicsFrequencies)
LAYOUT_FIELD()
FShaderPipeline::LAYOUT_FIELD (FHashedName , TypeName)
SaveShaderStableKeys()
RENDERCORE_API void FShaderPipeline::SaveShaderStableKeys (const FShaderMapPointerTable & InPtrTable, EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue & SaveKeyVal) const
Saves stable keys for the shaders in the pipeline.
Validate()
RENDERCORE_API void FShaderPipeline::Validate (const FShaderPipelineType * InPipelineType) const
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h