Unreal Engine 5.6 C++ API: FDebugRenderSceneProxy Class Reference
FDebugRenderSceneProxy Class Reference
#include "DebugRenderSceneProxy.h"
Data Structures
struct FArrowLine
Struct to hold info about arrowed lines to render.
struct FCapsule
struct FCircle
Struct to hold info about circles to render.
struct FCone
struct FCoordinateSystem
struct FDashedLine
Struct to gold info about dashed lines to render.
struct FDebugBox
Struct to hold info about boxes to render.
struct FDebugLine
Struct to hold info about lines to render.
struct FMaterialCache
struct FMesh
struct FSphere
Struct to hold info about spheres to render.
struct FText3d
Struct to hold info about texts to render using 3d coordinates.
struct FWireCylinder
Struct to hold info about cylinders to render.
struct FWireStar
Struct to hold info about lined stars to render.
Public Types
enum EDrawType { SolidMesh = 0 , WireMesh = 1 , SolidAndWireMeshes = 2 , Invalid = 3 }
Public Types inherited from FPrimitiveSceneProxy
enum class EInstanceBufferAccessFlags { SynchronizeUpdateTask , UnsynchronizedAndUnsafe }
typedef TArray< class FLightCacheInterface *, TInlineAllocator< 8 > > FLCIArray
Get the list of LCIs.
Public Member Functions
FDebugRenderSceneProxy (const UPrimitiveComponent *InComponent)
FDebugRenderSceneProxy (FDebugRenderSceneProxy const &)
virtual ~FDebugRenderSceneProxy ()
void DrawLineArrow (FPrimitiveDrawInterface *PDI, const FVector &Start, const FVector &End, const FColor &Color, float Mag) const
Draws a line with an arrow at the end.
uint32 GetAllocatedSize (void) const
virtual void GetDynamicMeshElements (const TArray< const FSceneView * > &Views, const FSceneViewFamily &ViewFamily, uint32 VisibilityMap, FMeshElementCollector &Collector) const override
Draw the scene proxy as a dynamic element.
virtual uint32 GetMemoryFootprint (void) const override
Every derived class should override these functions.
SIZE_T GetTypeHash () const override
Return a type (or subtype) specific hash for sorting purposes.
Public Member Functions inherited from FPrimitiveSceneProxy
FPrimitiveSceneProxy (const FPrimitiveSceneProxyDesc &InDesc, FName ResourceName=NAME_None)
FPrimitiveSceneProxy (const UPrimitiveComponent *InComponent, FName ResourceName=NAME_None)
Initialization constructor.
FPrimitiveSceneProxy (FPrimitiveSceneProxy const &)
Copy constructor.
virtual ~FPrimitiveSceneProxy ()
Virtual destructor.
virtual void AcceptOcclusionResults (const FSceneView *View, TArray< bool > *Results, int32 ResultsStart, int32 NumResults)
Gives the primitive the results of sub-occlusion-queries.
bool AffectsDistanceFieldLighting () const
bool AffectsDynamicIndirectLighting () const
bool AffectsIndirectLightingWhileHidden () const
bool AllowApproximateOcclusion () const
virtual bool AllowInstanceCullingOcclusionQueries () const
bool AlwaysHasVelocity () const
Returns true if this proxy should write velocity even when the transform isn't changing.
bool AnyMaterialAlwaysEvaluatesWorldPositionOffset () const
bool AnyMaterialHasPixelAnimation () const
bool AnyMaterialHasWorldPositionOffset () const
virtual void ApplyLateUpdateTransform (FRHICommandListBase &RHICmdList, const FMatrix &LateUpdateTransform)
Applies a "late in the frame" adjustment to the proxy's existing transform.
virtual void ApplyViewDependentMeshArguments (const FSceneView &View, FMeshBatch &ViewDependentMeshBatch) const
Gives the primitive an opportunity to override MeshBatch arguments for a specific View Only called for a MeshBatch with a bViewDependentArguments property set.
virtual void ApplyWorldOffset (FRHICommandListBase &RHICmdList, FVector InOffset)
Shifts primitive position and all relevant data by an arbitrary delta.
void BuildUniformShaderParameters (FPrimitiveUniformShaderParametersBuilder &Builder) const
Apply the unform shader parameter settings for the proxy to the builder.
virtual bool CanBeOccluded () const
bool CanSkipRedundantTransformUpdates () const
bool CastsCapsuleDirectShadow () const
bool CastsCinematicShadow () const
bool CastsContactShadow () const
bool CastsDeepShadow () const
bool CastsDynamicIndirectShadow () const
bool CastsDynamicShadow () const
bool CastsFarShadow () const
bool CastsHiddenShadow () const
bool CastsInsetShadow () const
bool CastsSelfShadowOnly () const
bool CastsShadowAsTwoSided () const
bool CastsStaticShadow () const
bool CastsVolumetricTranslucentShadow () const
virtual HHitProxy * CreateHitProxies (IPrimitiveComponent *ComponentInterface, TArray< TRefCountPtr< HHitProxy > > &OutHitProxies)
Creates the hit proxies are used when DrawDynamicElements is called.
virtual HHitProxy * CreateHitProxies (UPrimitiveComponent *Component, TArray< TRefCountPtr< HHitProxy > > &OutHitProxies)
All FPrimitiveSceneProxy derived classes can decide to fully override the HHitProxy creation, or add their own and call any of their base classes to add theirs.
virtual void CreateRenderThreadResources (FRHICommandListBase &RHICmdList)
Called when the rendering thread adds the proxy to the scene.
virtual void DestroyRenderThreadResources ()
Called when the rendering thread removes the proxy from the scene.
bool DoesMeshBatchesUseSceneInstanceCount () const
Returns true to inform scene update that the mesh batches produced makes use of the (GPU)Scene instance count, and thus don't require recaching if the instance count changed.
bool DoesVFRequirePrimitiveUniformBuffer () const
virtual void DrawStaticElements (FStaticPrimitiveDrawInterface *PDI)
Draws the primitive's static elements.
bool DrawsVelocity () const
Returns true if this proxy can write velocity.
bool EvaluateWorldPositionOffset () const
virtual void GatherSimpleLights (const FSceneViewFamily &ViewFamily, FSimpleLightArray &OutParticleLights) const
Callback from the renderer to gather simple lights that this proxy wants renderered.
float GetAbsMaxDisplacement () const
const FVector & GetActorPosition () const
SIZE_T GetAllocatedSize (void) const
const FBoxSphereBounds & GetBounds () const
virtual uint8 GetCurrentFirstLODIdx_RenderThread () const
uint8 GetCustomDepthStencilValue () const
virtual const FColorVertexBuffer * GetCustomHitProxyIdBuffer () const
Allows a scene proxy to override hit proxy ids and generate more than one hit proxy id per draw call Useful for sub-section selection (faces, vertices, bones, etc)
virtual FBoxSphereBounds GetCustomOcclusionBounds () const
Return the custom occlusion bounds for this scene proxy.
const FCustomPrimitiveData * GetCustomPrimitiveData () const
Get the custom primitive data for this scene proxy.
ESceneDepthPriorityGroup GetDepthPriorityGroup (const FSceneView *View) const
Determines the DPG to render the primitive in for the given view.
virtual FDesiredLODLevel GetDesiredLODLevel_RenderThread (const FSceneView *View) const
virtual void GetDistanceFieldAtlasData (const class FDistanceFieldVolumeData *&OutDistanceFieldData, float &SelfShadowBias) const
float GetDynamicIndirectShadowMinVisibility () const
virtual float GetGpuLodInstanceRadius () const
Returns the instance radius to use for per instance GPU LOD calculation.
virtual void GetHeightfieldRepresentation (UTexture2D *&OutHeightmapTexture, UTexture2D *&OutVisibilityTexture, FHeightfieldComponentDescription &OutDescription) const
EIndirectLightingCacheQuality GetIndirectLightingCacheQuality () const
FInstanceDataBufferHeader GetInstanceDataHeader () const
virtual FInstanceDataUpdateTaskInfo * GetInstanceDataUpdateTaskInfo () const
Return a pointer to a class that can be used to guard access to instance data that is being updated by a task.
virtual bool GetInstanceDrawDistanceMinMax (FVector2f &OutDistanceMinMax) const
Retrieves the instance draw distance range (mostly only used by objects whose instances are culled on the GPU)
const FInstanceSceneDataBuffers * GetInstanceSceneDataBuffers (EInstanceBufferAccessFlags AccessFlags=EInstanceBufferAccessFlags::SynchronizeUpdateTask) const
Get the instance data view, which may be null for uninstanced primitives.
virtual bool GetInstanceWorldPositionOffsetDisableDistance (float &OutWPODisableDistance) const
Retrieves the per-instance world position offset disable distance.
virtual void GetLCIs (FLCIArray &LCIs)
FName GetLevelName () const
uint8 GetLightingChannelMask () const
uint8 GetLightingChannelStencilValue () const
virtual int32 GetLightMapCoordinateIndex () const
Get the lightmap UV coordinate index for this primitive.
virtual int32 GetLightMapResolution () const
Get the lightmap resolution for this primitive.
ELightmapType GetLightmapType () const
virtual void GetLightRelevance (const FLightSceneProxy *LightSceneProxy, bool &bDynamic, bool &bRelevant, bool &bLightMapped, bool &bShadowMapped) const
Determines the relevance of this primitive's elements to the given light.
const FBoxSphereBounds & GetLocalBounds () const
const FMatrix & GetLocalToWorld () const
virtual int32 GetLOD (const FSceneView *View) const
Returns the LOD that the primitive will render at for this view.
virtual float GetLodScreenSizeScale () const
Returns a scale to apply to ScreenSize used in LOD calculation.
virtual FUintVector2 GetMaterialCacheTextureDescriptor () const
float GetMaxDrawDistance () const
float GetMaxWorldPositionOffsetExtent () const
virtual const class FCardRepresentationData * GetMeshCardRepresentation () const
virtual void GetMeshDescription (int32 LODIndex, TArray< FMeshBatch > &OutMeshElements) const
Gathers a description of the mesh elements to be rendered for the given LOD index, without consideration for views.
FName GetMeshDrawCommandStatsCategory () const
virtual FUintVector2 GetMeshPaintTextureDescriptor () const
float GetMinDrawDistance () const
const FVector2f & GetMinMaxMaterialDisplacement () const
virtual void GetNaniteResourceInfo (uint32 &ResourceID, uint32 &HierarchyOffset, uint32 &AssemblyTransformOffset, uint32 &ImposterIndex) const
int32 GetNumUncachedStaticLightingInteractions ()
virtual const TArray< FBoxSphereBounds > * GetOcclusionQueries (const FSceneView *View) const
Gets the boxes for sub occlusion queries.
FColor GetOverlayColor () const
FName GetOwnerName () const
virtual void GetPreSkinnedLocalBounds (FBoxSphereBounds &OutBounds) const
FLinearColor GetPrimitiveColor () const
FPrimitiveComponentId GetPrimitiveComponentId () const
FPrimitiveSceneInfo * GetPrimitiveSceneInfo () const
uint8 GetRayTracingGroupCullingPriority () const
int32 GetRayTracingGroupId () const
virtual FRenderCurveResourceData * GetRenderCurveResourceData ()
FName GetResourceName () const
const TArray< int32 > & GetRuntimeVirtualTextureIds () const
FSceneInterface & GetScene () const
uint8 GetSelectionOutlineColorIndex () const
EShadowCacheInvalidationBehavior GetShadowCacheInvalidationBehavior () const
virtual void GetShadowShapes (FVector PreViewTranslation, TArray< FCapsuleShape3f > &OutCapsuleShapes) const
Gathers shadow shapes from this proxy.
virtual TConstArrayView< FPrimitiveComponentId > GetSourceLandscapeComponentIds () const
virtual ESceneDepthPriorityGroup GetStaticDepthPriorityGroup () const
Determines the DPG to render the primitive in regardless of view.
FORCEINLINE TStatId GetStatId () const
EStencilMask GetStencilWriteMask () const
virtual void GetStreamableRenderAssetInfo (const FBoxSphereBounds &PrimitiveBounds, TArray< struct FStreamingRenderAssetPrimitiveInfo > &StreamableRenderAssets) const
float GetTranslucencySortDistanceOffset () const
int16 GetTranslucencySortPriority () const
FRHIUniformBuffer * GetUniformBuffer () const
virtual FPrimitiveViewRelevance GetViewRelevance (const FSceneView *View) const
Determines the relevance of this primitive's elements to the given view.
int32 GetVirtualTextureCullMips () const
int32 GetVirtualTextureLodBias () const
int32 GetVirtualTextureMinCoverage () const
int32 GetVisibilityId () const
FLinearColor GetWireframeColor () const
virtual bool HasCustomOcclusionBounds () const
Returns whether the proxy utilizes custom occlusion bounds or not.
bool HasDeformableMesh () const
Returns true if this proxy has any deformable mesh, meaning the mesh is animated e.g., by deforming the vertices through skinning, morphing or some procedural update.
virtual bool HasDistanceFieldRepresentation () const
virtual bool HasDynamicIndirectShadowCasterRepresentation () const
bool HasDynamicTransform () const
Returns true if this proxy can change transform so that we should cache previous transform for calculating velocity.
bool HasInstanceDataBuffers () const
bool HasPerInstanceHitProxies () const
bool HasStaticLighting () const
virtual bool HasSubprimitiveOcclusionQueries () const
bool HasValidSettingsForStaticLighting () const
bool HasViewDependentDPG () const
virtual bool HeightfieldHasPendingStreaming () const
bool Holdout () const
bool IsAlwaysVisible () const
Returns whether this proxy is always visible.
bool IsCollisionEnabled () const
bool IsCompatibleWithLumenCardSharing () const
virtual bool IsCullingReversedByComponent () const
virtual bool IsDetailMesh () const
Returns whether this proxy should be considered a "detail mesh".
FORCEINLINE bool IsDrawnInEditor () const
Tell us if this proxy is drawn in editor.
FORCEINLINE bool IsDrawnInGame () const
Tell us if this proxy is drawn in game.
bool IsEditingLevelInstanceChild () const
bool IsEmissiveLightSource () const
bool IsFirstPerson () const
bool IsFirstPersonWorldSpaceRepresentation () const
bool IsForceHidden () const
bool IsForceMipStreaming () const
bool IsHeterogeneousVolume () const
Returns whether this proxy is a heterogeneous volume.
bool IsHiddenInSceneCapture () const
bool IsHovered () const
bool IsIndividuallySelected () const
bool IsInstanceDataGPUOnly () const
Whether instance data only exists in the GPU Scene (instance data not present in CPU memory).
bool IsLandscapeNaniteProxy () const
bool IsLocalToWorldDeterminantNegative () const
bool IsMeshShapeOftenMoving () const
bool IsMovable () const
bool IsNaniteMesh () const
Returns whether this proxy is a Nanite mesh.
bool IsOftenMoving () const
bool IsOpaqueOrMasked () const
bool IsOwnedBy (const FSceneViewOwner &Owner) const
bool IsParentSelected () const
bool IsRayTracingFarField () const
bool IsSelectable () const
bool IsSelected () const
bool IsShadowCast (const FSceneView *View) const
bool IsShown (const FSceneView *View) const
bool IsSkinnedMesh () const
bool IsSplineMesh () const
bool IsStatic () const
bool IsSupportingStreamableRenderAssetsGathering () const
virtual bool IsUsingDistanceCullFade () const
bool IsVisibleInLumenScene () const
bool IsVisibleInRayTracing () const
bool IsVisibleInRealTimeSkyCaptures () const
bool IsVisibleInReflectionCaptures () const
bool IsVisibleInSceneCaptureOnly () const
bool LightAttachmentsAsGroup () const
bool NeedsUnbuiltPreviewLighting () const
virtual void OnDetachLight (const FLightSceneInfo *Light)
Called by the rendering thread to notify the proxy when a light is no longer associated with the proxy, so that it can clean up any cached resources.
virtual void OnTransformChanged (FRHICommandListBase &RHICmdList)
Called to notify the proxy when its transform has been updated.
const bool ReceivesDecals () const
void RenderBounds (FPrimitiveDrawInterface *PDI, const FEngineShowFlags &EngineShowFlags, const FBoxSphereBounds &Bounds, bool bRenderInEditor) const
Helper for components that want to render bounds.
void ResetSceneVelocity_GameThread ()
Enqueue and update for the render thread to remove the velocity data for this component from the scene.
void SetCanSkipRedundantTransformUpdates (bool bCanSkip)
Set whether the proxy can skip redundant transform updates where applicable.
void SetCollisionEnabled_GameThread (const bool bNewEnabled)
Set the collision flag on the scene proxy to enable/disable collision drawing.
void SetCollisionEnabled_RenderThread (const bool bNewEnabled)
Set the collision flag on the scene proxy to enable/disable collision drawing (RENDER THREAD)
void SetCustomDepthEnabled_GameThread (const bool bInRenderCustomDepth)
Set the custom depth enabled flag.
void SetCustomDepthEnabled_RenderThread (const bool bInRenderCustomDepth)
Set the custom depth enabled flag (RENDER THREAD)
void SetCustomDepthStencilValue_GameThread (const int32 InCustomDepthStencilValue)
Set the custom depth stencil value.
void SetCustomDepthStencilValue_RenderThread (const int32 InCustomDepthStencilValue)
Set the custom depth stencil value (RENDER THREAD)
virtual void SetDebugMassData (const TArray< FDebugMassData > &InDebugMassData)
Sets the primitive proxy's mass space to component space.
void SetDistanceFieldSelfShadowBias_RenderThread (float NewBias)
void SetDrawDistance_RenderThread (float MinDrawDistance, float MaxDrawDistance, float VirtualTextureMaxDrawDistance)
void SetDrawnInGame_RenderThread (bool bInDrawInGame)
Set the drawn in game flag, from the render thread.
void SetEvaluateWorldPositionOffset_GameThread (bool bEvaluate)
Enqueue updated setting for evaluation of World Position Offset.
void SetHiddenEdViews_GameThread (uint64 InHiddenEditorViews)
Updates the hidden editor view visibility map on the game thread which just enqueues a command on the render thread.
void SetHovered_GameThread (const bool bInHovered)
Updates hover state for the primitive proxy.
virtual void SetInstanceCullDistance_RenderThread (float StartCullDistance, float EndCullDistance)
void SetIsBeingMovedByEditor_GameThread (bool bIsBeingMoved)
Enqueue and update for the render thread to notify it that the editor is currently moving the owning component with gizmos.
void SetLevelInstanceEditingState_GameThread (const bool bInEditingState)
Updates the LevelInstance editing state for the primitive proxy.
void SetLightingChannels_GameThread (FLightingChannels LightingChannels)
Updates the lighting channels for the primitive proxy.
void SetOverlayColor_GameThread (FColor OverlayColor)
Enqueue updated overlay color for the render thread to use.
void SetPrimitiveColor (const FLinearColor &InPrimitiveColor)
void SetPrimitiveColor_GameThread (const FLinearColor &InPrimitiveColor)
Enqueue and update for the render thread to notify it that the primitive color changed.
void SetSelection_GameThread (const bool bInParentSelected, const bool bInIndividuallySelected=false)
Updates selection for the primitive proxy.
void SetSelectionOutlineColorIndex_GameThread (uint8 ColorIndex)
Enqueue updated selection outline color for the render thread to use.
void SetSelectionOverride_GameThread (bool bForceSelection)
Force the proxy to render as though it is selected.
void SetUsedMaterialForVerification (const TArray< UMaterialInterface * > &InUsedMaterialsForVerification)
This function exist only to perform an update of the UsedMaterialsForVerification on the render thread.
void SetWireframeColor (const FLinearColor &InWireframeColor)
virtual void SetWorldPositionOffsetDisableDistance_GameThread (int32 NewValue)
bool ShouldNotifyOnWorldAddRemove () const
bool ShouldReceiveMobileCSMShadows () const
bool ShouldRenderCustomDepth () const
bool ShouldRenderInDepthPass () const
bool ShouldRenderInMainPass () const
bool ShouldUseAsOccluder () const
virtual bool ShowInBSPSplitViewmode () const
bool SinglePassGDME () const
bool StaticElementsAlwaysUseProxyPrimitiveUniformBuffer () const
virtual bool StaticMeshHasPendingStreaming () const
bool SupportsDistanceFieldRepresentation () const
bool SupportsGPUScene () const
Returns true if all meshes drawn by this proxy support GPU scene.
bool SupportsHeightfieldRepresentation () const
bool SupportsInstanceDataBuffer () const
bool SupportsMaterialCache () const
bool SupportsParallelGDME () const
bool SupportsParallelGDRTI () const
bool SupportsSortedTriangles () const
bool TreatAsBackgroundForOcclusion () const
UE_DEPRECATED (5.4, "Use generic instance data through GetInstanceSceneDataBuffers().") virtual void GetDistanceFieldInstanceData(TArray< FRenderTransform > &InstanceLocalToPrimitiveTransforms) const final
UE_DEPRECATED (5.6, "Use GetRuntimeVirtualTextureIds() instead.") inline bool WritesVirtualTexture(URuntimeVirtualTexture *VirtualTexture) const
void UpdateUniformBuffer (FRHICommandList &RHICmdList)
Updates the primitive proxy's uniform buffer.
bool UseEditorCompositing (const FSceneView *View) const
bool UseSingleSampleShadowFromStationaryLights () const
bool VerifyUsedMaterial (const class FMaterialRenderProxy *MaterialRenderProxy) const
Verifies that a material used for rendering was present in the component's GetUsedMaterials list.
bool WantsEditorEffects () const
bool WantsSelectionOutline () const
bool WillEverBeLit () const
bool WritesVirtualTexture () const
Static Public Member Functions
static FConvexVolume AdjustViewFrustumForFarClipping (const FSceneView *InView, double InFarClippingDistance)
static FORCEINLINE bool BoxInFrustum (const FVector &Origin, const FVector &Extent, const FConvexVolume &ViewFrustum)
static FORCEINLINE bool BoxInView (const FVector &Origin, const FVector &Extent, const FSceneView *View)
static FORCEINLINE bool PointInFrustum (const FVector &Location, const FConvexVolume &ViewFrustum)
static FORCEINLINE bool PointInRange (const FVector &Start, const FSceneView *View, double Range)
static FORCEINLINE bool PointInView (const FVector &Location, const FSceneView *View)
static FORCEINLINE bool SegmentInFrustum (const FVector &StartPoint, const FVector &EndPoint, const FConvexVolume &ViewFrustum)
static FORCEINLINE bool SegmentInView (const FVector &StartPoint, const FVector &EndPoint, const FSceneView *View)
static FORCEINLINE bool SphereInFrustum (const FVector &Center, double Radius, const FConvexVolume &ViewFrustum)
static FORCEINLINE bool SphereInView (const FVector &Center, double Radius, const FSceneView *View)
Static Public Member Functions inherited from FPrimitiveSceneProxy
static void DrawArc (FPrimitiveDrawInterface *PDI, const FVector &Start, const FVector &End, const float Height, const uint32 Segments, const FLinearColor &Color, uint8 DepthPriorityGroup, const float Thickness=0.0f, const bool bScreenSpace=false)
Drawing helper.
static void DrawArrowHead (FPrimitiveDrawInterface *PDI, const FVector &Tip, const FVector &Origin, const float Size, const FLinearColor &Color, uint8 DepthPriorityGroup, const float Thickness=0.0f, const bool bScreenSpace=false)
Data Fields
TArray< FArrowLine > ArrowLines
TArray< FDebugBox > Boxes
TArray< FCapsule > Capsules
TArray< FCircle > Circles
TArray< FCone > Cones
TArray< FCoordinateSystem > CoordinateSystems
TArray< FWireCylinder > Cylinders
TArray< FDashedLine > DashedLines
FDebugDrawDelegate DebugTextDrawingDelegate
FDelegateHandle DebugTextDrawingDelegateHandle
uint32 DrawAlpha
EDrawType DrawType
double FarClippingDistance = 0.0
TArray< FDebugLine > Lines
TArray< FMesh > Meshes
TWeakObjectPtr< UMaterial > SolidMeshMaterial
TArray< FSphere > Spheres
TArray< FWireStar > Stars
TArray< FText3d > Texts
float TextWithoutShadowDistance
uint32 ViewFlagIndex
FString ViewFlagName
Data Fields inherited from FPrimitiveSceneProxy
TArray< FDebugMassData > DebugMassData
TSharedPtr< int32, ESPMode::ThreadSafe > SimpleStreamableAssetManagerIndex = MakeShared<int32, ESPMode::ThreadSafe>(INDEX_NONE)
Protected Member Functions
virtual void GetDynamicMeshElementsForView (const FSceneView *View, const int32 ViewIndex, const FSceneViewFamily &ViewFamily, const uint32 VisibilityMap, FMeshElementCollector &Collector, FMaterialCache &DefaultMaterialCache, FMaterialCache &SolidMeshMaterialCache) const
Protected Member Functions inherited from FPrimitiveSceneProxy
bool DrawInRuntimeVirtualTextureOnly (bool bEditor) const
Returns true if a primitive should currently be hidden because it is drawn only to the runtime virtual texture.
void EnableGPUSceneSupportFlags ()
Call during setup to set flags to indicate GPU-Scene support for the proxy if GPU-Scene is enabled & supported for the current feature level.
bool IsRuntimeVirtualTextureOnly () const
Returns true if a primitive can never be rendered outside of a runtime virtual texture.
virtual void OnEvaluateWorldPositionOffsetChanged_RenderThread ()
Allows child implementations to do render-thread work when bEvaluateWorldPositionOffset changes.
virtual void OnForceHiddenChanged ()
void OnLevelAddedToWorld_RenderThread ()
Called to notify the proxy that the level has been fully added to the world and the primitive will now be rendered.
void OnLevelRemovedFromWorld_RenderThread ()
Called to notify the proxy that the level has been fully removed from the world and the primitive will not be rendered.
void OverrideOwnerName (FName InOwnerName)
Allow subclasses to override the primitive name.
FRenderBounds PadInstanceLocalBounds (const FRenderBounds &InBounds)
void SetForceHidden (bool bForceHiddenIn)
void SetHovered_RenderThread (const bool bInHovered)
Updates hover state for the primitive proxy.
void SetLevelInstanceEditingState_RenderThread (const bool bInLevelInstanceEditingState)
Updates LevelInstance editing state for the primitive proxy.
void SetSelection_RenderThread (const bool bInParentSelected, const bool bInIndividuallySelected)
Updates selection for the primitive proxy.
void SetupInstanceSceneDataBuffers (const FInstanceSceneDataBuffers *InInstanceSceneDataBuffers)
UE_DEPRECATED (5.6, "StaticMeshBounds is no longer a parameter of this interface, please update the implementation.") 1 virtual void UpdateInstances_RenderThread(FRHICommandListBase &RHICmdList
Called on the render thread for a proxy that has an instance data update, the buffers are updated asynchronously so it is unclear what this should do, except update legacy data if needed.
virtual void UpdateInstances_RenderThread (FRHICommandListBase &RHICmdList, const FBoxSphereBounds &InBounds, const FBoxSphereBounds &InLocalBounds)
void UpdateVisibleInLumenScene ()
Updates bVisibleInLumen, which indicated whether a primitive should be tracked by Lumen scene.
Additional Inherited Members
Static Public Attributes inherited from FPrimitiveSceneProxy
static constexpr int32 InvalidRayTracingGroupId = -1
Protected Attributes inherited from FPrimitiveSceneProxy
uint8 bAffectDistanceFieldLighting: 1
uint8 bAffectDynamicIndirectLighting: 1
True if the primitive influences dynamic indirect lighting.
uint8 bAffectIndirectLightingWhileHidden: 1
True if the primitive should affect indirect lighting even when hidden.
uint8 bAllowApproximateOcclusion: 1
If this is True, this primitive doesn't need exact occlusion info.
uint8 bAlwaysHasVelocity: 1
Whether the primitive should always be considered to have velocities, even if it hasn't moved.
uint8 bAnyMaterialAlwaysEvaluatesWorldPositionOffset: 1
Whether the primitive has any materials that must ALWAYS evaluate World Position Offset.
uint8 bAnyMaterialHasPixelAnimation: 1
Whether the primitive has any materials that must ALWAYS evaluate World Position Offset.
uint8 bAnyMaterialHasWorldPositionOffset: 1
Whether the primitive has any materials with World Position Offset.
uint8 bCanSkipRedundantTransformUpdates: 1
Whether this component can skip redundant transform updates where applicable.
uint8 bCastCapsuleDirectShadow: 1
Whether the primitive should use capsules for direct shadowing, if present.
uint8 bCastCinematicShadow: 1
Whether this component should create a per-object shadow that gives higher effective shadow resolution.
uint8 bCastContactShadow: 1
Whether the object should cast a contact shadow.
uint8 bCastDeepShadow: 1
Whether the object should cast a deep shadow.
uint8 bCastDynamicShadow: 1
True if the primitive casts dynamic shadows.
uint8 bCastFarShadow: 1
uint8 bCastHiddenShadow: 1
True if the primitive casts shadows even when hidden.
uint8 bCastInsetShadow: 1
Whether this component should create a per-object shadow that gives higher effective shadow resolution.
uint8 bCastsDynamicIndirectShadow: 1
Whether the primitive should use an inset indirect shadow from capsules or mesh distance fields.
uint8 bCastShadowAsTwoSided: 1
Whether this primitive should cast dynamic shadows as if it were a two sided material.
uint8 bCastStaticShadow: 1
True if the primitive casts static shadows.
uint8 bCastVolumetricTranslucentShadow: 1
Whether the object should cast a volumetric translucent shadow.
uint8 bCompatibleWithLumenCardSharing: 1
Whether Lumen cards of this primitive can be shared.
uint8 bDoesMeshBatchesUseSceneInstanceCount: 1
Set to true to inform scene update that the MDCs produced may use the (GPU)Scene instance count, and thus don't require recaching if the instance count changed.
uint8 bEmissiveLightSource: 1
Whether the primitive will be used as an emissive light source.
uint8 bEvaluateWorldPositionOffset: 1
Whether the primitive should evaluate any World Position Offset.
uint8 bGoodCandidateForCachedShadowmap: 1
Whether this proxy's mesh is unlikely to be constantly changing.
uint8 bHasDeformableMesh: 1
True if the mesh representation is deformable (see HasDeformableMesh() above for more details).
uint8 bHasValidSettingsForStaticLighting: 1
True if the primitive wants to use static lighting, but has invalid content settings to do so.
uint8 bHasWorldPositionOffsetVelocity: 1
Whether the primitive has any materials with World Position Offset, and some conditions around velocity are met.
uint8 bHoldout: 1
If this is True, this primitive should render black with an alpha of 0, but all secondary effects (shadows, refletions, indirect lighting) should behave as usual.
uint8 bImplementsStreamableAssetGathering: 1
This is only set to true by constructors of proxy types witch support gathering of UStreamableAssets.
uint8 bIsAlwaysVisible: 1
Whether this proxy is always visible.
uint8 bIsFirstPerson: 1
If this is True, this primitive is to be rendered as a first person view object.
uint8 bIsFirstPersonWorldSpaceRepresentation: 1
If this is True, this primitive represents another first person primitive in world space.
uint8 bIsHeterogeneousVolume: 1
Whether this proxy is a heterogeneous volume.
uint8 bIsHierarchicalInstancedStaticMesh: 1
Whether the primitive is a HierarchicalInstancedStaticMesh.
uint8 bIsLandscapeGrass: 1
Whether the primitive is landscape grass.
uint8 bIsLandscapeNaniteProxy: 1
Whether this is FLandscapeNaniteSceneProxy and implements GetSourceLandscapeComponentIds().
uint8 bIsNaniteMesh: 1
Whether this proxy is a Nanite mesh.
uint8 bIsStaticMesh: 1
Whether this proxy is a static mesh.
uint8 bLightAttachmentsAsGroup: 1
Whether to light this component and any attachments as a group.
uint8 bNeedsUnbuiltPreviewLighting: 1
Whether the primitive should be statically lit but has unbuilt lighting, and a preview should be used.
uint8 bOpaqueOrMasked: 1
Whether this component contains opaque materials (cached once from assigned material).
uint8 bSelfShadowOnly: 1
When enabled, the component will only cast a shadow on itself and not other components in the world.
uint8 bShouldNotifyOnWorldAddRemove: 1
Whether this primitive requires notification when its level is added to the world and made visible for the first time.
uint8 bSinglePassGDME: 1
Whether to call GetDynamicMeshElements a single time, instead of once per unique FSceneViewFamily.
uint8 bSingleSampleShadowFromStationaryLights: 1
Whether the whole component should be shadowed as one from stationary lights, which makes shadow receiving much cheaper.
uint8 bSkinnedMesh: 1
If this is True, this primitive is a skinned mesh.
uint8 bSplineMesh: 1
If this is True, this primitive is a spline mesh.
uint8 bStaticElementsAlwaysUseProxyPrimitiveUniformBuffer: 1
Whether this proxy always uses UniformBuffer and no other uniform buffers.
uint8 bSupportsDistanceFieldRepresentation: 1
Whether the primitive type supports a distance field representation.
uint8 bSupportsGPUScene: 1
True if all meshes (AKA all vertex factories) drawn by this proxy support GPU scene (default is false).
uint8 bSupportsHeightfieldRepresentation: 1
Whether the primitive implements GetHeightfieldRepresentation()
uint8 bSupportsMaterialCache: 1
uint8 bSupportsParallelGDME: 1
Whether the proxy supports asynchronously calling GetDynamicMeshElements.
uint8 bSupportsParallelGDRTI: 1
Whether the proxy supports asynchronously calling GetDynamicRayTracingInstances.
uint8 bSupportsRuntimeVirtualTexture: 1
This is only set true by the constructors of proxy types which support writing to runtime virtual texture.
uint8 bSupportsSortedTriangles: 1
Whether the object support triangles when rendered with translucent material.
uint8 bVerifyUsedMaterials: 1
uint8 bVFRequiresPrimitiveUniformBuffer: 1
Whether this proxy ever draws with vertex factories that require a primitive uniform buffer.
uint8 bVisibleInLumenScene: 1
Whether this component should be tracked by Lumen Scene.
uint8 bWantsEditorEffects: 1
False by default, if true the proxy wants editor-only effects like outlines and overlays.
uint8 bWantsSelectionOutline: 1
true by default, if set to false will make given proxy never drawn with selection outline
uint8 bWillEverBeLit: 1
Can be set to false to skip some work only needed on lit primitives.
FMaterialRelevance CombinedMaterialRelevance
Cached material relevance available for GetMaterialRelevance call.
float DistanceFieldSelfShadowBias
float DynamicIndirectShadowMinVisibility
Min visibility for capsule shadows.
const FBoxSphereBounds const FBoxSphereBounds const FBoxSphereBounds &InStaticMeshBounds final
const FBoxSphereBounds & InBounds
TEnumAsByte< EIndirectLightingCacheQuality > IndirectLightingCacheQuality
Quality of interpolated indirect lighting for Movable components.
const FBoxSphereBounds const FBoxSphereBounds & InLocalBounds
float MaxDrawDistance
The primitive's cull distance.
float MaxWPOExtent
Maximum distance of World Position Offset used by materials.
float MinDrawDistance
The primitive's minimum cull distance.
FVector2f MinMaxMaterialDisplacement
TArray< ERuntimeVirtualTextureMaterialType > RuntimeVirtualTextureMaterialTypes
Set of unique runtime virtual texture material types referenced by RuntimeVirtualTextures.
TArray< int32 > RuntimeVirtualTextures
Array of runtime virtual textures unique ids that this proxy should render to.
EShadowCacheInvalidationBehavior ShadowCacheInvalidationBehavior
int8 VirtualTextureCullMips
Number of low mips to skip when rendering to runtime virtual texture.
int8 VirtualTextureLodBias
Geometry Lod bias when rendering to runtime virtual texture.
int8 VirtualTextureMinCoverage
Log2 of minimum estimated pixel coverage before culling from runtime virtual texture.
Detailed Description
Definition at line 37 of file DebugRenderSceneProxy.h.
Member Enumeration Documentation
EDrawType
enum FDebugRenderSceneProxy::EDrawType
Enumerator
SolidMesh
WireMesh
SolidAndWireMeshes
Invalid
Definition at line 44 of file DebugRenderSceneProxy.h.
Constructor & Destructor Documentation
~FDebugRenderSceneProxy()
virtual FDebugRenderSceneProxy::~FDebugRenderSceneProxy () virtual
FDebugRenderSceneProxy() [1/2]
FDebugRenderSceneProxy::FDebugRenderSceneProxy (const UPrimitiveComponent * InComponent)
Referenced by FDebugRenderSceneProxy().
FDebugRenderSceneProxy() [2/2]
FDebugRenderSceneProxy::FDebugRenderSceneProxy (FDebugRenderSceneProxy const &)
References FDebugRenderSceneProxy().
Member Function Documentation
AdjustViewFrustumForFarClipping()
FConvexVolume FDebugRenderSceneProxy::AdjustViewFrustumForFarClipping (const FSceneView * InView, double InFarClippingDistance) static
BoxInFrustum()
FORCEINLINE bool FDebugRenderSceneProxy::BoxInFrustum (const FVector & Origin, const FVector & Extent, const FConvexVolume & ViewFrustum) inline static
Definition at line 105 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, FConvexVolume::IntersectBox(), and Origin.
Referenced by BoxInView().
BoxInView()
FORCEINLINE bool FDebugRenderSceneProxy::BoxInView (const FVector & Origin, const FVector & Extent, const FSceneView * View) inline static
Definition at line 85 of file DebugRenderSceneProxy.h.
References BoxInFrustum(), FORCEINLINE, FVector, Origin, and FSceneView::ViewFrustum.
DrawLineArrow()
void FDebugRenderSceneProxy::DrawLineArrow (FPrimitiveDrawInterface * PDI, const FVector & Start, const FVector & End, const FColor & Color, float Mag) const
Draws a line with an arrow at the end.
Parameters
PDI Draw interface to render to
Start Starting point of the line.
End Ending point of the line.
Color Color of the line.
Mag Size of the arrow.
References Color, End, and FVector.
GetAllocatedSize()
uint32 FDebugRenderSceneProxy::GetAllocatedSize (void) const
Referenced by GetMemoryFootprint().
GetDynamicMeshElements()
virtual void FDebugRenderSceneProxy::GetDynamicMeshElements (const TArray< const FSceneView * > & Views, const FSceneViewFamily & ViewFamily, uint32 VisibilityMap, FMeshElementCollector & Collector) const override virtual
Draw the scene proxy as a dynamic element.
Reimplemented from FPrimitiveSceneProxy.
GetDynamicMeshElementsForView()
virtual void FDebugRenderSceneProxy::GetDynamicMeshElementsForView (const FSceneView * View, const int32 ViewIndex, const FSceneViewFamily & ViewFamily, const uint32 VisibilityMap, FMeshElementCollector & Collector, FMaterialCache & DefaultMaterialCache, FMaterialCache & SolidMeshMaterialCache) const protected virtual
GetMemoryFootprint()
virtual uint32 FDebugRenderSceneProxy::GetMemoryFootprint (void) const inline override virtual
Every derived class should override these functions.
Implements FPrimitiveSceneProxy.
Definition at line 72 of file DebugRenderSceneProxy.h.
References GetAllocatedSize().
GetTypeHash()
SIZE_T FDebugRenderSceneProxy::GetTypeHash () const override virtual
Return a type (or subtype) specific hash for sorting purposes.
Implements FPrimitiveSceneProxy.
Reimplemented in FEQSSceneProxy.
PointInFrustum()
FORCEINLINE bool FDebugRenderSceneProxy::PointInFrustum (const FVector & Location, const FConvexVolume & ViewFrustum) inline static
Definition at line 95 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, FConvexVolume::IntersectPoint(), and Location.
Referenced by PointInView().
PointInRange()
FORCEINLINE bool FDebugRenderSceneProxy::PointInRange (const FVector & Start, const FSceneView * View, double Range) inline static
Definition at line 115 of file DebugRenderSceneProxy.h.
References UE::Math::TVector< double >::DistSquared(), FORCEINLINE, FVector, FViewMatrices::GetViewOrigin(), FMath::Square(), and FSceneView::ViewMatrices.
PointInView()
FORCEINLINE bool FDebugRenderSceneProxy::PointInView (const FVector & Location, const FSceneView * View) inline static
Definition at line 75 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, Location, PointInFrustum(), and FSceneView::ViewFrustum.
SegmentInFrustum()
FORCEINLINE bool FDebugRenderSceneProxy::SegmentInFrustum (const FVector & StartPoint, const FVector & EndPoint, const FConvexVolume & ViewFrustum) inline static
Definition at line 100 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, and FConvexVolume::IntersectLineSegment().
Referenced by SegmentInView().
SegmentInView()
FORCEINLINE bool FDebugRenderSceneProxy::SegmentInView (const FVector & StartPoint, const FVector & EndPoint, const FSceneView * View) inline static
Definition at line 80 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, SegmentInFrustum(), and FSceneView::ViewFrustum.
SphereInFrustum()
FORCEINLINE bool FDebugRenderSceneProxy::SphereInFrustum (const FVector & Center, double Radius, const FConvexVolume & ViewFrustum) inline static
Definition at line 110 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, and FConvexVolume::IntersectSphere().
Referenced by SphereInView().
SphereInView()
FORCEINLINE bool FDebugRenderSceneProxy::SphereInView (const FVector & Center, double Radius, const FSceneView * View) inline static
Definition at line 90 of file DebugRenderSceneProxy.h.
References FORCEINLINE, FVector, SphereInFrustum(), and FSceneView::ViewFrustum.
Field Documentation
ArrowLines
TArray<FArrowLine> FDebugRenderSceneProxy::ArrowLines
Definition at line 402 of file DebugRenderSceneProxy.h.
Boxes
TArray<FDebugBox> FDebugRenderSceneProxy::Boxes
Definition at line 406 of file DebugRenderSceneProxy.h.
Capsules
TArray<FCapsule> FDebugRenderSceneProxy::Capsules
Definition at line 411 of file DebugRenderSceneProxy.h.
Circles
TArray<FCircle> FDebugRenderSceneProxy::Circles
Definition at line 403 of file DebugRenderSceneProxy.h.
Cones
TArray<FCone> FDebugRenderSceneProxy::Cones
Definition at line 409 of file DebugRenderSceneProxy.h.
CoordinateSystems
TArray<FCoordinateSystem> FDebugRenderSceneProxy::CoordinateSystems
Definition at line 412 of file DebugRenderSceneProxy.h.
Cylinders
TArray<FWireCylinder> FDebugRenderSceneProxy::Cylinders
Definition at line 404 of file DebugRenderSceneProxy.h.
DashedLines
TArray<FDashedLine> FDebugRenderSceneProxy::DashedLines
Definition at line 401 of file DebugRenderSceneProxy.h.
DebugTextDrawingDelegate
FDebugDrawDelegate FDebugRenderSceneProxy::DebugTextDrawingDelegate
Definition at line 417 of file DebugRenderSceneProxy.h.
DebugTextDrawingDelegateHandle
FDelegateHandle FDebugRenderSceneProxy::DebugTextDrawingDelegateHandle
Definition at line 418 of file DebugRenderSceneProxy.h.
DrawAlpha
uint32 FDebugRenderSceneProxy::DrawAlpha
Definition at line 420 of file DebugRenderSceneProxy.h.
DrawType
EDrawType FDebugRenderSceneProxy::DrawType
Definition at line 419 of file DebugRenderSceneProxy.h.
FarClippingDistance
double FDebugRenderSceneProxy::FarClippingDistance = 0.0
Definition at line 421 of file DebugRenderSceneProxy.h.
Lines
TArray<FDebugLine> FDebugRenderSceneProxy::Lines
Definition at line 400 of file DebugRenderSceneProxy.h.
Meshes
TArray<FMesh> FDebugRenderSceneProxy::Meshes
Definition at line 410 of file DebugRenderSceneProxy.h.
SolidMeshMaterial
TWeakObjectPtr<UMaterial> FDebugRenderSceneProxy::SolidMeshMaterial
Definition at line 423 of file DebugRenderSceneProxy.h.
Spheres
TArray<FSphere> FDebugRenderSceneProxy::Spheres
Definition at line 407 of file DebugRenderSceneProxy.h.
Referenced by FEQSSceneProxy::FEQSSceneProxy(), and FEQSSceneProxy::GetViewRelevance().
Stars
TArray<FWireStar> FDebugRenderSceneProxy::Stars
Definition at line 405 of file DebugRenderSceneProxy.h.
Texts
TArray<FText3d> FDebugRenderSceneProxy::Texts
Definition at line 408 of file DebugRenderSceneProxy.h.
Referenced by FEQSSceneProxy::FEQSSceneProxy(), and FEQSSceneProxy::GetViewRelevance().
TextWithoutShadowDistance
float FDebugRenderSceneProxy::TextWithoutShadowDistance
Definition at line 415 of file DebugRenderSceneProxy.h.
ViewFlagIndex
uint32 FDebugRenderSceneProxy::ViewFlagIndex
Definition at line 414 of file DebugRenderSceneProxy.h.
ViewFlagName
FString FDebugRenderSceneProxy::ViewFlagName
Definition at line 416 of file DebugRenderSceneProxy.h.
Referenced by FEQSSceneProxy::FEQSSceneProxy().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/DebugRenderSceneProxy.h