Unreal Engine 5.6 C++ API: FMeshElementContainer Class Reference
FMeshElementContainer Class Reference
Class representing a collection of mesh elements, such as vertices or triangles.
#include "MeshElementContainer.h"
Data Structures
class FElementIDs
This is a special type of iterator which returns successive IDs of valid elements, rather than the elements themselves.
Public Member Functions
FMeshElementContainer ()=default
FMeshElementContainer (const FMeshElementContainer &)=default
FMeshElementContainer (FMeshElementContainer &&Other)
Move constructor which ensures that NumHoles is set correctly in the moved object.
int32 Add ()
Add a new element at the next available index, and return the new ID.
MESHDESCRIPTION_API void Compact (TSparseArray< int32 > &OutIndexRemap)
Compacts elements and returns a remapping table.
int32 GetArraySize () const
Returns the index after the last valid element.
FORCEINLINE FAttributesSetBase & GetAttributes ()
Accessor for attributes.
FORCEINLINE const FAttributesSetBase & GetAttributes () const
FElementIDs FORCEINLINE GetElementIDs () const
Return iterable proxy object from container.
int32 GetFirstValidID () const
Returns the first valid ID.
void Insert (const int32 Index)
Inserts a new element with the given index.
bool IsValid (const int32 Index) const
Returns whether the given ID is valid or not.
int32 Num () const
Returns the number of elements in the container.
FMeshElementContainer & operator= (const FMeshElementContainer &)=default
FMeshElementContainer & operator= (FMeshElementContainer &&Other)
Move assignment operator which ensures that NumHoles is set correctly in the moved object.
MESHDESCRIPTION_API void Remap (const TSparseArray< int32 > &IndexRemap)
Remaps elements according to the passed remapping table.
void Remove (const int32 Index)
Removes the element with the given ID.
void Reserve (const int32 Elements)
Reserves space for the specified total number of elements.
void Reset (const int32 Elements=0)
Resets the container, optionally reserving space for elements to be added.
Protected Attributes
FAttributesSetBase Attributes
Attributes associated with this element container.
TBitArray BitArray
A bit array of all indices currently in use.
int32 NumHoles = 0
A count of the number of unused indices in the bit array.
Friends
FArchive & operator<< (FArchive &Ar, FMeshElementContainer &Container)
Serializer.
Detailed Description
Class representing a collection of mesh elements, such as vertices or triangles.
It has two purposes: 1) To generate new element IDs on demand, and recycle those which have been discarded. 2) To hold a map of attributes for a given element type and their values.
Definition at line 24 of file MeshElementContainer.h.
Constructor & Destructor Documentation
FMeshElementContainer() [1/3]
FMeshElementContainer::FMeshElementContainer () default
Referenced by FMeshElementContainer(), FMeshElementContainer(), operator<<, operator=(), and operator=().
FMeshElementContainer() [2/3]
FMeshElementContainer::FMeshElementContainer (const FMeshElementContainer &) default
References FMeshElementContainer().
FMeshElementContainer() [3/3]
FMeshElementContainer::FMeshElementContainer (FMeshElementContainer && Other) inline
Move constructor which ensures that NumHoles is set correctly in the moved object.
Definition at line 32 of file MeshElementContainer.h.
References FMeshElementContainer(), Attributes, BitArray, MoveTemp(), NumHoles, and Other.
Member Function Documentation
Add()
int32 FMeshElementContainer::Add () inline
Add a new element at the next available index, and return the new ID.
Definition at line 65 of file MeshElementContainer.h.
References Attributes, BitArray, check, INDEX_NONE, and NumHoles.
Referenced by TMeshElementContainer< FVertexID >::Add().
Compact()
MESHDESCRIPTION_API void FMeshElementContainer::Compact (TSparseArray< int32 > & OutIndexRemap)
Compacts elements and returns a remapping table.
GetArraySize()
int32 FMeshElementContainer::GetArraySize () const inline
Returns the index after the last valid element.
Definition at line 123 of file MeshElementContainer.h.
References BitArray.
GetAttributes() [1/2]
FORCEINLINE FAttributesSetBase & FMeshElementContainer::GetAttributes () inline
Accessor for attributes.
Definition at line 138 of file MeshElementContainer.h.
References Attributes, and FORCEINLINE.
GetAttributes() [2/2]
FORCEINLINE const FAttributesSetBase & FMeshElementContainer::GetAttributes () const inline
Definition at line 139 of file MeshElementContainer.h.
References Attributes, and FORCEINLINE.
GetElementIDs()
FElementIDs FORCEINLINE FMeshElementContainer::GetElementIDs () const inline
Return iterable proxy object from container.
Definition at line 227 of file MeshElementContainer.h.
References BitArray, and FORCEINLINE.
GetFirstValidID()
int32 FMeshElementContainer::GetFirstValidID () const inline
Returns the first valid ID.
Definition at line 126 of file MeshElementContainer.h.
References BitArray.
Referenced by TMeshElementContainer< FVertexID >::GetFirstValidID().
Insert()
void FMeshElementContainer::Insert (const int32 Index) inline
Inserts a new element with the given index.
Definition at line 85 of file MeshElementContainer.h.
References Attributes, BitArray, checkSlow, and NumHoles.
Referenced by TMeshElementContainer< FVertexID >::Insert().
IsValid()
bool FMeshElementContainer::IsValid (const int32 Index) const inline
Returns whether the given ID is valid or not.
Definition at line 132 of file MeshElementContainer.h.
References BitArray.
Referenced by TMeshElementContainer< FVertexID >::IsValid().
Num()
int32 FMeshElementContainer::Num () const inline
Returns the number of elements in the container.
Definition at line 120 of file MeshElementContainer.h.
References BitArray, and NumHoles.
operator=() [1/2]
FMeshElementContainer & FMeshElementContainer::operator= (const FMeshElementContainer &) default
References FMeshElementContainer().
operator=() [2/2]
FMeshElementContainer & FMeshElementContainer::operator= (FMeshElementContainer && Other) inline
Move assignment operator which ensures that NumHoles is set correctly in the moved object.
Definition at line 41 of file MeshElementContainer.h.
References FMeshElementContainer(), Attributes, BitArray, MoveTemp(), NumHoles, and Other.
Remap()
MESHDESCRIPTION_API void FMeshElementContainer::Remap (const TSparseArray< int32 > & IndexRemap)
Remaps elements according to the passed remapping table.
Remove()
void FMeshElementContainer::Remove (const int32 Index) inline
Removes the element with the given ID.
Definition at line 110 of file MeshElementContainer.h.
References Attributes, BitArray, checkSlow, and NumHoles.
Referenced by TMeshElementContainer< FVertexID >::Remove().
Reserve()
void FMeshElementContainer::Reserve (const int32 Elements) inline
Reserves space for the specified total number of elements.
Definition at line 62 of file MeshElementContainer.h.
References BitArray.
Reset()
void FMeshElementContainer::Reset (const int32 Elements = 0) inline
Resets the container, optionally reserving space for elements to be added.
Definition at line 54 of file MeshElementContainer.h.
References Attributes, BitArray, and NumHoles.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FMeshElementContainer & Container) friend
Serializer.
Definition at line 148 of file MeshElementContainer.h.
References FMeshElementContainer(), Ar, and Container.
Field Documentation
Attributes
FAttributesSetBase FMeshElementContainer::Attributes protected
Attributes associated with this element container.
Definition at line 234 of file MeshElementContainer.h.
Referenced by FMeshElementContainer(), Add(), GetAttributes(), GetAttributes(), TMeshElementContainer< FVertexID >::GetAttributes(), TMeshElementContainer< FVertexID >::GetAttributes(), Insert(), operator=(), Remove(), and Reset().
BitArray
TBitArray FMeshElementContainer::BitArray protected
A bit array of all indices currently in use.
Definition at line 231 of file MeshElementContainer.h.
Referenced by FMeshElementContainer(), Add(), GetArraySize(), GetElementIDs(), TMeshElementContainer< FVertexID >::GetElementIDs(), GetFirstValidID(), Insert(), IsValid(), Num(), operator=(), Remove(), Reserve(), and Reset().
NumHoles
int32 FMeshElementContainer::NumHoles = 0 protected
A count of the number of unused indices in the bit array.
IMPORTANT: This must always correspond to the number of zeroes in the BitArray.
Definition at line 237 of file MeshElementContainer.h.
Referenced by FMeshElementContainer(), Add(), Insert(), Num(), operator=(), Remove(), and Reset().
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/MeshElementContainer.h