Unreal Engine 5.6 C++ API: FLazyName Class Reference
FLazyName Class Reference
Lazily constructed FName that helps avoid allocating FNames during static initialization.
#include "NameTypes.h"
Data Structures
struct FLiteralOrName
Public Member Functions
FLazyName ()
template<int N>
FLazyName (const ANSICHAR(&Literal)[N])
template<int N>
FLazyName (const WIDECHAR(&Literal)[N])
FLazyName (FName Name)
operator FName () const
FName Resolve () const
FString ToString () const
FUtf8String ToUtf8String () const
Static Private Member Functions
static uint32 ParseNumber (const ANSICHAR *Literal, int32 Len)
static uint32 ParseNumber (const WIDECHAR *Literal, int32 Len)
Private Attributes
bool bLiteralIsWide = false
FLiteralOrName Either
uint32 Number = 0
Friends
bool operator== (const FLazyName &A, const FLazyName &B)
bool operator== (const FLazyName &Lazy, FName Name)
bool operator== (FName Name, const FLazyName &Lazy)
Detailed Description
Lazily constructed FName that helps avoid allocating FNames during static initialization.
Definition at line 1658 of file NameTypes.h.
Constructor & Destructor Documentation
FLazyName() [1/4]
FLazyName::FLazyName () inline
Definition at line 1661 of file NameTypes.h.
References Either.
Referenced by operator==, operator==, and operator==.
FLazyName() [2/4]
template<int N> FLazyName::FLazyName (const WIDECHAR(&) Literal[N]) inline
Parameters
Literal must be a string literal
Definition at line 1667 of file NameTypes.h.
References bLiteralIsWide, Either, Number, and ParseNumber().
FLazyName() [3/4]
template<int N> FLazyName::FLazyName (const ANSICHAR(&) Literal[N]) inline
Parameters
Literal must be a string literal
Definition at line 1675 of file NameTypes.h.
References bLiteralIsWide, Either, Number, and ParseNumber().
FLazyName() [4/4]
FLazyName::FLazyName (FName Name) inline explicit
Definition at line 1681 of file NameTypes.h.
References Either, Name, and Number.
Member Function Documentation
operator FName()
FLazyName::operator FName () const inline
Definition at line 1686 of file NameTypes.h.
References Resolve().
ParseNumber() [1/2]
uint32 FLazyName::ParseNumber (const ANSICHAR * Literal, int32 Len) static private
ParseNumber() [2/2]
uint32 FLazyName::ParseNumber (const WIDECHAR * Literal, int32 Len) static private
Referenced by FLazyName(), and FLazyName().
Resolve()
FName FLazyName::Resolve () const
Referenced by operator FName(), and operator==.
ToString()
FString FLazyName::ToString () const
ToUtf8String()
FUtf8String FLazyName::ToUtf8String () const
Friends And Related Symbol Documentation
operator== [1/3]
bool operator== (const FLazyName & A, const FLazyName & B) friend
References FLazyName(), A, and B.
operator== [2/3]
bool operator== (const FLazyName & Lazy, FName Name) friend
Definition at line 1785 of file NameTypes.h.
References FLazyName(), and Name.
operator== [3/3]
bool operator== (FName Name, const FLazyName & Lazy) friend
Definition at line 1767 of file NameTypes.h.
References FLazyName(), FLazyName::FLiteralOrName::AsAnsiLiteral(), FLazyName::FLiteralOrName::AsWideLiteral(), bLiteralIsWide, Either, FLazyName::FLiteralOrName::IsName(), Name, and Resolve().
Field Documentation
bLiteralIsWide
bool FLazyName::bLiteralIsWide = false private
Definition at line 1760 of file NameTypes.h.
Referenced by FLazyName(), FLazyName(), and operator==.
Either
FLiteralOrName FLazyName::Either mutable private
Definition at line 1756 of file NameTypes.h.
Referenced by FLazyName(), FLazyName(), FLazyName(), FLazyName(), and operator==.
Number
uint32 FLazyName::Number = 0 mutable private
Definition at line 1757 of file NameTypes.h.
Referenced by FLazyName(), FLazyName(), and FLazyName().
The documentation for this class was generated from the following file:
Runtime/Core/Public/UObject/NameTypes.h