Unreal Engine 5.6 C++ API: UE::Sequencer::FChannelGroupModel Class Reference
UE::Sequencer::FChannelGroupModel Class Reference
Model for the outliner entry associated with all sections' channels of a given common name.
#include "ChannelModel.h"
Public Member Functions
FChannelGroupModel (FName InChannelName, const FText &InDisplayText)
FChannelGroupModel (FName InChannelName, const FText &InDisplayText, const FText &InTooltipText)
FChannelGroupModel (FName InChannelName, const FText &InDisplayText, FGetMovieSceneTooltipText InGetTooltipTextDelegate)
~FChannelGroupModel ()
void AddChannel (TWeakViewModelPtr< FChannelModel > InChannel)
Adds a channel model to this group.
void BuildChannelOverrideMenu (FMenuBuilder &MenuBuilder)
void CleanupChannels ()
void CreateCurveModels (TArray< TUniquePtr< FCurveModel > > &OutCurveModels)
TArray< TSharedRef< IKeyArea > > GetAllKeyAreas () const
Get the key areas of all channels.
TSharedPtr< FChannelModel > GetChannel (const UMovieSceneSection *InOwnerSection) const
Get the channel model of the channel associated with the given section.
TSharedPtr< FChannelModel > GetChannel (int32 Index) const
Get the channel model at the given index in the list of channels.
TSharedPtr< FChannelModel > GetChannel (TSharedPtr< FSectionModel > InOwnerSection) const
Get the channel model of the channel associated with the given section.
FName GetChannelName () const
Returns the common name for all channels in this group.
TArrayView< const TWeakViewModelPtr< FChannelModel > > GetChannels () const
Gets all the channel models in this group.
uint32 GetChannelsSerialNumber () const
Gets a serial number representing if the list of channels has changed.
FText GetDisplayText () const
Returns the label for this group.
TSharedPtr< IKeyArea > GetKeyArea (const UMovieSceneSection *InOwnerSection) const
Get the key area of the channel associated with the given section.
TSharedPtr< IKeyArea > GetKeyArea (TSharedPtr< FSectionModel > InOwnerSection) const
Get the key area of the channel associated with the given section.
FText GetTooltipText () const
Returns the tooltip for this group.
FViewModelVariantIterator GetTrackAreaModelList () const override
FTrackAreaParameters GetTrackAreaParameters () const override
TOptional< FString > GetUniquePathName () const
bool HasCurves () const
bool IsAnimated () const
Returns whether any of the channels within this group have any keyframes on them.
void OnChannelOverridesChanged ()
Notifies this view-model that the list of channels has changed.
void OnRecycle () override
UE_SEQUENCER_DECLARE_CASTABLE (FChannelGroupModel, FViewModel, ITrackAreaExtension, IRecyclableExtension)
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::ITrackAreaExtension
virtual FViewModelVariantIterator GetTopLevelChildTrackAreaModels () const
template<typename T>
TTypedIterator< T, FViewModelVariantIterator > GetTrackAreaModelListAs () const
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackAreaExtension) virtual ~ITrackAreaExtension()
Public Member Functions inherited from UE::Sequencer::IRecyclableExtension
virtual ~IRecyclableExtension ()
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IRecyclableExtension) static void CallOnRecycle(const TViewModelPtr< IRecyclableExtension > &RecyclableItem)
Protected Member Functions
void UpdateMutability ()
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Protected Attributes
FName ChannelName
TArray< TWeakViewModelPtr< FChannelModel > > Channels
uint32 ChannelsSerialNumber
FText DisplayText
FGetMovieSceneTooltipText GetTooltipTextDelegate
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Additional Inherited Members
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Model for the outliner entry associated with all sections' channels of a given common name.
For instance, this represents the "Location.X" entry in the Sequencer outliner.
Definition at line 130 of file ChannelModel.h.
Constructor & Destructor Documentation
FChannelGroupModel() [1/3]
UE::Sequencer::FChannelGroupModel::FChannelGroupModel (FName InChannelName, const FText & InDisplayText)
Referenced by UE_SEQUENCER_DECLARE_CASTABLE().
FChannelGroupModel() [2/3]
UE::Sequencer::FChannelGroupModel::FChannelGroupModel (FName InChannelName, const FText & InDisplayText, const FText & InTooltipText)
FChannelGroupModel() [3/3]
UE::Sequencer::FChannelGroupModel::FChannelGroupModel (FName InChannelName, const FText & InDisplayText, FGetMovieSceneTooltipText InGetTooltipTextDelegate)
~FChannelGroupModel()
UE::Sequencer::FChannelGroupModel::~FChannelGroupModel ()
Member Function Documentation
AddChannel()
void UE::Sequencer::FChannelGroupModel::AddChannel (TWeakViewModelPtr< FChannelModel > InChannel)
Adds a channel model to this group.
BuildChannelOverrideMenu()
void UE::Sequencer::FChannelGroupModel::BuildChannelOverrideMenu (FMenuBuilder & MenuBuilder)
CleanupChannels()
void UE::Sequencer::FChannelGroupModel::CleanupChannels ()
CreateCurveModels()
void UE::Sequencer::FChannelGroupModel::CreateCurveModels (TArray< TUniquePtr< FCurveModel > > & OutCurveModels)
GetAllKeyAreas()
TArray< TSharedRef< IKeyArea > > UE::Sequencer::FChannelGroupModel::GetAllKeyAreas () const
Get the key areas of all channels.
GetChannel() [1/3]
TSharedPtr< FChannelModel > UE::Sequencer::FChannelGroupModel::GetChannel (const UMovieSceneSection * InOwnerSection) const
Get the channel model of the channel associated with the given section.
GetChannel() [2/3]
TSharedPtr< FChannelModel > UE::Sequencer::FChannelGroupModel::GetChannel (int32 Index) const
Get the channel model at the given index in the list of channels.
GetChannel() [3/3]
TSharedPtr< FChannelModel > UE::Sequencer::FChannelGroupModel::GetChannel (TSharedPtr< FSectionModel > InOwnerSection) const
Get the channel model of the channel associated with the given section.
GetChannelName()
FName UE::Sequencer::FChannelGroupModel::GetChannelName () const inline
Returns the common name for all channels in this group.
Definition at line 148 of file ChannelModel.h.
References ChannelName.
GetChannels()
TArrayView< const TWeakViewModelPtr< FChannelModel > > UE::Sequencer::FChannelGroupModel::GetChannels () const
Gets all the channel models in this group.
GetChannelsSerialNumber()
uint32 UE::Sequencer::FChannelGroupModel::GetChannelsSerialNumber () const
Gets a serial number representing if the list of channels has changed.
GetDisplayText()
FText UE::Sequencer::FChannelGroupModel::GetDisplayText () const inline
Returns the label for this group.
Definition at line 151 of file ChannelModel.h.
References DisplayText.
GetKeyArea() [1/2]
TSharedPtr< IKeyArea > UE::Sequencer::FChannelGroupModel::GetKeyArea (const UMovieSceneSection * InOwnerSection) const
Get the key area of the channel associated with the given section.
GetKeyArea() [2/2]
TSharedPtr< IKeyArea > UE::Sequencer::FChannelGroupModel::GetKeyArea (TSharedPtr< FSectionModel > InOwnerSection) const
Get the key area of the channel associated with the given section.
GetTooltipText()
FText UE::Sequencer::FChannelGroupModel::GetTooltipText () const
Returns the tooltip for this group.
GetTrackAreaModelList()
FViewModelVariantIterator UE::Sequencer::FChannelGroupModel::GetTrackAreaModelList () const override virtual
Implements UE::Sequencer::ITrackAreaExtension.
GetTrackAreaParameters()
FTrackAreaParameters UE::Sequencer::FChannelGroupModel::GetTrackAreaParameters () const override virtual
Implements UE::Sequencer::ITrackAreaExtension.
GetUniquePathName()
TOptional< FString > UE::Sequencer::FChannelGroupModel::GetUniquePathName () const
HasCurves()
bool UE::Sequencer::FChannelGroupModel::HasCurves () const
IsAnimated()
bool UE::Sequencer::FChannelGroupModel::IsAnimated () const
Returns whether any of the channels within this group have any keyframes on them.
OnChannelOverridesChanged()
void UE::Sequencer::FChannelGroupModel::OnChannelOverridesChanged ()
Notifies this view-model that the list of channels has changed.
OnRecycle()
void UE::Sequencer::FChannelGroupModel::OnRecycle () override virtual
Implements UE::Sequencer::IRecyclableExtension.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FChannelGroupModel::UE_SEQUENCER_DECLARE_CASTABLE (FChannelGroupModel , FViewModel , ITrackAreaExtension , IRecyclableExtension)
References FChannelGroupModel(), and UE::Sequencer::FViewModel::FViewModel().
UpdateMutability()
void UE::Sequencer::FChannelGroupModel::UpdateMutability () protected
Field Documentation
ChannelName
FName UE::Sequencer::FChannelGroupModel::ChannelName protected
Definition at line 210 of file ChannelModel.h.
Referenced by GetChannelName().
Channels
TArray<TWeakViewModelPtr<FChannelModel> > UE::Sequencer::FChannelGroupModel::Channels protected
Definition at line 208 of file ChannelModel.h.
ChannelsSerialNumber
uint32 UE::Sequencer::FChannelGroupModel::ChannelsSerialNumber protected
Definition at line 209 of file ChannelModel.h.
DisplayText
FText UE::Sequencer::FChannelGroupModel::DisplayText protected
Definition at line 211 of file ChannelModel.h.
Referenced by GetDisplayText().
GetTooltipTextDelegate
FGetMovieSceneTooltipText UE::Sequencer::FChannelGroupModel::GetTooltipTextDelegate protected
Definition at line 212 of file ChannelModel.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/MVVM/ViewModels/ChannelModel.h