Unreal Engine 5.6 C++ API: FAndroidApplication Class Reference
FAndroidApplication Class Reference
#include "AndroidApplication.h"
Public Member Functions
virtual ~FAndroidApplication ()
virtual void AddExternalInputDevice (TSharedPtr< class IInputDevice > InputDevice)
virtual IInputInterface * GetInputInterface () override
bool GetNativeWindowResolution (int32_t &OutWidth, int32_t &OutHeight) const
virtual FPlatformRect GetWorkArea (const FPlatformRect &CurrentWindow) const override
void InitializeWindow (const TSharedRef< FGenericWindow > &InWindow, const TSharedRef< FGenericWindowDefinition > &InDefinition, const TSharedPtr< FGenericWindow > &InParent, const bool bShowImmediately)
virtual bool IsGamepadAttached () const override
virtual TSharedRef< FGenericWindow > MakeWindow () override
virtual void PollGameDeviceState (const float TimeDelta) override
void SetMessageHandler (const TSharedRef< FGenericApplicationMessageHandler > &InMessageHandler)
virtual void Tick (const float TimeDelta) override
Public Member Functions inherited from GenericApplication
APPLICATIONCORE_API GenericApplication (const TSharedPtr< ICursor > &InCursor)
virtual APPLICATIONCORE_API ~GenericApplication ()
virtual void AddPendingConsoleCommand (const FString &InCommand)
virtual bool ApplicationLicenseValid (FPlatformUserId PlatformUser=PLATFORMUSERID_NONE)
DECLARE_EVENT (FSlateApplication, FOnClipboardContentChanged)
DECLARE_EVENT (FSlateApplication, FVirtualKeyboardHiddenEvent)
DECLARE_EVENT_OneParam (FSlateApplication, FVirtualKeyboardShownEvent, FPlatformRect)
Delegate for virtual keyboard being shown/hidden in case UI wants to slide out of the way.
DECLARE_EVENT_OneParam (GenericApplication, FOnDisplayMetricsChanged, const FDisplayMetrics &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnConsoleCommandAdded, const FString &)
virtual void DestroyApplication ()
virtual void FinishedInputThisFrame ()
virtual void * GetCapture (void) const
virtual void GetInitialDisplayMetrics (FDisplayMetrics &OutDisplayMetrics) const
TSharedRef< FGenericApplicationMessageHandler > GetMessageHandler ()
virtual FModifierKeysState GetModifierKeys () const
virtual ITextInputMethodSystem * GetTextInputMethodSystem ()
Function to return the current implementation of the Text Input Method System.
virtual EWindowTitleAlignment::Type GetWindowTitleAlignment () const
Gets the horizontal alignment of the window title bar's title text.
virtual EWindowTransparency GetWindowTransparencySupport () const
virtual TSharedPtr< FGenericWindow > GetWindowUnderCursor ()
virtual bool IsAllowedToRender () const
virtual bool IsCursorDirectlyOverSlateWindow () const
virtual bool IsMinimized () const
virtual bool IsMouseAttached () const
virtual bool IsUsingHighPrecisionMouseMode () const
virtual bool IsUsingTrackpad () const
FOnClipboardContentChanged & OnClipboardContentChanged ()
FOnDisplayMetricsChanged & OnDisplayMetricsChanged ()
Notifies subscribers when any of the display metrics change: e.g.
FVirtualKeyboardHiddenEvent & OnVirtualKeyboardHidden ()
FVirtualKeyboardShownEvent & OnVirtualKeyboardShown ()
virtual void ProcessDeferredEvents (const float TimeDelta)
virtual void PumpMessages (const float TimeDelta)
virtual void RegisterConsoleCommandListener (const FOnConsoleCommandListener &InListener)
virtual void SendAnalytics (IAnalyticsProvider *Provider)
Send any analytics captured by the application.
virtual void SetCapture (const TSharedPtr< FGenericWindow > &InWindow)
virtual void SetHighPrecisionMouseMode (const bool Enable, const TSharedPtr< FGenericWindow > &InWindow)
virtual void ShowSystemHelp ()
virtual bool SupportsSystemHelp () const
virtual bool TryCalculatePopupWindowPosition (const FPlatformRect &InAnchor, const FVector2D &InSize, const FVector2D &ProposedPlacement, const EPopUpOrientation::Type Orientation, FVector2D *const CalculatedPopUpPosition) const
Static Public Member Functions
static FAndroidApplication * CreateAndroidApplication ()
static FAndroidApplication * Get ()
static void OnWindowSizeChanged ()
Static Public Attributes
static TAutoConsoleVariable< bool > CVarAndroidSupportsDynamicResolution
static TAutoConsoleVariable< bool > CVarAndroidSupportsTimestampQueries
Protected Member Functions
FAndroidApplication ()
FAndroidApplication (TSharedPtr< class FAndroidInputInterface > InInputInterface)
Protected Member Functions inherited from GenericApplication
void BroadcastDisplayMetricsChanged (const FDisplayMetrics &InMetrics)
Trigger the OnDisplayMetricsChanged event with the argument 'InMetrics'.
Private Member Functions
void HandleDeviceOrientation ()
Private Attributes
bool bHasLoadedInputPlugins
EDeviceScreenOrientation DeviceOrientation
TSharedPtr< class FAndroidInputInterface > InputInterface
TArray< TSharedRef< FAndroidWindow > > Windows
Static Private Attributes
static FAndroidApplication * _application
static bool bWindowSizeChanged
Additional Inherited Members
Public Types inherited from GenericApplication
typedef FOnConsoleCommandAdded::FDelegate FOnConsoleCommandListener
Data Fields inherited from GenericApplication
const TSharedPtr< ICursor > Cursor
Protected Attributes inherited from GenericApplication
TSharedRef< class FGenericApplicationMessageHandler > MessageHandler
FOnClipboardContentChanged OnClipboardContentChangedEvent
Delegate for clipboard contents change.
FOnDisplayMetricsChanged OnDisplayMetricsChangedEvent
FVirtualKeyboardHiddenEvent VirtualKeyboardHiddenEvent
Delegate for virtual keyboard being shown.
FVirtualKeyboardShownEvent VirtualKeyboardShownEvent
Delegate for virtual keyboard being shown.
Detailed Description
Definition at line 27 of file AndroidApplication.h.
Constructor & Destructor Documentation
~FAndroidApplication()
virtual FAndroidApplication::~FAndroidApplication () inline virtual
Definition at line 73 of file AndroidApplication.h.
FAndroidApplication() [1/2]
FAndroidApplication::FAndroidApplication () protected
Referenced by CreateAndroidApplication(), and Get().
FAndroidApplication() [2/2]
FAndroidApplication::FAndroidApplication (TSharedPtr< class FAndroidInputInterface > InInputInterface) protected
Member Function Documentation
AddExternalInputDevice()
virtual void FAndroidApplication::AddExternalInputDevice (TSharedPtr< class IInputDevice > InputDevice) virtual
CreateAndroidApplication()
FAndroidApplication * FAndroidApplication::CreateAndroidApplication () static
References FAndroidApplication(), and FORCEINLINE.
Get()
FAndroidApplication * FAndroidApplication::Get () inline static
Definition at line 69 of file AndroidApplication.h.
References FAndroidApplication(), and _application.
GetInputInterface()
virtual IInputInterface * FAndroidApplication::GetInputInterface () override virtual
Reimplemented from GenericApplication.
GetNativeWindowResolution()
bool FAndroidApplication::GetNativeWindowResolution (int32_t & OutWidth, int32_t & OutHeight) const
GetWorkArea()
virtual FPlatformRect FAndroidApplication::GetWorkArea (const FPlatformRect & CurrentWindow) const override virtual
Reimplemented from GenericApplication.
HandleDeviceOrientation()
void FAndroidApplication::HandleDeviceOrientation () private
InitializeWindow()
void FAndroidApplication::InitializeWindow (const TSharedRef< FGenericWindow > & InWindow, const TSharedRef< FGenericWindowDefinition > & InDefinition, const TSharedPtr< FGenericWindow > & InParent, const bool bShowImmediately) virtual
Reimplemented from GenericApplication.
IsGamepadAttached()
virtual bool FAndroidApplication::IsGamepadAttached () const override virtual
Reimplemented from GenericApplication.
MakeWindow()
virtual TSharedRef< FGenericWindow > FAndroidApplication::MakeWindow () override virtual
Reimplemented from GenericApplication.
OnWindowSizeChanged()
void FAndroidApplication::OnWindowSizeChanged () static
PollGameDeviceState()
virtual void FAndroidApplication::PollGameDeviceState (const float TimeDelta) override virtual
Reimplemented from GenericApplication.
SetMessageHandler()
void FAndroidApplication::SetMessageHandler (const TSharedRef< FGenericApplicationMessageHandler > & InMessageHandler) virtual
Reimplemented from GenericApplication.
Tick()
virtual void FAndroidApplication::Tick (const float TimeDelta) override virtual
Reimplemented from GenericApplication.
Field Documentation
_application
FAndroidApplication* FAndroidApplication::_application static private
Definition at line 115 of file AndroidApplication.h.
Referenced by Get().
bHasLoadedInputPlugins
bool FAndroidApplication::bHasLoadedInputPlugins private
Definition at line 109 of file AndroidApplication.h.
bWindowSizeChanged
bool FAndroidApplication::bWindowSizeChanged static private
Definition at line 113 of file AndroidApplication.h.
CVarAndroidSupportsDynamicResolution
TAutoConsoleVariable<bool> FAndroidApplication::CVarAndroidSupportsDynamicResolution static
Definition at line 98 of file AndroidApplication.h.
CVarAndroidSupportsTimestampQueries
TAutoConsoleVariable<bool> FAndroidApplication::CVarAndroidSupportsTimestampQueries static
Definition at line 97 of file AndroidApplication.h.
DeviceOrientation
EDeviceScreenOrientation FAndroidApplication::DeviceOrientation private
Definition at line 117 of file AndroidApplication.h.
InputInterface
TSharedPtr< class FAndroidInputInterface > FAndroidApplication::InputInterface private
Definition at line 108 of file AndroidApplication.h.
Windows
TArray< TSharedRef< FAndroidWindow > > FAndroidApplication::Windows private
Definition at line 111 of file AndroidApplication.h.
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/Android/AndroidApplication.h