Unreal Engine 5.6 C++ API: FHLODActorDesc Class Reference
FHLODActorDesc Class Reference
ActorDesc for AWorldPartitionHLOD.
#include "HLODActorDesc.h"
Public Types
typedef TMap< FName, int64 > FStats
Public Types inherited from FWorldPartitionActorDesc
enum class EToStringMode : uint8 {
Guid , Compact , Full , Verbose ,
ForDiff
}
using FActorDescDeprecator = TFunction<void(FArchive&, FWorldPartitionActorDesc*)>
Public Member Functions
const TArray< FGuid > & GetChildHLODActors () const
const TArray< FGuid > & GetExternalChildHLODActors () const
const FTopLevelAssetPath & GetSourceHLODLayer () const
int64 GetStat (FName InStatName) const
const FStats & GetStats () const
Public Member Functions inherited from FWorldPartitionActorDesc
virtual ~FWorldPartitionActorDesc ()
void AddProperty (FName PropertyName, FName PropertyValue=NAME_None)
virtual void CheckForErrors (const IWorldPartitionActorDescInstanceView *InActorDescView, IStreamingGenerationErrorHandler *ErrorHandler) const
bool GetActorIsEditorOnly () const
bool GetActorIsEditorOnlyLoadedInPIE () const
bool GetActorIsHLODRelevant () const
bool GetActorIsRuntimeOnly () const
FName GetActorLabel () const
FName GetActorLabelOrName () const
const FString & GetActorLabelString () const
FName GetActorName () const
const FString & GetActorNameString () const
UClass * GetActorNativeClass () const
FName GetActorPackage () const
FSoftObjectPath GetActorSoftPath () const
const FTransform & GetActorTransform () const
FTopLevelAssetPath GetBaseClass () const
virtual UActorDescContainer * GetChildContainer () const
virtual const FWorldPartitionActorFilter * GetChildContainerFilter () const
virtual EWorldPartitionActorFilterType GetChildContainerFilterType () const
virtual FString GetChildContainerName () const
virtual FName GetChildContainerPackage () const
FGuid GetContentBundleGuid () const
TArray< FName > GetDataLayers (bool bIncludeExternalDataLayer=true) const
FName GetDisplayClassName () const
const FString & GetDisplayClassNameString () const
FBox GetEditorBounds () const
FName GetExternalDataLayer () const
const FSoftObjectPath & GetExternalDataLayerAsset () const
const FGuid & GetFolderGuid () const
FName GetFolderPath () const
const FGuid & GetGuid () const
FSoftObjectPath GetHLODLayer () const
bool GetIsSpatiallyLoaded () const
bool GetIsSpatiallyLoadedRaw () const
FTopLevelAssetPath GetNativeClass () const
const FGuid & GetParentActor () const
bool GetProperty (FName PropertyName, FName *PropertyValue) const
FBox GetRuntimeBounds () const
FName GetRuntimeGrid () const
virtual const FGuid & GetSceneOutlinerParent () const
const TArray< FName > & GetTags () const
bool HasProperty (FName PropertyName) const
virtual bool HasStandaloneHLOD () const
virtual void Init (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsChildContainerInstance () const
bool IsDefaultActorDesc () const
bool IsListedInSceneOutliner () const
bool IsMainWorldOnly () const
virtual bool IsResaveNeeded () const
bool IsUsingDataLayerAsset () const
bool operator== (const FWorldPartitionActorDesc &Other) const
void SerializeTo (TArray< uint8 > &OutData, FWorldPartitionActorDesc *BaseDesc=nullptr) const
virtual bool ShouldResave (const FWorldPartitionActorDesc *Other) const
Returns true if resaving this actor will have an impact on streaming generation.
FString ToString (EToStringMode Mode=EToStringMode::Compact) const
UE_DEPRECATED (5.1, "SetIsSpatiallyLoadedRaw is deprecated and should not be used.") inline void SetIsSpatiallyLoadedRaw(bool bNewIsSpatiallyLoaded)
UE_DEPRECATED (5.2, "GetBounds is deprecated, GetEditorBounds or GetRuntimeBounds should be used instead.") FBox GetBounds() const
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "GetOrigin is deprecated.") inline FVector GetOrigin() const
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.2, "ShouldValidateRuntimeGrid is deprecated and should not be used") virtual bool ShouldValidateRuntimeGrid() const
UE_DEPRECATED (5.3, "GetLevelPackage is deprecated use GetChildContainerPackage instead") virtual FName GetLevelPackage() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::GetUnloadedReason") FText GetUnloadedReason() const
UE_DEPRECATED (5.4, "Please use FWorldPartitionActorDescInstance::SetUnloadedReason") void SetUnloadedReason(FText *InUnloadedReason)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::GetDataLayerInstanceNames") TArray< FName > GetDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::HasResolvedDataLayerInstanceNames") inline bool HasResolvedDataLayerInstanceNames() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsEditorRelevant instead") virtual bool IsEditorRelevant() const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::IsRuntimeRelevant instead") virtual bool IsRuntimeRelevant(const FActorContainerID &InContainerID) const
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance::SetDataLayerInstanceNames") inline void SetDataLayerInstanceNames(const TArray< FName > &InDataLayerInstanceNames)
UE_DEPRECATED (5.4, "Use GetChildContainerFilter instead") virtual const FWorldPartitionActorFilter *GetContainerFilter() const
UE_DEPRECATED (5.4, "Use GetChildContainerFilterType instead") virtual EWorldPartitionActorFilterType GetContainerFilterType() const
UE_DEPRECATED (5.4, "Use GetChildContainerInstance instead") virtual bool GetContainerInstance(FContainerInstance &OutContainerInstance) const
UE_DEPRECATED (5.4, "Use GetChildContainerPackage instead") virtual FName GetContainerPackage() const
UE_DEPRECATED (5.4, "Use IsChildContainerInstance instead") virtual bool IsContainerInstance() const
UE_DEPRECATED (5.4, "Use SetContainer without World param") virtual void SetContainer(UActorDescContainer *InContainer
Protected Member Functions
FHLODActorDesc ()
virtual bool Equals (const FWorldPartitionActorDesc *Other) const override
virtual uint32 GetSizeOf () const override
virtual void Init (const AActor *InActor) override
virtual bool IsRuntimeRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const override
virtual void Serialize (FArchive &Ar) override
Protected Member Functions inherited from FWorldPartitionActorDesc
FWorldPartitionActorDesc ()
virtual UActorDescContainerInstance * CreateChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance) const
virtual bool GetChildContainerInstance (const FWorldPartitionActorDescInstance *InActorDescInstance, FContainerInstance &OutContainerInstance) const
virtual UWorldPartition * GetLoadedChildWorldPartition (const FWorldPartitionActorDescInstance *InActorDescInstance) const
void InitTransientProperties (const FWorldPartitionActorDescInitData &DescData)
virtual bool IsEditorRelevant (const FWorldPartitionActorDescInstance *InActorDescInstance) const
void SetEditorBounds (const FBox &InEditorBounds)
void SetRuntimeBounds (const FBox &InRuntimeBounds)
virtual void TransferFrom (const FWorldPartitionActorDesc *From)
virtual void TransferWorldData (const FWorldPartitionActorDesc *From)
Protected Attributes
TArray< FGuid > ChildHLODActors
TArray< FGuid > ExternalChildHLODActors
FStats HLODStats
FTopLevelAssetPath SourceHLODLayer
Protected Attributes inherited from FWorldPartitionActorDesc
FString ActorDisplayClassNameString
FName ActorLabel
FString ActorLabelString
FName ActorName
FString ActorNameString
UClass * ActorNativeClass
FName ActorPackage
FSoftObjectPath ActorPath
FTransform ActorTransform
FTransform ActorTransformRelative
bool bActorIsEditorOnly
bool bActorIsHLODRelevant
bool bActorIsListedInSceneOutliner
bool bActorIsMainWorldOnly
bool bActorIsRuntimeOnly
FTopLevelAssetPath BaseClass
bool bHasValidRelativeBounds
bool bIsDefaultActorDesc
bool bIsSpatiallyLoaded
bool bIsUsingDataLayerAsset
UActorDescContainer * Container
FGuid ContentBundleGuid
TArray< FName > DataLayers
FBox EditorBounds
FWorldPartitionRelativeBounds EditorBoundsRelative
TArray< FGuid > EditorOnlyReferences
FSoftObjectPath ExternalDataLayerAsset
FGuid FolderGuid
FName FolderPath
FGuid Guid
FSoftObjectPath HLODLayer
FTopLevelAssetPath NativeClass
FGuid ParentActor
FPropertyPairsMap Properties
TArray< FGuid > References
FBox RuntimeBounds
FWorldPartitionRelativeBounds RuntimeBoundsRelative
FName RuntimeGrid
TArray< FName > Tags
Friends
class AWorldPartitionHLOD
class FHLODActorDescFactory
Additional Inherited Members
Static Public Member Functions inherited from FWorldPartitionActorDesc
static void Patch (const FWorldPartitionActorDescInitData &DescData, TArray< uint8 > &OutData, FWorldPartitionAssetDataPatcher *InAssetDataPatcher)
static void RegisterActorDescDeprecator (TSubclassOf< AActor > ActorClass, const FActorDescDeprecator &Deprecator)
Data Fields inherited from FWorldPartitionActorDesc
UWorld * InWorldContext
Static Protected Attributes inherited from FWorldPartitionActorDesc
static TMap< TSubclassOf< AActor >, FActorDescDeprecator > Deprecators
Detailed Description
ActorDesc for AWorldPartitionHLOD.
Definition at line 20 of file HLODActorDesc.h.
Member Typedef Documentation
FStats
typedef TMap<FName, int64> FHLODActorDesc::FStats
Definition at line 26 of file HLODActorDesc.h.
Constructor & Destructor Documentation
FHLODActorDesc()
FHLODActorDesc::FHLODActorDesc () protected
Referenced by GetSizeOf().
Member Function Documentation
Equals()
virtual bool FHLODActorDesc::Equals (const FWorldPartitionActorDesc * Other) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDesc(), and Other.
GetChildHLODActors()
const TArray< FGuid > & FHLODActorDesc::GetChildHLODActors () const inline
Definition at line 28 of file HLODActorDesc.h.
References ChildHLODActors.
GetExternalChildHLODActors()
const TArray< FGuid > & FHLODActorDesc::GetExternalChildHLODActors () const inline
Definition at line 29 of file HLODActorDesc.h.
References ExternalChildHLODActors.
GetSizeOf()
virtual uint32 FHLODActorDesc::GetSizeOf () const inline override protected virtual
Reimplemented from FWorldPartitionActorDesc.
Definition at line 40 of file HLODActorDesc.h.
References FHLODActorDesc().
GetSourceHLODLayer()
const FTopLevelAssetPath & FHLODActorDesc::GetSourceHLODLayer () const inline
Definition at line 30 of file HLODActorDesc.h.
References SourceHLODLayer.
GetStat()
int64 FHLODActorDesc::GetStat (FName InStatName) const
GetStats()
const FStats & FHLODActorDesc::GetStats () const inline
Definition at line 31 of file HLODActorDesc.h.
References HLODStats.
Init()
virtual void FHLODActorDesc::Init (const AActor * InActor) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::AActor.
IsRuntimeRelevant()
virtual bool FHLODActorDesc::IsRuntimeRelevant (const FWorldPartitionActorDescInstance * InActorDescInstance) const override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References FWorldPartitionActorDesc::FWorldPartitionActorDescInstance.
Serialize()
virtual void FHLODActorDesc::Serialize (FArchive & Ar) override protected virtual
Reimplemented from FWorldPartitionActorDesc.
References Ar.
Friends And Related Symbol Documentation
AWorldPartitionHLOD
friend class AWorldPartitionHLOD friend
Definition at line 22 of file HLODActorDesc.h.
References AWorldPartitionHLOD.
Referenced by AWorldPartitionHLOD.
FHLODActorDescFactory
friend class FHLODActorDescFactory friend
Definition at line 23 of file HLODActorDesc.h.
References FHLODActorDescFactory.
Referenced by FHLODActorDescFactory.
Field Documentation
ChildHLODActors
TArray<FGuid> FHLODActorDesc::ChildHLODActors protected
Definition at line 45 of file HLODActorDesc.h.
Referenced by GetChildHLODActors().
ExternalChildHLODActors
TArray<FGuid> FHLODActorDesc::ExternalChildHLODActors protected
Definition at line 47 of file HLODActorDesc.h.
Referenced by GetExternalChildHLODActors().
HLODStats
FStats FHLODActorDesc::HLODStats protected
Definition at line 51 of file HLODActorDesc.h.
Referenced by GetStats().
SourceHLODLayer
FTopLevelAssetPath FHLODActorDesc::SourceHLODLayer protected
Definition at line 49 of file HLODActorDesc.h.
Referenced by GetSourceHLODLayer().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/HLOD/HLODActorDesc.h