Unreal Engine 5.6 C++ API: TReplyBase< ReplyType > Class Template Reference
TReplyBase< ReplyType > Class Template Reference
#include "ReplyBase.h"
Public Member Functions
TReplyBase (bool bIsHandled)
Public Member Functions inherited from FReplyBase
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately handled the event.
bool IsEventHandled () const
Protected Member Functions
ReplyType & Me ()
ReplyType & SetHandler (const TSharedRef< SWidget > &InHandler)
Set the widget that handled the event; undefined if never handled.
Protected Member Functions inherited from FReplyBase
FReplyBase (bool InIsHandled)
A reply can be handled or unhandled.
Friends
class FEventRouter
Additional Inherited Members
Protected Attributes inherited from FReplyBase
bool bIsHandled
Has a widget handled an event.
TSharedPtr< SWidget > EventHandler
Widget that handled the event that generated this reply.
Detailed Description
template<typename ReplyType>
class TReplyBase< ReplyType >
Definition at line 40 of file ReplyBase.h.
Constructor & Destructor Documentation
TReplyBase()
template<typename ReplyType> TReplyBase< ReplyType >::TReplyBase (bool bIsHandled) inline
Definition at line 43 of file ReplyBase.h.
References FReplyBase::FReplyBase(), and FReplyBase::bIsHandled.
Member Function Documentation
Me()
template<typename ReplyType> ReplyType & TReplyBase< ReplyType >::Me () inline protected
Returns
a reference to this reply
Definition at line 59 of file ReplyBase.h.
Referenced by SetHandler().
SetHandler()
template<typename ReplyType> ReplyType & TReplyBase< ReplyType >::SetHandler (const TSharedRef< SWidget > & InHandler) inline protected
Set the widget that handled the event; undefined if never handled.
This method is to be used by SlateApplication only!
Definition at line 52 of file ReplyBase.h.
References FReplyBase::EventHandler, and Me().
Friends And Related Symbol Documentation
FEventRouter
template<typename ReplyType> friend class FEventRouter friend
Definition at line 49 of file ReplyBase.h.
References FEventRouter.
Referenced by FEventRouter.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/ReplyBase.h