Unreal Engine 5.6 C++ API: TRigVMModelCachedValue< VersionObjectType, ValueType > Class Template Reference
TRigVMModelCachedValue< VersionObjectType, ValueType > Class Template Reference
A cached value which relies on a version providing object.
#include "RigVMModelCachedValue.h"
Public Member Functions
TRigVMModelCachedValue ()
TRigVMModelCachedValue (const VersionObjectType *InObject)
TRigVMModelCachedValue (VersionObjectType *InObject, const ValueType &InValue)
void Bind (const VersionObjectType *InVersionedObject)
const ValueType & Get (const ValueType &InDefault) const
const ValueType & GetValue () const
bool IsBound () const
bool IsValid () const
bool operator!= (const ValueType &InValueType) const
TRigVMModelCachedValue & operator= (const ValueType &InValueType)
bool operator== (const ValueType &InValueType) const
void ResetCachedValue ()
void Set (const ValueType &InValue)
void Unbind ()
Private Attributes
uint32 LastObjectVersion
TOptional< ValueType > Value
TWeakObjectPtr< const VersionObjectType > VersionedObjectWeakPtr
Detailed Description
template<typename VersionObjectType, typename ValueType>
class TRigVMModelCachedValue< VersionObjectType, ValueType >
A cached value which relies on a version providing object.
The versioned object needs to provide uint32 GetCachedValueVersion() Values within the cache are considered valid if they are a) set and b) the version of the cache matches the version of the versioned object.
Definition at line 14 of file RigVMModelCachedValue.h.
Constructor & Destructor Documentation
TRigVMModelCachedValue() [1/3]
template<typename VersionObjectType, typename ValueType> TRigVMModelCachedValue< VersionObjectType, ValueType >::TRigVMModelCachedValue () inline
Definition at line 19 of file RigVMModelCachedValue.h.
References LastObjectVersion.
Referenced by operator=().
TRigVMModelCachedValue() [2/3]
template<typename VersionObjectType, typename ValueType> TRigVMModelCachedValue< VersionObjectType, ValueType >::TRigVMModelCachedValue (const VersionObjectType * InObject) inline
Definition at line 25 of file RigVMModelCachedValue.h.
References LastObjectVersion, and VersionedObjectWeakPtr.
TRigVMModelCachedValue() [3/3]
template<typename VersionObjectType, typename ValueType> TRigVMModelCachedValue< VersionObjectType, ValueType >::TRigVMModelCachedValue (VersionObjectType * InObject, const ValueType & InValue) inline
Definition at line 32 of file RigVMModelCachedValue.h.
References LastObjectVersion, Set(), and VersionedObjectWeakPtr.
Member Function Documentation
Bind()
template<typename VersionObjectType, typename ValueType> void TRigVMModelCachedValue< VersionObjectType, ValueType >::Bind (const VersionObjectType * InVersionedObject) inline
Definition at line 59 of file RigVMModelCachedValue.h.
References ResetCachedValue(), and VersionedObjectWeakPtr.
Referenced by Unbind().
Get()
template<typename VersionObjectType, typename ValueType> const ValueType & TRigVMModelCachedValue< VersionObjectType, ValueType >::Get (const ValueType & InDefault) const inline
Definition at line 79 of file RigVMModelCachedValue.h.
References GetValue(), and IsValid().
GetValue()
template<typename VersionObjectType, typename ValueType> const ValueType & TRigVMModelCachedValue< VersionObjectType, ValueType >::GetValue () const inline
Definition at line 89 of file RigVMModelCachedValue.h.
References check, IsValid(), and Value.
Referenced by Get(), operator!=(), and operator==().
IsBound()
template<typename VersionObjectType, typename ValueType> bool TRigVMModelCachedValue< VersionObjectType, ValueType >::IsBound () const inline
Definition at line 53 of file RigVMModelCachedValue.h.
References VersionedObjectWeakPtr.
IsValid()
template<typename VersionObjectType, typename ValueType> bool TRigVMModelCachedValue< VersionObjectType, ValueType >::IsValid () const inline
Definition at line 40 of file RigVMModelCachedValue.h.
References LastObjectVersion, Value, and VersionedObjectWeakPtr.
Referenced by Get(), GetValue(), operator!=(), and operator==().
operator!=()
template<typename VersionObjectType, typename ValueType> bool TRigVMModelCachedValue< VersionObjectType, ValueType >::operator!= (const ValueType & InValueType) const inline
Definition at line 130 of file RigVMModelCachedValue.h.
References GetValue(), and IsValid().
operator=()
template<typename VersionObjectType, typename ValueType> TRigVMModelCachedValue & TRigVMModelCachedValue< VersionObjectType, ValueType >::operator= (const ValueType & InValueType) inline
Definition at line 113 of file RigVMModelCachedValue.h.
References TRigVMModelCachedValue(), and Set().
operator==()
template<typename VersionObjectType, typename ValueType> bool TRigVMModelCachedValue< VersionObjectType, ValueType >::operator== (const ValueType & InValueType) const inline
Definition at line 120 of file RigVMModelCachedValue.h.
References GetValue(), and IsValid().
ResetCachedValue()
template<typename VersionObjectType, typename ValueType> void TRigVMModelCachedValue< VersionObjectType, ValueType >::ResetCachedValue () inline
Definition at line 106 of file RigVMModelCachedValue.h.
References LastObjectVersion, and Value.
Referenced by Bind().
Set()
template<typename VersionObjectType, typename ValueType> void TRigVMModelCachedValue< VersionObjectType, ValueType >::Set (const ValueType & InValue) inline
Definition at line 96 of file RigVMModelCachedValue.h.
References check, LastObjectVersion, Value, and VersionedObjectWeakPtr.
Referenced by TRigVMModelCachedValue(), and operator=().
Unbind()
template<typename VersionObjectType, typename ValueType> void TRigVMModelCachedValue< VersionObjectType, ValueType >::Unbind () inline
Definition at line 73 of file RigVMModelCachedValue.h.
References Bind().
Field Documentation
LastObjectVersion
template<typename VersionObjectType, typename ValueType> uint32 TRigVMModelCachedValue< VersionObjectType, ValueType >::LastObjectVersion private
Definition at line 143 of file RigVMModelCachedValue.h.
Referenced by TRigVMModelCachedValue(), TRigVMModelCachedValue(), TRigVMModelCachedValue(), IsValid(), ResetCachedValue(), and Set().
Value
template<typename VersionObjectType, typename ValueType> TOptional<ValueType> TRigVMModelCachedValue< VersionObjectType, ValueType >::Value private
Definition at line 142 of file RigVMModelCachedValue.h.
Referenced by GetValue(), IsValid(), ResetCachedValue(), and Set().
VersionedObjectWeakPtr
template<typename VersionObjectType, typename ValueType> TWeakObjectPtr<const VersionObjectType> TRigVMModelCachedValue< VersionObjectType, ValueType >::VersionedObjectWeakPtr private
Definition at line 141 of file RigVMModelCachedValue.h.
Referenced by TRigVMModelCachedValue(), TRigVMModelCachedValue(), Bind(), IsBound(), IsValid(), and Set().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMModel/RigVMModelCachedValue.h