Unreal Engine 5.6 C++ API: Metasound::IDataTransmissionBase Class Reference
Metasound::IDataTransmissionBase Class Reference
#include "MetasoundRouter.h"
Public Member Functions
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Protected Attributes
FName DataType
Detailed Description
Definition at line 184 of file MetasoundRouter.h.
Constructor & Destructor Documentation
IDataTransmissionBase() [1/2]
Metasound::IDataTransmissionBase::IDataTransmissionBase () delete
Referenced by Metasound::IDataChannel::IDataChannel(), Metasound::IReceiver::IReceiver(), and Metasound::ISender::ISender().
IDataTransmissionBase() [2/2]
Metasound::IDataTransmissionBase::IDataTransmissionBase (FName InDataType) inline
Definition at line 189 of file MetasoundRouter.h.
References DataType.
~IDataTransmissionBase()
virtual Metasound::IDataTransmissionBase::~IDataTransmissionBase () virtual default
Member Function Documentation
CheckType()
template<typename TSenderImplementation> bool Metasound::IDataTransmissionBase::CheckType () const inline
Definition at line 197 of file MetasoundRouter.h.
References DataType, ensureAlwaysMsgf, TEXT, and FName::ToString().
Referenced by GetAs(), and GetAs().
GetAs() [1/2]
template<typename TSenderImplementation> TSenderImplementation & Metasound::IDataTransmissionBase::GetAs () inline
Definition at line 211 of file MetasoundRouter.h.
References check, and CheckType().
GetAs() [2/2]
template<typename TSenderImplementation> const TSenderImplementation & Metasound::IDataTransmissionBase::GetAs () const inline
Definition at line 204 of file MetasoundRouter.h.
References check, and CheckType().
Referenced by Metasound::TCopyableDataChannel< TDataType >::PopOpaque(), Metasound::TCopyableDataChannel< TDataType >::PushOpaque(), and Metasound::Frontend::FMetasoundAnalyzerView::TryGetOutputData().
GetDataType()
FName Metasound::IDataTransmissionBase::GetDataType () const inline
Definition at line 217 of file MetasoundRouter.h.
References DataType.
Field Documentation
DataType
FName Metasound::IDataTransmissionBase::DataType protected
Definition at line 224 of file MetasoundRouter.h.
Referenced by Metasound::IDataChannel::IDataChannel(), IDataTransmissionBase(), Metasound::IReceiver::IReceiver(), Metasound::ISender::ISender(), CheckType(), and GetDataType().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h