Unreal Engine 5.6 C++ API: IPlatformChunkInstall Class Reference
IPlatformChunkInstall Class Reference abstract
Interface for platform specific chunk based install.
#include "GenericPlatformChunkInstall.h"
Public Member Functions
virtual ~IPlatformChunkInstall ()
Virtual destructor.
virtual FDelegateHandle AddChunkInstallDelegate (FPlatformChunkInstallDelegate Delegate)=0
Request a delegate callback on chunk install completion or failure.
virtual FDelegateHandle AddNamedChunkCompleteDelegate (FPlatformNamedChunkCompleteDelegate Delegate)=0
Request a delegate callback on named chunk install completion or failure.
virtual void AsyncInit (TFunction< void(bool)> OnInitComplete)=0
Initialize the platform chunk installer in the background.
virtual bool DebugStartNextChunk ()=0
For platforms that support emulation of the Chunk install.
virtual void ExternalNotifyChunkAvailable (uint32 InChunkID)=0
Allow an external system to notify that a particular chunk ID has become available Initial use-case is for dynamically encrypted pak files to signal to the outside world that it has become available.
virtual float GetChunkProgress (uint32 ChunkID, EChunkProgressReportingType::Type ReportType)=0
Get the current install progress of a chunk.
virtual EChunkInstallSpeed::Type GetInstallSpeed ()=0
Inquire about the priority of chunk installation vs.
virtual bool GetNamedChunkInstallationStatus (const FName NamedChunk, FChunkInstallationStatusDetail &OutChunkStatusDetail) const =0
Get detailed installation status for the given named chunk.
virtual EChunkLocation::Type GetNamedChunkLocation (const FName NamedChunk)=0
Get the current location of the given named chunk.
virtual float GetNamedChunkProgress (const FName NamedChunk, EChunkProgressReportingType::Type ReportType)=0
Get the current install progress of the given named chunk.
virtual TArray< FName > GetNamedChunksByType (ENamedChunkType NamedChunkType) const =0
Get a list of all the named chunks of the given type.
virtual ENamedChunkType GetNamedChunkType (const FName NamedChunk) const =0
Query the type of the given named chunk.
virtual EChunkLocation::Type GetPakchunkLocation (int32 PakchunkIndex)=0
Get the current location of a chunk with pakchunk index.
virtual bool GetPakFilesInNamedChunk (const FName NamedChunk, TArray< FString > &OutFilesInChunk) const =0
Get the list of pak files in the given named chunk.
virtual bool GetProgressReportingTypeSupported (EChunkProgressReportingType::Type ReportType)=0
Check if a given reporting type is supported.
virtual bool InstallNamedChunk (const FName NamedChunk)=0
Install the given named chunk.
virtual bool InstallNamedChunks (const TArrayView< const FName > &NamedChunks)=0
Install the given set of named chunks.
virtual bool IsAvailable () const =0
Returns whether chunk installation is available (i.e.
virtual bool IsNamedChunkForCurrentLocale (const FName NamedChunk) const =0
Determine if the given named chunk is suitable for the current system locale.
virtual bool IsNamedChunkInProgress (const FName NamedChunk)=0
Check whether the give chunk is being installed.
virtual bool PrioritizeNamedChunk (const FName NamedChunk, EChunkPriority::Type Priority)=0
Hint to the installer that we would like to prioritize a specific chunk.
virtual bool PrioritizePakchunk (int32 PakchunkIndex, EChunkPriority::Type Priority)=0
Hint to the installer that we would like to prioritize a specific chunk.
virtual void RemoveChunkInstallDelegate (FDelegateHandle Delegate)=0
Remove a delegate callback on chunk install completion.
virtual void RemoveNamedChunkCompleteDelegate (FDelegateHandle Delegate)=0
Remove a delegate callback on named chunk install completion.
virtual bool SetAutoPakMountingEnabled (bool bEnabled)=0
Set whether pak files are auto-mounted when they are installed (the default is that they are mounted)
virtual bool SetInstallSpeed (EChunkInstallSpeed::Type InstallSpeed)=0
Specify the priority of chunk installation vs.
virtual bool SupportsBundleSource () const =0
Returns whether this platform chunk installer implements all the API functions to support the platform chunk install bundle source.
virtual bool SupportsNamedChunkInstall () const =0
Check whether current platform supports chunk installation by name.
UE_DEPRECATED (5.4, "use AddNamedChunkCompleteDelegate instead") virtual FDelegateHandle AddNamedChunkInstallDelegate(FPlatformNamedChunkInstallDelegate Delegate)=0
Request a delegate callback on named chunk install completion or failure.
UE_DEPRECATED (5.4, "use RemoveNamedChunkCompleteDelegate instead") virtual void RemoveNamedChunkInstallDelegate(FDelegateHandle Delegate)=0
Remove a delegate callback on named chunk install completion.
virtual bool UninstallNamedChunk (const FName NamedChunk)=0
Uninstall the given named chunk.
virtual bool UninstallNamedChunks (const TArrayView< const FName > &NamedChunks)=0
Uninstall the given set of named chunks.
Protected Member Functions
virtual EChunkLocation::Type GetChunkLocation (uint32 ChunkID)=0
Get the current location of a chunk.
virtual bool PrioritizeChunk (uint32 ChunkID, EChunkPriority::Type Priority)=0
Hint to the installer that we would like to prioritize a specific chunk.
Detailed Description
Interface for platform specific chunk based install.
Definition at line 132 of file GenericPlatformChunkInstall.h.
Constructor & Destructor Documentation
~IPlatformChunkInstall()
virtual IPlatformChunkInstall::~IPlatformChunkInstall () inline virtual
Virtual destructor.
Definition at line 137 of file GenericPlatformChunkInstall.h.
Member Function Documentation
AddChunkInstallDelegate()
virtual FDelegateHandle IPlatformChunkInstall::AddChunkInstallDelegate (FPlatformChunkInstallDelegate Delegate) pure virtual
Request a delegate callback on chunk install completion or failure.
Request may not be respected.
Parameters
Delegate The delegate to call when any chunk is installed or fails to install
Returns
Handle to the bound delegate
Implemented in FGenericPlatformChunkInstall.
AddNamedChunkCompleteDelegate()
virtual FDelegateHandle IPlatformChunkInstall::AddNamedChunkCompleteDelegate (FPlatformNamedChunkCompleteDelegate Delegate) pure virtual
Request a delegate callback on named chunk install completion or failure.
Request may not be respected.
Parameters
Delegate The delegate to call when any named chunk is installed or fails to install
Returns
Handle to the bound delegate
Implemented in FGenericPlatformChunkInstall.
References AddNamedChunkCompleteDelegate().
Referenced by AddNamedChunkCompleteDelegate().
AsyncInit()
virtual void IPlatformChunkInstall::AsyncInit (TFunction< void(bool)> OnInitComplete) pure virtual
Initialize the platform chunk installer in the background.
May require opt-in for the platform-specific chunk installer due to backwards compatility concerns.
Parameters
OnInitialized Callback for when asyncronous initialization is completed.
Implemented in FGenericPlatformChunkInstall.
DebugStartNextChunk()
virtual bool IPlatformChunkInstall::DebugStartNextChunk () pure virtual
For platforms that support emulation of the Chunk install.
Starts transfer of the next chunk. Does nothing in a shipping build.
Returns
true if the operation succeeds.
Implemented in FGenericPlatformChunkInstall.
ExternalNotifyChunkAvailable()
virtual void IPlatformChunkInstall::ExternalNotifyChunkAvailable (uint32 InChunkID) pure virtual
Allow an external system to notify that a particular chunk ID has become available Initial use-case is for dynamically encrypted pak files to signal to the outside world that it has become available.
Parameters
InChunkID - ID of the chunk that has just become available
Implemented in FGenericPlatformChunkInstall.
GetChunkLocation()
virtual EChunkLocation::Type IPlatformChunkInstall::GetChunkLocation (uint32 ChunkID) protected pure virtual
Get the current location of a chunk.
Pakchunk index and platform chunk id are not always the same. Call GetPakchunkLocation instead of calling from outside.
Parameters
ChunkID The id of the chunk to check.
Returns
Enum specifying whether the chunk is available to use, waiting to install, or does not exist.
Implemented in FGenericPlatformChunkInstall.
References GetChunkLocation().
Referenced by GetChunkLocation(), and FGenericPlatformChunkInstall::GetPakchunkLocation().
GetChunkProgress()
virtual float IPlatformChunkInstall::GetChunkProgress (uint32 ChunkID, EChunkProgressReportingType::Type ReportType) pure virtual
Get the current install progress of a chunk.
Let the user specify report type for platforms that support more than one.
Parameters
ChunkID The id of the chunk to check.
ReportType The type of progress report you want.
Returns
A value whose meaning is dependent on the ReportType param.
Implemented in FGenericPlatformChunkInstall.
GetInstallSpeed()
virtual EChunkInstallSpeed::Type IPlatformChunkInstall::GetInstallSpeed () pure virtual
Inquire about the priority of chunk installation vs.
game IO.
Returns
Paused, low or high priority.
Implemented in FGenericPlatformChunkInstall.
GetNamedChunkInstallationStatus()
virtual bool IPlatformChunkInstall::GetNamedChunkInstallationStatus (const FName NamedChunk, FChunkInstallationStatusDetail & OutChunkStatusDetail) const pure virtual
Get detailed installation status for the given named chunk.
Parameters
NamedChunk The named chunk to query
OutChunkStatusDetail (out) structure that will contain the status detail
Returns
true if the structure has been filled in
Implemented in FGenericPlatformChunkInstall.
References GetNamedChunkInstallationStatus().
Referenced by GetNamedChunkInstallationStatus().
GetNamedChunkLocation()
virtual EChunkLocation::Type IPlatformChunkInstall::GetNamedChunkLocation (const FName NamedChunk) pure virtual
Get the current location of the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
Enum specifying whether the chunk is available to use, waiting to install, or does not exist.
Implemented in FGenericPlatformChunkInstall.
GetNamedChunkProgress()
virtual float IPlatformChunkInstall::GetNamedChunkProgress (const FName NamedChunk, EChunkProgressReportingType::Type ReportType) pure virtual
Get the current install progress of the given named chunk.
Let the user specify report type for platforms that support more than one.
Parameters
NamedChunk The name of the chunk
ReportType The type of progress report you want.
Returns
A value whose meaning is dependent on the ReportType param.
Implemented in FGenericPlatformChunkInstall.
GetNamedChunksByType()
virtual TArray< FName > IPlatformChunkInstall::GetNamedChunksByType (ENamedChunkType NamedChunkType) const pure virtual
Get a list of all the named chunks of the given type.
Parameters
Enum indicating the type of chunk
Returns
Array containing all named chunks of the given type
Implemented in FGenericPlatformChunkInstall.
GetNamedChunkType()
virtual ENamedChunkType IPlatformChunkInstall::GetNamedChunkType (const FName NamedChunk) const pure virtual
Query the type of the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
Enum indicating the type of chunk, if any
Implemented in FGenericPlatformChunkInstall.
GetPakchunkLocation()
virtual EChunkLocation::Type IPlatformChunkInstall::GetPakchunkLocation (int32 PakchunkIndex) pure virtual
Get the current location of a chunk with pakchunk index.
Parameters
PakchunkIndex The id of the pak chunk.
Returns
Enum specifying whether the chunk is available to use, waiting to install, or does not exist.
Implemented in FGenericPlatformChunkInstall.
GetPakFilesInNamedChunk()
virtual bool IPlatformChunkInstall::GetPakFilesInNamedChunk (const FName NamedChunk, TArray< FString > & OutFilesInChunk) const pure virtual
Get the list of pak files in the given named chunk.
Parameters
NamedChunk The named chunk to query
OutFilesInChunk The pak files names in the named chunk
Returns
true if the named chunk is valid and this function is supported
Implemented in FGenericPlatformChunkInstall.
References GetPakFilesInNamedChunk().
Referenced by GetPakFilesInNamedChunk().
GetProgressReportingTypeSupported()
virtual bool IPlatformChunkInstall::GetProgressReportingTypeSupported (EChunkProgressReportingType::Type ReportType) pure virtual
Check if a given reporting type is supported.
Parameters
ReportType Enum specifying how progress is reported.
Returns
true if reporting type is supported on the current platform.
Implemented in FGenericPlatformChunkInstall.
InstallNamedChunk()
virtual bool IPlatformChunkInstall::InstallNamedChunk (const FName NamedChunk) pure virtual
Install the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
whether installation task has been kicked
Implemented in FGenericPlatformChunkInstall.
InstallNamedChunks()
virtual bool IPlatformChunkInstall::InstallNamedChunks (const TArrayView< const FName > & NamedChunks) pure virtual
Install the given set of named chunks.
Parameters
NamedChunks The names of the chunks to install
Returns
whether installation task has been kicked
Implemented in FGenericPlatformChunkInstall.
Referenced by FGenericPlatformChunkInstall::InstallNamedChunk().
IsAvailable()
virtual bool IPlatformChunkInstall::IsAvailable () const pure virtual
Returns whether chunk installation is available (i.e.
we are an installed packaged build etc)
Implemented in FGenericPlatformChunkInstall.
IsNamedChunkForCurrentLocale()
virtual bool IPlatformChunkInstall::IsNamedChunkForCurrentLocale (const FName NamedChunk) const pure virtual
Determine if the given named chunk is suitable for the current system locale.
Parameters
NamedChunk The named chunk to query
Returns
false if the chunk is associated with a different locale
Implemented in FGenericPlatformChunkInstall.
References IsNamedChunkForCurrentLocale().
Referenced by IsNamedChunkForCurrentLocale().
IsNamedChunkInProgress()
virtual bool IPlatformChunkInstall::IsNamedChunkInProgress (const FName NamedChunk) pure virtual
Check whether the give chunk is being installed.
Parameters
NamedChunk The name of the chunk
Returns
whether installation task has been kicked
Implemented in FGenericPlatformChunkInstall.
PrioritizeChunk()
virtual bool IPlatformChunkInstall::PrioritizeChunk (uint32 ChunkID, EChunkPriority::Type Priority) protected pure virtual
Hint to the installer that we would like to prioritize a specific chunk.
Parameters
ChunkID The id of the chunk to prioritize.
Priority The priority for the chunk.
Returns
false if the operation is not allowed or the chunk doesn't exist, otherwise true.
Implemented in FGenericPlatformChunkInstall.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PrioritizeChunk().
Referenced by PrioritizeChunk(), and FGenericPlatformChunkInstall::PrioritizePakchunk().
PrioritizeNamedChunk()
virtual bool IPlatformChunkInstall::PrioritizeNamedChunk (const FName NamedChunk, EChunkPriority::Type Priority) pure virtual
Hint to the installer that we would like to prioritize a specific chunk.
Parameters
NamedChunk The name of the chunk
Priority The priority for the chunk.
Returns
false if the operation is not allowed or the chunk doesn't exist, otherwise true.
Implemented in FGenericPlatformChunkInstall.
PrioritizePakchunk()
virtual bool IPlatformChunkInstall::PrioritizePakchunk (int32 PakchunkIndex, EChunkPriority::Type Priority) pure virtual
Hint to the installer that we would like to prioritize a specific chunk.
Parameters
PakchunkIndex The index of the pakchunk to prioritize.
Priority The priority for the chunk.
Returns
false if the operation is not allowed or the chunk doesn't exist, otherwise true.
Implemented in FGenericPlatformChunkInstall.
RemoveChunkInstallDelegate()
virtual void IPlatformChunkInstall::RemoveChunkInstallDelegate (FDelegateHandle Delegate) pure virtual
Remove a delegate callback on chunk install completion.
Parameters
Delegate The delegate to remove.
Implemented in FGenericPlatformChunkInstall.
RemoveNamedChunkCompleteDelegate()
virtual void IPlatformChunkInstall::RemoveNamedChunkCompleteDelegate (FDelegateHandle Delegate) pure virtual
Remove a delegate callback on named chunk install completion.
Parameters
Delegate The delegate to remove.
Implemented in FGenericPlatformChunkInstall.
References RemoveNamedChunkCompleteDelegate().
Referenced by RemoveNamedChunkCompleteDelegate().
SetAutoPakMountingEnabled()
virtual bool IPlatformChunkInstall::SetAutoPakMountingEnabled (bool bEnabled) pure virtual
Set whether pak files are auto-mounted when they are installed (the default is that they are mounted)
Parameters
bEnabled Whether to auto-mount pak files
Returns
false if this function is not supported
Implemented in FGenericPlatformChunkInstall.
References SetAutoPakMountingEnabled().
Referenced by SetAutoPakMountingEnabled().
SetInstallSpeed()
virtual bool IPlatformChunkInstall::SetInstallSpeed (EChunkInstallSpeed::Type InstallSpeed) pure virtual
Specify the priority of chunk installation vs.
game IO.
Parameters
InstallSpeed Pause, low or high priority.
Returns
false if the operation is not allowed, otherwise true.
Implemented in FGenericPlatformChunkInstall.
SupportsBundleSource()
virtual bool IPlatformChunkInstall::SupportsBundleSource () const pure virtual
Returns whether this platform chunk installer implements all the API functions to support the platform chunk install bundle source.
Implemented in FGenericPlatformChunkInstall.
References SupportsBundleSource().
Referenced by SupportsBundleSource().
SupportsNamedChunkInstall()
virtual bool IPlatformChunkInstall::SupportsNamedChunkInstall () const pure virtual
Check whether current platform supports chunk installation by name.
Returns
whether Intelligent Install is supported
Implemented in FGenericPlatformChunkInstall.
UE_DEPRECATED() [1/2]
IPlatformChunkInstall::UE_DEPRECATED (5. 4, "use AddNamedChunkCompleteDelegate instead") pure virtual
Request a delegate callback on named chunk install completion or failure.
Request may not be respected.
Parameters
Delegate The delegate to call when any named chunk is installed or fails to install
Returns
Handle to the bound delegate
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
IPlatformChunkInstall::UE_DEPRECATED (5. 4, "use RemoveNamedChunkCompleteDelegate instead") pure virtual
Remove a delegate callback on named chunk install completion.
Parameters
Delegate The delegate to remove.
References UE_DEPRECATED().
UninstallNamedChunk()
virtual bool IPlatformChunkInstall::UninstallNamedChunk (const FName NamedChunk) pure virtual
Uninstall the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
whether uninstallation task has been kicked
Implemented in FGenericPlatformChunkInstall.
UninstallNamedChunks()
virtual bool IPlatformChunkInstall::UninstallNamedChunks (const TArrayView< const FName > & NamedChunks) pure virtual
Uninstall the given set of named chunks.
Parameters
NamedChunk The names of the chunks to uninstall
Returns
whether uninstallation task has been kicked
Implemented in FGenericPlatformChunkInstall.
Referenced by FGenericPlatformChunkInstall::UninstallNamedChunk().
The documentation for this class was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformChunkInstall.h