Unreal Engine 5.6 C++ API: FPrimitiveComponentTarget Class Reference
FPrimitiveComponentTarget Class Reference abstract
#include "ComponentSourceInterfaces.h"
Data Structures
struct FCommitParams
Public Types
using FCommitter = TFunction< void(const FCommitParams&) >
Public Member Functions
FPrimitiveComponentTarget (UPrimitiveComponent *Component)
Constructor UPrimitivecomponent*.
virtual ~FPrimitiveComponentTarget ()
virtual INTERACTIVETOOLSFRAMEWORK_API void CommitMaterialSetUpdate (const FComponentMaterialSet &MaterialSet, bool bApplyToAsset)
Commit an update to the material set.
virtual void CommitMesh (const FCommitter &)=0
INTERACTIVETOOLSFRAMEWORK_API UMaterialInterface * GetMaterial (int32 MaterialIndex) const
Get pointer to a Material provided by this Source.
virtual INTERACTIVETOOLSFRAMEWORK_API void GetMaterialSet (FComponentMaterialSet &MaterialSetOut, bool bAssetMaterials=false) const
Get material set provided by this source.
virtual FMeshDescription * GetMesh ()=0
INTERACTIVETOOLSFRAMEWORK_API int32 GetNumMaterials () const
INTERACTIVETOOLSFRAMEWORK_API AActor * GetOwnerActor () const
INTERACTIVETOOLSFRAMEWORK_API UPrimitiveComponent * GetOwnerComponent () const
INTERACTIVETOOLSFRAMEWORK_API FTransform GetWorldTransform () const
virtual bool HasSameSourceData (const FPrimitiveComponentTarget &OtherTarget) const =0
Checks if the underlying asset that would be edited by CommitMesh() is the same for two ComponentTargets.
INTERACTIVETOOLSFRAMEWORK_API bool HitTest (const FRay &WorldRay, FHitResult &OutHit) const
Compute ray intersection with the MeshDescription this Source is providing.
virtual INTERACTIVETOOLSFRAMEWORK_API bool IsValid () const
INTERACTIVETOOLSFRAMEWORK_API void SetOwnerVisibility (bool bVisible) const
Set the visibility of the Component associated with this Source (ie to hide during Tool usage)
Data Fields
UPrimitiveComponent * Component {}
Detailed Description
Deprecated
Use tool targets instead, such as UPrimitiveComponentToolTarget
Wrapper around a UObject Component that can provide a MeshDescription, and (optionally) bake a modified MeshDescription back to this Component. An example of a Source might be a StaticMeshComponent. How a modified MeshDescription is committed back is context-dependent (in Editor vs PIE vs Runtime, etc).
(Conceivably this doesn't have to be backed by a Component, but most usage will assume there is an Actor)
Definition at line 29 of file ComponentSourceInterfaces.h.
Member Typedef Documentation
FCommitter
using FPrimitiveComponentTarget::FCommitter = TFunction< void(const FCommitParams&) >
Definition at line 105 of file ComponentSourceInterfaces.h.
Constructor & Destructor Documentation
~FPrimitiveComponentTarget()
virtual FPrimitiveComponentTarget::~FPrimitiveComponentTarget () inline virtual
Definition at line 32 of file ComponentSourceInterfaces.h.
FPrimitiveComponentTarget()
FPrimitiveComponentTarget::FPrimitiveComponentTarget (UPrimitiveComponent * Component) inline
Constructor UPrimitivecomponent*.
Parameters
Component the UPrimitiveComponent* to target
Definition at line 37 of file ComponentSourceInterfaces.h.
References Component.
Referenced by HasSameSourceData(), and FStaticMeshComponentTarget::HasSameSourceData().
Member Function Documentation
CommitMaterialSetUpdate()
virtual INTERACTIVETOOLSFRAMEWORK_API void FPrimitiveComponentTarget::CommitMaterialSetUpdate (const FComponentMaterialSet & MaterialSet, bool bApplyToAsset) virtual
Commit an update to the material set.
This may generate a transaction.
Parameters
MaterialSet new list of materials
bApplyToAsset if true, materials of Asset are updated (if Asset exists), rather than Component
Reimplemented in FStaticMeshComponentTarget.
CommitMesh()
virtual void FPrimitiveComponentTarget::CommitMesh (const FCommitter &) pure virtual
Implemented in FStaticMeshComponentTarget.
GetMaterial()
INTERACTIVETOOLSFRAMEWORK_API UMaterialInterface * FPrimitiveComponentTarget::GetMaterial (int32 MaterialIndex) const
Get pointer to a Material provided by this Source.
Parameters
MaterialIndex index of the material
Returns
MaterialInterface pointer, or null if MaterialIndex is invalid
GetMaterialSet()
virtual INTERACTIVETOOLSFRAMEWORK_API void FPrimitiveComponentTarget::GetMaterialSet (FComponentMaterialSet & MaterialSetOut, bool bAssetMaterials = false) const virtual
Get material set provided by this source.
Parameters
MaterialSetOut returned material set
bAssetMaterials if an underlying asset exists, return the Asset-level material assignment instead of the component materials
Reimplemented in FStaticMeshComponentTarget.
GetMesh()
virtual FMeshDescription * FPrimitiveComponentTarget::GetMesh () pure virtual
Implemented in FStaticMeshComponentTarget.
GetNumMaterials()
INTERACTIVETOOLSFRAMEWORK_API int32 FPrimitiveComponentTarget::GetNumMaterials () const
Returns
number of material indices in use by this Component
GetOwnerActor()
INTERACTIVETOOLSFRAMEWORK_API AActor * FPrimitiveComponentTarget::GetOwnerActor () const
Returns
the Actor that owns this Component
GetOwnerComponent()
INTERACTIVETOOLSFRAMEWORK_API UPrimitiveComponent * FPrimitiveComponentTarget::GetOwnerComponent () const
Returns
the Component this is a Source for
GetWorldTransform()
INTERACTIVETOOLSFRAMEWORK_API FTransform FPrimitiveComponentTarget::GetWorldTransform () const
Returns
the transform on this component
Todo
Do we need to return a list of transforms here?
HasSameSourceData()
virtual bool FPrimitiveComponentTarget::HasSameSourceData (const FPrimitiveComponentTarget & OtherTarget) const pure virtual
Checks if the underlying asset that would be edited by CommitMesh() is the same for two ComponentTargets.
Parameters
OtherTarget Another component target to compare against
Returns
true if both component targets are known to share the same source asset
Implemented in FStaticMeshComponentTarget.
References FPrimitiveComponentTarget().
HitTest()
INTERACTIVETOOLSFRAMEWORK_API bool FPrimitiveComponentTarget::HitTest (const FRay & WorldRay, FHitResult & OutHit) const
Compute ray intersection with the MeshDescription this Source is providing.
Parameters
WorldRay ray in world space
OutHit hit test data
Returns
true if ray intersected Component
IsValid()
virtual INTERACTIVETOOLSFRAMEWORK_API bool FPrimitiveComponentTarget::IsValid () const virtual
Returns
true if component target is still valid. May become invalid for various reasons (eg Component was deleted out from under us)
Reimplemented in FStaticMeshComponentTarget.
SetOwnerVisibility()
INTERACTIVETOOLSFRAMEWORK_API void FPrimitiveComponentTarget::SetOwnerVisibility (bool bVisible) const
Set the visibility of the Component associated with this Source (ie to hide during Tool usage)
Parameters
bVisible desired visibility
Field Documentation
Component
UPrimitiveComponent* FPrimitiveComponentTarget::Component {}
Definition at line 109 of file ComponentSourceInterfaces.h.
Referenced by FPrimitiveComponentTarget(), and FStaticMeshComponentTarget::FStaticMeshComponentTarget().
The documentation for this class was generated from the following file:
Runtime/InteractiveToolsFramework/Public/ComponentSourceInterfaces.h