Unreal Engine 5.6 C++ API: IAsyncReadFileHandle Class Reference
IAsyncReadFileHandle Class Reference abstract
#include "AsyncFileHandle.h"
Public Member Functions
IAsyncReadFileHandle ()
IAsyncReadFileHandle (const IAsyncReadFileHandle &)=delete
virtual ~IAsyncReadFileHandle ()
Destructor, also the only way to close the file handle.
IAsyncReadFileHandle & operator= (const IAsyncReadFileHandle &)=delete
virtual IAsyncReadRequest * ReadRequest (int64 Offset, int64 BytesToRead, EAsyncIOPriorityAndFlags PriorityAndFlags=AIOP_Normal, FAsyncFileCallBack *CompleteCallback=nullptr, uint8 *UserSuppliedMemory=nullptr)=0
Submit an async request and/or wait for an async request.
virtual void ShrinkHandleBuffers ()
Minimizes buffers held internally by this handle.
virtual IAsyncReadRequest * SizeRequest (FAsyncFileCallBack *CompleteCallback=nullptr)=0
Request the size of the file.
virtual bool UsesCache ()
Return true if this file is backed by a cache, if not, then precache requests are ignored.
Detailed Description
Definition at line 210 of file AsyncFileHandle.h.
Constructor & Destructor Documentation
IAsyncReadFileHandle() [1/2]
IAsyncReadFileHandle::IAsyncReadFileHandle () inline
Definition at line 213 of file AsyncFileHandle.h.
References INC_DWORD_STAT.
Referenced by FLoggingAsyncReadFileHandle::FLoggingAsyncReadFileHandle(), IAsyncReadFileHandle(), and operator=().
~IAsyncReadFileHandle()
virtual IAsyncReadFileHandle::~IAsyncReadFileHandle () inline virtual
Destructor, also the only way to close the file handle.
It is not legal to delete an async file with outstanding requests. You must always call WaitCompletion before deleting a request.
Definition at line 218 of file AsyncFileHandle.h.
References DEC_DWORD_STAT.
IAsyncReadFileHandle() [2/2]
IAsyncReadFileHandle::IAsyncReadFileHandle (const IAsyncReadFileHandle &) delete
References IAsyncReadFileHandle().
Member Function Documentation
operator=()
IAsyncReadFileHandle & IAsyncReadFileHandle::operator= (const IAsyncReadFileHandle &) delete
References IAsyncReadFileHandle().
ReadRequest()
virtual IAsyncReadRequest * IAsyncReadFileHandle::ReadRequest (int64 Offset, int64 BytesToRead, EAsyncIOPriorityAndFlags PriorityAndFlags = AIOP_Normal, FAsyncFileCallBack * CompleteCallback = nullptr, uint8 * UserSuppliedMemory = nullptr) pure virtual
Submit an async request and/or wait for an async request.
Parameters
Offset Offset into the file to start reading.
BytesToRead number of bytes to read. If this request is AIOP_Preache, the size can be anything, even MAX_int64, otherwise the size and offset must be fully contained in the file.
PriorityAndFlags Priority and flags of the request. If this includes AIOP_FLAG_PRECACHE, then memory will never be returned. The request should always be canceled and waited for, even for a precache request.
CompleteCallback Called from an arbitrary thread when the request is complete. Can be nullptr, if non-null, must remain valid until it is called. It will always be called.
Returns
A request for the read. This is owned by the caller and must be deleted by the caller.
Implemented in FAsyncReadFileHandleNull, and FLoggingAsyncReadFileHandle.
References AIOP_Normal.
ShrinkHandleBuffers()
virtual void IAsyncReadFileHandle::ShrinkHandleBuffers () inline virtual
Minimizes buffers held internally by this handle.
Definition at line 247 of file AsyncFileHandle.h.
SizeRequest()
virtual IAsyncReadRequest * IAsyncReadFileHandle::SizeRequest (FAsyncFileCallBack * CompleteCallback = nullptr) pure virtual
Request the size of the file.
This is also essentially the existence check.
Parameters
CompleteCallback Called from an arbitrary thread when the request is complete. Can be nullptr, if non-null, must remain valid until it is called. It will always be called.
Returns
A request for the size. This is owned by the caller and must be deleted by the caller.
Implemented in FAsyncReadFileHandleNull, and FLoggingAsyncReadFileHandle.
UsesCache()
virtual bool IAsyncReadFileHandle::UsesCache () inline virtual
Return true if this file is backed by a cache, if not, then precache requests are ignored.
Reimplemented in FAsyncReadFileHandleNull.
Definition at line 241 of file AsyncFileHandle.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/AsyncFileHandle.h