Unreal Engine 5.6 C++ API: UE::Anim::FNonBlendableAttributeBlendOperator Class Reference
UE::Anim::FNonBlendableAttributeBlendOperator Class Reference
#include "AttributeBlendOperator.h"
Public Member Functions
FNonBlendableAttributeBlendOperator (const UScriptStruct *InScriptStruct)
virtual void Accumulate (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Begin IAttributeBlendOperator overrides.
virtual void Blend (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Invoked when two or multiple sets of attribute container inputs are to be blended together.
virtual void BlendPerBone (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Invoked when two or multiple sets of attribute container inputs are to be blended together, using individual bone weights.
virtual void ConvertToAdditive (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAdditiveAttributes) const final
Invoked when an attribute container is supposed to be made additive with regards to container B.
virtual void Interpolate (const void *FromData, const void *ToData, float Alpha, void *InOutData) const final
Invoked to interpolate between two individual attribute type values, according to the provided alpha.
virtual void Override (const FAttributeBlendData &BlendData, FStackAttributeContainer *OutAttributes) const final
Invoked when an attribute container A is expected to override attributes in container B.
Public Member Functions inherited from UE::Anim::IAttributeBlendOperator
virtual ~IAttributeBlendOperator ()
Protected Attributes
TWeakObjectPtr< const UScriptStruct > ScriptStructPtr
Detailed Description
Definition at line 427 of file AttributeBlendOperator.h.
Constructor & Destructor Documentation
FNonBlendableAttributeBlendOperator()
UE::Anim::FNonBlendableAttributeBlendOperator::FNonBlendableAttributeBlendOperator (const UScriptStruct * InScriptStruct) inline
Definition at line 430 of file AttributeBlendOperator.h.
References ScriptStructPtr.
Member Function Documentation
Accumulate()
virtual void UE::Anim::FNonBlendableAttributeBlendOperator::Accumulate (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Begin IAttributeBlendOperator overrides.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 433 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::FAttributeBlendData::TSingleRawIterator::GetIdentifier(), UE::Anim::FAttributeBlendData::TSingleRawIterator::GetValuePtr(), UE::Anim::FAttributeBlendData::TSingleRawIterator::GetWeight(), INDEX_NONE, UE::Anim::FAttributeBlendData::TSingleRawIterator::Next(), and ScriptStructPtr.
Blend()
virtual void UE::Anim::FNonBlendableAttributeBlendOperator::Blend (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Invoked when two or multiple sets of attribute container inputs are to be blended together.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 475 of file AttributeBlendOperator.h.
References UE::Anim::Attributes::GetAttributeBlendType(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetHighestWeightedValue(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetIdentifier(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetValuePtr(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::Next(), and ScriptStructPtr.
BlendPerBone()
virtual void UE::Anim::FNonBlendableAttributeBlendOperator::BlendPerBone (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Invoked when two or multiple sets of attribute container inputs are to be blended together, using individual bone weights.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 499 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetBoneWeight(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetHighestBoneWeightedValue(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetIdentifier(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::GetValuePtr(), INDEX_NONE, FAnimWeight::IsRelevant(), UE::Anim::FAttributeBlendData::TAttributeSetRawIterator::Next(), and ScriptStructPtr.
ConvertToAdditive()
virtual void UE::Anim::FNonBlendableAttributeBlendOperator::ConvertToAdditive (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAdditiveAttributes) const inline final virtual
Invoked when an attribute container is supposed to be made additive with regards to container B.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 531 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::FAttributeBlendData::TSingleRawIterator::GetIdentifier(), UE::Anim::FAttributeBlendData::TSingleRawIterator::GetValuePtr(), UE::Anim::FAttributeBlendData::TSingleRawIterator::GetWeight(), INDEX_NONE, UE::Anim::FAttributeBlendData::TSingleRawIterator::Next(), and ScriptStructPtr.
Interpolate()
virtual void UE::Anim::FNonBlendableAttributeBlendOperator::Interpolate (const void * FromData, const void * ToData, float Alpha, void * InOutData) const inline final virtual
Invoked to interpolate between two individual attribute type values, according to the provided alpha.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 453 of file AttributeBlendOperator.h.
References Alpha, and ScriptStructPtr.
Override()
virtual void UE::Anim::FNonBlendableAttributeBlendOperator::Override (const FAttributeBlendData & BlendData, FStackAttributeContainer * OutAttributes) const inline final virtual
Invoked when an attribute container A is expected to override attributes in container B.
Implements UE::Anim::IAttributeBlendOperator.
Definition at line 460 of file AttributeBlendOperator.h.
References Attribute, UE::Anim::FAttributeBlendData::TSingleRawIterator::GetIdentifier(), UE::Anim::FAttributeBlendData::TSingleRawIterator::GetValuePtr(), UE::Anim::FAttributeBlendData::TSingleRawIterator::Next(), and ScriptStructPtr.
Field Documentation
ScriptStructPtr
TWeakObjectPtr<const UScriptStruct> UE::Anim::FNonBlendableAttributeBlendOperator::ScriptStructPtr protected
Definition at line 553 of file AttributeBlendOperator.h.
Referenced by FNonBlendableAttributeBlendOperator(), Accumulate(), Blend(), BlendPerBone(), ConvertToAdditive(), Interpolate(), and Override().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Animation/AttributeBlendOperator.h