Unreal Engine 5.6 C++ API: FMeshMaterialShaderMap Class Reference
FMeshMaterialShaderMap Class Reference
The shaders which the render the material on a mesh generated by a particular vertex factory type.
#include "MaterialShared.h"
Public Member Functions
FMeshMaterialShaderMap (EShaderPlatform InPlatform, const FHashedName &InVertexFactoryTypeName)
const FHashedName & GetVertexFactoryTypeName () const
void LoadMissingShadersFromMemory (const FSHAHash &MaterialShaderMapHash, const FMaterial *Material, EShaderPlatform Platform)
Public Member Functions inherited from FShaderMapContent
RENDERCORE_API FShaderMapContent (EShaderPlatform InPlatform)
Default constructor.
RENDERCORE_API ~FShaderMapContent ()
Destructor ensures pipelines cleared up.
RENDERCORE_API void AddShader (const FHashedName &TypeName, int32 PermutationId, FShader *Shader)
RENDERCORE_API void AddShaderPipeline (FShaderPipeline *Pipeline)
RENDERCORE_API void DumpShaderList (const FShaderMapBase &InShaderMap, FShaderListReport &Out) const
RENDERCORE_API void Empty ()
clears out all shaders and deletes shader pipelines held in the map
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API FShader * FindOrAddShader (const FHashedName &TypeName, int32 PermutationId, FShader *Shader)
RENDERCORE_API FShaderPipeline * FindOrAddShaderPipeline (FShaderPipeline *Pipeline)
RENDERCORE_API uint32 GetMaxNumInstructionsForShader (const FShaderMapBase &InShaderMap, FShaderType *ShaderType) const
RENDERCORE_API uint32 GetMaxTextureSamplersShaderMap (const FShaderMapBase &InShaderMap) const
uint32 GetNumShaderPipelines () const
RENDERCORE_API uint32 GetNumShaders () const
RENDERCORE_API void GetOutdatedTypes (const FShaderMapBase &InShaderMap, TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
RENDERCORE_API FShader * GetShader (const FHashedName &TypeName, int32 PermutationId=0) const
Finds the shader with the given type name.
FShader * GetShader (const FShaderType *ShaderType, int32 PermutationId=0) const
Finds the shader with the given type.
template<typename ShaderType>
ShaderType * GetShader (const typename ShaderType::FPermutationDomain &PermutationVector) const
Finds the shader with the given type.
template<typename ShaderType>
ShaderType * GetShader (int32 PermutationId=0) const
Finds the shader with the given type.
RENDERCORE_API void GetShaderList (const FShaderMapBase &InShaderMap, const FSHAHash &InMaterialShaderMapHash, TMap< FShaderId, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
RENDERCORE_API void GetShaderList (const FShaderMapBase &InShaderMap, TMap< FHashedName, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
FShaderPipeline * GetShaderPipeline (const FHashedName &PipelineTypeName) const
FShaderPipeline * GetShaderPipeline (const FShaderPipelineType *PipelineType) const
RENDERCORE_API void GetShaderPipelineList (const FShaderMapBase &InShaderMap, TArray< FShaderPipelineRef > &OutShaderPipelines, FShaderPipeline::EFilter Filter) const
Builds a list of the shader pipelines in a shader map.
TArrayView< const TMemoryImagePtr< FShaderPipeline > > GetShaderPipelines () const
RENDERCORE_API EShaderPlatform GetShaderPlatform () const
TArrayView< const TMemoryImagePtr< FShader > > GetShaders () const
const FShader::FShaderStatisticMap GetShaderStatisticsMapForShader (const FShaderMapBase &InShaderMap, FShaderType *ShaderType) const
bool HasShader (const FHashedName &TypeName, int32 PermutationId) const
Finds the shader with the given type.
bool HasShader (const FShaderType *Type, int32 PermutationId) const
bool HasShaderPipeline (const FHashedName &PipelineTypeName) const
bool HasShaderPipeline (const FShaderPipelineType *PipelineType) const
bool IsEmpty () const
RENDERCORE_API void RemoveShaderPipelineType (const FShaderPipelineType *ShaderPipelineType)
RENDERCORE_API void RemoveShaderTypePermutaion (const FHashedName &TypeName, int32 PermutationId)
Removes the shader of the given type from the shader map.
void RemoveShaderTypePermutaion (const FShaderType *Type, int32 PermutationId)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapBase &InShaderMap, EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API void UpdateHash (FSHA1 &Hasher) const
RENDERCORE_API void Validate (const FShaderMapBase &InShaderMap) const
Private Member Functions
DECLARE_TYPE_LAYOUT (FMeshMaterialShaderMap, NonVirtual)
LAYOUT_FIELD (FHashedName, VertexFactoryTypeName)
The vertex factory type these shaders are for.
Additional Inherited Members
Protected Types inherited from FShaderMapContent
using FMemoryImageHashTable = THashTable<FMemoryImageAllocator>
Protected Member Functions inherited from FShaderMapContent
RENDERCORE_API void EmptyShaderPipelines ()
LAYOUT_FIELD (FMemoryImageHashTable, ShaderHash)
LAYOUT_FIELD (FMemoryImageName, ShaderPlatformName)
The ShaderPlatform Name this shader map was compiled with.
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, ShaderTypes)
LAYOUT_FIELD (TMemoryImageArray< int32 >, ShaderPermutations)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShader > >, Shaders)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShaderPipeline > >, ShaderPipelines)
Detailed Description
The shaders which the render the material on a mesh generated by a particular vertex factory type.
Definition at line 1339 of file MaterialShared.h.
Constructor & Destructor Documentation
FMeshMaterialShaderMap()
FMeshMaterialShaderMap::FMeshMaterialShaderMap (EShaderPlatform InPlatform, const FHashedName & InVertexFactoryTypeName) inline
Definition at line 1343 of file MaterialShared.h.
References FShaderMapContent::FShaderMapContent().
Referenced by DECLARE_TYPE_LAYOUT().
Member Function Documentation
DECLARE_TYPE_LAYOUT()
FMeshMaterialShaderMap::DECLARE_TYPE_LAYOUT (FMeshMaterialShaderMap , NonVirtual) private
References FMeshMaterialShaderMap().
GetVertexFactoryTypeName()
const FHashedName & FMeshMaterialShaderMap::GetVertexFactoryTypeName () const inline
Definition at line 1356 of file MaterialShared.h.
Referenced by FMaterialShaderMapContent::FProjectMeshShaderMapToKey::operator()().
LAYOUT_FIELD()
FMeshMaterialShaderMap::LAYOUT_FIELD (FHashedName , VertexFactoryTypeName) private
The vertex factory type these shaders are for.
LoadMissingShadersFromMemory()
void FMeshMaterialShaderMap::LoadMissingShadersFromMemory (const FSHAHash & MaterialShaderMapHash, const FMaterial * Material, EShaderPlatform Platform)
References Material, and Platform.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialShared.h