Unreal Engine 5.6 C++ API: FShaderMapResource Class Reference
FShaderMapResource Class Reference abstract
#include "Shader.h"
Public Member Functions
RENDERCORE_API void AddRef ()
RENDERCORE_API void BeginCreateAllShaders ()
bool ContainsAtLeastOneRHIShaderCreated () const
virtual int32 GetGroupIndexForShader (int32 ShaderIndex) const
virtual int32 GetLibraryId () const
virtual int32 GetLibraryShaderIndex (int32 ShaderIndex) const
int32 GetNumRefs () const
int32 GetNumShaders () const
EShaderPlatform GetPlatform () const
FRHIShader * GetShader (int32 ShaderIndex, bool bRequired=true)
virtual FSHAHash GetShaderHash (int32 ShaderIndex)=0
Return shader hash for a particular shader without creating it.
virtual uint32 GetShaderSizeBytes (int32 ShaderIndex) const
virtual uint32 GetSizeBytes () const =0
bool HasShader (int32 ShaderIndex) const
bool IsValidShaderIndex (int32 ShaderIndex) const
virtual void PreloadShader (int32 ShaderIndex, FGraphEventArray &OutCompletionEvents)
virtual void PreloadShaderMap (FGraphEventArray &OutCompletionEvents)
RENDERCORE_API void Release ()
virtual RENDERCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Public Member Functions inherited from FDeferredCleanupInterface
virtual ~FDeferredCleanupInterface ()
Static Public Member Functions
static RENDERCORE_API bool ArePlatformsCompatible (EShaderPlatform CurrentPlatform, EShaderPlatform TargetPlatform)
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions
RENDERCORE_API FShaderMapResource (EShaderPlatform InPlatform, int32 NumShaders)
virtual RENDERCORE_API ~FShaderMapResource ()
virtual FRHIShader * CreateRHIShaderOrCrash (int32 ShaderIndex, bool bRequired)=0
Creates RHI shader, with a reference (so the caller can release).
SIZE_T GetAllocatedSize () const
virtual void ReleasePreloadedShaderCode (int32 ShaderIndex)
Signal the shader library that it can release compressed shader code for a shader that it keeps preloaded in memory.
RENDERCORE_API void ReleaseShaders ()
virtual bool TryRelease ()
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Private Member Functions
RENDERCORE_API FRHIShader * CreateShaderOrCrash (int32 ShaderIndex, bool bRequired)
Creates an entry in RHIShaders array and registers it among the raytracing libs if needed.
Private Attributes
uint32 bAtLeastOneRHIShaderCreated: 1
Whether we have at least one RHI shader created.
std::atomic< int32 > NumRefs
The number of references to this shader map.
uint32 NumRHIShaders: 31
Since the shaders are no longer a TArray, this is their count (the size of the RHIShaders array).
EShaderPlatform Platform
TUniquePtr< std::atomic< FRHIShader * >[]> RHIShaders
An array of shader pointers (refcount is managed manually).
FCriticalSection RHIShadersCreationGuard
This lock is to prevent two threads creating the same RHIShaders element.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 335 of file Shader.h.
Constructor & Destructor Documentation
FShaderMapResource()
RENDERCORE_API FShaderMapResource::FShaderMapResource (EShaderPlatform InPlatform, int32 NumShaders) explicit protected
Referenced by FShaderMapResource_InlineCode::FShaderMapResource_InlineCode().
~FShaderMapResource()
virtual RENDERCORE_API FShaderMapResource::~FShaderMapResource () protected virtual
Member Function Documentation
AddRef()
RENDERCORE_API void FShaderMapResource::AddRef ()
ArePlatformsCompatible()
RENDERCORE_API bool FShaderMapResource::ArePlatformsCompatible (EShaderPlatform CurrentPlatform, EShaderPlatform TargetPlatform) static
BeginCreateAllShaders()
RENDERCORE_API void FShaderMapResource::BeginCreateAllShaders ()
ContainsAtLeastOneRHIShaderCreated()
bool FShaderMapResource::ContainsAtLeastOneRHIShaderCreated () const inline
Definition at line 394 of file Shader.h.
References bAtLeastOneRHIShaderCreated.
CreateRHIShaderOrCrash()
virtual FRHIShader * FShaderMapResource::CreateRHIShaderOrCrash (int32 ShaderIndex, bool bRequired) protected pure virtual
Creates RHI shader, with a reference (so the caller can release).
Never returns nullptr (inability to create is Fatal)
Implemented in FShaderMapResource_InlineCode.
CreateShaderOrCrash()
RENDERCORE_API FRHIShader * FShaderMapResource::CreateShaderOrCrash (int32 ShaderIndex, bool bRequired) private
Creates an entry in RHIShaders array and registers it among the raytracing libs if needed.
Created shader is returned.
Referenced by GetShader().
GetAllocatedSize()
SIZE_T FShaderMapResource::GetAllocatedSize () const inline protected
Definition at line 468 of file Shader.h.
References NumRHIShaders, and TSequenceHistory< HistorySize >::Size.
GetGroupIndexForShader()
virtual int32 FShaderMapResource::GetGroupIndexForShader (int32 ShaderIndex) const inline virtual
Definition at line 376 of file Shader.h.
References INDEX_NONE.
GetLibraryId()
virtual int32 FShaderMapResource::GetLibraryId () const inline virtual
Definition at line 382 of file Shader.h.
References INDEX_NONE.
GetLibraryShaderIndex()
virtual int32 FShaderMapResource::GetLibraryShaderIndex (int32 ShaderIndex) const inline virtual
Definition at line 388 of file Shader.h.
References INDEX_NONE.
GetNumRefs()
int32 FShaderMapResource::GetNumRefs () const inline
Definition at line 344 of file Shader.h.
References NumRefs.
GetNumShaders()
int32 FShaderMapResource::GetNumShaders () const inline
Definition at line 349 of file Shader.h.
References NumRHIShaders.
GetPlatform()
EShaderPlatform FShaderMapResource::GetPlatform () const inline
Definition at line 340 of file Shader.h.
References Platform.
GetShader()
FRHIShader * FShaderMapResource::GetShader (int32 ShaderIndex, bool bRequired = true) inline
Definition at line 399 of file Shader.h.
References CreateShaderOrCrash(), RHIShaders, and UNLIKELY.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetGraphicsShader(), and TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetRHIShaderBase().
GetShaderHash()
virtual FSHAHash FShaderMapResource::GetShaderHash (int32 ShaderIndex) pure virtual
Return shader hash for a particular shader without creating it.
Implemented in FShaderMapResource_InlineCode.
GetShaderSizeBytes()
virtual uint32 FShaderMapResource::GetShaderSizeBytes (int32 ShaderIndex) const virtual
Reimplemented in FShaderMapResource_InlineCode.
GetSizeBytes()
virtual uint32 FShaderMapResource::GetSizeBytes () const pure virtual
Implemented in FShaderMapResource_InlineCode.
HasShader()
bool FShaderMapResource::HasShader (int32 ShaderIndex) const inline
Definition at line 359 of file Shader.h.
References RHIShaders.
IsValidShaderIndex()
bool FShaderMapResource::IsValidShaderIndex (int32 ShaderIndex) const inline
Definition at line 354 of file Shader.h.
References NumRHIShaders.
PreloadShader()
virtual void FShaderMapResource::PreloadShader (int32 ShaderIndex, FGraphEventArray & OutCompletionEvents) inline virtual
Definition at line 366 of file Shader.h.
PreloadShaderMap()
virtual void FShaderMapResource::PreloadShaderMap (FGraphEventArray & OutCompletionEvents) inline virtual
Definition at line 371 of file Shader.h.
Release()
RENDERCORE_API void FShaderMapResource::Release ()
ReleasePreloadedShaderCode()
virtual void FShaderMapResource::ReleasePreloadedShaderCode (int32 ShaderIndex) inline protected virtual
Signal the shader library that it can release compressed shader code for a shader that it keeps preloaded in memory.
Definition at line 481 of file Shader.h.
ReleaseRHI()
virtual RENDERCORE_API void FShaderMapResource::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseShaders()
RENDERCORE_API void FShaderMapResource::ReleaseShaders () protected
TryRelease()
virtual bool FShaderMapResource::TryRelease () inline protected virtual
Definition at line 483 of file Shader.h.
Field Documentation
bAtLeastOneRHIShaderCreated
uint32 FShaderMapResource::bAtLeastOneRHIShaderCreated private
Whether we have at least one RHI shader created.
Definition at line 506 of file Shader.h.
Referenced by ContainsAtLeastOneRHIShaderCreated().
NumRefs
std::atomic<int32> FShaderMapResource::NumRefs private
The number of references to this shader map.
Definition at line 511 of file Shader.h.
Referenced by GetNumRefs().
NumRHIShaders
uint32 FShaderMapResource::NumRHIShaders private
Since the shaders are no longer a TArray, this is their count (the size of the RHIShaders array).
This does not count actually created RHI shaders, just the size of the above array of pointers to them.
Definition at line 503 of file Shader.h.
Referenced by GetAllocatedSize(), GetNumShaders(), and IsValidShaderIndex().
Platform
EShaderPlatform FShaderMapResource::Platform private
Definition at line 508 of file Shader.h.
Referenced by GetPlatform().
RHIShaders
TUniquePtr<std::atomic<FRHIShader*>[]> FShaderMapResource::RHIShaders private
An array of shader pointers (refcount is managed manually).
Definition at line 500 of file Shader.h.
Referenced by GetShader(), and HasShader().
RHIShadersCreationGuard
FCriticalSection FShaderMapResource::RHIShadersCreationGuard private
This lock is to prevent two threads creating the same RHIShaders element.
It is only taken if the element is to be created.
Definition at line 493 of file Shader.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h