Unreal Engine 5.6 C++ API: UE::Geometry::FMeshBevel Class Reference
UE::Geometry::FMeshBevel Class Reference
FMeshBevel applies a "Bevel" operation to edges of a FDynamicMesh3.
#include "MeshBevel.h"
Data Structures
struct FBevelEdge
struct FBevelLoop
struct FBevelVertex
struct FBevelVertex_InteriorVertex
struct FOneRingWedge
Public Types
enum class EBevelVertexType { JunctionVertex , TerminatorVertex , BoundaryVertex , Unknown }
enum class EMaterialIDMode { ConstantMaterialID , InferMaterialID , InferMaterialID_ConstantIfAmbiguous }
Options for MaterialID assignment on the new triangles generated for the bevel.
Public Member Functions
DYNAMICMESH_API bool Apply (FDynamicMesh3 &Mesh, FDynamicMeshChangeTracker *ChangeTracker)
Apply the bevel operation to the mesh, and optionally track changes.
DYNAMICMESH_API void InitializeFromGroupTopology (const FDynamicMesh3 &Mesh, const FGroupTopology &Topology)
Initialize the bevel with all edges of the given GroupTopology.
DYNAMICMESH_API void InitializeFromGroupTopologyEdges (const FDynamicMesh3 &Mesh, const FGroupTopology &Topology, const TArray< int32 > &GroupEdges)
Initialize the bevel with the specified edges of a GroupTopology.
DYNAMICMESH_API bool InitializeFromGroupTopologyFaces (const FDynamicMesh3 &Mesh, const FGroupTopology &Topology, const TArray< int32 > &GroupFaces)
Initialize the bevel with the specified faces of a GroupTopology.
void InitializeFromTriangleEdges (const FDynamicMesh3 &Mesh, TConstArrayView< int32 > TriangleEdges)
Initialize the bevel with the specified mesh triangle edges.
DYNAMICMESH_API void InitializeFromTriangleEdges (const FDynamicMesh3 &Mesh, TConstArrayView< int32 > TriangleEdges, TFunctionRef< bool(int32)> IsCornerVertex)
Initialize the bevel with the specified mesh triangle edges.
DYNAMICMESH_API bool InitializeFromTriangleSet (const FDynamicMesh3 &Mesh, const TArray< int32 > &Triangles)
Initialize the bevel with border loops of the selected triangles.
Data Fields
double InsetDistance = 5.0
Distance that bevel edges/vertices are inset from their initial position.
EMaterialIDMode MaterialIDMode = EMaterialIDMode::ConstantMaterialID
Which MaterialID assignment mode to use.
TArray< int32 > NewTriangles
list of all new triangles created by the operation
int32 NumSubdivisions = 0
Number of subdivisions inserted in each bevel strip.
FProgressCancel * Progress = nullptr
Set this member to support progress/cancel in the computations below.
FGeometryResult ResultInfo = FGeometryResult(EGeometryResultType::InProgress)
status of the operation, warnings/errors may be returned here
double RoundWeight = 1.0
"Roundness" of the bevel profile.
int32 SetConstantMaterialID = 0
Constant MaterialID used for various MaterialIDMode settings.
Protected Member Functions
DYNAMICMESH_API void AddBevelEdgeLoop (const FDynamicMesh3 &Mesh, const FEdgeLoop &Loop)
DYNAMICMESH_API void AddBevelGroupEdge (const FDynamicMesh3 &Mesh, const FGroupTopology &Topology, int32 GroupEdgeID)
DYNAMICMESH_API void AppendEdgeQuads (FDynamicMesh3 &Mesh, FBevelEdge &Edge)
DYNAMICMESH_API void AppendEdgeQuads_Multi (FDynamicMesh3 &Mesh, FBevelEdge &Edge)
DYNAMICMESH_API void AppendJunctionVertexPolygon (FDynamicMesh3 &Mesh, FBevelVertex &Vertex)
DYNAMICMESH_API void AppendJunctionVertexPolygon_Multi (FDynamicMesh3 &Mesh, FBevelVertex &Vertex)
DYNAMICMESH_API void AppendLoopQuads (FDynamicMesh3 &Mesh, FBevelLoop &Loop)
DYNAMICMESH_API void AppendLoopQuads_Multi (FDynamicMesh3 &Mesh, FBevelLoop &Loop)
DYNAMICMESH_API void AppendTerminatorVertexPairQuad (FDynamicMesh3 &Mesh, FBevelVertex &Vertex0, FBevelVertex &Vertex1)
DYNAMICMESH_API void AppendTerminatorVertexPairQuad_Multi (FDynamicMesh3 &Mesh, FBevelVertex &Vertex0, FBevelVertex &Vertex1)
DYNAMICMESH_API void AppendTerminatorVertexTriangle (FDynamicMesh3 &Mesh, FBevelVertex &Vertex)
DYNAMICMESH_API void AppendTerminatorVertexTriangles_Multi (FDynamicMesh3 &Mesh, FBevelVertex &Vertex)
DYNAMICMESH_API void ApplyProfileShape_Round (FDynamicMesh3 &Mesh)
DYNAMICMESH_API void BuildJunctionVertex (FBevelVertex &Vertex, const FDynamicMesh3 &Mesh)
DYNAMICMESH_API void BuildTerminatorVertex (FBevelVertex &Vertex, const FDynamicMesh3 &Mesh)
DYNAMICMESH_API void BuildVertexSets (const FDynamicMesh3 &Mesh)
DYNAMICMESH_API void ComputeMaterialIDs (FDynamicMesh3 &Mesh)
DYNAMICMESH_API void ComputeNormals (FDynamicMesh3 &Mesh)
DYNAMICMESH_API void ComputeUVs (FDynamicMesh3 &Mesh)
DYNAMICMESH_API void CreateBevelMeshing (FDynamicMesh3 &Mesh)
DYNAMICMESH_API void CreateBevelMeshing_Multi (FDynamicMesh3 &Mesh)
Meshing functions for multi-segment bevel with optional round profile.
DYNAMICMESH_API void DisplaceVertices (FDynamicMesh3 &Mesh, double Distance)
DYNAMICMESH_API void FixUpUnlinkedBevelEdges (FDynamicMesh3 &Mesh)
DYNAMICMESH_API FBevelVertex * GetBevelVertexFromVertexID (int32 VertexID, int32 *IndexOut=nullptr)
DYNAMICMESH_API FInterpCurveVector MakeArcSplineCurve (const FVector3d &PosA, FVector3d &NormalA, const FVector3d &PosB, FVector3d &NormalB) const
DYNAMICMESH_API void UnlinkBevelEdgeInterior (FDynamicMesh3 &Mesh, FBevelEdge &BevelEdge, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void UnlinkBevelLoop (FDynamicMesh3 &Mesh, FBevelLoop &BevelLoop, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void UnlinkEdges (FDynamicMesh3 &Mesh, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void UnlinkJunctionVertex (FDynamicMesh3 &Mesh, FBevelVertex &BevelVertex, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void UnlinkLoops (FDynamicMesh3 &Mesh, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void UnlinkTerminatorVertex (FDynamicMesh3 &Mesh, FBevelVertex &BevelVertex, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void UnlinkVertices (FDynamicMesh3 &Mesh, FDynamicMeshChangeTracker *ChangeTracker)
Protected Attributes
TArray< FBevelEdge > Edges
TArray< FBevelLoop > Loops
TMap< int32, int32 > MeshEdgePairs
TMap< int32, int32 > VertexIDToIndexMap
TArray< FBevelVertex > Vertices
Private Member Functions
DYNAMICMESH_API void FinalizeTerminatorVertex (const FDynamicMesh3 &Mesh, FBevelVertex &Vertex)
DYNAMICMESH_API void FixBowties (FDynamicMesh3 &Mesh, FDynamicMeshChangeTracker *ChangeTracker)
DYNAMICMESH_API void InitVertexSet (const FDynamicMesh3 &Mesh, FBevelVertex &Vertex)
Detailed Description
FMeshBevel applies a "Bevel" operation to edges of a FDynamicMesh3.
Bevel is not strictly well-defined, there are a wide range of possible cases to handle and currently only some are supported. See this website for a discussion of many interesting cases (most are not currently supported): https://wiki.blender.org/wiki/User:Howardt/Bevel
The bevel operation is applied in-place to the input mesh. The bevel is mesh-topological, ie implemented by un-stitching mesh edges and inserting new triangles, rather than via booleans/etc.
Currently supports:
Bevel an isolated closed loop of edges, that edge-loop becomes a quad-strip (simplest case)
Bevel a set of open edge spans that may meet a T-junctions
if incoming-span-valence at a vertex is >= 3, vertex is replaced by a polygon
if incoming-span-valence at a vertex is 1, bevel is "terminated" by expanding the vertex into an edge (this is the messiest case)
vertex-on-boundary is a special case that is simpler
edge spans are replaced by quad-strips
Currently does not support:
Beveling an isolated vertex
partial bevels of a GroupTopology Edge
multiple-segment bevel (eg to do rounds/etc)
???
Generally this FMeshBevel is intended to be applied to group-boundary "edges" in a FGroupTopology. However the FGroupTopology is currently only used in the initial setup, so other methods could be used to construct the bevel topology.
Currently "updating" the bevel shape, once the topology is known, is not supported, but could be implemented relatively easily, as all the relevant information is already tracked and stored.
Definition at line 49 of file MeshBevel.h.
Member Enumeration Documentation
EBevelVertexType
enum class UE::Geometry::FMeshBevel::EBevelVertexType strong
Enumerator
JunctionVertex
TerminatorVertex
BoundaryVertex
Unknown
Definition at line 235 of file MeshBevel.h.
EMaterialIDMode
enum class UE::Geometry::FMeshBevel::EMaterialIDMode strong
Options for MaterialID assignment on the new triangles generated for the bevel.
Enumerator
ConstantMaterialID
InferMaterialID
InferMaterialID_ConstantIfAmbiguous
Definition at line 70 of file MeshBevel.h.
Member Function Documentation
AddBevelEdgeLoop()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AddBevelEdgeLoop (const FDynamicMesh3 & Mesh, const FEdgeLoop & Loop) protected
References AddBevelEdgeLoop(), UE::Geometry::Mesh, and UE_API.
Referenced by AddBevelEdgeLoop().
AddBevelGroupEdge()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AddBevelGroupEdge (const FDynamicMesh3 & Mesh, const FGroupTopology & Topology, int32 GroupEdgeID) protected
References AddBevelGroupEdge(), UE::Geometry::Mesh, and UE_API.
Referenced by AddBevelGroupEdge().
AppendEdgeQuads()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendEdgeQuads (FDynamicMesh3 & Mesh, FBevelEdge & Edge) protected
References AppendEdgeQuads(), UE::Geometry::Edge, UE::Geometry::Mesh, and UE_API.
Referenced by AppendEdgeQuads().
AppendEdgeQuads_Multi()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendEdgeQuads_Multi (FDynamicMesh3 & Mesh, FBevelEdge & Edge) protected
References AppendEdgeQuads_Multi(), UE::Geometry::Edge, UE::Geometry::Mesh, and UE_API.
Referenced by AppendEdgeQuads_Multi().
AppendJunctionVertexPolygon()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendJunctionVertexPolygon (FDynamicMesh3 & Mesh, FBevelVertex & Vertex) protected
References AppendJunctionVertexPolygon(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by AppendJunctionVertexPolygon().
AppendJunctionVertexPolygon_Multi()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendJunctionVertexPolygon_Multi (FDynamicMesh3 & Mesh, FBevelVertex & Vertex) protected
References AppendJunctionVertexPolygon_Multi(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by AppendJunctionVertexPolygon_Multi().
AppendLoopQuads()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendLoopQuads (FDynamicMesh3 & Mesh, FBevelLoop & Loop) protected
References AppendLoopQuads(), UE::Geometry::Mesh, and UE_API.
Referenced by AppendLoopQuads().
AppendLoopQuads_Multi()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendLoopQuads_Multi (FDynamicMesh3 & Mesh, FBevelLoop & Loop) protected
References AppendLoopQuads_Multi(), UE::Geometry::Mesh, and UE_API.
Referenced by AppendLoopQuads_Multi().
AppendTerminatorVertexPairQuad()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendTerminatorVertexPairQuad (FDynamicMesh3 & Mesh, FBevelVertex & Vertex0, FBevelVertex & Vertex1) protected
References AppendTerminatorVertexPairQuad(), UE::Geometry::Mesh, and UE_API.
Referenced by AppendTerminatorVertexPairQuad().
AppendTerminatorVertexPairQuad_Multi()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendTerminatorVertexPairQuad_Multi (FDynamicMesh3 & Mesh, FBevelVertex & Vertex0, FBevelVertex & Vertex1) protected
References AppendTerminatorVertexPairQuad_Multi(), UE::Geometry::Mesh, and UE_API.
Referenced by AppendTerminatorVertexPairQuad_Multi().
AppendTerminatorVertexTriangle()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendTerminatorVertexTriangle (FDynamicMesh3 & Mesh, FBevelVertex & Vertex) protected
References AppendTerminatorVertexTriangle(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by AppendTerminatorVertexTriangle().
AppendTerminatorVertexTriangles_Multi()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::AppendTerminatorVertexTriangles_Multi (FDynamicMesh3 & Mesh, FBevelVertex & Vertex) protected
References AppendTerminatorVertexTriangles_Multi(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by AppendTerminatorVertexTriangles_Multi().
Apply()
DYNAMICMESH_API bool UE::Geometry::FMeshBevel::Apply (FDynamicMesh3 & Mesh, FDynamicMeshChangeTracker * ChangeTracker)
Apply the bevel operation to the mesh, and optionally track changes.
References UE::Geometry::Mesh, and UE_API.
ApplyProfileShape_Round()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::ApplyProfileShape_Round (FDynamicMesh3 & Mesh) protected
References ApplyProfileShape_Round(), UE::Geometry::Mesh, and UE_API.
Referenced by ApplyProfileShape_Round().
BuildJunctionVertex()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::BuildJunctionVertex (FBevelVertex & Vertex, const FDynamicMesh3 & Mesh) protected
References BuildJunctionVertex(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by BuildJunctionVertex().
BuildTerminatorVertex()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::BuildTerminatorVertex (FBevelVertex & Vertex, const FDynamicMesh3 & Mesh) protected
References BuildTerminatorVertex(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by BuildTerminatorVertex().
BuildVertexSets()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::BuildVertexSets (const FDynamicMesh3 & Mesh) protected
References BuildVertexSets(), UE::Geometry::Mesh, and UE_API.
Referenced by BuildVertexSets().
ComputeMaterialIDs()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::ComputeMaterialIDs (FDynamicMesh3 & Mesh) protected
References ComputeMaterialIDs(), UE::Geometry::Mesh, and UE_API.
Referenced by ComputeMaterialIDs().
ComputeNormals()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::ComputeNormals (FDynamicMesh3 & Mesh) protected
References ComputeNormals(), UE::Geometry::Mesh, and UE_API.
Referenced by ComputeNormals().
ComputeUVs()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::ComputeUVs (FDynamicMesh3 & Mesh) protected
References ComputeUVs(), UE::Geometry::Mesh, and UE_API.
Referenced by ComputeUVs().
CreateBevelMeshing()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::CreateBevelMeshing (FDynamicMesh3 & Mesh) protected
References CreateBevelMeshing(), UE::Geometry::Mesh, and UE_API.
Referenced by CreateBevelMeshing().
CreateBevelMeshing_Multi()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::CreateBevelMeshing_Multi (FDynamicMesh3 & Mesh) protected
Meshing functions for multi-segment bevel with optional round profile.
References CreateBevelMeshing_Multi(), UE::Geometry::Mesh, and UE_API.
Referenced by CreateBevelMeshing_Multi().
DisplaceVertices()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::DisplaceVertices (FDynamicMesh3 & Mesh, double Distance) protected
References DisplaceVertices(), UE::Geometry::Distance(), UE::Geometry::Mesh, and UE_API.
Referenced by DisplaceVertices().
FinalizeTerminatorVertex()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::FinalizeTerminatorVertex (const FDynamicMesh3 & Mesh, FBevelVertex & Vertex) private
References FinalizeTerminatorVertex(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by FinalizeTerminatorVertex().
FixBowties()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::FixBowties (FDynamicMesh3 & Mesh, FDynamicMeshChangeTracker * ChangeTracker) private
References FixBowties(), UE::Geometry::Mesh, and UE_API.
Referenced by FixBowties().
FixUpUnlinkedBevelEdges()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::FixUpUnlinkedBevelEdges (FDynamicMesh3 & Mesh) protected
References FixUpUnlinkedBevelEdges(), UE::Geometry::Mesh, and UE_API.
Referenced by FixUpUnlinkedBevelEdges().
GetBevelVertexFromVertexID()
DYNAMICMESH_API FBevelVertex * UE::Geometry::FMeshBevel::GetBevelVertexFromVertexID (int32 VertexID, int32 * IndexOut = nullptr) protected
References GetBevelVertexFromVertexID(), and UE_API.
Referenced by GetBevelVertexFromVertexID().
InitializeFromGroupTopology()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::InitializeFromGroupTopology (const FDynamicMesh3 & Mesh, const FGroupTopology & Topology)
Initialize the bevel with all edges of the given GroupTopology.
References UE::Geometry::Mesh, and UE_API.
InitializeFromGroupTopologyEdges()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::InitializeFromGroupTopologyEdges (const FDynamicMesh3 & Mesh, const FGroupTopology & Topology, const TArray< int32 > & GroupEdges)
Initialize the bevel with the specified edges of a GroupTopology.
References UE::Geometry::Mesh, and UE_API.
InitializeFromGroupTopologyFaces()
DYNAMICMESH_API bool UE::Geometry::FMeshBevel::InitializeFromGroupTopologyFaces (const FDynamicMesh3 & Mesh, const FGroupTopology & Topology, const TArray< int32 > & GroupFaces)
Initialize the bevel with the specified faces of a GroupTopology.
Returns
false if any selection-bowtie vertices were found, in this case we cannot compute the bevel
References UE::Geometry::Mesh, and UE_API.
InitializeFromTriangleEdges() [1/2]
void UE::Geometry::FMeshBevel::InitializeFromTriangleEdges (const FDynamicMesh3 & Mesh, TConstArrayView< int32 > TriangleEdges) inline
Initialize the bevel with the specified mesh triangle edges.
Definition at line 115 of file MeshBevel.h.
References InitializeFromTriangleEdges(), and UE::Geometry::Mesh.
InitializeFromTriangleEdges() [2/2]
DYNAMICMESH_API void UE::Geometry::FMeshBevel::InitializeFromTriangleEdges (const FDynamicMesh3 & Mesh, TConstArrayView< int32 > TriangleEdges, TFunctionRef< bool(int32)> IsCornerVertex)
Initialize the bevel with the specified mesh triangle edges.
Parameters
IsCornerVertex Function to determine whether a vertex should be treated as a corner when beveling. Only affects vertices with exactly two adjacent TriangleEdges; otherwise corners will be automatically detected.
References UE::Geometry::Mesh, and UE_API.
Referenced by InitializeFromTriangleEdges().
InitializeFromTriangleSet()
DYNAMICMESH_API bool UE::Geometry::FMeshBevel::InitializeFromTriangleSet (const FDynamicMesh3 & Mesh, const TArray< int32 > & Triangles)
Initialize the bevel with border loops of the selected triangles.
Returns
false if any selection-bowtie vertices were found, in this case we cannot compute the bevel
References UE::Geometry::Mesh, and UE_API.
InitVertexSet()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::InitVertexSet (const FDynamicMesh3 & Mesh, FBevelVertex & Vertex) private
References InitVertexSet(), UE::Geometry::Mesh, UE_API, and UE::Geometry::Vertex.
Referenced by InitVertexSet().
MakeArcSplineCurve()
DYNAMICMESH_API FInterpCurveVector UE::Geometry::FMeshBevel::MakeArcSplineCurve (const FVector3d & PosA, FVector3d & NormalA, const FVector3d & PosB, FVector3d & NormalB) const protected
References MakeArcSplineCurve(), and UE_API.
Referenced by MakeArcSplineCurve().
UnlinkBevelEdgeInterior()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkBevelEdgeInterior (FDynamicMesh3 & Mesh, FBevelEdge & BevelEdge, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkBevelEdgeInterior().
Referenced by UnlinkBevelEdgeInterior().
UnlinkBevelLoop()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkBevelLoop (FDynamicMesh3 & Mesh, FBevelLoop & BevelLoop, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkBevelLoop().
Referenced by UnlinkBevelLoop().
UnlinkEdges()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkEdges (FDynamicMesh3 & Mesh, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkEdges().
Referenced by UnlinkEdges().
UnlinkJunctionVertex()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkJunctionVertex (FDynamicMesh3 & Mesh, FBevelVertex & BevelVertex, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkJunctionVertex().
Referenced by UnlinkJunctionVertex().
UnlinkLoops()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkLoops (FDynamicMesh3 & Mesh, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkLoops().
Referenced by UnlinkLoops().
UnlinkTerminatorVertex()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkTerminatorVertex (FDynamicMesh3 & Mesh, FBevelVertex & BevelVertex, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkTerminatorVertex().
Referenced by UnlinkTerminatorVertex().
UnlinkVertices()
DYNAMICMESH_API void UE::Geometry::FMeshBevel::UnlinkVertices (FDynamicMesh3 & Mesh, FDynamicMeshChangeTracker * ChangeTracker) protected
References UE::Geometry::Mesh, UE_API, and UnlinkVertices().
Referenced by UnlinkVertices().
Field Documentation
Edges
TArray<FBevelEdge> UE::Geometry::FMeshBevel::Edges protected
Definition at line 295 of file MeshBevel.h.
InsetDistance
double UE::Geometry::FMeshBevel::InsetDistance = 5.0
Distance that bevel edges/vertices are inset from their initial position.
Not guaranteed to hold for all vertices, though.
Definition at line 58 of file MeshBevel.h.
Loops
TArray<FBevelLoop> UE::Geometry::FMeshBevel::Loops protected
Definition at line 296 of file MeshBevel.h.
MaterialIDMode
EMaterialIDMode UE::Geometry::FMeshBevel::MaterialIDMode = EMaterialIDMode::ConstantMaterialID
Which MaterialID assignment mode to use.
Definition at line 77 of file MeshBevel.h.
MeshEdgePairs
TMap<int32, int32> UE::Geometry::FMeshBevel::MeshEdgePairs protected
Definition at line 298 of file MeshBevel.h.
NewTriangles
TArray<int32> UE::Geometry::FMeshBevel::NewTriangles
list of all new triangles created by the operation
Definition at line 90 of file MeshBevel.h.
NumSubdivisions
int32 UE::Geometry::FMeshBevel::NumSubdivisions = 0
Number of subdivisions inserted in each bevel strip.
Definition at line 61 of file MeshBevel.h.
Progress
FProgressCancel* UE::Geometry::FMeshBevel::Progress = nullptr
Set this member to support progress/cancel in the computations below.
Definition at line 82 of file MeshBevel.h.
ResultInfo
FGeometryResult UE::Geometry::FMeshBevel::ResultInfo = FGeometryResult(EGeometryResultType::InProgress)
status of the operation, warnings/errors may be returned here
Definition at line 93 of file MeshBevel.h.
RoundWeight
double UE::Geometry::FMeshBevel::RoundWeight = 1.0
"Roundness" of the bevel profile.
Ignored if Subdivisions = 0. Default=1 means try to be circular-ish. Higher values pull towards a sharper crease. 0 is flat (ie no profile, a linear chamfer). If negative, bevel profile will be an inverted-arc
Definition at line 67 of file MeshBevel.h.
SetConstantMaterialID
int32 UE::Geometry::FMeshBevel::SetConstantMaterialID = 0
Constant MaterialID used for various MaterialIDMode settings.
Definition at line 79 of file MeshBevel.h.
VertexIDToIndexMap
TMap<int32, int32> UE::Geometry::FMeshBevel::VertexIDToIndexMap protected
Definition at line 292 of file MeshBevel.h.
Vertices
TArray<FBevelVertex> UE::Geometry::FMeshBevel::Vertices protected
Definition at line 293 of file MeshBevel.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/MeshBevel.h