Unreal Engine 5.6 C++ API: FRigVMPropertyPath Class Reference
FRigVMPropertyPath Class Reference
The RigVMPropertyPath is used to access a memory pointer for a tail property given the memory of the head property.
#include "RigVMPropertyPath.h"
Public Member Functions
RIGVM_API FRigVMPropertyPath ()
RIGVM_API FRigVMPropertyPath (const FProperty *InProperty, const FString &InSegmentPath)
Constructor from complete data.
template<typename T>
T * GetData (uint8 *InPtr, const FProperty *InProperty) const
Accessor for traversing the path and returning the memory of the tail.
const TArray< FRigVMPropertyPathSegment > & GetSegments () const
RIGVM_API const FProperty * GetTailProperty () const
bool IsEmpty () const
bool IsValid () const
int32 Num () const
bool operator!= (const FRigVMPropertyPath &Other) const
bool operator< (const FRigVMPropertyPath &Other) const
bool operator== (const FRigVMPropertyPath &Other) const
bool operator> (const FRigVMPropertyPath &Other) const
const FRigVMPropertyPathSegment & operator[] (int32 InIndex) const
const FString & ToString () const
Static Public Attributes
static RIGVM_API FRigVMPropertyPath Empty
Private Member Functions
RIGVM_API uint8 * GetData_Internal (uint8 *InPtr, const FProperty *InProperty) const
Private Attributes
FString Path
TArray< FRigVMPropertyPathSegment > Segments
Friends
uint32 GetTypeHash (const FRigVMPropertyPath &InPropertyPath)
Detailed Description
The RigVMPropertyPath is used to access a memory pointer for a tail property given the memory of the head property.
A property path allows to traverse struct members, array elements and map values. For example given an array of transforms the property path '[2].Translation.X' is represented as three segments (1 array element and 2 struct members).
Definition at line 104 of file RigVMPropertyPath.h.
Constructor & Destructor Documentation
FRigVMPropertyPath() [1/2]
RIGVM_API FRigVMPropertyPath::FRigVMPropertyPath ()
References UE_API.
Referenced by GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
FRigVMPropertyPath() [2/2]
RIGVM_API FRigVMPropertyPath::FRigVMPropertyPath (const FProperty * InProperty, const FString & InSegmentPath)
Constructor from complete data.
Parameters
InProperty The head property to base this property path off of
InSegmentPath A . separated string providing all of the segments of this path
References UE_API.
Member Function Documentation
GetData()
template<typename T> T * FRigVMPropertyPath::GetData (uint8 * InPtr, const FProperty * InProperty) const inline
Accessor for traversing the path and returning the memory of the tail.
Parameters
InPtr The memory of the head property
InProperty The head property to traverse off of
Definition at line 162 of file RigVMPropertyPath.h.
References GetData_Internal().
GetData_Internal()
RIGVM_API uint8 * FRigVMPropertyPath::GetData_Internal (uint8 * InPtr, const FProperty * InProperty) const private
References UE_API.
Referenced by GetData().
GetSegments()
const TArray< FRigVMPropertyPathSegment > & FRigVMPropertyPath::GetSegments () const inline
Definition at line 134 of file RigVMPropertyPath.h.
References Segments.
GetTailProperty()
RIGVM_API const FProperty * FRigVMPropertyPath::GetTailProperty () const
References UE_API.
IsEmpty()
bool FRigVMPropertyPath::IsEmpty () const inline
Definition at line 128 of file RigVMPropertyPath.h.
References Num().
Referenced by GetTypeHash.
IsValid()
bool FRigVMPropertyPath::IsValid () const inline
Definition at line 125 of file RigVMPropertyPath.h.
References Num().
Num()
int32 FRigVMPropertyPath::Num () const inline
Definition at line 122 of file RigVMPropertyPath.h.
References Segments.
Referenced by IsEmpty(), and IsValid().
operator!=()
bool FRigVMPropertyPath::operator!= (const FRigVMPropertyPath & Other) const inline
Definition at line 141 of file RigVMPropertyPath.h.
References FRigVMPropertyPath(), GetTypeHash, and Other.
operator<()
bool FRigVMPropertyPath::operator< (const FRigVMPropertyPath & Other) const inline
Definition at line 151 of file RigVMPropertyPath.h.
References FRigVMPropertyPath(), GetTypeHash, and Other.
operator==()
bool FRigVMPropertyPath::operator== (const FRigVMPropertyPath & Other) const inline
Definition at line 136 of file RigVMPropertyPath.h.
References FRigVMPropertyPath(), GetTypeHash, and Other.
operator>()
bool FRigVMPropertyPath::operator> (const FRigVMPropertyPath & Other) const inline
Definition at line 146 of file RigVMPropertyPath.h.
References FRigVMPropertyPath(), GetTypeHash, and Other.
operator[]()
const FRigVMPropertyPathSegment & FRigVMPropertyPath::operator[] (int32 InIndex) const inline
Definition at line 131 of file RigVMPropertyPath.h.
References Segments.
ToString()
const FString & FRigVMPropertyPath::ToString () const inline
Definition at line 119 of file RigVMPropertyPath.h.
References Path.
Referenced by GetTypeHash.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRigVMPropertyPath & InPropertyPath) friend
Definition at line 168 of file RigVMPropertyPath.h.
References FRigVMPropertyPath(), GetTypeHash, HashCombine(), IsEmpty(), Property, and ToString().
Referenced by GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
Field Documentation
Empty
RIGVM_API FRigVMPropertyPath FRigVMPropertyPath::Empty static
Definition at line 185 of file RigVMPropertyPath.h.
Referenced by FRigVMMemoryHandle::GetPropertyPathRef().
Path
FString FRigVMPropertyPath::Path private
Definition at line 193 of file RigVMPropertyPath.h.
Referenced by ToString().
Segments
TArray<FRigVMPropertyPathSegment> FRigVMPropertyPath::Segments private
Definition at line 196 of file RigVMPropertyPath.h.
Referenced by GetSegments(), Num(), and operator[]().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMPropertyPath.h