Unreal Engine 5.6 C++ API: ISlateStyle Class Reference
ISlateStyle Class Reference abstract
#include "ISlateStyle.h"
Public Member Functions
ISlateStyle ()
Constructor.
virtual ~ISlateStyle ()
Destructor.
virtual const FSlateBrush * GetBrush (const FName PropertyName, const ANSICHAR *Specifier=nullptr, const ISlateStyle *RequestingStyle=nullptr) const =0
virtual const FLinearColor & GetColor (const FName PropertyName, const ANSICHAR *Specifier=nullptr, const FLinearColor &DefaultValue=FStyleDefaults::GetColor(), const ISlateStyle *RequestingStyle=nullptr) const =0
virtual FString GetContentRootDir () const =0
virtual FSlateBrush * GetDefaultBrush () const =0
Get default FSlateBrush.
virtual const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (const FName BrushTemplate, const ANSICHAR *Specifier, UTexture2D *TextureResource, const FName TextureName, const ISlateStyle *RequestingStyle=nullptr) const =0
virtual const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (const FName BrushTemplate, const FName TextureName, const ANSICHAR *Specifier=nullptr, const ISlateStyle *RequestingStyle=nullptr) const =0
virtual const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (const FName BrushTemplate, UTexture2D *TextureResource, const FName TextureName, const ISlateStyle *RequestingStyle=nullptr) const =0
virtual TArray< FName > GetEntriesUsingBrush (const FName BrushName) const =0
Gets the names of every style entry using a brush in this style Note: this function is expensive and is not designed to be used in performance critical situations.
virtual float GetFloat (const FName PropertyName, const ANSICHAR *Specifier=nullptr, float DefaultValue=FStyleDefaults::GetFloat(), const ISlateStyle *RequestingStyle=nullptr) const =0
virtual FSlateFontInfo GetFontStyle (const FName PropertyName, const ANSICHAR *Specifier=nullptr) const =0
virtual const FMargin & GetMargin (const FName PropertyName, const ANSICHAR *Specifier=nullptr, const FMargin &DefaultValue=FStyleDefaults::GetMargin(), const ISlateStyle *RequestingStyle=nullptr) const =0
virtual const FSlateBrush * GetOptionalBrush (const FName PropertyName, const ANSICHAR *Specifier=nullptr, const FSlateBrush *const DefaultBrush=FStyleDefaults::GetNoBrush()) const =0
Just like GetBrush, but returns DefaultBrush instead of the "missing brush" image when the resource is not found.
virtual void GetResources (TArray< const FSlateBrush * > &OutResources) const =0
Populate an array of FSlateBrush with resources consumed by this style.
virtual const FSlateColor GetSlateColor (const FName PropertyName, const ANSICHAR *Specifier=nullptr, const FSlateColor &DefaultValue=FStyleDefaults::GetSlateColor(), const ISlateStyle *RequestingStyle=nullptr) const =0
virtual const FSlateSound & GetSound (const FName PropertyName, const ANSICHAR *Specifier=nullptr, const ISlateStyle *RequestingStyle=nullptr) const =0
Look up a sound property specified by PropertyName and optional Specifier.
virtual TSet< FName > GetStyleKeys () const =0
virtual const FName & GetStyleSetName () const =0
virtual UE::Slate::FDeprecateVector2DResult GetVector (const FName PropertyName, const ANSICHAR *Specifier=nullptr, UE::Slate::FDeprecateVector2DParameter DefaultValue=FStyleDefaults::GetVector2D(), const ISlateStyle *RequestingStyle=nullptr) const =0
const FSlateWidgetStyle * GetWidgetStyle (const FName &WidgetStyleTypeName, FName PropertyName, const ANSICHAR *Specifier=nullptr, const FSlateWidgetStyle *DefaultValue=nullptr, bool bWarnIfNotFound=true) const
template<typename WidgetStyleType>
const WidgetStyleType & GetWidgetStyle (FName PropertyName, const ANSICHAR *Specifier, const WidgetStyleType *DefaultValue, bool bWarnIfNotFound) const
Locates a widget style of a specified type and name.
template<typename WidgetStyleType>
const WidgetStyleType & GetWidgetStyle (FName PropertyName, const ANSICHAR *Specifier=nullptr, const WidgetStyleType *DefaultValue=nullptr) const
Locates a widget style of a specified type and name.
virtual const TSet< FName > & GetWidgetStyleNames () const
template<typename WidgetStyleType>
bool HasWidgetStyle (FName PropertyName, const ANSICHAR *Specifier=nullptr) const
Static Public Member Functions
static FName Join (FName A, const ANSICHAR *B)
Protected Types
enum class EStyleMessageSeverity : uint8 {
UE_DEPRECATED =(5.1, "CriticalError was removed because it can't trigger an assert at the callsite. Use 'checkf' instead.") = 0 , Error = 1 , PerformanceWarning = 2 , Warning = 3 ,
Info = 4
}
The severity of the message type Ordered according to their severity.
Protected Member Functions
virtual const FSlateWidgetStyle * GetWidgetStyleInternal (const FName DesiredTypeName, const FName StyleName, const FSlateWidgetStyle *DefaultStyle, bool bWarnIfNotFound) const =0
virtual void Log (EStyleMessageSeverity Severity, const FText &Message) const =0
virtual void LogMissingResource (EStyleMessageSeverity Severity, const FText &Message, const FName &MissingResource) const =0
virtual const TSharedPtr< FSlateDynamicImageBrush > MakeDynamicImageBrush (const FName BrushTemplate, UTexture2D *TextureResource, const FName TextureName) const =0
Friends
class ISlateStyle
class FSlateStyleSet
Detailed Description
Definition at line 17 of file ISlateStyle.h.
Member Enumeration Documentation
EStyleMessageSeverity
enum class ISlateStyle::EStyleMessageSeverity : uint8 strong protected
The severity of the message type Ordered according to their severity.
Enumerator
UE_DEPRECATED
Error
PerformanceWarning
Warning
Info
Definition at line 207 of file ISlateStyle.h.
Constructor & Destructor Documentation
ISlateStyle()
ISlateStyle::ISlateStyle () inline
Constructor.
Definition at line 21 of file ISlateStyle.h.
~ISlateStyle()
virtual ISlateStyle::~ISlateStyle () inline virtual
Destructor.
Definition at line 25 of file ISlateStyle.h.
Member Function Documentation
GetBrush()
virtual const FSlateBrush * ISlateStyle::GetBrush (const FName PropertyName, const ANSICHAR * Specifier = nullptr, const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
Returns
an FSlateBrush property.
Implemented in FSlateGameResources, and FSlateStyleSet.
References ISlateStyle, and PropertyName.
Referenced by FArguments< ItemType >::GetBorder(), FAppStyle::GetBrush(), and FFolderDragDropOp::Init().
GetColor()
virtual const FLinearColor & ISlateStyle::GetColor (const FName PropertyName, const ANSICHAR * Specifier = nullptr, const FLinearColor & DefaultValue = FStyleDefaults::GetColor(), const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
DefaultValue The default value to return if the property cannot be found
Returns
a FLinearColor property.
Implemented in FSlateStyleSet.
References ISlateStyle, FStyleDefaults::GetColor(), and PropertyName.
Referenced by FAppStyle::GetColor().
GetContentRootDir()
virtual FString ISlateStyle::GetContentRootDir () const pure virtual
Implemented in FSlateStyleSet.
GetDefaultBrush()
virtual FSlateBrush * ISlateStyle::GetDefaultBrush () const pure virtual
Get default FSlateBrush.
Returns
- Default Slate brush value.
Implemented in FSlateStyleSet.
Referenced by FAppStyle::GetDefaultBrush().
GetDynamicImageBrush() [1/3]
virtual const TSharedPtr< FSlateDynamicImageBrush > ISlateStyle::GetDynamicImageBrush (const FName BrushTemplate, const ANSICHAR * Specifier, UTexture2D * TextureResource, const FName TextureName, const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Implemented in FSlateStyleSet.
References ISlateStyle.
GetDynamicImageBrush() [2/3]
virtual const TSharedPtr< FSlateDynamicImageBrush > ISlateStyle::GetDynamicImageBrush (const FName BrushTemplate, const FName TextureName, const ANSICHAR * Specifier = nullptr, const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Implemented in FSlateStyleSet.
References ISlateStyle.
Referenced by FAppStyle::GetDynamicImageBrush(), FAppStyle::GetDynamicImageBrush(), and FAppStyle::GetDynamicImageBrush().
GetDynamicImageBrush() [3/3]
virtual const TSharedPtr< FSlateDynamicImageBrush > ISlateStyle::GetDynamicImageBrush (const FName BrushTemplate, UTexture2D * TextureResource, const FName TextureName, const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Implemented in FSlateStyleSet.
References ISlateStyle.
GetEntriesUsingBrush()
virtual TArray< FName > ISlateStyle::GetEntriesUsingBrush (const FName BrushName) const pure virtual
Gets the names of every style entry using a brush in this style Note: this function is expensive and is not designed to be used in performance critical situations.
Parameters
BrushName The name of the brush to find style entries from
Returns
Array of style names using the brush
Implemented in FSlateStyleSet.
GetFloat()
virtual float ISlateStyle::GetFloat (const FName PropertyName, const ANSICHAR * Specifier = nullptr, float DefaultValue = FStyleDefaults::GetFloat(), const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
DefaultValue The default value to return if the property cannot be found
Returns
a float property.
Implemented in FSlateStyleSet.
References ISlateStyle, FStyleDefaults::GetFloat(), and PropertyName.
Referenced by FAppStyle::GetFloat(), and UE::CurveEditor::MakeResizeParams().
GetFontStyle()
virtual FSlateFontInfo ISlateStyle::GetFontStyle (const FName PropertyName, const ANSICHAR * Specifier = nullptr) const pure virtual
Parameters
Propertyname Name of the property to get
InFontInfo The value to set
Returns
a InFontInfo property.
Implemented in FSlateStyleSet.
References PropertyName.
Referenced by FAppStyle::GetFontStyle(), and STimecodeProvider::SLATE_BEGIN_ARGS().
GetMargin()
virtual const FMargin & ISlateStyle::GetMargin (const FName PropertyName, const ANSICHAR * Specifier = nullptr, const FMargin & DefaultValue = FStyleDefaults::GetMargin(), const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
DefaultValue The default value to return if the property cannot be found
Returns
a FMargin property.
Implemented in FSlateStyleSet.
References ISlateStyle, FStyleDefaults::GetMargin(), and PropertyName.
Referenced by FAppStyle::GetMargin().
GetOptionalBrush()
virtual const FSlateBrush * ISlateStyle::GetOptionalBrush (const FName PropertyName, const ANSICHAR * Specifier = nullptr, const FSlateBrush *const DefaultBrush = FStyleDefaults::GetNoBrush()) const pure virtual
Just like GetBrush, but returns DefaultBrush instead of the "missing brush" image when the resource is not found.
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
Returns
an FSlateBrush property.
Implemented in FSlateGameResources, and FSlateStyleSet.
References FStyleDefaults::GetNoBrush(), and PropertyName.
Referenced by FAppStyle::GetOptionalBrush().
GetResources()
virtual void ISlateStyle::GetResources (TArray< const FSlateBrush * > & OutResources) const pure virtual
Populate an array of FSlateBrush with resources consumed by this style.
Parameters
OutResources - the array to populate.
Implemented in FSlateGameResources, and FSlateStyleSet.
GetSlateColor()
virtual const FSlateColor ISlateStyle::GetSlateColor (const FName PropertyName, const ANSICHAR * Specifier = nullptr, const FSlateColor & DefaultValue = FStyleDefaults::GetSlateColor(), const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
DefaultValue The default value to return if the property cannot be found
Returns
a FLinearColor property.
Implemented in FSlateStyleSet.
References ISlateStyle, FStyleDefaults::GetSlateColor(), and PropertyName.
Referenced by FDiffSingleResult::GetDisplayColor(), and FAppStyle::GetSlateColor().
GetSound()
virtual const FSlateSound & ISlateStyle::GetSound (const FName PropertyName, const ANSICHAR * Specifier = nullptr, const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Look up a sound property specified by PropertyName and optional Specifier.
Implemented in FSlateStyleSet.
References ISlateStyle, and PropertyName.
Referenced by FAppStyle::GetSound().
GetStyleKeys()
virtual TSet< FName > ISlateStyle::GetStyleKeys () const pure virtual
Implemented in FSlateStyleSet.
GetStyleSetName()
virtual const FName & ISlateStyle::GetStyleSetName () const pure virtual
Returns
The name used to identity this style set
Implemented in FSlateStyleSet.
GetVector()
virtual UE::Slate::FDeprecateVector2DResult ISlateStyle::GetVector (const FName PropertyName, const ANSICHAR * Specifier = nullptr, UE::Slate::FDeprecateVector2DParameter DefaultValue = FStyleDefaults::GetVector2D(), const ISlateStyle * RequestingStyle = nullptr) const pure virtual
Parameters
PropertyName Name of the property to get
Specifier An optional string to append to the property name
DefaultValue The default value to return if the property cannot be found
Returns
a FVector2D property.
Implemented in FSlateStyleSet.
References ISlateStyle, FStyleDefaults::GetVector2D(), and PropertyName.
Referenced by FAppStyle::GetVector().
GetWidgetStyle() [1/3]
const FSlateWidgetStyle * ISlateStyle::GetWidgetStyle (const FName & WidgetStyleTypeName, FName PropertyName, const ANSICHAR * Specifier = nullptr, const FSlateWidgetStyle * DefaultValue = nullptr, bool bWarnIfNotFound = true) const inline
Definition at line 83 of file ISlateStyle.h.
References GetWidgetStyleInternal(), Join(), and PropertyName.
GetWidgetStyle() [2/3]
template<typename WidgetStyleType> const WidgetStyleType & ISlateStyle::GetWidgetStyle (FName PropertyName, const ANSICHAR * Specifier, const WidgetStyleType * DefaultValue, bool bWarnIfNotFound) const inline
Locates a widget style of a specified type and name.
Allows customization of whether a warning should be logged.
Returns
The found widget style or the default value.
Definition at line 53 of file ISlateStyle.h.
References GetWidgetStyleInternal(), Join(), and PropertyName.
Referenced by FRigVMEditorStyle::FRigVMEditorStyle(), FAppStyle::GetWidgetStyle(), GetWidgetStyle(), SAudioRadialSlider::SLATE_BEGIN_ARGS(), SAudioSliderBase::SLATE_BEGIN_ARGS(), and SAudioTextBox::SLATE_BEGIN_ARGS().
GetWidgetStyle() [3/3]
template<typename WidgetStyleType> const WidgetStyleType & ISlateStyle::GetWidgetStyle (FName PropertyName, const ANSICHAR * Specifier = nullptr, const WidgetStyleType * DefaultValue = nullptr) const inline
Locates a widget style of a specified type and name.
Parameters
DefaultValue The value to use if a widget style could not be found. If null and no style could be found, a warning will be logged.
Returns
The found widget style or the default value.
Definition at line 71 of file ISlateStyle.h.
References GetWidgetStyle(), and PropertyName.
GetWidgetStyleInternal()
virtual const FSlateWidgetStyle * ISlateStyle::GetWidgetStyleInternal (const FName DesiredTypeName, const FName StyleName, const FSlateWidgetStyle * DefaultStyle, bool bWarnIfNotFound) const protected pure virtual
Implemented in FSlateGameResources, and FSlateStyleSet.
Referenced by GetWidgetStyle(), GetWidgetStyle(), and HasWidgetStyle().
GetWidgetStyleNames()
virtual const TSet< FName > & ISlateStyle::GetWidgetStyleNames () const inline virtual
Reimplemented in FSlateStyleSet.
Definition at line 196 of file ISlateStyle.h.
HasWidgetStyle()
template<typename WidgetStyleType> bool ISlateStyle::HasWidgetStyle (FName PropertyName, const ANSICHAR * Specifier = nullptr) const inline
Definition at line 77 of file ISlateStyle.h.
References GetWidgetStyleInternal(), Join(), and PropertyName.
Join()
FName ISlateStyle::Join (FName A, const ANSICHAR * B) inline static
Definition at line 182 of file ISlateStyle.h.
References A, B, and FName.
Referenced by GetWidgetStyle(), GetWidgetStyle(), HasWidgetStyle(), TInteractiveToolCommands< CommandContextType >::RegisterUIToolCommand(), and EMultiBlockLocation::ToName().
Log()
virtual void ISlateStyle::Log (EStyleMessageSeverity Severity, const FText & Message) const protected pure virtual
Implemented in FSlateGameResources, and FSlateStyleSet.
LogMissingResource()
virtual void ISlateStyle::LogMissingResource (EStyleMessageSeverity Severity, const FText & Message, const FName & MissingResource) const protected pure virtual
Implemented in FSlateStyleSet.
MakeDynamicImageBrush()
virtual const TSharedPtr< FSlateDynamicImageBrush > ISlateStyle::MakeDynamicImageBrush (const FName BrushTemplate, UTexture2D * TextureResource, const FName TextureName) const protected pure virtual
Implemented in FSlateStyleSet.
Friends And Related Symbol Documentation
ISlateStyle
friend class ISlateStyle friend
Definition at line 220 of file ISlateStyle.h.
References ISlateStyle.
Referenced by ISlateStyle, GetBrush(), GetColor(), GetDynamicImageBrush(), GetDynamicImageBrush(), GetDynamicImageBrush(), GetFloat(), GetMargin(), GetSlateColor(), GetSound(), and GetVector().
FSlateStyleSet
friend class FSlateStyleSet friend
Definition at line 219 of file ISlateStyle.h.
References FSlateStyleSet.
Referenced by FSlateStyleSet.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Styling/ISlateStyle.h