Unreal Engine 5.6 C++ API: FMacPlatformMisc::FGPUDescriptorCommon< T > Class Template Reference
FMacPlatformMisc::FGPUDescriptorCommon< T > Class Template Reference
Common descriptor of each GPU in the OS that provides stock details about the GPU that are innaccessible from the higher-level rendering APIs and provides a direct link to the GPU in the IORegistry.
#include "MacPlatformMisc.h"
Public Member Functions
virtual ~FGPUDescriptorCommon ()
TMap< FString, float > GetPerformanceStatistics () const
FGPUDescriptorCommon & operator= (FGPUDescriptorCommon const &Other)
Data Fields
NSString * GPUBundleID = nil
uint32 GPUDeviceId = 0
bool GPUHeadless = false
uint32 GPUIndex = 0
uint32 GPUMemoryMB = 0
NSString * GPUMetalBundle = nil
NSString * GPUName = nil
NSString * GPUOpenGLBundle = nil
uint32 GPUVendorId = 0
Protected Member Functions
FGPUDescriptorCommon ()=default
FGPUDescriptorCommon (FGPUDescriptorCommon &&Other)=delete
FGPUDescriptorCommon (FGPUDescriptorCommon const &Other)=delete
void CopyFrom (FGPUDescriptorCommon const &Other)
Detailed Description
template<typename T>
class FMacPlatformMisc::FGPUDescriptorCommon< T >
Common descriptor of each GPU in the OS that provides stock details about the GPU that are innaccessible from the higher-level rendering APIs and provides a direct link to the GPU in the IORegistry.
Definition at line 132 of file MacPlatformMisc.h.
Constructor & Destructor Documentation
~FGPUDescriptorCommon()
template<typename T> virtual FMacPlatformMisc::FGPUDescriptorCommon< T >::~FGPUDescriptorCommon () virtual
FGPUDescriptorCommon() [1/3]
template<typename T> FMacPlatformMisc::FGPUDescriptorCommon< T >::FGPUDescriptorCommon () protected default
Referenced by FGPUDescriptorCommon(), FGPUDescriptorCommon(), CopyFrom(), and operator=().
FGPUDescriptorCommon() [2/3]
template<typename T> FMacPlatformMisc::FGPUDescriptorCommon< T >::FGPUDescriptorCommon (FGPUDescriptorCommon< T > const & Other) protected delete
References FGPUDescriptorCommon(), and Other.
FGPUDescriptorCommon() [3/3]
template<typename T> FMacPlatformMisc::FGPUDescriptorCommon< T >::FGPUDescriptorCommon (FGPUDescriptorCommon< T > && Other) protected delete
References FGPUDescriptorCommon(), and Other.
Member Function Documentation
CopyFrom()
template<typename T> void FMacPlatformMisc::FGPUDescriptorCommon< T >::CopyFrom (FGPUDescriptorCommon< T > const & Other) protected
References FGPUDescriptorCommon(), and Other.
GetPerformanceStatistics()
template<typename T> TMap< FString, float > FMacPlatformMisc::FGPUDescriptorCommon< T >::GetPerformanceStatistics () const
operator=()
template<typename T> FGPUDescriptorCommon & FMacPlatformMisc::FGPUDescriptorCommon< T >::operator= (FGPUDescriptorCommon< T > const & Other)
References FGPUDescriptorCommon(), and Other.
Field Documentation
GPUBundleID
template<typename T> NSString* FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUBundleID = nil
Definition at line 152 of file MacPlatformMisc.h.
GPUDeviceId
template<typename T> uint32 FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUDeviceId = 0
Definition at line 154 of file MacPlatformMisc.h.
GPUHeadless
template<typename T> bool FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUHeadless = false
Definition at line 158 of file MacPlatformMisc.h.
GPUIndex
template<typename T> uint32 FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUIndex = 0
Definition at line 156 of file MacPlatformMisc.h.
GPUMemoryMB
template<typename T> uint32 FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUMemoryMB = 0
Definition at line 155 of file MacPlatformMisc.h.
GPUMetalBundle
template<typename T> NSString* FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUMetalBundle = nil
Definition at line 150 of file MacPlatformMisc.h.
GPUName
template<typename T> NSString* FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUName = nil
Definition at line 149 of file MacPlatformMisc.h.
GPUOpenGLBundle
template<typename T> NSString* FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUOpenGLBundle = nil
Definition at line 151 of file MacPlatformMisc.h.
GPUVendorId
template<typename T> uint32 FMacPlatformMisc::FGPUDescriptorCommon< T >::GPUVendorId = 0
Definition at line 153 of file MacPlatformMisc.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Mac/MacPlatformMisc.h