Unreal Engine 5.6 C++ API: USoundCue Class Reference
USoundCue Class Reference
#include "SoundCue.h"
Public Member Functions
virtual void BeginDestroy () override
void CacheAggregateValues ()
Call to cache any values which need to be computed from the sound cue graph.
void CacheLoadingBehavior (ESoundWaveLoadingBehavior InBehavior)
Call this when stream caching is enabled to update sound waves of loading behavior they are inheriting via SoundCue.
virtual bool CanBeClusterRoot () const override
virtual bool CanBeInCluster () const override
void ClearGraph ()
Clears all nodes from the graph (for old editor's buffer soundcue)
void CompileSoundNodesFromGraphNodes ()
Use the EdGraph representation to compile the SoundCue.
template<class T>
T * ConstructSoundNode (TSubclassOf< USoundNode > SoundNodeClass=T::StaticClass(), bool bSelectNewNode=true)
Construct and initialize a node within this Cue.
void CreateGraph ()
Create the basic sound graph.
virtual TSharedPtr< Audio::IParameterTransmitter > CreateParameterTransmitter (Audio::FParameterTransmitterInitParams &&InParams) const override
float EvaluateMaxAttenuation (const FTransform &Origin, FVector Location, float DistanceScale=1.f) const
For SoundCues, use this instead of GetAttenuationSettingsToApply() -> Evaluate.
bool FindPathToNode (const UPTRINT NodeHashToFind, TArray< USoundNode * > &OutPath) const
Find the path through the sound cue to a node identified by its hash.
virtual const FSoundAttenuationSettings * GetAttenuationSettingsToApply () const override
int32 GetCookedQualityIndex () const
Set the Quality level that the Cue was cooked at, called by the SoundQualityNodes.
virtual FString GetDesc () override
virtual float GetDuration () const override
UEdGraph * GetGraph ()
Get the EdGraph of SoundNodes.
virtual float GetMaxDistance () const override
virtual float GetPitchMultiplier () override
virtual int32 GetResourceSizeForFormat (FName Format)
virtual bool GetSoundWavesWithCookedAnalysisData (TArray< USoundWave * > &OutSoundWaves) override
virtual float GetSubtitlePriority () const override
virtual float GetVolumeMultiplier () override
virtual bool HasCookedAmplitudeEnvelopeData () const override
virtual bool HasCookedFFTData () const override
virtual bool IsAttenuationSettingsEditable () const override
virtual bool IsPlayable () const override
virtual bool IsPlayWhenSilent () const override
void LinkGraphNodesFromSoundNodes ()
Use the SoundCue's children to link EdGraph Nodes together.
virtual void Parse (class FAudioDevice *AudioDevice, const UPTRINT NodeWaveInstanceHash, FActiveSound &ActiveSound, const FSoundParseParameters &ParseParams, TArray< FWaveInstance * > &WaveInstances) override
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostLoad () override
void PrimeSoundCue ()
Call this when stream caching is enabled to prime all SoundWave assets referenced by this Sound Cue.
void RecursiveFindAllNodes (USoundNode *Node, TArray< USoundNode * > &OutNodes)
Recursively finds all Nodes in the Tree.
void RecursiveFindAttenuation (const USoundNode *Node, TArray< const USoundNodeAttenuation * > &OutNodes) const
void RecursiveFindAttenuation (USoundNode *Node, TArray< USoundNodeAttenuation * > &OutNodes)
template<typename T>
void RecursiveFindNode (const USoundNode *Node, TArray< const T * > &OutNodes) const
template<typename T>
void RecursiveFindNode (USoundNode *Node, TArray< T * > &OutNodes)
Recursively finds sound nodes of type T.
void ReleaseRetainedAudio ()
void ResetGraph ()
Resets all graph data and nodes.
void RetainSoundCue ()
Call this when stream caching is enabled to retain all soundwave assets referenced by this sound cue.
virtual void Serialize (FStructuredArchive::FRecord Record) override
void SetupSoundNode (USoundNode *InSoundNode, bool bSelectNewNode=true)
Set up EdGraph parts of a SoundNode.
virtual bool ShouldApplyInteriorVolumes () override
Static Public Member Functions
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static void CacheQualityLevel ()
static FORCEINLINE int32 GetCachedQualityLevel ()
static TSharedPtr< ISoundCueAudioEditor > GetSoundCueAudioEditor ()
Gets the sound cue graph editor implementation.
static void SetSoundCueAudioEditor (TSharedPtr< ISoundCueAudioEditor > InSoundCueGraphEditor)
Sets the sound cue graph editor implementation.
static void StaticAudioQualityChanged (int32 NewQualityLevel)
Call when the audio quality has been changed.
Protected Member Functions
float ComputeMaxDistance () const override
bool RecursiveFindPathToNode (USoundNode *CurrentNode, const UPTRINT CurrentHash, const UPTRINT NodeHashToFind, TArray< USoundNode * > &OutPath) const
UPROPERTY ()) float SubtitlePriority
Private Member Functions
void AudioQualityChanged ()
void EvaluateNodes (bool bAddToRoot)
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< USoundNode > FirstNode
void OnPostEngineInit ()
void RecursivelySetExcludeBranchCulling (USoundNode *CurrentNode)
Recursively sets the branch culling exclusion on random nodes in this sound cue.
UPROPERTY () float PitchMultiplier
UPROPERTY () float VolumeMultiplier
UPROPERTY () FSoundAttenuationSettings AttenuationOverrides
UPROPERTY () int32 CookedQualityIndex
Private Attributes
UPROPERTY() uint8 bHasPlayWhenSilent uint8 bHasAttenuationNode: 1
Whether a sound has play when silent enabled (i.e.
uint8 bHasAttenuationNodeInitialized: 1
uint8 bIsRetainingAudio: 1
uint8 bShouldApplyInteriorVolumes: 1
uint8 bShouldApplyInteriorVolumesCached: 1
FCriticalSection EditorOnlyCs
float MaxAudibleDistance
FDelegateHandle OnPostEngineInitHandle
Static Private Attributes
static int32 CachedQualityLevel
static TSharedPtr< ISoundCueAudioEditor > SoundCueAudioEditor
Ptr to interface to sound cue editor operations.
Detailed Description
Definition at line 90 of file SoundCue.h.
Member Function Documentation
AddReferencedObjects()
void USoundCue::AddReferencedObjects (UObject * InThis, FReferenceCollector & Collector) static
AudioQualityChanged()
void USoundCue::AudioQualityChanged () private
BeginDestroy()
virtual void USoundCue::BeginDestroy () override virtual
CacheAggregateValues()
void USoundCue::CacheAggregateValues ()
Call to cache any values which need to be computed from the sound cue graph.
e.g. MaxDistance, Duration, etc.
CacheLoadingBehavior()
void USoundCue::CacheLoadingBehavior (ESoundWaveLoadingBehavior InBehavior)
Call this when stream caching is enabled to update sound waves of loading behavior they are inheriting via SoundCue.
CacheQualityLevel()
void USoundCue::CacheQualityLevel () static
CanBeClusterRoot()
virtual bool USoundCue::CanBeClusterRoot () const override virtual
CanBeInCluster()
virtual bool USoundCue::CanBeInCluster () const override virtual
ClearGraph()
void USoundCue::ClearGraph ()
Clears all nodes from the graph (for old editor's buffer soundcue)
CompileSoundNodesFromGraphNodes()
void USoundCue::CompileSoundNodesFromGraphNodes ()
Use the EdGraph representation to compile the SoundCue.
ComputeMaxDistance()
float USoundCue::ComputeMaxDistance () const override protected
ConstructSoundNode()
template<class T> T * USoundCue::ConstructSoundNode (TSubclassOf< USoundNode > SoundNodeClass = T::StaticClass(), bool bSelectNewNode = true) inline
Construct and initialize a node within this Cue.
Definition at line 190 of file SoundCue.h.
References NewObject, RF_Transactional, and SetupSoundNode().
CreateGraph()
void USoundCue::CreateGraph ()
Create the basic sound graph.
CreateParameterTransmitter()
virtual TSharedPtr< Audio::IParameterTransmitter > USoundCue::CreateParameterTransmitter (Audio::FParameterTransmitterInitParams && InParams) const override virtual
EvaluateMaxAttenuation()
float USoundCue::EvaluateMaxAttenuation (const FTransform & Origin, FVector Location, float DistanceScale = 1.f) const
For SoundCues, use this instead of GetAttenuationSettingsToApply() -> Evaluate.
In cases where a SoundCue has multiple Attenuation nodes within it, this function evaluates them all and returns the maximum value
Returns
float representing the max evaluated attenuation curve value based on distance from Origin to Location (will be 1.0 if no attenuation is set)
References FVector, Location, and Origin.
EvaluateNodes()
void USoundCue::EvaluateNodes (bool bAddToRoot) private
FindPathToNode()
bool USoundCue::FindPathToNode (const UPTRINT NodeHashToFind, TArray< USoundNode * > & OutPath) const
Find the path through the sound cue to a node identified by its hash.
GENERATED_UCLASS_BODY()
USoundCue::GENERATED_UCLASS_BODY () private
References Category, Sound, and UPROPERTY().
GetAttenuationSettingsToApply()
virtual const FSoundAttenuationSettings * USoundCue::GetAttenuationSettingsToApply () const override virtual
GetCachedQualityLevel()
FORCEINLINE int32 USoundCue::GetCachedQualityLevel () inline static
Definition at line 262 of file SoundCue.h.
References CachedQualityLevel, and FORCEINLINE.
GetCookedQualityIndex()
int32 USoundCue::GetCookedQualityIndex () const inline
Set the Quality level that the Cue was cooked at, called by the SoundQualityNodes.
Definition at line 265 of file SoundCue.h.
GetDesc()
virtual FString USoundCue::GetDesc () override virtual
References GetDesc().
Referenced by GetDesc().
GetDuration()
virtual float USoundCue::GetDuration () const override virtual
GetGraph()
UEdGraph * USoundCue::GetGraph ()
Get the EdGraph of SoundNodes.
GetMaxDistance()
virtual float USoundCue::GetMaxDistance () const override virtual
GetPitchMultiplier()
virtual float USoundCue::GetPitchMultiplier () override virtual
GetResourceSizeForFormat()
virtual int32 USoundCue::GetResourceSizeForFormat (FName Format) virtual
Parameters
Format Format to check
Returns
Sum of the size of waves referenced by this cue for the given platform.
References Format.
GetSoundCueAudioEditor()
TSharedPtr< ISoundCueAudioEditor > USoundCue::GetSoundCueAudioEditor () static
Gets the sound cue graph editor implementation.
GetSoundWavesWithCookedAnalysisData()
virtual bool USoundCue::GetSoundWavesWithCookedAnalysisData (TArray< USoundWave * > & OutSoundWaves) override virtual
GetSubtitlePriority()
virtual float USoundCue::GetSubtitlePriority () const override virtual
GetVolumeMultiplier()
virtual float USoundCue::GetVolumeMultiplier () override virtual
HasCookedAmplitudeEnvelopeData()
virtual bool USoundCue::HasCookedAmplitudeEnvelopeData () const override virtual
HasCookedFFTData()
virtual bool USoundCue::HasCookedFFTData () const override virtual
IsAttenuationSettingsEditable()
virtual bool USoundCue::IsAttenuationSettingsEditable () const inline override virtual
Definition at line 185 of file SoundCue.h.
IsPlayable()
virtual bool USoundCue::IsPlayable () const override virtual
IsPlayWhenSilent()
virtual bool USoundCue::IsPlayWhenSilent () const override virtual
LinkGraphNodesFromSoundNodes()
void USoundCue::LinkGraphNodesFromSoundNodes ()
Use the SoundCue's children to link EdGraph Nodes together.
OnPostEngineInit()
void USoundCue::OnPostEngineInit () private
Parse()
virtual void USoundCue::Parse (class FAudioDevice * AudioDevice, const UPTRINT NodeWaveInstanceHash, FActiveSound & ActiveSound, const FSoundParseParameters & ParseParams, TArray< FWaveInstance * > & WaveInstances) override virtual
PostEditChangeProperty()
virtual void USoundCue::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void USoundCue::PostInitProperties () override virtual
PostLoad()
virtual void USoundCue::PostLoad () override virtual
PrimeSoundCue()
void USoundCue::PrimeSoundCue ()
Call this when stream caching is enabled to prime all SoundWave assets referenced by this Sound Cue.
RecursiveFindAllNodes()
void USoundCue::RecursiveFindAllNodes (USoundNode * Node, TArray< USoundNode * > & OutNodes)
Recursively finds all Nodes in the Tree.
RecursiveFindAttenuation() [1/2]
void USoundCue::RecursiveFindAttenuation (const USoundNode * Node, TArray< const USoundNodeAttenuation * > & OutNodes) const
RecursiveFindAttenuation() [2/2]
void USoundCue::RecursiveFindAttenuation (USoundNode * Node, TArray< USoundNodeAttenuation * > & OutNodes)
RecursiveFindNode() [1/2]
template<typename T> void USoundCue::RecursiveFindNode (const USoundNode * Node, TArray< const T * > & OutNodes) const inline
Definition at line 237 of file SoundCue.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), Cast(), and RecursiveFindNode().
RecursiveFindNode() [2/2]
template<typename T> void USoundCue::RecursiveFindNode (USoundNode * Node, TArray< T * > & OutNodes) inline
Recursively finds sound nodes of type T.
Definition at line 217 of file SoundCue.h.
References TArray< InElementType, InAllocatorType >::AddUnique(), Cast(), and RecursiveFindNode().
Referenced by RecursiveFindNode(), and RecursiveFindNode().
RecursiveFindPathToNode()
bool USoundCue::RecursiveFindPathToNode (USoundNode * CurrentNode, const UPTRINT CurrentHash, const UPTRINT NodeHashToFind, TArray< USoundNode * > & OutPath) const protected
RecursivelySetExcludeBranchCulling()
void USoundCue::RecursivelySetExcludeBranchCulling (USoundNode * CurrentNode) private
Recursively sets the branch culling exclusion on random nodes in this sound cue.
ReleaseRetainedAudio()
void USoundCue::ReleaseRetainedAudio ()
ResetGraph()
void USoundCue::ResetGraph ()
Resets all graph data and nodes.
RetainSoundCue()
void USoundCue::RetainSoundCue ()
Call this when stream caching is enabled to retain all soundwave assets referenced by this sound cue.
Serialize()
virtual void USoundCue::Serialize (FStructuredArchive::FRecord Record) override virtual
References Record.
SetSoundCueAudioEditor()
void USoundCue::SetSoundCueAudioEditor (TSharedPtr< ISoundCueAudioEditor > InSoundCueGraphEditor) static
Sets the sound cue graph editor implementation.
SetupSoundNode()
void USoundCue::SetupSoundNode (USoundNode * InSoundNode, bool bSelectNewNode = true)
Set up EdGraph parts of a SoundNode.
Referenced by ConstructSoundNode().
ShouldApplyInteriorVolumes()
virtual bool USoundCue::ShouldApplyInteriorVolumes () override virtual
StaticAudioQualityChanged()
void USoundCue::StaticAudioQualityChanged (int32 NewQualityLevel) static
Call when the audio quality has been changed.
UPROPERTY() [1/5]
USoundCue::UPROPERTY () private
References Category, Sound, and UPROPERTY().
UPROPERTY() [2/5]
USoundCue::UPROPERTY () private
References Category, Sound, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/5]
USoundCue::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [4/5]
USoundCue::UPROPERTY () private
References INDEX_NONE, and UPROPERTY().
UPROPERTY() [5/5]
USoundCue::UPROPERTY () protected
References Category, float, and Meta.
Field Documentation
bHasAttenuationNode
UPROPERTY () uint8 bHasPlayWhenSilent uint8 USoundCue::bHasAttenuationNode private
Whether a sound has play when silent enabled (i.e.
for a sound cue, if any sound wave player has it enabled).
Definition at line 145 of file SoundCue.h.
bHasAttenuationNodeInitialized
uint8 USoundCue::bHasAttenuationNodeInitialized private
Definition at line 146 of file SoundCue.h.
bIsRetainingAudio
uint8 USoundCue::bIsRetainingAudio private
Definition at line 149 of file SoundCue.h.
bShouldApplyInteriorVolumes
uint8 USoundCue::bShouldApplyInteriorVolumes private
Definition at line 147 of file SoundCue.h.
bShouldApplyInteriorVolumesCached
uint8 USoundCue::bShouldApplyInteriorVolumesCached private
Definition at line 148 of file SoundCue.h.
CachedQualityLevel
int32 USoundCue::CachedQualityLevel static private
Definition at line 290 of file SoundCue.h.
Referenced by GetCachedQualityLevel().
EditorOnlyCs
FCriticalSection USoundCue::EditorOnlyCs private
Definition at line 346 of file SoundCue.h.
MaxAudibleDistance
float USoundCue::MaxAudibleDistance private
Definition at line 123 of file SoundCue.h.
OnPostEngineInitHandle
FDelegateHandle USoundCue::OnPostEngineInitHandle private
Definition at line 289 of file SoundCue.h.
SoundCueAudioEditor
TSharedPtr<ISoundCueAudioEditor> USoundCue::SoundCueAudioEditor static private
Ptr to interface to sound cue editor operations.
Definition at line 344 of file SoundCue.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Sound/SoundCue.h