Unreal Engine 5.6 C++ API: FCanvasRenderContext Class Reference
FCanvasRenderContext Class Reference
#include "CanvasRender.h"
Public Member Functions
FCanvasRenderContext (FRDGBuilder &InGraphBuilder, const FRenderTarget *RenderTarget, FIntRect InViewportRect, FIntRect InScissorRect, bool bScaledToRenderTarget)
template<typename ExecuteLambdaType, typename ParameterStructType>
void AddPass (FRDGEventName &&PassName, const ParameterStructType *PassParameters, ExecuteLambdaType &&ExecuteLambda)
template<typename ExecuteLambdaType>
void AddPass (FRDGEventName &&PassName, ExecuteLambdaType &&ExecuteLambda)
template<typename T, typename... TArgs>
T * Alloc (TArgs &&... Args)
template<typename T>
void DeferredDelete (const T *Ptr)
template<typename T>
void DeferredRelease (TSharedPtr< T > &&Ptr)
FRDGTextureRef GetRenderTarget () const
FIntRect GetScissorRect () const
FIntRect GetViewportRect () const
Data Fields
FRDGBuilder & GraphBuilder
Private Attributes
FRDGTextureRef RenderTarget
FIntRect ScissorRect
FIntRect ViewportRect
Detailed Description
Definition at line 8 of file CanvasRender.h.
Constructor & Destructor Documentation
FCanvasRenderContext()
FCanvasRenderContext::FCanvasRenderContext (FRDGBuilder & InGraphBuilder, const FRenderTarget * RenderTarget, FIntRect InViewportRect, FIntRect InScissorRect, bool bScaledToRenderTarget)
References RenderTarget.
Member Function Documentation
AddPass() [1/2]
template<typename ExecuteLambdaType, typename ParameterStructType> void FCanvasRenderContext::AddPass (FRDGEventName && PassName, const ParameterStructType * PassParameters, ExecuteLambdaType && ExecuteLambda) inline
Definition at line 14 of file CanvasRender.h.
References Forward(), GraphBuilder, Raster, ScissorRect, and ViewportRect.
Referenced by AddPass(), and FCanvasRenderThreadScope::AddPass().
AddPass() [2/2]
template<typename ExecuteLambdaType> void FCanvasRenderContext::AddPass (FRDGEventName && PassName, ExecuteLambdaType && ExecuteLambda) inline
Definition at line 31 of file CanvasRender.h.
References AddPass(), Forward(), GraphBuilder, and RenderTarget.
Alloc()
template<typename T, typename... TArgs> T * FCanvasRenderContext::Alloc (TArgs &&... Args) inline
Definition at line 39 of file CanvasRender.h.
References Forward(), and GraphBuilder.
Referenced by DeferredDelete(), and DeferredRelease().
DeferredDelete()
template<typename T> void FCanvasRenderContext::DeferredDelete (const T * Ptr) inline
Definition at line 52 of file CanvasRender.h.
References Alloc().
Referenced by FCanvasRenderThreadScope::DeferredDelete().
DeferredRelease()
template<typename T> void FCanvasRenderContext::DeferredRelease (TSharedPtr< T > && Ptr) inline
Definition at line 45 of file CanvasRender.h.
References Alloc(), and Forward().
GetRenderTarget()
FRDGTextureRef FCanvasRenderContext::GetRenderTarget () const inline
Definition at line 71 of file CanvasRender.h.
References RenderTarget.
GetScissorRect()
FIntRect FCanvasRenderContext::GetScissorRect () const inline
Definition at line 81 of file CanvasRender.h.
References ScissorRect.
GetViewportRect()
FIntRect FCanvasRenderContext::GetViewportRect () const inline
Definition at line 76 of file CanvasRender.h.
References ViewportRect.
Field Documentation
GraphBuilder
FRDGBuilder& FCanvasRenderContext::GraphBuilder
Definition at line 86 of file CanvasRender.h.
Referenced by AddPass(), AddPass(), and Alloc().
RenderTarget
FRDGTextureRef FCanvasRenderContext::RenderTarget private
Definition at line 89 of file CanvasRender.h.
Referenced by FCanvasRenderContext(), AddPass(), and GetRenderTarget().
ScissorRect
FIntRect FCanvasRenderContext::ScissorRect private
Definition at line 91 of file CanvasRender.h.
Referenced by AddPass(), and GetScissorRect().
ViewportRect
FIntRect FCanvasRenderContext::ViewportRect private
Definition at line 90 of file CanvasRender.h.
Referenced by AddPass(), and GetViewportRect().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/CanvasRender.h