Unreal Engine 5.6 C++ API: UBlueprintPathsLibrary Class Reference
UBlueprintPathsLibrary Class Reference
#include "BlueprintPathsLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION() static 1 bool ShouldSaveToUserDir()
Should the "saved" directory structures be rooted in the user dir or relative to the "engine/game".
UFUNCTION () static 1 bool CollapseRelativeDirectories(const FString &InPath
Takes a fully pathed string and eliminates relative pathing (eg: annihilates ".." with the adjacent directory).
UFUNCTION () static 1 bool DirectoryExists(const FString &InPath)
Returns true if this directory was found, false otherwise.
UFUNCTION () static 1 bool FileExists(const FString &InPath)
Returns true if this file was found, false otherwise.
UFUNCTION () static 1 bool HasProjectPersistentDownloadDir()
UFUNCTION () static 1 bool IsDrive(const FString &InPath)
Returns true if this path represents a root drive or volume.
UFUNCTION () static 1 bool IsProjectFilePathSet()
Checks whether the path to the project file, if any, is set.
UFUNCTION () static 1 bool IsRelative(const FString &InPath)
Returns true if this path is relative to another path.
UFUNCTION () static 1 bool IsRestrictedPath(const FString &InPath)
Determines if supplied path uses a restricted/internal subdirectory.
UFUNCTION () static 1 bool IsSamePath(const FString &PathA
Checks if two paths are the same.
UFUNCTION () static 1 bool MakePathRelativeTo(const FString &InPath
Assuming both paths (or filenames) are relative to the same base dir, converts InPath to be relative to InRelativeTo.
UFUNCTION () static 1 const FString &GetRelativePathToRoot()
Gets the relative path to get from BaseDir to RootDirectory.
UFUNCTION () static 1 const TArray< FString > &GetEditorLocalizationPaths()
Returns a list of editor-specific localization paths.
UFUNCTION () static 1 const TArray< FString > &GetEngineLocalizationPaths()
Returns a list of engine-specific localization paths.
UFUNCTION () static 1 const TArray< FString > &GetGameLocalizationPaths()
Returns a list of game-specific localization paths.
UFUNCTION () static 1 const TArray< FString > &GetPropertyNameLocalizationPaths()
Returns a list of property name localization paths.
UFUNCTION () static 1 const TArray< FString > &GetRestrictedFolderNames()
Returns a list of restricted/internal folder names (without any slashes) which may be tested against full paths to determine if a path is restricted or not.
UFUNCTION () static 1 const TArray< FString > &GetToolTipLocalizationPaths()
Returns a list of tool tip localization paths.
UFUNCTION () static 1 FString AutomationDir()
Returns the directory for automation save files.
UFUNCTION () static 1 FString AutomationLogDir()
Returns the directory for automation log files.
UFUNCTION () static 1 FString AutomationTransientDir()
Returns the directory for automation save files that are meant to be deleted every run.
UFUNCTION () static 1 FString BugItDir()
Returns the directory the engine uses to output BugIt files.
UFUNCTION () static 1 FString ChangeExtension(const FString &InPath
Changes the extension of the given filename (does nothing if the file has no extension)
UFUNCTION () static 1 FString CloudDir()
Returns the directory for local files used in cloud emulation or support.
UFUNCTION () static 1 FString Combine(const TArray< FString > &InPaths)
Combine two or more Paths into one single Path.
UFUNCTION () static 1 FString ConvertFromSandboxPath(const FString &InPath
Converts a sandbox (in Saved/Sandboxes) path to a normal path.
UFUNCTION () static 1 FString ConvertRelativePathToFull(const FString &InPath
Converts a relative path name to a fully qualified name relative to the specified BasePath.
UFUNCTION () static 1 FString ConvertToSandboxPath(const FString &InPath
Converts a normal path to a sandbox path (in Saved/Sandboxes).
UFUNCTION () static 1 FString CreateTempFilename(const FString &Path
Creates a temporary filename with the specified prefix.
UFUNCTION () static 1 FString DiffDir()
Returns the directory for temp files used for diffing.
UFUNCTION () static 1 FString EngineConfigDir()
Returns the directory the root configuration files are located.
UFUNCTION () static 1 FString EngineContentDir()
Returns the content directory of the "core" engine that can be shared across several games or across games & mods.
UFUNCTION () static 1 FString EngineDir()
Returns the base directory of the "core" engine that can be shared across several games or across games & mods.
UFUNCTION () static 1 FString EngineIntermediateDir()
Returns the intermediate directory of the engine.
UFUNCTION () static 1 FString EnginePluginsDir()
Returns the plugins directory of the engine.
UFUNCTION () static 1 FString EngineSavedDir()
Returns the saved directory of the engine.
UFUNCTION () static 1 FString EngineSourceDir()
Returns the directory where engine source code files are kept.
UFUNCTION () static 1 FString EngineUserDir()
Returns the root directory for user-specific engine files.
UFUNCTION () static 1 FString EngineVersionAgnosticUserDir()
Returns the root directory for user-specific engine files which can be shared between versions.
UFUNCTION () static 1 FString EnterpriseDir()
Returns the base directory enterprise directory.
UFUNCTION () static 1 FString EnterpriseFeaturePackDir()
Returns the enterprise FeaturePack directory.
UFUNCTION () static 1 FString EnterprisePluginsDir()
Returns the enterprise plugins directory.
UFUNCTION () static 1 FString FeaturePackDir()
Returns the directory where feature packs are kept.
UFUNCTION () static 1 FString GameAgnosticSavedDir()
Returns the saved directory that is not game specific.
UFUNCTION () static 1 FString GameDevelopersDir()
Returns the directory that contains subfolders for developer-specific content.
UFUNCTION () static 1 FString GameSourceDir()
Returns the directory where game source code files are kept.
UFUNCTION () static 1 FString GameUserDeveloperDir()
Returns the directory that contains developer-specific content for the current user.
UFUNCTION () static 1 FString GeneratedConfigDir()
Returns the directory the engine saves generated config files.
UFUNCTION () static 1 FString GetBaseFilename(const FString &InPath
UFUNCTION () static 1 FString GetCleanFilename(const FString &InPath)
UFUNCTION () static 1 FString GetExtension(const FString &InPath
Gets the extension for this filename.
UFUNCTION () static 1 FString GetInvalidFileSystemChars()
Returns a string containing all invalid characters as dictated by the operating system.
UFUNCTION () static 1 FString GetPath(const FString &InPath)
UFUNCTION () static 1 FString GetProjectFilePath()
Gets the path to the project file.
UFUNCTION () static 1 FString LaunchDir()
Returns the directory the application was launched from (useful for commandline utilities)
UFUNCTION () static 1 FString MakeValidFileName(const FString &InString
Returns a string that is safe to use as a filename because all items in GetInvalidFileSystemChars() are removed.
UFUNCTION () static 1 FString ProfilingDir()
Returns the directory the engine uses to output profiling files.
UFUNCTION () static 1 FString ProjectConfigDir()
Returns the directory the root configuration files are located.
UFUNCTION () static 1 FString ProjectContentDir()
Returns the content directory of the current game by looking at FApp::GetProjectName().
UFUNCTION () static 1 FString ProjectDir()
Returns the base directory of the current project by looking at FApp::GetProjectName().
UFUNCTION () static 1 FString ProjectIntermediateDir()
Returns the intermediate directory of the current game by looking at FApp::GetProjectName().
UFUNCTION () static 1 FString ProjectLogDir()
Returns the directory the engine uses to output logs.
UFUNCTION () static 1 FString ProjectModsDir()
Returns the mods directory of the current project by looking at FApp::GetProjectName().
UFUNCTION () static 1 FString ProjectPersistentDownloadDir()
UFUNCTION () static 1 FString ProjectPluginsDir()
Returns the plugins directory of the current game by looking at FApp::GetProjectName().
UFUNCTION () static 1 FString ProjectSavedDir()
Returns the saved directory of the current game by looking at FApp::GetProjectName().
UFUNCTION () static 1 FString ProjectUserDir()
Returns the root directory for user-specific game files.
UFUNCTION () static 1 FString RootDir()
Returns the root directory of the engine directory tree.
UFUNCTION () static 1 FString SandboxesDir()
Returns the directory the engine stores sandbox output.
UFUNCTION () static 1 FString ScreenShotDir()
Returns the directory the engine uses to output screenshot files.
UFUNCTION () static 1 FString SetExtension(const FString &InPath
Sets the extension of the given filename (like ChangeExtension, but also applies the extension if the file doesn't have one)
UFUNCTION () static 1 FString ShaderWorkingDir()
Returns the Shader Working Directory.
UFUNCTION () static 1 FString SourceConfigDir()
Returns the directory the engine uses to look for the source leaf ini files.
UFUNCTION () static 1 FString VideoCaptureDir()
Returns the directory the engine uses to output user requested video capture files.
UFUNCTION () static 1 void MakePlatformFilename(const FString &InPath
Takes an "Unreal" pathname and converts it to a platform filename.
UFUNCTION () static 1 void MakeStandardFilename(const FString &InPath
Make fully standard "Unreal" pathname:
UFUNCTION () static 1 void NormalizeDirectoryName(const FString &InPath
Normalize all / and \ to TEXT("/") and remove any trailing TEXT("/") if the character before that is not a TEXT("/") or a colon.
UFUNCTION () static 1 void NormalizeFilename(const FString &InPath
Convert all / and \ to TEXT("/")
UFUNCTION () static 1 void RemoveDuplicateSlashes(const FString &InPath
Removes duplicate slashes in paths.
UFUNCTION () static 1 void SetProjectFilePath(const FString &NewGameProjectFilePath)
Sets the path to the project file.
UFUNCTION () static 1 void Split(const FString &InPath
Parses a fully qualified or relative filename into its components (filename, path, extension).
UFUNCTION () static 1 void ValidatePath(const FString &InPath
Validates that the parts that make up the path contain no invalid characters as dictated by the operating system Note that this is a different set of restrictions to those imposed by FPackageName.
Private Attributes
bool & bDidSucceed
bool bIncludeDot = false)
bool bRemovePath = true)
const FString const FString & Extension = TEXT(".tmp"))
FString FString FString & ExtensionPart
FString FString & FilenamePart
const FString & InBasePath = TEXT(""))
const FString & InNewExtension
const FString & InRelativeTo
const FString & InReplacementChar = TEXT(""))
const FString & InSandboxName
FString & OutPath
const FString FString & OutPath
bool FText & OutReason
const FString & PathB
FString & PathPart
const FString & Prefix = TEXT("")
Detailed Description
Definition at line 17 of file BlueprintPathsLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UBlueprintPathsLibrary::GENERATED_UCLASS_BODY () private
Should the "saved" directory structures be rooted in the user dir or relative to the "engine/game".
References Category, and UFUNCTION().
UFUNCTION() [1/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Takes a fully pathed string and eliminates relative pathing (eg: annihilates ".." with the adjacent directory).
Assumes all slashes have been converted to TEXT('/'). For example, takes the string: BaseDirectory/SomeDirectory/../SomeOtherDirectory/Filename.ext and converts it to: BaseDirectory/SomeOtherDirectory/Filename.ext
References Category, OutPath, and UFUNCTION().
UFUNCTION() [2/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns true if this directory was found, false otherwise.
References Category, and UFUNCTION().
UFUNCTION() [3/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns true if this file was found, false otherwise.
References Category, and UFUNCTION().
UFUNCTION() [4/81]
UBlueprintPathsLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns true if this path represents a root drive or volume.
References Category, and UFUNCTION().
UFUNCTION() [6/81]
UBlueprintPathsLibrary::UFUNCTION () private
Checks whether the path to the project file, if any, is set.
Returns
true if the path is set, false otherwise.
References Category, and UFUNCTION().
UFUNCTION() [7/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns true if this path is relative to another path.
References Category, and UFUNCTION().
UFUNCTION() [8/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Determines if supplied path uses a restricted/internal subdirectory.
Note that slashes are normalized and character case is ignored for the comparison.
References Category, and UFUNCTION().
UFUNCTION() [9/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Checks if two paths are the same.
Parameters
PathA First path to check.
PathB Second path to check.
Returns
True if both paths are the same. False otherwise.
References Category, and UFUNCTION().
UFUNCTION() [10/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Assuming both paths (or filenames) are relative to the same base dir, converts InPath to be relative to InRelativeTo.
Parameters
InPath Path to change to be relative to InRelativeTo
InRelativeTo Path to use as the new relative base
InPath New path relative to InRelativeTo
Returns
true if OutPath was changed to be relative
References Category, and UFUNCTION().
UFUNCTION() [11/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Gets the relative path to get from BaseDir to RootDirectory.
References Category, and UFUNCTION().
UFUNCTION() [12/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a list of editor-specific localization paths.
References Category, and UFUNCTION().
UFUNCTION() [13/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a list of engine-specific localization paths.
References Category, and UFUNCTION().
UFUNCTION() [14/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a list of game-specific localization paths.
References Category, and UFUNCTION().
UFUNCTION() [15/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a list of property name localization paths.
References Category, and UFUNCTION().
UFUNCTION() [16/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a list of restricted/internal folder names (without any slashes) which may be tested against full paths to determine if a path is restricted or not.
References Category, and UFUNCTION().
UFUNCTION() [17/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a list of tool tip localization paths.
References Category, and UFUNCTION().
UFUNCTION() [18/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory for automation save files.
References Category, and UFUNCTION().
UFUNCTION() [19/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory for automation log files.
References Category, and UFUNCTION().
UFUNCTION() [20/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory for automation save files that are meant to be deleted every run.
References Category, and UFUNCTION().
UFUNCTION() [21/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine uses to output BugIt files.
Returns
screenshot directory
References Category, and UFUNCTION().
UFUNCTION() [22/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Changes the extension of the given filename (does nothing if the file has no extension)
References Category, and UFUNCTION().
UFUNCTION() [23/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory for local files used in cloud emulation or support.
References Category, and UFUNCTION().
UFUNCTION() [24/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Combine two or more Paths into one single Path.
References Category, and UFUNCTION().
UFUNCTION() [25/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Converts a sandbox (in Saved/Sandboxes) path to a normal path.
Parameters
InSandboxName The name of the sandbox.
References Category, InSandboxName, and UFUNCTION().
UFUNCTION() [26/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Converts a relative path name to a fully qualified name relative to the specified BasePath.
BasePath will be the process BaseDir() if not BasePath is given
References Category, and UFUNCTION().
UFUNCTION() [27/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Converts a normal path to a sandbox path (in Saved/Sandboxes).
Parameters
InSandboxName The name of the sandbox.
References Category, and UFUNCTION().
UFUNCTION() [28/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Creates a temporary filename with the specified prefix.
Parameters
Path The file pathname.
Prefix The file prefix.
Extension File extension ('.' required).
References Category, and UFUNCTION().
UFUNCTION() [29/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory for temp files used for diffing.
References Category, and UFUNCTION().
UFUNCTION() [30/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the root configuration files are located.
Returns
root config directory
References Category, and UFUNCTION().
UFUNCTION() [31/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the content directory of the "core" engine that can be shared across several games or across games & mods.
Returns
engine content directory
References Category, and UFUNCTION().
UFUNCTION() [32/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the base directory of the "core" engine that can be shared across several games or across games & mods.
Shaders and base localization files e.g. reside in the engine directory.
Returns
engine directory
References Category, and UFUNCTION().
UFUNCTION() [33/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the intermediate directory of the engine.
Returns
content directory
References Category, and UFUNCTION().
UFUNCTION() [34/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the plugins directory of the engine.
Returns
Plugins directory.
References Category, and UFUNCTION().
UFUNCTION() [35/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the saved directory of the engine.
Returns
Saved directory.
References Category, and UFUNCTION().
UFUNCTION() [36/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory where engine source code files are kept.
References Category, and UFUNCTION().
UFUNCTION() [37/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the root directory for user-specific engine files.
Always writable.
Returns
root user directory
References Category, and UFUNCTION().
UFUNCTION() [38/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the root directory for user-specific engine files which can be shared between versions.
Always writable.
Returns
root user directory
References Category, and UFUNCTION().
UFUNCTION() [39/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the base directory enterprise directory.
Returns
enterprise directory
References Category, and UFUNCTION().
UFUNCTION() [40/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the enterprise FeaturePack directory.
Returns
FeaturePack directory.
References Category, and UFUNCTION().
UFUNCTION() [41/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the enterprise plugins directory.
Returns
Plugins directory.
References Category, and UFUNCTION().
UFUNCTION() [42/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory where feature packs are kept.
References Category, and UFUNCTION().
UFUNCTION() [43/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the saved directory that is not game specific.
This is usually the same as EngineSavedDir().
Returns
saved directory
References Category, and UFUNCTION().
UFUNCTION() [44/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory that contains subfolders for developer-specific content.
References Category, and UFUNCTION().
UFUNCTION() [45/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory where game source code files are kept.
References Category, and UFUNCTION().
UFUNCTION() [46/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory that contains developer-specific content for the current user.
References Category, and UFUNCTION().
UFUNCTION() [47/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine saves generated config files.
Returns
config directory
References Category, and UFUNCTION().
UFUNCTION() [48/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
References Category, and UFUNCTION().
UFUNCTION() [49/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
References Category, and UFUNCTION().
UFUNCTION() [50/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Gets the extension for this filename.
Parameters
bIncludeDot if true, includes the leading dot in the result
Returns
the extension of this filename, or an empty string if the filename doesn't have an extension.
References Category, and UFUNCTION().
UFUNCTION() [51/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns a string containing all invalid characters as dictated by the operating system.
References Category, and UFUNCTION().
UFUNCTION() [52/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
References Category, and UFUNCTION().
UFUNCTION() [53/81]
UBlueprintPathsLibrary::UFUNCTION () private
Gets the path to the project file.
Returns
Project file path.
References Category, and UFUNCTION().
UFUNCTION() [54/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the application was launched from (useful for commandline utilities)
References Category, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [55/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Returns a string that is safe to use as a filename because all items in GetInvalidFileSystemChars() are removed.
Optionally specify the character to replace invalid characters with
Parameters
InString
InReplacementChar
References Category, and UFUNCTION().
UFUNCTION() [56/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine uses to output profiling files.
Returns
log directory
References Category, and UFUNCTION().
UFUNCTION() [57/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the root configuration files are located.
Returns
root config directory
References Category, and UFUNCTION().
UFUNCTION() [58/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the content directory of the current game by looking at FApp::GetProjectName().
Returns
content directory
References Category, and UFUNCTION().
UFUNCTION() [59/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the base directory of the current project by looking at FApp::GetProjectName().
This is usually a subdirectory of the installation root directory and can be overridden on the command line to allow self contained mod support.
Returns
base directory
References Category, and UFUNCTION().
UFUNCTION() [60/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the intermediate directory of the current game by looking at FApp::GetProjectName().
Returns
intermediate directory
References Category, and UFUNCTION().
UFUNCTION() [61/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine uses to output logs.
This currently can't be an .ini setting as the game starts logging before it can read from .ini files.
Returns
log directory
References Category, and UFUNCTION().
UFUNCTION() [62/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the mods directory of the current project by looking at FApp::GetProjectName().
Returns
mods directory
References Category, and UFUNCTION().
UFUNCTION() [63/81]
UBlueprintPathsLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [64/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the plugins directory of the current game by looking at FApp::GetProjectName().
Returns
plugins directory
References Category, and UFUNCTION().
UFUNCTION() [65/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the saved directory of the current game by looking at FApp::GetProjectName().
Returns
saved directory
References Category, and UFUNCTION().
UFUNCTION() [66/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the root directory for user-specific game files.
Returns
game user directory
References Category, and UFUNCTION().
UFUNCTION() [67/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the root directory of the engine directory tree.
Returns
Root directory.
References Category, and UFUNCTION().
UFUNCTION() [68/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine stores sandbox output.
Returns
sandbox directory
References Category, and UFUNCTION().
UFUNCTION() [69/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine uses to output screenshot files.
Returns
screenshot directory
References Category, and UFUNCTION().
UFUNCTION() [70/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Sets the extension of the given filename (like ChangeExtension, but also applies the extension if the file doesn't have one)
References Category, InNewExtension, and UFUNCTION().
UFUNCTION() [71/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the Shader Working Directory.
Returns
shader working directory
References Category, and UFUNCTION().
UFUNCTION() [72/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine uses to look for the source leaf ini files.
This can't be an .ini variable for obvious reasons.
Returns
source config directory
References Category, and UFUNCTION().
UFUNCTION() [73/81]
UBlueprintPathsLibrary::UFUNCTION () private
Returns the directory the engine uses to output user requested video capture files.
Returns
Video capture directory
References Category, and UFUNCTION().
UFUNCTION() [74/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Takes an "Unreal" pathname and converts it to a platform filename.
References Category, OutPath, and UFUNCTION().
UFUNCTION() [75/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Make fully standard "Unreal" pathname:
Normalizes path separators [NormalizeFilename]
Removes extraneous separators [NormalizeDirectoryName, as well removing adjacent separators]
Collapses internal ..'s
Makes relative to Engine\Binaries<Platform> (will ALWAYS start with ......)
References Category, OutPath, and UFUNCTION().
UFUNCTION() [76/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Normalize all / and \ to TEXT("/") and remove any trailing TEXT("/") if the character before that is not a TEXT("/") or a colon.
References Category, OutPath, and UFUNCTION().
UFUNCTION() [77/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Convert all / and \ to TEXT("/")
References Category, and UFUNCTION().
UFUNCTION() [78/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Removes duplicate slashes in paths.
Assumes all slashes have been converted to TEXT('/'). For example, takes the string: BaseDirectory/SomeDirectory//SomeOtherDirectory////Filename.ext and converts it to: BaseDirectory/SomeDirectory/SomeOtherDirectory/Filename.ext
References Category, OutPath, and UFUNCTION().
UFUNCTION() [79/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Sets the path to the project file.
Parameters
NewGameProjectFilePath - The project file path to set.
References Category, and UFUNCTION().
UFUNCTION() [80/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Parses a fully qualified or relative filename into its components (filename, path, extension).
Parameters
Path [out] receives the value of the path portion of the input string
Filename [out] receives the value of the filename portion of the input string
Extension [out] receives the value of the extension portion of the input string
References Category, and UFUNCTION().
UFUNCTION() [81/81]
UBlueprintPathsLibrary::UFUNCTION () const & private
Validates that the parts that make up the path contain no invalid characters as dictated by the operating system Note that this is a different set of restrictions to those imposed by FPackageName.
Parameters
InPath - path to validate
OutReason - If validation fails, this is filled with the failure reason
bDidSucceed - Whether the path could be validated
References Category, and UFUNCTION().
Field Documentation
bDidSucceed
bool& UBlueprintPathsLibrary::bDidSucceed private
Definition at line 572 of file BlueprintPathsLibrary.h.
bIncludeDot
bool UBlueprintPathsLibrary::bIncludeDot = false) private
Definition at line 409 of file BlueprintPathsLibrary.h.
bRemovePath
bool UBlueprintPathsLibrary::bRemovePath = true) private
Definition at line 417 of file BlueprintPathsLibrary.h.
Extension
const FString const FString& UBlueprintPathsLibrary::Extension = TEXT(".tmp")) private
Definition at line 545 of file BlueprintPathsLibrary.h.
ExtensionPart
FString FString FString& UBlueprintPathsLibrary::ExtensionPart private
Definition at line 582 of file BlueprintPathsLibrary.h.
FilenamePart
FString FString& UBlueprintPathsLibrary::FilenamePart private
Definition at line 582 of file BlueprintPathsLibrary.h.
InBasePath
const FString& UBlueprintPathsLibrary::InBasePath = TEXT("")) private
Definition at line 519 of file BlueprintPathsLibrary.h.
InNewExtension
const FString & UBlueprintPathsLibrary::InNewExtension private
Definition at line 425 of file BlueprintPathsLibrary.h.
Referenced by UFUNCTION().
InRelativeTo
const FString& UBlueprintPathsLibrary::InRelativeTo private
Definition at line 512 of file BlueprintPathsLibrary.h.
InReplacementChar
const FString& UBlueprintPathsLibrary::InReplacementChar = TEXT("")) private
Definition at line 561 of file BlueprintPathsLibrary.h.
InSandboxName
const FString & UBlueprintPathsLibrary::InSandboxName private
Definition at line 527 of file BlueprintPathsLibrary.h.
Referenced by UFUNCTION().
OutPath [1/2]
FString & UBlueprintPathsLibrary::OutPath private
Definition at line 449 of file BlueprintPathsLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
OutPath [2/2]
const FString FString& UBlueprintPathsLibrary::OutPath private
Definition at line 512 of file BlueprintPathsLibrary.h.
OutReason
bool FText& UBlueprintPathsLibrary::OutReason private
Definition at line 572 of file BlueprintPathsLibrary.h.
PathB
const FString& UBlueprintPathsLibrary::PathB private
Definition at line 460 of file BlueprintPathsLibrary.h.
PathPart
FString& UBlueprintPathsLibrary::PathPart private
Definition at line 582 of file BlueprintPathsLibrary.h.
Prefix
const FString& UBlueprintPathsLibrary::Prefix = TEXT("") private
Definition at line 545 of file BlueprintPathsLibrary.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/BlueprintPathsLibrary.h