Unreal Engine 5.6 C++ API: UBTDecorator_Blackboard Class Reference
UBTDecorator_Blackboard Class Reference
#include "BTDecorator_Blackboard.h"
Public Member Functions
virtual AIMODULE_API void BuildDescription ()
when observer can try to request abort?
Protected Member Functions
AIMODULE_API bool EvaluateOnBlackboard (const UBlackboardComponent &BlackboardComp) const
take blackboard value and evaluate decorator's condition
virtual AIMODULE_API void InitializeFromAsset (UBehaviorTree &Asset) override
virtual AIMODULE_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
AIMODULE_API void RefreshEnumBasedDecorator (const FBlackboardEntry &Entry)
decorator using enum based key requires to synchronize 'StringValue' used for storage with 'IntValue' used for runtime evaluation.
UPROPERTY () FString CachedDescription
cached description
UPROPERTY () uint8 OperationType
operation type
UPROPERTY ()) float FloatValue
value for arithmetic operations
UPROPERTY ()) FString StringValue
value for string operations
UPROPERTY ()) int32 IntValue
value for arithmetic operations
Protected Attributes
friend FBlackboardDecoratorDetails
Private Member Functions
virtual AIMODULE_API void DescribeRuntimeValues (const UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > &Values) const override
GENERATED_UCLASS_BODY () AIMODULE_API virtual bool CalculateRawConditionValue(UBehaviorTreeComponent &OwnerComp
virtual AIMODULE_API FString GetStaticDescription () const override
virtual AIMODULE_API EBlackboardNotificationResult OnBlackboardKeyValueChange (const UBlackboardComponent &Blackboard, FBlackboard::FKey ChangedKeyID) override
Private Attributes
uint8 *NodeMemory const override
Detailed Description
Definition at line 36 of file BTDecorator_Blackboard.h.
Member Function Documentation
BuildDescription()
virtual AIMODULE_API void UBTDecorator_Blackboard::BuildDescription () virtual
when observer can try to request abort?
describe decorator and cache it
DescribeRuntimeValues()
virtual AIMODULE_API void UBTDecorator_Blackboard::DescribeRuntimeValues (const UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > & Values) const override private virtual
References DescribeRuntimeValues(), and override.
Referenced by DescribeRuntimeValues().
EvaluateOnBlackboard()
AIMODULE_API bool UBTDecorator_Blackboard::EvaluateOnBlackboard (const UBlackboardComponent & BlackboardComp) const protected
take blackboard value and evaluate decorator's condition
GENERATED_UCLASS_BODY()
UBTDecorator_Blackboard::GENERATED_UCLASS_BODY () & private
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_Blackboard::GetStaticDescription () const override private virtual
References GetStaticDescription(), and override.
Referenced by GetStaticDescription().
InitializeFromAsset()
virtual AIMODULE_API void UBTDecorator_Blackboard::InitializeFromAsset (UBehaviorTree & Asset) override protected virtual
References Asset.
OnBlackboardKeyValueChange()
virtual AIMODULE_API EBlackboardNotificationResult UBTDecorator_Blackboard::OnBlackboardKeyValueChange (const UBlackboardComponent & Blackboard, FBlackboard::FKey ChangedKeyID) override private virtual
Reimplemented in UBTDecorator_ConditionalLoop.
References OnBlackboardKeyValueChange(), and override.
Referenced by OnBlackboardKeyValueChange().
PostEditChangeProperty()
virtual AIMODULE_API void UBTDecorator_Blackboard::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
RefreshEnumBasedDecorator()
AIMODULE_API void UBTDecorator_Blackboard::RefreshEnumBasedDecorator (const FBlackboardEntry & Entry) protected
decorator using enum based key requires to synchronize 'StringValue' used for storage with 'IntValue' used for runtime evaluation.
Note
using custom serialization version was not possible since we require blackboard and used types (e.g. UserDefinedEnumerations) to be loaded and keys to be resolved (i.e. InitializeFromAsset).
UPROPERTY() [1/5]
UBTDecorator_Blackboard::UPROPERTY () protected
cached description
References UPROPERTY().
UPROPERTY() [2/5]
UBTDecorator_Blackboard::UPROPERTY () protected
operation type
References Category, meta, and UPROPERTY().
UPROPERTY() [3/5]
UBTDecorator_Blackboard::UPROPERTY () protected
value for arithmetic operations
References Category, meta, and UPROPERTY().
UPROPERTY() [4/5]
UBTDecorator_Blackboard::UPROPERTY () protected
value for string operations
References Category, meta, and UPROPERTY().
UPROPERTY() [5/5]
UBTDecorator_Blackboard::UPROPERTY () protected
value for arithmetic operations
References Category, meta, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Field Documentation
FBlackboardDecoratorDetails
friend UBTDecorator_Blackboard::FBlackboardDecoratorDetails protected
Definition at line 104 of file BTDecorator_Blackboard.h.
override
uint8* NodeMemory const UBTDecorator_Blackboard::override private
Definition at line 40 of file BTDecorator_Blackboard.h.
Referenced by DescribeRuntimeValues(), GetStaticDescription(), and OnBlackboardKeyValueChange().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/BehaviorTree/Decorators/BTDecorator_Blackboard.h