Unreal Engine 5.6 C++ API: FSlateShaderResourceManager Class Reference
FSlateShaderResourceManager Class Reference abstract
Base texture manager class used by a Slate renderer to manage texture resources.
#include "ShaderResourceManager.h"
Public Member Functions
FSlateShaderResourceManager ()
virtual ~FSlateShaderResourceManager ()
virtual FSlateShaderResource * GetFontShaderResource (int32 InTextureAtlasIndex, FSlateShaderResource *FontTextureAtlas, const class UObject *FontMaterial)
virtual FSlateResourceHandle GetResourceHandle (const FSlateBrush &Brush)
virtual FSlateResourceHandle GetResourceHandle (const FSlateBrush &Brush, FVector2f LocalSize, float DrawScale)
Creates a handle to a Slate resource A handle is used as fast path for looking up a rendering resource for a given brush when adding Slate draw elements This can be cached and stored safely in code.
virtual FSlateShaderResourceProxy * GetShaderResource (const FSlateBrush &Brush, FVector2f LocalSize, float DrawScale)=0
Returns a texture associated with the passed in name.
virtual ISlateAtlasProvider * GetTextureAtlasProvider ()=0
Returns the way to access the texture atlas information from this resource manager.
Protected Member Functions
void ClearTextureMap ()
FString GetResourcePath (const FSlateBrush &InBrush) const
Protected Attributes
TMap< FName, FSlateShaderResourceProxy * > ResourceMap
Mapping of names to texture pointers.
Private Member Functions
FSlateShaderResourceManager (const FSlateShaderResourceManager &)
FSlateShaderResourceManager & operator= (const FSlateShaderResourceManager &)
Detailed Description
Base texture manager class used by a Slate renderer to manage texture resources.
Definition at line 43 of file ShaderResourceManager.h.
Constructor & Destructor Documentation
FSlateShaderResourceManager() [1/2]
FSlateShaderResourceManager::FSlateShaderResourceManager ()
Referenced by FSlateShaderResourceManager(), and operator=().
~FSlateShaderResourceManager()
virtual FSlateShaderResourceManager::~FSlateShaderResourceManager () virtual
FSlateShaderResourceManager() [2/2]
FSlateShaderResourceManager::FSlateShaderResourceManager (const FSlateShaderResourceManager &) private
References FSlateShaderResourceManager().
Member Function Documentation
ClearTextureMap()
void FSlateShaderResourceManager::ClearTextureMap () inline protected
Definition at line 77 of file ShaderResourceManager.h.
References ResourceMap.
GetFontShaderResource()
virtual FSlateShaderResource * FSlateShaderResourceManager::GetFontShaderResource (int32 InTextureAtlasIndex, FSlateShaderResource * FontTextureAtlas, const class UObject * FontMaterial) inline virtual
Definition at line 68 of file ShaderResourceManager.h.
GetResourceHandle() [1/2]
virtual FSlateResourceHandle FSlateShaderResourceManager::GetResourceHandle (const FSlateBrush & Brush) virtual
GetResourceHandle() [2/2]
virtual FSlateResourceHandle FSlateShaderResourceManager::GetResourceHandle (const FSlateBrush & Brush, FVector2f LocalSize, float DrawScale) virtual
Creates a handle to a Slate resource A handle is used as fast path for looking up a rendering resource for a given brush when adding Slate draw elements This can be cached and stored safely in code.
It will become invalid when a resource is destroyed It is expensive to create a resource so do not do it in time sensitive areas
Parameters
Brush The brush to get a rendering resource handle
LocalSize The unscaled size of the draw element using this brush. This size is used to rescale vector graphics only
DrawScale The scale of the draw element using this brush. This scale is used to rescale vector graphics only
Returns
The created resource handle.
GetResourcePath()
FString FSlateShaderResourceManager::GetResourcePath (const FSlateBrush & InBrush) const inline protected
Definition at line 90 of file ShaderResourceManager.h.
GetShaderResource()
virtual FSlateShaderResourceProxy * FSlateShaderResourceManager::GetShaderResource (const FSlateBrush & Brush, FVector2f LocalSize, float DrawScale) pure virtual
Returns a texture associated with the passed in name.
Should return nullptr if not found
GetTextureAtlasProvider()
virtual ISlateAtlasProvider * FSlateShaderResourceManager::GetTextureAtlasProvider () pure virtual
Returns the way to access the texture atlas information from this resource manager.
operator=()
FSlateShaderResourceManager & FSlateShaderResourceManager::operator= (const FSlateShaderResourceManager &) private
References FSlateShaderResourceManager().
Field Documentation
ResourceMap
TMap<FName,FSlateShaderResourceProxy*> FSlateShaderResourceManager::ResourceMap protected
Mapping of names to texture pointers.
Definition at line 97 of file ShaderResourceManager.h.
Referenced by ClearTextureMap().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Rendering/ShaderResourceManager.h