Unreal Engine 5.6 C++ API: FStarshipCoreStyle Class Reference
FStarshipCoreStyle Class Reference
Core slate style.
#include "StarshipCoreStyle.h"
Static Public Member Functions
static TSharedRef< class ISlateStyle > Create ()
static const ISlateStyle & Get ()
static const ISlateStyle & GetCoreStyle ()
static TSharedRef< const FCompositeFont > GetDefaultFont ()
Get the default font for Slate.
static FSlateFontInfo GetDefaultFontStyle (const FName InTypefaceFontName, const float InSize, const FFontOutlineSettings &InOutlineSettings=FFontOutlineSettings())
Get a font style using the default for for Slate.
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, class UTexture2D *TextureResource, FName TextureName)
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, const ANSICHAR *Specifier, class UTexture2D *TextureResource, FName TextureName)
static const TSharedPtr< FSlateDynamicImageBrush > GetDynamicImageBrush (FName BrushTemplate, FName TextureName, const ANSICHAR *Specifier=nullptr)
static bool IsInitialized ()
static void ResetToDefault ()
static void SetFocusBrush (FSlateBrush *NewBrush)
static void SetInactiveSelectionColor (const FLinearColor &NewColor)
static void SetPressedSelectionColor (const FLinearColor &NewColor)
static void SetSelectionColor (const FLinearColor &NewColor)
static void SetSelectorColor (const FLinearColor &NewColor)
Used to override the default selection colors.
Static Public Attributes
static const int32 RegularTextSize = 10
static const int32 SmallTextSize = 8
Static Private Member Functions
static void SetStyle (const TSharedRef< class ISlateStyle > &NewStyle)
static void SetupButtonStyles (TSharedRef< FStyle > &Style)
static void SetupCheckboxStyles (TSharedRef< FStyle > &Style)
static void SetupColorPickerStyles (TSharedRef< FStyle > &Style)
static void SetupColors (TSharedRef< FStyle > &Style)
static void SetupComboButtonStyles (TSharedRef< FStyle > &Style)
static void SetupDockingStyles (TSharedRef< FStyle > &Style)
static void SetupMultiboxStyles (TSharedRef< FStyle > &Style)
static void SetupTableViewStyles (TSharedRef< FStyle > &Style)
static void SetupTextStyles (TSharedRef< FStyle > &Style)
Static Private Attributes
static TSharedPtr< class ISlateStyle > Instance
Singleton instances of this style.
Detailed Description
Core slate style.
Definition at line 14 of file StarshipCoreStyle.h.
Member Function Documentation
Create()
TSharedRef< class ISlateStyle > FStarshipCoreStyle::Create () static
Get()
const ISlateStyle & FStarshipCoreStyle::Get () inline static
Returns
the Application Style
NOTE: Until the Editor can be fully updated, calling FStarshipCoreStyle::Get() will return the AppStyle instead of the style defined in this class.
Using the AppStyle is preferred in most cases as it allows the style to be changed and restyled more easily.
In cases requiring explicit use of the CoreStyle where a Slate Widget should not take on the appearance of the rest of the application, use FStarshipCoreStyle::GetCoreStyle().
Definition at line 33 of file StarshipCoreStyle.h.
References FAppStyle::Get().
GetCoreStyle()
const ISlateStyle & FStarshipCoreStyle::GetCoreStyle () inline static
Returns
the singleton instance of the style created in .
Definition at line 39 of file StarshipCoreStyle.h.
References Instance.
Referenced by SFacesOutlinerRow::Construct(), STransformOutlinerRow::Construct(), and SVerticesOutlinerRow::Construct().
GetDefaultFont()
TSharedRef< const FCompositeFont > FStarshipCoreStyle::GetDefaultFont () static
Get the default font for Slate.
GetDefaultFontStyle()
FSlateFontInfo FStarshipCoreStyle::GetDefaultFontStyle (const FName InTypefaceFontName, const float InSize, const FFontOutlineSettings & InOutlineSettings = FFontOutlineSettings()) static
Get a font style using the default for for Slate.
GetDynamicImageBrush() [1/3]
const TSharedPtr< FSlateDynamicImageBrush > FStarshipCoreStyle::GetDynamicImageBrush (FName BrushTemplate, class UTexture2D * TextureResource, FName TextureName) static
GetDynamicImageBrush() [2/3]
const TSharedPtr< FSlateDynamicImageBrush > FStarshipCoreStyle::GetDynamicImageBrush (FName BrushTemplate, const ANSICHAR * Specifier, class UTexture2D * TextureResource, FName TextureName) static
GetDynamicImageBrush() [3/3]
const TSharedPtr< FSlateDynamicImageBrush > FStarshipCoreStyle::GetDynamicImageBrush (FName BrushTemplate, FName TextureName, const ANSICHAR * Specifier = nullptr) static
IsInitialized()
bool FStarshipCoreStyle::IsInitialized () inline static
Definition at line 67 of file StarshipCoreStyle.h.
References Instance.
ResetToDefault()
void FStarshipCoreStyle::ResetToDefault () static
SetFocusBrush()
void FStarshipCoreStyle::SetFocusBrush (FSlateBrush * NewBrush) static
SetInactiveSelectionColor()
void FStarshipCoreStyle::SetInactiveSelectionColor (const FLinearColor & NewColor) static
SetPressedSelectionColor()
void FStarshipCoreStyle::SetPressedSelectionColor (const FLinearColor & NewColor) static
SetSelectionColor()
void FStarshipCoreStyle::SetSelectionColor (const FLinearColor & NewColor) static
SetSelectorColor()
void FStarshipCoreStyle::SetSelectorColor (const FLinearColor & NewColor) static
Used to override the default selection colors.
SetStyle()
void FStarshipCoreStyle::SetStyle (const TSharedRef< class ISlateStyle > & NewStyle) static private
SetupButtonStyles()
void FStarshipCoreStyle::SetupButtonStyles (TSharedRef< FStyle > & Style) static private
SetupCheckboxStyles()
void FStarshipCoreStyle::SetupCheckboxStyles (TSharedRef< FStyle > & Style) static private
SetupColorPickerStyles()
void FStarshipCoreStyle::SetupColorPickerStyles (TSharedRef< FStyle > & Style) static private
SetupColors()
void FStarshipCoreStyle::SetupColors (TSharedRef< FStyle > & Style) static private
SetupComboButtonStyles()
void FStarshipCoreStyle::SetupComboButtonStyles (TSharedRef< FStyle > & Style) static private
SetupDockingStyles()
void FStarshipCoreStyle::SetupDockingStyles (TSharedRef< FStyle > & Style) static private
SetupMultiboxStyles()
void FStarshipCoreStyle::SetupMultiboxStyles (TSharedRef< FStyle > & Style) static private
SetupTableViewStyles()
void FStarshipCoreStyle::SetupTableViewStyles (TSharedRef< FStyle > & Style) static private
SetupTextStyles()
void FStarshipCoreStyle::SetupTextStyles (TSharedRef< FStyle > & Style) static private
Field Documentation
Instance
TSharedPtr< class ISlateStyle > FStarshipCoreStyle::Instance static private
Singleton instances of this style.
Definition at line 86 of file StarshipCoreStyle.h.
Referenced by GetCoreStyle(), and IsInitialized().
RegularTextSize
const int32 FStarshipCoreStyle::RegularTextSize = 10 static
Definition at line 64 of file StarshipCoreStyle.h.
SmallTextSize
const int32 FStarshipCoreStyle::SmallTextSize = 8 static
Definition at line 65 of file StarshipCoreStyle.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Styling/StarshipCoreStyle.h