Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension > Class Template Reference
UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension > Class Template Reference
#include "DynamicMeshTriangleAttribute.h"
Data Structures
struct FChangeTriangleAttribute
Public Member Functions
FDynamicMeshTriangleAttributeChange ()
virtual ~FDynamicMeshTriangleAttributeChange ()
virtual bool Apply (FDynamicMeshAttributeBase *Attribute, bool bRevert) const override
virtual void SaveInitialTriangle (const FDynamicMeshAttributeBase *Attribute, int TriangleID) override
virtual void StoreAllFinalTriangles (const FDynamicMeshAttributeBase *Attribute, const TArray< int > &TriangleIDs) override
Public Member Functions inherited from UE::Geometry::TDynamicAttributeChangeBase< FDynamicMesh3 >
virtual ~TDynamicAttributeChangeBase ()
virtual bool Apply (TDynamicAttributeBase< FDynamicMesh3 > *Attribute, bool bRevert) const
virtual void SaveInitialTriangle (const TDynamicAttributeBase< FDynamicMesh3 > *Attribute, int TriangleID)
virtual void SaveInitialVertex (const TDynamicAttributeBase< FDynamicMesh3 > *Attribute, int VertexID)
virtual void StoreAllFinalTriangles (const TDynamicAttributeBase< FDynamicMesh3 > *Attribute, const TArray< int > &TriangleIDs)
virtual void StoreAllFinalVertices (const TDynamicAttributeBase< FDynamicMesh3 > *Attribute, const TSet< int > &TriangleIDs)
UE_DEPRECATED (5.6, "Use the version of this method that takes a TSet instead") virtual void StoreAllFinalVertices(const TDynamicAttributeBase< FDynamicMesh3 > *Attribute
Private Attributes
TArray< FChangeTriangleAttribute > NewTriangleAttributes
TArray< FChangeTriangleAttribute > OldTriangleAttributes
Additional Inherited Members
Data Fields inherited from UE::Geometry::TDynamicAttributeChangeBase< FDynamicMesh3 >
const TArray< int > & TriangleIDs
Detailed Description
template<typename AttribValueType, int AttribDimension>
class UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >
Definition at line 18 of file DynamicMeshTriangleAttribute.h.
Constructor & Destructor Documentation
FDynamicMeshTriangleAttributeChange()
template<typename AttribValueType, int AttribDimension> UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::FDynamicMeshTriangleAttributeChange () inline
Definition at line 30 of file DynamicMeshTriangleAttribute.h.
~FDynamicMeshTriangleAttributeChange()
template<typename AttribValueType, int AttribDimension> virtual UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::~FDynamicMeshTriangleAttributeChange () inline virtual
Definition at line 33 of file DynamicMeshTriangleAttribute.h.
Member Function Documentation
Apply()
template<typename AttribValueType, int AttribDimension> bool UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::Apply (FDynamicMeshAttributeBase * Attribute, bool bRevert) const inline override virtual
Definition at line 580 of file DynamicMeshTriangleAttribute.h.
References Attribute, checkSlow, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetParentMesh(), UE::Geometry::FDynamicMesh3::IsTriangle(), NewTriangleAttributes, OldTriangleAttributes, and UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::SetValue().
SaveInitialTriangle()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::SaveInitialTriangle (const FDynamicMeshAttributeBase * Attribute, int TriangleID) inline override virtual
Definition at line 558 of file DynamicMeshTriangleAttribute.h.
References Attribute, UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::FChangeTriangleAttribute::Data, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetValue(), OldTriangleAttributes, and UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::FChangeTriangleAttribute::TriangleID.
StoreAllFinalTriangles()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::StoreAllFinalTriangles (const FDynamicMeshAttributeBase * Attribute, const TArray< int > & TriangleIDs) inline override virtual
Definition at line 567 of file DynamicMeshTriangleAttribute.h.
References Attribute, UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::FChangeTriangleAttribute::Data, UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetValue(), NewTriangleAttributes, UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::FChangeTriangleAttribute::TriangleID, and UE::Geometry::TDynamicAttributeChangeBase< FDynamicMesh3 >::TriangleIDs.
Field Documentation
NewTriangleAttributes
template<typename AttribValueType, int AttribDimension> TArray<FChangeTriangleAttribute> UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::NewTriangleAttributes private
Definition at line 27 of file DynamicMeshTriangleAttribute.h.
Referenced by Apply(), and StoreAllFinalTriangles().
OldTriangleAttributes
template<typename AttribValueType, int AttribDimension> TArray<FChangeTriangleAttribute> UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::OldTriangleAttributes private
Definition at line 27 of file DynamicMeshTriangleAttribute.h.
Referenced by Apply(), and SaveInitialTriangle().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/DynamicMeshTriangleAttribute.h