Unreal Engine 5.6 C++ API: UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits > Class Template Reference
UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits > Class Template Reference
A helper class for simple blender systems.
#include "MovieSceneBlenderSystemHelper.h"
Public Types
using FCombineResults = TSimpleBlenderCombineResults<PropertyType, ResultTraits>
using FGatherResults = TSimpleBlenderGatherResults<PropertyType, ResultTraits>
Public Member Functions
TSimpleBlenderSystemImpl ()
void Run (UMovieSceneEntitySystemLinker *Linker, TBitArray<> &AllocatedBlendChannels, FSystemTaskPrerequisites &InPrerequisites, FSystemSubsequentTasks &Subsequents)
Runs the blender system.
void Schedule (UMovieSceneEntitySystemLinker *Linker, TBitArray<> &AllocatedBlendChannels, IEntitySystemScheduler *TaskScheduler)
void Setup (UMovieSceneBlenderSystem *InBlenderSystem, TComponentTypeID< PropertyType > InResultComponentID, UClass *ChannelEvaluatorSystem=nullptr)
Sets up this helper class.
void ZeroAccumulationBuffers ()
Private Attributes
TArray< TSimpleBlendResult< PropertyType > > BlendChannelResults
UMovieSceneBlenderSystem * BlenderSystem
FCachedEntityManagerState ChannelRelevancyCache
TComponentTypeID< PropertyType > ResultComponentID
Detailed Description
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>>
class UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >
A helper class for simple blender systems.
This class implements a simple blender system that accumulates all contributors to a blend channel, and returns the blended value, as defined by the value type's traits class (above).
Definition at line 107 of file MovieSceneBlenderSystemHelper.h.
Member Typedef Documentation
FCombineResults
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> using UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::FCombineResults = TSimpleBlenderCombineResults<PropertyType, ResultTraits>
Definition at line 112 of file MovieSceneBlenderSystemHelper.h.
FGatherResults
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> using UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::FGatherResults = TSimpleBlenderGatherResults<PropertyType, ResultTraits>
Definition at line 111 of file MovieSceneBlenderSystemHelper.h.
Constructor & Destructor Documentation
TSimpleBlenderSystemImpl()
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::TSimpleBlenderSystemImpl () inline
Definition at line 114 of file MovieSceneBlenderSystemHelper.h.
References BlenderSystem.
Member Function Documentation
Run()
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> void UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run (UMovieSceneEntitySystemLinker * Linker, TBitArray<> & AllocatedBlendChannels, FSystemTaskPrerequisites & InPrerequisites, FSystemSubsequentTasks & Subsequents) inline
Runs the blender system.
Definition at line 191 of file MovieSceneBlenderSystemHelper.h.
References UE::MovieScene::FSystemTaskPrerequisites::AddRootTask(), UE::MovieScene::All, UE::MovieScene::FBuiltInComponentTypes::BlendChannelInput, UE::MovieScene::FBuiltInComponentTypes::BlendChannelOutput, BlendChannelResults, BlenderSystem, ChannelRelevancyCache, UE::MovieScene::TEntityTaskComponents< T >::FilterAll(), UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FBuiltInComponentTypes::Ignored, MakeArrayView(), TBitArray< Allocator >::Num(), ResultComponentID, UE::MovieScene::Stale, and UE::MovieScene::FBuiltInComponentTypes::Tags.
Schedule()
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> void UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule (UMovieSceneEntitySystemLinker * Linker, TBitArray<> & AllocatedBlendChannels, IEntitySystemScheduler * TaskScheduler) inline
Definition at line 136 of file MovieSceneBlenderSystemHelper.h.
References UE::MovieScene::IEntitySystemScheduler::AddMemberFunctionTask(), UE::MovieScene::IEntitySystemScheduler::AddPrerequisite(), UE::MovieScene::All, UE::MovieScene::FBuiltInComponentTypes::BlendChannelInput, UE::MovieScene::FBuiltInComponentTypes::BlendChannelOutput, BlendChannelResults, BlenderSystem, UE::MovieScene::TEntityTaskComponents< T >::FilterAll(), UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FBuiltInComponentTypes::Ignored, TBitArray< Allocator >::Num(), ResultComponentID, UE::MovieScene::FBuiltInComponentTypes::Tags, TEXT, and ZeroAccumulationBuffers().
Setup()
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> void UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Setup (UMovieSceneBlenderSystem * InBlenderSystem, TComponentTypeID< PropertyType > InResultComponentID, UClass * ChannelEvaluatorSystem = nullptr) inline
Sets up this helper class.
To be called in the owning blender system's constructor.
Parameters
InBlenderSystem The owning blender system
InResultComponentID The component type for the values to blend
ChannelEvaluationSystem The evaluation system for the value to blend. If set, the owner blender system will be automatically made a downstream dependency of it (optional)
Definition at line 125 of file MovieSceneBlenderSystemHelper.h.
References BlenderSystem, ResultComponentID, and RF_ClassDefaultObject.
ZeroAccumulationBuffers()
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> void UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::ZeroAccumulationBuffers () inline
Definition at line 249 of file MovieSceneBlenderSystemHelper.h.
References BlendChannelResults, and MakeArrayView().
Referenced by Schedule().
Field Documentation
BlendChannelResults
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> TArray<TSimpleBlendResult<PropertyType> > UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::BlendChannelResults private
Definition at line 261 of file MovieSceneBlenderSystemHelper.h.
Referenced by Run(), Schedule(), and ZeroAccumulationBuffers().
BlenderSystem
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> UMovieSceneBlenderSystem* UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::BlenderSystem private
Definition at line 256 of file MovieSceneBlenderSystemHelper.h.
Referenced by TSimpleBlenderSystemImpl(), Run(), Schedule(), and Setup().
ChannelRelevancyCache
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> FCachedEntityManagerState UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::ChannelRelevancyCache private
Definition at line 259 of file MovieSceneBlenderSystemHelper.h.
Referenced by Run().
ResultComponentID
template<typename PropertyType, typename ResultTraits = TSimpleBlendResultTraits<PropertyType>> TComponentTypeID<PropertyType> UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::ResultComponentID private
Definition at line 257 of file MovieSceneBlenderSystemHelper.h.
Referenced by Run(), Schedule(), and Setup().
The documentation for this class was generated from the following file:
Runtime/MovieSceneTracks/Public/Systems/MovieSceneBlenderSystemHelper.h