Unreal Engine 5.6 C++ API: TCommonReplicator_AP< ModelDef > Class Template Reference
TCommonReplicator_AP< ModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Static Public Member Functions
static void NetRecv (const FNetSerializeParams &P, TInstanceData< ModelDef > &InstanceData, TClientRecvData< ModelDef > &ClientRecvState)
static void NetSend (const FNetSerializeParams &P, TInstanceData< ModelDef > &InstanceData, typename TInstanceFrameState< ModelDef >::FFrame &FrameData)
Detailed Description
template<typename ModelDef>
class TCommonReplicator_AP< ModelDef >
Definition at line 357 of file NetworkPredictionSerialization.h.
Member Function Documentation
NetRecv()
template<typename ModelDef> void TCommonReplicator_AP< ModelDef >::NetRecv (const FNetSerializeParams & P, TInstanceData< ModelDef > & InstanceData, TClientRecvData< ModelDef > & ClientRecvState) inline static
Definition at line 361 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, TClientRecvData< ModelDef >::AuxState, TConditionalState< TestType, UnderlyingType >::Get(), FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, TClientRecvData< ModelDef >::Physics, FNetworkPredictionDriverBase< ModelDef >::PhysicsNetRecv(), TClientRecvData< ModelDef >::SyncState, UE_NP_TRACE_PHYSICS_STATE_RECV, UE_NP_TRACE_USER_STATE_AUX, and UE_NP_TRACE_USER_STATE_SYNC.
Referenced by TFixedTickReplicator_AP< InModelDef >::NetRecv(), and TIndependentTickReplicator_AP< InModelDef >::NetRecv().
NetSend()
template<typename ModelDef> void TCommonReplicator_AP< ModelDef >::NetSend (const FNetSerializeParams & P, TInstanceData< ModelDef > & InstanceData, typename TInstanceFrameState< ModelDef >::FFrame & FrameData) inline static
Definition at line 375 of file NetworkPredictionSerialization.h.
References FNetSerializeParams::Ar, TInstanceFrameState< ModelDef >::FFrame::AuxState, TInstanceData< ModelDef >::Info, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, FNetworkPredictionDriverBase< ModelDef >::PhysicsNetSend(), and TInstanceFrameState< ModelDef >::FFrame::SyncState.
Referenced by TFixedTickReplicator_AP< InModelDef >::NetSend(), and TIndependentTickReplicator_AP< InModelDef >::NetSend().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionSerialization.h