Unreal Engine 5.6 C++ API: UE::AnimNext::FDataRegistry Class Reference
UE::AnimNext::FDataRegistry Class Reference
#include "DataRegistry.h"
Data Structures
struct FDataTypeDef
struct FReferencePoseData
Public Member Functions
template<typename DataType, typename... ArgTypes>
FDataHandle AllocateData (const int32 NumElements, ArgTypes &&... Args)
ANIMNEXT_API FDataHandle GetOrGenerateReferencePose (USkeletalMeshComponent *SkeletalMeshComponent)
ANIMNEXT_API FDataHandle GetRegisteredData (const FName &Id) const
template<typename DataType>
FDataHandle PreAllocateMemory (const int32 NumElements)
ANIMNEXT_API void RegisterData (const FName &Id, const FDataHandle &AnimationDataHandle)
template<typename DataType>
void RegisterDataType (int32 AllocationBlockSize)
ANIMNEXT_API FDataHandle RegisterReferencePose (USkeletalMeshComponent *SkeletalMeshComponent)
ANIMNEXT_API void RemoveReferencePose (USkeletalMeshComponent *SkeletalMeshComponent)
ANIMNEXT_API void UnregisterData (const FName &Id)
Static Public Member Functions
static ANIMNEXT_API FDataRegistry * Get ()
Private Types
typedef void(* DestroyFnSignature) (uint8 *TargetBuffer, int32 NumElem)
Private Member Functions
ANIMNEXT_API void FreeAllocatedBlock (Private::FAllocatedBlock *AllocatedBlock)
ANIMNEXT_API void OnLODRequiredBonesUpdate (USkeletalMeshComponent *SkeletalMeshComponent, int32 LODLevel, const TArray< FBoneIndexType > &LODRequiredBones)
template<typename DataType>
FDataTypeDef RegisterDataType_Impl (int32 AllocationBlockSize)
ANIMNEXT_API void ReleaseReferencePoseData ()
Static Private Member Functions
static ANIMNEXT_API void Destroy ()
static ANIMNEXT_API void HandlePostGarbageCollect ()
static ANIMNEXT_API void Init ()
Private Attributes
TSet< Private::FAllocatedBlock * > AllocatedBlocks
FRWLock AllocatedBlocksLock
TMap< FAnimNextParamType, FDataTypeDef > DataTypeDefs
FRWLock DataTypeDefsLock
volatile int32 HandleCounter = 0
TMap< TObjectKey< USkeletalMeshComponent >, FReferencePoseData > SkeletalMeshReferencePoses
FRWLock SkeletalMeshReferencePosesLock
TMap< FName, FDataHandle > StoredData
FRWLock StoredDataLock
Static Private Attributes
static constexpr int32 DEFAULT_BLOCK_SIZE = 32
Friends
class FAnimNextModuleImpl
struct FDataHandle
Detailed Description
Definition at line 25 of file DataRegistry.h.
Member Typedef Documentation
DestroyFnSignature
typedef void(* UE::AnimNext::FDataRegistry::DestroyFnSignature) (uint8 *TargetBuffer, int32 NumElem) private
Definition at line 138 of file DataRegistry.h.
Member Function Documentation
AllocateData()
template<typename DataType, typename... ArgTypes> FDataHandle UE::AnimNext::FDataRegistry::AllocateData (const int32 NumElements, ArgTypes &&... Args) inline
Definition at line 123 of file DataRegistry.h.
References FDataHandle, Forward(), Handle, and PreAllocateMemory().
Destroy()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::Destroy () static private
References UE_API.
FreeAllocatedBlock()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::FreeAllocatedBlock (Private::FAllocatedBlock * AllocatedBlock) private
References UE_API.
Get()
ANIMNEXT_API FDataRegistry * UE::AnimNext::FDataRegistry::Get () static
References UE_API.
GetOrGenerateReferencePose()
ANIMNEXT_API FDataHandle UE::AnimNext::FDataRegistry::GetOrGenerateReferencePose (USkeletalMeshComponent * SkeletalMeshComponent)
References FDataHandle, and UE_API.
GetRegisteredData()
ANIMNEXT_API FDataHandle UE::AnimNext::FDataRegistry::GetRegisteredData (const FName & Id) const
References FDataHandle, and UE_API.
HandlePostGarbageCollect()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::HandlePostGarbageCollect () static private
References UE_API.
Init()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::Init () static private
References UE_API.
OnLODRequiredBonesUpdate()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::OnLODRequiredBonesUpdate (USkeletalMeshComponent * SkeletalMeshComponent, int32 LODLevel, const TArray< FBoneIndexType > & LODRequiredBones) private
References UE_API.
PreAllocateMemory()
template<typename DataType> FDataHandle UE::AnimNext::FDataRegistry::PreAllocateMemory (const int32 NumElements) inline
Definition at line 77 of file DataRegistry.h.
References UE::AnimNext::Private::FAllocatedBlock::AddRef(), Align, AllocatedBlocks, AllocatedBlocksLock, DataTypeDefs, DataTypeDefsLock, DEFAULT_BLOCK_SIZE, UE::AnimNext::FDataRegistry::FDataTypeDef::ElementAlign, UE::AnimNext::FDataRegistry::FDataTypeDef::ElementSize, ensure, FDataHandle, Memory, UE::AnimNext::FDataRegistry::FDataTypeDef::ParamType, RegisterDataType_Impl(), SLT_ReadOnly, and SLT_Write.
Referenced by AllocateData().
RegisterData()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::RegisterData (const FName & Id, const FDataHandle & AnimationDataHandle)
References FDataHandle, and UE_API.
RegisterDataType()
template<typename DataType> void UE::AnimNext::FDataRegistry::RegisterDataType (int32 AllocationBlockSize) inline
Definition at line 66 of file DataRegistry.h.
References RegisterDataType_Impl().
RegisterDataType_Impl()
template<typename DataType> FDataTypeDef UE::AnimNext::FDataRegistry::RegisterDataType_Impl (int32 AllocationBlockSize) inline private
Definition at line 191 of file DataRegistry.h.
References check, DataTypeDefs, DataTypeDefsLock, UE::AnimNext::FDataRegistry::FDataTypeDef::ParamType, and SLT_Write.
Referenced by PreAllocateMemory(), and RegisterDataType().
RegisterReferencePose()
ANIMNEXT_API FDataHandle UE::AnimNext::FDataRegistry::RegisterReferencePose (USkeletalMeshComponent * SkeletalMeshComponent)
References FDataHandle, and UE_API.
ReleaseReferencePoseData()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::ReleaseReferencePoseData () private
References UE_API.
RemoveReferencePose()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::RemoveReferencePose (USkeletalMeshComponent * SkeletalMeshComponent)
References UE_API.
UnregisterData()
ANIMNEXT_API void UE::AnimNext::FDataRegistry::UnregisterData (const FName & Id)
References UE_API.
Friends And Related Symbol Documentation
FAnimNextModuleImpl
friend class FAnimNextModuleImpl friend
Definition at line 227 of file DataRegistry.h.
References FAnimNextModuleImpl.
Referenced by FAnimNextModuleImpl.
FDataHandle
friend struct FDataHandle friend
Definition at line 228 of file DataRegistry.h.
References FDataHandle.
Referenced by UE::AnimNext::FDataRegistry::FReferencePoseData::FReferencePoseData(), UE::AnimNext::FDataRegistry::FReferencePoseData::FReferencePoseData(), AllocateData(), FDataHandle, GetOrGenerateReferencePose(), GetRegisteredData(), PreAllocateMemory(), RegisterData(), and RegisterReferencePose().
Field Documentation
AllocatedBlocks
TSet<Private::FAllocatedBlock*> UE::AnimNext::FDataRegistry::AllocatedBlocks private
Definition at line 177 of file DataRegistry.h.
Referenced by PreAllocateMemory().
AllocatedBlocksLock
FRWLock UE::AnimNext::FDataRegistry::AllocatedBlocksLock private
Definition at line 179 of file DataRegistry.h.
Referenced by PreAllocateMemory().
DataTypeDefs
TMap<FAnimNextParamType, FDataTypeDef> UE::AnimNext::FDataRegistry::DataTypeDefs private
Definition at line 173 of file DataRegistry.h.
Referenced by PreAllocateMemory(), and RegisterDataType_Impl().
DataTypeDefsLock
FRWLock UE::AnimNext::FDataRegistry::DataTypeDefsLock private
Definition at line 175 of file DataRegistry.h.
Referenced by PreAllocateMemory(), and RegisterDataType_Impl().
DEFAULT_BLOCK_SIZE
int32 UE::AnimNext::FDataRegistry::DEFAULT_BLOCK_SIZE = 32 static constexpr private
Definition at line 140 of file DataRegistry.h.
Referenced by PreAllocateMemory().
HandleCounter
volatile int32 UE::AnimNext::FDataRegistry::HandleCounter = 0 private
Definition at line 236 of file DataRegistry.h.
SkeletalMeshReferencePoses
TMap<TObjectKey<USkeletalMeshComponent>, FReferencePoseData> UE::AnimNext::FDataRegistry::SkeletalMeshReferencePoses private
Definition at line 186 of file DataRegistry.h.
SkeletalMeshReferencePosesLock
FRWLock UE::AnimNext::FDataRegistry::SkeletalMeshReferencePosesLock mutable private
Definition at line 187 of file DataRegistry.h.
StoredData
TMap<FName, FDataHandle> UE::AnimNext::FDataRegistry::StoredData private
Definition at line 182 of file DataRegistry.h.
StoredDataLock
FRWLock UE::AnimNext::FDataRegistry::StoredDataLock mutable private
Definition at line 183 of file DataRegistry.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNext/Source/AnimNext/Public/DataRegistry.h