Unreal Engine 5.6 C++ API: UFloatingPawnMovement Class Reference
UFloatingPawnMovement Class Reference
#include "FloatingPawnMovement.h"
Public Member Functions
UPROPERTY () float Acceleration
Acceleration applied by input (rate of change of velocity)
UPROPERTY () float Deceleration
Deceleration applied when there is no input (rate of change of velocity)
UPROPERTY () float MaxSpeed
Maximum velocity magnitude allowed for the controlled Pawn.
UPROPERTY ()) float TurningBoost
Setting affecting extra force applied when changing direction, making turns have less drift and become more responsive.
Protected Member Functions
virtual void ApplyControlInputToVelocity (float DeltaTime)
Update Velocity based on input.
virtual bool LimitWorldBounds ()
Prevent Pawn from leaving the world bounds (if that restriction is enabled in WorldSettings)
virtual bool ResolvePenetrationImpl (const FVector &Adjustment, const FHitResult &Hit, const FQuat &NewRotation) override
Private Member Functions
GENERATED_UCLASS_BODY () 1 virtual void TickComponent(float DeltaTime
virtual float GetMaxSpeed () const override
Private Attributes
enum ELevelTick TickType FActorComponentTickFunction *ThisTickFunction override
Detailed Description
Definition at line 22 of file FloatingPawnMovement.h.
Member Function Documentation
ApplyControlInputToVelocity()
virtual void UFloatingPawnMovement::ApplyControlInputToVelocity (float DeltaTime) protected virtual
Update Velocity based on input.
Also applies gravity.
References ApplyControlInputToVelocity(), and DeltaTime.
Referenced by ApplyControlInputToVelocity().
GENERATED_UCLASS_BODY()
UFloatingPawnMovement::GENERATED_UCLASS_BODY () private
GetMaxSpeed()
virtual float UFloatingPawnMovement::GetMaxSpeed () const inline override private virtual
Definition at line 31 of file FloatingPawnMovement.h.
References GetMaxSpeed().
Referenced by GetMaxSpeed().
LimitWorldBounds()
virtual bool UFloatingPawnMovement::LimitWorldBounds () protected virtual
Prevent Pawn from leaving the world bounds (if that restriction is enabled in WorldSettings)
References LimitWorldBounds(), Transient, and UPROPERTY().
Referenced by LimitWorldBounds().
ResolvePenetrationImpl()
virtual bool UFloatingPawnMovement::ResolvePenetrationImpl (const FVector & Adjustment, const FHitResult & Hit, const FQuat & NewRotation) override protected virtual
References FVector.
UPROPERTY() [1/4]
UFloatingPawnMovement::UPROPERTY ()
Acceleration applied by input (rate of change of velocity)
References Acceleration, and Category.
UPROPERTY() [2/4]
UFloatingPawnMovement::UPROPERTY ()
Deceleration applied when there is no input (rate of change of velocity)
References Category.
UPROPERTY() [3/4]
UFloatingPawnMovement::UPROPERTY ()
Maximum velocity magnitude allowed for the controlled Pawn.
References Category.
Referenced by LimitWorldBounds().
UPROPERTY() [4/4]
UFloatingPawnMovement::UPROPERTY ()
Setting affecting extra force applied when changing direction, making turns have less drift and become more responsive.
Velocity magnitude is not allowed to increase, that only happens due to normal acceleration. It may decrease with large direction changes. Larger values apply extra force to reach the target direction more quickly, while a zero value disables any extra turn force.
References Category, float, and meta.
Field Documentation
override
enum ELevelTick TickType FActorComponentTickFunction* ThisTickFunction UFloatingPawnMovement::override private
Definition at line 27 of file FloatingPawnMovement.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/GameFramework/FloatingPawnMovement.h