Unreal Engine 5.6 C++ API: FBackgroundURLSessionHandler Class Reference
FBackgroundURLSessionHandler Class Reference
#include "IOSBackgroundURLSessionHandler.h"
Public Member Functions
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDownloadsCompletedWhileAppWasNotRunning, const bool)
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnDownloadMetrics, const uint64, const int32, const float) static FOnDownloadMetrics OnDownloadMetrics
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnDownloadCompleted, const uint64, const bool)
UE_DEPRECATED (5.5, "Use new API in FBackgroundURLSessionHandler.") static bool InitBackgroundSession(const FString &SessionIdentifier)
UE_DEPRECATED (5.5, "Use new API in FBackgroundURLSessionHandler.") static void ShutdownBackgroundSession(bool bShouldFinishTasksFirst
Static Public Member Functions
static void AllowCellular (bool bAllow)
static void CancelDownload (const uint64 DownloadId)
static uint64 CreateOrFindDownload (const TArray< FString > &URLs, const float Priority, BackgroundHttpFileHashHelperRef HelperRef, const uint64 ExpectedResultSize=0)
static TArray< FString > GetCDNOrderArray ()
static uint64 GetCurrentDownloadedBytes (const uint64 DownloadId)
static void GetDownloadDebugText (const uint64 DownloadId, TArray< FString > &Output)
static void HandleDidEnterBackground ()
static void HandleEventsForBackgroundURLSession (const FString &SessionIdentifier)
static void HandleWillEnterForeground ()
static bool IsDownloadFinished (const uint64 DownloadId, int32 &OutResultHTTPCode, FString &OutTemporaryFilePath)
static void PauseDownload (const uint64 DownloadId)
static void ResumeDownload (const uint64 DownloadId)
static void SaveBackgroundHttpFileHashHelperState ()
static void SetPriority (const uint64 DownloadId, const float Priority)
Static Public Attributes
static const uint64 InvalidDownloadId
static FOnDownloadCompleted OnDownloadCompleted
static FOnDownloadsCompletedWhileAppWasNotRunning OnDownloadsCompletedWhileAppWasNotRunning
Detailed Description
Definition at line 30 of file IOSBackgroundURLSessionHandler.h.
Member Function Documentation
AllowCellular()
void FBackgroundURLSessionHandler::AllowCellular (bool bAllow) static
References AllowCellular().
Referenced by AllowCellular().
CancelDownload()
void FBackgroundURLSessionHandler::CancelDownload (const uint64 DownloadId) static
References CancelDownload().
Referenced by CancelDownload().
CreateOrFindDownload()
uint64 FBackgroundURLSessionHandler::CreateOrFindDownload (const TArray< FString > & URLs, const float Priority, BackgroundHttpFileHashHelperRef HelperRef, const uint64 ExpectedResultSize = 0) static
References CreateOrFindDownload().
Referenced by CreateOrFindDownload().
DECLARE_MULTICAST_DELEGATE_OneParam()
FBackgroundURLSessionHandler::DECLARE_MULTICAST_DELEGATE_OneParam (FOnDownloadsCompletedWhileAppWasNotRunning , const bool)
References DECLARE_MULTICAST_DELEGATE_OneParam().
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_ThreeParams()
FBackgroundURLSessionHandler::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnDownloadMetrics , const uint64 , const int32 , const float)
References DECLARE_MULTICAST_DELEGATE_ThreeParams().
Referenced by DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_TwoParams()
FBackgroundURLSessionHandler::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnDownloadCompleted , const uint64 , const bool)
References DECLARE_MULTICAST_DELEGATE_TwoParams().
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams().
GetCDNOrderArray()
TArray< FString > FBackgroundURLSessionHandler::GetCDNOrderArray () static
References GetCDNOrderArray().
Referenced by GetCDNOrderArray().
GetCurrentDownloadedBytes()
uint64 FBackgroundURLSessionHandler::GetCurrentDownloadedBytes (const uint64 DownloadId) static
References GetCurrentDownloadedBytes().
Referenced by GetCurrentDownloadedBytes().
GetDownloadDebugText()
void FBackgroundURLSessionHandler::GetDownloadDebugText (const uint64 DownloadId, TArray< FString > & Output) static
HandleDidEnterBackground()
void FBackgroundURLSessionHandler::HandleDidEnterBackground () static
References HandleDidEnterBackground().
Referenced by HandleDidEnterBackground().
HandleEventsForBackgroundURLSession()
void FBackgroundURLSessionHandler::HandleEventsForBackgroundURLSession (const FString & SessionIdentifier) static
References HandleEventsForBackgroundURLSession().
Referenced by HandleEventsForBackgroundURLSession().
HandleWillEnterForeground()
void FBackgroundURLSessionHandler::HandleWillEnterForeground () static
References HandleWillEnterForeground().
Referenced by HandleWillEnterForeground().
IsDownloadFinished()
bool FBackgroundURLSessionHandler::IsDownloadFinished (const uint64 DownloadId, int32 & OutResultHTTPCode, FString & OutTemporaryFilePath) static
References IsDownloadFinished().
Referenced by IsDownloadFinished().
PauseDownload()
void FBackgroundURLSessionHandler::PauseDownload (const uint64 DownloadId) static
References PauseDownload().
Referenced by PauseDownload().
ResumeDownload()
void FBackgroundURLSessionHandler::ResumeDownload (const uint64 DownloadId) static
References ResumeDownload().
Referenced by ResumeDownload().
SaveBackgroundHttpFileHashHelperState()
void FBackgroundURLSessionHandler::SaveBackgroundHttpFileHashHelperState () static
References SaveBackgroundHttpFileHashHelperState().
Referenced by SaveBackgroundHttpFileHashHelperState().
SetPriority()
void FBackgroundURLSessionHandler::SetPriority (const uint64 DownloadId, const float Priority) static
References SetPriority().
Referenced by SetPriority().
UE_DEPRECATED() [1/2]
FBackgroundURLSessionHandler::UE_DEPRECATED (5. 5, "Use new API in FBackgroundURLSessionHandler.") const & inline
Definition at line 34 of file IOSBackgroundURLSessionHandler.h.
UE_DEPRECATED() [2/2]
FBackgroundURLSessionHandler::UE_DEPRECATED (5. 5, "Use new API in FBackgroundURLSessionHandler.")
Field Documentation
InvalidDownloadId
const uint64 FBackgroundURLSessionHandler::InvalidDownloadId static
Definition at line 57 of file IOSBackgroundURLSessionHandler.h.
OnDownloadCompleted
FOnDownloadCompleted FBackgroundURLSessionHandler::OnDownloadCompleted static
Definition at line 61 of file IOSBackgroundURLSessionHandler.h.
OnDownloadsCompletedWhileAppWasNotRunning
FOnDownloadsCompletedWhileAppWasNotRunning FBackgroundURLSessionHandler::OnDownloadsCompletedWhileAppWasNotRunning static
Definition at line 71 of file IOSBackgroundURLSessionHandler.h.
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/IOS/IOSBackgroundURLSessionHandler.h