Unreal Engine 5.6 C++ API: FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc > Class Template Reference
FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc > Class Template Reference
#include "LockFreeList.h"
Public Member Functions
FLockFreePointerListLIFOBase ()=default
~FLockFreePointerListLIFOBase ()
FORCEINLINE uint64 GetState () const
FORCEINLINE bool IsEmpty () const
T * Pop ()
template<typename ContainerType>
void PopAll (ContainerType &OutContainer)
template<typename FunctorType>
void PopAllAndApply (FunctorType InFunctor)
template<typename ContainerType>
void PopAllAndChangeState (ContainerType &OutContainer, TFunctionRef< uint64(uint64)> StateChange)
void Push (T *InPayload)
bool PushIf (T *InPayload, TFunctionRef< bool(uint64)> OkToPush)
void Reset ()
Private Types
typedef FLockFreeLinkPolicy::TLinkPtr TLinkPtr
Private Attributes
FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc > RootList
UE_NONCOPYABLE(FLockFreePointerListLIFOBase) typedef FLockFreeLinkPolicy typedef FLockFreeLinkPolicy::TLink TLink
Detailed Description
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1>
class FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >
Definition at line 414 of file LockFreeList.h.
Member Typedef Documentation
TLinkPtr
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> typedef FLockFreeLinkPolicy::TLinkPtr FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::TLinkPtr private
Definition at line 420 of file LockFreeList.h.
Constructor & Destructor Documentation
FLockFreePointerListLIFOBase()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::FLockFreePointerListLIFOBase () nodiscard default
~FLockFreePointerListLIFOBase()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::~FLockFreePointerListLIFOBase () inline
Definition at line 425 of file LockFreeList.h.
References Pop().
Member Function Documentation
GetState()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE uint64 FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::GetState () const inline nodiscard
Definition at line 532 of file LockFreeList.h.
References FORCEINLINE, and RootList.
Referenced by TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::IsClosed().
IsEmpty()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FORCEINLINE bool FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::IsEmpty () const inline nodiscard
Definition at line 527 of file LockFreeList.h.
References FORCEINLINE, and RootList.
Referenced by TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::IsEmpty().
Pop()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> T * FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop () inline nodiscard
Definition at line 473 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), FLockFreeLinkPolicy::FreeLockFreeLink(), Item, and RootList.
Referenced by ~FLockFreePointerListLIFOBase(), TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::Pop(), and Reset().
PopAll()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> template<typename ContainerType> void FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAll (ContainerType & OutContainer) inline
Definition at line 486 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), FLockFreeLinkPolicy::FreeLockFreeLink(), RootList, and TLink.
Referenced by TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::PopAll().
PopAllAndApply()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> template<typename FunctorType> void FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndApply (FunctorType InFunctor) inline
Definition at line 500 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), FLockFreeLinkPolicy::FreeLockFreeLink(), RootList, and TLink.
Referenced by TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::PopAllAndApply().
PopAllAndChangeState()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> template<typename ContainerType> void FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PopAllAndChangeState (ContainerType & OutContainer, TFunctionRef< uint64(uint64)> StateChange) inline
Definition at line 514 of file LockFreeList.h.
References FLockFreeLinkPolicy::DerefLink(), FLockFreeLinkPolicy::FreeLockFreeLink(), RootList, and TLink.
Referenced by TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::PopAllAndClose().
Push()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> void FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Push (T * InPayload) inline
Definition at line 436 of file LockFreeList.h.
References FLockFreeLinkPolicy::AllocLockFreeLink(), FLockFreeLinkPolicy::DerefLink(), Item, FIndexedLockFreeLink::Payload, and RootList.
Referenced by TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >::Push().
PushIf()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> bool FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::PushIf (T * InPayload, TFunctionRef< bool(uint64)> OkToPush) inline
Definition at line 443 of file LockFreeList.h.
References FLockFreeLinkPolicy::AllocLockFreeLink(), FLockFreeLinkPolicy::DerefLink(), FLockFreeLinkPolicy::FreeLockFreeLink(), Item, FIndexedLockFreeLink::Payload, RootList, and State.
Referenced by TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::PushIfNotClosed().
Reset()
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> void FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::Reset () inline
Definition at line 430 of file LockFreeList.h.
References Pop(), and RootList.
Referenced by TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::Reset().
Field Documentation
RootList
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> FLockFreePointerListLIFORoot<TPaddingForCacheContention, TABAInc> FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::RootList private
Definition at line 539 of file LockFreeList.h.
Referenced by GetState(), IsEmpty(), Pop(), PopAll(), PopAllAndApply(), PopAllAndChangeState(), Push(), PushIf(), and Reset().
TLink
template<class T, int TPaddingForCacheContention, uint64 TABAInc = 1> UE_NONCOPYABLE (FLockFreePointerListLIFOBase) typedef FLockFreeLinkPolicy typedef FLockFreeLinkPolicy::TLink FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >::TLink private
Definition at line 419 of file LockFreeList.h.
Referenced by PopAll(), PopAllAndApply(), and PopAllAndChangeState().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LockFreeList.h