Unreal Engine 5.6 C++ API: FText Class Reference
FText Class Reference
#include "Text.h"
Data Structures
class FSortPredicate
Public Types
using IntrusiveUnsetOptionalStateType = FText
Public Member Functions
FText ()
FText (const FText &)=default
FText (FIntrusiveUnsetOptionalState)
FText (FText &&Other)
FString BuildSourceString () const
Deep build of the source string for this FText, climbing the history hierarchy.
int32 CompareTo (const FText &Other, const ETextComparisonLevel::Type ComparisonLevel=ETextComparisonLevel::Default) const
int32 CompareToCaseIgnored (const FText &Other) const
DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< ITextGenerator >, FCreateTextGeneratorDelegate, FStructuredArchive::FRecord)
bool EqualTo (const FText &Other, const ETextComparisonLevel::Type ComparisonLevel=ETextComparisonLevel::Default) const
bool EqualToCaseIgnored (const FText &Other) const
bool IdenticalTo (const FText &Other, const ETextIdenticalModeFlags CompareModeFlags=ETextIdenticalModeFlags::None) const
Check to see if this FText is identical to the other FText.
bool IsCultureInvariant () const
bool IsEmpty () const
bool IsEmptyOrWhitespace () const
bool IsFromStringTable () const
bool IsInitializedFromString () const
bool IsNumeric () const
bool IsTransient () const
FText & operator= (const FText &)=default
FText & operator= (FText &&Other)
bool operator== (FIntrusiveUnsetOptionalState) const
bool ShouldGatherForLocalization () const
FText ToLower () const
Transforms the text to lowercase in a culture correct way.
FText ToUpper () const
Transforms the text to uppercase in a culture correct way.
UE_DEPRECATED (5.5, "FText::FindText is deprecated as it can no longer find untranslated text. Consider FText::FindTextInLiveTable_Advanced or FText::AsLocalizable_Advanced as a replacement, depending on your use-case.") static FORCEINLINE bool FindText(const FTextKey &Namespace
Static Public Member Functions
static FText AsCultureInvariant (const ANSICHAR *String)
Generate a culture invariant FText representing the passed in string.
static FText AsCultureInvariant (const UTF8CHAR *String)
static FText AsCultureInvariant (const WIDECHAR *String)
static FText AsCultureInvariant (FAnsiStringView String)
static FText AsCultureInvariant (FString &&String)
static FText AsCultureInvariant (FText Text)
Generate a culture invariant FText representing the passed in FText.
static FText AsCultureInvariant (FUtf8StringView String)
static FText AsCultureInvariant (FWideStringView String)
static FText AsCurrency (double Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (float Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (int16 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (int32 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (int64 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (int8 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (long Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (uint16 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (uint32 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (uint64 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrency (uint8 Val, const FString &CurrencyCode=FString(), const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsCurrencyBase (int64 BaseVal, const FString &CurrencyCode, const FCulturePtr &TargetCulture=NULL, int32 ForceDecimalPlaces=-1)
Generate an FText that represents the passed number as currency in the current culture.
static FText AsDate (const FDateTime &DateTime, const EDateTimeStyle::Type DateStyle=EDateTimeStyle::Default, const FString &TimeZone=FString(), const FCulturePtr &TargetCulture=NULL)
Generate an FText that represents the given timestamp as a date/time in the current culture using the given timezone (default is the local timezone).
static FText AsDateTime (const FDateTime &DateTime, const EDateTimeStyle::Type DateStyle=EDateTimeStyle::Default, const EDateTimeStyle::Type TimeStyle=EDateTimeStyle::Default, const FString &TimeZone=FString(), const FCulturePtr &TargetCulture=NULL)
static FText AsDateTime (const FDateTime &DateTime, const FString &CustomPattern, const FString &TimeZone=FString(), const FCulturePtr &TargetCulture=NULL)
static FText AsLocalizable_Advanced (const FTextKey &Namespace, const FTextKey &Key, const TCHAR *String)
=== !
static FText AsLocalizable_Advanced (const FTextKey &Namespace, const FTextKey &Key, FString &&String)
static FText AsLocalizable_Advanced (const FTextKey &Namespace, const FTextKey &Key, FStringView String)
static FText AsMemory (uint64 NumBytes, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL, EMemoryUnitStandard UnitStandard=EMemoryUnitStandard::IEC)
Generate an FText that represents the passed number as a memory size in the current culture.
static FText AsMemory (uint64 NumBytes, EMemoryUnitStandard UnitStandard)
Generate an FText that represents the passed number as a memory size in the current culture.
static FText AsNumber (double Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (float Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
Generate an FText that represents the passed number in the current culture.
static FText AsNumber (int16 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (int32 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (int64 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (int8 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (long Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (uint16 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (uint32 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (uint64 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsNumber (uint8 Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsPercent (double Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
static FText AsPercent (float Val, const FNumberFormattingOptions *const Options=NULL, const FCulturePtr &TargetCulture=NULL)
Generate an FText that represents the passed number as a percentage in the current culture.
static FText AsTime (const FDateTime &DateTime, const EDateTimeStyle::Type TimeStyle=EDateTimeStyle::Default, const FString &TimeZone=FString(), const FCulturePtr &TargetCulture=NULL)
static FText AsTimespan (const FTimespan &Timespan, const FCulturePtr &TargetCulture=NULL)
Generate an FText that represents the given timespan in the current culture, as a delta-time representation (eg, {Hours}:{Minutes}:{Seconds} or {Minutes}:{Seconds}).
static void AutoRTFMAssignFromOpenToClosed (FText &Closed, const FText &Open)
static FCreateTextGeneratorDelegate FindRegisteredTextGenerator (FName TypeID)
Returns the text generator factory function registered under the specified name, if any.
static bool FindTextInLiveTable_Advanced (const FTextKey &Namespace, const FTextKey &Key, FText &OutText, const FString *const SourceString=nullptr)
=== !
template<typename... ArgTypes>
static FORCEINLINE FText Format (FTextFormat Fmt, ArgTypes... Args)
Format the given list of variadic values as ordered arguments within the given format pattern.
static FText Format (FTextFormat Fmt, const FFormatNamedArguments &InArguments)
Format the given map of key->value pairs as named arguments within the given format pattern.
static FText Format (FTextFormat Fmt, const FFormatOrderedArguments &InArguments)
Format the given list values as ordered arguments within the given format pattern.
static FText Format (FTextFormat Fmt, FFormatNamedArguments &&InArguments)
static FText Format (FTextFormat Fmt, FFormatOrderedArguments &&InArguments)
template<typename... TArguments>
static FText FormatNamed (FTextFormat Fmt, TArguments &&... Args)
Format the given list of variadic key->value pairs as named arguments within the given format pattern.
template<typename... TArguments>
static FText FormatOrdered (FTextFormat Fmt, TArguments &&... Args)
Format the given list of variadic values as ordered arguments within the given format pattern.
static FText FromName (const FName &Val)
Generate an FText representing the pass name.
static FText FromString (const ANSICHAR *String)
Generate an FText representing the passed in string.
static FText FromString (const FAnsiString &String)
static FText FromString (const FString &String)
static FText FromString (const FUtf8String &String)
static FText FromString (const UTF8CHAR *String)
static FText FromString (const WIDECHAR *String)
static FText FromString (FString &&String)
static FText FromStringTable (const FName InTableId, const FTextKey &InKey, const EStringTableLoadingPolicy InLoadingPolicy=EStringTableLoadingPolicy::FindOrLoad)
Attempts to create an FText instance from a string table ID and key (this is the same as the LOCTABLE macro, except this can also work with non-literal string values).
static FText FromStringView (FAnsiStringView InString)
Generate a FText representing the passed string view.
static FText FromStringView (FUtf8StringView InString)
static FText FromStringView (FWideStringView InString)
static FText FromTextGenerator (const TSharedRef< ITextGenerator > &TextGenerator)
Produces a custom-generated FText.
static const FText & GetEmpty ()
static void GetFormatPatternParameters (const FTextFormat &Fmt, TArray< FString > &ParameterNames)
static FString GetInvariantTimeZone ()
Gets the time zone string that represents a non-specific, zero offset, culture invariant time zone.
static bool IsWhitespace (const TCHAR Char)
Check to see if the given character is considered whitespace by the current culture.
template<typename... ArgTypes>
static FORCEINLINE FText Join (const FText &Delimiter, ArgTypes... Args)
Join an arbitrary list of formattable items together, separated by the given delimiter.
static FText Join (const FText &Delimiter, const FFormatOrderedArguments &Args)
Join an arbitrary list of formattable values together, separated by the given delimiter.
static FText Join (const FText &Delimiter, const TArray< FText > &Args)
static void PreloadStringTable (FName InTableId, const FTextKey &InKey)
template<typename T>
static void RegisterTextGenerator ()
Registers a standard text generator factory function.
template<typename T>
static void RegisterTextGenerator (FName TypeID)
Registers a standard text generator factory function.
static void RegisterTextGenerator (FName TypeID, FCreateTextGeneratorDelegate FactoryFunction)
Registers a factory function to be used with serialization of text generators within FText.
static FText TrimPreceding (const FText &)
Removes any whitespace characters from the start of the text.
static FText TrimPrecedingAndTrailing (const FText &)
Removes any whitespace characters from the start and end of the text.
static FText TrimTrailing (const FText &)
Removes any whitespace characters from the end of the text.
template<typename T>
static void UnregisterTextGenerator ()
Unregisters a standard text generator factory function.
static void UnregisterTextGenerator (FName TypeID)
Unregisters a factory function to be used with serialization of text generators within FText.
Data Fields
const FTextKey & Key
const FTextKey FText & OutText
const FTextKey FText const FString *const SourceString
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Private Member Functions
FText (FName InTableId, const FTextKey &InKey, const EStringTableLoadingPolicy InLoadingPolicy)
FText (FString &&InSourceString)
FText (FString &&InSourceString, const FTextKey &InNamespace, const FTextKey &InKey, uint32 InFlags=0)
template<typename HistoryType UE_REQUIRES>
FText (TRefCountPtr< HistoryType > &&InTextData)
void GetHistoricFormatData (TArray< FHistoricTextFormatData > &OutHistoricFormatData) const
Get any historic text format data from the history used by this FText.
bool GetHistoricNumericData (FHistoricTextNumericData &OutHistoricNumericData) const
Get any historic numeric format data from the history used by this FText.
const ITextData & GetTextData () const
This accessor for TextData guards against the case where TextData might be null and returns the ITextData from EmptyText instead.
void Rebuild () const
Rebuilds the FText under the current culture if needed.
Static Private Member Functions
template<typename T1, typename T2>
static FText AsCurrencyTemplate (T1 Val, const FString &CurrencyCode, const FNumberFormattingOptions *const Options, const FCulturePtr &TargetCulture)
template<typename T1, typename T2>
static FText AsNumberTemplate (T1 Val, const FNumberFormattingOptions *const Options, const FCulturePtr &TargetCulture)
template<typename T1, typename T2>
static FText AsPercentTemplate (T1 Val, const FNumberFormattingOptions *const Options, const FCulturePtr &TargetCulture)
template<typename T>
static TSharedRef< ITextGenerator > CreateTextGenerator (FStructuredArchive::FRecord Record)
static FText FormatNamedImpl (FTextFormat &&Fmt, FFormatNamedArguments &&InArguments)
static FText FormatOrderedImpl (FTextFormat &&Fmt, FFormatOrderedArguments &&InArguments)
static void SerializeText (FArchive &Ar, FText &Value)
static void SerializeText (FStructuredArchive::FSlot Slot, FText &Value)
Private Attributes
uint32 Flags
Flags with various information on what sort of FText this is.
TRefCountPtr< ITextData > TextData
The internal shared data for this FText.
Friends
class FArchive
class FArchiveFromStructuredArchiveImpl
class FFormatArgumentValue
class FJsonArchiveInputFormatter
class FJsonArchiveOutputFormatter
class FScopedTextIdentityPreserver
class FStringTableRegistry
class FTextCache
class FTextFormatData
class FTextFormatter
class FTextHistory_ArgumentDataFormat
class FTextHistory_NamedFormat
class FTextHistory_OrderedFormat
class FTextHistory_Transform
class FTextInspector
class FTextProperty
class FTextSnapshot
class FTextStringHelper
Detailed Description
Definition at line 384 of file Text.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
using FText::IntrusiveUnsetOptionalStateType = FText
Definition at line 836 of file Text.h.
Constructor & Destructor Documentation
FText() [1/8]
FText::FText ()
Referenced by FText(), FText(), AsCultureInvariant(), AsCultureInvariant(), AsCultureInvariant(), AsCultureInvariant(), AsCultureInvariant(), AsCultureInvariant(), AsCultureInvariant(), AsCultureInvariant(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrency(), AsCurrencyBase(), AsCurrencyTemplate(), AsDate(), AsDateTime(), AsDateTime(), AsLocalizable_Advanced(), AsLocalizable_Advanced(), AsLocalizable_Advanced(), AsMemory(), AsMemory(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumber(), AsNumberTemplate(), AsPercent(), AsPercent(), AsPercentTemplate(), AsTime(), AsTimespan(), AutoRTFMAssignFromOpenToClosed(), CompareTo(), CompareToCaseIgnored(), EqualTo(), EqualToCaseIgnored(), FindTextInLiveTable_Advanced(), Format(), Format(), Format(), Format(), Format(), FormatNamed(), FormatNamedImpl(), FormatOrdered(), FormatOrderedImpl(), FromName(), FromString(), FromString(), FromString(), FromString(), FromString(), FromString(), FromString(), FromStringTable(), FromStringView(), FromStringView(), FromStringView(), FromTextGenerator(), GetEmpty(), IdenticalTo(), Join(), Join(), Join(), FText::FSortPredicate::operator()(), operator=(), operator=(), PreloadStringTable(), SerializeText(), SerializeText(), ToLower(), ToUpper(), TrimPreceding(), TrimPrecedingAndTrailing(), and TrimTrailing().
FText() [2/8]
FText::FText (const FText &) default
References FText().
FText() [3/8]
FText::FText (FText && Other)
References FText(), and Other.
FText() [4/8]
FText::FText (FIntrusiveUnsetOptionalState) inline explicit
Definition at line 838 of file Text.h.
References Flags, and TextData.
FText() [5/8]
template<typename HistoryType UE_REQUIRES> FText::FText (TRefCountPtr< HistoryType > && InTextData) inline explicit private
Definition at line 855 of file Text.h.
References Flags, MoveTemp(), and TextData.
FText() [6/8]
FText::FText (FString && InSourceString) explicit private
FText() [7/8]
FText::FText (FName InTableId, const FTextKey & InKey, const EStringTableLoadingPolicy InLoadingPolicy) private
FText() [8/8]
FText::FText (FString && InSourceString, const FTextKey & InNamespace, const FTextKey & InKey, uint32 InFlags = 0) private
Member Function Documentation
AsCultureInvariant() [1/8]
FText FText::AsCultureInvariant (const ANSICHAR * String) static nodiscard
Generate a culture invariant FText representing the passed in string.
References FText(), and String.
AsCultureInvariant() [2/8]
FText FText::AsCultureInvariant (const UTF8CHAR * String) static nodiscard
References FText(), and String.
AsCultureInvariant() [3/8]
FText FText::AsCultureInvariant (const WIDECHAR * String) static nodiscard
References FText(), and String.
AsCultureInvariant() [4/8]
FText FText::AsCultureInvariant (FAnsiStringView String) static nodiscard
References FText(), and String.
AsCultureInvariant() [5/8]
FText FText::AsCultureInvariant (FString && String) static nodiscard
References FText(), and String.
AsCultureInvariant() [6/8]
FText FText::AsCultureInvariant (FText Text) static nodiscard
Generate a culture invariant FText representing the passed in FText.
References FText(), and Text.
AsCultureInvariant() [7/8]
FText FText::AsCultureInvariant (FUtf8StringView String) static nodiscard
References FText(), and String.
AsCultureInvariant() [8/8]
FText FText::AsCultureInvariant (FWideStringView String) static nodiscard
References FText(), and String.
AsCurrency() [1/11]
FText FText::AsCurrency (double Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [2/11]
FText FText::AsCurrency (float Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [3/11]
FText FText::AsCurrency (int16 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [4/11]
FText FText::AsCurrency (int32 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [5/11]
FText FText::AsCurrency (int64 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [6/11]
FText FText::AsCurrency (int8 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [7/11]
FText FText::AsCurrency (long Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [8/11]
FText FText::AsCurrency (uint16 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [9/11]
FText FText::AsCurrency (uint32 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [10/11]
FText FText::AsCurrency (uint64 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrency() [11/11]
FText FText::AsCurrency (uint8 Val, const FString & CurrencyCode = FString(), const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsCurrencyBase()
FText FText::AsCurrencyBase (int64 BaseVal, const FString & CurrencyCode, const FCulturePtr & TargetCulture = NULL, int32 ForceDecimalPlaces = -1) static nodiscard
Generate an FText that represents the passed number as currency in the current culture.
BaseVal is specified in the smallest fractional value of the currency and will be converted for formatting according to the selected culture. Keep in mind the CurrencyCode is completely independent of the culture it's displayed in (and they do not imply one another). For example: FText::AsCurrencyBase(650, TEXT("EUR")); would return an FText of "<EUR>6.50" in most English cultures (en_US/en_UK) and "6,50<EUR>" in Spanish (es_ES) (where <EUR> is U+20AC)
References FText().
AsCurrencyTemplate()
template<typename T1, typename T2> FText FText::AsCurrencyTemplate (T1 Val, const FString & CurrencyCode, const FNumberFormattingOptions *const Options, const FCulturePtr & TargetCulture) static private
References FText().
AsDate()
FText FText::AsDate (const FDateTime & DateTime, const EDateTimeStyle::Type DateStyle = EDateTimeStyle::Default, const FString & TimeZone = FString(), const FCulturePtr & TargetCulture = NULL) static nodiscard
Generate an FText that represents the given timestamp as a date/time in the current culture using the given timezone (default is the local timezone).
This function will convert the given timestamp from UTC (eg, FDateTime::UtcNow()) to the given timezone (taking into account DST). If using a local timestamp (eg, FDateTime::Now()) then you MUST use FText::GetInvariantTimeZone() as the TimeZone argument to avoid additional timezone conversion.
Note
The overload using a custom pattern uses strftime-like syntax (see FDateTime::ToFormattedString).
References FText(), DateTime, and EDateTimeStyle::Default.
AsDateTime() [1/2]
FText FText::AsDateTime (const FDateTime & DateTime, const EDateTimeStyle::Type DateStyle = EDateTimeStyle::Default, const EDateTimeStyle::Type TimeStyle = EDateTimeStyle::Default, const FString & TimeZone = FString(), const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText(), DateTime, and EDateTimeStyle::Default.
AsDateTime() [2/2]
FText FText::AsDateTime (const FDateTime & DateTime, const FString & CustomPattern, const FString & TimeZone = FString(), const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText(), and DateTime.
AsLocalizable_Advanced() [1/3]
FText FText::AsLocalizable_Advanced (const FTextKey & Namespace, const FTextKey & Key, const TCHAR * String) static nodiscard
=== !
! This is an ADVANCED function. USE WITH CAUTION !! ===
Generate a localizable FText for the given ID and source string, either to create a NEW localizable FText, or to dynamically reference an EXISTING FText.
When using it to create a NEW localizable FText (eg, when editing an asset), YOU are responsible for ensuring that the resultant FText is gathered for localization (eg, by assigning it to a FText property or via a CUSTOM gather handler). Note: DO NOT use this as a general replacement for the LOCTEXT macro in C++!
When using it to dynamically reference an EXISTING FText (such as known LOCTEXT in code) it can be thought of as an alternative to FText::FindTextInLiveTable_Advanced that also handles untranslated text. Note: Direct dynamic references to FText are EXTREMELY FRAGILE, and you may want to use a string table instead!
References FText(), Key, and String.
AsLocalizable_Advanced() [2/3]
FText FText::AsLocalizable_Advanced (const FTextKey & Namespace, const FTextKey & Key, FString && String) static nodiscard
References FText(), Key, and String.
AsLocalizable_Advanced() [3/3]
FText FText::AsLocalizable_Advanced (const FTextKey & Namespace, const FTextKey & Key, FStringView String) static nodiscard
References FText(), Key, and String.
AsMemory() [1/2]
FText FText::AsMemory (uint64 NumBytes, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL, EMemoryUnitStandard UnitStandard = EMemoryUnitStandard::IEC) static nodiscard
Generate an FText that represents the passed number as a memory size in the current culture.
References FText(), and IEC.
AsMemory() [2/2]
FText FText::AsMemory (uint64 NumBytes, EMemoryUnitStandard UnitStandard) static nodiscard
Generate an FText that represents the passed number as a memory size in the current culture.
References FText().
AsNumber() [1/11]
FText FText::AsNumber (double Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [2/11]
FText FText::AsNumber (float Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
Generate an FText that represents the passed number in the current culture.
References FText().
Referenced by UE::Insights::FTableCellValue::AsText(), IAnimationDataController::ConvertSecondsToFrameNumber(), UE::Insights::FInt64ValueFormatterAsNumber::FormatValue(), FBookmarkUI::GetClearLabel(), FBookmarkUI::GetClearTooltip(), FDelayAction::GetDescription(), FBookmarkUI::GetJumpToLabel(), FBookmarkUI::GetJumpToTooltip(), FBookmarkUI::GetPlainLabel(), SRigVMActionMenu::GetSearchContextDesc(), FBookmarkUI::GetSetLabel(), FBookmarkUI::GetSetTooltip(), TraceServices::FMetadataSchema::FReader::GetText(), SNumericDropDown< NumericType >::GetValueText(), FActorDragDropOp::Init(), FFolderDragDropOp::Init(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), UE::Math::TVector< T >::ToCompactText(), FErrorTrackerWorstAnimation::ToText(), FErrorTrackerWorstBone::ToText(), and FTabId::ToText().
AsNumber() [3/11]
FText FText::AsNumber (int16 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [4/11]
FText FText::AsNumber (int32 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [5/11]
FText FText::AsNumber (int64 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [6/11]
FText FText::AsNumber (int8 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [7/11]
FText FText::AsNumber (long Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [8/11]
FText FText::AsNumber (uint16 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [9/11]
FText FText::AsNumber (uint32 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [10/11]
FText FText::AsNumber (uint64 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumber() [11/11]
FText FText::AsNumber (uint8 Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsNumberTemplate()
template<typename T1, typename T2> FText FText::AsNumberTemplate (T1 Val, const FNumberFormattingOptions *const Options, const FCulturePtr & TargetCulture) static private
References FText().
AsPercent() [1/2]
FText FText::AsPercent (double Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText().
AsPercent() [2/2]
FText FText::AsPercent (float Val, const FNumberFormattingOptions *const Options = NULL, const FCulturePtr & TargetCulture = NULL) static nodiscard
Generate an FText that represents the passed number as a percentage in the current culture.
References FText().
AsPercentTemplate()
template<typename T1, typename T2> FText FText::AsPercentTemplate (T1 Val, const FNumberFormattingOptions *const Options, const FCulturePtr & TargetCulture) static private
References FText(), and Record.
AsTime()
FText FText::AsTime (const FDateTime & DateTime, const EDateTimeStyle::Type TimeStyle = EDateTimeStyle::Default, const FString & TimeZone = FString(), const FCulturePtr & TargetCulture = NULL) static nodiscard
References FText(), DateTime, and EDateTimeStyle::Default.
AsTimespan()
FText FText::AsTimespan (const FTimespan & Timespan, const FCulturePtr & TargetCulture = NULL) static nodiscard
Generate an FText that represents the given timespan in the current culture, as a delta-time representation (eg, {Hours}:{Minutes}:{Seconds} or {Minutes}:{Seconds}).
References FText(), and Timespan.
AutoRTFMAssignFromOpenToClosed()
void FText::AutoRTFMAssignFromOpenToClosed (FText & Closed, const FText & Open) static
References FText().
BuildSourceString()
FString FText::BuildSourceString () const nodiscard
Deep build of the source string for this FText, climbing the history hierarchy.
Referenced by FindInBlueprintsHelpers::GetTypeHash(), FindInBlueprintsHelpers::FSimpleFTextKeyStorage::operator==(), and FNodeTextCache::UpdateCacheIternal().
CompareTo()
int32 FText::CompareTo (const FText & Other, const ETextComparisonLevel::Type ComparisonLevel = ETextComparisonLevel::Default) const nodiscard
References FText(), ETextComparisonLevel::Default, and Other.
CompareToCaseIgnored()
int32 FText::CompareToCaseIgnored (const FText & Other) const nodiscard
References FText(), and Other.
CreateTextGenerator()
template<typename T> TSharedRef< ITextGenerator > FText::CreateTextGenerator (FStructuredArchive::FRecord Record) inline static private
Definition at line 1055 of file Text.h.
References MakeShared(), and Record.
Referenced by RegisterTextGenerator().
DECLARE_DELEGATE_RetVal_OneParam()
FText::DECLARE_DELEGATE_RetVal_OneParam (TSharedRef< ITextGenerator > , FCreateTextGeneratorDelegate , FStructuredArchive::FRecord)
EqualTo()
bool FText::EqualTo (const FText & Other, const ETextComparisonLevel::Type ComparisonLevel = ETextComparisonLevel::Default) const nodiscard
References FText(), ETextComparisonLevel::Default, and Other.
Referenced by USTRUCT().
EqualToCaseIgnored()
bool FText::EqualToCaseIgnored (const FText & Other) const nodiscard
References FText(), and Other.
FindRegisteredTextGenerator()
FCreateTextGeneratorDelegate FText::FindRegisteredTextGenerator (FName TypeID) static nodiscard
Returns the text generator factory function registered under the specified name, if any.
Parameters
TypeID the name under which to look up the factory function
FindTextInLiveTable_Advanced()
bool FText::FindTextInLiveTable_Advanced (const FTextKey & Namespace, const FTextKey & Key, FText & OutText, const FString *const SourceString = nullptr) static
=== !
! This is an ADVANCED function. USE WITH CAUTION !! ===
Attempt to dynamically reference an EXISTING FText via its active display string in the live table. Note: This can ONLY find text that is currently localized (gathered, translated, and has an active display string in FTextLocalizationManager). If you need to find a localizable but untranslated text, see FText::AsLocalizable_Advanced. Note: Direct dynamic references to FText are EXTREMELY FRAGILE, and you may want to use a string table instead!
Parameters
Namespace The namespace of the text to find (if any).
Key The key of the text to find.
SourceString If set (not empty) then the found text must also have been created from this source string.
Returns
true if OutText was set; otherwise false and OutText will be unmodified
References FText(), Key, OutText, and SourceString.
Format() [1/5]
template<typename... ArgTypes> FORCEINLINE FText FText::Format (FTextFormat Fmt, ArgTypes... Args) inline static nodiscard
Format the given list of variadic values as ordered arguments within the given format pattern.
Note
You may want to pre-compile your FText pattern into a FTextFormat prior to performing formats within a loop or on a critical path, as this can save CPU cycles, memory, and mutex resources vs re-compiling the pattern for each format call. See FTextFormat for more info.
@usage FText::Format(LOCTEXT("PlayerNameFmt", "{0} is really cool"), FText::FromString(PlayerName));
Parameters
Fmt The format pattern to use
Args A variadic list of values to inject into the format pattern
Returns
The formatted FText
Definition at line 674 of file Text.h.
References FText(), FORCEINLINE, Format(), MoveTemp(), and TIsConstructible< T, Args >::Value.
Format() [2/5]
FText FText::Format (FTextFormat Fmt, const FFormatNamedArguments & InArguments) static nodiscard
Format the given map of key->value pairs as named arguments within the given format pattern.
Note
You may want to pre-compile your FText pattern into a FTextFormat prior to performing formats within a loop or on a critical path, as this can save CPU cycles, memory, and mutex resources vs re-compiling the pattern for each format call. See FTextFormat for more info.
Parameters
Fmt The format pattern to use
InArguments The map of key->value pairs to inject into the format pattern
Returns
The formatted FText
References FText().
Referenced by FTextBuilder::AppendLineFormat(), FSequencerFilterBase< InFilterType >::BuildTooltipTextForCommand(), Format(), FBookmarkUI::GetClearLabel(), FBookmarkUI::GetClearTooltip(), FDelayAction::GetDescription(), UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorProperties(), FBoneDragDropOp::GetHoverText(), FSocketDragDropOp::GetHoverText(), FBookmarkUI::GetJumpToLabel(), FBookmarkUI::GetJumpToTooltip(), FBookmarkUI::GetPlainLabel(), SRigVMActionMenu::GetSearchContextDesc(), TSubSectionMixin< ParentSectionClass >::GetSectionToolTip(), FBookmarkUI::GetSetLabel(), FBookmarkUI::GetSetTooltip(), TraceServices::FMetadataSchema::FReader::GetText(), SNumericEntryBox< NumericType >::GetToolTipText(), FActorDragDropOp::Init(), FFolderDragDropOp::Init(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), IAnimationDataController::ReportErrorf(), IAnimationDataController::Reportf(), IAnimationDataController::Reportf(), IAnimationDataController::ReportObjectErrorf(), IAnimationDataController::ReportObjectWarningf(), IAnimationDataController::ReportWarningf(), FActorDragDropGraphEdOp::SetToolTip(), UE::Math::TVector< T >::ToCompactText(), FErrorTrackerWorstAnimation::ToText(), FErrorTrackerWorstBone::ToText(), FTabId::ToText(), and UE::Math::TVector< T >::ToText().
Format() [3/5]
FText FText::Format (FTextFormat Fmt, const FFormatOrderedArguments & InArguments) static nodiscard
Format the given list values as ordered arguments within the given format pattern.
Note
You may want to pre-compile your FText pattern into a FTextFormat prior to performing formats within a loop or on a critical path, as this can save CPU cycles, memory, and mutex resources vs re-compiling the pattern for each format call. See FTextFormat for more info.
Parameters
Fmt The format pattern to use
InArguments The list of values to inject into the format pattern
Returns
The formatted FText
References FText().
Format() [4/5]
FText FText::Format (FTextFormat Fmt, FFormatNamedArguments && InArguments) static nodiscard
References FText().
Format() [5/5]
FText FText::Format (FTextFormat Fmt, FFormatOrderedArguments && InArguments) static nodiscard
References FText().
FormatNamed()
template<typename... TArguments> FText FText::FormatNamed (FTextFormat Fmt, TArguments &&... Args) static nodiscard
Format the given list of variadic key->value pairs as named arguments within the given format pattern.
Note
You may want to pre-compile your FText pattern into a FTextFormat prior to performing formats within a loop or on a critical path, as this can save CPU cycles, memory, and mutex resources vs re-compiling the pattern for each format call. See FTextFormat for more info.
@usage FText::FormatNamed(LOCTEXT("PlayerNameFmt", "{PlayerName} is really cool"), TEXT("PlayerName"), FText::FromString(PlayerName));
Parameters
Fmt The format pattern to use
Args A variadic list of "key then value" pairs to inject into the format pattern (must be an even number)
Returns
The formatted FText
Definition at line 1122 of file Text.h.
References FText(), TextFormatUtil::FormatNamed(), FormatNamedImpl(), Forward(), MoveTemp(), and TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Reserve().
FormatNamedImpl()
FText FText::FormatNamedImpl (FTextFormat && Fmt, FFormatNamedArguments && InArguments) static private
References FText().
Referenced by FormatNamed().
FormatOrdered()
template<typename... TArguments> FText FText::FormatOrdered (FTextFormat Fmt, TArguments &&... Args) static nodiscard
Format the given list of variadic values as ordered arguments within the given format pattern.
Note
You may want to pre-compile your FText pattern into a FTextFormat prior to performing formats within a loop or on a critical path, as this can save CPU cycles, memory, and mutex resources vs re-compiling the pattern for each format call. See FTextFormat for more info.
@usage FText::FormatOrdered(LOCTEXT("PlayerNameFmt", "{0} is really cool"), FText::FromString(PlayerName));
Parameters
Fmt The format pattern to use
Args A variadic list of values to inject into the format pattern
Returns
The formatted FText
Definition at line 1133 of file Text.h.
References FText(), TextFormatUtil::FormatOrdered(), FormatOrderedImpl(), Forward(), MoveTemp(), and TArray< InElementType, InAllocatorType >::Reserve().
Referenced by FTokenizedMessage::AddText().
FormatOrderedImpl()
FText FText::FormatOrderedImpl (FTextFormat && Fmt, FFormatOrderedArguments && InArguments) static private
References FText().
Referenced by FormatOrdered().
FromName()
FText FText::FromName (const FName & Val) static nodiscard
Generate an FText representing the pass name.
References FText().
Referenced by FImageToken::FImageToken(), SSkeletonBoneRemoval::GenerateSkeletonBoneRow(), SSkeletonListWidget::GenerateSkeletonBoneRow(), SBonePairRow::GenerateWidgetForColumn(), FMediaIOCoreSampleContainer< SampleType >::GetDisplayName(), IAssetReferenceFixer::GetFixerLabel(), FSocketDragDropOp::GetHoverText(), TMediaPermutationsSelectorBuilder< ItemType >::GetLabel(), TMediaPermutationsSelectorBuilder< ItemType >::GetTooltip(), FFolderDragDropOp::Init(), FErrorTrackerWorstAnimation::ToText(), FErrorTrackerWorstBone::ToText(), FTabId::ToText(), and USTRUCT().
FromString() [1/7]
FText FText::FromString (const ANSICHAR * String) static nodiscard
Generate an FText representing the passed in string.
References FText(), and String.
Referenced by FRigVMEditorZoomLevelsContainer::FRigVMEditorZoomLevelsContainer(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::Insights::FTableCellValue::AsText(), IAnimationDataController::CheckOuterClass(), FGameModeInfoCustomizer::CreateGameModePropertyLabelWidget(), UE::Insights::FInt64ValueFormatterAsHex32::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex64::FormatValue(), Verse::FNativeConverter::FromVValue(), Verse::FNativeConverter::FromVValue(), Verse::FNativeConverter::FromVValue(), SSkeletonListWidget::GenerateSkeletonRow(), FClassDragDropOp::GetDefaultDecorator(), FTransaction::GetDescription(), IConsoleObject::GetDetailedHelp(), UE::RigVM::Editor::Tools::FFilterByAssetTag::GetDisplayName(), FBoneDragDropOp::GetHoverText(), SRigVMActionMenu::GetSearchContextDesc(), TSubSectionMixin< ParentSectionClass >::GetSectionTitle(), TraceServices::FMetadataSchema::FReader::GetText(), SNumericEntryBox< NumericType >::GetToolTipText(), SRigVMUserDataPath::GetUserDataPathText(), SNumericTextBlockKeyEditor< ChannelType, NumericType >::GetValueAsText(), SGridLineSpacingList::GetValueText(), FActorDragDropOp::Init(), FLevelDragDropOp::Init(), UE::PixelStreaming2::IsPlatformSupported(), FSequencerFilterSuggestion::MakeSimpleSuggestion(), SNumericEntryBox< NumericType >::OnGetValueForTextBox(), SPinComboBox::OnGetVisibleTextInternal(), FActorDragDropGraphEdOp::SetToolTip(), SNumericRotatorInputBox< float >::SLATE_END_ARGS(), STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), STreeView< FRigVMSearchResult >::SLATE_EVENT(), FCompilerResultsLog::Tokenize(), FCompilerResultsLog::Tokenize(), and FNodeTextCache::UpdateCacheIternal().
FromString() [2/7]
FText FText::FromString (const FAnsiString & String) static nodiscard
References FText(), and String.
FromString() [3/7]
FText FText::FromString (const FString & String) static nodiscard
References FText(), and String.
FromString() [4/7]
FText FText::FromString (const FUtf8String & String) static nodiscard
References FText(), and String.
FromString() [5/7]
FText FText::FromString (const UTF8CHAR * String) static nodiscard
References FText(), and String.
FromString() [6/7]
FText FText::FromString (const WIDECHAR * String) static nodiscard
References FText(), and String.
FromString() [7/7]
FText FText::FromString (FString && String) static nodiscard
References FText(), and String.
FromStringTable()
FText FText::FromStringTable (const FName InTableId, const FTextKey & InKey, const EStringTableLoadingPolicy InLoadingPolicy = EStringTableLoadingPolicy::FindOrLoad) static nodiscard
Attempts to create an FText instance from a string table ID and key (this is the same as the LOCTABLE macro, except this can also work with non-literal string values).
Returns
The found text, or a dummy FText if not found.
References FText(), and FindOrLoad.
FromStringView() [1/3]
FText FText::FromStringView (FAnsiStringView InString) static nodiscard
Generate a FText representing the passed string view.
References FText().
Referenced by UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty().
FromStringView() [2/3]
FText FText::FromStringView (FUtf8StringView InString) static nodiscard
References FText().
FromStringView() [3/3]
FText FText::FromStringView (FWideStringView InString) static nodiscard
References FText().
FromTextGenerator()
FText FText::FromTextGenerator (const TSharedRef< ITextGenerator > & TextGenerator) static nodiscard
Produces a custom-generated FText.
Can be used for objects that produce text dependent on localized strings but that do not fit the standard formats.
Parameters
TextGenerator the text generator object that will generate the text
References FText().
GetEmpty()
const FText & FText::GetEmpty () static
References FText().
Referenced by FBindingContextStruct::FBindingContextStruct(), SMyBlueprint::AddEventForFunctionGraph(), FRigVMActionMenuBuilder::AddMenuSection(), UE::Insights::FTableCellValue::AsText(), FNodeTextCache::Clear(), FPropertyEditorModule::CreateStructureDetailView(), FPropertyEditorModule::CreateStructureDetailView(), FPropertyEditorModule::CreateStructureProviderDetailView(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::DeclareVertexInterface(), Metasound::SendNodePrivate::TSendOperator< TDataType >::DeclareVertexInterface(), IDetailLayoutBuilder::EditCategory(), IDetailLayoutBuilder::EditCategoryAllowNone(), UE::Insights::FAsTextValueFormatter::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex32::FormatValue(), UE::Insights::FInt64ValueFormatterAsHex64::FormatValue(), UE::Insights::FInt64ValueFormatterAsNumber::FormatValue(), UE::Insights::FTableCellValueFormatter::FormatValue(), UE::Insights::FTextValueFormatter::FormatValue(), FDetailArrayBuilder::GenerateHeaderRowContent(), IImportantToggleSettingInterface::GetAdditionalInfoUrlLabel(), FBaseAssetToolkit::GetBaseToolkitName(), ISequencerTextFilterExpressionContext::GetCategory(), SMyBlueprint::GetChildEvents(), SMyBlueprint::GetChildGraphs(), UE::SequenceNavigator::FNavigationToolItem::GetClassName(), UE::SequenceNavigator::FNavigationToolItemProxy::GetClassName(), UE::SequenceNavigator::INavigationToolProvider::GetDefaultColumnView(), FSequencerFilterBase< InFilterType >::GetDisplayName(), IMovieSceneEasingFunction::GetDisplayName(), UE::AnimNext::ITraitInterface::GetDisplayName(), UE::SequenceNavigator::FNavigationToolItem::GetDisplayName(), UE::AnimNext::ITraitInterface::GetDisplayShortName(), IImportantToggleSettingInterface::GetFalseStateDescription(), IImportantToggleSettingInterface::GetFalseStateLabel(), IImportantToggleSettingInterface::GetFalseStateTooltip(), TSubSectionMixin< ParentSectionClass >::GetSectionToolTip(), ILiveLinkSource::GetSourceToolTip(), FBaseToolkit::GetTabSuffix(), UE::Insights::FTableCellValue::GetText(), SNumericEntryBox< NumericType >::GetToolTipText(), UE::Insights::FBaseTreeNode::GetTooltipText(), IImportantToggleSettingInterface::GetTrueStateDescription(), IImportantToggleSettingInterface::GetTrueStateLabel(), IImportantToggleSettingInterface::GetTrueStateTooltip(), FThumbnailSection::HandleThumbnailTextBlockText(), SNumericEntryBox< NumericType >::OnGetValueForTextBox(), FEditorCategoryUtils::RegisterCategoryKey(), FEditorBuildUtils::RegisterCustomBuildType(), FEditorBuildUtils::RegisterCustomBuildType(), UEdGraphPin::ResetDefaultValue(), UEdGraphPin::ResetToDefaults(), FActorDragDropGraphEdOp::SetToolTip(), FFixResult::Success(), FGameInstancePIEResult::Success(), IStateTreeBindingLookup::UE_DEPRECATED(), FSlateNotificationManager::UpdateProgressNotification(), USTRUCT(), USTRUCT(), and FPluginTemplateDescription::ValidatePathForPlugin().
GetFormatPatternParameters()
void FText::GetFormatPatternParameters (const FTextFormat & Fmt, TArray< FString > & ParameterNames) static
GetHistoricFormatData()
void FText::GetHistoricFormatData (TArray< FHistoricTextFormatData > & OutHistoricFormatData) const private
Get any historic text format data from the history used by this FText.
GetHistoricNumericData()
bool FText::GetHistoricNumericData (FHistoricTextNumericData & OutHistoricNumericData) const private
Get any historic numeric format data from the history used by this FText.
GetInvariantTimeZone()
FString FText::GetInvariantTimeZone () static nodiscard
Gets the time zone string that represents a non-specific, zero offset, culture invariant time zone.
GetTextData()
const ITextData & FText::GetTextData () const private
This accessor for TextData guards against the case where TextData might be null and returns the ITextData from EmptyText instead.
IdenticalTo()
bool FText::IdenticalTo (const FText & Other, const ETextIdenticalModeFlags CompareModeFlags = ETextIdenticalModeFlags::None) const nodiscard
Check to see if this FText is identical to the other FText.
Note
This function defaults to only testing that the internal data has the same target (which makes it very fast!), rather than performing any deep or lexical analysis. The ETextIdenticalModeFlags can modify this default behavior. See the comments on those flag options for more information.
If you actually want to perform a full lexical comparison, then you need to use EqualTo instead.
References FText(), None, and Other.
Referenced by TSlateAttributeFTextComparePredicate::IdenticalTo(), and UE::Geometry::FAsyncTaskExecuterWithProgressCancel< TTask >::PollProgress().
IsCultureInvariant()
bool FText::IsCultureInvariant () const nodiscard
IsEmpty()
bool FText::IsEmpty () const nodiscard
Referenced by UE::StateTree::DescHelpers::GetDescriptionForMathOperation(), IAssetReferenceFixer::GetFixerLabel(), UE::Insights::TTreeNodeGroupingByUniqueValue< Type >::GetGroupName(), TSubSectionMixin< ParentSectionClass >::GetSectionToolTip(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), SSegmentedControl< OptionType >::RebuildChildren(), and SNumericEntryBox< NumericType >::SendChangesFromText().
IsEmptyOrWhitespace()
bool FText::IsEmptyOrWhitespace () const nodiscard
IsFromStringTable()
bool FText::IsFromStringTable () const nodiscard
IsInitializedFromString()
bool FText::IsInitializedFromString () const nodiscard
IsNumeric()
bool FText::IsNumeric () const nodiscard
Referenced by SNumericDropDown< NumericType >::ValueTextComitted(), and SGridLineSpacingList::ValueTextCommitted().
IsTransient()
bool FText::IsTransient () const nodiscard
IsWhitespace()
bool FText::IsWhitespace (const TCHAR Char) static nodiscard
Check to see if the given character is considered whitespace by the current culture.
Join() [1/3]
template<typename... ArgTypes> FORCEINLINE FText FText::Join (const FText & Delimiter, ArgTypes... Args) inline static nodiscard
Join an arbitrary list of formattable items together, separated by the given delimiter.
Note
Internally this uses FText::Format with a generated culture invariant format pattern
Parameters
Delimiter The delimiter to insert between the items
Args A variadic list of values to join together
Returns
The joined FText
Definition at line 736 of file Text.h.
References FText(), FORCEINLINE, Join(), MoveTemp(), and TIsConstructible< T, Args >::Value.
Join() [2/3]
FText FText::Join (const FText & Delimiter, const FFormatOrderedArguments & Args) static nodiscard
Join an arbitrary list of formattable values together, separated by the given delimiter.
Note
Internally this uses FText::Format with a generated culture invariant format pattern
Parameters
Delimiter The delimiter to insert between the items
Args An array of formattable values to join together
Returns
The joined FText
References FText().
Referenced by UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorFormatString(), and Join().
Join() [3/3]
FText FText::Join (const FText & Delimiter, const TArray< FText > & Args) static nodiscard
References FText().
operator=() [1/2]
FText & FText::operator= (const FText &) default
References FText().
operator=() [2/2]
FText & FText::operator= (FText && Other)
References FText(), and Other.
operator==()
bool FText::operator== (FIntrusiveUnsetOptionalState) const inline
Definition at line 843 of file Text.h.
References TextData.
PreloadStringTable()
void FText::PreloadStringTable (FName InTableId, const FTextKey & InKey) static
References FText(), Key, and Text.
Rebuild()
void FText::Rebuild () const private
Rebuilds the FText under the current culture if needed.
RegisterTextGenerator() [1/3]
template<typename T> void FText::RegisterTextGenerator () inline static
Registers a standard text generator factory function.
Template Parameters
T the text generator class type
This function can be used if the class has a public static FName member named "TypeID".
Definition at line 789 of file Text.h.
References RegisterTextGenerator().
Referenced by RegisterTextGenerator(), and RegisterTextGenerator().
RegisterTextGenerator() [2/3]
template<typename T> void FText::RegisterTextGenerator (FName TypeID) inline static
Registers a standard text generator factory function.
Template Parameters
T the text generator class type
Parameters
TypeID the name under which to register the factor function
Definition at line 776 of file Text.h.
References CreateTextGenerator(), and RegisterTextGenerator().
RegisterTextGenerator() [3/3]
void FText::RegisterTextGenerator (FName TypeID, FCreateTextGeneratorDelegate FactoryFunction) static
Registers a factory function to be used with serialization of text generators within FText.
Parameters
TypeID the name under which to register the factory function. Must match ITextGenerator::GetTypeID().
FactoryFunction the factory function to create the generator instance
SerializeText() [1/2]
void FText::SerializeText (FArchive & Ar, FText & Value) static private
References FText(), Ar, FArchive, and Value.
SerializeText() [2/2]
void FText::SerializeText (FStructuredArchive::FSlot Slot, FText & Value) static private
References FText(), and Value.
ShouldGatherForLocalization()
bool FText::ShouldGatherForLocalization () const nodiscard
ToLower()
FText FText::ToLower () const nodiscard
Transforms the text to lowercase in a culture correct way.
Note
The returned instance is linked to the original and will be rebuilt if the active culture is changed.
References FText().
ToUpper()
FText FText::ToUpper () const nodiscard
Transforms the text to uppercase in a culture correct way.
Note
The returned instance is linked to the original and will be rebuilt if the active culture is changed.
References FText().
TrimPreceding()
FText FText::TrimPreceding (const FText &) static nodiscard
Removes any whitespace characters from the start of the text.
References FText().
TrimPrecedingAndTrailing()
FText FText::TrimPrecedingAndTrailing (const FText &) static nodiscard
Removes any whitespace characters from the start and end of the text.
References FText().
TrimTrailing()
FText FText::TrimTrailing (const FText &) static nodiscard
Removes any whitespace characters from the end of the text.
References FText().
UE_DEPRECATED()
FText::UE_DEPRECATED (5. 5, "FText::FindText is deprecated as it can no longer find untranslated text. Consider FText::FindTextInLiveTable_Advanced or FText::AsLocalizable_Advanced as a replacement, depending on your use-case.") const &
UnregisterTextGenerator() [1/2]
template<typename T> void FText::UnregisterTextGenerator () inline static
Unregisters a standard text generator factory function.
This function can be used if the class has a public static FName member named "TypeID".
Template Parameters
T the text generator class type
Definition at line 811 of file Text.h.
References UnregisterTextGenerator().
Referenced by UnregisterTextGenerator().
UnregisterTextGenerator() [2/2]
void FText::UnregisterTextGenerator (FName TypeID) static
Unregisters a factory function to be used with serialization of text generators within FText.
Parameters
TypeID the name to remove from registration
See also
RegisterTextGenerator
Friends And Related Symbol Documentation
FArchive
friend class FArchive friend
Definition at line 912 of file Text.h.
References FArchive.
Referenced by FArchive, and SerializeText().
FArchiveFromStructuredArchiveImpl
friend class FArchiveFromStructuredArchiveImpl friend
Definition at line 913 of file Text.h.
References FArchiveFromStructuredArchiveImpl.
Referenced by FArchiveFromStructuredArchiveImpl.
FFormatArgumentValue
friend class FFormatArgumentValue friend
Definition at line 917 of file Text.h.
References FFormatArgumentValue.
Referenced by FFormatArgumentValue.
FJsonArchiveInputFormatter
friend class FJsonArchiveInputFormatter friend
Definition at line 914 of file Text.h.
References FJsonArchiveInputFormatter.
Referenced by FJsonArchiveInputFormatter.
FJsonArchiveOutputFormatter
friend class FJsonArchiveOutputFormatter friend
Definition at line 915 of file Text.h.
References FJsonArchiveOutputFormatter.
Referenced by FJsonArchiveOutputFormatter.
FScopedTextIdentityPreserver
friend class FScopedTextIdentityPreserver friend
Definition at line 922 of file Text.h.
References FScopedTextIdentityPreserver.
Referenced by FScopedTextIdentityPreserver.
FStringTableRegistry
friend class FStringTableRegistry friend
Definition at line 911 of file Text.h.
References FStringTableRegistry.
Referenced by FStringTableRegistry.
FTextCache
friend class FTextCache friend
Definition at line 905 of file Text.h.
References FTextCache.
Referenced by FTextCache.
FTextFormatData
friend class FTextFormatData friend
Definition at line 907 of file Text.h.
References FTextFormatData.
Referenced by FTextFormatData.
FTextFormatter
friend class FTextFormatter friend
Definition at line 906 of file Text.h.
References FTextFormatter.
Referenced by FTextFormatter.
FTextHistory_ArgumentDataFormat
friend class FTextHistory_ArgumentDataFormat friend
Definition at line 919 of file Text.h.
References FTextHistory_ArgumentDataFormat.
Referenced by FTextHistory_ArgumentDataFormat.
FTextHistory_NamedFormat
friend class FTextHistory_NamedFormat friend
Definition at line 918 of file Text.h.
References FTextHistory_NamedFormat.
Referenced by FTextHistory_NamedFormat.
FTextHistory_OrderedFormat
friend class FTextHistory_OrderedFormat friend
Definition at line 920 of file Text.h.
References FTextHistory_OrderedFormat.
Referenced by FTextHistory_OrderedFormat.
FTextHistory_Transform
friend class FTextHistory_Transform friend
Definition at line 921 of file Text.h.
References FTextHistory_Transform.
Referenced by FTextHistory_Transform.
FTextInspector
friend class FTextInspector friend
Definition at line 909 of file Text.h.
References FTextInspector.
Referenced by FTextInspector.
FTextProperty
friend class FTextProperty friend
Definition at line 916 of file Text.h.
References FTextProperty.
Referenced by FTextProperty.
FTextSnapshot
friend class FTextSnapshot friend
Definition at line 908 of file Text.h.
References FTextSnapshot.
Referenced by FTextSnapshot.
FTextStringHelper
friend class FTextStringHelper friend
Definition at line 910 of file Text.h.
References FTextStringHelper.
Referenced by FTextStringHelper.
Field Documentation
bHasIntrusiveUnsetOptionalState
bool FText::bHasIntrusiveUnsetOptionalState = true static constexpr
Definition at line 835 of file Text.h.
Flags
uint32 FText::Flags private
Flags with various information on what sort of FText this is.
Definition at line 902 of file Text.h.
Referenced by FText(), and FText().
Key
const FTextKey& FText::Key
Definition at line 555 of file Text.h.
Referenced by AsLocalizable_Advanced(), AsLocalizable_Advanced(), AsLocalizable_Advanced(), FindTextInLiveTable_Advanced(), and PreloadStringTable().
OutText
const FTextKey FText& FText::OutText
Definition at line 555 of file Text.h.
Referenced by FindTextInLiveTable_Advanced().
SourceString
const FTextKey FText const FString* const FText::SourceString nodiscard
Initial value:
= nullptr)
    {
        return FText::FindTextInLiveTable_Advanced(Namespace, Key, OutText, SourceString);
    }
     1 const FString& ToString() const
Definition at line 555 of file Text.h.
Referenced by FindTextInLiveTable_Advanced().
TextData
TRefCountPtr<ITextData> FText::TextData private
The internal shared data for this FText.
Definition at line 899 of file Text.h.
Referenced by FText(), FText(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/Text.h