Unreal Engine 5.6 C++ API: UE::TMultiUniqueLock< TLockType > Class Template Reference
UE::TMultiUniqueLock< TLockType > Class Template Reference final
#include "MultiUniqueLock.h"
Public Member Functions
TMultiUniqueLock (const TArray< TLockType * > &Locks)
TMultiUniqueLock (TArray< TLockType * > &&Locks)
~TMultiUniqueLock ()
TMultiUniqueLock & operator= (const TArray< TLockType * > &)=delete
TMultiUniqueLock & operator= (TArray< TLockType * > &&)=delete
Private Member Functions
void SortAndLock ()
Private Attributes
TArray< TLockType * > Locks
Detailed Description
template<typename TLockType>
class UE::TMultiUniqueLock< TLockType >
Definition at line 14 of file MultiUniqueLock.h.
Constructor & Destructor Documentation
TMultiUniqueLock() [1/2]
template<typename TLockType> UE::TMultiUniqueLock< TLockType >::TMultiUniqueLock (const TArray< TLockType * > & Locks) inline explicit
Definition at line 17 of file MultiUniqueLock.h.
References Locks, and SortAndLock().
Referenced by operator=(), and operator=().
TMultiUniqueLock() [2/2]
template<typename TLockType> UE::TMultiUniqueLock< TLockType >::TMultiUniqueLock (TArray< TLockType * > && Locks) inline explicit
Definition at line 23 of file MultiUniqueLock.h.
References Locks, MoveTemp(), and SortAndLock().
~TMultiUniqueLock()
template<typename TLockType> UE::TMultiUniqueLock< TLockType >::~TMultiUniqueLock () inline
Definition at line 32 of file MultiUniqueLock.h.
References Locks.
Member Function Documentation
operator=() [1/2]
template<typename TLockType> TMultiUniqueLock & UE::TMultiUniqueLock< TLockType >::operator= (const TArray< TLockType * > &) delete
References TMultiUniqueLock().
operator=() [2/2]
template<typename TLockType> TMultiUniqueLock & UE::TMultiUniqueLock< TLockType >::operator= (TArray< TLockType * > &&) delete
References TMultiUniqueLock().
SortAndLock()
template<typename TLockType> void UE::TMultiUniqueLock< TLockType >::SortAndLock () inline private
Definition at line 41 of file MultiUniqueLock.h.
References Locks, and Algo::Sort().
Referenced by TMultiUniqueLock(), and TMultiUniqueLock().
Field Documentation
Locks
template<typename TLockType> TArray<TLockType*> UE::TMultiUniqueLock< TLockType >::Locks private
Definition at line 50 of file MultiUniqueLock.h.
Referenced by TMultiUniqueLock(), TMultiUniqueLock(), ~TMultiUniqueLock(), and SortAndLock().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Async/MultiUniqueLock.h