Unreal Engine 5.6 C++ API: FSubTrackEditor Class Reference
FSubTrackEditor Class Reference
Tools for subsequences.
#include "SubTrackEditor.h"
Public Member Functions
FSubTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FSubTrackEditor ()
Virtual destructor.
virtual void AddTakesMenu (UMovieSceneSubSection *Section, FMenuBuilder &MenuBuilder)
Generate a menu for takes for this section.
virtual void BuildAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual TSharedPtr< SWidget > BuildOutlinerEditWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
bool CanAddSubSequence (const UMovieSceneSequence &Sequence) const
Check whether the given sequence can be added as a sub-sequence.
virtual bool CanAddTransformKeysForSelectedObjects () const override
Whether or not we can add a transform key for a selected object.
virtual void ChangeTake (UMovieSceneSequence *Sequence)
Switch the selected section's take sequence.
virtual void CreateNewTake (UMovieSceneSubSection *Section)
Create a new take of the given section.
virtual void DuplicateSection (UMovieSceneSubSection *Section)
Duplicate the section into this track.
virtual void EditMetaData (UMovieSceneSubSection *Section)
Edit the section's metadata.
virtual bool GetDefaultExpansionState (UMovieSceneTrack *InTrack) const override
virtual FString GetDefaultSubsequenceDirectory () const
Get the sub sequence directory.
virtual FString GetDefaultSubsequenceName () const
Get the default sub sequence name.
virtual FText GetDisplayName () const override
The display name text to use in the UX.
virtual const FSlateBrush * GetIconBrush () const override
Gets an icon brush for this track editor.
int32 GetPreviousKey (FMovieSceneDoubleChannel &Channel, FFrameNumber Time)
Helper function that finds the previous key.
virtual FString GetSubSectionDisplayName (const UMovieSceneSubSection *Section) const
Get the display name for the sub section.
virtual FName GetSubTrackBrushName () const
Get the brush used for the sub track editor.
virtual TSubclassOf< UMovieSceneSubTrack > GetSubTrackClass () const
Get the UMovieSceneSubTrack class.
virtual FText GetSubTrackName () const
Get the name of the sub track.
virtual FText GetSubTrackToolTip () const
Get the tooltip for this sub track editor.
FTransform GetTransformOriginDataForSubSection (const UMovieSceneSubSection *SubSection) const
Query's the channel data directly (does not take parent transforms into account).
virtual bool HandleAssetAdded (UObject *Asset, const FGuid &TargetObjectGuid) override
Called when an asset is dropped into Sequencer.
virtual bool HasTransformKeyBindings () const override
virtual void InsertSection (UMovieSceneTrack *Track)
Insert sequence into this track.
virtual bool IsResizable (UMovieSceneTrack *InTrack) const override
virtual TSharedRef< ISequencerSection > MakeSectionInterface (UMovieSceneSection &SectionObject, UMovieSceneTrack &Track, FGuid ObjectBinding) override
Called to generate a section layout for a particular section.
virtual void OnAddTransformKeysForSelectedObjects (EMovieSceneTransformChannel Channel) override
Adds transform tracks and keys to the selected objects in the level.
virtual bool OnAllowDrop (const FDragDropEvent &DragDropEvent, FSequencerDragDropParams &DragDropParams) override
Called when attempting to drop an asset directly onto a track.
virtual FReply OnDrop (const FDragDropEvent &DragDropEvent, const FSequencerDragDropParams &DragDropParams) override
Called when an asset is dropped directly onto a track.
virtual void OnInitialize () override
Called when the instance of this track editor is initialized.
virtual void OnRelease () override
Called when the instance of this track editor is released.
virtual void ProcessKeyOperation (FFrameNumber InKeyTime, const UE::Sequencer::FKeyOperation &Operation, ISequencer &InSequencer, TArray< UE::Sequencer::FAddKeyResult > *OutResults=nullptr) override
Add keys for the following sections based on an external value if possible.
void ResetSectionPreviews ()
Called when sequence playback updates to revert preview data on modified secitons.
void ResetSectionPreviews (const FMovieSceneChannelMetaData *MetaData, UMovieSceneSection *InSection)
void ResetSectionPreviews (FMovieSceneSequenceIDRef IDRef)
virtual void Resize (float NewSize, UMovieSceneTrack *InTrack) override
Resize this track.
virtual bool SupportsSequence (UMovieSceneSequence *InSequence) const override
Returns whether a sequence is supported by this tool.
virtual bool SupportsType (TSubclassOf< UMovieSceneTrack > Type) const override
Returns whether a track class is supported by this tool.
double UnwindChannel (const double &OldValue, double NewValue)
Helper function to fix-up Euler rotations if they would go over 180 degrees due to interpolation.
void UpdateActiveMode ()
Update the current active edit mode when a subtrack or section is selected.
void UpdateOrigin (FVector InPosition, FRotator InRotation)
Called when the editor mode has made external changes to the origin data.
Public Member Functions inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
FKeyframeTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
~FKeyframeTrackEditor ()
Virtual destructor.
virtual void BuildTrackContextMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the context menu for the track.
Public Member Functions inherited from FMovieSceneTrackEditor
FMovieSceneTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FMovieSceneTrackEditor ()
Destructor.
virtual UMovieSceneTrack * AddTrack (UMovieScene *FocusedMovieScene, const FGuid &ObjectHandle, TSubclassOf< class UMovieSceneTrack > TrackClass, FName UniqueTypeName) override
Add a new track to the sequence.
void AnimatablePropertyChanged (FOnKeyProperty OnKeyProperty)
virtual void BindCommands (TSharedRef< FUICommandList > SequencerCommandBindings) override
Allows the track editors to bind commands.
virtual void BuildObjectBindingColumnWidgets (TFunctionRef< TSharedRef< SHorizontalBox >()> GetEditBox, const UE::Sequencer::TViewModelPtr< UE::Sequencer::FObjectBindingModel > &ObjectBinding, const UE::Sequencer::FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Build a column widget for the specified object binding on the outliner.
virtual void BuildObjectBindingTrackMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass) override
Builds up the object binding track menu for the outliner.
virtual TSharedPtr< SWidget > BuildOutlinerColumnWidget (const FBuildColumnWidgetParams &Params, const FName &ColumnName) override
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditColumnWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the edit column for outliner nodes which represent tracks which are edited by this editor.
virtual void BuildPinnedAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildTrackSidebarMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the sidebar menu for the track.
FFindOrCreateHandleResult FindOrCreateHandleToObject (UObject *Object, bool bCreateHandleIfMissing=true, const FName &CreatedFolderName=NAME_None)
template<typename TrackClass>
FFindOrCreateRootTrackResult< TrackClass > FindOrCreateRootTrack ()
Find or add a track of the specified type in the focused movie scene.
FFindOrCreateTrackResult FindOrCreateTrackForObject (const FGuid &ObjectHandle, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName=NAME_None, bool bCreateTrackIfMissing=true)
UMovieSceneSequence * GetMovieSceneSequence () const
TSharedPtr< ISequencer > GetSequencer () const
FFrameNumber GetTimeForKey ()
virtual void Tick (float DeltaTime) override
Ticks this tool.
void UpdatePlaybackRange ()
Public Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedRef< FMovieSceneTrackEditor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneTrackEditor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from ISequencerTrackEditor
virtual ~ISequencerTrackEditor ()
Virtual destructor.
virtual void BuildObjectBindingContextMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Builds up the object binding cpmtext menu for the outliner.
virtual void BuildObjectBindingEditButtons (TSharedPtr< SHorizontalBox > EditBox, const FGuid &ObjectBinding, const UClass *ObjectClass)
Deprecated in principle, not practice (due to difficulty deprecating public virtual functions).
virtual void ExtendObjectBindingTrackMenu (TSharedRef< FExtender > Extender, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Extend the object binding track menu for the specified binding and class.
virtual bool HasTransformKeyOverridePriority () const
If true this track has priority when setting transform keys and should be the only one to set them.
virtual void ObjectImplicitlyAdded (UObject *InObject)
Handle this object being implicitly added.
virtual void ObjectImplicitlyRemoved (UObject *InObject)
Handle this object being implicitly removed.
virtual void OnPostSaveWorld (UWorld *World)
Called after the sequencer has re-evaluated all objects after saving the level.
virtual void OnPreSaveWorld (UWorld *World)
Called before the sequencer restores pre-animated state on all objects before saving the level.
Static Public Member Functions
static TSharedRef< ISequencerTrackEditor > CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer)
Creates an instance of this class.
Static Public Member Functions inherited from FMovieSceneTrackEditor
static void BeginKeying (FFrameNumber InFrameNumber)
Initiate keying when there is more than one object to key (ie.
static void EndKeying ()
Protected Member Functions
virtual bool CanHandleAssetAdded (UMovieSceneSequence *Sequence) const
Whether to handle this asset being dropped onto the sequence as opposed to a specific track.
UMovieSceneSubTrack * FindOrCreateSubTrack (UMovieScene *MovieScene, UMovieSceneTrack *Track) const
Find or create a sub track.
virtual void GetSupportedSequenceClassPaths (TArray< FTopLevelAssetPath > &OutClassPaths) const
Get the list of supported sequence class paths.
TSharedRef< SWidget > HandleAddSubSequenceComboButtonGetMenuContent (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel)
Callback for generating the menu of the "Add Sequence" combo button.
virtual bool HandleAddSubTrackMenuEntryCanExecute () const
Callback for determining whether the "Add Subsequence" menu entry can execute.
virtual void HandleAddSubTrackMenuEntryExecute ()
Callback for executing the "Add Subsequence" menu entry.
UE_DEPRECATED (5.3, "CreateNewTrack has been deprecated, please implement GetSubTrackClass") virtual UMovieSceneSubTrack *CreateNewTrack(UMovieScene *MovieScene) const
Protected Member Functions inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
FKeyPropertyResult AddKeysToObjects (TArrayView< UObject *const > ObjectsToKey, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(UMovieSceneSubTrack *)> OnInitializeNewTrack, const GenerateKeysCallback &OnGenerateKeys)
FKeyPropertyResult AddKeysToSection (UMovieSceneSection *Section, FFrameNumber KeyTime, const FGeneratedTrackKeys &Keys, ESequencerKeyMode KeyMode, EKeyFrameTrackEditorSetDefault SetDefault=EKeyFrameTrackEditorSetDefault::SetDefault)
virtual bool ModifyGeneratedKeysByCurrentAndWeight (UObject *Object, UMovieSceneTrack *Track, UMovieSceneSection *SectionToKey, FFrameNumber Time, FGeneratedTrackKeys &GeneratedTotalKeys, float Weight) const
Scale the generated keys by the the current value and the weight.
Protected Member Functions inherited from FMovieSceneTrackEditor
UMovieScene * GetFocusedMovieScene () const
Gets the currently focused movie scene, if any.
Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
FKeyPropertyResult AddKeyInternal (FFrameNumber KeyTime, UMovieSceneSequence *InMovieSceneSequence, UMovieSceneTrack *InTrack, int32 RowIndex)
Delegate for AnimatablePropertyChanged in AddKey.
void GetOriginKeys (const FVector &CurrentPosition, const FRotator &CurrentRotation, EMovieSceneTransformChannel ChannelsToKey, UMovieSceneSection *Section, FGeneratedTrackKeys &OutGeneratedKeys)
Helper for creating new keys.
void GetSectionsToKey (TArray< UMovieSceneSubSection * > &OutSectionsToKey) const
Helper for getting the sections that should be keyed.
void HandleAddSubSequenceComboButtonMenuEntryEnterPressed (const TArray< FAssetData > &AssetData, UMovieSceneTrack *InTrack)
Callback for executing a menu entry in the "Add Sequence" combo button when enter pressed.
void HandleAddSubSequenceComboButtonMenuEntryExecute (const FAssetData &AssetData, UMovieSceneTrack *InTrack)
Callback for executing a menu entry in the "Add Sequence" combo button.
FKeyPropertyResult HandleSequenceAdded (FFrameNumber KeyTime, UMovieSceneSequence *Sequence, UMovieSceneTrack *Track, int32 RowIndex)
Callback for AnimatablePropertyChanged in HandleAssetAdded.
void ProcessKeyOperationInternal (TArrayView< const UE::Sequencer::FKeySectionOperation > SectionsToKey, ISequencer &Sequencer, FFrameNumber KeyTime, TArray< UE::Sequencer::FAddKeyResult > *OutResults=nullptr)
Handles adding keys to section.
Private Attributes
TArray< UMovieSceneSubSection * > SectionsWithPreviews
Sections this editor has added preview data to for keyframing.
Additional Inherited Members
Public Types inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
using GenerateKeysCallback
Static Protected Member Functions inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
static bool CanAutoKeySection (UMovieSceneSection *Section, FFrameNumber Time)
Check whether we can autokey the specified section at the specified time.
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Tools for subsequences.
Definition at line 27 of file SubTrackEditor.h.
Constructor & Destructor Documentation
FSubTrackEditor()
FSubTrackEditor::FSubTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
Parameters
InSequencer The sequencer instance to be used by this tool
~FSubTrackEditor()
virtual FSubTrackEditor::~FSubTrackEditor () inline virtual
Virtual destructor.
Definition at line 40 of file SubTrackEditor.h.
Member Function Documentation
AddKeyInternal()
FKeyPropertyResult FSubTrackEditor::AddKeyInternal (FFrameNumber KeyTime, UMovieSceneSequence * InMovieSceneSequence, UMovieSceneTrack * InTrack, int32 RowIndex) private
Delegate for AnimatablePropertyChanged in AddKey.
References AddKeyInternal().
Referenced by AddKeyInternal().
AddTakesMenu()
virtual void FSubTrackEditor::AddTakesMenu (UMovieSceneSubSection * Section, FMenuBuilder & MenuBuilder) virtual
Generate a menu for takes for this section.
BuildAddTrackMenu()
virtual void FSubTrackEditor::BuildAddTrackMenu (FMenuBuilder & MenuBuilder) override virtual
Builds up the sequencer's "Add Track" menu.
Parameters
MenuBuilder The menu builder to change.
Reimplemented from FMovieSceneTrackEditor.
BuildOutlinerEditWidget()
virtual TSharedPtr< SWidget > FSubTrackEditor::BuildOutlinerEditWidget (const FGuid & ObjectBinding, UMovieSceneTrack * Track, const FBuildEditWidgetParams & Params) override virtual
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
Parameters
ObjectBinding The object binding associated with the track being edited by this editor.
Track The track being edited by this editor.
Params Parameter struct containing data relevant to the edit widget
Returns
The the widget to display in the outliner, or an empty shared ptr if not widget is to be displayed.
Reimplemented from FMovieSceneTrackEditor.
References Params.
CanAddSubSequence()
bool FSubTrackEditor::CanAddSubSequence (const UMovieSceneSequence & Sequence) const
Check whether the given sequence can be added as a sub-sequence.
The purpose of this method is to disallow circular references between sub-sequences in the focused movie scene.
Parameters
Sequence The sequence to check.
Returns
true if the sequence can be added as a sub-sequence, false otherwise.
CanAddTransformKeysForSelectedObjects()
virtual bool FSubTrackEditor::CanAddTransformKeysForSelectedObjects () const override virtual
Whether or not we can add a transform key for a selected object.
Returns
Returns true if we can.
Reimplemented from ISequencerTrackEditor.
CanHandleAssetAdded()
virtual bool FSubTrackEditor::CanHandleAssetAdded (UMovieSceneSequence * Sequence) const protected virtual
Whether to handle this asset being dropped onto the sequence as opposed to a specific track.
Reimplemented in FCinematicShotTrackEditor.
ChangeTake()
virtual void FSubTrackEditor::ChangeTake (UMovieSceneSequence * Sequence) virtual
Switch the selected section's take sequence.
CreateNewTake()
virtual void FSubTrackEditor::CreateNewTake (UMovieSceneSubSection * Section) virtual
Create a new take of the given section.
CreateTrackEditor()
TSharedRef< ISequencerTrackEditor > FSubTrackEditor::CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer) static
Creates an instance of this class.
Called by a sequencer
Parameters
OwningSequencer The sequencer instance to be used by this tool
Returns
The new instance of this class
DuplicateSection()
virtual void FSubTrackEditor::DuplicateSection (UMovieSceneSubSection * Section) virtual
Duplicate the section into this track.
EditMetaData()
virtual void FSubTrackEditor::EditMetaData (UMovieSceneSubSection * Section) virtual
Edit the section's metadata.
FindOrCreateSubTrack()
UMovieSceneSubTrack * FSubTrackEditor::FindOrCreateSubTrack (UMovieScene * MovieScene, UMovieSceneTrack * Track) const protected
Find or create a sub track.
If the given track is a subtrack, it will be returned.
References FindOrCreateSubTrack().
Referenced by FindOrCreateSubTrack().
GetDefaultExpansionState()
virtual bool FSubTrackEditor::GetDefaultExpansionState (UMovieSceneTrack * InTrack) const override virtual
Returns
The default expansion state of this track
Reimplemented from ISequencerTrackEditor.
GetDefaultSubsequenceDirectory()
virtual FString FSubTrackEditor::GetDefaultSubsequenceDirectory () const virtual
Get the sub sequence directory.
Reimplemented in FCinematicShotTrackEditor.
GetDefaultSubsequenceName()
virtual FString FSubTrackEditor::GetDefaultSubsequenceName () const virtual
Get the default sub sequence name.
Reimplemented in FCinematicShotTrackEditor.
GetDisplayName()
virtual FText FSubTrackEditor::GetDisplayName () const override virtual
The display name text to use in the UX.
Currently only used for sorting.
Reimplemented from FKeyframeTrackEditor< UMovieSceneSubTrack >.
Reimplemented in FCinematicShotTrackEditor.
GetIconBrush()
virtual const FSlateBrush * FSubTrackEditor::GetIconBrush () const override virtual
Gets an icon brush for this track editor.
Reimplemented from ISequencerTrackEditor.
GetOriginKeys()
void FSubTrackEditor::GetOriginKeys (const FVector & CurrentPosition, const FRotator & CurrentRotation, EMovieSceneTransformChannel ChannelsToKey, UMovieSceneSection * Section, FGeneratedTrackKeys & OutGeneratedKeys) private
Helper for creating new keys.
References FVector, and GetOriginKeys().
Referenced by GetOriginKeys().
GetPreviousKey()
int32 FSubTrackEditor::GetPreviousKey (FMovieSceneDoubleChannel & Channel, FFrameNumber Time)
Helper function that finds the previous key.
Used to "unwind" rotators
References Time.
GetSectionsToKey()
void FSubTrackEditor::GetSectionsToKey (TArray< UMovieSceneSubSection * > & OutSectionsToKey) const private
Helper for getting the sections that should be keyed.
References GetSectionsToKey().
Referenced by GetSectionsToKey().
GetSubSectionDisplayName()
virtual FString FSubTrackEditor::GetSubSectionDisplayName (const UMovieSceneSubSection * Section) const virtual
Get the display name for the sub section.
Reimplemented in FCinematicShotTrackEditor.
GetSubTrackBrushName()
virtual FName FSubTrackEditor::GetSubTrackBrushName () const virtual
Get the brush used for the sub track editor.
Reimplemented in FCinematicShotTrackEditor.
GetSubTrackClass()
virtual TSubclassOf< UMovieSceneSubTrack > FSubTrackEditor::GetSubTrackClass () const virtual
Get the UMovieSceneSubTrack class.
Reimplemented in FCinematicShotTrackEditor.
GetSubTrackName()
virtual FText FSubTrackEditor::GetSubTrackName () const virtual
Get the name of the sub track.
Reimplemented in FCinematicShotTrackEditor.
GetSubTrackToolTip()
virtual FText FSubTrackEditor::GetSubTrackToolTip () const virtual
Get the tooltip for this sub track editor.
Reimplemented in FCinematicShotTrackEditor.
GetSupportedSequenceClassPaths()
virtual void FSubTrackEditor::GetSupportedSequenceClassPaths (TArray< FTopLevelAssetPath > & OutClassPaths) const protected virtual
Get the list of supported sequence class paths.
GetTransformOriginDataForSubSection()
FTransform FSubTrackEditor::GetTransformOriginDataForSubSection (const UMovieSceneSubSection * SubSection) const
Query's the channel data directly (does not take parent transforms into account).
Used for setting keyframes.
HandleAddSubSequenceComboButtonGetMenuContent()
TSharedRef< SWidget > FSubTrackEditor::HandleAddSubSequenceComboButtonGetMenuContent (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel) protected
Callback for generating the menu of the "Add Sequence" combo button.
References HandleAddSubSequenceComboButtonGetMenuContent().
Referenced by HandleAddSubSequenceComboButtonGetMenuContent().
HandleAddSubSequenceComboButtonMenuEntryEnterPressed()
void FSubTrackEditor::HandleAddSubSequenceComboButtonMenuEntryEnterPressed (const TArray< FAssetData > & AssetData, UMovieSceneTrack * InTrack) private
Callback for executing a menu entry in the "Add Sequence" combo button when enter pressed.
References HandleAddSubSequenceComboButtonMenuEntryEnterPressed().
Referenced by HandleAddSubSequenceComboButtonMenuEntryEnterPressed().
HandleAddSubSequenceComboButtonMenuEntryExecute()
void FSubTrackEditor::HandleAddSubSequenceComboButtonMenuEntryExecute (const FAssetData & AssetData, UMovieSceneTrack * InTrack) private
Callback for executing a menu entry in the "Add Sequence" combo button.
References HandleAddSubSequenceComboButtonMenuEntryExecute().
Referenced by HandleAddSubSequenceComboButtonMenuEntryExecute().
HandleAddSubTrackMenuEntryCanExecute()
virtual bool FSubTrackEditor::HandleAddSubTrackMenuEntryCanExecute () const inline protected virtual
Callback for determining whether the "Add Subsequence" menu entry can execute.
Reimplemented in FCinematicShotTrackEditor.
Definition at line 156 of file SubTrackEditor.h.
HandleAddSubTrackMenuEntryExecute()
virtual void FSubTrackEditor::HandleAddSubTrackMenuEntryExecute () protected virtual
Callback for executing the "Add Subsequence" menu entry.
HandleAssetAdded()
virtual bool FSubTrackEditor::HandleAssetAdded (UObject * Asset, const FGuid & TargetObjectGuid) override virtual
Called when an asset is dropped into Sequencer.
Can potentially consume the asset so it doesn't get added as a spawnable.
Parameters
Asset The asset that is dropped in.
TargetObjectGuid The object guid this asset is dropped onto, if applicable.
Returns
true if we want to consume this asset, false otherwise.
Reimplemented from FMovieSceneTrackEditor.
References Asset.
HandleSequenceAdded()
FKeyPropertyResult FSubTrackEditor::HandleSequenceAdded (FFrameNumber KeyTime, UMovieSceneSequence * Sequence, UMovieSceneTrack * Track, int32 RowIndex) private
Callback for AnimatablePropertyChanged in HandleAssetAdded.
References HandleSequenceAdded().
Referenced by HandleSequenceAdded().
HasTransformKeyBindings()
virtual bool FSubTrackEditor::HasTransformKeyBindings () const inline override virtual
Returns
If it supports supports transform key bindings for setting keys.
Reimplemented from ISequencerTrackEditor.
Definition at line 69 of file SubTrackEditor.h.
InsertSection()
virtual void FSubTrackEditor::InsertSection (UMovieSceneTrack * Track) virtual
Insert sequence into this track.
IsResizable()
virtual bool FSubTrackEditor::IsResizable (UMovieSceneTrack * InTrack) const override virtual
Returns
Whether this track handles resize events
Reimplemented from ISequencerTrackEditor.
MakeSectionInterface()
virtual TSharedRef< ISequencerSection > FSubTrackEditor::MakeSectionInterface (UMovieSceneSection & SectionObject, UMovieSceneTrack & Track, FGuid ObjectBinding) override virtual
Called to generate a section layout for a particular section.
Parameters
SectionObject The section to make UI for.
Track The track that owns the section.
ObjectBinding the object binding for the track that owns the section, if there is one.
Reimplemented from FMovieSceneTrackEditor.
Reimplemented in FCinematicShotTrackEditor.
OnAddTransformKeysForSelectedObjects()
virtual void FSubTrackEditor::OnAddTransformKeysForSelectedObjects (EMovieSceneTransformChannel Channel) override virtual
Adds transform tracks and keys to the selected objects in the level.
Parameters
Channel The transform channel to add keys for.
Reimplemented from ISequencerTrackEditor.
OnAllowDrop()
virtual bool FSubTrackEditor::OnAllowDrop (const FDragDropEvent & DragDropEvent, FSequencerDragDropParams & DragDropParams) override virtual
Called when attempting to drop an asset directly onto a track.
Parameters
DragDropEvent The drag drop event.
DragDropParams The drag drop parameters.
Returns
Whether the drop event can be handled.
Reimplemented from FMovieSceneTrackEditor.
OnDrop()
virtual FReply FSubTrackEditor::OnDrop (const FDragDropEvent & DragDropEvent, const FSequencerDragDropParams & DragDropParams) override virtual
Called when an asset is dropped directly onto a track.
Parameters
DragDropEvent The drag drop event.
DragDropParams The drag drop parameters.
Returns
Whether the drop event was handled.
Reimplemented from FMovieSceneTrackEditor.
OnInitialize()
virtual void FSubTrackEditor::OnInitialize () override virtual
Called when the instance of this track editor is initialized.
Reimplemented from FMovieSceneTrackEditor.
OnRelease()
virtual void FSubTrackEditor::OnRelease () override virtual
Called when the instance of this track editor is released.
Reimplemented from FMovieSceneTrackEditor.
ProcessKeyOperation()
virtual void FSubTrackEditor::ProcessKeyOperation (FFrameNumber InKeyTime, const UE::Sequencer::FKeyOperation & Operation, ISequencer & InSequencer, TArray< UE::Sequencer::FAddKeyResult > * OutResults = nullptr) override virtual
Add keys for the following sections based on an external value if possible.
Parameters
InKeyTime The time at which to add keys
Operation Structure containing all the sections and channels to key
InSequencer The sequencer UI that is applying the key operation
OutResults The key handles that were added with this operation
Reimplemented from ISequencerTrackEditor.
ProcessKeyOperationInternal()
void FSubTrackEditor::ProcessKeyOperationInternal (TArrayView< const UE::Sequencer::FKeySectionOperation > SectionsToKey, ISequencer & Sequencer, FFrameNumber KeyTime, TArray< UE::Sequencer::FAddKeyResult > * OutResults = nullptr) private
Handles adding keys to section.
References ProcessKeyOperationInternal().
Referenced by ProcessKeyOperationInternal().
ResetSectionPreviews() [1/3]
void FSubTrackEditor::ResetSectionPreviews ()
Called when sequence playback updates to revert preview data on modified secitons.
ResetSectionPreviews() [2/3]
void FSubTrackEditor::ResetSectionPreviews (const FMovieSceneChannelMetaData * MetaData, UMovieSceneSection * InSection) inline
Definition at line 136 of file SubTrackEditor.h.
References MetaData, and ResetSectionPreviews().
Referenced by ResetSectionPreviews().
ResetSectionPreviews() [3/3]
void FSubTrackEditor::ResetSectionPreviews (FMovieSceneSequenceIDRef IDRef) inline
Definition at line 135 of file SubTrackEditor.h.
References ResetSectionPreviews().
Referenced by ResetSectionPreviews().
Resize()
virtual void FSubTrackEditor::Resize (float NewSize, UMovieSceneTrack * InTrack) override virtual
Resize this track.
Reimplemented from ISequencerTrackEditor.
SupportsSequence()
virtual bool FSubTrackEditor::SupportsSequence (UMovieSceneSequence * InSequence) const override virtual
Returns whether a sequence is supported by this tool.
Parameters
InSequence The sequence that could be supported.
Returns
true if the type is supported.
Reimplemented from FMovieSceneTrackEditor.
Reimplemented in FCinematicShotTrackEditor.
SupportsType()
virtual bool FSubTrackEditor::SupportsType (TSubclassOf< UMovieSceneTrack > Type) const override virtual
Returns whether a track class is supported by this tool.
Parameters
TrackClass The track class that could be supported.
Returns
true if the type is supported.
Reimplemented from FKeyframeTrackEditor< UMovieSceneSubTrack >.
UE_DEPRECATED()
FSubTrackEditor::UE_DEPRECATED (5. 3, "CreateNewTrack has been deprecated, please implement GetSubTrackClass") const protected
UnwindChannel()
double FSubTrackEditor::UnwindChannel (const double & OldValue, double NewValue)
Helper function to fix-up Euler rotations if they would go over 180 degrees due to interpolation.
UpdateActiveMode()
void FSubTrackEditor::UpdateActiveMode ()
Update the current active edit mode when a subtrack or section is selected.
UpdateOrigin()
void FSubTrackEditor::UpdateOrigin (FVector InPosition, FRotator InRotation)
Called when the editor mode has made external changes to the origin data.
References FVector.
Field Documentation
SectionsWithPreviews
TArray<UMovieSceneSubSection*> FSubTrackEditor::SectionsWithPreviews private
Sections this editor has added preview data to for keyframing.
Used to revert data when other edits are made, before adding a key
Definition at line 194 of file SubTrackEditor.h.
The documentation for this class was generated from the following file:
Editor/MovieSceneTools/Public/TrackEditors/SubTrackEditor.h