Unreal Engine 5.6 C++ API: FLambdaMeshSculptBrushOpFactory Class Reference
FLambdaMeshSculptBrushOpFactory Class Reference
#include "MeshBrushOpBase.h"
Public Member Functions
FLambdaMeshSculptBrushOpFactory ()
FLambdaMeshSculptBrushOpFactory (TUniqueFunction< TUniquePtr< FMeshSculptBrushOp >(void)> BuildFuncIn)
virtual TUniquePtr< FMeshSculptBrushOp > Build () override
Public Member Functions inherited from FMeshSculptBrushOpFactory
virtual ~FMeshSculptBrushOpFactory ()
Data Fields
TUniqueFunction< TUniquePtr< FMeshSculptBrushOp >(void)> BuildFunc
Detailed Description
Definition at line 287 of file MeshBrushOpBase.h.
Constructor & Destructor Documentation
FLambdaMeshSculptBrushOpFactory() [1/2]
FLambdaMeshSculptBrushOpFactory::FLambdaMeshSculptBrushOpFactory () inline
Definition at line 292 of file MeshBrushOpBase.h.
FLambdaMeshSculptBrushOpFactory() [2/2]
FLambdaMeshSculptBrushOpFactory::FLambdaMeshSculptBrushOpFactory (TUniqueFunction< TUniquePtr< FMeshSculptBrushOp >(void)> BuildFuncIn) inline
Definition at line 296 of file MeshBrushOpBase.h.
References BuildFunc, and MoveTemp().
Member Function Documentation
Build()
virtual TUniquePtr< FMeshSculptBrushOp > FLambdaMeshSculptBrushOpFactory::Build () inline override virtual
Implements FMeshSculptBrushOpFactory.
Definition at line 301 of file MeshBrushOpBase.h.
References BuildFunc.
Field Documentation
BuildFunc
TUniqueFunction<TUniquePtr<FMeshSculptBrushOp>(void)> FLambdaMeshSculptBrushOpFactory::BuildFunc
Definition at line 290 of file MeshBrushOpBase.h.
Referenced by FLambdaMeshSculptBrushOpFactory(), and Build().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/MeshModelingTools/Public/Sculpting/MeshBrushOpBase.h