Unreal Engine 5.6 C++ API: FUObjectArray Class Reference
FUObjectArray Class Reference
#include "UObjectArray.h"
Data Structures
class FUObjectCreateListener
Base class for UObjectBase create class listeners.
class FUObjectDeleteListener
Base class for UObjectBase delete class listeners.
class TIterator
Low level iterator.
Public Types
enum ESerialNumberConstants { START_SERIAL_NUMBER = 1000 }
Public Member Functions
FUObjectArray ()
Constructor, initializes to no permanent object pool.
void AddUObjectCreateListener (FUObjectCreateListener *Listener)
Adds a new listener for object creation.
void AddUObjectDeleteListener (FUObjectDeleteListener *Listener)
Adds a new listener for object deletion.
void AllocateObjectPool (int32 MaxUObjects, int32 MaxObjectsNotConsideredByGC, bool bPreAllocateObjectArray)
Allocates and initializes the permanent object pool.
int32 AllocateSerialNumber (int32 Index)
Given a UObject index return the serial number.
void AllocateUObjectIndex (class UObjectBase *Object, EInternalObjectFlags InitialFlags, int32 AlreadyAllocatedIndex=-1, int32 SerialNumber=0, FRemoteObjectId RemoteId=FRemoteObjectId())
Adds a uobject to the global array which is used for uobject iteration.
void CloseDisregardForGC ()
After the initial load, this closes the disregard pool so that new object are GC-able.
void DisableDisregardForGC ()
Disables the disregard for GC optimization.
bool DisregardForGCEnabled () const
indicates if the disregard for GC optimization is active
void DumpUObjectCountsToLog () const
void FreeUObjectIndex (class UObjectBase *Object)
Returns a UObject index top to the global uobject array.
SIZE_T GetAllocatedSize () const
SIZE_T GetDeleteListenersAllocatedSize (int32 *OutNumListeners=nullptr) const
FORCEINLINE int32 GetFirstGCIndex () const
Returns the index of the first object outside of the disregard for GC pool.
int32 GetObjectArrayCapacity () const
Returns the estimated number of object indices available for allocation.
int32 GetObjectArrayEstimatedAvailable () const
Returns the estimated number of object indices available for allocation.
FORCEINLINE int32 GetObjectArrayNum () const
Returns the size of the global UObject array, some of these might be unused.
int32 GetObjectArrayNumMinusAvailable () const
Returns the number of actual object indices that are claimed (the total size of the global object array minus the number of available object array elements.
FORCEINLINE int32 GetObjectArrayNumMinusPermanent () const
Returns the size of the global UObject array minus the number of permanent objects.
FORCEINLINE int32 GetObjectArrayNumPermanent () const
Returns the number of permanent objects.
TUObjectArray & GetObjectItemArrayUnsafe ()
INTERNAL USE ONLY: gets the internal FUObjectItem array.
const TUObjectArray & GetObjectItemArrayUnsafe () const
FORCEINLINE int32 GetSerialNumber (int32 Index)
Given a UObject index return the serial number.
FORCEINLINE FUObjectItem * IndexToObject (int32 Index)
Returns the UObject corresponding to index.
FORCEINLINE FUObjectItem * IndexToObject (int32 Index, bool bEvenIfGarbage)
FORCEINLINE FUObjectItem * IndexToObjectUnsafeForGC (int32 Index)
FORCEINLINE FUObjectItem * IndexToValidObject (int32 Index, bool bEvenIfGarbage)
FORCEINLINE bool IsDisregardForGC (const class UObjectBase *Object)
Returns true if this object is "disregard for GC"...same results as the legacy RF_DisregardForGC flag.
bool IsOpenForDisregardForGC () const
Returns true if the disregard for GC pool is open.
FORCEINLINE bool IsStale (FUObjectItem *ObjectItem, bool bIncludingGarbage)
FORCEINLINE bool IsStale (int32 Index, bool bIncludingGarbage)
bool IsValid (const UObjectBase *Object) const
Checks if a UObject pointer is valid.
FORCEINLINE bool IsValid (FUObjectItem *ObjectItem, bool bEvenIfGarbage)
FORCEINLINE bool IsValid (int32 Index, bool bEvenIfGarbage)
FORCEINLINE bool IsValidIndex (const UObjectBase *Object) const
Checks if the object index is valid.
void LockInternalArray () const
Locks the internal object array mutex.
FORCEINLINE int32 ObjectToIndex (const class UObjectBase *Object) const
Returns the index of a UObject.
FORCEINLINE FUObjectItem * ObjectToObjectItem (const UObjectBase *Object)
void OpenDisregardForGC ()
If there's enough slack in the disregard pool, we can re-open it and keep adding objects to it.
void RemoveObjectFromDeleteListeners (UObjectBase *Object)
Removes an object from delete listeners.
void RemoveUObjectCreateListener (FUObjectCreateListener *Listener)
Removes a listener for object creation.
void RemoveUObjectDeleteListener (FUObjectDeleteListener *Listener)
Removes a listener for object deletion.
void ShutdownUObjectArray ()
Clears some internal arrays to get rid of false memory leaks.
void UnlockInternalArray () const
Unlocks the internal object array mutex.
Private Types
typedef FChunkedFixedUObjectArray TUObjectArray
Private Member Functions
void ResetSerialNumber (UObjectBase *Object)
Reset the serial number from the game thread to invalidate all weak object pointers to it.
Private Attributes
bool bShouldRecycleObjectIndices = true
If set to false object indices won't be recycled to the global pool and can be explicitly reused when creating new objects.
int32 MaxObjectsNotConsideredByGC
Maximum number of objects in the disregard for GC Pool.
TArray< int32 > ObjAvailableList
Available object indices.
int32 ObjFirstGCIndex
First index into objects array taken into account for GC.
int32 ObjLastNonGCIndex
Index pointing to last object created in range disregarded for GC.
TUObjectArray ObjObjects
Array of all live objects.
FTransactionallySafeCriticalSection ObjObjectsCritical
Synchronization object for all live objects.
bool OpenForDisregardForGC
If true this is the intial load and we should load objects int the disregarded for GC range.
FThreadSafeCounter PrimarySerialNumber
Current primary serial number.
TArray< FUObjectCreateListener * > UObjectCreateListeners
Array of things to notify when a UObjectBase is created.
TArray< FUObjectDeleteListener * > UObjectDeleteListeners
Array of things to notify when a UObjectBase is destroyed.
Friends
UObject * StaticAllocateObject (const UClass *Class, UObject *InOuter, FName Name, EObjectFlags SetFlags, EInternalObjectFlags InternalSetFlags=EInternalObjectFlags::None, bool bCanReuseSubobjects=false, bool *bOutReusedSubobject=nullptr, UPackage *ExternalPackage=nullptr, int32 SerialNumber=0, FRemoteObjectId RemoteId=FRemoteObjectId(), class FGCReconstructionGuard *GCGuard=nullptr)
Create a new instance of an object or replace an existing object.
class UObject
Detailed Description
Definition at line 885 of file UObjectArray.h.
Member Typedef Documentation
TUObjectArray
typedef FChunkedFixedUObjectArray FUObjectArray::TUObjectArray private
Definition at line 1405 of file UObjectArray.h.
Member Enumeration Documentation
ESerialNumberConstants
enum FUObjectArray::ESerialNumberConstants
Enumerator
START_SERIAL_NUMBER
Definition at line 900 of file UObjectArray.h.
Constructor & Destructor Documentation
FUObjectArray()
FUObjectArray::FUObjectArray ()
Constructor, initializes to no permanent object pool.
Referenced by FUObjectArray::TIterator::TIterator(), and FUObjectArray::TIterator::GetIteratedArray().
Member Function Documentation
AddUObjectCreateListener()
void FUObjectArray::AddUObjectCreateListener (FUObjectCreateListener * Listener)
Adds a new listener for object creation.
Parameters
Listener listener to notify when an object is deleted
AddUObjectDeleteListener()
void FUObjectArray::AddUObjectDeleteListener (FUObjectDeleteListener * Listener)
Adds a new listener for object deletion.
Parameters
Listener listener to notify when an object is deleted
AllocateObjectPool()
void FUObjectArray::AllocateObjectPool (int32 MaxUObjects, int32 MaxObjectsNotConsideredByGC, bool bPreAllocateObjectArray)
Allocates and initializes the permanent object pool.
Parameters
MaxUObjects maximum number of UObjects that can ever exist in the array
MaxObjectsNotConsideredByGC number of objects in the permanent object pool
References MaxObjectsNotConsideredByGC.
AllocateSerialNumber()
int32 FUObjectArray::AllocateSerialNumber (int32 Index)
Given a UObject index return the serial number.
If it doesn't have a serial number, give it one. Threadsafe.
Parameters
Index - UObject Index
Returns
- the serial number for this UObject
AllocateUObjectIndex()
void FUObjectArray::AllocateUObjectIndex (class UObjectBase * Object, EInternalObjectFlags InitialFlags, int32 AlreadyAllocatedIndex = -1, int32 SerialNumber = 0, FRemoteObjectId RemoteId = FRemoteObjectId())
Adds a uobject to the global array which is used for uobject iteration.
Parameters
Object Object to allocate an index for
InitialFlags Flags to set in the object array before the object pointer becomes visible to other threads.
AlreadyAllocatedIndex already allocated internal index to use, negative value means allocate a new index
SerialNumber serial number to use
References Object.
CloseDisregardForGC()
void FUObjectArray::CloseDisregardForGC ()
After the initial load, this closes the disregard pool so that new object are GC-able.
DisableDisregardForGC()
void FUObjectArray::DisableDisregardForGC ()
Disables the disregard for GC optimization.
DisregardForGCEnabled()
bool FUObjectArray::DisregardForGCEnabled () const inline
indicates if the disregard for GC optimization is active
Returns
true if MaxObjectsNotConsideredByGC is greater than zero; this indicates that the disregard for GC optimization is enabled
Definition at line 996 of file UObjectArray.h.
References MaxObjectsNotConsideredByGC.
DumpUObjectCountsToLog()
void FUObjectArray::DumpUObjectCountsToLog () const
FreeUObjectIndex()
void FUObjectArray::FreeUObjectIndex (class UObjectBase * Object)
Returns a UObject index top to the global uobject array.
Parameters
Object object to free
References Object.
GetAllocatedSize()
SIZE_T FUObjectArray::GetAllocatedSize () const inline
Definition at line 1456 of file UObjectArray.h.
References ObjAvailableList, ObjObjects, ObjObjectsCritical, UObjectCreateListeners, and UObjectDeleteListeners.
GetDeleteListenersAllocatedSize()
SIZE_T FUObjectArray::GetDeleteListenersAllocatedSize (int32 * OutNumListeners = nullptr) const inline
Definition at line 1465 of file UObjectArray.h.
References UObjectDeleteListeners.
GetFirstGCIndex()
FORCEINLINE int32 FUObjectArray::GetFirstGCIndex () const inline
Returns the index of the first object outside of the disregard for GC pool.
Definition at line 1109 of file UObjectArray.h.
References FORCEINLINE, and ObjFirstGCIndex.
GetObjectArrayCapacity()
int32 FUObjectArray::GetObjectArrayCapacity () const inline
Returns the estimated number of object indices available for allocation.
Definition at line 1225 of file UObjectArray.h.
References ObjObjects.
GetObjectArrayEstimatedAvailable()
int32 FUObjectArray::GetObjectArrayEstimatedAvailable () const inline
Returns the estimated number of object indices available for allocation.
Definition at line 1217 of file UObjectArray.h.
References GetObjectArrayNumMinusAvailable(), and ObjObjects.
GetObjectArrayNum()
FORCEINLINE int32 FUObjectArray::GetObjectArrayNum () const inline
Returns the size of the global UObject array, some of these might be unused.
Returns
the number of UObjects in the global array
Definition at line 1178 of file UObjectArray.h.
References FORCEINLINE, and ObjObjects.
GetObjectArrayNumMinusAvailable()
int32 FUObjectArray::GetObjectArrayNumMinusAvailable () const inline
Returns the number of actual object indices that are claimed (the total size of the global object array minus the number of available object array elements.
Returns
The number of objects claimed
Definition at line 1209 of file UObjectArray.h.
References ObjAvailableList, and ObjObjects.
Referenced by GetObjectArrayEstimatedAvailable().
GetObjectArrayNumMinusPermanent()
FORCEINLINE int32 FUObjectArray::GetObjectArrayNumMinusPermanent () const inline
Returns the size of the global UObject array minus the number of permanent objects.
Returns
the number of UObjects in the global array
Definition at line 1188 of file UObjectArray.h.
References FORCEINLINE, ObjLastNonGCIndex, and ObjObjects.
GetObjectArrayNumPermanent()
FORCEINLINE int32 FUObjectArray::GetObjectArrayNumPermanent () const inline
Returns the number of permanent objects.
Returns
the number of permanent objects
Definition at line 1198 of file UObjectArray.h.
References FORCEINLINE, and ObjLastNonGCIndex.
GetObjectItemArrayUnsafe() [1/2]
TUObjectArray & FUObjectArray::GetObjectItemArrayUnsafe () inline
INTERNAL USE ONLY: gets the internal FUObjectItem array.
Definition at line 1446 of file UObjectArray.h.
References ObjObjects.
GetObjectItemArrayUnsafe() [2/2]
const TUObjectArray & FUObjectArray::GetObjectItemArrayUnsafe () const inline
Definition at line 1451 of file UObjectArray.h.
References ObjObjects.
GetSerialNumber()
FORCEINLINE int32 FUObjectArray::GetSerialNumber (int32 Index) inline
Given a UObject index return the serial number.
If it doesn't have a serial number, return 0. Threadsafe.
Parameters
Index - UObject Index
Returns
- the serial number for this UObject
Definition at line 1247 of file UObjectArray.h.
References checkSlow, FORCEINLINE, FUObjectItem::GetSerialNumber(), and IndexToObject().
IndexToObject() [1/2]
FORCEINLINE FUObjectItem * FUObjectArray::IndexToObject (int32 Index) inline
Returns the UObject corresponding to index.
Be advised this is only for very low level use.
Parameters
Index index of object to return
Returns
Object at this index
Definition at line 1035 of file UObjectArray.h.
References check, FORCEINLINE, and ObjObjects.
Referenced by GetSerialNumber(), IndexToObject(), IndexToValidObject(), IsStale(), IsValid(), and ObjectToObjectItem().
IndexToObject() [2/2]
FORCEINLINE FUObjectItem * FUObjectArray::IndexToObject (int32 Index, bool bEvenIfGarbage) inline
Definition at line 1050 of file UObjectArray.h.
References FORCEINLINE, Garbage, FUObjectItem::GetObject(), FUObjectItem::HasAnyFlags(), and IndexToObject().
IndexToObjectUnsafeForGC()
FORCEINLINE FUObjectItem * FUObjectArray::IndexToObjectUnsafeForGC (int32 Index) inline
Definition at line 1045 of file UObjectArray.h.
References FORCEINLINE, and ObjObjects.
IndexToValidObject()
FORCEINLINE FUObjectItem * FUObjectArray::IndexToValidObject (int32 Index, bool bEvenIfGarbage) inline
Definition at line 1078 of file UObjectArray.h.
References FORCEINLINE, IndexToObject(), and IsValid().
IsDisregardForGC()
FORCEINLINE bool FUObjectArray::IsDisregardForGC (const class UObjectBase * Object) inline
Returns true if this object is "disregard for GC"...same results as the legacy RF_DisregardForGC flag.
Parameters
Object object to get for disregard for GC
Returns
true if this object si disregard for GC
Definition at line 1169 of file UObjectArray.h.
References FORCEINLINE, Object, and ObjLastNonGCIndex.
IsOpenForDisregardForGC()
bool FUObjectArray::IsOpenForDisregardForGC () const inline
Returns true if the disregard for GC pool is open.
Definition at line 986 of file UObjectArray.h.
References OpenForDisregardForGC.
IsStale() [1/2]
FORCEINLINE bool FUObjectArray::IsStale (FUObjectItem * ObjectItem, bool bIncludingGarbage) inline
Definition at line 1091 of file UObjectArray.h.
References FORCEINLINE, Garbage, FUObjectItem::HasAnyFlags(), FUObjectItem::IsUnreachable(), and Unreachable.
Referenced by IsStale().
IsStale() [2/2]
FORCEINLINE bool FUObjectArray::IsStale (int32 Index, bool bIncludingGarbage) inline
Definition at line 1097 of file UObjectArray.h.
References FORCEINLINE, IndexToObject(), and IsStale().
IsValid() [1/3]
bool FUObjectArray::IsValid (const UObjectBase * Object) const
Checks if a UObject pointer is valid.
Parameters
Object object to test for validity
Returns
true if this index is valid
References Object.
IsValid() [2/3]
FORCEINLINE bool FUObjectArray::IsValid (FUObjectItem * ObjectItem, bool bEvenIfGarbage) inline
Definition at line 1069 of file UObjectArray.h.
References FORCEINLINE, Garbage, FUObjectItem::HasAnyFlags(), FUObjectItem::IsUnreachable(), and Unreachable.
IsValid() [3/3]
FORCEINLINE bool FUObjectArray::IsValid (int32 Index, bool bEvenIfGarbage) inline
Definition at line 1084 of file UObjectArray.h.
References FORCEINLINE, IndexToObject(), and IsValid().
IsValidIndex()
FORCEINLINE bool FUObjectArray::IsValidIndex (const UObjectBase * Object) const inline
Checks if the object index is valid.
Definition at line 1158 of file UObjectArray.h.
References FORCEINLINE, Object, and ObjObjects.
LockInternalArray()
void FUObjectArray::LockInternalArray () const inline
Locks the internal object array mutex.
Definition at line 1270 of file UObjectArray.h.
References check, IsInGameThread(), and ObjObjectsCritical.
Referenced by TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::TObjectIteratorBase(), and TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::AdvanceIterator().
ObjectToIndex()
FORCEINLINE int32 FUObjectArray::ObjectToIndex (const class UObjectBase * Object) const inline
Returns the index of a UObject.
Be advised this is only for very low level use.
Parameters
Object object to get the index of
Returns
index of this object
Definition at line 1024 of file UObjectArray.h.
References FORCEINLINE, and Object.
ObjectToObjectItem()
FORCEINLINE FUObjectItem * FUObjectArray::ObjectToObjectItem (const UObjectBase * Object) inline
Definition at line 1063 of file UObjectArray.h.
References FORCEINLINE, IndexToObject(), and Object.
OpenDisregardForGC()
void FUObjectArray::OpenDisregardForGC ()
If there's enough slack in the disregard pool, we can re-open it and keep adding objects to it.
RemoveObjectFromDeleteListeners()
void FUObjectArray::RemoveObjectFromDeleteListeners (UObjectBase * Object)
Removes an object from delete listeners.
Parameters
Object to remove from delete listeners
References Object.
RemoveUObjectCreateListener()
void FUObjectArray::RemoveUObjectCreateListener (FUObjectCreateListener * Listener)
Removes a listener for object creation.
Parameters
Listener listener to remove
RemoveUObjectDeleteListener()
void FUObjectArray::RemoveUObjectDeleteListener (FUObjectDeleteListener * Listener)
Removes a listener for object deletion.
Parameters
Listener listener to remove
ResetSerialNumber()
void FUObjectArray::ResetSerialNumber (UObjectBase * Object) private
Reset the serial number from the game thread to invalidate all weak object pointers to it.
Parameters
Object to reset
References Object.
ShutdownUObjectArray()
void FUObjectArray::ShutdownUObjectArray ()
Clears some internal arrays to get rid of false memory leaks.
UnlockInternalArray()
void FUObjectArray::UnlockInternalArray () const inline
Unlocks the internal object array mutex.
Definition at line 1280 of file UObjectArray.h.
References ObjObjectsCritical.
Referenced by TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::~TObjectIteratorBase(), and TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::AdvanceIterator().
Friends And Related Symbol Documentation
StaticAllocateObject
UObject * StaticAllocateObject (const UClass * Class, UObject * InOuter, FName Name, EObjectFlags SetFlags, EInternalObjectFlags InternalSetFlags = EInternalObjectFlags::None, bool bCanReuseSubobjects = false, bool * bOutReusedSubobject = nullptr, UPackage * ExternalPackage = nullptr, int32 SerialNumber = 0, FRemoteObjectId RemoteId = FRemoteObjectId(), class FGCReconstructionGuard * GCGuard = nullptr) friend
Create a new instance of an object or replace an existing object.
If both an Outer and Name are specified, and there is an object already in memory with the same Class, Outer, and Name, the existing object will be destructed, and the new object will be created in its place.
Parameters
Class the class of the object to create
InOuter the object to create this object within (the Outer property for the new object will be set to the value specified here).
Name the name to give the new object. If no value (NAME_None) is specified, the object will be given a unique name in the form of ClassName_#.
SetFlags the ObjectFlags to assign to the new object. some flags can affect the behavior of constructing the object.
InternalSetFlags the InternalObjectFlags to assign to the new object. some flags can affect the behavior of constructing the object.
bCanReuseSubobjects if set to true, SAO will not attempt to destroy a subobject if it already exists in memory.
bOutReusedSubobject flag indicating if the object is a subobject that has already been created (in which case further initialization is not necessary).
ExternalPackage External Package assigned to the allocated object, if any
RemoteId Globally unique id for this object
GCGuard Special synchronization object that prevents GC from running when reconstructing an object on top of existing one
Returns
a pointer to a fully initialized object of the specified class.
References UObject.
UObject
friend class UObject friend
Definition at line 887 of file UObjectArray.h.
References UObject.
Referenced by StaticAllocateObject, and UObject.
Field Documentation
bShouldRecycleObjectIndices
bool FUObjectArray::bShouldRecycleObjectIndices = true private
If set to false object indices won't be recycled to the global pool and can be explicitly reused when creating new objects.
Definition at line 1441 of file UObjectArray.h.
MaxObjectsNotConsideredByGC
int32 FUObjectArray::MaxObjectsNotConsideredByGC private
Maximum number of objects in the disregard for GC Pool.
Definition at line 1414 of file UObjectArray.h.
Referenced by AllocateObjectPool(), and DisregardForGCEnabled().
ObjAvailableList
TArray<int32> FUObjectArray::ObjAvailableList private
Available object indices.
Definition at line 1423 of file UObjectArray.h.
Referenced by GetAllocatedSize(), and GetObjectArrayNumMinusAvailable().
ObjFirstGCIndex
int32 FUObjectArray::ObjFirstGCIndex private
First index into objects array taken into account for GC.
Definition at line 1410 of file UObjectArray.h.
Referenced by GetFirstGCIndex().
ObjLastNonGCIndex
int32 FUObjectArray::ObjLastNonGCIndex private
Index pointing to last object created in range disregarded for GC.
Definition at line 1412 of file UObjectArray.h.
Referenced by GetObjectArrayNumMinusPermanent(), GetObjectArrayNumPermanent(), and IsDisregardForGC().
ObjObjects
TUObjectArray FUObjectArray::ObjObjects private
Array of all live objects.
Definition at line 1419 of file UObjectArray.h.
Referenced by FUObjectArray::TIterator::TIterator(), GetAllocatedSize(), GetObjectArrayCapacity(), GetObjectArrayEstimatedAvailable(), GetObjectArrayNum(), GetObjectArrayNumMinusAvailable(), GetObjectArrayNumMinusPermanent(), GetObjectItemArrayUnsafe(), GetObjectItemArrayUnsafe(), IndexToObject(), IndexToObjectUnsafeForGC(), and IsValidIndex().
ObjObjectsCritical
FTransactionallySafeCriticalSection FUObjectArray::ObjObjectsCritical mutable private
Synchronization object for all live objects.
Definition at line 1421 of file UObjectArray.h.
Referenced by GetAllocatedSize(), LockInternalArray(), and UnlockInternalArray().
OpenForDisregardForGC
bool FUObjectArray::OpenForDisregardForGC private
If true this is the intial load and we should load objects int the disregarded for GC range.
Definition at line 1417 of file UObjectArray.h.
Referenced by IsOpenForDisregardForGC().
PrimarySerialNumber
FThreadSafeCounter FUObjectArray::PrimarySerialNumber private
Current primary serial number.
Definition at line 1438 of file UObjectArray.h.
UObjectCreateListeners
TArray<FUObjectCreateListener* > FUObjectArray::UObjectCreateListeners private
Array of things to notify when a UObjectBase is created.
Definition at line 1428 of file UObjectArray.h.
Referenced by GetAllocatedSize().
UObjectDeleteListeners
TArray<FUObjectDeleteListener* > FUObjectArray::UObjectDeleteListeners private
Array of things to notify when a UObjectBase is destroyed.
Definition at line 1432 of file UObjectArray.h.
Referenced by GetAllocatedSize(), and GetDeleteListenersAllocatedSize().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectArray.h