Unreal Engine 5.6 C++ API: FTickableObjectBase Class Reference
FTickableObjectBase Class Reference abstract
Base class for tickable objects.
#include "Tickable.h"
Data Structures
struct FTickableObjectEntry
Implementation struct for an individual tickable object.
struct FTickableStatics
Implementation struct for internals of ticking, there should be one instance of this for each direct subclass.
Public Member Functions
virtual TStatId GetStatId () const =0
Return the stat id used to track the performance of this object.
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
virtual void Tick (float DeltaTime)=0
Pure virtual that must be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Protected Member Functions
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Base class for tickable objects.
Definition at line 37 of file Tickable.h.
Member Function Documentation
GetStatId()
virtual TStatId FTickableObjectBase::GetStatId () const pure virtual
Return the stat id used to track the performance of this object.
Implemented in ALevelBounds, FAssetEditorViewportLayout, FAssetThumbnailPool, FBlueprintActionDatabase, FBlueprintEditor, FCrowdTickHelper, FDataflowEditorToolkit, FDisplayClusterTickableGameObject, FFindInBlueprintSearchManager, FForceFeedbackManager, FMotionVectorSimulation, FReplaceNodeReferencesHelper, FRigVMNewEditor, FSkinWeightProfileManager, FThumbnailPreviewScene, TExternalDirtyActorsTracker< StoreType >, UE::Dataflow::FDataflowSimulationGenerator, UE::PixelStreaming2::FEpicRtcWebsocket, UE::PixelStreaming2::FStreamerReconnectTimer, and UVPScoutingSubsystemGestureManagerBase.
GetTickableTickType()
virtual ETickableTickType FTickableObjectBase::GetTickableTickType () const inline virtual
Virtual that can be overloaded by the inheriting class and is called before first tick.
It is used to determine whether an object can possibly tick, and if not, it will not get added to the tickable objects array. If the tickable tick type is Conditional then the virtual IsTickable will be called to determine whether to tick the object on each given frame.
Returns
an enum defining the rules for ticking this object.
Reimplemented in ALevelBounds, FBlueprintActionDatabase, FBlueprintEditor, FDisplayClusterTickableGameObject, FThumbnailPreviewScene, UE::Dataflow::FDataflowSimulationGenerator, and UVPScoutingSubsystemGestureManagerBase.
Definition at line 106 of file Tickable.h.
References Conditional.
IsTickable()
virtual bool FTickableObjectBase::IsTickable () const inline virtual
Virtual that can be overloaded by the inheriting class.
It is used to determine whether an object should be conditionally ticked.
Returns
true if object is ready to be ticked, false otherwise.
Reimplemented in ALevelBounds, FAssetEditorViewportLayout, FAssetThumbnailPool, FCrowdTickHelper, FDataflowEditorToolkit, FFindInBlueprintSearchManager, FForceFeedbackManager, FMotionVectorSimulation, FReplaceNodeReferencesHelper, FSkinWeightProfileManager, and UVPScoutingSubsystemGestureManagerBase.
Definition at line 114 of file Tickable.h.
SimpleTickObjects()
void FTickableObjectBase::SimpleTickObjects (FTickableStatics & Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc) static protected
Perform a simple tick using a class-specific statics struct and a function ref.
Referenced by FTickableCookObject::TickObjects(), and FTickableEditorObject::TickObjects().
Tick()
virtual void FTickableObjectBase::Tick (float DeltaTime) pure virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implemented in ALevelBounds, FAssetEditorViewportLayout, FAssetThumbnailPool, FBlueprintActionDatabase, FBlueprintEditor, FCrowdTickHelper, FDataflowEditorToolkit, FDisplayClusterTickableGameObject, FFindInBlueprintSearchManager, FForceFeedbackManager, FMotionVectorSimulation, FReplaceNodeReferencesHelper, FRigVMNewEditor, FSkinWeightProfileManager, FThumbnailPreviewScene, FWidgetBlueprintEditor, TExternalDirtyActorsTracker< StoreType >, UE::Dataflow::FDataflowSimulationGenerator, UE::PixelStreaming2::FEpicRtcWebsocket, UE::PixelStreaming2::FStreamerReconnectTimer, and UVPScoutingSubsystemGestureManagerBase.
References DeltaTime.
Referenced by FTickableEditorObject::TickObjects().
UE_DEPRECATED()
FTickableObjectBase::UE_DEPRECATED (5. 5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") const inline
Function called before IsTickable, used to change rules without breaking existing API.
This was used to allow checking for tickable safety before calling GetTickableGameObjectWorld.
Returns
true if object is allowed to be ticked, false otherwise.
Definition at line 121 of file Tickable.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Tickable.h