Unreal Engine 5.6 C++ API: FNamePermissionList Class Reference
FNamePermissionList Class Reference
#include "NamePermissionList.h"
Public Member Functions
FNamePermissionList ()
virtual ~FNamePermissionList ()
bool AddAllowListItem (const FName OwnerName, const FName Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
bool AddDenyListAll (const FName OwnerName)
Set to filter out all items.
bool AddDenyListItem (const FName OwnerName, const FName Item)
Add item to DenyList, this specific item will be filtered out.
bool Append (const FNamePermissionList &Other)
Add the specified filters to this one.
const TMap< FName, FPermissionListOwners > & GetAllowList () const
Get raw allowlist.
const TMap< FName, FPermissionListOwners > & GetDenyList () const
Get raw DenyList.
TArray< FName > GetOwnerNames () const
Gathers the names of all the owners in this DenyList.
bool HasFiltering () const
True if has filters active.
bool IsDenyListAll () const
Are all items set to be filtered out.
FSimpleMulticastDelegate & OnFilterChanged ()
Triggered when filter changes.
bool PassesFilter (const FName Item) const
Returns true if passes filter restrictions using exact match.
bool RemoveAllowListItem (const FName OwnerName, const FName Item)
Removes a previously-added item from the allowlist.
bool RemoveDenyListItem (const FName OwnerName, const FName Item)
Removes a previously-added item from the DenyList.
bool UnregisterOwner (const FName OwnerName)
Removes all filtering changes associated with a specific owner name.
bool UnregisterOwners (const TArray< FName > &OwnerNames)
Removes all filtering changes associated with the specified list of owner names.
bool UnregisterOwnersAndAppend (const TArray< FName > &OwnerNamesToRemove, const FNamePermissionList &FiltersToAdd)
Unregisters specified owners then adds specified filters in one operation (to avoid multiple filters changed events).
Public Member Functions inherited from TSharedFromThis< FNamePermissionList >
TSharedRef< FNamePermissionList, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FNamePermissionList, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Attributes
TMap< FName, FPermissionListOwners > AllowList
List of items to allow, if not empty all items will be filtered out unless they are in the list.
bool bSuppressOnFilterChanged = false
Temporarily prevent delegate from being triggered.
TMap< FName, FPermissionListOwners > DenyList
List if items to filter out.
FPermissionListOwners DenyListAll
List of owner names that requested all items to be filtered out.
FSimpleMulticastDelegate OnFilterChangedDelegate
Triggered when filter changes.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FNamePermissionList >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FNamePermissionList >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 21 of file NamePermissionList.h.
Constructor & Destructor Documentation
FNamePermissionList()
FNamePermissionList::FNamePermissionList () inline
Definition at line 24 of file NamePermissionList.h.
Referenced by Append(), and UnregisterOwnersAndAppend().
~FNamePermissionList()
virtual FNamePermissionList::~FNamePermissionList () inline virtual
Definition at line 25 of file NamePermissionList.h.
Member Function Documentation
AddAllowListItem()
bool FNamePermissionList::AddAllowListItem (const FName OwnerName, const FName Item)
Add item to allowlist after which all items not in the allowlist will be filtered out.
Returns
whether the filters changed.
References Item.
AddDenyListAll()
bool FNamePermissionList::AddDenyListAll (const FName OwnerName)
Set to filter out all items.
Returns
whether the filters changed.
AddDenyListItem()
bool FNamePermissionList::AddDenyListItem (const FName OwnerName, const FName Item)
Add item to DenyList, this specific item will be filtered out.
Returns
whether the filters changed.
References Item.
Append()
bool FNamePermissionList::Append (const FNamePermissionList & Other)
Add the specified filters to this one.
Returns
whether the filters changed.
References FNamePermissionList(), and Other.
GetAllowList()
const TMap< FName, FPermissionListOwners > & FNamePermissionList::GetAllowList () const inline
Get raw allowlist.
Definition at line 94 of file NamePermissionList.h.
References AllowList.
GetDenyList()
const TMap< FName, FPermissionListOwners > & FNamePermissionList::GetDenyList () const inline
Get raw DenyList.
Definition at line 91 of file NamePermissionList.h.
References DenyList.
GetOwnerNames()
TArray< FName > FNamePermissionList::GetOwnerNames () const
Gathers the names of all the owners in this DenyList.
HasFiltering()
bool FNamePermissionList::HasFiltering () const
True if has filters active.
IsDenyListAll()
bool FNamePermissionList::IsDenyListAll () const inline
Are all items set to be filtered out.
Definition at line 97 of file NamePermissionList.h.
References DenyListAll.
OnFilterChanged()
FSimpleMulticastDelegate & FNamePermissionList::OnFilterChanged () inline
Triggered when filter changes.
Definition at line 100 of file NamePermissionList.h.
References OnFilterChangedDelegate.
PassesFilter()
bool FNamePermissionList::PassesFilter (const FName Item) const
Returns true if passes filter restrictions using exact match.
References Item.
RemoveAllowListItem()
bool FNamePermissionList::RemoveAllowListItem (const FName OwnerName, const FName Item)
Removes a previously-added item from the allowlist.
Returns
whether the filters changed.
References Item.
RemoveDenyListItem()
bool FNamePermissionList::RemoveDenyListItem (const FName OwnerName, const FName Item)
Removes a previously-added item from the DenyList.
Returns
whether the filters changed.
References Item.
UnregisterOwner()
bool FNamePermissionList::UnregisterOwner (const FName OwnerName)
Removes all filtering changes associated with a specific owner name.
Returns
whether the filters changed.
UnregisterOwners()
bool FNamePermissionList::UnregisterOwners (const TArray< FName > & OwnerNames)
Removes all filtering changes associated with the specified list of owner names.
Returns
whether the filters changed.
UnregisterOwnersAndAppend()
bool FNamePermissionList::UnregisterOwnersAndAppend (const TArray< FName > & OwnerNamesToRemove, const FNamePermissionList & FiltersToAdd)
Unregisters specified owners then adds specified filters in one operation (to avoid multiple filters changed events).
Returns
whether the filters changed.
References FNamePermissionList().
Field Documentation
AllowList
TMap<FName, FPermissionListOwners> FNamePermissionList::AllowList protected
List of items to allow, if not empty all items will be filtered out unless they are in the list.
Definition at line 108 of file NamePermissionList.h.
Referenced by GetAllowList().
bSuppressOnFilterChanged
bool FNamePermissionList::bSuppressOnFilterChanged = false protected
Temporarily prevent delegate from being triggered.
Definition at line 117 of file NamePermissionList.h.
DenyList
TMap<FName, FPermissionListOwners> FNamePermissionList::DenyList protected
List if items to filter out.
Definition at line 105 of file NamePermissionList.h.
Referenced by GetDenyList().
DenyListAll
FPermissionListOwners FNamePermissionList::DenyListAll protected
List of owner names that requested all items to be filtered out.
Definition at line 111 of file NamePermissionList.h.
Referenced by IsDenyListAll().
OnFilterChangedDelegate
FSimpleMulticastDelegate FNamePermissionList::OnFilterChangedDelegate protected
Triggered when filter changes.
Definition at line 114 of file NamePermissionList.h.
Referenced by OnFilterChanged().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/NamePermissionList.h