Unreal Engine 5.6 C++ API: UE::Geometry::TDenseGrid3< ElemType > Class Template Reference
UE::Geometry::TDenseGrid3< ElemType > Class Template Reference
3D dense grid of floating-point scalar values.
#include "DenseGrid3.h"
Public Member Functions
TDenseGrid3 ()
Create empty grid.
TDenseGrid3 (int DimX, int DimY, int DimZ, ElemType InitialValue)
void Apply (TFunctionRef< ElemType(ElemType)> F)
void Assign (ElemType Value)
constexpr ElemType & At (int I, int J, int K)
constexpr const ElemType & At (int I, int J, int K) const
FAxisAlignedBox3i Bounds () const
FAxisAlignedBox3i BoundsInclusive () const
const FVector3i & GetDimensions () const
ElemType GetValue (const FVector3i &CellCoords) const
ElemType GetValue (int32 X, int32 Y, int32 Z) const
void GetXPair (int X0, int Y, int Z, ElemType &AOut, ElemType &BOut) const
TArray< ElemType > & GridValues ()
const TArray< ElemType > & GridValues () const
bool IsValidIndex (const FVector3i &Index) const
constexpr ElemType & operator[] (FVector3i Idx)
constexpr const ElemType & operator[] (FVector3i Idx) const
constexpr ElemType & operator[] (int Idx)
constexpr const ElemType & operator[] (int Idx) const
template<typename ProcessFunc>
void ProcessValue (const FVector3i &CellCoords, ProcessFunc Func)
Call an external lambda with a reference to the grid value at (X,Y,Z).
template<typename ProcessFunc>
void ProcessValue (int32 X, int32 Y, int32 Z, ProcessFunc Func)
Call an external lambda with a reference to the grid value at (X,Y,Z).
void Resize (int DimX, int DimY, int DimZ, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
void SetMax (const FVector3i &IJK, ElemType F)
void SetMin (const FVector3i &IJK, ElemType F)
void SetValue (const FVector3i &CellCoords, ElemType NewValue)
Set the grid value at (X,Y,Z)
void SetValue (int32 X, int32 Y, int32 Z, ElemType NewValue)
Set the grid value at (X,Y,Z)
int Size () const
FVector3i ToIndex (int Idx) const
int ToLinear (const FVector3i &IJK) const
int ToLinear (int X, int Y, int Z) const
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Resize") FORCEINLINE void Resize(int DimX
Data Fields
int int bool bAllowShrinking
int DimY
int int DimZ
Protected Attributes
TArray< ElemType > Buffer
grid of allocated elements
FVector3i Dimensions
dimensions per axis
Detailed Description
template<typename ElemType>
class UE::Geometry::TDenseGrid3< ElemType >
3D dense grid of floating-point scalar values.
Definition at line 22 of file DenseGrid3.h.
Constructor & Destructor Documentation
TDenseGrid3() [1/2]
template<typename ElemType> UE::Geometry::TDenseGrid3< ElemType >::TDenseGrid3 () inline
Create empty grid.
Definition at line 35 of file DenseGrid3.h.
TDenseGrid3() [2/2]
template<typename ElemType> UE::Geometry::TDenseGrid3< ElemType >::TDenseGrid3 (int DimX, int DimY, int DimZ, ElemType InitialValue) inline
Definition at line 39 of file DenseGrid3.h.
Member Function Documentation
Apply()
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::Apply (TFunctionRef< ElemType(ElemType)> F) inline
Definition at line 198 of file DenseGrid3.h.
Assign()
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::Assign (ElemType Value) inline
Definition at line 73 of file DenseGrid3.h.
Referenced by UE::Geometry::TDenseGrid3< float >::TDenseGrid3(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial().
At() [1/2]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid3< ElemType >::At (int I, int J, int K) inline constexpr
Definition at line 115 of file DenseGrid3.h.
Referenced by UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::check_neighbour(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_signs(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_signs(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial().
At() [2/2]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid3< ElemType >::At (int I, int J, int K) const inline constexpr
Definition at line 119 of file DenseGrid3.h.
Bounds()
template<typename ElemType> FAxisAlignedBox3i UE::Geometry::TDenseGrid3< ElemType >::Bounds () const inline
Definition at line 206 of file DenseGrid3.h.
Referenced by UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid().
BoundsInclusive()
template<typename ElemType> FAxisAlignedBox3i UE::Geometry::TDenseGrid3< ElemType >::BoundsInclusive () const inline
Definition at line 210 of file DenseGrid3.h.
GetDimensions()
template<typename ElemType> const FVector3i & UE::Geometry::TDenseGrid3< ElemType >::GetDimensions () const inline
Definition at line 56 of file DenseGrid3.h.
Referenced by UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::sweep(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::upper_bound().
GetValue() [1/2]
template<typename ElemType> ElemType UE::Geometry::TDenseGrid3< ElemType >::GetValue (const FVector3i & CellCoords) const inline
Returns
the grid value at (X,Y,Z)
Definition at line 144 of file DenseGrid3.h.
GetValue() [2/2]
template<typename ElemType> ElemType UE::Geometry::TDenseGrid3< ElemType >::GetValue (int32 X, int32 Y, int32 Z) const inline
Returns
the grid value at (X,Y,Z)
Definition at line 136 of file DenseGrid3.h.
GetXPair()
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::GetXPair (int X0, int Y, int Z, ElemType & AOut, ElemType & BOut) const inline
Definition at line 191 of file DenseGrid3.h.
GridValues() [1/2]
template<typename ElemType> TArray< ElemType > & UE::Geometry::TDenseGrid3< ElemType >::GridValues () inline
Definition at line 124 of file DenseGrid3.h.
GridValues() [2/2]
template<typename ElemType> const TArray< ElemType > & UE::Geometry::TDenseGrid3< ElemType >::GridValues () const inline
Definition at line 128 of file DenseGrid3.h.
IsValidIndex()
template<typename ElemType> bool UE::Geometry::TDenseGrid3< ElemType >::IsValidIndex (const FVector3i & Index) const inline
Definition at line 50 of file DenseGrid3.h.
operator[]() [1/4]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid3< ElemType >::operator[] (FVector3i Idx) inline constexpr
Definition at line 107 of file DenseGrid3.h.
operator[]() [2/4]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid3< ElemType >::operator[] (FVector3i Idx) const inline constexpr
Definition at line 111 of file DenseGrid3.h.
operator[]() [3/4]
template<typename ElemType> ElemType & UE::Geometry::TDenseGrid3< ElemType >::operator[] (int Idx) inline constexpr
Definition at line 98 of file DenseGrid3.h.
operator[]() [4/4]
template<typename ElemType> const ElemType & UE::Geometry::TDenseGrid3< ElemType >::operator[] (int Idx) const inline constexpr
Definition at line 102 of file DenseGrid3.h.
ProcessValue() [1/2]
template<typename ElemType> template<typename ProcessFunc> void UE::Geometry::TDenseGrid3< ElemType >::ProcessValue (const FVector3i & CellCoords, ProcessFunc Func) inline
Call an external lambda with a reference to the grid value at (X,Y,Z).
Called as Func(ElemType&), so the caller can both read and write the grid cell
Definition at line 182 of file DenseGrid3.h.
ProcessValue() [2/2]
template<typename ElemType> template<typename ProcessFunc> void UE::Geometry::TDenseGrid3< ElemType >::ProcessValue (int32 X, int32 Y, int32 Z, ProcessFunc Func) inline
Call an external lambda with a reference to the grid value at (X,Y,Z).
Called as Func(ElemType&), so the caller can both read and write the grid cell
Definition at line 170 of file DenseGrid3.h.
Resize()
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::Resize (int DimX, int DimY, int DimZ, EAllowShrinking AllowShrinking = EAllowShrinking::Default) inline
Definition at line 61 of file DenseGrid3.h.
Referenced by UE::Geometry::TDenseGrid3< float >::TDenseGrid3(), UE::Geometry::GetShape(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid_dense(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial().
SetMax()
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::SetMax (const FVector3i & IJK, ElemType F) inline
Definition at line 89 of file DenseGrid3.h.
SetMin()
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::SetMin (const FVector3i & IJK, ElemType F) inline
Definition at line 81 of file DenseGrid3.h.
SetValue() [1/2]
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::SetValue (const FVector3i & CellCoords, ElemType NewValue) inline
Set the grid value at (X,Y,Z)
Definition at line 160 of file DenseGrid3.h.
SetValue() [2/2]
template<typename ElemType> void UE::Geometry::TDenseGrid3< ElemType >::SetValue (int32 X, int32 Y, int32 Z, ElemType NewValue) inline
Set the grid value at (X,Y,Z)
Definition at line 152 of file DenseGrid3.h.
Size()
template<typename ElemType> int UE::Geometry::TDenseGrid3< ElemType >::Size () const inline
Definition at line 45 of file DenseGrid3.h.
Referenced by UE::Geometry::TDenseGrid3< float >::Apply(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid_dense(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill().
ToIndex()
template<typename ElemType> FVector3i UE::Geometry::TDenseGrid3< ElemType >::ToIndex (int Idx) const inline
Definition at line 215 of file DenseGrid3.h.
Referenced by UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), and UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid_dense().
ToLinear() [1/2]
template<typename ElemType> int UE::Geometry::TDenseGrid3< ElemType >::ToLinear (const FVector3i & IJK) const inline
Definition at line 226 of file DenseGrid3.h.
ToLinear() [2/2]
template<typename ElemType> int UE::Geometry::TDenseGrid3< ElemType >::ToLinear (int X, int Y, int Z) const inline
Definition at line 222 of file DenseGrid3.h.
Referenced by UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill().
UE_ALLOWSHRINKING_BOOL_DEPRECATED()
template<typename ElemType> UE::Geometry::TDenseGrid3< ElemType >::UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Resize")
Field Documentation
bAllowShrinking
template<typename ElemType> int int bool UE::Geometry::TDenseGrid3< ElemType >::bAllowShrinking
Initial value:
{
        Resize(DimX, DimY, DimZ, bAllowShrinking ? EAllowShrinking::Yes : EAllowShrinking::No)
Definition at line 68 of file DenseGrid3.h.
Buffer
template<typename ElemType> TArray<ElemType> UE::Geometry::TDenseGrid3< ElemType >::Buffer protected
grid of allocated elements
Definition at line 26 of file DenseGrid3.h.
Dimensions
template<typename ElemType> FVector3i UE::Geometry::TDenseGrid3< ElemType >::Dimensions protected
dimensions per axis
Definition at line 29 of file DenseGrid3.h.
DimY
template<typename ElemType> int UE::Geometry::TDenseGrid3< ElemType >::DimY
Definition at line 68 of file DenseGrid3.h.
DimZ
template<typename ElemType> int int UE::Geometry::TDenseGrid3< ElemType >::DimZ
Definition at line 68 of file DenseGrid3.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/DenseGrid3.h