Unreal Engine 5.6 C++ API: TUTF32ToUTF16_Convert< InFromType, InToType > Class Template Reference
TUTF32ToUTF16_Convert< InFromType, InToType > Class Template Reference
#include "StringConv.h"
Public Types
typedef InFromType FromType
typedef InToType ToType
Static Public Member Functions
template<typename SrcBufferType UE_REQUIRES>
static FORCEINLINE void Convert (ToType *Dest, int32 DestLen, const SrcBufferType *Source, int32 SourceLen)
Converts the string to the desired format.
template<typename SrcBufferType UE_REQUIRES>
static FORCEINLINE int32 ConvertedLength (const SrcBufferType *Source, int32 SourceLen)
Determines the length of the converted string.
template<typename BufferType>
static int32 Utf16FromCodepoint (uint32 Codepoint, BufferType OutputIterator, uint32 OutputIteratorNumRemaining)
Convert Codepoint into UTF-16 characters.
Static Private Member Functions
template<typename DestBufferType>
static void Convert_Impl (DestBufferType &Dest, int32 DestLen, const FromType *Source, const int32 SourceLen)
template<typename DestBufferType>
static bool WriteCodepointToBuffer (const uint32 Codepoint, DestBufferType &Dest, int32 &DestLen)
Detailed Description
template<typename InFromType, typename InToType>
class TUTF32ToUTF16_Convert< InFromType, InToType >
Definition at line 414 of file StringConv.h.
Member Typedef Documentation
FromType
template<typename InFromType, typename InToType> typedef InFromType TUTF32ToUTF16_Convert< InFromType, InToType >::FromType
Definition at line 420 of file StringConv.h.
ToType
template<typename InFromType, typename InToType> typedef InToType TUTF32ToUTF16_Convert< InFromType, InToType >::ToType
Definition at line 421 of file StringConv.h.
Member Function Documentation
Convert()
template<typename InFromType, typename InToType> template<typename SrcBufferType UE_REQUIRES> FORCEINLINE void TUTF32ToUTF16_Convert< InFromType, InToType >::Convert (ToType * Dest, int32 DestLen, const SrcBufferType * Source, int32 SourceLen) inline static
Converts the string to the desired format.
Parameters
Dest The destination buffer of the converted string.
DestLen The length of the destination buffer.
Source The source string to convert.
SourceLen The length of the source string.
Definition at line 491 of file StringConv.h.
References Convert_Impl(), FORCEINLINE, and Source.
Convert_Impl()
template<typename InFromType, typename InToType> template<typename DestBufferType> void TUTF32ToUTF16_Convert< InFromType, InToType >::Convert_Impl (DestBufferType & Dest, int32 DestLen, const FromType * Source, const int32 SourceLen) inline static private
Definition at line 516 of file StringConv.h.
References Source, and WriteCodepointToBuffer().
Referenced by Convert(), and ConvertedLength().
ConvertedLength()
template<typename InFromType, typename InToType> template<typename SrcBufferType UE_REQUIRES> FORCEINLINE int32 TUTF32ToUTF16_Convert< InFromType, InToType >::ConvertedLength (const SrcBufferType * Source, int32 SourceLen) inline static nodiscard
Determines the length of the converted string.
Returns
The length of the string in UTF-16 code units.
Definition at line 505 of file StringConv.h.
References Convert_Impl(), FORCEINLINE, UE::Core::Private::FCountingOutputIterator::GetCount(), and Source.
Utf16FromCodepoint()
template<typename InFromType, typename InToType> template<typename BufferType> int32 TUTF32ToUTF16_Convert< InFromType, InToType >::Utf16FromCodepoint (uint32 Codepoint, BufferType OutputIterator, uint32 OutputIteratorNumRemaining) inline static nodiscard
Convert Codepoint into UTF-16 characters.
Parameters
Codepoint Codepoint to expand into UTF-16 code units
OutputIterator Output iterator to write UTF-16 code units into
OutputIteratorNumRemaining Maximum number of UTF-16 code units that can be written to OutputIterator
Returns
Number of characters written for Codepoint
Definition at line 432 of file StringConv.h.
References StringConv::DecodeSurrogate(), ENCODED_SURROGATE_END_CODEPOINT, StringConv::IsEncodedSurrogate(), StringConv::IsHighSurrogate(), StringConv::IsLowSurrogate(), StringConv::IsValidCodepoint(), UE_PTRDIFF_TO_INT32, and UNICODE_BOGUS_CHAR_CODEPOINT.
Referenced by WriteCodepointToBuffer().
WriteCodepointToBuffer()
template<typename InFromType, typename InToType> template<typename DestBufferType> bool TUTF32ToUTF16_Convert< InFromType, InToType >::WriteCodepointToBuffer (const uint32 Codepoint, DestBufferType & Dest, int32 & DestLen) inline static private
Definition at line 531 of file StringConv.h.
References Utf16FromCodepoint().
Referenced by Convert_Impl().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/StringConv.h