Unreal Engine 5.6 C++ API: Metasound::FDataReferenceCollection Class Reference
Metasound::FDataReferenceCollection Class Reference
#include "MetasoundDataReferenceCollection.h"
Public Member Functions
template<typename DataType>
void AddDataReadReference (const FVertexName &InName, const TDataReadReference< DataType > &InDataReference)
Add a readable data reference to the collection.
template<typename DataType>
void AddDataReadReference (const FVertexName &InName, const TDataWriteReference< DataType > &InDataReference)
Add a readable data reference to the collection.
METASOUNDGRAPHCORE_API bool AddDataReadReferenceFrom (const FVertexName &InLocalName, const FDataReferenceCollection &InOtherCollection, const FVertexName &InOtherName, const FName &InOtherTypeName)
Add a readable data reference from another collection.
METASOUNDGRAPHCORE_API void AddDataReference (const FVertexName &InName, FAnyDataReference &&InDataReference)
Add a data reference to this collection.
template<typename DataType>
void AddDataWriteReference (const FVertexName &InName, const TDataWriteReference< DataType > &InDataReference)
Add a writable data reference to the collection.
METASOUNDGRAPHCORE_API bool AddDataWriteReferenceFrom (const FVertexName &InLocalName, const FDataReferenceCollection &InOtherCollection, const FVertexName &InOtherName, const FName &InOtherTypeName)
Add a writable data reference from another collection.
template<typename DataType>
bool ContainsDataReadReference (const FVertexName &InName) const
Query whether a readable data reference is within the collection.
METASOUNDGRAPHCORE_API bool ContainsDataReadReference (const FVertexName &InName, const FName &InTypeName) const
Query whether a readable data reference is within the collection.
template<typename DataType>
bool ContainsDataWriteReference (const FVertexName &InName) const
Query whether a writable data reference is within the collection.
METASOUNDGRAPHCORE_API bool ContainsDataWriteReference (const FVertexName &InName, const FName &InTypeName) const
Query whether a writable data reference is within the collection.
METASOUNDGRAPHCORE_API const FAnyDataReference * FindDataReference (const FVertexName &InName) const
Returns pointer to data reference if it exists for a given vertex name.
template<typename DataType>
TDataReadReference< DataType > GetDataReadReference (const FVertexName &InName) const
Returns a readable data ref from the collection.
template<typename DataType, typename... ConstructorArgTypes>
TDataReadReference< DataType > GetDataReadReferenceOrConstruct (FVertexName InName, ConstructorArgTypes &&... ConstructorArgs) const
Returns a readable data ref from the collection or construct one if one is not there.
template<typename DataType>
TDataReadReference< DataType > GetDataReadReferenceOrConstructWithVertexDefault (const FInputVertexInterface &InputVertices, FVertexName InName, const FOperatorSettings &InSettings) const
Returns a readable data ref from the collection or construct one if one is not there with the default provided from the given input vertex collection.
template<typename DataType>
TDataWriteReference< DataType > GetDataWriteReference (const FVertexName &InName) const
Returns a writable data ref from the collection.
template<typename DataType, typename... ConstructorArgTypes>
TDataWriteReference< DataType > GetDataWriteReferenceOrConstruct (const FVertexName &InName, ConstructorArgTypes &&... ConstructorArgs) const
Returns a writable data ref from the collection or construct one if one is not there.
Private Types
using FDataReferenceMap = TMap<FVertexName, FAnyDataReference>
Private Attributes
FDataReferenceMap DataRefMap
Detailed Description
Definition at line 17 of file MetasoundDataReferenceCollection.h.
Member Typedef Documentation
FDataReferenceMap
using Metasound::FDataReferenceCollection::FDataReferenceMap = TMap<FVertexName, FAnyDataReference> private
Definition at line 19 of file MetasoundDataReferenceCollection.h.
Member Function Documentation
AddDataReadReference() [1/2]
template<typename DataType> void Metasound::FDataReferenceCollection::AddDataReadReference (const FVertexName & InName, const TDataReadReference< DataType > & InDataReference) inline
Add a readable data reference to the collection.
Parameters
InName - Name of data reference. @InDataReference - Readable data reference.
Definition at line 29 of file MetasoundDataReferenceCollection.h.
References AddDataReference(), InName, and MoveTemp().
Referenced by AddDataReadReference().
AddDataReadReference() [2/2]
template<typename DataType> void Metasound::FDataReferenceCollection::AddDataReadReference (const FVertexName & InName, const TDataWriteReference< DataType > & InDataReference) inline
Add a readable data reference to the collection.
Parameters
InName - Name of data reference. @InDataReference - Writable data reference.
Definition at line 42 of file MetasoundDataReferenceCollection.h.
References AddDataReadReference(), and InName.
AddDataReadReferenceFrom()
METASOUNDGRAPHCORE_API bool Metasound::FDataReferenceCollection::AddDataReadReferenceFrom (const FVertexName & InLocalName, const FDataReferenceCollection & InOtherCollection, const FVertexName & InOtherName, const FName & InOtherTypeName)
Add a readable data reference from another collection.
Parameters
InLocalName - Name to give data added to this collection.
InOtherCollection - Collection which contains the desired data reference.
InOtherName - Name of desired data in other collection.
InOtherType - TypeName of desired data.
Returns
True if the data was successfully added. False otherwise.
References UE_API.
AddDataReference()
METASOUNDGRAPHCORE_API void Metasound::FDataReferenceCollection::AddDataReference (const FVertexName & InName, FAnyDataReference && InDataReference)
Add a data reference to this collection.
References InName, and UE_API.
Referenced by AddDataReadReference(), and AddDataWriteReference().
AddDataWriteReference()
template<typename DataType> void Metasound::FDataReferenceCollection::AddDataWriteReference (const FVertexName & InName, const TDataWriteReference< DataType > & InDataReference) inline
Add a writable data reference to the collection.
Parameters
InName - Name of data reference. @InDataReference - Writable data reference.
Definition at line 55 of file MetasoundDataReferenceCollection.h.
References AddDataReference(), InName, and MoveTemp().
AddDataWriteReferenceFrom()
METASOUNDGRAPHCORE_API bool Metasound::FDataReferenceCollection::AddDataWriteReferenceFrom (const FVertexName & InLocalName, const FDataReferenceCollection & InOtherCollection, const FVertexName & InOtherName, const FName & InOtherTypeName)
Add a writable data reference from another collection.
Parameters
InLocalName - Name to give data added to this collection.
InOtherCollection - Collection which contains the desired data reference.
InOtherName - Name of desired data in other collection.
InOtherType - TypeName of desired data.
Returns
True if the data was successfully added. False otherwise.
References UE_API.
ContainsDataReadReference() [1/2]
template<typename DataType> bool Metasound::FDataReferenceCollection::ContainsDataReadReference (const FVertexName & InName) const inline
Query whether a readable data reference is within the collection.
Parameters
InName - Name of the data.
Returns
True if the data exists in the collection. False otherwise.
Definition at line 118 of file MetasoundDataReferenceCollection.h.
References FindDataReference(), InName, Metasound::IsDataReferenceOfType(), Metasound::Read, Metasound::Value, and Metasound::Write.
ContainsDataReadReference() [2/2]
METASOUNDGRAPHCORE_API bool Metasound::FDataReferenceCollection::ContainsDataReadReference (const FVertexName & InName, const FName & InTypeName) const
Query whether a readable data reference is within the collection.
Parameters
InName - Name of the data.
InTypeName - TypeName of teh data.
Returns
True if the data exists in the collection. False otherwise.
References InName, and UE_API.
Referenced by GetDataReadReferenceOrConstruct(), and GetDataReadReferenceOrConstructWithVertexDefault().
ContainsDataWriteReference() [1/2]
template<typename DataType> bool Metasound::FDataReferenceCollection::ContainsDataWriteReference (const FVertexName & InName) const inline
Query whether a writable data reference is within the collection.
Parameters
InName - Name of the data.
Returns
True if the data exists in the collection. False otherwise.
Definition at line 139 of file MetasoundDataReferenceCollection.h.
References FindDataReference(), InName, Metasound::IsDataReferenceOfType(), and Metasound::Write.
ContainsDataWriteReference() [2/2]
METASOUNDGRAPHCORE_API bool Metasound::FDataReferenceCollection::ContainsDataWriteReference (const FVertexName & InName, const FName & InTypeName) const
Query whether a writable data reference is within the collection.
Parameters
InName - Name of the data.
InTypeName - TypeName of teh data.
Returns
True if the data exists in the collection. False otherwise.
References InName, and UE_API.
Referenced by GetDataWriteReferenceOrConstruct().
FindDataReference()
METASOUNDGRAPHCORE_API const FAnyDataReference * Metasound::FDataReferenceCollection::FindDataReference (const FVertexName & InName) const
Returns pointer to data reference if it exists for a given vertex name.
If no data reference exists for the given vertex name, a nullptr is returned.
References InName, and UE_API.
Referenced by ContainsDataReadReference(), ContainsDataWriteReference(), GetDataReadReference(), and GetDataWriteReference().
GetDataReadReference()
template<typename DataType> TDataReadReference< DataType > Metasound::FDataReferenceCollection::GetDataReadReference (const FVertexName & InName) const inline
Returns a readable data ref from the collection.
Parameters
InName - Name of readable data.
Returns
A readable data reference.
Definition at line 160 of file MetasoundDataReferenceCollection.h.
References check, FindDataReference(), Metasound::FAnyDataReference::GetDataReadReference(), and InName.
Referenced by GetDataReadReferenceOrConstruct(), and GetDataReadReferenceOrConstructWithVertexDefault().
GetDataReadReferenceOrConstruct()
template<typename DataType, typename... ConstructorArgTypes> TDataReadReference< DataType > Metasound::FDataReferenceCollection::GetDataReadReferenceOrConstruct (FVertexName InName, ConstructorArgTypes &&... ConstructorArgs) const inline
Returns a readable data ref from the collection or construct one if one is not there.
Parameters
InName - Name of readable data.
ConstructorArgs - Arguments to pass to constructor of TDataReadReference<DataType>
Returns
A readable data reference.
Definition at line 177 of file MetasoundDataReferenceCollection.h.
References ContainsDataReadReference(), Forward(), GetDataReadReference(), and InName.
GetDataReadReferenceOrConstructWithVertexDefault()
template<typename DataType> TDataReadReference< DataType > Metasound::FDataReferenceCollection::GetDataReadReferenceOrConstructWithVertexDefault (const FInputVertexInterface & InputVertices, FVertexName InName, const FOperatorSettings & InSettings) const inline
Returns a readable data ref from the collection or construct one if one is not there with the default provided from the given input vertex collection.
Parameters
InputVertices - Collection of input vertices to retrieve default from if reference is not available
InName - Name of readable data.
InSettings - OperatorSettings of Metasound Operator
Returns
A readable data reference.
Definition at line 201 of file MetasoundDataReferenceCollection.h.
References Metasound::TVertexInterfaceImpl< VertexType >::Contains(), ContainsDataReadReference(), Metasound::FLiteral::CreateInvalid(), ensure, GetDataReadReference(), and InName.
GetDataWriteReference()
template<typename DataType> TDataWriteReference< DataType > Metasound::FDataReferenceCollection::GetDataWriteReference (const FVertexName & InName) const inline
Returns a writable data ref from the collection.
Parameters
InName - Name of readable data.
Returns
A readable data reference.
Definition at line 229 of file MetasoundDataReferenceCollection.h.
References check, FindDataReference(), Metasound::FAnyDataReference::GetDataWriteReference(), and InName.
Referenced by GetDataWriteReferenceOrConstruct().
GetDataWriteReferenceOrConstruct()
template<typename DataType, typename... ConstructorArgTypes> TDataWriteReference< DataType > Metasound::FDataReferenceCollection::GetDataWriteReferenceOrConstruct (const FVertexName & InName, ConstructorArgTypes &&... ConstructorArgs) const inline
Returns a writable data ref from the collection or construct one if one is not there.
Parameters
InName - Name of readable data.
ConstructorArgs - Arguments to pass to constructor of TDataWriteReference<DataType>
Returns
A readable data reference.
Definition at line 246 of file MetasoundDataReferenceCollection.h.
References ContainsDataWriteReference(), Forward(), GetDataWriteReference(), and InName.
Field Documentation
DataRefMap
FDataReferenceMap Metasound::FDataReferenceCollection::DataRefMap private
Definition at line 263 of file MetasoundDataReferenceCollection.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundDataReferenceCollection.h