Unreal Engine 5.6 C++ API: FMultiSizeIndexContainer Class Reference
FMultiSizeIndexContainer Class Reference
Skeletal mesh index buffers are 16 bit by default and 32 bit when called for.
#include "MultiSizeIndexContainer.h"
Public Member Functions
FMultiSizeIndexContainer ()
FMultiSizeIndexContainer (const FMultiSizeIndexContainer &Other)
~FMultiSizeIndexContainer ()
void CopyIndexBuffer (const TArray< uint32 > &NewArray)
Populates the index buffer with a new set of indices.
void CreateIndexBuffer (uint8 DataTypeSize)
Creates a new index buffer.
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
uint8 GetDataTypeSize () const
Accessors.
FRawStaticIndexBuffer16or32Interface * GetIndexBuffer ()
const FRawStaticIndexBuffer16or32Interface * GetIndexBuffer () const
void GetIndexBuffer (TArray< uint32 > &OutArray) const
Returns a 32 bit version of the index buffer.
void GetIndexBufferData (FMultiSizeIndexContainerData &OutData) const
Retrieves index buffer related data.
void InitResources ()
Initialize the index buffer's render resources.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
bool IsIndexBufferValid () const
FMultiSizeIndexContainer & operator= (const FMultiSizeIndexContainer &Buffer)
void RebuildIndexBuffer (uint8 InDataTypeSize, const TArray< uint32 > &NewArray)
Repopulates the index buffer.
void ReleaseResources ()
Releases the index buffer's render resources.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void Serialize (FArchive &Ar, bool bNeedsCPUAccess)
Serialization.
void SerializeMetaData (FArchive &Ar, bool bNeedsCPUAccess)
void SetOwnerName (const FName &OwnerName)
SetOwnerName should be called before BeginInitResources for the owner name to be successfully tracked.
Private Attributes
uint8 DataTypeSize
Size of the index buffer's index type (should be 2 or 4 bytes)
FRawStaticIndexBuffer16or32Interface * IndexBuffer
The vertex index buffer.
Friends
FArchive & operator<< (FArchive &Ar, FMultiSizeIndexContainer &Buffer)
Detailed Description
Skeletal mesh index buffers are 16 bit by default and 32 bit when called for.
This class adds a level of abstraction on top of the index buffers so that we can treat them all as 32 bit.
Definition at line 17 of file MultiSizeIndexContainer.h.
Constructor & Destructor Documentation
FMultiSizeIndexContainer() [1/2]
FMultiSizeIndexContainer::FMultiSizeIndexContainer () inline
Definition at line 20 of file MultiSizeIndexContainer.h.
References DataTypeSize, and IndexBuffer.
Referenced by FMultiSizeIndexContainer(), operator<<, and operator=().
~FMultiSizeIndexContainer()
FMultiSizeIndexContainer::~FMultiSizeIndexContainer ()
FMultiSizeIndexContainer() [2/2]
FMultiSizeIndexContainer::FMultiSizeIndexContainer (const FMultiSizeIndexContainer & Other)
References FMultiSizeIndexContainer(), and Other.
Member Function Documentation
CopyIndexBuffer()
void FMultiSizeIndexContainer::CopyIndexBuffer (const TArray< uint32 > & NewArray)
Populates the index buffer with a new set of indices.
CreateIndexBuffer()
void FMultiSizeIndexContainer::CreateIndexBuffer (uint8 DataTypeSize)
Creates a new index buffer.
References DataTypeSize.
CreateRHIBuffer()
FBufferRHIRef FMultiSizeIndexContainer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
GetDataTypeSize()
uint8 FMultiSizeIndexContainer::GetDataTypeSize () const inline
Accessors.
Definition at line 78 of file MultiSizeIndexContainer.h.
References DataTypeSize.
GetIndexBuffer() [1/3]
FRawStaticIndexBuffer16or32Interface * FMultiSizeIndexContainer::GetIndexBuffer () inline
Definition at line 79 of file MultiSizeIndexContainer.h.
References check, and IndexBuffer.
GetIndexBuffer() [2/3]
const FRawStaticIndexBuffer16or32Interface * FMultiSizeIndexContainer::GetIndexBuffer () const inline
Definition at line 84 of file MultiSizeIndexContainer.h.
References check, and IndexBuffer.
GetIndexBuffer() [3/3]
void FMultiSizeIndexContainer::GetIndexBuffer (TArray< uint32 > & OutArray) const
Returns a 32 bit version of the index buffer.
GetIndexBufferData()
void FMultiSizeIndexContainer::GetIndexBufferData (FMultiSizeIndexContainerData & OutData) const
Retrieves index buffer related data.
InitResources()
void FMultiSizeIndexContainer::InitResources ()
Initialize the index buffer's render resources.
InitRHIForStreaming()
void FMultiSizeIndexContainer::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher)
References IntermediateBuffer.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
IsIndexBufferValid()
bool FMultiSizeIndexContainer::IsIndexBufferValid () const inline
Definition at line 73 of file MultiSizeIndexContainer.h.
References IndexBuffer.
operator=()
FMultiSizeIndexContainer & FMultiSizeIndexContainer::operator= (const FMultiSizeIndexContainer & Buffer)
References FMultiSizeIndexContainer(), and Buffer.
RebuildIndexBuffer()
void FMultiSizeIndexContainer::RebuildIndexBuffer (uint8 InDataTypeSize, const TArray< uint32 > & NewArray)
Repopulates the index buffer.
ReleaseResources()
void FMultiSizeIndexContainer::ReleaseResources ()
Releases the index buffer's render resources.
ReleaseRHIForStreaming()
void FMultiSizeIndexContainer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
Serialize()
void FMultiSizeIndexContainer::Serialize (FArchive & Ar, bool bNeedsCPUAccess)
Serialization.
Parameters
Ar The archive with which to serialize.
bNeedsCPUAccess If true, the loaded data will remain in CPU memory even after the RHI index buffer has been initialized.
References Ar.
SerializeMetaData()
void FMultiSizeIndexContainer::SerializeMetaData (FArchive & Ar, bool bNeedsCPUAccess)
References Ar.
SetOwnerName()
void FMultiSizeIndexContainer::SetOwnerName (const FName & OwnerName)
SetOwnerName should be called before BeginInitResources for the owner name to be successfully tracked.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FMultiSizeIndexContainer & Buffer) friend
References FMultiSizeIndexContainer(), Ar, and Buffer.
Field Documentation
DataTypeSize
uint8 FMultiSizeIndexContainer::DataTypeSize private
Size of the index buffer's index type (should be 2 or 4 bytes)
Definition at line 109 of file MultiSizeIndexContainer.h.
Referenced by FMultiSizeIndexContainer(), CreateIndexBuffer(), and GetDataTypeSize().
IndexBuffer
FRawStaticIndexBuffer16or32Interface* FMultiSizeIndexContainer::IndexBuffer private
The vertex index buffer.
Definition at line 111 of file MultiSizeIndexContainer.h.
Referenced by FMultiSizeIndexContainer(), GetIndexBuffer(), GetIndexBuffer(), and IsIndexBufferValid().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/MultiSizeIndexContainer.h