Unreal Engine 5.6 C++ API: UE::Geometry::TMeshDijkstra< PointSetType > Class Template Reference
UE::Geometry::TMeshDijkstra< PointSetType > Class Template Reference
TMeshDijkstra computes graph distances on a mesh from seed point(s) using Dijkstra's algorithm.
#include "MeshDijkstra.h"
Data Structures
struct FGraphNode
struct FSeedPoint
FSeedPoint defines a seed point passed to the various compute methods below.
Public Member Functions
TMeshDijkstra (const PointSetType *PointSetIn)
Construct TMeshDijkstra for the given PointSet.
void ComputeToMaxDistance (const TArray< FSeedPoint > &SeedPointsIn, double ComputeToMaxDistanceIn)
Computes graph distances outwards from seed points to all points that are less/equal to ComputeToMaxDistance from the seed.
void ComputeToMaxDistance (const TArray< FVector2d > &SeedPointsIn, double ComputeToMaxDistanceIn)
Computes graph distances outwards from seed points to all points that are less/equal to ComputeToMaxDistance from the seed.
bool ComputeToTargetPoint (const TArray< FSeedPoint > &SeedPointsIn, int32 TargetPointID, double ComputeToMaxDistanceIn=TNumericLimits< double >::Max())
Computes graph distances outwards from seed points to all points that are less/equal to ComputeToMaxDistance from the seed, or until TargetPointID is reached.
bool FindPathToNearestSeed (int32 PointID, TArray< int32 > &PathToSeedOut, int32 MaxLength=100000)
Find path from a point to the nearest seed point.
double GetDistance (int32 PointID) const
double GetMaxGraphDistance () const
int32 GetMaxGraphDistancePointID () const
int32 GetSeedExternalIDForPointSetID (int32 PointID)
bool HasDistance (int32 PointID) const
void Reset ()
Reset internal data structures but keep allocated memory.
Static Public Member Functions
static double InvalidDistance ()
Data Fields
bool bEnableDistanceWeighting = false
If enabled, when computing local point-pair distances, GetWeightedDistanceFunc() will be called with the Euclidean distance to allow for alternative metrics.
TUniqueFunction< FVector3d(int32)> GetPositionFunc
Return the 3D Position of a given Point in the PointSet.
TUniqueFunction< double(int32 FromVID, int32 ToVID, int32 SeedVID, double EuclideanDistance)> GetWeightedDistanceFunc
Called when computing pairwise point distances between neighbours FromVID and ToVID, to allow for alternative distance metrics.
const PointSetType * PointSet
PointSet we are calculating on.
Private Member Functions
const FGraphNode * GetNodeForPointSetID (int32 PointSetID) const
FGraphNode * GetNodeForPointSetID (int32 PointSetID, bool bCreateIfMissing)
void UpdateNeighboursSparse (FGraphNode *Parent)
Private Attributes
TDynamicVector< FGraphNode > AllocatedNodes
TMap< int32, int32 > IDToNodeIndexMap
double MaxGraphDistance
int32 MaxGraphDistancePointID
FIndexPriorityQueue Queue
TArray< FSeedPoint > SeedPoints
Detailed Description
template<class PointSetType>
class UE::Geometry::TMeshDijkstra< PointSetType >
TMeshDijkstra computes graph distances on a mesh from seed point(s) using Dijkstra's algorithm.
Templated on the point set type, which must provide positions, normals, and neighbours. Currently will only work for FDynamicMesh3 and FDynamicPointSet3 because of call to PointSetType->VtxVerticesItr()
Definition at line 24 of file MeshDijkstra.h.
Constructor & Destructor Documentation
TMeshDijkstra()
template<class PointSetType> UE::Geometry::TMeshDijkstra< PointSetType >::TMeshDijkstra (const PointSetType * PointSetIn) inline
Construct TMeshDijkstra for the given PointSet.
We will hold a reference to this PointSet for the lifetime of the class.
Definition at line 55 of file MeshDijkstra.h.
References bEnableDistanceWeighting, UE::Geometry::Distance(), GetPositionFunc, GetWeightedDistanceFunc, MaxGraphDistance, MaxGraphDistancePointID, PointSet, and Queue.
Member Function Documentation
ComputeToMaxDistance() [1/2]
template<class PointSetType> void UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToMaxDistance (const TArray< FSeedPoint > & SeedPointsIn, double ComputeToMaxDistanceIn) inline
Computes graph distances outwards from seed points to all points that are less/equal to ComputeToMaxDistance from the seed.
Parameters
SeedPointsIn seed points used to initialize computation, ie geodesics propagate out from this point set
ComputeToMaxDistance target graph-distance radius, will not compute/set distances on points with graph-distance larger than this
Definition at line 105 of file MeshDijkstra.h.
References UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, check, ensure, GetNodeForPointSetID(), UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, TMathUtil< RealType >::Max(), MaxGraphDistance, MaxGraphDistancePointID, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::PointID, Queue, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::SeedPointID, SeedPoints, and UpdateNeighboursSparse().
Referenced by ComputeToMaxDistance().
ComputeToMaxDistance() [2/2]
template<class PointSetType> void UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToMaxDistance (const TArray< FVector2d > & SeedPointsIn, double ComputeToMaxDistanceIn) inline
Computes graph distances outwards from seed points to all points that are less/equal to ComputeToMaxDistance from the seed.
Parameters
SeedPointsIn 2D tuples that define seed points as (PointID, InitialDistance) pairs
ComputeToMaxDistance target graph-distance radius, will not compute/set distances on points with graph-distance larger than this
Definition at line 152 of file MeshDijkstra.h.
References ComputeToMaxDistance(), TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::SetNum(), X, and Y.
ComputeToTargetPoint()
template<class PointSetType> bool UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToTargetPoint (const TArray< FSeedPoint > & SeedPointsIn, int32 TargetPointID, double ComputeToMaxDistanceIn = TNumericLimits<double>::Max()) inline
Computes graph distances outwards from seed points to all points that are less/equal to ComputeToMaxDistance from the seed, or until TargetPointID is reached.
This is useful for finding shortest paths between two points
Parameters
SeedPointsIn seed points used to initialize computation, ie geodesics propagate out from this point set
TargetPointID the target point, computation stops when this point is reached
ComputeToMaxDistance target graph-distance radius, will not compute/set distances on points with graph-distance larger than this
Definition at line 173 of file MeshDijkstra.h.
References UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, check, ensure, GetNodeForPointSetID(), UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, TMathUtil< RealType >::Max(), MaxGraphDistance, MaxGraphDistancePointID, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::PointID, Queue, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::SeedPointID, SeedPoints, and UpdateNeighboursSparse().
FindPathToNearestSeed()
template<class PointSetType> bool UE::Geometry::TMeshDijkstra< PointSetType >::FindPathToNearestSeed (int32 PointID, TArray< int32 > & PathToSeedOut, int32 MaxLength = 100000) inline
Find path from a point to the nearest seed point.
Parameters
PointID starting point, assumption is that we have computed dijkstra to this point
PathToSeedOut path is returned here, includes PointID and seed point as last element
MaxLength if PathToSeedOut grows beyond this length, we abort the search
Returns
true if valid path was found
Definition at line 283 of file MeshDijkstra.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, GetNodeForPointSetID(), UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::ParentPointID, and TArray< InElementType, InAllocatorType >::Reset().
GetDistance()
template<class PointSetType> double UE::Geometry::TMeshDijkstra< PointSetType >::GetDistance (int32 PointID) const inline
Returns
the distance calculated for index PointID
Definition at line 270 of file MeshDijkstra.h.
References UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, GetNodeForPointSetID(), UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, and InvalidDistance().
GetMaxGraphDistance()
template<class PointSetType> double UE::Geometry::TMeshDijkstra< PointSetType >::GetMaxGraphDistance () const inline
Returns
the maximum graph distance encountered during the computation
Definition at line 227 of file MeshDijkstra.h.
References MaxGraphDistance.
GetMaxGraphDistancePointID()
template<class PointSetType> int32 UE::Geometry::TMeshDijkstra< PointSetType >::GetMaxGraphDistancePointID () const inline
Returns
vertex id associated with the maximum graph distance returned by GetMaxGraphDistance()
Definition at line 236 of file MeshDijkstra.h.
References MaxGraphDistancePointID.
GetNodeForPointSetID() [1/2]
template<class PointSetType> const FGraphNode * UE::Geometry::TMeshDijkstra< PointSetType >::GetNodeForPointSetID (int32 PointSetID) const inline private
Definition at line 366 of file MeshDijkstra.h.
References AllocatedNodes, and IDToNodeIndexMap.
GetNodeForPointSetID() [2/2]
template<class PointSetType> FGraphNode * UE::Geometry::TMeshDijkstra< PointSetType >::GetNodeForPointSetID (int32 PointSetID, bool bCreateIfMissing) inline private
Definition at line 341 of file MeshDijkstra.h.
References AllocatedNodes, and IDToNodeIndexMap.
Referenced by ComputeToMaxDistance(), ComputeToTargetPoint(), FindPathToNearestSeed(), GetDistance(), GetSeedExternalIDForPointSetID(), HasDistance(), and UpdateNeighboursSparse().
GetSeedExternalIDForPointSetID()
template<class PointSetType> int32 UE::Geometry::TMeshDijkstra< PointSetType >::GetSeedExternalIDForPointSetID (int32 PointID) inline
Returns
the ExternalID of the SeedPoint that is closest to PointID, or -1 if PointID does not have a valid graph distance
Definition at line 245 of file MeshDijkstra.h.
References UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, GetNodeForPointSetID(), UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::SeedPointID, and SeedPoints.
HasDistance()
template<class PointSetType> bool UE::Geometry::TMeshDijkstra< PointSetType >::HasDistance (int32 PointID) const inline
Returns
true if the distance for index PointID was calculated
Definition at line 260 of file MeshDijkstra.h.
References UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, and GetNodeForPointSetID().
InvalidDistance()
template<class PointSetType> double UE::Geometry::TMeshDijkstra< PointSetType >::InvalidDistance () inline static
Returns
distance value that indicates invalid or uncomputed distance
Definition at line 71 of file MeshDijkstra.h.
Referenced by GetDistance().
Reset()
template<class PointSetType> void UE::Geometry::TMeshDijkstra< PointSetType >::Reset () inline
Reset internal data structures but keep allocated memory.
Definition at line 76 of file MeshDijkstra.h.
References AllocatedNodes, IDToNodeIndexMap, MaxGraphDistance, MaxGraphDistancePointID, and Queue.
UpdateNeighboursSparse()
template<class PointSetType> void UE::Geometry::TMeshDijkstra< PointSetType >::UpdateNeighboursSparse (FGraphNode * Parent) inline private
Definition at line 376 of file MeshDijkstra.h.
References bEnableDistanceWeighting, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::bFrozen, Distance, GetNodeForPointSetID(), GetPositionFunc, GetWeightedDistanceFunc, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::GraphDistance, Parent, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::ParentPointID, PointSet, Queue, UE::Geometry::TMeshDijkstra< PointSetType >::FGraphNode::SeedPointID, and SeedPoints.
Referenced by ComputeToMaxDistance(), and ComputeToTargetPoint().
Field Documentation
AllocatedNodes
template<class PointSetType> TDynamicVector<FGraphNode> UE::Geometry::TMeshDijkstra< PointSetType >::AllocatedNodes private
Definition at line 329 of file MeshDijkstra.h.
Referenced by GetNodeForPointSetID(), GetNodeForPointSetID(), and Reset().
bEnableDistanceWeighting
template<class PointSetType> bool UE::Geometry::TMeshDijkstra< PointSetType >::bEnableDistanceWeighting = false
If enabled, when computing local point-pair distances, GetWeightedDistanceFunc() will be called with the Euclidean distance to allow for alternative metrics.
Definition at line 41 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), and UpdateNeighboursSparse().
GetPositionFunc
template<class PointSetType> TUniqueFunction<FVector3d(int32)> UE::Geometry::TMeshDijkstra< PointSetType >::GetPositionFunc
Return the 3D Position of a given Point in the PointSet.
This function is set to PointSet->GetVertex() in the constructor below, but can be replaced with an external function if necessary (eg to provide deformed mesh positions, etc)
Definition at line 35 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), and UpdateNeighboursSparse().
GetWeightedDistanceFunc
template<class PointSetType> TUniqueFunction<double(int32 FromVID, int32 ToVID, int32 SeedVID, double EuclideanDistance)> UE::Geometry::TMeshDijkstra< PointSetType >::GetWeightedDistanceFunc
Called when computing pairwise point distances between neighbours FromVID and ToVID, to allow for alternative distance metrics.
SeedVID is the seed point that FromVID's value was propagated from (ie point reached by gradient walk) EuclideanDistance is the distance between the two input points
Definition at line 48 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), and UpdateNeighboursSparse().
IDToNodeIndexMap
template<class PointSetType> TMap<int32, int32> UE::Geometry::TMeshDijkstra< PointSetType >::IDToNodeIndexMap private
Definition at line 328 of file MeshDijkstra.h.
Referenced by GetNodeForPointSetID(), GetNodeForPointSetID(), and Reset().
MaxGraphDistance
template<class PointSetType> double UE::Geometry::TMeshDijkstra< PointSetType >::MaxGraphDistance private
Definition at line 337 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), ComputeToMaxDistance(), ComputeToTargetPoint(), GetMaxGraphDistance(), and Reset().
MaxGraphDistancePointID
template<class PointSetType> int32 UE::Geometry::TMeshDijkstra< PointSetType >::MaxGraphDistancePointID private
Definition at line 339 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), ComputeToMaxDistance(), ComputeToTargetPoint(), GetMaxGraphDistancePointID(), and Reset().
PointSet
template<class PointSetType> const PointSetType* UE::Geometry::TMeshDijkstra< PointSetType >::PointSet
PointSet we are calculating on.
Definition at line 28 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), and UpdateNeighboursSparse().
Queue
template<class PointSetType> FIndexPriorityQueue UE::Geometry::TMeshDijkstra< PointSetType >::Queue private
Definition at line 332 of file MeshDijkstra.h.
Referenced by TMeshDijkstra(), ComputeToMaxDistance(), ComputeToTargetPoint(), Reset(), and UpdateNeighboursSparse().
SeedPoints
template<class PointSetType> TArray<FSeedPoint> UE::Geometry::TMeshDijkstra< PointSetType >::SeedPoints private
Definition at line 334 of file MeshDijkstra.h.
Referenced by ComputeToMaxDistance(), ComputeToTargetPoint(), GetSeedExternalIDForPointSetID(), and UpdateNeighboursSparse().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Parameterization/MeshDijkstra.h