Unreal Engine 5.6 C++ API: TBitArray< Allocator >::FReverseIterator Class Reference
TBitArray< Allocator >::FReverseIterator Class Reference
Reverse iterator.
#include "BitArray.h"
Public Member Functions
FORCEINLINE FReverseIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND)
FORCEINLINE FReverseIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 StartIndex)
FORCEINLINE int32 GetIndex () const
FORCEINLINE FBitReference GetValue () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE FBitReference operator* () const
FORCEINLINE FReverseIterator & operator++ ()
Public Member Functions inherited from FRelativeBitReference
FORCEINLINE FRelativeBitReference (int32 BitIndex)
FORCEINLINE bool operator!= (FRelativeBitReference Other) const
FORCEINLINE bool operator== (FRelativeBitReference Other) const
Private Attributes
TBitArray< Allocator > & Array
int32 Index
Additional Inherited Members
Data Fields inherited from FRelativeBitReference
uint32 Mask
int32 WordIndex
Detailed Description
template<typename Allocator>
class TBitArray< Allocator >::FReverseIterator
Reverse iterator.
Definition at line 1525 of file BitArray.h.
Constructor & Destructor Documentation
FReverseIterator() [1/2]
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FReverseIterator::FReverseIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND) inline explicit nodiscard
Definition at line 1528 of file BitArray.h.
References FRelativeBitReference::FRelativeBitReference(), TBitArray< Allocator >::TBitArray(), Array, FORCEINLINE, Index, TBitArray< Allocator >::Num(), and UE_LIFETIMEBOUND.
Referenced by operator++().
FReverseIterator() [2/2]
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FReverseIterator::FReverseIterator (TBitArray< Allocator > &InArray UE_LIFETIMEBOUND, int32 StartIndex) inline explicit nodiscard
Definition at line 1535 of file BitArray.h.
References FRelativeBitReference::FRelativeBitReference(), TBitArray< Allocator >::TBitArray(), Array, FORCEINLINE, Index, and UE_LIFETIMEBOUND.
Member Function Documentation
GetIndex()
template<typename Allocator> FORCEINLINE int32 TBitArray< Allocator >::FReverseIterator::GetIndex () const inline nodiscard
Definition at line 1573 of file BitArray.h.
References FORCEINLINE, and Index.
GetValue()
template<typename Allocator> FORCEINLINE FBitReference TBitArray< Allocator >::FReverseIterator::GetValue () const inline nodiscard
Definition at line 1572 of file BitArray.h.
References Array, and FORCEINLINE.
Referenced by operator*().
operator bool()
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::FReverseIterator::operator bool () const inline explicit nodiscard
conversion to "bool" returning true if the iterator is valid.
Definition at line 1561 of file BitArray.h.
References FORCEINLINE, and Index.
operator!()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::FReverseIterator::operator! () const inline nodiscard
inverse of the "bool" operator
Definition at line 1567 of file BitArray.h.
References bool, and FORCEINLINE.
operator*()
template<typename Allocator> FORCEINLINE FBitReference TBitArray< Allocator >::FReverseIterator::operator* () const inline nodiscard
Definition at line 1555 of file BitArray.h.
References FORCEINLINE, and GetValue().
operator++()
template<typename Allocator> FORCEINLINE FReverseIterator & TBitArray< Allocator >::FReverseIterator::operator++ () inline
Definition at line 1542 of file BitArray.h.
References FReverseIterator(), FORCEINLINE, Index, NumBitsPerDWORD, and FRelativeBitReference::WordIndex.
Field Documentation
Array
template<typename Allocator> TBitArray<Allocator>& TBitArray< Allocator >::FReverseIterator::Array private
Definition at line 1575 of file BitArray.h.
Referenced by FReverseIterator(), FReverseIterator(), and GetValue().
Index
template<typename Allocator> int32 TBitArray< Allocator >::FReverseIterator::Index private
Definition at line 1576 of file BitArray.h.
Referenced by FReverseIterator(), FReverseIterator(), GetIndex(), operator bool(), and operator++().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/BitArray.h