Unreal Engine 5.6 C++ API: FReload Class Reference
FReload Class Reference
#include "ReloadUtilities.h"
Data Structures
struct FBlueprintUpdateInfo
struct FNativeFuncPtrMapKeyFuncs
struct FReinstanceStats
Public Types
using TFunctionRemap = TMap<FNativeFuncPtr, FNativeFuncPtr, FDefaultSetAllocator, FNativeFuncPtrMapKeyFuncs>
Public Member Functions
UNREALED_API FReload (EActiveReloadType InType, const TCHAR *InPrefix, const TArray< UPackage * > &InPackages, FOutputDevice &InAr)
UNREALED_API FReload (EActiveReloadType InType, const TCHAR *InPrefix, FOutputDevice &InAr)
virtual UNREALED_API ~FReload ()
UNREALED_API void Finalize (bool bRunGC=true)
Perform any finalize processing for reloading.
virtual UNREALED_API bool GetEnableReinstancing (bool bHasChanged) const override
Return if re-instancing is to be allowed.
UNREALED_API const TArray< UClass * > & GetNewClasses () override
Return an array of the new classes.
virtual const TCHAR * GetPrefix () const override
When classes, structures, and enumerations are renamed, the given prefix is applied.
virtual UNREALED_API const UObject * GetReinstancedCDO (const UObject *CDO) override
virtual UNREALED_API UObject * GetReinstancedCDO (UObject *CDO) override
For a given CDO, return the new CDO if it has been re-instanced.
virtual UNREALED_API const TMap< UClass *, UClass * > & GetReinstancedClasses () override
Return a map of the reinstanced classes where the old class is the key and the new class is the value.
virtual EActiveReloadType GetType () const override
Returns the type of reload currently in progress.
bool HasReinstancingOccurred () const
Return true if anything was re-instanced.
virtual UNREALED_API void NotifyChange (UClass *New, UClass *Old) override
Invoke to register a new or changed class, enumeration, or structure for re-instancing.
virtual UNREALED_API void NotifyChange (UEnum *New, UEnum *Old) override
virtual UNREALED_API void NotifyChange (UPackage *New, UPackage *Old) override
virtual UNREALED_API void NotifyChange (UScriptStruct *New, UScriptStruct *Old) override
virtual UNREALED_API void NotifyFunctionRemap (FNativeFuncPtr NewFunctionPointer, FNativeFuncPtr OldFunctionPointer) override
Invoke when a duplicate function has been detected.
virtual UNREALED_API void Reinstance () override
Perform the re-instancing.
UNREALED_API void Reset ()
If you wish to reuse the same reload object, invoke this method to reset the state.
void SetEnableReinstancing (bool bInEnableReinstancing)
Enable/Disable the support for reinstancing.
void SetSendReloadCompleteNotification (bool bSend)
Set the sending of the complete notification.
Public Member Functions inherited from IReload
virtual ~IReload ()=default
Private Member Functions
UNREALED_API void ReplaceReferencesToReconstructedCDOs ()
Finds all references to old CDOs and replaces them with the new ones.
UNREALED_API void UpdateStats (FReinstanceStats &Stats, void *New, void *Old)
Based on the pointers, update the given stat.
Static Private Member Functions
static UNREALED_API void FormatStat (FStringBuilderBase &Out, const TCHAR *Singular, const TCHAR *Plural, const TCHAR *What, int32 Value)
Helper method to format a specific stat.
static UNREALED_API void FormatStats (FStringBuilderBase &Out, const TCHAR *Singular, const TCHAR *Plural, const FReinstanceStats &Stats)
Helper method to format all the stats.
Private Attributes
FOutputDevice & Ar
Output device for any logging.
bool bCollectPackages
If true, we have to collect the package list from the context.
bool bEnabledMessage = false
bool bEnableReinstancing = true
If true, reinstancing is enabled.
bool bHasReinstancingOccurred = false
bool bSendReloadComplete = true
If true, send reload complete notification.
FReinstanceStats ClassStats
FReinstanceStats EnumStats
TFunctionRemap FunctionRemap
Map from old function pointer to new function pointer for hot reload.
TArray< UClass * > NewClasses
Array of new classes.
int32 NumFunctionsRemapped = 0
int32 NumScriptStructsRemapped = 0
TSet< UPackage * > Packages
List of packages affected by the reload.
FReinstanceStats PackageStats
const TCHAR * Prefix = nullptr
Prefix applied when renaming objects.
TMap< UObject *, UObject * > ReconstructedCDOsMap
Map of the reconstructed CDOs during the reinstancing process.
TMap< UObject *, UObject * > ReinstancedCDOsMap
Map of new CDOs where classes where changed.
TMap< UClass *, UClass * > ReinstancedClasses
Map from old class to new class.
TMap< UEnum *, UEnum * > ReinstancedEnums
Map from old enum to new enum.
TMap< UScriptStruct *, UScriptStruct * > ReinstancedStructs
Map from old struct to new struct.
FReinstanceStats StructStats
EActiveReloadType Type = EActiveReloadType::None
Type of the active reload.
Detailed Description
Definition at line 15 of file ReloadUtilities.h.
Member Typedef Documentation
TFunctionRemap
using FReload::TFunctionRemap = TMap<FNativeFuncPtr, FNativeFuncPtr, FDefaultSetAllocator, FNativeFuncPtrMapKeyFuncs>
Definition at line 26 of file ReloadUtilities.h.
Constructor & Destructor Documentation
FReload() [1/2]
UNREALED_API FReload::FReload (EActiveReloadType InType, const TCHAR * InPrefix, const TArray< UPackage * > & InPackages, FOutputDevice & InAr)
FReload() [2/2]
UNREALED_API FReload::FReload (EActiveReloadType InType, const TCHAR * InPrefix, FOutputDevice & InAr)
~FReload()
virtual UNREALED_API FReload::~FReload () virtual
Member Function Documentation
Finalize()
UNREALED_API void FReload::Finalize (bool bRunGC = true)
Perform any finalize processing for reloading.
FormatStat()
UNREALED_API void FReload::FormatStat (FStringBuilderBase & Out, const TCHAR * Singular, const TCHAR * Plural, const TCHAR * What, int32 Value) static private
Helper method to format a specific stat.
References Value.
FormatStats()
UNREALED_API void FReload::FormatStats (FStringBuilderBase & Out, const TCHAR * Singular, const TCHAR * Plural, const FReinstanceStats & Stats) static private
Helper method to format all the stats.
GetEnableReinstancing()
virtual UNREALED_API bool FReload::GetEnableReinstancing (bool bHasChanged) const override virtual
Return if re-instancing is to be allowed.
Implements IReload.
GetNewClasses()
UNREALED_API const TArray< UClass * > & FReload::GetNewClasses () inline override virtual
Return an array of the new classes.
Implements IReload.
Definition at line 53 of file ReloadUtilities.h.
References NewClasses.
GetPrefix()
virtual const TCHAR * FReload::GetPrefix () const inline override virtual
When classes, structures, and enumerations are renamed, the given prefix is applied.
Implements IReload.
Definition at line 37 of file ReloadUtilities.h.
References Prefix.
GetReinstancedCDO() [1/2]
virtual UNREALED_API const UObject * FReload::GetReinstancedCDO (const UObject * CDO) override virtual
Implements IReload.
GetReinstancedCDO() [2/2]
virtual UNREALED_API UObject * FReload::GetReinstancedCDO (UObject * CDO) override virtual
For a given CDO, return the new CDO if it has been re-instanced.
If it hasn't been re-instanced, then the supplied CDO will be returned. If a non-CDO object is passed in, it will be returned as is.
Implements IReload.
GetReinstancedClasses()
virtual UNREALED_API const TMap< UClass *, UClass * > & FReload::GetReinstancedClasses () inline override virtual
Return a map of the reinstanced classes where the old class is the key and the new class is the value.
Implements IReload.
Definition at line 48 of file ReloadUtilities.h.
References ReinstancedClasses.
GetType()
virtual EActiveReloadType FReload::GetType () const inline override virtual
Returns the type of reload currently in progress.
Implements IReload.
Definition at line 36 of file ReloadUtilities.h.
References Type.
HasReinstancingOccurred()
bool FReload::HasReinstancingOccurred () const inline
Return true if anything was re-instanced.
Definition at line 87 of file ReloadUtilities.h.
References bHasReinstancingOccurred.
NotifyChange() [1/4]
virtual UNREALED_API void FReload::NotifyChange (UClass * New, UClass * Old) override virtual
Invoke to register a new or changed class, enumeration, or structure for re-instancing.
Implements IReload.
References New().
NotifyChange() [2/4]
virtual UNREALED_API void FReload::NotifyChange (UEnum * New, UEnum * Old) override virtual
Implements IReload.
References New().
NotifyChange() [3/4]
virtual UNREALED_API void FReload::NotifyChange (UPackage * New, UPackage * Old) override virtual
Implements IReload.
References New().
NotifyChange() [4/4]
virtual UNREALED_API void FReload::NotifyChange (UScriptStruct * New, UScriptStruct * Old) override virtual
Implements IReload.
References New().
NotifyFunctionRemap()
virtual UNREALED_API void FReload::NotifyFunctionRemap (FNativeFuncPtr NewFunctionPointer, FNativeFuncPtr OldFunctionPointer) override virtual
Invoke when a duplicate function has been detected.
Implements IReload.
Reinstance()
virtual UNREALED_API void FReload::Reinstance () override virtual
Perform the re-instancing.
Implements IReload.
ReplaceReferencesToReconstructedCDOs()
UNREALED_API void FReload::ReplaceReferencesToReconstructedCDOs () private
Finds all references to old CDOs and replaces them with the new ones.
Skipping UBlueprintGeneratedClass::OverridenArchetypeForCDO as it's the only one needed.
Reset()
UNREALED_API void FReload::Reset ()
If you wish to reuse the same reload object, invoke this method to reset the state.
SetEnableReinstancing()
void FReload::SetEnableReinstancing (bool bInEnableReinstancing) inline
Enable/Disable the support for reinstancing.
Definition at line 79 of file ReloadUtilities.h.
References bEnableReinstancing.
SetSendReloadCompleteNotification()
void FReload::SetSendReloadCompleteNotification (bool bSend) inline
Set the sending of the complete notification.
Definition at line 71 of file ReloadUtilities.h.
References bSendReloadComplete.
UpdateStats()
UNREALED_API void FReload::UpdateStats (FReinstanceStats & Stats, void * New, void * Old) private
Based on the pointers, update the given stat.
References New().
Field Documentation
Ar
FOutputDevice& FReload::Ar private
Output device for any logging.
Definition at line 148 of file ReloadUtilities.h.
bCollectPackages
bool FReload::bCollectPackages private
If true, we have to collect the package list from the context.
Definition at line 172 of file ReloadUtilities.h.
bEnabledMessage
bool FReload::bEnabledMessage = false mutable private
Definition at line 186 of file ReloadUtilities.h.
bEnableReinstancing
bool FReload::bEnableReinstancing = true private
If true, reinstancing is enabled.
Definition at line 178 of file ReloadUtilities.h.
Referenced by SetEnableReinstancing().
bHasReinstancingOccurred
bool FReload::bHasReinstancingOccurred = false mutable private
Definition at line 187 of file ReloadUtilities.h.
Referenced by HasReinstancingOccurred().
bSendReloadComplete
bool FReload::bSendReloadComplete = true private
If true, send reload complete notification.
Definition at line 175 of file ReloadUtilities.h.
Referenced by SetSendReloadCompleteNotification().
ClassStats
FReinstanceStats FReload::ClassStats private
Definition at line 180 of file ReloadUtilities.h.
EnumStats
FReinstanceStats FReload::EnumStats private
Definition at line 181 of file ReloadUtilities.h.
FunctionRemap
TFunctionRemap FReload::FunctionRemap private
Map from old function pointer to new function pointer for hot reload.
Definition at line 151 of file ReloadUtilities.h.
NewClasses
TArray<UClass*> FReload::NewClasses private
Array of new classes.
Definition at line 163 of file ReloadUtilities.h.
Referenced by GetNewClasses().
NumFunctionsRemapped
int32 FReload::NumFunctionsRemapped = 0 private
Definition at line 184 of file ReloadUtilities.h.
NumScriptStructsRemapped
int32 FReload::NumScriptStructsRemapped = 0 private
Definition at line 185 of file ReloadUtilities.h.
Packages
TSet<UPackage*> FReload::Packages private
List of packages affected by the reload.
Definition at line 145 of file ReloadUtilities.h.
PackageStats
FReinstanceStats FReload::PackageStats private
Definition at line 183 of file ReloadUtilities.h.
Prefix
const TCHAR* FReload::Prefix = nullptr private
Prefix applied when renaming objects.
Definition at line 142 of file ReloadUtilities.h.
Referenced by GetPrefix().
ReconstructedCDOsMap
TMap<UObject*, UObject*> FReload::ReconstructedCDOsMap private
Map of the reconstructed CDOs during the reinstancing process.
Definition at line 154 of file ReloadUtilities.h.
ReinstancedCDOsMap
TMap<UObject*, UObject*> FReload::ReinstancedCDOsMap private
Map of new CDOs where classes where changed.
Definition at line 157 of file ReloadUtilities.h.
ReinstancedClasses
TMap<UClass*, UClass*> FReload::ReinstancedClasses private
Map from old class to new class.
New class may be null
Definition at line 160 of file ReloadUtilities.h.
Referenced by GetReinstancedClasses().
ReinstancedEnums
TMap<UEnum*, UEnum*> FReload::ReinstancedEnums private
Map from old enum to new enum.
New enum may be null
Definition at line 169 of file ReloadUtilities.h.
ReinstancedStructs
TMap<UScriptStruct*, UScriptStruct*> FReload::ReinstancedStructs private
Map from old struct to new struct.
New struct may be null
Definition at line 166 of file ReloadUtilities.h.
StructStats
FReinstanceStats FReload::StructStats private
Definition at line 182 of file ReloadUtilities.h.
Type
EActiveReloadType FReload::Type = EActiveReloadType::None private
Type of the active reload.
Definition at line 139 of file ReloadUtilities.h.
Referenced by GetType().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Kismet2/ReloadUtilities.h