Unreal Engine 5.6 C++ API: UE::Cook::TMPCollectorClientMessageCallback< MessageType > Class Template Reference
UE::Cook::TMPCollectorClientMessageCallback< MessageType > Class Template Reference
An implementation of IMPCollector that uses an ICollectorMessage subclass to serialize the message, and directs messages received on the client to the given callback.
#include "MPCollector.h"
Public Member Functions
TMPCollectorClientMessageCallback (TUniqueFunction< void(FMPCollectorClientMessageContext &Context, bool bReadSuccessful, MessageType &&Message)> &&InCallback)
virtual void ClientReceiveMessage (FMPCollectorClientMessageContext &Context, bool bReadSuccessful, MessageType &&Message) override
Public Member Functions inherited from UE::Cook::IMPCollectorForMessage< MessageType >
virtual void ClientReceiveMessage (FMPCollectorClientMessageContext &Context, FCbObjectView Message) override
virtual const TCHAR * GetDebugName () const override
virtual FGuid GetMessageType () const override
virtual void ServerReceiveMessage (FMPCollectorServerMessageContext &Context, bool bReadSuccessful, MessageType &&Message)
virtual void ServerReceiveMessage (FMPCollectorServerMessageContext &Context, FCbObjectView Message) override
Public Member Functions inherited from UE::Cook::IMPCollector
virtual ~IMPCollector ()
virtual void ClientTick (FMPCollectorClientTickContext &Context)
virtual void ClientTickPackage (FMPCollectorClientTickPackageContext &Context)
virtual void ServerTick (FMPCollectorServerTickContext &Context)
virtual void ServerTickPackage (FMPCollectorServerTickPackageContext &Context)
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Private Attributes
TUniqueFunction< void(FMPCollectorClientMessageContext &Context, bool bReadSuccessful, MessageType &&Message)> Callback
Detailed Description
template<typename MessageType>
class UE::Cook::TMPCollectorClientMessageCallback< MessageType >
An implementation of IMPCollector that uses an ICollectorMessage subclass to serialize the message, and directs messages received on the client to the given callback.
Definition at line 292 of file MPCollector.h.
Constructor & Destructor Documentation
TMPCollectorClientMessageCallback()
template<typename MessageType> UE::Cook::TMPCollectorClientMessageCallback< MessageType >::TMPCollectorClientMessageCallback (TUniqueFunction< void(FMPCollectorClientMessageContext &Context, bool bReadSuccessful, MessageType &&Message)> && InCallback) inline
Definition at line 295 of file MPCollector.h.
References Callback, check, and MoveTemp().
Member Function Documentation
ClientReceiveMessage()
template<typename MessageType> virtual void UE::Cook::TMPCollectorClientMessageCallback< MessageType >::ClientReceiveMessage (FMPCollectorClientMessageContext & Context, bool bReadSuccessful, MessageType && Message) inline override virtual
Reimplemented from UE::Cook::IMPCollectorForMessage< MessageType >.
Definition at line 302 of file MPCollector.h.
References Callback, and MoveTemp().
Field Documentation
Callback
template<typename MessageType> TUniqueFunction<void(FMPCollectorClientMessageContext& Context, bool bReadSuccessful, MessageType&& Message)> UE::Cook::TMPCollectorClientMessageCallback< MessageType >::Callback private
Definition at line 309 of file MPCollector.h.
Referenced by TMPCollectorClientMessageCallback(), and ClientReceiveMessage().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Cooker/MPCollector.h