Unreal Engine 5.6 C++ API: FStructuredArchiveRecord Class Reference
FStructuredArchiveRecord Class Reference final
Represents a record in the structured archive.
#include "StructuredArchiveSlots.h"
Public Member Functions
FORCEINLINE FStructuredArchiveArray EnterArray (FArchiveFieldName Name, int32 &Num)
FORCEINLINE FStructuredArchiveSlot EnterField (FArchiveFieldName Name)
FORCEINLINE FStructuredArchiveMap EnterMap (FArchiveFieldName Name, int32 &Num)
FORCEINLINE FStructuredArchiveRecord EnterRecord (FArchiveFieldName Name)
FORCEINLINE FStructuredArchiveStream EnterStream (FArchiveFieldName Name)
template<typename T>
FORCEINLINE FStructuredArchiveRecord & operator<< (UE::StructuredArchive::Private::TNamedValue< T > Item)
FORCEINLINE TOptional< FStructuredArchiveSlot > TryEnterField (FArchiveFieldName Name, bool bEnterForSaving)
Public Member Functions inherited from UE::StructuredArchive::Private::FSlotBase
FORCEINLINE FSlotBase (EPrivateToken, FStructuredArchive &InStructuredArchive)
const FArchiveState & GetArchiveState () const
FArchive & GetUnderlyingArchive () const
Private Member Functions
FORCEINLINE FSlotBase (EPrivateToken, FStructuredArchive &InStructuredArchive)
Private Attributes
friend FStructuredArchive
friend FStructuredArchiveSlot
Additional Inherited Members
Protected Types inherited from UE::StructuredArchive::Private::FSlotBase
enum class EPrivateToken
Protected Attributes inherited from UE::StructuredArchive::Private::FSlotBase
FStructuredArchive & StructuredArchive
Detailed Description
Represents a record in the structured archive.
An object contains slots that are identified by FArchiveName, which may be compiled out with binary-only archives.
Definition at line 143 of file StructuredArchiveSlots.h.
Member Function Documentation
EnterArray()
FORCEINLINE FStructuredArchiveArray FStructuredArchiveRecord::EnterArray (FArchiveFieldName Name, int32 & Num)
Definition at line 426 of file StructuredArchiveSlots.h.
References FStructuredArchiveSlot::EnterArray(), EnterField(), FORCEINLINE, Name, and Num.
EnterField()
FORCEINLINE FStructuredArchiveSlot FStructuredArchiveRecord::EnterField (FArchiveFieldName Name)
Definition at line 416 of file StructuredArchiveSlots.h.
References FORCEINLINE, FStructuredArchiveSlot, Name, and UE::StructuredArchive::Private::FSlotBase::StructuredArchive.
Referenced by EnterArray(), EnterMap(), EnterRecord(), EnterStream(), and operator<<().
EnterMap()
FORCEINLINE FStructuredArchiveMap FStructuredArchiveRecord::EnterMap (FArchiveFieldName Name, int32 & Num)
Definition at line 436 of file StructuredArchiveSlots.h.
References EnterField(), FStructuredArchiveSlot::EnterMap(), FORCEINLINE, Name, and Num.
EnterRecord()
FORCEINLINE FStructuredArchiveRecord FStructuredArchiveRecord::EnterRecord (FArchiveFieldName Name)
Definition at line 421 of file StructuredArchiveSlots.h.
References EnterField(), FStructuredArchiveSlot::EnterRecord(), FORCEINLINE, and Name.
EnterStream()
FORCEINLINE FStructuredArchiveStream FStructuredArchiveRecord::EnterStream (FArchiveFieldName Name)
Definition at line 431 of file StructuredArchiveSlots.h.
References EnterField(), FStructuredArchiveSlot::EnterStream(), FORCEINLINE, and Name.
FSlotBase()
FORCEINLINE UE::StructuredArchive::Private::FSlotBase::FSlotBase (EPrivateToken , FStructuredArchive & InStructuredArchive) inline explicit private
Definition at line 83 of file StructuredArchiveSlotBase.h.
operator<<()
template<typename T> FORCEINLINE FStructuredArchiveRecord & FStructuredArchiveRecord::operator<< (UE::StructuredArchive::Private::TNamedValue< T > Item) inline
Definition at line 154 of file StructuredArchiveSlots.h.
References EnterField(), FORCEINLINE, and Item.
TryEnterField()
FORCEINLINE TOptional< FStructuredArchiveSlot > FStructuredArchiveRecord::TryEnterField (FArchiveFieldName Name, bool bEnterForSaving)
Definition at line 441 of file StructuredArchiveSlots.h.
References FORCEINLINE, FStructuredArchiveSlot, UE::StructuredArchive::Private::GetFormatterImpl(), InPlace, Name, UE::StructuredArchive::Private::FSlotBase::StructuredArchive, and TryEnterField().
Referenced by TryEnterField().
Field Documentation
FStructuredArchive
friend FStructuredArchiveRecord::FStructuredArchive private
Definition at line 161 of file StructuredArchiveSlots.h.
FStructuredArchiveSlot
friend FStructuredArchiveRecord::FStructuredArchiveSlot private
Definition at line 162 of file StructuredArchiveSlots.h.
Referenced by EnterField(), and TryEnterField().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/StructuredArchiveSlots.h