Unreal Engine 5.6 C++ API: Metasound::FInputNode Class Reference
Metasound::FInputNode Class Reference
FInputNode represents an input to a metasound graph.
#include "MetasoundInputNode.h"
Public Member Functions
METASOUNDFRONTEND_API FInputNode (FInputNodeConstructorParams &&InParams, const FName &InDataTypeName, EVertexAccessType InVertexAccess, FOperatorFactorySharedRef InFactory)
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
UE_DEPRECATED (5.6, "Use CreateNodeClassMetadata(...) instead") static METASOUNDFRONTEND_API FNodeClassMetadata GetNodeMetadata(const FVertexName &InVertexName
UE_DEPRECATED (5.6, "You can find the vertex name by inspecting the FVertexInterface.") METASOUNDFRONTEND_API const FVertexName &GetVertexName() const
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Static Public Member Functions
static METASOUNDFRONTEND_API FNodeClassMetadata CreateNodeClassMetadata (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccess)
static METASOUNDFRONTEND_API FText GetInputDescription ()
Data Fields
const FName & InDataTypeName
const FName EVertexAccessType InVertexAccess
Protected Member Functions
METASOUNDFRONTEND_API FInputNode (FOperatorFactorySharedRef InFactory, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Static Protected Member Functions
static METASOUNDFRONTEND_API FVertexInterface CreateDefaultVertexInterface (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccess, const FLiteral *InDefaultLiteral=nullptr)
Static Private Member Functions
static FVertexInterface CreateVertexInterface (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccess, const FLiteral &InLiteral)
static FName GetVariantName (EVertexAccessType InVertexAccess)
Private Attributes
FOperatorFactorySharedRef Factory
Static Private Attributes
static FLazyName ConstructorVariant
Detailed Description
FInputNode represents an input to a metasound graph.
Definition at line 315 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
FInputNode() [1/2]
METASOUNDFRONTEND_API Metasound::FInputNode::FInputNode (FOperatorFactorySharedRef InFactory, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata) explicit protected
References UE_API.
Referenced by FInputNode(), Metasound::TInputNode< DataType, VertexAccess >::TInputNode(), and Metasound::TInputNode< DataType, VertexAccess >::TInputNode().
FInputNode() [2/2]
METASOUNDFRONTEND_API Metasound::FInputNode::FInputNode (FInputNodeConstructorParams && InParams, const FName & InDataTypeName, EVertexAccessType InVertexAccess, FOperatorFactorySharedRef InFactory) explicit
References FInputNode(), InDataTypeName, InVertexAccess, and UE_API.
Member Function Documentation
CreateDefaultVertexInterface()
METASOUNDFRONTEND_API FVertexInterface Metasound::FInputNode::CreateDefaultVertexInterface (const FVertexName & InVertexName, const FName & InDataTypeName, EVertexAccessType InVertexAccess, const FLiteral * InDefaultLiteral = nullptr) static protected
References InDataTypeName, InVertexAccess, and UE_API.
CreateNodeClassMetadata()
METASOUNDFRONTEND_API FNodeClassMetadata Metasound::FInputNode::CreateNodeClassMetadata (const FVertexName & InVertexName, const FName & InDataTypeName, EVertexAccessType InVertexAccess) static
References CreateNodeClassMetadata(), InDataTypeName, InVertexAccess, and UE_API.
Referenced by CreateNodeClassMetadata(), Metasound::TInputNode< DataType, VertexAccess >::CreateNodeClassMetadata(), and Metasound::TInputNode< DataType, VertexAccess >::UE_DEPRECATED().
CreateVertexInterface()
FVertexInterface Metasound::FInputNode::CreateVertexInterface (const FVertexName & InVertexName, const FName & InDataTypeName, EVertexAccessType InVertexAccess, const FLiteral & InLiteral) static private
References InDataTypeName, and InVertexAccess.
GetDefaultOperatorFactory()
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > Metasound::FInputNode::GetDefaultOperatorFactory () const override virtual
Return a reference to the default operator factory.
Implements Metasound::INode.
References GetDefaultOperatorFactory(), ThreadSafe, and UE_API.
Referenced by GetDefaultOperatorFactory().
GetInputDescription()
METASOUNDFRONTEND_API FText Metasound::FInputNode::GetInputDescription () static
References UE_API.
GetVariantName()
FName Metasound::FInputNode::GetVariantName (EVertexAccessType InVertexAccess) static private
References InVertexAccess.
UE_DEPRECATED() [1/2]
Metasound::FInputNode::UE_DEPRECATED (5. 6, "Use CreateNodeClassMetadata(...) instead") const &
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
Metasound::FInputNode::UE_DEPRECATED (5. 6, "You can find the vertex name by inspecting the FVertexInterface.") const &
References UE_API, and UE_DEPRECATED().
Field Documentation
ConstructorVariant
FLazyName Metasound::FInputNode::ConstructorVariant static private
Definition at line 317 of file MetasoundInputNode.h.
Factory
FOperatorFactorySharedRef Metasound::FInputNode::Factory private
Definition at line 347 of file MetasoundInputNode.h.
InDataTypeName
const FName& Metasound::FInputNode::InDataTypeName
Definition at line 333 of file MetasoundInputNode.h.
Referenced by FInputNode(), CreateDefaultVertexInterface(), CreateNodeClassMetadata(), and CreateVertexInterface().
InVertexAccess
const FName EVertexAccessType Metasound::FInputNode::InVertexAccess
Definition at line 333 of file MetasoundInputNode.h.
Referenced by FInputNode(), CreateDefaultVertexInterface(), CreateNodeClassMetadata(), CreateVertexInterface(), and GetVariantName().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundInputNode.h