Unreal Engine 5.6 C++ API: SDataflowConstructionViewportSelectionToolBar Class Reference
SDataflowConstructionViewportSelectionToolBar Class Reference
Base toolbar for the dataflow.
#include "DataflowConstructionViewportToolbar.h"
Public Member Functions
SLATE_ARGUMENT (TSharedPtr< class FUICommandList >, CommandList) SLATE_ARGUMENT(TSharedPtr< class FExtender >
SLATE_BEGIN_ARGS (SDataflowConstructionViewportSelectionToolBar)
Extenders SLATE_END_ARGS () void Construct(const FArguments &InArgs
Constructs this widget with the given parameters.
Data Fields
Extenders TSharedPtr< SDataflowConstructionViewport > InDataflowViewport
Private Member Functions
virtual TSharedRef< SWidget > GenerateShowMenu () const override
TSharedRef< SWidget > GenerateViewModeMenuContent () const
FText GetViewModeMenuLabel () const
const FSlateBrush * GetViewModeMenuLabelIcon () const
TSharedRef< SWidget > MakeDisplayToolBar (const TSharedPtr< FExtender > InExtenders)
TSharedRef< SWidget > MakeToolBar (const TSharedPtr< FExtender > InExtenders)
Private Attributes
TSharedPtr< FUICommandList > CommandList
TWeakPtr< SDataflowConstructionViewport > EditorViewport
Reference to the parent viewport.
TSharedPtr< SEditorViewportToolbarMenu > ViewModeDropDown
Detailed Description
Base toolbar for the dataflow.
Should be extended to add more features
Definition at line 12 of file DataflowConstructionViewportToolbar.h.
Member Function Documentation
GenerateShowMenu()
virtual TSharedRef< SWidget > SDataflowConstructionViewportSelectionToolBar::GenerateShowMenu () const override private virtual
References GenerateShowMenu().
Referenced by GenerateShowMenu().
GenerateViewModeMenuContent()
TSharedRef< SWidget > SDataflowConstructionViewportSelectionToolBar::GenerateViewModeMenuContent () const private
References GenerateViewModeMenuContent().
Referenced by GenerateViewModeMenuContent().
GetViewModeMenuLabel()
FText SDataflowConstructionViewportSelectionToolBar::GetViewModeMenuLabel () const private
References GetViewModeMenuLabel().
Referenced by GetViewModeMenuLabel().
GetViewModeMenuLabelIcon()
const FSlateBrush * SDataflowConstructionViewportSelectionToolBar::GetViewModeMenuLabelIcon () const private
References GetViewModeMenuLabelIcon().
Referenced by GetViewModeMenuLabelIcon().
MakeDisplayToolBar()
TSharedRef< SWidget > SDataflowConstructionViewportSelectionToolBar::MakeDisplayToolBar (const TSharedPtr< FExtender > InExtenders) private
References MakeDisplayToolBar().
Referenced by MakeDisplayToolBar().
MakeToolBar()
TSharedRef< SWidget > SDataflowConstructionViewportSelectionToolBar::MakeToolBar (const TSharedPtr< FExtender > InExtenders) private
References MakeToolBar().
Referenced by MakeToolBar().
SLATE_ARGUMENT()
SDataflowConstructionViewportSelectionToolBar::SLATE_ARGUMENT (TSharedPtr< class FUICommandList > , CommandList)
References CommandList.
SLATE_BEGIN_ARGS()
SDataflowConstructionViewportSelectionToolBar::SLATE_BEGIN_ARGS (SDataflowConstructionViewportSelectionToolBar) inline
Definition at line 15 of file DataflowConstructionViewportToolbar.h.
SLATE_END_ARGS()
Extenders SDataflowConstructionViewportSelectionToolBar::SLATE_END_ARGS () const &
Constructs this widget with the given parameters.
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Field Documentation
CommandList
TSharedPtr<FUICommandList> SDataflowConstructionViewportSelectionToolBar::CommandList private
Definition at line 44 of file DataflowConstructionViewportToolbar.h.
Referenced by SLATE_ARGUMENT().
EditorViewport
TWeakPtr<SDataflowConstructionViewport> SDataflowConstructionViewportSelectionToolBar::EditorViewport private
Reference to the parent viewport.
Definition at line 42 of file DataflowConstructionViewportToolbar.h.
InDataflowViewport
Extenders TSharedPtr<SDataflowConstructionViewport> SDataflowConstructionViewportSelectionToolBar::InDataflowViewport
Definition at line 21 of file DataflowConstructionViewportToolbar.h.
ViewModeDropDown
TSharedPtr<SEditorViewportToolbarMenu> SDataflowConstructionViewportSelectionToolBar::ViewModeDropDown private
Definition at line 39 of file DataflowConstructionViewportToolbar.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Dataflow/Source/DataflowEditor/Public/Dataflow/DataflowConstructionViewportToolbar.h