Unreal Engine 5.6 C++ API: TShaderRefBase< ShaderType, PointerTableType > Class Template Reference
TShaderRefBase< ShaderType, PointerTableType > Class Template Reference
#include "Shader.h"
Public Member Functions
TShaderRefBase ()
TShaderRefBase (const TShaderRefBase &)=default
template<typename OtherShaderType, typename OtherPointerTableType>
TShaderRefBase (const TShaderRefBase< OtherShaderType, OtherPointerTableType > &Rhs)
TShaderRefBase (ShaderType *InShader, const FShaderMapBase &InShaderMap)
FRHIAmplificationShader * GetAmplificationShader () const
FRHIComputeShader * GetComputeShader () const
FRHIGeometryShader * GetGeometryShader () const
FRHIGraphicsShader * GetGraphicsShader (bool bRequired=true) const
FRHIMeshShader * GetMeshShader () const
FRHIPixelShader * GetPixelShader (bool bRequired=true) const
const PointerTableType & GetPointerTable () const
FShaderMapResource * GetResource () const
FShaderMapResource & GetResourceChecked () const
FRHIShader * GetRHIShaderBase (EShaderFrequency Frequency, bool bRequired=true) const
ShaderType * GetShader () const
const FShaderMapBase * GetShaderMap () const
const FShaderMapBase & GetShaderMapChecked () const
FShaderType * GetType () const
FVertexFactoryType * GetVertexFactoryType () const
FRHIVertexShader * GetVertexShader (bool bRequired=true) const
FRHIWorkGraphShader * GetWorkGraphShader () const
bool IsNull () const
bool IsValid () const
ShaderType * operator-> () const
TShaderRefBase & operator= (const TShaderRefBase &)=default
template<typename OtherShaderType, typename OtherPointerTableType>
TShaderRefBase & operator= (const TShaderRefBase< OtherShaderType, OtherPointerTableType > &Rhs)
void Reset ()
Static Public Member Functions
template<typename OtherShaderType, typename OtherPointerTableType>
static TShaderRefBase< ShaderType, PointerTableType > Cast (const TShaderRefBase< OtherShaderType, OtherPointerTableType > &Rhs)
template<typename OtherShaderType, typename OtherPointerTableType>
static TShaderRefBase< ShaderType, PointerTableType > ReinterpretCast (const TShaderRefBase< OtherShaderType, OtherPointerTableType > &Rhs)
Private Member Functions
TShaderRefBase (ShaderType *InShader, const FShaderMapBase *InShaderMap)
Private Attributes
ShaderType * ShaderContent
const FShaderMapBase * ShaderMap
Friends
template<typename ShaderType1>
bool operator!= (const TShaderRefBase &Lhs, const TShaderRefBase< ShaderType1, PointerTableType > &Rhs)
template<typename ShaderType1>
bool operator== (const TShaderRefBase &Lhs, const TShaderRefBase< ShaderType1, PointerTableType > &Rhs)
Detailed Description
template<typename ShaderType, typename PointerTableType>
class TShaderRefBase< ShaderType, PointerTableType >
Definition at line 1043 of file Shader.h.
Constructor & Destructor Documentation
TShaderRefBase() [1/5]
template<typename ShaderType, typename PointerTableType> TShaderRefBase< ShaderType, PointerTableType >::TShaderRefBase () inline
Definition at line 1046 of file Shader.h.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), and TShaderRefBase< ShaderType, FShaderMapPointerTable >::ReinterpretCast().
TShaderRefBase() [2/5]
template<typename ShaderType, typename PointerTableType> TShaderRefBase< ShaderType, PointerTableType >::TShaderRefBase (ShaderType * InShader, const FShaderMapBase & InShaderMap) inline
Definition at line 1047 of file Shader.h.
TShaderRefBase() [3/5]
template<typename ShaderType, typename PointerTableType> TShaderRefBase< ShaderType, PointerTableType >::TShaderRefBase (const TShaderRefBase< ShaderType, PointerTableType > &) default
TShaderRefBase() [4/5]
template<typename ShaderType, typename PointerTableType> template<typename OtherShaderType, typename OtherPointerTableType> TShaderRefBase< ShaderType, PointerTableType >::TShaderRefBase (const TShaderRefBase< OtherShaderType, OtherPointerTableType > & Rhs) inline
Definition at line 1051 of file Shader.h.
TShaderRefBase() [5/5]
template<typename ShaderType, typename PointerTableType> TShaderRefBase< ShaderType, PointerTableType >::TShaderRefBase (ShaderType * InShader, const FShaderMapBase * InShaderMap) inline private
Definition at line 1214 of file Shader.h.
Member Function Documentation
Cast()
template<typename ShaderType, typename PointerTableType> template<typename OtherShaderType, typename OtherPointerTableType> TShaderRefBase< ShaderType, PointerTableType > TShaderRefBase< ShaderType, PointerTableType >::Cast (const TShaderRefBase< OtherShaderType, OtherPointerTableType > & Rhs) inline static
Definition at line 1064 of file Shader.h.
GetAmplificationShader()
template<typename ShaderType, typename PointerTableType> FRHIAmplificationShader * TShaderRefBase< ShaderType, PointerTableType >::GetAmplificationShader () const inline
Returns
the shader's aplification shader
Definition at line 1136 of file Shader.h.
Referenced by SetShaderParametersLegacyAS(), and SetShaderParametersMixedAS().
GetComputeShader()
template<typename ShaderType, typename PointerTableType> FRHIComputeShader * TShaderRefBase< ShaderType, PointerTableType >::GetComputeShader () const inline
Returns
the shader's compute shader
Definition at line 1151 of file Shader.h.
Referenced by FComputeShaderUtils::Private::AfterDispatch(), ClearUAVShader_T(), ClearUAVShader_T(), FComputeShaderUtils::Private::PrepareDispatch(), FPSOPrecacheData::SetComputeShader(), SetShaderParametersLegacyCS(), SetShaderParametersMixedCS(), and UnsetShaderParametersLegacyCS().
GetGeometryShader()
template<typename ShaderType, typename PointerTableType> FRHIGeometryShader * TShaderRefBase< ShaderType, PointerTableType >::GetGeometryShader () const inline
Returns
the shader's geometry shader
Definition at line 1146 of file Shader.h.
Referenced by SetShaderParametersLegacyGS(), and SetShaderParametersMixedGS().
GetGraphicsShader()
template<typename ShaderType, typename PointerTableType> FRHIGraphicsShader * TShaderRefBase< ShaderType, PointerTableType >::GetGraphicsShader (bool bRequired = true) const inline
Definition at line 1108 of file Shader.h.
GetMeshShader()
template<typename ShaderType, typename PointerTableType> FRHIMeshShader * TShaderRefBase< ShaderType, PointerTableType >::GetMeshShader () const inline
Returns
the shader's mesh shader
Definition at line 1131 of file Shader.h.
Referenced by SetShaderParametersLegacyMS(), and SetShaderParametersMixedMS().
GetPixelShader()
template<typename ShaderType, typename PointerTableType> FRHIPixelShader * TShaderRefBase< ShaderType, PointerTableType >::GetPixelShader (bool bRequired = true) const inline
Returns
the shader's pixel shader
Definition at line 1141 of file Shader.h.
Referenced by FPixelShaderUtils::AddRasterizeToRectsPass(), FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader(), SetShaderParametersLegacyPS(), SetShaderParametersMixedPS(), and UnsetShaderParametersLegacyPS().
GetPointerTable()
template<typename ShaderType, typename PointerTableType> const PointerTableType & TShaderRefBase< ShaderType, PointerTableType >::GetPointerTable () const inline
Definition at line 2641 of file Shader.h.
References checkSlow, and ShaderMap.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetType(), and TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetVertexFactoryType().
GetResource()
template<typename ShaderType, typename PointerTableType> FShaderMapResource * TShaderRefBase< ShaderType, PointerTableType >::GetResource () const inline
Definition at line 2648 of file Shader.h.
References checkSlow, and ShaderMap.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetResourceChecked().
GetResourceChecked()
template<typename ShaderType, typename PointerTableType> FShaderMapResource & TShaderRefBase< ShaderType, PointerTableType >::GetResourceChecked () const inline
Definition at line 1085 of file Shader.h.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetGraphicsShader(), and TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetRHIShaderBase().
GetRHIShaderBase()
template<typename ShaderType, typename PointerTableType> FRHIShader * TShaderRefBase< ShaderType, PointerTableType >::GetRHIShaderBase (EShaderFrequency Frequency, bool bRequired = true) const inline
Definition at line 1091 of file Shader.h.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetAmplificationShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetComputeShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetGeometryShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetMeshShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetPixelShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetVertexShader(), and TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetWorkGraphShader().
GetShader()
template<typename ShaderType, typename PointerTableType> ShaderType * TShaderRefBase< ShaderType, PointerTableType >::GetShader () const inline
Definition at line 1080 of file Shader.h.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), DispatchComputeShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::operator=(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::operator==, and TShaderRefBase< ShaderType, FShaderMapPointerTable >::ReinterpretCast().
GetShaderMap()
template<typename ShaderType, typename PointerTableType> const FShaderMapBase * TShaderRefBase< ShaderType, PointerTableType >::GetShaderMap () const inline
Definition at line 1081 of file Shader.h.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::Cast(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::operator=(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::operator==, and TShaderRefBase< ShaderType, FShaderMapPointerTable >::ReinterpretCast().
GetShaderMapChecked()
template<typename ShaderType, typename PointerTableType> const FShaderMapBase & TShaderRefBase< ShaderType, PointerTableType >::GetShaderMapChecked () const inline
Definition at line 1082 of file Shader.h.
GetType()
template<typename ShaderType, typename PointerTableType> FShaderType * TShaderRefBase< ShaderType, PointerTableType >::GetType () const inline
Definition at line 1083 of file Shader.h.
Referenced by TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetGraphicsShader(), and TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetRHIShaderBase().
GetVertexFactoryType()
template<typename ShaderType, typename PointerTableType> FVertexFactoryType * TShaderRefBase< ShaderType, PointerTableType >::GetVertexFactoryType () const inline
Definition at line 1084 of file Shader.h.
GetVertexShader()
template<typename ShaderType, typename PointerTableType> FRHIVertexShader * TShaderRefBase< ShaderType, PointerTableType >::GetVertexShader (bool bRequired = true) const inline
Returns
the shader's vertex shader
Definition at line 1126 of file Shader.h.
Referenced by SetShaderParametersLegacyVS(), and SetShaderParametersMixedVS().
GetWorkGraphShader()
template<typename ShaderType, typename PointerTableType> FRHIWorkGraphShader * TShaderRefBase< ShaderType, PointerTableType >::GetWorkGraphShader () const inline
Returns
the shader's work graph shader
Definition at line 1156 of file Shader.h.
IsNull()
template<typename ShaderType, typename PointerTableType> bool TShaderRefBase< ShaderType, PointerTableType >::IsNull () const inline
Definition at line 1076 of file Shader.h.
IsValid()
template<typename ShaderType, typename PointerTableType> bool TShaderRefBase< ShaderType, PointerTableType >::IsValid () const inline
Definition at line 1075 of file Shader.h.
Referenced by FPixelShaderUtils::AddFullscreenInstancedMultiViewportPass(), FPixelShaderUtils::AddFullscreenPass(), FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader(), and FGlobalShaderMap::GetShader().
operator->()
template<typename ShaderType, typename PointerTableType> ShaderType * TShaderRefBase< ShaderType, PointerTableType >::operator-> () const inline
Definition at line 1089 of file Shader.h.
operator=() [1/2]
template<typename ShaderType, typename PointerTableType> TShaderRefBase & TShaderRefBase< ShaderType, PointerTableType >::operator= (const TShaderRefBase< ShaderType, PointerTableType > &) default
operator=() [2/2]
template<typename ShaderType, typename PointerTableType> template<typename OtherShaderType, typename OtherPointerTableType> TShaderRefBase & TShaderRefBase< ShaderType, PointerTableType >::operator= (const TShaderRefBase< OtherShaderType, OtherPointerTableType > & Rhs) inline
Definition at line 1056 of file Shader.h.
ReinterpretCast()
template<typename ShaderType, typename PointerTableType> template<typename OtherShaderType, typename OtherPointerTableType> TShaderRefBase< ShaderType, PointerTableType > TShaderRefBase< ShaderType, PointerTableType >::ReinterpretCast (const TShaderRefBase< OtherShaderType, OtherPointerTableType > & Rhs) inline static
Definition at line 1070 of file Shader.h.
Reset()
template<typename ShaderType, typename PointerTableType> void TShaderRefBase< ShaderType, PointerTableType >::Reset () inline
Definition at line 1078 of file Shader.h.
Friends And Related Symbol Documentation
operator!=
template<typename ShaderType, typename PointerTableType> template<typename ShaderType1> bool operator!= (const TShaderRefBase< ShaderType, PointerTableType > & Lhs, const TShaderRefBase< ShaderType1, PointerTableType > & Rhs) friend
Definition at line 1235 of file Shader.h.
operator==
template<typename ShaderType, typename PointerTableType> template<typename ShaderType1> bool operator== (const TShaderRefBase< ShaderType, PointerTableType > & Lhs, const TShaderRefBase< ShaderType1, PointerTableType > & Rhs) friend
Definition at line 1224 of file Shader.h.
Field Documentation
ShaderContent
template<typename ShaderType, typename PointerTableType> ShaderType* TShaderRefBase< ShaderType, PointerTableType >::ShaderContent private
Definition at line 1220 of file Shader.h.
ShaderMap
template<typename ShaderType, typename PointerTableType> const FShaderMapBase* TShaderRefBase< ShaderType, PointerTableType >::ShaderMap private
Definition at line 1221 of file Shader.h.
Referenced by GetPointerTable(), and GetResource().
The documentation for this class was generated from the following files:
Runtime/RenderCore/Public/RendererInterface.h
Runtime/RenderCore/Public/Shader.h