Unreal Engine 5.6 C++ API: FODSCManager Class Reference
FODSCManager Class Reference
Responsible for processing shader compile responses from the ODSC Thread.
#include "ODSCManager.h"
Public Member Functions
FODSCManager ()
Constructor.
virtual ~FODSCManager ()
Destructor.
void AddThreadedRequest (const TArray< FString > &MaterialsToCompile, const FString &ShaderTypesToLoad, EShaderPlatform ShaderPlatform, ERHIFeatureLevel::Type FeatureLevel, EMaterialQualityLevel::Type QualityLevel, ODSCRecompileCommand RecompileCommandType, const FString &RequestedMaterialName=FString(), const FShaderCompilerFlags &ExtraCompilerFlags=FShaderCompilerFlags())
Add a request to compile a shader.
void AddThreadedShaderPipelineRequest (EShaderPlatform ShaderPlatform, ERHIFeatureLevel::Type FeatureLevel, EMaterialQualityLevel::Type QualityLevel, const FMaterial *Material, const FString &VertexFactoryName, const FString &PipelineName, const TArray< FString > &ShaderTypeNames, int32 PermutationId, const TArray< FShaderId > &RequestShaderIds)
Add a request to compile a pipeline of shaders.
bool CheckIfRequestAlreadySent (const TArray< FShaderId > &RequestShaderIds, const FMaterial *Material) const
bool Tick (float DeltaSeconds) override
FTSTicker callback.
void TryLoadGlobalShaders (EShaderPlatform ShaderPlatform)
UE_DEPRECATED (5.5, "RequestShaderIds is needed for AddThreadedShaderPipelineRequest and need to match the ones from FMaterialShaderMap::GetShaderList") void AddThreadedShaderPipelineRequest(EShaderPlatform ShaderPlatform
Public Member Functions inherited from FTSTickerObjectBase
FTSTickerObjectBase (float InDelay=0.0f, FTSTicker &Ticker=FTSTicker::GetCoreTicker())
Constructor.
virtual ~FTSTickerObjectBase ()
Virtual destructor.
UE_NONCOPYABLE (FTSTickerObjectBase)
Static Public Member Functions
static FMaterialShaderMap * FindMaterialShaderMap (const FString &MaterialName, const FMaterialShaderMapId &ShaderMapId)
static bool IsODSCActive ()
static void RegisterMaterialShaderMaps (const FString &MaterialName, const TArray< TRefCountPtr< FMaterialShaderMap > > &LoadedShaderMaps)
static void ReportODSCError (const FString &InErrorMessage)
static void ResetCurrentPrimitiveSceneInfo ()
static void ResumeODSCForceRecompile ()
static void SetCurrentPrimitiveSceneInfo (FPrimitiveSceneInfo *PrimitiveSceneInfo)
static bool ShouldForceRecompile (const FMaterialShaderMap *MaterialShaderMap, const FMaterial *Material)
static void SuspendODSCForceRecompile ()
static void UnregisterMaterialInstance (const UMaterialInstance *MI)
static void UnregisterMaterialName (const FMaterial *Material)
static bool UseDefaultMaterialOnRecompile ()
Data Fields
ERHIFeatureLevel::Type FeatureLevel
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString & MaterialName
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString const FString const TArray< FString > int32 PermutationId
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString const FString & PipelineName
ERHIFeatureLevel::Type EMaterialQualityLevel::Type QualityLevel
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString const FString const TArray< FString > & ShaderTypeNames
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString & VertexFactoryName
Private Member Functions
void ClearErrorMessage ()
bool HasAsyncLoadingInstances ()
void OnEnginePreExit ()
void RetrieveErrorMessage (FString &OutErrorMessage)
bool ShouldForceRecompileInternal (const FMaterialShaderMap *MaterialShaderMap, const FMaterial *Material)
void StopThread ()
Private Attributes
FString ErrorMessage
FCriticalSection ErrorMessageCS
TMap< const void *, TWeakObjectPtr< const UMaterialInstance > > MaterialInstancesCachedUniformExpressions
FCriticalSection MaterialInstancesCachedUniformExpressionsCS
FName MaterialNameToRecompile
FDelegateHandle OnScreenMessagesHandle
FODSCThread * Thread = nullptr
Handles communicating directly with the cook on the fly server.
Friends
class FODSCManagerAccess
Detailed Description
Responsible for processing shader compile responses from the ODSC Thread.
Interface for submitting shader compile requests to the ODSC Thread.
Definition at line 21 of file ODSCManager.h.
Constructor & Destructor Documentation
FODSCManager()
FODSCManager::FODSCManager ()
Constructor.
~FODSCManager()
virtual FODSCManager::~FODSCManager () virtual
Destructor.
Member Function Documentation
AddThreadedRequest()
void FODSCManager::AddThreadedRequest (const TArray< FString > & MaterialsToCompile, const FString & ShaderTypesToLoad, EShaderPlatform ShaderPlatform, ERHIFeatureLevel::Type FeatureLevel, EMaterialQualityLevel::Type QualityLevel, ODSCRecompileCommand RecompileCommandType, const FString & RequestedMaterialName = FString(), const FShaderCompilerFlags & ExtraCompilerFlags = FShaderCompilerFlags())
Add a request to compile a shader.
The results are submitted and processed in an async manner.
Parameters
MaterialsToCompile - List of material names to submit compiles for.
ShaderPlatform - Which shader platform to compile for.
RecompileCommandType - Whether we should recompile changed or global shaders.
Returns
false if no longer needs ticking
References FeatureLevel, QualityLevel, and ShaderPlatform.
AddThreadedShaderPipelineRequest()
void FODSCManager::AddThreadedShaderPipelineRequest (EShaderPlatform ShaderPlatform, ERHIFeatureLevel::Type FeatureLevel, EMaterialQualityLevel::Type QualityLevel, const FMaterial * Material, const FString & VertexFactoryName, const FString & PipelineName, const TArray< FString > & ShaderTypeNames, int32 PermutationId, const TArray< FShaderId > & RequestShaderIds)
Add a request to compile a pipeline of shaders.
The results are submitted and processed in an async manner.
Parameters
ShaderPlatform - Which shader platform to compile for.
FeatureLevel - Which feature level to compile for.
QualityLevel - Which material quality level to compile for.
MaterialName - The name of the material to compile.
VertexFactoryName - The name of the vertex factory type we should compile.
PipelineName - The name of the shader pipeline we should compile.
ShaderTypeNames - The shader type names of all the shader stages in the pipeline.
PermutationId - The permutation ID of the shader we should compile.
Returns
false if no longer needs ticking
References FeatureLevel, Material, PermutationId, PipelineName, QualityLevel, ShaderPlatform, ShaderTypeNames, and VertexFactoryName.
Referenced by UE_DEPRECATED().
CheckIfRequestAlreadySent()
bool FODSCManager::CheckIfRequestAlreadySent (const TArray< FShaderId > & RequestShaderIds, const FMaterial * Material) const
References Material.
ClearErrorMessage()
void FODSCManager::ClearErrorMessage () private
FindMaterialShaderMap()
FMaterialShaderMap * FODSCManager::FindMaterialShaderMap (const FString & MaterialName, const FMaterialShaderMapId & ShaderMapId) static
References MaterialName.
HasAsyncLoadingInstances()
bool FODSCManager::HasAsyncLoadingInstances () private
IsODSCActive()
bool FODSCManager::IsODSCActive () inline static
Definition at line 185 of file ODSCManager.h.
References GODSCManager.
Referenced by ShouldForceRecompile().
OnEnginePreExit()
void FODSCManager::OnEnginePreExit () private
RegisterMaterialShaderMaps()
void FODSCManager::RegisterMaterialShaderMaps (const FString & MaterialName, const TArray< TRefCountPtr< FMaterialShaderMap > > & LoadedShaderMaps) static
References MaterialName.
ReportODSCError()
void FODSCManager::ReportODSCError (const FString & InErrorMessage) static
ResetCurrentPrimitiveSceneInfo()
void FODSCManager::ResetCurrentPrimitiveSceneInfo () static
Referenced by FODSCPrimitiveSceneInfoScope::~FODSCPrimitiveSceneInfoScope().
ResumeODSCForceRecompile()
void FODSCManager::ResumeODSCForceRecompile () static
Referenced by FODSCSuspendForceRecompileScope::~FODSCSuspendForceRecompileScope().
RetrieveErrorMessage()
void FODSCManager::RetrieveErrorMessage (FString & OutErrorMessage) private
SetCurrentPrimitiveSceneInfo()
void FODSCManager::SetCurrentPrimitiveSceneInfo (FPrimitiveSceneInfo * PrimitiveSceneInfo) static
Referenced by FODSCPrimitiveSceneInfoScope::FODSCPrimitiveSceneInfoScope().
ShouldForceRecompile()
bool FODSCManager::ShouldForceRecompile (const FMaterialShaderMap * MaterialShaderMap, const FMaterial * Material) inline static
Definition at line 190 of file ODSCManager.h.
References GODSCManager, IsODSCActive(), and Material.
ShouldForceRecompileInternal()
bool FODSCManager::ShouldForceRecompileInternal (const FMaterialShaderMap * MaterialShaderMap, const FMaterial * Material) private
References Material.
StopThread()
void FODSCManager::StopThread () private
SuspendODSCForceRecompile()
void FODSCManager::SuspendODSCForceRecompile () static
Referenced by FODSCSuspendForceRecompileScope::FODSCSuspendForceRecompileScope().
Tick()
bool FODSCManager::Tick (float DeltaSeconds) override virtual
FTSTicker callback.
Parameters
DeltaSeconds - time in seconds since the last tick
Returns
false if no longer needs ticking
Implements FTSTickerObjectBase.
TryLoadGlobalShaders()
void FODSCManager::TryLoadGlobalShaders (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
UE_DEPRECATED()
FODSCManager::UE_DEPRECATED (5. 5, "RequestShaderIds is needed for AddThreadedShaderPipelineRequest and need to match the ones from FMaterialShaderMap::GetShaderList")
References AddThreadedShaderPipelineRequest(), and ShaderPlatform.
UnregisterMaterialInstance()
void FODSCManager::UnregisterMaterialInstance (const UMaterialInstance * MI) static
References Material.
UnregisterMaterialName()
void FODSCManager::UnregisterMaterialName (const FMaterial * Material) static
References Material.
UseDefaultMaterialOnRecompile()
bool FODSCManager::UseDefaultMaterialOnRecompile () static
Friends And Related Symbol Documentation
FODSCManagerAccess
friend class FODSCManagerAccess friend
Definition at line 132 of file ODSCManager.h.
References FODSCManagerAccess.
Referenced by FODSCManagerAccess.
Field Documentation
ErrorMessage
FString FODSCManager::ErrorMessage private
Definition at line 151 of file ODSCManager.h.
ErrorMessageCS
FCriticalSection FODSCManager::ErrorMessageCS private
Definition at line 150 of file ODSCManager.h.
FeatureLevel
ERHIFeatureLevel::Type FODSCManager::FeatureLevel
Definition at line 98 of file ODSCManager.h.
Referenced by AddThreadedRequest(), and AddThreadedShaderPipelineRequest().
MaterialInstancesCachedUniformExpressions
TMap<const void*, TWeakObjectPtr<const UMaterialInstance> > FODSCManager::MaterialInstancesCachedUniformExpressions private
Definition at line 148 of file ODSCManager.h.
MaterialInstancesCachedUniformExpressionsCS
FCriticalSection FODSCManager::MaterialInstancesCachedUniformExpressionsCS private
Definition at line 147 of file ODSCManager.h.
MaterialName
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString& FODSCManager::MaterialName
Definition at line 100 of file ODSCManager.h.
Referenced by FindMaterialShaderMap(), and RegisterMaterialShaderMaps().
MaterialNameToRecompile
FName FODSCManager::MaterialNameToRecompile private
Definition at line 153 of file ODSCManager.h.
OnScreenMessagesHandle
FDelegateHandle FODSCManager::OnScreenMessagesHandle private
Definition at line 146 of file ODSCManager.h.
PermutationId
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString const FString const TArray<FString> int32 FODSCManager::PermutationId
Initial value:
{}
    inline bool IsHandlingRequests() const { return Thread != nullptr; }
    static void RegisterMaterialInstance(const UMaterialInstance* MI)
Definition at line 104 of file ODSCManager.h.
Referenced by AddThreadedShaderPipelineRequest().
PipelineName
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString const FString& FODSCManager::PipelineName
Definition at line 102 of file ODSCManager.h.
Referenced by AddThreadedShaderPipelineRequest().
QualityLevel
ERHIFeatureLevel::Type EMaterialQualityLevel::Type FODSCManager::QualityLevel
Definition at line 99 of file ODSCManager.h.
Referenced by AddThreadedRequest(), and AddThreadedShaderPipelineRequest().
ShaderTypeNames
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString const FString const TArray<FString>& FODSCManager::ShaderTypeNames
Definition at line 103 of file ODSCManager.h.
Referenced by AddThreadedShaderPipelineRequest().
Thread
FODSCThread* FODSCManager::Thread = nullptr private
Handles communicating directly with the cook on the fly server.
Definition at line 144 of file ODSCManager.h.
VertexFactoryName
ERHIFeatureLevel::Type EMaterialQualityLevel::Type const FString const FString& FODSCManager::VertexFactoryName
Definition at line 101 of file ODSCManager.h.
Referenced by AddThreadedShaderPipelineRequest().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ODSC/ODSCManager.h