Unreal Engine 5.6 C++ API: FDisplayClusterSceneComponentRef Class Reference
FDisplayClusterSceneComponentRef Class Reference
#include "DisplayClusterObjectRef.h"
Public Member Functions
FDisplayClusterSceneComponentRef ()
FDisplayClusterSceneComponentRef (const FDisplayClusterSceneComponentRef &InComponentRef)
FDisplayClusterSceneComponentRef (USceneComponent *InComponent)
USceneComponent * GetOrFindSceneComponent () const
bool IsDefinedSceneComponent () const
bool IsEqualsComponentName (const FName &InComponentName) const
bool IsSceneComponentValid () const
void ResetSceneComponent ()
bool SetSceneComponent (USceneComponent *const InComponent)
Public Member Functions inherited from FDisplayClusterActorRef
FDisplayClusterActorRef ()
FDisplayClusterActorRef (const FDisplayClusterActorRef &InActorRef)
virtual ~FDisplayClusterActorRef ()
AActor * GetOrFindSceneActor () const
const TWeakObjectPtr< AActor > GetSceneActorWeakPtr () const
Returns the current weak ptr of the scene actor object.
bool IsDefinedSceneActor () const
void ResetSceneActor ()
bool SetSceneActor (const AActor *InActor)
Private Attributes
FName ComponentName
TWeakObjectPtr< USceneComponent > ComponentPtr
Additional Inherited Members
Protected Attributes inherited from FDisplayClusterActorRef
FCriticalSection DataGuard
Detailed Description
Definition at line 199 of file DisplayClusterObjectRef.h.
Constructor & Destructor Documentation
FDisplayClusterSceneComponentRef() [1/3]
FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef () inline
Definition at line 203 of file DisplayClusterObjectRef.h.
References FDisplayClusterActorRef::FDisplayClusterActorRef().
Referenced by FDisplayClusterRender_ProceduralMeshComponentRef::FDisplayClusterRender_ProceduralMeshComponentRef(), FDisplayClusterRender_ProceduralMeshComponentRef::FDisplayClusterRender_ProceduralMeshComponentRef(), FDisplayClusterRender_StaticMeshComponentRef::FDisplayClusterRender_StaticMeshComponentRef(), FDisplayClusterRender_StaticMeshComponentRef::FDisplayClusterRender_StaticMeshComponentRef(), and FDisplayClusterSceneComponentRef().
FDisplayClusterSceneComponentRef() [2/3]
FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef (const FDisplayClusterSceneComponentRef & InComponentRef) inline
Definition at line 207 of file DisplayClusterObjectRef.h.
References FDisplayClusterActorRef::FDisplayClusterActorRef(), FDisplayClusterSceneComponentRef(), ComponentName, and ComponentPtr.
FDisplayClusterSceneComponentRef() [3/3]
FDisplayClusterSceneComponentRef::FDisplayClusterSceneComponentRef (USceneComponent * InComponent) inline
Definition at line 213 of file DisplayClusterObjectRef.h.
References SetSceneComponent().
Member Function Documentation
GetOrFindSceneComponent()
USceneComponent * FDisplayClusterSceneComponentRef::GetOrFindSceneComponent () const
IsDefinedSceneComponent()
bool FDisplayClusterSceneComponentRef::IsDefinedSceneComponent () const inline
Definition at line 219 of file DisplayClusterObjectRef.h.
References ComponentName, and FDisplayClusterActorRef::IsDefinedSceneActor().
IsEqualsComponentName()
bool FDisplayClusterSceneComponentRef::IsEqualsComponentName (const FName & InComponentName) const inline
Definition at line 259 of file DisplayClusterObjectRef.h.
References ComponentName.
IsSceneComponentValid()
bool FDisplayClusterSceneComponentRef::IsSceneComponentValid () const inline
Definition at line 224 of file DisplayClusterObjectRef.h.
References ComponentPtr.
ResetSceneComponent()
void FDisplayClusterSceneComponentRef::ResetSceneComponent () inline
Definition at line 249 of file DisplayClusterObjectRef.h.
References ComponentName, ComponentPtr, FDisplayClusterActorRef::DataGuard, FName, and FDisplayClusterActorRef::ResetSceneActor().
Referenced by SetSceneComponent().
SetSceneComponent()
bool FDisplayClusterSceneComponentRef::SetSceneComponent (USceneComponent *const InComponent) inline
Definition at line 233 of file DisplayClusterObjectRef.h.
References ComponentName, ComponentPtr, FDisplayClusterActorRef::DataGuard, UObjectBase::GetFName(), UActorComponent::GetOwner(), ResetSceneComponent(), and FDisplayClusterActorRef::SetSceneActor().
Referenced by FDisplayClusterSceneComponentRef().
Field Documentation
ComponentName
FName FDisplayClusterSceneComponentRef::ComponentName private
Definition at line 266 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterSceneComponentRef(), IsDefinedSceneComponent(), IsEqualsComponentName(), ResetSceneComponent(), and SetSceneComponent().
ComponentPtr
TWeakObjectPtr<USceneComponent> FDisplayClusterSceneComponentRef::ComponentPtr mutable private
Definition at line 267 of file DisplayClusterObjectRef.h.
Referenced by FDisplayClusterSceneComponentRef(), IsSceneComponentValid(), ResetSceneComponent(), and SetSceneComponent().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Misc/DisplayClusterObjectRef.h