Unreal Engine 5.6 C++ API: UE::Sequencer::FTrackAreaViewModel Class Reference
UE::Sequencer::FTrackAreaViewModel Class Reference
#include "TrackAreaViewModel.h"
Public Member Functions
FTrackAreaViewModel ()
virtual ~FTrackAreaViewModel ()
void AddEditTool (TSharedPtr< ISequencerEditTool > InNewTool)
void AddHotspot (TSharedPtr< ITrackAreaHotspot > NewHotspot)
void AddViewSpace (const FGuid &ID, TSharedPtr< FTrackAreaViewSpace > ViewSpace)
bool AttemptToActivateTool (FName Identifier)
bool CanActivateEditTool (FName Identifier) const
Check whether it's possible to activate the specified tool.
void ClearHotspots ()
DECLARE_MULTICAST_DELEGATE_TwoParams (FViewSpaceEvent, const FGuid &, TSharedPtr< FTrackAreaViewSpace >) FViewSpaceEvent OnViewSpaceAdded
TSharedPtr< FTrackAreaViewSpace > FindViewSpace (const FGuid &InID) const
TSharedPtr< FEditorViewModel > GetEditor () const
Get the editor view-model provided by the creation context.
ISequencerEditTool * GetEditTool () const
Access the currently active track area edit tool.
TSharedPtr< ITrackAreaHotspot > GetHotspot () const
Get the current active hotspot.
FOnTrackAreaHotspotChanged & GetOnHotspotChangedDelegate ()
Get the callback that is fired when the current hotspot changes.
virtual FFrameRate GetTickResolution () const
Gets the current tick resolution of the editor.
FTimeToPixel GetTimeToPixel (float TrackAreaWidth) const
Create a time/pixel converter for the given geometry.
virtual TRange< double > GetViewRange () const
Gets the current view range of this track area.
void LockEditTool ()
void LockHotspot (bool bIsLocked)
Set whether the hotspot is locked and cannot be changed (ie when a menu is open)
virtual void OnConstruct () override
Called once for this model when it is added to a parent that has valid shared data.
void RemoveHotspot (FViewModelTypeID Type)
void RemoveViewSpace (const FGuid &ID)
void SetHotspot (TSharedPtr< ITrackAreaHotspot > NewHotspot)
Set the hotspot to something else.
UE_SEQUENCER_DECLARE_CASTABLE (FTrackAreaViewModel, FViewModel)
void UnlockEditTool ()
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Data Fields
FViewSpaceEvent OnViewSpaceRemoved
Protected Member Functions
void UpdateViewSpaces ()
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Protected Attributes
bool bEditToolLocked
When true, prevents any other edit tool being activated by way of CanActivateEditTool always returning true.
bool bHotspotLocked
When true, prevents any other hotspot being activated.
TSharedPtr< ISequencerEditTool > EditTool
The currently active edit tool on this track area.
TArray< TSharedPtr< ISequencerEditTool > > EditTools
The currently active edit tools on this track area.
TArray< TSharedPtr< ITrackAreaHotspot > > HotspotStack
The current hotspot that can be set from anywhere to initiate drags.
FOnTrackAreaHotspotChanged OnHotspotChangedDelegate
The delegate that is fired when the current hotspot changes.
TMap< FGuid, TSharedPtr< FTrackAreaViewSpace > > ViewSpaces
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Additional Inherited Members
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 31 of file TrackAreaViewModel.h.
Constructor & Destructor Documentation
FTrackAreaViewModel()
UE::Sequencer::FTrackAreaViewModel::FTrackAreaViewModel ()
Referenced by UE::Sequencer::FSequencerTrackAreaViewModel::UE_SEQUENCER_DECLARE_CASTABLE(), and UE_SEQUENCER_DECLARE_CASTABLE().
~FTrackAreaViewModel()
virtual UE::Sequencer::FTrackAreaViewModel::~FTrackAreaViewModel () virtual
Member Function Documentation
AddEditTool()
void UE::Sequencer::FTrackAreaViewModel::AddEditTool (TSharedPtr< ISequencerEditTool > InNewTool)
AddHotspot()
void UE::Sequencer::FTrackAreaViewModel::AddHotspot (TSharedPtr< ITrackAreaHotspot > NewHotspot)
AddViewSpace()
void UE::Sequencer::FTrackAreaViewModel::AddViewSpace (const FGuid & ID, TSharedPtr< FTrackAreaViewSpace > ViewSpace)
References ID.
AttemptToActivateTool()
bool UE::Sequencer::FTrackAreaViewModel::AttemptToActivateTool (FName Identifier)
CanActivateEditTool()
bool UE::Sequencer::FTrackAreaViewModel::CanActivateEditTool (FName Identifier) const
Check whether it's possible to activate the specified tool.
ClearHotspots()
void UE::Sequencer::FTrackAreaViewModel::ClearHotspots ()
DECLARE_MULTICAST_DELEGATE_TwoParams()
UE::Sequencer::FTrackAreaViewModel::DECLARE_MULTICAST_DELEGATE_TwoParams (FViewSpaceEvent , const FGuid & , TSharedPtr< FTrackAreaViewSpace >)
FindViewSpace()
TSharedPtr< FTrackAreaViewSpace > UE::Sequencer::FTrackAreaViewModel::FindViewSpace (const FGuid & InID) const
GetEditor()
TSharedPtr< FEditorViewModel > UE::Sequencer::FTrackAreaViewModel::GetEditor () const
Get the editor view-model provided by the creation context.
GetEditTool()
ISequencerEditTool * UE::Sequencer::FTrackAreaViewModel::GetEditTool () const inline
Access the currently active track area edit tool.
Definition at line 79 of file TrackAreaViewModel.h.
References EditTool.
GetHotspot()
TSharedPtr< ITrackAreaHotspot > UE::Sequencer::FTrackAreaViewModel::GetHotspot () const
Get the current active hotspot.
GetOnHotspotChangedDelegate()
FOnTrackAreaHotspotChanged & UE::Sequencer::FTrackAreaViewModel::GetOnHotspotChangedDelegate ()
Get the callback that is fired when the current hotspot changes.
GetTickResolution()
virtual FFrameRate UE::Sequencer::FTrackAreaViewModel::GetTickResolution () const virtual
Gets the current tick resolution of the editor.
Reimplemented in UE::Sequencer::FSequencerTrackAreaViewModel.
GetTimeToPixel()
FTimeToPixel UE::Sequencer::FTrackAreaViewModel::GetTimeToPixel (float TrackAreaWidth) const
Create a time/pixel converter for the given geometry.
GetViewRange()
virtual TRange< double > UE::Sequencer::FTrackAreaViewModel::GetViewRange () const virtual
Gets the current view range of this track area.
Reimplemented in UE::Sequencer::FSequencerTrackAreaViewModel.
LockEditTool()
void UE::Sequencer::FTrackAreaViewModel::LockEditTool ()
LockHotspot()
void UE::Sequencer::FTrackAreaViewModel::LockHotspot (bool bIsLocked)
Set whether the hotspot is locked and cannot be changed (ie when a menu is open)
OnConstruct()
virtual void UE::Sequencer::FTrackAreaViewModel::OnConstruct () override virtual
Called once for this model when it is added to a parent that has valid shared data.
Reimplemented from UE::Sequencer::FViewModel.
RemoveHotspot()
void UE::Sequencer::FTrackAreaViewModel::RemoveHotspot (FViewModelTypeID Type)
RemoveViewSpace()
void UE::Sequencer::FTrackAreaViewModel::RemoveViewSpace (const FGuid & ID)
References ID.
SetHotspot()
void UE::Sequencer::FTrackAreaViewModel::SetHotspot (TSharedPtr< ITrackAreaHotspot > NewHotspot)
Set the hotspot to something else.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FTrackAreaViewModel::UE_SEQUENCER_DECLARE_CASTABLE (FTrackAreaViewModel , FViewModel)
References FTrackAreaViewModel(), and UE::Sequencer::FViewModel::FViewModel().
UnlockEditTool()
void UE::Sequencer::FTrackAreaViewModel::UnlockEditTool ()
UpdateViewSpaces()
void UE::Sequencer::FTrackAreaViewModel::UpdateViewSpaces () protected
Field Documentation
bEditToolLocked
bool UE::Sequencer::FTrackAreaViewModel::bEditToolLocked protected
When true, prevents any other edit tool being activated by way of CanActivateEditTool always returning true.
Definition at line 118 of file TrackAreaViewModel.h.
bHotspotLocked
bool UE::Sequencer::FTrackAreaViewModel::bHotspotLocked protected
When true, prevents any other hotspot being activated.
Definition at line 115 of file TrackAreaViewModel.h.
EditTool
TSharedPtr<ISequencerEditTool> UE::Sequencer::FTrackAreaViewModel::EditTool protected
The currently active edit tool on this track area.
Definition at line 112 of file TrackAreaViewModel.h.
Referenced by GetEditTool().
EditTools
TArray<TSharedPtr<ISequencerEditTool> > UE::Sequencer::FTrackAreaViewModel::EditTools protected
The currently active edit tools on this track area.
Definition at line 109 of file TrackAreaViewModel.h.
HotspotStack
TArray<TSharedPtr<ITrackAreaHotspot> > UE::Sequencer::FTrackAreaViewModel::HotspotStack protected
The current hotspot that can be set from anywhere to initiate drags.
Definition at line 103 of file TrackAreaViewModel.h.
OnHotspotChangedDelegate
FOnTrackAreaHotspotChanged UE::Sequencer::FTrackAreaViewModel::OnHotspotChangedDelegate protected
The delegate that is fired when the current hotspot changes.
Definition at line 106 of file TrackAreaViewModel.h.
OnViewSpaceRemoved
FViewSpaceEvent UE::Sequencer::FTrackAreaViewModel::OnViewSpaceRemoved
Definition at line 46 of file TrackAreaViewModel.h.
ViewSpaces
TMap<FGuid, TSharedPtr<FTrackAreaViewSpace> > UE::Sequencer::FTrackAreaViewModel::ViewSpaces protected
Definition at line 100 of file TrackAreaViewModel.h.
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/TrackAreaViewModel.h