Unreal Engine 5.6 C++ API: FQuatFloat32NoW Class Reference
FQuatFloat32NoW Class Reference
#include "AnimationCompression.h"
Public Member Functions
FQuatFloat32NoW ()
FQuatFloat32NoW (const FQuat4f &Quat)
void FromQuat (const FQuat4f &Quat)
void ToQuat (FQuat4f &Out) const
Static Public Member Functions
template<bool bIsDataAligned>
static FQuat4f ToQuat (const uint32 *PackedValue)
Data Fields
uint32 Packed
Friends
FArchive & operator<< (FArchive &Ar, FQuatFloat32NoW &Quat)
Detailed Description
Definition at line 476 of file AnimationCompression.h.
Constructor & Destructor Documentation
FQuatFloat32NoW() [1/2]
FQuatFloat32NoW::FQuatFloat32NoW () inline
Definition at line 481 of file AnimationCompression.h.
Referenced by operator<<.
FQuatFloat32NoW() [2/2]
FQuatFloat32NoW::FQuatFloat32NoW (const FQuat4f & Quat) inline explicit
Definition at line 484 of file AnimationCompression.h.
References FromQuat(), and Quat.
Member Function Documentation
FromQuat()
void FQuatFloat32NoW::FromQuat (const FQuat4f & Quat) inline
Definition at line 489 of file AnimationCompression.h.
References TFloatPacker< NumExponentBits, NumMantissaBits, bRound, FloatInfo >::Encode(), UE::Math::TQuat< T >::Normalize(), Packed, Quat, UE::Math::TQuat< T >::W, UE::Math::TQuat< T >::X, UE::Math::TQuat< T >::Y, and UE::Math::TQuat< T >::Z.
Referenced by FQuatFloat32NoW().
ToQuat() [1/2]
template<bool bIsDataAligned> FQuat4f FQuatFloat32NoW::ToQuat (const uint32 * PackedValue) inline static
Definition at line 515 of file AnimationCompression.h.
References TFloatPacker< NumExponentBits, NumMantissaBits, bRound, FloatInfo >::Decode(), Packed, AnimationCompressionUtils::UnalignedRead(), X, Y, and Z.
Referenced by DecompressRotation(), FAnimationCompression_PerTrackUtils::DecompressRotation(), and ToQuat().
ToQuat() [2/2]
void FQuatFloat32NoW::ToQuat (FQuat4f & Out) const inline
Definition at line 539 of file AnimationCompression.h.
References Packed, and ToQuat().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FQuatFloat32NoW & Quat) friend
Definition at line 544 of file AnimationCompression.h.
References FQuatFloat32NoW(), Ar, and Quat.
Field Documentation
Packed
uint32 FQuatFloat32NoW::Packed
Definition at line 479 of file AnimationCompression.h.
Referenced by FromQuat(), ToQuat(), and ToQuat().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AnimationCompression.h