Unreal Engine 5.6 C++ API: TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator > Class Template Reference
TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator > Class Template Reference
Iterates over the elements in the octree that intersect a bounding box.
#include "GenericOctree.h"
Public Member Functions
TConstElementBoxIterator (const TOctree_DEPRECATED &Tree, const FBoxCenterAndExtent &InBoundingBox)
Initialization constructor.
void Advance ()
Iterates to the next element.
const ElementType & GetCurrentElement () const
bool HasPendingElements () const
Checks if there are any elements left to iterate over.
Private Member Functions
void AdvanceToNextIntersectingElement ()
Advances the iterator to the next intersecting primitive, starting at a primitive in the current node.
void ProcessChildren ()
Processes the children of the current node.
Private Attributes
ElementConstIt ElementIt
The element iterator for the current node.
FBoxCenterAndExtent IteratorBounds
The bounding box to check for intersection with.
TConstIterator< StackAllocator > NodeIt
The octree node iterator.
Detailed Description
template<typename ElementType, typename OctreeSemantics>
template<typename StackAllocator = DefaultStackAllocator>
class TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >
Iterates over the elements in the octree that intersect a bounding box.
Definition at line 1298 of file GenericOctree.h.
Constructor & Destructor Documentation
TConstElementBoxIterator()
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::TConstElementBoxIterator (const TOctree_DEPRECATED & Tree, const FBoxCenterAndExtent & InBoundingBox) inline
Initialization constructor.
Definition at line 1316 of file GenericOctree.h.
References TOctree_DEPRECATED< ElementType, OctreeSemantics >::TOctree_DEPRECATED(), AdvanceToNextIntersectingElement(), ElementIt, IteratorBounds, NodeIt, ProcessChildren(), and TOctree_DEPRECATED< ElementType, OctreeSemantics >::RootNode.
Member Function Documentation
Advance()
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::Advance () inline
Iterates to the next element.
Definition at line 1303 of file GenericOctree.h.
References AdvanceToNextIntersectingElement(), and ElementIt.
AdvanceToNextIntersectingElement()
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::AdvanceToNextIntersectingElement () inline private
Advances the iterator to the next intersecting primitive, starting at a primitive in the current node.
Definition at line 1359 of file GenericOctree.h.
References check, ElementIt, IteratorBounds, Move, NodeIt, PLATFORM_CACHE_LINE_SIZE, FGenericPlatformMisc::Prefetch(), and ProcessChildren().
Referenced by TConstElementBoxIterator(), and Advance().
GetCurrentElement()
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> const ElementType & TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::GetCurrentElement () const inline nodiscard
Definition at line 1326 of file GenericOctree.h.
References ElementIt.
HasPendingElements()
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> bool TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::HasPendingElements () const inline nodiscard
Checks if there are any elements left to iterate over.
Definition at line 1310 of file GenericOctree.h.
References NodeIt.
ProcessChildren()
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> void TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::ProcessChildren () inline private
Processes the children of the current node.
Definition at line 1343 of file GenericOctree.h.
References FOctreeChildNodeSubset::Contains(), FOREACH_OCTREE_CHILD_NODE, TOctree_DEPRECATED< ElementType, OctreeSemantics >::FNode::HasChild(), IteratorBounds, and NodeIt.
Referenced by TConstElementBoxIterator(), and AdvanceToNextIntersectingElement().
Field Documentation
ElementIt
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> ElementConstIt TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::ElementIt private
The element iterator for the current node.
Definition at line 1340 of file GenericOctree.h.
Referenced by TConstElementBoxIterator(), Advance(), AdvanceToNextIntersectingElement(), and GetCurrentElement().
IteratorBounds
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> FBoxCenterAndExtent TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::IteratorBounds private
The bounding box to check for intersection with.
Definition at line 1334 of file GenericOctree.h.
Referenced by TConstElementBoxIterator(), AdvanceToNextIntersectingElement(), and ProcessChildren().
NodeIt
template<typename ElementType, typename OctreeSemantics> template<typename StackAllocator = DefaultStackAllocator> TConstIterator<StackAllocator> TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::NodeIt private
The octree node iterator.
Definition at line 1337 of file GenericOctree.h.
Referenced by TConstElementBoxIterator(), AdvanceToNextIntersectingElement(), HasPendingElements(), and ProcessChildren().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/GenericOctree.h