Unreal Engine 5.6 C++ API: FRDGParameterStruct Class Reference
FRDGParameterStruct Class Reference
Wraps a pass parameter struct payload and provides helpers for traversing members.
#include "RenderGraphParameter.h"
Public Member Functions
template<typename ParameterStructType>
FRDGParameterStruct (const ParameterStructType *Parameters, const FShaderParametersMetadata *InParameterMetadata)
FRDGParameterStruct (const void *InContents, const FRHIUniformBufferLayout *InLayout)
template<typename FunctionType>
void Enumerate (FunctionType Function) const
Enumerates all graph parameters on the layout.
template<typename FunctionType>
void EnumerateBuffers (FunctionType Function) const
Same as Enumerate, but only buffer parameters are included.
template<typename FunctionType>
void EnumerateTextures (FunctionType Function) const
Same as Enumerate, but only texture parameters are included.
template<typename FunctionType>
void EnumerateUniformBuffers (FunctionType Function) const
Enumerates all non-null uniform buffers.
uint32 GetBufferParameterCount () const
Returns the number of buffer parameters present on the layout.
const uint8 * GetContents () const
Returns the contents of the struct.
const FRHIUniformBufferLayout & GetLayout () const
Returns the layout associated with this struct.
const FRHIUniformBufferLayout * GetLayoutPtr () const
const FShaderParametersMetadata * GetMetadata () const
RENDERCORE_API FRHIRenderPassInfo GetRenderPassInfo () const
Returns the render pass info generated from the render target binding slots.
const FRenderTargetBindingSlots & GetRenderTargets () const
Returns the render target binding slots.
RENDERCORE_API FUniformBufferStaticBindings GetStaticUniformBuffers () const
Returns a set of static uniform buffer bindings for the parameter struct.
uint32 GetTextureParameterCount () const
Returns the number of texture parameters present on the layout.
uint32 GetUniformBufferParameterCount () const
Returns the number of RDG uniform buffers present in the layout.
FORCEINLINE bool HasExternalOutputs () const
FORCEINLINE bool HasRenderTargets () const
Helpful forwards from the layout.
FORCEINLINE bool HasStaticSlot () const
Static Public Member Functions
static void ClearUniformBuffers (void *Contents, const FRHIUniformBufferLayout *Layout)
Clears out all uniform buffer references in the parameter struct.
Private Member Functions
FRDGParameter GetParameterInternal (TArrayView< const FRHIUniformBufferResource > Parameters, uint32 ParameterIndex) const
Private Attributes
const uint8 * Contents
FUniformBufferLayoutRHIRef Layout
const FShaderParametersMetadata * Metadata = nullptr
Friends
class FRDGPass
Detailed Description
Wraps a pass parameter struct payload and provides helpers for traversing members.
Definition at line 212 of file RenderGraphParameter.h.
Constructor & Destructor Documentation
FRDGParameterStruct() [1/2]
template<typename ParameterStructType> FRDGParameterStruct::FRDGParameterStruct (const ParameterStructType * Parameters, const FShaderParametersMetadata * InParameterMetadata) inline explicit
Definition at line 216 of file RenderGraphParameter.h.
References Contents, GetLayoutPtr(), Layout, and Metadata.
Referenced by TRDGParameterStruct< ParameterStructType >::TRDGParameterStruct().
FRDGParameterStruct() [2/2]
FRDGParameterStruct::FRDGParameterStruct (const void * InContents, const FRHIUniformBufferLayout * InLayout) inline explicit
Definition at line 222 of file RenderGraphParameter.h.
References checkf, Contents, Layout, and TEXT.
Member Function Documentation
ClearUniformBuffers()
void FRDGParameterStruct::ClearUniformBuffers (void * Contents, const FRHIUniformBufferLayout * Layout) static
Clears out all uniform buffer references in the parameter struct.
References Contents, and Layout.
Enumerate()
template<typename FunctionType> void FRDGParameterStruct::Enumerate (FunctionType Function) const
Enumerates all graph parameters on the layout.
Graph uniform buffers are traversed recursively but are also included in the enumeration. Expected function signature: void(FRDGParameter).
References Function.
EnumerateBuffers()
template<typename FunctionType> void FRDGParameterStruct::EnumerateBuffers (FunctionType Function) const
Same as Enumerate, but only buffer parameters are included.
References Function.
EnumerateTextures()
template<typename FunctionType> void FRDGParameterStruct::EnumerateTextures (FunctionType Function) const
Same as Enumerate, but only texture parameters are included.
References Function.
EnumerateUniformBuffers()
template<typename FunctionType> void FRDGParameterStruct::EnumerateUniformBuffers (FunctionType Function) const
Enumerates all non-null uniform buffers.
Expected function signature: void(FRDGUniformBufferBinding).
References Function.
GetBufferParameterCount()
uint32 FRDGParameterStruct::GetBufferParameterCount () const inline
Returns the number of buffer parameters present on the layout.
Definition at line 244 of file RenderGraphParameter.h.
References Layout.
GetContents()
const uint8 * FRDGParameterStruct::GetContents () const inline
Returns the contents of the struct.
Definition at line 230 of file RenderGraphParameter.h.
References Contents.
Referenced by TRDGParameterStruct< ParameterStructType >::GetContents().
GetLayout()
const FRHIUniformBufferLayout & FRDGParameterStruct::GetLayout () const inline
Returns the layout associated with this struct.
Definition at line 233 of file RenderGraphParameter.h.
References Layout.
Referenced by TRDGParameterStruct< ParameterStructType >::TRDGParameterStruct().
GetLayoutPtr()
const FRHIUniformBufferLayout * FRDGParameterStruct::GetLayoutPtr () const inline
Definition at line 234 of file RenderGraphParameter.h.
References Layout.
Referenced by FRDGParameterStruct().
GetMetadata()
const FShaderParametersMetadata * FRDGParameterStruct::GetMetadata () const inline
Definition at line 236 of file RenderGraphParameter.h.
References Metadata.
GetParameterInternal()
FRDGParameter FRDGParameterStruct::GetParameterInternal (TArrayView< const FRHIUniformBufferResource > Parameters, uint32 ParameterIndex) const inline private
Definition at line 288 of file RenderGraphParameter.h.
References checkf, Contents, Layout, TArrayView< InElementType, InSizeType >::Num(), and TEXT.
GetRenderPassInfo()
RENDERCORE_API FRHIRenderPassInfo FRDGParameterStruct::GetRenderPassInfo () const
Returns the render pass info generated from the render target binding slots.
Referenced by GetRenderPassInfo().
GetRenderTargets()
const FRenderTargetBindingSlots & FRDGParameterStruct::GetRenderTargets () const inline
Returns the render target binding slots.
Asserts if they don't exist.
Definition at line 253 of file RenderGraphParameter.h.
References check, Contents, HasRenderTargets(), and Layout.
GetStaticUniformBuffers()
RENDERCORE_API FUniformBufferStaticBindings FRDGParameterStruct::GetStaticUniformBuffers () const
Returns a set of static uniform buffer bindings for the parameter struct.
Referenced by GetStaticUniformBuffers().
GetTextureParameterCount()
uint32 FRDGParameterStruct::GetTextureParameterCount () const inline
Returns the number of texture parameters present on the layout.
Definition at line 247 of file RenderGraphParameter.h.
References Layout.
GetUniformBufferParameterCount()
uint32 FRDGParameterStruct::GetUniformBufferParameterCount () const inline
Returns the number of RDG uniform buffers present in the layout.
Definition at line 250 of file RenderGraphParameter.h.
References Layout.
HasExternalOutputs()
FORCEINLINE bool FRDGParameterStruct::HasExternalOutputs () const inline
Definition at line 240 of file RenderGraphParameter.h.
References FORCEINLINE, and Layout.
HasRenderTargets()
FORCEINLINE bool FRDGParameterStruct::HasRenderTargets () const inline
Helpful forwards from the layout.
Definition at line 239 of file RenderGraphParameter.h.
References FORCEINLINE, and Layout.
Referenced by GetRenderTargets(), and HasRenderPassInfo().
HasStaticSlot()
FORCEINLINE bool FRDGParameterStruct::HasStaticSlot () const inline
Definition at line 241 of file RenderGraphParameter.h.
References FORCEINLINE, and Layout.
Friends And Related Symbol Documentation
FRDGPass
friend class FRDGPass friend
Definition at line 300 of file RenderGraphParameter.h.
References FRDGPass.
Referenced by FRDGPass.
Field Documentation
Contents
const uint8* FRDGParameterStruct::Contents private
Definition at line 296 of file RenderGraphParameter.h.
Referenced by FRDGParameterStruct(), FRDGParameterStruct(), ClearUniformBuffers(), GetContents(), GetParameterInternal(), and GetRenderTargets().
Layout
FUniformBufferLayoutRHIRef FRDGParameterStruct::Layout private
Definition at line 297 of file RenderGraphParameter.h.
Referenced by FRDGParameterStruct(), FRDGParameterStruct(), ClearUniformBuffers(), GetBufferParameterCount(), GetLayout(), GetLayoutPtr(), GetParameterInternal(), GetRenderTargets(), GetTextureParameterCount(), GetUniformBufferParameterCount(), HasExternalOutputs(), HasRenderTargets(), and HasStaticSlot().
Metadata
const FShaderParametersMetadata* FRDGParameterStruct::Metadata = nullptr private
Definition at line 298 of file RenderGraphParameter.h.
Referenced by FRDGParameterStruct(), and GetMetadata().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphParameter.h