Unreal Engine 5.6 C++ API: FNumericProperty Class Reference
FNumericProperty Class Reference
#include "UnrealType.h"
Private Member Functions
FNumericProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled in properties.
template<typename T>
bool CanHoldValue (T Value) const
DECLARE_FIELD_API (FNumericProperty, FProperty, CASTCLASS_FNumericProperty, 1) 1 FNumericProperty(FFieldVariant InOwner
virtual void ExportText_Internal (FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const override
virtual double GetFloatingPointPropertyValue (void const *Data) const
Gets the value of an floating point property type.
virtual UEnum * GetIntPropertyEnum () const
Return the UEnum if this property is a FByteProperty with a non-null Enum.
virtual FString GetNumericPropertyValueToString (void const *Data) const
Get the value of any numeric type and return it as a string.
virtual FString GetNumericPropertyValueToString_InContainer (void const *Container) const
virtual int64 GetSignedIntPropertyValue (void const *Data) const
Gets the value of a signed integral property type.
virtual int64 GetSignedIntPropertyValue_InContainer (void const *Container) const
virtual uint64 GetUnsignedIntPropertyValue (void const *Data) const
Gets the value of an unsigned integral property type.
virtual uint64 GetUnsignedIntPropertyValue_InContainer (void const *Container) const
virtual const TCHAR * ImportText_Internal (const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject *Parent, int32 PortFlags, FOutputDevice *ErrorText) const override
FORCEINLINE bool IsEnum () const
Return true if this property is a FByteProperty with a non-null Enum.
virtual bool IsFloatingPoint () const
Return true if this property is for a floating point number.
virtual bool IsInteger () const
Return true if this property is for a integral or enum type.
virtual void SetFloatingPointPropertyValue (void *Data, double Value) const
Set the value of a floating point property type.
virtual void SetIntPropertyValue (void *Data, int64 Value) const
Set the value of a signed integral property type.
virtual void SetIntPropertyValue (void *Data, uint64 Value) const
Set the value of an unsigned integral property type.
virtual void SetNumericPropertyValueFromString (void *Data, TCHAR const *Value) const
Set the value of any numeric type from a string point.
virtual void SetNumericPropertyValueFromString_InContainer (void *Container, TCHAR const *Value) const
Static Private Member Functions
static int64 ReadEnumAsInt64 (FStructuredArchive::FSlot Slot, UStruct *DefaultsStruct, const FPropertyTag &Tag)
Private Attributes
virtual bool CanHoldDoubleValueInternal (double Value) const PURE_VIRTUAL(FNumericProperty
virtual bool CanHoldSignedValueInternal (int64 Value) const PURE_VIRTUAL(FNumericProperty
virtual bool CanHoldUnsignedValueInternal (uint64 Value) const PURE_VIRTUAL(FNumericProperty
const FName & InName
const FName EObjectFlags InObjectFlags
Additional Inherited Members
Public Types inherited from FField
typedef FField BaseFieldClass
typedef FFieldClass FieldTypeClass
using FLinkedListBuilder = TLinkedListBuilder<FField>
typedef FField Super
typedef FField ThisClass
Public Member Functions inherited from FProperty
FProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithoutOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
void * AllocateAndInitializeValue () const
Allocates and initializes memory to hold a value this property represents.
virtual void CallGetter (const void *Container, void *OutValue) const
Calls the native getter function for this property.
virtual void CallSetter (void *Container, const void *InValue) const
Calls the native setter function for this property.
virtual bool CanSerializeFromTypeName (UE::FPropertyTypeName Type) const
Returns true if the type of this property matches the type name.
virtual void ClearIntrusiveOptionalValue (void *Data) const
Set the value to it's special unset state.
FORCEINLINE void ClearPropertyFlags (EPropertyFlags NewFlags)
FORCEINLINE void ClearValue (void *Data) const
Zeros the value for this property.
FORCEINLINE void ClearValue_InContainer (void *Data, int32 ArrayIndex=0) const
Zeros the value for this property.
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (UObject *ContainerPtr, int32 ArrayIndex=0) const
Get the pointer to property value in a supplied 'container'.
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (void const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void const *ContainerPtr, int32 ArrayIndex=0) const
bool ContainsFinishDestroy (TArray< const FStructProperty * > &EncounteredStructProps) const
Returns true if the property or any of the child properties should be cleared on FinishDestroy.
FORCEINLINE bool ContainsInstancedObjectProperty () const
Returns true if this property, or in the case of e.g.
virtual bool ContainsObjectReference (TArray< const FStructProperty * > &EncounteredStructProps, EPropertyObjectReferenceType InReferenceType=EPropertyObjectReferenceType::Strong) const
Returns true if this property, or in the case of e.g.
bool ContainsWeakObjectReference () const
Returns true if this property, or in the case of e.g.
virtual EConvertFromTypeResult ConvertFromType (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, const uint8 *Defaults)
Allows a property to implement backwards compatibility handling for tagged properties.
FORCEINLINE void CopyCompleteValue (void *Dest, void const *Src) const
Copy the value for all elements of this property.
FORCEINLINE void CopyCompleteValue_InContainer (void *Dest, void const *Src) const
virtual void CopyCompleteValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueFromScriptVM_InContainer (void *OutContainer, void const *InValue) const
virtual void CopyCompleteValueToScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueToScriptVM_InContainer (void *OutValue, void const *InContainer) const
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
FORCEINLINE void CopySingleValue (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueToScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
void DestroyAndFreeValue (void *InMemory) const
Destroys and frees memory with a value this property represents.
FORCEINLINE void DestroyValue (void *Dest) const
Destroys the value for this property.
FORCEINLINE void DestroyValue_InContainer (void *Dest) const
Destroys the value for this property.
virtual void EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
virtual void EmitReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
bool ExportText_Direct (FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
FORCEINLINE bool ExportText_InContainer (int32 Index, FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_Direct (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_InContainer (FString &ValueStr, const void *Container, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void FinishDestroy (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
void FinishDestroy_InContainer (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
ELifetimeCondition GetBlueprintReplicationCondition () const
virtual FString GetCPPMacroType (FString &ExtendedTypeText) const
int32 GetElementSize () const
virtual FName GetID () const
virtual int32 GetMinAlignment () const
FString GetNameCPP () const
Returns the C++ name of the property, including the _DEPRECATED suffix if the property is deprecated.
FORCEINLINE int32 GetOffset_ForDebug () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForGC () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForInternal () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForUFunction () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ReplaceWith_ContainerPtrToValuePtr () const
Return offset of property from container base.
FProperty * GetOwnerProperty ()
Returns the first FProperty in this property's Outer chain that does not have a FProperty for an Outer.
const FProperty * GetOwnerProperty () const
FORCEINLINE EPropertyFlags GetPropertyFlags () const
Returns this property's propertyflags.
FORCEINLINE FProperty * GetRepOwner ()
Returns the replication owner, which is the property itself, or NULL if this isn't important for replication.
void GetSingleValue_InContainer (const void *InContainer, void *OutValue, int32 ArrayIndex) const
Copies a single value to OutValue even if the property represents a static array of values.
FORCEINLINE int32 GetSize () const
FORCEINLINE void GetValue_InContainer (void const *InContainer, void *OutValue) const
virtual void * GetValueAddressAtIndex_Direct (const FProperty *Inner, void *InValueAddress, int32 Index) const
Gets value address at given index inside of a static array or container.
uint32 GetValueTypeHash (const void *Src) const
Returns the hash value for an element of this property.
FORCEINLINE bool HasAllPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAnyPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
virtual bool HasGetter () const
Checks if this property as a native getter function.
virtual bool HasSetter () const
Checks if this property as a native setter function.
virtual bool HasSetterOrGetter () const
Checks if this property as a native setter or getter function.
bool Identical_InContainer (const void *A, const void *B, int32 ArrayIndex=0, uint32 PortFlags=0) const
Determines whether the property values are identical.
const TCHAR * ImportText_Direct (const TCHAR *Buffer, void *PropertyPtr, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
const TCHAR * ImportText_InContainer (const TCHAR *Buffer, void *Container, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
virtual bool virtual HasIntrusiveUnsetOptionalState() const PURE_VIRTUAL(FProperty void InitializeIntrusiveUnsetOptionalValue (void *Data) const
Returns whether this type has a special state for an unset TOptional meaning the size TOptional<T> and T are the same.
FORCEINLINE void InitializeValue (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE void InitializeValue_InContainer (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
virtual void InstanceSubobjects (void *Data, void const *DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph *InstanceGraph)
Creates new copies of components.
FORCEINLINE bool IsEditorOnlyProperty () const
Editor-only properties are those that only are used with the editor is present or cannot be removed from serialisation.
FORCEINLINE bool IsInContainer (const UStruct *ContainerClass) const
See if the offset of this property is below the supplied container size.
FORCEINLINE bool IsInContainer (int32 ContainerSize) const
See if the offset of this property is below the supplied container size.
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const
Returns whether an optional value of this inner type is unset.
int32 Link (FArchive &Ar)
void LinkWithoutChangingOffset (FArchive &Ar)
virtual bool LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag *Tag=nullptr)
Restores this property and its owned properties from the type name.
void PerformOperationWithGetter (void *OutContainer, const void *DirectPropertyAddress, TFunctionRef< void(const void *)> DirectValueAccessFunc) const
Helper function for getting container / struct property value and performing operation directly on the value memory.
void PerformOperationWithSetter (void *OutContainer, void *DirectPropertyAddress, TFunctionRef< void(void *)> DirectValueAccessFunc) const
Helper function for setting container / struct property value and performing operation directly on the value memory.
virtual void PostDuplicate (const FField &InField) override
Fixups after duplicating a Field.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const
Attempt to resolve the given inner path info against this outer property to get the inner property value.
virtual bool SameType (const FProperty *Other) const
returns true, if Other is property of exactly the same type
virtual void SaveTypeName (UE::FPropertyTypeNameBuilder &Type) const
Saves the type name of this property and its owned properties.
virtual void Serialize (FArchive &Ar) override
void SerializeBinProperty (FStructuredArchive::FSlot Slot, void *Data, int32 ArrayIdx=-1)
Serializes the property with the struct's data residing in Data.
void SerializeNonMatchingBinProperty (FStructuredArchive::FSlot Slot, void *Data, void const *DefaultData, UStruct *DefaultStruct)
Serializes the property with the struct's data residing in Data, unless it matches the default.
void SetBlueprintReplicationCondition (ELifetimeCondition InBlueprintReplicationCondition)
void SetElementSize (int32 NewSize)
FORCEINLINE void SetPropertyFlags (EPropertyFlags NewFlags)
void SetSingleValue_InContainer (void *OutContainer, const void *InValue, int32 ArrayIndex) const
Copies a single value to the property even if the property represents a static array of values.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const void *InValue) const
bool ShouldDuplicateValue () const
Determines whether this property value is eligible for copying when duplicating an object.
bool ShouldPort (uint32 PortFlags=0) const
bool ShouldSerializeValue (FArchive &Ar) const
virtual bool SupportsNetSharedSerialization () const
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow Visit(const FPropertyVisitorData &Data
virtual bool UseBinaryOrNativeSerialization (const FArchive &Ar) const
bool ValidateImportFlags (uint32 PortFlags, FOutputDevice *ErrorText=NULL) const
Verify that modifying this property's value via ImportText is allowed.
EPropertyVisitorControlFlow Visit (const FPropertyVisitorData &Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from FField
FField (EInternal InInernal, FFieldClass *InClass)
FField (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
virtual ~FField ()
virtual void AddCppProperty (FProperty *Property)
virtual void AddReferencedObjects (FReferenceCollector &Collector)
void AppendName (FString &ResultString) const
virtual void BeginDestroy ()
virtual void Bind ()
void ClearFlags (EObjectFlags NewFlags)
FString GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
uint64 GetCastFlags () const
FFieldClass * GetClass () const
virtual SIZE_T GetFieldSize () const
EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
FString GetFullName () const
virtual FField * GetInnerFieldByName (const FName &InName)
Returns an inner field by name if the field has any.
virtual void GetInnerFields (TArray< FField * > &OutFields)
Fills the provided array with all inner fields this field owns (recursively)
FLinkerLoad * GetLinker () const
FORCEINLINE FString GetName () const
FORCEINLINE void GetName (FString &OutName) const
UPackage * GetOutermost () const
Goes up the outer chain to look for the outermost package.
template<typename T>
T * GetOwner () const
template<typename T>
FUNCTION_NON_NULL_RETURN_START T * GetOwnerChecked () const FUNCTION_NON_NULL_RETURN_END
UClass * GetOwnerClass () const
Goes up the outer chain to look for a UClass.
UStruct * GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
UField * GetOwnerUField () const
Goes up the outer chain to look for a UField.
FORCEINLINE UObject * GetOwnerUObject () const
Goes up the outer chain to look for a UObject.
FFieldVariant GetOwnerVariant () const
Gets the owner container for this field.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=nullptr) const
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
template<typename T>
T * GetTypedOwner () const
FField * GetTypedOwner (FFieldClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
UObject * GetTypedOwner (UClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE UObject * InternalGetOwnerAsUObjectUnsafe () const
Internal function for quickly getting the owner of this object as UObject.
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *FieldType) const
bool IsIn (const FField *InOwner) const
bool IsIn (const UObject *InOwner) const
bool IsNative () const
bool IsRooted () const
bool IsValidLowLevel () const
virtual void PostLoad ()
void Rename (const FName &NewName)
void SetFlags (EObjectFlags NewFlags)
UE_DEPRECATED (5.0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAllCastFlags(const uint64 InCastFlags) const
UE_DEPRECATED (5.0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAnyCastFlags(const uint64 InCastFlags) const
Static Public Member Functions inherited from FProperty
static FName FindRedirectedPropertyName (const UStruct *ObjectStruct, FName OldName)
Gets a redirected property name, will return NAME_None if no redirection was found.
static const TCHAR * ImportSingleProperty (const TCHAR *Str, void *DestData, const UStruct *ObjectStruct, UObject *SubobjectOuter, int32 PortFlags, FOutputDevice *Warn, TArray< struct FDefinedProperty > &DefinedProperties)
parses and imports a text definition of a single property's value (if array, may be an individual element) also includes parsing of special operations for array properties (Add/Remove/RemoveIndex/Empty)
Static Public Member Functions inherited from FField
static FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given its class.
static FField * Construct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given the name of its class.
static FField * Duplicate (const FField *InField, FFieldVariant DestOwner, const FName DestName=NAME_None, EObjectFlags FlagMask=RF_AllFlags, EInternalObjectFlags InternalFlagsMask=EInternalObjectFlags_AllFlags)
Duplicates an FField.
static FName GenerateFFieldName (FFieldVariant InOwner, FFieldClass *InClass)
Generates a name for a Field of a given type.
static FFieldClass * StaticClass ()
static constexpr uint64 StaticClassCastFlags ()
static constexpr uint64 StaticClassCastFlagsPrivate ()
static FField * TryConstruct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Tries to construct a new field given the name of its class.
Data Fields inherited from FProperty
const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc const
FProperty * DestructorLinkNext
In memory only: Linked list of properties requiring destruction.
virtual FString GetCPPType (FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const PURE_VIRTUAL(FProperty
Returns the text to use for exporting this property to header file.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags=0) const PURE_VIRTUAL(FProperty
Determines whether the property values are identical.
virtual void virtual SerializeItem(FStructuredArchive::FSlot Slot, void *Value, void const *Defaults=NULL) const PURE_VIRTUAL(FProperty boo NetSerializeItem)(FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const
FProperty * NextRef
In memory only: Linked list of object reference properties from most-derived to base.
FProperty * PostConstructLinkNext
In memory only: Linked list of properties requiring post constructor initialization.
EPropertyFlags PropertyFlags
FProperty * PropertyLinkNext
In memory only: Linked list of properties from most-derived to base.
uint16 RepIndex
FName RepNotifyFunc
Data Fields inherited from FField
EObjectFlags FlagsPrivate
Object flags.
FName NamePrivate
Name of this field.
FField * Next
Next Field in the linked list.
FFieldVariant Owner
Owner of this field.
Protected Member Functions inherited from FProperty
virtual void ClearValueInternal (void *Data) const
virtual bool ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > &EncounteredStructProps) const
virtual void CopyValuesInternal (void *Dest, void const *Src, int32 Count) const
virtual void DestroyValueInternal (void *Dest) const
virtual void FinishDestroyInternal (void *Data) const
virtual uint32 GetValueTypeHashInternal (const void *Src) const
void Init ()
Initializes internal state.
virtual void InitializeValueInternal (void *Dest) const
virtual void LinkInternal (FArchive &Ar)
FORCEINLINE void * PointerToValuePtr (void const *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, int32 ArrayIndex=0) const
void SetOffset_Internal (int32 NewOffset)
Set the alignment offset for this property - added for FMapProperty.
Protected Member Functions inherited from FField
void SetFlagsTo (EObjectFlags NewFlags)
Set the object flags directly.
Protected Attributes inherited from FProperty
virtual void virtual ExportText_Internal(FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const PURE_VIRTUAL(FProperty const TCHAR ImportText_Internal)(const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const PURE_VIRTUAL(FProperty
Detailed Description
Definition at line 1673 of file UnrealType.h.
Constructor & Destructor Documentation
FNumericProperty()
FNumericProperty::FNumericProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset & Prop, EPropertyFlags AdditionalPropertyFlags = CPF_None) private
Constructor used for constructing compiled in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
References FNumericProperty(), FProperty::const, and UE_API.
Referenced by FNumericProperty(), and DECLARE_FIELD_API().
Member Function Documentation
CanHoldValue()
template<typename T> bool FNumericProperty::CanHoldValue (T Value) const inline private
Definition at line 1704 of file UnrealType.h.
References CanHoldDoubleValueInternal, CanHoldSignedValueInternal, CanHoldUnsignedValueInternal, TIsFloatingPoint< T >::Value, TIsSigned< T >::Value, and Value.
DECLARE_FIELD_API()
FNumericProperty::DECLARE_FIELD_API (FNumericProperty , FProperty , CASTCLASS_FNumericProperty , 1) private
References FNumericProperty(), FProperty::FProperty(), CASTCLASS_FNumericProperty, and UE_API.
ExportText_Internal()
virtual void FNumericProperty::ExportText_Internal (FString & ValueStr, const void * PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const override private virtual
Reimplemented in FByteProperty.
References Parent, and UE_API.
GetFloatingPointPropertyValue()
virtual double FNumericProperty::GetFloatingPointPropertyValue (void const * Data) const private virtual
Gets the value of an floating point property type.
Parameters
Data - pointer to property data to get
Returns
Data as a double
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API.
GetIntPropertyEnum()
virtual UEnum * FNumericProperty::GetIntPropertyEnum () const private virtual
Return the UEnum if this property is a FByteProperty with a non-null Enum.
Reimplemented in FByteProperty.
References UE_API.
Referenced by IsEnum().
GetNumericPropertyValueToString()
virtual FString FNumericProperty::GetNumericPropertyValueToString (void const * Data) const private virtual
Get the value of any numeric type and return it as a string.
Parameters
Data - pointer to property data to get
Returns
Data as a string CAUTION: This routine does not do enum name conversion
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API.
GetNumericPropertyValueToString_InContainer()
virtual FString FNumericProperty::GetNumericPropertyValueToString_InContainer (void const * Container) const private virtual
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References Container, and UE_API.
GetSignedIntPropertyValue()
virtual int64 FNumericProperty::GetSignedIntPropertyValue (void const * Data) const private virtual
Gets the value of a signed integral property type.
Parameters
Data - pointer to property data to get
Returns
Data as a signed int
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API.
GetSignedIntPropertyValue_InContainer()
virtual int64 FNumericProperty::GetSignedIntPropertyValue_InContainer (void const * Container) const private virtual
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References Container, and UE_API.
GetUnsignedIntPropertyValue()
virtual uint64 FNumericProperty::GetUnsignedIntPropertyValue (void const * Data) const private virtual
Gets the value of an unsigned integral property type.
Parameters
Data - pointer to property data to get
Returns
Data as an unsigned int
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API.
GetUnsignedIntPropertyValue_InContainer()
virtual uint64 FNumericProperty::GetUnsignedIntPropertyValue_InContainer (void const * Container) const private virtual
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References Container, and UE_API.
ImportText_Internal()
virtual const TCHAR * FNumericProperty::ImportText_Internal (const TCHAR * Buffer, void * ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject * Parent, int32 PortFlags, FOutputDevice * ErrorText) const override private virtual
Reimplemented in FByteProperty.
References Buffer, Parent, and UE_API.
IsEnum()
FORCEINLINE bool FNumericProperty::IsEnum () const inline private
Return true if this property is a FByteProperty with a non-null Enum.
Definition at line 1722 of file UnrealType.h.
References FORCEINLINE, and GetIntPropertyEnum().
IsFloatingPoint()
virtual bool FNumericProperty::IsFloatingPoint () const private virtual
Return true if this property is for a floating point number.
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API.
IsInteger()
virtual bool FNumericProperty::IsInteger () const private virtual
Return true if this property is for a integral or enum type.
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API.
ReadEnumAsInt64()
int64 FNumericProperty::ReadEnumAsInt64 (FStructuredArchive::FSlot Slot, UStruct * DefaultsStruct, const FPropertyTag & Tag) static private
References UE_API.
SetFloatingPointPropertyValue()
virtual void FNumericProperty::SetFloatingPointPropertyValue (void * Data, double Value) const private virtual
Set the value of a floating point property type.
Parameters
Data - pointer to property data to set
Value - Value to set data to
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API, and Value.
SetIntPropertyValue() [1/2]
virtual void FNumericProperty::SetIntPropertyValue (void * Data, int64 Value) const private virtual
Set the value of a signed integral property type.
Parameters
Data - pointer to property data to set
Value - Value to set data to
References UE_API, and Value.
SetIntPropertyValue() [2/2]
virtual void FNumericProperty::SetIntPropertyValue (void * Data, uint64 Value) const private virtual
Set the value of an unsigned integral property type.
Parameters
Data - pointer to property data to set
Value - Value to set data to
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API, and Value.
SetNumericPropertyValueFromString()
virtual void FNumericProperty::SetNumericPropertyValueFromString (void * Data, TCHAR const * Value) const private virtual
Set the value of any numeric type from a string point.
Parameters
Data - pointer to property data to set
Value - Value (as a string) to set CAUTION: This routine does not do enum name conversion
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References UE_API, and Value.
SetNumericPropertyValueFromString_InContainer()
virtual void FNumericProperty::SetNumericPropertyValueFromString_InContainer (void * Container, TCHAR const * Value) const private virtual
Reimplemented in TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
References Container, UE_API, and Value.
Field Documentation
CanHoldDoubleValueInternal
virtual bool FNumericProperty::CanHoldDoubleValueInternal(double Value) const PURE_VIRTUAL(FNumericProperty private
Definition at line 1796 of file UnrealType.h.
Referenced by CanHoldValue().
CanHoldSignedValueInternal
virtual bool FNumericProperty::CanHoldSignedValueInternal(int64 Value) const PURE_VIRTUAL(FNumericProperty private
Definition at line 1797 of file UnrealType.h.
Referenced by CanHoldValue().
CanHoldUnsignedValueInternal
virtual bool FNumericProperty::CanHoldUnsignedValueInternal(uint64 Value) const PURE_VIRTUAL(FNumericProperty private
Definition at line 1798 of file UnrealType.h.
Referenced by CanHoldValue().
InName
const FName& FNumericProperty::InName private
Definition at line 1677 of file UnrealType.h.
Referenced by FByteProperty::FByteProperty().
InObjectFlags
const FName EObjectFlags FNumericProperty::InObjectFlags private
Definition at line 1677 of file UnrealType.h.
Referenced by FByteProperty::FByteProperty().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h