Unreal Engine 5.6 C++ API: IPlatformInputDeviceMapper Class Reference
IPlatformInputDeviceMapper Class Reference abstract
Base class to private a mapping of Platform Users (FPlatformUserID) to their associated available input devices (FInputDeviceID).
#include "GenericPlatformInputDeviceMapper.h"
Public Member Functions
APPLICATIONCORE_API IPlatformInputDeviceMapper ()
virtual APPLICATIONCORE_API ~IPlatformInputDeviceMapper ()
Virtual destructor.
virtual FInputDeviceId AllocateNewInputDeviceId ()=0
Returns the next available input device id.
virtual FPlatformUserId AllocateNewUserId ()=0
Allocates a new user id when a user becomes active, will return none if no more can be created.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnUserInputDeviceConnectionChange, EInputDeviceConnectionState, FPlatformUserId, FInputDeviceId)
Callback for handling an Input Device's connection state change.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnUserInputDevicePairingChange, FInputDeviceId, FPlatformUserId, FPlatformUserId)
Callback for handling an Input Device pairing change.
virtual APPLICATIONCORE_API int32 GetAllActiveUsers (TArray< FPlatformUserId > &OutUsers) const
Get all currently active platform ids, anyone who has a mapped input device.
virtual APPLICATIONCORE_API int32 GetAllConnectedInputDevices (TArray< FInputDeviceId > &OutInputDevices) const
Gather all currently connected input devices.
virtual APPLICATIONCORE_API int32 GetAllInputDevices (TArray< FInputDeviceId > &OutInputDevices) const
Get all mapped input devices on this platform regardless of their connection state.
virtual APPLICATIONCORE_API int32 GetAllInputDevicesForUser (const FPlatformUserId UserId, TArray< FInputDeviceId > &OutInputDevices) const
Populates the OutInputDevices array with any InputDeviceID's that are mapped to the given platform user.
virtual APPLICATIONCORE_API const EInputDeviceMappingPolicy GetCurrentDeviceMappingPolicy () const
virtual FInputDeviceId GetDefaultInputDevice () const =0
Returns the default device id used for things like keyboard/mouse input.
virtual APPLICATIONCORE_API FPlatformUserId GetFirstPlatformUserWithNoInputDevice () const
Finds the first FPlatformUserId which was already allocated with no input devices.
virtual APPLICATIONCORE_API EInputDeviceConnectionState GetInputDeviceConnectionState (const FInputDeviceId DeviceId) const
Gets the connection state of the given input device.
virtual APPLICATIONCORE_API int32 GetMaxPlatformUserCount () const
Returns the max allowed number of platform users this platform can have.
FOnUserInputDeviceConnectionChange & GetOnInputDeviceConnectionChange () const
FOnUserInputDevicePairingChange & GetOnInputDevicePairingChange () const
virtual APPLICATIONCORE_API FPlatformUserId GetPlatformUserForNewlyConnectedDevice (const int32 InUserId=-1)
Returns the platform user id that a newly connected device should be mapped to.
virtual FPlatformUserId GetPlatformUserForUserIndex (int32 LocalUserIndex)=0
virtual APPLICATIONCORE_API FInputDeviceId GetPrimaryInputDeviceForUser (FPlatformUserId UserId) const
Returns the primary input device used by a specific player, or INPUTDEVICEID_NONE if invalid.
virtual FPlatformUserId GetPrimaryPlatformUser () const =0
Returns the 'Primary' Platform user for this platform.
virtual APPLICATIONCORE_API FPlatformUserId GetUserForInputDevice (FInputDeviceId DeviceId) const
Returns the platform user attached to this input device, or PLATFORMUSERID_NONE if invalid.
virtual FPlatformUserId GetUserForUnpairedInputDevices () const =0
Returns the platform user id that is being used for unmapped input devices.
virtual int32 GetUserIndexForPlatformUser (FPlatformUserId UserId)=0
APPLICATIONCORE_API void HandleInputDevicePolicyChanged (const EInputDeviceMappingPolicy NewPolicy)
Remaps the currently connected input devices based on the new given policy.
virtual APPLICATIONCORE_API bool Internal_ChangeInputDeviceUserMapping (FInputDeviceId DeviceId, FPlatformUserId NewUserId, FPlatformUserId OldUserId)
Change the user mapping of the given input device from an old user to a new one.
virtual APPLICATIONCORE_API bool Internal_MapInputDeviceToUser (FInputDeviceId DeviceId, FPlatformUserId UserId, EInputDeviceConnectionState ConnectionState)
Maps the given Input Device to the given userID.
virtual APPLICATIONCORE_API bool Internal_SetInputDeviceConnectionState (FInputDeviceId DeviceId, EInputDeviceConnectionState NewState)
Set the connection state of a given Input Device to something new.
virtual APPLICATIONCORE_API bool IsInputDeviceMappedToUnpairedUser (const FInputDeviceId InputDevice) const
Returns true if the given input device is mapped to the unpaired platform user id.
virtual APPLICATIONCORE_API bool IsUnpairedUserId (const FPlatformUserId PlatformId) const
Returns true if the given Platform User Id is the user for unpaired input devices on this platform.
virtual bool RemapControllerIdToPlatformUserAndDevice (int32 ControllerId, FPlatformUserId &InOutUserId, FInputDeviceId &OutInputDeviceId)=0
Remap the legacy "int32 ControllerId" to the updated FPlatformUserId and FInputDeviceId.
virtual bool RemapUserAndDeviceToControllerId (FPlatformUserId UserId, int32 &OutControllerId, FInputDeviceId OptionalDeviceId=INPUTDEVICEID_NONE)=0
Remap a FPlatformUserId to a ControllerId that is needed by legacy code.
Static Public Member Functions
static APPLICATIONCORE_API IPlatformInputDeviceMapper & Get ()
Get the platform input device mapper.
Protected Member Functions
virtual APPLICATIONCORE_API void BindCoreDelegates ()
Binds to any core delegates that the platform may broadcast.
virtual bool IsUsingControllerIdAsUserId () const =0
If true, this device mapper is operating in a backward compatible mode where there is a 1:1 mapping between controller id and user id.
virtual void OnUserLoginChangedEvent (bool bLoggedIn, int32 UserId, int32 UserIndex)=0
Callback for when FCoreDelegates::OnUserLoginChangedEvent is broadcasted.
virtual bool ShouldBroadcastLegacyDelegates () const =0
If true, than this device mapper will broadcast the older CoreDelegates as well as the new delegates.
virtual APPLICATIONCORE_API bool ShouldCreateUniqueUserForEachDevice () const
If true, then when we remap the platform's raw int32 ControllerId to its FInputDeviceId and owning FPlatformUserId we should create a new platform user id if this controller id is not already mapped.
virtual APPLICATIONCORE_API void UnbindCoreDelegates ()
Unbind from any delegates that have been hooked into.
Protected Attributes
TArray< FPlatformUserId > AllocatedPlatformUserIds
Keeps track of any allocated platform user ID's by this device mapper.
FInputDeviceId LastInputDeviceId = INPUTDEVICEID_NONE
Highest used input device id.
FPlatformUserId LastPlatformUserId = PLATFORMUSERID_NONE
Highest used platform user id.
TMap< FInputDeviceId, FPlatformInputDeviceState > MappedInputDevices
A map of all input devices to their current state.
Static Protected Attributes
static APPLICATIONCORE_API FOnUserInputDeviceConnectionChange OnInputDeviceConnectionChange
Callback when input devices are disconnected/reconnected.
static APPLICATIONCORE_API FOnUserInputDevicePairingChange OnInputDevicePairingChange
Callback when an input device's owning platform user pairing changes.
Detailed Description
Base class to private a mapping of Platform Users (FPlatformUserID) to their associated available input devices (FInputDeviceID).
This will handle the allocation of the globally unique identifier of the FInputDeviceID, and allow overrides of how each platform maps input devices to their users. Some platforms may desire to have each new input device assigned to a different user, while others may want multiple input devices associated with a single user.
Note
Keep any function comments up to date with those in PlatformInputDeviceMapperLibrary.h!
Definition at line 27 of file GenericPlatformInputDeviceMapper.h.
Constructor & Destructor Documentation
IPlatformInputDeviceMapper()
APPLICATIONCORE_API IPlatformInputDeviceMapper::IPlatformInputDeviceMapper ()
Referenced by Get().
~IPlatformInputDeviceMapper()
virtual APPLICATIONCORE_API IPlatformInputDeviceMapper::~IPlatformInputDeviceMapper () virtual
Virtual destructor.
Member Function Documentation
AllocateNewInputDeviceId()
virtual FInputDeviceId IPlatformInputDeviceMapper::AllocateNewInputDeviceId () pure virtual
Returns the next available input device id.
This ID should be globally unique!
Implemented in FGenericPlatformInputDeviceMapper.
Referenced by TInputDeviceMap< TDeviceKeyType >::GetOrCreateDeviceId().
AllocateNewUserId()
virtual FPlatformUserId IPlatformInputDeviceMapper::AllocateNewUserId () pure virtual
Allocates a new user id when a user becomes active, will return none if no more can be created.
Implemented in FGenericPlatformInputDeviceMapper.
BindCoreDelegates()
virtual APPLICATIONCORE_API void IPlatformInputDeviceMapper::BindCoreDelegates () protected virtual
Binds to any core delegates that the platform may broadcast.
By default it is only the OnUserLoginChangedEvent delegate. Called during the constructor of this device mapper.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/2]
IPlatformInputDeviceMapper::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnUserInputDeviceConnectionChange , EInputDeviceConnectionState , FPlatformUserId , FInputDeviceId)
Callback for handling an Input Device's connection state change.
Parameters
NewConnectionState The new connection state of this device
FPlatformUserId The User ID whose input device has changed
FInputDeviceId The Input Device ID that has changed connection
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/2]
IPlatformInputDeviceMapper::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnUserInputDevicePairingChange , FInputDeviceId , FPlatformUserId , FPlatformUserId)
Callback for handling an Input Device pairing change.
Parameters
FInputDeviceId Input device ID
FPlatformUserId The NewUserPlatformId
FPlatformUserId The OldUserPlatformId
Get()
APPLICATIONCORE_API IPlatformInputDeviceMapper & IPlatformInputDeviceMapper::Get () static
Get the platform input device mapper.
References IPlatformInputDeviceMapper().
Referenced by FSlateDefaultInputMapping::GetInputDeviceIdForKeyboard(), FSlateDefaultInputMapping::GetInputDeviceIdForMouse(), TInputDeviceMap< TDeviceKeyType >::GetOrCreateDeviceId(), ISlateInputManager::GetUserIndexForInputDevice(), TInputDeviceMap< TDeviceKeyType >::MapDefaultInputDevice(), FGenericApplicationMessageHandler::OnMotionDetected(), FGenericApplicationMessageHandler::OnTouchEnded(), FGenericApplicationMessageHandler::OnTouchFirstMove(), FGenericApplicationMessageHandler::OnTouchForceChanged(), FGenericApplicationMessageHandler::OnTouchMoved(), and FGenericApplicationMessageHandler::OnTouchStarted().
GetAllActiveUsers()
virtual APPLICATIONCORE_API int32 IPlatformInputDeviceMapper::GetAllActiveUsers (TArray< FPlatformUserId > & OutUsers) const virtual
Get all currently active platform ids, anyone who has a mapped input device.
Parameters
OutUsers Array that will be populated with the platform users.
Returns
The number of active platform users
GetAllConnectedInputDevices()
virtual APPLICATIONCORE_API int32 IPlatformInputDeviceMapper::GetAllConnectedInputDevices (TArray< FInputDeviceId > & OutInputDevices) const virtual
Gather all currently connected input devices.
Parameters
OutInputDevices Array of input devices to populate
Returns
The number of connected input devices
GetAllInputDevices()
virtual APPLICATIONCORE_API int32 IPlatformInputDeviceMapper::GetAllInputDevices (TArray< FInputDeviceId > & OutInputDevices) const virtual
Get all mapped input devices on this platform regardless of their connection state.
Parameters
OutInputDevices Array of input devices to populate
Returns
The number of connected input devices
GetAllInputDevicesForUser()
virtual APPLICATIONCORE_API int32 IPlatformInputDeviceMapper::GetAllInputDevicesForUser (const FPlatformUserId UserId, TArray< FInputDeviceId > & OutInputDevices) const virtual
Populates the OutInputDevices array with any InputDeviceID's that are mapped to the given platform user.
Parameters
UserId The Platform User to gather the input devices of.
OutInputDevices Array of input device ID's that will be populated with the mapped devices.
Returns
The number of mapped devices, INDEX_NONE if the user was not found.
GetCurrentDeviceMappingPolicy()
virtual APPLICATIONCORE_API const EInputDeviceMappingPolicy IPlatformInputDeviceMapper::GetCurrentDeviceMappingPolicy () const virtual
GetDefaultInputDevice()
virtual FInputDeviceId IPlatformInputDeviceMapper::GetDefaultInputDevice () const pure virtual
Returns the default device id used for things like keyboard/mouse input.
Implemented in FGenericPlatformInputDeviceMapper.
Referenced by FSlateDefaultInputMapping::GetInputDeviceIdForKeyboard(), FSlateDefaultInputMapping::GetInputDeviceIdForMouse(), and TInputDeviceMap< TDeviceKeyType >::MapDefaultInputDevice().
GetFirstPlatformUserWithNoInputDevice()
virtual APPLICATIONCORE_API FPlatformUserId IPlatformInputDeviceMapper::GetFirstPlatformUserWithNoInputDevice () const virtual
Finds the first FPlatformUserId which was already allocated with no input devices.
Returns PLATFORMUSERID_NONE if every current platform user has a valid input device mapped to it.
Will not return the Unpaired platform user.
GetInputDeviceConnectionState()
virtual APPLICATIONCORE_API EInputDeviceConnectionState IPlatformInputDeviceMapper::GetInputDeviceConnectionState (const FInputDeviceId DeviceId) const virtual
Gets the connection state of the given input device.
Parameters
DeviceId The device to get the connection state of
Returns
The connection state of the given device. EInputDeviceConnectionState::Unknown if the device is not mapped
GetMaxPlatformUserCount()
virtual APPLICATIONCORE_API int32 IPlatformInputDeviceMapper::GetMaxPlatformUserCount () const virtual
Returns the max allowed number of platform users this platform can have.
By default, this will return the value specified in the input settings ini file
GetOnInputDeviceConnectionChange()
FOnUserInputDeviceConnectionChange & IPlatformInputDeviceMapper::GetOnInputDeviceConnectionChange () const inline
Definition at line 192 of file GenericPlatformInputDeviceMapper.h.
References OnInputDeviceConnectionChange.
GetOnInputDevicePairingChange()
FOnUserInputDevicePairingChange & IPlatformInputDeviceMapper::GetOnInputDevicePairingChange () const inline
Definition at line 193 of file GenericPlatformInputDeviceMapper.h.
References OnInputDevicePairingChange.
GetPlatformUserForNewlyConnectedDevice()
virtual APPLICATIONCORE_API FPlatformUserId IPlatformInputDeviceMapper::GetPlatformUserForNewlyConnectedDevice (const int32 InUserId = -1) virtual
Returns the platform user id that a newly connected device should be mapped to.
If "ShouldCreateUniqueUserForEachDevice" is true, then a new platform user id will be allocated for this device. Otherwise, this will return the primary platform user.
Parameters
InUserId An optional user index which can be passed in. If this is not -1, and IsUsingControllerIdAsUserId is true, then the platform user id for that user will be returned.
GetPlatformUserForUserIndex()
virtual FPlatformUserId IPlatformInputDeviceMapper::GetPlatformUserForUserIndex (int32 LocalUserIndex) pure virtual
Implemented in FGenericPlatformInputDeviceMapper.
GetPrimaryInputDeviceForUser()
virtual APPLICATIONCORE_API FInputDeviceId IPlatformInputDeviceMapper::GetPrimaryInputDeviceForUser (FPlatformUserId UserId) const virtual
Returns the primary input device used by a specific player, or INPUTDEVICEID_NONE if invalid.
GetPrimaryPlatformUser()
virtual FPlatformUserId IPlatformInputDeviceMapper::GetPrimaryPlatformUser () const pure virtual
Returns the 'Primary' Platform user for this platform.
This typically has an internal ID of '0' and is used as the default platform user to map devices such as the keyboard and mouse that don't get assigned unique ID's from their owning platform code.
Implemented in FGenericPlatformInputDeviceMapper.
GetUserForInputDevice()
virtual APPLICATIONCORE_API FPlatformUserId IPlatformInputDeviceMapper::GetUserForInputDevice (FInputDeviceId DeviceId) const virtual
Returns the platform user attached to this input device, or PLATFORMUSERID_NONE if invalid.
GetUserForUnpairedInputDevices()
virtual FPlatformUserId IPlatformInputDeviceMapper::GetUserForUnpairedInputDevices () const pure virtual
Returns the platform user id that is being used for unmapped input devices.
Will be PLATFORMUSERID_NONE if platform does not support this (this is the default behavior)
Implemented in FGenericPlatformInputDeviceMapper.
GetUserIndexForPlatformUser()
virtual int32 IPlatformInputDeviceMapper::GetUserIndexForPlatformUser (FPlatformUserId UserId) pure virtual
Implemented in FGenericPlatformInputDeviceMapper.
HandleInputDevicePolicyChanged()
APPLICATIONCORE_API void IPlatformInputDeviceMapper::HandleInputDevicePolicyChanged (const EInputDeviceMappingPolicy NewPolicy)
Remaps the currently connected input devices based on the new given policy.
This property can only be changed at editor time and should not be used at runtime.
Internal_ChangeInputDeviceUserMapping()
virtual APPLICATIONCORE_API bool IPlatformInputDeviceMapper::Internal_ChangeInputDeviceUserMapping (FInputDeviceId DeviceId, FPlatformUserId NewUserId, FPlatformUserId OldUserId) virtual
Change the user mapping of the given input device from an old user to a new one.
This will broadcast the OnInputDevicePairingChange delegate. Use this when you know that an input device is already mapped, but it has changed platform users This should be called by the platform's implementation.
Parameters
DeviceId The input device to change the owner on
NewUserId The new platform user that this input device should be mapped to
OldUserId The old platform user that this input device is currently mapped to
Returns
True if the device was successfully remapped
Internal_MapInputDeviceToUser()
virtual APPLICATIONCORE_API bool IPlatformInputDeviceMapper::Internal_MapInputDeviceToUser (FInputDeviceId DeviceId, FPlatformUserId UserId, EInputDeviceConnectionState ConnectionState) virtual
Maps the given Input Device to the given userID.
This will broadcast the OnInputDeviceConnectionChange delegate. This should be called by the platform's implementation.
Parameters
DeviceId The device id to map
UserId The Platform User that owns the given device
ConnectionState The connection state of the device
Returns
True if the input device was successfully mapped
Internal_SetInputDeviceConnectionState()
virtual APPLICATIONCORE_API bool IPlatformInputDeviceMapper::Internal_SetInputDeviceConnectionState (FInputDeviceId DeviceId, EInputDeviceConnectionState NewState) virtual
Set the connection state of a given Input Device to something new.
This will broadcast the OnInputDeviceConnectionChange delegate. This should be called by the platform's implementation.
Parameters
DeviceId The device id that has had a connection change
NewState The new connection state of the given device
Returns
True if the connection state was set successfully
IsInputDeviceMappedToUnpairedUser()
virtual APPLICATIONCORE_API bool IPlatformInputDeviceMapper::IsInputDeviceMappedToUnpairedUser (const FInputDeviceId InputDevice) const virtual
Returns true if the given input device is mapped to the unpaired platform user id.
IsUnpairedUserId()
virtual APPLICATIONCORE_API bool IPlatformInputDeviceMapper::IsUnpairedUserId (const FPlatformUserId PlatformId) const virtual
Returns true if the given Platform User Id is the user for unpaired input devices on this platform.
IsUsingControllerIdAsUserId()
virtual bool IPlatformInputDeviceMapper::IsUsingControllerIdAsUserId () const protected pure virtual
If true, this device mapper is operating in a backward compatible mode where there is a 1:1 mapping between controller id and user id.
Implemented in FGenericPlatformInputDeviceMapper.
OnUserLoginChangedEvent()
virtual void IPlatformInputDeviceMapper::OnUserLoginChangedEvent (bool bLoggedIn, int32 UserId, int32 UserIndex) protected pure virtual
Callback for when FCoreDelegates::OnUserLoginChangedEvent is broadcasted.
Implemented in FGenericPlatformInputDeviceMapper.
RemapControllerIdToPlatformUserAndDevice()
virtual bool IPlatformInputDeviceMapper::RemapControllerIdToPlatformUserAndDevice (int32 ControllerId, FPlatformUserId & InOutUserId, FInputDeviceId & OutInputDeviceId) pure virtual
Remap the legacy "int32 ControllerId" to the updated FPlatformUserId and FInputDeviceId.
Use this function to add compatibility to platforms that may not have implemented this device mapper yet.
This is useful for functions such as FGenericApplicationMessageHandler::OnControllerAnalog that used to use the "int32 ControllerId" as a parameter so that you can call the new FGenericApplicationMessageHandler that take in a PlatformUserId and an InputDeviceId.
Parameters
ControllerId The old plain "int32" that represented gamepad id or user index depending on the context.
InOutUserId If the old function provides a PlatformId then pass it here, otherwise pass PLATFORMUSERID_NONE.
OutInputDeviceId The best guess for an InputDeviceId based on the legacy int32 ControllerId. This may be INPUTDEVICEID_NONE.
Returns
True if this maps to a real user
Implemented in FGenericPlatformInputDeviceMapper.
Referenced by FGenericApplicationMessageHandler::OnMotionDetected(), FGenericApplicationMessageHandler::OnTouchEnded(), FGenericApplicationMessageHandler::OnTouchFirstMove(), FGenericApplicationMessageHandler::OnTouchForceChanged(), FGenericApplicationMessageHandler::OnTouchMoved(), and FGenericApplicationMessageHandler::OnTouchStarted().
RemapUserAndDeviceToControllerId()
virtual bool IPlatformInputDeviceMapper::RemapUserAndDeviceToControllerId (FPlatformUserId UserId, int32 & OutControllerId, FInputDeviceId OptionalDeviceId = INPUTDEVICEID_NONE) pure virtual
Remap a FPlatformUserId to a ControllerId that is needed by legacy code.
Use this function to add compatibility to platforms that may not have implemented this device mapper yet.
Parameters
UserId The platform user that should be converted
OutControllerId Set to the old plain "int32" that represented gamepad id or user index depending on the context.
OptionalDeviceId Set this to a specific device id if known
Returns
True if this maps to a real user
Implemented in FGenericPlatformInputDeviceMapper.
References INPUTDEVICEID_NONE.
ShouldBroadcastLegacyDelegates()
virtual bool IPlatformInputDeviceMapper::ShouldBroadcastLegacyDelegates () const protected pure virtual
If true, than this device mapper will broadcast the older CoreDelegates as well as the new delegates.
Set this to true if your platform needs calls from OnControllerConnectionChange or OnControllerPairingChange
Implemented in FGenericPlatformInputDeviceMapper.
ShouldCreateUniqueUserForEachDevice()
virtual APPLICATIONCORE_API bool IPlatformInputDeviceMapper::ShouldCreateUniqueUserForEachDevice () const protected virtual
If true, then when we remap the platform's raw int32 ControllerId to its FInputDeviceId and owning FPlatformUserId we should create a new platform user id if this controller id is not already mapped.
UnbindCoreDelegates()
virtual APPLICATIONCORE_API void IPlatformInputDeviceMapper::UnbindCoreDelegates () protected virtual
Unbind from any delegates that have been hooked into.
Called during the destructor of this device mapper.
Field Documentation
AllocatedPlatformUserIds
TArray<FPlatformUserId> IPlatformInputDeviceMapper::AllocatedPlatformUserIds protected
Keeps track of any allocated platform user ID's by this device mapper.
Definition at line 312 of file GenericPlatformInputDeviceMapper.h.
LastInputDeviceId
FInputDeviceId IPlatformInputDeviceMapper::LastInputDeviceId = INPUTDEVICEID_NONE protected
Highest used input device id.
Incremented in AllocateNewInputDeviceId and Internal_MapInputDeviceToUser by default.
Definition at line 309 of file GenericPlatformInputDeviceMapper.h.
LastPlatformUserId
FPlatformUserId IPlatformInputDeviceMapper::LastPlatformUserId = PLATFORMUSERID_NONE protected
Highest used platform user id.
Incremented in AllocateNewUserId and Internal_MapInputDeviceToUser by default.
Definition at line 306 of file GenericPlatformInputDeviceMapper.h.
MappedInputDevices
TMap<FInputDeviceId, FPlatformInputDeviceState> IPlatformInputDeviceMapper::MappedInputDevices protected
A map of all input devices to their current state.
Definition at line 303 of file GenericPlatformInputDeviceMapper.h.
OnInputDeviceConnectionChange
APPLICATIONCORE_API FOnUserInputDeviceConnectionChange IPlatformInputDeviceMapper::OnInputDeviceConnectionChange static protected
Callback when input devices are disconnected/reconnected.
Definition at line 297 of file GenericPlatformInputDeviceMapper.h.
Referenced by GetOnInputDeviceConnectionChange().
OnInputDevicePairingChange
APPLICATIONCORE_API FOnUserInputDevicePairingChange IPlatformInputDeviceMapper::OnInputDevicePairingChange static protected
Callback when an input device's owning platform user pairing changes.
Definition at line 300 of file GenericPlatformInputDeviceMapper.h.
Referenced by GetOnInputDevicePairingChange().
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/GenericPlatform/GenericPlatformInputDeviceMapper.h