Unreal Engine 5.6 C++ API: TActorDescContainerInstanceCollection< ActorDescContPtrType > Class Template Reference
TActorDescContainerInstanceCollection< ActorDescContPtrType > Class Template Reference
#include "ActorDescContainerInstanceCollection.h"
Data Structures
class TBaseIterator
class TConstIterator
class TIterator
Public Member Functions
TActorDescContainerInstanceCollection ()=default
template<class U>
TActorDescContainerInstanceCollection (const TArray< U > &ActorDescContainerInstances)
template<class U>
TActorDescContainerInstanceCollection (std::initializer_list< U > ActorDescContainerInstanceArray)
virtual ~TActorDescContainerInstanceCollection ()
void AddContainer (ActorDescContPtrType Container)
template<class U>
void Append (const TActorDescContainerInstanceCollection< U > &OtherCollection)
bool Contains (const FName &ContainerPackageName) const
DECLARE_EVENT_OneParam (UWorldPartition, FActorDescInstanceAddedEvent, FWorldPartitionActorDescInstance *)
DECLARE_EVENT_OneParam (UWorldPartition, FActorDescInstanceRemovedEvent, FWorldPartitionActorDescInstance *)
DECLARE_EVENT_OneParam (UWorldPartition, FActorReplacedEvent, FWorldPartitionActorDescInstance *)
void Empty ()
ActorDescContPtrType FindContainer (const FName &ContainerPackageName) const
ActorDescContPtrType FindHandlingContainerInstance (const AActor *Actor) const
void ForEachActorDescContainerInstance (TFunctionRef< void(ActorDescContPtrType)> Func, bool bRecursive=false)
void ForEachActorDescContainerInstance (TFunctionRef< void(ActorDescContPtrType)> Func, bool bRecursive=false) const
void ForEachActorDescContainerInstanceBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func, bool bRecursive=false)
void ForEachActorDescContainerInstanceBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func, bool bRecursive=false) const
uint32 GetActorDescContainerCount () const
ActorDescContPtrType GetActorDescContainerInstance (const FGuid &ActorGuid) const
FWorldPartitionActorDescInstance * GetActorDescInstance (const FGuid &Guid)
const FWorldPartitionActorDescInstance * GetActorDescInstance (const FGuid &Guid) const
const FWorldPartitionActorDescInstance * GetActorDescInstanceByName (FName ActorName) const
const FWorldPartitionActorDescInstance * GetActorDescInstanceByPath (const FSoftObjectPath &ActorPath) const
const FWorldPartitionActorDescInstance * GetActorDescInstanceByPath (const FString &ActorPath) const
bool IsEmpty () const
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
void LoadAllActors (TArray< FWorldPartitionReference > &OutReferences)
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
void OnPackageDeleted (UPackage *Package)
template<typename Dummy = void, typename = typename TEnableIf<!TIsConst<TRemovePointer<ActorDescContPtrType>>::Value, Dummy>::Type>
bool RemoveActor (const FGuid &ActorGuid)
bool RemoveContainer (ActorDescContPtrType Container)
Data Fields
FActorDescInstanceAddedEvent OnActorDescInstanceAddedEvent
FActorDescInstanceRemovedEvent OnActorDescInstanceRemovedEvent
FActorReplacedEvent OnActorReplacedEvent
Protected Member Functions
virtual void OnCollectionChanged ()
virtual bool ShouldRegisterDelegates () const
Protected Attributes
TArray< ActorDescContPtrType > ActorDescContainerInstanceCollection
Private Member Functions
void OnActorDescInstanceAdded (FWorldPartitionActorDescInstance *ActorDescInstance)
void OnActorDescInstanceRemoved (FWorldPartitionActorDescInstance *ActorDescInstance)
void OnActorReplaced (FWorldPartitionActorDescInstance *ActorDescInstance)
void RegisterDelegates (ActorDescContPtrType Container)
void UnregisterDelegates (ActorDescContPtrType Container)
Friends
template<class>
class TActorDescContainerInstanceCollection
Detailed Description
template<class ActorDescContPtrType>
class TActorDescContainerInstanceCollection< ActorDescContPtrType >
Definition at line 13 of file ActorDescContainerInstanceCollection.h.
Constructor & Destructor Documentation
TActorDescContainerInstanceCollection() [1/3]
template<class ActorDescContPtrType> TActorDescContainerInstanceCollection< ActorDescContPtrType >::TActorDescContainerInstanceCollection () default
TActorDescContainerInstanceCollection() [2/3]
template<class ActorDescContPtrType> template<class U> TActorDescContainerInstanceCollection< ActorDescContPtrType >::TActorDescContainerInstanceCollection (std::initializer_list< U > ActorDescContainerInstanceArray)
Definition at line 210 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection, ForEachActorDescContainerInstance(), and RegisterDelegates().
TActorDescContainerInstanceCollection() [3/3]
template<class ActorDescContPtrType> template<class U> TActorDescContainerInstanceCollection< ActorDescContPtrType >::TActorDescContainerInstanceCollection (const TArray< U > & ActorDescContainerInstances)
Definition at line 221 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection, ForEachActorDescContainerInstance(), and RegisterDelegates().
~TActorDescContainerInstanceCollection()
template<class ActorDescContPtrType> TActorDescContainerInstanceCollection< ActorDescContPtrType >::~TActorDescContainerInstanceCollection () virtual
Definition at line 231 of file ActorDescContainerInstanceCollection.h.
References Empty.
Member Function Documentation
AddContainer()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::AddContainer (ActorDescContPtrType Container)
Definition at line 237 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection, Container, OnCollectionChanged(), and RegisterDelegates().
Append()
template<class ActorDescContPtrType> template<class U> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::Append (const TActorDescContainerInstanceCollection< U > & OtherCollection)
Definition at line 258 of file ActorDescContainerInstanceCollection.h.
References TActorDescContainerInstanceCollection, ActorDescContainerInstanceCollection, IsEmpty(), TArray< InElementType, InAllocatorType >::Num(), OnCollectionChanged(), and RegisterDelegates().
Contains()
template<class ActorDescContPtrType> bool TActorDescContainerInstanceCollection< ActorDescContPtrType >::Contains (const FName & ContainerPackageName) const
Definition at line 276 of file ActorDescContainerInstanceCollection.h.
References FindContainer().
DECLARE_EVENT_OneParam() [1/3]
template<class ActorDescContPtrType> TActorDescContainerInstanceCollection< ActorDescContPtrType >::DECLARE_EVENT_OneParam (UWorldPartition , FActorDescInstanceAddedEvent , FWorldPartitionActorDescInstance *)
DECLARE_EVENT_OneParam() [2/3]
template<class ActorDescContPtrType> TActorDescContainerInstanceCollection< ActorDescContPtrType >::DECLARE_EVENT_OneParam (UWorldPartition , FActorDescInstanceRemovedEvent , FWorldPartitionActorDescInstance *)
DECLARE_EVENT_OneParam() [3/3]
template<class ActorDescContPtrType> TActorDescContainerInstanceCollection< ActorDescContPtrType >::DECLARE_EVENT_OneParam (UWorldPartition , FActorReplacedEvent , FWorldPartitionActorDescInstance *)
Empty()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::Empty ()
Definition at line 289 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection, ForEachActorDescContainerInstance(), OnCollectionChanged(), and UnregisterDelegates().
FindContainer()
template<class ActorDescContPtrType> ActorDescContPtrType TActorDescContainerInstanceCollection< ActorDescContPtrType >::FindContainer (const FName & ContainerPackageName) const
Definition at line 282 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection.
Referenced by Contains().
FindHandlingContainerInstance()
template<class ActorDescContPtrType> ActorDescContPtrType TActorDescContainerInstanceCollection< ActorDescContPtrType >::FindHandlingContainerInstance (const AActor * Actor) const
Definition at line 397 of file ActorDescContainerInstanceCollection.h.
References Actor, ForEachActorDescContainerInstanceBreakable(), and GetActorDescContainerInstance().
ForEachActorDescContainerInstance() [1/2]
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::ForEachActorDescContainerInstance (TFunctionRef< void(ActorDescContPtrType)> Func, bool bRecursive = false)
Definition at line 503 of file ActorDescContainerInstanceCollection.h.
References TActorDescContainerInstanceCollection, and ForEachActorDescContainerInstance().
Referenced by TActorDescContainerInstanceCollection(), TActorDescContainerInstanceCollection(), Empty(), ForEachActorDescContainerInstance(), LoadAllActors(), and OnPackageDeleted().
ForEachActorDescContainerInstance() [2/2]
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::ForEachActorDescContainerInstance (TFunctionRef< void(ActorDescContPtrType)> Func, bool bRecursive = false) const
Definition at line 494 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable().
ForEachActorDescContainerInstanceBreakable() [1/2]
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::ForEachActorDescContainerInstanceBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func, bool bRecursive = false)
Definition at line 488 of file ActorDescContainerInstanceCollection.h.
References TActorDescContainerInstanceCollection, and ForEachActorDescContainerInstanceBreakable().
Referenced by FindHandlingContainerInstance(), ForEachActorDescContainerInstance(), ForEachActorDescContainerInstanceBreakable(), GetActorDescContainerInstance(), GetActorDescInstance(), GetActorDescInstanceByName(), GetActorDescInstanceByPath(), GetActorDescInstanceByPath(), and RemoveActor().
ForEachActorDescContainerInstanceBreakable() [2/2]
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::ForEachActorDescContainerInstanceBreakable (TFunctionRef< bool(ActorDescContPtrType)> Func, bool bRecursive = false) const
Definition at line 455 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection, bool, and Guid.
GetActorDescContainerCount()
template<class ActorDescContPtrType> uint32 TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescContainerCount () const inline
Definition at line 39 of file ActorDescContainerInstanceCollection.h.
GetActorDescContainerInstance()
template<class ActorDescContPtrType> ActorDescContPtrType TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescContainerInstance (const FGuid & ActorGuid) const
Definition at line 381 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable().
Referenced by FindHandlingContainerInstance(), and FWorldPartitionImplBase::GetActorDescContainerInstance().
GetActorDescInstance() [1/2]
template<class ActorDescContPtrType> FWorldPartitionActorDescInstance * TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescInstance (const FGuid & Guid)
Definition at line 336 of file ActorDescContainerInstanceCollection.h.
References TActorDescContainerInstanceCollection, and Guid.
GetActorDescInstance() [2/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDescInstance * TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescInstance (const FGuid & Guid) const
Definition at line 323 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable(), and Guid.
GetActorDescInstanceByName()
template<class ActorDescContPtrType> const FWorldPartitionActorDescInstance * TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescInstanceByName (FName ActorName) const
Definition at line 368 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable().
GetActorDescInstanceByPath() [1/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDescInstance * TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescInstanceByPath (const FSoftObjectPath & ActorPath) const
Definition at line 355 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable().
GetActorDescInstanceByPath() [2/2]
template<class ActorDescContPtrType> const FWorldPartitionActorDescInstance * TActorDescContainerInstanceCollection< ActorDescContPtrType >::GetActorDescInstanceByPath (const FString & ActorPath) const
Definition at line 342 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable().
IsEmpty()
template<class ActorDescContPtrType> bool TActorDescContainerInstanceCollection< ActorDescContPtrType >::IsEmpty () const inline
Definition at line 38 of file ActorDescContainerInstanceCollection.h.
Referenced by Append().
LoadAllActors()
template<class ActorDescContPtrType> template<typename, typename> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::LoadAllActors (TArray< FWorldPartitionReference > & OutReferences)
Definition at line 445 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstance().
OnActorDescInstanceAdded()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnActorDescInstanceAdded (FWorldPartitionActorDescInstance * ActorDescInstance) private
Definition at line 509 of file ActorDescContainerInstanceCollection.h.
References OnActorDescInstanceAddedEvent.
Referenced by RegisterDelegates().
OnActorDescInstanceRemoved()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnActorDescInstanceRemoved (FWorldPartitionActorDescInstance * ActorDescInstance) private
Definition at line 515 of file ActorDescContainerInstanceCollection.h.
References OnActorDescInstanceRemovedEvent.
Referenced by RegisterDelegates().
OnActorReplaced()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnActorReplaced (FWorldPartitionActorDescInstance * ActorDescInstance) private
Definition at line 521 of file ActorDescContainerInstanceCollection.h.
References OnActorReplacedEvent.
Referenced by RegisterDelegates().
OnCollectionChanged()
template<class ActorDescContPtrType> virtual void TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnCollectionChanged () inline protected virtual
Reimplemented in FStreamingGenerationContainerInstanceCollection.
Definition at line 76 of file ActorDescContainerInstanceCollection.h.
Referenced by AddContainer(), Append(), Empty(), and RemoveContainer().
OnPackageDeleted()
template<class ActorDescContPtrType> template<typename, typename> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnPackageDeleted (UPackage * Package)
Definition at line 435 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstance(), and Package.
RegisterDelegates()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::RegisterDelegates (ActorDescContPtrType Container) private
Definition at line 301 of file ActorDescContainerInstanceCollection.h.
References ConstCast(), Container, OnActorDescInstanceAdded(), OnActorDescInstanceRemoved(), OnActorReplaced(), and ShouldRegisterDelegates().
Referenced by TActorDescContainerInstanceCollection(), TActorDescContainerInstanceCollection(), AddContainer(), and Append().
RemoveActor()
template<class ActorDescContPtrType> template<typename, typename> bool TActorDescContainerInstanceCollection< ActorDescContPtrType >::RemoveActor (const FGuid & ActorGuid)
Definition at line 421 of file ActorDescContainerInstanceCollection.h.
References ForEachActorDescContainerInstanceBreakable().
RemoveContainer()
template<class ActorDescContPtrType> bool TActorDescContainerInstanceCollection< ActorDescContPtrType >::RemoveContainer (ActorDescContPtrType Container)
Definition at line 245 of file ActorDescContainerInstanceCollection.h.
References ActorDescContainerInstanceCollection, Container, OnCollectionChanged(), and UnregisterDelegates().
ShouldRegisterDelegates()
template<class ActorDescContPtrType> virtual bool TActorDescContainerInstanceCollection< ActorDescContPtrType >::ShouldRegisterDelegates () const inline protected virtual
Reimplemented in FStreamingGenerationContainerInstanceCollection.
Definition at line 77 of file ActorDescContainerInstanceCollection.h.
Referenced by RegisterDelegates(), and UnregisterDelegates().
UnregisterDelegates()
template<class ActorDescContPtrType> void TActorDescContainerInstanceCollection< ActorDescContPtrType >::UnregisterDelegates (ActorDescContPtrType Container) private
Definition at line 312 of file ActorDescContainerInstanceCollection.h.
References ConstCast(), Container, and ShouldRegisterDelegates().
Referenced by Empty(), and RemoveContainer().
Friends And Related Symbol Documentation
TActorDescContainerInstanceCollection
template<class ActorDescContPtrType> template<class> friend class TActorDescContainerInstanceCollection friend
Definition at line 17 of file ActorDescContainerInstanceCollection.h.
Referenced by Append(), ForEachActorDescContainerInstance(), ForEachActorDescContainerInstanceBreakable(), and GetActorDescInstance().
Field Documentation
ActorDescContainerInstanceCollection
template<class ActorDescContPtrType> TArray<ActorDescContPtrType> TActorDescContainerInstanceCollection< ActorDescContPtrType >::ActorDescContainerInstanceCollection protected
Definition at line 79 of file ActorDescContainerInstanceCollection.h.
Referenced by TActorDescContainerInstanceCollection(), TActorDescContainerInstanceCollection(), TActorDescContainerInstanceCollection< ActorDescContPtrType >::TBaseIterator< false, ActorType >::TBaseIterator(), AddContainer(), Append(), Empty(), FindContainer(), ForEachActorDescContainerInstanceBreakable(), and RemoveContainer().
OnActorDescInstanceAddedEvent
template<class ActorDescContPtrType> FActorDescInstanceAddedEvent TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnActorDescInstanceAddedEvent
Definition at line 61 of file ActorDescContainerInstanceCollection.h.
Referenced by OnActorDescInstanceAdded().
OnActorDescInstanceRemovedEvent
template<class ActorDescContPtrType> FActorDescInstanceRemovedEvent TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnActorDescInstanceRemovedEvent
Definition at line 64 of file ActorDescContainerInstanceCollection.h.
Referenced by OnActorDescInstanceRemoved().
OnActorReplacedEvent
template<class ActorDescContPtrType> FActorReplacedEvent TActorDescContainerInstanceCollection< ActorDescContPtrType >::OnActorReplacedEvent
Definition at line 67 of file ActorDescContainerInstanceCollection.h.
Referenced by OnActorReplaced().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/ActorDescContainerInstanceCollection.h