Unreal Engine 5.6 C++ API: HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T > Class Template Reference
HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T > Class Template Reference
#include "SpmcAnalysisResultQueue.h"
Data Structures
struct FEntry
class FReadCursor
class FScopedItemConsumeRef
class FScopedItemPeekRef
class FScopedItemWriteRef
Public Types
using ItemType = T
Public Member Functions
FSpmcAnalysisResultQueue ()
FSpmcAnalysisResultQueue (int32 InitialItemCount)
void DecrementIndex (int32 &Index) const
SIZE_T GetAllocatedSize () const
const FEntry * GetEntry (int32 Index) const
int32 GetLastWriteIndex () const
FScopedItemWriteRef GetNextAtomicWriteSlot ()
int32 GetNextWriteIndex () const
void IncrementIndex (int32 &Index, int32 NumberAhead=1) const
int32 NumItems () const
const FEntry & operator[] (int32 Index)
void SetNumItems (int32 NumItems)
Private Attributes
TArray< FEntry > Items
int32 NextItemSerialNumber { 0 }
int32 NextWritePos { 0 }
Detailed Description
template<typename T>
class HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >
Definition at line 12 of file SpmcAnalysisResultQueue.h.
Member Typedef Documentation
ItemType
template<typename T> using HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::ItemType = T
Definition at line 23 of file SpmcAnalysisResultQueue.h.
Constructor & Destructor Documentation
FSpmcAnalysisResultQueue() [1/2]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FSpmcAnalysisResultQueue () inline
Definition at line 346 of file SpmcAnalysisResultQueue.h.
Referenced by HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::FReadCursor(), and HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemWriteRef::FScopedItemWriteRef().
FSpmcAnalysisResultQueue() [2/2]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FSpmcAnalysisResultQueue (int32 InitialItemCount) inline
Definition at line 348 of file SpmcAnalysisResultQueue.h.
Member Function Documentation
DecrementIndex()
template<typename T> void HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::DecrementIndex (int32 & Index) const inline
Definition at line 395 of file SpmcAnalysisResultQueue.h.
GetAllocatedSize()
template<typename T> SIZE_T HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::GetAllocatedSize () const inline
Definition at line 376 of file SpmcAnalysisResultQueue.h.
GetEntry()
template<typename T> const FEntry * HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::GetEntry (int32 Index) const inline
Definition at line 370 of file SpmcAnalysisResultQueue.h.
GetLastWriteIndex()
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::GetLastWriteIndex () const inline
Definition at line 360 of file SpmcAnalysisResultQueue.h.
GetNextAtomicWriteSlot()
template<typename T> FScopedItemWriteRef HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::GetNextAtomicWriteSlot () inline
Definition at line 381 of file SpmcAnalysisResultQueue.h.
GetNextWriteIndex()
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::GetNextWriteIndex () const inline
Definition at line 359 of file SpmcAnalysisResultQueue.h.
Referenced by HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::FReadCursor().
IncrementIndex()
template<typename T> void HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::IncrementIndex (int32 & Index, int32 NumberAhead = 1) const inline
Definition at line 386 of file SpmcAnalysisResultQueue.h.
Referenced by HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef().
NumItems()
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::NumItems () const inline
Definition at line 357 of file SpmcAnalysisResultQueue.h.
operator[]()
template<typename T> const FEntry & HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::operator[] (int32 Index) inline
Definition at line 404 of file SpmcAnalysisResultQueue.h.
SetNumItems()
template<typename T> void HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::SetNumItems (int32 NumItems) inline
Definition at line 353 of file SpmcAnalysisResultQueue.h.
Field Documentation
Items
template<typename T> TArray<FEntry> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::Items private
Definition at line 413 of file SpmcAnalysisResultQueue.h.
NextItemSerialNumber
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::NextItemSerialNumber { 0 } private
Definition at line 411 of file SpmcAnalysisResultQueue.h.
NextWritePos
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::NextWritePos { 0 } private
Definition at line 412 of file SpmcAnalysisResultQueue.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixMetasound/Public/HarmonixMetasound/Analysis/SpmcAnalysisResultQueue.h