Unreal Engine 5.6 C++ API: FGlobalDynamicIndexBuffer Class Reference
FGlobalDynamicIndexBuffer Class Reference
A system for dynamically allocating GPU memory for indices.
#include "GlobalRenderResources.h"
Public Types
using FAllocation = FGlobalDynamicIndexBufferAllocation
using FAllocationEx = FGlobalDynamicIndexBufferAllocationEx
Public Member Functions
FGlobalDynamicIndexBuffer ()=default
FGlobalDynamicIndexBuffer (FRHICommandListBase &InRHICmdList)
~FGlobalDynamicIndexBuffer ()
template<typename IndexType>
FORCEINLINE FAllocationEx Allocate (uint32 NumIndices)
Helper function to allocate.
RENDERCORE_API FAllocation Allocate (uint32 NumIndices, uint32 IndexStride)
Allocates space in the global index buffer.
RENDERCORE_API void Commit ()
Commits allocated memory to the GPU.
void Init (FRHICommandListBase &InRHICmdList)
Private Attributes
TArray< FDynamicIndexBuffer * > IndexBuffers16
TArray< FDynamicIndexBuffer * > IndexBuffers32
FRHICommandListBase * RHICmdList = nullptr
Detailed Description
A system for dynamically allocating GPU memory for indices.
Definition at line 279 of file GlobalRenderResources.h.
Member Typedef Documentation
FAllocation
using FGlobalDynamicIndexBuffer::FAllocation = FGlobalDynamicIndexBufferAllocation
Definition at line 282 of file GlobalRenderResources.h.
FAllocationEx
using FGlobalDynamicIndexBuffer::FAllocationEx = FGlobalDynamicIndexBufferAllocationEx
Definition at line 283 of file GlobalRenderResources.h.
Constructor & Destructor Documentation
FGlobalDynamicIndexBuffer() [1/2]
FGlobalDynamicIndexBuffer::FGlobalDynamicIndexBuffer () default
FGlobalDynamicIndexBuffer() [2/2]
FGlobalDynamicIndexBuffer::FGlobalDynamicIndexBuffer (FRHICommandListBase & InRHICmdList) inline
Definition at line 287 of file GlobalRenderResources.h.
References RHICmdList.
~FGlobalDynamicIndexBuffer()
FGlobalDynamicIndexBuffer::~FGlobalDynamicIndexBuffer () inline
Definition at line 291 of file GlobalRenderResources.h.
References Commit().
Member Function Documentation
Allocate() [1/2]
template<typename IndexType> FORCEINLINE FAllocationEx FGlobalDynamicIndexBuffer::Allocate (uint32 NumIndices) inline
Helper function to allocate.
Parameters
NumIndices - The number of indices to allocate.
Returns
an FAllocation with information regarding the allocated memory.
Definition at line 316 of file GlobalRenderResources.h.
References Allocate(), and FORCEINLINE.
Allocate() [2/2]
RENDERCORE_API FAllocation FGlobalDynamicIndexBuffer::Allocate (uint32 NumIndices, uint32 IndexStride)
Allocates space in the global index buffer.
Parameters
NumIndices - The number of indices to allocate.
IndexStride - The size of an index (2 or 4 bytes).
Returns
An FAllocation with information regarding the allocated memory.
Referenced by Allocate().
Commit()
RENDERCORE_API void FGlobalDynamicIndexBuffer::Commit ()
Commits allocated memory to the GPU.
WARNING: Once this buffer has been committed to the GPU, allocations remain valid only until the next call to Allocate!
Referenced by ~FGlobalDynamicIndexBuffer().
Init()
void FGlobalDynamicIndexBuffer::Init (FRHICommandListBase & InRHICmdList) inline
Definition at line 296 of file GlobalRenderResources.h.
References check, IndexBuffers16, IndexBuffers32, and RHICmdList.
Field Documentation
IndexBuffers16
TArray<FDynamicIndexBuffer*> FGlobalDynamicIndexBuffer::IndexBuffers16 private
Definition at line 330 of file GlobalRenderResources.h.
Referenced by Init().
IndexBuffers32
TArray<FDynamicIndexBuffer*> FGlobalDynamicIndexBuffer::IndexBuffers32 private
Definition at line 331 of file GlobalRenderResources.h.
Referenced by Init().
RHICmdList
FRHICommandListBase* FGlobalDynamicIndexBuffer::RHICmdList = nullptr private
Definition at line 329 of file GlobalRenderResources.h.
Referenced by FGlobalDynamicIndexBuffer(), and Init().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/GlobalRenderResources.h