Unreal Engine 5.6 C++ API: FObjectPreSaveContext Class Reference
FObjectPreSaveContext Class Reference
Interface used by PreSave to access the save parameters.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectPreSaveContext (const FObjectPreSaveContext &Other)
FObjectPreSaveContext (FObjectSaveContextData &InData)
UE::Cook::ECookingDLC GetCookingDLC () const
UE::Cook::ECookType GetCookType () const
EObjectSaveContextPhase GetPhase () const
Return which phase of SavePackage callbacks are active.
uint32 GetSaveFlags () const
Return the save flags (ESaveFlags) of the save.
const TCHAR * GetTargetFilename () const
The target Filename being saved into (not the temporary file for saving).
const ITargetPlatform * GetTargetPlatform () const
Return the targetplatform of the save, if cooking.
bool IsCookByTheBook () const
bool IsCooking () const
Report whether this is a save into a target-specific cooked format.
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
bool IsDeterminismDebug () const
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
bool IsFirstConcurrentSave () const
Always true normally.
bool IsProceduralSave () const
Return whether the package is being saved due to a procedural save.
bool IsUpdatingLoadedPath () const
Return whether LoadedPath of the package being saved is being updated.
void RegisterDeterminismHelper (const TRefCountPtr< UE::Cook::IDeterminismHelper > &DeterminismHelper)
Ignored unless IsDeterminismDebug()=true.
UE_DEPRECATED (5.5, "Calling AddSaveOverride in UObject::PreSave is deprecated. Override UObject::CollectSaveOverrides and call AddSaveOverride on its context instead.") void AddSaveOverride(UObject *Target
Add a save override to specific object.
UE_DEPRECATED(5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.AddLoadBuildDependency (@see CookEvents.h).") 1 void AddCookBuildDependency(UE UE_DEPRECATED (5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.AddRuntimeDependency (@see CookEvents.h).") 1 void AddCookRuntimeDependency(FSoftObjectPath Dependency)
UE_DEPRECATED (5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.HarvestCookRuntimeDependencies (@see CookEvents.h).") 1 void HarvestCookRuntimeDependencies(UObject *HarvestReferencesFrom)
Data Fields
FObjectSaveOverride InOverride
Protected Attributes
FObjectSaveContextData & Data
Friends
class UObject
Detailed Description
Interface used by PreSave to access the save parameters.
Definition at line 243 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectPreSaveContext() [1/2]
FObjectPreSaveContext::FObjectPreSaveContext (FObjectSaveContextData & InData) inline explicit
Definition at line 246 of file ObjectSaveContext.h.
References Data.
Referenced by FObjectPreSaveContext(), FObjectPreSaveRootContext::FObjectPreSaveRootContext(), and FObjectPreSaveRootContext::FObjectPreSaveRootContext().
FObjectPreSaveContext() [2/2]
FObjectPreSaveContext::FObjectPreSaveContext (const FObjectPreSaveContext & Other) inline
Definition at line 252 of file ObjectSaveContext.h.
References FObjectPreSaveContext(), Data, and Other.
Member Function Documentation
GetCookingDLC()
UE::Cook::ECookingDLC FObjectPreSaveContext::GetCookingDLC () const inline
Definition at line 275 of file ObjectSaveContext.h.
References Data.
GetCookType()
UE::Cook::ECookType FObjectPreSaveContext::GetCookType () const inline
Definition at line 274 of file ObjectSaveContext.h.
References Data.
Referenced by IsCookByTheBook(), IsCookOnTheFly(), and IsCookTypeUnknown().
GetPhase()
EObjectSaveContextPhase FObjectPreSaveContext::GetPhase () const inline
Return which phase of SavePackage callbacks are active.
See also
EObjectSaveContextPhase.
Definition at line 278 of file ObjectSaveContext.h.
References Data.
GetSaveFlags()
uint32 FObjectPreSaveContext::GetSaveFlags () const inline
Return the save flags (ESaveFlags) of the save.
Definition at line 314 of file ObjectSaveContext.h.
References Data.
GetTargetFilename()
const TCHAR * FObjectPreSaveContext::GetTargetFilename () const inline
The target Filename being saved into (not the temporary file for saving).
The path is in the standard UnrealEngine form - it is as a relative path from the process binary directory. Empty string if the saved bytes are not being saved to a file. Never null.
Definition at line 263 of file ObjectSaveContext.h.
References Data.
GetTargetPlatform()
const ITargetPlatform * FObjectPreSaveContext::GetTargetPlatform () const inline
Return the targetplatform of the save, if cooking.
Null if not cooking.
Definition at line 269 of file ObjectSaveContext.h.
References Data.
IsCookByTheBook()
bool FObjectPreSaveContext::IsCookByTheBook () const inline
Definition at line 271 of file ObjectSaveContext.h.
References UE::Cook::ByTheBook, and GetCookType().
IsCooking()
bool FObjectPreSaveContext::IsCooking () const inline
Report whether this is a save into a target-specific cooked format.
Definition at line 266 of file ObjectSaveContext.h.
References Data.
IsCookOnTheFly()
bool FObjectPreSaveContext::IsCookOnTheFly () const inline
Definition at line 272 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::OnTheFly.
IsCookTypeUnknown()
bool FObjectPreSaveContext::IsCookTypeUnknown () const inline
Definition at line 273 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::Unknown.
IsDeterminismDebug()
bool FObjectPreSaveContext::IsDeterminismDebug () const
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
References IsDeterminismDebug().
Referenced by IsDeterminismDebug().
IsFirstConcurrentSave()
bool FObjectPreSaveContext::IsFirstConcurrentSave () const inline
Always true normally.
When a system is executing multiple PreSaves concurrently before a single save, will return false for all but the first PreSave.
Definition at line 320 of file ObjectSaveContext.h.
References Data.
IsProceduralSave()
bool FObjectPreSaveContext::IsProceduralSave () const inline
Return whether the package is being saved due to a procedural save.
Any save without the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
Definition at line 305 of file ObjectSaveContext.h.
References Data.
IsUpdatingLoadedPath()
bool FObjectPreSaveContext::IsUpdatingLoadedPath () const inline
Return whether LoadedPath of the package being saved is being updated.
This allows us to update the in-memory package when it is saved in editor to match its new save file.
Definition at line 311 of file ObjectSaveContext.h.
References Data.
RegisterDeterminismHelper()
void FObjectPreSaveContext::RegisterDeterminismHelper (const TRefCountPtr< UE::Cook::IDeterminismHelper > & DeterminismHelper)
Ignored unless IsDeterminismDebug()=true.
An object should call this function to register their callback class for adding determinism diagnostics the package save.
References RegisterDeterminismHelper().
Referenced by RegisterDeterminismHelper().
UE_DEPRECATED() [1/3]
FObjectPreSaveContext::UE_DEPRECATED (5. 5, "Calling AddSaveOverride in UObject::PreSave is deprecated. Override UObject::CollectSaveOverrides and call AddSaveOverride on its context instead.")
Add a save override to specific object.
(i.e. mark certain objects or properties transient for this save)
UE_DEPRECATED() [2/3]
UE_DEPRECATED(5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.AddLoadBuildDependency (@see CookEvents.h).") 1 void AddCookBuildDependency(UE FObjectPreSaveContext::UE_DEPRECATED (5. 6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.AddRuntimeDependency (@see CookEvents.h).")
References UE_DEPRECATED().
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FObjectPreSaveContext::UE_DEPRECATED (5. 6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.HarvestCookRuntimeDependencies (@see CookEvents.h).")
References UE_DEPRECATED(), and UObject.
Friends And Related Symbol Documentation
UObject
friend class UObject friend
Definition at line 333 of file ObjectSaveContext.h.
References UObject.
Referenced by UE_DEPRECATED(), and UObject.
Field Documentation
Data
FObjectSaveContextData& FObjectPreSaveContext::Data protected
Definition at line 332 of file ObjectSaveContext.h.
Referenced by FObjectPreSaveContext(), FObjectPreSaveContext(), FObjectPreSaveRootContext::FObjectPreSaveRootContext(), GetCookingDLC(), GetCookType(), GetPhase(), GetSaveFlags(), GetTargetFilename(), GetTargetPlatform(), IsCooking(), IsFirstConcurrentSave(), IsProceduralSave(), IsUpdatingLoadedPath(), and FObjectPreSaveRootContext::SetCleanupRequired().
InOverride
FObjectSaveOverride FObjectPreSaveContext::InOverride
Initial value:
{
        Data.AddSaveOverride(Target, MoveTemp(InOverride))
Definition at line 326 of file ObjectSaveContext.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ObjectSaveContext.h