Unreal Engine 5.6 C++ API: FUniformBufferStaticSlotRegistry Class Reference
FUniformBufferStaticSlotRegistry Class Reference
Registry for uniform buffer static slots.
#include "ShaderParameterMetadata.h"
Public Member Functions
FUniformBufferStaticSlot FindSlotByName (FName SlotName) const
FString GetDebugDescription (FUniformBufferStaticSlot Slot) const
int32 GetSlotCount () const
FName GetSlotName (FUniformBufferStaticSlot Slot) const
RENDERCORE_API void RegisterSlot (FName SlotName)
Static Public Member Functions
static RENDERCORE_API FUniformBufferStaticSlotRegistry & Get ()
Private Attributes
TArray< FName > SlotNames
Detailed Description
Registry for uniform buffer static slots.
Definition at line 94 of file ShaderParameterMetadata.h.
Member Function Documentation
FindSlotByName()
FUniformBufferStaticSlot FUniformBufferStaticSlotRegistry::FindSlotByName (FName SlotName) const inline
Definition at line 117 of file ShaderParameterMetadata.h.
References SlotNames.
Get()
RENDERCORE_API FUniformBufferStaticSlotRegistry & FUniformBufferStaticSlotRegistry::Get () static
GetDebugDescription()
FString FUniformBufferStaticSlotRegistry::GetDebugDescription (FUniformBufferStaticSlot Slot) const inline
Definition at line 106 of file ShaderParameterMetadata.h.
References GetSlotName(), TEXT, and ToString().
GetSlotCount()
int32 FUniformBufferStaticSlotRegistry::GetSlotCount () const inline
Definition at line 101 of file ShaderParameterMetadata.h.
References SlotNames.
GetSlotName()
FName FUniformBufferStaticSlotRegistry::GetSlotName (FUniformBufferStaticSlot Slot) const inline
Definition at line 111 of file ShaderParameterMetadata.h.
References checkf, SlotNames, and TEXT.
Referenced by GetDebugDescription().
RegisterSlot()
RENDERCORE_API void FUniformBufferStaticSlotRegistry::RegisterSlot (FName SlotName)
Field Documentation
SlotNames
TArray<FName> FUniformBufferStaticSlotRegistry::SlotNames private
Definition at line 131 of file ShaderParameterMetadata.h.
Referenced by FindSlotByName(), GetSlotCount(), and GetSlotName().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameterMetadata.h