Unreal Engine 5.6 C++ API: FUTF8ToTCHAR_Convert Class Reference
FUTF8ToTCHAR_Convert Class Reference
#include "StringConv.h"
Public Types
typedef UTF8CHAR FromType
typedef ANSICHAR LegacyFromType
typedef TCHAR ToType
Static Public Member Functions
static FORCEINLINE void Convert (ToType *Dest, const int32 DestLen, const LegacyFromType *Source, const int32 SourceLen)
template<typename SrcBufferType UE_REQUIRES>
static FORCEINLINE void Convert (ToType *Dest, const int32 DestLen, const SrcBufferType *Source, const int32 SourceLen)
Converts the UTF-8 string to UTF-16 or UTF-32.
static int32 ConvertedLength (const LegacyFromType *Source, const int32 SourceLen)
template<typename SrcBufferType UE_REQUIRES>
static int32 ConvertedLength (const SrcBufferType *Source, const int32 SourceLen)
Determines the length of the converted string.
Detailed Description
Definition at line 364 of file StringConv.h.
Member Typedef Documentation
FromType
typedef UTF8CHAR FUTF8ToTCHAR_Convert::FromType
Definition at line 368 of file StringConv.h.
LegacyFromType
typedef ANSICHAR FUTF8ToTCHAR_Convert::LegacyFromType
Definition at line 367 of file StringConv.h.
ToType
typedef TCHAR FUTF8ToTCHAR_Convert::ToType
Definition at line 369 of file StringConv.h.
Member Function Documentation
Convert() [1/2]
FORCEINLINE void FUTF8ToTCHAR_Convert::Convert (ToType * Dest, const int32 DestLen, const LegacyFromType * Source, const int32 SourceLen) inline static
Definition at line 387 of file StringConv.h.
References FGenericPlatformString::Convert(), FORCEINLINE, and Source.
Convert() [2/2]
template<typename SrcBufferType UE_REQUIRES> FORCEINLINE void FUTF8ToTCHAR_Convert::Convert (ToType * Dest, const int32 DestLen, const SrcBufferType * Source, const int32 SourceLen) inline static
Converts the UTF-8 string to UTF-16 or UTF-32.
Parameters
Dest The destination buffer of the converted string.
DestLen The length of the destination buffer.
Source The source string to convert.
SourceLen The length of the source string.
Definition at line 383 of file StringConv.h.
References FGenericPlatformString::Convert(), FORCEINLINE, and Source.
ConvertedLength() [1/2]
int32 FUTF8ToTCHAR_Convert::ConvertedLength (const LegacyFromType * Source, const int32 SourceLen) inline static nodiscard
Definition at line 407 of file StringConv.h.
References FGenericPlatformString::ConvertedLength(), and Source.
ConvertedLength() [2/2]
template<typename SrcBufferType UE_REQUIRES> int32 FUTF8ToTCHAR_Convert::ConvertedLength (const SrcBufferType * Source, const int32 SourceLen) inline static nodiscard
Determines the length of the converted string.
Parameters
Source string to read and determine amount of TCHARs to represent
SourceLen Length of source string; we will not read past this amount, even if the characters tell us to
Returns
The length of the string in UTF-16 or UTF-32 characters.
Definition at line 403 of file StringConv.h.
References FGenericPlatformString::ConvertedLength(), and Source.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/StringConv.h