Unreal Engine 5.6 C++ API: FMediaIOCustomizationBase Class Reference
FMediaIOCustomizationBase Class Reference abstract
Base implementation of different MediaIO details view customization.
#include "MediaIOCustomizationBase.h"
Public Member Functions
virtual void CustomizeChildren (TSharedRef< class IPropertyHandle > InPropertyHandle, class IDetailChildrenBuilder &StructBuilder, IPropertyTypeCustomizationUtils &PropertyTypeCustomizationUtils) override
Called when the children of the property should be customized or extra rows added.
virtual void CustomizeHeader (TSharedRef< class IPropertyHandle > InPropertyHandle, class FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &PropertyTypeCustomizationUtils) override
IPropertyTypeCustomization interface.
Public Member Functions inherited from IPropertyTypeCustomization
virtual ~IPropertyTypeCustomization ()
virtual bool ShouldInlineKey () const
Public Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedRef< IPropertyTypeCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPropertyTypeCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
template<class T>
void AssignValue (const T &NewValue) const
virtual TAttribute< FText > GetContentText ()=0
TArray< UObject * > GetCustomizedObjects () const
TSharedPtr< IPropertyHandle > GetMediaProperty () const
template<class T>
T * GetPropertyValueFromPropertyHandle ()
virtual TSharedRef< SWidget > HandleSourceComboButtonMenuContent ()=0
Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
FName DeviceProviderName
Private Member Functions
void AssignValueImpl (const void *NewValue) const
Private Attributes
TSharedPtr< IPropertyHandle > MediaProperty
Pointer to the property handle.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Base implementation of different MediaIO details view customization.
Definition at line 14 of file MediaIOCustomizationBase.h.
Member Function Documentation
AssignValue()
template<class T> void FMediaIOCustomizationBase::AssignValue (const T & NewValue) const inline protected
Definition at line 41 of file MediaIOCustomizationBase.h.
References AssignValueImpl().
AssignValueImpl()
void FMediaIOCustomizationBase::AssignValueImpl (const void * NewValue) const private
Referenced by AssignValue().
CustomizeChildren()
virtual void FMediaIOCustomizationBase::CustomizeChildren (TSharedRef< class IPropertyHandle > PropertyHandle, class IDetailChildrenBuilder & ChildBuilder, IPropertyTypeCustomizationUtils & CustomizationUtils) override virtual
Called when the children of the property should be customized or extra rows added.
Parameters
PropertyHandle Handle to the property being customized
StructBuilder A builder for adding children
StructCustomizationUtils Utilities for customization
Implements IPropertyTypeCustomization.
CustomizeHeader()
virtual void FMediaIOCustomizationBase::CustomizeHeader (TSharedRef< class IPropertyHandle > InPropertyHandle, class FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & PropertyTypeCustomizationUtils) override virtual
IPropertyTypeCustomization interface.
Implements IPropertyTypeCustomization.
GetContentText()
virtual TAttribute< FText > FMediaIOCustomizationBase::GetContentText () protected pure virtual
Implemented in FMediaIOConfigurationCustomization, FMediaIODeviceCustomization, FMediaIOInputConfigurationCustomization, FMediaIOOutputConfigurationCustomization, and FMediaIOVideoTimecodeConfigurationCustomization.
GetCustomizedObjects()
TArray< UObject * > FMediaIOCustomizationBase::GetCustomizedObjects () const protected
GetMediaProperty()
TSharedPtr< IPropertyHandle > FMediaIOCustomizationBase::GetMediaProperty () const inline protected
Definition at line 48 of file MediaIOCustomizationBase.h.
References MediaProperty.
GetPropertyValueFromPropertyHandle()
template<class T> T * FMediaIOCustomizationBase::GetPropertyValueFromPropertyHandle () inline protected
Definition at line 23 of file MediaIOCustomizationBase.h.
References CastField(), check, MediaProperty, Property, RawData, and Struct.
HandleSourceComboButtonMenuContent()
virtual TSharedRef< SWidget > FMediaIOCustomizationBase::HandleSourceComboButtonMenuContent () protected pure virtual
Implemented in FMediaIOConfigurationCustomization, FMediaIODeviceCustomization, FMediaIOInputConfigurationCustomization, FMediaIOOutputConfigurationCustomization, and FMediaIOVideoTimecodeConfigurationCustomization.
Field Documentation
DeviceProviderName
FName FMediaIOCustomizationBase::DeviceProviderName protected
Definition at line 51 of file MediaIOCustomizationBase.h.
MediaProperty
TSharedPtr<IPropertyHandle> FMediaIOCustomizationBase::MediaProperty private
Pointer to the property handle.
Definition at line 57 of file MediaIOCustomizationBase.h.
Referenced by GetMediaProperty(), and GetPropertyValueFromPropertyHandle().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaIOFramework/Source/MediaIOEditor/Public/Customizations/MediaIOCustomizationBase.h