Unreal Engine 5.6 C++ API: FMoveBrushOp Class Reference
FMoveBrushOp Class Reference
#include "MeshMoveBrushOps.h"
Public Member Functions
virtual void ApplyStamp (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) override
virtual ESculptBrushOpTargetType GetBrushTargetType () const override
virtual bool IgnoreZeroMovements () const override
Public Member Functions inherited from FMeshSculptBrushOp
virtual ~FMeshSculptBrushOp ()
virtual void BeginStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &InitialVertices)
virtual void CancelStroke ()
virtual void ConfigureOptions (const FSculptBrushOptions &Options)
virtual void EndStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &FinalVertices)
virtual bool GetAlignStampToView () const
virtual EBrushRegionType GetBrushRegionType () const
const FMeshSculptFallofFunc & GetFalloff () const
template<typename PropType>
PropType * GetPropertySetAs ()
template<typename PropType>
const PropType * GetPropertySetAs () const
virtual EReferencePlaneType GetReferencePlaneType () const
virtual EStampAlignmentType GetStampAlignmentType () const
virtual bool SupportsVariableSpacing () const
virtual bool UseLastStampFrameOnZeroMovement () const
virtual bool UsesAlpha () const
virtual bool WantsStampRegionPlane () const
Additional Inherited Members
Public Types inherited from FMeshSculptBrushOp
enum class EBrushRegionType { LocalSphere , InfiniteCylinder , CylinderOnSphere }
enum class EReferencePlaneType { None , InitialROI , InitialROI_ViewAligned , WorkPlane }
enum class EStampAlignmentType { HitNormal , Camera , ReferencePlane , ReferenceSphere }
Data Fields inherited from FMeshSculptBrushOp
FSculptBrushOptions CurrentOptions
TSharedPtr< FMeshSculptFallofFunc > Falloff
TWeakObjectPtr< UMeshSculptBrushOpProps > PropertySet
Detailed Description
Definition at line 44 of file MeshMoveBrushOps.h.
Member Function Documentation
ApplyStamp()
virtual void FMoveBrushOp::ApplyStamp (const FDynamicMesh3 * Mesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) inline override virtual
Implements FMeshSculptBrushOp.
Definition at line 48 of file MeshMoveBrushOps.h.
References UE::Geometry::TFrame3< RealType >::FromFrameVector(), FMeshSculptBrushOp::GetPropertySetAs(), UE::Math::TVector< T >::Length(), FSculptBrushStamp::LocalFrame, Mesh, UE::Geometry::Normalized(), UE::Geometry::TFrame3< RealType >::Origin, ParallelFor(), FSculptBrushStamp::Power, FSculptBrushStamp::PrevLocalFrame, FSculptBrushStamp::PrevWorldFrame, UE::Geometry::TFrame3< RealType >::ToFrameVector(), FSculptBrushStamp::WorldFrame, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetBrushTargetType()
virtual ESculptBrushOpTargetType FMoveBrushOp::GetBrushTargetType () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 82 of file MeshMoveBrushOps.h.
References ActivePlane.
IgnoreZeroMovements()
virtual bool FMoveBrushOp::IgnoreZeroMovements () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 87 of file MeshMoveBrushOps.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/MeshModelingTools/Public/Sculpting/MeshMoveBrushOps.h