Unreal Engine 5.6 C++ API: IAnimationDataModel Class Reference
IAnimationDataModel Class Reference abstract
#include "IAnimationDataModel.h"
Data Structures
struct FEvaluationAndModificationLock
struct FGuidGenerationSettings
struct FModelNotifier
Public Member Functions
virtual void Evaluate (FAnimationPoseData &InOutPoseData, const UE::Anim::DataModel::FEvaluationContext &EvaluationContext) const =0
Evaluates the contained Animation Data to populated an Animation Pose with (Bones, Curves and Attributes).
virtual FTransform EvaluateBoneTrackTransform (FName TrackName, const FFrameTime &FrameTime, const EAnimInterpolationType &Interpolation) const =0
virtual const FAnimatedBoneAttribute * FindAttribute (const FAnimationAttributeIdentifier &AttributeIdentifier) const =0
virtual const FAnimCurveBase * FindCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const FFloatCurve * FindFloatCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const FRichCurve * FindRichCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const FTransformCurve * FindTransformCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
GENERATED_BODY () struct FReimportScope
virtual FString GenerateDebugStateString () const
virtual FGuid GenerateGuid () const
virtual FGuid GenerateGuid (const FGuidGenerationSettings &InSettings) const =0
virtual const FAnimatedBoneAttribute & GetAttribute (const FAnimationAttributeIdentifier &AttributeIdentifier) const =0
virtual TArrayView< const FAnimatedBoneAttribute > GetAttributes () const =0
virtual void GetAttributesForBone (const FName &BoneName, TArray< const FAnimatedBoneAttribute * > &OutBoneAttributes) const =0
virtual void GetBoneTracksTransform (const TArray< FName > &TrackNames, const FFrameNumber &FrameNumber, TArray< FTransform > &OutTransforms) const =0
virtual FTransform GetBoneTrackTransform (FName TrackName, const FFrameNumber &FrameNumber) const =0
virtual void GetBoneTrackTransforms (FName TrackName, const TArray< FFrameNumber > &FrameNumbers, TArray< FTransform > &OutTransforms) const =0
virtual void GetBoneTrackTransforms (FName TrackName, TArray< FTransform > &OutTransforms) const =0
virtual TScriptInterface< IAnimationDataController > GetController ()=0
virtual const FAnimCurveBase & GetCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const FAnimationCurveData & GetCurveData () const =0
Returns all contained curve animation data.
virtual const FFloatCurve & GetFloatCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const TArray< struct FFloatCurve > & GetFloatCurves () const =0
virtual FAnimDataModelModifiedEvent & GetModifiedEvent ()=0
virtual int32 GetNumberOfAttributes () const =0
virtual int32 GetNumberOfAttributesForBoneIndex (const int32 BoneIndex) const =0
virtual const FRichCurve & GetRichCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const FTransformCurve & GetTransformCurve (const FAnimationCurveIdentifier &CurveIdentifier) const =0
virtual const TArray< struct FTransformCurve > & GetTransformCurves () const =0
virtual bool HasBeenPopulated () const =0
virtual void IterateBoneKeys (const FName &BoneName, TFunction< bool(const FVector3f &Pos, const FQuat4f &, const FVector3f, const FFrameNumber &)> IterationFunction) const =0
UE_DEPRECATED (5.2, "FindBoneTrackByIndex has been deprecated") UFUNCTION() virtual int32 GetBoneTrackIndex(const FBoneAnimationTrack &Track) const =0
UE_DEPRECATED (5.2, "FindBoneTrackByIndex has been deprecated") virtual const FBoneAnimationTrack *FindBoneTrackByIndex(int32 BoneIndex) const =0
UE_DEPRECATED (5.2, "FindBoneTrackByName has been deprecated") virtual const FBoneAnimationTrack *FindBoneTrackByName(FName Name) const =0
UE_DEPRECATED (5.2, "GetBoneAnimationTracks has been deprecated") UFUNCTION() virtual const TArray< FBoneAnimationTrack > &GetBoneAnimationTracks() const =0
UE_DEPRECATED (5.2, "GetBoneTrackByIndex has been deprecated") UFUNCTION() virtual const FBoneAnimationTrack &GetBoneTrackByIndex(int32 TrackIndex) const =0
UE_DEPRECATED (5.2, "GetBoneTrackByName has been deprecated") UFUNCTION() virtual const FBoneAnimationTrack &GetBoneTrackByName(FName TrackName) const =0
UE_DEPRECATED (5.2, "GetBoneTrackIndexByName has been deprecated") UFUNCTION() virtual int32 GetBoneTrackIndexByName(FName TrackName) const =0
UE_DEPRECATED (5.2, "IsValidBoneTrackIndex has been deprecated") UFUNCTION() virtual bool IsValidBoneTrackIndex(int32 TrackIndex) const =0
UFUNCTION () virtual bool IsValidBoneTrackName(const FName &TrackName) const =0
UFUNCTION () virtual double GetPlayLength() const =0
UFUNCTION () virtual FFrameRate GetFrameRate() const =0
UFUNCTION () virtual int32 GetNumberOfFloatCurves() const =0
UFUNCTION () virtual int32 GetNumberOfFrames() const =0
UFUNCTION () virtual int32 GetNumberOfKeys() const =0
UFUNCTION () virtual int32 GetNumberOfTransformCurves() const =0
UFUNCTION () virtual int32 GetNumBoneTracks() const =0
UFUNCTION () virtual UAnimSequence *GetAnimationSequence() const =0
UFUNCTION () virtual void GetBoneTrackNames(TArray< FName > &OutNames) const =0
Populates the provided array with all contained (bone) track names.
Protected Member Functions
virtual FAnimDataModelModifiedDynamicEvent & GetModifiedDynamicEvent ()=0
virtual IAnimationDataModel::FModelNotifier & GetNotifier ()=0
virtual bool & GetPopulationFlag ()=0
virtual void LockEvaluationAndModification () const =0
virtual void OnNotify (const EAnimDataModelNotifyType &NotifyType, const FAnimDataModelNotifPayload &Payload)=0
virtual bool TryLockEvaluationAndModification () const =0
virtual void UnlockEvaluationAndModification () const =0
Detailed Description
Definition at line 126 of file IAnimationDataModel.h.
Member Function Documentation
Evaluate()
virtual void IAnimationDataModel::Evaluate (FAnimationPoseData & InOutPoseData, const UE::Anim::DataModel::FEvaluationContext & EvaluationContext) const pure virtual
Evaluates the contained Animation Data to populated an Animation Pose with (Bones, Curves and Attributes).
Parameters
InOutPoseData Container for the to-be-evaluated pose related data
EvaluationContext Context describing how the data should be evaluated (timing etc.)
Implemented in UAnimDataModel.
EvaluateBoneTrackTransform()
virtual FTransform IAnimationDataModel::EvaluateBoneTrackTransform (FName TrackName, const FFrameTime & FrameTime, const EAnimInterpolationType & Interpolation) const pure virtual
Implemented in UAnimDataModel.
References EvaluateBoneTrackTransform(), and Interpolation.
Referenced by EvaluateBoneTrackTransform().
FindAttribute()
virtual const FAnimatedBoneAttribute * IAnimationDataModel::FindAttribute (const FAnimationAttributeIdentifier & AttributeIdentifier) const pure virtual
Returns
Animated (bone) attribute ptr for the provided identifier if valid, otherwise returns a nullptr
Implemented in UAnimDataModel.
References FindAttribute().
Referenced by FindAttribute().
FindCurve()
virtual const FAnimCurveBase * IAnimationDataModel::FindCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Curve ptr for the provided identifier if valid, otherwise returns a nullptr
Implemented in UAnimDataModel.
References FindCurve().
Referenced by FindCurve().
FindFloatCurve()
virtual const FFloatCurve * IAnimationDataModel::FindFloatCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Float Curve ptr for the provided identifier if valid, otherwise returns a nullptr
Implemented in UAnimDataModel.
References FindFloatCurve().
Referenced by FindFloatCurve().
FindRichCurve()
virtual const FRichCurve * IAnimationDataModel::FindRichCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Rich curve ptr for the provided identifier if valid, otherwise returns a nullptr
Implemented in UAnimDataModel.
References FindRichCurve().
Referenced by FindRichCurve().
FindTransformCurve()
virtual const FTransformCurve * IAnimationDataModel::FindTransformCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Transform Curve ptr for the provided identifier if valid, otherwise returns a nullptr
Implemented in UAnimDataModel.
References FindTransformCurve().
Referenced by FindTransformCurve().
GENERATED_BODY()
IAnimationDataModel::GENERATED_BODY () inline
Definition at line 129 of file IAnimationDataModel.h.
References GetPopulationFlag().
GenerateDebugStateString()
virtual FString IAnimationDataModel::GenerateDebugStateString () const inline virtual
Returns
String representing the data reported by GenerateGuid, used to debug indeterminism in GenerateGuid.
Reimplemented in UAnimDataModel.
Definition at line 391 of file IAnimationDataModel.h.
References GenerateGuid(), TEXT, and ToString().
GenerateGuid() [1/2]
virtual FGuid IAnimationDataModel::GenerateGuid () const inline virtual
Returns
GUID representing the contained data and state
Definition at line 385 of file IAnimationDataModel.h.
References GenerateGuid().
Referenced by GenerateGuid().
GenerateGuid() [2/2]
virtual FGuid IAnimationDataModel::GenerateGuid (const FGuidGenerationSettings & InSettings) const pure virtual
Returns
GUID representing a configured sub-set of the contained data and state
Parameters
InSettings Settings used to determine which data should be included when generating the returned GUID
Implemented in UAnimDataModel.
Referenced by GenerateDebugStateString().
GetAttribute()
virtual const FAnimatedBoneAttribute & IAnimationDataModel::GetAttribute (const FAnimationAttributeIdentifier & AttributeIdentifier) const pure virtual
Returns
Animated (bone) attribute object for the provided identifier if valid
Implemented in UAnimDataModel.
References GetAttribute().
Referenced by GetAttribute().
GetAttributes()
virtual TArrayView< const FAnimatedBoneAttribute > IAnimationDataModel::GetAttributes () const pure virtual
Returns
Animated (bone) attributes stored
Implemented in UAnimDataModel.
References GetAttributes().
Referenced by GetAttributes().
GetAttributesForBone()
virtual void IAnimationDataModel::GetAttributesForBone (const FName & BoneName, TArray< const FAnimatedBoneAttribute * > & OutBoneAttributes) const pure virtual
Returns
All animated (bone) attributes stored for the specified bone name
Implemented in UAnimDataModel.
References GetAttributesForBone().
Referenced by GetAttributesForBone().
GetBoneTracksTransform()
virtual void IAnimationDataModel::GetBoneTracksTransform (const TArray< FName > & TrackNames, const FFrameNumber & FrameNumber, TArray< FTransform > & OutTransforms) const pure virtual
Implemented in UAnimDataModel.
References GetBoneTracksTransform().
Referenced by GetBoneTracksTransform().
GetBoneTrackTransform()
virtual FTransform IAnimationDataModel::GetBoneTrackTransform (FName TrackName, const FFrameNumber & FrameNumber) const pure virtual
Implemented in UAnimDataModel.
References GetBoneTrackTransform().
Referenced by GetBoneTrackTransform().
GetBoneTrackTransforms() [1/2]
virtual void IAnimationDataModel::GetBoneTrackTransforms (FName TrackName, const TArray< FFrameNumber > & FrameNumbers, TArray< FTransform > & OutTransforms) const pure virtual
Implemented in UAnimDataModel.
References GetBoneTrackTransforms().
Referenced by GetBoneTrackTransforms(), and GetBoneTrackTransforms().
GetBoneTrackTransforms() [2/2]
virtual void IAnimationDataModel::GetBoneTrackTransforms (FName TrackName, TArray< FTransform > & OutTransforms) const pure virtual
Implemented in UAnimDataModel.
References GetBoneTrackTransforms().
GetController()
virtual TScriptInterface< IAnimationDataController > IAnimationDataModel::GetController () pure virtual
Returns
IAnimationDataController instance used for mutating this model
Implemented in UAnimDataModel.
GetCurve()
virtual const FAnimCurveBase & IAnimationDataModel::GetCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Curve object for the provided identifier if valid
Implemented in UAnimDataModel.
References GetCurve().
Referenced by GetCurve().
GetCurveData()
virtual const FAnimationCurveData & IAnimationDataModel::GetCurveData () const pure virtual
Returns all contained curve animation data.
Implemented in UAnimDataModel.
References GetCurveData().
Referenced by GetCurveData().
GetFloatCurve()
virtual const FFloatCurve & IAnimationDataModel::GetFloatCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Float Curve object for the provided identifier if valid
Implemented in UAnimDataModel.
References GetFloatCurve().
Referenced by GetFloatCurve().
GetFloatCurves()
virtual const TArray< struct FFloatCurve > & IAnimationDataModel::GetFloatCurves () const pure virtual
Returns
Array containing all stored float curves
Implemented in UAnimDataModel.
References GetFloatCurves().
Referenced by GetFloatCurves().
GetModifiedDynamicEvent()
virtual FAnimDataModelModifiedDynamicEvent & IAnimationDataModel::GetModifiedDynamicEvent () protected pure virtual
Implemented in UAnimDataModel.
Referenced by IAnimationDataModel::FModelNotifier::FModelNotifier().
GetModifiedEvent()
virtual FAnimDataModelModifiedEvent & IAnimationDataModel::GetModifiedEvent () pure virtual
Returns
Multicast delegate which is broadcasted to propagated changes to any internal data, see FAnimDataModelModifiedEvent and EAnimDataModelNotifyType
Implemented in UAnimDataModel.
References GetModifiedEvent().
Referenced by IAnimationDataModel::FModelNotifier::FModelNotifier(), and GetModifiedEvent().
GetNotifier()
virtual IAnimationDataModel::FModelNotifier & IAnimationDataModel::GetNotifier () protected pure virtual
Implemented in UAnimDataModel.
GetNumberOfAttributes()
virtual int32 IAnimationDataModel::GetNumberOfAttributes () const pure virtual
Returns
Number of animated (bone) attributes stored
Implemented in UAnimDataModel.
References GetNumberOfAttributes().
Referenced by GetNumberOfAttributes().
GetNumberOfAttributesForBoneIndex()
virtual int32 IAnimationDataModel::GetNumberOfAttributesForBoneIndex (const int32 BoneIndex) const pure virtual
Returns
Number of animated (bone) attributes stored for the specified bone index
Implemented in UAnimDataModel.
References GetNumberOfAttributesForBoneIndex().
Referenced by GetNumberOfAttributesForBoneIndex().
GetPopulationFlag()
virtual bool & IAnimationDataModel::GetPopulationFlag () protected pure virtual
Implemented in UAnimDataModel.
Referenced by GENERATED_BODY().
GetRichCurve()
virtual const FRichCurve & IAnimationDataModel::GetRichCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Rich Curve object for the provided identifier if valid
Implemented in UAnimDataModel.
References GetRichCurve().
Referenced by GetRichCurve().
GetTransformCurve()
virtual const FTransformCurve & IAnimationDataModel::GetTransformCurve (const FAnimationCurveIdentifier & CurveIdentifier) const pure virtual
Returns
Transform Curve object for the provided identifier if valid
Implemented in UAnimDataModel.
References GetTransformCurve().
Referenced by GetTransformCurve().
GetTransformCurves()
virtual const TArray< struct FTransformCurve > & IAnimationDataModel::GetTransformCurves () const pure virtual
Returns
Array containing all stored FTransform curves
Implemented in UAnimDataModel.
References GetTransformCurves().
Referenced by GetTransformCurves().
HasBeenPopulated()
virtual bool IAnimationDataModel::HasBeenPopulated () const pure virtual
Implemented in UAnimDataModel.
IterateBoneKeys()
virtual void IAnimationDataModel::IterateBoneKeys (const FName & BoneName, TFunction< bool(const FVector3f &Pos, const FQuat4f &, const FVector3f, const FFrameNumber &)> IterationFunction) const pure virtual
Implemented in UAnimDataModel.
LockEvaluationAndModification()
virtual void IAnimationDataModel::LockEvaluationAndModification () const protected pure virtual
Implemented in UAnimDataModel.
Referenced by IAnimationDataModel::FEvaluationAndModificationLock::FEvaluationAndModificationLock().
OnNotify()
virtual void IAnimationDataModel::OnNotify (const EAnimDataModelNotifyType & NotifyType, const FAnimDataModelNotifPayload & Payload) protected pure virtual
Implemented in UAnimDataModel.
TryLockEvaluationAndModification()
virtual bool IAnimationDataModel::TryLockEvaluationAndModification () const protected pure virtual
Implemented in UAnimDataModel.
Referenced by IAnimationDataModel::FEvaluationAndModificationLock::FEvaluationAndModificationLock().
UE_DEPRECATED() [1/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "FindBoneTrackByIndex has been deprecated") const & pure virtual
Returns
Internal track index for the provided bone animation track if found, otherwise returns INDEX_NONE
References Category, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [2/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "FindBoneTrackByIndex has been deprecated") const pure virtual
Returns
Bone animation track for the provided index if valid, otherwise returns a nullptr
References UE_DEPRECATED().
UE_DEPRECATED() [3/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "FindBoneTrackByName has been deprecated") const pure virtual
Returns
Bone animation track for the provided (bone) name if found, otherwise returns a nullptr
References Name, and UE_DEPRECATED().
UE_DEPRECATED() [4/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "GetBoneAnimationTracks has been deprecated") const & pure virtual
Returns
Array containing all bone animation tracks
References Category, and UFUNCTION().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "GetBoneTrackByIndex has been deprecated") const & pure virtual
Returns
Bone animation track for the provided index
References Category, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [6/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "GetBoneTrackByName has been deprecated") const & pure virtual
Returns
Bone animation track for the provided (bone) name
References Category, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [7/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "GetBoneTrackIndexByName has been deprecated") const pure virtual
Returns
Internal track index for the provided (bone) name if found, otherwise returns INDEX_NONE
References Category, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [8/8]
IAnimationDataModel::UE_DEPRECATED (5. 2, "IsValidBoneTrackIndex has been deprecated") const pure virtual
Returns
Whether or not the provided track index is valid
References Category, UE_DEPRECATED(), and UFUNCTION().
UFUNCTION() [1/10]
IAnimationDataModel::UFUNCTION () const & pure virtual
References Category, and UFUNCTION().
UFUNCTION() [2/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Total length of play-able animation data
References Category.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [3/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Frame rate at which the animation data is key-ed
References Category.
UFUNCTION() [4/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Total number of stored float curves
References Category, and UFUNCTION().
UFUNCTION() [5/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Total number of frames of animation data stored
References Category.
UFUNCTION() [6/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Total number of animation data keys stored
References Category.
UFUNCTION() [7/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Total number of stored FTransform curves
References Category, and UFUNCTION().
UFUNCTION() [8/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
Total number of bone animation tracks
References Category, and UFUNCTION().
UFUNCTION() [9/10]
IAnimationDataModel::UFUNCTION () const pure virtual
Returns
The outer UAnimSequence object if found, otherwise returns a nullptr
References Category, and UFUNCTION().
UFUNCTION() [10/10]
IAnimationDataModel::UFUNCTION () const & pure virtual
Populates the provided array with all contained (bone) track names.
Parameters
OutNames [out] Array containing all bone track names
References Category, and UFUNCTION().
UnlockEvaluationAndModification()
virtual void IAnimationDataModel::UnlockEvaluationAndModification () const protected pure virtual
Implemented in UAnimDataModel.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Animation/AnimData/IAnimationDataModel.h