Unreal Engine 5.6 C++ API: FDetailsDiff Class Reference
FDetailsDiff Class Reference
Struct to handle showing details for an object and provide an interface for listing all differences.
#include "DetailsDiff.h"
Public Member Functions
FDetailsDiff (const UObject *InObject, bool bScrollbarOnLeft=false)
TSharedRef< IDetailsView > DetailsWidget () const
Returns actual widget that is used to display details.
void DiffAgainst (const FDetailsDiff &Newer, TArray< FSingleObjectDiffEntry > &OutDifferences, bool bSortByDisplayOrder=false) const
Perform a diff against another view, ordering either by display order or by remove/add/change.
const UObject * GetDisplayedObject () const
Returns object being displayed.
TArray< FPropertySoftPath > GetDisplayedProperties () const
Returns a list of all properties that would be diffed.
PRAGMA_ENABLE_DEPRECATION_WARNINGS void HighlightProperty (const FPropertySoftPath &PropertyName)
Attempt to highlight the property with the given path, may not always succeed.
UE_DEPRECATED (5.6, "FOnDisplayedPropertiesChanged removed, interact with IDetailsView directly") DECLARE_DELEGATE(FOnDisplayedPropertiesChanged)
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "InOnDisplayedPropertiesChanged, interact with IDetailsView directly") FDetailsDiff(const UObject *InObject
Static Public Member Functions
static TSharedRef< IDetailsView > CreateDetailsView (const UObject *InObject, TSharedPtr< SScrollBar > ExternalScrollbar=nullptr, bool bScrollbarOnLeft=false)
static void LinkScrolling (FDetailsDiff &LeftPanel, FDetailsDiff &RightPanel, const TAttribute< TArray< FVector2f > > &ScrollRate)
Link the two details panels so they scroll in sync with one another.
Data Fields
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOnDisplayedPropertiesChanged bool bScrollbarOnLeft = false)
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOnDisplayedPropertiesChanged InOnDisplayedPropertiesChanged
Private Attributes
TSharedPtr< class IDetailsView > DetailsView
const UObject * DisplayedObject
TArray< FPropertyPath > DisplayedProperties
TSharedPtr< SLinkableScrollBar > ScrollBar
Detailed Description
Struct to handle showing details for an object and provide an interface for listing all differences.
Definition at line 18 of file DetailsDiff.h.
Constructor & Destructor Documentation
FDetailsDiff()
FDetailsDiff::FDetailsDiff (const UObject * InObject, bool bScrollbarOnLeft = false)
References bScrollbarOnLeft.
Referenced by DiffAgainst(), and LinkScrolling().
Member Function Documentation
CreateDetailsView()
TSharedRef< IDetailsView > FDetailsDiff::CreateDetailsView (const UObject * InObject, TSharedPtr< SScrollBar > ExternalScrollbar = nullptr, bool bScrollbarOnLeft = false) static
References bScrollbarOnLeft.
DetailsWidget()
TSharedRef< IDetailsView > FDetailsDiff::DetailsWidget () const
Returns actual widget that is used to display details.
References DetailsWidget().
Referenced by DetailsWidget().
DiffAgainst()
void FDetailsDiff::DiffAgainst (const FDetailsDiff & Newer, TArray< FSingleObjectDiffEntry > & OutDifferences, bool bSortByDisplayOrder = false) const
Perform a diff against another view, ordering either by display order or by remove/add/change.
References FDetailsDiff(), and Newer.
GetDisplayedObject()
const UObject * FDetailsDiff::GetDisplayedObject () const inline
Returns object being displayed.
Definition at line 38 of file DetailsDiff.h.
References DisplayedObject, and GetDisplayedObject().
Referenced by GetDisplayedObject().
GetDisplayedProperties()
TArray< FPropertySoftPath > FDetailsDiff::GetDisplayedProperties () const
Returns a list of all properties that would be diffed.
HighlightProperty()
PRAGMA_ENABLE_DEPRECATION_WARNINGS void FDetailsDiff::HighlightProperty (const FPropertySoftPath & PropertyName)
Attempt to highlight the property with the given path, may not always succeed.
References HighlightProperty(), and PropertyName.
Referenced by HighlightProperty().
LinkScrolling()
void FDetailsDiff::LinkScrolling (FDetailsDiff & LeftPanel, FDetailsDiff & RightPanel, const TAttribute< TArray< FVector2f > > & ScrollRate) static
Link the two details panels so they scroll in sync with one another.
References FDetailsDiff().
UE_DEPRECATED() [1/2]
FDetailsDiff::UE_DEPRECATED (5. 6, "FOnDisplayedPropertiesChanged removed, interact with IDetailsView directly")
References DECLARE_DELEGATE, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FDetailsDiff::UE_DEPRECATED (5. 6, " InOnDisplayedPropertiesChanged, interact with IDetailsView directly") const
References UE_DEPRECATED().
Field Documentation
bScrollbarOnLeft
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOnDisplayedPropertiesChanged bool FDetailsDiff::bScrollbarOnLeft = false)
Definition at line 28 of file DetailsDiff.h.
Referenced by FDetailsDiff(), and CreateDetailsView().
DetailsView
TSharedPtr< class IDetailsView > FDetailsDiff::DetailsView private
Definition at line 55 of file DetailsDiff.h.
DisplayedObject
const UObject* FDetailsDiff::DisplayedObject private
Definition at line 53 of file DetailsDiff.h.
Referenced by GetDisplayedObject().
DisplayedProperties
TArray< FPropertyPath > FDetailsDiff::DisplayedProperties private
Definition at line 52 of file DetailsDiff.h.
InOnDisplayedPropertiesChanged
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOnDisplayedPropertiesChanged FDetailsDiff::InOnDisplayedPropertiesChanged
Definition at line 28 of file DetailsDiff.h.
ScrollBar
TSharedPtr<SLinkableScrollBar> FDetailsDiff::ScrollBar private
Definition at line 57 of file DetailsDiff.h.
The documentation for this class was generated from the following file:
Editor/Kismet/Public/DetailsDiff.h