Unreal Engine 5.6 C++ API: FScopedStoreArchiveOffset Class Reference
FScopedStoreArchiveOffset Class Reference
Helps track Offsets in an Archive before the actual size of the offset is known.
#include "ReplayTypes.h"
Public Member Functions
FScopedStoreArchiveOffset ()=delete
FScopedStoreArchiveOffset (const FScopedStoreArchiveOffset &)=delete
FScopedStoreArchiveOffset (FArchive &InAr)
FScopedStoreArchiveOffset (FScopedStoreArchiveOffset &&)=delete
~FScopedStoreArchiveOffset ()
FScopedStoreArchiveOffset & operator= (const FScopedStoreArchiveOffset &)=delete
FScopedStoreArchiveOffset & operator= (FScopedStoreArchiveOffset &&)=delete
Private Attributes
FArchive & Ar
const FArchivePos StartPosition
Detailed Description
Helps track Offsets in an Archive before the actual size of the offset is known.
This relies on serialization always used a fixed number of bytes for primitive types, and Sane implementations of Seek and Tell.
Definition at line 451 of file ReplayTypes.h.
Constructor & Destructor Documentation
FScopedStoreArchiveOffset() [1/4]
FScopedStoreArchiveOffset::FScopedStoreArchiveOffset () delete
Referenced by FScopedStoreArchiveOffset(), FScopedStoreArchiveOffset(), operator=(), and operator=().
FScopedStoreArchiveOffset() [2/4]
FScopedStoreArchiveOffset::FScopedStoreArchiveOffset (FScopedStoreArchiveOffset &&) delete
References FScopedStoreArchiveOffset().
FScopedStoreArchiveOffset() [3/4]
FScopedStoreArchiveOffset::FScopedStoreArchiveOffset (const FScopedStoreArchiveOffset &) delete
References FScopedStoreArchiveOffset().
FScopedStoreArchiveOffset() [4/4]
FScopedStoreArchiveOffset::FScopedStoreArchiveOffset (FArchive & InAr) inline
Definition at line 460 of file ReplayTypes.h.
References Ar, and StartPosition.
~FScopedStoreArchiveOffset()
FScopedStoreArchiveOffset::~FScopedStoreArchiveOffset () inline
Definition at line 469 of file ReplayTypes.h.
References Ar, and StartPosition.
Member Function Documentation
operator=() [1/2]
FScopedStoreArchiveOffset & FScopedStoreArchiveOffset::operator= (const FScopedStoreArchiveOffset &) delete
References FScopedStoreArchiveOffset().
operator=() [2/2]
FScopedStoreArchiveOffset & FScopedStoreArchiveOffset::operator= (FScopedStoreArchiveOffset &&) delete
References FScopedStoreArchiveOffset().
Field Documentation
Ar
FArchive& FScopedStoreArchiveOffset::Ar private
Definition at line 480 of file ReplayTypes.h.
Referenced by FScopedStoreArchiveOffset(), and ~FScopedStoreArchiveOffset().
StartPosition
const FArchivePos FScopedStoreArchiveOffset::StartPosition private
Definition at line 481 of file ReplayTypes.h.
Referenced by FScopedStoreArchiveOffset(), and ~FScopedStoreArchiveOffset().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ReplayTypes.h