Unreal Engine 5.6 C++ API: FRigVMGraphMathTypeDetailCustomization Class Reference
FRigVMGraphMathTypeDetailCustomization Class Reference
Customization for editing a rig vm node.
#include "RigVMGraphDetailCustomization.h"
Public Member Functions
FRigVMGraphMathTypeDetailCustomization ()
virtual void CustomizeChildren (TSharedRef< class IPropertyHandle > InPropertyHandle, class IDetailChildrenBuilder &StructBuilder, IPropertyTypeCustomizationUtils &StructCustomizationUtils) override
Called when the children of the property should be customized or extra rows added.
virtual void CustomizeHeader (TSharedRef< class IPropertyHandle > InPropertyHandle, class FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &StructCustomizationUtils) override
IPropertyTypeCustomization interface.
Public Member Functions inherited from IPropertyTypeCustomization
virtual ~IPropertyTypeCustomization ()
virtual bool ShouldInlineKey () const
Public Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedRef< IPropertyTypeCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPropertyTypeCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IPropertyTypeCustomization > MakeInstance ()
Protected Member Functions
template<typename TransformType>
void ConfigureTransformWidgetArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, typename SAdvancedTransformInputBox< TransformType >::FArguments &WidgetArgs, TConstArrayView< FName > ComponentNames)
template<typename RotationType>
void ExtendRotationArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void *ArgumentsPtr)
template<>
void ExtendRotationArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void *ArgumentsPtr)
template<>
void ExtendRotationArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void *ArgumentsPtr)
template<typename VectorType>
void ExtendVectorArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void *ArgumentsPtr)
template<>
void ExtendVectorArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void *ArgumentsPtr)
template<>
void ExtendVectorArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void *ArgumentsPtr)
bool GetPropertyChain (TSharedRef< class IPropertyHandle > InPropertyHandle, FEditPropertyChain &OutPropertyChain, TArray< int32 > &OutPropertyArrayIndices, bool &bOutEnabled)
template<typename RotationType>
TOptional< RotationType > GetRotation (TSharedRef< class IPropertyHandle > InPropertyHandle)
template<typename VectorType, typename NumericType>
TOptional< NumericType > GetVectorComponent (TSharedRef< class IPropertyHandle > InPropertyHandle, int32 InComponent)
template<typename RotationType>
void MakeRotationHeaderRow (TSharedRef< class IPropertyHandle > InPropertyHandle, FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &StructCustomizationUtils)
template<typename TransformType>
void MakeTransformChildren (TSharedRef< class IPropertyHandle > InPropertyHandle, IDetailChildrenBuilder &StructBuilder, IPropertyTypeCustomizationUtils &StructCustomizationUtils, TConstArrayView< FName > ComponentNames)
template<typename TransformType>
void MakeTransformHeaderRow (TSharedRef< class IPropertyHandle > InPropertyHandle, FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &StructCustomizationUtils, TConstArrayView< FName > ComponentNames)
template<typename VectorType, int32 NumberOfComponents>
void MakeVectorHeaderRow (TSharedRef< class IPropertyHandle > InPropertyHandle, FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &StructCustomizationUtils)
template<typename RotationType>
void OnRotationChanged (TSharedRef< class IPropertyHandle > InPropertyHandle, RotationType InValue, bool bIsCommit, ETextCommit::Type InCommitType=ETextCommit::Default)
template<typename VectorType, typename NumericType>
void OnVectorComponentChanged (TSharedRef< class IPropertyHandle > InPropertyHandle, int32 InComponent, NumericType InValue, bool bIsCommit, ETextCommit::Type InCommitType=ETextCommit::Default)
Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
template<typename ValueType>
static ValueType & ContainerMemoryBlockToValueRef (uint8 *InMemoryBlock, ValueType &InDefault, FEditPropertyChain &InPropertyChain, TArray< int32 > &InPropertyArrayIndices)
template<typename TransformType>
static FName GetRotationPropertyName ()
template<typename TransformType>
static FName GetScalePropertyName ()
template<>
FName GetScalePropertyName ()
template<typename TransformType>
static FName GetTranslationPropertyName ()
template<>
FName GetTranslationPropertyName ()
template<typename ValueType>
static bool IsQuaternionBasedRotation ()
template<>
bool IsQuaternionBasedRotation ()
template<>
bool IsQuaternionBasedRotation ()
Static Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
TWeakObjectPtr< URigVMBlueprint > BlueprintBeingCustomized
TWeakObjectPtr< URigVMGraph > GraphBeingCustomized
Detailed Description
Customization for editing a rig vm node.
Definition at line 434 of file RigVMGraphDetailCustomization.h.
Constructor & Destructor Documentation
FRigVMGraphMathTypeDetailCustomization()
FRigVMGraphMathTypeDetailCustomization::FRigVMGraphMathTypeDetailCustomization ()
Referenced by MakeInstance().
Member Function Documentation
ConfigureTransformWidgetArgs()
template<typename TransformType> void FRigVMGraphMathTypeDetailCustomization::ConfigureTransformWidgetArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, typename SAdvancedTransformInputBox< TransformType >::FArguments & WidgetArgs, TConstArrayView< FName > ComponentNames) protected
ContainerMemoryBlockToValueRef()
template<typename ValueType> ValueType & FRigVMGraphMathTypeDetailCustomization::ContainerMemoryBlockToValueRef (uint8 * InMemoryBlock, ValueType & InDefault, FEditPropertyChain & InPropertyChain, TArray< int32 > & InPropertyArrayIndices) inline static protected
Definition at line 484 of file RigVMGraphDetailCustomization.h.
References ArrayProperty, CastField(), check, TDoubleLinkedList< ElementType >::GetHead(), FScriptArrayHelper::GetRawPtr(), INDEX_NONE, FScriptArrayHelper::IsValidIndex(), TArray< InElementType, InAllocatorType >::IsValidIndex(), and Property.
CustomizeChildren()
virtual void FRigVMGraphMathTypeDetailCustomization::CustomizeChildren (TSharedRef< class IPropertyHandle > PropertyHandle, class IDetailChildrenBuilder & ChildBuilder, IPropertyTypeCustomizationUtils & CustomizationUtils) override virtual
Called when the children of the property should be customized or extra rows added.
Parameters
PropertyHandle Handle to the property being customized
StructBuilder A builder for adding children
StructCustomizationUtils Utilities for customization
Implements IPropertyTypeCustomization.
CustomizeHeader()
virtual void FRigVMGraphMathTypeDetailCustomization::CustomizeHeader (TSharedRef< class IPropertyHandle > InPropertyHandle, class FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & StructCustomizationUtils) override virtual
IPropertyTypeCustomization interface.
Implements IPropertyTypeCustomization.
ExtendRotationArgs() [1/3]
template<typename RotationType> void FRigVMGraphMathTypeDetailCustomization::ExtendRotationArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void * ArgumentsPtr) inline protected
Definition at line 668 of file RigVMGraphDetailCustomization.h.
ExtendRotationArgs() [2/3]
template<> void FRigVMGraphMathTypeDetailCustomization::ExtendRotationArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void * ArgumentsPtr) inline protected
Definition at line 757 of file RigVMGraphDetailCustomization.h.
References GetRotation(), and OnRotationChanged().
ExtendRotationArgs() [3/3]
template<> void FRigVMGraphMathTypeDetailCustomization::ExtendRotationArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void * ArgumentsPtr) inline protected
Definition at line 781 of file RigVMGraphDetailCustomization.h.
References GetRotation(), and OnRotationChanged().
ExtendVectorArgs() [1/3]
template<typename VectorType> void FRigVMGraphMathTypeDetailCustomization::ExtendVectorArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void * ArgumentsPtr) inline protected
Definition at line 590 of file RigVMGraphDetailCustomization.h.
ExtendVectorArgs() [2/3]
template<> void FRigVMGraphMathTypeDetailCustomization::ExtendVectorArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void * ArgumentsPtr) inline protected
Definition at line 699 of file RigVMGraphDetailCustomization.h.
References FVector, GetVectorComponent(), OnVectorComponentChanged(), and Value.
ExtendVectorArgs() [3/3]
template<> void FRigVMGraphMathTypeDetailCustomization::ExtendVectorArgs (TSharedRef< class IPropertyHandle > InPropertyHandle, void * ArgumentsPtr) inline protected
Definition at line 722 of file RigVMGraphDetailCustomization.h.
References GetVectorComponent(), OnVectorComponentChanged(), and Value.
GetPropertyChain()
bool FRigVMGraphMathTypeDetailCustomization::GetPropertyChain (TSharedRef< class IPropertyHandle > InPropertyHandle, FEditPropertyChain & OutPropertyChain, TArray< int32 > & OutPropertyArrayIndices, bool & bOutEnabled) inline protected
Definition at line 451 of file RigVMGraphDetailCustomization.h.
References TDoubleLinkedList< ElementType >::AddHead(), TDoubleLinkedList< ElementType >::Empty(), TDoubleLinkedList< ElementType >::GetHead(), TDoubleLinkedList< ElementType >::GetTail(), FProperty::HasAnyPropertyFlags(), TArray< InElementType, InAllocatorType >::Insert(), TSharedPtr< ObjectType, InMode >::IsValid(), TArray< InElementType, InAllocatorType >::Reset(), and FEditPropertyChain::SetActiveMemberPropertyNode().
Referenced by GetRotation(), GetVectorComponent(), and OnRotationChanged().
GetRotation()
template<typename RotationType> TOptional< RotationType > FRigVMGraphMathTypeDetailCustomization::GetRotation (TSharedRef< class IPropertyHandle > InPropertyHandle) inline protected
Definition at line 609 of file RigVMGraphDetailCustomization.h.
References GetPropertyChain(), FPropertyAccess::Success, and Value.
Referenced by ExtendRotationArgs().
GetRotationPropertyName()
template<typename TransformType> FName FRigVMGraphMathTypeDetailCustomization::GetRotationPropertyName () inline static protected
Definition at line 677 of file RigVMGraphDetailCustomization.h.
References TEXT.
GetScalePropertyName() [1/2]
template<typename TransformType> FName FRigVMGraphMathTypeDetailCustomization::GetScalePropertyName () inline static protected
Definition at line 683 of file RigVMGraphDetailCustomization.h.
References TEXT.
GetScalePropertyName() [2/2]
template<> FName FRigVMGraphMathTypeDetailCustomization::GetScalePropertyName () inline static protected
Definition at line 811 of file RigVMGraphDetailCustomization.h.
References TEXT.
GetTranslationPropertyName() [1/2]
template<typename TransformType> FName FRigVMGraphMathTypeDetailCustomization::GetTranslationPropertyName () inline static protected
Definition at line 671 of file RigVMGraphDetailCustomization.h.
References TEXT.
GetTranslationPropertyName() [2/2]
template<> FName FRigVMGraphMathTypeDetailCustomization::GetTranslationPropertyName () inline static protected
Definition at line 805 of file RigVMGraphDetailCustomization.h.
References TEXT.
GetVectorComponent()
template<typename VectorType, typename NumericType> TOptional< NumericType > FRigVMGraphMathTypeDetailCustomization::GetVectorComponent (TSharedRef< class IPropertyHandle > InPropertyHandle, int32 InComponent) inline protected
Definition at line 534 of file RigVMGraphDetailCustomization.h.
References GetPropertyChain(), FPropertyAccess::Success, and Value.
Referenced by ExtendVectorArgs().
IsQuaternionBasedRotation() [1/3]
template<typename ValueType> bool FRigVMGraphMathTypeDetailCustomization::IsQuaternionBasedRotation () inline static protected
Definition at line 530 of file RigVMGraphDetailCustomization.h.
IsQuaternionBasedRotation() [2/3]
template<> bool FRigVMGraphMathTypeDetailCustomization::IsQuaternionBasedRotation () inline static protected
Definition at line 693 of file RigVMGraphDetailCustomization.h.
IsQuaternionBasedRotation() [3/3]
template<> bool FRigVMGraphMathTypeDetailCustomization::IsQuaternionBasedRotation () inline static protected
Definition at line 696 of file RigVMGraphDetailCustomization.h.
MakeInstance()
TSharedRef< IPropertyTypeCustomization > FRigVMGraphMathTypeDetailCustomization::MakeInstance () inline static
Definition at line 440 of file RigVMGraphDetailCustomization.h.
References FRigVMGraphMathTypeDetailCustomization(), and MakeShareable().
MakeRotationHeaderRow()
template<typename RotationType> void FRigVMGraphMathTypeDetailCustomization::MakeRotationHeaderRow (TSharedRef< class IPropertyHandle > InPropertyHandle, FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & StructCustomizationUtils) protected
MakeTransformChildren()
template<typename TransformType> void FRigVMGraphMathTypeDetailCustomization::MakeTransformChildren (TSharedRef< class IPropertyHandle > InPropertyHandle, IDetailChildrenBuilder & StructBuilder, IPropertyTypeCustomizationUtils & StructCustomizationUtils, TConstArrayView< FName > ComponentNames) protected
MakeTransformHeaderRow()
template<typename TransformType> void FRigVMGraphMathTypeDetailCustomization::MakeTransformHeaderRow (TSharedRef< class IPropertyHandle > InPropertyHandle, FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & StructCustomizationUtils, TConstArrayView< FName > ComponentNames) protected
MakeVectorHeaderRow()
template<typename VectorType, int32 NumberOfComponents> void FRigVMGraphMathTypeDetailCustomization::MakeVectorHeaderRow (TSharedRef< class IPropertyHandle > InPropertyHandle, FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & StructCustomizationUtils) protected
OnRotationChanged()
template<typename RotationType> void FRigVMGraphMathTypeDetailCustomization::OnRotationChanged (TSharedRef< class IPropertyHandle > InPropertyHandle, RotationType InValue, bool bIsCommit, ETextCommit::Type InCommitType = ETextCommit::Default) inline protected
Definition at line 634 of file RigVMGraphDetailCustomization.h.
References BlueprintBeingCustomized, GetPropertyChain(), GraphBeingCustomized, and TEXT.
Referenced by ExtendRotationArgs().
OnVectorComponentChanged()
template<typename VectorType, typename NumericType> void FRigVMGraphMathTypeDetailCustomization::OnVectorComponentChanged (TSharedRef< class IPropertyHandle > InPropertyHandle, int32 InComponent, NumericType InValue, bool bIsCommit, ETextCommit::Type InCommitType = ETextCommit::Default) inline protected
Definition at line 562 of file RigVMGraphDetailCustomization.h.
References BlueprintBeingCustomized, GraphBeingCustomized, and TEXT.
Referenced by ExtendVectorArgs().
Field Documentation
BlueprintBeingCustomized
TWeakObjectPtr<URigVMBlueprint> FRigVMGraphMathTypeDetailCustomization::BlueprintBeingCustomized protected
Definition at line 688 of file RigVMGraphDetailCustomization.h.
Referenced by OnRotationChanged(), and OnVectorComponentChanged().
GraphBeingCustomized
TWeakObjectPtr<URigVMGraph> FRigVMGraphMathTypeDetailCustomization::GraphBeingCustomized protected
Definition at line 689 of file RigVMGraphDetailCustomization.h.
Referenced by OnRotationChanged(), and OnVectorComponentChanged().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Editor/RigVMGraphDetailCustomization.h