Unreal Engine 5.6 C++ API: TPromise< ResultType > Class Template Reference
TPromise< ResultType > Class Template Reference
Template for promises.
#include "Future.h"
Public Member Functions
TPromise ()
Default constructor (creates a new shared state).
TPromise (const TPromise &Other)=delete
TPromise (TPromise &&Other)=default
TPromise (TUniqueFunction< void()> &&CompletionCallback)
Create and initialize a new instance with a callback.
~TPromise ()
Destructor.
template<typename... ArgTypes>
void EmplaceValue (ArgTypes &&... Args)
Sets the promised result.
TFuture< ResultType > GetFuture ()
Gets a TFuture object associated with the shared state of this promise.
TPromise & operator= (const TPromise &Other)=delete
TPromise & operator= (TPromise &&Other)=default
template<typename DummyResultType = ResultType UE_REQUIRES(std::is_void_v<DummyResultType>)>
FORCEINLINE void SetValue ()
template<typename DummyResultType = ResultType UE_REQUIRES(!std::is_void_v<DummyResultType>)>
FORCEINLINE void SetValue (const SetType &Result)
Sets the promised result.
template<typename DummyResultType = ResultType UE_REQUIRES(!std::is_void_v<DummyResultType> && !std::is_lvalue_reference_v<DummyResultType>)>
FORCEINLINE void SetValue (SetType &&Result)
Protected Member Functions
const TSharedPtr< StateType > & GetState ()
Gets the shared state object.
Private Types
using SetType = std::conditional_t<std::is_void_v<ResultType>, int, ResultType>
using StateType = TFutureState<ResultType>
Private Attributes
bool bFutureRetrieved = false
Whether a future has already been retrieved from this promise.
TSharedPtr< StateType > State
Holds the shared state object.
Detailed Description
template<typename ResultType>
class TPromise< ResultType >
Template for promises.
Definition at line 555 of file Future.h.
Member Typedef Documentation
SetType
template<typename ResultType> using TPromise< ResultType >::SetType = std::conditional_t<std::is_void_v<ResultType>, int, ResultType> private
Definition at line 560 of file Future.h.
StateType
template<typename ResultType> using TPromise< ResultType >::StateType = TFutureState<ResultType> private
Definition at line 557 of file Future.h.
Constructor & Destructor Documentation
TPromise() [1/4]
template<typename ResultType> TPromise< ResultType >::TPromise () inline
Default constructor (creates a new shared state).
Definition at line 565 of file Future.h.
References MakeShared(), and State.
Referenced by TPromise(), TPromise(), operator=(), and operator=().
TPromise() [2/4]
template<typename ResultType> TPromise< ResultType >::TPromise (TUniqueFunction< void()> && CompletionCallback) inline
Create and initialize a new instance with a callback.
Parameters
CompletionCallback A function that is called when the future state is completed.
Definition at line 575 of file Future.h.
References MakeShared(), MoveTemp(), and State.
TPromise() [3/4]
template<typename ResultType> TPromise< ResultType >::TPromise (TPromise< ResultType > && Other) default
References TPromise(), and Other.
TPromise() [4/4]
template<typename ResultType> TPromise< ResultType >::TPromise (const TPromise< ResultType > & Other) delete
References TPromise(), and Other.
~TPromise()
template<typename ResultType> TPromise< ResultType >::~TPromise () inline
Destructor.
Definition at line 587 of file Future.h.
References check, and State.
Member Function Documentation
EmplaceValue()
template<typename ResultType> template<typename... ArgTypes> void TPromise< ResultType >::EmplaceValue (ArgTypes &&... Args) inline
Sets the promised result.
The result must be set only once. An assertion will be triggered if this method is called a second time.
Parameters
Args The arguments to forward to the constructor of the result.
Definition at line 667 of file Future.h.
References Forward(), and GetState().
Referenced by MakeFulfilledPromise(), SetValue(), SetValue(), and SetValue().
GetFuture()
template<typename ResultType> TFuture< ResultType > TPromise< ResultType >::GetFuture () inline
Gets a TFuture object associated with the shared state of this promise.
Returns
The TFuture object.
Definition at line 602 of file Future.h.
References bFutureRetrieved, check, and GetState().
Referenced by TAsyncResult< ResultType >::TAsyncResult(), Async(), AsyncPool(), AsyncThread(), and TFutureBase< ResultType >::Then().
GetState()
template<typename ResultType> const TSharedPtr< StateType > & TPromise< ResultType >::GetState () inline protected
Gets the shared state object.
Returns
The shared state object.
Definition at line 678 of file Future.h.
References check, and State.
Referenced by EmplaceValue(), and GetFuture().
operator=() [1/2]
template<typename ResultType> TPromise & TPromise< ResultType >::operator= (const TPromise< ResultType > & Other) delete
References TPromise(), and Other.
operator=() [2/2]
template<typename ResultType> TPromise & TPromise< ResultType >::operator= (TPromise< ResultType > && Other) default
References TPromise(), and Other.
SetValue() [1/3]
template<typename ResultType> template<typename DummyResultType = ResultType UE_REQUIRES(std::is_void_v<DummyResultType>)> FORCEINLINE void TPromise< ResultType >::SetValue () inline
Definition at line 650 of file Future.h.
References EmplaceValue(), and FORCEINLINE.
SetValue() [2/3]
template<typename ResultType> template<typename DummyResultType = ResultType UE_REQUIRES(!std::is_void_v<DummyResultType>)> FORCEINLINE void TPromise< ResultType >::SetValue (const SetType & Result) inline
Sets the promised result.
The result must be set only once. An assertion will be triggered if this method is called a second time.
Parameters
Result The result value to set.
Definition at line 624 of file Future.h.
References EmplaceValue(), and FORCEINLINE.
Referenced by TAsyncResult< ResultType >::TAsyncResult(), Async(), AsyncThread(), SetPromise(), SetPromise(), FutureDetail::SetPromiseValue(), and FutureDetail::SetPromiseValue().
SetValue() [3/3]
template<typename ResultType> template<typename DummyResultType = ResultType UE_REQUIRES(!std::is_void_v<DummyResultType> && !std::is_lvalue_reference_v<DummyResultType>)> FORCEINLINE void TPromise< ResultType >::SetValue (SetType && Result) inline
Definition at line 637 of file Future.h.
References EmplaceValue(), FORCEINLINE, and MoveTemp().
Field Documentation
bFutureRetrieved
template<typename ResultType> bool TPromise< ResultType >::bFutureRetrieved = false private
Whether a future has already been retrieved from this promise.
Definition at line 692 of file Future.h.
Referenced by GetFuture().
State
template<typename ResultType> TSharedPtr<StateType> TPromise< ResultType >::State private
Holds the shared state object.
Definition at line 689 of file Future.h.
Referenced by TPromise(), TPromise(), ~TPromise(), and GetState().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/Future.h