Unreal Engine 5.6 C++ API: FAutoConsoleCommand Class Reference
FAutoConsoleCommand Class Reference
Autoregistering console command.
#include "IConsoleManager.h"
Public Member Functions
FAutoConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandDelegate &Command, uint32 Flags=ECVF_Default)
Register a console command that takes no arguments.
FAutoConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithArgsAndOutputDeviceDelegate &Command, uint32 Flags=ECVF_Default)
Register a console command that takes an output device.
FAutoConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithArgsDelegate &Command, uint32 Flags=ECVF_Default)
Register a console command that takes arguments.
FAutoConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithOutputDeviceDelegate &Command, uint32 Flags=ECVF_Default)
Register a console command that takes an output device.
FAutoConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithWorldArgsAndOutputDeviceDelegate &Command, uint32 Flags=ECVF_Default)
Register a console command that takes arguments, a world argument and an output device.
FAutoConsoleCommand (const TCHAR *Name, const TCHAR *Help, const FConsoleCommandWithWorldDelegate &Command, uint32 Flags=ECVF_Default)
Register a console command that takes a world argument.
Additional Inherited Members
Private Member Functions inherited from FAutoConsoleObject
virtual ~FAutoConsoleObject ()
Destructor, removes the console object.
FORCEINLINE IConsoleVariable * AsVariable ()
returns the contained console object as an IConsoleVariable
FORCEINLINE const IConsoleVariable * AsVariable () const
returns the contained console object as an IConsoleVariable
FAutoConsoleObject (IConsoleObject *InTarget)
Constructor, saves the argument for future removal from the console variable system.
Static Private Member Functions inherited from FAutoConsoleObject
static TArray< const FAutoConsoleObject * > & AccessDesktopShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessGeneralShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessMobileShaderChangeCvars ()
Detailed Description
Autoregistering console command.
Definition at line 1987 of file IConsoleManager.h.
Constructor & Destructor Documentation
FAutoConsoleCommand() [1/6]
FAutoConsoleCommand::FAutoConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandDelegate & Command, uint32 Flags = ECVF_Default) inline
Register a console command that takes no arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
Definition at line 1998 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleCommand() [2/6]
FAutoConsoleCommand::FAutoConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithArgsDelegate & Command, uint32 Flags = ECVF_Default) inline
Register a console command that takes arguments.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
Definition at line 2011 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleCommand() [3/6]
FAutoConsoleCommand::FAutoConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithOutputDeviceDelegate & Command, uint32 Flags = ECVF_Default) inline
Register a console command that takes an output device.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
Definition at line 2024 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleCommand() [4/6]
FAutoConsoleCommand::FAutoConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithArgsAndOutputDeviceDelegate & Command, uint32 Flags = ECVF_Default) inline
Register a console command that takes an output device.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
Definition at line 2037 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleCommand() [5/6]
FAutoConsoleCommand::FAutoConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithWorldDelegate & Command, uint32 Flags = ECVF_Default) inline
Register a console command that takes a world argument.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
Definition at line 2050 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleCommand() [6/6]
FAutoConsoleCommand::FAutoConsoleCommand (const TCHAR * Name, const TCHAR * Help, const FConsoleCommandWithWorldArgsAndOutputDeviceDelegate & Command, uint32 Flags = ECVF_Default) inline
Register a console command that takes arguments, a world argument and an output device.
Parameters
Name The name of this command (must not be nullptr)
Help Help text for this command
Command The user function to call when this command is executed
Flags Optional flags bitmask
Definition at line 2063 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h