Unreal Engine 5.6 C++ API: FLinkerInstancingContext Class Reference
FLinkerInstancingContext Class Reference
Helper class to remap package imports during loading.
#include "LinkerInstancingContext.h"
Public Member Functions
FLinkerInstancingContext ()
FLinkerInstancingContext (bool bInSoftObjectPathRemappingEnabled)
FLinkerInstancingContext (TSet< FName > InTags)
void AddPackageMapping (FName Original, FName Instanced)
Add a mapping from a package name to a new package name.
void AddPackageMappingFunc (TFunction< FName(FName)> InInstancedPackageMapFunc)
Add a mapping function from a package name to a new package name.
void AddPathMapping (FSoftObjectPath Original, FSoftObjectPath Instanced)
Add a mapping from a top level asset path (/Path/To/Package.AssetName) to another.
void AddTag (FName NewTag)
void AppendTags (const TSet< FName > &NewTags)
void FixupSoftObjectPath (FSoftObjectPath &InOutSoftObjectPath) const
bool GetSoftObjectPathRemappingEnabled () const
bool HasTag (FName Tag) const
bool IsInstanced () const
FName RemapPackage (const FName &PackageName) const
Remap the package name from the import table to its instanced counterpart, otherwise return the name unmodified.
FSoftObjectPath RemapPath (const FSoftObjectPath &Path) const
Remap the top level asset part of the path name to its instanced counterpart, otherwise return the name unmodified.
void SetSoftObjectPathRemappingEnabled (bool bInSoftObjectPathRemappingEnabled)
UE_DEPRECATED (5.2, "No longer used, check ELoadFlags::LOAD_RegenerateBulkDataGuids in the LoadFlags instead") bool ShouldRegenerateUniqueBulkDataGuids() const
UE_DEPRECATED (5.2, "No longer used, pass ELoadFlags::LOAD_RegenerateBulkDataGuids to LoadPackage instead") void SetRegenerateUniqueBulkDataGuids(bool bFlag)
Static Public Member Functions
static FLinkerInstancingContext DuplicateContext (const FLinkerInstancingContext &InLinkerInstancingContext)
static FString GetInstancedPackageName (const FString &InOuterPackageName, const FString &InPackageName)
Return the instanced package name for a given instanced outer package and an object package name.
static FName GetInstancedPackageName (FName InOuterPackageName, FName InPackageName)
Private Member Functions
void BuildPackageMapping (FName Original, FName Instanced)
void EnableAutomationTest ()
bool FindPackageMapping (FName Original, FName &Instanced) const
Private Attributes
TSharedPtr< FSharedLinkerInstancingContextData > SharedData
Friends
struct FAsyncPackage2
class FLinkerInstancingContextTests
class FLinkerLoad
Detailed Description
Helper class to remap package imports during loading.
This is usually when objects in a package are outer-ed to object in another package or vice versa. Instancing such a package without a instance remapping would resolve imports to the original package which is not desirable in an instancing context (i.e. loading a level instance) This is because an instanced package has a different name than the package file name on disk, this class is used in the linker to remaps reference to the package name as stored in import tables on disk to the corresponding instanced package or packages we are loading.
Definition at line 98 of file LinkerInstancingContext.h.
Constructor & Destructor Documentation
FLinkerInstancingContext() [1/3]
FLinkerInstancingContext::FLinkerInstancingContext ()
Referenced by DuplicateContext().
FLinkerInstancingContext() [2/3]
FLinkerInstancingContext::FLinkerInstancingContext (TSet< FName > InTags) explicit
FLinkerInstancingContext() [3/3]
FLinkerInstancingContext::FLinkerInstancingContext (bool bInSoftObjectPathRemappingEnabled) explicit
Member Function Documentation
AddPackageMapping()
void FLinkerInstancingContext::AddPackageMapping (FName Original, FName Instanced)
Add a mapping from a package name to a new package name.
There should be no separators (. or :) in these strings.
Referenced by FExternalPackageHelper::LoadObjectsFromExternalPackages().
AddPackageMappingFunc()
void FLinkerInstancingContext::AddPackageMappingFunc (TFunction< FName(FName)> InInstancedPackageMapFunc)
Add a mapping function from a package name to a new package name.
This function should be thread-safe, as it can be invoked from ALT.
AddPathMapping()
void FLinkerInstancingContext::AddPathMapping (FSoftObjectPath Original, FSoftObjectPath Instanced)
Add a mapping from a top level asset path (/Path/To/Package.AssetName) to another.
AddTag()
void FLinkerInstancingContext::AddTag (FName NewTag)
AppendTags()
void FLinkerInstancingContext::AppendTags (const TSet< FName > & NewTags)
BuildPackageMapping()
void FLinkerInstancingContext::BuildPackageMapping (FName Original, FName Instanced) private
DuplicateContext()
FLinkerInstancingContext FLinkerInstancingContext::DuplicateContext (const FLinkerInstancingContext & InLinkerInstancingContext) static
References FLinkerInstancingContext().
EnableAutomationTest()
void FLinkerInstancingContext::EnableAutomationTest () private
FindPackageMapping()
bool FLinkerInstancingContext::FindPackageMapping (FName Original, FName & Instanced) const private
FixupSoftObjectPath()
void FLinkerInstancingContext::FixupSoftObjectPath (FSoftObjectPath & InOutSoftObjectPath) const
GetInstancedPackageName() [1/2]
FString FLinkerInstancingContext::GetInstancedPackageName (const FString & InOuterPackageName, const FString & InPackageName) inline static
Return the instanced package name for a given instanced outer package and an object package name.
Definition at line 140 of file LinkerInstancingContext.h.
References TEXT.
Referenced by GetInstancedPackageName().
GetInstancedPackageName() [2/2]
FName FLinkerInstancingContext::GetInstancedPackageName (FName InOuterPackageName, FName InPackageName) inline static
Definition at line 145 of file LinkerInstancingContext.h.
References GetInstancedPackageName(), and FName::ToString().
GetSoftObjectPathRemappingEnabled()
bool FLinkerInstancingContext::GetSoftObjectPathRemappingEnabled () const
HasTag()
bool FLinkerInstancingContext::HasTag (FName Tag) const
IsInstanced()
bool FLinkerInstancingContext::IsInstanced () const
RemapPackage()
FName FLinkerInstancingContext::RemapPackage (const FName & PackageName) const
Remap the package name from the import table to its instanced counterpart, otherwise return the name unmodified.
References PackageName.
Referenced by FExternalPackageHelper::LoadObjectsFromExternalPackages().
RemapPath()
FSoftObjectPath FLinkerInstancingContext::RemapPath (const FSoftObjectPath & Path) const
Remap the top level asset part of the path name to its instanced counterpart, otherwise return the name unmodified.
i.e. remaps /Path/To/Package.AssetName:Inner to /NewPath/To/NewPackage.NewAssetName:Inner
References Path.
SetSoftObjectPathRemappingEnabled()
void FLinkerInstancingContext::SetSoftObjectPathRemappingEnabled (bool bInSoftObjectPathRemappingEnabled)
UE_DEPRECATED() [1/2]
FLinkerInstancingContext::UE_DEPRECATED (5. 2, "No longer used, check ELoadFlags::LOAD_RegenerateBulkDataGuids in the LoadFlags instead") const inline
Definition at line 136 of file LinkerInstancingContext.h.
References bool.
UE_DEPRECATED() [2/2]
FLinkerInstancingContext::UE_DEPRECATED (5. 2, "No longer used, pass ELoadFlags::LOAD_RegenerateBulkDataGuids to LoadPackage instead") inline
Definition at line 133 of file LinkerInstancingContext.h.
Friends And Related Symbol Documentation
FAsyncPackage2
friend struct FAsyncPackage2 friend
Definition at line 158 of file LinkerInstancingContext.h.
References FAsyncPackage2.
Referenced by FAsyncPackage2.
FLinkerInstancingContextTests
friend class FLinkerInstancingContextTests friend
Definition at line 159 of file LinkerInstancingContext.h.
References FLinkerInstancingContextTests.
Referenced by FLinkerInstancingContextTests.
FLinkerLoad
friend class FLinkerLoad friend
Definition at line 157 of file LinkerInstancingContext.h.
References FLinkerLoad.
Referenced by FLinkerLoad.
Field Documentation
SharedData
TSharedPtr<FSharedLinkerInstancingContextData> FLinkerInstancingContext::SharedData private
Definition at line 162 of file LinkerInstancingContext.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/LinkerInstancingContext.h