Unreal Engine 5.6 C++ API: FMeshVertexChangeBuilder Class Reference
FMeshVertexChangeBuilder Class Reference
FMeshVertexChangeBuilder can be used to construct a FMeshVertexChange.
#include "MeshVertexChange.h"
Public Member Functions
GEOMETRYFRAMEWORK_API FMeshVertexChangeBuilder ()
GEOMETRYFRAMEWORK_API FMeshVertexChangeBuilder (EMeshVertexChangeComponents Components)
GEOMETRYFRAMEWORK_API void SaveOverlayNormals (const FDynamicMesh3 *Mesh, const TArray< int32 > &ElementIDs, bool bInitial)
GEOMETRYFRAMEWORK_API void SaveOverlayNormals (const FDynamicMesh3 *Mesh, const TSet< int32 > &ElementIDs, bool bInitial)
GEOMETRYFRAMEWORK_API void SaveOverlayUVs (const FDynamicMesh3 *Mesh, const TArray< int32 > &ElementIDs, bool bInitial)
GEOMETRYFRAMEWORK_API void SaveOverlayUVs (const FDynamicMesh3 *Mesh, const TSet< int32 > &ElementIDs, bool bInitial)
GEOMETRYFRAMEWORK_API void SaveVertexFinal (const FDynamicMesh3 *Mesh, int32 VertexID)
GEOMETRYFRAMEWORK_API void SaveVertexInitial (const FDynamicMesh3 *Mesh, int32 VertexID)
template<typename Enumerable>
void SaveVertices (const FDynamicMesh3 *Mesh, Enumerable Enum, bool bInitial)
GEOMETRYFRAMEWORK_API void UpdateVertex (int32 VertexID, const FVector3d &OldPosition, const FVector3d &NewPosition)
GEOMETRYFRAMEWORK_API void UpdateVertexColor (int32 VertexID, const FVector3f &OldColor, const FVector3f &NewColor)
Data Fields
bool bSaveColors = false
bool bSaveOverlayNormals = false
bool bSaveOverlayUVs = false
bool bSavePositions = true
TUniquePtr< FMeshVertexChange > Change
TUniqueFunction< void(int32, int32)> OnNewVertexSaved = nullptr
If set, this function is called whenever a newly-seen VertexID is saved, parameters are (VertexID, Index) into saved-vertices array.
TMap< int32, int32 > SavedNormalElements
TMap< int32, int32 > SavedUVElements
TMap< int32, int32 > SavedVertices
Protected Member Functions
GEOMETRYFRAMEWORK_API void UpdateOverlayNormal (int32 ElementID, const FVector3f &OldNormal, const FVector3f &NewNormal)
GEOMETRYFRAMEWORK_API void UpdateOverlayNormalFinal (int32 ElementID, const FVector3f &NewNormal)
GEOMETRYFRAMEWORK_API void UpdateOverlayUV (int32 ElementID, const FVector2f &OldUV, const FVector2f &NewUV)
GEOMETRYFRAMEWORK_API void UpdateOverlayUVFinal (int32 ElementID, const FVector2f &NewUV)
GEOMETRYFRAMEWORK_API void UpdateVertexFinal (int32 VertexID, const FVector3d &NewPosition)
Detailed Description
FMeshVertexChangeBuilder can be used to construct a FMeshVertexChange.
Definition at line 70 of file MeshVertexChange.h.
Constructor & Destructor Documentation
FMeshVertexChangeBuilder() [1/2]
GEOMETRYFRAMEWORK_API FMeshVertexChangeBuilder::FMeshVertexChangeBuilder ()
FMeshVertexChangeBuilder() [2/2]
GEOMETRYFRAMEWORK_API FMeshVertexChangeBuilder::FMeshVertexChangeBuilder (EMeshVertexChangeComponents Components) explicit
References Components.
Member Function Documentation
SaveOverlayNormals() [1/2]
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::SaveOverlayNormals (const FDynamicMesh3 * Mesh, const TArray< int32 > & ElementIDs, bool bInitial)
References Mesh.
SaveOverlayNormals() [2/2]
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::SaveOverlayNormals (const FDynamicMesh3 * Mesh, const TSet< int32 > & ElementIDs, bool bInitial)
References Mesh.
SaveOverlayUVs() [1/2]
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::SaveOverlayUVs (const FDynamicMesh3 * Mesh, const TArray< int32 > & ElementIDs, bool bInitial)
References Mesh.
SaveOverlayUVs() [2/2]
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::SaveOverlayUVs (const FDynamicMesh3 * Mesh, const TSet< int32 > & ElementIDs, bool bInitial)
References Mesh.
SaveVertexFinal()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::SaveVertexFinal (const FDynamicMesh3 * Mesh, int32 VertexID)
References Enum, and Mesh.
Referenced by SaveVertices().
SaveVertexInitial()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::SaveVertexInitial (const FDynamicMesh3 * Mesh, int32 VertexID)
References Mesh.
Referenced by SaveVertices().
SaveVertices()
template<typename Enumerable> void FMeshVertexChangeBuilder::SaveVertices (const FDynamicMesh3 * Mesh, Enumerable Enum, bool bInitial)
Definition at line 141 of file MeshVertexChange.h.
References Enum, Mesh, SaveVertexFinal(), and SaveVertexInitial().
UpdateOverlayNormal()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateOverlayNormal (int32 ElementID, const FVector3f & OldNormal, const FVector3f & NewNormal) protected
UpdateOverlayNormalFinal()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateOverlayNormalFinal (int32 ElementID, const FVector3f & NewNormal) protected
UpdateOverlayUV()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateOverlayUV (int32 ElementID, const FVector2f & OldUV, const FVector2f & NewUV) protected
UpdateOverlayUVFinal()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateOverlayUVFinal (int32 ElementID, const FVector2f & NewUV) protected
UpdateVertex()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateVertex (int32 VertexID, const FVector3d & OldPosition, const FVector3d & NewPosition)
UpdateVertexColor()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateVertexColor (int32 VertexID, const FVector3f & OldColor, const FVector3f & NewColor)
UpdateVertexFinal()
GEOMETRYFRAMEWORK_API void FMeshVertexChangeBuilder::UpdateVertexFinal (int32 VertexID, const FVector3d & NewPosition) protected
Field Documentation
bSaveColors
bool FMeshVertexChangeBuilder::bSaveColors = false
Definition at line 76 of file MeshVertexChange.h.
bSaveOverlayNormals
bool FMeshVertexChangeBuilder::bSaveOverlayNormals = false
Definition at line 78 of file MeshVertexChange.h.
bSaveOverlayUVs
bool FMeshVertexChangeBuilder::bSaveOverlayUVs = false
Definition at line 81 of file MeshVertexChange.h.
bSavePositions
bool FMeshVertexChangeBuilder::bSavePositions = true
Definition at line 75 of file MeshVertexChange.h.
Change
TUniquePtr<FMeshVertexChange> FMeshVertexChangeBuilder::Change
Definition at line 73 of file MeshVertexChange.h.
OnNewVertexSaved
TUniqueFunction<void(int32, int32)> FMeshVertexChangeBuilder::OnNewVertexSaved = nullptr
If set, this function is called whenever a newly-seen VertexID is saved, parameters are (VertexID, Index) into saved-vertices array.
Definition at line 85 of file MeshVertexChange.h.
SavedNormalElements
TMap<int32, int32> FMeshVertexChangeBuilder::SavedNormalElements
Definition at line 79 of file MeshVertexChange.h.
SavedUVElements
TMap<int32, int32> FMeshVertexChangeBuilder::SavedUVElements
Definition at line 82 of file MeshVertexChange.h.
SavedVertices
TMap<int32, int32> FMeshVertexChangeBuilder::SavedVertices
Definition at line 74 of file MeshVertexChange.h.
The documentation for this class was generated from the following file:
Runtime/GeometryFramework/Public/Changes/MeshVertexChange.h