Unreal Engine 5.6 C++ API: FNetworkPredictionModelDefRegistry Class Reference
FNetworkPredictionModelDefRegistry Class Reference
#include "NetworkPredictionModelDefRegistry.h"
Data Structures
struct FTypeInfo
Public Member Functions
void FinalizeTypes ()
template<typename ModelDef>
void RegisterType ()
Static Public Member Functions
static FNetworkPredictionModelDefRegistry & Get ()
Private Attributes
bool bFinalized = false
TArray< FTypeInfo > ModelDefList
Static Private Attributes
static NETWORKPREDICTION_API FNetworkPredictionModelDefRegistry Singleton
Detailed Description
Definition at line 12 of file NetworkPredictionModelDefRegistry.h.
Member Function Documentation
FinalizeTypes()
void FNetworkPredictionModelDefRegistry::FinalizeTypes () inline
Definition at line 41 of file NetworkPredictionModelDefRegistry.h.
References bFinalized, Count, Log, ModelDefList, FNetworkPredictionModelDefRegistry::FTypeInfo::Name, npEnsureMsgf, FNetworkPredictionModelDefRegistry::FTypeInfo::SortPriority, TCString< TCHAR >::Strcmp(), TEXT, and UE_LOG.
Get()
FNetworkPredictionModelDefRegistry & FNetworkPredictionModelDefRegistry::Get () inline static
Definition at line 16 of file NetworkPredictionModelDefRegistry.h.
References Singleton.
Referenced by TNetworkPredictionModelDefRegisterHelper< ModelDef >::TNetworkPredictionModelDefRegisterHelper().
RegisterType()
template<typename ModelDef> void FNetworkPredictionModelDefRegistry::RegisterType () inline
Definition at line 22 of file NetworkPredictionModelDefRegistry.h.
References bFinalized, ModelDefList, and npEnsure.
Referenced by TNetworkPredictionModelDefRegisterHelper< ModelDef >::TNetworkPredictionModelDefRegisterHelper().
Field Documentation
bFinalized
bool FNetworkPredictionModelDefRegistry::bFinalized = false private
Definition at line 87 of file NetworkPredictionModelDefRegistry.h.
Referenced by FinalizeTypes(), and RegisterType().
ModelDefList
TArray<FTypeInfo> FNetworkPredictionModelDefRegistry::ModelDefList private
Definition at line 85 of file NetworkPredictionModelDefRegistry.h.
Referenced by FinalizeTypes(), and RegisterType().
Singleton
NETWORKPREDICTION_API FNetworkPredictionModelDefRegistry FNetworkPredictionModelDefRegistry::Singleton static private
Definition at line 71 of file NetworkPredictionModelDefRegistry.h.
Referenced by Get().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionModelDefRegistry.h