Unreal Engine 5.6 C++ API: FScopedJavaObject< T > Class Template Reference
FScopedJavaObject< T > Class Template Reference
#include "AndroidJavaEnv.h"
Public Member Functions
FScopedJavaObject ()
FScopedJavaObject (const FScopedJavaObject &Other)=delete
FScopedJavaObject (FScopedJavaObject &&Other)
FScopedJavaObject (JNIEnv *InEnv, const T &InObjRef)
~FScopedJavaObject ()
operator bool () const
T operator* () const
FScopedJavaObject & operator= (const FScopedJavaObject &Other)=delete
FScopedJavaObject & operator= (FScopedJavaObject &&Other)
Private Attributes
JNIEnv * Env = nullptr
T ObjRef = nullptr
Detailed Description
template<typename T>
class FScopedJavaObject< T >
Definition at line 25 of file AndroidJavaEnv.h.
Constructor & Destructor Documentation
FScopedJavaObject() [1/4]
template<typename T> FScopedJavaObject< T >::FScopedJavaObject () inline
Definition at line 28 of file AndroidJavaEnv.h.
Referenced by FScopedJavaObject(), FScopedJavaObject(), operator=(), and operator=().
FScopedJavaObject() [2/4]
template<typename T> FScopedJavaObject< T >::FScopedJavaObject (JNIEnv * InEnv, const T & InObjRef) inline
Definition at line 29 of file AndroidJavaEnv.h.
References Env, and ObjRef.
FScopedJavaObject() [3/4]
template<typename T> FScopedJavaObject< T >::FScopedJavaObject (FScopedJavaObject< T > && Other) inline
Definition at line 34 of file AndroidJavaEnv.h.
References FScopedJavaObject(), Env, ObjRef, and Other.
FScopedJavaObject() [4/4]
template<typename T> FScopedJavaObject< T >::FScopedJavaObject (const FScopedJavaObject< T > & Other) delete
References FScopedJavaObject(), and Other.
~FScopedJavaObject()
template<typename T> FScopedJavaObject< T >::~FScopedJavaObject () inline
Definition at line 52 of file AndroidJavaEnv.h.
References Env, and ObjRef.
Member Function Documentation
operator bool()
template<typename T> FScopedJavaObject< T >::operator bool () const inline
Definition at line 75 of file AndroidJavaEnv.h.
References Env, and ObjRef.
operator*()
template<typename T> T FScopedJavaObject< T >::operator* () const inline
Definition at line 73 of file AndroidJavaEnv.h.
References ObjRef.
operator=() [1/2]
template<typename T> FScopedJavaObject & FScopedJavaObject< T >::operator= (const FScopedJavaObject< T > & Other) delete
References FScopedJavaObject(), and Other.
operator=() [2/2]
template<typename T> FScopedJavaObject & FScopedJavaObject< T >::operator= (FScopedJavaObject< T > && Other) inline
Definition at line 45 of file AndroidJavaEnv.h.
References FScopedJavaObject(), Env, ObjRef, Other, and Swap.
Field Documentation
Env
template<typename T> JNIEnv* FScopedJavaObject< T >::Env = nullptr private
Definition at line 86 of file AndroidJavaEnv.h.
Referenced by FScopedJavaObject(), FScopedJavaObject(), ~FScopedJavaObject(), operator bool(), and operator=().
ObjRef
template<typename T> T FScopedJavaObject< T >::ObjRef = nullptr private
Definition at line 87 of file AndroidJavaEnv.h.
Referenced by FScopedJavaObject(), FScopedJavaObject(), ~FScopedJavaObject(), operator bool(), operator*(), and operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Android/AndroidJavaEnv.h