Unreal Engine 5.6 C++ API: FCbObject Class Reference
FCbObject Class Reference
An object that includes a shared buffer for the memory that contains it.
#include "CompactBinary.h"
Public Member Functions
FCbField AsField () &&
FCbField AsField () const &
Access the object as an object field.
FCbField Find (FUtf8StringView Name) const
Find a field by case-sensitive name comparison.
FCbField FindIgnoreCase (FUtf8StringView Name) const
Find a field by case-insensitive name comparison.
FCompositeBuffer GetBuffer () const
Returns a buffer that contains the object as it would be serialized by CopyTo.
FCbField operator[] (FUtf8StringView Name) const
Find a field by case-sensitive name comparison.
TCbBuffer ()=default
Construct a default value.
TCbBuffer (const ViewType &Value, FSharedBuffer OuterBuffer)
Construct a value that holds a reference to the buffer that contains it.
template<typename OtherViewType>
TCbBuffer (const ViewType &Value, TCbBuffer< OtherViewType > OuterBuffer)
Construct a value that holds a reference to the buffer of the outer that contains it.
TCbBuffer (FSharedBuffer ValueBuffer, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a value from a pointer to its data and an optional externally-provided type.
Public Member Functions inherited from TCbBuffer< FCbObjectView >
const FCbObjectView & AsView () const
Returns the value as a view.
FCbFieldIterator begin () const
DO NOT USE DIRECTLY.
FCbFieldIterator CreateIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
const FSharedBuffer & GetOuterBuffer () const &
Returns the outer buffer (if any) that contains this value.
bool IsOwned () const
Whether this reference has ownership of the memory in its buffer.
void MakeOwned ()
Clone the value, if necessary, to a buffer that this reference has ownership of.
FCbField operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
void Reset ()
Reset this to a default value and null buffer.
Public Member Functions inherited from FCbObjectView
FCbObjectView ()
Construct an object with no fields.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the object if serialized by itself with no name.
FCbFieldView AsFieldView () const
Access the object as an object field.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the object into an archive.
void CopyTo (FMutableMemoryView Buffer) const
Copy the object into a buffer of exactly GetSize() bytes, with no name.
FCbFieldViewIterator CreateViewIterator () const
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbObjectView &Other) const
Whether this object is identical to the other object.
constexpr FCbFieldView ()=default
FCbFieldView (const FCbValue &Value)
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
FCbFieldView FindView (FUtf8StringView Name) const
Find a field by case-sensitive name comparison.
FCbFieldView FindViewIgnoreCase (FUtf8StringView Name) const
Find a field by case-insensitive name comparison.
FIoHash GetHash () const
Calculate the hash of the object if serialized by itself with no name.
uint64 GetSize () const
Returns the size of the object in bytes if serialized by itself with no name.
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the object.
operator bool () const
Whether the object has any fields.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field by case-sensitive name comparison.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the object as it would be serialized, such as by CopyTo.
Additional Inherited Members
Static Public Member Functions inherited from FCbObjectView
static FCbObjectView FromFieldNoCheck (const FCbFieldView &Field)
Construct an object from an object field.
Static Public Member Functions inherited from TCbBufferFactory< FCbObject, FCbObjectView >
static FCbObject Clone (const void *const Data)
Construct a value from an owned clone of its memory.
static FCbObject MakeView (const void *const Data, FSharedBuffer OuterBuffer=FSharedBuffer())
Construct a value from a read-only view of its memory and its optional outer buffer.
Protected Member Functions inherited from FCbFieldView
void Assign (const void *InData, const ECbFieldType InType)
Assign a field from a pointer to its data and an optional externally-provided type.
constexpr ECbFieldType GetType () const
Returns the type of the field excluding flags.
constexpr ECbFieldType GetTypeWithFlags () const
Returns the type of the field including flags.
constexpr const void * GetValueData () const
Returns the start of the value.
const void * GetValueEnd () const
Returns the end of the value.
uint64 GetValueSize () const
Returns the size of the value in bytes, which is the field excluding the type and name.
FMemoryView GetValueView () const
Returns a view of the value, which excludes the type and name.
FMemoryView GetView () const
Returns a view of the field, including the type and name when present.
FMemoryView GetViewNoType () const
Returns a view of the name and value, which excludes the type.
constexpr FCbFieldView ()=default
Construct a field with no name and no value.
FCbFieldView (const FCbValue &Value)
Construct a field from a value, without access to the name.
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field from a pointer to its data and an optional externally-provided type.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the field, including the type and name.
FCbArrayView AsArrayView ()
Access the field as an array.
FIoHash AsAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an attachment.
FIoHash AsBinaryAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing a binary attachment.
FMemoryView AsBinaryView (FMemoryView Default=FMemoryView())
Access the field as binary.
bool AsBool (bool bDefault=false)
Access the field as a bool.
FMemoryView AsCustom (FUtf8StringView Name, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with a string identifier.
FMemoryView AsCustom (uint64 Id, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with an integer identifier.
FCbCustomById AsCustomById (FCbCustomById Default=FCbCustomById())
Access the field as a custom sub-type with an integer identifier.
FCbCustomByName AsCustomByName (FCbCustomByName Default=FCbCustomByName())
Access the field as a custom sub-type with a string identifier.
FDateTime AsDateTime ()
Access the field as a date/time.
FDateTime AsDateTime (FDateTime Default)
Access the field as a date/time.
int64 AsDateTimeTicks (int64 Default=0)
Access the field as a date/time tick count.
double AsDouble (double Default=0.0)
Access the field as a double.
float AsFloat (float Default=0.0f)
Access the field as a float.
FIoHash AsHash (const FIoHash &Default=FIoHash())
Access the field as a hash.
int16 AsInt16 (int16 Default=0)
Access the field as an int16.
int32 AsInt32 (int32 Default=0)
Access the field as an int32.
int64 AsInt64 (int64 Default=0)
Access the field as an int64.
int8 AsInt8 (int8 Default=0)
Access the field as an int8.
FIoHash AsObjectAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an object attachment.
FCbObjectId AsObjectId (const FCbObjectId &Default=FCbObjectId())
Access the field as an object identifier.
FCbObjectView AsObjectView ()
Access the field as an object.
FUtf8StringView AsString (FUtf8StringView Default=FUtf8StringView())
Access the field as a string.
FTimespan AsTimeSpan ()
Access the field as a timespan.
FTimespan AsTimeSpan (FTimespan Default)
Access the field as a timespan.
int64 AsTimeSpanTicks (int64 Default=0)
Access the field as a timespan tick count.
uint16 AsUInt16 (uint16 Default=0)
Access the field as a uint16.
uint32 AsUInt32 (uint32 Default=0)
Access the field as a uint32.
uint64 AsUInt64 (uint64 Default=0)
Access the field as a uint64.
uint8 AsUInt8 (uint8 Default=0)
Access the field as a uint8.
FGuid AsUuid ()
Access the field as a UUID.
FGuid AsUuid (const FGuid &Default)
Access the field as a UUID.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the field into an archive, including its type and name.
void CopyTo (FMutableMemoryView Buffer) const
Copy the field into a buffer of exactly GetSize() bytes, including the type and name.
FCbFieldViewIterator CreateViewIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbFieldView &Other) const
Whether this field is identical to the other field.
constexpr ECbFieldError GetError () const
The type of error that occurred on the last field access, or None.
FIoHash GetHash () const
Calculate the hash of the field, including the type and name.
constexpr FUtf8StringView GetName () const
Returns the name of the field if it has a name, otherwise an empty view.
uint64 GetSize () const
Returns the size of the field in bytes, including the type and name.
FCbValue GetValue () const
Returns the value for unchecked access.
constexpr bool HasError () const
Whether the last field access encountered an error.
constexpr bool HasName () const
True if the field has a name.
constexpr bool HasValue () const
Whether the field has a value.
constexpr bool IsArray () const
constexpr bool IsAttachment () const
constexpr bool IsBinary () const
constexpr bool IsBinaryAttachment () const
constexpr bool IsBool () const
constexpr bool IsCustomById () const
constexpr bool IsCustomByName () const
constexpr bool IsDateTime () const
constexpr bool IsFloat () const
Whether the field is a float, or integer that supports implicit conversion.
constexpr bool IsHash () const
constexpr bool IsInteger () const
Whether the field is an integer of unspecified range and sign.
constexpr bool IsNull () const
constexpr bool IsObject () const
constexpr bool IsObjectAttachment () const
constexpr bool IsObjectId () const
constexpr bool IsString () const
constexpr bool IsTimeSpan () const
constexpr bool IsUuid () const
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field.
constexpr operator bool () const
Whether the field has a value.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
constexpr FCbFieldView RemoveName () const
Returns a copy of the field with the name removed.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the field as it would be serialized, such as by CopyTo.
Detailed Description
An object that includes a shared buffer for the memory that contains it.
See also
FCbObjectView
TCbBuffer
Definition at line 1391 of file CompactBinary.h.
Member Function Documentation
AsField() [1/2]
FCbField FCbObject::AsField () && inline nodiscard
Definition at line 1421 of file CompactBinary.h.
References FCbObjectView::AsFieldView(), and MoveTemp().
AsField() [2/2]
FCbField FCbObject::AsField () const & inline nodiscard
Access the object as an object field.
Definition at line 1420 of file CompactBinary.h.
References FCbObjectView::AsFieldView().
Find()
FCbField FCbObject::Find (FUtf8StringView Name) const inline nodiscard
Find a field by case-sensitive name comparison.
Definition at line 1397 of file CompactBinary.h.
References FCbObjectView::FindView(), and Name.
FindIgnoreCase()
FCbField FCbObject::FindIgnoreCase (FUtf8StringView Name) const inline nodiscard
Find a field by case-insensitive name comparison.
Definition at line 1407 of file CompactBinary.h.
References FCbObjectView::FindViewIgnoreCase(), and Name.
GetBuffer()
FCompositeBuffer FCbObject::GetBuffer () const nodiscard
Returns a buffer that contains the object as it would be serialized by CopyTo.
operator[]()
FCbField FCbObject::operator[] (FUtf8StringView Name) const inline nodiscard
Find a field by case-sensitive name comparison.
Definition at line 1417 of file CompactBinary.h.
References Find, and Name.
TCbBuffer() [1/4]
TCbBuffer< ViewType >::TCbBuffer () default
Construct a default value.
TCbBuffer() [2/4]
TCbBuffer< ViewType >::TCbBuffer (const ViewType & Value, FSharedBuffer OuterBuffer) inline
Construct a value that holds a reference to the buffer that contains it.
Definition at line 1135 of file CompactBinary.h.
TCbBuffer() [3/4]
template<typename OtherViewType> TCbBuffer< ViewType >::TCbBuffer (const ViewType & Value, TCbBuffer< OtherViewType > OuterBuffer) inline
Construct a value that holds a reference to the buffer of the outer that contains it.
Definition at line 1147 of file CompactBinary.h.
TCbBuffer() [4/4]
TCbBuffer< ViewType >::TCbBuffer (FSharedBuffer ValueBuffer, ECbFieldType Type = ECbFieldType::HasFieldType) inline explicit
Construct a value from a pointer to its data and an optional externally-provided type.
Parameters
ValueBuffer A buffer that exactly contains the value.
Type HasFieldType means that ValueBuffer contains the type. Otherwise, use the given type.
Definition at line 1124 of file CompactBinary.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinary.h