Unreal Engine 5.6 C++ API: FGenericSaveGameSystem Class Reference
FGenericSaveGameSystem Class Reference
A generic save game system that just uses IFileManager to save/load with normal files.
#include "SaveGameSystem.h"
Public Member Functions
virtual bool DeleteGame (bool bAttemptToUseUI, const TCHAR *Name, const int32 UserIndex) override
Delete an existing save game, blocking until complete.
virtual bool DoesSaveGameExist (const TCHAR *Name, const int32 UserIndex) override
Return true if the named savegame exists (probably not useful with NativeUI.
virtual ESaveExistsResult DoesSaveGameExistWithResult (const TCHAR *Name, const int32 UserIndex) override
Similar to DoesSaveGameExist, except returns a result code with more information.
virtual bool DoesSaveSystemSupportMultipleUsers () override
Some save systems don't support more than one user, in those cases the game needs to avoid saving settings for anyone but the primary user.
virtual bool GetSaveGameNames (TArray< FString > &FoundSaves, const int32 UserIndex) override
Gets a list of all known saves.
virtual bool LoadGame (bool bAttemptToUseUI, const TCHAR *Name, const int32 UserIndex, TArray< uint8 > &Data) override
Loads the game, blocking until complete.
virtual bool PlatformHasNativeUI () override
Returns true if the platform has a native UI (like many consoles)
virtual bool SaveGame (bool bAttemptToUseUI, const TCHAR *Name, const int32 UserIndex, const TArray< uint8 > &Data) override
Saves the game, blocking until complete.
Public Member Functions inherited from ISaveGameSystem
virtual void DeleteGameAsync (bool bAttemptToUseUI, const TCHAR *Name, FPlatformUserId PlatformUserId, FSaveGameAsyncOpCompleteCallback Callback)
virtual void DoesSaveGameExistAsync (const TCHAR *Name, FPlatformUserId PlatformUserId, FSaveGameAsyncExistsCallback Callback)
virtual void GetSaveGameNamesAsync (FPlatformUserId PlatformUserId, FSaveGameAsyncGetNamesCallback Callback)
virtual void InitAsync (bool bAttemptToUseUI, FPlatformUserId PlatformUserId, FSaveGameAsyncInitCompleteCallback Callback)
virtual void LoadGameAsync (bool bAttemptToUseUI, const TCHAR *Name, FPlatformUserId PlatformUserId, FSaveGameAsyncLoadCompleteCallback Callback)
virtual void SaveGameAsync (bool bAttemptToUseUI, const TCHAR *Name, FPlatformUserId PlatformUserId, TSharedRef< const TArray< uint8 > > Data, FSaveGameAsyncOpCompleteCallback Callback)
Protected Member Functions
virtual FString GetSaveGamePath (const TCHAR *Name)
Get the path to save game file for the given name, a platform may be able to simply override this and no other functions above.
Protected Member Functions inherited from ISaveGameSystem
void OnAsyncComplete (TFunction< void()> Callback)
Additional Inherited Members
Public Types inherited from ISaveGameSystem
enum class ESaveExistsResult { OK , DoesNotExist , Corrupt , UnspecifiedError }
typedef TFunction< void(const FString &, FPlatformUserId, ISaveGameSystem::ESaveExistsResult)> FSaveGameAsyncExistsCallback
typedef TFunction< void(FPlatformUserId, bool, const TArray< FString > &)> FSaveGameAsyncGetNamesCallback
typedef TFunction< void(FPlatformUserId, bool)> FSaveGameAsyncInitCompleteCallback
typedef TFunction< void(const FString &, FPlatformUserId, bool, const TArray< uint8 > &)> FSaveGameAsyncLoadCompleteCallback
typedef TFunction< void(const FString &, FPlatformUserId, bool)> FSaveGameAsyncOpCompleteCallback
Static Protected Attributes inherited from ISaveGameSystem
static UE::Tasks::FPipe AsyncTaskPipe
Detailed Description
A generic save game system that just uses IFileManager to save/load with normal files.
Definition at line 107 of file SaveGameSystem.h.
Member Function Documentation
DeleteGame()
virtual bool FGenericSaveGameSystem::DeleteGame (bool bAttemptToUseUI, const TCHAR * Name, const int32 UserIndex) inline override virtual
Delete an existing save game, blocking until complete.
Implements ISaveGameSystem.
Definition at line 158 of file SaveGameSystem.h.
References IFileManager::Delete(), IFileManager::Get(), GetSaveGamePath(), and Name.
DoesSaveGameExist()
virtual bool FGenericSaveGameSystem::DoesSaveGameExist (const TCHAR * Name, const int32 UserIndex) inline override virtual
Return true if the named savegame exists (probably not useful with NativeUI.
Implements ISaveGameSystem.
Definition at line 129 of file SaveGameSystem.h.
References DoesSaveGameExistWithResult(), Name, and ISaveGameSystem::OK.
DoesSaveGameExistWithResult()
virtual ESaveExistsResult FGenericSaveGameSystem::DoesSaveGameExistWithResult (const TCHAR * Name, const int32 UserIndex) inline override virtual
Similar to DoesSaveGameExist, except returns a result code with more information.
Implements ISaveGameSystem.
Definition at line 120 of file SaveGameSystem.h.
References ISaveGameSystem::DoesNotExist, IFileManager::Get(), GetSaveGamePath(), Name, and ISaveGameSystem::OK.
Referenced by DoesSaveGameExist().
DoesSaveSystemSupportMultipleUsers()
virtual bool FGenericSaveGameSystem::DoesSaveSystemSupportMultipleUsers () inline override virtual
Some save systems don't support more than one user, in those cases the game needs to avoid saving settings for anyone but the primary user.
Implements ISaveGameSystem.
Definition at line 115 of file SaveGameSystem.h.
GetSaveGameNames()
virtual bool FGenericSaveGameSystem::GetSaveGameNames (TArray< FString > & FoundSaves, const int32 UserIndex) inline override virtual
Gets a list of all known saves.
This isn't possible on all platforms.
Reimplemented from ISaveGameSystem.
Definition at line 134 of file SaveGameSystem.h.
References TArray< InElementType, InAllocatorType >::Add(), IFileManager::FindFiles(), IFileManager::Get(), FPaths::GetBaseFilename(), FPaths::ProjectSavedDir(), and TEXT.
GetSaveGamePath()
virtual FString FGenericSaveGameSystem::GetSaveGamePath (const TCHAR * Name) inline protected virtual
Get the path to save game file for the given name, a platform may be able to simply override this and no other functions above.
Definition at line 166 of file SaveGameSystem.h.
References Name, FPaths::ProjectSavedDir(), and TEXT.
Referenced by DeleteGame(), DoesSaveGameExistWithResult(), LoadGame(), and SaveGame().
LoadGame()
virtual bool FGenericSaveGameSystem::LoadGame (bool bAttemptToUseUI, const TCHAR * Name, const int32 UserIndex, TArray< uint8 > & Data) inline override virtual
Loads the game, blocking until complete.
Implements ISaveGameSystem.
Definition at line 153 of file SaveGameSystem.h.
References GetSaveGamePath(), FFileHelper::LoadFileToArray(), and Name.
PlatformHasNativeUI()
virtual bool FGenericSaveGameSystem::PlatformHasNativeUI () inline override virtual
Returns true if the platform has a native UI (like many consoles)
Implements ISaveGameSystem.
Definition at line 110 of file SaveGameSystem.h.
SaveGame()
virtual bool FGenericSaveGameSystem::SaveGame (bool bAttemptToUseUI, const TCHAR * Name, const int32 UserIndex, const TArray< uint8 > & Data) inline override virtual
Saves the game, blocking until complete.
Platform may use FGameDelegates to get more information from the game
Implements ISaveGameSystem.
Definition at line 148 of file SaveGameSystem.h.
References GetSaveGamePath(), Name, and FFileHelper::SaveArrayToFile().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SaveGameSystem.h