Unreal Engine 5.6 C++ API: UParticleModuleLocationPrimitiveTriangle Class Reference
UParticleModuleLocationPrimitiveTriangle Class Reference
#include "ParticleModuleLocationPrimitiveTriangle.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() struct FRawDistributionVector StartOffset
void InitializeDefaults ()
Initializes the default values for this property.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void Render3DPreview (const FPreviewContext &Context) override
virtual void Spawn (const FSpawnContext &Context) override
void SpawnEx (const FSpawnContext &Context, struct FRandomStream *InRandomStream)
Extended version of spawn, allows for using a random stream for distribution value retrieval.
UPROPERTY () struct FRawDistributionFloat Angle
UPROPERTY () struct FRawDistributionFloat Height
UPROPERTY () struct FRawDistributionFloat Thickness
Detailed Description
Definition at line 20 of file ParticleModuleLocationPrimitiveTriangle.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UParticleModuleLocationPrimitiveTriangle::GENERATED_UCLASS_BODY () private
References Category, Location, and UPROPERTY().
InitializeDefaults()
void UParticleModuleLocationPrimitiveTriangle::InitializeDefaults () private
Initializes the default values for this property.
References InitializeDefaults().
Referenced by InitializeDefaults().
PostEditChangeProperty()
virtual void UParticleModuleLocationPrimitiveTriangle::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UParticleModuleLocationPrimitiveTriangle::PostInitProperties () override private virtual
Render3DPreview()
virtual void UParticleModuleLocationPrimitiveTriangle::Render3DPreview (const FPreviewContext & Context) override private virtual
Spawn()
virtual void UParticleModuleLocationPrimitiveTriangle::Spawn (const FSpawnContext & Context) override private virtual
SpawnEx()
void UParticleModuleLocationPrimitiveTriangle::SpawnEx (const FSpawnContext & Context, struct FRandomStream * InRandomStream) private
Extended version of spawn, allows for using a random stream for distribution value retrieval.
Parameters
Owner The particle emitter instance that is spawning
Offset The offset to the modules payload data
SpawnTime The time of the spawn
InRandomStream The random stream to use for retrieving random values
UPROPERTY() [1/3]
UParticleModuleLocationPrimitiveTriangle::UPROPERTY () private
References Angle, Category, Location, and UPROPERTY().
UPROPERTY() [2/3]
UParticleModuleLocationPrimitiveTriangle::UPROPERTY () private
References Category, Location, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [3/3]
UParticleModuleLocationPrimitiveTriangle::UPROPERTY () private
References Category, Location, and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/Location/ParticleModuleLocationPrimitiveTriangle.h