Unreal Engine 5.6 C++ API: TSpscQueue< T, AllocatorType > Class Template Reference
TSpscQueue< T, AllocatorType > Class Template Reference final
Fast single-producer/single-consumer unbounded concurrent queue.
#include "SpscQueue.h"
Data Structures
struct FNode
Public Types
using ElementType = T
Public Member Functions
TSpscQueue ()
~TSpscQueue ()
TOptional< ElementType > Dequeue ()
bool Dequeue (ElementType &OutElem)
template<typename... ArgTypes>
void Enqueue (ArgTypes &&... Args)
bool IsEmpty () const
ElementType * Peek () const
UE_NONCOPYABLE (TSpscQueue)
Private Member Functions
FNode * AllocNode ()
Private Attributes
FNode * First
FNode * Head
std::atomic< FNode * > Tail
FNode * TailCopy
Detailed Description
template<typename T, typename AllocatorType = FMemory>
class TSpscQueue< T, AllocatorType >
Fast single-producer/single-consumer unbounded concurrent queue.
Doesn't free memory until destruction but recycles consumed items. Based on http://www.1024cores.net/home/lock-free-algorithms/queues/unbounded-spsc-queue
Definition at line 17 of file SpscQueue.h.
Member Typedef Documentation
ElementType
template<typename T, typename AllocatorType = FMemory> using TSpscQueue< T, AllocatorType >::ElementType = T
Definition at line 20 of file SpscQueue.h.
Constructor & Destructor Documentation
TSpscQueue()
template<typename T, typename AllocatorType = FMemory> TSpscQueue< T, AllocatorType >::TSpscQueue () inline nodiscard
Definition at line 24 of file SpscQueue.h.
References First, Head, Tail, and TailCopy.
Referenced by UE_NONCOPYABLE().
~TSpscQueue()
template<typename T, typename AllocatorType = FMemory> TSpscQueue< T, AllocatorType >::~TSpscQueue () inline
Definition at line 31 of file SpscQueue.h.
References DestructItem(), First, TSpscQueue< T, AllocatorType >::FNode::Next, Tail, and TSpscQueue< T, AllocatorType >::FNode::Value.
Member Function Documentation
AllocNode()
template<typename T, typename AllocatorType = FMemory> FNode * TSpscQueue< T, AllocatorType >::AllocNode () inline private
Definition at line 127 of file SpscQueue.h.
References First, TSpscQueue< T, AllocatorType >::FNode::Next, Tail, and TailCopy.
Referenced by Enqueue().
Dequeue() [1/2]
template<typename T, typename AllocatorType = FMemory> TOptional< ElementType > TSpscQueue< T, AllocatorType >::Dequeue () inline
Definition at line 67 of file SpscQueue.h.
References DestructItem(), MoveTemp(), TSpscQueue< T, AllocatorType >::FNode::Next, Tail, TSpscQueue< T, AllocatorType >::FNode::Value, and Value.
Referenced by Dequeue().
Dequeue() [2/2]
template<typename T, typename AllocatorType = FMemory> bool TSpscQueue< T, AllocatorType >::Dequeue (ElementType & OutElem) inline
Definition at line 84 of file SpscQueue.h.
References Dequeue(), TOptional< OptionalType >::GetValue(), TOptional< OptionalType >::IsSet(), and MoveTempIfPossible().
Enqueue()
template<typename T, typename AllocatorType = FMemory> template<typename... ArgTypes> void TSpscQueue< T, AllocatorType >::Enqueue (ArgTypes &&... Args) inline
Definition at line 57 of file SpscQueue.h.
References AllocNode(), Forward(), Head, and TSpscQueue< T, AllocatorType >::FNode::Value.
IsEmpty()
template<typename T, typename AllocatorType = FMemory> bool TSpscQueue< T, AllocatorType >::IsEmpty () const inline nodiscard
Definition at line 96 of file SpscQueue.h.
References TSpscQueue< T, AllocatorType >::FNode::Next, and Tail.
Peek()
template<typename T, typename AllocatorType = FMemory> ElementType * TSpscQueue< T, AllocatorType >::Peek () const inline nodiscard
Definition at line 106 of file SpscQueue.h.
References TSpscQueue< T, AllocatorType >::FNode::Next, Tail, and TSpscQueue< T, AllocatorType >::FNode::Value.
UE_NONCOPYABLE()
template<typename T, typename AllocatorType = FMemory> TSpscQueue< T, AllocatorType >::UE_NONCOPYABLE (TSpscQueue< T, AllocatorType >)
References TSpscQueue().
Field Documentation
First
template<typename T, typename AllocatorType = FMemory> FNode* TSpscQueue< T, AllocatorType >::First private
Definition at line 169 of file SpscQueue.h.
Referenced by TSpscQueue(), ~TSpscQueue(), and AllocNode().
Head
template<typename T, typename AllocatorType = FMemory> FNode* TSpscQueue< T, AllocatorType >::Head private
Definition at line 165 of file SpscQueue.h.
Referenced by TSpscQueue(), and Enqueue().
Tail
template<typename T, typename AllocatorType = FMemory> std::atomic<FNode*> TSpscQueue< T, AllocatorType >::Tail private
Definition at line 158 of file SpscQueue.h.
Referenced by TSpscQueue(), ~TSpscQueue(), AllocNode(), Dequeue(), IsEmpty(), and Peek().
TailCopy
template<typename T, typename AllocatorType = FMemory> FNode* TSpscQueue< T, AllocatorType >::TailCopy private
Definition at line 170 of file SpscQueue.h.
Referenced by TSpscQueue(), and AllocNode().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SpscQueue.h