Unreal Engine 5.6 C++ API: FMovieSceneSpawnRegister Class Reference
FMovieSceneSpawnRegister Class Reference abstract
Class responsible for managing spawnables in a movie scene.
#include "MovieSceneSpawnRegister.h"
Data Structures
struct FMovieSceneSpawnRegisterKey
Helper key type for mapping a guid and sequence instance to a specific value.
struct FSpawnedObject
Structure holding information pertaining to a spawned object.
Public Types
using FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Public Member Functions
MOVIESCENE_API FMovieSceneSpawnRegister ()
MOVIESCENE_API FMovieSceneSpawnRegister (const FMovieSceneSpawnRegister &)
virtual MOVIESCENE_API ~FMovieSceneSpawnRegister ()
Virtual destructor.
virtual bool CanConvertSpawnableToPossessable (FMovieSceneSpawnable &Spawnable) const
virtual MOVIESCENE_API bool CanConvertToPossessable (const FGuid &Guid, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, int32 BindingIndex=0) const
Check whether the specified binding can become a Possessable.
virtual bool CanSpawnObject (UClass *InClass) const
Whether this class is supported as a spawnable.
MOVIESCENE_API void CleanUp (IMovieScenePlayer &Player)
MOVIESCENE_API void CleanUp (TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called to indiscriminately clean up any spawned objects.
MOVIESCENE_API void CleanUpSequence (FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer &Player)
MOVIESCENE_API void CleanUpSequence (FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called to clean up any non-externally owned spawnables that were spawned from the specified instance.
virtual TValueOrError< FNewSpawnable, FText > CreateNewSpawnableType (UObject &SourceObject, UMovieScene &OwnerMovieScene, UActorFactory *ActorFactory=nullptr)
Create a new spawnable type from the given source object.
void DestroyObjectDirectly (UObject &InObject)
Destroy a specific previously spawned object, where its binding ID and sequence ID is not known.
MOVIESCENE_API void DestroyObjectsByPredicate (IMovieScenePlayer &Player, const TFunctionRef< bool(const FGuid &, ESpawnOwnership, FMovieSceneSequenceIDRef)> &Predicate)
MOVIESCENE_API void DestroyObjectsByPredicate (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const TFunctionRef< bool(const FGuid &, ESpawnOwnership, FMovieSceneSequenceIDRef)> &Predicate)
MOVIESCENE_API void DestroyObjectsByPredicate (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const TFunctionRef< bool(const FGuid &, ESpawnOwnership, FMovieSceneSequenceIDRef, int32)> &Predicate)
Destroy spawned objects using a custom predicate.
MOVIESCENE_API bool DestroySpawnedObject (const FGuid &BindingId, FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer &Player)
bool DestroySpawnedObject (const FGuid &BindingId, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
MOVIESCENE_API bool DestroySpawnedObject (const FGuid &BindingId, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, int32 BindingIndex)
Destroy a specific previously spawned object.
TWeakObjectPtr FindSpawnedObject (const FGuid &BindingId, FMovieSceneSequenceIDRef TemplateID) const
MOVIESCENE_API TWeakObjectPtr FindSpawnedObject (const FGuid &BindingId, FMovieSceneSequenceIDRef TemplateID, int BindingIndex) const
Attempt to find a previously spawned object represented by the specified object and template IDs.
MOVIESCENE_API void ForgetExternallyOwnedSpawnedObjects (FMovieSceneEvaluationState &State, IMovieScenePlayer &Player)
MOVIESCENE_API void ForgetExternallyOwnedSpawnedObjects (TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Purge any memory of any objects that are considered externally owned.
MOVIESCENE_API void HandleConvertPossessableToSpawnable (UObject *OldObject, IMovieScenePlayer &Player, TOptional< FTransformData > &OutTransformData)
virtual void HandleConvertPossessableToSpawnable (UObject *OldObject, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, TOptional< FTransformData > &OutTransformData)
Called to handle cleanup of objects when we convert a possessable to a spawnable object.
MOVIESCENE_API void OnSequenceExpired (FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer &Player)
MOVIESCENE_API void OnSequenceExpired (FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called when the current time has moved beyond the specified sequence's play range.
virtual void SaveDefaultSpawnableState (const FGuid &Guid, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
virtual void SaveDefaultSpawnableState (const FGuid &Guid, int32 BindingIndex, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called to save the default state of the specified spawnable.
MOVIESCENE_API void SaveDefaultSpawnableState (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer &Player)
virtual MOVIESCENE_API void SaveDefaultSpawnableState (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
virtual void SetupDefaultsForSpawnable (UObject *SpawnedObject, const FGuid &Guid, const TOptional< FTransformData > &TransformData, TSharedRef< ISequencer > Sequencer, USequencerSettings *Settings)
Setup a new spawnable object with some default tracks and keys.
MOVIESCENE_API UObject * SpawnObject (const FGuid &BindingId, UMovieScene &MovieScene, FMovieSceneSequenceIDRef Template, IMovieScenePlayer &Player)
virtual UObject * SpawnObject (const FGuid &BindingId, UMovieScene &MovieScene, FMovieSceneSequenceIDRef Template, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
virtual MOVIESCENE_API UObject * SpawnObject (const FGuid &BindingId, UMovieScene &MovieScene, FMovieSceneSequenceIDRef Template, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, int32 BindingIndex)
Spawn an object for the specified GUID, from the specified sequence instance.
MOVIESCENE_API UObject * SpawnObject (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer &Player)
Public Member Functions inherited from TSharedFromThis< FMovieSceneSpawnRegister >
TSharedRef< FMovieSceneSpawnRegister, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneSpawnRegister, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static MOVIESCENE_API UE::MovieScene::TPlaybackCapabilityID< FMovieSceneSpawnRegister > GetPlaybackCapabilityID ()
Protected Member Functions
virtual void DestroySpawnedObject (UObject &Object, UMovieSceneSpawnableBindingBase *CustomSpawnableBinding)=0
Destroy a specific previously spawned object.
virtual void PreDestroyObject (UObject &Object, const FGuid &BindingId, int32 BindingIndex, FMovieSceneSequenceIDRef TemplateID)
virtual UObject * SpawnObject (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)=0
Spawn an object for the specified GUID, from the specified sequence instance.
UE_DEPRECATED (5.5, "Please use the version of this with BindingIndex") MOVIESCENE_API virtual void PreDestroyObject(UObject &Object
Called right before a spawned object with the specified ID and template ID is destroyed.
UE_DEPRECATED (5.5, "Please use the version of this with CustomSpawnableBinding") virtual void DestroySpawnedObject(UObject &Object)
Protected Member Functions inherited from TSharedFromThis< FMovieSceneSpawnRegister >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bCleaningUp = false
True when cleaning ourselves up.
const FGuid & BindingId
TMap< FMovieSceneSpawnRegisterKey, FSpawnedObject > Register
Register of spawned objects.
const FGuid FMovieSceneSequenceIDRef TemplateID
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneSpawnRegister >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Class responsible for managing spawnables in a movie scene.
Definition at line 48 of file MovieSceneSpawnRegister.h.
Member Typedef Documentation
FSharedPlaybackState
using FMovieSceneSpawnRegister::FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Definition at line 52 of file MovieSceneSpawnRegister.h.
Constructor & Destructor Documentation
FMovieSceneSpawnRegister() [1/2]
MOVIESCENE_API FMovieSceneSpawnRegister::FMovieSceneSpawnRegister ()
References FMovieSceneSpawnRegister().
Referenced by FMovieSceneSpawnRegister(), FMovieSceneSpawnRegister(), ~FMovieSceneSpawnRegister(), and GetPlaybackCapabilityID().
FMovieSceneSpawnRegister() [2/2]
MOVIESCENE_API FMovieSceneSpawnRegister::FMovieSceneSpawnRegister (const FMovieSceneSpawnRegister &)
References FMovieSceneSpawnRegister().
~FMovieSceneSpawnRegister()
virtual MOVIESCENE_API FMovieSceneSpawnRegister::~FMovieSceneSpawnRegister () virtual
Virtual destructor.
References FMovieSceneSpawnRegister().
Member Function Documentation
CanConvertSpawnableToPossessable()
virtual bool FMovieSceneSpawnRegister::CanConvertSpawnableToPossessable (FMovieSceneSpawnable & Spawnable) const inline virtual
Definition at line 220 of file MovieSceneSpawnRegister.h.
CanConvertToPossessable()
virtual MOVIESCENE_API bool FMovieSceneSpawnRegister::CanConvertToPossessable (const FGuid & Guid, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, int32 BindingIndex = 0) const virtual
Check whether the specified binding can become a Possessable.
Parameters
BindingId ID of the object to destroy
TemplateID Identifier for the current template we're evaluating
Returns
whether the conversion from Spawnable to Possessable can occur.
References Guid, and TemplateID.
CanSpawnObject()
virtual bool FMovieSceneSpawnRegister::CanSpawnObject (UClass * InClass) const inline virtual
Whether this class is supported as a spawnable.
Parameters
InClass The class
Returns
Whether this class is supported as a spawnable
Reimplemented in FLevelSequenceSpawnRegister.
Definition at line 165 of file MovieSceneSpawnRegister.h.
CleanUp() [1/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::CleanUp (IMovieScenePlayer & Player)
CleanUp() [2/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::CleanUp (TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called to indiscriminately clean up any spawned objects.
CleanUpSequence() [1/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::CleanUpSequence (FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer & Player)
References TemplateID.
CleanUpSequence() [2/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::CleanUpSequence (FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called to clean up any non-externally owned spawnables that were spawned from the specified instance.
References TemplateID.
CreateNewSpawnableType()
virtual TValueOrError< FNewSpawnable, FText > FMovieSceneSpawnRegister::CreateNewSpawnableType (UObject & SourceObject, UMovieScene & OwnerMovieScene, UActorFactory * ActorFactory = nullptr) inline virtual
Create a new spawnable type from the given source object.
Parameters
SourceObject The source object to create the spawnable from
OwnerMovieScene The owner movie scene that this spawnable type should reside in
ActorFactory Optional actor factory to use to create spawnable type
Returns
the new spawnable type, or error
Definition at line 175 of file MovieSceneSpawnRegister.h.
References MakeError(), and NSLOCTEXT.
DestroyObjectDirectly()
void FMovieSceneSpawnRegister::DestroyObjectDirectly (UObject & InObject) inline
Destroy a specific previously spawned object, where its binding ID and sequence ID is not known.
Note
Should only be used for restoring pre-animated state, or where it is otherwise impossible to call DestroySpawnedObject
Parameters
InObject the object to destroy
Definition at line 106 of file MovieSceneSpawnRegister.h.
References DestroyObjectDirectly(), and DestroySpawnedObject().
Referenced by DestroyObjectDirectly().
DestroyObjectsByPredicate() [1/3]
MOVIESCENE_API void FMovieSceneSpawnRegister::DestroyObjectsByPredicate (IMovieScenePlayer & Player, const TFunctionRef< bool(const FGuid &, ESpawnOwnership, FMovieSceneSequenceIDRef)> & Predicate)
References Predicate.
DestroyObjectsByPredicate() [2/3]
MOVIESCENE_API void FMovieSceneSpawnRegister::DestroyObjectsByPredicate (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const TFunctionRef< bool(const FGuid &, ESpawnOwnership, FMovieSceneSequenceIDRef)> & Predicate)
References Predicate.
DestroyObjectsByPredicate() [3/3]
MOVIESCENE_API void FMovieSceneSpawnRegister::DestroyObjectsByPredicate (TSharedRef< const FSharedPlaybackState > SharedPlaybackState, const TFunctionRef< bool(const FGuid &, ESpawnOwnership, FMovieSceneSequenceIDRef, int32)> & Predicate)
Destroy spawned objects using a custom predicate.
Parameters
Player Movie scene player that is ultimately responsible for destroying the objects
Predicate Predicate used for testing whether an object should be destroyed. Returns true for destruction, false to skip.
References Predicate.
DestroySpawnedObject() [1/4]
MOVIESCENE_API bool FMovieSceneSpawnRegister::DestroySpawnedObject (const FGuid & BindingId, FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer & Player)
References BindingId, and TemplateID.
DestroySpawnedObject() [2/4]
bool FMovieSceneSpawnRegister::DestroySpawnedObject (const FGuid & BindingId, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) inline
Definition at line 146 of file MovieSceneSpawnRegister.h.
References BindingId, DestroySpawnedObject(), and TemplateID.
Referenced by DestroySpawnedObject().
DestroySpawnedObject() [3/4]
MOVIESCENE_API bool FMovieSceneSpawnRegister::DestroySpawnedObject (const FGuid & BindingId, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, int32 BindingIndex)
Destroy a specific previously spawned object.
Parameters
BindingId ID of the object to destroy
TemplateID Identifier for the current template we're evaluating
Player Movie scene player that is ultimately responsible for destroying the object
BindingIndex For level sequences using custom spawnable bindings, the index of the binding reference.
Returns
True if an object was destroyed, false otherwise The version without the binding index is to support old clients of the previous API
References BindingId, DestroySpawnedObject(), and TemplateID.
Referenced by DestroyObjectDirectly(), DestroySpawnedObject(), and UE_DEPRECATED().
DestroySpawnedObject() [4/4]
virtual void FMovieSceneSpawnRegister::DestroySpawnedObject (UObject & Object, UMovieSceneSpawnableBindingBase * CustomSpawnableBinding) protected pure virtual
Destroy a specific previously spawned object.
Parameters
Object The object to destroy
CustomSpawnableBinding Optional custom spawnable binding to handle the destroy.
Implemented in FLevelSequenceSpawnRegister, and FNullMovieSceneSpawnRegister.
References Object.
FindSpawnedObject() [1/2]
TWeakObjectPtr FMovieSceneSpawnRegister::FindSpawnedObject (const FGuid & BindingId, FMovieSceneSequenceIDRef TemplateID) const inline
Definition at line 144 of file MovieSceneSpawnRegister.h.
References BindingId, FindSpawnedObject(), and TemplateID.
Referenced by FindSpawnedObject().
FindSpawnedObject() [2/2]
MOVIESCENE_API TWeakObjectPtr FMovieSceneSpawnRegister::FindSpawnedObject (const FGuid & BindingId, FMovieSceneSequenceIDRef TemplateID, int BindingIndex) const
Attempt to find a previously spawned object represented by the specified object and template IDs.
Parameters
BindingId ID of the object to find
TemplateID Unique ID of the template to look within
BindingIndex For level sequences using custom spawnable bindings, the index of the binding reference.
Returns
The spawned object if found; nullptr otherwise. The version without the binding index is to support old clients of the previous API
References BindingId, FindSpawnedObject(), and TemplateID.
Referenced by FindSpawnedObject().
ForgetExternallyOwnedSpawnedObjects() [1/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::ForgetExternallyOwnedSpawnedObjects (FMovieSceneEvaluationState & State, IMovieScenePlayer & Player)
References State.
ForgetExternallyOwnedSpawnedObjects() [2/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::ForgetExternallyOwnedSpawnedObjects (TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Purge any memory of any objects that are considered externally owned.
Parameters
Player Movie scene player that is ultimately responsible for destroying the objects
GetPlaybackCapabilityID()
MOVIESCENE_API UE::MovieScene::TPlaybackCapabilityID< FMovieSceneSpawnRegister > FMovieSceneSpawnRegister::GetPlaybackCapabilityID () static
References FMovieSceneSpawnRegister().
HandleConvertPossessableToSpawnable() [1/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::HandleConvertPossessableToSpawnable (UObject * OldObject, IMovieScenePlayer & Player, TOptional< FTransformData > & OutTransformData)
HandleConvertPossessableToSpawnable() [2/2]
virtual void FMovieSceneSpawnRegister::HandleConvertPossessableToSpawnable (UObject * OldObject, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, TOptional< FTransformData > & OutTransformData) inline virtual
Called to handle cleanup of objects when we convert a possessable to a spawnable object.
Parameters
OldObject The old possessable object
Player The current player
OutTransformData Transform data that can be used to recreate objects in the same location
Definition at line 200 of file MovieSceneSpawnRegister.h.
OnSequenceExpired() [1/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::OnSequenceExpired (FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer & Player)
References TemplateID.
OnSequenceExpired() [2/2]
MOVIESCENE_API void FMovieSceneSpawnRegister::OnSequenceExpired (FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState)
Called when the current time has moved beyond the specified sequence's play range.
References TemplateID.
PreDestroyObject()
virtual void FMovieSceneSpawnRegister::PreDestroyObject (UObject & Object, const FGuid & BindingId, int32 BindingIndex, FMovieSceneSequenceIDRef TemplateID) inline protected virtual
Definition at line 242 of file MovieSceneSpawnRegister.h.
References BindingId, Object, PreDestroyObject(), and TemplateID.
Referenced by PreDestroyObject().
SaveDefaultSpawnableState() [1/4]
virtual void FMovieSceneSpawnRegister::SaveDefaultSpawnableState (const FGuid & Guid, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) inline virtual
Definition at line 214 of file MovieSceneSpawnRegister.h.
References Guid, SaveDefaultSpawnableState(), and TemplateID.
Referenced by SaveDefaultSpawnableState().
SaveDefaultSpawnableState() [2/4]
virtual void FMovieSceneSpawnRegister::SaveDefaultSpawnableState (const FGuid & Guid, int32 BindingIndex, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) inline virtual
Called to save the default state of the specified spawnable.
Definition at line 180 of file MovieSceneSpawnRegister.h.
References Guid, and TemplateID.
SaveDefaultSpawnableState() [3/4]
MOVIESCENE_API void FMovieSceneSpawnRegister::SaveDefaultSpawnableState (FMovieSceneSpawnable & Spawnable, FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer & Player)
References TemplateID.
SaveDefaultSpawnableState() [4/4]
virtual MOVIESCENE_API void FMovieSceneSpawnRegister::SaveDefaultSpawnableState (FMovieSceneSpawnable & Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) virtual
References TemplateID.
SetupDefaultsForSpawnable()
virtual void FMovieSceneSpawnRegister::SetupDefaultsForSpawnable (UObject * SpawnedObject, const FGuid & Guid, const TOptional< FTransformData > & TransformData, TSharedRef< ISequencer > Sequencer, USequencerSettings * Settings) inline virtual
Setup a new spawnable object with some default tracks and keys.
Parameters
SpawnedObject The newly spawned object. This may be NULL in the case of a spawnable that has not yet bneen spawned.
Guid The ID of the spawnable to setup defaults for
TransformData The transform of the object to be spawned. This will usually be valid in the case of converting a possessable to a spawnable.
Sequencer The sequencer this spawnable was just created by
Settings The settings for this sequencer
Definition at line 191 of file MovieSceneSpawnRegister.h.
References Guid.
SpawnObject() [1/5]
MOVIESCENE_API UObject * FMovieSceneSpawnRegister::SpawnObject (const FGuid & BindingId, UMovieScene & MovieScene, FMovieSceneSequenceIDRef Template, IMovieScenePlayer & Player)
References BindingId.
SpawnObject() [2/5]
virtual UObject * FMovieSceneSpawnRegister::SpawnObject (const FGuid & BindingId, UMovieScene & MovieScene, FMovieSceneSequenceIDRef Template, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) inline virtual
Definition at line 145 of file MovieSceneSpawnRegister.h.
References BindingId, and SpawnObject().
Referenced by SpawnObject().
SpawnObject() [3/5]
virtual MOVIESCENE_API UObject * FMovieSceneSpawnRegister::SpawnObject (const FGuid & BindingId, UMovieScene & MovieScene, FMovieSceneSequenceIDRef Template, TSharedRef< const FSharedPlaybackState > SharedPlaybackState, int32 BindingIndex) virtual
Spawn an object for the specified GUID, from the specified sequence instance.
Parameters
BindingId ID of the object to spawn
TemplateID Identifier for the current template we're evaluating
Player Movie scene player that is ultimately responsible for spawning the object
BindingIndex For level sequences using custom spawnable bindings, the index of the binding reference.
Returns
the spawned object, or nullptr on failure The version without the binding index is to support old clients of the previous API
References BindingId, and SpawnObject().
Referenced by SpawnObject().
SpawnObject() [4/5]
MOVIESCENE_API UObject * FMovieSceneSpawnRegister::SpawnObject (FMovieSceneSpawnable & Spawnable, FMovieSceneSequenceIDRef TemplateID, IMovieScenePlayer & Player)
References TemplateID.
SpawnObject() [5/5]
virtual UObject * FMovieSceneSpawnRegister::SpawnObject (FMovieSceneSpawnable & Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const FSharedPlaybackState > SharedPlaybackState) protected pure virtual
Spawn an object for the specified GUID, from the specified sequence instance.
Parameters
Object ID of the object to spawn
TemplateID Identifier for the current template we're evaluating
Player Movie scene player that is ultimately responsible for spawning the object
Returns
the spawned object, or nullptr on failure
Implemented in FLevelSequenceSpawnRegister, and FNullMovieSceneSpawnRegister.
References TemplateID.
UE_DEPRECATED() [1/2]
FMovieSceneSpawnRegister::UE_DEPRECATED (5. 5, "Please use the version of this with BindingIndex") & protected
Called right before a spawned object with the specified ID and template ID is destroyed.
UE_DEPRECATED() [2/2]
FMovieSceneSpawnRegister::UE_DEPRECATED (5. 5, "Please use the version of this with CustomSpawnableBinding") & inline protected
Definition at line 244 of file MovieSceneSpawnRegister.h.
References DestroySpawnedObject(), and Object.
Field Documentation
bCleaningUp
bool FMovieSceneSpawnRegister::bCleaningUp = false protected
True when cleaning ourselves up.
Used to bypass marking a sequence dirty when objects are modified since we're cleaning ourselves up
Definition at line 314 of file MovieSceneSpawnRegister.h.
BindingId
const FGuid& FMovieSceneSpawnRegister::BindingId protected
Definition at line 240 of file MovieSceneSpawnRegister.h.
Referenced by DestroySpawnedObject(), DestroySpawnedObject(), DestroySpawnedObject(), FindSpawnedObject(), FindSpawnedObject(), PreDestroyObject(), SpawnObject(), SpawnObject(), and SpawnObject().
Register
TMap<FMovieSceneSpawnRegisterKey, FSpawnedObject> FMovieSceneSpawnRegister::Register protected
Register of spawned objects.
Definition at line 311 of file MovieSceneSpawnRegister.h.
TemplateID
const FGuid FMovieSceneSequenceIDRef FMovieSceneSpawnRegister::TemplateID protected
Definition at line 240 of file MovieSceneSpawnRegister.h.
Referenced by CanConvertToPossessable(), CleanUpSequence(), CleanUpSequence(), DestroySpawnedObject(), DestroySpawnedObject(), DestroySpawnedObject(), FindSpawnedObject(), FindSpawnedObject(), OnSequenceExpired(), OnSequenceExpired(), PreDestroyObject(), SaveDefaultSpawnableState(), SaveDefaultSpawnableState(), SaveDefaultSpawnableState(), SaveDefaultSpawnableState(), FLevelSequenceSpawnRegister::SpawnObject(), SpawnObject(), and SpawnObject().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/MovieSceneSpawnRegister.h