Unreal Engine 5.6 C++ API: TraceServices::TMonotonicTimeline< InEventType, SettingsType > Class Template Reference
TraceServices::TMonotonicTimeline< InEventType, SettingsType > Class Template Reference
#include "MonotonicTimeline.h"
Data Structures
struct FFindBestMatchEventInParams
struct FFindBestMatchEventOutParams
struct FIterationState
Public Types
using EventType = InEventType
Public Types inherited from TraceServices::ITimeline< InEventType >
typedef TFunction< EEventEnumerate(bool, double, const EventType &, uint32)> AsyncEventCallback
typedef TFunction< EEventEnumerate(double, double, uint32, const EventType &, uint32)> AsyncEventRangeCallback
typedef TFunctionRef< EEventEnumerate(bool, double, const EventType &)> EventCallback
typedef TFunctionRef< EEventEnumerate(double, double, uint32, const EventType &)> EventRangeCallback
typedef InEventType EventType
typedef TFunction< void(uint32)> TaskInfoCallback
Public Member Functions
TMonotonicTimeline (ILinearAllocator &InAllocator)
virtual ~TMonotonicTimeline ()=default
virtual void AppendBeginEvent (double StartTime, const EventType &Event) override
virtual void AppendEndEvent (double EndTime) override
virtual void EnumerateEvents (double IntervalStart, double IntervalEnd, typename ITimeline< EventType >::EventCallback Callback) const override
virtual void EnumerateEvents (double IntervalStart, double IntervalEnd, typename ITimeline< EventType >::EventRangeCallback Callback) const override
virtual void EnumerateEventsBackwards (double IntervalEnd, double IntervalStart, typename ITimeline< EventType >::EventCallback Callback) const override
virtual void EnumerateEventsBackwards (double IntervalEnd, double IntervalStart, typename ITimeline< EventType >::EventRangeCallback Callback) const override
virtual void EnumerateEventsBackwardsDownSampled (double IntervalEnd, double IntervalStart, double Resolution, typename ITimeline< EventType >::EventCallback Callback) const override
virtual void EnumerateEventsBackwardsDownSampled (double IntervalEnd, double IntervalStart, double Resolution, typename ITimeline< EventType >::EventRangeCallback Callback) const override
virtual void EnumerateEventsDownSampled (double IntervalStart, double IntervalEnd, double Resolution, typename ITimeline< EventType >::EventCallback Callback) const override
virtual void EnumerateEventsDownSampled (double IntervalStart, double IntervalEnd, double Resolution, typename ITimeline< EventType >::EventRangeCallback Callback) const override
virtual void EnumerateEventsDownSampledAsync (const typename ITimeline< EventType >::EnumerateAsyncParams &EnumerateAsyncParams) const override
virtual int32 GetDepthAt (double Time) const override
virtual double GetEndTime () const override
virtual const EventType & GetEvent (uint64 InIndex) const override
virtual uint64 GetEventCount () const override
virtual bool GetEventInfo (double InTime, double DeltaTime, int32 Depth, typename ITimeline< InEventType >::FTimelineEventInfo &EventInfo) const override
virtual double GetLastTimestamp () const override
virtual uint64 GetModCount () const override
virtual double GetStartTime () const override
Public Member Functions inherited from TraceServices::ITimeline< InEventType >
virtual ~ITimeline ()=default
virtual void EnumerateEvents (double IntervalStart, double IntervalEnd, EventCallback Callback) const =0
virtual void EnumerateEvents (double IntervalStart, double IntervalEnd, EventRangeCallback Callback) const =0
virtual void EnumerateEventsBackwards (double IntervalEnd, double IntervalStart, EventCallback Callback) const
virtual void EnumerateEventsBackwards (double IntervalEnd, double IntervalStart, EventRangeCallback Callback) const
virtual void EnumerateEventsBackwardsDownSampled (double IntervalEnd, double IntervalStart, double Resolution, EventCallback Callback) const
virtual void EnumerateEventsBackwardsDownSampled (double IntervalEnd, double IntervalStart, double Resolution, EventRangeCallback Callback) const
virtual void EnumerateEventsDownSampled (double IntervalStart, double IntervalEnd, double Resolution, EventCallback Callback) const =0
virtual void EnumerateEventsDownSampled (double IntervalStart, double IntervalEnd, double Resolution, EventRangeCallback Callback) const =0
virtual void EnumerateEventsDownSampledAsync (const EnumerateAsyncParams &EnumerateAsyncParams) const
virtual bool GetEventInfo (double InTime, double DeltaTime, int32 Depth, FTimelineEventInfo &EventInfo) const =0
Finds event information for the event closest to InTime from the interval [InTime - DeltaTime, InTime + DeltaTime].
Public Member Functions inherited from TraceServices::IEditableTimeline< InEventType >
virtual ~IEditableTimeline ()=default
Private Types
typedef FDetailLevel< InEventType, SettingsType > FDetailLevel
typedef FDetailLevelDepthState< InEventType > FDetailLevelDepthState
typedef FEnumerateAsyncTask< InEventType, SettingsType > FEnumarateAsyncTask
typedef FEventInfoStackEntry< InEventType, SettingsType > FEventInfoStackEntry
Private Member Functions
void AddEvent (FDetailLevel &DetailLevel, const EventType &Event)
void AddScopeEntry (FDetailLevel &DetailLevel, double Time, bool IsEnter)
bool FindBestMatchEvent (const FFindBestMatchEventInParams &InParams, FFindBestMatchEventOutParams &OutParams) const
bool FindEventUsingPageInitialStack (typename TPagedArray< FEventScopeEntry, FEventScopeEntryPage >::TIterator ScopeEntryIterator, double Time, double DeltaTime, int32 Depth, const FDetailLevel &DetailLevel, FEventStackEntry &OutPageStackEntry) const
void UpdateDominatingEvent (FDetailLevel &DetailLevel, int32 Depth, double CurrentTime)
Private Attributes
ILinearAllocator & Allocator
TArray< FDetailLevel > DetailLevels
int32 ExtraDepthEvents = 0
uint64 ModCount = 0
Friends
class FEnumerateAsyncTask< InEventType, SettingsType >
Detailed Description
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings>
class TraceServices::TMonotonicTimeline< InEventType, SettingsType >
Definition at line 60 of file MonotonicTimeline.h.
Member Typedef Documentation
EventType
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> using TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EventType = InEventType
Definition at line 72 of file MonotonicTimeline.h.
FDetailLevel
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> typedef FDetailLevel<InEventType, SettingsType> TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FDetailLevel private
Definition at line 67 of file MonotonicTimeline.h.
FDetailLevelDepthState
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> typedef FDetailLevelDepthState<InEventType> TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FDetailLevelDepthState private
Definition at line 68 of file MonotonicTimeline.h.
FEnumarateAsyncTask
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> typedef FEnumerateAsyncTask<InEventType, SettingsType> TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FEnumarateAsyncTask private
Definition at line 69 of file MonotonicTimeline.h.
FEventInfoStackEntry
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> typedef FEventInfoStackEntry<InEventType, SettingsType> TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FEventInfoStackEntry private
Definition at line 66 of file MonotonicTimeline.h.
Constructor & Destructor Documentation
TMonotonicTimeline()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> TraceServices::TMonotonicTimeline< InEventType, SettingsType >::TMonotonicTimeline (ILinearAllocator & InAllocator) inline
Definition at line 74 of file MonotonicTimeline.h.
References Allocator, and DetailLevels.
~TMonotonicTimeline()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual TraceServices::TMonotonicTimeline< InEventType, SettingsType >::~TMonotonicTimeline () virtual default
Member Function Documentation
AddEvent()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AddEvent (FDetailLevel & DetailLevel, const EventType & Event) inline private
Definition at line 1243 of file MonotonicTimeline.h.
References TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::CurrentScopeEntryPageIndex, TraceServices::FEventScopeEntryPage::EndEventIndex, Event, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, TraceServices::TPagedArray< InItemType, InPageType >::PushBack(), and TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries.
Referenced by AppendBeginEvent().
AddScopeEntry()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AddScopeEntry (FDetailLevel & DetailLevel, double Time, bool IsEnter) inline private
Definition at line 1145 of file MonotonicTimeline.h.
References Allocator, TraceServices::FEventScopeEntryPage::BeginEventIndex, TraceServices::FEventScopeEntryPage::BeginTime, check, checkf, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::CurrentDepth, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::CurrentScopeEntryPageIndex, TraceServices::FEventScopeEntryPage::EndEventIndex, TraceServices::FEventScopeEntryPage::EndTime, TraceServices::FEventStackEntry::EndTime, TraceServices::FEventStackEntry::EnterScopeIndex, TraceServices::FEventStackEntry::EventIndex, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::EventStack, TraceServices::FEventStackEntry::ExclTime, TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::LastTime, TraceServices::TPagedArray< InItemType, InPageType >::Num(), TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, TEXT, Time, and TraceServices::FEventScopeEntry::Time.
Referenced by AppendBeginEvent(), and AppendEndEvent().
AppendBeginEvent()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AppendBeginEvent (double StartTime, const EventType & Event) inline override virtual
Implements TraceServices::IEditableTimeline< InEventType >.
Definition at line 91 of file MonotonicTimeline.h.
References AddEvent(), AddScopeEntry(), check, Depth, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::DepthStates, DetailLevels, TraceServices::FDetailLevelDepthState< EventType >::DominatingEvent, TraceServices::FDetailLevelDepthState< EventType >::DominatingEventDuration, TraceServices::FDetailLevelDepthState< EventType >::DominatingEventEndTime, TraceServices::FDetailLevelDepthState< EventType >::DominatingEventStartTime, TraceServices::FDetailLevelDepthState< EventType >::EnterTime, Event, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::FDetailLevelDepthState< EventType >::ExitTime, ExtraDepthEvents, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, ModCount, TraceServices::TPagedArray< InItemType, InPageType >::Num(), TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::PendingDepth, TraceServices::FDetailLevelDepthState< EventType >::PendingEventIndex, TraceServices::FDetailLevelDepthState< EventType >::PendingScopeEnterIndex, TraceServices::FDetailLevel< EventType, SettingsType >::Resolution, TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, and TraceServices::FDetailLevel< EventType, SettingsType >::SetEvent().
AppendEndEvent()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::AppendEndEvent (double EndTime) inline override virtual
Implements TraceServices::IEditableTimeline< InEventType >.
Definition at line 157 of file MonotonicTimeline.h.
References AddScopeEntry(), check, Depth, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::DepthStates, DetailLevels, TraceServices::FDetailLevelDepthState< EventType >::EnterTime, TraceServices::FDetailLevelDepthState< EventType >::ExitTime, ExtraDepthEvents, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, ModCount, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::PendingDepth, TraceServices::FDetailLevelDepthState< EventType >::PendingEventIndex, TraceServices::FDetailLevelDepthState< EventType >::PendingScopeEnterIndex, TraceServices::FDetailLevel< EventType, SettingsType >::Resolution, and UpdateDominatingEvent().
EnumerateEvents() [1/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEvents (double IntervalStart, double IntervalEnd, typename ITimeline< EventType >::EventCallback Callback) const inline override virtual
Definition at line 774 of file MonotonicTimeline.h.
References EnumerateEventsDownSampled().
EnumerateEvents() [2/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEvents (double IntervalStart, double IntervalEnd, typename ITimeline< EventType >::EventRangeCallback Callback) const inline override virtual
Definition at line 779 of file MonotonicTimeline.h.
References EnumerateEventsDownSampled().
EnumerateEventsBackwards() [1/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwards (double IntervalEnd, double IntervalStart, typename ITimeline< EventType >::EventCallback Callback) const inline override virtual
Definition at line 784 of file MonotonicTimeline.h.
References EnumerateEventsBackwardsDownSampled().
EnumerateEventsBackwards() [2/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwards (double IntervalEnd, double IntervalStart, typename ITimeline< EventType >::EventRangeCallback Callback) const inline override virtual
Definition at line 789 of file MonotonicTimeline.h.
References EnumerateEventsBackwardsDownSampled().
EnumerateEventsBackwardsDownSampled() [1/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwardsDownSampled (double IntervalEnd, double IntervalStart, double Resolution, typename ITimeline< EventType >::EventCallback Callback) const inline override virtual
Definition at line 401 of file MonotonicTimeline.h.
References TraceServices::FEventScopeEntryPage::BeginEventIndex, check, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::CurrentDepth, DetailLevels, TraceServices::FEventStackEntry::EndTime, TraceServices::FEventStackEntry::EnterScopeIndex, Event, TraceServices::FEventStackEntry::EventIndex, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::EventStack, TraceServices::FDetailLevel< EventType, SettingsType >::GetEvent(), TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem(), TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::LastTime, TraceServices::TPagedArray< InItemType, InPageType >::Num(), TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, TraceServices::Stop, TraceServices::FEventScopeEntry::Time, and Algo::UpperBoundBy().
Referenced by EnumerateEventsBackwards(), EnumerateEventsBackwards(), and EnumerateEventsBackwardsDownSampled().
EnumerateEventsBackwardsDownSampled() [2/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsBackwardsDownSampled (double IntervalEnd, double IntervalStart, double Resolution, typename ITimeline< EventType >::EventRangeCallback Callback) const inline override virtual
Definition at line 598 of file MonotonicTimeline.h.
References TraceServices::Continue, EnumerateEventsBackwardsDownSampled(), Event, and Time.
EnumerateEventsDownSampled() [1/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled (double IntervalStart, double IntervalEnd, double Resolution, typename ITimeline< EventType >::EventCallback Callback) const inline override virtual
Definition at line 227 of file MonotonicTimeline.h.
References TraceServices::FEventScopeEntryPage::BeginEventIndex, TraceServices::FEventScopeEntryPage::BeginTime, check, DetailLevels, TraceServices::FEventScopeEntryPage::EndTime, TraceServices::FEventStackEntry::EndTime, TraceServices::FEventStackEntry::EnterScopeIndex, Event, TraceServices::FEventStackEntry::EventIndex, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::FDetailLevel< EventType, SettingsType >::GetEvent(), TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem(), TraceServices::FDetailLevel< EventType, SettingsType >::GetScopeEntryTime(), TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::LastTime, TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, TraceServices::Stop, TraceServices::FEventScopeEntry::Time, and Algo::UpperBoundBy().
Referenced by EnumerateEvents(), EnumerateEvents(), and EnumerateEventsDownSampled().
EnumerateEventsDownSampled() [2/2]
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampled (double IntervalStart, double IntervalEnd, double Resolution, typename ITimeline< EventType >::EventRangeCallback Callback) const inline override virtual
Definition at line 718 of file MonotonicTimeline.h.
References TArray< InElementType, InAllocatorType >::AddDefaulted_GetRef(), TraceServices::Continue, Depth, EnumerateEventsDownSampled(), Event, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::Num(), and Time.
EnumerateEventsDownSampledAsync()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::EnumerateEventsDownSampledAsync (const typename ITimeline< EventType >::EnumerateAsyncParams & EnumerateAsyncParams) const inline override virtual
Definition at line 631 of file MonotonicTimeline.h.
References TArray< InElementType, InAllocatorType >::Add(), AsyncTask(), check, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::DetailLevel, DetailLevels, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::EndPageIndex, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::EndTime, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::EventCallback, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::EventCallback, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::EventRangeCallback, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::EventRangeCallback, GThreadPool, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::IntervalEnd, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::IntervalStart, MakeShared(), FMath::Max, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::MaxOccupancy, FMath::Min, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::NumTasks, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::Resolution, TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::SetupCallback, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::SortOrder, TraceServices::ITimeline< InEventType >::EnumerateAsyncParams::SortOrder, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::StartPageIndex, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::StartTime, TraceServices::FAsyncEnumerateTaskData< InEventType, SettingsType >::TaskIndex, and Algo::UpperBoundBy().
FindBestMatchEvent()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> bool TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FindBestMatchEvent (const FFindBestMatchEventInParams & InParams, FFindBestMatchEventOutParams & OutParams) const inline private
Definition at line 1307 of file MonotonicTimeline.h.
References TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::bHasEndTime, check, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::EndTime, Event, TraceServices::FEventInfoStackEntry< EventType, SettingsType >::Event, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::EventInfo, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::EventsIterator, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::EventStack, TraceServices::FEventInfoStackEntry< EventType, SettingsType >::ExclTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::IterationState, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::IterationState, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::LastIterationTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::ScopeIterator, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::StackDepth, TraceServices::FEventInfoStackEntry< EventType, SettingsType >::StartTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::TargetDepth, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::TargetEndTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::TargetExactTime, and TraceServices::FEventScopeEntry::Time.
Referenced by GetEventInfo().
FindEventUsingPageInitialStack()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> bool TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FindEventUsingPageInitialStack (typename TPagedArray< FEventScopeEntry, FEventScopeEntryPage >::TIterator ScopeEntryIterator, double Time, double DeltaTime, int32 Depth, const FDetailLevel & DetailLevel, FEventStackEntry & OutPageStackEntry) const inline private
Definition at line 1252 of file MonotonicTimeline.h.
References DeltaTime, Depth, TraceServices::FEventStackEntry::EndTime, TraceServices::FEventStackEntry::EnterScopeIndex, TraceServices::TPagedArrayIterator< ItemType, PageType >::GetCurrentPage(), TraceServices::FDetailLevel< EventType, SettingsType >::GetScopeEntryTime(), TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::TPagedArrayIterator< ItemType, PageType >::NextPage(), and Time.
Referenced by GetEventInfo().
GetDepthAt()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual int32 TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetDepthAt (double Time) const inline override virtual
Reimplemented from TraceServices::ITimeline< InEventType >.
Definition at line 1052 of file MonotonicTimeline.h.
References TraceServices::FEventScopeEntryPage::BeginTime, check, DetailLevels, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, Time, TraceServices::FEventScopeEntry::Time, and Algo::UpperBoundBy().
GetEndTime()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual double TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEndTime () const inline override virtual
Implements TraceServices::ITimeline< InEventType >.
Definition at line 221 of file MonotonicTimeline.h.
References DetailLevels, and Time.
GetEvent()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual const EventType & TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEvent (uint64 InIndex) const inline override virtual
Implements TraceServices::ITimeline< InEventType >.
Definition at line 211 of file MonotonicTimeline.h.
References DetailLevels.
GetEventCount()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual uint64 TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEventCount () const inline override virtual
Implements TraceServices::ITimeline< InEventType >.
Definition at line 206 of file MonotonicTimeline.h.
References DetailLevels.
GetEventInfo()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual bool TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetEventInfo (double InTime, double DeltaTime, int32 Depth, typename ITimeline< InEventType >::FTimelineEventInfo & EventInfo) const inline override virtual
Definition at line 794 of file MonotonicTimeline.h.
References TraceServices::FEventScopeEntryPage::BeginEventIndex, TraceServices::FEventScopeEntryPage::BeginTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::bHasEndTime, check, DeltaTime, Depth, DetailLevels, TraceServices::FEventStackEntry::EndTime, TraceServices::ITimeline< InEventType >::FTimelineEventInfo::EndTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::EndTime, TraceServices::FEventStackEntry::EnterScopeIndex, Event, TraceServices::FEventInfoStackEntry< EventType, SettingsType >::Event, TraceServices::ITimeline< InEventType >::FTimelineEventInfo::Event, TraceServices::FEventStackEntry::EventIndex, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::EventInfo, TraceServices::FDetailLevel< EventType, SettingsType >::Events, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::EventsIterator, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::EventStack, TraceServices::FEventInfoStackEntry< EventType, SettingsType >::ExclTime, TraceServices::FEventStackEntry::ExclTime, TraceServices::ITimeline< InEventType >::FTimelineEventInfo::ExclTime, FindBestMatchEvent(), FindEventUsingPageInitialStack(), TraceServices::FDetailLevel< EventType, SettingsType >::GetEvent(), TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem(), TraceServices::FDetailLevel< EventType, SettingsType >::GetScopeEntryTime(), TraceServices::FEventScopeEntryPage::InitialStack, TraceServices::FEventScopeEntryPage::InitialStackCount, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, InTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::IterationState, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventOutParams::IterationState, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::LastIterationTime, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::LastTime, FMath::Max, TraceServices::FDetailLevel< EventType, SettingsType >::ScopeEntries, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::ScopeIterator, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FIterationState::StackDepth, TraceServices::FEventInfoStackEntry< EventType, SettingsType >::StartTime, TraceServices::ITimeline< InEventType >::FTimelineEventInfo::StartTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::TargetDepth, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::TargetEndTime, TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FFindBestMatchEventInParams::TargetExactTime, TraceServices::FEventScopeEntry::Time, and Algo::UpperBoundBy().
GetLastTimestamp()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual double TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetLastTimestamp () const inline override virtual
Reimplemented from TraceServices::IEditableTimeline< InEventType >.
Definition at line 86 of file MonotonicTimeline.h.
References DetailLevels.
GetModCount()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual uint64 TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetModCount () const inline override virtual
Implements TraceServices::ITimeline< InEventType >.
Definition at line 201 of file MonotonicTimeline.h.
References ModCount.
GetStartTime()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> virtual double TraceServices::TMonotonicTimeline< InEventType, SettingsType >::GetStartTime () const inline override virtual
Implements TraceServices::ITimeline< InEventType >.
Definition at line 216 of file MonotonicTimeline.h.
References DetailLevels, and Time.
UpdateDominatingEvent()
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> void TraceServices::TMonotonicTimeline< InEventType, SettingsType >::UpdateDominatingEvent (FDetailLevel & DetailLevel, int32 Depth, double CurrentTime) inline private
Definition at line 1124 of file MonotonicTimeline.h.
References check, Depth, TraceServices::FDetailLevelInsertionState< EventType, SettingsType >::DepthStates, DetailLevels, TraceServices::FDetailLevelDepthState< EventType >::DominatingEvent, TraceServices::FDetailLevelDepthState< EventType >::DominatingEventDuration, TraceServices::FDetailLevelDepthState< EventType >::DominatingEventEndTime, TraceServices::FDetailLevelDepthState< EventType >::DominatingEventStartTime, TraceServices::FDetailLevelDepthState< EventType >::EnterTime, TraceServices::FDetailLevel< EventType, SettingsType >::InsertionState, TraceServices::FDetailLevelDepthState< EventType >::PendingEventIndex, TraceServices::FDetailLevelDepthState< EventType >::PendingScopeEnterIndex, and TraceServices::FDetailLevel< EventType, SettingsType >::SetEvent().
Referenced by AppendEndEvent().
Friends And Related Symbol Documentation
FEnumerateAsyncTask< InEventType, SettingsType >
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> friend class FEnumerateAsyncTask< InEventType, SettingsType > friend
Definition at line 56 of file MonotonicTimeline.h.
Field Documentation
Allocator
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> ILinearAllocator& TraceServices::TMonotonicTimeline< InEventType, SettingsType >::Allocator private
Definition at line 1441 of file MonotonicTimeline.h.
Referenced by TMonotonicTimeline(), and AddScopeEntry().
DetailLevels
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> TArray<FDetailLevel> TraceServices::TMonotonicTimeline< InEventType, SettingsType >::DetailLevels private
Definition at line 1442 of file MonotonicTimeline.h.
Referenced by TMonotonicTimeline(), AppendBeginEvent(), AppendEndEvent(), EnumerateEventsBackwardsDownSampled(), EnumerateEventsDownSampled(), EnumerateEventsDownSampledAsync(), GetDepthAt(), GetEndTime(), GetEvent(), GetEventCount(), GetEventInfo(), GetLastTimestamp(), GetStartTime(), and UpdateDominatingEvent().
ExtraDepthEvents
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> int32 TraceServices::TMonotonicTimeline< InEventType, SettingsType >::ExtraDepthEvents = 0 private
Definition at line 1443 of file MonotonicTimeline.h.
Referenced by AppendBeginEvent(), and AppendEndEvent().
ModCount
template<typename InEventType, typename SettingsType = FMonotonicTimelineDefaultSettings> uint64 TraceServices::TMonotonicTimeline< InEventType, SettingsType >::ModCount = 0 private
Definition at line 1444 of file MonotonicTimeline.h.
Referenced by AppendBeginEvent(), AppendEndEvent(), and GetModCount().
The documentation for this class was generated from the following file:
Developer/TraceServices/Public/Model/MonotonicTimeline.h