Unreal Engine 5.6 C++ API: FRDGExternalAccessQueue Class Reference
FRDGExternalAccessQueue Class Reference
Batches up RDG external resource access mode requests and submits them all at once to RDG.
#include "RenderGraphUtils.h"
Data Structures
struct FResource
Public Member Functions
FRDGExternalAccessQueue ()=default
~FRDGExternalAccessQueue ()
void Add (FRDGViewableResource *Resource, ERHIAccess Access=ERHIAccess::SRVMask, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
void AddUnique (FRDGViewableResource *Resource, ERHIAccess Access=ERHIAccess::SRVMask, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
bool Contains (FRDGViewableResource *Resource)
bool IsEmpty () const
void Reserve (uint32 ResourceCount)
RENDERCORE_API void Submit (FRDGBuilder &GraphBuilder)
Private Member Functions
void Validate (FRDGViewableResource *Resource, ERHIAccess Access, ERHIPipeline Pipelines)
Private Attributes
TArray< FResource, FRDGArrayAllocator > Resources
Detailed Description
Batches up RDG external resource access mode requests and submits them all at once to RDG.
Definition at line 1271 of file RenderGraphUtils.h.
Constructor & Destructor Documentation
FRDGExternalAccessQueue()
FRDGExternalAccessQueue::FRDGExternalAccessQueue () default
~FRDGExternalAccessQueue()
FRDGExternalAccessQueue::~FRDGExternalAccessQueue () inline
Definition at line 1276 of file RenderGraphUtils.h.
References checkf, IsEmpty(), and TEXT.
Member Function Documentation
Add()
void FRDGExternalAccessQueue::Add (FRDGViewableResource * Resource, ERHIAccess Access = ERHIAccess::SRVMask, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 1286 of file RenderGraphUtils.h.
References Access, Resources, and Validate().
Referenced by ConvertToExternalAccessBuffer(), and ConvertToExternalAccessTexture().
AddUnique()
void FRDGExternalAccessQueue::AddUnique (FRDGViewableResource * Resource, ERHIAccess Access = ERHIAccess::SRVMask, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 1297 of file RenderGraphUtils.h.
References Access, Contains(), Resources, and Validate().
Contains()
bool FRDGExternalAccessQueue::Contains (FRDGViewableResource * Resource) inline
Definition at line 1316 of file RenderGraphUtils.h.
References FRDGExternalAccessQueue::FResource::Resource, and Resources.
Referenced by AddUnique().
IsEmpty()
bool FRDGExternalAccessQueue::IsEmpty () const inline
Definition at line 1321 of file RenderGraphUtils.h.
References Resources.
Referenced by ~FRDGExternalAccessQueue().
Reserve()
void FRDGExternalAccessQueue::Reserve (uint32 ResourceCount) inline
Definition at line 1281 of file RenderGraphUtils.h.
References Resources.
Submit()
RENDERCORE_API void FRDGExternalAccessQueue::Submit (FRDGBuilder & GraphBuilder)
Validate()
void FRDGExternalAccessQueue::Validate (FRDGViewableResource * Resource, ERHIAccess Access, ERHIPipeline Pipelines) inline private
Definition at line 1327 of file RenderGraphUtils.h.
References Access, check, checkf, FRDGResource::Name, and TEXT.
Referenced by Add(), and AddUnique().
Field Documentation
Resources
TArray<FResource, FRDGArrayAllocator> FRDGExternalAccessQueue::Resources private
Definition at line 1348 of file RenderGraphUtils.h.
Referenced by Add(), AddUnique(), Contains(), IsEmpty(), and Reserve().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphUtils.h