Unreal Engine 5.6 C++ API: UE::Geometry::TBlockedGrid3Layout< BlockSize_ > Class Template Reference
UE::Geometry::TBlockedGrid3Layout< BlockSize_ > Class Template Reference
#include "BlockedLayout3.h"
Public Types
typedef TBlockData3Layout< BlockSize_ > FBlockData3Layout
Public Member Functions
TBlockedGrid3Layout ()
TBlockedGrid3Layout (FVector3i Dims)
TBlockedGrid3Layout (int32 DimI, int32 DimJ, int32 DimK)
int32 BlockIJKToBlockIndex (const FVector3i &BlockIJK) const
FVector3i BlockIndexToBlockIJK (const int32 BlockIndex) const
FAxisAlignedBox3i Bounds () const
FAxisAlignedBox3i BoundsInclusive () const
void GetBlockAndLocalIndex (const FVector3i &IJK, int32 &BlockIndexOut, int32 &LocalIndexOut) const
return the block index and local index of the cell at (I,J,K).
void GetBlockAndLocalIndex (int32 I, int32 J, int32 K, int32 &BlockIndexOut, int32 &LocalIndexOut) const
const FVector3i & GetBlockDimensions () const
const FVector3i & GetDimensions () const
int32 IJKtoBlockIndex (const FVector3i &IJK) const
bool IsValidBlockIJK (const FVector3i &BlockIJK)
bool IsValidIJK (const FVector3i &IJK) const
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Recompute the block dimensions required to cover the requested cell dimensions.
int64 Size () const
Static Public Attributes
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Protected Attributes
FVector3i BlockDimensions
FVector3i Dimensions
Detailed Description
template<int32 BlockSize_>
class UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
Definition at line 49 of file BlockedLayout3.h.
Member Typedef Documentation
FBlockData3Layout
template<int32 BlockSize_> typedef TBlockData3Layout<BlockSize_> UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::FBlockData3Layout
Definition at line 55 of file BlockedLayout3.h.
Constructor & Destructor Documentation
TBlockedGrid3Layout() [1/3]
template<int32 BlockSize_> UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::TBlockedGrid3Layout () inline
Definition at line 57 of file BlockedLayout3.h.
TBlockedGrid3Layout() [2/3]
template<int32 BlockSize_> UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::TBlockedGrid3Layout (int32 DimI, int32 DimJ, int32 DimK) inline
Definition at line 62 of file BlockedLayout3.h.
TBlockedGrid3Layout() [3/3]
template<int32 BlockSize_> UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::TBlockedGrid3Layout (FVector3i Dims) inline
Definition at line 67 of file BlockedLayout3.h.
Member Function Documentation
BlockIJKToBlockIndex()
template<int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::BlockIJKToBlockIndex (const FVector3i & BlockIJK) const inline
Returns
the block index for the specified block (BlockIJK) in a linearization of the 3d block space.
Definition at line 189 of file BlockedLayout3.h.
Referenced by UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockData(), UE::Geometry::TBlockedGrid3< float, 8 >::GetBlockData(), UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::IJKtoBlockIndex(), UE::Geometry::TBlockedGrid3< float, 8 >::ReadBlockDefaultValue(), UE::Geometry::TBlockedGrid3< float, 8 >::TouchBlockData(), and UE::Geometry::TBlockedGrid3< float, 8 >::WriteBlockDefaultValue().
BlockIndexToBlockIJK()
template<int32 BlockSize_> FVector3i UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::BlockIndexToBlockIJK (const int32 BlockIndex) const inline
Returns
the 3-d coordinates of the block specified by an index in a linearization of the blocks. BlockIJK is the lattice address of the block in terms of block units (e.g. the location in a grid of blocks).
Definition at line 176 of file BlockedLayout3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs().
Bounds()
template<int32 BlockSize_> FAxisAlignedBox3i UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::Bounds () const inline
Definition at line 105 of file BlockedLayout3.h.
BoundsInclusive()
template<int32 BlockSize_> FAxisAlignedBox3i UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::BoundsInclusive () const inline
Definition at line 113 of file BlockedLayout3.h.
GetBlockAndLocalIndex() [1/2]
template<int32 BlockSize_> void UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::GetBlockAndLocalIndex (const FVector3i & IJK, int32 & BlockIndexOut, int32 & LocalIndexOut) const inline
return the block index and local index of the cell at (I,J,K).
Definition at line 158 of file BlockedLayout3.h.
Referenced by UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::GetBlockAndLocalIndex(), UE::Geometry::TBlockedGrid3< float, 8 >::ProcessValueWithLock(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::ReadValue(), UE::Geometry::TBlockedGrid3< float, 8 >::SetValueWithLock(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::WriteValue().
GetBlockAndLocalIndex() [2/2]
template<int32 BlockSize_> void UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::GetBlockAndLocalIndex (int32 I, int32 J, int32 K, int32 & BlockIndexOut, int32 & LocalIndexOut) const inline
Definition at line 167 of file BlockedLayout3.h.
GetBlockDimensions()
template<int32 BlockSize_> const FVector3i & UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::GetBlockDimensions () const inline
Returns
the dimensions of this layout in terms of blocks.
Definition at line 97 of file BlockedLayout3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::AllocateTopologyUnionImpl(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), UE::Geometry::FBlock3< ElemType, BlockSize_ >::GetNumBlocks(), and UE::Geometry::TBlockedGrid3< float, 8 >::GetNumBlocks().
GetDimensions()
template<int32 BlockSize_> const FVector3i & UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::GetDimensions () const inline
Returns
the dimensions of this layout in terms of cell ijks.
Definition at line 89 of file BlockedLayout3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::AllocateTopologyUnionImpl(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial().
IJKtoBlockIndex()
template<int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::IJKtoBlockIndex (const FVector3i & IJK) const inline
Returns
the index of the block that holds the cell indicated by IJK.
Definition at line 149 of file BlockedLayout3.h.
Referenced by UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::GetBlockAndLocalIndex().
IsValidBlockIJK()
template<int32 BlockSize_> bool UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::IsValidBlockIJK (const FVector3i & BlockIJK) inline
Returns
true if the specified block IJK is within the bounds of the block dimensions.
Definition at line 140 of file BlockedLayout3.h.
IsValidIJK()
template<int32 BlockSize_> bool UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::IsValidIJK (const FVector3i & IJK) const inline
Returns
true if the specified cell IJK is within the bounds of the dimensions.
Definition at line 131 of file BlockedLayout3.h.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill().
Resize()
template<int32 BlockSize_> void UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::Resize (int32 DimI, int32 DimJ, int32 DimK) inline
Recompute the block dimensions required to cover the requested cell dimensions.
Definition at line 75 of file BlockedLayout3.h.
Referenced by UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::TBlockedGrid3Layout(), UE::Geometry::TBlockedGrid3Layout< FBlockedGrid3f::BlockSize >::TBlockedGrid3Layout(), and UE::Geometry::FBlock3< ElemType, BlockSize_ >::Resize().
Size()
template<int32 BlockSize_> int64 UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::Size () const inline
Returns
the number of ijk cells in contained within this grid layout. note: because blocks are 3d pages of fixed size so the number of Blocks X Cells in Block might actually be a larger.
Definition at line 123 of file BlockedLayout3.h.
Field Documentation
BlockDimensions
template<int32 BlockSize_> FVector3i UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::BlockDimensions protected
Definition at line 196 of file BlockedLayout3.h.
BlockElemCount
template<int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::BlockElemCount = BlockSize * BlockSize * BlockSize static constexpr
Definition at line 53 of file BlockedLayout3.h.
BlockSize
template<int32 BlockSize_> int32 UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::BlockSize = BlockSize_ static constexpr
Definition at line 52 of file BlockedLayout3.h.
Dimensions
template<int32 BlockSize_> FVector3i UE::Geometry::TBlockedGrid3Layout< BlockSize_ >::Dimensions protected
Definition at line 197 of file BlockedLayout3.h.
Referenced by UE::Geometry::FBlock3< ElemType, BlockSize_ >::Reset().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/BlockedLayout3.h