Unreal Engine 5.6 C++ API: IMovieSceneKeyProxy Class Reference
IMovieSceneKeyProxy Class Reference abstract
Interface that can be implemented by any object that is used as a key editing proxy for a moviescene channel.
#include "MovieSceneKeyProxy.h"
Public Member Functions
GENERATED_BODY () virtual void UpdateValuesFromRawData()=0
To be called by the edit interface to update this instance's properties with the underlying raw data.
Protected Member Functions
template<typename ChannelType, typename ValueType>
void OnProxyValueChanged (TMovieSceneChannelHandle< ChannelType > InChannelHandle, UMovieSceneSignedObject *InSignedObject, FKeyHandle InKeyHandle, ValueType &InOutValue, FFrameNumber &InOutTime)
Implementation function that sets the underlying key time/value to the specified values if possible.
template<typename ChannelType, typename ValueType>
void RefreshCurrentValue (TMovieSceneChannelHandle< ChannelType > InChannelHandle, FKeyHandle InKeyHandle, ValueType &OutValue, FFrameNumber &OutTime)
Implementation function that retrieves the underlying key time/value and applies then to the specified value and time parameters.
Detailed Description
Interface that can be implemented by any object that is used as a key editing proxy for a moviescene channel.
When used, UpdateValuesFromRawData should be called every frame to optionally retrieve the current values of the key for this proxy.
Definition at line 26 of file MovieSceneKeyProxy.h.
Member Function Documentation
GENERATED_BODY()
IMovieSceneKeyProxy::GENERATED_BODY () pure virtual
To be called by the edit interface to update this instance's properties with the underlying raw data.
References OnProxyValueChanged(), and RefreshCurrentValue().
OnProxyValueChanged()
template<typename ChannelType, typename ValueType> void IMovieSceneKeyProxy::OnProxyValueChanged (TMovieSceneChannelHandle< ChannelType > InChannelHandle, UMovieSceneSignedObject * InSignedObject, FKeyHandle InKeyHandle, ValueType & InOutValue, FFrameNumber & InOutTime) protected
Implementation function that sets the underlying key time/value to the specified values if possible.
If the section is locked, InOutValue and InOutTime will be reset back to the current key's value
Parameters
InChannelHandle The channel on which the underlying key value resides
InSection The section that owns the channel
InKeyHandle A handle to the key that we are reflecting
InOutValue Value to assign to the underlying key. If the section is locked, this will receive the existing key's value without changing the underlying key value.
InOutTime Time to move the underlying key to. If the section is locked, this will receive the existing key's time without changing the underlying time.
Definition at line 67 of file MovieSceneKeyProxy.h.
References Cast(), INDEX_NONE, and OnProxyValueChanged().
Referenced by GENERATED_BODY(), and OnProxyValueChanged().
RefreshCurrentValue()
template<typename ChannelType, typename ValueType> void IMovieSceneKeyProxy::RefreshCurrentValue (TMovieSceneChannelHandle< ChannelType > InChannelHandle, FKeyHandle InKeyHandle, ValueType & OutValue, FFrameNumber & OutTime) protected
Implementation function that retrieves the underlying key time/value and applies then to the specified value and time parameters.
Normally called once per tick.
Parameters
InChannelHandle The channel on which the underlying key value resides
InKeyHandle A handle to the key that we are reflecting
OutValue (Out) Value to receive the underlying key's value
OutTime (Out) Time to receive the underlying key time
Definition at line 112 of file MovieSceneKeyProxy.h.
References TMovieSceneChannelHandle< ChannelType >::Get(), INDEX_NONE, and FMath::Min.
Referenced by GENERATED_BODY().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/MovieSceneKeyProxy.h