Unreal Engine 5.6 C++ API: FUniformExpressionSet Class Reference
FUniformExpressionSet Class Reference
Stores all uniform expressions for a material generated from a material translation.
#include "MaterialShared.h"
Data Structures
union FVTPackedStackAndLayerIndex
Public Member Functions
FUniformExpressionSet ()
uint32 AddDefaultParameterValue (const UE::Shader::FValue &Value)
void AddNumericParameterEvaluation (uint32 ParameterIndex, uint32 BufferOffset)
Adds a new direct parameter evaluation for parameter with specified index (returned by FindOrAddNumericParameter) BufferOffset is the location in the uniform buffer in which to evaluate the parameter (in multiple of float components).
int32 AddVTLayer (int32 StackIndex, int32 TextureIndex)
int32 AddVTStack (int32 InPreallocatedStackTextureIndex)
uint32 AllocateFromUniformBuffer (uint32 SizeInBytes)
FShaderParametersMetadata * CreateBufferStruct ()
void FillUniformBuffer (const FMaterialRenderContext &MaterialRenderContext, const FUniformExpressionCache &UniformExpressionCache, const FRHIUniformBufferLayout *UniformBufferLayout, uint8 *TempBuffer, int TempBufferSize) const
void FillUniformBuffer (const FMaterialRenderContext &MaterialRenderContext, TConstArrayView< IAllocatedVirtualTexture * > AllocatedVTs, const FRHIUniformBufferLayout *UniformBufferLayout, uint8 *TempBuffer, int TempBufferSize) const
int32 FindOrAddExternalTextureParameter (const FMaterialExternalTextureParameterInfo &Info)
int32 FindOrAddNumericParameter (EMaterialParameterType Type, const FMaterialParameterInfo &ParameterInfo, uint32 DefaultValueOffset)
int32 FindOrAddTextureCollectionParameter (const FMaterialTextureCollectionParameterInfo &Info)
int32 FindOrAddTextureParameter (EMaterialTextureParameterType Type, const FMaterialTextureParameterInfo &Info)
const uint8 * GetDefaultParameterData (uint32 Offset) const
UE::Shader::FValue GetDefaultParameterValue (EMaterialParameterType Type, uint32 Offset) const
void GetGameThreadTextureCollectionValue (int32 Index, const UMaterialInterface *MaterialInterface, const FMaterial &Material, UTextureCollection *&OutValue) const
void GetGameThreadTextureValue (EMaterialTextureParameterType Type, int32 Index, const UMaterialInterface *MaterialInterface, const FMaterial &Material, UTexture *&OutValue, bool bAllowOverride=true) const
const FMaterialNumericParameterInfo & GetNumericParameter (uint32 Index) const
uint32 GetNumericParameterEvaluationOffset (uint32 ParameterIndex) const
Returns the offset of specified parameter given with AddNumericParameterEvaluation.
int32 GetNumTextureCollections () const
int32 GetNumTextures (EMaterialTextureParameterType Type) const
uint32 GetReferencedTexture2DRHIHash (const FMaterialRenderContext &MaterialRenderContext) const
FString GetSummaryString () const
const FMaterialTextureCollectionParameterInfo & GetTextureCollectionParameter (int32 Index) const
const FMaterialTextureParameterInfo & GetTextureParameter (EMaterialTextureParameterType Type, int32 Index) const
void GetTextureValue (EMaterialTextureParameterType Type, int32 Index, const FMaterialRenderContext &Context, const FMaterial &Material, const UTexture *&OutValue) const
void GetTextureValue (int32 Index, const FMaterialRenderContext &Context, const FMaterial &Material, const URuntimeVirtualTexture *&OutValue) const
void GetTextureValue (int32 Index, const FMaterialRenderContext &Context, const FMaterial &Material, const USparseVolumeTexture *&OutValue) const
const FRHIUniformBufferLayoutInitializer & GetUniformBufferLayoutInitializer () const
const FMaterialVirtualTextureStack & GetVTStack (int32 Index) const
TConstArrayView< FMaterialVirtualTextureStack > GetVTStacks () const
bool HasExternalTextureExpressions () const
bool IsEmpty () const
bool operator== (const FUniformExpressionSet &ReferenceSet) const
void SetParameterCollections (TConstArrayView< const class UMaterialParameterCollection * > Collections)
void SetVTLayer (int32 StackIndex, int32 VTLayerIndex, int32 TextureIndex)
Protected Member Functions
FVTPackedStackAndLayerIndex GetVTStackAndLayerIndex (int32 UniformExpressionIndex) const
LAYOUT_ARRAY (TMemoryImageArray< FMaterialTextureParameterInfo >, UniformTextureParameters, NumMaterialTextureParameterTypes)
LAYOUT_FIELD (FRHIUniformBufferLayoutInitializer, UniformBufferLayoutInitializer)
LAYOUT_FIELD (TMemoryImageArray< FGuid >, ParameterCollections)
Ids of parameter collections referenced by the material that was translated.
LAYOUT_FIELD (TMemoryImageArray< FMaterialExternalTextureParameterInfo >, UniformExternalTextureParameters)
LAYOUT_FIELD (TMemoryImageArray< FMaterialNumericParameterInfo >, UniformNumericParameters)
LAYOUT_FIELD (TMemoryImageArray< FMaterialTextureCollectionParameterInfo >, UniformTextureCollectionParameters)
LAYOUT_FIELD (TMemoryImageArray< FMaterialUniformParameterEvaluation >, UniformParameterEvaluations)
LAYOUT_FIELD (TMemoryImageArray< FMaterialUniformPreshaderField >, UniformPreshaderFields)
LAYOUT_FIELD (TMemoryImageArray< FMaterialUniformPreshaderHeader >, UniformPreshaders)
LAYOUT_FIELD (TMemoryImageArray< FMaterialVirtualTextureStack >, VTStacks)
Virtual texture stacks found during compilation.
LAYOUT_FIELD (TMemoryImageArray< uint8 >, DefaultValues)
LAYOUT_FIELD (UE::Shader::FPreshaderData, UniformPreshaderData)
LAYOUT_FIELD (uint32, UniformPreshaderBufferSize)
Private Member Functions
DECLARE_TYPE_LAYOUT (FUniformExpressionSet, NonVirtual)
Friends
class FDebugUniformExpressionSet
class FHLSLMaterialTranslator
class FMaterial
class FMaterialRenderProxy
class FMaterialShader
class FMaterialShaderMap
class FMaterialVirtualTextureStack
Detailed Description
Stores all uniform expressions for a material generated from a material translation.
Definition at line 640 of file MaterialShared.h.
Constructor & Destructor Documentation
FUniformExpressionSet()
FUniformExpressionSet::FUniformExpressionSet () inline
Definition at line 644 of file MaterialShared.h.
Referenced by DECLARE_TYPE_LAYOUT(), and operator==().
Member Function Documentation
AddDefaultParameterValue()
uint32 FUniformExpressionSet::AddDefaultParameterValue (const UE::Shader::FValue & Value)
References Value.
AddNumericParameterEvaluation()
void FUniformExpressionSet::AddNumericParameterEvaluation (uint32 ParameterIndex, uint32 BufferOffset)
Adds a new direct parameter evaluation for parameter with specified index (returned by FindOrAddNumericParameter) BufferOffset is the location in the uniform buffer in which to evaluate the parameter (in multiple of float components).
AddVTLayer()
int32 FUniformExpressionSet::AddVTLayer (int32 StackIndex, int32 TextureIndex)
AddVTStack()
int32 FUniformExpressionSet::AddVTStack (int32 InPreallocatedStackTextureIndex)
AllocateFromUniformBuffer()
uint32 FUniformExpressionSet::AllocateFromUniformBuffer (uint32 SizeInBytes)
CreateBufferStruct()
FShaderParametersMetadata * FUniformExpressionSet::CreateBufferStruct ()
DECLARE_TYPE_LAYOUT()
FUniformExpressionSet::DECLARE_TYPE_LAYOUT (FUniformExpressionSet , NonVirtual) private
References FUniformExpressionSet().
FillUniformBuffer() [1/2]
void FUniformExpressionSet::FillUniformBuffer (const FMaterialRenderContext & MaterialRenderContext, const FUniformExpressionCache & UniformExpressionCache, const FRHIUniformBufferLayout * UniformBufferLayout, uint8 * TempBuffer, int TempBufferSize) const
FillUniformBuffer() [2/2]
void FUniformExpressionSet::FillUniformBuffer (const FMaterialRenderContext & MaterialRenderContext, TConstArrayView< IAllocatedVirtualTexture * > AllocatedVTs, const FRHIUniformBufferLayout * UniformBufferLayout, uint8 * TempBuffer, int TempBufferSize) const
FindOrAddExternalTextureParameter()
int32 FUniformExpressionSet::FindOrAddExternalTextureParameter (const FMaterialExternalTextureParameterInfo & Info)
References Info.
FindOrAddNumericParameter()
int32 FUniformExpressionSet::FindOrAddNumericParameter (EMaterialParameterType Type, const FMaterialParameterInfo & ParameterInfo, uint32 DefaultValueOffset)
FindOrAddTextureCollectionParameter()
int32 FUniformExpressionSet::FindOrAddTextureCollectionParameter (const FMaterialTextureCollectionParameterInfo & Info)
References Info.
FindOrAddTextureParameter()
int32 FUniformExpressionSet::FindOrAddTextureParameter (EMaterialTextureParameterType Type, const FMaterialTextureParameterInfo & Info)
References Info.
GetDefaultParameterData()
const uint8 * FUniformExpressionSet::GetDefaultParameterData (uint32 Offset) const inline
Definition at line 676 of file MaterialShared.h.
GetDefaultParameterValue()
UE::Shader::FValue FUniformExpressionSet::GetDefaultParameterValue (EMaterialParameterType Type, uint32 Offset) const inline
Definition at line 671 of file MaterialShared.h.
References UE::Shader::FValue::FromMemoryImage(), and GetShaderValueType().
GetGameThreadTextureCollectionValue()
void FUniformExpressionSet::GetGameThreadTextureCollectionValue (int32 Index, const UMaterialInterface * MaterialInterface, const FMaterial & Material, UTextureCollection *& OutValue) const
References FMaterial, and Material.
GetGameThreadTextureValue()
void FUniformExpressionSet::GetGameThreadTextureValue (EMaterialTextureParameterType Type, int32 Index, const UMaterialInterface * MaterialInterface, const FMaterial & Material, UTexture *& OutValue, bool bAllowOverride = true) const
References FMaterial, and Material.
GetNumericParameter()
const FMaterialNumericParameterInfo & FUniformExpressionSet::GetNumericParameter (uint32 Index) const inline
Definition at line 681 of file MaterialShared.h.
GetNumericParameterEvaluationOffset()
uint32 FUniformExpressionSet::GetNumericParameterEvaluationOffset (uint32 ParameterIndex) const
Returns the offset of specified parameter given with AddNumericParameterEvaluation.
GetNumTextureCollections()
int32 FUniformExpressionSet::GetNumTextureCollections () const inline
Definition at line 691 of file MaterialShared.h.
GetNumTextures()
int32 FUniformExpressionSet::GetNumTextures (EMaterialTextureParameterType Type) const inline
Definition at line 685 of file MaterialShared.h.
References Num.
GetReferencedTexture2DRHIHash()
uint32 FUniformExpressionSet::GetReferencedTexture2DRHIHash (const FMaterialRenderContext & MaterialRenderContext) const
GetSummaryString()
FString FUniformExpressionSet::GetSummaryString () const
GetTextureCollectionParameter()
const FMaterialTextureCollectionParameterInfo & FUniformExpressionSet::GetTextureCollectionParameter (int32 Index) const inline
Definition at line 683 of file MaterialShared.h.
GetTextureParameter()
const FMaterialTextureParameterInfo & FUniformExpressionSet::GetTextureParameter (EMaterialTextureParameterType Type, int32 Index) const inline
Definition at line 682 of file MaterialShared.h.
GetTextureValue() [1/3]
void FUniformExpressionSet::GetTextureValue (EMaterialTextureParameterType Type, int32 Index, const FMaterialRenderContext & Context, const FMaterial & Material, const UTexture *& OutValue) const
References FMaterial, and Material.
GetTextureValue() [2/3]
void FUniformExpressionSet::GetTextureValue (int32 Index, const FMaterialRenderContext & Context, const FMaterial & Material, const URuntimeVirtualTexture *& OutValue) const
References FMaterial, and Material.
GetTextureValue() [3/3]
void FUniformExpressionSet::GetTextureValue (int32 Index, const FMaterialRenderContext & Context, const FMaterial & Material, const USparseVolumeTexture *& OutValue) const
References FMaterial, and Material.
GetUniformBufferLayoutInitializer()
const FRHIUniformBufferLayoutInitializer & FUniformExpressionSet::GetUniformBufferLayoutInitializer () const inline
Definition at line 666 of file MaterialShared.h.
GetVTStack()
const FMaterialVirtualTextureStack & FUniformExpressionSet::GetVTStack (int32 Index) const inline
Definition at line 710 of file MaterialShared.h.
References FMaterialVirtualTextureStack.
GetVTStackAndLayerIndex()
FVTPackedStackAndLayerIndex FUniformExpressionSet::GetVTStackAndLayerIndex (int32 UniformExpressionIndex) const protected
GetVTStacks()
TConstArrayView< FMaterialVirtualTextureStack > FUniformExpressionSet::GetVTStacks () const inline
Definition at line 709 of file MaterialShared.h.
HasExternalTextureExpressions()
bool FUniformExpressionSet::HasExternalTextureExpressions () const inline
Definition at line 661 of file MaterialShared.h.
IsEmpty()
bool FUniformExpressionSet::IsEmpty () const
LAYOUT_ARRAY()
FUniformExpressionSet::LAYOUT_ARRAY (TMemoryImageArray< FMaterialTextureParameterInfo > , UniformTextureParameters , NumMaterialTextureParameterTypes) protected
References NumMaterialTextureParameterTypes.
LAYOUT_FIELD() [1/12]
FUniformExpressionSet::LAYOUT_FIELD (FRHIUniformBufferLayoutInitializer , UniformBufferLayoutInitializer) protected
LAYOUT_FIELD() [2/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FGuid > , ParameterCollections) protected
Ids of parameter collections referenced by the material that was translated.
LAYOUT_FIELD() [3/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialExternalTextureParameterInfo > , UniformExternalTextureParameters) protected
LAYOUT_FIELD() [4/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialNumericParameterInfo > , UniformNumericParameters) protected
LAYOUT_FIELD() [5/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialTextureCollectionParameterInfo > , UniformTextureCollectionParameters) protected
LAYOUT_FIELD() [6/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialUniformParameterEvaluation > , UniformParameterEvaluations) protected
LAYOUT_FIELD() [7/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialUniformPreshaderField > , UniformPreshaderFields) protected
LAYOUT_FIELD() [8/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialUniformPreshaderHeader > , UniformPreshaders) protected
LAYOUT_FIELD() [9/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< FMaterialVirtualTextureStack > , VTStacks) protected
Virtual texture stacks found during compilation.
LAYOUT_FIELD() [10/12]
FUniformExpressionSet::LAYOUT_FIELD (TMemoryImageArray< uint8 > , DefaultValues) protected
LAYOUT_FIELD() [11/12]
FUniformExpressionSet::LAYOUT_FIELD (UE::Shader::FPreshaderData , UniformPreshaderData) protected
LAYOUT_FIELD() [12/12]
FUniformExpressionSet::LAYOUT_FIELD (uint32 , UniformPreshaderBufferSize) protected
operator==()
bool FUniformExpressionSet::operator== (const FUniformExpressionSet & ReferenceSet) const
References FUniformExpressionSet().
SetParameterCollections()
void FUniformExpressionSet::SetParameterCollections (TConstArrayView< const class UMaterialParameterCollection * > Collections)
SetVTLayer()
void FUniformExpressionSet::SetVTLayer (int32 StackIndex, int32 VTLayerIndex, int32 TextureIndex)
Friends And Related Symbol Documentation
FDebugUniformExpressionSet
friend class FDebugUniformExpressionSet friend
Definition at line 736 of file MaterialShared.h.
References FDebugUniformExpressionSet.
Referenced by FDebugUniformExpressionSet.
FHLSLMaterialTranslator
friend class FHLSLMaterialTranslator friend
Definition at line 731 of file MaterialShared.h.
References FHLSLMaterialTranslator.
Referenced by FHLSLMaterialTranslator.
FMaterial
friend class FMaterial friend
Definition at line 730 of file MaterialShared.h.
References FMaterial.
Referenced by FMaterial, GetGameThreadTextureCollectionValue(), GetGameThreadTextureValue(), GetTextureValue(), GetTextureValue(), and GetTextureValue().
FMaterialRenderProxy
friend class FMaterialRenderProxy friend
Definition at line 734 of file MaterialShared.h.
References FMaterialRenderProxy.
Referenced by FMaterialRenderProxy.
FMaterialShader
friend class FMaterialShader friend
Definition at line 733 of file MaterialShared.h.
References FMaterialShader.
Referenced by FMaterialShader.
FMaterialShaderMap
friend class FMaterialShaderMap friend
Definition at line 732 of file MaterialShared.h.
References FMaterialShaderMap.
Referenced by FMaterialShaderMap.
FMaterialVirtualTextureStack
friend class FMaterialVirtualTextureStack friend
Definition at line 735 of file MaterialShared.h.
References FMaterialVirtualTextureStack.
Referenced by FMaterialVirtualTextureStack, and GetVTStack().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialShared.h