Unreal Engine 5.6 C++ API: FAsyncTaskBase Class Reference
FAsyncTaskBase Class Reference abstract
#include "AsyncWork.h"
Public Member Functions
virtual ~FAsyncTaskBase ()
Destructor, not legal when a task is in process.
bool Cancel ()
Cancel the task, if possible.
void EnsureCompletion (bool bDoWorkOnThisThreadIfNotStarted=true, bool bIsLatencySensitive=false)
Wait until the job is complete.
const TCHAR * GetDebugName () const final
Returns text to identify the Work, for debug/log purposes only.
EQueuedWorkPriority GetPriority () const
int64 GetRequiredMemory () const final
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
bool IsDone ()
Returns true if the work and TASK has completed, false while it's still in progress.
bool IsIdle () const
Returns true if the work has not been started or has been completed.
bool IsWorkDone () const
Returns true if the work has completed, false while it's still in progress.
bool Reschedule (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal)
If not already being processed, will be rescheduled on given thread pool and priority.
bool SetPriority (EQueuedWorkPriority QueuedWorkPriority)
void StartBackgroundTask (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags=EQueuedWorkFlags::None, int64 InRequiredMemory=-1, const TCHAR *InDebugName=nullptr)
Queue this task for processing by the background thread pool.
void StartSynchronousTask (EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags=EQueuedWorkFlags::None, int64 InRequiredMemory=-1, const TCHAR *InDebugName=nullptr)
Run this task on this thread.
bool WaitCompletionWithTimeout (float TimeLimitSeconds)
Wait until the job is complete, up to a time limit.
Protected Member Functions
void CheckIdle () const
Internal call to assert that we are idle.
virtual void DoTaskWork ()=0
Perform task's work.
void Init (TStatId InStatId)
virtual void MarkAsCanceled ()
Mark the task as canceled (i.e.
virtual bool TryAbandonTask ()=0
Abandon task if possible, returns true on success, false otherwise.
Private Member Functions
void Abandon () final
Always called from the thread pool.
void DestroyEvent ()
void DoThreadedWork () final
Performs the work, this is only called from a pool thread.
void DoWork ()
Tells the user job to do the work, sometimes called synchronously, sometimes from the thread pool.
void FinishThreadedWork ()
Triggers the work completion event, only called from a pool thread.
EQueuedWorkFlags GetQueuedWorkFlags () const final
Returns any special work flags.
void Start (bool bForceSynchronous, FQueuedThreadPool *InQueuedPool, EQueuedWorkPriority InQueuedWorkPriority, EQueuedWorkFlags InQueuedWorkFlags, int64 InRequiredMemory, const TCHAR *InDebugName)
void SyncCompletion (bool bIsLatencySensitive)
Internal call to synchronize completion between threads, never called from a pool thread.
Private Member Functions inherited from UE::FInheritedContextBase
void CaptureInheritedContext ()
FInheritedContextScope RestoreInheritedContext ()
Private Member Functions inherited from IQueuedWork
virtual ~IQueuedWork ()
Virtual destructor so that child implementations are guaranteed a chance to clean up any resources they allocated.
Private Attributes
const TCHAR * DebugName = nullptr
Text to identify the Task; used for debug/log purposes only.
FEvent * DoneEvent = nullptr
If we aren't doing the work synchronously, this will hold the completion event.
EQueuedWorkFlags Flags = EQueuedWorkFlags::None
Current flags.
EQueuedWorkPriority Priority = EQueuedWorkPriority::Normal
Current priority.
FQueuedThreadPool * QueuedPool = nullptr
Pool we are queued into, maintained by the calling thread.
int64 RequiredMemory = -1
Approximation of the peak memory (in bytes) this task could require during it's execution.
TStatId StatId
StatId used for FScopeCycleCounter.
FThreadSafeCounter WorkNotFinishedCounter
Thread safe counter that indicates WORK completion, no necessarily finalization of the job.
Private Attributes inherited from IQueuedWork
IInternalDataType InternalData
Additional Inherited Members
Private Types inherited from IQueuedWork
using IInternalDataType = TRefCountPtr<IQueuedWorkInternalData>
Internal data can be used by the pool.
Detailed Description
FAsyncTask - template task for jobs queued to thread pools
Sample code:
class ExampleAsyncTask : public FNonAbandonableTask
{
    friend class FAsyncTask<ExampleAsyncTask>;
    int32 ExampleData;
    ExampleAsyncTask(int32 InExampleData)
     : ExampleData(InExampleData)
    {
    }
    void DoWork()
    {
        ... do the work here
    }
    FORCEINLINE TStatId GetStatId() const
    {
        RETURN_QUICK_DECLARE_CYCLE_STAT(ExampleAsyncTask, STATGROUP_ThreadPoolAsyncTasks);
    }
};
void Example()
{
start an example job
    FAsyncTask<ExampleAsyncTask>* MyTask = new FAsyncTask<ExampleAsyncTask>( 5 );
    MyTask->StartBackgroundTask();
–or –
    MyTask->StartSynchronousTask();
to just do it now on this thread Check if the task is done :
    if (MyTask->IsDone())
    {
    }
Spinning on IsDone is not acceptable(see EnsureCompletion), but it is ok to check once a frame. Ensure the task is done, doing the task on the current thread if it has not been started, waiting until completion in all cases.
    MyTask->EnsureCompletion();
    delete Task;
}
Definition at line 206 of file AsyncWork.h.
Constructor & Destructor Documentation
~FAsyncTaskBase()
virtual FAsyncTaskBase::~FAsyncTaskBase () inline virtual
Destructor, not legal when a task is in process.
Definition at line 387 of file AsyncWork.h.
References CheckIdle(), and DestroyEvent().
Member Function Documentation
Abandon()
void FAsyncTaskBase::Abandon (void) inline final private virtual
Always called from the thread pool.
Called if the task is removed from queue before it has started which might happen at exit. If the user job can abandon, we do that, otherwise we force the work to be done now (doing nothing would not be safe).
Implements IQueuedWork.
Definition at line 320 of file AsyncWork.h.
References check, DoWork(), FinishThreadedWork(), TryAbandonTask(), and WorkNotFinishedCounter.
Cancel()
bool FAsyncTaskBase::Cancel () inline
Cancel the task, if possible.
Note that this is different than abandoning (which is called by the thread pool at shutdown).
Returns
true if the task was canceled and is safe to delete. If it wasn't canceled, it may be done, but that isn't checked here.
Definition at line 482 of file AsyncWork.h.
References check, FinishThreadedWork(), IsWorkDone(), MarkAsCanceled(), QueuedPool, and WorkNotFinishedCounter.
CheckIdle()
void FAsyncTaskBase::CheckIdle () const inline protected
Internal call to assert that we are idle.
Definition at line 363 of file AsyncWork.h.
References check, FDebug::DumpStackTraceToLog(), QueuedPool, ELogVerbosity::Warning, and WorkNotFinishedCounter.
Referenced by ~FAsyncTaskBase(), EnsureCompletion(), FAsyncTask< FAsyncSoundWavePCMWriteWorker >::GetTask(), FAsyncTask< FAsyncSoundWavePCMWriteWorker >::GetTask(), Start(), SyncCompletion(), and WaitCompletionWithTimeout().
DestroyEvent()
void FAsyncTaskBase::DestroyEvent () inline private
Definition at line 229 of file AsyncWork.h.
References DoneEvent, and FGenericPlatformProcess::ReturnSynchEventToPool().
Referenced by ~FAsyncTaskBase(), and Start().
DoTaskWork()
virtual void FAsyncTaskBase::DoTaskWork () protected pure virtual
Perform task's work.
Implemented in FAsyncTask< TTask >, FAsyncTask< class FAsyncAudioDecompressWorker >, FAsyncTask< DeleteTaskType >, FAsyncTask< FAsyncAudioDecompressWorker >, FAsyncTask< FAsyncRealtimeAudioTaskWorker< T > >, FAsyncTask< FAsyncSoundWavePCMWriteWorker >, FAsyncTask< FAsyncStreamDerivedChunkWorker >, FAsyncTask< FGroomBindingAsyncBuildWorker >, FAsyncTask< FSkinnedAssetAsyncBuildWorker >, FAsyncTask< FStaticMeshAsyncBuildWorker >, and FAsyncTask< UE::Geometry::TModelingOpTask< OpType > >.
Referenced by DoWork().
DoThreadedWork()
void FAsyncTaskBase::DoThreadedWork () inline final private virtual
Performs the work, this is only called from a pool thread.
Implements IQueuedWork.
Definition at line 310 of file AsyncWork.h.
References DoWork(), and FinishThreadedWork().
DoWork()
void FAsyncTaskBase::DoWork () inline private
Tells the user job to do the work, sometimes called synchronously, sometimes from the thread pool.
Calls the event tracker.
Definition at line 283 of file AsyncWork.h.
References check, DoTaskWork(), UE::FInheritedContextBase::RestoreInheritedContext(), StatId, and WorkNotFinishedCounter.
Referenced by Abandon(), DoThreadedWork(), EnsureCompletion(), and Start().
EnsureCompletion()
void FAsyncTaskBase::EnsureCompletion (bool bDoWorkOnThisThreadIfNotStarted = true, bool bIsLatencySensitive = false) inline
Wait until the job is complete.
Parameters
bDoWorkOnThisThreadIfNotStarted if true and the work has not been started, retract the async task and do it now on this thread
specifies if waiting for the task should return as soon as possible even if this delays other tasks
Definition at line 429 of file AsyncWork.h.
References CheckIdle(), DoWork(), FinishThreadedWork(), QueuedPool, SyncCompletion(), and WorkNotFinishedCounter.
FinishThreadedWork()
void FAsyncTaskBase::FinishThreadedWork () inline private
Triggers the work completion event, only called from a pool thread.
Definition at line 296 of file AsyncWork.h.
References check, DECLARE_SCOPE_CYCLE_COUNTER, DoneEvent, QueuedPool, StatId, and TEXT.
Referenced by Abandon(), Cancel(), DoThreadedWork(), and EnsureCompletion().
GetDebugName()
const TCHAR * FAsyncTaskBase::GetDebugName () const inline final virtual
Returns text to identify the Work, for debug/log purposes only.
Reimplemented from IQueuedWork.
Definition at line 402 of file AsyncWork.h.
References DebugName.
GetPriority()
EQueuedWorkPriority FAsyncTaskBase::GetPriority () const inline
Definition at line 576 of file AsyncWork.h.
References Priority.
GetQueuedWorkFlags()
EQueuedWorkFlags FAsyncTaskBase::GetQueuedWorkFlags () const inline final private virtual
Returns any special work flags.
Reimplemented from IQueuedWork.
Definition at line 235 of file AsyncWork.h.
References Flags.
GetRequiredMemory()
int64 FAsyncTaskBase::GetRequiredMemory () const inline final virtual
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
Reimplemented from IQueuedWork.
Definition at line 397 of file AsyncWork.h.
References RequiredMemory.
Init()
void FAsyncTaskBase::Init (TStatId InStatId) inline protected
Definition at line 355 of file AsyncWork.h.
References StatId.
IsDone()
bool FAsyncTaskBase::IsDone () inline
Returns true if the work and TASK has completed, false while it's still in progress.
prior to returning true, it synchronizes so the task can be destroyed or reused
Definition at line 540 of file AsyncWork.h.
References IsWorkDone(), and SyncCompletion().
Referenced by WaitCompletionWithTimeout().
IsIdle()
bool FAsyncTaskBase::IsIdle () const inline
Returns true if the work has not been started or has been completed.
NOT to be used for synchronization, but great for check()'s
Definition at line 566 of file AsyncWork.h.
References QueuedPool, and WorkNotFinishedCounter.
IsWorkDone()
bool FAsyncTaskBase::IsWorkDone () const inline
Returns true if the work has completed, false while it's still in progress.
This does not block and if true, you can use the results. But you can't destroy or reuse the task without IsDone() being true or EnsureCompletion()
Definition at line 554 of file AsyncWork.h.
References WorkNotFinishedCounter.
Referenced by Cancel(), and IsDone().
MarkAsCanceled()
virtual void FAsyncTaskBase::MarkAsCanceled () inline protected virtual
Mark the task as canceled (i.e.
no longer needed).
Reimplemented in FAsyncTask< TTask >, FAsyncTask< class FAsyncAudioDecompressWorker >, FAsyncTask< DeleteTaskType >, FAsyncTask< FAsyncAudioDecompressWorker >, FAsyncTask< FAsyncRealtimeAudioTaskWorker< T > >, FAsyncTask< FAsyncSoundWavePCMWriteWorker >, FAsyncTask< FAsyncStreamDerivedChunkWorker >, FAsyncTask< FGroomBindingAsyncBuildWorker >, FAsyncTask< FSkinnedAssetAsyncBuildWorker >, FAsyncTask< FStaticMeshAsyncBuildWorker >, and FAsyncTask< UE::Geometry::TModelingOpTask< OpType > >.
Definition at line 381 of file AsyncWork.h.
Referenced by Cancel().
Reschedule()
bool FAsyncTaskBase::Reschedule (FQueuedThreadPool * InQueuedPool = GThreadPool, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) inline
If not already being processed, will be rescheduled on given thread pool and priority.
Returns
true if the reschedule was successful, false if was already being processed.
Definition at line 461 of file AsyncWork.h.
References GThreadPool, Normal, Priority, and QueuedPool.
Referenced by SetPriority().
SetPriority()
bool FAsyncTaskBase::SetPriority (EQueuedWorkPriority QueuedWorkPriority) inline
Definition at line 571 of file AsyncWork.h.
References QueuedPool, and Reschedule().
Start()
void FAsyncTaskBase::Start (bool bForceSynchronous, FQueuedThreadPool * InQueuedPool, EQueuedWorkPriority InQueuedWorkPriority, EQueuedWorkFlags InQueuedWorkFlags, int64 InRequiredMemory, const TCHAR * InDebugName) inline private
Definition at line 243 of file AsyncWork.h.
References UE::FInheritedContextBase::CaptureInheritedContext(), CheckIdle(), DebugName, DECLARE_SCOPE_CYCLE_COUNTER, DestroyEvent(), DoneEvent, DoWork(), Flags, FGenericPlatformProcess::GetSynchEventFromPool(), FAndroidMisc::MemoryBarrier(), Priority, QueuedPool, RequiredMemory, StatId, TEXT, and WorkNotFinishedCounter.
Referenced by StartBackgroundTask(), and StartSynchronousTask().
StartBackgroundTask()
void FAsyncTaskBase::StartBackgroundTask (FQueuedThreadPool * InQueuedPool = GThreadPool, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags = EQueuedWorkFlags::None, int64 InRequiredMemory = -1, const TCHAR * InDebugName = nullptr) inline
Queue this task for processing by the background thread pool.
Definition at line 419 of file AsyncWork.h.
References GThreadPool, None, Normal, and Start().
Referenced by UE::Geometry::FAsyncTaskExecuterWithAbort< TTask >::CancelAndDelete().
StartSynchronousTask()
void FAsyncTaskBase::StartSynchronousTask (EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags = EQueuedWorkFlags::None, int64 InRequiredMemory = -1, const TCHAR * InDebugName = nullptr) inline
Run this task on this thread.
Parameters
bDoNow if true then do the job now instead of at EnsureCompletion
Definition at line 411 of file AsyncWork.h.
References GThreadPool, None, Normal, and Start().
SyncCompletion()
void FAsyncTaskBase::SyncCompletion (bool bIsLatencySensitive) inline private
Internal call to synchronize completion between threads, never called from a pool thread.
Parameters
bIsLatencySensitive specifies if waiting for the task should return as soon as possible even if this delays other tasks
Definition at line 338 of file AsyncWork.h.
References check, CheckIdle(), DECLARE_SCOPE_CYCLE_COUNTER, DoneEvent, FAndroidMisc::MemoryBarrier(), QueuedPool, StatId, SyncCompletion(), TEXT, and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by EnsureCompletion(), IsDone(), and SyncCompletion().
TryAbandonTask()
virtual bool FAsyncTaskBase::TryAbandonTask () protected pure virtual
Abandon task if possible, returns true on success, false otherwise.
Implemented in FAsyncTask< TTask >, FAsyncTask< class FAsyncAudioDecompressWorker >, FAsyncTask< DeleteTaskType >, FAsyncTask< FAsyncAudioDecompressWorker >, FAsyncTask< FAsyncRealtimeAudioTaskWorker< T > >, FAsyncTask< FAsyncSoundWavePCMWriteWorker >, FAsyncTask< FAsyncStreamDerivedChunkWorker >, FAsyncTask< FGroomBindingAsyncBuildWorker >, FAsyncTask< FSkinnedAssetAsyncBuildWorker >, FAsyncTask< FStaticMeshAsyncBuildWorker >, and FAsyncTask< UE::Geometry::TModelingOpTask< OpType > >.
Referenced by Abandon().
WaitCompletionWithTimeout()
bool FAsyncTaskBase::WaitCompletionWithTimeout (float TimeLimitSeconds) inline
Wait until the job is complete, up to a time limit.
Parameters
TimeLimitSeconds Must be positive, otherwise polls – same as calling IsDone()
Returns
true if the task is completed
Definition at line 508 of file AsyncWork.h.
References check, CheckIdle(), DECLARE_SCOPE_CYCLE_COUNTER, DoneEvent, IsDone(), FAndroidMisc::MemoryBarrier(), QueuedPool, StatId, and TEXT.
Field Documentation
DebugName
const TCHAR* FAsyncTaskBase::DebugName = nullptr private
Text to identify the Task; used for debug/log purposes only.
Definition at line 223 of file AsyncWork.h.
Referenced by GetDebugName(), and Start().
DoneEvent
FEvent* FAsyncTaskBase::DoneEvent = nullptr private
If we aren't doing the work synchronously, this will hold the completion event.
Definition at line 213 of file AsyncWork.h.
Referenced by DestroyEvent(), FinishThreadedWork(), Start(), SyncCompletion(), and WaitCompletionWithTimeout().
Flags
EQueuedWorkFlags FAsyncTaskBase::Flags = EQueuedWorkFlags::None private
Current flags.
Definition at line 219 of file AsyncWork.h.
Referenced by GetQueuedWorkFlags(), and Start().
Priority
EQueuedWorkPriority FAsyncTaskBase::Priority = EQueuedWorkPriority::Normal private
Current priority.
Definition at line 217 of file AsyncWork.h.
Referenced by GetPriority(), Reschedule(), and Start().
QueuedPool
FQueuedThreadPool* FAsyncTaskBase::QueuedPool = nullptr private
Pool we are queued into, maintained by the calling thread.
Definition at line 215 of file AsyncWork.h.
Referenced by Cancel(), CheckIdle(), EnsureCompletion(), FinishThreadedWork(), IsIdle(), Reschedule(), SetPriority(), Start(), SyncCompletion(), and WaitCompletionWithTimeout().
RequiredMemory
int64 FAsyncTaskBase::RequiredMemory = -1 private
Approximation of the peak memory (in bytes) this task could require during it's execution.
Definition at line 221 of file AsyncWork.h.
Referenced by GetRequiredMemory(), and Start().
StatId
TStatId FAsyncTaskBase::StatId private
StatId used for FScopeCycleCounter.
Definition at line 225 of file AsyncWork.h.
Referenced by DoWork(), FinishThreadedWork(), Init(), Start(), SyncCompletion(), and WaitCompletionWithTimeout().
WorkNotFinishedCounter
FThreadSafeCounter FAsyncTaskBase::WorkNotFinishedCounter private
Thread safe counter that indicates WORK completion, no necessarily finalization of the job.
Definition at line 211 of file AsyncWork.h.
Referenced by Abandon(), Cancel(), CheckIdle(), DoWork(), EnsureCompletion(), IsIdle(), IsWorkDone(), and Start().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/AsyncWork.h