Unreal Engine 5.6 C++ API: FModuleManager Class Reference
FModuleManager Class Reference
Implements the module manager.
#include "ModuleManager.h"
Data Structures
class FModuleInfo
Information about a single module (may or may not be loaded.)
struct FPrivateToken
Public Member Functions
FModuleManager (const FModuleManager &)=delete
FModuleManager (FPrivateToken)
Hidden constructor.
~FModuleManager ()
Destructor.
void AbandonModule (const FName InModuleName)
Abandons a loaded module, leaving it loaded in memory but no longer tracking it in the module manager.
void AbandonModuleWithCallback (const FName InModuleName)
Calls PreUnload then abandons a module in memory.
void AddBinariesDirectory (const TCHAR *InDirectory, bool bIsGameDirectory)
Adds an engine binaries directory.
void AddExtraBinarySearchPaths ()
Add any extra search paths that may be required.
void AddModule (const FName InModuleName)
Adds a module to our list of modules, unless it's already known.
void AddModuleToModulesList (const FName InModuleName, FModuleManager::ModuleInfoRef &ModuleInfo)
DECLARE_DELEGATE_RetVal (IModuleInterface *, FInitializeStaticallyLinkedModule) void RegisterStaticallyLinkedModule(const FLazyName InModuleName
Delegate that's used by the module manager to initialize a registered module that we statically linked with (monolithic only)
DECLARE_DELEGATE_RetVal_OneParam (bool, FIsPackageLoadedCallback, FName)
Gets a delegate that is executed when a module containing UObjects has been loaded.
bool DoesLoadedModuleHaveUObjects (const FName ModuleName) const
Determines whether the specified module contains UObjects.
void FindModules (const TCHAR *WildcardWithoutExtension, TArray< FModuleDiskInfo > &OutModules) const
void FindModules (const TCHAR *WildcardWithoutExtension, TArray< FName > &OutModules) const
Finds module files on the disk for loadable modules matching the specified wildcard.
FString GetGameBinariesDirectory () const
Gets the game binaries directory.
IModuleInterface * GetModule (const FName InModuleName)
Gets the specified module.
int32 GetModuleCount () const
Gets the number of loaded modules.
FString GetModuleFilename (FName ModuleName) const
Gets the filename for a module.
bool HasAnyOverridenModuleFilename () const
Determines if any non-default module instances are loaded (eg.
bool IsModuleLoaded (const FName InModuleName) const
Checks whether the specified module is currently loaded.
bool IsModuleUpToDate (const FName InModuleName) const
Checks to see if the specified module exists and is compatible with the current engine version.
FIsPackageLoadedCallback & IsPackageLoadedCallback ()
IModuleInterface * LoadModule (const FName InModuleName, ELoadModuleFlags InLoadModuleFlags=ELoadModuleFlags::None)
Loads the specified module.
void LoadModuleBinaryOnly (FName ModuleName)
Will load the binary without doing initialization.
IModuleInterface & LoadModuleChecked (const FName InModuleName)
Loads the specified module, checking to ensure it exists.
bool LoadModuleWithCallback (const FName InModuleName, FOutputDevice &Ar)
Loads a module in memory then calls PostLoad.
IModuleInterface * LoadModuleWithFailureReason (const FName InModuleName, EModuleLoadResult &OutFailureReason, ELoadModuleFlags InLoadModuleFlags=ELoadModuleFlags::None)
Loads the specified module and returns a result.
void MakeUniqueModuleFilename (const FName InModuleName, FString &UniqueSuffix, FString &UniqueModuleFileName) const
Generates a unique file name for the specified module name by adding a random suffix and checking for file collisions.
bool ModuleExists (const TCHAR *ModuleName, FString *OutModuleFilePath=nullptr) const
Determines if a module with the given name exists, regardless of whether it is currently loaded.
TDelegateRegistration< bool(TConstArrayView< FName >)> & OnCheckLiveObjectsInModulesCallback ()
Gets a delegate that is executed whenever we need to confirm that modules can be safely unloaded.
TTSMulticastDelegateRegistration< void(FName ModuleName, EModuleChangeReason ChangeReason)> & OnModulesChanged ()
void OnObjectCleanup ()
Signal that objects used by an unloading dynamic library should be cleaned up now.
TMulticastDelegateRegistration< void(FName, bool)> & OnProcessLoadedObjectsCallback ()
TMulticastDelegateRegistration< void(TConstArrayView< FName >)> & OnRemoveLoadedObjectsCallback ()
Gets a multicast delegate that is executed when any UObjects need destroying before modules are unloaded.
FModuleManager & operator= (const FModuleManager &)=delete
bool QueryModule (const FName InModuleName, FModuleStatus &OutModuleStatus) const
Queries information about a specific module name.
void QueryModules (TArray< FModuleStatus > &OutModuleStatuses) const
Queries information about all of the currently known modules.
void RefreshModuleFilenameFromManifest (const FName InModuleName)
void ResetModulePathsCache ()
Clears module path cache.
void SaveCurrentStateForBootstrap (const TCHAR *Filename)
Save the current module manager's state into a file for bootstrapping other processes.
void SetGameBinariesDirectory (const TCHAR *InDirectory)
Set the game binaries directory.
void SetModuleFilename (FName ModuleName, const FString &Filename)
Sets the filename for a module.
void StartProcessingNewlyLoadedObjects ()
Called by the engine at startup to let the Module Manager know that it's now safe to process new UObjects discovered by loading C++ modules.
bool UnloadModule (const FName InModuleName, bool bIsShutdown=false, bool bAllowUnloadCode=true)
Unloads a specific module NOTE: You can manually unload a module before the normal shutdown occurs with this, but be careful as you may be unloading another module's dependency too early!
void UnloadModulesAtShutdown ()
Unloads modules during the shutdown process.
void UnloadOrAbandonModuleWithCallback (const FName InModuleName, FOutputDevice &Ar)
Calls PreUnload then either unloads or abandons a module in memory, depending on whether the module supports unloading.
Static Public Member Functions
static FModuleManager & Get ()
Gets the singleton instance of the module manager.
template<typename TModuleInterface>
static TModuleInterface & GetModuleChecked (const FName ModuleName)
Gets a module by name, checking to ensure it exists.
template<typename TModuleInterface>
static FORCEINLINE TModuleInterface * GetModulePtr (const FName ModuleName)
Gets a module by name.
static const TCHAR * GetUBTConfiguration ()
Gets the build configuration for compiling modules, as required by UBT.
template<typename TModuleInterface>
static TModuleInterface & LoadModuleChecked (const FName InModuleName)
Loads a module by name, checking to ensure it exists.
template<typename TModuleInterface>
static TModuleInterface * LoadModulePtr (const FName InModuleName)
Loads a module by name.
static void TearDown ()
Destroys singleton if it exists.
Data Fields
const FInitializeStaticallyLinkedModule & InInitializerDelegate
Protected Member Functions
virtual bool Exec_Dev (UWorld *Inworld, const TCHAR *Cmd, FOutputDevice &Ar) override
Implementation of Exec that is only called in non-shipping targets.
Private Types
typedef TMap< FName, ModuleInfoRef > FModuleMap
Type definition for maps of module names to module infos.
typedef TSharedPtr< FModuleInfo, ESPMode::ThreadSafe > ModuleInfoPtr
typedef TSharedRef< FModuleInfo, ESPMode::ThreadSafe > ModuleInfoRef
Private Member Functions
ModuleInfoPtr FindModule (FName InModuleName)
Thread safe module finding routine.
FORCEINLINE TSharedPtr< const FModuleInfo, ESPMode::ThreadSafe > FindModule (FName InModuleName) const
ModuleInfoRef FindModuleChecked (FName InModuleName)
FORCEINLINE TSharedRef< const FModuleInfo, ESPMode::ThreadSafe > FindModuleChecked (FName InModuleName) const
void FindModulePaths (const TCHAR *NamePattern, TMap< FName, FString > &OutModulePaths) const
Finds modules matching a given name wildcard.
void FindModulePathsInDirectory (const FString &DirectoryName, bool bIsGameDirectory, TMap< FName, FString > &OutModulePaths) const
Finds modules within a given directory.
IModuleInterface * GetOrLoadModule (const FName InModuleName, EModuleLoadResult &OutFailureReason, ELoadModuleFlags InLoadModuleFlags=ELoadModuleFlags::None)
void InternalFreeLibrary (FName ModuleName, void *Handle)
Attempt to free the backing library for a module.
void * InternalLoadLibrary (FName ModuleName, const FString &ModuleFileToLoad)
Load the library for a given module.
void ProcessPendingStaticallyLinkedModuleInitializers () const
Adds pending module initializer registrations to the StaticallyLinkedModuleInitializers map.
void RefreshModuleFilenameFromManifestImpl (const FName InModuleName, FModuleInfo &ModuleInfo)
Refreshes the filename of a new module from the manifest.
void SerializeStateForBootstrap_Impl (FArchive &Ar)
Serialize a bootstrapping state into or from an archive.
Private Member Functions inherited from FSelfRegisteringExec
FSelfRegisteringExec ()
Constructor, registering this instance.
virtual ~FSelfRegisteringExec ()
Destructor, unregistering this instance.
Private Member Functions inherited from FExec
virtual ~FExec ()
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Exec handler.
virtual bool Exec_Editor (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in editor.
virtual bool Exec_Runtime (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is called on all targets where UE_ALLOW_EXEC_COMMANDS is true.
Static Private Member Functions
static IModuleInterface * GetModulePtr_Internal (FName ModuleName)
static void WarnIfItWasntSafeToLoadHere (const FName InModuleName)
Static Private Member Functions inherited from FSelfRegisteringExec
static bool StaticExec (UWorld *Inworld, const TCHAR *Cmd, FOutputDevice &Ar)
Routes a command to the self-registered execs.
Private Attributes
bool bCanProcessNewlyLoadedObjects
True if module manager should automatically register new UObjects discovered while loading C++ modules.
bool bExtraBinarySearchPathsAdded
True once AddExtraBinarySearchPaths has been called.
TOptional< FString > BuildId
ID used to validate module manifests.
TDelegate< bool(TConstArrayView< FName >)> CheckLiveObjectsInModulesCallback
Delegate called to check whether any module to delay-unload still has live objects.
TArray< FString > EngineBinariesDirectories
Array of engine binaries directories.
TArray< FString > GameBinariesDirectories
Array of game binaries directories.
FIsPackageLoadedCallback IsPackageLoaded
When module manager is linked against an application that supports UObjects, this delegate will be primed at startup to provide information about whether a UObject package is loaded into memory.
TMap< FName, FString > ModulePathsCache
Cache of known module paths.
FModuleMap Modules
Map of all modules.
TTSMulticastDelegate< void(FName ModuleName, EModuleChangeReason ChangeReason)> ModulesChangedEvent
Multicast delegate that will broadcast a notification when modules are loaded, unloaded, or our set of known modules changes.
FCriticalSection ModulesCriticalSection
Critical section object controlling R/W access to Modules.
TArray< FString > PendingEngineBinariesDirectories
TArray< FString > PendingGameBinariesDirectories
TArray< TPair< FLazyName, FInitializeStaticallyLinkedModule >, TInlineAllocator< 16 > > PendingStaticallyLinkedModuleInitializers
Pending registrations of module names.
TMulticastDelegate< void(FName, bool)> ProcessLoadedObjectsCallback
Multicast delegate called to process any new loaded objects.
TMulticastDelegate< void(TConstArrayView< FName >)> RemoveLoadedObjectsCallback
Multicast delegate called to remove any loaded objects for a list of modules.
TMap< FName, FInitializeStaticallyLinkedModule > StaticallyLinkedModuleInitializers
Map of module names to a delegate that can initialize each respective statically linked module.
Friends
FArchive & operator<< (FArchive &Ar, FModuleManager &ModuleManager)
TOptional< FModuleManager > & UE::Core::Private::GetModuleManagerSingleton ()
Detailed Description
Implements the module manager.
The module manager is used to load and unload modules, as well as to keep track of all of the modules that are currently loaded. You can access this singleton using FModuleManager::Get().
Definition at line 170 of file ModuleManager.h.
Member Typedef Documentation
FModuleMap
typedef TMap<FName, ModuleInfoRef> FModuleManager::FModuleMap private
Type definition for maps of module names to module infos.
Definition at line 642 of file ModuleManager.h.
ModuleInfoPtr
typedef TSharedPtr<FModuleInfo, ESPMode::ThreadSafe> FModuleManager::ModuleInfoPtr private
Definition at line 638 of file ModuleManager.h.
ModuleInfoRef
typedef TSharedRef<FModuleInfo, ESPMode::ThreadSafe> FModuleManager::ModuleInfoRef private
Definition at line 639 of file ModuleManager.h.
Constructor & Destructor Documentation
~FModuleManager()
FModuleManager::~FModuleManager ()
Destructor.
FModuleManager() [1/2]
FModuleManager::FModuleManager (FPrivateToken)
Hidden constructor.
Use the static Get function to return the singleton instance.
Referenced by FModuleManager(), FindModule(), FindModuleChecked(), Get(), GetModuleChecked(), operator<<, and operator=().
FModuleManager() [2/2]
FModuleManager::FModuleManager (const FModuleManager &) delete
References FModuleManager().
Member Function Documentation
AbandonModule()
void FModuleManager::AbandonModule (const FName InModuleName)
Abandons a loaded module, leaving it loaded in memory but no longer tracking it in the module manager.
Parameters
InModuleName The name of the module to abandon. Should not include path, extension or platform/configuration info. This is just the "module name" part of the module file name.
See also
IsModuleLoaded, LoadModule, LoadModuleWithFailureReason, UnloadModule
AbandonModuleWithCallback()
void FModuleManager::AbandonModuleWithCallback (const FName InModuleName)
Calls PreUnload then abandons a module in memory.
Parameters
InModuleName The name of the module to unload.
See also
LoadModuleWithCallback
AddBinariesDirectory()
void FModuleManager::AddBinariesDirectory (const TCHAR * InDirectory, bool bIsGameDirectory)
Adds an engine binaries directory.
AddExtraBinarySearchPaths()
void FModuleManager::AddExtraBinarySearchPaths ()
Add any extra search paths that may be required.
AddModule()
void FModuleManager::AddModule (const FName InModuleName)
Adds a module to our list of modules, unless it's already known.
Parameters
InModuleName The base name of the module file. Should not include path, extension or platform/configuration info. This is just the "name" part of the module file name. Names should be globally unique.
AddModuleToModulesList()
void FModuleManager::AddModuleToModulesList (const FName InModuleName, FModuleManager::ModuleInfoRef & ModuleInfo)
DECLARE_DELEGATE_RetVal()
FModuleManager::DECLARE_DELEGATE_RetVal (IModuleInterface * , FInitializeStaticallyLinkedModule) const
Delegate that's used by the module manager to initialize a registered module that we statically linked with (monolithic only)
Registers an initializer for a module that is statically linked.
Parameters
InModuleName The name of this module.
InInitializerDelegate The delegate that will be called to initialize an instance of this module.
DECLARE_DELEGATE_RetVal_OneParam()
FModuleManager::DECLARE_DELEGATE_RetVal_OneParam (bool , FIsPackageLoadedCallback , FName)
Gets a delegate that is executed when a module containing UObjects has been loaded.
The first parameter is the name of the loaded module.
Returns
The event delegate.
DoesLoadedModuleHaveUObjects()
bool FModuleManager::DoesLoadedModuleHaveUObjects (const FName ModuleName) const
Determines whether the specified module contains UObjects.
The module must already be loaded into memory before calling this function.
Parameters
ModuleName Name of the loaded module to check.
Returns
True if the module was found to contain UObjects, or false if it did not (or wasn't loaded.)
Exec_Dev()
virtual bool FModuleManager::Exec_Dev (UWorld * InWorld, const TCHAR * Cmd, FOutputDevice & Ar) override protected virtual
Implementation of Exec that is only called in non-shipping targets.
Reimplemented from FExec.
References Ar, and Cmd.
FindModule() [1/2]
ModuleInfoPtr FModuleManager::FindModule (FName InModuleName) private
Thread safe module finding routine.
Referenced by FindModule().
FindModule() [2/2]
FORCEINLINE TSharedPtr< const FModuleInfo, ESPMode::ThreadSafe > FModuleManager::FindModule (FName InModuleName) const inline private
Definition at line 679 of file ModuleManager.h.
References FModuleManager(), FindModule(), and FORCEINLINE.
FindModuleChecked() [1/2]
ModuleInfoRef FModuleManager::FindModuleChecked (FName InModuleName) private
Referenced by FindModuleChecked().
FindModuleChecked() [2/2]
FORCEINLINE TSharedRef< const FModuleInfo, ESPMode::ThreadSafe > FModuleManager::FindModuleChecked (FName InModuleName) const inline private
Definition at line 684 of file ModuleManager.h.
References FModuleManager(), FindModuleChecked(), and FORCEINLINE.
FindModulePaths()
void FModuleManager::FindModulePaths (const TCHAR * NamePattern, TMap< FName, FString > & OutModulePaths) const private
Finds modules matching a given name wildcard.
FindModulePathsInDirectory()
void FModuleManager::FindModulePathsInDirectory (const FString & DirectoryName, bool bIsGameDirectory, TMap< FName, FString > & OutModulePaths) const private
Finds modules within a given directory.
FindModules() [1/2]
void FModuleManager::FindModules (const TCHAR * WildcardWithoutExtension, TArray< FModuleDiskInfo > & OutModules) const
FindModules() [2/2]
void FModuleManager::FindModules (const TCHAR * WildcardWithoutExtension, TArray< FName > & OutModules) const
Finds module files on the disk for loadable modules matching the specified wildcard.
Parameters
WildcardWithoutExtension Filename part (no path, no extension, no build config info) to search for.
OutModules List of modules found.
Get()
FModuleManager & FModuleManager::Get () static
Gets the singleton instance of the module manager.
Returns
The module manager instance.
References FModuleManager().
Referenced by FModuleObserver::FModuleObserver(), FStaticallyLinkedModuleRegistrant< ModuleClass >::FStaticallyLinkedModuleRegistrant(), FModuleObserver::~FModuleObserver(), ICurveEditorModule::Get(), GetModuleChecked(), IAIModule::IsAvailable(), ICameraPhotographyModule::IsAvailable(), IChaosCachingEditorPlugin::IsAvailable(), IChaosCachingPlugin::IsAvailable(), IChaosFleshEditorPlugin::IsAvailable(), IChaosFleshEnginePlugin::IsAvailable(), IChaosModularVehicleEditorPlugin::IsAvailable(), IChaosModularVehicleEnginePlugin::IsAvailable(), IChaosModularVehiclePlugin::IsAvailable(), IChaosSolverEditorPlugin::IsAvailable(), IChaosVehiclesEditorPlugin::IsAvailable(), IChaosVehiclesPlugin::IsAvailable(), ICommonUIModule::IsAvailable(), ICurveEditorModule::IsAvailable(), ICustomMeshComponentPlugin::IsAvailable(), IDisplayCluster::IsAvailable(), IDisplayClusterColorGrading::IsAvailable(), IDisplayClusterConfiguration::IsAvailable(), IDisplayClusterConfigurator::IsAvailable(), IDisplayClusterDetails::IsAvailable(), IDisplayClusterLightCardEditor::IsAvailable(), IDisplayClusterLightCardEditorShaders::IsAvailable(), IDisplayClusterLightCardExtenderModule::IsAvailable(), IDisplayClusterOperator::IsAvailable(), IDisplayClusterProjection::IsAvailable(), IDisplayClusterScenePreview::IsAvailable(), IDisplayClusterShaders::IsAvailable(), IDisplayClusterWarp::IsAvailable(), IGameplayAbilitiesModule::IsAvailable(), IGameplayTagsModule::IsAvailable(), IGameplayTasksModule::IsAvailable(), ILiveLinkOverNDisplayModule::IsAvailable(), IMeshDescriptionModule::IsAvailable(), IMovieSceneModule::IsAvailable(), IMovieSceneTracksModule::IsAvailable(), INetworkPredictionModule::IsAvailable(), IPixelStreaming2EditorModule::IsAvailable(), IPixelStreaming2HMDModule::IsAvailable(), IPixelStreaming2InputModule::IsAvailable(), IPixelStreaming2Module::IsAvailable(), IPixelStreaming2RTCModule::IsAvailable(), IPixelStreamingEditorModule::IsAvailable(), IPixelStreamingHMDModule::IsAvailable(), IPixelStreamingInputModule::IsAvailable(), IPixelStreamingModule::IsAvailable(), IProceduralMeshComponentEditorPlugin::IsAvailable(), IProceduralMeshComponentPlugin::IsAvailable(), ISmartObjectsModule::IsAvailable(), IStateTreeModule::IsAvailable(), IWebBrowserWidgetModule::IsAvailable(), LoadModuleChecked(), LoadModulePtr(), and SRigVMBulkEditDialog< InWidgetType >::ShowNormal().
GetGameBinariesDirectory()
FString FModuleManager::GetGameBinariesDirectory () const
Gets the game binaries directory.
GetModule()
IModuleInterface * FModuleManager::GetModule (const FName InModuleName)
Gets the specified module.
Parameters
InModuleName Name of the module to return.
Returns
The module, or nullptr if the module is not loaded.
See also
GetModuleChecked, GetModulePtr
Referenced by GetModuleChecked().
GetModuleChecked()
template<typename TModuleInterface> TModuleInterface & FModuleManager::GetModuleChecked (const FName ModuleName) inline static
Gets a module by name, checking to ensure it exists.
This method checks whether the module actually exists. If the module does not exist, an assertion will be triggered.
Parameters
ModuleName The module to get.
Returns
The interface to the module.
See also
GetModulePtr, LoadModulePtr, LoadModuleChecked
Definition at line 334 of file ModuleManager.h.
References FModuleManager(), checkf, Get(), GetModule(), IsModuleLoaded(), TEXT, and FName::ToString().
Referenced by AnimationEditorUtils::CreateAnimationAsset(), ICurveEditorModule::Get(), IDisplayCluster::Get(), IDisplayClusterColorGrading::Get(), IDisplayClusterConfiguration::Get(), IDisplayClusterConfigurator::Get(), IDisplayClusterDetails::Get(), IDisplayClusterLightCardEditor::Get(), IDisplayClusterLightCardEditorShaders::Get(), IDisplayClusterOperator::Get(), IDisplayClusterScenePreview::Get(), IMovieSceneModule::Get_Concurrent(), ICommonUIModule::GetEditorSettings(), and ICommonUIModule::GetSettings().
GetModuleCount()
int32 FModuleManager::GetModuleCount () const
Gets the number of loaded modules.
Returns
The number of modules.
GetModuleFilename()
FString FModuleManager::GetModuleFilename (FName ModuleName) const
Gets the filename for a module.
The return value is a full path of a module known to the module manager.
GetModulePtr()
template<typename TModuleInterface> FORCEINLINE TModuleInterface * FModuleManager::GetModulePtr (const FName ModuleName) inline static
Gets a module by name.
Parameters
ModuleName The module to get.
Returns
The interface to the module, or nullptr if the module was not found.
See also
GetModuleChecked, LoadModulePtr, LoadModuleChecked
Definition at line 357 of file ModuleManager.h.
References FORCEINLINE, and GetModulePtr_Internal().
GetModulePtr_Internal()
IModuleInterface * FModuleManager::GetModulePtr_Internal (FName ModuleName) static private
Referenced by GetModulePtr().
GetOrLoadModule()
IModuleInterface * FModuleManager::GetOrLoadModule (const FName InModuleName, EModuleLoadResult & OutFailureReason, ELoadModuleFlags InLoadModuleFlags = ELoadModuleFlags::None) private
GetUBTConfiguration()
const TCHAR * FModuleManager::GetUBTConfiguration () static
Gets the build configuration for compiling modules, as required by UBT.
Returns
Configuration name for UBT.
HasAnyOverridenModuleFilename()
bool FModuleManager::HasAnyOverridenModuleFilename () const
Determines if any non-default module instances are loaded (eg.
hot reloaded modules)
InternalFreeLibrary()
void FModuleManager::InternalFreeLibrary (FName ModuleName, void * Handle) private
Attempt to free the backing library for a module.
References Handle.
InternalLoadLibrary()
void * FModuleManager::InternalLoadLibrary (FName ModuleName, const FString & ModuleFileToLoad) private
Load the library for a given module.
IsModuleLoaded()
bool FModuleManager::IsModuleLoaded (const FName InModuleName) const
Checks whether the specified module is currently loaded.
This is an O(1) operation.
Parameters
InModuleName The base name of the module file. Should not include path, extension or platform/configuration info. This is just the "module name" part of the module file name. Names should be globally unique.
Returns
true if module is currently loaded, false otherwise.
See also
AbandonModule, LoadModule, LoadModuleWithFailureReason, UnloadModule
Referenced by FModuleObserver::FModuleObserver(), FModuleObserver::~FModuleObserver(), GetModuleChecked(), IAIModule::IsAvailable(), ICameraPhotographyModule::IsAvailable(), IChaosCachingEditorPlugin::IsAvailable(), IChaosCachingPlugin::IsAvailable(), IChaosFleshEditorPlugin::IsAvailable(), IChaosFleshEnginePlugin::IsAvailable(), IChaosModularVehicleEditorPlugin::IsAvailable(), IChaosModularVehicleEnginePlugin::IsAvailable(), IChaosModularVehiclePlugin::IsAvailable(), IChaosSolverEditorPlugin::IsAvailable(), IChaosVehiclesEditorPlugin::IsAvailable(), IChaosVehiclesPlugin::IsAvailable(), ICommonUIModule::IsAvailable(), ICurveEditorModule::IsAvailable(), ICustomMeshComponentPlugin::IsAvailable(), IDisplayCluster::IsAvailable(), IDisplayClusterColorGrading::IsAvailable(), IDisplayClusterConfiguration::IsAvailable(), IDisplayClusterConfigurator::IsAvailable(), IDisplayClusterDetails::IsAvailable(), IDisplayClusterLightCardEditor::IsAvailable(), IDisplayClusterLightCardEditorShaders::IsAvailable(), IDisplayClusterLightCardExtenderModule::IsAvailable(), IDisplayClusterOperator::IsAvailable(), IDisplayClusterProjection::IsAvailable(), IDisplayClusterScenePreview::IsAvailable(), IDisplayClusterShaders::IsAvailable(), IDisplayClusterWarp::IsAvailable(), IGameplayAbilitiesModule::IsAvailable(), IGameplayTagsModule::IsAvailable(), IGameplayTasksModule::IsAvailable(), ILiveLinkOverNDisplayModule::IsAvailable(), IMeshDescriptionModule::IsAvailable(), IMovieSceneModule::IsAvailable(), IMovieSceneTracksModule::IsAvailable(), INetworkPredictionModule::IsAvailable(), IPixelStreaming2EditorModule::IsAvailable(), IPixelStreaming2HMDModule::IsAvailable(), IPixelStreaming2InputModule::IsAvailable(), IPixelStreaming2Module::IsAvailable(), IPixelStreaming2RTCModule::IsAvailable(), IPixelStreamingEditorModule::IsAvailable(), IPixelStreamingHMDModule::IsAvailable(), IPixelStreamingInputModule::IsAvailable(), IPixelStreamingModule::IsAvailable(), IProceduralMeshComponentEditorPlugin::IsAvailable(), IProceduralMeshComponentPlugin::IsAvailable(), ISmartObjectsModule::IsAvailable(), IStateTreeModule::IsAvailable(), and IWebBrowserWidgetModule::IsAvailable().
IsModuleUpToDate()
bool FModuleManager::IsModuleUpToDate (const FName InModuleName) const
Checks to see if the specified module exists and is compatible with the current engine version.
Parameters
InModuleName The base name of the module file.
Returns
true if module exists and is up to date, false otherwise.
IsPackageLoadedCallback()
FIsPackageLoadedCallback & FModuleManager::IsPackageLoadedCallback () inline
Definition at line 568 of file ModuleManager.h.
References IsPackageLoaded.
LoadModule()
IModuleInterface * FModuleManager::LoadModule (const FName InModuleName, ELoadModuleFlags InLoadModuleFlags = ELoadModuleFlags::None)
Loads the specified module.
Parameters
InModuleName The base name of the module file. Should not include path, extension or platform/configuration info. This is just the "module name" part of the module file name. Names should be globally unique.
InLoadModuleFlags Optional flags for module load operation.
Returns
The loaded module, or nullptr if the load operation failed.
See also
AbandonModule, IsModuleLoaded, LoadModuleChecked, LoadModulePtr, LoadModuleWithFailureReason, UnloadModule
Referenced by LoadModulePtr().
LoadModuleBinaryOnly()
void FModuleManager::LoadModuleBinaryOnly (FName ModuleName)
Will load the binary without doing initialization.
Calling this will not make it possible to unload the module again
LoadModuleChecked() [1/2]
IModuleInterface & FModuleManager::LoadModuleChecked (const FName InModuleName)
Loads the specified module, checking to ensure it exists.
Parameters
InModuleName The base name of the module file. Should not include path, extension or platform/configuration info. This is just the "module name" part of the module file name. Names should be globally unique.
Returns
The loaded module, or nullptr if the load operation failed.
See also
AbandonModule, IsModuleLoaded, LoadModuleChecked, LoadModulePtr, LoadModuleWithFailureReason, UnloadModule
Referenced by AnimationEditorUtils::ExecuteNewAnimAsset(), FLocationServicesAndroidImplModule::Get(), FLocationServicesBPLibraryModule::Get(), FLocationServicesIOSImplModule::Get(), FMovieSceneToolsModule::Get(), IAIModule::Get(), ICameraPhotographyModule::Get(), IChaosCachingEditorPlugin::Get(), IChaosCachingPlugin::Get(), IChaosFleshEditorPlugin::Get(), IChaosFleshEnginePlugin::Get(), IChaosModularVehicleEditorPlugin::Get(), IChaosModularVehicleEnginePlugin::Get(), IChaosModularVehiclePlugin::Get(), IChaosSolverEditorPlugin::Get(), IChaosVehiclesEditorPlugin::Get(), IChaosVehiclesPlugin::Get(), ICommonUIModule::Get(), ICustomMeshComponentPlugin::Get(), IDisplayClusterLightCardExtenderModule::Get(), IDisplayClusterProjection::Get(), IDisplayClusterShaders::Get(), IDisplayClusterWarp::Get(), IGameplayAbilitiesModule::Get(), IGameplayTagsModule::Get(), IGameplayTasksModule::Get(), ILiveLinkOverNDisplayModule::Get(), IMeshDescriptionModule::Get(), IMovieSceneModule::Get(), IMovieSceneTracksModule::Get(), INetworkPredictionModule::Get(), IPixelStreaming2EditorModule::Get(), IPixelStreaming2HMDModule::Get(), IPixelStreaming2InputModule::Get(), IPixelStreaming2Module::Get(), IPixelStreaming2RTCModule::Get(), IPixelStreamingEditorModule::Get(), IPixelStreamingHMDModule::Get(), IPixelStreamingInputModule::Get(), IPixelStreamingModule::Get(), IPlatformFeaturesModule::Get(), IProceduralMeshComponentEditorPlugin::Get(), IProceduralMeshComponentPlugin::Get(), IRigVMEditorModule::Get(), ISmartObjectsModule::Get(), IStateTreeModule::Get(), IVPUtilitiesEditorModule::Get(), IWebBrowserWidgetModule::Get(), LoadModuleChecked(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), and SRigVMBulkEditDialog< InWidgetType >::ShowNormal().
LoadModuleChecked() [2/2]
template<typename TModuleInterface> TModuleInterface & FModuleManager::LoadModuleChecked (const FName InModuleName) inline static
Loads a module by name, checking to ensure it exists.
This method checks whether the module actually exists. If the module does not exist, an assertion will be triggered. If the module was already loaded previously, the existing instance will be returned.
Parameters
ModuleName The module to find and load
Returns
Returns the module interface, casted to the specified typename
See also
GetModulePtr, LoadModulePtr, LoadModuleChecked
Definition at line 373 of file ModuleManager.h.
References Get(), and LoadModuleChecked().
LoadModulePtr()
template<typename TModuleInterface> TModuleInterface * FModuleManager::LoadModulePtr (const FName InModuleName) inline static
Loads a module by name.
Parameters
ModuleName The module to find and load.
Returns
The interface to the module, or nullptr if the module was not found.
See also
GetModulePtr, GetModuleChecked, LoadModuleChecked
Definition at line 387 of file ModuleManager.h.
References Get(), and LoadModule().
LoadModuleWithCallback()
bool FModuleManager::LoadModuleWithCallback (const FName InModuleName, FOutputDevice & Ar)
Loads a module in memory then calls PostLoad.
Parameters
InModuleName The name of the module to load.
Ar The archive to receive error messages, if any.
Returns
true on success, false otherwise.
See also
UnloadOrAbandonModuleWithCallback
References Ar.
LoadModuleWithFailureReason()
IModuleInterface * FModuleManager::LoadModuleWithFailureReason (const FName InModuleName, EModuleLoadResult & OutFailureReason, ELoadModuleFlags InLoadModuleFlags = ELoadModuleFlags::None)
Loads the specified module and returns a result.
Parameters
InModuleName The base name of the module file. Should not include path, extension or platform/configuration info. This is just the "module name" part of the module file name. Names should be globally unique.
OutFailureReason Will contain the result.
InLoadModuleFlags Optional flags for module load operation.
Returns
The loaded module (null if the load operation failed).
See also
AbandonModule, IsModuleLoaded, LoadModule, LoadModuleChecked, LoadModulePtr, UnloadModule
MakeUniqueModuleFilename()
void FModuleManager::MakeUniqueModuleFilename (const FName InModuleName, FString & UniqueSuffix, FString & UniqueModuleFileName) const
Generates a unique file name for the specified module name by adding a random suffix and checking for file collisions.
ModuleExists()
bool FModuleManager::ModuleExists (const TCHAR * ModuleName, FString * OutModuleFilePath = nullptr) const
Determines if a module with the given name exists, regardless of whether it is currently loaded.
Parameters
ModuleName Name of the module to look for.
OutModuleFilePath If non-null, the assembly filename of the module will be written. Empty string will be written if ModuleExists returns false or assembly is unknown due to e.g. Monolithic executable.
Returns
Whether the module exists.
OnCheckLiveObjectsInModulesCallback()
TDelegateRegistration< bool(TConstArrayView< FName >)> & FModuleManager::OnCheckLiveObjectsInModulesCallback () inline
Gets a delegate that is executed whenever we need to confirm that modules can be safely unloaded.
Returns
The delegate.
Definition at line 555 of file ModuleManager.h.
References CheckLiveObjectsInModulesCallback.
OnModulesChanged()
TTSMulticastDelegateRegistration< void(FName ModuleName, EModuleChangeReason ChangeReason)> & FModuleManager::OnModulesChanged () inline
Definition at line 521 of file ModuleManager.h.
References ModulesChangedEvent.
Referenced by FModuleObserver::FModuleObserver(), and FModuleObserver::~FModuleObserver().
OnObjectCleanup()
void FModuleManager::OnObjectCleanup ()
Signal that objects used by an unloading dynamic library should be cleaned up now.
OnProcessLoadedObjectsCallback()
TMulticastDelegateRegistration< void(FName, bool)> & FModuleManager::OnProcessLoadedObjectsCallback () inline
Definition at line 535 of file ModuleManager.h.
References ProcessLoadedObjectsCallback.
OnRemoveLoadedObjectsCallback()
TMulticastDelegateRegistration< void(TConstArrayView< FName >)> & FModuleManager::OnRemoveLoadedObjectsCallback () inline
Gets a multicast delegate that is executed when any UObjects need destroying before modules are unloaded.
Returns
The delegate.
Definition at line 545 of file ModuleManager.h.
References RemoveLoadedObjectsCallback.
operator=()
FModuleManager & FModuleManager::operator= (const FModuleManager &) delete
References FModuleManager().
ProcessPendingStaticallyLinkedModuleInitializers()
void FModuleManager::ProcessPendingStaticallyLinkedModuleInitializers () const private
Adds pending module initializer registrations to the StaticallyLinkedModuleInitializers map.
QueryModule()
bool FModuleManager::QueryModule (const FName InModuleName, FModuleStatus & OutModuleStatus) const
Queries information about a specific module name.
Parameters
InModuleName Module to query status for.
OutModuleStatus Status of the specified module.
Returns
true if the module was found and the OutModuleStatus is valid, false otherwise.
See also
QueryModules
QueryModules()
void FModuleManager::QueryModules (TArray< FModuleStatus > & OutModuleStatuses) const
Queries information about all of the currently known modules.
Parameters
OutModuleStatuses Status of all modules. Note that the array will be cleared before the results are added to it.
See also
QueryModule
RefreshModuleFilenameFromManifest()
void FModuleManager::RefreshModuleFilenameFromManifest (const FName InModuleName)
RefreshModuleFilenameFromManifestImpl()
void FModuleManager::RefreshModuleFilenameFromManifestImpl (const FName InModuleName, FModuleInfo & ModuleInfo) private
Refreshes the filename of a new module from the manifest.
ResetModulePathsCache()
void FModuleManager::ResetModulePathsCache ()
Clears module path cache.
SaveCurrentStateForBootstrap()
void FModuleManager::SaveCurrentStateForBootstrap (const TCHAR * Filename)
Save the current module manager's state into a file for bootstrapping other processes.
References Filename.
SerializeStateForBootstrap_Impl()
void FModuleManager::SerializeStateForBootstrap_Impl (FArchive & Ar) private
Serialize a bootstrapping state into or from an archive.
References Ar.
SetGameBinariesDirectory()
void FModuleManager::SetGameBinariesDirectory (const TCHAR * InDirectory)
Set the game binaries directory.
Parameters
InDirectory The game binaries directory.
SetModuleFilename()
void FModuleManager::SetModuleFilename (FName ModuleName, const FString & Filename)
Sets the filename for a module.
The module is not reloaded immediately, but the new name will be used for subsequent unload/load events.
References Filename.
StartProcessingNewlyLoadedObjects()
void FModuleManager::StartProcessingNewlyLoadedObjects ()
Called by the engine at startup to let the Module Manager know that it's now safe to process new UObjects discovered by loading C++ modules.
TearDown()
void FModuleManager::TearDown () static
Destroys singleton if it exists.
Get() must not be called after Destroy().
UnloadModule()
bool FModuleManager::UnloadModule (const FName InModuleName, bool bIsShutdown = false, bool bAllowUnloadCode = true)
Unloads a specific module NOTE: You can manually unload a module before the normal shutdown occurs with this, but be careful as you may be unloading another module's dependency too early!
Parameters
InModuleName The name of the module to unload. Should not include path, extension or platform/configuration info. This is just the "module name" part of the module file name.
bIsShutdown Is this unload module call occurring at shutdown (default = false).
bAllowUnloadCode Allow unloading of code library if possible (default = true).
Returns
true if module was unloaded successfully, false otherwise.
See also
AbandonModule, IsModuleLoaded, LoadModule, LoadModuleWithFailureReason
UnloadModulesAtShutdown()
void FModuleManager::UnloadModulesAtShutdown ()
Unloads modules during the shutdown process.
Modules are unloaded in reverse order to when their StartupModule() FINISHES. The practical implication of this is that if module A depends on another module B, and A loads B during A's StartupModule, that B will actually get Unloaded after A during shutdown. This allows A's ShutdownModule() call to still reference module B. You can manually unload a module yourself which will change this ordering, but be careful as you may be unloading another module's dependency!
This method is Usually called at various points while exiting an application.
UnloadOrAbandonModuleWithCallback()
void FModuleManager::UnloadOrAbandonModuleWithCallback (const FName InModuleName, FOutputDevice & Ar)
Calls PreUnload then either unloads or abandons a module in memory, depending on whether the module supports unloading.
Parameters
InModuleName The name of the module to unload.
Ar The archive to receive error messages, if any.
See also
LoadModuleWithCallback
References Ar.
WarnIfItWasntSafeToLoadHere()
void FModuleManager::WarnIfItWasntSafeToLoadHere (const FName InModuleName) static private
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FModuleManager & ModuleManager) friend
References FModuleManager(), and Ar.
UE::Core::Private::GetModuleManagerSingleton
TOptional< FModuleManager > & UE::Core::Private::GetModuleManagerSingleton () friend
Field Documentation
bCanProcessNewlyLoadedObjects
bool FModuleManager::bCanProcessNewlyLoadedObjects private
True if module manager should automatically register new UObjects discovered while loading C++ modules.
Definition at line 732 of file ModuleManager.h.
bExtraBinarySearchPathsAdded
bool FModuleManager::bExtraBinarySearchPathsAdded private
True once AddExtraBinarySearchPaths has been called.
Definition at line 735 of file ModuleManager.h.
BuildId
TOptional<FString> FModuleManager::BuildId mutable private
ID used to validate module manifests.
Read from the module manifest in the engine directory on first query to load a new module; unset until then.
Definition at line 766 of file ModuleManager.h.
CheckLiveObjectsInModulesCallback
TDelegate<bool(TConstArrayView<FName>)> FModuleManager::CheckLiveObjectsInModulesCallback private
Delegate called to check whether any module to delay-unload still has live objects.
Definition at line 751 of file ModuleManager.h.
Referenced by OnCheckLiveObjectsInModulesCallback().
EngineBinariesDirectories
TArray<FString> FModuleManager::EngineBinariesDirectories mutable private
Array of engine binaries directories.
Definition at line 758 of file ModuleManager.h.
GameBinariesDirectories
TArray<FString> FModuleManager::GameBinariesDirectories mutable private
Array of game binaries directories.
Definition at line 762 of file ModuleManager.h.
InInitializerDelegate
const FInitializeStaticallyLinkedModule& FModuleManager::InInitializerDelegate
Initial value:
{
        PendingStaticallyLinkedModuleInitializers.Emplace( InModuleName, InInitializerDelegate )
Definition at line 440 of file ModuleManager.h.
IsPackageLoaded
FIsPackageLoadedCallback FModuleManager::IsPackageLoaded private
When module manager is linked against an application that supports UObjects, this delegate will be primed at startup to provide information about whether a UObject package is loaded into memory.
Definition at line 755 of file ModuleManager.h.
Referenced by IsPackageLoadedCallback().
ModulePathsCache
TMap<FName, FString> FModuleManager::ModulePathsCache mutable private
Cache of known module paths.
Used for performance. Can increase editor startup times by up to 30%
Definition at line 738 of file ModuleManager.h.
Modules
FModuleMap FModuleManager::Modules private
Map of all modules.
Maps the case-insensitive module name to information about that module, loaded or not.
Definition at line 721 of file ModuleManager.h.
ModulesChangedEvent
TTSMulticastDelegate<void(FName ModuleName, EModuleChangeReason ChangeReason)> FModuleManager::ModulesChangedEvent private
Multicast delegate that will broadcast a notification when modules are loaded, unloaded, or our set of known modules changes.
Definition at line 742 of file ModuleManager.h.
Referenced by OnModulesChanged().
ModulesCriticalSection
FCriticalSection FModuleManager::ModulesCriticalSection mutable private
Critical section object controlling R/W access to Modules.
Definition at line 769 of file ModuleManager.h.
PendingEngineBinariesDirectories
TArray<FString> FModuleManager::PendingEngineBinariesDirectories mutable private
Definition at line 759 of file ModuleManager.h.
PendingGameBinariesDirectories
TArray<FString> FModuleManager::PendingGameBinariesDirectories mutable private
Definition at line 763 of file ModuleManager.h.
PendingStaticallyLinkedModuleInitializers
TArray<TPair<FLazyName, FInitializeStaticallyLinkedModule>, TInlineAllocator<16> > FModuleManager::PendingStaticallyLinkedModuleInitializers mutable private
Pending registrations of module names.
We use an array here to stop comparisons (and thus FNames being constructed) when they are registered. Instead, we validate there are no duplicates when they're inserted into StaticallyLinkedModuleInitializers.
Definition at line 726 of file ModuleManager.h.
ProcessLoadedObjectsCallback
TMulticastDelegate<void(FName, bool)> FModuleManager::ProcessLoadedObjectsCallback private
Multicast delegate called to process any new loaded objects.
Definition at line 745 of file ModuleManager.h.
Referenced by OnProcessLoadedObjectsCallback().
RemoveLoadedObjectsCallback
TMulticastDelegate<void(TConstArrayView<FName>)> FModuleManager::RemoveLoadedObjectsCallback private
Multicast delegate called to remove any loaded objects for a list of modules.
Definition at line 748 of file ModuleManager.h.
Referenced by OnRemoveLoadedObjectsCallback().
StaticallyLinkedModuleInitializers
TMap<FName, FInitializeStaticallyLinkedModule> FModuleManager::StaticallyLinkedModuleInitializers mutable private
Map of module names to a delegate that can initialize each respective statically linked module.
Definition at line 729 of file ModuleManager.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Modules/ModuleManager.h