Unreal Engine 5.6 C++ API: UE::Math::FLinearFeedbackShiftRegister Class Reference
UE::Math::FLinearFeedbackShiftRegister Class Reference
#include "LFSR.h"
Public Member Functions
FLinearFeedbackShiftRegister ()
uint32 GetNextValue (uint32 N)
uint32 GetNextValueWithLast (uint32 N)
Private Member Functions
uint32 GetNextValueInternal (uint32 N, bool IncludeLast)
Private Attributes
const uint32 StartState = 1
uint32 State = StartState
Detailed Description
Definition at line 16 of file LFSR.h.
Constructor & Destructor Documentation
FLinearFeedbackShiftRegister()
UE::Math::FLinearFeedbackShiftRegister::FLinearFeedbackShiftRegister () inline nodiscard
Definition at line 20 of file LFSR.h.
Member Function Documentation
GetNextValue()
uint32 UE::Math::FLinearFeedbackShiftRegister::GetNextValue (uint32 N) inline nodiscard
Definition at line 25 of file LFSR.h.
References GetNextValueInternal().
GetNextValueInternal()
uint32 UE::Math::FLinearFeedbackShiftRegister::GetNextValueInternal (uint32 N, bool IncludeLast) inline private
Definition at line 43 of file LFSR.h.
References check, Mask, StartState, and State.
Referenced by GetNextValue(), and GetNextValueWithLast().
GetNextValueWithLast()
uint32 UE::Math::FLinearFeedbackShiftRegister::GetNextValueWithLast (uint32 N) inline nodiscard
Definition at line 33 of file LFSR.h.
References GetNextValueInternal().
Field Documentation
StartState
const uint32 UE::Math::FLinearFeedbackShiftRegister::StartState = 1 private
Definition at line 40 of file LFSR.h.
Referenced by GetNextValueInternal().
State
uint32 UE::Math::FLinearFeedbackShiftRegister::State = StartState private
Definition at line 41 of file LFSR.h.
Referenced by GetNextValueInternal().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/LFSR.h