Unreal Engine 5.6 C++ API: TSparseArray< InElementType, Allocator >::TRangedForConstIterator Class Reference
TSparseArray< InElementType, Allocator >::TRangedForConstIterator Class Reference
#include "SparseArray.h"
Public Member Functions
TRangedForConstIterator (const TSparseArray &InArray, const typename TBaseIterator< true >::BitArrayItType &InBitArrayIt)
FORCEINLINE bool operator!= (const TRangedForConstIterator &Rhs) const
Public Member Functions inherited from TSparseArray< InElementType, Allocator >::TConstIterator
TConstIterator (const TSparseArray &InArray)
TConstIterator (const TSparseArray &InArray, const typename TBaseIterator< true >::BitArrayItType &InBitArrayIt)
Public Member Functions inherited from TSparseArray< InElementType, Allocator >::TBaseIterator< true >
TBaseIterator (ArrayType &InArray, const BitArrayItType &InBitArrayIt)
FORCEINLINE int32 GetIndex () const
FORCEINLINE const FRelativeBitReference & GetRelativeBitReference () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
FORCEINLINE ItElementType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
FORCEINLINE ItElementType * operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
Private Attributes
int32 InitialNum
Additional Inherited Members
Public Types inherited from TSparseArray< InElementType, Allocator >::TBaseIterator< true >
typedef TConstSetBitIterator< typename Allocator::BitArrayAllocator > BitArrayItType
Protected Attributes inherited from TSparseArray< InElementType, Allocator >::TBaseIterator< true >
ArrayType & Array
BitArrayItType BitArrayIt
Detailed Description
template<typename InElementType, typename Allocator>
class TSparseArray< InElementType, Allocator >::TRangedForConstIterator
Definition at line 1071 of file SparseArray.h.
Constructor & Destructor Documentation
TRangedForConstIterator()
template<typename InElementType, typename Allocator> TSparseArray< InElementType, Allocator >::TRangedForConstIterator::TRangedForConstIterator (const TSparseArray & InArray, const typename TBaseIterator< true >::BitArrayItType & InBitArrayIt) inline nodiscard
Definition at line 1074 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::TConstIterator::TConstIterator(), TSparseArray< InElementType, Allocator >::TSparseArray(), InitialNum, and TSparseArray< InElementType, Allocator >::Num().
Referenced by operator!=().
Member Function Documentation
operator!=()
template<typename InElementType, typename Allocator> FORCEINLINE bool TSparseArray< InElementType, Allocator >::TRangedForConstIterator::operator!= (const TRangedForConstIterator & Rhs) const inline nodiscard
Definition at line 1080 of file SparseArray.h.
References TRangedForConstIterator(), TSparseArray< InElementType, Allocator >::TBaseIterator< true >::Array, ensureMsgf, FORCEINLINE, InitialNum, and TEXT.
Field Documentation
InitialNum
template<typename InElementType, typename Allocator> int32 TSparseArray< InElementType, Allocator >::TRangedForConstIterator::InitialNum private
Definition at line 1091 of file SparseArray.h.
Referenced by TRangedForConstIterator(), and operator!=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SparseArray.h