Unreal Engine 5.6 C++ API: UE::Geometry::FMeshConstraintsUtil Class Reference
UE::Geometry::FMeshConstraintsUtil Class Reference
Utility functions for configuring a FMeshConstraints instance.
#include "MeshConstraintsUtil.h"
Public Types
enum class EBoundaryType { Mesh = 0 , Group = 1 , MaterialID = 2 }
Static Public Member Functions
static DYNAMICMESH_API void ConstrainAllBoundariesAndSeams (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, EEdgeRefineFlags MeshBoundaryConstraint, EEdgeRefineFlags GroupBoundaryConstraint, EEdgeRefineFlags MaterialBoundaryConstraint, bool bAllowSeamSplits, bool bAllowSeamSmoothing, bool bAllowSeamCollpase=false, bool bParallel=true)
Constrain all attribute seams for all overlays of a mesh and different types of boundaries on the mesh.
static DYNAMICMESH_API void ConstrainAllSeams (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, bool bAllowSplits, bool bAllowSmoothing, bool bParallel=true)
Constrain all attribute seams for all overlays of a mesh.
static DYNAMICMESH_API bool ConstrainEdgeBoundariesAndSeams (const int EdgeID, const FDynamicMesh3 &Mesh, const EEdgeRefineFlags MeshBoundaryConstraint, const EEdgeRefineFlags GroupBoundaryConstraint, const EEdgeRefineFlags MaterialBoundaryConstraint, const EEdgeRefineFlags SeamEdgeConstraint, const bool bAllowSeamSmoothing, FEdgeConstraint &EdgeConstraint, FVertexConstraint &VertexConstraintA, FVertexConstraint &VertexConstraintB)
Constrain all attribute seams for all overlays of a mesh and different types of boundaries on the mesh.
static DYNAMICMESH_API void ConstrainROIBoundariesInEdgeROI (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, const TSet< int > &EdgeROI, const TSet< int > &TriangleROI, bool bAllowSplits, bool bAllowSmoothing)
Constrain each edge in the EdgeROI set that is incident on exactly one triangle in the TriangleROI set.
template<typename RealType, int ElementSize>
static void ConstrainSeams (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, const TDynamicMeshOverlay< RealType, ElementSize > &Overlay)
Constrain attribute seams of the given overlay.
static DYNAMICMESH_API void ConstrainSeamsInEdgeROI (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, const TArray< int > &EdgeROI, bool bAllowSplits, bool bAllowSmoothing, bool bParallel=true)
template<typename EnumerableType>
static void FullyConstrainEdges (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, EnumerableType Enumerable)
For all edges, disable flip/split/collapse.
template<typename iter>
static void FullyConstrainEdges (FMeshConstraints &Constraints, const FDynamicMesh3 &Mesh, iter BeginEdges, iter EndEdges)
For all edges, disable flip/split/collapse.
static DYNAMICMESH_API void SetBoundaryConstraintsWithProjection (FMeshConstraints &Constraints, const EBoundaryType BoundaryToConstrain, const FDynamicMesh3 &Mesh, double CornerAngleThreshold=45.0)
Create polycurve projection targets at group boundaries.
Private Member Functions
FMeshConstraintsUtil ()=delete
Detailed Description
Utility functions for configuring a FMeshConstraints instance.
Definition at line 22 of file MeshConstraintsUtil.h.
Member Enumeration Documentation
EBoundaryType
enum class UE::Geometry::FMeshConstraintsUtil::EBoundaryType strong
Enumerator
Mesh
Group
MaterialID
Definition at line 177 of file MeshConstraintsUtil.h.
Constructor & Destructor Documentation
FMeshConstraintsUtil()
UE::Geometry::FMeshConstraintsUtil::FMeshConstraintsUtil () private delete
Member Function Documentation
ConstrainAllBoundariesAndSeams()
DYNAMICMESH_API void UE::Geometry::FMeshConstraintsUtil::ConstrainAllBoundariesAndSeams (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, EEdgeRefineFlags MeshBoundaryConstraint, EEdgeRefineFlags GroupBoundaryConstraint, EEdgeRefineFlags MaterialBoundaryConstraint, bool bAllowSeamSplits, bool bAllowSeamSmoothing, bool bAllowSeamCollpase = false, bool bParallel = true) static
Constrain all attribute seams for all overlays of a mesh and different types of boundaries on the mesh.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
MeshBoundaryConstraint the constraints to place on Mesh boundaries
GroupBoundaryConstraint the constraints to place on boundaries between polygon groups
MaterialBoundaryConstraint the constraints to place on boundaries between different materials
bAllowSplits should we allow constrained edges to be split
bAllowSmoothing should we allow constrained vertices to be smoothed
bAllowSeamCollapse should we allow seam edges to collapse
bParallel should we run the algo in parallel
References Mesh, and UE_API.
ConstrainAllSeams()
DYNAMICMESH_API void UE::Geometry::FMeshConstraintsUtil::ConstrainAllSeams (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, bool bAllowSplits, bool bAllowSmoothing, bool bParallel = true) static
Constrain all attribute seams for all overlays of a mesh.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
bAllowSplits should we allow constrained edges to be split
bAllowSmoothing should we allow constrained vertices to be smoothed
bParallel should we run the algo in parallel
References Mesh, and UE_API.
ConstrainEdgeBoundariesAndSeams()
DYNAMICMESH_API bool UE::Geometry::FMeshConstraintsUtil::ConstrainEdgeBoundariesAndSeams (const int EdgeID, const FDynamicMesh3 & Mesh, const EEdgeRefineFlags MeshBoundaryConstraint, const EEdgeRefineFlags GroupBoundaryConstraint, const EEdgeRefineFlags MaterialBoundaryConstraint, const EEdgeRefineFlags SeamEdgeConstraint, const bool bAllowSeamSmoothing, FEdgeConstraint & EdgeConstraint, FVertexConstraint & VertexConstraintA, FVertexConstraint & VertexConstraintB) static
Constrain all attribute seams for all overlays of a mesh and different types of boundaries on the mesh.
Parameters
EdgeID the edge in Mesh to constrain
Mesh the mesh to constrain
MeshBoundaryConstraint the constraint policy for Mesh boundaries
GroupBoundaryConstraint the constraint policy for boundaries between polygon groups
MaterialBoundaryConstraint the constraint policy for boundaries between different materials
SeamEdgeConstraint the constraint policy for attribute (e.g. uv, normals) seams
bAllowSmoothing should we allow constrained vertices to be smoothed
EdgeConstraint [out] edge constraint to be updated
VertexConstraintA [out] vertex constraint to be updated on return
VertexConstraintB [out] vertex constraint to be updated on return
Returns
false if no constraint is needed for this edge
References Mesh, and UE_API.
ConstrainROIBoundariesInEdgeROI()
DYNAMICMESH_API void UE::Geometry::FMeshConstraintsUtil::ConstrainROIBoundariesInEdgeROI (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, const TSet< int > & EdgeROI, const TSet< int > & TriangleROI, bool bAllowSplits, bool bAllowSmoothing) static
Constrain each edge in the EdgeROI set that is incident on exactly one triangle in the TriangleROI set.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
EdgeROI set of edges to try to constrain
TriangleROI set of triangles that determine whether an edge is a "boundary"
bAllowSplits should we allow constrained edges to be split
bAllowSmoothing should we allow constrained vertices to be smoothed
References Mesh, and UE_API.
ConstrainSeams()
template<typename RealType, int ElementSize> void UE::Geometry::FMeshConstraintsUtil::ConstrainSeams (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, const TDynamicMeshOverlay< RealType, ElementSize > & Overlay) inline static
Constrain attribute seams of the given overlay.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
Overlay the attribute overlay to find seams in
Definition at line 92 of file MeshConstraintsUtil.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, UE::Geometry::FEdgeConstraint::FullyConstrained(), UE::Geometry::FVertexConstraint::FullyConstrained(), UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >::IsSeamEdge(), Mesh, UE::Geometry::FMeshConstraints::SetOrUpdateEdgeConstraint(), and UE::Geometry::FMeshConstraints::SetOrUpdateVertexConstraint().
ConstrainSeamsInEdgeROI()
DYNAMICMESH_API void UE::Geometry::FMeshConstraintsUtil::ConstrainSeamsInEdgeROI (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, const TArray< int > & EdgeROI, bool bAllowSplits, bool bAllowSmoothing, bool bParallel = true) static
   Constrain all attribute seams for all overlays of a mesh, for edges in the edge array. This includes edges in
s * EdgeROI that are seams, as well as vertices incident to edges in EdgeROI that are on seams.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
EdgeROI list of edges to try to constrain
bAllowSplits should we allow constrained edges to be split
bAllowSmoothing should we allow constrained vertices to be smoothed
References Mesh, and UE_API.
FullyConstrainEdges() [1/2]
template<typename EnumerableType> void UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, EnumerableType Enumerable) inline static
For all edges, disable flip/split/collapse.
For all vertices, pin in current position.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
Enumerable object that can be passed to a range-based for loop
Definition at line 138 of file MeshConstraintsUtil.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, UE::Geometry::FEdgeConstraint::FullyConstrained(), UE::Geometry::FVertexConstraint::FullyConstrained(), Mesh, UE::Geometry::FMeshConstraints::SetOrUpdateEdgeConstraint(), and UE::Geometry::FMeshConstraints::SetOrUpdateVertexConstraint().
FullyConstrainEdges() [2/2]
template<typename iter> void UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges (FMeshConstraints & Constraints, const FDynamicMesh3 & Mesh, iter BeginEdges, iter EndEdges) inline static
For all edges, disable flip/split/collapse.
For all vertices, pin in current position.
Parameters
Constraints the set of constraints to add to
Mesh the mesh to constrain
Definition at line 114 of file MeshConstraintsUtil.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, UE::Geometry::FEdgeConstraint::FullyConstrained(), UE::Geometry::FVertexConstraint::FullyConstrained(), Mesh, UE::Geometry::FMeshConstraints::SetOrUpdateEdgeConstraint(), and UE::Geometry::FMeshConstraints::SetOrUpdateVertexConstraint().
SetBoundaryConstraintsWithProjection()
DYNAMICMESH_API void UE::Geometry::FMeshConstraintsUtil::SetBoundaryConstraintsWithProjection (FMeshConstraints & Constraints, const EBoundaryType BoundaryToConstrain, const FDynamicMesh3 & Mesh, double CornerAngleThreshold = 45.0) static
Create polycurve projection targets at group boundaries.
Vertices on multiple boundaries are fixed, as well as vertices at boundary "corners" (where the angle formed between adjacent boundary edges is above a given threshold.)
Parameters
Constraints (out) constraint data to add new constraints to
Mesh the mesh to constrain
CornerAngleThreshold angle threshold (in degrees) above which adjacent edges are considered a corner
References Mesh, and UE_API.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/MeshConstraintsUtil.h