Unreal Engine 5.6 C++ API: FDetailWidgetRow Class Reference
FDetailWidgetRow Class Reference
Represents a single row of custom widgets in a details panel.
#include "DetailWidgetRow.h"
Data Structures
struct FCustomMenuData
Public Member Functions
FDetailWidgetRow ()
virtual ~FDetailWidgetRow ()
FDetailWidgetRow & AddCustomContextMenuAction (const FUIAction &Action, const FText &Name, const FText &Tooltip=FText(), const FSlateIcon &SlateIcon=FSlateIcon())
Add a custom action to the row context menu.
FDetailWidgetRow & CopyAction (const FUIAction &InCopyAction)
Sets a custom copy action to take when copying the data from this row.
FDetailWidgetRow & DragDropHandler (TSharedPtr< IDetailDragDropHandler > InDragDropHandler)
Sets a handler for the row to be a source or target of drag-and-drop operations.
FDetailWidgetRow & EditCondition (TAttribute< bool > InEditConditionValue, FOnBooleanValueChanged InOnEditConditionValueChanged)
Override the edit condition.
FDetailWidgetDecl & ExtensionContent ()
Assigns content to the extension (right) slot.
FDetailWidgetRow & FilterString (const FText &InFilterString)
Sets a string which should be used to filter the content when a user searches.
virtual TOptional< FResetToDefaultOverride > GetCustomResetToDefault () const override
const TArray< TSharedPtr< IPropertyHandle > > & GetPropertyHandles () const
Return all the property handles this WidgetRow represent.
virtual FName GetRowName () const override
IDetailLayoutRow interface.
bool HasAnyContent () const
bool HasColumns () const
bool HasExtensionContent () const
bool HasNameContent () const
bool HasResetToDefaultContent () const
bool HasValueContent () const
bool IsCopyPasteBound () const
FDetailWidgetRow & IsEnabled (const TAttribute< bool > &InIsEnabled)
Sets the enabled state of the entire row.
bool IsPasteFromTextBound () const
FDetailWidgetRow & IsValueEnabled (const TAttribute< bool > &InIsEnabled)
Sets the enabled state of the value widget only.
FDetailWidgetDecl & NameContent ()
Assigns content to just the name slot.
FDetailWidgetRow & operator= (const FDetailWidgetRow &Other)
FDetailWidgetRow & operator[] (TSharedRef< SWidget > InWidget)
Assigns content to the entire row.
FDetailWidgetRow & OverrideResetToDefault (const FResetToDefaultOverride &InResetToDefaultOverride)
Sets flag to indicate if property value differs from the default.
FDetailWidgetRow & PasteAction (const FUIAction &InPasteAction)
Sets a custom paste action to take when copying the data from this row.
FDetailWidgetRow & PropertyHandleList (const TArray< TSharedPtr< IPropertyHandle > > &InPropertyHandles)
Used to provide all the property handles this WidgetRow represent.
FDetailWidgetDecl & ResetToDefaultContent ()
Assigns content to the reset to default (right-most) slot.
FDetailWidgetRow & RowTag (const FName &InRowTagName)
Sets a tag which can be used to identify this row.
FDetailWidgetRow & ShouldAutoExpand (bool bForceExpansion=true)
Sets whether or not this property should auto-expand.
FDetailWidgetDecl & ValueContent ()
Assigns content to the value slot.
FDetailWidgetRow & Visibility (const TAttribute< EVisibility > &InVisibility)
Sets the visibility of the entire row.
FDetailWidgetDecl & WholeRowContent ()
Assigns content to the whole slot, this is an explicit alternative to using [].
Data Fields
FUIAction CopyMenuAction
Action for copying data on this row.
TSharedPtr< IDetailDragDropHandler > CustomDragDropHandler
Custom handler for drag-and-drop of the row.
TArray< FCustomMenuData > CustomMenuItems
Custom Action on this row.
TOptional< FResetToDefaultOverride > CustomResetToDefault
Custom reset to default handler.
TAttribute< bool > EditConditionValue
Custom edit condition value.
FDetailWidgetDecl ExtensionWidget
Extension (right) column content.
FText FilterTextString
String to filter with.
TOptional< bool > ForceAutoExpansion
True to force auto-expansion.
TAttribute< bool > IsEnabledAttr
IsEnabled of the row.
TAttribute< bool > IsValueEnabledAttr
IsEnabled of the value widget only.
FDetailWidgetDecl NameWidget
Name column content.
FOnBooleanValueChanged OnEditConditionValueChanged
Custom edit condition value changed handler.
TWeakPtr< FOnPasteFromText > OnPasteFromTextDelegate
Delegate for pasting (optionally tagged) text on this row.
FUIAction PasteMenuAction
Action for pasting data on this row.
TArray< TSharedPtr< IPropertyHandle > > PropertyHandles
FDetailWidgetDecl ResetToDefaultWidget
Reset to default (right-most) column content.
FName RowTagName
FDetailWidgetDecl ValueWidget
Value column content.
TAttribute< EVisibility > VisibilityAttr
Visibility of the row.
FDetailWidgetDecl WholeRowWidget
Whole row content.
Static Public Attributes
PROPERTYEDITOR_API static const float DefaultValueMaxWidth
PROPERTYEDITOR_API static const float DefaultValueMinWidth
Detailed Description
Represents a single row of custom widgets in a details panel.
Definition at line 105 of file DetailWidgetRow.h.
Constructor & Destructor Documentation
FDetailWidgetRow()
FDetailWidgetRow::FDetailWidgetRow () inline
Definition at line 111 of file DetailWidgetRow.h.
References CopyMenuAction, DefaultValueMaxWidth, DefaultValueMinWidth, ExtensionWidget, FilterTextString, NameWidget, PasteMenuAction, ResetToDefaultWidget, RowTagName, ValueWidget, VisibilityAttr, Visible, and WholeRowWidget.
Referenced by AddCustomContextMenuAction(), CopyAction(), DragDropHandler(), EditCondition(), FilterString(), IsEnabled(), IsValueEnabled(), operator=(), operator[](), OverrideResetToDefault(), PasteAction(), PropertyHandleList(), RowTag(), ShouldAutoExpand(), and Visibility().
~FDetailWidgetRow()
virtual FDetailWidgetRow::~FDetailWidgetRow () inline virtual
Definition at line 148 of file DetailWidgetRow.h.
Member Function Documentation
AddCustomContextMenuAction()
FDetailWidgetRow & FDetailWidgetRow::AddCustomContextMenuAction (const FUIAction & Action, const FText & Name, const FText & Tooltip = FText(), const FSlateIcon & SlateIcon = FSlateIcon()) inline
Add a custom action to the row context menu.
Definition at line 260 of file DetailWidgetRow.h.
References FDetailWidgetRow(), CustomMenuItems, and Name.
CopyAction()
FDetailWidgetRow & FDetailWidgetRow::CopyAction (const FUIAction & InCopyAction) inline
Sets a custom copy action to take when copying the data from this row.
Definition at line 242 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and CopyMenuAction.
DragDropHandler()
FDetailWidgetRow & FDetailWidgetRow::DragDropHandler (TSharedPtr< IDetailDragDropHandler > InDragDropHandler) inline
Sets a handler for the row to be a source or target of drag-and-drop operations.
Definition at line 345 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and CustomDragDropHandler.
EditCondition()
FDetailWidgetRow & FDetailWidgetRow::EditCondition (TAttribute< bool > InEditConditionValue, FOnBooleanValueChanged InOnEditConditionValueChanged) inline
Override the edit condition.
Definition at line 335 of file DetailWidgetRow.h.
References FDetailWidgetRow(), EditConditionValue, and OnEditConditionValueChanged.
ExtensionContent()
FDetailWidgetDecl & FDetailWidgetRow::ExtensionContent () inline
Assigns content to the extension (right) slot.
Definition at line 190 of file DetailWidgetRow.h.
References ExtensionWidget.
Referenced by IDetailPropertyExtensionHandler::ExtendWidgetRow().
FilterString()
FDetailWidgetRow & FDetailWidgetRow::FilterString (const FText & InFilterString) inline
Sets a string which should be used to filter the content when a user searches.
Definition at line 206 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and FilterTextString.
Referenced by FDetailArrayBuilder::GenerateHeaderRowContent().
GetCustomResetToDefault()
virtual TOptional< FResetToDefaultOverride > FDetailWidgetRow::GetCustomResetToDefault () const inline override virtual
Implements IDetailLayoutRow.
Definition at line 152 of file DetailWidgetRow.h.
References CustomResetToDefault.
GetPropertyHandles()
const TArray< TSharedPtr< IPropertyHandle > > & FDetailWidgetRow::GetPropertyHandles () const inline
Return all the property handles this WidgetRow represent.
Definition at line 363 of file DetailWidgetRow.h.
References PropertyHandles.
GetRowName()
virtual FName FDetailWidgetRow::GetRowName () const inline override virtual
IDetailLayoutRow interface.
Implements IDetailLayoutRow.
Definition at line 151 of file DetailWidgetRow.h.
References RowTagName.
HasAnyContent()
bool FDetailWidgetRow::HasAnyContent () const inline
Returns
true of the row has any content
Definition at line 297 of file DetailWidgetRow.h.
References HasColumns(), HasResetToDefaultContent(), InvalidDetailWidgetName, and WholeRowWidget.
HasColumns()
bool FDetailWidgetRow::HasColumns () const inline
Returns
true if the row has columns, false if it spans the entire row
Definition at line 289 of file DetailWidgetRow.h.
References HasNameContent(), and HasValueContent().
Referenced by HasAnyContent().
HasExtensionContent()
bool FDetailWidgetRow::HasExtensionContent () const inline
Definition at line 276 of file DetailWidgetRow.h.
References ExtensionWidget, and InvalidDetailWidgetName.
HasNameContent()
bool FDetailWidgetRow::HasNameContent () const inline
Definition at line 266 of file DetailWidgetRow.h.
References InvalidDetailWidgetName, and NameWidget.
Referenced by HasColumns().
HasResetToDefaultContent()
bool FDetailWidgetRow::HasResetToDefaultContent () const inline
Definition at line 281 of file DetailWidgetRow.h.
References InvalidDetailWidgetName, and ResetToDefaultWidget.
Referenced by HasAnyContent().
HasValueContent()
bool FDetailWidgetRow::HasValueContent () const inline
Definition at line 271 of file DetailWidgetRow.h.
References InvalidDetailWidgetName, and ValueWidget.
Referenced by HasColumns().
IsCopyPasteBound()
bool FDetailWidgetRow::IsCopyPasteBound () const inline
Returns
true if a custom copy/paste is bound on this row
Definition at line 303 of file DetailWidgetRow.h.
References CopyMenuAction, and PasteMenuAction.
IsEnabled()
FDetailWidgetRow & FDetailWidgetRow::IsEnabled (const TAttribute< bool > & InIsEnabled) inline
Sets the enabled state of the entire row.
Definition at line 224 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and IsEnabledAttr.
IsPasteFromTextBound()
bool FDetailWidgetRow::IsPasteFromTextBound () const inline
Returns
true if a custom paste text is bound on this row
Definition at line 309 of file DetailWidgetRow.h.
References OnPasteFromTextDelegate.
IsValueEnabled()
FDetailWidgetRow & FDetailWidgetRow::IsValueEnabled (const TAttribute< bool > & InIsEnabled) inline
Sets the enabled state of the value widget only.
Definition at line 233 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and IsValueEnabledAttr.
NameContent()
FDetailWidgetDecl & FDetailWidgetRow::NameContent () inline
Assigns content to just the name slot.
Definition at line 174 of file DetailWidgetRow.h.
References NameWidget.
Referenced by FGameModeInfoCustomizer::CustomizeGameModeSetting(), and FDetailArrayBuilder::GenerateHeaderRowContent().
operator=()
FDetailWidgetRow & FDetailWidgetRow::operator= (const FDetailWidgetRow & Other) inline
Definition at line 125 of file DetailWidgetRow.h.
References FDetailWidgetRow(), CopyMenuAction, CustomDragDropHandler, CustomMenuItems, CustomResetToDefault, EditConditionValue, ExtensionWidget, FilterTextString, IsEnabledAttr, IsValueEnabledAttr, NameWidget, OnEditConditionValueChanged, Other, PasteMenuAction, PropertyHandles, ResetToDefaultWidget, RowTagName, ValueWidget, VisibilityAttr, and WholeRowWidget.
operator[]()
FDetailWidgetRow & FDetailWidgetRow::operator[] (TSharedRef< SWidget > InWidget) inline
Assigns content to the entire row.
Definition at line 157 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and WholeRowWidget.
OverrideResetToDefault()
FDetailWidgetRow & FDetailWidgetRow::OverrideResetToDefault (const FResetToDefaultOverride & InResetToDefaultOverride) inline
Sets flag to indicate if property value differs from the default.
Definition at line 326 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and CustomResetToDefault.
PasteAction()
FDetailWidgetRow & FDetailWidgetRow::PasteAction (const FUIAction & InPasteAction) inline
Sets a custom paste action to take when copying the data from this row.
Definition at line 251 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and PasteMenuAction.
PropertyHandleList()
FDetailWidgetRow & FDetailWidgetRow::PropertyHandleList (const TArray< TSharedPtr< IPropertyHandle > > & InPropertyHandles) inline
Used to provide all the property handles this WidgetRow represent.
Definition at line 354 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and PropertyHandles.
ResetToDefaultContent()
FDetailWidgetDecl & FDetailWidgetRow::ResetToDefaultContent () inline
Assigns content to the reset to default (right-most) slot.
Definition at line 198 of file DetailWidgetRow.h.
References ResetToDefaultWidget.
RowTag()
FDetailWidgetRow & FDetailWidgetRow::RowTag (const FName & InRowTagName) inline
Sets a tag which can be used to identify this row.
Definition at line 317 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and RowTagName.
ShouldAutoExpand()
FDetailWidgetRow & FDetailWidgetRow::ShouldAutoExpand (bool bForceExpansion = true) inline
Sets whether or not this property should auto-expand.
Parameters
bForceExpansion true to force the property to be expanded
Definition at line 370 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and ForceAutoExpansion.
ValueContent()
FDetailWidgetDecl & FDetailWidgetRow::ValueContent () inline
Assigns content to the value slot.
Definition at line 182 of file DetailWidgetRow.h.
References ValueWidget.
Visibility()
FDetailWidgetRow & FDetailWidgetRow::Visibility (const TAttribute< EVisibility > & InVisibility) inline
Sets the visibility of the entire row.
Definition at line 215 of file DetailWidgetRow.h.
References FDetailWidgetRow(), and VisibilityAttr.
WholeRowContent()
FDetailWidgetDecl & FDetailWidgetRow::WholeRowContent () inline
Assigns content to the whole slot, this is an explicit alternative to using [].
Definition at line 166 of file DetailWidgetRow.h.
References WholeRowWidget.
Field Documentation
CopyMenuAction
FUIAction FDetailWidgetRow::CopyMenuAction
Action for copying data on this row.
Definition at line 396 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), CopyAction(), IsCopyPasteBound(), and operator=().
CustomDragDropHandler
TSharedPtr<IDetailDragDropHandler> FDetailWidgetRow::CustomDragDropHandler
Custom handler for drag-and-drop of the row.
Definition at line 439 of file DetailWidgetRow.h.
Referenced by DragDropHandler(), and operator=().
CustomMenuItems
TArray<FCustomMenuData> FDetailWidgetRow::CustomMenuItems
Custom Action on this row.
Definition at line 429 of file DetailWidgetRow.h.
Referenced by AddCustomContextMenuAction(), and operator=().
CustomResetToDefault
TOptional<FResetToDefaultOverride> FDetailWidgetRow::CustomResetToDefault
Custom reset to default handler.
Definition at line 433 of file DetailWidgetRow.h.
Referenced by GetCustomResetToDefault(), operator=(), and OverrideResetToDefault().
DefaultValueMaxWidth
PROPERTYEDITOR_API static const float FDetailWidgetRow::DefaultValueMaxWidth static
Definition at line 109 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow().
DefaultValueMinWidth
PROPERTYEDITOR_API static const float FDetailWidgetRow::DefaultValueMinWidth static
Definition at line 108 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow().
EditConditionValue
TAttribute<bool> FDetailWidgetRow::EditConditionValue
Custom edit condition value.
Definition at line 435 of file DetailWidgetRow.h.
Referenced by EditCondition(), and operator=().
ExtensionWidget
FDetailWidgetDecl FDetailWidgetRow::ExtensionWidget
Extension (right) column content.
Definition at line 382 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), ExtensionContent(), HasExtensionContent(), and operator=().
FilterTextString
FText FDetailWidgetRow::FilterTextString
String to filter with.
Definition at line 394 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), FilterString(), and operator=().
ForceAutoExpansion
TOptional<bool> FDetailWidgetRow::ForceAutoExpansion
True to force auto-expansion.
Definition at line 443 of file DetailWidgetRow.h.
Referenced by ShouldAutoExpand().
IsEnabledAttr
TAttribute<bool> FDetailWidgetRow::IsEnabledAttr
IsEnabled of the row.
Definition at line 390 of file DetailWidgetRow.h.
Referenced by IsEnabled(), and operator=().
IsValueEnabledAttr
TAttribute<bool> FDetailWidgetRow::IsValueEnabledAttr
IsEnabled of the value widget only.
Definition at line 392 of file DetailWidgetRow.h.
Referenced by IsValueEnabled(), and operator=().
NameWidget
FDetailWidgetDecl FDetailWidgetRow::NameWidget
Name column content.
Definition at line 378 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), HasNameContent(), NameContent(), and operator=().
OnEditConditionValueChanged
FOnBooleanValueChanged FDetailWidgetRow::OnEditConditionValueChanged
Custom edit condition value changed handler.
Definition at line 437 of file DetailWidgetRow.h.
Referenced by EditCondition(), and operator=().
OnPasteFromTextDelegate
TWeakPtr<FOnPasteFromText> FDetailWidgetRow::OnPasteFromTextDelegate
Delegate for pasting (optionally tagged) text on this row.
Definition at line 400 of file DetailWidgetRow.h.
Referenced by IsPasteFromTextBound().
PasteMenuAction
FUIAction FDetailWidgetRow::PasteMenuAction
Action for pasting data on this row.
Definition at line 398 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), IsCopyPasteBound(), operator=(), and PasteAction().
PropertyHandles
TArray<TSharedPtr<IPropertyHandle> > FDetailWidgetRow::PropertyHandles
Definition at line 441 of file DetailWidgetRow.h.
Referenced by GetPropertyHandles(), operator=(), and PropertyHandleList().
ResetToDefaultWidget
FDetailWidgetDecl FDetailWidgetRow::ResetToDefaultWidget
Reset to default (right-most) column content.
Definition at line 384 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), HasResetToDefaultContent(), operator=(), and ResetToDefaultContent().
RowTagName
FName FDetailWidgetRow::RowTagName
Definition at line 431 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), GetRowName(), operator=(), and RowTag().
ValueWidget
FDetailWidgetDecl FDetailWidgetRow::ValueWidget
Value column content.
Definition at line 380 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), HasValueContent(), operator=(), and ValueContent().
VisibilityAttr
TAttribute<EVisibility> FDetailWidgetRow::VisibilityAttr
Visibility of the row.
Definition at line 388 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), operator=(), and Visibility().
WholeRowWidget
FDetailWidgetDecl FDetailWidgetRow::WholeRowWidget
Whole row content.
Definition at line 386 of file DetailWidgetRow.h.
Referenced by FDetailWidgetRow(), HasAnyContent(), operator=(), operator[](), and WholeRowContent().
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/DetailWidgetRow.h