Unreal Engine 5.6 C++ API: FArrayReader Class Reference
FArrayReader Class Reference final
#include "ArrayReader.h"
Public Member Functions
FArrayReader (bool bIsPersistent=false)
virtual FString GetArchiveName () const
Returns the name of the Archive.
void Serialize (void *Data, int64 Count)
int64 TotalSize ()
Returns total size of the backing data storage.
Public Member Functions inherited from FMemoryArchive
virtual FArchive & operator<< (class FName &N) override
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (class UObject *&Res) override
Serializes an UObject value from or into this archive.
virtual FArchive & operator<< (FField *&Value)
Serializes a Field value from or into this archive.
virtual FArchive & operator<< (FText &Value)
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (struct FLazyObjectPtr &Value)
Serializes a lazy object pointer value from or into this archive.
virtual FArchive & operator<< (struct FObjectPtr &Value)
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (struct FSoftObjectPath &Value)
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (struct FSoftObjectPtr &Value)
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (struct FWeakObjectPtr &Value)
Serializes FWeakObjectPtr value from or into this archive.
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
void Seek (int64 InPos) final
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
int64 Tell () final
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
Public Member Functions inherited from FArchive
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData)
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData)
Attaches/ associates the passed in bulk data object with the linker.
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback)
Adds external read dependency.
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
virtual bool Close ()
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
Detaches the passed in bulk data object from the linker.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
virtual void Flush ()
Attempts to finish writing any buffered data to disk/permanent storage.
virtual void FlushCache ()
Flushes cache and frees internal data.
virtual void ForceBlueprintFinalization ()
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj)
Called to retrieve the archetype from the event driven loader.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
virtual FArchive * GetCacheableArchive ()
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
virtual FLinker * GetLinker ()
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
virtual bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
virtual void MarkScriptSerializationEnd (const UObject *Obj)
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj)
Called when an object begins serializing property data using script serialization.
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopDebugDataString ()
virtual void PopFileRegionType ()
virtual void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Pop a property that was previously being serialized off the property stack.
virtual bool Precache (int64 PrecacheOffset, int64 PrecacheSize)
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
virtual void Preload (UObject *Object)
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
virtual void PushDebugDataString (const FName &DebugData)
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
virtual void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Push a property that is currently being serialized onto the property stack.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
virtual void SerializeBits (void *V, int64 LengthBits)
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params)
Serialize bulk data.
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeInt (uint32 &Value, uint32 Max)
virtual void SerializeIntPacked (uint32 &Value)
Packs int value into bytes of 7 bits with 8th bit for 'more'.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags)
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags)
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetFilterEditorOnly (bool InFilterEditorOnly)
Sets a flag indicating that this archive needs to filter editor-only content.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
virtual void SetSerializedProperty (FProperty *InProperty)
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr)
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const
Checks whether the archive wants to skip the property independent of the other flags.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
virtual void UsingCustomVersion (const struct FGuid &Guid)
Registers the custom version to the archive.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Public Member Functions inherited from TArray< uint8 >
FORCEINLINE TArray ()
Constructor, initializes element number counters.
FORCEINLINE TArray (const ElementType *Ptr, SizeType Count)
Constructor from a raw array of elements.
FORCEINLINE TArray (const TArray &Other)
Copy constructor.
FORCEINLINE TArray (const TArray &Other, SizeType ExtraSlack)
Copy constructor.
FORCEINLINE TArray (const TArray< OtherElementType, OtherAllocator > &Other)
Copy constructor with changed allocator.
TArray (const TArrayView< OtherElementType, OtherSizeType > &Other)
FORCEINLINE TArray (const TArrayView< OtherElementType, OtherSizeType > &Other)
UE_NODEBUG TArray (FIntrusiveUnsetOptionalState Tag)
TArray (std::initializer_list< uint8 > InitList)
Initializer list constructor.
FORCEINLINE TArray (TArray &&Other)
Move constructor.
TArray (TArray< OtherElementType, AllocatorType > &&Other, SizeType ExtraSlack)
Move constructor.
FORCEINLINE TArray (TArray< OtherElementType, OtherAllocator > &&Other)
Move constructor.
~TArray ()
Destructor.
UE_NODEBUG FORCEINLINE SizeType Add (const ElementType &Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE SizeType Add (ElementType &&Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE ElementType & Add_GetRef (const ElementType &Item) UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE ElementType & Add_GetRef (ElementType &&Item) UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
SizeType AddDefaulted ()
Adds new items to the end of the array, possibly reallocating the whole array to fit.
SizeType AddDefaulted (SizeType Count)
ElementType & AddDefaulted_GetRef () UE_LIFETIMEBOUND
Add a new item to the end of the array, possibly reallocating the whole array to fit.
FORCEINLINE SizeType AddUninitialized ()
Adds a given number of uninitialized elements into the array.
FORCEINLINE SizeType AddUninitialized (SizeType Count)
FORCEINLINE SizeType AddUnique (const ElementType &Item)
Adds unique element to array if it doesn't exist.
FORCEINLINE SizeType AddUnique (ElementType &&Item)
Adds unique element to array if it doesn't exist.
SizeType AddZeroed ()
Adds new items to the end of the array, possibly reallocating the whole array to fit.
SizeType AddZeroed (SizeType Count)
ElementType & AddZeroed_GetRef () UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
void Append (const ElementType *Ptr, SizeType Count)
Adds a raw array of elements to the end of the TArray.
void Append (const TArray< OtherElementType, OtherAllocatorType > &Source)
Appends the specified array to this array.
void Append (const typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType *Ptr, SizeType Count)
Adds a raw array of elements to the end of the TArray.
void Append (RangeType &&Source)
Appends the elements from a contiguous range to this array.
FORCEINLINE void Append (std::initializer_list< ElementType > InitList)
Adds an initializer list of elements to the end of the TArray.
void Append (TArray< OtherElementType, OtherAllocator > &&Source)
Appends the specified array to this array.
UE_NODEBUG FORCEINLINE RangedForIteratorType begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
UE_NODEBUG FORCEINLINE RangedForConstIteratorType begin () const
void BulkSerialize (FArchive &Ar, bool bForcePerElementSerialization=false)
Bulk serialize array as a single memory blob when loading.
FORCEINLINE void CheckAddress (const ElementType *Addr) const
Checks that the specified address is not part of an element within the container.
UE_NODEBUG FORCEINLINE void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero and less than or equal to the maximum.
bool Contains (const ComparisonType &Item) const
Checks if this array contains the element.
UE_NODEBUG FORCEINLINE bool ContainsByPredicate (Predicate Pred) const
Checks if this array contains an element for which the predicate is true.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
UE_NODEBUG void CountBytes (FArchive &Ar) const
Count bytes needed to serialize this array.
UE_NODEBUG TConstIterator CreateConstIterator () const
Creates a const iterator for the contents of this array.
UE_NODEBUG TIterator CreateIterator ()
Creates an iterator for the contents of this array.
FORCEINLINE SizeType Emplace (ArgsType &&... Args)
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
FORCEINLINE ElementType & Emplace_GetRef (ArgsType &&... Args) UE_LIFETIMEBOUND
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
FORCEINLINE void EmplaceAt (SizeType Index, ArgsType &&... Args)
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
FORCEINLINE ElementType & EmplaceAt_GetRef (SizeType Index, ArgsType &&... Args) UE_LIFETIMEBOUND
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
void Empty (SizeType Slack=0)
Empties the array.
UE_NODEBUG FORCEINLINE RangedForIteratorType end ()
UE_NODEBUG FORCEINLINE RangedForConstIteratorType end () const
TArray< ElementType > FilterByPredicate (Predicate Pred) const
Filters the elements in the array based on a predicate functor.
SizeType Find (const ElementType &Item) const
Finds element within the array.
UE_NODEBUG FORCEINLINE bool Find (const ElementType &Item, SizeType &Index) const
Finds element within the array.
ElementType * FindByKey (const KeyType &Key)
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
UE_NODEBUG FORCEINLINE const ElementType * FindByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
ElementType * FindByPredicate (Predicate Pred)
Finds an element which matches a predicate functor.
UE_NODEBUG FORCEINLINE const ElementType * FindByPredicate (Predicate Pred) const
Finds an element which matches a predicate functor.
bool FindItemByClass (SearchType **Item=nullptr, SizeType *ItemIndex=nullptr, SizeType StartIndex=0) const
Searches for the first entry of the specified type, will only work with TArray<UObject*>.
SizeType FindLast (const ElementType &Item) const
Finds element within the array starting from the end.
UE_NODEBUG FORCEINLINE bool FindLast (const ElementType &Item, SizeType &Index) const
Finds element within the array starting from the end.
UE_NODEBUG FORCEINLINE SizeType FindLastByPredicate (Predicate Pred) const
Searches the array for the last occurrence of an element which matches the specified predicate.
SizeType FindLastByPredicate (Predicate Pred, SizeType Count) const
Searches an initial subrange of the array for the last occurrence of an element which matches the specified predicate.
UE_NODEBUG FORCEINLINE SIZE_T GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container.
UE_NODEBUG ElementAllocatorType & GetAllocatorInstance ()
UE_NODEBUG const ElementAllocatorType & GetAllocatorInstance () const
UE_NODEBUG FORCEINLINE const ElementType * GetData () const UE_LIFETIMEBOUND
Helper function for returning a typed pointer to the first array entry.
UE_NODEBUG FORCEINLINE ElementType * GetData () UE_LIFETIMEBOUND
Helper function for returning a typed pointer to the first array entry.
UE_NODEBUG FORCEINLINE SizeType GetSlack () const
Returns the amount of slack in this array in elements.
UE_NODEBUG void Heapify ()
Builds an implicit heap from the array.
UE_NODEBUG FORCEINLINE void Heapify (const PREDICATE_CLASS &Predicate)
Implicit heaps.
void HeapPop (ElementType &OutItem, const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG void HeapPop (ElementType &OutItem, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
void HeapPopDiscard (const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG void HeapPopDiscard (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG SizeType HeapPush (const ElementType &InItem)
Adds a new element to the heap.
SizeType HeapPush (const ElementType &InItem, const PREDICATE_CLASS &Predicate)
Adds a new element to the heap.
UE_NODEBUG SizeType HeapPush (ElementType &&InItem)
Adds a new element to the heap.
SizeType HeapPush (ElementType &&InItem, const PREDICATE_CLASS &Predicate)
Adds a new element to the heap.
void HeapRemoveAt (SizeType Index, const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element from the heap.
UE_NODEBUG void HeapRemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element from the heap.
UE_NODEBUG void HeapSort ()
Performs heap sort on the array.
UE_NODEBUG void HeapSort (const PREDICATE_CLASS &Predicate)
Performs heap sort on the array.
UE_NODEBUG const ElementType & HeapTop () const UE_LIFETIMEBOUND
Returns the top element from the heap (does not remove the element).
UE_NODEBUG ElementType & HeapTop () UE_LIFETIMEBOUND
Returns the top element from the heap (does not remove the element).
SizeType IndexOfByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
SizeType IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
void Init (const ElementType &Element, SizeType Number)
Sets the size of the array, filling it with the given element.
SizeType Insert (const ElementType &Item, SizeType Index)
Inserts a given element into the array at given location.
SizeType Insert (const ElementType *Ptr, SizeType Count, SizeType Index)
Inserts a raw array of elements at a particular index in the TArray.
SizeType Insert (const TArray< ElementType, OtherAllocator > &Items, const SizeType InIndex)
Inserts given elements into the array at given location.
SizeType Insert (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &Items, const SizeType InIndex)
Inserts given elements into the array at given location.
SizeType Insert (ElementType &&Item, SizeType Index)
Inserts a given element into the array at given location.
SizeType Insert (std::initializer_list< ElementType > InitList, const SizeType InIndex)
Inserts given elements into the array at given location.
SizeType Insert (TArray< ElementType, OtherAllocator > &&Items, const SizeType InIndex)
Inserts given elements into the array at given location.
SizeType Insert (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &&Items, const SizeType InIndex)
Inserts given elements into the array at given location.
ElementType & Insert_GetRef (const ElementType &Item, SizeType Index) UE_LIFETIMEBOUND
Inserts a given element into the array at given location.
ElementType & Insert_GetRef (ElementType &&Item, SizeType Index) UE_LIFETIMEBOUND
Inserts a given element into the array at given location.
void InsertDefaulted (SizeType Index)
Inserts a given number of default-constructed elements into the array at a given location.
void InsertDefaulted (SizeType Index, SizeType Count)
ElementType & InsertDefaulted_GetRef (SizeType Index) UE_LIFETIMEBOUND
Inserts a default-constructed element into the array at a given location.
UE_NODEBUG FORCEINLINE void InsertUninitialized (SizeType Index)
Inserts a given number of uninitialized elements into the array at given location.
UE_NODEBUG FORCEINLINE void InsertUninitialized (SizeType Index, SizeType Count)
void InsertZeroed (SizeType Index)
Inserts a given number of zeroed elements into the array at given location.
void InsertZeroed (SizeType Index, SizeType Count)
ElementType & InsertZeroed_GetRef (SizeType Index) UE_LIFETIMEBOUND
Inserts a zeroed element into the array at given location.
bool IsEmpty () const
Returns true if the array is empty and contains no elements.
UE_NODEBUG FORCEINLINE bool IsValidIndex (SizeType Index) const
Tests if index is valid, i.e.
UE_NODEBUG FORCEINLINE const ElementType & Last (SizeType IndexFromTheEnd=0) const UE_LIFETIMEBOUND
Returns n-th last element from the array.
UE_NODEBUG FORCEINLINE ElementType & Last (SizeType IndexFromTheEnd=0) UE_LIFETIMEBOUND
Returns n-th last element from the array.
UE_NODEBUG FORCEINLINE SizeType Max () const
Returns maximum number of elements in array.
UE_NODEBUG FORCEINLINE SizeType Num () const
Returns number of elements in array.
UE_NODEBUG FORCEINLINE SIZE_T NumBytes () const
operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & () const
Immutable implicit conversion operator to constant container of compatible element type.
operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & ()
Mutable implicit conversion operator to container of compatible element type.
UE_NODEBUG FORCEINLINE bool operator!= (const TArray &OtherArray) const
Inequality operator.
UE_NODEBUG TArray & operator+= (const TArray &Other)
Appends the specified array to this array.
UE_NODEBUG TArray & operator+= (std::initializer_list< ElementType > InitList)
Appends the specified initializer list to this array.
UE_NODEBUG TArray & operator+= (TArray &&Other)
Appends the specified array to this array.
TArray & operator= (const TArray &Other)
Assignment operator.
TArray & operator= (const TArray< ElementType, OtherAllocatorType > &Other)
Assignment operator.
TArray & operator= (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &Other)
Assignment operator.
TArray & operator= (const TArrayView< OtherElementType, OtherSizeType > &Other)
FORCEINLINE TArray< uint8, InAllocatorType > & operator= (const TArrayView< OtherElementType, OtherSizeType > &Other)
TArray & operator= (std::initializer_list< uint8 > InitList)
Initializer list assignment operator.
TArray & operator= (TArray &&Other)
Move assignment operator.
TArray & operator= (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, AllocatorType > &&Other)
Move assignment operator.
UE_NODEBUG bool operator== (const TArray &OtherArray) const
Equality operator.
UE_NODEBUG bool operator== (FIntrusiveUnsetOptionalState Tag) const
UE_NODEBUG FORCEINLINE const ElementType & operator[] (SizeType Index) const UE_LIFETIMEBOUND
Array bracket operator.
UE_NODEBUG FORCEINLINE ElementType & operator[] (SizeType Index) UE_LIFETIMEBOUND
Array bracket operator.
ElementType Pop (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Pops element from the array.
UE_NODEBUG FORCEINLINE void Push (const ElementType &Item)
Pushes element into the array.
UE_NODEBUG FORCEINLINE void Push (ElementType &&Item)
Pushes element into the array.
FORCEINLINE void RangeCheck (SizeType Index) const
Checks if index is in array range.
FORCEINLINE void RangeCheck (SizeType Index, SizeType Count) const
Checks if a range of indices are in the array range.
UE_NODEBUG FORCEINLINE RangedForReverseIteratorType rbegin ()
UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType rbegin () const
SizeType Remove (const ElementType &Item)
Removes as many instances of Item as there are in the array, maintaining order but not indices.
SizeType RemoveAll (const PREDICATE_CLASS &Predicate)
Remove all instances that match the predicate, maintaining order but not indices Optimized to work with runs of matches/non-matches.
SizeType RemoveAllSwap (const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Remove all instances that match the predicate.
FORCEINLINE void RemoveAt (SizeType Index, CountType Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, optionally shrinking the array.
void RemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, then shrinks the array.
FORCEINLINE void RemoveAtSwap (SizeType Index, CountType Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, optionally shrinking the array.
FORCEINLINE void RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, then shrinks the array.
SizeType RemoveSingle (const ElementType &Item)
Removes the first occurrence of the specified item in the array, maintaining order but not indices.
SizeType RemoveSingleSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the first occurrence of the specified item in the array.
SizeType RemoveSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes all instances of a given item from the array.
UE_NODEBUG FORCEINLINE RangedForReverseIteratorType rend ()
UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType rend () const
FORCEINLINE void Reserve (SizeType Number)
Reserves memory such that the array can contain at least Number elements.
void Reset (SizeType NewSize=0)
Same as empty, but doesn't change memory allocations, unless the new size is larger than the current array.
void SetNum (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements.
void SetNumUninitialized (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements.
void SetNumUnsafeInternal (SizeType NewNum)
Does nothing except setting the new number of elements in the array.
void SetNumZeroed (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements, optionally shrinking it.
FORCEINLINE void Shrink ()
Shrinks the array's used memory to smallest possible to store elements currently in it.
UE_NODEBUG void Sort ()
Sorts the array assuming < operator is defined for the item type.
UE_NODEBUG void Sort (const PREDICATE_CLASS &Predicate)
Sorts the array using user define predicate class.
UE_NODEBUG void StableSort ()
Stable sorts the array assuming < operator is defined for the item type.
UE_NODEBUG void StableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the array using user defined predicate class.
FORCEINLINE void Swap (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
Element-wise array element swap.
FORCEINLINE void SwapMemory (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
Element-wise array memory swap.
UE_NODEBUG FORCEINLINE const ElementType & Top () const UE_LIFETIMEBOUND
Returns the top element, i.e.
UE_NODEBUG FORCEINLINE ElementType & Top () UE_LIFETIMEBOUND
Returns the top element, i.e.
void ToString (const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext) const
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") UE_NODEBUG FORCEINLINE void HeapPop(ElementType &OutItem
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") UE_NODEBUG FORCEINLINE void HeapPop(ElementType &OutItem
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") UE_NODEBUG FORCEINLINE void HeapPopDiscard(bool bAllowShrinking)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") UE_NODEBUG FORCEINLINE void HeapPopDiscard(const PREDICATE_CLASS &Predicate
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt") UE_NODEBUG FORCEINLINE void HeapRemoveAt(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt") UE_NODEBUG void HeapRemoveAt(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Pop") UE_NODEBUG FORCEINLINE ElementType Pop(bool bAllowShrinking)
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAllSwap") UE_NODEBUG FORCEINLINE SizeType RemoveAllSwap(const PREDICATE_CLASS &Predicate
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt") FORCEINLINE void RemoveAt(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap") UE_NODEBUG FORCEINLINE void RemoveAtSwap(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingleSwap") UE_NODEBUG FORCEINLINE SizeType RemoveSingleSwap(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSwap") UE_NODEBUG FORCEINLINE SizeType RemoveSwap(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum") UE_NODEBUG FORCEINLINE void SetNum(SizeType NewNum
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized") UE_NODEBUG FORCEINLINE void SetNumUninitialized(SizeType NewNum
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumZeroed") UE_NODEBUG FORCEINLINE void SetNumZeroed(SizeType NewNum
UE_NODEBUG void VerifyHeap (const PREDICATE_CLASS &Predicate)
Verifies the heap.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Additional Inherited Members
Public Types inherited from TArray< uint8 >
using AllocatorType
using ElementAllocatorType
using ElementType
using IntrusiveUnsetOptionalStateType
using RangedForConstIteratorType
using RangedForConstReverseIteratorType
using RangedForIteratorType
using RangedForReverseIteratorType
using SizeType
using TConstIterator
using TIterator
Static Public Member Functions inherited from TArray< uint8 >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
UE_NODEBUG static FORCEINLINE constexpr uint32 GetTypeSize ()
Helper function returning the size of the inner type.
Data Fields inherited from FArchive
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Data Fields inherited from TArray< uint8 >
CountType bool bAllowShrinking
bool bAllowShrinking
const PREDICATE_CLASS bool bAllowShrinking
CountType Count
const PREDICATE_CLASS & Predicate
Static Public Attributes inherited from TArray< uint8 >
static constexpr bool bHasIntrusiveUnsetOptionalState
Protected Member Functions inherited from FMemoryArchive
FMemoryArchive ()
Marked as protected to avoid instantiating this class directly.
Protected Member Functions inherited from FArchive
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Static Protected Member Functions inherited from FArchive
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Protected Attributes inherited from FMemoryArchive
int64 Offset
Protected Attributes inherited from TArray< uint8 >
ElementAllocatorType AllocatorInstance
SizeType ArrayMax
SizeType ArrayNum
Detailed Description
Definition at line 11 of file ArrayReader.h.
Constructor & Destructor Documentation
FArrayReader()
FArrayReader::FArrayReader (bool bIsPersistent = false) inline
Definition at line 14 of file ArrayReader.h.
References FArchive::SetIsLoading(), and FArchive::SetIsPersistent().
Member Function Documentation
GetArchiveName()
virtual FString FArrayReader::GetArchiveName () const inline virtual
Returns the name of the Archive.
Useful for getting the name of the package a struct or object is in when a loading error occurs.
This is overridden for the specific Archive Types
Reimplemented from FMemoryArchive.
Definition at line 26 of file ArrayReader.h.
References TEXT.
Serialize()
void FArrayReader::Serialize (void * Data, int64 Count) inline virtual
Reimplemented from FArchive.
Definition at line 33 of file ArrayReader.h.
References TArray< uint8 >::Count, FArchive::IsError(), FMemory::Memcpy(), TArray< uint8 >::Num(), FMemoryArchive::Offset, and FArchive::SetError().
TotalSize()
int64 FArrayReader::TotalSize () inline virtual
Returns total size of the backing data storage.
Reimplemented from FArchive.
Definition at line 28 of file ArrayReader.h.
References TArray< uint8 >::Num().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/ArrayReader.h