Unreal Engine 5.6 C++ API: TextFilterExpressionParser::FTextToken Class Reference
TextFilterExpressionParser::FTextToken Class Reference
#include "TextFilterExpressionEvaluator.h"
Public Types
enum class EInvertResult : uint8 { No , Yes }
Public Member Functions
FTextToken (const FTextToken &Other)
FTextToken (FTextFilterString InString, ETextFilterTextComparisonMode InTextComparisonMode, const EInvertResult InInvertResult)
FTextToken (FTextToken &&Other)
bool EvaluateAsBasicStringExpression (const ITextFilterExpressionContext *InContext) const
bool EvaluateAsComplexExpression (const ITextFilterExpressionContext *InContext, const FTextFilterString &InKey, const ETextFilterComparisonOperation InComparisonOperation) const
const FTextFilterString & GetString () const
ETextFilterTextComparisonMode GetTextComparisonMode () const
FTextToken & operator= (const FTextToken &Other)
FTextToken & operator= (FTextToken &&Other)
Private Attributes
EInvertResult InvertResult
FTextFilterString String
ETextFilterTextComparisonMode TextComparisonMode
Detailed Description
Definition at line 78 of file TextFilterExpressionEvaluator.h.
Member Enumeration Documentation
EInvertResult
enum class TextFilterExpressionParser::FTextToken::EInvertResult : uint8 strong
Enumerator
No
Yes
Definition at line 81 of file TextFilterExpressionEvaluator.h.
Constructor & Destructor Documentation
FTextToken() [1/3]
TextFilterExpressionParser::FTextToken::FTextToken (FTextFilterString InString, ETextFilterTextComparisonMode InTextComparisonMode, const EInvertResult InInvertResult) inline
Definition at line 87 of file TextFilterExpressionEvaluator.h.
References InvertResult, MoveTemp(), String, and TextComparisonMode.
Referenced by FTextToken(), FTextToken(), operator=(), and operator=().
FTextToken() [2/3]
TextFilterExpressionParser::FTextToken::FTextToken (const FTextToken & Other) inline
Definition at line 94 of file TextFilterExpressionEvaluator.h.
References FTextToken(), InvertResult, Other, String, and TextComparisonMode.
FTextToken() [3/3]
TextFilterExpressionParser::FTextToken::FTextToken (FTextToken && Other) inline
Definition at line 101 of file TextFilterExpressionEvaluator.h.
References FTextToken(), InvertResult, MoveTemp(), Other, String, and TextComparisonMode.
Member Function Documentation
EvaluateAsBasicStringExpression()
bool TextFilterExpressionParser::FTextToken::EvaluateAsBasicStringExpression (const ITextFilterExpressionContext * InContext) const inline
Definition at line 129 of file TextFilterExpressionEvaluator.h.
References InvertResult, No, String, ITextFilterExpressionContext::TestBasicStringExpression(), and TextComparisonMode.
EvaluateAsComplexExpression()
bool TextFilterExpressionParser::FTextToken::EvaluateAsComplexExpression (const ITextFilterExpressionContext * InContext, const FTextFilterString & InKey, const ETextFilterComparisonOperation InComparisonOperation) const inline
Definition at line 141 of file TextFilterExpressionEvaluator.h.
References FTextFilterString::AsName(), InvertResult, No, String, ITextFilterExpressionContext::TestComplexExpression(), and TextComparisonMode.
GetString()
const FTextFilterString & TextFilterExpressionParser::FTextToken::GetString () const inline
Definition at line 124 of file TextFilterExpressionEvaluator.h.
References String.
GetTextComparisonMode()
ETextFilterTextComparisonMode TextFilterExpressionParser::FTextToken::GetTextComparisonMode () const inline
Definition at line 147 of file TextFilterExpressionEvaluator.h.
References TextComparisonMode.
operator=() [1/2]
FTextToken & TextFilterExpressionParser::FTextToken::operator= (const FTextToken & Other) inline
Definition at line 108 of file TextFilterExpressionEvaluator.h.
References FTextToken(), InvertResult, Other, String, and TextComparisonMode.
operator=() [2/2]
FTextToken & TextFilterExpressionParser::FTextToken::operator= (FTextToken && Other) inline
Definition at line 116 of file TextFilterExpressionEvaluator.h.
References FTextToken(), InvertResult, MoveTemp(), Other, String, and TextComparisonMode.
Field Documentation
InvertResult
EInvertResult TextFilterExpressionParser::FTextToken::InvertResult private
Definition at line 155 of file TextFilterExpressionEvaluator.h.
Referenced by FTextToken(), FTextToken(), FTextToken(), EvaluateAsBasicStringExpression(), EvaluateAsComplexExpression(), operator=(), and operator=().
String
FTextFilterString TextFilterExpressionParser::FTextToken::String private
Definition at line 153 of file TextFilterExpressionEvaluator.h.
Referenced by FTextToken(), FTextToken(), FTextToken(), EvaluateAsBasicStringExpression(), EvaluateAsComplexExpression(), GetString(), operator=(), and operator=().
TextComparisonMode
ETextFilterTextComparisonMode TextFilterExpressionParser::FTextToken::TextComparisonMode private
Definition at line 154 of file TextFilterExpressionEvaluator.h.
Referenced by FTextToken(), FTextToken(), FTextToken(), EvaluateAsBasicStringExpression(), EvaluateAsComplexExpression(), GetTextComparisonMode(), operator=(), and operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/TextFilterExpressionEvaluator.h