Unreal Engine 5.6 C++ API: IDisplayClusterProjectionPolicy Class Reference
IDisplayClusterProjectionPolicy Class Reference abstract
nDisplay projection policy
#include "IDisplayClusterProjectionPolicy.h"
Public Member Functions
virtual ~IDisplayClusterProjectionPolicy ()=default
virtual void ApplyWarpBlend_RenderThread (FRHICommandListImmediate &RHICmdList, const IDisplayClusterViewportProxy *InViewportProxy)
Performs Warp and Blend on the rendering thread Have to be called only if IsWarpBlendSupported_RenderThread() returns true.
virtual void BeginUpdateFrameContexts (IDisplayClusterViewport *InViewport) const
Called before FDisplayClusterViewport::UpdateFrameContexts() From this function, the policy can override any viewport settings (custom overscan, etc).
virtual void BeginWarpBlend_RenderThread (FRHICommandListImmediate &RHICmdList, const IDisplayClusterViewportProxy *InViewportProxy)
Initializing the projection policy logic for the current frame before applying warp blending.
virtual bool CalculateView (IDisplayClusterViewport *InViewport, const uint32 InContextNum, FVector &InOutViewLocation, FRotator &InOutViewRotation, const FVector &ViewOffset, const float WorldToMeters, const float NCP, const float FCP)=0
Calculate view projection data.
virtual void EndUpdateFrameContexts (IDisplayClusterViewport *InViewport) const
Called after FDisplayClusterViewport::UpdateFrameContexts()
virtual void EndWarpBlend_RenderThread (FRHICommandListImmediate &RHICmdList, const IDisplayClusterViewportProxy *InViewportProxy)
Completing the projection policy logic for the current frame after applying warp blending.
virtual bool GetCustomRenderTargetSize (const IDisplayClusterViewport *InViewport, FIntPoint &OutRenderTargetSize) const
This function can override the size of the RenderTarget texture for the viewport.
virtual const FString & GetId () const =0
Return projection policy instance ID.
virtual UMeshComponent * GetOrCreatePreviewEditableMeshComponent (IDisplayClusterViewport *InViewport)
Build preview Editable mesh This MeshComponent is a copy of the preview mesh and can be moved freely with the UI visualization.
virtual UMeshComponent * GetOrCreatePreviewMeshComponent (IDisplayClusterViewport *InViewport, bool &bOutIsRootActorComponent)
Build preview mesh This MeshComponent cannot be moved freely.
virtual USceneComponent *const GetOriginComponent () const
Return Origin point component used by this viewport This component is used to convert from the local DCRA space to the local projection policy space, which contains the calibrated geometry data used for the warp.
virtual const TMap< FString, FString > & GetParameters () const =0
Return projection policy configuration.
virtual USceneComponent *const GetPreviewEditableMeshOriginComponent (IDisplayClusterViewport *InViewport) const
Return Origin point component used by preview Editable mesh.
virtual USceneComponent *const GetPreviewMeshOriginComponent (IDisplayClusterViewport *InViewport) const
Return Origin point component used by preview mesh.
virtual bool GetProjectionMatrix (IDisplayClusterViewport *InViewport, const uint32 InContextNum, FMatrix &OutPrjMatrix)=0
Gets projection matrix.
virtual const FString & GetType () const =0
Return projection policy type.
virtual bool GetWarpBlendInterface (TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > &OutWarpBlendInterface) const
Return warpblend interface of this policy.
virtual bool GetWarpBlendInterface_RenderThread (TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > &OutWarpBlendInterfaceProxy) const
Return warpblend interface proxy of this policy.
virtual IDisplayClusterWarpPolicy * GetWarpPolicy () const
Get warp policy.
virtual IDisplayClusterWarpPolicy * GetWarpPolicy_RenderThread () const
Get warp policy on rendering thread.
virtual void HandleEndScene (IDisplayClusterViewport *InViewport)
Called when current level is going to be closed (i.e.
virtual bool HandleStartScene (IDisplayClusterViewport *InViewport)
Called each time a new game level starts.
virtual bool HasPreviewEditableMesh (IDisplayClusterViewport *InViewport)
Ask projection policy instance if it has any Editable mesh based preview.
virtual bool HasPreviewMesh (IDisplayClusterViewport *InViewport)
Ask projection policy instance if it has any mesh based preview.
virtual bool IsCameraProjectionVisible (const FRotator &InViewRotation, const FVector &InViewLocation, const FMatrix &InProjectionMatrix)
virtual bool IsConfigurationChanged (const struct FDisplayClusterConfigurationProjection *InConfigurationProjectionPolicy) const =0
Check projection policy settings changes.
virtual bool IsFrustumRotatedToFitContextSize (IDisplayClusterViewport *InViewport, const uint32 InContextNum)
Returns true if the frustum has been rotated to fit the context size.
virtual bool IsWarpBlendSupported (const IDisplayClusterViewport *InViewport) const
Returns if a policy provides warp&blend feature.
virtual bool IsWarpBlendSupported_RenderThread (const IDisplayClusterViewportProxy *InViewportProxy) const
Returns if a policy provides warp&blend feature (.
virtual void PostUpdateBaseConfiguration (IDisplayClusterViewport *InViewport) const
Called after the base configuration is completed, but before the ICVFX.
virtual bool ResolveInternalRenderTargetResource_RenderThread (FRHICommandListImmediate &RHICmdList, const IDisplayClusterViewportProxy *InViewportProxy, const IDisplayClusterViewportProxy *InSourceViewportProxy)
Override copying 'InternalRenderTargetResource' to 'InputShaderResource'.
virtual void SetupProjectionViewPoint (IDisplayClusterViewport *InViewport, const float InDeltaTime, FMinimalViewInfo &InOutViewInfo, float *OutCustomNearClippingPlane=nullptr)
Override view from this projection policy.
virtual void SetWarpPolicy (IDisplayClusterWarpPolicy *InWarpPolicy)
Set warp policy for this projection.
virtual bool ShouldSupportICVFX (const IDisplayClusterViewport *InViewport) const
Returns true if this policy supports ICVFX rendering.
virtual bool ShouldUseAdditionalTargetableResource (const IDisplayClusterViewport *InViewport) const
virtual bool ShouldUseAnySizeScaleForRenderTarget (const IDisplayClusterViewport *InViewport) const
This function controls the RTT size multipliers - if false is returned, all modifiers should be ignored.
virtual bool ShouldUseSourceTextureWithMips (const IDisplayClusterViewport *InViewport) const
Returns true if the policy supports input mip-textures.
virtual bool ShouldUseViewPointComponentPostProcesses (IDisplayClusterViewport *InViewport) const
UE_DEPRECATED (5.1, "This function has been deprecated. Please use 'GetType'.") virtual const FString GetTypeId() const
Return projection policy type.
UE_DEPRECATED (5.3, "This function has been deprecated. Please use 'ShouldSupportICVFX(IDisplayClusterViewport*)'.") virtual bool ShouldSupportICVFX() const
UE_DEPRECATED (5.4, "This function has been deprecated. Please use 'HasPreviewMesh(IDisplayClusterViewport*)'.") virtual bool HasPreviewMesh()
Ask projection policy instance if it has any mesh based preview.
UE_DEPRECATED (5.6, "This function has been deprecated. Please use 'IsWarpBlendSupported(IDisplayClusterViewport*) or IsWarpBlendSupported_RenderThread(IDisplayClusterViewportProxy*)'.") virtual bool IsWarpBlendSupported()
Returns if a policy provides warp&blend feature.
UE_DEPRECATED (5.6, "This function has been deprecated. Please use 'ShouldUseAdditionalTargetableResource(IDisplayClusterViewport*).") virtual bool ShouldUseAdditionalTargetableResource() const
UE_DEPRECATED (5.6, "This function has been deprecated. Please use 'ShouldUseSourceTextureWithMips(IDisplayClusterViewport*).") virtual bool ShouldUseSourceTextureWithMips() const
Returns true if the policy supports input mip-textures.
virtual void UpdatePostProcessSettings (IDisplayClusterViewport *InViewport)
Projection policy can override PP.
virtual void UpdateProxyData (IDisplayClusterViewport *InViewport)
Send projection policy game thread data to render thread proxy called once per frame from FDisplayClusterViewportManager::FinalizeNewFrame.
Detailed Description
nDisplay projection policy
Definition at line 20 of file IDisplayClusterProjectionPolicy.h.
Constructor & Destructor Documentation
~IDisplayClusterProjectionPolicy()
virtual IDisplayClusterProjectionPolicy::~IDisplayClusterProjectionPolicy () virtual default
Member Function Documentation
ApplyWarpBlend_RenderThread()
virtual void IDisplayClusterProjectionPolicy::ApplyWarpBlend_RenderThread (FRHICommandListImmediate & RHICmdList, const IDisplayClusterViewportProxy * InViewportProxy) inline virtual
Performs Warp and Blend on the rendering thread Have to be called only if IsWarpBlendSupported_RenderThread() returns true.
Parameters
RHICmdList - RHI commands
InViewportProxy - viewport proxy
Definition at line 303 of file IDisplayClusterProjectionPolicy.h.
BeginUpdateFrameContexts()
virtual void IDisplayClusterProjectionPolicy::BeginUpdateFrameContexts (IDisplayClusterViewport * InViewport) const inline virtual
Called before FDisplayClusterViewport::UpdateFrameContexts() From this function, the policy can override any viewport settings (custom overscan, etc).
Parameters
InViewport - a owner viewport
Definition at line 99 of file IDisplayClusterProjectionPolicy.h.
BeginWarpBlend_RenderThread()
virtual void IDisplayClusterProjectionPolicy::BeginWarpBlend_RenderThread (FRHICommandListImmediate & RHICmdList, const IDisplayClusterViewportProxy * InViewportProxy) inline virtual
Initializing the projection policy logic for the current frame before applying warp blending.
Have to be called only if IsWarpBlendSupported_RenderThread() returns true
Parameters
RHICmdList - RHI commands
InViewportProxy - viewport proxy
Definition at line 292 of file IDisplayClusterProjectionPolicy.h.
CalculateView()
virtual bool IDisplayClusterProjectionPolicy::CalculateView (IDisplayClusterViewport * InViewport, const uint32 InContextNum, FVector & InOutViewLocation, FRotator & InOutViewRotation, const FVector & ViewOffset, const float WorldToMeters, const float NCP, const float FCP) pure virtual
Calculate view projection data.
Parameters
InViewport - a owner viewport
InContextNum - Index of view that is being processed for this viewport
InOutViewLocation - (in/out) View location with ViewOffset (i.e. left eye pre-computed location)
InOutViewRotation - (in/out) View rotation
ViewOffset - Offset applied ot a camera location that gives us InOutViewLocation (i.e. right offset in world to compute right eye location)
WorldToMeters - Current world scale (units (cm) in meter)
NCP - Distance to the near clipping plane
FCP - Distance to the far clipping plane
Returns
- True if success
References FVector.
EndUpdateFrameContexts()
virtual void IDisplayClusterProjectionPolicy::EndUpdateFrameContexts (IDisplayClusterViewport * InViewport) const inline virtual
Called after FDisplayClusterViewport::UpdateFrameContexts()
Parameters
InViewport - a owner viewport
Definition at line 107 of file IDisplayClusterProjectionPolicy.h.
EndWarpBlend_RenderThread()
virtual void IDisplayClusterProjectionPolicy::EndWarpBlend_RenderThread (FRHICommandListImmediate & RHICmdList, const IDisplayClusterViewportProxy * InViewportProxy) inline virtual
Completing the projection policy logic for the current frame after applying warp blending.
Have to be called only if IsWarpBlendSupported_RenderThread() returns true
Parameters
ViewIdx - Index of view that is being processed for this viewport
RHICmdList - RHI commands
SrcTexture - Source texture
ViewportRect - Region of the SrcTexture to perform warp&blend operations
Definition at line 316 of file IDisplayClusterProjectionPolicy.h.
GetCustomRenderTargetSize()
virtual bool IDisplayClusterProjectionPolicy::GetCustomRenderTargetSize (const IDisplayClusterViewport * InViewport, FIntPoint & OutRenderTargetSize) const inline virtual
This function can override the size of the RenderTarget texture for the viewport.
Parameters
InViewport - viewport to override RTT size.
OutRenderTargetSize - (out) the desired RTT size.
Returns
is true if the RTT size should be overridden.
Definition at line 265 of file IDisplayClusterProjectionPolicy.h.
GetId()
virtual const FString & IDisplayClusterProjectionPolicy::GetId () const pure virtual
Return projection policy instance ID.
GetOrCreatePreviewEditableMeshComponent()
virtual UMeshComponent * IDisplayClusterProjectionPolicy::GetOrCreatePreviewEditableMeshComponent (IDisplayClusterViewport * InViewport) inline virtual
Build preview Editable mesh This MeshComponent is a copy of the preview mesh and can be moved freely with the UI visualization.
Parameters
InViewport - a owner viewport
Definition at line 410 of file IDisplayClusterProjectionPolicy.h.
GetOrCreatePreviewMeshComponent()
virtual UMeshComponent * IDisplayClusterProjectionPolicy::GetOrCreatePreviewMeshComponent (IDisplayClusterViewport * InViewport, bool & bOutIsRootActorComponent) inline virtual
Build preview mesh This MeshComponent cannot be moved freely.
This MeshComponent is attached to the geometry from the real world via Origin. When the screen geometry in the real world changes position, the position of this component must also be changed.
Parameters
InViewport - Projection specific parameters.
bOutIsRootActorComponent - return true, if used custom root actor component. return false, if created unique temporary component
Definition at line 378 of file IDisplayClusterProjectionPolicy.h.
GetOriginComponent()
virtual USceneComponent *const IDisplayClusterProjectionPolicy::GetOriginComponent () const inline virtual
Return Origin point component used by this viewport This component is used to convert from the local DCRA space to the local projection policy space, which contains the calibrated geometry data used for the warp.
Definition at line 55 of file IDisplayClusterProjectionPolicy.h.
GetParameters()
virtual const TMap< FString, FString > & IDisplayClusterProjectionPolicy::GetParameters () const pure virtual
Return projection policy configuration.
GetPreviewEditableMeshOriginComponent()
virtual USceneComponent *const IDisplayClusterProjectionPolicy::GetPreviewEditableMeshOriginComponent (IDisplayClusterViewport * InViewport) const inline virtual
Return Origin point component used by preview Editable mesh.
Parameters
InViewport - a owner viewport
Definition at line 420 of file IDisplayClusterProjectionPolicy.h.
GetPreviewMeshOriginComponent()
virtual USceneComponent *const IDisplayClusterProjectionPolicy::GetPreviewMeshOriginComponent (IDisplayClusterViewport * InViewport) const inline virtual
Return Origin point component used by preview mesh.
Parameters
InViewport - a owner viewport
Definition at line 388 of file IDisplayClusterProjectionPolicy.h.
GetProjectionMatrix()
virtual bool IDisplayClusterProjectionPolicy::GetProjectionMatrix (IDisplayClusterViewport * InViewport, const uint32 InContextNum, FMatrix & OutPrjMatrix) pure virtual
Gets projection matrix.
Parameters
InViewport - a owner viewport
InContextNum - Index of view that is being processed for this viewport
OutPrjMatrix - (out) projection matrix
Returns
- True if success
GetType()
virtual const FString & IDisplayClusterProjectionPolicy::GetType () const pure virtual
Return projection policy type.
Referenced by UE_DEPRECATED().
GetWarpBlendInterface()
virtual bool IDisplayClusterProjectionPolicy::GetWarpBlendInterface (TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > & OutWarpBlendInterface) const inline virtual
Return warpblend interface of this policy.
Parameters
OutWarpBlendInterface - output interface ref
Returns
- true if output interface valid
Definition at line 326 of file IDisplayClusterProjectionPolicy.h.
GetWarpBlendInterface_RenderThread()
virtual bool IDisplayClusterProjectionPolicy::GetWarpBlendInterface_RenderThread (TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > & OutWarpBlendInterfaceProxy) const inline virtual
Return warpblend interface proxy of this policy.
Parameters
OutWarpBlendInterfaceProxy - output interface ref
Returns
- true if output interface valid
Definition at line 338 of file IDisplayClusterProjectionPolicy.h.
GetWarpPolicy()
virtual IDisplayClusterWarpPolicy * IDisplayClusterProjectionPolicy::GetWarpPolicy () const inline virtual
Get warp policy.
Definition at line 121 of file IDisplayClusterProjectionPolicy.h.
GetWarpPolicy_RenderThread()
virtual IDisplayClusterWarpPolicy * IDisplayClusterProjectionPolicy::GetWarpPolicy_RenderThread () const inline virtual
Get warp policy on rendering thread.
Definition at line 129 of file IDisplayClusterProjectionPolicy.h.
HandleEndScene()
virtual void IDisplayClusterProjectionPolicy::HandleEndScene (IDisplayClusterViewport * InViewport) inline virtual
Called when current level is going to be closed (i.e.
before loading a new map)
Parameters
InViewport - a owner viewport
Definition at line 82 of file IDisplayClusterProjectionPolicy.h.
HandleStartScene()
virtual bool IDisplayClusterProjectionPolicy::HandleStartScene (IDisplayClusterViewport * InViewport) inline virtual
Called each time a new game level starts.
Parameters
InViewport - a owner viewport
Definition at line 72 of file IDisplayClusterProjectionPolicy.h.
HasPreviewEditableMesh()
virtual bool IDisplayClusterProjectionPolicy::HasPreviewEditableMesh (IDisplayClusterViewport * InViewport) inline virtual
Ask projection policy instance if it has any Editable mesh based preview.
Parameters
InViewport - a owner viewport
Returns
- True if mesh based preview is available
Definition at line 399 of file IDisplayClusterProjectionPolicy.h.
HasPreviewMesh()
virtual bool IDisplayClusterProjectionPolicy::HasPreviewMesh (IDisplayClusterViewport * InViewport) inline virtual
Ask projection policy instance if it has any mesh based preview.
Parameters
InViewport - a owner viewport
Returns
- True if mesh based preview is available
Definition at line 364 of file IDisplayClusterProjectionPolicy.h.
Referenced by UE_DEPRECATED().
IsCameraProjectionVisible()
virtual bool IDisplayClusterProjectionPolicy::IsCameraProjectionVisible (const FRotator & InViewRotation, const FVector & InViewLocation, const FMatrix & InProjectionMatrix) inline virtual
Definition at line 162 of file IDisplayClusterProjectionPolicy.h.
References FVector.
IsConfigurationChanged()
virtual bool IDisplayClusterProjectionPolicy::IsConfigurationChanged (const struct FDisplayClusterConfigurationProjection * InConfigurationProjectionPolicy) const pure virtual
Check projection policy settings changes.
Parameters
InConfigurationProjectionPolicy - new settings
Returns
- True if found changes
IsFrustumRotatedToFitContextSize()
virtual bool IDisplayClusterProjectionPolicy::IsFrustumRotatedToFitContextSize (IDisplayClusterViewport * InViewport, const uint32 InContextNum) inline virtual
Returns true if the frustum has been rotated to fit the context size.
Parameters
InViewport - a owner viewport
InContextNum - Index of view that is being processed for this viewport
Returns
true is success.
Definition at line 231 of file IDisplayClusterProjectionPolicy.h.
IsWarpBlendSupported()
virtual bool IDisplayClusterProjectionPolicy::IsWarpBlendSupported (const IDisplayClusterViewport * InViewport) const inline virtual
Returns if a policy provides warp&blend feature.
Returns
- True if warp&blend operations are supported by the policy implementation
Definition at line 241 of file IDisplayClusterProjectionPolicy.h.
Referenced by UE_DEPRECATED().
IsWarpBlendSupported_RenderThread()
virtual bool IDisplayClusterProjectionPolicy::IsWarpBlendSupported_RenderThread (const IDisplayClusterViewportProxy * InViewportProxy) const inline virtual
Returns if a policy provides warp&blend feature (.
Returns
- True if warp&blend operations are supported by the policy implementation
Definition at line 252 of file IDisplayClusterProjectionPolicy.h.
PostUpdateBaseConfiguration()
virtual void IDisplayClusterProjectionPolicy::PostUpdateBaseConfiguration (IDisplayClusterViewport * InViewport) const inline virtual
Called after the base configuration is completed, but before the ICVFX.
Parameters
InViewport - a owner viewport
Definition at line 90 of file IDisplayClusterProjectionPolicy.h.
ResolveInternalRenderTargetResource_RenderThread()
virtual bool IDisplayClusterProjectionPolicy::ResolveInternalRenderTargetResource_RenderThread (FRHICommandListImmediate & RHICmdList, const IDisplayClusterViewportProxy * InViewportProxy, const IDisplayClusterViewportProxy * InSourceViewportProxy) inline virtual
Override copying 'InternalRenderTargetResource' to 'InputShaderResource'.
The same behavior as for function bellow is expected: ResolveResources_RenderThread(RHICmdList, InSourceViewportProxy, InSrcResourceType, InDstResourceType);
Parameters
InViewportProxy - This ViewportProxy will get the result
InSourceViewportProxy - This ViewportProxy will provide the input resource
Returns
- true, if copying is overridden.
Definition at line 353 of file IDisplayClusterProjectionPolicy.h.
SetupProjectionViewPoint()
virtual void IDisplayClusterProjectionPolicy::SetupProjectionViewPoint (IDisplayClusterViewport * InViewport, const float InDeltaTime, FMinimalViewInfo & InOutViewInfo, float * OutCustomNearClippingPlane = nullptr) inline virtual
Override view from this projection policy.
Parameters
InViewport - a owner viewport
InDeltaTime - delta time in current frame
InOutViewInfo - ViewInfo data
OutCustomNearClippingPlane - Custom NCP, or a value less than zero if not defined.
Definition at line 183 of file IDisplayClusterProjectionPolicy.h.
SetWarpPolicy()
virtual void IDisplayClusterProjectionPolicy::SetWarpPolicy (IDisplayClusterWarpPolicy * InWarpPolicy) inline virtual
Set warp policy for this projection.
Parameters
InWarpPolicy - the warp policy instance
Definition at line 115 of file IDisplayClusterProjectionPolicy.h.
ShouldSupportICVFX()
virtual bool IDisplayClusterProjectionPolicy::ShouldSupportICVFX (const IDisplayClusterViewport * InViewport) const inline virtual
Returns true if this policy supports ICVFX rendering.
Parameters
InViewport - a owner viewport
Definition at line 155 of file IDisplayClusterProjectionPolicy.h.
Referenced by UE_DEPRECATED().
ShouldUseAdditionalTargetableResource()
virtual bool IDisplayClusterProjectionPolicy::ShouldUseAdditionalTargetableResource (const IDisplayClusterViewport * InViewport) const inline virtual
Definition at line 135 of file IDisplayClusterProjectionPolicy.h.
Referenced by UE_DEPRECATED().
ShouldUseAnySizeScaleForRenderTarget()
virtual bool IDisplayClusterProjectionPolicy::ShouldUseAnySizeScaleForRenderTarget (const IDisplayClusterViewport * InViewport) const inline virtual
This function controls the RTT size multipliers - if false is returned, all modifiers should be ignored.
Here is the list of ignored modifiers: RenderTargetAdaptRatio, RenderTargetRatio, ClusterRenderTargetRatioMult, ClusterICVFXOuterViewportRenderTargetRatioMult, ClusterICVFXInnerViewportRenderTargetRatioMult
Parameters
InViewport - the DC viewport.
Definition at line 279 of file IDisplayClusterProjectionPolicy.h.
ShouldUseSourceTextureWithMips()
virtual bool IDisplayClusterProjectionPolicy::ShouldUseSourceTextureWithMips (const IDisplayClusterViewport * InViewport) const inline virtual
Returns true if the policy supports input mip-textures.
Use a mip texture for smoother deformation on curved surfaces.
Returns
- true, if mip-texture is supported by the policy implementation
Definition at line 146 of file IDisplayClusterProjectionPolicy.h.
Referenced by UE_DEPRECATED().
ShouldUseViewPointComponentPostProcesses()
virtual bool IDisplayClusterProjectionPolicy::ShouldUseViewPointComponentPostProcesses (IDisplayClusterViewport * InViewport) const inline virtual
Definition at line 187 of file IDisplayClusterProjectionPolicy.h.
UE_DEPRECATED() [1/6]
IDisplayClusterProjectionPolicy::UE_DEPRECATED (5. 1, "This function has been deprecated. Please use 'GetType'.") const inline
Return projection policy type.
Definition at line 39 of file IDisplayClusterProjectionPolicy.h.
References GetType().
UE_DEPRECATED() [2/6]
IDisplayClusterProjectionPolicy::UE_DEPRECATED (5. 3, "This function has been deprecated. Please use 'ShouldSupportICVFX(IDisplayClusterViewport*)'.") const inline
Definition at line 428 of file IDisplayClusterProjectionPolicy.h.
References ShouldSupportICVFX().
UE_DEPRECATED() [3/6]
IDisplayClusterProjectionPolicy::UE_DEPRECATED (5. 4, "This function has been deprecated. Please use 'HasPreviewMesh(IDisplayClusterViewport*)'.") inline
Ask projection policy instance if it has any mesh based preview.
Returns
- True if mesh based preview is available
Definition at line 441 of file IDisplayClusterProjectionPolicy.h.
References HasPreviewMesh().
UE_DEPRECATED() [4/6]
IDisplayClusterProjectionPolicy::UE_DEPRECATED (5. 6, "This function has been deprecated. Please use 'IsWarpBlendSupported(IDisplayClusterViewport*) or IsWarpBlendSupported_RenderThread(IDisplayClusterViewportProxy*)'.") inline
Returns if a policy provides warp&blend feature.
Returns
- True if warp&blend operations are supported by the policy implementation
Definition at line 452 of file IDisplayClusterProjectionPolicy.h.
References IsWarpBlendSupported().
UE_DEPRECATED() [5/6]
IDisplayClusterProjectionPolicy::UE_DEPRECATED (5. 6, "This function has been deprecated. Please use 'ShouldUseAdditionalTargetableResource(IDisplayClusterViewport*).") const inline
Definition at line 459 of file IDisplayClusterProjectionPolicy.h.
References ShouldUseAdditionalTargetableResource().
UE_DEPRECATED() [6/6]
IDisplayClusterProjectionPolicy::UE_DEPRECATED (5. 6, "This function has been deprecated. Please use 'ShouldUseSourceTextureWithMips(IDisplayClusterViewport*).") const inline
Returns true if the policy supports input mip-textures.
Use a mip texture for smoother deformation on curved surfaces.
Returns
- true, if mip-texture is supported by the policy implementation
Definition at line 471 of file IDisplayClusterProjectionPolicy.h.
References ShouldUseSourceTextureWithMips().
UpdatePostProcessSettings()
virtual void IDisplayClusterProjectionPolicy::UpdatePostProcessSettings (IDisplayClusterViewport * InViewport) inline virtual
Projection policy can override PP.
Parameters
InViewport - a owner viewport
Definition at line 196 of file IDisplayClusterProjectionPolicy.h.
UpdateProxyData()
virtual void IDisplayClusterProjectionPolicy::UpdateProxyData (IDisplayClusterViewport * InViewport) inline virtual
Send projection policy game thread data to render thread proxy called once per frame from FDisplayClusterViewportManager::FinalizeNewFrame.
Definition at line 64 of file IDisplayClusterProjectionPolicy.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Render/Projection/IDisplayClusterProjectionPolicy.h