Unreal Engine 5.6 C++ API: FTickableCookObject Class Reference
FTickableCookObject Class Reference abstract
The same as FTickableEditorObject, but for systems that need to be ticked periodically during cooking.
#include "TickableEditorObject.h"
Public Member Functions
FTickableCookObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableCookObject ()
Removes this instance from the static array of tickable objects.
virtual void TickCook (float DeltaTime, bool bCookCompete)=0
Cook tick virtual, must be implemented in subclass.
UE_NONCOPYABLE (FTickableCookObject)
Public Member Functions inherited from FTickableObjectBase
virtual TStatId GetStatId () const =0
Return the stat id used to track the performance of this object.
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
virtual void Tick (float DeltaTime)=0
Pure virtual that must be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Public Member Functions
static void TickObjects (const float DeltaSeconds, bool bCookComplete)
Calls TickCook on every enabled tickable object.
Static Private Member Functions
static UNREALED_API FTickableStatics & GetStatics ()
Returns the tracking struct for this type.
Static Private Attributes
static UNREALED_API FTickableObjectBase * ObjectBeingTicked
Set if we are in the Tick function for an editor tickable object.
Additional Inherited Members
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
The same as FTickableEditorObject, but for systems that need to be ticked periodically during cooking.
If a system needs to be cooked both during cook commandlet and in editor without the cook commandlet, it should dual-inherit from both FTickableCookObject and FTickableEditorObject.
Definition at line 71 of file TickableEditorObject.h.
Constructor & Destructor Documentation
FTickableCookObject()
FTickableCookObject::FTickableCookObject () inline
Registers this instance with the static array of tickable objects.
Definition at line 91 of file TickableEditorObject.h.
References ensure, GetStatics(), IsInAsyncLoadingThread, IsInGameThread(), and FTickableObjectBase::FTickableStatics::QueueTickableObjectForAdd().
Referenced by TickObjects(), and UE_NONCOPYABLE().
~FTickableCookObject()
virtual FTickableCookObject::~FTickableCookObject () inline virtual
Removes this instance from the static array of tickable objects.
Definition at line 100 of file TickableEditorObject.h.
References ensure, ensureMsgf, GetStatics(), IsInAsyncLoadingThread, IsInGameThread(), Never, ObjectBeingTicked, FTickableObjectBase::FTickableStatics::SetTickTypeForTickableObject(), and TEXT.
Member Function Documentation
GetStatics()
UNREALED_API FTickableStatics & FTickableCookObject::GetStatics () static private
Returns the tracking struct for this type.
Referenced by FTickableCookObject(), ~FTickableCookObject(), and TickObjects().
TickCook()
virtual void FTickableCookObject::TickCook (float DeltaTime, bool bCookCompete) pure virtual
Cook tick virtual, must be implemented in subclass.
References DeltaTime.
Referenced by TickObjects().
TickObjects()
void FTickableCookObject::TickObjects (const float DeltaSeconds, bool bCookComplete) inline static
Calls TickCook on every enabled tickable object.
Definition at line 77 of file TickableEditorObject.h.
References FTickableCookObject(), GetStatics(), ObjectBeingTicked, FTickableObjectBase::SimpleTickObjects(), and TickCook().
UE_NONCOPYABLE()
FTickableCookObject::UE_NONCOPYABLE (FTickableCookObject)
References FTickableCookObject().
Field Documentation
ObjectBeingTicked
UNREALED_API FTickableObjectBase* FTickableCookObject::ObjectBeingTicked static private
Set if we are in the Tick function for an editor tickable object.
Definition at line 115 of file TickableEditorObject.h.
Referenced by ~FTickableCookObject(), and TickObjects().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/TickableEditorObject.h