Unreal Engine 5.6 C++ API: FBulkDataBuffer< DataType > Class Template Reference
FBulkDataBuffer< DataType > Class Template Reference
Used to manage a raw data buffer provided by BulkData while providing access to it via a TArrayView.
#include "BulkDataBuffer.h"
Public Types
using ViewType = TArrayView64<DataType>
Public Member Functions
FBulkDataBuffer ()=default
Constructor.
FBulkDataBuffer (const FBulkDataBuffer &Other)
Copy constructor which will create it's own memory buffer and then copy from the source object rather than share access to the same buffer.
FBulkDataBuffer (DataType *InBuffer, int64 InNumberOfElements)
Constructor.
FBulkDataBuffer (FBulkDataBuffer &&Other)
Move constructor.
~FBulkDataBuffer ()
Destructor.
void Empty ()
Frees the internal buffer and sets the internal TArrayView to an empty state.
const ViewType & GetView () const
Allows access to the data buffer owned by the object in the form of a TArrayView.
FBulkDataBuffer & operator= (const FBulkDataBuffer &Other)
Assignment operator which will create it's own memory buffer and then copy from the source object rather than share access to the same buffer.
FBulkDataBuffer & operator= (FBulkDataBuffer &&Other)
Move assignment operator.
void Reset (DataType *InBuffer, uint64 InNumberOfElements)
Frees any existing buffer and takes ownership of the buffer provided instead.
Private Member Functions
void FreeBuffer ()
Private Attributes
ViewType View
Detailed Description
template<typename DataType>
class FBulkDataBuffer< DataType >
Used to manage a raw data buffer provided by BulkData while providing access to it via a TArrayView.
This object assumes that it owns the buffer that it has been given and will free the memory when the object is destroyed.
Definition at line 15 of file BulkDataBuffer.h.
Member Typedef Documentation
ViewType
template<typename DataType> using FBulkDataBuffer< DataType >::ViewType = TArrayView64<DataType>
Definition at line 18 of file BulkDataBuffer.h.
Constructor & Destructor Documentation
FBulkDataBuffer() [1/4]
template<typename DataType> FBulkDataBuffer< DataType >::FBulkDataBuffer () default
Constructor.
Referenced by FBulkDataBuffer(), FBulkDataBuffer(), operator=(), and operator=().
FBulkDataBuffer() [2/4]
template<typename DataType> FBulkDataBuffer< DataType >::FBulkDataBuffer (const FBulkDataBuffer< DataType > & Other) inline
Copy constructor which will create it's own memory buffer and then copy from the source object rather than share access to the same buffer.
Parameters
Other The source array to copy.
Definition at line 30 of file BulkDataBuffer.h.
References FBulkDataBuffer(), and Other.
FBulkDataBuffer() [3/4]
template<typename DataType> FBulkDataBuffer< DataType >::FBulkDataBuffer (FBulkDataBuffer< DataType > && Other) inline
Move constructor.
Parameters
Other FBulkDataBuffer to move from.
Definition at line 40 of file BulkDataBuffer.h.
References FBulkDataBuffer(), Other, and View.
FBulkDataBuffer() [4/4]
template<typename DataType> FBulkDataBuffer< DataType >::FBulkDataBuffer (DataType * InBuffer, int64 InNumberOfElements) inline
Constructor.
Parameters
InBuffer Pointer to memory to take ownership of, must've have been allocated via FMemory::Malloc/Realloc.
InNumberOfElements The number of elements in the buffer.
Definition at line 50 of file BulkDataBuffer.h.
References View.
~FBulkDataBuffer()
template<typename DataType> FBulkDataBuffer< DataType >::~FBulkDataBuffer () inline
Destructor.
Definition at line 57 of file BulkDataBuffer.h.
References FreeBuffer().
Member Function Documentation
Empty()
template<typename DataType> void FBulkDataBuffer< DataType >::Empty () inline
Frees the internal buffer and sets the internal TArrayView to an empty state.
Definition at line 108 of file BulkDataBuffer.h.
References FreeBuffer(), and View.
FreeBuffer()
template<typename DataType> void FBulkDataBuffer< DataType >::FreeBuffer () inline private
Definition at line 140 of file BulkDataBuffer.h.
References FMemory::Free(), and View.
Referenced by ~FBulkDataBuffer(), Empty(), operator=(), operator=(), and Reset().
GetView()
template<typename DataType> const ViewType & FBulkDataBuffer< DataType >::GetView () const inline
Allows access to the data buffer owned by the object in the form of a TArrayView.
Returns
A valid TArrayView
Definition at line 133 of file BulkDataBuffer.h.
References View.
operator=() [1/2]
template<typename DataType> FBulkDataBuffer & FBulkDataBuffer< DataType >::operator= (const FBulkDataBuffer< DataType > & Other) inline
Assignment operator which will create it's own memory buffer and then copy from the source object rather than share access to the same buffer.
Parameters
Other The source FBulkDataBuffer to assign from.
Definition at line 69 of file BulkDataBuffer.h.
References FBulkDataBuffer(), FreeBuffer(), FMemory::Memcpy(), Other, and View.
operator=() [2/2]
template<typename DataType> FBulkDataBuffer & FBulkDataBuffer< DataType >::operator= (FBulkDataBuffer< DataType > && Other) inline
Move assignment operator.
Parameters
Other FBulkDataBuffer to assign and move from.
Definition at line 91 of file BulkDataBuffer.h.
References FBulkDataBuffer(), FreeBuffer(), Other, and View.
Reset()
template<typename DataType> void FBulkDataBuffer< DataType >::Reset (DataType * InBuffer, uint64 InNumberOfElements) inline
Frees any existing buffer and takes ownership of the buffer provided instead.
Parameters
InBuffer Pointer to memory to take ownership of, must've have been allocated via FMemory::Malloc/Realloc.
InNumberOfElements The number of elements in the buffer. buffers actual size if desired.
Definition at line 122 of file BulkDataBuffer.h.
References FreeBuffer(), and View.
Field Documentation
View
template<typename DataType> ViewType FBulkDataBuffer< DataType >::View private
Definition at line 148 of file BulkDataBuffer.h.
Referenced by FBulkDataBuffer(), FBulkDataBuffer(), Empty(), FreeBuffer(), GetView(), operator=(), operator=(), and Reset().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/BulkDataBuffer.h