Unreal Engine 5.6 C++ API: FVirtualStackAllocator Class Reference
FVirtualStackAllocator Class Reference
#include "VirtualStackAllocator.h"
Public Member Functions
FVirtualStackAllocator (size_t RequestedStackSize, EVirtualStackAllocatorDecommitMode Mode)
~FVirtualStackAllocator ()
void * Allocate (size_t Size, size_t Alignment)
FORCEINLINE FScopedStackAllocatorBookmark CreateScopedBookmark ()
size_t GetAllocatedBytes () const
size_t GetCommittedBytes () const
Private Member Functions
FVirtualStackAllocator ()
FVirtualStackAllocator (const FVirtualStackAllocator &Other)=delete
FVirtualStackAllocator (FVirtualStackAllocator &&Other)=delete
void DecommitUnusedPages ()
FORCEINLINE void Free (void *RestorePointer)
void operator= (const FVirtualStackAllocator &Other)=delete
void operator= (FVirtualStackAllocator &&Other)=delete
Private Attributes
EVirtualStackAllocatorDecommitMode DecommitMode = EVirtualStackAllocatorDecommitMode::AllOnDestruction
friend FScopedStackAllocatorBookmark
void * NextAllocationStart = nullptr
void * NextUncommittedPage = nullptr
const size_t PageSize
void * RecentHighWaterMark = nullptr
size_t TotalReservationSize
FPlatformMemory::FPlatformVirtualMemoryBlock VirtualMemory
Detailed Description
Definition at line 71 of file VirtualStackAllocator.h.
Constructor & Destructor Documentation
FVirtualStackAllocator() [1/4]
FVirtualStackAllocator::FVirtualStackAllocator (size_t RequestedStackSize, EVirtualStackAllocatorDecommitMode Mode)
Referenced by FVirtualStackAllocator(), FVirtualStackAllocator(), operator=(), and operator=().
~FVirtualStackAllocator()
FVirtualStackAllocator::~FVirtualStackAllocator ()
FVirtualStackAllocator() [2/4]
FVirtualStackAllocator::FVirtualStackAllocator (const FVirtualStackAllocator & Other) private delete
References FVirtualStackAllocator(), and Other.
FVirtualStackAllocator() [3/4]
FVirtualStackAllocator::FVirtualStackAllocator (FVirtualStackAllocator && Other) private delete
References FVirtualStackAllocator(), and Other.
FVirtualStackAllocator() [4/4]
FVirtualStackAllocator::FVirtualStackAllocator () private
Member Function Documentation
Allocate()
void * FVirtualStackAllocator::Allocate (size_t Size, size_t Alignment)
References TSequenceHistory< HistorySize >::Size.
CreateScopedBookmark()
FORCEINLINE FScopedStackAllocatorBookmark FVirtualStackAllocator::CreateScopedBookmark () inline
Definition at line 81 of file VirtualStackAllocator.h.
References FORCEINLINE, FScopedStackAllocatorBookmark, and NextAllocationStart.
DecommitUnusedPages()
void FVirtualStackAllocator::DecommitUnusedPages () private
Referenced by Free().
Free()
FORCEINLINE void FVirtualStackAllocator::Free (void * RestorePointer) inline private
Definition at line 109 of file VirtualStackAllocator.h.
References AllOnDestruction, ASAN_POISON_MEMORY_REGION, check, DecommitMode, DecommitUnusedPages(), FORCEINLINE, NextAllocationStart, UNLIKELY, and VirtualMemory.
GetAllocatedBytes()
size_t FVirtualStackAllocator::GetAllocatedBytes () const inline
Definition at line 89 of file VirtualStackAllocator.h.
References NextAllocationStart, and VirtualMemory.
GetCommittedBytes()
size_t FVirtualStackAllocator::GetCommittedBytes () const inline
Definition at line 94 of file VirtualStackAllocator.h.
References NextUncommittedPage, and VirtualMemory.
operator=() [1/2]
void FVirtualStackAllocator::operator= (const FVirtualStackAllocator & Other) private delete
References FVirtualStackAllocator(), and Other.
operator=() [2/2]
void FVirtualStackAllocator::operator= (FVirtualStackAllocator && Other) private delete
References FVirtualStackAllocator(), and Other.
Field Documentation
DecommitMode
EVirtualStackAllocatorDecommitMode FVirtualStackAllocator::DecommitMode = EVirtualStackAllocatorDecommitMode::AllOnDestruction private
Definition at line 140 of file VirtualStackAllocator.h.
Referenced by Free().
FScopedStackAllocatorBookmark
friend FVirtualStackAllocator::FScopedStackAllocatorBookmark private
Definition at line 105 of file VirtualStackAllocator.h.
Referenced by CreateScopedBookmark().
NextAllocationStart
void* FVirtualStackAllocator::NextAllocationStart = nullptr private
Definition at line 135 of file VirtualStackAllocator.h.
Referenced by CreateScopedBookmark(), Free(), and GetAllocatedBytes().
NextUncommittedPage
void* FVirtualStackAllocator::NextUncommittedPage = nullptr private
Definition at line 132 of file VirtualStackAllocator.h.
Referenced by GetCommittedBytes().
PageSize
const size_t FVirtualStackAllocator::PageSize private
Definition at line 138 of file VirtualStackAllocator.h.
RecentHighWaterMark
void* FVirtualStackAllocator::RecentHighWaterMark = nullptr private
Definition at line 133 of file VirtualStackAllocator.h.
TotalReservationSize
size_t FVirtualStackAllocator::TotalReservationSize private
Definition at line 137 of file VirtualStackAllocator.h.
VirtualMemory
FPlatformMemory::FPlatformVirtualMemoryBlock FVirtualStackAllocator::VirtualMemory private
Definition at line 131 of file VirtualStackAllocator.h.
Referenced by Free(), GetAllocatedBytes(), and GetCommittedBytes().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/VirtualStackAllocator.h