Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolColumnExtender Class Reference
UE::SequenceNavigator::FNavigationToolColumnExtender Class Reference
Extension Class to add Navigation Tool Columns.
#include "NavigationToolColumnExtender.h"
Public Member Functions
template<typename InColumnType, ENavigationToolExtensionPosition InExtensionPosition, typename InRefColumnType UE_REQUIRES>
void AddColumn ()
template<typename InColumnType UE_REQUIRES>
void AddColumn ()
SEQUENCENAVIGATOR_API void AddColumn (const TSharedPtr< FNavigationToolColumn > &InNewColumn, const ENavigationToolExtensionPosition InPosition=ENavigationToolExtensionPosition::After)
const TArray< TSharedPtr< FNavigationToolColumn > > & GetColumns () const
Private Member Functions
SEQUENCENAVIGATOR_API void AddColumn (const TSharedPtr< FNavigationToolColumn > &InColumn, const ENavigationToolExtensionPosition InExtensionPosition, const FName InReferenceColumnId)
int32 FindColumnIndex (const FName InColumnId) const
Private Attributes
TArray< TSharedPtr< FNavigationToolColumn > > Columns
Detailed Description
Extension Class to add Navigation Tool Columns.
Example #1: This would create a Tag Column at the end of the current column list (order matters!) ColumnExtender.AddColumn<FNavigationToolTagColumn>();
Example #2: This would create a Tag Column before the Label Column (if it doesn't exist, it's the same behavior as the above example) ColumnExtender.AddColumn<FNavigationToolTagColumn, ENavigationToolExtensionPosition::Before, FNavigationToolLabelColumn>();
Definition at line 24 of file NavigationToolColumnExtender.h.
Member Function Documentation
AddColumn() [1/4]
template<typename InColumnType, ENavigationToolExtensionPosition InExtensionPosition, typename InRefColumnType UE_REQUIRES> void UE::SequenceNavigator::FNavigationToolColumnExtender::AddColumn () inline
Definition at line 29 of file NavigationToolColumnExtender.h.
References AddColumn(), and MakeShared().
Referenced by AddColumn(), and AddColumn().
AddColumn() [2/4]
template<typename InColumnType UE_REQUIRES> void UE::SequenceNavigator::FNavigationToolColumnExtender::AddColumn () inline
Definition at line 36 of file NavigationToolColumnExtender.h.
References AddColumn(), Before, and MakeShared().
AddColumn() [3/4]
SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolColumnExtender::AddColumn (const TSharedPtr< FNavigationToolColumn > & InColumn, const ENavigationToolExtensionPosition InExtensionPosition, const FName InReferenceColumnId) private
AddColumn() [4/4]
SEQUENCENAVIGATOR_API void UE::SequenceNavigator::FNavigationToolColumnExtender::AddColumn (const TSharedPtr< FNavigationToolColumn > & InNewColumn, const ENavigationToolExtensionPosition InPosition = ENavigationToolExtensionPosition::After) inline
Definition at line 41 of file NavigationToolColumnExtender.h.
References AddColumn(), and After.
FindColumnIndex()
int32 UE::SequenceNavigator::FNavigationToolColumnExtender::FindColumnIndex (const FName InColumnId) const private
GetColumns()
const TArray< TSharedPtr< FNavigationToolColumn > > & UE::SequenceNavigator::FNavigationToolColumnExtender::GetColumns () const inline
Definition at line 47 of file NavigationToolColumnExtender.h.
References Columns.
Field Documentation
Columns
TArray<TSharedPtr<FNavigationToolColumn> > UE::SequenceNavigator::FNavigationToolColumnExtender::Columns private
Definition at line 56 of file NavigationToolColumnExtender.h.
Referenced by GetColumns().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/Columns/NavigationToolColumnExtender.h