Unreal Engine 5.6 C++ API: FSequencerKeyStructGenerator Class Reference
FSequencerKeyStructGenerator Class Reference
Struct type that is generated from an FMovieSceneChannel type to create a single edit interface for a key/value pair.
#include "SequencerKeyStructGenerator.h"
Public Member Functions
void AddGeneratedStruct (FName InstancedStructName, UMovieSceneKeyStructType *Struct)
Add the specified struct to this manager with the specified unique name, explicitly keeping it alive through AddReferencedObjects.
template<typename ChannelType>
TSharedPtr< FStructOnScope > CreateKeyStructInstance (const TMovieSceneChannelHandle< ChannelType > &ChannelHandle, FKeyHandle InHandle)
Create a new struct instance using the specified channel and key handles.
UMovieSceneKeyStructType * DefaultInstanceGeneratedStruct (UScriptStruct *ChannelType)
Create a new generated key struct by reflecting array properties with 'KeyTimes' and 'KeyValues' meta-data.
UMovieSceneKeyStructType * FindGeneratedStruct (FName InstancedStructName)
Attempt to locate an existing struct type with the specified name.
Static Public Member Functions
static UMovieSceneKeyStructType * AllocateNewKeyStruct ()
Allocate a brand new, empty key struct type.
static UMovieSceneKeyStructType * AllocateNewKeyStruct (UScriptStruct *ChannelType)
Allocate a brand new, key struct type, automatically discovering time/value properties from property meta-data.
static void FinalizeNewKeyStruct (UMovieSceneKeyStructType *InStruct)
Finalize the specified struct type by prepending a time property and linking the struct.
static FArrayProperty * FindArrayPropertyWithTag (UScriptStruct *ChannelStruct, FName MetaDataTag)
Helper function to locate an array property with the specified meta-data tag.
static FSequencerKeyStructGenerator & Get ()
Access the singlton instance of this class.
Private Member Functions
FSequencerKeyStructGenerator ()
~FSequencerKeyStructGenerator ()
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
FGCObject Interface.
TSharedPtr< FStructOnScope > CreateInitialStructInstance (const void *SourceChannel, UMovieSceneKeyStructType *GeneratedStructType, int32 InitialKeyIndex)
Create a new struct instance populated with the time and value for the specified key index, but no OnPropertyChangedEvent initialized.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
Private Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Static Private Member Functions
template<typename ChannelType>
static void CopyInstanceToKey (const TMovieSceneChannelHandle< ChannelType > &DestChannelHandle, FKeyHandle DestHandle, FStructOnScope *SourceInstance)
Applies reflected values from the key struct instance back into the channel, called on user-interaction with the edit instance.
Static Private Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Private Attributes
TMap< FName, TObjectPtr< UMovieSceneKeyStructType > > InstanceNameToGeneratedStruct
Mapping of instance name -> generated struct type for reference collection.
Additional Inherited Members
Private Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Private Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
Struct type that is generated from an FMovieSceneChannel type to create a single edit interface for a key/value pair.
Singleton class that is used to create, store and instantiate generated structs for editing single keys on channels
Definition at line 78 of file SequencerKeyStructGenerator.h.
Constructor & Destructor Documentation
FSequencerKeyStructGenerator()
FSequencerKeyStructGenerator::FSequencerKeyStructGenerator () inline private
Definition at line 158 of file SequencerKeyStructGenerator.h.
Referenced by Get().
~FSequencerKeyStructGenerator()
FSequencerKeyStructGenerator::~FSequencerKeyStructGenerator () inline private
Definition at line 159 of file SequencerKeyStructGenerator.h.
Member Function Documentation
AddGeneratedStruct()
void FSequencerKeyStructGenerator::AddGeneratedStruct (FName InstancedStructName, UMovieSceneKeyStructType * Struct)
Add the specified struct to this manager with the specified unique name, explicitly keeping it alive through AddReferencedObjects.
Parameters
InstancedStructName A unique name to associate with this struct, potentially for later retrieval. May include a specific property postfix such as an object or enum type for dynamic channels.
GeneratedStruct The generated struct to associate with the name
References Struct.
AddReferencedObjects()
virtual void FSequencerKeyStructGenerator::AddReferencedObjects (FReferenceCollector & Collector) override private virtual
FGCObject Interface.
Implements FGCObject.
AllocateNewKeyStruct() [1/2]
UMovieSceneKeyStructType * FSequencerKeyStructGenerator::AllocateNewKeyStruct () static
Allocate a brand new, empty key struct type.
Must be fully completed and finalized with FinalizeNewKeyStruct
AllocateNewKeyStruct() [2/2]
UMovieSceneKeyStructType * FSequencerKeyStructGenerator::AllocateNewKeyStruct (UScriptStruct * ChannelType) static
Allocate a brand new, key struct type, automatically discovering time/value properties from property meta-data.
Must be finalized with FinalizeNewKeyStruct
CopyInstanceToKey()
template<typename ChannelType> void FSequencerKeyStructGenerator::CopyInstanceToKey (const TMovieSceneChannelHandle< ChannelType > & DestChannelHandle, FKeyHandle DestHandle, FStructOnScope * SourceInstance) static private
Applies reflected values from the key struct instance back into the channel, called on user-interaction with the edit instance.
Definition at line 259 of file SequencerKeyStructGenerator.h.
References CastChecked(), TMovieSceneChannelHandle< ChannelType >::Get(), FScriptArrayHelper::GetRawPtr(), FStructOnScope::GetStruct(), FStructOnScope::GetStructMemory(), and INDEX_NONE.
Referenced by CreateKeyStructInstance().
CreateInitialStructInstance()
TSharedPtr< FStructOnScope > FSequencerKeyStructGenerator::CreateInitialStructInstance (const void * SourceChannel, UMovieSceneKeyStructType * GeneratedStructType, int32 InitialKeyIndex) private
Create a new struct instance populated with the time and value for the specified key index, but no OnPropertyChangedEvent initialized.
Referenced by CreateKeyStructInstance().
CreateKeyStructInstance()
template<typename ChannelType> TSharedPtr< FStructOnScope > FSequencerKeyStructGenerator::CreateKeyStructInstance (const TMovieSceneChannelHandle< ChannelType > & ChannelHandle, FKeyHandle InHandle)
Create a new struct instance using the specified channel and key handles.
Note
: Specific generation logic may be implemented by overloading the following free-function for your channel type: UMovieSceneKeyStructType* InstanceGeneratedStruct(ChannelType* Channel, FSequencerKeyStructGenerator* Generator)
Returns
An instance of a key struct for use on an edit UI, or nullptr if no valid one could be generated.
Definition at line 222 of file SequencerKeyStructGenerator.h.
References CopyInstanceToKey(), CreateInitialStructInstance(), DefaultInstanceGeneratedStruct(), TMovieSceneChannelHandle< ChannelType >::Get(), TSharedPtr< ObjectType, InMode >::Get(), INDEX_NONE, InstanceGeneratedStruct(), and PostConstructKeyInstance().
Referenced by DefaultInstanceGeneratedStruct(), and Sequencer::GetKeyStruct().
DefaultInstanceGeneratedStruct()
UMovieSceneKeyStructType * FSequencerKeyStructGenerator::DefaultInstanceGeneratedStruct (UScriptStruct * ChannelType)
Create a new generated key struct by reflecting array properties with 'KeyTimes' and 'KeyValues' meta-data.
Parameters
ChannelType The struct type of the channel (normally retrieved through StaticStruct())
Returns
A valid pointer to a UMovieSceneKeyStructType struct type, or nullptr if one could not be found or allocated
References CreateKeyStructInstance().
Referenced by CreateKeyStructInstance().
FinalizeNewKeyStruct()
void FSequencerKeyStructGenerator::FinalizeNewKeyStruct (UMovieSceneKeyStructType * InStruct) static
Finalize the specified struct type by prepending a time property and linking the struct.
FindArrayPropertyWithTag()
FArrayProperty * FSequencerKeyStructGenerator::FindArrayPropertyWithTag (UScriptStruct * ChannelStruct, FName MetaDataTag) static
Helper function to locate an array property with the specified meta-data tag.
FindGeneratedStruct()
UMovieSceneKeyStructType * FSequencerKeyStructGenerator::FindGeneratedStruct (FName InstancedStructName)
Attempt to locate an existing struct type with the specified name.
Parameters
InstancedStructName The unique name to look for
Returns
A generated struct that was added with the specified name, or nullptr if one does not exist.
Get()
FSequencerKeyStructGenerator & FSequencerKeyStructGenerator::Get () static
Access the singlton instance of this class.
References FSequencerKeyStructGenerator().
Referenced by Sequencer::GetKeyStruct().
GetReferencerName()
virtual FString FSequencerKeyStructGenerator::GetReferencerName () const inline override private virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 170 of file SequencerKeyStructGenerator.h.
References TEXT.
Field Documentation
InstanceNameToGeneratedStruct
TMap<FName, TObjectPtr<UMovieSceneKeyStructType> > FSequencerKeyStructGenerator::InstanceNameToGeneratedStruct private
Mapping of instance name -> generated struct type for reference collection.
Definition at line 156 of file SequencerKeyStructGenerator.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/SequencerKeyStructGenerator.h