Unreal Engine 5.6 C++ API: FLoaderAdapterPinnedActors Class Reference
FLoaderAdapterPinnedActors Class Reference
#include "LoaderAdapterPinnedActors.h"
Public Member Functions
FLoaderAdapterPinnedActors (UWorld *InWorld)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance version instead") static bool SupportsPinning(FWorldPartitionActorDesc *InActorDesc)
Public Member Functions inherited from FLoaderAdapterActorList
FLoaderAdapterActorList (UWorld *InWorld)
void AddActors (const TArray< FGuid > &ActorGuids)
void AddActors (const TArray< FWorldPartitionHandle > &ActorHandles)
bool ContainsActor (const FGuid &ActorGuid) const
bool ContainsActor (const FWorldPartitionHandle &ActorHandle) const
void RemoveActors (const TArray< FGuid > &ActorGuids)
void RemoveActors (const TArray< FWorldPartitionHandle > &ActorHandles)
Public Member Functions inherited from FLoaderAdapterList
FLoaderAdapterList (UWorld *InWorld)
virtual ~FLoaderAdapterList ()
const TSet< FWorldPartitionHandle > & GetActors () const
Public Member Functions inherited from IWorldPartitionActorLoaderInterface::ILoaderAdapter
ILoaderAdapter (UWorld *InWorld)
virtual ~ILoaderAdapter ()
virtual TOptional< FBox > GetBoundingBox () const
virtual TOptional< FColor > GetColor () const
virtual TOptional< FString > GetLabel () const
bool GetUserCreated () const
UWorld * GetWorld () const
bool IsLoaded () const
void Load ()
void SetUserCreated (bool bValue)
UE_DEPRECATED (5.4, "Use OnActorDescContainerInstanceInitialize") void OnActorDescContainerInitialize(UActorDescContainer *Container)
UE_DEPRECATED (5.4, "Use OnActorDescContainerInstanceUninitialize") void OnActorDescContainerUninitialize(UActorDescContainer *Container)
void Unload ()
Static Public Member Functions
static bool SupportsPinning (AActor *InActor)
static bool SupportsPinning (FWorldPartitionActorDescInstance *InActorDescInstance)
Protected Member Functions
virtual bool PassActorDescFilter (const FWorldPartitionHandle &ActorHandle) const override
Protected Member Functions inherited from FLoaderAdapterList
virtual void ForEachActor (TFunctionRef< void(const FWorldPartitionHandle &)> InOperation) const override
Protected Member Functions inherited from IWorldPartitionActorLoaderInterface::ILoaderAdapter
void AddReferenceToActor (FWorldPartitionHandle &Actor)
FActorReferenceMap & GetContainerReferences (UActorDescContainerInstance *InContainerInstance)
const FActorReferenceMap * GetContainerReferencesConst (UActorDescContainerInstance *InContainerInstance) const
UWorldPartition * GetLoadedChildWorldPartition (const FWorldPartitionHandle &Handle) const
void OnActorDescContainerInstanceInitialize (UActorDescContainerInstance *ContainerInstance)
void OnActorDescContainerInstanceUninitialize (UActorDescContainerInstance *ContainerInstance)
void OnRefreshLoadedState (bool bFromUserOperation)
void PostLoadedStateChanged (int32 NumLoads, int32 NumUnloads, bool bClearTransactions)
void RefreshLoadedState ()
void RegisterDelegates ()
void RemoveReferenceToActor (FWorldPartitionHandle &Actor)
bool ShouldActorBeLoaded (const FWorldPartitionHandle &Actor) const
void UnregisterDelegates ()
Additional Inherited Members
Protected Attributes inherited from FLoaderAdapterActorList
TSet< FWorldPartitionHandle > ActorsToRemove
Protected Attributes inherited from FLoaderAdapterList
TSet< FWorldPartitionHandle > Actors
Detailed Description
Definition at line 12 of file LoaderAdapterPinnedActors.h.
Constructor & Destructor Documentation
FLoaderAdapterPinnedActors()
FLoaderAdapterPinnedActors::FLoaderAdapterPinnedActors (UWorld * InWorld) inline
Definition at line 15 of file LoaderAdapterPinnedActors.h.
References FLoaderAdapterActorList::FLoaderAdapterActorList().
Member Function Documentation
PassActorDescFilter()
virtual bool FLoaderAdapterPinnedActors::PassActorDescFilter (const FWorldPartitionHandle & ActorHandle) const override protected virtual
Reimplemented from FLoaderAdapterActorList.
SupportsPinning() [1/2]
bool FLoaderAdapterPinnedActors::SupportsPinning (AActor * InActor) static
SupportsPinning() [2/2]
bool FLoaderAdapterPinnedActors::SupportsPinning (FWorldPartitionActorDescInstance * InActorDescInstance) static
Referenced by UE_DEPRECATED().
UE_DEPRECATED()
FLoaderAdapterPinnedActors::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance version instead") inline
Definition at line 19 of file LoaderAdapterPinnedActors.h.
References SupportsPinning().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/LoaderAdapter/LoaderAdapterPinnedActors.h