Unreal Engine 5.6 C++ API: TSoftClassPtr< TClass > Class Template Reference
TSoftClassPtr< TClass > Class Template Reference
TSoftClassPtr is a templatized wrapper around FSoftObjectPtr that works like a TSubclassOf, it can be used in UProperties for blueprint subclasses.
#include "SoftObjectPtr.h"
Public Types
using ElementType = TClass
Public Member Functions
FORCEINLINE TSoftClassPtr ()=default
FORCEINLINE TSoftClassPtr (const FSoftObjectPath &ObjectPath)
Construct from a soft object path.
FORCEINLINE TSoftClassPtr (const TSoftClassPtr &Other)=default
template<class TClassA UE_REQUIRES>
FORCEINLINE TSoftClassPtr (const TSoftClassPtr< TClassA > &Other)
Construct from another soft pointer.
FORCEINLINE TSoftClassPtr (const UClass *From)
Construct from a class already in memory.
FORCEINLINE TSoftClassPtr (TSoftClassPtr &&Other)=default
FORCEINLINE ~TSoftClassPtr ()=default
FORCEINLINE UClass * Get () const
Dereference the soft pointer.
FORCEINLINE FString GetAssetName () const
Returns assetname string, leaving off the /package/path part.
FORCEINLINE FName GetLongPackageFName () const
Returns /package/path name, leaving off the asset name.
FORCEINLINE FString GetLongPackageName () const
Returns /package/path string, leaving off the asset name.
FORCEINLINE uint32 GetPtrTypeHash () const
Hash function.
FORCEINLINE const FSoftObjectPath & GetUniqueID () const
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
int32 LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams=FLoadAssetAsyncOptionalParams()) const
Attempts to asynchronously load the object referenced by this soft pointer.
UClass * LoadSynchronous () const
Synchronously load (if necessary) and return the asset object represented by this asset ptr.
FORCEINLINE operator bool () const
Dereference soft pointer to see if it points somewhere valid.
FORCEINLINE bool operator!= (const TSoftClassPtr &Rhs) const
Compare soft pointers for inequality Caution: Two soft pointers might not be equal to each other, but they both might return nullptr.
FORCEINLINE UClass & operator* () const
Dereference the soft pointer.
FORCEINLINE UClass * operator-> () const
Dereference the soft pointer.
FORCEINLINE void operator= (const FSoftObjectPath &ObjectPath)
Copy from a soft object path.
FORCEINLINE TSoftClassPtr & operator= (const TSoftClassPtr &Other)=default
template<class TClassA UE_REQUIRES>
FORCEINLINE TSoftClassPtr & operator= (const TSoftObjectPtr< TClassA > &Other)
Copy from another soft pointer.
template<class TClassA UE_REQUIRES>
FORCEINLINE TSoftClassPtr & operator= (const TWeakObjectPtr< TClassA > &Other)
Copy from a weak pointer already in memory.
FORCEINLINE void operator= (const UClass *From)
Copy from a class already in memory.
FORCEINLINE TSoftClassPtr & operator= (TSoftClassPtr &&Other)=default
FORCEINLINE bool operator== (const TSoftClassPtr &Rhs) const
Compare soft pointers for equality Caution: Two soft pointers might not be equal to each other, but they both might return nullptr.
FORCEINLINE void Reset ()
Reset the soft pointer back to the null state.
FORCEINLINE void ResetWeakPtr ()
Resets the weak ptr only, call this when ObjectId may change.
void Serialize (FArchive &Ar)
FORCEINLINE const FSoftObjectPath & ToSoftObjectPath () const
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
FORCEINLINE FString ToString () const
Returns string representation of reference, in form /package/path.assetname.
Private Attributes
FSoftObjectPtr SoftObjectPtr
Friends
template<class TClassA>
class TSoftClassPtr
Detailed Description
template<class TClass = UObject>
class TSoftClassPtr< TClass >
TSoftClassPtr is a templatized wrapper around FSoftObjectPtr that works like a TSubclassOf, it can be used in UProperties for blueprint subclasses.
Definition at line 762 of file SoftObjectPtr.h.
Member Typedef Documentation
ElementType
template<class TClass = UObject> using TSoftClassPtr< TClass >::ElementType = TClass
Definition at line 768 of file SoftObjectPtr.h.
Constructor & Destructor Documentation
TSoftClassPtr() [1/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::TSoftClassPtr () nodiscard default
TSoftClassPtr() [2/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::TSoftClassPtr (const TSoftClassPtr< TClass > & Other) nodiscard default
TSoftClassPtr() [3/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::TSoftClassPtr (TSoftClassPtr< TClass > && Other) nodiscard default
~TSoftClassPtr()
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::~TSoftClassPtr () default
TSoftClassPtr() [4/6]
template<class TClass = UObject> template<class TClassA UE_REQUIRES> FORCEINLINE TSoftClassPtr< TClass >::TSoftClassPtr (const TSoftClassPtr< TClassA > & Other) inline nodiscard
Construct from another soft pointer.
Definition at line 782 of file SoftObjectPtr.h.
TSoftClassPtr() [5/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::TSoftClassPtr (const UClass * From) inline nodiscard
Construct from a class already in memory.
Definition at line 788 of file SoftObjectPtr.h.
TSoftClassPtr() [6/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::TSoftClassPtr (const FSoftObjectPath & ObjectPath) inline explicit nodiscard
Construct from a soft object path.
Definition at line 794 of file SoftObjectPtr.h.
Member Function Documentation
Get()
template<class TClass = UObject> FORCEINLINE UClass * TSoftClassPtr< TClass >::Get () const inline nodiscard
Dereference the soft pointer.
Returns
nullptr if this object is gone or the soft pointer was null, otherwise a valid UClass pointer
Definition at line 873 of file SoftObjectPtr.h.
Referenced by TSoftClassPtr< const T >::IsValid(), TSoftClassPtr< const T >::operator*(), and TSoftClassPtr< const T >::operator->().
GetAssetName()
template<class TClass = UObject> FORCEINLINE FString TSoftClassPtr< TClass >::GetAssetName () const inline nodiscard
Returns assetname string, leaving off the /package/path part.
Definition at line 957 of file SoftObjectPtr.h.
GetLongPackageFName()
template<class TClass = UObject> FORCEINLINE FName TSoftClassPtr< TClass >::GetLongPackageFName () const inline nodiscard
Returns /package/path name, leaving off the asset name.
Definition at line 951 of file SoftObjectPtr.h.
GetLongPackageName()
template<class TClass = UObject> FORCEINLINE FString TSoftClassPtr< TClass >::GetLongPackageName () const inline nodiscard
Returns /package/path string, leaving off the asset name.
Definition at line 945 of file SoftObjectPtr.h.
GetPtrTypeHash()
template<class TClass = UObject> FORCEINLINE uint32 TSoftClassPtr< TClass >::GetPtrTypeHash () const inline nodiscard
Hash function.
Definition at line 969 of file SoftObjectPtr.h.
Referenced by GetTypeHash().
GetUniqueID()
template<class TClass = UObject> FORCEINLINE const FSoftObjectPath & TSoftClassPtr< TClass >::GetUniqueID () const inline nodiscard
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
Definition at line 927 of file SoftObjectPtr.h.
IsNull()
template<class TClass = UObject> FORCEINLINE bool TSoftClassPtr< TClass >::IsNull () const inline nodiscard
Test if this can never point to a live UObject.
Returns
true if this is explicitly pointing to no object
Definition at line 921 of file SoftObjectPtr.h.
IsPending()
template<class TClass = UObject> FORCEINLINE bool TSoftClassPtr< TClass >::IsPending () const inline nodiscard
Test if this does not point to a live UObject, but may in the future.
Returns
true if this does not point to a real object, but could possibly
Definition at line 911 of file SoftObjectPtr.h.
IsValid()
template<class TClass = UObject> FORCEINLINE bool TSoftClassPtr< TClass >::IsValid () const inline nodiscard
Test if this points to a live UObject.
Returns
true if Get() would return a valid non-null pointer
Definition at line 900 of file SoftObjectPtr.h.
Referenced by TSoftClassPtr< const T >::operator bool().
LoadAsync()
template<class TClass = UObject> int32 TSoftClassPtr< TClass >::LoadAsync (FLoadSoftObjectPathAsyncDelegate InCompletionDelegate, FLoadAssetAsyncOptionalParams InOptionalParams = FLoadAssetAsyncOptionalParams()) const inline
Attempts to asynchronously load the object referenced by this soft pointer.
This is a wrapper around the LoadAsync function in SoftObjectPath, and the delegate is responsible for validating it loaded the correct type
Parameters
InCompletionDelegate Delegate to be invoked when the async load finishes, this will execute on the game thread as soon as the load succeeds or fails
InOptionalParams Optional parameters for async loading the asset
Returns
Unique ID associated with this load request (the same object or package can be associated with multiple IDs).
Definition at line 994 of file SoftObjectPtr.h.
LoadSynchronous()
template<class TClass = UObject> UClass * TSoftClassPtr< TClass >::LoadSynchronous () const inline
Synchronously load (if necessary) and return the asset object represented by this asset ptr.
Definition at line 975 of file SoftObjectPtr.h.
operator bool()
template<class TClass = UObject> FORCEINLINE TSoftClassPtr< TClass >::operator bool () const inline explicit nodiscard
Dereference soft pointer to see if it points somewhere valid.
Definition at line 963 of file SoftObjectPtr.h.
operator!=()
template<class TClass = UObject> FORCEINLINE bool TSoftClassPtr< TClass >::operator!= (const TSoftClassPtr< TClass > & Rhs) const inline nodiscard
Compare soft pointers for inequality Caution: Two soft pointers might not be equal to each other, but they both might return nullptr.
Parameters
Other soft pointer to compare to
Definition at line 862 of file SoftObjectPtr.h.
operator*()
template<class TClass = UObject> FORCEINLINE UClass & TSoftClassPtr< TClass >::operator* () const inline nodiscard
Dereference the soft pointer.
Definition at line 884 of file SoftObjectPtr.h.
operator->()
template<class TClass = UObject> FORCEINLINE UClass * TSoftClassPtr< TClass >::operator-> () const inline nodiscard
Dereference the soft pointer.
Definition at line 890 of file SoftObjectPtr.h.
operator=() [1/6]
template<class TClass = UObject> FORCEINLINE void TSoftClassPtr< TClass >::operator= (const FSoftObjectPath & ObjectPath) inline
Copy from a soft object path.
Definition at line 818 of file SoftObjectPtr.h.
operator=() [2/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr & TSoftClassPtr< TClass >::operator= (const TSoftClassPtr< TClass > & Other) default
operator=() [3/6]
template<class TClass = UObject> template<class TClassA UE_REQUIRES> FORCEINLINE TSoftClassPtr & TSoftClassPtr< TClass >::operator= (const TSoftObjectPtr< TClassA > & Other) inline
Copy from another soft pointer.
Definition at line 839 of file SoftObjectPtr.h.
operator=() [4/6]
template<class TClass = UObject> template<class TClassA UE_REQUIRES> FORCEINLINE TSoftClassPtr & TSoftClassPtr< TClass >::operator= (const TWeakObjectPtr< TClassA > & Other) inline
Copy from a weak pointer already in memory.
Definition at line 828 of file SoftObjectPtr.h.
operator=() [5/6]
template<class TClass = UObject> FORCEINLINE void TSoftClassPtr< TClass >::operator= (const UClass * From) inline
Copy from a class already in memory.
Definition at line 812 of file SoftObjectPtr.h.
operator=() [6/6]
template<class TClass = UObject> FORCEINLINE TSoftClassPtr & TSoftClassPtr< TClass >::operator= (TSoftClassPtr< TClass > && Other) default
operator==()
template<class TClass = UObject> FORCEINLINE bool TSoftClassPtr< TClass >::operator== (const TSoftClassPtr< TClass > & Rhs) const inline nodiscard
Compare soft pointers for equality Caution: Two soft pointers might not be equal to each other, but they both might return nullptr.
Parameters
Other soft pointer to compare to
Definition at line 851 of file SoftObjectPtr.h.
Reset()
template<class TClass = UObject> FORCEINLINE void TSoftClassPtr< TClass >::Reset () inline
Reset the soft pointer back to the null state.
Definition at line 800 of file SoftObjectPtr.h.
ResetWeakPtr()
template<class TClass = UObject> FORCEINLINE void TSoftClassPtr< TClass >::ResetWeakPtr () inline
Resets the weak ptr only, call this when ObjectId may change.
Definition at line 806 of file SoftObjectPtr.h.
Serialize()
template<class TClass = UObject> void TSoftClassPtr< TClass >::Serialize (FArchive & Ar) inline
Definition at line 999 of file SoftObjectPtr.h.
Referenced by operator<<().
ToSoftObjectPath()
template<class TClass = UObject> FORCEINLINE const FSoftObjectPath & TSoftClassPtr< TClass >::ToSoftObjectPath () const inline nodiscard
Returns the StringObjectPath that is wrapped by this SoftObjectPtr.
Definition at line 933 of file SoftObjectPtr.h.
Referenced by TSoftClassPtr< const T >::GetAssetName(), TSoftClassPtr< const T >::GetLongPackageFName(), TSoftClassPtr< const T >::GetLongPackageName(), and TSoftClassPtr< const T >::ToString().
ToString()
template<class TClass = UObject> FORCEINLINE FString TSoftClassPtr< TClass >::ToString () const inline nodiscard
Returns string representation of reference, in form /package/path.assetname.
Definition at line 939 of file SoftObjectPtr.h.
Friends And Related Symbol Documentation
TSoftClassPtr
template<class TClass = UObject> template<class TClassA> friend class TSoftClassPtr friend
Definition at line 765 of file SoftObjectPtr.h.
Field Documentation
SoftObjectPtr
template<class TClass = UObject> FSoftObjectPtr TSoftClassPtr< TClass >::SoftObjectPtr private
Definition at line 1005 of file SoftObjectPtr.h.
Referenced by TSoftClassPtr< const T >::operator!=(), and TSoftClassPtr< const T >::operator==().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/SoftObjectPtr.h