Unreal Engine 5.6 C++ API: TPropertyTypeFundamentals< InTCppType > Class Template Reference
TPropertyTypeFundamentals< InTCppType > Class Template Reference
#include "UnrealType.h"
Public Types
enum { CPPSize = sizeof(TCppType) , CPPAlignment = alignof(TCppType) }
typedef InTCppType TCppType
Type of the CPP property.
Static Public Member Functions
static FORCEINLINE void ClearIntrusiveOptionalValue (void *A)
static FORCEINLINE void DestroyPropertyValue (void *A)
Destroy the value of a property at an address.
static FORCEINLINE TCppType GetDefaultPropertyValue ()
Get the default value of the cpp type, just the default constructor, which works even for things like in32.
static FORCEINLINE TCppType GetOptionalPropertyValue (void const *B)
Get the value of the property from an address, unless it is NULL, then return the default value.
static FORCEINLINE TCppType const & GetPropertyValue (void const *A)
Get the value of the property from an address.
static FORCEINLINE TCppType * GetPropertyValuePtr (void *A)
Convert the address of a value of the property to the proper type.
static FORCEINLINE TCppType const * GetPropertyValuePtr (void const *A)
Convert the address of a value of the property to the proper type.
static FORCEINLINE TCHAR const * GetTypeName ()
static FORCEINLINE bool HasIntrusiveUnsetOptionalState ()
static FORCEINLINE void InitializeIntrusiveUnsetOptionalValue (void *Data)
static FORCEINLINE TCppType * InitializePropertyValue (void *A)
Initialize the value of a property at an address, this assumes over uninitialized memory.
static FORCEINLINE bool IsIntrusiveOptionalValueSet (const void *A)
static FORCEINLINE void SetPropertyValue (void *A, TCppType const &Value)
Set the value of a property at an address.
Static Protected Member Functions
static FORCEINLINE EPropertyFlags GetComputedFlagsPropertyFlags ()
Get the property flags corresponding to this C++ type, from the C++ type traits system.
Detailed Description
template<typename InTCppType>
class TPropertyTypeFundamentals< InTCppType >
Definition at line 1388 of file UnrealType.h.
Member Typedef Documentation
TCppType
template<typename InTCppType> typedef InTCppType TPropertyTypeFundamentals< InTCppType >::TCppType
Type of the CPP property.
Definition at line 1392 of file UnrealType.h.
Member Enumeration Documentation
anonymous enum
template<typename InTCppType> anonymous enum
Enumerator
CPPSize
CPPAlignment
Definition at line 1393 of file UnrealType.h.
Member Function Documentation
ClearIntrusiveOptionalValue()
template<typename InTCppType> FORCEINLINE void TPropertyTypeFundamentals< InTCppType >::ClearIntrusiveOptionalValue (void * A) inline static
Definition at line 1460 of file UnrealType.h.
References A, FORCEINLINE, and Reset.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::ClearIntrusiveOptionalValue().
DestroyPropertyValue()
template<typename InTCppType> FORCEINLINE void TPropertyTypeFundamentals< InTCppType >::DestroyPropertyValue (void * A) inline static
Destroy the value of a property at an address.
Definition at line 1440 of file UnrealType.h.
References A, FORCEINLINE, and GetPropertyValuePtr().
Referenced by TProperty< InTCppType, FObjectPropertyBase >::DestroyValueInternal().
GetComputedFlagsPropertyFlags()
template<typename InTCppType> FORCEINLINE EPropertyFlags TPropertyTypeFundamentals< InTCppType >::GetComputedFlagsPropertyFlags () inline static protected
Get the property flags corresponding to this C++ type, from the C++ type traits system.
Definition at line 1467 of file UnrealType.h.
References FORCEINLINE, TModels_V, TIsPODType< T >::Value, and TIsZeroConstructType< T >::Value.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::TProperty(), and TProperty< InTCppType, FObjectPropertyBase >::LinkInternal().
GetDefaultPropertyValue()
template<typename InTCppType> FORCEINLINE TCppType TPropertyTypeFundamentals< InTCppType >::GetDefaultPropertyValue () inline static
Get the default value of the cpp type, just the default constructor, which works even for things like in32.
Definition at line 1420 of file UnrealType.h.
References FORCEINLINE.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::ClearValueInternal(), GetOptionalPropertyValue(), TProperty< InTCppType, FObjectPropertyBase >::GetOptionalPropertyValue_InContainer(), and TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >::Identical().
GetOptionalPropertyValue()
template<typename InTCppType> FORCEINLINE TCppType TPropertyTypeFundamentals< InTCppType >::GetOptionalPropertyValue (void const * B) inline static
Get the value of the property from an address, unless it is NULL, then return the default value.
Definition at line 1425 of file UnrealType.h.
References B, FORCEINLINE, GetDefaultPropertyValue(), and GetPropertyValue().
GetPropertyValue()
template<typename InTCppType> FORCEINLINE TCppType const & TPropertyTypeFundamentals< InTCppType >::GetPropertyValue (void const * A) inline static
Get the value of the property from an address.
Definition at line 1415 of file UnrealType.h.
References A, FORCEINLINE, and GetPropertyValuePtr().
Referenced by TProperty_Numeric< InTCppType >::GetFloatingPointPropertyValue(), TProperty_Numeric< InTCppType >::GetNumericPropertyValueToString(), GetOptionalPropertyValue(), TProperty_Numeric< InTCppType >::GetSignedIntPropertyValue(), TProperty_Numeric< InTCppType >::GetUnsignedIntPropertyValue(), and TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >::Identical().
GetPropertyValuePtr() [1/2]
template<typename InTCppType> FORCEINLINE TCppType * TPropertyTypeFundamentals< InTCppType >::GetPropertyValuePtr (void * A) inline static
Convert the address of a value of the property to the proper type.
Definition at line 1410 of file UnrealType.h.
References A, and FORCEINLINE.
GetPropertyValuePtr() [2/2]
template<typename InTCppType> FORCEINLINE TCppType const * TPropertyTypeFundamentals< InTCppType >::GetPropertyValuePtr (void const * A) inline static
Convert the address of a value of the property to the proper type.
Definition at line 1405 of file UnrealType.h.
References A, and FORCEINLINE.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::CopyValuesInternal(), DestroyPropertyValue(), GetPropertyValue(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValuePtr_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValuePtr_InContainer(), TProperty_WithEqualityAndSerializer< InTCppType, FNumericProperty >::SerializeItem(), TProperty_Numeric< InTCppType >::SetNumericPropertyValueFromString(), and SetPropertyValue().
GetTypeName()
template<typename InTCppType> FORCEINLINE TCHAR const * TPropertyTypeFundamentals< InTCppType >::GetTypeName () inline static
Definition at line 1399 of file UnrealType.h.
References FORCEINLINE, and TNameOf< T >::GetName().
Referenced by TProperty< InTCppType, FObjectPropertyBase >::GetCPPType().
HasIntrusiveUnsetOptionalState()
template<typename InTCppType> FORCEINLINE bool TPropertyTypeFundamentals< InTCppType >::HasIntrusiveUnsetOptionalState () inline static
Definition at line 1445 of file UnrealType.h.
References FORCEINLINE.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::HasIntrusiveUnsetOptionalState().
InitializeIntrusiveUnsetOptionalValue()
template<typename InTCppType> FORCEINLINE void TPropertyTypeFundamentals< InTCppType >::InitializeIntrusiveUnsetOptionalValue (void * Data) inline static
Definition at line 1450 of file UnrealType.h.
References FORCEINLINE.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::InitializeIntrusiveUnsetOptionalValue().
InitializePropertyValue()
template<typename InTCppType> FORCEINLINE TCppType * TPropertyTypeFundamentals< InTCppType >::InitializePropertyValue (void * A) inline static
Initialize the value of a property at an address, this assumes over uninitialized memory.
Definition at line 1435 of file UnrealType.h.
References A, and FORCEINLINE.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::InitializeValueInternal().
IsIntrusiveOptionalValueSet()
template<typename InTCppType> FORCEINLINE bool TPropertyTypeFundamentals< InTCppType >::IsIntrusiveOptionalValueSet (const void * A) inline static
Definition at line 1455 of file UnrealType.h.
References A, and FORCEINLINE.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::IsIntrusiveOptionalValueSet().
SetPropertyValue()
template<typename InTCppType> FORCEINLINE void TPropertyTypeFundamentals< InTCppType >::SetPropertyValue (void * A, TCppType const & Value) inline static
Set the value of a property at an address.
Definition at line 1430 of file UnrealType.h.
References A, FORCEINLINE, GetPropertyValuePtr(), and Value.
Referenced by TProperty< InTCppType, FObjectPropertyBase >::ClearValueInternal(), TProperty_Numeric< InTCppType >::SetFloatingPointPropertyValue(), TProperty_Numeric< InTCppType >::SetIntPropertyValue(), and TProperty_Numeric< InTCppType >::SetIntPropertyValue().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h