Unreal Engine 5.6 C++ API: FAsyncTaskNotification Class Reference
FAsyncTaskNotification Class Reference
Provides notifications for an on-going asynchronous task.
#include "AsyncTaskNotification.h"
Public Member Functions
FAsyncTaskNotification (const FAsyncTaskNotification &)=delete
Non-copyable.
FAsyncTaskNotification (const FAsyncTaskNotificationConfig &InConfig)
Create an asynchronous task notification.
FAsyncTaskNotification (FAsyncTaskNotification &&InOther)
Movable.
~FAsyncTaskNotification ()
Destroy the asynchronous task notification.
EAsyncTaskNotificationPromptAction GetPromptAction () const
Return the notification prompt action.
FAsyncTaskNotification & operator= (const FAsyncTaskNotification &)=delete
FAsyncTaskNotification & operator= (FAsyncTaskNotification &&InOther)
void SetCanCancel (const TAttribute< bool > &InCanCancel)
Set whether this task be canceled.
void SetComplete (const bool bSuccess=true)
Set the task as complete.
void SetComplete (const FText &InTitleText, const FText &InProgressText, const bool bSuccess=true)
Update the text and set the task as complete.
void SetHyperlink (const FSimpleDelegate &InHyperlink, const FText &InHyperlinkText=FText())
Set the Hyperlink for this notification.
void SetKeepOpenOnFailure (const TAttribute< bool > &InKeepOpenOnFailure)
Set whether to keep this notification open on failure.
void SetKeepOpenOnSuccess (const TAttribute< bool > &InKeepOpenOnSuccess)
Set whether to keep this notification open on success.
void SetNotificationState (const FAsyncNotificationStateData &InState)
Set the notification state.
void SetProgressText (const FText &InProgressText)
Set the progress text of this notification.
void SetPromptText (const FText &InPromptText)
Set the prompt text of this notification, if needed.
void SetTitleText (const FText &InTitleText, const bool bClearProgressText=true)
Set the title text of this notification.
Private Attributes
TSharedPtr< IAsyncTaskNotificationImpl > NotificationImpl
Pointer to the real notification implementation.
Detailed Description
Provides notifications for an on-going asynchronous task.
Definition at line 113 of file AsyncTaskNotification.h.
Constructor & Destructor Documentation
FAsyncTaskNotification() [1/3]
FAsyncTaskNotification::FAsyncTaskNotification (const FAsyncTaskNotificationConfig & InConfig)
Create an asynchronous task notification.
Referenced by FAsyncTaskNotification(), FAsyncTaskNotification(), operator=(), and operator=().
~FAsyncTaskNotification()
FAsyncTaskNotification::~FAsyncTaskNotification ()
Destroy the asynchronous task notification.
FAsyncTaskNotification() [2/3]
FAsyncTaskNotification::FAsyncTaskNotification (const FAsyncTaskNotification &) delete
Non-copyable.
References FAsyncTaskNotification().
FAsyncTaskNotification() [3/3]
FAsyncTaskNotification::FAsyncTaskNotification (FAsyncTaskNotification && InOther)
Movable.
References FAsyncTaskNotification().
Member Function Documentation
GetPromptAction()
EAsyncTaskNotificationPromptAction FAsyncTaskNotification::GetPromptAction () const
Return the notification prompt action.
The action resets to None when the notification state changes.
operator=() [1/2]
FAsyncTaskNotification & FAsyncTaskNotification::operator= (const FAsyncTaskNotification &) delete
References FAsyncTaskNotification().
operator=() [2/2]
FAsyncTaskNotification & FAsyncTaskNotification::operator= (FAsyncTaskNotification && InOther)
References FAsyncTaskNotification().
SetCanCancel()
void FAsyncTaskNotification::SetCanCancel (const TAttribute< bool > & InCanCancel)
Set whether this task be canceled.
SetComplete() [1/2]
void FAsyncTaskNotification::SetComplete (const bool bSuccess = true)
Set the task as complete.
SetComplete() [2/2]
void FAsyncTaskNotification::SetComplete (const FText & InTitleText, const FText & InProgressText, const bool bSuccess = true)
Update the text and set the task as complete.
SetHyperlink()
void FAsyncTaskNotification::SetHyperlink (const FSimpleDelegate & InHyperlink, const FText & InHyperlinkText = FText())
Set the Hyperlink for this notification.
SetKeepOpenOnFailure()
void FAsyncTaskNotification::SetKeepOpenOnFailure (const TAttribute< bool > & InKeepOpenOnFailure)
Set whether to keep this notification open on failure.
SetKeepOpenOnSuccess()
void FAsyncTaskNotification::SetKeepOpenOnSuccess (const TAttribute< bool > & InKeepOpenOnSuccess)
Set whether to keep this notification open on success.
SetNotificationState()
void FAsyncTaskNotification::SetNotificationState (const FAsyncNotificationStateData & InState)
Set the notification state.
Provide finer control than SetComplete by setting every field of the state.
SetProgressText()
void FAsyncTaskNotification::SetProgressText (const FText & InProgressText)
Set the progress text of this notification.
SetPromptText()
void FAsyncTaskNotification::SetPromptText (const FText & InPromptText)
Set the prompt text of this notification, if needed.
SetTitleText()
void FAsyncTaskNotification::SetTitleText (const FText & InTitleText, const bool bClearProgressText = true)
Set the title text of this notification.
Field Documentation
NotificationImpl
TSharedPtr<IAsyncTaskNotificationImpl> FAsyncTaskNotification::NotificationImpl private
Pointer to the real notification implementation.
Definition at line 196 of file AsyncTaskNotification.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/AsyncTaskNotification.h