Unreal Engine 5.6 C++ API: FAudioSpectrumPlotScaleInfo Class Reference
FAudioSpectrumPlotScaleInfo Class Reference
Utility class for converting between spectrum data and local/absolute screen space.
#include "SAudioSpectrumPlot.h"
Public Member Functions
FAudioSpectrumPlotScaleInfo (const FVector2f InWidgetSize, EAudioSpectrumPlotFrequencyAxisScale InFrequencyAxisScale, float InViewMinFrequency, float InViewMaxFrequency, float InViewMinSoundLevel, float InViewMaxSoundLevel)
float FrequencyToLocalX (float Frequency) const
float LocalXToFrequency (float ScreenX) const
float LocalYToSoundLevel (float ScreenY) const
float SoundLevelToLocalY (float SoundLevel) const
FVector2f ToLocalPos (const FVector2f &FrequencyAndSoundLevel) const
Private Member Functions
float ForwardTransformFrequency (float Frequency) const
float InverseTransformFrequency (float TransformedFrequency) const
Private Attributes
const EAudioSpectrumPlotFrequencyAxisScale FrequencyAxisScale
const float PixelsPerDecibel
const float PixelsPerTransformedHz
const float TransformedViewFrequencyRange
const float TransformedViewMaxFrequency
const float TransformedViewMinFrequency
const float ViewMaxSoundLevel
const float ViewMinSoundLevel
const float ViewSoundLevelRange
const FVector2f WidgetSize
Detailed Description
Utility class for converting between spectrum data and local/absolute screen space.
Definition at line 44 of file SAudioSpectrumPlot.h.
Constructor & Destructor Documentation
FAudioSpectrumPlotScaleInfo()
FAudioSpectrumPlotScaleInfo::FAudioSpectrumPlotScaleInfo (const FVector2f InWidgetSize, EAudioSpectrumPlotFrequencyAxisScale InFrequencyAxisScale, float InViewMinFrequency, float InViewMaxFrequency, float InViewMinSoundLevel, float InViewMaxSoundLevel) inline
Definition at line 47 of file SAudioSpectrumPlot.h.
References ForwardTransformFrequency(), FrequencyAxisScale, PixelsPerDecibel, PixelsPerTransformedHz, TransformedViewFrequencyRange, TransformedViewMaxFrequency, TransformedViewMinFrequency, ViewMaxSoundLevel, ViewMinSoundLevel, ViewSoundLevelRange, WidgetSize, X, and Y.
Member Function Documentation
ForwardTransformFrequency()
float FAudioSpectrumPlotScaleInfo::ForwardTransformFrequency (float Frequency) const inline private
Definition at line 89 of file SAudioSpectrumPlot.h.
References Frequency, and FrequencyAxisScale.
Referenced by FAudioSpectrumPlotScaleInfo(), and FrequencyToLocalX().
FrequencyToLocalX()
float FAudioSpectrumPlotScaleInfo::FrequencyToLocalX (float Frequency) const inline
Definition at line 68 of file SAudioSpectrumPlot.h.
References ForwardTransformFrequency(), Frequency, PixelsPerTransformedHz, and TransformedViewMinFrequency.
Referenced by ToLocalPos().
InverseTransformFrequency()
float FAudioSpectrumPlotScaleInfo::InverseTransformFrequency (float TransformedFrequency) const inline private
Definition at line 94 of file SAudioSpectrumPlot.h.
References FrequencyAxisScale.
Referenced by LocalXToFrequency().
LocalXToFrequency()
float FAudioSpectrumPlotScaleInfo::LocalXToFrequency (float ScreenX) const inline
Definition at line 62 of file SAudioSpectrumPlot.h.
References InverseTransformFrequency(), PixelsPerTransformedHz, and TransformedViewMinFrequency.
LocalYToSoundLevel()
float FAudioSpectrumPlotScaleInfo::LocalYToSoundLevel (float ScreenY) const inline
Definition at line 73 of file SAudioSpectrumPlot.h.
References PixelsPerDecibel, and ViewMaxSoundLevel.
SoundLevelToLocalY()
float FAudioSpectrumPlotScaleInfo::SoundLevelToLocalY (float SoundLevel) const inline
Definition at line 78 of file SAudioSpectrumPlot.h.
References PixelsPerDecibel, and ViewMaxSoundLevel.
Referenced by ToLocalPos().
ToLocalPos()
FVector2f FAudioSpectrumPlotScaleInfo::ToLocalPos (const FVector2f & FrequencyAndSoundLevel) const inline
Definition at line 83 of file SAudioSpectrumPlot.h.
References FrequencyToLocalX(), SoundLevelToLocalY(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Field Documentation
FrequencyAxisScale
const EAudioSpectrumPlotFrequencyAxisScale FAudioSpectrumPlotScaleInfo::FrequencyAxisScale private
Definition at line 101 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo(), ForwardTransformFrequency(), and InverseTransformFrequency().
PixelsPerDecibel
const float FAudioSpectrumPlotScaleInfo::PixelsPerDecibel private
Definition at line 110 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo(), LocalYToSoundLevel(), and SoundLevelToLocalY().
PixelsPerTransformedHz
const float FAudioSpectrumPlotScaleInfo::PixelsPerTransformedHz private
Definition at line 105 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo(), FrequencyToLocalX(), and LocalXToFrequency().
TransformedViewFrequencyRange
const float FAudioSpectrumPlotScaleInfo::TransformedViewFrequencyRange private
Definition at line 104 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo().
TransformedViewMaxFrequency
const float FAudioSpectrumPlotScaleInfo::TransformedViewMaxFrequency private
Definition at line 103 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo().
TransformedViewMinFrequency
const float FAudioSpectrumPlotScaleInfo::TransformedViewMinFrequency private
Definition at line 102 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo(), FrequencyToLocalX(), and LocalXToFrequency().
ViewMaxSoundLevel
const float FAudioSpectrumPlotScaleInfo::ViewMaxSoundLevel private
Definition at line 108 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo(), LocalYToSoundLevel(), and SoundLevelToLocalY().
ViewMinSoundLevel
const float FAudioSpectrumPlotScaleInfo::ViewMinSoundLevel private
Definition at line 107 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo().
ViewSoundLevelRange
const float FAudioSpectrumPlotScaleInfo::ViewSoundLevelRange private
Definition at line 109 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo().
WidgetSize
const FVector2f FAudioSpectrumPlotScaleInfo::WidgetSize private
Definition at line 99 of file SAudioSpectrumPlot.h.
Referenced by FAudioSpectrumPlotScaleInfo().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/AudioWidgets/Source/AudioWidgets/Public/SAudioSpectrumPlot.h