Unreal Engine 5.6 C++ API: ISCSEditorUICustomization Class Reference
ISCSEditorUICustomization Class Reference
SCSEditor UI customization.
#include "ISCSEditorUICustomization.h"
Public Member Functions
virtual ~ISCSEditorUICustomization ()
virtual EChildActorComponentTreeViewVisualizationMode GetChildActorVisualizationMode () const
virtual TSubclassOf< UActorComponent > GetComponentTypeFilter (TArrayView< UObject * > Context) const
virtual bool HideAddComponentButton (TArrayView< UObject * > Context) const
virtual bool HideBlueprintButtons (TArrayView< UObject * > Context) const
virtual bool HideComponentsFilterBox (TArrayView< UObject * > Context) const
virtual bool HideComponentsTree (TArrayView< UObject * > Context) const
UE_DEPRECATED (5.5, "Use version with ObjectContext instead") virtual bool HideAddComponentButton() const
UE_DEPRECATED (5.5, "Use version with ObjectContext instead") virtual bool HideBlueprintButtons() const
UE_DEPRECATED (5.5, "Use version with ObjectContext instead") virtual bool HideComponentsFilterBox() const
UE_DEPRECATED (5.5, "Use version with ObjectContext instead") virtual bool HideComponentsTree() const
UE_DEPRECATED (5.5, "Use version with ObjectContext instead") virtual TSubclassOf< UActorComponent > GetComponentTypeFilter() const
Detailed Description
SCSEditor UI customization.
Definition at line 13 of file ISCSEditorUICustomization.h.
Constructor & Destructor Documentation
~ISCSEditorUICustomization()
virtual ISCSEditorUICustomization::~ISCSEditorUICustomization () inline virtual
Definition at line 16 of file ISCSEditorUICustomization.h.
Member Function Documentation
GetChildActorVisualizationMode()
virtual EChildActorComponentTreeViewVisualizationMode ISCSEditorUICustomization::GetChildActorVisualizationMode () const inline virtual
Returns
An override for the default ChildActorComponentTreeViewVisualizationMode from the project settings, if different from UseDefault.
Note
Setting an override also forces child actor tree view expansion to be enabled.
Definition at line 49 of file ISCSEditorUICustomization.h.
GetComponentTypeFilter()
virtual TSubclassOf< UActorComponent > ISCSEditorUICustomization::GetComponentTypeFilter (TArrayView< UObject * > Context) const inline virtual
Returns
A component type that limits visible nodes when filtering the tree view
Definition at line 52 of file ISCSEditorUICustomization.h.
Referenced by UE_DEPRECATED().
HideAddComponentButton()
virtual bool ISCSEditorUICustomization::HideAddComponentButton (TArrayView< UObject * > Context) const inline virtual
Returns
Whether to hide the "Add Component" combo button
Definition at line 40 of file ISCSEditorUICustomization.h.
Referenced by UE_DEPRECATED().
HideBlueprintButtons()
virtual bool ISCSEditorUICustomization::HideBlueprintButtons (TArrayView< UObject * > Context) const inline virtual
Returns
Whether to hide the "Edit Blueprint" and "Blueprint/Add Script" buttons
Definition at line 43 of file ISCSEditorUICustomization.h.
Referenced by UE_DEPRECATED().
HideComponentsFilterBox()
virtual bool ISCSEditorUICustomization::HideComponentsFilterBox (TArrayView< UObject * > Context) const inline virtual
Returns
Whether to hide the components filter box
Definition at line 37 of file ISCSEditorUICustomization.h.
Referenced by UE_DEPRECATED().
HideComponentsTree()
virtual bool ISCSEditorUICustomization::HideComponentsTree (TArrayView< UObject * > Context) const inline virtual
Returns
Whether to hide the components tree
Definition at line 34 of file ISCSEditorUICustomization.h.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/5]
ISCSEditorUICustomization::UE_DEPRECATED (5. 5, "Use version with ObjectContext instead") const inline
Definition at line 24 of file ISCSEditorUICustomization.h.
References HideAddComponentButton().
UE_DEPRECATED() [2/5]
ISCSEditorUICustomization::UE_DEPRECATED (5. 5, "Use version with ObjectContext instead") const inline
Definition at line 27 of file ISCSEditorUICustomization.h.
References HideBlueprintButtons().
UE_DEPRECATED() [3/5]
ISCSEditorUICustomization::UE_DEPRECATED (5. 5, "Use version with ObjectContext instead") const inline
Definition at line 21 of file ISCSEditorUICustomization.h.
References HideComponentsFilterBox().
UE_DEPRECATED() [4/5]
ISCSEditorUICustomization::UE_DEPRECATED (5. 5, "Use version with ObjectContext instead") const inline
Definition at line 18 of file ISCSEditorUICustomization.h.
References HideComponentsTree().
UE_DEPRECATED() [5/5]
ISCSEditorUICustomization::UE_DEPRECATED (5. 5, "Use version with ObjectContext instead") const inline
Definition at line 30 of file ISCSEditorUICustomization.h.
References GetComponentTypeFilter().
The documentation for this class was generated from the following file:
Editor/Kismet/Public/ISCSEditorUICustomization.h