Unreal Engine 5.6 C++ API: UE::Geometry::FDelaunay2 Class Reference
UE::Geometry::FDelaunay2 Class Reference
#include "Delaunay2.h"
Public Types
enum class EFillMode {
Solid , PositiveWinding , NonZeroWinding , NegativeWinding ,
OddWinding
}
enum class EResult {
Success , NotComputed , EmptyInput , Collinear ,
MissingEdges , Unknown
}
Public Member Functions
bool CanComputeVoronoiCells () const
GEOMETRYCORE_API bool ConstrainEdges (TArrayView< const TVector2< double > > Vertices, TArrayView< const FIndex2i > Edges)
Update an already-computed triangulation so the given edges are in the triangulation.
GEOMETRYCORE_API bool ConstrainEdges (TArrayView< const TVector2< float > > Vertices, TArrayView< const FIndex2i > Edges)
GEOMETRYCORE_API void FixDuplicatesOnEdge (FIndex2i &Edge)
GEOMETRYCORE_API bool GetFilledTriangles (TArray< FIndex3i > &TrianglesOut, TArrayView< const FIndex2i > BoundaryEdges, TArrayView< const FIndex2i > HoleEdges) const
Get (by reference) the triangles that are inside the given edges, removing the outside-boundary triangles and the inside-hole triangles.
GEOMETRYCORE_API bool GetFilledTriangles (TArray< FIndex3i > &TrianglesOut, TArrayView< const FIndex2i > Edges, EFillMode FillMode=EFillMode::PositiveWinding) const
Get (by reference) the triangles that are inside the given edges, removing the outer boundary triangles If a Winding-Number-based fill mode is used, assumes edges are oriented and tracks the winding number across edges.
TArray< FIndex3i > GetFilledTriangles (TArrayView< const FIndex2i > Edges, EFillMode FillMode=EFillMode::PositiveWinding)
Return the triangles that are inside the given edges, removing the outer boundary triangles If a Winding-Number-based fill mode is used, assumes edges are oriented and tracks the winding number across edges.
GEOMETRYCORE_API bool GetFilledTrianglesGeneralizedWinding (TArray< FIndex3i > &TrianglesOut, TArrayView< const TVector2< double > > Vertices, TArrayView< const FIndex2i > Edges, EFillMode FillMode=EFillMode::PositiveWinding) const
Get (by reference) the triangles that are inside the given edges, using a generalized winding number method to determine which triangles are inside Not valid for EFillMode::Solid, will fall back to the above GetFilledTriangles method in that case.
GEOMETRYCORE_API bool GetFilledTrianglesGeneralizedWinding (TArray< FIndex3i > &TrianglesOut, TArrayView< const TVector2< float > > Vertices, TArrayView< const FIndex2i > Edges, EFillMode FillMode=EFillMode::PositiveWinding) const
EResult GetResult () const
GEOMETRYCORE_API TArray< FIndex3i > GetTriangles () const
GEOMETRYCORE_API void GetTrianglesAndAdjacency (TArray< FIndex3i > &Triangles, TArray< FIndex3i > &Adjacency) const
GEOMETRYCORE_API TArray< TArray< FVector2d > > GetVoronoiCells (TArrayView< const FVector2d > Vertices, bool bIncludeBoundary=false, FAxisAlignedBox2d ClipBounds=FAxisAlignedBox2d::Empty(), double ExpandBounds=0.0) const
Get Voronoi diagram cells as dual of the Delaunay triangulation.
GEOMETRYCORE_API TArray< TArray< FVector2f > > GetVoronoiCells (TArrayView< const FVector2f > Vertices, bool bIncludeBoundary=false, FAxisAlignedBox2f ClipBounds=FAxisAlignedBox2f::Empty(), float ExpandBounds=0.0f) const
GEOMETRYCORE_API bool HasDuplicates () const
GEOMETRYCORE_API bool HasEdge (const FIndex2i &Edge, bool bRemapDuplicates)
GEOMETRYCORE_API bool HasEdges (TArrayView< const FIndex2i > Edges) const
bool IsConstrained () const
GEOMETRYCORE_API bool IsDelaunay (TArrayView< const FVector2d > Vertices, TArrayView< const FIndex2i > SkipEdges=TArrayView< const FIndex2i >()) const
GEOMETRYCORE_API bool IsDelaunay (TArrayView< const FVector2f > Vertices, TArrayView< const FIndex2i > SkipEdges=TArrayView< const FIndex2i >()) const
GEOMETRYCORE_API int32 RemapIfDuplicate (int32 Index) const
template<typename RealType>
bool Triangulate (const TGeneralPolygon2< RealType > &GeneralPolygon, TArray< FIndex3i > *TrianglesOut=nullptr, TArray< TVector2< RealType > > *VerticesOut=nullptr, bool bFallbackToGeneralizedWinding=false)
template<typename RealType>
bool Triangulate (const TPolygon2< RealType > &Polygon, TArray< FIndex3i > *TrianglesOut=nullptr)
GEOMETRYCORE_API bool Triangulate (TArrayView< const TVector2< double > > Vertices, TArrayView< const FIndex2i > Edges=TArrayView< const FIndex2i >())
Compute an (optionally constrained) Delaunay triangulation.
GEOMETRYCORE_API bool Triangulate (TArrayView< const TVector2< float > > Vertices, TArrayView< const FIndex2i > Edges=TArrayView< const FIndex2i >())
Static Public Member Functions
template<typename RealType>
static TArray< TArray< TVector2< RealType > > > ComputeVoronoiCells (TArrayView< const TVector2< RealType > > Sites, bool bIncludeBoundary=false, TAxisAlignedBox2< RealType > ClipBounds=FAxisAlignedBox2f::Empty(), RealType ExpandBounds=(RealType) 0)
Compute Voronoi diagram cells.
Data Fields
bool bAutomaticallyFixEdgesToDuplicateVertices = false
bool bKeepFastEdgeAdjacencyData = false
bool bValidateEdges = true
FRandomStream RandomStream
Protected Member Functions
UE_DEPRECATED (5.5, "No longer used by the implementation and may be removed") bool ValidateResult(TArrayView< const FIndex2i > Edges) const
Protected Attributes
bool bIsConstrained = false
TPimplPtr< FDelaunay2Connectivity > Connectivity
Private Member Functions
bool ValidateEdgesResult (TArrayView< const FIndex2i > Edges)
Private Attributes
EResult Result = EResult::NotComputed
Detailed Description
Definition at line 35 of file Delaunay2.h.
Member Enumeration Documentation
EFillMode
enum class UE::Geometry::FDelaunay2::EFillMode strong
Enumerator
Solid
PositiveWinding
NonZeroWinding
NegativeWinding
OddWinding
Definition at line 56 of file Delaunay2.h.
EResult
enum class UE::Geometry::FDelaunay2::EResult strong
Enumerator
Success
NotComputed
EmptyInput
Collinear
MissingEdges
Unknown
Definition at line 40 of file Delaunay2.h.
Member Function Documentation
CanComputeVoronoiCells()
bool UE::Geometry::FDelaunay2::CanComputeVoronoiCells () const inline
Returns
Whether the triangulation result supports computing a Voronoi diagram – i.e., if it was triangulated, or a collinear input
Definition at line 312 of file Delaunay2.h.
References Collinear, Result, and Success.
ComputeVoronoiCells()
template<typename RealType> TArray< TArray< TVector2< RealType > > > UE::Geometry::FDelaunay2::ComputeVoronoiCells (TArrayView< const TVector2< RealType > > Sites, bool bIncludeBoundary = false, TAxisAlignedBox2< RealType > ClipBounds = FAxisAlignedBox2f::Empty(), RealType ExpandBounds = (RealType)0) inline static
Compute Voronoi diagram cells.
Parameters
Sites Positions to use as the sites of the Voronoi diagram
bIncludeBoundary If true, include the cells on the boundary of the diagram. These cells are conceptually infinite, but will be clipped to a bounding box.
ClipBounds If non-empty, all Voronoi diagram cells will be clipped to this rectangle.
ExpandBounds Amount to expand the clipping bounds beyond the Bounds argument (or the bounding box of non-boundary Voronoi cells, if Bounds was empty)
Returns
The cells of each Voronoi site, or an empty array if the Triangulation was not yet computed
Definition at line 298 of file Delaunay2.h.
References UE::Geometry::TAxisAlignedBox2< float >::Empty(), GetVoronoiCells(), and Triangulate().
ConstrainEdges() [1/2]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::ConstrainEdges (TArrayView< const TVector2< double > > Vertices, TArrayView< const FIndex2i > Edges)
Update an already-computed triangulation so the given edges are in the triangulation.
Note: Assumes the edges do not intersect other constrained edges OR existing vertices in the triangulation
Returns
true if edges were successfully inserted. Note: Will not detect failure due to intersection of constrained edges unless member bValidateEdges == true.
References UE::Geometry::Vertices.
ConstrainEdges() [2/2]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::ConstrainEdges (TArrayView< const TVector2< float > > Vertices, TArrayView< const FIndex2i > Edges)
References UE::Geometry::Vertices.
FixDuplicatesOnEdge()
GEOMETRYCORE_API void UE::Geometry::FDelaunay2::FixDuplicatesOnEdge (FIndex2i & Edge)
References UE::Geometry::Edge.
GetFilledTriangles() [1/3]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::GetFilledTriangles (TArray< FIndex3i > & TrianglesOut, TArrayView< const FIndex2i > BoundaryEdges, TArrayView< const FIndex2i > HoleEdges) const
Get (by reference) the triangles that are inside the given edges, removing the outside-boundary triangles and the inside-hole triangles.
Parameters
TrianglesOut Will be filled with a subset of the triangulation that is 'inside' the given edges, as defined by the FillMode
BoundaryEdges Constrained edges in the triangulation that define the boundary of the desired shape
HoleEdges Constrained edges in the triangulation that define inner holes of the desired shape
Returns
true if any result was successfully computed (including an empty result). Currently only returns false if Triangulate() has not been called yet.
GetFilledTriangles() [2/3]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::GetFilledTriangles (TArray< FIndex3i > & TrianglesOut, TArrayView< const FIndex2i > Edges, EFillMode FillMode = EFillMode::PositiveWinding) const
Get (by reference) the triangles that are inside the given edges, removing the outer boundary triangles If a Winding-Number-based fill mode is used, assumes edges are oriented and tracks the winding number across edges.
Parameters
TrianglesOut Will be filled with a subset of the triangulation that is 'inside' the given edges, as defined by the FillMode
Edges The array of edges that were already constrained in the triangulation (by a previous call to Triangulate or ConstrainEdges)
FillMode Strategy to use to define which triangles to include in the output
Returns
true if the result was well defined and consistent; false otherwise. Solid fill mode always has a well defined result; Winding-number-based fills do not if the edges have open spans. Note the triangulation will still be filled by best-effort even if the function returns false.
References PositiveWinding.
GetFilledTriangles() [3/3]
TArray< FIndex3i > UE::Geometry::FDelaunay2::GetFilledTriangles (TArrayView< const FIndex2i > Edges, EFillMode FillMode = EFillMode::PositiveWinding) inline
Return the triangles that are inside the given edges, removing the outer boundary triangles If a Winding-Number-based fill mode is used, assumes edges are oriented and tracks the winding number across edges.
Parameters
Edges The array of edges that were already constrained in the triangulation (by a previous call to Triangulate or ConstrainEdges)
FillMode Strategy to use to define which triangles to include in the output
Returns
A subset of the triangulation that is 'inside' the given edges, as defined by the FillMode
Definition at line 204 of file Delaunay2.h.
References GetFilledTriangles(), and PositiveWinding.
Referenced by GetFilledTriangles(), Triangulate(), and Triangulate().
GetFilledTrianglesGeneralizedWinding() [1/2]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::GetFilledTrianglesGeneralizedWinding (TArray< FIndex3i > & TrianglesOut, TArrayView< const TVector2< double > > Vertices, TArrayView< const FIndex2i > Edges, EFillMode FillMode = EFillMode::PositiveWinding) const
Get (by reference) the triangles that are inside the given edges, using a generalized winding number method to determine which triangles are inside Not valid for EFillMode::Solid, will fall back to the above GetFilledTriangles method in that case.
This method is for triangulations where the edges did not define a fully-closed shape, either by construction or due to un-resolved edge intersections in the input. Note that it is slower than the standard GetFilledTriangles, and is worse for closed polygons where all edges were successfully constrained.
Parameters
TrianglesOut Will be filled with a subset of the triangulation that is 'inside' the given edges, as defined by the FillMode
Vertices The array of vertices that were used in the triangulation (by the previous call to Triangulate)
Edges The array of edges that were already constrained in the triangulation (by a previous call to Triangulate or ConstrainEdges)
FillMode Strategy to use to define which triangles to include in the output
Returns
true if the result was well defined and consistent; false otherwise. Solid fill mode always has a well defined result; Winding-number-based fills do not if the edges have open spans. Note the triangulation will still be filled by best-effort even if the function returns false.
References PositiveWinding, and UE::Geometry::Vertices.
Referenced by Triangulate().
GetFilledTrianglesGeneralizedWinding() [2/2]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::GetFilledTrianglesGeneralizedWinding (TArray< FIndex3i > & TrianglesOut, TArrayView< const TVector2< float > > Vertices, TArrayView< const FIndex2i > Edges, EFillMode FillMode = EFillMode::PositiveWinding) const
References PositiveWinding, and UE::Geometry::Vertices.
GetResult()
EResult UE::Geometry::FDelaunay2::GetResult () const inline
Returns
Last triangulation result – either Success, NotComputed, or a reason for failure
Definition at line 306 of file Delaunay2.h.
References Result.
GetTriangles()
GEOMETRYCORE_API TArray< FIndex3i > UE::Geometry::FDelaunay2::GetTriangles () const
GetTrianglesAndAdjacency()
GEOMETRYCORE_API void UE::Geometry::FDelaunay2::GetTrianglesAndAdjacency (TArray< FIndex3i > & Triangles, TArray< FIndex3i > & Adjacency) const
GetVoronoiCells() [1/2]
GEOMETRYCORE_API TArray< TArray< FVector2d > > UE::Geometry::FDelaunay2::GetVoronoiCells (TArrayView< const FVector2d > Vertices, bool bIncludeBoundary = false, FAxisAlignedBox2d ClipBounds = FAxisAlignedBox2d::Empty(), double ExpandBounds = 0.0) const
Get Voronoi diagram cells as dual of the Delaunay triangulation.
You must call Triangulate() before calling this.
Parameters
Vertices Vertices of the Delaunay triangulation, to be used as the sites of the Voronoi diagram
bIncludeBoundary If true, include the cells on the boundary of the diagram. These cells are conceptually infinite, but will be clipped to a bounding box.
ClipBounds If non-empty, all Voronoi diagram cells will be clipped to this rectangle.
ExpandBounds Amount to expand the clipping bounds beyond the Bounds argument (or the bounding box of non-boundary Voronoi cells, if Bounds was empty)
Returns
The cells of each Voronoi site, or an empty array if the Triangulation was not yet computed
References UE::Geometry::TAxisAlignedBox2< double >::Empty(), and UE::Geometry::Vertices.
Referenced by ComputeVoronoiCells().
GetVoronoiCells() [2/2]
GEOMETRYCORE_API TArray< TArray< FVector2f > > UE::Geometry::FDelaunay2::GetVoronoiCells (TArrayView< const FVector2f > Vertices, bool bIncludeBoundary = false, FAxisAlignedBox2f ClipBounds = FAxisAlignedBox2f::Empty(), float ExpandBounds = 0.0f) const
References UE::Geometry::TAxisAlignedBox2< float >::Empty(), and UE::Geometry::Vertices.
HasDuplicates()
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::HasDuplicates () const
HasEdge()
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::HasEdge (const FIndex2i & Edge, bool bRemapDuplicates)
References UE::Geometry::Edge.
HasEdges()
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::HasEdges (TArrayView< const FIndex2i > Edges) const
Referenced by UE_DEPRECATED(), and ValidateEdgesResult().
IsConstrained()
bool UE::Geometry::FDelaunay2::IsConstrained () const inline
Definition at line 252 of file Delaunay2.h.
References bIsConstrained.
IsDelaunay() [1/2]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::IsDelaunay (TArrayView< const FVector2d > Vertices, TArrayView< const FIndex2i > SkipEdges = TArrayView< const FIndex2i >()) const
References UE::Geometry::Vertices.
IsDelaunay() [2/2]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::IsDelaunay (TArrayView< const FVector2f > Vertices, TArrayView< const FIndex2i > SkipEdges = TArrayView< const FIndex2i >()) const
References UE::Geometry::Vertices.
RemapIfDuplicate()
GEOMETRYCORE_API int32 UE::Geometry::FDelaunay2::RemapIfDuplicate (int32 Index) const
Triangulate() [1/4]
template<typename RealType> bool UE::Geometry::FDelaunay2::Triangulate (const TGeneralPolygon2< RealType > & GeneralPolygon, TArray< FIndex3i > * TrianglesOut = nullptr, TArray< TVector2< RealType > > * VerticesOut = nullptr, bool bFallbackToGeneralizedWinding = false) inline
Definition at line 128 of file Delaunay2.h.
References TArray< InElementType, InAllocatorType >::Append(), GetFilledTriangles(), GetFilledTrianglesGeneralizedWinding(), UE::Geometry::TGeneralPolygon2< T >::GetHoles(), UE::Geometry::TGeneralPolygon2< T >::GetOuter(), Last, MoveTemp(), NegativeWinding, Num, TArray< InElementType, InAllocatorType >::Num(), UE::Geometry::TGeneralPolygon2< T >::OuterIsClockwise(), PositiveWinding, Triangulate(), and UE::Geometry::Vertices.
Triangulate() [2/4]
template<typename RealType> bool UE::Geometry::FDelaunay2::Triangulate (const TPolygon2< RealType > & Polygon, TArray< FIndex3i > * TrianglesOut = nullptr) inline
Definition at line 105 of file Delaunay2.h.
References TArray< InElementType, InAllocatorType >::Add(), GetFilledTriangles(), Last, UE::Geometry::Polygon, TArray< InElementType, InAllocatorType >::Reserve(), Solid, and Triangulate().
Triangulate() [3/4]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::Triangulate (TArrayView< const TVector2< double > > Vertices, TArrayView< const FIndex2i > Edges = TArrayView< const FIndex2i >())
Compute an (optionally constrained) Delaunay triangulation.
Note this clears any previously-held triangulation data, and triangulates the passed-in vertices (and optional edges) from scratch
Returns
false if triangulation failed
References UE::Geometry::Vertices.
Referenced by ComputeVoronoiCells(), Triangulate(), and Triangulate().
Triangulate() [4/4]
GEOMETRYCORE_API bool UE::Geometry::FDelaunay2::Triangulate (TArrayView< const TVector2< float > > Vertices, TArrayView< const FIndex2i > Edges = TArrayView< const FIndex2i >())
References UE::Geometry::Vertices.
UE_DEPRECATED()
UE::Geometry::FDelaunay2::UE_DEPRECATED (5. 5, "No longer used by the implementation and may be removed") const inline protected
Definition at line 323 of file Delaunay2.h.
References bool, bValidateEdges, and HasEdges().
ValidateEdgesResult()
bool UE::Geometry::FDelaunay2::ValidateEdgesResult (TArrayView< const FIndex2i > Edges) inline private
Definition at line 332 of file Delaunay2.h.
References bValidateEdges, HasEdges(), MissingEdges, and Result.
Field Documentation
bAutomaticallyFixEdgesToDuplicateVertices
bool UE::Geometry::FDelaunay2::bAutomaticallyFixEdgesToDuplicateVertices = false
Definition at line 85 of file Delaunay2.h.
bIsConstrained
bool UE::Geometry::FDelaunay2::bIsConstrained = false protected
Definition at line 320 of file Delaunay2.h.
Referenced by IsConstrained().
bKeepFastEdgeAdjacencyData
bool UE::Geometry::FDelaunay2::bKeepFastEdgeAdjacencyData = false
Definition at line 76 of file Delaunay2.h.
bValidateEdges
bool UE::Geometry::FDelaunay2::bValidateEdges = true
Definition at line 81 of file Delaunay2.h.
Referenced by UE_DEPRECATED(), and ValidateEdgesResult().
Connectivity
TPimplPtr<FDelaunay2Connectivity> UE::Geometry::FDelaunay2::Connectivity protected
Definition at line 318 of file Delaunay2.h.
RandomStream
FRandomStream UE::Geometry::FDelaunay2::RandomStream
Definition at line 73 of file Delaunay2.h.
Result
EResult UE::Geometry::FDelaunay2::Result = EResult::NotComputed private
Definition at line 330 of file Delaunay2.h.
Referenced by CanComputeVoronoiCells(), GetResult(), and ValidateEdgesResult().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/CompGeom/Delaunay2.h