Unreal Engine 5.6 C++ API: TArrayBuilder< ElementType, Allocator > Class Template Reference
TArrayBuilder< ElementType, Allocator > Class Template Reference
Template for fluent array builders.
#include "ArrayBuilder.h"
Public Member Functions
TArrayBuilder ()
Default constructor.
template<typename OtherAllocator>
TArrayBuilder (const TArray< ElementType, OtherAllocator > &InArray)
Creates and initializes an array builder from an array of items.
TArrayBuilder & Add (const ElementType &Item)
Adds an item.
TArrayBuilder & AddUnique (const ElementType &Item)
Adds an unique item.
template<typename OtherAllocator>
TArrayBuilder & Append (const TArray< ElementType, OtherAllocator > &OtherArray)
Appends an array of items.
TArray< ElementType, Allocator > Build ()
Builds the array as configured.
operator TArray< ElementType, Allocator > ()
Implicit conversion operator to build the array as configured.
Private Attributes
TArray< ElementType, Allocator > Array
Holds the array.
Detailed Description
template<typename ElementType, typename Allocator = FDefaultAllocator>
class TArrayBuilder< ElementType, Allocator >
Template for fluent array builders.
Parameters
ElementType The type of elements stored in the array.
Allocator The allocator to use for elements.
Definition at line 15 of file ArrayBuilder.h.
Constructor & Destructor Documentation
TArrayBuilder() [1/2]
template<typename ElementType, typename Allocator = FDefaultAllocator> TArrayBuilder< ElementType, Allocator >::TArrayBuilder () inline
Default constructor.
Definition at line 20 of file ArrayBuilder.h.
Referenced by Add(), AddUnique(), and Append().
TArrayBuilder() [2/2]
template<typename ElementType, typename Allocator = FDefaultAllocator> template<typename OtherAllocator> TArrayBuilder< ElementType, Allocator >::TArrayBuilder (const TArray< ElementType, OtherAllocator > & InArray) inline
Creates and initializes an array builder from an array of items.
Parameters
InArray The array of items to copy.
Definition at line 27 of file ArrayBuilder.h.
References Array.
Member Function Documentation
Add()
template<typename ElementType, typename Allocator = FDefaultAllocator> TArrayBuilder & TArrayBuilder< ElementType, Allocator >::Add (const ElementType & Item) inline
Adds an item.
Parameters
Item The item to add.
Returns
This instance (for method chaining).
See also
AddUnique
Definition at line 40 of file ArrayBuilder.h.
References TArrayBuilder(), Array, and Item.
AddUnique()
template<typename ElementType, typename Allocator = FDefaultAllocator> TArrayBuilder & TArrayBuilder< ElementType, Allocator >::AddUnique (const ElementType & Item) inline
Adds an unique item.
Parameters
Item The unique item to add.
Returns
This instance (for method chaining).
See also
Add
Definition at line 54 of file ArrayBuilder.h.
References TArrayBuilder(), Array, and Item.
Append()
template<typename ElementType, typename Allocator = FDefaultAllocator> template<typename OtherAllocator> TArrayBuilder & TArrayBuilder< ElementType, Allocator >::Append (const TArray< ElementType, OtherAllocator > & OtherArray) inline
Appends an array of items.
Parameters
OtherArray The array to append.
Returns
This instance (for method chaining).
Definition at line 67 of file ArrayBuilder.h.
References TArrayBuilder(), and Array.
Build()
template<typename ElementType, typename Allocator = FDefaultAllocator> TArray< ElementType, Allocator > TArrayBuilder< ElementType, Allocator >::Build () inline
Builds the array as configured.
Returns
A new array.
Definition at line 81 of file ArrayBuilder.h.
References Array.
Referenced by operator TArray< ElementType, Allocator >().
operator TArray< ElementType, Allocator >()
template<typename ElementType, typename Allocator = FDefaultAllocator> TArrayBuilder< ElementType, Allocator >::operator TArray< ElementType, Allocator > () inline
Implicit conversion operator to build the array as configured.
Returns
A new array.
Definition at line 91 of file ArrayBuilder.h.
References Build().
Field Documentation
Array
template<typename ElementType, typename Allocator = FDefaultAllocator> TArray<ElementType, Allocator> TArrayBuilder< ElementType, Allocator >::Array private
Holds the array.
Definition at line 99 of file ArrayBuilder.h.
Referenced by TArrayBuilder(), Add(), AddUnique(), Append(), and Build().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/ArrayBuilder.h