Unreal Engine 5.6 C++ API: TBigInt< NumBits, bSigned > Class Template Reference
TBigInt< NumBits, bSigned > Class Template Reference
n-bit integer.
#include "BigInt.h"
Public Types
typedef TBigInt< NumBits, bSigned > BigInt
Public Member Functions
TBigInt ()
Default constructor.
TBigInt (const FString &Value)
Constructor.
TBigInt (const uint32 *InBits)
Constructor.
TBigInt (const uint8 *InData, uint32 InNumBytes)
Constructor.
TBigInt (int64 Other)
Constructor.
void Add (const BigInt &Other)
Adds two integers.
void BitwiseAnd (const BigInt &Other)
Bitwise 'and'.
void BitwiseNot ()
Bitwise 'not'.
void BitwiseOr (const BigInt &Other)
Bitwise 'or'.
void Divide (const BigInt &Divisor)
Divides two integers.
void DivideWithRemainder (const BigInt &Divisor, BigInt &Remainder)
Divides two integers with remainder.
int32 GetBit (int32 BitIndex) const
Returns a bit value as an integer value (0 or 1).
FORCEINLINE uint32 * GetBits ()
FORCEINLINE const uint32 * GetBits () const
int32 GetHighestNonZeroBit () const
Returns the index of the highest non-zero bit.
int32 GetHighestNonZeroWord () const
Returns the index of the highest word that is not zero.
bool IsEqual (const BigInt &Other) const
Checks if two integers are equal.
bool IsFirstBitSet () const
bool IsGreater (const BigInt &Other) const
this > Other
bool IsGreaterOrEqual (const BigInt &Other) const
this >= Other
bool IsGreaterThanZero () const
this > 0
bool IsLess (const BigInt &Other) const
this < Other
bool IsLessOrEqual (const BigInt &Other) const
this <= Other
bool IsLessThanZero () const
this < 0
bool IsNegative () const
Checks if this integer is negative.
bool IsZero () const
this == 0
void Modulo (const BigInt &Modulus)
Performs modulo operation on this integer.
void Multiply (const BigInt &Factor)
Multiplies two integers.
void MultiplyFast (const BigInt &Factor)
Multiplies two positive integers.
void Negate ()
Negates this integer.
bool operator!= (const BigInt &Other) const
BigInt operator% (const BigInt &Modulus) const
BigInt & operator%= (const BigInt &Modulus)
BigInt operator& (const BigInt &Other) const
BigInt & operator&= (const BigInt &Other)
BigInt operator* (const BigInt &Other) const
BigInt & operator*= (const BigInt &Other)
BigInt operator+ (const BigInt &Other) const
BigInt & operator++ ()
BigInt & operator+= (const BigInt &Other)
BigInt operator- (const BigInt &Other) const
BigInt & operator-- ()
BigInt & operator-= (const BigInt &Other)
BigInt operator/ (const BigInt &Divider) const
BigInt & operator/= (const BigInt &Divider)
bool operator< (const BigInt &Other) const
BigInt operator<< (int32 Count) const
BigInt & operator<<= (int32 Count)
bool operator<= (const BigInt &Other) const
TBigInt & operator= (int64 Other)
Assignment operator for int64 values.
bool operator== (const BigInt &Other) const
bool operator> (const BigInt &Other) const
bool operator>= (const BigInt &Other) const
BigInt operator>> (int32 Count) const
BigInt & operator>>= (int32 Count)
bool operator[] (int32 BitIndex) const
Bit indexing operator.
BigInt operator| (const BigInt &Other) const
BigInt & operator|= (const BigInt &Other)
BigInt operator~ () const
void Parse (const FString &Value)
Parses a string representing a hex value.
FORCEINLINE void Set (int64 Value)
Initializes this big int with a 64 bit integer value.
void SetBit (int32 BitIndex, int32 Value)
Sets a bit value.
void ShiftLeft (const int32 BitCount)
Shift left by the specified amount of bits.
void ShiftLeftByOneInternal ()
Shift left by 1 bit.
void ShiftLeftInternal (const int32 BitCount)
Shift left by the specified amount of bits.
void ShiftRight (const int32 BitCount)
Shift right by the specified amount of bits.
void ShiftRightByOneInternal ()
Shift right by 1 bit.
void ShiftRightInternal (const int32 BitCount)
Shift right by the specified amount of bits.
int32 Sign () const
Returns the sign of this integer.
void Sqrt ()
Calculates square root of this integer.
void Subtract (const BigInt &Other)
Subtracts two integers.
int64 ToInt () const
Returns the value of this big int as a 64-bit integer.
FString ToString () const
Returns this big int as a string.
FORCEINLINE void Zero ()
Sets this integer to 0.
Static Public Attributes
static BigInt One
Private Types
enum { BitsPerWord = 32 , NumWords = NumBits / BitsPerWord }
Static Private Member Functions
static FORCEINLINE void MakePositiveFactors (BigInt &FactorA, int32 &SignA, BigInt &FactorB, int32 &SignB)
Makes sure both factors are positive integers and stores their original signs.
static FORCEINLINE void RestoreSign (BigInt &Result, int32 SignA, int32 SignB)
Restores a sign of a result based on the sign of two factors that produced the result.
Private Attributes
uint32 Bits [NumWords]
All bits stored as an array of words.
Friends
FArchive & operator<< (FArchive &Ar, BigInt &Value)
Serialization.
Detailed Description
template<int32 NumBits, bool bSigned = true>
class TBigInt< NumBits, bSigned >
n-bit integer.
Todo
: optimize Data is stored as an array of 32-bit words from the least to the most significant Doesn't handle overflows (not a big issue, we can always use a bigger bit count) Minimum sanity checks. Can convert from int64 and back (by truncating the result, this is mostly for testing)
Definition at line 18 of file BigInt.h.
Member Typedef Documentation
BigInt
template<int32 NumBits, bool bSigned = true> typedef TBigInt<NumBits, bSigned> TBigInt< NumBits, bSigned >::BigInt
Definition at line 22 of file BigInt.h.
Member Enumeration Documentation
anonymous enum
template<int32 NumBits, bool bSigned = true> anonymous enum private
Enumerator
BitsPerWord
Word size.
NumWords
Definition at line 28 of file BigInt.h.
Constructor & Destructor Documentation
TBigInt() [1/5]
template<int32 NumBits, bool bSigned = true> TBigInt< NumBits, bSigned >::TBigInt () inline nodiscard
Default constructor.
Initializes the number to zero.
Definition at line 111 of file BigInt.h.
TBigInt() [2/5]
template<int32 NumBits, bool bSigned = true> TBigInt< NumBits, bSigned >::TBigInt (int64 Other) inline nodiscard
Constructor.
Initializes this big int with a 64 bit integer value.
Parameters
Other The value to set.
Definition at line 121 of file BigInt.h.
TBigInt() [3/5]
template<int32 NumBits, bool bSigned = true> TBigInt< NumBits, bSigned >::TBigInt (const uint32 * InBits) inline explicit nodiscard
Constructor.
Initializes this big int with an array of words.
Definition at line 129 of file BigInt.h.
TBigInt() [4/5]
template<int32 NumBits, bool bSigned = true> TBigInt< NumBits, bSigned >::TBigInt (const uint8 * InData, uint32 InNumBytes) inline explicit nodiscard
Constructor.
Initializes this big int with an array of bytes.
Definition at line 137 of file BigInt.h.
TBigInt() [5/5]
template<int32 NumBits, bool bSigned = true> TBigInt< NumBits, bSigned >::TBigInt (const FString & Value) inline explicit nodiscard
Constructor.
Initializes this big int with a string representing a hex value.
Definition at line 152 of file BigInt.h.
Member Function Documentation
Add()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Add (const BigInt & Other) inline
Adds two integers.
Definition at line 260 of file BigInt.h.
Referenced by Sqrt().
BitwiseAnd()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::BitwiseAnd (const BigInt & Other) inline
Bitwise 'and'.
Definition at line 634 of file BigInt.h.
Referenced by operator&=().
BitwiseNot()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::BitwiseNot () inline
Bitwise 'not'.
Definition at line 645 of file BigInt.h.
BitwiseOr()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::BitwiseOr (const BigInt & Other) inline
Bitwise 'or'.
Definition at line 623 of file BigInt.h.
Referenced by operator|=().
Divide()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Divide (const BigInt & Divisor) inline
Divides two integers.
Definition at line 457 of file BigInt.h.
Referenced by operator/=().
DivideWithRemainder()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::DivideWithRemainder (const BigInt & Divisor, BigInt & Remainder) inline
Divides two integers with remainder.
Definition at line 382 of file BigInt.h.
Referenced by Divide(), and Modulo().
GetBit()
template<int32 NumBits, bool bSigned = true> int32 TBigInt< NumBits, bSigned >::GetBit (int32 BitIndex) const inline nodiscard
Returns a bit value as an integer value (0 or 1).
Definition at line 546 of file BigInt.h.
Referenced by operator[]().
GetBits() [1/2]
template<int32 NumBits, bool bSigned = true> FORCEINLINE uint32 * TBigInt< NumBits, bSigned >::GetBits () inline nodiscard
Definition at line 82 of file BigInt.h.
GetBits() [2/2]
template<int32 NumBits, bool bSigned = true> FORCEINLINE const uint32 * TBigInt< NumBits, bSigned >::GetBits () const inline nodiscard
Definition at line 87 of file BigInt.h.
GetHighestNonZeroBit()
template<int32 NumBits, bool bSigned = true> int32 TBigInt< NumBits, bSigned >::GetHighestNonZeroBit () const inline nodiscard
Returns the index of the highest non-zero bit.
-1 if no such bit exists.
Definition at line 529 of file BigInt.h.
Referenced by DivideWithRemainder().
GetHighestNonZeroWord()
template<int32 NumBits, bool bSigned = true> int32 TBigInt< NumBits, bSigned >::GetHighestNonZeroWord () const inline nodiscard
Returns the index of the highest word that is not zero.
-1 if no such word exists.
Definition at line 320 of file BigInt.h.
Referenced by MultiplyFast().
IsEqual()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsEqual (const BigInt & Other) const inline nodiscard
Checks if two integers are equal.
Definition at line 656 of file BigInt.h.
Referenced by operator!=(), and operator==().
IsFirstBitSet()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsFirstBitSet () const inline nodiscard
Definition at line 779 of file BigInt.h.
IsGreater()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsGreater (const BigInt & Other) const inline nodiscard
this > Other
Definition at line 714 of file BigInt.h.
Referenced by IsLess(), and operator>().
IsGreaterOrEqual()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsGreaterOrEqual (const BigInt & Other) const inline nodiscard
this >= Other
Definition at line 735 of file BigInt.h.
Referenced by IsLessOrEqual(), and operator>=().
IsGreaterThanZero()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsGreaterThanZero () const inline nodiscard
this > 0
Definition at line 766 of file BigInt.h.
IsLess()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsLess (const BigInt & Other) const inline nodiscard
this < Other
Definition at line 672 of file BigInt.h.
Referenced by IsGreater(), and operator<().
IsLessOrEqual()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsLessOrEqual (const BigInt & Other) const inline nodiscard
this <= Other
Definition at line 693 of file BigInt.h.
Referenced by IsGreaterOrEqual(), and operator<=().
IsLessThanZero()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsLessThanZero () const inline nodiscard
this < 0
Definition at line 774 of file BigInt.h.
IsNegative()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsNegative () const inline nodiscard
Checks if this integer is negative.
Definition at line 285 of file BigInt.h.
Referenced by IsGreater(), IsGreaterOrEqual(), IsGreaterThanZero(), IsLess(), IsLessOrEqual(), IsLessThanZero(), Modulo(), and Sign().
IsZero()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::IsZero () const inline nodiscard
this == 0
Definition at line 756 of file BigInt.h.
Referenced by IsGreaterThanZero(), IsLessThanZero(), and Sqrt().
MakePositiveFactors()
template<int32 NumBits, bool bSigned = true> FORCEINLINE void TBigInt< NumBits, bSigned >::MakePositiveFactors (BigInt & FactorA, int32 & SignA, BigInt & FactorB, int32 & SignB) inline static private
Makes sure both factors are positive integers and stores their original signs.
Parameters
FactorA first factor
SignA sign of the first factor
FactorB second factor
SignB sign of the second pactor
Definition at line 48 of file BigInt.h.
Referenced by DivideWithRemainder(), and Multiply().
Modulo()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Modulo (const BigInt & Modulus) inline
Performs modulo operation on this integer.
Definition at line 466 of file BigInt.h.
Referenced by operator%=().
Multiply()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Multiply (const BigInt & Factor) inline
Multiplies two integers.
Definition at line 363 of file BigInt.h.
Referenced by operator*=().
MultiplyFast()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::MultiplyFast (const BigInt & Factor) inline
Multiplies two positive integers.
Definition at line 330 of file BigInt.h.
Referenced by Modulo().
Negate()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Negate () inline
Negates this integer.
value = -value
Definition at line 308 of file BigInt.h.
Referenced by MakePositiveFactors(), Modulo(), and Subtract().
operator!=()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator!= (const BigInt & Other) const inline nodiscard
Definition at line 920 of file BigInt.h.
operator%()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator% (const BigInt & Modulus) const inline nodiscard
Definition at line 882 of file BigInt.h.
operator%=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator%= (const BigInt & Modulus) inline
Definition at line 889 of file BigInt.h.
operator&()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator& (const BigInt & Other) const inline nodiscard
Definition at line 925 of file BigInt.h.
operator&=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator&= (const BigInt & Other) inline
Definition at line 932 of file BigInt.h.
operator*()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator* (const BigInt & Other) const inline nodiscard
Definition at line 856 of file BigInt.h.
operator*=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator*= (const BigInt & Other) inline
Definition at line 863 of file BigInt.h.
operator+()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator+ (const BigInt & Other) const inline nodiscard
Definition at line 818 of file BigInt.h.
operator++()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator++ () inline
Definition at line 825 of file BigInt.h.
operator+=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator+= (const BigInt & Other) inline
Definition at line 831 of file BigInt.h.
operator-()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator- (const BigInt & Other) const inline nodiscard
Definition at line 837 of file BigInt.h.
operator--()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator-- () inline
Definition at line 844 of file BigInt.h.
operator-=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator-= (const BigInt & Other) inline
Definition at line 850 of file BigInt.h.
operator/()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator/ (const BigInt & Divider) const inline nodiscard
Definition at line 869 of file BigInt.h.
operator/=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator/= (const BigInt & Divider) inline
Definition at line 876 of file BigInt.h.
operator<()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator< (const BigInt & Other) const inline nodiscard
Definition at line 895 of file BigInt.h.
operator<<()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator<< (int32 Count) const inline nodiscard
Definition at line 805 of file BigInt.h.
operator<<=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator<<= (int32 Count) inline
Definition at line 812 of file BigInt.h.
operator<=()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator<= (const BigInt & Other) const inline nodiscard
Definition at line 900 of file BigInt.h.
operator=()
template<int32 NumBits, bool bSigned = true> TBigInt & TBigInt< NumBits, bSigned >::operator= (int64 Other) inline
Assignment operator for int64 values.
Definition at line 520 of file BigInt.h.
operator==()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator== (const BigInt & Other) const inline nodiscard
Definition at line 915 of file BigInt.h.
operator>()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator> (const BigInt & Other) const inline nodiscard
Definition at line 905 of file BigInt.h.
operator>=()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator>= (const BigInt & Other) const inline nodiscard
Definition at line 910 of file BigInt.h.
operator>>()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator>> (int32 Count) const inline nodiscard
Definition at line 792 of file BigInt.h.
operator>>=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator>>= (int32 Count) inline
Definition at line 799 of file BigInt.h.
operator[]()
template<int32 NumBits, bool bSigned = true> bool TBigInt< NumBits, bSigned >::operator[] (int32 BitIndex) const inline nodiscard
Bit indexing operator.
Definition at line 786 of file BigInt.h.
operator|()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator| (const BigInt & Other) const inline nodiscard
Definition at line 938 of file BigInt.h.
operator|=()
template<int32 NumBits, bool bSigned = true> BigInt & TBigInt< NumBits, bSigned >::operator|= (const BigInt & Other) inline
Definition at line 945 of file BigInt.h.
operator~()
template<int32 NumBits, bool bSigned = true> BigInt TBigInt< NumBits, bSigned >::operator~ () const inline nodiscard
Definition at line 951 of file BigInt.h.
Parse()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Parse (const FString & Value) inline
Parses a string representing a hex value.
Definition at line 991 of file BigInt.h.
Referenced by TBigInt().
RestoreSign()
template<int32 NumBits, bool bSigned = true> FORCEINLINE void TBigInt< NumBits, bSigned >::RestoreSign (BigInt & Result, int32 SignA, int32 SignB) inline static private
Restores a sign of a result based on the sign of two factors that produced the result.
Parameters
Result math opration result
SignA sign of the first factor
SignB sign of the second factor
Definition at line 72 of file BigInt.h.
Referenced by DivideWithRemainder(), and Multiply().
Set()
template<int32 NumBits, bool bSigned = true> FORCEINLINE void TBigInt< NumBits, bSigned >::Set (int64 Value) inline
Initializes this big int with a 64 bit integer value.
Parameters
Value The value to set.
Definition at line 103 of file BigInt.h.
Referenced by TBigInt(), and operator=().
SetBit()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::SetBit (int32 BitIndex, int32 Value) inline
Sets a bit value.
Definition at line 556 of file BigInt.h.
ShiftLeft()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::ShiftLeft (const int32 BitCount) inline
Shift left by the specified amount of bits.
Parameters
BitCount the number of bits to shift.
Definition at line 575 of file BigInt.h.
Referenced by operator<<=(), and ShiftRight().
ShiftLeftByOneInternal()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::ShiftLeftByOneInternal () inline
Shift left by 1 bit.
Definition at line 195 of file BigInt.h.
Referenced by DivideWithRemainder().
ShiftLeftInternal()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::ShiftLeftInternal (const int32 BitCount) inline
Shift left by the specified amount of bits.
Does not check if BitCount is valid.
Parameters
BitCount the number of bits to shift.
Definition at line 162 of file BigInt.h.
Referenced by DivideWithRemainder(), ShiftLeft(), and Sqrt().
ShiftRight()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::ShiftRight (const int32 BitCount) inline
Shift right by the specified amount of bits.
Parameters
BitCount the number of bits to shift.
Definition at line 600 of file BigInt.h.
Referenced by operator>>=(), and ShiftLeft().
ShiftRightByOneInternal()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::ShiftRightByOneInternal () inline
Shift right by 1 bit.
Definition at line 245 of file BigInt.h.
Referenced by DivideWithRemainder().
ShiftRightInternal()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::ShiftRightInternal (const int32 BitCount) inline
Shift right by the specified amount of bits.
Does not check if BitCount is valid.
Parameters
BitCount the number of bits to shift.
Definition at line 212 of file BigInt.h.
Referenced by DivideWithRemainder(), ShiftRight(), and Sqrt().
Sign()
template<int32 NumBits, bool bSigned = true> int32 TBigInt< NumBits, bSigned >::Sign () const inline nodiscard
Returns the sign of this integer.
Definition at line 300 of file BigInt.h.
Referenced by MakePositiveFactors().
Sqrt()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Sqrt () inline
Calculates square root of this integer.
Definition at line 485 of file BigInt.h.
Subtract()
template<int32 NumBits, bool bSigned = true> void TBigInt< NumBits, bSigned >::Subtract (const BigInt & Other) inline
Subtracts two integers.
Definition at line 275 of file BigInt.h.
Referenced by operator--(), and operator-=().
ToInt()
template<int32 NumBits, bool bSigned = true> int64 TBigInt< NumBits, bSigned >::ToInt () const inline nodiscard
Returns the value of this big int as a 64-bit integer.
If the value is greater, the higher bits are truncated.
Definition at line 962 of file BigInt.h.
ToString()
template<int32 NumBits, bool bSigned = true> FString TBigInt< NumBits, bSigned >::ToString () const inline nodiscard
Returns this big int as a string.
Definition at line 970 of file BigInt.h.
Zero()
template<int32 NumBits, bool bSigned = true> FORCEINLINE void TBigInt< NumBits, bSigned >::Zero () inline
Sets this integer to 0.
Definition at line 93 of file BigInt.h.
Referenced by TBigInt(), TBigInt(), DivideWithRemainder(), Parse(), Set(), ShiftLeft(), and ShiftRight().
Friends And Related Symbol Documentation
operator<<
template<int32 NumBits, bool bSigned = true> FArchive & operator<< (FArchive & Ar, BigInt & Value) friend
Serialization.
Definition at line 1015 of file BigInt.h.
Field Documentation
Bits
template<int32 NumBits, bool bSigned = true> uint32 TBigInt< NumBits, bSigned >::Bits[NumWords] private
All bits stored as an array of words.
Definition at line 38 of file BigInt.h.
Referenced by MultiplyFast().
One
template<int32 NumBits, bool bSigned> TBigInt< NumBits, bSigned > TBigInt< NumBits, bSigned >::One static
Definition at line 24 of file BigInt.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/BigInt.h