Unreal Engine 5.6 C++ API: UE::Geometry::FGeometrySelectionEditor Class Reference
UE::Geometry::FGeometrySelectionEditor Class Reference
FGeometrySelectionEditor is a utility/helper class used for modifying a FGeometrySelection.
#include "GeometrySelection.h"
Public Member Functions
DYNAMICMESH_API void ClearSelection (FGeometrySelectionDelta &DeltaOut)
Clear the Target Selection and return change information in DeltaOut.
template<typename ListType>
bool Deselect (const ListType &List, FGeometrySelectionDelta &DeltaOut)
Remove the items in the List from the Target Selection and return change information in DeltaOut.
EGeometryElementType GetElementType () const
bool GetIsTopologyIDFilteringEnabled () const
const FGeometrySelectionHitQueryConfig & GetQueryConfig () const
const FGeometrySelection & GetSelection () const
Access the Selection object this Editor is modifying.
EGeometryTopologyType GetTopologyType () const
DYNAMICMESH_API void Initialize (FGeometrySelection *TargetSelectionIn, bool bEnableTopologyIDFiltering)
Initialize the Editor with the given Selection.
DYNAMICMESH_API void Initialize (FGeometrySelection *TargetSelectionIn, const FGeometrySelectionHitQueryConfig &QueryConfigIn, bool bEnableTopologyIDFiltering)
Initialize the Editor with the given Selection.
DYNAMICMESH_API bool IsSelected (uint64 ID) const
DYNAMICMESH_API bool RemoveFromSelection (uint64 ID)
Remove ID from Selection.
DYNAMICMESH_API bool Replace (const FGeometrySelection &NewSelection, FGeometrySelectionDelta &DeltaOut)
Replace the current set of selected items with those in the NewSelection, and return change information in DeltaOut.
template<typename ListType>
bool Select (const ListType &List, FGeometrySelectionDelta &DeltaOut)
Add the items in the List to the Target Selection and return change information in DeltaOut.
bool Select (uint64 ID)
Add the items to the Target Selection.
DYNAMICMESH_API void UpdateQueryConfig (const FGeometrySelectionHitQueryConfig &NewConfig, bool bEnableTopologyIDFilteringIn)
Update the active QueryConfig for this SelectionEditor.
Protected Member Functions
DYNAMICMESH_API uint64 RemapToExistingTopologyID (uint64 ID, bool &bFoundOut) const
Protected Attributes
bool bEnableTopologyIDFiltering = false
FGeometrySelectionHitQueryConfig QueryConfig
FGeometrySelection * TargetSelection = nullptr
Detailed Description
FGeometrySelectionEditor is a utility/helper class used for modifying a FGeometrySelection.
The various functions can be used to add or remove to the Selection, while also tracking what changed, returned via FGeometrySelectionDelta structs.
In some cases (eg Polygroup selections on faces and edges), only the TopologyIDs are unique, and the same TopologyID may be paired with an arbitrary TriangleID/EdgeID. FGeometrySelection is currently not aware of this distinction, however it means when (for example) adding to a selection, a new uint64 ID should only be added if the TopologyID is unique, ie the ElementID bit should be ignored. FGeometrySelectionEditor can do this, by enabling TopologyIDFiltering in the various setup/config functions.
Note, however, this means that FGeometrySelectionEditor.IsSelected() must be used to determine whether an ID is selected, rather than Selection.Contains()
Definition at line 331 of file GeometrySelection.h.
Member Function Documentation
ClearSelection()
DYNAMICMESH_API void UE::Geometry::FGeometrySelectionEditor::ClearSelection (FGeometrySelectionDelta & DeltaOut)
Clear the Target Selection and return change information in DeltaOut.
References UE_API.
Deselect()
template<typename ListType> bool UE::Geometry::FGeometrySelectionEditor::Deselect (const ListType & List, FGeometrySelectionDelta & DeltaOut) inline
Remove the items in the List from the Target Selection and return change information in DeltaOut.
Definition at line 410 of file GeometrySelection.h.
References TArray< InElementType, InAllocatorType >::Add(), ID, UE::Geometry::FGeometrySelectionDelta::Removed, and RemoveFromSelection().
GetElementType()
EGeometryElementType UE::Geometry::FGeometrySelectionEditor::GetElementType () const inline
Returns
the Element Type of the Target Selection
Definition at line 352 of file GeometrySelection.h.
References TargetSelection.
GetIsTopologyIDFilteringEnabled()
bool UE::Geometry::FGeometrySelectionEditor::GetIsTopologyIDFilteringEnabled () const inline
Definition at line 359 of file GeometrySelection.h.
References bEnableTopologyIDFiltering.
Referenced by UE::Geometry::FGeometrySelectionPreview::FGeometrySelectionPreview().
GetQueryConfig()
const FGeometrySelectionHitQueryConfig & UE::Geometry::FGeometrySelectionEditor::GetQueryConfig () const inline
Returns
the active configuration for this Selection Editor, eg what type of element/topology is being selected. This is redundant w/ the above fields.
Definition at line 357 of file GeometrySelection.h.
References QueryConfig.
Referenced by UE::Geometry::FGeometrySelectionPreview::FGeometrySelectionPreview().
GetSelection()
const FGeometrySelection & UE::Geometry::FGeometrySelectionEditor::GetSelection () const inline
Access the Selection object this Editor is modifying.
Definition at line 378 of file GeometrySelection.h.
References TargetSelection.
Referenced by UE::Geometry::FGeometrySelectionPreview::FGeometrySelectionPreview().
GetTopologyType()
EGeometryTopologyType UE::Geometry::FGeometrySelectionEditor::GetTopologyType () const inline
Returns
the Topology Type of the Target Selection
Definition at line 354 of file GeometrySelection.h.
References TargetSelection.
Initialize() [1/2]
DYNAMICMESH_API void UE::Geometry::FGeometrySelectionEditor::Initialize (FGeometrySelection * TargetSelectionIn, bool bEnableTopologyIDFiltering)
Initialize the Editor with the given Selection.
The TargetSelectionIn must live longer than the FGeometrySelectionEditor
References bEnableTopologyIDFiltering, and UE_API.
Initialize() [2/2]
DYNAMICMESH_API void UE::Geometry::FGeometrySelectionEditor::Initialize (FGeometrySelection * TargetSelectionIn, const FGeometrySelectionHitQueryConfig & QueryConfigIn, bool bEnableTopologyIDFiltering)
Initialize the Editor with the given Selection.
The TargetSelectionIn must live longer than the FGeometrySelectionEditor
References bEnableTopologyIDFiltering, and UE_API.
IsSelected()
DYNAMICMESH_API bool UE::Geometry::FGeometrySelectionEditor::IsSelected (uint64 ID) const
Returns
true if the given ID is currently selected in the Target Selection
References ID, and UE_API.
Referenced by Select(), and Select().
RemapToExistingTopologyID()
DYNAMICMESH_API uint64 UE::Geometry::FGeometrySelectionEditor::RemapToExistingTopologyID (uint64 ID, bool & bFoundOut) const protected
References ID, and UE_API.
RemoveFromSelection()
DYNAMICMESH_API bool UE::Geometry::FGeometrySelectionEditor::RemoveFromSelection (uint64 ID)
Remove ID from Selection.
References ID, and UE_API.
Referenced by Deselect().
Replace()
DYNAMICMESH_API bool UE::Geometry::FGeometrySelectionEditor::Replace (const FGeometrySelection & NewSelection, FGeometrySelectionDelta & DeltaOut)
Replace the current set of selected items with those in the NewSelection, and return change information in DeltaOut.
References UE_API.
Select() [1/2]
template<typename ListType> bool UE::Geometry::FGeometrySelectionEditor::Select (const ListType & List, FGeometrySelectionDelta & DeltaOut) inline
Add the items in the List to the Target Selection and return change information in DeltaOut.
Definition at line 393 of file GeometrySelection.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FGeometrySelectionDelta::Added, ID, IsSelected(), and TargetSelection.
Select() [2/2]
bool UE::Geometry::FGeometrySelectionEditor::Select (uint64 ID) inline
Add the items to the Target Selection.
Definition at line 381 of file GeometrySelection.h.
References ID, IsSelected(), and TargetSelection.
UpdateQueryConfig()
DYNAMICMESH_API void UE::Geometry::FGeometrySelectionEditor::UpdateQueryConfig (const FGeometrySelectionHitQueryConfig & NewConfig, bool bEnableTopologyIDFilteringIn)
Update the active QueryConfig for this SelectionEditor.
This is necessary to keep it in sync w/ the TargetSelection, if the ElementType or TopologyType are modified. This perhaps should be revisited as they basically always need to be the same...
References UE_API.
Field Documentation
bEnableTopologyIDFiltering
bool UE::Geometry::FGeometrySelectionEditor::bEnableTopologyIDFiltering = false protected
Definition at line 432 of file GeometrySelection.h.
Referenced by GetIsTopologyIDFilteringEnabled(), Initialize(), and Initialize().
QueryConfig
FGeometrySelectionHitQueryConfig UE::Geometry::FGeometrySelectionEditor::QueryConfig protected
Definition at line 430 of file GeometrySelection.h.
Referenced by GetQueryConfig().
TargetSelection
FGeometrySelection* UE::Geometry::FGeometrySelectionEditor::TargetSelection = nullptr protected
Definition at line 429 of file GeometrySelection.h.
Referenced by GetElementType(), GetSelection(), GetTopologyType(), Select(), and Select().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Selections/GeometrySelection.h