Unreal Engine 5.6 C++ API: IProjectExternalContentInterface Class Reference
IProjectExternalContentInterface Class Reference abstract
Interface to manage project references to external content.
#include "IProjectExternalContentInterface.h"
Public Member Functions
virtual void AddExternalContent (const FString &VersePath, FAddExternalContentComplete CompleteCallback=FAddExternalContentComplete())=0
Add a reference to external content to the project and asynchronously downloads/loads the external content.
DECLARE_DELEGATE_OneParam (FRemoveExternalContentComplete, bool)
Called upon RemoveExternalContent completion.
DECLARE_DELEGATE_TwoParams (FAddExternalContentComplete, bool, const TArray< TSharedRef< IPlugin > > &)
Called upon AddExternalContent completion.
virtual TArray< FString > GetExternalContentVersePaths () const =0
Return the list of external content Verse paths referenced by the project.
virtual bool HasExternalContent (const FString &VersePath) const =0
Return whether the specified external content is referenced by the project.
virtual bool IsEnabled () const =0
Return whether the project can reference external content.
virtual bool IsExternalContentLoaded (const FString &VersePath) const =0
Return whether the specified external content is loaded (and referenced by the project)
void RemoveExternalContent (const FString &VersePath, FRemoveExternalContentComplete CompleteCallback=FRemoveExternalContentComplete())
virtual void RemoveExternalContent (TConstArrayView< FString > VersePaths, FRemoveExternalContentComplete CompleteCallback=FRemoveExternalContentComplete())=0
Remove references to external content from the project and unloads the external content.
UE_DEPRECATED (5.6, "GetExternalContentIds is deprecated, use GetExternalContentVersePaths instead") TArray< FString > GetExternalContentIds() const
Detailed Description
Interface to manage project references to external content.
Definition at line 9 of file IProjectExternalContentInterface.h.
Member Function Documentation
AddExternalContent()
virtual void IProjectExternalContentInterface::AddExternalContent (const FString & VersePath, FAddExternalContentComplete CompleteCallback = FAddExternalContentComplete()) pure virtual
Add a reference to external content to the project and asynchronously downloads/loads the external content.
Parameters
VersePath External content Verse path
CompleteCallback See FAddExternalContentComplete
DECLARE_DELEGATE_OneParam()
IProjectExternalContentInterface::DECLARE_DELEGATE_OneParam (FRemoveExternalContentComplete , bool)
Called upon RemoveExternalContent completion.
Parameters
bSuccess Whether the external content was successfully removed from the project (could be canceled by the user)
DECLARE_DELEGATE_TwoParams()
IProjectExternalContentInterface::DECLARE_DELEGATE_TwoParams (FAddExternalContentComplete , bool , const TArray< TSharedRef< IPlugin > > &)
Called upon AddExternalContent completion.
Parameters
bSuccess Whether the external content was successfully added to the project
Plugins List of loaded plugins hosting the external content
GetExternalContentVersePaths()
virtual TArray< FString > IProjectExternalContentInterface::GetExternalContentVersePaths () const pure virtual
Return the list of external content Verse paths referenced by the project.
Referenced by UE_DEPRECATED().
HasExternalContent()
virtual bool IProjectExternalContentInterface::HasExternalContent (const FString & VersePath) const pure virtual
Return whether the specified external content is referenced by the project.
Parameters
VersePath External content Verse path
IsEnabled()
virtual bool IProjectExternalContentInterface::IsEnabled () const pure virtual
Return whether the project can reference external content.
IsExternalContentLoaded()
virtual bool IProjectExternalContentInterface::IsExternalContentLoaded (const FString & VersePath) const pure virtual
Return whether the specified external content is loaded (and referenced by the project)
Parameters
VersePath External content Verse path
RemoveExternalContent() [1/2]
void IProjectExternalContentInterface::RemoveExternalContent (const FString & VersePath, FRemoveExternalContentComplete CompleteCallback = FRemoveExternalContentComplete()) inline
Definition at line 60 of file IProjectExternalContentInterface.h.
References MoveTemp(), and RemoveExternalContent().
RemoveExternalContent() [2/2]
virtual void IProjectExternalContentInterface::RemoveExternalContent (TConstArrayView< FString > VersePaths, FRemoveExternalContentComplete CompleteCallback = FRemoveExternalContentComplete()) pure virtual
Remove references to external content from the project and unloads the external content.
Parameters
VersePaths External content Verse paths
CompleteCallback See FRemoveExternalContentComplete
Referenced by RemoveExternalContent().
UE_DEPRECATED()
IProjectExternalContentInterface::UE_DEPRECATED (5. 6, "GetExternalContentIds is deprecated, use GetExternalContentVersePaths instead") const inline
Definition at line 30 of file IProjectExternalContentInterface.h.
References GetExternalContentVersePaths().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/IProjectExternalContentInterface.h