Unreal Engine 5.6 C++ API: TShear2< T > Class Template Reference
TShear2< T > Class Template Reference
Represents a 2D shear: [1 YY] [XX 1] XX represents a shear parallel to the X axis.
#include "TransformCalculus2D.h"
Public Types
using FReal = T
using Vector2Type = UE::Math::TVector2<T>
Public Member Functions
TShear2 ()
Ctor.
template<typename VType>
TShear2 (const UE::Math::TVector2< VType > &InShear)
Ctor.
TShear2 (T ShearX, T ShearY)
Ctor.
TMatrix2x2< T > Concatenate (const TShear2 &RHS) const
Concatenate two shears.
const Vector2Type & GetVector () const
Access to the underlying FVector2D that stores the scale.
TMatrix2x2< T > Inverse () const
Invert the shear.
bool operator!= (const TShear2 &Other) const
Inequality.
bool operator== (const TShear2 &Other) const
Equality.
template<typename ArgType>
UE::Math::TVector2< ArgType > TransformPoint (const UE::Math::TVector2< ArgType > &Point) const
Transform 2D Point [X Y] * [1 YY] == [X+Y*XX Y+X*YY] [XX 1].
template<typename ArgType>
UE::Math::TVector2< ArgType > TransformVector (const UE::Math::TVector2< ArgType > &Vector) const
Transform 2D Vector.
Static Public Member Functions
template<typename VType>
static TShear2 FromShearAngles (const UE::Math::TVector2< VType > &InShearAngles)
Generates a shear structure based on angles instead of slope.
Private Attributes
Vector2Type Shear
Underlying storage of the 2D shear.
Detailed Description
template<typename T>
class TShear2< T >
Represents a 2D shear: [1 YY] [XX 1] XX represents a shear parallel to the X axis.
YY represents a shear parallel to the Y axis.
Definition at line 198 of file TransformCalculus2D.h.
Member Typedef Documentation
FReal
template<typename T> using TShear2< T >::FReal = T
Definition at line 203 of file TransformCalculus2D.h.
Vector2Type
template<typename T> using TShear2< T >::Vector2Type = UE::Math::TVector2<T>
Definition at line 204 of file TransformCalculus2D.h.
Constructor & Destructor Documentation
TShear2() [1/3]
template<typename T> TShear2< T >::TShear2 () inline
Ctor.
initialize to an identity.
Definition at line 207 of file TransformCalculus2D.h.
Referenced by Concatenate(), and TShear2< float >::FromShearAngles().
TShear2() [2/3]
template<typename T> TShear2< T >::TShear2 (T ShearX, T ShearY) inline explicit
Ctor.
initialize from a set of shears parallel to the X and Y axis, respectively.
Definition at line 209 of file TransformCalculus2D.h.
TShear2() [3/3]
template<typename T> template<typename VType> TShear2< T >::TShear2 (const UE::Math::TVector2< VType > & InShear) inline explicit
Ctor.
initialize from a 2D vector representing a set of shears parallel to the X and Y axis, respectively.
Definition at line 212 of file TransformCalculus2D.h.
Member Function Documentation
Concatenate()
template<typename T> TMatrix2x2< T > TShear2< T >::Concatenate (const TShear2< T > & RHS) const inline nodiscard
Concatenate two shears.
The result is NOT a shear, but must be represented by a generalized 2x2 transform. Defer the implementation until we can declare a 2x2 matrix. [1 YYA] * [1 YYB] == [1+YYA*XXB YYB*YYA] [XXA 1] [XXB 1] [XXA+XXB XXA*XXB+1]
Definition at line 633 of file TransformCalculus2D.h.
References TShear2(), Shear, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
FromShearAngles()
template<typename T> template<typename VType> TShear2 TShear2< T >::FromShearAngles (const UE::Math::TVector2< VType > & InShearAngles) inline static nodiscard
Generates a shear structure based on angles instead of slope.
Parameters
InShearAngles The angles of shear.
Returns
the sheare structure.
Definition at line 220 of file TransformCalculus2D.h.
GetVector()
template<typename T> const Vector2Type & TShear2< T >::GetVector () const inline nodiscard
Access to the underlying FVector2D that stores the scale.
Definition at line 278 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::TMatrix2x2().
Inverse()
template<typename T> TMatrix2x2< T > TShear2< T >::Inverse () const inline nodiscard
Invert the shear.
The result is NOT a shear, but must be represented by a generalized 2x2 transform. Defer the implementation until we can declare a 2x2 matrix. [1 YY]^-1 == 1/(1-YY*XX) * [1 -YY] [XX 1] [-XX 1]
Definition at line 645 of file TransformCalculus2D.h.
References Shear.
operator!=()
template<typename T> bool TShear2< T >::operator!= (const TShear2< T > & Other) const inline nodiscard
Inequality.
Definition at line 272 of file TransformCalculus2D.h.
operator==()
template<typename T> bool TShear2< T >::operator== (const TShear2< T > & Other) const inline nodiscard
Equality.
Definition at line 266 of file TransformCalculus2D.h.
Referenced by TShear2< float >::operator!=().
TransformPoint()
template<typename T> template<typename ArgType> UE::Math::TVector2< ArgType > TShear2< T >::TransformPoint (const UE::Math::TVector2< ArgType > & Point) const inline nodiscard
Transform 2D Point [X Y] * [1 YY] == [X+Y*XX Y+X*YY] [XX 1].
Definition at line 237 of file TransformCalculus2D.h.
Referenced by TShear2< float >::TransformVector().
TransformVector()
template<typename T> template<typename ArgType> UE::Math::TVector2< ArgType > TShear2< T >::TransformVector (const UE::Math::TVector2< ArgType > & Vector) const inline nodiscard
Transform 2D Vector.
Definition at line 243 of file TransformCalculus2D.h.
Field Documentation
Shear
template<typename T> Vector2Type TShear2< T >::Shear private
Underlying storage of the 2D shear.
Definition at line 285 of file TransformCalculus2D.h.
Referenced by Concatenate(), and Inverse().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/TransformCalculus2D.h