Unreal Engine 5.6 C++ API: ISlateInputManager Class Reference
ISlateInputManager Class Reference abstract
Interface for a Slate Input Mapping.
#include "SlateApplication.h"
Public Member Functions
virtual ~ISlateInputManager ()=default
virtual FInputDeviceId GetInputDeviceIdForKeyboard () const =0
virtual FInputDeviceId GetInputDeviceIdForMouse () const =0
virtual int32 GetUserIndexForController (int32 ControllerId) const
virtual TOptional< int32 > GetUserIndexForController (int32 ControllerId, FKey InKey) const =0
virtual TOptional< int32 > GetUserIndexForInputDevice (FInputDeviceId InputDeviceId) const
virtual int32 GetUserIndexForKeyboard () const =0
virtual int32 GetUserIndexForMouse () const =0
virtual TOptional< int32 > GetUserIndexForPlatformUser (FPlatformUserId PlatformUser) const
Detailed Description
Interface for a Slate Input Mapping.
Definition at line 119 of file SlateApplication.h.
Constructor & Destructor Documentation
~ISlateInputManager()
virtual ISlateInputManager::~ISlateInputManager () virtual default
Member Function Documentation
GetInputDeviceIdForKeyboard()
virtual FInputDeviceId ISlateInputManager::GetInputDeviceIdForKeyboard () const pure virtual
Implemented in FSlateDefaultInputMapping.
GetInputDeviceIdForMouse()
virtual FInputDeviceId ISlateInputManager::GetInputDeviceIdForMouse () const pure virtual
Implemented in FSlateDefaultInputMapping.
GetUserIndexForController() [1/2]
virtual int32 ISlateInputManager::GetUserIndexForController (int32 ControllerId) const inline virtual
Reimplemented in FSlateDefaultInputMapping.
Definition at line 143 of file SlateApplication.h.
GetUserIndexForController() [2/2]
virtual TOptional< int32 > ISlateInputManager::GetUserIndexForController (int32 ControllerId, FKey InKey) const pure virtual
Implemented in FSlateDefaultInputMapping.
GetUserIndexForInputDevice()
virtual TOptional< int32 > ISlateInputManager::GetUserIndexForInputDevice (FInputDeviceId InputDeviceId) const inline virtual
Definition at line 131 of file SlateApplication.h.
References IPlatformInputDeviceMapper::Get(), and GetUserIndexForPlatformUser().
GetUserIndexForKeyboard()
virtual int32 ISlateInputManager::GetUserIndexForKeyboard () const pure virtual
Implemented in FSlateDefaultInputMapping.
GetUserIndexForMouse()
virtual int32 ISlateInputManager::GetUserIndexForMouse () const pure virtual
Implemented in FSlateDefaultInputMapping.
GetUserIndexForPlatformUser()
virtual TOptional< int32 > ISlateInputManager::GetUserIndexForPlatformUser (FPlatformUserId PlatformUser) const inline virtual
Definition at line 137 of file SlateApplication.h.
References FPlatformUserId::GetInternalId().
Referenced by GetUserIndexForInputDevice().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Application/SlateApplication.h