Unreal Engine 5.6 C++ API: FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler Class Reference
FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler Class Reference abstract
#include "DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h"
Public Member Functions
FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler (UDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase *InPolicyObject)
virtual bool IsCaptureTypeSupported (UMediaCapture *MediaCapture) const override
Returns true if specified media capture type can be synchonized by the policy implementation.
virtual bool IsRunning () override final
Returns true if currently synchronizing a media output.
virtual bool StartSynchronization (UMediaCapture *MediaCapture, const FString &MediaId) override
Starts synchronization of specific output stream (capture device).
virtual void StopSynchronization () override
Stops synchronization of specific output stream (capture device).
virtual void Synchronize ()=0
Children implement their own sync approaches.
Public Member Functions inherited from IDisplayClusterMediaOutputSynchronizationPolicyHandler
virtual ~IDisplayClusterMediaOutputSynchronizationPolicyHandler ()=default
Destructor.
virtual TSubclassOf< UDisplayClusterMediaOutputSynchronizationPolicy > GetPolicyClass () const =0
Returns the policy config class used to create this policy handler.
Public Member Functions inherited from TSharedFromThis< IDisplayClusterMediaOutputSynchronizationPolicyHandler >
TSharedRef< IDisplayClusterMediaOutputSynchronizationPolicyHandler, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDisplayClusterMediaOutputSynchronizationPolicyHandler, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
TSharedPtr< IDisplayClusterGenericBarriersClient > GetBarrierClient ()
Returns barrier client created for this sync policy.
const FString & GetBarrierId () const
Get Barrier ID for this sync policy.
FString GetMediaDeviceId () const
Returns media device ID being synchronized.
const FString & GetThreadMarker () const
Get thread marker for this sync policy.
virtual bool InitializeBarrier (const FString &SyncInstanceId)
Initializes dynamic barrier on the primary node.
void SyncThreadOnBarrier ()
Synchronizes calling thread at the barrier.
UE_DEPRECATED (5.6, "This method has been deprecated. Please use another 'GetBarrierClient' that returns TSharedPtr.") IDisplayClusterGenericBarriersClient *const GetBarrierClient() const
Returns barrier client created for this sync policy.
Protected Member Functions inherited from TSharedFromThis< IDisplayClusterMediaOutputSynchronizationPolicyHandler >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
int32 BarrierTimeoutMs = 3000
Barrier timeout (ms)
TObjectPtr< UMediaCapture > CapturingDevice
Capture device being used.
Private Member Functions
FString GenerateBarrierName () const
Generates name of the dynamic barrier.
void GenerateSyncCallersMapping (TMap< FString, TSet< FString > > &OutMarkers) const
Generates per-node sync callers mapping.
void LogSyncCallersMapping (const TMap< FString, TSet< FString > > &OutNodeToSyncCallers) const
Auxiliary function to log custom barrier callers mapping.
void ProcessMediaSynchronizationCallback ()
Handles media capture sync callbacks.
void ReleaseBarrier ()
Releases dynamic barrier on the primary node.
UE_DEPRECATED (5.6, "This method has been deprecated. Please use 'GenerateSyncCallersMapping'.") void GenerateListOfThreadMarkers(TArray< FString > &OutMarkers) const
Private Attributes
FString BarrierId
Unique barrier name to use.
bool bIsRunning = false
Is synchronization currently active.
TSharedPtr< IDisplayClusterGenericBarriersClient > EthernetBarrierClient
Generic barriers API.
FString MediaDeviceId
ID of media device being synchronized.
FString ThreadMarker
Unique thread (caller) marker to be used on the barrier.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IDisplayClusterMediaOutputSynchronizationPolicyHandler >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 15 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
Constructor & Destructor Documentation
FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler()
FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler (UDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase * InPolicyObject)
Member Function Documentation
GenerateBarrierName()
FString FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::GenerateBarrierName () const private
Generates name of the dynamic barrier.
GenerateSyncCallersMapping()
void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::GenerateSyncCallersMapping (TMap< FString, TSet< FString > > & OutMarkers) const private
Generates per-node sync callers mapping.
GetBarrierClient()
TSharedPtr< IDisplayClusterGenericBarriersClient > FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::GetBarrierClient () protected
Returns barrier client created for this sync policy.
Referenced by UE_DEPRECATED().
GetBarrierId()
const FString & FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::GetBarrierId () const protected
Get Barrier ID for this sync policy.
GetMediaDeviceId()
FString FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::GetMediaDeviceId () const protected
Returns media device ID being synchronized.
References GetMediaDeviceId().
Referenced by GetMediaDeviceId().
GetThreadMarker()
const FString & FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::GetThreadMarker () const protected
Get thread marker for this sync policy.
InitializeBarrier()
virtual bool FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::InitializeBarrier (const FString & SyncInstanceId) protected virtual
Initializes dynamic barrier on the primary node.
References InitializeBarrier().
Referenced by InitializeBarrier().
IsCaptureTypeSupported()
virtual bool FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::IsCaptureTypeSupported (UMediaCapture * MediaCapture) const override virtual
Returns true if specified media capture type can be synchonized by the policy implementation.
Implements IDisplayClusterMediaOutputSynchronizationPolicyHandler.
References IsCaptureTypeSupported().
Referenced by IsCaptureTypeSupported().
IsRunning()
virtual bool FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::IsRunning () final override virtual
Returns true if currently synchronizing a media output.
Implements IDisplayClusterMediaOutputSynchronizationPolicyHandler.
LogSyncCallersMapping()
void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::LogSyncCallersMapping (const TMap< FString, TSet< FString > > & OutNodeToSyncCallers) const private
Auxiliary function to log custom barrier callers mapping.
ProcessMediaSynchronizationCallback()
void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::ProcessMediaSynchronizationCallback () private
Handles media capture sync callbacks.
ReleaseBarrier()
void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::ReleaseBarrier () private
Releases dynamic barrier on the primary node.
StartSynchronization()
virtual bool FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::StartSynchronization (UMediaCapture * MediaCapture, const FString & MediaId) override virtual
Starts synchronization of specific output stream (capture device).
Returns false if failed.
Implements IDisplayClusterMediaOutputSynchronizationPolicyHandler.
Reimplemented in FDisplayClusterMediaOutputSynchronizationPolicyVblankHandler.
StopSynchronization()
virtual void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::StopSynchronization () override virtual
Stops synchronization of specific output stream (capture device).
Implements IDisplayClusterMediaOutputSynchronizationPolicyHandler.
Synchronize()
virtual void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::Synchronize () pure virtual
Children implement their own sync approaches.
Implemented in FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierHandler, and FDisplayClusterMediaOutputSynchronizationPolicyThresholdBaseHandler.
References Synchronize().
Referenced by Synchronize().
SyncThreadOnBarrier()
void FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::SyncThreadOnBarrier () protected
Synchronizes calling thread at the barrier.
References SyncThreadOnBarrier().
Referenced by SyncThreadOnBarrier().
UE_DEPRECATED() [1/2]
FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::UE_DEPRECATED (5. 6, "This method has been deprecated. Please use 'GenerateSyncCallersMapping'.") const & inline private
Definition at line 77 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
UE_DEPRECATED() [2/2]
FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::UE_DEPRECATED (5. 6, "This method has been deprecated. Please use another 'GetBarrierClient' that returns TSharedPtr.") const inline protected
Returns barrier client created for this sync policy.
Definition at line 48 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
References EthernetBarrierClient, GetBarrierClient(), and UE_DEPRECATED().
Referenced by UE_DEPRECATED().
Field Documentation
BarrierId
FString FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::BarrierId private
Unique barrier name to use.
Definition at line 100 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
BarrierTimeoutMs
int32 FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::BarrierTimeoutMs = 3000 protected
Barrier timeout (ms)
Definition at line 90 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
bIsRunning
bool FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::bIsRunning = false private
Is synchronization currently active.
Definition at line 94 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
CapturingDevice
TObjectPtr<UMediaCapture> FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::CapturingDevice protected
Capture device being used.
Definition at line 87 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
EthernetBarrierClient
TSharedPtr<IDisplayClusterGenericBarriersClient> FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::EthernetBarrierClient private
Generic barriers API.
Definition at line 106 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
Referenced by UE_DEPRECATED().
MediaDeviceId
FString FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::MediaDeviceId private
ID of media device being synchronized.
Definition at line 97 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
ThreadMarker
FString FDisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBaseHandler::ThreadMarker private
Unique thread (caller) marker to be used on the barrier.
Definition at line 103 of file DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterMedia/Public/Synchronization/DisplayClusterMediaOutputSynchronizationPolicyEthernetBarrierBase.h