Unreal Engine 5.6 C++ API: UVectorFieldComponent Class Reference
UVectorFieldComponent Class Reference
#include "VectorFieldComponent.h"
Public Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials) const override
virtual void OnRegister () override
virtual void OnUnregister () override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void SendRenderTransform_Concurrent () override
Data Fields
class FFXSystemInterface * FXSystem
The FX system with which this vector field is associated.
class FVectorFieldInstance * VectorFieldInstance
The instance of this vector field registered with the FX system.
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UVectorField > VectorField
The vector field asset.
UPROPERTY() uint32 bPreviewVectorField UFUNCTION () virtual void SetIntensity(float NewIntensity)
If true, the vector field is only used for preview visualizations.
UPROPERTY () float Intensity
The intensity at which the vector field is applied.
UPROPERTY () float Tightness
How tightly particles follow the vector field.
Detailed Description
Definition at line 18 of file VectorFieldComponent.h.
Member Function Documentation
CalcBounds()
virtual FBoxSphereBounds UVectorFieldComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
References CalcBounds().
Referenced by CalcBounds().
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UVectorFieldComponent::CreateSceneProxy () override virtual
References CreateSceneProxy().
Referenced by CreateSceneProxy().
GENERATED_UCLASS_BODY()
UVectorFieldComponent::GENERATED_UCLASS_BODY () private
The vector field asset.
References Category, and UPROPERTY().
GetUsedMaterials()
virtual void UVectorFieldComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials) const override virtual
References GetUsedMaterials().
Referenced by GetUsedMaterials().
OnRegister()
virtual void UVectorFieldComponent::OnRegister () override virtual
References OnRegister().
Referenced by OnRegister().
OnUnregister()
virtual void UVectorFieldComponent::OnUnregister () override virtual
References OnUnregister().
Referenced by OnUnregister().
PostEditChangeProperty()
virtual void UVectorFieldComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
SendRenderTransform_Concurrent()
virtual void UVectorFieldComponent::SendRenderTransform_Concurrent () override virtual
References SendRenderTransform_Concurrent().
Referenced by SendRenderTransform_Concurrent().
UFUNCTION()
UPROPERTY() uint32 bPreviewVectorField UVectorFieldComponent::UFUNCTION () private
If true, the vector field is only used for preview visualizations.
Set the intensity of the vector field.
Parameters
NewIntensity - The new intensity of the vector field.
References Category, and UFUNCTION().
Referenced by UFUNCTION().
UPROPERTY() [1/2]
UVectorFieldComponent::UPROPERTY () private
The intensity at which the vector field is applied.
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/2]
UVectorFieldComponent::UPROPERTY () private
How tightly particles follow the vector field.
References Category, transient, and UPROPERTY().
Field Documentation
FXSystem
class FFXSystemInterface* UVectorFieldComponent::FXSystem
The FX system with which this vector field is associated.
Definition at line 49 of file VectorFieldComponent.h.
VectorFieldInstance
class FVectorFieldInstance* UVectorFieldComponent::VectorFieldInstance
The instance of this vector field registered with the FX system.
Definition at line 51 of file VectorFieldComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/VectorFieldComponent.h