Unreal Engine 5.6 C++ API: UE::FInheritedContextBase Class Reference
UE::FInheritedContextBase Class Reference
#include "InheritedContext.h"
Public Member Functions
void CaptureInheritedContext ()
FInheritedContextScope RestoreInheritedContext ()
Detailed Description
Definition at line 117 of file InheritedContext.h.
Member Function Documentation
CaptureInheritedContext()
void UE::FInheritedContextBase::CaptureInheritedContext () inline
Definition at line 121 of file InheritedContext.h.
References MemoryTrace_GetActiveTag(), and UE_TRACE_METADATA_SAVE_STACK.
Referenced by FRenderCommandPipe::FCommand::FCommand(), FRenderThreadCommandPipe::FCommand::FCommand(), FIoRequestImpl::FIoRequestImpl(), UE::Tasks::Private::FTaskBase::Init(), FAsyncTaskBase::Start(), and FAutoDeleteAsyncTask< FCancelIORequestsTask >::Start().
RestoreInheritedContext()
FInheritedContextScope UE::FInheritedContextBase::RestoreInheritedContext () nodiscard
Referenced by FAsyncTaskBase::DoWork(), FAutoDeleteAsyncTask< FCancelIORequestsTask >::DoWork(), ENUM_CLASS_FLAGS(), UE::FPlatformIoDispatcherBase::ScatterDecodedBlock(), and UE::Tasks::Private::FTaskBase::TryExecuteTask().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/InheritedContext.h