Unreal Engine 5.6 C++ API: UUVEditorTexelDensityActionSettings Class Reference
UUVEditorTexelDensityActionSettings Class Reference
#include "UVEditorTexelDensityTool.h"
Public Member Functions
void Initialize (UUVEditorTexelDensityTool *ParentToolIn)
void PostAction (ETexelDensityToolAction Action)
void SampleTexelDensity ()
Data Fields
TWeakObjectPtr< UUVEditorTexelDensityTool > ParentTool
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Definition at line 60 of file UVEditorTexelDensityTool.h.
Member Function Documentation
Initialize()
void UUVEditorTexelDensityActionSettings::Initialize (UUVEditorTexelDensityTool * ParentToolIn) inline
Definition at line 67 of file UVEditorTexelDensityTool.h.
References Initialize(), and ParentTool.
Referenced by Initialize().
PostAction()
void UUVEditorTexelDensityActionSettings::PostAction (ETexelDensityToolAction Action)
References Category.
SampleTexelDensity()
void UUVEditorTexelDensityActionSettings::SampleTexelDensity ()
References SampleTexelDensity(), and UCLASS.
Referenced by SampleTexelDensity().
Field Documentation
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorTexelDensityActionSettings::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 62 of file UVEditorTexelDensityTool.h.
ParentTool
TWeakObjectPtr<UUVEditorTexelDensityTool> UUVEditorTexelDensityActionSettings::ParentTool
Definition at line 65 of file UVEditorTexelDensityTool.h.
Referenced by Initialize().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/UVEditorTexelDensityTool.h