Unreal Engine 5.6 C++ API: LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues > Class Template Reference
LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues > Class Template Reference
#include "LocalQueue.h"
Data Structures
class TLocalQueue
Public Member Functions
TLocalQueueRegistry ()
FTask * DequeueGlobal (bool GetBackGroundTasks=true)
FTask * DequeueSteal (bool GetBackGroundTasks)
void Enqueue (FTask *Item, uint32 PriorityIndex)
void Reset ()
Private Types
using DequeueHazard = typename FOverflowQueueType::DequeueHazard
using FLocalQueueType = LocalQueue_Impl::TWorkStealingQueue2<FTask, NumLocalItems>
using FOverflowQueueType = FAAArrayQueue<FTask>
Private Member Functions
void AddLocalQueue (TLocalQueue *QueueToAdd)
FTask * StealItem (uint32 &CachedRandomIndex, uint32 &CachedPriorityIndex, bool GetBackGroundTasks)
Static Private Member Functions
static uint32 Rand ()
Private Attributes
std::atomic< TLocalQueue * > LocalQueues [MaxLocalQueues] { nullptr }
std::atomic< uint32 > NumLocalQueues {0}
FOverflowQueueType OverflowQueues [uint32(ETaskPriority::Count)]
Detailed Description
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024>
class LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >
Definition at line 156 of file LocalQueue.h.
Member Typedef Documentation
DequeueHazard
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> using LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::DequeueHazard = typename FOverflowQueueType::DequeueHazard private
Definition at line 172 of file LocalQueue.h.
FLocalQueueType
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> using LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::FLocalQueueType = LocalQueue_Impl::TWorkStealingQueue2<FTask, NumLocalItems> private
Definition at line 170 of file LocalQueue.h.
FOverflowQueueType
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> using LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::FOverflowQueueType = FAAArrayQueue<FTask> private
Definition at line 171 of file LocalQueue.h.
Constructor & Destructor Documentation
TLocalQueueRegistry()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueueRegistry () inline
Definition at line 283 of file LocalQueue.h.
Member Function Documentation
AddLocalQueue()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> void LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::AddLocalQueue (TLocalQueue * QueueToAdd) inline private
Definition at line 289 of file LocalQueue.h.
References Fatal, LocalQueues, NumLocalQueues, TEXT, and UE_CLOG.
DequeueGlobal()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FTask * LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::DequeueGlobal (bool GetBackGroundTasks = true) inline
Definition at line 339 of file LocalQueue.h.
References LowLevelTasks::Count, LowLevelTasks::ForegroundCount, Item, and OverflowQueues.
DequeueSteal()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FTask * LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::DequeueSteal (bool GetBackGroundTasks) inline
Definition at line 353 of file LocalQueue.h.
References Rand(), and StealItem().
Enqueue()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> void LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::Enqueue (FTask * Item, uint32 PriorityIndex) inline
Definition at line 330 of file LocalQueue.h.
References check, LowLevelTasks::Count, Item, and OverflowQueues.
Rand()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> uint32 LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::Rand () inline static private
Definition at line 158 of file LocalQueue.h.
References FAndroidTime::Cycles(), and State.
Referenced by DequeueSteal(), and LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::DequeueSteal().
Reset()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> void LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::Reset () inline
Definition at line 366 of file LocalQueue.h.
References LocalQueues, and NumLocalQueues.
StealItem()
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FTask * LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::StealItem (uint32 & CachedRandomIndex, uint32 & CachedPriorityIndex, bool GetBackGroundTasks) inline private
Definition at line 300 of file LocalQueue.h.
References LowLevelTasks::Count, LowLevelTasks::ForegroundCount, LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::TLocalQueue::InvalidIndex, Item, LocalQueues, and NumLocalQueues.
Referenced by DequeueSteal().
Field Documentation
LocalQueues
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> std::atomic<TLocalQueue*> LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::LocalQueues[MaxLocalQueues] { nullptr } private
Definition at line 379 of file LocalQueue.h.
Referenced by AddLocalQueue(), Reset(), and StealItem().
NumLocalQueues
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> std::atomic<uint32> LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::NumLocalQueues {0} private
Definition at line 380 of file LocalQueue.h.
Referenced by AddLocalQueue(), Reset(), and StealItem().
OverflowQueues
template<uint32 NumLocalItems = 1024, uint32 MaxLocalQueues = 1024> FOverflowQueueType LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::OverflowQueues[uint32(ETaskPriority::Count)] private
Definition at line 378 of file LocalQueue.h.
Referenced by DequeueGlobal(), and Enqueue().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/Fundamental/LocalQueue.h