Unreal Engine 5.6 C++ API: UE::Geometry::FMeshRegionGraph Class Reference
UE::Geometry::FMeshRegionGraph Class Reference
FMeshRegionGraph represents neighbourhood relationships between mesh patches.
#include "MeshRegionGraph.h"
Data Structures
struct FNeighbour
struct FRegion
Public Member Functions
DYNAMICMESH_API bool AreRegionsConnected (int32 RegionAIndex, int32 RegionBIndex) const
bool AreTrianglesConnected (int32 TriangleA, int32 TriangleB) const
DYNAMICMESH_API void BuildFromComponents (const FDynamicMesh3 &Mesh, const FMeshConnectedComponents &Components, TFunctionRef< int32(int32)> ExternalIDFunc, TFunctionRef< bool(int32, int32)> TrisConnectedPredicate=[](int, int) { return true;})
Build a region graph for a Mesh using the given ConnectedComponents.
DYNAMICMESH_API void BuildFromTriangleSets (const FDynamicMesh3 &Mesh, const TArray< TArray< int32 > > &TriangleSets, TFunctionRef< int32(int32)> ExternalIDFunc, TFunctionRef< bool(int32, int32)> TrisConnectedPredicate=[](int, int) { return true;})
Build a region graph for a Mesh using the given triangle sets.
int32 GetExternalID (int32 RegionIdx) const
DYNAMICMESH_API TArray< int32 > GetNeighbours (int32 RegionIdx) const
int32 GetRegionTriCount (int32 RegionIdx) const
const TArray< int32 > & GetRegionTris (int32 RegionIdx) const
int32 IsRegion (int32 RegionIdx) const
int32 MaxRegionIndex () const
DYNAMICMESH_API bool MergeRegion (int32 RemoveRgnIdx, int32 MergeToRgnIdx)
Merge one existing Region into another.
DYNAMICMESH_API bool MergeSmallRegions (int32 SmallThreshold, TFunctionRef< float(int32 SmallRgnIdx, int32 NbrRgnIdx)> RegionSimilarityFunc)
Incrementally merge regions with a triangle count below the given SmallThreshold.
TArray< int32 > && MoveRegionTris (int32 RegionIdx)
DYNAMICMESH_API bool OptimizeBorders (int32 MaxRounds=25)
Optimize region borders by swapping triangles.
Data Fields
TArray< int32 > EmptyTriSet
TArray< FRegion > Regions
TArray< FIndex3i > TriangleNbrTris
TArray< int32 > TriangleToRegionMap
Protected Member Functions
DYNAMICMESH_API void BuildNeigbours (int32 RegionIdx)
DYNAMICMESH_API bool MergeSmallRegionsPass (int32 SmallThreshold, TFunctionRef< float(int32 SmallRgnIdx, int32 NbrRgnIdx)> RegionSimilarityFunc)
Detailed Description
FMeshRegionGraph represents neighbourhood relationships between mesh patches.
This is similar in some ways to a FGroupTopology, however only patch-adjacency connections are tracked. Connectivity between patches can be queried, and patches can be merged without rebuilding the graph.
Each mesh Patch/Region is assigned an integer ID/RegionIndex. After removing or merging regions, some RegionIndex values may be invalid, use IsRegion() to check
An integer ID can be associated with each Region using the ExternalIDFunc passed to the various Build() functions.
Definition at line 28 of file MeshRegionGraph.h.
Member Function Documentation
AreRegionsConnected()
DYNAMICMESH_API bool UE::Geometry::FMeshRegionGraph::AreRegionsConnected (int32 RegionAIndex, int32 RegionBIndex) const
Returns
true if the two regions are adjacent, ie they share an edge on at least one triangle
References UE_API.
AreTrianglesConnected()
bool UE::Geometry::FMeshRegionGraph::AreTrianglesConnected (int32 TriangleA, int32 TriangleB) const inline
Returns
true if the two triangles are in the same region
Definition at line 86 of file MeshRegionGraph.h.
References TriangleToRegionMap.
BuildFromComponents()
DYNAMICMESH_API void UE::Geometry::FMeshRegionGraph::BuildFromComponents (const FDynamicMesh3 & Mesh, const FMeshConnectedComponents & Components, TFunctionRef< int32(int32)> ExternalIDFunc, TFunctionRef< bool(int32, int32)> TrisConnectedPredicate = [](int, int) { return true;})
Build a region graph for a Mesh using the given ConnectedComponents.
Parameters
ExternalIDFunc This allows the client to provide an integer ID that will be associated with each Region - called with the region index in Components
References Components, UE::Geometry::Mesh, and UE_API.
BuildFromTriangleSets()
DYNAMICMESH_API void UE::Geometry::FMeshRegionGraph::BuildFromTriangleSets (const FDynamicMesh3 & Mesh, const TArray< TArray< int32 > > & TriangleSets, TFunctionRef< int32(int32)> ExternalIDFunc, TFunctionRef< bool(int32, int32)> TrisConnectedPredicate = [](int, int) { return true;})
Build a region graph for a Mesh using the given triangle sets.
Parameters
ExternalIDFunc This allows the client to provide an integer ID that will be associated with each Region - called with the region index in TriangleSets
References UE::Geometry::Mesh, and UE_API.
BuildNeigbours()
DYNAMICMESH_API void UE::Geometry::FMeshRegionGraph::BuildNeigbours (int32 RegionIdx) protected
References UE_API.
GetExternalID()
int32 UE::Geometry::FMeshRegionGraph::GetExternalID (int32 RegionIdx) const inline
Returns
the ExternalID for a Region, defined at Build time
Definition at line 63 of file MeshRegionGraph.h.
References IsRegion(), and Regions.
GetNeighbours()
DYNAMICMESH_API TArray< int32 > UE::Geometry::FMeshRegionGraph::GetNeighbours (int32 RegionIdx) const
Returns
list of Neigbour Region Indices for a Region
References UE_API.
GetRegionTriCount()
int32 UE::Geometry::FMeshRegionGraph::GetRegionTriCount (int32 RegionIdx) const inline
Returns
the triangle count for a Region
Definition at line 68 of file MeshRegionGraph.h.
References IsRegion(), and Regions.
GetRegionTris()
const TArray< int32 > & UE::Geometry::FMeshRegionGraph::GetRegionTris (int32 RegionIdx) const inline
Returns
list of triangles in a Region
Definition at line 73 of file MeshRegionGraph.h.
References EmptyTriSet, IsRegion(), and Regions.
IsRegion()
int32 UE::Geometry::FMeshRegionGraph::IsRegion (int32 RegionIdx) const inline
Returns
true if the RegionIndex is valid
Definition at line 58 of file MeshRegionGraph.h.
References Regions.
Referenced by GetExternalID(), GetRegionTriCount(), and GetRegionTris().
MaxRegionIndex()
int32 UE::Geometry::FMeshRegionGraph::MaxRegionIndex () const inline
Returns
Max valid region index. Some region indices may be invalid.
Definition at line 53 of file MeshRegionGraph.h.
References Regions.
MergeRegion()
DYNAMICMESH_API bool UE::Geometry::FMeshRegionGraph::MergeRegion (int32 RemoveRgnIdx, int32 MergeToRgnIdx)
Merge one existing Region into another.
Parameters
RemoveRgnIdx this region will be removed
MergeToRgnIdx this region will be added to
References UE_API.
MergeSmallRegions()
DYNAMICMESH_API bool UE::Geometry::FMeshRegionGraph::MergeSmallRegions (int32 SmallThreshold, TFunctionRef< float(int32 SmallRgnIdx, int32 NbrRgnIdx)> RegionSimilarityFunc)
Incrementally merge regions with a triangle count below the given SmallThreshold.
A Small region is merged to it's most-similar neighbour, as defined by RegionSimilarityFunc. The merge order is sorted by largest Similarity, ie most-similar regions are merged first.
References UE_API.
MergeSmallRegionsPass()
DYNAMICMESH_API bool UE::Geometry::FMeshRegionGraph::MergeSmallRegionsPass (int32 SmallThreshold, TFunctionRef< float(int32 SmallRgnIdx, int32 NbrRgnIdx)> RegionSimilarityFunc) protected
References UE_API.
MoveRegionTris()
TArray< int32 > && UE::Geometry::FMeshRegionGraph::MoveRegionTris (int32 RegionIdx) inline
Returns
list of triangles in a Region
Warning
This method leaves the FMeshRegionGraph in an invalid state, and should only be used as a means to avoid memory copies while extracting the triangle sets from a FMeshRegionGraph that will then be discarded
Definition at line 119 of file MeshRegionGraph.h.
References MoveTemp(), and Regions.
OptimizeBorders()
DYNAMICMESH_API bool UE::Geometry::FMeshRegionGraph::OptimizeBorders (int32 MaxRounds = 25)
Optimize region borders by swapping triangles.
The swap criteria is, if 2/3 of the neighbours of a given Triangle in region A are both in region B, swap it to region B. This swapping process is repeated in rounds, MaxRounds times.
Returns
true if any swaps were applied
References UE_API.
Field Documentation
EmptyTriSet
TArray<int32> UE::Geometry::FMeshRegionGraph::EmptyTriSet
Definition at line 148 of file MeshRegionGraph.h.
Referenced by GetRegionTris().
Regions
TArray<FRegion> UE::Geometry::FMeshRegionGraph::Regions
Definition at line 144 of file MeshRegionGraph.h.
Referenced by GetExternalID(), GetRegionTriCount(), GetRegionTris(), IsRegion(), MaxRegionIndex(), and MoveRegionTris().
TriangleNbrTris
TArray<FIndex3i> UE::Geometry::FMeshRegionGraph::TriangleNbrTris
Definition at line 146 of file MeshRegionGraph.h.
TriangleToRegionMap
TArray<int32> UE::Geometry::FMeshRegionGraph::TriangleToRegionMap
Definition at line 145 of file MeshRegionGraph.h.
Referenced by AreTrianglesConnected().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Parameterization/MeshRegionGraph.h