Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > Class Template Reference
UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > Class Template Reference
TDynamicMeshTriangleAttribute is an add-on to a FDynamicMesh3 that allows for per-triangle storage of an attribute value.
#include "DynamicMeshTriangleAttribute.h"
Public Member Functions
TDynamicMeshTriangleAttribute ()
Create an empty overlay.
TDynamicMeshTriangleAttribute (FDynamicMesh3 *ParentMeshIn, bool bAutoInit=true)
Create an overlay for the given parent mesh.
virtual bool Append (const TDynamicAttributeBase &Source, const UE::Geometry::FDynamicMesh3::FAppendInfo &Info) override
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
virtual void AppendDefaulted (const UE::Geometry::FDynamicMesh3::FAppendInfo &Info) override
Add default-valued elements, using the AppendInfo to determine the range to add.
void CompactCopy (const FCompactMaps &CompactMaps, const TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > &ToCopy)
void CompactInPlace (const FCompactMaps &CompactMaps)
Compact the attribute in place.
void Copy (const TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > &Copy)
Set this overlay to contain the same arrays as the copy overlay.
virtual bool CopyIn (int RawID, void *Buffer, int BufferSize) override
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
virtual bool CopyOut (int RawID, void *Buffer, int BufferSize) const override
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
virtual bool CopyThroughMapping (const TDynamicAttributeBase< FDynamicMesh3 > *Source, const FMeshIndexMappings &Mapping) override
void CopyValue (int FromTriangleID, int ToTriangleID)
Copy the attribute value at FromTriangleID to ToTriangleID.
virtual SIZE_T GetByteCount () const
virtual AttribValueType GetDefaultAttributeValue ()
FDynamicMesh3 * GetParentMesh ()
const FDynamicMesh3 * GetParentMesh () const
template<typename AsType>
void GetValue (int TriangleID, AsType &Data) const
Get the element at a given index.
void GetValue (int TriangleID, AttribValueType *Data) const
Get the element at a given index.
void Initialize (AttribValueType InitialValue=(AttribValueType) 0)
Initialize the attribute values with InitialValue, and resize to the parent mesh's max triangle ID.
bool IsBorderEdge (int EdgeID, bool bMeshBoundaryIsBorder=true) const
Returns true if the parent-mesh edge is a "Seam" in this overlay.
bool IsSameAs (const TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > &Other, bool bIgnoreDataLayout) const
Returns true if this AttributeSet is the same as Other.
virtual FDynamicMeshAttributeBase * MakeCompactCopy (const FCompactMaps &CompactMaps, FDynamicMesh3 *ParentMeshIn) const override
Allocate a new compact copy of the attribute layer, optionally with a different parent.
virtual FDynamicMeshAttributeBase * MakeCopy (FDynamicMesh3 *ParentMeshIn) const override
Allocate a new copy of the attribute layer, optionally with a different parent.
virtual FDynamicMeshAttributeBase * MakeNew (FDynamicMesh3 *ParentMeshIn) const override
Allocate a new empty instance of the same type of attribute layer.
virtual TUniquePtr< FDynamicMeshAttributeChangeBase > NewBlankChange () const override
void OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo &CollapseInfo) override
Update the overlay to reflect an edge collapse in the parent mesh.
void OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo &FlipInfo) override
Update the overlay to reflect an edge flip in the parent mesh.
void OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo &MergeInfo) override
Update the overlay to reflect an edge merge in the parent mesh.
void OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo &MergeInfo) override
Update to reflect a vertex merge that does not resolve as a collapse or edge merge (i.e.
virtual void OnNewTriangle (int TriangleID, bool bInserted) override
void OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo &PokeInfo) override
Update the overlay to reflect a face poke in the parent mesh.
void OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo &SplitInfo) override
Update the overlay to reflect an edge split in the parent mesh.
void OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate) override
Update the overlay to reflect a vertex split in the parent.
void ResizeAttribStoreIfNeeded (int TriangleID)
void Serialize (FArchive &Ar, const FCompactMaps *CompactMaps, bool bUseCompression)
Serialize to and from an archive.
void SetNewValue (int NewTriangleID, const AttribValueType *Data)
void SetScalarValue (int TriangleID, const AttribValueType &SingleValue)
Set the element at a given index with a scalar value (the same value for each dimension)
template<typename AsType>
void SetValue (int TriangleID, const AsType &Data)
Set the element at a given index.
void SetValue (int TriangleID, const AttribValueType *Data)
Set the element at a given index.
Public Member Functions inherited from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >
virtual ~TDynamicAttributeBase ()
virtual bool CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const
Check validity of attribute.
virtual bool CopyThroughMapping (const TDynamicAttributeBase *Source, const FMeshIndexMappings &Mapping)=0
Copy data from a different attribute to this one, using the mesh index mapping to determine the correspondence.
FName GetName () const
Get optional identifier for this attribute set.
virtual void OnNewVertex (int VertexID, bool bInserted)
virtual void OnRemoveTriangle (int TriangleID)
virtual void OnRemoveVertex (int VertexID)
virtual void OnReverseTriOrientation (int TriangleID)
void Serialize (FArchive &Ar)
Serialize to and from an archive.
void SetName (FName NameIn)
Set optional identifier for this attribute set.
Protected Types
using Super = FDynamicMeshAttributeBase
Protected Attributes
TDynamicVector< AttribValueType > AttribValues
List of per-triangle attribute values.
FDynamicMesh3 * ParentMesh
The parent mesh this overlay belongs to.
Protected Attributes inherited from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >
FName Name
Optional FName identifier for this attribute set.
Private Member Functions
void Reparent (FDynamicMesh3 *ParentMeshIn)
@set the parent mesh for this overlay.
Friends
class FDynamicMesh3
class FDynamicMeshAttributeSet
FArchive & operator<< (FArchive &Ar, TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > &Attr)
Serialization operator for TDynamicMeshTriangleAttribute.
Additional Inherited Members
Protected Member Functions inherited from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >
virtual void CopyParentClassData (const TDynamicAttributeBase< FDynamicMesh3 > &Other)
Implementation of parent-class copy.
Detailed Description
template<typename AttribValueType, int AttribDimension>
class UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >
TDynamicMeshTriangleAttribute is an add-on to a FDynamicMesh3 that allows for per-triangle storage of an attribute value.
The FDynamicMesh3 mesh topology operations (eg split/flip/collapse edge, poke face, etc) can be mirrored to the overlay via OnSplitEdge(), etc.
Definition at line 53 of file DynamicMeshTriangleAttribute.h.
Member Typedef Documentation
Super
template<typename AttribValueType, int AttribDimension> using UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::Super = FDynamicMeshAttributeBase protected
Definition at line 63 of file DynamicMeshTriangleAttribute.h.
Constructor & Destructor Documentation
TDynamicMeshTriangleAttribute() [1/2]
template<typename AttribValueType, int AttribDimension> UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::TDynamicMeshTriangleAttribute () inline
Create an empty overlay.
Definition at line 70 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeCompactCopy(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeCopy(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeNew().
TDynamicMeshTriangleAttribute() [2/2]
template<typename AttribValueType, int AttribDimension> UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::TDynamicMeshTriangleAttribute (FDynamicMesh3 * ParentMeshIn, bool bAutoInit = true) inline
Create an overlay for the given parent mesh.
Definition at line 76 of file DynamicMeshTriangleAttribute.h.
Member Function Documentation
Append()
template<typename AttribValueType, int AttribDimension> virtual bool UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::Append (const TDynamicAttributeBase & Source, const UE::Geometry::FDynamicMesh3::FAppendInfo & AppendInfo) inline override virtual
Add elements from the Source attribute, using the AppendInfo to determine the range to copy.
Returns
true if the append succeeded, false otherwise (e.g. false if the data from the source attribute was not compatible and the CopyOut failed to copy across)
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 200 of file DynamicMeshTriangleAttribute.h.
AppendDefaulted()
template<typename AttribValueType, int AttribDimension> virtual void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::AppendDefaulted (const UE::Geometry::FDynamicMesh3::FAppendInfo & AppendInfo) inline override virtual
Add default-valued elements, using the AppendInfo to determine the range to add.
Called when appending from a mesh that does not have this attribute.
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 221 of file DynamicMeshTriangleAttribute.h.
CompactCopy()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::CompactCopy (const FCompactMaps & CompactMaps, const TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > & ToCopy) inline
Definition at line 144 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeCompactCopy().
CompactInPlace()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::CompactInPlace (const FCompactMaps & CompactMaps) inline virtual
Compact the attribute in place.
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 127 of file DynamicMeshTriangleAttribute.h.
Copy()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::Copy (const TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > & Copy) inline
Set this overlay to contain the same arrays as the copy overlay.
Definition at line 113 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeCopy().
CopyIn()
template<typename AttribValueType, int AttribDimension> virtual bool UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::CopyIn (int RawID, void * Buffer, int BufferSize) inline override virtual
Generic function to copy data in to an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 241 of file DynamicMeshTriangleAttribute.h.
CopyOut()
template<typename AttribValueType, int AttribDimension> virtual bool UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::CopyOut (int RawID, void * Buffer, int BufferSize) const inline override virtual
Generic function to copy data out of an attribute; it's up to the derived class to map RawID to chunks of attribute data.
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 227 of file DynamicMeshTriangleAttribute.h.
CopyThroughMapping()
template<typename AttribValueType, int AttribDimension> virtual bool UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::CopyThroughMapping (const TDynamicAttributeBase< FDynamicMesh3 > * Source, const FMeshIndexMappings & Mapping) inline override virtual
Definition at line 185 of file DynamicMeshTriangleAttribute.h.
CopyValue()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::CopyValue (int FromTriangleID, int ToTriangleID) inline
Copy the attribute value at FromTriangleID to ToTriangleID.
Definition at line 312 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactInPlace(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::OnPokeTriangle(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::OnSplitEdge().
GetByteCount()
template<typename AttribValueType, int AttribDimension> virtual SIZE_T UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetByteCount () const inline virtual
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 549 of file DynamicMeshTriangleAttribute.h.
GetDefaultAttributeValue()
template<typename AttribValueType, int AttribDimension> virtual AttribValueType UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetDefaultAttributeValue () inline virtual
Definition at line 399 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::AppendDefaulted(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::OnNewTriangle(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::ResizeAttribStoreIfNeeded().
GetParentMesh() [1/2]
template<typename AttribValueType, int AttribDimension> FDynamicMesh3 * UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetParentMesh () inline
Returns
the parent mesh for this overlay
Definition at line 96 of file DynamicMeshTriangleAttribute.h.
GetParentMesh() [2/2]
template<typename AttribValueType, int AttribDimension> const FDynamicMesh3 * UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetParentMesh () const inline
Returns
the parent mesh for this overlay
Definition at line 94 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::Apply().
GetValue() [1/2]
template<typename AttribValueType, int AttribDimension> template<typename AsType> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetValue (int TriangleID, AsType & Data) const inline
Get the element at a given index.
Definition at line 268 of file DynamicMeshTriangleAttribute.h.
GetValue() [2/2]
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::GetValue (int TriangleID, AttribValueType * Data) const inline
Get the element at a given index.
Definition at line 257 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy(), UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::SaveInitialTriangle(), and UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::StoreAllFinalTriangles().
Initialize()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::Initialize (AttribValueType InitialValue = (AttribValueType)0) inline
Initialize the attribute values with InitialValue, and resize to the parent mesh's max triangle ID.
Definition at line 163 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeCompactCopy(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::MakeNew().
IsBorderEdge()
template<typename AttribValueType, int AttribDimension> bool UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::IsBorderEdge (int EdgeID, bool bMeshBoundaryIsBorder = true) const inline
Returns true if the parent-mesh edge is a "Seam" in this overlay.
Definition at line 324 of file DynamicMeshTriangleAttribute.h.
IsSameAs()
template<typename AttribValueType, int AttribDimension> bool UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::IsSameAs (const TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > & Other, bool bIgnoreDataLayout) const inline
Returns true if this AttributeSet is the same as Other.
Definition at line 427 of file DynamicMeshTriangleAttribute.h.
MakeCompactCopy()
template<typename AttribValueType, int AttribDimension> virtual FDynamicMeshAttributeBase * UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::MakeCompactCopy (const FCompactMaps & CompactMaps, FDynamicMesh3 * ParentIn) const inline override virtual
Allocate a new compact copy of the attribute layer, optionally with a different parent.
Default implementation does a full copy and then compacts it, usually derived class will want to override this with a more efficient direct compact copy implementation
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 119 of file DynamicMeshTriangleAttribute.h.
MakeCopy()
template<typename AttribValueType, int AttribDimension> virtual FDynamicMeshAttributeBase * UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::MakeCopy (FDynamicMesh3 * ParentIn) const inline override virtual
Allocate a new copy of the attribute layer, optionally with a different parent.
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 105 of file DynamicMeshTriangleAttribute.h.
MakeNew()
template<typename AttribValueType, int AttribDimension> virtual FDynamicMeshAttributeBase * UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::MakeNew (FDynamicMesh3 * ParentIn) const inline override virtual
Allocate a new empty instance of the same type of attribute layer.
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 98 of file DynamicMeshTriangleAttribute.h.
NewBlankChange()
template<typename AttribValueType, int AttribDimension> virtual TUniquePtr< FDynamicMeshAttributeChangeBase > UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::NewBlankChange () const inline override virtual
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 344 of file DynamicMeshTriangleAttribute.h.
OnCollapseEdge()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo & CollapseInfo) inline override virtual
Update the overlay to reflect an edge collapse in the parent mesh.
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 369 of file DynamicMeshTriangleAttribute.h.
OnFlipEdge()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo & FlipInfo) inline override virtual
Update the overlay to reflect an edge flip in the parent mesh.
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 363 of file DynamicMeshTriangleAttribute.h.
OnMergeEdges()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo & MergeInfo) inline override virtual
Update the overlay to reflect an edge merge in the parent mesh.
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 382 of file DynamicMeshTriangleAttribute.h.
OnMergeVertices()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo & MergeInfo) inline override virtual
Update to reflect a vertex merge that does not resolve as a collapse or edge merge (i.e.
a vertex merge that resolves as bowtie creation).
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 387 of file DynamicMeshTriangleAttribute.h.
OnNewTriangle()
template<typename AttribValueType, int AttribDimension> virtual void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnNewTriangle (int TriangleID, bool bInserted) inline override virtual
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 417 of file DynamicMeshTriangleAttribute.h.
OnPokeTriangle()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo & PokeInfo) inline override virtual
Update the overlay to reflect a face poke in the parent mesh.
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 375 of file DynamicMeshTriangleAttribute.h.
OnSplitEdge()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo & SplitInfo) inline override virtual
Update the overlay to reflect an edge split in the parent mesh.
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 353 of file DynamicMeshTriangleAttribute.h.
OnSplitVertex()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo & SplitInfo, const TArrayView< const int > & TrianglesToUpdate) inline override virtual
Update the overlay to reflect a vertex split in the parent.
Reimplemented from UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 394 of file DynamicMeshTriangleAttribute.h.
Reparent()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::Reparent (FDynamicMesh3 * ParentMeshIn) inline private virtual
@set the parent mesh for this overlay.
Only safe for use during FDynamicMesh move
Implements UE::Geometry::TDynamicAttributeBase< FDynamicMesh3 >.
Definition at line 87 of file DynamicMeshTriangleAttribute.h.
ResizeAttribStoreIfNeeded()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::ResizeAttribStoreIfNeeded (int TriangleID) inline
Definition at line 404 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::OnNewTriangle().
Serialize()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::Serialize (FArchive & Ar, const FCompactMaps * CompactMaps, bool bUseCompression) inline
Serialize to and from an archive.
Parameters
Ar Archive to serialize with.
CompactMaps If this is not a null pointer, the mesh serialization compacted the vertex and/or triangle data using the provided mapping.
bUseCompression Use compression for serializing bulk data.
Definition at line 497 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::operator<<, and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::Serialize().
SetNewValue()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::SetNewValue (int NewTriangleID, const AttribValueType * Data) inline
Definition at line 170 of file DynamicMeshTriangleAttribute.h.
SetScalarValue()
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::SetScalarValue (int TriangleID, const AttribValueType & SingleValue) inline
Set the element at a given index with a scalar value (the same value for each dimension)
Definition at line 300 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::OnNewTriangle().
SetValue() [1/2]
template<typename AttribValueType, int AttribDimension> template<typename AsType> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::SetValue (int TriangleID, const AsType & Data) inline
Set the element at a given index.
Definition at line 290 of file DynamicMeshTriangleAttribute.h.
SetValue() [2/2]
template<typename AttribValueType, int AttribDimension> void UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::SetValue (int TriangleID, const AttribValueType * Data) inline
Set the element at a given index.
Definition at line 279 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::Append(), UE::Geometry::FDynamicMeshTriangleAttributeChange< AttribValueType, AttribDimension >::Apply(), UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy(), and UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CopyThroughMapping().
Friends And Related Symbol Documentation
FDynamicMesh3
template<typename AttribValueType, int AttribDimension> friend class FDynamicMesh3 friend
Definition at line 65 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshScalarTriangleAttribute< int32 >::TDynamicMeshScalarTriangleAttribute().
FDynamicMeshAttributeSet
template<typename AttribValueType, int AttribDimension> friend class FDynamicMeshAttributeSet friend
Definition at line 66 of file DynamicMeshTriangleAttribute.h.
operator<<
template<typename AttribValueType, int AttribDimension> FArchive & operator<< (FArchive & Ar, TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension > & Attr) friend
Serialization operator for TDynamicMeshTriangleAttribute.
Parameters
Ar Archive to serialize with.
Attr Mesh triangle attribute to serialize.
Returns
Passing down serializing archive.
Definition at line 484 of file DynamicMeshTriangleAttribute.h.
Field Documentation
AttribValues
template<typename AttribValueType, int AttribDimension> TDynamicVector<AttribValueType> UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::AttribValues protected
List of per-triangle attribute values.
Definition at line 61 of file DynamicMeshTriangleAttribute.h.
Referenced by UE::Geometry::TDynamicMeshTriangleAttribute< RealType, 1 >::CompactCopy().
ParentMesh
template<typename AttribValueType, int AttribDimension> FDynamicMesh3* UE::Geometry::TDynamicMeshTriangleAttribute< AttribValueType, AttribDimension >::ParentMesh protected
The parent mesh this overlay belongs to.
Definition at line 58 of file DynamicMeshTriangleAttribute.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/DynamicMeshTriangleAttribute.h