Unreal Engine 5.6 C++ API: FChange Class Reference
FChange Class Reference abstract
FChange modifies a UObject and is meant to be used to implement undo/redo.
#include "Change.h"
Public Types
enum class EChangeStyle { InPlaceSwap , CommandPattern }
Public Member Functions
virtual ~FChange ()
Virtual destructor.
virtual void AddReferencedObjects (FReferenceCollector &Collector)
Used by GC to collect referenced objects.
virtual void Apply (UObject *Object)=0
Makes the change to the object.
virtual TUniquePtr< FChange > Execute (UObject *Object)=0
Makes the change to the object, returning a new change that can be used to perfectly roll back this change.
virtual EChangeStyle GetChangeType ()=0
What style of change is this.
virtual bool HasExpired (UObject *Object) const
virtual void PrintToLog (FFeedbackContext &FeedbackContext, const int32 IndentLevel=0)
Prints this change to the log, including sub-changes if there are any.
virtual void Revert (UObject *Object)=0
Reverts change to the object.
virtual FString ToString () const =0
Describes this change (for debugging)
Protected Member Functions
FChange ()
Protected default constructor.
Private Member Functions
FChange (const FChange &)=delete
FChange & operator= (const FChange &)=delete
Detailed Description
FChange modifies a UObject and is meant to be used to implement undo/redo.
The change is embedded in an FTransaction which executes it instead of the standard serialization transaction (cannot be combined - see FTransaction).
The original FChange style (used by MeshEditor) was that calling Execute() would return a new FChange that applies the opposite action, and FTransaction would swap the two at each undo/redo step (eg a "DeleteObject" FChange would return a "CreateObject" FChange)
The alternative "Command Pattern"-style FChange calls Apply() and Revert() on a single FChange.
FChange may eventually be deprecated. You should subclass FSwapChange and FCommandChange to implement these different styles.
Definition at line 31 of file Change.h.
Member Enumeration Documentation
EChangeStyle
enum class FChange::EChangeStyle strong
Enumerator
InPlaceSwap
CommandPattern
Definition at line 35 of file Change.h.
Constructor & Destructor Documentation
~FChange()
virtual FChange::~FChange () inline virtual
Virtual destructor.
Definition at line 66 of file Change.h.
FChange() [1/2]
FChange::FChange () inline protected
Protected default constructor.
Definition at line 73 of file Change.h.
Referenced by FChange(), and operator=().
FChange() [2/2]
FChange::FChange (const FChange &) private delete
References FChange().
Member Function Documentation
AddReferencedObjects()
virtual void FChange::AddReferencedObjects (FReferenceCollector & Collector) inline virtual
Used by GC to collect referenced objects.
Definition at line 57 of file Change.h.
Apply()
virtual void FChange::Apply (UObject * Object) pure virtual
Makes the change to the object.
Implemented in FActivateToolChange, FBeginToolChange, FComponentWorldTransformChange, FCurveControlPointsMechanicInsertionChange, FCurveControlPointsMechanicModeChange, FCurveControlPointsMechanicMovementChange, FCurveControlPointsMechanicSelectionChange, FDrawPolygonStateChange, FDrawPolyPathStateChange, FEditMeshPolygonsToolMeshChange, FGeometrySelectionDeltaChange, FGeometrySelectionReplaceChange, FGroupEdgeInsertionFirstPointChange, FLatticeControlPointsMechanicMovementChange, FLatticeControlPointsMechanicSelectionChange, FLatticeDeformerToolConstrainedPointsChange, FMeshChange, FMeshReplacementChange, FMeshSelectionChange, FMeshTopologySelectionMechanicSelectionChange, FMeshVertexChange, FPolyEditActivityStartChange, FPolyEditCutFacesActivityFirstPointChange, FSpaceCurveDeformationMechanicMovementChange, FSpaceCurveDeformationMechanicSelectionChange, FSwapChange, FToolChangeWrapperChange, FToolCommandChangeSequence, FTransformProxyChange, TCustomIndexedValuesChange< ValueType, CustomDataType >, TCustomIndexedValuesChange< float, int32 >, TCustomIndexedValuesChange< FVector4f, int32 >, TIndexedValuesChange< ValueType >, TIndexedValuesChange< float >, TIndexedValuesChange< FVector4f >, TSimpleValueLambdaChange< ValueType >, and TWrappedToolCommandChange< ChangeType >.
References Object.
Execute()
virtual TUniquePtr< FChange > FChange::Execute (UObject * Object) pure virtual
Makes the change to the object, returning a new change that can be used to perfectly roll back this change.
Implemented in FCommandChange, and FCompoundChange.
References Object.
GetChangeType()
virtual EChangeStyle FChange::GetChangeType () pure virtual
What style of change is this.
Implemented in FCommandChange, and FSwapChange.
HasExpired()
virtual bool FChange::HasExpired (UObject * Object) const inline virtual
Returns
true if this Change has Expired, ie it will no longer have any effect and could be skipped by undo/redo
Reimplemented in FActivateToolChange, FBeginToolChange, FCurveControlPointsMechanicInsertionChange, FCurveControlPointsMechanicModeChange, FCurveControlPointsMechanicMovementChange, FCurveControlPointsMechanicSelectionChange, FDrawPolygonStateChange, FDrawPolyPathStateChange, FGeometrySelectionDeltaChange, FGeometrySelectionReplaceChange, FGroupEdgeInsertionFirstPointChange, FLatticeControlPointsMechanicMovementChange, FLatticeControlPointsMechanicSelectionChange, FLatticeDeformerToolConstrainedPointsChange, FPolyEditActivityStartChange, FPolyEditCutFacesActivityFirstPointChange, FToolChangeWrapperChange, and UE::CurveEditor::FCurveEditorCommandChange.
Definition at line 54 of file Change.h.
References Object.
operator=()
FChange & FChange::operator= (const FChange &) private delete
References FChange().
PrintToLog()
virtual void FChange::PrintToLog (FFeedbackContext & FeedbackContext, const int32 IndentLevel = 0) virtual
Prints this change to the log, including sub-changes if there are any.
For compound changes, there might be multiple lines. You should not need to override this function.
Reimplemented in FCompoundChange.
Revert()
virtual void FChange::Revert (UObject * Object) pure virtual
Reverts change to the object.
Implemented in FActivateToolChange, FBeginToolChange, FComponentWorldTransformChange, FCurveControlPointsMechanicInsertionChange, FCurveControlPointsMechanicModeChange, FCurveControlPointsMechanicMovementChange, FCurveControlPointsMechanicSelectionChange, FDrawPolygonStateChange, FDrawPolyPathStateChange, FEditMeshPolygonsToolMeshChange, FGeometrySelectionDeltaChange, FGeometrySelectionReplaceChange, FGroupEdgeInsertionFirstPointChange, FLatticeControlPointsMechanicMovementChange, FLatticeControlPointsMechanicSelectionChange, FLatticeDeformerToolConstrainedPointsChange, FMeshChange, FMeshReplacementChange, FMeshSelectionChange, FMeshTopologySelectionMechanicSelectionChange, FMeshVertexChange, FPolyEditActivityStartChange, FPolyEditCutFacesActivityFirstPointChange, FSpaceCurveDeformationMechanicMovementChange, FSpaceCurveDeformationMechanicSelectionChange, FSwapChange, FToolChangeWrapperChange, FToolCommandChangeSequence, FTransformProxyChange, TCustomIndexedValuesChange< ValueType, CustomDataType >, TCustomIndexedValuesChange< float, int32 >, TCustomIndexedValuesChange< FVector4f, int32 >, TIndexedValuesChange< ValueType >, TIndexedValuesChange< float >, TIndexedValuesChange< FVector4f >, TSimpleValueLambdaChange< ValueType >, and TWrappedToolCommandChange< ChangeType >.
References Object.
ToString()
virtual FString FChange::ToString () const pure virtual
Describes this change (for debugging)
Implemented in FActivateToolChange, FBeginToolChange, FComponentWorldTransformChange, FCompoundChange, FCurveControlPointsMechanicInsertionChange, FCurveControlPointsMechanicModeChange, FCurveControlPointsMechanicMovementChange, FCurveControlPointsMechanicSelectionChange, FDrawPolygonStateChange, FDrawPolyPathStateChange, FEditMeshPolygonsToolMeshChange, FGeometrySelectionDeltaChange, FGeometrySelectionReplaceChange, FGroupEdgeInsertionFirstPointChange, FLatticeControlPointsMechanicMovementChange, FLatticeControlPointsMechanicSelectionChange, FLatticeDeformerToolConstrainedPointsChange, FMeshAttributePaintChange, FMeshChange, FMeshReplacementChange, FMeshSelectionChange, FMeshTopologySelectionMechanicSelectionChange, FMeshVertexChange, FMeshVertexColorPaintChange, FPolyEditActivityStartChange, FPolyEditCutFacesActivityFirstPointChange, FSpaceCurveDeformationMechanicMovementChange, FSpaceCurveDeformationMechanicSelectionChange, FToolChangeWrapperChange, FToolCommandChange, FToolCommandChangeSequence, FTransformProxyChange, TIndexedValuesChange< ValueType >, TIndexedValuesChange< float >, TIndexedValuesChange< FVector4f >, TWrappedToolCommandChange< ChangeType >, and UE::CurveEditor::FCurveEditorCommandChange.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/Change.h