Unreal Engine 5.6 C++ API: UE::Geometry::TSphericalFibonacci< RealType > Class Template Reference
UE::Geometry::TSphericalFibonacci< RealType > Class Template Reference
A Spherical Fibonacci (SF) Point Set is a set of points that are roughly evenly distributed on a sphere.
#include "SphericalFibonacci.h"
Public Member Functions
TSphericalFibonacci (int32 NumPoints=64)
int32 FindIndex (const TVector< RealType > &P)
int32 Num () const
TVector< RealType > operator[] (int32 Index) const
TVector< RealType > Point (int32 Index) const
Data Fields
int32 N = 64
Static Protected Member Functions
static RealType MultiplyAddFrac (RealType a, RealType b)
Detailed Description
template<typename RealType>
class UE::Geometry::TSphericalFibonacci< RealType >
A Spherical Fibonacci (SF) Point Set is a set of points that are roughly evenly distributed on a sphere.
The points lie on a spiral, see https://dl.acm.org/doi/10.1145/2816795.2818131 for more information. The i-th SF point an N-point set can be calculated directly. For a given (normalized) point P, finding the nearest SF point (ie mapping back to i) can be done in constant time.
Z is "up" in the sphere.
Definition at line 25 of file SphericalFibonacci.h.
Constructor & Destructor Documentation
TSphericalFibonacci()
template<typename RealType> UE::Geometry::TSphericalFibonacci< RealType >::TSphericalFibonacci (int32 NumPoints = 64) inline
Definition at line 30 of file SphericalFibonacci.h.
References N.
Member Function Documentation
FindIndex()
template<typename RealType> int32 UE::Geometry::TSphericalFibonacci< RealType >::FindIndex (const TVector< RealType > & P) inline
Returns
Index of the sphere point closest to the given point P
Definition at line 74 of file SphericalFibonacci.h.
References TMathUtil< RealType >::Atan2(), B, TMathUtil< RealType >::Clamp(), TMathUtil< RealType >::Cos(), UE::Geometry::DistanceSquared(), TMathUtil< RealType >::Floor(), TMathUtil< RealType >::Log(), TMathUtil< RealType >::Max(), TMathUtil< RealType >::Min(), MultiplyAddFrac(), N, TMathUtil< RealType >::Pow(), TMathUtil< RealType >::Round(), TMathUtil< RealType >::Sin(), TMathUtil< RealType >::Sqrt(), UE::Math::TVector2< T >::X, UE::Math::TVector< T >::X, UE::Math::TVector2< T >::Y, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
MultiplyAddFrac()
template<typename RealType> RealType UE::Geometry::TSphericalFibonacci< RealType >::MultiplyAddFrac (RealType a, RealType b) inline static protected
Definition at line 129 of file SphericalFibonacci.h.
References TMathUtil< RealType >::Floor().
Referenced by FindIndex().
Num()
template<typename RealType> int32 UE::Geometry::TSphericalFibonacci< RealType >::Num () const inline
Definition at line 35 of file SphericalFibonacci.h.
References N.
operator[]()
template<typename RealType> TVector< RealType > UE::Geometry::TSphericalFibonacci< RealType >::operator[] (int32 Index) const inline
Parameters
Index point index in range [0,Num()-1]
Returns
sphere point for given Index
Definition at line 65 of file SphericalFibonacci.h.
References Point.
Point()
template<typename RealType> TVector< RealType > UE::Geometry::TSphericalFibonacci< RealType >::Point (int32 Index) const inline
Parameters
Index point index in range [0,Num()-1]
Returns
sphere point for given Index
Definition at line 44 of file SphericalFibonacci.h.
References TMathUtil< RealType >::ACos(), checkSlow, TMathUtil< RealType >::Cos(), TMathUtil< RealType >::Floor(), N, TMathUtil< RealType >::Sin(), and TMathUtil< RealType >::Sqrt().
Field Documentation
N
template<typename RealType> int32 UE::Geometry::TSphericalFibonacci< RealType >::N = 64
Definition at line 28 of file SphericalFibonacci.h.
Referenced by TSphericalFibonacci(), FindIndex(), Num(), and Point().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Sampling/SphericalFibonacci.h