Unreal Engine 5.6 C++ API: FBlendableManager Class Reference
FBlendableManager Class Reference
#include "BlendableManager.h"
Public Member Functions
FBlendableManager ()
template<class T>
T & GetSingleFinalData ()
template<class T>
const T & GetSingleFinalDataConst () const
template<class T>
T * IterateBlendables (FBlendableEntry *&InIterator) const
template<class T>
T * PushBlendableData (float InWeight, const T &InData)
Private Member Functions
FBlendableEntry * GetNextBlendableEntryPtr (FBlendableEntry *InIterator=0) const
FBlendableEntry * PushBlendableDataPtr (float InWeight, FName InBlendableType, const uint8 *InData, uint32 InDataSize, uint32 Alignment)
Private Attributes
TArray< uint8 > Scratch
Detailed Description
Definition at line 30 of file BlendableManager.h.
Constructor & Destructor Documentation
FBlendableManager()
FBlendableManager::FBlendableManager () inline
Definition at line 34 of file BlendableManager.h.
References Scratch.
Member Function Documentation
GetNextBlendableEntryPtr()
FBlendableEntry * FBlendableManager::GetNextBlendableEntryPtr (FBlendableEntry * InIterator = 0) const inline private
Definition at line 124 of file BlendableManager.h.
References Scratch.
Referenced by IterateBlendables().
GetSingleFinalData()
template<class T> T & FBlendableManager::GetSingleFinalData () inline
Definition at line 59 of file BlendableManager.h.
References IterateBlendables(), and PushBlendableData().
GetSingleFinalDataConst()
template<class T> const T & FBlendableManager::GetSingleFinalDataConst () const inline
Definition at line 79 of file BlendableManager.h.
References IterateBlendables().
IterateBlendables()
template<class T> T * FBlendableManager::IterateBlendables (FBlendableEntry *& InIterator) const inline
Definition at line 100 of file BlendableManager.h.
References FBlendableEntry::BlendableType, FBlendableEntry::GetDataPtr(), and GetNextBlendableEntryPtr().
Referenced by GetSingleFinalData(), and GetSingleFinalDataConst().
PushBlendableData()
template<class T> T * FBlendableManager::PushBlendableData (float InWeight, const T & InData) inline
Definition at line 43 of file BlendableManager.h.
References FBlendableEntry::GetDataPtr(), FMath::Max, and PushBlendableDataPtr().
Referenced by GetSingleFinalData().
PushBlendableDataPtr()
FBlendableEntry * FBlendableManager::PushBlendableDataPtr (float InWeight, FName InBlendableType, const uint8 * InData, uint32 InDataSize, uint32 Alignment) inline private
Definition at line 151 of file BlendableManager.h.
References FBlendableEntry::BlendableType, check, FBlendableEntry::DataSize, FBlendableEntry::GetDataPtr(), FBlendableEntry::PrePadding, Scratch, and FBlendableEntry::Weight.
Referenced by PushBlendableData().
Field Documentation
Scratch
TArray<uint8> FBlendableManager::Scratch private
Definition at line 121 of file BlendableManager.h.
Referenced by FBlendableManager(), GetNextBlendableEntryPtr(), and PushBlendableDataPtr().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/BlendableManager.h