Unreal Engine 5.6 C++ API: FSkeletalMeshAttributesShared Class Reference
FSkeletalMeshAttributesShared Class Reference
#include "SkeletalMeshAttributes.h"
Public Types
using FBoneArray = TMeshElementContainer<FBoneID>
using FBoneColorAttributesConstRef = TMeshAttributesConstRef<FBoneID, FVector4f>
using FBoneColorAttributesRef = TMeshAttributesRef<FBoneID, FVector4f>
using FBoneNameAttributesConstRef = TMeshAttributesConstRef<FBoneID, FName>
using FBoneNameAttributesRef = TMeshAttributesRef<FBoneID, FName>
using FBoneParentIndexAttributesConstRef = TMeshAttributesConstRef<FBoneID, int32>
using FBoneParentIndexAttributesRef = TMeshAttributesRef<FBoneID, int32>
using FBonePoseAttributesConstRef = TMeshAttributesConstRef<FBoneID, FTransform>
using FBonePoseAttributesRef = TMeshAttributesRef<FBoneID, FTransform>
using FSourceGeometryPartArray = TMeshElementContainer<FSourceGeometryPartID>
using FSourceGeometryPartNameConstRef = TMeshAttributesConstRef<FSourceGeometryPartID, FName>
using FSourceGeometryPartNameRef = TMeshAttributesRef<FSourceGeometryPartID, FName>
using FSourceGeometryPartVertexOffsetAndCountConstRef = TMeshAttributesConstRef<FSourceGeometryPartID, TArrayView<int32>>
using FSourceGeometryPartVertexOffsetAndCountRef = TMeshAttributesRef<FSourceGeometryPartID, TArrayView<int32>>
Public Member Functions
SKELETALMESHDESCRIPTION_API FSkeletalMeshAttributesShared (const FMeshDescription &InMeshDescription)
SKELETALMESHDESCRIPTION_API const TAttributesSet< FBoneID > & BoneAttributes () const
SKELETALMESHDESCRIPTION_API const FBoneArray & Bones () const
SKELETALMESHDESCRIPTION_API FBoneColorAttributesConstRef GetBoneColors () const
SKELETALMESHDESCRIPTION_API FBoneNameAttributesConstRef GetBoneNames () const
SKELETALMESHDESCRIPTION_API FBoneParentIndexAttributesConstRef GetBoneParentIndices () const
SKELETALMESHDESCRIPTION_API FBonePoseAttributesConstRef GetBonePoses () const
SKELETALMESHDESCRIPTION_API TArray< FName > GetMorphTargetNames () const
Returns the list of all registered morph targets on this mesh.
SKELETALMESHDESCRIPTION_API int32 GetNumBones () const
SKELETALMESHDESCRIPTION_API int32 GetNumSourceGeometryParts () const
SKELETALMESHDESCRIPTION_API TArray< FName > GetSkinWeightProfileNames (const bool bInUserDefinedOnly=false) const
Returns the list of all registered skin weight profile names on this mesh.
SKELETALMESHDESCRIPTION_API FSourceGeometryPartNameConstRef GetSourceGeometryPartNames () const
SKELETALMESHDESCRIPTION_API FSourceGeometryPartVertexOffsetAndCountConstRef GetSourceGeometryPartVertexOffsetAndCounts () const
SKELETALMESHDESCRIPTION_API TVertexInstanceAttributesConstRef< FVector3f > GetVertexInstanceMorphNormalDelta (const FName InMorphTargetName) const
Returns a read-only vertex instance normal delta attribute for the given morph target.
SKELETALMESHDESCRIPTION_API TVertexAttributesConstRef< FVector3f > GetVertexMorphPositionDelta (const FName InMorphTargetName) const
Returns a read-only vertex position delta attribute for the given morph target.
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesConstRef GetVertexSkinWeights (const FName InProfileName=NAME_None) const
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesConstRef GetVertexSkinWeightsFromAttributeName (const FName InAttributeName=NAME_None) const
SKELETALMESHDESCRIPTION_API bool HasBoneColorAttribute () const
SKELETALMESHDESCRIPTION_API bool HasBoneNameAttribute () const
SKELETALMESHDESCRIPTION_API bool HasBoneParentIndexAttribute () const
SKELETALMESHDESCRIPTION_API bool HasBonePoseAttribute () const
bool HasBones () const
SKELETALMESHDESCRIPTION_API bool HasMorphTargetNormalsAttribute (const FName InMorphTargetName) const
SKELETALMESHDESCRIPTION_API bool HasMorphTargetPositionsAttribute (const FName InMorphTargetName) const
bool HasSourceGeometryParts () const
SKELETALMESHDESCRIPTION_API bool IsBoneValid (const FBoneID BoneID) const
SKELETALMESHDESCRIPTION_API bool IsSourceGeometryPartValid (const FSourceGeometryPartID InSourceGeometryPartID) const
SKELETALMESHDESCRIPTION_API const TAttributesSet< FSourceGeometryPartID > & SourceGeometryPartAttributes () const
SKELETALMESHDESCRIPTION_API const FSourceGeometryPartArray & SourceGeometryParts () const
Static Public Member Functions
static SKELETALMESHDESCRIPTION_API FName GetMorphTargetNameFromAttribute (const FName InAttributeName)
Returns the name of a morph target given the attribute name. If the given attribute name is invalid, NAME_None is returned.
static SKELETALMESHDESCRIPTION_API FName GetProfileNameFromAttribute (const FName InAttributeName)
Returns a skin profile name from the attribute name, if the attribute name is a valid skin weights attribute.
static SKELETALMESHDESCRIPTION_API bool IsMorphTargetAttribute (const FName InAttributeName)
Returns true if the given attribute name refers to a morph target attribute.
static SKELETALMESHDESCRIPTION_API bool IsSkinWeightAttribute (const FName InAttributeName)
Helper function that indicates whether an attribute name represents a skin weight attribute.
static SKELETALMESHDESCRIPTION_API bool IsValidSkinWeightProfileName (const FName InProfileName)
Returns true if the given identifier is a valid profile name.
Static Public Attributes
static SKELETALMESHDESCRIPTION_API FName BonesElementName
Name of the mesh element type representing bones.
static SKELETALMESHDESCRIPTION_API FName DefaultSkinWeightProfileName
static SKELETALMESHDESCRIPTION_API FName SourceGeometryPartElementName
Name of the mesh element representing import data for meshes that were imported from separate geometries into a single skeletal mesh piece.
Static Protected Member Functions
static SKELETALMESHDESCRIPTION_API FName CreateMorphTargetAttributeName (const FName InMorphTargetName)
Construct a name for a morph target attribute with the given a user-visible morph target name.
static SKELETALMESHDESCRIPTION_API FName CreateSkinWeightAttributeName (const FName InProfileName)
Construct a name for a skin weight attribute with the given skin weight profile name.
Protected Attributes
const FMeshElementChannels * BoneElementsShared = nullptr
const FMeshElementChannels * SourceGeometryPartElementsShared = nullptr
Private Attributes
const FMeshDescription & MeshDescriptionShared
Detailed Description
Definition at line 46 of file SkeletalMeshAttributes.h.
Member Typedef Documentation
FBoneArray
using FSkeletalMeshAttributesShared::FBoneArray = TMeshElementContainer<FBoneID>
Definition at line 49 of file SkeletalMeshAttributes.h.
FBoneColorAttributesConstRef
using FSkeletalMeshAttributesShared::FBoneColorAttributesConstRef = TMeshAttributesConstRef<FBoneID, FVector4f>
Definition at line 61 of file SkeletalMeshAttributes.h.
FBoneColorAttributesRef
using FSkeletalMeshAttributesShared::FBoneColorAttributesRef = TMeshAttributesRef<FBoneID, FVector4f>
Definition at line 60 of file SkeletalMeshAttributes.h.
FBoneNameAttributesConstRef
using FSkeletalMeshAttributesShared::FBoneNameAttributesConstRef = TMeshAttributesConstRef<FBoneID, FName>
Definition at line 52 of file SkeletalMeshAttributes.h.
FBoneNameAttributesRef
using FSkeletalMeshAttributesShared::FBoneNameAttributesRef = TMeshAttributesRef<FBoneID, FName>
Definition at line 51 of file SkeletalMeshAttributes.h.
FBoneParentIndexAttributesConstRef
using FSkeletalMeshAttributesShared::FBoneParentIndexAttributesConstRef = TMeshAttributesConstRef<FBoneID, int32>
Definition at line 55 of file SkeletalMeshAttributes.h.
FBoneParentIndexAttributesRef
using FSkeletalMeshAttributesShared::FBoneParentIndexAttributesRef = TMeshAttributesRef<FBoneID, int32>
Definition at line 54 of file SkeletalMeshAttributes.h.
FBonePoseAttributesConstRef
using FSkeletalMeshAttributesShared::FBonePoseAttributesConstRef = TMeshAttributesConstRef<FBoneID, FTransform>
Definition at line 58 of file SkeletalMeshAttributes.h.
FBonePoseAttributesRef
using FSkeletalMeshAttributesShared::FBonePoseAttributesRef = TMeshAttributesRef<FBoneID, FTransform>
Definition at line 57 of file SkeletalMeshAttributes.h.
FSourceGeometryPartArray
using FSkeletalMeshAttributesShared::FSourceGeometryPartArray = TMeshElementContainer<FSourceGeometryPartID>
Definition at line 63 of file SkeletalMeshAttributes.h.
FSourceGeometryPartNameConstRef
using FSkeletalMeshAttributesShared::FSourceGeometryPartNameConstRef = TMeshAttributesConstRef<FSourceGeometryPartID, FName>
Definition at line 66 of file SkeletalMeshAttributes.h.
FSourceGeometryPartNameRef
using FSkeletalMeshAttributesShared::FSourceGeometryPartNameRef = TMeshAttributesRef<FSourceGeometryPartID, FName>
Definition at line 65 of file SkeletalMeshAttributes.h.
FSourceGeometryPartVertexOffsetAndCountConstRef
using FSkeletalMeshAttributesShared::FSourceGeometryPartVertexOffsetAndCountConstRef = TMeshAttributesConstRef<FSourceGeometryPartID, TArrayView<int32>>
Definition at line 69 of file SkeletalMeshAttributes.h.
FSourceGeometryPartVertexOffsetAndCountRef
using FSkeletalMeshAttributesShared::FSourceGeometryPartVertexOffsetAndCountRef = TMeshAttributesRef<FSourceGeometryPartID, TArrayView<int32>>
Definition at line 68 of file SkeletalMeshAttributes.h.
Constructor & Destructor Documentation
FSkeletalMeshAttributesShared()
SKELETALMESHDESCRIPTION_API FSkeletalMeshAttributesShared::FSkeletalMeshAttributesShared (const FMeshDescription & InMeshDescription)
Referenced by FSkeletalMeshConstAttributes::FSkeletalMeshConstAttributes().
Member Function Documentation
BoneAttributes()
SKELETALMESHDESCRIPTION_API const TAttributesSet< FBoneID > & FSkeletalMeshAttributesShared::BoneAttributes () const
Bones()
SKELETALMESHDESCRIPTION_API const FBoneArray & FSkeletalMeshAttributesShared::Bones () const
CreateMorphTargetAttributeName()
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::CreateMorphTargetAttributeName (const FName InMorphTargetName) static protected
Construct a name for a morph target attribute with the given a user-visible morph target name.
CreateSkinWeightAttributeName()
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::CreateSkinWeightAttributeName (const FName InProfileName) static protected
Construct a name for a skin weight attribute with the given skin weight profile name.
Each mesh description can hold different skin weight profiles, although the default is always present.
GetBoneColors()
SKELETALMESHDESCRIPTION_API FBoneColorAttributesConstRef FSkeletalMeshAttributesShared::GetBoneColors () const
GetBoneNames()
SKELETALMESHDESCRIPTION_API FBoneNameAttributesConstRef FSkeletalMeshAttributesShared::GetBoneNames () const
GetBoneParentIndices()
SKELETALMESHDESCRIPTION_API FBoneParentIndexAttributesConstRef FSkeletalMeshAttributesShared::GetBoneParentIndices () const
GetBonePoses()
SKELETALMESHDESCRIPTION_API FBonePoseAttributesConstRef FSkeletalMeshAttributesShared::GetBonePoses () const
GetMorphTargetNameFromAttribute()
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::GetMorphTargetNameFromAttribute (const FName InAttributeName) static
Returns the name of a morph target given the attribute name. If the given attribute name is invalid, NAME_None is returned.
GetMorphTargetNames()
SKELETALMESHDESCRIPTION_API TArray< FName > FSkeletalMeshAttributesShared::GetMorphTargetNames () const
Returns the list of all registered morph targets on this mesh.
GetNumBones()
SKELETALMESHDESCRIPTION_API int32 FSkeletalMeshAttributesShared::GetNumBones () const
Returns
the number of the bones. 0 if bone element does not exist in the FMeshDescription.
GetNumSourceGeometryParts()
SKELETALMESHDESCRIPTION_API int32 FSkeletalMeshAttributesShared::GetNumSourceGeometryParts () const
GetProfileNameFromAttribute()
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::GetProfileNameFromAttribute (const FName InAttributeName) static
Returns a skin profile name from the attribute name, if the attribute name is a valid skin weights attribute.
GetSkinWeightProfileNames()
SKELETALMESHDESCRIPTION_API TArray< FName > FSkeletalMeshAttributesShared::GetSkinWeightProfileNames (const bool bInUserDefinedOnly = false) const
Returns the list of all registered skin weight profile names on this mesh.
Parameters
bInUserDefinedOnly Only return user-defined profiles, not the default profile.
Returns
The list of the profile names.
GetSourceGeometryPartNames()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartNameConstRef FSkeletalMeshAttributesShared::GetSourceGeometryPartNames () const
GetSourceGeometryPartVertexOffsetAndCounts()
SKELETALMESHDESCRIPTION_API FSourceGeometryPartVertexOffsetAndCountConstRef FSkeletalMeshAttributesShared::GetSourceGeometryPartVertexOffsetAndCounts () const
GetVertexInstanceMorphNormalDelta()
SKELETALMESHDESCRIPTION_API TVertexInstanceAttributesConstRef< FVector3f > FSkeletalMeshAttributesShared::GetVertexInstanceMorphNormalDelta (const FName InMorphTargetName) const
Returns a read-only vertex instance normal delta attribute for the given morph target.
The delta is the difference between the normal vector of the mesh and the normal vector of the desired morphed mesh. Adding this value to the normal vector of the mesh will return the morph's normal vector for this vertex instance. If the morph was not registered to include normals, this will return an invalid attribute.
GetVertexMorphPositionDelta()
SKELETALMESHDESCRIPTION_API TVertexAttributesConstRef< FVector3f > FSkeletalMeshAttributesShared::GetVertexMorphPositionDelta (const FName InMorphTargetName) const
Returns a read-only vertex position delta attribute for the given morph target.
The delta is the difference between the point position of the mesh and the point position of the morphed mesh. Adding this value to the point position of the mesh will return the morph point position.
GetVertexSkinWeights()
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesConstRef FSkeletalMeshAttributesShared::GetVertexSkinWeights (const FName InProfileName = NAME_None) const
GetVertexSkinWeightsFromAttributeName()
SKELETALMESHDESCRIPTION_API FSkinWeightsVertexAttributesConstRef FSkeletalMeshAttributesShared::GetVertexSkinWeightsFromAttributeName (const FName InAttributeName = NAME_None) const
HasBoneColorAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::HasBoneColorAttribute () const
HasBoneNameAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::HasBoneNameAttribute () const
HasBoneParentIndexAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::HasBoneParentIndexAttribute () const
HasBonePoseAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::HasBonePoseAttribute () const
HasBones()
bool FSkeletalMeshAttributesShared::HasBones () const inline
Returns
true, if bone element was added to the MeshDescription.
Definition at line 163 of file SkeletalMeshAttributes.h.
References BoneElementsShared.
HasMorphTargetNormalsAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::HasMorphTargetNormalsAttribute (const FName InMorphTargetName) const
HasMorphTargetPositionsAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::HasMorphTargetPositionsAttribute (const FName InMorphTargetName) const
HasSourceGeometryParts()
bool FSkeletalMeshAttributesShared::HasSourceGeometryParts () const inline
Definition at line 184 of file SkeletalMeshAttributes.h.
References SourceGeometryPartElementsShared.
IsBoneValid()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::IsBoneValid (const FBoneID BoneID) const
Returns
true, if the passed bone ID is valid
IsMorphTargetAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::IsMorphTargetAttribute (const FName InAttributeName) static
Returns true if the given attribute name refers to a morph target attribute.
Referenced by FSkeletalMeshAttributes::IsReservedAttributeName().
IsSkinWeightAttribute()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::IsSkinWeightAttribute (const FName InAttributeName) static
Helper function that indicates whether an attribute name represents a skin weight attribute.
Referenced by FSkeletalMeshAttributes::IsReservedAttributeName().
IsSourceGeometryPartValid()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::IsSourceGeometryPartValid (const FSourceGeometryPartID InSourceGeometryPartID) const
IsValidSkinWeightProfileName()
SKELETALMESHDESCRIPTION_API bool FSkeletalMeshAttributesShared::IsValidSkinWeightProfileName (const FName InProfileName) static
Returns true if the given identifier is a valid profile name.
If the name is empty, or matches the default profile, then the profile name is considered invalid.
SourceGeometryPartAttributes()
SKELETALMESHDESCRIPTION_API const TAttributesSet< FSourceGeometryPartID > & FSkeletalMeshAttributesShared::SourceGeometryPartAttributes () const
SourceGeometryParts()
SKELETALMESHDESCRIPTION_API const FSourceGeometryPartArray & FSkeletalMeshAttributesShared::SourceGeometryParts () const
Field Documentation
BoneElementsShared
const FMeshElementChannels* FSkeletalMeshAttributesShared::BoneElementsShared = nullptr protected
Definition at line 210 of file SkeletalMeshAttributes.h.
Referenced by HasBones().
BonesElementName
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::BonesElementName static
Name of the mesh element type representing bones.
Note
this is different from the MeshAttribute::Bone::Name attribute. This is a name of the element that is added to the mesh description to represent Bones (similar to the Vertex/Polygons/Edges elements). MeshAttribute::Bone::Name is just one of the attributes of the Bones element.
Definition at line 78 of file SkeletalMeshAttributes.h.
DefaultSkinWeightProfileName
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::DefaultSkinWeightProfileName static
Definition at line 90 of file SkeletalMeshAttributes.h.
MeshDescriptionShared
const FMeshDescription& FSkeletalMeshAttributesShared::MeshDescriptionShared private
Definition at line 214 of file SkeletalMeshAttributes.h.
SourceGeometryPartElementName
SKELETALMESHDESCRIPTION_API FName FSkeletalMeshAttributesShared::SourceGeometryPartElementName static
Name of the mesh element representing import data for meshes that were imported from separate geometries into a single skeletal mesh piece.
Can be used to match parts of the mesh back to the constituent parts of the import source.
Definition at line 86 of file SkeletalMeshAttributes.h.
SourceGeometryPartElementsShared
const FMeshElementChannels* FSkeletalMeshAttributesShared::SourceGeometryPartElementsShared = nullptr protected
Definition at line 211 of file SkeletalMeshAttributes.h.
Referenced by HasSourceGeometryParts().
The documentation for this class was generated from the following file:
Runtime/SkeletalMeshDescription/Public/SkeletalMeshAttributes.h