Unreal Engine 5.6 C++ API: UUVEditorChannelEditTargetProperties Class Reference
UUVEditorChannelEditTargetProperties Class Reference
#include "UVEditorLayerEditTool.h"
Public Member Functions
const TArray< FString > & GetAssetNames ()
int32 GetSelectedAssetID ()
int32 GetSelectedChannelIndex (bool bForceToZeroOnFailure=false, bool bUseReference=false)
const TArray< FString > & GetUVChannelNames ()
void Initialize (const TArray< TObjectPtr< UUVEditorToolMeshInput > > &TargetsIn, bool bInitializeSelection)
void SetUsageFlags (EChannelEditToolAction Action)
bool ValidateUVAssetSelection (bool bUpdateIfInvalid)
Verify that the UV asset selection is valid.
bool ValidateUVChannelSelection (bool bUpdateIfInvalid)
Verify that the UV channel selection is valid.
Data Fields
FString Asset
bool bActionNeedsAsset = true
bool bActionNeedsReference = false
bool bActionNeedsTarget = true
TArray< int32 > NumUVChannelsPerAsset
FString ReferenceChannel
FString TargetChannel
TArray< FString > UVAssetNames
TArray< FString > UVChannelNames
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Definition at line 53 of file UVEditorLayerEditTool.h.
Member Function Documentation
GetAssetNames()
const TArray< FString > & UUVEditorChannelEditTargetProperties::GetAssetNames ()
References Category, GetAssetNames(), GetUVChannelNames(), meta, and UPROPERTY.
Referenced by GetAssetNames().
GetSelectedAssetID()
int32 UUVEditorChannelEditTargetProperties::GetSelectedAssetID ()
Returns
selected UV asset ID, or -1 if invalid selection
References GetSelectedAssetID().
Referenced by GetSelectedAssetID().
GetSelectedChannelIndex()
int32 UUVEditorChannelEditTargetProperties::GetSelectedChannelIndex (bool bForceToZeroOnFailure = false, bool bUseReference = false)
Parameters
bForceToZeroOnFailure if true, then instead of returning -1 we return 0 so calling code can fallback to default UV paths
bUseReference if true, get the selected reference channel index, otherwise return the target channel's index.
Returns
selected UV channel index, or -1 if invalid selection, or 0 if invalid selection and bool bForceToZeroOnFailure = true
References GetSelectedChannelIndex(), and UCLASS.
Referenced by GetSelectedChannelIndex().
GetUVChannelNames()
const TArray< FString > & UUVEditorChannelEditTargetProperties::GetUVChannelNames ()
References GetUVChannelNames().
Referenced by GetAssetNames(), and GetUVChannelNames().
Initialize()
void UUVEditorChannelEditTargetProperties::Initialize (const TArray< TObjectPtr< UUVEditorToolMeshInput > > & TargetsIn, bool bInitializeSelection)
References Initialize().
Referenced by Initialize().
SetUsageFlags()
void UUVEditorChannelEditTargetProperties::SetUsageFlags (EChannelEditToolAction Action)
References SetUsageFlags().
Referenced by SetUsageFlags().
ValidateUVAssetSelection()
bool UUVEditorChannelEditTargetProperties::ValidateUVAssetSelection (bool bUpdateIfInvalid)
Verify that the UV asset selection is valid.
Parameters
bUpdateIfInvalid if selection is not valid, reset UVAsset to Asset0 or empty if no assets exist
Returns
true if selection in UVAsset is an entry in UVAssetNames.
References ValidateUVAssetSelection().
Referenced by ValidateUVAssetSelection().
ValidateUVChannelSelection()
bool UUVEditorChannelEditTargetProperties::ValidateUVChannelSelection (bool bUpdateIfInvalid)
Verify that the UV channel selection is valid.
Parameters
bUpdateIfInvalid if selection is not valid, UVChannel to UV0 or empty if no UV channels exist
Returns
true if selection in UVChannel is an entry in UVChannelNamesList.
References ValidateUVChannelSelection().
Referenced by ValidateUVChannelSelection().
Field Documentation
Asset
FString UUVEditorChannelEditTargetProperties::Asset
Definition at line 59 of file UVEditorLayerEditTool.h.
bActionNeedsAsset
bool UUVEditorChannelEditTargetProperties::bActionNeedsAsset = true
Definition at line 80 of file UVEditorLayerEditTool.h.
bActionNeedsReference
bool UUVEditorChannelEditTargetProperties::bActionNeedsReference = false
Definition at line 83 of file UVEditorLayerEditTool.h.
bActionNeedsTarget
bool UUVEditorChannelEditTargetProperties::bActionNeedsTarget = true
Definition at line 86 of file UVEditorLayerEditTool.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorChannelEditTargetProperties::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 55 of file UVEditorLayerEditTool.h.
NumUVChannelsPerAsset
TArray<int32> UUVEditorChannelEditTargetProperties::NumUVChannelsPerAsset
Definition at line 77 of file UVEditorLayerEditTool.h.
ReferenceChannel
FString UUVEditorChannelEditTargetProperties::ReferenceChannel
Definition at line 68 of file UVEditorLayerEditTool.h.
TargetChannel
FString UUVEditorChannelEditTargetProperties::TargetChannel
Definition at line 65 of file UVEditorLayerEditTool.h.
UVAssetNames
TArray<FString> UUVEditorChannelEditTargetProperties::UVAssetNames
Definition at line 74 of file UVEditorLayerEditTool.h.
UVChannelNames
TArray<FString> UUVEditorChannelEditTargetProperties::UVChannelNames
Definition at line 73 of file UVEditorLayerEditTool.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/UVEditorLayerEditTool.h