Unreal Engine 5.6 C++ API: Metasound::TOutputStorage< DataType > Class Template Reference
Metasound::TOutputStorage< DataType > Class Template Reference final
#include "MetasoundOutputStorage.h"
Public Member Functions
TOutputStorage (const DataType &InData)
virtual TUniquePtr< IOutputStorage > Clone () const override
const DataType & Get () const
virtual FName GetDataTypeName () const override
void Set (const DataType &Value)
void Set (DataType &&Value)
Public Member Functions inherited from Metasound::IOutputStorage
virtual ~IOutputStorage ()=default
Private Attributes
DataType Data
Detailed Description
template<typename DataType>
class Metasound::TOutputStorage< DataType >
Definition at line 21 of file MetasoundOutputStorage.h.
Constructor & Destructor Documentation
TOutputStorage()
template<typename DataType> Metasound::TOutputStorage< DataType >::TOutputStorage (const DataType & InData) inline explicit
Definition at line 24 of file MetasoundOutputStorage.h.
References Data.
Member Function Documentation
Clone()
template<typename DataType> virtual TUniquePtr< IOutputStorage > Metasound::TOutputStorage< DataType >::Clone () const inline override virtual
Implements Metasound::IOutputStorage.
Definition at line 34 of file MetasoundOutputStorage.h.
References Data, and MakeUnique().
Get()
template<typename DataType> const DataType & Metasound::TOutputStorage< DataType >::Get () const inline
Definition at line 49 of file MetasoundOutputStorage.h.
References Data.
GetDataTypeName()
template<typename DataType> virtual FName Metasound::TOutputStorage< DataType >::GetDataTypeName () const inline override virtual
Implements Metasound::IOutputStorage.
Definition at line 28 of file MetasoundOutputStorage.h.
References Metasound::GetMetasoundDataTypeName().
Set() [1/2]
template<typename DataType> void Metasound::TOutputStorage< DataType >::Set (const DataType & Value) inline
Definition at line 39 of file MetasoundOutputStorage.h.
References Data, and Metasound::Value.
Set() [2/2]
template<typename DataType> void Metasound::TOutputStorage< DataType >::Set (DataType && Value) inline
Definition at line 44 of file MetasoundOutputStorage.h.
References Data, MoveTemp(), and Metasound::Value.
Field Documentation
Data
template<typename DataType> DataType Metasound::TOutputStorage< DataType >::Data private
Definition at line 55 of file MetasoundOutputStorage.h.
Referenced by TOutputStorage(), Clone(), Get(), Set(), and Set().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundOutputStorage.h