Unreal Engine 5.6 C++ API: UE::Geometry::TMeshSimplification< QuadricErrorType > Class Template Reference
UE::Geometry::TMeshSimplification< QuadricErrorType > Class Template Reference
Implementation of Garland & Heckbert Quadric Error Metric (QEM) Triangle Mesh Simplification.
#include "MeshSimplification.h"
Data Structures
struct FEdgeError
struct QEdge
Public Types
enum class EGeometricErrorCriteria { None = 0 , PredictedPointToProjectionTarget = 1 }
Ways to measure geometric error.
enum class ESimplificationCollapseModes { MinimalQuadricPositionError = 0 , MinimalExistingVertexError = 1 , AverageVertexPosition = 2 }
typedef QuadricErrorType FQuadricErrorType
typedef TQuadricError< RealType > FSeamQuadricType
typedef FQuadricErrorType::ScalarType RealType
Public Types inherited from UE::Geometry::FMeshRefinerBase
enum class ETargetProjectionMode : uint8 { NoProjection = 0 , AfterRefinement = 1 , Inline = 2 }
Options for projecting vertices onto target surface.
enum class EVertexControl : uint8 { AllowAll = 0 , NoSmooth = 1 , NoProject = 2 , NoMovement = NoSmooth | NoProject }
Public Member Functions
TMeshSimplification (FDynamicMesh3 *m)
virtual DYNAMICMESH_API void FastCollapsePass (double MinEdgeLength, int Rounds=1, bool bMeshIsClosedHint=false, uint32 MinTriangleCount=0)
Does N rounds of collapsing edges longer than fMinEdgeLength.
virtual DYNAMICMESH_API void SimplifyToEdgeLength (double MinEdgeLength)
Simplify mesh until no edges smaller than min length remain.
virtual DYNAMICMESH_API void SimplifyToMaxError (double MaxError)
Simplify mesh until the quadric error of an edge collapse exceeds the specified criteria.
virtual DYNAMICMESH_API void SimplifyToMinimalPlanar (double CoplanarAngleTolDeg=0.001, TFunctionRef< bool(int32 EdgeID)> EdgeFilterPredicate=[](int32) { return true;})
Maximally collapse mesh in a way that does not change shape at all.
virtual DYNAMICMESH_API void SimplifyToTriangleCount (int TriangleCount)
Simplify mesh until we reach a specific triangle count.
virtual DYNAMICMESH_API void SimplifyToVertexCount (int VertexCount)
Simplify mesh until it has a specific vertex count.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBase
FMeshRefinerBase (const FMeshRefinerBase &)=delete
FMeshRefinerBase (FMeshRefinerBase &&)=delete
virtual ~FMeshRefinerBase ()
virtual bool Cancelled ()
If this returns true, abort computation.
const TOptional< FMeshConstraints > & GetConstraints ()
Get the current mesh constraints.
double GetEdgeFlipTolerance ()
FDynamicMesh3 * GetMesh ()
Get the current mesh we are operating on.
FMeshRefinerBase & operator= (const FMeshRefinerBase &)=delete
FMeshRefinerBase & operator= (FMeshRefinerBase &&)=delete
IProjectionTarget * ProjectionTarget ()
Get the current Projection Target.
void SetEdgeFlipTolerance (double NewTolerance)
Set edge flip tolerance.
void SetExternalConstraints (TOptional< FMeshConstraints > ConstraintsIn)
Set external constraints.
DYNAMICMESH_API void SetMeshChangeTracker (FDynamicMeshChangeTracker *Tracker)
void SetProjectionTarget (IProjectionTarget *TargetIn)
Set a Projection Target.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBaseFixLayout
virtual ~FMeshRefinerBaseFixLayout ()=default
Data Fields
bool bAllowSeamCollapse = true
if true, we allow UV and Normal seams to collapse during simplification.
bool bPreserveBoundaryShape = true
if true, we try to keep boundary vertices on boundary.
bool bPreventTinyTriangles = false
Controls whether we disallow creation of triangles with small areas inside edge operations.
bool bRetainQuadricMemory = false
if false, face and vertex quadrics are recomputed in the neighborhood of each collapse, definitely slower but maybe higher quality
ESimplificationCollapseModes CollapseMode = ESimplificationCollapseModes::MinimalQuadricPositionError
Controls the method used when selecting the position the results from an edge collapse.
EGeometricErrorCriteria GeometricErrorConstraint = EGeometricErrorCriteria::None
Geometric error measurement/check to perform before allowing an edge collapse.
double GeometricErrorTolerance = 0.0
Tolerance to use in geometric error checking.
EEdgeRefineFlags GroupBoundaryConstraint
EEdgeRefineFlags MaterialBoundaryConstraint
EEdgeRefineFlags MeshBoundaryConstraint
When using the constraint system, these options will apply to the appropriate boundaries.
Data Fields inherited from UE::Geometry::FMeshRefinerBase
bool AllowCollapseFixedVertsWithSameSetID = true
If true, then when two Fixed vertices have the same non-invalid SetID, we treat them as not fixed and allow collapse.
int DEBUG_CHECK_LEVEL = 0
0 = no checking, 1 = check constraints each pass, 2 = and check validity each pass, 3 = and check validity after every mesh change (v slow but best for debugging)
TArray< int > DebugEdges
This is a debugging aid, will break to debugger if these edges are touched, in debug builds.
bool ENABLE_PROFILING = false
Set to true to profile various passes.
FProgressCancel * Progress = nullptr
Set this to be able to cancel running Remesher/Reducer.
ETargetProjectionMode ProjectionMode = ETargetProjectionMode::NoProjection
Method to use to project vertices onto target surface.
TFunction< EVertexControl(int)> VertexControlF = nullptr
This function allows client to specify fine-grained control over what happens to specific vertices.
Protected Types
enum class ETargetModes { TriangleCount = 0 , VertexCount = 1 , MinEdgeLength = 2 , MaxError = 3 }
Protected Member Functions
TMeshSimplification ()
virtual DYNAMICMESH_API void ApplyToProjectVertices (const TFunction< void(int)> &apply_f)
FQuadricErrorType AssembleEdgeQuadric (const FDynamicMesh3::FEdge &edge) const
bool CanCollapseEdge (int edgeID, int a, int b, int c, int d, int t0, int t1, int &collapse_to) const
Figure out if we can collapse edge eid=[a,b] under current constraint set This depends on the base class function FMeshRefinerBase::CanCollapseEdge, but includes additional restrictions specified by the CollapseMode of this simplifier.
bool CheckIfCollapseWithinGeometricTolerance (int vid, int vother, const FVector3d &newv, int tc, int td)
Check if edge collapse would violate geometric error criteria.
ESimplificationResult CollapseEdge (int edgeID, FVector3d vNewPos, FDynamicMesh3::FEdgeCollapseInfo &collapseInfo, int32 RequireKeepVert=-1)
Collapse given edge.
FQuadricErrorType ComputeFaceQuadric (const int tid, FVector3d &nface, FVector3d &c, double &Area) const
virtual DYNAMICMESH_API void DoSimplify ()
Top-level function that does the simplification.
bool EnableInlineProjection () const
virtual DYNAMICMESH_API void FullProjectionPass ()
virtual int GetNextEdge (int CurEdgeID, bool &bDoneOut)
virtual DYNAMICMESH_API FVector3d GetProjectedCollapsePosition (int vid, const FVector3d &vNewPos)
FVector3d GetProjectedPoint (const FVector3d &pos)
virtual DYNAMICMESH_API void InitializeQueue ()
virtual DYNAMICMESH_API void InitializeSeamQuadrics ()
virtual DYNAMICMESH_API void InitializeTriQuadrics ()
virtual DYNAMICMESH_API void InitializeVertexQuadrics ()
bool IsBoundaryVertex (int vid) const
virtual DYNAMICMESH_API void OnEdgeCollapse (int edgeID, int va, int vb, const FDynamicMesh3::FEdgeCollapseInfo &collapseInfo)
virtual DYNAMICMESH_API void OnRemoveIsolatedTriangle (int tId)
FVector3d OptimalPoint (int eid, const FQuadricErrorType &q, int ea, int eb)
void Precompute (bool bMeshIsClosed=false)
virtual void ProfileBeginCollapse ()
virtual void ProfileBeginOps ()
virtual void ProfileBeginPass ()
virtual void ProfileBeginProject ()
virtual void ProfileBeginSetup ()
virtual void ProfileEndCollapse ()
virtual void ProfileEndOps ()
virtual void ProfileEndPass ()
virtual void ProfileEndProject ()
virtual void ProfileEndSetup ()
virtual DYNAMICMESH_API void ProjectVertex (int vID, IProjectionTarget *targetIn)
bool RemoveIsolatedTriangle (int tID)
Remove an isolated triangle.
virtual void Reproject ()
virtual int StartEdges ()
virtual DYNAMICMESH_API void UpdateNeighborhood (const FDynamicMesh3::FEdgeCollapseInfo &collapseInfo)
Protected Member Functions inherited from UE::Geometry::FMeshRefinerBase
FMeshRefinerBase ()
FMeshRefinerBase (FDynamicMesh3 *MeshIn)
DYNAMICMESH_API bool CanCollapseEdge (int eid, int a, int b, int c, int d, int tc, int td, int &collapse_to) const
Figure out if we can collapse edge eid=[a,b] under current constraint set.
DYNAMICMESH_API bool CanCollapseVertex (int eid, int a, int b, int &collapse_to) const
Resolve vertex constraints for collapsing edge eid=[a,b].
DYNAMICMESH_API bool CheckIfCollapseCreatesFlipOrInvalid (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a face-normal flip.
DYNAMICMESH_API bool CheckIfCollapseCreatesTinyTriangle (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a triangle with small area (either all vertices are close together, or in a sliver configuration) This only checks one-ring of vid, so you have to call it twice, with vid and vother reversed, to check both one-rings.
DYNAMICMESH_API bool CheckIfFlipCreatesTinyTriangle (int OriginalEdgeVertexA, int OriginalEdgeVertexB, int OppositeEdgeVertexC, int OppositeEdgeVertexD, int OriginalTriangleIndex) const
Check if edge flip might create a triangle with small area (either all vertices are close together, or in a sliver configuration)
DYNAMICMESH_API bool CheckIfFlipInvertsNormals (int a, int b, int c, int d, int t0) const
Check if edge flip might reverse normal direction.
double ComputeEdgeFlipMetric (const FVector3d &Direction0, const FVector3d &Direction1) const
DYNAMICMESH_API void DebugCheckUVSeamConstraints ()
DYNAMICMESH_API void DebugCheckVertexConstraints ()
virtual DYNAMICMESH_API void DoDebugChecks (bool bEndOfPass=false)
FVertexConstraint GetVertexConstraint (int VertexID)
bool GetVertexConstraint (int VertexID, FVertexConstraint &OutConstraint)
bool IsVertexPositionConstrained (int VertexID)
DYNAMICMESH_API void RuntimeDebugCheck (int EdgeID)
virtual DYNAMICMESH_API void SaveEdgeBeforeModify (int32 EdgeID)
virtual DYNAMICMESH_API void SaveTriangleBeforeModify (int32 TriangleID)
virtual DYNAMICMESH_API void SaveVertexTrianglesBeforeModify (int32 VertexID)
Protected Attributes
bool bHaveBoundary
int COUNT_COLLAPSES
int COUNT_ITERATIONS
TArray< QEdge > EdgeQuadrics
FIndexPriorityQueue EdgeQueue
TArray< bool > IsBoundaryVtxCache
uint64 MaxEdgeID = 0
float MaxErrorAllowed = FLT_MAX
double MinEdgeLength = FMathd::MaxReal
FDynamicMeshNormalOverlay * NormalOverlay
double SeamEdgeWeight = 256.
TMap< int, FSeamQuadricType > seamQuadrics
ETargetModes SimplifyMode = ETargetModes::TriangleCount
int TargetCount = INT_MAX
TArray< double > triAreas
TArray< FQuadricErrorType > triQuadrics
TArray< FQuadricErrorType > vertQuadrics
Protected Attributes inherited from UE::Geometry::FMeshRefinerBase
FDynamicMeshChangeTracker * ActiveChangeTracker = nullptr
TOptional< FMeshConstraints > Constraints
Constraints are used to control how certain edges and vertices can be modified.
double EdgeFlipTolerance = 0.0f
If normals dot product is less than this, we consider it a normal flip.
FDynamicMesh3 * Mesh = nullptr
Mesh that will be refined.
IProjectionTarget * ProjTarget = nullptr
Vertices can be projected onto this surface when they are modified.
double TinyTriangleThreshold = SMALL_NUMBER
Avoid creation of triangles smaller than this value.
Detailed Description
template<typename QuadricErrorType>
class UE::Geometry::TMeshSimplification< QuadricErrorType >
Implementation of Garland & Heckbert Quadric Error Metric (QEM) Triangle Mesh Simplification.
Definition at line 38 of file MeshSimplification.h.
Member Typedef Documentation
FQuadricErrorType
template<typename QuadricErrorType> typedef QuadricErrorType UE::Geometry::TMeshSimplification< QuadricErrorType >::FQuadricErrorType
Definition at line 42 of file MeshSimplification.h.
FSeamQuadricType
template<typename QuadricErrorType> typedef TQuadricError<RealType> UE::Geometry::TMeshSimplification< QuadricErrorType >::FSeamQuadricType
Definition at line 44 of file MeshSimplification.h.
RealType
template<typename QuadricErrorType> typedef FQuadricErrorType::ScalarType UE::Geometry::TMeshSimplification< QuadricErrorType >::RealType
Definition at line 43 of file MeshSimplification.h.
Member Enumeration Documentation
EGeometricErrorCriteria
template<typename QuadricErrorType> enum class UE::Geometry::TMeshSimplification::EGeometricErrorCriteria strong
Ways to measure geometric error.
Enumerator
None
No geometric error checking.
PredictedPointToProjectionTarget
Fixed envelope around projection target.
Definition at line 90 of file MeshSimplification.h.
ESimplificationCollapseModes
template<typename QuadricErrorType> enum class UE::Geometry::TMeshSimplification::ESimplificationCollapseModes strong
Enumerator
MinimalQuadricPositionError
MinimalExistingVertexError
AverageVertexPosition
Definition at line 47 of file MeshSimplification.h.
ETargetModes
template<typename QuadricErrorType> enum class UE::Geometry::TMeshSimplification::ETargetModes strong protected
Enumerator
TriangleCount
VertexCount
MinEdgeLength
MaxError
Definition at line 176 of file MeshSimplification.h.
Constructor & Destructor Documentation
TMeshSimplification() [1/2]
template<typename QuadricErrorType> UE::Geometry::TMeshSimplification< QuadricErrorType >::TMeshSimplification (FDynamicMesh3 * m) inline
Definition at line 105 of file MeshSimplification.h.
TMeshSimplification() [2/2]
template<typename QuadricErrorType> UE::Geometry::TMeshSimplification< QuadricErrorType >::TMeshSimplification () inline protected
Definition at line 166 of file MeshSimplification.h.
Member Function Documentation
ApplyToProjectVertices()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::ApplyToProjectVertices (const TFunction< void(int)> & apply_f) protected virtual
AssembleEdgeQuadric()
template<typename QuadricErrorType> FQuadricErrorType UE::Geometry::TMeshSimplification< QuadricErrorType >::AssembleEdgeQuadric (const FDynamicMesh3::FEdge & edge) const protected
CanCollapseEdge()
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::CanCollapseEdge (int edgeID, int a, int b, int c, int d, int t0, int t1, int & collapse_to) const protected
Figure out if we can collapse edge eid=[a,b] under current constraint set This depends on the base class function FMeshRefinerBase::CanCollapseEdge, but includes additional restrictions specified by the CollapseMode of this simplifier.
See the base class for description of parameters.
CheckIfCollapseWithinGeometricTolerance()
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::CheckIfCollapseWithinGeometricTolerance (int vid, int vother, const FVector3d & newv, int tc, int td) protected
Check if edge collapse would violate geometric error criteria.
Parameters
vid first vertex of edge
vother other vertex of edge
newv new vertex position after collapse
tc triangle on one side of edge
td triangle on other side of edge
CollapseEdge()
template<typename QuadricErrorType> ESimplificationResult UE::Geometry::TMeshSimplification< QuadricErrorType >::CollapseEdge (int edgeID, FVector3d vNewPos, FDynamicMesh3::FEdgeCollapseInfo & collapseInfo, int32 RequireKeepVert = -1) protected
Collapse given edge.
Parameters
RequireCollapseToVert if >= 0 and after constraints/etc the vertex we will collapse "to" cannot be this vertex, do not collapse
ComputeFaceQuadric()
template<typename QuadricErrorType> FQuadricErrorType UE::Geometry::TMeshSimplification< QuadricErrorType >::ComputeFaceQuadric (const int tid, FVector3d & nface, FVector3d & c, double & Area) const protected
DoSimplify()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::DoSimplify () protected virtual
Top-level function that does the simplification.
EnableInlineProjection()
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::EnableInlineProjection () const inline protected
Definition at line 171 of file MeshSimplification.h.
Referenced by UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::GetProjectedPoint().
FastCollapsePass()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::FastCollapsePass (double MinEdgeLength, int Rounds = 1, bool bMeshIsClosedHint = false, uint32 MinTriangleCount = 0) virtual
Does N rounds of collapsing edges longer than fMinEdgeLength.
Does not use Quadrics or priority queue. This is a quick way to get triangle count down on huge meshes (eg like marching cubes output).
Parameters
MinEdgeLength collapse any edge longer than this
Rounds number of collapse rounds
MeshIsClosedHint if you know the mesh is closed, this pass this true to avoid some precomputes
MinTriangleCount halt fast collapse if mesh falls below this triangle count
FullProjectionPass()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::FullProjectionPass () protected virtual
Referenced by UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::Reproject().
GetNextEdge()
template<typename QuadricErrorType> virtual int UE::Geometry::TMeshSimplification< QuadricErrorType >::GetNextEdge (int CurEdgeID, bool & bDoneOut) inline protected virtual
Definition at line 204 of file MeshSimplification.h.
GetProjectedCollapsePosition()
template<typename QuadricErrorType> virtual DYNAMICMESH_API FVector3d UE::Geometry::TMeshSimplification< QuadricErrorType >::GetProjectedCollapsePosition (int vid, const FVector3d & vNewPos) protected virtual
GetProjectedPoint()
template<typename QuadricErrorType> FVector3d UE::Geometry::TMeshSimplification< QuadricErrorType >::GetProjectedPoint (const FVector3d & pos) inline protected
Definition at line 269 of file MeshSimplification.h.
InitializeQueue()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::InitializeQueue () protected virtual
InitializeSeamQuadrics()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::InitializeSeamQuadrics () protected virtual
InitializeTriQuadrics()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::InitializeTriQuadrics () protected virtual
InitializeVertexQuadrics()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::InitializeVertexQuadrics () protected virtual
IsBoundaryVertex()
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::IsBoundaryVertex (int vid) const inline protected
Definition at line 302 of file MeshSimplification.h.
OnEdgeCollapse()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::OnEdgeCollapse (int edgeID, int va, int vb, const FDynamicMesh3::FEdgeCollapseInfo & collapseInfo) protected virtual
OnRemoveIsolatedTriangle()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::OnRemoveIsolatedTriangle (int tId) protected virtual
OptimalPoint()
template<typename QuadricErrorType> FVector3d UE::Geometry::TMeshSimplification< QuadricErrorType >::OptimalPoint (int eid, const FQuadricErrorType & q, int ea, int eb) protected
Precompute()
template<typename QuadricErrorType> void UE::Geometry::TMeshSimplification< QuadricErrorType >::Precompute (bool bMeshIsClosed = false) protected
ProfileBeginCollapse()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileBeginCollapse () inline protected virtual
Definition at line 422 of file MeshSimplification.h.
ProfileBeginOps()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileBeginOps () inline protected virtual
Definition at line 396 of file MeshSimplification.h.
ProfileBeginPass()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileBeginPass () inline protected virtual
Definition at line 370 of file MeshSimplification.h.
ProfileBeginProject()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileBeginProject () inline protected virtual
Definition at line 413 of file MeshSimplification.h.
Referenced by UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::Reproject().
ProfileBeginSetup()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileBeginSetup () inline protected virtual
Definition at line 404 of file MeshSimplification.h.
ProfileEndCollapse()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileEndCollapse () inline protected virtual
Definition at line 426 of file MeshSimplification.h.
ProfileEndOps()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileEndOps () inline protected virtual
Definition at line 400 of file MeshSimplification.h.
ProfileEndPass()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileEndPass () inline protected virtual
Definition at line 383 of file MeshSimplification.h.
ProfileEndProject()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileEndProject () inline protected virtual
Definition at line 417 of file MeshSimplification.h.
Referenced by UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::Reproject().
ProfileEndSetup()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProfileEndSetup () inline protected virtual
Definition at line 408 of file MeshSimplification.h.
ProjectVertex()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::ProjectVertex (int vID, IProjectionTarget * targetIn) protected virtual
RemoveIsolatedTriangle()
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::RemoveIsolatedTriangle (int tID) protected
Remove an isolated triangle.
Returns
false if the triangle shares a vertex with another triangle
Reproject()
template<typename QuadricErrorType> virtual void UE::Geometry::TMeshSimplification< QuadricErrorType >::Reproject () inline protected virtual
Definition at line 283 of file MeshSimplification.h.
SimplifyToEdgeLength()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::SimplifyToEdgeLength (double MinEdgeLength) virtual
Simplify mesh until no edges smaller than min length remain.
This is not a great criteria.
Parameters
MinEdgeLength collapse any edge longer than this
SimplifyToMaxError()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::SimplifyToMaxError (double MaxError) virtual
Simplify mesh until the quadric error of an edge collapse exceeds the specified criteria.
Parameters
MaxError collapse an edge if the corresponding quadric error exceeds this
SimplifyToMinimalPlanar()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::SimplifyToMinimalPlanar (double CoplanarAngleTolDeg = 0.001, TFunctionRef< bool(int32 EdgeID)> EdgeFilterPredicate = [](int32) { return true;}) virtual
Maximally collapse mesh in a way that does not change shape at all.
This process does not involve quadric error at all.
Parameters
AngleTolDeg two triangles are considered coplanar if their normals are within this angle tolerance
EdgeFilterPredicate only edges that pass this predicate will be considered for collapse. Default all true.
SimplifyToTriangleCount()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::SimplifyToTriangleCount (int TriangleCount) virtual
Simplify mesh until we reach a specific triangle count.
Note that because triangles are removed in pairs, the resulting count may be TriangleCount-1
Parameters
TriangleCount the target triangle count
SimplifyToVertexCount()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::SimplifyToVertexCount (int VertexCount) virtual
Simplify mesh until it has a specific vertex count.
Parameters
VertexCount the target vertex count
StartEdges()
template<typename QuadricErrorType> virtual int UE::Geometry::TMeshSimplification< QuadricErrorType >::StartEdges () inline protected virtual
Definition at line 198 of file MeshSimplification.h.
UpdateNeighborhood()
template<typename QuadricErrorType> virtual DYNAMICMESH_API void UE::Geometry::TMeshSimplification< QuadricErrorType >::UpdateNeighborhood (const FDynamicMesh3::FEdgeCollapseInfo & collapseInfo) protected virtual
Field Documentation
bAllowSeamCollapse
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::bAllowSeamCollapse = true
if true, we allow UV and Normal seams to collapse during simplification.
Definition at line 78 of file MeshSimplification.h.
bHaveBoundary
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::bHaveBoundary protected
Definition at line 298 of file MeshSimplification.h.
bPreserveBoundaryShape
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::bPreserveBoundaryShape = true
if true, we try to keep boundary vertices on boundary.
You probably want this if you aren't using seam quadrics.
Definition at line 75 of file MeshSimplification.h.
bPreventTinyTriangles
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::bPreventTinyTriangles = false
Controls whether we disallow creation of triangles with small areas inside edge operations.
This is moderately expensive and in some cases can result in lower-quality meshes. Disabled by default.
Definition at line 83 of file MeshSimplification.h.
bRetainQuadricMemory
template<typename QuadricErrorType> bool UE::Geometry::TMeshSimplification< QuadricErrorType >::bRetainQuadricMemory = false
if false, face and vertex quadrics are recomputed in the neighborhood of each collapse, definitely slower but maybe higher quality
Definition at line 70 of file MeshSimplification.h.
CollapseMode
template<typename QuadricErrorType> ESimplificationCollapseModes UE::Geometry::TMeshSimplification< QuadricErrorType >::CollapseMode = ESimplificationCollapseModes::MinimalQuadricPositionError
Controls the method used when selecting the position the results from an edge collapse.
Note some of the simpler methods (such as average) may be significantly slower as they result in many more points that are rejected because the would cause a triangle flip.
MinimalQuadricPositionError Try to find position for collapsed vertices that minimizes quadric error. If false we just use midpoints, which is actually significantly slower, because it results in many more points that would cause a triangle flip, which are then rejected.
MinimalExistingVertexError Use one of the existing vertex position with smallest error for the collapse point.
AverageVertexPosition Use the midpoint of the two vertex positions.
Definition at line 67 of file MeshSimplification.h.
COUNT_COLLAPSES
template<typename QuadricErrorType> int UE::Geometry::TMeshSimplification< QuadricErrorType >::COUNT_COLLAPSES protected
Definition at line 366 of file MeshSimplification.h.
COUNT_ITERATIONS
template<typename QuadricErrorType> int UE::Geometry::TMeshSimplification< QuadricErrorType >::COUNT_ITERATIONS protected
Definition at line 367 of file MeshSimplification.h.
EdgeQuadrics
template<typename QuadricErrorType> TArray<QEdge> UE::Geometry::TMeshSimplification< QuadricErrorType >::EdgeQuadrics protected
Definition at line 251 of file MeshSimplification.h.
EdgeQueue
template<typename QuadricErrorType> FIndexPriorityQueue UE::Geometry::TMeshSimplification< QuadricErrorType >::EdgeQueue protected
Definition at line 252 of file MeshSimplification.h.
GeometricErrorConstraint
template<typename QuadricErrorType> EGeometricErrorCriteria UE::Geometry::TMeshSimplification< QuadricErrorType >::GeometricErrorConstraint = EGeometricErrorCriteria::None
Geometric error measurement/check to perform before allowing an edge collapse.
Definition at line 99 of file MeshSimplification.h.
GeometricErrorTolerance
template<typename QuadricErrorType> double UE::Geometry::TMeshSimplification< QuadricErrorType >::GeometricErrorTolerance = 0.0
Tolerance to use in geometric error checking.
Definition at line 102 of file MeshSimplification.h.
GroupBoundaryConstraint
template<typename QuadricErrorType> EEdgeRefineFlags UE::Geometry::TMeshSimplification< QuadricErrorType >::GroupBoundaryConstraint
Definition at line 86 of file MeshSimplification.h.
IsBoundaryVtxCache
template<typename QuadricErrorType> TArray<bool> UE::Geometry::TMeshSimplification< QuadricErrorType >::IsBoundaryVtxCache protected
Definition at line 299 of file MeshSimplification.h.
MaterialBoundaryConstraint
template<typename QuadricErrorType> EEdgeRefineFlags UE::Geometry::TMeshSimplification< QuadricErrorType >::MaterialBoundaryConstraint
Definition at line 86 of file MeshSimplification.h.
MaxEdgeID
template<typename QuadricErrorType> uint64 UE::Geometry::TMeshSimplification< QuadricErrorType >::MaxEdgeID = 0 protected
Definition at line 197 of file MeshSimplification.h.
MaxErrorAllowed
template<typename QuadricErrorType> float UE::Geometry::TMeshSimplification< QuadricErrorType >::MaxErrorAllowed = FLT_MAX protected
Definition at line 173 of file MeshSimplification.h.
MeshBoundaryConstraint
template<typename QuadricErrorType> EEdgeRefineFlags UE::Geometry::TMeshSimplification< QuadricErrorType >::MeshBoundaryConstraint
When using the constraint system, these options will apply to the appropriate boundaries.
Definition at line 86 of file MeshSimplification.h.
MinEdgeLength
template<typename QuadricErrorType> double UE::Geometry::TMeshSimplification< QuadricErrorType >::MinEdgeLength = FMathd::MaxReal protected
Definition at line 174 of file MeshSimplification.h.
NormalOverlay
template<typename QuadricErrorType> FDynamicMeshNormalOverlay* UE::Geometry::TMeshSimplification< QuadricErrorType >::NormalOverlay protected
Definition at line 226 of file MeshSimplification.h.
SeamEdgeWeight
template<typename QuadricErrorType> double UE::Geometry::TMeshSimplification< QuadricErrorType >::SeamEdgeWeight = 256. protected
Definition at line 214 of file MeshSimplification.h.
seamQuadrics
template<typename QuadricErrorType> TMap<int, FSeamQuadricType> UE::Geometry::TMeshSimplification< QuadricErrorType >::seamQuadrics protected
Definition at line 219 of file MeshSimplification.h.
SimplifyMode
template<typename QuadricErrorType> ETargetModes UE::Geometry::TMeshSimplification< QuadricErrorType >::SimplifyMode = ETargetModes::TriangleCount protected
Definition at line 183 of file MeshSimplification.h.
TargetCount
template<typename QuadricErrorType> int UE::Geometry::TMeshSimplification< QuadricErrorType >::TargetCount = INT_MAX protected
Definition at line 175 of file MeshSimplification.h.
triAreas
template<typename QuadricErrorType> TArray<double> UE::Geometry::TMeshSimplification< QuadricErrorType >::triAreas protected
Definition at line 222 of file MeshSimplification.h.
triQuadrics
template<typename QuadricErrorType> TArray<FQuadricErrorType> UE::Geometry::TMeshSimplification< QuadricErrorType >::triQuadrics protected
Definition at line 223 of file MeshSimplification.h.
vertQuadrics
template<typename QuadricErrorType> TArray<FQuadricErrorType> UE::Geometry::TMeshSimplification< QuadricErrorType >::vertQuadrics protected
Definition at line 216 of file MeshSimplification.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/MeshSimplification.h