Unreal Engine 5.6 C++ API: HarmonixMetasound::FMidiAsset Class Reference
HarmonixMetasound::FMidiAsset Class Reference
#include "MidiAsset.h"
Public Member Functions
FMidiAsset ()=default
FMidiAsset (const FMidiAsset &)=default
HARMONIXMETASOUND_API FMidiAsset (const TSharedPtr< Audio::IProxyData > &InInitData)
const FMidiFileProxyPtr & GetMidiProxy () const
HARMONIXMETASOUND_API bool IsMidiValid () const
FMidiFileProxy * operator-> ()
const FMidiFileProxy * operator-> () const
FMidiAsset & operator= (const FMidiAsset &Other)=default
Private Attributes
FMidiFileProxyPtr MidiFileProxy
Detailed Description
Definition at line 15 of file MidiAsset.h.
Constructor & Destructor Documentation
FMidiAsset() [1/3]
HarmonixMetasound::FMidiAsset::FMidiAsset () default
Referenced by FMidiAsset(), and operator=().
FMidiAsset() [2/3]
HarmonixMetasound::FMidiAsset::FMidiAsset (const FMidiAsset &) default
References FMidiAsset().
FMidiAsset() [3/3]
HARMONIXMETASOUND_API HarmonixMetasound::FMidiAsset::FMidiAsset (const TSharedPtr< Audio::IProxyData > & InInitData)
References UE_API.
Member Function Documentation
GetMidiProxy()
const FMidiFileProxyPtr & HarmonixMetasound::FMidiAsset::GetMidiProxy () const inline
Definition at line 29 of file MidiAsset.h.
References MidiFileProxy.
IsMidiValid()
HARMONIXMETASOUND_API bool HarmonixMetasound::FMidiAsset::IsMidiValid () const
References UE_API.
operator->() [1/2]
FMidiFileProxy * HarmonixMetasound::FMidiAsset::operator-> () inline
Definition at line 39 of file MidiAsset.h.
References MidiFileProxy.
operator->() [2/2]
const FMidiFileProxy * HarmonixMetasound::FMidiAsset::operator-> () const inline
Definition at line 34 of file MidiAsset.h.
References MidiFileProxy.
operator=()
FMidiAsset & HarmonixMetasound::FMidiAsset::operator= (const FMidiAsset & Other) default
References FMidiAsset(), and Other.
Field Documentation
MidiFileProxy
FMidiFileProxyPtr HarmonixMetasound::FMidiAsset::MidiFileProxy private
Definition at line 17 of file MidiAsset.h.
Referenced by GetMidiProxy(), operator->(), and operator->().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixMetasound/Public/HarmonixMetasound/DataTypes/MidiAsset.h