Unreal Engine 5.6 C++ API: FScopedForceUnicodeInArchive Class Reference
FScopedForceUnicodeInArchive Class Reference
#include "ReplayTypes.h"
Public Member Functions
FScopedForceUnicodeInArchive ()=delete
FScopedForceUnicodeInArchive (const FScopedForceUnicodeInArchive &)=delete
FScopedForceUnicodeInArchive (FArchive &InArchive)
FScopedForceUnicodeInArchive (FScopedForceUnicodeInArchive &&)=delete
~FScopedForceUnicodeInArchive ()
FScopedForceUnicodeInArchive & operator= (const FScopedForceUnicodeInArchive &)=delete
FScopedForceUnicodeInArchive & operator= (FScopedForceUnicodeInArchive &&)=delete
Private Member Functions
void EnableFastStringSerialization ()
void RestoreStringSerialization ()
Private Attributes
FArchive & Archive
bool bWasUnicode
Detailed Description
Definition at line 404 of file ReplayTypes.h.
Constructor & Destructor Documentation
FScopedForceUnicodeInArchive() [1/4]
FScopedForceUnicodeInArchive::FScopedForceUnicodeInArchive () delete
Referenced by FScopedForceUnicodeInArchive(), FScopedForceUnicodeInArchive(), operator=(), and operator=().
FScopedForceUnicodeInArchive() [2/4]
FScopedForceUnicodeInArchive::FScopedForceUnicodeInArchive (FScopedForceUnicodeInArchive &&) delete
References FScopedForceUnicodeInArchive().
FScopedForceUnicodeInArchive() [3/4]
FScopedForceUnicodeInArchive::FScopedForceUnicodeInArchive (const FScopedForceUnicodeInArchive &) delete
References FScopedForceUnicodeInArchive().
FScopedForceUnicodeInArchive() [4/4]
FScopedForceUnicodeInArchive::FScopedForceUnicodeInArchive (FArchive & InArchive) inline
Definition at line 413 of file ReplayTypes.h.
References Archive, bWasUnicode, and EnableFastStringSerialization().
~FScopedForceUnicodeInArchive()
FScopedForceUnicodeInArchive::~FScopedForceUnicodeInArchive () inline
Definition at line 420 of file ReplayTypes.h.
References RestoreStringSerialization().
Member Function Documentation
EnableFastStringSerialization()
void FScopedForceUnicodeInArchive::EnableFastStringSerialization () inline private
Definition at line 426 of file ReplayTypes.h.
References Archive, and TIsCharEncodingCompatibleWith< SrcEncoding, DestEncoding >::Value.
Referenced by FScopedForceUnicodeInArchive().
operator=() [1/2]
FScopedForceUnicodeInArchive & FScopedForceUnicodeInArchive::operator= (const FScopedForceUnicodeInArchive &) delete
References FScopedForceUnicodeInArchive().
operator=() [2/2]
FScopedForceUnicodeInArchive & FScopedForceUnicodeInArchive::operator= (FScopedForceUnicodeInArchive &&) delete
References FScopedForceUnicodeInArchive().
RestoreStringSerialization()
void FScopedForceUnicodeInArchive::RestoreStringSerialization () inline private
Definition at line 434 of file ReplayTypes.h.
References Archive, bWasUnicode, and TIsCharEncodingCompatibleWith< SrcEncoding, DestEncoding >::Value.
Referenced by ~FScopedForceUnicodeInArchive().
Field Documentation
Archive
FArchive& FScopedForceUnicodeInArchive::Archive private
Definition at line 442 of file ReplayTypes.h.
Referenced by FScopedForceUnicodeInArchive(), EnableFastStringSerialization(), and RestoreStringSerialization().
bWasUnicode
bool FScopedForceUnicodeInArchive::bWasUnicode private
Definition at line 443 of file ReplayTypes.h.
Referenced by FScopedForceUnicodeInArchive(), and RestoreStringSerialization().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ReplayTypes.h