Unreal Engine 5.6 C++ API: FFixToken Class Reference
FFixToken Class Reference
A fix action token.
#include "TokenizedMessage.h"
Data Structures
struct FPrivateToken
Public Member Functions
FFixToken (FPrivateToken, const FText &InName, TSharedPtr< UE::DataValidation::IFixer > Fixer, int32 FixIndex)
TSharedRef< UE::DataValidation::IFixer > GetFixer () const
int32 GetFixIndex () const
virtual EMessageToken::Type GetType () const override
Get the type of this message token.
void SetFix (TSharedRef< UE::DataValidation::IFixer > InFixer, int32 InFixIndex)
Public Member Functions inherited from IMessageToken
virtual ~IMessageToken ()
Virtual destructor.
virtual const FOnMessageTokenActivated & GetOnMessageTokenActivated () const
Get the activated delegate associated with this token, if any.
virtual TSharedRef< IMessageToken > OnMessageTokenActivated (FOnMessageTokenActivated InMessageTokenActivated)
Set the activated delegate associated with this token.
virtual const FText & ToText () const
Get a string representation of this token.
Public Member Functions inherited from TSharedFromThis< IMessageToken >
TSharedRef< IMessageToken, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IMessageToken, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FFixToken > Create (const FText &InName, TSharedRef< UE::DataValidation::IFixer > InFixer, int32 InFixIndex)
Creates an FFixToken out of an IFixer and a fix index.
Private Member Functions
FFixToken (const FText &InName, TSharedPtr< UE::DataValidation::IFixer > InFixer, int32 InFixIndex)
Private Attributes
TSharedPtr< UE::DataValidation::IFixer > Fixer
int32 FixIndex = INDEX_NONE
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IMessageToken >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IMessageToken >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from IMessageToken
FText CachedText
Cached string representation of this token.
FOnMessageTokenActivated MessageTokenActivated
A delegate for when this token is activated (e.g.
Detailed Description
A fix action token.
These are displayed in a separate list below the log message.
Definition at line 795 of file TokenizedMessage.h.
Constructor & Destructor Documentation
FFixToken() [1/2]
FFixToken::FFixToken (FPrivateToken , const FText & InName, TSharedPtr< UE::DataValidation::IFixer > Fixer, int32 FixIndex) inline
Definition at line 817 of file TokenizedMessage.h.
References FFixToken(), Fixer, FixIndex, InName, and MoveTemp().
Referenced by FFixToken().
FFixToken() [2/2]
FFixToken::FFixToken (const FText & InName, TSharedPtr< UE::DataValidation::IFixer > InFixer, int32 InFixIndex) private
References InName.
Member Function Documentation
Create()
TSharedRef< FFixToken > FFixToken::Create (const FText & InName, TSharedRef< UE::DataValidation::IFixer > InFixer, int32 InFixIndex) static
Creates an FFixToken out of an IFixer and a fix index.
Prefer IFixer::CreateToken over this.
References InName.
GetFixer()
TSharedRef< UE::DataValidation::IFixer > FFixToken::GetFixer () const inline
Definition at line 809 of file TokenizedMessage.h.
References Fixer.
GetFixIndex()
int32 FFixToken::GetFixIndex () const inline
Definition at line 810 of file TokenizedMessage.h.
References FixIndex.
GetType()
virtual EMessageToken::Type FFixToken::GetType () const inline override virtual
Get the type of this message token.
Returns
the type of the token
Implements IMessageToken.
Definition at line 804 of file TokenizedMessage.h.
References EMessageToken::Fix.
SetFix()
void FFixToken::SetFix (TSharedRef< UE::DataValidation::IFixer > InFixer, int32 InFixIndex) inline
Definition at line 811 of file TokenizedMessage.h.
References Fixer, and FixIndex.
Field Documentation
Fixer
TSharedPtr<UE::DataValidation::IFixer> FFixToken::Fixer private
Definition at line 824 of file TokenizedMessage.h.
Referenced by FFixToken(), GetFixer(), and SetFix().
FixIndex
int32 FFixToken::FixIndex = INDEX_NONE private
Definition at line 825 of file TokenizedMessage.h.
Referenced by FFixToken(), GetFixIndex(), and SetFix().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Logging/TokenizedMessage.h