Unreal Engine 5.6 C++ API: FSimpleAudioInfoFactory Class Reference
FSimpleAudioInfoFactory Class Reference
#include "AudioDecompress.h"
Public Member Functions
FSimpleAudioInfoFactory (const TFunction< ICompressedAudioInfo *()> &InLambda, const FName &InFormatName, const FCapabilities InCaps={})
Constructs a simple AudioInfo factory.
virtual ~FSimpleAudioInfoFactory () override
virtual ICompressedAudioInfo * Create () override
virtual bool IsSeekingSupported (const bool bIsStreaming) const override
Quries if seeking is supported by the decoder.
Public Member Functions inherited from IAudioInfoFactory
virtual ~IAudioInfoFactory ()=default
Private Attributes
FCapabilities Capabilities
TFunction< ICompressedAudioInfo *()> CreateLambda
FName FormatName
Detailed Description
Definition at line 413 of file AudioDecompress.h.
Constructor & Destructor Documentation
FSimpleAudioInfoFactory()
FSimpleAudioInfoFactory::FSimpleAudioInfoFactory (const TFunction< ICompressedAudioInfo *()> & InLambda, const FName & InFormatName, const FCapabilities InCaps = {}) inline
Constructs a simple AudioInfo factory.
Parameters
InLambda Lambda to Create a ICompressionAudioInfo object
InFormatName The factory name of the Format. "ADPCM" etc.
InCaps The Capabilities of the decoder implementation.
Definition at line 422 of file AudioDecompress.h.
~FSimpleAudioInfoFactory()
virtual FSimpleAudioInfoFactory::~FSimpleAudioInfoFactory () inline override virtual
Definition at line 427 of file AudioDecompress.h.
References FormatName, IAudioInfoFactoryRegistry::Get(), and IAudioInfoFactoryRegistry::Unregister().
Member Function Documentation
Create()
virtual ICompressedAudioInfo * FSimpleAudioInfoFactory::Create () inline override virtual
Implements IAudioInfoFactory.
Definition at line 431 of file AudioDecompress.h.
References CreateLambda.
IsSeekingSupported()
virtual bool FSimpleAudioInfoFactory::IsSeekingSupported (const bool bIsStreaming) const inline override virtual
Quries if seeking is supported by the decoder.
Parameters
bIsStreaming If the media is to be streamed or not.
Returns
True for supported, false otherwise.
Implements IAudioInfoFactory.
Definition at line 438 of file AudioDecompress.h.
References Capabilities.
Field Documentation
Capabilities
FCapabilities FSimpleAudioInfoFactory::Capabilities private
Definition at line 448 of file AudioDecompress.h.
Referenced by IsSeekingSupported().
CreateLambda
TFunction<ICompressedAudioInfo* ()> FSimpleAudioInfoFactory::CreateLambda private
Definition at line 446 of file AudioDecompress.h.
Referenced by Create().
FormatName
FName FSimpleAudioInfoFactory::FormatName private
Definition at line 447 of file AudioDecompress.h.
Referenced by ~FSimpleAudioInfoFactory().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AudioDecompress.h