Unreal Engine 5.6 C++ API: UE::Cook::IDeterminismHelper Class Reference
UE::Cook::IDeterminismHelper Class Reference
Interface implemented by UObjects that want to store diagnostic data for comparison when a package is found to contain indeterminism by a -diffonly cook or is found to have a FalsePositiveIncrementalSkip by a -incrementalvalidate cook.
#include "CookDeterminismHelper.h"
Public Member Functions
virtual void ConstructDiagnostics (IDeterminismConstructDiagnosticsContext &Context)
Override this function to add diagnostics to the package containing data about the UObject that registered the DeterminismHelper.
virtual void OnPackageModified (IDeterminismModifiedExportContext &ExportContext)
Override this function to get a callback with the old and new values of the diagnostics when a package is found to be modified by indeterminism or FalsePositiveIncrementalSkip.
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Detailed Description
Interface implemented by UObjects that want to store diagnostic data for comparison when a package is found to contain indeterminism by a -diffonly cook or is found to have a FalsePositiveIncrementalSkip by a -incrementalvalidate cook.
DeterminismHelper objects are registered via FObjectPreSaveContext.RegisterDeterminismHelper in the PreSave of a UObject.
Definition at line 122 of file CookDeterminismHelper.h.
Member Function Documentation
ConstructDiagnostics()
virtual void UE::Cook::IDeterminismHelper::ConstructDiagnostics (IDeterminismConstructDiagnosticsContext & Context) inline virtual
Override this function to add diagnostics to the package containing data about the UObject that registered the DeterminismHelper.
Definition at line 129 of file CookDeterminismHelper.h.
OnPackageModified()
virtual void UE::Cook::IDeterminismHelper::OnPackageModified (IDeterminismModifiedExportContext & ExportContext) inline virtual
Override this function to get a callback with the old and new values of the diagnostics when a package is found to be modified by indeterminism or FalsePositiveIncrementalSkip.
The default implementation just prints out the old and new values of each diagnostic.
Definition at line 138 of file CookDeterminismHelper.h.
References UE::Cook::IDeterminismModifiedExportContext::AppendDiagnostics(), UE::Cook::IDeterminismModifiedExportContext::IsModified(), and UE::Cook::IDeterminismModifiedExportContext::IsPrimaryAsset().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Cooker/CookDeterminismHelper.h