Unreal Engine 5.6 C++ API: FMeshElementIndexer Class Reference
FMeshElementIndexer Class Reference
This is an efficient container for holding back references to mesh elements from attributes.
#include "MeshElementIndexer.h"
Data Structures
struct FChunk
We are modelling a one-to-many relationship, where a single key yields multiple indices, e.g.
struct FIndexPerChannel
Public Member Functions
FMeshElementIndexer ()=default
MESHDESCRIPTION_API FMeshElementIndexer (const FMeshElementChannels *Key, const FMeshElementChannels *Referencer, FName AttributeName, int32 ReferencerChannelIndex=0)
FMeshElementIndexer (const FMeshElementIndexer &)=delete
FMeshElementIndexer (FMeshElementIndexer &&)=default
MESHDESCRIPTION_API void AddReferenceToKey (int32 KeyIndex, int32 ReferenceIndex, int32 KeyChannelIndex=0)
Add a reference to a key.
MESHDESCRIPTION_API void Build ()
Build any stale indices.
TArrayView< const int32 > Find (int32 KeyIndex, int32 KeyChannelIndex=0)
Retrieve all referencer indices whose named attribute refers to KeyIndex.
template<typename ElementIDType>
TArrayView< const ElementIDType > Find (int32 KeyIndex, int32 KeyChannelIndex=0)
MESHDESCRIPTION_API void ForceRebuild ()
Force the indexer to be completely rebuilt.
FMeshElementIndexer & operator= (const FMeshElementIndexer &)=delete
FMeshElementIndexer & operator= (FMeshElementIndexer &&)=default
MESHDESCRIPTION_API void RemoveKey (int32 KeyIndex, int32 KeyChannelIndex=0)
Remove the specified key from the indexer.
MESHDESCRIPTION_API void RemoveReferenceFromKey (int32 KeyIndex, int32 ReferenceIndex, int32 KeyChannelIndex=0)
Remove reference from key.
MESHDESCRIPTION_API void Reset ()
Resets the indexer.
void Resume ()
Resume indexing and mark indexer as stale, but do not force an immediate rebuild.
MESHDESCRIPTION_API void Set (const FMeshElementChannels *Key, const FMeshElementChannels *Referencer, FName AttributeName, int32 ReferencerChannelIndex=0)
Set the parameters of this mesh element indexer.
void SetChunkSize (int InChunkSize)
Sets the chunk size for the indexer, for optimization purposes.
void SetInitialNumReferences (int InInitialSize)
Sets the initial/expected number of references per key.
void SetUnchunked ()
Configures the indexer not to use chunks.
void Suspend ()
Suspend indexing until the next rebuild.
Private Member Functions
MESHDESCRIPTION_API void AddUnchunked (int32 KeyIndex, int32 ReferenceIndex, int32 KeyChannelIndex=0)
MESHDESCRIPTION_API void BuildIndex (int32 Index)
MESHDESCRIPTION_API void ConditionalBuild (int32 KeyIndex, int32 KeyChannelIndex)
int32 GetChunkElementForKey (int32 ElementIndex) const
int32 GetChunkForKey (int32 ElementIndex) const
int32 GetChunkSize () const
int32 GetNumChunksForKeys (int32 NumElements) const
MESHDESCRIPTION_API void RebuildIndex (int32 Index)
MESHDESCRIPTION_API void UpdatePerChannelIndices ()
Private Attributes
bool bEverythingStale = true
True if the entire data needs to be rebuilt.
bool bSuspended = false
Whether indexing is temporarily suspended.
uint32 ChunkBits = 8
Chunk size.
uint32 ChunkMask = (1U << ChunkBits) - 1
int32 InitialSize = 1
The initial size for key chunks.
TArray< FIndexPerChannel > PerChannelIndices
const FMeshElementChannels * ReferencedElementType
The element type used as the key for this index.
TMeshAttributesRef< int, TArrayView< const int32 > > ReferencingAttributeRef
The attribute ref used to reference the above key.
Detailed Description
This is an efficient container for holding back references to mesh elements from attributes.
Typically this will be a one-to-many relationship, where a given key has many different references.
Naively this would be implemented as an array of arrays, but we want to minimise allocations and fragmentation as much as possible. This is achieved in two ways:
1) Arrays representing the list of references are consolidated into chunks of a user-specified size. This reduces the number of individual allocations which need to be made. By default, 256 keys are consolidated into a single chunk.
2) The arrays are lazily updated. The most expensive aspect of consolidating adjacent keys' values into a single chunk of data is having to insert new space into the middle of the chunk. If a new value can't be immediately added into a chunk without inserting, the key is marked as stale and the referencer is remembered. If a stale key is queried, the indexer will be updated first, building all stale keys by getting back references from the remembered referencers.
There is also a way to fully rebuild an indexer, which will perform optimally few allocations, and collect all back references at once. It may sometimes be desirable to suspend an indexer, build a mesh description with indexing suspended, and then perform an indexer rebuild for additional speed and allocation efficiency.
Some element relationships don't lend themselves to chunking, for example polygon groups to triangles. In this case, there are generally few polygon groups compared to many triangles. Chunking can be turned off for such indexers, resulting in a more simple array representation which can be arbitrarily grown without requiring elements to be inserted.
Definition at line 47 of file MeshElementIndexer.h.
Constructor & Destructor Documentation
FMeshElementIndexer() [1/4]
FMeshElementIndexer::FMeshElementIndexer () default
Referenced by FMeshElementIndexer(), FMeshElementIndexer(), operator=(), and operator=().
FMeshElementIndexer() [2/4]
MESHDESCRIPTION_API FMeshElementIndexer::FMeshElementIndexer (const FMeshElementChannels * Key, const FMeshElementChannels * Referencer, FName AttributeName, int32 ReferencerChannelIndex = 0)
References Key.
FMeshElementIndexer() [3/4]
FMeshElementIndexer::FMeshElementIndexer (const FMeshElementIndexer &) delete
References FMeshElementIndexer().
FMeshElementIndexer() [4/4]
FMeshElementIndexer::FMeshElementIndexer (FMeshElementIndexer &&) default
References FMeshElementIndexer().
Member Function Documentation
AddReferenceToKey()
MESHDESCRIPTION_API void FMeshElementIndexer::AddReferenceToKey (int32 KeyIndex, int32 ReferenceIndex, int32 KeyChannelIndex = 0)
Add a reference to a key.
This will be queued and take effect in batch when an affected key is looked up. This is preferable to regenerating the index entirely.
AddUnchunked()
MESHDESCRIPTION_API void FMeshElementIndexer::AddUnchunked (int32 KeyIndex, int32 ReferenceIndex, int32 KeyChannelIndex = 0) private
Build()
MESHDESCRIPTION_API void FMeshElementIndexer::Build ()
Build any stale indices.
BuildIndex()
MESHDESCRIPTION_API void FMeshElementIndexer::BuildIndex (int32 Index) private
ConditionalBuild()
MESHDESCRIPTION_API void FMeshElementIndexer::ConditionalBuild (int32 KeyIndex, int32 KeyChannelIndex) private
Referenced by Find().
Find() [1/2]
TArrayView< const int32 > FMeshElementIndexer::Find (int32 KeyIndex, int32 KeyChannelIndex = 0) inline
Retrieve all referencer indices whose named attribute refers to KeyIndex.
Non-const because finding a stale index might cause a rebuild.
Definition at line 101 of file MeshElementIndexer.h.
References bSuspended, check, ConditionalBuild(), GetChunkElementForKey(), GetChunkForKey(), and PerChannelIndices.
Find() [2/2]
template<typename ElementIDType> TArrayView< const ElementIDType > FMeshElementIndexer::Find (int32 KeyIndex, int32 KeyChannelIndex = 0) inline
Definition at line 118 of file MeshElementIndexer.h.
References bSuspended, check, ConditionalBuild(), GetChunkElementForKey(), GetChunkForKey(), INDEX_NONE, and PerChannelIndices.
ForceRebuild()
MESHDESCRIPTION_API void FMeshElementIndexer::ForceRebuild ()
Force the indexer to be completely rebuilt.
GetChunkElementForKey()
int32 FMeshElementIndexer::GetChunkElementForKey (int32 ElementIndex) const inline private
Definition at line 201 of file MeshElementIndexer.h.
References checkSlow, ChunkMask, and INDEX_NONE.
Referenced by Find().
GetChunkForKey()
int32 FMeshElementIndexer::GetChunkForKey (int32 ElementIndex) const inline private
Definition at line 194 of file MeshElementIndexer.h.
References checkSlow, ChunkBits, and INDEX_NONE.
Referenced by Find().
GetChunkSize()
int32 FMeshElementIndexer::GetChunkSize () const inline private
Definition at line 208 of file MeshElementIndexer.h.
References ChunkBits.
GetNumChunksForKeys()
int32 FMeshElementIndexer::GetNumChunksForKeys (int32 NumElements) const inline private
Definition at line 211 of file MeshElementIndexer.h.
References ChunkBits, and ChunkMask.
operator=() [1/2]
FMeshElementIndexer & FMeshElementIndexer::operator= (const FMeshElementIndexer &) delete
References FMeshElementIndexer().
operator=() [2/2]
FMeshElementIndexer & FMeshElementIndexer::operator= (FMeshElementIndexer &&) default
References FMeshElementIndexer().
RebuildIndex()
MESHDESCRIPTION_API void FMeshElementIndexer::RebuildIndex (int32 Index) private
RemoveKey()
MESHDESCRIPTION_API void FMeshElementIndexer::RemoveKey (int32 KeyIndex, int32 KeyChannelIndex = 0)
Remove the specified key from the indexer.
RemoveReferenceFromKey()
MESHDESCRIPTION_API void FMeshElementIndexer::RemoveReferenceFromKey (int32 KeyIndex, int32 ReferenceIndex, int32 KeyChannelIndex = 0)
Remove reference from key.
This will take immediate effect.
Reset()
MESHDESCRIPTION_API void FMeshElementIndexer::Reset ()
Resets the indexer.
Resume()
void FMeshElementIndexer::Resume () inline
Resume indexing and mark indexer as stale, but do not force an immediate rebuild.
Definition at line 161 of file MeshElementIndexer.h.
References bEverythingStale, and bSuspended.
Set()
MESHDESCRIPTION_API void FMeshElementIndexer::Set (const FMeshElementChannels * Key, const FMeshElementChannels * Referencer, FName AttributeName, int32 ReferencerChannelIndex = 0)
Set the parameters of this mesh element indexer.
References Key.
SetChunkSize()
void FMeshElementIndexer::SetChunkSize (int InChunkSize) inline
Sets the chunk size for the indexer, for optimization purposes.
The default chunk size is 256.
Definition at line 75 of file MeshElementIndexer.h.
References ChunkBits, and ChunkMask.
Referenced by SetUnchunked().
SetInitialNumReferences()
void FMeshElementIndexer::SetInitialNumReferences (int InInitialSize) inline
Sets the initial/expected number of references per key.
Definition at line 69 of file MeshElementIndexer.h.
References InitialSize.
SetUnchunked()
void FMeshElementIndexer::SetUnchunked () inline
Configures the indexer not to use chunks.
This is desirable if there are very few keys with a lot of references, e.g. polygon groups to polygons
Definition at line 85 of file MeshElementIndexer.h.
References check, ChunkBits, ChunkMask, and SetChunkSize().
Suspend()
void FMeshElementIndexer::Suspend () inline
Suspend indexing until the next rebuild.
Definition at line 156 of file MeshElementIndexer.h.
References bSuspended.
UpdatePerChannelIndices()
MESHDESCRIPTION_API void FMeshElementIndexer::UpdatePerChannelIndices () private
Field Documentation
bEverythingStale
bool FMeshElementIndexer::bEverythingStale = true private
True if the entire data needs to be rebuilt.
Definition at line 323 of file MeshElementIndexer.h.
Referenced by Resume().
bSuspended
bool FMeshElementIndexer::bSuspended = false private
Whether indexing is temporarily suspended.
Definition at line 320 of file MeshElementIndexer.h.
Referenced by Find(), Resume(), and Suspend().
ChunkBits
uint32 FMeshElementIndexer::ChunkBits = 8 private
Chunk size.
Definition at line 316 of file MeshElementIndexer.h.
Referenced by GetChunkForKey(), GetChunkSize(), GetNumChunksForKeys(), SetChunkSize(), and SetUnchunked().
ChunkMask
uint32 FMeshElementIndexer::ChunkMask = (1U << ChunkBits) - 1 private
Definition at line 317 of file MeshElementIndexer.h.
Referenced by GetChunkElementForKey(), GetNumChunksForKeys(), SetChunkSize(), and SetUnchunked().
InitialSize
int32 FMeshElementIndexer::InitialSize = 1 private
The initial size for key chunks.
Definition at line 313 of file MeshElementIndexer.h.
Referenced by FMeshElementIndexer::FChunk::FChunk(), and SetInitialNumReferences().
PerChannelIndices
TArray<FIndexPerChannel> FMeshElementIndexer::PerChannelIndices private
Definition at line 304 of file MeshElementIndexer.h.
Referenced by Find().
ReferencedElementType
const FMeshElementChannels* FMeshElementIndexer::ReferencedElementType private
The element type used as the key for this index.
Definition at line 307 of file MeshElementIndexer.h.
ReferencingAttributeRef
TMeshAttributesRef<int, TArrayView<const int32> > FMeshElementIndexer::ReferencingAttributeRef private
The attribute ref used to reference the above key.
Definition at line 310 of file MeshElementIndexer.h.
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/MeshElementIndexer.h