Unreal Engine 5.6 C++ API: FFixedUObjectArray Class Reference
FFixedUObjectArray Class Reference
Fixed size UObject array.
#include "UObjectArray.h"
Public Member Functions
FFixedUObjectArray ()
~FFixedUObjectArray ()
int32 AddRange (int32 Count)
int32 AddSingle ()
FORCEINLINE int32 Capacity () const
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
FORCEINLINE FUObjectItem * GetObjectPtr (int32 Index)
FORCEINLINE FUObjectItem const * GetObjectPtr (int32 Index) const
UObjectBase *** GetRootBlockForDebuggerVisualizers ()
Return a naked pointer to the fundamental data structure for debug visualizers.
FORCEINLINE bool IsValidIndex (int32 Index) const
Return if this index is valid Thread safe, if it is valid now, it is valid forever.
FORCEINLINE int32 Num () const
Return the number of elements in the array Thread safe, but you know, someone might have added more elements before this even returns.
FORCEINLINE FUObjectItem & operator[] (int32 Index)
FORCEINLINE FUObjectItem const & operator[] (int32 Index) const
Return a reference to an element.
void PreAllocate (int32 InMaxElements)
Expands the array so that Element[Index] is allocated.
Private Member Functions
TSAN_ATOMIC (FUObjectItem *) Objects
Static primary table to chunks of pointers.
TSAN_ATOMIC (int32) MaxElements
Number of elements we currently have.
TSAN_ATOMIC (int32) NumElements
Current number of UObject slots.
Detailed Description
Fixed size UObject array.
Definition at line 527 of file UObjectArray.h.
Constructor & Destructor Documentation
FFixedUObjectArray()
FFixedUObjectArray::FFixedUObjectArray () inline
Definition at line 538 of file UObjectArray.h.
~FFixedUObjectArray()
FFixedUObjectArray::~FFixedUObjectArray () inline
Definition at line 545 of file UObjectArray.h.
Member Function Documentation
AddRange()
int32 FFixedUObjectArray::AddRange (int32 Count) inline
Definition at line 572 of file UObjectArray.h.
References check, UE::UObjectArrayPrivate::CheckUObjectLimitReached(), Count, and FAndroidMisc::MemoryBarrier().
AddSingle()
int32 FFixedUObjectArray::AddSingle () inline
Definition at line 561 of file UObjectArray.h.
References check, UE::UObjectArrayPrivate::CheckUObjectLimitReached(), and FAndroidMisc::MemoryBarrier().
Capacity()
FORCEINLINE int32 FFixedUObjectArray::Capacity () const inline
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the maximum number of elements in the array
Definition at line 610 of file UObjectArray.h.
References FORCEINLINE.
GetObjectPtr() [1/2]
FORCEINLINE FUObjectItem * FFixedUObjectArray::GetObjectPtr (int32 Index) inline
Definition at line 589 of file UObjectArray.h.
References check, and FORCEINLINE.
GetObjectPtr() [2/2]
FORCEINLINE FUObjectItem const * FFixedUObjectArray::GetObjectPtr (int32 Index) const inline
Definition at line 583 of file UObjectArray.h.
References check, and FORCEINLINE.
Referenced by operator[](), and operator[]().
GetRootBlockForDebuggerVisualizers()
UObjectBase *** FFixedUObjectArray::GetRootBlockForDebuggerVisualizers () inline
Return a naked pointer to the fundamental data structure for debug visualizers.
Definition at line 648 of file UObjectArray.h.
IsValidIndex()
FORCEINLINE bool FFixedUObjectArray::IsValidIndex (int32 Index) const inline
Return if this index is valid Thread safe, if it is valid now, it is valid forever.
Other threads might be adding during this call.
Parameters
Index Index to test
Returns
true, if this is a valid
Definition at line 621 of file UObjectArray.h.
References FORCEINLINE, and Num.
Num()
FORCEINLINE int32 FFixedUObjectArray::Num () const inline
Return the number of elements in the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the number of elements in the array
Definition at line 600 of file UObjectArray.h.
References FORCEINLINE.
operator[]() [1/2]
FORCEINLINE FUObjectItem & FFixedUObjectArray::operator[] (int32 Index) inline
Definition at line 638 of file UObjectArray.h.
References check, FORCEINLINE, and GetObjectPtr().
operator[]() [2/2]
FORCEINLINE FUObjectItem const & FFixedUObjectArray::operator[] (int32 Index) const inline
Return a reference to an element.
Parameters
Index Index to return
Returns
a reference to the pointer to the element Thread safe, if it is valid now, it is valid forever. This might return nullptr, but by then, some other thread might have made it non-nullptr.
Definition at line 631 of file UObjectArray.h.
References check, FORCEINLINE, and GetObjectPtr().
PreAllocate()
void FFixedUObjectArray::PreAllocate (int32 InMaxElements) inline
Expands the array so that Element[Index] is allocated.
New pointers are all zero.
Parameters
Index The Index of an element we want to be sure is allocated
Definition at line 554 of file UObjectArray.h.
References check.
TSAN_ATOMIC() [1/3]
FFixedUObjectArray::TSAN_ATOMIC (FUObjectItem *) private
Static primary table to chunks of pointers.
TSAN_ATOMIC() [2/3]
FFixedUObjectArray::TSAN_ATOMIC (int32) private
Number of elements we currently have.
TSAN_ATOMIC() [3/3]
FFixedUObjectArray::TSAN_ATOMIC (int32) private
Current number of UObject slots.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectArray.h