Unreal Engine 5.6 C++ API: FSkinWeightsVertexAttributesRef Class Reference
FSkinWeightsVertexAttributesRef Class Reference
#include "SkinWeightsAttributesRef.h"
Public Member Functions
FSkinWeightsVertexAttributesRef ()=default
FSkinWeightsVertexAttributesRef (const FSkinWeightsVertexAttributesRef &)=default
FSkinWeightsVertexAttributesRef (FSkinWeightsVertexAttributesRef &&) noexcept=default
FVertexBoneWeights Get (const FVertexID InVertexIndex) const
bool IsValid () const
FSkinWeightsVertexAttributesRef & operator= (const FSkinWeightsVertexAttributesRef &InAttributesRef)
FSkinWeightsVertexAttributesRef & operator= (FSkinWeightsVertexAttributesRef &&InAttributesRef) noexcept
void Set (const FVertexID InVertexIndex, const UE::AnimationCore::FBoneWeights &InWeights)
void Set (const FVertexID InVertexIndex, TArrayView< const UE::AnimationCore::FBoneWeight > InWeights, const UE::AnimationCore::FBoneWeightsSettings &InSettings={})
Protected Member Functions
FSkinWeightsVertexAttributesRef (TVertexAttributesRef< TArrayAttribute< int32 > > InAttributesRef)
Private Attributes
TVertexAttributesRef< TArrayAttribute< int32 > > AttributesRef
Friends
class FSkeletalMeshAttributes
class FSkinWeightsVertexAttributesConstRef
Detailed Description
Definition at line 158 of file SkinWeightsAttributesRef.h.
Constructor & Destructor Documentation
FSkinWeightsVertexAttributesRef() [1/4]
FSkinWeightsVertexAttributesRef::FSkinWeightsVertexAttributesRef () default
Referenced by FSkinWeightsVertexAttributesRef(), FSkinWeightsVertexAttributesRef(), operator=(), and operator=().
FSkinWeightsVertexAttributesRef() [2/4]
FSkinWeightsVertexAttributesRef::FSkinWeightsVertexAttributesRef (const FSkinWeightsVertexAttributesRef &) default
References FSkinWeightsVertexAttributesRef().
FSkinWeightsVertexAttributesRef() [3/4]
FSkinWeightsVertexAttributesRef::FSkinWeightsVertexAttributesRef (FSkinWeightsVertexAttributesRef &&) default noexcept
References FSkinWeightsVertexAttributesRef().
FSkinWeightsVertexAttributesRef() [4/4]
FSkinWeightsVertexAttributesRef::FSkinWeightsVertexAttributesRef (TVertexAttributesRef< TArrayAttribute< int32 > > InAttributesRef) inline protected
Definition at line 214 of file SkinWeightsAttributesRef.h.
References AttributesRef.
Member Function Documentation
Get()
FVertexBoneWeights FSkinWeightsVertexAttributesRef::Get (const FVertexID InVertexIndex) const inline
Definition at line 182 of file SkinWeightsAttributesRef.h.
References AttributesRef.
IsValid()
bool FSkinWeightsVertexAttributesRef::IsValid () const inline
Definition at line 177 of file SkinWeightsAttributesRef.h.
References AttributesRef.
operator=() [1/2]
FSkinWeightsVertexAttributesRef & FSkinWeightsVertexAttributesRef::operator= (const FSkinWeightsVertexAttributesRef & InAttributesRef) inline
Definition at line 164 of file SkinWeightsAttributesRef.h.
References FSkinWeightsVertexAttributesRef(), and AttributesRef.
operator=() [2/2]
FSkinWeightsVertexAttributesRef & FSkinWeightsVertexAttributesRef::operator= (FSkinWeightsVertexAttributesRef && InAttributesRef) inline noexcept
Definition at line 170 of file SkinWeightsAttributesRef.h.
References FSkinWeightsVertexAttributesRef(), AttributesRef, and MoveTemp().
Set() [1/2]
void FSkinWeightsVertexAttributesRef::Set (const FVertexID InVertexIndex, const UE::AnimationCore::FBoneWeights & InWeights) inline
Definition at line 187 of file SkinWeightsAttributesRef.h.
References AttributesRef.
Set() [2/2]
void FSkinWeightsVertexAttributesRef::Set (const FVertexID InVertexIndex, TArrayView< const UE::AnimationCore::FBoneWeight > InWeights, const UE::AnimationCore::FBoneWeightsSettings & InSettings = {}) inline
Definition at line 199 of file SkinWeightsAttributesRef.h.
Friends And Related Symbol Documentation
FSkeletalMeshAttributes
friend class FSkeletalMeshAttributes friend
Definition at line 212 of file SkinWeightsAttributesRef.h.
References FSkeletalMeshAttributes.
Referenced by FSkeletalMeshAttributes.
FSkinWeightsVertexAttributesConstRef
friend class FSkinWeightsVertexAttributesConstRef friend
Definition at line 219 of file SkinWeightsAttributesRef.h.
References FSkinWeightsVertexAttributesConstRef.
Referenced by FSkinWeightsVertexAttributesConstRef.
Field Documentation
AttributesRef
TVertexAttributesRef<TArrayAttribute<int32> > FSkinWeightsVertexAttributesRef::AttributesRef private
Definition at line 220 of file SkinWeightsAttributesRef.h.
Referenced by FSkinWeightsVertexAttributesRef(), Get(), IsValid(), FSkinWeightsVertexAttributesConstRef::operator=(), operator=(), operator=(), and Set().
The documentation for this class was generated from the following file:
Runtime/SkeletalMeshDescription/Public/SkinWeightsAttributesRef.h