Unreal Engine 5.6 C++ API: FStaticMeshAsyncBuildWorker Class Reference
FStaticMeshAsyncBuildWorker Class Reference
Worker used to perform async static mesh compilation.
#include "StaticMesh.h"
Public Member Functions
FStaticMeshAsyncBuildWorker (UStaticMesh *InStaticMesh, TUniquePtr< FStaticMeshBuildContext > &&InBuildContext)
Initialization constructor.
FStaticMeshAsyncBuildWorker (UStaticMesh *InStaticMesh, TUniquePtr< FStaticMeshPostLoadContext > &&InPostLoadContext)
Initialization constructor.
void DoWork ()
FORCEINLINE TStatId GetStatId () const
void MarkAsCanceled ()
Public Member Functions inherited from FNonAbandonableTask
void Abandon ()
bool CanAbandon ()
Data Fields
TUniquePtr< FStaticMeshBuildContext > BuildContext
TUniquePtr< FStaticMeshPostLoadContext > PostLoadContext
UStaticMesh * StaticMesh
Detailed Description
Worker used to perform async static mesh compilation.
Definition at line 164 of file StaticMesh.h.
Constructor & Destructor Documentation
FStaticMeshAsyncBuildWorker() [1/2]
FStaticMeshAsyncBuildWorker::FStaticMeshAsyncBuildWorker (UStaticMesh * InStaticMesh, TUniquePtr< FStaticMeshBuildContext > && InBuildContext) inline
Initialization constructor.
Definition at line 172 of file StaticMesh.h.
References BuildContext, MoveTemp(), PostLoadContext, and StaticMesh.
Referenced by GetStatId().
FStaticMeshAsyncBuildWorker() [2/2]
FStaticMeshAsyncBuildWorker::FStaticMeshAsyncBuildWorker (UStaticMesh * InStaticMesh, TUniquePtr< FStaticMeshPostLoadContext > && InPostLoadContext) inline
Initialization constructor.
Definition at line 182 of file StaticMesh.h.
References BuildContext, MoveTemp(), PostLoadContext, and StaticMesh.
Member Function Documentation
DoWork()
void FStaticMeshAsyncBuildWorker::DoWork ()
GetStatId()
FORCEINLINE TStatId FStaticMeshAsyncBuildWorker::GetStatId () const inline
Definition at line 193 of file StaticMesh.h.
References FStaticMeshAsyncBuildWorker(), FORCEINLINE, and RETURN_QUICK_DECLARE_CYCLE_STAT.
MarkAsCanceled()
void FStaticMeshAsyncBuildWorker::MarkAsCanceled ()
Field Documentation
BuildContext
TUniquePtr<FStaticMeshBuildContext> FStaticMeshAsyncBuildWorker::BuildContext
Definition at line 169 of file StaticMesh.h.
Referenced by FStaticMeshAsyncBuildWorker(), and FStaticMeshAsyncBuildWorker().
PostLoadContext
TUniquePtr<FStaticMeshPostLoadContext> FStaticMeshAsyncBuildWorker::PostLoadContext
Definition at line 168 of file StaticMesh.h.
Referenced by FStaticMeshAsyncBuildWorker(), and FStaticMeshAsyncBuildWorker().
StaticMesh
UStaticMesh* FStaticMeshAsyncBuildWorker::StaticMesh
Definition at line 167 of file StaticMesh.h.
Referenced by FStaticMeshAsyncBuildWorker(), and FStaticMeshAsyncBuildWorker().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/StaticMesh.h