Unreal Engine 5.6 C++ API: TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy > Class Template Reference
TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy > Class Template Reference
#include "ConcurrentLinearAllocator.h"
Data Structures
class FAllocationHeader
struct FBlockHeader
struct FTLSCleanup
Static Public Member Functions
static FORCEINLINE_DEBUGGABLE void Free (void *Pointer)
static FORCEINLINE_DEBUGGABLE SIZE_T GetAllocationSize (void *Pointer)
template<typename T>
static FORCEINLINE_DEBUGGABLE void * Malloc ()
template<uint32 Alignment>
static FORCEINLINE_DEBUGGABLE void * Malloc (SIZE_T Size)
static FORCEINLINE_DEBUGGABLE void * Malloc (SIZE_T Size, uint32 Alignment)
static FORCEINLINE_DEBUGGABLE void * Realloc (void *Old, SIZE_T Size, uint32 Alignment)
Private Member Functions
LLM (static constexpr ELLMAllocType LLMAllocationType=BlockAllocationTag::Allocator::UsesFMalloc ? ELLMAllocType::FMalloc :ELLMAllocType::None;) struct FBlockHeader
Static Private Member Functions
static FORCENOINLINE void AllocateBlock (FBlockHeader *&Header)
static FORCEINLINE FAllocationHeader * GetAllocationHeader (void *Pointer)
Static Private Attributes
static constexpr bool SupportsFastPath
Detailed Description
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy>
class TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >
Definition at line 182 of file ConcurrentLinearAllocator.h.
Member Function Documentation
AllocateBlock()
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> FORCENOINLINE void TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::AllocateBlock (FBlockHeader *& Header) inline static private
Definition at line 308 of file ConcurrentLinearAllocator.h.
Referenced by TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc().
Free()
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> FORCEINLINE_DEBUGGABLE void TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::Free (void * Pointer) inline static
Definition at line 471 of file ConcurrentLinearAllocator.h.
Referenced by TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::~ForElementType(), TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::MoveToEmpty(), and TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Realloc().
GetAllocationHeader()
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> FORCEINLINE FAllocationHeader * TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::GetAllocationHeader (void * Pointer) inline static private
Definition at line 221 of file ConcurrentLinearAllocator.h.
Referenced by TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Free(), and TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::GetAllocationSize().
GetAllocationSize()
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> FORCEINLINE_DEBUGGABLE SIZE_T TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::GetAllocationSize (void * Pointer) inline static
Definition at line 512 of file ConcurrentLinearAllocator.h.
Referenced by TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Realloc().
LLM()
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::LLM (static constexpr ELLMAllocType LLMAllocationType = BlockAllocationTag::Allocator::UsesFMalloc ? ELLMAllocType::FMalloc :ELLMAllocType::None;) private
Malloc() [1/3]
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> template<typename T> FORCEINLINE_DEBUGGABLE void * TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::Malloc () inline static
Definition at line 334 of file ConcurrentLinearAllocator.h.
Referenced by TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc(), TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Malloc(), and TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >< FSceneRenderingBlockAllocationTag >::Realloc().
Malloc() [2/3]
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> template<uint32 Alignment> FORCEINLINE_DEBUGGABLE void * TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::Malloc (SIZE_T Size) inline static
Definition at line 328 of file ConcurrentLinearAllocator.h.
Malloc() [3/3]
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> FORCEINLINE_DEBUGGABLE void * TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::Malloc (SIZE_T Size, uint32 Alignment) inline static
Definition at line 339 of file ConcurrentLinearAllocator.h.
Realloc()
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> FORCEINLINE_DEBUGGABLE void * TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::Realloc (void * Old, SIZE_T Size, uint32 Alignment) inline static
Definition at line 532 of file ConcurrentLinearAllocator.h.
Referenced by TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::ResizeAllocation().
Field Documentation
SupportsFastPath
template<typename BlockAllocationTag, ELinearAllocatorThreadPolicy ThreadPolicy> bool TLinearAllocatorBase< BlockAllocationTag, ThreadPolicy >::SupportsFastPath static constexpr private
Initial value:
= ((BlockAllocationTag::BlockSize <= (64 * 1024)) && (FPlatformProperties::GetMaxSupportedVirtualMemoryAlignment() >= 64 * 1024))
        && FMath::IsPowerOfTwo(BlockAllocationTag::BlockSize)
        && ! 0 && !BlockAllocationTag::RequiresAccurateSize
        && BlockAllocationTag::Allocator::SupportsAlignment
Definition at line 184 of file ConcurrentLinearAllocator.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/ConcurrentLinearAllocator.h