Unreal Engine 5.6 C++ API: FHLODHashContext Class Reference
FHLODHashContext Class Reference
#include "HLODHashBuilder.h"
Public Member Functions
FHLODHashContext (FName InName)
template<typename... TArgs>
FHLODHashContext (UE::Core::TCheckedFormatString< FString::FmtCharType, TArgs... > Format, TArgs... Args)
const TCHAR * GetContext () const
Private Attributes
FString Context
Friends
FArchive & operator<< (FArchive &Ar, FHLODHashContext InContext)
Overload for FHLODHashContext to log structured properties.
Detailed Description
Definition at line 61 of file HLODHashBuilder.h.
Constructor & Destructor Documentation
FHLODHashContext() [1/2]
template<typename... TArgs> FHLODHashContext::FHLODHashContext (UE::Core::TCheckedFormatString< FString::FmtCharType, TArgs... > Format, TArgs... Args) inline explicit
Definition at line 65 of file HLODHashBuilder.h.
References Context, and Format.
Referenced by operator<<.
FHLODHashContext() [2/2]
FHLODHashContext::FHLODHashContext (FName InName) inline explicit
Definition at line 68 of file HLODHashBuilder.h.
References Context, InName, and ToString().
Member Function Documentation
GetContext()
const TCHAR * FHLODHashContext::GetContext () const inline
Definition at line 71 of file HLODHashBuilder.h.
References Context.
Referenced by operator<<.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FHLODHashContext InContext) friend
Overload for FHLODHashContext to log structured properties.
Definition at line 74 of file HLODHashBuilder.h.
References FHLODHashContext(), Ar, and GetContext().
Field Documentation
Context
FString FHLODHashContext::Context private
Definition at line 81 of file HLODHashBuilder.h.
Referenced by FHLODHashContext(), FHLODHashContext(), and GetContext().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/HLOD/HLODHashBuilder.h