Unreal Engine 5.6 C++ API: FLevelUtils Class Reference
FLevelUtils Class Reference
A set of static methods for common editor operations that operate on ULevel objects.
#include "LevelUtils.h"
Data Structures
struct FApplyLevelTransformParams
Public Member Functions
UE_DEPRECATED (4.24, "Use version that takes params struct") static void ApplyLevelTransform(ULevel *Level
Static Public Member Functions
static void ApplyEditorTransform (const ULevelStreaming *StreamingLevel, bool bDoPostEditMove=true, AActor *Actor=nullptr)
Apply the LevelEditorTransform on a level.
static void ApplyLevelTransform (const FApplyLevelTransformParams &TransformParams)
Transforms the level to a new world space.
static ULevelStreaming * FindStreamingLevel (const ULevel *Level)
Returns the streaming level corresponding to the specified ULevel, or NULL if none exists.
static ULevelStreaming * FindStreamingLevel (UWorld *InWorld, const FName PackageName)
Returns the streaming level by package FName, or NULL if none exists.
static ULevelStreaming * FindStreamingLevel (UWorld *InWorld, const TCHAR *PackageName)
Returns the streaming level by package name, or NULL if none exists.
static ULevelStreaming * GetServerVisibleStreamingLevel (UWorld *InWorld, const FName &InPackageName)
Returns the streaming level by package name if visible on server, or NULL if none exists.
static bool IsApplyingLevelTransform ()
static bool IsLevelLoaded (ULevel *Level)
Returns true if the level is currently loaded in the editor, false otherwise.
static bool IsLevelLocked (AActor *Actor)
static bool IsLevelLocked (ULevel *Level)
Returns true if the specified level is locked for edit, false otherwise.
static bool IsLevelVisible (const ULevel *Level)
Returns true if the specified level is visible in the editor, false otherwise.
static bool IsMovingLevel ()
Returns true if we are moving a level.
static bool IsServerStreamingLevelVisible (UWorld *InWorld, const FName &InPackageName)
Returns whether the given package is part of the world server visible streaming levels or not.
static bool IsValidStreamingLevel (UWorld *InWorld, const TCHAR *InPackageName)
Returns whether the given package is referenced by one of the world streaming levels or not.
static void RemoveEditorTransform (const ULevelStreaming *StreamingLevel, bool bDoPostEditMove=true, AActor *Actor=nullptr)
Remove the LevelEditorTransform from a level.
static void SetEditorTransform (ULevelStreaming *StreamingLevel, const FTransform &Transform, bool bDoPostEditMove=true)
Sets a new LevelEditorTransform on a streaming level .
static bool SupportsMakingInvisibleTransactionRequests (UWorld *InWorld)
Returns whether the world supports for a client to use "making invisible" transaction requests to the server.
static bool SupportsMakingVisibleTransactionRequests (UWorld *InWorld)
Returns whether the world supports for a client to use "making visible" transaction requests to the server.
static void ToggleLevelLock (ULevel *Level)
Sets a level's edit lock.
Data Fields
const FTransform bool bDoPostEditMove
const FTransform & LevelTransform
Static Private Attributes
static bool bApplyingLevelTransform
static bool bMovingLevel
Detailed Description
A set of static methods for common editor operations that operate on ULevel objects.
Definition at line 14 of file LevelUtils.h.
Member Function Documentation
ApplyEditorTransform()
void FLevelUtils::ApplyEditorTransform (const ULevelStreaming * StreamingLevel, bool bDoPostEditMove = true, AActor * Actor = nullptr) static
Apply the LevelEditorTransform on a level.
Parameters
StreamingLevel The level.
bDoPostEditMove Whether to call PostEditMove on actors after transforming
Actor Optional actor on which to apply the transform instead of the full level.
References Actor, and bDoPostEditMove.
ApplyLevelTransform()
void FLevelUtils::ApplyLevelTransform (const FApplyLevelTransformParams & TransformParams) static
Transforms the level to a new world space.
FindStreamingLevel() [1/3]
ULevelStreaming * FLevelUtils::FindStreamingLevel (const ULevel * Level) static
Returns the streaming level corresponding to the specified ULevel, or NULL if none exists.
Parameters
Level The level to query.
Returns
The level's streaming level, or NULL if none exists.
FindStreamingLevel() [2/3]
ULevelStreaming * FLevelUtils::FindStreamingLevel (UWorld * InWorld, const FName PackageName) static
Returns the streaming level by package FName, or NULL if none exists.
Parameters
InWorld World to look in for the streaming level
PackageFName FName of the package containing the ULevel to query
Returns
The level's streaming level, or NULL if none exists.
References PackageName.
FindStreamingLevel() [3/3]
ULevelStreaming * FLevelUtils::FindStreamingLevel (UWorld * InWorld, const TCHAR * PackageName) static
Returns the streaming level by package name, or NULL if none exists.
Parameters
InWorld World to look in for the streaming level
PackageName Name of the package containing the ULevel to query
Returns
The level's streaming level, or NULL if none exists.
References PackageName.
GetServerVisibleStreamingLevel()
ULevelStreaming * FLevelUtils::GetServerVisibleStreamingLevel (UWorld * InWorld, const FName & InPackageName) static
Returns the streaming level by package name if visible on server, or NULL if none exists.
Parameters
InWorld World to look in for the streaming level
PackageName Name of the package containing the ULevel to query
Returns
The level's streaming level if visible on server, or NULL if none exists.
IsApplyingLevelTransform()
bool FLevelUtils::IsApplyingLevelTransform () static
IsLevelLoaded()
bool FLevelUtils::IsLevelLoaded (ULevel * Level) static
Returns true if the level is currently loaded in the editor, false otherwise.
Parameters
Level The level to query.
Returns
true if the level is loaded, false otherwise.
References IsLevelVisible().
IsLevelLocked() [1/2]
bool FLevelUtils::IsLevelLocked (AActor * Actor) static
References Actor.
IsLevelLocked() [2/2]
bool FLevelUtils::IsLevelLocked (ULevel * Level) static
Returns true if the specified level is locked for edit, false otherwise.
Parameters
Level The level to query.
Returns
true if the level is locked, false otherwise.
Referenced by FBrushBuilderDragDropOp::OnDrop().
IsLevelVisible()
bool FLevelUtils::IsLevelVisible (const ULevel * Level) static
Returns true if the specified level is visible in the editor, false otherwise.
Parameters
StreamingLevel The level to query. Returns true if the specified level is visible in the editor, false otherwise.
Level The level to query.
Referenced by IsLevelLoaded().
IsMovingLevel()
bool FLevelUtils::IsMovingLevel () static
Returns true if we are moving a level.
IsServerStreamingLevelVisible()
bool FLevelUtils::IsServerStreamingLevelVisible (UWorld * InWorld, const FName & InPackageName) static
Returns whether the given package is part of the world server visible streaming levels or not.
Parameters
InWorld World to look in for the streaming level
InPackageName Name of the package containing the ULevel to query
Returns
True if the given package is referenced by one of the world server visible streaming levels, else False.
IsValidStreamingLevel()
bool FLevelUtils::IsValidStreamingLevel (UWorld * InWorld, const TCHAR * InPackageName) static
Returns whether the given package is referenced by one of the world streaming levels or not.
Parameters
InWorld World to look in for the streaming level
InPackageName Name of the package containing the ULevel to query
Returns
True if the given package is referenced by one of the world streaming levels, else False.
RemoveEditorTransform()
void FLevelUtils::RemoveEditorTransform (const ULevelStreaming * StreamingLevel, bool bDoPostEditMove = true, AActor * Actor = nullptr) static
Remove the LevelEditorTransform from a level.
Parameters
StreamingLevel The level.
bDoPostEditMove Whether to call PostEditMove on actors after transforming
Actor Optional actor on which to apply the transform instead of the full level.
References Actor, and bDoPostEditMove.
SetEditorTransform()
void FLevelUtils::SetEditorTransform (ULevelStreaming * StreamingLevel, const FTransform & Transform, bool bDoPostEditMove = true) static
Sets a new LevelEditorTransform on a streaming level .
Parameters
StreamingLevel The level.
Transform The new transform.
bDoPostEditMove Whether to call PostEditMove on actors after transforming
References bDoPostEditMove, and Transform.
SupportsMakingInvisibleTransactionRequests()
bool FLevelUtils::SupportsMakingInvisibleTransactionRequests (UWorld * InWorld) static
Returns whether the world supports for a client to use "making invisible" transaction requests to the server.
SupportsMakingVisibleTransactionRequests()
bool FLevelUtils::SupportsMakingVisibleTransactionRequests (UWorld * InWorld) static
Returns whether the world supports for a client to use "making visible" transaction requests to the server.
ToggleLevelLock()
void FLevelUtils::ToggleLevelLock (ULevel * Level) static
Sets a level's edit lock.
Parameters
Level The level to modify.
UE_DEPRECATED()
FLevelUtils::UE_DEPRECATED (4. 24, "Use version that takes params struct")
Field Documentation
bApplyingLevelTransform
bool FLevelUtils::bApplyingLevelTransform static private
Definition at line 224 of file LevelUtils.h.
bDoPostEditMove
const FTransform bool FLevelUtils::bDoPostEditMove
Initial value:
= true)
    {
        FApplyLevelTransformParams Params(Level, LevelTransform);
        Params.bDoPostEditMove = bDoPostEditMove;
        ApplyLevelTransform(Params);
    }
    static 1 void ApplyPostEditMove( ULevel* Level )
Definition at line 167 of file LevelUtils.h.
Referenced by ApplyEditorTransform(), RemoveEditorTransform(), and SetEditorTransform().
bMovingLevel
bool FLevelUtils::bMovingLevel static private
Definition at line 223 of file LevelUtils.h.
LevelTransform
const FTransform& FLevelUtils::LevelTransform
Definition at line 167 of file LevelUtils.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/LevelUtils.h