Unreal Engine 5.6 C++ API: FDetailsViewStyleKey Class Reference
FDetailsViewStyleKey Class Reference
A class which provides a strongly typed Key object for.
#include "DetailsViewStyleKey.h"
Public Member Functions
PROPERTYEDITOR_API FDetailsViewStyleKey ()
Default constructor for.
PROPERTYEDITOR_API FDetailsViewStyleKey (const FDetailsViewStyleKey &Key)
const Copy Constructor for
PROPERTYEDITOR_API FDetailsViewStyleKey (FDetailsViewStyleKey &Key)
Copy Constructor for.
PROPERTYEDITOR_API FDetailsViewStyleKey (FName InName)
A constructor for.
PROPERTYEDITOR_API FName GetName () const
Returns the FName Name of this.
PROPERTYEDITOR_API FDetailsViewStyleKey & operator= (const FDetailsViewStyleKey &OtherStyleKey)
const assignment operator
PROPERTYEDITOR_API FDetailsViewStyleKey & operator= (FDetailsViewStyleKey &OtherStyleKey)
Assignment operator for.
PROPERTYEDITOR_API bool operator== (const FDetailsViewStyleKey &OtherStyleKey) const
Private Attributes
FName Name
Detailed Description
A class which provides a strongly typed Key object for.
FDetailsViewStyleKey
instances
Definition at line 11 of file DetailsViewStyleKey.h.
Constructor & Destructor Documentation
FDetailsViewStyleKey() [1/4]
PROPERTYEDITOR_API FDetailsViewStyleKey::FDetailsViewStyleKey ()
Default constructor for.
FDetailsViewStyleKey
instances
Referenced by FDetailsViewStyleKey(), FDetailsViewStyleKey(), operator=(), operator=(), and operator==().
FDetailsViewStyleKey() [2/4]
PROPERTYEDITOR_API FDetailsViewStyleKey::FDetailsViewStyleKey (FDetailsViewStyleKey & Key)
Copy Constructor for.
FDetailsViewStyleKey
instances
References FDetailsViewStyleKey(), and Key.
FDetailsViewStyleKey() [3/4]
PROPERTYEDITOR_API FDetailsViewStyleKey::FDetailsViewStyleKey (const FDetailsViewStyleKey & Key)
const Copy Constructor for
FDetailsViewStyleKey
instances
References FDetailsViewStyleKey(), and Key.
FDetailsViewStyleKey() [4/4]
PROPERTYEDITOR_API FDetailsViewStyleKey::FDetailsViewStyleKey (FName InName)
A constructor for.
FDetailsViewStyleKey
instances which takes an FName InName to initialize the leu
References InName.
Member Function Documentation
GetName()
PROPERTYEDITOR_API FName FDetailsViewStyleKey::GetName () const
Returns the FName Name of this.
FDetailsViewStyleKey
operator=() [1/2]
PROPERTYEDITOR_API FDetailsViewStyleKey & FDetailsViewStyleKey::operator= (const FDetailsViewStyleKey & OtherStyleKey)
const assignment operator
FDetailsViewStyleKey
instances.
Parameters
OtherStyleKey the key for the
FDetailsViewStyleKey
with which to initialize this
FDetailsViewStyleKey
References FDetailsViewStyleKey().
operator=() [2/2]
PROPERTYEDITOR_API FDetailsViewStyleKey & FDetailsViewStyleKey::operator= (FDetailsViewStyleKey & OtherStyleKey)
Assignment operator for.
FDetailsViewStyleKey
instances.
Parameters
OtherStyleKey the key for the
FDetailsViewStyleKey
with which to initialize this
FDetailsViewStyleKey
References FDetailsViewStyleKey().
operator==()
PROPERTYEDITOR_API bool FDetailsViewStyleKey::operator== (const FDetailsViewStyleKey & OtherStyleKey) const
References FDetailsViewStyleKey().
Field Documentation
Name
FName FDetailsViewStyleKey::Name private
Definition at line 56 of file DetailsViewStyleKey.h.
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/DetailsViewStyleKey.h