Unreal Engine 5.6 C++ API: FField Class Reference
FField Class Reference
Base class of reflection data objects.
#include "Field.h"
Public Types
typedef FField BaseFieldClass
typedef FFieldClass FieldTypeClass
using FLinkedListBuilder = TLinkedListBuilder<FField>
typedef FField Super
typedef FField ThisClass
Public Member Functions
FField (EInternal InInernal, FFieldClass *InClass)
FField (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
virtual ~FField ()
virtual void AddCppProperty (FProperty *Property)
virtual void AddReferencedObjects (FReferenceCollector &Collector)
void AppendName (FString &ResultString) const
virtual void BeginDestroy ()
virtual void Bind ()
void ClearFlags (EObjectFlags NewFlags)
FString GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
uint64 GetCastFlags () const
FFieldClass * GetClass () const
virtual SIZE_T GetFieldSize () const
EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
FString GetFullName () const
virtual FField * GetInnerFieldByName (const FName &InName)
Returns an inner field by name if the field has any.
virtual void GetInnerFields (TArray< FField * > &OutFields)
Fills the provided array with all inner fields this field owns (recursively)
FLinkerLoad * GetLinker () const
FORCEINLINE FString GetName () const
FORCEINLINE void GetName (FString &OutName) const
UPackage * GetOutermost () const
Goes up the outer chain to look for the outermost package.
template<typename T>
T * GetOwner () const
template<typename T>
FUNCTION_NON_NULL_RETURN_START T * GetOwnerChecked () const FUNCTION_NON_NULL_RETURN_END
UClass * GetOwnerClass () const
Goes up the outer chain to look for a UClass.
UStruct * GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
UField * GetOwnerUField () const
Goes up the outer chain to look for a UField.
FORCEINLINE UObject * GetOwnerUObject () const
Goes up the outer chain to look for a UObject.
FFieldVariant GetOwnerVariant () const
Gets the owner container for this field.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=nullptr) const
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
template<typename T>
T * GetTypedOwner () const
FField * GetTypedOwner (FFieldClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
UObject * GetTypedOwner (UClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE UObject * InternalGetOwnerAsUObjectUnsafe () const
Internal function for quickly getting the owner of this object as UObject.
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *FieldType) const
bool IsIn (const FField *InOwner) const
bool IsIn (const UObject *InOwner) const
bool IsNative () const
bool IsRooted () const
bool IsValidLowLevel () const
virtual void PostDuplicate (const FField &InField)
Fixups after duplicating a Field.
virtual void PostLoad ()
void Rename (const FName &NewName)
virtual void Serialize (FArchive &Ar)
void SetFlags (EObjectFlags NewFlags)
UE_DEPRECATED (5.0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAllCastFlags(const uint64 InCastFlags) const
UE_DEPRECATED (5.0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAnyCastFlags(const uint64 InCastFlags) const
Static Public Member Functions
static FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given its class.
static FField * Construct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given the name of its class.
static FField * Duplicate (const FField *InField, FFieldVariant DestOwner, const FName DestName=NAME_None, EObjectFlags FlagMask=RF_AllFlags, EInternalObjectFlags InternalFlagsMask=EInternalObjectFlags_AllFlags)
Duplicates an FField.
static FName GenerateFFieldName (FFieldVariant InOwner, FFieldClass *InClass)
Generates a name for a Field of a given type.
static FFieldClass * StaticClass ()
static constexpr uint64 StaticClassCastFlags ()
static constexpr uint64 StaticClassCastFlagsPrivate ()
static FField * TryConstruct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Tries to construct a new field given the name of its class.
Data Fields
EObjectFlags FlagsPrivate
Object flags.
FName NamePrivate
Name of this field.
FField * Next
Next Field in the linked list.
FFieldVariant Owner
Owner of this field.
Protected Member Functions
void SetFlagsTo (EObjectFlags NewFlags)
Set the object flags directly.
Private Member Functions
UE_NONCOPYABLE (FField)
Private Attributes
FFieldClass * ClassPrivate
Pointer to the class object representing the type of this FField.
Detailed Description
Base class of reflection data objects.
Definition at line 453 of file Field.h.
Member Typedef Documentation
BaseFieldClass
typedef FField FField::BaseFieldClass
Definition at line 463 of file Field.h.
FieldTypeClass
typedef FFieldClass FField::FieldTypeClass
Definition at line 464 of file Field.h.
FLinkedListBuilder
using FField::FLinkedListBuilder = TLinkedListBuilder<FField>
Definition at line 963 of file Field.h.
Super
typedef FField FField::Super
Definition at line 461 of file Field.h.
ThisClass
typedef FField FField::ThisClass
Definition at line 462 of file Field.h.
Constructor & Destructor Documentation
FField() [1/2]
FField::FField (EInternal InInernal, FFieldClass * InClass)
Referenced by Construct(), Construct(), FProperty::DECLARE_FIELD_API(), Duplicate(), GetFieldSize(), FArrayProperty::GetInnerFieldByName(), FEnumProperty::GetInnerFieldByName(), GetInnerFieldByName(), FMapProperty::GetInnerFieldByName(), FOptionalProperty::GetInnerFieldByName(), FSetProperty::GetInnerFieldByName(), GetTypedOwner(), IsIn(), FArrayProperty::PostDuplicate(), FBoolProperty::PostDuplicate(), FDelegateProperty::PostDuplicate(), FEnumProperty::PostDuplicate(), PostDuplicate(), FInterfaceProperty::PostDuplicate(), FMapProperty::PostDuplicate(), FMulticastDelegateProperty::PostDuplicate(), FObjectPropertyBase::PostDuplicate(), FOptionalProperty::PostDuplicate(), FProperty::PostDuplicate(), FSetProperty::PostDuplicate(), FStructProperty::PostDuplicate(), TryConstruct(), and UE_NONCOPYABLE().
FField() [2/2]
FField::FField (FFieldVariant InOwner, const FName & InName, EObjectFlags InObjectFlags)
References InName.
~FField()
virtual FField::~FField () virtual
Member Function Documentation
AddCppProperty()
virtual void FField::AddCppProperty (FProperty * Property) virtual
Reimplemented in FArrayProperty, FEnumProperty, FMapProperty, FOptionalProperty, and FSetProperty.
References Property.
AddReferencedObjects()
virtual void FField::AddReferencedObjects (FReferenceCollector & Collector) virtual
Reimplemented in FArrayProperty, FByteProperty, FClassProperty, FDelegateProperty, FEnumProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, FSoftClassProperty, and FStructProperty.
Referenced by FArchiveScriptReferenceCollector::operator<<().
AppendName()
void FField::AppendName (FString & ResultString) const inline
Definition at line 625 of file Field.h.
References FName::AppendString(), and GetFName().
BeginDestroy()
virtual void FField::BeginDestroy () virtual
Reimplemented in FClassProperty, FDelegateProperty, FInterfaceProperty, FMulticastDelegateProperty, FObjectPropertyBase, and FSoftClassProperty.
Bind()
virtual void FField::Bind () virtual
ClearFlags()
void FField::ClearFlags (EObjectFlags NewFlags) inline
Definition at line 557 of file Field.h.
References checkSlow, GetFlags(), RF_AllFlags, RF_MarkAsNative, RF_MarkAsRootSet, and SetFlagsTo().
Construct() [1/2]
FField * FField::Construct (const FFieldVariant & InOwner, const FName & InName, EObjectFlags InFlags) static
Constructs a new field given its class.
References FField(), and InName.
Referenced by SerializeSingleField().
Construct() [2/2]
FField * FField::Construct (const FName & FieldTypeName, const FFieldVariant & InOwner, const FName & InName, EObjectFlags InFlags) static
Constructs a new field given the name of its class.
References FField(), and InName.
Duplicate()
FField * FField::Duplicate (const FField * InField, FFieldVariant DestOwner, const FName DestName = NAME_None, EObjectFlags FlagMask = RF_AllFlags, EInternalObjectFlags InternalFlagsMask = EInternalObjectFlags_AllFlags) static
Duplicates an FField.
References FField(), EInternalObjectFlags_AllFlags, and RF_AllFlags.
GenerateFFieldName()
FName FField::GenerateFFieldName (FFieldVariant InOwner, FFieldClass * InClass) static
Generates a name for a Field of a given type.
Each generated name is unique in the current runtime
GetAuthoredName()
FString FField::GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
By default this is the same as GetName() but it can be overridden if that is an internal-only name. This name is consistent in editor/cooked builds, is not localized, and is useful for data import/export.
GetCastFlags()
uint64 FField::GetCastFlags () const inline
Definition at line 589 of file Field.h.
References FFieldClass::GetCastFlags(), and GetClass().
Referenced by IsA(), UE_DEPRECATED(), and UE_DEPRECATED().
GetClass()
FFieldClass * FField::GetClass () const inline
Definition at line 585 of file Field.h.
References ClassPrivate.
Referenced by FProperty::ContainerUObjectPtrToValuePtrInternal(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), ExactCastField(), ExactCastField(), GetCastFlags(), IsA(), IsA(), and FFieldPath::ResolveField().
GetFieldSize()
virtual SIZE_T FField::GetFieldSize () const inline virtual
Definition at line 468 of file Field.h.
References FField().
GetFlags()
EObjectFlags FField::GetFlags () const inline
Retrieve the object flags directly.
Returns
Flags for this object
Definition at line 546 of file Field.h.
References checkfSlow, FlagsPrivate, GetFName(), RF_AllFlags, TEXT, and ToString().
Referenced by ClearFlags(), HasAllFlags(), HasAnyFlags(), and SetFlags().
GetFName()
FORCEINLINE FName FField::GetFName () const inline
Definition at line 697 of file Field.h.
References FORCEINLINE, IsThisNotNull(), NamePrivate, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by AppendName(), ENUM_CLASS_FLAGS(), GetFlags(), GetFNameSafe(), FAnimGraphNodeAlphaOptions::HandlePostEditChangeProperty(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), SetFlagsTo(), and FPropertyPath::ToString().
GetFullName()
FString FField::GetFullName () const
Referenced by FProperty::CallGetter(), FProperty::CallSetter(), and GetReplicatedProperty().
GetInnerFieldByName()
virtual FField * FField::GetInnerFieldByName (const FName & InName) inline virtual
Returns an inner field by name if the field has any.
Reimplemented in FArrayProperty, FEnumProperty, FMapProperty, FOptionalProperty, and FSetProperty.
Definition at line 753 of file Field.h.
References FField(), and InName.
GetInnerFields()
virtual void FField::GetInnerFields (TArray< FField * > & OutFields) inline virtual
Fills the provided array with all inner fields this field owns (recursively)
Reimplemented in FArrayProperty, FEnumProperty, FMapProperty, FOptionalProperty, and FSetProperty.
Definition at line 759 of file Field.h.
GetLinker()
FLinkerLoad * FField::GetLinker () const
GetName() [1/2]
FORCEINLINE FString FField::GetName () const inline
Definition at line 711 of file Field.h.
References FORCEINLINE, IsThisNotNull(), NamePrivate, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and TEXT.
Referenced by FProperty::ContainerUObjectPtrToValuePtrInternal(), FGameModeInfoCustomizer::CreateGameModePropertyLabelWidget(), GetNameSafe(), and FGameModeInfoCustomizer::OnMakeNewDefaultClassClicked().
GetName() [2/2]
FORCEINLINE void FField::GetName (FString & OutName) const inline
Definition at line 725 of file Field.h.
References FORCEINLINE, IsThisNotNull(), NamePrivate, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and TEXT.
GetOutermost()
UPackage * FField::GetOutermost () const
Goes up the outer chain to look for the outermost package.
GetOwner()
template<typename T> T * FField::GetOwner () const inline
Definition at line 673 of file Field.h.
References Owner.
Referenced by FProperty::ContainerUObjectPtrToValuePtrInternal(), FProperty::ContainerVoidPtrToValuePtrInternal(), FProperty::GetOwnerProperty(), FProperty::GetOwnerProperty(), and FPropertyChangedParams::GetPropertyValue().
GetOwnerChecked()
template<typename T> FUNCTION_NON_NULL_RETURN_START T * FField::GetOwnerChecked () const inline
Definition at line 681 of file Field.h.
References check, FUNCTION_NON_NULL_RETURN_END, and Owner.
GetOwnerClass()
UClass * FField::GetOwnerClass () const
Goes up the outer chain to look for a UClass.
Referenced by FProperty::ShouldDuplicateValue().
GetOwnerStruct()
UStruct * FField::GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
GetOwnerUField()
UField * FField::GetOwnerUField () const
Goes up the outer chain to look for a UField.
GetOwnerUObject()
FORCEINLINE UObject * FField::GetOwnerUObject () const inline
Goes up the outer chain to look for a UObject.
This function is used in GC so for performance reasons it has to be inlined
Definition at line 637 of file Field.h.
References FORCEINLINE, FFieldVariant::IsUObject(), FFieldVariant::IsValid(), Owner, FFieldVariant::ToFieldUnsafe(), and FFieldVariant::ToUObject().
GetOwnerVariant()
FFieldVariant FField::GetOwnerVariant () const inline
Gets the owner container for this field.
Definition at line 631 of file Field.h.
References Owner.
GetPathName() [1/2]
void FField::GetPathName (const UObject * StopOuter, FStringBuilderBase & ResultString) const
GetPathName() [2/2]
FString FField::GetPathName (const UObject * StopOuter = nullptr) const
GetPreloadDependencies()
virtual void FField::GetPreloadDependencies (TArray< UObject * > & OutDeps) virtual
Reimplemented in FArrayProperty, FByteProperty, FEnumProperty, FMapProperty, FOptionalProperty, FSetProperty, and FStructProperty.
GetTypedOwner() [1/3]
template<typename T> T * FField::GetTypedOwner () const inline
Definition at line 691 of file Field.h.
References GetTypedOwner().
Referenced by GetTypedOwner().
GetTypedOwner() [2/3]
FField * FField::GetTypedOwner (FFieldClass * Target) const
Goes up the outer chain to look for the outer of the specified type.
References FField(), and Target.
GetTypedOwner() [3/3]
UObject * FField::GetTypedOwner (UClass * Target) const
Goes up the outer chain to look for the outer of the specified type.
References Target.
HasAllFlags()
bool FField::HasAllFlags (EObjectFlags FlagsToCheck) const inline
Used to safely check whether all of the passed in flags are set.
Parameters
FlagsToCheck Object flags to check for
Returns
true if all of the passed in flags are set (including no flags passed in), false otherwise
Definition at line 579 of file Field.h.
References checkSlow, GetFlags(), RF_AllFlags, RF_MarkAsNative, and RF_MarkAsRootSet.
HasAnyFlags()
bool FField::HasAnyFlags (EObjectFlags FlagsToCheck) const inline
Used to safely check whether any of the passed in flags are set.
Parameters
FlagsToCheck Object flags to check for.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 568 of file Field.h.
References checkSlow, GetFlags(), RF_AllFlags, RF_MarkAsNative, and RF_MarkAsRootSet.
Referenced by FTrackInstancePropertyBindings::FResolvedProperty::GetValidProperty().
InternalGetOwnerAsUObjectUnsafe()
FORCEINLINE UObject * FField::InternalGetOwnerAsUObjectUnsafe () const inline
Internal function for quickly getting the owner of this object as UObject.
FOR INTERNAL USE ONLY
Definition at line 649 of file Field.h.
References FORCEINLINE, and Owner.
IsA() [1/2]
template<typename T> bool FField::IsA () const inline
Definition at line 601 of file Field.h.
References GetCastFlags(), GetClass(), and FFieldClass::IsChildOf().
Referenced by FProperty::ContainerUObjectPtrToValuePtrInternal().
IsA() [2/2]
bool FField::IsA (const FFieldClass * FieldType) const inline
Definition at line 594 of file Field.h.
References check, GetClass(), and FFieldClass::IsChildOf().
Referenced by RigVMTypeUtils::AreCompatible(), CastField(), CastField(), CastFieldCheckedNullAllowed(), CastFieldCheckedNullAllowed(), FRigVMMemoryHandle::IsPropertyType(), TPropertyIterator< T >::IterateToNext(), FFieldPath::ResolveField(), and FPropertyPath::ToString().
IsIn() [1/2]
bool FField::IsIn (const FField * InOwner) const
References FField().
IsIn() [2/2]
bool FField::IsIn (const UObject * InOwner) const
IsNative()
bool FField::IsNative () const
Referenced by FObjectProperty::ClearIntrusiveOptionalValue(), and FObjectProperty::IsIntrusiveOptionalValueSet().
IsRooted()
bool FField::IsRooted () const
IsValidLowLevel()
bool FField::IsValidLowLevel () const
Referenced by FProperty::ContainerUObjectPtrToValuePtrInternal().
PostDuplicate()
virtual void FField::PostDuplicate (const FField & InField) virtual
Fixups after duplicating a Field.
Reimplemented in FArrayProperty, FBoolProperty, FByteProperty, FClassProperty, FDelegateProperty, FEnumProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FProperty, FSetProperty, FSoftClassProperty, and FStructProperty.
References FField().
PostLoad()
virtual void FField::PostLoad () virtual
Rename()
void FField::Rename (const FName & NewName)
Serialize()
virtual void FField::Serialize (FArchive & Ar) virtual
Reimplemented in FArrayProperty, FBoolProperty, FByteProperty, FClassProperty, FDelegateProperty, FEnumProperty, FFieldPathProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FProperty, FSetProperty, FSoftClassProperty, and FStructProperty.
References Ar.
SetFlags()
void FField::SetFlags (EObjectFlags NewFlags) inline
Definition at line 552 of file Field.h.
References checkSlow, GetFlags(), RF_MarkAsNative, RF_MarkAsRootSet, and SetFlagsTo().
SetFlagsTo()
void FField::SetFlagsTo (EObjectFlags NewFlags) inline protected
Set the object flags directly.
Definition at line 535 of file Field.h.
References checkfSlow, FlagsPrivate, GetFName(), RF_AllFlags, TEXT, and ToString().
Referenced by ClearFlags(), and SetFlags().
StaticClass()
FFieldClass * FField::StaticClass () static
Referenced by FFieldPath::ResolveField(), FFrame::StepCompiledIn(), and FPropertyPath::ToString().
StaticClassCastFlags()
constexpr uint64 FField::StaticClassCastFlags () inline static constexpr
Definition at line 477 of file Field.h.
References CASTCLASS_UField.
StaticClassCastFlagsPrivate()
constexpr uint64 FField::StaticClassCastFlagsPrivate () inline static constexpr
Definition at line 473 of file Field.h.
References CASTCLASS_UField.
TryConstruct()
FField * FField::TryConstruct (const FName & FieldTypeName, const FFieldVariant & InOwner, const FName & InName, EObjectFlags InFlags) static
Tries to construct a new field given the name of its class.
Returns null if the type does not exist.
References FField(), and InName.
UE_DEPRECATED() [1/2]
FField::UE_DEPRECATED (5. 0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") const inline
Definition at line 619 of file Field.h.
References GetCastFlags().
UE_DEPRECATED() [2/2]
FField::UE_DEPRECATED (5. 0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") const inline
Definition at line 613 of file Field.h.
References GetCastFlags().
UE_NONCOPYABLE()
FField::UE_NONCOPYABLE (FField) private
References FField().
Field Documentation
ClassPrivate
FFieldClass* FField::ClassPrivate private
Pointer to the class object representing the type of this FField.
Definition at line 458 of file Field.h.
Referenced by GetClass().
FlagsPrivate
EObjectFlags FField::FlagsPrivate
Object flags.
Definition at line 492 of file Field.h.
Referenced by GetFlags(), and SetFlagsTo().
NamePrivate
FName FField::NamePrivate
Name of this field.
Definition at line 489 of file Field.h.
Referenced by GetFName(), GetName(), and GetName().
Next
FField* FField::Next
Next Field in the linked list.
Definition at line 486 of file Field.h.
Referenced by UE::Private::DoesParamMatch(), and TPropertyIterator< T >::IterateToNext().
Owner
FFieldVariant FField::Owner
Owner of this field.
Definition at line 483 of file Field.h.
Referenced by GetOwner(), GetOwnerChecked(), GetOwnerUObject(), GetOwnerVariant(), FArrayProperty::InstanceSubobjects(), FDelegateProperty::InstanceSubobjects(), FMapProperty::InstanceSubobjects(), FMulticastDelegateProperty::InstanceSubobjects(), FObjectPropertyBase::InstanceSubobjects(), FOptionalProperty::InstanceSubobjects(), FProperty::InstanceSubobjects(), FSetProperty::InstanceSubobjects(), FStructProperty::InstanceSubobjects(), and InternalGetOwnerAsUObjectUnsafe().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/Field.h