Unreal Engine 5.6 C++ API: FDynamicResolutionHeuristicProxy Class Reference
FDynamicResolutionHeuristicProxy Class Reference
Render thread proxy that holds the heuristic for dynamic resolution.
#include "DynamicResolutionProxy.h"
Data Structures
struct FrameHistoryEntry
Public Member Functions
FDynamicResolutionHeuristicProxy ()
~FDynamicResolutionHeuristicProxy ()
void CreateNewPreviousFrameTimings_RenderThread (float GameThreadTimeMs, float RenderThreadTimeMs, float TotalFrameGPUBusyTimeMs)
Create a new previous frame and feeds its timings.
FORCEINLINE DynamicRenderScaling::TMap< float > GetResolutionFractionsApproximation_GameThread () const
Returns a non thread safe approximation of the current resolution fraction applied on render thread.
DynamicRenderScaling::TMap< float > GetResolutionFractionUpperBounds () const
Returns the view fraction upper bound.
FORCEINLINE DynamicRenderScaling::TMap< float > QueryCurrentFrameResolutionFractions () const
Returns the view fraction that should be used for current frame.
void RefreshCurrentFrameResolutionFraction_RenderThread ()
Refresh resolution fraction's from history.
void Reset_RenderThread ()
Resets the proxy.
void SetTemporalUpscaler (const UE::Renderer::Private::ITemporalUpscaler *InTemporalUpscaler)
Applies the minimum/maximum resolution fraction for a third-party temporal upscaler.
Static Public Member Functions
static TSharedPtr< class IDynamicResolutionState > CreateDefaultState ()
Creates a default dynamic resolution state using this proxy that queries GPU timing from the RHI.
Private Member Functions
const FrameHistoryEntry & GetPreviousFrameEntry (int32 BrowsingFrameId) const
DynamicRenderScaling::TMap< float > QueryCurrentFrameResolutionFractions_Internal () const
void RefreshCurrentFrameResolutionFractionUpperBound_RenderThread ()
void RefreshHeuristicStats_RenderThread ()
void ResetInternal ()
void ResizeHistoryIfNeeded ()
Private Attributes
DynamicRenderScaling::TMap< int32 > BudgetHistorySizes
DynamicRenderScaling::TMap< float > CurrentFrameMaxResolutionFractions
DynamicRenderScaling::TMap< float > CurrentFrameResolutionFractions
TArray< FrameHistoryEntry > History
int32 HistorySize
int32 IgnoreFrameRemainingCount
int32 NumberOfFramesSinceScreenPercentageChange
int32 PreviousFrameIndex
float TemporalUpscalerMaxResolutionFraction
float TemporalUpscalerMinResolutionFraction
Detailed Description
Render thread proxy that holds the heuristic for dynamic resolution.
Definition at line 11 of file DynamicResolutionProxy.h.
Constructor & Destructor Documentation
FDynamicResolutionHeuristicProxy()
FDynamicResolutionHeuristicProxy::FDynamicResolutionHeuristicProxy ()
~FDynamicResolutionHeuristicProxy()
FDynamicResolutionHeuristicProxy::~FDynamicResolutionHeuristicProxy ()
Member Function Documentation
CreateDefaultState()
TSharedPtr< class IDynamicResolutionState > FDynamicResolutionHeuristicProxy::CreateDefaultState () static
Creates a default dynamic resolution state using this proxy that queries GPU timing from the RHI.
CreateNewPreviousFrameTimings_RenderThread()
void FDynamicResolutionHeuristicProxy::CreateNewPreviousFrameTimings_RenderThread (float GameThreadTimeMs, float RenderThreadTimeMs, float TotalFrameGPUBusyTimeMs)
Create a new previous frame and feeds its timings.
GetPreviousFrameEntry()
const FrameHistoryEntry & FDynamicResolutionHeuristicProxy::GetPreviousFrameEntry (int32 BrowsingFrameId) const inline private
Definition at line 98 of file DynamicResolutionProxy.h.
References History, HistorySize, and PreviousFrameIndex.
GetResolutionFractionsApproximation_GameThread()
FORCEINLINE DynamicRenderScaling::TMap< float > FDynamicResolutionHeuristicProxy::GetResolutionFractionsApproximation_GameThread () const inline
Returns a non thread safe approximation of the current resolution fraction applied on render thread.
Definition at line 34 of file DynamicResolutionProxy.h.
References check, FORCEINLINE, IsInGameThread(), and QueryCurrentFrameResolutionFractions_Internal().
GetResolutionFractionUpperBounds()
DynamicRenderScaling::TMap< float > FDynamicResolutionHeuristicProxy::GetResolutionFractionUpperBounds () const
Returns the view fraction upper bound.
QueryCurrentFrameResolutionFractions()
FORCEINLINE DynamicRenderScaling::TMap< float > FDynamicResolutionHeuristicProxy::QueryCurrentFrameResolutionFractions () const inline
Returns the view fraction that should be used for current frame.
Definition at line 27 of file DynamicResolutionProxy.h.
References check, FORCEINLINE, IsInParallelRenderingThread(), and QueryCurrentFrameResolutionFractions_Internal().
QueryCurrentFrameResolutionFractions_Internal()
DynamicRenderScaling::TMap< float > FDynamicResolutionHeuristicProxy::QueryCurrentFrameResolutionFractions_Internal () const private
Referenced by GetResolutionFractionsApproximation_GameThread(), and QueryCurrentFrameResolutionFractions().
RefreshCurrentFrameResolutionFraction_RenderThread()
void FDynamicResolutionHeuristicProxy::RefreshCurrentFrameResolutionFraction_RenderThread ()
Refresh resolution fraction's from history.
RefreshCurrentFrameResolutionFractionUpperBound_RenderThread()
void FDynamicResolutionHeuristicProxy::RefreshCurrentFrameResolutionFractionUpperBound_RenderThread () private
RefreshHeuristicStats_RenderThread()
void FDynamicResolutionHeuristicProxy::RefreshHeuristicStats_RenderThread () private
Reset_RenderThread()
void FDynamicResolutionHeuristicProxy::Reset_RenderThread ()
Resets the proxy.
ResetInternal()
void FDynamicResolutionHeuristicProxy::ResetInternal () private
ResizeHistoryIfNeeded()
void FDynamicResolutionHeuristicProxy::ResizeHistoryIfNeeded () private
SetTemporalUpscaler()
void FDynamicResolutionHeuristicProxy::SetTemporalUpscaler (const UE::Renderer::Private::ITemporalUpscaler * InTemporalUpscaler)
Applies the minimum/maximum resolution fraction for a third-party temporal upscaler.
Field Documentation
BudgetHistorySizes
DynamicRenderScaling::TMap<int32> FDynamicResolutionHeuristicProxy::BudgetHistorySizes private
Definition at line 92 of file DynamicResolutionProxy.h.
CurrentFrameMaxResolutionFractions
DynamicRenderScaling::TMap<float> FDynamicResolutionHeuristicProxy::CurrentFrameMaxResolutionFractions private
Definition at line 91 of file DynamicResolutionProxy.h.
CurrentFrameResolutionFractions
DynamicRenderScaling::TMap<float> FDynamicResolutionHeuristicProxy::CurrentFrameResolutionFractions private
Definition at line 90 of file DynamicResolutionProxy.h.
History
TArray<FrameHistoryEntry> FDynamicResolutionHeuristicProxy::History private
Definition at line 79 of file DynamicResolutionProxy.h.
Referenced by GetPreviousFrameEntry().
HistorySize
int32 FDynamicResolutionHeuristicProxy::HistorySize private
Definition at line 81 of file DynamicResolutionProxy.h.
Referenced by GetPreviousFrameEntry().
IgnoreFrameRemainingCount
int32 FDynamicResolutionHeuristicProxy::IgnoreFrameRemainingCount private
Definition at line 87 of file DynamicResolutionProxy.h.
NumberOfFramesSinceScreenPercentageChange
int32 FDynamicResolutionHeuristicProxy::NumberOfFramesSinceScreenPercentageChange private
Definition at line 84 of file DynamicResolutionProxy.h.
PreviousFrameIndex
int32 FDynamicResolutionHeuristicProxy::PreviousFrameIndex private
Definition at line 80 of file DynamicResolutionProxy.h.
Referenced by GetPreviousFrameEntry().
TemporalUpscalerMaxResolutionFraction
float FDynamicResolutionHeuristicProxy::TemporalUpscalerMaxResolutionFraction private
Definition at line 96 of file DynamicResolutionProxy.h.
TemporalUpscalerMinResolutionFraction
float FDynamicResolutionHeuristicProxy::TemporalUpscalerMinResolutionFraction private
Definition at line 95 of file DynamicResolutionProxy.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/DynamicResolutionProxy.h