Unreal Engine 5.6 C++ API: UE::Geometry::FMeshRefinerBase Class Reference
UE::Geometry::FMeshRefinerBase Class Reference
This is a base class that implements common functionality for various triangle mesh resampling strategies (ie FRemesher and FReducer).
#include "MeshRefinerBase.h"
Public Types
enum class ETargetProjectionMode : uint8 { NoProjection = 0 , AfterRefinement = 1 , Inline = 2 }
Options for projecting vertices onto target surface.
enum class EVertexControl : uint8 { AllowAll = 0 , NoSmooth = 1 , NoProject = 2 , NoMovement = NoSmooth | NoProject }
Public Member Functions
FMeshRefinerBase (const FMeshRefinerBase &)=delete
FMeshRefinerBase (FMeshRefinerBase &&)=delete
virtual ~FMeshRefinerBase ()
virtual bool Cancelled ()
If this returns true, abort computation.
const TOptional< FMeshConstraints > & GetConstraints ()
Get the current mesh constraints.
double GetEdgeFlipTolerance ()
FDynamicMesh3 * GetMesh ()
Get the current mesh we are operating on.
FMeshRefinerBase & operator= (const FMeshRefinerBase &)=delete
FMeshRefinerBase & operator= (FMeshRefinerBase &&)=delete
IProjectionTarget * ProjectionTarget ()
Get the current Projection Target.
void SetEdgeFlipTolerance (double NewTolerance)
Set edge flip tolerance.
void SetExternalConstraints (TOptional< FMeshConstraints > ConstraintsIn)
Set external constraints.
DYNAMICMESH_API void SetMeshChangeTracker (FDynamicMeshChangeTracker *Tracker)
void SetProjectionTarget (IProjectionTarget *TargetIn)
Set a Projection Target.
Public Member Functions inherited from UE::Geometry::FMeshRefinerBaseFixLayout
virtual ~FMeshRefinerBaseFixLayout ()=default
Data Fields
bool AllowCollapseFixedVertsWithSameSetID = true
If true, then when two Fixed vertices have the same non-invalid SetID, we treat them as not fixed and allow collapse.
int DEBUG_CHECK_LEVEL = 0
0 = no checking, 1 = check constraints each pass, 2 = and check validity each pass, 3 = and check validity after every mesh change (v slow but best for debugging)
TArray< int > DebugEdges
This is a debugging aid, will break to debugger if these edges are touched, in debug builds.
bool ENABLE_PROFILING = false
Set to true to profile various passes.
FProgressCancel * Progress = nullptr
Set this to be able to cancel running Remesher/Reducer.
ETargetProjectionMode ProjectionMode = ETargetProjectionMode::NoProjection
Method to use to project vertices onto target surface.
TFunction< EVertexControl(int)> VertexControlF = nullptr
This function allows client to specify fine-grained control over what happens to specific vertices.
Protected Member Functions
FMeshRefinerBase ()
FMeshRefinerBase (FDynamicMesh3 *MeshIn)
DYNAMICMESH_API bool CanCollapseEdge (int eid, int a, int b, int c, int d, int tc, int td, int &collapse_to) const
Figure out if we can collapse edge eid=[a,b] under current constraint set.
DYNAMICMESH_API bool CanCollapseVertex (int eid, int a, int b, int &collapse_to) const
Resolve vertex constraints for collapsing edge eid=[a,b].
DYNAMICMESH_API bool CheckIfCollapseCreatesFlipOrInvalid (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a face-normal flip.
DYNAMICMESH_API bool CheckIfCollapseCreatesTinyTriangle (int vid, int vother, const FVector3d &newv, int tc, int td) const
Check if edge collapse will create a triangle with small area (either all vertices are close together, or in a sliver configuration) This only checks one-ring of vid, so you have to call it twice, with vid and vother reversed, to check both one-rings.
DYNAMICMESH_API bool CheckIfFlipCreatesTinyTriangle (int OriginalEdgeVertexA, int OriginalEdgeVertexB, int OppositeEdgeVertexC, int OppositeEdgeVertexD, int OriginalTriangleIndex) const
Check if edge flip might create a triangle with small area (either all vertices are close together, or in a sliver configuration)
DYNAMICMESH_API bool CheckIfFlipInvertsNormals (int a, int b, int c, int d, int t0) const
Check if edge flip might reverse normal direction.
double ComputeEdgeFlipMetric (const FVector3d &Direction0, const FVector3d &Direction1) const
DYNAMICMESH_API void DebugCheckUVSeamConstraints ()
DYNAMICMESH_API void DebugCheckVertexConstraints ()
virtual DYNAMICMESH_API void DoDebugChecks (bool bEndOfPass=false)
FVertexConstraint GetVertexConstraint (int VertexID)
bool GetVertexConstraint (int VertexID, FVertexConstraint &OutConstraint)
bool IsVertexPositionConstrained (int VertexID)
DYNAMICMESH_API void RuntimeDebugCheck (int EdgeID)
virtual DYNAMICMESH_API void SaveEdgeBeforeModify (int32 EdgeID)
virtual DYNAMICMESH_API void SaveTriangleBeforeModify (int32 TriangleID)
virtual DYNAMICMESH_API void SaveVertexTrianglesBeforeModify (int32 VertexID)
Protected Attributes
FDynamicMeshChangeTracker * ActiveChangeTracker = nullptr
TOptional< FMeshConstraints > Constraints
Constraints are used to control how certain edges and vertices can be modified.
double EdgeFlipTolerance = 0.0f
If normals dot product is less than this, we consider it a normal flip.
FDynamicMesh3 * Mesh = nullptr
Mesh that will be refined.
IProjectionTarget * ProjTarget = nullptr
Vertices can be projected onto this surface when they are modified.
double TinyTriangleThreshold = SMALL_NUMBER
Avoid creation of triangles smaller than this value.
Detailed Description
This is a base class that implements common functionality for various triangle mesh resampling strategies (ie FRemesher and FReducer).
You probably should not use this class directly.
Definition at line 29 of file MeshRefinerBase.h.
Member Enumeration Documentation
ETargetProjectionMode
enum class UE::Geometry::FMeshRefinerBase::ETargetProjectionMode : uint8 strong
Options for projecting vertices onto target surface.
Enumerator
NoProjection
AfterRefinement
Inline
Definition at line 75 of file MeshRefinerBase.h.
EVertexControl
enum class UE::Geometry::FMeshRefinerBase::EVertexControl : uint8 strong
Enumerator
AllowAll
NoSmooth
NoProject
NoMovement
Definition at line 55 of file MeshRefinerBase.h.
Constructor & Destructor Documentation
FMeshRefinerBase() [1/4]
UE::Geometry::FMeshRefinerBase::FMeshRefinerBase (FDynamicMesh3 * MeshIn) inline protected
Definition at line 43 of file MeshRefinerBase.h.
Referenced by FMeshRefinerBase(), FMeshRefinerBase(), UE::Geometry::FRemesher::FRemesher(), UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::TMeshSimplification(), operator=(), and operator=().
FMeshRefinerBase() [2/4]
UE::Geometry::FMeshRefinerBase::FMeshRefinerBase () inline protected
Definition at line 48 of file MeshRefinerBase.h.
FMeshRefinerBase() [3/4]
UE::Geometry::FMeshRefinerBase::FMeshRefinerBase (const FMeshRefinerBase &) delete
References FMeshRefinerBase().
FMeshRefinerBase() [4/4]
UE::Geometry::FMeshRefinerBase::FMeshRefinerBase (FMeshRefinerBase &&) delete
References FMeshRefinerBase().
~FMeshRefinerBase()
virtual UE::Geometry::FMeshRefinerBase::~FMeshRefinerBase () inline virtual
Definition at line 106 of file MeshRefinerBase.h.
Member Function Documentation
Cancelled()
virtual bool UE::Geometry::FMeshRefinerBase::Cancelled () inline virtual
If this returns true, abort computation.
Definition at line 142 of file MeshRefinerBase.h.
References Progress.
CanCollapseEdge()
DYNAMICMESH_API bool UE::Geometry::FMeshRefinerBase::CanCollapseEdge (int eid, int a, int b, int c, int d, int tc, int td, int & collapse_to) const protected
Figure out if we can collapse edge eid=[a,b] under current constraint set.
First we resolve vertex constraints using CanCollapseVertex(). However this does not catch some topological cases at the edge-constraint level, which which we will only be able to detect once we know if we are losing a or b. See comments on CanCollapseVertex() for what collapse_to is for.
Parameters
a first vertex of edge
b second vertex of edge
c opposing vertex 1
d opposing vertex 2
tc index of triangle [a,b,c]
td index of triangle [a,b,d]
collapse_to either a or b if we should collapse to one of those, or -1 if either is acceptable
CanCollapseVertex()
DYNAMICMESH_API bool UE::Geometry::FMeshRefinerBase::CanCollapseVertex (int eid, int a, int b, int & collapse_to) const protected
Resolve vertex constraints for collapsing edge eid=[a,b].
Generally we would collapse a to b, and set the new position as 0.5*(v_a+v_b). However if a or b are constrained, then we want to keep that vertex and collapse to its position. This vertex (a or b) will be returned in collapse_to, which is -1 otherwise. If a and b are constrained, then things are complicated (and documented below).
Parameters
eid edge ID
a first vertex of edge
b second vertex of edge*
collapse_to either a or b if we should collapse to one of those, or -1 if either is acceptable
CheckIfCollapseCreatesFlipOrInvalid()
DYNAMICMESH_API bool UE::Geometry::FMeshRefinerBase::CheckIfCollapseCreatesFlipOrInvalid (int vid, int vother, const FVector3d & newv, int tc, int td) const protected
Check if edge collapse will create a face-normal flip.
Also checks if collapse would violate link condition, since we are iterating over one-ring anyway. This only checks one-ring of vid, so you have to call it twice, with vid and vother reversed, to check both one-rings
Parameters
vid first vertex of edge
vother other vertex of edge
newv new vertex position after collapse
tc triangle on one side of edge
td triangle on other side of edge
CheckIfCollapseCreatesTinyTriangle()
DYNAMICMESH_API bool UE::Geometry::FMeshRefinerBase::CheckIfCollapseCreatesTinyTriangle (int vid, int vother, const FVector3d & newv, int tc, int td) const protected
Check if edge collapse will create a triangle with small area (either all vertices are close together, or in a sliver configuration) This only checks one-ring of vid, so you have to call it twice, with vid and vother reversed, to check both one-rings.
Parameters
vid first vertex of edge
vother other vertex of edge
newv new vertex position after collapse
tc triangle on one side of edge
td triangle on other side of edge
CheckIfFlipCreatesTinyTriangle()
DYNAMICMESH_API bool UE::Geometry::FMeshRefinerBase::CheckIfFlipCreatesTinyTriangle (int OriginalEdgeVertexA, int OriginalEdgeVertexB, int OppositeEdgeVertexC, int OppositeEdgeVertexD, int OriginalTriangleIndex) const protected
Check if edge flip might create a triangle with small area (either all vertices are close together, or in a sliver configuration)
Parameters
a first vertex of edge
b second vertex of edge
c opposing vertex 1
d opposing vertex 2
t0 index of triangle containing [a,b,c]
CheckIfFlipInvertsNormals()
DYNAMICMESH_API bool UE::Geometry::FMeshRefinerBase::CheckIfFlipInvertsNormals (int a, int b, int c, int d, int t0) const protected
Check if edge flip might reverse normal direction.
Not entirely clear on how to best implement this test. Currently checking if any normal-pairs are reversed.
Parameters
a first vertex of edge
b second vertex of edge
c opposing vertex 1
d opposing vertex 2
t0 index of triangle containing [a,b,c]
ComputeEdgeFlipMetric()
double UE::Geometry::FMeshRefinerBase::ComputeEdgeFlipMetric (const FVector3d & Direction0, const FVector3d & Direction1) const inline protected
Returns
edge-flip dotproduct metric in range [-1,1] measured between two possibly-not-normalized normal directions. if EdgeFlipTolerance is 0, only the sign of the returned value is valid
Definition at line 157 of file MeshRefinerBase.h.
References UE::Math::TVector< T >::Dot(), EdgeFlipTolerance, Normalized, and TMathUtilConstants< double >::ZeroTolerance.
DebugCheckUVSeamConstraints()
DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::DebugCheckUVSeamConstraints () protected
DebugCheckVertexConstraints()
DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::DebugCheckVertexConstraints () protected
DoDebugChecks()
virtual DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::DoDebugChecks (bool bEndOfPass = false) protected virtual
Referenced by UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::Reproject().
GetConstraints()
const TOptional< FMeshConstraints > & UE::Geometry::FMeshRefinerBase::GetConstraints () inline
Get the current mesh constraints.
Definition at line 112 of file MeshRefinerBase.h.
References Constraints.
GetEdgeFlipTolerance()
double UE::Geometry::FMeshRefinerBase::GetEdgeFlipTolerance () inline
Returns
edge flip tolerance
Definition at line 132 of file MeshRefinerBase.h.
References EdgeFlipTolerance.
GetMesh()
FDynamicMesh3 * UE::Geometry::FMeshRefinerBase::GetMesh () inline
Get the current mesh we are operating on.
Definition at line 109 of file MeshRefinerBase.h.
References Mesh.
Referenced by UE::Geometry::FSubRegionRemesher::AddEdgeToTriangleROI(), UE::Geometry::FSubRegionRemesher::AddVertexToTriangleROI(), UE::Geometry::FSubRegionRemesher::InitializeFromVertexROI(), UE::Geometry::FRestrictedSubRegionRemesher::OnEdgeFlip(), and UE::Geometry::FSubRegionRemesher::OnEdgeFlip().
GetVertexConstraint() [1/2]
FVertexConstraint UE::Geometry::FMeshRefinerBase::GetVertexConstraint (int VertexID) inline protected
Returns
constraint for given vertex
Definition at line 268 of file MeshRefinerBase.h.
References Constraints, and UE::Geometry::FVertexConstraint::Unconstrained().
GetVertexConstraint() [2/2]
bool UE::Geometry::FMeshRefinerBase::GetVertexConstraint (int VertexID, FVertexConstraint & OutConstraint) inline protected
Returns
true if vertex has constraint
Definition at line 280 of file MeshRefinerBase.h.
References Constraints.
IsVertexPositionConstrained()
bool UE::Geometry::FMeshRefinerBase::IsVertexPositionConstrained (int VertexID) inline protected
Returns
true if given vertex can't move, or has a projection target
Definition at line 255 of file MeshRefinerBase.h.
References UE::Geometry::FVertexConstraint::bCanMove, Constraints, and UE::Geometry::FVertexConstraint::Target.
operator=() [1/2]
FMeshRefinerBase & UE::Geometry::FMeshRefinerBase::operator= (const FMeshRefinerBase &) delete
References FMeshRefinerBase().
operator=() [2/2]
FMeshRefinerBase & UE::Geometry::FMeshRefinerBase::operator= (FMeshRefinerBase &&) delete
References FMeshRefinerBase().
ProjectionTarget()
IProjectionTarget * UE::Geometry::FMeshRefinerBase::ProjectionTarget () inline
Get the current Projection Target.
Definition at line 122 of file MeshRefinerBase.h.
RuntimeDebugCheck()
DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::RuntimeDebugCheck (int EdgeID) protected
SaveEdgeBeforeModify()
virtual DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::SaveEdgeBeforeModify (int32 EdgeID) protected virtual
SaveTriangleBeforeModify()
virtual DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::SaveTriangleBeforeModify (int32 TriangleID) protected virtual
SaveVertexTrianglesBeforeModify()
virtual DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::SaveVertexTrianglesBeforeModify (int32 VertexID) protected virtual
SetEdgeFlipTolerance()
void UE::Geometry::FMeshRefinerBase::SetEdgeFlipTolerance (double NewTolerance) inline
Set edge flip tolerance.
Value is clamped to range [-1,1]
Definition at line 135 of file MeshRefinerBase.h.
References UE::Geometry::VectorUtil::Clamp(), and EdgeFlipTolerance.
SetExternalConstraints()
void UE::Geometry::FMeshRefinerBase::SetExternalConstraints (TOptional< FMeshConstraints > ConstraintsIn) inline
Set external constraints.
Note that this object will be updated during computation.
Definition at line 118 of file MeshRefinerBase.h.
References Constraints, and MoveTemp().
SetMeshChangeTracker()
DYNAMICMESH_API void UE::Geometry::FMeshRefinerBase::SetMeshChangeTracker (FDynamicMeshChangeTracker * Tracker)
SetProjectionTarget()
void UE::Geometry::FMeshRefinerBase::SetProjectionTarget (IProjectionTarget * TargetIn) inline
Set a Projection Target.
Definition at line 125 of file MeshRefinerBase.h.
Field Documentation
ActiveChangeTracker
FDynamicMeshChangeTracker* UE::Geometry::FMeshRefinerBase::ActiveChangeTracker = nullptr protected
Definition at line 41 of file MeshRefinerBase.h.
AllowCollapseFixedVertsWithSameSetID
bool UE::Geometry::FMeshRefinerBase::AllowCollapseFixedVertsWithSameSetID = true
If true, then when two Fixed vertices have the same non-invalid SetID, we treat them as not fixed and allow collapse.
Definition at line 92 of file MeshRefinerBase.h.
Constraints
TOptional<FMeshConstraints> UE::Geometry::FMeshRefinerBase::Constraints protected
Constraints are used to control how certain edges and vertices can be modified.
Definition at line 36 of file MeshRefinerBase.h.
Referenced by GetConstraints(), GetVertexConstraint(), GetVertexConstraint(), IsVertexPositionConstrained(), and SetExternalConstraints().
DEBUG_CHECK_LEVEL
int UE::Geometry::FMeshRefinerBase::DEBUG_CHECK_LEVEL = 0
0 = no checking, 1 = check constraints each pass, 2 = and check validity each pass, 3 = and check validity after every mesh change (v slow but best for debugging)
Definition at line 98 of file MeshRefinerBase.h.
DebugEdges
TArray<int> UE::Geometry::FMeshRefinerBase::DebugEdges
This is a debugging aid, will break to debugger if these edges are touched, in debug builds.
Definition at line 72 of file MeshRefinerBase.h.
EdgeFlipTolerance
double UE::Geometry::FMeshRefinerBase::EdgeFlipTolerance = 0.0f protected
If normals dot product is less than this, we consider it a normal flip.
default = 0
Definition at line 152 of file MeshRefinerBase.h.
Referenced by ComputeEdgeFlipMetric(), GetEdgeFlipTolerance(), and SetEdgeFlipTolerance().
ENABLE_PROFILING
bool UE::Geometry::FMeshRefinerBase::ENABLE_PROFILING = false
Set to true to profile various passes.
Todo
re-enable this!
Definition at line 95 of file MeshRefinerBase.h.
Referenced by UE::Geometry::FRemesher::ProfileBeginPass(), UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::ProfileBeginPass(), UE::Geometry::FRemesher::ProfileEndPass(), and UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::ProfileEndPass().
Mesh
FDynamicMesh3* UE::Geometry::FMeshRefinerBase::Mesh = nullptr protected
Mesh that will be refined.
Definition at line 33 of file MeshRefinerBase.h.
Referenced by UE::Geometry::FSubRegionRemesher::FSubRegionRemesher(), UE::Geometry::FSubRegionRemesher::FullSmoothPass_Buffer(), GetMesh(), UE::Geometry::FSubRegionRemesher::InitializeFromTriangleROI(), UE::Geometry::FSubRegionRemesher::InitializeFromVertexROI(), UE::Geometry::FQueueRemesher::QueueOneRing(), UE::Geometry::FRemesher::StartEdges(), and UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::StartEdges().
Progress
FProgressCancel* UE::Geometry::FMeshRefinerBase::Progress = nullptr
Set this to be able to cancel running Remesher/Reducer.
Definition at line 69 of file MeshRefinerBase.h.
Referenced by Cancelled().
ProjectionMode
ETargetProjectionMode UE::Geometry::FMeshRefinerBase::ProjectionMode = ETargetProjectionMode::NoProjection
Method to use to project vertices onto target surface.
Default is no projection.
Definition at line 85 of file MeshRefinerBase.h.
Referenced by UE::Geometry::FRemesher::EnableInlineProjection(), UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::EnableInlineProjection(), UE::Geometry::FQueueRemesher::PopState(), UE::Geometry::FQueueRemesher::PushState(), and UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::Reproject().
ProjTarget
IProjectionTarget* UE::Geometry::FMeshRefinerBase::ProjTarget = nullptr protected
Vertices can be projected onto this surface when they are modified.
Definition at line 39 of file MeshRefinerBase.h.
Referenced by UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::GetProjectedPoint(), and UE::Geometry::TMeshSimplification< FAttrBasedQuadricErrord >::Reproject().
TinyTriangleThreshold
double UE::Geometry::FMeshRefinerBase::TinyTriangleThreshold = SMALL_NUMBER protected
Avoid creation of triangles smaller than this value.
We compare the triangle cross product's norm squared to this value since it's cheaper to compute than the triangle area. So the actual area threshold is sqrt(TinyTriangleThreshold)/2. Default is based on the threshold for creating triangles in a simulation mesh
Definition at line 188 of file MeshRefinerBase.h.
VertexControlF
TFunction<EVertexControl(int)> UE::Geometry::FMeshRefinerBase::VertexControlF = nullptr
This function allows client to specify fine-grained control over what happens to specific vertices.
Somewhat redundant w/ FVertexConstraints, but simpler to code and has the option to be dynamic during remesh pass.
Definition at line 66 of file MeshRefinerBase.h.
Referenced by UE::Geometry::FSubRegionRemesher::FSubRegionRemesher().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/MeshRefinerBase.h