Unreal Engine 5.6 C++ API: SRigVMGraphBreakLinksDialog Class Reference
SRigVMGraphBreakLinksDialog Class Reference
#include "SRigVMGraphBreakLinksWidget.h"
Public Member Functions
EAppReturnType::Type ShowModal ()
SLATE_ARGUMENT (TArray< URigVMLink * >, Links) SLATE_ARGUMENT(FRigVMOnFocusOnLinkRequestedDelegate
SLATE_BEGIN_ARGS (SRigVMGraphBreakLinksDialog)
OnFocusOnLink SLATE_END_ARGS () void Construct(const FArguments &InArgs)
Public Member Functions inherited from SWindow
Style bDragAnywhere SLATE_ARGUMENT(EAutoCenter, AutoCenter) SLATE_ARGUMENT(UE ~SWindow ()
The windows auto-centering mode.
bool AcceptsInput () const
EWindowActivationPolicy ActivationPolicy () const
void AddChildWindow (const TSharedRef< SWindow > &ChildWindow)
Add ChildWindow as this window's child.
SOverlay::FScopedWidgetSlotArguments AddOverlaySlot (const int32 ZOrder=INDEX_NONE)
Adds content to draw on top of the entire window.
FScopedWidgetSlotArguments AddPopupLayerSlot ()
Return a new slot in the popup layer.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const override
virtual bool Advanced_IsInvalidationRoot () const override
virtual bool Advanced_IsWindow () const override
Is this widget derivative of SWindow.
bool AppearsInTaskbar () const
void BeginFullWindowOverlayTransition ()
Begins a transition from showing regular window content to overlay content During the transition we show both sets of content.
void BringToFront (bool bForce=false)
Bring the window to the front.
void Construct (const FArguments &InArgs)
void DestroyWindowImmediately ()
Warning: use Request Destroy Window whenever possible!
void DrawAttention (const FWindowDrawAttentionParameters &Parameters)
Attempts to draw the user's attention to this window in whatever way is appropriate for the platform if this window is not the current active.
void EnableWindow (bool bEnable)
Enables or disables this window and all of its children.
void EndFullWindowOverlayTransition ()
Ends a transition from showing regular window content to overlay content When this is called content occluded by the full window overlay(if there is one) will be physically hidden.
void FlashWindow ()
Flashed the window, used for drawing attention to modal dialogs.
TArray< TSharedRef< SWindow > > & GetChildWindows ()
const TArray< TSharedRef< SWindow > > & GetChildWindows () const
FSlateRect GetClientRectInScreen () const
UE::Slate::FDeprecateVector2DResult GetClientSizeInScreen () const
FSlateRect GetClippingRectangleInWindow () const
TSharedRef< SWidget > GetContent ()
Gets the widget content for this window.
int32 GetCornerRadius ()
EWindowZone::Type GetCurrentWindowZone (UE::Slate::FDeprecateVector2DParameter LocalMousePosition)
Gets the current Window Zone that mouse position is over.
UE::Slate::FDeprecateVector2DResult GetDesiredSizeDesktopPixels () const
float GetDPIScaleFactor () const
Returns the DPI scale factor of the native window.
int32 GetExpectedMaxHeight () const
int32 GetExpectedMaxWidth () const
FSlateRect GetFullScreenInfo () const
Returns the rectangle of the screen the window is associated with.
FHittestGrid & GetHittestGrid ()
Access the hittest acceleration data structure for this window.
UE::Slate::FDeprecateVector2DResult GetInitialDesiredPositionInScreen () const
UE::Slate::FDeprecateVector2DResult GetInitialDesiredSizeInScreen () const
bool GetIsHDR () const
FSlateLayoutTransform GetLocalToScreenTransform () const
FSlateLayoutTransform GetLocalToWindowTransform () const
UE::Slate::FDeprecateVector2DResult GetMorphTargetPosition () const
FSlateRect GetMorphTargetShape () const
TSharedPtr< FGenericWindow > GetNativeWindow ()
TSharedPtr< const FGenericWindow > GetNativeWindow () const
FSlateRect GetNonMaximizedRectInScreen () const
FMargin GetNonMaximizedWindowBorderSize () const
Returns the margins used for the window border if it's not maximized.
FOnWindowActivatedEvent & GetOnWindowActivatedEvent ()
Gets the multicast delegate executed when the window is activated.
FOnWindowClosedEvent & GetOnWindowClosedEvent ()
Gets the multicast delegate to execute right before the window is closed.
FOnWindowDeactivatedEvent & GetOnWindowDeactivatedEvent ()
Gets the multicast delegate executed when the window is deactivated.
float GetOpacity () const
TSharedPtr< SWindow > GetParentWindow () const
UE::Slate::FDeprecateVector2DResult GetPositionInScreen () const
FSlateRect GetRectInScreen () const
UE::Slate::FDeprecateVector2DResult GetSizeInScreen () const
FWindowSizeLimits GetSizeLimits () const
Optional constraints on min and max sizes that this window can be.
FText GetTitle () const
Grabs the current window title.
TSharedPtr< IWindowTitleBar > GetTitleBar () const
FOptionalSize GetTitleBarSize () const
Returns the size of the title bar as a Slate size parameter.
TSharedPtr< SWindow > GetTopmostAncestor ()
Look up the parent chain until we find the top-level window that owns this window.
EWindowTransparency GetTransparencySupport () const
EWindowType GetType () const
Grabs the window type.
TSharedPtr< ISlateViewport > GetViewport ()
float GetViewportScaleUIOverride () const
UE::Slate::FDeprecateVector2DResult GetViewportSize () const
Returns the viewport size, taking into consideration if the window size should drive the viewport size.
TWeakPtr< SWidget > GetWidgetFocusedOnDeactivate ()
Returns widget last focused on deactivate.
FMargin GetWindowBorderSize (bool bIncTitleBar=false) const
Returns the margins used for the window border.
TAttribute< FText > GetWindowCloseButtonToolTipText () const
Return the tooltip text that should be used for the window's Close button.
FGeometry GetWindowGeometryInScreen () const
Get the Geometry that describes this window.
FGeometry GetWindowGeometryInWindow () const
EWindowMode::Type GetWindowMode () const
UE::Slate::FDeprecateVector2DResult GetWindowSizeFromClientSize (UE::Slate::FDeprecateVector2DParameter InClientSize, TOptional< float > DPIScale=TOptional< float >())
For a given client size, calculate the window size required to accommodate any potential non-OS borders and title bars.
EVisibility GetWindowVisibility () const
Windows that are not hittestable should not show up in the hittest grid.
void HACK_ForceToFront ()
@hack Force a window to front even if a different application is in front.
bool HasActiveChildren () const
Are any of our child windows active?
bool HasActiveParent () const
Are any of our parent windows active?
bool HasCloseBox () const
bool HasFullWindowOverlayContent () const
Checks to see if there is content assigned as a full window overlay.
bool HasMaximizeBox () const
bool HasMinimizeBox () const
bool HasOSWindowBorder () const
bool HasOverlay () const
Check whether we have a full window overlay, used to draw content over the entire window.
bool HasSizingFrame () const
void HideWindow ()
Make the window invisible.
void InitialMaximize ()
Maximize the window if bInitiallyMaximized is set.
void InitialMinimize ()
Maximize the window if bInitiallyMinimized is set.
bool IsActive () const
Is this window active?
bool IsAutosized () const
bool IsDescendantOf (const TSharedPtr< SWindow > &ParentWindow) const
Returns whether or not this window is a descendant of the specfied parent window.
bool IsDrawingEnabled () const
bool IsFocusedInitially () const
bool IsManualManageDPIChanges () const
bool IsMirrorWindow ()
bool IsModalWindow ()
bool IsMorphing () const
bool IsMorphingSize () const
bool IsRegularWindow () const
bool IsScreenspaceMouseWithin (UE::Slate::FDeprecateVector2DParameter ScreenspaceMouseCoordinate) const
bool IsTopmostWindow () const
bool IsUserSized () const
bool IsViewportSizeDrivenByWindow () const
Returns whether or not the viewport and window size should be linked together.
bool IsVirtualWindow () const
bool IsVisible () const
bool IsWindowMaximized () const
bool IsWindowMinimized () const
void Maximize ()
Windows functions.
void Minimize ()
void MorphToPosition (const FCurveSequence &Sequence, const float TargetOpacity, const UE::Slate::FDeprecateVector2DParameter &TargetPosition)
Animate the window to TargetOpacity and TargetPosition over a short period of time.
void MorphToShape (const FCurveSequence &Sequence, const float TargetOpacity, const FSlateRect &TargetShape)
Animate the window to TargetOpacity and TargetShape over a short period of time.
void MoveWindowTo (UE::Slate::FDeprecateVector2DParameter NewPosition)
Relocate the window to a screenspace position specified by NewPosition.
void NotifyWindowBeingDestroyed ()
Calls the OnWindowClosed delegate when this window is about to be closed.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual bool OnIsActiveChanged (const FWindowActivateEvent &ActivateEvent)
The system will call this method to notify the window that it has been places in the foreground or background.
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent) override
Visualize a new pop-up if possible.
int32 PaintWindow (double CurrentTime, float DeltaTime, FSlateWindowElementList &OutDrawElements, const FWidgetStyle &InWidgetStyle, bool bParentEnabled)
Paint the window and all of its contents.
void ProcessWindowInvalidation ()
Process the invalidation of the widget contained by the window in GlobalInvalidation.
bool RemoveDescendantWindow (const TSharedRef< SWindow > &DescendantToRemove)
Remove DescendantToRemove from this window's children or their children.
bool RemoveOverlaySlot (const TSharedRef< SWidget > &InContent)
Removes a widget that is being drawn over the entire window.
void RemovePopupLayerSlot (const TSharedRef< SWidget > &WidgetToRemove)
Counterpart to AddPopupLayerSlot.
void RequestDestroyWindow ()
Request that this window be destroyed.
void ResetViewportScaleUIOverride ()
void ReshapeWindow (const FSlateRect &InNewShape)
void ReshapeWindow (UE::Slate::FDeprecateVector2DParameter NewPosition, UE::Slate::FDeprecateVector2DParameter NewSize)
Relocate the window to a screenspace position specified by NewPosition and resize it to NewSize.
void Resize (UE::Slate::FDeprecateVector2DParameter NewClientSize)
Resize the window to be dpi scaled NewClientSize immediately.
void Restore ()
void SetAllowFastUpdate (bool bInAllowFastUpdate)
void SetAsModalWindow ()
Set modal window related flags - called by Slate app code during FSlateApplication::AddModalWindow()
void SetCachedScreenPosition (UE::Slate::FDeprecateVector2DParameter NewPosition)
Sets the actual screen position of the window.
void SetCachedSize (UE::Slate::FDeprecateVector2DParameter NewSize)
Sets the actual size of the window.
void SetContent (TSharedRef< SWidget > InContent)
Sets the widget content for this window.
void SetDPIScaleFactor (const float Factor)
Overrides the DPI scale factor of the native window.
void SetFullWindowOverlayContent (TSharedPtr< SWidget > InContent)
Sets a widget to use as a full window overlay, or clears an existing widget if set.
void SetIndependentViewportSize (const UE::Slate::FDeprecateVector2DParameter &VP)
Sets the viewport size independently of the window size, if non-zero.
void SetIsHDR (bool bHDR)
void SetManualManageDPIChanges (const bool bManualDPI)
Will inform the native window that we need to handle any DPI changes from within the application.
void SetMirrorWindow (bool bSetMirrorWindow)
Set mirror window flag.
void SetNativeWindow (TSharedRef< FGenericWindow > InNativeWindow)
Sets the native OS window associated with this SWindow.
void SetNativeWindowButtonsVisibility (bool bVisible)
Shows or hides native window buttons on platforms that use them.
void SetOnWindowClosed (const FOnWindowClosed &InDelegate)
Sets the delegate to execute right before the window is closed.
void SetOnWindowMoved (const FOnWindowMoved &InDelegate)
Sets the delegate to execute right after the window has been moved.
void SetOnWorldSwitchHack (FOnSwitchWorldHack &InOnWorldSwitchHack)
Sets the delegate to call when switching worlds in before ticking,drawing, or sending messages to widgets in this window.
void SetOpacity (const float InOpacity)
Sets the opacity of this window.
void SetRequestDestroyWindowOverride (const FRequestDestroyWindowOverride &InDelegate)
Sets the delegate to override RequestDestroyWindow.
void SetSizeLimits (const FWindowSizeLimits &InSizeLimits)
Set optional constraints on min and max sizes that this window can be.
void SetSizingRule (ESizingRule InSizingRule)
Should this window automatically derive its size based on its content or be user-drive?
void SetTitle (const FText &InTitle)
Sets the current window title.
void SetTitleBar (const TSharedPtr< IWindowTitleBar > InTitleBar)
void SetViewport (TSharedRef< ISlateViewport > ViewportRef)
void SetViewportScaleUIOverride (float InViewportScaleUIOverride)
void SetViewportSizeDrivenByWindow (bool bDrivenByWindow)
Sets whether or not the viewport size should be driven by the window's size.
void SetWidgetToFocusOnActivate (TSharedPtr< SWidget > InWidget)
Sets a widget that should become focused when this window is next activated.
void SetWindowMode (EWindowMode::Type WindowMode)
Toggle window between window modes (fullscreen, windowed, etc)
bool ShouldPreserveAspectRatio () const
void ShowWindow ()
Make the window visible.
bool SizeWillChangeOften () const
SLATE_ARGUMENT (EWindowType, Type) SLATE_STYLE_ARGUMENT(FWindowStyle
Type of this window.
Style SLATE_ATTRIBUTE (FText, Title) SLATE_ARGUMENT(bool
Title of the window.
SLATE_BEGIN_ARGS (SWindow)
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
int32 SwitchWorlds (int32 WorldId) const
Hack to switch worlds.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
virtual FString ToString () const override
void UnsetViewport (TSharedRef< ISlateViewport > ViewportRef)
void UpdateMorphTargetPosition (const UE::Slate::FDeprecateVector2DParameter &TargetPosition)
Set a new morph position and force the morph to run for at least one frame in order to reach that target.
void UpdateMorphTargetShape (const FSlateRect &TargetShape)
Set a new morph shape and force the morph to run for at least one frame in order to reach that target.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FSlateInvalidationRoot
FSlateInvalidationRoot ()
virtual ~FSlateInvalidationRoot ()
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void Advanced_ResetInvalidation (bool bClearResourcesImmediately)
FSlateCachedElementData & GetCachedElements ()
const FSlateCachedElementData & GetCachedElements () const
const FSlateInvalidationWidgetList & GetFastPathWidgetList () const
const TSharedPtr< SWidget > GetFastPathWidgetListRoot () const
FHittestGrid * GetHittestGrid () const
FSlateInvalidationRootHandle GetInvalidationRootHandle () const
const SWidget * GetInvalidationRootWidget () const
ESlateInvalidationPaintType GetLastPaintType () const
FPerformanceStat GetPerformanceStat () const
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
void InvalidateRootChildOrder (const SWidget *Investigator=nullptr)
Rebuild the list and request a SlowPath.
void InvalidateRootLayout (const SWidget *Investigator=nullptr)
Invalidate the layout, forcing the parent of the InvalidationRoot to be repainted.
void InvalidateScreenPosition (const SWidget *Investigator=nullptr)
Update the screen position of the SWidget owning the InvalidationRoot.
bool NeedsSlowPath () const
void OnWidgetDestroyed (const SWidget *Widget)
FSlateInvalidationResult PaintInvalidationRoot (const FSlateInvalidationContext &Context)
void SetLastPaintType (ESlateInvalidationPaintType Value)
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Protected Member Functions
bool IsOkButtonEnabled () const
FReply OnButtonClick (EAppReturnType::Type ButtonID)
Protected Member Functions inherited from SWindow
void ConstructWindowInternals ()
virtual bool CustomPrepass (float LayoutScaleMultiplier) override
virtual TSharedRef< SWidget > GetRootWidget () override
virtual EHorizontalAlignment GetTitleAlignment ()
Returns the alignment type for the titlebar's title text.
virtual TSharedRef< SWidget > MakeWindowTitleBar (const TSharedRef< SWindow > &Window, const TSharedPtr< SWidget > &CenterContent, EHorizontalAlignment CenterContentAlignment)
Returns swindow title bar widgets.
virtual int32 PaintSlowPath (const FSlateInvalidationContext &InvalidationContext) override
void SetWindowBackground (const FSlateBrush *InWindowBackground)
void StartMorph ()
Kick off a morph to whatever the target shape happens to be.
EActiveTimerReturnType TriggerPlayMorphSequence (double InCurrentTime, float InDeltaTime)
One-off active timer to trigger a the morph sequence to play.
void UpdateWindowContentVisibility ()
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from FSlateInvalidationRoot
void ClearAllFastPathData (bool bClearResourcesImmediately)
int32 GetCachedMaxLayerId () const
virtual void OnRootInvalidated ()
bool ProcessInvalidation ()
void SetInvalidationRootHittestGrid (FHittestGrid &InHittestGrid)
void SetInvalidationRootWidget (SWidget &InInvalidationRootWidget)
void SetNeedsSlowPath (bool InNeedsSlowPath)
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Protected Attributes
TSharedPtr< SRigVMGraphBreakLinksWidget > BreakLinksWidget
EAppReturnType::Type UserResponse
Protected Attributes inherited from SWindow
EAutoCenter AutoCenterRule
How to auto center the window.
bool bAllowFastUpdate: 1
True if this window allows global invalidation of its contents.
bool bCreateTitleBar: 1
True if this window has a title bar.
bool bDragAnywhere
When true, grabbing anywhere on the window will allow it to be dragged.
bool bFocusWhenFirstShown: 1
Focus this window immediately as it is shown.
bool bHasCloseButton: 1
True if this window displays an enabled close button on the toolbar area.
bool bHasEverBeenShown: 1
True if this window has been shown yet.
bool bHasMaximizeButton: 1
True if this window displays an enabled maximize button on the toolbar area.
bool bHasMinimizeButton: 1
True if this window displays an enabled minimize button on the toolbar area.
bool bHasOSWindowBorder: 1
True if this window displays the os window border instead of drawing one in slate.
bool bHasSizingFrame: 1
True if this window displays thick edge that can be used to resize the window.
bool bInitiallyMaximized: 1
true if this window is maximized when its created
bool bInitiallyMinimized: 1
true if this window is minimized when its created
bool bIsDrawingEnabled
bool bIsHDR: 1
True if the window is being displayed on a HDR capable monitor.
bool bIsMirrorWindow: 1
True if the window is a mirror window for HMD content.
bool bIsModalWindow: 1
True if the window is modal.
bool bIsPopupWindow: 1
True if this is a pop up window.
bool bIsTopmostWindow: 1
True if this is a topmost window.
bool bManualManageDPI: 1
bool bShouldPreserveAspectRatio: 1
True if the window should preserve its aspect ratio when resized by user.
bool bShouldShowWindowContentDuringOverlay
Whether or not we should show content of the window which could be occluded by full screen window content.
bool bSizeWillChangeOften: 1
True if we expect the size of this window to change often, such as if its animated, or if it recycled for tool-tips, and we'd like to avoid costly GPU buffer resizes when that happens.
bool bVirtualWindow: 1
True if this window is virtual and not directly rendered by slate application or the OS.
TArray< TSharedRef< SWindow > > ChildWindows
Child windows of this window.
TAttribute< FText > CloseButtonToolTipText
Tooltip text displayed over the window's Close button (on Windows only).
SVerticalBox::FSlot * ContentSlot
int32 ExpectedMaxHeight
The expected maximum height of the window.
int32 ExpectedMaxWidth
The expected maximum width of the window.
int32 FocusUserIndex
The index of the user that should focus this window on activation.
TSharedPtr< SWidget > FullWindowOverlayWidget
Full window overlay widget.
TUniquePtr< FHittestGrid > HittestGrid
Each window has its own hittest grid for accelerated widget picking.
UE::Slate::FDeprecateVector2DResult InitialDesiredScreenPosition
Initial desired position of the window's content in screen space.
UE::Slate::FDeprecateVector2DResult InitialDesiredSize
Initial desired size of the window's content in screen space.
FMargin LayoutBorder
struct SWindow::FMorpher Morpher
TSharedPtr< FGenericWindow > NativeWindow
The native window that is backing this Slate Window.
FOnWindowActivated OnWindowActivated
Invoked when the window has been activated.
FOnWindowClosed OnWindowClosed
Invoked when the window is about to be closed.
FOnWindowDeactivated OnWindowDeactivated
Invoked when the window has been deactivated.
FOnWindowMoved OnWindowMoved
Invoked when the window is moved.
FOnSwitchWorldHack OnWorldSwitchHack
World switch delegate.
float Opacity
Current opacity of the window.
TWeakPtr< SWindow > ParentWindowPtr
When not null, this window will always appear on top of the parent and be closed when the parent is closed.
TSharedPtr< class SPopupLayer > PopupLayer
This layer provides mechanism for tooltips, drag-drop decorators, and popups without creating a new window.
UE::Slate::FDeprecateVector2DResult PreFullscreenPosition
The position of the window before entering fullscreen.
FRequestDestroyWindowOverride RequestDestroyWindowOverride
Invoked when the window is requested to be destroyed.
UE::Slate::FDeprecateVector2DResult ScreenPosition
Position of the window's content in screen space.
UE::Slate::FDeprecateVector2DResult Size
Size of the window's content area in screen space.
FWindowSizeLimits SizeLimits
Min and Max values for Width and Height; all optional.
ESizingRule SizingRule
How to size the window.
TAttribute< FText > Title
Title of the window, displayed in the title bar as well as potentially in the task bar (Windows platform)
TSharedPtr< SWidget > TitleArea
TSharedPtr< IWindowTitleBar > TitleBar
float TitleBarSize
Size of this window's title bar.
EWindowTransparency TransparencySupport
Transparency setting for this window.
EWindowType Type
Type of the window.
FMargin UserResizeBorder
TWeakPtr< ISlateViewport > Viewport
Pointer to the viewport registered with this window if any.
float ViewportScaleUIOverride
Mix of aspect ratio + DPI + UI Zoom.
UE::Slate::FDeprecateVector2DResult ViewportSize
Size of the viewport.
TWeakPtr< SWidget > WidgetFocusedOnDeactivate
Widget that had keyboard focus when this window was last de-activated, if any.
TWeakPtr< SWidget > WidgetToFocusOnActivate
Widget to transfer keyboard focus to when this window becomes active, if any.
FOnWindowActivatedEvent WindowActivatedEvent
EWindowActivationPolicy WindowActivationPolicy
When should the window be activated upon being shown.
FOnWindowClosedEvent WindowClosedEvent
FOnWindowDeactivatedEvent WindowDeactivatedEvent
TSharedPtr< SOverlay > WindowOverlay
Window overlay widget.
EWindowZone::Type WindowZone
Cached "zone" the cursor was over in the window the last time that someone called GetCurrentWindowZone()
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Public Types inherited from SWindow
using FScopedWidgetSlotArguments = TPanelChildren<FPopupLayerSlot>::FScopedWidgetSlotArguments
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from SWindow
static UE::Slate::FDeprecateVector2DResult ComputeWindowSizeForContent (UE::Slate::FDeprecateVector2DParameter ContentSize)
static TSharedRef< SWindow > MakeCursorDecorator ()
Make cursor decorator window.
static TSharedRef< SWindow > MakeNotificationWindow ()
Make a notification window.
static TSharedRef< SWindow > MakeStyledCursorDecorator (const FWindowStyle &InStyle)
Make cursor decorator window with a non-default style.
static TSharedRef< SWindow > MakeToolTipWindow ()
Make a tool tip window.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Data Fields inherited from SWindow
FSlateRect MoveResizeRect
UE::Slate::FDeprecateVector2DResult MoveResizeStart
EWindowZone::Type MoveResizeZone
Used to store the zone where the mouse down event occurred during move / drag.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 39 of file SRigVMGraphBreakLinksWidget.h.
Member Function Documentation
IsOkButtonEnabled()
bool SRigVMGraphBreakLinksDialog::IsOkButtonEnabled () const protected
References IsOkButtonEnabled().
Referenced by IsOkButtonEnabled().
OnButtonClick()
FReply SRigVMGraphBreakLinksDialog::OnButtonClick (EAppReturnType::Type ButtonID) protected
References OnButtonClick(), and SWindow::Type.
Referenced by OnButtonClick().
ShowModal()
EAppReturnType::Type SRigVMGraphBreakLinksDialog::ShowModal ()
References ShowModal(), and SWindow::Type.
Referenced by ShowModal().
SLATE_ARGUMENT()
SRigVMGraphBreakLinksDialog::SLATE_ARGUMENT (TArray< URigVMLink * > , Links)
SLATE_BEGIN_ARGS()
SRigVMGraphBreakLinksDialog::SLATE_BEGIN_ARGS (SRigVMGraphBreakLinksDialog) inline
Definition at line 43 of file SRigVMGraphBreakLinksWidget.h.
SLATE_END_ARGS()
OnFocusOnLink SRigVMGraphBreakLinksDialog::SLATE_END_ARGS () const &
References SWindow::Construct(), and SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Field Documentation
BreakLinksWidget
TSharedPtr<SRigVMGraphBreakLinksWidget> SRigVMGraphBreakLinksDialog::BreakLinksWidget protected
Definition at line 57 of file SRigVMGraphBreakLinksWidget.h.
UserResponse
EAppReturnType::Type SRigVMGraphBreakLinksDialog::UserResponse protected
Definition at line 61 of file SRigVMGraphBreakLinksWidget.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Widgets/SRigVMGraphBreakLinksWidget.h