Unreal Engine 5.6 C++ API: FRenderResource Class Reference
FRenderResource Class Reference
A rendering resource which is owned by the rendering thread.
#include "RenderResource.h"
Public Types
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
virtual void ReleaseRHI ()
Releases the RHI resources used by this resource.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Static Private Member Functions
static RENDERCORE_API FBufferRHIRef CreateRHIBufferInternal (FRHICommandListBase &RHICmdList, const TCHAR *InDebugName, const FName &InOwnerName, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, FResourceArrayInterface *ResourceArray, bool bWithoutNativeResource)
static RENDERCORE_API bool ShouldFreeResourceObject (void *ResourceObject, FResourceArrayInterface *ResourceArray)
Private Attributes
TEnumAsByte< ERHIFeatureLevel::Type > FeatureLevel
EInitPhase InitPhase = EInitPhase::Default
int32 ListIndex
Detailed Description
A rendering resource which is owned by the rendering thread.
Definition at line 36 of file RenderResource.h.
Member Enumeration Documentation
EInitPhase
enum class FRenderResource::EInitPhase : uint8 strong
Controls initialization order of render resources.
Early engine resources utilize the 'Pre' phase to avoid static init ordering issues.
Enumerator
Pre
Default
MAX
Definition at line 42 of file RenderResource.h.
Constructor & Destructor Documentation
FRenderResource() [1/4]
RENDERCORE_API FRenderResource::FRenderResource ()
Default constructor.
Referenced by FRenderResource(), FRenderResource(), FVertexFactory::FVertexFactory(), FSlateTexture2DRHIRef::GetRenderResource(), operator=(), and operator=().
FRenderResource() [2/4]
RENDERCORE_API FRenderResource::FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
FRenderResource() [3/4]
RENDERCORE_API FRenderResource::FRenderResource (const FRenderResource &)
Misc copy/assignment.
References FRenderResource().
FRenderResource() [4/4]
RENDERCORE_API FRenderResource::FRenderResource (FRenderResource &&)
References FRenderResource().
~FRenderResource()
virtual RENDERCORE_API FRenderResource::~FRenderResource () virtual
Destructor used to catch unreleased resources.
Member Function Documentation
ChangeFeatureLevel()
RENDERCORE_API void FRenderResource::ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel) static
Reinitializes render resources at a new feature level.
CreateRHIBuffer()
template<typename T> FBufferRHIRef FRenderResource::CreateRHIBuffer (FRHICommandListBase & RHICmdList, T & InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR * InDebugName) inline protected
Definition at line 157 of file RenderResource.h.
References Buffer, CreateRHIBufferInternal(), GetOwnerName(), RESTRICT, and ShouldFreeResourceObject().
CreateRHIBufferInternal()
RENDERCORE_API FBufferRHIRef FRenderResource::CreateRHIBufferInternal (FRHICommandListBase & RHICmdList, const TCHAR * InDebugName, const FName & InOwnerName, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, FResourceArrayInterface * ResourceArray, bool bWithoutNativeResource) static private
Referenced by CreateRHIBuffer().
GetFeatureLevel()
const FStaticFeatureLevel FRenderResource::GetFeatureLevel () const inline protected
Definition at line 152 of file RenderResource.h.
References FeatureLevel.
Referenced by FParticleVertexFactoryBase::GetFeatureLevel().
GetFriendlyName()
virtual FString FRenderResource::GetFriendlyName () const inline virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented in FColorVertexBuffer, FDummyViewport, FDuplicatedVerticesBuffer, FHairCardsDeformedResource, FHairCardsInterpolationResource, FHairCardsRestResource, FHairMeshesDeformedResource, FHairMeshesRestResource, FHairStrandsClusterResource, FHairStrandsCullingResource, FHairStrandsDeformedResource, FHairStrandsInterpolationResource, FHairStrandsLODDeformedRootResource, FHairStrandsLODRestRootResource, FHairStrandsRestResource, FIndexBuffer, FNDIGeometryCollectionBuffer, FNDIHairStrandsBuffer, FNDIVelocityGridBuffer, FPlanarReflectionRenderTarget, FPositionVertexBuffer, FSceneViewport, FShaderMapResource_InlineCode, FSkeletalMeshAttributeVertexBuffer, FSkeletalMeshVertexClothBuffer, FSkinWeightDataVertexBuffer, FSkinWeightLookupVertexBuffer, FStaticMeshInstanceBuffer::FInstanceCustomDataBuffer, FStaticMeshInstanceBuffer::FInstanceLightmapBuffer, FStaticMeshInstanceBuffer::FInstanceOriginBuffer, FStaticMeshInstanceBuffer::FInstanceTransformBuffer, FStaticMeshInstanceBuffer, FStaticMeshSectionAreaWeightedTriangleSamplerBuffer, FStaticMeshVertexBuffer::FTangentsVertexBuffer, FStaticMeshVertexBuffer::FTexcoordVertexBuffer, FStaticMeshVertexBuffer, FTexture, FTextureReference, FVertexBuffer, UE::ChaosDeformable::FFloatArrayBufferWithSRV, UE::ChaosDeformable::FHalfArrayBufferWithSRV, and UE::ChaosDeformable::FIndexArrayBufferWithSRV.
Definition at line 108 of file RenderResource.h.
References TEXT.
GetImmediateCommandList()
RENDERCORE_API FRHICommandListBase & FRenderResource::GetImmediateCommandList () static protected
Referenced by FIdentityPrimitiveUniformBuffer::InitContents(), TGlobalResource< FGlobalBoundShaderStateResource >::InitGlobalResource(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::UE_DEPRECATED(), and TUniformBuffer< FLightmapResourceClusterShaderParameters >::UE_DEPRECATED().
GetInitPhase()
EInitPhase FRenderResource::GetInitPhase () const inline
Definition at line 114 of file RenderResource.h.
References InitPhase.
GetListIndex()
int32 FRenderResource::GetListIndex () const inline
Definition at line 113 of file RenderResource.h.
References ListIndex.
GetOwnerName()
FName FRenderResource::GetOwnerName () const inline
Definition at line 124 of file RenderResource.h.
Referenced by FRawStaticIndexBuffer16or32< INDEX_TYPE >::CreateRHIBuffer(), CreateRHIBuffer(), and FDuplicatedVerticesBuffer::InitRHI().
GetResourceName()
FName FRenderResource::GetResourceName () const inline
Definition at line 140 of file RenderResource.h.
HasValidFeatureLevel()
FORCEINLINE bool FRenderResource::HasValidFeatureLevel () const inline protected
Definition at line 153 of file RenderResource.h.
References FeatureLevel, and FORCEINLINE.
Referenced by FParticleVertexFactoryBase::GetFeatureLevel().
InitPreRHIResources()
RENDERCORE_API void FRenderResource::InitPreRHIResources () static
Initialize all resources initialized before the RHI was initialized.
InitResource()
virtual RENDERCORE_API void FRenderResource::InitResource (FRHICommandListBase & RHICmdList) virtual
Initializes the resource.
This is only called by the rendering thread.
Reimplemented in FCanvasTileRendererItem::FTileVertexFactory, FCanvasTriangleRendererItem::FTriangleVertexFactory, FHairCardsRestResource, FHairMeshesRestResource, FStaticMeshInstanceBuffer, and FStaticMeshVertexBuffer.
Referenced by FLandscapeVertexBuffer::FLandscapeVertexBuffer(), FMeshRenderBufferSet::InitOrUpdateResource(), and FMeshRenderBufferSet::UpdateRaytracingGeometryIfEnabled().
InitRHI()
virtual void FRenderResource::InitRHI (FRHICommandListBase & RHICmdList) inline virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented in FClearVertexBuffer, FColorVertexBuffer, FCubeIndexBuffer, FDefaultLightmapResourceClusterUniformBuffer, FDummyViewport, FDuplicatedVerticesBuffer, FDynamicMeshIndexBuffer16, FDynamicMeshIndexBuffer32, FEmptyVertexDeclaration, FFilterVertexDeclaration, FGeometryCacheVertexVertexFactory, FGeometryCollectionVertexFactory, FGlobalDynamicReadBuffer, FGPUBaseSkinVertexFactory, FGPUSkinPassthroughVertexFactory, FHairCardIndexBuffer, FHairCardsVertexBuffer, FHairCardsVertexFactory, FHairCommonResource, FHairStrandsVertexFactory, FInstancedStaticMeshVertexFactory, FLandscapeVertexBuffer, FLandscapeVertexFactory, FLightmapResourceCluster, FLocalVertexFactory, FMaterialRenderProxy, FMediaVertexDeclaration, FMeshParticleVertexFactory, FMorphTargetVertexInfoBuffers, FNaniteVertexFactory, FNDIGeometryCollectionBuffer, FNDIHairStrandsBuffer, FNDIVelocityGridBuffer, FNullColorVertexBuffer, FNullDynamicParameterVertexBuffer, FNullVertexBuffer, FParticleBeamTrailVertexFactory, FParticleEightTexCoordVertexBuffer, FParticleIndexBuffer, FParticleScratchVertexBuffer, FParticleSortBuffers, FParticleSpriteVertexFactory, FParticleTexCoordVertexBuffer, FPhysicsFieldResource, FPlanarReflectionRenderTarget, FPositionVertexBuffer, FPrecomputedVolumetricLightmapData, FPrimitiveIdDummyBuffer, FRawIndexBuffer16or32, FRawIndexBuffer, FRawStaticIndexBuffer16or32< INDEX_TYPE >, FRawStaticIndexBuffer, FRDGWrapperVertexBuffer, FSceneViewport, FScreenRectangleIndexBuffer, FScreenRectangleVertexBuffer, FScreenSpaceVertexBuffer, FScreenVertexDeclaration, FSharedSamplerState, FSimpleElementVertexDeclaration, FSinglePrimitiveStructured, FSixTriangleParticleIndexBuffer, FSkeletalMeshAttributeVertexBuffer, FSkeletalMeshHalfEdgeBuffer, FSkeletalMeshVertexClothBuffer, FSkinWeightDataVertexBuffer, FSkinWeightLookupVertexBuffer, FSkyTextureCubeResource, FSlateRenderTargetRHI, FSlateTexture2DRHIRef, FSlateTextureRenderTarget2DResource, FStaticMeshInstanceBuffer, FStaticMeshSectionAreaWeightedTriangleSamplerBuffer, FStaticMeshVertexBuffer, FStaticShadowDepthMap, FStreamableTextureResource, FSubUVBoundingGeometryBuffer, FTexture2DDynamicResource, FTexture2DResource, FTextureCollectionResource, FTextureReference, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetVolumeResource, FTileVertexDeclaration, FTwoTrianglesIndexBuffer, FViewport, FVirtualTexture2DResource, FWaterMeshIndexBuffer, FWaterMeshVertexBuffer, Nanite::FStreamingManager, Nanite::FVertexFactoryResource, TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >, TGPUSkinVertexFactory< BoneInfluenceType >, TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FBoneBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FClothBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, TStaticStateRHI< InitializerType, RHIRefType, RHIParamRefType >::FStaticStateResource, TUniformBuffer< TBufferStruct >, TUniformBuffer< FLandscapeUniformShaderParameters >, TUniformBuffer< FLightmapResourceClusterShaderParameters >, TUniformBuffer< FPrimitiveUniformShaderParameters >, TWaterVertexFactory< bWithWaterSelectionSupport, DrawMode >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::Indirect >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::IndirectInstancedStereo >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::NonIndirect >, UE::ChaosDeformable::FFloatArrayBufferWithSRV, UE::ChaosDeformable::FHalfArrayBufferWithSRV, UE::ChaosDeformable::FIndexArrayBufferWithSRV, and UE::SVT::FTextureRenderResources.
Definition at line 80 of file RenderResource.h.
IsInitialized()
FORCEINLINE bool FRenderResource::IsInitialized () const inline
Definition at line 111 of file RenderResource.h.
References FORCEINLINE, INDEX_NONE, and ListIndex.
Referenced by TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::CreatePooledResource(), FLocalVertexFactory::GetColorOverrideStream(), FStreamableTextureResource::GetPostInitState(), FStreamableTextureResource::GetState(), FMeshRenderBufferSet::InitOrUpdateResource(), TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleasePooledResource(), SetInitPhase(), and TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::UE_DEPRECATED().
operator=() [1/2]
RENDERCORE_API FRenderResource & FRenderResource::operator= (const FRenderResource & Other)
References FRenderResource(), and Other.
operator=() [2/2]
RENDERCORE_API FRenderResource & FRenderResource::operator= (FRenderResource && Other)
References FRenderResource(), and Other.
ReleaseResource()
virtual RENDERCORE_API void FRenderResource::ReleaseResource () virtual
Prepares the resource for deletion.
This is only called by the rendering thread.
Reimplemented in FHairCardsRestResource, FHairCardsVertexFactory, FHairMeshesRestResource, FLandscapeVertexFactory, FMaterialRenderProxy, FStaticMeshInstanceBuffer, FStaticMeshVertexBuffer, and TStaticStateRHI< InitializerType, RHIRefType, RHIParamRefType >::FStaticStateResource.
Referenced by FLandscapeVertexBuffer::~FLandscapeVertexBuffer(), FMeshRenderBufferSet::~FMeshRenderBufferSet(), FLandscapeVertexFactory::ReleaseResource(), TStaticStateRHI< InitializerType, RHIRefType, RHIParamRefType >::FStaticStateResource::ReleaseResource(), and FMeshRenderBufferSet::UpdateRaytracingGeometryIfEnabled().
ReleaseRHI()
virtual void FRenderResource::ReleaseRHI () inline virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented in FBufferWithRDG, FColorVertexBuffer, FDuplicatedVerticesBuffer, FEmptyVertexDeclaration, FFilterVertexDeclaration, FGeometryCollectionVertexFactory, FGlobalBoundShaderStateResource, FGlobalDynamicReadBuffer, FGPUBaseSkinVertexFactory, FGPUSkinPassthroughVertexFactory, FGPUSortManager::FValueBuffer, FHairCardsVertexFactory, FHairCommonResource, FHairStrandsVertexFactory, FIndexBuffer, FLightmapResourceCluster, FLocalVertexFactory, FMaterialRenderProxy, FMediaVertexDeclaration, FMorphTargetVertexInfoBuffers, FNDIGeometryCollectionBuffer, FNDIHairStrandsBuffer, FNDIVelocityGridBuffer, FNullColorVertexBuffer, FNullVertexBuffer, FParticleScratchVertexBuffer, FParticleSortBuffers, FPhysicsFieldResource, FPositionVertexBuffer, FPrecomputedVolumetricLightmapData, FPrimitiveIdDummyBuffer, FRawStaticIndexBuffer16or32< INDEX_TYPE >, FRDGWrapperVertexBuffer, FRenderTargetPool, FSceneViewport, FScreenVertexDeclaration, FShaderMapResource, FSharedSamplerState, FSimpleElementVertexDeclaration, FSinglePrimitiveStructured, FSkeletalMeshAttributeVertexBuffer, FSkeletalMeshHalfEdgeBuffer, FSkeletalMeshVertexClothBuffer, FSkinWeightDataVertexBuffer, FSkinWeightLookupVertexBuffer, FSkyTextureCubeResource, FSlateRenderTargetRHI, FSlateTexture2DRHIRef, FSlateTextureRenderTarget2DResource, FStaticMeshInstanceBuffer, FStaticMeshSectionAreaWeightedTriangleSamplerBuffer, FStaticMeshVertexBuffer, FStreamableTextureResource, FSubsurfaceProfileTexture, FSubUVBoundingGeometryBuffer, FTexture2DDynamicResource, FTexture, FTextureCollectionResource, FTextureReference, FTextureRenderTarget2DArrayResource, FTextureRenderTarget2DResource, FTextureRenderTargetCubeResource, FTextureRenderTargetVolumeResource, FTextureWithSRV, FTileVertexDeclaration, FVertexBuffer, FVertexBufferWithSRV, FVertexFactory, FViewport, FVirtualTexture2DResource, FVolumetricLightmapBrickAtlas, FWaterMeshVertexBuffer, Nanite::FStreamingManager, Nanite::FVertexFactoryResource, TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >, TGPUSkinVertexFactory< BoneInfluenceType >, TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FBoneBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FClothBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, TStaticStateRHI< InitializerType, RHIRefType, RHIParamRefType >::FStaticStateResource, TUniformBuffer< TBufferStruct >, TUniformBuffer< FLandscapeUniformShaderParameters >, TUniformBuffer< FLightmapResourceClusterShaderParameters >, TUniformBuffer< FPrimitiveUniformShaderParameters >, TWaterVertexFactory< bWithWaterSelectionSupport, DrawMode >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::Indirect >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::IndirectInstancedStereo >, TWaterVertexFactory< WITH_WATER_SELECTION_SUPPORT, EWaterVertexFactoryDrawMode::NonIndirect >, and UE::SVT::FTextureRenderResources.
Definition at line 87 of file RenderResource.h.
Referenced by FRawStaticIndexBuffer16or32< INDEX_TYPE >::ReleaseRHI().
ReleaseRHIForAllResources()
RENDERCORE_API void FRenderResource::ReleaseRHIForAllResources () static
Release all render resources that are currently initialized.
SetFeatureLevel()
void FRenderResource::SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel) inline protected
Definition at line 151 of file RenderResource.h.
References FeatureLevel.
SetInitPhase()
void FRenderResource::SetInitPhase (EInitPhase InInitPhase) inline protected
Definition at line 179 of file RenderResource.h.
References check, InitPhase, IsInitialized(), and MAX.
SetOwnerName()
void FRenderResource::SetOwnerName (FName InOwnerName) inline
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
Definition at line 117 of file RenderResource.h.
Referenced by FLandscapeVertexBuffer::FLandscapeVertexBuffer(), and BeginInitResource().
SetResourceName()
void FRenderResource::SetResourceName (FName InResourceName) inline
Definition at line 133 of file RenderResource.h.
ShouldFreeResourceObject()
RENDERCORE_API bool FRenderResource::ShouldFreeResourceObject (void * ResourceObject, FResourceArrayInterface * ResourceArray) static private
Referenced by CreateRHIBuffer().
UpdateRHI()
RENDERCORE_API void FRenderResource::UpdateRHI (FRHICommandListBase & RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Otherwise, do nothing. This is only called by the rendering thread.
Referenced by FMeshRenderBufferSet::InitOrUpdateResource(), FTextureRenderTarget2DResource::Resize(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::SetContents(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::SetContentsToZero(), FGeometryCollectionVertexFactory::SetData(), FInstancedStaticMeshVertexFactory::SetData(), and FLandscapeVertexFactory::SetData().
Field Documentation
FeatureLevel
TEnumAsByte<ERHIFeatureLevel::Type> FRenderResource::FeatureLevel private
Definition at line 204 of file RenderResource.h.
Referenced by FNaniteVertexFactory::FNaniteVertexFactory(), DECLARE_MULTICAST_DELEGATE_OneParam(), GetFeatureLevel(), FInstancedStaticMeshVertexFactory::GetVertexElements(), FInstancedStaticMeshVertexFactory::GetVertexElements(), FLocalVertexFactory::GetVertexElements(), FLocalVertexFactory::GetVertexElements(), FMeshParticleVertexFactory::GetVertexElements(), FMeshParticleVertexFactory::GetVertexElements(), TGPUSkinVertexFactory< BoneInfluenceType >::GetVertexElements(), TGPUSkinVertexFactory< BoneInfluenceType >::GetVertexElements(), HasValidFeatureLevel(), and SetFeatureLevel().
InitPhase
EInitPhase FRenderResource::InitPhase = EInitPhase::Default private
Definition at line 205 of file RenderResource.h.
Referenced by GetInitPhase(), and SetInitPhase().
ListIndex
int32 FRenderResource::ListIndex private
Definition at line 203 of file RenderResource.h.
Referenced by GetListIndex(), and IsInitialized().
ResourceState
ERenderResourceState FRenderResource::ResourceState = ERenderResourceState::Default
Definition at line 208 of file RenderResource.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderResource.h