Unreal Engine 5.6 C++ API: Metasound::TLiteralNode< DataType > Class Template Reference
Metasound::TLiteralNode< DataType > Class Template Reference
TLiteralNode represents a variable within a metasound graph.
#include "MetasoundLiteralNode.h"
Public Member Functions
TLiteralNode (const FVertexName &InInstanceName, const FGuid &InInstanceID, FLiteral &&InParam)
UE_DEPRECATED (5.3, "Use the default interface on the node class metadata") static FVertexInterface DeclareVertexInterface()
Public Member Functions inherited from Metasound::FLiteralNode
METASOUNDFRONTEND_API FLiteralNode (const FVertexName &InInstanceName, const FGuid &InInstanceID, const FName &InDataTypeName, EVertexAccessType InAccessType, FOperatorFactorySharedRef InFactory)
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
virtual METASOUNDFRONTEND_API const FVertexInterface & GetVertexInterface () const override
Return the current vertex interface.
virtual METASOUNDFRONTEND_API bool IsVertexInterfaceSupported (const FVertexInterface &InInterface) const override
virtual METASOUNDFRONTEND_API bool SetVertexInterface (const FVertexInterface &InInterface) override
Public Member Functions inherited from Metasound::FNode
METASOUNDGRAPHCORE_API FNode (const FVertexName &InInstanceName, const FGuid &InInstanceID, const FNodeClassMetadata &InInfo, TSharedPtr< const IOperatorData > InOperatorData={})
virtual ~FNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FVertexName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default input literal for a vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Static Public Member Functions
static FNodeClassMetadata GetNodeInfo ()
Static Public Member Functions inherited from Metasound::FLiteralNode
static METASOUNDFRONTEND_API FNodeClassMetadata GetNodeMetadata (const FName &InDataTypeName, EVertexAccessType InAccessType)
Static Private Attributes
static constexpr EVertexAccessType AccessType = (bIsExecutableDataType || bIsPostExecutableDataType) ? EVertexAccessType::Reference : EVertexAccessType::Value
static constexpr bool bIsExecutableDataType = TExecutableDataType<DataType>::bIsExecutable
static constexpr bool bIsPostExecutableDataType = TPostExecutableDataType<DataType>::bIsPostExecutable
Additional Inherited Members
Static Protected Member Functions inherited from Metasound::FLiteralNode
static METASOUNDFRONTEND_API FVertexInterface CreateVertexInterface (const FName &InDataTypeName, EVertexAccessType InAccessType)
Detailed Description
template<typename DataType>
class Metasound::TLiteralNode< DataType >
TLiteralNode represents a variable within a metasound graph.
Definition at line 176 of file MetasoundLiteralNode.h.
Constructor & Destructor Documentation
TLiteralNode()
template<typename DataType> Metasound::TLiteralNode< DataType >::TLiteralNode (const FVertexName & InInstanceName, const FGuid & InInstanceID, FLiteral && InParam) inline explicit
Definition at line 201 of file MetasoundLiteralNode.h.
References Metasound::FLiteralNode::FLiteralNode(), AccessType, Metasound::GetMetasoundDataTypeName(), Metasound::MakeOperatorFactoryRef(), and MoveTemp().
Member Function Documentation
GetNodeInfo()
template<typename DataType> FNodeClassMetadata Metasound::TLiteralNode< DataType >::GetNodeInfo () inline static
Definition at line 194 of file MetasoundLiteralNode.h.
References AccessType, Metasound::GetMetasoundDataTypeName(), and Metasound::FLiteralNode::GetNodeMetadata().
UE_DEPRECATED()
template<typename DataType> Metasound::TLiteralNode< DataType >::UE_DEPRECATED (5. 3, "Use the default interface on the node class metadata") inline
Definition at line 188 of file MetasoundLiteralNode.h.
References AccessType, Metasound::FLiteralNode::CreateVertexInterface(), and Metasound::GetMetasoundDataTypeName().
Field Documentation
AccessType
template<typename DataType> EVertexAccessType Metasound::TLiteralNode< DataType >::AccessType = (bIsExecutableDataType || bIsPostExecutableDataType) ? EVertexAccessType::Reference : EVertexAccessType::Value static constexpr private
Definition at line 184 of file MetasoundLiteralNode.h.
Referenced by TLiteralNode(), GetNodeInfo(), and UE_DEPRECATED().
bIsExecutableDataType
template<typename DataType> bool Metasound::TLiteralNode< DataType >::bIsExecutableDataType = TExecutableDataType<DataType>::bIsExecutable static constexpr private
Definition at line 180 of file MetasoundLiteralNode.h.
bIsPostExecutableDataType
template<typename DataType> bool Metasound::TLiteralNode< DataType >::bIsPostExecutableDataType = TPostExecutableDataType<DataType>::bIsPostExecutable static constexpr private
Definition at line 181 of file MetasoundLiteralNode.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundLiteralNode.h