Unreal Engine 5.6 C++ API: FGraphEditorDragDropAction Class Reference
FGraphEditorDragDropAction Class Reference
#include "GraphEditorDragDropAction.h"
Public Member Functions
DRAG_DROP_OPERATOR_TYPE (FGraphEditorDragDropAction, FDragDropOperation) FGraphEditorDragDropAction()
virtual FReply DroppedOnAction (TSharedRef< struct FEdGraphSchemaAction > Action)
virtual FReply DroppedOnCategory (FText Category)
virtual FReply DroppedOnNode (const FVector2f &ScreenPosition, const FVector2f &GraphPosition)
virtual FReply DroppedOnPanel (const TSharedRef< SWidget > &Panel, const FVector2f &ScreenPosition, const FVector2f &GraphPosition, UEdGraph &Graph)
virtual FReply DroppedOnPin (const FVector2f &ScreenPosition, const FVector2f &GraphPosition)
bool HasFeedbackMessage ()
virtual void HoverTargetChanged ()
virtual bool IsSupportedBySchema (const UEdGraphSchema *Schema) const
void SetDropTargetValid (bool bValid)
void SetFeedbackMessage (const TSharedPtr< SWidget > &Message)
void SetHoveredAction (TSharedPtr< struct FEdGraphSchemaAction > Action)
void SetHoveredCategoryName (const FText &InHoverCategoryName)
void SetHoveredGraph (const TSharedPtr< SGraphPanel > &InGraph)
void SetHoveredNode (const TSharedPtr< SGraphNode > &InNode)
void SetHoveredNode (UEdGraphNode *InNode)
void SetHoveredPin (UEdGraphPin *InPin)
void SetSimpleFeedbackMessage (const FSlateBrush *Icon, const FSlateColor &IconColor, const FText &Message, const FSlateBrush *SecondaryIcon=nullptr, const FSlateColor SecondaryColor=FSlateColor())
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnNode(FVector2D ScreenPosition
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnPanel(const TSharedRef< SWidget > &Panel
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") virtual FReply DroppedOnPin(FVector2D ScreenPosition
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const
Gets the widget that will serve as the decorator unless overridden.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
FVector2D FVector2D GraphPosition
FVector2D ScreenPosition
FVector2D GraphPosition UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
FVector2D FVector2D UEdGraph &Graph UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Protected Member Functions
virtual void Construct () override
Constructs the window and widget if applicable.
virtual EVisibility GetErrorIconVisible () const
UEdGraph * GetHoveredGraph () const
UEdGraphNode * GetHoveredNode () const
UEdGraphPin * GetHoveredPin () const
virtual EVisibility GetIconVisible () const
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bDropTargetValid
TWeakPtr< struct FEdGraphSchemaAction > HoveredAction
FText HoveredCategoryName
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Private Attributes
TSharedPtr< SGraphPanel > HoveredGraph
TWeakObjectPtr< UEdGraphNode > HoveredNode
FEdGraphPinReference HoveredPin
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 29 of file GraphEditorDragDropAction.h.
Member Function Documentation
Construct()
virtual void FGraphEditorDragDropAction::Construct () override protected virtual
Constructs the window and widget if applicable.
Reimplemented from FDragDropOperation.
Reimplemented in FRigVMGraphExplorerDragDropOp, and UE::Sequencer::FOutlinerViewModelDragDropOp.
DRAG_DROP_OPERATOR_TYPE()
FGraphEditorDragDropAction::DRAG_DROP_OPERATOR_TYPE (FGraphEditorDragDropAction , FDragDropOperation)
References FDragDropOperation::FDragDropOperation().
DroppedOnAction()
virtual FReply FGraphEditorDragDropAction::DroppedOnAction (TSharedRef< struct FEdGraphSchemaAction > Action) inline virtual
Reimplemented in FRigVMFunctionDragDropAction.
Definition at line 55 of file GraphEditorDragDropAction.h.
References DroppedOnAction(), and FReply::Unhandled().
Referenced by DroppedOnAction().
DroppedOnCategory()
virtual FReply FGraphEditorDragDropAction::DroppedOnCategory (FText Category) inline virtual
Reimplemented in FMyBlueprintItemDragDropAction, and FRigVMFunctionDragDropAction.
Definition at line 56 of file GraphEditorDragDropAction.h.
References Category, and FReply::Unhandled().
DroppedOnNode()
virtual FReply FGraphEditorDragDropAction::DroppedOnNode (const FVector2f & ScreenPosition, const FVector2f & GraphPosition) virtual
Reimplemented in FKismetVariableDragDropAction.
References DroppedOnNode(), GraphPosition, and ScreenPosition.
Referenced by DroppedOnNode(), and UE_DEPRECATED().
DroppedOnPanel()
virtual FReply FGraphEditorDragDropAction::DroppedOnPanel (const TSharedRef< SWidget > & Panel, const FVector2f & ScreenPosition, const FVector2f & GraphPosition, UEdGraph & Graph) virtual
Reimplemented in FGraphSchemaActionDragDropAction, FKismetVariableDragDropAction, FRigVMFunctionDragDropAction, and FRigVMGraphExplorerDragDropOp.
References DroppedOnPanel(), GraphPosition, and ScreenPosition.
Referenced by DroppedOnPanel().
DroppedOnPin()
virtual FReply FGraphEditorDragDropAction::DroppedOnPin (const FVector2f & ScreenPosition, const FVector2f & GraphPosition) virtual
Reimplemented in FGraphSchemaActionDragDropAction, FKismetVariableDragDropAction, FRigVMFunctionDragDropAction, and FRigVMGraphExplorerDragDropOp.
References DroppedOnPin(), GraphPosition, and ScreenPosition.
Referenced by DroppedOnPin().
GetErrorIconVisible()
virtual EVisibility FGraphEditorDragDropAction::GetErrorIconVisible () const protected virtual
GetHoveredGraph()
UEdGraph * FGraphEditorDragDropAction::GetHoveredGraph () const protected
GetHoveredNode()
UEdGraphNode * FGraphEditorDragDropAction::GetHoveredNode () const protected
GetHoveredPin()
UEdGraphPin * FGraphEditorDragDropAction::GetHoveredPin () const protected
GetIconVisible()
virtual EVisibility FGraphEditorDragDropAction::GetIconVisible () const protected virtual
HasFeedbackMessage()
bool FGraphEditorDragDropAction::HasFeedbackMessage ()
HoverTargetChanged()
virtual void FGraphEditorDragDropAction::HoverTargetChanged () inline virtual
Reimplemented in FMyBlueprintItemDragDropAction, and FRigVMFunctionDragDropAction.
Definition at line 45 of file GraphEditorDragDropAction.h.
Referenced by FGraphSchemaActionDragDropAction::DRAG_DROP_OPERATOR_TYPE().
IsSupportedBySchema()
virtual bool FGraphEditorDragDropAction::IsSupportedBySchema (const UEdGraphSchema * Schema) const inline virtual
Definition at line 59 of file GraphEditorDragDropAction.h.
SetDropTargetValid()
void FGraphEditorDragDropAction::SetDropTargetValid (bool bValid) inline
Definition at line 42 of file GraphEditorDragDropAction.h.
References bDropTargetValid.
SetFeedbackMessage()
void FGraphEditorDragDropAction::SetFeedbackMessage (const TSharedPtr< SWidget > & Message)
SetHoveredAction()
void FGraphEditorDragDropAction::SetHoveredAction (TSharedPtr< struct FEdGraphSchemaAction > Action)
SetHoveredCategoryName()
void FGraphEditorDragDropAction::SetHoveredCategoryName (const FText & InHoverCategoryName)
SetHoveredGraph()
void FGraphEditorDragDropAction::SetHoveredGraph (const TSharedPtr< SGraphPanel > & InGraph)
SetHoveredNode() [1/2]
void FGraphEditorDragDropAction::SetHoveredNode (const TSharedPtr< SGraphNode > & InNode)
SetHoveredNode() [2/2]
void FGraphEditorDragDropAction::SetHoveredNode (UEdGraphNode * InNode)
SetHoveredPin()
void FGraphEditorDragDropAction::SetHoveredPin (UEdGraphPin * InPin)
SetSimpleFeedbackMessage()
void FGraphEditorDragDropAction::SetSimpleFeedbackMessage (const FSlateBrush * Icon, const FSlateColor & IconColor, const FText & Message, const FSlateBrush * SecondaryIcon = nullptr, const FSlateColor SecondaryColor = FSlateColor())
References Icon.
UE_DEPRECATED() [1/3]
FGraphEditorDragDropAction::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.")
References DroppedOnNode(), GraphPosition, ScreenPosition, UE_DEPRECATED(), and UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION.
UE_DEPRECATED() [2/3]
FGraphEditorDragDropAction::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FGraphEditorDragDropAction::UE_DEPRECATED (5. 6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
bDropTargetValid
bool FGraphEditorDragDropAction::bDropTargetValid protected
Definition at line 95 of file GraphEditorDragDropAction.h.
Referenced by SetDropTargetValid().
GraphPosition
FVector2D FVector2D FGraphEditorDragDropAction::GraphPosition
Definition at line 53 of file GraphEditorDragDropAction.h.
Referenced by DroppedOnNode(), FKismetVariableDragDropAction::DroppedOnNode(), DroppedOnPanel(), FGraphSchemaActionDragDropAction::DroppedOnPanel(), FKismetVariableDragDropAction::DroppedOnPanel(), FRigVMFunctionDragDropAction::DroppedOnPanel(), FRigVMGraphExplorerDragDropOp::DroppedOnPanel(), DroppedOnPin(), FGraphSchemaActionDragDropAction::DroppedOnPin(), FKismetVariableDragDropAction::DroppedOnPin(), FRigVMFunctionDragDropAction::DroppedOnPin(), FRigVMGraphExplorerDragDropOp::DroppedOnPin(), and UE_DEPRECATED().
HoveredAction
TWeakPtr<struct FEdGraphSchemaAction> FGraphEditorDragDropAction::HoveredAction protected
Definition at line 92 of file GraphEditorDragDropAction.h.
HoveredCategoryName
FText FGraphEditorDragDropAction::HoveredCategoryName protected
Definition at line 89 of file GraphEditorDragDropAction.h.
HoveredGraph
TSharedPtr<SGraphPanel> FGraphEditorDragDropAction::HoveredGraph private
Definition at line 84 of file GraphEditorDragDropAction.h.
HoveredNode
TWeakObjectPtr<UEdGraphNode> FGraphEditorDragDropAction::HoveredNode private
Definition at line 81 of file GraphEditorDragDropAction.h.
HoveredPin
FEdGraphPinReference FGraphEditorDragDropAction::HoveredPin private
Definition at line 78 of file GraphEditorDragDropAction.h.
ScreenPosition
FVector2D FGraphEditorDragDropAction::ScreenPosition
Definition at line 53 of file GraphEditorDragDropAction.h.
Referenced by DroppedOnNode(), FKismetVariableDragDropAction::DroppedOnNode(), DroppedOnPanel(), FGraphSchemaActionDragDropAction::DroppedOnPanel(), FKismetVariableDragDropAction::DroppedOnPanel(), FRigVMFunctionDragDropAction::DroppedOnPanel(), FRigVMGraphExplorerDragDropOp::DroppedOnPanel(), DroppedOnPin(), FGraphSchemaActionDragDropAction::DroppedOnPin(), FKismetVariableDragDropAction::DroppedOnPin(), FRigVMFunctionDragDropAction::DroppedOnPin(), FRigVMGraphExplorerDragDropOp::DroppedOnPin(), and UE_DEPRECATED().
UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION [1/2]
FVector2D GraphPosition FGraphEditorDragDropAction::UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Definition at line 47 of file GraphEditorDragDropAction.h.
Referenced by UE_DEPRECATED().
UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION [2/2]
FVector2D FVector2D UEdGraph& Graph FGraphEditorDragDropAction::UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Definition at line 53 of file GraphEditorDragDropAction.h.
The documentation for this class was generated from the following file:
Editor/GraphEditor/Public/GraphEditorDragDropAction.h