Unreal Engine 5.6 C++ API: SBlueprintDiff Class Reference
SBlueprintDiff Class Reference
#include "SBlueprintDiff.h"
Data Structures
struct FDiffControl
class FScopedCategorySortChange
To make diffing more accurate and friendly, UBlueprint::CategorySorting gets modified.
Public Member Functions
virtual ~SBlueprintDiff ()
DECLARE_DELEGATE_TwoParams (FOpenInDefaults, const class UBlueprint *, const class UBlueprint *)
void OnBlueprintChanged (UBlueprint *InBlueprint)
Called when blueprint is modified.
void OnDiffListSelectionChanged (TSharedPtr< struct FDiffResultItem > TheDiff)
Called when user clicks on an entry in the listview of differences.
void OnGraphChanged (FGraphToDiff *Diff)
Called when a new Graph is clicked on by user.
void OnGraphSelectionChanged (TSharedPtr< FGraphToDiff > Item, ESelectInfo::Type SelectionType)
Called when user clicks on a new graph list item.
BlueprintNew NewRevision SLATE_ARGUMENT (bool, ShowAssetNames) SLATE_ARGUMENT(TSharedPtr< SWindow >
SLATE_ARGUMENT (const class UBlueprint *, BlueprintOld) SLATE_ARGUMENT(const class UBlueprint *
BlueprintNew SLATE_ARGUMENT (struct FRevisionInfo, OldRevision) SLATE_ARGUMENT(struct FRevisionInfo
SLATE_BEGIN_ARGS (SBlueprintDiff)
BlueprintNew NewRevision ParentWindow SLATE_END_ARGS () void Construct(const FArguments &InArgs)
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedPtr< SWindow > CreateDiffWindow (const UBlueprint *OldBlueprint, const UBlueprint *NewBlueprint, const FRevisionInfo &OldRevision, const FRevisionInfo &NewRevision, const UClass *BlueprintClass)
Helper function to create a window that holds a diff widget that defaults a window title.
static TSharedPtr< SWindow > CreateDiffWindow (FText WindowTitle, const UBlueprint *OldBlueprint, const UBlueprint *NewBlueprint, const struct FRevisionInfo &OldRevision, const struct FRevisionInfo &NewRevision)
Helper function to create a window that holds a diff widget.
static TSharedRef< SWidget > DefaultEmptyPanel ()
Helper function for generating an empty widget.
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions
void CreateGraphEntry (class UEdGraph *GraphOld, class UEdGraph *GraphNew)
Create a list item entry graph that exists in at least one of the blueprints.
void DisablePinDiffFocus ()
Disable the focus on a particular pin.
FGraphToDiff * FindGraphToDiffEntry (const FString &GraphPath)
Find the FGraphToDiff that displays the graph with GraphPath relative path.
void FocusOnGraphRevisions (FGraphToDiff *Diff)
Bring these revisions of graph into focus on main display.
FDiffControl GenerateBlueprintTypePanel ()
FDiffControl GenerateClassSettingsPanel ()
FDiffControl GenerateComponentsPanel ()
FDiffControl GenerateDefaultsPanel ()
void GenerateDifferencesList ()
Function used to generate the list of differences and the widgets needed to calculate that list.
FDiffControl GenerateGeneralFileCommentEntries ()
FDiffControl GenerateGraphPanel ()
TSharedRef< SOverlay > GenerateGraphWidgetForPanel (FDiffPanel &OutDiffPanel) const
FDiffControl GenerateMyBlueprintPanel ()
TSharedRef< SBox > GenerateRevisionInfoWidgetForPanel (TSharedPtr< SWidget > &OutGeneratedWidget, const FText &InRevisionText) const
FName GetCurrentMode () const
FDiffPanel & GetDiffPanelForNode (UEdGraphNode &Node)
Get Graph editor associated with this Graph.
FSlateIcon GetLockViewImage () const
Get the image to show for the toggle lock option.
FSlateIcon GetSplitViewModeImage () const
Get the image to show for the toggle split view mode option.
void HandleGraphChanged (FGraphToDiff *Diff)
Event handler that updates the graph view when user selects a new graph.
bool HasNextDiff () const
Called to determine whether we have a list of differences to cycle through.
bool HasPrevDiff () const
bool IsGraphDiffNeeded (class UEdGraph *InGraph) const
Checks if a graph is valid for diffing.
void NextDiff ()
Called when user clicks button to go to next difference.
void OnCloseAssetEditor (UObject *Asset, EAssetEditorCloseReason CloseReason)
Called when editor may need to be closed.
void OnModeChanged (const FName &InNewViewMode) const
void OnToggleLockView ()
User toggles the option to lock the views between the two blueprints.
void OnToggleSplitViewMode ()
User toggles the option to change the split view mode betwwen vertical and horizontal.
void PrevDiff ()
Called when user clicks button to go to prev difference.
void ResetGraphEditors ()
Reset the graph editor, called when user switches graphs to display.
void SetCurrentMode (FName NewMode)
Accessor and event handler for toggling between diff view modes (defaults, components, graph view, interface, macro):
void UpdateTopSectionVisibility (const FName &InNewViewMode) const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
FDelegateHandle AssetEditorCloseDelegate
bool bLockViews
If the two views should be locked.
bool bVerticalSplitGraphMode = true
If the view on Graph Mode should be divided vertically.
FName CurrentMode
TSharedPtr< STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > > > DifferencesTreeView
Tree view that displays the differences, cached for the buttons that iterate the differences:
TSharedPtr< SSplitter > DiffGraphSplitter
TSharedPtr< FAsyncDetailViewDiff > GraphDetailDiff
TArray< TSharedPtr< FGraphToDiff > > Graphs
List of graphs to diff, are added to panel last.
TSharedPtr< SSplitter > GraphToolBarWidget
TSharedPtr< SBox > ModeContents
Contents widget that we swap when mode changes (defaults, components, etc)
TMap< FName, FDiffControl > ModePanels
Stored references to widgets used to display various parts of a blueprint, from the mode name.
FDiffPanel PanelNew
FDiffPanel PanelOld
TArray< TSharedPtr< class FBlueprintDifferenceTreeEntry > > PrimaryDifferencesList
Tree of differences collected across all panels:
TArray< TSharedPtr< class FBlueprintDifferenceTreeEntry > > RealDifferences
List of all differences, cached so that we can iterate only the differences and not labels, etc:
class SBlueprintDiff::FScopedCategorySortChange ScopedCategorySortChange
TSharedPtr< FTabManager > TabManager
We can't use the global tab manager because we need to instance the diff control, so we have our own tab manager:
TSharedPtr< SSplitter > TopRevisionInfoWidget
TWeakPtr< SWindow > WeakParentWindow
A pointer to the window holding this.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Friends
struct FListItemGraphToDiff
Additional Inherited Members
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 139 of file SBlueprintDiff.h.
Constructor & Destructor Documentation
~SBlueprintDiff()
virtual SBlueprintDiff::~SBlueprintDiff () virtual
Member Function Documentation
CreateDiffWindow() [1/2]
TSharedPtr< SWindow > SBlueprintDiff::CreateDiffWindow (const UBlueprint * OldBlueprint, const UBlueprint * NewBlueprint, const FRevisionInfo & OldRevision, const FRevisionInfo & NewRevision, const UClass * BlueprintClass) static
Helper function to create a window that holds a diff widget that defaults a window title.
References CreateDiffWindow(), and SWidget::SWindow.
CreateDiffWindow() [2/2]
TSharedPtr< SWindow > SBlueprintDiff::CreateDiffWindow (FText WindowTitle, const UBlueprint * OldBlueprint, const UBlueprint * NewBlueprint, const struct FRevisionInfo & OldRevision, const struct FRevisionInfo & NewRevision) static
Helper function to create a window that holds a diff widget.
References CreateDiffWindow(), and SWidget::SWindow.
Referenced by CreateDiffWindow(), and CreateDiffWindow().
CreateGraphEntry()
void SBlueprintDiff::CreateGraphEntry (class UEdGraph * GraphOld, class UEdGraph * GraphNew) protected
Create a list item entry graph that exists in at least one of the blueprints.
References CreateGraphEntry().
Referenced by CreateGraphEntry().
DECLARE_DELEGATE_TwoParams()
SBlueprintDiff::DECLARE_DELEGATE_TwoParams (FOpenInDefaults , const class UBlueprint * , const class UBlueprint *)
DefaultEmptyPanel()
TSharedRef< SWidget > SBlueprintDiff::DefaultEmptyPanel () static
Helper function for generating an empty widget.
References SWidget::SWidget(), and DefaultEmptyPanel().
Referenced by DefaultEmptyPanel().
DisablePinDiffFocus()
void SBlueprintDiff::DisablePinDiffFocus () protected
Disable the focus on a particular pin.
References DisablePinDiffFocus().
Referenced by DisablePinDiffFocus().
FindGraphToDiffEntry()
FGraphToDiff * SBlueprintDiff::FindGraphToDiffEntry (const FString & GraphPath) protected
Find the FGraphToDiff that displays the graph with GraphPath relative path.
References FindGraphToDiffEntry().
Referenced by FindGraphToDiffEntry().
FocusOnGraphRevisions()
void SBlueprintDiff::FocusOnGraphRevisions (FGraphToDiff * Diff) protected
Bring these revisions of graph into focus on main display.
References FocusOnGraphRevisions().
Referenced by FocusOnGraphRevisions().
GenerateBlueprintTypePanel()
FDiffControl SBlueprintDiff::GenerateBlueprintTypePanel () protected
GenerateClassSettingsPanel()
FDiffControl SBlueprintDiff::GenerateClassSettingsPanel () protected
GenerateComponentsPanel()
FDiffControl SBlueprintDiff::GenerateComponentsPanel () protected
GenerateDefaultsPanel()
FDiffControl SBlueprintDiff::GenerateDefaultsPanel () protected
GenerateDifferencesList()
void SBlueprintDiff::GenerateDifferencesList () protected
Function used to generate the list of differences and the widgets needed to calculate that list.
References GenerateDifferencesList().
Referenced by GenerateDifferencesList().
GenerateGeneralFileCommentEntries()
FDiffControl SBlueprintDiff::GenerateGeneralFileCommentEntries () protected
GenerateGraphPanel()
FDiffControl SBlueprintDiff::GenerateGraphPanel () protected
GenerateGraphWidgetForPanel()
TSharedRef< SOverlay > SBlueprintDiff::GenerateGraphWidgetForPanel (FDiffPanel & OutDiffPanel) const protected
GenerateMyBlueprintPanel()
FDiffControl SBlueprintDiff::GenerateMyBlueprintPanel () protected
GenerateRevisionInfoWidgetForPanel()
TSharedRef< SBox > SBlueprintDiff::GenerateRevisionInfoWidgetForPanel (TSharedPtr< SWidget > & OutGeneratedWidget, const FText & InRevisionText) const protected
GetCurrentMode()
FName SBlueprintDiff::GetCurrentMode () const inline protected
Definition at line 260 of file SBlueprintDiff.h.
References CurrentMode.
GetDiffPanelForNode()
FDiffPanel & SBlueprintDiff::GetDiffPanelForNode (UEdGraphNode & Node) protected
Get Graph editor associated with this Graph.
References GetDiffPanelForNode().
Referenced by GetDiffPanelForNode().
GetLockViewImage()
FSlateIcon SBlueprintDiff::GetLockViewImage () const protected
Get the image to show for the toggle lock option.
References GetLockViewImage().
Referenced by GetLockViewImage().
GetSplitViewModeImage()
FSlateIcon SBlueprintDiff::GetSplitViewModeImage () const protected
Get the image to show for the toggle split view mode option.
References GetSplitViewModeImage().
Referenced by GetSplitViewModeImage().
HandleGraphChanged()
void SBlueprintDiff::HandleGraphChanged (FGraphToDiff * Diff) protected
Event handler that updates the graph view when user selects a new graph.
References HandleGraphChanged().
Referenced by HandleGraphChanged().
HasNextDiff()
bool SBlueprintDiff::HasNextDiff () const protected
Called to determine whether we have a list of differences to cycle through.
References HasNextDiff().
Referenced by HasNextDiff().
HasPrevDiff()
bool SBlueprintDiff::HasPrevDiff () const protected
References HasPrevDiff().
Referenced by HasPrevDiff().
IsGraphDiffNeeded()
bool SBlueprintDiff::IsGraphDiffNeeded (class UEdGraph * InGraph) const protected
Checks if a graph is valid for diffing.
References IsGraphDiffNeeded().
Referenced by IsGraphDiffNeeded().
NextDiff()
void SBlueprintDiff::NextDiff () protected
Called when user clicks button to go to next difference.
References NextDiff().
Referenced by NextDiff().
OnBlueprintChanged()
void SBlueprintDiff::OnBlueprintChanged (UBlueprint * InBlueprint)
Called when blueprint is modified.
References OnBlueprintChanged().
Referenced by OnBlueprintChanged().
OnCloseAssetEditor()
void SBlueprintDiff::OnCloseAssetEditor (UObject * Asset, EAssetEditorCloseReason CloseReason) protected
Called when editor may need to be closed.
References Asset, and OnCloseAssetEditor().
Referenced by OnCloseAssetEditor().
OnDiffListSelectionChanged()
void SBlueprintDiff::OnDiffListSelectionChanged (TSharedPtr< struct FDiffResultItem > TheDiff)
Called when user clicks on an entry in the listview of differences.
References OnDiffListSelectionChanged().
Referenced by OnDiffListSelectionChanged().
OnGraphChanged()
void SBlueprintDiff::OnGraphChanged (FGraphToDiff * Diff)
Called when a new Graph is clicked on by user.
References OnGraphChanged().
Referenced by OnGraphChanged().
OnGraphSelectionChanged()
void SBlueprintDiff::OnGraphSelectionChanged (TSharedPtr< FGraphToDiff > Item, ESelectInfo::Type SelectionType)
Called when user clicks on a new graph list item.
References Item, and OnGraphSelectionChanged().
Referenced by OnGraphSelectionChanged().
OnModeChanged()
void SBlueprintDiff::OnModeChanged (const FName & InNewViewMode) const protected
OnToggleLockView()
void SBlueprintDiff::OnToggleLockView () protected
User toggles the option to lock the views between the two blueprints.
References OnToggleLockView().
Referenced by OnToggleLockView().
OnToggleSplitViewMode()
void SBlueprintDiff::OnToggleSplitViewMode () protected
User toggles the option to change the split view mode betwwen vertical and horizontal.
References OnToggleSplitViewMode().
Referenced by OnToggleSplitViewMode().
PrevDiff()
void SBlueprintDiff::PrevDiff () protected
Called when user clicks button to go to prev difference.
References PrevDiff().
Referenced by PrevDiff().
ResetGraphEditors()
void SBlueprintDiff::ResetGraphEditors () protected
Reset the graph editor, called when user switches graphs to display.
References ResetGraphEditors().
Referenced by ResetGraphEditors().
SetCurrentMode()
void SBlueprintDiff::SetCurrentMode (FName NewMode) protected
Accessor and event handler for toggling between diff view modes (defaults, components, graph view, interface, macro):
SLATE_ARGUMENT() [1/3]
BlueprintNew NewRevision SBlueprintDiff::SLATE_ARGUMENT (bool , ShowAssetNames)
References SLATE_ARGUMENT(), and SWidget::SWindow.
SLATE_ARGUMENT() [2/3]
SBlueprintDiff::SLATE_ARGUMENT (const class UBlueprint * , BlueprintOld) const
Referenced by SLATE_ARGUMENT(), and SLATE_ARGUMENT().
SLATE_ARGUMENT() [3/3]
BlueprintNew SBlueprintDiff::SLATE_ARGUMENT (struct FRevisionInfo , OldRevision)
References SLATE_ARGUMENT().
SLATE_BEGIN_ARGS()
SBlueprintDiff::SLATE_BEGIN_ARGS (SBlueprintDiff) inline
Definition at line 144 of file SBlueprintDiff.h.
SLATE_END_ARGS()
BlueprintNew NewRevision ParentWindow SBlueprintDiff::SLATE_END_ARGS () const &
References SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
Tick()
virtual void SBlueprintDiff::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
References Tick().
Referenced by Tick().
UpdateTopSectionVisibility()
void SBlueprintDiff::UpdateTopSectionVisibility (const FName & InNewViewMode) const protected
Friends And Related Symbol Documentation
FListItemGraphToDiff
friend struct FListItemGraphToDiff friend
Definition at line 288 of file SBlueprintDiff.h.
References FListItemGraphToDiff.
Referenced by FListItemGraphToDiff.
Field Documentation
AssetEditorCloseDelegate
FDelegateHandle SBlueprintDiff::AssetEditorCloseDelegate protected
Definition at line 308 of file SBlueprintDiff.h.
bLockViews
bool SBlueprintDiff::bLockViews protected
If the two views should be locked.
Definition at line 274 of file SBlueprintDiff.h.
bVerticalSplitGraphMode
bool SBlueprintDiff::bVerticalSplitGraphMode = true protected
If the view on Graph Mode should be divided vertically.
Definition at line 277 of file SBlueprintDiff.h.
CurrentMode
FName SBlueprintDiff::CurrentMode protected
Definition at line 265 of file SBlueprintDiff.h.
Referenced by GetCurrentMode().
DifferencesTreeView
TSharedPtr< STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > > > SBlueprintDiff::DifferencesTreeView protected
Tree view that displays the differences, cached for the buttons that iterate the differences:
Definition at line 300 of file SBlueprintDiff.h.
DiffGraphSplitter
TSharedPtr<SSplitter> SBlueprintDiff::DiffGraphSplitter protected
Definition at line 284 of file SBlueprintDiff.h.
GraphDetailDiff
TSharedPtr<FAsyncDetailViewDiff> SBlueprintDiff::GraphDetailDiff protected
Definition at line 271 of file SBlueprintDiff.h.
Graphs
TArray<TSharedPtr<FGraphToDiff> > SBlueprintDiff::Graphs protected
List of graphs to diff, are added to panel last.
Definition at line 218 of file SBlueprintDiff.h.
GraphToolBarWidget
TSharedPtr<SSplitter> SBlueprintDiff::GraphToolBarWidget protected
Definition at line 286 of file SBlueprintDiff.h.
ModeContents
TSharedPtr<SBox> SBlueprintDiff::ModeContents protected
Contents widget that we swap when mode changes (defaults, components, etc)
Definition at line 280 of file SBlueprintDiff.h.
ModePanels
TMap<FName, FDiffControl> SBlueprintDiff::ModePanels protected
Stored references to widgets used to display various parts of a blueprint, from the mode name.
Definition at line 303 of file SBlueprintDiff.h.
PanelNew
FDiffPanel SBlueprintDiff::PanelNew protected
Definition at line 268 of file SBlueprintDiff.h.
PanelOld
FDiffPanel SBlueprintDiff::PanelOld protected
Definition at line 268 of file SBlueprintDiff.h.
PrimaryDifferencesList
TArray< TSharedPtr<class FBlueprintDifferenceTreeEntry> > SBlueprintDiff::PrimaryDifferencesList protected
Tree of differences collected across all panels:
Definition at line 294 of file SBlueprintDiff.h.
RealDifferences
TArray< TSharedPtr<class FBlueprintDifferenceTreeEntry> > SBlueprintDiff::RealDifferences protected
List of all differences, cached so that we can iterate only the differences and not labels, etc:
Definition at line 297 of file SBlueprintDiff.h.
ScopedCategorySortChange
class SBlueprintDiff::FScopedCategorySortChange SBlueprintDiff::ScopedCategorySortChange protected
TabManager
TSharedPtr<FTabManager> SBlueprintDiff::TabManager protected
We can't use the global tab manager because we need to instance the diff control, so we have our own tab manager:
Definition at line 291 of file SBlueprintDiff.h.
TopRevisionInfoWidget
TSharedPtr<SSplitter> SBlueprintDiff::TopRevisionInfoWidget protected
Definition at line 282 of file SBlueprintDiff.h.
WeakParentWindow
TWeakPtr<SWindow> SBlueprintDiff::WeakParentWindow protected
A pointer to the window holding this.
Definition at line 306 of file SBlueprintDiff.h.
The documentation for this class was generated from the following file:
Editor/Kismet/Public/SBlueprintDiff.h