Unreal Engine 5.6 C++ API: FBoxCenterAndExtent Class Reference
FBoxCenterAndExtent Class Reference
An unquantized bounding box.
#include "GenericOctree.h"
Public Types
using FReal = FVector4::FReal
Public Member Functions
FBoxCenterAndExtent ()
Default constructor.
FBoxCenterAndExtent (const FBox &Box)
FBox conversion constructor.
FBoxCenterAndExtent (const float PositionRadius[4])
Center - radius as four contiguous floats conversion constructor.
FBoxCenterAndExtent (const FVector &InCenter, const FVector &InExtent)
Initialization constructor.
template<typename TExtent>
FBoxCenterAndExtent (const UE::Math::TBoxSphereBounds< FReal, TExtent > &BoxSphere)
FBoxSphereBounds conversion constructor.
FBox GetBox () const
Converts to a FBox.
Data Fields
FVector4 Center
FVector4 Extent
Friends
FORCEINLINE bool Intersect (const FBoxCenterAndExtent &A, const FBoxCenterAndExtent &B)
Determines whether two boxes intersect.
FORCEINLINE bool Intersect (const float A[4], const FBoxCenterAndExtent &B)
Determines whether two boxes intersect.
template<typename TExtent>
FORCEINLINE bool Intersect (const UE::Math::TBoxSphereBounds< FReal, TExtent > &A, const FBoxCenterAndExtent &B)
Determines whether two boxes intersect.
Detailed Description
An unquantized bounding box.
Definition at line 41 of file GenericOctree.h.
Member Typedef Documentation
FReal
using FBoxCenterAndExtent::FReal = FVector4::FReal
Definition at line 44 of file GenericOctree.h.
Constructor & Destructor Documentation
FBoxCenterAndExtent() [1/5]
FBoxCenterAndExtent::FBoxCenterAndExtent () inline nodiscard
Default constructor.
Definition at line 50 of file GenericOctree.h.
Referenced by Intersect, Intersect, and Intersect.
FBoxCenterAndExtent() [2/5]
FBoxCenterAndExtent::FBoxCenterAndExtent (const FVector & InCenter, const FVector & InExtent) inline nodiscard
Initialization constructor.
Definition at line 53 of file GenericOctree.h.
References Center, Extent, and FVector.
FBoxCenterAndExtent() [3/5]
FBoxCenterAndExtent::FBoxCenterAndExtent (const FBox & Box) inline nodiscard
FBox conversion constructor.
Definition at line 59 of file GenericOctree.h.
References Box, Center, Extent, and FVector.
FBoxCenterAndExtent() [4/5]
template<typename TExtent> FBoxCenterAndExtent::FBoxCenterAndExtent (const UE::Math::TBoxSphereBounds< FReal, TExtent > & BoxSphere) inline explicit nodiscard
FBoxSphereBounds conversion constructor.
Definition at line 69 of file GenericOctree.h.
References UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent, Center, Extent, FVector, and UE::Math::TBoxSphereBounds< T, TExtent >::Origin.
FBoxCenterAndExtent() [5/5]
FBoxCenterAndExtent::FBoxCenterAndExtent (const float PositionRadius[4]) inline explicit nodiscard
Center - radius as four contiguous floats conversion constructor.
Definition at line 77 of file GenericOctree.h.
References Center, and Extent.
Member Function Documentation
GetBox()
FBox FBoxCenterAndExtent::GetBox () const inline nodiscard
Converts to a FBox.
Definition at line 84 of file GenericOctree.h.
References Center, and Extent.
Friends And Related Symbol Documentation
Intersect [1/3]
FORCEINLINE bool Intersect (const FBoxCenterAndExtent & A, const FBoxCenterAndExtent & B) friend
Determines whether two boxes intersect.
Warning: this operates on the W of the bounds positions!
Returns
true if the boxes intersect, or false.
Definition at line 94 of file GenericOctree.h.
References FBoxCenterAndExtent(), A, B, FORCEINLINE, VectorAbs(), VectorAdd(), VectorAnyGreaterThan(), VectorLoadAligned(), and VectorSubtract().
Intersect [2/3]
FORCEINLINE bool Intersect (const float A[4], const FBoxCenterAndExtent & B) friend
Determines whether two boxes intersect.
Warning: this operates on the W of the bounds positions!
Parameters
A box given in center - radius form as four contiguous floats
Returns
true if the boxes intersect, or false.
Definition at line 130 of file GenericOctree.h.
References FBoxCenterAndExtent(), A, B, FORCEINLINE, VectorAbs(), VectorAdd(), VectorAnyGreaterThan(), VectorLoadAligned(), VectorLoadFloat1(), VectorSet_W0(), and VectorSubtract().
Intersect [3/3]
template<typename TExtent> FORCEINLINE bool Intersect (const UE::Math::TBoxSphereBounds< FReal, TExtent > & A, const FBoxCenterAndExtent & B) friend
Determines whether two boxes intersect.
Warning: this operates on the W of the bounds positions!
Returns
true if the boxes intersect, or false.
Definition at line 112 of file GenericOctree.h.
References FBoxCenterAndExtent(), A, B, FORCEINLINE, VectorAbs(), VectorAdd(), VectorAnyGreaterThan(), VectorLoadAligned(), and VectorSubtract().
Field Documentation
Center
FVector4 FBoxCenterAndExtent::Center
Definition at line 46 of file GenericOctree.h.
Referenced by FBoxCenterAndExtent(), FBoxCenterAndExtent(), FBoxCenterAndExtent(), FBoxCenterAndExtent(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::AddElementToNode(), GetBox(), and FOctreeNodeContext::GetChildContext().
Extent
FVector4 FBoxCenterAndExtent::Extent
Definition at line 47 of file GenericOctree.h.
Referenced by FBoxCenterAndExtent(), FBoxCenterAndExtent(), FBoxCenterAndExtent(), FBoxCenterAndExtent(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::AddElementToNode(), GetBox(), and FOctreeNodeContext::GetChildContext().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/GenericOctree.h