Unreal Engine 5.6 C++ API: FRigVMEditorBase Class Reference
FRigVMEditorBase Class Reference
#include "RigVMEditor.h"
Public Member Functions
bool CanCopyNodes () const
bool CanCutNodes () const
bool CanDeleteNodes () const
bool CanDuplicateNodes () const
bool CanPasteNodes () const
bool CanStartWatchingPin () const
bool CanStopWatchingPin () const
void Compile ()
void CopySelectedNodes ()
void CutSelectedNodes ()
void DeleteSelectedNodes ()
void DuplicateNodes ()
FText GetGraphDecorationString (UEdGraph *InGraph) const
virtual URigVMBlueprint * GetRigVMBlueprint () const override
void HandleJumpToHyperlink (const UObject *InSubject)
virtual void InitRigVMEditor (const EToolkitMode::Type Mode, const TSharedPtr< class IToolkitHost > &InitToolkitHost, class URigVMBlueprint *InRigVMBlueprint)
Edits the specified asset(s)
bool IsCompilingEnabled () const
virtual bool IsEditable (UEdGraph *InGraph) const override
virtual void OnGraphNodeDropToPerform (TSharedPtr< FDragDropOperation > InDragDropOp, UEdGraph *InGraph, const FVector2f &InNodePosition, const FVector2f &InScreenPosition) override
virtual FOnRefreshEvent OnRefresh () override
void OnStartWatchingPin ()
void OnStopWatchingPin ()
void PasteNodes ()
Public Member Functions inherited from IRigVMEditor
DECLARE_EVENT (IRigVMEditor, FOnRefreshEvent)
DECLARE_EVENT_OneParam (IRigVMEditor, FPreviewHostUpdated, IRigVMEditor *)
virtual UEdGraph * GetFocusedGraph () const =0
virtual TWeakPtr< class SGraphEditor > GetFocusedGraphEditor ()=0
virtual FName GetGraphExplorerWidgetID ()=0
virtual TSharedPtr< FAssetEditorToolkit > GetHostingApp ()=0
virtual bool GetIsContextSensitive ()=0
virtual FNotifyHook * GetNotifyHook ()=0
virtual const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const =0
virtual void GetPinTypeSelectorFilters (TArray< TSharedPtr< class IPinTypeSelectorFilter > > &OutFilters) const =0
virtual FPreviewScene * GetPreviewScene ()=0
virtual TSharedPtr< class SRigVMDetailsInspector > GetRigVMInspector () const =0
virtual TSharedPtr< FTabManager > GetTabManager ()=0
virtual TSharedRef< FUICommandList > GetToolkitCommands ()=0
virtual void JumpToHyperlink (const UObject *ObjectReference, bool bRequestRename=false)=0
virtual void OnAddNewVariable ()=0
virtual TSharedPtr< SDockTab > OpenDocument (const UObject *DocumentID, FDocumentTracker::EOpenDocumentCause Cause)=0
virtual TSharedPtr< SGraphEditor > OpenGraphAndBringToFront (UEdGraph *Graph, bool bSetFocus=true)=0
virtual void SetIsContextSensitive (const bool bIsContextSensitive)=0
virtual void SummonSearchUI (bool bSetFindWithinBlueprint, FString NewSearchTerms=FString(), bool bSelectFirstResult=false)=0
virtual void ZoomToSelection_Clicked ()=0
Static Public Member Functions
static FRigVMEditorBase * GetFromAssetEditorInstance (IAssetEditorInstance *Instance)
static FSlateBrush const * GetVarIconAndColorFromPinType (const FEdGraphPinType &PinType, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
static FSlateBrush const * GetVarIconAndColorFromProperty (const FProperty *Property, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
Protected Types
enum ERigVMEditorExecutionModeType { ERigVMEditorExecutionModeType_Release , ERigVMEditorExecutionModeType_Debug }
Protected Member Functions
FRigVMEditorBase ()
virtual ~FRigVMEditorBase ()
virtual void AddNewFunctionVariant (const UEdGraph *InOriginalFunction) override
void AddReferencedObjects (FReferenceCollector &Collector)
bool AreDelegatesAllowed () const
bool AreEventGraphsAllowed () const
bool AreMacrosAllowed () const
virtual void BindCommands ()
void BringToolkitToFront ()
virtual void CacheNameLists ()
Update the name lists for use in name combo boxes.
virtual bool CanAddNewLocalVariable () const override
bool CanAutoCompileGraph () const
bool CanHideItem () const
void ClearDetailObject (bool bChangeUISelectionState=true)
void ClearDetailsViewWrapperObjects ()
void CreateDefaultCommandsImpl ()
virtual void CreateEmptyGraphContent (URigVMController *InController)
bool DetailViewShowsAnyRigUnit () const
bool DetailViewShowsLocalVariable () const
bool DetailViewShowsStruct (UScriptStruct *InStruct) const
void ExtendMenu ()
Extend menu.
void ExtendToolbar ()
Extend toolbar.
virtual void FillToolbar (FToolBarBuilder &ToolbarBuilder, bool bEndSection=true)
Fill the toolbar with content.
void FocusInspectorOnGraphSelection (const TSet< class UObject * > &NewSelection, bool bForceRefresh=false)
virtual void ForceEditorRefresh (ERefreshRigVMEditorReason::Type Reason=ERefreshRigVMEditorReason::UnknownReason) override
void FrameSelection ()
virtual FMenuBuilder GenerateBulkEditMenu ()
TSharedRef< SWidget > GenerateBulkEditMenuContent ()
TSharedRef< SWidget > GenerateEventQueueMenuContent ()
virtual void GenerateEventQueueMenuContent (FMenuBuilder &MenuBuilder)
TSharedRef< SWidget > GenerateExecutionModeMenuContent ()
FText GetBaseToolkitName () const
UBlueprint * GetBlueprintObj () const
virtual FString GetCustomDebugObjectLabel (UObject *ObjectBeingDebugged) const override
virtual void GetDebugObjects (TArray< FRigVMCustomDebugObject > &DebugList) const override
virtual TArray< FName > GetDefaultEventQueue () const
TSubclassOf< UEdGraphSchema > GetDefaultSchemaClass () const
virtual UClass * GetDetailWrapperClass () const
virtual const FName GetEditorModeName () const
TArray< FName > GetEventQueue () const
virtual int32 GetEventQueueComboValue () const
FSlateIcon GetEventQueueIcon () const
virtual FSlateIcon GetEventQueueIcon (const TArray< FName > &InEventQueue) const
virtual FText GetEventQueueLabel () const
int32 GetExecutionModeComboValue () const
FSlateIcon GetExecutionModeIcon () const
FText GetExecutionModeLabel () const
URigVMController * GetFocusedController () const
virtual URigVMGraph * GetFocusedModel () const override
FGraphAppearanceInfo GetGraphAppearance (class UEdGraph *InGraph) const
TSharedPtr< SGraphEditor > GetGraphEditor (UEdGraph *InEdGraph) const
virtual TSharedPtr< SRigVMEditorGraphExplorer > GetGraphExplorerWidget () override
virtual UObject * GetOuterForHost () const
virtual URigVMHost * GetRigVMHost () const override
TArray< TWeakObjectPtr< UObject > > GetSelectedObjects () const
TStatId GetStatId () const
bool & GetSuspendDetailsPanelRefreshFlag ()
TSharedRef< SBorder > GetToolbox ()
Get the toolbox hosting widget.
FName GetToolkitContextFName () const
FName GetToolkitFName () const
FText GetToolkitToolTipText () const
FLinearColor GetWorldCentricTabColorScale () const
FString GetWorldCentricTabPrefix () const
const TArray< TStrongObjectPtr< URigVMDetailsViewWrapperObject > > & GetWrapperObjects () const
void HandleAssetRequestClose (UObject *InObject, EAssetEditorCloseReason InReason)
void HandleAssetRequestedOpen (UObject *InObject)
void HandleBreakpointActionRequested (const ERigVMBreakpointAction BreakpointAction)
void HandleBreakpointAdded ()
FActionMenuContent HandleCreateGraphActionMenu (UEdGraph *InGraph, const FVector2f &InNodePosition, const TArray< UEdGraphPin * > &InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed)
Wraps the normal blueprint editor's action menu creation callback.
void HandleHideItem ()
Handle hiding items in the graph.
virtual void HandleModifiedEvent (ERigVMGraphNotifType InNotifType, URigVMGraph *InGraph, UObject *InSubject) override
virtual void HandleRefreshEditorFromBlueprint (URigVMBlueprint *InBlueprint)
void HandleSetObjectBeingDebugged (UObject *InObject)
void HandleShowCurrentStatement ()
void HandleVariableDroppedFromBlueprint (UObject *InSubject, FProperty *InVariableToDrop, const FVector2D &InDropPosition, const FVector2D &InScreenPosition)
virtual void HandleVMExecutedEvent (URigVMHost *InHost, const FName &InEventName)
void HandleVMExecutionHalted (const int32 InstructionIndex, UObject *InNode, const FName &InEntryName)
virtual bool InEditingMode () const override
void InitToolMenuContextImpl (FToolMenuContext &MenuContext)
bool IsAutoCompileGraphOn () const
bool IsDetailsPanelRefreshSuspended () const
bool IsEditingSingleBlueprint () const
bool IsHaltedAtBreakpoint () const
bool IsInAScriptingMode () const
bool IsNativeParentClassCodeLinkEnabled () const
bool IsSectionVisibleImpl (RigVMNodeSectionID::Type InSectionID) const
bool JumpToHyperlinkImpl (const UObject *ObjectReference, bool bRequestRename=false)
bool NewDocument_IsVisibleForTypeImpl (ECreatedDocumentType GraphType) const
void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged)
void NotifyPreChange (FProperty *PropertyAboutToChange)
bool OnActionMatchesName (FEdGraphSchemaAction *InAction, const FName &InName) const
void OnActiveTabChanged (TSharedPtr< SDockTab > PreviouslyActive, TSharedPtr< SDockTab > NewlyActivated)
virtual void OnAddNewLocalVariable () override
void OnBlueprintChangedImpl (UBlueprint *InBlueprint, bool bIsJustBeingCompiled)
void OnCreateComment ()
void OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList)
virtual FRigVMEditorClosed & OnEditorClosed () override
virtual void OnFinishedChangingProperties (const FPropertyChangedEvent &PropertyChangedEvent) override
delegate for changing property
void OnGraphEditorFocused (const TSharedRef< SGraphEditor > &InGraphEditor)
void OnGraphImported (UEdGraph *InEdGraph)
void OnGraphNodeClicked (URigVMEdGraphNode *InNode)
virtual bool OnlyShowCustomDebugObjects () const override
virtual void OnNewDocumentClicked (ECreatedDocumentType GraphType) override
void OnNodeDoubleClicked (URigVMBlueprint *InBlueprint, URigVMNode *InNode)
void OnNodeTitleCommitted (const FText &NewText, ETextCommit::Type CommitInfo, UEdGraphNode *NodeBeingChanged)
virtual void OnPasteNewLocalVariable (const FBPVariableDescription &VariableDescription) override
void OnPIEStopped (bool bSimulation)
virtual FPreviewHostUpdated & OnPreviewHostUpdated () override
void OnPropertyChanged (UObject *InObject, FPropertyChangedEvent &InEvent)
bool OnRequestBreakLinksDialog (TArray< URigVMLink * > InLinks)
FRigVMController_BulkEditResult OnRequestBulkEditDialog (URigVMBlueprint *InBlueprint, URigVMController *InController, URigVMLibraryNode *InFunction, ERigVMControllerBulkEditType InEditType)
void OnRequestLocalizeFunctionDialog (FRigVMGraphFunctionIdentifier &InFunction, URigVMController *InTargetController, IRigVMGraphFunctionHost *InTargetFunctionHost, bool bForce)
TRigVMTypeIndex OnRequestPinTypeSelectionDialog (const TArray< TRigVMTypeIndex > &InTypes)
void OnSelectedNodesChangedImpl (const TSet< class UObject * > &NewSelection)
FReply OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f &InPosition, UEdGraph *InGraph)
void OnToolkitHostingFinished (const TSharedRef< class IToolkit > &Toolkit)
void OnToolkitHostingStarted (const TSharedRef< class IToolkit > &Toolkit)
virtual void OnWrappedPropertyChangedChainEvent (URigVMDetailsViewWrapperObject *InWrapperObject, const FString &InPropertyPath, FPropertyChangedChainEvent &InPropertyChangedChainEvent)
void PostRedoImpl (bool bSuccess)
virtual void PostTransaction (bool bSuccess, const FTransaction *Transaction, bool bIsRedo)
void PostUndoImpl (bool bSuccess)
void RedoAction ()
Redo Action.
virtual void RefreshDetailView ()
bool ReparentBlueprint_IsVisible () const
void SaveAsset_Execute ()
void SaveAssetAs_Execute ()
virtual bool SelectLocalVariable (const UEdGraph *Graph, const FName &VariableName) override
virtual void SetDetailObjectFilter (TSharedPtr< FDetailsViewObjectFilter > InObjectFilter)
virtual void SetDetailObjects (const TArray< UObject * > &InObjects)
virtual void SetDetailObjects (const TArray< UObject * > &InObjects, bool bChangeUISelectionState)
void SetDetailViewForFocusedGraph ()
void SetDetailViewForGraph (URigVMGraph *InGraph)
void SetDetailViewForLocalVariable ()
void SetEventQueue (TArray< FName > InEventQueue)
virtual void SetEventQueue (TArray< FName > InEventQueue, bool bCompile)
void SetExecutionMode (const ERigVMEditorExecutionModeType InExecutionMode)
virtual void SetGraphExplorerWidget (TSharedPtr< SRigVMEditorGraphExplorer > InWidget) override
void SetHaltedNode (URigVMNode *Node)
void SetHost (URigVMHost *InHost)
void SetMemoryStorageDetails (const TArray< FRigVMMemoryStorageStruct * > &InStructs)
void SetupGraphEditorEvents (UEdGraph *InGraph, SGraphEditor::FGraphEditorEvents &InEvents)
bool ShouldLoadBPLibrariesFromAssetRegistry ()
bool ShouldOpenGraphByDefault () const
void SwapAssetReferences ()
void SwapFunctionAcrossProject ()
void SwapFunctionForAssets (const TArray< FAssetData > &InAssets, bool bSetupUndo)
void SwapFunctionWithinAsset ()
void Tick (float DeltaTime)
void ToggleAutoCompileGraph ()
void ToggleEventQueue ()
void ToggleExecutionMode ()
bool TransactionObjectAffectsBlueprintImpl (UObject *InTransactedObject)
UE_DEPRECATED (5.4, "Please use HandleVMCompiledEvent with ExtendedExecuteContext param.") virtual void HandleVMCompiledEvent(UObject *InCompiledObject
void UnbindEditor ()
void UndoAction ()
Undo Action.
bool UpdateDefaultValueForVariable (FBPVariableDescription &InVariable, bool bUseCDO)
void UpdateGraphCompilerErrors ()
Once the log is collected update the graph.
virtual void UpdateRigVMHost ()
Push a newly compiled/opened host to the editor.
virtual void UpdateRigVMHost_PreClearOldHost (URigVMHost *InPreviousHost)
void UpdateStaleWatchedPins ()
Update stale watch pins.
Protected Member Functions inherited from IRigVMEditor
virtual void AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode)=0
virtual void AddAutoCompileWidget (FToolBarBuilder &ToolbarBuilder)=0
virtual void AddCompileWidget (FToolBarBuilder &ToolbarBuilder)=0
virtual void AddMenuExtender (TSharedPtr< FExtender > Extender)=0
virtual void AddReferencedObjectsImpl (FReferenceCollector &Collector)=0
virtual void AddSelectedDebugObjectWidget (FToolBarBuilder &ToolbarBuilder)=0
virtual void AddSettingsAndDefaultWidget (FToolBarBuilder &ToolbarBuilder)=0
virtual void AddToolbarExtender (TSharedPtr< FExtender > Extender)=0
virtual void AnalyticsTrackNodeEvent (UBlueprint *Blueprint, UEdGraphNode *GraphNode, bool bNodeDelete=false) const =0
virtual void BringToolkitToFrontImpl ()=0
virtual void CloseDocumentTab (const UObject *DocumentID)=0
virtual void CommonInitialization (const TArray< UBlueprint * > &InitBlueprints, bool bShouldOpenInDefaultsMode)=0
virtual void CompileImpl ()=0
virtual void CreateDefaultCommands ()=0
virtual TSharedPtr< FApplicationMode > CreateEditorMode ()=0
virtual void CreateEditorToolbar ()=0
virtual TSharedRef< SGraphEditor > CreateGraphEditorWidget (TSharedRef< class FTabInfo > InTabInfo, class UEdGraph *InGraph)=0
virtual void EditClassDefaults_Clicked ()=0
virtual void EditGlobalOptions_Clicked ()=0
virtual bool FindOpenTabsContainingDocument (const UObject *DocumentID, TArray< TSharedPtr< SDockTab > > &Results)=0
virtual TSharedPtr< class IMessageLogListing > GetCompilerResultsListing ()=0
virtual UEdGraphPin * GetCurrentlySelectedPin () const =0
virtual TSharedPtr< FDocumentTracker > GetDocumentManager () const =0
virtual const TArray< UObject * > & GetEditingBlueprints () const =0
virtual const FName GetEditorAppName () const =0
virtual FGraphAppearanceInfo GetGraphAppearanceImpl (class UEdGraph *InGraph) const =0
virtual TWeakPtr< FDocumentTabFactory > GetGraphEditorTabFactory () const =0
virtual const TSharedPtr< FAssetEditorToolkit > GetHostingApp () const =0
virtual FEdGraphPinType GetLastPinTypeUsed ()=0
virtual FGraphPanelSelectionSet GetSelectedNodes () const =0
virtual FName GetSelectedVariableName ()=0
virtual FEditorModeTools & GetToolkitEditorModeManager () const =0
virtual const TSharedRef< IToolkitHost > GetToolkitHost () const =0
virtual void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())=0
virtual void InitToolMenuContext (FToolMenuContext &MenuContext)=0
virtual bool IsEditableImpl (UEdGraph *InGraph) const =0
virtual bool IsGraphInCurrentBlueprint (const UEdGraph *InGraph) const =0
virtual bool IsHosted () const =0
virtual bool IsNodeTitleVisible (const UEdGraphNode *Node, bool bRequestRename)=0
virtual void JumpToNode (const class UEdGraphNode *Node, bool bRequestRename=false)=0
virtual void JumpToPin (const class UEdGraphPin *Pin)=0
virtual void LogSimpleMessage (const FText &MessageText)=0
virtual void NotifyPostChangeImpl (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged)=0
virtual void NotifyPreChangeImpl (FProperty *PropertyAboutToChange)=0
virtual void OnBlueprintChangedInnerImpl (UBlueprint *InBlueprint, bool bIsJustBeingCompiled=false)=0
virtual FActionMenuContent OnCreateGraphActionMenu (UEdGraph *InGraph, const FVector2f &InNodePosition, const TArray< UEdGraphPin * > &InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed)=0
virtual void PostLayoutBlueprintEditorInitialization ()=0
virtual void PostRedo (bool bSuccess)=0
virtual void PostUndo (bool bSuccess)=0
virtual void RefreshEditorsImpl (ERefreshRigVMEditorReason::Type Reason=ERefreshRigVMEditorReason::UnknownReason)=0
virtual void RefreshInspector ()=0
virtual void RefreshStandAloneDefaultsEditor ()=0
virtual void RegenerateMenusAndToolbars ()=0
virtual void RegisterToolbarTab (const TSharedRef< class FTabManager > &TabManager)=0
virtual void RemoveMenuExtender (TSharedPtr< FExtender > Extender)=0
virtual void RemoveToolbarExtender (TSharedPtr< FExtender > Extender)=0
virtual void RenameNewlyAddedAction (FName InActionName)=0
virtual void RestoreEditedObjectState ()=0
virtual void SaveAsset_Execute_Impl ()=0
virtual void SaveAssetAs_Execute_Impl ()=0
virtual void SetCurrentMode (FName NewMode)=0
virtual void SetUISelectionState (FName SelectionOwner)=0
virtual void SetupGraphEditorEventsImpl (UEdGraph *InGraph, SGraphEditor::FGraphEditorEvents &InEvents)=0
virtual void SetupViewForBlueprintEditingMode ()=0
virtual TSharedRef< const IRigVMEditor > SharedRef () const =0
virtual TSharedRef< IRigVMEditor > SharedRef ()=0
virtual bool TransactionObjectAffectsBlueprint (UObject *InTransactedObject)=0
virtual void TryInvokingDetailsTab (bool bFlash=true)=0
Static Protected Member Functions
static FSlateIcon GetExecutionModeIcon (const ERigVMEditorExecutionModeType InExecutionMode)
static bool IsPIERunning ()
Returns true if PIE is currently running.
Protected Attributes
URigVMController * ActiveController
bool bAllowBulkEdits
bool bAnyErrorsLeft
bool bDetailsPanelRequiresClear
bool bIsCompilingThroughUI
Are we currently compiling through the user interface.
bool bIsSettingObjectBeingDebugged
bool bRequestedReopen = false
bool bRigVMEditorInitialized
bool bSuspendDetailsPanelRefresh
ERigVMEditorExecutionModeType ExecutionMode
TSharedPtr< SRigVMEditorGraphExplorer > GraphExplorerWidget
URigVMNode * HaltedAtNode
URigVM * InVM
TMap< FString, FString > KnownInstructionLimitWarnings
FString LastDebuggedHost
TArray< FName > LastEventQueue
TSharedPtr< FExtender > MenuExtender
The extender to pass to the level editor to extend it's window menu.
FOnRefreshEvent OnRefreshEvent
FPreviewHostUpdated PreviewHostUpdated
Our currently running rig vm instance.
FDelegateHandle PropertyChangedHandle
FRigVMEditorClosed RigVMEditorClosedDelegate
FRigVMLog RigVMLog
The log to use for errors resulting from the init phase of the units.
TSharedPtr< FExtender > ToolbarExtender
Toolbar extender.
TSharedPtr< SBorder > Toolbox
Toolbox hosting widget.
TArray< TStrongObjectPtr< URigVMDetailsViewWrapperObject > > WrapperObjects
Friends
class SRigVMEditorGraphExplorer
class SRigVMExecutionStackView
Additional Inherited Members
Public Types inherited from IRigVMEditor
enum ECreatedDocumentType {
CGT_NewVariable , CGT_NewFunctionGraph , CGT_NewMacroGraph , CGT_NewAnimationLayer ,
CGT_NewEventGraph , CGT_NewLocalVariable
}
Detailed Description
Definition at line 250 of file RigVMEditor.h.
Member Enumeration Documentation
ERigVMEditorExecutionModeType
enum FRigVMEditorBase::ERigVMEditorExecutionModeType protected
Enumerator
ERigVMEditorExecutionModeType_Release
ERigVMEditorExecutionModeType_Debug
Definition at line 401 of file RigVMEditor.h.
Constructor & Destructor Documentation
FRigVMEditorBase()
FRigVMEditorBase::FRigVMEditorBase () protected
Referenced by GetFromAssetEditorInstance().
~FRigVMEditorBase()
virtual FRigVMEditorBase::~FRigVMEditorBase () inline protected virtual
Definition at line 320 of file RigVMEditor.h.
Member Function Documentation
AddNewFunctionVariant()
virtual void FRigVMEditorBase::AddNewFunctionVariant (const UEdGraph * InOriginalFunction) override protected virtual
Implements IRigVMEditor.
AddReferencedObjects()
void FRigVMEditorBase::AddReferencedObjects (FReferenceCollector & Collector) protected
Referenced by FRigVMNewEditor::AddReferencedObjects().
AreDelegatesAllowed()
bool FRigVMEditorBase::AreDelegatesAllowed () const protected
AreEventGraphsAllowed()
bool FRigVMEditorBase::AreEventGraphsAllowed () const protected
AreMacrosAllowed()
bool FRigVMEditorBase::AreMacrosAllowed () const protected
BindCommands()
virtual void FRigVMEditorBase::BindCommands () protected virtual
BringToolkitToFront()
void FRigVMEditorBase::BringToolkitToFront () protected
CacheNameLists()
virtual void FRigVMEditorBase::CacheNameLists () protected virtual
Update the name lists for use in name combo boxes.
CanAddNewLocalVariable()
virtual bool FRigVMEditorBase::CanAddNewLocalVariable () const override protected virtual
Implements IRigVMEditor.
CanAutoCompileGraph()
bool FRigVMEditorBase::CanAutoCompileGraph () const inline protected
Definition at line 469 of file RigVMEditor.h.
CanCopyNodes()
bool FRigVMEditorBase::CanCopyNodes () const
CanCutNodes()
bool FRigVMEditorBase::CanCutNodes () const
CanDeleteNodes()
bool FRigVMEditorBase::CanDeleteNodes () const
CanDuplicateNodes()
bool FRigVMEditorBase::CanDuplicateNodes () const
CanHideItem()
bool FRigVMEditorBase::CanHideItem () const protected
CanPasteNodes()
bool FRigVMEditorBase::CanPasteNodes () const
CanStartWatchingPin()
bool FRigVMEditorBase::CanStartWatchingPin () const
CanStopWatchingPin()
bool FRigVMEditorBase::CanStopWatchingPin () const
ClearDetailObject()
void FRigVMEditorBase::ClearDetailObject (bool bChangeUISelectionState = true) protected
ClearDetailsViewWrapperObjects()
void FRigVMEditorBase::ClearDetailsViewWrapperObjects () protected
Compile()
void FRigVMEditorBase::Compile ()
Referenced by FRigVMNewEditor::Compile().
CopySelectedNodes()
void FRigVMEditorBase::CopySelectedNodes ()
CreateDefaultCommandsImpl()
void FRigVMEditorBase::CreateDefaultCommandsImpl () protected
CreateEmptyGraphContent()
virtual void FRigVMEditorBase::CreateEmptyGraphContent (URigVMController * InController) inline protected virtual
Definition at line 388 of file RigVMEditor.h.
CutSelectedNodes()
void FRigVMEditorBase::CutSelectedNodes ()
DeleteSelectedNodes()
void FRigVMEditorBase::DeleteSelectedNodes ()
DetailViewShowsAnyRigUnit()
bool FRigVMEditorBase::DetailViewShowsAnyRigUnit () const protected
DetailViewShowsLocalVariable()
bool FRigVMEditorBase::DetailViewShowsLocalVariable () const protected
DetailViewShowsStruct()
bool FRigVMEditorBase::DetailViewShowsStruct (UScriptStruct * InStruct) const protected
DuplicateNodes()
void FRigVMEditorBase::DuplicateNodes ()
ExtendMenu()
void FRigVMEditorBase::ExtendMenu () protected
Extend menu.
ExtendToolbar()
void FRigVMEditorBase::ExtendToolbar () protected
Extend toolbar.
FillToolbar()
virtual void FRigVMEditorBase::FillToolbar (FToolBarBuilder & ToolbarBuilder, bool bEndSection = true) protected virtual
Fill the toolbar with content.
FocusInspectorOnGraphSelection()
void FRigVMEditorBase::FocusInspectorOnGraphSelection (const TSet< class UObject * > & NewSelection, bool bForceRefresh = false) protected
ForceEditorRefresh()
virtual void FRigVMEditorBase::ForceEditorRefresh (ERefreshRigVMEditorReason::Type Reason = ERefreshRigVMEditorReason::UnknownReason) override protected virtual
Implements IRigVMEditor.
References ERefreshRigVMEditorReason::UnknownReason.
FrameSelection()
void FRigVMEditorBase::FrameSelection () protected
GenerateBulkEditMenu()
virtual FMenuBuilder FRigVMEditorBase::GenerateBulkEditMenu () protected virtual
GenerateBulkEditMenuContent()
TSharedRef< SWidget > FRigVMEditorBase::GenerateBulkEditMenuContent () protected
GenerateEventQueueMenuContent() [1/2]
TSharedRef< SWidget > FRigVMEditorBase::GenerateEventQueueMenuContent () protected
GenerateEventQueueMenuContent() [2/2]
virtual void FRigVMEditorBase::GenerateEventQueueMenuContent (FMenuBuilder & MenuBuilder) protected virtual
GenerateExecutionModeMenuContent()
TSharedRef< SWidget > FRigVMEditorBase::GenerateExecutionModeMenuContent () protected
GetBaseToolkitName()
FText FRigVMEditorBase::GetBaseToolkitName () const protected
GetBlueprintObj()
UBlueprint * FRigVMEditorBase::GetBlueprintObj () const protected
GetCustomDebugObjectLabel()
virtual FString FRigVMEditorBase::GetCustomDebugObjectLabel (UObject * ObjectBeingDebugged) const override protected virtual
Implements IRigVMEditor.
GetDebugObjects()
virtual void FRigVMEditorBase::GetDebugObjects (TArray< FRigVMCustomDebugObject > & DebugList) const override protected virtual
Implements IRigVMEditor.
GetDefaultEventQueue()
virtual TArray< FName > FRigVMEditorBase::GetDefaultEventQueue () const protected virtual
GetDefaultSchemaClass()
TSubclassOf< UEdGraphSchema > FRigVMEditorBase::GetDefaultSchemaClass () const protected
GetDetailWrapperClass()
virtual UClass * FRigVMEditorBase::GetDetailWrapperClass () const protected virtual
GetEditorModeName()
virtual const FName FRigVMEditorBase::GetEditorModeName () const protected virtual
GetEventQueue()
TArray< FName > FRigVMEditorBase::GetEventQueue () const protected
GetEventQueueComboValue()
virtual int32 FRigVMEditorBase::GetEventQueueComboValue () const inline protected virtual
Definition at line 527 of file RigVMEditor.h.
References INDEX_NONE.
GetEventQueueIcon() [1/2]
FSlateIcon FRigVMEditorBase::GetEventQueueIcon () const protected
GetEventQueueIcon() [2/2]
virtual FSlateIcon FRigVMEditorBase::GetEventQueueIcon (const TArray< FName > & InEventQueue) const protected virtual
GetEventQueueLabel()
virtual FText FRigVMEditorBase::GetEventQueueLabel () const inline protected virtual
Definition at line 528 of file RigVMEditor.h.
GetExecutionModeComboValue()
int32 FRigVMEditorBase::GetExecutionModeComboValue () const protected
GetExecutionModeIcon() [1/2]
FSlateIcon FRigVMEditorBase::GetExecutionModeIcon () const protected
GetExecutionModeIcon() [2/2]
FSlateIcon FRigVMEditorBase::GetExecutionModeIcon (const ERigVMEditorExecutionModeType InExecutionMode) static protected
GetExecutionModeLabel()
FText FRigVMEditorBase::GetExecutionModeLabel () const protected
GetFocusedController()
URigVMController * FRigVMEditorBase::GetFocusedController () const protected
GetFocusedModel()
virtual URigVMGraph * FRigVMEditorBase::GetFocusedModel () const override protected virtual
Implements IRigVMEditor.
GetFromAssetEditorInstance()
FRigVMEditorBase * FRigVMEditorBase::GetFromAssetEditorInstance (IAssetEditorInstance * Instance) static
References FRigVMEditorBase(), and Instance.
GetGraphAppearance()
FGraphAppearanceInfo FRigVMEditorBase::GetGraphAppearance (class UEdGraph * InGraph) const protected
GetGraphDecorationString()
FText FRigVMEditorBase::GetGraphDecorationString (UEdGraph * InGraph) const
GetGraphEditor()
TSharedPtr< SGraphEditor > FRigVMEditorBase::GetGraphEditor (UEdGraph * InEdGraph) const protected
GetGraphExplorerWidget()
virtual TSharedPtr< SRigVMEditorGraphExplorer > FRigVMEditorBase::GetGraphExplorerWidget () inline override protected virtual
Implements IRigVMEditor.
Definition at line 588 of file RigVMEditor.h.
References GraphExplorerWidget.
GetOuterForHost()
virtual UObject * FRigVMEditorBase::GetOuterForHost () const protected virtual
GetRigVMBlueprint()
virtual URigVMBlueprint * FRigVMEditorBase::GetRigVMBlueprint () const override virtual
Implements IRigVMEditor.
GetRigVMHost()
virtual URigVMHost * FRigVMEditorBase::GetRigVMHost () const override protected virtual
Implements IRigVMEditor.
GetSelectedObjects()
TArray< TWeakObjectPtr< UObject > > FRigVMEditorBase::GetSelectedObjects () const protected
GetStatId()
TStatId FRigVMEditorBase::GetStatId () const protected
GetSuspendDetailsPanelRefreshFlag()
bool & FRigVMEditorBase::GetSuspendDetailsPanelRefreshFlag () inline protected
Definition at line 491 of file RigVMEditor.h.
References bSuspendDetailsPanelRefresh.
GetToolbox()
TSharedRef< SBorder > FRigVMEditorBase::GetToolbox () inline protected
Get the toolbox hosting widget.
Definition at line 396 of file RigVMEditor.h.
References Toolbox.
GetToolkitContextFName()
FName FRigVMEditorBase::GetToolkitContextFName () const protected
GetToolkitFName()
FName FRigVMEditorBase::GetToolkitFName () const protected
GetToolkitToolTipText()
FText FRigVMEditorBase::GetToolkitToolTipText () const protected
GetVarIconAndColorFromPinType()
FSlateBrush const * FRigVMEditorBase::GetVarIconAndColorFromPinType (const FEdGraphPinType & PinType, FSlateColor & IconColorOut, FSlateBrush const *& SecondaryBrushOut, FSlateColor & SecondaryColorOut) static
Util for finding a glyph and color for a variable.
Parameters
PinType The variable's pin type
IconColorOut The resulting color for the glyph
SecondaryBrushOut The resulting secondary glyph brush (used for Map types)
SecondaryColorOut The resulting secondary color for the glyph (used for Map types)
Returns
The resulting glyph brush
GetVarIconAndColorFromProperty()
FSlateBrush const * FRigVMEditorBase::GetVarIconAndColorFromProperty (const FProperty * Property, FSlateColor & IconColorOut, FSlateBrush const *& SecondaryBrushOut, FSlateColor & SecondaryColorOut) static
Util for finding a glyph and color for a variable.
Parameters
Property The variable's property
IconColorOut The resulting color for the glyph
SecondaryBrushOut The resulting secondary glyph brush (used for Map types)
SecondaryColorOut The resulting secondary color for the glyph (used for Map types)
Returns
The resulting glyph brush
References Property.
Referenced by SRigVMActionMenu::OnCreateWidgetForAction().
GetWorldCentricTabColorScale()
FLinearColor FRigVMEditorBase::GetWorldCentricTabColorScale () const protected
Referenced by FRigVMNewEditor::GetWorldCentricTabColorScale().
GetWorldCentricTabPrefix()
FString FRigVMEditorBase::GetWorldCentricTabPrefix () const protected
GetWrapperObjects()
const TArray< TStrongObjectPtr< URigVMDetailsViewWrapperObject > > & FRigVMEditorBase::GetWrapperObjects () const inline protected
Definition at line 506 of file RigVMEditor.h.
References WrapperObjects.
HandleAssetRequestClose()
void FRigVMEditorBase::HandleAssetRequestClose (UObject * InObject, EAssetEditorCloseReason InReason) protected
HandleAssetRequestedOpen()
void FRigVMEditorBase::HandleAssetRequestedOpen (UObject * InObject) protected
HandleBreakpointActionRequested()
void FRigVMEditorBase::HandleBreakpointActionRequested (const ERigVMBreakpointAction BreakpointAction) protected
HandleBreakpointAdded()
void FRigVMEditorBase::HandleBreakpointAdded () protected
HandleCreateGraphActionMenu()
FActionMenuContent FRigVMEditorBase::HandleCreateGraphActionMenu (UEdGraph * InGraph, const FVector2f & InNodePosition, const TArray< UEdGraphPin * > & InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed) protected
Wraps the normal blueprint editor's action menu creation callback.
References SGraphEditor::FActionMenuClosed.
HandleHideItem()
void FRigVMEditorBase::HandleHideItem () protected
Handle hiding items in the graph.
HandleJumpToHyperlink()
void FRigVMEditorBase::HandleJumpToHyperlink (const UObject * InSubject)
HandleModifiedEvent()
virtual void FRigVMEditorBase::HandleModifiedEvent (ERigVMGraphNotifType InNotifType, URigVMGraph * InGraph, UObject * InSubject) override protected virtual
Implements IRigVMEditor.
HandleRefreshEditorFromBlueprint()
virtual void FRigVMEditorBase::HandleRefreshEditorFromBlueprint (URigVMBlueprint * InBlueprint) protected virtual
HandleSetObjectBeingDebugged()
void FRigVMEditorBase::HandleSetObjectBeingDebugged (UObject * InObject) protected
Referenced by FRigVMNewEditor::HandleSetObjectBeingDebugged().
HandleShowCurrentStatement()
void FRigVMEditorBase::HandleShowCurrentStatement () protected
HandleVariableDroppedFromBlueprint()
void FRigVMEditorBase::HandleVariableDroppedFromBlueprint (UObject * InSubject, FProperty * InVariableToDrop, const FVector2D & InDropPosition, const FVector2D & InScreenPosition) protected
HandleVMExecutedEvent()
virtual void FRigVMEditorBase::HandleVMExecutedEvent (URigVMHost * InHost, const FName & InEventName) protected virtual
HandleVMExecutionHalted()
void FRigVMEditorBase::HandleVMExecutionHalted (const int32 InstructionIndex, UObject * InNode, const FName & InEntryName) protected
InEditingMode()
virtual bool FRigVMEditorBase::InEditingMode () const override protected virtual
Implements IRigVMEditor.
InitRigVMEditor()
virtual void FRigVMEditorBase::InitRigVMEditor (const EToolkitMode::Type Mode, const TSharedPtr< class IToolkitHost > & InitToolkitHost, class URigVMBlueprint * InRigVMBlueprint) virtual
Edits the specified asset(s)
Parameters
Mode Mode that this editor should operate in
InitToolkitHost When Mode is WorldCentric, this is the level editor instance to spawn this editor within
InRigVMBlueprint The blueprint object to start editing.
InitToolMenuContextImpl()
void FRigVMEditorBase::InitToolMenuContextImpl (FToolMenuContext & MenuContext) protected
IsAutoCompileGraphOn()
bool FRigVMEditorBase::IsAutoCompileGraphOn () const protected
IsCompilingEnabled()
bool FRigVMEditorBase::IsCompilingEnabled () const
IsDetailsPanelRefreshSuspended()
bool FRigVMEditorBase::IsDetailsPanelRefreshSuspended () const inline protected
Definition at line 490 of file RigVMEditor.h.
References bSuspendDetailsPanelRefresh.
IsEditable()
virtual bool FRigVMEditorBase::IsEditable (UEdGraph * InGraph) const override virtual
Implements IRigVMEditor.
IsEditingSingleBlueprint()
bool FRigVMEditorBase::IsEditingSingleBlueprint () const protected
IsHaltedAtBreakpoint()
bool FRigVMEditorBase::IsHaltedAtBreakpoint () const protected
IsInAScriptingMode()
bool FRigVMEditorBase::IsInAScriptingMode () const inline protected
Definition at line 413 of file RigVMEditor.h.
IsNativeParentClassCodeLinkEnabled()
bool FRigVMEditorBase::IsNativeParentClassCodeLinkEnabled () const inline protected
Definition at line 357 of file RigVMEditor.h.
IsPIERunning()
bool FRigVMEditorBase::IsPIERunning () static protected
Returns true if PIE is currently running.
IsSectionVisibleImpl()
bool FRigVMEditorBase::IsSectionVisibleImpl (RigVMNodeSectionID::Type InSectionID) const protected
JumpToHyperlinkImpl()
bool FRigVMEditorBase::JumpToHyperlinkImpl (const UObject * ObjectReference, bool bRequestRename = false) protected
References ObjectReference.
NewDocument_IsVisibleForTypeImpl()
bool FRigVMEditorBase::NewDocument_IsVisibleForTypeImpl (ECreatedDocumentType GraphType) const protected
NotifyPostChange()
void FRigVMEditorBase::NotifyPostChange (const FPropertyChangedEvent & PropertyChangedEvent, FProperty * PropertyThatChanged) protected
NotifyPreChange()
void FRigVMEditorBase::NotifyPreChange (FProperty * PropertyAboutToChange) protected
OnActionMatchesName()
bool FRigVMEditorBase::OnActionMatchesName (FEdGraphSchemaAction * InAction, const FName & InName) const protected
References InName.
OnActiveTabChanged()
void FRigVMEditorBase::OnActiveTabChanged (TSharedPtr< SDockTab > PreviouslyActive, TSharedPtr< SDockTab > NewlyActivated) protected
OnAddNewLocalVariable()
virtual void FRigVMEditorBase::OnAddNewLocalVariable () override protected virtual
Implements IRigVMEditor.
OnBlueprintChangedImpl()
void FRigVMEditorBase::OnBlueprintChangedImpl (UBlueprint * InBlueprint, bool bIsJustBeingCompiled) protected
OnCreateComment()
void FRigVMEditorBase::OnCreateComment () protected
OnCreateGraphEditorCommands()
void FRigVMEditorBase::OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList) protected
Referenced by FRigVMNewEditor::OnCreateGraphEditorCommands().
OnEditorClosed()
virtual FRigVMEditorClosed & FRigVMEditorBase::OnEditorClosed () inline override protected virtual
Implements IRigVMEditor.
Definition at line 392 of file RigVMEditor.h.
References RigVMEditorClosedDelegate.
OnFinishedChangingProperties()
virtual void FRigVMEditorBase::OnFinishedChangingProperties (const FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
delegate for changing property
Implements IRigVMEditor.
Reimplemented in FRigVMNewEditor.
Referenced by FRigVMNewEditor::OnFinishedChangingProperties().
OnGraphEditorFocused()
void FRigVMEditorBase::OnGraphEditorFocused (const TSharedRef< SGraphEditor > & InGraphEditor) protected
OnGraphImported()
void FRigVMEditorBase::OnGraphImported (UEdGraph * InEdGraph) protected
OnGraphNodeClicked()
void FRigVMEditorBase::OnGraphNodeClicked (URigVMEdGraphNode * InNode) protected
OnGraphNodeDropToPerform()
virtual void FRigVMEditorBase::OnGraphNodeDropToPerform (TSharedPtr< FDragDropOperation > InDragDropOp, UEdGraph * InGraph, const FVector2f & InNodePosition, const FVector2f & InScreenPosition) override virtual
Implements IRigVMEditor.
OnlyShowCustomDebugObjects()
virtual bool FRigVMEditorBase::OnlyShowCustomDebugObjects () const inline override protected virtual
Implements IRigVMEditor.
Definition at line 539 of file RigVMEditor.h.
OnNewDocumentClicked()
virtual void FRigVMEditorBase::OnNewDocumentClicked (ECreatedDocumentType GraphType) override protected virtual
Implements IRigVMEditor.
OnNodeDoubleClicked()
void FRigVMEditorBase::OnNodeDoubleClicked (URigVMBlueprint * InBlueprint, URigVMNode * InNode) protected
OnNodeTitleCommitted()
void FRigVMEditorBase::OnNodeTitleCommitted (const FText & NewText, ETextCommit::Type CommitInfo, UEdGraphNode * NodeBeingChanged) protected
OnPasteNewLocalVariable()
virtual void FRigVMEditorBase::OnPasteNewLocalVariable (const FBPVariableDescription & VariableDescription) override protected virtual
Implements IRigVMEditor.
OnPIEStopped()
void FRigVMEditorBase::OnPIEStopped (bool bSimulation) protected
OnPreviewHostUpdated()
virtual FPreviewHostUpdated & FRigVMEditorBase::OnPreviewHostUpdated () inline override protected virtual
Implements IRigVMEditor.
Definition at line 390 of file RigVMEditor.h.
References PreviewHostUpdated.
OnPropertyChanged()
void FRigVMEditorBase::OnPropertyChanged (UObject * InObject, FPropertyChangedEvent & InEvent) protected
OnRefresh()
virtual FOnRefreshEvent FRigVMEditorBase::OnRefresh () inline override virtual
Implements IRigVMEditor.
Definition at line 288 of file RigVMEditor.h.
References OnRefreshEvent.
OnRequestBreakLinksDialog()
bool FRigVMEditorBase::OnRequestBreakLinksDialog (TArray< URigVMLink * > InLinks) protected
OnRequestBulkEditDialog()
FRigVMController_BulkEditResult FRigVMEditorBase::OnRequestBulkEditDialog (URigVMBlueprint * InBlueprint, URigVMController * InController, URigVMLibraryNode * InFunction, ERigVMControllerBulkEditType InEditType) protected
OnRequestLocalizeFunctionDialog()
void FRigVMEditorBase::OnRequestLocalizeFunctionDialog (FRigVMGraphFunctionIdentifier & InFunction, URigVMController * InTargetController, IRigVMGraphFunctionHost * InTargetFunctionHost, bool bForce) protected
OnRequestPinTypeSelectionDialog()
TRigVMTypeIndex FRigVMEditorBase::OnRequestPinTypeSelectionDialog (const TArray< TRigVMTypeIndex > & InTypes) protected
OnSelectedNodesChangedImpl()
void FRigVMEditorBase::OnSelectedNodesChangedImpl (const TSet< class UObject * > & NewSelection) protected
OnSpawnGraphNodeByShortcut()
FReply FRigVMEditorBase::OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f & InPosition, UEdGraph * InGraph) protected
Referenced by FRigVMNewEditor::OnSpawnGraphNodeByShortcut().
OnStartWatchingPin()
void FRigVMEditorBase::OnStartWatchingPin ()
OnStopWatchingPin()
void FRigVMEditorBase::OnStopWatchingPin ()
OnToolkitHostingFinished()
void FRigVMEditorBase::OnToolkitHostingFinished (const TSharedRef< class IToolkit > & Toolkit) protected
OnToolkitHostingStarted()
void FRigVMEditorBase::OnToolkitHostingStarted (const TSharedRef< class IToolkit > & Toolkit) protected
OnWrappedPropertyChangedChainEvent()
virtual void FRigVMEditorBase::OnWrappedPropertyChangedChainEvent (URigVMDetailsViewWrapperObject * InWrapperObject, const FString & InPropertyPath, FPropertyChangedChainEvent & InPropertyChangedChainEvent) protected virtual
PasteNodes()
void FRigVMEditorBase::PasteNodes ()
PostRedoImpl()
void FRigVMEditorBase::PostRedoImpl (bool bSuccess) protected
PostTransaction()
virtual void FRigVMEditorBase::PostTransaction (bool bSuccess, const FTransaction * Transaction, bool bIsRedo) protected virtual
PostUndoImpl()
void FRigVMEditorBase::PostUndoImpl (bool bSuccess) protected
RedoAction()
void FRigVMEditorBase::RedoAction () protected
Redo Action.
RefreshDetailView()
virtual void FRigVMEditorBase::RefreshDetailView () protected virtual
ReparentBlueprint_IsVisible()
bool FRigVMEditorBase::ReparentBlueprint_IsVisible () const inline protected
Definition at line 358 of file RigVMEditor.h.
SaveAsset_Execute()
void FRigVMEditorBase::SaveAsset_Execute () protected
SaveAssetAs_Execute()
void FRigVMEditorBase::SaveAssetAs_Execute () protected
SelectLocalVariable()
virtual bool FRigVMEditorBase::SelectLocalVariable (const UEdGraph * Graph, const FName & VariableName) override protected virtual
Implements IRigVMEditor.
SetDetailObjectFilter()
virtual void FRigVMEditorBase::SetDetailObjectFilter (TSharedPtr< FDetailsViewObjectFilter > InObjectFilter) protected virtual
SetDetailObjects() [1/2]
virtual void FRigVMEditorBase::SetDetailObjects (const TArray< UObject * > & InObjects) protected virtual
SetDetailObjects() [2/2]
virtual void FRigVMEditorBase::SetDetailObjects (const TArray< UObject * > & InObjects, bool bChangeUISelectionState) protected virtual
SetDetailViewForFocusedGraph()
void FRigVMEditorBase::SetDetailViewForFocusedGraph () protected
SetDetailViewForGraph()
void FRigVMEditorBase::SetDetailViewForGraph (URigVMGraph * InGraph) protected
SetDetailViewForLocalVariable()
void FRigVMEditorBase::SetDetailViewForLocalVariable () protected
SetEventQueue() [1/2]
void FRigVMEditorBase::SetEventQueue (TArray< FName > InEventQueue) protected
SetEventQueue() [2/2]
virtual void FRigVMEditorBase::SetEventQueue (TArray< FName > InEventQueue, bool bCompile) protected virtual
SetExecutionMode()
void FRigVMEditorBase::SetExecutionMode (const ERigVMEditorExecutionModeType InExecutionMode) protected
SetGraphExplorerWidget()
virtual void FRigVMEditorBase::SetGraphExplorerWidget (TSharedPtr< SRigVMEditorGraphExplorer > InWidget) inline override protected virtual
Implements IRigVMEditor.
Definition at line 587 of file RigVMEditor.h.
References GraphExplorerWidget.
SetHaltedNode()
void FRigVMEditorBase::SetHaltedNode (URigVMNode * Node) protected
SetHost()
void FRigVMEditorBase::SetHost (URigVMHost * InHost) protected
SetMemoryStorageDetails()
void FRigVMEditorBase::SetMemoryStorageDetails (const TArray< FRigVMMemoryStorageStruct * > & InStructs) protected
SetupGraphEditorEvents()
void FRigVMEditorBase::SetupGraphEditorEvents (UEdGraph * InGraph, SGraphEditor::FGraphEditorEvents & InEvents) protected
ShouldLoadBPLibrariesFromAssetRegistry()
bool FRigVMEditorBase::ShouldLoadBPLibrariesFromAssetRegistry () inline protected
Definition at line 360 of file RigVMEditor.h.
ShouldOpenGraphByDefault()
bool FRigVMEditorBase::ShouldOpenGraphByDefault () const inline protected
Definition at line 362 of file RigVMEditor.h.
Referenced by FRigVMNewEditor::ShouldOpenGraphByDefault().
SwapAssetReferences()
void FRigVMEditorBase::SwapAssetReferences () protected
SwapFunctionAcrossProject()
void FRigVMEditorBase::SwapFunctionAcrossProject () protected
SwapFunctionForAssets()
void FRigVMEditorBase::SwapFunctionForAssets (const TArray< FAssetData > & InAssets, bool bSetupUndo) protected
SwapFunctionWithinAsset()
void FRigVMEditorBase::SwapFunctionWithinAsset () protected
Tick()
void FRigVMEditorBase::Tick (float DeltaTime) protected
References DeltaTime.
ToggleAutoCompileGraph()
void FRigVMEditorBase::ToggleAutoCompileGraph () protected
ToggleEventQueue()
void FRigVMEditorBase::ToggleEventQueue () protected
ToggleExecutionMode()
void FRigVMEditorBase::ToggleExecutionMode () protected
TransactionObjectAffectsBlueprintImpl()
bool FRigVMEditorBase::TransactionObjectAffectsBlueprintImpl (UObject * InTransactedObject) protected
UE_DEPRECATED()
FRigVMEditorBase::UE_DEPRECATED (5. 4, "Please use HandleVMCompiledEvent with ExtendedExecuteContext param.") protected
UnbindEditor()
void FRigVMEditorBase::UnbindEditor () protected
UndoAction()
void FRigVMEditorBase::UndoAction () protected
Undo Action.
UpdateDefaultValueForVariable()
bool FRigVMEditorBase::UpdateDefaultValueForVariable (FBPVariableDescription & InVariable, bool bUseCDO) protected
UpdateGraphCompilerErrors()
void FRigVMEditorBase::UpdateGraphCompilerErrors () protected
Once the log is collected update the graph.
UpdateRigVMHost()
virtual void FRigVMEditorBase::UpdateRigVMHost () protected virtual
Push a newly compiled/opened host to the editor.
UpdateRigVMHost_PreClearOldHost()
virtual void FRigVMEditorBase::UpdateRigVMHost_PreClearOldHost (URigVMHost * InPreviousHost) inline protected virtual
Definition at line 457 of file RigVMEditor.h.
UpdateStaleWatchedPins()
void FRigVMEditorBase::UpdateStaleWatchedPins () protected
Update stale watch pins.
Friends And Related Symbol Documentation
SRigVMEditorGraphExplorer
friend class SRigVMEditorGraphExplorer friend
Definition at line 628 of file RigVMEditor.h.
References SRigVMEditorGraphExplorer.
Referenced by SRigVMEditorGraphExplorer.
SRigVMExecutionStackView
friend class SRigVMExecutionStackView friend
Definition at line 627 of file RigVMEditor.h.
References SRigVMExecutionStackView.
Referenced by SRigVMExecutionStackView.
Field Documentation
ActiveController
URigVMController* FRigVMEditorBase::ActiveController protected
Definition at line 453 of file RigVMEditor.h.
bAllowBulkEdits
bool FRigVMEditorBase::bAllowBulkEdits protected
Definition at line 600 of file RigVMEditor.h.
bAnyErrorsLeft
bool FRigVMEditorBase::bAnyErrorsLeft protected
Definition at line 593 of file RigVMEditor.h.
bDetailsPanelRequiresClear
bool FRigVMEditorBase::bDetailsPanelRequiresClear protected
Definition at line 599 of file RigVMEditor.h.
bIsCompilingThroughUI
bool FRigVMEditorBase::bIsCompilingThroughUI protected
Are we currently compiling through the user interface.
Definition at line 606 of file RigVMEditor.h.
bIsSettingObjectBeingDebugged
bool FRigVMEditorBase::bIsSettingObjectBeingDebugged protected
Definition at line 601 of file RigVMEditor.h.
bRequestedReopen
bool FRigVMEditorBase::bRequestedReopen = false protected
Definition at line 327 of file RigVMEditor.h.
bRigVMEditorInitialized
bool FRigVMEditorBase::bRigVMEditorInitialized protected
Definition at line 603 of file RigVMEditor.h.
bSuspendDetailsPanelRefresh
bool FRigVMEditorBase::bSuspendDetailsPanelRefresh protected
Definition at line 598 of file RigVMEditor.h.
Referenced by GetSuspendDetailsPanelRefreshFlag(), and IsDetailsPanelRefreshSuspended().
ExecutionMode
ERigVMEditorExecutionModeType FRigVMEditorBase::ExecutionMode protected
Definition at line 610 of file RigVMEditor.h.
GraphExplorerWidget
TSharedPtr<SRigVMEditorGraphExplorer> FRigVMEditorBase::GraphExplorerWidget protected
Definition at line 583 of file RigVMEditor.h.
Referenced by GetGraphExplorerWidget(), and SetGraphExplorerWidget().
HaltedAtNode
URigVMNode* FRigVMEditorBase::HaltedAtNode protected
Definition at line 595 of file RigVMEditor.h.
InVM
URigVM* FRigVMEditorBase::InVM protected
Initial value:
{}
    virtual void HandleVMCompiledEvent(UObject* InCompiledObject, URigVM* InVM, FRigVMExtendedExecuteContext& InContext)
Definition at line 433 of file RigVMEditor.h.
KnownInstructionLimitWarnings
TMap<FString, FString> FRigVMEditorBase::KnownInstructionLimitWarnings protected
Definition at line 594 of file RigVMEditor.h.
LastDebuggedHost
FString FRigVMEditorBase::LastDebuggedHost protected
Definition at line 596 of file RigVMEditor.h.
LastEventQueue
TArray<FName> FRigVMEditorBase::LastEventQueue protected
Definition at line 615 of file RigVMEditor.h.
MenuExtender
TSharedPtr<FExtender> FRigVMEditorBase::MenuExtender protected
The extender to pass to the level editor to extend it's window menu.
Definition at line 618 of file RigVMEditor.h.
OnRefreshEvent
FOnRefreshEvent FRigVMEditorBase::OnRefreshEvent protected
Definition at line 625 of file RigVMEditor.h.
Referenced by OnRefresh().
PreviewHostUpdated
FPreviewHostUpdated FRigVMEditorBase::PreviewHostUpdated protected
Our currently running rig vm instance.
Definition at line 578 of file RigVMEditor.h.
Referenced by OnPreviewHostUpdated().
PropertyChangedHandle
FDelegateHandle FRigVMEditorBase::PropertyChangedHandle protected
Definition at line 623 of file RigVMEditor.h.
RigVMEditorClosedDelegate
FRigVMEditorClosed FRigVMEditorBase::RigVMEditorClosedDelegate protected
Definition at line 585 of file RigVMEditor.h.
Referenced by OnEditorClosed().
RigVMLog
FRigVMLog FRigVMEditorBase::RigVMLog protected
The log to use for errors resulting from the init phase of the units.
Definition at line 613 of file RigVMEditor.h.
ToolbarExtender
TSharedPtr<FExtender> FRigVMEditorBase::ToolbarExtender protected
Toolbar extender.
Definition at line 621 of file RigVMEditor.h.
Toolbox
TSharedPtr<SBorder> FRigVMEditorBase::Toolbox protected
Toolbox hosting widget.
Definition at line 581 of file RigVMEditor.h.
Referenced by GetToolbox().
WrapperObjects
TArray<TStrongObjectPtr<URigVMDetailsViewWrapperObject> > FRigVMEditorBase::WrapperObjects protected
Definition at line 608 of file RigVMEditor.h.
Referenced by GetWrapperObjects().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Editor/RigVMEditor.h