Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolEditorSelection Class Reference
UE::SequenceNavigator::FNavigationToolEditorSelection Class Reference
#include "NavigationToolEditorSelection.h"
Public Member Functions
FNavigationToolEditorSelection (FEditorModeTools &InModeTools, UObject *InChangedSelection=nullptr)
UObject * GetChangedSelection () const
template<typename InObjectType = UObject, ENavigationToolSelectionSource InSource = ENavigationToolSelectionSource::All, typename InObjectReturnType = InObjectType, typename = TDerivesFromUObject<InObjectType>, typename = TDerivesFromUObject<InObjectType, InObjectReturnType>>
TArray< InObjectReturnType * > GetSelectedObjects () const
template<typename InObjectType = UObject, typename = TDerivesFromUObject<InObjectType>>
USelection * GetSelection () const
Retrieves the USelection object closest to Object Type.
bool IsValid () const
Determines this Selection valid either if there's either no Changed Selection (i.e.
Private Types
template<typename InObjectType, typename InParentObjectType = UObject>
using TDerivesFromUObject = typename TEnableIf<TIsDerivedFrom<InObjectType, InParentObjectType>::Value>::Type
Private Member Functions
template<typename InElementType>
TArray< InElementType > GetSelectedObjects (USelection *InSelection) const
Private Attributes
TWeakObjectPtr< UObject > ChangedSelectionWeak
The Selection that changed that triggered this FNavigationToolEditorSelection to be instanced.
FEditorModeTools & ModeTools
The Mode Tools used to get the USelection instances.
Detailed Description
Definition at line 26 of file NavigationToolEditorSelection.h.
Member Typedef Documentation
TDerivesFromUObject
template<typename InObjectType, typename InParentObjectType = UObject> using UE::SequenceNavigator::FNavigationToolEditorSelection::TDerivesFromUObject = typename TEnableIf<TIsDerivedFrom<InObjectType, InParentObjectType>::Value>::Type private
Definition at line 29 of file NavigationToolEditorSelection.h.
Constructor & Destructor Documentation
FNavigationToolEditorSelection()
UE::SequenceNavigator::FNavigationToolEditorSelection::FNavigationToolEditorSelection (FEditorModeTools & InModeTools, UObject * InChangedSelection = nullptr) inline
Definition at line 32 of file NavigationToolEditorSelection.h.
References ChangedSelectionWeak, and ModeTools.
Member Function Documentation
GetChangedSelection()
UObject * UE::SequenceNavigator::FNavigationToolEditorSelection::GetChangedSelection () const inline
Definition at line 49 of file NavigationToolEditorSelection.h.
References ChangedSelectionWeak.
GetSelectedObjects() [1/2]
template<typename InObjectType = UObject, ENavigationToolSelectionSource InSource = ENavigationToolSelectionSource::All, typename InObjectReturnType = InObjectType, typename = TDerivesFromUObject<InObjectType>, typename = TDerivesFromUObject<InObjectType, InObjectReturnType>> TArray< InObjectReturnType * > UE::SequenceNavigator::FNavigationToolEditorSelection::GetSelectedObjects () const inline
Definition at line 73 of file NavigationToolEditorSelection.h.
References UE::SequenceNavigator::All, TArray< InElementType, InAllocatorType >::Append(), GetSelectedObjects(), GetSelection(), and UE::SequenceNavigator::Single.
Referenced by GetSelectedObjects().
GetSelectedObjects() [2/2]
template<typename InElementType> TArray< InElementType > UE::SequenceNavigator::FNavigationToolEditorSelection::GetSelectedObjects (USelection * InSelection) const inline private
Definition at line 93 of file NavigationToolEditorSelection.h.
References ensure.
GetSelection()
template<typename InObjectType = UObject, typename = TDerivesFromUObject<InObjectType>> USelection * UE::SequenceNavigator::FNavigationToolEditorSelection::GetSelection () const inline
Retrieves the USelection object closest to Object Type.
Definition at line 53 of file NavigationToolEditorSelection.h.
References ModeTools, and TIsDerivedFrom< DerivedType, BaseType >::Value.
Referenced by GetSelectedObjects().
IsValid()
bool UE::SequenceNavigator::FNavigationToolEditorSelection::IsValid () const inline
Determines this Selection valid either if there's either no Changed Selection (i.e.
just handling Mode Tools) or the given Selection Object is one of the 3 in the given Editor Mode Tools
Definition at line 41 of file NavigationToolEditorSelection.h.
References ChangedSelectionWeak, and ModeTools.
Field Documentation
ChangedSelectionWeak
TWeakObjectPtr<UObject> UE::SequenceNavigator::FNavigationToolEditorSelection::ChangedSelectionWeak private
The Selection that changed that triggered this FNavigationToolEditorSelection to be instanced.
Can be null if nothing changed.
Definition at line 108 of file NavigationToolEditorSelection.h.
Referenced by FNavigationToolEditorSelection(), GetChangedSelection(), and IsValid().
ModeTools
FEditorModeTools& UE::SequenceNavigator::FNavigationToolEditorSelection::ModeTools private
The Mode Tools used to get the USelection instances.
Definition at line 105 of file NavigationToolEditorSelection.h.
Referenced by FNavigationToolEditorSelection(), GetSelection(), and IsValid().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/NavigationToolEditorSelection.h