Unreal Engine 5.6 C++ API: UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable > Class Template Reference
UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable > Class Template Reference
#include "TaskPrivate.h"
Public Member Functions
virtual void ExecuteTask () override final
Public Member Functions inherited from UE::Tasks::Private::TTaskWithResult< ResultType >
ResultType & GetResult ()
Public Member Functions inherited from UE::Tasks::Private::FTaskBase
void AddNested (FTaskBase &Nested)
template<typename HigherLevelTaskType, decltype(std::declval< HigherLevelTaskType >().Pimpl) * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites)
bool AddPrerequisites (FTaskBase &Prerequisite)
void AddRef ()
bool AddSubsequent (FTaskBase &Subsequent)
EExtendedTaskPriority GetExtendedPriority () const
FPipe * GetPipe () const
ETaskPriority GetPriority () const
uint32 GetRefCount (std::memory_order MemoryOrder=std::memory_order_relaxed) const
TaskTrace::FId GetTraceId () const
bool IsAwaitable () const
bool IsCompleted () const
bool IsNamedThreadTask () const
void Release ()
void ReleaseInternalReference ()
void SetPipe (FPipe &InPipe)
bool TryLaunch (uint64 TaskSize)
bool TryRetractAndExecute (FTimeout Timeout, uint32 RecursionDepth=0)
template<typename ConditionType>
UE_DEPRECATED (5.5, "This method will be removed.") bool BusyWait(ConditionType &&Condition)
UE_DEPRECATED (5.5, "Use Wait instead") bool BusyWait(FTimeout Timeout)
void Wait ()
bool Wait (FTimeout Timeout)
void WaitWithNamedThreadsSupport ()
Protected Member Functions
TExecutableTaskBase (const TCHAR *InDebugName, TaskBodyType &&TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
Protected Member Functions inherited from UE::Tasks::Private::TTaskWithResult< ResultType >
TTaskWithResult (const TCHAR *InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, uint32 InitRefCount, ETaskFlags Flags)
virtual ~TTaskWithResult () override
Protected Member Functions inherited from UE::Tasks::Private::FTaskBase
FTaskBase (uint32 InitRefCount, bool bUnlockPrerequisites=true)
virtual ~FTaskBase ()
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites, bool bLockPrerequisite)
void ClearPipe ()
void Close ()
void Init (const TCHAR *InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
bool TryExecuteTask ()
void UnlockPrerequisites ()
Private Member Functions
UE_NONCOPYABLE (TExecutableTaskBase)
Private Attributes
TTypeCompatibleBytes< TaskBodyType > TaskBodyStorage
Additional Inherited Members
Protected Attributes inherited from UE::Tasks::Private::TTaskWithResult< ResultType >
TTypeCompatibleBytes< ResultType > ResultStorage
Detailed Description
template<typename TaskBodyType, typename ResultType = TInvokeResult_T<TaskBodyType>, typename Enable = void>
class UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >
Definition at line 868 of file TaskPrivate.h.
Constructor & Destructor Documentation
TExecutableTaskBase()
template<typename TaskBodyType, typename ResultType = TInvokeResult_T<TaskBodyType>, typename Enable = void> UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::TExecutableTaskBase (const TCHAR * InDebugName, TaskBodyType && TaskBody, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags) inline protected
Definition at line 882 of file TaskPrivate.h.
References UE::Tasks::Private::TTaskWithResult< ResultType >::TTaskWithResult(), Flags, MoveTemp(), and TaskBodyStorage.
Referenced by UE::Tasks::Private::TExecutableTask< TaskBodyType >::TExecutableTask(), and UE_NONCOPYABLE().
Member Function Documentation
ExecuteTask()
template<typename TaskBodyType, typename ResultType = TInvokeResult_T<TaskBodyType>, typename Enable = void> virtual void UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::ExecuteTask () inline final override virtual
Implements UE::Tasks::Private::FTaskBase.
Definition at line 873 of file TaskPrivate.h.
References DestructItem(), Invoke(), UE::Tasks::Private::TTaskWithResult< ResultType >::ResultStorage, and TaskBodyStorage.
UE_NONCOPYABLE()
template<typename TaskBodyType, typename ResultType = TInvokeResult_T<TaskBodyType>, typename Enable = void> UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::UE_NONCOPYABLE (TExecutableTaskBase< TaskBodyType, ResultType, Enable >) private
References TExecutableTaskBase().
Field Documentation
TaskBodyStorage
template<typename TaskBodyType, typename ResultType = TInvokeResult_T<TaskBodyType>, typename Enable = void> TTypeCompatibleBytes<TaskBodyType> UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::TaskBodyStorage private
Definition at line 892 of file TaskPrivate.h.
Referenced by TExecutableTaskBase(), and ExecuteTask().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Tasks/TaskPrivate.h