Unreal Engine 5.6 C++ API: TFieldPtrAccessor< T > Class Template Reference
TFieldPtrAccessor< T > Class Template Reference
Helper to provide backward compatibility when converting a raw pointer into accessors.
#include "FieldAccessor.h"
Public Member Functions
TFieldPtrAccessor (const TFieldPtrAccessor &Other)
TFieldPtrAccessor (T *InValue=nullptr)
TFieldPtrAccessor (TFunction< T *()> InGet, TFunction< void(T *)> InSet)
operator bool () const
template<typename OtherT>
operator OtherT * () const
operator T* () const
bool operator! () const
bool operator!= (const T *OtherPtr) const
T * operator-> () const
TFieldPtrAccessor & operator= (const TFieldPtrAccessor &Other)=delete
TFieldPtrAccessor & operator= (T *OtherPtr)
TFieldPtrAccessor & operator= (TFieldPtrAccessor &&)=delete
bool operator== (const T *OtherPtr) const
Private Attributes
T * CapturedValue = nullptr
TFunction< T *()> Get
TFunction< void(T *)> Set
Detailed Description
template<typename T>
class TFieldPtrAccessor< T >
Helper to provide backward compatibility when converting a raw pointer into accessors.
The helper is trying hard to mimic's a raw pointer field functionality without breaking compatibility for existing code.
The helper's getter are all const and return a non-const pointer. This is because accessing a pointer field inside a const struct will not make that pointer const like we typically do for accessors. Since we want to mimic the behavior of a public field as much as possible, we offer that same functionality.
The helper supports being captured in a lamba as seen below and will become a const copy of the value at the capture's moment. ex: [CapturedValue = Object.OnceARawFieldBecomingAnAccessor]() { // ExtractedValue contains a copy that will not change even if the original Object.OnceARawFieldBecomingAnAccessor changes. const Class* ExtractedValue = CapturedValue; });
This helper also supports taking a nullptr in its constructor so it properly supports conditional like such ex: ExtractedValue* Val = (Condition) ? Object.OnceARawFieldBecomingAnAccessor : nullptr;
A comforming compiler is supposed to try both conversions (nullptr -> TFieldPtrAccessor and TFieldPtrAccessor -> nullptr) but MSVC without the /permissive- flag will only try to cast nullptr into a TFieldPtrAccessor, which has to succeed to avoid breaking compabitility with existing code.
For more info, please refer to https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019#ambiguous-conditional-operator-arguments
Definition at line 39 of file FieldAccessor.h.
Constructor & Destructor Documentation
TFieldPtrAccessor() [1/3]
template<typename T> TFieldPtrAccessor< T >::TFieldPtrAccessor (TFunction< T *()> InGet, TFunction< void(T *)> InSet) inline
Definition at line 43 of file FieldAccessor.h.
References Get, MoveTemp(), and Set.
Referenced by TFieldPtrAccessor(), operator=(), operator=(), and operator=().
TFieldPtrAccessor() [2/3]
template<typename T> TFieldPtrAccessor< T >::TFieldPtrAccessor (T * InValue = nullptr) inline
Definition at line 50 of file FieldAccessor.h.
References CapturedValue, and Get.
TFieldPtrAccessor() [3/3]
template<typename T> TFieldPtrAccessor< T >::TFieldPtrAccessor (const TFieldPtrAccessor< T > & Other) inline
Definition at line 58 of file FieldAccessor.h.
References TFieldPtrAccessor(), CapturedValue, Get, and Other.
Member Function Documentation
operator bool()
template<typename T> TFieldPtrAccessor< T >::operator bool () const inline
Definition at line 73 of file FieldAccessor.h.
References Get.
operator OtherT *()
template<typename T> template<typename OtherT> TFieldPtrAccessor< T >::operator OtherT * () const inline explicit
Definition at line 84 of file FieldAccessor.h.
References Get.
operator T*()
template<typename T> TFieldPtrAccessor< T >::operator T* () const inline
Definition at line 78 of file FieldAccessor.h.
References Get.
operator!()
template<typename T> bool TFieldPtrAccessor< T >::operator! () const inline
Definition at line 89 of file FieldAccessor.h.
References Get.
operator!=()
template<typename T> bool TFieldPtrAccessor< T >::operator!= (const T * OtherPtr) const inline
Definition at line 99 of file FieldAccessor.h.
References Get.
operator->()
template<typename T> T * TFieldPtrAccessor< T >::operator-> () const inline
Definition at line 68 of file FieldAccessor.h.
References Get.
operator=() [1/3]
template<typename T> TFieldPtrAccessor & TFieldPtrAccessor< T >::operator= (const TFieldPtrAccessor< T > & Other) delete
References TFieldPtrAccessor(), and Other.
operator=() [2/3]
template<typename T> TFieldPtrAccessor & TFieldPtrAccessor< T >::operator= (T * OtherPtr) inline
Definition at line 104 of file FieldAccessor.h.
References TFieldPtrAccessor(), and Set.
operator=() [3/3]
template<typename T> TFieldPtrAccessor & TFieldPtrAccessor< T >::operator= (TFieldPtrAccessor< T > &&) delete
References TFieldPtrAccessor().
operator==()
template<typename T> bool TFieldPtrAccessor< T >::operator== (const T * OtherPtr) const inline
Definition at line 94 of file FieldAccessor.h.
References Get.
Field Documentation
CapturedValue
template<typename T> T* TFieldPtrAccessor< T >::CapturedValue = nullptr private
Definition at line 112 of file FieldAccessor.h.
Referenced by TFieldPtrAccessor(), and TFieldPtrAccessor().
Get
template<typename T> TFunction< T* ()> TFieldPtrAccessor< T >::Get private
Definition at line 113 of file FieldAccessor.h.
Referenced by TFieldPtrAccessor(), TFieldPtrAccessor(), TFieldPtrAccessor(), operator bool(), operator OtherT *(), operator T*(), operator!(), operator!=(), operator->(), and operator==().
Set
template<typename T> TFunction<void(T*)> TFieldPtrAccessor< T >::Set private
Definition at line 114 of file FieldAccessor.h.
Referenced by TFieldPtrAccessor(), and operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/FieldAccessor.h