Unreal Engine 5.6 C++ API: FRawStaticIndexBuffer16or32< INDEX_TYPE > Class Template Reference
FRawStaticIndexBuffer16or32< INDEX_TYPE > Class Template Reference
#include "RawIndexBuffer.h"
Public Member Functions
FRawStaticIndexBuffer16or32 (bool InNeedsCPUAccess=false)
Constructor.
virtual int32 AddItem (uint32 Val) override
virtual void AssignNewBuffer (const TArray< INDEX_TYPE > &Buffer)
void CacheOptimize ()
Orders a triangle list for better vertex cache coherency.
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI index buffer with CPU data.
virtual void Empty (int32 Slack) override
virtual uint32 Get (uint32 Idx) const override
virtual bool GetNeedsCPUAccess () const override
The following methods are basically just accessors that allow us to hide the implementation by making the index array a private member.
virtual void * GetPointerTo (uint32 Idx) override
virtual int32 GetResourceDataSize () const override
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Create the index buffer RHI resource and initialize its data.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
virtual void Insert (int32 Idx, int32 Num) override
virtual int32 Num () const override
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
virtual void Remove (int32 Idx, int32 Num) override
virtual void Serialize (FArchive &Ar) override
Serializer for this class.
virtual void SerializeMetaData (FArchive &Ar) override
virtual void SetMetaData (int32 InCachedNumIndices) override
Public Member Functions inherited from FRawStaticIndexBuffer16or32Interface
FRHIShaderResourceView * GetSRV () const
Public Member Functions inherited from FIndexBuffer
RENDERCORE_API FIndexBuffer ()
RENDERCORE_API FIndexBuffer (const FIndexBuffer &)
virtual RENDERCORE_API ~FIndexBuffer ()
virtual RENDERCORE_API FString GetFriendlyName () const override
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FIndexBuffer & operator= (const FIndexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Attributes
int32 CachedNumIndices
TResourceArray< INDEX_TYPE, INDEXBUFFER_ALIGNMENT > Indices
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FIndexBuffer
FBufferRHIRef IndexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRawStaticIndexBuffer16or32Interface
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, size_t IndexSize, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
bool IsSRVNeeded (bool bAllowCPUAccess) const
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRawStaticIndexBuffer16or32Interface
static FBufferRHIRef CreateRHIIndexBufferInternal (FRHICommandListBase &RHICmdList, const TCHAR *InDebugName, const FName &InOwnerName, int32 IndexCount, size_t IndexSize, FResourceArrayInterface *ResourceArray, bool bNeedSRV)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Protected Attributes inherited from FRawStaticIndexBuffer16or32Interface
FShaderResourceViewRHIRef SRVValue
Detailed Description
template<typename INDEX_TYPE>
class FRawStaticIndexBuffer16or32< INDEX_TYPE >
Definition at line 378 of file RawIndexBuffer.h.
Constructor & Destructor Documentation
FRawStaticIndexBuffer16or32()
template<typename INDEX_TYPE> FRawStaticIndexBuffer16or32< INDEX_TYPE >::FRawStaticIndexBuffer16or32 (bool InNeedsCPUAccess = false) inline
Constructor.
Parameters
InNeedsCPUAccess - true if resource array data should be CPU accessible
Definition at line 385 of file RawIndexBuffer.h.
References CachedNumIndices, and Indices.
Member Function Documentation
AddItem()
template<typename INDEX_TYPE> virtual int32 FRawStaticIndexBuffer16or32< INDEX_TYPE >::AddItem (uint32 Val) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 456 of file RawIndexBuffer.h.
References CachedNumIndices, and Indices.
AssignNewBuffer()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::AssignNewBuffer (const TArray< INDEX_TYPE > & Buffer) inline virtual
Definition at line 497 of file RawIndexBuffer.h.
References Buffer, CachedNumIndices, and Indices.
CacheOptimize()
template<typename INDEX_TYPE> void FRawStaticIndexBuffer16or32< INDEX_TYPE >::CacheOptimize ()
Orders a triangle list for better vertex cache coherency.
CreateRHIBuffer()
template<typename INDEX_TYPE> FBufferRHIRef FRawStaticIndexBuffer16or32< INDEX_TYPE >::CreateRHIBuffer (FRHICommandListBase & RHICmdList) inline
Create an RHI index buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
Definition at line 505 of file RawIndexBuffer.h.
References CachedNumIndices, FRawStaticIndexBuffer16or32Interface::CreateRHIIndexBufferInternal(), FRenderResource::GetOwnerName(), Indices, FRawStaticIndexBuffer16or32Interface::IsSRVNeeded(), and TEXT.
Referenced by InitRHI().
Empty()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::Empty (int32 Slack) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 486 of file RawIndexBuffer.h.
References CachedNumIndices, and Indices.
Get()
template<typename INDEX_TYPE> virtual uint32 FRawStaticIndexBuffer16or32< INDEX_TYPE >::Get (uint32 Idx) const inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 462 of file RawIndexBuffer.h.
References Indices.
GetNeedsCPUAccess()
template<typename INDEX_TYPE> virtual bool FRawStaticIndexBuffer16or32< INDEX_TYPE >::GetNeedsCPUAccess () const inline override virtual
The following methods are basically just accessors that allow us to hide the implementation by making the index array a private member.
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 449 of file RawIndexBuffer.h.
References Indices.
GetPointerTo()
template<typename INDEX_TYPE> virtual void * FRawStaticIndexBuffer16or32< INDEX_TYPE >::GetPointerTo (uint32 Idx) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 467 of file RawIndexBuffer.h.
References Indices.
GetResourceDataSize()
template<typename INDEX_TYPE> virtual int32 FRawStaticIndexBuffer16or32< INDEX_TYPE >::GetResourceDataSize () const inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 492 of file RawIndexBuffer.h.
References Indices.
InitRHI()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::InitRHI (FRHICommandListBase & RHICmdList) inline override virtual
Create the index buffer RHI resource and initialize its data.
Reimplemented from FRenderResource.
Definition at line 395 of file RawIndexBuffer.h.
References CreateRHIBuffer(), FIndexBuffer::IndexBufferRHI, Indices, FRawStaticIndexBuffer16or32Interface::IsSRVNeeded(), Num(), PF_R16_UINT, PF_R32_UINT, and FRawStaticIndexBuffer16or32Interface::SRVValue.
InitRHIForStreaming()
template<typename INDEX_TYPE> void FRawStaticIndexBuffer16or32< INDEX_TYPE >::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher) inline
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
Definition at line 527 of file RawIndexBuffer.h.
References FRawStaticIndexBuffer16or32Interface::InitRHIForStreaming(), and IntermediateBuffer.
Insert()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::Insert (int32 Idx, int32 Num) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 472 of file RawIndexBuffer.h.
References CachedNumIndices, check, Indices, and Num().
Num()
template<typename INDEX_TYPE> virtual int32 FRawStaticIndexBuffer16or32< INDEX_TYPE >::Num () const inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 451 of file RawIndexBuffer.h.
References CachedNumIndices.
Referenced by InitRHI(), Insert(), and Remove().
ReleaseRHI()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::ReleaseRHI () inline override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FIndexBuffer.
Definition at line 411 of file RawIndexBuffer.h.
References FRenderResource::ReleaseRHI(), and FRawStaticIndexBuffer16or32Interface::SRVValue.
ReleaseRHIForStreaming()
template<typename INDEX_TYPE> void FRawStaticIndexBuffer16or32< INDEX_TYPE >::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher) inline
Definition at line 532 of file RawIndexBuffer.h.
References FRawStaticIndexBuffer16or32Interface::ReleaseRHIForStreaming().
Remove()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::Remove (int32 Idx, int32 Num) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 479 of file RawIndexBuffer.h.
References CachedNumIndices, check, Indices, and Num().
Serialize()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::Serialize (FArchive & Ar) inline override virtual
Serializer for this class.
Parameters
Ar - archive to serialize to
I - data to serialize
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 423 of file RawIndexBuffer.h.
References Ar, CachedNumIndices, and Indices.
SerializeMetaData()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::SerializeMetaData (FArchive & Ar) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 429 of file RawIndexBuffer.h.
References Ar, and CachedNumIndices.
SetMetaData()
template<typename INDEX_TYPE> virtual void FRawStaticIndexBuffer16or32< INDEX_TYPE >::SetMetaData (int32 InCachedNumIndices) inline override virtual
Implements FRawStaticIndexBuffer16or32Interface.
Definition at line 434 of file RawIndexBuffer.h.
References CachedNumIndices.
Field Documentation
CachedNumIndices
template<typename INDEX_TYPE> int32 FRawStaticIndexBuffer16or32< INDEX_TYPE >::CachedNumIndices private
Definition at line 540 of file RawIndexBuffer.h.
Referenced by FRawStaticIndexBuffer16or32(), AddItem(), AssignNewBuffer(), CreateRHIBuffer(), Empty(), Insert(), Num(), Remove(), Serialize(), SerializeMetaData(), and SetMetaData().
Indices
template<typename INDEX_TYPE> TResourceArray<INDEX_TYPE,INDEXBUFFER_ALIGNMENT> FRawStaticIndexBuffer16or32< INDEX_TYPE >::Indices private
Definition at line 538 of file RawIndexBuffer.h.
Referenced by FRawStaticIndexBuffer16or32(), AddItem(), AssignNewBuffer(), CreateRHIBuffer(), Empty(), Get(), GetNeedsCPUAccess(), GetPointerTo(), GetResourceDataSize(), InitRHI(), Insert(), Remove(), and Serialize().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/RawIndexBuffer.h