Unreal Engine 5.6 C++ API: FCbObjectView Class Reference
FCbObjectView Class Reference
Array of FCbField[View] that have unique names.
#include "CompactBinary.h"
Public Member Functions
FCbObjectView ()
Construct an object with no fields.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the object if serialized by itself with no name.
FCbFieldView AsFieldView () const
Access the object as an object field.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the object into an archive.
void CopyTo (FMutableMemoryView Buffer) const
Copy the object into a buffer of exactly GetSize() bytes, with no name.
FCbFieldViewIterator CreateViewIterator () const
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbObjectView &Other) const
Whether this object is identical to the other object.
constexpr FCbFieldView ()=default
FCbFieldView (const FCbValue &Value)
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
FCbFieldView FindView (FUtf8StringView Name) const
Find a field by case-sensitive name comparison.
FCbFieldView FindViewIgnoreCase (FUtf8StringView Name) const
Find a field by case-insensitive name comparison.
FIoHash GetHash () const
Calculate the hash of the object if serialized by itself with no name.
uint64 GetSize () const
Returns the size of the object in bytes if serialized by itself with no name.
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the object.
operator bool () const
Whether the object has any fields.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field by case-sensitive name comparison.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the object as it would be serialized, such as by CopyTo.
Static Public Member Functions
static FCbObjectView FromFieldNoCheck (const FCbFieldView &Field)
Construct an object from an object field.
Private Member Functions
FCbObjectView (const FCbFieldView &Field)
Construct an object from an object field.
Additional Inherited Members
Protected Member Functions inherited from FCbFieldView
void Assign (const void *InData, const ECbFieldType InType)
Assign a field from a pointer to its data and an optional externally-provided type.
constexpr ECbFieldType GetType () const
Returns the type of the field excluding flags.
constexpr ECbFieldType GetTypeWithFlags () const
Returns the type of the field including flags.
constexpr const void * GetValueData () const
Returns the start of the value.
const void * GetValueEnd () const
Returns the end of the value.
uint64 GetValueSize () const
Returns the size of the value in bytes, which is the field excluding the type and name.
FMemoryView GetValueView () const
Returns a view of the value, which excludes the type and name.
FMemoryView GetView () const
Returns a view of the field, including the type and name when present.
FMemoryView GetViewNoType () const
Returns a view of the name and value, which excludes the type.
constexpr FCbFieldView ()=default
Construct a field with no name and no value.
FCbFieldView (const FCbValue &Value)
Construct a field from a value, without access to the name.
FCbFieldView (const void *Data, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a field from a pointer to its data and an optional externally-provided type.
void AppendHash (FIoHashBuilder &Builder) const
Append the hash of the field, including the type and name.
FCbArrayView AsArrayView ()
Access the field as an array.
FIoHash AsAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an attachment.
FIoHash AsBinaryAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing a binary attachment.
FMemoryView AsBinaryView (FMemoryView Default=FMemoryView())
Access the field as binary.
bool AsBool (bool bDefault=false)
Access the field as a bool.
FMemoryView AsCustom (FUtf8StringView Name, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with a string identifier.
FMemoryView AsCustom (uint64 Id, FMemoryView Default=FMemoryView())
Access the field as a custom sub-type with an integer identifier.
FCbCustomById AsCustomById (FCbCustomById Default=FCbCustomById())
Access the field as a custom sub-type with an integer identifier.
FCbCustomByName AsCustomByName (FCbCustomByName Default=FCbCustomByName())
Access the field as a custom sub-type with a string identifier.
FDateTime AsDateTime ()
Access the field as a date/time.
FDateTime AsDateTime (FDateTime Default)
Access the field as a date/time.
int64 AsDateTimeTicks (int64 Default=0)
Access the field as a date/time tick count.
double AsDouble (double Default=0.0)
Access the field as a double.
float AsFloat (float Default=0.0f)
Access the field as a float.
FIoHash AsHash (const FIoHash &Default=FIoHash())
Access the field as a hash.
int16 AsInt16 (int16 Default=0)
Access the field as an int16.
int32 AsInt32 (int32 Default=0)
Access the field as an int32.
int64 AsInt64 (int64 Default=0)
Access the field as an int64.
int8 AsInt8 (int8 Default=0)
Access the field as an int8.
FIoHash AsObjectAttachment (const FIoHash &Default=FIoHash())
Access the field as a hash referencing an object attachment.
FCbObjectId AsObjectId (const FCbObjectId &Default=FCbObjectId())
Access the field as an object identifier.
FCbObjectView AsObjectView ()
Access the field as an object.
FUtf8StringView AsString (FUtf8StringView Default=FUtf8StringView())
Access the field as a string.
FTimespan AsTimeSpan ()
Access the field as a timespan.
FTimespan AsTimeSpan (FTimespan Default)
Access the field as a timespan.
int64 AsTimeSpanTicks (int64 Default=0)
Access the field as a timespan tick count.
uint16 AsUInt16 (uint16 Default=0)
Access the field as a uint16.
uint32 AsUInt32 (uint32 Default=0)
Access the field as a uint32.
uint64 AsUInt64 (uint64 Default=0)
Access the field as a uint64.
uint8 AsUInt8 (uint8 Default=0)
Access the field as a uint8.
FGuid AsUuid ()
Access the field as a UUID.
FGuid AsUuid (const FGuid &Default)
Access the field as a UUID.
FCbFieldViewIterator begin () const
DO NOT USE DIRECTLY.
void CopyTo (FArchive &Ar) const
Copy the field into an archive, including its type and name.
void CopyTo (FMutableMemoryView Buffer) const
Copy the field into a buffer of exactly GetSize() bytes, including the type and name.
FCbFieldViewIterator CreateViewIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
bool Equals (const FCbFieldView &Other) const
Whether this field is identical to the other field.
constexpr ECbFieldError GetError () const
The type of error that occurred on the last field access, or None.
FIoHash GetHash () const
Calculate the hash of the field, including the type and name.
constexpr FUtf8StringView GetName () const
Returns the name of the field if it has a name, otherwise an empty view.
uint64 GetSize () const
Returns the size of the field in bytes, including the type and name.
FCbValue GetValue () const
Returns the value for unchecked access.
constexpr bool HasError () const
Whether the last field access encountered an error.
constexpr bool HasName () const
True if the field has a name.
constexpr bool HasValue () const
Whether the field has a value.
constexpr bool IsArray () const
constexpr bool IsAttachment () const
constexpr bool IsBinary () const
constexpr bool IsBinaryAttachment () const
constexpr bool IsBool () const
constexpr bool IsCustomById () const
constexpr bool IsCustomByName () const
constexpr bool IsDateTime () const
constexpr bool IsFloat () const
Whether the field is a float, or integer that supports implicit conversion.
constexpr bool IsHash () const
constexpr bool IsInteger () const
Whether the field is an integer of unspecified range and sign.
constexpr bool IsNull () const
constexpr bool IsObject () const
constexpr bool IsObjectAttachment () const
constexpr bool IsObjectId () const
constexpr bool IsString () const
constexpr bool IsTimeSpan () const
constexpr bool IsUuid () const
void IterateAttachments (FCbFieldVisitor Visitor) const
Invoke the visitor for every attachment in the field.
constexpr operator bool () const
Whether the field has a value.
FCbFieldView operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
constexpr FCbFieldView RemoveName () const
Returns a copy of the field with the name removed.
bool TryGetView (FMemoryView &OutView) const
Try to get a view of the field as it would be serialized, such as by CopyTo.
Detailed Description
Array of FCbField[View] that have unique names.
Accessing the fields of an object is always a safe operation, even if the requested field does not exist. Fields may be accessed by name or through iteration. When a field is requested that is not found in the object, the field that it returns has no value (evaluates to false) though attempting to access the empty field is also safe, as described by FCbFieldView.
This type only provides a view into memory and does not perform any memory management itself. Use FCbObject to hold a reference to the underlying memory when necessary.
Definition at line 1024 of file CompactBinary.h.
Constructor & Destructor Documentation
FCbObjectView() [1/2]
FCbObjectView::FCbObjectView ()
Construct an object with no fields.
Referenced by Equals(), and FromFieldNoCheck().
FCbObjectView() [2/2]
FCbObjectView::FCbObjectView (const FCbFieldView & Field) inline explicit private
Construct an object from an object field.
No type check is performed! Use via FromFieldNoCheck.
Definition at line 1105 of file CompactBinary.h.
References FCbFieldView().
Member Function Documentation
AppendHash()
void FCbObjectView::AppendHash (FIoHashBuilder & Builder) const
Append the hash of the object if serialized by itself with no name.
AsFieldView()
FCbFieldView FCbObjectView::AsFieldView () const inline nodiscard
Access the object as an object field.
Definition at line 1051 of file CompactBinary.h.
References FCbFieldView(), and FCbFieldView::RemoveName().
Referenced by FCbObject::AsField(), and FCbObject::AsField().
begin()
FCbFieldViewIterator FCbFieldView::begin () const inline
DO NOT USE DIRECTLY.
These functions enable range-based for loop support.
Definition at line 825 of file CompactBinary.h.
CopyTo() [1/2]
void FCbObjectView::CopyTo (FArchive & Ar) const
Copy the object into an archive.
This will write GetSize() bytes, with no name.
References Ar.
CopyTo() [2/2]
void FCbObjectView::CopyTo (FMutableMemoryView Buffer) const
Copy the object into a buffer of exactly GetSize() bytes, with no name.
References Buffer.
CreateViewIterator()
FCbFieldViewIterator FCbFieldView::CreateViewIterator () const nodiscard
See also
FCbFieldView::CreateViewIterator
Referenced by IterateAttachments().
end()
FCbIteratorSentinel FCbFieldView::end () const inline constexpr
Definition at line 826 of file CompactBinary.h.
Equals()
bool FCbObjectView::Equals (const FCbObjectView & Other) const
Whether this object is identical to the other object.
Performs a deep comparison of any contained arrays or objects and their fields. Comparison assumes that both fields are valid and are written in the canonical format. Fields must be written in the same order in arrays and objects, and name comparison is case sensitive. If these assumptions do not hold, this may return false for equivalent inputs. Validation can be done with the All mode to check these assumptions about the format of the inputs.
References FCbObjectView(), and Other.
FCbFieldView() [1/3]
FCbFieldView::FCbFieldView () constexpr default
See also
FCbFieldView::FCbFieldView
Referenced by FCbObjectView(), AsFieldView(), FindView(), FindViewIgnoreCase(), FromFieldNoCheck(), and operator[]().
FCbFieldView() [2/3]
FORCEINLINE FCbFieldView::FCbFieldView (const FCbValue & Value) inline explicit
See also
FCbFieldView::FCbFieldView
Definition at line 624 of file CompactBinaryValue.h.
FCbFieldView() [3/3]
FCbFieldView::FCbFieldView (const void * Data, ECbFieldType Type = ECbFieldType::HasFieldType) explicit
See also
FCbFieldView::FCbFieldView
FindView()
FCbFieldView FCbObjectView::FindView (FUtf8StringView Name) const nodiscard
Find a field by case-sensitive name comparison.
The cost of this operation scales linearly with the number of fields in the object. Prefer to iterate over the fields only once when consuming an object.
Parameters
Name The name of the field.
Returns
The matching field if found, otherwise a field with no value.
References FCbFieldView(), and Name.
Referenced by FCbObject::Find(), and operator[]().
FindViewIgnoreCase()
FCbFieldView FCbObjectView::FindViewIgnoreCase (FUtf8StringView Name) const nodiscard
Find a field by case-insensitive name comparison.
References FCbFieldView(), and Name.
Referenced by FCbObject::FindIgnoreCase().
FromFieldNoCheck()
FCbObjectView FCbObjectView::FromFieldNoCheck (const FCbFieldView & Field) inline static nodiscard
Construct an object from an object field.
No type check is performed!
Definition at line 1054 of file CompactBinary.h.
References FCbObjectView(), and FCbFieldView().
GetHash()
FIoHash FCbObjectView::GetHash () const
Calculate the hash of the object if serialized by itself with no name.
GetSize()
uint64 FCbObjectView::GetSize () const
Returns the size of the object in bytes if serialized by itself with no name.
IterateAttachments()
void FCbObjectView::IterateAttachments (FCbFieldVisitor Visitor) const inline
Invoke the visitor for every attachment in the object.
Definition at line 1085 of file CompactBinary.h.
References CreateViewIterator(), and TCbFieldIterator< FieldType >::IterateRangeAttachments().
operator bool()
FCbObjectView::operator bool () const explicit
Whether the object has any fields.
operator[]()
FCbFieldView FCbObjectView::operator[] (FUtf8StringView Name) const inline nodiscard
Find a field by case-sensitive name comparison.
Definition at line 1048 of file CompactBinary.h.
References FCbFieldView(), FindView(), and Name.
TryGetView()
bool FCbObjectView::TryGetView (FMemoryView & OutView) const inline
Try to get a view of the object as it would be serialized, such as by CopyTo.
A view is available if the object contains its type and has no name. Access the equivalent for other objects through FCbObject::GetBuffer, FCbObject::Clone, or CopyTo.
Definition at line 1093 of file CompactBinary.h.
References FCbFieldView::HasName(), and FCbFieldView::TryGetView().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinary.h