Unreal Engine 5.6 C++ API: UUVToolSelectionHighlightMechanic Class Reference
UUVToolSelectionHighlightMechanic Class Reference
Mechanic for highlighting mesh elements (usually selection) in the UV editor.
#include "UVToolSelectionHighlightMechanic.h"
Public Member Functions
void AppendAppliedHighlight (const TArray< FUVToolSelection > &AppliedSelections, bool bUsePreviews=false)
Adds additional highlighting elements based on selection information.
FTransform GetUnwrapHighlightTransform ()
Get the current transform of the unwrap highlight.
void Initialize (UWorld *UnwrapWorld, UWorld *LivePreviewWorld)
void RebuildAppliedHighlightFromUnwrapSelection (const TArray< FUVToolSelection > &UnwrapSelections, bool bUsePreviews=false)
Convert the unwrap selections to elements in the applied mesh, then highlight those there.
void RebuildUnwrapHighlight (const TArray< FUVToolSelection > &Selections, const FTransform &StartTransform, bool bUsePreviews=false)
Rebuilds the unwrap mesh highlights.
void SetColor (const FColor Color) const
Directly set the Color property of the selection line and point set.
void SetEnablePairedEdgeHighlights (bool bEnable)
When true, edge selections also highlight the edge pairings (i.e.
void SetIsVisible (bool bUnwrapHighlightVisible, bool bLivePreviewHighlightVisible)
void SetLineThickness (const float LineSize) const
Directly set the Size/Thickness property of the selection line set.
void SetPointSize (const float PointSize) const
directly set the Size property of the selection point set.
void SetUnwrapHighlightTransform (const FTransform &Transform, bool bRebuildStaticPairedEdges=true, bool bUsePreviews=false)
Set the transform of the unwrap mesh highlights without rebuilding them, likely to follow the translation of the underlying elements via gizmo.
void Shutdown () override
Protected Attributes
bool bPairedEdgeHighlightsEnabled = true
TObjectPtr< APreviewGeometryActor > LivePreviewGeometryActor = nullptr
TWeakObjectPtr< UBasic3DLineSetComponent > LivePreviewLineSet = nullptr
TWeakObjectPtr< UBasic3DPointSetComponent > LivePreviewPointSet = nullptr
TWeakObjectPtr< UBasic2DLineSetComponent > SewEdgePairingLeftLineSet = nullptr
TWeakObjectPtr< UBasic2DLineSetComponent > SewEdgePairingRightLineSet = nullptr
TWeakObjectPtr< UBasic2DLineSetComponent > SewEdgeUnselectedPairingLineSet = nullptr
TArray< TPair< TWeakObjectPtr< UUVEditorToolMeshInput >, TArray< TPair< int32, int32 > > > > StaticPairedEdgeVidsPerMesh
TObjectPtr< UMaterialInstanceDynamic > TriangleSetMaterial = nullptr
TObjectPtr< APreviewGeometryActor > UnwrapGeometryActor = nullptr
TWeakObjectPtr< UBasic2DLineSetComponent > UnwrapLineSet = nullptr
TWeakObjectPtr< UBasic2DLineSetComponent > UnwrapPairedEdgeLineSet = nullptr
TWeakObjectPtr< UBasic2DPointSetComponent > UnwrapPointSet = nullptr
TObjectPtr< APreviewGeometryActor > UnwrapStationaryGeometryActor = nullptr
TWeakObjectPtr< UBasic2DTriangleSetComponent > UnwrapTriangleSet = nullptr
Private Types
using FUVToolSelection = UE::Geometry::FUVToolSelection
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Mechanic for highlighting mesh elements (usually selection) in the UV editor.
Definition at line 29 of file UVToolSelectionHighlightMechanic.h.
Member Typedef Documentation
FUVToolSelection
using UUVToolSelectionHighlightMechanic::FUVToolSelection = UE::Geometry::FUVToolSelection private
Definition at line 33 of file UVToolSelectionHighlightMechanic.h.
Member Function Documentation
AppendAppliedHighlight()
void UUVToolSelectionHighlightMechanic::AppendAppliedHighlight (const TArray< FUVToolSelection > & AppliedSelections, bool bUsePreviews = false)
Adds additional highlighting elements based on selection information.
This is used to extend selection line sets for the unset selections if they are needed.
Parameters
bUsePreviews If true, the previews are used rather than the canonicals for finding the highlight positions.
References AppendAppliedHighlight().
Referenced by AppendAppliedHighlight().
GetUnwrapHighlightTransform()
FTransform UUVToolSelectionHighlightMechanic::GetUnwrapHighlightTransform ()
Get the current transform of the unwrap highlight.
References GetUnwrapHighlightTransform().
Referenced by GetUnwrapHighlightTransform().
Initialize()
void UUVToolSelectionHighlightMechanic::Initialize (UWorld * UnwrapWorld, UWorld * LivePreviewWorld)
References Initialize().
Referenced by Initialize().
RebuildAppliedHighlightFromUnwrapSelection()
void UUVToolSelectionHighlightMechanic::RebuildAppliedHighlightFromUnwrapSelection (const TArray< FUVToolSelection > & UnwrapSelections, bool bUsePreviews = false)
Convert the unwrap selections to elements in the applied mesh, then highlight those there.
Parameters
bUsePreviews If true, the previews are used rather than the canonicals both for converting over to applied mesh elements and to finding the highlight positions.
References RebuildAppliedHighlightFromUnwrapSelection().
Referenced by RebuildAppliedHighlightFromUnwrapSelection().
RebuildUnwrapHighlight()
void UUVToolSelectionHighlightMechanic::RebuildUnwrapHighlight (const TArray< FUVToolSelection > & Selections, const FTransform & StartTransform, bool bUsePreviews = false)
Rebuilds the unwrap mesh highlights.
Parameters
StartTransform The transform to consider as the start transform, so that the highlights can be repositioned easily later via SetUnwrapHighlightTransform().
bUsePreviews If true, the selected element positions will be gotten from the UnwrapPreview of each selection target rather than UnwrapCanonical.
References RebuildUnwrapHighlight().
Referenced by RebuildUnwrapHighlight().
SetColor()
void UUVToolSelectionHighlightMechanic::SetColor (const FColor Color) const
Directly set the Color property of the selection line and point set.
References Color, and SetColor().
Referenced by SetColor().
SetEnablePairedEdgeHighlights()
void UUVToolSelectionHighlightMechanic::SetEnablePairedEdgeHighlights (bool bEnable)
When true, edge selections also highlight the edge pairings (i.e.
edges that could weld with the selected edges). Note that the call itself controls visibility and the next rebuild call, but won't cause an immediate rebuild on its own.
References SetEnablePairedEdgeHighlights().
Referenced by SetEnablePairedEdgeHighlights().
SetIsVisible()
void UUVToolSelectionHighlightMechanic::SetIsVisible (bool bUnwrapHighlightVisible, bool bLivePreviewHighlightVisible)
References SetIsVisible().
Referenced by SetIsVisible().
SetLineThickness()
void UUVToolSelectionHighlightMechanic::SetLineThickness (const float LineSize) const
Directly set the Size/Thickness property of the selection line set.
References SetLineThickness().
Referenced by SetLineThickness().
SetPointSize()
void UUVToolSelectionHighlightMechanic::SetPointSize (const float PointSize) const
directly set the Size property of the selection point set.
References SetPointSize(), and UPROPERTY.
Referenced by SetPointSize().
SetUnwrapHighlightTransform()
void UUVToolSelectionHighlightMechanic::SetUnwrapHighlightTransform (const FTransform & Transform, bool bRebuildStaticPairedEdges = true, bool bUsePreviews = false)
Set the transform of the unwrap mesh highlights without rebuilding them, likely to follow the translation of the underlying elements via gizmo.
Parameters
bRebuildStaticPairedEdges If true, and paired edge highlighting is enabled, unselected paired edges are rebuilt in the highlight. This is usually necessary because such edges may be attached to moving selected edges.
bUsePreviews If bRebuildStaticPairedEdges is true, this will prefer to use the previews rather than the unwrap canonical.
References SetUnwrapHighlightTransform(), and Transform.
Referenced by SetUnwrapHighlightTransform().
Shutdown()
void UUVToolSelectionHighlightMechanic::Shutdown () override
References Shutdown().
Referenced by Shutdown().
Field Documentation
bPairedEdgeHighlightsEnabled
bool UUVToolSelectionHighlightMechanic::bPairedEdgeHighlightsEnabled = true protected
Definition at line 137 of file UVToolSelectionHighlightMechanic.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVToolSelectionHighlightMechanic::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 31 of file UVToolSelectionHighlightMechanic.h.
LivePreviewGeometryActor
TObjectPtr<APreviewGeometryActor> UUVToolSelectionHighlightMechanic::LivePreviewGeometryActor = nullptr protected
Definition at line 133 of file UVToolSelectionHighlightMechanic.h.
LivePreviewLineSet
TWeakObjectPtr<UBasic3DLineSetComponent> UUVToolSelectionHighlightMechanic::LivePreviewLineSet = nullptr protected
Definition at line 134 of file UVToolSelectionHighlightMechanic.h.
LivePreviewPointSet
TWeakObjectPtr<UBasic3DPointSetComponent> UUVToolSelectionHighlightMechanic::LivePreviewPointSet = nullptr protected
Definition at line 135 of file UVToolSelectionHighlightMechanic.h.
SewEdgePairingLeftLineSet
TWeakObjectPtr<UBasic2DLineSetComponent> UUVToolSelectionHighlightMechanic::SewEdgePairingLeftLineSet = nullptr protected
Definition at line 118 of file UVToolSelectionHighlightMechanic.h.
SewEdgePairingRightLineSet
TWeakObjectPtr<UBasic2DLineSetComponent> UUVToolSelectionHighlightMechanic::SewEdgePairingRightLineSet = nullptr protected
Definition at line 119 of file UVToolSelectionHighlightMechanic.h.
SewEdgeUnselectedPairingLineSet
TWeakObjectPtr<UBasic2DLineSetComponent> UUVToolSelectionHighlightMechanic::SewEdgeUnselectedPairingLineSet = nullptr protected
Definition at line 125 of file UVToolSelectionHighlightMechanic.h.
StaticPairedEdgeVidsPerMesh
TArray<TPair<TWeakObjectPtr<UUVEditorToolMeshInput>, TArray<TPair<int32, int32> > > > UUVToolSelectionHighlightMechanic::StaticPairedEdgeVidsPerMesh protected
Definition at line 130 of file UVToolSelectionHighlightMechanic.h.
TriangleSetMaterial
TObjectPtr<UMaterialInstanceDynamic> UUVToolSelectionHighlightMechanic::TriangleSetMaterial = nullptr protected
Definition at line 114 of file UVToolSelectionHighlightMechanic.h.
UnwrapGeometryActor
TObjectPtr<APreviewGeometryActor> UUVToolSelectionHighlightMechanic::UnwrapGeometryActor = nullptr protected
Definition at line 112 of file UVToolSelectionHighlightMechanic.h.
UnwrapLineSet
TWeakObjectPtr<UBasic2DLineSetComponent> UUVToolSelectionHighlightMechanic::UnwrapLineSet = nullptr protected
Definition at line 117 of file UVToolSelectionHighlightMechanic.h.
UnwrapPairedEdgeLineSet
TWeakObjectPtr<UBasic2DLineSetComponent> UUVToolSelectionHighlightMechanic::UnwrapPairedEdgeLineSet = nullptr protected
Definition at line 121 of file UVToolSelectionHighlightMechanic.h.
UnwrapPointSet
TWeakObjectPtr<UBasic2DPointSetComponent> UUVToolSelectionHighlightMechanic::UnwrapPointSet = nullptr protected
Definition at line 120 of file UVToolSelectionHighlightMechanic.h.
UnwrapStationaryGeometryActor
TObjectPtr<APreviewGeometryActor> UUVToolSelectionHighlightMechanic::UnwrapStationaryGeometryActor = nullptr protected
Definition at line 124 of file UVToolSelectionHighlightMechanic.h.
UnwrapTriangleSet
TWeakObjectPtr<UBasic2DTriangleSetComponent> UUVToolSelectionHighlightMechanic::UnwrapTriangleSet = nullptr protected
Definition at line 116 of file UVToolSelectionHighlightMechanic.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/Selection/UVToolSelectionHighlightMechanic.h