Unreal Engine 5.6 C++ API: FCinematicShotTrackEditor Class Reference
FCinematicShotTrackEditor Class Reference
Tools for cinematic shots.
#include "CinematicShotTrackEditor.h"
Public Member Functions
FCinematicShotTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FCinematicShotTrackEditor ()
Virtual destructor.
virtual TSharedPtr< SWidget > BuildOutlinerColumnWidget (const FBuildColumnWidgetParams &Params, const FName &ColumnName) override
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
virtual void BuildTrackContextMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the context menu for the track.
virtual FString GetDefaultSubsequenceDirectory () const override
Get the sub sequence directory.
virtual FString GetDefaultSubsequenceName () const override
Get the default sub sequence name.
virtual FText GetDisplayName () const override
The display name text to use in the UX.
virtual FString GetSubSectionDisplayName (const UMovieSceneSubSection *Section) const override
Get the display name for the sub section.
virtual FName GetSubTrackBrushName () const override
Get the brush used for the sub track editor.
virtual TSubclassOf< UMovieSceneSubTrack > GetSubTrackClass () const
Get the UMovieSceneSubTrack class.
virtual FText GetSubTrackName () const override
Get the name of the sub track.
virtual FText GetSubTrackToolTip () const override
Get the tooltip for this sub track editor.
virtual TSharedRef< ISequencerSection > MakeSectionInterface (UMovieSceneSection &SectionObject, UMovieSceneTrack &Track, FGuid ObjectBinding) override
Called to generate a section layout for a particular section.
void RenderShots (const TArray< UMovieSceneCinematicShotSection * > &Sections)
virtual bool SupportsSequence (UMovieSceneSequence *InSequence) const override
Returns whether a sequence is supported by this tool.
virtual void Tick (float DeltaTime) override
Ticks this tool.
UE_DEPRECATED (5.5, "Use FCameraCutPlaybackCapability::LastViewTargetCamera instead.") TWeakObjectPtr< AActor > GetCinematicShotCamera() const
Public Member Functions inherited from FSubTrackEditor
FSubTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FSubTrackEditor ()
Virtual destructor.
virtual void AddTakesMenu (UMovieSceneSubSection *Section, FMenuBuilder &MenuBuilder)
Generate a menu for takes for this section.
virtual void BuildAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual TSharedPtr< SWidget > BuildOutlinerEditWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
bool CanAddSubSequence (const UMovieSceneSequence &Sequence) const
Check whether the given sequence can be added as a sub-sequence.
virtual bool CanAddTransformKeysForSelectedObjects () const override
Whether or not we can add a transform key for a selected object.
virtual void ChangeTake (UMovieSceneSequence *Sequence)
Switch the selected section's take sequence.
virtual void CreateNewTake (UMovieSceneSubSection *Section)
Create a new take of the given section.
virtual void DuplicateSection (UMovieSceneSubSection *Section)
Duplicate the section into this track.
virtual void EditMetaData (UMovieSceneSubSection *Section)
Edit the section's metadata.
virtual bool GetDefaultExpansionState (UMovieSceneTrack *InTrack) const override
virtual const FSlateBrush * GetIconBrush () const override
Gets an icon brush for this track editor.
int32 GetPreviousKey (FMovieSceneDoubleChannel &Channel, FFrameNumber Time)
Helper function that finds the previous key.
FTransform GetTransformOriginDataForSubSection (const UMovieSceneSubSection *SubSection) const
Query's the channel data directly (does not take parent transforms into account).
virtual bool HandleAssetAdded (UObject *Asset, const FGuid &TargetObjectGuid) override
Called when an asset is dropped into Sequencer.
virtual bool HasTransformKeyBindings () const override
virtual void InsertSection (UMovieSceneTrack *Track)
Insert sequence into this track.
virtual bool IsResizable (UMovieSceneTrack *InTrack) const override
virtual void OnAddTransformKeysForSelectedObjects (EMovieSceneTransformChannel Channel) override
Adds transform tracks and keys to the selected objects in the level.
virtual bool OnAllowDrop (const FDragDropEvent &DragDropEvent, FSequencerDragDropParams &DragDropParams) override
Called when attempting to drop an asset directly onto a track.
virtual FReply OnDrop (const FDragDropEvent &DragDropEvent, const FSequencerDragDropParams &DragDropParams) override
Called when an asset is dropped directly onto a track.
virtual void OnInitialize () override
Called when the instance of this track editor is initialized.
virtual void OnRelease () override
Called when the instance of this track editor is released.
virtual void ProcessKeyOperation (FFrameNumber InKeyTime, const UE::Sequencer::FKeyOperation &Operation, ISequencer &InSequencer, TArray< UE::Sequencer::FAddKeyResult > *OutResults=nullptr) override
Add keys for the following sections based on an external value if possible.
void ResetSectionPreviews ()
Called when sequence playback updates to revert preview data on modified secitons.
void ResetSectionPreviews (const FMovieSceneChannelMetaData *MetaData, UMovieSceneSection *InSection)
void ResetSectionPreviews (FMovieSceneSequenceIDRef IDRef)
virtual void Resize (float NewSize, UMovieSceneTrack *InTrack) override
Resize this track.
virtual bool SupportsType (TSubclassOf< UMovieSceneTrack > Type) const override
Returns whether a track class is supported by this tool.
double UnwindChannel (const double &OldValue, double NewValue)
Helper function to fix-up Euler rotations if they would go over 180 degrees due to interpolation.
void UpdateActiveMode ()
Update the current active edit mode when a subtrack or section is selected.
void UpdateOrigin (FVector InPosition, FRotator InRotation)
Called when the editor mode has made external changes to the origin data.
Public Member Functions inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
FKeyframeTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
~FKeyframeTrackEditor ()
Virtual destructor.
Public Member Functions inherited from FMovieSceneTrackEditor
FMovieSceneTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FMovieSceneTrackEditor ()
Destructor.
virtual UMovieSceneTrack * AddTrack (UMovieScene *FocusedMovieScene, const FGuid &ObjectHandle, TSubclassOf< class UMovieSceneTrack > TrackClass, FName UniqueTypeName) override
Add a new track to the sequence.
void AnimatablePropertyChanged (FOnKeyProperty OnKeyProperty)
virtual void BindCommands (TSharedRef< FUICommandList > SequencerCommandBindings) override
Allows the track editors to bind commands.
virtual void BuildObjectBindingColumnWidgets (TFunctionRef< TSharedRef< SHorizontalBox >()> GetEditBox, const UE::Sequencer::TViewModelPtr< UE::Sequencer::FObjectBindingModel > &ObjectBinding, const UE::Sequencer::FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Build a column widget for the specified object binding on the outliner.
virtual void BuildObjectBindingTrackMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass) override
Builds up the object binding track menu for the outliner.
virtual TSharedPtr< SWidget > BuildOutlinerEditColumnWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the edit column for outliner nodes which represent tracks which are edited by this editor.
virtual void BuildPinnedAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildTrackSidebarMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the sidebar menu for the track.
FFindOrCreateHandleResult FindOrCreateHandleToObject (UObject *Object, bool bCreateHandleIfMissing=true, const FName &CreatedFolderName=NAME_None)
template<typename TrackClass>
FFindOrCreateRootTrackResult< TrackClass > FindOrCreateRootTrack ()
Find or add a track of the specified type in the focused movie scene.
FFindOrCreateTrackResult FindOrCreateTrackForObject (const FGuid &ObjectHandle, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName=NAME_None, bool bCreateTrackIfMissing=true)
UMovieSceneSequence * GetMovieSceneSequence () const
TSharedPtr< ISequencer > GetSequencer () const
FFrameNumber GetTimeForKey ()
void UpdatePlaybackRange ()
Public Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedRef< FMovieSceneTrackEditor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneTrackEditor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from ISequencerTrackEditor
virtual ~ISequencerTrackEditor ()
Virtual destructor.
virtual void BuildObjectBindingContextMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Builds up the object binding cpmtext menu for the outliner.
virtual void BuildObjectBindingEditButtons (TSharedPtr< SHorizontalBox > EditBox, const FGuid &ObjectBinding, const UClass *ObjectClass)
Deprecated in principle, not practice (due to difficulty deprecating public virtual functions).
virtual void ExtendObjectBindingTrackMenu (TSharedRef< FExtender > Extender, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Extend the object binding track menu for the specified binding and class.
virtual bool HasTransformKeyOverridePriority () const
If true this track has priority when setting transform keys and should be the only one to set them.
virtual void ObjectImplicitlyAdded (UObject *InObject)
Handle this object being implicitly added.
virtual void ObjectImplicitlyRemoved (UObject *InObject)
Handle this object being implicitly removed.
virtual void OnPostSaveWorld (UWorld *World)
Called after the sequencer has re-evaluated all objects after saving the level.
virtual void OnPreSaveWorld (UWorld *World)
Called before the sequencer restores pre-animated state on all objects before saving the level.
Static Public Member Functions
static TSharedRef< ISequencerTrackEditor > CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer)
Creates an instance of this class.
Static Public Member Functions inherited from FSubTrackEditor
static TSharedRef< ISequencerTrackEditor > CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer)
Creates an instance of this class.
Static Public Member Functions inherited from FMovieSceneTrackEditor
static void BeginKeying (FFrameNumber InFrameNumber)
Initiate keying when there is more than one object to key (ie.
static void EndKeying ()
Protected Member Functions
virtual bool CanHandleAssetAdded (UMovieSceneSequence *Sequence) const override
Whether to handle this asset being dropped onto the sequence as opposed to a specific track.
virtual bool HandleAddSubTrackMenuEntryCanExecute () const override
Callback for determining whether the "Add Subsequence" menu entry can execute.
Protected Member Functions inherited from FSubTrackEditor
UMovieSceneSubTrack * FindOrCreateSubTrack (UMovieScene *MovieScene, UMovieSceneTrack *Track) const
Find or create a sub track.
virtual void GetSupportedSequenceClassPaths (TArray< FTopLevelAssetPath > &OutClassPaths) const
Get the list of supported sequence class paths.
TSharedRef< SWidget > HandleAddSubSequenceComboButtonGetMenuContent (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > TrackModel)
Callback for generating the menu of the "Add Sequence" combo button.
virtual void HandleAddSubTrackMenuEntryExecute ()
Callback for executing the "Add Subsequence" menu entry.
UE_DEPRECATED (5.3, "CreateNewTrack has been deprecated, please implement GetSubTrackClass") virtual UMovieSceneSubTrack *CreateNewTrack(UMovieScene *MovieScene) const
Protected Member Functions inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
FKeyPropertyResult AddKeysToObjects (TArrayView< UObject *const > ObjectsToKey, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(UMovieSceneSubTrack *)> OnInitializeNewTrack, const GenerateKeysCallback &OnGenerateKeys)
FKeyPropertyResult AddKeysToSection (UMovieSceneSection *Section, FFrameNumber KeyTime, const FGeneratedTrackKeys &Keys, ESequencerKeyMode KeyMode, EKeyFrameTrackEditorSetDefault SetDefault=EKeyFrameTrackEditorSetDefault::SetDefault)
virtual bool ModifyGeneratedKeysByCurrentAndWeight (UObject *Object, UMovieSceneTrack *Track, UMovieSceneSection *SectionToKey, FFrameNumber Time, FGeneratedTrackKeys &GeneratedTotalKeys, float Weight) const
Scale the generated keys by the the current value and the weight.
Protected Member Functions inherited from FMovieSceneTrackEditor
UMovieScene * GetFocusedMovieScene () const
Gets the currently focused movie scene, if any.
Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
ECheckBoxState AreShotsLocked () const
Delegate for shots button lock state.
void ExportEDL ()
Callback for ExportEDL.
void ExportFCPXML ()
Callback for ExportFCPXML.
FText GetLockShotsToolTip () const
Delegate for shots button lock tooltip.
void ImportEDL ()
Callback for ImportEDL.
void ImportFCPXML ()
Callback for ImportFCPXML.
void OnLockShotsClicked (ECheckBoxState CheckBoxState)
Delegate for locked shots button.
Private Attributes
TSharedPtr< FTrackEditorThumbnailPool > ThumbnailPool
The Thumbnail pool which draws all the viewport thumbnails for the shot track.
Additional Inherited Members
Public Types inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
using GenerateKeysCallback
Static Protected Member Functions inherited from FKeyframeTrackEditor< UMovieSceneSubTrack >
static bool CanAutoKeySection (UMovieSceneSection *Section, FFrameNumber Time)
Check whether we can autokey the specified section at the specified time.
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Tools for cinematic shots.
Definition at line 25 of file CinematicShotTrackEditor.h.
Constructor & Destructor Documentation
FCinematicShotTrackEditor()
FCinematicShotTrackEditor::FCinematicShotTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
Parameters
InSequencer The sequencer instance to be used by this tool.
~FCinematicShotTrackEditor()
virtual FCinematicShotTrackEditor::~FCinematicShotTrackEditor () inline virtual
Virtual destructor.
Definition at line 37 of file CinematicShotTrackEditor.h.
Member Function Documentation
AreShotsLocked()
ECheckBoxState FCinematicShotTrackEditor::AreShotsLocked () const private
Delegate for shots button lock state.
References AreShotsLocked().
Referenced by AreShotsLocked().
BuildOutlinerColumnWidget()
virtual TSharedPtr< SWidget > FCinematicShotTrackEditor::BuildOutlinerColumnWidget (const FBuildColumnWidgetParams & Params, const FName & ColumnName) override virtual
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
Parameters
Params Parameter struct containing data relevant to the edit widget
ColumnName The name of the column. See FCommonOutlinerNames
Returns
The the widget to display in the outliner, or an empty shared ptr if not widget is to be displayed.
Reimplemented from FMovieSceneTrackEditor.
References BuildOutlinerColumnWidget(), and Params.
Referenced by BuildOutlinerColumnWidget().
BuildTrackContextMenu()
virtual void FCinematicShotTrackEditor::BuildTrackContextMenu (FMenuBuilder & MenuBuilder, UMovieSceneTrack * Track) override virtual
Builds the context menu for the track.
Parameters
MenuBuilder The menu builder to use to build the track menu.
Reimplemented from FKeyframeTrackEditor< UMovieSceneSubTrack >.
References BuildTrackContextMenu().
Referenced by BuildTrackContextMenu().
CanHandleAssetAdded()
virtual bool FCinematicShotTrackEditor::CanHandleAssetAdded (UMovieSceneSequence * Sequence) const override protected virtual
Whether to handle this asset being dropped onto the sequence as opposed to a specific track.
Reimplemented from FSubTrackEditor.
References CanHandleAssetAdded().
Referenced by CanHandleAssetAdded().
CreateTrackEditor()
TSharedRef< ISequencerTrackEditor > FCinematicShotTrackEditor::CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer) static
Creates an instance of this class.
Called by a sequencer .
Parameters
OwningSequencer The sequencer instance to be used by this tool.
Returns
The new instance of this class.
ExportEDL()
void FCinematicShotTrackEditor::ExportEDL () private
Callback for ExportEDL.
References ExportEDL().
Referenced by ExportEDL().
ExportFCPXML()
void FCinematicShotTrackEditor::ExportFCPXML () private
Callback for ExportFCPXML.
References ExportFCPXML().
Referenced by ExportFCPXML().
GetDefaultSubsequenceDirectory()
virtual FString FCinematicShotTrackEditor::GetDefaultSubsequenceDirectory () const override virtual
Get the sub sequence directory.
Reimplemented from FSubTrackEditor.
References GetDefaultSubsequenceDirectory().
Referenced by GetDefaultSubsequenceDirectory().
GetDefaultSubsequenceName()
virtual FString FCinematicShotTrackEditor::GetDefaultSubsequenceName () const override virtual
Get the default sub sequence name.
Reimplemented from FSubTrackEditor.
References GetDefaultSubsequenceName().
Referenced by GetDefaultSubsequenceName().
GetDisplayName()
virtual FText FCinematicShotTrackEditor::GetDisplayName () const override virtual
The display name text to use in the UX.
Currently only used for sorting.
Reimplemented from FSubTrackEditor.
References GetDisplayName().
Referenced by GetDisplayName().
GetLockShotsToolTip()
FText FCinematicShotTrackEditor::GetLockShotsToolTip () const private
Delegate for shots button lock tooltip.
References GetLockShotsToolTip().
Referenced by GetLockShotsToolTip().
GetSubSectionDisplayName()
virtual FString FCinematicShotTrackEditor::GetSubSectionDisplayName (const UMovieSceneSubSection * Section) const override virtual
Get the display name for the sub section.
Reimplemented from FSubTrackEditor.
References GetSubSectionDisplayName().
Referenced by GetSubSectionDisplayName().
GetSubTrackBrushName()
virtual FName FCinematicShotTrackEditor::GetSubTrackBrushName () const override virtual
Get the brush used for the sub track editor.
Reimplemented from FSubTrackEditor.
References GetSubTrackBrushName().
Referenced by GetSubTrackBrushName().
GetSubTrackClass()
virtual TSubclassOf< UMovieSceneSubTrack > FCinematicShotTrackEditor::GetSubTrackClass () const virtual
Get the UMovieSceneSubTrack class.
Reimplemented from FSubTrackEditor.
References GetSubTrackClass().
Referenced by GetSubTrackClass().
GetSubTrackName()
virtual FText FCinematicShotTrackEditor::GetSubTrackName () const override virtual
Get the name of the sub track.
Reimplemented from FSubTrackEditor.
References GetSubTrackName().
Referenced by GetSubTrackName().
GetSubTrackToolTip()
virtual FText FCinematicShotTrackEditor::GetSubTrackToolTip () const override virtual
Get the tooltip for this sub track editor.
Reimplemented from FSubTrackEditor.
References GetSubTrackToolTip().
Referenced by GetSubTrackToolTip().
HandleAddSubTrackMenuEntryCanExecute()
virtual bool FCinematicShotTrackEditor::HandleAddSubTrackMenuEntryCanExecute () const override protected virtual
Callback for determining whether the "Add Subsequence" menu entry can execute.
Reimplemented from FSubTrackEditor.
References HandleAddSubTrackMenuEntryCanExecute().
Referenced by HandleAddSubTrackMenuEntryCanExecute().
ImportEDL()
void FCinematicShotTrackEditor::ImportEDL () private
Callback for ImportEDL.
References ImportEDL().
Referenced by ImportEDL().
ImportFCPXML()
void FCinematicShotTrackEditor::ImportFCPXML () private
Callback for ImportFCPXML.
References ImportFCPXML().
Referenced by ImportFCPXML().
MakeSectionInterface()
virtual TSharedRef< ISequencerSection > FCinematicShotTrackEditor::MakeSectionInterface (UMovieSceneSection & SectionObject, UMovieSceneTrack & Track, FGuid ObjectBinding) override virtual
Called to generate a section layout for a particular section.
Parameters
SectionObject The section to make UI for.
Track The track that owns the section.
ObjectBinding the object binding for the track that owns the section, if there is one.
Reimplemented from FSubTrackEditor.
References MakeSectionInterface().
Referenced by MakeSectionInterface().
OnLockShotsClicked()
void FCinematicShotTrackEditor::OnLockShotsClicked (ECheckBoxState CheckBoxState) private
Delegate for locked shots button.
References OnLockShotsClicked().
Referenced by OnLockShotsClicked().
RenderShots()
void FCinematicShotTrackEditor::RenderShots (const TArray< UMovieSceneCinematicShotSection * > & Sections)
References RenderShots(), and Sections.
Referenced by RenderShots().
SupportsSequence()
virtual bool FCinematicShotTrackEditor::SupportsSequence (UMovieSceneSequence * InSequence) const override virtual
Returns whether a sequence is supported by this tool.
Parameters
InSequence The sequence that could be supported.
Returns
true if the type is supported.
Reimplemented from FSubTrackEditor.
References SupportsSequence().
Referenced by SupportsSequence().
Tick()
virtual void FCinematicShotTrackEditor::Tick (float DeltaTime) override virtual
Ticks this tool.
Parameters
DeltaTime The time since the last tick.
Reimplemented from FMovieSceneTrackEditor.
References DeltaTime, and Tick().
Referenced by Tick().
UE_DEPRECATED()
FCinematicShotTrackEditor::UE_DEPRECATED (5. 5, "Use FCameraCutPlaybackCapability::LastViewTargetCamera instead.") const
Field Documentation
ThumbnailPool
TSharedPtr<FTrackEditorThumbnailPool> FCinematicShotTrackEditor::ThumbnailPool private
The Thumbnail pool which draws all the viewport thumbnails for the shot track.
Definition at line 109 of file CinematicShotTrackEditor.h.
The documentation for this class was generated from the following file:
Editor/MovieSceneTools/Public/TrackEditors/CinematicShotTrackEditor.h