Unreal Engine 5.6 C++ API: TMulticastDelegateBase< UserPolicy > Class Template Reference
TMulticastDelegateBase< UserPolicy > Class Template Reference
Abstract base class for multicast delegates.
#include "MulticastDelegateBase.h"
Public Member Functions
TMulticastDelegateBase (TMulticastDelegateBase &&Other)
void Clear ()
Removes all functions from this delegate's invocation list.
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this delegate's invocation list and the delegates stored within it, not including sizeof(*this).
bool IsBound () const
Checks to see if any functions are bound to this multi-cast delegate.
bool IsBoundToObject (FDelegateUserObjectConst InUserObject) const
Checks to see if any functions are bound to the given user object.
TMulticastDelegateBase & operator= (TMulticastDelegateBase &&Other)
int32 RemoveAll (FDelegateUserObjectConst InUserObject)
Removes all functions from this multi-cast delegate's invocation list that are bound to the specified UserObject.
Protected Types
using InvocationListType = TArray<UnicastDelegateType, FMulticastInvocationListAllocatorType>
using Super = TDelegateAccessHandlerBase<typename UserPolicy::FThreadSafetyMode>
using UnicastDelegateType = TDelegateBase<FNotThreadSafeNotCheckedDelegateMode>
Protected Member Functions
TMulticastDelegateBase ()
Hidden default constructor.
template<typename NewDelegateType>
FDelegateHandle AddDelegateInstance (NewDelegateType &&NewDelegateBaseRef)
Adds the given delegate instance to the invocation list.
template<typename DelegateInstanceInterfaceType, typename... ParamTypes>
void Broadcast (ParamTypes... Params) const
template<typename DelegateInstanceInterfaceType>
void CopyFrom (const TMulticastDelegateBase &Other)
bool RemoveDelegateInstance (FDelegateHandle Handle)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Private Member Functions
void ClearUnchecked ()
void CompactInvocationList (bool CheckThreshold=false)
Removes any expired or deleted functions from the invocation list.
InvocationListType & GetInvocationList ()
Gets a read-only reference to the invocation list.
const InvocationListType & GetInvocationList () const
int32 GetInvocationListLockCount () const
Returns the lock counter for the invocation list.
void LockInvocationList () const
Increments the lock counter for the invocation list.
bool ShouldSkipCompactionUnderAutoRTFM () const
void UnlockInvocationList () const
Decrements the lock counter for the invocation list.
Private Attributes
int32 CompactionThreshold = 2
Used to determine when a compaction should happen.
InvocationListType InvocationList
Holds the collection of delegate instances to invoke.
int32 InvocationListLockCount = 0
Holds a lock counter for the invocation list.
Detailed Description
template<typename UserPolicy>
class TMulticastDelegateBase< UserPolicy >
Abstract base class for multicast delegates.
Definition at line 27 of file MulticastDelegateBase.h.
Member Typedef Documentation
InvocationListType
template<typename UserPolicy> using TMulticastDelegateBase< UserPolicy >::InvocationListType = TArray<UnicastDelegateType, FMulticastInvocationListAllocatorType> protected
Definition at line 39 of file MulticastDelegateBase.h.
Super
template<typename UserPolicy> using TMulticastDelegateBase< UserPolicy >::Super = TDelegateAccessHandlerBase<typename UserPolicy::FThreadSafetyMode> protected
Definition at line 30 of file MulticastDelegateBase.h.
UnicastDelegateType
template<typename UserPolicy> using TMulticastDelegateBase< UserPolicy >::UnicastDelegateType = TDelegateBase<FNotThreadSafeNotCheckedDelegateMode> protected
Definition at line 37 of file MulticastDelegateBase.h.
Constructor & Destructor Documentation
TMulticastDelegateBase() [1/2]
template<typename UserPolicy> TMulticastDelegateBase< UserPolicy >::TMulticastDelegateBase (TMulticastDelegateBase< UserPolicy > && Other) inline
Definition at line 42 of file MulticastDelegateBase.h.
TMulticastDelegateBase() [2/2]
template<typename UserPolicy> TMulticastDelegateBase< UserPolicy >::TMulticastDelegateBase () inline protected
Hidden default constructor.
Definition at line 205 of file MulticastDelegateBase.h.
Member Function Documentation
AddDelegateInstance()
template<typename UserPolicy> template<typename NewDelegateType> FDelegateHandle TMulticastDelegateBase< UserPolicy >::AddDelegateInstance (NewDelegateType && NewDelegateBaseRef) inline protected
Adds the given delegate instance to the invocation list.
Parameters
NewDelegateBaseRef The delegate instance to add.
Definition at line 278 of file MulticastDelegateBase.h.
Broadcast()
template<typename UserPolicy> template<typename DelegateInstanceInterfaceType, typename... ParamTypes> void TMulticastDelegateBase< UserPolicy >::Broadcast (ParamTypes... Params) const inline protected
Definition at line 240 of file MulticastDelegateBase.h.
Clear()
template<typename UserPolicy> void TMulticastDelegateBase< UserPolicy >::Clear () inline
Removes all functions from this delegate's invocation list.
Definition at line 79 of file MulticastDelegateBase.h.
ClearUnchecked()
template<typename UserPolicy> void TMulticastDelegateBase< UserPolicy >::ClearUnchecked () inline private
Definition at line 426 of file MulticastDelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Clear(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::CopyFrom(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::operator=().
CompactInvocationList()
template<typename UserPolicy> void TMulticastDelegateBase< UserPolicy >::CompactInvocationList (bool CheckThreshold = false) inline private
Removes any expired or deleted functions from the invocation list.
See also
RequestCompaction
Definition at line 335 of file MulticastDelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::AddDelegateInstance(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Broadcast(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::ClearUnchecked(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveDelegateInstance().
CopyFrom()
template<typename UserPolicy> template<typename DelegateInstanceInterfaceType> void TMulticastDelegateBase< UserPolicy >::CopyFrom (const TMulticastDelegateBase< UserPolicy > & Other) inline protected
Definition at line 213 of file MulticastDelegateBase.h.
GetAllocatedSize()
template<typename UserPolicy> SIZE_T TMulticastDelegateBase< UserPolicy >::GetAllocatedSize () const inline
Returns the amount of memory allocated by this delegate's invocation list and the delegates stored within it, not including sizeof(*this).
Definition at line 189 of file MulticastDelegateBase.h.
GetInvocationList() [1/2]
template<typename UserPolicy> InvocationListType & TMulticastDelegateBase< UserPolicy >::GetInvocationList () inline private
Gets a read-only reference to the invocation list.
Returns
The invocation list.
Definition at line 387 of file MulticastDelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Broadcast().
GetInvocationList() [2/2]
template<typename UserPolicy> const InvocationListType & TMulticastDelegateBase< UserPolicy >::GetInvocationList () const inline private
Definition at line 392 of file MulticastDelegateBase.h.
GetInvocationListLockCount()
template<typename UserPolicy> int32 TMulticastDelegateBase< UserPolicy >::GetInvocationListLockCount () const inline private
Returns the lock counter for the invocation list.
Definition at line 420 of file MulticastDelegateBase.h.
IsBound()
template<typename UserPolicy> bool TMulticastDelegateBase< UserPolicy >::IsBound () const inline
Checks to see if any functions are bound to this multi-cast delegate.
Returns
true if any functions are bound, false otherwise.
Definition at line 91 of file MulticastDelegateBase.h.
IsBoundToObject()
template<typename UserPolicy> bool TMulticastDelegateBase< UserPolicy >::IsBoundToObject (FDelegateUserObjectConst InUserObject) const inline
Checks to see if any functions are bound to the given user object.
Returns
True if any functions are bound to InUserObject, false otherwise.
Definition at line 110 of file MulticastDelegateBase.h.
LockInvocationList()
template<typename UserPolicy> void TMulticastDelegateBase< UserPolicy >::LockInvocationList () const inline private
Increments the lock counter for the invocation list.
Definition at line 398 of file MulticastDelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Broadcast().
operator=()
template<typename UserPolicy> TMulticastDelegateBase & TMulticastDelegateBase< UserPolicy >::operator= (TMulticastDelegateBase< UserPolicy > && Other) inline
Definition at line 47 of file MulticastDelegateBase.h.
RemoveAll()
template<typename UserPolicy> int32 TMulticastDelegateBase< UserPolicy >::RemoveAll (FDelegateUserObjectConst InUserObject) inline
Removes all functions from this multi-cast delegate's invocation list that are bound to the specified UserObject.
Note that the order of the delegates may not be preserved!
Parameters
InUserObject The object to remove all delegates for.
Returns
The number of delegates successfully removed.
Definition at line 133 of file MulticastDelegateBase.h.
RemoveDelegateInstance()
template<typename UserPolicy> bool TMulticastDelegateBase< UserPolicy >::RemoveDelegateInstance (FDelegateHandle Handle) inline protected
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Parameters
Handle The handle of the delegate instance to remove.
Returns
true if the delegate was successfully removed.
Definition at line 299 of file MulticastDelegateBase.h.
ShouldSkipCompactionUnderAutoRTFM()
template<typename UserPolicy> bool TMulticastDelegateBase< UserPolicy >::ShouldSkipCompactionUnderAutoRTFM () const inline private
Definition at line 321 of file MulticastDelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::CompactInvocationList(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::LockInvocationList(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveAll(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::UnlockInvocationList().
UnlockInvocationList()
template<typename UserPolicy> void TMulticastDelegateBase< UserPolicy >::UnlockInvocationList () const inline private
Decrements the lock counter for the invocation list.
Definition at line 409 of file MulticastDelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Broadcast().
Field Documentation
CompactionThreshold
template<typename UserPolicy> int32 TMulticastDelegateBase< UserPolicy >::CompactionThreshold = 2 private
Used to determine when a compaction should happen.
Definition at line 440 of file MulticastDelegateBase.h.
InvocationList
template<typename UserPolicy> InvocationListType TMulticastDelegateBase< UserPolicy >::InvocationList private
Holds the collection of delegate instances to invoke.
Definition at line 437 of file MulticastDelegateBase.h.
InvocationListLockCount
template<typename UserPolicy> int32 TMulticastDelegateBase< UserPolicy >::InvocationListLockCount = 0 mutable private
Holds a lock counter for the invocation list.
Definition at line 443 of file MulticastDelegateBase.h.
The documentation for this class was generated from the following files:
Runtime/Core/Public/Delegates/DelegateBase.h
Runtime/Core/Public/Delegates/MulticastDelegateBase.h