Unreal Engine 5.6 C++ API: Metasound::FGraph Class Reference
Metasound::FGraph Class Reference
FGraph contains the edges between nodes as well as input and output vertices.
#include "MetasoundGraph.h"
Data Structures
struct FDeprecationNodeStorageAdapter
class FFactory
Public Member Functions
METASOUNDGRAPHCORE_API FGraph (const FString &InInstanceName, const FGuid &InInstanceID, TSharedPtr< const IOperatorData > InNodeConfig={})
virtual ~FGraph ()=default
METASOUNDGRAPHCORE_API void AddDataEdge (const FDataEdge &InEdge)
Add an edge to the graph.
METASOUNDGRAPHCORE_API bool AddDataEdge (const INode &FromNode, const FVertexName &FromVertexKey, const INode &ToNode, const FVertexName &ToVertexKey)
Add an edge to the graph, connecting two vertices from two nodes.
METASOUNDGRAPHCORE_API void AddInputDataDestination (const FInputDataDestination &InDestination)
Add an input data destination to describe how data provided outside this graph should be routed internally.
METASOUNDGRAPHCORE_API bool AddInputDataDestination (const INode &InNode, const FVertexName &InVertexName)
Add an input data destination to describe how data provided outside this graph should be routed internally.
METASOUNDGRAPHCORE_API void AddInputNode (FGuid InNodeID, const FVertexName &InVertexName, TUniquePtr< INode > InNode)
Add an input node to this graph.
METASOUNDGRAPHCORE_API void AddNode (const FGuid &InNodeID, TUniquePtr< INode > InNode)
Store a node on this graph.
METASOUNDGRAPHCORE_API void AddOutputDataSource (const FOutputDataSource &InSource)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
METASOUNDGRAPHCORE_API bool AddOutputDataSource (const INode &InNode, const FVertexName &InVertexName)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
METASOUNDGRAPHCORE_API void AddOutputNode (FGuid InNodeID, const FVertexName &InVertexName, TUniquePtr< INode > InNode)
Add an output node to this graph.
METASOUNDGRAPHCORE_API const INode * FindNode (const FGuid &InNodeID) const
Retrieve node by node ID.
METASOUNDGRAPHCORE_API int32 FindUnconnectedNodes (TArray< TPair< FGuid, const INode * > > &OutUnconnectedNodes) const
Populates an array with all nodes which exist in the graph but do not have any connections.
virtual METASOUNDGRAPHCORE_API const TArray< FDataEdge > & GetDataEdges () const override
Retrieve all the edges associated with a graph.
virtual METASOUNDGRAPHCORE_API FOperatorFactorySharedRef GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
virtual METASOUNDGRAPHCORE_API const FInputDataDestinationCollection & GetInputDataDestinations () const override
Get vertices which contain input parameters.
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FVertexName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata about this graph.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this graph.
virtual METASOUNDGRAPHCORE_API const FOutputDataSourceCollection & GetOutputDataSources () const override
Get vertices which contain output parameters.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the current vertex interface.
METASOUNDGRAPHCORE_API bool RemoveDataEdge (const INode &FromNode, const FVertexName &FromVertexKey, const INode &ToNode, const FVertexName &ToVertexKey)
Remove the given data edge.
METASOUNDGRAPHCORE_API void RemoveDataEdgesWithNode (const INode &InNode)
Removes all edges with connected to the node.
METASOUNDGRAPHCORE_API bool RemoveInputDataDestination (const FVertexName &InVertexName)
Remove an input data destination by vertex name.
METASOUNDGRAPHCORE_API bool RemoveNode (const FGuid &InNodeID, bool bInRemoveDataEdgesWithNode=true)
Removes node from graph.
METASOUNDGRAPHCORE_API bool RemoveOutputDataSource (const FVertexName &InVertexName)
Remove an output data source by vertex name.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default value associated with an input vertex.
METASOUNDGRAPHCORE_API void SetNodeDefaultInput (const FGuid &InNodeID, const FVertexName &InVertexName, const FLiteral &InLiteral)
Set the input default literal for a node that exists in the graph.
template<typename PredicateType>
UE_DEPRECATED (5.3, "Removing data edges by predicate is no longer supported") void RemoveDataEdgeByPredicate(const PredicateType &Predicate)
Removes all edges for which that predicate returns true.
UE_DEPRECATED (5.6, "FGraphs can only set their interface by adding inputs and outputs.") METASOUNDGRAPHCORE_API virtual bool SetVertexInterface(const FVertexInterface &InInterface) override
Set the vertex interface.
UE_DEPRECATED (5.6, "This function no longer serves a purpose.") METASOUNDGRAPHCORE_API virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const override
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "Use AddInputNode(...) which accepts a unique ptr") METASOUNDGRAPHCORE_API void AddInputNode(FGuid InNodeID
Add an input node to this graph.
UE_DEPRECATED (5.6, "Use AddNode(...) which accepts a unique ptr") METASOUNDGRAPHCORE_API void AddNode(const FGuid &InNodeID
UE_DEPRECATED (5.6, "Use AddOutputNode(...) which accepts a unique ptr") METASOUNDGRAPHCORE_API void AddOutputNode(FGuid InNodeID
Add an output node to this graph.
Public Member Functions inherited from Metasound::IGraph
virtual ~IGraph ()
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Data Fields
TSharedPtr< const INode > InNode
const FVertexName TSharedPtr< const INode > InNode
const FVertexName & InVertexName
Private Member Functions
METASOUNDGRAPHCORE_API INode * FindMutableNode (const FGuid &InNodeID)
Private Attributes
TArray< FDataEdge > Edges
FInputDataDestinationCollection InputDestinations
FGuid InstanceID
FVertexName InstanceName
FNodeClassMetadata Metadata
TSortedMap< FGuid, FDeprecationNodeStorageAdapter > Nodes
TSharedPtr< const IOperatorData > OperatorData
FOutputDataSourceCollection OutputSources
Detailed Description
FGraph contains the edges between nodes as well as input and output vertices.
FGraph does not maintain ownership over any node. Nodes used within the graph must be valid for the lifetime of the graph.
Definition at line 19 of file MetasoundGraph.h.
Constructor & Destructor Documentation
FGraph()
METASOUNDGRAPHCORE_API Metasound::FGraph::FGraph (const FString & InInstanceName, const FGuid & InInstanceID, TSharedPtr< const IOperatorData > InNodeConfig = {})
References UE_API.
Referenced by Metasound::FFrontendGraph::UE_DEPRECATED().
~FGraph()
virtual Metasound::FGraph::~FGraph () virtual default
Member Function Documentation
AddDataEdge() [1/2]
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddDataEdge (const FDataEdge & InEdge)
Add an edge to the graph.
References AddDataEdge(), and UE_API.
Referenced by AddDataEdge(), and AddDataEdge().
AddDataEdge() [2/2]
METASOUNDGRAPHCORE_API bool Metasound::FGraph::AddDataEdge (const INode & FromNode, const FVertexName & FromVertexKey, const INode & ToNode, const FVertexName & ToVertexKey)
Add an edge to the graph, connecting two vertices from two nodes.
Parameters
FromNode - Node which contains the output vertex.
FromVertexKey - Key of the vertex in the FromNode.
ToNode - Node which contains the input vertex.
ToVertexKey - Key of the vertex in the ToNode.
Returns
True if the edge was successfully added. False otherwise.
References AddDataEdge(), and UE_API.
AddInputDataDestination() [1/2]
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddInputDataDestination (const FInputDataDestination & InDestination)
Add an input data destination to describe how data provided outside this graph should be routed internally.
References AddInputDataDestination(), and UE_API.
AddInputDataDestination() [2/2]
METASOUNDGRAPHCORE_API bool Metasound::FGraph::AddInputDataDestination (const INode & InNode, const FVertexName & InVertexName)
Add an input data destination to describe how data provided outside this graph should be routed internally.
Parameters
InNode - Node which receives the data.
InVertexName - Key for input vertex on InNode.
Returns
True if the destination was successfully added. False otherwise.
References AddInputDataDestination(), InNode, InVertexName, and UE_API.
Referenced by AddInputDataDestination(), and AddInputDataDestination().
AddInputNode()
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddInputNode (FGuid InNodeID, const FVertexName & InVertexName, TUniquePtr< INode > InNode)
Add an input node to this graph.
Parameters
InNodeID - A unique ID associated with the node.
InVertexName - The key for the graph input vertex.
InNode - A unique pointer to an input node.
References AddInputNode(), InNode, InVertexName, and UE_API.
Referenced by AddInputNode().
AddNode()
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddNode (const FGuid & InNodeID, TUniquePtr< INode > InNode)
Store a node on this graph.
Parameters
InNodeID - A unique ID associated with the node.
InNode - A shared pointer to a node.
References AddNode(), InNode, and UE_API.
Referenced by AddNode().
AddOutputDataSource() [1/2]
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddOutputDataSource (const FOutputDataSource & InSource)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
References AddOutputDataSource(), and UE_API.
AddOutputDataSource() [2/2]
METASOUNDGRAPHCORE_API bool Metasound::FGraph::AddOutputDataSource (const INode & InNode, const FVertexName & InVertexName)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
Parameters
InNode - Node which produces the data.
InVertexName - Key for output vertex on InNode.
Returns
True if the source was successfully added. False otherwise.
References AddOutputDataSource(), InNode, InVertexName, and UE_API.
Referenced by AddOutputDataSource(), and AddOutputDataSource().
AddOutputNode()
METASOUNDGRAPHCORE_API void Metasound::FGraph::AddOutputNode (FGuid InNodeID, const FVertexName & InVertexName, TUniquePtr< INode > InNode)
Add an output node to this graph.
Parameters
InNodeID - A unique ID associated with the node.
InVertexName - The key for the graph output vertex.
InNode - A shared pointer to an output node.
References AddOutputNode(), InNode, InVertexName, and UE_API.
Referenced by AddOutputNode(), and UE_DEPRECATED().
FindMutableNode()
METASOUNDGRAPHCORE_API INode * Metasound::FGraph::FindMutableNode (const FGuid & InNodeID) private
References FindMutableNode(), and UE_API.
Referenced by FindMutableNode().
FindNode()
METASOUNDGRAPHCORE_API const INode * Metasound::FGraph::FindNode (const FGuid & InNodeID) const
Retrieve node by node ID.
Parameters
InNodeID - The NodeID of the requested Node.
Returns
Pointer to the Node if it is stored on this graph. nullptr otherwise.
References FindNode(), and UE_API.
Referenced by FindNode().
FindUnconnectedNodes()
METASOUNDGRAPHCORE_API int32 Metasound::FGraph::FindUnconnectedNodes (TArray< TPair< FGuid, const INode * > > & OutUnconnectedNodes) const
Populates an array with all nodes which exist in the graph but do not have any connections.
Parameters
OutUnconnectedNodes - Array to populate.
Returns
Number of unconnected nodes found.
References FindUnconnectedNodes(), and UE_API.
Referenced by FindUnconnectedNodes().
GetDataEdges()
virtual METASOUNDGRAPHCORE_API const TArray< FDataEdge > & Metasound::FGraph::GetDataEdges () const override virtual
Retrieve all the edges associated with a graph.
Implements Metasound::IGraph.
References UE_API.
GetDefaultOperatorFactory()
virtual METASOUNDGRAPHCORE_API FOperatorFactorySharedRef Metasound::FGraph::GetDefaultOperatorFactory () const override virtual
Return a reference to the default operator factory.
Implements Metasound::INode.
References GetDefaultOperatorFactory(), and UE_API.
Referenced by GetDefaultOperatorFactory().
GetInputDataDestinations()
virtual METASOUNDGRAPHCORE_API const FInputDataDestinationCollection & Metasound::FGraph::GetInputDataDestinations () const override virtual
Get vertices which contain input parameters.
Implements Metasound::IGraph.
References GetInputDataDestinations(), and UE_API.
Referenced by GetInputDataDestinations().
GetInstanceID()
virtual METASOUNDGRAPHCORE_API const FGuid & Metasound::FGraph::GetInstanceID () const override virtual
Return the ID of this specific instance of the node class.
Implements Metasound::INodeBase.
References UE_API.
GetInstanceName()
virtual METASOUNDGRAPHCORE_API const FVertexName & Metasound::FGraph::GetInstanceName () const override virtual
Return the name of this specific instance of the node class.
Implements Metasound::INodeBase.
References UE_API.
GetMetadata()
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & Metasound::FGraph::GetMetadata () const override virtual
Return metadata about this graph.
Implements Metasound::INodeBase.
References UE_API.
GetOperatorData()
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > Metasound::FGraph::GetOperatorData () const override virtual
Return the configuration for this graph.
References UE_API.
GetOutputDataSources()
virtual METASOUNDGRAPHCORE_API const FOutputDataSourceCollection & Metasound::FGraph::GetOutputDataSources () const override virtual
Get vertices which contain output parameters.
Implements Metasound::IGraph.
References GetOutputDataSources(), and UE_API.
Referenced by GetOutputDataSources().
GetVertexInterface()
virtual METASOUNDGRAPHCORE_API const FVertexInterface & Metasound::FGraph::GetVertexInterface () const override virtual
Return the current vertex interface.
Implements Metasound::INodeBase.
References UE_API.
RemoveDataEdge()
METASOUNDGRAPHCORE_API bool Metasound::FGraph::RemoveDataEdge (const INode & FromNode, const FVertexName & FromVertexKey, const INode & ToNode, const FVertexName & ToVertexKey)
Remove the given data edge.
Returns
True on success, false on failure.
References RemoveDataEdge(), and UE_API.
Referenced by RemoveDataEdge().
RemoveDataEdgesWithNode()
METASOUNDGRAPHCORE_API void Metasound::FGraph::RemoveDataEdgesWithNode (const INode & InNode)
Removes all edges with connected to the node.
References InNode, and UE_API.
RemoveInputDataDestination()
METASOUNDGRAPHCORE_API bool Metasound::FGraph::RemoveInputDataDestination (const FVertexName & InVertexName)
Remove an input data destination by vertex name.
Parameters
InVertexName - Name of vertex to remove.
Returns
True if destination existed and was successfully removed. False otherwise.
References InVertexName, RemoveInputDataDestination(), and UE_API.
Referenced by RemoveInputDataDestination().
RemoveNode()
METASOUNDGRAPHCORE_API bool Metasound::FGraph::RemoveNode (const FGuid & InNodeID, bool bInRemoveDataEdgesWithNode = true)
Removes node from graph.
Parameters
InNodeID - ID of node to remove.
bInRemoveDataEdgesWithNode - If true, will also call RemoveDataEdgesWithNode(...)
Returns
true if node exists and is removed, false otherwise.
References RemoveNode(), and UE_API.
Referenced by RemoveNode().
RemoveOutputDataSource()
METASOUNDGRAPHCORE_API bool Metasound::FGraph::RemoveOutputDataSource (const FVertexName & InVertexName)
Remove an output data source by vertex name.
Parameters
InVertexName - Name of vertex to remove.
Returns
True if source existed and was successfully removed. False otherwise.
References InVertexName, RemoveOutputDataSource(), and UE_API.
Referenced by RemoveOutputDataSource().
SetDefaultInput()
virtual METASOUNDGRAPHCORE_API void Metasound::FGraph::SetDefaultInput (const FVertexName & InVertexName, const FLiteral & InLiteral) override virtual
Set the default value associated with an input vertex.
Reimplemented from Metasound::INodeBase.
References InVertexName, and UE_API.
SetNodeDefaultInput()
METASOUNDGRAPHCORE_API void Metasound::FGraph::SetNodeDefaultInput (const FGuid & InNodeID, const FVertexName & InVertexName, const FLiteral & InLiteral)
Set the input default literal for a node that exists in the graph.
Parameters
InNodeID - ID of not to update.
InVertexName - Name of input vertex on the node.
InLiteral - Literal used to construct default input.
References InVertexName, SetNodeDefaultInput(), and UE_API.
Referenced by SetNodeDefaultInput().
UE_DEPRECATED() [1/6]
template<typename PredicateType> Metasound::FGraph::UE_DEPRECATED (5. 3, "Removing data edges by predicate is no longer supported") const & inline
Removes all edges for which that predicate returns true.
Parameters
Predicate - A callable object which accepts an FDataEdge and returns true if the edge should be removed.
Definition at line 99 of file MetasoundGraph.h.
References Edges, Predicate, and UE_DEPRECATED().
UE_DEPRECATED() [2/6]
Metasound::FGraph::UE_DEPRECATED (5. 6, "FGraphs can only set their interface by adding inputs and outputs.") const & override
Set the vertex interface.
If the vertex was successfully changed, returns true.
Parameters
InInterface - New interface for node.
Returns
True on success, false otherwise.
References UE_API.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/6]
Metasound::FGraph::UE_DEPRECATED (5. 6, "This function no longer serves a purpose.") const & override
Expresses whether a specific vertex interface is supported.
Parameters
InInterface - New interface.
Returns
True if the interface is supported, false otherwise.
References UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [4/6]
Metasound::FGraph::UE_DEPRECATED (5. 6, "Use AddInputNode(...) which accepts a unique ptr")
Add an input node to this graph.
Parameters
InNodeID - A unique ID associated with the node.
InVertexName - The key for the graph input vertex.
InNode - A shared pointer to an input node.
References UE_DEPRECATED().
UE_DEPRECATED() [5/6]
Metasound::FGraph::UE_DEPRECATED (5. 6, "Use AddNode(...) which accepts a unique ptr") const &
UE_DEPRECATED() [6/6]
Metasound::FGraph::UE_DEPRECATED (5. 6, "Use AddOutputNode(...) which accepts a unique ptr")
Add an output node to this graph.
Parameters
InNodeID - A unique ID associated with the node.
InVertexName - The key for the graph output vertex.
InNode - A shared pointer to an output node.
References AddOutputNode(), InNode, InVertexName, UE_API, and UE_DEPRECATED().
Field Documentation
Edges
TArray<FDataEdge> Metasound::FGraph::Edges private
Definition at line 256 of file MetasoundGraph.h.
Referenced by UE_DEPRECATED().
InNode [1/2]
const FVertexName TSharedPtr< const INode > Metasound::FGraph::InNode
Definition at line 109 of file MetasoundGraph.h.
Referenced by Metasound::FGraph::FDeprecationNodeStorageAdapter::FDeprecationNodeStorageAdapter(), Metasound::FGraph::FDeprecationNodeStorageAdapter::FDeprecationNodeStorageAdapter(), AddInputDataDestination(), AddInputNode(), AddNode(), AddOutputDataSource(), AddOutputNode(), RemoveDataEdgesWithNode(), and UE_DEPRECATED().
InNode [2/2]
const FVertexName TSharedPtr<const INode> Metasound::FGraph::InNode
Definition at line 133 of file MetasoundGraph.h.
InputDestinations
FInputDataDestinationCollection Metasound::FGraph::InputDestinations private
Definition at line 287 of file MetasoundGraph.h.
InstanceID
FGuid Metasound::FGraph::InstanceID private
Definition at line 251 of file MetasoundGraph.h.
InstanceName
FVertexName Metasound::FGraph::InstanceName private
Definition at line 250 of file MetasoundGraph.h.
InVertexName
const FVertexName & Metasound::FGraph::InVertexName
Definition at line 133 of file MetasoundGraph.h.
Referenced by AddInputDataDestination(), AddInputNode(), AddOutputDataSource(), AddOutputNode(), RemoveInputDataDestination(), RemoveOutputDataSource(), SetDefaultInput(), SetNodeDefaultInput(), and UE_DEPRECATED().
Metadata
FNodeClassMetadata Metasound::FGraph::Metadata private
Definition at line 253 of file MetasoundGraph.h.
Nodes
TSortedMap<FGuid, FDeprecationNodeStorageAdapter> Metasound::FGraph::Nodes private
Definition at line 285 of file MetasoundGraph.h.
OperatorData
TSharedPtr<const IOperatorData> Metasound::FGraph::OperatorData private
Definition at line 254 of file MetasoundGraph.h.
OutputSources
FOutputDataSourceCollection Metasound::FGraph::OutputSources private
Definition at line 288 of file MetasoundGraph.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundGraph.h