Unreal Engine 5.6 C++ API: FStaticMeshVertexBuffer Class Reference
FStaticMeshVertexBuffer Class Reference
Vertex buffer for a static mesh LOD.
#include "StaticMeshVertexBuffer.h"
Data Structures
class FTangentsVertexBuffer
class FTexcoordVertexBuffer
Public Member Functions
FStaticMeshVertexBuffer ()
Default constructor.
~FStaticMeshVertexBuffer ()
Destructor.
void AppendVertices (const FStaticMeshBuildVertex *Vertices, const uint32 NumVerticesToAppend, bool bUseBackwardsCompatibleF16TruncUVs=false)
Appends the specified vertices to the end of the buffer.
void BindLightMapVertexBuffer (const FVertexFactory *VertexFactory, struct FStaticMeshDataType &Data, int LightMapCoordinateIndex) const
void BindPackedTexCoordVertexBuffer (const FVertexFactory *VertexFactory, struct FStaticMeshDataType &Data, int32 MaxNumTexCoords=-1) const
void BindTangentVertexBuffer (const FVertexFactory *VertexFactory, struct FStaticMeshDataType &Data) const
void BindTexCoordVertexBuffer (const FVertexFactory *VertexFactory, struct FStaticMeshDataType &Data, int ClampedNumTexCoords=-1) const
void CleanUp ()
Delete existing resources.
void ClearMetaData ()
FBufferRHIRef CreateTangentsRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI vertex buffer with CPU data.
FBufferRHIRef CreateTexCoordRHIBuffer (FRHICommandListBase &RHICmdList)
FORCEINLINE_DEBUGGABLE bool GetAllowCPUAccess () const
virtual FString GetFriendlyName () const override
FORCEINLINE_DEBUGGABLE uint32 GetNumTexCoords () const
FORCEINLINE_DEBUGGABLE uint32 GetNumVertices () const
FORCEINLINE_DEBUGGABLE uint32 GetResourceSize () const
FORCEINLINE_DEBUGGABLE void * GetTangentData ()
FORCEINLINE_DEBUGGABLE const void * GetTangentData () const
int GetTangentSize () const
FRHIShaderResourceView * GetTangentsSRV () const
FORCEINLINE_DEBUGGABLE void * GetTexCoordData ()
FORCEINLINE_DEBUGGABLE const void * GetTexCoordData () const
int GetTexCoordSize () const
FRHIShaderResourceView * GetTexCoordsSRV () const
FORCEINLINE_DEBUGGABLE bool GetUseFullPrecisionUVs () const
FORCEINLINE_DEBUGGABLE bool GetUseHighPrecisionTangentBasis () const
FORCEINLINE_DEBUGGABLE FVector2f GetVertexUV (uint32 VertexIndex, uint32 UVIndex) const
Set the vertex UV values at the given index in the vertex buffer.
template<EStaticMeshVertexUVType UVTypeT>
FORCEINLINE_DEBUGGABLE FVector2f GetVertexUV_Typed (uint32 VertexIndex, uint32 UVIndex) const
void Init (const FConstMeshBuildVertexView &InVertices, bool bNeedsCPUAccess=true)
Initializes the buffer with the given vertices.
void Init (const FConstMeshBuildVertexView &InVertices, const FStaticMeshVertexBufferFlags &InInitFlags)
void Init (const FStaticMeshVertexBuffer &InVertexBuffer, bool bNeedsCPUAccess=true)
Initializes this vertex buffer with the contents of the given vertex buffer.
void Init (const TArray< FStaticMeshBuildVertex > &InVertices, uint32 InNumTexCoords, bool bNeedsCPUAccess=true)
void Init (const TArray< FStaticMeshBuildVertex > &InVertices, uint32 InNumTexCoords, const FStaticMeshVertexBufferFlags &InInitFlags)
Initializes the buffer with the given vertices.
void Init (uint32 InNumVertices, uint32 InNumTexCoords, bool bNeedsCPUAccess=true)
virtual void InitResource (FRHICommandListBase &RHICmdList) override
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForStreaming (FRHIBuffer *IntermediateTangentsBuffer, FRHIBuffer *IntermediateTexCoordBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
bool IsValid ()
void operator= (const FStaticMeshVertexBuffer &Other)
Specialized assignment operator, only used when importing LOD's.
virtual void ReleaseResource () override
Prepares the resource for deletion.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void Serialize (FArchive &Ar, bool bNeedsCPUAccess)
Serializer.
void SerializeMetaData (FArchive &Ar)
void SetMetaData (uint32 NumTexCoords, uint32 NumVertices, bool bUseFullPrecisionUVs, bool bUseHighPrecisionTangentBasis)
FORCEINLINE_DEBUGGABLE void SetUseFullPrecisionUVs (bool UseFull)
FORCEINLINE_DEBUGGABLE void SetUseHighPrecisionTangentBasis (bool bUseHighPrecision)
FORCEINLINE_DEBUGGABLE void SetVertexTangents (uint32 VertexIndex, FVector3f X, FVector3f Y, FVector3f Z)
FORCEINLINE_DEBUGGABLE void SetVertexUV (uint32 VertexIndex, uint32 UVIndex, const FVector2f &Vec2D, bool bUseBackwardsCompatibleF16TruncUVs=false)
Set the vertex UV values at the given index in the vertex buffer.
FORCEINLINE_DEBUGGABLE FVector4f VertexTangentX (uint32 VertexIndex) const
template<EStaticMeshVertexTangentBasisType TangentBasisTypeT>
FORCEINLINE_DEBUGGABLE FVector4f VertexTangentX_Typed (uint32 VertexIndex) const
FORCEINLINE_DEBUGGABLE FVector3f VertexTangentY (uint32 VertexIndex) const
Calculate the binormal (TangentY) vector using the normal,tangent vectors.
template<EStaticMeshVertexTangentBasisType TangentBasisTypeT>
FORCEINLINE_DEBUGGABLE FVector4f VertexTangentY_Typed (uint32 VertexIndex) const
FORCEINLINE_DEBUGGABLE FVector4f VertexTangentZ (uint32 VertexIndex) const
template<EStaticMeshVertexTangentBasisType TangentBasisTypeT>
FORCEINLINE_DEBUGGABLE FVector4f VertexTangentZ_Typed (uint32 VertexIndex) const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
FStaticMeshVertexBuffer::FTangentsVertexBuffer TangentsVertexBuffer
FStaticMeshVertexBuffer::FTexcoordVertexBuffer TexCoordVertexBuffer
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Private Member Functions
void AllocateData (bool bNeedsCPUAccess=true)
Allocates the vertex data storage type.
void ConvertHalfTexcoordsToFloat (const uint8 *InData)
Convert half float data to full float if the HW requires it.
void InitTangentAndTexCoordStrides ()
Private Attributes
bool bUseFullPrecisionUVs
Corresponds to UStaticMesh::UseFullPrecisionUVs.
bool bUseHighPrecisionTangentBasis
If true then RGB10A2 is used to store tangent else RGBA8.
bool NeedsCPUAccess = true
uint32 NumTexCoords
The number of texcoords/vertex in the buffer.
uint32 NumVertices
The cached number of vertices.
FStaticMeshVertexDataInterface * TangentsData
The vertex data storage type.
uint8 * TangentsDataPtr
The cached vertex data pointer.
FShaderResourceViewRHIRef TangentsSRV
uint32 TangentsStride
The cached Tangent stride.
FStaticMeshVertexDataInterface * TexcoordData
uint8 * TexcoordDataPtr
uint32 TexcoordStride
The cached Texcoord stride.
FShaderResourceViewRHIRef TextureCoordinatesSRV
Friends
class FStaticMeshVertexBuffer
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Vertex buffer for a static mesh LOD.
Definition at line 149 of file StaticMeshVertexBuffer.h.
Constructor & Destructor Documentation
FStaticMeshVertexBuffer()
FStaticMeshVertexBuffer::FStaticMeshVertexBuffer ()
Default constructor.
~FStaticMeshVertexBuffer()
FStaticMeshVertexBuffer::~FStaticMeshVertexBuffer ()
Destructor.
Member Function Documentation
AllocateData()
void FStaticMeshVertexBuffer::AllocateData (bool bNeedsCPUAccess = true) private
Allocates the vertex data storage type.
AppendVertices()
void FStaticMeshVertexBuffer::AppendVertices (const FStaticMeshBuildVertex * Vertices, const uint32 NumVerticesToAppend, bool bUseBackwardsCompatibleF16TruncUVs = false)
Appends the specified vertices to the end of the buffer.
Parameters
Vertices The vertex data to be appended. Must not be nullptr.
NumVerticesToAppend How many vertices should be added
bUseBackwardsCompatibleF16TruncUVs - Whether backwards compatible legacy truncation mode should be used for F16 UVs (default false)
BindLightMapVertexBuffer()
void FStaticMeshVertexBuffer::BindLightMapVertexBuffer (const FVertexFactory * VertexFactory, struct FStaticMeshDataType & Data, int LightMapCoordinateIndex) const
References LightMapCoordinateIndex, and VertexFactory.
BindPackedTexCoordVertexBuffer()
void FStaticMeshVertexBuffer::BindPackedTexCoordVertexBuffer (const FVertexFactory * VertexFactory, struct FStaticMeshDataType & Data, int32 MaxNumTexCoords = -1) const
References VertexFactory.
BindTangentVertexBuffer()
void FStaticMeshVertexBuffer::BindTangentVertexBuffer (const FVertexFactory * VertexFactory, struct FStaticMeshDataType & Data) const
References VertexFactory.
BindTexCoordVertexBuffer()
void FStaticMeshVertexBuffer::BindTexCoordVertexBuffer (const FVertexFactory * VertexFactory, struct FStaticMeshDataType & Data, int ClampedNumTexCoords = -1) const
References VertexFactory.
CleanUp()
void FStaticMeshVertexBuffer::CleanUp ()
Delete existing resources.
ClearMetaData()
void FStaticMeshVertexBuffer::ClearMetaData ()
ConvertHalfTexcoordsToFloat()
void FStaticMeshVertexBuffer::ConvertHalfTexcoordsToFloat (const uint8 * InData) private
Convert half float data to full float if the HW requires it.
Parameters
InData - optional half float source data to convert into full float texture coordinate buffer. if null, convert existing half float texture coordinates to a new float buffer.
CreateTangentsRHIBuffer()
FBufferRHIRef FStaticMeshVertexBuffer::CreateTangentsRHIBuffer (FRHICommandListBase & RHICmdList)
Create an RHI vertex buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
CreateTexCoordRHIBuffer()
FBufferRHIRef FStaticMeshVertexBuffer::CreateTexCoordRHIBuffer (FRHICommandListBase & RHICmdList)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
GetAllowCPUAccess()
FORCEINLINE_DEBUGGABLE bool FStaticMeshVertexBuffer::GetAllowCPUAccess () const inline
Definition at line 471 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, TangentsData, and TexcoordData.
GetFriendlyName()
virtual FString FStaticMeshVertexBuffer::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Definition at line 454 of file StaticMeshVertexBuffer.h.
References TEXT.
GetNumTexCoords()
FORCEINLINE_DEBUGGABLE uint32 FStaticMeshVertexBuffer::GetNumTexCoords () const inline
Definition at line 411 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, and NumTexCoords.
Referenced by GetResourceSize(), GetVertexUV(), GetVertexUV_Typed(), SetVertexUV(), and FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays().
GetNumVertices()
FORCEINLINE_DEBUGGABLE uint32 FStaticMeshVertexBuffer::GetNumVertices () const inline
Definition at line 406 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, and NumVertices.
Referenced by GetVertexUV(), SetVertexTangents(), SetVertexUV(), FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays(), FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays(), VertexTangentX(), VertexTangentY(), and VertexTangentZ().
GetResourceSize()
FORCEINLINE_DEBUGGABLE uint32 FStaticMeshVertexBuffer::GetResourceSize () const inline
Definition at line 436 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, GetNumTexCoords(), NumVertices, TangentsStride, and TexcoordStride.
GetTangentData() [1/2]
FORCEINLINE_DEBUGGABLE void * FStaticMeshVertexBuffer::GetTangentData () inline
Definition at line 461 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, and TangentsDataPtr.
GetTangentData() [2/2]
FORCEINLINE_DEBUGGABLE const void * FStaticMeshVertexBuffer::GetTangentData () const inline
Definition at line 462 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, and TangentsDataPtr.
GetTangentSize()
int FStaticMeshVertexBuffer::GetTangentSize () const
GetTangentsSRV()
FRHIShaderResourceView * FStaticMeshVertexBuffer::GetTangentsSRV () const inline
Definition at line 494 of file StaticMeshVertexBuffer.h.
References TangentsSRV.
GetTexCoordData() [1/2]
FORCEINLINE_DEBUGGABLE void * FStaticMeshVertexBuffer::GetTexCoordData () inline
Definition at line 464 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, and TexcoordDataPtr.
GetTexCoordData() [2/2]
FORCEINLINE_DEBUGGABLE const void * FStaticMeshVertexBuffer::GetTexCoordData () const inline
Definition at line 465 of file StaticMeshVertexBuffer.h.
References FORCEINLINE_DEBUGGABLE, and TexcoordDataPtr.
GetTexCoordSize()
int FStaticMeshVertexBuffer::GetTexCoordSize () const
GetTexCoordsSRV()
FRHIShaderResourceView * FStaticMeshVertexBuffer::GetTexCoordsSRV () const inline
Definition at line 495 of file StaticMeshVertexBuffer.h.
References TextureCoordinatesSRV.
GetUseFullPrecisionUVs()
FORCEINLINE_DEBUGGABLE bool FStaticMeshVertexBuffer::GetUseFullPrecisionUVs () const inline
Definition at line 416 of file StaticMeshVertexBuffer.h.
References bUseFullPrecisionUVs, and FORCEINLINE_DEBUGGABLE.
Referenced by GetVertexUV(), and SetVertexUV().
GetUseHighPrecisionTangentBasis()
FORCEINLINE_DEBUGGABLE bool FStaticMeshVertexBuffer::GetUseHighPrecisionTangentBasis () const inline
Definition at line 426 of file StaticMeshVertexBuffer.h.
References bUseHighPrecisionTangentBasis, and FORCEINLINE_DEBUGGABLE.
Referenced by SetVertexTangents(), VertexTangentX(), VertexTangentY(), and VertexTangentZ().
GetVertexUV()
FORCEINLINE_DEBUGGABLE FVector2f FStaticMeshVertexBuffer::GetVertexUV (uint32 VertexIndex, uint32 UVIndex) const inline
Set the vertex UV values at the given index in the vertex buffer.
Parameters
VertexIndex - index into the vertex buffer
UVIndex - [0,MAX_STATIC_TEXCOORDS] value to index into UVs array
2D UV values
Definition at line 391 of file StaticMeshVertexBuffer.h.
References checkSlow, FORCEINLINE_DEBUGGABLE, GetNumTexCoords(), GetNumVertices(), GetUseFullPrecisionUVs(), and GetVertexUV_Typed().
GetVertexUV_Typed()
template<EStaticMeshVertexUVType UVTypeT> FORCEINLINE_DEBUGGABLE FVector2f FStaticMeshVertexBuffer::GetVertexUV_Typed (uint32 VertexIndex, uint32 UVIndex) const inline
Definition at line 373 of file StaticMeshVertexBuffer.h.
References check, FORCEINLINE_DEBUGGABLE, GetNumTexCoords(), TexcoordData, and TexcoordDataPtr.
Referenced by GetVertexUV().
Init() [1/6]
void FStaticMeshVertexBuffer::Init (const FConstMeshBuildVertexView & InVertices, bool bNeedsCPUAccess = true) inline
Initializes the buffer with the given vertices.
Parameters
InVertices - The vertices to initialize the buffer with.
InNumTexCoords - The number of texture coordinate to store in the buffer.
bNeedsCPUAccess - Whether the vertex data needs to be accessed by the CPU after creation (default true)
Definition at line 181 of file StaticMeshVertexBuffer.h.
References Flags, and Init.
Init() [2/6]
void FStaticMeshVertexBuffer::Init (const FConstMeshBuildVertexView & InVertices, const FStaticMeshVertexBufferFlags & InInitFlags)
Init() [3/6]
void FStaticMeshVertexBuffer::Init (const FStaticMeshVertexBuffer & InVertexBuffer, bool bNeedsCPUAccess = true)
Initializes this vertex buffer with the contents of the given vertex buffer.
Parameters
InVertexBuffer - The vertex buffer to initialize from.
bNeedsCPUAccess - Whether the vertex data needs to be accessed by the CPU after creation (default true)
References FStaticMeshVertexBuffer.
Init() [4/6]
void FStaticMeshVertexBuffer::Init (const TArray< FStaticMeshBuildVertex > & InVertices, uint32 InNumTexCoords, bool bNeedsCPUAccess = true) inline
Definition at line 188 of file StaticMeshVertexBuffer.h.
References Flags, Init, and MakeConstMeshBuildVertexView().
Init() [5/6]
void FStaticMeshVertexBuffer::Init (const TArray< FStaticMeshBuildVertex > & InVertices, uint32 InNumTexCoords, const FStaticMeshVertexBufferFlags & InInitFlags)
Initializes the buffer with the given vertices.
Parameters
InVertices - The vertices to initialize the buffer with.
InNumTexCoords - The number of texture coordinate to store in the buffer.
Flags - Options for Init ; FStaticMeshVertexBufferFlags can be default constructed for default options
Init() [6/6]
void FStaticMeshVertexBuffer::Init (uint32 InNumVertices, uint32 InNumTexCoords, bool bNeedsCPUAccess = true)
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays().
InitResource()
virtual void FStaticMeshVertexBuffer::InitResource (FRHICommandListBase & RHICmdList) override virtual
Initializes the resource.
This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHI()
virtual void FStaticMeshVertexBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FStaticMeshVertexBuffer::InitRHIForStreaming (FRHIBuffer * IntermediateTangentsBuffer, FRHIBuffer * IntermediateTexCoordBuffer, FRHIResourceReplaceBatcher & Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
InitTangentAndTexCoordStrides()
void FStaticMeshVertexBuffer::InitTangentAndTexCoordStrides () private
IsValid()
bool FStaticMeshVertexBuffer::IsValid () inline
Definition at line 489 of file StaticMeshVertexBuffer.h.
References IsValidRef(), TangentsVertexBuffer, and TexCoordVertexBuffer.
operator=()
void FStaticMeshVertexBuffer::operator= (const FStaticMeshVertexBuffer & Other)
Specialized assignment operator, only used when importing LOD's.
References FStaticMeshVertexBuffer, and Other.
ReleaseResource()
virtual void FStaticMeshVertexBuffer::ReleaseResource () override virtual
Prepares the resource for deletion.
This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHI()
virtual void FStaticMeshVertexBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
ReleaseRHIForStreaming()
void FStaticMeshVertexBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
Serialize()
void FStaticMeshVertexBuffer::Serialize (FArchive & Ar, bool bNeedsCPUAccess)
Serializer.
Parameters
Ar Archive to serialize with
bNeedsCPUAccess Whether the elements need to be accessed by the CPU
References Ar.
SerializeMetaData()
void FStaticMeshVertexBuffer::SerializeMetaData (FArchive & Ar)
References Ar.
SetMetaData()
void FStaticMeshVertexBuffer::SetMetaData (uint32 NumTexCoords, uint32 NumVertices, bool bUseFullPrecisionUVs, bool bUseHighPrecisionTangentBasis)
References bUseFullPrecisionUVs, bUseHighPrecisionTangentBasis, NumTexCoords, and NumVertices.
SetUseFullPrecisionUVs()
FORCEINLINE_DEBUGGABLE void FStaticMeshVertexBuffer::SetUseFullPrecisionUVs (bool UseFull) inline
Definition at line 421 of file StaticMeshVertexBuffer.h.
References bUseFullPrecisionUVs, and FORCEINLINE_DEBUGGABLE.
SetUseHighPrecisionTangentBasis()
FORCEINLINE_DEBUGGABLE void FStaticMeshVertexBuffer::SetUseHighPrecisionTangentBasis (bool bUseHighPrecision) inline
Definition at line 431 of file StaticMeshVertexBuffer.h.
References bUseHighPrecisionTangentBasis, and FORCEINLINE_DEBUGGABLE.
SetVertexTangents()
FORCEINLINE_DEBUGGABLE void FStaticMeshVertexBuffer::SetVertexTangents (uint32 VertexIndex, FVector3f X, FVector3f Y, FVector3f Z) inline
Definition at line 309 of file StaticMeshVertexBuffer.h.
References check, checkSlow, FORCEINLINE_DEBUGGABLE, GetNumVertices(), GetUseHighPrecisionTangentBasis(), TangentsData, TangentsDataPtr, X, Y, and Z.
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
SetVertexUV()
FORCEINLINE_DEBUGGABLE void FStaticMeshVertexBuffer::SetVertexUV (uint32 VertexIndex, uint32 UVIndex, const FVector2f & Vec2D, bool bUseBackwardsCompatibleF16TruncUVs = false) inline
Set the vertex UV values at the given index in the vertex buffer.
Parameters
VertexIndex - index into the vertex buffer
UVIndex - [0,MAX_STATIC_TEXCOORDS] value to index into UVs array
Vec2D - UV values to set
bUseBackwardsCompatibleF16TruncUVs - whether backwards compatible Truncate mode is used for F32 to F16 conversion
Definition at line 339 of file StaticMeshVertexBuffer.h.
References check, checkSlow, FORCEINLINE_DEBUGGABLE, GetNumTexCoords(), GetNumVertices(), GetUseFullPrecisionUVs(), FVector2DHalf::SetTruncate(), TexcoordData, and TexcoordDataPtr.
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexUVBufferFromOverlays().
VertexTangentX()
FORCEINLINE_DEBUGGABLE FVector4f FStaticMeshVertexBuffer::VertexTangentX (uint32 VertexIndex) const inline
Definition at line 241 of file StaticMeshVertexBuffer.h.
References checkSlow, FORCEINLINE_DEBUGGABLE, GetNumVertices(), GetUseHighPrecisionTangentBasis(), and VertexTangentX_Typed().
VertexTangentX_Typed()
template<EStaticMeshVertexTangentBasisType TangentBasisTypeT> FORCEINLINE_DEBUGGABLE FVector4f FStaticMeshVertexBuffer::VertexTangentX_Typed (uint32 VertexIndex) const inline
Definition at line 232 of file StaticMeshVertexBuffer.h.
References check, FORCEINLINE_DEBUGGABLE, TangentsData, and TangentsDataPtr.
Referenced by VertexTangentX().
VertexTangentY()
FORCEINLINE_DEBUGGABLE FVector3f FStaticMeshVertexBuffer::VertexTangentY (uint32 VertexIndex) const inline
Calculate the binormal (TangentY) vector using the normal,tangent vectors.
Parameters
VertexIndex - index into the vertex buffer
Returns
binormal (TangentY) vector
Definition at line 295 of file StaticMeshVertexBuffer.h.
References checkSlow, FORCEINLINE_DEBUGGABLE, GetNumVertices(), GetUseHighPrecisionTangentBasis(), and VertexTangentY_Typed().
VertexTangentY_Typed()
template<EStaticMeshVertexTangentBasisType TangentBasisTypeT> FORCEINLINE_DEBUGGABLE FVector4f FStaticMeshVertexBuffer::VertexTangentY_Typed (uint32 VertexIndex) const inline
Definition at line 280 of file StaticMeshVertexBuffer.h.
References check, FORCEINLINE_DEBUGGABLE, TangentsData, and TangentsDataPtr.
Referenced by VertexTangentY().
VertexTangentZ()
FORCEINLINE_DEBUGGABLE FVector4f FStaticMeshVertexBuffer::VertexTangentZ (uint32 VertexIndex) const inline
Definition at line 265 of file StaticMeshVertexBuffer.h.
References checkSlow, FORCEINLINE_DEBUGGABLE, GetNumVertices(), GetUseHighPrecisionTangentBasis(), and VertexTangentZ_Typed().
VertexTangentZ_Typed()
template<EStaticMeshVertexTangentBasisType TangentBasisTypeT> FORCEINLINE_DEBUGGABLE FVector4f FStaticMeshVertexBuffer::VertexTangentZ_Typed (uint32 VertexIndex) const inline
Definition at line 256 of file StaticMeshVertexBuffer.h.
References check, FORCEINLINE_DEBUGGABLE, TangentsData, and TangentsDataPtr.
Referenced by VertexTangentZ().
Friends And Related Symbol Documentation
FStaticMeshVertexBuffer
friend class FStaticMeshVertexBuffer friend
Definition at line 151 of file StaticMeshVertexBuffer.h.
References FStaticMeshVertexBuffer.
Referenced by FStaticMeshVertexBuffer, Init(), and operator=().
Field Documentation
bUseFullPrecisionUVs
bool FStaticMeshVertexBuffer::bUseFullPrecisionUVs private
Corresponds to UStaticMesh::UseFullPrecisionUVs.
if true then 32 bit UVs are used
Definition at line 522 of file StaticMeshVertexBuffer.h.
Referenced by GetUseFullPrecisionUVs(), SetMetaData(), and SetUseFullPrecisionUVs().
bUseHighPrecisionTangentBasis
bool FStaticMeshVertexBuffer::bUseHighPrecisionTangentBasis private
If true then RGB10A2 is used to store tangent else RGBA8.
Definition at line 525 of file StaticMeshVertexBuffer.h.
Referenced by GetUseHighPrecisionTangentBasis(), SetMetaData(), and SetUseHighPrecisionTangentBasis().
NeedsCPUAccess
bool FStaticMeshVertexBuffer::NeedsCPUAccess = true private
Definition at line 527 of file StaticMeshVertexBuffer.h.
NumTexCoords
uint32 FStaticMeshVertexBuffer::NumTexCoords private
The number of texcoords/vertex in the buffer.
Definition at line 516 of file StaticMeshVertexBuffer.h.
Referenced by GetNumTexCoords(), and SetMetaData().
NumVertices
uint32 FStaticMeshVertexBuffer::NumVertices private
The cached number of vertices.
Definition at line 519 of file StaticMeshVertexBuffer.h.
Referenced by GetNumVertices(), GetResourceSize(), and SetMetaData().
TangentsData
FStaticMeshVertexDataInterface* FStaticMeshVertexBuffer::TangentsData private
The vertex data storage type.
Definition at line 499 of file StaticMeshVertexBuffer.h.
Referenced by GetAllowCPUAccess(), SetVertexTangents(), VertexTangentX_Typed(), VertexTangentY_Typed(), and VertexTangentZ_Typed().
TangentsDataPtr
uint8* FStaticMeshVertexBuffer::TangentsDataPtr private
The cached vertex data pointer.
Definition at line 506 of file StaticMeshVertexBuffer.h.
Referenced by GetTangentData(), GetTangentData(), SetVertexTangents(), VertexTangentX_Typed(), VertexTangentY_Typed(), and VertexTangentZ_Typed().
TangentsSRV
FShaderResourceViewRHIRef FStaticMeshVertexBuffer::TangentsSRV private
Definition at line 500 of file StaticMeshVertexBuffer.h.
Referenced by GetTangentsSRV().
TangentsStride
uint32 FStaticMeshVertexBuffer::TangentsStride mutable private
The cached Tangent stride.
Definition at line 510 of file StaticMeshVertexBuffer.h.
Referenced by GetResourceSize().
TangentsVertexBuffer
FStaticMeshVertexBuffer::FTangentsVertexBuffer FStaticMeshVertexBuffer::TangentsVertexBuffer
Referenced by IsValid().
TexcoordData
FStaticMeshVertexDataInterface* FStaticMeshVertexBuffer::TexcoordData private
Definition at line 502 of file StaticMeshVertexBuffer.h.
Referenced by GetAllowCPUAccess(), GetVertexUV_Typed(), and SetVertexUV().
TexcoordDataPtr
uint8* FStaticMeshVertexBuffer::TexcoordDataPtr private
Definition at line 507 of file StaticMeshVertexBuffer.h.
Referenced by GetTexCoordData(), GetTexCoordData(), GetVertexUV_Typed(), and SetVertexUV().
TexcoordStride
uint32 FStaticMeshVertexBuffer::TexcoordStride mutable private
The cached Texcoord stride.
Definition at line 513 of file StaticMeshVertexBuffer.h.
Referenced by GetResourceSize().
TexCoordVertexBuffer
FStaticMeshVertexBuffer::FTexcoordVertexBuffer FStaticMeshVertexBuffer::TexCoordVertexBuffer
Referenced by IsValid().
TextureCoordinatesSRV
FShaderResourceViewRHIRef FStaticMeshVertexBuffer::TextureCoordinatesSRV private
Definition at line 503 of file StaticMeshVertexBuffer.h.
Referenced by GetTexCoordsSRV().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/StaticMeshVertexBuffer.h