Unreal Engine 5.6 C++ API: TAlignedHeapAllocator< Alignment >::ForAnyElementType Class Reference
TAlignedHeapAllocator< Alignment >::ForAnyElementType Class Reference
#include "ContainerAllocationPolicies.h"
Public Member Functions
ForAnyElementType ()
Default constructor.
FORCEINLINE ~ForAnyElementType ()
Destructor.
FORCEINLINE SizeType CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const
FORCEINLINE SizeType CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const
SIZE_T GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const
FORCEINLINE FScriptContainerElement * GetAllocation () const
SizeType GetInitialCapacity () const
bool HasAllocation () const
FORCEINLINE void MoveToEmpty (ForAnyElementType &Other)
Moves the state of another allocator into this one.
void ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement)
Private Member Functions
ForAnyElementType (const ForAnyElementType &)
ForAnyElementType & operator= (const ForAnyElementType &)
Private Attributes
FScriptContainerElement * Data
A pointer to the container's elements.
Detailed Description
template<uint32 Alignment = DEFAULT_ALIGNMENT>
class TAlignedHeapAllocator< Alignment >::ForAnyElementType
Definition at line 460 of file ContainerAllocationPolicies.h.
Constructor & Destructor Documentation
ForAnyElementType() [1/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> TAlignedHeapAllocator< Alignment >::ForAnyElementType::ForAnyElementType () inline
Default constructor.
Definition at line 465 of file ContainerAllocationPolicies.h.
References Data.
Referenced by ForAnyElementType(), MoveToEmpty(), and operator=().
~ForAnyElementType()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE TAlignedHeapAllocator< Alignment >::ForAnyElementType::~ForAnyElementType () inline
Destructor.
Definition at line 492 of file ContainerAllocationPolicies.h.
References Data, FORCEINLINE, and FMemory::Free().
ForAnyElementType() [2/2]
template<uint32 Alignment = DEFAULT_ALIGNMENT> TAlignedHeapAllocator< Alignment >::ForAnyElementType::ForAnyElementType (const ForAnyElementType &) private
References ForAnyElementType().
Member Function Documentation
CalculateSlackGrow()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE SizeType TAlignedHeapAllocator< Alignment >::ForAnyElementType::CalculateSlackGrow (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 541 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackGrow(), and FORCEINLINE.
CalculateSlackReserve()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE SizeType TAlignedHeapAllocator< Alignment >::ForAnyElementType::CalculateSlackReserve (SizeType NewMax, SIZE_T NumBytesPerElement) const inline
Definition at line 533 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackReserve(), and FORCEINLINE.
CalculateSlackShrink()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE SizeType TAlignedHeapAllocator< Alignment >::ForAnyElementType::CalculateSlackShrink (SizeType NewMax, SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 537 of file ContainerAllocationPolicies.h.
References DefaultCalculateSlackShrink(), and FORCEINLINE.
GetAllocatedSize()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SIZE_T TAlignedHeapAllocator< Alignment >::ForAnyElementType::GetAllocatedSize (SizeType CurrentMax, SIZE_T NumBytesPerElement) const inline
Definition at line 546 of file ContainerAllocationPolicies.h.
GetAllocation()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE FScriptContainerElement * TAlignedHeapAllocator< Alignment >::ForAnyElementType::GetAllocation () const inline
Definition at line 505 of file ContainerAllocationPolicies.h.
References Data, and FORCEINLINE.
Referenced by TAlignedHeapAllocator< Alignment >::ForElementType< ElementType >::GetAllocation().
GetInitialCapacity()
template<uint32 Alignment = DEFAULT_ALIGNMENT> SizeType TAlignedHeapAllocator< Alignment >::ForAnyElementType::GetInitialCapacity () const inline
Definition at line 556 of file ContainerAllocationPolicies.h.
HasAllocation()
template<uint32 Alignment = DEFAULT_ALIGNMENT> bool TAlignedHeapAllocator< Alignment >::ForAnyElementType::HasAllocation () const inline
Definition at line 551 of file ContainerAllocationPolicies.h.
References Data.
MoveToEmpty()
template<uint32 Alignment = DEFAULT_ALIGNMENT> FORCEINLINE void TAlignedHeapAllocator< Alignment >::ForAnyElementType::MoveToEmpty (ForAnyElementType & Other) inline
Moves the state of another allocator into this one.
Assumes that the allocator is currently empty, i.e. memory may be allocated but any existing elements have already been destructed (if necessary).
Parameters
Other - The allocator to move the state from. This allocator should be left in a valid empty state.
Definition at line 474 of file ContainerAllocationPolicies.h.
References ForAnyElementType(), checkSlow, Data, FORCEINLINE, FMemory::Free(), and Other.
operator=()
template<uint32 Alignment = DEFAULT_ALIGNMENT> ForAnyElementType & TAlignedHeapAllocator< Alignment >::ForAnyElementType::operator= (const ForAnyElementType &) private
References ForAnyElementType().
ResizeAllocation()
template<uint32 Alignment = DEFAULT_ALIGNMENT> void TAlignedHeapAllocator< Alignment >::ForAnyElementType::ResizeAllocation (SizeType CurrentNum, SizeType NewMax, SIZE_T NumBytesPerElement) inline
Definition at line 509 of file ContainerAllocationPolicies.h.
References Data, MAX_int32, UE::Core::Private::OnInvalidAlignedHeapAllocatorNum(), and UNLIKELY.
Field Documentation
Data
template<uint32 Alignment = DEFAULT_ALIGNMENT> FScriptContainerElement* TAlignedHeapAllocator< Alignment >::ForAnyElementType::Data private
A pointer to the container's elements.
Definition at line 580 of file ContainerAllocationPolicies.h.
Referenced by ForAnyElementType(), ~ForAnyElementType(), GetAllocation(), HasAllocation(), MoveToEmpty(), and ResizeAllocation().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/ContainerAllocationPolicies.h