Unreal Engine 5.6 C++ API: FDisplayedBoneMappingInfo Class Reference
FDisplayedBoneMappingInfo Class Reference
#include "SBoneMappingBase.h"
Public Member Functions
FString GetDisplayName () const
FName GetNodeName () const
Static Public Member Functions
static TSharedRef< FDisplayedBoneMappingInfo > Make (const FName NodeName, const FString DisplayName)
Static function for creating a new item, but ensures that you can only have a TSharedRef to one.
Data Fields
FString DisplayName
FName Name
Protected Member Functions
FDisplayedBoneMappingInfo ()
Hidden constructor, always use Make above.
FDisplayedBoneMappingInfo (const FName InNodeName, const FString InDisplayName)
Hidden constructor, always use Make above.
Detailed Description
Definition at line 24 of file SBoneMappingBase.h.
Constructor & Destructor Documentation
FDisplayedBoneMappingInfo() [1/2]
FDisplayedBoneMappingInfo::FDisplayedBoneMappingInfo (const FName InNodeName, const FString InDisplayName) inline protected
Hidden constructor, always use Make above.
Definition at line 48 of file SBoneMappingBase.h.
References DisplayName, and Name.
FDisplayedBoneMappingInfo() [2/2]
FDisplayedBoneMappingInfo::FDisplayedBoneMappingInfo () inline protected
Hidden constructor, always use Make above.
Definition at line 54 of file SBoneMappingBase.h.
Referenced by Make().
Member Function Documentation
GetDisplayName()
FString FDisplayedBoneMappingInfo::GetDisplayName () const inline
Definition at line 41 of file SBoneMappingBase.h.
References DisplayName.
GetNodeName()
FName FDisplayedBoneMappingInfo::GetNodeName () const inline
Definition at line 36 of file SBoneMappingBase.h.
References Name.
Make()
TSharedRef< FDisplayedBoneMappingInfo > FDisplayedBoneMappingInfo::Make (const FName NodeName, const FString DisplayName) inline static
Static function for creating a new item, but ensures that you can only have a TSharedRef to one.
Definition at line 31 of file SBoneMappingBase.h.
References FDisplayedBoneMappingInfo(), DisplayName, and MakeShareable().
Field Documentation
DisplayName
FString FDisplayedBoneMappingInfo::DisplayName
Definition at line 28 of file SBoneMappingBase.h.
Referenced by FDisplayedBoneMappingInfo(), GetDisplayName(), and Make().
Name
FName FDisplayedBoneMappingInfo::Name
Definition at line 27 of file SBoneMappingBase.h.
Referenced by FDisplayedBoneMappingInfo(), and GetNodeName().
The documentation for this class was generated from the following file:
Editor/Persona/Public/SBoneMappingBase.h